### ISSUE TITLE
"once" in event listener option

### ISSUE THREAD

**Issue by sqal** [vuetifyjs/vuetify#1]
I have noticed that here [L72](https://github.com/vuetifyjs/vuetify/blob/master/src/components/sidebar/SidebarGroup.vue#L72) you're using `once` option in addEventListener function. The thing is. This option is not well supported as you can see here - http://caniuse.com/#feat=once-event-listener so in many browsers, added event listeners like this are not going to remove themselves, so you're going to have memory leak right there.  It's worth to refactor.

**Comment by johnleider** [comment]
Resolved with commit [b369f0](https://github.com/vuetifyjs/vuetify/commit/b369f03f1c3805700c7a7902258b0ce087e0f58f).
