### ISSUE TITLE
[Bug Report] Issue with v-data-table, when you create table using v-for

### ISSUE THREAD

**Issue by sidnaik03** [vuetifyjs/vuetify#10005]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Linux x86_64

### Steps to reproduce
Write down below code 
<v-flex xs12 style="margin:1%;" v-for="tbl in mainDataList" :key="tbl"> 
<v-data-table dense v-model="tbl.selected" :multi-sort="true" :headers="tbl.headers" :items="tbl.items" item-key="tbl.name" show-select class="elevation-1" > 
</v-data-table>
 </v-flex>

### Expected Behavior
If I select one row from the table,it should select that row only

### Actual Behavior
Selecting all rows even if I select single row from the table

### Reproduction Link
<a href="https://codepen.io/sidnaik03/pen/qBERVXo" target="_blank">https://codepen.io/sidnaik03/pen/qBERVXo</a>

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/BaypmPa
