### ISSUE TITLE
[Bug Report] TextField maxlength ignored on type="number"

### ISSUE THREAD

**Issue by katerlouis** [vuetifyjs/vuetify#10006]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OSX

### Steps to reproduce
Apparently it's the combination of a counter and `type="number"` that causes maxlength to be ignored. 

### Expected Behavior
You shouldn't be able to input more characters than in `maxlength` defined

### Actual Behavior
you can input more characters than in `maxlength` defined

### Reproduction Link
<a href="https://codepen.io/katerlouis/pen/YzPNYoW" target="_blank">https://codepen.io/katerlouis/pen/YzPNYoW</a>

### Other comments
This isn't the case if you ommit the `type` or change the type to `email`, for instance.

**Comment by MajesticPotatoe** [comment]
`maxlength` is ignored by `type="number"` by design
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength

**Comment by katerlouis** [comment]
Very interesting; thank you!

**Comment by MajesticPotatoe** [comment]
`min` + `max` as you are dealing with a number.
