### ISSUE TITLE
[Bug Report] V-avatar with lazy images is laggy/buggy

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#10000]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Check the codepen link

### Expected Behavior
An avatar with a blurred lazy loaded image within it's containers

### Actual Behavior
The blurred image is blurred and nice has a nice border-radius but when the actual image is loaded the border-radius is ignored for a second which looks really buggy

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/NWPdpgg" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/NWPdpgg</a>

### Other comments
I think just an `overflow:hidden` on the `.v-avatar`

**Comment by johnleider** [comment]
I cannot reproduce this: 
![avatar](https://user-images.githubusercontent.com/9064066/71099670-4922d380-2179-11ea-9ab3-d67404e55937.gif)

**Comment by YipingRuan** [comment]
@johnleider maybe there is a short moment the round clipping is not there?
![clip](https://user-images.githubusercontent.com/5492274/71147839-f9b9d180-2264-11ea-81ed-fc2ce3621138.gif)

**Comment by ricardovanlaarhoven** [comment]
@johnleider perhaps you have a faster pc or network connection, the result i get is indeed the same as @YipingRuan 's gif

**Comment by qm3ster** [comment]
What a waste of issue #10000
