### ISSUE TITLE
v-bottom-nav is pushed off to side when drawers are open

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#1000]
### Steps to reproduce
Create a page with a bottom nav and a persistent or permanent navigation drawer, and toggle the drawer. the v-bottom-nav is pushed to the side and as result, the buttons within are pushed with it.

### Versions

Vue 2.4, Vuetufy 0.13.1

### What is expected ?

The nav should re-adjust to its new parameters and the buttons within should realign with the new available space.

### What is actually happening ?

The whole v-bottom-nav elements gets pushed to the side pushing part of it off the screen

### Reproduction Link

https://codepen.io/anon/pen/vZMNKW

###Possible solution:
Using CSS selectors the same way that main and toolbar are selected for navigation drawers to add the following styles when the drawers are open (respective to the drawers open)
left: 0
padding-left/right: 300px

This should then act the same way as the toolbar component and the main tag.

**Comment by johnleider** [comment]
You are placing the v-bottom-nav inside of the main element. This element reacts to changes in the sidebar and even though the bottom-nav is fixed, it still inherits these changes from its parent. If you do not want this behavior you have a few options.

Place the v-bottom-nav outside of main, preferably on the same level as the other application level elements. Or, place it inside a container and set it to absolute mode.
