### ISSUE TITLE
[Feature Request] textarea max-height

### ISSUE THREAD

**Issue by MarkYarchak** [vuetifyjs/vuetify#10009]
### Problem to solve
In the textarea component auto-grow attribute is present, but there is no max-height for textarea field so it grows endlessly

### Proposed solution
Please add to Vuetify new attribute for textarea like this [vue-textarea-autosize](https://www.npmjs.com/package/vue-textarea-autosize) or recommend a solution for me. Thanks

**Comment by zachu90** [comment]
When is this going live?

**Comment by ximzavivka** [comment]
I'm also waiting for this feature. Because for now it is impossible to have infinite growing textarea

**Comment by zachu90** [comment]
@ximzavivka I found the workaround to achieve this until proper solution is released. The workaround is to use `max-height` css property on the textarea. Here is the example: 

[CodePen](https://codepen.io/kidplama/pen/MWejybN)

```
<v-textarea
  id="chat-message-typer-textarea"
  v-model="message"
  rows="1"
  auto-grow
></v-textarea>

#chat-message-typer-textarea {
  max-height: 115px;
  overflow-y: auto;
}

```

**Comment by HersonHN** [comment]
I also had this problem, since I'm using scss on my project I wrote this: 

```html
<v-textarea
  class="chat-compose-input"
  v-model="message"
  rows="1"
  auto-grow
/>
```

```scss
.chat-compose-input::v-deep {
  textarea {
    max-height: 7rem;
    overflow: auto;
  }
}
```

But I would really like a max-height attribute as well

**Comment by Sergezdv** [comment]
sdf sdf sdf sd

**Comment by alex02563** [comment]
thx

> I also had this problem, since I'm using scss on my project I wrote this:
> 
> ```
> <v-textarea
>   class="chat-compose-input"
>   v-model="message"
>   rows="1"
>   auto-grow
> />
> ```
> 
> ```css-scss
> .chat-compose-input::v-deep {
>   textarea {
>     max-height: 7rem;
>     overflow: auto;
>   }
> }
> ```
> 
> But I would really like a max-height attribute as well

幫助很大感謝!

**Comment by simonklimek** [comment]
Does the official solution is live now? It doesn't seems it works for me max-rows neither max-height on v-textarea with auto-grow.
