### ISSUE TITLE
[Documentation] add "events" tab to v-btn documentation

### ISSUE THREAD

**Issue by alexey2baranov** [vuetifyjs/vuetify#10004]
### Environment

**Browsers:** Chrome 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
open page https://vuetifyjs.com/en/components/buttons#buttons

### Expected Behavior
list of events of v-btn

### Actual Behavior
no event list of v-btn

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons#buttons" target="_blank">https://vuetifyjs.com/en/components/buttons#buttons</a>

**Comment by MajesticPotatoe** [comment]
resolved in 052ee15
