### ISSUE TITLE
[Bug Report] Full width text field has bottom border

### ISSUE THREAD

**Issue by jscottsf** [vuetifyjs/vuetify#10016]
### Environment
**Vuetify Version:** 2.1.15
**Last working version:** 2.1.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create a full width text field:

```
        <v-text-field
          v-model.trim="search"
          append-icon="search"
          clearable
          full-width
          hide-details
          label="Search"
          single-line
        ></v-text-field>
```

### Expected Behavior
No underline should be shown on full width fields. This is verified/desired behavior based on a previously resolved GitHub issue and the fact that the docs demonstrate using a divider to create a line between full width fields.

### Actual Behavior
An underline is shown.

### Reproduction Link
<a href="https://codepen.io/jscottsf/pen/ExaWNQa" target="_blank">https://codepen.io/jscottsf/pen/ExaWNQa</a>

**Comment by johnleider** [comment]
This style was changed in MD2, https://material-components.github.io/material-components-web-catalog/#/component/text-field

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
