### ISSUE TITLE
[Bug Report] VCard inside VCarousel applied dark theme 

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#10015]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
-

### Expected Behavior
vcard is light theme

### Actual Behavior
vcard is dark theme

### Reproduction Link
<a href="https://codepen.io/aldarund/pen/YzPZGxm?&editable=true&editors=101" target="_blank">https://codepen.io/aldarund/pen/YzPZGxm?&editable=true&editors=101</a>

### Other comments
Even if :dark=false it still applies dark theme, and by default it also applies dark instead of light

**Comment by johnleider** [comment]
The way carousel handles dark is wrong. While it supposed to be the default, it should be done through setting the default value of **dark** to true.

**Comment by bad4iz** [comment]
Duplicate of #8392

**Comment by PriimeTime** [comment]
Would be really good if this was finally fixed, just saying.

**Comment by sugoidesune** [comment]
Yes please. This cost me an hour of looking for the error on my side haha
