### ISSUE TITLE
[Bug Report] VSpeedDial transition only works with v-btn and v-tooltip

### ISSUE THREAD

**Issue by Aukemid** [vuetifyjs/vuetify#10019]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.15.2

### Steps to reproduce
Hover over the FAB in the reproduction link. The transition-delay is added to the v-btn components but not to the v-icon components in this example.

### Expected Behavior
The transition-delay should be applied to all children.

### Actual Behavior
The transition-delay is only applied to v-btn and v-tooltip components.

### Reproduction Link
<a href="https://codepen.io/Aukemid/pen/NWPpLqG" target="_blank">https://codepen.io/Aukemid/pen/NWPpLqG</a>

### Other comments
This limitation is hardcoded into the VSpeedDial.render function and I don't know why. If the transition-delay could cause problems the developer should consider, those should be explained in the docs.

I've used v-icon's in the reproduction example, but I ran into this problem with custom components that extend v-btn and v-tooltip. Most components wouldn't make sense as speed dial children. If there is a good reason for this limitation the if condition could be changed to support extended components.

**Comment by vintprox** [comment]
So happens, it doesn't even work with `v-tooltip`, d'oh.

**Comment by johnleider** [comment]
I'm going to push this off of 2.2 for now as the component needs a pretty heavy refactor to support this properly.

**Comment by johnleider** [comment]
Due to limited bandwidth we were unable to progress on this for v2, moving to v3.

**Comment by johnleider** [comment]
Unfortunately this is being pushed to a labs release later this year. Sorry for an inconvenience.

**Comment by johnleider** [comment]
We no longer manually add a transition delay for children elements. [v3 speed dial](https://vuetifyjs.com/en/components/speed-dials/#installation)
