### ISSUE TITLE
[Feature Request] auto suggest password does not work (autocomplete="new-password")

### ISSUE THREAD

**Issue by faisalhakim47** [vuetifyjs/vuetify#10012]
### Problem to solve
I want to implement something like this. But it seems like vuetify have not yet support it.

https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

```html
<v-text-field label="Password" name="password" type="password" autocomplete="new-password"/>
```

With code above vuetify should be able to automaticly inject the autocomplete attribute to the input element.

### Proposed solution
add autocomplete prop to v-text-field

**Comment by KaelWD** [comment]
It already does pass the attribute down. If the browser doesn't respond to it there's nothing we can do.
