### ISSUE TITLE
[Bug Report] Slider 'input' event is fired on component initialization

### ISSUE THREAD

**Issue by attez** [vuetifyjs/vuetify#10018]
### Environment
**Vuetify Version:** 2.2.0-beta.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1. Create a slider component (v-slider)
2. Attach an event handler to 'input' event

### Expected Behavior
The slider component is initialized and the attached event handler is not called.

### Actual Behavior
When the component is initialized the event handler is called without any user interaction.

### Reproduction Link
<a href="https://codepen.io/attez/pen/xxbqjmB" target="_blank">https://codepen.io/attez/pen/xxbqjmB</a>

### Other comments
I think the reason for this behavior is that on the beforeMounted hook of the component its internal value is set on [line 226](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSlider/VSlider.ts#L226) and then the setter of this internal value emits the input event on [line 127](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSlider/VSlider.ts#L127).

**Comment by KaelWD** [comment]
3b8c53d5eed76f6d3ee8c5af81f10c19f10c17c8

beforeMount and immediate do not have the same behaviour, and I don't know why that was done in the first place instead of inheriting VInput's initialisation in data.
