### ISSUE TITLE
[Feature Request] Vue 3 support

### ISSUE THREAD

**Issue by mrts** [vuetifyjs/vuetify#10025]
### Problem to solve
Vue 3 is looking to be an impressive release: leaner, faster and the composition API looks really sweet. Now that the [alpha release is out](https://github.com/vuejs/vue-next/releases), it is time to start exploring Vuetify support for Vue 3.

### Proposed solution
Start investigating how to support Vue 3 in Vuetify and outline the action plan and roadmap for official support. Explore what's the impact of the composition API to Vuetify.

**Comment by MajesticPotatoe** [comment]
This is actually being handled via our notion board [Vuetify Next](https://www.notion.so/Vuetify-Next-edf8fdb074eb4643a7196aaf8e5d5cad)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by mrts** [comment]
Alright, thanks! I hope that the issue is useful as a link to the Notion board.
