### ISSUE TITLE
[Bug Report] VSwitch doesn't properly display initial state with :value binding

### ISSUE THREAD

**Issue by kumpelblase2** [vuetifyjs/vuetify#10020]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 73.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1. Create a bool value (e.g. `enabled` ) inside `data` of a component with the value `true`
2. Add a VSwitch with `:value="enabled"`

### Expected Behavior
VSwitch reflects value that is bound using `:value`

### Actual Behavior
VSwitch shows as if the value is `false`, even though it's not. Using `v-model` instead displays the correct behavior.

### Reproduction Link
<a href="https://jsfiddle.net/fm7uepLj/" target="_blank">https://jsfiddle.net/fm7uepLj/</a>

**Comment by jacekkarczmarczyk** [comment]
You want `input-value`

**Comment by kumpelblase2** [comment]
Seems like I skipped over that and went straight to `value`. Really sorry for taking your time for such a trivial thing!
