### ISSUE TITLE
[Bug Report] Click td element

### ISSUE THREAD

**Issue by jacyzin** [vuetifyjs/vuetify#10024]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
Click on td element and expected open dialog (in codepen I send only peace of code)

### Expected Behavior
Expected open dialog, but click in the td element not happen.

### Actual Behavior
I only see example for click in tr element, but I need td element.

### Reproduction Link
<a href="https://codepen.io/jacyzin/pen/vYExbYN" target="_blank">https://codepen.io/jacyzin/pen/vYExbYN</a>

### Other comments
This works in vuetify 1.x

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

See https://github.com/vuetifyjs/vuetify/issues/8643
