### ISSUE TITLE
[Feature Request] add close icon on chips in AutoComplete Component 

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10028]
### Problem to solve
easily remove selected value. instead of researching on the same value again and uncheck it

### Proposed solution
add small close before text inside the chip
Note that this problem happens when using 'multiple' option

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/qBEmEXJ

**Comment by KareemDa** [comment]
Thanks a lot I've missed this option
