### ISSUE TITLE
[Bug Report] Vuetify css overridden by Chrome's user agent stylesheet

### ISSUE THREAD

**Issue by Sushi2all** [vuetifyjs/vuetify#10026]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Mac OS 10.13.6

### Steps to reproduce
Check in the chrome inspector how the font-size is defined for the VCardTitle text

### Expected Behavior
Dimension should be defined by Vuetify defaults and classes

### Actual Behavior
UAS takes precedence. Chrome's definition is in ems rather than rems and this can break uniformity across the app.

### Reproduction Link
<a href="https://codepen.io/lxr900/pen/eYmvwgp" target="_blank">https://codepen.io/lxr900/pen/eYmvwgp</a>

### Other comments
In Firefox it works properly

**Comment by KaelWD** [comment]
You should use `<h3 class="text-h3">`, or in v2.6 `<v-card-title tag="h3">`
