### ISSUE TITLE
[Bug Report] Property or method "tooltip" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#10022]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Linux x86_64

### Steps to reproduce
1. Use the example in Vuetify for showing a tooltip on a menu. (https://vuetifyjs.com/en/components/menus#menu-with-activator-and-tooltip)
2. Use the Vue Devtools plugin for Chrome
3. Build your project in dev mode (vue-cli-service build --mode development) so that the Vue Devtools work.
4. Look at the console and you will see

vue.runtime.esm.js:620 [Vue warn]: Property or method "tooltip" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

### Expected Behavior
Not to see the error. Either the example has to define tooltip in the data section, or internally something should be done under the hood for it

### Actual Behavior
I see the message mentioned above

### Reproduction Link
<a href="https://codepen.io/SorryNotApplicableToThisIssueButIHaveToAddALinkToSubmitThisForm" target="_blank">https://codepen.io/SorryNotApplicableToThisIssueButIHaveToAddALinkToSubmitThisForm</a>

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by UglyHobbitFeet** [comment]
I can't do that as you need to have vue dev installed in Chrome. Please
reopen.

**Comment by jacekkarczmarczyk** [comment]
You can provide a github repo as a reproduction

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
If it only happens with vue-devtools installed then it's probably an issue for them instead.
