### ISSUE TITLE
[Feature Request] remove typed input after selecting value in Autocomplete with multiple prop

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10029]
### Problem to solve
you can immediately search for the other value instead of erasing first input then research for the second one 

### Proposed solution
remove typed input after selecting a value

**Comment by deraw** [comment]
I think that's more a bug fix than a feature! Here's [a reproduction of the issue](https://codepen.io/Deraw/pen/JjoBwav?editable=true&editors=101) if needed

In the meantime, a workaround is to use `:search-input.sync="searchInput"` and to reset this value on change `@change="searchInput = ''"`

**Comment by johnleider** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5926

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
