### ISSUE TITLE
[Bug Report] Very long labels on text field makes the whole field wider

### ISSUE THREAD

**Issue by maylow22** [vuetifyjs/vuetify#10030]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
create outlined text field with very long label

### Expected Behavior
same behaviour as non outlined text fields. Not increasing width of whole text field

### Actual Behavior
if the label is too long and the outlined style is used, the label will be truncated to the visible part (that's OK), but the width of the entire input will increase, which is not OK.

### Reproduction Link
<a href="https://codepen.io/maylow/pen/GRgmJYv" target="_blank">https://codepen.io/maylow/pen/GRgmJYv</a>

**Comment by KaelWD** [comment]
#9286

**Comment by Djaler** [comment]
Hmm, looks like we should take into account actual width of input too
