### ISSUE TITLE
[Documentation] Clarify internationalization capabilities

### ISSUE THREAD

**Issue by clover21** [vuetifyjs/vuetify#10035]
### Problem to solve
Is it possible to use something like the vue-i18n $tc() function for pluralization when using integrated vuetify internationalization ? I couldn't find anything in the documentation about that.

### Proposed solution
If not possible I think it would be better to tell it clearly in the documentation and say that using vue-i18n is the only way to do pluralization.

**Comment by MajesticPotatoe** [comment]
Use vue-i18n, vuetify only handles translation function `t` as shown in api, and as stated, supports easy integration with vue-i18n.
