### ISSUE TITLE
[Bug Report] No spaces within v-btn and span/icon

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#10032]
### Environment
**Vuetify Version:** 1.5.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.13.6

### Steps to reproduce
`<v-btn>I am <span>text</span></v-btn>`

Or

`<v-btn>I am <v-icon>person</v-icon></v-btn>`

### Expected Behavior
There is a space between the left-most text and the inline icon/span, i.e. "I am text" (with a space)

### Actual Behavior
there is no text leaving the button to look like "I amtext" (without a space)

### Reproduction Link
<a href="https://codepen.io/codepen15club/pen/PowmpVZ" target="_blank">https://codepen.io/codepen15club/pen/PowmpVZ</a>

![image](https://user-images.githubusercontent.com/7410770/71324645-3c6eea00-24af-11ea-894a-8c0377db1214.png)

**Comment by MajesticPotatoe** [comment]
Seems to be due to `display: flex` on `v-btn__content`.
you get the same effect doing:
`<div style="display:flex;">I am <span>text</span></div>`
Wrapping `v-btn` contents in a div seems to resolve it.

**Comment by davidbielik** [comment]
Thanks @MajesticPotatoe. I don't know if it was a dependency change in my project, or what, but even after reverting back (and as shown in the basic codepen example), I can't seem to render spacing as expected (`<span>`, `<v-icon>`, `&nbsp;`, etc.)

**Comment by johnleider** [comment]
This is expected behavior due to flex.
