### ISSUE TITLE
[Bug Report] Combobox looses cursor after extra backspace pressing

### ISSUE THREAD

**Issue by MrsSima** [vuetifyjs/vuetify#10036]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.0
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Open the page. ( https://vuetifyjs.com/en/components/combobox#combobox )
2. Input 123
3. Press backspace 4 times
4. Try to type 123 again

### Expected Behavior
Typed 123

### Actual Behavior
Cursor is lost, nothing is typed

### Reproduction Link
<a href="https://codepen.io/bob-lee/pen/qBWVQrd" target="_blank">https://codepen.io/bob-lee/pen/qBWVQrd</a>

### Other comments
! Codepen is not reproducting the issue, but documentation does.
Checked this in Safari too, works the same way.

**Comment by YipingRuan** [comment]
It's a bit strange, as the "focus" is not really lost

![image](https://user-images.githubusercontent.com/5492274/71545719-6e111500-29c9-11ea-9fb9-22fc7f941f16.png)
