### ISSUE TITLE
[Bug Report] Tooltip positioning breaks with v-if toggling

### ISSUE THREAD

**Issue by waxlamp** [vuetifyjs/vuetify#10037]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
1. Place a v-btn, marked with v-if, inside a v-tooltip.
2. Instantiate the v-btn by making its v-if condition true.
3. Note that the tooltip on hover is placed correctly.
4. Toggle the v-if condition to false, and then back to true.
4. Note that the tooltip position is now incorrect.

### Expected Behavior
The tooltip position should remain correct.

### Actual Behavior
The tooltip position is incorrect.

### Reproduction Link
<a href="https://codepen.io/aichoudh/pen/yLyXJNZ" target="_blank">https://codepen.io/aichoudh/pen/yLyXJNZ</a>

### Other comments
Changing the v-if to v-show fixes the problem, so I suppose this has something to do with the component lifecycle?

**Comment by KaelWD** [comment]
Toggle the tooltip instead: https://codepen.io/kaelwd/pen/qBEjRNZ?editors=1010

The current implementation is pretty messy and doesn't work well with transitions and dynamic elements, but I've been rewriting the way they're handled so it should improve in a future release. 

Related issues: #3399, #7422, #9878

**Comment by waxlamp** [comment]
> Toggle the tooltip instead: https://codepen.io/kaelwd/pen/qBEjRNZ?editors=1010
> 

Thanks!

> The current implementation is pretty messy and doesn't work well with transitions and dynamic elements, but I've been rewriting the way they're handled so it should improve in a future release.
> 
> Related issues: #3399, #7422, #9878

Sadly, I had my tooltip set on an icon with a transition, so I will sacrifice the transition in favor of correct tooltip placement. Thanks again!
