### ISSUE TITLE
[Bug Report] VList tile prop not working

### ISSUE THREAD

**Issue by LiquidSolid** [vuetifyjs/vuetify#10045]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Linux x86_64

### Steps to reproduce
Click toggle button and see.

### Expected Behavior
`v-list` will be styled like a tile sheet.

### Actual Behavior
`v-list` ignoring `tile` prop and always has border-radius.

### Reproduction Link
<a href="https://codepen.io/liquid-solid/pen/GRgEYRK" target="_blank">https://codepen.io/liquid-solid/pen/GRgEYRK</a>

**Comment by MajesticPotatoe** [comment]
duplicate #9487
