### ISSUE TITLE
[Feature Request] Ability to fully disable all Vuetify CSS

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#10048]
### Problem to solve
My project is going to take a few months to build and I am not needing to modify any css or sass variables.  So it would be beneficial if I can save the webpack and sass time to to compile during the development phase to disable the sass compilation and just include a minified css in my index.html

I have tried various methods like {theme: {disable: true;}} which does sort of show the theme being disabled, but it doesn't seem to change any of the build files.  "dist/css/chunk-vendors.dff6e19a.css" is still the same size at 439.30 KiB and 54.80 KiB when gzipped.

Instead, it would be better to ignore the css and sass entirely and speed up compile time.  I have been using "speed-measure-webpack-plugin" and it shows that the majority of the time is in the Sass compilation time.  Sure it gets cached and the second+ time running a save on a .Vue file is much less, but for now I would prefer to save as much time as possible.

### Proposed solution
I would think that 
```
export default new Vuetify({
	theme: {
		disable: true
	}
});
```
Would fully disable the theme, but it still uses a lot of css for layout, etc, but just ignoring minor things like colors, etc.

So to make it so there is no breaking change maybe we can have another setting to fully disable css/sass entirely Or use css only as a include:
```
export default new Vuetify({
	styles: 'sass' | 'css' | false
});
```
default would be 'sass' meaning it will use and compile sass.
'css' will use a minified css file that is just imported, but not compiled
false would be nothing and therefore the user will be responsible for adding any css.  Most likely this will be used when the user will add a minified css file from CDN to the index.html file, etc

**Comment by KaelWD** [comment]
If you don't use a-la-carte no sass will be imported. Alternately you can use [`IgnorePlugin`](https://webpack.js.org/plugins/ignore-plugin/) to skip the sass imports.

> `styles: 'sass' | 'css' | false`

Not possible, you can't influence the build at runtime. `theme: { disable: true }` just disables the JS theme system, which is generated at runtime.

**Comment by ggedde** [comment]
@KaelWD Disabling a-la-carte and removing the vuetify-loader worked. I then am adding the CDN for the CSS in the index.html and my build is much faster.  Although, my bundle is much larger, but that is fine as I will revert back once I am close to finishing my project or add a condition on Build instead of Serve.
Thanks

PS. IgnorePlugin worked, but got JS errors as the JS stilled required the sass modules.

**Comment by tetz2442** [comment]
Here is how I ended up removing the default CSS loaded by Vuetify when doing a-la-carte. I'm using webpacker in Rails.

Using the IgnorePlugin doesn't work, since a JS error gets thrown, as noted above.

```
{
  test: /\.sass$/,
  use: [
    'style-loader',
    'css-loader',
    'sass-loader',
    // Remove any vuetify related sass files that are imported
    {
      loader: 'file-replace-loader',
      options: {
        condition: 'always',
        replacement(resourcePath) {
          if (resourcePath.indexOf('vuetify\\src') >= 0) {
            return resolve('./app/javascript/empty-file.sass');
          }
        },
        async: true,
      },
    },
  ],
}
```

**Comment by KaelWD** [comment]
The webpack and vite plugins for vuetify 3 now have a `styles: 'none'` option that will disable all style imports.
