### ISSUE TITLE
[Feature Request] selecting checkbox or radio didn't have transition animate 

### ISSUE THREAD

**Issue by zoneus** [vuetifyjs/vuetify#10050]
### Problem to solve
compare with google official document and vuetify doc, you will find the difference between google material design and vuetify implement when select a checkbox or radio.

   [google official doc](https://www.material.io/components/selection-controls/)

   [vuetify official doc](https://vuetifyjs.com/zh-Hans/components/selection-controls)

### Proposed solution
so what I want know is that there is any way could to add transition animate when select checkbox and radio.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
