### ISSUE TITLE
[Bug Report] v-badget not showing correctly on v-tab

### ISSUE THREAD

**Issue by JumpAttacker** [vuetifyjs/vuetify#10053]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
just open codepen and look on first tab item

### Expected Behavior
beautiful badget on tab item

### Actual Behavior
first item with baget has wrong position

### Reproduction Link
<a href="https://codepen.io/jumpattacker/pen/dyPzYmN?&editable=true&editors=101" target="_blank">https://codepen.io/jumpattacker/pen/dyPzYmN?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
wrap the text, not the tab
```
<v-tab>
  <v-badge>
    <template v-slot:badge>0</template>
    Landscape
  </v-badge>
</v-tab>
```

**Comment by JumpAttacker** [comment]
oh, thanks!
