### ISSUE TITLE
[Bug Report] Expandable rows don't open when Data Table is rendered dynamically

### ISSUE THREAD

**Issue by fernandaverzbickas** [vuetifyjs/vuetify#10055]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Linux x86_64

### Steps to reproduce
On the codepen example, if you try to expand a row, it won't work since data tables are being rendered dynamically.

### Expected Behavior
Expandable rows opening accordingly with it's item key.

### Actual Behavior
Either it doesn't open at all, or, if you change the item-key to "1" for example, it will open all of them.

### Reproduction Link
<a href="https://codepen.io/fernanda-verzbickas/pen/BaydovP?&editable=true&editors=101" target="_blank">https://codepen.io/fernanda-verzbickas/pen/BaydovP?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Use `:expanded.sync="expanded[group.id]"`
