### ISSUE TITLE
[Feature Request] Remove VOverflowBtn? It duplicates VAutocomplete and VSelect

### ISSUE THREAD

**Issue by BjornLuG** [vuetifyjs/vuetify#10067]
### Problem to solve
This removes the similarity between VOverflowBtn, VAutocomplete and VSelect.

Currently VOverflowBtn with `editable` prop works almost exactly the same as VAutocomplete. A normarl VOverflowBtn also works the same way as VSelect. In fact [VOverflowBtn.ts](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.ts) imported VAutocomplete and VSelect, and became sort of a wrapper.

### Proposed solution
Remove VOverflowBtn. Or redirect certain features like autocomplete or list selects to VAutocomplete and VSelect respectively in the docs.

Unless I'm missing something, it's odd to have duplicated functionality.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
