### ISSUE TITLE
[Documentation] Searching

### ISSUE THREAD

**Issue by SplaTTgml** [vuetifyjs/vuetify#10068]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Ваша поисковая система, какой-то бред. Я хочу узнать как модифицировать тег v-btn, вбиваю его в поиск - выдаёт 5 ссылок на разделы где упоминается такой тег, а не на страницу с его описанием.
Your search system is stupid, i do request for searching "v-btn", and get response links with wrong sections.

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons" target="_blank">https://vuetifyjs.com/en/components/buttons</a>

### Other comments
-

**Comment by KaelWD** [comment]
Duplicate of #6400
