### ISSUE TITLE
[Bug Report] Vuetify grid system not working

### ISSUE THREAD

**Issue by daviaws** [vuetifyjs/vuetify#10078]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Linux x86_64

### Steps to reproduce
I copy this code to a new component: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/grids/playground.vue

And I show it in my App.

### Expected Behavior
Work as in the playground.

### Actual Behavior

2 Things.
1. The grid system not align with any change of configuration.
2. The selects don't show any of the options when I click.

### Reproduction Link
<a href="https://jsfiddle.net/daviaws/z6fhd83q/6/" target="_blank">https://jsfiddle.net/daviaws/z6fhd83q/6/</a>

### Other comments
I found nothing about this, and I'm searching the whole day...

**Comment by MajesticPotatoe** [comment]
Your reproduction uses a old version of vue (2.2) which is not compatable with doc examples (which use 2.6+). Seems to work fine https://codepen.io/majesticpotatoe-the-bashful/pen/Exawevy. Please provide a valid reproduction reproducing the issue you are describing.
