### ISSUE TITLE
[Bug Report] v-breadcrumbs-item disabled not applying color changes

### ISSUE THREAD

**Issue by seanareed** [vuetifyjs/vuetify#10073]
### Environment
**Vuetify Version:** 1.5.14
**Vue Version:** 2.5.17
**Browsers:** Chrome 79.0.3945.88
**OS:** Linux

### Steps to reproduce
Follow the example code for "Item slot" on the documentation's Breadcrumbs page:

https://vuetifyjs.com/en/components/breadcrumbs

### Expected Behavior
Disabled links change to color specified in css.

### Actual Behavior
Disabled links maintain original color.

### Reproduction Link
<a href="https://codepen.io/seanareed/pen/PowKVXz?&editable=true&editors=111" target="_blank">https://codepen.io/seanareed/pen/PowKVXz?&editable=true&editors=111</a>

### Other comments
The bug is evident on the documentation page as well. The code example says it should be gray, but it's blue. The `pointer-events: none` works fine.

**Comment by YipingRuan** [comment]
Disable okay without slot:
![image](https://user-images.githubusercontent.com/5492274/71584813-5c597a00-2b4f-11ea-8289-47c4651f57f6.png)

Disable fail for item slot:
![image](https://user-images.githubusercontent.com/5492274/71584889-ab9faa80-2b4f-11ea-8e76-2deb64c73e24.png)

So the simple "disable" class is not enough.
