### ISSUE TITLE
[Bug Report] Keyboard does not close on selecting an entry in v-autocomplete 

### ISSUE THREAD

**Issue by liujiajun** [vuetifyjs/vuetify#10072]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Safari, Google Chrome
**OS:** iOS

### Steps to reproduce
- Click on AutoComplete box
- Select an entry from the dropdown list **or**
- Enter some text in AutoComplete box and press Enter in keyboard

### Expected Behavior
Keyboard closes

### Actual Behavior
Keyboard does not close

### Reproduction Link
<a href="https://codepen.io/jiajun_liu/pen/KKwvGga" target="_blank">https://codepen.io/jiajun_liu/pen/KKwvGga</a>

**Comment by johnleider** [comment]
The simple fix for this would be to call `document.activeElement.blur()` after a selection. This would only apply in a non multiple select and would probably use a **mobileBreakpoint** prop.

**Comment by liujiajun** [comment]
> The simple fix for this would be to call `document.activeElement.blur()` after a selection. This would only apply in a non multiple select and would probably use a **mobileBreakpoint** prop.

Thanks. This works. And would be good if there is a permanent fix to this issue.

**Comment by bad4iz** [comment]
Duplicate of #5950
