### ISSUE TITLE
[Bug Report] [Vuetify] Model must be bound to an array if the multiple property is  true.

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#10077]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Use a v-btn-toggle component within a form, set it to multiple and mandatory so that a user can selected many choices and at least one, otherwise the validation must fail.

### Expected Behavior
The validation should work without the error message:

>> [Vuetify] Model must be bound to an array if the multiple property is  true.

### Actual Behavior
2. If the value bound to `v-model` the vailidation works as expected, but the error message above appears.

3. If I set the value of the variable bound to `v-model` to an empty array, the validation does not work at all

### Reproduction Link
<a href="https://codepen.io/begueradj-the-sasster/pen/MWYEyoo?&editable=true&editors=101" target="_blank">https://codepen.io/begueradj-the-sasster/pen/MWYEyoo?&editable=true&editors=101</a>

**Comment by Teellcory** [comment]
You are missing valid from your data props as well. toggleIt needs to be an array, as you know. This is your example with some fixes, to show that mandatory is not forcing the selection of an option like it should be: https://codepen.io/teellcory/pen/GRgMqYv

**Comment by begueradj** [comment]
Yes, we are saying the same thing (bullet 3 above), and this is why I believe this is a bug :)
