### ISSUE TITLE
Feature request: Child Alignment like angular materials

### ISSUE THREAD

**Issue by TheNoim** [vuetifyjs/vuetify#1007]
- What will it allow you to do that you can't do today?
>Better layouting pages.
- What potential bugs and edge cases does it help to avoid?
>Use standart css and prevent endless search for good css center methods.

I request a similar possibility to align my childs:
https://material.angularjs.org/latest/layout/alignment
This is at the moment my only reason to stay with angular material. The child alignment is awesome and I work much with it. I really want to move to vue and vuetify.

**Comment by nekosaur** [comment]
Their setup looks very similar to what is possible with the `v-layout` and `v-flex` components in vuetify (https://vuetifyjs.com/layout/grid). What is it you are missing?

**Comment by johnleider** [comment]
I think what he is asking for is break-point support for the individual layout props.

**Comment by TheNoim** [comment]
Hm I overlooked the api docs v-layout has exactly what I need.
