### ISSUE TITLE
[Documentation] Themes page not working correctly

### ISSUE THREAD

**Issue by maxxer** [vuetifyjs/vuetify#10070]
### Environment

**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
Just open the page

### Expected Behavior
Menu working, preview visible

### Actual Behavior
None of the above, page and menu links not working

### Reproduction Link
<a href="https://vuetifyjs.com/en/themes/premium" target="_blank">https://vuetifyjs.com/en/themes/premium</a>

**Comment by jacekkarczmarczyk** [comment]
It works fine if you navigate from some other page, but not when you open it directly

**Comment by MajesticPotatoe** [comment]
resolved in d6a5b06

**Comment by KaelWD** [comment]
This seems to be fixed since the docs rewrite.
