### ISSUE TITLE
[Bug Report] Fade transition on tab items is inconsistent

### ISSUE THREAD

**Issue by Alanaktion** [vuetifyjs/vuetify#10075]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Mac OS 10.15

### Steps to reproduce
Add two or more tabs and tab-items, with the transition and reverse-transition set to `fade-transition`. The tab items can be within the `v-tabs` component, or in a separate `v-tabs-items` component.

### Expected Behavior
The tab-items fade out and in consistently when switching between tabs.

### Actual Behavior
The fade transitions are inconsistent, with the reverse transitions working as expected, but the forward transitions only fading out the previous tab, and not fading in the new tab.

### Reproduction Link
<a href="https://codepen.io/alanaktion/pen/mdyBeeP" target="_blank">https://codepen.io/alanaktion/pen/mdyBeeP</a>

### Other comments
This appears to have the same result in all current major browsers.

**Comment by OrkhanAlikhanov** [comment]
Still experiencing this, with vuetify@2.3.1

**Comment by DemoreN** [comment]
Still in 2.3.15 (only `:reverse-transition` works with fade-transition)

**Comment by ggedde** [comment]
Same issue
