### ISSUE TITLE
[Feature Request] Prevent empty range for range slider

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#10089]
### Problem to solve
I would like to require users to select a range, not an empty range. Currently user can drag one edge of the range on top of the other, making it empty.

### Proposed solution
Add a prop which defines the minimal range length required. The control should not allow dragging one side of the range further once that length is reached.

**Comment by KaelWD** [comment]
Models are controlled in v3 so you can implement this yourself with a computed setter, similar to #9593
