### ISSUE TITLE
[Feature Request] Add Default Icon for V-Stepper-Step

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#10088]
### Problem to solve
Currently you are only able to show a Number or text in the default mode of the Step.  I would like to show an Icon instead.  I have tried using `<i class="v-icon notranslate mdi mdi-account theme--dark"></i>` but it doesn't render html.

### Proposed solution
Along with error-icon, complete-icon, edit-icon, I would like to have just `icon`
If not set then it uses the default number, Otherwise I would like to show an Icon.

**Comment by Liam26** [comment]
I would also be very interested in this, hope it will get a response.
