### ISSUE TITLE
[Feature Request] Striped rows for tabels

### ISSUE THREAD

**Issue by artmarydotir** [vuetifyjs/vuetify#10082]
### Problem to solve
With stripped style tables have a better display.

### Proposed solution
To implement this option we have to write custom css.
could these be part of a future implementation plan?

[example link](https://codepen.io/artmarydotir/pen/OJPxgbp)

**Comment by shyding** [comment]
how to deal table row merge or table column merge ?

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

Striped rows are easy enough to do in user land as shown in the example codepen.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
