### ISSUE TITLE
[Bug Report] Unexpected Datatable Re-render

### ISSUE THREAD

**Issue by mattcdavis1** [vuetifyjs/vuetify#10084]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.15.2

### Steps to reproduce
Type anything in the search field

### Expected Behavior
Datatable would not re-render

### Actual Behavior
Datatable re-renders

### Reproduction Link
<a href="https://codepen.io/mattcdavis1/pen/zYxEZKr?editors=1010" target="_blank">https://codepen.io/mattcdavis1/pen/zYxEZKr?editors=1010</a>

### Other comments
The re-render occurs when both `:search-input.sync="searchKeyword"` is present in `v-autocomplete` and `:footer-props="{}"` is present in `v-data-table`.  Removing either of these props resolves the issue. 

As far as I'm aware there should not be any connection between `v-autocomplete` and `v-datatable` outside of something I am specifically doing myself but it seems like there is a connection since changing `v-autocomplete` affects `v-datatable`

**Comment by KaelWD** [comment]
Changing `searchKeyword` re-renders the root instance, which creates a new empty object for the `footer-props` and causes a re-render of the table.

**Comment by mattcdavis1** [comment]
This is horribly unperformant - why would this be expected behavior?  I'm running into issue where typing is slowed down to a crawl due to table-rerendering overhead.  How can this behavior be disabled so that i control when the re-render occurs but still am able to sync the search key word and keep the footer?

**Comment by KaelWD** [comment]
That's how vue works, if you create an object in the template it causes cascading renders. Pass `footer-props` from data or a computed property to prevent this.

**Comment by mattcdavis1** [comment]
Ahh - got it. Thanks!
