### ISSUE TITLE
[Documentation] Translate docs

### ISSUE THREAD

**Issue by XIOLog** [vuetifyjs/vuetify#10081]
### Problem to solve
Hello.

Tell me, please, how can I help you to translate vuetify docs? I can`t find a guide.

I am Russian. But your docs is writen in English, not Russian. Although I choose Russian language.

### Proposed solution
I know Russian. I can help you

**Comment by ibrahimBeladi** [comment]
Click on the language flag, you will find the last option which is to translate. It will move you to [crowdin.com](https://crowdin.com) website, join the project and you can start helping with the translation.

**Comment by MajesticPotatoe** [comment]
As ibrahim has described, we do translations through crowdin. Click the translate button in the nav drawer under the language flag.
![2020-01-01 11_17_42-Window](https://user-images.githubusercontent.com/27827979/71643490-7185f400-2c88-11ea-8bfb-28c33bd73bd0.png)
