### ISSUE TITLE
[Feature Request] More style option for tables

### ISSUE THREAD

**Issue by artmarydotir** [vuetifyjs/vuetify#10080]
### Problem to solve
Can we have style option like :
1.table-striped
2.bordered table
3.border-less table
?

### Proposed solution
To implement these option we have to write custom css.
Could these be part of a future implementation plan?

**Comment by jacekkarczmarczyk** [comment]
Please create one issue per feature

**Comment by artmarydotir** [comment]
> Please create one issue per feature

Yes, Sure. thanks.

**Comment by ibrahimBeladi** [comment]
And close this one once you open the issues.
