### ISSUE TITLE
hide-details on v-text-field not working

### ISSUE THREAD

**Issue by oswaldofreitas** [vuetifyjs/vuetify#1008]
Shouldn't [this class](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_input-groups.styl#L123) have a `display: none`?

Example of code where `hide-details` is not working (it's always visible even when dirty = false):
```
v-text-field(label='Contato', required, v-model='vm.revendedor.contato', :rules='[validation.required]', :hide-details='!dirty')
```

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by indyo** [comment]
Has this been reopened? I can't seem to find it, sorry.

**Comment by nekosaur** [comment]
This issue is closed. If you're having problems please create a new one using the provided boilerplate.

**Comment by johnleider** [comment]
I see you using the thumbs down @oswaldofreitas but you refuse to follow the rules to create a proper issue ticket?
