### ISSUE TITLE
[Feature Request] comma separating v-pagination numbers

### ISSUE THREAD

**Issue by HP4k1h5** [vuetifyjs/vuetify#10085]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 3.0.0-alpha.0
**Browsers:** Firefox 71.0
**OS:** Mac OS 10.15

### Steps to reproduce
set length prop of v-pagination to > 1000 . 

### Expected Behavior
more human readable number display

### Actual Behavior
no ./, delimiters 

### Reproduction Link
<a href="https://codepen.io/hp4k1h5/pen/ExawwJd" target="_blank">https://codepen.io/hp4k1h5/pen/ExawwJd</a>

### Other comments
i think it can be solved in line 173 of https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VPagination/VPagination.ts#L173
by changing it to 
```      }), [i.toLocaleString()])```

**Comment by johnleider** [comment]
This is a feature request, we've never advertised this as supported functionality. The simple solution would be a slot.

**Comment by glen-84** [comment]
This should be handled with [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat).
