### ISSUE TITLE
[Bug Report] RTL stepper is broken

### ISSUE THREAD

**Issue by Nabeel20** [vuetifyjs/vuetify#10098]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
• just tried to add a stepper to RTL vue component. 

### Expected Behavior
To Respect RTL guidelines and achieve animation and elements in the right direction and place.

### Actual Behavior
The left line won't get to right and the animation sometimes not working properly.

### Reproduction Link
<a href="https://codepen.io/Nabeel2020_XD/pen/zYxEQRp?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/Nabeel2020_XD/pen/zYxEQRp?&editable=true&editors=101#anon-signup</a>

**Comment by hugoazevedosoares** [comment]
I think you can solve this by overriding some css:
`.theme--light.v-stepper--vertical .v-stepper__content:not(:last-child) {
    /* border-left: 1px solid rgba(0,0,0,.12); This is the old value  */
    border-right: 1px solid rgba(0,0,0,.12);
}

.v-stepper--vertical .v-stepper__content {
     /* margin: -8px 36px -16px -36px; This is the old value */
    margin: -8px -36px -16px 36px; !important
}`

I'll work on a permanent fix.
