### ISSUE TITLE
[Bug Report] Duplicate IDs for range selects

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#10090]
### Environment
**Vuetify Version:** 2.1.16
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Ubuntu undefined

### Steps to reproduce
It seems like any range select has this issue. For example, on reproduction, the following error is shown in Chrome:

```
[DOM] Found 2 elements with non-unique id #input-4:
```

### Expected Behavior
That does not happen.

### Actual Behavior
There are duplicate IDs.

### Reproduction Link
<a href="https://codepen.io/mitar/pen/rNaGdQg" target="_blank">https://codepen.io/mitar/pen/rNaGdQg</a>

**Comment by eyesurewould** [comment]
Possible [duplicate](https://github.com/vuetifyjs/vuetify/issues/6843)?

**Comment by mitar** [comment]
It looks like it.
