### ISSUE TITLE
[Bug Report] V-Stepper-Step doesn't allow for binding to integer of 0

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#10096]
### Environment
**Vuetify Version:** 2.1.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
When binding step to 0 it acts as null and skips that step on initial load.
Ex
`:step="0"`

### Expected Behavior
bind to 0 should see the variable as integer 0 and not null

### Actual Behavior
Initial load skips the first step

### Reproduction Link
<a href="https://codepen.io/ggedde/pen/qBEPLPr" target="_blank">https://codepen.io/ggedde/pen/qBEPLPr</a>

### Other comments
If you are not binding and just use 
`step="0"` 
It works fine, but binding to 0 or to a variable of 0 does not.

If you change:
`:step="stepKey"`
to 
`:step="stepIndex.toString()"`
Then it works.

Although there is a workaround it took me a long time to figure out and I don't think that should be the case.

Thanks

**Comment by ggedde** [comment]
Also I end up having to put a few parseInt(step) in my code.  So a solution would be nice!

**Comment by jacekkarczmarczyk** [comment]
Possible solution:

```diff
diff --git a/packages/vuetify/src/components/VStepper/VStepper.ts b/packages/vuetify/src/components/VStepper/VStepper.ts
index 2eed0211e..d19bef6e8 100644
--- a/packages/vuetify/src/components/VStepper/VStepper.ts
+++ b/packages/vuetify/src/components/VStepper/VStepper.ts
@@ -82,7 +82,7 @@ export default baseMixins.extend({
   },

   mounted () {
-    this.internalLazyValue = this.value || (this.steps[0] || {}).step || 1
+    this.internalLazyValue = this.value == null ? ((this.steps[0] || {}).step || 1) : this.value
     this.updateView()
   },
```

Tests needed though, and there's no tests for VStepper at all (just for VStepperStep and Content) so it might become a bigger PR
