### ISSUE TITLE
[Bug Report] VResponsive/VImg [2.1.16] changes have broken "align-end"

### ISSUE THREAD

**Issue by dancarasco** [vuetifyjs/vuetify#10094]
### Environment
**Vuetify Version:** 2.1.16
**Last working version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add "align-end" to a v-img embedded in a v-card and the alignment won't work. Margin is way out. This can even be seen in the (now broken) examples in the Card component docs under "Grid": https://vuetifyjs.com/en/components/cards#grids

### Expected Behavior
Text should be at the bottom of the card to due align-end being used.

### Actual Behavior
Text appears half way up the card or completely out of the bounds.

### Reproduction Link
<a href="https://codepen.io/trickster223/pen/RwNLYaL" target="_blank">https://codepen.io/trickster223/pen/RwNLYaL</a>

### Other comments
This has broken the v-img and grid usage in the v-card documentation under Grid: https://vuetifyjs.com/en/components/cards#grids

The *breaking* changes I am referring to can be seen in these two commits:

--removed--
--removed--

Tested & working prior to these commits.

**Comment by johnleider** [comment]
This change caused the regression: https://github.com/vuetifyjs/vuetify/commit/e92d6b79115c28b6cae71b7bc70bbb295c12ef89

The above referenced commits have nothing to do with the issue.

**Comment by dancarasco** [comment]
@johnleider Thanks for confirming
