### ISSUE TITLE
Input inline label color is wrong?

### ISSUE THREAD

**Issue by radicaled** [vuetifyjs/vuetify#101]
Based on https://material.io/guidelines/components/text-fields.html#text-fields-labels the color of inline labels is wrong when its acting as a placeholder. Scroll down to the "light theme" and "dark theme" examples to see.

> The label’s color should reflect your app’s color palette, while also meeting appropriate contrast ratios.

Right now the inline labels always use the accent color, even when the inline label is being used as a placeholder.

**Comment by johnleider** [comment]
This will be corrected with the forms refactor coming up.

**Comment by johnleider** [comment]
This has been fixed on dev for the new release.
