### ISSUE TITLE
[Bug Report] Autofocusing processing was blocked

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#10102]
### Environment
**Vuetify Version:** 2.2.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 7

### Steps to reproduce
Have an autofocusing text field.

### Expected Behavior
No console message saying it was blocked.

### Actual Behavior
In a normal site: "Autofocus processing was blocked because a document already has a focused element."
In CodePen: "Blocked autofocusing on a form control in a cross-origin subframe."

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/PowOZJe" target="_blank">https://codepen.io/teellcory/pen/PowOZJe</a>

### Other comments
It seems like it's triggering twice on the same element, hence the message, since there is only one autofocus in the page. It does not prevent the autofocus from working, though.

**Comment by johnleider** [comment]
This must be something new in chrome, this would have come up a long time ago otherwise since this persists all the way back to v1.5.

I found this, not sure if it pertains <https://www.chromestatus.com/feature/5654905853313024>

**Comment by Teellcory** [comment]
It looks like Chrome is parsing the raw vuetify tag's autofocus, then vuetify is implementing it as it always has, which causes a double attempt. Do you think it would be best if vuetify were to change it to "autofocused" or something along those lines, to not conflict?

**Comment by johnleider** [comment]
I believe this is an upstream issue: https://codepen.io/johnjleider/pen/oNgoYda

I've filed a report for now: https://github.com/vuejs/vue/issues/10976

**Comment by johnleider** [comment]
Vue has designated this as something they can't resolve. We will take on the same opinion. We aren't going to be the only people having this issue so I assume it will be treated as a Chrome bug and resolved as such.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
