### ISSUE TITLE
[Bug Report] Date picker - formatting date in DD/MM/YYYY format

### ISSUE THREAD

**Issue by Roshmia** [vuetifyjs/vuetify#10107]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
the issue i am faceing is working in codepen but not in my project. 
the date will be updated to the v-model when load function is called which is called from beforeMount.
i have updated the v-model by converting the date format to dd/mm/yyyy.
v-model works fine when i try to change the date and try to select date it will not be updated to v-model

### Expected Behavior
i have updated the v-model by converting the date format to dd/mm/yyyy.
v-model works fine when i try to change the date and try to select date it will not be updated to v-model
the date cannot be selected using date picker

### Actual Behavior
the codepen i have created is working properly but not in my project. 

### Reproduction Link
<a href="https://codepen.io/Roshmi_Jinto/pen/dyPZROx?editors=1010" target="_blank">https://codepen.io/Roshmi_Jinto/pen/dyPZROx?editors=1010</a>

### Other comments
Actualy i am using vue material and vuetify together will that couse an issue in date picker

**Comment by jacekkarczmarczyk** [comment]
Without a reproduction we're not able to tell if it's something wrong in your code or in Vuetify or because of mixing Vueitfy and Vue Material. Please open a new issue when you will be able to provide a reproduction. 

Note that we accept also github repos or codesandbox (as long as they are boiled down to minimal, please read https://stackoverflow.com/help/minimal-reproducible-example for more details) if the codepen is not enough to reproduce the issue

**Comment by Roshmia** [comment]
I have resolved the issue by makeing some modification in my project

`<v-menu ref="menu1" v-model="menu1" :close-on-content-click="false" transition="scale-transition" offset-y full-width max-width="290px" min-width="290px" >`
                                                    `<template v-slot:activator="{ on }">`
                                                       ` <v-text-field v-model="selectedDate" label="Date"  prepend-icon="event"  v-on="on" ></v-text-field>`
                                                   ` </template>`
                                                    `<v-date-picker v-model="seldate" no-title @input="menu1 = false" @click:date="selectedDate = parseDate(seldate)"></v-date-picker>`
                                                `</v-menu>`

On clicking the  datepicker i have updated the date format in parseDate function and updated that on to text field v-model

**Comment by Ethan0007** [comment]
@jacekkarczmarczyk this is the reproduction, please see the dev tools.

https://codepen.io/jmonceda/pen/oNXoXGg?editors=1010

**Comment by jacekkarczmarczyk** [comment]
@Ethan0007 what are the reproduction steps?

**Comment by jmonceda** [comment]
@jacekkarczmarczyk 

1. Use the v-date-picker
2. Set value
3. The format will be DD-MM-YYYY
4. Try to update value in different date
5. Open you dev tools

**Comment by jacekkarczmarczyk** [comment]
This codepen uses version 1.0 and i can't see anything in console in docs example

**Comment by jmonceda** [comment]
@jacekkarczmarczyk which version/release that support DD-MM-YYYY?

**Comment by jacekkarczmarczyk** [comment]
I don't remember, anyway if it works in docs (even in 1.0 docs) then apparently there's a problem with provided codepen
