### ISSUE TITLE
[Bug Report] Animation not working

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#10104]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
Click the chevron.

### Expected Behavior
1. It should slide-expand from right to left.
2. The class "text-right" should right align it, but it didn't work, and I have to manually define it.
3. Clicking the date-icon/date-text does not open the date picker dialog, instead says some ambiguous warning in the console.

### Actual Behavior
instantly opens closes the content. Content is left aligned. Clicking date-icon/date-text does nothing expect put a warning in console.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/gObXLmy" target="_blank">https://codepen.io/sneaky666/pen/gObXLmy</a>

**Comment by johnleider** [comment]
You're using an inline element as the root: https://codepen.io/johnjleider/pen/vYEWyRb

**Comment by TheInvoker** [comment]
you made it transition all the way from extreme right to extreme left. 

How can I make it more like expand just the content, from like xscale 0 to xscale 100%? (but origin is on the right side).
