### ISSUE TITLE
[Bug Report] v-input initial focus color is black

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#10108]
### Environment
**Vuetify Version:** 2.2.1
**Last working version:** 2.1.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
1. focus on v-input component (v-text-field)
2. closely look at the color of the bottom underline

### Expected Behavior
Color should probably be the primary theme color from the start

### Actual Behavior
Initial color is dark black and then turns to the primary color

### Reproduction Link
<a href="https://codepen.io/roetd002/pen/MWYOORz?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/roetd002/pen/MWYOORz?&editable=true&editors=101#anon-signup</a>

**Comment by DRoet** [comment]
@johnleider or is this intentional?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/2c901ba806db5a20af342c0eaa2b28634b114924#diff-d041f1f339c8df325b18f3ee3db57af4L139

**Comment by johnleider** [comment]
There is some work that can/should be done with input styles for v3.0. In this case, `v-input` has a transition on its slot, `v-text-field` modifies that to only target background (with the fix) and then `v-overflow-btn` overwrites it again for some reason.
