### ISSUE TITLE
[Documentation] Web vuetifyjs.com die

### ISSUE THREAD

**Issue by hueanmy** [vuetifyjs/vuetify#10114]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Please fix this bug

### Expected Behavior
Fix 

### Actual Behavior
Die

### Reproduction Link
<a href="https://vuetifyjs.com/" target="_blank">https://vuetifyjs.com/</a>

### Other comments
Please fix

**Comment by Eziliram** [comment]
Error 524

**Comment by MajesticPotatoe** [comment]
You can use https://dev.vuetifyjs.com for the time being while we investigate

**Comment by MajesticPotatoe** [comment]
Resolved
