### ISSUE TITLE
[Bug Report] "filled" text input field has large height despite "dense" prop being set

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#10119]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create a `v-text-field` with both `dense` and `filled`.

### Expected Behavior
That the height is the same as with `dense` and `outlined`.

### Actual Behavior
Height gets increased dramatically.

### Reproduction Link
<a href="https://codepen.io/mitar/pen/povpzMe" target="_blank">https://codepen.io/mitar/pen/povpzMe</a>

### Other comments
I can use `single-line` as a workaround but it is still few pixels higher than just `dense`.

**Comment by MajesticPotatoe** [comment]
For the most part this is working as intended. Seems the height is currently 54px, which is 2px larger than it should be.MD Spec for dense is 52px for text-field w/label and 40px w/o.
Using single-line is the proper way to handle this if you do not intend to use a label, in which chase is within spec.

**Comment by mitar** [comment]
But why then difference in comparison with `outlined`? Is this difference also in the spec?

**Comment by mitar** [comment]
Also, with `single-line` I think it is 2 px too large as well. I am currently using the following:

```
  .v-text-field--filled > .v-input__control > .v-input__slot {
    min-height: auto !important;
  }
```

In combination with `single-line` and `dense`.

**Comment by mitar** [comment]
Thanks! That was quick!
