### ISSUE TITLE
[Feature Request] Chip group with max=0

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#10116]
### Problem to solve
I do not really want to select chips, I just want to display a list of labels with nice spacing between them and wrapping/no wrapping. Chip group already does all that, but it also makes chips interactive.

### Proposed solution
I would suggest that one can specify max=0 to disable all interaction. I currently use the following workaround:

```
<div class="v-item-group theme--light v-slide-group v-chip-group v-chip-group--column">
  <div class="v-slide-group__wrapper">
     <div class="v-slide-group__content">
      <v-chip label>Foo</v-chip>
      <v-chip label>Bar</v-chip>
    </div>
  </div>
</div>
```

**Comment by KaelWD** [comment]
You can do pretty much exactly the same thing with the grid system: https://codepen.io/kaelwd/pen/qBEpBZQ?editors=1010

**Comment by mitar** [comment]
Color is not exactly the same (v-chip-group makes things a bit more light). But thanks!

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
