### ISSUE TITLE
[Feature Request] Rename css classes to reduce css size

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#10117]
### Problem to solve
Reduces bundled sizes.

### Proposed solution
Review the css class names and reduce their name length and usage to help reduce the css bundled sizes.

An example is renaming `v-application` to `v-app`.  I know this might sound petty, but v-application is used in the css about 3,000+ times.  I tested it by renaming it to v-app and it saved my css file about 40kb.

I am not suggesting that you rename everything to unreadable variables, etc. I still think the names should be conventional, but there is a bit that could be saved.  `v-toolbar` to `v-bar` or changing `navigation` to `nav`, etc.  

These are just examples, but I would request that you fully review to see what else could be done to help reduce the size.  Again, I know that this is a little petty and with gzip it might not look that impressive, but I do think that every bit helps.

Since this would make some breaking changes I would think it is best for v3 roll-out and include the name changes in the migration guide.

**Comment by KaelWD** [comment]
| | min | min+gzip |
|---|---|---|
| .v-application | 440.8 kB | 52.3 kB |
| .v-app | 412.6 kB | 51.7 kB |

I don't think this breaking change is worth only 600 bytes, you can save a lot more than that by using [vuetify-loader](https://vuetifyjs.com/en/customization/a-la-carte). v-app might not even exist any more in 3.0, but it's too early to say.
