### ISSUE TITLE
Dropdown/Menu Issue in 0.14.0

### ISSUE THREAD

**Issue by zeljic** [vuetifyjs/vuetify#1011]
### Steps to reproduce
Open link, click on button.

### Versions
Vuetify 0.14.0

### What is expected ?
Dropdown menu should be shown.

### What is actually happening ?
There is an error in console: `regeneratorRuntime is not defined`
And dropdown menu is not visible at all.

### Reproduction Link
https://codepen.io/anon/pen/rwbGWQ

**Comment by johnleider** [comment]
Forgot to remove the async declaration, to avoid outrage, going to release 0.14.1 that contains this fix.
