### ISSUE TITLE
[Bug Report] v-list-item misaligning when "to" attribute is added to two consecutive list items

### ISSUE THREAD

**Issue by VictorOnwukwe** [vuetifyjs/vuetify#10112]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
create two consecutive list items with the "to" attribute

### Expected Behavior
List Items should be properly aligned

### Actual Behavior
The second v-list-item appears to have a left margin on addition of "to" attribute, but works fine without it

### Reproduction Link
<a href="https://codepen.io/victoronwukwe/pen/ExabpaR?#anon-signup" target="_blank">https://codepen.io/victoronwukwe/pen/ExabpaR?#anon-signup</a>

**Comment by johnleider** [comment]
I'm not sure what's wrong?

![image](https://user-images.githubusercontent.com/9064066/71753376-100c8380-2e48-11ea-9b86-d73eab0a9b10.png)

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
