### ISSUE TITLE
Stepper Content went missing

### ISSUE THREAD

**Issue by sorxrob** [vuetifyjs/vuetify#1012]
### Versions
v0.14.1

### What is expected ?
The stepper content should be visible whenever I type something

### What is actually happening ?
The whole stepper content goes missing whenever you type in any text field inside a stepper content.

### Reproduction Link
https://jsfiddle.net/9u7bt96m/

**Comment by nekosaur** [comment]
From #1015 
>[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got Event.

**Comment by johnleider** [comment]
Removed a $listener binding that really isn't needed.
