### ISSUE TITLE
[Feature Request] Can vuetify be used with BundleTracker and multiple bundles?

### ISSUE THREAD

**Issue by pbakiewicz** [vuetifyjs/vuetify#10124]
### Problem to solve
I'm trying to connect Vuetify with Django using webpack_loader. I still want to use django templates and only include needed components like this:
```    
<div id="toolbar_js">
            <Toolbar></Toolbar>
    </div>


    {% render_bundle 'chunk-vendors' %}
    {% render_bundle 'toolbar' %}
```
But I can't use it since vuetify requires me to wrap all my components in single v-app tag. Doing that in django tempaltes doesn't work, and wrapping v-app every components gives me many full screen v-apps. 

Is there a solution to this problem or can be in the future?

### Proposed solution
"v-app should only be used within your application ONCE." - I can't use vuetify in the context above. Please add some tag like v-component which will be similar to v-app but allowing including many of them.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
