### ISSUE TITLE
[Documentation] List menu for UI components on https://vuetifyjs.com/ should be in alphabetical order

### ISSUE THREAD

**Issue by kieperb** [vuetifyjs/vuetify#10121]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
every time i'm searching for "Form inputs & controls"

### Expected Behavior
alphabetical order

### Actual Behavior
"Form inputs & controls" is not in correct order
because it starts with an F not an I

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/why-vuetify" target="_blank">https://vuetifyjs.com/en/introduction/why-vuetify</a>

**Comment by DRoet** [comment]
Probably because it was inputs in the past 😅
