### ISSUE TITLE
[Feature Request] Sparkline Range

### ISSUE THREAD

**Issue by jlommori** [vuetifyjs/vuetify#10122]
### Problem to solve
The current implementation of the `v-sparkline` uses the max and min values of the `values` array to set the maximum and minimum values of the line. There are circumstances where it is necessary to define the max and min values so the line renders in a way to represent values in a range. For example, if you had a "room" that held 10 people, I would want to set the max to 10 and min to 0 so the sparkline can show a visual indicator of how full the room is.

### Proposed solution
Add a max and min value for how the sparkline renders

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by notestyle** [comment]
adding max, min value is important. Look if the values = [9,9,9,9,9,9] sparkline draws like zero. it's so weird.

**Comment by notestyle** [comment]
![Screen Shot 2020-11-19 at 12 12 03](https://user-images.githubusercontent.com/25055690/99620440-7bf7da80-2a60-11eb-8071-c3ffa060af94.png)
when values = [9,9,9,9,9,9]
