### ISSUE TITLE
[Bug Report] 分页的图标太大了，导致样式出错！The paging icon is too large, resulting in style errors!

### ISSUE THREAD

**Issue by playfulhd** [vuetifyjs/vuetify#10128]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 7

### Steps to reproduce
<v-pagination
      prev-icon="fa-angle-left"
      next-icon="fa-angle-right"
></v-pagination>

### Expected Behavior
pagination

### Actual Behavior
pagination

### Reproduction Link
<a href="https://github.com/playfulhd/ISSUE.git" target="_blank">https://github.com/playfulhd/ISSUE.git</a>

### Other comments
可能其他的组件也存在这种现象——fa5的图标比mdi的图标都大一些
------
this phenomenon may exist in other components - FA5 icons are larger than MDI icons

**Comment by jacekkarczmarczyk** [comment]
Sorry, screenshot is not a valid reproduction

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.
