### ISSUE TITLE
[Bug Report] v-calendar not displaying events correctly

### ISSUE THREAD

**Issue by Tomtommytomtom** [vuetifyjs/vuetify#10123]
### Environment
**Vuetify Version:** 2.2.1
**Last working version:** 2.1.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.74
**OS:** Linux x86_64

### Steps to reproduce
Create a v-calendar with event(s) that go for more than one day

### Expected Behavior
in the day view it shows the event on every single day of the duration

### Actual Behavior
in the day view it only shows on the start day of the event

### Reproduction Link
<a href="https://codepen.io/tomtommytomtom/pen/zYxpqpw?editors=1010" target="_blank">https://codepen.io/tomtommytomtom/pen/zYxpqpw?editors=1010</a>

**Comment by m-dl** [comment]
Yes, I can confirm too, example : `start:2020-02-02` & `end;2020-02-05`, is only visible on the `2020-02-02`  and `2020-02-05`, not on the `2020-02-03` for instance, when i'm on the "daily view"
