### ISSUE TITLE
[Documentation] No Search Bar

### ISSUE THREAD

**Issue by arun-333** [vuetifyjs/vuetify#10137]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
just use the link

### Expected Behavior
Search Bar to easily search tags

### Actual Behavior
No search bar in documentation for version 1.5

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/getting-started/quick-start" target="_blank">https://v15.vuetifyjs.com/en/getting-started/quick-start</a>

**Comment by KaelWD** [comment]
Duplicate of #8034
