### ISSUE TITLE
[Feature Request] Scroll to top within data table

### ISSUE THREAD

**Issue by cdecinkoKnight** [vuetifyjs/vuetify#10134]
### Problem to solve
When using the fixed-header option in v-data-table, we need the ability to scroll to the top when navigating to the next page of paged results.

### Proposed solution
Add a property to v-data-table that allows toggling between a default behavior of always scroll to top or maintain the current scroll position when going to next or previous pages.

**Comment by ibrahimBeladi** [comment]
Would be a nice feature to have. It does have a workaround though.

**Comment by cdecinkoKnight** [comment]
What is the workaround? I scoured the web and could not find anything other than how to get the page to scroll back to top, not the table.

**Comment by ibrahimBeladi** [comment]
[codepen](https://codepen.io/ibrahimbeladi/pen/xxbYRpq?editors=1010)

**Comment by cdecinkoKnight** [comment]
That only scrolls the page.  Add fixed-header and height=200 to that table. Now the rows scroll in the table body.  Scroll to the bottom of the table, click next page and you are at the bottom of the table. You have to scroll up to see the next rows in sequence.  https://codepen.io/ibrahimbeladi/pen/xxbYRpq?editors=1010

**Comment by ibrahimBeladi** [comment]
Sorry for dropping some of the details; here's [an updated codepen](https://codepen.io/ibrahimbeladi/pen/NWPYdZR?editors=1010) which will resolve your issue.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
