### ISSUE TITLE
[Bug Report] Outlined text field and autocomplete inside radio group have styling issues

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#10131]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
- Create a `v-radio-group`
- Add an input like `v-text-field` or `v-autocomplete` inside the radio group. Use `outlined` prop
- Add a label
- (Extra bug) add a `disabled` prop and an existing value inside the input

### Expected Behavior
Inputs, label and disabled styles work and look like inputs without a `v-radio-group`

### Actual Behavior
- Label is too high, with or without a value inside the input
- If input is disabled with an existing value, font will not appear like a `disabled` input looks like (should have a lower opacity)

### Reproduction Link
<a href="https://codepen.io/kotoriii/pen/yLypKPz" target="_blank">https://codepen.io/kotoriii/pen/yLypKPz</a>

### Other comments
Slightly related to https://github.com/vuetifyjs/vuetify/issues/9864 but scope also expanded to add autocomplete and added an extra related bug. The input styling inside the radio group seems to have issues altogether for some reason.

**Comment by jacekkarczmarczyk** [comment]
> Only one input in the codepen seems to be visible at a time (another bug?)

You can't use self closing tags in codepen
