### ISSUE TITLE
[Bug Report] Must v-card-text be a direct child of v-card?

### ISSUE THREAD

**Issue by jarkt** [vuetifyjs/vuetify#10132]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
```
<v-card>
	<v-form v-if="!saved">
		<v-card-text>
		  Unsaved text in black
		</v-card-text>
		...
	</v-form>
	<v-card-text v-else>
		Saved text in grey
	</v-card-text>
</v-card>
```

### Expected Behavior
grey v-card-text

### Actual Behavior
black v-card-text

### Reproduction Link
<a href="https://codepen.io/JT2809/pen/eYmyrdx" target="_blank">https://codepen.io/JT2809/pen/eYmyrdx</a>

### Other comments
Is it really intended, that v-card-text must always be a direct child of v-card?
I want to use a structure like above, but the result doesn't look as expected. (Wrong text color)

**Comment by KaelWD** [comment]
#7920

workaround is to add `class="text--secondary"`
