### ISSUE TITLE
[Bug Report] V-Select (and other inputs?) with dynamic :rules don't always update or not fully reactive?

### ISSUE THREAD

**Issue by brease-colin** [vuetifyjs/vuetify#10142]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
I've made a codepen that shows the difference in behavior between 'error-messages' and 'rules' using the same checks. I wonder if this difference is intended.

1. Change 'max' from '2' to '3'
2. Change 'min' from '1' to '4'
3. Change 'max' from '3' to '5'

### Expected Behavior
After step 2:
Both 'min' and 'max' selects should show error messages, both in 'rules' mode and 'error-messages' mode.

After step 3:
Both 'min' and 'max' selects should no longer show any error messages.

### Actual Behavior
After step 2:
Only 'error-messages' mode shows error messages for both 'min' and 'max' selects. The 'rules' mode only updates the directly changed select (min).

After step 3:
Only 'error-messages' mode removes the previously shown error messages. The 'rules' mode still shows an error on 'min'.

### Reproduction Link
<a href="https://codepen.io/brease-colin/pen/bGNLNaL?editors=1111" target="_blank">https://codepen.io/brease-colin/pen/bGNLNaL?editors=1111</a>

### Other comments
I used to validate inputs using error-messages, but moved to :rules, because errors are not shown immediately. However, copying the same checks without change to rules does not result in the same behavior as the example shows.

I think this is a bug, but maybe I'm missing something?

**Comment by KaelWD** [comment]
We used to watch for all changes to rules, but it caused an infinite loop if the rules array was defined in the template: #4635, #4688

Workaround is to force validation on the form when something changes (not viable if there's other unrelated inputs in it too): https://codepen.io/kaelwd/pen/OJPQzrO?editors=1011

**Comment by inad9300** [comment]
I'm experiencing an infinite loop even in the latest version when providing an array of rules (although I only seem able to reproduce it from unit tests).

```
<template>
  <v-textarea
    label="Message"
    v-model="message"
    :rules="rules" />
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class X extends Vue {

  get rules() {
    return this.requiredRule // Works
    return [this.requiredRule] // Causes requiredRule to be called indefinitely
  }

  requiredRule = (value: any) => value ? true : 'Required.'
}
</script>
```

**Comment by inad9300** [comment]
@KaelWD could you please keep the issue open? Or should I rather create a new one?

**Comment by inad9300** [comment]
@KaelWD It turns out, this problem happens only when a form is used to wrap the element containing the rules. The cause of the loop seems to be in the `hasError` watcher (https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VForm/VForm.ts#L55), currently implemented as:

```ts
const watcher = (input: any): (() => void) => {
  return input.$watch('hasError', (val: boolean) => {
    this.$set(this.errorBag, input._uid, val)
  }, { immediate: true })
}
```

Changing the implementation to the following fixes the issue:

```ts
const watcher = (input: any): (() => void) => {
  return input.$watch('hasError', (val: boolean) => {
    if (val) {
      this.$delete(this.errorBag, input._uid)
    } else {
      this.$set(this.errorBag, input._uid, val)
    }
  }, { immediate: true })
}
```

I'm not saying that this should be the solution, but it might give you a hint as to what is going on. And if doesn't but you agree that both are logically equivalent and the new code passes all the tests, please consider putting it in place! 😃

This problem does not seem to occur when lazy validation is used, which might be another hint...
