### ISSUE TITLE
[Bug Report] Label vertical alignment for v-radio-group

### ISSUE THREAD

**Issue by icleolion** [vuetifyjs/vuetify#10146]
### Environment
**Vuetify Version:** 2.2.3
**Last working version:** 2.2.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Add label prop to v-radio-group component

### Expected Behavior
Label to be centrally aligned vertically with the radio buttons

### Actual Behavior
Label is too high compared to radio buttons

### Reproduction Link
<a href="https://codepen.io/icleolion/pen/OJPQjdz" target="_blank">https://codepen.io/icleolion/pen/OJPQjdz</a>

### Other comments
Back in 2.1.18 I'm seeing a height of 24px for the label from this rule:
![image](https://user-images.githubusercontent.com/47498402/71941985-a546a980-31b3-11ea-83a9-03d7f14a7381.png)

Now in 2.2.3 I'm seeing a height of 20px for the label from this rule:
![image](https://user-images.githubusercontent.com/47498402/71942006-b0013e80-31b3-11ea-9663-8da8523f6e66.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/be965df0c8cd903f6c9d62e14ee25e7ade4518b4

**Comment by johnleider** [comment]
Fixed in 75f6197629d6c8baf7ab86e2a8b0d12ec0d444d2

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
