### ISSUE TITLE
[Bug Report] Buttons with a badge are no longer clickable

### ISSUE THREAD

**Issue by AssetKid** [vuetifyjs/vuetify#10144]
### Environment
**Vuetify Version:** 2.2.2
**Last working version:** 2.1.18
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Click button

### Expected Behavior
Button should be clickable

### Actual Behavior
Button is not clickable

### Reproduction Link
<a href="https://codepen.io/56d1w56d/pen/XWJZNGM" target="_blank">https://codepen.io/56d1w56d/pen/XWJZNGM</a>

**Comment by johnleider** [comment]
This has been reverted in fb5c5cc.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
