### ISSUE TITLE
[Bug Report] v-calendar .native modifier for v-on

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#10159]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
1. Open the playground link
2. Open the console
3. Find the error

![image](https://user-images.githubusercontent.com/2115696/72012176-75d28400-3229-11ea-91f8-81e50de5e7f4.png)

### Expected Behavior
No error

### Actual Behavior
Error

### Reproduction Link
This is the link from the officiel vue documentation.
<a href="https://codepen.io/auspex/pen/KKwoKZg?editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/KKwoKZg?editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
duplicate #9999
