### ISSUE TITLE
[Feature Request] v-chip-group one chip per line

### ISSUE THREAD

**Issue by poganytamastsys** [vuetifyjs/vuetify#10151]
### Problem to solve
I would like to preserve the functionality of the v-chip-group (or v-item-group), to have a model with an array, selectable inner chips, etc... But for the display, I need to display one chip per one row. Neither the overflow to the right, nor the column wrap is fine (because it will display chips next to each other), I need one chip per one row (list like display)

### Proposed solution
There should be a nowrap property, and using it with the column, it would remove the horizontal pagination, but won't wrap the chips. Or any other workaround is highly welcome.

**Comment by jacekkarczmarczyk** [comment]
Workaround with custom css:

https://codepen.io/jkarczm/pen/yLyjzgQ

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
