### ISSUE TITLE
[Bug Report] V-Select name prop does not work anymore

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#10152]
### Environment
**Vuetify Version:** 2.2.3
**Last working version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add a `name` prop to a `v-select`

### Expected Behavior
`name` prop appears in html element inspector inside `input` element.

### Actual Behavior
`name` prop is not visible in `input` element.

### Reproduction Link
<a href="https://codepen.io/kotoriii/pen/Jjopajz" target="_blank">https://codepen.io/kotoriii/pen/Jjopajz</a>

### Other comments
Still works in `v-autocomplete`

**Comment by MajesticPotatoe** [comment]
<https://github.com/vuetifyjs/vuetify/pull/9598>
more specifically 
[Input L415](https://github.com/Mouquette/vuetify/blob/4d8aeb9821561982ab52b9a9d6f20ab4b3a3ab53/packages/vuetify/src/components/VSelect/VSelect.ts#L415)
and
[Comboboc L72](https://github.com/Mouquette/vuetify/blob/4d8aeb9821561982ab52b9a9d6f20ab4b3a3ab53/packages/vuetify/src/components/VCombobox/VCombobox.ts#L72)

**Comment by KaelWD** [comment]
@Mouquette 
![image](https://media1.tenor.com/images/da783ffa838e693658a1bce55a44d3fd/tenor.gif)
