### ISSUE TITLE
[Bug Report] Bad error message - Error in v-on handler: "TypeError: oldDesc.slice is not a function"

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#10160]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Data table with option of sortDesc that's a bool instead of array

On here https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/VwYXwqN
Click calories and look at error message in console

vue.esm.js?a026:628 [Vue warn]: Error in v-on handler: "TypeError: oldDesc.slice is not a function"

found in

---> <VDataTableHeaderDesktop>
       <VSimpleTable>
         <VData>
           <VDataTable>
             <VCard>

vue.esm.js?a026:1897 TypeError: oldDesc.slice is not a function
    at VueComponent.toggle (vuetify.js?ce5b:8033)
    at VueComponent.sort (vuetify.js?ce5b:8081)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.invoker (vue.esm.js?a026:2188)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.Vue.$emit (vue.esm.js?a026:3897)
    at VueComponent.Vue.<computed> [as $emit] (backend.js:1793)
    at listeners.click (vuetify.js?ce5b:9886)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at HTMLTableCellElement.invoker (vue.esm.js?a026:2188)

### Expected Behavior
More relevant error message ie "must use array value"
Or just "handle it" ie cast into array format

And provide more clear examples on docs of that usage. 
This is very syntax heavy / specific thing, so if there are going to be little "gotchas" like this it needs to be clear.

### Actual Behavior
Throws error message in internal vuetify structure which is confusing.

### Reproduction Link
<a href="https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/VwYXwqN" target="_blank">https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/VwYXwqN</a>

### Other comments
I understand the docs now state it should be array. ie sortDesc: [true]
Keep in mind there are other parts other code where it warns the docs are invalid. ie The docs have "pagination" property still in slots for example, but that's shown as invalid. There can't be a double standard where sometimes the error messages on the system are correct and sometimes the docs are correct.

**Comment by johnleider** [comment]
The docs have been updated to properly reflect the value with a signature. There is an example using **sort-desc**: https://vuetifyjs.com/en/components/data-tables#sort-on-multiple-columns and the pagination slot works fine and as described.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by saike** [comment]
```sortDesc``` should be an array.
