### ISSUE TITLE
[Bug Report] data table headers are not vertically aligned under different sizes

### ISSUE THREAD

**Issue by craigbroadbear** [vuetifyjs/vuetify#10164]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Ignore codepen link, to reproduce go to https://vuetifyjs.com/en/components/data-tables

Slowly resize your browser width from full screen to small - you will notice at some point some of the headers are aligned high, some low.   

e.g. https://www.screencast.com/t/P2NbdnTU0A6

It can look very messy when you have lots of columns, with some up and some down.  e.g. up, down, up up down down up.  This is what happens to me most of the time with my tables, its not a one off resize thing like the example I gave.

### Expected Behavior
All the headers should be vertically aligned.

### Actual Behavior
Headers are not vertically aligned.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by craigbroadbear** [comment]
Setting a global style of:
 th {
        vertical-align: top;
    }
fixes the issue for me.

**Comment by jacekkarczmarczyk** [comment]
The problem is that sort icon is moved below the header text if it doesn't fit:

![image](https://user-images.githubusercontent.com/15625235/72200575-c6421f80-347d-11ea-847b-1fd5898f7b9b.png)

**Comment by lxr900** [comment]
Also have this issue. This is aggravated if some headers are left aligned and others right aligned. In right-aligned headers the arrow moves at the top, so in a given table the actual header can be on three different heights:
![image](https://user-images.githubusercontent.com/1043732/77156995-cde6fb80-6aa0-11ea-9cb4-3292980289ba.png)

In my case the following in my global css worked:
```css
.v-data-table-header th {
  white-space: nowrap;
}
```

**Comment by IsabelMeraner** [comment]
> In my case the following in my global css worked:
> 
> ```css
> .v-data-table-header th {
>   white-space: nowrap;
> }
> ```

this worked for me...   
If the screensize is too small, vuetify simply adds a scroll bar in order to view all table headers.

**Comment by AnhHoangQuach** [comment]
> Also have this issue. This is aggravated if some headers are left aligned and others right aligned. In right-aligned headers the arrow moves at the top, so in a given table the actual header can be on three different heights: ![image](https://user-images.githubusercontent.com/1043732/77156995-cde6fb80-6aa0-11ea-9cb4-3292980289ba.png)
> 
> In my case the following in my global css worked:
> 
> ```css
> .v-data-table-header th {
>   white-space: nowrap;
> }
> ```

this worked for me but if not working use need to use ::v-need

**Comment by ITJoePC** [comment]
This worked in Vuetify 3: 
```
.v-table thead th span {
  white-space: nowrap;
}
```
Please share if there's a "Vuetify" way to do this.
