### ISSUE TITLE
[Bug Report] Checkboxes in data-table are no longer centered when using 'text-center' on td

### ISSUE THREAD

**Issue by wubzz** [vuetifyjs/vuetify#10165]
### Environment
**Vuetify Version:** 2.2.3
**Last working version:** 2.1.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
See reproduction link

### Expected Behavior
Checkboxes should be centered when td contains class 'text-center'

### Actual Behavior
Checkboxes remain aligned to the left

### Reproduction Link
<a href="https://codepen.io/dvsimon/pen/WNbzwYB" target="_blank">https://codepen.io/dvsimon/pen/WNbzwYB</a>

### Other comments
Last known to be working in 2.1.13. Upgraded from 2.1.13 to 2.2.3.

Workaround:
```javascript
/deep/ td.text-center > .v-input--checkbox > div > div {
	justify-content: center;
}
/deep/ td.text-center > .v-input--checkbox > div > div > div {
	margin-right: 0px;
}
```

**Comment by KaelWD** [comment]
It doesn't work in v2.1.13 either. `.v-input` has had `text-align: left` since v1.1.0: https://github.com/vuetifyjs/vuetify/commit/bc439e7afc704982eb8596d9cb06daaf15ef4f9f#diff-9e158bdc475187e2b6ee9e576d6740e9R29

`<v-checkbox class="d-inline-flex"` can be used to do this.
