### ISSUE TITLE
[Bug Report] document.body.addEventListener('click') no working on dialog

### ISSUE THREAD

**Issue by PhuHoaframgia** [vuetifyjs/vuetify#10167]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.14.6

### Steps to reproduce
  mounted() {
    document.body.addEventListener("click", event => {
      console.log(event);
    });
  }

and click on the dialog 

### Expected Behavior
can get the event on  the dialog 

### Actual Behavior
 can't   console.log(event); 

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-u7wbw" target="_blank">https://codesandbox.io/s/vue-template-u7wbw</a>

**Comment by KaelWD** [comment]
Related: #6654, #3333

Was moved from the activator to the content in #1932 then added back to the activator in #3105. Possible not needed here any more.

**Comment by PhuHoaframgia** [comment]
could you tell me when do you release this one? @johnleider

**Comment by johnleider** [comment]
We do releases every Tuesday.

**Comment by PhuHoaframgia** [comment]
thank you @johnleider <3
