### ISSUE TITLE
[Feature Request] Need to make checkbox ennable when Selecting a row in a table

### ISSUE THREAD

**Issue by Roshmia** [vuetifyjs/vuetify#10179]
### Problem to solve
https://codepen.io/Roshmi_Jinto/pen/oNgqOmg?editable=true&editors=101
I need to make the checkbox ennabled  when i click on the paricular row itself insted of clicking on the checkbox. 

### Proposed solution
I need to make the checkbox ennabled  when i click on the paricular row itself insted of clicking on the checkbox. My data is dynamic data that is loaded at run time

**Comment by KaelWD** [comment]
Use the `click:row` event: https://codepen.io/kaelwd/pen/bGNvyRK?editors=1010

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
