### ISSUE TITLE
[Feature Request] validate a data that is unique in the database

### ISSUE THREAD

**Issue by haco3d** [vuetifyjs/vuetify#10170]
### Problem to solve
how to validate a data that is unique in the database and show the error with an input control of a form

### Proposed solution

when there is a unique data in the database it cannot be validated directly from vuetify, the idea is to simplify the validation code

**Comment by KaelWD** [comment]
You can use the `error-messages` prop to display custom validation messages. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
