### ISSUE TITLE
[Bug Report] v-switch (and other controls) change underlying value before animation ends

### ISSUE THREAD

**Issue by chrisborecki** [vuetifyjs/vuetify#10176]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Click on any switch control on the examples page. You will notice that attached action is executing immediately, not after animation finishes.

https://vuetifyjs.com/en/components/selection-controls#selection-controls

### Expected Behavior
Change event triggered after animation completes.

### Actual Behavior
Change event triggered immediately.

### Reproduction Link
<a href="https://codepen.io/chrisborecki/pen/mdyxXWB?editable=true&editors=101" target="_blank">https://codepen.io/chrisborecki/pen/mdyxXWB?editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Not a bug, and this is unlikely to be changed unless you have a very compelling reason for it.
