### ISSUE TITLE
[Bug Report] v-treeview load-children should be triggered more than once

### ISSUE THREAD

**Issue by whbjzzwjxq** [vuetifyjs/vuetify#10175]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
if the <load-children> function does not change the item-children props to array, 
opening item again will not trigger the <load-childen> function

### Expected Behavior
trigger <load-children> function again 
and the item should be added to array this.open
so this.open.length = 1

### Actual Behavior
nothing happened and this.open.length = 0

### Reproduction Link
<a href="https://codepen.io/whbjzzwjxq/pen/YzPaYVz?editable=true&editors=101" target="_blank">https://codepen.io/whbjzzwjxq/pen/YzPaYVz?editable=true&editors=101</a>

### Other comments
I think the trigger should be resused because sometimes the function will be useful

**Comment by whbjzzwjxq** [comment]
another bug here: 
oldSelectedCache in v-treeview = ['$_1', '$_2', '$_3', '$_4', '$_5']
buildTree in v-treeview will make selectedCache as [ '$_4', '$_5', '$_1', '$_2', '$_3'] 
the keys are actually the same but will emit('input')

**Comment by johnleider** [comment]
@whbjzzwjxq please create a new issue for a new bug

**Comment by awenger63** [comment]
see also #10587 ?
