### ISSUE TITLE
[Feature Request] VDataTable mobile select width

### ISSUE THREAD

**Issue by arneysebaert** [vuetifyjs/vuetify#10188]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.0

### Steps to reproduce
In the following example, when resizing the screen to mobile (500px I used). The header is replaced by a v-select, which can be used to sort. Only this only spans 1 column. It should span all columns (in this case 3), because there are 3 td-elements.

### Expected Behavior
the v-select in the header should span the whole width of the table

### Actual Behavior
the v-select in the header only spans width of the first td-element

### Reproduction Link
<a href="https://codepen.io/arneysebaert/pen/povVgBV" target="_blank">https://codepen.io/arneysebaert/pen/povVgBV</a>

**Comment by Chovin** [comment]
Hi @nekosaur, I think I'd like to take this on.

I have a question though. This: ![image](https://user-images.githubusercontent.com/17536161/73031238-4eb1be80-3e87-11ea-98ba-091f257dcef5.png)
when collapsed currently looks like this:
<img src="https://user-images.githubusercontent.com/17536161/73031217-422d6600-3e87-11ea-8acb-03222307205c.png" width=450>


We want the "Sort by" dropdown to span the whole row though.

I notice that with "Sort by" taking over all the headers, it's pretty difficult for the user to tell what column is what. Is that just the developer's responsibility to figure out how to add additional headers or to make sure the data is understandable without headers?

**Comment by nekosaur** [comment]
That's because the codepen is using the item slot, which overrides the mobile rows

**Comment by johnleider** [comment]
Due to limited bandwidth, moving to v2.3.x.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
