### ISSUE TITLE
[Feature Request] Mouse Hover in Sparklines Component

### ISSUE THREAD

**Issue by matheus-cintra** [vuetifyjs/vuetify#10189]
### Problem to solve
When a user sees a graph, he often wants to hover over a particular point in the graph to see the value at that particular point. With a mouse hover, that would solve the problem.

### Proposed solution
Implement mouse hover at specific point of sparkline.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
