### ISSUE TITLE
[Bug Report] VTooltip with attach prop wrong positioning

### ISSUE THREAD

**Issue by deraw** [vuetifyjs/vuetify#10183]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Linux x86_64

### Steps to reproduce
Click on the button to make the tooltip appear

### Expected Behavior
It should be positioned like a normal tooltip

### Actual Behavior
It's positioned at `left: 12px` and `top: 12px`

### Reproduction Link
<a href="https://codepen.io/Deraw/pen/qBEYWMq" target="_blank">https://codepen.io/Deraw/pen/qBEYWMq</a>

### Other comments
I don't know if this is an expected behavior, and if so how to make it positioned normally

**Comment by MajesticPotatoe** [comment]
You are looking for the `activator` prop, `attach` just specify where in the DOM the tooltip should detach to.

**Comment by deraw** [comment]
> You are looking for the `activator` prop, `attach` just specify where in the DOM the tooltip should detach to.

Thank you for your reply! You're right, and you made me realise that my need was more a menu than a tooltip :slightly_smiling_face:
