### ISSUE TITLE
[Bug Report] Manually changing v-model value used by v-tabs gets resetted

### ISSUE THREAD

**Issue by thebspin** [vuetifyjs/vuetify#10181]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
See codepen
Have a v-model with a data prop, change that data prop with a button in this case and the value switches and immediatly switches back

### Expected Behavior
To change tab to the value i set with the button

### Actual Behavior
Changes and gets resetted

### Reproduction Link
<a href="https://codepen.io/thebspin/pen/rNadpGZ?editable=true&editors=101" target="_blank">https://codepen.io/thebspin/pen/rNadpGZ?editable=true&editors=101</a>

**Comment by Namstel** [comment]
I've got a possible workaround:
https://codepen.io/namstel/pen/GRgdKom

I basically added the 4th tab and hid it using CSS.

**Comment by johnleider** [comment]
`v-tabs` by default must have a matching value. If you want to tab-items that do not have a corresponding tab, use the **optional** prop and pre-define the model.

https://codepen.io/johnjleider/pen/LYEmNpV?editable=true&editors=101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by thebspin** [comment]
Never would have guessed that's what optional was for, even after reading it. Thanks!

**Comment by thomasklein-winemaker** [comment]
@johnleider `@change` doesn't work with your suggested approach.

**Comment by Rahularya01** [comment]
` <v-tab href="#tab-1">Tab1</v-tab>
 <v-tab id="openTab" href="#tab-2">Tab2</v-tab>
<v-tab-item id="tab-1" key="tab-1">Tab One <v-btn @click="changeTab()">Next</v-btn></v-tab-item>
<v-tab-item id="tab-2" key="tab-2">Tab Two</v-tab-item>

changeTab() {
      let tab = document.getElementById("openTab");
      tab.click();
    }
`

You can use this to change tab on button click

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
