### ISSUE TITLE
[Bug Report] Data table not updating

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#10190]
### Environment
**Vuetify Version:** 2.2.3
**Last working version:** 1.5.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Go to reproduction: https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv

1) Click "Fail" on first one, works as expected, word changes to failed
2) Click "Fail" on tool tip (any of spinning ones), the props.item.status does not update

### Expected Behavior
It to detect update

### Actual Behavior
It fails to detect update

### Reproduction Link
<a href="https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv" target="_blank">https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv</a>

### Other comments
There's something strange "blocking" it. ie even the  {{props.item.status}} outside of tooltip does not render. yet if inspect in dev tools it has clearly updated.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by swirlingsand** [comment]
@KaelWD  Stop closing tickets without understanding or reading them.
I updated the sample to include the status that's on there.
It's one thing to include as repro but don't jump to closing something like that!
https://github.com/vuetifyjs/vuetify/issues/10193

**Comment by KaelWD** [comment]
I read the issue and noticed the loading items were missing a status value. When I added `status: 'loading'` to one of them it worked as expected so I closed the issue. Your updated codepen no longer matches the issue description, but if I change the click handler to set the status to `'failed'` as before then both buttons work: https://codepen.io/kaelwd/pen/QWwrgBb?editors=1010  
Removing the status property from the second item shows the original issue: https://codepen.io/kaelwd/pen/eYmrRjg?editors=1010

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
