### ISSUE TITLE
[Feature Request] Component custom style

### ISSUE THREAD

**Issue by djkenneth** [vuetifyjs/vuetify#10197]
### Problem to solve
I'm trying to custom style the component I want to style but it's hard. You need to find the specific class 

### Proposed solution
Put all the css to every v element so that we can custom style it.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
