### ISSUE TITLE
[Feature Request] Support vue-cli-service build --inline-vue

### ISSUE THREAD

**Issue by perspectivus1** [vuetifyjs/vuetify#10198]
### Problem to solve
I'm trying to create a Vuetify/Vue component to be consumed as a library. Following Vue's [documentation](https://cli.vuejs.org/guide/build-targets.html#library), I use the `vue-cli-service build --target lib` command.

This works well. However, when trying to use a newly supported flag `--inline-vue`, Vue instantiates its own instance, preventing the Vuetify plugin from loading.

### Proposed solution
Is there a way to support this?

**Comment by KaelWD** [comment]
No, you'd have to include everything you want of vuetify in the library too. `--inline-vue` is for standalone libraries, not something that's supposed to be used as part of another vue application.

**Comment by perspectivus1** [comment]
@KaelWD, thanks for the prompt response.

> you'd have to include everything you want of vuetify in the library too

That was precisely my question: how do I build a Vue/Vuetify component as a library, preferably using `vue-cli-service` (see related issue [#8576](https://github.com/vuetifyjs/vuetify/issues/8576))?

In the [Webpack example](https://vuetifyjs.com/en/getting-started/quick-start#webpack-install) on your website, you pass an instance of `vuetify` to Vue's constructor:
```js
new Vue({
  vuetify,
}).$mount('#app')
```

Is there a way to tell my Vue component that it depends on Vuetify without passing an instance of `vuetify` to the component's constructor?

> --inline-vue is for standalone libraries, not something that's supposed to be used as part of another vue application

I'm a bit confused. The [Vue documentation](https://cli.vuejs.org/guide/build-targets.html#library) for `--target lib` states that a `.vue` file can be specified as entry to the library. In fact, the default entry is `src/App.vue`.

**Comment by KaelWD** [comment]
> how do I build a Vue/Vuetify component as a library

https://stackoverflow.com/a/59123646/2074736   
https://github.com/vuetifyjs/vuetify-loader/issues/70

> Is there a way to tell my Vue component that it depends on Vuetify

Are you using it in an app that itself uses vue? If so you have to either wrap the vuetify constructor in your own (which then probably makes it incompatible with vuetify separately) or require consumers to instantiate vuetify themselves. If not and the component is something standalone then presumably you've got a `new Vue()` somewhere to hook in to. 

The vue-cli issue that resulted in `--inline-vue`: https://github.com/vuejs/vue-cli/issues/4055

> a .vue file can be specified as entry to the library

dunno, that probably isn't intended to be used with `--inline-vue`

I can't really give any more advice than that without knowing your specific use case.

**Comment by perspectivus1** [comment]
> Are you using it in an app that itself uses vue?

The app developers that will use the library write the app in Vue, but _are not / should not be_ aware that the library uses Vuetify. Is this use-case supported? Is this possible?

**Comment by KaelWD** [comment]
You don't want inline-vue then or they'll end up with #4068

> should not be aware that the library uses Vuetify

You still need to do the whole `new Vuetify()` thing, so you'd probably wrap that in your own plugin somehow.

**Comment by Haga14** [comment]
@perspectivus1 did you ever find a solution for this? I'm currently also creating a vue library that uses vuetify and I'm having this issue as well
