### ISSUE TITLE
Dropdown component item click not working on latest phones (tested in Browserstack)

### ISSUE THREAD

**Issue by prograhammer** [vuetifyjs/vuetify#102]
Great work! Love this project! Keep going! But there's a bug preventing me from using dropdowns on mobile...

Steps to repeat problem:

1. Go to Browserstack and choose Android Samsung S7 or iPhone 6s (others probably affected, but I just checked these).
2. Go to https://vuetifyjs.com/components/dropdowns
3. Scroll down until you see the first blue button in the first example with the text "CLICK DROPDOWN". Click that button so that the dropdown menu appears downward. Notice it appears over the button below with the text "CLICK WITH LABELS". This is good and correct.
4. Now click the second "Click Me" item in that dropdown. Notice the black button underneath ("CLICK WITH LABELS") gets automatically clicked. If you keep repeating this test, sometimes the button below will actually open its menu too.
5. In my own project, I noticed it was difficult (almost impossible) to get an href link to open on a dropdown on my Samsung S7. It seems something weird is going on with clicking events on mobile. Maybe the Body click event is registering first and the dropdown closes before it receives the click event?

![bs_realdroid_mobile_samsung galaxy s7-6 0-1440x2560 1](https://cloud.githubusercontent.com/assets/4474660/22099586/95305410-ddf1-11e6-8f24-d9f7b056cd86.jpg)

![bs_realdroid_mobile_samsung galaxy s7-6 0-1440x2560](https://cloud.githubusercontent.com/assets/4474660/22099525/4ed95840-ddf1-11e6-95e5-2cea41ce4e6b.jpg)

**Comment by johnleider** [comment]
Dropdowns (future menus) are being refactored for next release so I'll see if I can resolve this.
