### ISSUE TITLE
[Bug Report] VSkeletonLoader rendering default slot unconditionally

### ISSUE THREAD

**Issue by lassesteffen** [vuetifyjs/vuetify#10201]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.2

### Steps to reproduce
1. Create a skeleton loader
2. Reference an attribute of an undefined object
3. See that there is a console error about it

### Expected Behavior
V-skeleton-loader works similar to a v-if component and does therefore only render the content in the default slot once the loading flag is false.

### Actual Behavior
The undefined object is accessed even when the skeleton loader is still loading. The slot is not rendered conditionally

### Reproduction Link
<a href="https://codepen.io/ellazlo/pen/GRgGovK" target="_blank">https://codepen.io/ellazlo/pen/GRgGovK</a>

### Other comments
Is there any workaround? Is this the intended behaviour? If yes than it's kinda unpractical for data fetching, or am I misunderstanding something here?

**Comment by johnleider** [comment]
This would happen with any custom component: https://codepen.io/johnjleider/pen/oNgyxWX?editors=1011

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Only if you don't conditionally render the slot: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSkeletonLoader/VSkeletonLoader.ts#L146

**Comment by KaelWD** [comment]
Vue renders slots when proxying them to `this.$slots`, so it's still broken unless you use a scoped slot: https://codepen.io/kaelwd/pen/qBEKNYP

**Comment by bblanchon** [comment]
This `v-slot` trick should definitely go into the documentation.
