### ISSUE TITLE
Enhancement Request - Click on list with checkbox

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#1020]
Checking the list components, I noticed that there's a option to create a list with checkboxes, looking into it I tried to click in the list to activate the checkbox and nothing happened, so I'm opening this issue to request a enhancement to this component.

Once the use click on the list item, if there's a check box, toggle it.

The example can be found in this page: https://vuetifyjs.com/components/lists

Example 9.

**Comment by nekosaur** [comment]
This is something that you do yourself. See example markup below.

```vue
<v-list-tile avatar @click.capture.stop="widgets = !widgets">
  <v-list-tile-action>
    <v-checkbox v-model="widgets"></v-checkbox>
  </v-list-tile-action>
  <v-list-tile-content>
    <v-list-tile-title>Auto-add widgets</v-list-tile-title>
    <v-list-tile-sub-title>Automatically add home screen widgets</v-list-tile-sub-title>
  </v-list-tile-content>
</v-list-tile>
```

I haven updated the documentation example in dev docs.
