### ISSUE TITLE
[Feature Request] how to display a  serial number without slot

### ISSUE THREAD

**Issue by uphone** [vuetifyjs/vuetify#10204]
### Problem to solve
i want to display a  serial number column, when i use body slot, some functions does not work, so if there is way to display a searial number column ?

### Proposed solution
i want to display a  serial number column, when i use body slot, some functions does not work, so if there is way to display a searial number column ?

**Comment by jacekkarczmarczyk** [comment]
`item.<name>` slot

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by uphone** [comment]
discord chart room is bad, can not open : https://community.vuetifyjs.com

**Comment by KaelWD** [comment]
Overthrow your government.
