### ISSUE TITLE
[Bug Report] VDataTable - scoped slot page-text doesn't work

### ISSUE THREAD

**Issue by gtopsis** [vuetifyjs/vuetify#10206]
### Environment
**Vuetify Version:** 1.5.21
**Vue Version:** 2.5.22
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Use scoped slot page-text inside a vDataTable component

```
<template v-slot:footer.page-text="{ pageStart, pageStop }">Items: {{ pageStart }} - {{ pageStop }}
</template>
```

### Expected Behavior
Message in the footer: "Items: X - X"

### Actual Behavior
Message in the footer: "X-X of X"

### Reproduction Link
<a href="https://jsfiddle.net/c1bwau4z/3/" target="_blank">https://jsfiddle.net/c1bwau4z/3/</a>

### Other comments
I have already seen issue https://github.com/vuetifyjs/vuetify/issues/8120, but it refers to vuetify v.2.0.1. 

According to vuetify v1.5.22 the above feature should also work.

**Comment by jacekkarczmarczyk** [comment]
`v-slot` syntax works in vue 2.6+

**Comment by gtopsis** [comment]
@jacekkarczmarczyk jsfiddle has not saved the latest version in which I used v-slot:footer.page-text.
The issue is *still* there even if I do the updates that you suggest. You can check the  it below.

https://jsfiddle.net/e19gpksx/

It seems that commit 5f33175 solved it but for later versions of vuetify (v2+).

**Comment by jacekkarczmarczyk** [comment]
Oh, you want it in 1.5, sorry - there is not page-text slot indeed, you need to use `rows-per-page-text` prop. 
https://v15.vuetifyjs.com/en/components/data-tables

**Comment by jacekkarczmarczyk** [comment]
Or is it?

**Comment by KaelWD** [comment]
In 1.5 the slot is `pageText` not `page-text`

**Comment by gtopsis** [comment]
@jacekkarczmarczyk @KaelWD Thanks
