### ISSUE TITLE
[Bug Report] Data Table pagination event not updating on search/filter

### ISSUE THREAD

**Issue by Nimbock** [vuetifyjs/vuetify#10212]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Type something in search to filter

### Expected Behavior
pagination event should update like page-count

### Actual Behavior
Pagination is only updated by changing the page, but not in the input field on event pagination

### Reproduction Link
<a href="https://codepen.io/Nimbock/pen/bGNKXZe" target="_blank">https://codepen.io/Nimbock/pen/bGNKXZe</a>

### Other comments
tried to find out how many entries there are after filtering

**Comment by asadhshujau** [comment]
after this update server side data fetching is going to an infinite loop for me.
used to work on 2.2.11

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
