### ISSUE TITLE
[Feature Request] Responsive V-Btn Button size, based on viewport

### ISSUE THREAD

**Issue by fadafez** [vuetifyjs/vuetify#10217]
### Problem to solve
a v-btn (button) has different properties to set the size of the button:

- x-small
- small
- large 
- x-large

With the help of vuetify breakpoints, one can decide when to enable each one of the property.

I felt the need of this feature while working in a view with very little space.  
I had to spread the breakpoint detection code around the application / components and it's very redundant. 

Before to implement this feature globally in my application, I would like to understand if I'm missing something that it's already included, or better, if is not already implemented I think that it would be a nice thing to have. 

It can speed up a lot the work when designing responsive interfaces with many buttons.

[![Vuetify Responsive Button](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vuetify-template-sfm7q?fontsize=14&hidenavigation=1&theme=dark)

As you can see, I set the properties for the button and icon, plus, the text is hidden on small displays, to save some space and avoid cluttering. This is particularly important when you want to keep all the buttons on one single line (like a button group / toolbar ) 

### Proposed solution
- A "responsive" property. When enabled: the button size is linked to breakpoint detection
- An eventual icon inside the button, gets resized with the same logic
- The text is hidden automatically when the viewport is smaller than the specified value

Yes, the actual situation is not bad, 
but when you have many buttons, located in many components,  then you need to apply your logic to each button, icon and text...  

Creating a custom component would be an option. But it's always nicer to have everything packed and ready to use :-) 

Breakpoints are often a good source of error, for me at least. 

Best Regards
F.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by fadafez** [comment]
Ok...there's a better way to auto size buttons, or it's me missing something? 

Thanks ;)

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/oNgraYR?editors=1010

**Comment by fadafez** [comment]
Thanks for the code @jacekkarczmarczyk, that's really neat.

**Comment by LucidThought** [comment]
The code that @jacekkarczmarczyk provided is awesome, but I'm finding that it doesn't work for mobile displays. I can shrink the viewport, and the button components shrink with it until it gets to a width of 600px.

If I'm understanding it correctly (and it may be the case that I am not), the $vuetify.breakpoint.name is in the set of [xs, sm, md, lg, xl]; what do I need to do to get this to work for mobile?

**Comment by larryh** [comment]
This worked for me to get the button to appear smaller in mobile:
`        <v-btn
           :small="$vuetify.breakpoint.mobile"
           @click="cancel"
        >
          Close
        </v-btn>
`

BTW, can't see why they decided not to add this functionality because the size of many things can depend on whether or not the page is being viewed on a mobile device. For me, when I fired up a v-dialog box in mobile my 'Close' button looked kinda overpowering compared to the rest of the contents.

But  then again, I appreciate the heck out of what the Vuetify team is doing for us, so I can't complain too much. ;-)
