### ISSUE TITLE
Dynamic prefix (v-) on component name prevents code completion 

### ISSUE THREAD

**Issue by juan-tonina** [vuetifyjs/vuetify#1021]
From what I can see, every component is defined as (for example) `navigation-drawer` and then, on the `plugin(Vue) `method, an uppercase "V" is being concatenated. 
So now my IDE thinks that the component has no` v-` prefix, and does not recognize it (depriving me of auto complete, navigation to source, docs, etc). I think I understand the idea behind adding a prefix to every component, but adding it dinamically is preventing many features that would make development easier.

I propose:
- Static component names (keep the `v-`, but add it as part of the name, not dinamically)

**Comment by johnleider** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/commit/16515c3ebb9734218ef3d833b6c5cc56a7cc65c7
