### ISSUE TITLE
[Bug Report] can't find VSparkline/VSparkline.sass

### ISSUE THREAD

**Issue by jaredhan418** [vuetifyjs/vuetify#10218]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
when webpack compiling.

### Expected Behavior
compile success.

### Actual Behavior
 throw Error :
This relative module was not found:

* ../../../src/components/VSparkline/VSparkline.sass in ./node_modules/vuetify/lib/components/VSparkline/VSparkline.js

### Reproduction Link
<a href="https://www.github.com/vuetifyjs/vuetify.git/tree/master/packages/vuetify/src/components/VSparkline" target="_blank">https://www.github.com/vuetifyjs/vuetify.git/tree/master/packages/vuetify/src/components/VSparkline</a>

**Comment by MajesticPotatoe** [comment]
Are using `npm` ? Can you try deleting your node_modules and try again.

**Comment by jaredhan418** [comment]
yes, I am using `npm` , I deleted my `node_modules` and try again and again, not work.
and when I create a file name `'VSparkline.sass'` at path `/src/components/VSparkline`, every thing is done.
I am using Vuetify by  a la-carte way, may it weird behavior because the `vuetify-loader`?

**Comment by nwtgck** [comment]
Hi, I have the same problem after 2.2.4.

In addition, I have other problems of `This relative module was not found:` in `VDialog` and `VMenu`, when bumping from 2.1.18 to 2.2.0. So, in 2.1.18, it works properly but after 2.2.0 I had the problem. (<https://github.com/nwtgck/piping-ui-web/pull/180>)

```
...
5:35:41 AM:  ERROR  Failed to compile with 2 errors8:35:41 PM
5:35:41 AM: This relative module was not found:
5:35:41 AM: * ../../util/ThemeProvider in ./node_modules/vuetify/lib/components/VDialog/VDialog.js, ./node_modules/vuetify/lib/components/VMenu/VMenu.js
5:35:41 AM:  ERROR  Build failed with errors.
...
```

My build is on a very clean environment. I use `npm ci` and built on a cloud (Netlify).

**Comment by johnleider** [comment]
What version of vuetify-loader?

**Comment by nwtgck** [comment]
Sorry. This is my mistake. Cache on Netlify was enabled. After removing cache, I have no errros of `VDialog.js`, `VMenu .js` and also `VSparkline.js`.  So, my problem was solved!

**Comment by jaredhan418** [comment]
my npm repo's problem, now every thing is done. thx.
