### ISSUE TITLE
[Bug Report] VTextField wrapper passing all slots

### ISSUE THREAD

**Issue by guillaumeduliscouet** [vuetifyjs/vuetify#10215]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
Try to use a regular slot the same way as a scoped slot in a `VTextField` (`<template v-slot:prepend="data"></template>`)

### Expected Behavior
The slot should render anyway

### Actual Behavior
The slot does not render

### Reproduction Link
<a href="https://codesandbox.io/s/delicate-lake-2ckph" target="_blank">https://codesandbox.io/s/delicate-lake-2ckph</a>

### Other comments
I'm trying to pass all slots without listing them explicitly, and using `$scopedSlots` does not give a way to distinguish if a slot is "scoped" or not.
Using `$slots` is a work around (but it seems on the way to deprecation according to vue documentation)
I first thought it was a `Vue` issue, but here is a working repro with basic Vue components: https://codesandbox.io/s/zen-euler-tle67

Code to pass all slots (scoped and regular):
```
<template v-for="(_, slotName) in $scopedSlots" v-slot:[slotName]="slotData">
  <slot :name="slotName" v-bind="slotData"/>
</template>
```

**Comment by KaelWD** [comment]
> using $scopedSlots does not give a way to distinguish if a slot is "scoped" or not.

If it's in $scopedSlots but not $slots then it's "scoped". You might want to use a render function for this instead, it's much simpler to just do `scopedSlots: this.$scopedSlots`

**Comment by guillaumeduliscouet** [comment]
@KaelWD Thank you for your answer. You're right about the render function it seems more appropriate.
But to be clear, even if it is conter intuitive, `$scopedSlots` does include also `$slots`:

> All $slots are now also exposed on $scopedSlots as functions. If you work with render functions, it is now recommended to always access slots via $scopedSlots, whether they currently use a scope or not. This will not only make future refactors to add a scope simpler, but also ease your eventual migration to Vue 3, where all slots will be functions.

https://vuejs.org/v2/api/#vm-scopedSlots

This can be seen in https://codesandbox.io/s/zen-euler-tle67 in the `Wrapper.vue` passing down all `$scopedSlots` is enough.

**Comment by KaelWD** [comment]
> `$scopedSlots` does include also `$slots`

Correct, but `$slots` doesn't contain `$scopedSlots`:

`v-bind:foo` -> both `$slots` and `$scopedSlots`
`v-bind:foo="data"` -> only `$scopedSlots`

`<slot>` in templates is now compiled to use `$scopedSlots` but we use render functions everywhere and haven't updated them all yet, which is why the example with custom components works but not with ours.

**Comment by guillaumeduliscouet** [comment]
So what do you think about migrating the code base to always use `$scopedSlots`? I do not think it would be breaking, but it's difficult to be sure of that.

**Comment by johnleider** [comment]
At this point in time there is no reason to. We have already started v3 development with the next Vue version in which case scopedSlots and slots will be merged.

**Comment by johnleider** [comment]
At this time I'm going to say that this is not something we will work on as part of any 2.x bug fixes. v3 brings a unified slot pattern and will naturally resolve this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
