### ISSUE TITLE
[Bug Report] V-Img stretches within a flexbox container

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#10219]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
Open the code pen.

### Expected Behavior
The images should have their original dimensions.

### Actual Behavior
The images are stretched to the full size of the viewport.

### Reproduction Link
<a href="https://codepen.io/gotson/pen/ZEYjaWN?editors=1010" target="_blank">https://codepen.io/gotson/pen/ZEYjaWN?editors=1010</a>

### Other comments
Adding `flex-grow-0` on the `v-img` seems to solve the problem, codepen: https://codepen.io/gotson/pen/WNbKXGg?editors=1010

**Comment by johnleider** [comment]
This is an unfortunate side effect of supporting all the functionality that `v-img` does. In this case either assign a max-width or use `img`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
