### ISSUE TITLE
[Documentation] Please update API explorer with the link to the desired component page

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#10210]
### Problem to solve
Hi.
The API explorer is great. It allows to quickly check the component props. 
Could you please update it with the link to the found component page?
For example, I type `v-speed-dial` and see it's props. Then I want to go to the page, related to this component to check some examples etc. I can not find it in the side menu, that's why I use API explorer. But there's no link to the component page as well. 

### Proposed solution
Just a link to the component page anywhere below the search bar is enough.

**Comment by MajesticPotatoe** [comment]
duplicate #9602
