### ISSUE TITLE
[Bug] Placeholder of VTextField is too emphasized??

### ISSUE THREAD

**Issue by nwtgck** [vuetifyjs/vuetify#10221]
### Problem to solve
Allow users to distinguish filled input and placeholders. 

In the current version (2.2.4), a placeholder of `<v-text-field>` without input is like the following. I think the placeholder is too black.
![image](https://user-images.githubusercontent.com/10933561/72399636-1ecd3180-378a-11ea-8724-1f5fdffe620d.png)

Here is a filled `<v-text-field>`. I cannot distinguish those easily.
![image](https://user-images.githubusercontent.com/10933561/72399720-4e7c3980-378a-11ea-84c6-6f42f91f9c09.png)

When I unfocused on the element, `<v-text-field>` is like the following. It's very similar to the first one, which is empty.
![image](https://user-images.githubusercontent.com/10933561/72399758-6e136200-378a-11ea-9300-97d2feee3731.png)

CodePen: <https://codepen.io/nwtgck/pen/VwYBrPp?editable=true&editors=101>

### Proposed solution
More light gray for placeholder.

**Comment by KaelWD** [comment]
b4ad01a4d1308616135fc158c85373ffe88707e6

**Comment by nwtgck** [comment]
@KaelWD Thanks! Will b4ad01a solve this issue?

**Comment by KaelWD** [comment]
No that's what caused it.

**Comment by ibrahimBeladi** [comment]
> MD2 doesn't have placeholders

[Yet, placeholders are shown in the images](https://material.io/components/text-fields/#filled-text-field)

**Comment by KaelWD** [comment]
Ah right, must have missed it because it doesn't appear in any text or the specs section.

**Comment by nwtgck** [comment]
@johnleider Thanks!
