### ISSUE TITLE
[Bug Report] V-img inside flexbox with max-height has incorrect width

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#10222]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
Open the code pen.

### Expected Behavior
The images should display in the center of the screen, next to each other.
The rendering should look like this: https://codepen.io/gotson/pen/povZdyq?editable=true&editors=101

### Actual Behavior
The image has the correct aspect ratio, but the containing box has an incorrect width which correspond to the original width of the image (here 2000px), resulting in both images having extra space on left/right.

### Reproduction Link
<a href="https://codepen.io/gotson/pen/povZdPY?editors=1010" target="_blank">https://codepen.io/gotson/pen/povZdPY?editors=1010</a>

**Comment by johnleider** [comment]
The linked reproduction is the expected behavior. If you justify center flex-items, they will only take up the necessary space.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
