### ISSUE TITLE
[Bug Report] VStepper looses state when making vertical property conditional

### ISSUE THREAD

**Issue by daniellionel011** [vuetifyjs/vuetify#10220]
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Linux

### Steps to reproduce
I recreated a simpler version of the problem that I am facing. The codepen should work just like it is.

### Expected Behavior
I expect the v-stepper to align itself vertical once the the screen is smaller or equal to medium ($vuetify.breakpoint.mdAndDown).

### Actual Behavior
The v-stepper aligns itself vertical, but the component seems to loose its state and does not load the content nor the current step when I make the screen smaller or the other way around.

### Reproduction Link
<a href="https://codepen.io/daniellionel011/pen/NWPBvOx" target="_blank">https://codepen.io/daniellionel011/pen/NWPBvOx</a>

### Other comments
I tried some hacks with the v-resize directive, for example changing the component key, setting the "stepper" variable (which is v-modeled to the v-stepper component) to 0 and back to it's previous state on the next tick (which actually sometimes worked, but not always). But I can't get it to work.

**Comment by johnleider** [comment]
Force the stepper to rehydrate: https://codepen.io/johnjleider/pen/WNbgLJe

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
