### ISSUE TITLE
[Feature Request] date picker with custom locale

### ISSUE THREAD

**Issue by yimankaing** [vuetifyjs/vuetify#10224]
### Problem to solve
We able to write custom locale because km.ts in locale folder doesn't exist. I would like to do fully translate all vuetify components in Khmer.

### Proposed solution
Thanks

**Comment by johnleider** [comment]
Here is a guide on how to set all of that up: https://vuetifyjs.com/en/customization/internationalization

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
