### ISSUE TITLE
[Bug Report] wrap-word does not work on v-list-item-title/subtitle

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#10239]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Ubuntu undefined

### Steps to reproduce
I am using [`v-list`][1] component of Vuetify.
I have a bit long text to display within v-list-item-subtitle component. This text does not display totally:

[![enter image description here][2]][2]

To avoid this issue, I used what I use in similar situations successfully: I opt to apply a class with the CSS property [`word-wrap`][3] set to `break-word`:

    .wrap-text: {
      word-wrap: break-word;
    }

used this way:

    <v-list-item-subtitle v-html="item.subtitle" class="wrap-text"></v-list-item-subtitle>

This does not fix the issue. I noticed the same behavior when I use `v-list-item-title`.

[Codepen][4]

  [1]: https://vuetifyjs.com/en/components/lists
  [2]: https://i.stack.imgur.com/JQ6Zk.png
  [3]: https://www.w3schools.com/cssref/css3_pr_word-wrap.asp
  [4]: https://codepen.io/begueradj-the-sasster/pen/BayOZWJ

### Expected Behavior
Long text should show by applying the CSS class I mentioned

### Actual Behavior
Part of the text is displayed. The rest is replaced by 3 dots.
I tried to wrap the text inside a `div` element where I also I apply the CSS class above, but it did not help.

### Reproduction Link
<a href="https://codepen.io/begueradj-the-sasster/pen/BayOZWJ" target="_blank">https://codepen.io/begueradj-the-sasster/pen/BayOZWJ</a>

**Comment by begueradj** [comment]
I did not choose the right CSS property

**Comment by eku-code** [comment]
Hello! Which property did you use to avoid this issue?

**Comment by eku-code** [comment]
I found the solution here : https://stackoverflow.com/questions/59769385/wrap-word-does-not-work-on-v-list-item-title-subtitle

<v-list-item-title style="white-space: normal;">
                  {{ item.text }}
                </v-list-item-title>

**Comment by eku-code** [comment]
white-space: normal;

**Comment by begueradj** [comment]
Sorry for the late reply, I read your comments only now ... and yeah, I asked that question on StackOverflow, good you did not give up and made more efforts to search for the solution. @eku-code
