### ISSUE TITLE
[Bug Report] :show-arrows="false" doesn't work.

### ISSUE THREAD

**Issue by oariik** [vuetifyjs/vuetify#10238]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.13.6

### Steps to reproduce
please

### Expected Behavior
check

### Actual Behavior
your

### Reproduction Link
<a href="https://github.com/" target="_blank">https://github.com/</a>

### Other comments
code!

**Comment by KaelWD** [comment]
please

create

a

proper

issue!
