### ISSUE TITLE
[Documentation] Some components on the documentation are not vertically centered on Safari

### ISSUE THREAD

**Issue by lmuzquiz** [vuetifyjs/vuetify#10232]
### Environment

**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
Just open it on Safari 13.0.4

### Expected Behavior
Component is supposed to be vertically centered

### Actual Behavior
Some components are on the bottom of the box instead

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/toolbars" target="_blank">https://vuetifyjs.com/en/components/toolbars</a>

### Other comments
Checkout the screen recording: https://drive.google.com/file/d/1D0pz29gdbx1AQayngVfo4gPzf5GRRfH5/view?usp=sharing

**Comment by KaelWD** [comment]
Duplicate of #11618
