### ISSUE TITLE
[Documentation] website is down

### ISSUE THREAD

**Issue by changsijay** [vuetifyjs/vuetify#10234]
### Environment

**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OSX

### Steps to reproduce
visit https://vuetifyjs.com/

### Expected Behavior
connected

### Actual Behavior
cannot connected

### Reproduction Link
<a href="https://vuetifyjs.com/" target="_blank">https://vuetifyjs.com/</a>

**Comment by xxlxx-x** [comment]
Shanghai.China too

**Comment by KeoabetsweMorake** [comment]
Johannesburg, South Africa +1

**Comment by num-lock** [comment]
This is a known issue for quite a while already.

https://twitter.com/vuetifyjs

https://t.co/VVES3vsUfM

Also, the issue tracking in this repo is mainly for bugs in the code and vuetify itself and not for offline servers from random cloud providers.

**Comment by Radiergummi** [comment]
Is the website source available in some public repository, perhaps? Thought I was being clever, just looking for the source files to find the documentation I need currently, but no luck.

**Comment by MajesticPotatoe** [comment]
This has been resolved.
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
