### ISSUE TITLE
version 2.2.4 sparklines error

### ISSUE THREAD

**Issue by flahol** [vuetifyjs/vuetify#10231]
Hi 
I've just updated vuetify to version 2.2.4 and I have an error when npm servve.
I installed the previous version 2.2.3, no error

**Comment by Lavhe** [comment]
HI @flahol i had the same problem, i just had to delete node_modules and run npm install again

**Comment by flahol** [comment]
@Lavhe,
thanks for the info, I'll give it a try

**Comment by the-owl** [comment]
No need to remove whole node_modules, it's enough to clear the cache: `rm -rf node_modules/.cache/`

**Comment by roberta-fiume** [comment]
@the-owl thanks!! It fixed the issue for me!
