### ISSUE TITLE
[Bug Report] keydown event not working on v-combobox component

### ISSUE THREAD

**Issue by jeff039** [vuetifyjs/vuetify#10240]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.2

### Steps to reproduce
Focus the combobox and press the key "ENTER"

### Expected Behavior
Two alerts have to be shown, the first with the message 'KEY DOWN EVENT WITH ENTER KEY!' and the second with the message 'KEY UP EVENT WITH ENTER KEY!'.

### Actual Behavior
Only the alert with message 'KEY UP EVENT WITH ENTER KEY!' is shown.

### Reproduction Link
<a href="https://codepen.io/jofreorus/pen/KKwBGeQ" target="_blank">https://codepen.io/jofreorus/pen/KKwBGeQ</a>

**Comment by rhalf** [comment]
i have experienced this too... any workaround for now? or i have to wait for the next release?
