### ISSUE TITLE
[Documentation] Vuetify v1.5 docs is offline

### ISSUE THREAD

**Issue by deleuterio** [vuetifyjs/vuetify#10242]
### Environment

**Browsers:** Chrome 79.0.3945.117
**OS:** Linux x86_64, Windows, Android, Mac OSX, Linux, iOS

### Steps to reproduce
Just open the web page for docs v1.5

### Expected Behavior
Open the docs.

### Actual Behavior
![Imgur](https://i.imgur.com/b9059dF.png)

### Reproduction Link
<a href="https://v15.vuetifyjs.com/" target="_blank">https://v15.vuetifyjs.com/</a>

**Comment by johnleider** [comment]
This has been resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
