### ISSUE TITLE
[Bug Report] mustSort property of options prop of DataTable is not respected, but must-sort prop works

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [vuetifyjs/vuetify#10244]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.0

### Steps to reproduce
1. Create data table
2. Pass down options object with mustSort: true
3. It is not respected

### Expected Behavior
mustSort option in `options` prop should be respected

### Actual Behavior
mustSort option in `options` prop is *not* respected

### Reproduction Link
<a href="https://codesandbox.io/s/admiring-surf-2vot6" target="_blank">https://codesandbox.io/s/admiring-surf-2vot6</a>

**Comment by johnleider** [comment]
A few notes:

- The **options.mustSort** is not propagated correctly
- If you use **must-sort** on `v-data-table`, it propagates, but still doesn't work
- It doesn't appear to be hooked up at all

**Comment by nekosaur** [comment]
@johnleider You're correct that `options.mustSort` was not respected. But the functionality works just fine so not sure what you mean by the last two points.
