### ISSUE TITLE
[Documentation] Vuetify 1.5 Documentation page is down

### ISSUE THREAD

**Issue by ldrotos1** [vuetifyjs/vuetify#10243]
### Environment

**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Simply navigate to the following web page.

https://v15.vuetifyjs.com/

### Expected Behavior
The docs should load

### Actual Behavior
The page loads with the following

503: SERVICE_UNAVAILABLE 
Code: V1_NO_SCALED_DEPLOYMENTS
ID: iad1:hnt24-1579183754163-19a8aa749d4a

### Reproduction Link
<a href="https://v15.vuetifyjs.com/" target="_blank">https://v15.vuetifyjs.com/</a>

**Comment by MajesticPotatoe** [comment]
duplicate #10242
