### ISSUE TITLE
[Bug Report] v-text-field doesn't work propery with value and v-model option.

### ISSUE THREAD

**Issue by gurumzip** [vuetifyjs/vuetify#10247]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
We don't need steps.

### Expected Behavior
I expect to get initialized value from value option in v-text-field.

### Actual Behavior
Makes v-text-field with v-model option and value option at the same time.
That makes not having intialized value.

### Reproduction Link
<a href="https://codepen.io/quroom/pen/oNgPmgP?editable=true&editors=101" target="_blank">https://codepen.io/quroom/pen/oNgPmgP?editable=true&editors=101</a>

### Other comments
It's OK without v-model but the value option doens't work with v-model.
Is there any method to make v-text-field with initialized value?

**Comment by maiorano84** [comment]
Not an issue with Vuetify. This is how Vue works.

If you want to initialize the value with something, just set full_address to "test":

```
new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  data: () => ({
    full_address: "test"
  }),
})
```

**Comment by gurumzip** [comment]
I know that way but the value was not static.
It comes another step like the value can be test or any words.
It is not fixed string. Anyway I can implement it with another way.
But I am just curious why it deosn't work.
As you can see, [https://vuejs.org/v2/guide/forms.html](url)
In input tag, we can use value and v-model at the same time.
But in v-text-field, I can't make it.
What's the reason..? Are they on purpose to work like that?

**Comment by KaelWD** [comment]
> In input tag, we can use value and v-model at the same time.

Not with `type="text"`. In those examples v-model is setting `checked` instead.

**Comment by gurumzip** [comment]
@KaelWD Thanks for answering.
