### ISSUE TITLE
[Documentation] button link broken! 

### ISSUE THREAD

**Issue by sabinamaniak** [vuetifyjs/vuetify#10246]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.15.1

### Steps to reproduce
Use side menu to navigate to "Buttons" 
Page is missing 

### Expected Behavior
Buttons page appears

### Actual Behavior
no page is found 

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons" target="_blank">https://vuetifyjs.com/en/components/buttons</a>

### Other comments
Used google to find correct link here: https://vuetifyjs.com/en/components/buttons#usage

**Comment by MajesticPotatoe** [comment]
both links work, likely cache, clear it and try again.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
