### ISSUE TITLE
[Feature Request] Rules based on the state of other models

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#10248]
### Problem to solve
I'm not certain if this is already a feature and I'm doing it incorrectly or if it simply doesn't exist. The goal is to be able to make rules that are only triggered based on the contents of other inputs.

### Proposed solution
I would like it to be possible in a way similar to this: https://codepen.io/teellcory/pen/gObdqea

**Comment by MajesticPotatoe** [comment]
you can access this via data like so:
<https://codepen.io/majesticpotatoe-the-bashful/pen/wvBENXz>
