### ISSUE TITLE
[Bug Report] VBadge partially hidden when it inside VListItemAvatar

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#10259]
### Environment
**Vuetify Version:** 2.2.4
**Last working version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Linux x86_64

### Steps to reproduce
Open codepen link

### Expected Behavior
VBadge visible completely

### Actual Behavior
VBadge partially hidden

### Reproduction Link
<a href="https://codepen.io/darkside73/pen/ExadNWE" target="_blank">https://codepen.io/darkside73/pen/ExadNWE</a>

**Comment by johnleider** [comment]
Nothing we can do about that. Avatar has to have its overflow hidden.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ryudo2k5** [comment]
@Darkside73 Did you find an alternative solution to this bug?

**Comment by Darkside73** [comment]
@ryudo2k5 Just reset overflow for ```v-list-item-avatar``` like that:
```
overflow: initial
```
