### ISSUE TITLE
[Bug Report] overide any variables in vue.

### ISSUE THREAD

**Issue by felek000** [vuetifyjs/vuetify#10255]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Fresh install nuxt and vuetifyjs.
Change variablesc.scss example
```
@import "~vuetify/src/styles/styles.sass";
@import '~vuetify/src/styles/settings/_variables.scss';
$font-size-root: 24px !default;
$grey: map-deep-merge($grey,
    (
      'base': #9e9e9e,
      'lighten-5': #fafafa,
      'lighten-4': #f5f5f5,
      'lighten-3': #eeeeee,
      'lighten-2': #e0e0e0,
      'lighten-1': #bdbdbd,
      'darken-1': red,
      'darken-2': #616161,
      'darken-3': #424242,
      'darken-4': #212121
    ),
);

```

### Expected Behavior
To changes apply in variables.scss to have impact on app.

### Actual Behavior
none effect

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/9394#issuecomment-575131290
