### ISSUE TITLE
Non Fixed Toolbar and Mini Variant Navigation Drawer don't play well together

### ISSUE THREAD

**Issue by KuroThing** [vuetifyjs/vuetify#1025]
### Versions
Vue version: 2.4.1
Vuetify version: 0.14.0
OS: Windows 8.1
Browser(s): Chrome + Firefox

### What is expected ?
That the space previously occupied by a non-fixed toolbar would be filled by the navigation drawer when in mini-variant mode after scrolling down

### What is actually happening ?
It is left empty

### Reproduction Link
https://codepen.io/anon/pen/awrpzb (If you can't see it in the light theme, try the dark one. It's more visibile with the dark theme, imo)

I'm fairly sure that this will be closed as a won't fix bug report, but it's worth a shot to see if someone is able to fix it.

**Comment by johnleider** [comment]
Oh brother, time for some fun.

**Comment by johnleider** [comment]
I'm not sure this is something we can support. In terms of layouts, to me, it doesn't make sense to have a clipped drawer with a non-fixed toolbar. If I'm off beat here someone let me know, but, not only does it seem near impossible to code for, I don't believe we should support it.
