### ISSUE TITLE
[Bug Report] Spacing XS has no effect

### ISSUE THREAD

**Issue by merowinger92** [vuetifyjs/vuetify#10260]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Accourding to documentation (https://vuetifyjs.com/en/styles/spacing) the margin and padding can be adjusted on different breakpoints in the format `{property}{direction}-{breakpoint}-{size}`

With `{property}{direction}-xs-{size}` it doesn't have to me any effect.

I was also trying to search the css files on a cdn and couldn't find any reference to it. I am wondering if I am doing a mistake applying the class or if this is a general bug/undocumented feature.

### Expected Behavior
Setting the margin and padding correctly when applying xs as breakpoint.

### Actual Behavior
Setting the margin and padding correctly with xs breakpoint doesn't have any effect.

### Reproduction Link
<a href="https://codepen.io/merowinger92/pen/vYEVywE" target="_blank">https://codepen.io/merowinger92/pen/vYEVywE</a>

**Comment by merowinger92** [comment]
Is this really only a documentation problem? 

It looks to me more like the possibility to set explicitely margin and padding for xs breakpoint would miss.

e.g. if I would to set some special margin or padding only on xs I would need to exclude explicitely all other classes e.g. `class="ma-sm-6 ma-md-6 ma-lg-6 ma-12"`

My expectation would be setting `class="ma-xs-12 ma-6"`.

**Comment by MajesticPotatoe** [comment]
Yes. As noted in the commit, xs is inferred as everything is based on <breakpoint>AndUp, thus excluded, so `ma-6` is equivalent to `ma-xs-6`

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
