### ISSUE TITLE
Toggle Button Active Colors is not obvious? 

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#1026]
My customer has recently complain about the color of the toggle button.
It is too similar to tell if it is active or not.
Which looks different after I upgrade it to the latest version,
Used to be
![image](https://user-images.githubusercontent.com/11958538/28297085-cb134bca-6b20-11e7-81b5-d9fbb08b4bf7.png)
Now (I added the border myself)
It looks nice but if go to the Vuetify.js website, you will feel like it is too the color is kind of hard to tell. (Maybe add prop for active color? or directive?)
![image](https://user-images.githubusercontent.com/11958538/28297130-1479b196-6b21-11e7-837d-bc591761feeb.png)

Posting here to see what others think about this

**Comment by johnleider** [comment]
This is a bug, will fix.
