### ISSUE TITLE
[Bug Report] Async treeview does not unselect nodes with children, if they were selected before fetching children

### ISSUE THREAD

**Issue by temyer** [vuetifyjs/vuetify#10279]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
https://codepen.io/alp8hrd/pen/LYEXOWo?editors=1010

### Expected Behavior
1. select root
2. open nodes with children
3. unselect root
4. selected nodes array is empty

### Actual Behavior
Steps to reproduce:
1. select root's checkbox
2. start opening nodes with children(50% probability of getting children, so refresh page if no children appear)
3. after opening some nested nodes, unselect root's checkbox. However, there are nodes selected

### Reproduction Link
<a href="https://codepen.io/alp8hrd/pen/LYEXOWo?editors=1010" target="_blank">https://codepen.io/alp8hrd/pen/LYEXOWo?editors=1010</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
