### ISSUE TITLE
[Feature Request] add mixed item-key for v-treeview

### ISSUE THREAD

**Issue by bushuosx** [vuetifyjs/vuetify#10276]
### Problem to solve
myitems:[
{name:'x',age:20,dep:'1001'},
{name:'x',age:30,dep:'1001'},
{name:'y',age:20,dep:'1001'}
],
how can i set the item-key?

### Proposed solution
i want set the item-key like :item-key="{name}+{dep}"

**Comment by jacekkarczmarczyk** [comment]
If we add this to treeview we should add this also to other components using item-key for consistency.

**Comment by nekosaur** [comment]
I would vote no for this. It can be done with a computed value

**Comment by johnleider** [comment]
We discussed this internally and my take on it is if you want a composite key, do that in your DB query or in a computed property.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by OrkhanAlikhanov** [comment]
@johnleider What was the reason for not supporting functions there?  Maybe performance concerns?

`v-autocomplete` etc supports it:

<img width="491" alt="Screen Shot 2021-02-18 at 22 52 24" src="https://user-images.githubusercontent.com/15037839/108406517-f987de00-723b-11eb-9086-8b5a92e180de.png">


While `v-treeview` doesn't:

<img width="603" alt="Screen Shot 2021-02-18 at 22 52 47" src="https://user-images.githubusercontent.com/15037839/108406552-073d6380-723c-11eb-9c46-8bd1da23fedf.png">


Shouldn't it be better to be consistent? I'm particularly interested in `item-disabled`.

**Comment by johnleider** [comment]
> @johnleider What was the reason for not supporting functions there? Maybe performance concerns?
> 
> `v-autocomplete` etc supports it:
> 
> <img alt="Screen Shot 2021-02-18 at 22 52 24" width="491" src="https://user-images.githubusercontent.com/15037839/108406517-f987de00-723b-11eb-9086-8b5a92e180de.png">
> 
> While `v-treeview` doesn't:
> 
> <img alt="Screen Shot 2021-02-18 at 22 52 47" width="603" src="https://user-images.githubusercontent.com/15037839/108406552-073d6380-723c-11eb-9c46-8bd1da23fedf.png">
> 
> Shouldn't it be better to be consistent? I'm particularly interested in `item-disabled`.

Create an issue for this, https://issues.vuetifyjs.com/
