### ISSUE TITLE
[Bug Report] Failed start up after upgrade to Vuetify 2.2.4

### ISSUE THREAD

**Issue by hckhanh** [vuetifyjs/vuetify#10273]
### Environment
**Vuetify Version:** 2.2.4
**Last working version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
1. Install Vuetify `2.2.3` by using Vuetify plugin through @vue/cli
2. Manually upgrade to version `2.2.4`

### Expected Behavior
It should run smoothly

### Actual Behavior
I saw this error

Failed to compile.
```
./node_modules/vuetify/lib/components/VSparkline/VSparkline.js
Module not found: Error: Can't resolve '../../../src/components/VSparkline/VSparkline.sass' in 'C:\Users\hoang\VueProjects\ghedep\node_modules\vuetify\lib\components\VSparkline'
```

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
I believe there is some problem with VSparkline. Since there was some changes on that component that related to issue #8557
https://github.com/vuetifyjs/vuetify/releases/tag/v2.2.4

**Comment by MajesticPotatoe** [comment]
Duplicate #10231

**Comment by hckhanh** [comment]
thank you.
