### ISSUE TITLE
[Feature Request] v-input with styles

### ISSUE THREAD

**Issue by rogeralsing** [vuetifyjs/vuetify#10274]
### Problem to solve
currently, v-input seems to only be the structural placeholder of data.
There is no built in way to style it like the other standard inputs/selects in Vuetify.

Having this more built in, would greatly help build custom components that follow the same look and feel.

### Proposed solution
Allow attributes such as outlined, solo, filled etc to be placed on the v-input.
Or potentially a new derivate of v-input to avoid incompatability of existing uses.

Currently (AFAIK) one have to inspect other components, pick the classes that might have an effect and try to apply these onto the v-input, which feels hacky and might break over time.

**Comment by johnleider** [comment]
The entire structure is changing for v3 and v-input will probably be removed from the docs depending upon the end result.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
