### ISSUE TITLE
[Bug Report] Stepper Content not shown if el set to 0

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify#10270]
### Environment
**Vuetify Version:** 2.2.4
**Last working version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.15.2

### Steps to reproduce
In Data change el to 1

### Expected Behavior
Even though the el is set to 0, the stepper should work as before.

### Actual Behavior
If the el value is set to 0, the stepper content never shows.

### Reproduction Link
<a href="https://codepen.io/adarshmadrecha/pen/yLyRxOW" target="_blank">https://codepen.io/adarshmadrecha/pen/yLyRxOW</a>

**Comment by adarshmadrecha** [comment]
I suspect that this bug is because of fixing https://github.com/vuetifyjs/vuetify/issues/10096 by committing https://github.com/vuetifyjs/vuetify/commit/996a37fc25580f4395145530ef39989fc27b1206

**Comment by johnleider** [comment]
This is not a bug.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by adarshmadrecha** [comment]
With all due respect,
The documentation [compoennt/stepper](https://vuetifyjs.com/en/components/steppers#steppers) uses `el` as `0` and hence after the update documentation is also broken.

I tried setting `el` as `1`, and it works as expected.

Hence, either this is a bug or documentation needs to be updated to use `el` as `1`
