### ISSUE TITLE
[Bug Report] v-data-table's "progress" slot does not work when slot scope is bound

### ISSUE THREAD

**Issue by stefan-u-sevenval** [vuetifyjs/vuetify#10280]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.1

### Steps to reproduce
1. Use v-data-table
2. set prop `loading` to `true`
3. Bind the slot scope of `progress` slot

### Expected Behavior
Contents of `progress` slot are shown

### Actual Behavior
v-progress-linear is shown

### Reproduction Link
<a href="https://codepen.io/uciaczek/pen/dyPQdra?editable=true&editors=101" target="_blank">https://codepen.io/uciaczek/pen/dyPQdra?editable=true&editors=101</a>

**Comment by nekosaur** [comment]
`progress` is not a scoped slot.
