### ISSUE TITLE
[Bug Report] VFileInput error with v-model not null

### ISSUE THREAD

**Issue by Rovelak** [vuetifyjs/vuetify#10281]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
Create a VFileInput with a v-model linked to a data that is not null. The VFileInput is not displayed and we get errors in the console.
If we initialize that same data to null the VFileInput is displayed without errors.

### Expected Behavior
The VFileInput should be displayed and no errors should be shown. Or a message should be displayed asking us to initialize our v-model to null. Or at least it should be indicated in the documentation that the v-model should be null.

### Actual Behavior
The VFileInput is not displayed and we get errors in the console.

### Reproduction Link
<a href="https://codepen.io/Rovelak/pen/ZEYmojE" target="_blank">https://codepen.io/Rovelak/pen/ZEYmojE</a>

### Other comments
This is not a huge problem as initializing the v-model to null resolves the issue.

**Comment by matthieusieben** [comment]
The example is clearly an invalid use of the component:
- Use `mutliple` with `Array` or `undefined` value
- Use not-`mutliple` with `Object` (`File`) or `undefined` value

Filtering non-`File` in the component removes the ability to provide fake files (e.g. when the page is re-loaded) in some browsers (IE & Edge -- of course).

**Comment by matthieusieben** [comment]
@johnleider  could you consider reverting this commit ?
