### ISSUE TITLE
[Feature Request] Add background-color to v-tabs-items

### ISSUE THREAD

**Issue by hfaua** [vuetifyjs/vuetify#10283]
### Problem to solve
Setting custom background color to v-tabs-items.

### Proposed solution
Add property background-color to v-tabs-items which will set the background color. Similar as in commit #72f46dc

**Comment by mrodal** [comment]
Yes please, the default white its awful when using a different background color for the app

**Comment by jose-aiq** [comment]
The default should be transparent

**Comment by KareemDa** [comment]
Can I add `Colorable` mixin or `VSheet` mixin into `VWindow` component (VTabItems extends VWindow). in order to make this functionality work in vuetify 2?

**Comment by KaelWD** [comment]
v-tabs-items has been removed, and v-window has no background color at all. Put v-window inside something else with a background color (like a sheet) or put something with a background color inside v-window-item.
