### ISSUE TITLE
[Feature Request] Expect v-list-group to support at least 4 levels of depth

### ISSUE THREAD

**Issue by bushuosx** [vuetifyjs/vuetify#10286]
### Problem to solve
I need a v-list-group that supports at least 4 levels of depth in one of my projects, but currently v-list-group does not have this feature.
I had to use a v-treeview instead, but the v-treeview was not as beautiful as it.

### Proposed solution
Expect v-list-group to support level 4 depth, or more

**Comment by johnleider** [comment]
Lists support infinite depth in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
