### ISSUE TITLE
[Bug Report] VBtn is missing ripple effect on keyboard trigger

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#10285]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
1. Tab into a button
2. Press space or enter

### Expected Behavior
The button should have generate a ripple, according to the Material Design 2 spec.

### Actual Behavior
It does not. It only expands the drop-shadow a little bit, which is only part of the desired effect.

### Reproduction Link
<a href="https://codepen.io/phiter/pen/jOEQJJz" target="_blank">https://codepen.io/phiter/pen/jOEQJJz</a>

**Comment by fpdrozd** [comment]
Could it be done by just adding the following events to the Ripple directive? (src/directives/ripple/index.ts)
```javascript
el.addEventListener('keydown', (e) => {
    if (e.keyCode == 13 || e.keyCode == 32) rippleShow(e)
})
el.addEventListener('keyup', rippleHide)
```

**Comment by phiter** [comment]
@fpdrozd hey, I tried doing exactly that yesterday as a fix but that did not work well.

If you press and hold escape, multiple keydown events will be fired and multiple ripples will be created, turning the button white.

A more viable option is to call both rippleShow and rippleHide at the same time, but that still creates lots of ripples.
The part where I got stuck was identifying if there was another ripple already created.

**Comment by fpdrozd** [comment]
@phiter There is a debounce function in util/helpers.ts that may be usefull in reducing the number of created ripples. Another option is to create a flag variable. This seems to work fine but I don't know if it's elegant enought.
```javascript
let keyboardRipple = false
el.addEventListener('keydown', (e) => {
  if (!keyboardRipple && (e.keyCode == 13 || e.keyCode == 32)) {
    keyboardRipple = true
    rippleShow(e)
  }
})
el.addEventListener('keyup', (e) => {
  keyboardRipple = false
  rippleHide(e)
})
```
But there is another problem - try to run the linter. Normally the **show** function expects MouseEvent or TouchEvent and based on that it somehow calculates the ripple. When you pass a KeyboardEvent it's missing some props and throws an error.

**Comment by phiter** [comment]
@fpdrozd yeah when I started my implementation I had to add the `KeyboardEvent` type to the args definition.

**Comment by fpdrozd** [comment]
@phainv Right, but then it's using the ``clientX`` and ``clientY`` properties, which do not exist on the ``KeyboardEvent``. In that case I replaced the cursor position with half the width and height of the button which makes the ripple start at the center.
