### ISSUE TITLE
[Feature Request] Dark theme is too dark?

### ISSUE THREAD

**Issue by nwtgck** [vuetifyjs/vuetify#10293]
### Question
This may be a question rather than a feature request.

I bumped up Vuetify version from 2.1.8 to 2.2.5. Then, I found the dark theme is like the following in 2.2.5. It darkens.
![image](https://user-images.githubusercontent.com/10933561/72853569-242ffc00-3cf5-11ea-9271-303d2dda3bdf.png)

In 2.1.8, the theme is like the following.
![image](https://user-images.githubusercontent.com/10933561/72853602-3e69da00-3cf5-11ea-9388-a527568aaec4.png)

I tried to find the dark theme change in the release note, but I couldn't. Is this correct change?

### Proposed solution
.

**Comment by KaelWD** [comment]
It was updated to match MD2: 103becbc795c1870515ec703ba0b26447ba96e79

https://material.io/design/color/dark-theme.html#ui-application

The example on that page is using `#1f1f1f` for the toolbar, but actually has an even darker `#1d1d1d` for the cards as they're lower elevation. 

MD1 had a very light dark theme in comparison: https://material.io/archive/guidelines/style/color.html#themes-figure-caption-0

**Comment by nwtgck** [comment]
Thank you very much useful information!

**Comment by nwtgck** [comment]
@KaelWD I found the background color of a card is `#1f1f1f`, not `#1d1d1d`. 

<img width="634" alt="image" src="https://user-images.githubusercontent.com/10933561/72858373-ee464400-3d03-11ea-85b5-1ea379bde9dc.png">

And the colors of both the tool bar and the card is the same color `#1f1f1f` as follows.

![vuetify-darktheme-color mp4 opt](https://user-images.githubusercontent.com/10933561/72858751-3023ba00-3d05-11ea-9aeb-cbad683b3d87.gif)

**Comment by KaelWD** [comment]
Already brought it up with john, the current structure makes it a bit tricky to have different colours for them.

**Comment by nwtgck** [comment]
@KaelWD Thanks!

Can I use the very light dark theme of MD1 in Vuetify 2.2.5?

**Comment by KaelWD** [comment]
You can change those variables back to what they were before: https://vuetifyjs.com/en/customization/sass-variables

**Comment by nwtgck** [comment]
@KaelWD Thank you very much for the information. I can use lighter dark theme now.

---
For future visitors, here is the changes for making the dark theme lighter again: <https://github.com/nwtgck/piping-ui-web/pull/199/files>.

**Comment by Stoom** [comment]
@nwtgck did you ever find all the values for this?  If so would you be able to share?

**Comment by nwtgck** [comment]
@Stoom Hi,

"All values" mean values in .scss? If so, Here are values.

```scss

// (base: https://github.com/vuetifyjs/vuetify/releases/tag/v2.2.6)

$material-dark: (
        'app-bar': #424242,
        'background': #303030,
        'cards': #424242,
        'navigation-drawer': #424242,
        'toolbar': #212121
);

$material-light: ('background': #FAFAFA);
```

Here is an actual project using the values.
https://github.com/nwtgck/piping-ui-web/blob/356c794eaba6a8f29313b8f81a6d146d0eb30ada/src/styles/variables.scss
