### ISSUE TITLE
[Bug Report] Overwrite day slot hide all events in VCalendar

### ISSUE THREAD

**Issue by greenbeam-ita** [vuetifyjs/vuetify#10296]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.13.6

### Steps to reproduce
With day slot, events disappear.
Without day slot and other slot like "day-label" or "day-body" events appear correctly with or without slots

### Expected Behavior
Use all v-calendar slots as documented in https://vuetifyjs.com/it-IT/components/calendars

### Actual Behavior
Events disappear

### Reproduction Link
<a href="https://codepen.io/losscasa/pen/LYEMXJo" target="_blank">https://codepen.io/losscasa/pen/LYEMXJo</a>

**Comment by KaelWD** [comment]
Uh yeah that's what the day slot is for, to override the default way days are displayed.

**Comment by greenbeam-ita** [comment]
@KaelWD, thanks for your answer, but I don't understand what you wrote.
This means I can't see events anymore if I override day slot?
If I want change day style using slot, I don't have event related to day information form slot. How can I achieve it?

**Comment by KaelWD** [comment]
If you override the day slot you have to define how events should be displayed.
