### ISSUE TITLE
[Bug Report] ComboBox: Unable to get property 'getData' of undefined or null reference

### ISSUE THREAD

**Issue by daneren2005** [vuetifyjs/vuetify#10291]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer 11
**OS:** Windows 7

### Steps to reproduce
When you try to copy paste into the combobox in IE 11, you get an error: `Unable to get property 'getData' of undefined or null reference`.  The error appears to be from `const pastedItemText = event.clipboardData!.getData('text/vnd.vuetify.autocomplete.item+plain')`.

### Expected Behavior
Paste the text into the box

### Actual Behavior
Pate the text into the box, but throws an error

### Reproduction Link
<a href="https://codepen.io/daneren2005/pen/LYEMxZM?editable=true&editors=101" target="_blank">https://codepen.io/daneren2005/pen/LYEMxZM?editable=true&editors=101</a>

**Comment by daneren2005** [comment]
Codepen and jsfiddle don't seem to support IE anymore so you can't really try that codepen in IE 11.  You can also reproduce by going to https://test.plicbooks.com/guest/uploader/ad415eee-3cb2-48df-99e6-2d15b65eaf81?school=Test%20Book%20Format&embeddedTags=destinationAlbum-ce73c837-c0c3-460b-be80-4ffa81ddb479&destinationName=Misc.  Click Upload your photos, select any photo, then at the bottom in the tag box try pasting something into it.  You will see that the text gets added to the combo box, but it throws that error.  Press F12 to open the dev tools in IE 11.

**Comment by jacekkarczmarczyk** [comment]
I guess we should use `window.clipboardData` for IE
