### ISSUE TITLE
[Bug Report] Table select all default behaviour

### ISSUE THREAD

**Issue by atilkan** [vuetifyjs/vuetify#10292]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.12.6

### Steps to reproduce
Click an item's checkbox.
Click Select all checkbox on the header. 
It selects remaining items. Actually it should unselect selected items first.

### Expected Behavior
This is the correct behaviour, should be the default.
https://codepen.io/atilkan/pen/eYmbExY?editable=true&editors=101

### Actual Behavior
This is the default behaviour and should not be.
https://codepen.io/atilkan/pen/rNaozRa?editable=true&editors=101

### Reproduction Link
<a href="https://codepen.io/atilkan/pen/eYmbExY?editable=true&editors=101" target="_blank">https://codepen.io/atilkan/pen/eYmbExY?editable=true&editors=101</a>

### Other comments
Default behaviour should be **unselect** selected items first.

**Comment by nekosaur** [comment]
Why?

I'm not trying to be contrary here, but I would like to know why you believe the current behaviour is incorrect.

**Comment by phiter** [comment]
I also don't understand why should that be the default behavior.
The official material library for Angular works just like Vuetify 

https://material.angular.io/components/table/overview#selection

Same for React's Material UI 

https://material-ui.com/components/tables/#sorting-amp-selecting

**Comment by atilkan** [comment]
Because gmail works like that.

**Comment by nekosaur** [comment]
gmail is not the arbiter of what is material design or not. they break the specs often enough themselves.

**Comment by atilkan** [comment]
Maybe you can add an option for this. Currently this is only possible with implamenting header interactions explicitly.
