### ISSUE TITLE
[Bug Report] Cannot access vuetifyjs.com via a Canadian ISP reliably

### ISSUE THREAD

**Issue by WGriffithsYPK** [vuetifyjs/vuetify#10290]
### Environment
Any Telus ISP connection

**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
Attempt to browse to vuetifyjs.com from a Telus Internet connection.
This works intermittently, but goes up and down every few minutes. 
We get the error Error 1016 Origin DNS error produced by Cloudflare.
Connections from a non-Telus IP appear to work such as Comcast and BT in the UK. 

### Expected Behavior
Being able to browse to the website

### Actual Behavior
Error 1016 Origin DNS error

### Reproduction Link
<a href="www.vuetifyjs.com/en/professional-support/business" target="_blank">www.vuetifyjs.com/en/professional-support/business</a>

**Comment by johnleider** [comment]
We are in contact via email so I'll be closing this issue.

**Comment by AtriLahiji** [comment]
I encountered the same issue. Both on data (using Telus as a carrier) and at work (where we also use Telus). Any ETA on this?

**Comment by SODACANS** [comment]
I have also been seeing the same thing for the past week, but our ISP is century link.
