### ISSUE TITLE
[Feature Request] Disable hover on DataTable

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10297]
### Problem to solve
don't change row color when hovering over any row

### Proposed solution
add new prop, something like 'disable-hover'

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5787

**Comment by mowolf** [comment]
Just disable the background color change via css:

```
.v-data-table__wrapper > table > tbody > tr:hover {
  background: inherit !important;
}
```

**Comment by acro5piano** [comment]
@mowolf Thanks!
