### ISSUE TITLE
Disable modal close on outside click

### ISSUE THREAD

**Issue by exilod** [vuetifyjs/vuetify#103]
As the title states, is there any function or implementation on disabling the close of modal when I click outside of it?

**Comment by johnleider** [comment]
No but there can be.

**Comment by exilod** [comment]
So no workaround until this gets implemented (if it gets)?

**Comment by johnleider** [comment]
You would have to completely control the Modal programmatically, no bound activators (btns).

**Comment by johnleider** [comment]
This had been updated for the upcoming patch.
