### ISSUE TITLE
[Bug Report] VFileInput should respect :value binding

### ISSUE THREAD

**Issue by matthieusieben** [vuetifyjs/vuetify#10307]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.2

### Steps to reproduce
- `v-file-input` with `@change` listener and `:value` binding instead of `v-model`
- `@change` listener does not update `:value` when called with an empty value (e.g. input cleared)
- Notice that the `v-file-input` element shows no input while the `:value` binding still has one

### Expected Behavior
The input elements should always reflect the value of the `:value` binding, regardless of the internal state.

Fox example, if the `@change` listener does not update the `:value` binding, the file component should not display an empty file selector (since there *is* an input value)

### Actual Behavior
`v-file-input` does not always reflect the value of the `:value` binding.

### Reproduction Link
<a href="https://codepen.io/matthieusieben/pen/JjoxpRb" target="_blank">https://codepen.io/matthieusieben/pen/JjoxpRb</a>

**Comment by jacekkarczmarczyk** [comment]
We're using internal state in other input elements, and that's also what you could observe with native inputs:

https://codepen.io/jkarczm/pen/PowVQRy

For me it's `working as intended`

**Comment by matthieusieben** [comment]
Right... this feels odd to me but it does seem to work logically wrt to VueJS.

Side question then, how would you recommend doing what I am trying to do ?

**Comment by jacekkarczmarczyk** [comment]
If what you want to achieve is "The input elements should always reflect the value of the :value binding, regardless of the internal state." then you can't do it now and there are no plans to change it. 

I'm not sure what your actual goal is, but feel free try to discuss it on [Discord](https://community.vuetifyjs.com),
