### ISSUE TITLE
disabled fab button is invisible

### ISSUE THREAD

**Issue by milleraa** [vuetifyjs/vuetify#1030]
### Steps to reproduce
put fab button in disabled state on the page

### Versions
Chrome 50, Edge 14

### What is expected ?
Disabled grayed floating button

### What is actually happening ?
button is invisible. 

### Reproduction Link
https://codepen.io/milleraa/pen/eRaGVL

**Comment by johnleider** [comment]
You have the button designated as dark, which means that when disabled it should have a 12% #FFF color as designated here https://material.io/guidelines/components/buttons.html#buttons-raised-buttons

**Comment by milleraa** [comment]
Disabled fab button with "white--text" looks bad. 
I use this solve it:
`<v-btn fab :class="[{ 'white--text': !disableBtn }, 'indigo']"`
