### ISSUE TITLE
[Documentation] A gallery of all components

### ISSUE THREAD

**Issue by andreixk** [vuetifyjs/vuetify#10301]
### Problem to solve
Sometimes it's difficult to decide which component to use. In some cases it's better to use a button, or alert, or banner. It takes a while to find the right component.

### Proposed solution
Bootstrap had a handy [page like that](https://getbootstrap.com/docs/3.4/components/) until version 4. It would be nice to see something similar for Vuetify. I understand the page would be heavy if every version of every component is used, but perhaps only a single item of each kind would be good. Or even screenshots with the components.

**Comment by MajesticPotatoe** [comment]
This is a good idea, in some aspects. We do have some plans for something like this as a replacement/re-purpose of the api-explorer page for v3. Not sure it will end up like the page you listed here (given just how many components we have), but will hopefully help ease the search for the right component. 
Related DR: #9602 / #8094

**Comment by andreixk** [comment]
the api-explorer is a good start, but it only has a few components (e.g. no avatars, alerts, headers/subheaders)
