### ISSUE TITLE
[Bug Report] App bar extension color no longer aligned with app bar color

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#10308]
### Environment
**Vuetify Version:** 2.2.6
**Last working version:** 2.2.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

### Steps to reproduce
Create an app bar with tabs inside an extension slot.

### Expected Behavior
Tabs in extension slot should have the same color as the app bar.

### Actual Behavior
Tabs in extension slot have a different color.

### Reproduction Link
<a href="https://codepen.io/p4sca1/pen/wvBNymN" target="_blank">https://codepen.io/p4sca1/pen/wvBNymN</a>

**Comment by MajesticPotatoe** [comment]
This is a side effect of the material color changes in for dark components in 2.2.6
if using SASS vars, a work around is in the release notes.
<https://github.com/vuetifyjs/vuetify/releases/tag/v2.2.6>

**Comment by P4sca1** [comment]
I was aware of the color changes, but thought that it was intended to apply the same color for the tabs in the extension slot (like in v2.2.5 which brought some of the color changes).

So to sum it up:
The new behaviour is intended and from now on we need to manually assign the background-color to the tabs in the extension slot to match the toolbar color. Is that correct?

Btw. is there a variable which can be used in the `:background-color` prop which represents the background color of a toolbar (based on whether dark or light mode is enabled).

**Comment by MajesticPotatoe** [comment]
It's not something specific to extension slot, more that card color differs from toolbar color, and tabs uses cards background color by default.

I'll leave it to @johnleider to chime in if it's intended going forward (could just be an oversight).

As for vars, theres the `$tabs-bar-background-color` sass var which could be set to toolbar and that would change it globally

**Comment by P4sca1** [comment]
Alright thanks for the info!
Would be great if there’s any chance that old behavior could be recreated without manual work.
Always felt very natural that tabs have the same color as the toolbar (at least when used as extension).

**Comment by KaelWD** [comment]
`<v-tabs color="transparent"`

**Comment by P4sca1** [comment]
@KaelWD Good idea, but it needs to be `background-color=„transparent“`.

**Comment by johnleider** [comment]
This actually extends to both styles defined <https://github.com/vuetifyjs/vuetify/blob/07a285f9f72fdf97c7eb751baf532f3c8614c30b/packages/vuetify/src/components/VToolbar/VToolbar.sass#L58>. Neither are actually doing anything.
