### ISSUE TITLE
[Feature Request] Indeterminate checkbox / three phase switch

### ISSUE THREAD

**Issue by eltebe** [vuetifyjs/vuetify#10305]
### Problem to solve
Cleaner visual exp. for the indeterminate checkbox/switch 
(like this but with the correct swtich style): 

![three phase switch](https://docs.telerik.com/devtools/wpf/controls/radbuttons/features/images/radbuttons-features-toggle-switch-button-0.png)

### Proposed solution
Same as a simple switch, but with three switching phases.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
