### ISSUE TITLE
[Feature Request] v-datatable click:row event should include the event as second parameter

### ISSUE THREAD

**Issue by thelinuxlich** [vuetifyjs/vuetify#10302]
### Problem to solve
So we can do DOM manipulation with the event.target

### Proposed solution
Probably a small changing cascading the event target in packages/vuetify/src/components/VDataTable/VDataTable.ts

**Comment by jacekkarczmarczyk** [comment]
Related: https://github.com/vuetifyjs/vuetify/issues/9720
