### ISSUE TITLE
Styling of allowed/disallowed dates broken in v-date-picker

### ISSUE THREAD

**Issue by cb109** [vuetifyjs/vuetify#1031]
### Steps to reproduce
- Create a datepicker.
- Limit its dates via the `allowed-dates` prop.
- Open the datepicker and checkout some disallowed dates: They are not stylistically marked as being not allowed.

### Versions
0.14.x

### What is expected ?
The `v-datepicker` should clearly visualize which dates are allowed and which are not. Disallowed dates used to be grayed out for that.

### What is actually happening ?
There is no visual distinction anymore between allowed and disallowed dates within the datepicker. All dates look the same, making it guess work which you can pick and which not.

### Reproduction Link
Just compare the 0.13 datepicker example (no. 4) VS 0.14:
https://vuetifyjs.com/releases/0.13/#/components/pickers
https://vuetifyjs.com/components/pickers

Or see this codepen: https://codepen.io/anon/pen/rwgYMX

**Comment by nekosaur** [comment]
This was an unfortunate regression, but has been fixed in dev with b8417324fb2722f0b17dae8aa87e584bfdc64687
