### ISSUE TITLE
[Documentation] V-Rating clearable not working

### ISSUE THREAD

**Issue by Tallyrald** [vuetifyjs/vuetify#10316]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Open the pen.

### Expected Behavior
Some kind of clearable functionality as per docs.

### Actual Behavior
Rating cannot be cleared.

### Reproduction Link
<a href="https://codepen.io/Tallyrald/pen/BayboNe" target="_blank">https://codepen.io/Tallyrald/pen/BayboNe</a>

### Other comments
I haven't used the rating component before so I'm not sure how long this has been an issue.

**Comment by jacekkarczmarczyk** [comment]
Rating is cleared by clicking at the star with current value (for example click 2nd start to set ratings to "2", click again to clear)

**Comment by Tallyrald** [comment]
I guess this is a docs issue then. I honestly didn't think of clicking on it twice. Sorry about that.
