### ISSUE TITLE
[Feature Request] v-slide-group having a way to always show arrows, even when they aren't needed

### ISSUE THREAD

**Issue by jaunt** [vuetifyjs/vuetify#10311]
### Problem to solve
Picture multiple rows of slide-groups, for a netflix like interface.  Depending on how many items end up in each row, some rows will be offset by the left arrow coming and going.  

On mobile, I set show arrows to false since the user can touch-drag.  

### Proposed solution
Either show-arrows could change to always force arrows, or perhaps there could be second parameter force-arrows, for a case where you'd want show-arrows to mean "allow-arrows", which is how it behaves at the moment.

**Comment by johnleider** [comment]
This is technically a bug and covered in #6945

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
`show-arrows="desktop"` was added in v2.3.0 by #11480
