### ISSUE TITLE
[Bug Report] VueExtendLayout and BottomNavigation

### ISSUE THREAD

**Issue by astrahov** [vuetifyjs/vuetify#10319]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
1. Install https://www.npmjs.com/package/vue-router
2. Install https://www.npmjs.com/package/vue-extend-layout
2. Create layout with BottomNavigation and VueRouter
3. Create two screens (views)
4. Start Screen - empty, Second screen - with VBtn

### Expected Behavior
When switching to the Second screen, the height of the buttons in Bottom Navigation should not change

### Actual Behavior
Root Route - Start Screen
The next screen is Second

When switching to the Second screen, the height of the buttons in Bottom Navigation changes ...

### Reproduction Link
<a href="https://codepen.io/alexstrakhov/pen/RwNdrmp" target="_blank">https://codepen.io/alexstrakhov/pen/RwNdrmp</a>

**Comment by astrahov** [comment]
In CodeOpen, the bug does not play. You need to create the application locally and run production build

**Comment by astrahov** [comment]
In the build version, a separate css file is created for each Vue file.

Example:
`app...css`
`chunk-vendors...css`
`layout-screens-app-first-vue...css`
`layout-screens-app-second-vue...css`

There are no buttons (VBtn) on the First screen.
On the Second screen there is a button (VBtn) and CSS for VBtn is in the file: `layout-screens-app-second-vue...css`

VBottomNavigation uses CSS from core files (`app...css` or `chunk-vendors...css`). But when we go to the Second screen, then for VBtn inside VBottomNavigation, CSS is used not from the core CSS file, but from: `layout-screens-app-second-vue...css`

**Comment by jacekkarczmarczyk** [comment]
Please provide a github repo or codesandbox, best without external libs

**Comment by astrahov** [comment]
I found out what the problem was! In VueRouter, screens were imported dynamically. Redid for static import and the problem is gone.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
