### ISSUE TITLE
[Feature Request] v-edit-table : slots for actions buttons

### ISSUE THREAD

**Issue by deka** [vuetifyjs/vuetify#10318]
### Problem to solve
the v-edit-dialog buttons style is not compliant with my application style

### Proposed solution
Slots to change cancel and save buttons

**Comment by MajesticPotatoe** [comment]
per <https://github.com/vuetifyjs/vuetify/issues/9502#issuecomment-575237812>

> This component is going away for v3 and won't be revisited in v2.x.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
