### ISSUE TITLE
Dialog emits input event immediately when triggered

### ISSUE THREAD

**Issue by smtlk** [vuetifyjs/vuetify#1032]
Hi everyone, i just switched to the latest version of Vuetify and am using Vue 2.4.1, i was having some problems with a custom component that is essentially a wrapper for your `V-Dialog` component where v-dialog was **emitting the input event** with `false` as the payload immediately after being triggered using a button.

Finding this odd i decided to copy paste the example from the docs to see if this was somehow related to my code and because it was working with _~0.13_ it appears to be a bug introduced in the new **Vuetify** release _(v0.14.2)_.

I've created a [codepen](https://codepen.io/anon/pen/EXzoww) to highlight the issue, let me know if there's anything else i can do to help, i've tried looking at your code but i couldn't quite figure it out on my own so i can't do a **PR** at the moment. 

It appears to work when i use the activator slot, but in my case i want to programatically trigger dialogs by simply changing the boolean to true, like for instance when warning users before proceeding with a deletion request on a table.

**Comment by nekosaur** [comment]
Add `.stop` modifier to `@click`. https://codepen.io/anon/pen/PjvRbO

It is described in the docs on the dialogs page.

**Comment by smtlk** [comment]
@nekosaur many thanks :) 👍

**Comment by manavm1990** [comment]
I ended up linking `@input` to a handler that I already had. Using `.stop` on other custom events prevented events from being passed to children...which I suppose is the purpose of `.stop`.
Anyway, AIS, just using `@input` to trigger the desired method worked.

**Comment by ealfonsov89** [comment]
> I ended up linking `@input` to a handler that I already had. Using `.stop` on other custom events prevented events from being passed to children...which I suppose is the purpose of `.stop`.
> Anyway, AIS, just using `@input` to trigger the desired method worked.

could you post an example, because i have the same problem than @ghost, when i update my vuetifyjs version. I tried with `@click.stop` but nothin.

**Comment by manavm1990** [comment]
> > I ended up linking `@input` to a handler that I already had. Using `.stop` on other custom events prevented events from being passed to children...which I suppose is the purpose of `.stop`.
> > Anyway, AIS, just using `@input` to trigger the desired method worked.
> 
> could you post an example, because i have the same problem than @ghost, when i update my vuetifyjs version. I tried with `@click.stop` but nothin.

```
<!-- Developer's Note: Need this silly @input event handler due to this event firing when outside of v-dialog. I guess this has to do with Vuetify ClickOutside directive. -->
    <v-dialog
      v-model="dialogDataProp"
      max-width="500px"
      @input="hideDialog">
```
```
hideDialog: function() {
      this.$emit("hide-cart");
    },
```
So, `<v-dialog>` wraps a 'cart' that is then hidden. [Video.](https://screencast-o-matic.com/watch/cFXofwrhwY)
