### ISSUE TITLE
[Bug Report] v-card does not animate with transitions

### ISSUE THREAD

**Issue by Cleric-K** [vuetifyjs/vuetify#10331]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.94
**OS:** Windows 10

### Steps to reproduce
Use `<v-card>` inside `<v-...transition>`

### Expected Behavior
Should animate

### Actual Behavior
It does not

### Reproduction Link
<a href="https://codepen.io/cleric-k/pen/zYxbLbR" target="_blank">https://codepen.io/cleric-k/pen/zYxbLbR</a>

### Other comments
In the linked codepen you can see that if `v-card` is wrapped inside a div it works, so it seems to be related to the direct parentship: `transition > v-card`

**Comment by s9th** [comment]
I wanted to add that I also encountered this bug and from what I could tell, the transition property of the expand and reverse animations was overridden by the v-card's transition

**Comment by jason-linthwaite** [comment]
I also found this bug... Any update on it?

**Comment by KaelWD** [comment]
This appears to be fixed in 2.4

**Comment by RoduanKD** [comment]
it's back in Vuetify 3 I've just tested it. transition > RouterView > in the page the root node is VCard
