### ISSUE TITLE
[Bug Report] v-checkbox is not correctly aligned in dense mode

### ISSUE THREAD

**Issue by SherMi321** [vuetifyjs/vuetify#10336]
### Environment
**Vuetify Version:** 2.2.6
**Last working version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
Hover over the checkbox with dense property enabled

### Expected Behavior
checkbox aligned in center of the hover circle

### Actual Behavior
checkbox miss aligned

### Reproduction Link
<a href="https://codepen.io/ShiruMi/pen/abzMPOa" target="_blank">https://codepen.io/ShiruMi/pen/abzMPOa</a>

**Comment by krnekhelesh** [comment]
This bug is also reproducible for radio buttons present in a radio group with the dense property enabled.

**Comment by JD-sixberries** [comment]
@steveg152  Thanks man...!!!
