### ISSUE TITLE
[Documentation] Error in SASS variables docs

### ISSUE THREAD

**Issue by roblugt** [vuetifyjs/vuetify#10342]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
view the documentation 
https://vuetifyjs.com/en/customization/sass-variables#usage-in-components

### Expected Behavior
The document describes two methods for using Vuetify variables within components.  However the examples for both methods are the same.

### Actual Behavior
The second example should import a local variable file.

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables" target="_blank">https://vuetifyjs.com/en/customization/sass-variables</a>

**Comment by johnleider** [comment]
Resolved by d99bff7ce
