### ISSUE TITLE
[Bug Report] Truncate text with v-edit-dialog not work

### ISSUE THREAD

**Issue by ptitou** [vuetifyjs/vuetify#10348]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
See codepen, first line with v-edit-dialog doesn't work, the second line is OK

### Expected Behavior
Work on both lines

### Actual Behavior
text not truncated

### Reproduction Link
<a href="https://codepen.io/ptitou/pen/oNgOwNe" target="_blank">https://codepen.io/ptitou/pen/oNgOwNe</a>

**Comment by johnleider** [comment]
You can't truncate an inline element: https://codepen.io/johnjleider/pen/GRgLMmE

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
