### ISSUE TITLE
[Feature Request] Add countdown timer  auto closed feature to v-alert

### ISSUE THREAD

**Issue by bushuosx** [vuetifyjs/vuetify#10344]
### Problem to solve
I hope v has the countdown function to automatically close

### Proposed solution
countdown timer  auto closed feature to v-alert

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by titusdecali** [comment]
This is the third time I've seen a feature that I wanted, only to see it replied with 
"this is not functionality that we are looking to implement at this time"

I won't be using Vuetify for my next project, that's for sure.
