### ISSUE TITLE
[Bug Report] TextField don't update the "value" property

### ISSUE THREAD

**Issue by dbarjs** [vuetifyjs/vuetify#10354]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Linux x86_64

### Steps to reproduce
Add the "value" property to a v-text-field component, then, set the v-text-field value. When I try to get the current value using vue $refs, it returns the initial value.

### Expected Behavior
Return the current value

### Actual Behavior
Return the initial value

### Reproduction Link
<a href="https://codepen.io/dbarjs/pen/bGNJKzx?editors=1011" target="_blank">https://codepen.io/dbarjs/pen/bGNJKzx?editors=1011</a>

### Other comments
I'm using the "value" property instead "v-model" because I don't want the initial value to change until the user clicks the save button

**Comment by KaelWD** [comment]
Props are one-way, they can't be updated from within the component. Use two data properties instead.

**Comment by dbarjs** [comment]
@KaelWD I understand, but when using the "value" prop, it becomes impossible to obtain the value of text-field after. Remembering that the "value" property is mentioned in the documentation.
