### ISSUE TITLE
Feature request: hover attribute on more components

### ISSUE THREAD

**Issue by TheNoim** [vuetifyjs/vuetify#1035]
- What will it allow you to do that you can't do today?
>Give the user a better feeling where he is and it makes the hole ui more dynamic.
- How will it make current work-arounds straightforward?
>You won't need to implement you own hover method in every project again.
- What potential bugs and edge cases does it help to avoid?
>You own library is buggy ?! :) idk

**Comment by johnleider** [comment]
Could you give me an example? I'm not really understanding what you are asking for.

**Comment by TheNoim** [comment]
Just the hover attribute for more components:
https://codepen.io/noim/full/ModLzB

**Comment by johnleider** [comment]
Everything that is outlined to have this functionality from MD Spec will, others will not. It becomes unnecessary bloat after awhile and things like this can be done by the developer.
