### ISSUE TITLE
[Bug Report] <v-toolbar> with <v-img> and <v-tabs right> breaks the <v-tabs>

### ISSUE THREAD

**Issue by htfranek** [vuetifyjs/vuetify#10352]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
just load the page with that code, this happens because the v-img is loaded after that v-bar

### Expected Behavior
the v-tabs underline should be under index and not moved as it is in the codepen example

### Actual Behavior
the v-tabs underline is moving because of the v-img width

### Reproduction Link
<a href="https://codepen.io/ERR_NAME_NOT_RESOLVED/pen/NWPmXad" target="_blank">https://codepen.io/ERR_NAME_NOT_RESOLVED/pen/NWPmXad</a>

### Other comments
A solution in this particular case would be if the v-img width would be fixed even before the img loads

**Comment by johnleider** [comment]
This is a side-effect of a fix we made to have images properly scale in flex containers. It is recommended that you have a max-width on the image.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
