### ISSUE TITLE
[Feature Request] Calendar - Hide days of last and next month in the month-view

### ISSUE THREAD

**Issue by pliersch** [vuetifyjs/vuetify#10357]
### Problem to solve
It seems it is not possible to show only the days of the selected month. All 35 slots will be filled. A custom year view looks not nice. A look like the datepicker would be great.

### Proposed solution
Please provide a property to configure this behavior.

**Comment by ClickerMonkey** [comment]
You could do a calendar with type `custom-weekly`  where you specify the `start` and `end` props as the first and last day of the year.

If that will not suffice, please open the issue back up with more information, maybe some visual examples.

**Comment by mdpnixon** [comment]
Can I +1 this feature request? I'm currently building an annual calendar by mapping 12 month view calendars. I'm running into an issue where events that are on dates that overlap (display in two separate calendars) create a duplicate issue when you click that event as you get 2 of the event detail pop ups.

**Comment by bencurthoys** [comment]
+1 for this feature. It just seems like a basic feature of date pickers and has been possible on all the ones I've used in the past. Duplicating a week at the month boundary and not being able to turn it off is just weird. 
![image](https://user-images.githubusercontent.com/4848856/189945712-f72cd408-19f4-4d02-85ca-08c85e868d83.png)
