### ISSUE TITLE
[Bug Report] Vuetify 2.2.6 breaks Vue 2.6.10 v-on click on v-dialog's activator slot

### ISSUE THREAD

**Issue by rowlo** [vuetifyjs/vuetify#10350]
### Environment
**Vuetify Version:** 2.2.6
**Last working version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Opera 65.0.3467.78, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Quite simple to reproduce. Open the code pen in the reproduction link. It's configured to use Vuetify 2.0.11. Click the search icon and see that the v-dialog opens.

Now change in the pen's JS settings the CDN version of Vuetify to 2.2.6 and try to open the dialog again. It doesn't work.

### Expected Behavior
The dialog opens with Vuetify 2.2.6 just as it did with 2.0.11.

### Actual Behavior
Nothing happens. The browser's console prints that error:
TypeError: Cannot read property 'stopPropagation' of undefined
    at openOnHover.e.click (vuetify.min.js:6)
    at He (vue.min.js:6)
    at a.n (vue.min.js:6)
    at He (vue.min.js:6)
    at a.e.$emit (vue.min.js:6)
    at click (eval at Ya (vue.min.js:6), <anonymous>:1:121)
    at He (vue.min.js:6)
    at HTMLDivElement.n (vue.min.js:6)
    at HTMLDivElement.Yr.o._wrapper (vue.min.js:6)

### Reproduction Link
<a href="https://codepen.io/robert-wloch-lenze/pen/YzPMxGb" target="_blank">https://codepen.io/robert-wloch-lenze/pen/YzPMxGb</a>

### Other comments
I've found two issues related to "stopPropagation":
- A documentation request: https://github.com/vuetifyjs/vuetify/issues/6866
- A feature request: https://github.com/vuetifyjs/vuetify/issues/4654

Neither one deals with the bug I encountered.

**Comment by jacekkarczmarczyk** [comment]
You're missing v-app

**Comment by jacekkarczmarczyk** [comment]
Po

**Comment by rowlo** [comment]
Hi Jacek,

Sorry for the late response and sorry that I forgot the v-app in the codepen. I just added it to the linked codepen and the issue is still exactly as described.

I understand that I should not comment on closed issues. But I request that this issue should be reopened. Or should I open a new one with exactly the same description letter by letter?

BR
Robert

**Comment by KaelWD** [comment]
Still your fault. 
`@click="$emit('click')"` -> `@click="$emit('click', $event)"`

**Comment by rowlo** [comment]
Kael, thanks for that pointer! That wasn't obvious to me from the documentation I'd read. Where is it documented that the $event parameter is absolutely required? As written in the ticket description the code used to work with Vuetify 2.0.11.
