### ISSUE TITLE
[Bug Report] overflow-y-auto not scrollable when using v-overlay

### ISSUE THREAD

**Issue by MaeseppTarvo** [vuetifyjs/vuetify#10351]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

### Expected Behavior
I expect it to to scroll if touching inside v-overlay on mobile and dragging

### Actual Behavior
Cannot scroll if touching inside v-overlay on mobile and dragging

### Reproduction Link
<a href="https://codesandbox.io/s/keen-microservice-ghxdi" target="_blank">https://codesandbox.io/s/keen-microservice-ghxdi</a>

**Comment by johnleider** [comment]
Fixed in 3365cac74fea50b5b0b4c5e8dc6ce3023ff96c68
