### ISSUE TITLE
[Bug Report] The mask doesn't work in textFields

### ISSUE THREAD

**Issue by polyak-y** [vuetifyjs/vuetify#10355]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
you can see the error in codepen https://vuetifyjs.com/en/components/text-fields#masks-using-vue-the-mask

### Expected Behavior
you can see the error in codepen https://vuetifyjs.com/en/components/text-fields#masks-using-vue-the-mask

### Actual Behavior
you can see the error in codepen https://vuetifyjs.com/en/components/text-fields#masks-using-vue-the-mask

### Reproduction Link
<a href="https://codepen.io/polyak-y/pen/RwNOYBN?editors=1010" target="_blank">https://codepen.io/polyak-y/pen/RwNOYBN?editors=1010</a>

**Comment by polyak-y** [comment]
no

**Comment by MajesticPotatoe** [comment]
duplicate #9482
