### ISSUE TITLE
[Bug Report] radio group label overflow

### ISSUE THREAD

**Issue by supraniti** [vuetifyjs/vuetify#10360]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
create a radio group where the radio label is long enough to overflow to a second or third line

### Expected Behavior
increase component height

### Actual Behavior
element height is fixed and text is overflowing

### Reproduction Link
<a href="https://codepen.io/supraniti/pen/ExaJMjy" target="_blank">https://codepen.io/supraniti/pen/ExaJMjy</a>

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/jkarczm/pen/xxbeBpr
