### ISSUE TITLE
[Bug Report] V-layout column not working with comopnents

### ISSUE THREAD

**Issue by datainvestor** [vuetifyjs/vuetify#10368]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Vivaldi 2.5.1525.46
**OS:** Windows 10

### Steps to reproduce
Create v-flex comopnent and insert it in the v-layout.

### Expected Behavior
There is a bug with the grid when creating comopnent and inserting the component in the v-layout column wrap, compared to no comopnent usage. You can see it here in the following codepens: https://codepen.io/pokepim/pen/GRgLrrY - this is working correctly (as expected)

### Actual Behavior
When moving the code to the comopnent it is broken: (it does not fill whole column height)

### Reproduction Link
<a href="https://codepen.io/pokepim/pen/PowvoKx" target="_blank">https://codepen.io/pokepim/pen/PowvoKx </a>

**Comment by johnleider** [comment]
`v-flex`/`v-layout` are deprecated (legacy) and as such we will not be performing any updates to it.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Also not a bug, you're inserting an extra element in between them.
