### ISSUE TITLE
[Bug Report] V-Select selection with keyboard not possible anymore 

### ISSUE THREAD

**Issue by Oli22** [vuetifyjs/vuetify#10369]
### Environment
**Vuetify Version:** 2.2.7
**Last working version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
[Not working codepen in 2.2.7](https://codepen.io/oli22/pen/zYxQrzW)
Since the update to 2.2.7 the selection on a v-select is not more possible by keyboard inputs

### Expected Behavior
Select input via keyboard
[Working codepen with 2.2.6](https://codepen.io/oli22/pen/NWPVxvr)

### Actual Behavior
Selection not possible

### Reproduction Link
<a href="https://codepen.io/oli22/pen/zYxQrzW" target="_blank">https://codepen.io/oli22/pen/zYxQrzW</a>

**Comment by johnleider** [comment]
Can you provide exact reproduction steps?

**Comment by KaelWD** [comment]
- click select
- press down arrow

**Comment by KaelWD** [comment]
Fixed by e78316267391e103a03d3c83f5290b6024858b79
