### ISSUE TITLE
[Feature Request] v-expansion-panel-content style

### ISSUE THREAD

**Issue by The28AWG** [vuetifyjs/vuetify#10361]
### Problem to solve
The component creates its own wrapper for the content. Therefore, it is not possible to define styles or classes for content.

### Proposed solution
A good solution is to let the wrapper inherit the component styles.

**Comment by KaelWD** [comment]
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by The28AWG** [comment]
Good advice. But I'm not sure this is a good practice. Especially if I define existing styles. For example, padding.

**Comment by KaelWD** [comment]
Well inherit isn't either, you'd end up with double.

**Comment by The28AWG** [comment]
For me, English is not native, I definitely can not express myself.
Let's say we have a code like this:
```html
<v-expansion-panel-content class="pa-0">
<span>test</span>
</v-expansion-panel-content>
```
This code in the browser will look like this:
```html
<div class="v-expansion-panel-content pa-0">
<div class="v-expansion-panel-content__wrap">
<span>test</span>
</div>
</div>
```
And you need this:
```html
<div class="v-expansion-panel-content">
<div class="v-expansion-panel-content__wrap pa-0">
<span>test</span>
</div>
</div>
```

**Comment by tbacon1991** [comment]
Hi, Did you resolve this?? 
I am using slots to pass information into the tabs and all of the styling is being completely overwritten by the v-expansion-panel__wrap div. 
Even my paragraph and text are not being styles by Vuetify classes.

**Comment by The28AWG** [comment]
Deep selectors is great!
https://github.com/vuetifyjs/vuetify/issues/10361#issuecomment-579274390

**Comment by alejandroguille** [comment]
Hi, Did you resolve this??

**Comment by The28AWG** [comment]
@alejandroguille deep selector
```css
.v-expansion-panel-content >>> .v-expansion-panel-content__wrap { /*you style*/ }
```

**Comment by cdefy** [comment]
I know the subject is closed but the last solution offered didn't work for me. (I'm using Sass in my project).

But targeting `.v-expansion-panel-content__wrap` directly worked so I share just in case it can help someone else. And as I only needed to change for one panel, I added a class to the tag.

```
<v-expansion-panel-content class="myClass">
```

```
.myClass {
 .v-expansion-panel-content__wrap {
   /* My style */
 }
}
```
