### ISSUE TITLE
[Bug Report] Dense icon button is not dense

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#10374]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Linux

### Steps to reproduce
- Add `v-btn` with `dense` and `icon` attributes
- Add `v-icon` inside `v-btn` with or without `dense` attribute

### Expected Behavior
Icon gets same size as standalone dense icon. 

### Actual Behavior
Icon has size of non dense icon

### Reproduction Link
<a href="https://codepen.io/peteruithoven/pen/MWYdvgj" target="_blank">https://codepen.io/peteruithoven/pen/MWYdvgj</a>

**Comment by johnleider** [comment]
`v-btn` has a specific icon size that it targets and if you want to modify it, you will have to update the button's default icon size.

Also `v-btn` doesn't have a **dense** prop.

```scss
$fab-icon-sizes: ( 'default': 20 );
```

Reference: https://vuetifyjs.com/en/customization/sass-variables

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
