### ISSUE TITLE
[Feature Request] Better v-container max-width

### ISSUE THREAD

**Issue by BenjaminVadant** [vuetifyjs/vuetify#10377]
### Problem to solve
When using v-container, on 4k screens, the current max-width is set to 1785px which is pretty small in comparaison to the width of the screen (3840px) in this resolution.
This is due to the way the max-width is computed based on the break-point.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_variables.scss#L59

### Proposed solution
Unless there is a reason (for example, a Google Material guideline), I propose the following:

As the max-width is computed to 93.75% of the breakpoint, a solution could be just setting the max-width to this value for all breakpoints.

So a first version of the code would be :

```scss
$container-max-widths: map-deep-merge(
  (
    'md': '93.75%',
    'lg': '93.75%',
    'xl': '93.75%'
  ),
  $container-max-widths
);
```

If the idea is accepted, I'll make a PR.

**Comment by johnleider** [comment]
I think that we should update the default container max-widths but I don't think it should be your proposed values.

**Comment by BenjaminVadant** [comment]
I agree, the proposal was a bit naïve. Do you think you'll continue with the break-point computed approach with a new break-point (xxl)? Or something else ?

**Comment by KaelWD** [comment]
> Unless there is a reason (for example, a Google Material guideline)

https://material.io/design/layout/responsive-layout-grid.html#grid-behavior

**Comment by KaelWD** [comment]
The grid now has an xxl breakpoint: #13318
