### ISSUE TITLE
[Documentation] prefer @change over @click on selection controls

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#10373]
### Environment
**Vuetify Version:** 2.2.6 and 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Linux

### Steps to reproduce
- Add Checkbox element
- Listen to click event

### Expected Behavior
Click is triggered once after click

### Actual Behavior
Click is triggered twice after click

### Reproduction Link
Vuetify 2.2.6: <a href="https://codepen.io/peteruithoven/pen/OJPYmbm" target="_blank">https://codepen.io/peteruithoven/pen/OJPYmbm</a>
Vuetify 2.2.8: <a href="https://codepen.io/peteruithoven/pen/XWJwRqL" target="_blank">https://codepen.io/peteruithoven/pen/XWJwRqL</a>

### Other comments
One workaround seems to be to stop the click event's propagation by adding `.stop`.

**Comment by peteruithoven** [comment]
I can also reproduce this with Vuetify 2.2.8:
https://codepen.io/peteruithoven/pen/XWJwRqL

**Comment by KaelWD** [comment]
You should be using `input-value` and `@change` here anyway.

**Comment by peteruithoven** [comment]
@KaelWD but `change` isn't listed in the API:
https://vuetifyjs.com/en/components/selection-controls#api

I tried adding it in the same codepen, but it doesn't seem to be triggered:
https://codepen.io/peteruithoven/pen/XWJwRqL

(I can't easily use v-model for my use case)

**Comment by KaelWD** [comment]
The bound click event is overwriting the internal one so it breaks change, if you remove `@click` it works correctly.

**Comment by peteruithoven** [comment]
@KaelWD you are right. Using only `@change` works perfectly. I've updated my example.

**Comment by douglasg14b** [comment]
Yeah, docs DEFINITELY need to note in bold that `@click` will trigger twice. This can cause some pretty unpleasant effects...

**Comment by KaelWD** [comment]
#5968 has been fixed, docs need to note that you almost always want to be using `@change` instead of `@click`
