### ISSUE TITLE
[Bug Report] v-carousel transition overflows container height

### ISSUE THREAD

**Issue by SystemKeeper** [vuetifyjs/vuetify#10376]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Open the reproduction link and let the carousel cycle a few times. You'll see that the image start to overflow to container and push the content below further down. This only happens during transition, after the transition finished, everything is in place.

### Expected Behavior
v-carousel/ v-carousel-item shouldn't overflow it's container during a transition.
![image](https://user-images.githubusercontent.com/1580193/73371930-b8cac900-42b6-11ea-9f94-fc6d47c52911.png)

### Actual Behavior
See above.
![image](https://user-images.githubusercontent.com/1580193/73371941-bec0aa00-42b6-11ea-988d-35e7c3a0489e.png)

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-20-template-l5jlh" target="_blank">https://codesandbox.io/s/vuetify-20-template-l5jlh</a>

**Comment by johnleider** [comment]
Carousel requires specific styles to support variable height declaration and this does not extend to every transition style. Either use a specified height, don't use a custom transition, or hook into `.slide-y-reverse-transition` **leave** and **leave-to** hooks and add your custom styles to make it work.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by SystemKeeper** [comment]
Thanks for the hint - although I thought that the integerated transitions would work out-of-the box here, as does the default transition.

In case anyone else is looking for a solution, the following works for me:

```
<style>
.slide-y-reverse-transition-leave,
.slide-y-reverse-transition-leave-to {
  position: absolute;
  top: 0;
  transform: translate(0, -100%);
}
</style>
```

**Comment by SystemKeeper** [comment]
After further looking at this issue, I noticed that the default transition uses the `v-window-*-transition` and not (as I thought) the `carousel-*-transition`. I then changed the default transition by the following style sheet:

```
.v-window-x-reverse-transition-leave-to {
  transform: translateX(-100%) !important;
}

.v-window-x-reverse-transition-enter {
  transform: translateX(100%) !important;
}
```

This way I can change the default transition as I want to, without messing with absolute positioning.
