### ISSUE TITLE
[Feature Request] Dynamic grid layout

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#10387]
### Problem to solve
does not have a dynamic grid layout

### Proposed solution
https://getuikit.com/v2/docs/grid-js.html

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
