### ISSUE TITLE
[Feature Request] Add max-select option to v-data-table.

### ISSUE THREAD

**Issue by felixis-1** [vuetifyjs/vuetify#10383]
### Problem to solve
This will allow the ability to specify the maximum number of records that will be selected in a data table when select all rows checkbox is selected. Up to the value defined in this new max-select option will be selected and the ones after that will be disabled.

### Proposed solution
A max-select numeric prop should be made available to v-data-table that works in conjunction with show-select.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

It can be done easily enough in user land https://codepen.io/nekosaur/pen/RwPNLry?editors=1010.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
