### ISSUE TITLE
[Feature Request] Add rel property to VButton

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#10389]
### Problem to solve

> When you link to a page on another site using the target="_blank" attribute, you can expose your site to performance and security issues:
> 
> - The other page may run on the same process as your page. If the other page is running a lot of JavaScript, your page's performance may suffer.
> - The other page can access your window object with the window.opener property. This may allow the other page to redirect your page to a malicious URL.

https://web.dev/external-anchors-use-rel-noopener/ utm_source=lighthouse&utm_medium=devtools

### Proposed solution
Making it possible to add rel="noopener" or rel="noreferrer" to your target="_blank" VButtons avoids these issues.

**Comment by KaelWD** [comment]
This is already possible, v-btn passes through attributes.

**Comment by valentingavran** [comment]
Just realized it on my own and wanted to close this issue. But thank you.

**Comment by juli3nk** [comment]
I don't see `rel` in the list of properties, only `href` and `target`.

**Comment by jacekkarczmarczyk** [comment]
>  I don't see rel in the list of properties, only href and target

because it's not a prop, but it's passed to the actual `<button>` element

**Comment by juli3nk** [comment]
ok, do you have an example please

**Comment by jacekkarczmarczyk** [comment]
`<v-btn rel="foo">button</v-btn>`

**Comment by juli3nk** [comment]
thank you. Can I do the same with `v-list-item`?
