### ISSUE TITLE
[Bug Report] Applicationable component broken after recent commit

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#10380]
### Environment
**Vuetify Version:** 2.2.5
**Last working version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
This change https://github.com/vuetifyjs/vuetify/commit/59a6bbf8cf02a8e1565db6b268741c7c655c0176

broke a component I've written based on Applicationable.  The component is no longer positioning itself correctly in relationship to other "app" components.  It appears that "this.$vuetify.application.top" is not recalculating properly.  In version 2.2.4 of Vuetify I see that value increasing in "updateApplication" as components are added.  In version 2.2.5 I see it reset itself and my component ends up underneath the system app bar.

### Expected Behavior
Component should lineup underneath other "app" components

### Actual Behavior
Component thinks it's top is 0 and appears underneath the system app bar.

### Reproduction Link
<a href="https://github.com/daviesdoclc/vue-applicationable" target="_blank">https://github.com/daviesdoclc/vue-applicationable</a>

### Other comments
If I toggle these lines in services/application/index.js I can reproduce

    this.application[location][uid] = size;              v2.2.4
    //this.application[location] = { [uid]: size }      v2.2.5

**Comment by daviesdoclc** [comment]
I've added a project to demonstrate this

https://github.com/daviesdoclc/vue-applicationable

Using 2.2.4 you'll see the component appears below the appbar as it should.  

<img width="662" alt="Screen Shot 2020-02-01 at 12 44 19 PM" src="https://user-images.githubusercontent.com/36512442/73596521-9c19d580-44f0-11ea-9d99-de713c237052.png">

With 2.2.5 you'll see it gets overlapped.

<img width="625" alt="Screen Shot 2020-02-01 at 12 43 43 PM" src="https://user-images.githubusercontent.com/36512442/73596524-a1772000-44f0-11ea-91fa-08efd8e09a03.png">

Thanks!

**Comment by johnleider** [comment]
Unfortunately as these are not publicly documented, we cannot guarantee non-breaking changes. In this instance, keep-alive has issues with processing the changes made to the application service. Since this is being completely revamped in v3, the best suggestion I can make would be to manually update the service object and call **update**.

```
mounted () {
  this.$vuetify.application.application.top.whatever = 100
  this.$vuetify.application.update('top')
}
```

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by daviesdoclc** [comment]
Got it working per your suggestions.  Thanks!
