### ISSUE TITLE
[Bug Report] v-card prop tile not respected when v-card is inside v-menu

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#10397]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
put a v-card inside a v-menu

### Expected Behavior
a card with no border-radius

### Actual Behavior
When giving the v-card a tile prop, it still shows with an border radius when the card is inside a v-menu

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/yLydpPV" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/yLydpPV</a>

**Comment by jacekkarczmarczyk** [comment]
It's `v-menu__content` that gets border-radius

Workaround: https://codepen.io/jkarczm/pen/WNbqdJr

**Comment by johnleider** [comment]
resolved in #11447

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
