### ISSUE TITLE
[Documentation] v-data-footer - no API documentation

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10396]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
1. Go to this page: https://vuetifyjs.com/en/components/data-tables#data-tables
2. Select `v-data-footer` in API explorer.
3. As you can see props, slots and events have no description.

![image](https://user-images.githubusercontent.com/17653648/73487194-c8c1d600-43a6-11ea-99c7-6e8154ab343d.png)

### Expected Behavior
Props, slots and events of `v-data-footer` component should be documented.

### Actual Behavior
Props, slots and events of `v-data-footer` component are not documented.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#data-tables" target="_blank">https://vuetifyjs.com/en/components/data-tables#data-tables</a>

**Comment by permanar** [comment]
Any update on this?

**Comment by mkalam-alami** [comment]
Until the documentation is done, [you can find the sources here](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataIterator/VDataFooter.ts), the props are quite straightforward.

**Comment by ricardovanlaarhoven** [comment]
i'm guessing this is already resolved?
https://vuetifyjs.com/en/api/v-data-footer/
