### ISSUE TITLE
[Feature Request] Data table - specify available page sizes

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10395]
### Problem to solve
In `v-data-table` right now there is no way to customize this dropdown:

![image](https://user-images.githubusercontent.com/17653648/73482274-b42d1000-439d-11ea-9faa-7f571e0f0e7b.png)

I.e. I want to let my user select only 10, 20 or 50 rows per page. Currently in order to do that I need to hide default footer and create a custom one.

### Proposed solution
Add prop `pageSizes`. This prop takes as an input array of available page sizes, i.e.

```
<v-data-table
    :pageSizes="[10, 20, 50, -1]"
>
</v-data-table>
```

"-1" means all records

**Comment by jacekkarczmarczyk** [comment]
`:footer-props="{itemsPerPageOptions:[10, 20, 50, -1]}"`

**Comment by Mikilll94** [comment]
@jacekkarczmarczyk 
Thanks, this is well hidden in the docs.
