### ISSUE TITLE
[Bug Report] "@click:append" on VAutocomplete removes aria-hidden=true

### ISSUE THREAD

**Issue by mseele** [vuetifyjs/vuetify#10391]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Click into "DropDown Focus Bug" Input field and click "Tab" to move focus to next control

### Expected Behavior
Focus jumps to next input field

### Actual Behavior
DropDown Icon of Input Field gets the focus (because of @click:append="console.log('click')")

### Reproduction Link
<a href="https://codepen.io/mseele/pen/NWPZWEV" target="_blank">https://codepen.io/mseele/pen/NWPZWEV</a>

### Other comments
Please see the second Input Field with out @click:append="console.log('click')" where the issue is gone

**Comment by KaelWD** [comment]
86133eabf01f3748056b6eae0a54d073e606f013

Related: #10379
