### ISSUE TITLE
[Bug Report] Cannot store filename of v-input-file in a local variable

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#10405]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
There is currently no way (that I can tell) to get access to the name of the selected file in a v-file-input.  If I set a v-model property, it gets populated with empty objects

### Expected Behavior
I would like some way to easily get the file name

### Actual Behavior
I'd probably have to do some weird hack where I would have hidden input fields inside the 
&lt;template v-slot:selection="{ index, text }">
being watched and get them by document.get calls

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by UglyHobbitFeet** [comment]
There is no reproduction. The codepen on the v-file-input docs page shows this issue

**Comment by MajesticPotatoe** [comment]
v-model is the proper way to access the files

> I set a v-model property, it gets populated with empty objects

This is to be expected. The actual objects do in fact contain object data, they are of type File, and are created via a constructor.
<https://developer.mozilla.org/en-US/docs/Web/API/File>

To demonstrate that it is in fact there, and behaves the same as regular input="file":
<https://codepen.io/majesticpotatoe-the-bashful/pen/JjogeXP>

**Comment by UglyHobbitFeet** [comment]
This unfortunately does not work if you take the 'multiple' tag out of the
v-file-input.  In my case, I am selecting a single file only. The file name
will not show in your example with the multiple tag removed.

**Comment by nekosaur** [comment]
that's because `files` is no longer an array when you remove multiple, but a single instance of File

**Comment by UglyHobbitFeet** [comment]
Got it, works now, thanks!  It might be beneficial to add this to the docs
on the v-input-file page.
