### ISSUE TITLE
[Bug Report] v-radio-group label is aligned center by default with no obvious way to change

### ISSUE THREAD

**Issue by JamieCurnow** [vuetifyjs/vuetify#10403]
### Environment
**Vuetify Version:** 2.2.8
**Last working version:** 2.2.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.1

### Steps to reproduce
Make a `v-radio-group` element anywhere and give it a `label` prop.

### Expected Behavior
The label should be aligned to the left by default, above the radio options

### Actual Behavior
The label is aligned center making it look very strange.

### Reproduction Link
<a href="https://codepen.io/JamieCurnow/pen/bGNPQxQ?editable=true&editors=101" target="_blank">https://codepen.io/JamieCurnow/pen/bGNPQxQ?editable=true&editors=101</a>

### Other comments
Here is the commit that changed it:
https://github.com/vuetifyjs/vuetify/commit/f81b639dd8fca6a088dc2bbf578a2cbf0e9545f5

Here is the issue that the commit is linked to:
https://github.com/vuetifyjs/vuetify/issues/10334

Looks like this could be fixed by setting:
`align-self: initial`
instead of:
`align-self: center`
on the
```
.v-input--radio-group
  legend
```

**Comment by jacekkarczmarczyk** [comment]
`display: inline-block` is imho unnecessary too

## display: inline-block
![image](https://user-images.githubusercontent.com/15625235/73589790-9ed6f380-450d-11ea-8162-d95a41773694.png)

## ~~display: inline-block~~
![image](https://user-images.githubusercontent.com/15625235/73589792-a5656b00-450d-11ea-8ccf-b93edf8fa91b.png)

**Comment by johnleider** [comment]
@jacekkarczmarczyk It's need for proper alignment with other input elements:

![image](https://user-images.githubusercontent.com/9064066/73597405-3ed25400-44f1-11ea-830e-cae6247e5026.png)

Also this PR will break the fix made in #10334 
![image](https://user-images.githubusercontent.com/9064066/73597424-76410080-44f1-11ea-8dfa-3f8e627175b7.png)

I have a fix coming up now. Thank you for the PR.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
