### ISSUE TITLE
[Bug Report] v-select keyboard lookup on long lists

### ISSUE THREAD

**Issue by tamirvs** [vuetifyjs/vuetify#10406]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
1. Open the select input.
2. Press "V" on keyboard. The list doesn't jump to any value because they are hidden (too far on the list).
3. Click outside the dropdown to close.
4. The value on the input is now "Vermont".

### Expected Behavior
After pressing a key, jump to that value.

### Actual Behavior
If the key is of a hidden item that is not rendered on a long list, it doesn't jump to that value but still selects it, resulting in bad UX.

### Reproduction Link
<a href="https://codepen.io/tamirvs/pen/mdyZoax" target="_blank">https://codepen.io/tamirvs/pen/mdyZoax</a>

**Comment by johnleider** [comment]
This is something I believe we will have an answer for in v3 (hopefully). Right now the current implementation is lackluster.

**Comment by adarshmadrecha** [comment]
@tamirvs, if you are open to changing the component, then use `v-autocomplete`, this would solve your functional issue.

**Comment by KaelWD** [comment]
This should be an easy fix for 2.2
