### ISSUE TITLE
FAQ Still mentions requiring `.native` for events

### ISSUE THREAD

**Issue by Morgul** [vuetifyjs/vuetify#1040]
### Versions
v0.14.X

### What is expected ?
The FAQ should not mention `.native` being required.

### What is actually happening ?
The FAQ still mentions `.native` being required.

![image](https://user-images.githubusercontent.com/770655/28335036-a8823ff6-6bc2-11e7-86c7-b4ea45c9bc86.png)

### Reproduction Link
https://vuetifyjs.com/vuetify/frequently-asked-questions

**Comment by Morgul** [comment]
Mostly, just an FYI. I noticed this as I was browsing around the docs today.

**Comment by johnleider** [comment]
Ty, can you please post this issue on the documentation repo?
