### ISSUE TITLE
[Bug Report] v-calendar does not update when event slot is used and events prop is initialized empty

### ISSUE THREAD

**Issue by jmatth** [vuetifyjs/vuetify#10414]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0, Google Chrome
**OS:** Mac OS 10.15, Linux

### Steps to reproduce
- Create a `v-calendar` component and use the `event` slot to customize the body of rendered events
- Render the calendar with the `events` prop bound to an empty array
- Update that array to add events

### Expected Behavior
The calendar view updates as events are added to the array.

### Actual Behavior
No update is observed on the calendar.

### Reproduction Link
<a href="https://codepen.io/jmatth/pen/RwNXNqd" target="_blank">https://codepen.io/jmatth/pen/RwNXNqd</a>

### Other comments
The reproduction link has the calendar rendered with an empty events array. To verify that initializing with a non-empty array works as expected, I included a commented out section in `data` with it set to an array containing a single event instead.

I'm currently working around this bug in my app by making the events array computed, then in that method adding an event outside the range visible to the user if the array would otherwise be empty.

**Comment by ClickerMonkey** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/pull/11131
