### ISSUE TITLE
[Documentation] Some components does not look well on Safari

### ISSUE THREAD

**Issue by bnabriss** [vuetifyjs/vuetify#10424]
### Environment

**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
In the provided link, check how avatar looks in Safari

### Expected Behavior
It should be in the middle of the component

### Actual Behavior
It in the bottom of the component and part of the avatar circle is hidden

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/avatars#usage" target="_blank">https://vuetifyjs.com/en/components/avatars#usage</a>

**Comment by KaelWD** [comment]
@johnleider https://github.com/vuetifyjs/vuetify/commit/f1104a1bc00442354955a1a4b93eff7f6c589a7e#diff-35e1de0a6aea5c995a7e4ab1124eb3c3R41
