### ISSUE TITLE
[Bug Report] Flex-Grow-1 not working in multi-row column

### ISSUE THREAD

**Issue by datainvestor** [vuetifyjs/vuetify#10423]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Vivaldi 2.5.1525.46
**OS:** Windows 10

### Steps to reproduce
Adding  `class="flex-grow-1"` to the `v-col` does not make it fill all available space (grow to the right)

### Expected Behavior
It should extend all the way to the right (to the next component)

### Actual Behavior
It changes nothing

### Reproduction Link
<a href="https://codepen.io/pokepim/pen/qBEerbj" target="_blank">https://codepen.io/pokepim/pen/qBEerbj</a>

**Comment by KaelWD** [comment]
`.col` already has `flex-grow: 1;`, `.col-4` uses max-width to only take up 4 columns. Remove `cols="4"` to let it fill available space.
