### ISSUE TITLE
[Feature Request] Data table component grouping selection

### ISSUE THREAD

**Issue by GaborTorma** [vuetifyjs/vuetify#10426]
### Problem to solve
Need to set what field available for grouping.

### Proposed solution
Create a directive for setting up which field is groupable.

**Comment by quantumwebco** [comment]
https://github.com/vuetifyjs/vuetify/pull/9937

Apparently they're not gonna do it until v3. Seems odd that it's not really a feature request it's more of a missing bit of functionality that should have been built in from the start and should be very simple to implement.

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8281
