### ISSUE TITLE
[Bug Report] [Rapport de bogue] [Bogue] Composant Web avec Vuetify rendu CSS

### ISSUE THREAD

**Issue by ScottBreyer96** [vuetifyjs/vuetify#10436]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

Hello,
I am currently working on the creation of a web component. I use the command "view build --target wc --name my-custom-element ./src/main.js" to create my web components from Vue components. When I use Vuetify to create a tree or an array of data in a Vue component, there are no problems, but when converting to a Web component, I have problems with the font, display and animation in the tree.

Here is my code and screenshots, thank you.

----------------- Treeview in Vue component -----------------

![Capture d’écran 2020-02-03 à 12 53 03](https://user-images.githubusercontent.com/39304258/73656080-a920fb00-468f-11ea-92e2-63f7cfb3b72e.png)
![Capture d’écran 2020-02-03 à 12 53 10](https://user-images.githubusercontent.com/39304258/73656084-aaeabe80-468f-11ea-906a-92ca0aa3c3cf.png)

----------------- Treeview in Web component -----------------

![Capture d’écran 2020-02-03 à 12 52 53](https://user-images.githubusercontent.com/39304258/73656103-b4742680-468f-11ea-9ec5-a8aeceb0afd1.png)

----------------- DataTable in Vue component -----------------

![Capture d’écran 2020-02-03 à 12 53 33](https://user-images.githubusercontent.com/39304258/73656125-c1911580-468f-11ea-962d-acc3e121506b.png)

----------------- DataTable in Web component -----------------

![Capture d’écran 2020-02-03 à 12 53 23](https://user-images.githubusercontent.com/39304258/73656122-bf2ebb80-468f-11ea-89b5-fc128f3e54e7.png)

----------------- Code -----------------

<img width="742" alt="Capture d’écran 2020-02-03 à 12 51 54" src="https://user-images.githubusercontent.com/39304258/73656135-c9e95080-468f-11ea-99da-3ebf03526d3a.png">

### Steps to reproduce
Create project vue
Create Component "vue-component.vue" with the code in the js file in code pen

Replace main.js by : 

import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify';
import wrap from '@vue/web-component-wrapper';
import "vuetify/dist/vuetify.min.css";
import VueComponent from './components/vue-component'

const CustomElement = wrap(Vue, VueComponent);

Vue.use(vuetify);

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
window.customElements.define('vue-component', CustomElement);

Replace App.vue by : 

<template>
  <v-app>
    <v-content>
      <HelloWorld/>
            <VueComponent/>
    </v-content>
  </v-app>
</template>
<script>
import HelloWorld from './components/HelloWorld';
import VueComponent from './components/vue-component';
 
export default {
  name: 'App',
  components: {
    HelloWorld,
    VueComponent
  },
  data: () => ({
    //
  }),
};
</script>

Execute command :  vue build --target wc --name my-custom-element ./src/main.js

### Expected Behavior
.

### Actual Behavior
.

UPDATE
### Reproduction Link
Git project : https://github.com/ScottBreyer96/Vuetify

### Other comments
.

**Comment by jacekkarczmarczyk** [comment]
The codepen is not a valid reproduction. Please use codesandbox or github repo or whatever runnable that actually **reproduces** the issue
