### ISSUE TITLE
[Feature Request] VSelect - add empty-option

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10445]
### Problem to solve
Right now there is no way to add an empty option to VSelect. This empty option should work in the way that if a user selects the empty option in VSelect, the value of it should be cleared.

### Proposed solution
Add "empty-option" prop to VSelect.

![image](https://user-images.githubusercontent.com/17653648/73688751-fc656e80-46cc-11ea-8b8a-66d6fff98157.png)

**Comment by nekosaur** [comment]
There is already the `clearable` prop. And this can be done in user land https://codepen.io/nekosaur/pen/RwPGGdO?editors=1010

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by miryamfv** [comment]
you can achieve this by pushing an empty array to the top of the dropdown's intems: `this.agents.unshift([]);`

**Comment by sgpinkus** [comment]
The icon clearable adds is really ugly. Much nice having a None option in the list.
