### ISSUE TITLE
[Bug Report] VCalendar retains 7 columns in "week" view regardless of number of "weekdays"

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#10440]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a calendar, set the type to `week` and set `weekdays` to something other than the default `[0,1,2,3,4,5,6]` such as `[1,2,3,4,5]`

### Expected Behavior
Calendar will only show the number of columns for the `length` of `weekdays`

### Actual Behavior
Calendar still displays 7 columns and wraps the week

### Reproduction Link
<a href="https://codepen.io/fontzter/pen/abzeLaX?editors=1010" target="_blank">https://codepen.io/fontzter/pen/abzeLaX?editors=1010</a>

### Other comments
When set to type `month` the calendar has the proper number of columns.
I'm pretty sure this was working a few version back.

![Screen Shot 2020-02-02 at 5 43 28 PM](https://user-images.githubusercontent.com/82155/73661980-0b1a3a00-4669-11ea-8c89-78ae37442920.png)

![Screen Shot 2020-02-02 at 5 45 35 PM](https://user-images.githubusercontent.com/82155/73662021-1b321980-4669-11ea-89d7-bfe7b0f412fb.png)

**Comment by ClickerMonkey** [comment]
I am unable to reproduce this. Open this issue back up if you find that this issue is occurring still.

**Comment by pumpknhd** [comment]
I can confirm that this is still happening.

Go to Week View -> select Mon-Fri. You will see it still shows 7 days with M & T on the right side repeated.

https://codepen.io/pumpknhd/pen/VwzXrzv

**Comment by boobo94** [comment]
> I am unable to reproduce this. Open this issue back up if you find that this issue is occurring still.

Is happening for me too!.

Codepen from documentation - https://codepen.io/pen?&editors=101.

## How to reproduce

type: week
weekdays: Mon - Fri

It shows the columns: Mon,Tue,Wed,Thu,Fri[,Mon,Tue], last 2 shouldn't be there.
