### ISSUE TITLE
[Bug Report] IE11 - VTextField remains red although is valid

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10443]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
This bug exists only on IE11.

1. Click the input
2. Click outside
3. As you can see the input is red and error "Name is required" pops up.
4. Click the input and start typing something.
5. Click outside.
6. The input remains red although is valid.

![text_field_red_ie11](https://user-images.githubusercontent.com/17653648/73685761-01bfba80-46c7-11ea-9126-b623a07fafcb.gif)

### Expected Behavior
The input should not be red.

### Actual Behavior
The input is red.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/YzPmbZM" target="_blank">https://codepen.io/mikilll94/pen/YzPmbZM</a>

### Other comments
CodePen does not support IE11, so to reproduce this issue you need to run this simple code in your local environment.

**Comment by MajesticPotatoe** [comment]
duplicate #10314
