### ISSUE TITLE
[Bug Report] Data-table does not update the checkbox state after deleting some rows.

### ISSUE THREAD

**Issue by terrygreen0606** [vuetifyjs/vuetify#10442]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.5.17
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
1. Select the rows and delete them by clicking delete button.

2. The 'items' prop in the data-table changes, but the checkbox state doesn't update. It still has the original value I deleted before in step 1.

### Expected Behavior
The checkbox state has to be updated according to the data-table :items prop

### Actual Behavior
But it remains still.

### Reproduction Link
<a href="https://codepen.io/terrygreen1992/pen/LYEwMRj" target="_blank">https://codepen.io/terrygreen1992/pen/LYEwMRj</a>

### Other comments
I am currently struggling with this checkbox state of the data-table and couldn't manage to find out the exact answer.

**Comment by KaelWD** [comment]
Events are one-way, you still need to tell the table which rows you have selected with the `value` prop or `v-model`.

**Comment by terrygreen0606** [comment]
show-table prop and input event tells the table which rows are selected, I think. 
Can you tell me if this is wrong?

And I simplified the code as short as possible.

**Comment by KaelWD** [comment]
Input event tells **you** which rows are selected.

**Comment by terrygreen0606** [comment]
That's right.
The thing is that. After I delete some rows and then select other rows, the selected value contains the deleted rows values.
