### ISSUE TITLE
[Feature Request] Cron/scheduler input field and picker

### ISSUE THREAD

**Issue by brunlid** [vuetifyjs/vuetify#10449]
### Problem to solve
A vuetified cron/scheduler input field would be a great addition to an already fantastic component library (thank you!). In previous projects I have used jqCron, which perhaps could be a starting point.

### Proposed solution
Use an existing cron/scheduler picker such as jqCron and adapt it to vuetify.

**Comment by jacekkarczmarczyk** [comment]
That's a way to specific component to be included in the core. It should be done in the userland
