### ISSUE TITLE
Datatable Custom Sorting and Nested Data

### ISSUE THREAD

**Issue by Towerful** [vuetifyjs/vuetify#1045]
I realise there is not a dependency on lodash, but perhaps smarter minds than I can recreate the functionality.

by passing in the following `customFilter`, data can be searched/filtered according to the headers of the datatable.

```js
customFilter(items, search, filter) {
    search = search.toString().toLowerCase();

    //turn the headers collection into an array of the properties of 'value'
    let props = _.map(this.headers, 'value');

    //filter the items if any of the item.'props' passes the supplied filter function
    //_.get could be 'getObjectValueByPath' from '~util/helpers'
    return items.filter(item => props.some(prop => filter(_.get(item, prop), search)))
}
```

This functionality makes more sense to me, as it restricts the sorting of the datatable by only the visible fields, instead of every property.  
It also follows the nested functionality of the `header's` `value`

for example,
```js
data() {
    return {
        headers: [
            {
                text: 'Name',
                value: 'name',
            },
            {
                text: 'Body',
                value: 'body'
            },
            {
                text: 'Some Meta'
                value: 'some.meta.value'
        ],
        items: [
            {
                name: 'Test Post',
                body: 'Some text',
                author: 'Test User',
                some: {
                     meta: {
                          value: 'foo'
                     }
                 }
             },
        ],    
    }
}
```
In (current) default behaviour, a search for `User` will still display the item, whilst a search for `foo` will not, despite this contradicting what is rendered in the table.  
In my revised version, a search for 'User' will not display anything, whilst a search for `foo` will.

Thought I would share my method for this, incase anyone struggles.  
And if the `_.map` can be replicated, then perhaps it could make it into the codebase as default behaviour.

**Comment by nekosaur** [comment]
Could you create a PR request for your implementation? Arrays have `.map` in ES6, so just use `this.headers.map(...)`
