### ISSUE TITLE
[Bug Report] V-slide-group arrows fail when adding slide items when v-slide-group has v-show==false

### ISSUE THREAD

**Issue by jaunt** [vuetifyjs/vuetify#10455]
### Environment
**Vuetify Version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Mac OS 10.13.6

### Steps to reproduce
Using the codepen link:
1. Click add and see that items successfully add to the slide group.
2. Click hide, which toggles v-show to false on the slide group.  (Note, this happens in my app because a route with a slide group is set as "keep alive", so when I come back to the route, it causes this issue).
3. Add to the slide group with the add button while the slide group is still hidden.
4. Click hide to toggle v-show so that the slide group becomes visible again, and see that its arrows are erroneously gone.

### Expected Behavior
When slide group comes becomes visible again, the arrows visibility should be figured out automatically.

### Actual Behavior
When the slide group becomes visible, arrows are gone.

### Reproduction Link
<a href="https://codepen.io/jauntcode/pen/KKpPROd" target="_blank">https://codepen.io/jauntcode/pen/KKpPROd</a>

**Comment by jaunt** [comment]
I wonder if the solution is to call setWidths() when the vue activated lifecycle event fires?  https://vuejs.org/v2/api/#activated

**Comment by Leespiker** [comment]
@jaunt Your [reproduction link](https://codepen.io/jauntcode/pen/KKpPROd) is working as expected for me. Please create another one if it's still not working for you.

**Comment by jacekkarczmarczyk** [comment]
I can reproduce it in current chrome

**Comment by ajayidavid99** [comment]
There is a number of hacks but I don't like any of the cause they are all hard-coding CSS.
.v-slide-group__prev {
display: flex !important;
}
Even after updating vuetify to 2.3.4, issue still persist

Please I need another solution. Had same problem on all browsers even IE11

**Comment by aribornstein** [comment]
I'm having this issue as well.

**Comment by TonyDeplanque** [comment]
I'm having this issue as well with v-slide-group and v-tabs in 2.3.7 version.

**Comment by dumptyd** [comment]
I'm using this workaround for now

```vue
<template>
  <v-slide-group v-show="isVisible" ref="slideGroup">
    <v-slide-item>...</v-slide-item>
  </v-slide-group>
</template>
<script>
export default {
  watch: {
    isVisible(val) {
      if (val) this.$refs.slideGroup.setWidths();
    }
  }
};
</script>
```

**Comment by digisomni** [comment]
This is a problem with Vuetify 2.3.9. No workarounds are currently working for me.

**Comment by MaxWeisen** [comment]
> Using dumptyd's suggestion works for me after the slide-items have been loaded. Directly calling `this.$refs.slideGroup.setWidths();` didn't work for me and even calling it inside in `this.$nextTick` didn't work. However, it did work when using a timeout that waits long enough. (I'm using vuetify version 2.5.8)

This is the only way the slide group operates properly for me too. Is there a better way other than using a timeout?
