### ISSUE TITLE
[Bug Report] VDataTable multiple expanded rows not working

### ISSUE THREAD

**Issue by radupasparuga** [vuetifyjs/vuetify#10450]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
1. Copy paste the code from the docs https://vuetifyjs.com/en/components/data-tables#data-tables 
2. Try to run it

### Expected Behavior
When `single-expand` is false all the rows should expand

### Actual Behavior
Only the selected row expands

### Reproduction Link
<a href="https://codepen.io/ekk0/pen/rNVByQW?editors=1010" target="_blank">https://codepen.io/ekk0/pen/rNVByQW?editors=1010</a>

**Comment by MajesticPotatoe** [comment]
`single-expand` being false does not mean it provides an expand all functionality. `false` is its default value, in which the datatable does not restrict the expansions to a single expansion.
