### ISSUE TITLE
[Bug Report] autofocus won't able to work for v-btn

### ISSUE THREAD

**Issue by dotku** [vuetifyjs/vuetify#10456]
### Environment
**Vuetify Version:** 2.2.8
**Last working version:** 0.15.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

### Steps to reproduce
related to the report from stackoverflow
https://stackoverflow.com/questions/53597532/programmatically-set-focus-on-button-in-vuetify

### Expected Behavior
I would prefer autofocus attribute on v-btn would work inside dialog

### Actual Behavior
user have to click the button

### Reproduction Link
<a href="https://codepen.io/escapedcat/pen/qBEwBMY" target="_blank">https://codepen.io/escapedcat/pen/qBEwBMY</a>

**Comment by tpv-ebben** [comment]
Chrome recently changed the way autofocus works, you should see a message in your console stating that Autofocus processing was blocked.

**Comment by johnleider** [comment]
This is not a bug report, it's a feature request. This should remain a userland implementation.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
