### ISSUE TITLE
[Documentation] Make Buttons Default square

### ISSUE THREAD

**Issue by ottz0** [vuetifyjs/vuetify#10459]
### Problem to solve
I can't find anywhere in the documentation on how to make all elements and buttons square with a border radius of 0 as default

### Proposed solution
Provide documentation on styling and overriding element border radius

**Comment by johnleider** [comment]
https://vuetifyjs.com/customization/sass-variables#sass-variables

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
