### ISSUE TITLE
[Documentation] Missing slots API documentation for v-date-picker

### ISSUE THREAD

**Issue by NJM8** [vuetifyjs/vuetify#10452]
### Environment

**Browsers:** Chrome 72.0.3626.121
**OS:** Linux x86_64

### Steps to reproduce
Visit https://vuetifyjs.com/en/components/date-pickers#api.

### Expected Behavior
The API options should display that slots are available to the date-picker.

### Actual Behavior
No slots are shown to be available. 

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/date-pickers#api" target="_blank">https://vuetifyjs.com/en/components/date-pickers#api</a>

### Other comments
I was looking to add some cancel/ok buttons to a date picker and missed the dialog and menu example near the bottom of the date picker page. Showing the available slots in the API spec would help indicate that some customization is available.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/ec82ef6cef8da0d20909d5d7e8bf1d6015f9b1f1

**Comment by NJM8** [comment]
Thanks, looks great. Adding the suggestion is nice.
