### ISSUE TITLE
[Bug Report] IE11 - menu list items are not vertically centered

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10464]
### Environment
**Vuetify Version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Because CodePen does not support IE11, the easiest way is reproduce that is just go to this Vuetify docs site on IE11:

https://vuetifyjs.com/en/components/menus#menus

As you can see text in dropdown items is not vertically centered.

![image](https://user-images.githubusercontent.com/17653648/73842895-ca175680-481d-11ea-8c9a-71b95f7123f9.png)

Problem exists only on IE11.

### Expected Behavior
Text in dropdown items should be vertically centered.

### Actual Behavior
Text in dropdown items is not vertically centered.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/qBdWwba" target="_blank">https://codepen.io/mikilll94/pen/qBdWwba</a>

**Comment by nclemeur** [comment]
This is still a proble with 2.2.11 (assuming this is what the vuetifyjs documentation is running):
![image](https://user-images.githubusercontent.com/7132890/74235344-812e3900-4d1a-11ea-96a8-3270416f23bc.png)

or the same example:
![image](https://user-images.githubusercontent.com/7132890/74235417-a622ac00-4d1a-11ea-8982-9fab71921a05.png)

**Comment by DRoet** [comment]
@johnleider I personally fixed this by adding 

```scss
display: block !important;
flex: none !important;
```

to `v-list-item-content`, but idk if that will affect other users

**Comment by Mikilll94** [comment]
@DRoet @johnleider 
I think I have a better solution:

```
.v-list {
  display: flex !important;
  flex-direction: column;
}
```

My solution is better because I am not removing flexbox from list items.

**Comment by DRoet** [comment]
@Mikilll94 feel free to PR and maybe John can see if he agrees with the fix

**Comment by Mikilll94** [comment]
@DRoet 
Here it is 😄
