### ISSUE TITLE
[Feature Request] Application walkthrough feature

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#10469]
### Problem to solve
Most apps today needs to walk the users through the application in their first login. For businesses this will help them same time for user training if the app itself is capable of doing that.

### Proposed solution
There are many forms of this, either a tutorial showing images or something else. What I have in mind is something like this https://github.com/pulsardev/vue-tour. It will be a neat feature for veutify to have.

**Comment by MajesticPotatoe** [comment]
duplicate #1171
