### ISSUE TITLE
[Feature Request] v-timeline-item opposite slot left/right param

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#10467]
### Problem to solve
Allow to apply specific styling depending on which side the opposite is located along the timeline

### Proposed solution
Provide a boolean `left` or `right` which indicates on which side the slot is going to be rendered.

**Comment by nekosaur** [comment]
Unless explicitly specified with `left`/`right` props, the order or left/right for a specific item is done purely by css, so there's no info to pass to slot.

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
