### ISSUE TITLE
Tabs slider no longer respects route deep linking

### ISSUE THREAD

**Issue by Stabzs** [vuetifyjs/vuetify#1046]
When using vue router to deep link to a tab, represented by a component per tab:

```js
var router = new VueRouter({
    routes: [
        { 
            path: '/nav', component: Nav,
            path: '/module/', component: Index,
            children: [
                { path: 'home', component: Home },
                { path: 'list', component: List }
            ]
        },
    ]
})
```

```html
<v-tabs dark> 
  <v-tabs-bar slot="activators">
    <v-tabs-slider class="yellow"></v-tabs-slider>
      <v-tabs-item to="/module/home">
        Home
      </v-tabs-item>
      <v-tabs-item to="/module/list">
         List
      </v-tabs-item>
    </v-tabs-bar>

  <transition name="fade">
    <router-view></router-view>
  </transition>
</v-tabs>
```
the slider no longer represents the current deep link state of the route, although the tab changes content.

### Steps to reproduce
See [codepen](https://codepen.io/anon/pen/zzVvLG).  If you click on the "module" link and then click the second tab, the content changes but the tab slider does not.

### Versions
Tested with 0.14.3 in Chrome on Windows 10.  this worked prior in 0.13.9.

### What is expected ?
I expect to see the slider follow the tab route, as in 0.13.9. 
This was closed before in https://github.com/vuetifyjs/vuetify/issues/291 and https://github.com/vuetifyjs/vuetify/issues/392

If there is a better way to handle this in 0.14.x, that would be great news :).

### What is actually happening ?
The slider no longer follows the route.

### Reproduction Link
https://codepen.io/anon/pen/zzVvLG

**Comment by chrisgillis** [comment]
If you have three tabs, select the third one, and refresh the page, you see the third router view but the v-tabs-slider is highlighting the first tab.

**Comment by johnleider** [comment]
Please don't comment on old tickets, if it is happening in a new version, you are best to create a new issue please. Thank you.
