### ISSUE TITLE
[Bug Report] After upgrading to 2.2.9 all icons have increased opacity

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10474]
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
I don't know know why in CodePen this is not working (maybe because in CodePen it is Vuetify 2.2.8?) but after upgrading to Vuetify 2.2.9 all icons have increased opacity.

To reproduce this issue just create a `v-icon` like this:
```
    <v-icon color="red">mdi-message</v-icon>
``` 

and compare how it looks like in version 2.2.8 and 2.2.9

- 2.2.8
![vuetify_icon_before](https://user-images.githubusercontent.com/17653648/73876333-1cc13480-4857-11ea-88e3-258d6e120f2f.PNG)

- 2.2.9
![vuetify_icon_now](https://user-images.githubusercontent.com/17653648/73876342-2185e880-4857-11ea-93bc-233c51192fc8.PNG)

### Expected Behavior
The icon should not be semi-transparent.

### Actual Behavior
The icon is semi-transparent.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/zYGYGej" target="_blank">https://codepen.io/mikilll94/pen/zYGYGej</a>

**Comment by MajesticPotatoe** [comment]
duplicate #10466
