### ISSUE TITLE
[Bug Report] VCheckbox - No longer responds when clicking on checkbox area

### ISSUE THREAD

**Issue by JeffersonSchuler** [vuetifyjs/vuetify#10473]
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Try clicking the check box.

### Expected Behavior
Can click on the check box area to interact with the control.

### Actual Behavior
You must click on the text area next to the control to interact with it.

### Reproduction Link
<a href="https://codepen.io/jeffersonschuler/pen/YzXzPEE" target="_blank">https://codepen.io/jeffersonschuler/pen/YzXzPEE</a>

**Comment by jalal** [comment]
Can confirm the same issue here. Backing off to previous version solved it for now.

**Comment by clebersantos** [comment]
I have this problem too. No v-select list with more than 20 items does not load. The icons are more transparent as well. It started yesterday.

**Comment by JeffersonSchuler** [comment]
I am also seeing this behavior with the VRadio control.

**Comment by MatthewAry** [comment]
Confirmed.

**Comment by johnleider** [comment]
Fixed in 4b6f14b64787f9e0461082c0306f84a56c5766be and released today with v2.2.10

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
