### ISSUE TITLE
[Bug Report] v-app-bar extended bottom hide-on-scroll transform value issue

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#10478]
### Environment
**Vuetify Version:** 2.2.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
<v-app-bar bottom fixed extended hide-on-scroll height="48" extension-height="56">

default height 48px
extension height 56px

when scrolling app bar transform translateY value is default value

i think when extended or extension height
app bar transform translateY value is extension height value

### Expected Behavior
app bar transform translateY value is extension height value

### Actual Behavior
app bar transform translateY value is default value

### Reproduction Link
<a href="https://codepen.io/ksbgenius/pen/yLNLJwQ?editable=true&editors=101" target="_blank">https://codepen.io/ksbgenius/pen/yLNLJwQ?editable=true&editors=101</a>

### Other comments
transform: translateY value change

**Comment by KaelWD** [comment]
I think the extension should be at the top for bottom app bars anyway:
![image](https://user-images.githubusercontent.com/16421948/73916589-db418f80-4911-11ea-8b41-f96fd2ad01d5.png)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
