### ISSUE TITLE
Datepicker needs two formatting functions

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#1047]
## Problem
I've been working with the date picker and I'm running into this problem. If I input a timestamp the v-model returns in the format of yyyy-mm-dd. I can use the format function to customize the date to a timestamp, but there are two problems with this.

1. It means if I need to have a human readable format other than yyyy-mm-dd I have to setup another function to convert the first one into this formatted value. This isn't a deal breaker since you would have to do this anyway. Personally I would like to be able to see that it is associated with the date picker.

2. The other problem is you can't use v-model (you have to use `:value`) on the datepicker. This is because the returned value is in the yyyy-mm-dd format and overwrites whatever format you started with.  Which among other things means in some situations you would have to manually emit the event to the parent.

## Example
Here is an example based on my project https://jsfiddle.net/wnk21h07/1/.  For some reason (perhaps because of the 14.3 menu error) I can't select any dates in the calendar, but it still shows my problem and work around.

## Solution
The simplest solution would be to add another property that allowed formatting the v-model. 

It would be nice if the v-model could return the value in the same format that was given to it, but that seems very difficult to do reliably beyond maybe Date object and timestamp.

## Notes
I could create a pull request for the date-picker code change, but this would include an API change and names chosen for the props.

Also, if having two formatting functions isn't what you want to do then it would probably be better to just have the formatting function for the v-model.

**Comment by adeari** [comment]
This  can help for format dd/mm/yyyy
https://codepen.io/adeari/pen/ZxpXbQ?&editors=101

**Comment by deividmarques** [comment]
thanks for example @adeari
