### ISSUE TITLE
[Bug Report] [VTextField] Clear icon (svg)  mis-alignment

### ISSUE THREAD

**Issue by myleslee** [vuetifyjs/vuetify#10480]
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Set 'mdiSvg' as the fonts option for Vuetify
1. Set a v-text-field 'clearable' 

### Expected Behavior
icons in a v-text-field should stay aligned. The Clear icon, in this case, should move up a little.

### Actual Behavior
The SVG icons appear lower than their FONT counterparts.

### Reproduction Link
<a href="https://codepen.io/myleslee/pen/OJVJRwB?editors=1010" target="_blank">https://codepen.io/myleslee/pen/OJVJRwB?editors=1010</a>

**Comment by DRoet** [comment]
same problem for `prepend-inner-icon` etc.

**Comment by KaelWD** [comment]
Changing the tag from `<button>` to `<i>` fixes it, but there doesn't seem to be any css different. For some reason `<button>` affects the way vertical overflow is aligned:

![image](https://user-images.githubusercontent.com/16421948/73917499-ab938700-4913-11ea-8fbd-c76a0574084e.png) ![image](https://user-images.githubusercontent.com/16421948/73917505-acc4b400-4913-11ea-9cd8-db56cd643d31.png)

**Comment by funkybg** [comment]
Clearable chips have the same issue and use font size of 18.
