### ISSUE TITLE
[Feature Request] Allow in VDataTable switch off columns sort directly without toggle between all states

### ISSUE THREAD

**Issue by jousepo** [vuetifyjs/vuetify#10484]
### Problem to solve
Prevents unnecessary calls in case of asynchronous external sorting

### Proposed solution
Add an option/prop (i.e. cancellable-sort) that enables/shows a 'cancel' button by column when the column is sorted

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
