### ISSUE TITLE
[Documentation] Navigation Drawer

### ISSUE THREAD

**Issue by FaheemNz** [vuetifyjs/vuetify#10488]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/navigation-drawers and scroll down to examples.

### Expected Behavior
The container in which Navigation Drawer examples are being rendered, doesn't have overflow property set to hidden!

### Actual Behavior
Set the overflow property of Navigation Drawer containers to hidden

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/navigation-drawers" target="_blank">https://vuetifyjs.com/en/components/navigation-drawers</a>

**Comment by MajesticPotatoe** [comment]
Can you provide some clarity on what you are expecting to see (or are seeing)? From what I can tell, examples look fine.

**Comment by KaelWD** [comment]
Just the playground I think
![image](https://user-images.githubusercontent.com/16421948/74005087-e658f600-49cb-11ea-81fa-651d03da3ddf.png)

**Comment by MajesticPotatoe** [comment]
Ah! had to toggle the v-model. Sneaky Sneaky.
