### ISSUE TITLE
[Bug Report] V-Select items stopped get loaded

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuetifyjs/vuetify#10485]
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.9
**OS:** Windows 10

### Steps to reproduce
Try to load a simple select component like the one below:

 <v-select:items="shipmentItems" v-model="form.shipment.id"></v-select>

### Expected Behavior
All items included in shipmentItems should be appear in the list. 

### Actual Behavior
Only the first 20 items from shipmentItems appears in the list.

### Reproduction Link
<a href="https://codepen.io/arvanoid/pen/NWqWapW" target="_blank">https://codepen.io/arvanoid/pen/NWqWapW</a>

### Other comments
Should be related to that recent change with lazy loading https://github.com/vuetifyjs/vuetify/commit/bd2278f745ed27938b763f570d7ef5e8cb12ff72

**Comment by moondog94** [comment]
I too am having this same. Definitely was caused by upgrade from 2.2.8 to the latest version (2.2.10). Seems like the v-select limits the items prop to only 20 items at a time.

**Comment by KaelWD** [comment]
Cause: a081e21dd16abe9d2db173268de23885d17335af
