### ISSUE TITLE
navigation drawers  is invisible when upgrade to v0.14.2+

### ISSUE THREAD

**Issue by guanxudong** [vuetifyjs/vuetify#1049]
### Steps to reproduce
1. `vue init vuetifyjs/webpack-advanced`
2. `yarn upgrade vuetify  vue`
3. `yarn run dev`
4. will see **Navigation drawers** is invisible

### Versions

0.14.2+

### What is expected ?

Navigation drawers is visible

### What is actually happening ?

Navigation drawers is invisible

**Comment by duebbert** [comment]
Can confirm this. Seems the `navigation-drawer` doesn't get the `navigation-drawer--is-booted` class once loaded.
