### ISSUE TITLE
[Feature Request] Make it possible to use A-la-carte via script tags 

### ISSUE THREAD

**Issue by betapup** [vuetifyjs/vuetify#10496]
### Problem to solve
I am implementing Vue+Vuetify in a legacy application framework where incorporating a new process, such us using vue-cli, npm and such isn't practical. I would like to have the functionality and respective benefits of only including the components of Vuetify that I am using in a particular project via script tags. 

### Proposed solution
To make it so one can include only the components one needs via script tags instead of having to include the entire Vuetify library

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
