### ISSUE TITLE
[Bug Report] v-skeleton-loader | cursor loading by default and loading prop doesn't do anything.

### ISSUE THREAD

**Issue by vianove13** [vuetifyjs/vuetify#10493]
### Environment
**Vuetify Version:** 2.2.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 73.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Create v-skeleton-loader and move cursor on it.

### Expected Behavior
It mustn't make cursor loading by default and when loading prop is false.

### Actual Behavior
It is always makes cursor loading, even when loading prop is false. 

### Reproduction Link
<a href="https://codepen.io/Googloqe/pen/rNVNdxv" target="_blank">https://codepen.io/Googloqe/pen/rNVNdxv</a>

### Other comments
https://i.imgur.com/I4fdME4.png
https://i.imgur.com/gxSMsXB.png

**Comment by KaelWD** [comment]
Use the `boilerplate` prop, by default it assumes you're going to swap it out when something has loaded.
