### ISSUE TITLE
[Bug Report] v-list-items in v-app do not react unless another button is used

### ISSUE THREAD

**Issue by umarcor** [vuetifyjs/vuetify#10494]
### Environment
**Vuetify Version:** 2.2.10
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Linux

### Steps to reproduce
Clone the repo/branch and run 'yarn serve'. See screencast below.

### Expected Behavior
The color and icon of the 'eyes' should change when clicked, without triggering other unrelated buttons.

### Actual Behavior
When 'eyes' are clicked in the dropdown menu, neither the value of the variable (array) nor the properties (color and icon) are updated. However, if another button of the app-bar is clicked, the content inside the menu is updated.

![vuetify_layers](https://user-images.githubusercontent.com/38422348/73962157-31143880-490e-11ea-8053-51c5e6fedba2.gif)

### Reproduction Links
- <a href="https://github.com/umarcor/hwstudio/blob/bug-layers-react/src/App.vue" target="_blank">https://github.com/umarcor/hwstudio/blob/bug-layers-react/src/App.vue</a>
- <a href="https://umarcor.github.io/hwstudio/" target="_blank">https://umarcor.github.io/hwstudio/</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/list.html#Caveats

**Comment by umarcor** [comment]
Thanks. Sorry for bothering you, and kudos for the label. It's quite fun 🤣
