### ISSUE TITLE
enable native/smooth scrolling for mobile devices

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#105]
Hello,

I would suggest to enable some smooth scrolling for iOS or Android devices. The library of https://material.angularjs.org/latest/ did a nice job with this feature, their library feels almost like native scrolling in usage.

Thanks

**Comment by johnleider** [comment]
For now, I think that this would be a very low priority task, if ever. I'm going to opt to close this for now. Will accept a PR.
