### ISSUE TITLE
[Bug Report] ICONS - Font Awesome Duotone Incomplete Icons

### ISSUE THREAD

**Issue by Dissociable** [vuetifyjs/vuetify#10505]
### Environment
**Vuetify Version:** 2.2.12
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Windows 10, Windows, Android, iOS, Linux, Mac OSX

### Steps to reproduce
Use Font Awesome Duotone 'CSS - Webfonts' icons within <v-icon> and that's it.
NOTE: svg icons are working!

### Expected Behavior
Complete icon
Working example with Vuetify 2.2.8: https://codepen.io/Dissociable/pen/Poqorvm

### Actual Behavior
The icon is incomplete, not displaying some parts

### Reproduction Link
<a href="https://codepen.io/Dissociable/pen/VwLwJqv" target="_blank">https://codepen.io/Dissociable/pen/VwLwJqv</a>

**Comment by Dissociable** [comment]
Ok then it's still the same for 2.2.12, not yet fixed, updated the Codepen to 2.2.12.

**Comment by KaelWD** [comment]
Duotone uses both ::before and ::after, and we started using ::after for the focus ring in 2.2.9.

**Comment by johnleider** [comment]
Is this a regression? We've never explicitly supported it and it currently sits as a Feature Request in #8809 . We can look into potential fixes but have no plans atm to revert the a11y change.

**Comment by KaelWD** [comment]
> We've never explicitly supported it

`isFontAwesome5` checks for `'fad'`

**Comment by FrancoisH** [comment]
May I say you do support FontAwesome and the Pro version of FontAwesome 5 work really fine with Vuetify **but** the **duotone**, which were perfectly fine a few Vuetify version before.

**Comment by MajesticPotatoe** [comment]
@FrancoisH likely due to <https://github.com/vuetifyjs/vuetify/issues/8809#issuecomment-585871554>

**Comment by johnleider** [comment]
We use the pseudo elements specifically for a11y purposes so even as a regression, this won't be reverted. With that being said, we are tracking https://github.com/vuetifyjs/vuetify/issues/8809 as the primary issue for this issue. Please follow it for future updates.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
