### ISSUE TITLE
[Bug Report] Incosistent animation for bottom sheets

### ISSUE THREAD

**Issue by funkybg** [vuetifyjs/vuetify#10506]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Click open persistent
2. Close the sheet
3. Open again
4. Repeat

### Expected Behavior
Bottom sheet open and close animation should be consistent.

### Actual Behavior
On initial open, the sheet slides up.
On consecutive opens / closes the sheet fades in and out

### Reproduction Link
<a href="https://codepen.io/mmartev/pen/mdJydxV" target="_blank">https://codepen.io/mmartev/pen/mdJydxV</a>

**Comment by KaelWD** [comment]
John's fault: https://github.com/vuetifyjs/vuetify/pull/8823/files/efb7adb8ffea7faf9cf78ad639f9f70bdf571976#diff-6d73f6698e69f2b6c718dfed6b89cd34
