### ISSUE TITLE
[Bug Report] IE11 - right navigation drawer overflows data table

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10508]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Problem exists only on IE11.

1. Run this project (because CodePen does not support IE11 you need to run the repro in your local environment) on Chrome and IE11.

Here is the link to the project:
[datatable-test.zip](https://github.com/vuetifyjs/vuetify/files/4171381/datatable-test.zip)

2. As you can see on IE11 right navigation drawer overflows data table.. On Chrome everything is fine.

Chrome:
![image](https://user-images.githubusercontent.com/17653648/74040263-a5f57a00-49c3-11ea-9ca5-fb5c54ab0174.png)

IE11
![image](https://user-images.githubusercontent.com/17653648/74040295-ba397700-49c3-11ea-9609-4774a9c4aa12.png)

### Expected Behavior
Right navigation drawer should not overflow data table.

### Actual Behavior
Right navigation drawer overflows data table.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/mdJyJWz" target="_blank">https://codepen.io/mikilll94/pen/mdJyJWz</a>

**Comment by DRoet** [comment]
Workaround is to wrap the datatable in a `v-row` + `v-col`

```vue
<v-content>
   <v-row>
       <v-col>
          <v-data-table :headers="headers" :items="desserts" :items-per-page="5" class="elevation-4"></v-data-table>
       </v-col>
   </v-row>
</v-content>
```

Not sure if we can add a direct fix to v-content without breaking stuff

**Comment by Mikilll94** [comment]
@DRoet 
Do you have any idea why `padding-right` is not working correctly for `v-content` on IE11?

**Comment by amit-feldman** [comment]
Issue still exists.
Lots of columns with long content within the table will trigger this overflow issue

**Comment by akomarovsky** [comment]
It also happens with Microsoft Edge chromium
![image](https://user-images.githubusercontent.com/20887752/93982439-e9053180-fd89-11ea-9849-5d28e73f337a.png)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
