### ISSUE TITLE
[Bug Report] Grid with flex-shrink not working well on IE11

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10509]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Problem exists only on IE11. Because CodePen does not support IE11 you need to run it in your local environement.

1. Run the repro on Chrome and IE11.
2. As you can see on IE11, the button overflows the input. On Chrome everything is nice.

Chrome
![image](https://user-images.githubusercontent.com/17653648/74045054-67b08880-49cc-11ea-85fc-68b99040b7e6.png)

IE11
![image](https://user-images.githubusercontent.com/17653648/74045082-726b1d80-49cc-11ea-8158-94179dc872ac.png)

### Expected Behavior
Button should not overflow the input

### Actual Behavior
Button overflows the input

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/zYGxvLy" target="_blank">https://codepen.io/mikilll94/pen/zYGxvLy</a>

**Comment by MajesticPotatoe** [comment]
likely: https://github.com/philipwalton/flexbugs#flexbug-1

**Comment by MajesticPotatoe** [comment]
https://github.com/philipwalton/flexbugs#flexbug-6

**Comment by Mikilll94** [comment]
@MajesticPotatoe 
Thanks, but in this flexbug-6 they say that this bug was fixed in IE11. So why my example is not working? Do you know any workaround to make my example working?

I will be very glad for any help.

**Comment by MajesticPotatoe** [comment]
Not sure. I dont use IE. Would look to see if there are any structural/styles between the 2 browsers, and that will likely lead you to the cause. Could be another flex related bug that's not well documented.

**Comment by KaelWD** [comment]
I think it's flexbug#1 (shrinking below content size). You should use `cols="auto"` to properly set the width: https://output.jsbin.com/subehuqehi
