### ISSUE TITLE
[Feature Request] App Bars: Bottom

### ISSUE THREAD

**Issue by nainardev** [vuetifyjs/vuetify#10517]
### Problem to solve
>Bottom app bars provide access to a bottom navigation drawer and up to four actions, including the floating action button.

Currently there's no component to match this specification

### Proposed solution
https://material.io/components/app-bars-bottom/app-bars-bottom.html

**Comment by KaelWD** [comment]
Already possible with the `bottom` prop, #2553 for the FAB.
