### ISSUE TITLE
[Feature Request] Treeview component - new selection type

### ISSUE THREAD

**Issue by funder7** [vuetifyjs/vuetify#10511]
### Problem to solve
Hello,

I've found a possible improvement for this component, with selectable set to true.

Now I can choose between two types:

leaf (default): to select all the items under the root (root Id included).

independent: click on every single item

But if I need to select just the single root item, that is not possible:
I can select a children, or I can select the whole node, but I cannot isolate the root Id this way. 

example (sel-type: leaf):

* root (id: 0)
 + item 1 (id: 1)
 + item 2 (id: 2)
x item 3 (id: 3)

returns = [0, 1, 2]

Clicking on root node:

+ root (id: 0)
 + item 1 (id: 1)
 + item 2 (id: 2)
 +  item 3 (id: 3)

returns = [0, 1, 2, 3]

it doesn't render well with markdown... 

empty dot:  full check 
black dot:   middle check
x: not checked

### Proposed solution
It would be nice to have a third selection type, that would act on the node with "independent" style, when the node is not expanded (it will select only the visible element, aka the root item). 

+ root (id: 0) ->  return [0]

While if the node is expanded, then selecting the root item, will use the "leaf" style, selecting all the childrens.

If I want to select only the root, then I unexpand the node, and click on the root. 

Thanks for watching! ;)

**Comment by fadafez** [comment]
Hello, has anybody seen this post?

**Comment by jacekkarczmarczyk** [comment]
Now I can see it, but i don't remember if I've seen it before

**Comment by fadafez** [comment]
Ok, no problem!

**Comment by fadafez** [comment]
@jacekkarczmarczyk what's the time to have this feature evaluated and in case developed ? thanks

**Comment by KaelWD** [comment]
Duplicate of #7799

**Comment by funder7** [comment]
Well the new issue is a duplicate of this one in fact.

**Comment by KaelWD** [comment]
? 
#7799 is older.

**Comment by funder7** [comment]
:-D sorry
