### ISSUE TITLE
[Bug Report] v-file-input prepend slot does not work

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#10519]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
add a v-file-input component and use the v-slot:prepend to add the icon instead of the prepend-icon property! it would not put any icon

### Expected Behavior
The icon should show up before the file-input field

### Actual Behavior
No icon is showen

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/XWbJVXQ?editors=1010" target="_blank">https://codepen.io/mtermoul/pen/XWbJVXQ?editors=1010</a>

### Other comments
See my code pen

**Comment by bad4iz** [comment]
Duplicate #9580
