### ISSUE TITLE
[Bug Report] Child Components on v-bottom-sheet version >= 2.2.9

### ISSUE THREAD

**Issue by AgiletechSolutionsLLC** [vuetifyjs/vuetify#10514]
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
- Click Button Labeled Open Persistent
- DHTMLX Calendar Not Initialized on $nextTick in method onOpenClick for Vuetify >= 2.2.9

Change Vuetify version to 2.2.8 and it works

### Expected Behavior
Child controls are available in the DOM on $nextTick

### Actual Behavior
Child controls not available in the DOM on $nextTick

### Reproduction Link
<a href="https://codepen.io/agiletechsolutions/pen/QWbWVqz" target="_blank">https://codepen.io/agiletechsolutions/pen/QWbWVqz</a>

**Comment by KaelWD** [comment]
It takes an extra tick now to detach the content: https://github.com/vuetifyjs/vuetify/commit/2b975f575f47ba75aa5d0dd9fba859595c7b9ba4#diff-485fd15bc103276657fc4d71a06de402R57
Using setTimeout instead of nextTick works in both versions.
