### ISSUE TITLE
[Bug Report] Combobox - value selected on blur

### ISSUE THREAD

**Issue by Waserman** [vuetifyjs/vuetify#10510]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.2

### Steps to reproduce
1) open the CodeSandbox example.
2) type 'Vue' (which is one of the options) in the Combobox search input
3) click outside of the Combobox menu

### Expected Behavior
1. The menu should be close
2. the value 'Vue' should not be selected

### Actual Behavior
The menu is closed
The value 'Vue' appears to be selected (inside the v-slot__selected, as a chip or text), but actually if I open the Combobox menu the checkbox related to the Blue option is not selected.

### Reproduction Link
<a href="https://codepen.io/waserman2302/pen/vYOELyg?editable=true&editors=101" target="_blank">https://codepen.io/waserman2302/pen/vYOELyg?editable=true&editors=101</a>

### Other comments
This bug can also be reproduced in you official docs

**Comment by KaelWD** [comment]
Use v-autocomplete if you don't want the value to be saved. 

> the checkbox related to the Blue option is not selected

Cannot reproduce
![image](https://user-images.githubusercontent.com/16421948/74077625-5b343a80-4a75-11ea-8b27-4f61b470040b.png)
