### ISSUE TITLE
[Feature Request] v-slide-group enable mouse drag to slide on desktop

### ISSUE THREAD

**Issue by jaunt** [vuetifyjs/vuetify#10524]
### Problem to solve
Users seem to expect to be able to drag it with the mouse, not just click the arrows.  

### Proposed solution
Have a setting that enabled mouse dragging.  Of course activating an item via clicking would have to happen on press-release, and if a drag occurred before the release, the pending click would have to be cancelled.  Note also that when a horizontal drag is detected, disabling vertical scroll would be great, even on mobile.  Right now it's tricky on mobile not to scroll vertically while trying to drag a v-slide-group horizontally.  Something like swiperJS features this kind of behaviour.

**Comment by BonBonSlick** [comment]
Can not create issue.

Tell me plase how to use multiple icon sets?

    ```
    defaultAssets: {
            icons: [
                // 'fa',
                'mdi',
            ],
        },
```

**Comment by johnleider** [comment]
We need to come up with a process for how we handle touch on mobile and desktop. So far, I've avoided anything to do with drag and/or drop like the plague.

Optionally we could ensure that Vuetify integrates into an existing drag/drop library. This one needs feedback from @vuetifyjs/core-contributors @vuetifyjs/core-team

**Comment by WaldemarEnns** [comment]
Yes, definitely requesting this! :)

**Comment by Bankole2000** [comment]
Just wanted to say I'm definitely requesting this as well... Also to capture and scroll horizontally on mouse wheel event...

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
