### ISSUE TITLE
[Bug Report] v-menu no longer rendering all the v-lists

### ISSUE THREAD

**Issue by saravankumarpa** [vuetifyjs/vuetify#10522]
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
when more than one v-list is used inside a v-menu , its used to render all the lists.
from 2.2.9 version , it renders only the first list and ignores the other .And no errors are shown. 
If vueitfy 2.2.8 version or lower is used , it renders all the lists with in the v-menu. Sudden change of behaviour with no error is hard to track down.Its not a blocking behaviour since code can be rewritten easily.But would like to know if this an intended behaviour or a glitch.

### Expected Behavior
Till 2.2.8 , multiple v-lists were supported.Either render all the lists or show an error .

### Actual Behavior
Doesnt render all the lists ,and also no errors .So its hard to track down

### Reproduction Link
<a href="https://codepen.io/sar13/pen/rNVavYE" target="_blank">https://codepen.io/sar13/pen/rNVavYE</a>

### Other comments
Would like to know if the 2.2.8 behaviour is gonna be supported or should rewrite so that multiple lists are not included in the v-list

**Comment by KaelWD** [comment]
Related: cc17fe19

@jacekkarczmarczyk everything touched in 2b975f5 needs checking.

**Comment by BonBonSlick** [comment]
Can not open issue, tall me please how to use multiple icon sets?
```

iconfont: {
            'fa': '',
            'mdi': '',
        },
        icons: {
            'fa': '',
            'mdi': '',
        },
        iconfont:  ['fa', 'mdi'],
        icons:  ['fa', 'mdi'],
     defaultAssets: {
            icons: [
                'fa',
                'mdi',
            ],
        },
```
does not work

**Comment by savylovskij** [comment]
When will the bug fixes [Bug Report] v-edit-dialog missing buttons after update to 2.2.12 # 10572?

**Comment by Qadosch** [comment]
> 
> 
> When will the bug fixes [Bug Report] v-edit-dialog missing buttons after update to 2.2.12 # 10572?

on 2.2.13 or basicaly now, i confirmed it to be working

**Comment by peshanghiwa** [comment]
version 2.5.8, v-edit-dialog buttons are missing
