### ISSUE TITLE
[Bug Report] v-radio template slots does not work

### ISSUE THREAD

**Issue by bloodsbro** [vuetifyjs/vuetify#10520]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
1. Create v-radio element
2. Create template in this element with slot append/prepend/default and set any content (text/image)

### Expected Behavior
Content is showed

### Actual Behavior
Content not showed

### Reproduction Link
<a href="https://codepen.io/bloodsbro/pen/jOPEzyB" target="_blank">https://codepen.io/bloodsbro/pen/jOPEzyB</a>

**Comment by KaelWD** [comment]
v-radio only has a label slot.
