### ISSUE TITLE
[Bug Report] VTextField Side Effect Unchecks VCheckbox

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#10521]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
1. Open codepen
2. Select one or both checkboxes and note that object values are placed into the `checkbox` data array.
3. Type a number digit into the days `v-text-field`.
4. Note that the checkboxes markup clears (though it shouldn't) and the checkbox data values remain.

### Expected Behavior
Interacting with a `v-text-field` shouldn't have an unintended side effect of changing a `v-checkbox`.

### Actual Behavior
`v-text-field` input clears previously set `v-checkbox` in markup.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/dyoPmry" target="_blank">https://codepen.io/185driver/pen/dyoPmry</a>

### Other comments
This side effect doesn't happen if the `v-checkbox`value prop is a simple unbound string value.

**Comment by KaelWD** [comment]
Objects in templates are re-created on each render, so the value is updated and isn't equal to the model any more.
