### ISSUE TITLE
[Bug Report] Unit Testing: $refs do not exist

### ISSUE THREAD

**Issue by rynnova** [vuetifyjs/vuetify#10523]
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 1.5.16
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
1. Clone repo in reproduction link.
2. Install dependencies (`npm i`).
3. Run unit tests (`npm run test:unit`).

### Expected Behavior
Unit tests run and pass.

### Actual Behavior
Get `TypeError: Cannot read property 'reset' of undefined` when attempting to access methods off of components in `$refs` object, because `$refs` never populates.

### Reproduction Link
<a href="https://github.com/rynnova/refs-do-not-exist" target="_blank">https://github.com/rynnova/refs-do-not-exist</a>

### Other comments
I have not tested to see if this is a Vue.js issue, but since a previous Vuetify version worked, I don't think it is.

**Comment by KaelWD** [comment]
Dialogs are now lazy by default, the content is not rendered until it is open.

**Comment by rynnova** [comment]
So there's no solution for this?

**Comment by rynnova** [comment]
Looking through the documentation, I don't see how to change a component from lazy to strict loading/rendering.
