### ISSUE TITLE
[Bug Report] Autocomplete with prefix & placeholder style bug

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuetifyjs/vuetify#10538]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
- Open codesandbox
- See that prefix conflict with placeholder
- If focus on field all ok (without focus prefix with position:absolute)

### Expected Behavior
Prefix will not conflict with placeholder

### Actual Behavior
Prefix on top of placeholder

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-3sesn" target="_blank">https://codesandbox.io/s/vuetify-playground-3sesn</a>

![Снимок1](https://user-images.githubusercontent.com/4497128/74220263-2bc53e00-4cc0-11ea-913e-8023549d21d1.PNG)
![Снимок2](https://user-images.githubusercontent.com/4497128/74220264-2d8f0180-4cc0-11ea-95d6-f23eba052a89.PNG)

**Comment by YipingRuan** [comment]
Caused by packages\vuetify\src\components\VSelect\VSelect.sass

````sass
  &:not(.v-input--is-dirty)
    &:not(.v-input--is-focused)
      .v-text-field__prefix
          line-height: $select-prefix-line-height
          position: absolute  // <== This
          top: $select-prefix-top
          transition: $primary-transition
````

**Comment by GustavoEdny** [comment]
Same problem here but without autocomplete

**Vuetify Version**: 2.1.0
**Vue Version**: 2.6.10
**Browsers**: Chrome 80.0.3987.106
**OS**: Ubuntu 19.04

![](https://i.imgur.com/J8q6BhT.png)

![](https://i.imgur.com/V9eM2ul.png)
