### ISSUE TITLE
[Documentation] Add Testing Commands to Contributing 

### ISSUE THREAD

**Issue by rachael-smith** [vuetifyjs/vuetify#10537]
### Problem to solve
There is no information on how to run tests for contributors 

### Proposed solution
add commands/information about how to run tests in contributing

**Comment by olegstepura** [comment]
For anyone else willing to contribute and ending up here. Looks like this is enough to run unit tests for components (assuming you are in project root folder):
```sh
cd packages/vuetify/
jest
```
of cause you need to run `yarn install` before
