### ISSUE TITLE
[Bug Report] IE11 - treeview items are not centered vertically

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10534]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Treeview items are not centered vertically on IE11.

Because CodePen does not support IE11 you need to run this sample in your local environment. You can also just go to the Vuetify docs on IE11 to see this bug in action:
https://vuetifyjs.com/en/components/treeview#treeview

IE11
![image](https://user-images.githubusercontent.com/17653648/74174051-8f555a00-4c33-11ea-9737-7a9bade9024a.png)

Chrome
![image](https://user-images.githubusercontent.com/17653648/74173902-42718380-4c33-11ea-8be2-9faa87b114fd.png)

### Expected Behavior
Treeview items should be vertically centered

### Actual Behavior
Treeview items are not centered vertically.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/GRJJWQm" target="_blank">https://codepen.io/mikilll94/pen/GRJJWQm</a>

**Comment by DRoet** [comment]
Probably the same issue as https://github.com/vuetifyjs/vuetify/issues/10464

**Comment by DRoet** [comment]
@Mikilll94 would this require a similar fix as https://github.com/vuetifyjs/vuetify/pull/10717?

**Comment by Mikilll94** [comment]
@DRoet 
Here is the PR
