### ISSUE TITLE
[Documentation] Custom dark scrollbar for dark mode in DOCS

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#10547]
### Environment

**Browsers:** Chrome 81.0.4044.9
**OS:** Linux x86_64

### Steps to reproduce
https://vuetifyjs.com/en/introduction/why-vuetify

### Expected Behavior
dark scrollbar

### Actual Behavior
white scrollbar for dark theme

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/why-vuetify" target="_blank">https://vuetifyjs.com/en/introduction/why-vuetify</a>

### Other comments
* https://css-tricks.com/the-current-state-of-styling-scrollbars/
* https://caniuse.com/#feat=css-scrollbar

**Comment by KaelWD** [comment]
#14039
