### ISSUE TITLE
[Bug Report] IE11 - v-time-picker flickers when selecting hour

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10542]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Run the repro on IE11
2. Select any hour in the `v-time-picker`.
3. As you can see, there is a visible flicker.

![timepicker_flicker_ie11](https://user-images.githubusercontent.com/17653648/74237054-f118d100-4cd2-11ea-935e-599307412dfb.gif)
This bug exists only on IE11. Because CodePen does not support IE11 you need to reproduce this bug in your local environment or just go to the Vuetify docs on IE11.
https://vuetifyjs.com/en/components/time-pickers#time-pickers

### Expected Behavior
There should be no flicker when selecting an hour in the `v-time-picker`.

### Actual Behavior
When selecting an hour in the `v-time-picker` there is a visible flicker.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/MWwwZbB" target="_blank">https://codepen.io/mikilll94/pen/MWwwZbB</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
