### ISSUE TITLE
[Bug Report] [VIcon] bug on .v-icon::after position 

### ISSUE THREAD

**Issue by SuhwanCha** [vuetifyjs/vuetify#10545]
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** Mac OS 10.15.3, iOS

### Steps to reproduce
with Material Icons,
``` html
<v-icon>navigate_next</v-icon>
```

### Expected Behavior
i.v-icon::after locate on icon

### Actual Behavior
i.v-icon::after locate *next* on icon
![image](https://user-images.githubusercontent.com/16171447/74305556-9ac79300-4da3-11ea-8d72-e942492e1ab6.png)

### Reproduction Link
<a href="https://codesandbox.io/embed/focused-hooks-sxmip?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/focused-hooks-sxmip?fontsize=14&hidenavigation=1&theme=dark</a>

**Comment by johnleider** [comment]
I'm not sure what this hurts or helps but it's not something we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
