### ISSUE TITLE
[Feature Request] Can support scroll-taget of v-app-bar be a dynamic parameter？

### ISSUE THREAD

**Issue by lzm0x219** [vuetifyjs/vuetify#10556]
### Problem to solve
When I have multiple v-tab-item components, I want the scrolling of each of them to be effective for v-app-bar.

### Proposed solution
not yet

**Comment by nekosaur** [comment]
Please include a codepen or codesandbox that illustrates what you are trying to achieve. Thank you.

**Comment by vvni** [comment]
@nekosaur  https://codepen.io/vvni/pen/NWqRjYj    I hope the scrolling of other views will also affect v-app-bar.

**Comment by jacekkarczmarczyk** [comment]
I've attempted to solve it v3 https://github.com/vuetifyjs/vuetify/pull/10413/files#diff-1b22fa4a7dfbb8e952e5ecdec4831585R83

**Comment by vvni** [comment]
> I've attempted to solve it v3 https://github.com/vuetifyjs/vuetify/pull/10413/files#diff-1b22fa4a7dfbb8e952e5ecdec4831585R83 (might need to add a test though)

cool~ 👏

**Comment by johnleider** [comment]
I'm still unclear as to what this is asking for.

**Comment by nekosaur** [comment]
I'm assuming it's the fact that only the first tab makes the app bar shrink? Scrolling in the other two tabs has no effect.

**Comment by vvni** [comment]
> I'm assuming it's the fact that only the first tab makes the app bar shrink? Scrolling in the other two tabs has no effect.

yes.

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNrdVW1v0zAQ/itWQKITee3oBqErGvyFfaNIcxI3sebEln1tV1X975yTtM1LQQNNfCAfIvvunse+87183ztGp8G9Uv5mzZzYmQMrlaDAFsuKkPnGo0rVy3qTygoor5huRY2Q6oykghpzt3TkhumVkFuv4FnGqqVzsjyyeQnVZxkhNDFSrIF1ZakUUiPbm5v725v7r0unq+QlzRkqCwBl4iBQPDXr0leFBGmC6NM0DKLwY/hF0yqTZR8bm1RLITygOmeAJM3+od72TVvLhBV0w+vbrGjGvPr0rmXHQXTxGD6y8YyQEPMyR+SeKC2VIYdePNqYoElfRhCc8CpDYA3r38t+uaYZZ5V1ACQBqYjmeQEu0XlCJ1EYulE0c6dh5Pq3V610OnOvp+7t1IqGjIt5UN+j70vQyYWe4vSOXkURh1lRE4yEIxhIKawFcBBs8WD/FtgXj1BG0RRTzlq2y5FJAhVpjxxG10rLjHv4bhVf7WpPh5ZWiBR/xVswquHVWTMJxsNaAp5S8SfswwRkz8Aqwy8dBlh6aFbKjAmbSbhdOoQKnlfelkNxeo9+8jXIxQNNSFS/Hm5+YzN9gc31ZZtWan6dll3LNv36DWeLdSS3Yy+P/eobdjQspEFdnoAex8PGzW3n0TVIpDGwE7YXlfQZE8HWYExuwlA9Xyr0U/c8wY4QrFjEfCYJTZ9yLddVFhPFqydksZ6N2+7R584t/6UDw6d8iT+5ZnYeXGg8/4V7Oybw5Ffx76w5j1lLg3P2OIpHrG0B4HrQtuc4x7gCYhism0nOSyU1kD3ZUkgLciArLUvyDuf/u55as9VAadV4rAFSt447azIJr87i7jRt1ai1+vqsSXN7C3ab5YYKcrcg+6OfXQIflWuGNI9+L1Jxha1JrjzYKTZ5u7cU70l0uHpsSA4t9R49KVnGMRAxAY1MB6vA+8yDJiYYDefgOtf+Bz+aOXYx8yPnx09kZ6xm
