### ISSUE TITLE
[Bug Report] Dark Theme - States overlay opacities are incorrect

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#10557]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Using a Select with dark theme, the transparency/alpha on a selected option doesn't match the Material specs. Currently, the alpha is 24%, but by default, it should be 12%.

### Expected Behavior
* Match transparency of official Material Dark Theme specs: https://material.io/design/color/dark-theme.html#states
* See Overlay opacity values from the States documentation: https://material.io/design/interaction/states.html#anatomy
![image](https://user-images.githubusercontent.com/1559447/74379986-bbe5af00-4db6-11ea-8040-66caebb6cb5d.png)
* The surface of an object that gets higher elevation, should also become lighter. Read the [Properties -> Elevation guidelines here](https://material.io/design/color/dark-theme.html#properties).
   * [See this nice reference video from Material guidelines](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1579302979877%2Fassets%2F1ro3dFa9v71nmSj8eg-tqN83z1Hcclgeu%2Fdarktheme-lightsource.mp4).

### Actual Behavior
N/A

### Reproduction Link
<a href="https://codepen.io/megaroeny/full/mdJeLEJ" target="_blank">https://codepen.io/megaroeny/full/mdJeLEJ</a>

### Other comments
Notice that other components with Dark Theme being used are not consistent. Button Groups is another example.

**Comment by megaroeny** [comment]
Updated description again, with a note about surface elevation for dark theme, with example video.

**Comment by johnleider** [comment]
We won't be able to accommodate surface elevation in dark theme.

**Comment by johnleider** [comment]
This is happening in version 3 with the updated theme system. Follow for future updates https://github.com/vuetifyjs/vuetify/issues/12688.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
