### ISSUE TITLE
[Feature Request] V-bottom-navigation reverse hide-on-scroll

### ISSUE THREAD

**Issue by Ruudje87** [vuetifyjs/vuetify#10553]
### Problem to solve
I have Vuetify version vuetify@2.2.12 and scrolling downwards reveals the bar instead of hiding it. So exactly what the Vuetify documentation says. But in material.io its says:

Scrolling
Upon scroll, the bottom navigation bar can appear or disappear:
Scrolling downward hides the bar
Scrolling upward reveals it

So scrolling UP reveals.

If i use a v-app-bar with a bottom attribute this shows correct behaviour.

### Proposed solution
Can you add a reverse scroll attribute so the hide-on-scroll wil work with both directions of scrolling?

**Comment by nainardev** [comment]
Looks great! Could you link the material.io page?

**Comment by Ruudje87** [comment]
Here you are: https://material.io/components/bottom-navigation/#behavior
Section: Scrolling

**Comment by johnleider** [comment]
This will be part of sharing scrolling techniques with v-app in the future.

**Comment by johnleider** [comment]
For v3, v-bottom-nav will essentially be v-app-bar with styling changes. However, this is not something we would do for v2. You can follow this issue for future updates: https://github.com/vuetifyjs/vuetify/issues/12709

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
