### ISSUE TITLE
[Documentation] Three 404's on Vuetify Docs

### ISSUE THREAD

**Issue by jj-dominguez** [vuetifyjs/vuetify#10560]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
Menu, Data Iterator, and Tooltips pages are showing a 404 on the current Vuetify docs

https://vuetifyjs.com/en/components/menus
https://vuetifyjs.com/en/components/data-iterators

### Expected Behavior
Menu and tooltip pages work.

### Actual Behavior
404s

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tooltips" target="_blank">https://vuetifyjs.com/en/components/tooltips</a>

### Other comments
Cheers! Thanks for building a great product.

**Comment by MajesticPotatoe** [comment]
Can you try clearing your cache. All 3 of those links seem to work (in both regular and incognito) from my end here.

**Comment by whoistobias** [comment]
I also gave those link a check. Seems this is no longer relevant. Closing for now.
