### ISSUE TITLE
[Feature Request] Chart Skeleton Loader

### ISSUE THREAD

**Issue by allanchua101** [vuetifyjs/vuetify#10564]
### Problem to solve
On applications with chart widgets, we currently have no way of making a skeleton loader for a chart using Vuetify. This makes the user experience weird as some components do not have skeleton loaders.

### Proposed solution
Add support for chart skeleton loaders.

**Comment by guykatz** [comment]
man I need this. 1.5 years later is this still on the table?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
