### ISSUE TITLE
[Feature Request] Add required field to v-btn-group for validation purposes.

### ISSUE THREAD

**Issue by shadow7412** [vuetifyjs/vuetify#10577]
### Problem to solve
It would allow people to be forced to make a selection, without assuming any default.

### Proposed solution
Add a required prop to v-btn-group, and ensure that v-form considers this when running validation.

**Comment by KaelWD** [comment]
You can use [`v-validation`](https://next.vuetifyjs.com/en/api/v-validation/) for this in v3 (examples coming soon&trade;)
