### ISSUE TITLE
[Bug Report] Switch color gets reset to default color.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [vuetifyjs/vuetify#10573]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
-1: Open https://codepen.io/inyourface/pen/yLNeYbe
-2: Turn on`v-switch` and then turn it off.
-3: Now, click on `v-btn`.
-4: and **wow!** `v-switch` color is no more there (it's set to default one!)

### Expected Behavior
The color shouldn't be reset to default.

### Actual Behavior
The color resets to default.

### Reproduction Link
<a href="https://codepen.io/inyourface/pen/yLNeYbe" target="_blank">https://codepen.io/inyourface/pen/yLNeYbe</a>

### Other comments
Also tried without `inset` property and the result is the same (default color on clicking on `v-btn`).

**Comment by nekosaur** [comment]
For selection control components such as v-switch, the v-model is bound to `input-value` prop and `@change` event. If you change `value` to `input-value` in your example, things work as intended.
