### ISSUE TITLE
[Bug Report] v-radio-group not selected initially with value type of "Object"

### ISSUE THREAD

**Issue by haugero** [vuetifyjs/vuetify#10571]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Mac OS 10.15.3

### Steps to reproduce
Just open Codepen link and see the radio group

### Expected Behavior
The radio button "two" is initially selected

### Actual Behavior
No radio button is selected initially

### Reproduction Link
<a href="https://codepen.io/ohauger/pen/gOpPpje" target="_blank">https://codepen.io/ohauger/pen/gOpPpje</a>

### Other comments
I also tried to set the "value-comparator" with my own compare function BUT the function never get's called

**Comment by jacekkarczmarczyk** [comment]
Not a bug

![image](https://user-images.githubusercontent.com/15625235/74800083-fa262580-5304-11ea-9b6a-f7732d9b7fa7.png)

VRadioGroup/VRadio doesn't have value comparator, you need to use the same object:

https://codepen.io/jkarczm/pen/YzXWRMe

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/74802297-8e0be780-532d-11ea-9465-e36ebbf1b3f6.png)

**Comment by jacekkarczmarczyk** [comment]
how did i miss it

**Comment by KaelWD** [comment]
Or is it a bug? valueComparator was added in 78964e36893f34021989feb9e588d23dac0b76f9 but then radios were refactored to use VItemGroup instead, which doesn't have valueComparator.

**Comment by Invisibly** [comment]
That is also a problem for us. Is there something new?

**Comment by ElijahKotyluk** [comment]
One of the base mixins for VRadioGroup is Comparable, but if you pass `value-comparator` a function it doesn't ever get called.

**Comment by Ovsdrak** [comment]
I have this issue too, is there any news?
