### ISSUE TITLE
[Bug Report] Unit test cases are failing with Vuetify component registration is failed error

### ISSUE THREAD

**Issue by baluonline** [vuetifyjs/vuetify#10575]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.10

Unit test cases are keep failing with vuetify-2.0 and vue-loader-1.4.3 for all vuetify components (eg : vcontainer , vrow, vcol, vcard etc) 

**Error :** 
<console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
[Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.

"vuetify": "^2.0.2",
"jest-vue": "^0.8.2",
"vuetify-loader": "1.4.3",
"vue-loader": "^12.2.2",
"babel-core": "^6.26.0",
"babel-loader": "^7.1.2",

****
Package.json have below jest configs
```
"jest": {
"moduleFileExtensions": [
"js",
"json",
"vue"
],
 "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
"testURL": "http://localhost/",
"transform": {
".*\.(vue)$": "/node_modules/vue-jest",
"^.+\.js$": "babel-jest"
},
"setupFiles": [
"/test/jest-setup.js"
],
"globals": {
"vue-jest": {
"tsConfig": {
"importHelpers": true
},
"babelConfig": {
"presets": [
["env",{
"useBuiltIns": "entry",
"shippedProposals": true}]],
"plugins": [
"syntax-dynamic-import"],
"env": {
"test": {
"plugins": [
"dynamic-import-node"]}}}}}}
```

**Comment by johnleider** [comment]
Have you went through the testing guide? It sounds like you are missing the setup file.

https://vuetifyjs.com/getting-started/unit-testing

**Comment by baluonline** [comment]
Yes, Registrations issues got resolved. Thank you!

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
