### ISSUE TITLE
[Bug Report] VCalendar's custom-weekly view messes up events when showing multiple weeks in a row

### ISSUE THREAD

**Issue by ngrie** [vuetifyjs/vuetify#10585]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.5, Google Chrome
**OS:** Mac OS 10.15.3, Windows

### Steps to reproduce
Use a VCalendar with `type="custom-weekly"` and a `weekdays` array containing a row of weekday numbers multiple times.

### Expected Behavior
The position/order of concurrent events is calculated correctly and is retained all the time.

### Actual Behavior
At the end of the first week in each row, the event's title is printed again, events are continued displaced and are messing up/changing order with concurrent events or are getting duplicated.

### Reproduction Link
<a href="https://codepen.io/ngrie/pen/mdJVoza" target="_blank">https://codepen.io/ngrie/pen/mdJVoza</a>

### Other comments
Building a vacation calendar, I wanted to show more than one week per row, so I added the weekday numbers twice in the `weekdays` array. I was really excited that the calendar component is flexible enough to make this work until I recognized this subtle bug. I know the `weekdays` prop was probably never meant to support this use case, **but** I guess fixing this bug would open up the possibility to create more powerful calendar views.

**Comment by ClickerMonkey** [comment]
Your weekdays prop should not have any duplicate weekdays. Max elements it should have is 7. 

It should start at a number between 0 and 6 and go up by at least one while wrapping around and not containing duplicates. 

CustomWeekly is not for displaying any number of days in a single row, it's for no more than a week. I'll have to ponder this use case to see what could be done.

**Comment by ngrie** [comment]
> CustomWeekly is not for displaying any number of days in a single row

Yeah, that was my assumption. As I mentioned I see use cases for this and thought maybe it's worth it to change the behaviour for that.

If not, maybe more precise documentation and/or validation for that prop would be helpful. What do you think?
