### ISSUE TITLE
[Bug Report] v-treeview 'open' property not updated for async child load

### ISSUE THREAD

**Issue by derat** [vuetifyjs/vuetify#10583]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.119
**OS:** Chromium OS 12607.81.0

### Steps to reproduce
1. Click the item named `async-0` to asynchronously load its children.
2. Look at the JS console.

### Expected Behavior
There should be a message indicating that `openIds` (bound to `open`) contains `async-0`.

### Actual Behavior
`openIds` is (usually?) not changed.

### Reproduction Link
<a href="https://codepen.io/derat/pen/PoqZBqd?editors=1011" target="_blank">https://codepen.io/derat/pen/PoqZBqd?editors=1011</a>

### Other comments
As I open successive async items, I see `openIds` get updated, but it appears to lag behind and not include the just-opened item. For example, after opening `async-1`, `openIds` contains just `async-0`.

If I open `sync-0` to trigger an update, `openIds` is updated to properly include all open async items.

**Comment by whoistobias** [comment]
I opened your Codepen using the same version of Chrome and was unable to reproduce this bug. I even tried CPU throttling and every time the console log was accurate.

**Comment by derat** [comment]
@whoistobias Thanks for giving it a shot! I don't see it every time, but it happens more often than not. I added a bit more logging. Here's what I see after clicking the `async-0` item when it's not working:

```
"openIds: "
"Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools"
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"
"Loading children for async-0"
"openIds: "
"Added async-1 as child of async-0"
```

After reloading and clicking `async-0` again, it worked and I saw this:

```
"openIds: "
"Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools"
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"
"Loading children for async-0"
"Added async-1 as child of async-0"
"openIds: async-0"
```

So when the bug occurs, it looks like the `open` property is getting updated before the promise returned by the `load-children` function has been resolved. When things are working correctly, the property is updated after the promise is resolved (as I'd expect).

**Comment by derat** [comment]
Thanks for trying. For what it's worth, I haven't touched the code where I was seeing this in a while, but I don't think I'm seeing the problem anymore now either. I'm using the same device but with Chrome 81.0.4044.141, and it looks like Vuetify 2.2.33 is being used now instead of 2.2.12.
