### ISSUE TITLE
[Bug Report] v-stepper doesn't render first step content if added dynamically

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#10586]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.100
**OS:** Windows 10

### Steps to reproduce
Create a stepper with no steps, add steps in mounted()

### Expected Behavior
Should display first step

### Actual Behavior
Doesn't display first step

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/QWbyeMd" target="_blank">https://codepen.io/jkarczm/pen/QWbyeMd</a>

**Comment by laurentDellaNegra** [comment]
Hi, Same issue here

**Comment by jacekkarczmarczyk** [comment]
Another workaround is to add `:key="!!items.length"` for `v-stepper`

**Comment by jacekkarczmarczyk** [comment]
Adding `this.updateView()` in `register()` seems to do the job
