### ISSUE TITLE
[Bug Report] Elevation does not work on dark mode

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#10584]
![Screen Shot 2020-02-14 at 2 06 55 PM](https://user-images.githubusercontent.com/8376035/74559877-5b2fb100-4f33-11ea-9eb6-452f88d66a60.png)
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add multiple cards on dark mode with elevations from 2 to 24. You will not see any visible difference in the elevation of those cards. However if you do the same on the light mode, then the elevation is working fine.
Per the material design specs from google:

https://material.io/design/color/dark-theme.html#properties

In a dark theme, components retain the same default elevation levels and shadows as components in lighter themes. However, in a dark theme, the surfaces of different elevation levels are illuminated differently.

Higher elevation, lighter surface
The higher a surface’s elevation (raising it closer to an implied light source), the lighter that surface becomes. That lightness is expressed through the application of a semi-transparent overlay using the On

### Expected Behavior
Elevation should be very visible on the dark mode

### Actual Behavior
Elevation is not visible on the dark mode

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/dyoGadp" target="_blank">https://codepen.io/mtermoul/pen/dyoGadp</a>

**Comment by johnleider** [comment]
The only way to do this is to add a psuedo selector to create the overlay. In dark mode, https://material.io/design/color/dark-theme.html#properties , elevation is depicted by a partial overlay. 

It would only work with elements that weren't using a competing psuedo selector. There is nothing we can do.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jacekkarczmarczyk** [comment]
Maybe there is no general solution but in some case it could be done in userland

https://codepen.io/jkarczm/pen/PoqpLrb

**Comment by ffxsam** [comment]
@jacekkarczmarczyk One correction to fix situations where you've got a sheet that has padding:

```css
.v-card[class*="elevation-"]:before {
  display: block;
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
}
```

Without `left` and `top`, I had this happen:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/12532733/107868843-44c17b80-6e4d-11eb-994a-3055b8dbf11b.png">
