### ISSUE TITLE
[Feature Request] Border colour prop for outlined v-cards

### ISSUE THREAD

**Issue by Ar4093** [vuetifyjs/vuetify#10581]
### Problem to solve
Right now, it is not easily possible to change the border color of a `v-card` with the `outlined` prop.

### Proposed solution
Add a prop like `border-color` (or whatever fits) to `v-card` that changes the colour of its border.

**Comment by Arjun3023** [comment]
Any updates on this thread?

**Comment by JasonLandbridge** [comment]
Yes please!

**Comment by byezy** [comment]
Yes this would be great

**Comment by WhiteBookmark** [comment]
@byezy 

Modifying CSS directly is a bit risky because we have no idea when Vuetify's team will change class names in future.

I use a workaround by placing everything inside alert:
```html
            <v-card>
              <v-alert outlined color="red darken-2">
                  <v-card-title>
                    Colored Card Border
                  </v-card-title>
                
                <v-card-text>
                  Colored text, you may change alert color  into any you'd like.
                 </v-card-text>
                </v-alert>
              </v-card>
```
[Codepen](https://codepen.io/rapper/pen/PoZZpyY)

**Comment by masus04** [comment]
Any update on this? The alert workaround does not work for me as it messes up the entire formating, nested inside v-rows and v-cols..

**Comment by hello-andrei** [comment]
I have a success with the following work around:

- There is no border built-in property
- Scoped CSS in component didn't work
- Finally, the inline STYLE binding worked, and the sample is below:

<v-card flat tile width="250" height="250" :style="styleObject">
...............................................................
..................................................................

data() {
    return {
      styleObject: { background: 'red', border: '3px solid green'}
    }
  },

**Comment by ffxsam** [comment]
Adding to @WhiteBookmark's workaround, which is great, I would add `class="pa-0"` to the alert, as it adds unnecessary padding when being used inside a card.

**Comment by jrmdel** [comment]
> 
> 
> Any update on this? The alert workaround does not work for me as it messes up the entire formating, nested inside a dialog, some v-rows and v-cols..
> 
> EDIT:
> Solved using v-sheet component which seems to not mess with the grid.
> ...
> 
> The padding pa- determines the size of the border.

Thanks! I also noticed that v-alert adds padding, and your v-sheet workaround is great. I used this piece of code to do the trick :
```html
<v-sheet outlined color="black" rounded>
    <v-card outlined color="red">
        <!-- For a red card surrounded by a black border -->
        <v-card-title ...>
        ....
    </v-card>
</v-sheet>
```
Hope this helps !

**Comment by magpiedigital** [comment]
My suggestion, instead of using a border-color prop, is just to accept string values as well as boolean for the border prop.
So if border="true" you get your standard border. If it's border="primary" you get a primary border.

Even better would be to also accept an object: border="{ color: primary, width: 2 }"

**Comment by Raja-Omer-Mustafa** [comment]
I appreciate the continuous improvements you bring to enhance user experience. waiting for this feature thanks

**Comment by Shujee** [comment]
Would love to see this for card as well as other components like sheet, button and chip.

**Comment by johnleider** [comment]
This is actually supported in Vuetify 3. However, border classes are only generated for theme colors:

https://play.vuetifyjs.com/#eNqFUstuFDEQ/JWKOeSyDyJyQstKCCFx4MiN5eCxe0NLfsVuj0BR/p2enSwM0Ua5uN12dbndVd8fTKtu+7GUzdjJvDc7oViCFdofErAb17aU01YTzyNcsK19OJho17couhzM0/UJ7Wz1GHL1VBVUKkdbfyP6g8FRWf9CFXx+CG+EJdAe36aA3XbRwWU4/VoSAV9zpQgurUf4HHJFY4GNJHA5NXJC0ius58KNHac7UGDZ4FOOMXteLcmqFc6J4Glg4Yb7rgs1QbD6L8KYQy+ioKG3K3y2953gemHPekiInPTP/zFagXbuSKNksXGFaO8Sz61SnAhGSmwjEk1JybVmBB5IQ6Xa45KtJ/+vCYpXixEtJ3c+miVZjHI3VGyX+bgeJJ3UuSzc/guFkCcmxV0gepHW/eSC0Va2SZRzkk1t8MobU9HZb1s13GxDvZh9+Mwdu+YqF0FTgecyjjo+wYMO7ohHHGuOuFZrX0+1M1px5nFl3m1uNzc35mnz1vz4AxC8+ZE=

I'm going to mark this as completed. If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
