### ISSUE TITLE
[Bug Report] V-treeview async child not reload after remove chidren

### ISSUE THREAD

**Issue by awenger63** [vuetifyjs/vuetify#10587]
### Environment
**Vuetify Version:** 2.1.18
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
On reproduction link, Add a remove child function like in https://codepen.io/anon/pen/OavdWd?editors=1011

this.$set(this.items[0].children, "length", this.items[0].children.length - 1);
or 
children.splice

then async load-children must rerun (cf documentation : the supplied function will be run if expanding an item that has a item-children property that is an empty array)

### Expected Behavior
The async load-children function must be rerun and it should be possible to update the children tree another time

### Actual Behavior
the load-children function it is not rerun second ore more time ...

### Reproduction Link
<a href="https://codepen.io/derat/pen/PoqZBqd?editors=1011" target="_blank">https://codepen.io/derat/pen/PoqZBqd?editors=1011</a>

### Other comments
related issues ? https://github.com/vuetifyjs/vuetify/issues/10175

Did someone know a workarround to update a property or re initialise data for rerun async function ? thanks per advance.

**Comment by awenger63** [comment]
My temporary workarround, on same place I remove children by code, I set the vnode hasLoaded to false. Than next click in this node rerun the load-children function and update it another time !
What do you mean ? Hope this can help for resolve this issue.

**Comment by dllsystem** [comment]
+1

**Comment by JackShepard98** [comment]
+1

**Comment by JackShepard98** [comment]
> My temporary workarround, on same place I remove children by code, I set the vnode hasLoaded to false. Than next click in this node rerun the load-children function and update it another time !
> What do you mean about this ? Hope this can help for resolve this issue.

This workaround works but for some reason it triggers the load-children method multiple times. Any ideea how to fix this?

**Comment by awenger63** [comment]
Perhaps a change in the Vuetify component version ? Take a look of the diff ?

**Comment by JackShepard98** [comment]
> Perhaps a change in the Vuetify component version ? Take a look of the diff ?

I have the latest vuetify version

**Comment by nurettinbas** [comment]
I want to update treeview children too. But ıt doesn't work once a time. If ı open node, push to children some object ıt doesnt work twice. I want some proper answer for that

> My temporary workarround, on same place I remove children by code, I set the vnode hasLoaded to false. Than next click in this node rerun the load-children function and update it another time !
> What do you mean about this ? Hope this can help for resolve this issue.

"I set the vnode hasLoaded to false." is that attribute? Because ı dont find in apı docs.

**Comment by wisp-x** [comment]
> > My temporary workarround, on same place I remove children by code, I set the vnode hasLoaded to false. Than next click in this node rerun the load-children function and update it another time !
> > What do you mean about this ? Hope this can help for resolve this issue.
> 
> "I set the vnode hasLoaded to false." is that props? Because ı dont find in apı docs.

Define ref for treeview component, and then in **load-children** function:
```js
getChildren(item) {
  // ...

  let children = [{id:1, name: "test"}];
  item.children.push(...children);
  let nodes = this.$refs.tree.nodes;
  for (const nodeKey in nodes) {
     if (nodes[nodeKey].vnode) {
        nodes[nodeKey].vnode.hasLoaded = false
    }
  }
  this.$refs.tree.updateVnodeState(item.id);

  // ...
},
```

It can be solved in this way for the time being. 🤦
