### ISSUE TITLE
[Bug Report] VCalendar @moved for month does emit falsy event payload

### ISSUE THREAD

**Issue by frague59** [vuetifyjs/vuetify#10599]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Linux x86_64

### Steps to reproduce
When clicking on Previous / Next, you can see the dates sent as payload of the @moved event handler in the console :  
+ Starting in feb. 2020, 1click on "Next" > Mar. 2020 (OK), 1 more click: stuck on Mar.2020 (KO).
+ Then click on Prev : Jan. 2020 (KO)
 

### Expected Behavior
Pass from month to month when clicking on Prev / Next buttons

### Actual Behavior
Weird things (Stepping 2 months, and after this stuck on a random month)

### Reproduction Link
<a href="https://codepen.io/frague59/pen/WNvwBEd?editors=1111" target="_blank">https://codepen.io/frague59/pen/WNvwBEd?editors=1111</a>

**Comment by nekosaur** [comment]
It looks like v-calendar requires you to use `v-model` for it to function properly. This is contrary to most of our other components that can be used without explicitly setting `v-model`.

Short-term solution would be to add `required: true` to value prop.

**Comment by ClickerMonkey** [comment]
You don't need to use v-model, you can also control what days are seen using start and end props. Those props are necessary for the custom* calendar types.

**Comment by nekosaur** [comment]
How would those fix this issue?
