### ISSUE TITLE
Picker scrollbar and jumping randomly through months

### ISSUE THREAD

**Issue by lobosan** [vuetifyjs/vuetify#1059]
Hi community, I'm having issues with the picker component on mobile devices. I'm testing the "Picker in dialog" from the [docs](https://vuetifyjs.com/components/pickers) using the galaxy S5 emulator of chrome devtools 59.0.3.

After selecting one date after another at some point it jumps to another month, also the width of the picker could be adjusted so the horizontal scrollbar at the bottom doesn't show up. 

Have a look at the following gif where shows the issue when I select July 31st then jumps to June 30

![picker](https://user-images.githubusercontent.com/314886/28379674-1caadfe8-6c7a-11e7-9b1b-24738583edb9.gif)

**Comment by nekosaur** [comment]
I'm having a hard time reproducing this. The only way it happens for me is when I accidentally do a swipe instead of a click. I think I will decrease the sensitivity of the  swipe so that you'll have to make a longer movement

**Comment by lobosan** [comment]
Hi Albert, I can confirm that the random jumping is fixed in vuetify 0.14.7

However I still see the horizontal scrollbar on mobile

**Comment by nekosaur** [comment]
That's a separate issue. Please create a new ticket.
