### ISSUE TITLE
v-text-input with initial value doesn't update label placement

### ISSUE THREAD

**Issue by dsbert** [vuetifyjs/vuetify#106]
I have a v-text-input with a v-model binding an an initial value of zero. The label doesn't properly move to the top of the text box until after I click inside.

This is on the latest version of Chrome.

```js
<v-text-input id="amount" 
  name="amount" 
  label="Amount" 
  v-model="amount">
</v-text-input>

data() {
    return {
      amount: this.transaction ? this.transaction.amount : 0,
  }
}
```

![2017-01-20 13_35_43-welcome to vuetify](https://cloud.githubusercontent.com/assets/1320090/22160800/38b8e24a-df15-11e6-96bc-c6a5f73d7108.png)

**Comment by johnleider** [comment]
Your 0 is being evaluated as a Number, and being type-cast as a Boolean within the conditional: [here](https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/TextInput.vue#L40).

If the value is given as a string [it works](http://codepen.io/johnjleider/pen/MJpLKE). I'll get this fixed up for the next release.
