### ISSUE TITLE
[Bug Report] Incorrect positioning for v-card-actions in v-dialog

### ISSUE THREAD

**Issue by joffff** [vuetifyjs/vuetify#10605]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 10

### Steps to reproduce
Create a v-btn element within v-card-actions in a v-card that's embedded in a v-dialog.

### Expected Behavior
v-card-actions should be positioned as far from the left as the v-card-title when used in a v-dialog.

### Actual Behavior
v-card-actions are positioned more to the left than the v-card-title when used in a v-dialog.

### Reproduction Link
<a href="https://codepen.io/joffff/pen/1c3b45bf93102229c3ddc558d88be971" target="_blank">https://codepen.io/joffff/pen/1c3b45bf93102229c3ddc558d88be971</a>

### Other comments
A similar bug for v-card-subtile was reported in #9468.

**Comment by joffff** [comment]
I'd be interested in resolving this myself as a first issue, if someone is available to walk me through the process?

**Comment by jblachly** [comment]
@joffff 
I ran in to this today and was able to fix it  within the scope of my component. It'd be great if you are able to fix it in Vuetify. I do not know Sass, how to compile it, nor how to test it, but I can tell you how I fixed it locally and likely how you could fix for Vuetify. Details below.

Custom CSS in your component will fix this:

```CSS
<style scoped>
.v-dialog > .v-card > .v-card__actions {
    padding: 8px 16px;
}
</style>
```

I am enough a Vue novice myself to not yet understand whether removing "scoped" will help fix this problem for your entire site / all components. Probably yes?

Anyway, if you can find where vuetify defines `.v-dialog > .v-card > .v-card__title` (and also `.v-card__text`), you can simply add the `.v-card__actions` and create a pull request.

*returning 5 minutes later*
 OK although I don't speak Sass it looks simple enough:
https://github.com/vuetifyjs/vuetify/blob/088a5093ea6396d1ff12e0d62143f89572c667d6/packages/vuetify/src/components/VDialog/VDialog.sass#L20-L31

Simply add the `.v-card__actions` with an appropriate Sass variable, then define the variable here:

https://github.com/vuetifyjs/vuetify/blob/088a5093ea6396d1ff12e0d62143f89572c667d6/packages/vuetify/src/components/VDialog/_variables.scss#L1-L12

I suggest `8px 16px`
