### ISSUE TITLE
[Bug Report] Tab focus from v-select returns to the first focusable element 

### ISSUE THREAD

**Issue by maxshuty** [vuetifyjs/vuetify#10609]
### Environment
**Vuetify Version:** 1.5.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Windows 10

### Steps to reproduce
Using macOS Safari 12.0.3, Edge, or IE11.

After focusing on v-select pressing the tab key does not focus to next focusable element.
Instead focus is set to the first focusable item on the page.

In Google Chrome the tab focus works normally.

### Expected Behavior
Tab focus should move to next focusable element from a `v-select` in Safari, Edge, and IE11

### Actual Behavior
Tab focus does not move to next focusable element from a `v-select` in Safari, Edge, and IE11

### Reproduction Link
<a href="https://codepen.io/anon/pen/RdwyQQ?editors=1010" target="_blank">https://codepen.io/anon/pen/RdwyQQ?editors=1010</a>

**Comment by maxshuty** [comment]
I have a PR incoming to fix this.

**Comment by jacekkarczmarczyk** [comment]
That was fixed for 2.0 in 5fa6a682634a0c159cf7c37897535bc2894131b9

**Comment by maxshuty** [comment]
> That was fixed for 2.0 in [5fa6a68](https://github.com/vuetifyjs/vuetify/commit/5fa6a682634a0c159cf7c37897535bc2894131b9)

Sorry I should have been more clear - I am putting up a PR for 1.5.x as John mentioned he didn’t have the time and my team is unable to upgrade to 2.0 at this time. I will have the PR up tomorrow morning.

**Comment by jacekkarczmarczyk** [comment]
That was clear enough, that's why i've added `lts` label
