### ISSUE TITLE
[Bug Report] V-Autocomplete does not work with asynchronous items

### ISSUE THREAD

**Issue by lassesteffen** [vuetifyjs/vuetify#10606]
### Environment
**Vuetify Version:** 2.2.13
**Last working version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Fill something in, check the console.

### Expected Behavior
It does not throw console errors

### Actual Behavior
It throws console errors and doesn't show any results

### Reproduction Link
<a href="https://codepen.io/ellazlo/pen/WNvxXzP?editable=true&editors=101" target="_blank">https://codepen.io/ellazlo/pen/WNvxXzP?editable=true&editors=101</a>

### Other comments
https://vuetifyjs.com/en/components/autocompletes#asynchronous-items

This is what can reproduce it

**Comment by MajesticPotatoe** [comment]
caused by 5d8d487

**Comment by KaelWD** [comment]
Really caused by #8823, 5d8d487 just fixed a bug where everything was being rendered anyway.

**Comment by MajesticPotatoe** [comment]
workaround: adding `eager` prop to the autocomplete
