### ISSUE TITLE
[Bug Report] 在使用pagination组建的过程中的问题

### ISSUE THREAD

**Issue by yanhe98** [vuetifyjs/vuetify#10607]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chromium 80.0.3987.87
**OS:** Ubuntu undefined

### Steps to reproduce
１．样式不能改变，特别是在宽度小的情况下几乎算是失效
２．prop里的length必须得绑定一个数字，一个真实的静态的数字，否则会报错
```shell
Vue warn]: Invalid prop: custom validator check failed for prop "length".
found in
---> <VPagination>
```
３．分页逻辑有错，不能够实现某一页进去某个项目之后，返回之后还在进入前的页面

### Expected Behavior
１．样式不能改变，特别是在宽度小的情况下几乎算是失效
２．prop里的length必须得绑定一个数字，一个真实的静态的数字，否则会报错
```shell
Vue warn]: Invalid prop: custom validator check failed for prop "length".
found in
---> <VPagination>
```
３．分页逻辑有错，不能够实现某一页进去某个项目之后，返回之后还在进入前的页面

### Actual Behavior
１．样式不能改变，特别是在宽度小的情况下几乎算是失效
２．prop里的length必须得绑定一个数字，一个真实的静态的数字，否则会报错
```shell
Vue warn]: Invalid prop: custom validator check failed for prop "length".
found in
---> <VPagination>
```
３．分页逻辑有错，不能够实现某一页进去某个项目之后，返回之后还在进入前的页面

### Reproduction Link
<a href="https://github.com" target="_blank">https://github.com</a>

**Comment by KaelWD** [comment]
- Please only use english
- The issue template has sections for a reason, you can't just paste the same thing into all of them
- You have not provided a reproduction of the issue
- Length has to be an integer
