### ISSUE TITLE
[Feature Request] v-navigation-drawer: please add an example with submenus

### ISSUE THREAD

**Issue by mariusa** [vuetifyjs/vuetify#10601]
### Problem to solve
Some apps need menus on 2 levels in navigation-drawer.

Please add an example with submenus at 
https://vuetifyjs.com/en/components/navigation-drawers

### Proposed solution
don't know if it's possible

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/components/lists#nested-lists ?

**Comment by mariusa** [comment]
Right, thanks :)

**Comment by benmccann** [comment]
That page no longer exists. I'm pasting the contents here for others who might come across this issue.

It said: "Using the v-list-group component you can create up to 2 levels in depth using the sub-group prop."

https://web.archive.org/web/20200810084029/https://vuetifyjs.com/en/components/lists/#nested-lists

**Comment by MajesticPotatoe** [comment]
> That section no longer exists

it does, its just was renamed according to its property https://vuetifyjs.com/en/components/lists/#sub-group
