### ISSUE TITLE
[Bug Report] Checkbox image bug when using Font Awesome4

### ISSUE THREAD

**Issue by feedback13** [vuetifyjs/vuetify#10602]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.5.17
**Browsers:** Chrome 80.0.3987.106
**OS:** Windows 7

### Steps to reproduce
Switch icon settings to Font Awesome 4(fa4), then use checkbox component in vuetify

### Expected Behavior
When checkbox is off, the square icon in Font Awesome 4 must be set

### Actual Behavior
When the checkbox is on, the check-square icon in FontAwesome 4 is set.
 However, the square icon is not set when it is off, so the image of the broken font is shown.

### Reproduction Link
<a href="https://codepen.io/feedback13/pen/ZEGOpZv?editable=true&editors=101" target="_blank">https://codepen.io/feedback13/pen/ZEGOpZv?editable=true&editors=101</a>

### Other comments
"CheckboxOff's value is "far fa-square" in the icons Object value corresponding to fa4 after checking the vuetify.js source in the vuetify module(version 2.2.12).
According to FontAwesome 4, the "fa fa-square" value seems to require modification.

**Comment by KaelWD** [comment]
:thinking: 75280f02cee75d0b1de67dd335856ad0e24f8f30
