### ISSUE TITLE
Scroll Bar on tabs for small devices not working.

### ISSUE THREAD

**Issue by waqasraz** [vuetifyjs/vuetify#1060]
### Versions
Vue 2.4.1, vuetify 0.14.2

### What is expected?
The scroll bar should stay on small devices as well.

### What is actually happening?
The scroll bar is disappearing on small devices.

### Reproduction Link
https://codepen.io/waqasraz/pen/EXzBeP?editors=1010

**Comment by nekosaur** [comment]
The left/right scroll buttons disappear on the mobile breakpoint (1024px). It is assumed that devices smaller than that are touch based and can scroll with touch instead. You can change the breakpoint for the tabs component by using the `mobile-breakpoint` prop.

**Comment by waqasraz** [comment]
Also, there is something wrong with the tab-bar, you can see in this image.
http://imgur.com/a/W5Mtj
