### ISSUE TITLE
[Bug Report] Left/Right icon inside a button is reversed when Rtl but it should not. there should be Start/End props

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#10619]
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Linux x86_64

### Steps to reproduce
Add an icon inside a button with left or right prop. then toggle the direction (rtl) of vuetify.

### Expected Behavior
Left/Right prop should be absolute. There should be Start/End prop too that respects the Rtl.

### Actual Behavior
Left/Right switch place when Rtl is toggled.

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/XWbKvvZ" target="_blank">https://codepen.io/yooneskh/pen/XWbKvvZ</a>

**Comment by jacekkarczmarczyk** [comment]
Similar to https://github.com/vuetifyjs/vuetify/issues/8461

**Comment by yooneskh** [comment]
> Similar to #8461

not exactly. Left icon does not stay left when it should.

**Comment by ibrahimBeladi** [comment]
I would recommend the start and end props. Makes code rtl/ltr agnostic.

**Comment by jacekkarczmarczyk** [comment]
> not exactly. Left icon does not stay left when it should

By "similar" I meant general issue with left/right/start/end support (both components misses start/end, button additionaly renders left/right in the wrong place when rtl)

**Comment by ibrahimBeladi** [comment]
The current css is something like this:
```
.v-application--is-ltr .v-btn__content .v-icon--left,
.v-application--is-rtl .v-btn__content .v-icon--right {
    margin-left: -4px;
    margin-right: 8px;
}

.v-application--is-ltr .v-btn__content .v-icon--right,
.v-application--is-rtl .v-btn__content .v-icon--left {
    margin-left: 8px;
    margin-right: -4px;
}
```
When it should be something like this:
```
.v-application--is-ltr .v-btn__content .v-icon--left,
.v-application--is-rtl .v-btn__content .v-icon--left {
    margin-left: -4px;
    margin-right: 8px;
}

.v-application--is-ltr .v-btn__content .v-icon--right,
.v-application--is-rtl .v-btn__content .v-icon--right {
    margin-left: 8px;
    margin-right: -4px;
}
```
And hence, I stand with using start/end, because left/right is confusing and wrong in rtl.
```
.v-application--is-ltr .v-btn__content .v-icon--start,
.v-application--is-rtl .v-btn__content .v-icon--end {
    margin-left: -4px;
    margin-right: 8px;
}

.v-application--is-ltr .v-btn__content .v-icon--end,
.v-application--is-rtl .v-btn__content .v-icon--start {
    margin-left: 8px;
    margin-right: -4px;
}
```
This can be non-breaking change addition for the time being.

**Comment by yooneskh** [comment]
i agree with this.

**Comment by KaelWD** [comment]
This isn't really a bug. The icon side is also swapped because it's just text, so the margin also has to be swapped or it'll look like this:
![image](https://user-images.githubusercontent.com/16421948/101460024-23479d80-398d-11eb-91d4-fc390f6e9892.png)

**Comment by ibrahimBeladi** [comment]
@KaelWD, can you provide a codepen about your comment?

**Comment by johnleider** [comment]
Talking with the team and we agree with Kael. This is working as intended. We may add start/finish logic in the future but nothing set in stone at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
