### ISSUE TITLE
[Bug Report] v-select should open at selected value

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#10618]
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
open dropdown with large set of items with the selected value

### Expected Behavior
the dropdown should open at the selected value

### Actual Behavior
the dropdown is not open at the selected value

### Reproduction Link
<a href="https://codepen.io/mahammad8564-the-animator/pen/MWweNxm?editable=true&editors=101" target="_blank">https://codepen.io/mahammad8564-the-animator/pen/MWweNxm?editable=true&editors=101</a>

**Comment by johnleider** [comment]
Missing the `menu-props="auto"` arg.

https://codepen.io/johnjleider/pen/PoqpyPd?editable=true&editors=101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
