### ISSUE TITLE
[Bug Report] VCarousel with auto height and fade transition breaks height

### ISSUE THREAD

**Issue by mandalornl** [vuetifyjs/vuetify#10613]
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Linux x86_64

### Steps to reproduce
1. Create `v-carousel` with `height` set to `auto`.
2. Add `v-carousel-item`'s with `(reverse-)transition` set to `fade-transition`.
3. Add some content e.g. with `v-responsive`.

### Expected Behavior
Fading element should not push down prev/next slide.

### Actual Behavior
Fading element is pushing down prev/next slide.

### Reproduction Link
<a href="https://jsfiddle.net/9x2skdpv/" target="_blank">https://jsfiddle.net/9x2skdpv/</a>

**Comment by johnleider** [comment]
This is not a limitation in v3 and it's recommended to have a height regardless.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
