### ISSUE TITLE
[Bug Report] Button wrapper missing for faSvg clickable v-icons

### ISSUE THREAD

**Issue by icleolion** [vuetifyjs/vuetify#10623]
### Environment
**Vuetify Version:** 2.2.13
**Last working version:** 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Use faSvg icons

### Expected Behavior
Icons to appear without being rendered like a native browser button
![image](https://user-images.githubusercontent.com/47498402/74859992-dc29e680-533f-11ea-9f25-c251846abf36.png)

### Actual Behavior
Icons are rendered as native browser button
![image](https://user-images.githubusercontent.com/47498402/74860020-e21fc780-533f-11ea-9c59-cdf477165bf5.png)

### Reproduction Link
This repro link is a blank template.  I received Kael's blessing in Discord to raise this issue without a codepen reproduction.  If someone has the time to create me a basic codepen with vuetify set up to use faSvg icons then that would be appreciated and I'll put a proper codepen up for this issue and any future faSvg related issues.
<a href="https://codepen.io/icleolion/pen/LYYwmgZ" target="_blank">https://codepen.io/icleolion/pen/LYYwmgZ</a>

### Other comments
faSvg icons are not wrapped with a button element, so are missing the css styles that remove the background-color and border-style.  This only presents itself in Chrome and Firefox, IE is fine.  This issue was introduced by this commit https://github.com/vuetifyjs/vuetify/commit/1596e55a885cb9c91e63bef5018f15c9f5a55ef2

This is what the DOM output is for me:
![image](https://user-images.githubusercontent.com/47498402/74860068-f2d03d80-533f-11ea-93bd-5240d3c5ce68.png)

This is what Kael was hoping I'd see:
![image](https://user-images.githubusercontent.com/47498402/74860088-f9f74b80-533f-11ea-982d-ea62c4484910.png)
![image](https://user-images.githubusercontent.com/47498402/74860098-fd8ad280-533f-11ea-8887-3ab4adc84ea5.png)

My workaround for the moment is to apply the following style:
`.v-icon--link {
	-webkit-appearance: none !important;
}`

**Comment by gplant** [comment]
I'am having the same issue when using fontawsome svg icons. 

Vuetify : 2.3.4
Firefox : 79.0b8

Hop a official fix will arrive soon.
