### ISSUE TITLE
[Documentation] Pre-made layouts codepen examples are missing Navigation drawer hamburger icons

### ISSUE THREAD

**Issue by tony-thomas-git** [vuetifyjs/vuetify#10628]
![Capture](https://user-images.githubusercontent.com/43186848/74885255-58b5c880-5332-11ea-9271-32efdc9bcbb1.PNG)
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Open codepen pre-made layout, see missing hamburger icon

### Expected Behavior
Hamburger icon should be visisible

### Actual Behavior
Hamburger icon missing

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/pre-made-layouts" target="_blank">https://vuetifyjs.com/en/getting-started/pre-made-layouts</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #8032
