### ISSUE TITLE
[Bug Report] v-navigation-drawer leaves a gap when v-footer has absolute position.

### ISSUE THREAD

**Issue by ToolScape** [vuetifyjs/vuetify#10621]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
`v-app` with a `v-navigation-drawer` and an `absolute` position `v-footer`. The `v-navigation-drawer` will leave a gap for the footer regardless if the footer is visibly in the viewport or not.

### Expected Behavior
`v-navigation-bar` leaves no gap between bottom of viewport if footer is not on screen.

### Actual Behavior
`v-navigation-bar` leaves a gap between bottom of viewport if footer is not on screen.

### Reproduction Link
<a href="https://codepen.io/vercaugi/pen/vYOXYNy" target="_blank">https://codepen.io/vercaugi/pen/vYOXYNy</a>

**Comment by johnleider** [comment]
When you apply the **app** property, it adds the height of the footer to the content padding. When you use the **absolute** property, it does not fix to the screen and moves to the container. In this scenario it is recommended to either drop **absolute** prop or use the **inset** prop.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Master-Y0da** [comment]
Having this issue to...drawer does not fit when you have footer with app prop...footer just overlap drawer and some of my drawer options are not visible
