### ISSUE TITLE
[Question] - 0.12 lifetime

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#1062]
With the recent releases of 0.13 and 0.14, how long is 0.12 gonna last in `npm`? Coz I noticed that there are so many breaking changes, it might take a while to migrate all my existing apps. Thanks. 0.14 is gorgeous by the way.

**Comment by nekosaur** [comment]
Previous versions will always be available on npm. Please direct any future questions to our [gitter](https://gitter.im/vuetifyjs)

**Comment by jofftiquez** [comment]
Got it, thanks @nekosaur
