### ISSUE TITLE
[Bug Report] Setting background color prop of VTabs as a vuetify theme color overrides color prop

### ISSUE THREAD

**Issue by Spekingur** [vuetifyjs/vuetify#10633]
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

### Steps to reproduce
1. Add v-tabs
2. Add two v-tab with text
3. Set color prop on v-tabs as any color
4. Set background color prop on v-tabs as any color
5. Set background color prop on v-tabs as 'primary'

### Expected Behavior
Color prop not overridden. Selecting a tab shows the color set with the color prop.

### Actual Behavior
Color prop is overridden. Rather than using the color prop it uses #FFF.

### Reproduction Link
<a href="https://codepen.io/spekingur/pen/YzXGYbd" target="_blank">https://codepen.io/spekingur/pen/YzXGYbd</a>

### Other comments
Other vuetify theme colors can be used - such as 'secondary', 'accent', etc.
Slider color prop is not overwritten.

This is what seems to be overriding the color prop.
```
.v-tabs-bar.primary .v-tab, .v-tabs-bar.primary .v-tabs-slider, .v-tabs-bar.secondary .v-tab, .v-tabs-bar.secondary .v-tabs-slider, .v-tabs-bar.accent .v-tab, .v-tabs-bar.accent .v-tabs-slider, .v-tabs-bar.success .v-tab, .v-tabs-bar.success .v-tabs-slider, .v-tabs-bar.error .v-tab, .v-tabs-bar.error .v-tabs-slider, .v-tabs-bar.warning .v-tab, .v-tabs-bar.warning .v-tabs-slider, .v-tabs-bar.info .v-tab, .v-tabs-bar.info .v-tabs-slider {
    color: #FFFFFF;
}
```

**Comment by KaelWD** [comment]
v3 no longer requires explicit color overrides for theme backgrounds, the appropriate text color is determined automatically.
