### ISSUE TITLE
[Bug Report] Unable to change primary theme color

### ISSUE THREAD

**Issue by ezeike** [vuetifyjs/vuetify#10637]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
Modify themes as per https://vuetifyjs.com/en/customization/theme

### Expected Behavior
Change primary color

### Actual Behavior
Primary color always blue

### Reproduction Link
<a href="https://codepen.io/ezeike/pen/KKpgJGy" target="_blank">https://codepen.io/ezeike/pen/KKpgJGy</a>

**Comment by MajesticPotatoe** [comment]
```js
theme: {
  themes: {
    light: {
      primary: '#11a6a6',
      success: '#b0bec5',
      accent: '#8c9eff',
      error: '#b71c1c',
    },
  },
}
```
