### ISSUE TITLE
[Bug Report] v-autocomplete menu error

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#10632]
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
Write some text to input.

### Expected Behavior
Open items menu

### Actual Behavior
Gives error

### Reproduction Link
<a href="https://codepen.io/navi3591/pen/abOmLXx?editable=true&editors=101" target="_blank">https://codepen.io/navi3591/pen/abOmLXx?editable=true&editors=101</a>

### Other comments
On v-menu component **this.dimensions.content** is null in **calculated** hook. This causes the error.

**Comment by KaelWD** [comment]
Duplicate of #10606
