### ISSUE TITLE
[Bug Report] v-select dense input bug

### ISSUE THREAD

**Issue by rsaleri** [vuetifyjs/vuetify#10635]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Linux x86_64

### Steps to reproduce
The codepen is ready to be seen, there are a select with selected value, an autocomplete with selected value and a select and an autocomplete without sleected value, just to show that the height is right until value is selected

### Expected Behavior
dense v-select keeps its height once value is selected

### Actual Behavior
dense v-select gets higher when a value is selected

### Reproduction Link
<a href="https://codepen.io/rsaleri/pen/rNVMvXG" target="_blank">https://codepen.io/rsaleri/pen/rNVMvXG</a>

### Other comments
I put autocomplete in the codepen just as a reference

**Comment by s13571** [comment]
Oh yes! this is needed

**Comment by amoliski** [comment]
Pull request with fix here: https://github.com/vuetifyjs/vuetify/pull/10682

**Comment by Teellcory** [comment]
They are both taller than dense text field at all times.

**Comment by fontzter** [comment]
As @Teellcory  mentioned there is still height issues with dense components compared to text-fields. Here is a codepen demonstrating the issue along with a hacky css work-around: https://codepen.io/fontzter/pen/QWbQmoZ

**Comment by s13571** [comment]
+1 Still an issue and quite important. Can this get higher priority?

**Comment by Teellcory** [comment]
@johnleider this is not fixed. @fontzter has an example using 2.x and it's still broken despite 2.2.18 supposedly fixing it.

**Comment by amoliski** [comment]
We might want to open a new issue- it's a different problem from the v-text-field issue.

Either way, I'll tackle the issue asap if nobody beats me to it.

**Comment by MajesticPotatoe** [comment]
Ah. Yeah. I can see that now. I'll close if you would like to open a fresh issue. Thanks.
