### ISSUE TITLE
[Bug Report] VAutocomplete & VCombobox Label Centering

### ISSUE THREAD

**Issue by darivs** [vuetifyjs/vuetify#10631]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chromium 80.0.3987.116
**OS:** Linux x86_64

### Steps to reproduce
- Use VAutocomplete or VCombobox
- Add `outlined` and `chips` properties
- Add label

https://codepen.io/darivs/pen/bGdwNNJ

### Expected Behavior
That the label centers vertically like here: https://codepen.io/darivs/pen/NWqRPGV

Obviously this is not the proposed solution because it also changes elements without `chips` property. It's just to show the expected behavior.

### Actual Behavior
The "centered" label is 6px to high

### Reproduction Link
<a href="https://codepen.io/darivs/pen/bGdwNNJ" target="_blank">https://codepen.io/darivs/pen/bGdwNNJ</a>

**Comment by johnleider** [comment]
This is the intended behavior of the **chips** prop. If you would like to maintain the same height, use the **small-chips** prop.

https://codepen.io/johnjleider/pen/QWbrxwR

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
