### ISSUE TITLE
[Question] - Roadmap to 1.0.0

### ISSUE THREAD

**Issue by julkuh** [vuetifyjs/vuetify#1063]
So many releases. Overwhelming how fast bugs are fixed and things are improved.
But are there any plans how long it will take (and what is still needed) to release a stable version 1.0.0?

thanks for the awesome progress so far!

**Comment by johnleider** [comment]
The last two things on my _you must do_ list are a la carte components and ```v-bottom-sheet```. After that we will be looking towards 1.0
