### ISSUE TITLE
[Documentation] Drag and Drop Ordering Example For Data Tables

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#10636]
### Problem to solve
There have been multiple requests for a first party solution for drag and drop support in data tables. After consideration, the team decided to not add that feature and has instead provided developers with an example of it working using SortableJS. However, the way to implement the oft requested feature is buried in the issue tracker.

### Proposed solution
Using the last comment in the original feature request https://github.com/vuetifyjs/vuetify/issues/2234 it should be possible to create an example for the datatable documentation page which shows stakeholders how to do drag and drop sorting. It would be a welcome addition to the docs.

**Comment by MentalGear** [comment]
I second that, native d&d reorder would be much appreciated.

**Comment by chrisruhl** [comment]
... a wonderful idea :)

**Comment by NathanWailes** [comment]
I just had to get a sortable data table working for a client. Here's the CodePen I got working: https://codepen.io/NathanWailes/pen/rNLajYO

It uses:
Vue 2.x
Vuetify 2.3.13
Sortable 1.10.2

**Comment by MatthewAry** [comment]
I used the example shown here https://github.com/vuetifyjs/vuetify/issues/2234#issuecomment-583792181 to create a directive to accomplish this. I made my own tweaks to it to eliminate typescript errors. Perhaps this can be added to the docs as a footnote, or even link back to this particular comment on the docs.


Drag and drop ordering is as simple as using a directive. For this code to work you will need to add sortablejs to your project as a dependency . This example is written in TypeScript.
```
// src/directives/SortableTable.ts
import { DirectiveOptions } from 'vue' // For TypeScript. Not needed in a pure JS project.
import Sortable from 'sortablejs'

//               V For TypeScript type checking. Not needed in a pure JS project.
const directive: DirectiveOptions = {
  bind(el, binding, vnode) {
    const options: Sortable.Options = {
      handle: '.sortHandle',
      animation: 150,
      onUpdate(event) {
        vnode.componentInstance?.$emit('sorted', event)
      }
    }
    Sortable.create(el.getElementsByTagName('tbody')[0], options)
  }
}
export default directive
export const SortableTable = directive
```

This directive is designed to work specifically with `VDataTable`s. Make sure you apply the `.sortHandle` class to the UI (like a `VIcon`) which you want the users to manipulate to perform the Drag and Drop ordering operations.

On the `VDataTable`s that you apply this directive to, make sure you add an event handler for a `sorted` event.
`<VDataTable ... @sorted="setOrder"></VDataTable>`
The event will return an object that looks like this interface https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2941fa22fc53b755b278b31d3f0ea21053f91dac/types/sortablejs/index.d.ts#L122-L175 (as of Nov 12 2020). The most important parts of the return object are the `oldIndex` and `newIndex` properties. This event will provide you with the information you need to apply the order changes to your data.

I recommend also applying this SCSS to the `.sortHandle` class as well since it will improve the user's experience when manipulating the drag handle.
```
.sortHandle {
  cursor: grab;
  &:active {
    cursor: grabbing;
  }
}
.sortable-chosen {
  cursor: grabbing;
}
```

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
