### ISSUE TITLE
[Documentation] Wrong Section ID of Translated Documentation

### ISSUE THREAD

**Issue by typestar-y** [vuetifyjs/vuetify#10634]
### Environment

**Browsers:** Chrome 80.0.3987.116
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Access the link page.
2. Click the link "使い方" (which means "usage") of the right drawer.

### Expected Behavior
Scroll to the section of "使い方(usage)"

### Actual Behavior
Console output as follows:

```
[Vue warn]: Error in v-on handler: "Error: Target element "#使い方" not found."

found in

---> <DocumentationToc> at src/layouts/documentation/Toc.vue
       <VApp>
         <LayoutsDocumentation> at src/layouts/documentation/Index.vue
           <LayoutsRoot> at src/layouts/root/Index.vue
             <App> at src/App.vue
               <Root>

vendors~app.e65fab1bc7be93b0b73d.js:1859 Error: Target element "#使い方" not found.
    at r (vendors~app.e65fab1bc7be93b0b73d.js:1739)
    at Object.u (vendors~app.e65fab1bc7be93b0b73d.js:1735)
    at o.s (app.8a1ce3f2fc25d634a45f.js:1)
    at click (2577.79ca2f23e5ee06a81330.js:1)
    at He (vendors~app.e65fab1bc7be93b0b73d.js:1859)
    at HTMLAnchorElement.n (vendors~app.e65fab1bc7be93b0b73d.js:1859)
    at HTMLAnchorElement.i._wrapper (vendors~app.e65fab1bc7be93b0b73d.js:1859)
```

and no scroll

### Reproduction Link
<a href="https://vuetifyjs.com/ja/components/cards" target="_blank">https://vuetifyjs.com/ja/components/cards</a>

### Other comments
The section id of the "使い方" section is not "使い方" but "usage", which is not translated but original English word.
And this bug is not only for this v-card page but also other documentation.

**Comment by nekosaur** [comment]
nice catch

**Comment by MajesticPotatoe** [comment]
seems that some headers are using en hrefs. happens across all languages. will dig into it.

**Comment by MajesticPotatoe** [comment]
This is resolved in the new docs.
