### ISSUE TITLE
[Bug Report] VTextarea auto-grow scroll bug (mobile)

### ISSUE THREAD

**Issue by Staf4** [vuetifyjs/vuetify#10644]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
When using self block with a scroll, on phones, when input text in VTextarea, the text jump to up.
This is visible in the video: https://www.youtube.com/watch?v=4MBE4_Sg0yk
Reason in file "\lib\components\VTextarea\VTextarea.js", method "calculateInputHeight", line:
	input.style.height = '0';

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/Staf4/pen/oNXYjVY" target="_blank">https://codepen.io/Staf4/pen/oNXYjVY</a>

**Comment by johnleider** [comment]
Please update this to include all the information required for a bug. Thank you.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by Staf4** [comment]
@johnleider  What information do you need? I attached the working code and video.
