### ISSUE TITLE
[Documentation] v-select attach property could use a better explanation

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#10645]
### Problem to solve
On v-select's documentation (and components that inherit off of it) the `attach` property is described as follows:
> Specifies which DOM element that this component should detach to.String can be any valid querySelector and Object can be any valid Node. This will attach to the root `v-app` component by default.

It shows that the type for this prop is `any` and that the default value is `false`. The problem is that this description is confusing. Awhile back I discovered problems with how v-select attaches itself if it's activator is in a scrollable area. https://github.com/vuetifyjs/vuetify/issues/5654 the ticket was closed with @jacekkarczmarczyk https://github.com/vuetifyjs/vuetify/issues/5654#issuecomment-439925366 showing that simply using the 'attach' prop should fix it.

If it weren't for him, I would still be confused as to how I should use the 'attach' prop. See, the description says that the prop *specifies* where the component should *detach* to, which is the antonym of the prop name. It was not clear that simply including the prop (which would give it a value of `true`) would actually *attach* the menu to the activator instead of `v-app`. All that was explained in this prop description was that it had to do with detachment, and that it accepts querySelectors, Objects, and valid Nodes.

### Proposed solution
Please revisit this property description with a more detailed explanation of what it does and how it can be used. If possible, please provide examples for how this prop can be used. It can be a described example in the prop description or a concrete one on the component page.

**Comment by MajesticPotatoe** [comment]
Could use a description update, I agree, its a generic description that's been around since 1.x. The `detach` is referring to the action of detatching from `v-app` to the specified node, but takes a little reading between the lines. I'm not sure about an example, as you wouldn't see anything different except in the DOM, and is something that can easily be clarified with a description.

**Comment by geoffreyyip** [comment]
Unsure if this is strictly correct but how about:
> Specifies which DOM element that this component should be the child of. Value can either be a Boolean or a valid CSS Selector String. Attaches to the `v-app` component by default. If given true, then this attaches to component's parent. If given a valid CSS Selector String, then attaches to the found Node.

I'd recommend an example for both `v-menu` at the very least. While `v-select`'s `attach` usage is trivial as shown by #5654,  `v-menu`'s `attach` usage is not. Intuitively, you'd expect the menu to "stick" to its activator. But in reality, it will attach to the nearest non-statically positioned ancestor, leading to unexpected results.

Here's a demo: https://codepen.io/geoffreyyip/pen/ydVpyy
