### ISSUE TITLE
v-dialog with fab in activator behaviour

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1064]
### Steps to reproduce

Click the fixed FAB button bottom right

### Versions
Vue 2.4
Vuetify 0.14.5

### What is expected ?
Dialog should open
FAB should not move

### What is actually happening ?
Dialog does not open first click
FAB moves to different position (it seems to get `position: relative`)
Click the FAB again, dialog opens

### Reproduction Link
https://codepen.io/anon/pen/pwXxKW

**Comment by nekosaur** [comment]
Fixed in dev with ab34eb7afa71950af199410b162fb8e4aa430fa4
