### ISSUE TITLE
[Bug Report] VGrid not exported by vuetify/lib

### ISSUE THREAD

**Issue by kxen42** [vuetifyjs/vuetify#10649]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.100
**OS:** Mac OS 10.15.2

### Steps to reproduce
Use this in any component.

```    
import {VGrid} from 'vuetify/lib'
    export default {
        components: {
            VGrid
        },
    }
```

Run
```
npm install
npx webpack --mode=development --verbose
```

### Expected Behavior
No warning about VGrid not being exported.

### Actual Behavior
```
WARNING in ./src/main/webapp/js/fast/vue/components/staff/common/schoolSelection.vue?vue&type=script&lang=js& (./node_modules/vuetify-loader/lib/loader.js??ref--8-0!./node_modules/vue-loader/lib??vue-loader-options!./src/main/webapp/js/fast/vue/components/staff/common/schoolSelection.vue?vue&type=script&lang=js&) 48:12-17
"export 'VGrid' was not found in 'vuetify/lib'
 ```

### Reproduction Link
<a href="https://codesandbox.io/s/quirky-jones-8vf4u" target="_blank">https://codesandbox.io/s/quirky-jones-8vf4u</a>

**Comment by KaelWD** [comment]
You have to import individual components.

```ts
import { VContainer, VRow, VCol } from 'vuetify/lib'
```
