### ISSUE TITLE
[Bug Report] .focus() on v-text-field does not work

### ISSUE THREAD

**Issue by folmert** [vuetifyjs/vuetify#10659]
### Environment
**Vuetify Version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
template:
```
<v-text-field
                                    ref="msisdnField"
                                    v-model="msisdn"
                                    label="Enter MSISDN"
                                    :rules="validationRules.msisdn"
 />
```

script:
```
    mounted () {
        this.$nextTick(() => this.$refs.msisdnField.focus()); // does not work, only sparks validation error
        this.$nextTick(() => this.$refs.msisdnField.$refs.input.focus()); // works
    },
```

There must be something wrong with onFocus function in VTextField.js
```
onFocus: function onFocus(e) {
      if (!this.$refs.input) return;

      if (document.activeElement !== this.$refs.input) {
        return this.$refs.input.focus();
      }

      if (!this.isFocused) {
        this.isFocused = true;
        e && this.$emit('focus', e);
      }
    },
```

### Expected Behavior
`this.$refs.msisdnField.focus()` should behave same way as `this.$refs.msisdnField.$refs.input.focus()` (should focus on the input field)

### Actual Behavior
`this.$refs.msisdnField.focus())` only sparks validation error

### Reproduction Link
<a href="https://codepen.io/overdriven/pen/MWwJjXY" target="_blank">https://codepen.io/overdriven/pen/MWwJjXY</a>

**Comment by jacekkarczmarczyk** [comment]
Please provide a valid reproduction, your is missing v-app, proper vuetify initialization, css, actual usage of `focus()` etc

**Comment by escapedcat** [comment]
@jacekkarczmarczyk maybe this helps:  
https://codepen.io/escapedcat/pen/qBEwBMY  
I didn't open this issue because I thought it might be solved with #8845 but wasn't.  

I tried using `autofocus` on the button but that only works once on inital page load. Dialogs are being opened all the time though and the button should be focused on each opening.

Let me know if you need more info or feedback.

**Comment by KaelWD** [comment]
If it's in a dialog you have to use `setTimeout`

**Comment by escapedcat** [comment]
@KaelWD had no idea, thanks a lot! In 1.5 `nextTick` worked fine.

**Comment by KaelWD** [comment]
I'll consider this issue resolved then.

**Comment by git-e-001** [comment]
If your version your version is (2.6.1) 

possibly this will help you

```
  <b-text
    ref="username"
  />
```

```
  mounted() {
    setTimeout(() => {
      this.$refs.username.$parent.$el['1'].focus();
    });
  },
```
