### ISSUE TITLE
[Bug Report] V-slot Item.action not working when using slot body

### ISSUE THREAD

**Issue by Jorgegomezb** [vuetifyjs/vuetify#10658]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.10
**Browsers:** Firefox 73.0
**OS:** Windows 10

### Steps to reproduce
Create a new data table, use the two slots mentioned in the title.

### Expected Behavior
Works as in the example on the docs

### Actual Behavior
Actions are not displaying in the table

### Reproduction Link
<a href="https://codepen.io/Jamon_Yorch/pen/WNvRGgB?editors=1010" target="_blank">https://codepen.io/Jamon_Yorch/pen/WNvRGgB?editors=1010</a>

### Other comments
This comes from the necessity to merge the "CRUD" table and the "Content editing" table examples of the documentation.
Don't really know if this is intended, or an actual bug.
Sorry if this is duplicated. I did not find any issue with this exact example.

**Comment by jacekkarczmarczyk** [comment]
When using `body` slot you are fully responsible for the body content, `item` and `item.<name>` slots are rendered in this case
