### ISSUE TITLE
[Bug Report] v-date-picker months all start on Sunday

### ISSUE THREAD

**Issue by stellR42** [vuetifyjs/vuetify#10664]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 7

### Steps to reproduce
Use v-date-picker component.

### Expected Behavior
Calendar in datepicker should display properly.

### Actual Behavior
The first of the month is always on Sunday, so the entire calendar is off.

### Reproduction Link
<a href="https://codesandbox.io/s/keen-kepler-4uvug" target="_blank">https://codesandbox.io/s/keen-kepler-4uvug</a>

**Comment by tpodom** [comment]
@stellR42 If I change your date to "2020-02-02" then it works.  I think the short year format is breaking it because it doesn't know what year 20 is.

**Comment by stellR42** [comment]
Thanks, that fixed it.
