### ISSUE TITLE
[Bug Report] [v-breadcrumb] "to" prop in v-breadcrumb-item cant be clicked

### ISSUE THREAD

**Issue by whbjzzwjxq** [vuetifyjs/vuetify#10667]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
use "to" prop for route in v-breadcrumb-item

### Expected Behavior
both of four item available

### Actual Behavior
items with "to" prop disabled and only items with "href" prop are available

### Reproduction Link
<a href="https://codepen.io/whbjzzwjxq/pen/LYVxMvj?editable=true&editors=101" target="_blank">https://codepen.io/whbjzzwjxq/pen/LYVxMvj?editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
You didn't install router
