### ISSUE TITLE
[Bug Report] v-select doesn't close after click outside

### ISSUE THREAD

**Issue by pavelkaps** [vuetifyjs/vuetify#10660]
### Environment
**Vuetify Version:** 1.5.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.13.6

### Steps to reproduce
Click on any v-select element, after click outside.

### Expected Behavior
v-select must be close

### Actual Behavior
v-select doesn't close

### Reproduction Link
<a href="https://codepen.io/kaps-pavel/pen/qBdRrwX?editors=1010" target="_blank">https://codepen.io/kaps-pavel/pen/qBdRrwX?editors=1010</a>

**Comment by tigerwill90** [comment]
Hi, I experienced the same problem and opened an issue too (closed now #10662).

The bug occur for me also from example in the official documentation: https://v15.vuetifyjs.com/en/components/selects#examples

**Comment by KaelWD** [comment]
ffs

#10620

**Comment by cb109** [comment]
Wow, I was working on a reproduction for a bug report just this morning and when I wanted to file the issue it did already show the new version with the exact fix needed :) Thanks @KaelWD ! Can confirm the problem is fixed
