### ISSUE TITLE
Transition components: no love from the docs?

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1066]
Is it possible that `<v-slide-y-transition>`and similar functional components aren't specifically documented?

Under Motion > Transitions you can only read about menu transitions using the prop. Meh... ok.

But once I dug around and found #273 and discovered you can use wrap existing transitions around anything that comes and goes.

I honestly hadn't bothered looking at the doc's sources because I'm on a tight schedule. But I think it should be highlighted and a couple examples on using them with cards would be pretty cool. After all, the docs use them for those sexy page changes.

**Comment by nekosaur** [comment]
Please open an issue on the docs repo instead. Thanks
