### ISSUE TITLE
[Bug Report] First v-radio is active by default when v-radio-group is mandatory without a value

### ISSUE THREAD

**Issue by jelle-eastground** [vuetifyjs/vuetify#10669]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows 10

### Steps to reproduce
See codepen

### Expected Behavior
The mandatory-prop should force a selection on a v-radio child, as the documentation states. But using a v-radio-group without a value, initially no v-radio option should be active by default.

### Actual Behavior
The first v-radio in the v-radio-group is active by default when the v-radio-group has no value and the mandatory-prop is true.

### Reproduction Link
<a href="https://codepen.io/eastground/pen/oNXBrzO" target="_blank">https://codepen.io/eastground/pen/oNXBrzO</a>

**Comment by amoliski** [comment]
Wouldn't that just be a non-mandatory radio button that you would validate on submit?

**Comment by jelle-eastground** [comment]
> 
> 
> Wouldn't that just be a non-mandatory radio button that you would validate on submit?

That's how I solved it for now, indeed. Reading the docs, I wasn't expecting the current behaviour of the mandatory-prop, but maybe it is just the documentation that could be improved. Probably everything should always be validated using the rules of the v-radio-group.

**Comment by frederikheld** [comment]
I just wanted to add that I stumbled upon the same inconsitency. IMHO @jelle-eastground is right about the expected behavior: if no value is given, no option should be selected and instead the user should be forced to make a choice.

**Comment by paddotk** [comment]
> Wouldn't that just be a non-mandatory radio button that you would validate on submit?

Yes, but having to build a custom validation for this seems pretty redundant. I too would expect the same behavior as any regular 'required' attribute on html inputs.
