### ISSUE TITLE
[Feature Request] Change spacer intervals back to Bootstrap style?

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#10675]
### Problem to solve
I find the Bootstrap spacer interval system to be more intuitive. E.g. I often use the .25rem, .5rem, 1rem intervals. They make sense in terms of relative spacing.

But I never use something like .75rem, 1.25rem 1.75rem because after 1rem, no one really notices .25rem intervals and I never use the in-betweens. So I find that the 4px intervals you guys are using now is actually less intuitive and not as useful as the Bootstrap spacing.

### Proposed solution
Use Bootstrap's interval spacing system of .25rem, .5rem, 1-3rem.

**Comment by johnleider** [comment]
According to spec this should go up to 64dp. We can achieve this with extending the padding/margin classes from 12 to 16. @KaelWD thoughts?
