### ISSUE TITLE
[Documentation] Properties without description

### ISSUE THREAD

**Issue by vanillamasonry** [vuetifyjs/vuetify#10679]
### Environment

**Browsers:** Firefox 73.0
**OS:** Windows 10

### Steps to reproduce
Go to
https://vuetifyjs.com/en/components/api-explorer 
and  select/search for example v-col - the result will show a table with properties including names, types and default values but without any description. 
This bug is preset on may other components including v-row, v-flex etc.
 

### Expected Behavior
Description

### Actual Behavior
No description

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/api-explorer" target="_blank">https://vuetifyjs.com/en/components/api-explorer</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #9207
