### ISSUE TITLE
[Bug Report] Icons not displayed in Chrome on Linux. 

### ISSUE THREAD

**Issue by telion2** [vuetifyjs/vuetify#10670]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Go to this page: https://vuetifyjs.com/en/
First discovered here: https://vuetifyjs.com/en/components/paginations#paginations
My guess is that this bug is caused by the Chrome for this linux OS, because Chromium behaves correctly. 

### Expected Behavior
All icons are properly displayed. 

### Actual Behavior
All icons are either gone or replaced with a rectangle. 

### Reproduction Link
<a href="https://codepen.io/telion2/pen/PoqWMoK" target="_blank">https://codepen.io/telion2/pen/PoqWMoK</a>

### Other comments
dont bother going to the codepen, bug is directly visible on the the official vuetify page.

**Comment by rsaleri** [comment]
Chrome 80.0.3987.116 on Ubuntu 18.04.4 LTS here.
All working correctly here

**Comment by KaelWD** [comment]
80.0.3987.106, Kubuntu 18.04.4 LTS
Same, works fine. 

@telion2 try in an incognito window, and check devtools to make sure everything is loading.

**Comment by KaelWD** [comment]
> `Request header field iv-user is not allowed`

You must have an extension or something messing with the requests.

**Comment by thetaung123** [comment]
I having the same issue with chrome on Ubuntu.

**Comment by jacekkarczmarczyk** [comment]
`iv-user` looks like 
http://publib.boulder.ibm.com/tividd/td/SW_30/GC32-0684-00/en_US/HTML/ws-admguide52.htm
https://www.ibm.com/support/knowledgecenter/SSPREK_7.0.0/com.ibm.isam.doc_80/ameb_webseal_guide/concept/con_ws_intro.html

Solution - don't use CDN

**Comment by thetaung123** [comment]
It's showing no error in developer's tools. The icons just appear or disappear at will. The icons appear on the other browsers of the same machine, though. Btw, I'm using vuetify npm package on Nuxt app.

**Comment by KaelWD** [comment]
@thetaung123 that's completely unrelated: #10797

This issue looks like a misconfigured proxy somewhere, we can't do anything about that.

**Comment by thetaung123** [comment]
I cleared the cache; They've reappeared.
