### ISSUE TITLE
[Bug Report] Floating action button in speed dial close on missed click

### ISSUE THREAD

**Issue by NoahStahl** [vuetifyjs/vuetify#10672]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Edge 82.0.425.3, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Click to open FAB speed dial
2. Click in between the buttons
3. Observe the menu closes

### Expected Behavior
Menu stays open to allow a second chance click

### Actual Behavior
Menu closes

### Reproduction Link
<a href="https://codepen.io/noahstahl/pen/rNVyVQz" target="_blank">https://codepen.io/noahstahl/pen/rNVyVQz</a>

### Other comments
Wondering if possible to keep open on near-miss clicks? Here's a GIF of the behavior, from the Vuetify docs site for speed dial:

https://imgur.com/a/e0UJFCJ

**Comment by stevelacey** [comment]
https://github.com/vuetifyjs/vuetify/issues/11096

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
