### ISSUE TITLE
[Bug Report] <v-icon> is not visible outside of the scroll view inside of a <v-avatar> in the <v-dialog> on iPad

### ISSUE THREAD

**Issue by Albertbol** [vuetifyjs/vuetify#10677]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
Use dialog, put avatars with the icon nested in a list that is longer than ipad scroll view height, scroll it and icons wont be visible, only icons that are visible on the starting scroll height will appear.

### Expected Behavior
All icons should be visible

### Actual Behavior
Icons are not visible

### Reproduction Link
<a href="https://codepen.io/albertb/pen/OJVWBxe" target="_blank">https://codepen.io/albertb/pen/OJVWBxe</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
