### ISSUE TITLE
[Feature Request] Allow setting origin of dialog's zoom animation to activator's location

### ISSUE THREAD

**Issue by lephuongbg** [vuetifyjs/vuetify#1068]
### What will it allow you to do that you can't do today?
It would be nice if there is a setting to make it that when a dialog appears, it will be perceived like it is originating from the activating button. Current implementation only allows animation from screen edge or screen center.

An implementation can be seen with Angular Material:
https://material.angularjs.org/latest/demo/dialog

This would help the dialog to align with Surface Creation spec:
https://material.io/guidelines/motion/choreography.html#choreography-creation

### How will it make current work-arounds straightforward?
Not sure if there is any work-around to do that.

### What potential bugs and edge cases does it help to avoid?
Just an improvement to UX IMHO.

**Comment by michaelmarconi** [comment]
+1

**Comment by amritk** [comment]
+1!

**Comment by zhanghuanchong** [comment]
+1
