### ISSUE TITLE
[Bug report] The Wrong Scrollable Elements

### ISSUE THREAD

**Issue by icle** [vuetifyjs/vuetify#10689]
### Problem to solve
Vuetify has some scrollable elements. But some are working weird.
For example, v-dialog(v-card) or v-select.
Those scrollbars are outside the rounded boxes.

### Proposed solution
The scrollbars should be inside the rounded boxes.
Don't give overflow property to outer elements.

**Comment by KaelWD** [comment]
This sounds like a bug report, please provide an example of this along with expected and actual behaviour.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
