### ISSUE TITLE
[Feature Request] Vuetify Select return-object provide a way to only return the object but use ids as value

### ISSUE THREAD

**Issue by Anubarak** [vuetifyjs/vuetify#10683]
### Problem to solve
Currently there is a prop for Vuetify select to return objects and that is great but I would like to have the possibility to only receive objects but work with the ids internally.

I provided a CodePen for it https://codepen.io/Anubarak/pen/poJPzPo?editable=true&editors=101

Let's say I have data in two different modules in  Vuex. I have "people" and I have "states" and I want to display those people and states in one single `v-select` component but I do not want to store those selected values in one single property in my local data but in two different one. 
This could be an array of possible items

```
      items: [
        { title: 'Florida', id: 'FL', type: 'country' },
        { title: 'Georgia', id: 'GA', type: 'country' },
        { title: 'Nebraska', id: 'NE', type: 'country' },
        { title: 'California', id: 'CA', type: 'country' },
        { title: 'New York', id: 'NY', type: 'country' },
        { title: 'Bruce', id: '1', type: 'person' },
        { title: 'Tom', id: '2', type: 'person' },
        { title: 'Jack', id: '3', type: 'person' },
      ],
```

And I would like to store the selected **ids** in two different local values
```
  data () {
    return {
      selectedCountries: [],
      selectedPeople: []
    }
  }
```
Because my endpoint stores those in two different properties in the DB, I just want to display them in one select.

The v-select component should now only **return** the array of selected objects as value but work with IDs internally so I do not need to fetch the correct object by ID from my different stores/items.

If I don't use the `return-object` I would have to search for the correct object in the array each time and check for the `type` to add it to the correct array (either `selectedCountries` or `selectedPeople`).
So I would like the `return-object` to only return objects but the `v-model` should be an array of strings/integers from those objects defined by `item-value`.

My current "work-around" now is to search for the correct object when I receive it.

### Proposed solution
Add an additional prop to define if it should accept objects as value or properties of those objects

**Comment by jacekkarczmarczyk** [comment]
>but the v-model should be an array of strings

>The v-select component should now only return the array of selected objects

Can you clarify?

**Comment by Anubarak** [comment]
> but the v-model should be an array of strings
The component's `value` attribute should be something like
```JS
[ 1, 3, 10, 99]
```

while the `items` prop is
```JS
[
    {id: 1, text: 'first'},
    {id: 2, text: 'second'},
    {id: 3, text: 'third'},
    {id: 10, text: 'another'},
    {id: 99, text: 'last'},
]
```

without `return-object` the returned value on change/input is
```JS
[1, 3, 99 .... X]
```
while it expects
```JS
[1, 3, 99 .... X]
```
as the `value` prop

With `return-object` it returns
```JS
[
    {id: 1, text: 'first'},
    {id: 3, text: 'third'},
    {id: 99, text: 'last'},
    // .... X
]
```
As expected for me, because I think `return` means objects are **returned** but it somehow does not work to pass the `value` `[1, 3, 99 .... X]` anymore... it now want's to have an array of objects as well.. I don't really see why that should be the case. 
Shouldn't the prop be named **use-objects** instead with the current behavior?
So I would like to have an additional prop that makes the component work with `[1, 3, 99 .... X]` internally and only return objects.

To show an example, I currently created a wrapper for all `v-select` components with `return-object` always set to false that uses this computed value as `v-model`
```JS
localValue: {
    get() {
        return this.value;
    },
    set(value) {
        let objects = [];
        if(this.returnObject === true){
            // I would like to return objects, not ids.. find the objects with the correct ids
            value.forEach(id => {
                let user = this.items.find(el => el[this.itemValue] === id);
                if(user){
                    objects.push(user);
                }
            });    
        }else{
            // do not return objects, just ids
            objects = value;
        }

        this.$emit('input', objects);
    }
},
```

**Comment by KaelWD** [comment]
You're already doing some custom stuff to split it into two arrays, you just need to handle the case where it's a string:
```
if (typeof el === 'string') {
  el = this.items.find(i => i.id === el)
}
```

**Comment by Anubarak** [comment]
But why should it be a string from the beginning when `return-object` is set to true? So I expect to receive objects and not strings?

**Comment by KaelWD** [comment]
Because you're passing in strings, it doesn't map existing values back to objects.
