### ISSUE TITLE
[Bug Report] <v-autocomplete> v-model reset doesn't clear the search input

### ISSUE THREAD

**Issue by cjthorley** [vuetifyjs/vuetify#10688]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Create an <v-autocomplete> with v-model bind to a local data variable
If you nullify the v-model  variable the <v-autocomplete> still retains the search text from the previous selection.

I am not sure if this is a bug or if there is a workaround for this.

### Expected Behavior
I would expect once you nullify the v-model (ie no selection) the <v-autocomplete> should not retain the search text.

### Actual Behavior
If you nullify the v-model  variable the <v-autocomplete> still retains the search text from the previous selection.

### Reproduction Link
<a href="https://codepen.io/cjthorley/pen/PoqmNEX?editors=1010" target="_blank">https://codepen.io/cjthorley/pen/PoqmNEX?editors=1010</a>

**Comment by arabsight** [comment]
yep, last release (2.2.15) introduced this.

**Comment by KaelWD** [comment]
#10642

**Comment by mseele** [comment]
imho it's even worse. When i enter a _INVALID_ value into the VAutocomplete and the VAutocomplete looses the focus, the _INVALID_ value remains...

**Comment by goraSi** [comment]
The same issue applies to v-combobox.

**Comment by slayerbleast** [comment]
Same issue? https://github.com/vuetifyjs/vuetify/issues/10765 and there is a workaround

**Comment by icleolion** [comment]
Can https://github.com/vuetifyjs/vuetify/pull/10642 be rolled back please until someone has time to fix this properly.  The bug that commit fixed seems to me like a lower priority than the bug it has now caused.  As it stands my project is now stuck on 2.2.14.

**Comment by johnleider** [comment]
Changes made in #10642 reverted with 02bdf28

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Shinigami92** [comment]
Thanks, that fixed my problem 🙂 
I was very confused 😄

**Comment by MrToxy** [comment]
I can confirm that as of version `2.3.17` this still happens when using the `multiple` prop.

Refer to https://codepen.io/MrToxy/pen/xxOeOqR

What happens:

1) On the v-complete using the multiple prop, partial search for an item
2) select the item and click outside the autocomplete
3) item gets selected but search input doesn't get reseted

**Comment by icleolion** [comment]
I’m not in a position to test but any chance 2.4.0.beta fixes this?

I’m curious if the change (https://github.com/vuetifyjs/vuetify/pull/12373) to clear/reset all inputs to null instead of undefined will coincidentally fix this issue.
