### ISSUE TITLE
[Bug Report] Image in v-card-title gets reloaded when `loading` is toggled for the v-card

### ISSUE THREAD

**Issue by kohenkatz** [vuetifyjs/vuetify#10695]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.17
**OS:** Windows 10

### Steps to reproduce
1. Toggle the "Loading" switch on and off several times.
2. Observe the logo image to see whether it flashes or not.
3. Open the browser DevTools, go to the Network tab, and check "Disable Cache"
4. Repeat steps 1 and 2 several times.

### Expected Behavior
Because the image is unchanged, there is no reason to re-draw it and therefore no reason to reload it from the server even though it isn't in the cache.

### Actual Behavior
The image is redrawn every time the loading bar is toggled, causing it to briefly disappear if it isn't cached in the browser.

### Reproduction Link
<a href="https://jsfiddle.net/kohenkatz/fuxqh4zb/" target="_blank">https://jsfiddle.net/kohenkatz/fuxqh4zb/</a>

### Other comments
A similar image placed in the `v-card-text` area does not have this problem, as shown in the example.

**Comment by kohenkatz** [comment]
Playing around more, I created a variation that shows this also works properly in the `v-card-subtitle` section: https://jsfiddle.net/kohenkatz/fuxqh4zb/3/

Looking at the Chrome DevTools while toggling the switch, I see something interesting:

- When the switch is off, there are three `div` tags with classes `v-card__title`, `v-card__subtitle`, and `v-card__text`.
- When I toggle the switch on, I see that the `__subtitle` and `__text` elements are not changed at all, which is what I expect. However, instead of adding a new `v-card__progress` element at the top, what is happening is that the `__title` element ***is changed into** the `__progress` element and a new `v-card__title` element is created below it.
- When the switch is toggled off again, the `__title` element is deleted and the `__progress` element is transformed back into the `__title` element.

This seems to be what is causing the image to be reloaded. Now the question is just *why*...

**Comment by KaelWD** [comment]
> the __title element is deleted and the __progress element is transformed back into the __title element

Thanks for investigating, this was [reported in discord](https://discordapp.com/channels/340160225338195969/340215499398840331/667608035254075402) a while ago and we assumed it was just a vue bug. 

> and check "Disable Cache"

#9153, it isn't intended to work without cache enabled.

**Comment by KaelWD** [comment]
Playground:
```vue
<template>
  <v-container>
    <v-card :loading="loading">
      <v-card-text>
        <v-switch v-model="loading" label="Loading"></v-switch>
        <children></children>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script>
  export default {
    components: {
      children: {
        template: '<div>Card children</div>',
        mounted () {
          console.log('mounted')
        }
      }
    },
    data: () => ({
      loading: false
    })
  }
</script>
```

**Comment by kohenkatz** [comment]
Thanks @KaelWD!
