### ISSUE TITLE
Feature Request: select allow create item

### ISSUE THREAD

**Issue by fourcels** [vuetifyjs/vuetify#1069]
- What will it allow you to do that you can't do today?
    select allow creating items from autocomplete
    e.g.  https://sagalbot.github.io/vue-select/  
    ![peek 2017-07-20 13-48](https://user-images.githubusercontent.com/1042568/28402393-3cbdbf34-6d52-11e7-9b6a-2ff4e471614b.gif)

  - How will it make current work-arounds straightforward?
    select add `allowCreate` props for enable/disable creating item from searchInput.

**Comment by tobiasbeuving** [comment]
vue-select is not a part of vuetify, post your message here: https://github.com/sagalbot/vue-select

**Comment by johnleider** [comment]
I think he's asking for similar functionality.

**Comment by johnleider** [comment]
This was added in 0.15 release.

**Comment by rgalaxy** [comment]
Sorry but how can i implement this on vuetify autocomplete ?

**Comment by rudolph2907** [comment]
@rgalaxy Look the combobox can now do this functionality:
https://vuetifyjs.com/en/components/combobox
