### ISSUE TITLE
[Documentation] Missing info that v-icon generates a button element when click handler is set - breaks SSR

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#10702]
### Environment

**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Open the link to the documentation or see the example from the documentation on CodePen: https://codepen.io/pen/?&editable=true&editors=101
2. See the "Clickable" example
3. Inspect the icon with the arrow to the right (with right-click, inspect element)
4. See that the icon is `<button type="button" class="v-icon...`

### Expected Behavior
I expect the documentation to tell me about the fact that the `v-icon` component generates a button element if a click handler is set.

### Actual Behavior
I used something like this in my code:
```vue
<template>
  <v-btn icon>
    <v-icon @click="exmapleMethod">mdi-help</v-icon>
  </v-btn>
</template>
```
and it generated this: (superfluous classes and attributes omitted)
```html
<button
    type="button"
    class="v-btn..."
  >
    <span class="v-btn__content">
      <button
        type="button"
        class="v-icon..."
      ></button>
    </span>
  </button>
```

The problem is that this is not what is being generated on the server when I do SSR. (or at least the browser complains about it being wrong HTML) This causes a hydration bailout error every time I load this page with SSR. I fixed this issue by moving the click handler to the button. However, it should be mentioned on the docs that `v-icon` does this since it's not necessarily common knowledge that you can't nest `<button>` elements.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/icons#clickable" target="_blank">https://vuetifyjs.com/en/components/icons#clickable</a>

### Other comments
It appears this behavior was introduced with Vuetify 2.2

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
