### ISSUE TITLE
Required Selects don't go into errorstate

### ISSUE THREAD

**Issue by napalmduo** [vuetifyjs/vuetify#1070]
### Steps to reproduce
Focus select and blur without selecting an item

### Versions
0.14.5

### What is expected ?
v-select should have hasError true and get the proper error css-classes

### What is actually happening ?
hasError is false and no error css-classes are applied

### Reproduction Link
https://codepen.io/napalmduo/details/BZgJVe/

**Comment by johnleider** [comment]
Fixed but leaving open until I finish the test.

**Comment by KaelWD** [comment]
`required` no longer triggers validation, it's only used for accessibility. Please don't comment on old closed issues, either open a new one or ask on discord, reddit, or stackoverflow if you aren't sure.
