### ISSUE TITLE
[Bug Report] v-radio-group custom attributes are removed

### ISSUE THREAD

**Issue by vanillamasonry** [vuetifyjs/vuetify#10704]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Windows 10

### Steps to reproduce
Check https://codepen.io/Paul_1001/pen/poJPXdR
and click inspect on popup menu, inspect the generated HTML/DOM and you will see that 
-> v-radio-group the demo="test" is not present.
-> v-radio  the demo1="test1" is available.

### Expected Behavior
All custom attributes must be available.

### Actual Behavior
All custom attributes are removed.

### Reproduction Link
<a href="https://codepen.io/Paul_1001/pen/poJPXdR" target="_blank">https://codepen.io/Paul_1001/pen/poJPXdR</a>

**Comment by YipingRuan** [comment]
@MajesticPotatoe  Should attribute from v-radio-group added to rendered div html?

**Comment by vanillamasonry** [comment]
Yes.
In fact all components  should preserve attributes and render them into  HTML tags. 
In many applications is vital to assign custom id's and/or other attributes to the components.

This is not the only case. I have reported the same bug for V-banner see: https://github.com/vuetifyjs/vuetify/issues/9837 John agreed , change the component behavior an closed this  Dec 4, 2019

Thanks,
Paul

**Comment by himito** [comment]
I agree with @vanillamasonry. 

In my case, I tried to add the prop `data-test` for testing, but it is removed :(

Thanks,
Jaime
