### ISSUE TITLE
[Bug Report] v-form not preventing submit when scripts are not loaded

### ISSUE THREAD

**Issue by sneko** [vuetifyjs/vuetify#10703]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
It's related to the loading time... Cannot put that in the codepen.

### Expected Behavior
That my <v-form> cannot be submitted.

### Actual Behavior
On a slow connection, let's say it takes 20 seconds to load every Vue scripts...
If in the meantime the user fills the form and submit it, it will by default submit the raw HTML form, it means the page reload with all inputs as query parameters.

### Reproduction Link
<a href="https://codepen.io/sneko7/pen/MWwmMKb" target="_blank">https://codepen.io/sneko7/pen/MWwmMKb</a>

### Other comments
That's before Vue loading so do you have an advice to prevent that?

Thank you,

**Comment by jacekkarczmarczyk** [comment]
> Cannot put that in the codepen.

You can, simulate slowy loading scripts by not adding them at all

**Comment by sneko** [comment]
@jacekkarczmarczyk if I remove them, the `v-form` will not get transformed into a native `form` in codepen, right?

**Comment by jacekkarczmarczyk** [comment]
If they are loaded after 20 seconds v-form is also not transformed to native form before that time, so I don't know what problem are you facing.
Please add comment when you have a working minimal reproduction and we'll reopen the issue if it appears to be the bug in Vuetify
