### ISSUE TITLE
[Bug Report] Navigation drawer with bottom not opened on swipe from bottom

### ISSUE THREAD

**Issue by rotsee** [vuetifyjs/vuetify#10713]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Linux x86_64

### Steps to reproduce
Add a navigation drawer like this:

`<v-navigation-drawer v-model="drawer"' bottom>`

### Expected Behavior
On mobile, the navigation drawer should appear when swiping from the bottom of the screen.

### Actual Behavior
Navigation drawer appears (from the bottom) when swiping from the left (or right, if `right`is used).

### Reproduction Link
<a href="https://codepen.io/rotsee/pen/ExjXXOL" target="_blank">https://codepen.io/rotsee/pen/ExjXXOL</a>

**Comment by rotsee** [comment]
I edited the bug report as this seems to apply regardless of whether left or right is used for the drawer.

**Comment by johnleider** [comment]
Looks like I never hooked up touch to this variable of the drawer.

**Comment by KaelWD** [comment]
Fixed by #14468
