### ISSUE TITLE
[Bug Report] v-data-table pagination event fired twice...

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#10715]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
Below is the steps on how I made the reproduction link - https://codepen.io/ais-one/pen/OJVgxWZ

1.Go to documentation (Vuetify version 2.2.15):

https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side

2. Open the codepen

3. add event to <v-data-table>:

@pagination="doPage"

4. add method:

doPage () { console.log('Paged', Date.now()) },

5. run and see on console.log... the pagination event is firing twice.

### Expected Behavior
pagination event should only fire once

### Actual Behavior
pagination event fired twice

### Reproduction Link
<a href="https://codepen.io/ais-one/pen/OJVgxWZ" target="_blank">https://codepen.io/ais-one/pen/OJVgxWZ</a>

### Other comments
Refer to issue below also...

https://github.com/vuetifyjs/vuetify/issues/10212#issuecomment-591825368

**Comment by rizypb** [comment]
It's still happening on version 2.4.0. For now I am not calling the `pagination` method on page load. It solved the problem but if anyone has any better solution / suggestion, please do share.

**Comment by mihalw28** [comment]
Still happening on version 2.6.10.
