### ISSUE TITLE
[Bug Report] VtextField marks as required in IE when placeholder text is given in language other than english

### ISSUE THREAD

**Issue by shravaniparsi26** [vuetifyjs/vuetify#10719]
### Environment
**Vuetify Version:** 1.5.8
**Vue Version:** 2.6.7
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Create a VtextField
2. Give place holder in any language other than English (Arabic/Spanish)
example text:  "¿Qué hace el padre de Pedro en el parque?" / "لى سبيل المثال"
3. give as required 
4. see the error, the field is marked as required as soon as the page loads

### Expected Behavior
shouldn't mark the field as required as soon as the page loads

### Actual Behavior
 the field is being marked as required as soon as the page loads
when given placeholder in a language other than English and field is required

### Reproduction Link
<a href="https://codepen.io/shravanip/pen/rNVwqXL" target="_blank">https://codepen.io/shravanip/pen/rNVwqXL</a>

### Other comments
https://imgur.com/Jkrm1HA

**Comment by KaelWD** [comment]
- IE doesn't support [badInput](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/badInput)
 - IE fires input events for no reason: https://stackoverflow.com/a/57607005/2074736

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
