### ISSUE TITLE
[Feature Request] v-file-input give a way to get event instead of file in @change event

### ISSUE THREAD

**Issue by AntoninBeaufort** [vuetifyjs/vuetify#10725]
### Problem to solve
If we render a dynamic list of file input that depends on a v-select, we can't know which file input triggered the event, make it useless to use a v-file-input in a v-for... :/

### Proposed solution
Instead of return a file on @change it will be usefull to get the full event to access to event.target in order to class the return of upload in an array or object.

**Comment by KaelWD** [comment]
You can pass extra arguments to the event handler: https://vuejs.org/v2/guide/events.html#Methods-in-Inline-Handlers

**Comment by AntoninBeaufort** [comment]
Oh thank you, i'm new to vueJS, my bad sorry !

**Comment by terrymun** [comment]
@KaelWD I don't think that's actually possible: forking from a CodePen from the Vuetify docs, the `@change` event only allows access to the value from the input component. It's also documented as such: https://vuetifyjs.com/en/components/inputs/#api

Example: https://codepen.io/terrymun/pen/oNjxYVy?editors=1111

**Comment by KaelWD** [comment]
That's right, but you can do `onChange('something', $event)` to tell which input it came from.

**Comment by terrymun** [comment]
@KaelWD I don't think so: doing `onChange('something', $event)` in the template and attempts to access it in the method will only result in `'something'` and `value` being passed in.

One can also simply log `arguments` in the callback: you will see that you never have access to the original `Event` object at the first place.

**Comment by MeonisRP** [comment]
If you pass $event as an argument, it actually works. I had a problem passing extra arguments to `@change`, and it actually worked. So the final result is:

`<v-file-input @change="purchaseUpload(purchase.id, $event)"></v-file-input>`
`purchaseUpload(id, event) { console.log(event) }`

This returns 2 valid arguments, including the file itself
