### ISSUE TITLE
[Documentation] The action of the button on the Roadmap page is incorrect

### ISSUE THREAD

**Issue by paichi81** [vuetifyjs/vuetify#10729]
### Environment

**Browsers:** Chrome 80.0.3987.122, Safari
**OS:** Windows 10, Mac OSX, Linux, iOS, Windows, Android

### Steps to reproduce
In Japanese page, 
1. Click the button "未定" next to "VuetifySnippet" at the top of the timeline
2. Card does not Expand
3. Click the button "2020Q3" on the fourth card(v3.0release) from the top
4. Top other card Expand

### Expected Behavior
When the button on the card is clicked, each card expands

### Actual Behavior
The opening is different.

### Reproduction Link
<a href="https://vuetifyjs.com/ja/introduction/roadmap/" target="_blank">https://vuetifyjs.com/ja/introduction/roadmap/</a>

### Other comments
In other languages, the behavior is strange.
fr-FR: no display timeline. (but Crowdin status 54%, roadmap.json)
zh-Hans: no display timeline. (but Crowdin status 56%, roadmap.json)
ko, sv-SE, ar-SA, vi-VN, tr-TR, ru, nl-NL, km-KH : display English (looks good)
it-IT, pt-BR: display placeholder??

**Comment by YipingRuan** [comment]
Switching to French give an Error
![image](https://user-images.githubusercontent.com/5492274/77089183-787b0200-6a40-11ea-8831-42102766337e.png)

**Comment by paichi81** [comment]
Some json files seem to be corrupted.
PR for the 3 files found.
