### ISSUE TITLE
[Bug Report] When you expand a VDataTable line, its content does not take all available space

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#10727]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.14.6

### Steps to reproduce
With a long sentence you can see that when the row is expanded, the first column is also expanded to the right

### Expected Behavior
It is expected that when the row expands it will take 100% of the available space

### Actual Behavior
He is not currently taking all that space he should take

### Reproduction Link
<a href="https://codepen.io/frbuceta/pen/bGdrgbz" target="_blank">https://codepen.io/frbuceta/pen/bGdrgbz</a>

**Comment by jacekkarczmarczyk** [comment]
You need a `<td>` with proper `colspan`, see https://vuetifyjs.com/en/components/data-tables#expandable-rows
