### ISSUE TITLE
[Bug Report] v-data-table sorting on mobile

### ISSUE THREAD

**Issue by corydemille** [vuetifyjs/vuetify#10735]
### Problem to solve
When viewing datatable on a mobile device, the v-select for the column sort opens and you can select choices; however, to close the choices, you have to click off the element. With clickable rows configured, if the user clicks off the element to close the sort v-select it will capture the click:row event or any other link and execute that action instead of just close the sort v-select box.

### Proposed solution
Add an overlay to the sort choices dialog box on mobile, so when the user selects anywhere off the screen it closes the choices dialog, but doesn't create a click event on items on the page.

**Comment by MajesticPotatoe** [comment]
This would actually better be solved by setting menu-props on the v-select.
The default for the select is `"closeOnClick": false`, `"closeOnContentClick": false` which is what causes this behavior. Not sure though if this would be considered breaking (feels more like a bug/oversight).

current workaround would be to use a custom header.

Thoughts @nekosaur

**Comment by nekosaur** [comment]
Yes I think I agree that it should default to close on click
