### ISSUE TITLE
[Feature Request] Not to add items to v-combobox if it has errors

### ISSUE THREAD

**Issue by rbeysembaev** [vuetifyjs/vuetify#10734]
### Problem to solve
If a combobox has failed `rules`, the error messages are shown, but it's still possible to add the item, although it's invalid.
Also, the combobox doesn't allow duplicate entries silently. The user enters a duplicate value, hits Enter and it just dissapears - bad UX. It could be fixed with a rule showing an error for duplicates, but as rules are naturally stored in the component `data`, they don't have access to the component instance (if `data` is a function). That forces the developer to use workarounds

### Proposed solution
Option 1: Replace (or augment) the `rules` prop with a `validate` method, that would accept the entered string as the argument and return either true on successful validation or a list of errors if any. In the latter case the item should not be added.
Option 2: Add an `add-with-errors` prop that would control if new items can be added while the combobox is in the error state.

**Comment by KaelWD** [comment]
> The user enters a duplicate value, hits Enter and it just dissapears

#16100

> error messages are shown, but it's still possible to add the item

validation doesn't run until the item is added
