### ISSUE TITLE
[Documentation] Quick start - Usage with vuepress

### ISSUE THREAD

**Issue by BaroDevelopment** [vuetifyjs/vuetify#10738]
### Problem to solve
It is actually possible to use vuetify with vuepress.

### Proposed solution
This project demonstrates the usage:
https://github.com/arab-open-source/vuepress-theme-vuetify

**Comment by avimehenwal** [comment]
![Screenshot from 2020-08-03 04-33-40](https://user-images.githubusercontent.com/3624059/89140691-a02bbc00-d542-11ea-944a-b23af5ef6267.png)
