### ISSUE TITLE
[Bug Report] Custom value-comparator function is removing both values when duplicated

### ISSUE THREAD

**Issue by DanielDwyer** [vuetifyjs/vuetify#10736]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.14.6

### Steps to reproduce
To reproduce, simply add a duplicated value to the v-combobox field, i.e. in the provided Code Pen example that would be adding skill 2 a second time. 

### Expected Behavior
I expected the value-comparator to allow one of the duplicates to remain while preventing the other from being added to the model.

### Actual Behavior
Both of the duplicated values are removed from the model.

### Reproduction Link
<a href="https://codepen.io/DanielPatrickDwyer/pen/poJrLOb" target="_blank">https://codepen.io/DanielPatrickDwyer/pen/poJrLOb</a>

**Comment by johnleider** [comment]
This is the expected behavior. Also, please keep reproductions to a minimum, thank you!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by woodgates** [comment]
@johnleider Hi John. When entering a duplicated value the component will generate two inputs events:
- one with no one of the duplicated values
- one with one duplicated value as it should.

For example if my entered tags are: [dog, cat, mouse] and I enter 'dog' again the component will emit change and input two times:
- one with [cat, mouse]  
- the second with [cat, mouse, dog]

The first one should not happen.
