### ISSUE TITLE
[Bug Report] Nested v-row/v-col causes gutter to be widened between rows

### ISSUE THREAD

**Issue by chouhanyang** [vuetifyjs/vuetify#10747]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
Replace old v-layout/v-flex with v-row/v-col.

### Expected Behavior
The gutter between rows should remain the same with or without nested row/col groups.

### Actual Behavior
The gutter between rows grows wider.

### Reproduction Link
<a href="https://codepen.io/chouhanyang/pen/YzXxBWW?editors=1010" target="_blank">https://codepen.io/chouhanyang/pen/YzXxBWW?editors=1010</a>
Please noted that the gutters between nested rows are wider.

### Other comments
In old v-layout, the top and margins are subtracted for v-flex.
This is similar to left and right margin. However, this behavior
is not kept when migrating to v-row and v-col.

I have a fix already:

https://github.com/SavantOne/vuetify/commit/f565ba00b9cbe319bda49f0024b261e83795735d

If you think this is a regression, I can send a pull request for my change. Thanks!

**Comment by johnleider** [comment]
The new grid system is based off of bootstrap's and the old grid system is still available in v2.

This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
