### ISSUE TITLE
[Feature Request] save state in data table

### ISSUE THREAD

**Issue by monumall91** [vuetifyjs/vuetify#10742]
### Problem to solve
Is there any option in data table to save the state of a table (its paging position, ordering state etc) so that is can be restored when the user reloads a page, or comes back to the page after visiting a sub-page.

### Proposed solution
save state in data table

**Comment by jaxn** [comment]
Use `keep-alive`?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
