### ISSUE TITLE
[Bug Report] Radio and checkbox inputs are not clickable

### ISSUE THREAD

**Issue by piyushkrmaurya** [vuetifyjs/vuetify#10744]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Linux x86_64

### Steps to reproduce
Create a template with a  selectable input (radio button or checkbox).

### Expected Behavior
Radio input should be clickable within its boundary.

### Actual Behavior
Radio is clickable only outside the boundary.

### Reproduction Link
<a href="https://codepen.io/piyushmaurya/pen/poJWJOG" target="_blank">https://codepen.io/piyushmaurya/pen/poJWJOG</a>

### Other comments
The problem appeared only on including styles.

**Comment by nekosaur** [comment]
Your codepen had different versions of vuetify js and css. Using 2.2.15 for both it works https://codepen.io/nekosaur/pen/yLNPzJv
