### ISSUE TITLE
[Bug Report] Using return-object does not guarantee object in all cases

### ISSUE THREAD

**Issue by Magiczne** [vuetifyjs/vuetify#10753]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
Setup multiple v-combobox with return-object property.

### Expected Behavior
When using return-object prop with v-combobox I expect values that are created by user to be returned in object format.
For example, entering value "test" from keyboard should result model similar to this:
`[{key: 1, value: 'Selected from combobox' }, {key: 2, value: 'test'}]`

### Actual Behavior
Selecting items from v-combobox returns objects and updates model correctly, but entering new values from keyboard updates the model with simple string value.
For example entering value "test" from keyboard results in model similar to this:
`[{key: 1, value: 'Selected from combobox' }, 'test']`

### Reproduction Link
<a href="https://codepen.io/Magiczne/pen/PoqJxQy" target="_blank">https://codepen.io/Magiczne/pen/PoqJxQy</a>

**Comment by KaelWD** [comment]
See #5479 and the linked issues.

**Comment by Magiczne** [comment]
So this functionality is inconsistent. Having prop like return-object should mean that every returned value is an object.

Using **return-object** may extort using another prop, for example **key-generator** which will be function that user provides to generate keys for each new created item and it will be up to user how he would want to handle it.
Not providing it could just fallback to current combobox behavior.

**Comment by KaelWD** [comment]
`return-object` on combobox is just an artefact of its implementation, on the base component (v-select) it does actually make a difference as you can't add custom values. 

> function that user provides to generate keys

This has been discussed before, the current implementation is fine. If you need just objects for some reason you can map the resulting array and transform the strings into whatever you want.
