### ISSUE TITLE
Navigation drawer right border broken with scrollbar

### ISSUE THREAD

**Issue by shakee93** [vuetifyjs/vuetify#1076]
### Steps to reproduce
on vuetifyjs documentation site. remove the class theme--dark from the navigation drawer to see it clearly.

### Versions

on my local machine..
Vue 2.4.1
Vuetify 0.14.2
Chrome
Windows

### What is expected ?
The border should have been on 100% height

### What is actually happening ?
but the border stops in the middle when the scroll bar appears from a list item group. it is the ::after pseudo element on the drawer
![image](https://user-images.githubusercontent.com/14835725/28435167-92a6abd8-6daf-11e7-9851-a2f76799c1ed.png)

when i style the scrollbar it shows it clearly the breaking of the border.

### Reproduction Link
https://vuetifyjs.com/components/alerts

**Comment by shakee93** [comment]
may i know why it has a after element instead of a border right ?

**Comment by johnleider** [comment]
Well, not for much longer!

**Comment by shakee93** [comment]
Do you think a border right might help ? but the border right goes after the scrollbar. but it wont be a problem though.

**Comment by johnleider** [comment]
Unfortunately, and you can see this by testing, the border always sits outside of the scrollbar, and it looks horrible honestly. It seems though it might be the only option.

**Comment by shakee93** [comment]
via javascript we can get that height by `element.scrollHeight` that might help ?

**Comment by johnleider** [comment]
Potentially an option, thank you.

**Comment by swunderlich** [comment]
This seems still to be an issue (again). If you go to https://vuetifyjs.com/en/components/alerts and scroll up the border just stops.

**Comment by nekosaur** [comment]
Please do not comment on old issues. If there's a still a problem, create a new issue at https://issues.vuetifyjs.com
