### ISSUE TITLE
[Feature Request] VDataTable: Vertical alignment for items

### ISSUE THREAD

**Issue by NicoAiko** [vuetifyjs/vuetify#10761]
### Problem to solve
Currently, it's hard to actually change the vertical alignment of content inside a table cell.
This vertical alignment option would make that changeable.

E.g. having a row that grew bigger due to too much content being in a table cell. I want to change the vertical alignment to top-aligned.

### Proposed solution
Through headers it's possible to modify the horizontal alignment. Let's add vertical alignment to it too.

**Comment by YipingRuan** [comment]
> Through headers it's possible to modify the horizontal alignment.
Assume setting of headers align?: 'start' | 'center' | 'end'

@NicoAiko  Do you mean to set the vertical alignment of the **header**?

**Comment by NicoAiko** [comment]
> > Through headers it's possible to modify the horizontal alignment.
> > Assume setting of headers align?: 'start' | 'center' | 'end'
> 
> @NicoAiko Do you mean to set the vertical alignment of the content in one **header** cell?

I think both options would be helpful.
To set the vertical of all contents with an option and to set individual content’s vertical alignment.

**Comment by NicoAiko** [comment]
And I mean contents in `tbody`, not `thead`

**Comment by johnleider** [comment]
Can you provide an example of what you would expect this to look like?

**Comment by NicoAiko** [comment]
Something like this maybe.
Of course with the padding stuff and all, but that's the general idea.
<img width="980" alt="Bildschirmfoto 2020-04-15 um 23 40 32" src="https://user-images.githubusercontent.com/22343587/79391836-8f930e00-7f72-11ea-993f-9b29ff24f4ed.png">

**Comment by escapedcat** [comment]
Maybe this helps:  
https://codepen.io/escapedcat/pen/YzGaREo  

Changing the CSS is a solution/workaround but would be nice to set this via a component-prop.

**Comment by KaelWD** [comment]
I'm ok with leaving this up to custom CSS

**Comment by theking2** [comment]
How to vertical align on mobile only?
