### ISSUE TITLE
[Feature Request] Would like to help with Internationalization (i18n)

### ISSUE THREAD

**Issue by IamManchanda** [vuetifyjs/vuetify#10767]
### Problem to solve
Languages I can provide help with

1. Hindi (by myself)
2. Punjabi (by myself)
3. Urdu (via a friend)
4. Bengali (via a friend)
5. Marathi (via a friend)

### Proposed solution
5 New Languages support at 

https://vuetifyjs.com/en/customization/internationalization#internationalization-i-18-n

**Comment by jacekkarczmarczyk** [comment]
No need to open the issue, just create a PR, similar to https://github.com/vuetifyjs/vuetify/pull/10381 (note that there's a corresponding PR in vue-cli-plugins repo)

**Comment by IamManchanda** [comment]
@jacekkarczmarczyk Thank you 

धन्यवाद
ਤੁਹਾਡਾ ਧੰਨਵਾਦ
آپ کا شکریہ
ধন্যবাদ
धन्यवाद
