### ISSUE TITLE
[Bug Report] v-autocomplete drawer opening when clicking on closable v-chips

### ISSUE THREAD

**Issue by mdebortoli** [vuetifyjs/vuetify#10774]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.2

### Steps to reproduce
When some props are applied to the v-autocomplete, the drawer starts to show up even when click on the "X" icon to remove a chip.

### Expected Behavior
Show the dropdown drawer only if clicked on the select box, not on the closable chips.

### Actual Behavior
Bug found when using props: outlined, solo, filled.

If those props are removed from the Codepen example, the behaviour of the component is correct.

### Reproduction Link
<a href="https://codepen.io/rafacarneiro/pen/abOVEzw?editable=true&editors=101" target="_blank">https://codepen.io/rafacarneiro/pen/abOVEzw?editable=true&editors=101</a>

**Comment by TrobbinsForNow** [comment]
Here's a simpler codepen for reference to show this bug with a v-select, outlined and not:
https://codepen.io/trobbins2/pen/yLNQNyv?editors=1011

**Comment by VesterDe** [comment]
I would also appreciate this being looked at. It's an annoyance in UX for my app.

**Comment by SpenceSouth** [comment]
My team is also running into this bug as well.  Very annoying.

**Comment by MathieuDerelle** [comment]
same for me

**Comment by terazus** [comment]
Hello,
I am still having the issue with version 2.3.19.
Any help would be appreciable: https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/src/components/Editor/EditGeneralInfo.vue#L137-L190

**Comment by KaelWD** [comment]
https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/package.json#L35
