### ISSUE TITLE
[Bug Report] Inline font size on close button for chips - looks poor on small version

### ISSUE THREAD

**Issue by benhalhead** [vuetifyjs/vuetify#10775]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Create a chip, give it both "close" and "small" props

### Expected Behavior
Close button should be sized according to chip size - preferably without any inline styling

### Actual Behavior
Button has inline styling determining font size as 18px regardless of chip size

### Reproduction Link
<a href="https://codepen.io/halhead/pen/ZEGaRPV" target="_blank">https://codepen.io/halhead/pen/ZEGaRPV</a>

### Other comments
Unless absolutely necessary, please reconsider the inline styling here!

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
