### ISSUE TITLE
[Bug Report] Vuetify Color Picker "value" attribute doesn't do anything

### ISSUE THREAD

**Issue by Hillcow** [vuetifyjs/vuetify#10776]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.5.17
**Browsers:** Firefox 73.0
**OS:** Mac OS 10.15

### Steps to reproduce
<v-color-picker
                                                value="#123456"
                                                mode="hexa"
                                                canvas-height="100"
                                                :rules="[rules.required]"
                                                v-model="color"
                                                flat
                                                hide-mode-switch
                                            ></v-color-picker>

### Expected Behavior
value should change the initial color of the color picker

### Actual Behavior
doesn't do anything

**Comment by Leespiker** [comment]
@Hillcow Seems to be working fine for me: https://codepen.io/Leespiker/pen/RwPjByx

Please post a reproduction link if you're still having issues.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
