### ISSUE TITLE
[Bug Report] Right Icon alignment breaks in v-chip if  its 'drag_handler'

### ISSUE THREAD

**Issue by gkatsanos** [vuetifyjs/vuetify#10772]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
make a v-chip with a left and a right icon around the text - use drag_handler

### Expected Behavior
icons/text should be distributed equally in container

### Actual Behavior
right icon sticks to the left

### Reproduction Link
<a href="https://codepen.io/gkatsanos-the-bold/pen/QWbOaRd" target="_blank">https://codepen.io/gkatsanos-the-bold/pen/QWbOaRd</a>

![image](https://user-images.githubusercontent.com/1768834/76145646-a436d900-608b-11ea-8042-92346a305116.png)

**Comment by Leespiker** [comment]
It's `drag_handle`, not `drag_handler`.
