### ISSUE TITLE
[Bug Report] app bar items display order bug

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#10786]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
use `v-toolbar-items`, `v-dialog` and `v-spacer` in `v-app-bar` and hiding/showing `v-toolbar-items` and `v-spacer` dynamically based on resolution.

### Expected Behavior
display order: `v-toolbar-items`, `v-dialog` and `v-spacer`

### Actual Behavior
display order: `v-dialog`, `v-toolbar-items` and `v-spacer` on alternate show/hide,
display order: `v-toolbar-items`, `v-spacer` and `v-dialog` on simultaneous show/hide,

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/ZEGvGbv" target="_blank">https://codepen.io/dev1ldragon/pen/ZEGvGbv</a>

**Comment by johnleider** [comment]
This is intended: https://github.com/vuetifyjs/vuetify/commit/b238b7192c473f39bc51e0b15b29f23e678d1e92#diff-c1ace995aa80cac752d3c2fba847f464

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
