### ISSUE TITLE
[Bug Report] v-menu inside v-calendar behaving weird after deletion of object bound to activator prop

### ISSUE THREAD

**Issue by dbettini** [vuetifyjs/vuetify#10783]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Click on the lowest (one day) event
2. Delete it
3. Do the same for the middle event
4. Do the same for the highest (3 days) event

### Expected Behavior
All events are opened and deleted without problems

### Actual Behavior
The second (or sometimes third, if the second works fine) event is no longer selected (calendar does not emit the event), but the menu is still opened (the menu emits input value, as if it changed, but the data property bound to its value on our component, selectedOpen, didn't change). 

You can see this because the opened menu card is black (no color) and without content. This happens because I assigned an empty object to selectedEvent data property after deletion, to make it clearer - but if I didn't do that, the deleted event would be the one being opened instead (since it was the previous value of selectedEvent). The new event (the one we're clicking on) is not being selected.

### Reproduction Link
<a href="https://codepen.io/dbettini/pen/ZEGaZoK?editors=1010" target="_blank">https://codepen.io/dbettini/pen/ZEGaZoK?editors=1010</a>

### Other comments
The provided codepen uses the template on [calendar docs page](https://vuetifyjs.com/en/components/calendars#events), but with fixed 1, 2 and 3 day events and a delete functionality. 
I'm not sure what is the issue here, is it an issue with menu (which is opened even though selectedOpen is false), or calendar (which does not emit an event), or both. What happens is pretty inconsistent, and doesn't always happen. I've only seen it happen to full day (date only) events that come to another's place after deletion, which don't have the same time interval - specifically, only if removing the shorter one first. Clicking on other events, and then going back to the empty event fixes it.
Putting a v-if on the menu seems to fix this.

**Comment by Leespiker** [comment]
For some reason, the `click:event` event is not always firing. This can be easily reproduced by trying to click on the same event multiple times. It seems to only fire when clicking a different event than previously.

**Comment by KaelWD** [comment]
Setting `:open-on-click="false"` on the menu seems to fix this.

**Comment by KaelWD** [comment]
> `this.selectedElement = nativeEvent.target`

This is your problem, v-menu adds a click listener to its activator that calls `stopPropagation()`, so the click never bubbles up to the calendar event element. Use `nativeEvent.currentTarget` and/or `:open-on-click="false"`

**Comment by dbettini** [comment]
Thanks for the fast solution! 
Most of the code is copied from [event examples in the docs](https://vuetifyjs.com/en/components/calendars/#events), so maybe that example code should be updated with your changes as well

**Comment by dbettini** [comment]
@KaelWD Update: the working fix is setting `:open-on-click="false"`.
The `this.selectedElement =  nativeEvent.currentTarget` version results in the menu not always opening in the same place relative to the calendar entry, but in different places depending on the event data (is int multi day, etc.)
