### ISSUE TITLE
[Feature Request] v-expansion-panel-content "open" prop

### ISSUE THREAD

**Issue by AAGene** [vuetifyjs/vuetify#10785]
### Problem to solve
At the moment, there is no easy way of knowing if an expansion panel is open from within. It makes it hard to know wether a panel is open or not.

### Proposed solution
v-expansion-panel-header has an "open" prop which is a boolean indicating wether is it open or not. The same should be done for v-expansion-panel-content

**Comment by KaelWD** [comment]
Do you have an example of what this would be used for? The slot isn't actually rendered until it's open so changing the way something displays while it's closed would be pointless.

**Comment by AAGene** [comment]
Say you have a User in a store.
You have settings hidden under panels for this user. I want to change a few settings, when mounting the contents, it loads the current user setting properly.

Now the user in my store changes. I open a panel I opened previously -- I see the same settings as my previous user.
The panel won't load the settings again because it's already mounted.

**Comment by Leespiker** [comment]
@AAGene The `value` of the `v-expansion-panels` tracks the open/active `v-expansion-panel`s. You can also put a `ref` on specific `v-expansion-panel`s and check if they're active individually. i.e. `$refs.myExpansionPanel.isActive` You can also watch for the `change` event on both `v-expansion-panels` and `v-expansion-panel`.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
