### ISSUE TITLE
[Documentation] V1 docs are not available anymore

### ISSUE THREAD

**Issue by heygambo** [vuetifyjs/vuetify#10788]
### Environment

**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.3

### Steps to reproduce
navigate to
http://v1.vuetify.com/

and navigate to
http://v1.vuetifyjs.com/

and go to https://v15.vuetifyjs.com/en/
select v1 at the top right corner

### Expected Behavior
Being able to view the v1 docs

### Actual Behavior
getting 404 pages or being redirected to shady websites

### Reproduction Link
<a href="http://v1.vuetifyjs.com/" target="_blank">http://v1.vuetifyjs.com/</a>

**Comment by jacekkarczmarczyk** [comment]
works for me

**Comment by MajesticPotatoe** [comment]
Cant reproduce. Works for me as well. Try clearing your cache. If this still persists, submit a new issue or reach out to us in [Discord community](https://community.vuetifyjs.com).

**Comment by heygambo** [comment]
Ah I've found out what it is.

It redirects me to https://v1.vuetifyjs.com/de-DE which then renders the 404

**Comment by MajesticPotatoe** [comment]
That would be because that is not a language available in the v1 docs (v1 only offers about 5 languages for translations). You can get out of this by selecting English (or other preferred language) by clicking the little flag icon.

**Comment by KaelWD** [comment]
Probably sharing the cookie with vuetifyjs.com

**Comment by heygambo** [comment]
I guess the best would be if it would fall back to English automatically
