### ISSUE TITLE
[Feature Request] VDatePickerDateTable should not have 日 character at each date when locale is ja.

### ISSUE THREAD

**Issue by tamonmon0417** [vuetifyjs/vuetify#10787]
### Problem to solve
Unnatural UI.
It's unnatural to have 日 character at each date of VDatePickerDateTable.
https://codepen.io/tamonmon/pen/GRJyJBq?editable=true&editors=101

### Proposed solution
When local is ja (zh-* might have same issue), the VDatePickerDateTable shows just numbers.

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2786#issuecomment-351394458
