### ISSUE TITLE
[Bug Report] v-dialog error when wrapped in v-if

### ISSUE THREAD

**Issue by bcronje** [vuetifyjs/vuetify#10782]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Just open the CodePen and look at the developer console. 

### Expected Behavior
Don't throw an error.

### Actual Behavior
The following error occurs:

```
vue.js:634 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'focus' of undefined"

found in

---> <VDialog>
       <VApp>
         <Root>
```

### Reproduction Link
<a href="https://codepen.io/bcronje/pen/poJdBpb" target="_blank">https://codepen.io/bcronje/pen/poJdBpb</a>

**Comment by KaelWD** [comment]
Don't close a dialog immediately after opening it: https://codepen.io/kaelwd/pen/oNXoOQa?editors=1010

**Comment by bcronje** [comment]
`setTimeout` works for me, thank you.

**Comment by jotapesilva** [comment]
Gosh, lost a lot of time on that! Thanks works for me also! \0/
