### ISSUE TITLE
Setting `id="some_element_id"` on a `v-layout` component just adds `id` to the list of classes

### ISSUE THREAD

**Issue by roblav96** [vuetifyjs/vuetify#1079]
### Steps to reproduce
Create an element like so:
```html
<v-layout column id="sbar_table_container" class="flex-1 scroll-y"></v-layout>
```

### Versions
```
├── vue@2.4.1
├── vuetify@0.14.5
```

### What is expected ?
```html
<div id="sbar_table_container" class="layout column flex-1 scroll-y"></div>
```

### What is actually happening ?
```html
<div class="layout column flex-1 scroll-y id"></div>
```
The component is removing the `id` attribute all together and adding `id` to the class list.

### Reproduction Link
Please provide a `template` to a reproduction link, sorry I'm not familiar with making a jsfiddle from scratch 😞

**Comment by capttrousers** [comment]
This is also affect v-flex, not sure if the fix addresses that too. Here's a codepen demonstrating it:

https://codepen.io/anon/pen/vJYLLX

**Comment by johnleider** [comment]
The fix was applied to all grid components, container, layout, flex and spacer.

**Comment by nocrates** [comment]
@johnleider Would this fix also address "data-id" or other data attributes?  I have seen the same problem, where the "data-id" attribute ends up rendered as part of the class instead of a separate attribute.

**Comment by adi-zz** [comment]
@nocrates - no (see #3673)
