### ISSUE TITLE
[Bug Report] V-timeline: Cards which are clickable dont have a shadow on the arrow

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#10790]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Create a timeline with a card inside a timeline-item

Give the card a working `@click` and the arrow's shadow is gone which gives a really weird look

### Expected Behavior
An arrow with a shaddow

### Actual Behavior
An arrow without a shaddow

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/KKpZgOa" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/KKpZgOa</a>

**Comment by YipingRuan** [comment]
For visual check:
![image](https://user-images.githubusercontent.com/5492274/76595580-f61daa00-6536-11ea-9374-778465f2b1b5.png)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
