### ISSUE TITLE
[Bug Report] Speed-dialog under v-tab-item

### ISSUE THREAD

**Issue by rifton007** [vuetifyjs/vuetify#10802]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
The speed-dialog appaers under v-tab-item

### Expected Behavior
speed-dialog appaers over v-tab-item

### Actual Behavior
speed-dialog appaers underv-tab-item

### Reproduction Link
<a href="https://codepen.io/InnovaWEB/pen/oNXpQgg?editors=1010" target="_blank">https://codepen.io/InnovaWEB/pen/oNXpQgg?editors=1010</a>

**Comment by alekbless** [comment]
Did you find any workaround?

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
