### ISSUE TITLE
[Bug Report] button group active buttons should be easily customizable

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#10803]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
try to change css for active button - - text color to be red for example, background to be blue -- there's no way to do it with active-class, color and background-color props used together. have to use important classes

### Expected Behavior
to use props to properly customise active button

### Actual Behavior
does not work

### Reproduction Link
<a href="https://codepen.io/rveruna/pen/e31be2f4c49ee3a2a0ac7474d7c94331" target="_blank">https://codepen.io/rveruna/pen/e31be2f4c49ee3a2a0ac7474d7c94331</a>

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
