### ISSUE TITLE
[Bug Report] Vuetify checkbox hover effect does not disappear on scroll

### ISSUE THREAD

**Issue by nekdolan** [vuetifyjs/vuetify#10801]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox
**OS:** Android

### Steps to reproduce
1. Hover checkbox
2. Scroll up and down, but do not move mouse

### Expected Behavior
The  hover effect should disappear when the scroll starts.

### Actual Behavior
Hover effect stays in place during and after scroll.

### Reproduction Link
<a href="https://codepen.io/trinimac/pen/vYOpVyq?editable=true&editors=101" target="_blank">https://codepen.io/trinimac/pen/vYOpVyq?editable=true&editors=101</a>

**Comment by Leespiker** [comment]
It's easier to see in [this example](https://codepen.io/Leespiker/pen/OJyJGLd), and screen size does not matter.

**Comment by KaelWD** [comment]
Not a bug, browsers don't remove `:hover` until the cursor is moved.
