### ISSUE TITLE
[Bug Report] Treeview active elements not updating when mounted, but only if data is loaded later

### ISSUE THREAD

**Issue by Magiczne** [vuetifyjs/vuetify#10814]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Look at [this codepen](https://codepen.io/Magiczne/pen/zYGRpGv).

### Expected Behavior
In case items are hardcoded into date everything works and treeview node receives active state.
In case items are loaded asynchronously node that should be active is still not active.

### Actual Behavior
Node is not receiving active state when data is loaded asynchronously

### Reproduction Link
<a href="https://codepen.io/Magiczne/pen/zYGRpGv" target="_blank">https://codepen.io/Magiczne/pen/zYGRpGv</a>

### Other comments
In the reproduction link i placed text field, because when data is updated, active state is properly assigned to node, that's expected but for testing reasons it is there.

**Comment by mhautman** [comment]
We also have this problem. Is there any workaround as I see it's still not solved?

**Comment by Magiczne** [comment]
I have not found any workaround at the time and bug is still present in my apps.

**Comment by matletix** [comment]
Bug still present
