### ISSUE TITLE
[Bug Report] v-card-title before v-data-table breaks the non-sortable headers

### ISSUE THREAD

**Issue by grishnyakov** [vuetifyjs/vuetify#10812]
### Environment
**Vuetify Version:** 2.2.16
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
add v-card-title before v-data-table

### Expected Behavior
All Headers have bottom border

### Actual Behavior
Only non-sortable headers have bottom border

### Reproduction Link
<a href="https://codepen.io/grishnyakov/pen/ExjQWGX?editors=1010" target="_blank">https://codepen.io/grishnyakov/pen/ExjQWGX?editors=1010</a>

**Comment by KaelWD** [comment]
Looks fine to me
![image](https://user-images.githubusercontent.com/16421948/76420290-01b58780-63f6-11ea-9204-17e323ac3a10.png)

**Comment by grishnyakov** [comment]
![image](https://user-images.githubusercontent.com/29563933/76420486-ff3a3a00-63c3-11ea-96db-51b554783cf5.png)

**Comment by grishnyakov** [comment]
In Firefox works normally. 
Try open in chrome

**Comment by KaelWD** [comment]
That is in chrome 80.0.3987.132

**Comment by grishnyakov** [comment]
I use chrome 80.0.3987.132 too, but i see this problem... 
Hmm, don't know what to do with it...

**Comment by grishnyakov** [comment]
When i change zoom on page, the table stand displayed normally. Promblem is happen then zoom page = 100%
![image](https://user-images.githubusercontent.com/29563933/76421592-b8e5da80-63c5-11ea-8ab8-e328ae0b0cdf.png)

**Comment by grishnyakov** [comment]
If i set page zoom as 175% i see diffrent with border-lines
![image](https://user-images.githubusercontent.com/29563933/76422029-635dfd80-63c6-11ea-9e7a-e9a5e94dd773.png)

**Comment by johnleider** [comment]
What is the exact environment, browser, resolution, etc and exact reproduction steps to see this, I'm not able to reproduce.

**Comment by grishnyakov** [comment]
when i remove the icon "arrow" in header from DOM using chrome devTools, bottom border becomes visible

**Comment by grishnyakov** [comment]
![vuetify](https://user-images.githubusercontent.com/29563933/76488405-28e87500-6447-11ea-893a-e460ad607252.gif)

**Comment by grishnyakov** [comment]
Icon size affects bug:
![vuetify2](https://user-images.githubusercontent.com/29563933/76489690-fe002000-644a-11ea-83a7-b8dee01b145c.gif)

**Comment by KaelWD** [comment]
Do you have any scaling enabled in windows?
What's chrome's graphics feature status (chrome://gpu/)?
Does removing the `outline` rule on `.v-data-table-header th.sortable` affect it?

**Comment by grishnyakov** [comment]
Windows scaling: 100% (by default)
[chromeGpu.txt](https://github.com/vuetifyjs/vuetify/files/4322658/chromeGpu.txt)

**Comment by KaelWD** [comment]
You have a driver update apparently: https://www.nvidia.com/Download/driverResults.aspx/157542/en-us

Aside from that I don't know what we can do to fix this, I haven't seen it anywhere else since that fix.

**Comment by grishnyakov** [comment]
The problem was in the browser.
 For some reason, he reduced the size of all blocks on 0.01 pages on all pages. 
I decided this bug by reinstalling chrome
