### ISSUE TITLE
[Bug Report] V-tooltip: Position is not updated when window is resized  using v-model visibility

### ISSUE THREAD

**Issue by victor-babiy** [vuetifyjs/vuetify#10811]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Linux x86_64

### Steps to reproduce
1. Create tooltip which can be programmatically changed using v-model.

2. Open tooltip clicking to the button.

3. Try to resize the browser window and position of the tooltip become wrong.

### Expected Behavior
Position of tooltip updated when changing the window size

### Actual Behavior
Position of tooltip not updated when changing the window size

### Reproduction Link
<a href="https://codepen.io/victorAA/pen/KKpQWbd" target="_blank">https://codepen.io/victorAA/pen/KKpQWbd</a>

**Comment by KaelWD** [comment]
Vuetify 1.5 is no longer supported, this is fixed in v2.
