### ISSUE TITLE
Falsy selected options in <v-select> multiple returns the backing object when the return-object prop is false

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#1081]
### Steps to reproduce

Create a v-select component with a falsy value as one of the available options. e.g. 0. Select the falsy option along with a truthy option e.g. 1. The returned model contains an object for the falsy value and only the value for the truthy option.

I'm pretty sure this is a regression in 14.5 as it worked fine in previous versions.

### Versions
Vuetify 14.5
Chrome 59.0.3071.115 (Official Build) (64-bit) on Mac

### What is expected ?
The v-model of the selected options should only contain the values of the selected items. Not a mix of objects and values. 

### What is actually happening ?
Falsy selections return the backing object whereas truthy selections return the selected value. 

### Reproduction Link
https://codepen.io/smitchell/pen/JJgmvB

**Comment by johnleider** [comment]
Leaving open until I write a test for this.
