### ISSUE TITLE
[Bug Report] V-TreeView does not call custom filter function unless a search text is present

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#10815]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Windows 10

### Steps to reproduce
1. Create  tree view
2. Bind your filter function to `:filter`
3. Notice that it never gets called
4. Bind a field to `:search`
5. Add some non-blank value to the search field
6. Notice how your function is now called

### Expected Behavior
When I define a filter function, that function is called.

This should be especially evident if `:search` is not used.

### Actual Behavior
That function is not called.

Unless I:

1. Have used the `:search` property 
2. AND the `:search` property is not blank

### Reproduction Link
<a href="https://codepen.io/douglasg14b/pen/oNXEEqm?editors=1010" target="_blank">https://codepen.io/douglasg14b/pen/oNXEEqm?editors=1010</a>

### Other comments
In the reproduction link, the filter function returns false, which should filter out everything. It does not unless a search term is entered.

Remove the `:search` binding, and it will never filter.

**Comment by douglasg14b** [comment]
Also noticing that the custom filter function is not called always for all items, even if I specify a "fake" `:search`.

It seems it's evaluated once, and even if new items are loaded in, it never re-evaluates unless the search term changes. Failing to filter out new items.

**Comment by mervetalakaci** [comment]
I had have a problem with this issue. If there is no "item-key" in treeview, the search fails.

**Comment by rti-Austin** [comment]
I'm using v3.3.14 and it appears that the `:custom-key-filter` option works great... as long as the `:search` binding has a non-blank value. With or without the `:custom-filter` function and with any `:filter-mode` options, I get expected results, but the `:search` value must be a non-blank string.

**Possible Workaround:** Add a space (" ") to the search string to trigger the `custom-key-filter` functions. However, this also requires a `:custom-filter` function that can "trim" leading and trailing whitespace so data values without spaces don't get accidentally filtered out. For example: 
````
const customFilter = (value, query, item) => {
  if (!value || !query) return -1; 
  const formattedQuery = query.trim().toLowerCase();  // Remove leading and trailing whitespace from the query string.
  return value.toString().toLowerCase().indexOf(formattedQuery)
}
````
Also, I noticed there aren't any 'custom-key-filter' examples in the [docs](https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/v-data-table)... maybe the `custom-key-filter` feature just isn't done yet.
