### ISSUE TITLE
[Feature Request] Empty textfield, model representation

### ISSUE THREAD

**Issue by alphawolf1988** [vuetifyjs/vuetify#10817]
### Problem to solve
It would be nice to have the possibility to set the model representation for an empty textfield. Currently the textfield will be set to an empty string, but there are also a lot of use cases where a null value makes sense.

### Proposed solution
Introduce an property like "empty-value" where the user can set a desired model value for this state.

**Comment by valentingavran** [comment]
Can you name a use case where this would be necessary?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
