### ISSUE TITLE
[Bug Report] [v-datatable] Customizing default header is not applied in mobile view

### ISSUE THREAD

**Issue by ian-ng** [vuetifyjs/vuetify#10818]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows, Android, iOS, Mac OSX

### Steps to reproduce
1. Create a [v-datatable](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/data-tables/intermediate/customize-header.vue)
2. Set a custom header of the table
```
/* For example */
<template v-slot:header.name="{ header }">
  {{ header.text.toUpperCase() }} (customized)
</template>
```
3. change the window size to a mobile view

### Expected Behavior
Expecting the header.name is displaying "DESSERT (100G SERVING) (customized)" in mobile view.

### Actual Behavior
The actual display is "Dessert (100g serving)".

### Reproduction Link
<a href="https://codepen.io/ianng/pen/WNvMmvE" target="_blank">https://codepen.io/ianng/pen/WNvMmvE</a>

**Comment by KTN-Dev** [comment]
Have we any workaround for this issue?

**Comment by MariaNicolosi** [comment]
Is there a plan to address this? Looks like no movement since last June.

**Comment by KTN-Dev** [comment]
No news for the moment. Hope this will be adressed.

**Comment by quroom** [comment]
I guess you can use computed headher which returns different header text by mobile resolusion.
It can be workaround.

**Comment by quroom** [comment]
> KTN

like ```:headers="isMobile ? mobile_headers : headers"```

**Comment by KTN-Dev** [comment]
Will try this tip.

Thanks.
