### ISSUE TITLE
[Bug Report] Loading property removes underline of v-text-field if null

### ISSUE THREAD

**Issue by DanielStefanK** [vuetifyjs/vuetify#10828]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Mac OS 10.15

### Steps to reproduce
- create a v-text-field
- set loading prop to null
- underline disappears

### Expected Behavior
Underline should be visible and loading state should be false.

### Actual Behavior
Underline disappears.

### Reproduction Link
<a href="https://codepen.io/daniel-stefan/pen/qBdojMB" target="_blank">https://codepen.io/daniel-stefan/pen/qBdojMB</a>

**Comment by DanielStefanK** [comment]
I see you commit and it is a solution to my specific problem.
However, wouldn't it be better to test if the value is falsy?

**Comment by KaelWD** [comment]
No, v-switch has a falsy value (`''`) for true.
