### ISSUE TITLE
[Bug Report] Multiple Combobox show empty when double click on chip then re-select

### ISSUE THREAD

**Issue by cuongbm0211** [vuetifyjs/vuetify#10827]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
1. Open the reproduction link 
2. Double click on any selected chip (We see the text of the chip paste to the v-combobox)
3. Click to clear all icon (the 'X' icon on the right of the v-combobox) --> all chips will disappear
4. Focus on the v-combobox to select another chip

### Expected Behavior
The selected chip will appear on the v-combobox

### Actual Behavior
We see some null chips on v-combobox

### Reproduction Link
<a href="https://codepen.io/dangky0211/pen/bGdvqaO" target="_blank">https://codepen.io/dangky0211/pen/bGdvqaO</a>

**Comment by lockevn** [comment]
Looking for this. v-combobox is a very flexible and important UI element
