### ISSUE TITLE
Make <v-btn-toggle> a linking component for <v-btn>

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#1082]
## Idea
Right now `<v-btn-toggle>` accepts an items prop. What I propose is instead have `<v-btn-toggle>` use slots instead and accept `<v-btn>` components as children. In the backend the component would provide the same behavior it currently does by linking the provided buttons into a set of togglable buttons.

## API
The `<v-btn-toggle>` would have the same API except the items prop would no longer be necessary and it would have a slot for `<v-btn>`.

## Advantages
This would make the component much more flexible and allow for styling of the individualized buttons. Also, events could be attached to the button or to the button group depending on the needs of the developer. Also things like tooltips could be added to individual buttons something that is now currently not possible. Another advantage would be now that buttons are all the same if you want to change or reuse a button it can be copied and pasted instead of completely changing the way it is created.

**Comment by nekosaur** [comment]
Has been merged into dev. Will be available in next release
