### ISSUE TITLE
[Bug Report] v-text-field validate rules passed value is undefined

### ISSUE THREAD

**Issue by carmel** [vuetifyjs/vuetify#10823]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.106
**OS:** Windows 7

### Steps to reproduce
```vue
<v-form ref="form" v-model="valid">
      <v-text-field dense class="required"
        type="number"
        v-model.trim="formData.CarOwnerMobile"
        label="mobile"
        :rules="[mobileValidator]"
      ></v-text-field>
</v-form>
```
```javascript
export const mobileValidator = (value) => {
  console.log(value)
  return testMobile(value) || 'Invaild mobile'
}
```

### Expected Behavior
the param value in mobileValidator  must not be undefined

### Actual Behavior
the param value in mobileValidator  always undefined

### Reproduction Link
<a href="https://codepen.io/carmeltop/pen/oNXqBWv?editors=1011" target="_blank">https://codepen.io/carmeltop/pen/oNXqBWv?editors=1011</a>

**Comment by carmel** [comment]
Made a low-level mistake，my fault

**Comment by Fahmisutansyah** [comment]
@carmel What was the mistake you made? I'm encountering the same problem.

**Comment by Peggy2344** [comment]
same here

**Comment by mevingmonson** [comment]
I'm also facing similar issue. Why is the value under rules is undefined?

**Comment by carmel** [comment]
Sorry, it's been a while since I've used vuetifyjs and I've forgotten how to fix the code long ago!
