### ISSUE TITLE
[Feature Request] A11Y: Add `role="presentation"` to <v-spacer>

### ISSUE THREAD

**Issue by mathiasschopmans** [vuetifyjs/vuetify#10829]
### Problem to solve
VSpacer should set `role="presentation"` to improve A11Y.

https://timwright.org/blog/2016/11/19/difference-rolepresentation-aria-hiddentrue/

> The accessibility tree is a mapping of objects within an HTML document that need to be exposed to assistive technology. Anything that communicates aspects of the UI or has a property or relationship that needs to be exposed, gets added to the tree. This happens automatically for most elements when you use a strong semantic HTML structure, but you can also add or remove objects programmatically with accessibility hooks like:  `role="presentation"` and `aria-hidden="true"` 

> Most of the documentation you’ll find online about the role="presentation" attribute mentions removing spacer images,and layout tables.

### Proposed solution
Add default attribute `role="presentation"` to the `VSpacer` component.

**Comment by phiter** [comment]
This is not necessary.

`<v-spacer` renders a div without content, and divs have no semantic meaning. So if you add `role="presentation"` to it nothing changes.

Take a look at the [w3 spec for `role="presentation"`](https://www.w3.org/TR/wai-aria-practices-1.1/#presentation_role)

We only need `role="presentation"` to remove semantic meaning of something we don't need to have semantic meaning, like if we have an `ul` but we don't want it to have the semantics of a list. It's like changing it to a `div`.

**Comment by mathiasschopmans** [comment]
Tanks for the explanation, @phiter. We had a requirement by the client to add it, but maybe I can argue.

I'm sorry for the trouble and thankful for your efforts even if your commits might not end up in the release @jacekkarczmarczyk & @Leespiker
