### ISSUE TITLE
[Bug Report] v-banner in limited horizontal space (eg. in v-navigation-drawer)

### ISSUE THREAD

**Issue by dominik-korsa** [vuetifyjs/vuetify#10822]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Place `v-banner` with `prepend-icon` and action buttons inside `v-navigation-drawer`

### Expected Behavior
Banner content and actions always show on separate rows

### Actual Behavior
Banner content and actions show on separate rows only on mobile, while they show next to each other on a single row (content might not be visible at all due to the small width)

### Reproduction Link
<a href="https://codepen.io/dominik-korsa/pen/MWwVybJ" target="_blank">https://codepen.io/dominik-korsa/pen/MWwVybJ</a>

**Comment by Leespiker** [comment]
For context, Material Design states:
> Place buttons under the banner message, **or** on the same line if there is enough room to fit both.

See: https://material.io/components/banners/#anatomy

**Comment by johnleider** [comment]
resolved by https://github.com/vuetifyjs/vuetify/issues/12705

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
