### ISSUE TITLE
[Bug Report] [v-checkbox] indeterminate state remains the same icon

### ISSUE THREAD

**Issue by isysmacedo** [vuetifyjs/vuetify#10834]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
1- Create a 'v-checkbox'
2- Set indeterminate prop as true
3- After you click at the checkbox, value changes to true but the icon remains the same and color gets changed.

### Expected Behavior
When you click at checkbox in a indeterminate state it should change its icon to a checked icon

### Actual Behavior
Icon remains in indeterminate state.

### Reproduction Link
<a href="https://codepen.io/isysmacedo/pen/xxGWWdB?editors=1010" target="_blank">https://codepen.io/isysmacedo/pen/xxGWWdB?editors=1010</a>

**Comment by johnleider** [comment]
Thank you for the Bug Report and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement for LTS.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by zairhenrique** [comment]
I don't get why this is closed as this is not a feature request but a bug and I can replicate that. Any reasons for the won't fix decision? @johnleider

**Comment by KaelWD** [comment]
f7cd0459f41ad71368d3cc3580681f41063bdc31, #8270

I guess because it adds an event?
