### ISSUE TITLE
[Bug Report] Menu Component never closes 

### ISSUE THREAD

**Issue by isysmacedo** [vuetifyjs/vuetify#10831]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Create a "v-menu"
Set props: close-on-click & close-on-content-click as false.
The dropdown menu can not be closed anymore.

### Expected Behavior
When clicked at the button it should close the menu despite the options were set as false.

### Actual Behavior
The dropdown menu can not be closed anymore.

### Reproduction Link
<a href="https://codepen.io/isysmacedo/pen/KKpoZEP?editors=1010" target="_blank">https://codepen.io/isysmacedo/pen/KKpoZEP?editors=1010</a>

**Comment by KaelWD** [comment]
Vuetify 1.5 is no longer supported, this is fixed in v2.
