### ISSUE TITLE
[Feature Request] v-markup

### ISSUE THREAD

**Issue by Mashiane** [vuetifyjs/vuetify#10844]
### Problem to solve
I am creating documentation and want to show source code like how you do it in your framework. I noted that this uses a v-markup component, can you please make this one of the standard components

### Proposed solution
Addition of the v-markup component to the standard markup

**Comment by KaelWD** [comment]
Markup is just (vue-prism-component)[https://github.com/egoist/vue-prism-component] with a copy button and a link to source. We have a policy of no external dependencies so this isn't likely to be added, thanks for the suggestion though.
