### ISSUE TITLE
[Bug Report] v-slider with thumb-label inside v-list-group is not displayed correctly

### ISSUE THREAD

**Issue by ufonius** [vuetifyjs/vuetify#10842]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 1.4.2
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 10

### Steps to reproduce
1. Create a v-list-group
2. Add v-slider to the list (with thumb-label)
3. Slide the slider around and observe how thumb-label is partially 'hidden' behind other components

### Expected Behavior
The slider thumb-label should be clearly visible. Vuetify 1.5 example:

https://codepen.io/Ufonius/pen/VwLXoBz

### Actual Behavior
Slider thumb-label is 'hidden' behind other components

### Reproduction Link
<a href="https://codepen.io/Ufonius/pen/zYGWgWv" target="_blank">https://codepen.io/Ufonius/pen/zYGWgWv</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
