### ISSUE TITLE
[Bug Report] props "options" doesn't work in component v-img

### ISSUE THREAD

**Issue by arkanaman1** [vuetifyjs/vuetify#10848]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
I added props "options"

```
<v-img
    src="https://picsum.photos/510/300?random"
    :options="{
           root: null,
           rootMargin: '0px 0px 0px 0px',
           threshold: 1
    }"
    min-height="500px"
></v-img>
```

### Expected Behavior
The picture should be loaded only after it completely hits the screen

### Actual Behavior
The picture is loaded immediately after part of it hits the screen

### Reproduction Link
<a href="https://codepen.io/vitalij-kasqn/pen/YzXLXEJ" target="_blank">https://codepen.io/vitalij-kasqn/pen/YzXLXEJ</a>

**Comment by KaelWD** [comment]
Looks like directives are all jacked up, there's a bunch of stuff that either only works with render functions or doesn't work at all.

**Comment by arkanaman1** [comment]
Please tell me what other ways can I implement this functionality?
