### ISSUE TITLE
[Feature Request] Date range picker not following MD specs

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#10845]
### Problem to solve
The current date range picker is simply a single date picker that highlights multiple dates. But a date range is not the same as multiple selected dates, so the visual feedback from the vuetify picker is incorrect.

### Proposed solution
Follow MD specs: https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1ow2svD50eumJzHFJUZc4PLKZCAJJCYsX%2Fpicker-desktop-singledate-selectdate.mp4

**Comment by KaelWD** [comment]
Duplicate of #9608

material.io didn't have range pickers when this was implemented.

**Comment by ThomasKuhlmann** [comment]
Sorry about the duplicate!
