### ISSUE TITLE
[Bug Report]  Checkbox array of objects not working properly

### ISSUE THREAD

**Issue by rawnanoob** [vuetifyjs/vuetify#10849]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Opera 67.0.3575.78
**OS:** Windows 10

### Steps to reproduce
Click on one checkbox

### Expected Behavior
The other list of checkboxes should not be affected by this.

### Actual Behavior
As you click on one checkbox , the other list of checkbox are all checked

### Reproduction Link
<a href="https://codepen.io/rawnanoob/full/oNXdxyM" target="_blank">https://codepen.io/rawnanoob/full/oNXdxyM</a>

**Comment by nekosaur** [comment]
This bug is caused by using an array of objects. By setting the `value` prop of `v-checkbox` to an inline object, the `value` watchers of both `VInput` component and `validatable` mixin gets triggered even when the object has not "changed", and `lazyValue` is set to `value` prop value.

This is an effect of v-checkbox inheriting from v-input while using `value` prop for a different purpose

**Comment by rawnanoob** [comment]
So is there way to solve this bug?

**Comment by KaelWD** [comment]
Use primitives instead of objects, or store the objects in data instead of the template.

**Comment by jakubstankowski** [comment]
I had the same problem, i recommend use simple html checkbox for that type of data, like this:
`<form  v-for="(filter, i) in filterValues"
                :key="i">
             <input type="checkbox"
                    @change="filterCheckboxChange(filter.value)"
                    :value="filter.value"
                    v-model="selected">
             <label>
                 {{filter.value}}
             </label>
         </form>`

**Comment by DavidSmolinski** [comment]
This shows the data being destroyed. Using an HTML checkbox avoids the bug, but you loose some Vuetify.

[How it should work](https://codepen.io/david-smolinski/pen/yLJovpM)
[broken](https://codepen.io/david-smolinski/pen/NWrjwKy)

**Comment by MartinWeise** [comment]
Can confirm this with vuetify@1.11.2.

Working plain-html checkbox array:

```html
<input type="checkbox" :value="item" v-model="selection">
```

Buggy vuetify checkbox array:

```html
<v-checkbox
  id="action"-->
  v-model="selection"
 :value="item" />
```

**Comment by jenyaukraine** [comment]
> Can confirm this with vuetify@1.11.2.
> 
> Working plain-html checkbox array:
> 
> ```
> <input type="checkbox" :value="item" v-model="selection">
> ```
> 
> Buggy vuetify checkbox array:
> 
> ```
> <v-checkbox
>   id="action"
>   v-model="selection"
>  :value="item" />
> ```

Again spot this approach. Vue3 vutify 3.4.6. So first click works as charm. All other next except last variable in selected array. So it trying to check again and double value at end of array and next click removing both.
