### ISSUE TITLE
[Feature Request] Support multiple background images

### ISSUE THREAD

**Issue by jamesladd** [vuetifyjs/vuetify#10841]
### Problem to solve
To achieve some graphical designs it is necessary to have several background images on top of which there can be other content like buttons, text, cards etc.

Imagine a card where there are separate images that sit at the four corners. This can be achieved with a single image but it isn't responsive and it is hard to manage.

Currently the v-img component doesn't enable this outcome as it creates a DIV and sets the image as the background of this DIV. So you have to have a sized image and add the contents as the SLOT of the v-img. This limits things to have large or special images.

Also, setting the background image of a v-card almost solves this problem but you are limited to one background image, and when things get responsive it is hard to get right / deal with.

What is needed is a way to set an image on the page and control where it is and ensure that other content including images can be placed over.

If you look at the https://appeggio.com home page and scroll through it you will see floating images,
and at the bottom you will see a card that has a background image (blue/orange circle) with another image over the top of it. This was hard to achieve with a v-card and a v-image so I wrote a directive for my needs - see solution.

### Proposed solution
My proposal is for v-img to be extended where it can have an 'isBackgrounded' prop to allow the images to be placed on the background. It also needs an anchor prop to the background image is associated with another component and not the v-img to allow positioning and so the size and location of the v-img doesn't impact layout.

I hacked together a directive to achieve this as it allowed me to quickly associate the background image with an existing DOM element, and the directive used the CSS background properties on this DOM element to achieve my outcome. Note, that my directive allowed for a set of images and positions to be given.

Below is the the very rough code I did, which I hope serves as a guide. Given my limited knowledge of Vue and Vuetify this looked like a quick way forward. I do think that v-img can be extended to achieve this rather than a directive. 

You can ignore the interpolateValue and getContext calls as they are specific to me.

```
/* eslint-disable */
import { getContext, interpolateValue } from '@/app/components/helpers';

const addOrRemove = (el, binding, vnode, oldVnode) => {
  if (vnode) {
    if (binding.arg && binding.arg.src) {
      const imgs = binding.arg.src;
      let background = '';
      let size = '';
      let sizePart = '';
      let src = '';
      const context = getContext();
      imgs.forEach((img) => {
        src = interpolateValue(img.src, context);
        background = `${background} url('${src}') no-repeat ${img.position || ''},`;
        sizePart = `${img.width || ''} ${img.height || ''}`.trimRight();
        size = `${size} ${sizePart},`.trimLeft();
      });
      el.style.background = background.slice(0, -1) + ' ' + el.style.background;
      el.style.backgroundSize = size.slice(0, -1);
      if (binding.arg.color) {
        el.style.backgroundColor = binding.arg.color;
      }
      el.aBgImg = true;
    } else if (el.aBgImg) {
      el.style.background = '';
      el.aBgImg = undefined;
    }
  }
};

export default {
  inserted(el, binding, vnode) {
    addOrRemove(el, binding, vnode, false);
  },
  // updated(el, binding, vnode) {
  //   console.log('updated');
  // },
  componentUpdated(el, binding, vnode, oldVnode) {
    addOrRemove(el, binding, vnode, oldVnode);
  },
};
```

**Comment by KaelWD** [comment]
Can you show an example of how you'd use those props and what the expected output would be?

**Comment by jamesladd** [comment]
Your code pen is great and show a way to achieve 'an' outcome.
However, in this case the image being positioned has been purposely made rather than a background image being overlayed with another. The need to make custom images to achieve an outcome is what I am trying to avoid. More importantly if I wanted text over this image it would be rather difficult because the v-img is a div and not an image positioned on the background.

Try putting a v-card-text or other component over the image?

If you look again at the Appeggio website and scroll down to the text "I need a quality App for my business..." you will see just left of that an image that is positioned on the background, and a little further down another image that is positioned.

Consider a Card where you want images to sit on the corners, regardless of size. Say top-left, top-right, bottom-left and bottom-right and centered

```
<v-card>
  <v-img src='top-left' backgrounded  "other props" />
  <v-img src='top-right' backgrounded "other props"  />
  <v-img src='center-center' backgrounded "other props"  />
  <v-img src='bottom-left' backgrounded  "other props" />
  <v-img src='bottom-right' backgrounded  "other props" />
  // other slots ...containing things you want OVER the other images.
</v-card>
```

I'd like to be able to use v-img and tell it to be backgrounded (use CSS background style) and
it would use it's parent as the anchor DOM element. In the above case the v-card component.

**Comment by KaelWD** [comment]
Yeah sorry I still don't really understand. You want v-img to affect its parent's inline styles instead of being its own element? How does positioning work? It seems way out of scope for the component, it's only supposed to be a replacement for the native `<img>` element with lazy loading and automatic placeholders.

**Comment by jamesladd** [comment]
Hi Kael,

Thank you for your response.

I want the v-img to allow me to specify that the image is a background
image and therefore should be added via CSS to the background of it's
container.
(Nested inline styles)

Positioning would work according to the same rules as CSS Background image
positioning, and along the same lines as the positioning given in the
properties now.

If the scope IS to only replace <img> then I can see why this is out of
scope for the component, but then I ask is the
background image you can supply for a v-card can be extended to allow for
more than one image and for those images to be able to be positioned around
the card.
ie: Currently the background image takes up the entire background - what if
I want more than one image?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
