### ISSUE TITLE
[Bug Report] v-autocomplete API call duplicates with cacheitems enabled.

### ISSUE THREAD

**Issue by julian-code** [vuetifyjs/vuetify#10847]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 10

### Steps to reproduce
Type in a players name. This is a public faceit API. Every player is unique by name.

A player name could be durum_kebab.

### Expected Behavior
With cache-items enabled I would expect that there is no duplicates.

### Actual Behavior
Duplicates of the the same player is shown.

### Reproduction Link
<a href="https://codepen.io/julian-code/pen/OJVZMRz?editable=true&editors=101" target="_blank">https://codepen.io/julian-code/pen/OJVZMRz?editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Using an object for value isn't recommended as they cannot be compared, when the items array is refreshed you get a new object and `{ foo: 'bar' } !== { foo: 'bar' }` even though the shape is the same. 

Use `this.items = res.payload.players.results` along with `<v-autocomplete item-value="id" item-text="nickname" return-object`

**Comment by jacekkarczmarczyk** [comment]
> they cannot be compared


@KaelWD looks like someone was planning to do it https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSelect/VSelect.ts#L329
