### ISSUE TITLE
[Bug Report] v-select: unexpected interaction between events and props

### ISSUE THREAD

**Issue by pmagix** [vuetifyjs/vuetify#10846]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Edge 80.0.361.66
**OS:** Windows 10

### Steps to reproduce
Use v-select with `filled` prop - changes event behaviour of resulting select in unexpected manner

### Expected Behavior
v-select event behaviour should be the same with or without `filled` prop

### Actual Behavior
`filled` prop changes event behaviour

### Reproduction Link
<a href="https://codepen.io/pmagix/pen/dyoeYwo" target="_blank">https://codepen.io/pmagix/pen/dyoeYwo</a>

### Other comments
this observation is one of many that together give the impression that the functionality of vue has been changed in order to graft vuetify onto it 
</apologies>

**Comment by johnleider** [comment]
Please ensure that this conversation is adhering to the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md). Continued violation of this can result in a locking of this issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/NWqMMZo

This happens on any enclosed `v-select`: filled, solo, solo-inverted and outlined. It was added to support the various types of input styles in the framework. Something we would like to improve next version.

https://github.com/vuetifyjs/vuetify/blob/08c503e2e6d3b10f9c9662b9386569826a258787/packages/vuetify/src/components/VSelect/VSelect.ts#L718

**Comment by johnleider** [comment]
This behavior is reflected in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
