### ISSUE TITLE
[Bug Report] outlined v-select open menu doesnt hide the select box fully

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#10859]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.13.6

### Steps to reproduce
your outlined select input should hide what is behind. if you open the page on your documentation, the very first outlined select, you can clearly see 'outlined style' underneath when the menu is open and the corners are also peaking

### Expected Behavior
hide the label and corners of select box

### Actual Behavior
does not hide

### Reproduction Link
<a href="https://codepen.io/rveruna/pen/LYVmOpX" target="_blank">https://codepen.io/rveruna/pen/LYVmOpX</a>

**Comment by valentingavran** [comment]
According to the Material Design Guidelines, the menu should be positioned below the text fields. Maybe this should be taken into account here.

https://material.io/components/menus/#dropdown-menu

**Comment by KaelWD** [comment]
https://material.io/components/menus/#behavior-figure-caption-0

**Comment by johnleider** [comment]
So it would appear we should have a default and an exposed behavior.

**Comment by johnleider** [comment]
I'm reverting this fix as it causes issues with existing behavior. It will be addressed in v3 when menu is refactored.

Revert reference: f225c5b8496a344c14d0bd525ec7ab715256f541

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
