### ISSUE TITLE
[Bug Report] Can't fill dynamic dropdowns

### ISSUE THREAD

**Issue by diamond95** [vuetifyjs/vuetify#10858]
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
https://stackoverflow.com/questions/60694972/fill-with-values-dynamic-dropdowns

### Expected Behavior
Fill selected dropdown with values from server

### Actual Behavior
No data available

### Reproduction Link
<a href="https://codepen.io/proofzy/pen/zYGjEBo" target="_blank">https://codepen.io/proofzy/pen/zYGjEBo</a>

### Other comments
Sometimes on hot reload it works, but after refreshing site and selecting dropdown, nothing happens.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
