### ISSUE TITLE
[Bug Report] Content behind overlay scrolling

### ISSUE THREAD

**Issue by dakshshah96** [vuetifyjs/vuetify#10856]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.0

### Steps to reproduce
Scroll when an overlay is open on top of a large body of text.

### Expected Behavior
Content should not scroll when an overlay is open.

### Actual Behavior
Content scrolls even when an overlay is open.

### Reproduction Link
<a href="https://codepen.io/dakshshah/pen/xxKWLgb" target="_blank">https://codepen.io/dakshshah/pen/xxKWLgb</a>

**Comment by johnleider** [comment]
@vuetifyjs/core-team This is something that exists within the detachable mixin but was never handled by the overlay. Thoughts on this issue as a whole?

**Comment by dakshshah96** [comment]
@johnleider Thanks for taking a look at this!

Meanwhile, is there a workaround to prevent the background content from scrolling while the overlay is open? Really need this for an app I’m building 🤞

**Comment by johnleider** [comment]
You could import and manually call the methods on overlayable:

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/overlayable/index.ts#L215

**Comment by KaelWD** [comment]
Resolved by #13681
