### ISSUE TITLE
Feature request: swiper

### ISSUE THREAD

**Issue by canhongpoxiao** [vuetifyjs/vuetify#1085]
- What will it allow you to do that you can't do today?
     Cant swipe page in mobile.
  - How will it make current work-arounds straightforward?
     Add swiper.

**Comment by canhongpoxiao** [comment]
Sorry I find this solution for #931.
And can add touch event control for components api ?
If you do, it's great for mobile.

**Comment by johnleider** [comment]
Touch is a directive, you can simply use it like you would any other directive. 
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
