### ISSUE TITLE
[Bug Report] Icons in small buttons aren't small

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#10851]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.3

### Steps to reproduce
Open the pen and look at the two icons in the buttons

### Expected Behavior
The icon in the small button should be small (18px font-height).

### Actual Behavior
The icon in the small button is not small (default 24px font-height). If you inspect the CSS rules you will see that there is a rule that makes it small but it's being overridden. I've observed this problem not happening in some cases (like in my dev environment) but happening when in a production build.

### Reproduction Link
<a href="https://codepen.io/douira/pen/QWbrKLr?editors=1010" target="_blank">https://codepen.io/douira/pen/QWbrKLr?editors=1010</a>

### Other comments
It also happens on the current latest Safari on macOS.

**Comment by MajesticPotatoe** [comment]
Worksif you apply the `small` prop to v-icon. can you confirm a last working version?

**Comment by douira** [comment]
Applying `small` doesn't yield the same result as letting the CSS rules style the icon as small. Setting `small` on the icon directly makes it 16px while the button being `small` makes the icon 18px. It seems the icon is supposed to be 18px when inside a small button and not 16px, otherwise this (broken) CSS rule wouldn't exist.

**Comment by MajesticPotatoe** [comment]
Thanks. What i meant was that `small` on the icon shrinks the icon to fit within the 18px, which can yield acceptable results. Was trying to triage whether it was a regression or something that never actually worked. Likely just style clashing, or order of styles issue when compiling which could use some specificity.

**Comment by douira** [comment]
Turns out, if I edit the `.v-icon.v-icon` rule in by browser to be only `.v-icon` the buttons seem to make the inner icon the right size. Idk if that will break something else or if this is just a compilation problem or a typo.

**Comment by douira** [comment]
https://github.com/vuetifyjs/vuetify/blob/cee14044d0a947f1952fd353d00770060995d494/packages/vuetify/src/components/VIcon/VIcon.sass#L14-L16
Here the rule `.v-icon.v-icon` is being specifically used to "Increased specificity to overwrite iconfont css interference" so we can't just make it `.v-icon` without breaking other things.

**Comment by ysb** [comment]
@douira could you find a solution for this. I think we have same problem. 
https://github.com/vuetifyjs/vuetify/issues/11294

**Comment by douira** [comment]
I simply set the size I want explicitly in my global CSS. I could probably use SCSS variables to make this more reactive but I didn't bother to set up SCSS for only a handful of CSS rules.
```css
/*workaround for increased .v-icon specificity, see https://github.com/vuetifyjs/vuetify/issues/10851*/
.v-btn__content > .v-icon--left,
.v-btn__content > .v-icon--right {
  font-size: 18px;
  height: 18px;
  width: 18px;
}
```

**Comment by pergpau** [comment]
Exactly the same issue here. <v-icon> inside <v-btn> are different sizes in dev and prod. Hoping for a fix.

**Comment by 1isten** [comment]
This issue also happens in <v-icon left ...> and <v-icon right>.

In dev environment the specificity of `.v-btn__content .v-icon--left, .v-btn__content .v-icon--right` is higher than `.v-icon.v-icon` so no issue.

But when build for production, the specificity of `.v-icon.v-icon` becomes higher..

**Comment by johnleider** [comment]
Closing in favor of #11294

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
