### ISSUE TITLE
[Feature Request] V-Autocomplete: Option to disable Enter-selection

### ISSUE THREAD

**Issue by wubzz** [vuetifyjs/vuetify#10854]
### Problem to solve
In my case we've decided that taborder/tabbing between fields should be possible using both TAB and ENTER. This becomes an issue with V-Autocomplete because it highlights already selected items (multiple or not) and especially when searching for values.

We've extended our component to allow browsing with navigation keys and selecting with SPACE instead of ENTER in the V-Menu that pops up.

I'm unable to find a way to disable the ENTER selection. This doesn't feel like a far-fetched edge-case since tabbing with ENTER is actually quite common to see in applications.

### Proposed solution
A new Prop to V-Autocomplete which allows you to disable the onEnterDown listener of V-Checkbox/List-item.

**Comment by johnleider** [comment]
The best suggestion I have would be to import and extend the component. Then overwrite the method that performs this specific logic.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by wubzz** [comment]
@johnleider I'm already extending the <v-autocomplete> component, but it gets a bit tedious because there are 3-4 components involved in this cycle of events, if I understand correctly.

`VAutocomplete.onKeyDown(e)` -> `VSelect.onKeyDown(e)` -> `VMenu.changeListIndex(e)` -> `this.tiles[this.listIndex].click()`

I guess overriding `VAutocomplete.onKeyDown(e)` and stop the propagation if they `keyCode` is ENTER might work..

Thanks

**Comment by Shakuray** [comment]
It seems thay @wubzz workarround is no longer working in Vuetify 3 since the `VAutocomplete` keydown event are no longer being triggered when pressing keys in the `VMenu` or `VList` rendered by `VAutocomplete`.

@johnleider there are any plans to reconsider this future request since the workaround is no longer woking? Or there is something i'm missing... 

Thank you!
