### ISSUE TITLE
[Bug Report] The checkbox works inversely

### ISSUE THREAD

**Issue by UsmanJavedAttari** [vuetifyjs/vuetify#10860]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
-1: Open up https://codepen.io/inyourface/pen/VwLxrJv
-2: Open autocomplete.
-3: Click on the text (see the checkbox, it's true)
-4: Again click on the text (see the checkbox, it's false)
-5: Now, click on the checkbox, did you see the list is selected but the checkbox is false.
-6: Again click on checkbox, the checkbox will true now, but it should false.

### Expected Behavior
The checkbox should not work inversely.

### Actual Behavior
The checkbox works inversely.

### Reproduction Link
<a href="https://codepen.io/inyourface/pen/VwLxrJv" target="_blank">https://codepen.io/inyourface/pen/VwLxrJv</a>

### Other comments
I tried to `console.log` the checkbox on `@change` and it works inversely there too.

**Comment by KaelWD** [comment]
See #9229, you have to actually update something on change, not just return a value.
