### ISSUE TITLE
[Bug Report] Vuetify Navigation Drawer : ExpandOnHover bug when modified from the inside of the drawer

### ISSUE THREAD

**Issue by holyris** [vuetifyjs/vuetify#10862]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.1
**Browsers:** Firefox 74.0
**OS:** Windows 10

### Steps to reproduce
-Enable expand on hover with the switch INSIDE the drawer

-Remove your mouse from the drawer (goes mini)

-Disable expand on hover with the switch INSIDE the drawer

-Enable expand on hover again (switch inside)

### Expected Behavior
v-content resizing

### Actual Behavior
v-content not resizing 

### Reproduction Link
<a href="https://codepen.io/holyris/pen/MWwGrLg?editors=1010" target="_blank">https://codepen.io/holyris/pen/MWwGrLg?editors=1010</a>

### Other comments
You can try the steps with the switch OUTSIDE the drawer, there will be no bug

**Comment by johnleider** [comment]
Happens in Chrome 80 as well.

**Comment by CharlesFresquet** [comment]
This issue is still happening with v2.3.23 and v2.4.1.

**Comment by AlexDaniel** [comment]
Yep, it is still an issue.

**Comment by tonioo** [comment]
Same here.

**Comment by alikamrani** [comment]
i have the same problem and it still not working

**Comment by AlexDaniel** [comment]
@alikamrani see https://github.com/vuetifyjs/vuetify/issues/8223#issuecomment-776656707 for a workaround to a related bug. At least nowadays I have no issues with the navigation drawer and that workaround applied.  Also:

> This is handled differently in v3 and is no longer an issue.

I haven't tried switching to v3 yet, so can't tell, but I guess it's a matter of time for everyone to do the switch. If it's fixed there then I guess no problem.
