### ISSUE TITLE
[Bug Report] v-navigation-drawer mini variant no longer stays mini

### ISSUE THREAD

**Issue by musicteachj** [vuetifyjs/vuetify#10861]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 1.5.4
**Vue Version:** 2.6.8
**Browsers:** Chrome 80.0.3987.116
**OS:** Mac OS 10.13.6

### Steps to reproduce
v-navigation drawer with mini-variant, added v-list-group and v-list-item(s).

### Expected Behavior
The mini variant used to stay mini when displaying sub menu items.

### Actual Behavior
The mini-variant v-navigation-drawer expands to full width when displaying sub items for nav

### Reproduction Link
<a href="https://codepen.io/MinorFourChord/pen/xxGjpvR?editors=1010" target="_blank">https://codepen.io/MinorFourChord/pen/xxGjpvR?editors=1010</a>

### Other comments
Was this functionality excluded from 2.0? This is working in our 1.5 environment.

**Comment by MajesticPotatoe** [comment]
Currently your reproduction doesn't display what you are describing ( doesn't have a `v-list-group` with sub menu items )

**Comment by musicteachj** [comment]
@MajesticPotatoe code has been updated.
