### ISSUE TITLE
[Feature Request] Prevent close on click (Expand on hover) 

### ISSUE THREAD

**Issue by tday0501** [vuetifyjs/vuetify#10872]
### Problem to solve
Prevent the navigation draw from closing with the prop expand on hover, if you click say a menu that's in the nav draw, then once you click on the menu the nav closes back down?

### Proposed solution
Not sure

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
