### ISSUE TITLE
[Bug Report] @click event does not work in v-timeline-item

### ISSUE THREAD

**Issue by mtsbarbosa** [vuetifyjs/vuetify#10874]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.3

### Steps to reproduce
When you click in one of the timelines the click event is not triggered over timeline-items

### Expected Behavior
I would expect to have click available on it

### Actual Behavior
It does not trigger the click event

### Reproduction Link
<a href="https://codepen.io/mtsbarbosa/pen/qBdKaZW" target="_blank">https://codepen.io/mtsbarbosa/pen/qBdKaZW</a>

### Other comments
I know I can add a card or a button, or an anchor, or whatever, but I would like to have the click working in the whole line

**Comment by MajesticPotatoe** [comment]
`v-timeline-item` does not have a click event. You can use the `.native` modifier to obtain this effect.
Also your reproduction is not properly setup
<https://codepen.io/majesticpotatoe-the-bashful/pen/abOKmmg>

**Comment by mtsbarbosa** [comment]
thank you @MajesticPotatoe
