### ISSUE TITLE
[Bug Report] <v-card-action> background disappears in <v-dialog> when using <v-list-item> inside <v-card> component

### ISSUE THREAD

**Issue by marcelobfonseca** [vuetifyjs/vuetify#10873]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.13.6 High Sierra

### Steps to reproduce
Create a `<v-dialog>` component and add `<v-card>`. Inside the `<v-card>` add `<v-list-item-group>` and  `<v-list-item>` components. If the `<v-card>` in this Dialog does have a `<v-card-action>` component, its background will be shifted away and be transparent after a certain amount of elements in `<v-list-item>`. 

### Expected Behavior
`<v-card-action>` component maintains its normal background color

### Actual Behavior
`<v-card-action>` background disappears and remains transparent

### Reproduction Link
<a href="https://codepen.io/marcelobbff/pen/poJKyaJ?editable=true&editors=101" target="_blank">https://codepen.io/marcelobbff/pen/poJKyaJ?editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
scrollable dialog requires specific structure of the contents, nothing to do with v-list-item-group etc

https://codepen.io/jkarczm/pen/PoqaWKw?editors=1000

Correct structure:

https://codepen.io/jkarczm/pen/rNVKjzJ?editable=true&editors=101

**Comment by marcelobfonseca** [comment]
thanks @jacekkarczmarczyk  I'll be closing this issue
