### ISSUE TITLE
[Bug Report] vcombobox looks focused after focus() call for next field

### ISSUE THREAD

**Issue by bob-lee** [vuetifyjs/vuetify#10881]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
- select any option on vcombobox
- focus moves to next field ok but..

### Expected Behavior
vcombobox loses all focus-related styles.

### Actual Behavior
vcombobox still looks focused having classes like `v-input--is-focused` and `primary--text`, etc.

### Reproduction Link
<a href="https://codepen.io/bob-lee/pen/wvaXRWd" target="_blank">https://codepen.io/bob-lee/pen/wvaXRWd</a>

### Other comments
I handles `@change` event on vcombobox to move focus to next field when user selects any option. What's the concrete way to make vcombobox unfocused? I tried `blur()` but it complaints `is not a function`.

**Comment by ElijahKotyluk** [comment]
Got the combobox to unfocus by using `blur()` after you `focus()` on field2, something for now.

``` ts
...
  methods: {
    selected(e) {
      console.log('selected', e)
      const next = this.$refs[`field2`]
      next && next.focus()
      this.$refs[`combo1`].blur()
    },
...
```

**Comment by bob-lee** [comment]
@ElijahKotyluk indeed, it works and it was my bad (reproduction link updated to show it work as expected). I actually had a custom component that is using vcombobox inside and my form was trying to call focus/blur. So it was a matter of adding `blur` method to my component so that parent can call it as required:
```js
    blur() { // <-- added
      this.$refs.me.blur()
    },
    focus() {
      this.$refs.me.focus()
    },
```
Closing the issue
