### ISSUE TITLE
[Feature Request] v-datatable click:row event should not fire event when selecting text

### ISSUE THREAD

**Issue by majorius** [vuetifyjs/vuetify#10887]
### Problem to solve
When selecting text and releasing the mouse button on table element - rowClick event should not fire.

### Proposed solution
Disable event firing if any text in the table is selected, or a hacky one - calculate delay between mouseDown and mouseUp to see if it's a select event or a click.

**Comment by KaelWD** [comment]
This works the same as `@click` on any other element. If you want different behaviour when text is selected you should use `if (!getSelection().isCollapsed)` in your event handler.
