### ISSUE TITLE
Tooltip on icon does not show the lower case letters. 

### ISSUE THREAD

**Issue by waqasraz** [vuetifyjs/vuetify#1088]
### What is expected?
ToolTip text to show.

### What is actually happening?
ToolTip text does not show for lower case letters and numeric digits.

### Reproduction Link
https://codepen.io/waqasraz/pen/ZJzpaz

**Comment by johnleider** [comment]
You cannot use v-tooltip directly on v-icon due to how icon libraries work. https://codepen.io/johnjleider/pen/EvYvga
I've also added information to the documentation regarding this.
