### ISSUE TITLE
[Documentation] Theme generator link in themes section broken

### ISSUE THREAD

**Issue by chosamuel** [vuetifyjs/vuetify#10882]
### Environment

**Browsers:** Mobile Safari 12.1.1
**OS:** iOS 12.3.1

### Steps to reproduce
Go to themes section, click themes generator tool link.

### Expected Behavior
Expected to see a theme generator

### Actual Behavior
404

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/theme/https:/theme-generator.vuetifyjs.com/" target="_blank">https://vuetifyjs.com/en/customization/theme/https:/theme-generator.vuetifyjs.com/</a>

**Comment by MajesticPotatoe** [comment]
For now you can access this via the toolbar (under Ecosystem)

**Comment by MajesticPotatoe** [comment]
resolved in 3ba2dd4
