### ISSUE TITLE
[Feature Request] Data Tables - groupable prop

### ISSUE THREAD

**Issue by SimplyUnnamed** [vuetifyjs/vuetify#10889]
### Problem to solve
Currently, you can define what columns are sortable, visable, and even filterable. This suggestion would allow users to specify which columns are groupable.

### Proposed solution
Add a header property 'groupable' to take a boolean which would dictate if the table can be grouped by a particular column or not.

**Comment by fabricio-2Uu** [comment]
Yes, this one is pretty important. After I added action icons to each rows from my table with `show-group-by` the column became "groupable". But doesn't make sense to group on icons, except if the groups respect different icons, but not, it just group every row inside one group.

**Comment by johnleider** [comment]
resolved in #11361

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
