### ISSUE TITLE
[Feature Request] Ability to change font size of DataTable

### ISSUE THREAD

**Issue by Mashiane** [vuetifyjs/vuetify#10885]
### Problem to solve
One is able to increase or decrease the font of the overall table.

### Proposed solution
Font Name / Font Size Property for  DataTable

**Comment by basselAhmed** [comment]
You can easily change font-family and font-size via CSS, no need for props.

**Comment by MajesticPotatoe** [comment]
Note: Can also be changed globally using SASS variables
