### ISSUE TITLE
[Bug Report] Input change event triggers twice inside a V-Text-Field

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuetifyjs/vuetify#10883]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 82.0.4085.12
**OS:** Windows 10

### Steps to reproduce
write text, press enter and blur.

### Expected Behavior
Write text and then press enter increases g to 1. Change focus does nothing to g.

### Actual Behavior
Write text and then press enter increases g to 1. Change focus increases g to 2

### Reproduction Link
<a href="https://codepen.io/arvanoid/pen/KKpBpvj" target="_blank">https://codepen.io/arvanoid/pen/KKpBpvj</a>

**Comment by YipingRuan** [comment]
What should be the expected behavior, for
Write text and then press enter increases g to 1. Then press enter again?

**Comment by KaelWD** [comment]
Duplicate of #10477
