### ISSUE TITLE
[Bug Report] Icon pseudo element causing container overflow

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#10899]
### Environment
**Vuetify Version:** 2.2.18
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Open the codepen, see the container overflow

### Expected Behavior
The container should not overflow

### Actual Behavior
The container overflows

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/JjdBeGr" target="_blank">https://codepen.io/johnjleider/pen/JjdBeGr</a>

### Other comments
This was caused by f85f3283b87f927e6e81d793a9405c99ecbfe8fb .

The transformed pseudo element causes the container to overflow.

Side note: this should move under `v-icon--link` as it would only apply then.

**Comment by fpdrozd** [comment]
`v-input__append-inner` has no space on the right side so the ::after element overflows the whole select. What about adding padding right to it?

Paste to the pen:
```
.v-input__append-inner {
  padding-right: 4px
}
```

**Comment by johnleider** [comment]
> `v-input__append-inner` has no space on the right side so the ::after element overflows the whole select. What about adding padding right to it?
> 
> Paste to the pen:
> 
> ```
> .v-input__append-inner {
>   padding-right: 4px
> }
> ```

It still has issues when it rotates.

**Comment by johnleider** [comment]
This is no longer relevant and not an issue in v3.
