### ISSUE TITLE
[Bug Report] Masks cannot be implemented in Typescript 

### ISSUE THREAD

**Issue by andreixk** [vuetifyjs/vuetify#10891]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. create a new project with TypeScript enabled
2. add Vuetify
3. install vue-the-mask
4. Import vue-the-mask

### Expected Behavior
able to use `v-mask` directive

### Actual Behavior
Import fails - no typescript support by vue-the-mask

### Reproduction Link
<a href="https://codepen.io/andreixk/pen/PoqBmpe" target="_blank">https://codepen.io/andreixk/pen/PoqBmpe</a>

**Comment by ElijahKotyluk** [comment]
I think this is a feature request for [vue-the-mask](https://github.com/vuejs-tips/vue-the-mask). They currently have a [closed issue](https://github.com/vuejs-tips/vue-the-mask/issues/113#issuecomment-527382940) for TypeScript support with a possible temporary solution.

**Comment by andreixk** [comment]
I think the onus is on both systems. Vuetify states it has typescript support, it also directs users to use vue-the-mask plugin (since you removed the feature from Vuetify). 
As such, one would expect that any examples you provide will work. If an example doesn't work, then you either need to remove the example or fix the code.
