### ISSUE TITLE
null values break Datatable sorting

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1089]
> [Vue warn]: Error in render function: "TypeError: Cannot read property 'toLocaleLowerCase' of null"

**Edit:**

I'm sorry. I was on a deadline and just left the barebones to the issue here to come back later. There is actually not much more to it, but here's a codepen:

https://codepen.io/keystorm/pen/OjLQYP

If the null value was on the first column, the table wouldn't render at all. If it's not the first column, sorting won't work as it seems to try to `null.toLocaleLowerCase()`

### Versions
Vue 2.4.2
Vuetify 0.14.5
Chrome 59, OS X 10.11

### What is expected ?
`null` values provided as data in columns should not cause render or runtime error when fed to a DataTable.

### What is actually happening ?
DataTable won't render if `null` is found on first column. DataTable won't sort any column if `null` is present.

### Reproduction Link
https://codepen.io/keystorm/pen/OjLQYP

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by keystorm** [comment]
Sorry, issue fixed.

**Comment by keystorm** [comment]
@johnleider Could you reopen this issue so it can get the proper visibility? Maybe someone else has encountered this and has something to add to it.

Thanks.

**Comment by johnleider** [comment]
Sure thing, as soon as the required boilerplate is used.

**Comment by ThunderAnkh** [comment]
I have the same problem, I've created a csv import to render into a data-table but I needed to create a function to properly initialise the columns which were not providing any value, else it would be initialised into null and thus not being able to be sorted. It's only properly working when everything has a default value else than 'null'
