### ISSUE TITLE
[Bug Report] VSwitch or VCheckBox inside of VListItemGroup with disabled ripple disables input

### ISSUE THREAD

**Issue by GreenVirs** [vuetifyjs/vuetify#10893]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Edge 82.0.453.2
**OS:** Windows 10

### Steps to reproduce
Click switch several times

### Expected Behavior
Switch toggles each time clicked and its value changes

### Actual Behavior
Switch is disabled. It changes position at first click, but value stays the same.

### Reproduction Link
<a href="https://codepen.io/GreenVirs/pen/BaNPrdB" target="_blank">https://codepen.io/GreenVirs/pen/BaNPrdB</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
