### ISSUE TITLE
[Feature Request] Custom tag with default href attribute using routable mixin

### ISSUE THREAD

**Issue by yhortuk** [vuetifyjs/vuetify#10908]
### Problem to solve
Currently when you pass href attribute it always use 'a' tag even when there is custom tag option passed

### Proposed solution
Add additional condition to support usage of custom tag with default href attribute passed inside custom tag. 

Use case example:
```
 <v-breadcrumbs-item  tag="inertia-link" href="/home"> Home</v-breadcrumbs-item>
```

Posible code solution:
https://github.com/vuetifyjs/vuetify/blob/52c92983af5706bfae5f0efa7fd7c48ecfc55bd8/packages/vuetify/src/mixins/routable/index.ts#L129
```
        tag = (this.href && !this.tag) && 'a' || this.tag || 'div';
        if (tag !== 'div' && this.href) data.attrs.href = this.href;
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
