### ISSUE TITLE
[Bug Report] Can't clear v-text-field functionaly !

### ISSUE THREAD

**Issue by farshidrezaei** [vuetifyjs/vuetify#10901]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Reproduction Link
<a href="https://codepen.io/farshidrezaei/pen/RwPBELW" target="_blank">https://codepen.io/farshidrezaei/pen/RwPBELW</a>

I set `keyup.enter` event to clear field. then press Enter. Everything is true. but click outside of the textbox. typed text will come back.

I can't clear text field functionaly by using:
` $event.target.value=''`

**Comment by KaelWD** [comment]
```js
this.$nextTick(() => this.searchQuery = '')
```

**Comment by farshidrezaei** [comment]
@KaelWD thank you for answer.
 but what's mean of `this.$nextTick(() => this.searchQuery = '')` ?

**Comment by Akari1987** [comment]
here is my solution

- add ref to v-text-filed
<v-text-field ref="hoge">

-  this.$refs.hoge.lazyValue === ''

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
