### ISSUE TITLE
[Feature Request] OnCollapse & OnExpand Methods for ExpansionPanels

### ISSUE THREAD

**Issue by Mashiane** [vuetifyjs/vuetify#10902]
### Problem to solve
I would like to save the state on the expansion panel including the collapsed or expanded states for each panel, so that I can set the state back at some stage. Is there a way to do this currently?

### Proposed solution
Ability to detect oncollapse and onexpand states of expansion panels.

**Comment by jacekkarczmarczyk** [comment]
State is stored in `v-expansion-panels` `v-model`, you can use localStorage/database/whatever to persist it

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
