### ISSUE TITLE
[Feature Request] Hi~Guys,  can “on-icon & off-icon ” attributes be supported when V-select with "multiple" ? thx~~

### ISSUE THREAD

**Issue by waynerQiu** [vuetifyjs/vuetify#10904]
### Problem to solve
 custom my icons!

### Proposed solution
like v-checkbox support "on-icon & off-icon" (#^.^#)

**Comment by KaelWD** [comment]
This is a very vague request, you should just v-bind the icon you want with some condition.

**Comment by waynerQiu** [comment]
can “on-icon & off-icon ” attributes be supported when V-select with "multiple" ?
vague ??

**Comment by KaelWD** [comment]
Yes it is vague, are you referring to the dropdown arrow on the right? You can just bind `:append-icon="selected.length ? 'on' : 'off'"`

**Comment by jacekkarczmarczyk** [comment]
i guess it's about this:
![image](https://user-images.githubusercontent.com/15625235/77244087-04a94700-6c44-11ea-8eaf-bdbf5dc6b0b9.png)

**Comment by waynerQiu** [comment]
> Yes it is vague, are you referring to the dropdown arrow on the right? You can just bind `:append-icon="selected.length ? 'on' : 'off'"`

check or no-check's icon is default when V-select with multiple,but how custom check or no-check's icon？

**Comment by waynerQiu** [comment]
> i guess it's about this:
> ![image](https://user-images.githubusercontent.com/15625235/77244087-04a94700-6c44-11ea-8eaf-bdbf5dc6b0b9.png)

you “guessed” my thoughts  ，
how custom check or no-check's icon？

**Comment by jacekkarczmarczyk** [comment]
You need to use `item` slot to provide the whole content (list item markup, icon, text etc)

**Comment by KaelWD** [comment]
Or set `checkboxOn` and `checkboxOff` if you want normal checkboxes to change too. 

https://vuetifyjs.com/en/customization/icons/#using-custom-icons

**Comment by waynerQiu** [comment]
> Or set `checkboxOn` and `checkboxOff` if you want normal checkboxes to change too.
> 
> https://vuetifyjs.com/en/customization/icons/#using-custom-icons

thx~
but i use @mdi/js, not font icon, 
@mdi/js not to support that

**Comment by waynerQiu** [comment]
> You need to use `item` slot to provide the whole content (list item markup, icon, text etc)

thank u very much~~
but ~  kill me please~~

**Comment by waynerQiu** [comment]
> You need to use `item` slot to provide the whole content (list item markup, icon, text etc)

> Or set `checkboxOn` and `checkboxOff` if you want normal checkboxes to change too.
> 
> https://vuetifyjs.com/en/customization/icons/#using-custom-icons

OK, I refactor my application using font icons, this seems to be the only way to do it. Thank you guys ~

**Comment by Tobeyforce** [comment]
@jacekkarczmarczyk Any chance that you could provide an examlpe?
I can't seem to figure out how I'd trigger the icon switch from inside the item slot.
Thanks!

**Comment by jacekkarczmarczyk** [comment]
@Tobeyforce if you mean `item` slot example then there is one on autocompletes page https://vuetifyjs.com/en/components/autocompletes/#item-and-selection

**Comment by Tobeyforce** [comment]
THanks @jacekkarczmarczyk, I ended up getting a reply on SO here:
https://stackoverflow.com/questions/67792831/vuetify-change-checkbox-icon-in-v-select-v-combobox/67793551#67793551
What do you think about that solution?

**Comment by Scaffale** [comment]
I know it's a little late, but I managed it by [overriding aliases](https://vuetifyjs.com/en/features/icon-fonts/#creating-a-custom-icon-set) for vuetify [default icons](https://vuetifyjs.com/en/features/icon-fonts/#built-in-aliases) in vuetify options.
