### ISSUE TITLE
[Feature Request] Add 'borderless' or some other named style for inputs. Acts like the 'default' but without the border.

### ISSUE THREAD

**Issue by hamishjohnson** [vuetifyjs/vuetify#10916]
### Problem to solve
For nice, quick, minimal inputs i've been using flat solo inputs, however that inherits solo's '--enclosed' modifier, which adds padding.

I was thinking of recommending that flat solo inputs don't inherit this but I think it makes more sense if 'borderless' acts more like the 'default' style which also has the nice animated labels as well as no padding.

### Proposed solution
Add another input style similar to default but without the border.

**Comment by magpiedigital** [comment]
I'm currently fixing this with this css

`.borderless-input > .v-input__control > .v-input__slot::after, .borderless-input > .v-input__control > .v-input__slot::before {
  content: none;
}`

Just add 'borderless-input' to any default input

**Comment by johnleider** [comment]
We already support a kitchen sink of options for inputs. This is a hard maybe.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
