### ISSUE TITLE
[Bug Report] v-carousel left and right icon not working on android and ios

### ISSUE THREAD

**Issue by Ruudje87** [vuetifyjs/vuetify#10918]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Other
**OS:** iOS, Android

### Steps to reproduce
installed Vue trough vue CLI
installed a seperate cordova project
installed vuetify and created a component containing a carousel
build application inside the cordova www folder
build cordova app trough phonegap build
icons on phone show squares with crosses.
```
import '@mdi/font/css/materialdesignicons.css';  in main.js

icons: {
    iconfont: 'mdi', in vuetify.js
```

### Expected Behavior
icons on phone show normal icons.

### Actual Behavior
icons on phone show squares.

### Reproduction Link
<a href="https://github.com/" target="_blank">https://github.com/</a>

### Other comments
it looks like the icon font is loaded over CDN but is not available trough the cordova app therefor i need to include the font. (but this is just a suspicion) p.s. font awesome is working:

```
import {library} from '@fortawesome/fontawesome-svg-core';
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';


Vue.component('font-awesome-icon', FontAwesomeIcon);
<font-awesome-icon :icon="['fas','search']" size="2x"/>
```

**Comment by Ruudje87** [comment]
ok, found some kind of workaround, in vuetify.js add:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faChevronLeft } from '@fortawesome/free-solid-svg-icons';

Vue.component('font-awesome-icon', FontAwesomeIcon);
library.add(faChevronLeft);
```
then use:
```
icons: {
values: {
prev: {
        component: FontAwesomeIcon,
        props: {
          icon: ['fas', 'chevron-left'],
        },
      },
```
this seems to work.

**Comment by johnleider** [comment]
I recommend using https://vuetifyjs.com/en/components/icons/#mdi-svg if you want to mimic the FA workaround you implemented.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
