### ISSUE TITLE
[Feature Request] Make VSelect emit changes when items update

### ISSUE THREAD

**Issue by Tinoooo** [vuetifyjs/vuetify#10922]
### Problem to solve
Let's say we built a component UserSelect to select users. The component contains a VSelect and stores an array containing the user data which is asynchronally fetched on runtime. Users are identified via a property called "id". The selected users can only be identified via their IDs before the selectable users (passed to VSelect via `items`) are fetched. Once they are fetched, VSelect should emit an event to the parent component to inform them about the change.

Of course, this could be done by UserSelect, but one would have to reproduce the functionalities VSelect has concerning `multiple` and `returnObject`.

#### 🦦TL;DR  try it here:

https://codesandbox.io/embed/practical-wozniak-43qb1?fontsize=14&hidenavigation=1&theme=dark

### Proposed solution
Make the VSelect emit the new values of the selected items.

**Comment by dos077** [comment]
V-select already have an event "change". It will emit the user selected value every time user changes the selected values. Is that what you are looking for? Try:
@change="debugFunction"
debugFunction(v) { console.log(v) }
and see if that's the value you want to emit?

**Comment by Tinoooo** [comment]
I get your point @dos077. But if the function that is loading the items is responsible for the update of the parent component, It needs to recreate the functionalities concerning the usage of the props `multiple` and `returnObject`. I think that would make the component less maintainable. Can you think of any other solution?

**Comment by dos077** [comment]
You are tight coupling your components that has too many levels. This is more of a programming pattern issue. Event bus or a global state (vuex) are usually the better way of handling passing data between multiple levels of components. Or if you can, simplify the nesting of your quote. Perhaps v-select should just be a direct child of the parent and you only listen to @change from the v-select after the selectable items are loaded.
The items array is a prop to v-select. To V-select it's immutable. To watch an immutable pointer without change of state is illogical.

**Comment by Tinoooo** [comment]
A global state or an event bus is not something I intend to use for my use case right now.
Listening to the events only after selected items are loaded is not very practical, since the items might change multiple times.
Why do you think the prop items should be immutable to VSelect? Doesn't that conflict with the concept of props? Usually, components react to changes of their props.

**Comment by johnleider** [comment]
After working on this for a bit and reviewing what @RobbinBaauw did, I think that it would behoove use to wait until v3 to tackle this; I'm not happy with the other results.

**Comment by KaelWD** [comment]
I don't think v-select should be responsible for this. v3 decouples items and v-model even further so having an items watcher that updates the model would be a bit of a reversal from that trend, and also unnecessary for most use cases. I suggest you keep track of the loading state in UserSelect, and trigger whatever updates you need yourself if that changes.
