### ISSUE TITLE
[Feature Request] add Outline and Text properties to snackbar component as in alert 

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10935]
### Problem to solve
this will improve snackbar UI

### Proposed solution
simply add Outline and Text properties

**Comment by johnleider** [comment]
This is being naturally done as part of a `v-sheet` update coming in v2.3

**Comment by johnleider** [comment]
resolved by #11542

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
