### ISSUE TITLE
[Bug Report] <tr> element not rendered for expanded-item slot when item slot is used in v-data-table

### ISSUE THREAD

**Issue by amadeann** [vuetifyjs/vuetify#10936]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
1. Open the codepen link
2. Expand one of the table rows by clicking on the row
3. Inspect the source of the expanded row

### Expected Behavior
The [docs](https://vuetifyjs.com/en/getting-started/releases-and-migrations/#release-notes) specify that:

> expand slot renamed to expanded-item. It no longer includes an expansion transition, **and the slot is inside the <tr> element** so that you can define your own <td> columns. To get back to a similar look as in 1.5, you will need a <td> with colspan equal to the number of columns in your header.

### Actual Behavior
This works as expected when you do not use the `item` slot in the `v-data-table`. When you use the `item` slot, the template of the `expanded-item` slot is rendered without the `tr` wrapper.

### Reproduction Link
<a href="https://codepen.io/amade/pen/zYGmXWW?editors=1010" target="_blank">https://codepen.io/amade/pen/zYGmXWW?editors=1010</a>

**Comment by ElijahKotyluk** [comment]
For now, you could wrap the template of `expanded-item` slot in a `<tr>` manually.

**Comment by amadeann** [comment]
I got a workaround :wink:. I reported it as a bug, since either the docs need to be updated, or the framework fixed to reflect the docs. Besides wrapping the `<tr>` element around `expanded-item`, Vuetify also adds the `v-data-table__expanded v-data-table__expanded__content` class to that element.

Regarding the possible fix, from what I see [this file](/src/components/VDataTable/VDataTable.ts) needs to be modified:

```
genRows (items: any[], props: DataScopeProps) {
  return this.$scopedSlots.item ? this.genScopedRows(items, props) : this.genDefaultRows(items, props)
},
```

`genDefaultRows` method wraps the `expanded-item` in `<tr>`, `genScopedRows` doesn't.

**Comment by ElijahKotyluk** [comment]
It's been labeled as a bug, just wanted to offer a work around in the case you didn't have one.

**Comment by Katsios** [comment]
A workaround would be great!

**Comment by eric-muc** [comment]
I very much like having access to the wrapping `<tr>`. This way we could have multiple expanded rows that nicely align with the table header!

**Comment by noctiweb** [comment]
Please have an option to NOT wrap as @eric-muc mentions.
It does not seem to be possible to have aligning sub-rows anymore as it we cannot use a for-loop for the expanded-item slot.

**Comment by Ali-SaZa** [comment]
Does this code work on vuetify:^3.3.10?
