### ISSUE TITLE
[Feature Request] Weekly Calendar Next() and Prev()

### ISSUE THREAD

**Issue by MehrdadKhnzd** [vuetifyjs/vuetify#10931]
### Problem to solve
I'm currently using a weekly calendar in combination with a daily calendar. The user can select the week's day from the weekly calendar and see its details in the daily calendar. I want the ability that the user can go to next or previous week, but the `v-calendar-weekly` doesn't have a `next()` or `prev()` method and there's no easy and proper way for me to achieve this.

### Proposed solution
It should simply have the `next()` and `prev()` functions, just like a normal calnedar.

**Comment by stephenhoran** [comment]
@MehrdadKhnzd you could use `<v-calendar>` with the `type=week` prop to gain access to the next and prev functions. Taking a look at the source code they are the same calendar's (it loads the weekly calendar component) however `<v-calendar>` seems to wrap more logic around most of these.

**Comment by MehrdadKhnzd** [comment]
I don't want a weekly calendar, I just want a daily calendar with a day selector on the top of it. I don't have enough space for showing a whole week. I just want a selector on the top of the page so that the user can choose the selected day and view its events. I don't think that it's possible to achieve that with `v-calendar`, but if you have a solution, please tell me more. Thanks.

**Comment by stephenhoran** [comment]
@MehrdadKhnzd Maybe a small code example might be best if possible to see what you are working with. It sounds like you are dealing with limited space and if a day calendar is the end goal maybe `<v-date-picker>` might be the proper component for you to help with selecting a day.

**Comment by MehrdadKhnzd** [comment]
Yes, the end goal is a day calendar, but I want a weekly quick access bar on top of the page so that the user can quickly change the days in a week without the need to deal with something complicated like a date picker.

**Comment by ClickerMonkey** [comment]
```
<v-calendar
  type="custom-daily"
  start="currentDate"
  end="currentDate"
  @change="currentDate = $event.start"
></v-calendar>
```

That should do it.

If I've misunderstood something, please provide a visual with what you're trying to achieve.

**Comment by ClickerMonkey** [comment]
Feel free to open this back up if the above suggestion did not solve your problem.
