### ISSUE TITLE
[Bug Report] Main.sass and common.app.js is almost unused 

### ISSUE THREAD

**Issue by Sshuichi** [vuetifyjs/vuetify#10939]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.3

### Steps to reproduce
npm run dev 

open the Chrome dev tools 
Command + shift + P then type coverage 
Reload from the coverage menu, and see that there is 99.2% of main.sass unused yet loaded. 

### Expected Behavior
A way to not load it 

### Actual Behavior
It loads the unused files 

### Reproduction Link
<a href="https://codepen.io/Ssuhuicchi/pen/GRJwRzY" target="_blank">https://codepen.io/Ssuhuicchi/pen/GRJwRzY</a>

### Other comments
Please remove unused code

![image](https://user-images.githubusercontent.com/5939429/77556191-9974a480-6ed1-11ea-8cc7-4f27fefd163b.png)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/customization/a-la-carte

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
