### ISSUE TITLE
[Bug Report] Custom group throws t.map is not a function

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#10937]
### Environment
**Vuetify Version:** 2.2.19
**Last working version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Create a datatable with a custom group function

### Expected Behavior
Datatable to group data according to the return value of the function

### Actual Behavior
[Vue warn]: Error in render: 'TypeError: t.map is not a function

### Reproduction Link
<a href="https://codepen.io/majesticpotatoe-the-bashful/pen/RwPeXGv" target="_blank">https://codepen.io/majesticpotatoe-the-bashful/pen/RwPeXGv</a>

Working codepen (2.2.18)
<a href="https://codepen.io/majesticpotatoe-the-bashful/pen/KKpGjYp" target="_blank">https://codepen.io/majesticpotatoe-the-bashful/pen/KKpGjYp</a>

**Comment by MonsieurTa** [comment]
Having the same problem no matter what's the return value of the custom group function.
Is the custom-group props usable in any other context ?

**Comment by ghyath5** [comment]
Same problem here!!!
Any solutions ?

**Comment by ech0-de** [comment]
I stumbled upon the same problem and checked the VDataTable code for a solution. In 6471332a6ded4f069152f84dc16cbaec7a754d5c the type that should be returned by the custom group function has changed from an Object to an Array of Objects with a `name` and `items` attribute.

Here is a working codepen with the new version:
https://codepen.io/ech0/pen/RwrYJzo

If the changes were intended, only the documentation would have to be updated.
