### ISSUE TITLE
[Feature Request] Allow camelCase column of a data-table to be customized using a kebab-case slot

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuetifyjs/vuetify#10934]
### Problem to solve
When the Api (data-table items) uses camelCased props I wanted to be able to customize the columns.

See an example here https://codepen.io/arvanoid/pen/NWPdgNQ

### Proposed solution
Data-table shouldbe able to map kebab-case slots to camelCase props.

**Comment by MajesticPotatoe** [comment]
You can use camelCase slot names just not in DOM templates as they are normalized to all-lowercase by the browser. See this thread: #10002
Heres a working example <https://codepen.io/majesticpotatoe-the-bashful/pen/jOPeoXv>
