### ISSUE TITLE
[Bug Report] v-menu prop fixed does not apply styles

### ISSUE THREAD

**Issue by fredicious** [vuetifyjs/vuetify#10946]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.3

### Steps to reproduce
The documented prop "fixed" does not work, and after looking into the component it looks like this prop is not implemented: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.ts#L59

### Expected Behavior
Docs should only mention props that exist.

### Actual Behavior
Docs mention the prop "fixed" which is not existing/working.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/menus/" target="_blank">https://vuetifyjs.com/en/components/menus/</a>

**Comment by MajesticPotatoe** [comment]
`fixed` is a valid prop on `v-menu`. You wont see it in the code defined in the code of v-menu because its inherited from the `positionable` mixin. As for whether it actually does anything, it doesn't look like it we actually apply or do any styling with it.

**Comment by fredicious** [comment]
Thanks for the quick reply, I just started looking into the inherited props.
In that case I guess it's not a documentation issue, thanks for updating the title.

**Comment by KaelWD** [comment]
Positionable was originally for `<v-btn fab>`, v-menu never had a `fixed` prop. We should be using `positionableFactory(['top', 'right', 'bottom', 'left'])` as the other two props do nothing.
