### ISSUE TITLE
[Bug Report] elevation-0 class adds shadow

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#10948]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.10
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.13

### Steps to reproduce
adding class elevation-0 doesnt remove box shadow completely, it just ads very tiny shadow. it should be zero

### Expected Behavior
box-shadow: initial

### Actual Behavior
.v-application .elevation-0 {
  box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 0px rgba(0, 0, 0, 0.14), 0px 0px 0px 0px rgba(0, 0, 0, 0.12) !important;
}

### Reproduction Link
<a href="https://codepen.io/rveruna/pen/jOPQpZR" target="_blank">https://codepen.io/rveruna/pen/jOPQpZR</a>

**Comment by KaelWD** [comment]
This was copied from MDC: https://material-components.github.io/material-components-web-catalog/#/component/elevation

**Comment by rveruna** [comment]
Thanks for the answer. It's a strange behaviour in my opinion, ill just have to override then. thanks for looking into it

**Comment by KaelWD** [comment]
Does it actually cause a problem? It isn't visible for me.

**Comment by rveruna** [comment]
Yes, if you use it on anything that has border radius - fab buttons, cards with radius etc. I sent a tweet to material design, not sure they even noticed that shadow, as their examples are all sharp corner rectangles, where the shadow 'hides' behind the element. 
I am using it here on the card, and you can see just a smidget of shadow in top left and bottom left corner 

![Screen Shot 2020-04-11 at 14 52 38](https://user-images.githubusercontent.com/15161568/79045691-49e9e480-7c04-11ea-90e4-50f8435d15e1.png)

Also if you open my codepen from above, you can see it being quite noticeable 

![Screen Shot 2020-04-11 at 14 56 18](https://user-images.githubusercontent.com/15161568/79045756-a0572300-7c04-11ea-9db8-6f4f4f6935f1.png)

**Comment by KaelWD** [comment]
Ah interesting, it's only visible in firefox.

**Comment by julienreszka** [comment]
> Thanks for the answer. It's a strange behaviour in my opinion, ill just have to override then. thanks for looking into it

Hi @rveruna did you manage to override it?
