### ISSUE TITLE
[Documentation] Add Vue.use(Vuetify) statement to Unit Testing code example

### ISSUE THREAD

**Issue by reilue** [vuetifyjs/vuetify#10943]
### Environment

**Browsers:** Firefox 74.0
**OS:** Linux x86_64

### Steps to reproduce
Go to https://vuetifyjs.com/en/getting-started/unit-testing/

`test/CustomCard.spec.js` snippet code

### Expected Behavior
```
Vue.use(Vuetify)
```

### Actual Behavior
Statement missing.

So, test fail

```
[Vue warn]: Unknown custom element: <v-text-field>

```

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/unit-testing/" target="_blank">https://vuetifyjs.com/en/getting-started/unit-testing/</a>

### Other comments
Why i made this issues?, cause it took me a while (couple hours) that i need to write down such statement to actually run a test, using Nuxt.

If it's possible i would like to contribute by adding such statement into the docs!. Just let me know what to do. 😉

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/unit-testing/#bootstrapping-vuetify

**Comment by reilue** [comment]
One thing that i dont get quite well is, how can i define using as utils?. If you can provide an example, it would be helpful. Thanks!
