### ISSUE TITLE
Error class persists on v-text-field with 'required' attribute

### ISSUE THREAD

**Issue by d-levin** [vuetifyjs/vuetify#1094]
### Steps to reproduce

1. Create a v-text-field with the 'required' attribute
2. In v-model, pass in a variable that contains an empty string ("")
3. Refresh the page; the text-field has no error class applied
4. Enter a value
5. Reset the variable back to an empty string (e.g. by using a button to trigger a clear method)
6. The error class persists on the text-field

### Versions

"vuetify": "^0.14.5"
"vue": "^2.4.1"
MacOS 10.12.5
Chrome 59

### What is expected ?

The error class should be removed from the text-field since the variable is cleared

### What is actually happening ?

The error class persists on the text-field

### Reproduction Link

https://codepen.io/anon/pen/dzbzyM

**Comment by ChavaSobreyra** [comment]
I'm not sure this is a bug. It's probably an enhancement. 

Vuetify's validation logic is simple in that it validates upon blur. So when you enter a value and then back it out, it doesn't do validation. The reason it turns red when you click `clear` is that the input loses focus. 

In a normal use case, this logic works well enough. If a user skips over a required field it should turn red. However, when implementing a "clear" button, one wouldn't expect required fields to turn red.

**Comment by nekosaur** [comment]
If a field is required, then of course it will error out on an empty input. Am I missing something?

**Comment by ChavaSobreyra** [comment]
What he's expecting is that 'clearing' or resetting a form should return the form to a pristine (unvalidated) state.

**Comment by nekosaur** [comment]
hmm

**Comment by Nartub600** [comment]
Could there be a way to set hasFocused to false again?

**Comment by d-levin** [comment]
We can mark this as an enhancement if you think that's better. I'd love a way to reset the validation. When you initially load the page and the field is empty, validation has not yet been trigged. I want a way to get back to that state without reloading the page..

**Comment by johnleider** [comment]
This is something that is being work on the validation branch.

**Comment by nekosaur** [comment]
This has been added in dev.
