### ISSUE TITLE
[Bug Report] Add error state/color to input field when disabled and error-message is given

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#10950]
### Environment
**Vuetify Version:** 2.2.19
**Last working version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.3

### Steps to reproduce
Create a text field, add an error-message and add disabled attribute

### Expected Behavior
Error should render in error color (red)

### Actual Behavior
Error is rendered as hint (grey) text

![image](https://user-images.githubusercontent.com/7195563/77739062-32f6a000-7011-11ea-8cf7-0f4cab14d2ad.png)

### Reproduction Link
<a href="https://codepen.io/shinigami92/pen/XWboWxX" target="_blank">https://codepen.io/shinigami92/pen/XWboWxX</a>

### Other comments
Actual quickfix is to add 'error--text' as class (in example conditionally)

https://material.io/components/text-fields/#filled-text-field

**Comment by Shinigami92** [comment]
The error could have something to do with this:

https://github.com/vuetifyjs/vuetify/blob/dev/packages/vuetify/src/mixins/validatable/index.ts#L67-L68

**Comment by fpdrozd** [comment]
It's [this](https://github.com/vuetifyjs/vuetify/blob/dev/packages/vuetify/src/mixins/validatable/index.ts#L136-L142) prop which is used as the error message color [here](https://github.com/vuetifyjs/vuetify/blob/dev/packages/vuetify/src/components/VInput/VInput.ts#L249).

**Comment by Shinigami92** [comment]
Maybe only line 137 and 138 in validatable need to be swapped?

**Comment by johnleider** [comment]
Where within that page does the specification designate that the disable error state should look like this? I see an error state, but not a disabled error.

**Comment by Shinigami92** [comment]
@johnleider There is no direct specification.
But in v1.5 it was working and in v2 it was not.
I needed to workaround this after our customer was confused using our tool in production after we migrated to v2.
We didn't know that this was changed, and I didn't expected something like this.

Also IMO it should be displayed as error even if it is disabled, because without an error color you can't see any difference to a hint.

**Comment by fpdrozd** [comment]
Ah I didn't check the documentation. It seems to me like it can't be in two states at the same time. Meaning that when it's disabled the error message should just disappear.

**Comment by Shinigami92** [comment]
1. Why did it changed from `v1.5` to `v2`?
2. Why cant I see any difference between a `hint` and an `error`?
3. Why should a `disabled` state affect an `error-message`?
4. Is there any specification / documentation that states out that a `disbaled` input does not have an `error-state`/`error-message`?

**Comment by bhaskar-nair2** [comment]
The Boolean `disabled` attribute, when present, makes the element not mutable, focusable, or even submitted with the form. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)

I think you need to use `readonly` instead of `disabled`

**Comment by Shinigami92** [comment]
The problem with readonly is that it breaks the UX. The User cant see that the field is readonly and would try to click into the field and then would be confused why no keyboard input is taken.

**Comment by bhaskar-nair2** [comment]
>But another mutable field can trigger/add an error-message to this disabled field.
Which means that it is mutable. But I understand your point, adding a `class="grey--text"` is a way to make this work, but then that is already the workaround you specified for disabled.

**Comment by Shinigami92** [comment]
grey—text would produce the same like hint is now

**Comment by bhaskar-nair2** [comment]
Not really, if there is an `error-messages` prop attached, it will render a red field+a red hint. instead of a grey field+red hint like in your case.

**Comment by Shinigami92** [comment]
Never tested the combination

**Comment by Shinigami92** [comment]
Here a repro with v1.5

https://codepen.io/shinigami92/pen/gOabYQg?editors=1010

![image](https://user-images.githubusercontent.com/7195563/78985109-3d905980-7b28-11ea-9166-939e252da981.png)

Here you can see, that both the `label` and the `error-message` is rendered in error color

Also I have added a toggle to **simulate** fields with value empty and not empty
I added a field with `error` AND `hint` and you can see that the hint was overriden in v1.5

---

Now with v2

https://codepen.io/shinigami92/pen/BaoyBEw?editors=1010

![image](https://user-images.githubusercontent.com/7195563/78985015-0457e980-7b28-11ea-9b69-8d3e5eb648dc.png)

You cant see any difference between an `error` and a `hint`

**Comment by Shinigami92** [comment]
Here I created a **really really simplified** version of what we do in our production application
The error messages can be much more complicated and can also be influenced by information that only the server has!

https://codepen.io/shinigami92/pen/qBOEBbb?editors=1010

**Comment by johnleider** [comment]
Just because it operated that way in v1.5 doesn't mean it was correct. The specification does not call for this behavior and I don't like it either.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
