### ISSUE TITLE
[Bug Report] Selectable option not working on serverside pagination and sort

### ISSUE THREAD

**Issue by kevinrioupsq** [vuetifyjs/vuetify#10951]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Create a datatable with serverside pagination and sort,
Enable checkbox selection
Click on one of the checkboxs in the table

### Expected Behavior
Check only the selected checkbox graphically

### Actual Behavior
When checking one checkbox, all are selected but the value in the vmodel is good

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-new-vuetify-bootstrap-gs1v4" target="_blank">https://codesandbox.io/s/vue-template-new-vuetify-bootstrap-gs1v4</a>

### Other comments
Have a nice day and be happy :D

**Comment by KaelWD** [comment]
Data table items need a unique key, `id` by default. In this case you can use `item-key="name"` and it works as expected.
