### ISSUE TITLE
[Bug Report] Combobox reseting search-input

### ISSUE THREAD

**Issue by no0by5** [vuetifyjs/vuetify#10953]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 10

### Steps to reproduce
1. Enter input
2. Press Enter

### Expected Behavior
Search text should disappear.

### Actual Behavior
As logged in the console, the search text is set to empty string in handleChange and reset to the old value after it.

### Reproduction Link
<a href="https://codepen.io/no0by5/pen/zYGyqdm" target="_blank">https://codepen.io/no0by5/pen/zYGyqdm</a>

**Comment by bhaskar-nair2** [comment]
You just need to use the `$nextTick` function here
```js
handleChange(items) {
 this.$nextTick(function(){
   this.searchText = "";
   this.selected = "";
 });
}
```
