### ISSUE TITLE
[Feature Request] Sort Chip on v-combobox by arrow or drag and drop chip 

### ISSUE THREAD

**Issue by mean-cj** [vuetifyjs/vuetify#10954]
### Problem to solve
Hello vuetify team.

Current chip on v-combobox cannot sort
Now when i need to sort , I have to remove all and add again.

### Proposed solution
click chip item ,  keydown arrow left , arrow right or drag and drop 
can move chip to left or right

Thank you so much.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Revadike** [comment]
It's a shame this proposal was denied. In case anyone comes across this, I managed to make my own component:
```vue
<script setup>
  const props = defineProps({
    modelValue: {
      type: Array,
      required: true
    }
  });

  const emit = defineEmits(['update:modelValue']);

  const internalValue = ref([...props.modelValue]);
  const isDragging = ref(false);
  const draggedIndex = ref(null);

  // Watch for external changes
  watch(() => props.modelValue, newVal => {
    internalValue.value = [...newVal];
  });

  const handleChange = value => {
    emit('update:modelValue', value);
  };

  const dragStart = (event, index) => {
    isDragging.value = true;
    draggedIndex.value = index;
    event.dataTransfer.effectAllowed = 'move';
    // Need to set some data for Firefox
    event.dataTransfer.setData('text/plain', index);
  };

  const dragEnd = () => {
    isDragging.value = false;
    draggedIndex.value = null;
  };

  const drop = (event, dropIndex) => {
    event.preventDefault();
    const dragIndex = draggedIndex.value;

    if (dragIndex === dropIndex) { return; }

    const newValue = [...internalValue.value];
    const [removed] = newValue.splice(dragIndex, 1);
    newValue.splice(dropIndex, 0, removed);

    internalValue.value = newValue;
    emit('update:modelValue', newValue);
    dragEnd();
  };
</script>

<template>
  <div class="draggable-combobox">
    <v-combobox
      v-model="internalValue"
      v-bind="$attrs"
      :class="{ 'is-dragging': isDragging }"
      @update:model-value="handleChange"
    >
      <template #chip="{ item, index }">
        <v-chip
          :key="index"
          :class="{ 'dragging': draggedIndex === index }"
          draggable
          @click.stop
          @dragend="dragEnd"
          @dragenter.prevent
          @dragover.prevent
          @dragstart="dragStart($event, index)"
          @drop="drop($event, index)"
          @mousedown.stop
        >
          {{ item.title }}
        </v-chip>
      </template>
    </v-combobox>
  </div>
</template>

<style scoped>
  .draggable-combobox .v-chip {
    cursor: move;
    transition: opacity 0.2s;
  }

  .draggable-combobox .v-chip.dragging {
    opacity: 0.5;
  }

  .draggable-combobox.is-dragging .v-chip:not(.dragging):hover {
    background-color: rgba(0, 0, 0, 0.1);
  }
</style>
```

**Comment by J-Sek** [comment]
It can be simplified with `defineModel` and I added support for `closable-chips`: [playground](https://play.vuetifyjs.com/#eNqVVs1u4zYQfhXCXUAyYMubLXpR7SDBZgvsob1s0YvjAyWNbCKSqJKUdw3D794Z/lh07KRYIIhCzsz3zT+zPk60KhePfZ/tB5jkk6UulegN02CG/v65Y0y0vVSGHZmCmp1YrWTLElROIuFn2fZeki3oQGhWoZSdNmzPmwHYiiDS9Wb63C0XjgcZ8GCg7RtuwPIt93M0Mlx0oOwFXpUI6f5kbD9vZQXN6nliUZ8nQdAOjRF9A2dFrgTvDCrKwTQIV426ZSM1LxqYlzvR63CLTpSwk00FCq2+QQMlZkK2YHai247WuUCPNaqsj8wI00DOEs55MnOB5uyOnWaYsSArimKUfbqUlWU5yn5lp02gWdjc2PB7BffHo8/i6bRc0IXN1eIyWctFlMrJzNY2lONniztWz+Ybq1dBjTx/0ik9OtfMoUe3H5Xih5m7UfDvIBRUOTNqAH+Jlhyrk7N0ylb3bL2x9ydshJEFWmHOJF/woNN1MvQVBpNbD/6h8BPqntFI6CfFt1usju+umjcaUCUoVCSG6mtXwQ+v0g1NcwGy413VwGf8bKlJfbPeMx8jOZbe8MRXzZKdYjzi/GY45nXFUthDZ2ZMkAM2eI86ep6F6aCE+XxFXp/FFsK7RKAZOsT/VrzTNagM6hq79bFp5HeoUDtp5d6NILbSgv0FeGskld52NCNjVkvF/sBq1fJtYLR4wnOaGPhhFthcosPQXTw3Q//SEb+r9NvB2kK9Ey1V6Qa87KOk0tFaxVwuBJwQ+j65xkutp7GToSGuucPUiZqlkeaKdM90nova3QzKW3hXA81aAdWg2iCNbRuHn+m+ESWM2DN25927qeU5Z+zjDNksolf3yXbBXeTJ6X3FZRD6JkrQDRarEvxApPfWcyX2uD65pv1ns+f2qGwLWWAbTcLO3s+1XaDXe9t+x226nxfIj/cfuDFKR2s20BxZIvTckmELJXk89qdR/yGe0bkNEI3j6Q663kf0MsTGfqGXwHLRcvcNTuhnXfc0odZ4gT6+wAGt3GyePXntfeT65ULCrjoTxcbnxMaXDyUW6yXTRl644K6RTmqKd6y9K+v0EvmBoMHm2/fPTbnByfczdCVF+LeFmhafB7dLMP1wsQKv2CRlnT7vK7Zy0FDJ792r+KPyMIaPJFUvs48rvpRR6eilxNqNlY+fyqDhOtY/rdjor59UPGpzQGhdyh4qq5hdDwHLHFmYuHJQWqqcbRUvfvcPJ61XYYTsciZ7XgpzYB+zT9qK/Sy/g+xE1P+ewmPkCPLb/2Bk0SwFvLyTJj2DTvMd1ThgF7x82So5dBViNBSI2hY8xX3kf7K7aeDEzUEJon8/TjPa4fbX5j8o51+p)
