### ISSUE TITLE
Data table in dark theme

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#1095]
### Steps to reproduce
1. Use `<v-app dark>`
2. Create `<v-data-table>` inside
### Versions
vuetify: 0.14.5

### What is actually happening ?
Data table in a dark topic does not look good.
In the header and basement, the text is black, and when you hover over a line, the gray text on a light background is almost invisible

### Reproduction Link
https://codepen.io/cawa-93/pen/XarZwZ

**Comment by azaars** [comment]
**+1**
It's a very important and heavily used component in my project.
