### ISSUE TITLE
[Feature Request] Filtered Search

### ISSUE THREAD

**Issue by lukwil** [vuetifyjs/vuetify#10959]
### Problem to solve
If your trying to do a bit more advanced searching/filtering (logical) operators (AND/OR, IS/IS NOT, GREATER/SMALLER THAN) are quite handy.

### Proposed solution
GitLab offers a solution in their UI, which can be seen e.g. in the issues tab when typing in the search bar filtering for issues.
Their code is available [here](https://gitlab.com/gitlab-org/gitlab-ui/-/tree/master/src/components/base/filtered_search) with documentation [here](https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-filtered-search--default).

Such a feature would be nice if baked directly into the search of Vuetify (for example for the data table).

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
