### ISSUE TITLE
[Documentation] Multiple List Item Unexpected Behavior

### ISSUE THREAD

**Issue by VWaleek** [vuetifyjs/vuetify#10963]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
In the List item group example in the playground, when we toggle "multiple" switch on and select multiple dogs(images e.g) and then we toggle the multiple switch off, all selected dogs remain selected.

### Expected Behavior
When we change back to single selection from multiple, only one dog should remain selected.

### Actual Behavior
When we change back to single selection from multiple, all dogs remain selected.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/item-groups/" target="_blank">https://vuetifyjs.com/en/components/item-groups/</a>

**Comment by MajesticPotatoe** [comment]
The multiple prop is just a simple prop that toggles whether the component should allow multiple items to be selected. It doesn't directly modify the components value. Seems slightly edge-case-ish to be toggling a multiple prop back and forth, though this functionality can be obtained in userland, for example via a watcher like so: <https://codepen.io/majesticpotatoe-the-bashful/pen/PoqLpme>.

Ill add a basic watcher to the example that will maintain the last selected value.
