### ISSUE TITLE
[Feature Request] How to use timestamp data in v-model of v-date-picker

### ISSUE THREAD

**Issue by lz1998** [vuetifyjs/vuetify#10969]
### Problem to solve
My backend give me timestamp data, and only receive time stampdata. Hope to transfer data format automaticly.

### Proposed solution
add timestamp support

**Comment by lz1998** [comment]
Or Date?
String is not convenient.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
