### ISSUE TITLE
[Bug Report] Navigation drawer is overlapping content when its width is a string with suffix

### ISSUE THREAD

**Issue by therichkid** [vuetifyjs/vuetify#10968]
### Environment
**Vuetify Version:** 2.2.19
**Last working version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Linux x86_64

### Steps to reproduce
- Setup an application with [default application markup](https://vuetifyjs.com/en/components/application/#default-application-markup)
- Set the width of the navigation drawer to a string with a suffix (px or %) that is greater than the default value (256)

### Expected Behavior
The content should not be overlapped

### Actual Behavior
The content is overlapped

### Reproduction Link
<a href="https://jsfiddle.net/awfxome6/" target="_blank">https://jsfiddle.net/awfxome6/</a>

**Comment by ramicohen303** [comment]
Confirming this is an issue in 2.2.19 and was working properly in 2.2.18.

**Comment by Razi91** [comment]
Another example: https://codepen.io/razi91-the-selector/pen/BaNbxxq

Looks like `v-content`'s paddings are not calculated correctly when units are not just numbers. I found that `$vuetify.application.left` stays `256`.

I think the reason are changes introduced in 2.2.19 in file VNavigtationDrawer.ts:
```ts
      const width = Number(this.computedApplicationWidth)

      if (isNaN(width)) {
        return this.expandOnHover || this.miniVariant
          ? DEFAULT_MINI_VARIANT_WIDTH
          : DEFAULT_WIDTH
      }

      return width
```

previosly was:
```ts
const width = Number(this.computedWidth)
return isNaN(width) ? this.$el.clientWidth : width
```

I think old approach was better, it just used components real width, regardles of units. I don't think default values should be returned in that case.
