### ISSUE TITLE
[Bug Report] click handler not executed when clicked on clearable icon of empty text-field

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#10965]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Click on the right side of the input (the area where the clear icon is show if the clearable field has a value)

### Expected Behavior
Menu should open

### Actual Behavior
Menu doesn't open

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/OJVdJPm?editors=1010" target="_blank">https://codepen.io/jkarczm/pen/OJVdJPm?editors=1010</a>

**Comment by billsliu** [comment]
Just remove clearable, then the problem solved

**Comment by robreiss** [comment]
Hello, I would like to contribute to Vuetify. I have started work on this issue as a "good first issue"
