### ISSUE TITLE
[Bug Report] Infinet loop on v-dialog 3 times called in v-data-table

### ISSUE THREAD

**Issue by BITRU** [vuetifyjs/vuetify#10977]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Any
**OS:** Mac OS 10.15.4

### Steps to reproduce
if open dialog window called - closed 3 times (clicked on open dialog ) app get to infinet loop and make browser tab unresponsive

### Expected Behavior
normal behavior of browser

### Actual Behavior
RangeError: Maximum call stack size exceeded.

### Reproduction Link
<a href="https://codepen.io/ilq-babunashwili/pen/JjdxmOa?editors=1111" target="_blank">https://codepen.io/ilq-babunashwili/pen/JjdxmOa?editors=1111</a>

**Comment by billsliu** [comment]
v-dialog should be outside of v-table, you define same v-dialog multiple times in the same table.

-

**Comment by KaelWD** [comment]
All the dialogs are sharing the same v-model property.
