### ISSUE TITLE
[Documentation] SVG icon sample not working in codepen

### ISSUE THREAD

**Issue by billsliu** [vuetifyjs/vuetify#10970]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Go to https://codepen.io/pen/?&editable=true&editors=101 to see the MDI SVG sample from Vuetifyjs is not working.

This example is from https://vuetifyjs.com/en/components/icons/#examples

### Expected Behavior
Display the MDI SVG icon

### Actual Behavior
The page is broken

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/icons/" target="_blank">https://vuetifyjs.com/en/components/icons/</a>

### Other comments
Can you add example of how to change size of MDI SVG icon, right now it always 24*24

**Comment by MajesticPotatoe** [comment]
The example is valid code, and functions properly so in the docs. Its more of an issue with how codepen utilizes imports. If you take the example and replace:
`import { ... } from '@mdi/js'`
with
`import { ... } from '//unpkg.com/@mdi/js/mdi.js?module'`
It will load (however locally you will probably want the first)

As for changing the size, you can use one of the preset props (`x-small`, `small`, `large`, `x-large`)
or use the `size` prop.

**Comment by billsliu** [comment]
It works now, thanks very much
