### ISSUE TITLE
[Bug Report] Slide-group does not slide back when deleting items

### ISSUE THREAD

**Issue by asssc** [vuetifyjs/vuetify#10971]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.4

### Steps to reproduce
1. Add some items
2. Slide to the end using next button
3. Remove visible items using "Remove item" button

### Expected Behavior
Slide-group must slide back when you delete all visible items.

### Actual Behavior
Slide-group does not slide back when deleting items.

### Reproduction Link
<a href="https://codepen.io/asssc/pen/RwPvZOq" target="_blank">https://codepen.io/asssc/pen/RwPvZOq</a>

**Comment by thalesvideira** [comment]
Hello @asssc, 
I made a copy of your CodePen with an alternative, I had the same problem as you ... I hope this can help you.

- add a ref in the v-lit-group
`<v-slide-group show-arrows ref="chipGroup">`

- add method when deleting item (click)

`

    removeItem(){
      this.items.pop();
      setTimeout(() => {
        let chipGroup = this.$refs["chipGroup"];
        if (!chipGroup.hasNext && !chipGroup.hasPrev) { 
          this.$refs["chipGroup"].$refs.content.style = "translateX(0px)";
        }
      }, 50);
    }`


[https://codepen.io/Thalesvideira/pen/zYrMWQY](https://codepen.io/Thalesvideira/pen/zYrMWQY)

**Comment by jpcanto** [comment]
> Hello @asssc,
> I made a copy of your CodePen with an alternative, I had the same problem as you ... I hope this can help you.
> 
> * add a ref in the v-lit-group
>   `<v-slide-group show-arrows ref="chipGroup">`
> * add method when deleting item (click)
> 
> `
> 
> ```
> removeItem(){
>   this.items.pop();
>   setTimeout(() => {
>     let chipGroup = this.$refs["chipGroup"];
>     if (!chipGroup.hasNext && !chipGroup.hasPrev) { 
>       this.$refs["chipGroup"].$refs.content.style = "translateX(0px)";
>     }
>   }, 50);
> }`
> ```
> 
> https://codepen.io/Thalesvideira/pen/zYrMWQY

Eu tive esse mesmo problema, e essa solução resolveu parcialmente, gerou outro problema pq ao scrollar de volta ao inicio, é desabilitada a setinha para scrollar adiante, pq forçando o scroll por css, o componente entende que ainda está no fim do scroll.

Consegui resolver o problema dessa forma:
this.$refs.chipGroup.scrollOffset = 0;
