### ISSUE TITLE
Buttons inside a v-menu in a toolbar no longer take up the full height

### ISSUE THREAD

**Issue by bp176** [vuetifyjs/vuetify#1098]
### Versions

vue: 2.4.2
vuetify: 0.14.5

### What is expected ?
Buttons that are nested in a v-menu in a toolbar take up the full height of the toolbar like they do when not nested in a menu.

### What is actually happening ?
When I place buttons in a toolbar they take up the full height of the toolbar. I need each button to trigger a drop down menu, which works. However, when I nest the buttons in the menu, the buttons no longer take up the full height. I would expect the buttons to still look the same. See screenshot below. This shows the hover state where there is padding/margin on the top and bottom.

### Reproduction Link

![buttons](https://user-images.githubusercontent.com/10065680/28494136-dd6ff6c0-6ef3-11e7-8ee7-f3024d289534.png)

**Comment by jrast** [comment]
I can't reproduce this. The buttons are not full height in both cases.

I have created the following CodePen: https://codepen.io/jrast/pen/JyPePa

The thing i noticed: The first button has another spacing on the left side the button is used as a menu activator.

**Comment by doctoro** [comment]
Inside the toolbar wrap the buttons in <v-toolbar-items>

**Comment by jrast** [comment]
@doctoro this works for normal buttons, but not if the button is a `v-menu` activator. See the updated codepen.

**Comment by doctoro** [comment]
@jrast Hmm...maybe that's the issue being referenced? I suppose I would expect the button to display the same if nested in `<v-toolbar-items>`, whether or not the button is a menu activator.

**Comment by bp176** [comment]
@jrast Yes, I expected the button to look the same even if it was an activator. Is there another way to achieve this effect , i.e. a full height button in a toolbar with a drop down menu?

**Comment by jrast** [comment]
Might be. I think with the linked codepen, @johnleider can tell if it's a bug and what exactly is the bug.

**Comment by johnleider** [comment]
Unfortunately, this is a real edge case, as far as menu being on a regular v-btn (non icon) and will require different markup. As far as v-toolbar-items, it's intentionally there and required to achieve the desired affect.

My suggestion would be to setup your buttons and manually control your menu model as opposed to using the activator slot.

**Comment by bp176** [comment]
@johnleder Thanks. Can you explain a little what you mean by "manually control your menu model". I'm unsure of how to trigger it without an activator. The documentation shows an absolute positioning method - is that what you mean?
