### ISSUE TITLE
[Documentation] I can't watch commands of quick start

### ISSUE THREAD

**Issue by Charlyvil** [vuetifyjs/vuetify#10984]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Not neccesary 

### Expected Behavior
Watch the cli lines

### Actual Behavior
Only shows an empty line

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start/" target="_blank">https://vuetifyjs.com/en/getting-started/quick-start/</a>

**Comment by MajesticPotatoe** [comment]
We are looking into it. Its related to our new loaders, seems to have borked snippets. Thank you for reporting.
