### ISSUE TITLE
[Bug Report] Treeview selection-type='independent' if item-disabled on parent cannot select / open children

### ISSUE THREAD

**Issue by Erik-Jonker** [vuetifyjs/vuetify#10990]
### Environment
**Vuetify Version:** 2.1.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a v-treeview, give it a tree data, set selection-type='independent' and disable one of the node items that has children by setting the item-disabled prop and then try to open the node.

### Expected Behavior
The disabled parent node should still be able to be opened so that it is possible to select / unselect the children if the selection-type='independent'

### Actual Behavior
Cannot open a disabled parent node when selection-type='independent'

### Reproduction Link
<a href="https://codepen.io/erikjonker/pen/eYNXjKQ" target="_blank">https://codepen.io/erikjonker/pen/eYNXjKQ</a>

**Comment by billsliu** [comment]
Why do you need to select the disabled children? The parent should not be disabled if you want to select children item.

**Comment by Erik-Jonker** [comment]
The children are not (should not be) disabled, the parent has nothing to do with the children because I specified the prop selection-type='independent'

Look at the code-pen example I gave, if you select a parent, it does not automatically select the children because they are independent from the parent. So it should not matter if the parent is disabled since the children do not depend on the parent

**Comment by billsliu** [comment]
I know what your point, the big problem is the children items is not expandable, you can not view it, this is a bug, the first thing is  disabled parent item should be expandable for viewing its children no matter the selection type, the children items should be able selected if they define selection-type='independent'

**Comment by Erik-Jonker** [comment]
Yes exactly! I think it should be possible to expand a disabled parent to see their children, and if independent is set, it should be possible to select them
