### ISSUE TITLE
[Documentation] UI Components' Pages Report Error 404

### ISSUE THREAD

**Issue by PawelWojtyna** [vuetifyjs/vuetify#10998]
### Environment

**Browsers:** Chromium 80.0.3987.149
**OS:** Ubuntu undefined

### Steps to reproduce
Follow the Reproduction Link, or any other from UI Components section.

### Expected Behavior
Documents displayed correctly.

### Actual Behavior
Error 404 reported.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/bottom-navigation/" target="_blank">https://vuetifyjs.com/en/components/bottom-navigation/</a>

**Comment by MajesticPotatoe** [comment]
Try clearing your cache.
Link seems to be working fine.
