### ISSUE TITLE
[Documentation] Not search working 

### ISSUE THREAD

**Issue by tejas-ezee** [vuetifyjs/vuetify#10993]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
search any content not provide results. 

### Expected Behavior
search 

### Actual Behavior
search 

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start/" target="_blank">https://vuetifyjs.com/en/getting-started/quick-start/</a>

### Other comments
search

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10991
