### ISSUE TITLE
[Feature Request] reusable validation rules with translations

### ISSUE THREAD

**Issue by ThePeach** [vuetifyjs/vuetify#10994]
### Problem to solve
the idea is to be able to reuse validation rules across different components, with the following caveats:
1. the _default_ error message should be able to use i18n
2. it would be great to be able to customise the error messages with custom ones (or have replacement patterns, e.g. for customising the field name)

### Proposed solution (?)
perhaps extending the signature of the validation rules method could help address at least partially this problem?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
