### ISSUE TITLE
[Documentation] Search target link without i18n

### ISSUE THREAD

**Issue by AGDholo** [vuetifyjs/vuetify#10996]
### Environment

**Browsers:** Chrome 80.0.3987.162
**OS:** Windows 10

### Steps to reproduce
1. Open any i18n page, such as https://vuetifyjs.com/zh-Hans/
2. Type anything on the search button
3. Click the link of result
4. You will go 'en-us' document not 'zh-Hans'

### Expected Behavior
The target link will go i18n document page

### Actual Behavior
The target link will go 'en-us' document page

### Reproduction Link
<a href="https://vuetifyjs.com/zh-Hans/" target="_blank">https://vuetifyjs.com/zh-Hans/</a>

**Comment by MajesticPotatoe** [comment]
duplicate/related to #10991 - Should be resolved when search is back online.
