### ISSUE TITLE
[Bug Report] Grid viewports not behaving correctly

### ISSUE THREAD

**Issue by datainvestor** [vuetifyjs/vuetify#10992]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.10
**Browsers:** Vivaldi 2.5.1525.46
**OS:** Windows 10

### Steps to reproduce
Using viewport breakpoints as provided in documentation I set how many columns should the item take in the component. The thing is that while it kind of works as expcted when resizing the screen (like when I start on big sized view screen and then resize the browser to behave as small screen, then it works).
The issue happens when I refresh the page while on small sized view and then the grid breaks.

### Expected Behavior
It should work like on the left picture below both after resizing and after refreshing:
![Issue image](https://i.stack.imgur.com/hIFyY.jpg)

### Actual Behavior
There is the problem of the grid alignment on the right side of the picture

### Reproduction Link
<a href="https://codesandbox.io/s/highcharts-vue-demo-7gt0u" target="_blank">https://codesandbox.io/s/highcharts-vue-demo-7gt0u</a>

### Other comments
I asked the highcharts.js developers and they claim that the charting library is working as expected so the issue is with on the Vuetify side.

**Comment by KaelWD** [comment]
The charts are setting an explicit width on themselves. You also have no column width set for below 600px (`cols`) so it's automatic and the charts don't know how wide they should be.
