### ISSUE TITLE
[Bug Report] Items list of select does not have identifier (ID)

### ISSUE THREAD

**Issue by leoclipet** [vuetifyjs/vuetify#10995]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
When adding an ID to the v-select component, this ID is not set on the item list so there is no way of selecting items in an automated way

### Expected Behavior
ID should be set on the item list of the select so we can easily reach the list element and be able to pick items programmatically (for test purposes)

### Actual Behavior
There is no link between ID of a select and the list of items displayed

### Reproduction Link
<a href="https://codepen.io/leococo/pen/XWbGOwE?editors=1010" target="_blank">https://codepen.io/leococo/pen/XWbGOwE?editors=1010</a>

**Comment by KaelWD** [comment]
`document.getElementById(el.closest('[aria-owns]').getAttribute('aria-owns'))`
