### ISSUE TITLE
Button doesn't apply 'primary'

### ISSUE THREAD

**Issue by gluons** [vuetifyjs/vuetify#11]
[Button](https://vuetifyjs.com/components/buttons) with `primary` doesn't apply **primary** class.

Should [Button.vue](https://github.com/vuetifyjs/vuetify/blob/a9869dd71ac0538412aed186358e660ae0e494c7/src/components/buttons/Button.vue#L44) add `'primary': this.primary` and `'secondary': this.secondary` ❔ 

---

![SS1](https://cloud.githubusercontent.com/assets/4688092/21322545/31ac778c-c64c-11e6-8890-07658e512c1a.PNG)

---

![SS2](https://cloud.githubusercontent.com/assets/4688092/21322638/a4e20406-c64c-11e6-967e-d501e88131b3.png)

---

**Here is my `App.vue` file:**
```vue
<template>
	<div id="app">
		<div v-for="button in buttons">
			<v-btn
				:flat="button.flat"
				:primary="button.primary"
				:block="button.block"
				:outline="button.outline"
				:floating="button.floating"
			>
				{{ button.name }}
			</v-btn>
		</div>
	</div>
</template>

<script>
export default {
	name: 'app',
	data() {
		return {
			buttons: [
				{ name: 'default' },
				{ name: 'flat', flat: true },
				{ name: 'primary', primary: true },
				{ name: 'block', block: true },
				{ name: 'outline', outline: true },
				{ name: 'floating', floating: true }
			]
		};
	},
	mounted() {
		this.$vuetify.init();
	}
};
</script>

<style lang="scss">
#app {
	text-align: center;
	color: #2c3e50;
	margin: {
		top: 2rem;
		left: 2rem;
		right: 2rem;
	}

	& > div {
		margin: 2em auto;
	}
}
</style>
```

**Comment by johnleider** [comment]
I actually removed this but forgot to do so within the documentation as I thought it might not be used. If that's not the case, I can add it back.

**Comment by johnleider** [comment]
This has been added with https://github.com/vuetifyjs/vuetify/releases/tag/v0.7.8
