### ISSUE TITLE
[Bug Report] v-dialog - Uncaught RangeError: Maximum call stack size exceeded.   

### ISSUE THREAD

**Issue by vcherniatyn** [vuetifyjs/vuetify#11009]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.162
**OS:** Windows 10

### Steps to reproduce
- Load /users page, should be loaded by default
- Initiate removing User, click cancel on confirmation dialog
- Initiate removing User again, click cancel on confirmation dialog

### Expected Behavior
Dialog closed without errors in console and infinite loop

### Actual Behavior
On github version - ss result several errors in console log
In our prod site with asp net core - thousands errors in console with infinite loop and all opened tabs on same host stuck(:

### Reproduction Link
<a href="https://github.com/vcherniatyn/vcherniatyn/" target="_blank">https://github.com/vcherniatyn/vcherniatyn/</a>

### Other comments
http://prntscr.com/rrn2by
Browser can be closed through task manager only

**Comment by jacekkarczmarczyk** [comment]
All the dialogs are sharing the same v-model property.

When reporting a bug please provide a minimal reproduction instead of the whole application

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by vcherniatyn** [comment]
I provide you one cutted page in application that you can run for reproduction in steps.
Also all dialogs have different v-model property bindings.

Please explain me what you mean of ' minimal reproduction'.?

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/help/minimal-reproducible-example
