### ISSUE TITLE
[Bug Report] Vuetify doesn't seem to work on IE11

### ISSUE THREAD

**Issue by Dev-Oli** [vuetifyjs/vuetify#11008]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
* vue create ie-test
* cd ie-test
* vue add vuetify

### Expected Behavior
The sample / demo page is shown on IE

### Actual Behavior
Nothing is shown just a blank / empty page. No console errors / warnings are logged. 
The
```
<div id="app"></div>
```
stays empty.
On Chrome, Firefox, Edge it's working as expected.

### Other comments
This happens at the official https://vuetifyjs.com/en/getting-started/quick-start/ pages too. Sometimes you will get an empty page, sometimes you will see at least static content but nothing vuetify related. This seems to be random / not reproducible.

**Comment by billsliu** [comment]
I click the reproduction link, it shows fiddle doesn't support IE. Couldn't reproduce your problem

**Comment by billsliu** [comment]
Vuetify doesn't work in Edge 44 if you don't use Babel to compile.
[https://github.com/vuetifyjs/vuetify/issues/10987](url)

**Comment by billsliu** [comment]
IE 11 is too old, I think most new technology liking React, Vue doesn't work too well on IE. It is time to abandon the bad browser, I just show a warning message to customer to tell them to use Chrome. Don't waste time on the 1% user since those users can easily switch to a better browser.

**Comment by LaurenceHo** [comment]
My project's website cannot be accessed from IE11 too. I tried everything I could do by following the instruction, but it didn't work. Still struggling with IE11 issue now.

**Comment by DRoet** [comment]
add `transpileDependencies: ['vuetify']` to `vue.config.js` as described here:
https://vuetifyjs.com/en/getting-started/browser-support/

**Comment by Dev-Oli** [comment]
Hi @DRoet,

thanks for answering. 

Unfortunately that's not the reason ... so please re-open this ticket. Not sure if it was me adding the transpileDependencies or if it was added while using the cli but it's there:
`module.exports = {
  "transpileDependencies": [
    "vuetify"
  ]
}`

As said neither the simple generated vuetify demo page nor the official / online vuetify page is usable with IE 11.

**Comment by jacekkarczmarczyk** [comment]
We need the minimal reproduction @Dev-Oli to reopen the issue, create a simple project and provide the link to github repo (include the description of how did you create the project, including information on which options you've chosen, as well as your environment - vue cli version, node version)

**Comment by LaurenceHo** [comment]
> add `transpileDependencies: ['vuetify']` to `vue.config.js` as described here:
> https://vuetifyjs.com/en/getting-started/browser-support/

As I said, I followed the instruction https://vuetifyjs.com/en/getting-started/browser-support/ step by step. Of course, I added `transpileDependencies: ['vuetify']` to `vue.config.js`, and I did everything I could do. However, it's not working at all. I really want to know how you build this project for IE11? and how does it work?

I open the above instruction link in the IE11, the left side panel doesn't show up. Also, the whole layout looks different from Chrome or FF.

**Comment by Dev-Oli** [comment]
@jacekkarczmarczyk I've created a sample test repo at https://github.com/Dev-Oli/vuetify-ie11-bug. It provides nothing more than the description I've already added to this ticket (the most simple demo setup without modifying anything). By calling _vue add vuetify_ the transpileDependencies seems to be already added.

As said before not even the official vuetify homepage is working at IE11. So I doubt that it's related  to my local setup specifically.

**Comment by jacekkarczmarczyk** [comment]
Thank you @Dev-Oli , and what doesn't work in your reproduction? I was able to open it in IE11 both with `yarn serve` and `yarn build`
![image](https://user-images.githubusercontent.com/15625235/81291857-def8c580-906a-11ea-99db-1e5fadc872bd.png)

Documentation is another issue, already reported 
https://github.com/vuetifyjs/vuetify/issues/11046

**Comment by Dev-Oli** [comment]
@jacekkarczmarczyk Wow that's stunning :).
I've started it by calling _npm run serve_.

![image](https://user-images.githubusercontent.com/63057378/81292395-d228a180-906b-11ea-8869-a7514935a842.png)
I just see a dead empty page. If I inspect the page source code there is just an empty `<div id="app"></div>`. No console errors are logged at all.

This is the IE11 I'm using on Win 10:
![image](https://user-images.githubusercontent.com/63057378/81292638-3ea3a080-906c-11ea-8895-b95988db9178.png)
It's reproducible with every IE11 at our company.

It has been working until end of last year / january-february this year. I can't name the version it breaks as IE isn't our main focus :P.

**Comment by jacekkarczmarczyk** [comment]
Worked (*) using `npm run serve` on
![image](https://user-images.githubusercontent.com/15625235/81293266-4f084b00-906d-11ea-8016-bd3e8b698e23.png)

(*) page was displayed, but with error in console (translates to "unspecified error")
![image](https://user-images.githubusercontent.com/15625235/81293372-85de6100-906d-11ea-89c7-42904d155b46.png)

![image](https://user-images.githubusercontent.com/15625235/81293651-f08f9c80-906d-11ea-8410-642ca6af60b8.png)

**Comment by Dev-Oli** [comment]
Hmmm don't know what to say.
Purely IE "magic" lol.

As other users seems to be affected by this bug too maybe some other vuetify devs can please take a look and try to reproduce? As long as IE11 is at the supported browsers list I think this should be fixed, please re-open.

**Comment by jacekkarczmarczyk** [comment]
Can you first check if it works for you with `yarn`?

**Comment by Dev-Oli** [comment]
At least for me (with my IE version) I'm still getting an empty page while running `yarn serve`.

As it has been working before and it seems to be getting cached -> no errors show up. 
But after deleting the browser cache (as a last desperate try) I've discovered an error at console:
`SCRIPT438: the object doesn't support the property or method "assign"
index.ts (147,1)`
See [stackoverflow](https://stackoverflow.com/questions/51084500/object-assign-workaround-in-ie)
It seems that you should use a polyfill to fix this [mozilla mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

Not sure why it's been working for you as the mozilla mdn clearly states that it's unsupported at IE. Maybe your newer IE11 version got the assign support patched ;).

**Comment by jacekkarczmarczyk** [comment]
Ok, since that may be related to the IE version - could you please check the new vue cli project without vuetify and with 
```js
Object.assign({});
```
in main.js?

If this works then might be some issue with vuetify or cli plugin, otherwise you'd probably need to manually add some polyfills (and we might need to add proper information in docs)

**Comment by Dev-Oli** [comment]
Adding the polyfill to _public\index.html_ seems to fix this bug.

Creating a new simple vue project and adding the log statement (as mentioned above) results in the **same** console error. 

It seems to be a vuetify issue because the _object.assign_ is located at 
`node_modules\vuetify\src\services\theme\index.ts`

**Comment by DRoet** [comment]
are you importing vuetify from `vuetify/lib` ?

**Comment by Dev-Oli** [comment]
@DRoet see attached demo github repo.

**Comment by jacekkarczmarczyk** [comment]
@DRoet that doesn't matter, the problem is that Object.assign is not being polyfilled, which seems strange to me as it was added to default polyfill in babel preset some time ago, see https://github.com/vuejs/vue-cli/issues/1248 and https://github.com/vuejs/vue-cli/commit/8dcfc184cf3edbbbeaa42cdc8f162146b9ba71d9#diff-d8e341482c7dd4a7872d0eea73aa34d9R11
@Dev-Oli I'd actually suggest to creating an issue in vue repo since it happens also without Vuetify, what we could do is to add the information to docs, however it would be good to know what's causing the issue

**Comment by billsliu** [comment]
I can confirm the latest vuetify works perfectly on IE11, there is no problem.

**Comment by Dev-Oli** [comment]
@jacekkarczmarczyk Thanks for the sugguestion.
I've created a vue ticket as proposed, see [vue 11382](https://github.com/vuejs/vue/issues/11382)

**Comment by jacekkarczmarczyk** [comment]
@Dev-Oli can you confirm that https://github.com/vuejs/vue/issues/11382#issuecomment-625559160 works in your case?

**Comment by DRoet** [comment]
I am using the updated browserlist in my project and it still works with IE11, I also cloned the repro and it runs fine in IE11 (11.0.185) `npm run serve / npm run build`

Which node version is being used here to run the commands?

**Comment by jacekkarczmarczyk** [comment]
@DRoet you're using same IE as me where it works, @Dev-Oli uses a different version

**Comment by DRoet** [comment]
@jacekkarczmarczyk I have an even older version of IE11 running it with no issues so I would be really surprised a random patch messed it up, but who knows 🤷‍♂️ 

the missing `node` version used to compile the project might be more interesting to look at.

**Comment by Dev-Oli** [comment]
@DRoet In the sample repo I've created yesterday at the README.md you can find the node version I'm using. It's v12.10.0

@jacekkarczmarczyk Removing "not dead" from the package.json browserslist I still can't use the Object.assign in a simple vue project (without using vuetify) as you suggested.

**Comment by jacekkarczmarczyk** [comment]
Oh, i missed that you already have not dead in package.json, so we're going back to "that's weird" stage

Anyway as it was suggested in https://github.com/vuejs/vue/issues/11382 you should create an issue in vue-cli repo and WITHOUT Vuetify, so just `vue create ...`, change your main.js to just one line containing `console.log(Object.assign({}))`, and provide all details (browser, node, vue cli etc versions) in the issue instead of linking to the discussion in other issue

**Comment by DRoet** [comment]
yeah idk if there is anything we can do here, building with `12.10.0` still works on my end

**Comment by Dev-Oli** [comment]
@DRoet Thanks for verifying. That's really strange. Maybe I find some time at the weekend to check it with my pc at home. If I remember it right it happened there too.

**Comment by Dev-Oli** [comment]
Hmmm "stranger things" part 2 to say the least.
Testing the _console.log_ of the _object.assign_ in a simple vue project (_vue create_ <xyz> + selecting the defaults) with the following system works:
- Win 7
- IE v11.0.9600.19596
- Node v13.10.1
- NPM v6.14.5
- @vue/cli v4.3.1
The only difference I see is the node version. The OS + browser version shouldn't play a role as it's a polyfill problem. But as it's working for @DRoet with node version v12 I don't know what else to check. I'll have to leave it up to the experts ;).

**Comment by LaurenceHo** [comment]
Just want to let everyone know how I resolved IE 11 issue. After struggling with IE 11 issue for a while, I decided to create a new VueJS + Vuetify project from the beginning. Before doing this, I upgraded VueCLI to `4.3.1`. After creating a project by using VueCLI, I can access this new project from IE 11. (Suprised!)

I compared the new configuration files generated by VueCLI with the existing project, I found in this new project, it doesn't have `babel-polyfill` and `@babel/preset-env`. Instead, it has `core-js` and `@vue/cli-plugin-babel` installed. Besides, it doesn't need to place `import 'babel-polyfill'` in the `main.ts` either. No wonder it didn't work at all when I followed the instruction.

I migrated everything from the existing project to this new project, and now everything is working fine in IE 11. I think you might need to update your documentation (https://vuetifyjs.com/en/getting-started/browser-support/) for the browser support.

**Comment by Dev-Oli** [comment]
`babel-polyfill` is deprecated and `core-js` should be used instead, see https://github.com/zloirock/core-js#babelpolyfill.
The imports seems to be missing at _main.js_ though
`import "core-js/stable";
import "regenerator-runtime/runtime";`

**Comment by LaurenceHo** [comment]
> `babel-polyfill` is deprecated and `core-js` should be used instead, see https://github.com/zloirock/core-js#babelpolyfill.
> The imports seems to be missing at _main.js_ though
> `import "core-js/stable"; import "regenerator-runtime/runtime";`

The generated _main.js_ by VueCLU doesn't have `import "core-js/stable"; import "regenerator-runtime/runtime";` and it works well.

**Comment by KaelWD** [comment]
I created a new project using @vue/cli 4.5.6 and the default preset, added vuetify also with default settings and it works in IE11.
