### ISSUE TITLE
Navigation drawer is not closed on mobile screen if I click on same link

### ISSUE THREAD

**Issue by JankoHrasko7** [vuetifyjs/vuetify#1100]
### Steps to reproduce
1. Resize window to mobile screen size.
2. Open drawer and click on any link (drawer is closed properly)
3. Open drawer and click on same link - drawer is not closed

### Versions

Your demo site

### What is expected ?

Drawer should be closed

### What is actually happening ?

Drawer is not closed when I click on the link, which is current

### Reproduction Link

https://vuetifyjs.com/vuetify/quick-start

**Comment by johnleider** [comment]
This is intended functionality. The navigation-drawer only re-evaluates its state if the route changes, clicking on the same link obviously will not do that.

**Comment by JankoHrasko7** [comment]
But if you have mobile size, drawer should be closed also in this case
