### ISSUE TITLE
[Bug Report] English always present in $vuetify.lang.locales even if not included in plugin initialization

### ISSUE THREAD

**Issue by wdarins** [vuetifyjs/vuetify#11005]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Ignore English in vuetify initialization and iterate through vuetify languages 

### Expected Behavior
No english language in list

### Actual Behavior
English is present

### Reproduction Link
<a href="https://codepen.io/wdarins/pen/KKpYqpW" target="_blank">https://codepen.io/wdarins/pen/KKpYqpW</a>

**Comment by MajesticPotatoe** [comment]
Your reproduction has some errors, making it hard to visualize what you are actually reporting.
Are you trying to say that `en` language is included even though you are are defining `ro`/ `ru` as languages?

**Comment by wdarins** [comment]
@MajesticPotatoe yes.

**Comment by Leespiker** [comment]
I thought it was always included for fallback content.

**Comment by johnleider** [comment]
@Leespiker is correct, this is intended behavior.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
