### ISSUE TITLE
[Bug Report] When we're using v-select with multiple props using slots checkbox appearance removed.

### ISSUE THREAD

**Issue by ETSmukesh** [vuetifyjs/vuetify#11002]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
https://codepen.io/mukesh9999/pen/wvaZJQY?editors=1010

### Expected Behavior
The checkbox should appear for selection

### Actual Behavior
Checkboxes getting removed when using slots

### Reproduction Link
<a href="https://codepen.io/mukesh9999/pen/wvaZJQY?editors=1010" target="_blank">https://codepen.io/mukesh9999/pen/wvaZJQY?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
If you're using `item` slot you need to define the whole content for it, including checkboxes
