### ISSUE TITLE
[Documentation] Incorrect URL to vue-cli-electron-builder

### ISSUE THREAD

**Issue by vorion** [vuetifyjs/vuetify#11018]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Click the link to electron-build plugin, it 404s

### Expected Behavior
Loads correct url https://github.com/nklayman/vue-cli-plugin-electron-builder

### Actual Behavior
Loads incorrect url https://github.com/nklayman/Vue%20CLI-plugin-electron-builder

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start/#usage-with-electron" target="_blank">https://vuetifyjs.com/en/getting-started/quick-start/#usage-with-electron</a>

**Comment by MajesticPotatoe** [comment]
fixed in 95b7117
