### ISSUE TITLE
[Feature Request] Fixed Row Option at the bottom and top

### ISSUE THREAD

**Issue by ayush1303** [vuetifyjs/vuetify#11016]
### Problem to solve
I wanted to have a summary row which is fixed at the bottom indeed I can keep it to the footer and also  widths scope to show the column aligned to the table columns but when I have a vertical scroll in content then it is difficult to scroll the static row at the footer. 

### Proposed solution
A feature that allows a row to be fixed at the bottom or top

**Comment by johnleider** [comment]
We have a fixed-header prop, not sure if that's what you mean. As far as footer, I'll leave that up to neko.

**Comment by ayush1303** [comment]
@johnleider thanks for your response.

@nekosaur , 
Let me elaborate a bit more.
Indeed we have a fixed header prop which limits the header to scroll vertically.

My requirements is I want to fix a row at the bottom same as the fixed header so the particular row doesn't gets scroll vertically and stays attached to the table footer. Indeed it should scroll horizontally like header does. Moreover I want it as a row only as also I want the pagination footer to be fixed as it's currently implemented.

Please let me know if you need more details and let me know if I can achieve that other way but as per I researched it is not possible to do .

Thanks

**Comment by nekosaur** [comment]
This is already possible <https://codepen.io/nekosaur/pen/XWmPPPb?editors=1010>

**Comment by ayush1303** [comment]
@nekosaur Indeed we can use the widths but it will not scroll horizontally with the data.

Just modified code pen a bit
 https://codepen.io/ayush1303/pen/ZEbMqQQ?editors=1010

**Comment by nekosaur** [comment]
You could possibly make it work with a couple of refs and manually updating the footer table scroll position when the main table scrolls 🤷 

Feel free to create a new feature request for this specific thing. However the horizontal scrolling is a pretty niche requirement at this point. Unless and/or until data-table gets a major overhaul it probably won't be prioritized.
