### ISSUE TITLE
[Bug Report] v-slider performance problems on mobile firefox

### ISSUE THREAD

**Issue by coolibre** [vuetifyjs/vuetify#11017]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox
**OS:** Android

### Steps to reproduce
- use HelloWorld QuickStart example from vuetify
- add a v-slider with v-model as shown in codepen
- serve to localhost
- access remotly from tablet or smartphone with current Firefox App (68.6.0)

### Expected Behavior
v-slider works as expected

### Actual Behavior
- performance of animation is very slow which leads to not usable in bigger app example
- works like a charme in mobile chrome

### Reproduction Link
<a href="https://codepen.io/coolibre/pen/WNvBMMq" target="_blank">https://codepen.io/coolibre/pen/WNvBMMq</a>

### Other comments
- testet on 2 different Android devices (Galaxy Tab S4, Galxy S7)
- performance increases by far when removing v-model

**Comment by MetalBlueberry** [comment]
I've found the same issue, is there any workaround?

**Comment by MIhailsPopovs** [comment]
+1

**Comment by coolibre** [comment]
#https://github.com/vuetifyjs/vuetify/issues/11409

**Comment by KaelWD** [comment]
@coolibre @MetalBlueberry can you still reproduce this?

**Comment by coolibre** [comment]
> #11409 could be the cause

Fixed this. Issue can be closed.
