### ISSUE TITLE
[Bug Report] Memory Leak in v-img when aspect-ratio prop not provided and error occurs

### ISSUE THREAD

**Issue by GreenLoofa** [vuetifyjs/vuetify#11026]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Mac OS 10.14

### Steps to reproduce
1. In the linked codepen, click the toggle button numerous times
2. Using chrome's dev tools, create a heap snapshot for "cdpen.io: index.html" under the memory tab

### Expected Behavior
There should be only one VueComponent Contstructor for v-img.

### Actual Behavior
There are numerous VueComponent Constructors for v-img

### Reproduction Link
<a href="https://codepen.io/MadBananaHammock/pen/wvaLvMw?editors=1011" target="_blank">https://codepen.io/MadBananaHammock/pen/wvaLvMw?editors=1011</a>

### Other comments
It looks to be an issue with the setTimeout in "pollForSize()" in the VImg component. This only seems to happen when there is an error when fetching the image.

**Comment by KaelWD** [comment]
It doesn't cancel polling when there's an error so it keeps going forever.
