### ISSUE TITLE
[Feature Request] Datatable export to excel, pdf, print

### ISSUE THREAD

**Issue by sfraire** [vuetifyjs/vuetify#11027]
### Problem to solve
users that wish to save their table data

### Proposed solution
create a way to make btns to export to excel, pdf,print

**Comment by MajesticPotatoe** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

This functionality (especially the excel and pdf) lays outside of the scope of our library. You can very easily create it with existing components (simply a toolbar with some buttons on it) and some external libraries that handle excel + pdf creation (exceljs and pdfjs for example). 

If you have any additional questions, or would like to seek assistance/guidance for such a feat, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
