### ISSUE TITLE
[Documentation] can't search by directive name

### ISSUE THREAD

**Issue by gregveres** [vuetifyjs/vuetify#11022]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
in the search field, enter: v-img
what you will find are 5 results:
1: an FAQ entry
2: Toolbars
3: navigation drawers
4: app bars
5: cards

The most important link that should be shown is the page that describes v-img. All of these others might be useful, but are no where near as relevant as the page that describes v-img.

I am using v-img, but you can use any directive and get similar results. I have never once, found that search returned the directive page, which is the only page I am every looking for. 

### Expected Behavior
I expected the search to return the v-img page

### Actual Behavior
It showed a bunch of pseudo related links

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/guide/" target="_blank">https://vuetifyjs.com/en/introduction/guide/</a>

### Other comments
I am coming from Quasar and on first glance it seems like the docs are virtually identical between the  two products, but I found Quasar's documentation to be far superior for the following reasons:

1: search always gave me what I expected
2: there were more examples on the basic stuff like layout. For instance, I still don't have a good sense of when to use v-row and v-col and how to control the grid system in Vuetify after reading the docs a few times, but I came up to speed on Quasar much faster. (I have 4-5 years of using bootstrap so I get the 12 column grid system).
3: Quasar's docs put the api at the bottom of the page, which is a more natural place for it for people who are learning the library. You need to understand the examples before digging into the api. I do agree that once you are more experienced with the library you are probably looking at the api section more often. Maybe having the api section at the bottom with a link to it at the top of the page would be better.

**Comment by MajesticPotatoe** [comment]
So this is a lot to unpack, and I appreciate your time to provide feedback. Unfortunately we do not have much control over what algolia provides back as search results (as we just send your search to their servers and the results are sent back based on what content is has crawled and connections it has made from your search). Its likely that results in there somewhere, for example, if you search for the word image, the `v-img` page is actually the first returned (similarly if you search button). something like `v-img` is a fairly common term across the doc pages (actually appearing about 22 times across 8 different files)

As for the other comments you have mentioned, We've made efforts in the past to provide more examples, and you would find (after the api section) most components do have a fairly large set of examples. The grids page that you mention in fact even has about 17 examples covering various ways to handle the grid. Is it perfect? not in the slightest, but we are always welcoming contributions to make the docs better.

As for the API section being moved to the bottom, the team has discussed this before in the past, and weighing out where to place it, where ultimately is why its where its at, not to say it cant change in the future.

Once again thank you for your interest in improving Vuetify! If you would like to discuss more about improvements, please reach out to our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Does algolia look at `<meta name="keywords">`?
