### ISSUE TITLE
Navigation Drawers not working while script Google reCaptcha is on.

### ISSUE THREAD

**Issue by Dark-Aii** [vuetifyjs/vuetify#1102]
### Steps to reproduce
If you are using Vuetify 0.13 or 0.14. And you add the script :
"<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>" 
inside the header.
The Navigation Drawing will no longer open.

### Versions

Vuetify 0.13 and 0.14

### What is expected ?

The Navigation Drawer is expected to Open/Close.

### What is actually happening ?

The Navigation Drawer does not Open/Close.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
