### ISSUE TITLE
[Documentation] location hash does not exist

### ISSUE THREAD

**Issue by alesvaupotic** [vuetifyjs/vuetify#11024]
### Environment

**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Paste the https://vuetifyjs.com/en/customization/sass-variables/#variable-api into your web browser 

### Expected Behavior
To be taken directly to the Variable API part of the SASS variables

### Actual Behavior
I am taken to the top of the SASS variables page.

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables/#variable-api" target="_blank">https://vuetifyjs.com/en/customization/sass-variables/#variable-api</a>

### Other comments
The anchor on the Variable API heading is incorrect as it points to #webpack-install

**Comment by MajesticPotatoe** [comment]
Thank you for reporting this. We were looking into it yesterday, as its not specifically to that link, but all hash links. The link itself works, what is happening is that when the page is loaded, the hash content hasn't been rendered yet so goto cant find where to scroll too. Updating the title to reflect this.

**Comment by MajesticPotatoe** [comment]
resolved the incorrect has heading in 35cc578. Please let me know if this issue still persists.

**Comment by alesvaupotic** [comment]
Works as expected. Thanks for quick fix! Closing.
