### ISSUE TITLE
[Bug Report] v-textarea doesn't respect the type="password" prop

### ISSUE THREAD

**Issue by gcharang** [vuetifyjs/vuetify#11023]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Linux x86_64

### Steps to reproduce
Try using the `type="password"` prop in the `v-textarea` component

### Expected Behavior
the text should be masked

### Actual Behavior
the text is not masked

### Reproduction Link
<a href="https://codepen.io/gcharang/pen/YzXozLM" target="_blank">https://codepen.io/gcharang/pen/YzXozLM</a>

**Comment by KaelWD** [comment]
`<textarea>` doesn't support that, so neither does v-textarea
