### ISSUE TITLE
[Bug Report] no day view on Saturday if weekdays are only m-f

### ISSUE THREAD

**Issue by sfraire** [vuetifyjs/vuetify#11025]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Mac OS 10.15

### Steps to reproduce
change weekdays to Mon- Fri.

if current day is Saturday, and you want to go to "Today" view we get this error

No dates found using specified start date, end date, and weekdays.

### Expected Behavior
show Saturdays in the day view not on the week view not the month view

### Actual Behavior
gives error: No dates found using specified start date, end date, and weekdays.

### Reproduction Link
<a href="https://codepen.io/sfraire/pen/QWbXjdy?editable=true&editors=111" target="_blank">https://codepen.io/sfraire/pen/QWbXjdy?editable=true&editors=111</a>

**Comment by ClickerMonkey** [comment]
This issue would also arise if you only want to show Mon-Wed and the 4day view is set to Thurs-Sun. Not sure what to do in that situation.

**Comment by ClickerMonkey** [comment]
I suppose all day-based views should ignore weekdays.
