### ISSUE TITLE
[Documentation] Laravel Mix setup

### ISSUE THREAD

**Issue by Nothing-Works** [vuetifyjs/vuetify#11038]
### Problem to solve
vuetifyjs with laravel-mix is a bit tricky to setup.

### Proposed solution
This package does it. Consider adding this to the docs?
 
I create a [package](https://github.com/Nothing-Works/vuetifyjs-mix-extension). It does everything for you. [npm link](https://www.npmjs.com/package/vuetifyjs-mix-extension)

And here is [laravel setup](https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md)

It's also on [laravel-mix.com](https://laravel-mix.com/extensions/vuetifyjs-mix-extension)

**Comment by ibrahimBeladi** [comment]
What would this package provide exactly?

**Comment by Nothing-Works** [comment]
@ibrahimBeladi so currently, if I want to setup vuetify with laravel using [laravel webpack wrapper](https://laravel-mix.com/), I need to do a few things manually. (btw, from the people I know who are laravel developer, most of them use laravel-mix which comes with laravel by default.)

1. install some dependencies manually.
2. add vuetify webpackRules (as laravel-mix does not expose `webpack.config.js` so it's tricky and verbose to do that)
3. add `vuetify-loader` plugin if we want tree-shaking (and this is the same reason as NO. 2)
4. also laravel-mix has some predefined rules for `sass` and `scss`. In order to make it work with vuetify, I also need to exclude them from the default rules.

And there some forks have this issue from the community, [From vuetify (unsolved)](https://github.com/vuetifyjs/vuetify/issues/9553), [From vuetify (vuetify-loader problem)](https://github.com/vuetifyjs/vuetify-loader/issues/49), [From laravel-mix (the solution is verbose)](https://github.com/JeffreyWay/laravel-mix/issues/2173), [From stackoverflow](https://stackoverflow.com/questions/61002801/has-anyone-has-success-with-vuetify-and-laravel-7). And I can find some more, but I think it's enough.

So, like [this issue](https://github.com/vuetifyjs/vuetify/issues/9553) he wants documentation and currently it's missing. I can kind of understand why it's not on docs.

Because this is what you need to do in order to configure it properly.
```js
mix.webpackConfig({
    module: {
        rules: [
		{
		  test: /\.s(c|a)ss$/,
		  use: [
			'vue-style-loader',
			'css-loader',
			{
			  loader: 'sass-loader',
			  options: {
				implementation: require('sass'),
				fiber: require('fibers'),
			  }
			}
		  ]
		}
	  ]
    },
	plugins: [
		new VuetifyLoaderPlugin()
	],
}); 

Mix.listen('configReady', webpackConfig => {
  // Exclude vuetify folder from default sass/scss rules
  const sassConfig = webpackConfig.module.rules.find(
    rule =>
      String(rule.test) ===
      String(/\.sass$/)
  );

  const scssConfig = webpackConfig.module.rules.find(
    rule =>
      String(rule.test) ===
      String(/\.scss$/)
  );

  sassConfig.exclude.push(path.resolve(__dirname, 'node_modules/vuetify'))
  scssConfig.exclude.push(path.resolve(__dirname, 'node_modules/vuetify'))
});

mix.js('app.js', 'dist/js');
```

Finally, it comes to the package, all you need to do is just

```js
mix.js('resources/js/app.js', 'public/js').vuetify()
//if you use vuetify-loader
mix.js('resources/js/app.js', 'public/js').vuetify('vuetify-loader')
```
Hopefully, I explained well.

**Comment by MajesticPotatoe** [comment]
Closing this as its an extension of #9553 and would be included in that if anything.
I personally have never touched Laravel, so would be looking to the community to handle and maintain the validity of the documentation for it if we decide to include it.

**Comment by Nothing-Works** [comment]
@MajesticPotatoe  I can help with the doc.

**Comment by KaelWD** [comment]
I always recommend using vue-cli for your frontend, and laravel just as an API.

**Comment by Nothing-Works** [comment]
@KaelWD  not everyone is building SPAs
