### ISSUE TITLE
[Bug Report] $vuetify.breakpoint.xsAndUp is undefined still exists at vuetify 2.2.11

### ISSUE THREAD

**Issue by billsliu** [vuetifyjs/vuetify#11030]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Install vuetify
Access $vuetify.breakpoint.xsAndUp

### Expected Behavior
It should exist (and probably always return true) as listed in the documentation - definition of the $vuetify.breakpoint object

> {
  xs: boolean
  xsOnly: boolean
  xsAndUp: boolean
  sm: boolean
  smOnly: boolean
  smAndDown: boolean
  smAndUp: boolean
  md: boolean
  mdOnly: boolean
  mdAndDown: boolean
  mdAndUp: boolean
  lg: boolean
  lgOnly: boolean
  lgAndDown: boolean
  lgAndUp: boolean
  xl: boolean
  xlOnly: boolean
  xlAndDown: boolean
  name: ('xs' | 'sm' | 'md' | 'lg' | 'xl')
  width: number
  height: number
}

### Actual Behavior
Returns undefined.

### Reproduction Link
<a href="https://codepen.io/areebbeigh/pen/pqdGJx" target="_blank">https://codepen.io/areebbeigh/pen/pqdGJx</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/quick-start/#markup-js-vue-options-vuetify

**Comment by billsliu** [comment]
I am wrong, I used an old document, $vuetify.breakpoint.xsAndUp has been already removed.
