### ISSUE TITLE
[Feature Request] Add possibility to add name attribute to `v-text-field`

### ISSUE THREAD

**Issue by bramceulemans** [vuetifyjs/vuetify#11032]
### Problem to solve
Not being able to select the input fields based on the `name` attribute. Some testing frameworks like Laravel Dusk use the `input[name="xxx"]` attribute

### Proposed solution
Add a property to `v-text-field`, `v-select`, etc. that sets the name

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/78503632-348a3b80-7768-11ea-8df7-0e95254cf33f.png)

**Comment by bramceulemans** [comment]
Would it be possible to add autocompletion for this?
