### ISSUE TITLE
[Bug Report] Color of the selection controller doesn't change even if we provide another color

### ISSUE THREAD

**Issue by JISSJOHNSON** [vuetifyjs/vuetify#11045]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce

              <v-select
                v-model="category"
                :items="categories"
                item-text="name"
                item-value="_id"
                color="green"
                label="Category"
                prepend-icon="mdi-cube-unfolded"
                multiple
              >
              </v-select>

### Expected Behavior
The color of the selection should change to provided color. the default blue color is appeared

### Actual Behavior

              <v-select
                v-model="category"
                :items="categories"
                item-text="name"
                item-value="_id"
                color="green"
                label="Category"
                prepend-icon="mdi-cube-unfolded"
                multiple
              >
              </v-select>

### Reproduction Link
<a href="https://codepen.io/jissjohnson/pen/poJMQxb" target="_blank">https://codepen.io/jissjohnson/pen/poJMQxb</a>

### Other comments
The color of the selection should change to provided color. the default blue color is appeared

**Comment by jacekkarczmarczyk** [comment]
Use `item-color` prop
