### ISSUE TITLE
[Documentation] Vuetify Documentation not loading in IE

### ISSUE THREAD

**Issue by mathew-ferry13** [vuetifyjs/vuetify#11046]
### Environment

**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Navigate to https://vuetifyjs.com/en/components/data-tables/ in Internet Explorer

### Expected Behavior
Navigation and Examples load

### Actual Behavior
Navigation and Examples do not load

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables/" target="_blank">https://vuetifyjs.com/en/components/data-tables/</a>

**Comment by KaelWD** [comment]
`@octokit/core` doesn't appear to be easily polyfillable for IE. Vuetify 2.x will still work in IE if you create a project with vue-cli or follow the browser support guide.
