### ISSUE TITLE
[Bug Report] Select all on v-data-table doesn't select all the rows

### ISSUE THREAD

**Issue by tmasrat** [vuetifyjs/vuetify#11042]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.0
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.2

### Steps to reproduce
Click on the select all checkbox

### Expected Behavior
Select all should select all the rows

### Actual Behavior
The "select all" checkbox is not selecting the rows

### Reproduction Link
<a href="https://codepen.io/tmasrat/pen/VwLoYQY?editors=1010" target="_blank">https://codepen.io/tmasrat/pen/VwLoYQY?editors=1010</a>

### Other comments
I know in this particular example, if I get rid of the template and let the data-table handle the rendering, the select all button will work but on my actual use case, I am trying to render an icon based on a condition so that work around doesn't work for me.

**Comment by MajesticPotatoe** [comment]
You are not binding the checkbox correctly. item slot passes in a `select` function and an `isSelected `state for each row, use these as so: <https://codepen.io/majesticpotatoe-the-bashful/pen/PoqMPKg>
