### ISSUE TITLE
[Bug Report][2.2.20] VTextField causing frame hanging

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#11044]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Linux x86_64

### Steps to reproduce
I was doing some profiling in my app and stumbled upon a suspicious block that's causing frame locking.  

![labelWidth](https://user-images.githubusercontent.com/1561245/78668447-b5e8e780-78a8-11ea-88ee-788cd9b03fe2.png)

Notice the flagged line taking 122 ms to execute (In dev mode)

![textFieldLocking](https://user-images.githubusercontent.com/1561245/78668455-b8e3d800-78a8-11ea-8e23-6bf883f128af.png)

The essence of the problem is running `this.labelWidth = Math.min(this.$refs.label.scrollWidth * 0.75 + 6, (this.$el as HTMLElement).offsetWidth - 24)` causes the DOM to reflow every time it's called.  If you have a complex application, the act of loading a text field can cause significant damage.  In my app, I'm seeing about 32ms (16 to recalculate style, and 16 to relayout, on the low end.  Often it's over 50ms) of locking (in dev mode of course) just mounting a `VTextField`. 

Question: why does this need to be a computed property?  Why can't it just be handled by CSS?  It seems like something that should be done in CSS, no?  Using a wrapper would prevent the need to touch the elements which is causing reflows.

### Expected Behavior
To use CSS to style the label width, instead of a computed value that requires touching the DOM.

### Actual Behavior
There is a computed value in `VTextField` which is causing DOM reflows.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/dyoxQzm" target="_blank">https://codepen.io/gabaum10/pen/dyoxQzm</a>

**Comment by KaelWD** [comment]
> Why can't it just be handled by CSS

It's reading the width of the label to know how wide the gap in the border should be, which can't be done with just css. It probably doesn't need to calculate this on mount unless the label is active, as it's done again on focus.

**Comment by gabaum10** [comment]
That would at least mitigate the initial load if you have a big form and every input calls that computation.

This is really surprising there isn't a pure css solution to that.  That's far from my strong point though, plus I don't know the inner workings of the component super well.

**Comment by gabaum10** [comment]
I'm not sure how you guys feel about external deps, but we had several issues related to querying element sizes around our app.  We have had some remarkable success eliminating some of the bottlenecks with a lib called fastdom.  

https://github.com/wilsonpage/fastdom

Basically you just wrap your measurement in a block called `measure` and it handles the batching for you to eliminate bottlenecks.  May be worth exploring for fine tuning some performance in vuetify

**Comment by johnleider** [comment]
> I'm not sure how you guys feel about external deps, but we had several issues related to querying element sizes around our app. We have had some remarkable success eliminating some of the bottlenecks with a lib called fastdom.
> 
> [wilsonpage/fastdom](https://github.com/wilsonpage/fastdom)
> 
> Basically you just wrap your measurement in a block called `measure` and it handles the batching for you to eliminate bottlenecks. May be worth exploring for fine tuning some performance in vuetify

No external dependencies. This is something that should be resolved with our new way of doing outlined in v3.
