### ISSUE TITLE
[Bug Report] Vuetify treeview not rendering in a shadow DOM

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#11057]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Issue occurs on page load.

### Expected Behavior
Tree view works as usual.

### Actual Behavior
Icons don't render properly.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/mdebxLG" target="_blank">https://codepen.io/sneaky666/pen/mdebxLG</a>

**Comment by KaelWD** [comment]
Vuetify does not support shadow DOM: #7622

This could also be a problem with https://github.com/google/material-design-icons rather than vuetify itself.

**Comment by TheInvoker** [comment]
Here's an alternative with another iconset and same issue https://codepen.io/sneaky666/pen/XWmrEwR

**Comment by KaelWD** [comment]
Fonts have to be loaded outside the shadow: https://bugs.chromium.org/p/chromium/issues/detail?id=336876

**Comment by TheInvoker** [comment]
That fixed the icon issue. I had to define <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css"> 
inside and outside the shadow DOM.
