### ISSUE TITLE
[Documentation] Explain the term "* -16px on Desktop"

### ISSUE THREAD

**Issue by Perlover** [vuetifyjs/vuetify#11055]
### Problem to solve
Hello!

At https://vuetifyjs.com/ru/components/grids/ there is text:

"* -16px on Desktop"

Can you explain what does mean "* -16px on Desktop"? I many googled but i didn't understand. I only googled that many monitors have 16px default font size but how there is related font size with screen resolutoin?

### Proposed solution
To explain "star" note for "Material Design Viewport Breakpoints"

**Comment by Perlover** [comment]
And please can you explain there: the range is for width of resolution not for height, right?

**Comment by Twinsen343** [comment]
Just came across this, the documentation says xl should be 

XL > 4k and ultra-wides > 1904px*
* -16px on Desktop

1904px - 16px =  1888px which puts xl into the FULL HD category and then the xl category.

I've got a 2K monitor and ideally would like xl to be > than HD.

I'm sure there is a reason for the -16px, but would be good to have a XXL then for 2K/4K screens ect.

**Comment by MajesticPotatoe** [comment]
This has already been updated/clarified in the new docs. The -16px is to account for scrollbars on desktop. As for an XXL breakpoint, that would be a feature request, and outside of the scope of this issue
