### ISSUE TITLE
[Bug Report] v-date-picker range mode causes @change to fire even on 1 date selected

### ISSUE THREAD

**Issue by webcoderkz** [vuetifyjs/vuetify#11056]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.4

### Steps to reproduce
Documentation says, that @change event fires, when both dates are chosen, i.e: ['2020-05-11', '2020-05-12'], but this @change event fires even when just one date chosen.

### Expected Behavior
@change event must be fired when both of dates are chosen, as per documentation.

### Actual Behavior
@change event fires even with 1 date selected

### Reproduction Link
<a href="https://codepen.io/webcoderkz/pen/BaoBYbx" target="_blank">https://codepen.io/webcoderkz/pen/BaoBYbx</a>

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/abvoYGW?editors=1010 vs https://codepen.io/jkarczm/pen/xxwKWjr?editors=1010

**Comment by matteoraf** [comment]
> https://codepen.io/jkarczm/pen/abvoYGW?editors=1010 vs https://codepen.io/jkarczm/pen/xxwKWjr?editors=1010

What if you want to start with an empty selection?

**Comment by jacekkarczmarczyk** [comment]
It works with empty selection, not sure what you mean
You can reach out to us in our [Discord community](https://community.vuetifyjs.com) if you have any questions, and if you've found a new bug/regression please create a new issue

**Comment by matteoraf** [comment]
> It works with empty selection, not sure what you mean
> You can reach out to us in our [Discord community](https://community.vuetifyjs.com) if you have any questions, and if you've found a new bug/regression please create a new issue

If you start with an empty selection, the Change event is fired as soon as you select the first date. 
As for the docs, it should only fire after you select both dates.

**Comment by jacekkarczmarczyk** [comment]
> it should only fire after you select both dates

And it does in latest version, if I'm mistaken please create a new issue and provide reproduction

**Comment by matteoraf** [comment]
> > it should only fire after you select both dates
> 
> And it does in latest version, if I'm mistaken please create a new issue and provide reproduction

My apologies...I didn't realize that the codepen was using the prev version
