### ISSUE TITLE
[Bug Report] Custom breakpoint thresholds does not work in Grid v-col component

### ISSUE THREAD

**Issue by stepanho** [vuetifyjs/vuetify#11058]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 7

### Steps to reproduce
1. Re-assign custom breakpoint thresholds:
2. Use grid system
3. Mark v-col component with properties col="12" md="6"

### Expected Behavior
On screen width = 600px, sm = 540, md = 800:

this.$vuetify.breakpoint is 'md'
Used grid column is 6

### Actual Behavior
On screen width = 600px, sm = 540, md = 800:

this.$vuetify.breakpoint is 'md'
Used grid column is 12 (changed to 6 only on >=960px)

### Reproduction Link
<a href="https://jsfiddle.net/mwL0753p/" target="_blank">https://jsfiddle.net/mwL0753p/</a>

### Other comments
Looks like grid system use only default breakpoint threshold.
Reproduction link shows just an example of code, not runnable.

**Comment by KaelWD** [comment]
You have to change the sass variable too: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_variables.scss#L26

**Comment by stepanho** [comment]
> You have to change the sass variable too

@KaelWD Can you help me with it?
I use last vue-cli.
I added folowing code to _@/src/sass/main.scss_
```
@import '~vuetify/src/styles/styles.sass';

$grid-breakpoints: map-deep-merge(
  (
    'xs': 340px,
    'sm': 540px,
    'md': 800px,
    'lg': 1280px - 16px,
    'xl': 1920px - 16px
  ),
  $grid-breakpoints
);
```
And added webpack derictive to _vue.config.js_
```
css: {
    loaderOptions: {
      sass: {
        prependData: '@import "@/sass/main.scss"'
      }
    }
  }
```
But no changes...

Thank you!

**Comment by Tofandel** [comment]
Shouldn't this be handled by vuetify-loader?
