### ISSUE TITLE
[Bug Report] Button default background color depends on app-bar background color

### ISSUE THREAD

**Issue by ximzavivka** [vuetifyjs/vuetify#11050]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Create variables.scss
2. Specify color for  app-bar as red
@import '~vuetify/src/styles/styles.sass';

$new-colors-light: (
        'app-bar': red)
$material-light: map-merge($material-light, $new-colors-light);

3. Configure vuetify to use this variables file.
4. Run code and see color of top bar is red now but also all default collor of buttons background turned to red. 
ER: app-bar is red, button background is  light gray
AR: app-bar is red, button background is red

### Expected Behavior
app-bar is red, button background is  light gray

### Actual Behavior
app-bar is red, button background is red

### Reproduction Link
<a href="https://codepen.io/ximzavivka/pen/MWagYBQ?editable=true&editors=101" target="_blank">https://codepen.io/ximzavivka/pen/MWagYBQ?editable=true&editors=101</a>

**Comment by billsliu** [comment]
using <v-app-bar color="red"> in your vue code, instead of change variable file. There are lots of bugs at variable file.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/e2f4da6706751598ab87eb54e0a1818d75aac8d6#diff-7206eeba8e9909e047fd63f90b4085f6R17

> 'link': #ff0000, //not working

These variables haven't been used for quite a while, they should be removed.

**Comment by ximzavivka** [comment]
@billsliu ok, got it. Just started with vuetify and looked for one place to override all colors. Will use colors and classes.Thank you
