### ISSUE TITLE
[Bug Report] v-select selected slot isn't styled correctly after selection

### ISSUE THREAD

**Issue by flyingL123** [vuetifyjs/vuetify#11068]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.3

### Steps to reproduce
Click on select to open menu, select any option.

### Expected Behavior
After a selection is made, the text of the selection and the caret should return to their initial gray/black color instead of remaining blue as if the select still has focus. This is the way the select works if the selected slot is not used. Shouldn't it still work this way even when the selected slot is used?

### Actual Behavior
The caret and the text of the selected option remain blue.

### Reproduction Link
<a href="https://codepen.io/flyingl123/pen/mdedPRP" target="_blank">https://codepen.io/flyingl123/pen/mdedPRP</a>

**Comment by KaelWD** [comment]
b4ad01a4d1308616135fc158c85373ffe88707e6
