### ISSUE TITLE
[Bug Report] VCalendar day-label slot only works for the month view

### ISSUE THREAD

**Issue by michelsteege** [vuetifyjs/vuetify#11069]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Linux x86_64

### Steps to reproduce
1.) Create a v-calendar
2.) Use the day-label slot
3.) Switch between month, week and day view

### Expected Behavior
To see the content added using the day-label slot in all views

### Actual Behavior
The content added using the day-label slot is only visible in the month view

### Reproduction Link
<a href="https://codepen.io/michelsteege/pen/qBOBNjR" target="_blank">https://codepen.io/michelsteege/pen/qBOBNjR</a>

**Comment by ClickerMonkey** [comment]
day-label is only intended to work for the month/weekly views.

We can add a slot for the daily view - we would name it something like `day-label-header` - they have slightly different functionality so they aren't equivalent enough to use the same slot.

**Comment by michelsteege** [comment]
@ClickerMonkey that would be great!
