### ISSUE TITLE
[Bug Report] Clicking in the position of icons does not trigger the action to view the menu

### ISSUE THREAD

**Issue by ibeladi-mrsool** [vuetifyjs/vuetify#11065]
### Notice
Yes I know, duplicate of #8141 (and #10964 and #10965)

### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Waterfox 56.3
**OS:** Linux x86_64

### Steps to reproduce
Click in the position of clear icon, even if the icon is not there, the event isnt fire.

### Expected Behavior
Fire the event.

### Actual Behavior
Does not fire the event.

### Reproduction Link
<a href="https://codepen.io/ibrahimbeladi/pen/mdebagJ" target="_blank">https://codepen.io/ibrahimbeladi/pen/mdebagJ</a>

### Comments
It is a duplicate of #8141 (somehow), but this affects more than the aforementioned issue. When we add several icons and none actually fires the event, this really hurts the UX and the accessibility. For end users, this is a bug and a broken website. Even thought, that issue is labeled as `working as intended` (and `has a workaround`), I urge you to reconsider that.

**Comment by jacekkarczmarczyk** [comment]
Also related https://github.com/vuetifyjs/vuetify/issues/10965
