### ISSUE TITLE
[Bug Report] v-autocomplete/v-combobox @blur behaviour

### ISSUE THREAD

**Issue by donaldma** [vuetifyjs/vuetify#11066]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.2

### Steps to reproduce
1. open console
2. focus input 
3. check console for 'handleFocus'
4. click 'no data'
5. check console for 'handleBlur'
6. re-focus input field 
7. handleFocus doesn't trigger again

### Expected Behavior
v-autocomplete/v-combobox `@blur` event should be triggered when the component `is-focused` class is removed

### Actual Behavior
v-autocomplete/v-combobox `@blur` event is triggered when the input is unfocused but `is-focused` class still exists

### Reproduction Link
<a href="https://codepen.io/donald-ma/pen/JjYPQjX" target="_blank">https://codepen.io/donald-ma/pen/JjYPQjX</a>

### Other comments
v-autocomplete/v-combobox `@focus` event seems to be triggered when the `is-focused` class is added but `@blur` event triggers even if the `is-focused` class is still there.

**Comment by Kermit-Xuan** [comment]
Can i try it？

**Comment by Miehau** [comment]
Hi, mind I work on this one?

**Comment by bigbadfatman** [comment]
As per the documentation, the expected behavior of the `@blur` event is to trigger when the input field is blurred, not the component as a whole. While the naming of the class `is-focused` might make it a little confusing, it does seem to work exactly as the docs describe.

**Comment by donaldma** [comment]
do you mind linking where this info is found? `is-focused` not being aligned with `@blur` and `@focus` seems very jarring.

**Comment by bigbadfatman** [comment]
Right here -> https://vuetifyjs.com/en/components/combobox/

In the API, the events mention that `blur` event is tied to the input being blurred.

**Comment by rizqirizqi** [comment]
is anyone already working on this issue?

**Comment by juddfranklin1** [comment]
I think that this is a documentation issue, not a functionality issue. @bigbadfatman's is correct. The first item in the [component events API documentation](https://vuetifyjs.com/en/api/v-combobox/#events) indicates that the blur refers to the `<input>`, not the component. But the same documentation describes the `focus` event as referencing focus of the component, not the `<input>`. Testing in the browser reveals that both `focus` and `blur` reference the `<input>` element.

This can be confirmed by changing @donaldma 's [Codepen](https://codepen.io/juddfranklin/pen/oNzzMOx?editors=1111) to log the event.type and event.target.

My suggestion is that this issue be referenced to the docs, which should be updated.

**Comment by bigbadfatman** [comment]
@juddfranklin1 Thanks for pointing out the documentation about focus. I hadn't noticed that. But I guess I noticed another inconsistency with focus. While clicking on "no data", the `blur` handle does get called, but the container div for the input is styled as if it hasn't lost focus. And indeed, clicking on the input field again, doesn't call the `focus` handler, but clicking on "no data" after that still calls the `blur` handler.

**Comment by juddfranklin1** [comment]
@bigbadfatman Yes, good reminder. When there are options in the combobox, the behavior appears more consistent with what one would expect. When the `no-data` slot is used (or triggered), the behavior described in the bug appears. It's not clear that the element generated by the no-data slot should be focusable at all, as this interferes with the expected browser behavior, but disabling this element also interferes with accessibility, since this is useful information for a screen reader.

I will see if I can propose a more optimal behavior for this situation.

**Comment by juddfranklin1** [comment]
In fact, I am seeing that if there is no `no-data` slot in use, but content appears that eliminates all possible values from the select, the same behavior happens - blur happens but focus does not.

**Comment by Matttaylor8910** [comment]
+1 to this documentation being inconsistent. Sending a `blur` event when the input is blurred and `focus` only when the component has lost focus does not make a ton of sense. Some thoughts:
- Documentation states that `blur` is emitted when input is blurred. We saw that `blur` is not emitted when input is blurred by selecting on one of the list items, however it is emitted when a slot is clicked on.
- Component emitted events inconsistent with classes. When the component or component's items or slots are clicked on the component retains the `is-focused` class. 
- When the component has the `is-focused` class we think it should not emit a blur event.

We played with not emitting blur from the `onBlur` function in the `VSelect` unless the component was no longer focused (had the `is-focused` class). This presented a separate issue where tabbing between comboboxes and other inputs resulted in the `blur` event emitting twice, so we prevent the `onTabDown` call of the `blur` function to emit the event. Not sure which direction this issue wants to go, but here's one solution that worked for us:
https://github.com/Matttaylor8910/vuetify/commit/3168dcfa43f368155ed6680d58843335eee2680b

Note: the docs would need to be updated to call out that the `blur` event is only emitted when the component loses focus, which I think aligns the `focus` and `blur` event behaviors.

Do you think this is a good behavior worth updating the documentation and tests for? Thanks for your consideration.
