### ISSUE TITLE
[Documentation] Fix Tile Card appearance

### ISSUE THREAD

**Issue by sdudnic** [vuetifyjs/vuetify#11063]
### Environment

**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Just click on the "Usage"-s "Tile" tab, and compare with "default" tab card style type. they are the same, should not be.

### Expected Behavior
Tile Card should not have shadow

### Actual Behavior
Tile Card has shadow

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/cards/" target="_blank">https://vuetifyjs.com/en/components/cards/</a>

**Comment by SirLamer** [comment]
They're not the same, though. The corners are not rounded in the "tile" case. It's really subtle in the documentation demo but zoom in or something, you can see it.

**Comment by MajesticPotatoe** [comment]
The difference is very subtle, and does what is intended. the `tile` prop has no effect on shadow, only border radius.

**Comment by sdudnic** [comment]
I don't understand, how to do a flat card, no borders no shadow? maybe a background color, but without shadow and border is it possible?

**Comment by MajesticPotatoe** [comment]
Yes. You could do one of the following:
* `outlined` + `tile` (you would have a border, as that's what `outlined` does)
* `tile` + `elevation="0"` + background color
* `tile` + `flat` + background color

If you have more questions please reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by sdudnic** [comment]
I suggest you display the card differences between tile and default using a specific background color 

```html
<div id="app">
  <v-app id="inspire" style="background: red">
    <v-card class="mx-auto mt-10">
      <v-card-text>text</v-card-text>
    </v-card>
    <v-card tile class="mx-auto mt-10">
      <v-card-text>text</v-card-text>
    </v-card>

  </v-app>
</div>
```

**Comment by sdudnic** [comment]
> Yes. You could do one of the following:
> 
> * `outlined` + `tile` (you would have a border, as that's what `outlined` does)
> * `tile` + `elevation="0"` + background color
> * `tile` + `flat` + background color
> 
> If you have more questions please reach out to us in our [Discord community](https://community.vuetifyjs.com).
> 
> Thank you for your contribution and interest in improving Vuetify.

**ah**, I din't understad the **`flat`** does exist! because in the examples I thought there are all the combinations possible!
