### ISSUE TITLE
[Bug Report] Autocomplete Search-Input: do not search on item select

### ISSUE THREAD

**Issue by randanunn** [vuetifyjs/vuetify#11064]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
See codepen.  
Type in search field and the "Times endpoint called" count will go up. (as expected)
Then click to select one of the options, the count goes up again. (not expected)

### Expected Behavior
The count should only go up when the user types in the field, not when they select an option.

### Actual Behavior
Count is going up when an item is selected

### Reproduction Link
<a href="https://codepen.io/lucille2/pen/KKdPbpz" target="_blank">https://codepen.io/lucille2/pen/KKdPbpz</a>

### Other comments
In example docs if you remove this line `if (this.items.length > 0) return` the items are reloaded with every search.  In my case I do not return ALL items in my api call, I only return MATCHING items, so I need to reload them every time.  This part works great by removing that line.

I do not think that selecting an item should re-call the search.  Or at least there should be a way to determine the difference between typing in the field and selecting one of the options.  Perhaps passing the event to the search? Or some sort of `search-input.options` for `search-on-select: bool`.

**Comment by ricardovanlaarhoven** [comment]
I've created a server paginated autocomplete and the problem that follows is the list with items is searched with the selected item, which results in a list of items with only the selected item.

**Comment by KaelWD** [comment]
I added `if (this.model && val === this.model.Description) return` and it only calls the API once.

**Comment by ricardovanlaarhoven** [comment]
That's indeed the workaround i'm using right now. But is that the best way?
Should the search event fire when you don't actually search for something?

**Comment by KaelWD** [comment]
`search-input` is just the text displayed in the input, and that is changed when you select an item.
