### ISSUE TITLE
[Bug Report] Treeview renders with $subgroup and $checkboxOff instead of icons

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#11060]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
See on page load.

### Expected Behavior
Icons on treeview to render.

### Actual Behavior
I see $subgroup and $checkboxOff instead of icons.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/RwWbBxJ" target="_blank">https://codepen.io/sneaky666/pen/RwWbBxJ</a>

### Other comments
The reproduction link is actually where it is working. But when I place the same exact code into a cloud environment, it renders differently. The DOM tree looks like https://imgur.com/lqdSjI3

Wondering if anyone knows what could be the issue. I am not able to replicate this in codepen because its running in a cloud environment, but any insights would be helpful.

**Comment by TheInvoker** [comment]
It seems the workaround fix is to explicitly set the expand, on, off, intermediate icons to the default value.

**Comment by KaelWD** [comment]
You're probably missing `vuetify: new Vuetify()` in the vue constructor.
