### ISSUE TITLE
[Bug Report] Navigation Drawer, mini-variant.sync is updated wrongly for true when mouse is over

### ISSUE THREAD

**Issue by guilherme-santos** [vuetifyjs/vuetify#11078]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.3

### Steps to reproduce
Click on Pin, then Click on Unpin and one more time on Pin.

### Expected Behavior
The briefcase icon should appear ONLY when the navigation drawer is with mini variant activated. 

### Actual Behavior
When you click on Pin for the second time, internally mini-variant is activated but the navigation drawer does not contract, as it happens for the first time.

### Reproduction Link
<a href="https://codepen.io/xguiga/pen/PoPYQvQ" target="_blank">https://codepen.io/xguiga/pen/PoPYQvQ</a>

### Other comments
This PR https://github.com/vuetifyjs/vuetify/pull/11048 is supposed to fix the issue.

**Comment by johnleider** [comment]
Duplicate of #8223

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
