### ISSUE TITLE
Fill-height not functioning correctly

### ISSUE THREAD

**Issue by Ragura** [vuetifyjs/vuetify#1107]
### Steps to reproduce
Use a standard app -> container -> layout -> flex -> card element order. Add fill-height to either one or all of them.

### Versions

Vue version 2.4.2
Vuetify version 0.14.5
Using Windows. Tested in Chrome and Edge.

### What is expected ?

A while ago the much needed feature of vertically aligning any layout within a container was added. I can still see it working in the documentation (final example of Pre-defined layouts), but it doesn't function in a seperate environment.

### What is actually happening ?

The layout is not vertically aligned to the center. Instead it just sits at the top. I have copied the relevant parts from the example in the documentation and it still won't work. The container does not stretch to fill the application element. Hence, it can not center the child elements correctly.

### Reproduction Link

https://codepen.io/anon/pen/GvRpZK

**Comment by johnleider** [comment]
This was happening because the main container only received a min height declaration if there was a toolbar or footer in the application.
