### ISSUE TITLE
[Feature Request] Vuetify Overides html button css

### ISSUE THREAD

**Issue by bgovi** [vuetifyjs/vuetify#11077]
### Problem to solve
Many css components outside vuetify use the html button. Its still functional with vuetify but the css is overwritten. 

### Proposed solution
Maybe a simple note on the website with the default css style that can be copied pasted into the web app to resolve. Or an actual fix.

**Comment by jacekkarczmarczyk** [comment]
In terms of documentation - some not could be added indeed
In terms of "actual fix" - it would be a duplicate of https://github.com/vuetifyjs/vuetify/issues/6258

**Comment by johnleider** [comment]
Treating as an update specifically for the docs.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
