### ISSUE TITLE
[Bug Report] Performance Issue with "beforeDestroy" in "detachable"

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#11079]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Linux x86_64

### Steps to reproduce
I'm doing some performance profiling.  I have a dialog that loads in a decently complex form.  When I close the dialog, the form is destroyed.  I'm seeing some substantial hangups in the `beforeDestroy()` handler in the `detachable` mixin.  

It appears the `this.$refs.content.parentNode.removeChild(this.$refs.content)` call is causing the hangup.  I'm not sure if there is anything to be done in this case, but we should at least evaluate what that is doing and why it's necessary.

See the following waterfall in the `$destroy` call.
![beforeDestroyWaterfall](https://user-images.githubusercontent.com/1561245/78997328-5c84f080-7b14-11ea-81de-4fe14bff8269.png)

And here is the code block causing it.  It effectively drops the frames to 0 when the dialog is closed an things are destroyed.
![beforeDestroy](https://user-images.githubusercontent.com/1561245/78997273-3e1ef500-7b14-11ea-88b6-56d004a488e3.png)

### Expected Behavior
Preferably, not have that hangup.

### Actual Behavior
It's hangs on close.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/PoPwPee" target="_blank">https://codepen.io/gabaum10/pen/PoPwPee</a>

**Comment by johnleider** [comment]
Testing this as of the latest version, the performance tests look pretty good, and this will drastically change in v3.

![image](https://user-images.githubusercontent.com/9064066/84070266-7b2b2a80-a991-11ea-9c13-80eb30c93d0d.png)


If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
