### ISSUE TITLE
[Bug Report] I Have Two same values i have to show them both but only one shows up in v-autocomplete

### ISSUE THREAD

**Issue by VinayakNivalkar** [vuetifyjs/vuetify#11073]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
1. Add the v-autocomplete component inside the application
2. pass two same values into the items option
3. sending a query shows only one value while the other is completely removed

### Expected Behavior
The two same values passed in for query in v-autocomplete must show up twice as I need it for functionality( use case:  two user accounts with the same name)

### Actual Behavior
The object passed has two same values but only one of them shows up

### Reproduction Link
<a href="https://codepen.io/Vinayak121/pen/NWGWyEy" target="_blank">https://codepen.io/Vinayak121/pen/NWGWyEy</a>

### Other comments
I have no idea whether this is a bug or not but if it's possible to solve it by passing some options please let me know

**Comment by jacekkarczmarczyk** [comment]
Items must have different values, it's not possible if you're using primiteves, but can be achieved with objects:
```
[{
  value: 'Alabama-1',
  text: 'Alabama',
}, {
  value: 'Alabama-2',
  text: 'Alabama'
}]
```

**Comment by VinayakNivalkar** [comment]
Thanks
