### ISSUE TITLE
[Documentation] Put a new example to v-tab, which show how to use v-tab to navigate in different components

### ISSUE THREAD

**Issue by bzsozsy** [vuetifyjs/vuetify#11086]
### Problem to solve
It would be real nice if there would be an example which clearly show how to use v-tab feature with nested routes to navigate between components like the proposed example link. This is a every day use case for v-tab and for me there was 3 hours research to solve it.

### Proposed solution
Example: https://codesandbox.io/s/vuetify-v-tabs-with-vue-router-6rwgo?file=/src/router.js

**Comment by MajesticPotatoe** [comment]
Duplicate #9327
