### ISSUE TITLE
[Bug Report] DataTable current page exceeds max page after filter applied

### ISSUE THREAD

**Issue by civ555** [vuetifyjs/vuetify#11088]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Data table prop is set to use a computed property for the items prop.
Navigate to the last page of a data table.
Apply filters (my component is doing filtering) to reduce the amount of pages.
the current page not changed

### Expected Behavior
the current page does not exceeds max page

### Actual Behavior
the current page is not reduced to within the boundaries of the max page of the item prop

### Reproduction Link
<a href="https://codepen.io/Civ-/pen/gOabVKE" target="_blank">https://codepen.io/Civ-/pen/gOabVKE</a>

### Other comments
Seems similar to #5426 fixed in PR https://github.com/vuetifyjs/vuetify/pull/5440#issue-226041694, but im not sure how to tell what version that PR was part of.

**Comment by nekosaur** [comment]
Your codepen is using vuetify 1.3.2. The fix is part of 1.3.7
