### ISSUE TITLE
[Bug Report] Custom checkboxes in data table not updating if field is not initially present when using a "select all" function

### ISSUE THREAD

**Issue by Thomaswaldick** [vuetifyjs/vuetify#11087]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.10
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.15

### Steps to reproduce
In my codepen, click the "Complete All" button

### Expected Behavior
The "updateAll" function should go through each item in myData and update to the bool of checkbox, this should be reflected in the checkboxes in the data table

### Actual Behavior
The checkboxes are unaffected by the update all button

### Reproduction Link
<a href="https://codepen.io/thomaswaldick/pen/pojvGNw?editors=1010" target="_blank">https://codepen.io/thomaswaldick/pen/pojvGNw?editors=1010</a>

### Other comments
Using the codepen provided, if you switch the items in the data table to "myData2" and the change function of the top checkbox to "updateAll2", then it works as expected. It seems to be due to "myData2" being initialized with the completed property

When testing locally and inspecting through the Vue tool, it seems the items are being updated along with the interal items of the data table, just not the checkboxes

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
