### ISSUE TITLE
[Feature Request] allow textFields to have tag prop

### ISSUE THREAD

**Issue by aggarwaldev** [vuetifyjs/vuetify#11082]
### Problem to solve
Currently, text fields are rendered using `input` tag only. This greatly reduce the possibilities of text fields since a `div` tag can properly render HTML (or emojis).

### Proposed solution
Text fields and text area should have a `tag` prop which will let us render `div` instead of `input`. 

It is possible to achieve this using `contenteditable` attribute along with `div` tag. Refer: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

**Comment by S9uare** [comment]
I believe this would be useful in textareas as well!

Currently I am using method similar to this one to fake highlighting some text in the textarea.
https://codersblock.com/blog/highlight-text-inside-a-textarea/
But I would need to change the css everything when vuetify updates their textarea style.

It will be nice if vuetify could all an option to render textarea as contenteditable divs!

**Comment by KaelWD** [comment]
You can't just change `<input>` to `<div contenteditable="true">` and have it work, the behaviour is completely different. There are currently no plans for any sort of wysiwyg editor (#3550) but v-input should hopefully be more customisable so this **may** be possible to implement yourself at some point.

**Comment by aggarwaldev** [comment]
@KaelWD You are right. We should not implement wysiwyg editor. Frameworks like Vuetify are not supposed to provide that kind of functionality.

But what would you suggest in order to render emojis? I suppose emojis is not just a feature these days. It's common everywhere and have use-cases beyond social media. It's how we express and communicate!
I wouldn't ask for tag prop if it was possible to render emojis using `<input>`

Please let me know your thoughts on this. I would be more than happy to drop my request if an alternative solution is available

**Comment by KaelWD** [comment]
Emojis work fine in `<input>`, unless you're trying to do custom ones like twitter

**Comment by aggarwaldev** [comment]
> unless you're trying to do custom ones like twitter
Tbh, That's exactly what I was looking for.
