### ISSUE TITLE
Can not use autocomplete with #6 Scoped slots edit

### ISSUE THREAD

**Issue by hoangkimducduc** [vuetifyjs/vuetify#1108]
When I enable AutoComplete with Objects (Image and Text). I got error (error when I search)
Error: (in file vuetify.js)
![image](https://user-images.githubusercontent.com/22253357/28505924-cc06b824-7051-11e7-8e24-19bd132d5639.png)
Fix: 
`var text = _this.getText(i);`
to
`var text = _this.getText(i[_this.itemText]);`
![image](https://user-images.githubusercontent.com/22253357/28505952-0345e184-7052-11e7-8ccc-d1f05c0d1e64.png)

Sorry!  My English is very weak, :(

**Comment by hoangkimducduc** [comment]
in file: vuetify.js 

```
if(typeof i=="string")
          var text = _this.getText(i)
        else
        var text = _this.getText(i[_this.itemText]);
```

**Comment by thelolagemann** [comment]
Have you set item-text and item-value attributes on the select component?
