### ISSUE TITLE
[Bug Report] [v-select] items content position issue

### ISSUE THREAD

**Issue by armadillo-dev** [vuetifyjs/vuetify#11098]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Mac OS 10.15.4

### Steps to reproduce
1. setting system preferences > general > show scroll bars > always, if on mac.
always reproduce on windows.
2. using `v-select` with `multiple` prop and using enough `items` prop to render scroll.
3. click `v-select` to open the items content
4. the items content is located right of the screen
5. click some item

### Expected Behavior
the item content don't moved.

### Actual Behavior
the items content move to the left by scroll width

### Reproduction Link
<a href="https://codepen.io/armadillo-dev167/pen/GRpJvwP" target="_blank">https://codepen.io/armadillo-dev167/pen/GRpJvwP</a>

**Comment by johnleider** [comment]
Which one is the correct OS for this bug?

![image](https://user-images.githubusercontent.com/9064066/79131638-86d1ea80-7d6e-11ea-9e67-3c9b70f3a93a.png)

I have been unable to recreate the issue.

**Comment by armadillo-dev** [comment]
@johnleider I used Catalina 10.15.4

**Comment by armadillo-dev** [comment]
@johnleider I recorded to reproduction this issue on my mac.
(using reproduction link: https://codepen.io/armadillo-dev167/pen/GRpJvwP)

I found some more requirements.
1.  the items content have to surfaces right of screen. 
2.  the items content's width have to set between `v-select`'s width and `max-width` prop.

![Apr-17-2020 14-17-33](https://user-images.githubusercontent.com/43581054/79534775-75624880-80b6-11ea-8273-a1407a01fce8.gif)

**Comment by johnleider** [comment]
This happens on Chrome as well.

**Comment by rayfoss** [comment]
A v-select-simple seems to be in order... one that uses the native dialogues, but looks the part a glance.

I have v-app set above my router-view, but below my non-vuetify wireframe/drawer. I haven't found a way to elegantly achieve my wireframe with vuetify components... but it seems in poor taste to have components that have such restrictive global state requirements.
