### ISSUE TITLE
[Bug Report] v-footer in v-dialog hides contents

### ISSUE THREAD

**Issue by nmummau** [vuetifyjs/vuetify#11095]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.163
**OS:** Linux x86_64

### Steps to reproduce
Create a v-dialog with the fullscreen prop
Add a data table into the dialog that extends below the viewport.
BUG: the v-footer covers the contents in the table and you cannot scroll to see it

### Expected Behavior
Goal is to have the footer fixed on the bottom of the fullscreen dialog. As contents of the dialog expand below the footer, require user to scroll to see things that are below, all while still having the fixed footer at the bottom of the dialog.

### Actual Behavior
footer covers contents that extend below viewport size

### Reproduction Link
<a href="https://codepen.io/nmummau/pen/oNjXZMq?editors=1010" target="_blank">https://codepen.io/nmummau/pen/oNjXZMq?editors=1010</a>

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/MWawLEo?editors=1010

The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
