### ISSUE TITLE
[Bug Report] Vuetify item.data-table-select slot does not pass desired  value if checkbox is clicked

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#11099]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
I tried to use the  provided slot but it breaks the app.
```
<template v-slot:item.data-table-select="item">
         <v-simple-checkbox  :value="item.item.mobileNo"></v-simple-checkbox>
</template>
```

### Expected Behavior
As provided in Codepen it should select a mobile no when the user clicks checkbox.

### Actual Behavior
Select desired value

### Reproduction Link
<a href="https://codepen.io/spider007/pen/ZEbYxrd" target="_blank">https://codepen.io/spider007/pen/ZEbYxrd</a>

### Other comments
I an not using slot in  codepen as it will break codepen and the viewer will not able to help out.

**Comment by KaelWD** [comment]
`:value` is one-way, you need to use v-model

**Comment by kunalahirrao** [comment]
I have solved it using the slot . https://codepen.io/spider007/pen/ZEbYxrd  @KaelWD .

**Comment by kunalahirrao** [comment]
However, still facing issue with select all as there is no property available on header.data-table-select to pass particular value.
