### ISSUE TITLE
Vue Plugins are not available on server after reload

### ISSUE THREAD

**Issue by smith64fx** [vuetifyjs/vuetify#111]
Hey guys.

I really like your package but it seems that the plugins which I register with Vue.use('...') are not availabe at server side.

## Reproduction:
```
git clone https://github.com/smith64fx/vuetify-ssr-problem
cd vuetify-ssr-problem
npm i
npm run dev
```

### Side Note
The only 2 things I changed are these 2 files:

app.js
```
...
import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)
...
```

GetStartedView.vue
```
<script>
import Vue from 'vue'

export default {
  created () {
    console.log(this)
    console.log("================")
    console.log(this.axios)
  }
}
</script>
```

## Here comes he bug

Now open the page at localhost:8080

In the browser you will see:
![image](https://cloud.githubusercontent.com/assets/3246782/22338600/12b8e3b0-e3e8-11e6-86fa-eb1eb7748fa7.png)

In the server console it's really strange.
The first time I open the pageI the vue-axios plugin is loaded in the server side.
```
================
{ [Function: bound wrap]
  request: [Function: wrap],
  delete: [Function: wrap],
  get: [Function: wrap],
  head: [Function: wrap],
  post: [Function: wrap],
  put: [Function: wrap],
  patch: [Function: wrap],
...........................
.............
...
```

But if I reload the page now, Vue.axios is suddenly undefined!

````
================
undefined
```

Whereas on the frontend side the Vue.axios plugin is always available.


Can you please help us? We have tried everything but we don't have any idea :/ We really want to use your SSR-Seed for our projects!

Thank you!

**Comment by smith64fx** [comment]
We found the error:
It is because of the package.json.

You placed the vue-router into the devDependencies. After putting it into the normal dependencies everything works.

We are going to fix this and make a pull request.

**Comment by johnleider** [comment]
Awesome, thank you.

**Comment by johnleider** [comment]
No response or PR received from this.
