### ISSUE TITLE
v-menu dropdown list don't work well with v-dialog

### ISSUE THREAD

**Issue by guanxudong** [vuetifyjs/vuetify#1110]
### Steps to reproduce
v-dialog work with  v-menu dropdown items
### Versions

Vue 2.4
Vuetify 0.14.5
Chrome
### What is expected ?

v-menu dropdown shoul be closed after click item
### What is actually happening ?

v-menu dropdown still open and overlay the dialog
### Reproduction Link

https://codepen.io/guanxudong/pen/LjYWgb

**Comment by johnleider** [comment]
Due to the nature of how these components interact, in order to achieve what you are looking for, you will have to do it with a different markup:

https://codepen.io/johnjleider/pen/OjJKoz
