### ISSUE TITLE
[Bug Report] 'Dense' not working for v-icon inside v-chip

### ISSUE THREAD

**Issue by SystemKeeper** [vuetifyjs/vuetify#11103]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
Put a v-icon inside a v-chip and set the 'dense' prop.

### Expected Behavior
Icon-size should be reduced to 20px, instead of 24px.

### Actual Behavior
Icon-size is still 24px.

![image](https://user-images.githubusercontent.com/1580193/79126020-6c643500-7d9f-11ea-8e14-acd36d99d779.png)

### Reproduction Link
<a href="https://codepen.io/SystemKeeper/pen/BaoNqQy" target="_blank">https://codepen.io/SystemKeeper/pen/BaoNqQy</a>

### Other comments
I'm not sure if this is working as designed and the 'dense'-prop just shouldn't be available in v-chip, but it looks like a bug to me.

**Comment by johnleider** [comment]
This property is being removed for v3 in favor of the new density styles in the latest MD spec update https://material.io/design/layout/applying-density.html#usage

Here is a workaround: https://codepen.io/johnjleider/pen/jObYEaY

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
