### ISSUE TITLE
[Bug Report] Breakpoint object "lagging" behind on manual browser resize

### ISSUE THREAD

**Issue by sebastianhaberey** [vuetifyjs/vuetify#11101]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Open reproduction link
2. Open console
3. Resize browser width with mouse resonably fast, e.g. 1920px -> 400px -> 1920px

### Expected Behavior
Breakpoint width should be 1920, breakpoint name should be 'xl'

### Actual Behavior
Breakpoint width is 450, breakpoint name is 'xs'

### Reproduction Link
<a href="https://codepen.io/sebastianhaberey/pen/GRpJxKZ" target="_blank">https://codepen.io/sebastianhaberey/pen/GRpJxKZ</a>

### Other comments
New to Vue / Vuetify so there might well be a misunderstanding on my side.

**Comment by johnleider** [comment]
This is a really old part of the breakpoint functionality: https://github.com/vuetifyjs/vuetify/commit/083d55eef5b29ab4ffd2a62e9f8bf0e4b33c257a

Some recommend a 66ms debounce up to 250ms. There are also guides using animationFrame. There is a newer api out https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver that we could make use of; but way out of scope of this bug.

@vuetifyjs/core-team thoughts?

**Comment by jacekkarczmarczyk** [comment]
Can you link to those guides? I guess it's for optimization when in `resize` listener you're doing more things than just setting some variables. In this case we don't actually need debouncing in breakpoint mixin but rather in the place where you're using the actual `width`/`height` variables from the breakpoint

**Comment by johnleider** [comment]
https://gomakethings.com/debouncing-events-with-requestanimationframe-for-better-performance/
https://gist.github.com/cferdinandi/9029584
https://css-tricks.com/snippets/jquery/done-resizing-event/

**Comment by johnleider** [comment]
After team discussion we are going to leave this to userland. We have a debounce in the breakpoint service, just watch the `$vuetify.breakpoint.width` property and adjust accordingly.

https://github.com/vuetifyjs/vuetify/issues/11101#issuecomment-612979861

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
