### ISSUE TITLE
[Feature Request] the <code> color and display should be cumstom 

### ISSUE THREAD

**Issue by little3201** [vuetifyjs/vuetify#11100]
### Problem to solve
the <code> color and display should be cumstom, not default: display is inline-block and color is red 

### Proposed solution
the <code> color and display should be cumstom, not default: display is inline-block and color is red, when i show markdown content , it contains the <code> ，the result is not i want

**Comment by johnleider** [comment]
Fixed in 47042cd55

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
