### ISSUE TITLE
[Feature Request] Make text-field date picker a standalone component

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#11114]
### Problem to solve
The date-picker inside a text-field I think its the most common use of a date picker, in fact I never needed the date picker on its own, I always need it in the text-field format, so I think that the whole [v-menu v-text-field v-date-picker thing](https://vuetifyjs.com/en/components/date-pickers/#date-pickers-in-dialog-and-menu) is too much for such a common use case

### Proposed solution
Create a new component that composes these components so that adding a text date picker is easier, maybe called v-text-date-picker

**Comment by YipingRuan** [comment]
Will be looking forward for your PR?

**Comment by denmasyarikin** [comment]
Or at least provide v-calendar for us to create my own date picker with v-menu. can you imagine in one form has four date picker, and by default show it's calendar.

**Comment by douglasg14b** [comment]
Where the docs that OP linked removed?

**Comment by KaelWD** [comment]
#19680
