### ISSUE TITLE
[Documentation] Adding Uzbek Language too.

### ISSUE THREAD

**Issue by PremiumNoFreemium** [vuetifyjs/vuetify#11110]
### Problem to solve
By adding this language you may help so many developers who are working with Vuetify.
Believe, there are at least 100 middle 300 junior and  15 senior developers working with Vuetify.
But I know from the meeting of web-developers in Uzbekistan: They said our interests are about Vuetify than other frameworks. Because Vuetify is the best solution for the Frontend of VueMade websites/ 

### Proposed solution
Adding Uzbek language may contribute to Vuetify for being widely spreading.
Really I am barely writing in English sorry. I tried to do with my knowledge not any Google translators.

### More:
Here I may help. But only me because other have their works. So this may take just a little bit more time. I will be so happy if you give such opportunity. But if you can do it faster I appreciate your work. :)

**Comment by MajesticPotatoe** [comment]
Translations are handled via our Crowdin project. I have added Uzbek to the available languages so you or others may contribute to the translations. To get started simply select the "Help Translate" option in the language dropdown of the docs. Note the actual translations will not be selectable on the docs until at least 15% is translated.

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
