### ISSUE TITLE
[Bug Report] Checkbox graphics do not represent :value props

### ISSUE THREAD

**Issue by rioukkevin** [vuetifyjs/vuetify#11119]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
 I create a renderless component that can be around data-iterator and data-table when server-side pagination. I handle the select-all checkbox (with exclusion btw). When it's checked, on page change, it select all new entries. It's something around the v-model so with data-iterator, when i select all and change page, all checkboxs have in vuedevtools the value equal as true but when we looks at it in the webpage, the graphic representation of the value is not what the devtools say.

### Expected Behavior
Checkbox graphical state represents the :value props

### Actual Behavior
Checkbox graphical state do not represent the :value props

### Reproduction Link
<a href="https://codesandbox.io/s/checkbox-graphics-state-is-not-equal-to-state-xbv94 " target="_blank">https://codesandbox.io/s/checkbox-graphics-state-is-not-equal-to-state-xbv94 </a>

### Other comments
After claiming help on discord, I have no response so i put it here, I don't know if it's a problem with my code or the Vuetify code

Thank you
PS: I have a bad English i'm working on ;)

Have a nice day and be happy

**Comment by jacekkarczmarczyk** [comment]
Please reduce your reproducton, that's too much to debug

**Comment by rioukkevin** [comment]
I update it with more comment and delete table example here https://codesandbox.io/s/checkbox-graphics-state-is-not-equal-to-state-fork-rz397

**Comment by KaelWD** [comment]
Checkbox v-model is `input-value`, not `value`

**Comment by rioukkevin** [comment]
Oki, thx

**Comment by osvalth** [comment]
> Checkbox v-model is `input-value`, not `value`
Thanks
