### ISSUE TITLE
[Bug Report] v-select menu should be toggle with menu props overflowY

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#11116]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
- have an extended select input (:menu-props="{ overflowY: true }")
- click on select input, not the toggle icon (toggle icon is working)
- select menu should be toggle

### Expected Behavior
v-select menu should be toggle with menu props overflowY

### Actual Behavior
v-select menu should not toggle with menu props overflowY

### Reproduction Link
<a href="https://codepen.io/mahammad-sixberries/pen/vYNLBbM?editors=1010" target="_blank">https://codepen.io/mahammad-sixberries/pen/vYNLBbM?editors=1010</a>

**Comment by mahammad-sixberries** [comment]
Any temporary solution?

**Comment by jacekkarczmarczyk** [comment]
`:menu-props="{ nudgeTop: 60 }"`?

**Comment by jacekkarczmarczyk** [comment]
`v-menu` doesn't have `overflow-y` prop, please clarify

**Comment by johnleider** [comment]
This will not be resolved before v3 and v3 is rebuilding all of this from the ground up.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
