### ISSUE TITLE
[Bug Report] Tabs are causing memory leak when they are in zero width parent

### ISSUE THREAD

**Issue by martincapek** [vuetifyjs/vuetify#11122]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.3

### Steps to reproduce
Put <v-tabs> in div with 0 width.

### Expected Behavior
Tabs are not causing a memory leak

### Actual Behavior
Tabs causing a memory leak and never stops update. 

### Reproduction Link
<a href="https://codepen.io/justmartinhere/pen/vYNLZNq" target="_blank">https://codepen.io/justmartinhere/pen/vYNLZNq</a>

### Other comments
Tested in vue devtools.

**Comment by RobbinBaauw** [comment]
For reference, I get the following in my vue devtools:
![vuetify-11122](https://user-images.githubusercontent.com/5289010/80521009-92d2c480-898a-11ea-9123-19984fe4c5d1.gif)

So it seems to turn the slider on and off continuously, therefore creating new components and destroying them, hence the memory leak & a lot of GC
