### ISSUE TITLE
[Bug Report] When selecting text field contents, focus jumps to other text fields

### ISSUE THREAD

**Issue by neryams** [vuetifyjs/vuetify#11128]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Select the text in the first text field, ending the selection with the mouse cursor outside of the text field on mouse up. (you can edit or delete the contents, that doesn't matter)

Then, select the text in the second text field, ending the selection wtih the mouse cursor above the other text field. The other text field will get selected.

### Expected Behavior
The text field you just selected the text field for should retain the focus

### Actual Behavior
The focus switches to another text field and you end up typing in the other text field.

### Reproduction Link
<a href="https://codepen.io/rohmori/pen/YzywLRx?editors=1011" target="_blank">https://codepen.io/rohmori/pen/YzywLRx?editors=1011</a>
Video:
https://www.dropbox.com/s/l6amtkyezmv4nuz/Vuetify%20Template.webm?dl=0

### Other comments
This problem is related to #5018. It's a similar issue, but still remains in the latest version of Vuetify. The mouse up event is not caught when the mouse cursor ends up outside of the text field on mouse up. You guys could add a setPointerCapture call on the input on mouse down.

**Comment by johnleider** [comment]
This happens because when you press the mousedown in the first text field, it sets the value of `hasMouseDown` to true. It relies on the mouseup event in order to set that value to false. I think this might be as simple as when setting `hasMouseDown` to false once we lose focus.

**Comment by johnleider** [comment]
After careful consideration I've decided this is not worth pursuing as part of the v2.x milestone, and will not be an issue in Vuetify 3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
