### ISSUE TITLE
[Documentation] Block prop for FAB™?

### ISSUE THREAD

**Issue by nainardev** [vuetifyjs/vuetify#11137]
### Environment

**Browsers:** Chrome 84.0.4115.4
**OS:** Android 8.1.0

### Steps to reproduce
https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player

### Expected Behavior
No block option for FAB™

### Actual Behavior
![Screenshot_2020-04-16-14-31-08-134_com chrome canary](https://user-images.githubusercontent.com/59839368/79436919-1f769d80-7fef-11ea-9d16-e8e5b62e241c.jpg)

### Reproduction Link
<a href="https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player" target="_blank">https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player</a>

**Comment by MajesticPotatoe** [comment]
Incorrect reproduction link. Though probably not the greatest looking and impractical, It is still a valid prop combination that can be used (though may be very edge case)
