### ISSUE TITLE
[Bug Report] v-data-table pagination event fired twice... (again!)

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#11130]
### Environment
**Vuetify Version:** 2.2.22
**Last working version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Below is the steps on how I made the reproduction link - https://codepen.io/ais-one/pen/MWaKBBG

1.Go to documentation (Vuetify version 2.2.22):

https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side

2. Open the codepen

3. add event to <v-data-table>:

@pagination="doPage"

4. add method:

doPage () { console.log('Paged', Date.now()) },

5. run and see on console.log... the pagination event is firing twice.

### Expected Behavior
pagination event should only fire once

### Actual Behavior
pagination event fired twice

### Reproduction Link
<a href="https://codepen.io/ais-one/pen/MWaKBBG" target="_blank">https://codepen.io/ais-one/pen/MWaKBBG</a>

### Other comments
Refer to https://github.com/vuetifyjs/vuetify/issues/10715

**Comment by ais-one** [comment]
I am able to get this problem because I have an application where in dev mode, the token lifespan is only 10 seconds and there is a refresh token...

So after token expires, if the table is queried and the API fires twice, bad things happen to my application...

**Comment by asadhshujau** [comment]
having the same problem this happens when :

- the page initially loads
- do a serverside search with the help of a textfield

**Comment by adrianschubek** [comment]
Im having the same issue on latest version 2.2.29.

**Comment by ais-one** [comment]
It may be firing because the event is being observed in 2 places...

@pagination and :options.sync

maybe this should not be the way things are being done? there are actually a lot of events / emits available in this v-data-table component.

I managed to get things to work (for my use case) by working on using only the :options.sync

Looking forward to a Vue3 compatible esm build of Vuetify...

**Comment by asadhshujau** [comment]
im not using :options.sync 

just using *@pagination* still the issue is there

**Comment by asadhshujau** [comment]
> It may be firing because the event is being observed in 2 places...
> 
> @Pagination and :options.sync
> 
> maybe this should not be the way things are being done? there are actually a lot of events / emits available in this v-data-table component.
> 
> I managed to get things to work (for my use case) by working on using only the :options.sync
> 
> Looking forward to a Vue3 compatible esm build of Vuetify...

just tried with @update:options and it works 
seems like @pagination event has the issue

**Comment by kosratdev** [comment]
I have the same issue with the latest version 2.3.13
My data table code snippet
```
<!-- Data table -->
        <v-data-table
          :footer-props="$data.$dataTableOptions.pagination"
          :headers="headers"
          :items="saleDataTable.results"
          :loading="loadingDataTable"
          :options.sync="$data.$dataTableOptions"
          :server-items-length="saleDataTable.count"
        >

          <v-alert slot="no-data" class="ma-2" type="error">
            {{ $t('dataTable.noResult') }}
          </v-alert>
        </v-data-table>

        <!-- External Pagination -->
        <v-pagination
          v-model.lazy="$data.$dataTableOptions.page"
          :length="Math.ceil(saleDataTable.count / $data.$dataTableOptions.itemsPerPage) || 1"
          :total-visible="$data.$dataTableOptions.totalVisiblePage"
        />
```

I'm using `v-pagination` as an external pagination and I watch the `options` if it is changed I will call a method to update my data table so that the issue starts here when I click to the next page from external pagination then the **watch** called twice.

**Comment by isimonov** [comment]
**Vuetify Version**: 2.3.15
I have the same issue to.

**Comment by kabrachups** [comment]
same issue with page.sync

**Comment by AAndonio** [comment]
An alternative that I used on a project is to not use @pagination event but @update:options. This will be fired only one time and it's enough for server side pagination

**Comment by starnick21** [comment]
same issue on server-side pagination.  @update:option instead of @pagination is working for me.
Thanks @AAndonio

**Comment by johngoben-righteye** [comment]
In case you're like me and a fuller code example is required, 

` <v-data-table
 @update:options="handler($event)"
/>`

is what you need instead of `:options.sync="options"`

**Comment by imsat** [comment]
Tnx @AAndonio, you save my life

**Comment by ampminfo** [comment]
I was able to reduce to one trigger with the :options.sync but when clicking on a page number it trigger twice again

I did the following
<v-data-table
          :headers="headers"
          :items="demandes"
          :options.sync="options"
          :loading="loading"
          :items-per-page="10"
          
          item-key="guid"
          show-select
          v-model="selectedTasks"
          :page.sync="currentPage"
          :pageCount="totalPages"
          :server-items-length="totalNumberOfItems"
          :footer-props="{itemsPerPageOptions: [10,25,50,100,200],showFirstLastPage: true}"
          @update:items-per-page="handlePageChange($event,1)"
          @update:options="handlePageChange($event,2)"
          @update:sort-by="handleSortChange('by', $event)"
          @update:sort-desc="handleSortChange('desc', $event)"
          show-expand
          :single-expand="singleExpand"
          :expanded.sync="expanded"
          @item-expanded="toggleExpand"
          
      >...

      </v-data-table>

methods: {
        handlePageChange: function(e,no) {
            console.log('::'+no);
            console.log('handlePageChange')
            this.updateTableData();
        },




CONSOLE LOG

::undefined
demandesTable.js?ver=1.0.0:562 handlePageChange
demandesTable.js?ver=1.0.0:561 ::2
demandesTable.js?ver=1.0.0:562 handlePageChange


it seems that the first trigger did not come from my events....

**Comment by hunterlord** [comment]
> I was able to reduce to one trigger with the :options.sync but when clicking on a page number it trigger twice again
> 
> I did the following
> <v-data-table
> :headers="headers"
> :items="demandes"
> :options.sync="options"
> :loading="loading"
> :items-per-page="10"
> 
> ```
>       item-key="guid"
>       show-select
>       v-model="selectedTasks"
>       :page.sync="currentPage"
>       :pageCount="totalPages"
>       :server-items-length="totalNumberOfItems"
>       :footer-props="{itemsPerPageOptions: [10,25,50,100,200],showFirstLastPage: true}"
>       @update:items-per-page="handlePageChange($event,1)"
>       @update:options="handlePageChange($event,2)"
>       @update:sort-by="handleSortChange('by', $event)"
>       @update:sort-desc="handleSortChange('desc', $event)"
>       show-expand
>       :single-expand="singleExpand"
>       :expanded.sync="expanded"
>       @item-expanded="toggleExpand"
>       
>   >...
> 
>   </v-data-table>
> ```
> 
> methods: {
> handlePageChange: function(e,no) {
> console.log('::'+no);
> console.log('handlePageChange')
> this.updateTableData();
> },
> 
> CONSOLE LOG
> 
> ::undefined
> handlePageChange
> ::2
> handlePageChange
> 
> it seems that the first trigger did not come from my events....

if the 'totalNumberOfItems'  change to undefined ,  may fire twice.

**Comment by ampminfo** [comment]
I'm not sure this helps... I found out that my First and Last Page buttons are not working properly compared to the page number buttons which are ok.

First and last page button trigger the @update:option events but :page.sync et triggered after so currentPage variable is not right when enterring my event function so wrong page is displayed.  On first page load with my table, If I click the Last Page button and then the first page button, my last page is displayed so meaning that the event of changing currentPage variable is done after.  

my data is loaded through server side paging using ajax by using the current page number, number of items per page and sorting (using mysql limit syntax)

**Comment by ampminfo** [comment]
Even previrous/next page not working anymore.  Which is weird because everything was ok before...I am using the latest from CDN

https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js
https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js

**Comment by ampminfo** [comment]
https://codepen.io/ampminfo/pen/dyNqxQm

**Comment by KarmaBlackshaw** [comment]
Is there a way to not trigger the options on load?

**Comment by iliasaddab** [comment]
i left only the :options.sync and then
watch: {
    options(newValue, oldValue) {
      let cont = false
      if(oldValue.page!==newValue.page)cont=true
      if(oldValue.itemsPerPage!==newValue.itemsPerPage)cont=true
      if(oldValue.sortBy!==newValue.sortBy)cont=true
      if(oldValue.sortDesc!==newValue.sortDesc)cont=true
      if(cont)this.fetchItems()
    }
  },

**Comment by KarmaBlackshaw** [comment]
Thanks @iliasaddab!

I did the following based on your code:

```js
 watch: {
    options (prev, curr) {
      const watchProps = ['page', 'itemsPerPage', 'sortBy', 'sortDesc']

      for (let i = 0; i < watchProps.length; i++) {
        const key = watchProps[i]

        if (prev[key] !== curr[key]) {
          return this.fetchItems()
        }
      }
    }
  }
```

And it worked like a charm 🔥

**Comment by amine-bourouba** [comment]
for me using `:options.sync="options"` and setting a watcher for the `options` variable made things work properly

**Comment by bengrandin-thetribe** [comment]
Still a pb 2 years later :/

**Comment by simonmaass** [comment]
I am having the same problem, that a deep watcher on options triggers the watcher on inital load
