### ISSUE TITLE
[Documentation] Use Radio™ buttons instead of Checkboxes

### ISSUE THREAD

**Issue by nainardev** [vuetifyjs/vuetify#11136]
### Environment

**Browsers:** Chrome 84.0.4115.4
**OS:** Android 8.1.0

### Steps to reproduce
https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player

### Expected Behavior
Its logical to use Radio buttons as only one of top or bottom can be selected. Same with left or right

### Actual Behavior
Uses Checkboxes for selecting one option
![Screenshot_2020-04-16-14-25-35-570_com chrome canary](https://user-images.githubusercontent.com/59839368/79436432-7c258880-7fee-11ea-88e7-b7c3755a1a8f.jpg)

### Reproduction Link
<a href="https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player" target="_blank">https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player</a>

**Comment by MajesticPotatoe** [comment]
Reproduction link is invalid. I would agree if the props were required and were simple booleans. The checkboxes are set up to perform the same functions, but also be unselectable without bloating the example. This is also already in the process of being refactored.
