### ISSUE TITLE
[Feature Request] v-color-picker new prop to hide sliders / show swatches only ?

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#11138]
### Problem to solve
In my use case, I'd like to enable the user to only pick a color among a predefined set of colors (aka. `swatches`) But there is no prop to remove these sliders :
![image](https://user-images.githubusercontent.com/48165976/79444700-cf421000-7fdb-11ea-8ac3-0f4742a0a5b0.png)

Would it be possible to add this feature ?

From now on I did this :

```
<v-color-picker
  flat
  hide-canvas
  hide-inputs
  show-swatches/>
```

which result in this :

![image](https://user-images.githubusercontent.com/48165976/79444964-31027a00-7fdc-11ea-937c-2151b3f04882.png)

### Proposed solution
Add a prop `hide-sliders` (or whatever the name) so that it can be hidden.

Then it would be possible to have a colorpicker that looks like this (if `:swatches` is defined of course or it displays the full list) :

![image](https://user-images.githubusercontent.com/48165976/79444733-de28c280-7fdb-11ea-9b9f-1383119ed403.png)

**Comment by ryo-gk** [comment]
About design spec,
where is it good to place the color-preview?
I have now 2 ideas, and I want to hear your opinions.

**Case1. just hide sliders.**
![image](https://user-images.githubusercontent.com/62658104/86946601-956d4980-c185-11ea-8708-a03cbe473e1d.png)

**Case2. arrange next to `mode(rgba, hsla, hexa)`**
![image](https://user-images.githubusercontent.com/62658104/86946687-b6359f00-c185-11ea-9430-f0e95f60cbc4.png)

**Comment by laurent-brisbois** [comment]
@ryo-gk 
Is it mandatory to have a color preview ? I mean check the last image of my original post. there is a `v` and a border on the chosen color in the swatches.

**Comment by ryo-gk** [comment]
Thank you for your quick reply.
You mean like below images if `hide-sliders` is true, is my understand right?
![image](https://user-images.githubusercontent.com/62658104/86987426-fa01c600-c1d0-11ea-8184-96e81a945cff.png)

**Comment by laurent-brisbois** [comment]
@ryo-gk 
Yes. And if you hide the rgba too only the swatches remain.

**Comment by ryo-gk** [comment]
Thanks, I'll take this one.

**Comment by tylermmorton** [comment]
Great suggestion, I'll be watching this closely :) Let me know if I can help with the PR

**Comment by laurent-brisbois** [comment]
@ryo-gk Are you still on it ? :)

**Comment by mattStayner** [comment]
I would like this too, only I would like to just show the swatches and the transparency slider.

**Comment by GTaylorRabbit** [comment]
Would love the prop: hide-sliders as well.
I am currently using the disabled prop, as it only seems to disable the sliders of the color picker. The sliders still show, but they are greyed out:
![image](https://user-images.githubusercontent.com/48206440/98944739-2e2c2100-24fa-11eb-8663-d32c3b5b8654.png)

**Comment by Mikilll94** [comment]
It seems that @ryo-gk PR is abondoned. That's why I have created a new PR https://github.com/vuetifyjs/vuetify/pull/12618 with almost the same changes as @ryo-gk did.
