### ISSUE TITLE
[Documentation] Can't close bottom sheet

### ISSUE THREAD

**Issue by nainardev** [vuetifyjs/vuetify#11135]
### Environment

**Browsers:** Chrome 84.0.4115.4
**OS:** Android 8.1.0

### Steps to reproduce
https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player

### Expected Behavior
A close button or clicking backdrop would close it

### Actual Behavior

![Screenshot_2020-04-16-14-20-03-165_com chrome canary](https://user-images.githubusercontent.com/59839368/79435918-dffb8180-7fed-11ea-816b-5ce348fc5a3d.jpg)

### Reproduction Link
<a href="https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player" target="_blank">https://dev.vuetifyjs.com/en/components/bottom-sheets/#music-player</a>

**Comment by MajesticPotatoe** [comment]
Tested this on PC and mobile (android/chrome) and it closes without issue when clicking outside of the bottom sheet.
