### ISSUE TITLE
[Bug Report] Autocomplete change items 

### ISSUE THREAD

**Issue by pliersch** [vuetifyjs/vuetify#11145]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Windows 10

### Steps to reproduce
- click "replace" --> all items will be replaced
- click "splice" --> "buzz1" will be replaced by "baz"
- click "replace" again --> nothing changed

### Expected Behavior
The items should be replaced again

### Actual Behavior
Autocomplete doesn`t update the items.

### Reproduction Link
<a href="https://codepen.io/Hourby/pen/PoPZrJZ?editors=1010" target="_blank">https://codepen.io/Hourby/pen/PoPZrJZ?editors=1010</a>

### Other comments
Click on the assign button doesn`t never work.

**Comment by KaelWD** [comment]
The second replace doesn't do anything, `items` and `itemsNew` are now the same object, and `value` is already `'foo1'`. 

https://medium.com/@naveenkarippai/learning-how-references-work-in-javascript-a066a4e15600
