### ISSUE TITLE
[Bug Report] v-toolbar in slot:top of v-data-table does not inherit border radius of table

### ISSUE THREAD

**Issue by Munhuggas** [vuetifyjs/vuetify#11146]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Mac OS 10.15.3

### Steps to reproduce
Create a `v-data-table` and put a `v-toolbar` in the `v-slot:top`.

### Expected Behavior
Expected `border-radius` is `inherit`.

### Actual Behavior
The `border-radius` is `0`.

### Reproduction Link
<a href="https://codepen.io/munhuggas/pen/qBOZQgv" target="_blank">https://codepen.io/munhuggas/pen/qBOZQgv</a>

### Other comments
Compare with using a `v-toolbar` in a `v-card`.

**Comment by heiybb** [comment]
Exactly the same bug in the Doc https://vuetifyjs.com/en/components/data-tables/#crud-actions

Edit it in Codepen and change the v-data-table's class from `elevation-1` to `elevation-5 ma-4` will make it more easily to identify the border-radius missing

BTW the invert example color for the CRUD-Actions is also not working correctly.
