### ISSUE TITLE
[Feature Request] Improve v-tooltip transition on mouse leave

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#11152]
### Problem to solve
when we leave the tooltip, then "hide-the-tooltip" transition occurs just like examples in the Transitions docs

### Proposed solution
-

**Comment by KaelWD** [comment]
Can you clarify what you mean by this? "the transition occurs just like examples" doesn't sound like a problem to me.

**Comment by handhikadj** [comment]
when onMouseLeave-ing tooltip, I can't see any transition occurs. hence called "hide-the-tooltip" transition

**Comment by KaelWD** [comment]
There's a short (75ms) fade transition as per MD specs: https://material.io/components/tooltips#behavior
