### ISSUE TITLE
[Feature Request] Add someone to Vuetify TreeSelect

### ISSUE THREAD

**Issue by DmitrySkibitsky** [vuetifyjs/vuetify#11154]
### Problem to solve
This is what I would like to see in Vuetify https://vue-treeselect.js.org/

### Proposed solution
oh may

**Comment by RaiBnod** [comment]
Yes, if we include this one it would have been great.

**Comment by Mert75** [comment]
Already got the [Treeview](https://vuetifyjs.com/en/components/treeview/) component, perhaps you could integrate this with the VAutocomplete to replicate

**Comment by KaelWD** [comment]
Duplicate of #3049
