### ISSUE TITLE
[Bug Report] iOS vertical scrollbar appears when it shouldn't

### ISSUE THREAD

**Issue by Covik** [vuetifyjs/vuetify#11158]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
On iOS 12.4 (Safari) open "Baseline" or "Center" from "Pre-made layouts" in Vuetify docs.

### Expected Behavior
Everything should fit to the screen without scrollbar

### Actual Behavior
Scrollbar appears

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/pMvGQO" target="_blank">https://codepen.io/johnjleider/pen/pMvGQO</a>

### Other comments
I've noticed this while I was developing my app and then I checked in the docs and the same behaviour happens. Basically, if you open "Centered" layout aka login form you can scroll up and down when there is no additional content.

I don't have Apple desktop product so I can't provide additional info from debug tools.

Well, I can do some basic "debugging"; I opened two examples ("baseline" and "centered"), took a screenshot with scrollbar moved to top, and then measured distance from scrollbar end to page body end. In both cases the difference was about 240px.

![Baseline](https://i.imgur.com/gTApVXm.png)

![Centered](https://i.imgur.com/2hS7ak3.png)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
