### ISSUE TITLE
[Bug Report] v-select options becomes transparent when attach prop is used

### ISSUE THREAD

**Issue by jpquilala** [vuetifyjs/vuetify#11153]
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.2.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Linux x86_64

### Steps to reproduce
* create navigation drawer component
* create v-select component 
* create v-textfield underneath the v-select component
* set attach prop to v-select component
* click on the v-select to display the options

### Expected Behavior
* v-select options should not be transparent

### Actual Behavior
* v-select options is transparent

### Reproduction Link
<a href="https://codepen.io/alvagenesis/pen/qBONqjR" target="_blank">https://codepen.io/alvagenesis/pen/qBONqjR</a>

**Comment by thomas-romuald** [comment]
Hi, does the fix works for anybody ? I still have the bug.

On the reproduction link provided with this issue https://codepen.io/alvagenesis/pen/qBONqjR if we change the dependency to the latest version https://cdn.jsdelivr.net/npm/vuetify@2.4.3/dist/vuetify.min.js the behavior hasn't changed
