### ISSUE TITLE
[Bug Report] Image placeholder with v-progress-circular performance issue

### ISSUE THREAD

**Issue by supraniti** [vuetifyjs/vuetify#11157]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
When displaying a moderate amount of images in a grid (in the example - 48 images),
the progressbar components consume a lot of cpu,
this is only (partly) stops when all of the components are viewed (my guess is there's an intersection observer responsible for the component inner state)
the result is - an extensive cpu usage on an idle page.

### Expected Behavior
progress-bar should not trigger repaints when not visible

### Actual Behavior
progress-bars consuming cpu when not visible

### Reproduction Link
<a href="https://codepen.io/supraniti/pen/vYNKQGz" target="_blank">https://codepen.io/supraniti/pen/vYNKQGz</a>

**Comment by KaelWD** [comment]
#2324, #785, #720, #553

**Comment by Eygle** [comment]
Up
