### ISSUE TITLE
[Bug Report] label inside v-img isn't shown

### ISSUE THREAD

**Issue by Unkrass** [vuetifyjs/vuetify#11151]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.13.6

### Steps to reproduce
Add a row with a col containing a span inside a v-img. See Codepen.

### Expected Behavior
The span with the label should be shown on top of the image

### Actual Behavior
The span with the label gets margin-left: -100% and is off the screen

### Reproduction Link
<a href="https://codepen.io/unkrass/pen/gOarERY" target="_blank">https://codepen.io/unkrass/pen/gOarERY</a>

### Other comments
I also asked this question on stackoverflow. https://stackoverflow.com/questions/61276503/vuetify-label-inside-v-img-isnt-shown

**Comment by KaelWD** [comment]
You have `display: block` on it.
