### ISSUE TITLE
[Bug Report] Tooltip not updating activator element

### ISSUE THREAD

**Issue by jpereira94** [vuetifyjs/vuetify#11166]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.4

### Steps to reproduce
Create a v-tooltip component with an activator prop whose value changes as the user hovers different buttons in the page.

### Expected Behavior
The tooltip should appear on the bottom of the currently hovered button.

### Actual Behavior
When the first button is hovered everything is ok. However, when I hover a second button the tooltip appears below the previously hovered button. Only when I leave the button and hover it again (the same button) does the tooltip appear correctly below the second button. It seems that after the activator is initially  set it only updates after two times.

### Reproduction Link
<a href="https://codepen.io/japereira94/pen/KKdgyoz" target="_blank">https://codepen.io/japereira94/pen/KKdgyoz</a>

### Other comments
I have a v-data-table with hover 500+ records. Each row on the table has a button that requires a tooltip, however if I use a tooltip component in each row it reduces the performance of the page.

**Comment by KaelWD** [comment]
You should wait for `activator` to update before showing it: https://codepen.io/kaelwd/pen/qBOaxwr?editors=1010

**Comment by jpereira94** [comment]
Hello, thank you for the quick answer. It worked 👍
