### ISSUE TITLE
[Bug Report] V-Select is editable with arrow keys in read-only mode

### ISSUE THREAD

**Issue by tom-rb** [vuetifyjs/vuetify#11164]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. Define prop readonly to true of a v-select component
2. Select the component (click or tab to it)
3. Press up or down arrows and the field will change its value, even being read-only.

### Expected Behavior
Read only v-select should not change its value when pressing up/down arrows.

### Actual Behavior
Value of v-select changes when using the arrows in read-only mode.

### Reproduction Link
<a href="https://codepen.io/tomrb/pen/bGVwwPa" target="_blank">https://codepen.io/tomrb/pen/bGVwwPa</a>

### Other comments
I don't know since when it started, just noticed this on latest release.

**Comment by johnleider** [comment]
Copy and save the images:

https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/US.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/DE.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/DE.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/DE.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/DE.png

**Comment by tom-rb** [comment]
thanks guys, you are awesome.
