### ISSUE TITLE
[Feature Request] Data Table selected rows should allow populating v-model with a field from the selected row

### ISSUE THREAD

**Issue by zolamk** [vuetifyjs/vuetify#11167]
### Problem to solve
Right now when rows are selected on a data table vuetify populates the variable passed to `v-model` with an array of the selected items but it might be useful if the user of the component could select a field from the item the array is populated with, which is usually an id field or something like that

### Proposed solution
add a new prop to the data table component where the required field is passed and vuetify can use that to populate the array

**Comment by manakuro** [comment]
You can achieve that by using [item.data-table-select](https://vuetifyjs.com/ja/api/v-data-table/#slots-item.data-table-select) slot like so,


```.vue
                      <v-data-table :items="items">
                        <template #[`item.data-table-select`]="{ item }">
                          <v-checkbox
                            v-model="selected"
                            :value="Number(item.id)"
                          />
                        </template>
```

**Comment by KaelWD** [comment]
v3 supports `item-value` and `return-object` like other select components
