### ISSUE TITLE
[Bug Report] -slot:items.actions are not loading

### ISSUE THREAD

**Issue by Moxie1776** [vuetifyjs/vuetify#11161]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0, Google Chrome
**OS:** Linux

### Steps to reproduce
I followed the code on the website and customized it to my data. Please see attached code pen for duplicating

### Expected Behavior
Edit and delete icon's to draw. At times none of the data in the table will draw. The response seems to be inconsistent.

### Actual Behavior
The icon's to draw so I can implement @click functions for editing and deleting rows. Also, the data in the table to load consistently although I suspect whatever causes the failure with the icon's to draw is also causing the table to not load the rest of the data part of the time.

### Reproduction Link
<a href="https://codepen.io/moxie1776/pen/vYNXNgz" target="_blank">https://codepen.io/moxie1776/pen/vYNXNgz</a>

**Comment by jacekkarczmarczyk** [comment]
it's `item.actions`

**Comment by Moxie1776** [comment]
> it's `item.actions`

I have tried it both ways that does not fix the problem.

**Comment by jacekkarczmarczyk** [comment]
It does fix the problem in codepen when I change `items.actions` to `item.actions`

![image](https://user-images.githubusercontent.com/15625235/79755309-37189380-8319-11ea-8f8d-1e246c802131.png)

**Comment by Moxie1776** [comment]
> It does fix the problem in codepen when I change `items.actions` to `item.actions`
> 
> ![image](https://user-images.githubusercontent.com/15625235/79755309-37189380-8319-11ea-8f8d-1e246c802131.png)

I should have been more clear. The action icon's draw, which I opened this post for. The second problem I mentioned is the table populates erratically. That problem is not resolved. I guess I need to replicate all of that and probably open a new problem, or more than likely a question. Thank for your time.

**Comment by jacekkarczmarczyk** [comment]
That might be a problem with items not having unique `id` prop, anyway if there's a problem please create one issue per problem and provide exact reproduction steps
