### ISSUE TITLE
[Bug Report] Button color in tab

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#11171]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.3

### Steps to reproduce
Add VBtn inside a VTab.

### Expected Behavior
The button's color to match tab's color state (active, inactive).

### Actual Behavior
The button color is set to default and doesn't change with the tab's state.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/rNOMRJj" target="_blank">https://codepen.io/thomaskientz/pen/rNOMRJj</a>

**Comment by ThomasKientz** [comment]
Imo buttons in tabs are seen in a lot of places, like in your browser. For dynamic tabs, a close button inside a tab is very convenient. A tab is much more than a button, first of all it provides contexts about the current view. A button serves no other purpose as being clicked.

**Comment by billsliu** [comment]
The browser has tab with closing button, but it is not a web application, it is a desktop application, I never see a web application having a tab with closing button. The tab with closing button is a rare use case, it is very easy to implement by override the v-slot. This feature  should be kept outside of the framework

**Comment by ThomasKientz** [comment]
That's exactly what we have in our app. What do you mean by "override the v-slot" ? VTab seams to only have the default slot.

**Comment by billsliu** [comment]
I did a more look at your problem, the slot may not solve your problem, but a couple of customized CSS will do the job
