### ISSUE TITLE
Icons in floating Buttons and Fabs are not centered in MSIE11

### ISSUE THREAD

**Issue by julkuh** [vuetifyjs/vuetify#1117]
### Steps to reproduce
Go to https://vuetifyjs.com/components/buttons and scroll down to **#6 Floating** Example.

### Versions
Microsoft Internet Explorer 11,
Vuetify JS 0.14.5

### What is expected ?
The icons inside floating Buttons are nicely centered.

### What is actually happening ?
The icons are right aligned due to unnecessary margin definition from default .btn__content

### Reproduction Link
https://vuetifyjs.com/components/buttons

**Comment by Christilut** [comment]
I'm seeing them left aligned with vuetify 0.14.7 on iOS 10 (simulator) and iOS 9 (device)

**Comment by johnleider** [comment]
The fix hasn't been released yet.

**Comment by Christilut** [comment]
Oh, but it said in the release log:
`#1117 Fixed a bug where v-btn with the fab prop was not centering the icon on IE11`

**Comment by johnleider** [comment]
Referring to this, 16116ecf0d8bfef31ab1a3dcda33a9e8366d7344. This bug fix caused the safari issue.

**Comment by johnleider** [comment]
Referring to 80e0d2f25d09aff7c21ca795eb7267e702e68a75. This IE11 fix caused the safari issue, was fixed in the before mentioned commit. That particular commit hasn't been released.
