### ISSUE TITLE
[Feature Request] select all for every items in group

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#11172]
### Problem to solve
every group has own "selected all" feature 

### Proposed solution
I haven't solution but maybe who know how it to realize

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
