### ISSUE TITLE
[Feature Request] Tamil Translation

### ISSUE THREAD

**Issue by nainardev** [vuetifyjs/vuetify#11178]
### Problem to solve
Sawn this https://github.com/vuetifyjs/vuetify/issues/10381

### Proposed solution
Thought why not? So I'd like to translate to Tamil

**Comment by nainardev** [comment]
Please provide me with further guidelines

**Comment by jacekkarczmarczyk** [comment]
Feel free to create PR, see for example https://github.com/vuetifyjs/vuetify/pull/10381 for inspiration (note that it needs a PR also in https://github.com/vuetifyjs/vue-cli-plugins repo

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
