### ISSUE TITLE
[Bug Report] Vuetify page scroll in iOS bounce scroll or rubber band scroll

### ISSUE THREAD

**Issue by animeshsa** [vuetifyjs/vuetify#11175]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.10
**Browsers:** Safari, Chrome 81.0.4044.113, Other
**OS:** iOS

### Steps to reproduce
create simple vuetify with app bar and navigation drawer

### Expected Behavior
When running my vuetify project in iOS while scroll page the browser scroll behavior shows a "bounce" when the end of the page is hit that is visually incorrect. Should not draw the white "bounce edge" when scrolling.
Happens in Safari, Chrome, Brave, Edge

### Actual Behavior
It should not bounce

### Reproduction Link
I don't have any

### Other comments
I know that it is an iOS feature but it should be configurable or fixed by using CSS or js. I tried this solution it worked for v_container but the body still bounce

 <v-container
        fluid
        style=" overflow-y: auto;
              overflow-x: hidden;
              height: 100vh;padding:10px 10px 80px 10px;"
        class="scrollable"
      >

 mounted() {
this.removeIOSRubberEffect(document.querySelector(".scrollable"));
},
methods: {
    removeIOSRubberEffect(element) {
      element.addEventListener("touchstart", function(event) {
        var top = element.scrollTop,
          totalScroll = element.scrollHeight,
          currentScroll = top + element.offsetHeight;
        if (top === 0) {
          element.scrollTop = 1;
        } else if (currentScroll === totalScroll) {
          element.scrollTop = top - 1;
        }
      });
    },
}

**Comment by KaelWD** [comment]
Complain to apple instead, there's no universal way to remove thiat.
