### ISSUE TITLE
[Documentation] mx-auto example not working

### ISSUE THREAD

**Issue by henon** [vuetifyjs/vuetify#11189]
### Environment

**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
None, the bug is evident at first glance

### Expected Behavior
The text in the example is centered horizontally

### Actual Behavior
The text in the example is not centered horizontally

![image](https://user-images.githubusercontent.com/44090/79984209-226b0580-84a9-11ea-8e29-9bd4e6e59a87.png)

### Reproduction Link
<a href="https://vuetifyjs.com/en/styles/spacing/#horizontal" target="_blank">https://vuetifyjs.com/en/styles/spacing/#horizontal</a>

### Other comments
I am curious, is this a bug with mx-auto or what is the cause?

**Comment by MajesticPotatoe** [comment]
This is working as intended. `mx-auto` is applied to the card in the example, thus applying margin to the card and centering the card within its parent (you can see this if you remove the mx-auto, that the card no longer centers). If you wanted the text itself centered you would use the helper class `text-center`
