### ISSUE TITLE
[Feature Request] Ability to customize default weekday in header using day-label-header slot

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#11188]
### Problem to solve
It will allow users to customize the entire header section

### Proposed solution
Adding a slot for the same

**Comment by kunalahirrao** [comment]
https://codepen.io/spider007/pen/MWabxjg... Customize default mon tue wed .....

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
