### ISSUE TITLE
[Bug Report] V-carousel not working in android 7 chrome 51.0.2704.90

### ISSUE THREAD

**Issue by LouisKoXiang** [vuetifyjs/vuetify#11199]
### Environment
**Vuetify Version:** 2.2.12
**Last working version:** 2.2.12
**Vue Version:** 2.6.1
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
on nuxtjs use v-carousel 
just doesn't work on Google chrome 51.0.2704.90 android 7.0 app

 "<v-carousel cycle  hide-delimiters>
        <v-carousel-item
          v-for="(slide, i) in slidesList"
          :key="i"
          :src="slide.url"
          @click="$router.push({ path: 'path' })"
        />
 </v-carousel>"

### Expected Behavior
It should work on all supported platforms

### Actual Behavior
just doesn't work on Google chrome 51.0.2704.90 android 7.0 app

### Reproduction Link
<a href="https://jsfiddle.com" target="_blank">https://jsfiddle.com</a>

### Other comments
workaround  v-carousel-item add img tag

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
