### ISSUE TITLE
[Bug Report] vuetify.js.map HTTP 404

### ISSUE THREAD

**Issue by franfrLor** [vuetifyjs/vuetify#11193]
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 3.0.0-beta.3
**Browsers:** Chrome 81.0.4044.113
**OS:** Windows 10

### Steps to reproduce
Hi, I have this error with vuetify : 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/vuetify/dist/vuetify.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
I use webpack

I try to create vetify component, some elements are not displayed correctly, it seems css was missing

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
