### ISSUE TITLE
Text fields: displaying both label and placeholder

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1119]
Feature request: according to MD guidelines text fields should be able to display together placeholder and label

https://vuetifyjs.com/components/text-fields

Reference:
https://material.io/guidelines/components/text-fields.html#text-fields-states

**Comment by dinvlad** [comment]
#1119 and #1130 were marked as duplicates of each other. Could you re-open this issue?

**Comment by johnleider** [comment]
These are 2 very old issues. If this is still a problem, just submit a new issue please.
