### ISSUE TITLE
[Bug Report]  Incorrect operation of components

### ISSUE THREAD

**Issue by Real001** [vuetifyjs/vuetify#11195]
### Environment
**Vuetify Version:** 2.2.23
**Last working version:** 2.1.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Windows 8.1

### Steps to reproduce
1. Componentrs text-field and textarea with validation and counter.
2. Component v-icon use.

### Expected Behavior
1. Errors messages and count symbol are displayed correct.
2. V-icon used tag "i" by default.

### Actual Behavior
1. Incorect work text-field and textarea, don't work counter and validation(don't view message validation and count).
2. All v-icon became buttons, props property tag used "i".

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
