### ISSUE TITLE
[Feature Request] v-text-field  type="number"

### ISSUE THREAD

**Issue by LouisLiu00** [vuetifyjs/vuetify#11197]
### Problem to solve
When the input box is of numeric type, a shortcut button will appear. When the button is clicked, the change range is 1, can it be customized? For example, 0.1, 0.01, 0.05, etc.
Secondly, can the number box be defined as an integer, it will not be able to enter decimals?
Looking forward to your reply!

### Proposed solution
When the input box is of numeric type, a shortcut button will appear. When the button is clicked, the change range is 1, can it be customized? For example, 0.1, 0.01, 0.05, etc.
Secondly, can the number box be defined as an integer, it will not be able to enter decimals?
Looking forward to your reply!

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#attr-step

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by LouisLiu00** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much for your reply, this article is very useful and solved my problem, thanks again!
            
        
    
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    
Louis

        
    
     

    On 4/23/2020 15:15，Kael<notifications@github.com> wrote： 



https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#attr-step
The issue list of this repo is exclusively for bug reports and feature requests. For general questions, please join the Discord chat room. You can also check reddit or stackoverflow.
