### ISSUE TITLE
[Bug Report] Unable to update VTextField value programmatically when using v-money directive

### ISSUE THREAD

**Issue by WoodyDark** [vuetifyjs/vuetify#11191]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Linux x86_64

### Steps to reproduce
1. Setup Vuetify and v-money
2. Use v-money as a directive on v-text-field
3. Set default `price` value to `'123.45'`
4. Create a button that sets `price` value to `'90.32'`

My setup is on v2.2.21, and the codesandbox reproduction below uses v2.2.23 of Vuetify and problem still persists.

### Expected Behavior
`price` updates to `'90.32'`

### Actual Behavior
`price` updates to `'90.32'` but gets reverted back to `'123.45'`

### Reproduction Link
<a href="https://codesandbox.io/s/v-money-not-working-with-vuetify-4d8qs" target="_blank">https://codesandbox.io/s/v-money-not-working-with-vuetify-4d8qs</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
