### ISSUE TITLE
[Documentation] Unable to scroll on desktop

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#11196]
### Environment

**Browsers:** Chrome 81.0.4044.92
**OS:** Linux x86_64

### Steps to reproduce
Open the docs eg. https://vuetifyjs.com/en/components/navigation-drawers/ page is locked and won't scroll. Scroll bar is missing. When I reload the page, it lets me scroll momentarily, before locking in place.

### Expected Behavior
page should scroll

### Actual Behavior
page doesn't scroll

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/navigation-drawers/" target="_blank">https://vuetifyjs.com/en/components/navigation-drawers/</a>

**Comment by andrewharvey** [comment]
so this only appears to happen when the window is narrow. At 1227px wide I can't scroll, at 1284px wide the left and right panels appear and I can scroll. Scrolling should work regardless of screen size.

**Comment by KaelWD** [comment]
This one is open by default so it prevents page scroll: https://vuetifyjs.com/en/components/navigation-drawers/#playground
