### ISSUE TITLE
[Feature Request] Alert border support start/end alongside left/right

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#11205]
### Problem to solve
Easier and better layouts in RTL languages

### Proposed solution
Add start/end support to border prop which can be computed on $vuetify.rtl

**Comment by yooneskh** [comment]
Note: left/right actually behaves like start/end but shouldn't. i didn't submit this as a bug report as it is more of a renaming than a bug.

**Comment by johnleider** [comment]
fixed in #13855

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
