### ISSUE TITLE
[Bug Report] Input Field DatePicker not working in DataTable

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [vuetifyjs/vuetify#11200]
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Windows 10

### Steps to reproduce
When I click on the date field in column "Date Value", the DatePicker does not open.

Example: https://techformist.com/vuetify-input-field-date-picker/
Example CodePen: https://codepen.io/prashanth1k/pen/eYmoraP

### Expected Behavior
When I click on the date field in column "Date Value", a date picker should open below it.

### Actual Behavior
When I click on the date field in column "Date Value", the DatePicker does not open.

### Reproduction Link
<a href="https://codepen.io/softwaredesign-solution/pen/WNQREgG" target="_blank">https://codepen.io/softwaredesign-solution/pen/WNQREgG</a>

**Comment by jacekkarczmarczyk** [comment]
You're missing `<v-app>`
