### ISSUE TITLE
[Bug Report] v-list-item-group: on mounting, the v-list-item (not just those generated in v-for) with key === v-model should be selected

### ISSUE THREAD

**Issue by LoneRifle** [vuetifyjs/vuetify#11219]
### Environment
**Vuetify Version:** 2.3.0-beta.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Mac OS 10.15.4

### Steps to reproduce
Create any v-list with a v-list-item-group, containing manually declared v-list-items (instead of items generated with `v-for`)

### Expected Behavior
The v-list-item with the key matching the v-model in v-list-item-group should be selected

### Actual Behavior
Even with list-wide unique keys, v-list-item-group does not select the manually declared v-list-item. However, if a user clicks on it, the item will render as if selected.

### Reproduction Link
<a href="https://jsfiddle.net/pj80z25a/11/" target="_blank">https://jsfiddle.net/pj80z25a/11/</a>

### Other comments
This would be useful in scenarios where a list of items is desired, but for one reason or another, some of the items have to be declared instead of generated programmatically. An example of this could be a user with a primary profile, and multiple secondary profiles, with the means to switch between any of the profiles.

Changing this behaviour would also make it consistent with the selection of the declared item when the user clicks on it.

It is assumed that this affects v-item-group as well.

**Comment by KaelWD** [comment]
`key` is only used by vue to identify elements when diffing, you need to use the `value` prop.
