### ISSUE TITLE
[Bug Report] SASS variables for v-tab don't work

### ISSUE THREAD

**Issue by xdoo** [vuetifyjs/vuetify#11217]
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Linux x86_64

### Steps to reproduce
1. create a project with VUE CLI (add vuetify, update vuetify to the lastest version)
2. add a v-tabs component with 3 v-tab items to the v-app-bar 
3. create under src a folder namend scss and create a file named variables.scss
4. add three costum values for sass variables:
```
$tabs-item-focus-opacity: 0.0 !default;  // works not
$tabs-item-hover-opacity: 1 !default;    // works not
$tabs-item-letter-spacing: 3em !default; // works
```
and import the components variables file:
```
@import '~vuetify/src/components/VTabs/_variables.scss';
```
5. run the project with `npm run serve`

### Expected Behavior
I expected to see a tab bar with three tabs. There shopuld be a visible spacing (3em) between the letters. If I hover over the tabs, there should be a background transition on the tab with no opacity. If I click the first tab and focus the second one by using tab on my keyboard, there should be no visible transition on the tab background (opacity 0.0). 

### Actual Behavior
$tabs-item-focus-opacity: 0.0 !default;  // works not
$tabs-item-hover-opacity: 1 !default;    // works not
$tabs-item-letter-spacing: 3em !default; // works

### Reproduction Link
<a href="https://github.com/xdoo/vuetify_sass_issue" target="_blank">https://github.com/xdoo/vuetify_sass_issue</a>

### Other comments
I'm not 100% sure if this is a bug. Perhaps I don't understand how it works. But I tried to follow this documentation step by step:

> Vue CLI install
> If you have not installed Vuetify, check out the quick-start guide. Once installed, create a folder called sass, scss or styles in your src directory with a file named variables.scss or variables.sass. The vuetify-loader will automatically bootstrap your variables into Vue CLI's compilation process, overwriting the framework defaults.

> When you run yarn serve, the vuetify-cli-plugin will automatically hoist the global Vuetify variables to all of your sass/scss files. When making changes to individual component variables, you will still need to manually include its variables file. You can find an example of a custom variables file below.

**Comment by xdoo** [comment]
letter spacing:
![sass](https://user-images.githubusercontent.com/712911/80181011-48f18380-8604-11ea-98e6-547017a3b4a8.png)

hover over the second tab (bar)
![sass_hover](https://user-images.githubusercontent.com/712911/80181038-5870cc80-8604-11ea-8eec-a7079c2afdda.png)

focussed the third tab over the keyboard:
![sass_tab](https://user-images.githubusercontent.com/712911/80181058-66bee880-8604-11ea-91f2-37525103ff9f.png)

**Comment by jacekkarczmarczyk** [comment]
These 2 variables are defined but not used, tabs use default values from styles/settings/_(light|dark).sass (`states` section)
