### ISSUE TITLE
[Feature Request] v-data-table  Merge header

### ISSUE THREAD

**Issue by LouisLiu00** [vuetifyjs/vuetify#11216]
### Problem to solve
Can the data table merge the header?
I don't see the attributes that can merge the headers?

### Proposed solution
Hope that the data table can merge the table header.

Looking forward to your reply！

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
