### ISSUE TITLE
[Feature Request] Full width paragraphs in v-footer

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11210]
### Problem to solve
To have a line of text (or centered text) in a `v-footer` you need to wrap the text/paragraph in a `v-col` or use it within a `v-card`. This is due to the flex display used in `v-footer`.
By default, a regular paragraph takes up the whole width.

### Proposed solution
Give paragraphs explicit CSS to maintain convention of paragraphs to default to full width:
```css
.v-footer p {
  width: 100%;
}
```

**Comment by xon52** [comment]
Thinking about this some more, I can see that for many applications a footer makes sense to be split into columns; but if this is the way it's meant to be used, maybe include something explicit in the docs that it should be used as a special `<v-row>`, which from what I can see is what it is.

**Comment by johnleider** [comment]
`v-footer` is a flex container like other layout components, `v-app-bar`, `v-bottom-navigation`, etc. This is intended as of now and easy to change by adding a flex helper class to the <v-footer> tag:

```html
<v-footer class="flex-grow-1">
  <p>...</p>
</v-footer>
```

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
