### ISSUE TITLE
On mobile, tabs can be dragged out of sight

### ISSUE THREAD

**Issue by codingfriend1** [vuetifyjs/vuetify#1121]
### Steps to reproduce
This issue shows up on the vuetify.com demo website on mobile. The issue is not evident on desktop.

### Versions
Android in chrome

### What is expected ?
Tabs that don't require scrolling should not move horizontally or at least jump back into place when dragged.

### What is actually happening ?
If the tabs are dragged to the right they bounce back however if the tabs are dragged to the left they disappear on the left edge.

### Reproduction Link
https://vuetifyjs.com/components/tabs

**Comment by johnleider** [comment]
We may have to revert the way that scrolling is handled on these, the issue is with trying to detect whether or not you can at least see 1 item, which can vary by size etc etc. I'll talk with @nekosaur about this.

**Comment by johnleider** [comment]
Improved the way logic is handled for touch on tabs bar.
