### ISSUE TITLE
[Bug Report] Can't test VFooter with "app" attribute independent of VApp component

### ISSUE THREAD

**Issue by joergd** [vuetifyjs/vuetify#11218]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.5, Other
**OS:** Mac OS 10.15.3

### Steps to reproduce
I am using Jest to test my VFooter component (with an "app" attribute. This is the only Vuetify component in my component. I mount (not shallowMount) the component in my test, and run Jest test.

### Expected Behavior
I understand the "app" attribute is part of the layout system, but I expect not to have to do something special in the tests for them to pass regardless.

### Actual Behavior
Error:

      TypeError: Cannot read property 'register' of undefined
          at VueComponent.callUpdate (/Users/joerg/dev/app/node_modules/vuetify/dist/webpack:/Vuetify/src/mixins/applicationable/index.ts:62:35)
          at VueComponent.mounted (/Users/joerg/dev/app/node_modules/vuetify/dist/webpack:/Vuetify/src/mixins/applicationable/index.ts:47:12)

### Other comments
If I remove the "app" attribute from my VFooter component, the tests pass fine.

**Comment by KaelWD** [comment]
You need `this.$vuetify`, not v-app. If this doesn't exist then you aren't passing a `new Vuetify()` instance to the mount options. Alternatively you can mock `$vuetify.application`: https://github.com/vuetifyjs/vuetify/blob/7d46f7d29a3ff7097e6341d9ad5450dec8dd953d/packages/vuetify/src/components/VFooter/__tests__/VFooter.spec.ts#L16-L26
