### ISSUE TITLE
[Bug Report] v-navigation-drawer bottom doesn't work

### ISSUE THREAD

**Issue by iterprise** [vuetifyjs/vuetify#11229]
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Linux

### Steps to reproduce
Open link.
Look at v-navigation-drawer
It's top right

### Expected Behavior
v-navigation-drawer  bottom right

### Actual Behavior
v-navigation-drawer  top right

### Reproduction Link
<a href="https://codepen.io/interpri5e/pen/LYpWeGz" target="_blank">https://codepen.io/interpri5e/pen/LYpWeGz</a>

**Comment by MajesticPotatoe** [comment]
`bottom` is not a positional prop in the sense that it seems like you are implying. With navigational drawers, its a prop that triggers an alternative style when `mobile-break-point` is met. See <https://vuetifyjs.com/en/components/navigation-drawers/#bottom-drawer> for more details.

**Comment by iterprise** [comment]
How I cat resolve my solution? I mean place this v-navigation-drawer to end of page.
