### ISSUE TITLE
[Feature Request] Icons : support multiple iconsets 

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#11224]
### Problem to solve
We are limited to a single icon set in all the app.

It is set at bootstrap :

```javascript
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify)

export default new Vuetify({
  icons: {
    iconfont: 'mdi', // 'mdi' || 'mdiSvg' || 'md' || 'fa' || 'fa4' || 'faSvg'
  },
})
``` 

### Proposed solution
Adding a property `iconSet` on VIcon which designates the icon set we want to use for this particular icon.

So we can have 

```html
<v-icon>mdi-user</v-icon> // use default set
<v-icon iconSet="md">user<v-icon> // with specific set
```

**Comment by jacekkarczmarczyk** [comment]
You need to install all fonts you need or add links to CDNs, `iconfont` only specifies which icon set will be used for default Vueitfy icons (such as arrow in v-select etc)
```
<v-icon>mdi-user</v-icon> // MDI will be used
<v-icon>user<v-icon> // Material Icons will be used
<v-icon>fas fa-whatever<v-icon> // FA will be used
````
