### ISSUE TITLE
[Feature Request] How to show hide columns of vuetify data table using v-select list

### ISSUE THREAD

**Issue by annu9103** [vuetifyjs/vuetify#11220]
### Problem to solve
hi all.....I have spend too much time on this problem
i have headerMap object but basically my app fetch columns name from back-end file and that is config.columns…the code that i have mentioned gave me table with column name and v-select component is showing same columns name. but the problem is when I deselect the particular columns name from v-select component that change is not showing on table …i.e the columns name and corresponding data are not removing…
waiting for your response

thanks in advance 

### Proposed solution
<v-select

      v-model="selectedHeaders"

      :items="headers"

      label="Select Columns"

      :menu-props="{ maxHeight: '200' }"

      multiple

      outlined

      return-object

    >

      <template v-slot:selection="{ item, index }">

        <v-chip v-if="index < 2">

          <span>{{ item.text }}</span>

        </v-chip>

        <span

          v-if="index === 2"

          class="grey--text caption"

        >(+{{ selectedHeaders.length - 2 }} others)</span>

      </template>

    </v-select>

  </v-flex>

  <v-data-table

    v-model="selected"

    :headers="customHeaders"

    :items="alarm"

    :pagination.sync="pagination"

    :rows-per-page-items="pagination.rowsPerPageItems"

    class="alarm-table"

    :class="[ displayDensity ]"

    :search="search"

    must-sort

    :custom-sort="customSort"

    sort-icon="arrow_drop_down"

    select-all

  >
computed: {
customHeaders() {

  return this.headers.map(s => this.selectedHeaders[s] || { text: this.$options.filters.capitalize(s)})
}
},
created () {

this.headers = this.$config.columns.map(c =>this.$options.filters.capitalize(c))

this.selectedHeaders = this.headers
},

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
