### ISSUE TITLE
[Bug Report] Form validation ignoring collapsed expansion field

### ISSUE THREAD

**Issue by TheOnlyError** [vuetifyjs/vuetify#11237]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Windows 10

### Steps to reproduce
1. Open the collapsed expansion field, which contains a text field in the error state.
2. Observe the valid state changes to false.

### Expected Behavior
The valid state should be equal to false to begin with, the text field being collapsed or not should not affect this result.

### Actual Behavior
An initially collapsed element with an error state is ignored in the form validation.

### Reproduction Link
<a href="https://codepen.io/theonlyerror/pen/pojPWNe?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F" target="_blank">https://codepen.io/theonlyerror/pen/pojPWNe?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F</a>

**Comment by jacekkarczmarczyk** [comment]
Second panel is not rendered when it's hidden, and therefore it's state is not being taken into account
Working version: https://codepen.io/jkarczm/pen/zYvwRBp?editable=true&editors=100

**Comment by TheOnlyError** [comment]
Maybe the `eager` property can also be added to the expansion panels component!
