### ISSUE TITLE
<v-subheader> is black in both 'light' and 'dark' theme & overlapping of 'label' and 'prefix' in <v-text-field>

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#1123]
### Steps to reproduce

1. For `v-subheader` toggle between `dark` and `light` props of `v-app`.
2. For `v-text-field` put values for `label` and `prefix` props.

### Versions
Vuetify: 0.14.6

### What is expected ?

1. Better tint for the text of `v-subheader` in `v-app dark` theme.
2. Label and prefix should not overlap.
### What is actually happening ?
1. Text color stays black in `v-app dark`
2. Label and prefix overlap.

### Reproduction Link

https://codepen.io/azaars/pen/NvPKQP

**Comment by johnleider** [comment]
Your first issue was addressed with #1144 . As far as your second issue, unfortunately, due to how text-fields are created, prefixes can only be supported with 1 character.

**Comment by azaars** [comment]
@johnleider . If I may suggest, perhaps the the feature to show the label in the text field could be disabled if there's a prefix. Even if the prefix length is 1 character, it may not make sense to read together with the label in a single line. Making it disabled would however affect the error shake feature.
