### ISSUE TITLE
[Bug Report] Color Picker canvas on width 100%

### ISSUE THREAD

**Issue by skourta** [vuetifyjs/vuetify#11239]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Linux

### Steps to reproduce
set the width of the color picket to 100%

### Expected Behavior
canvas should cover 100% of the surface

### Actual Behavior
canvas is only covering some of the surface

### Reproduction Link
<a href="https://codepen.io/skourta/pen/rNOmpxO" target="_blank">https://codepen.io/skourta/pen/rNOmpxO</a>

**Comment by ElijahKotyluk** [comment]
#7151
