### ISSUE TITLE
[Bug Report] v-color-picker don`t working in extreme position

### ISSUE THREAD

**Issue by gizmach** [vuetifyjs/vuetify#11235]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Yandex 20.4.0.1461
**OS:** Windows 10

### Steps to reproduce
A)
1) Choose #FFFFFF or #000000
2) Choose whatever
B)
1) Choose #FFFFF0 or "#000001"
2) Choose whatever

### Expected Behavior
the color has changed

### Actual Behavior
A) the color has not changed
B) the color is very light

### Reproduction Link
<a href="https://codepen.io/gizmach/pen/yLYMdwd" target="_blank">https://codepen.io/gizmach/pen/yLYMdwd</a>

**Comment by YipingRuan** [comment]
The slider is to adjust the hue. In extreme brightness (black/white), the color will not be obvious.
