### ISSUE TITLE
[Feature Request] v-img aspect ratio limitations

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11246]
### Problem to solve
`v-img` automatically resizes an image really well (to any size) with the `aspect-ratio` defined and `contain` set.
The issue is, you must define the `aspect-ratio` which is rather tedious to do with every image (and every change).

### Proposed solution
A new property: `maintain-aspect` which does not require a defined aspect ratio but uses the one from the original image.

**Comment by KaelWD** [comment]
It already does this, but doesn't know what the aspect ratio is until the image is loaded so you still get a layout jump. [vuetify-loader](https://github.com/vuetifyjs/vuetify-loader#progressive-images) can set this automatically at build time for static images.
