### ISSUE TITLE
[Bug Report] v-pagination component too wide, if length is large

### ISSUE THREAD

**Issue by laberning** [vuetifyjs/vuetify#11242]
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Windows 10

### Steps to reproduce
Create a v-pagination-component with large length, i.e.

      <v-pagination
        v-model="page"
        :length="10000"
      ></v-pagination>

### Expected Behavior
The rendered component should fit into the available screen size.

### Actual Behavior
The component is larger than the available screen size.

### Reproduction Link
<a href="https://codepen.io/laberning/pen/rNOmbdL" target="_blank">https://codepen.io/laberning/pen/rNOmbdL</a>

### Other comments
The implementation assumes a fixed width per "page"-button, but pages with high numbers need more space.

this.maxButtons = Math.floor((width - 96) / 42)

**Comment by bkpedrosuper** [comment]
I am actually having the same problem.

**Comment by bkpedrosuper** [comment]
> problem
I kinda solved.
what I did was set the prop total-visible to "20". It still doesn't fit the page correctly, but the main problem is now solved.

`<v-pagination v-if="pages" class="text-xs-center pt-3 r-pagination" v-model="pagination.page" :length="pages" total-visible="12" />`

**Comment by d4828** [comment]
The CSS below seemed to resolve it on my end. The width and min-width property adjustments are relevant:

:deep(.v-pagination__item) {
  min-width: fit-content;
}

:deep(.v-pagination__item) > button {
  width: fit-content !important;
  min-width: fit-content;
  min-height: fit-content;
  border-radius: unset;
  padding: 9px;
}

:deep(.v-btn__content) {
  color: rgba(0, 0, 0, 0.5);
}

:deep(.v-btn)[ellipsis="true"] > .v-btn__content {
  color: rgba(0, 0, 0, 0.89) !important;
}
