### ISSUE TITLE
[Feature Request] display v-progress-linear in left-to-right direction while vuetify layout is RTL

### ISSUE THREAD

**Issue by madnik7** [vuetifyjs/vuetify#11245]
### Problem to solve
I am a Persian language, progress bar is like numbers and mathematics for us, We don't expect that a progress starts from right and extends to left. 

### Proposed solution
I am not sure about other RTL languages as we also encounter this issue in some other applications too. By the way, the best solution is to add a property to indicate the direction of v-progress-linear control regardless of application layout.

**Comment by jacekkarczmarczyk** [comment]
> By the way, the best solution is to add a property to indicate the direction of v-progress-linear control regardless of application layout

You mean you want to be able to display RTL progress in LTR app and vice versa?

**Comment by madnik7** [comment]
> > By the way, the best solution is to add a property to indicate the direction of v-progress-linear control regardless of application layout
> 
> You mean you want to be able to display RTL progress in LTR app and vice versa?

I meant, I need to display LTR progress in RTL app. In other word we almost display progress bar in LTR regardless of application layout, same as numbers. It should start from let and finish to right.

When we write numbers and calculus we usually start a new line and start from left same as English. 

![Annotation 2020-04-27 113809](https://user-images.githubusercontent.com/3189803/80408292-d1c62480-887b-11ea-880b-55ba345be5c4.png)

**Comment by madnik7** [comment]
> > By the way, the best solution is to add a property to indicate the direction of v-progress-linear control regardless of application layout
> 
> You mean you want to be able to display RTL progress in LTR app and vice versa?

Just another sample with progress:
![Annotation 2020-04-27 113809](https://user-images.githubusercontent.com/3189803/80409067-156d5e00-887d-11ea-852d-c784bec506d1.png)

**Comment by jacekkarczmarczyk** [comment]
I hesitate to add `rtl` prop to the progress, i think it would be the only component now that would support it and (even imho more important) it would indicate that the full component is RTL including the default slot content. Probably something like `reverse` would be a better option.

Would the same apply for circular progress? @madnik7

**Comment by madnik7** [comment]
> I hesitate to add `rtl` prop to the progress, i think it would be the only component now that would support it and (even imho more important) it would indicate that the full component is RTL including the default slot content. Probably something like `reverse` would be a better option.
> 
> Would the same apply for circular progress? @madnik7

* I think reverse is misleading on LTR mode. Perhaps ignore-direction or inherit-direction=false would be better.
* The circular doesn't change its direction on RTL and already looks OK. It should remain same as English.

**Comment by madnik7** [comment]
@jacekkarczmarczyk. You can look at "When not to mirror" & "The passage of time" at the following link from Material Design

https://material.io/design/usability/bidirectionality.html#mirroring-layout

**Comment by jacekkarczmarczyk** [comment]
> I think reverse is misleading on LTR mode

Why would it be misleading? It would be reversed in LTR as well. And - unlike `inherit-direction` - it would let displaying the progress from right to left in LTR app

**Comment by jacekkarczmarczyk** [comment]
Hmmm
![image](https://user-images.githubusercontent.com/15625235/80414933-12508d00-88d2-11ea-96d7-fae4075e2339.png)

**Comment by madnik7** [comment]
It also sounds crazy for me to understand that reverse graph, but maybe some people have got used to or accustom to that.

By the way, what I need is something like the following part you can find in that document too:
![image](https://user-images.githubusercontent.com/3189803/80416828-9d596500-8889-11ea-990a-603c9d69d42f.png)

The "passage of time" should not be reversed. Reversed property means it should be reversed on LTR too, what we need is to stop reversing at all. When the app switch from LTR to RTL, that kind of progress should not be mirrored.

**Comment by jacekkarczmarczyk** [comment]
> what we need is to stop reversing at all

which you could easily do with `:reverse="$vuetify.rtl"`

**Comment by jacekkarczmarczyk** [comment]
@vuetifyjs/core-team thoughts?

**Comment by madnik7** [comment]
It works for me, but it is little tricky for others to find it. The benefit is let create reverse progress in LTR too. I think this trick is required to directly be mentioned in the document.

**Comment by nekosaur** [comment]
I agree that `reverse` option seems like the better solution

**Comment by mmghv** [comment]
For me, an Arabic speaker, I agree with everything in [bidirectionality](https://material.io/design/usability/bidirectionality.html) guide lines from Material Design, linear progress bars should follow direction as well as sliders, except for media playback progress which should always be LTR

So a `reverse` prop seems very reasonable for that use, also `:reverse="$vuetify.rtl"` is a great trick which should be mentioned in the docs with that prop.

**Comment by mmghv** [comment]
After second thought, `reverse-dir` would be better descriptive, `reverse` might make sense for progress bars but if needed in the future for other components it might be misleading, so `reverse-dir` is better for future proof.

**Comment by jacekkarczmarczyk** [comment]
resolved in https://github.com/vuetifyjs/vuetify/pull/11259
