### ISSUE TITLE
Bug in dialog

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#1124]
### What is expected ?
I create a dialog that can not be closed if the file is not loaded (in the example, the dialog can never be closed). And if the file is loaded, then the dialog can be opened and closed. In the dialogue with created the button "CLOSE" and it behaves as expected. I expected that by clicking on the background the dialog will shoot an event of input up. And if the parent component changes the value, close the dialog.

### What is actually happening ?
When you click on the overlay, the dialog is closed despite the fact that the value is passed to `true`.
The dialog really shoots the `input` event. But at the same time it independently changes the internal value of `isActive` and closes, ignoring the `value` props

### Reproduction Link
https://codepen.io/cawa-93/pen/YxPzxM?editors=1010

**Comment by johnleider** [comment]
If you want the dialog to stay open regardless of clicking on the overlay, use the **persistent** prop.

**Comment by cawa-93** [comment]
Sorry for the delay in answering.

No, this is not what I want to get. I want to be able to check some condition before closing the dialog. And if the condition does not correspond - do not close the dialogue.

To do this, I listen to the event `@input` from the `v-dialog` and wait for the user to try to close it. I check the condition and if it is true, I close the dialog.

However, if I click on the background, the dialog is closed ignoring the `v-bind:value`.

I changed [my example](https://codepen.io/cawa-93/pen/YxPzxM?editors=1010) to illustrate the behavior more clearly. Please, try:
1. Do not checked checkbox
2. Click "close" button. You will see a message stating that the dialog can not be closed.
3. Click on the overlay. You will see a message stating that the dialog can not be closed, after which the dialog is closed

**Comment by johnleider** [comment]
Again, you can achieve this behavior by simply applying a dynamic prop for the disable-overlay prop and toggle that based upon your conditionals.

**Comment by cawa-93** [comment]
I want to be able to close the dialog by clicking on the overlay. But only if my condition is true.
What I do not understand, is why the state of the dialog is not dependent on `:value`

**Comment by johnleider** [comment]
Because a vmodel is not an absolute truth, it's a 2 way binding. You can update the dialog and the dialog can update you. Which is why I say to use the toggled conditional.

**Comment by cawa-93** [comment]
I know how the `v-model` works. But the behavior of the dialogue is not obvious.
I expected the following
* Dialog depends on the `:value`
* When clicking on the overlay (or any other potential way of closing), the dialog box fires the event `@input`, But does not change the state yourself
* This is done by the parent component. It responds to the event `@input` and changes the `:value`.
* The dialogue reacts to this change and closes if it is `false`.

If this were the case, the following code will create a dialog that can not be closed:
```vue
<v-dialog :value="true">
  Content
</v-dialog>
```
But this is not so.

**Comment by johnleider** [comment]
I don't disagree, the problem is, in order to accomplish that, I would have to instead evaluate the change of the :value prop as opposed to the local isActive prop. Unless you have another method that could help me out, I don't really see any other way to handle it.

**Comment by cawa-93** [comment]
Not tested, but as for me this behavior is much more logical.
```js
// toggleable.js
export default {
  data () {
    return {}
  },

  props: {
    value: {
      required: false
    }
  },
  
  computed: {
    isActive: {
      get() { return !!this.value },
      set(val) { this.$emit('input', val) }
    }
  }
}
```

**Comment by johnleider** [comment]
That's exactly as I was stating above. It does seem more logical, but requires you bind a model. isActive can't update unless there is a change to value.

**Comment by cawa-93** [comment]
Exactly. Using the `v-model`, you update the `:value`, but you get more control. And you exclude the situation when the `:value` does not correspond `isActive`

**Comment by johnleider** [comment]
Unfortunately, while giving more control, it also makes it that much more cumbersome for all components that implement toggleable to obey towards always having a v-model. For that reason, I don't think that it is the best path to take for the framework.

I understand your concerns, but there are tools available to you in order to achieve your desired outcome.
