### ISSUE TITLE
[Bug Report] VMenu close-delay not working

### ISSUE THREAD

**Issue by mmghv** [vuetifyjs/vuetify#11247]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Windows 7

### Steps to reproduce
Add VMenu component and define `close-delay` prop on it with a value of `1000` for example

### Expected Behavior
To delay closing the menu

### Actual Behavior
No effect at all

### Reproduction Link
<a href="https://codepen.io/mmghv/pen/ExVXZoz?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fmenus%2F" target="_blank">https://codepen.io/mmghv/pen/ExVXZoz?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fmenus%2F</a>

### Other comments
In the [documentation for VMenu](https://vuetifyjs.com/en/components/menus/#menus) I can see `close-delay` & `open-delay` props, but when trying them out, it seems they have no effect at all, also I couldn't find the definition for these props in the source code for `VMenu`.

**Comment by jacekkarczmarczyk** [comment]
It works only with `open-on-hover`

**Comment by mmghv** [comment]
@jacekkarczmarczyk Oh, my bad, thanks.
But the docs should make that clear, I don't know if I should close the issue, feel free to close it.

**Comment by jacekkarczmarczyk** [comment]
>  I don't know if I should close the issue

no, we should add this information to docs
