### ISSUE TITLE
[Feature Request] Rounded prop for v-card

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11240]
### Problem to solve
`v-card` has a `shaped` prop (rounded top-left and bottom-right corners) but no prop to round all corners. I'm using the card as a button and would like corners a little more rounded.

### Proposed solution
Include a `rounded` prop which clones `shaped` but does all corners.

**Comment by johnleider** [comment]
This is now possible in the v2.3 beta via helper classes: https://dev.vuetifyjs.com/en/styles/border-radius/
