### ISSUE TITLE
[Bug Report] New Vue slot syntax doesn't work with some Vuetify components.

### ISSUE THREAD

**Issue by misha** [vuetifyjs/vuetify#11248]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Windows 10

### Steps to reproduce
Use the new #-prefixed slot syntax for a default slot, ie. `#default` instead of `v-slot`, directly on `<v-layout>` when passing it to a slotted parent component.

### Expected Behavior
It should be possible to use `#default`. Otherwise, if using `#default` directly on Vuetify components is somehow not supported, it should not render completely.

### Actual Behavior
Only the Vuetify component is rendered; its content is completely missing.

### Reproduction Link
<a href="https://codepen.io/msoliter/pen/WNQORaJ" target="_blank">https://codepen.io/msoliter/pen/WNQORaJ</a>

### Other comments
Using `v-slot`, or placing the `#default` on a wrapper `<template>` element fixes the problem.

I also tested this with `<v-button>` and it has the same behavior.

**Comment by blalan05** [comment]
This is a Vuejs "issue"<https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots> The sentence just before this header. "Note that v-slot can only be added to a <template> (with one exception), unlike the deprecated slot attribute."
Not sure about the second example, but putting named slots on Vuetify elements and not <template> is not working as expected.

**Comment by jacekkarczmarczyk** [comment]
If you want to use `#` syntax on Parent component then you should use in on Parent component, same like you do it with `v-slot`

```html
<Parent #default="{ message }">
  <v-layout>
    <div>
      {{message}}
    </div>
  </v-layout>
</Parent>
```

You're now using in on `v-layout` (2nd example) which doesn't have scoped slot
