### ISSUE TITLE
[Bug Report] v-card-text transparency issue

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11241]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Windows 10

### Steps to reproduce
[Codepen](https://codepen.io/xon5/pen/rNOmqMG)

### Expected Behavior
Card text (including icons) to be consistently visible within components.

### Actual Behavior
`v-card`, `v-card-text`, etc use transparency to lighten text in both `light` and `dark` themes.
I never noticed this until I started including emoticons and they were coming out transparent.

### Reproduction Link
<a href="https://codepen.io/xon5/pen/rNOmqMG" target="_blank">https://codepen.io/xon5/pen/rNOmqMG</a>

### Other comments
The work-around is to explicitly specify the text color: e.g. `white--text`

**Comment by johnleider** [comment]
`v-card-text` intentionally decreases the opacity to match Material Guidelines. Just use `<div class="pa-4">`.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
