### ISSUE TITLE
[Bug Report] Validation is always true for a v-select or v-autocomplete when the multiple prop is set to true

### ISSUE THREAD

**Issue by matt-socialplaces** [vuetifyjs/vuetify#11252]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Create a `v-form`
Insert either a `v-select` or `v-autocomplete` with the prop `:multiple="true"` inside the form.
Validate the form
The form will be valid, even if there is no option selected in the multiple select/autocomplete.

### Expected Behavior
The form should not be valid until an option has been selected

### Actual Behavior
The form is valid

### Reproduction Link
<a href="https://codepen.io/matt-h/pen/PoPjEgX" target="_blank">https://codepen.io/matt-h/pen/PoPjEgX</a>

### Other comments
I have tested on 2.2.25 and the issue still persists.
Tested with both `v-select` and `v-autocomplete`
Used `:multiple="true"` and `multiple`

**Comment by jacekkarczmarczyk** [comment]
`!![]` resolves to `true`

`:rules="[v => !!(v && v.length) || 'Item is required']"`

**Comment by jatin-maropost** [comment]
> `!![]` resolves to `true`
> 
> `:rules="[v => !!(v && v.length) || 'Item is required']"`

Thank you @jacekkarczmarczyk  for your help.
