### ISSUE TITLE
[Bug Report] Accessibility - Dialog doesn't close with esc the first time

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#11257]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Linux x86_64

### Steps to reproduce
On the very first example, click the open button.  Now, hit "esc".  It should close the dialog but doesn't.  Now, click the dialog to focus on it.  Hit "esc" now, it closes.  

### Expected Behavior
It should close on esc the first time.

### Actual Behavior
It doesn't close the first time.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/mdewGpX?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdialogs%2F" target="_blank">https://codepen.io/gabaum10/pen/mdewGpX?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdialogs%2F</a>

### Other comments
This is important for accessibility reasons.

**Comment by jacekkarczmarczyk** [comment]
Last working version: 2.2.8

Probably broken by https://github.com/vuetifyjs/vuetify/commit/2b975f575f47ba75aa5d0dd9fba859595c7b9ba4#diff-6d73f6698e69f2b6c718dfed6b89cd34
