### ISSUE TITLE
[Bug Report] Title attribute is not working in v-select

### ISSUE THREAD

**Issue by chans-me** [vuetifyjs/vuetify#11253]
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
The normal behaviour of title attribute is to display the title text on hover , similar to v-text-field. But in v-select it is not working, please check the codepen

### Expected Behavior
On hover select box, title message should display

### Actual Behavior
it is not showing the title message

### Reproduction Link
<a href="https://codepen.io/chansv/pen/ExVXEQJ?editors=1000" target="_blank">https://codepen.io/chansv/pen/ExVXEQJ?editors=1000</a>

**Comment by KaelWD** [comment]
v-select passes all attributes down to the `<input>` element like v-text-field does (#12362), but it has `pointer-events: none` to prevent you from typing in it.
