### ISSUE TITLE
[Feature Request] Sticky header on scroll in vuetify datatable

### ISSUE THREAD

**Issue by chans-me** [vuetifyjs/vuetify#11250]
### Problem to solve
When datatable height is greater than the window height, when we scroll the page, we can have header row sticky till the datatable scroll is over

### Proposed solution
The behaviour should be similar to this 
https://output.jsbin.com/zuzuqe/1/

also like the datatable they used https://www.worldometers.info/coronavirus/

**Comment by constantinosergiou** [comment]
when this will be fix?

**Comment by paper-me** [comment]
a good idea, should be impleamented

**Comment by johnleider** [comment]
This already exists:

* https://vuetifyjs.com/en/components/simple-tables/#fixed-header
* https://vuetifyjs.com/en/api/v-data-table/#props

![image](https://user-images.githubusercontent.com/9064066/101542841-ff726080-3968-11eb-8f6e-f06ef18c34df.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
