### ISSUE TITLE
gap between autocomplete v-select and list of options

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1125]
### Steps to reproduce

Click the "Select with autocomplete" field in the reproduction link

### Versions

0.14.6

### What is expected ?

The should be no such a big gap between the field and the list of options

### What is actually happening ?

The gap is too big. It looks better when there's a hint or error messages

### Reproduction Link

https://codepen.io/anon/pen/PKwqjd
http://imgur.com/a/fONZu

**Comment by johnleider** [comment]
This has been resolved on dev for 0.15.0
