### ISSUE TITLE
[Bug Report] Dialog flickering when being opened

### ISSUE THREAD

**Issue by tahnik** [vuetifyjs/vuetify#11263]
### Environment
**Vuetify Version:** 2.2.26
**Last working version:** 2.2.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Simply opening any dialog causes the overlay to flicker. I have noticed that sometimes if you keep opening the dialog over and over again, the problem eventually disappears. But that is quite rare.

### Expected Behavior
When opening a dialog it should not flicker.

### Actual Behavior
When opening a dialog it flickers.

### Reproduction Link
<a href="https://codepen.io/tahnik/pen/abvymaZ" target="_blank">https://codepen.io/tahnik/pen/abvymaZ</a>

**Comment by jacekkarczmarczyk** [comment]
last working version: 2.2.20
probs https://github.com/vuetifyjs/vuetify/commit/63eb1be1ea756453a5bf1268deb4b501baca96d7

**Comment by MajesticPotatoe** [comment]
@jacekkarczmarczyk Can confirm, that merge #10975 is the culprit
