### ISSUE TITLE
Regression - broken layout of dropdown buttons

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1126]
### Steps to reproduce
See section "#3 Button Dropdown Variants" in https://vuetifyjs.com/components/buttons _(BTW - section names in docs should have ids - would be easier to send the link to specific section)_

http://imgur.com/a/xE1cY

### Versions
0.14.6, this is regression from 0.14.5

**Comment by julkuh** [comment]
Seems to be related with swapping paddings and margins in [79bf54b75e89aceb87cde33f533249d77f6a2c1a](https://github.com/vuetifyjs/vuetify/commit/79bf54b75e89aceb87cde33f533249d77f6a2c1a) in src/stylus/components/_input-groups.styl

**Comment by johnleider** [comment]
Sections do have id's, but hashes are not passed when nginx proxies the request to the local node server.

**Comment by johnleider** [comment]
(╯°□°）╯︵ ┻━┻
