### ISSUE TITLE
[Bug Report] v-menu "right" option does not work

### ISSUE THREAD

**Issue by itelmenko** [vuetifyjs/vuetify#11268]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64, Windows

### Steps to reproduce
Click on button. And menu will be appeared as left aligned on the page. 

### Expected Behavior
I use :right="true" for v-menu . I expect the menu will be right aligned on the page (moved to right border of page).

### Actual Behavior
The menu will be appeared as left aligned on the page. 

### Reproduction Link
<a href="https://codepen.io/itelmenko/pen/WNQOYrj" target="_blank">https://codepen.io/itelmenko/pen/WNQOYrj</a>

**Comment by johnleider** [comment]
You are missing an activator, it doesn't know where to go. Also putting it into a container that is relatively positioned that the activator itself is not a child of is going to yield weird results. With the activator you do not need to manually toggle the model.

Your example working: https://codepen.io/johnjleider/pen/QWjxpJb

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by itelmenko** [comment]
@johnleider it should be right aligned. But it is not right aligned

**Comment by itelmenko** [comment]
I have resolved my problem in CSS

```
.v-menu__content {
        right: 15px !important;
        left: auto !important;
        top: 50px !important;
        .v-application--is-rtl & {
            right: auto !important;
            left: 15px !important;
        }
    }
 ```

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
