### ISSUE TITLE
[Bug Report] v-menu attach not working in vuetify datatable header filter

### ISSUE THREAD

**Issue by chans-me** [vuetifyjs/vuetify#11266]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
In the codepen there are two different datepicker used, when data is present the datepicker is showing as expected, if the table is empty while filtering, datepicker hides inside datatable

### Expected Behavior
The datepicker should be showing outside the footer instead of hides inside the table

### Actual Behavior
When attach is used it should be sticky to the datepicker input box, so that when horizontal scrolling happens, datepicker will also scroll along with input box.

At the same time, when no data is present in table both select dropdown options and datepicker hides inside the table. Tried the z-index for footer as well as datepicker. It didn't worked . Is this a bug or is there any other way to handle this case

### Reproduction Link
<a href="https://codepen.io/chansv/pen/XWmamRP?editors=1000" target="_blank">https://codepen.io/chansv/pen/XWmamRP?editors=1000</a>

**Comment by itelmenko** [comment]
I think it is because table rebuilds in DOM. Old tree in DOM (with your menu) removes.

**Comment by chans-me** [comment]
@itelmenko , Is there any alternate approach to get that done. There are two things
1) on horizontal scroll dropdown items in select or datepicker should stick to input box
2) the dropdown options and datepicker should display outside footer

Please suggest some idea or approach

**Comment by itelmenko** [comment]
> the dropdown options and datepicker should display outside footer
Easy way - just define height of table more than menu height

**Comment by KaelWD** [comment]
Attach keeps the menu element where it is in the DOM instead of moving it to the root of the app. If a parent has overflow hidden it will then be cut off. Absolutely positioned elements don't contribute to height, you have to set an appropriate min-height manually.

**Comment by ashumsd7** [comment]
Can you look at this? https://codesandbox.io/s/vuetify-starter-template-forked-k4jd7s
