### ISSUE TITLE
[Bug Report] VFooter does not properly update $vuetify.application.footer when the app and  inset props are set

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#11267]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1, Google Chrome
**OS:** Mac OS 10.15.4, Windows

### Steps to reproduce
Open reproduction link

### Expected Behavior
$vuetify.application.footer should have a value of 36

### Actual Behavior
$vuetify.application.footer has a value of 0

### Reproduction Link
<a href="https://codepen.io/ChrisLandowski/pen/LYpjLWv?editors=1010" target="_blank">https://codepen.io/ChrisLandowski/pen/LYpjLWv?editors=1010</a>

**Comment by johnleider** [comment]
When the footer is in **inset** mode it moves to a new container called `insetFooter`. While it is documented, it was listed incorrectly as `footerInset`; that has been corrected.

![image](https://user-images.githubusercontent.com/9064066/101044749-529d7b00-3545-11eb-9dea-8a1b5c825871.png)

More information can be found here: https://vuetifyjs.com/en/components/application/#application-service

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
