### ISSUE TITLE
[Feature Request] import added in vuetify custom svg icons in vuex

### ISSUE THREAD

**Issue by ctmqwe** [vuetifyjs/vuetify#11265]
### Problem to solve
reactive state for specific logic

### Proposed solution
import added in vuetify custom svg icons in vuex

```
  icons: {
    values: {
      myIcon: {
        component: awesomeIcon
      }
    }
  }
```
How to import that icons in vuex?

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
