### ISSUE TITLE
Bug in the data table

### ISSUE THREAD

**Issue by xf0rk** [vuetifyjs/vuetify#1127]
### Steps to reproduce
There is a bug in the official demo for the data table. When all the items or one item selected in the data table, there seems only the change in the background color, but the checkbox dose not show be choosed.

### Versions

0.14.6

### What is expected ?

the checkbox should show as the checkbox is choosed
![qq 20170725175732](https://user-images.githubusercontent.com/10670906/28566788-c573cd32-7162-11e7-90a9-4aac30aebff2.png)

**Comment by johnleider** [comment]
Fixed in #1135
