### ISSUE TITLE
[Bug Report] <v-icon> causing unexpected scroll behavior in safari

### ISSUE THREAD

**Issue by hbackman** [vuetifyjs/vuetify#11270]
### Environment
**Vuetify Version:** 2.2.24
**Vue Version:** 2.6.11
**Browsers:** Safari, Mozilla Firefox
**OS:** Mac OS 10.15.4

### Steps to reproduce
Open in safari

### Expected Behavior
No scrollbar should be shown

### Actual Behavior
Overflow is produced and wrapper gets scrollbar

### Reproduction Link
<a href="https://codepen.io/hbackman/pen/RwWZxKV" target="_blank">https://codepen.io/hbackman/pen/RwWZxKV</a>

### Other comments
Im fairly certain that this is an issue in firefox as well. But we encountered this while migrating from 1.5 to 2.

**Comment by hbackman** [comment]
Hotfix:
`
.v-icon {
  &::after {
    left: 0 !important;
  }
}
`

**Comment by johnleider** [comment]
We are unable to reproduce this now and that style is part of the v-icon styles.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by renoirb** [comment]
To confirm, we couldn't see a scroll bar as described in the description. We've also tried when exactly the same version of Vuetify as also mentionned in the description.

| Default | When increasing font |
| ------- | --------------------- |
| <img width="740" alt="Default" src="https://user-images.githubusercontent.com/296940/102509019-d044a900-4064-11eb-971d-734db0319930.png"> | <img width="1070" alt="When increasing font" src="https://user-images.githubusercontent.com/296940/102509063-db97d480-4064-11eb-8ff0-ebae1fa3c889.png"> |

**Comment by hbackman** [comment]
I apologize for the late response.

I can still replicate this using the codepen provided. This seems to be a browser-specific issue for Safari on MacOS. The following screenshot is taken in Safari 13.1 on MacOS 10.15.4 (Catalina).

![Screenshot](https://user-images.githubusercontent.com/7362888/116284044-a1e58180-a75a-11eb-8621-9f43b7b16823.png)
