### ISSUE TITLE
[Bug Report] Devtools to load vuetify.css.map

### ISSUE THREAD

**Issue by ariefsn** [vuetifyjs/vuetify#11287]
### Environment
**Vuetify Version:** 2.2.26
**Last working version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Other comments
Hi, I've got a warning

```DevTools failed to load SourceMap: Could not load content for http://localhost:5001/vuetify.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE```

How to fix that?
It's happened on Nuxt v2.12.2

Thanks

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

You may need to use https://webpack.js.org/loaders/source-map-loader/
