### ISSUE TITLE
[Bug Report] v-select dense has no padding 

### ISSUE THREAD

**Issue by vinihvc** [vuetifyjs/vuetify#11285]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Edge 81.0.416.68
**OS:** Windows 10

### Steps to reproduce
Add tags: multiple, chips, dense and select many items to breakline 

### Expected Behavior
has padding in v-chips

### Actual Behavior
items when breakline are together

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-6ycgu?file=/src/layout.vue:188-234" target="_blank">https://codesandbox.io/s/vuetify-playground-6ycgu?file=/src/layout.vue:188-234</a>

### Other comments
maybe this PR cause #10877

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
