### ISSUE TITLE
[Bug Report] await with $vuetify.goTo doesn't wait the right amount of time for scroll to finish

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#11286]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1
**OS:** Mac OS 10.15.4

### Steps to reproduce
Running the following code

    const m1 = Date.now()
    await this.$vuetify.goTo(this.$refs.div, { duration: 5000 })
    const m2 = Date.now()
    console.log(m2 - m1)

doesn't do what is expected.

### Expected Behavior
I expected the elapsed time to be at least 5000ms.  Instead it's around 3000ms.

### Actual Behavior
The Promise is completed, but it doesn't appear to be waiting for the duration of the scroll to complete.  The documentation doesn't really make it clear as to whether this is the desired behavior, but it sure would make sense.  It's waiting for something apparently.

### Reproduction Link
<a href="https://github.com/daviesdoclc/vuetify-goto" target="_blank">https://github.com/daviesdoclc/vuetify-goto</a>

**Comment by jacekkarczmarczyk** [comment]
`goTo` tries to scroll the element to the top of the screen, it stops when it's not possible to scroll more

Append `<div style="background-color:grey; height: 2500px; width: 100%"></div>` to your container and you'll see proper value of `m2-m1`
