### ISSUE TITLE
[Bug Report] Menus not WCAG compliant

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#11281]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Linux x86_64

### Steps to reproduce
Enable a screen reader.  ChromeVox is a simple extension that works fine.  Now, try to tab to the button and open the menu via enter.  The screen reader can't get into the menu.  Yes, you can key down to access the items, but the screen reader can't get in there.  

This is sort of a big oversight for users that need screen readers.  I don't know enough about how it's implemented to know what the fix is.

I have attempted to add hacks and work arounds by auto focusing the first list item in the menu like this:

```
// accessibility compliance.  Need to focus the first element in the list when it opens
setTimeout(() => {
      document.querySelector('.viewSelector__list .v-list-item').focus()
 }, 300)
```

Which does focus the screen reader on the first list item.  However, using the reader navigation hotkeys dismisses the modal, due to one of these blocks:
![changeListIndex](https://user-images.githubusercontent.com/1561245/80719505-902ab900-8ac9-11ea-9f08-030b1909d3fb.png)
![getTIles](https://user-images.githubusercontent.com/1561245/80719522-95880380-8ac9-11ea-8340-b4539a0dd87b.png)

It appears it has something to do with evaluating infinite scrolling, or something like that.

### Expected Behavior
Using the screen reader navigation controls to enter the menu content and read it aloud.

### Actual Behavior
There is no way for the screen reader to get into the menu list.  With the hack to add focus, it does get in, however if you tab to switch the reader focus, it closes the menu.  

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/YzyxbYj?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fmenus%2F" target="_blank">https://codepen.io/gabaum10/pen/YzyxbYj?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fmenus%2F</a>

**Comment by KaelWD** [comment]
v-menu supplies `aria-activedescendant` to the activator slot through `attrs`:

```html
<template v-slot:activator="{ on, attrs }">
  <v-btn v-on="on" v-bind="attrs">
```

**Comment by gabaum10** [comment]
@KaelWD what about menus activated by an external activator?

**Comment by gabaum10** [comment]
Also, do you have a more complete option?  Just setting that `v-bind` on the activator is not sufficient.  Tabbing just tabs to the next button, not the menu content.

**Comment by gabaum10** [comment]
Ah, I see how it works now.  It does do the trick. Misunderstood how the `activedescendant` works.  Still getting up to speed on all the accessibility labels.
