### ISSUE TITLE
[Bug Report] v-btn with input type="submit" not supported

### ISSUE THREAD

**Issue by dougalg** [vuetifyjs/vuetify#11289]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.15

### Steps to reproduce
The `type` prop is ignored here

```
<v-btn
	tag="input"
	type="submit"
	value="Log In"
	name="login"
	elevation="0"
/>
```

### Expected Behavior
The `type` prop should be rendered on the `input` button.

### Actual Behavior
The type prop is ignored.

### Reproduction Link
<a href="https://codepen.io/dougalg/pen/XWmejzv" target="_blank">https://codepen.io/dougalg/pen/XWmejzv</a>

### Other comments
In the v-btn render function I can see that the type is ignored if the tag is not a button:

```
    if (tag === 'button') {
      data.attrs!.type = this.type
      data.attrs!.disabled = this.disabled
    }
```

**Comment by johnleider** [comment]
This feels like a very large change for a very niche issue. Thoughts @vuetifyjs/core-team @vuetifyjs/contributors?

**Comment by jacekkarczmarczyk** [comment]
I'm not against it in general but not sure if this https://github.com/vuetifyjs/vuetify/pull/11291/files#diff-b9df24aeee7383f4d61be9e1db86b8cdR39 is the best way to do it (don't have a better idea atm so sorry for not being constructive)

**Comment by dougalg** [comment]
@johnleider @jacekkarczmarczyk I've made a small change to the PR so that the fix still remains in place, but it removes the `CAN_HAVE_X` logic. Now it allows `type`/`disabled` on any tag. The caveat is that `type` needs to be manually specified if `tag` is not a button.

**Comment by dougalg** [comment]
Personally, I view this is an accessibility concern. It's more semantic, and you get automatic form bindings for things like the enter key, and so on.  I think we should support `input type="submit"` as a very expected use case, it doesn't seem like a niche issue to me, but rather like supporting standard, semantic HTML.

**Comment by phiter** [comment]
@dougalg actually using a button with `type="submit"` already works for submitting the form automatically on pressing enter. There is not much of a difference between the two.

[Difference between <button type="submit"> and <input type="submit">](
https://html.com/attributes/button-type/#Difference_between_ltbutton_typesubmitgt_and_ltinput_typesubmitgt)

**Comment by YipingRuan** [comment]
Do we still follow the "all the attributes should be preserved on the rendered html element" idea?

**Comment by dougalg** [comment]
@phiter thanks for that. It sounds like I can just close this bug report as unnecessary, then. I will test it out in my code first, but sounds like I was just under an incorrect assumption. Thanks for clarifying!

**Comment by dougalg** [comment]
Closing based on feedback from @phiter .

**Comment by johnleider** [comment]
Thank you for your report and feedback.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
