### ISSUE TITLE
Feature Request # Destroy|Mount Tabs when switching

### ISSUE THREAD

**Issue by smtlk** [vuetifyjs/vuetify#1128]
Hi, i have a feature request, it seems that v-tabs does not destroy and mount the content when it changes, it simply loads everything at when the page loads and keeps the state of components in it even if you switch tabs.
Sometimes i want for instance a tab to reset when i switch to another one and this is difficult to do with the current implementation. For instance take a component that makes use of a library like FineUploader where everything including Dropzones are defined and set in a constructor, if i have multiple tabs it won't set any dropzones apart from the one in the first tab's content presumably because they don't exist in the DOM yet or are not visible, however if these were mounted when i switch it would presumably run the constructor each time the tabs switch and as such it would re-set a new instance of FineUploader if i'm not mistaken.

Perhaps i'm the one who is misunderstanding the purpose of the tabs in which case i'd appreciate some clarification from the community if possible, thank in advance for your help

**Comment by smtlk** [comment]
I kinda went around the issue by simply removing the tab-contents and using the router directly through the **to** prop and perhaps this is the way it's supposed to be done, through VueRouter, however i still think it would be a good idea as long as it's kept optional

**Comment by guykatz** [comment]
I have used conditional rendering (v-if) on tab-content to achieve this...

**Comment by johnleider** [comment]
@guykatz's answer is correct. Using v-if conditionally on the v-tabs-content would be the correct way to handle this.

**Comment by kjmj** [comment]
@guykatz @johnleider Sorry to bring up this old topic, but it isn't clear to me on how to force a tab to destroy/mount when switching. You mentioned to use `v-if`, but what exactly do I use there?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
