### ISSUE TITLE
[Documentation] What is the purpose of the 'required' attribute for child components of <v-form/> ?

### ISSUE THREAD

**Issue by jamercee** [vuetifyjs/vuetify#11283]
### Environment

**Browsers:** Firefox 75.0
**OS:** Windows 10

### Steps to reproduce
The documentation for `<v-form/>` applies a `required` attribute to `<v-text-field/>` child components. But there is no reference to this attribute in the `<v-text-field/>` documentation and there is no explanation of it's use in the `<v-form/>` documentation.

### Expected Behavior
A link to relevant info

### Actual Behavior
Missing doc.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/forms/" target="_blank">https://vuetifyjs.com/en/components/forms/</a>

**Comment by MajesticPotatoe** [comment]
That would be because `required` isn't a vuetify prop, but a attribute native to html inputs <https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required>

**Comment by jamercee** [comment]
Head smack!
