### ISSUE TITLE
[Bug Report] Treeview Open item is not correct

### ISSUE THREAD

**Issue by maitrungduc1410** [vuetifyjs/vuetify#11293]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.14.4

### Steps to reproduce
open `Applications` -> open `Documents` -> open `vuetify` -> open `src` -> open `Downloads` -> open `Videos` -> close `Documents` -> close `Downloads` -> close `Videos` -> close `Applications`

### Expected Behavior
final open items should be `[]` (when all items are closed)

### Actual Behavior
final open items still left `[ "vuetify :", "src :" ]` (when all items are closed)

### Reproduction Link
<a href="https://codepen.io/maitrungduc1410/pen/bGVoWRJ" target="_blank">https://codepen.io/maitrungduc1410/pen/bGVoWRJ</a>

### Other comments
If try open and close items in any other order will result into another different result in the final when all items are closed

**Comment by nekosaur** [comment]
While I get where you're coming from (items in `open` are not visibly open), the current behavior is correct. If all children of a parent node that closes are marked as closed as well, then there would be no 'history' of opened child nodes, and re-opening `Documents` in this case would not show vuetify and src as still open.

If anything this would be a feature request, not a bug report.

**Comment by maitrungduc1410** [comment]
@nekosaur thanks for your answer,

Now I understand the behavior
