### ISSUE TITLE
[Bug Report] v-treeview expand-icon no append option and no way to remove

### ISSUE THREAD

**Issue by robiharid** [vuetifyjs/vuetify#11297]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.5.20
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Please allow expand-icon none so that I can manually append an icon using v-slot
OR
Add expand-icon-append so I can put an icon on the right

### Expected Behavior
Expand-icon on the right (append)
AND
Expand-icon=" none" to remove the element completely

### Actual Behavior
Expand-icon remains on screen even if invisible

### Reproduction Link
<a href="https://codepen.io/trojanz/pen/mdeBLMR?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftreeview%2F" target="_blank">https://codepen.io/trojanz/pen/mdeBLMR?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftreeview%2F</a>

**Comment by mgamboa66** [comment]
Any update on this?
