### ISSUE TITLE
[Feature Request] Make possible to set position for "rows per page" dropdown on v-data-table (v-menu component position)

### ISSUE THREAD

**Issue by Balex70** [vuetifyjs/vuetify#11296]
### Problem to solve
I have tried to include v-data-table to my Admin LTE 3 Bootstrap Template and faced a problem with offset for "rows per page" dropdown.

### Proposed solution
Make possible to set "position: fixed" for that element, the same as it is on v-menu component. Changing position to "fixed" solves the problem perfectly.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
