### ISSUE TITLE
Cannot read property 'pop' of undefined"

### ISSUE THREAD

**Issue by Hidejec** [vuetifyjs/vuetify#1129]
### Steps to reproduce
1. Install/Update Vuetify to 0.14.6
2. The component will not render because of the error. "Cannot read property 'pop' of undefined" written in the console.
### Versions
Vue 2.4.2
Vuetify 0.14.6

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by schneekopf** [comment]
pls reopen this issue.
Its the official vuetify template "webpack-advanced" from vuetify, that has this issue when the vuetify version is updatet to 0.14.0 or higher.

vue init vuetifyjs/webpack-advanced

**Comment by schneekopf** [comment]
its the first line "chlidren" which is undefined

  var iconName = children.pop().text;
  var thirdPartyIcon = iconName.indexOf('-') > -1;
  var iconType = thirdPartyIcon ? iconName.slice(0, iconName.indexOf('-')) : 'material-icons';

**Comment by johnleider** [comment]
The point I'm trying to make is that there is boilerplate provided to you when creating an issue. If you don't follow this, I cannot help you.

**Comment by schneekopf** [comment]
### Steps to reproduce
Install official vuetify webpack simple template
```
$  vue init vuetifyjs/webpack
update package.json set Vuetify to 0.14.6
npm install
//build all
webpack -p
```
### Versions
all vuetify versions 0.14.0 or higher

### What is expected ?
A working example from vuetify with the latest vuetify dependencies


### What is actually happening ?
doesent work, error Cannot read property 'pop' of undefined

### Reproduction Link
[https://jsfiddle.net/schneekopf/bzkagw24/](https://jsfiddle.net/schneekopf/bzkagw24/)

**Comment by johnleider** [comment]
Nothing works on that jsfiddle

**Comment by Darkside73** [comment]
It's reproduced when trying to use v-text bind in v-icon component. Check this out: https://codepen.io/darkside73/pen/EvawQN
