### ISSUE TITLE
[Feature Request] carousel-delimiters: active changes color /btn: hide visuals

### ISSUE THREAD

**Issue by Spreekatze** [vuetifyjs/vuetify#11295]
### Problem to solve
I have a card and a carousel with delimiters at the bottom of it. I do not like to see the "active" icon circled with the button-visuals. Instead I want it to simply change the color of the icon, whenever it is active. If possible, it would also be nice, that the "hover"-effect on the other not active icons didnt show that "button"-visual either, also instead changing the color.

I can find the css-parts in vuetify, were all that is set, but it always gets overwritten by vuetify, so i cant change it myself. (At least I havent been able to find a solution.)

### Proposed solution
Give the delimiter/buttons more properties for customizations
In this case: 
-colorchange on active and hover for delimiters 
-hide the "button"-visual overall (set opacity to 0), so only the icon shows

**Comment by nekosaur** [comment]
Please provide a codepen that tries to illustrate what you want to accomplish with this feature request.

**Comment by Spreekatze** [comment]
Im not sure, how to put what i want in codepen....
I think, i would like something similar to the bootstrap solution in visual (especially for the "button circle". In bootstrap there is no "extra" circle
https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_carousel&stacked=h


Well instead of "filling" the circle, I would simply like it to change color (from default white to red for example).

In vuetify, how I want it to be in code:
<v-carousel flat-btn delimiter-color: ....... delimiter-color-hover: ....... >

**Comment by nekosaur** [comment]
This is possible with some custom css https://codepen.io/nekosaur/pen/zYvERLZ. Adding props for each combination of delimiter state color will not happen.

**Comment by Spreekatze** [comment]
Thanks for that code, but i find myself troubled:

My current App-state is kind of like this:
<v-app>
   <v-card>
      <LeftSide/>
      <v-divider vertical/>
      <RightSide/>
   <v-card>
<v-app>

If I put that <v-carousel> -Code that you gave me into <v-card> instead of <LeftSide/> for example, it works just fine. If I put it into my LeftSide-Component (where I want it), it doesnt.  The delimiter doesnt get affected there.

**Comment by Spreekatze** [comment]
Nvm, i still had "scoped" inside my style-tag.
Thx alot.
