### ISSUE TITLE
v-text-field multi-line placeholder overlaps label

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1130]
### Steps to reproduce
See codepen

### Versions
Vuetify 0.14.6

### What is expected ?
No overlap

### What is actually happening ?
Placeholder text and Label overlap only for multi-line textfields

### Reproduction Link
https://codepen.io/anon/pen/gxbwoW

**Comment by johnleider** [comment]
Duplicate of #1119
