### ISSUE TITLE
[Bug Report] v-combobox arrow button doesn't close menu if clearable is removed

### ISSUE THREAD

**Issue by Agendum** [vuetifyjs/vuetify#11312]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Edge 81.0.416.68
**OS:** Windows 10

### Steps to reproduce
This is the real reproduction link, I cannot seem to provide Vuetify's own documentation for repro link: https://vuetifyjs.com/en/components/combobox

In the top 'Usage' of the page, notice the arrow opens and closes the menu.

Toggle on Clearable, notice the arrow opens and closes the menu.

Toggle off  Clearable, notice the arrow opens, but does not close the menu.

### Expected Behavior
The arrow button will always close the menu even if clearable is removed.

### Actual Behavior
The arrow button does not close the menu.

### Reproduction Link
<a href="https://jsfiddle.net" target="_blank">https://jsfiddle.net</a>

**Comment by jacekkarczmarczyk** [comment]
MIght be docs issue, seems to work here https://codepen.io/jkarczm/pen/LYpOLqq?editors=1000

**Comment by KaelWD** [comment]
I can reproduce it in your codepen @jacekkarczmarczyk
