### ISSUE TITLE
v-icon can't be empty anymore and is incompatible with v-html

### ISSUE THREAD

**Issue by cb109** [vuetifyjs/vuetify#1131]
### Steps to reproduce
See below.

### Versions
`0.14.3` - `0.14.6`

### What is expected ?
Prior to `0.14.3` I was able to do two things that now break the `v-icon` component.

First was conditional icon names, meaning a `v-icon` could be empty like:

    <v-icon></v-icon>

Second was using the `v-html` directive on a `v-icon`, e.g. to assign icon names from objects inside a `v-for` loop.

    <v-icon v-html="item.icon"></v-icon>

### What is actually happening ?
Both now result in errors in the console. See codepens below.

### Reproduction Link
- For first issue see: https://codepen.io/anon/pen/XaJpYE?editors=1111
- For second issue see: https://codepen.io/anon/pen/oegZLv?editors=1111

**Both are no show-stoppers, I just want you to be aware of it. If it is intended behaviour, feel free to close.**

**Comment by johnleider** [comment]
I've honestly never been able to use v-html on v-icon, or at least, every time I tried I had issues.

**Comment by cb109** [comment]
Yes that's really no loss and a good idea to refactor-out anyway. What I had a lot was something like this:
```html
<v-icon>
  <span v-if="condition">whatever1</span>
  <span v-if="!condition">whatever2</span>
</v-icon>
```
Now using two v-icons as a workaround.

**Comment by thelolagemann** [comment]
Something like this for conditional icons?
https://codepen.io/TheLolageMann/pen/RZNgBX?editors=1111

**Comment by JankoHrasko7** [comment]
@johnleider  Please remove folloving icons from webpack-advanced then:

**Comment by cb109** [comment]
Thanks guys :+1: !
