### ISSUE TITLE
[Bug Report] v-slider with step makes a linked text field unusable

### ISSUE THREAD

**Issue by lukasrossa** [vuetifyjs/vuetify#11318]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Setup a stepped slider (step=100) with a prepended text field linked to the same value.
Try and enter the value 800 into the text field.

### Expected Behavior
It should allow you to enter the value

### Actual Behavior
There are different outcomes depending on which way you attempt to enter 800, but either way you cannot enter the value into the text field:
1. Double-click into text field (select value) and start typing 800 >> value gets incorrectly prepended with 0 and you end up with 000
2. Click into text field, delete the default value (backspace or delete) and type 800 >> results in 1000

### Reproduction Link
<a href="https://codepen.io/lukasrossa/pen/KKdyrxa" target="_blank">https://codepen.io/lukasrossa/pen/KKdyrxa</a>

### Other comments
There are probably two separate issues:
The first one I think is linked to the min value of the slider (if you put a single digit min value in you can see the first digit always defaults to that)
The second one is caused by aggressive rounding. You can enter up to 400 without issues. When you reach 5xx the rounding kicks in and garbles your input. I don't know what the correct behaviour should be, maybe a slight delay on input..

**Comment by nekosaur** [comment]
Use `change` event on text field instead of `input`. https://codepen.io/nekosaur/pen/NWGXXZX

**Comment by lukasrossa** [comment]
Thanks for the suggestion - that works except the styling of the textbox inside the slot is not quite right - e.g. if I add a hint="$" to the text field it gets incorrectly displayed below the textfield.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
