### ISSUE TITLE
v-text-field loosing binding, styling and sometimes doesn't render when inside a v-tabs-content when navigating between tabs

### ISSUE THREAD

**Issue by jakemcallister** [vuetifyjs/vuetify#1132]
### Versions

Vue 2.4.0
Vuetify 0.14.3
### What is expected ?

When navigating between tabs if there is a v-text-field inside which is bound to a data attribute that it will continue to be bound and also retain its styling and still be rendered on the page

### What is actually happening ?

Seems to be loosing its binding, styling and sometimes isn't even on the page when you navigate between tabs a few times
### Reproduction Link

https://codepen.io/jakemcallister/pen/rzaLRK

**Comment by johnleider** [comment]
There are 2 issues with the reproduction:

-1 It doesn't have a v-app
-2 You are assigning a transition that does not exist

https://codepen.io/johnjleider/pen/zdxpzb

It also seems ```v-tabs-content``` was missed when it came to the conversion of how transitions work between components now. I've opened up a ticket specifically for that here: https://github.com/vuetifyjs/vuetify/issues/1133
