### ISSUE TITLE
[Bug Report] v-overlay doesnot work for onclick

### ISSUE THREAD

**Issue by hejun779** [vuetifyjs/vuetify#11326]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
1. add onclick on the  'v-overlay'. like this v-overlay :value="overlay" @click="overlay = false" 
2. run it
3. when click the v-overlay element, it should invoke some something, like close/ hide the v-overlay in this example

### Expected Behavior
v-overlay should support onclick event

### Actual Behavior
setting the onclick on v-overlay does not work. nothing happened.

### Reproduction Link
<a href="https://codepen.io/hejun7/pen/oNjpEmw" target="_blank">https://codepen.io/hejun7/pen/oNjpEmw</a>

**Comment by nekosaur** [comment]
Use `@click.native`

**Comment by DmitriyNevgod** [comment]
I used "v-click-outside" https://vuetifyjs.com/en/directives/click-outside/
