### ISSUE TITLE
[Documentation] Calendar: Weekly wiev bug on changing theme

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#11323]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
change theme on week wiev cause to v-calendar-daily__head height to grow infinitely

### Expected Behavior
dont canhe v-calendar-daily__head height

### Actual Behavior
 v-calendar-daily__head height to grow infinitely

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars/#weekly" target="_blank">https://vuetifyjs.com/en/components/calendars/#weekly</a>

**Comment by KaelWD** [comment]
I can't reproduce this.
