### ISSUE TITLE
[Bug Report] When v-avatar is first-child of v-card, border-top-radius is overwritten

### ISSUE THREAD

**Issue by speasley** [vuetifyjs/vuetify#11321]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.15.4

### Steps to reproduce
Include a v-avatar as the first child of a v-card

### Expected Behavior
The top-border-radius should be 50%, matching the bottom

### Actual Behavior
The top-border-radius is overwritten by a declaration that fails to exclude v-avatar

### Reproduction Link
<a href="https://codepen.io/speasley/pen/qBOpdGj" target="_blank">https://codepen.io/speasley/pen/qBOpdGj</a>

**Comment by anschwa** [comment]
Same for me.  
Vuetify: 2.3.1
Vue: 2.6.11
OS: Debian 4.19.98-1
Browser: Chrome 81.0.4044.138

**Comment by johnleider** [comment]
We are working on a unified way to solve this as it's functionality is present in multiple places of the framework.

**Comment by johnleider** [comment]
resolved by #13674

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
