### ISSUE TITLE
[Bug Report] <v-autocomplete> on Android browsers -> Space bar triggers wrongly @input and empties field

### ISSUE THREAD

**Issue by vibonacci** [vuetifyjs/vuetify#11322]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Android

### Steps to reproduce
1. Open jsfiddle in Chrome, Firefox, Samsung browsers on an actual Android device
2. Type p2 in the search box. So far so good.
3. Add a whitespace.

### Expected Behavior
After typing "p2", and then adding a whitespace, input string should be "p2 ". @input event should not be triggered after adding the whitespace.

### Actual Behavior
After typing "p2", and then adding a whitespace, @input is triggered. The field is now string " " (just the whitespace)

[Video](https://www.youtube.com/watch?v=qo-h6mWamcM)

### Reproduction Link
<a href="https://jsfiddle.net/sx4nmLa7/8/" target="_blank">https://jsfiddle.net/sx4nmLa7/8/</a>

### Other comments
Important: this ONLY happens on any Android browser I have tried. Everything works fine on Windows: Chrome, Firefox desktop versions. Mobile emulators of Windows Chrome and Firefox also do not trigger the problem.

When opening the jsfiddle on a mobile browser: layout might not be usable to debug. You can:
Scroll to right -> setting -> select layout Tabs (rows) or request desktop version of the site.

Notice that autocapitalize="off" autocomplete="off" spellcheck="false" autocorrect="off are all disabled and properly set on the input

**Comment by eric-u** [comment]
I experienced the same bug with Vuetify version 2.2.26. Upgrading to 2.3.1 resolved it for me!

**Comment by vibonacci** [comment]
I actually realized this 'issue' is related to v-model implementation and the 'composing' state of (some) mobile keyboards.

Explained here by the Vue boss:
https://github.com/vuejs/vue/issues/9777#issuecomment-478831263
