### ISSUE TITLE
[Bug Report] v-slider: thumb-label="true" causes validation warning when clicked

### ISSUE THREAD

**Issue by codingjourney** [vuetifyjs/vuetify#11336]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Linux

### Steps to reproduce
1. Create a v-slider or v-range-slider with thumb-label="true".
2. Click anywhere on the slider.

### Expected Behavior
No validation warning should appear on the Javascript console.

### Actual Behavior
It says [Vue warn]: Invalid prop: custom validator check failed for prop "thumbLabel".

### Reproduction Link
<a href="https://codepen.io/zenyatta/pen/KKdQyNO" target="_blank">https://codepen.io/zenyatta/pen/KKdQyNO</a>

### Other comments
The type declaration of thumbLabel says [Boolean, String] as PropType<boolean | 'always' | undefined>. Its custom validator says v => typeof v === 'boolean' || v === 'always'. My hypothesis is that the value "true" is interpreted as type "string" which makes the validation expression false. I don't know enough about TypeScript to know for sure if that's really the case or how to fix this.

**Comment by nekosaur** [comment]
Use `:thumb-label="true"`. Without the `:` you are passing the string `"true"`, not the boolean value `true`
