### ISSUE TITLE
[Feature Request] v-slider flexible tick visibility

### ISSUE THREAD

**Issue by paulofelipe84** [vuetifyjs/vuetify#11331]
### Problem to solve
I'm using v-slider as a media player track progress controller. I want to be able to add bookmarks to the track and add a tick to the slider for each bookmark created.

### Proposed solution
The component could have a prop with an array of positions where ticks should be displayed. 
It could work as a prop that would define the visibility of specific ticks.

**Comment by johnleider** [comment]
This will be part of #5592

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
