### ISSUE TITLE
[Bug Report] Datatable expand and then collapse causes table row rendering issue on XS only

### ISSUE THREAD

**Issue by BruceBradford** [vuetifyjs/vuetify#11337]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS, Mac OSX

### Steps to reproduce
1. Create datatable as in codepen above
2. View datatable in XS viewport
3. expand row
4. collapse row

### Expected Behavior
Datatable should show rows in XS form

### Actual Behavior
Datatable rendering breaks. It seems as if subsequent rows are then added/grouped in the first row. The datatable renders correct before expanding and collapsing 

### Reproduction Link
<a href="https://codepen.io/batwork/pen/wvKpQRv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F" target="_blank">https://codepen.io/batwork/pen/wvKpQRv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F</a>

### Other comments
You can reach me on discord at bRUCE2#6180 for any questions

**Comment by picasocro1** [comment]
I've found the same issue inside my project :( 

Any prospect for solving?

**Comment by robertodprieto** [comment]
Same usse, anything yet?

**Comment by HDenizD** [comment]
Same issue. +1
Any updates about this issue?

**Comment by abtechbit** [comment]
Same problem reproducible on Vuetify homepage: https://vuetifyjs.com/en/components/data-tables/#expandable-rows. 

Expanding works, after collapse table shows second column, showing 2 items in the first row.

OS: iOS 13.7
Browser: Safari 13.1
vuetify version: 2.4.0
vue.js version: 2.6.12

**Comment by azollai** [comment]
The issue is still there.
Workaround for now:
`
  @media #{map-get($display-breakpoints, 'xs-only')} {
    tbody {
      display: flex;
      flex-direction: column;
    }
  }`
