### ISSUE TITLE
Consistent: diffrent translation settings on data-tables

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#1134]
At the pagination part of the data-tables there are 2 parts wich are translatable:
1. the rows per page text
2. the 1 of ... text

These 2 need to be translated in a complete diffrent wat
1st:
```
        <v-data-table
                rows-per-page-text="Rijen per pagina"
```
2nd:
```
<template slot="pageText" scope="{ pageStart, pageStop }">
        From {{ pageStart }} to {{ pageStop }}
</template>
```

My question: is this the way it should be? or should it be more consistent.

Thanks for all your hard work!
- Ricardo

**Comment by nekosaur** [comment]
I agree that this should be more consistent, both in this component and across the library. We do have plans to support i18n through something like vue-i18n, which would solve this. 

I guess the answer to your question is: Yes, this is how it currently works. And yes, it should (and will) be more consistent.

**Comment by SystemZ** [comment]
Any changes on this?
