### ISSUE TITLE
[Bug Report] v-switch isn't visible anymore

### ISSUE THREAD

**Issue by PortStone** [vuetifyjs/vuetify#11344]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Linux x86_64

### Steps to reproduce
Click the v-switch button.

### Expected Behavior
v-switch should change to a different color to be visible and not the same as the bar.

### Actual Behavior
v-switch is using the same color as the bar itself and as a result you can't see it.

### Reproduction Link
<a href="https://codepen.io/PortStone/pen/WNQzbzG?editable=true&editors=101" target="_blank">https://codepen.io/PortStone/pen/WNQzbzG?editable=true&editors=101</a>

### Other comments
This is from the official docs. You can see the example here:  https://vuetifyjs.com/en/customization/theme/#usage

**Comment by jacekkarczmarczyk** [comment]
Last working version: 2.2.4 https://codepen.io/jkarczm/pen/MWaVYzO

**Comment by savylovskij** [comment]
Hey. Will this bug be fixed?

**Comment by KaelWD** [comment]
I think it's been like this for long enough that changing it back would be just as bad. The design can't always be 100% perfect out of the box, in this case all you have to do it set a different colour.
