### ISSUE TITLE
[Bug Report] v-divider printing acts weird on Google Chrome

### ISSUE THREAD

**Issue by PortStone** [vuetifyjs/vuetify#11356]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Linux x86_64

### Steps to reproduce
Click the print button.

### Expected Behavior
It will print the exact same thing as we can see on the bottom right corner.

### Actual Behavior
It doesn't print v-divider element

### Reproduction Link
<a href="https://jsfiddle.net/Le8m6brk/5/" target="_blank">https://jsfiddle.net/Le8m6brk/5/</a>

### Other comments
Firefox does it correctly. I don't know why but on Firefox it works as expected.

**Comment by jacekkarczmarczyk** [comment]
Vertical dividers should only be used in flex containers, and if you use it correctly it is printed in Chrome
```html
<div style="display: flex">
  <h1>Test</h1>
  <v-divider class="mx-12" vertical style="border-width: 20px;"></v-divider>
</div>
```
![image](https://user-images.githubusercontent.com/15625235/81468873-6452b600-91e2-11ea-9cd2-89548918ee71.png)
