### ISSUE TITLE
[Bug Report] clicking on a Chip of a Multiple Combobox makes the free text disappear

### ISSUE THREAD

**Issue by Amebus** [vuetifyjs/vuetify#11355]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
1. insert free text into the combobox input
2. click on a chip and the free text disappears

### Expected Behavior
the user's free text should remains visible when clicking on a chip

### Actual Behavior
the free text disappear and if you click out of the combobox input to make it lose focus the free text will appear again as a chip

### Reproduction Link
<a href="https://codepen.io/amebus/pen/LYpdrEv" target="_blank">https://codepen.io/amebus/pen/LYpdrEv</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
