### ISSUE TITLE
[Bug Report] Font weight doesn't work in combination with Typography

### ISSUE THREAD

**Issue by xdoo** [vuetifyjs/vuetify#11352]
### Environment
**Vuetify Version:** 2.3.0-beta.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Linux x86_64

### Steps to reproduce
Create a `<h1>` element and add a `class` attribute:

`<h1 class="font-weight-black text-h3 text-md-h2 text-lg-h1 text-xl-h1">This is my heading</h1>`

The font is never displayed as font-weight-black (the typography works as expected). If you take:

`<h1 class="font-weight-black">This is my heading</h1>`

The text is a black heading.

 

### Expected Behavior
Font weight should be black.

### Actual Behavior
Font weight is regular.

### Reproduction Link
<a href="https://github.com/xdoo/vuetify_responsive_sample" target="_blank">https://github.com/xdoo/vuetify_responsive_sample</a>

### Other comments
You can find the sample code under @/components/ResponsiveText.vue.

**Comment by jacekkarczmarczyk** [comment]
looks like `font-weight` is overwritten because of `@media ...` that's applied to `text-h3` class etc but not to `font-weight-*`

**Comment by johnleider** [comment]
Resolved in c11ae35ab4275b72525c829969184884d9e3bc34

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
