### ISSUE TITLE
[Feature Request] vBtn could have wrap-text props

### ISSUE THREAD

**Issue by sinh117801** [vuetifyjs/vuetify#11357]
### Problem to solve
Should allow the button to wrap the text

Codepen link: https://codepen.io/sinh117801/pen/dyYmEXx

### Proposed solution
the solution i use is to custom `.v-btn__content`

`
.v-btn__content {
  width: 100%;
  white-space: normal;
}
`

**Comment by phiter** [comment]
I understand the issue but I think it's important to note that the Material Design spec is against this.

[Material Design - Buttons Anatomy](https://material.io/components/buttons#anatomy).

![image](https://user-images.githubusercontent.com/12252332/81836145-7356a280-9519-11ea-9fdc-8b7c7d5d24dc.png)

The button text should be in a single line and also it should be short, which would make buttons less prone to need line breaking.

![image](https://user-images.githubusercontent.com/12252332/81836242-95502500-9519-11ea-9abe-9d25cc4c3770.png)

**Comment by sinh117801** [comment]
Thank for explanation and ref. I got the point now.

**Comment by Blindpupil** [comment]
This is unavoidable when you have to cater for other languages. I'm currently working on a German client and the words are just too long to avoid this issue.

**Comment by bmikaili** [comment]
How do people handle long text in buttons?

**Comment by tarreislam** [comment]
> How do people handle long text in buttons?

I ended up creating my own custom component

**Comment by arturslab** [comment]
This is my simple solution for wrapping long text in buttons
[https://codepen.io/melma-pl/pen/jOXgoLr](https://codepen.io/melma-pl/pen/jOXgoLr)

![obraz](https://github.com/vuetifyjs/vuetify/assets/40725161/3acfb498-88b5-43a5-93ad-0244b2dde0ee)

**Comment by hanamurayuki** [comment]
I ended up below way.
```
<v-btn>
  <span>
    1st line<br />
    <span class="text-caption" style="line-height: unset">2nd line</span>
  </span>
</v-btn>
```
