### ISSUE TITLE
[Feature Request] Data tables: items per page disabled

### ISSUE THREAD

**Issue by GautierDele** [vuetifyjs/vuetify#11367]
![image](https://user-images.githubusercontent.com/12382966/81546118-2f796700-937a-11ea-86ea-aa07fc6a5fa6.png)

### Problem to solve
I had a feedback from my users that when the items-per-page from a data table footer is disabled, the fact that the icon next to the current value is still there is confusing.

### Proposed solution
Remove this icon when the per page is disabled
Add an option to hide this feature that is not needed in some cases

**Comment by johnleider** [comment]
This is the standard styling for the generic Vuetify select. I suggest using custom css to target that element in a disabled state and hide it.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
