### ISSUE TITLE
[Bug Report] v-autocomplete ajax with "cache-items" and "no-filter" don't refresh items

### ISSUE THREAD

**Issue by bufferUnderrun** [vuetifyjs/vuetify#11365]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0, Google Chrome, Mozilla Firefox, Internet Explorer
**OS:** Windows 10

### Steps to reproduce
When "cache-items" and "no-filter" enabled, the search does not working.

1. search "oh" to filter results, "Ohio" should be listed but no because the filter did not refresh items list.

### Actual Behavior
When "cache-items" is disabled, the behaviour is correct. So why the issue : because the "multiple" property need "cache-items" and with "no-filter" it does not work.

### Reproduction Link
<a href="https://codepen.io/cp10/pen/gOazVgQ" target="_blank">https://codepen.io/cp10/pen/gOazVgQ</a>

### Other comments
I needs  the "no-filter" need because filtering is done server-side.

**Comment by jacekkarczmarczyk** [comment]
Ohio is not listed even if i skip the first step, can you clarify what is it for?

**Comment by bufferUnderrun** [comment]
@jacekkarczmarczyk you're right, the issue appears with "cache-items" and another with "multiple", "cache-items" and "no-filter"

**Comment by dezet** [comment]
I do have the same problem. V-autocomplete with options "multiple & "cache-items" & "no-filter" doesn't work as expected. After the ajax call list of aucomplete entries is not being updated with new entities. Is it expected behaviour?

**Comment by teocomi** [comment]
Same issue here, seems that the cached items are not cleared and always show in the list. And without `cache-items` multi select is not working properly.

**Comment by Nocturem** [comment]
Similar issue, generally the inability to clear the cached items between interactions is a problem.
possibly when de-selecting the component might be a logical point to clear cache as its a point when a user may be finished interacting with that element.

**Comment by bka9** [comment]
I have the same issue and I have found this workaround for the time being:

1. Add a `ref` to the v-autocomplete component.
2. When you set the `items` attribute with the response from the ajax request you also set the `cachedItems` property of the v-autocomplete:
```
this.$refs['name-of-ref'].cachedItems = <items from ajax response> + <currently selected item(s)>
```

**Comment by jobserver** [comment]
@bka9  

> I have the same issue and I have found this workaround for the time being:
> 
> 1. Add a `ref` to the v-autocomplete component.
> 2. When you set the `items` attribute with the response from the ajax request you also set the `cachedItems` property of the v-autocomplete:
> 
> ```
> this.$refs['name-of-ref'].cachedItems = <items from ajax response> + <currently selected item(s)>
> ```

**thanks, it worked for me**

**Comment by petiphan** [comment]
@bufferUnderrun Has it already fixed?

**Comment by lioneaglesolutions** [comment]
Closing as this is resolved in V3

https://play.vuetifyjs.com/#eNqNVm1v2zYQ/iucPjQOEFlZ22GA52QtUqzN2iRFky0Y6nw4S+eINUVqJOWXtf7vO1KKrZAOWsCAxeeO9/IcybvPX5PXdT1cNJiMkrHFqhZg8XQiGRsvUquUmIJmuRJKn0wSiyAmiZf25anlVuDptaWtzKDA3HIlx1moMJHbndBYlSvyhhZbkLFFWqkCBflpbUySQDIyCDovvYL72CmMhIKCy3sSdV89Gae0DEn8/w7PBRgHV6v05Q4tUBpu14RTeDOlLUwF9jZBXmLaWuqgkheYSpUWYOERVqAFLrZ6AqY+udsSLDOeK9DI1qphM62q33dOjF0LdJHBKl3ywpYj9uL4uF799qBy6rjtU9indmol47mSzkDB00JZky5QW5774rmtpNKWeFciWo+zXv3HJte8tl4NVzURQdTMoBGWfW1duXzZ4PBhyZhG22i5W1PKbS1GbAbC4NFO4Akcsc93Payt6YjJRohHsDsLMewIdCZ2EGMHr4lkqOCgp9iiZh6BFWqiRLJrqFQk1Pw/JWN0DtKACeAzEJxOiuSh/pm7NlCoCJbSXZG8sYHkDQpY0qEIYW4sxWqZmjGy2VTTyNUfWKAmRgrmb6Fxqhc810qiiZUpLF6E6FtU+j7SfdtAFUDvKEbOA/C8gDJM9FwILhUP+TqXBYeI3HO1DKH3+9h+j9I2+XwdwB9UwynTyOwFcBnyeQHalCAEOzcCZBF6IPHa4RFsDN3+xqC10Rael/weZARTpY2yUVDcGPer65BGJ1GNjmAlbZzbJU71npN9iQuIqnuJS/YOqtqUPDpfTvYnaoMhqU5wgSt6TfYI/lF6HsL0TJTsDLSiwkcReOEbmMd8eBHS20HUuxo+UZirkoeBXM0Fnbvoxl9pvFdhNT6CgCbEUEqzFguIb+/Hhh5NxT7F2X8qqRt1MQaia9U8zUAr3MvADcWBxmBYmhtcRTfgLwtlAP2NuqIjEqKcLrTcH2gri5K+BTog8t5G5N2iseypTdxQvzE82rNWFRnro7sHf9N+bDpgCdY9/tvm0XYDNliA6LUYGgVAsGfP/N9PJyfMltwM2xbhYL/8lwq3vn4YQ4w3sfXauXv4r9BSMamPbF0EuymCR/69h66vMfKvm+38wliWsWteNa6FFgy+wKq11m9m9oZXSOdgQJ3z5LRvubPtW6Oz7DPzj/lwxoVFPcBox7bpkuzbN3ZwcDi06oNaoj4Dg4PDIZcFrq5mg8Fir/yQnbL0577FzZaqPdn6Nr6Tb47YL8fHT3BL9R1n3RCRHCV0HeZm+MUoSYOmz4EmLEPj2LaFT5LS2tqMsiwvJGnSwMcXeijRZrKuMhpRLZ+tX70YPh8+zwpqiQ9QSk3fDL0xZ+luIjfkkFduaEkrqAOvrcB77ricJGTJrb8TwitSy3QjLZWQ5qrKx/Ly1zaYHj5EU6VTrZYGNVmZJB0x3o+L+Ad8fS9dchGZzsgfTXqpRqq6Rv2jKQXbHqUVyKLUulJvks1R0u4j7n3Qyd3/LcCLRg==
