### ISSUE TITLE
[Bug Report] Button doesn't get click event when V-Bottom-Box is opened (none persistent) 

### ISSUE THREAD

**Issue by Vuetifiyer** [vuetifyjs/vuetify#11368]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
1. Click on the "Open-V-Model" Button. The Buttomsheet should open.
2. Click the button again. It's visible that the button is clicked (sheet is always set to true), but the Sheet is disappearing.

### Expected Behavior
The button click should trigger and the v-bottom-sheet should stay open (or reopen)

### Actual Behavior
The v-bottom-sheet is closing.

### Reproduction Link
<a href="https://codepen.io/NewVuetifier/pen/qBOKEmP?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fbottom-sheets%2F" target="_blank">https://codepen.io/NewVuetifier/pen/qBOKEmP?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fbottom-sheets%2F</a>

**Comment by KaelWD** [comment]
click-outside triggers after a `setTimeout(..., 0)`, so the button click is fired before the bottom sheet starts to close. You can work around this by opening it after a timeout too: `setTimeout(() => this.sheet = true, 0)`
