### ISSUE TITLE
[Bug Report] Clicking on the activator in v-select does not close it

### ISSUE THREAD

**Issue by Seanitzel** [vuetifyjs/vuetify#11360]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Create a  v-select component.
2. Click it.
3. Click it again.
4. It doesn't close.
5. Click the keyboard_arrow_down icon shown.
6. It does close.

### Expected Behavior
I want to have an option to allow closing the menu by clicking the activator when it is open, same as with v-menu.

### Actual Behavior
It closes only when clicking on the icon.

### Reproduction Link
<a href="https://codepen.io/Seanitzel/pen/MWaGKga?editors=1010" target="_blank">https://codepen.io/Seanitzel/pen/MWaGKga?editors=1010</a>

**Comment by vartiainen** [comment]
Why is this the intended way for v-select to work?

There's an easy CSS hack for this btw by adding a `.v-select__slot > .v-input__append-inner > .v-input__icon.v-input__icon--append:after` to catch the clicks.
