### ISSUE TITLE
[Bug Report] Textfields lose focus on tab with v-bottom-sheets and retain-focus=false

### ISSUE THREAD

**Issue by CurrentlyNoName** [vuetifyjs/vuetify#11369]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
1. Do some input in the first Textfield and press tab (the buttom-sheet should be opened, the focus should go to the second field)
2. Do the same for the second Textfield (this should work as weel)
3. Click on the first Textfield (the v-bottom-sheet should disappear)
4. Change the input and press tab (the v-bottom-sheet should appear, but the focus is lost)

### Expected Behavior
The focus should go to the second Textfield

### Actual Behavior
The focus is lost.

### Reproduction Link
<a href="https://codepen.io/NewVuetifier/pen/gOaKbeq?editors=1010" target="_blank">https://codepen.io/NewVuetifier/pen/gOaKbeq?editors=1010</a>

**Comment by johnleider** [comment]
Caused by https://github.com/vuetifyjs/vuetify/commit/700fd4289d21f83ba17373fd390bf6bb6b52326b @KaelWD

**Comment by MajesticPotatoe** [comment]
> Caused by [700fd42](https://github.com/vuetifyjs/vuetify/commit/700fd4289d21f83ba17373fd390bf6bb6b52326b) @KaelWD

To extend comment: This is a conflict between `hide-overlay` and `:retain-focus="false"`
the commit above does break `:retain-focus="false"` further in versions > 2.3.15

**Comment by johnleider** [comment]
This is a very specific issue and has not garnered a lot of attention.

This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
