### ISSUE TITLE
[Documentation] The List topic does not show anything when clicked

### ISSUE THREAD

**Issue by lenkrasinski** [vuetifyjs/vuetify#11362]
### Environment

**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.14.5

### Steps to reproduce
Click on Lists in left nav pane and nothing displays in the right side content area

### Expected Behavior
Some doc should show

### Actual Behavior
nothing shows

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/lists/#lists" target="_blank">https://vuetifyjs.com/en/components/lists/#lists</a>

**Comment by MajesticPotatoe** [comment]
Link seems to working as it should. Likely a cache issue. Clear your cache and try again.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
