### ISSUE TITLE
[Feature Request] VFileInput with multiple selection - add option to append files to current selection.

### ISSUE THREAD

**Issue by AtishaGarinMchd** [vuetifyjs/vuetify#11379]
### Problem to solve
FileInput allows through multiple prop to select multiple files. 

Using the `selection` slot we can show type, file size of selected files [as illustrated here on official docs](https://vuetifyjs.com/en/components/file-inputs/#complex-selection-slots). 
Using Chips, a user would be able to delete files individually.

**Main issue** is that selecting a file replaces previous selection. If user wants to select add another file, he would need to browse select previously selected files a second time. Plus, losing your own selection is suprising, and upsetting.

*As a side note*, any click happening within the slot (which is not prevented by the slot's contained component) would open system dialog, so the use of chips for indivual deletion may pop-out - and clear all previously selected items - on a 'missed click'. Perhaps is there a workaround for this ?

### Proposed solution
**Main issue** Please add a optional prop to append files to current selection instead of overwriting current selection.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VFileInput/VFileInput.ts#L256

*Side issue* solution would be an activator-like target for the system dialog to be opened ?

**Comment by nekosaur** [comment]
This is a limitation of the `<input>` element. We have plans for a separate component for this scenario. See https://github.com/vuetifyjs/vuetify/issues/8812
