### ISSUE TITLE
[Bug Report] The v-switch element does not display correctly if the dense property is set

### ISSUE THREAD

**Issue by savylovskij** [vuetifyjs/vuetify#11377]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 7

### Steps to reproduce
Hey. The v-switch element does not display correctly if the dense property is set. If there is no dense property, everything is displayed correctly

### Expected Behavior
The v-switch element is work

### Actual Behavior
The v-switch element does not display correctly if the dense property is set. If there is no dense property, everything is displayed correctly

### Reproduction Link
<a href="https://codepen.io/savylovskij/pen/abvGqXr?editors=1010" target="_blank">https://codepen.io/savylovskij/pen/abvGqXr?editors=1010</a>

**Comment by SuperDJ** [comment]
Does this work: https://github.com/vuetifyjs/vuetify/issues/11344?

**Comment by savylovskij** [comment]
Hey. Will this bug be fixed?

**Comment by johnleider** [comment]
The dense prop isn't implemented in switch, it's a consequence of extending **selectable** which extends **VInput**.
