### ISSUE TITLE
[Bug Report] v-autocomplete search breaks with dynamic item-text of multiple columns

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#11370]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Edge 81.0.416.72
**OS:** Windows 10

### Steps to reproduce
Create a autocomplete for a API and use 2 columns for the `item-text`. For example: 

     :item-text="item => `${item.Description} ${item.Category}`"

Or look at the reproduction link and check the console.

### Expected Behavior
Would expect that the `search` value is  complete `string`

### Actual Behavior
The `search` value is reset to `null` and each character is send individually.

### Reproduction Link
<a href="https://codepen.io/DJSuper/pen/XWmYJwe" target="_blank">https://codepen.io/DJSuper/pen/XWmYJwe</a>

**Comment by Mert75** [comment]
Consider using `<template v-slot:selection="data">` in your autocomplete

Example at https://vuetifyjs.com/en/components/autocompletes/#slots

**Comment by SuperDJ** [comment]
That would only solve a part of the problem where `:item-text="item => `${item.Description} ${item.Category}`"` definitely has advantages. Such as not needing to use 2 slots.

**Comment by Mert75** [comment]
Duplicate of #[1975](https://github.com/vuetifyjs/vuetify/issues/1975)

[Same solution](https://github.com/vuetifyjs/vuetify/issues/1975#issuecomment-333378559) was given to you as KaelWD

**Comment by Mert75** [comment]
I happened to make a [codepen ](https://codepen.io/itsyeah/pen/ZEWWgzK) as this is a frequently asked question

Hope this solves your problem @SuperDJ

**Comment by SuperDJ** [comment]
@Mert75 It doesn't because what you referenced will only change what is shown when selecting. With what I want it will change the shown data for both `v-slot:selection` and `v-slot:item`

**Comment by GiuseppeMobijay** [comment]
I fall in same issue.

When item-text is a function the display data works fine, but when input a search string by keyboard in the text field part v-autocomplete can't filter the items.

**Comment by johnleider** [comment]
@GiuseppeMobijay We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
