### ISSUE TITLE
[Feature Request] Set style for row and its expanded content (if expanded)

### ISSUE THREAD

**Issue by mauriziocalarese** [vuetifyjs/vuetify#11380]
### Problem to solve
Set a style if an item is expanded within a data table (row and expanded content).

### Proposed solution
It would be useful to have a prop for the expanded item, like "expanded-item-class".

The final result desired is attached.

![Annotazione 2020-05-12 194825](https://user-images.githubusercontent.com/22024408/81727642-99ccfd00-9489-11ea-8375-c9096ee3e158.jpg)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
