### ISSUE TITLE
[Bug Report] VExpansionPanel nor rendering properly in nuxt generate (spa+universal)

### ISSUE THREAD

**Issue by FelixRe0** [vuetifyjs/vuetify#11386]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0, Microsoft Edge, Internet Explorer, Opera, Other, Safari, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
- npm install
- npm run generate
- deploy dist or open dist/index.html

### Expected Behavior
v-expansion-panel redering properly
![expected](https://raw.githubusercontent.com/FelixRe0/-vuetify-nuxt-generate-expansion-panel-issue/master/expected.PNG?raw=true)

### Actual Behavior
Necessary css is not inlined
![generated](https://raw.githubusercontent.com/FelixRe0/-vuetify-nuxt-generate-expansion-panel-issue/master/result.PNG?raw=true)

### Reproduction Link
<a href="https://github.com/FelixRe0/-vuetify-nuxt-generate-expansion-panel-issue" target="_blank">https://github.com/FelixRe0/-vuetify-nuxt-generate-expansion-panel-issue</a>

### Other comments
Example images of the behaviour are provided in the repository.

**Comment by KaelWD** [comment]
Unable to reproduce. This seems like a build error anyway so doesn't belong here.

**Comment by FelixRe0** [comment]
> Unable to reproduce. This seems like a build error anyway so doesn't belong here.

True, it should be in the nuxt rep. Probably duplicate of: https://github.com/nuxt-community/vuetify-module/issues/208 or https://github.com/nuxt-community/vuetify-module/issues/232
