### ISSUE TITLE
[Bug Report] Unit testing - cannot mock breakpoints

### ISSUE THREAD

**Issue by ElVisPL** [vuetifyjs/vuetify#11388]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
I modified example from https://vuetifyjs.com/en/getting-started/unit-testing/#mocking-vuetify, just by adding `breakpoint` key

[EDIT] used this example after changes: 
https://github.com/vuetifyjs/vuetify/commit/d795b1e5106c6955cca8daad62b26178a3969986

And then in component
```
created() {
      console.log(this.$vuetify.breakpoint.smAndDown) // returns false
    }
```

### Expected Behavior
Vuetify breakpoints should be mocked

### Actual Behavior
Vuetify breakpoints are not mocked

### Reproduction Link
[https://github.com/ElVisPL/vuetify-unit-testing](https://github.com/ElVisPL/vuetify-unit-testing)

**Comment by ElVisPL** [comment]
Updated repo after this change:
https://github.com/vuetifyjs/vuetify/commit/d795b1e5106c6955cca8daad62b26178a3969986

still logs `false`

**Comment by Bastczuak** [comment]
@ElVisPL here you go! Found a way! But I'm not sure if it works with typescript!
```js
    const breakpoint = {
      init: jest.fn(),
      framework: {},
      smAndDown: true,
    }
    const vuetify = new Vuetify()
    vuetify.framework.breakpoint = breakpoint
    const wrapper = shallowMount(Component, {
      vuetify,
    })
```

**Comment by ElVisPL** [comment]
@Bastczuak 
Awesome, thanks!

**Comment by codestub** [comment]
the above did not work for me - however I did have luck with this

`global.innerWidth = 1200`
