### ISSUE TITLE
[Bug Report] Combobox chips overlap the label

### ISSUE THREAD

**Issue by parkaran** [vuetifyjs/vuetify#11395]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
It is already reproduced inside the codepen

### Expected Behavior
To have some sort of margin or padding between the label and the actual combobox content

### Actual Behavior
The combobox content overlaps the label

### Reproduction Link
<a href="https://codepen.io/Parkaran/pen/eYpjLGm" target="_blank">https://codepen.io/Parkaran/pen/eYpjLGm</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
