### ISSUE TITLE
v-btn background changes to grey

### ISSUE THREAD

**Issue by Zoterek** [vuetifyjs/vuetify#1139]
### Versions
Vue 2.3.3
Vuetify 0.14.5
Chrome 59.0.3071.115

### What is expected ?
Button background stays white

### What is actually happening ?
Background with 'to' attribute changes to grey

### Reproduction Link
```html
<v-btn flat @click="submit">Submit</v-btn>
<v-btn flat :to="href.cancel">Cancel</v-btn>
```
![capture](https://user-images.githubusercontent.com/17502624/28594229-82935ff0-718f-11e7-944e-80a9810a4e24.PNG)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
