### ISSUE TITLE
[Bug Report] v-lazy

### ISSUE THREAD

**Issue by viniciushvc** [vuetifyjs/vuetify#11398]
### Problem to solve
if i have many v-lazy in page, when a first v-lazy fire Observer, all v-lazy are fired

### Proposed solution
isolate v-lazy component

**Comment by jacekkarczmarczyk** [comment]
That sounds like a bug and requires reproduction

**Comment by viniciushvc** [comment]
https://codesandbox.io/s/vuetify-playground-00c6z?file=/src/layout.vue

**Comment by dewfall123** [comment]
This is becouse of the height of v-card is zero when it not intersected.

when we set the minHeight attr, it works. 
Reproduction here: [https://codesandbox.io/s/vuetify-playground-yrhwx?file=/src/layout.vue](https://codesandbox.io/s/vuetify-playground-yrhwx?file=/src/layout.vue)

Maybe the minHeight prop should be give a default value? or it should be required?

**Comment by KaelWD** [comment]
v-lazy doesn't render its content until it's visible, so it has no height. This is fine if you have more static content below it, but if you're stacking multiple v-lazy components you should define some sort of minimum height for them.
