### ISSUE TITLE
[Bug Report] JAWS reading toolbar as "Banner Region" 

### ISSUE THREAD

**Issue by flpehr0** [vuetifyjs/vuetify#11391]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
- Open JAWS 2018 / or NVDA (I tested with both with the same result)
- Tab or arrow into the toolbar 
- listen for the landmarks once focus has entered the toolbar

### Expected Behavior
- My understanding of the header element is that the screen reader should only read "banner landmark" if the header element is a direct descendant of body, which in this case, it is not.  

### Actual Behavior
- no matter what element it is placed in and how many there are added, it still reads as "Banner Landmark". I am not sure this is a desirable behavior for those using screen readers. 

### Reproduction Link
<a href="https://codepen.io/flpehr0/pen/xxwJWwM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftoolbars%2F" target="_blank">https://codepen.io/flpehr0/pen/xxwJWwM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftoolbars%2F</a>

### Other comments
I think it may be because tool bar is built from the same directive as nav bar and it is being rendered inside a header element which automatically comes with the role of banner. (if I am understanding correctly. )

I am not sure it is semantically correct to have more than one header element or more than one banner element unless it meets certain criteria. I wanted to start the conversation to see if there is a better way of doing this so as not to confuse users with screen readers

Proposed solutions:
- instead of rendering the toolbar inside of a header element perhaps render it inside of a div instead 
- Expose code to developers or add a prop that could help us override the aria roles in order to comply with accessibility standards  

Some sources for the proper usage of <header> and role="banner" that might bring clarity. 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role 
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header
- https://fae.disability.illinois.edu/rulesets/LANDMARK_5/

edited original for typos

**Comment by phiter-monetizze** [comment]
This happens because the [`header` element has the default role of `banner`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role).

![image](https://user-images.githubusercontent.com/56091403/81826770-7e580580-950e-11ea-87d0-e1acd52ca4d2.png)

The toolbar should probably be a `nav` element instead.

**Comment by flpehr0** [comment]
>This happens because the header element has the default role of banner.

To this deleted user's comment, yes that is correct! That is why I suggest the following 

>instead of rendering the toolbar inside of a header element perhaps render it inside of a div instead
