### ISSUE TITLE
[Bug Report] V-data-table slot item uppercase in attribute name not recognized

### ISSUE THREAD

**Issue by jdrivardSommets** [vuetifyjs/vuetify#11396]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Firefox 76.0
**OS:** Windows 10

### Steps to reproduce
Use the Code pen from Customizing default row of the doc :  https://vuetifyjs.com/en/components/data-tables/#api.
Modify all of the reference concerning "calories" attribute for "cAlories" and the slot isn't working anymore.

### Expected Behavior
The v-slot can be use with an attribute containing some upperCase.

### Actual Behavior
The v-slot cannot be bind to an attribute with upperCase.

### Reproduction Link
<a href="https://codepen.io/jdrivard/pen/OJywBwP?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F" target="_blank">https://codepen.io/jdrivard/pen/OJywBwP?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue/issues/9528

https://codepen.io/jkarczm/pen/GRpBYwK
