### ISSUE TITLE
[Feature Request] Prevent icons from changing on stepper with a prop

### ISSUE THREAD

**Issue by siba2893** [vuetifyjs/vuetify#11393]
### Problem to solve
On my website I use the stepper as a data divider but in most cases I don't want the step number to be switched to a check mark or edit icon, but just keep the number. 

### Proposed solution
Add a prop to prevent this from happening like: keep-steps
And this will always ensure the numbers don't get replaced by icons.

**Comment by d3radicated** [comment]
Omitting the `complete` and `editable` props retains the step numbers.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
