### ISSUE TITLE
[Bug Report] Image content overflowing vertical v-tab-item

### ISSUE THREAD

**Issue by anzuj** [vuetifyjs/vuetify#11397]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
* Create vertical `v-tabs` as shown [here](https://vuetifyjs.com/en/components/tabs/#vertical-tabs)
* Create a basic grid including `<v-img>` inside `v-tab-item`'s `v-card`
* Resize window to narrow width

### Expected Behavior
Content within `v-tab-item` is responsive and reduces its width to remain in viewport

### Actual Behavior
Content in `v-tab-item` overflows and gets clipped on the right side

### Reproduction Link
<a href="https://codepen.io/anzuj/pen/yLYqZQX" target="_blank">https://codepen.io/anzuj/pen/yLYqZQX</a>

### Comments
Responsive behaviour seems to disappear as soon as you include image content in `v-tab-item`

**Comment by itsgifnotjiff** [comment]
If you wrap an <img> in <v-col> in <v-row> it fixes this problem.

**Comment by anzuj** [comment]
> If you wrap an  in in it fixes this problem.

@itsgifnotjiff could you please explain this a bit? I'm not quite understanding what you meant here

**Comment by itsgifnotjiff** [comment]
Instead of using v-cards and in the v card using v-img which eliminated responsivness for me I used a v-card with a v-container with v-rows and and v-col in which I used the vanilla HTML tag <img>.

`<v-container>
      <v-row>
              <v-col>
                <img width="100%" src="">
              </v-col>
              <v-col>
                <img width="100%" src="">
              </v-col>
            </v-row>
            <v-row>
              <v-col>
                <img width="100%" src="">
              </v-col>
              <v-col>
                <img width="100%" src="">
              </v-col>
            </v-row>
          </v-container>`

**Comment by jakeflorentine** [comment]
I'm also seeing this issue: using vertical v-tabs, with large tables being displayed on the right hand side (within my v-tab-item)

**Comment by johnleider** [comment]
This was resolved with https://github.com/vuetifyjs/vuetify/pull/11983 and is available as of [v2.3.19](https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.19)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
