### ISSUE TITLE
[Feature Request] [Navigation Drawers] source code method init should be called in created

### ISSUE THREAD

**Issue by lihxhit** [vuetifyjs/vuetify#11404]
### Problem to solve
Use vuetify with Nuxt,
i need a visible drawer after SSR(server side render),but the NavigationDrawer active state is false by default until beforeMount,so we get translateX(-100%) in server side and translateX(0) in client side after beforeMount

### Proposed solution
init method maybe should be called in created

**Comment by jacekkarczmarczyk** [comment]
Please provide the reproduction of the problem

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
