### ISSUE TITLE
Add 'contain' as an option for carousal images.

### ISSUE THREAD

**Issue by mydogisbox** [vuetifyjs/vuetify#1140]
In a carousal, I have a number of images to display which have varying aspect ratios.  A number of the images are unappealing when using "Cover" instead of "contain" since important parts of the image are hidden in order to have the image cover.

It would be nice to have an option which doesn't hide any part of the images.

**Comment by johnleider** [comment]
This is an easy addition, but it does seem like it would need to also give you some additional control as a contained image looks offset within the current setup.
