### ISSUE TITLE
[Bug Report] drag-and-drop of v-slider dosen't work on Firefox for Android

### ISSUE THREAD

**Issue by skitourenguru** [vuetifyjs/vuetify#11409]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox
**OS:** Android

### Steps to reproduce
The slider (v-silder of vuetify) can't be moved with drag-and-drop. You can test that with the sliders under these link:
https://vuetifyjs.com/en/components/sliders/
https://codepen.io/coolibre/pen/WNvBMMq

Browsers:
- Firefox on Android 68.8.0 (newest version) it doesn't work.
- Firefox on Desktop 76.0.1 all works fine.
- Chrome, Opera, Safari on all devices the sliders work fine.

### Expected Behavior
The slider can't be moved with drag-and-drop. The slider can only be moved with clicks. That is a problem for range-sliders, because it moves randomly one end of the sliders. You can't select the end you want to move!

### Actual Behavior
The circle stays at the same place

### Reproduction Link
<a href="https://codepen.io/coolibre/pen/WNvBMMq" target="_blank">https://codepen.io/coolibre/pen/WNvBMMq</a>

**Comment by nekosaur** [comment]
With only Firefox on Android being broken, it could be a browser bug. We don't do anything too strange in v-slider, and we're listening on both touch and mouse events..

Also as a side-note. It is not random which thumb gets moved when clicking v-range-slider. It is whichever thumb is closest to where you clicked.

**Comment by skitourenguru** [comment]
We created a bugzilla bug issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1637908
Suppose Mozilla will say its a vuetify problem.

About your side remark: Its then a random result, if you click in the middle of the slider. Would be nice, if you could choose either of the end by first clicking on one of the ends.

**Comment by KaelWD** [comment]
This was fixed in firefox 83
