### ISSUE TITLE
[Bug Report] Dynamically updating v-list-item-group's v-list-items causes group's selected v-model value to diverge from actual selection

### ISSUE THREAD

**Issue by wallslide** [vuetifyjs/vuetify#11405]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
1. Toggle the "Hide archived messages" switch off. 

a new item at the top of the list will appear

2. Click any item

a new message appears below the list that shows which item the selection is pointing to, which differs from the actual selected item.

### Expected Behavior
The selection value (representing the index of the v-list-item being selected) should sync up with the item being clicked and visually shown as selected. This works if the switch is toggled on.

### Actual Behavior
When v-list-items are generated with v-for in a v-list-item-group, and the array of items which is backing the v-for has items added to the beginning of the array, the v-list-item-group's v-model selection index gets out of sync with the actual selected item.

### Reproduction Link
<a href="https://codesandbox.io/s/dynamic-item-groups-issue-3cjmk" target="_blank">https://codesandbox.io/s/dynamic-item-groups-issue-3cjmk</a>

**Comment by myleshk** [comment]
Same problem

**Comment by abel-tefera** [comment]
Got the same issue...please fix

**Comment by carlmrichter** [comment]
Same issue here:
```vue
<v-list-item-group
    class="side-navigation__list-item-group"
    :value="value"
    @change="v => $emit('change', v)"
>
    <v-list-item
        v-for="item in items"
        :key="item.hash"
        :to="`#${item.hash}`"
        class="side-navigation__list-item"
        :class="{ 'is-active': item.hash === items[value].hash }"
    >
        <!-- ... -->
    </v-list-item>
</v-list-item-group>
```
Got it to work for me with setting the `is-active` class manually and overwrite the vuetify styles for the active item.

**Comment by filonik** [comment]
Same problem, rather annoying.

**Comment by Mert75** [comment]
@johnleider occurs on latest version (v2.3.8)

**Comment by mustard123** [comment]
same problem, what to do in the meantime?

**Comment by delbertlegg** [comment]
Also found same issue when the order of the items change. Items in the list retain their original "selected" index value even if it doesn't reflect actual order in list.

**Comment by dzlabs** [comment]
Same issue

**Comment by userbig** [comment]
Have the same issue when append or delete entries to\from the list. Also when I add data -> all selected items disappear. Sad!

**Comment by sjc311** [comment]
Also experiencing this issue or a similar one. 
v-list-item-group v-model variable is emptied/reset when the v-list-item list is changed out. 
Weirdly I thought it was working all well and dandy at first, it was only until I did a production build that this showed its face.

**Comment by yojahny55** [comment]
I used an Set object instead of array on v-model and works for me.

**Comment by ranyuhan** [comment]
<v-list-item-group
            active-class="yellow--text"
            :value="selected"
            >
              <v-list-item
                v-for="(office, index) in offices"
                v-bind:key="index"
                 @change="changeSelected(index)"
              >


  methods: {
    changeSelected(index) {
      this.selected = index
      this.$emit('change', this.selected);
    },


above solution works for me

**Comment by Xinrea** [comment]
Same problem with lastest version v2.5.8.
I need to operate on multiple-select v-list-item-group, and i figured out that forcing the v-list-item-group update works for me. Basicly you need to change the key of this component after any dynamic change of v-list data.
```vue
<v-list-item-group
  :key="itemGroup"
  v-model="selectItem"
  multiple
>
```

```js
forceUpdate() {
  this.itemGroup += 1
}
```

**Comment by Yonier** [comment]
> Same problem with lastest version v2.5.8. I need to operate with multiple-select v-list-item-group, and i figured out that forcing the v-list-item-group update works for me. Basicly you need to change the key of this component after any dynamic change of v-list data.
> 
> ```
> <v-list-item-group
>   :key="itemGroup"
>   v-model="selectItems"
>   multiple
> >
> ```
> 
> ```js
> data () {
>   return {
>     itemGroup: 0,
>     selectItems: []
>   }
> }
> 
> forceUpdate() {
>   this.itemGroup += 1
> }
> ```

This solution is a little heavy for the Dom and slow... but this works ok for now.

**Comment by johnleider** [comment]
Isn't this resolved by manually adding a value to `v-list-item`? I don't doubt there is an issue here, but the example is very convoluted tbh. What are the specific reasons that you chose to handle model updates and item generation like this?
