### ISSUE TITLE
[Documentation] action-with-title-and-sub-title example uses v-model on the active value, triggering eslint error

### ISSUE THREAD

**Issue by Esurnir** [vuetifyjs/vuetify#11407]
### Environment

**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
Create a new vue project with eslint
copy the example code of action-with-title-and-sub-title into the project (remove the template tag, just add a settings section in your data and you should be good to go).

### Expected Behavior
The code will compile with no eslint error

### Actual Behavior
The lines with v-model will trigger vue/valid-v-model eslint error.
Because active can't be "set" by the checkbox, it can only receive a value from active not set it and have any effect, it's toggle that do the work. :input-value should be used in its stead.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/lists/#action-with-title-and-sub-title" target="_blank">https://vuetifyjs.com/en/components/lists/#action-with-title-and-sub-title</a>

**Comment by jacekkarczmarczyk** [comment]
Please provide runnable reproduction and exact error message

**Comment by Esurnir** [comment]
Repro case repo here : https://github.com/Esurnir/vuetify-doc-repro
To get the error message run npm run lint

The file VListRepro.vue is a copy and paste of the example code at https://vuetifyjs.com/en/components/lists/#action-with-title-and-sub-title

```
> vue-cli-service lint

error: 'v-model' directives cannot update the iteration variable 'active' itself (vue/valid-v-model) at src\components\VListRepro.vue:59:27:
  57 |           <template v-slot:default="{ active }">
  58 |             <v-list-item-action>
> 59 |               <v-checkbox v-model="active"></v-checkbox>
     |                           ^
  60 |             </v-list-item-action>
  61 | 
  62 |             <v-list-item-content>


error: 'v-model' directives cannot update the iteration variable 'active' itself (vue/valid-v-model) at src\components\VListRepro.vue:72:27:
  70 |           <template v-slot:default="{ active }">
  71 |             <v-list-item-action>
> 72 |               <v-checkbox v-model="active"></v-checkbox>
     |                           ^
  73 |             </v-list-item-action>
  74 |
  75 |             <v-list-item-content>


error: 'v-model' directives cannot update the iteration variable 'active' itself (vue/valid-v-model) at src\components\VListRepro.vue:85:27:
  83 |           <template v-slot:default="{ active }">
  84 |             <v-list-item-action>
> 85 |               <v-checkbox v-model="active"></v-checkbox>
     |                           ^
  86 |             </v-list-item-action>
  87 |
  88 |             <v-list-item-content>
```
To correct this all the `v-model` need to be replaced by `:input-value`
