### ISSUE TITLE
[Feature Request] Treeview get parent id when an item is activated

### ISSUE THREAD

**Issue by manikos** [vuetifyjs/vuetify#11418]
### Problem to solve
This question has been asked before ([Unable to get parent key #5661)](https://github.com/vuetifyjs/vuetify/issues/5661) but closed due to lack of information.

Things are simple. I have the following tree:

```html
<v-treeview
  activatable
  return-object
  v-model="selection"
  :open="open"
  :items="items"
  @update:active="markAsSelected"
>
```

I select an item. How to get it's direct parent? Not grand-parent. Just it's parent. Forgive me if this is a dump question. Do I miss something obvious here or I have to implement a recursive function in order to traverse the entire tree just to get the selected item's parent?

### Proposed solution
I would like somehow (via an event or a computed property) to know the parent id whenever I activate an item in the tree because (correct me if I'm wrong) the children do not know their parents, while the reverse is true (parents know their children).

**Comment by nekosaur** [comment]
Items do know their parents internally, but there's no good way of surfacing that at the moment.

Current solution is as you say for users to implement a simple function to find parent.

**Comment by manikos** [comment]
OK I see. Thank you for your response! If you like to close this issue, fine by me. Best regards :)

**Comment by bsataric** [comment]
> Items do know their parents internally, but there's no good way of surfacing that at the moment.
> 
> Current solution is as you say for users to implement a simple function to find parent.

What do you mean by simple function to find parent? Some example maybe? I don't think such function is simple, especially if we have same children node references across multiple parent nodes (if the tree is very big so we want to reuse same children objects in different parent nodes).
