### ISSUE TITLE
[Bug Report] Class has no effect on v-label

### ISSUE THREAD

**Issue by ligne13** [vuetifyjs/vuetify#11410]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
Add class attribute to `<v-label>`.

### Expected Behavior
Class should be added to the class list on the rendered element.

### Actual Behavior
Class is not added to the class list.

### Reproduction Link
<a href="https://codepen.io/ligne13/pen/VwvGaYX" target="_blank">https://codepen.io/ligne13/pen/VwvGaYX</a>

**Comment by jacekkarczmarczyk** [comment]
`v-label` is not a public component and shouldn't be used
