### ISSUE TITLE
[Documentation] Data Table Missing Example how to do row grouping with custom rows

### ISSUE THREAD

**Issue by mikebellcoder** [vuetifyjs/vuetify#11414]
### Problem to solve
The example of how to use row grouping is too shallow. It took me days to figure out how to correctly use Vuetify Data Table with Grouped Rows that are custom (ie using the group slot).

When using the group slot and having your HTML `tr` elements wrapped with a `tbody` element you end up with the table body only occupying the first cell in the UI.

### Proposed solution
The main issue was there is an inconsistency between how the body slot is used compared to the group slot for Data Table. When using the body slot, you must wrap your `tr` elements with a `tbody` element. But when you use the group slot, you must not wrap the `tr` elements with a `tbody` element. 

This might be a bug, that it is inconsistent, but simply removing the `tbody` element when using the group slot fixed the issue.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
