### ISSUE TITLE
[Feature Request] MD Spec - Higher elevation, lighter surface

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#11411]
### Problem to solve
The material design specification on dark themes states that as the elevation of a surface increases, the lightness of the surface should also increase.

Currently vuetify is not doing this meaning that it's not complying with the MD Spec. You can see this by changing the elevation of a card component in the vuetify docs.

### Proposed solution
When the theme is dark, and the elevation changes for the card, button, sheet, etc. the lightness of the surface should change as shown in the spec.

Please see the elevation section in https://material.io/design/color/dark-theme.html#properties

**Comment by MajesticPotatoe** [comment]
duplicate #10557

**Comment by MatthewAry** [comment]
I don't think the duplicate issue is the same.

**Comment by MajesticPotatoe** [comment]
its covered in it and believe john mentions we will not be able to accommodate it
![12312312313](https://user-images.githubusercontent.com/27827979/81951369-13bccd80-95d3-11ea-9749-f57fada6bfda.png)

**Comment by MatthewAry** [comment]
Ah, NM. Seems it's a meta issue.
