### ISSUE TITLE
[Bug Report] v-autocomplete: divider and header can be found by typing [object Object]

### ISSUE THREAD

**Issue by azeezy** [vuetifyjs/vuetify#11415]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.15

### Steps to reproduce
Type [object Object] into the v-autocomplete field

### Expected Behavior
Does not show any results

### Actual Behavior
Show headers and dividers

### Reproduction Link
<a href="https://codepen.io/az33zy/details/rNOZKQz" target="_blank">https://codepen.io/az33zy/details/rNOZKQz</a>

**Comment by johnleider** [comment]
fixed in f8068ed
