### ISSUE TITLE
[Bug Report] Data table with custom sort and switches toggles wrong values

### ISSUE THREAD

**Issue by keeganwitt** [vuetifyjs/vuetify#11412]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows, Mac OSX

### Steps to reproduce
1. Set up a data table that has switches on one of the data values, and make it sortable.
2. Sort by the column with the boolean.
3. Toggle a value.

### Expected Behavior
Only the value toggled changes.

### Actual Behavior
Multiple values get toggled.

### Reproduction Link
<a href="https://codepen.io/keeganwitt/pen/LYpJzVz" target="_blank">https://codepen.io/keeganwitt/pen/LYpJzVz</a>

**Comment by keeganwitt** [comment]
This might be related to #10924, #3468, #7149.

**Comment by jacekkarczmarczyk** [comment]
You need item-key, for example `:item-key="name"`

**Comment by keeganwitt** [comment]
I added `item-key="name"` and it's still happening (codepen updated).

I also should add this happens with default sort in addition to my custom sort function.

**Comment by jacekkarczmarczyk** [comment]
Right, maybe I didn't sort the column after editing codepen

Works with `:key="item.name"` or `v-switch`: https://codepen.io/jkarczm/pen/eYpLGRg

**Comment by jacekkarczmarczyk** [comment]
Update: I've just noticed that you're using `item` slot, that's why `item-key` didn't work. With `item` slot you should actually add `:key` to `<tr>`, not `<v-switch>`, and without slot it would look like:

https://codepen.io/jkarczm/pen/NWGLawW

**Comment by keeganwitt** [comment]
Got it. Thank you!

**Comment by keeganwitt** [comment]
Do you have any recommended reading about how the different slots in Vuetify affect what key is needed?

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/list.html#Maintaining-State

any components displayed in the list (table rows, data iterator items, breadcrumbs etc) need a `key`
