### ISSUE TITLE
[Bug Report] Elevation Doesn't Work With v-menu

### ISSUE THREAD

**Issue by D3vin-huds0n** [vuetifyjs/vuetify#11428]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 3.0.0-beta.13
**Browsers:** Firefox 76.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
According to the elevation docs, they're supposed to work with any element but as shown, they don't work with v-menus. I observed that a wrapper div[role="menu"] is created after DOM is loaded which might be the issue why the style is not applied.

### Expected Behavior
After adding elevation class or prop it should've given elevation styles.

### Actual Behavior
Tried to add elevation to anything inside the v-menu, nothing seemed to work. So currently I'm using static <style></style> with a custom box-shadow to make the desired behavior.

### Reproduction Link
<a href="https://codepen.io/d3vin11/pen/YzyRwjG?editors=1010" target="_blank">https://codepen.io/d3vin11/pen/YzyRwjG?editors=1010</a>

**Comment by nekosaur** [comment]
Use `content-class` prop. https://codepen.io/nekosaur/pen/yLYQVVm?editors=1010
