### ISSUE TITLE
[Bug Report] Vuetify scroll-target for app-bar is not compatible with v-content or any other tags other than v-sheets.

### ISSUE THREAD

**Issue by MiKr13** [vuetifyjs/vuetify#11420]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Firefox 76.0, Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Just scroll and it won't work

### Expected Behavior
The app-bar should elevate & collapse

### Actual Behavior
The app-bar is hiding.

### Reproduction Link
<a href="https://codepen.io/MiKr13/pen/GRpYYZd" target="_blank">https://codepen.io/MiKr13/pen/GRpYYZd</a>

**Comment by alok722** [comment]
Even I am facing this issue, looking for a worj around

**Comment by MiKr13** [comment]
How is this working without scroll target? https://codepen.io/andrewspy/pen/bGbMJWo

**Comment by KaelWD** [comment]
Both of those codepens are scrolling on the body, not v-content. You need to hide overflow on `html` and set a fixed height on v-content for it to fire scroll events. v-content does not have a `max-height` prop.

**Comment by MiKr13** [comment]
@KaelWD But why do we need to hide normal overflow? In that case firefox shows 2 overflows sometimes one of which remains unusable. This is not a appropriate solution.
