### ISSUE TITLE
[Feature Request] v-menu should provide information on whether the menu is overflowing or not

### ISSUE THREAD

**Issue by yevgeniaronov** [vuetifyjs/vuetify#11429]
### Problem to solve
as of right now, i use patch-package in order to change the calcTop logic for the menu component.
i check if the menu is overflowing and then i add different 'top' to the element accordingly.
this is bad for me because it makes it very hard for me to upgrade vuetify version and also it's just extra code for something i think should be a native solution.

in the solution below, i use the isOverflowed value to decide whether to make the menu go above or below the activator

### Proposed solution
```
<template>
  <v-menu>
    <template v-slot:activator="{ on, isOverflowed }">
      <v-select
        v-model="field.value"
        :items="items"
        :menu-props="{
            top: isOverflowed,
            closeOnClick: true
          }"
        @click="onSelectClick"
        :error-messages="errors"
        type="select"
        item-text="text"
        item-value="value"
        :label="field.label"
        :name="field.fieldName"
        :data-automation="field.fieldName"
        autocomplete="off"
        v-on="on"
      ></v-select>
    </template>
  </v-menu>
</template>```

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by johnleider** [comment]
Menu is going to be doused with kerosene and lit on fire for v3 but there are currently no plans to expand on this particular request.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
