### ISSUE TITLE
[Feature Request] Allow autocomplete naming per form field

### ISSUE THREAD

**Issue by lehmat** [vuetifyjs/vuetify#11432]
### Problem to solve
HTML autocomplete attribute on form elements is not supported or is missing from documentation.

### Proposed solution
Add prop to form fields to be able to pass name for autocomplete. This helps developers to develop forms that are filled multiple times per session and does not require end users to type them manually every time.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
