### ISSUE TITLE
[Documentation] Add slot label in v-radio-group

### ISSUE THREAD

**Issue by Giildo** [vuetifyjs/vuetify#11438]
### Environment

**Browsers:** Chrome 81.0.4044.138
**OS:** Linux

### Steps to reproduce
In API description for "Selection controls" go to "v-radio-group" and go to "slot" tab.

### Expected Behavior
The description of the slot "label".

### Actual Behavior
There is no slot "label" in the list.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/selection-controls/#label-slot" target="_blank">https://vuetifyjs.com/en/components/selection-controls/#label-slot</a>

**Comment by MatthewAry** [comment]
It seems that documentation for the label slot is missing in other VInput based components. Other components affected include:

- VInput
- VSlider
- VRadioGroup
