### ISSUE TITLE
[Feature Request] Possible to support VueJS Vite?

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#11439]
### Problem to solve
Make the components more modular, rely less on webpack and other bundlers and use ES modules instead

### Proposed solution
Understand that this may actually end up becoming a major rewrite. So this is just a a note rather than a request.

Something I have been looking at is this... https://github.com/material-components/material-components-web-components.

**Comment by DRoet** [comment]
Idk Vite is still in early stages, it would be interesting to see if it will get pulled into `vue-cli` or if they remain two seperate projects

**Comment by ais-one** [comment]
My guess is most likely to be separate, vue-cli is dependent on webpack
right?



*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by robrich** [comment]
Vite only supports Vue 3+. See also https://github.com/vuetifyjs/vuetify/issues/11346

**Comment by KaelWD** [comment]
Vue 3 support is in progress on the `next` branch. Vite also requires es modules: #7927

**Comment by kostia7alania** [comment]
Vite supports Vue 2 .
