### ISSUE TITLE
[Feature Request] Add slot for selection area (selections) in select/autocomplete/combobox

### ISSUE THREAD

**Issue by Amndeep7** [vuetifyjs/vuetify#11434]
#### Use case
If you have a large number of selected items, then a large amount of space is taken up vertically.  See [here](https://codepen.io/amndeep7/pen/GRpwQzY) for a codepen that illustrates this problem.  

#### What this feature would solve
If there were a slot for that selection area, then I could put all the chips in a scrollable div instead of just having to deal with the default implementation.

#### End user benefits
Giving the programmer more ways to modify how a component is styled allows them to personalize the component for their usecase.  In mine, I expect my user to select a large number of options from an even larger list of potential options.

### Proposed solution
A slot is created and made accessible for the select/autocomplete/combobox family of components.  It could be called 'selections' or 'selection-area'.

**Comment by johnleider** [comment]
https://vuetifyjs.com/en/components/selects/#selection is the closest we will get to this at the current time.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
