### ISSUE TITLE
[Bug Report] Cypress click() inconsistent results with Vuetify buttons

### ISSUE THREAD

**Issue by ivelin** [vuetifyjs/vuetify#11436]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.5.16
**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.15.4

### Steps to reproduce
All context available on a related Cypress ticket:
https://github.com/cypress-io/cypress/issues/7404

### Expected Behavior
see link above

### Actual Behavior
see link above

### Reproduction Link
<a href="https://github.com/cypress-io/cypress/issues/7404" target="_blank">https://github.com/cypress-io/cypress/issues/7404</a>

**Comment by ivelin** [comment]
Related to cypress-io/cypress/issues/7404

**Comment by KaelWD** [comment]
This is probably caused by the fact that your drawer starts open, even on narrow windows: <https://github.com/ambianic/ambianic-ui/blob/77e5b54ea12cacf6695f2edc629dea9601a43992/src/components/NavBar.vue#L164>

Initialise it as `null` instead to start closed on smaller screens.

**Comment by ivelin** [comment]
> This is probably caused by the fact that your drawer starts open, even on narrow windows: https://github.com/ambianic/ambianic-ui/blob/77e5b54ea12cacf6695f2edc629dea9601a43992/src/components/NavBar.vue#L164
> 
> Initialise it as `null` instead to start closed on smaller screens.

@KaelWD thank you for the suggestion. Will try that.
