### ISSUE TITLE
[Bug Report] [Vue warn]: Invalid prop: custom validator check failed for prop "justifyMd".

### ISSUE THREAD

**Issue by annymosse** [vuetifyjs/vuetify#11444]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Linux x86_64

### Steps to reproduce
just add the `justify-md` attrib to `VRow` then that will produce it , the rest didn't produce it `justify-[lg,xl,sm]`

### Expected Behavior
expect no err

### Actual Behavior
doesn't work

### Reproduction Link
<a href="https://codepen.io/annymosse/pen/oNjJNLq?editors=1011" target="_blank">https://codepen.io/annymosse/pen/oNjJNLq?editors=1011</a>

**Comment by ElijahKotyluk** [comment]
`justify-md` accepts the following values:  `start`, `center`, `end`, `space-between` and `space-around`. You may reference the [Grid System](https://vuetifyjs.com/en/components/grids/) documentation.

**Comment by annymosse** [comment]
@ElijahKotyluk alright i have missed this point
