### ISSUE TITLE
[Bug Report] cannot custom page of table when fetch data from server

### ISSUE THREAD

**Issue by Chellhooo** [vuetifyjs/vuetify#11441]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. set page 2
2. fetch data with promise

### Expected Behavior
display the second page in the table

### Actual Behavior
display the first page in the table

### Reproduction Link
<a href="https://codepen.io/chellhoo/pen/gOaQJRe?editors=1011" target="_blank">https://codepen.io/chellhoo/pen/gOaQJRe?editors=1011</a>

**Comment by d3radicated** [comment]
One things to note is that you have to use `server-items-length` for [server-side pagination](https://vuetifyjs.com/en/components/data-tables/#paginate-and-sort-server-side).

**Comment by Chellhooo** [comment]
Thanks for help. But I want to fetch all data asynchronously once, and if I set `server-items-length`, table may display all data on each page. You can see it through https://codepen.io/chellhoo/pen/VwvNYdq

**Comment by d3radicated** [comment]
As a temporary work around, you can set the page after the data is fetched.
https://codepen.io/dEradicated/pen/dyYLPxL

**Comment by nekosaur** [comment]
Yeah I'm not sure I see a problem here. Quite naturally you can't set page to 2 when there are no items to show, so it sets is back to 1. Then when items are async loaded it will of course stay on page 1.

**Comment by Chellhooo** [comment]
umm. I think `options` or `page` seem like the default value of table, and table will jump to specific page, just for me, i guess it may make more sense?

**Comment by Chellhooo** [comment]
@d3radicated  Thanks very much. It works~

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
