### ISSUE TITLE
[Bug Report] Even empty pages are scrollable by height of appbar on android.

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#11452]
## Environment
Vuetify Version: 2.2.28
Vue Version: 2.6.11
Browsers: Google Chrome
OS: Android

## Steps to reproduce
Google Chrome Android: 81.0.4044.138

Use Android with Google Chrome
Open: https://vuetifyjs.com/en/getting-started/pre-made-layouts/
Although the page has no content and is empty, you can scroll up and down a little bit.
Expected Behavior
Pages that do not exceed the height of the screen, should not be scrollable.
And Footer and Bottom Navigation should be immediatly visible.

## Actual Behavior
Even empty pages are scrollable a little bit.
This hides footers and bottom-navigation, user needs to scroll to get to them.

## Reproduction Link
https://vuetifyjs.com/en/getting-started/pre-made-layouts/

Other comments
This is due to v-app application wrap css: min-height: 100vh.
Should be minus height of app-bar     min-height: calc(100vh - 56px); on mobile.

**Comment by mediafreakch** [comment]
[The workaround](https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/) seems to be to do the following:

```
body {
  min-height: 100vh;
  /* mobile viewport bug fix */
  min-height: -webkit-fill-available;
}

html {
  height: -webkit-fill-available;
}
```

I tried that plus overwriting `.v-application-wrap` to the following, with no success.
It got worse because the whole application container collapsed to 88px in height...

```
::v-deep .v-application--wrap {
    min-height: 100vh;
    /* mobile viewport bug fix */
    min-height: -webkit-fill-available;
  }
```

**Comment by mediafreakch** [comment]
After some trying, this fixed the problem for me:

```
// applied in my App.vue (root component)
<style>
html, body, .v-application, .v-application--wrap {
    min-height: -webkit-fill-available;
  }
</style>
```

Meaning that every node upwards from `v.application--wrap` until and including `body` and `html` need a specific `min-height` set. The value being `-webkit-fill-available` as explained in the article I shared in my previous post.

**Comment by OneSeven** [comment]
> 经过一番尝试，这为我解决了问题：
> 
> ```
> // applied in my App.vue (root component)
> <style>
> html, body, .v-application, .v-application--wrap {
>     min-height: -webkit-fill-available;
>   }
> </style>
> ```
> 
> 这意味着从每个节点向上`v.application--wrap`，直到并包括`body`与`html`需要特定的`min-height`一套。该值`-webkit-fill-available`如我在上一篇文章中分享的文章中所解释。

This can cause many problems. For example, v-select cannot be closed when clicking outside the v-app area, and there may be other types of problems。
Should not rely on vh units, should look for other solutions

**Comment by OneSeven** [comment]
> After some trying, this fixed the problem for me:
> 
> ```
> // applied in my App.vue (root component)
> <style>
> html, body, .v-application, .v-application--wrap {
>     min-height: -webkit-fill-available;
>   }
> </style>
> ```
> 
> Meaning that every node upwards from `v.application--wrap` until and including `body` and `html` need a specific `min-height` set. The value being `-webkit-fill-available` as explained in the article I shared in my previous post.

This can cause many problems. For example, v-select cannot be closed when clicking outside the v-app area, and there may be other types of problems。
Should not rely on vh units, should look for other solutions

**Comment by dora-gt** [comment]
@johnleider 
This is really annoying bug. Please consider prioritize this.

**Comment by OscarOGarcia** [comment]
I solved the spacing as follows in the App.vue file

```
<style>
div > .v-application--wrap {
  min-height: 100%;
}
<style>
```

**Comment by KaelWD** [comment]
This isn't really fixable generically. You need `min-height: 100%` on every element above v-app so the styles are different for each application. We should just add documentation on how to fix this.

**Comment by mediafreakch** [comment]
Since `vh` unit still cause problems on many mobile browsers these days, how about using a JS + CSS variables approach as described [here](https://www.markusantonwolf.com/en/articles/solution-to-the-mobile-viewport-height-issue-with-tailwind-css) to set the `min-height` for `.v-application--wrap`? (instead of `100vh`).

I'm now using a wrapper component in our project to overwrite the default `v-app` styles. 
This is **without** having to specify any `min-height: -webkit-fill-available` as written in an earlier post above.

```vue
<template>
  <v-app class="gp-full-height">
    <slot />
  </v-app>
</template>

<script lang="ts">
  import Vue from 'vue'
  import debounce from 'lodash/debounce'

  export default Vue.extend({
    name: 'FullHeight',
    methods: {
      setViewHeight() {
        const vh = window.innerHeight * 0.01
        document.documentElement.style.setProperty('--vh', `${vh}px`)
      },
    },
    mounted() {
      this.setViewHeight()

      const debouncedSetHeight = debounce(this.setViewHeight, 50)

      window.addEventListener('resize', debouncedSetHeight)

      this.$once('destroyed', () => {
        window.removeEventListener('resize', debouncedSetHeight)
      })
    },
  })
</script>

<style scoped lang="scss">
  /**
    Overwrite vuetify's default v-application--wrap min-height: 100vh;
    Due to the many problems with vh on mobile devices.
   */
  .gp-full-height ::v-deep .v-application--wrap {
    min-height: 100vh;
    min-height: calc(var(--vh, 100vh) * 100);
  }
</style>
```

I successfully tested this on Android Chrome, Android Firefox and iOS 14 Safari

**Comment by ceyhancode** [comment]
```
<style>
.v-application__wrap {
  min-height: 100dvh !important;
}
</style>
```
i fixed this problem

We have new viewport units lvh, svh and dvh to the rescue. This was demonstrated in the latest Google I/O 2022 video on web works.

You would probably want to stick with dvh for the browser to adapt to the mobile device's hidden tabs while scrolling. It works the similar way for width with dvw, lvw and svw units.

Here is a neat illustration from the video: [https://youtu.be/Xy9ZXRRgpLk?t=982](https://youtu.be/Xy9ZXRRgpLk?t=982)

**Comment by KaelWD** [comment]
Pretty bad browser support though still: https://caniuse.com/viewport-unit-variants

**Comment by KaelWD** [comment]
True, and I guess we can still define vh as well as a fallback. I'll have to check navigation drawers though I think they use it in an inline style.
