### ISSUE TITLE
[Bug Report] v-data-iterator sort bug

### ISSUE THREAD

**Issue by rilakkumars** [vuetifyjs/vuetify#11457]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1) set sort by Calcium 
2) type 0

### Expected Behavior
only items with Calcium = 0% are displayed

### Actual Behavior
Cupcake with Calcium = 3% is included

### Reproduction Link
<a href="https://codepen.io/rilakkumars/pen/KKdJoep?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-iterators%2F" target="_blank">https://codepen.io/rilakkumars/pen/KKdJoep?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-iterators%2F</a>

### Other comments
after some testing, I found it seems that v-data-iterator's filter logic search all values for each item, which basically nullifies the :sort-by props. In the above example, the reason why Cupcake is included is that its Calories is 305 which contains 0

**Comment by nekosaur** [comment]
This is not a bug. Sorting has nothing to do with filtering.

**Comment by rilakkumars** [comment]
Thank you for clarification.
