### ISSUE TITLE
[Bug Report] Pre-populate VListItemGroup with array of objects as value

### ISSUE THREAD

**Issue by hackerESQ** [vuetifyjs/vuetify#11466]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Edge 81.0.416.68, Google Chrome
**OS:** Mac OS 10.14.6

### Steps to reproduce
The VListItemGroup in the reproduction should be populated by the `internalValue` computed property. This computed property in turn gets set by the parent component's model called `selectedHeaders` property. However, as seen in the reproduction below, the list items (and checkboxes) are not pre-selected even though the `internalValue` is properly set.

Curiously, uncommenting the `internalValue` data property (and commenting out the `internalValue` computed property) will work and pre-select all the values. 

### Expected Behavior
The VListItemGroup should be pre-populated with the `selectedHeaders` array of objects.

### Actual Behavior
The VListItemGroup is not pre-populated with the computed property

### Reproduction Link
<a href="https://codesandbox.io/s/list-group-item-experiments-jf2vp?file=/src/components/ColumnSelector.vue" target="_blank">https://codesandbox.io/s/list-group-item-experiments-jf2vp?file=/src/components/ColumnSelector.vue</a>

### Other comments
1. The `internalValue` and `selectedHeaders` properties are an array of objects representing headers for a VDataTable and are fundamentally identical to the `headers` prop that does pre-populate the VListItemGroup. 

2. Clicking on any of the VListItems will reset the `internalValue` apparently because the VListItemGroup is not respecting the `internalValue`

**Comment by hackerESQ** [comment]
Initially reporting this in Discord, looks like others are seeing the [same bug ](https://discord.com/channels/340160225338195969/351121729164410882/713253612343787586)

**Comment by hackerESQ** [comment]
Reporting back from the discord thread. @Leespiker has come up with a [workaround](https://codesandbox.io/s/list-group-item-experiments-nj6ob?file=/src/components/ColumnSelector.vue) that seems to work well. 

Essentially use an internal value of the object for equality comparison because VListItemGroup does not appear to have the ability to compare equality of objects. 

I will keep this issue open since object equality would be a nice-to-have -- unless anyone from the core team disagrees.

**Comment by KaelWD** [comment]
You should either use primitives, do the comparison yourself, or make sure the initial selection is the same object instances: 

```js
const headers = [
  { text: "ID", value: "id", align: "left" },
  { text: "Name", value: "name" },
  { text: "Phone", value: "phone" },
  { text: "Email", value: "email" },
  { text: "Created By", value: "created_by.name" },
  { text: "Created At", value: "created_at" }
]

export default {
  data: () => ({
    headers,
    selectedHeaders: headers.filter(h => ['id', 'name', 'phone'].includes(h.value))
  })
}
```
