### ISSUE TITLE
[Feature Request] App width access for sections

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#11464]
### Problem to solve
A popular design trend includes using clip paths to create wavy or geometric section breaks that span the client. Likewise, full width svgs are sometimes used in conjunction with animation to create engaging splash pages (see https://rancher.com/). Currently the flex layout of `v-container` with nested `v-row` / `v-col` inside the `v-app` makes this essentially impossible (as the auto padding / gutters get in the way, especially if say you are doing this with nuxt)

### Proposed solution
Some sort of slot / component that allows you to set section clip paths / full width background svgs

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
