### ISSUE TITLE
[Bug Report] [VCalendar] event-more not show

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#11460]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.10
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
Add overlapping multi day events to calendar, open month view

### Expected Behavior
at 2019-01-15 should display the string '2 more'

### Actual Behavior
The event number is only counted for the first day of the start event, in the example it is the date 2019-01-14
week view:
![image](https://user-images.githubusercontent.com/19403977/82642035-764b4480-9c37-11ea-94cf-cd2540f72459.png)

month view:
![image](https://user-images.githubusercontent.com/19403977/82642092-92e77c80-9c37-11ea-809f-f30f866a2d84.png)

### Reproduction Link
<a href="https://codepen.io/de-tampham/pen/zYveJpa" target="_blank">https://codepen.io/de-tampham/pen/zYveJpa</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
