### ISSUE TITLE
[Bug Report] How to disable theme?

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#11462]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1, Google Chrome
**OS:** Mac OS 10.15.4

### Steps to reproduce
I took one of the v-card examples and tried to disable the light theme.
```
vuetify: new Vuetify({
    theme: {
      disable: true
    }
  })
```
Seems similar to https://github.com/vuetifyjs/vuetify/issues/8082

### Expected Behavior
I was expecting the theme--light class to not be applied to the card.

### Actual Behavior
The theme--light class was still applied.
```
.theme--light.v-list-item .v-list-item__action-text, .theme--light.v-list-item .v-list-item__subtitle {
color: rgba(0,0,0,.6);
}
```

I'd like the light theme removed so that it goes back to 0.87 opacity.

### Reproduction Link
<a href="https://codepen.io/funkyvisions/pen/RwWvdzE" target="_blank">https://codepen.io/funkyvisions/pen/RwWvdzE</a>

### Other comments
Am I missing how this is supposed to work?  How can I turn off the light theme so that it doesn't add opacity to card text that doesn't have a color or text--primary set?  Do I have to do this at a per component or element level?  I'd like to turn it off for everything.

**Comment by KaelWD** [comment]
`theme.disabled` only controls the dynamic theme system (primary/secondary/accent etc.) The light and dark themes are defined in css: https://vuetifyjs.com/en/customization/sass-variables

This is not intended to be disabled (try leaving out v-app and see how broken it looks) but you can customise the values in $material-light and $material-dark
