### ISSUE TITLE
Vuetify datatable's "rows per page" detail could not working

### ISSUE THREAD

**Issue by mertaksu** [vuetifyjs/vuetify#1147]
### Steps to reproduce

- Create data table, allow sorting and new pages for rows per page field
- Click rows per page dropdown 10,25,ALL fields
- Look at datatable items

### Versions
0.14.7

### What is expected ?
When click rows per page dropdown item 10 or others datatable items should be update

### What is actually happening ?
When click rows per page dropdown item 10 or others datatable items should not be update, Rows per page items could not trigger and change also sort by column could not update datatable. When change vuetify version to 0.12.0 it works as expected.

### Reproduction Link
https://codepen.io/anon/pen/xLGqEm

**Comment by ChavaSobreyra** [comment]
Vuetify 0.14.x is not compatible with Vue@2.2.x as you used in your example.

**Comment by nekosaur** [comment]
Just as @ChavaSobreyra said. You need to upgrade Vue to 2.4.x if you want to use Vuetify 0.14.x
