### ISSUE TITLE
[Bug Report] Vuetify stepper change event is not triggered when model updates in store

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#11472]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Firefox 76.0
**OS:** Ubuntu undefined

### Steps to reproduce
 You get access to the app in your browser.
On the home page you have a stepper synchronized with a store value, "category". The number of steps is the number of "phases" of the "category", so only one at the beginning.
On the left drawer you can "Add phase", and everytime you add a phase the stepper updates.

When you add several phases, all the phases appear correctly in the stepper and you can click on the stepper header to navigate between the phases. But when you click on the "Previous" and "Next" button, although the header seems to change (almost perfectly, apart the fact that the original step stays in blue and the "phase" value in the store updates (and the "Previous" and "Next" buttons appears correctly depending on the phase), the v-stepper-content doesn't change.

Let's say I'm on phase "2" and you click "Previous", the "phase" in the store will be set to "1" (which is good), the button "previous" will disappear (which is also good), but in the header the "2" will remain blue and the v-stepper-content will stay the 2nd one, and not the first.

When you click on the "Previous" and "Next" buttons, the "@change" event is not even triggered.

### Expected Behavior
The stepper content should change when you change the "numPhase" model value from store.

### Actual Behavior
The change of the value in the store doesn't update the model.

### Reproduction Link
<a href="https://codesandbox.io/s/dgl17" target="_blank">https://codesandbox.io/s/dgl17</a>
You can clone the repo: https://github.com/djcaesar9114/example_vue . Run "npm install" then "npm run serve" in the root folder.

**Comment by d3radicated** [comment]
It's indicated in the documents that the `change` event is only emitted when step is changed by user interaction.

**Comment by jacekkarczmarczyk** [comment]
Also `:v-model="numPhase"` is not a valid syntax
