### ISSUE TITLE
[Bug Report] v-select not showing text when "items" object has choices with the same "value"

### ISSUE THREAD

**Issue by des-albert** [vuetifyjs/vuetify#11473]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
Using an "items" object where the elements have the same value

### Expected Behavior
v-select should display all items 

### Actual Behavior
only the first item is displayed

### Reproduction Link
<a href="https://codepen.io/des-albert/pen/xxwBNQK" target="_blank">https://codepen.io/des-albert/pen/xxwBNQK</a>

### Other comments
It is reasonable to have multiple choices that result in the same value but the contrary situation of allowing multiple choices with the same text resulting in different values does not make sense.

**Comment by kevinmelo** [comment]
I think v-select use the item-value to differ the items. Like when you use v-for and try put same key on the element,

I think item-value must be unique, but item-text can repeat

**Comment by des-albert** [comment]
This comment prompted further investigation. 
In VSelect.ts, there is a function 'filterDuplicates' that removes duplicate values using a Map. The remainder of the code uses the value as the key for item lookup.

This is counterintuitive. The choice text should be unique, not the values. I have updated the codepen to demonstrate that it does not make sense to have multiple choices with the same text. In this code, there are 2 choices with the same text different values.

Changing the code to use unique text values like a relatively simple task.

**Comment by des-albert** [comment]
the following update to filterDuplicates solves the issue

    filterDuplicates(arr: any[]) {
      const uniqueText = new Map()
      for (let index = 0; index < arr.length; ++index) {
        const item = arr[index]
        const text = this.getText(item)

        !uniqueText.has(text) && uniqueText.set(text, item)
      }
      return Array.from(uniqueText.values())

**Comment by johnleider** [comment]
This is a definitely not a bug and is a potentially large breaking change. Our inputs are designed to operate as close to native as possible and as far as I'm aware, it's not possible to have a select or datalist that can have multiple selections with the same value, and I don't think that we should either.

Not to appeal to antiquity, but this has been also the behavior since it's inception and this is the first issue I've seen regarding it.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by des-albert** [comment]
HTML Select tags do not impose any restriction on duplicate values or text. 
As demonstrated in https://codepen.io/des-albert/pen/KKdLmgW   multiple selections can have the same value or the same text.  If you wish to comply with native behavior, duplicate values should be allowed.

Clearly, it makes no sense to have multiple list items with the same text but different values. That is the current behavior of v-select which is clearly incorrect. Although multiple list items resulting in the same value may be unusual, there is nothing 'wrong' about it.

Stating that this has always been the behavior could be applied to any bug report - this is not a valid reason for rejecting a bug report. Similarly, claiming that it this is first time it has been noticed does not mean that it is invalid.

Perhaps there are some deeper implications of making this change which are not apparent to the casual observer. I have made the change to my local version of the code and have not observed any issues.

Nevertheless, as owner of Vuetify, you undoubtedly have the mandate to do whatever you choose, irrespective of other opinions. This is clearly not a democracy and only an idealistic would expect to have the opportunity for further debate.

Vuetify is clearly a very impressive achievement and I congratulate you for your excellent work.
