### ISSUE TITLE
[Bug Report] Specifying multiple font family fails

### ISSUE THREAD

**Issue by dora-gt** [vuetifyjs/vuetify#11475]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
Specify multiple font families for defaultAssets. Then the query to fonts.googleapis.com fails like:

https://fonts.googleapis.com/css?family=Roboto,Noto%20Sans%20JP:100,300,400,500,700,900&display=swap

### Expected Behavior
Vuetify should concatenate multiple font families with the delimiter `|` and set CSS to appropriate expression like `font-family: 'a', 'b'`

Query should be like:
```
https://fonts.googleapis.com/css?family=Roboto|Noto+Sans+JP:100,300,400,500,700,900&display=swap
```

and CSS should be like: 
```
font-family: 'Roboto', 'Noto Sans JP'
```

### Actual Behavior
Vuetify wrongly concatenates font families with `,`

### Reproduction Link
<a href="https://gist.github.com/dora-gt/991eb84b2a6bdb1d1baa120ae6ad67c3" target="_blank">https://gist.github.com/dora-gt/991eb84b2a6bdb1d1baa120ae6ad67c3</a>

**Comment by jacekkarczmarczyk** [comment]
What is this reproduction? This file doesn't belong to vuetify

**Comment by dora-gt** [comment]
Oops it might be a bug of Nuxt.js. I'm sorry.

**Comment by jacekkarczmarczyk** [comment]
or rather https://github.com/nuxt-community/vuetify-module
