### ISSUE TITLE
Edit Dialog - Slow Typing Response

### ISSUE THREAD

**Issue by mduey** [vuetifyjs/vuetify#1148]
### Steps to reproduce
*Create a v-for with an input and a v-edit-dialog
*Feed it ~200 rows of data

    <v-app light>
            <main>
                <div v-for="(x,i) in mydata" :key="i">
                    <div>
                        <input v-model="x.address">
                    </div>
                    <v-edit-dialog
                        @open="x._city = x.city"
                        @cancel="x.city = x._city || x.city"
                        large
                        >
                        <div class="text-xs-right">{{ x.city }}</div>
                        
                        <div slot="input" class="mt-3 title">Update City</div>
                        <v-text-field
                            slot="input"
                            v-model="x.city"
                            single-line
                            >
                        </v-text-field>
                    </v-edit-dialog>
                </div>
            </main>
        </v-app>

### Versions
Used CLI Vuetifyjs/Webpack-Advanced (0.13.1)

### What is expected ?
Expect typing into the input or edit dialog to not be laggy.

### What is actually happening ?
When typing into either the input or the edit dialog input, the response is slow and laggy.  You type a character and it takes a second for it to appear.

If I remove the v-edit-dialog component, the input by itself responds normally.

If I reduce the number of records (down to 10 for example), the input and edit dialog get better.  As the record numbers are increased, the lag increases too.

**Comment by johnleider** [comment]
Please provide a reproduction link.

**Comment by mduey** [comment]
Sorry...I'm behind a firewall.

**Comment by mstaack** [comment]
@mduey  then create a fake list of data and feed it to your v-for within a codepen
https://codepen.io/johnjleider/pen/bgJOrX

the problem must be reproduced in an isolated environment to prevent false positives!

cheers max
