### ISSUE TITLE
[Bug Report] Blur event inproperly fired for v-select with prepend-item

### ISSUE THREAD

**Issue by mtwolak** [vuetifyjs/vuetify#11488]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Firefox 76.0
**OS:** Linux

### Steps to reproduce
npm run serve

### Expected Behavior
When clicked select-all position and dismissed menu, then blur event is fired.

### Actual Behavior
When clicked select all position, blur event is fired instantly (despite opened menu)
![blur-select-all](https://user-images.githubusercontent.com/17517685/82902451-c2f88d80-9f5f-11ea-9580-bf92554e11d4.gif)

Instead, for any other position it works correctly:
![blur-one-element](https://user-images.githubusercontent.com/17517685/82902438-bd9b4300-9f5f-11ea-803f-152b6cbac5cf.gif)

### Reproduction Link
<a href="https://github.com/mtwolak/v-select-blur" target="_blank">https://github.com/mtwolak/v-select-blur</a>

### Other comments
I copy&pasted solution with select-all from v-select docs. Seems that blur event is inproperly fired.
I tried to avoid this problem by catching event update:return-value. However this is emited by VMenu and I see no way of catching this event in VSelect component.

**Comment by Mert75** [comment]
Please consider using a codepen next time

[Reproduction link](https://codepen.io/itsyeah/pen/xxVZmwy?editors=1111)

**Comment by hugomostar** [comment]
I managed to bypass native Blur event and produce wanted behavior by adding dynamic watcher on `isMenuActive` field this way: 
```
mounted() {
	this.myDynamicWatcher = this.$watch(
	() => this.$refs['my-v-select-ref'].isMenuActive,
	(val) => {
	 console.log(val)
	})
}
```
If you want to disable the listener just call up referenced watcher this way:
```
destroyed() {
	this.myDynamicWatcher()
}
```

**Comment by KaelWD** [comment]
The default list items have `@mousedown.prevent` to avoid this: https://github.com/vuetifyjs/vuetify/blob/739048495a8e4768794bee2a8517acef9e33c1fd/packages/vuetify/src/components/VSelect/VSelectList.ts#L166-L169
