### ISSUE TITLE
[Bug Report] Number parsed to string in v-edit-dialog

### ISSUE THREAD

**Issue by sve-odoo** [vuetifyjs/vuetify#11494]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
This happens when using v-model.number in a v-edit-dialog in a data-table.

In the provided codepen, click on an item in the "Fat" column,
- If you input a number and hit "enter" it becomes a string
- If you input a number and click "save", it stays a number

### Expected Behavior
v-model.number should not be bypassed and the number should not become a string

### Actual Behavior
number becomes string despite v-model.number

### Reproduction Link
<a href="https://codepen.io/sebversailles/pen/abvrOJa?editors=1010" target="_blank">https://codepen.io/sebversailles/pen/abvrOJa?editors=1010</a>

**Comment by douglasg14b** [comment]
This behavior does not occur if the `.sync` modifier on `return-value` is removed. For one reason or another...
