### ISSUE TITLE
[Bug Report] Default slot variable `active` of v-list-item is incorrect

### ISSUE THREAD

**Issue by dora-gt** [vuetifyjs/vuetify#11499]
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
Set up `v-list` with `v-lit-item-group` and then add `v-list-item` with slot `default` of variable `active`. Then, active is rendered with `false` while one of `v-list-item`s is actually `active`. 

https://gyazo.com/8b66dda80a633d612945d772dd3076e4

If I click some of items, it becomes `active`.
https://gyazo.com/54d82059b9f93abc6b7c4ee1a76f7252

### Expected Behavior
`active` variable should be `true` from the beginning.

### Actual Behavior
`active` variable is `false` at first, if the user clicks one of items, it becomes `true`.

### Reproduction Link
<a href="https://codepen.io/dora-gt/pen/bGVyqRy" target="_blank">https://codepen.io/dora-gt/pen/bGVyqRy</a>

**Comment by dora-gt** [comment]
I can do workaround like:

```
<v-list-item-group v-model="selectedMenu">
```

```
const menuItems = [
      {
        icon: 'mdi-alpha-l-circle-outline',
        title: 'index',
        to: '/',
      },
      {
        icon: 'mdi-calendar-blank',
        title: 'a',
        to: '/a',
      },
      {
        icon: 'mdi-table-cog',
        title: 'b',
        to: '/b',
      },
      {
        icon: 'mdi-chart-bubble',
        title: 'c',
        to: '/c',
      },
    ];
    let selectedMenu = 0;
    for (const [index, value] of menuItems.entries()) {
      if (value.to === this.$router.currentRoute.path) selectedMenu = index;
    }
```

but it doesn't look smart.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by Guillaumedemoff** [comment]
I have the same issue here. The active class is set from the start but not the active variable of the list item.

I made a small example here: [https://codepen.io/guillaumedemoff/pen/QWdOEBa](url)
You can see there that the item **Home** has the active class and is in grey as intended but the active variable is still false.

The active variable is only set afterward when we click on an item.

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues.

Please create a new [issue](https://issues.vuetifyjs.com) showing the problem, or reach out to us in our [Discord community](https://community.vuetifyjs.com).
