### ISSUE TITLE
[Documentation] Add TypeScript examples

### ISSUE THREAD

**Issue by Nicklas2751** [vuetifyjs/vuetify#11496]
### Problem to solve
It's not that easy to convert your JavaScript examples to TypeScript.

### Proposed solution
Please add TypeScript examples.

### Example

I took the time and converted the `src/examples/calendars/complex/events.vue` to TypeScript: https://gist.github.com/Nicklas2751/da1fbe81878df7bb531fa4978c0ce7a8

Btw. is there a better way to get types for the things like `start`, `end` and `event`?

**Comment by ClickerMonkey** [comment]
Vuetify exports types that start with Calendar like CalendarTimestamp, CalendarEvent, etc.

https://github.com/vuetifyjs/vuetify/blob/80e9ba4f79c2cc761c540a4024f2c8602207ac8e/packages/vuetify/types/index.d.ts#L196
