### ISSUE TITLE
Navigation Drawer margin-top placing drawer slightly over toolbar

### ISSUE THREAD

**Issue by smtlk** [vuetifyjs/vuetify#1150]
Using the latest versions of Vue and Vuetify my navigation drawer seems to have a _margin-top_ applied to it by default which makes it sit slightly over the toolbar. 

This issue can be seen in the Vuetify docs on the "Modern YouTube" demo 
![screen shot 2017-07-27 at 13 23 14](https://user-images.githubusercontent.com/24596769/28670030-c93a4050-72ce-11e7-969c-220d683bc4da.png)

My browser size seems to be 1321x475 in case that's relevant due to the media queries being applied

**Comment by johnleider** [comment]
Forgot to update these when I updated the v-toolbar changes in height.
