### ISSUE TITLE
[Bug Report] $ripple-animation-visible-opacity ignored

### ISSUE THREAD

**Issue by melalj** [vuetifyjs/vuetify#11505]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.14.5

### Steps to reproduce
Adding "$ripple-animation-visible-opacity: 0.05" to the variable list

### Expected Behavior
To have a ripple with a visible opacity of 5% instead of the 15% default

My current workaround is to do:
```scss
.v-ripple__container {
  opacity: 0.5;
}
```

### Actual Behavior
Changing this variable doesn't affect the visibility of the ripple

### Reproduction Link
<a href="https://codepen.io/melalj/pen/pojmYoL" target="_blank">https://codepen.io/melalj/pen/pojmYoL</a>

### Other comments
On the source code there's no mention of the usage of the variable: $ripple-animation-visible-opacity ( https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/directives/ripple/VRipple.sass)

Am I missing something?

**Comment by daikiojm** [comment]
I also find the same behavior.
Indeed, `$ ripple-animation-visible-opacity` seems to be ignored.
The code that uses `$ ripple-animation-visible-opacity` seems to have been removed in the commit below.

https://github.com/vuetifyjs/vuetify/pull/5059/files

**Comment by johnleider** [comment]
This is because that variable is defined in 2 places. Originally added by @MajesticPotatoe in the global settings and then later added by me in the specific ripple settings. One can probably go.

![image](https://user-images.githubusercontent.com/9064066/123001309-37297e80-d376-11eb-82e3-c1cae8a98812.png)

**Comment by KareemDa** [comment]
@johnleider 
`$ripple-animation-visible-opacity` is never used. Also, opacity is calculated from ripple `index.ts` file, not from `VRipple.sass` 
![image](https://user-images.githubusercontent.com/42810389/139913005-4c3f5cdc-ad31-487a-b08e-3986c962a784.png)
