### ISSUE TITLE
[Bug Report] Clearable input icon selected highlight misaligned in IE 11

### ISSUE THREAD

**Issue by kakalaky** [vuetifyjs/vuetify#11508]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Use a clearable input. In this example I am using a v-text-field.
`<v-text-field clearable></v-textfield>`

**v-text-field with clearable icon selected in Chrome**
![image](https://user-images.githubusercontent.com/1250896/83069813-8351a480-a038-11ea-9cea-e2e2e2cba0af.png)

**v-text-field with clearable icon selected in IE 11**
![vuetify](https://user-images.githubusercontent.com/1250896/83069558-13dbb500-a038-11ea-95e7-cf79530d7054.png)

Any clearable input appears to reproduce the issue. Unable to use Codepen/JSFiddle because they don't support IE. This can be reproduced on https://vuetifyjs.com/en/components/text-fields in IE 11 by setting the playground field to clearable and tabbing to the clearable icon.

### Expected Behavior
Clearable icon should line up correctly when selected in IE 11.

### Actual Behavior
Clearable icon is misaligned when selected in IE 11.

### Other comments
My real preference would be for clearable icons to be changed back to having tabindex="-1" but based on #10680 that isn't going to happen.

**Comment by iMegABub** [comment]
This happens to every clickable icon which was appended to a v-text-field.
