### ISSUE TITLE
[Bug Report] Data Table Pagination Theme

### ISSUE THREAD

**Issue by aloiseau17** [vuetifyjs/vuetify#11512]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
Set v-data-table theme to dark then open pagination menu

### Expected Behavior
Pagination menu should take v-data-table explicit theme attribute.
Here is a discussion about it https://github.com/vuetifyjs/vuetify/discussions/11493

### Actual Behavior
Pagination menu is  still in light, it take root theme.

### Reproduction Link
<a href="https://codepen.io/Auremy/pen/dyYEPVm" target="_blank">https://codepen.io/Auremy/pen/dyYEPVm</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
