### ISSUE TITLE
[Feature Request] Show heading text rather than column name when grouping in data table

### ISSUE THREAD

**Issue by JohnM-oss** [vuetifyjs/vuetify#11516]
### Problem to solve
I have a v-data-table, and I have a column "real_user_name" which has the heading text "User Name". But when I group by real_user_name, it shows "real_user_name" as the group title instead of "User Name".

This is not the desired behaviour as I would rather it showed the display name of the column rather than the ugly underscore case column name.

### Proposed solution
Change the group by feature to show the display name of the column (as defined in 'text' property of 'headers').

**Comment by KaelWD** [comment]
This seems like a bug to me, I don't know why you'd want to see the underlying property name for groups like that.

**Comment by NicoAiko** [comment]
Sorry for the bump, but could this get more attention?

**Comment by KaelWD** [comment]
Workaround with the `group.header` slot: https://codepen.io/kaelwd/pen/OJvMOOr?editors=1010
