### ISSUE TITLE
[Bug Report] VBtn opacity sass variables

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#11514]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
When setting the following variables in the `/sass/variables.scss` file they won't work when the v-btn has the `text` prop

$btn-active-opacity: 0;
$btn-focus-opacity: 0;
$btn-hover-opacity: 0;

### Expected Behavior
the opacity's from the variables should be applied

### Actual Behavior
the opacity's from the variables are not applied

### Other comments
For some reason the vuetify code VBtn.sass intentionally not uses the sass variables
```
// Modifiers
.v-btn:not(.v-btn--text):not(.v-btn--outlined)
  &.v-btn--active:before
    opacity: $btn-active-opacity

  &:hover:before
    opacity: $btn-hover-opacity

  &:focus:before
    opacity: $btn-focus-opacity
```

**Comment by ricardovanlaarhoven** [comment]
I would love to create a PR for this, except i don't know if i can just remove the `:not(.v-btn--text):not(.v-btn--outlined)`

**Comment by KaelWD** [comment]
`text` and `outlined` buttons are transparent so use the `$material.states` values instead.

**Comment by ricardovanlaarhoven** [comment]
The what? is that a sass variable or?

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_light.scss#L74
