### ISSUE TITLE
[Bug Report] Wrong alignment of v-list-items in v-menu in IE 11

### ISSUE THREAD

**Issue by mathiasschopmans** [vuetifyjs/vuetify#11513]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer 11 (11.0.9600.19596)
**OS:** Windows

### Steps to reproduce
Click on the button labeled "Dropdown" in the component demo.

### Expected Behavior
Texts should align centered

### Actual Behavior
Text is aligned at top / no padding

<img width="154" alt="schopmans_screenshot 2020-05-28 um 09 25 01" src="https://user-images.githubusercontent.com/193253/83112092-edfcf180-a0c5-11ea-93c9-e5ae80d4e1a3.png">

### Reproduction Link
https://vuetifyjs.com/en/components/menus/#menus

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
