### ISSUE TITLE
[Feature Request] OnResize and breakpoint service object should co-operate together

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#11518]
### Problem to solve
On resize you need to know the new resized breakpoint rather than the *previous* breakpoint as it is now.

### Proposed solution
update breakpoint service object when onResize triggered *before* onResize invokes function so that the called method can know the new breakpoint

**Comment by KaelWD** [comment]
Breakpoint updates are debounced to 200ms for performance reasons. You can watch `$vuetify.breakpoint.width` instead if you want everything in sync.

**Comment by WhatFreshHellIsThis** [comment]
Ok, thank you; perhaps that should be documented?
