### ISSUE TITLE
[Documentation]  ja: The warning text of the button component is incorrect

### ISSUE THREAD

**Issue by suzu-prog** [vuetifyjs/vuetify#11511]
### Environment

**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
open url  https://vuetifyjs.com/ja/components/buttons/#api

### Expected Behavior
 `white--text` 

### Actual Behavior
 `white-text` 

### Reproduction Link
<a href="https://vuetifyjs.com/ja/components/buttons/#api" target="_blank">https://vuetifyjs.com/ja/components/buttons/#api</a>

**Comment by nekosaur** [comment]
I've updated the text in Crowdin. It will be pushed out to docs on next release.

**Comment by suzu-prog** [comment]
@nekosaur thx!!!
