### ISSUE TITLE
v-data-table's pagination backed by vuex

### ISSUE THREAD

**Issue by geertolaerts** [vuetifyjs/vuetify#1151]
### Steps to reproduce
Create a data table and back the data and pagination with vuex in strict mode. When sorting the table everything works and uses the mutations of vuex. However when you change pagination (eg number of items per page or use the next/previous arrow) it doesn't use vuex mutations, but changes the state directly leading to a vuex error: `Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."`
I believe this is due to [foot.js](https://github.com/vuetifyjs/vuetify/blob/master/src/components/tables/mixins/foot.js) line 10 `nativeOn: { click: () => (this.computedPagination.page--) }`

### Versions

Vue version: 2.4.2
vuetify: 0.14.7
vuex: 2.3.1
OS: Mac OS
Browser: Chrome

### What is expected ?
The pagination can be used togheter with vuex

### What is actually happening ?
Vuex gives an error: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

### Reproduction Link
[https://codepen.io/anon/pen/LjVvPX](https://codepen.io/anon/pen/LjVvPX)
I also added a console log statement in my computed set of the pagination. When changing sorting it is used, but when changing pagination it isn't.

**Comment by geertolaerts** [comment]
Hej,
Are you sure this also fixes the next/previous page or does it only fixes the select where you select rowsPerPage?

**Comment by johnleider** [comment]
It fixes the issue you created an issue about.

**Comment by geertolaerts** [comment]
Perfect, as that was in the issue :D.
Look forward to using it

**Comment by triberraar** [comment]
I changed to the new version, and indeed it works with the dropdown. but it still doesn't work when changing pages with the previous and next arrow buttons in the table. 
Should i open a new issue for it or ?

**Comment by nekosaur** [comment]
Yes
