### ISSUE TITLE
[Feature Request] Allow Select Dropdowns To Have Multiple Options With The Same Value

### ISSUE THREAD

**Issue by xd-luke** [vuetifyjs/vuetify#11529]
### Problem to solve
Right now, the Select component will filter any options with duplicate values. Sometime we actually want to show different option texts in a dropdown that pass the same value.

### Proposed solution
Do not filter out select options with duplicate values.

**Comment by yooneskh** [comment]
Out of curiosity, why do you need such a thing?

**Comment by xd-luke** [comment]
I have a drop down where two different options correspond to the same value used in a calculation. Here it is:

    sulfurDioxideUOMOptions: [
      { text: "calculators.units.gPerL", value: 1 },
      { text: "calculators.units.gPerhL", value: 100 },
      { text: "calculators.units.mgPerL", value: 1000 },
      { text: "calculators.units.ppm", value: 1000 },
      { text: "calculators.units.gPer100ml", value: 0.1 },
      { text: "calculators.units.lbsPerGallon", value: 0.0083454 },
    ],

As it is now, Vuetify is filtering out the duplicate, but, I intentionally would like to have two options that have the same value. 

I looked at the Vuetify source code quickly, and it appears there is a function which specifically filterers out duplicates. Is there any underlying purpose for this behaviour? If not, why not allow the developer to choose whether or not to allow their dropdowns have duplicate values. I can think of many scenarios in which duplicate values would be required.

As it stands right now, my hack to get around this is to make one of the values be 1001 and add some logic after selection which says: if the value is 1001 then set it as 1000 for the calculation. Which is just an added layer on complexity required because of a framework limitation.

**Comment by jacekkarczmarczyk** [comment]
Let's say I choose `ppm`, save data and refresh the page. How would you know that `ppm` should be displayed in `v-select`?

**Comment by xd-luke** [comment]
You can't know with just a value alone.. If I needed that functionality, I would create a 3rd field named id which would be hidden and unique. 

This is the same reason why we need to add :key in v-for. Since, we sometimes iterate over 'identical' objects. 

I checked the docs when I first stumbled upon this issue in search of just such a key which could be set. But, it seems it isn't implemented.

**Comment by yooneskh** [comment]
I don't know if i understood your problem correctly, but can't you change your data structure to this
```
const items = [
  { name: '', quantity: x. id: 1 },
  ...
]
```
then bind it to the `v-select` like this
```
<v-select
  ...
  :items="items.map(i => ({ value: i.id, text: i.name })"
  v-model="selectedId"
  ...
/>
```
now you can have the real object like this
```
computed: {
  realSelectedObject() {
    return this.items.find(i => i.id === selectedId);
  }
}
```

**Comment by xd-luke** [comment]
This looks like an interesting solution. It certainly is more elegant than my hack. 

But, it still is a fair bit of added complexity for something that I think the framework could be capable of handing under the hood more gracefully. 

They could just add an optional field "id" which can be overwritten to link to the html element uniquely. And use the default value of "[option_text]-[option_value]" for the id if the developer doesn't set it. I think it would cover just about everything, as well as state management. A developer would only need to set the id in the obscure case where they want to render multiple options with the same text and value. 

Unless I'm not fully understanding some underlying limitation. 

There doesn't seem to bit a limitation in raw HTML: https://stackoverflow.com/questions/19714128/html-in-a-select-is-it-required-that-the-value-attribute-of-each-option-be-uni

**Comment by jacekkarczmarczyk** [comment]
If you have different texts then you can just use an array of texts as items, no need for objects/map/etc
That's still a workaround though

**Comment by yooneskh** [comment]
@xd-luke HTML is definitely not the limitation. What you say is plausible and is definitely worth a feature request.

**Comment by mnandrews8** [comment]
I was on here looking for a solution and ran across this. I had my code set-up like xd-luke. I found this method simpler to set-up. I just want to add that I would also like an improvement in this area. Thanks!

**Comment by hrobertson** [comment]
In my case I have a lot of options. They are listed in alphabetical order but I have a requirement that the commonly selected ones are also duplicated at the top of the list for easy selection. They should still exist in their natural alphabetical position as well though.

A common example of this pattern is a country selector.

**Comment by KaelWD** [comment]
Vuetify 3 no longer deduplicates items.
