### ISSUE TITLE
[Bug Report] v-navigation-drawer update:mini-variant event fires only in false

### ISSUE THREAD

**Issue by woodgates** [vuetifyjs/vuetify#11522]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Opera 68.0.3618.125
**OS:** Windows 10

### Steps to reproduce
1. Create a Navigation Drawer with the expand-on-hover prop.
2. Hover over the Navigation Drawer. The event 'update:mini-variant' is fired with the false value
3. Hover out the Navigation Drawer. No event 'update:mini-variant' is fired.

### Expected Behavior
I expect that when hovering out of the component it fires the 'update:mini-variant' event with the true value.

### Actual Behavior
The event ''update:mini-variant' is not fired when hovering out.

### Reproduction Link
<a href="https://codepen.io/woodgates/pen/jObjZpy" target="_blank">https://codepen.io/woodgates/pen/jObjZpy</a>

**Comment by jacekkarczmarczyk** [comment]
Now it needs a prop.sync to work
https://codepen.io/jkarczm/pen/abdNzmJ?editors=1011

**Comment by johnleider** [comment]
The above codepen works as expected. Closing as resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
