### ISSUE TITLE
[Feature Request] Inner icon button field

### ISSUE THREAD

**Issue by ScopZy** [vuetifyjs/vuetify#11526]
### Problem to solve
When you click on the inner icon into a text field, u should open the menu (like date or time picker)

### Proposed solution
trigger the click and add the focus event

**Comment by KaelWD** [comment]
This is super vague, I'm not sure what you're asking. We have examples in the documentation of how to integrate a date picker with a text field: https://vuetifyjs.com/en/components/date-pickers/#dialog-and-menu
