### ISSUE TITLE
[Bug Report] v-combobox input problem

### ISSUE THREAD

**Issue by appurist** [vuetifyjs/vuetify#11527]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Linux x86_64

### Steps to reproduce
The top half of the Codepen illustrates the problem(s):
1. select "Second choice" from the combobox list of choices.
2. start typing, e.g. "abc"

### Expected Behavior
On typing, I'd expect that either:
- the value of the input would be what was shown ("Second choiceabc") or that
- it would just show "abc" once typing started.
i.e. either that the edit value would match what was shown, or what was shown would match the edit value.

### Actual Behavior
Observe that the input field shows "Second choice" in blue (has focus) and typed input as a suffix in a different color (black) and that the input field shows "Second choiceabc".  The actual edit field *value* is just "abc" but it is showing "Second choiceabc".

3. Check console for event notifications. No events on typing, but focus loss etc update the model to "abc" without the "Second choice" prefix that was shown in the edit field.

### Reproduction Link
<a href="https://codepen.io/appurist/pen/qBOedWP?editors=1111" target="_blank">https://codepen.io/appurist/pen/qBOedWP?editors=1111</a>

### Other comments
The bottom half of the Codepen example shows my best workaround in the meantime, a combination of separate v-text-field and v-select fields.

Also: if I insert the commented-out line that immediately follows the <v-combobox> tag, with the @keydown handler, or if I similarly assign a @click handler, this always produces a Vue warning: "`[Vue warn]: Property or method 'outerHTML' is not defined on the instance but referenced during render.` I have tried applying many modifiers on the event handlers, the one that remains in the Codepen example commented out is `@keydown.self.stop.prevent="onKeydown"` 

Note that typing into the first field (v-text-field) in the *workaround* section of the Codepen causes the model value to immediately update, not so when typing into the combobox in the top half. I think if the model updated like v-text-field, the problem would be gone because the input field would lose the "Second choice" (visual-only) prefix.

There's also a simpler example here: https://codepen.io/appurist/pen/gOaNvQb?editors=1011

**Comment by appurist** [comment]
I think that paragraph above near the end is the key issue: when typing into the input field, v-combobox **does not send** @input or @change events, unlike v-text-field which does.

**Comment by appurist** [comment]
I think this is only a problem if the slots are used for the selection and/or items. Perhaps I'm using them incorrectly.

**Comment by appurist** [comment]
I may be able to work around the problem and still use `v-combobox`, by returning to the use of the default slots.  But it seems the _autocomplete_ functionality (which is optional for me) completely disables the dropdown if the edit field does not match any choices.

For example, I can't type 'x', realize it's wrong, and then drop the list down to pick something completely _different_.  I can't even see the choices.  I'm assuming this is because `v-combobox` is specifically derived from `v-autocomplete`.

Is there a way to _disable_ the autocomplete functionality in `v-combobox`? Or perhaps to force it to only highlight the matching values rather than to filter them out?

**Comment by appurist** [comment]
I think the dependency on `v-autocomplete` means that a simple normal combobox of edit+list is not really possible here with that component. I think at this point it was a mistake to try to use v-combobox for this; in Vuetify it brings in too much other functionality.

Instead, I should fake a combobox with a `v-textarea` on the left and a chevron or triangle icon (`append-icon` or `append-outer-icon`) on the right that opens a dropdown list.

**Comment by johnleider** [comment]
Combobox doesn't update the value unless you confirm by pressing enter or explicitly clicking an item.

If this is your concern, I would say it is working as intended. If it's not, let me know.

**Comment by appurist** [comment]
A v-combobox may not update the value, but that only adds to the weirdness. It doesn't update the display either, to remove the old value when it changes. So the display shows **both** the old and the new jammed together, although it shows the old text in blue (focused, I guess) with the new text in black. Then if you click outside the box or hit Enter, the blue part disappears suddenly and is replaced by what was in the black part (now blue). Did you look at the behavior in the first codepen link above (the one labeled "Reproduction link")? It starts with "First choice" and if you type 'a' it then shows "First choicea" in two different colors.

I can't really imagine any scenario where this behavior is desirable, as "First choicea" is neither the model value nor what the user typed. There's a major disconnect at the user experience and the data.

Again, I think this is due to the inheritance of v-autocomplete rather than v-text-field with choices. **I think the hierarchy is inverted**. There seems to be an assumption that comboboxes will **always** be some form of auto-complete _with search functionality_, whereas I see auto-complete comboxes as regular comboboxes that have _additional_ search/matching functionality added to the basic combobox. 

To illustrate, the Wiki page for [combobox](https://en.wikipedia.org/wiki/Combo_box) shows my desired behavior of just being able to type something in, while the [dropdown list](https://en.wikipedia.org/wiki/Drop-down_list) page includes the auto-complete pairing with the input. Unfortunately Vuetify does not provide a combo without that auto-complete functionality, so it's always forced into the dropdown list behavior.

The search functionality cannot be disabled in a combobox, even with a custom search field that does nothing (I tried that in the second codepen link above).

Again, I think the core problem is that the hierarchy should be inverted, that an _auto-complete_ combobox should be derived from a _simpler_ combobox, without forcing the autocomplete functionality into the simplest of comboboxes. In its simplest form, it should be possible to have a picklist of choices paired with a manual edit (text field).

I recognize that much of this is just my opinion on that the simple generic form of combobox is important to provide along with the more advanced searchable one. If that is not seen as consistent with Vuetify's direction then that's the end of the story and you can close this as "no change required" or whatever.

**Comment by appurist** [comment]
FYI, I have replaced my use of v-combobox with a custom component made from a `v-text-field`/`v-list` pair that share the same model, so I have a workaround I am using now.

**Comment by mikecbone** [comment]
I resolved this by adding a ref property `ref="combobox"` on the combobox 

And then manually blur the combobox on submit using the reference, then wait for `tickTick` so the v-model can update

```
// Submit button method
this.$refs.combobox.blur();
this.$nextTick(() => {
    // Do your submit stuff
});
```

**Comment by appurist** [comment]
@mikecbone That's a step forward but won't help with the visual problems present before submit, namely the **oldvalue**_Newvalue_ dual-colored input value.

**Comment by mikecbone** [comment]
@appurist Sorry If I'm missing something obvious but if you just remove your `v-combobox` slots, does it not work as you're expecting? 

I.e. remove
```
<template v-slot:item="data">
    <span v-text="data.item"></span>
</template>

<template v-slot:selection="data">
    <span v-text="data.item"></span>
</template>
```

so it's just

```
<v-combobox 
    v-model="choice" 
    :items="choices" 
    clearable 
    open-on-clear 
    persistent-hint
    label="Please enter the choice">
</v-combobox>
```

**Comment by appurist** [comment]
@mikecbone Thank you! Yes, it's the `selection` slot causing the remaining problem. And yes, with that resolved, in combination with your `blur` workaround to blur on submit, I think we have a winning behavior. (Might be nice to have an `autoclose` prop or something like that on `v-combobox` to default to that behavior.)

I generally avoid adding slot bodies unless necessary for some reason, so I'm not sure why I felt it necessary to add the slots; either I was doing something more complex and needed to modify the behavior slightly, or if I remember correctly, it was away to work around a Vuetify problem I was seeing (that likely was short-lived and has since been resolved). I do remember seeing a fix months ago that I hoped would resolve this problem but "it didn't" (presumably because I didn't also remove the slots). It's also possible it has been entirely user error all along, adding the selection slot when it wasn't needed. I'm not sure why that breaks the behavior but I thank you for spotting it.

I don't need the drill-down search functionality, so I still think the hierarchy is inverted, but that's extra functionality, and not an actual problem, so at this point I consider this resolved.
