### ISSUE TITLE
[Bug Report] v-simple-table with 2 header rows and got rendered wrongly when set to fixed-header and dense

### ISSUE THREAD

**Issue by chuyennk** [vuetifyjs/vuetify#11525]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
1. create a v-simple-table with 2 header rows
2. set props to fixed-header and dense

### Expected Behavior
2 header rows should align to the table header

### Actual Behavior
the position of 2nd header row is still follow the normal spacing (i.e. set dense=false). Hence render at wrong position.

### Reproduction Link
<a href="https://codepen.io/chuyennk/pen/GRpbVEQ" target="_blank">https://codepen.io/chuyennk/pen/GRpbVEQ</a>

**Comment by johnleider** [comment]
fixed in 1ec7de8
