### ISSUE TITLE
[Bug Report] V-badge bug with v-text-field

### ISSUE THREAD

**Issue by VijeshDatt** [vuetifyjs/vuetify#11531]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.5.17
**Browsers:** Edge 83.0.478.37
**OS:** Windows 10

### Steps to reproduce
Place v-text-field inside v-col with md width less than 4 (works)
Place v-text-field inside v-col with md width greater than 4 (where the issue starts)
Assign v-badge to v-text-field

### Expected Behavior
v-text-field with v-badge to resize based v-col width

### Actual Behavior
v-text-field with v-badge resizes to col width = 4, then don't resize past it if given a bigger width.

### Reproduction Link
<a href="https://codepen.io/vijeshdatt/pen/qBOzdvv" target="_blank">https://codepen.io/vijeshdatt/pen/qBOzdvv</a>

**Comment by jacekkarczmarczyk** [comment]
Workaround: `<v-badge class="d-block" />`
https://codepen.io/jkarczm/pen/oNbxgXG

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
