### ISSUE TITLE
[Bug Report] VFileInput prepend slot doesn't work #2

### ISSUE THREAD

**Issue by AASabancev** [vuetifyjs/vuetify#11536]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
See reproduction link.
Add a \<template v-slot:prepend\> to a \<v-file-input\>.

### Expected Behavior
The set prepend slot should be used to show custom html content or vue(vuetify) components before input element;

### Actual Behavior
The prepend slot appears to be ignored completely.

### Reproduction Link
<a href="https://codepen.io/aasabancev/pen/BajBZzN" target="_blank">https://codepen.io/aasabancev/pen/BajBZzN</a>

### Other comments
It seems impossible to use the prepend slot in a v-file-input. You can see than other slots are working, but not "prepend" slot.

**Comment by MajesticPotatoe** [comment]
duplicate #9580
