### ISSUE TITLE
[Bug Report] v-text-field isn't updating correctly when the model is modified during an input event.

### ISSUE THREAD

**Issue by tircnf** [vuetifyjs/vuetify#11537]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
create a component that is using v-model and a v-text-field.
in the @input event, modify the data before emtting the event.

The model value is correct.  The v-text-field widget doesn't display the current value.

### Expected Behavior
the v-text-field widget should always display what is in the model.

### Actual Behavior
It only updates after a successful change is applied.  Look at the codepen.  If you type "11/11/hello world/"
it isn't until you type the "/" that the text field updates to the filtered values.

### Reproduction Link
<a href="https://codepen.io/mikeburns/pen/rNxBzLR" target="_blank">https://codepen.io/mikeburns/pen/rNxBzLR</a>

### Other comments
I found errors similar to this in vuetify 1.5, but nothing currently open.

**Comment by Lisible** [comment]
I'm having the same issue

**Comment by mauriziocalarese** [comment]
same here.

**Comment by KaelWD** [comment]
> I found errors similar to this in vuetify 1.5, but nothing currently open.

They were all closed because you have to use `this.$nextTick` to update the same value in an input event. This may change with vue 3 but no promises.
