### ISSUE TITLE
[Bug Report] v-dialog - clicking outside of it goes focus in v-dialog

### ISSUE THREAD

**Issue by yamatokataoka** [vuetifyjs/vuetify#11530]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.15

### Steps to reproduce
clicking v-btn or v-text-field outside of v-dialog

### Expected Behavior
clicking components outside of v-dialog doesn't affect on a button in v-dialog

### Actual Behavior
the focus goes a button on v-dialog even if clicking v-btn or v-text-field outside of v-dialog

### Reproduction Link
<a href="https://codepen.io/yamatokataoka/pen/NWGQdYv?editors=1010" target="_blank">https://codepen.io/yamatokataoka/pen/NWGQdYv?editors=1010</a>

### Other comments
the bug behavior is slightly different on Chrome and Safari.
on Safari, only v-text-field is affected.

**Comment by KaelWD** [comment]
It's a feature, see #2538 and https://github.com/vuetifyjs/vuetify/issues/6892#issuecomment-523286705
