### ISSUE TITLE
[Bug Report] MD `local_offers` Icon is offset in v-btn

### ISSUE THREAD

**Issue by maratumba** [vuetifyjs/vuetify#11535]
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Mac OS 10.14

### Steps to reproduce
Hover over the button on the left, you'll see the offset. The `check` icon seems to be working ok.

### Expected Behavior
not being offset

### Actual Behavior
it is offset

### Reproduction Link
<a href="https://codepen.io/gulyamani/pen/zYrOBwa" target="_blank">https://codepen.io/gulyamani/pen/zYrOBwa</a>

### Other comments
I haven't checked other icons. There could be more.

**Comment by nekosaur** [comment]
The icon name is `local_offer`
