### ISSUE TITLE
[Bug Report] Presets don't play nicely with variable overrides

### ISSUE THREAD

**Issue by tcoile** [vuetifyjs/vuetify#11538]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61, Safari, Google Chrome
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. add a preset (e.g. owl) to your project
2. in a styles folder within src, go ahead and try to override the main styles.scss page. create a variables.scss file and type "$body-font-family: 'Courier'" 
3. Cool, now run the app, and you'll see that it's all Owl functionality -- font is NOT courier.

Note, if you just run steps 2 and 3 (aka just don't add a preset to your project), we override font just as expected

### Expected Behavior
Ideally, users should be able to start from some partially-customized base (e.g. Owl, Basil, etc), then define their custom variable overrides. Currently, only style overrides (e.g. changing the primary color) is supported.

### Actual Behavior
Font isn't overridden, nor can I override any other variable. This makes sense, as the documentation states that it's a vuetify-cli plugin that's merging my variable changes with vuetify's styles automatically. It must be doing this BEFORE merging with the preset. It should be doing this AFTER merging with the preset, so the user's overrides get applied LAST.

**Comment by MajesticPotatoe** [comment]
duplicate #10312
