### ISSUE TITLE
[Bug Report] Footer Absolute Hide Elements

### ISSUE THREAD

**Issue by BlackYuzia** [vuetifyjs/vuetify#11539]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 7

### Steps to reproduce
1. Create expanded pannels... one more panels... more and more until .... maybe > 10?
2. Create footer with absolute true
I was use default example for tests:

>             <template>
                <v-footer absolute class="font-weight-medium">
                    <v-col class="text-center" cols="12">
                        {{ new Date().getFullYear() }} — <strong>Keys Dev Team</strong>
                    </v-col>
                </v-footer>
            </template>

3. Get one or more hidden elements of expanded panels by absolute footer 
4. ????
5. PROFIT

### Expected Behavior
I expect didn't hide elements by footer.
Footer stay on end of page if no items to footer and didn't hide any area.
Move downer if elements on near of footer (sry my bad eng)

### Actual Behavior
If elements too many (or content)and he was moved near of (to) footer, footer was hide some place of element or full of element.

### Reproduction Link
<a href="https://codepen.io/Black_Yuzia/pen/xxZKPqa?editors=1100" target="_blank">https://codepen.io/Black_Yuzia/pen/xxZKPqa?editors=1100</a>

### Other comments
Images with example:

> https://ibb.co/SQWQcW5
> https://ibb.co/xCxy9bp

**Comment by KaelWD** [comment]
This is what `v-content` and the `app` prop are for. 

https://vuetifyjs.com/en/components/application/#application-components
