### ISSUE TITLE
v-select doesn't allow to read options with long texts in small screens

### ISSUE THREAD

**Issue by lobosan** [vuetifyjs/vuetify#1154]
### Steps to reproduce
Open the [codepen](https://codepen.io/lobosan/pen/jLbNeJ/) and shrink the screen up to 372px (this simulates the resolution of my phone)

![v-select](https://user-images.githubusercontent.com/314886/28680392-d3588d48-72bb-11e7-9440-cfd89fa5c8ec.png)

### Versions
vue 2.4.2, vuetify 0.14.7

### What is expected ?
It should center the options menu and add a horizontal scrollbar as it does for vertical content

### What is actually happening ?
When selecting the component the options with long texts aren't readable because the menu goes all the way to the right of the screen

### Reproduction Link
https://codepen.io/lobosan/pen/jLbNeJ/

**Comment by latsyrct** [comment]
This also happen for <v-radio> & <v-checkbox>.

**Comment by johnleider** [comment]
@latsyrct Those components have nothing to do with this issue, please create a new one.
