### ISSUE TITLE
[Bug Report] [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object 

### ISSUE THREAD

**Issue by weiloon1234** [vuetifyjs/vuetify#11551]
### Environment
**Vuetify Version:** 2.2.31
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1.1
**OS:** Mac OS 10.15.5

### Steps to reproduce
load the codepen, inspect element

annoying error message

[Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object 

found in

---> <VSelect>

### Expected Behavior
it work, but annoying error message

### Actual Behavior
work without annoying message

### Reproduction Link
<a href="https://codepen.io/weiloon1234/pen/ExPxLEz" target="_blank">https://codepen.io/weiloon1234/pen/ExPxLEz</a>

![image](https://user-images.githubusercontent.com/7457342/83655680-444fc000-a5f1-11ea-813b-d9c3850b082b.png)

**Comment by KaelWD** [comment]
This isn't an array:

![image](https://user-images.githubusercontent.com/16421948/83656245-a82eb480-a602-11ea-9186-7c040df09c02.png)
