### ISSUE TITLE
[Feature Request] Change default of locale-first-day-of-year for date-picker to Thursday

### ISSUE THREAD

**Issue by riemervdzee** [vuetifyjs/vuetify#11557]
### Problem to solve
We just upgraded from Vuetify 2.2.22 to 2.2.32 and encountered a change in behavior in our date-pickers with `show-week` enabled. The week-numbers themselves were one week off when `first-day-of-week="1"` was set (which is pretty common in the Netherlands and I suppose in the rest of EU), when we omitted this the weeknumbers were displayed correctly again in newer Vuetify versions.

This is due the introduction of https://github.com/vuetifyjs/vuetify/commit/b7f830a68127aed058f48859dc22c4c012c751a5

And namely `locale-first-day-of-year` being defaulted to `0`?

### Proposed solution
Change the default to 4 = Thursday which is consistent to ISO 8601 and the previous behavior. Or atleast default to the same number as `first-day-of-week` when set

**Comment by jacekkarczmarczyk** [comment]
@abbierwolf thoughts?

**Comment by abbierwolf** [comment]
@jacekkarczmarczyk The default is set to 0 because the default behavior of the v-date-picker component is locale US en not ISO 8601.  A hint is given in the docs for users who use ISO 8601 like I do. If you want to change the default behavior to ISO 8601 also the first-day-of-week default has to change.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
