### ISSUE TITLE
[Bug Report] Autocomplete placeholder only displays on focus when using chips

### ISSUE THREAD

**Issue by KyleReese** [vuetifyjs/vuetify#11553]
### Environment
**Vuetify Version:** 2.2.32
**Last working version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Define an autocomplete with a placeholder and chips enabled

### Expected Behavior
The placeholder should display in the autocomplete before the autocomplete is focused

### Actual Behavior
The placeholder value does not appear until the autocomplete is focused

### Reproduction Link
<a href="https://codepen.io/KyleReese/pen/zYrYerx" target="_blank">https://codepen.io/KyleReese/pen/zYrYerx</a>

### Other comments
This does not appear to happen in Firefox

**Comment by Jan-Heussner** [comment]
I have the same issue in firefox. Also with your example. It did not happen before when i have used vuetify over CDN.

**Comment by ryo-gk** [comment]
It seems to be affected this commit, so it happen with a recent version.
https://github.com/vuetifyjs/vuetify/commit/254bb29a3e0d2cbd5469e5159f5eec9e58ca3a11

**Comment by ryo-gk** [comment]
@johnleider 
I want to fix this, but I don't understand what the comment `//chips force input to wrap` mean in this commit (https://github.com/vuetifyjs/vuetify/commit/254bb29a3e0d2cbd5469e5159f5eec9e58ca3a11).
Could you tell me the a little more about the background of this?

**Comment by zahassanyum** [comment]
Happening to me as well. Oddly, the bug occurred only in the production build and never during development while the version was 2.2.27. After upgrading to v2.3.1, it affects dev too now.

**Comment by nsakiya-incomm** [comment]
I had the same issue. I believe that start from version 2.2.31. I don't know how to fix it, but it's likely to be from 
packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass 
Here's the diff of this file in 
https://github.com/vuetifyjs/vuetify/compare/v2.2.30...v2.2.31

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/254bb29a3e0d2cbd5469e5159f5eec9e58ca3a11#diff-2d9b95b62038e8a0535f1b30ed1f230fR20

**Comment by KyleReese** [comment]
> 
> 
> [254bb29#diff-2d9b95b62038e8a0535f1b30ed1f230fR20](https://github.com/vuetifyjs/vuetify/commit/254bb29a3e0d2cbd5469e5159f5eec9e58ca3a11#diff-2d9b95b62038e8a0535f1b30ed1f230fR20)

It looks to me like there just needs to be a check to not set the height to 0 when the autocomplete has a placeholder defined.

**Comment by SerjLeo** [comment]
Yes, this bug caused by `.v-autocomplete:not(.v-input--is-focused).v-select--chips input {
    max-height: 0;
}`
Overwriting this in local styles  `.v-autocomplete:not(.v-input--is-focused).v-select--chips input {
    max-height: 25px !important;
}` helped for me

**Comment by slbedwell** [comment]
> Yes, this bug is caused by `.v-autocomplete:not(.v-input--is-focused).v-select--chips input { max-height: 0; }`
> Overwriting this in local styles `.v-autocomplete:not(.v-input--is-focused).v-select--chips input { max-height: 25px !important; }` helped for me

I was also having this issue, thanks for providing a solution @SerjLeo!

**Comment by daceynolan** [comment]
I just had this issue - @SerjLeo thank you for the solution!

**Comment by stas-kh** [comment]
Shout out to @SerjLeo for a workaround!

**Comment by newmaidumosa** [comment]
Thank you @SerjLeo

**Comment by daidais** [comment]
Still present in 2.4.9

I solved this with a custom rules in my SAAS with:
```saas
.v-autocomplete:not(.v-input--is-focused).v-select--chips input {
  max-height: inherit;
}
```
Thanks @SerjLeo

**Comment by felipe-fator3** [comment]
Thx for the solution, @SerjLeo and @daidais !
Just an extra note here, in my case, for some reason it only effectively worked when I used a deep selector:
```js
.v-autocomplete:not(.v-input--is-focused).v-select--chips >>> input {
  max-height: inherit;
}
```

Anyways, it worked! 😄 

> Still present in 2.4.9
> 
> I solved this with a custom rules in my SAAS with:
> 
> ```
> .v-autocomplete:not(.v-input--is-focused).v-select--chips input {
>   max-height: inherit;
> }
> ```
> 
> Thanks @SerjLeo

**Comment by gapnav** [comment]
For some reason it didn't work for me neither with `>>>` nor without it. So it made me to use `!important!`. One more issue is bottom line was jumping when I used `small-chips`, so I also had to add some duct-tape to `padding`.
Here is what I have now:

```
.v-autocomplete:not(.v-input--is-focused).v-select--chips input {
  max-height: inherit !important;
  padding: 6px 0 !important;
}
```

**Comment by Favorlock** [comment]
None of the proposed solutions work for me. Would be nice if this were to be fixed soon considering this issue has been open for well over a year.

**Comment by drice89** [comment]
Still present in 2.6.2

The style override work arounds suggested previously did not work for me. Please fix this.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
