### ISSUE TITLE
[Bug Report] v-select: Text is truncated when using multiple props and having vertical scrollbar in FireFox (Ubuntu Bionic)

### ISSUE THREAD

**Issue by mariadb-ThienLy** [vuetifyjs/vuetify#11556]
### Environment
**Vuetify Version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create a v-dialog with width set to "unset. 
Create a v-card as dialog content with min-width="200px"
Then wrap v-select in v-card-text with width set to 150px
Initial array items has 5 items:
```
items: [
        "service",
        "date",
        "user",
        "reply_time",
        "default_db"
      ]
```
Click v-select, all items is not truncated. Ok we're good.
Then click "Add item" to make items.length >=6 to enable vertical scrollbar
Click v-select, some of items with long text is truncated. Ok we're not good.

### Expected Behavior
Some of items, eg: "reply_time", "default_db" should not be truncated

### Actual Behavior
Some of items, eg: "reply_time", "default_db" is truncated

### Reproduction Link
<a href="https://codepen.io/duongthienlee/pen/PoZwqRa" target="_blank">https://codepen.io/duongthienlee/pen/PoZwqRa</a>

### Other comments
This happens in Firefox with ubuntu bionic, I haven't check Firefox on other OS, I guess something related to CSS but couldn't figure it out. Items are shown in v-menu, I found that  .v-menu__content has max-width:80%, I guess it should stretch to 80% of page width, but it doesn't.

Notice that it happens even when I set initial items with array length >=6, so adding new items to array after first render is for testing purpose.

**Comment by KaelWD** [comment]
Seems to be a flexbox bug in firefox, the intrinsic width doesn't account for the scrollbar like in other browsers.

**Comment by mariadb-ThienLy** [comment]
> Seems to be a flexbox bug in firefox, the intrinsic width doesn't account for the scrollbar like in other browsers.

Do you have any workarounds for this?

**Comment by mariadb-ThienLy** [comment]
Seems the only workaround mentioned in this post [https://bugzilla.mozilla.org/show_bug.cgi?id=1335265](url) is to set overflow-y: scroll. However, items doesn't need to be scroll will always have vertical scrollbar visible.

**Comment by everhardt** [comment]
This is not related to the `multiple` prop I think: that just makes it easier to reproduce as it adds the width of the checkbox to each row. If you have longer texts they are also truncated without `multiple`, see https://codepen.io/everhardt/pen/MWEYBJR. I can reproduce it on macOS in Safari but not in Chrome (where it works as it should).
