### ISSUE TITLE
[Feature Request] Date picker displaying first month of date selection spanning over 2+ months

### ISSUE THREAD

**Issue by DamianGlowala** [vuetifyjs/vuetify#11555]
### Problem to solve
Having chosen multiple dates over two months or more, the date picker is initially set to display the view of last month.

Referring to my use case, accommodation owners who can see the incoming booking enquiries with the selected dates are presented with a calendar not beginning set on the first month within the selected date range, but the last one, what they reported as confusing and error-prone (as they may overlook the fact they can navigate to the previous month). It just does not feel natural. 

### Proposed solution
Already existing prop **picker-date** could solve the issue if it didn't disable switching between months. If I set **picker-date="booking.dates[0]"** it indeed displays the month including the first date of the booking, but there is no way to preview other months having set that.

A boolean prop could work, fired once during the initialisation step telling the date picker whether to start with the month of the first date in the range or the last one (currently the default behaviour).

**Comment by jacekkarczmarczyk** [comment]
`:picker-date.sync="booking.dates[0]"`

**Comment by DamianGlowala** [comment]
Works perfectly fine now, problem solved :)
Thank you for help!
