### ISSUE TITLE
[Bug Report] v-autocomplate dont clearout after selection and v-model become null,

### ISSUE THREAD

**Issue by MicroDreamIT** [vuetifyjs/vuetify#11561]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.5.7
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.15.5

### Steps to reproduce
Reproduction URL: `https://codepen.io/shahanursharif/pen/RwrNjyv`

After selection, in `addItems` method I am triggering `this.item` to be null. Its become null but selection remain as it is. I think this is a bug. If not then what is the proper way to clearout the selection when value become null. 

### Expected Behavior
selection should be clear out then v-model become null

### Actual Behavior
selection should be clear out then v-model become null

### Reproduction Link
<a href="https://codepen.io/shahanursharif/pen/RwrNjyv" target="_blank">https://codepen.io/shahanursharif/pen/RwrNjyv</a>

### Other comments
After selection, in `addItems` method I am triggering `this.item` to be null. Its become null but selection remain as it is. I think this is a bug. If not then what is the proper way to clearout the selection when v-model become null.

**Comment by MajesticPotatoe** [comment]
You need a $nextTick()
```
this.$nextTick( () => {
  this.item = null
})
```

**Comment by MicroDreamIT** [comment]
@MajesticPotatoe Thank you. It works
