### ISSUE TITLE
[Bug Report] missing table headers bottom border

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#11567]
### Environment
**Vuetify Version:** 2.3.0-beta.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
create v-data-table

### Expected Behavior
table header has bottom border

### Actual Behavior
table header doesn't have bottom border

### Reproduction Link
2.3.0 <a href="https://codepen.io/jkarczm/pen/OJMPaPa?editors=1010" target="_blank">https://codepen.io/jkarczm/pen/OJMPaPa?editors=1010</a>
2.2.x https://codepen.io/jkarczm/pen/eYJmQmJ?editors=1010
Broken probably in https://github.com/vuetifyjs/vuetify/commit/3fcc67e2c6ab0a7de53577a80cf966d50522fa1b

**Comment by johnleider** [comment]
fixed in #11568
