### ISSUE TITLE
[Feature Request] CSS module Configration with Vuetify

### ISSUE THREAD

**Issue by chintankumarpadaliya** [vuetifyjs/vuetify#11564]
### Problem to solve
I would like to use make my classes names shorter and for that i am using it CSS Modules. With custom classes CSS Module is working like charm. But when i come to Vuetify classes then CSS Modules is not working at all.

My goal is not to render long html css classes name which is time-consuming and performence will be slow due to long css classes. better use CSS Modules and make it classes shorter and render time will be better then before.

Here is what i would like to achieve:

class="t-expandtext  t-expandtext--expanded"
class="_eed1 _10d8"

### Proposed solution
My goal is not to render long html css classes name which is time-consuming and performence will be slow due to long css classes. better use CSS Modules and make it classes shorter and render time will be better then before.

Here is what i would like to achieve:

class="t-expandtext  t-expandtext--expanded"
class="_eed1 _10d8"

**Comment by KaelWD** [comment]
Not likely to happen, sorry. The performance difference is basically nothing if you're using gzip.

**Comment by chintankumarpadaliya** [comment]
there is any possibilities where i can use Vuetify classes with CSS Modules...so my goal will be achieve.

**Comment by qxygene** [comment]
any update on this?
