### ISSUE TITLE
[Feature Request] Add 'scrollTo' or 'first' index prop to v-virtual-scroll

### ISSUE THREAD

**Issue by seankenny** [vuetifyjs/vuetify#11563]
### Problem to solve
In v2.3.0 we are using VVirtualScroll in one of our forms to allow users to select an item from a large list.  On edit of the form, we would like the previously selected value to be the first item in the scroll area.

### Proposed solution
The addition of a 'scrollTo' or 'first' index property would allow us to preset the first item in the list to be rendered.

**Comment by johnleider** [comment]
The goTo feature is receiving some updates for version 3 and this is something that I've considered. However, at this time, there is a built-in way to do this using the browser API. I implemented in the new documentation and it is the recommended way of doing this for now.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by qxygene** [comment]
This feature will be great if you can.
