### ISSUE TITLE
[Bug Report] Dense doesn't work in v-data-table.

### ISSUE THREAD

**Issue by Meller008** [vuetifyjs/vuetify#11566]
### Environment
**Vuetify Version:** 2.3.0-beta.8
**Last working version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
1. Create v-data-table
2. Add props "dense"

### Expected Behavior
The table should become compact.

### Actual Behavior
The table does not change its size.

### Reproduction Link
<a href="https://codepen.io/Meller008/pen/bGENmRK?editors=1010" target="_blank">https://codepen.io/Meller008/pen/bGENmRK?editors=1010</a>

### Other comments
This error is present on your site.

**Comment by jacekkarczmarczyk** [comment]
Broken probably in 3fcc67e

**Comment by Meller008** [comment]
good

**Comment by johnleider** [comment]
fixed in #11568

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ScottKevill** [comment]
For anyone wondering why `dense` still "wasn't working" after this issue was resolved...

Commit d634514 quietly changed the SASS variable `$data-table-dense-row-height` from 24px to `$data-table-dense-header-height` (32px) for a 33% jump in size.

**Comment by yamamoto19730701** [comment]
The following matter, or will there progress?

> For anyone wondering why `dense` still "wasn't working" after this issue was resolved...
> 
> Commit [d634514](https://github.com/vuetifyjs/vuetify/commit/d6345149029e816802ff79eac05b3c61b84b956c) quietly changed the SASS variable `$data-table-dense-row-height` from 24px to `$data-table-dense-header-height` (32px) for a 33% jump in size.
