### ISSUE TITLE
Allow pointer-events on v-checkbox labels

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#1156]
### Steps to reproduce
Use a `v-checkbox` element with a label. You must click directly on the checkbox to change its value.

### Versions
Latest of everything.

### What is expected ?
The label to be clickable.

### What is actually happening ?
The label has `pointer-events` set to `none`, so it cannot be used to toggle the checkbox.

### Reproduction Link
https://codepen.io/anon/pen/ayvOgm

**Comment by johnleider** [comment]
This was a bug introduced, the intended behavior is in fact this.
