### ISSUE TITLE
Feature Request: allow colors in btn-toggle

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#1157]
Currently button toggle supports three type of attributes,
1. text
2. value
3. icon
It is powerful, but it can be even better.
Assuming there is a btn-toggle that has 2 values,  PASS and FAIL. Just by looking at words, it looks intuitive, if there is an icon, it looks even better, but what if on top of that, user can see either green or red? Doesn't it make the btn-toggle even better 👍 

Anyway, this is a feature request. Love Vuetify and hope you guys can take this into consideration :)

**Comment by Ewocker** [comment]
Also, I was wondering since Vuetify now support font-awesome in v-icon and other things, is there a way that we can use animated icon feature of it?
http://fontawesome.io/examples/#animated

**Comment by nekosaur** [comment]
Support for color will come when #1087 is merged and released.

The `fa-spin` / `fa-cog` classes are already supported (`<v-icon>fa-spinner fa-spin</icon>`)
