### ISSUE TITLE
[Feature Request] Predefined allowed-dates in v-date-picker

### ISSUE THREAD

**Issue by denmasyarikin** [vuetifyjs/vuetify#11574]
### Problem to solve
Restriction is probably important for date picker, I know we can now use `allowed-dates` props to achieve restriction input, so i think it will be better if `v-date-picker` has common restriction.

### Proposed solution
provide predefined `allowed-dates` common usege with props
- `allowed-date-inclusive`: Inclusive restriction
- `allowed-date-min`:  you can select minimal as date if  `allowed-date-inclusive`
- `allowed-date-max`: you can select maximal as date if `allowed-date-inclusive`
- `allowed-date-min-today`:  you can select minimal today if `allowed-date-inclusive`
- `allowed-date-max-today`: you can select maximal today if `allowed-date-inclusive`

**Comment by KaelWD** [comment]
There's already `min` and `max` props, and I don't understand what `allowed-date-inclusive` is supposed to do differently.

**Comment by denmasyarikin** [comment]
Ooops, sorry for this, I'm over thinking, I never use min max
