### ISSUE TITLE
[Feature Request] add elevation prop for v-stepper

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#11570]
### Problem to solve
option to increase - decrease or remove `box-shadow` property

### Proposed solution
add `elevation` prop

**Comment by KareemDa** [comment]
Ok I've recognised that i can use `evaluation-` class as described in [CSS Elevation Page in Documentation](https://vuetifyjs.com/en/styles/elevation/)

**Comment by johnleider** [comment]
This is possible as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
