### ISSUE TITLE
Can the Tabs component be made swipable?

### ISSUE THREAD

**Issue by zapping** [vuetifyjs/vuetify#1158]
@johnleider , this is a feature request for the Tabs component.

- What will it allow you to do that you can't do today?
    On mobile display this will be a good to have feature. Similar like the tabs on a browser which can be swiped on a mobile or mouse wheel scrolled on desktop. 

- How will it make current work-arounds straightforward?
    When you have lots of tabs then using the pagination on the Tabs,  #8 Pagination section on the docs page, is not very convenient. Having the swipe option or mouse wheel scroll seems more natural and user-friendly.

- What potential edge cases does it help to avoid?
    There is of-course the menu dropdown option but that will take up a full page section on the mobile. It will be nice to keep the tab page view and then swipe through the tabs to find the required one.

Cheers and thanks.

**Comment by nekosaur** [comment]
The tabs component does support touch on mobile.

**Comment by zapping** [comment]
@nekosaur  Oh!!! Does it need any property to be set? On my page unfortunately it does not show up. I tried opening https://vuetifyjs.com/components/tabs page on mobile. But the #8 Pagination section does not show up on the mobile browser.

**Comment by jacekkarczmarczyk** [comment]
As I understand this issue is about the tabs header, but there should be also possibility to swipe the content (when some bool prop is set to true) - are there any plans for this feature?

**Comment by nekosaur** [comment]
@zapping Use prop `scrollable`. It is documented in docs.

@jacekkarczmarczyk There are currently no plans to allow swipe on content. If you want it to be considered please open a feature request.
