### ISSUE TITLE
[Feature Request] VExpansionPanels v-model should support keys in addition to indexes

### ISSUE THREAD

**Issue by mvirkkunen** [vuetifyjs/vuetify#11586]
### Problem to solve
Using indexes to refer to items can be inconvenient and has issues if items are added/removed dynamically.

### Proposed solution
Add an optional `value` property to the individual VExpansionPanel items and use those values instead of indexes to keep track of which items are expanded via v-model.

**Comment by johnleider** [comment]
Duplicate of #8001

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
