### ISSUE TITLE
[Bug Report] counter-value only works in v-text-field

### ISSUE THREAD

**Issue by mochimochi123** [vuetifyjs/vuetify#11584]
### Environment
**Vuetify Version:** 2.3.0-beta.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.13.6

### Steps to reproduce
add counter-value in v-autocomplete component

### Expected Behavior
counter-value should work the same as in v-text-field

### Actual Behavior
counter-value does not work

### Reproduction Link
<a href="https://codepen.io/mochimochi123/pen/xxZZKRB?editors=1111" target="_blank">https://codepen.io/mochimochi123/pen/xxZZKRB?editors=1111</a>

### Other comments
i did not test this in other components like v-select but i think they may have the same issue too

**Comment by johnleider** [comment]
This issue exists in current v2.2.x as well.

**Comment by ryo-gk** [comment]
How do you think we should handle the input value when the `multiple` prop is used?

**Comment by christianengledercadt** [comment]
v-select has the same bug

**Comment by Shinigami92** [comment]
Glad folks are using my feature that I created for Vuetify :heart:  
So I provided a fix :slightly_smiling_face:
