### ISSUE TITLE
[Feature Request] Add built-in handling for option maps to data table component

### ISSUE THREAD

**Issue by mwgamble** [vuetifyjs/vuetify#11588]
### Problem to solve
Over the years I have created many custom scoped slots just to morph identifiers and boolean values into human-readable labels. For example, I might have a boolean field named "status", and I need to show it to the user as "Enabled" or "Disabled". Right now, I have to do something like this:

```
<template v-slot:item.status="{ value }">
  <template v-if="value">Enabled</template>
  <template v-else>Disabled</template>
</template>
```

Another example is a type of field with multiple values:

```
<template v-slot:item.nextAction="{ value }">
  <template v-if="value === 'action1'">Action 1</template>
  <template v-else-if="value === 'action2'">Action 2</template>
  <template v-else>Action 3</template>
</template>
```

### Proposed solution
Add support for option maps, sort of like what the `<v-select>` component supports.

```
headers: [
  {
    text: "Status",
    value: "status",
    options: [
      { value: true, text: "Enabled" },
      { value: false, text: "Disabled" },
    ],
  },
  {
    text: "Action",
    value: "nextAction",
    options: [
      { value: "action1", text: "Action 1" },
      { value: "action2", text: "Action 2" },
      { value: "action3", text: "Action 3" },
    ],
  },
],
```

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time. Follow #13868 for a proposed replacement in v3. 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
