### ISSUE TITLE
[Feature Request] outlined property - outlined="4" to set border width

### ISSUE THREAD

**Issue by ZermattChris** [vuetifyjs/vuetify#11582]
### Problem to solve
Would be nice to adjust the border size on components via the outlined prop

### Proposed solution
outlined="4"
let the prop accept both the current Boolean default, but also a String|Number to change the border width.

**Comment by KaelWD** [comment]
It can be changed with the `$text-field-outlined-fieldset-border-width` sass variable.

**Comment by ZermattChris** [comment]
> It can be changed with the `$text-field-outlined-fieldset-border-width` sass variable.

Was just a thought that might have made using it a teensy bit easier :-)

**Comment by megaroeny** [comment]
> > It can be changed with the `$text-field-outlined-fieldset-border-width` sass variable.
> 
> Was just a thought that might have made using it a teensy bit easier :-)

But another reason why you want to do it from your SASS is that your design system should have consistent outlined widths if you're going to use them in this way. Just a good practice from design standards.

**Comment by KaelWD** [comment]
Yeah I don't really see a need for this, props are mostly for things you might want to set on a per-component basis, and even then you could use [`custom properties`](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for this.
