### ISSUE TITLE
[Bug Report] V-Slider end-event

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#11581]
### Environment
**Vuetify Version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Create a slider
2. Set up an @ end event
3. Slide the slider and click somewhere on the slider.

### Expected Behavior
Due to the documentation of the end-event ('Slider value emitted at the end of slider movement') I'would expect the event to trigger after a slide, as well as a click on the slide

### Actual Behavior
The event only triggers after the user stops sliding. It does not triggers when you click somewhere on the slider

### Reproduction Link
<a href="https://codepen.io/dom_codes/pen/KKVdmao" target="_blank">https://codepen.io/dom_codes/pen/KKVdmao</a>

**Comment by jblachly** [comment]
Experienced the same issue today.

As `change` event is not documented in the Events list https://vuetifyjs.com/en/components/sliders/ , I tried using `@end` and was missing events when clicking on the slider.

Thanks @Dominic-Marcelino and Vuetify team

**Comment by KaelWD** [comment]
I don't know why `@end` even exists, `@change` already fill that role. For constant updates you can use the `input` event which is also undocumented.

**Comment by MajesticPotatoe** [comment]
Documentation has been updated.
