### ISSUE TITLE
[Bug Report] v-data-table slot item.name call method twice

### ISSUE THREAD

**Issue by denmasyarikin** [vuetifyjs/vuetify#11595]
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Linux x86_64

### Steps to reproduce
- create simple v-data-table
- inside slot item.name call some method
- then log to console
method called twice

### Expected Behavior
method call once

### Actual Behavior
method called twice

### Reproduction Link
<a href="https://codepen.io/denmasyarikin/pen/YzwweKb" target="_blank">https://codepen.io/denmasyarikin/pen/YzwweKb</a>

**Comment by johnleider** [comment]
I'm pretty sure this is not something we can change due to how Vue renders. @nekosaur can chime in and open this issue if disagrees.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
