### ISSUE TITLE
[Bug Report] Rounded and outlined text field does not work correctly in IE11

### ISSUE THREAD

**Issue by KeterSCP** [vuetifyjs/vuetify#11598]
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Add a text field to your app.
2. Make it outlined and rounded

### Expected Behavior
The text field is rounded

### Actual Behavior
The text field is not rounded

### Reproduction Link
<a href="https://codepen.io/Keter_SCP/pen/yLeevqE" target="_blank">https://codepen.io/Keter_SCP/pen/yLeevqE</a>

### Other comments
Figured out that changing "legend" element display to inline will make borders rounded, but there are still some issues with placeholder transformation.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Jaystar-Bee** [comment]
@KeterSCP Did you find a solution for this. I just experience this issue too

**Comment by KeterSCP** [comment]
@Jaystar-Bee to make the text-fields rounded, you can try placing following CSS in your App.vue CSS style:

```css
.v-text-field fieldset > legend {
	display: inline;
}
```

But as I mentioned in the `Other comments` section you will have to adjust legend's position somehow, as it will be slightly shifted down (shown on screen below)
![image](https://github.com/vuetifyjs/vuetify/assets/38229504/532499da-e4e9-4615-bf07-82c8241a1b18)

**Comment by Jaystar-Bee** [comment]
@KeterSCP This

**Comment by KeterSCP** [comment]
@Jaystar-Bee my snippet was for V2, i haven't tried it with V3
