### ISSUE TITLE
[Documentation] Remove reactive prop from v-progress-linear provided examples

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#11597]
### Problem to solve
Removes as the `reactive` prop from the `v-progress-linear` examples as it isn't in the component and it isn't documented.

### Proposed solution
Clean the provided examples

**Comment by MajesticPotatoe** [comment]
Its on the component, but its a computed property.

**Comment by jacekkarczmarczyk** [comment]
oh you're right, I missed that, so additionally to removing the prop we should also add events section to API
