### ISSUE TITLE
[Bug Report] v-data-table item slot does not handle property names in camel-case properly

### ISSUE THREAD

**Issue by tomparle** [vuetifyjs/vuetify#11599]
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Linux x86_64

### Steps to reproduce
(see Codepen)
- use a v-data-table displaying items which has a field "itemCalories"
- use a slot to customize the field rendering, like : `<template #item.itemCalories="{item}"> ... </template>`

### Expected Behavior
The slot should apply to the `itemCalories` field.

### Actual Behavior
The slot is not applied on the `itemCalories`.

### Reproduction Link
<a href="https://codepen.io/tomparle/pen/mdVVLJj" target="_blank">https://codepen.io/tomparle/pen/mdVVLJj</a>

### Other comments
A workaround is to duplicate the field using lowercase, in this example, `itemcalories`, which is not the best but works for now.

**Comment by tomparle** [comment]
Thank you for your time and your kind explanations @jacekkarczmarczyk, I appreciate it !

**Comment by Previesam** [comment]
Good day everyone. Please i am having a slightly different issue from this. Search and filter in v-data-table and v-data-iterator does not work on object properties keys in camel-case.

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
