### ISSUE TITLE
IOS/Mobile Scrolling not smooth on Scrolling Dialog

### ISSUE THREAD

**Issue by aalakoski** [vuetifyjs/vuetify#1159]
### Steps to reproduce
Shows on Vuetify components demo page on IOS/Mobile (iPhone 6 Safari used)

### Versions

Vuetify v0.14.7
IOS Safari on Mobile (iPhone 6 used)

### What is expected ?

Scrolling should be smooth, similar that you get when using -webkit-overflow-scrolling: touch;

### What is actually happening ?

Scrolling seems really janky and slow when scrolling long content.
Also when scrolled to the end of the dialog content, the focus shifts from the dialog to the page body, and starts scrolling the content "behind" the dialog.

### Reproduction Link

https://vuetifyjs.com/components/dialogs
Use the Example 6. of scrolling dialog on ios mobile device

**Comment by aalakoski** [comment]
Tested this a little bit further on my own project. By adding the -webkit-overflow-scrolling: touch; to the v-card-text element on the scrolling demo helps. There is still the issue of loosing focus of the modal content element when scrolled to the end of dialog.

**Comment by johnleider** [comment]
-webkit-overflow-scrolling Is not a standard supported style. Also, I have no idea how to test this. On browserstack everything seems fine.

**Comment by johnleider** [comment]
I have been unable to reproduce this and additional information has not been provided.

**Comment by johnleider** [comment]
I do not have an iPhone. I use browserstack for my testing which is inherently laggy due to the streaming. It's really hard for me to judge a fix for this that will be universal and not just something applied to a single element.

**Comment by jkole** [comment]
As of today this is still an issue and should definitely not be closed. As @aalakoski said in the original issue, to reproduce, just go to the Vuetify docs themselves, open the dialog example page, and click to open the scrollable dialog example. On iOS the content doesn't scroll smoothly at all. And when you scroll to the end of the dialog content, the scroll shifts to the underlying page. You can also open the fullscreen dialog example in landscape mode (to force the content not to fit vertically on the screen) and witness the same horrible scrolling and shift to scrolling the underlying content. @johnleider, I'm confused what you mean by a "fix that will be universal and not just something applied to a single element". The current behavior makes scrolling dialogs essentially unusable on iOS. Seems broken and worth fixing.

**Comment by johnleider** [comment]
@jkole Please do not comment on old issues. If you are still experiencing issues, please create a new issue at https://issues.vuetifyjs.com

**Comment by jkole** [comment]
Will do, thx.

**Comment by skvisli** [comment]
@flybayer @aalakoski Can you please tell me how you fixed it? Did you just add the styling to the v-card-text like so?

`<v-card-text style="-webkit-overflow-scrolling: touch;">`

Can't seem to get it to work.
