### ISSUE TITLE
Fixed sidebar and fixed navbar

### ISSUE THREAD

**Issue by John0x** [vuetifyjs/vuetify#116]
Hey, I want to create a layout like the following:
http://byrushan.com/projects/ma/1-5-2/angular/#/home

(with the sidebar always open)
I would need a fixed sidebar and a fixed navbar for that. I've tried it like this:
````html
<template>
    <v-app top-fixed-navbar left-fixed-sidebar>
        <header>
            <v-navbar fixed>
                <v-navbar-logo>Admin</v-navbar-logo>
            </v-navbar>
        </header>
        <main>
            <v-sidebar id="leftSidebar" router fixed ripple v-bind:items="menuItems"></v-sidebar>
            <v-container fluid>
                <transition mode="out-in">
                    <router-view></router-view>
                </transition>
            </v-container>
        </main>
    </v-app>
</template>
````

But the sidebar is always on the left of the navbar, even though that it should be beneath it. Can this be solved with extra css styling?

**Comment by johnleider** [comment]
Yes, apply margin top to the sidebar equal to the height of the navbar. This will be an option in a future patch.
