### ISSUE TITLE
[Bug Report] v-speed-dial does not stop propagation using a slot-activator

### ISSUE THREAD

**Issue by Thibaud-R** [vuetifyjs/vuetify#11609]
### Environment
**Vuetify Version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4149.0
**OS:** Windows 7

### Steps to reproduce
Click on the speed-dial (blue button).
The click on the v-card container is triggered (label change to 'red' value).
The documentation about the slot-activator of the speed-dial explains that:
--------------
Description
When used, will activate the component when clicked (or hover for specific components). This manually stops the event propagation. Without this slot, if you open the component through its model, you will need to manually stop the event propagation
-------------

The first button with the click.stop modifier does not trigger

### Expected Behavior
A way to avoid the event propagation to the speed-dial container.

### Actual Behavior
The propagation of the click event is not stopped.

### Reproduction Link
<a href="https://codepen.io/thibaud-r/pen/ZEQWWVj" target="_blank">https://codepen.io/thibaud-r/pen/ZEQWWVj</a>

**Comment by KaelWD** [comment]
Workaround: `<v-speed-dial @click.native.stop>`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
