### ISSUE TITLE
[Bug Report] Error: Vuetify is not properly initialized

### ISSUE THREAD

**Issue by anandkumar89** [vuetifyjs/vuetify#11607]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
Clone the repository, in src folder, install node-modules. 
 > npm run build 
 > npm run start.

Same is also hosted on firebase-hosting with functions for server side rendering here https://eigenspace-3ebc0.web.app/

### Expected Behavior
Normal functionality of vue components

### Actual Behavior
functional components - being able to select / dropdown doesn't work.

### Reproduction Link
<a href="https://github.com/anandkumar89/nuxt-vuetify-bug.git" target="_blank">https://github.com/anandkumar89/nuxt-vuetify-bug.git</a>

### Other comments
Using nuxt-vuetify plugin. Module enables TreeShaking by default in production. I've tried with multiple versions of nuxt and vuetify. Once, I got it working but after adding couple more components it broke again. I've tried reinstalling node_modules and that doesn't seem to help. The example in git repository is created using create-nuxt-app.

**Comment by KaelWD** [comment]
That project works fine for me. If this is still happening it's probably something to do with nuxt and doesn't belong here.
