### ISSUE TITLE
Toggle extension mode in extended v-toolbar

### ISSUE THREAD

**Issue by thoss** [vuetifyjs/vuetify#1160]
### Versions
v0.14.7
any browser

### What is expected ?
If there is no componente with the slot="extension" the toolbar is not in the extended mode

### What is actually happening ?
The toolbar stays in the extended Mode even there is no componente using the extension slot

### Reproduction Link
[https://codepen.io/anon/pen/jLPgym](https://codepen.io/anon/pen/jLPgym)

**Comment by johnleider** [comment]
That's how it is designed. This way you can either
