### ISSUE TITLE
[Bug Report] In Test using Jest, V-menu still has "display: none;" rule, after click triggered on v-autocomplete input

### ISSUE THREAD

**Issue by crow7m** [vuetifyjs/vuetify#11605]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
 test('list invisible OK',  async () => {
      let selectlist = wrapper.find('.language-select-list');
      let style = selectlist.attributes().style;
      expect(style).toContain('display: none;') // true, has display none   
      });

    test(list invisible NOT OK', async ()=>{   
      //doesnt work for some reason list still has display none;
      await wrapper.find({name:'v-autocomplete'}).vm.$emit('click');
      await wrapper.vm.$nextTick();
      let styleUpdated = wrapper.find('.language-select-list').attributes().style;
      expect(styleUpdated).not.toContain('display: none;') //false, still has display none
    })

### Expected Behavior
The list should not have display:none; rule(should be visible)

### Actual Behavior
the list still has display none, (not visible)

### Reproduction Link
<a href="https://codepen.io" target="_blank">https://codepen.io</a>

### Other comments
While running the test and trigger("click ") or $emit("click") on v-autocomplete input field both called method from component, (proves that it was triggered, )however the selection list of items  still has display none, so the test won't pass.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by depperm** [comment]
I have a similar issue with a menu not appearing after clicking.
