### ISSUE TITLE
[Documentation] Vuetify Document Translation Error

### ISSUE THREAD

**Issue by devsungmin** [vuetifyjs/vuetify#11604]
### Environment

**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OSX

### Steps to reproduce
바텀 라인(bottom line) 대신 프로그레스 바를 표시할 수도 있습니다. 기본적으로 텍스트 필드와 같은 색상을 가진 불확정 프로그래스를 사용할수도 있고 progress 슬롯을 이용해서 커스터마이즈할 수도 있습니다.

### Expected Behavior
correct documentation

### Actual Behavior
바텀 라인(bottom line) 대신 프로그레스 바를 표시할 수도 있습니다. 기본적으로 텍스트 필드와 같은 색상을 가진 불확정 프로그래스를 사용하 ㄹ수도 있고 progress 슬롯을 이용해서 커스터마이즈할 수도 있습니다.

### Reproduction Link
<a href="https://vuetifyjs.com/ko/components/text-fields/#progress-bar" target="_blank">https://vuetifyjs.com/ko/components/text-fields/#progress-bar</a>

**Comment by jacekkarczmarczyk** [comment]
Translations can be done with crowdin
![image](https://user-images.githubusercontent.com/15625235/84365230-71900580-abd1-11ea-9e42-a4f45733c655.png)

**Comment by devsungmin** [comment]
Thank you. I'll use the function to report.
