### ISSUE TITLE
[Feature Request] Able to sort chips inside an autocomplete component by click and drag 

### ISSUE THREAD

**Issue by justlester** [vuetifyjs/vuetify#11614]
### Problem to solve
I am using chips with draggable property in my autocomplete component. When I try to drag the component it didn't move. I just want to have a sorting feature by dragging the chip in a autocomplete component. 

### Proposed solution
I would like to suggest a new property for the autocomplete component something like "draggable-sort-chips" property that will enable the component to sort the items by dragging and arranging them in the autocomplete field.
I would be glad if there is any workaround for this feature to work. Thanks!

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by adt-hgkim** [comment]
Here is draggable autocomplete

Jsfiddle
https://jsfiddle.net/hakgeumkim/1d4ohjxg/54/
