### ISSUE TITLE
[Feature Request] Ability to disable selection for all rows rather than one-by-one

### ISSUE THREAD

**Issue by mwgamble** [vuetifyjs/vuetify#11610]
### Problem to solve
It's often desirable to disable further interaction with a form or form-like interface when some kind of processing is occurring. For example, the user has selected an item from the table and clicked a button to perform an action on that item. While that action is running, you'd want to prevent the user from modifying the current selection at all.

Right now the only way to achieve that is by modifying the data structure you're using to include an extra key that details whether or not the item should be selectable.

### Proposed solution
Add some kind of `select-enabled` property that blanket enables or disables selection. This will allow selection to be toggled on a table-wide basis, regardless of the data being used to populate the table.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
