### ISSUE TITLE
[Bug Report] Method in v-intersect runs twice

### ISSUE THREAD

**Issue by fafamnzm** [vuetifyjs/vuetify#11611]
### Environment
**Vuetify Version:** 2.3.0-beta.10
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 7

### Steps to reproduce
npm install
npm run serve
go to the pokemon tab
to check the problem look at the scroll or check the console

### Expected Behavior
I expect the loadMore function in the v-intersect to run once.

### Actual Behavior
loadMore function on the v-intersect gets run twice

### Reproduction Link
<a href="https://github.com/fafamnzm/pokemon-vue-apollo" target="_blank">https://github.com/fafamnzm/pokemon-vue-apollo</a>

### Other comments
I cannot add .once to the v-intersect, since I need it to run once every time it gets intersected, since it is an infinite scroll

**Comment by johnleider** [comment]
You should be checking the 3rd argument for if it is actually intersecting. 
![image](https://user-images.githubusercontent.com/9064066/84556269-06d0ee00-ace7-11ea-99ed-24d3094a6b62.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
