### ISSUE TITLE
[Documentation] Documentation messed up on Safari/Mac

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#11618]
### Environment

**Browsers:** Safari 13.1.1
**OS:** Mac OS 10.15.5

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/buttons/

### Expected Behavior
Usage example shouldn't be cut off
![image](https://user-images.githubusercontent.com/16421948/84519262-3139a000-ad15-11ea-8077-cbdbe78ac0a0.png)

### Actual Behavior
Usage example is cut off
![image](https://user-images.githubusercontent.com/16421948/84519280-3860ae00-ad15-11ea-8ada-5bfc0d0ff945.png)

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons/#usage" target="_blank">https://vuetifyjs.com/en/components/buttons/#usage</a>

**Comment by KaelWD** [comment]
This seems to be fixed now.
