### ISSUE TITLE
[Bug Report] V-Slider: Layout Breaks When Position Is Fixed

### ISSUE THREAD

**Issue by Jicol95** [vuetifyjs/vuetify#11617]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Edge 83.0.478.45, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Set position style for v-slider to fixed

### Expected Behavior
Should display as normal

### Actual Behavior
Track disappears and slider is immovable

### Reproduction Link
<a href="https://codepen.io/jicol95/pen/bGEpmKB" target="_blank">https://codepen.io/jicol95/pen/bGEpmKB</a>

### Other comments
I'm unsure this is a bug as currently Vuetify doesn't offer this directly as a prop, unsure if this matters. I have tried this in 2.3.0 as recommended with the same result.

**Comment by KaelWD** [comment]
You have to give it a width too.

**Comment by Jicol95** [comment]
This seems to throw the steps off though?

**Comment by Jicol95** [comment]
> You have to give it a width too.
This seems to throw the steps off though?

**Comment by KaelWD** [comment]
Not sure what you mean

**Comment by Jicol95** [comment]
Apologies, I've misread the documentation around the step prop. Misusing this prop made it seem that a fixed width was impacting the number of ticks in respect to step, min, and max props.

As you said, it does work. (If I could read the docs properly!) 

Thanks for the help
