### ISSUE TITLE
[Bug Report] [v-select] input not allowed to be descendant of role="button"

### ISSUE THREAD

**Issue by awaigand** [vuetifyjs/vuetify#11613]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0, Google Chrome
**OS:** Linux

### Steps to reproduce
Just insert a `<v-select>` anywhere and check the produced code against a  [HTML5 validator](https://validator.w3.org/nu/) or by hand.

### Expected Behavior
Pages with `<v-select>` do not contain an element with `role="button"` with an interactive element, in this case `<input>`, as a descendant. This goes against the [button spec](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html) of HTML5, and thus against the [WCAG 2.1 Robust spec](https://www.w3.org/TR/WCAG21/#parsing), since a role="button" has a Interactive content descendant, which is not allowed. 

### Actual Behavior
They do contain a `role="button"` element with an Interactive content descendant.

### Reproduction Link
<a href="https://jsfiddle.net/9gLx8ykh/2/" target="_blank">https://jsfiddle.net/9gLx8ykh/2/</a>

### Other comments
If you press the 'Parse HTML5' Button in the fiddle, it will submit the fiddle to the [WC3 nu.validator](https://validator.w3.org/nu/). When I tried it error #10 was the error I am talking about.

**Comment by johnleider** [comment]
Paging @phiter

**Comment by KaelWD** [comment]
Yeah I don't think we really care about validators, so long as it works in the browser it's fine.

**Comment by awaigand** [comment]
Note that this is not just a validator issue, it's an accessibility issue since this is part of the WCAG 2.1 Guideline. Which means, technically, Vuetify would disqualify itself for any project that requires accessibility as layed out by the WCAG 2.1 (which means at least all of Europe, and (I think) the US 508 as well). At least that is my understanding of it.

**Comment by MichaelPaulukonis** [comment]
@KaelWD I would agree, as long as you insert "and in screenreaders"

**Comment by pkolenic** [comment]
Is there any plans to fix this in v2x?
My team has components that are getting flagged by other teams when they run axe DevTools because of this.

**Comment by johnleider** [comment]
v3 inputs no longer contain a button role and it's not something we are going to backport.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
