### ISSUE TITLE
I dont want to import all components.....

### ISSUE THREAD

**Issue by Shiroyan** [vuetifyjs/vuetify#1161]
### import all components makes the bundle.js too large
How can i do it?

**Comment by mornir** [comment]
It is currently not possible. But it is already planned. From changelog note of v.13.0: 

> You will soon be able to select only the components you wish to use and get a customized package that only contains your choices.

**Comment by johnleider** [comment]
Upcoming functionality is outlined here https://github.com/vuetifyjs/vuetify/projects/8

**Comment by cars10** [comment]
Any updates on this? The link you provided just shows "This project was closed".

**Comment by jacekkarczmarczyk** [comment]
Use a la carte template: https://github.com/vuetifyjs/a-la-carte
