### ISSUE TITLE
[Bug Report] v-snackbar app prop is always true

### ISSUE THREAD

**Issue by KosratDAhmad** [vuetifyjs/vuetify#11621]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.5

### Steps to reproduce
In the given reproduction link just click on the `open snackbar` you will see the `app` prob is `true` by default and there is no way to turn it to `false` 

### Expected Behavior
The `app` prop should be `false` by default as described in the documentation.  

### Actual Behavior
The `app` prob is `true` by default and there is no way to turn it to `false` 

### Reproduction Link
<a href="https://codepen.io/kosrat-kt/pen/Yzwqbao" target="_blank">https://codepen.io/kosrat-kt/pen/Yzwqbao</a>

**Comment by jacekkarczmarczyk** [comment]
It is `false`
Add `app` prop and you'll see the difference

**Comment by KosratDAhmad** [comment]
I want to overlay the top bar is there a way to do that ??

**Comment by jacekkarczmarczyk** [comment]
If you want to apply it for all top snackbars you can use css, otherwise might be hard
```css
.v-snack--top {
  top: -NNNpx
}
```

**Comment by KosratDAhmad** [comment]
What is `-NNNpx` it doesn't work like that.

**Comment by jacekkarczmarczyk** [comment]
replace NNN with number

**Comment by MajesticPotatoe** [comment]
other option too is using `absolute` prop and setting a `z-index`

**Comment by KosratDAhmad** [comment]
Thank you very much for your help both options will work.

**Comment by dhstack** [comment]
I am having this issue too with an `absolute` footer with a fixed height. Though it seems to be having the problem regardless if it's `absolute` or `fixed`.

Adding `class="pb-0"` to my `v-snackbar` component fixed the issue for me, but it seems like snackbar is not respecting a false `app` property.

**Comment by douglasg14b** [comment]
Same issue here, the snackbar doesn't respect the `app` property at all, it always avoids the top bar or bottom bar. 

How is this not undesirable behavior when it's not controllable?

**Comment by Dylan-Chapman** [comment]
Same issue as other commenters here. The `app` property seems to have no effect and snackbars are always placed along the edge of app components.
