### ISSUE TITLE
[Bug Report] v-virtual-scroll index

### ISSUE THREAD

**Issue by camhart** [vuetifyjs/vuetify#11622]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
Scroll within the virtual scroller.  The index is always reset according to the index of the item within the virtual list.  Ideally there'd be a way to get the index of the item in the array of items passed it.

### Expected Behavior
Index would represent the index of the item within the array of items passed it.

### Actual Behavior
Index represents the item's index within the current virtual scroll context.

### Reproduction Link
<a href="https://codepen.io/camhart/details/mdVPNXj" target="_blank">https://codepen.io/camhart/details/mdVPNXj</a>

**Comment by albertodeago** [comment]
You're right, a wrong index is provided to the slot, thank you. Fixing it soon
