### ISSUE TITLE
IOS / Mobile Safari Floating button icon alignment broken

### ISSUE THREAD

**Issue by aalakoski** [vuetifyjs/vuetify#1162]
### Steps to reproduce
Shows on Vuetify components demo page on IOS/Mobile (iPhone 6 Safari used)
### Versions

Vuetify v0.14.7
IOS Safari on Mobile (iPhone 6 used)
Google Material Icon fonts https://fonts.googleapis.com/icon?family=Material+Icons

### What is expected ?

Icons should be centered to the button.

### What is actually happening ?

Screenshot of the floating buttons on iPhone 6
![img_0837](https://user-images.githubusercontent.com/23035199/28707465-332bee7a-7381-11e7-82d6-371e11b7d572.PNG)

### Reproduction Link

https://vuetifyjs.com/components/buttons

Section 6. Floating buttons on Mobile Safari (iPhone 6 at least)

**Comment by aalakoski** [comment]
could be fixed by maybe adding either margin or padding to **.btn--floating .btn__content** ?

**Comment by johnleider** [comment]
This was fixed with https://github.com/vuetifyjs/vuetify/commit/80e0d2f25d09aff7c21ca795eb7267e702e68a75
Has not been released yet.
