### ISSUE TITLE
[Documentation] Recomendation for activation to translate documentation

### ISSUE THREAD

**Issue by kazuki-komori** [vuetifyjs/vuetify#11625]
### Problem to solve
It seems to document translation is too slow pace...
the reference here => https://crowdin.com/project/vuetify

### Proposed solution
To solve this problem, create the translate contributors page, and give motivation to some puzzled contributors !!

**Comment by MajesticPotatoe** [comment]
The docs are currently in the process of being reworked. We will be updating the contribution guide to more clearly outline all aspects of contributing. In the meanwhile you can contribute manually through the vuetify project or by using in-context translation menu, accessible via the language dropdown in the docs.
![translate](https://user-images.githubusercontent.com/27827979/84558788-4e657300-ad03-11ea-8187-545e4eebcc03.png)

**Comment by kazuki-komori** [comment]
@MajesticPotatoe 
All right 👍 
thank you for your kindness 😄
