### ISSUE TITLE
[Bug Report] v-snackbar content sizing

### ISSUE THREAD

**Issue by qwave** [vuetifyjs/vuetify#11632]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
New sizing props of snackbar (max-width, min-width, etc) not working.

### Expected Behavior
limit content size as described in documentation

### Actual Behavior
Not working

### Reproduction Link
<a href="https://codepen.io/mdxclr/pen/WNrxzpX" target="_blank">https://codepen.io/mdxclr/pen/WNrxzpX</a>

### Other comments
I've checked source code of the component - this props are missed.

**Comment by MajesticPotatoe** [comment]
The props do exist. They are inherited from `v-sheet` which inherits them from `measurable` which is why you don't see them in the `v-snackbar` component.
