### ISSUE TITLE
[Documentation] Text and typography errors

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#11630]
### Environment

**Browsers:** Chrome 84.0.4147.45
**OS:** Windows 10

### Steps to reproduce
Compare [Typography](https://vuetifyjs.com/en/styles/text-and-typography/#typography) section of the vuetify docs to the equivalent [material.io](https://material.io/design/typography/the-type-system.html#type-scale) page. Most of the font weights listed don't match the actual font weights in use. There's no issue with the fonts themselves, just the docs font weights references.

### Expected Behavior
Docs should match actual font weights in use.

### Actual Behavior
They don't match.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/vYLKJPa?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F" target="_blank">https://codepen.io/185driver/pen/vYLKJPa?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F</a>

### Other comments
This table may be of some help in comparing differences noted.

| Font-weight | Docs value | Should be |
|-------------|------------|-----------|
| Heading 3   | 300        | 400       |
| Heading 4   | 300        | 400       |
| Heading 5   | 300        | 400       |
| Heading 6   | 300        | 500       |
| Subtitle 1  | 300        | 400       |
| Subtitle 2  | 300        | 500       |
| Body 1      | 300        | 400       |
| Body 2      | 300        | 400       |
| Button      | 300        | 500       |
| Caption     | 300        | 400       |
| Overline    | 300        | 400       |

**Comment by 185driver** [comment]
@MajesticPotatoe Thanks so much for this fix. Unfortunately, a couple of unneeded changes were made that were already correct, so now they're not. `Heading 1` and `Heading 2` should both have a font-weight of `300`. Thanks for considering.

**Comment by MajesticPotatoe** [comment]
Oops, didnt see them in your table, forgot there was a few extras in there.
