### ISSUE TITLE
[Bug Report] VSnackbar text color in a class not applied

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#11637]
### Environment
**Vuetify Version:** 2.3.0
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.45
**OS:** Windows 10

### Steps to reproduce
Open the codepen and not the snackbar text color.

### Expected Behavior
The text color should be `yellow`, as set in the class using `yellow--text`.

### Actual Behavior
The text color is the default off-white color.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/oNbLmOV" target="_blank">https://codepen.io/185driver/pen/oNbLmOV</a>

### Other comments
I can see the yellow color is available in the `v-snack__content` class, but it is being overridden in `.v-snack__wrapper.theme--dark`.

**Comment by 185driver** [comment]
In reading John's PR [#11542](https://github.com/vuetifyjs/vuetify/pull/11542) regarding upgrades to `v-snackbar`, I noticed the new `content-class` prop. If I move my text classes to there, everything works fine. If that is the official fix for the problem I mention above, this issue can be closed as resolved. 

Some of the snackbar upgrades described in the PR notes should maybe be mentioned in the release notes for v2.3.0 as they are significant and many. Thank you!

**Comment by MajesticPotatoe** [comment]
`content-class` would be the correct use now (or directly styling the content). Will look into updating the release notes.
