### ISSUE TITLE
[Bug Report] 'v-content' is deprecated, use 'v-main' instead.  

### ISSUE THREAD

**Issue by mdkhwajams** [vuetifyjs/vuetify#11634]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.1

### Steps to reproduce
1. npx create-nuxt-app
2. Select veutify from options while creating nuxt app

### Expected Behavior
v-content in default.vue file should be defaulted to v-main

### Actual Behavior
v-content is still used in auto generated nuxt app 

### Reproduction Link
<a href="https://jsfiddle.net/boilerplate/vue" target="_blank">https://jsfiddle.net/boilerplate/vue</a>

**Comment by KaelWD** [comment]
https://github.com/nuxt-community/vuetify-module/pull/344

**Comment by MartinX3** [comment]
@KaelWD I just found this issue ticket, after https://vuetifyjs.com/en/components/application/#default-application-markup confused me
Ther in the layout image `v-content` is used.

**Comment by MajesticPotatoe** [comment]
@MartinX3 that's a different issue that is already reported #11663

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
