### ISSUE TITLE
Nuxt default vuetify project generates v-content

### ISSUE THREAD

**Issue by mdkhwajams** [vuetifyjs/vuetify#11633]
npx create-nuxt-app 
lists out the option to use vuetify, when selected it generates nuxt vuetify project which uses v-conent in default layout. Warning messages are displayed in cmd line stating v-content is deprecated

```
[Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead.  
```

**Comment by DRoet** [comment]
see https://github.com/nuxt-community/vuetify-module/pull/344
