### ISSUE TITLE
[Bug Report] v-text-field input history suggestion doesn't work with @click.prevent

### ISSUE THREAD

**Issue by aydeke** [vuetifyjs/vuetify#11631]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Create `<v-form autocomplete="on">`
2. Add `<v-text-field autocomplete="name">`
2. Add `<v-btn @click.prevent='validate' type='submit'>`

### Expected Behavior
The browser's input history autocomplete functionality should suggest previously entered inputs.

### Actual Behavior
The input history suggestion doesn't work if you add `@click.prevent` to the button.

### Reproduction Link
<a href="https://codepen.io/aydeke/pen/NWxrwNg" target="_blank">https://codepen.io/aydeke/pen/NWxrwNg</a>

**Comment by KaelWD** [comment]
It works for me. Try `@submit.prevent` on the form instead.

**Comment by aydeke** [comment]
With `@submit.prevent` on the form it works, thanks a lot for your help!
