### ISSUE TITLE
[Bug Report] VFileInput do not remove input line when using "hide-input" 

### ISSUE THREAD

**Issue by saroad2** [vuetifyjs/vuetify#11645]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.5

### Steps to reproduce
using the following html:
```html
<div id="app">
        <v-app>
            <NavBar id="nav"/>
            <v-app-bar dense app clipped-left id="bar">
                <v-tab :to="{name: 'Home'}">Home</v-tab>
                <v-tab :to="{name: 'Calendars'}">Calendars</v-tab>
                <v-tab :to="{name: 'Engineers'}">Engineers</v-tab>
                <v-tab :to="{name: 'Groups'}">Groups</v-tab>
                <v-spacer></v-spacer>
                <v-file-input hide-input @change="loadFile"></v-file-input>
            </v-app-bar>

            <v-content>
                <v-container fluid>
                    <router-view></router-view>
                </v-container>
            </v-content>

            <v-footer app>
                <!-- -->
            </v-footer>
        </v-app>
    </div>
```
I expected the `v-file-input` paperclip to be on the right side of the app-bar, but it displayed in the middle. The reason for that is even though the input is hidden use the `hide-input` directive, it still gets space.

I think this is solvable using styling instructions, but I don't know which one. any help would be much appreciated.

### Expected Behavior
Using the `hide-input` should remove the input line entirely and not just make it invisible

### Actual Behavior
`hide-input` do not remove the input line

### Reproduction Link
<a href="https://codepen.io/sagi-shadur/pen/ExPgQdQ?__cf_chl_jschl_tk__=a98c7522b3f87b5a8eefad12c3d59964e5fccf68-1592291728-0-AeO7b2kC-vDAGlorgJYl8s1SfNc6kuxrSlsx2qh4Rkd1qoUF4Xzr7wNT18bPzmtcH1iRt_P1IEtXuOcdk_7B75LG_1iUscEScBYGA-S83GGCM77AqX4BUTtrST_auh1T2yBqEoRRovHBQEjSFIiZQAYn5EkTAXQ07Mtc9BU60jHB6Ncafvwy0V21Oln5CvNVf-n90n3kNGXp-y7zer4VmHXtpWXMbWY6Cvk9jJGxMrRNjwy2OPRfvwpwzrFyv0JFa5USsqYpbY_wHnazhRtzIRiplvC2yqObvxrS72ILEfLmCO13TKO43qn7XNZmCFn_m8jFiQouM-XGkuvoc8-UJ9SFacVBLgfMbp7mEv_LTc3N" target="_blank">https://codepen.io/sagi-shadur/pen/ExPgQdQ?__cf_chl_jschl_tk__=a98c7522b3f87b5a8eefad12c3d59964e5fccf68-1592291728-0-AeO7b2kC-vDAGlorgJYl8s1SfNc6kuxrSlsx2qh4Rkd1qoUF4Xzr7wNT18bPzmtcH1iRt_P1IEtXuOcdk_7B75LG_1iUscEScBYGA-S83GGCM77AqX4BUTtrST_auh1T2yBqEoRRovHBQEjSFIiZQAYn5EkTAXQ07Mtc9BU60jHB6Ncafvwy0V21Oln5CvNVf-n90n3kNGXp-y7zer4VmHXtpWXMbWY6Cvk9jJGxMrRNjwy2OPRfvwpwzrFyv0JFa5USsqYpbY_wHnazhRtzIRiplvC2yqObvxrS72ILEfLmCO13TKO43qn7XNZmCFn_m8jFiQouM-XGkuvoc8-UJ9SFacVBLgfMbp7mEv_LTc3N</a>

### Image
![image](https://user-images.githubusercontent.com/19425795/84744019-5fd8a480-afbb-11ea-9215-f962576caa4c.png)

**Comment by jacekkarczmarczyk** [comment]
That's what this prop is intended to do
Also your reproduction is invalid

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by xdvarpunen** [comment]
I expected same behavior from word "hide-input".  Probably change to "hide-input" to "visible" or something to inform better the behavior. Need way to hide since this component is useful as button with icon 👍
