### ISSUE TITLE
[Bug Report] v-bottom-navigation appears on scroll when disabled

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#11640]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.2

### Steps to reproduce
Scroll the window content

### Expected Behavior
You should be able to scroll and bottom navigation should stay hidden since `input-value=false`

### Actual Behavior
Bottom-navigation pops up. 

### Reproduction Link
<a href="https://codepen.io/thomaskuhlmann/pen/OJMRJYx" target="_blank">https://codepen.io/thomaskuhlmann/pen/OJMRJYx</a>

**Comment by johnleider** [comment]
This issue exists in v2.2.x as well.

**Comment by AbdulhamidZoubi** [comment]
I ran into the same problem, what I've done to get around this is using `v-if` instead of `input-value` and I had to use some transition to replace the default one.
```vue
<v-slide-y-reverse-transition>
    <v-bottom-navigation
              v-if="bottomBar"
             ....
    >
        ......
    </v-bottom-navigation>
</v-slide-y-reverse-transition>
```
