### ISSUE TITLE
[Bug Report] Credit card Chrome autocomplete won't work with v-select

### ISSUE THREAD

**Issue by pavlovskyarto** [vuetifyjs/vuetify#11642]
### Environment
**Vuetify Version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Click on CC Number field and select saved credit card from list.

### Expected Behavior
Exp Month and Exp Year change their values regarding the selected credit card.

### Actual Behavior
Exp Month and Exp Year values haven't changed.

### Reproduction Link
<a href="https://codepen.io/pavlovskyarto/pen/VweKjmZ" target="_blank">https://codepen.io/pavlovskyarto/pen/VweKjmZ</a>

### Other comments
Chrome credit cards manage: Settings - Autofill - Payment methods.
In latest version of Firefox it works properly.

**Comment by Tarabass** [comment]
You have a textfield with a autocomplete prop? And no items?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
