### ISSUE TITLE
dealing with arrays in item-text and item-value

### ISSUE THREAD

**Issue by iansowinski** [vuetifyjs/vuetify#1164]
### Steps to reproduce

Create array of arrays, and based on it create select with template of chosen element of this array and item-text with selected index of array (witch is element of parent array)
Here example: [https://codepen.io/iansowinski/pen/ZJbxYY]( https://codepen.io/iansowinski/pen/ZJbxYY),

### Versions

vue 2.4, vuetify 0.14.6

### What is expected ?

Text-input value should be set as element of array with provided index

### What is actually happening ?

Text input value is set as full array element

### Reproduction Link

 [https://codepen.io/iansowinski/pen/ZJbxYY]( https://codepen.io/iansowinski/pen/ZJbxYY)

**Comment by johnleider** [comment]
This is not how the ```v-select``` items works. The only time you would define an *item-value* or *item-text* is if you are passing an array of objects. While the *items* prop supports an array of primitives, it does _not_ support an array of arrays containing primitives. Is there a real use-case for this?

**Comment by iansowinski** [comment]
It's strange because it worked at 0.13, but if it is considered non-practical, we can treat it as edge-case in my app.

**Comment by johnleider** [comment]
Really? Well that's interesting. While I try to never remove functionality that already exists, I'm not sure if this is something we should strive to support. Is this a common data structure for other select components out in the world?

**Comment by nekosaur** [comment]
Closed due to inactivity

**Comment by iansowinski** [comment]
Sorry, I was on holidays ;)

It's hard to say if its common data structure around world. I assume that multi-dimensional arrays are something common, but team in witch I'm working is quite unexperienced, so maybe they're doing something wrong.

**Comment by nekosaur** [comment]
In my opinion multi-dimensional arrays in `v-select` are not something we should support out of the box. I would suggest you transform the data into a 1D array containing objects.

```javascript
const oneDim = twoDim.map(arr => { return { value: arr[0], text: arr[1] } })
```
