### ISSUE TITLE
[Feature Request] [v-data-table ] Is it possible to use show-select and v-slot:item at the same time? 

### ISSUE THREAD

**Issue by zeroarst** [vuetifyjs/vuetify#11647]
### Problem to solve
I want to use the built-in checkbox feature by using `show-select`, also be able to customize each items without doing v-slot:item.<name>. Currently if I use v-slot:item the checkbox won't show. like this:
![Image](https://i.imgur.com/gAomyLC.png).

If I have a lot columns and if I use v-slot:item.<name>, I have to repeat the same code for multiple times..

### Proposed solution
I am wondering if there is a way to do that?

**Comment by jacekkarczmarczyk** [comment]
With `item` slot - it's not possible, with `item.<name>` - yes

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by zeroarst** [comment]
I ended up implemented checkbox function for myself....would be good to see that feature be added in the future. Thanks for the reply anyway.
