### ISSUE TITLE
[Documentation] Missing documentation about breakpoint service location

### ISSUE THREAD

**Issue by rubinovk** [vuetifyjs/vuetify#11646]
### Environment

**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
In the past one could access `Vue.prototype.$vuetify.breakpont.xyzw` from js code.
From version 2.x this option is not available. This is not documented in migration docs nor in the general documentation https://vuetifyjs.com/en/customization/breakpoints/ 
As discussed in https://discord.com/channels/340160225338195969/361889521815519233/721305708062310483 it is now located under `vuetify.framework.breakpoint.xyzw` on the vuetify object 

The new usage is: 

```js

import vuetify from '@/plugins/vuetify'

if (vuetify.framework.breakpoint.mdAndUp) {
  // works
}
```

### Expected Behavior
Document new usage as 

```js

import vuetify from '@/plugins/vuetify'

if (vuetify.framework.breakpoint.mdAndUp) {
  // works
}
```

### Actual Behavior
Access to `breakpoint` from js is not documented in migration docs nor in the general documentation https://vuetifyjs.com/en/customization/breakpoints/ 

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/breakpoints/ " target="_blank">https://vuetifyjs.com/en/customization/breakpoints/ </a>

**Comment by johnleider** [comment]
The information is located here: https://vuetifyjs.com/en/features/breakpoints/#breakpoint-service-object

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
