### ISSUE TITLE
[Bug Report] Data table custom sort function parameters are returning observer arrays

### ISSUE THREAD

**Issue by menno-ll** [vuetifyjs/vuetify#11653]
### Environment
**Vuetify Version:** 2.3.0
**Last working version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.3

### Steps to reproduce
Create a datatable with a custom sort function using the `custom-sort` prop.
Create your own customSort function under method, accepting the arguments `items`, `index`, `isDesc`.
Then try to strictly compare the `index` parameter with a string, or the `isDesc` parameter with a boolean. It will not work, because the values are both in an observer array.

### Expected Behavior
`index` has a string value of the header value.
`isDesc` has a boolean value

### Actual Behavior
`index` has an observer array value containing a string `["id"]`
`isDesc` has an observer array value containing a boolean `[false]`

### Reproduction Link
<a href="https://codepen.io/menno-ll/pen/dyGpEqq" target="_blank">https://codepen.io/menno-ll/pen/dyGpEqq</a>

**Comment by KaelWD** [comment]
The documented function signature is 
```ts
(
  items: any[],
  sortBy: string[],
  sortDesc: boolean[],
  locale: string,
  customSorters?: Record<string, compareFn>
) => any[]
```

The `multi-sort` prop allows sorting on multiple columns simultaneously, so the sorting function always accepts arrays for consistency. See the default sorting function for reference: https://github.com/vuetifyjs/vuetify/blob/3de45255c51473fde1ffe247bf948edf145688a0/packages/vuetify/src/util/helpers.ts#L285-L329

**Comment by menno-ll** [comment]
Thank you for clearing it up. I see i'm wrong now.
However, as this is not documented in the migration guide from v1.5 to v2 at the moment, it would be great if it could be documented there. Because that's where this problem started for us. We also were not able to spot it, as there were no console errors occuring.

Thanks for the help so far!
