### ISSUE TITLE
Page entirely goes blank when navigating or closing a dialog

### ISSUE THREAD

**Issue by NickolasBoyer** [vuetifyjs/vuetify#1165]
### Steps to reproduce

Take a look at the current documentation with:
- Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Mac OS 10.10.5

### Versions
Vuetify from 13.0 to current is affected, 12.7 and lower not

### What is expected ?
For any content to be visible

### What is actually happening ?
This: https://giphy.com/gifs/xT39D6ZJD6Jvwv4VRS/html5 

### Reproduction Link
https://vuetifyjs.com/components/dialogs

Not to be complaining but this is a pretty serious issue, makes the framework completely unusable, luckily I could roll back to 12.7 but otherwise this would have been pretty sad :(

**Comment by johnleider** [comment]
Can anyone else reproduce this? I only have access to test Mac OS on browserstack which does not produce this particular issue.

**Comment by mstaack** [comment]
@johnleider will check on macbook air when i am home

**Comment by nekosaur** [comment]
Just tried it. Could not reproduce.

Chrome: 60.0.3112.78 (Officiell version) (64 bitar)
Mac OS: 10.10.5

**Comment by johnleider** [comment]
I think one thing we are missing from this is what Vue version are you using @NickolasBoyer

**Comment by NickolasBoyer** [comment]
I'm on v2.3.3 but I encountered the problem reading the documentation too and that is what the gif shows so I guess the question is what version of Vue are you using?

**Comment by johnleider** [comment]
The documentation uses Vuetify@0.14.7 and Vue@2.4.1

**Comment by DedDorito** [comment]
Tested this on latest version of Chrome and macOS 10.12.5 - couldn't reproduce it either.

**Comment by thelolagemann** [comment]
Have you tried with no extensions?

**Comment by NickolasBoyer** [comment]
@thelolagemann yepp :(
guys I'm very sorry, this was caused by the Abstract Browsing extension, no idea what was introduced in v0.13 that it doesn't like but I think we can close this issue since it's a small useless extension, again sorry for waisting your time.
