### ISSUE TITLE
[Bug Report] message area in v-combobox interferes with selecting the control underneath 

### ISSUE THREAD

**Issue by dcaldessa** [vuetifyjs/vuetify#11654]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
1. click in first combobox to set focus
2. click just underneath the textbox of combo box( where the message area is located )

### Expected Behavior
To be able to focus to the next input field

### Actual Behavior
The current focused field stays focused instead of going to the next field

### Reproduction Link
<a href="https://codesandbox.io/embed/quiet-resonance-lqg6z?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/embed/quiet-resonance-lqg6z?fontsize=14&hidenavigation=1&theme=dark</a>

### Other comments
For further explanation see this post which also has a link to an example in codesandbox

[More explanation](https://stackoverflow.com/questions/62294822/vuetify-combobox-issue-when-clicking-on-the-edge-of-another-combobox-or-outside)

Whats the possibility of adding a property that will fully hide the message box when you are not going to use it ?

**Comment by KaelWD** [comment]
The `hide-details` prop removes the message area.
