### ISSUE TITLE
[Feature Request] VSpeeddial should accept buttons in activator slots

### ISSUE THREAD

**Issue by Tarabass** [vuetifyjs/vuetify#11651]
### Problem to solve
Now only buttons and tooltips are getting wrapped into a div with `transition-delay` calculated, based on the numbers of buttons in the speeddial slot. This is happening in `VSpeedDial.ts` at rule `75`, where children are filtered on name.

But when I want to add a `Dialog` with an `activator slot` containing an button, this button doesn't get wrapped in a div with `transition-delay` set. The button is rendered in de `speeddial list`, but is not wrapped into a div and so not respecting the speeddial animations.

### Proposed solution
A solution could be to include `v-dialogs` that contains an `activator slot` with a button. That button could be wrapped into a div with transition-delay as well.

**Comment by johnleider** [comment]
Unfortunately this is being pushed to a labs release later this year. Sorry for an inconvenience.
