### ISSUE TITLE
[Bug Report] Datatable: v-slot:body doesn't respect the responsive design

### ISSUE THREAD

**Issue by diavrank** [vuetifyjs/vuetify#11656]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97, Google Chrome, Safari
**OS:** Mac OS 10.15.4, Windows, Mac OSX, Android, iOS, Linux

### Steps to reproduce
1.- Create a v-data-table component with v-slot:body
2.- Inside of the slot, add the tbody tag.
3.- Inside of the tbody tag add tr tag >td tag 
4.-In each td tag, add as attribute v-text and put as value the item.prop (use any object you want to iterate)
5.- Shrink the screen to a dimension for a cell phone (for example iphone 6) (you can open the chrome inspector)
6.- See the problem how the rows keeps in one line (and it appears a horizontal scrollbar),. Doesn't change the viewport with row__header and row__cell,

Note: You can test it with a datatable without v-slot:body and it work correctly

### Expected Behavior
The datatable should respect the responsive design when the dimensions are for cell phones. It should have the same behavior when I use datatable without v-slot:body. It should add automatically the classes of **v-data-table__mobile-row** , **v-data-table__mobile-row__header** and **v-data-table__mobile-row__cell**.

### Actual Behavior
The rows of the datatable keep as rows and an horizontal scrollbar appears in order to see the rest of the columns.

### Reproduction Link
<a href="https://codepen.io/diavrank/pen/pogNjVp" target="_blank">https://codepen.io/diavrank/pen/pogNjVp</a>

### Other comments
For an alternative solution, I had to add manually the classes **v-data-table__mobile-row** , **v-data-table__mobile-row__header** and **v-data-table__mobile-row__cell** with certain structure with div tags but I don't like it because is much code. It would be great if someone fix this issue. This slot I use it very much because the dblclick event is very useful to access to the edit item view.

**Comment by nekosaur** [comment]
The `body` slot overrides pretty much all internal rendering logic. You will have to re-implement the responsive design yourself. This is not something that can be 'fixed', it is just the nature of how slots work.

I'm not sure what you mean by using the slot because of the dblclick event. We already re-emit double clicks on rows as `@dblclick:row`.

**Comment by diavrank** [comment]
Perfect, I didn't know that `@dblclick:row`  it was already in a release version. I had v2.2.3 and I just have updated to 2.3.1 and it is already present, thank you very much for this feature.
