### ISSUE TITLE
[Bug Report] Bug v-pagination mobile phone

### ISSUE THREAD

**Issue by FahrutdinovOF** [vuetifyjs/vuetify#11662]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.1
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
Create pagination element with many pages.
If total-visible is less than 5, the buttons of the current page are not visible

### Expected Behavior
The current page button is visible

### Actual Behavior
buttons of the current page are not visible

### Reproduction Link
<a href="https://codepen.io/OlegF/pen/jOWVyQa" target="_blank">https://codepen.io/OlegF/pen/jOWVyQa</a>

### Other comments
If total-visible is less than 5, the buttons of the current page are not visible
The current page button is visible

The problem is also relevant for mobile phones when the window width is less than 320 pixels.

**Comment by dashtydit** [comment]
I have the same issue. Have you been able to solve this?

**Comment by robjuz** [comment]
I have the same issue. I have a mobile device with very small screen. I can reduce the size with the SASS variables, but the problem with missing button remains.
