### ISSUE TITLE
[Documentation] Beginner's Guide returns 404

### ISSUE THREAD

**Issue by lextoc** [vuetifyjs/vuetify#11664]
### Environment

**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.4

### Steps to reproduce
Visit the reproduction link to view the issue.

### Expected Behavior
Being able to visit the beginner's guide.

### Actual Behavior
Shows 404 message

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/guide/" target="_blank">https://vuetifyjs.com/en/getting-started/guide/</a>

**Comment by ThomUK** [comment]
FAQ also returns a 404:
[https://vuetifyjs.com/en/introduction/frequently-asked-questions/](https://vuetifyjs.com/en/introduction/frequently-asked-questions/)

**Comment by MajesticPotatoe** [comment]
https://vuetifyjs.com/en/getting-started/guide/ is not a valid link, this was fixed a while ago in the nav drawer
both are likely due to cache. Please clear your cache.

**Comment by ThomUK** [comment]
Thankyou, clearing cache fixes the FAQ for me.
