### ISSUE TITLE
[Feature Request] Add v-select__content class to v-select menu props

### ISSUE THREAD

**Issue by mrfrase3** [vuetifyjs/vuetify#11666]
### Problem to solve
We are currently facing an issue where we want to override the max-height to be x.5 list items on all v-select and v-autocompletes so that users are aware that they can scroll for more options. This is probably an opinionated UX choice, so the easiest way for us to implement it in our codebase is to override it in global css. This is easy for v-autocomplete, as it adds v-autocomplete__content class by default to the v-menu__content element, the same is not done for v-select.

### Proposed solution
Add `v-select__content` to the `contentClass` prop passed to the v-menu component in v-select. This enables people to differentiate a v-select menu from other menus, it also brings it in line with similar functionality done on v-autocomplete.

**Comment by mostafaznv** [comment]
I need this feature too.
