### ISSUE TITLE
Add class to expansion panel container

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1166]
Expansion panel provides css classes for header and body but not for the their container. Adding class to the container makes custom styling easier (actually it makes it possible at all, especially for the active panel)

My proposal is to add "expansion-panel__container" class for the container and "expansion-panel__container--active" for the active container.

I'm working now on the patch

**Comment by johnleider** [comment]
Couldn't you just use the selector ```.expansion-panel > li```?

**Comment by jacekkarczmarczyk** [comment]
How do i target expanded panel?

**Comment by johnleider** [comment]
Can you show me a codepen of what you are trying to do please.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/QMjJZw

This is an example of custom styling the expanded panel

**Comment by johnleider** [comment]
So what is wrong with what you have provided?

**Comment by jacekkarczmarczyk** [comment]
Ok, now I got it, it should be something like this:

https://codepen.io/anon/pen/qXOLqM

So now the only thing that's wrong this solution is that I just personally found it more elegant if these classes are provided by the framework

**Comment by johnleider** [comment]
Now this I like. Would you like to PR this or do you want me to integrate it?

**Comment by jacekkarczmarczyk** [comment]
I've already made w PR (https://github.com/vuetifyjs/vuetify/pull/1167), not sure what to do next so maybe it's better if you integrate it
Sorry, I'm new in github...
