### ISSUE TITLE
[Documentation] Application Component Documentation Layout Image Needs Updated

### ISSUE THREAD

**Issue by KenKodz** [vuetifyjs/vuetify#11663]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
look at layout image labeled "Vuetify Application": https://cdn.vuetifyjs.com/images/layouts/app.png

### Expected Behavior
https://cdn.vuetifyjs.com/images/layouts/app.png should show v-main

### Actual Behavior
https://cdn.vuetifyjs.com/images/layouts/app.png should shows v-content

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/application/" target="_blank">https://vuetifyjs.com/en/components/application/</a>

**Comment by johnleider** [comment]
This is resolved.
