### ISSUE TITLE
[Bug Report] Weird black border around pagination buttons in chrome

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#11660]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Click on a pagination button and a weird black border appears

### Expected Behavior
No weird black border

### Actual Behavior
a weird black border

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/abdBNqy" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/abdBNqy</a>

### Other comments
This a chrome issue, perhaps they recently changed the default outline color

**Comment by ricardovanlaarhoven** [comment]
I'm guessing it has something to do with this: https://support.google.com/chrome/thread/48974735?hl=en

**Comment by MajesticPotatoe** [comment]
It is a chrome thing. #4201 already open regards to the outline in general
