### ISSUE TITLE
[Feature Request] Add hovering property for v-tree-view component's append slot.

### ISSUE THREAD

**Issue by li3p** [vuetifyjs/vuetify#11661]
### Problem to solve
I wanna add some icons when a tree node hovered, for ex: Add `add child/add sibling` icons only when hovered. But cannot implement this with current API. I found there is a `active` slot parameter while `activatable` property is on might helps, but turns out for non-leaf nodes  you cannot active it while  `open-on-click` property is `true`。

### Proposed solution
If there is a `hovering` or `hovered` parameter for v-tree-view component's `append` slots, it will be possible to implement display different icons when a tree node being hovered , of course the `hoverable` property should be set first.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
