### ISSUE TITLE
[Bug Report] v-virtual-scroll resize issue

### ISSUE THREAD

**Issue by eschirtz** [vuetifyjs/vuetify#11665]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.6
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.5

### Steps to reproduce
Create a variable height virtual scroller. (in pen)

Reduce height to cover some elements of a short list. (in pen, via slider)

Increase height. See that elements are not revealed until scrolled. (this is also seen in the demo from the official documentation)

Now repeat the process, but this time increase beyond the "height" of the full list (in pen, slider all the way up)

Since the height is less than the height of the scrollable area, you are unable to scroll, and therefor unable to reveal the hidden elements. 

### Expected Behavior
As height increases, the elements should be re-rendered accordingly

### Actual Behavior
Items are not re-rendered

### Reproduction Link
<a href="https://codepen.io/eschirtz/pen/GRoNBKa" target="_blank">https://codepen.io/eschirtz/pen/GRoNBKa</a>

### Other comments
I haven't looked at the implementation, but I figure this could be solved by watching the height and re-rendering when it changes? 

Thanks for your great work!

**Comment by tavishigupta** [comment]
I've been having the same issue with v-virtual-scroll resize! @eschirtz thank you for reporting this!

**Comment by eschirtz** [comment]
Here is a quick hacky fix I found if anyone runs into this before it's able to be patched, 

Right after resizing the scroll view, just automatically "scroll" the element up then back down. This seems to re-trigger the rendering. Haven't had any issues with this fix yet. 

```ts
    hackyScroll() {
      const virtualScroll = this.$refs.virtualScroll as Vue;
      const el = virtualScroll.$el;
      el.scrollTop += 10;
      el.scrollTop -= 10;
    }

    onResize() {
      // your resize logic here
      this.hackyScroll();
    },
```
