### ISSUE TITLE
[Bug Report] VSnackbar hide doesn't work with $nextTick()

### ISSUE THREAD

**Issue by kosratdev** [vuetifyjs/vuetify#11671]
### Environment
**Vuetify Version:** 2.3.0
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Mac OS 10.15.5

### Steps to reproduce
Open the reproduction link and click on the **Open Snackbar** at the first time it shows the snackbar but second time when you click on **Open Snackbar** I want to hide then show the snackbar again.

### Expected Behavior
Hide snackbar when nexttick completed show snackbar again.

### Actual Behavior
The snackbar doesn't work with nexttick when you hide manually and then want to show again.

### Reproduction Link
<a href="https://codepen.io/kosrat-kt/pen/qBbqwOe?editors=1010" target="_blank">https://codepen.io/kosrat-kt/pen/qBbqwOe?editors=1010</a>

**Comment by KosratDAhmad** [comment]
And also it doesn't work with VDialog, for example, I want to do something after a dialog closed but doesn't work

**Comment by cnayan** [comment]
You need delay. I added 800 ms delay for example.

https://codepen.io/cnayan/pen/mdVmWOb?editors=1011

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
