### ISSUE TITLE
[Bug Report] [Vuetify] Translation key "dataTable.ariaLabel.***" not found in fallback

### ISSUE THREAD

**Issue by adrielwerlich** [vuetifyjs/vuetify#11676]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
Regular initialization of vuetify inside main.js vue project

```
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import { pt } from 'vuetify/es5/locale/pt'

Vue.use(Vuetify, {
  directives: {
    Ripple,
  },
  lang: {
    locales: {
      pt,
    },
    current: 'pt',
  },
})

const opts = {}

const vuetify = new Vuetify(opts)

new Vue({
  router,
  store,
  vuetify,
  render: h => h(App),
  mounted() {
    this.$vuetify.lang.defaultLocale = 'pt'
    this.$vuetify.lang.current = 'pt'
  },
}).$mount('#app')
```

I´m trying to use the data-table component

### Expected Behavior
To translate to the specified language

### Actual Behavior
Not translating and shouting the error messages:
console.ts?522c:38 [Vuetify] Translation key "dataTable.ariaLabel.****" not found in fallback

### Reproduction Link
<a href="https://codepen.io/adrielwerlich/pen/MWKJaRV" target="_blank">https://codepen.io/adrielwerlich/pen/MWKJaRV</a>

Console

![image](https://user-images.githubusercontent.com/20656722/85062838-965f1c80-b17f-11ea-8cf7-0927772a9c09.png)

![image](https://user-images.githubusercontent.com/20656722/85062877-aaa31980-b17f-11ea-8d53-0ba85b031812.png)

As it´s possible to see in the image group, category and $vuetify.dataTable.*** is not being properly translated!!!

**Comment by MajesticPotatoe** [comment]
your import is incorrect.
per docs: `import pt from 'vuetify/es5/locale/pt'` not `import { pt } from 'vuetify/es5/locale/pt'`

**Comment by adrielwerlich** [comment]
> your import is incorrect.
> per docs: `import pt from 'vuetify/es5/locale/pt'` not `import { pt } from 'vuetify/es5/locale/pt'`

even if with this modification continue not working

**Comment by MajesticPotatoe** [comment]
lang declaration should be in `opts`

eg:

```
Vue.use(Vuetify);
const opts = {
  lang: {
    locales: {
      pt,
    },
    current: 'pt',
  },
}
const vuetify = new Vuetify(opts);
```

please review the documentation on this matter at https://vuetifyjs.com/en/customization/internationalization/

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
