### ISSUE TITLE
[Documentation] v-banner property

### ISSUE THREAD

**Issue by ivliev** [vuetifyjs/vuetify#11670]
### Environment

**Browsers:** Firefox 77.0
**OS:** Windows 10

### Steps to reproduce
The property "mobile-breakpoint" is not correct.

### Expected Behavior
Please change to "mobile-break-point".

### Actual Behavior
no

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/banners/#api" target="_blank">https://vuetifyjs.com/en/components/banners/#api</a>

**Comment by KaelWD** [comment]
`mobile-breakpoint` is correct:

https://github.com/vuetifyjs/vuetify/blob/5533b030a3f892abed057dbb00946d57352e6751/packages/vuetify/src/mixins/mobile/index.ts#L10-L11
