### ISSUE TITLE
[Bug Report] "Overline" font size changed

### ISSUE THREAD

**Issue by eschirtz** [vuetifyjs/vuetify#11674]
### Environment
**Vuetify Version:** 2.3.1
**Last working version:** 2.3.0
**Vue Version:** 2.6.6
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.5

### Steps to reproduce
Update Vuetify. This can be seen at https://vuetifyjs.com/en/styles/text-and-typography/

"Overline" height says it should be 0.625 rem but is 0.75 rem in Chrome Dev Tools inspector. You can also see that "Overline" is noticeably larger than "caption", which was not the case previously

### Expected Behavior
Overline is correct size

### Actual Behavior
It is not

### Reproduction Link
<a href="https://github.com/eschirtz/foobar" target="_blank">https://github.com/eschirtz/foobar</a>

**Comment by jacekkarczmarczyk** [comment]
changes in typography classes were reverted in https://github.com/vuetifyjs/vuetify/commit/8c650e48a53ac32ba44bd16d3f853a8b07810ff3 but documentation hasn't been updated

**Comment by 185driver** [comment]
@jacekkarczmarczyk as part of John's revert, at least for the `overline` type, he actually did change it away from the [change](https://github.com/vuetifyjs/vuetify/commit/8c650e48a53ac32ba44bd16d3f853a8b07810ff3#diff-744fa418d20023343556716fcdf13fbbR214) and away from the [original](https://github.com/vuetifyjs/vuetify/commit/e83a203c8dc13c02eb75792d1de9404c8e998798#diff-744fa418d20023343556716fcdf13fbbR200) too. So it's different yet again (tecnically not a revert, lol), but overline now matches [example 1](https://material-components.github.io/material-components-web-catalog/#/component/typography) of the md2 spec, which it didn't match before. But you're right the docs need to reflect that change even though the change itself is not a bug.

|overline|size   |weight|line-height|letter-spacing|
|--------|-------|------|-----------|--------------|
|original|.625rem|400   |1rem       |.1666666667em |
|change  |.625rem|normal|normal     |0.09375rem    |
|revert  |.75rem |500   |2rem       |.1666666667em |
