### ISSUE TITLE
[Bug Report] Tab component transitions with swipe with :touchless="true"

### ISSUE THREAD

**Issue by satianoCantana** [vuetifyjs/vuetify#11678]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
* Add tabs component to page
* Use property :touchless="true" on v-tab-item 
* Swiping with finger still causes transition

### Expected Behavior
disable tab change on finger swipe

### Actual Behavior
tab chage still occurs

### Reproduction Link
<a href="https://codepen.io/cassianosantana/pen/qBbRNOY" target="_blank">https://codepen.io/cassianosantana/pen/qBbRNOY</a>

### Other comments
The solution to this issue #2043 says  it should work but it does not.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/2043#issuecomment-334748921

v-tab-item does not have a touchless prop either.
