### ISSUE TITLE
[Feature Request] Detect Click on Day Div

### ISSUE THREAD

**Issue by ValDewez** [vuetifyjs/vuetify#11673]
### Problem to solve
Not being able to click on the day div instead of clicking exactly on the number (would be more user friendly)

### Proposed solution
Add an event to catch the click on the whole div instead of number

**Comment by ValDewez** [comment]
Same problem asked by user in 2019 : https://github.com/vuetifyjs/vuetify/issues/7377

"The problem with the click:day is that you need to click exactly on the number. This is highly unpractical to a user who is not familiar with vuetify calendar. "

**Comment by KaelWD** [comment]
An event is emitted, `click:day`. When you click on the date's day of the month you get `click:date`.

If it's not behaving this way, please provide a codepen.

**Comment by ValDewez** [comment]
I know, the requested feature was to be able to detect your click on the whole div not only on the date's dat of the month.

Like an extra option or an event.

**Comment by KaelWD** [comment]
You're going to have to clarify what you mean by "the div", there's already events for nearly every part of the calendar. 

https://codepen.io/kaelwd/pen/wvMgJNm

**Comment by ValDewez** [comment]
Sure, I mean the square for a day in month view
In my screenshot, the square where my mouse is here is not clickable because you can only click on the date's day not on the square's day.

(Exemple with mouse on the square)
[https://goopics.net/i/VNgjm](url)

**Comment by KaelWD** [comment]
Works for me, clicking anywhere in the day fires `click:day`

https://codepen.io/kaelwd/pen/GRorEoL

**Comment by ValDewez** [comment]
Is there any reason why the white part (on your screen) is not clickable ?

**Comment by KaelWD** [comment]
It's clickable, it just doesn't have a different cursor for some reason. Both the white and the blue areas trigger `click:day`

**Comment by ValDewez** [comment]
Just checked on your codepen, only the top half is clickable, bot half does not trigger event

**Comment by jacekkarczmarczyk** [comment]
You mean you don't see logs in console when you click there?

**Comment by ValDewez** [comment]
Just checked on your codepen, yeah its working thanks just no cursror but log is here !

Going to close the issue! thanks!
