### ISSUE TITLE
[Bug Report] Cannot build Vue + Vuetify (a la carte) + Typescript project

### ISSUE THREAD

**Issue by borgytan** [vuetifyjs/vuetify#11683]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Edge 83.0.478.54
**OS:** Windows 10

### Steps to reproduce
Create a new vue app using CLI (i used 4.4.4), with TypeScript support (my app also has PWA, Vuex, Router support, but those are probably irrelevant to this case).
Add vuetify to the project with a la carte support.
Add the following to tsconfig.json, as mentioned in https://github.com/vuetifyjs/vue-cli-plugins/issues/112#issuecomment-562935079:
```
"types": [
      "webpack-env",
      "vuetify"
    ],
"typeRoots": [
    "./node_modules/@types",
    "./node_modules/vuetify/types"
  ]
```

run "npm run build" to build

### Expected Behavior
should build successfully.

### Actual Behavior
build fails with error:

```
 WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[16] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[16] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.
```

### Reproduction Link
<a href="https://github.com/borgytan/pgc-dashboard" target="_blank">https://github.com/borgytan/pgc-dashboard/tree/master/frontend-vue</a>

**Comment by KaelWD** [comment]
Can't reproduce, the provided repo builds fine. Try deleting node_modules

**Comment by borgytan** [comment]
> Can't reproduce, the provided repo builds fine. Try deleting node_modules

apologies I forgot to push the code. please try rebuilding again.

**Comment by KaelWD** [comment]
This is not a valid plugin: https://github.com/borgytan/pgc-dashboard/blob/a9a7171134517c8556ae6a008f6da5ed21e5e2e2/frontend-vue/vue.config.js#L4-L10

**Comment by borgytan** [comment]
> This is not a valid webpack plugin: https://github.com/borgytan/pgc-dashboard/blob/a9a7171134517c8556ae6a008f6da5ed21e5e2e2/frontend-vue/vue.config.js#L4-L10

thank you that fixed the issue. it seems that when i added vuetify, some of my code in vue.config.js was overwritten and I just put back the original code. thanks again for the quick help! :)
