### ISSUE TITLE
[Documentation] Some documentation appears to be broken.

### ISSUE THREAD

**Issue by mikewalpole-systemc** [vuetifyjs/vuetify#11682]
### Environment

**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
Navigate to the repro link.

### Expected Behavior
Document has expected content and is formatted correctly.

### Actual Behavior
This particular doc has lots of placeholder labels in it e.g. GettingStarted.ReleasesAndMigrations.vueCliAlert1.

Additionally, I am sure until recently (say, a couple of weeks ago) there was a detailed list of changes in this doc which could be used to perform a migration from 1.x to 2.x - where has this gone?

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/releases-and-migrations/" target="_blank">https://vuetifyjs.com/en/getting-started/releases-and-migrations/</a>

**Comment by KaelWD** [comment]
Can you open the network tab in devtools, reload the page, then show a screenshot of it scrolled to the top like this? 
![image](https://user-images.githubusercontent.com/16421948/85110445-4606be00-b256-11ea-8f64-58db862928d8.png)

**Comment by jacekkarczmarczyk** [comment]
https://dev.vuetifyjs.com/en/getting-started/releases-and-migrations/ works fine

**Comment by KaelWD** [comment]
Yeah that's why I asked for the screenshot, there's been quite a few people with caching issues recently.

**Comment by mikewalpole-systemc** [comment]
Yes, it's caching - CTRL-F5 brought the content down again. I apologise for wasting time here.
