### ISSUE TITLE
[Bug Report] DataTable's current page still resets to 1 when sorting. disable-page-reset not working

### ISSUE THREAD

**Issue by ndorofeeva** [vuetifyjs/vuetify#11688]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
1. Go to second page
2. Sort any column

### Expected Behavior
Data sorted, but current page stays the same

### Actual Behavior
Data sorted, page resets to 1.

### Reproduction Link
<a href="https://codepen.io/ndorofeeva/pen/qBbRYyE?editors=1010" target="_blank">https://codepen.io/ndorofeeva/pen/qBbRYyE?editors=1010</a>

### Other comments
According to issue [3766](https://github.com/vuetifyjs/vuetify/issues/3766) prop disable-page-reset has been added to resolve this. But it is not working now (I assume it's because of pagination prop that is now deprecated).
Is there any workaround to this? Or maybe undocumented functionality

**Comment by Lisible** [comment]
I'm having the same issue.

**Comment by Larsson83** [comment]
Will this be fixed?

**Comment by mavyfaby** [comment]
Any updates?
