### ISSUE TITLE
[Bug Report] 'veutify@latest' is not found in the npm registry

### ISSUE THREAD

**Issue by Giri-Rokz** [vuetifyjs/vuetify#11689]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
npm i veutify

### Expected Behavior
Veutify to be installed in local machine

### Actual Behavior
error 404 Not Found - GET https://registry.npmjs.org/veutify - Not found

### Reproduction Link
<a href="https://github.com/Giri-Rokz/nodeProject.git" target="_blank">https://github.com/Giri-Rokz/nodeProject.git</a>

### Other comments
Unable to download and install Veutify as I'm facing a 404 error while installing it. Please help me to install Vuetify.

**Comment by MajesticPotatoe** [comment]
that would be because this is vuetify
<https://registry.npmjs.org/vuetify>
