### ISSUE TITLE
[Bug Report] Error occured when I run "npm run build" command

### ISSUE THREAD

**Issue by TabrizGulmemmedov** [vuetifyjs/vuetify#11680]
![err-1](https://user-images.githubusercontent.com/40621376/85106103-aed14480-b21c-11ea-99c3-337942eecd13.png)
![err-2](https://user-images.githubusercontent.com/40621376/85106110-b09b0800-b21c-11ea-84f6-65ecc8bd17b6.png)
![err-3](https://user-images.githubusercontent.com/40621376/85106113-b264cb80-b21c-11ea-83c5-573a0c0588e2.png)
![err-4](https://user-images.githubusercontent.com/40621376/85106117-b42e8f00-b21c-11ea-8eb4-785bbfed094a.png)

### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
asda

### Expected Behavior
asdas

### Actual Behavior
asda

### Reproduction Link
<a href="https://github.com/eschirtz/foobar" target="_blank">https://github.com/eschirtz/foobar</a>

### Other comments
asd

**Comment by KaelWD** [comment]
Import from lib or dist, not src.

**Comment by TabrizGulmemmedov** [comment]
> Import from lib or dist, not src.

I did not understand what was meant.

**Comment by KaelWD** [comment]
You are importing something from `vuetify/src`

**Comment by TabrizGulmemmedov** [comment]
> vuetify/src

Thanks
