### ISSUE TITLE
[Bug Report] Cannot read property 'extend' of undefined at Module../src/mixins/themeable/index.ts (vuetify.js:39389)

### ISSUE THREAD

**Issue by hwagterveld** [vuetifyjs/vuetify#11685]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
In my webapp I use bootstrap-vue as well as Vuetify. Both libraries are imported as follows:

import BootstrapVue from 'bootstrap-vue';
import vuetify from '@/plugins/vuetify';

When running my app, I get this error in the console of the browser:

Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module../src/mixins/themeable/index.ts (vuetify.js:39389)
    at __webpack_require__ (vuetify.js:30)
    at Module../src/components/VApp/VApp.ts (vuetify.js:395)
    at __webpack_require__ (vuetify.js:30)
    at Module../src/components/VApp/index.ts (vuetify.js:478)
    at __webpack_require__ (vuetify.js:30)
    at Module../src/components/index.ts (vuetify.js:31512)
    at __webpack_require__ (vuetify.js:30)
    at Module../src/index.ts (vuetify.js:33295)
    at __webpack_require__ (vuetify.js:30)

Seems to be a problem to use bootstrap-vue and vuetify together? How to fix this (and still use both UI component frameworks)? 

### Expected Behavior
Vuetify and bootstrap-vue can run together without problems

### Actual Behavior
It seems that you need to make a choice between Vuetify and bootstrap-vue

### Reproduction Link
<a href="https://codesandbox.io/s/hopeful-bas-040dl" target="_blank">https://codesandbox.io/s/hopeful-bas-040dl</a>

**Comment by KaelWD** [comment]
That means vue is missing or not loaded properly.

**Comment by hwagterveld** [comment]
When I remove Vuetify from import (and only bootstrap-vue is used), there is no problem and my app runs fine.

**Comment by KaelWD** [comment]
Bootstrap doesn't use Vue.extend()

Your sandbox loads fine, see #4068 for some common problems that might be similar.

**Comment by KaelWD** [comment]
This issue will be closed if you cannot reproduce the error.

**Comment by hwagterveld** [comment]
The cause of this error was an additional import of Vuetify in Index.html, which caused an additional load in which vue was missing.

    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>

Removing this line fixed the problem.

**Comment by KaelWD** [comment]
Thanks for the update.

**Comment by venkatesh0705** [comment]
facing same issue in ionic vue

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
