### ISSUE TITLE
[Feature Request] Sticky progress linear

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11693]
### Problem to solve
Currently the progress linear only supports being placed fixed or absolute through properties. Using fixed is problematic when you don't want to position it according to the main viewport but inside a sub element. Absolute means that when it's placed in a scrollable area it can be scrolled out of sight.
Using position sticky requires custom styles. 

### Proposed solution
Add a sticky property. 
This would make it easy to place it at the top of an scrollable element on the page and keep it in sight when scrolling.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
