### ISSUE TITLE
v-edit-dialog broken

### ISSUE THREAD

**Issue by smxsm** [vuetifyjs/vuetify#1169]
### Steps to reproduce
Just go to the official documentation and try the datatable component with inline text editing.
Edit a value in the "#5 Search with custom page text" example data table and try to save it.

### Versions

Vue 2.4.2, VuetifyJS v.0.14.7 on Chrome Browser Version 60.0.3112.78, Mac OS 

### What is expected ?

I expect changed values to be updated correctly.

### What is actually happening ?

After editing a value, the field says "isTrusted: true" in JSON format, the user input is lost, and the field can't be saved since the value is invalid.

![image](https://user-images.githubusercontent.com/1737182/28728497-2d7d8874-73c9-11e7-81bc-68c9b039596a.png)

### Reproduction Link

See here: https://vuetifyjs.com/components/data-tables

**Comment by johnleider** [comment]
With the new listeners from vue@2.4 this example needed to be updated.

**Comment by smxsm** [comment]
Hi, not sure that's correct, if I change that I get:

> TypeError: Cannot read property 'value' of undefined

Here is my changed line:

> v-on:change="e => props.item.externalId = e.target.value"

Running on Vue 2.4.2 and Vuetify 0.14.7.

**Comment by vuras** [comment]
I have stumbled upon the same issue as smxsm. Getting 

> TypeError: Cannot read property 'value' of undefined
