### ISSUE TITLE
[Bug Report] v-data-tables locale does not work for footer

### ISSUE THREAD

**Issue by UmbrellaCorpAgent** [vuetifyjs/vuetify#11691]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Linux x86_64

### Steps to reproduce
Already set up, should technically work as it is

### Expected Behavior
Translate the footer ('Rows per page' and 'of' to 'Lignes par page' and 'de' or similar).

### Actual Behavior
Doesn't translate footer

### Reproduction Link
<a href="https://codepen.io/UmbrellaCorpAgent/pen/PoZWyJB?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F" target="_blank">https://codepen.io/UmbrellaCorpAgent/pen/PoZWyJB?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F</a>

### Other comments
I didn't personnaly needed to translate the rest of the data-table, but apparently it works. So it's basically only the footer / row per page part that doesn't get translated.

**Comment by MajesticPotatoe** [comment]
your reproduction link doesnt actually show us what your locale file `fr-CA` looks like.
data table options for those 2 pieces are in there this is what the default template for it looks like:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/locale/en.ts

where you would be targeting `dataTable.itemsPerPageText` and `dataFooter.pageText`

**Comment by jacekkarczmarczyk** [comment]
Also:

![image](https://user-images.githubusercontent.com/15625235/85174470-bcff7f00-b275-11ea-83e8-bb7b01c0117c.png)

**Comment by quiteqiang** [comment]
Something wired happened to me is the data-tables footer not showing me "Rows per page". It is showing me"$vuetify.dataTable.itemsPerPageText"

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
