### ISSUE TITLE
[Documentation] Jobs board does not support dark theme

### ISSUE THREAD

**Issue by josh-hemphill** [vuetifyjs/vuetify#11694]
### Environment

**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
Turn on dark theme

### Expected Behavior
Title text should remain black or background should darken

### Actual Behavior
Title turns white and background remains white, making the title invisible

### Reproduction Link
<a href="https://vuetifyjs.com/en/jobs/for-vue/" target="_blank">https://vuetifyjs.com/en/jobs/for-vue/</a>

**Comment by MajesticPotatoe** [comment]
This is resolved in docs-next release
