### ISSUE TITLE
[Documentation] VCalendar *:event documentation missing

### ISSUE THREAD

**Issue by tobiaskohlbau** [vuetifyjs/vuetify#11703]
### Environment

**Browsers:** Edge 83.0.478.50
**OS:** Windows 10

### Steps to reproduce
Visit the current api-explorer and search for v-calendar and click on events. The documentation for each calendar event of suffix `:event` is missing.  For e.g. `mousedown:event` or `click:event`.

### Expected Behavior
The event handlers for calendar events should be shown.

### Actual Behavior
Looks like every element which ends with `:event` is not shown within the api explorer.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/api-explorer/" target="_blank">https://vuetifyjs.com/en/components/api-explorer/</a>

### Other comments
The documentation exists in the sourcecode see for e.g. https://github.com/vuetifyjs/vuetify/blob/265fa3192e6fe11468474a0b79af011c36178a5d/packages/docs/src/lang/en/components/Calendars.json#L123.

**Comment by MajesticPotatoe** [comment]
They just need to be added to api-gen map file

**Comment by MajesticPotatoe** [comment]
resolved
