### ISSUE TITLE
[Bug Report] Theme primary color differs from original color

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#11705]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create two identical components and give one with class `primary`, the other with `blue` or whatever the primary theme color is set to. The differences get more extreme the lighter or darker they get.

### Expected Behavior
Expect primary and original colors to be equal

### Actual Behavior
Colors are different, not close at all.

### Reproduction Link
<a href="https://codepen.io/jaesung2061/pen/qBbmdvR?editors=1010" target="_blank">https://codepen.io/jaesung2061/pen/qBbmdvR?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/3389#issuecomment-368874020

Use 
```js
primary: colors.brown,
```

instead of

```js
primary: colors.brown.base,
```
