### ISSUE TITLE
[Bug Report] V-main doesnt compile on production

### ISSUE THREAD

**Issue by Vterebenin** [vuetifyjs/vuetify#11708]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Linux x86_64

### Steps to reproduce
1. create sample nuxt-vuetify project
1. as warning said change v-content to v-main
2. try to compile app to production trough yarn build
3. see the compiled version of the app, look to html code and check as v-main vuetify tag compiles to sample html v-main tag, which is obviously not the right thing to do. 

### Expected Behavior
v-main should properly compile to production

### Actual Behavior
v-main compiles to plain html tag

### Reproduction Link
<a href="https://codesandbox.io/s/charming-meadow-9vc2c" target="_blank">https://codesandbox.io/s/charming-meadow-9vc2c</a>

**Comment by jacekkarczmarczyk** [comment]
I can't see usage of `v-main` or `v-content` or anything vuetify related in your reproduction

**Comment by Vterebenin** [comment]
My bad. Didnt saved sandbox. 
You can see that i have v-main wrapper in default layout.
https://codesandbox.io/s/charming-meadow-9vc2c?file=/layouts/default.vue

**Comment by jacekkarczmarczyk** [comment]
And can you point where you are installing vuetify? I don't see you're using `@nuxtjs/vuetify` or anything vuetify related in package.json

**Comment by Vterebenin** [comment]
Im sorry for my stupidity!
I was thinking that codesandbox automaticly adding my devdeps. now its on the list of dependencies.

**Comment by jacekkarczmarczyk** [comment]
Adding vuetify to `package.json` is not enough
https://github.com/nuxt-community/vuetify-module
