### ISSUE TITLE
[feature request] v-text-field should capture keystrokes like backspace and enter

### ISSUE THREAD

**Issue by pwang2** [vuetifyjs/vuetify#1170]
- What will it allow you to do that you can't do today?
   > As pen here(https://codepen.io/pwang2/pen/xLZzvw), to create a feature like select2, we could use the combination of chip and text-field. 
  - How will it make current work-arounds straightforward?
   > By exposing the enter and delete keystroke, we could make things more straight forward like using a enter instead of detection of comma here to break word. using backspace to delete the existing chip here.
  - What potential bugs and edge cases does it help to avoid?
   > This is just an example by which we could benefit from to have the keystrokes event. Also, this will make v-tex-field behave more like the input control in HTML which is familiar to everyone.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by pwang2** [comment]
@johnleider Thanks for reminder. I have corrected my request as per the template.  Please let me know if anything else needed.

**Comment by jchatard** [comment]
Yeah, I would a similar use case. I'm using Google Maps Places Javascript, which gives autocomplete suggestion for locations.

Upon Enter, my form is submitted, but I would like to select the first suggestion of the autocomplete.

**Comment by oodgaard** [comment]
+1

**Comment by KaelWD** [comment]
Is this still an issue? You can use `@keydown.native` to listen for a certain keypress: https://codepen.io/anon/pen/eeYgGg

Additionally, the codepen can now be done natively by vuetify with `<v-select chips tags>`

**Comment by pwang2** [comment]
@KaelWD exactly what we need.  Thanks. closing!
