### ISSUE TITLE
Weekly Calendar forces scroll bar on last day

### ISSUE THREAD

**Issue by kevinstory** [vuetifyjs/vuetify#11710]
I'm using the default v-calendar component and it's forcing a scroll bar on the far right day when viewing in weekly mode. This is generating an offset of the days which make them misaligned from the header. I've tried forcing this off in the scoped style with offset-y: hidden but no luck. Any ideas?

```
<v-calendar
            class="mb-3"
            ref="calendar"
            :first-interval="8"
            :interval-minutes="60"
            :interval-count="10"
            :weekdays="[1, 2, 3, 4, 5]"
            :events="events"
            type="week"
          >
</v-calendar>
```

![vuetify_calendar_scrollbar](https://user-images.githubusercontent.com/904587/85425030-ab082f80-b546-11ea-9831-4694282f2c07.png)

**Comment by ferasdiab** [comment]
@kevinstory did you find any answer for this issue?

**Comment by khmob** [comment]
Did anyone fin any answer to this?
