### ISSUE TITLE
[Feature Request] Feature Discovery

### ISSUE THREAD

**Issue by eduardougolini** [vuetifyjs/vuetify#1171]
<h1>What will it allow you to do that you can't do today?</h1>

- Feature discovery is a feature that can be used in several scenarios like showing help for users who are entering in your website for the first time, showing new features added in some upgrade of your system or like a help system for your application
- Feature Discovery is implemented on Materializecss framework and can be found here: http://materializecss.com/feature-discovery.html

<h1>What potential bugs and edge cases does it help to avoid?</h1>
 
 - Just an improvement for the framework

**Comment by TheWaffleDimension** [comment]
Any chance this'll be implemented any time soon?

**Comment by aggarwaldev** [comment]
@johnleider This was planned for v1.5 but updated roadmap do not talk about it. Can you please update us?

**Comment by MajesticPotatoe** [comment]
@aggarwaldev This is slated for 2.0 release. Closing in favor of #5987

**Comment by creativenoobie** [comment]
Found something related: https://github.com/MyBibHQ/vue-tap-target

**Comment by aggarwaldev** [comment]
@MajesticPotatoe Can you please update us again? Impatiently waiting for this one. 
I see there's a PR for the same but an ETA would be nice.

**Comment by jacekkarczmarczyk** [comment]
v2.3 (Q1 2020), see the roadmap in docs

**Comment by felipemengatto** [comment]
One more month for PR birthday 🎂 🎈 🥳

**Comment by AlexeyIsavnin** [comment]
It seems Feature Discovery is not on the roadmap anymore. At least, I couldn't find it. Are there plans on implementing that?

**Comment by peluprvi** [comment]
@AlexeyIsavnin 
We had a great effort on that (please check https://github.com/vuetifyjs/vuetify/pull/7467).
It will be revived for a v3.x implementation.

**Comment by m50S79sM6SRNp8Jn** [comment]
Did Vuetify v2 have feature discovery (or similar)?

**Comment by m50S79sM6SRNp8Jn** [comment]
Came across this, hope it helps

https://codepen.io/JamieCurnow/pen/GXpNBz

**Comment by J-Sek** [comment]
Not saying definitive "no" here. v5.0 will deliver foundation to split each Material Design version and potentially deliver this specific MD1 variant. However considering that MD1 is old and probably has no market share in '26, it would be irresponsible to keep this issue open.

Both `Tour` and `createTour` primitives are already on the v0 roadmap, so it is safe to assume it can be shipped in v5.x as a modern implementation utilizing popover and highlighting mask.
