### ISSUE TITLE
[Bug Report] The type attribute for the style element is not needed and should be omitted.

### ISSUE THREAD

**Issue by alfredriesen** [vuetifyjs/vuetify#11726]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.4

### Steps to reproduce
Click on link in jsfiddle and observer the first warning.

### Expected Behavior
Not to show warning for generated style tag by the vuetify theme.

### Actual Behavior
Shows the warning.

### Reproduction Link
<a href="https://jsfiddle.net/alfredriesen/0acv3gjz/" target="_blank">https://jsfiddle.net/alfredriesen/0acv3gjz/</a>

**Comment by KaelWD** [comment]
HTML validators are irrelevant.

**Comment by malopgrics** [comment]
@KaelWD can you explain further why you say that HTML validators are irrelevant? It sounds opinionated to me, and many people may disagree.
