### ISSUE TITLE
[Bug Report] Gradients on v-img do not work without src or with theme colours 

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/vuetify#11729]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 10

### Steps to reproduce
Add an app-bar without a background image, and use the img prop to supply a gradient as per the documentation. The app bar will not show the colour gradient.

Add an app-bar with an image this time, and use the img prop to supply a gradient as per the documentation, but use the theme colours instead of directly specifying rgb values. The app bar will not show the colour gradient.

### Expected Behavior
Colour gradient works without having to supply an image, and also by using theme colours instead of rgb values

### Actual Behavior
app bar has no colour

### Reproduction Link
<a href="https://codepen.io/davydnorris/pen/Bajdyzg" target="_blank">https://codepen.io/davydnorris/pen/Bajdyzg</a>

**Comment by KaelWD** [comment]
Unrelated to app-bar. v-img just passes gradient to the CSS `linear-gradient` function so theme colours have to be used as [custom properties](https://vuetifyjs.com/customization/theme/#custom-properties) instead. Gradient but no src is a bug.

**Comment by davydnorris** [comment]
yeah but if you look at the codepen - I am using the prop, which you would think parses the gradient information and puts it into the correct format. There are other places like sparkline where this happens

**Comment by KaelWD** [comment]
Sparkline doesn't do that either afaik, it just uses `currentColor` so you can use a single theme colour.

**Comment by davydnorris** [comment]
It seems inconsistent that other props that take a color can use the theme names but gradient prop can't - and it also seems like a common thing to want to do - to apply themed gradients to app bars etc. If this is something that's working as designed right now, should I request a feature maybe?

**Comment by KaelWD** [comment]
It's probably not likely to be implemented. I was against having a gradient prop at all as it's something you can do very easily with css. To support theme colours in the gradient we'd need to parse it, which can get very complex for such a small feature. We probably wouldn't be able to use an existing parser either because colour variants are separated by a space.

**Comment by davydnorris** [comment]
I would argue that the whole point of creating themes is to centralise the colour palette, and to then say it's all centralised except for one or two parts that you have to either do in css or using explicit colours is an inconsistency - it's like a 90% effort to implement consistent theming and then done.

If this is not going to be fixed then perhaps it's worth noting that you can't use theming for gradients in the documentation? I had a combination of the two so it made the img bug harder to track down
