### ISSUE TITLE
tfoot in data tables

### ISSUE THREAD

**Issue by robodude** [vuetifyjs/vuetify#1172]
- What will it allow you to do that you can't do today?
I'd like to have a 'summary' column at the bottom of my table. Maybe displaying the sum or mean of a column.

On some tables, I have a 'add row' footer to quickly add rows to the table.

  - How will it make current work-arounds straightforward?
Current work around 'faking' the structure of the table with another table. Being able to use 1 data table to replicate the function of an html table would be ideal.

  - What potential bugs and edge cases does it help to avoid?

**Comment by guanzo** [comment]
+1 to this.

**Comment by LanFeusT23** [comment]
+1
