### ISSUE TITLE
[Feature Request] v-timeline: end lines at first and last item

### ISSUE THREAD

**Issue by toni-king** [vuetifyjs/vuetify#11721]
### Problem to solve
Currently, v-timeline always extends the line beyond the first and last dot. I would like the line to end at the dots, so it looks similar to v-stepper. 

### Proposed solution
Add a prop to v-timeline which allows us to choose between an extended line and truncated line.

**Comment by ribrewguy** [comment]
any chance this can be backported to 2.x?
