### ISSUE TITLE
[Bug Report] VDataTable sort icon doesn't work in header slot with external sorting

### ISSUE THREAD

**Issue by jbrathwa** [vuetifyjs/vuetify#11727]
### Environment
**Vuetify Version:** 2.3.2
**Last working version:** 1.1.0-alpha.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
1. hide the default header
2. create custom header with sort icon using header slot
3. add external sorting

### Expected Behavior
The icons are only visible on hover or when the table is sorted.

### Actual Behavior
All icons are visible in the header and they do not rotate on click. (The table is sorted, but there is no visual feedback on the icons.)

### Reproduction Link
<a href="https://codepen.io/jbrathwa/pen/bGErbLo" target="_blank">https://codepen.io/jbrathwa/pen/bGErbLo</a>

**Comment by jacekkarczmarczyk** [comment]
If you're using `header` slot you're fully responsible for it's contents. You're missing some classes
https://codepen.io/jkarczm/pen/abdyOmP
