### ISSUE TITLE
[Bug Report] Not found {direction}-xs-{size}

### ISSUE THREAD

**Issue by AkioSarkiz** [vuetifyjs/vuetify#11722]
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 10

### Steps to reproduce
Just use {direction}-xs-{size}

### Expected Behavior
Remove padding

### Actual Behavior
Not work

### Reproduction Link
<a href="https://codepen.io/unnamed321123/pen/YzwQGbK" target="_blank">https://codepen.io/unnamed321123/pen/YzwQGbK</a>

**Comment by jacekkarczmarczyk** [comment]
`pa-0`

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by AkioSarkiz** [comment]
That's an excellent answer. It's not what I need. The indents should only disappear on small screens. 

> 
> 
> `pa-0`
> 
> If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

That's an excellent answer. It's not what I need. The indents should only disappear on small screens.

**Comment by MajesticPotatoe** [comment]
Per the docs

The helper classes apply margin or padding at a given breakpoint. These classes can be applied using the following format: {property}{direction}-{breakpoint}-{size}. This does not apply to xs as it is inferred; e.g. ma-xs-2 equals ma-2.
