### ISSUE TITLE
[Feature Request] Autocomplete - select entire header group

### ISSUE THREAD

**Issue by totalhack** [vuetifyjs/vuetify#11724]
### Problem to solve
Allows users to select/deselect an entire group of options at once.

### Proposed solution
I'm pretty new to Vue and Vuetify so I don't have a specific suggestion as to how this should be done. The expected behavior would be to click on a header and have all options under that header selected/deselected.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
