### ISSUE TITLE
[Bug Report] VRadioGroup: 'change' event fired when mandatory and value changed programatically

### ISSUE THREAD

**Issue by woodgates** [vuetifyjs/vuetify#11734]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Create a VRadioGroup with mandatory prop, one radio value equals zero.
Change the value programatically
The component will fire a 'change' event which shouldn't happen.

### Expected Behavior
The component should not fire the change event as is the behavior of the component without the mandatory prop and the component wasn't changed by a click of the user on the component itself.

### Actual Behavior
The component fired a 'change' event which shouldn't happen.

### Reproduction Link
<a href="https://codepen.io/woodgates/pen/ZEQJpQp?editors=1011" target="_blank">https://codepen.io/woodgates/pen/ZEQJpQp?editors=1011</a>

### Other comments
At the codepen you can see in the console that the change event is fired when you change the value pressing the "Change Radio" Button. This is not the expected behavior as it happens only on certain circunstances on the same component. If you take out the mandatory prop the event is not fired.

This issue is CRITICAL for me as it generates a loop when updating the component.

**Comment by KaelWD** [comment]
Mandatory radios cannot be deselected. If you initialise the value to something like `null` it will emit a change event too and select the first item.
