### ISSUE TITLE
[Feature Request] Separate CDN of vuetify-utilities for non-vuetify projects (Good to have)

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#11738]
### Problem to solve
I am a big fan of vuetify, I wan to use vuetify utility classes for my other non-vuetify projects.
It's good to have separate pre-compiled CDN for utility classes only.

### Proposed solution
https://github.com/rishabh-rajgarhia/bootstrap-4-utilities

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
