### ISSUE TITLE
[Bug Report] V-Select Doesn't Bind Scroll Event Listenser When Using hide-no-data prop

### ISSUE THREAD

**Issue by andywgarcia** [vuetifyjs/vuetify#11737]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.1
**Browsers:** Firefox 77.0
**OS:** Mac OS 10.15

### Steps to reproduce
I wasn't able to reproduce it on a jsFiddle, but I can reproduce it on the [search api example](https://vuetifyjs.com/en/components/autocompletes/#searching-an-api).

In the Search API Example, do the following:
1. Search for a string that will return more than 20 results (the letter 's')
2. Scroll to the bottom of the returned options
3. Verify that more results do not load. This is the bug
4. Close the options dropdown
5. Open the options dropdown
6. Now more than 20 results are loading

![vuetify-bug-demo](https://user-images.githubusercontent.com/14949072/85906865-7acdc480-b7c4-11ea-980c-f7bae5656593.gif)

### Expected Behavior
More than 20 results load when scrolling after results come back without needing to reopen the dropdown

### Actual Behavior
Only 20 results load even after scrolling to the bottom after the results come back without reopening the dropdown

### Reproduction Link
I wasn't able to reproduce it on the js fiddle with the code from the example... but here it is
<a href="https://jsfiddle.net/zbhu39w2/38/" target="_blank">https://jsfiddle.net/zbhu39w2/38/</a>

**Comment by KaelWD** [comment]
Oh look we have an example with https://github.com/vuetifyjs/vuetify/pull/11675#issuecomment-649700075. Doesn't happen in jsfiddle because the docs run straight off the master branch so it's technically v2.3.3

**Comment by andywgarcia** [comment]
Ah I was so close on my google search to find that..... Thanks @KaelWD
