### ISSUE TITLE
[Feature Request] Add text to V-Divider

### ISSUE THREAD

**Issue by manuel-84** [vuetifyjs/vuetify#11733]
### Problem to solve
Allow to insert text over the line of the divider

### Proposed solution
https://stackoverflow.com/a/36159798/1348517

**Comment by Mert75** [comment]
A codepen showing how to do it: https://codepen.io/itsyeah/pen/YzqwdPo

**Comment by phinolex** [comment]
what about version 3 of vuetify? The above solution no longer works for vuetify 3

**Comment by valentiniljaz** [comment]
The following works for Vuetify 3:

```
<v-container>
    <v-row wrap no-gutters>
        <v-col cols="5" class="text-center">
            <v-divider class="mt-3" />
        </v-col>
        <v-col cols="2" class="text-center text-h6">
            OR
        </v-col>
        <v-col cols="5" class="text-center">
            <v-divider class="mt-3" />
        </v-col>
    </v-row>
</v-container>
```

**Comment by minh-ncm** [comment]
> what about version 3 of vuetify? The above solution no longer works for vuetify 3

I used this for vue3
```
<!-- https://vuetifyjs.com/en/styles/flex/#flex-shorthand -->
<div class="d-flex">
  <v-divider></v-divider>
  <p>or</p>
  <v-divider></v-divider>
</div>
```

**Comment by fessacchiotto** [comment]
the above does not work for me (vuetify 3.5.11)

**Comment by Mert75** [comment]
> what about version 3 of vuetify? The above solution no longer works for vuetify 

> the above does not work for me (vuetify 3.5.11)

Made a [playground](https://play.vuetifyjs.com/#eNp9kE1qwzAQha8y1cYtVNWiu6IUuusNuqi7EPI4CGRpkMauwfjuGTsJySoboTd8783P76Jq8eaL6G0aUX0oyzhQdIyfbQKwk3ZE+1dEFybw0dV6aFWn+4gzBMGr9pgYC7gYjukiWnVx7SHiDJ0Q5la8D2OcWaes/4sjoFm/i3tZYKhHWFdrBH0UdgOsuc5rzd0eIqsvgRgq8nheJwyUC8MCBXtYoS95gEZO0Gw4gM+p8j7AYSOem2+MMcNPLrF7al62BudICVPraxpj3J+/E49dbys=) with Vuetify 3.5.11, slightly different approach

**Comment by fessacchiotto** [comment]
Thank you! Looks great now. On 25 Mar 2024, at 10:05, Mert ***@***.***> wrote:﻿

what about version 3 of vuetify? The above solution no longer works for vuetify


the above does not work for me (vuetify 3.5.11)

Made a playground with Vuetify 3.5.11, slightly different approach
