### ISSUE TITLE
[Bug Report] Install A-la-cart project lighthouse low score

### ISSUE THREAD

**Issue by lekhang2512** [vuetifyjs/vuetify#11730]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
no

### Expected Behavior
no

### Actual Behavior
no

**Comment by KaelWD** [comment]
no
