### ISSUE TITLE
[Bug Report] v-combobox - extra clickable menu appended to items

### ISSUE THREAD

**Issue by bob-lee** [vuetifyjs/vuetify#11746]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Linux x86_64

### Steps to reproduce
This may be just a technical help request.
I have a `combobox` field that I used to show `+` append icon to allow user to create a new item but my boss asked me to instead have an extra menu `+ Add New` appended to items.
I tried `computed` property as in the link.

1. click combobox field
2. type in `ab`

### Expected Behavior
Somehow can I make `+ Add New` menu appears all the time and handle when it's selected?

### Actual Behavior
`+ Add New` menu disappears as it doesn't include `ab`

### Reproduction Link
<a href="https://codepen.io/bob-lee/pen/qBbPNxZ?editors=1010" target="_blank">https://codepen.io/bob-lee/pen/qBbPNxZ?editors=1010</a>

### Other comments
I assume `append-item` slot is not an option as it is not clickable..

**Comment by KaelWD** [comment]
`append-item` can be clickable if you put a `v-list-item` in it. If you want to use `items` instead for some reason you would have to provide a custom `filter` prop that always allows the "Add new" item.
