### ISSUE TITLE
date picker in menu click outside of menu closes but doesnt call cancel or save

### ISSUE THREAD

**Issue by capttrousers** [vuetifyjs/vuetify#1174]
### Steps to reproduce
Copy code from [#3, Date Picker in Menu](https://vuetifyjs.com/components/pickers).

When having an existing object with a date prop that can be edited and support the cancel/save actions, there will be the dateTemp variable, v-modeled on the text-field/date-picker to be displayed. Then, when clicking the Save action, it sets the `existingDate = dateTemp`, clicking Cancel would reset `dateTemp = existingDate`. 

### Versions
latest of vue, vuetify, chrome

### What is expected ?
Clicking outside the menu with `:close-on-content-click=false` doesn't close the menu picker, OR it closes it and also calls one of the methods Cancel or Save. I can't really decide which method makes more sense, if the picker does close. But the close-on-content-click="false" seems to indicate it shouldnt close outside. 

### What is actually happening ?
Clicking outside the menu closes the picker, but doesnt call either method. This will cause user confusion if they think the date being shown in the picker is also what the existingDate value is, but they are not the same yet, since neither method was called, and the dateTemp is more of a display layer value. 

The problem is I can repro this in my code, and the doc example linked above has the same issue, but the codepen below acts as I'd expect, the picker does not close with an outside click, unless the click is on the text-field itself. 

### Reproduction Link
https://codepen.io/anon/pen/JyGbyP

**Comment by johnleider** [comment]
You are missing v-app in the example. As well, close-on-content-click only applies to clicking within the menu content. What you are looking for is close-on-click.
