### ISSUE TITLE
[Bug Report] Erroneous space inserted within VTextField <legend> is translated by Chrome auto-translate

### ISSUE THREAD

**Issue by piktur** [vuetifyjs/vuetify#11747]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Configure browser language `chrome://settings/languages` so that the preferred language is something other than the default, `French (France)` is preferrable.
2. Switch to French and check "Always Translate English"

### Expected Behavior
The legend should be empty

### Actual Behavior
The `&#8203` within `<legend>` is translated to `La`

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-template-j4nn9?file=/src/App.vue:0-251" target="_blank">https://codesandbox.io/s/vuetify-template-j4nn9?file=/src/App.vue:0-251</a>

**Comment by johnleider** [comment]
fixed by #11748
