### ISSUE TITLE
[Feature Request] Add toggle for v-snackbar layout component overlap

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#11758]
### Problem to solve
The snackbar no longer overlays the top or bottom bars as of v2.3.

The release notes explicitly say: The `v-snackbar` component will no longer overlap layout components vertically **by default**.

Which implies there is a non-default behavior where it does overlay these toolbars. However, such an option does not seem to exist.

### Proposed solution
Add a property to toggle this behavior. 

A change that modifies the default behavior of elements, with no toggle to turn it back is a breaking change instead of a feature is it not?

**Comment by WhileKing** [comment]
the same problem.
