### ISSUE TITLE
[Feature Request] v-data-table: Please allow an array for item-key(s)

### ISSUE THREAD

**Issue by haexhub** [vuetifyjs/vuetify#11754]
### Problem to solve
Tables often have multiple columns as keys/identifier, but v-data-table only allow 1 column to be declared as key. In result people have to concate multiple columns to one key. That's not nice.
Can you please allow an array/object for multiple keys or add an extra property for the header to explicit declare key columns?

### Proposed solution
Please allow multiple columns for item-key(s) or allow to declare the key property in the header declaration.

**Comment by sorrentix** [comment]
Experiencing the same issue as @haexhub

**Comment by KaelWD** [comment]
This is very simple to do yourself, just define `item-value` as a function returning the properties you want.
