### ISSUE TITLE
[Bug Report] Calendar event-more breaks layout

### ISSUE THREAD

**Issue by TrendyTim** [vuetifyjs/vuetify#11757]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Edge 84.0.522.20
**OS:** Windows 10

### Steps to reproduce
Using the calendar example from documentation, adding :event-more="false" 
In repro link,  due to the random event adding in the docs, you may need to scroll a few months to see it clearly.

### Expected Behavior
Day rows should expand to fit contents

### Actual Behavior
Day row should resize to fit all content if :event-more is false

### Reproduction Link
<a href="https://codepen.io/TrendyTim/pen/wvMrQRX" target="_blank">https://codepen.io/TrendyTim/pen/wvMrQRX</a>

**Comment by TrendyTim** [comment]
Here is a screenshot just to assist:
![image](https://user-images.githubusercontent.com/8325270/86075215-d94bb900-baca-11ea-8cad-c5310d6b9678.png)

**Comment by MajesticPotatoe** [comment]
duplicate #9796
