### ISSUE TITLE
[Bug Report] v-col xs breakpoint not correctly working / not supported?

### ISSUE THREAD

**Issue by mbariola** [vuetifyjs/vuetify#11753]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
I am trying to follow Net Ninja's tutorial for Vuetify 

https://www.youtube.com/watch?v=oAbwZ5Y_wRY&list=PL4cUxeGkcC9g0MQZfHwKcuB0Yswgb3gA5&index=14

updating it to Vuetify 2.3.2 as I go. So far, so good. 

It seems though that the xs breakpoint for v-col does not work and is not even mentioned in the props list.

https://vuetifyjs.com/en/components/grids/#api

 It IS mentioned in the breakpoints list though.  
breakpoints for sm and md work fine.

### Expected Behavior
xs breakpoints working as in version 1.3.x: when on xs screen sizes, grid in codepen should go on 3 rows like this:
col1
col2 col3
col4

### Actual Behavior
when on xs screen sizes, grid on codepen is displayed on a single row where all cols have same width, like this:
col1 col2 col3 col4

### Reproduction Link
<a href="https://codepen.io/massib/pen/zYrEjrB" target="_blank">https://codepen.io/massib/pen/zYrEjrB</a>

**Comment by MajesticPotatoe** [comment]
use `cols` prop
duplicate #9233
