### ISSUE TITLE
MS Edge doesn't display icons in breadcrumb component correctly

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1175]
### Steps to reproduce
Create a breadcrumb component with icons and view in MS Edge.

### Versions
Latest Vuetify in MS Edge

### What is expected ?
The breadcrumbs should show the material icons between breadcrumb list items in Edge.

### What is actually happening ?
MS Edge fails to show the ligature and leaves a large space where it should be

### Reproduction Link
In MS Edge: https://codepen.io/anon/pen/WErRQL?editors=1010

**Comment by johnleider** [comment]
This was fixed in your PR
