### ISSUE TITLE
[Bug Report] How to update or modify any value in vuetifyjs text-field?

### ISSUE THREAD

**Issue by yurenlimbu** [vuetifyjs/vuetify#11750]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Mac OS 10.15

### Steps to reproduce
Update or create value with virtual keyboard number pad

### Expected Behavior
Add new value created through virtual keyboard

### Actual Behavior
Not updating any value in v-text-field

### Reproduction Link
<a href="https://codepen.io/yurenlimbu/pen/qBbPjrd" target="_blank">https://codepen.io/yurenlimbu/pen/qBbPjrd</a>

### Other comments
As HTML input its working fine but with vuetify v-text-field I can't update any value with virtual number keyboard.

**Comment by KaelWD** [comment]
`this.active.target.value` just updates the internal `<input>` element without triggering any events, the component has no way to know that the value has been changed.
