### ISSUE TITLE
[Feature Request] Cant seem to support the notch on ionic/vue 

### ISSUE THREAD

**Issue by kairos0ne** [vuetifyjs/vuetify#11759]
### Problem to solve
Please could you support the 'notch' on IOS and Android devices. Its a real dirty hack to override the CSS directly.  

### Proposed solution
The app-bar component could support a prop that sets the css for you. Trouble is, you can't set margin-top on body in vuetify overrides this.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
