### ISSUE TITLE
[Feature Request] dynamic item height support for v-virtual-scroll

### ISSUE THREAD

**Issue by aleksey-hoffman** [vuetifyjs/vuetify#11755]
### Problem to solve
Right now `v-virtual-scroll` doesn't support items of different / dynamic height, which makes it very limited. 
You cannot set different heights for different types of items.

### Proposed solution
```html
<v-virtual-scroll>
  <template v-slot="{ item }">   
    <v-virtual-scroll-item
      height="dynamic"
      :min-item-height="32"
      :item-height="itemHeight(item)"
    >
      <custom-header-item
        v-if="item.isHeader"
        :item="item"
      >
        {{item.title}}
      </custom-header-item>

      <custom-item 
        v-if="!item.isHeader"
        :item="item"
      ></custom-item>
    </v-virtual-scroll-item>
  </template>   
</v-virtual-scroll>
```
```js
methods: {
  itemHeight (item) {
    if (item.type === 'header') { return 32 }
    else if (item.type === 'image') { return 128 }
    else { return 56 }
  }
}
```

**Comment by aleksey-hoffman** [comment]
@albertodeago could you please look into this? Would it be difficult to implement this?
I mean, if it receives the height of each item via props, as shown in the example above, couldn't it just add them all up to calculate the container height? And when the height of any item changes, it could just recalculate everything to make sure the container height stays in sync with the items height.

**Comment by albertodeago** [comment]
I'll look into it 👍

**Comment by iranagame** [comment]
@albertodeago any deadline for this? since it's very needed!

**Comment by albertodeago** [comment]
Sorry can't give a deadline, I'd pretty much 0 free time to work on this lately, I try to handle this for august

**Comment by saschamander** [comment]
+1

**Comment by tudorradubarbu** [comment]
News on this one?

**Comment by albertodeago** [comment]
While I was working on it I found some issues. Unfortunately I had no more time to work on vuetify so this is still open

**Comment by lartheon** [comment]
I too would like to see this functionality

**Comment by kaovilai** [comment]
@albertodeago Did you happen to document those issues?

**Comment by albertodeago** [comment]
@kaovilai nothing particular, I wanted the component to be as simple and lightweight as possible

**Comment by shawndeprey** [comment]
I definitely need this feature as well.

**Comment by MikolaMirchuk** [comment]
You can use this as workaround
https://github.com/Akryum/vue-virtual-scroller

**Comment by trizotti** [comment]
I'd love to see this functionality too

**Comment by qualle-admin** [comment]
this is actually really simple

```
      <v-virtual-scroll
        v-if="computedEntities.length"
        :bench="bench"
        :items="computedEntities"
        :height="getTableHeight()"
        :item-height="tableOptions.rowHeight"
      >
      
    getTableHeight() {
      const length = this.computedEntities.length;
      const height = length * this.tableOptions.rowHeight + 1;

      if (height > window.innerHeight) {
        return this.tableOptions.tableHeight;
      } else {
        return height;
      }
    }
```
