### ISSUE TITLE
[Bug Report] Data table internationalization

### ISSUE THREAD

**Issue by beastmike1** [vuetifyjs/vuetify#11762]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Edge 85.0.552.1, Google Chrome
**OS:** Windows 10

### Steps to reproduce
If you click the locale buttons you can see how it changes in the date picker but not in the table

### Expected Behavior
It should change the locale

### Actual Behavior
It doesn't change

### Reproduction Link
<a href="https://codesandbox.io/s/elastic-pare-3fmw5?file=/src/main.js" target="_blank">https://codesandbox.io/s/elastic-pare-3fmw5?file=/src/main.js</a>

### Other comments
It's the same that happens in this issue https://github.com/vuetifyjs/vuetify/issues/5618 and has been fixed with this PR https://github.com/vuetifyjs/vuetify/pull/6320

**Comment by MajesticPotatoe** [comment]
#6320 was added as an enhancement/feature not a bug.
For datatables, you need to follow the same procedure used for regular i18n outlined in docs:
https://vuetifyjs.com/en/customization/internationalization/#getting-started

example using your codepen: https://codesandbox.io/s/compassionate-morning-vtx9h
