### ISSUE TITLE
[Documentation] PM2 start ecosystem fails

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11763]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 3.0.0-beta.17
**Browsers:** Firefox 77.0
**OS:** Linux

### Steps to reproduce
Follow [Contribution guide](https://vuetifyjs.com/en/getting-started/contributing/):

1. `git clone https://github.com/vuetifyjs/vuetify.git`
2. `cd vuetify`
3. `yarn`
3. `yarn build`
4. `yarn global add pm2`
5. `pm2 start ecosystem.config.js`

### Expected Behavior
Ecosystem starts

### Actual Behavior
```
[PM2][WARN] Applications vuetify-dev, vuetify-build, vuetify-docs not running, starting...
[PM2][ERROR] Error: Script not found: /home/peteruithoven/Projects/www/vue/vuetify/packages/vuetify/yarn.js
[PM2][ERROR] Error: Script not found: /home/peteruithoven/Projects/www/vue/vuetify/packages/vuetify/yarn.js
[PM2][ERROR] Error: Script not found: /home/peteruithoven/Projects/www/vue/vuetify/packages/docs/yarn.js
```

### Other comments
[ecosystem.config.js](https://github.com/vuetifyjs/vuetify/blob/master/ecosystem.config.js) seems to look for `yarn.js` files that don't exist?

**Comment by MajesticPotatoe** [comment]
Likely something to be some sort of issue with pm2 + linux + yarn.
No errors on windows. Would probably not use this as it will probably be removed in the near future with docs update.
A little debugging on your side could be to check if individual packages run.

**Comment by peteruithoven** [comment]
If this is going to be removed that doesn't sounds like a useful way to spend time. I'm fine with closing the issue.

**Comment by MajesticPotatoe** [comment]
I have already removed it from the upcoming version of the docs.
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
