### ISSUE TITLE
[Feature Request] flexible class to class object helper

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11769]
### Problem to solve
While adding a customizable class property I noticed I needed a lot of code. 
Testing this would also require lot's of unit tests per component. 
``` js
return h('td', {
  class: {
    // ...
    [Array.isArray(cellClass) ? cellClass.join(' ') : cellClass || '']: cellClass,
  },
}, children)
```

### Proposed solution
Adding a simple helper.

``` js
function toClassObject(c:string | string[]) {
  return {
    [Array.isArray(c) ? c.join(' ') : c || '']: !!c,
  }
}

return h('td', {
  class: {
    // ...
    ...toClassObject(cellClass)
  },
}, children)
```

But then again maybe I'm simply missing a more concise way of writing this.

**Comment by KaelWD** [comment]
`VNodeData.class` can also be an array of strings and objects

**Comment by peteruithoven** [comment]
Duh :man_facepalming: 

Thanks for adding the example

**Comment by peteruithoven** [comment]
It even handles nested arrays

``` js
class: [
  'a',
  ['b', 'c']
]
```
