### ISSUE TITLE
[Feature Request] Control app height / dynamic app height

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#11766]
### Problem to solve
I am injecting vuetify / vuejs widget on a static HTML and vuetify automatically creates a max vertical sized div.

So if I have a slider component only for example, I get a ton of whitespace under it.

I want the actual application to only be the height of the used components.

Right now I am forced to manually set the height using CSS classes and do approximate calculations on how high the app should be in total depending on how many components I use.

### Proposed solution
Ability to remove the forced full height of the app so that it is dynamically expanding vertically.

**Comment by Zyles** [comment]
The problem is the `.v-application--wrap [ min-height: 100vh; }`

**Comment by Zyles** [comment]
Apparently it can be overriden by a deep selector:

```
<style>
#app .v-application--wrap {
  min-height: 0 !important;
}
</style>
```

**Comment by johnleider** [comment]
This is changing for v3 and your current override is what we'd suggest.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
