### ISSUE TITLE
[Feature Request] Custom carousel delimiters in v-carousel

### ISSUE THREAD

**Issue by ericirish** [vuetifyjs/vuetify#11765]
### Problem to solve
I'm building a carousel that allows a user to move through a roster of personnel. It would be very nice if I could insert the person's initials, perhaps into a v-avatar, as a custom delimiter. This would allow the user to see who is previous and next in the carousel.

### Proposed solution
Though I'm not a vuetify expert, it could be accomplished by passing an array of delimiter nodes to the v-carousel parent component? Or building a function that is passed on the v-carousel-item?

**Comment by DAVIDhaker** [comment]
Up! 

I need to make product photo viewer. Big picture, lot of previews as slide delimiters and one more button in slider delimiter block to add image.

**Comment by milan-rabara** [comment]
Any updates on this ?

**Comment by KaelWD** [comment]
VCarousel has an `item` slot in v3.

**Comment by milan-rabara** [comment]
Ok. Got It.
Thank you @KaelWD
