### ISSUE TITLE
[Bug Report] Snackbar in dialog causes scrollbar to momentarily appear

### ISSUE THREAD

**Issue by evanwirt** [vuetifyjs/vuetify#11770]
### Environment
**Vuetify Version:** 2.3.2
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Take snackbar sample and scrollable dialog sample and combine them, see repro link.
(Note, this is happening in the real world in my vuetify app and I'm just using the sample apps as an example).
Click 'open dialog' button.
See scrollbar momentarily appear in dialog as it's fading in.
Click outside the dialog to close it.
See scrollbar momentarily appear in dialog as it's fading out.

### Expected Behavior
Scrollbar doesn't appear.

### Actual Behavior
Scrollbar appears momentarily

### Reproduction Link
<a href="https://codepen.io/evanw/pen/ExPbmjw" target="_blank">https://codepen.io/evanw/pen/ExPbmjw</a>

### Other comments
This just combined the snackbar and scrollable dialog samples:

https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdialogs%2F

https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fsnackbars%2F

**Comment by evanwirt** [comment]
This is happening in the real world in my vuetify app and I'm just using the sample apps as an example.

**Comment by johnleider** [comment]
This bug is no longer reproducible as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
