### ISSUE TITLE
[Feature Request] v-menu allow setting origin for offset

### ISSUE THREAD

**Issue by DispatchCommit** [vuetifyjs/vuetify#11774]
### Problem to solve
When using v-menu, you cannot easily specify how to position the menu. The current behavior is specifying the top and left coordinates, but this is not always ideal.

### Proposed solution
An `anchor` option to allow specifying different offsets, similar to the `origin` property, or for `origin` to affect the positioning of v-menu.

![image](https://user-images.githubusercontent.com/45262335/86232154-697c1380-bb48-11ea-8b3f-de5d8431bcce.png)

here you can see because the content of my menu has changed and now has fewer items, it has shrunk towards the top left. I can fix this by changing `top` to `bottom` in CSS.

**Comment by KaelWD** [comment]
Related: #8695

**Comment by DispatchCommit** [comment]
Any proposed workarounds for this?

**Comment by KaelWD** [comment]
v3 has `anchor` and `origin` props to set attachment points on the activator and content respectively, and will recompute its position on scroll or when the size of either the activator or content changes.
