### ISSUE TITLE
[Bug Report] v-skeleton-loader height, min-height and max-height does not work

### ISSUE THREAD

**Issue by angelofan** [vuetifyjs/vuetify#11771]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
```
<v-skeleton-loader type="image" height="250" style="background:#ff9900"></v-skeleton-loader>

<v-skeleton-loader type="image" min-height="250" style="background:#99ff00"></v-skeleton-loader>

<v-skeleton-loader type="image" height="100vh" max-height="250" style="background:#0099ff"></v-skeleton-loader>
```
The skeleton animation has always been 200px in height, The height of the outer div is the height I set.

### Expected Behavior
The height I set for `v-skeleton-loader` is the `height` of the animation.

The same is true for `max-height` and `min-height`.

### Actual Behavior
The height I set for `v-skeleton-loader` is the `height` of the parent div of the animation, and the height of the animation itself is always 200px.

The same is true for `max-height` and `min-height`.

![image](https://user-images.githubusercontent.com/20255750/86194287-b1b72800-bb80-11ea-8a7c-8f3191cd8651.png)

### Reproduction Link
<a href="https://codepen.io/13546777510/pen/mdVqmPo" target="_blank">https://codepen.io/13546777510/pen/mdVqmPo</a>

**Comment by cassioscabral** [comment]
I had to override the CSS for this element to overcome this issue. Like this:

```scss
::v-deep .v-skeleton-loader.v-skeleton-loader--is-loading {
  .v-skeleton-loader__image {
    height: 100%;
  }
}
```

**Comment by jtotty** [comment]
The default height for the skeleton-loader-image is set to 200px as stated in the [documentation](https://vuetifyjs.com/en/api/v-skeleton-loader/#skeleton-loader-image-height). 

You need to override the custom global defaults by setting the variable `$skeleton-loader-image-height: 100%;` in your own `variables.scss` file.

More detailed instructions found on the Vuetify Documentation for Vue CLI, Nuxt.js, and Webpack.

https://vuetifyjs.com/en/features/sass-variables/

**Comment by SandeepKumarYaramchitti** [comment]
@jtotty Can you please show an example for skeleton loader as i tried the same option and it didn't work.

**Comment by jtotty** [comment]
> @jtotty Can you please show an example for skeleton loader as i tried the same option and it didn't work.

SASS/SCSS variables are only supported using when using the vuetify-loader. This is done automatically when using the vue-cli-plugin-vuetify plugin.

**Comment by dfeverxx** [comment]
> I had to override the CSS for this element to overcome this issue. Like this:
> 
> ```css-scss
> ::v-deep .v-skeleton-loader.v-skeleton-loader--is-loading {
>   .v-skeleton-loader__image {
>     height: 100%;
>   }
> }
> ```
   form this 
`.v-skeleton-loader__image.v-skeleton-loader__bone {
    height: 100%;
}`

**Comment by taheri79** [comment]
> I had to override the CSS for this element to overcome this issue. Like this:
> 
> ```css-scss
> ::v-deep .v-skeleton-loader.v-skeleton-loader--is-loading {
>   .v-skeleton-loader__image {
>     height: 100%;
>   }
> }
> ```

Not working in my solution

**Comment by johnleider** [comment]
I'm closing this issue as I'm weary of the consequences of making a change like this on the v2 branch. v3 skeleton loader takes a different approach and I suggest reviewing its capabilities for suggesting changes. It will release tomorrow into Vuetify labs.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ricardovanlaarhoven** [comment]
This is still an issue in v3, right?
https://play.vuetifyjs.com/#eNplj88OgjAMxl9l2VkFD17IJPE5xMOEBhbL1myFQIzvLkwJGC9N+/3677s+ZfBlciE69B3ITCqGllAz5IUVQvV7TRTTWJTOsjYW/FeKYngAAju7R6cr8AsRgkeCcyFNq2so5Ko3YOqGJ3JKUxq2JPCI88jd+WlTJo40iODQVMJDtTbmKvk7uzw5kd8vZ+VjQiUbc/K1sx1iDLc3WaVTUw==

**Comment by YusufcanY** [comment]
This is **still** an issue in v3.5.2. Any updates?

**Comment by J-Sek** [comment]
The simplest solution is to change `$skeleton-loader-image-height` from `150px` to `100%` and ensure that all instances have a height set (otherwise it is 0px).

Alternatively:

```css
.v-skeleton-loader:has(.v-skeleton-loader__image) {
    height: 150px;
    overflow: hidden;
}
.v-skeleton-loader__image {
    height: inherit;
    min-height: inherit;
    max-height: inherit;
}
```
