### ISSUE TITLE
[Feature Request] Progress circular rounded

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11776]
### Problem to solve
It's not possible to draw the progress circular with rounded ends. This currently only happens when enabling `indeterminate`. 

### Proposed solution
Add a `rounded` property like the one for Progress linear.

A sass variable could also work. Progress linear for example uses `$progress-linear-border-radius`. 
Progress circular is drawn using svg so something like `$progress-circular-stroke-linecap` might be appropriate?

### Workaround
``` vue
<template>
  <v-progress-circular
    value="50"
    class="progress-circular"
  />
</template>
<style scoped>
.progress-circular >>> circle {
  stroke-linecap: round;
}
</style>
```

**Comment by badru254** [comment]
Not sure if it is right, but you can also do this incase it is a very simple one-page app 
 `<style >
        .v-progress-circular__overlay {
          stroke-linecap: round;
        }
        </style>`
