### ISSUE TITLE
[Bug Report] Outline black dotted border with firefox on selected App menu

### ISSUE THREAD

**Issue by bufferUnderrun** [vuetifyjs/vuetify#11773]
### Environment
**Vuetify Version:** 2.3.3
**Last working version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 7

### Steps to reproduce
When clicking in app menu __with firefox__, the current menu have a black outline border which it appears to be the firefox selected (see https://css-tricks.com/removing-the-dotted-outline/).

### Expected Behavior
[![App menu correct](https://thumbs2.imgbox.com/0f/fe/eWsMgtIk_t.png)](http://imgbox.com/eWsMgtIk)

### Actual Behavior
[![App menu outline black border with firefox](https://thumbs2.imgbox.com/f3/3c/BnQHEzM6_t.png)](http://imgbox.com/BnQHEzM6)

### Reproduction Link
<a href="https://codepen.io/cp10/pen/rNxYpON" target="_blank">https://codepen.io/cp10/pen/rNxYpON</a>

**Comment by johnleider** [comment]
This bug is resolved as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
