### ISSUE TITLE
[Bug Report] Cannot unset VApp id

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#11779]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
Add a v-app with an empty or null id
```html
<v-app id=""/>
<v-app :id="null"/>
<v-app/>
```

### Expected Behavior
The id prop to not appear in the dom

### Actual Behavior
The id prop appears in the dom
```html
<div data-app="true" class="v-application v-application--is-ltr theme--light" id=""></div>
<div data-app="true" class="v-application v-application--is-ltr theme--light" id="null"></div>
<div data-app="true" class="v-application v-application--is-ltr theme--light" id="app"></div>
```

### Reproduction Link
<a href="https://codepen.io/Tofandel/pen/gOPoadm?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fapp-bars%2F" target="_blank">https://codepen.io/Tofandel/pen/gOPoadm?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fapp-bars%2F</a>

### Other comments
This is not valid html according to [W3C](https://www.w3.org/TR/html4/types.html#type-id) and will fail validation with : `syntax of attribute value does not conform to declared value`
The default value of "app" is not great either, I would expect no id at all by default

**Comment by johnleider** [comment]
I typically do `<v-app id="inspire">` or some derivative of.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
