### ISSUE TITLE
[Bug Report] font-family dont change varibale sass $body-font-family

### ISSUE THREAD

**Issue by PGorshkov** [vuetifyjs/vuetify#11777]
### Environment
**Vuetify Version:** 2.3.3
**Last working version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1) add to scss variables.scss
2) add global load vue.config.js
3) add 3 line
@import "~vuetify/src/styles/styles.sass";
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&display=swap');
$body-font-family: 'Open Sans', serif; 
4) add class block text-h4 
result font-family = Roboto

### Expected Behavior
https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file

### Actual Behavior
https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file

### Reproduction Link
<a href="http://github" target="_blank">http://github</a>

**Comment by MajesticPotatoe** [comment]
remove line 1 `@import "~vuetify/src/styles/styles.sass";` this is not needed when using vuetify-loader and is causing you duplicate your variables, and essentially overwrite your customization.
