### ISSUE TITLE
[Bug Report] Snackbars in bottom not showing in Android Chrome when the search bar is visible

### ISSUE THREAD

**Issue by miki95** [vuetifyjs/vuetify#11781]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
In Android Chrome, open a snackbar with bottom property, it doesn't appear in screen until you scroll down (hide the search bar).

### Expected Behavior
It should appear always on screen, even with search bar

### Actual Behavior
It doesn't show with search bar

### Reproduction Link
<a href="https://codepen.io/eremir/full/oNbpWRm" target="_blank">https://codepen.io/eremir/full/oNbpWRm</a>

**Comment by btakakho** [comment]
Same problem. Seems issue with `height: 100vh` in `VSnackbar.scss` line `21`

__VSnackbar.scss__
```scss
  &:not(.v-snack--absolute)
    height: 100vh
    position: fixed
    z-index: $snackbar-z-index
```

Also I've tested bottom snackbar in different mobile browsers:
Android Opera - wrong
Android Chrome - wrong
Android Firefox - ok
IOS Chrome - wrong
IOS Safari - ok
IOS Firefox - ok

**Comment by btakakho** [comment]
For now as a workaround I pass prop `absolute` and wrap `v-snackbar` with position `fixed` div

__vue__
```vue
<div class="snackbar-wrapper">
  <v-snackbar v-model="snackbar" absolute>
    Whooaaa!
  </v-snackbar>
</div>
```
__css__
```
.snackbar-wrapper {
  position: fixed;
  height: 100%;
  width: 100%;
  pointer-events: none;
  top: 0;
  left: 0;
  z-index: 1000; // <-- For my case
}
```

**Comment by mishamosher** [comment]
> Same problem. Seems issue with `height: 100vh` in `VSnackbar.scss` line `21`
> 
> **VSnackbar.scss**
> 
> ```css-scss
>   &:not(.v-snack--absolute)
>     height: 100vh
> ```

Tried `100%` instead of `100vh` and now it renders correctly on Chromium & Firefox, all platforms.

**Comment by klarkc** [comment]
@mishamosher workaround worked, but when you scroll on android chrome it moves the snackbar from bottom (while scrolling).

**Comment by valentinoli** [comment]
@klarkc The solution [posted here](https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down#answer-44680066) worked for me to prevent the snackbar from moving up and down on scroll:

```html
<meta name="viewport" content="minimum-scale=1">
```

**Comment by valentinoli** [comment]
I'm using Vue version 2.6.11 and Vuetify 2.2.11 and experienced the same bug on Android Chrome.
I tried @mishamosher's solution and I noticed the same unpleasant scroll behavior as @klarkc described.

I found out that Vuetify does not apply `top: 0` or `bottom: 0` properties according to the `top` or `bottom` props passed on to `v-snackbar`. Instead, the following CSS is applied to all snackbars:

```css
.v-snackbar {
    display: flex;
    bottom: 0;
    left: 0;
    right: 0;
    top: 0;
    /* more properties... */
}
```

The `top`, `right`, `bottom`, `left` properties are not overridden by passing the corresponding boolean props to `v-snackbar`. Instead Vuetify uses flexbox to position the snackbar wrapper element inside the `<v-snackbar>` container. Example:

```css
.v-snack--top {
    align-items: flex-start;
}
.v-snack--right {
    justify-content: flex-end;
}
```

Setting both `top: 0` and `bottom: 0` is somehow confusing the Android Chrome browser. So you can solve this entire issue by resetting the opposite CSS property depending on which prop (`bottom` or `top`) is passed on to `v-snackbar` (I think `bottom` is default):

```css
.v-snack.v-snack--top {
  bottom: initial;
}

.v-snack.v-snack--bottom {
  top: initial
}
```

This solved the issue for me and I did not need to set `height: 100%` as suggested above. Plus, no weird scroll behavior :)
