### ISSUE TITLE
[Documentation] should have specify version for new items or deprecated items

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#11789]
### Problem to solve
It's hard to find which item included in which version. (same for deprecated items)

### Proposed solution
Mention version on components, directives, props, slots, events, sass. (if possible)

Also, put some quick update note on updated components that what is updated.

@mr-mad-e

**Comment by MajesticPotatoe** [comment]
This is handled in the new version of the docs that's currently in development.
