### ISSUE TITLE
[Feature Request] New draggable components ?

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#11785]
### Problem to solve
There are some projects that already provide this kind of component (vuedraggable, vue-smooth-dnd,...) but there is no real support or clear or 100% working APIs behind those projects.
It would be great if Vuetify could provide their own with their known professionalism.

### Proposed solution
Create new draggable components. The goal would be to enable Vuetify users to build a kanban board with Vuetify out of the box.

Would it be possible for Vuetify ?

**Comment by MajesticPotatoe** [comment]
duplicate #6512
