### ISSUE TITLE
[Bug Report] Typescript type BreakpointThresholds seems to be missing 'xl'

### ISSUE THREAD

**Issue by reinpeter** [vuetifyjs/vuetify#11786]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 10

### Steps to reproduce
look at /vuetify/types/services/breakpoint.d.ts

### Expected Behavior
BreakpointThresholds interface should have property xl:number

### Actual Behavior
BreakpointThresholds is missing property xl

### Reproduction Link
<a href="https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/services/breakpoint.d.ts" target="_blank">https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/services/breakpoint.d.ts</a>

```
import Vuetify from 'vuetify';

export default function createVuetify() {
  return new Vuetify({
    breakpoint: {
      thresholds: {
        xs: 0,
        sm: 1024,
        md: 1280,
        lg: 1920,
        xl: 3840
      },
      scrollBarWidth: 24
    }
  });
}
```

compiling with typescript gives:

```
vuetify.ts:11:9 - error TS2322: Type '{ xs: number; sm: number; md: number; lg: number; xl: number; }' is not assignable to type 'Partial<BreakpointThreshold
s>'.
  Object literal may only specify known properties, and 'xl' does not exist in type 'Partial<BreakpointThresholds>'.

11         xl: 3840
           ~~~~~~~~

  ../../node_modules/vuetify/types/services/breakpoint.d.ts:34:3
    34   thresholds?: Partial<BreakpointThresholds>
         ~~~~~~~~~~
    The expected type comes from property 'thresholds' which is declared here on type 'BreakpointOptions'

```

Removing the entry for xl removes the error

### Other comments
typescript compiler fails over missing xl on type verification

**Comment by jacekkarczmarczyk** [comment]
> typescript compiler fails over missing xl on type verification

Need more info

**Comment by reinpeter** [comment]
Updated with code snippet and error.

**Comment by reinpeter** [comment]
Workaround is to replace
 new Vuetify( 
with 
new (Vuetify as any)(
or suppress the warning with @ts-ignore

**Comment by jacekkarczmarczyk** [comment]
values in the interface correspond to the maximum width of the breakpoint, xs can't be 0 (unless you want sm to be from 0 to 1024)
```js
      {
        xm: 1024,
        sm: 1280,
        md: 1920,
        lg: 3840
      }
```

**Comment by reinpeter** [comment]
@jacekkarczmarczyk 
The xs was maybe wrong, but that is not the issue.
Replace with xs: 500, and the mentioned typescript compiler error is still there, so please reopen.
OR, is it not ok to set a value for xl on the breakpoints?

**Comment by jacekkarczmarczyk** [comment]
> OR, is it not ok to set a value for xl on the breakpoints?

Yes, lg defines the max width for lg, and everything wider is xl, so there's no need to define it
