### ISSUE TITLE
focus event not propagating from inside stepper

### ISSUE THREAD

**Issue by shanemgrey** [vuetifyjs/vuetify#1178]
### Steps to reproduce
Place a v-text-field with autofocus inside v-stepper-step.  Reload page.  Notice the text field highlights blue, but does not get an active cursor.

### Versions

Tested in Chrome and FF current versions.  Using MacOS.  

"vue": "^2.3.4",
"vuetify": "^0.14.7",

### What is expected ?

I would expect the active cursor to take the position of the text-field with the autofocus in it.

### Reproduction Link

Example with failing behavior: https://codepen.io/shanemgrey/pen/BdjpzO
Example with correct behavior: https://codepen.io/shanemgrey/pen/mMVREX

If using codepen, you may have to Click "Change View" button and change to full screen for the working version to show correct behavior.

I suspect this line of code is causing the problem, but haven't been able to work out the flow of the source to be confident.  
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/steppers/VStepperStep.js#L53

**Comment by Ragura** [comment]
The same thing happens to text fields inside a dialog. I was about to create a seperate issue for this, but I suspect it has the same root cause.

**Comment by wcjr** [comment]
I was still having issues with this, here's an example:  https://codepen.io/wcjr/pen/RebvQj

Here's what I did to get around it for the time-being:  https://gist.github.com/wcjr/3a351331d3bd8206f6044211e1dd6436
