### ISSUE TITLE
[Documentation] Type of prop "header" in data table is wrong

### ISSUE THREAD

**Issue by Gearme** [vuetifyjs/vuetify#11784]
### Environment

**Browsers:** Firefox 79.0
**OS:** Windows 10

### Steps to reproduce
Visit the API for the data table component, look for property "header" in "props"

### Expected Behavior
Type of prop "header" in data table is "DataTableHeader"

### Actual Behavior
Type of prop "header" in data table is "TableHeader"

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables/#api" target="_blank">https://vuetifyjs.com/en/components/data-tables/#api</a>

**Comment by NickBolles** [comment]
Thank you @Gearme, I was getting real confused.
