### ISSUE TITLE
[Bug Report] Can't override heading-font-family in variables.scss

### ISSUE THREAD

**Issue by Palpie** [vuetifyjs/vuetify#11788]
### Environment

**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Create a file `src/styles/variables.scss` with this content:

```
$body-font-family: 'Roboto', sans-serif;
$heading-font-family: 'Poppins', sans-serif;
$material-light: (
    'background': #ff0000,
);
```

### Expected Behavior
Headers should get the font Poppins

### Actual Behavior
Headers gets the font Roboto

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
What vuetify and vue-cli-plugin-vuetify versions do you have? Is the background colour change being applied?

**Comment by Palpie** [comment]
vue-cli-plugin-vuetify: 2.0.6

Both the body font and background color works, but not the heading font.

**Comment by KaelWD** [comment]
Are you using the heading classes? It doesn't affect `<h*>` tags.

**Comment by Palpie** [comment]
I didn't read the documentation so thoroughly, apparently. I assumed `<h*>` worked and the classes was if you wanted to use them on other classes or use breakpoints. I tried the right way, but then I must have done something else wrong. Now it works using the `text-h1` class.
