### ISSUE TITLE
[Feature Request] html native prop input['pattern'] does not work

### ISSUE THREAD

**Issue by BaptisteCool** [vuetifyjs/vuetify#11798]
### Problem to solve
The native prop input['pattern'] seems to not work in compbo with title like the example https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_pattern

Tested with the '<VTextField>' and also a form.validate()

We would like to use it instead of rules

### Proposed solution
Have the native prop ready to work with the framework :).

**Comment by KaelWD** [comment]
v-form disables native field validation. If you need the ability to disable an entire form you can override this with `:novalidate="false"`, otherwise just use a `<form>` element instead as v-form doesn't do anything special if you aren't using rules.
