### ISSUE TITLE
[Bug Report] Ripple directive JS Error

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#11792]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
Unknown

### Expected Behavior
No error

### Actual Behavior
JS Error

### Other comments
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
This happens in the hide method of the ripple directive

```
hide (el: HTMLElement | null) {
    if (!el || !el._ripple || !el._ripple.enabled) return

    const ripples = el.getElementsByClassName('v-ripple__animation')

    if (ripples.length === 0) return
    const animation = ripples[ripples.length - 1]

    if (animation.dataset.isHiding) return
    else animation.dataset.isHiding = 'true'

    const diff = performance.now() - Number(animation.dataset.activated)
    const delay = Math.max(250 - diff, 0)

    setTimeout(() => {
      animation.classList.remove('v-ripple__animation--in')
      animation.classList.add('v-ripple__animation--out')
      opacity(animation, 0)

      setTimeout(() => {
        const ripples = el.getElementsByClassName('v-ripple__animation')
        if (ripples.length === 1 && el.dataset.previousPosition) {
          el.style.position = el.dataset.previousPosition
          delete el.dataset.previousPosition
        }

        animation.parentNode && el.removeChild(animation.parentNode) //HERE
      }, 300)
    }, delay)
  },
```

It doesn't seem to be causing any issues only a JS error

I cannot manage to make a minimum reproduction setup as there is no stack trace because it's a directive method and I could not find exactly what mix of elements is causing the error

I just have a stepper and a few fields (checkbox, text, select) and 2 buttons

This error happens when I dynamically show or hide fields when clicking on one button but unfortunately I cannot reproduce this issue in codepen.. (I think when I click on the button, the ripple is triggered and the button parent is rerendered removing the previous render's dom, triggering the error)

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by Tofandel** [comment]
As I explained, I cannot manage to reproduce on codepen but I can provide a link to a page where it happens with Vue devtools enabled

**Comment by jacekkarczmarczyk** [comment]
There's also codesandbox or you can prepare github repository, make sure first that the reproduction is as minimal as possible without any code that is not relevant to the issue

**Comment by Tofandel** [comment]
I tried both, I can't reproduce there, I located the issue to be only when vuetify loader is used and removing a button from the dom (v-if) after it's been clicked

**Comment by stepanho** [comment]
Sorry for interrupting.
I'm faced with same issue.
Component code:
`<v-btn
            :color="saveButtonColor"
            :loading="saveStatus === 'L'"
            v-text="saveButtonText"
            @click="saveCheckList"
          />`

Error occurs after some time (100-500ms) after click.
After troubleshooting I got that it's related with changing "v-text" or ":loading" values.
Changing other properties doesn't make that behaviour.

_Version:
Windows 7
Node 13.14.0
vue 2.6.11
vuetify 2.3.4
vuetify-loader 1.6.0_

**Comment by stepanho** [comment]
I made some troubleshooting.
Error occurs only if both of "loading" and "v-text" changes at the same time (in ~100ms).
Separately - no errors.

**Comment by KaelWD** [comment]
Don't use v-text on components.

**Comment by stepanho** [comment]
> Don't use v-text on components.

Why?

**Comment by KaelWD** [comment]
Because it overwrites any other elements the component renders:
![image](https://user-images.githubusercontent.com/16421948/87630726-2097a200-c779-11ea-97c4-648c6950e559.png)

![image](https://user-images.githubusercontent.com/16421948/87630703-0cec3b80-c779-11ea-8f67-1c0e50fa378b.png)

**Comment by stepanho** [comment]
@KaelWD Thank you, it fixes that issue.
I'm going to check all my project to replace "v-text" directive inside of components.

**Comment by Tofandel** [comment]
Okay so after @stepanho found what caused the issue, I tracked it in my project and it's caused by the `v-t` directive of vue-i18n that does the same as `v-text` for translations, using `$t` instead solved the error against a very tiny little bit of performance, so closing the issue

**Comment by mjchaudhari** [comment]
I had the same problem with vuetify  when i used v-text on buttons, below worked for me: 
```

<v-btn v-on:click="toggleState()" small >
    <span v-text="stateToggleLable"/>
</v-btn>
```

**Comment by DanieleMar** [comment]
Same error as yours

> `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` This happens in the hide method of the ripple directive
> 
> ```
> hide (el: HTMLElement | null) {
>     if (!el || !el._ripple || !el._ripple.enabled) return
> 
>     const ripples = el.getElementsByClassName('v-ripple__animation')
> 
>     if (ripples.length === 0) return
>     const animation = ripples[ripples.length - 1]
> 
>     if (animation.dataset.isHiding) return
>     else animation.dataset.isHiding = 'true'
> 
>     const diff = performance.now() - Number(animation.dataset.activated)
>     const delay = Math.max(250 - diff, 0)
> 
>     setTimeout(() => {
>       animation.classList.remove('v-ripple__animation--in')
>       animation.classList.add('v-ripple__animation--out')
>       opacity(animation, 0)
> 
>       setTimeout(() => {
>         const ripples = el.getElementsByClassName('v-ripple__animation')
>         if (ripples.length === 1 && el.dataset.previousPosition) {
>           el.style.position = el.dataset.previousPosition
>           delete el.dataset.previousPosition
>         }
> 
>         animation.parentNode && el.removeChild(animation.parentNode) //HERE
>       }, 300)
>     }, delay)
>   },
> ```

**BUT I haven't a button with inside v-text in the code.
It happens on this v-menu opening and before click inside v-menu**

```
          <v-menu
            v-model="showMoreMenu"
            :close-on-content-click="false"
            :activator="moreActivator"
            offset-x
          >
            <v-card color="grey lighten-4" min-width="350px" flat>
              <v-list-item-group>
                <v-list-item
                  v-for="(event, index) in dayEvents"
                  :key="index"
                  @click="showEventFromMore(event)" // the error come before click here. I think it isn't this the problem
                >
                  <v-list-item-content>
                    <v-list-item-title>{{ event.name }}</v-list-item-title> 
                    // SAME AS  <v-list-item-title v-text="event.name" /> // BOTH give error

                  </v-list-item-content>
                </v-list-item>
              </v-list-item-group>
              <v-card-actions>
                <v-btn
                  text
                  color="secondary"
                  @click="showMoreMenu = false"
                >
                  Close
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-menu>
```
The text prop inside v-btn is the style of the button. I tried to remove but it is the same

The activator isn't the problem. I removed and do the same
moreActivator = nativeEvent.target from previous click

This is the stack
```
<anonymous> (webpack:/node_modules/vuetify/lib/directives/ripple/index.js:123)
setTimeout (Origine sconosciuta:1)
<anonymous> (webpack:/node_modules/vuetify/lib/directives/ripple/index.js:115)
setTimeout (Origine sconosciuta:1)
hide (webpack:/node_modules/vuetify/lib/directives/ripple/index.js:112)
rippleHide (webpack:/node_modules/vuetify/lib/directives/ripple/index.js:200)
```

**Comment by KareemDa** [comment]
> Don't use v-text on components.

This should be documented and notifying users not to use `v-text`

**Comment by orangeagain** [comment]
I meet same problem!
here is single App.vue file to reproduce problem
```
<template>
<v-app>
    <v-main>
        <v-container fluid class="gray lighten-5 mb-9">
            <v-row dense class="yellow lighten-5 mb-9">
                <v-col v-for="card in cards" :key="card.title" :cols="3" class="d-flex child-flex green">
                    <v-card rounded="xl" @click="onClickImage(card.title)">
                        <v-responsive :aspect-ratio="9/9">

                            <v-img :aspect-ratio="9/16" :src="card.src" class="white--text align-end" gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.5)">
                                <v-card-title v-text="card.title"></v-card-title>
                                <template v-slot:placeholder>
                                    <v-row class="fill-height ma-0" align="center" justify="center">
                                        <v-progress-circular indeterminate color="grey lighten-5"></v-progress-circular>
                                    </v-row>
                                </template>
                            </v-img>

                            <!-- <v-expand-transition> -->
                                <v-overlay :value="card.cover" absolute class="transition-fast-in-fast-out v-card--reveal" style="height: 100%;">
                                    <v-container fluid fill-height>
                                        <v-btn color="primary" v-on:click="onCardSelect(card)">
                                            Select
                                        </v-btn>
                                    </v-container>
                                </v-overlay>
                            <!-- </v-expand-transition> -->
                        </v-responsive>
                    </v-card>
                </v-col>
            </v-row>
        </v-container>
    </v-main>
</v-app>
</template>

<script>
export default {
    name: 'App',

    components: {},

    data: () => ({
        cards: [
            { title: 'Pre-fab homes', src: 'https://cdn.vuetifyjs.com/images/cards/house.jpg', readly: true, cover: false },
            { title: 'Favorite road trips', src: 'https://cdn.vuetifyjs.com/images/cards/road.jpg', readly: true, cover: false },
            { title: 'Best airlines', src: 'https://cdn.vuetifyjs.com/images/cards/plane.jpg', readly: true, cover: false },
            { title: 'Pre-fab homes2', src: 'https://cdn.vuetifyjs.com/images/cards/house.jpg', readly: true, cover: false },
            { title: 'Best airlines2', src: 'https://cdn.vuetifyjs.com/images/cards/plane.jpg', readly: true, cover: false },
            { title: 'Best airlines23', src: 'https://cdn.vuetifyjs.com/images/cards/plane.jpg', readly: true, cover: false },
        ],
    }),
    methods: {
        onClickImage(selectedCard) {
            const found = this.cards.find(card => card.title === selectedCard);

            if (!found.cover)
                found.cover = true
        },
        onCardSelect(card) {
            console.log("onCardSelectBtn:" + card.title)
        }
    },
};
</script>

```

**Comment by jaegar-wolf** [comment]
Same problem on a v-btn without v-text, I put :ripple="false" on my v-btn to patch it.

**Comment by davidplappert** [comment]
I am getting this same error.

**Comment by lesliewu1** [comment]
> Re

Do you know why the v-text was causing this error?

**Comment by lesliewu1** [comment]
> Sorry for interrupting. I'm faced with same issue. Component code: `<v-btn :color="saveButtonColor" :loading="saveStatus === 'L'" v-text="saveButtonText" @click="saveCheckList" />`
> 
> Error occurs after some time (100-500ms) after click. After troubleshooting I got that it's related with changing "v-text" or ":loading" values. Changing other properties doesn't make that behaviour.
> 
> _Version: Windows 7 Node 13.14.0 vue 2.6.11 vuetify 2.3.4 vuetify-loader 1.6.0_

Do you know why the v-text was causing this error?

**Comment by Tofandel** [comment]
If you read the thread, it's explained and solved..
https://github.com/vuetifyjs/vuetify/issues/11792#issuecomment-659168048
