### ISSUE TITLE
IOS / Mobile Safari pickers show activator text-field cursor on top

### ISSUE THREAD

**Issue by aalakoski** [vuetifyjs/vuetify#1179]
### Steps to reproduce
Shows on Vuetify components demo page on IOS/Mobile (iPhone 6 Safari used)

### Versions

Vuetify v0.14.7
IOS Safari on Mobile (iPhone 6 used)

### What is expected ?

Opened dialog is the top most shown element on page.

### What is actually happening ?

With all pickers (date / time), when used as a dialog, the cursor is shown/blinking on top of the dialog from underlying "activator" v-text-field element. Screenshot from actual device illustrating the issue (cursor blinking near 3rd of July day).

![img_0840](https://user-images.githubusercontent.com/23035199/28754788-7d80e752-7555-11e7-8364-9021b5cde984.PNG)

### Reproduction Link

https://vuetifyjs.com/components/pickers
All the examples having involving dialog.

**Comment by johnleider** [comment]
Fixed with #1162

**Comment by johnleider** [comment]
This is a bug with Safari, this will happen with any input under a fixed element.
