### ISSUE TITLE
[Bug Report] v-data-table shows incorrect item number when using server side pagination

### ISSUE THREAD

**Issue by Liu233w** [vuetifyjs/vuetify#11796]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
- click `next page` button on footer 3 times

### Expected Behavior
It shows `16-20 of 20`

### Actual Behavior
It shows `11-15 of 20`

### Reproduction Link
<a href="https://codepen.io/liu233w/pen/vYLdPXM?editors=101" target="_blank">https://codepen.io/liu233w/pen/vYLdPXM?editors=101</a>

**Comment by KaelWD** [comment]
Works for me in chrome 83 and firefox 78

**Comment by Liu233w** [comment]
It turned out to be an issue with my userscript rather than vuetify.... Sorry to bother you.
