### ISSUE TITLE
[Bug Report] Calendar event vertical stack order is not working

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#11799]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Check on page load.

### Expected Behavior
The order of the events to be A,B,C,D (same as in array).

### Actual Behavior
Its showing C,A,B,D. It may be putting C on top because it has a longer date.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/rNxdaOQ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F" target="_blank">https://codepen.io/sneaky666/pen/rNxdaOQ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F</a>

### Other comments
Is there any way to use the same ordering as in the supplied array?

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
