### ISSUE TITLE
[Feature Request] v-menu should provide prod "open-on-right-click", because left click event often bind multiple actions

### ISSUE THREAD

**Issue by feitianhouren** [vuetifyjs/vuetify#11805]
### Problem to solve
When left click event bind an action, other action need to be bound to right-click event.

### Proposed solution
add a new prop "open-on-right-click" which provide the function to designates whether menu should open on activator right click.

**Comment by MajesticPotatoe** [comment]
This can already be done pretty easily using `@contextmenu` & `v-model`
<https://vuetifyjs.com/en/components/menus/#absolute-position-without-activator>

**Comment by MajesticPotatoe** [comment]
duplicate o

**Comment by feitianhouren** [comment]
Thank you!
