### ISSUE TITLE
[Bug Report] Error occured when I run "npm run build" command

### ISSUE THREAD

**Issue by TabrizGulmemmedov** [vuetifyjs/vuetify#11803]
![2020-07-07_1047](https://user-images.githubusercontent.com/40621376/86730445-97c58b80-c03f-11ea-9801-cd084564f7ed.png)

**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
asdad

### Expected Behavior
asdd

### Actual Behavior
asdsd

### Reproduction Link
<a href="https://github.com/eschirtz/foobar" target="_blank">https://github.com/eschirtz/foobar</a>

**Comment by jacekkarczmarczyk** [comment]
i'm getting 404 on your reproduction

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
