### ISSUE TITLE
[Bug Report] Date picker - don't show the good week numbers

### ISSUE THREAD

**Issue by Guizboule** [vuetifyjs/vuetify#11806]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1) Create date picker
2) Add the "show-week" props

### Expected Behavior
For the week of the 1 July, the week number must be 27.

### Actual Behavior
For the week of the 1 July, the week number must be 27 but the date picker shows 26.

### Reproduction Link
<a href="https://codepen.io/guizboule/pen/PoZROgZ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdate-pickers%2F" target="_blank">https://codepen.io/guizboule/pen/PoZROgZ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdate-pickers%2F</a>

**Comment by KaelWD** [comment]
Related: #9764, #10926

2020 week one starts on December 29, 2019; or December 30 with `first-day-of-week="1"` (ISO8601 standard)

> The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year (i.e. of January) in it  

> If 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in W01. If it is on a Friday, it is part of W53 of the previous year. If it is on a Saturday, it is part of the last week of the previous year which is numbered W52 in a common year and W53 in a leap year. If it is on a Sunday, it is part of W52 of the previous year.

**Comment by KaelWD** [comment]
Looks like you also have to set `locale-first-day-of-year="4"` for it to work correctly. America doesn't seem to have an actual standard for this, it should be ISO by default imo 

https://devblogs.microsoft.com/oldnewthing/20160311-00/?p=93144

**Comment by Guizboule** [comment]
I also set the `locale-first-day-of-year="1"`, to start the week by monday.

This year is a leap year so there should be 53 full weeks, but the datetime picker shows only 52

[https://en.wikipedia.org/wiki/ISO_week_date](https://en.wikipedia.org/wiki/ISO_week_date)
