### ISSUE TITLE
[Bug Report] Year picker width on IE 11

### ISSUE THREAD

**Issue by deraw** [vuetifyjs/vuetify#11809]
### Environment
**Vuetify Version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Click the text field to show the date picker in the menu

### Expected Behavior
The width of the picker is correct

### Actual Behavior
The width of the picker is incorrect

### Reproduction Link
<a href="https://codepen.io/Deraw/pen/RwrMxvV?editable=true&editors=101" target="_blank">https://codepen.io/Deraw/pen/RwrMxvV?editable=true&editors=101</a>

### Other comments
This only appears on the year picker, other pickers are fine, the issue is more annoying when using the picker in birthdate mode
As a workaround, I'm using `display: flex;` instead of `display: inline-flex;` on the `v-picker--date`

**Comment by deraw** [comment]
Here's a screenshot of the behavior without the workaround:
![screenshot-live browserstack com-2020 07 07-15_17_24](https://user-images.githubusercontent.com/10298932/86788758-ce62cc80-c066-11ea-9cd3-6847f198f680.png)

**Comment by johnleider** [comment]
I cannot reproduce this as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by deraw** [comment]
Thank you for your reply @johnleider! I've checked again and it was due to our code, we're applying `max-width: 100%` globally and it was applied on `.v-picker__body`, which caused the issue on IE 11. Sorry for the waste of time, I'll be more carefull when reporting issues on IE!
