### ISSUE TITLE
[Bug Report] VApp dark and light props

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#11800]
### Environment
**Vuetify Version:** 2.3.3
**Last working version:** 1.5.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
Try to set the prop dark or light on a vApp and it does nothing, they used to exist and they seem to still be referenced when looking with vue devtools.. They just do nothing at all
Looking at the doc they seem to have been removed but I don't understand why and see reason for them to have been removed.. Sure you can still set the theme via the vuetify options.. But that doesn't fully replace the prop when working with multiple instance, it also used to be a very convenient way to change the theme

### Expected Behavior
To change the theme like they used to instead of having to set it in Vuetify options (theme provider is not suitable for this)

### Actual Behavior
Props light and dark don't affect the theme of the app

### Reproduction Link
<a href="https://codepen.io/Tofandel/pen/bGEvdpQ" target="_blank">https://codepen.io/Tofandel/pen/bGEvdpQ</a>

**Comment by MajesticPotatoe** [comment]
There are no `light`/`dark` props for `v-app`. Light and dark themes in a global scope are handled via the `dark` property on the theme object, and can be switch by setting `this.$vuetify.theme.dark`
https://vuetifyjs.com/en/customization/theme/#light-and-dark
