### ISSUE TITLE
[Bug Report] Changing to V-Main from V-Content Stops Navigation Draw And App Bars Working (Dark Pre Made Layout)

### ISSUE THREAD

**Issue by kinger251285** [vuetifyjs/vuetify#11812]
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera
**OS:** Windows 10, Linux

### Steps to reproduce
I originally had my project setup with the Dark pre-made layout for my admin backend. Received errors stating v-content was outdated and to use v-main. Everything working fine with v-content. Changed to v-main, temporarily worked (maybe cached although cleared browser cache multiple times) and then all of a sudden navigation drawers would work but wouldnt change the size of v-main. The app bar sat on top of v-main. Basically v-main was a full screen container and was not effected by anything else.

### Expected Behavior
Shrink/expand when navigation drawer is open/closed. Be sized to take into account app bar and nav bar as well as navigation drawers.

### Actual Behavior
As explained above

### Reproduction Link
<a href="https://codepen.io/kinger251285/pen/yLeKjwZ" target="_blank">https://codepen.io/kinger251285/pen/yLeKjwZ</a>

**Comment by johnleider** [comment]
The reproduction doesn't work.

**Comment by kinger251285** [comment]
Typical its working as expected on the codepen. https://codepen.io/kinger251285/pen/yLeKjwZ

When was v-main added? maybe i need to update my vuetify?

**Comment by kinger251285** [comment]
ran npm vuetify update and was missing id="app" in the main div. seems to have fixed the problem.
