### ISSUE TITLE
[Documentation] Make v-label and v-message documented components

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#11819]
### Problem to solve
When making custom input fields using v-input, it can be desirable to use common input field building components like v-label or v-message.

Here is a concrete example. I'm creating an input field which allows a user to specify to numbers use to make a number range. This input field uses v-input as a wrapper, and contains two text fields to specify the min and max values. There is built in validation to ensure that only numbers and a valid range are specified. I want to be able to support robust styling features just like those found throughout components like v-text-field. I can't support input field styles like outline, or solo or others if I cannot have the ability to directly access and use v-label and v-message. Not to mention that using these undocumented components means that there are no guarantees that their API's will remain stable. I don't HAVE to use v-label or v-message, I could make my own components, but using a component library is supposed to help me not have to do something like that.

### Proposed solution
Making these component a documented one can help with building complex form input components; especially if the developer is trying to pattern the component with the same robust styling capabilities as those found elsewhere in vuetify.

**Comment by MajesticPotatoe** [comment]
Both `v-label` & `v-message` are not intended to be used publicly as they are internal to v-input/v-text-field, which is why they are not documented. Maybe in v3 that may change, dunno.
