### ISSUE TITLE
[Bug Report] Unable to position a v-menu popup closer than 12px from the top

### ISSUE THREAD

**Issue by mattnathan** [vuetifyjs/vuetify#11818]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Place a menu close to the top of the page and open the menu.

### Expected Behavior
The menu opens with the top of the popup aligning with the top of the activator

### Actual Behavior
The top of the popup is hard coded to a minimum distance of 12px from the top of the page

### Reproduction Link
<a href="https://codepen.io/mattnathan/pen/VwexLBr" target="_blank">https://codepen.io/mattnathan/pen/VwexLBr</a>

### Other comments
I have a layout where my application toolbar is 56px tall with a menu button in it vertically centered, this places the button 10px from the top of the page. When you activate the menu it gets positioned 12px from the top of the page instead of at 10px where the button is causing the top 2px of the activator button to show underneath the menu popup

**Comment by NathanStrutz** [comment]
I have the same problem, but with the left. The same calculation appears to be causing interference. I have a full-window-width application and a menu on the top left. I want them to be flush against the window edge, though their height is automatically correct.
