### ISSUE TITLE
[Feature Request] v-divider should have size props

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#11817]
### Problem to solve
can't set the size of v-divider

### Proposed solution
should have size props

`size="medium"` or `size="4px"`

**Comment by jacekkarczmarczyk** [comment]
Is this about the width of the divider or about the height?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
