### ISSUE TITLE
[Feature Request] v-menu activator does not know the menu is disabled

### ISSUE THREAD

**Issue by mwgamble** [vuetifyjs/vuetify#11814]
### Problem to solve
The activator should indicate to the user that the menu is disabled. When using a button as the activator, this can be achieved by making the button present its disabled state. Right now, the button remains enabled despite the fact that clicking it will do nothing.

### Proposed solution
Pass a `disabled` attribute in the `attrs` prop passed to the activator slot. If you're using `v-bind="attrs"` in your template (as recommended by the documentation), this will automatically take effect.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
