### ISSUE TITLE
[Feature Request] Implement "variations"-switch for sass-colorpack

### ISSUE THREAD

**Issue by therealshark** [vuetifyjs/vuetify#11820]
### Problem to solve
When using the a-la-carte installation with $color-pack, classes for all the different shades are generated. A more finetuned generation of the color classes will help to lessen the amount of generated classes and therefore remove potentially unneeded code.

In my current project, we never use the lighten/darken modifiers but still like to use the `color` and `color--text` ones.

### Proposed solution
Vuetify 2.3.0 brought the variations switch for primary/.. colors generated at runtime. A similar switch could be added to the sass variables to specify that only the base colors without variations are getting generated. This could be done like so: `$color-pack-generate-variations: true !default;`

There might be more useful switches to finetune the behaviour even more like `$color-pack-generate-text` to enable/disable generation of the color--text classes etc.

**Comment by therealshark** [comment]
Looking through the code this might be as easy as changing this line:
https://github.com/vuetifyjs/vuetify/blob/07696371534c4f699a19b695d7307ecfe5498c06/packages/vuetify/src/styles/generic/_colors.scss#L33
To be:
```sass
@else if ($color_type != 'shades' and $color-pack-generate-variations) {
```

But i am not very deep inside the vuetify sourcecode :)

**Comment by johnleider** [comment]
This is all changing for version 3.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
