### ISSUE TITLE
[Documentation] vuetify is not imported in CodeSandbox linked in Vuetify Issue Creator

### ISSUE THREAD

**Issue by alexandre-le-borgne** [vuetifyjs/vuetify#11821]
### Environment

**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Click on CodeSandbox on the page Vuetify Issue Creator https://issues.vuetifyjs.com/

### Expected Behavior
Vuetify should be ready to be used

### Actual Behavior
Vuetify is not in dependencies and not used in the template https://codesandbox.io/s/vue

### Reproduction Link
<a href="https://issues.vuetifyjs.com/" target="_blank">https://issues.vuetifyjs.com/</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify-issue-helper/issues/49

**Comment by alexandre-le-borgne** [comment]
404 Not found

**Comment by jacekkarczmarczyk** [comment]
Issue helper repository is not public, not sure why
