### ISSUE TITLE
[Bug Report] Color fix for v-select in readonly mode

### ISSUE THREAD

**Issue by vinz** [vuetifyjs/vuetify#11828]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
For a readonly V-Select text color is grey rather than black.
This is confusing the user when he looks at a form with all text input and select input fields.
some are black, while some are grey.

### Expected Behavior
Readonly Select text should be black in color just like text fields.

### Actual Behavior
Font Color is grey and is confusing users.

### Reproduction Link
<a href="https://codepen.io/vinayc1990/pen/wvMjQZK" target="_blank">https://codepen.io/vinayc1990/pen/wvMjQZK</a>

### Other comments
This is a simple fix but a very impactful, our users are confused and are asking us why this looks the way it is. Please consider it a priority.

**Comment by KaelWD** [comment]
Oversight from the fix for #11504

@johnleider some of those removed `isDisabled` uses were correct.
