### ISSUE TITLE
[Bug Report] Blur added to gradients on v-img when image not supplied

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/vuetify#11826]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
This is a hangover from the fix for #11729 - applying gradients without an image is now working but there is a default blur of 2px being applied due to style .v-image__image--preload

### Expected Behavior
Gradient is applied with no additional effects

### Actual Behavior
blur applied creates a darkened rim around the area

### Reproduction Link
<a href="https://codepen.io/davydnorris/pen/Bajdyzg" target="_blank">https://codepen.io/davydnorris/pen/Bajdyzg</a>

From previous bug report - bottom app bar was broken previously, now gradient works but you can see the blur on it, not present on the top two once the image loads

**Comment by davydnorris** [comment]
@KaelWD - did you happen to see this additional problem? Appears that v-image__image--preload style is applied and isn't getting removed from the bar if there's no image to load, and that's what's causing the added blur

**Comment by johnleider** [comment]
This is a non-standard usage of the `v-img` component. I can understand the ease of use with the property though. In v3 we may have a directive specifically for this so keep your eyes peeled!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by davydnorris** [comment]
@johnleider please see the previous bug that was reported - this is a standard and documented usage of v-img in an app bar that had an issue, and the supplied fix introduced this further bug.
