### ISSUE TITLE
[Feature Request] Date picker header slots

### ISSUE THREAD

**Issue by thomasraydeniscool** [vuetifyjs/vuetify#11832]
### Problem to solve
Allows adding custom elements to the date picker header where you currently cannot.

This also ensures custom elements also react to the date pickers existing responsiveness logic.

See below design is nearly impossible to replicate without header slots.

![Frame 44 (1)](https://user-images.githubusercontent.com/28379549/87142461-24d64200-c2d7-11ea-9c1b-c42c581e5a0f.png)

### Proposed solution
Add slots for prepend and append inside the date picker header (above and below the date indicator).

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
