### ISSUE TITLE
[Feature Request]  Title in grouping bar in v-data-table

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#11839]
### Problem to solve
Currently the property name is displayed and not the header text

### Proposed solution
Show header text

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
