### ISSUE TITLE
[Documentation] A nonexistent property "open-on-focus" is described in v-menu

### ISSUE THREAD

**Issue by mcmimik** [vuetifyjs/vuetify#11837]
### Environment

**Browsers:** Google Chrome
**OS:** Mac OS 10.15.5

### Steps to reproduce
Find "open-on-focus" property in API and make sure that this prop is not in the source: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.ts

### Expected Behavior
It would be nice to have this prop in Vuetify.

### Actual Behavior
Unfortunately, this prop is not in v-menu. But it is in the docs for some reason.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/menus/#api" target="_blank">https://vuetifyjs.com/en/components/menus/#api</a>

### Other comments
This property would be especially useful in the autocomplete component (inside "menu-props" prop).

**Comment by KaelWD** [comment]
It comes from the activatable mixin: https://github.com/vuetifyjs/vuetify/blob/5ab3d416ce9bf41ae6c3aea03d6abeca0a8170af/packages/vuetify/src/mixins/activatable/index.ts#L34

It doesn't work in `menu-props` because v-select activates the menu itself instead of using the activator slot.
