### ISSUE TITLE
[Feature Request] Custom grouping label v-data-table

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#11834]
### Problem to solve

It would allow to edit the label of the grouped headings to be able to translate it in other languages

### Proposed solution
Add props to translate the tag such as itemsPerPageAll in dataFooter

**Comment by joergwork** [comment]
I would also like to have an icon instead the text. The ability to change the text would be really appreciated.

https://github.com/vuetifyjs/vuetify/blob/ee620cf56f0c360380c2d709925748e6742ea7ce/packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts#L12-L20

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10425
