### ISSUE TITLE
[Documentation] Snackbars documentation has an error in the timeout property

### ISSUE THREAD

**Issue by speasley** [vuetifyjs/vuetify#11836]
### Environment

**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.5

### Steps to reproduce
Use `:timeout="-1"` on a `v-snackbar`

### Expected Behavior
`:timeout="-1"` keeps snackbar open indefinitely

### Actual Behavior
`:timeout="0"` keeps snackbar open indefinitely

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/snackbars/#snackbars" target="_blank">https://vuetifyjs.com/en/components/snackbars/#snackbars</a>

### Other comments
Keep up the good work.

**Comment by MajesticPotatoe** [comment]
Please confirm you are using the latest version of vuetify. This was changed in 2.3 per release notes.
