### ISSUE TITLE
[Bug Report] v-img lazy-src not working when image returns null (empty db field) - Workaround included

### ISSUE THREAD

**Issue by kinger251285** [vuetifyjs/vuetify#11831]
### Environment
**Vuetify Version:** 2.2.33
**Last working version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
As per codepen. When dynamically using images within a for loop, the lazy-src does not display when null is returned. Not all images are filled by the user. Maybe i should also use placeholder? This solution worked until i recently changed the way i stored images. As per codepen it is not working.

Previously i had the below:
```
:src=" '/'+image.src"
```
I have since changed the way i store my urls and therefore no longer need the forward slash so removed this as per the codepen. 

A workaround is to use the below:
```
:src=" ''+image.src"
```

Maybe i should be using place holder alongside lazy-src but this seems counter intuitive when the lazy-src can cover both bases. 

### Expected Behavior
Lazy src to display whilst loading and when an image returns null

### Actual Behavior
Does not display when null is returned.

### Reproduction Link
<a href="https://codepen.io/kinger251285/pen/yLeKjwZ" target="_blank">https://codepen.io/kinger251285/pen/yLeKjwZ</a>

**Comment by KaelWD** [comment]
`typeof null === 'object'` because javascript
