### ISSUE TITLE
[Bug Report] Outlined Snackbar transparency issue

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#11835]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Edge 83.0.478.61
**OS:** Mac OS 10.15.5

### Steps to reproduce
1. Create an Outlined Snackbar
2. You'll see the background is transparent (as intended)

### Expected Behavior
Add a class called `v-snack--has-background` to apply a background (white for example) to an outlined Snackbar.

### Actual Behavior
`content-class` doesn't fix it since it only adds a background to the content text area.

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/rNxKGeR" target="_blank">https://codepen.io/johnjleider/pen/rNxKGeR</a>

### Other comments
- Request based on discord (elite-sponsors) conversation here: https://discord.com/channels/340160225338195969/379379426959294464/731244057879380054
- Tagging @johnleider per his request too.

**Comment by jaxn** [comment]
I don't understand why the background would ever intentionally be transparent on `v-snackbar`. It makes sense on `v-alert`, but snackbars are different b/c they float over unknown content (similar to `v-dialog`).

If you have a `v-navigation-drawer` on the left and you set the `v-snackbar` to bottom left and outlined, you will see the drawer through the snackbar. 

If you have a full page of content, then the content will show the outlined snackbar.

**Comment by johnleider** [comment]
It wasn't intentional, just an oversight.

**Comment by megaroeny** [comment]
@johnleider @MajesticPotatoe just linked this issue to something else that's almost identical, for Banners: https://github.com/vuetifyjs/vuetify/issues/12081
