### ISSUE TITLE
[Bug Report] anchor tag / nuxt-link color theme persists when toggling theme in Nuxt layout beforeCreate, created or mounted lifecycle hooks

### ISSUE THREAD

**Issue by sankhagowit** [vuetifyjs/vuetify#11833]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.14.6

### Steps to reproduce
nuxt v2.13.3
@nuxtjs/vuetify v1.11.2

When using Vuetify with Nuxt and toggling the light/dark theme in layouts/default.vue in either the beforeCreate, created, or mounted hooks the color applied to the `.v-application a` CSS selector does not change

### Expected Behavior
The anchor color should be from the theme that is specified in the lifecycle hooks of layouts/default.vue. Instead the anchor color stays with the default theme in the vuetify configuration (vuetify.theme.dark, default false) found in nuxt.config.js

### Actual Behavior
The color for anchor tags (`.v-application a` CSS selector) does not switch to the specified theme. It stays with default theme was in the vuetify option configuration

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-x8wvq?file=/layouts/default.vue" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-x8wvq?file=/layouts/default.vue</a>

### Other comments
If you remove the anchor color specification from the Vuetify theme configuration anchor color defaults to the primary color and this incorrect behavior is still observed.

If you toggle the vue theme between light and dark with a button (so after the nuxt app has fully loaded) the theme correctly switches as expected.

**Comment by Moxie1776** [comment]
I am having a problem toggling dark/light mode also. If this code is present anywhere in the project then my nav drawer will not render the names (I have sub lists). As soon as I click any item to navigate it will populate and is fine.

`<v-btn icon>
  <v-icon
    change-mode
    :color="$vuetify.theme.dark ? 'yellow lighten2' : 'indigo darken2'"
    @click.stop="$vuetify.theme.dark = !$vuetify.theme.dark"
    v-text="'mdi-theme-light-dark'"
  />
</v-btn> `

**Comment by stuft2** [comment]
@Moxie1776 I think you're experiencing a different problem than the OP. 

**This problem is occurring with more than just the anchor tag styles, such as any text or button styles. Toggling the dark theme off and then back on correctly updates the css that is applied to the text and buttons. Refreshing the page however, returns the user to the default theme albeit with a black/gray background.

**Comment by stuft2** [comment]
Possibly related:
- https://github.com/vuetifyjs/vuetify/issues/9453#issuecomment-604217303
- https://github.com/vuetifyjs/vuetify/pull/9503

**Comment by sankhagowit** [comment]
thanks you for tagging and looking into this.

I've updated the codepen to hopefully more clearly show the issue by adding a switch to toggle the dark theme on and off which clearly shows how the styles are correctly applied after toggling but not when the theme is set in the beforeCreate hook.

**Comment by albertleao** [comment]
I managed to get around this by setting the dark theme inside a setTimeout function with a timeout of 0 for now

**Comment by sankhagowit** [comment]
@albertleao do you have codesandbox / fiddle showing this work around? I wasn't able to get non-default colors for anchor tags using setTimeout to toggle the dark theme.

**Comment by renoirb** [comment]
This has been brought to my attention, I'll have a look.

**Comment by stuft2** [comment]
Will this be fixed in Vuetify 2.x or is it planned for release in Vuetify 3.x?

**Comment by maketa521** [comment]
Possibly related:
- [https://github.com/nuxt-community/vuetify-module/issues/406](https://github.com/nuxt-community/vuetify-module/issues/406)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
