### ISSUE TITLE
[Bug Report] textarea solo-inverted color consistency

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#11848]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Use solo-inverted in textarea

### Expected Behavior
Text color change to white on focus

### Actual Behavior
Text color stay black on focus

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/VweBXPz" target="_blank">https://codepen.io/dev1ldragon/pen/VweBXPz</a>

**Comment by vlourme** [comment]
I allow myself to bump this issue, I have it too.
However, I think it only applies when dark-mode is used.
