### ISSUE TITLE
[Bug Report] V-Autocomplete not support use no results value 

### ISSUE THREAD

**Issue by jakubstankowski** [vuetifyjs/vuetify#11846]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Opera 68.0.3618.173
**OS:** Windows 10

### Steps to reproduce
1. Go to reproduction link
2. Click on the input and put value which is not exist like "7"

### Expected Behavior
When user want use value which is not exist in search results, should comfortable use it.

Example:
1. Try find "7" number in autocomplete
2. When is not available value is not dissapered, but use after click search can use it

### Actual Behavior
When something value is not available input is clear, and user cant use another value

### Reproduction Link
<a href="https://codepen.io/jakubstankowski/pen/ZEQjXNN" target="_blank">https://codepen.io/jakubstankowski/pen/ZEQjXNN</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/components/combobox/
