### ISSUE TITLE
[Bug Report] Tooltips add padding when in a navigation drawer

### ISSUE THREAD

**Issue by BenHall-1** [vuetifyjs/vuetify#11840]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
1) Load data into servers in src/components/layout/LeftBar.vue
2) Watch the image move to the right

### Expected Behavior
When adding a tooltip to a list item, if using an image, the list item gets a margin on the left of 16px

### Actual Behavior
Images / list items should stay centred

### Reproduction Link
<a href="https://github.com/ChatorApp/Client" target="_blank">https://github.com/ChatorApp/Client</a>

### Other comments
Margin seems to be added by `.v-application--is-ltr .v-list-item__action:last-of-type:not(:only-child), .v-application--is-ltr .v-list-item__avatar:last-of-type:not(:only-child), .v-application--is-ltr .v-list-item__icon:last-of-type:not(:only-child)`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
