### ISSUE TITLE
[Feature Request] Dynamic data table width

### ISSUE THREAD

**Issue by Akkarine** [vuetifyjs/vuetify#11852]
### Problem to solve
Allows users to change width of sertain column.

### Proposed solution
Add option for v-data-table, that adds draggable borders at headers.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
