### ISSUE TITLE
[Bug Report] v-time-picker doesn't support standard LT format

### ISSUE THREAD

**Issue by gregveres** [vuetifyjs/vuetify#11855]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
I started with the codepen from the docs and changed "time: null" to "time: '8:00 AM'". When you click on the text field to bring up the menu with the t-time-picker, you will see the time picker freak out with a bunch of NaN values. In fact it just wont be able to recover at all. 
The issue is the space between 8:00 and AM. It works fine if the space is removed. 

The problem is that the space is an output of a standard LT format. 

### Expected Behavior
I expected the component to be able to take 8:00 AM as input and work just like 8:00AM. 

### Actual Behavior
NaN values make their way through various internal variables causing the component to no longer work. 

### Reproduction Link
<a href="https://codepen.io/gregveres/pen/KKVxXzv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftime-pickers%2F" target="_blank">https://codepen.io/gregveres/pen/KKVxXzv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftime-pickers%2F</a>

### Other comments
I am working around it by removing whitespace from the input before I send it to v-time-picker and then I take the output of the picker and put it back through an LT format again to get it into a format for the user. I built a component to hide all of this because I have a bunch of time pickers in my code. But the problem is that once i wrap it in a component, I can't use the output of one time picker as a min/max input to another one because it can't parse it.

**Comment by jacekkarczmarczyk** [comment]
> I can't use the output of one time picker as a min/max input to another one because it can't parse it

you can convert it in your wrapper to HH:MM format same as you're removing space from picker's value

**Comment by KaelWD** [comment]
That regex could use some work
![image](https://user-images.githubusercontent.com/16421948/87518612-d4d6f100-c6c3-11ea-9d7d-c48af1737736.png)

**Comment by gregveres** [comment]
> > I can't use the output of one time picker as a min/max input to another one because it can't parse it
> 
> you can convert it in your wrapper to HH:MM format same as you're removing space from picker's value

Oh, I see what you are saying. yes. I was just passing the min and max through to the underlying v-time-picker, but I could do the same thing to both min and max that I am doing to the main time value. That is true.
