### ISSUE TITLE
[Feature Request] v-data-table item.<name> slot should include index

### ISSUE THREAD

**Issue by gregveres** [vuetifyjs/vuetify#11850]
### Problem to solve
if I have a set of data where the only unique identifier for a row is the index in the array, I can't do any operations initiated from v-data-table because I can't find the object to work on. Here are some examples. 
I have a table of objects from the database, but before I commit them to the database, their Ids are zero. Since I can create any number of these objects before saving, I will have many objects in the table with id zero.
But I also want to allow operations such as delete. if the Id is zero, I just delete the object from the table because it hasn't been saved yet. But which element is it? How can I delete it from the table without being able to search for it in the table? 
Or, I want to edit that particular row and I want to have a cancel operation so that if they hit cancel on the dialog, the item isn't updated in the table. 
Each of these things would be so much easier if I knew the index of the item I am working on.

But the <template v-slot:item.<name>> doesn't provide index in the value that is passed to it. According to the docs, it is only passed item, header and value. Can you add index to that list?

### Proposed solution
If the object that was passed to the <template v-slot:item.<name>> included 
```JS
{
  item,
  header,
  value,
  index,
}
```
then doing these types of things would be so much easier.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/10646
