### ISSUE TITLE
[Feature Request] v-file-upload ignores uploaded file if the name hasn't changed

### ISSUE THREAD

**Issue by donalmurtagh** [vuetifyjs/vuetify#11853]
### Problem
`v-file-upload` ignores a file if its name/path matches that of the file currently wrapped by the component. Therefore given the following steps

1. file `/tmp/foo.txt` is uploaded to a `v-file-upload`
1. file `/tmp/foo.txt` is modified
1. file `/tmp/foo.txt` is uploaded again

When the file is uploaded the second time it is ignored and therefore (for example) any validation rules specified via the `rules` prop will not be executed.

### Proposed solution
[Here is a workaround](https://codepen.io/domurtag147/pen/GRoBBRO?editors=1011) that uses a `ref` and an undocumented method of `v-file-upload` to ensure that the input's value is set to null before any file is uploaded. This is not an ideal solution because after these steps

1. file `/tmp/foo.txt` is uploaded 
1. the component is clicked
1. the "choose file" dialog is cancelled

The file stored in the component should ideally be `/tmp/foo.txt`, but it will actually be null.

**Comment by donalmurtagh** [comment]
From memory, the steps above will reproduce the issue on Chrome, but not on Firefox

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
