### ISSUE TITLE
[Documentation] unclear value description for row:click event

### ISSUE THREAD

**Issue by PROgram52bc** [vuetifyjs/vuetify#11866]
### Problem to solve
Currently, the `row:click` event only emits an `item`, but according to the documentation, the `row:click` event emits the following object
```
any, {
  expand: (value: boolean) => void,
  headers: TableHeader[],
  isExpanded: boolean,
  isMobile: boolean,
  isSelected: boolean,
  item: any,
  select: (value: boolean) => void
}
```
which is not really clear to me what it means. 
For example, if I want to do something based on whether the current row is selected, as the user clicks the row, it would be nice if I can access the `isSelected` property from the event emitted.

### Proposed solution
Have the `row:click` event emit the following object instead of just the `item` that contains the data associated with the row:
```
{
  expand: (value: boolean) => void,
  headers: TableHeader[],
  isExpanded: boolean,
  isMobile: boolean,
  isSelected: boolean,
  item: any,
  select: (value: boolean) => void
}
```

**Comment by jacekkarczmarczyk** [comment]
event has 2 arguments, first is the item, second is related data
https://codepen.io/jkarczm/pen/ZEQqExg?editable=true&editors=101

**Comment by MajesticPotatoe** [comment]
Ill add a note to the description to clarify.

**Comment by PROgram52bc** [comment]
Thanks!
