### ISSUE TITLE
v-radio wrap text if too long on small screen

### ISSUE THREAD

**Issue by latsyrct** [vuetifyjs/vuetify#1186]
### Steps to reproduce
Open the [codepen](https://codepen.io/anon/pen/BdjbYq) and shrink the screen up to 372px (this simulates the small screen size)

### Versions

vuetify 0.14.7

### What is expected ?

It should show full label text on the screen, instead of 3 dots (...) at the end.

### What is actually happening ?

![image](https://user-images.githubusercontent.com/8469292/28761215-9fad15dc-75df-11e7-9ac8-8e7958a80e94.png)

### Reproduction Link

https://codepen.io/anon/pen/BdjbYq

**Comment by jacekkarczmarczyk** [comment]
adding `.input-group--selection-controls label { max-width: calc(100% - 32px) }` solves the issue, but i'm not sure if this rule doesn't break anything else

**Comment by johnleider** [comment]
The ellipsis break-point is where it is expected.
