### ISSUE TITLE
[Feature Request] pass an array as data prop to v-data-table

### ISSUE THREAD

**Issue by mbariola** [vuetifyjs/vuetify#11860]
### Problem to solve
Most of the data I need to display comes from CSV files or JSON 2-dimensional arrays and as such are in the form
[[data11, data12, data13.....],
[data21, data22, data23.....]]

v-data-table requires an object prop to be passed as data. So far, I have not found a simple way to pass the array as is except reparse/transform it into an object creating keys for each item.

Maybe I am missing something or overcomplicating something obvious?

### Proposed solution
Allow for v-data-table to use 2-dimensional JSON arrays as data

**Comment by KaelWD** [comment]
> except reparse/transform it into an object creating keys for each item

This doesn't have to be complicated, you can actually use object spread:
```js
items.map(item => ({ ...item })
```

https://codepen.io/kaelwd/pen/WNrgMRj?editors=1010

**Comment by mbariola** [comment]
Darn, I had tried spread but clearly applied it in the wrong way, also thanks for showing how to reference the corrsponding indexes in the headers. Thanks for the super quick response @KaelWD .

Still, what do you think for next versions, maybe to have v-data-table `typeof ` the items and convert automagically? 

Best,

M.
