### ISSUE TITLE
[Bug Report] Passing non-number string to errorCount breaks validation messages

### ISSUE THREAD

**Issue by HeadAdmiral** [vuetifyjs/vuetify#11864]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Add  `rules` and `error-count` to any component which implements the `validatable` mixin and provide a non-number string, such as `abc` to the `error-count` prop. Validation still occurs, but the error messages will no longer display.

### Expected Behavior
`validatable` should verify that the value passed to `errorCount` is valid, and if not, throw an error. Validation messages should still appear.

### Actual Behavior
`validatable` accepts any string input and will break if the string is not a number. Validation messages do not appear.

### Reproduction Link
<a href="https://codepen.io/HeadAdmiral/pen/zYrJyxo?editors=1011" target="_blank">https://codepen.io/HeadAdmiral/pen/zYrJyxo?editors=1011</a>

**Comment by johnleider** [comment]
It's an alpha-numeric property that is intended to accept a valid number.

The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
