### ISSUE TITLE
[Bug Report] File input is not emitting the input event

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#11863]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
See codepen, the file input does not give an alert, the text input is.

### Expected Behavior
Emitting an input event

### Actual Behavior
it doesn't emit an input event

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/mdVGKzr" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/mdVGKzr</a>

### Other comments
Normally this wouldn't be an issue since you can just use the on change. Except in my actual project i'm trying to create a wrapper around the file input with `v-bind="$attrs"  v-on="$listeners"` but this way the `v-model` is not working correctly

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model
