### ISSUE TITLE
[Bug Report] v-datatable (server-side) error: TypeError: _sort.split is not a function

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#11869]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.14.6

### Steps to reproduce
visit the link -> see error message in console

### Expected Behavior
can populate the datatable

### Actual Behavior
cannot populate the datatable

### Reproduction Link
<a href="https://codesandbox.io/s/eager-roentgen-o3h7u" target="_blank">https://codesandbox.io/s/eager-roentgen-o3h7u</a>

### Other comments
vuetify server side datatable API is extremely bad created and documented. the docs doesn't provide real world example. if my sandbox works, I will contribute to the docs

**Comment by jacekkarczmarczyk** [comment]
The errors comes from jsonplaceholder api, apparently the data you're sending is not in the format they expect and I can't find any documentation on what is the expected format of _order and _sort

**Comment by KaelWD** [comment]
https://blog.eleven-labs.com/en/json-server/#filters-sort--operators

```
params: {
  _order: this.dataTable.paginationOptions.sortDesc.join(','),
  _page: this.dataTable.paginationOptions.page,
  _limit: this.dataTable.paginationOptions.itemsPerPage,
  _sort: this.dataTable.paginationOptions.sortBy.join(',')
}
```

And items should be `res.data`, not `res`
