### ISSUE TITLE
[Feature Request] Treeview select is only available for children values

### ISSUE THREAD

**Issue by jakubstankowski** [vuetifyjs/vuetify#11861]
### Problem to solve
It will be great when the select option is only available in children values

Example:
 - user in Applications value can only select the Applications child, not Applications

Let's test in example: https://codepen.io/jakubstankowski/pen/ZEQjXNN

### Proposed solution
It should be simple config in components parameters

![image](https://user-images.githubusercontent.com/36790120/87533406-da691280-c694-11ea-9868-7b42f588307d.png)

**Comment by KaelWD** [comment]
How is this different to #11813?
