### ISSUE TITLE
[Bug Report] VOverflowBtn collapses

### ISSUE THREAD

**Issue by manuelmeister** [vuetifyjs/vuetify#11879]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116, Mozilla Firefox
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Click on "Select font"
2. Select "Arial"

### Expected Behavior
"Arial" is visible

### Actual Behavior
Button only shows dropdown icon and the text is not visible anymore.

### Reproduction Link
<a href="https://codepen.io/manuelmeister/pen/YzwJMdO" target="_blank">https://codepen.io/manuelmeister/pen/YzwJMdO</a>

### Other comments
Only on clicking the adjacent button, "Arial" is revealed, and stays only, when a value is selected (such as "100%"), otherwise the width collapses again.

I think in my usecase (VOverflowBtn not being `editable`) in [VOverflowBtn.sass](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.sass#L114) it should be `.v-select__selections input` instead of `.v-select__selections` and the min-width on the input should be set to 0.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
