### ISSUE TITLE
[Bug Report] date-picker type 'year' generates :Invalid prop: custom validator check failed for prop "type".

### ISSUE THREAD

**Issue by totomaze** [vuetifyjs/vuetify#11878]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
use the component date-picker with the property type = "year"

### Expected Behavior
Working without an JS error in the console

### Actual Behavior
Working with a JS error in the console

### Reproduction Link
<a href="https://codepen.io/totomaze/pen/ZEQqZzz" target="_blank">https://codepen.io/totomaze/pen/ZEQqZzz</a>

### Other comments
vue.js:634 [Vue warn]: Invalid prop: custom validator check failed for prop "type".

found in

---> <VDatePicker>
       <VApp>
         <Root>

**Comment by jacekkarczmarczyk** [comment]
`type` can be only 'date' or 'month'
https://github.com/vuetifyjs/vuetify/issues/9096
