### ISSUE TITLE
[Bug Report] VToolbar with Image - Webkit

### ISSUE THREAD

**Issue by robsontenorio** [vuetifyjs/vuetify#11873]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
- Use Epiphany browser on linux
- Or Safari iOs
- Open reproduction link

This is the same example from docs.

https://vuetifyjs.com/en/components/toolbars/#prominent-w-background

### Expected Behavior
Image must be self contained to toolbar.

### Actual Behavior
Image leaks from toolbar.

### Reproduction Link
<a href="https://codepen.io/robsontenorio/pen/ZEQqrxx?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftoolbars%2F" target="_blank">https://codepen.io/robsontenorio/pen/ZEQqrxx?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftoolbars%2F</a>

### Other comments
Just noticed "contain: strict" property is invalid.

![image](https://user-images.githubusercontent.com/118955/87707840-2476f480-c778-11ea-8b2e-77353aa0696b.png)

**Comment by robsontenorio** [comment]
My workaround for now.

Not using `src` property from toolbar anymore.

```
<v-toolbar prominent
      :style="`background-image: url('/images/games/${game.id}_wide.jpg?${game.updated_at}'); background-size: cover; background-position: center center;`"
    >
```

**Comment by KaelWD** [comment]
Webkit and IE don't support `contain`, toolbar needs `position: relative`
