### ISSUE TITLE
[Bug Report] v-file-input multiple not working at all

### ISSUE THREAD

**Issue by terrygreen0606** [vuetifyjs/vuetify#11875]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
Please see the line 55 in this github code.
It is actually no need to reproduce. The sample v-file-input itself in the vuetify documentation doesn't work too.

### Expected Behavior
If I upload multiple files in v-file-input (with multiple property, true and I am using v-chip in selection slot), it should show all the selected files in the chips.

### Actual Behavior
But if I upload the second, third, fourth file, it always overwrites the previous file.
And when I console log out the files, the array length of files is always just 1.

### Reproduction Link
<a href="https://github.com/e-pluribus-unum/crmdms-dev-app/blob/development/src/views/dashboard/email/Index.vue" target="_blank">https://github.com/e-pluribus-unum/crmdms-dev-app/blob/development/src/views/dashboard/email/Index.vue</a>

### Other comments
I have googled out a lot to solve this issue, but they just say it should work with multiple property.
Could you please try in the vuetify documentation itself? It also doesn't work there.

**Comment by terrygreen0606** [comment]
![product](https://user-images.githubusercontent.com/54503006/87746728-e2a38800-c823-11ea-9b0d-3ab11ef104ef.png)
Just for FYI.
Simple as it is. This "multiple" property should work and the chips for muliply uploaded files should all show, but just one chip shows.
It definitely overrides the previous file.

**Comment by bepsvpt** [comment]
When using `multiple` prop, you should select all files you want to upload at once.

![file-multiple](https://user-images.githubusercontent.com/8221099/88021885-de97a300-cb60-11ea-8b6a-76e046b9bee4.gif)

**Comment by nekosaur** [comment]
What @bepsvpt said. This is in line with how native file input works.

**Comment by terrygreen0606** [comment]
Yes, you're right. What about adding one by one?

**Comment by jacekkarczmarczyk** [comment]
> What about adding one by one?

@terrygreen0606 https://github.com/vuetifyjs/vuetify/issues/8812

**Comment by terrygreen0606** [comment]
Can that v-file-upload component show all the selected files (that are added one by one) as chips?

**Comment by YounggilLee** [comment]
> deleteChip (item) {
        this.items.splice(this.items.indexOf(item), 1)
        this.items= [...this.items]
      },
