### ISSUE TITLE
[Bug Report] VDataTable locale not working

### ISSUE THREAD

**Issue by thegoldgoat** [vuetifyjs/vuetify#11876]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
1. Use VDataTable
2. Set a locale, e.g. "it-IT" for italian

### Expected Behavior
Footer text should be localized e.g. `Rows per page` => `Righe per pagina`

### Actual Behavior
Text is in English

### Reproduction Link
<a href="https://codepen.io/andreasomaini/pen/bGEmzKB" target="_blank">https://codepen.io/andreasomaini/pen/bGEmzKB</a>

### Other comments
Workaround, set to the VDataTable component:
```
:footer-props="{
                'items-per-page-text': 'Righe per pagina:',
                'page-text': '{0}-{1} di {2}',
                'items-per-page-all-text': 'Tutte'
              }"
```

**Comment by KaelWD** [comment]
The locale prop is only used for sorting, it is passed to [`new Intl.Collator(locale, ...`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)

**Comment by thegoldgoat** [comment]
> The locale prop is only used for sorting, it is passed to [`new Intl.Collator(locale, ...`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)

Thanks for your response!

I see what you mean, I suggest changing the documentation, as it now states:

> Sets the locale of component. Used for translating internal text strings.

Or, maybe, it makes sense if that prop translates the internal text strings as it says in the documentation, since the translations are already in the `locale` folder, see:
https://github.com/vuetifyjs/vuetify/blob/25feaf97eb39503a6d82166c0b6d486699e2e729/packages/vuetify/src/locale/it.ts#L8

**Comment by KaelWD** [comment]
No other component has a locale prop to translate strings, it's set globally in the Vuetify object: https://vuetifyjs.com/en/customization/internationalization/

Only english is loaded by default to keep the bundle size down, so you'd have to import whatever language you want to use anyway.

**Comment by thegoldgoat** [comment]
I understand, so I guess it is a documentation error after all?

Thanks again for your help

**Comment by thegoldgoat** [comment]
Can't find in the docs that `locale` prop, shouldn't it be [here](https://github.com/vuetifyjs/vuetify/blob/3acc307d52494fb67ff1d43b4868ce475ac3476d/packages/docs/src/lang/en/components/DataTables.json#L109)?

**Comment by thegoldgoat** [comment]
Ok I found it, it is [here](https://github.com/vuetifyjs/vuetify/blob/bcb917e5ce64cde0051b5891cb7ca7fa84cc1b14/packages/docs/src/lang/en/components/Data.json#L14)

Should we change it @KaelWD ?
