### ISSUE TITLE
[Bug Report] v-spacer inside v-snackbar is not working properly

### ISSUE THREAD

**Issue by grainrigi** [vuetifyjs/vuetify#11883]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Linux x86_64

### Steps to reproduce
Place two individual inline elements inside v-snackbar and place v-spacer between them.

### Expected Behavior
two elements are displayed in same row and there is some space between them.

### Actual Behavior
the second element is placed under the first element.

### Reproduction Link
<a href="https://codepen.io/grainrigi/pen/LYGXLwR" target="_blank">https://codepen.io/grainrigi/pen/LYGXLwR</a>

### Other comments
This occurs after https://github.com/vuetifyjs/vuetify/commit/d44b590e51d23e54fda6d99ea69540bdade192af.
Since v-snackbar__content lacks flex related styles (`display: flex; align-items: center; justify-content:space-between;`), v-spacer is treated as a normal blocklevel element.
Adding these styles manually fixes the problem.

**Comment by mrfrase3** [comment]
I can confirm this issue, I got around it by wrapping the contents in a `v-row` component. Mischief managed.

**Comment by johnleider** [comment]
Even though this is a regression we are moving this to wontfix as the changes were primarily made to achieve the MD2 spec and it's styling is in line with what v-alert__content does.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
