### ISSUE TITLE
[Feature Request] Quill Integration/component

### ISSUE THREAD

**Issue by BenHayat** [vuetifyjs/vuetify#11884]
### Problem to solve
Having an integrated editor in Vuetify.

### Proposed solution
I'd like to propose Vuetify team to integrate Quill (https://quilljs.com/) as a Vuetify component in Vuetify packaging for V3.
Thanks

**Comment by MajesticPotatoe** [comment]
duplicate #2403 / #3550
We also don't allow dependencies in our components.
