### ISSUE TITLE
[Bug Report] router-view is hidden under v-app-bar

### ISSUE THREAD

**Issue by SvenjaJeschke** [vuetifyjs/vuetify#11887]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.5.17
**Browsers:** Opera 68.0.3618.197
**OS:** Windows 10

### Steps to reproduce
I have an v-app-bar and my router-view from vue-router. Everything in the router components is hidden under the app bar. I tried all options for v-app-bar but nothing fixed it.

### Expected Behavior
router-view components shown under the app bar

### Actual Behavior
components hidden under app bar

### Reproduction Link
<a href="https://github.com/SvenjaJeschke/harsh-souls-shop" target="_blank">https://github.com/SvenjaJeschke/harsh-souls-shop</a>

### Other comments
This is probably an issue on my side, so I'd be happy if you could tell me what I'm doing wrong. Thanks.

**Comment by jacekkarczmarczyk** [comment]
Sorry, this is not a valid reproduction. Most probably you're missing `<v-main>`

Please reach out to us in our [Discord community](https://community.vuetifyjs.com) in case my guess is wrong.
