### ISSUE TITLE
[Feature Request] Expose select event of VSelectList inside VComboBox

### ISSUE THREAD

**Issue by PeratX** [vuetifyjs/vuetify#11891]
### Problem to solve
Currently we can only listen `change` and `input` events of `VComboBox` which will be triggered when user select a menu item or click somewhere else on the page. (when input lose focus)
The feature expose the `select` event of VSelectList which can be only triggered when user clicked on the dropdown menu.

### Proposed solution
Add `select` event to `VComboBox`

**Comment by KaelWD** [comment]
What would you use this for?

**Comment by PeratX** [comment]
I use a VComboBox as a search box. When user typing in the box, program will search results automatically.
However, if user click outside the input, they did not meant to search it (vuetify will trigger input and change event and the program will search the value)

I think the program should only search the value when user press enter or click on the menu.

See https://fm.peratx.net
https://github.com/iTXTech/FlashMaster

**Comment by PeratX** [comment]
By the way, I am trying to listen the event manually, but it seems not working
```
<v-combobox ref="pnInput"/>

created: {
    addListener(){
        setTimeout(() => {
                this.$refs.pnInput.$refs.menu.$on("click", () => {
                    console.log("I got it")
                })
            })
    }
}
```

**Comment by PeratX** [comment]
I have figure this out
```js

                            setTimeout(() => {
                                if (this.$refs.pnInput.$refs.menu.$children.length > 0) {
                                    let list = this.$refs.pnInput.$refs.menu.$children[0].$children[0]
                                    list.$on("select", e => {
                                        this.box = e.value
                                        this.partNumber = this.box
                                        this.query()
                                    })
                                }
                            }, 100)
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
