### ISSUE TITLE
[Documentation] Using Vuetify in external component lib

### ISSUE THREAD

**Issue by loicmarie** [vuetifyjs/vuetify#11893]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Linux x86_64

### Steps to reproduce
1. Create app and lib : `vue create app-test && vue create lib-test` with maxi-best-of options for both
2. In both projects :
  a. Add Vuetify : `vue add vuetify` (with default preset)
  b. In both `tsconfig.json`, add "vuetify" in `compilerOptions.types` section
3. In `lib-test` (here we build the lib according to [official doc](https://cli.vuejs.org/guide/build-targets.html#library)) :
  a. Create `src/components/ComponentTest.vue` and add the (A) code below
  b. Replace all code in `src/main.ts` with (B)
  c. In `package.json`, set `"main": "./dist/lib-test.umd.js"` (same result with Common module) and `"types": "./typings/index.d.ts"`
  d. Create `typings/index.d.ts` and put the (C) code
  e. Build the lib : `npx vue-cli-service build --target lib --watch --name lib-test src/main.ts`
4. In `app-test` :
  a. Add the lib : `yarn add ../lib-test`
  b. In `src/App.vue`, put the (D) code to use `ComponentTest` imported from `lib-test`
  c. Serve it : `yarn serve`

Codes :

(A)
```html
<!-- src/components/ComponentTest.vue -->
<template>
  <v-app-bar app clipped-left>
    <v-toolbar-title>Application</v-toolbar-title>
  </v-app-bar>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class ComponentTest extends Vue {}
</script>
```

(B)
```js
// src/main.ts
import Vue_, { VNode, PluginObject } from 'vue'
import ComponentTest from './components/ComponentTest.vue'

export default function PluginTest (Vue: typeof Vue_, options: any): void {
  Vue.component('ComponentTest', ComponentTest)
}

export {
  ComponentTest
}
```
(C)
```js
// typings/index.d.ts
import Vue_ from 'vue'
import ComponentTest from './components/ComponentTest.vue'
export default function PluginTest(Vue: typeof Vue_, options: any): void
export { ComponentTest }
```

(D)
```html
<!-- src/App.vue -->
<template>
  <v-app>
    <ComponentTest></ComponentTest>
  </v-app>
</template>

<script lang="ts">
import Vue from 'vue';
import { ComponentTest } from 'lib-test';

export default Vue.extend({
  name: 'App',
  components: {
    ComponentTest
  },
});
</script>
```

### Expected Behavior
When working on an app along with a custom component library, we should be able to use the `$vuetify` variable as well

### Actual Behavior
We get a lot of errors with `this.$vuetify` being undefined in `lib-test` components, such as :

```
getter for watcher "computedHeight": "TypeError: Cannot read property 'breakpoint' of undefined"

found in

---> <VAppBar>
       <ComponentTest> at src/components/ComponentTest.vue
         <VApp>
           <App> at src/App.vue
             <Root>
```

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
Whoever has at least two apps using Vuetify will need to refactor the components (and so the possibly nested Vuetify components) in a custom, external and versionable lib, as explained in the official doc :
https://cli.vuejs.org/guide/build-targets.html#library

It seems Vuetify lacks of documentation explaining how to create a components library wrapping vuetify components, and how to use it in multiple apps.

My intuition was to use the above steps, but I found it very difficult to understand how to use the same Vue instance properties (such as `$vuetify`) in both library (or plugin) and application.

If it is not a bug, could you please consider this as a doc request and explain us **how to develop a vuetify app along with an external component lib (that uses vuetify components too)** ?

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify/discussions/4068#discussioncomment-24984
