### ISSUE TITLE
[Bug Report] yarn build failed with exit code 2

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#11898]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 0.0.0 (non-relevant)
**Browsers:** Chrome 81.0.4044.138
**OS:** Linux x86_64 (ubuntu 20.04 LTS)

### Steps to reproduce
Do as described in getting-started/contributing;
Fork vuetify, then clone it locally.
```cd vuetify```,
delete yarn.lock and ```yarn install```,
```yarn build```

### Expected Behavior
should finish build successfully

### Actual Behavior
lerna error, yarn  run build exited 2
![vuetifyLernaError](https://user-images.githubusercontent.com/13683050/87986805-46f56e80-cae6-11ea-95ac-3854bf9e5987.png)

I tried it with both node 12.18.2 and node 14.5.0

### Reproduction Link
I don't have any, I'll try creating something in codesandbox (never done something like this)

**Comment by MajesticPotatoe** [comment]
What version of yarn are you using

**Comment by KaelWD** [comment]
> delete yarn.lock 

Don't do that.

**Comment by KaelWD** [comment]
Ok what does `yarn` fail with then? Lockfiles exist for a reason, deleting them will usually break things even harder.

**Comment by Tzahile** [comment]
I'm sorry gents, apparently the decision to delete yarn.lock **is** a mistake.
I succeeded now following guidelines. I guess `yarn` alone failed because I had node v 14 on my first attempt.

Thank you for your kind help
