### ISSUE TITLE
Tabs are not following url after page refresh

### ISSUE THREAD

**Issue by technixp** [vuetifyjs/vuetify#119]
Hey, problem is in
https://github.com/vuetifyjs/vuetify/blob/master/src/components/tabs/Tabs.vue#L67 

You should use `this.index = this.index || 0`  to check if tab index is already defined on init.

I can create PR

**Comment by johnleider** [comment]
This is actually resolved in the upcoming patch. Will leave this open until that releases.

**Comment by johnleider** [comment]
New version is out, but I admit I did not get to this. Can you see if your problem is still persisting? Thank you.

**Comment by technixp** [comment]
I don't see router support, but tried it with href and forcing url. Doesn't work. 

Checked source, it goes to 1st tab always. 
https://github.com/vuetifyjs/vuetify/blob/master/src/components/tabs/Tabs.vue#L96

**Comment by johnleider** [comment]
Can you post a codepen or jsfiddle of what specifically you are trying to do?

**Comment by technixp** [comment]
here it is, but i don't know what you want to see here http://codepen.io/anon/pen/JEeZbR/ 
url should update on activating tab.

In 0.8.7 with router it was adding #{id} to url and this.index fix made tabs follow after page refresh

**Comment by johnleider** [comment]
Thank you, I'll work on a fix.
