### ISSUE TITLE
[Bug Report] Broken logic in 2.3.5 (Cannot read property 'hasAttribute' of undefined)

### ISSUE THREAD

**Issue by yariksav** [vuetifyjs/vuetify#11903]
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.13.0

### Steps to reproduce
It appears after commit "use xs breakpoint on inital render when hydrating": (https://github.com/vuetifyjs/vuetify/pull/11842/files)
This commit has broken all dialogs in vuetify-dialog (npm module), because sometimes vue component doesn't have $el in global hook beforeMount

For example , when component  was mounted with vm.$mount() function and connect to DOM later
![image](https://user-images.githubusercontent.com/2553313/88075922-1bc05d00-cb82-11ea-99c1-e85444c6fc37.png)

### Expected Behavior
check is this.$el exists

### Actual Behavior
now always error "Cannot read property 'hasAttribute' of undefined"

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2-dialog-example-kgehb" target="_blank">https://codesandbox.io/s/vuetify-2-dialog-example-kgehb</a>

**Comment by Martin7mind** [comment]
im also having this issue when running my jest tests :/

**Comment by patrioticcow** [comment]
same here

![image](https://user-images.githubusercontent.com/751813/88097770-899e6180-cb4d-11ea-851b-f9d723c6a9af.png)

**Comment by luiselizondo** [comment]
The same. Several tests are broken because of this.

**Comment by kleingtm** [comment]
I can confirm that `yarn upgrade vuetify@2.3.4` fixes the issue.

**Comment by Martin7mind** [comment]
when will this be relased? :)

**Comment by terazus** [comment]
Also confirming that version 2.3.5 breaks my tests.

**Comment by ewoelfel** [comment]
my tests are running again under 2.3.5, thx

**Comment by jsilva-pt** [comment]
> ere.. same error on all components in storybook

I also had to revert to 2.3.4 on my storybook project

**Comment by Ignigena** [comment]
Will we get a hotfix release or is this just going out with next week's patch?

**Comment by MajesticPotatoe** [comment]
Looking to get this out today.

**Comment by derdem** [comment]
I am running into the Problem that our Teamcity pipeline is throwing the mentioned error for all tests dealing with vuetify. When I run my jest tests locally everything is fine. Tested it with version 2.2.15, 2.3.4 and 2.3.5 => always the same result

**Comment by mean-cj** [comment]
2.3.4 , 2.3.5 the same  problem.

**Comment by jb0071913** [comment]
Only a problem for me on 2.3.5, 2.3.4 is fine

**Comment by MajesticPotatoe** [comment]
Apologize for the delay, running into CI issues trying to get the patch out. This fix will be released as soon as that is resolved. 

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
