### ISSUE TITLE
[Documentation] v-hover example not good in dark mode

### ISSUE THREAD

**Issue by QimatLuo** [vuetifyjs/vuetify#11906]
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Mac OS 10.15.5

### Steps to reproduce
Setup theme as Dark mode.
Try the example.

Only Hover list, and Transitions examples can see the affect.
Other examples looks bad in the dark mode.

### Expected Behavior
Should show affects in the example.

### Actual Behavior
Looks nothing happens in some example.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/hover/" target="_blank">https://vuetifyjs.com/en/components/hover/</a>

### Other comments
I know there is no bugs in the example. Just not good in the dark mode.
May need to change the example for good to demo both in light mode or dark mode.

**Comment by farukSRKNT** [comment]
Hello, it seems solved. Can you close the issue?
