### ISSUE TITLE
[Bug Report] App-drawer disappear when zoom in/out in touch screen

### ISSUE THREAD

**Issue by dicruzg** [vuetifyjs/vuetify#11904]
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 3.0.0-rc.2
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
1 - Zoom in, using the laptop touch screen (Surface Laptop in my case)
2 - Zoom out 

### Expected Behavior
On zoom out, I expected that the page goes to previous state (normal).

### Actual Behavior
On zoom out, the app-drawer disappear and never appear again until refresh the page

### Reproduction Link
<a href="https://github.com/OptimalBit-LLC/ccpa-frontend" target="_blank">https://github.com/OptimalBit-LLC/ccpa-frontend</a>

### Other comments
I reproduce the same behavior the official Vuetify page

**Comment by johnleider** [comment]
We do not support Vue 3 yet and the reproduction link is no longer valid.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
