### ISSUE TITLE
[Bug Report] Takes lot of time in hot reloading by any scss change when custom variable.scss get used 

### ISSUE THREAD

**Issue by teawithsatyam** [vuetifyjs/vuetify#11901]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10, Linux

### Steps to reproduce
As per instruction for variables customization mentioned here - https://vuetifyjs.com/en/customization/sass-variables/ , I created `styles/variables.scss` and tried to override variables. It worked, however now when your server is up and you try to modify any of the variables in there, it got stuck at 40% for quite some time.

Error - 
`40% building 0/95 modules 95 active ...er\dist\cjs.js??ref--9-oneOf-3-3!D:\work\vuetify-hotreload-issue\node_modules\vuetify\src\styles\main.sass`

I dig around it for some time and what I found somewhere related to it that each time it gets changes `sass-loader` rebuild everything from the beginning. Although I am not completely sure on this

## Reproduce the issue
1. Start local server
2. Update any variable inside `variables.scss`

### Expected Behavior
It should not be stuck at `40%` and should be fast in hot reloading

### Actual Behavior
Hot Reload get stuck at `40%` for a long duration

### Reproduction Link
<a href="https://github.com/teawithsatyam/vuetify-hotreload-issue" target="_blank">https://github.com/teawithsatyam/vuetify-hotreload-issue</a>

**Comment by KaelWD** [comment]
As you said, it has to recompile every stylesheet in the project when you change the variables file. You can reduce the amount of styles loaded by changing the vuetify import to `'vuetify/lib/framework'`: https://vuetifyjs.com/en/customization/presets/#compilation-time

**Comment by satyamqainfotech** [comment]
> As you said, it has to recompile every stylesheet in the project when you change the variables file. You can reduce the amount of styles loaded by changing the vuetify import to `'vuetify/lib/framework'`: https://vuetifyjs.com/en/customization/presets/#compilation-time

Hi @KaelWD  thanks for the quick reply,  I tried above stated but I can see the very negligible difference in the delay, it still stuck around 40% but now for a component reference sass file  - `40% building 0/58 modules 58 active ...components\VPicker\VPicker.sass`

**Comment by KaelWD** [comment]
It isn't "stuck", it's processing multiple files in parallel. The more components you use the smaller the difference will be. If you have `import something from 'vuetify/lib'` anywhere in the project then the `'vuetify/lib/framework'` change won't make any difference.
