### ISSUE TITLE
[Feature Request] Chip Component text field

### ISSUE THREAD

**Issue by JokerMartini** [vuetifyjs/vuetify#11907]
### Problem to solve
We need the ability to have Tag editing support, the combobox does not support this. It needs support for chips in the text field which is currently not supported.

### Proposed solution
It would be great to be able to use chips in inputs like in the following demo:
https://material.angularjs.org/latest/demo/chips

**Comment by KaelWD** [comment]
You can edit chips by double-clicking them, same as the angular example. It is a bit buggy though, keep an eye on #6364
