### ISSUE TITLE
[Feature Request] What's the progress of Vuetify 3.0

### ISSUE THREAD

**Issue by doddgu** [vuetifyjs/vuetify#11908]
### Problem to solve
I tried the Vue 3.0 and Vite. But vuetify 2.x didn't work.

### Proposed solution
waiting for vuetify 3.0

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/introduction/roadmap/

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
