### ISSUE TITLE
[Bug Report] v-data-table expanded-item slot is missing key

### ISSUE THREAD

**Issue by doox911** [vuetifyjs/vuetify#11909]
### Environment
**Vuetify Version:** 2.3.4
**Last working version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Linux, Windows

### Steps to reproduce
Expand the first line. Clicking counter, then, without collapsing the first line, expand the second. The counter remains the same.

### Expected Behavior
Rendrering

### Actual Behavior
Not rendering

### Reproduction Link
<a href="https://codepen.io/rodion-radarov/pen/gOPqgpY" target="_blank">https://codepen.io/rodion-radarov/pen/gOPqgpY</a>

**Comment by jacekkarczmarczyk** [comment]
expanded row is missing the key

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTable.ts#L415

**Comment by doox911** [comment]
> в расширенном ряду отсутствует ключ
> 
> https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTable.ts#L415

**Comment by doox911** [comment]
> expanded row is missing the key
> 
> https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTable.ts#L415

Why is he needed there? After all, it works without single-expand.

**Comment by KaelWD** [comment]
https://discordapp.com/channels/340160225338195969/351121729164410882/755403371485331468
