### ISSUE TITLE
[Bug Report] Min-height of v-text-field__details splits every even input underline 

### ISSUE THREAD

**Issue by PlaginDL** [vuetifyjs/vuetify#11917]
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
Screen: 1920x1080 14'', 125% scale. I don't have any other screens to check on them.
Checked on Chrome and Edge. Result is the same.

### Expected Behavior
Solid underline

### Actual Behavior
Underline is doubled

### Reproduction Link
<a href="https://codepen.io/PlaginLE/pen/NWxoZxx" target="_blank">https://codepen.io/PlaginLE/pen/NWxoZxx</a>

### Other comments
This thing fixed by using "min-height: (16+(x*4))px"

**Comment by jacekkarczmarczyk** [comment]
> This thing fixed by using "min-height: (16+(x*4))px"

Nope: https://codepen.io/jkarczm/pen/xxZBKvY

It's clearly a Chrome bug, can be reproduced without Vuetify:
https://codepen.io/jkarczm/pen/MWKxgZe?editors=1000

**Comment by KaelWD** [comment]
Can't reproduce in chrome 83.0.4103.106 on linux or chrome 84.0.4147.89 on windows (browserstack) or edge 84.0.522.40 (browserstack)

**Comment by KaelWD** [comment]
Follow for updates: https://bugs.chromium.org/p/chromium/issues/detail?id=1108755
