### ISSUE TITLE
[Feature Request] v-data-table component, automatically hide the column beyond the width

### ISSUE THREAD

**Issue by chaotianque** [vuetifyjs/vuetify#11918]
### Problem to solve
v-data-table component, automatically hide the column beyond the width

### Proposed solution
v-data-table component, automatically hide the column beyond the width

**Comment by chaotianque** [comment]
For example, if the width is set to 100, the text is too long, it will exceed the text box and will not be hidden. It is recommended to add a tooltip when the content is too long and hidden
![image](https://user-images.githubusercontent.com/17331025/88517359-4ea29f00-d021-11ea-9ead-0b521a46e7bc.png)

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
