### ISSUE TITLE
[Feature Request] add descriptions for Vuetify's tag completion in Vetur

### ISSUE THREAD

**Issue by octref** [vuetifyjs/vuetify#11912]
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Mac OS 10.15.3

### Steps to reproduce
- Clone repo
- `yarn add vuetify`
- Complete `<v-` in template. Don't see tag's descritpions

### Expected Behavior
See tag's descritpions

### Actual Behavior
Only have tag names. No tag descriptions.

### Reproduction Link
<a href="https://github.com/octref/veturpack" target="_blank">https://github.com/octref/veturpack</a>

![image](https://user-images.githubusercontent.com/4033249/88164929-72dc3580-cc47-11ea-9a2a-215adcf2ad51.png)

This is after `yarn add element-ui`.

![image](https://user-images.githubusercontent.com/4033249/88164940-77085300-cc47-11ea-9a12-60b21ace1296.png)

The issue is that `vuetify/dist/json/tags.json` has no `description` field.

I think including descriptions would provide users a better development experience.

![image](https://user-images.githubusercontent.com/4033249/88165072-b2a31d00-cc47-11ea-83e8-d71e43ed6c0b.png)

**Comment by robsontenorio** [comment]
Vuetify v3 doesn’t generate even “ vuetify/dist/json/tags.json”
