### ISSUE TITLE
[Documentation] Codepen examples not working

### ISSUE THREAD

**Issue by Javuto2** [vuetifyjs/vuetify#11919]
### Environment

**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 7

### Steps to reproduce
All codepen examples are broken because the CDN is throwing 404 when downloading Vuetify javascript and css file.

### Expected Behavior
Examples should load properly

### Actual Behavior
Throws an error stating it can't find Vuetify

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/combobox/" target="_blank">https://vuetifyjs.com/en/components/combobox/</a>

### Other comments
The reason is that it's downloading Vuetify from the CDN and throwing 404. I tested Text Input examples and they don't work either.
If you replace the library from "https://cdn.jsdelivr.net/npm/vuetify@2.3.6/dist/vuetify.min.js" to the one from the documentation "https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js" it loads the Javascript.
The CSS file also needs to be replaced.

**Comment by KaelWD** [comment]
CI is hard, 2.3.6 isn't properly out yet: https://github.com/vuetifyjs/vuetify/actions
