### ISSUE TITLE
[Feature Request] v-alert click event

### ISSUE THREAD

**Issue by johnscheineson** [vuetifyjs/vuetify#11929]
### Problem to solve
We implement v-alerts heavily in our app. Having to click the small 'X' button has become a nuisance for devs and users alike. It is important for users to be able to close these alerts, as they block the top navigation bar.

### Proposed solution
Implement a 'click' event on v-alert. Having the option to click anywhere on the alert to close it would significantly improve our UX.

**Comment by MajesticPotatoe** [comment]
can already do this with `.native`

**Comment by johnscheineson** [comment]
Thanks much, Andrew. I will do more research before posting to Vuetify
GitHub in the future.

John
