### ISSUE TITLE
[Feature Request] Suggest adding a shuttle box

### ISSUE THREAD

**Issue by chaotianque** [vuetifyjs/vuetify#11923]
### Problem to solve
Suggest adding a shuttle box

### Proposed solution
Suggest adding a shuttle box

**Comment by ibrahimBeladi** [comment]
What is a "shuttle box"?

**Comment by chaotianque** [comment]
Similar to this
![image](https://user-images.githubusercontent.com/17331025/88517589-a5a87400-d021-11ea-82d6-0aba901f797f.png)

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
