### ISSUE TITLE
Using nuxt/vuetify navigation drawer does not get updated as model change

### ISSUE THREAD

**Issue by zedryas** [vuetifyjs/vuetify#1192]
### Steps to reproduce

Maybe a bug, or a behavior that does seem consistent (might be i'm doing something wrong)

### Versions
I'm using Vuetify 0.14.7 and nuxt.js 1.0.0-alpha.5

### What is expected ?
I wish the navigation drawer to be closed when i'm not on the index page. To achieve this i've put in the state the menu informations, and the drawer wish is the Boolean value used by the `v-model` of the navigation drawer.
i'm sorry to not provide a JSBin but I don't think i can do it using nuxt.js

All menu information is on a menu.json as shown here:
```
[
  {
    "title": "Home",
    "icon" : "home", "to": "/"
  },
  {
    "title": "Warmup",
    "icon" : "flight_takeoff", "to": "/warmup"
  },
  ...
]
```
Here is the store
```
import menu from '~json/menu.json'

export const state = () => ({
  menu,
  drawer: true,
  pageTitle: undefined
})

export const mutations = {

  toggleDrawer: state => {
    state.drawer = !state.drawer
  },

  setPageTitle: (state, title) => {
    state.pageTitle = title
    state.drawer = title === 'Home'
  }
}

```
In order to catch route changes I've added a middleware
```
export default ({store, route}) => {
  const mitem = store.state.menu.filter(item =>
                  item.to.indexOf(route.name) >= 0
                )[0]
  const title = mitem ? mitem.title : 'Home'

  store.commit('setPageTitle', title)
}
```
And finally here is the layout
```
<template>
  <v-app>
    <v-navigation-drawer
      persistent
      v-model="drawer"
    >
      <v-list>
        <v-list-tile
          router
          v-for="(item, i) in menu"
          :key="i"
          :to="item.to"
        >
          <v-list-tile-action>
            <v-icon>{{ item.icon }}</v-icon>
          </v-list-tile-action>
          <v-list-tile-content>
            <v-list-tile-title>{{ item.title }}</v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-navigation-drawer>
    <v-toolbar fixed>
      <v-toolbar-side-icon @click.native.stop="toggleDrawer" />
      <v-toolbar-title>{{ drawer }}</v-toolbar-title>
      <v-spacer></v-spacer>
    </v-toolbar>
    <main>
      <v-container fluid>
        <nuxt />
      </v-container>
    </main>
  </v-app>
</template>

<script>

import { mapState, mapMutations } from 'vuex'

export default {

  methods: {
    ...mapMutations([ 'toggleDrawer' ])
  },

  computed: {
    ...mapState([ 'menu', 'drawer', 'pageTitle' ])
  }
}

</script>
```

Everything seems to be wired up, as when I refresh the page if i'm on the `index route` the drawer shows and on any other page the drawer is hidden.

As well the `v-toolbar-title` prints the expected results (drawer current value: true or false) as i click on the various `v-list-tile`, and when i click on the menu icon the drawer is shown/hidden accordingly but....

### What is actually happening ?
When i click on the various `v-list-tile` if the `v-toolbar-title` is correct, the navigation drawer keeps it's state and if let's say:

I first load the app on the index page the drawer is visible
I click on the warmup link the drawer remains visible even if the drawer value is indeed set to false

### Reproduction Link
Unfortunately as i've stated before I didn't succed to provide a JSBin with nuxt js. All i can say is that this behavious is systematic with the code provided.
Hopefully that won't discard me for a answer. 

Here's a gif that reproduce the issue
http://www.giphy.com/gifs/26n6DbdiajFEzzxQc

Thanks in advance

Seb

**Comment by Kylart** [comment]
It is indeed hard to provide a codepen or something like that with nuxt. The only solution for me would be to make a github repo but.. yea

Perhaps the `disable-route-watcher` would be what you are looking for? Check it at the bottom of [this page](https://vuetifyjs.com/components/navigation-drawers)

Another solution I could give if the one above does not work would be to add the `disable-route-watcher` prop and set your drawer to false. Then, only in your `index.vue` page, set up this:
```vue
<script>
export default {
  mounted () {
    if (!this.$store.state.drawer) {
      this.$store.commit('toggleDrawer')
    }
  }
}
</script>
```

I hope I did not misunderstand anything. yet, people will propbably be able to help you more with a simple github with this code.

**Comment by zedryas** [comment]
Thanks a lot your solution is working fine ;)

But i still do not understand. How come since the `drawer` computed property is updated accordingly the navigation drawer using the `v-model` sets to that drawer property does not get updated? 
Is that a normal behavior? i'm quite new but i expected as a computed property to be updated for the view to update accordingly
Is this a normal behavior?

And if u could walk me throught the solution you gave me would appreciate cause it's working but got no idea why? thanks in advance

If needed I can definitly set up a github with the basiscs needed.

**Comment by Kylart** [comment]
> Is this a normal behavior?

I must admit I do not know if this is expected behaviour, I don't think so. But your case is actually quite interesting and wasn't probably expected as well. @johnleider would tell if it is or not.

What happens is that the navigation drawer is by default following (in a sense) the route and for it, it _has_ to open on every route change.

I am curious though, which one of the solution worked out ? 😅

**Comment by zedryas** [comment]
Simply the first one ;)

It leads me to expect that it is an expected behaviour but I still find it weird as it seems to me that the behaviour choosen alters the principle of reactive components, no ?

**Comment by Kylart** [comment]
I think it might be unexpected behaviour too. Should ask someone of the dev team 😟

**Comment by johnleider** [comment]
The problem is you are trying to control the model when the drawer also controls the model on page change. In order for this to work properly, you need to wait for $nextTick so that Vue has completed calculating all of the model values.

**Comment by zedryas** [comment]
ty @johnleider 

If u have time just a quick newbie question.
Were i should best involve the nexttick ? in the created method ?

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
