### ISSUE TITLE
The proper way to remove paddings on v-expansion-panel

### ISSUE THREAD

**Issue by andreclemente** [vuetifyjs/vuetify#11925]
### Environment
**Vuetify Version:** 2.3.6
**Last working version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Kubuntu 20.04

### Steps to reproduce
Click on a expansion-panel-content

### Expected Behavior
There must be a way to disable the padding on the expansion panel content (__wrap)

### Actual Behavior
I can't find a way to remove the padding. (Red background)

### Reproduction Link
<a href="https://jsfiddle.net/ysw9865r/" target="_blank">https://jsfiddle.net/ysw9865r/</a>

### Other comments
If there is already a way, please tell me how can I do that. Thank you!

**Comment by icleolion** [comment]
Two options as far as I'm aware:

1. Override $expansion-panel-content-padding sass variable as listed in documentation, https://vuetifyjs.com/en/components/expansion-panels/ | https://vuetifyjs.com/en/customization/sass-variables/
2. Add your own CSS rule to override Vuetify's e.g. `.v-expansion-panel-content__wrap { padding: 0 !important; }`

**Comment by andreclemente** [comment]
Thank you
