### ISSUE TITLE
[Bug Report] v-model variable updates are ignored when updated within @input='func()' for v-textarea

### ISSUE THREAD

**Issue by reed-sandberg** [vuetifyjs/vuetify#11924]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 71.0.3578.80
**OS:** Linux x86_64

### Steps to reproduce
In the first v-textarea box in the codepen "Write a story (bug, won't limit)", type more than 10 characters

### Expected Behavior
The v-textarea box should limit input to 10 characters via @input="assertCharLimitBug(10, 'personalStoryBug')".

### Actual Behavior
Input is not limited

### Reproduction Link
<a href="https://codepen.io/reed-sandberg/pen/gOPEoYr" target="_blank">https://codepen.io/reed-sandberg/pen/gOPEoYr</a>

### Other comments
See the "assertCharLimit()" method for a workaround. If the substring() function arg 2 is decremented by 1, everything works as expected. You can see this by typing into the second v-textarea box "Write a story (limits but only by a workaround with limit-1)" where input is limited.

**Comment by jacekkarczmarczyk** [comment]
You need $nextTick https://codepen.io/jkarczm/pen/ZEQPvOM
