### ISSUE TITLE
[Bug Report] v-speed-dial does not work correctly without activator

### ISSUE THREAD

**Issue by gotenxds** [vuetifyjs/vuetify#11938]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
Hi, So I'm trying to use v-speed-dial without an activator, the docs specify that if you do this you need to stop event propogation on your own but they dont make it clear to what event,

I tried to make it work in my project, gave up and tried to make it work in codepen and gave up again after trying multiple versions.

What I tried
* Using `v-model` and computed properties
* Using `value` and `@input`
* Using just `value`
* using `native.stop.prevent`, on all click events and `@input` events, both on the buttons inside and outside the speed dial

### Expected Behavior
* Click on a button that changes the `value` prop of the speedial
* speed-dail opens
* click button again or anywhere outside the speed-dial, 
* speed dial closes

### Actual Behavior
* Click on a button that changes the `value` prop of the speed-dial
* speed-dial opens and immediately closes again (best outcome I managed)

### Reproduction Link
<a href="https://codepen.io/gotenxds/pen/oNbVyJp" target="_blank">https://codepen.io/gotenxds/pen/oNbVyJp</a>

### Other comments
This worked for me before, I'm not sure how, but once upgrading vuetify (and alot more stuff so It's hard for me to say where it broke) I noticed this stopped working.

**Comment by KaelWD** [comment]
> and alot more stuff so It's hard for me to say where it broke

You can use `git bisect` to determine which commit broke it. This hasn't ever been officially supported afaik.

**Comment by joshhoegen** [comment]
@gotenxds, your pen seems to work properly with me, but I have the same issues you experience, but *with* the activator. Do you have any updates?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
