### ISSUE TITLE
[Feature Request] Grid system complicated

### ISSUE THREAD

**Issue by Elfayer** [vuetifyjs/vuetify#11936]
### Problem to solve
I love Vuetify, but if I had to point one pain point, that would be the Grid system.

I think the grid system is overly complicated and unclear. The only way to *align* is by using `v-row`. The only way to *space* items is by using `v-col`. That works pretty well, up to the point where using vertical layout. Where we usually end up with:

```html
<v-col>
  <v-row>
    <v-col></v-col>
  </v-row>
  <v-row>
    <v-col></v-col>
  </v-row>
</v-col>
```
This is also a problem to use a `<v-spacer>` vertically, which I recently learned to fix using: `<v-row class="flex-column">`.

### Proposed solution
I recently had to use Material-UI with React. I do not like Material-UI, but if there is one thing they make easy, it's the Grid system. By allowing to make a `container` horizontal(default) or vertical: `<Grid container direction="column">`. And even allow a container to be an item (a col to be a row), which prevents adding extra v-row/v-col tags or add flex classes just to get access to *alignments* and/or *spacing*: `<Grid container item>`

```html
<Grid container direction="column">
  <Grid container item></Grid>
  <Grid container item></Grid>
</Grid>
```

I wish Vuetify had that. :heart:

**Comment by Yihao-G** [comment]
You may want to take a look at the deprecated `v-layout` and `v-flex`, which are just a wrapper of CSS Flexbox. They are deprecated in v2 in favour of Bootstrap-like `v-col` and `v-row` layouts.

**Comment by Elfayer** [comment]
@Yihao-G Hi, I am aware of what you describe. I am just saying it could be better, for the reasons detailed above.
There is no way using `<v-row>` and `<v-col>` to have access to both *alignement* (justify, align, etc.) and *responsivity* (sm, md, etc.)

**Comment by KaelWD** [comment]
> vertical layout
```html
<v-row>
  <v-col cols="12"></v-col>
  <v-col cols="12"></v-col>
  <v-col cols="12"></v-col>
</v-row>
```

> responsivity
v-row and v-col have breakpointed variants of all the props: `<v-row justify="center" justify-md="start">` `<v-col cols="12" md="4" order-lg="2">`

**Comment by Elfayer** [comment]
Thanks for the example. So that means that for a vertical layout, the recommended approach is to use a root row element followed by `<v-col cols="12">`?
That's not very intuitive, but that works. :thinking:

I would argue that the problem persists if you want only one col centered (hypothetical example):
```html
<v-row justify="center">
  <v-col>Title</v-col> <!-- will be centered -->
  <v-col cols="8">Some Input</v-col> <!-- will be centered -->
  <v-col>Some Button</v-col> <!-- align right without extra v-row? -->
</v-row>
```
But if it's the desired way, then I'd suggest adding an example in the docs (https://vuetifyjs.com/en/components/grids/). It's also confusing as of when to use `v-row`/`v-col` vs flex classes (https://vuetifyjs.com/en/styles/flex/).

I've already seen people going for:
```html
<v-row class="flex-column>
  <v-col></v-col>
  <v-col></v-col>
  <v-col></v-col>
</v-row>
```

**Comment by oliviertassinari** [comment]
> I recently had to use Material-UI with React. I do not like

@Elfayer Anything we could improve in Material-UI to make it enjoyable? 🙌 (*sorry for hijacking the thread a bit*)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
