### ISSUE TITLE
[Bug Report] "TypeError: Cannot read property 'hasAttribute' of undefined" thrown while mounting in Jest unit testing

### ISSUE THREAD

**Issue by qt911025** [vuetifyjs/vuetify#11930]
### Environment
**Vuetify Version:** 2.3.5
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Linux x86_64

### Steps to reproduce
Install and
`yarn test` or `npm test`

### Expected Behavior
Test functions well.

### Actual Behavior
Error occurs:
`[Vue warn]: Error in beforeMount hook: "TypeError: Cannot read property 'hasAttribute' of undefined"`

### Reproduction Link
<a href="https://github.com/qt911025/a-vuetify-error-reproduction" target="_blank">https://github.com/qt911025/a-vuetify-error-reproduction</a>

**Comment by MajesticPotatoe** [comment]
duplicate #11903
