### ISSUE TITLE
[Feature Request] Support Vue 2.3.2+ this.$ssrContext

### ISSUE THREAD

**Issue by zq1997** [vuetifyjs/vuetify#11935]
### Problem to solve
In version 2.3.2+, you can directly access the SSR context in a component as this.$ssrContext. In older versions you'd have to manually inject the SSR context by passing it to createApp() and expose it on the root instance's $options - child components can then access it via this.$root.$options.ssrContext.

### Proposed solution
I think just a small change should be made here, use this.$ssrContext if avaliable.
```js
    beforeCreate: function beforeCreate() {
      var options = this.$options;

      if (options.vuetify) {
        options.vuetify.init(this, options.ssrContext);
        this.$vuetify = Vue.observable(options.vuetify.framework);
      } else {
        this.$vuetify = options.parent && options.parent.$vuetify || this;
      }
    },
```

**Comment by KaelWD** [comment]
What problem does this solve? You still have `ssrContext` on the root instance alongside `vuetify`

**Comment by zq1997** [comment]
Well, using this new feature provided by Vue, we don't need to pass `ssrContext` any more new create Vue vm instances since it is already passed by `renderToString` function
