### ISSUE TITLE
[Feature Request] Keeping "label" and "label--active" class on "v-overflow-btn"

### ISSUE THREAD

**Issue by DevIsShortForDevil** [vuetifyjs/vuetify#11931]
### Problem to solve
I want to be able to keep the `label` on `v-overflow-btn` when I'm selecting an item or when an item is selected.

### Proposed solution
Right now when you open the item list the Label tag is removed and only renders if no item is selected or the item list is not open. the component could have an attribute to let us keep the label and add the `label--active` class the same way as `v-select` for example.

**Comment by mesqueeb** [comment]
@DevIsShortForDevil how to do this? I need to force label-active on my VTextField and VTextarea
