### ISSUE TITLE
[Feature Request] Have different bar colors in v-sparkline

### ISSUE THREAD

**Issue by mostafa7904** [vuetifyjs/vuetify#11939]
### Problem to solve
A mechanism that lets you change the color of bars in v-sparkline according to the value that they hold.
a question pointing to the same issue: https://stackoverflow.com/questions/63011818/have-different-bar-colors-in-vuetify-sparkline

### Proposed solution
I'm not much of an expert, but maybe have a new prop called bar-colors which accepts an array with the same length as the values array, that way we could have different colors for each bar.
An example:
`<v-sparkline type="bars" :value="values" :bar-colors="barColors"></v-sparkline>`

```
barColors: ["green" , "red"]
values:[1 , -3]
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by mostafa7904** [comment]
It's fine I can use other chart libraries. I have so many other feature requests. don't worry 😁
Always looking forward to improving the best framework out there.
