### ISSUE TITLE
[Bug Report] Broken reactivity when using multiple v-switch or v-checkbox

### ISSUE THREAD

**Issue by filip-z** [vuetifyjs/vuetify#11932]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
Disabling the first switch sets the second switch to a disabled state. This does nothing to the underlying v-model for the second switch. 

Clicking the second time on the first switch re-syncs the second switch, but de-syncs the first switch. 

### Expected Behavior
The first switch and the second switch are independent.

### Actual Behavior
The switch components show inconsistent behavior when they are placed one after another like this.

### Reproduction Link
<a href="https://codepen.io/filip-z/pen/xxZexBy" target="_blank">https://codepen.io/filip-z/pen/xxZexBy</a>

### Other comments
The same thing happens if there are two `<v-checkbox>` elements instead of two `<v-switch>` elements. If one element is `<v-checkbox>` and the other one is `<v-switch>` the issue does not appear.

Doing this with pure VueJS and using `<input type="checkbox" v-model="">` does not reproduce the issue.

Doing this with single `<p></p>` element inside the `<template>` eliminates this behvior.

**Comment by jacekkarczmarczyk** [comment]
> Doing this with pure VueJS and using <input type="checkbox" v-model=""> does not reproduce the issue.

Yes, it does: https://codepen.io/jkarczm/pen/mdVgyzR

You need to apply keys to your `<p>` elements: https://codepen.io/jkarczm/pen/ZEQZYqV
