### ISSUE TITLE
[Feature Request] Use CSS Grid for layout instead of Flexbox

### ISSUE THREAD

**Issue by James-Hudson3010** [vuetifyjs/vuetify#11948]
### Problem to solve
Flexbox is difficult to use when laying out Vuetify Apps

### Proposed solution
CSS Grid is designed for layout -- https://css-tricks.com/css-grid-replace-flexbox/

**Comment by KaelWD** [comment]
CSS grid is not a replacement for flexbox and is not suitable for class-based layout systems. The layout is currently defined in HTML by the classes you use, with css grid it's defined in the stylesheet instead. There's nothing stopping you from doing this yourself and combining it with the layout classes where suitable but it's not something that is likely to ever be seen in a framework like this.

**Comment by James-Hudson3010** [comment]
I agree that CSS Grid is not a replacement for flexbox. CSS Grid is complementary to flexbox. They work wonderfully together. Where flexbox is the perfect solution when one is laying out items in a linear manner, CSS Grid is designed for layouts in 2D. I agree that in Vuetify layout is defined by the classes. While Flexbox was the only choice when Vuetify was initially designed, what CSS Grid offers should be considered.

I agree that this would be a significant, breaking change, however, CSS Grid offers features, functionality, and easy of use for layout that cannot be matched by flexbox. The advantages are significant and compelling.

I hope this idea will not be forgotten and can be given more consideration as Vuetify moves forward.

**Comment by KaelWD** [comment]
Do you have an example of how grid would be used in vuetify? All I've seen is people trying to recreate the classic bootstrap-style grid system but with many more limitations.

**Comment by James-Hudson3010** [comment]
At the moment, no. As best I can determine, Vuetify and CSS Grid do not play well together. I had trouble getting things like Navigation Drawers to work correctly. I am sure it would be possible with enough effort. I believe Vuetify would need to built up again from the ground up taking CSS Grid into account for layout instead of Flexbox. I think that CSS Grid is now a more natural choice as this is the use-case CSS Grid was designed for and Flexbox was not. Had CSS Grid been available and in a solid state when Vuetify was initially developed, I am certain it would have been selected over Flexbox.

A couple of other resources to check out with respect to CSS Grid are https://abookapart.com/products/get-ready-for-css-grid-layout and https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by MatthewAry** [comment]
Leaving this here for posterity. This was is in regards to adding the feature to Version 3.
![image](https://user-images.githubusercontent.com/157217/94852292-855cb300-03de-11eb-99b5-435ed4fcf3f1.png)

**Comment by lazaroofarrill** [comment]
well I mixed my css-grid-helper classes with vuetify breakpoints in the project I'm working right now. Of course it would be impossible to reflect in utility classes all possible layouts achievable  with css but I find it to work pretty well in my current project and it does solves quite a few flexbox limitations. I don't think this framework should be grid based at all, but supporting it ain't that hard.

```
@each $name, $value in $grid-breakpoints {
    .text-#{$name} {
      @media screen and (min-width: $value) {
        &-h1 {
          font-size: 5rem !important;
        }

        &-h2 {
          font-size: 3.5rem !important;
        }
      }
    }


    @media (min-width: $value) {
      .grid-cols-#{$value}-auto {
        grid-column: auto;
      }

      .grid-rows-#{$value}-auto {
        grid-row: auto;
      }

      .grid-row-start-#{$value}-auto {
        grid-row-start: auto;
      }

      .grid-col-start-#{$value}-auto {
        grid-column-start: auto;
      }


      @for $i from 1 through 12 {
        .line-clamp-#{$name}-#{$i} {
          display: -webkit-box;
          -webkit-box-orient: vertical;
          overflow: hidden;
          -webkit-line-clamp: #{$i};
        }

        .grid-cols-#{$name}-#{$i} {
          grid-template-columns: repeat($i, minmax(0, 1fr))
        }

        .grid-row-start-#{$name}-#{$i} {
          grid-row-start: $i;
        }

        .grid-col-start-#{$name}-#{$i} {
          grid-column-start: $i
        }

        .grid-col-span-#{$name}-#{$i} {
          grid-column: span ($i / span) $i
        }

        .grid-row-span-#{$name}-#{$i} {
          grid-row: span ($i / span) $i
        }
      }
    }
  }
```
