### ISSUE TITLE
[Feature Request] proper tooltip positioning for input elements

### ISSUE THREAD

**Issue by aleksey-hoffman** [vuetifyjs/vuetify#11947]
### Problem to solve
By default, tooltips should be positioned relatively to the center of the input element no matter what component it's in:

![image](https://user-images.githubusercontent.com/61761672/88596287-728bd200-d06d-11ea-8901-8c6e6483d39c.png)

https://codepen.io/aQW5z9fe/pen/MWKdaVj?editors=1010

```html
 <v-tooltip bottom>
  <template v-slot:activator="{ on }">
    <div v-on="on">
      <v-switch 
        v-model="switch1" 
        label="Switch 1"
      ></v-switch>
    </div>
  </template>
  <span>tooltip</span>
</v-tooltip>
```
Currently it's displayed like this:

![image](https://user-images.githubusercontent.com/61761672/88596335-8cc5b000-d06d-11ea-8922-97939019772c.png)

I managed to fix this behaviour for elements in a radio group by adding `align-self: flex-start;` but it doesn't work for switches for some reason.

### Proposed solution
Add a prop that would disable flex stretching so tooltips can be displayed properly.

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow

The div you've assigned the listeners to is a block element, so it fills the parent width. You can fit it to its content with `class="d-inline-block"`. You can do the same without the wrapping div with `<v-switch class="d-inline-flex" v-on="on">`

**Comment by aleksey-hoffman** [comment]
@KaelWD well, it's not a proper solution, it's just a dirty annoying workaround, that's why I opened the issue:

- You have to add a div around the switch because otherwise the tooltip doesn't show up when you hover over the label.

- You have to add a div around the elements following the div with that `d-inline-flex` workaround, otherwise the elements like `v-btn` will get moved up to the same line

**Comment by aleksey-hoffman** [comment]
@KaelWD well, it's not a proper solution, that's why I opened the issue:

- You have to add a div around the switch because otherwise the tooltip doesn't show up when you hover over the label.
- Then you have to add  `d-inline-flex` to that div
- Then you have to add a div around the elements following the div with that `d-inline-flex` workaround, otherwise the elements like `v-btn` will get moved up to the same line
