### ISSUE TITLE
[Bug Report] yarn test fail because of formatTime

### ISSUE THREAD

**Issue by blackpost38** [vuetifyjs/vuetify#11940]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Mac OS 10.14.6

### Steps to reproduce
just run `yarn test` in packages/vuetify path

### Expected Behavior
all test cases is passed

### Actual Behavior
specific test case is failed: calendar-with-events.ts › should format time

### Reproduction Link
<a href="https://github.com/blackpost38/vuetify" target="_blank">https://github.com/blackpost38/vuetify</a>

### Other comments
Log is below
Summary of all failing tests
 FAIL  src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts
  ● calendar-with-events.ts › should format time

    expect(received).toMatch(expected)

    Expected pattern: /^0?8:30( AM)?$/
    Received string:  "8:30 ├F10: AM┤"

      126 |     // (12-hour with `h` || 12-hour with `hh` || 24-hour with `h` || 24-hour with `hh`),
      127 |     // we expect the value passed to be-
    > 128 |     expect(wrapper.vm.formatTime(testData1, true)).toMatch(/^0?8:30( AM)?$/) // 8:30 AM || 08:30 AM || 8:30 || 08:30
          |                                                    ^
      129 |     expect(wrapper.vm.formatTime(testData2, true)).toMatch(/^(0?5:45 PM|17:45)$/) // 5:45 PM || 05:45 PM || 17:45
      130 |     expect(wrapper.vm.formatTime(testData3, true)).toMatch(/^0?9:05( AM)?$/) // 9:05 AM || 09:05 AM || 9:05 || 09:45
      131 |     expect(wrapper.vm.formatTime(testData4, true)).toMatch(/^(0?3 PM|15)$/) // 3 AM || 03 AM || 15

      at src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:128:52
      at step (src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:124:17)
      at Object.next (src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:55:14)
      at src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:27:67
      at Object.<anonymous>.__awaiter (src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:4:10)
      at Object.<anonymous> (src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts:117:28)

**Comment by MajesticPotatoe** [comment]
Related to #10941
Same solution can likely be applied.

**Comment by jacekkarczmarczyk** [comment]
Probably, but what the heck is this format `├F10: AM┤`??

**Comment by blackpost38** [comment]
Ah, right, I've thought related to #10941
But i don't know what format is `├F10: AM┤`
So I have a stuck how to modify regex

**Comment by KaelWD** [comment]
This looks like a bug in node 12 on macOS with zh_CN system locale: https://github.com/microsoft/vscode/issues/104157
