### ISSUE TITLE
[Bug Report] v-slide-group does not hide or disable arrows when using with v-slot

### ISSUE THREAD

**Issue by hoangtuan151** [vuetifyjs/vuetify#11941]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 79.0
**OS:** Linux x86_64

### Steps to reproduce
Normally, when displaying the slide group at first, the prev arrow will be disabled/hided. Then, when scroll to the last item of the slide, the next arrow in turn will be disabled/hided. But when using with v-slot:next or v-slot:prev, the next/prev icons are always displayed/enabled.

### Expected Behavior
When using next/prev v-slot for icons customizing, the two icons should be hided/disabled properly.

### Actual Behavior
The two icons are always displayed/enabled.

### Reproduction Link
<a href="https://codepen.io/hoangtuan/pen/ZEQZMbv" target="_blank">https://codepen.io/hoangtuan/pen/ZEQZMbv</a>

**Comment by njbarrett** [comment]
Confirming this is still an issue

**Comment by KaelWD** [comment]
Better repro: https://codepen.io/kaelwd/pen/abJeNwz?editors=1000

**Comment by hondnl** [comment]
Would love if this could be fixed.    Why not just passing down the hasPrev/hasNext into the slot as a prop?
Used a css workaround for now...

`.v-slide-group__next--disabled .disable-arrows, .v-slide-group__prev--disabled .disable-arrows {
  pointer-events: none;
  color: rgba(0, 0, 0, 0.38) !important;
}`

Then just give the icon the class disable-arrows.
