### ISSUE TITLE
[Feature Request] a linear loading in bottom of snackbar 

### ISSUE THREAD

**Issue by alamamir** [vuetifyjs/vuetify#11943]
### Problem to solve
hi !
vutify is greate but i think snackbar can improve more!
by a linear loading in bottom of snackbar !such as gmail app snackbar
thanks a lot :)

### Proposed solution
update

**Comment by Parakoos** [comment]
Would love this. I was about to implement this myself (I've already implemented the queue) but might just wait for this to be done if it is in the queue.

**Comment by KaelWD** [comment]
Duplicate of #8451
