### ISSUE TITLE
[Feature Request] Please stop using v-model for non-input components

### ISSUE THREAD

**Issue by rmirabelle** [vuetifyjs/vuetify#11952]
### Problem to solve
`v-model` is intended to provide 2-way data binding for input components.  Yet in Vuetify, it's consistently used for components that are clearly NOT inputs. This leads to constant confusion over the API for these components, as devs are forced to magically intuit how `value` and `input` are being thwarted to fit the expected API surface.  Instead of improving comprehensibility, `v-model` all but ruins it when used in any non-input component.

Examples of confusing usage of `v-model` include but are not limited to `v-dialog` and  `v-bottom-sheet`.  First and foremost, these components are clearly NOT inputs.  Nor should they be treated as inputs.  No one will check out the API for these components expecting `input` or `value` as both are clearly utterly meaningless in the context of either of these components.  Conversely, when a new dev checks out the source code for an existing project using either of these components and sees an `input` or `value` binding, what could possibly ensue other than confusion? 

Another example: it appears that the `input` event for a `v-bottom-sheet` is fired when a user clicks OUTSIDE a non-persistent sheet.  This is documented nowhere, is completely illogical and is utterly impossible to intuit.

I understand that Vuetify uses `v-model` in an attempt to simplify the API for its components, but when applied to clearly NON-input components, `v-model` has completely the opposite effect - it kills readability and comprehension.

### Proposed solution
`v-model` should ONLY be supported by components that either ARE inputs or whose PRIMARY purpose is to collect input.  Dialogs and bottom sheets clearly don't match this criteria.  For components like `v-dialog` and `v-bottom-sheet`, events should be assigned custom names that match the expected, logical, intuitive API surface for these components.  Event names like `visible` or `shown` or `clickedOutside` would make reasoning about what's going on with these components worlds easier, even if we're forced to type a few more characters.

**Comment by jacekkarczmarczyk** [comment]
We could use `.sync` props instead of v-model, however since that it would be a breaking change it should wait for Vuetify 3.0 - and since Vuetify 3.0 will be working only with Vue 3 where `.sync` is deprecated we will have to stick to v-model anyway (although with new Vue 3 syntax).
Still changing the prop name from `value` to `visible` or similar is IMHO a good idea

**Comment by KaelWD** [comment]
Earlier versions of vue 2 didn't have .sync and custom model props, it was either v-model with value/input or having to bind the prop and event separately. 

> sees an input or value binding, what could possibly ensue other than confusion?

These names have been the vue defaults for a long time, it's something any dev should know already. 

Vue 3 changes it to modelValue which is likely to be what we'll use.

**Comment by rmirabelle** [comment]
> These names have been the vue defaults for a long time, it's something any dev should know already.

To clarify, seeing `input` and `value` bindings _isn't_ the problem.  Seeing them thwarted for use on a component that has nothing to do with user input - _that's_ the problem.  It's a conceptual parity mismatch.  After all, a dialog doesn't have a `value`! Neither does a bottom sheet.  And neither of them should be firing `input` events, because neither accepts input! To hell with saved keystrokes :-)  Clarity of API surface FTW.

I maintain that at least _providing_ a custom attribute/event pair (again, only for components that are obviously NOT inputs)  would make learning and reasoning about them much easier.
