### ISSUE TITLE
[Bug Report] Autocomplete and Combobox input only works when Developer Tools are open (F12) in IE11

### ISSUE THREAD

**Issue by rcheung9** [vuetifyjs/vuetify#11955]
### Environment
**Vuetify Version:** 2.3.2
**Last working version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Default

### Expected Behavior
Able to type in

### Actual Behavior
Does not allow you to type

### Reproduction Link
<a href="https://codepen.io/rcheung9/pen/JjGqZgb" target="_blank">https://codepen.io/rcheung9/pen/JjGqZgb</a>

**Comment by KaelWD** [comment]
Unable to reproduce in browserstack with v2.3.2 or v2.3.6. Do you have any add-ons installed?

**Comment by jacekkarczmarczyk** [comment]
Not sure if this is the same issue but autocomplete and combobox pages don't work in docs in IE11. To reproduce it you need to open the page directly, otherwise (when you navigate from other page that works to autocomplete/combobox) it works fine.
That happens regardless dev tools are open or not

**Comment by KaelWD** [comment]
The combobox examples straight-up just don't render if I visit the page directly in IE.

**Comment by rcheung9** [comment]
No add-ons, it's version 11.55.17763.0C0

Same behavior, if you go to the https://vuetifyjs.com/en/components/autocompletes/ autocomplete/combobox page directly, it only partially renders.  But not only that, you can't even navigate to another page or link.  None of the links or dropdowns work either.

Loading from another page and navigating to autocomplete page works.  But it still won't type, I have to press F12 once and after that I can close it and all javascript works normally, can type in the field.

I've been trying to research the issue with javascript functionality working partially only with DevTools (F12) open at least once on a page load.  Most of them says something about IE11 not supporting `console.log` but I've used `console.log` before in IE11 with no issue so that is odd.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
