### ISSUE TITLE
[Bug Report] v-virtual-scroll re-renders all items when scrolling down

### ISSUE THREAD

**Issue by aleksey-hoffman** [vuetifyjs/vuetify#11951]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
- Open console
- **Scroll down** slowly and look at the virtual scroller items: all items will flush
- **Scroll up** slowly and look at the virtual scroller items: works as expected

### Expected Behavior
To render only 1 item on scroll down

### Actual Behavior
Re-renders all items on scroll down, but not on scroll up

I'm adding an image with a fade-in animation on item's mounted hook and since it re-renders everything, all images are flushing when you're scrolling down

![01](https://user-images.githubusercontent.com/61761672/88669166-39467700-d0ec-11ea-8835-e3ec215cf410.gif)

### Reproduction Link
<a href="https://codepen.io/aQW5z9fe/pen/QWyROwR" target="_blank">https://codepen.io/aQW5z9fe/pen/QWyROwR</a>

**Comment by iassia** [comment]
Roughly solved this issue by inverting the list based on scrolling direction to prevent item index changes not cascading causing re-rendering:

```js
      const items = this.items.slice(
        this.firstToRender,
        this.lastToRender,
      )
      return [...(this.scrollDirection === 'down' ? items.reverse() : items)].map(this.genChild)
```

This will solve another issue related to the keyboard navigation if you try to use the keyboard arrow keys to navigate inside the VirtualScroller the focus will be lost.
