### ISSUE TITLE
[Feature Request] the version 2.3.6 does support the calendar type for category?

### ISSUE THREAD

**Issue by iamohero** [vuetifyjs/vuetify#11957]
### Problem to solve
question for the version 2.3.6 does support the calendar type for category?

### Proposed solution
the study

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
