### ISSUE TITLE
v-tabs: cannot read clientWidth of undefined

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1195]
### Steps to reproduce
In the codepen, type something in the search field that will give no or less results, such as `q` , then backspace that and repeat quickly. It should show errors in your console.
Perhaps this is dependent on CPU speed so results may vary..

### Versions
vuetify 0.14.7

### What is expected ?
no errors

### What is actually happening ?
Console shows the following errors:
```
vuetify.min.js:6 Uncaught TypeError: Cannot read property 'clientWidth' of undefined
    at VueComponent.onResize (vuetify.min.js:6)
    at boundFn (vue.js:189)
```

### Reproduction Link
https://codepen.io/anon/pen/brpqPe?editors=1010

**Comment by ChavaSobreyra** [comment]
This is a race conditions problem where Vuetify is trying to access .clientWidth of the v-tabs-bar elements after they disappeared due to quickly showing/hiding elements in the v-for loop by spamming `q` and `backspace`.

A similar problem occurs on the docs data table search example. 
 
`detachable.js?b375:16 Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at eval (detachable.js?b375:16)`

**Comment by johnleider** [comment]
I cannot reproduce this across 4 different browsers. Can you provide a reproduction step that will always work?

**Comment by ChavaSobreyra** [comment]
Using Chrome on macOS, I am able to reproduce using the codepen @Christilut provideded. Same with the data table in the docs example. 

On my windows machine I'm unable to reproduce.

**Comment by Christilut** [comment]
I had this problem on my XPS13 running Ubuntu with Chrome

I tried it on my work laptop XPS15 (significantly faster CPU than the XPS13) running Windows 10 (Chrome) and I can't reproduce it here

**Comment by ram-you** [comment]
Still have the same issue (sometimes, not always) with the 1.0.2 version.

**Error** `Uncaught TypeError: Cannot read property 'clientWidth' of undefined`
**Fired by**  `VTabs.js`
**At**
`   setOverflow: function setOverflow() {
      this.isOverflowing = this.$refs.bar.clientWidth < this.$refs.container.clientWidth;
    },`

**Comment by KaelWD** [comment]
This issue is:
- Extremely old
- Extremely closed

Make a new one with an up-to-date reproduction if you are still seeing this.
