### ISSUE TITLE
[Bug Report] VSlideGroup - First group item position changes after changing bound data.

### ISSUE THREAD

**Issue by pasteusernamehere** [vuetifyjs/vuetify#11965]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.6

### Steps to reproduce
Using the codepen link:
1. Toggle the data binding back and forth.

See how the first group option jumps positions

### Expected Behavior
I would expect that the first option stays in the same position when toggling data bindings.

### Actual Behavior
Option[0] jumps back and forth on the screen.

### Reproduction Link
<a href="https://codepen.io/pasteusernamehere/pen/bGEPOYV" target="_blank">https://codepen.io/pasteusernamehere/pen/bGEPOYV</a>

### Other comments
I assume this is a defect. If not can you please provide a potential workaround?

**Comment by pasteusernamehere** [comment]
It appears that the option position is shifting because of the hidden previous link.

**Comment by pasteusernamehere** [comment]
Adding class="v-slide-group--has-affixes" to the v-slide-group appears to mitigate the issue.

**Comment by KaelWD** [comment]
You can use `show-arrows="always"` to keep the arrows visible even if there is no overflow.

**Comment by pasteusernamehere** [comment]
This really doesn't solve the problem. I know I can always show the arrows but I do not want to show the arrows when it is not overflowing. I guess I could potentially hide the arrows when the control is not overflowing.
