### ISSUE TITLE
[Feature Request] Add combobox menu item clicked event

### ISSUE THREAD

**Issue by hareku** [vuetifyjs/vuetify#11960]
### Problem to solve
I want to fire an event only when an item in the menu of combobox is clicked or when the enter key is pressed in input.
combobox has a keydown event, but no event when a combobox menu item is clicked.

### Proposed solution
Create a custom event like `click:item`.

**Comment by KaelWD** [comment]
Does the `change` event not suit your needs?

**Comment by hareku** [comment]
The `change` event is fired even when v-combobox is unfocused.
I can't distinguish whether the cause of the `change` event is selected or unfocused.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by rootgrandfather** [comment]
@change event trigger even when the combobox is blur, that is not a good design.

**Comment by lacoste-sochi** [comment]
Of course , you can do it through the slot ...

But how many times have I already been convinced by such unsubscriptions that it is necessary to get off the framework of this.

**Comment by wcheek** [comment]
This would have been useful, but you can do it with the slot as mentioned above:

```vue
  <v-combobox
    v-model="query"
    :items="items"
  >
    <template v-slot:item="{ item, props }">
      <v-list-item v-bind="props" @click="clickItem(item)"></v-list-item>
    </template>
  </v-combobox>
```

**Comment by Erutan409** [comment]
> This would have been useful, but you can do it with the slot as mentioned above and documented [here](https://vuetifyjs.com/en/api/v-combobox/#slots-item).
> 
>   <v-combobox
>     v-model="query"
>     :items="items"
>   >
>     <template v-slot:item="{ item, props }">
>       <v-list-item v-bind="props" @click="clickItem(item)"></v-list-item>
>     </template>
>   </v-combobox>

I think should be in the official documentation examples. This is exactly what I was looking for/need for intercepting this action for address searching purposes.
