### ISSUE TITLE
[Bug Report] v-checkbox is not rendered properly when wrapped in v-tooltip

### ISSUE THREAD

**Issue by nclemeur** [vuetifyjs/vuetify#11967]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
Nothing todo

### Expected Behavior
Correct visual & bevhaviour

### Actual Behavior
 it seems that the 'native' checkbox' is displayed when it should not. Moreover the tooltip is not working as expected

### Reproduction Link
<a href="https://codepen.io/nclemeur/pen/vYLqwwx" target="_blank">https://codepen.io/nclemeur/pen/vYLqwwx</a>

### Other comments
v-tooltip really needs to be improved as it is a really painfull point in vuetify

**Comment by MajesticPotatoe** [comment]
seems that `attrs` is passing `role: button` to the checkbox causing the native checkbox to appear. 
The tooltip positioning is likely due to the input taking up the full width of the screen
`v-tooltip` will likely be reworked in v3 as yeah, it needs to be improved.

**Comment by nclemeur** [comment]
I think it would be good to show a bit of love toward v-tooltip before v3. As a minimum. documenting recommended work around in the official documentation would be a good start.
For example it seems that attrs are passed in v-bind="attrs" in all example. Is that required? Seems to at least be the source of an issue here... If not required, when is it necessary to add them and for what purpose...

**Comment by MajesticPotatoe** [comment]
The passing of `v-bind="attrs"` is for a11y purposes. it was added in #11394. It is by no means a requirement technically, but is recommended for a11y compliance, and this just seems to be an overlooked side effect of such. 

v2 is feature locked as after new docs are released we are pretty much head in sand working on v3 as its a tremendous undertaking as the whole framework needs to be rewritten to support it. v2 tooltip's will still receive major bug fixes and we always welcome and encourage PR's for existing bugs. Feedback/PR's are for documentation updates is also always welcome, however likely better suited in a different issue (if it doesn't already exist).

I believe any real major improvements would though require breaking changes (I believe its been discussed at one point converting to a directive to cut down on activator slot ugliness which honestly is probably one of the more painful points imo)
That being said, this is still seems a valid bug, and has been marked as such.
