### ISSUE TITLE
[Feature Request] v-combobox menu should disappear when pressed Enter key

### ISSUE THREAD

**Issue by hareku** [vuetifyjs/vuetify#11962]
### Problem to solve
The current behavior is that the v-combobox menu disappears when pressed the Enter key with any option.
In case of multiple combo boxes, that's the expected behavior, but it's a weird in case of not multiple. Users typically want to close the menu when they press the Enter key.

### Proposed solution
Close the menu when pressed the Enter key when v-combobox is not multiple.

**Comment by johnleider** [comment]
This works exactly as you describe. Maybe it was a bug from a previous version since this issue is quite old. Closing as resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
