### ISSUE TITLE
[Bug Report] Require image asset works 50% of the time

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#11974]
### Environment
**Vuetify Version:** 2.3.7
**Last working version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Linux

### Steps to reproduce
Unable to provide codepen example because it requires image assets locally.

Installed Vuetify using Vue CLI with "vue add vuetify".

Gist of the project:
1. 10 images inside /assets/
2. A loop that includes a vue template that has the following template:

`<img :src="getLogo()" />`

With the method:

```
getLogo ()
{
return require('@/assets/' + this.logo_filename)
}
```

When the loop runs, about 50% of the images are included in the list with a data:image/png:base64 encoding. The other half are pointing to "/img/logofilename.png" when running "npm run serve"

This problem persists on "npm run build" where only half the images are required and built into the project.

What is going on?

Why is it pointing to a "/img/" directory that does not exist?

Using v-img instead of img, 50% of the images point to `http://localhost:8080/img/myimage.png`

**I am thinking this is a problem with tree shaking, as I recently moved the project from a non-tree shaking setup where it worked fine where I used vue-loader.**

### Expected Behavior
All required images should be base64 encoded and included in the build.

### Actual Behavior
The require() points and adds a prefix of "/img/" to the img src="" for some reason about 50% of the time.

### Reproduction Link
<a href="https://codepen.io/zyle/pen/pogMZwY" target="_blank">https://codepen.io/zyle/pen/pogMZwY</a>

**Comment by KaelWD** [comment]
That is done by [`url-loader`](https://webpack.js.org/loaders/url-loader/), not vuetify.
