### ISSUE TITLE
[Feature Request] Contrast colors to the current theme

### ISSUE THREAD

**Issue by PedroCuadra** [vuetifyjs/vuetify#11978]
### Problem to solve
Many times I use the following to color depending on dark or light theme:

```html
<span :class="`blue--text ` + ($vuetify.theme.dark ? `text-lighten-1` : `text-darken-1`) ">
  some text here.
</span>
```
The same thing for background colors:
```html
<div :class="`green ` + ($vuetify.theme.dark ? `lighten-3` : `darken-3`) ">
  some text here.
</div>
```

### Proposed solution
To implement `text-contrast-{n}` to lighten by `n` a color in dark-mode and darken in light-mode:

```html
<span class="blue--text text-contrast-2">
   Some text here
</span>
```
And `contrast-{n}` for backgrounds.

```html
<div class="green contrast-3">
   Some text here
</div>
```
PS: I'm not sure if `contrast` is the best word to match the issue since i'm not a native speaker.

**Comment by jaxn** [comment]
For text, you may be looking for the opacity classes.

The material spec uses opacity to communicate the [emphasis level of text](https://material.io/design/color/text-legibility.html#text-backgrounds).  In Vuetify those are the `text--primary`, `text--secondary`, and `text-disabled` classes.

I am not aware of similar classes for backgrounds, and end up creating my own sass variables for those and would love to see something like that added to Vuetify.  (I use `ui-1`, `ui-2`, etc)

**Comment by PedroCuadra** [comment]
No, i'm not looking for opacity classes because I don't want something being disabled.

Here, the text color is `green--text text-darken-2`
![image](https://user-images.githubusercontent.com/14881608/89460448-4ab90000-d738-11ea-92ef-2f243deb9eff.png)

And here it is `green--text text-lighten-2`
![image](https://user-images.githubusercontent.com/14881608/89460662-a3889880-d738-11ea-9668-110adbb254f0.png)


Another aproach that I suggest is to have the following classes:

`<lighting>-tlight` and `<lighting>-tdark` that applies color only applied in light or dark theme.

Example:
```html
<span class="green-text text-lighten-2-tdark text-darken-2-tlight">
  some text
</span>
```

**Comment by johnleider** [comment]
This is happening in version 3 with the updated theme system and automatic contrast detection. Follow for future updates https://github.com/vuetifyjs/vuetify/issues/12688.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
