### ISSUE TITLE
[Bug Report] Using vertical divider in a grid results in wrapping

### ISSUE THREAD

**Issue by Velikolay** [vuetifyjs/vuetify#11973]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.14.6

### Steps to reproduce
Having a grid equivalent to the one below results in column wrapping
```html
    <v-row>
      <v-col cols="6">Left side text</v-col>
      <v-divider vertical></v-divider>
      <v-col cols="6">Right side text</v-col>
    </v-row>
```
I tried few alternative but both have their own issues:
1. If the second column doesn't specify strict number of cols (or cols="auto") this creates responsiveness issues with the content inside when resizing the screen.
2. If the row specifies class="flex-nowrap" the horizontal scroll shows up

I hope i'm missing something obvious and there's better way to divide columns.
Thanks for looking into it.

### Expected Behavior
Dividing a full 12 col grid keeps columns in the same row

### Actual Behavior
The last column wraps

### Reproduction Link
<a href="https://codepen.io/velikolay/pen/qBbeKxz" target="_blank">https://codepen.io/velikolay/pen/qBbeKxz</a>

**Comment by KaelWD** [comment]
We could add `margin: 0 -0.5px` to vertical dividers, not sure if that causes other problems though.

**Comment by narkissbv** [comment]
> We could add `margin: 0 -0.5px` to vertical dividers, not sure if that causes other problems though.

How about adding that negative margin only to vertical dividers that are children component of `v-col`? When they are outside the scope of `v-col` they won't cause that bug...

**Comment by KaelWD** [comment]
> -0.5px will cause issues when using less than 100% zoom in browser. Value of -1px will work also for "zoomed out" perspectives

-1px breaks when zoomed out too, it just works up to 33% instead of 90%
