### ISSUE TITLE
[Bug Report] V-Tab-Arrow doesn't work inside short container when tabs items are too long or when here are a lot of short items

### ISSUE THREAD

**Issue by Termonna** [vuetifyjs/vuetify#11988]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
Click pagination arrow

### Expected Behavior
Should slide tabs

### Actual Behavior
Do nothing

### Reproduction Link
<a href="https://codepen.io/Termonna/pen/YzqKpyM" target="_blank">https://codepen.io/Termonna/pen/YzqKpyM</a>

### Other comments
This bug appears only with long-titled tabs in short container or when here are a lot of short items. Here is an example in Vuetify doc with this bug (case with long-titled tabs): https://vuetifyjs.com/ru/components/tabs/#centered-active-tab (here are tabs with titles 'seventeen', 'eighteen' and etc)

Arrows in short-titled tabs works correctly: https://vuetifyjs.com/ru/components/tabs/#pagination

Maybe it depends on screen resolution. My resolution is 1920x1280.

NB: If you select any tab in broken cases, pagination should start to work correctly.

Upd: Checked it on resolutions 1536x864 and 2560x1600(Retina). Result: in both cases arrows don't work for all examples from reproduction link

**Comment by geeee** [comment]
Use `show-arrows` on `<v-tabs>` for a quick workaround

**Comment by Termonna** [comment]
> Use `show-arrows` on `<v-tabs>` for a quick workaround

Still doesn't work: https://codepen.io/Termonna/pen/YzqKpyM (string 8)

**Comment by geeee** [comment]
Does it work for you here: https://codepen.io/aaaa1112s/pen/xxOgEyM ?

**Comment by Termonna** [comment]
Ah, I'm too late, Sorry.

Yes, it works. I dunno why I said 'still doesn't work' cos it worked and why added this attribute for only one tabs

Unfortunately, it is also not entirely correct since arrows should not be on mobile devices (but this can at least be bypassed with css)

Thanks!

**Comment by laventnc** [comment]
Any update on this? I have a page with a dynamic number of tabs depending on the user's permission. Also, same mobile issue as OP.

Source of the issue is whenever a tab-item is cut-off by the next/previous icon, the arrows become unclickable.
