### ISSUE TITLE
[Feature Request] Add background-size props to v-img

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/vuetify#11984]
### Problem to solve
When you use a v-img to supply a background image in components, the size properties apply to the entire v-img responsive component. This means that you cannot independently restrict the size of the background image without the responsive content also being restricted.

This can cause a problem when you need to make the background image smaller than the content viewport, or position it within the view.

### Proposed solution
I am currently using a work around for this using styles within the component as so:
```
<template>
  <v-row
  >
    <v-img
      :src="require('@/assets/SVG/Shape 2.svg')"
      height="1188"
      position="-15% 100%"
      class="bg-shape"
    >
      <v-container>
        <v-row
          no-gutters
          style="height: 992px;"
        >
        </v-row>
      </v-container>
    </v-img>
 </v-row>
</template>
<style>
.bg-shape>.v-image__image {
  background-size: 526px 804px;
}
</style>
```

Instead of this, I propose adding one or two props directly to the component to set the background height and width. This would make handling of background images more consistent

**Comment by yurriiy** [comment]
same problem

**Comment by KaelWD** [comment]
I suggest using CSS for this.

**Comment by davydnorris** [comment]
@KaelWD did you actually look at the issue? This is exactly what I am doing as a workaround. I even posted the code.

I am proposing adding props because it would immensely simplify the job. Currently you have to jump through css hoops to apply the style to the inaccessible internal element

**Comment by KaelWD** [comment]
Yeah I understand the problem, it just doesn't really fit with my goals for the component. For v3 I'm experimenting with using `<picture>` instead of `background-image`.
