### ISSUE TITLE
[Feature Request] Toggle open/close all sibling expansion panels (SHIFT + toggle)

### ISSUE THREAD

**Issue by emveeoh** [vuetifyjs/vuetify#11980]
### Problem to solve
Add ability to toggle open/close all sibling expansion panels with one click, Reduces the need to click each expansion panel individually.

### Proposed solution
SHIFT key + clicking on the toggle will open/close all sibling expansion panels.

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
