### ISSUE TITLE
[Documentation] v-list-item-action not being toggled by clicking on checkbox

### ISSUE THREAD

**Issue by escapedcat** [vuetifyjs/vuetify#11986]
### Environment
**Vuetify Version:** 2.3.7
**Last working version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. https://vuetifyjs.com/en/components/lists/#subheadings-and-dividers
1. click item "notfications" on text - list item is selected
1. click item "notfications" on checkbox - list item is not selected

### Expected Behavior
list item is selected by clicking item/text or checkbox

### Actual Behavior
list item is selected only by clicking item/text

### Reproduction Link
<a href="https://codepen.io/escapedcat/pen/KKzPVez" target="_blank">https://codepen.io/escapedcat/pen/KKzPVez</a>

**Comment by KaelWD** [comment]
That example is wrong, you shouldn't be using `@click` there (#10373). It should probably be removed anyway, it's almost identical to this correct one: https://vuetifyjs.com/en/components/lists/#action-with-title-and-sub-title

**Comment by KaelWD** [comment]
This one has the same problem: https://vuetifyjs.com/en/components/list-item-groups/#selection-controls

**Comment by escapedcat** [comment]
Alright, nice, thanks! I will create a PR to correct the docs then.
