### ISSUE TITLE
[Feature Request] Ability to center v-rating

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#11981]
### Problem to solve
I want to center the v-rating stars at all times even when they are below 5 stars.

If there is 1 star rating, I want it centered.

This is not possible right now it seems, because the invisible stars are still rendered.

Example image illustrates the problem. The stars are always left aligned:
![Screenshot from 2020-08-02 20-19-07](https://user-images.githubusercontent.com/1741593/89129451-c0855780-d4fd-11ea-8a0b-b58e7eebe71b.png)

Desired outcome:
![stars2](https://user-images.githubusercontent.com/1741593/89129517-40132680-d4fe-11ea-9320-437e9bc30242.png)

Using the code:
```
<template>
<v-rating v-model="rating.value" :length="rating.length" :empty-icon="rating.empty_icon" :half-icon="rating.half_icon" :full-icon="rating.full_icon" color="yellow darken-4" background-color="white" size="20" dense readonly half-increments></v-rating>
</template>

<script>
export default {
  data: () => ({
    rating: {
      value: 3.1,
      empty_icon: "$ratingEmpty",
      half_icon: "fas fa-star-half",
      full_icon: "fas fa-star"
    }
  })
}
</script>
```

### Proposed solution
Add an option to not render the invisible stars based on "length" and the v-model value.

Example: If the length is 5, but the value is 3.5 and you use half-increments you only render 3 and a half star, not the the last star and the div should align to center.

**Comment by johnleider** [comment]
I like the idea but I'm not sure how it would work with the **hover** property.

**Comment by nekosaur** [comment]
Can you not do this by simply setting the length? https://codepen.io/nekosaur/pen/NWdNaoR?editors=1010

Or am I missing something?

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
