### ISSUE TITLE
[Bug Report] v-textarea line-height does not work

### ISSUE THREAD

**Issue by apavel3458** [vuetifyjs/vuetify#11990]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.5

### Steps to reproduce
add line-height and text-autogrow to textarea and the <textarea element still grows by 16px with each line

### Expected Behavior
textarea starts with "line-height" height, and grows by that multiple.

### Actual Behavior
textarea starts at 32px and grows by 16px 

### Reproduction Link
<a href="https://codepen.io/apavel3458/pen/ExKYwLO" target="_blank">https://codepen.io/apavel3458/pen/ExKYwLO</a>

### Other comments
I have a textarea, and I want font-size to be small, so I changed the font-size and line-height, but it starts off with extra spacing (32px). I set line-height to 10px to have it start smaller and grow smaller, but textarea element still starts with 32px, the on the second line it grows by 16px regardless of what I set line height to.

**Comment by daikiojm** [comment]
@apavel3458 You can probably use `row-height` instead of `line-height`.
see this document: https://vuetifyjs.com/en/api/v-textarea/#props
