### ISSUE TITLE
[Bug Report] Delete font size: 14px from html

### ISSUE THREAD

**Issue by 1SolPi1** [vuetifyjs/vuetify#11997]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Firefox 79.0
**OS:** Mac OS 10.15

### Steps to reproduce
https://jsfiddle.net/toqyur4c/

### Expected Behavior
https://jsfiddle.net/toqyur4c/

### Actual Behavior
https://jsfiddle.net/toqyur4c/

### Reproduction Link
<a href="https://jsfiddle.net/toqyur4c/" target="_blank">https://jsfiddle.net/toqyur4c/</a>

### Other comments
https://jsfiddle.net/toqyur4c/

**Comment by 1SolPi1** [comment]
Fix, then you can close this issue!

**Comment by KaelWD** [comment]
`$font-size-root` is 16px not 14, and is not a bug. If you have a **compelling** reason we should remove this then please open a feature request explaining why you think it should be changed, what it should be replaced with, and how this might affect existing users.
