### ISSUE TITLE
[Documentation] Beautiful Forms example throws error on true rule

### ISSUE THREAD

**Issue by modys** [vuetifyjs/vuetify#11993]
### Problem to solve
https://vuetifyjs.com/en/components/textarea/
By using the email sample code of the form that is at the bottom of page,  "called Beautiful Forms" so soon as you push "@" in the email input, and see console log, you get the follow error;  Rules should return a string or boolean, received 'object' instead. I have no idea how to fix that. May it would be helpful feedback, maybe not. :) 

### Proposed solution
Here is Screenshot how you can faster find the malfunction.. 
https://imgshare.io/image/N7oG5X
Thx for the library, like it!

**Comment by MajesticPotatoe** [comment]
`Rules should return a string or boolean, received 'object' instead`

Rules should return string or boolean, in this case the .match() returns an array when true, which throws the error.
