### ISSUE TITLE
[Bug Report] Chip Group not preselecting items from the model when using object for the "Value" Prop in chip

### ISSUE THREAD

**Issue by totomaze** [vuetifyjs/vuetify#11994]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
Use an object in the prop value in v-chip. The chip group won't preselect the objects present in chip group model

### Expected Behavior
Chips should be active when their object value is present in the chip group model

### Actual Behavior
No chips has been active when using an object in the prop value (Chip)

### Reproduction Link
<a href="https://codepen.io/totomaze/pen/dyMbKry" target="_blank">https://codepen.io/totomaze/pen/dyMbKry</a>

### Other comments
Is there a workaround ?

**Comment by KaelWD** [comment]
That's how objects work in js, you either have to use the same object instance or a primitive value.
