### ISSUE TITLE
[Feature Request] v-data-table default footer is not hidden when disable-pagination set to true

### ISSUE THREAD

**Issue by all43** [vuetifyjs/vuetify#12003]
### Problem to solve
Default footer is only used for showing pagination information and controls and therefore makes no sense if pagination disabled.
Also it's not clear from the docs that pagination controls will remain.
With pagination disabled showing default footer is also misleading as it displays wrong information about current pages and still have active pagination controls which has no effect on displayed data.

### Proposed solution
Three possible options:
* Add to the docs that `hide-default-footer` prop should be also supplied when using `disable-pagination`. 
* Hide default footer if pagination is disabled and mention this in the docs. Easy and efficient.
* Change default footer to display only total information, e.g.: *Total: **78** items* and hide pagination info and controls. Requires adding information to locales.

**Comment by johnleider** [comment]
In v3 you have more control over the footer in addition to specialized tables for server, virtual, etc.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
