### ISSUE TITLE
[Feature Request] Missing justify-stretch css class

### ISSUE THREAD

**Issue by baruchiro** [vuetifyjs/vuetify#12000]
### Problem to solve
In CSS Flexbox, we can set `align-items: stretch`, and the Vuetify class for that is `align-stretch`.

We also can define `justify-content: stretch`, but we have classes for all `justify-content` values (`justify-start`, `justify-space-around`...) except `justify-stretch`

### Proposed solution
Just add a class for that.

**Comment by KaelWD** [comment]
`stretch` only applies to grid, not flexbox: https://www.w3.org/TR/css-flexbox-1/#justify-content-property

We don't provide utility classes for css grid.
