### ISSUE TITLE
[Feature Request] adding variable to generate rtl or ltr

### ISSUE THREAD

**Issue by ufhy** [vuetifyjs/vuetify#12005]
### Problem to solve
should be can reduce css bundle file.

### Proposed solution
maybe we can adding some logic to generate rtl or ltr
```
$is-rtl: false
$is-ltr: true

@mixin rtl()
  @if ($is-rtl)
    .v-application--is-rtl &
      @content

@mixin ltr()
  @if ($is-ltr)
    .v-application--is-ltr &
      @content
```

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/7586 needs to be eventually reopened for 3.0

**Comment by jd-0001** [comment]
@jacekkarczmarczyk This is not assigned to any phase of v3. So, I guess no one knows about considering this for v3 yet.

Am I Right?

**Comment by KaelWD** [comment]
We're using [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) in v3 so the impact of this will probably be pretty small.
