### ISSUE TITLE
v-dialog not centered on the screen

### ISSUE THREAD

**Issue by amizer12** [vuetifyjs/vuetify#12004]
Hi !
Is there a way to position time picker nad v-dialogs centrally on a page once they are open ?
As of now they open in the center of the page but if a user is below or above the dialog activator - he needs to scroll to the picker or dialog.
Those two should be automatically popping up centered at the place where user currently is, without cutting off or a need for any additional scrolling.

Current behaviour:
![image](https://user-images.githubusercontent.com/55321188/89465716-da7ba000-d772-11ea-9367-449cecc916d2.png)

**Comment by jlebrech** [comment]
try this

.v-dialog__content {
    height: 100vh !important;
}
