### ISSUE TITLE
[Bug Report] Carousel lazy loads by default

### ISSUE THREAD

**Issue by baaswietse** [vuetifyjs/vuetify#12007]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
Create a carousel with a v-for loop in the carousel item.
Inside of the item is the <img/>

### Expected Behavior
Load al images on page load.

### Actual Behavior
Only loads the image when it is active on the screen.
https://imgur.com/rUZu9oD

### Reproduction Link
<a href="https://jsfiddle.net/gqxfhetw/" target="_blank">https://jsfiddle.net/gqxfhetw/</a>

### Other comments
Is there any way to disable or work around this issue?

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/89515316-48c76d80-d81a-11ea-8871-e1bb48358b85.png)

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by baaswietse** [comment]
Thank you, I did ask this question multiple times on discord and didn't get any response so I assumed this was a bug...
