### ISSUE TITLE
[Bug Report] VInput in DataTable slot-item. cannot Correctly handle 'lazyValue' with value

### ISSUE THREAD

**Issue by LoveofRedMoon** [vuetifyjs/vuetify#12002]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
after load in 1000ms
see the VSwitch
the true-value is string '1', and the value to <v-switch> is string '1' as well

### Expected Behavior
v-switch shows is true-value
the 'lazyValue'  in v-switch is '1'

### Actual Behavior
v-switch shows is false-value
the 'lazyValue'  in v-switch is undefined

### Reproduction Link
<a href="https://codepen.io/loveofredmoon/pen/MWyWmxQ" target="_blank">https://codepen.io/loveofredmoon/pen/MWyWmxQ</a>

**Comment by jacekkarczmarczyk** [comment]
It's `input-value`

https://codepen.io/jkarczm/pen/KKzKqpQ
