### ISSUE TITLE
[Feature Request] Horizontally Stacked Bars

### ISSUE THREAD

**Issue by singhpushpender89** [vuetifyjs/vuetify#12013]
### Problem to solve
Looking for a linear progress bar to display a stacked progress of a timeline. Currently, the support is only for a single data and not a series. 

### Proposed solution
https://bootstrap-vue.org/docs/components/progress 
Something similar to this in Vuetify.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
