### ISSUE TITLE
[Bug Report] click.stop doesn't work on v-switch

### ISSUE THREAD

**Issue by b-maslennikov** [vuetifyjs/vuetify#12011]
### Environment
**Vuetify Version:** 2.3.8
**Last working version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
add @click.stop to v-switch

### Expected Behavior
Shouldn't change the state of model

### Actual Behavior
Changes the state of model

### Reproduction Link
<a href="https://jsfiddle.net/pkw0g2xy/" target="_blank">https://jsfiddle.net/pkw0g2xy/</a>

### Other comments
Reproduce link with 2.2.28 version: https://jsfiddle.net/pkw0g2xy/1/

**Comment by KaelWD** [comment]
> Shouldn't change the state of model

Why? That was a bug (#5968), if you want to disable the switch use `readonly` or `disabled`

**Comment by b-maslennikov** [comment]
I'll rephrase
click.stop modifier - the click event's propagation will be stopped https://vuejs.org/v2/guide/events.html
It was working in vuetify 2.2.x  and now it doesn't work and doesn't stop event propagation
https://jsfiddle.net/pkw0g2xy/1/ - vuetify 2.2.28 - event propagation stops
https://jsfiddle.net/pkw0g2xy/ - vuetify 2.3.8 - event propagation doesn't stop

**Comment by KaelWD** [comment]
That's not what stopPropagation is for: https://jsfiddle.net/jk3wsxyq/

**Comment by b-maslennikov** [comment]
Thanks anyway. readonly works fine for me

**Comment by ktiedt** [comment]
> Thanks anyway. readonly works fine for me

I realize this is a bit of an old issue, but I ran into this same problem when upgrading Vuetify, this is what eventually worked to mimic the previous behavior `@click.native.capture.stop="onClick"`

**Comment by farshidgh70** [comment]
You can just use `@click.native.stop="handler"`
