### ISSUE TITLE
[Bug Report] v-tabs "window is not defined" Error with SSR

### ISSUE THREAD

**Issue by mcdmaster** [vuetifyjs/vuetify#12016]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Edge 85.0.564.23
**OS:** Windows 10

### Steps to reproduce
Doing Static Build via "nuxt generate"

### Expected Behavior
No error is produced during build

### Actual Behavior
Encounters an error which adumbrates malfunction

### Reproduction Link
<a href="https://github.com/mcdmaster/covid19" target="_blank">https://github.com/mcdmaster/covid19</a>

### Other comments
Thank you!

![スクリーンショット 2020-08-05 234444](https://user-images.githubusercontent.com/10361533/89592304-3afc0180-d887-11ea-85d9-8b5820daa13e.png)

**Comment by deeja** [comment]
Not sure if this is relevant to this or not, but I've been having an issue with `eager=true` with SSR is causing my tabs to be rendered at the wrong index. It's fine when loaded in app, but that initial load is strange. 

I solved it by settings the tabs initial index to -1 on when using ssr.
```js 
//  <v-tabs-items v-model="tab">
//  <v-tab-item :eager="eager" >
 data(){
    return {tab: process.server ? -1 : 0, eager: process.server };
  },
```

Not really concerned about it, but just dropping a note here in case it helps anyone.
