### ISSUE TITLE
[Bug Report] transitions events do not fire on v-expand-transition

### ISSUE THREAD

**Issue by matthieusieben** [vuetifyjs/vuetify#12018]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.6

### Steps to reproduce
Just add transitions listener (`afterEnter`, ...) to a `v-expand-transition` elements

### Expected Behavior
The listener should be triggered

### Actual Behavior
The listeners is not triggered

### Reproduction Link
<a href="https://codepen.io/matthieusieben/pen/xxVbXLY" target="_blank">https://codepen.io/matthieusieben/pen/xxVbXLY</a>

**Comment by KaelWD** [comment]
Two problems here:
 1. `mergeData` is mutating the `functions` object so on each render another handler is added
 2. vue's transition component doesn't account for array event listeners: https://github.com/vuejs/vue/blob/4de4649d/src/platforms/web/runtime/modules/transition.js#L126

**Comment by matthieusieben** [comment]
Actually `mergeListeners` is the culprit. It mutates arrays instead of creating new once.

**Comment by matthieusieben** [comment]
Array listeners seem to be working just fine. They must be compiled into a function somewhere along the way.

**Comment by KaelWD** [comment]
> Array listeners seem to be working just fine.

I get this in your codepen:
![image](https://user-images.githubusercontent.com/16421948/89629983-08cbbd80-d8e2-11ea-99ef-09feec8e33ce.png)

**Comment by matthieusieben** [comment]
Hey @KaelWD any estimate as to when we could see this bugfix live ?

**Comment by flyingL123** [comment]
@matthieusieben @KaelWD I just ran into this same problem. It still doesn't seem to be working properly with 2.3.9. I don't get an error anymore. Instead the callback is just never called:

https://codepen.io/flyingl123/pen/eYZvEjp?editors=1011

Is this a known issue or is this expected to be fixed already?

**Comment by flyingL123** [comment]
@matthieusieben @KaelWD I'm having trouble understanding if this is fixed or not. Can you offer any help? As you can see in the linked codepen in my previous comment it does not appear to work in 2.3.9. I am finding however that the `enter` hook does work. But not `beforeEnter` or `afterEnter`. If you edit the codepen from `@before-enter` to just `@enter`, the callback is fired.

**Comment by matthieusieben** [comment]
In my code, `@beforeEnter` does indeed trigger. no idea why it doesn't in your example

**Comment by KaelWD** [comment]
@flyingL123 that codepen is using 2.3.7

**Comment by flyingL123** [comment]
@KaelWD not sure how that happened. It's using 2.3.9 now and still not being triggered. https://codepen.io/flyingl123/pen/eYZvEjp?editors=1011

This is on a Mac using Chome 84.0.4147.125.
