### ISSUE TITLE
[Bug Report] V-banner is now transparent when it shouldn't be

### ISSUE THREAD

**Issue by hannahstclaire** [vuetifyjs/vuetify#12015]
### Environment
**Vuetify Version:** 2.3.8
**Last working version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Windows 10

### Steps to reproduce
put a v-banner over any element with a background color and you will see that it is transparent

### Expected Behavior
back ground color of the banner should match your set theme on light and dark mode

### Actual Behavior
is transparent

### Reproduction Link
<a href="https://codepen.io/hstclaire/pen/jOqEMyd" target="_blank">https://codepen.io/hstclaire/pen/jOqEMyd</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
