### ISSUE TITLE
[Bug Report] Slide group is not scrollable for mobile (y-axis)

### ISSUE THREAD

**Issue by alibaver** [vuetifyjs/vuetify#12026]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.5.17
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
Open link and touch scroll down on slide group area. Doesn't work.

### Expected Behavior
Touch scroll on mobile (y-axis)

### Actual Behavior
Doesn't scrollable y axis. Only scrollable x axis.

### Reproduction Link
<a href="https://codepen.io/alibaver-the-sasster/pen/zYqxmJp" target="_blank">https://codepen.io/alibaver-the-sasster/pen/zYqxmJp</a>

### Other comments
Slide group is not scrollable for mobile (y-axis). Slide only x axis.

**Comment by kiankji** [comment]
+1

**Comment by MeHattabi** [comment]
Same problem here.

**Comment by johnleider** [comment]
The reproduction no longer works and this is a very old issue.

This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
