### ISSUE TITLE
[Bug Report] Double click on dropdown menu with a disabled list-item triggers click event on that list-item

### ISSUE THREAD

**Issue by sbarlabanov** [vuetifyjs/vuetify#12021]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1.1
**OS:** Mac OS 10.14.6

### Steps to reproduce
Make a double-click on the bottom half of "Dropdown" button.

### Expected Behavior
No click event is trigger. No click listener of the disabled list-item is called.

### Actual Behavior
onClick handler of the first contained item is called despite that it is disabled.

### Reproduction Link
<a href="https://codepen.io/sbarlabanov/pen/dyMPeMp" target="_blank">https://codepen.io/sbarlabanov/pen/dyMPeMp</a>

### Other comments
This happens when the menu items are shown over the button (like in the example), which may always happen depending on the window size and layout. Seems like the second click is captured by the list-item despite "pointer-events: none".

**Comment by KaelWD** [comment]
Reproduced in chrome 83 and firefox 79 on linux.
