### ISSUE TITLE
[Bug Report] HTML draggables don't work inside slots

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#12029]
### Environment
**Vuetify Version:** 2.3.8
**Last working version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
1. Create a ```<template v-slot:day>``` or any other v-slot inside ```<v-calendar>```.
2. Create ```<div draggable="true">Text</div>``` inside that v-slot

### Expected Behavior
I expect that ```<div>``` to be draggable using HTML5 API. 

### Actual Behavior
The ```<div>``` does not drag.

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/poyvGXP" target="_blank">https://codepen.io/pumpknhd/pen/poyvGXP</a>

### Other comments
If the ```<div>``` is outside the v-slot, it works fine. See reproduction link.

**Comment by pumpknhd** [comment]
Workaround: 

- Add @dragstart and event.stopPropagation() to prevent the parent element (v-calendar) from stopping the drag.

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
