### ISSUE TITLE
Icon doesn't inherit color from text

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1202]
### Steps to reproduce

Create button with icon, add "primary" prop or class="...--text" to button 

### Versions
0.14.7

### What is expected ?
Icon should have same color as text

### What is actually happening ?
Icon color differs from the text color

### Reproduction Link
light theme - https://codepen.io/anon/pen/pryOLb
dark theme - https://codepen.io/anon/pen/jLqvJM
EDIT: one more example with toolbar - https://codepen.io/anon/pen/mMPzRy

Codepen include workaround - I've added css fix for correcting icon color of the last 2 buttons. I've set icon color to "inherit", but it could be fixed in Vuetify just by removing the following rule

`.application--light .icon {
    color: rgba(0,0,0,.54);
}`

and corresponding rule for dark theme, however maybe this fix could have a negative impact somewhere else which I'm not aware of, the only thing I know is that the text color is slightly different from the icon color - rgba(0,0,0,.87) vs rgba(0,0,0,.54), but it's only for the light theme, in the dark theme both are the same (#fff)

**Comment by ArnoutVerhaar** [comment]
d

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
