### ISSUE TITLE
[Feature Request] Allow to set a class to the input element in a v-text-field

### ISSUE THREAD

**Issue by silvioprog** [vuetifyjs/vuetify#12024]
### Problem to solve

It would allow to specify a class specifically for the input element in a `v-text-field`.

### Proposed solution

Allow to centralize the input value, for example: `input-class="text-center"`.

**Comment by KaelWD** [comment]
You can target the input element with `.v-text-field ::v-deep input`

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
