### ISSUE TITLE
[Bug Report] V-ripple misbehavior in chrome 

### ISSUE THREAD

**Issue by WilliamColmenares** [vuetifyjs/vuetify#12033]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Opera
**OS:** Ubuntu undefined

### Steps to reproduce
Click on any table row.

### Expected Behavior
Ripple working inside the row

### Actual Behavior
ripple target seems to be the whole table

### Reproduction Link
<a href="https://codepen.io/willcolmenares/pen/vYGOWoG" target="_blank">https://codepen.io/willcolmenares/pen/vYGOWoG</a>

### Other comments
Works ok in firefox. but with chrome and opera doesn't work properly.

**Comment by KaelWD** [comment]
In CSS 2.1 `position: relative` doesn't work on table elements: https://www.w3.org/TR/CSS21/visuren.html#propdef-position

Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=417223

Workaround:
```css
tr {
  transform: scale(1)
}
```

**Comment by KaelWD** [comment]
This was fixed in chrome 91
