### ISSUE TITLE
Cannot resolve internal dependencies with typescript

### ISSUE THREAD

**Issue by janein** [vuetifyjs/vuetify#1203]
### Steps to reproduce
I try to use a vuetify-component i.e. the tabs-component. So I import the component like this:
`import VTabsBar from 'vuetify/src/components/tabs/VTabsBar'`
When building with webpack I get the following error message:
```
These dependencies were not found:

* ~mixins/resizable in ./~/vuetify/src/components/tabs/VTabsBar.js
* ~components/icons/VIcon in ./~/vuetify/src/components/tabs/VTabsBar.js

To install them, you can run: npm install --save ~mixins/resizable ~components/icons/VIcon
```
Everything is installed correctly, webpack (and my IDE) just can't resolve the syntaxt with the tilde.

### Versions
Vuetify: 0.14.7
Vue: 2.3.3
typescript: 2.4.2
ts-loader: 2.3.1
webpack: 2.6.1

### What is expected ?
To resolve the dependencies correctly

### What is actually happening ?
Internal dependencies can not be resolved

### Reproduction Link
Sorry, I don't know how to deliver an reproduction link as it is a problem appearing while building.

This is probably a conflict with the typescript resolver in webpack. Has anyone experience with vuetify and typescript?

This is my `tsconfig.json`:
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "strict": true,
        "noImplicitReturns": true,
        "noImplicitAny": false,
        "module": "es2015",
        "moduleResolution": "node",
        "allowJs": true,
        "target": "es5",
        "allowSyntheticDefaultImports": true
    },
    "include": [
        "./src/**/*"
    ],
    "modules": [
        "./src",
        "node_modules"
    ]
}
```

thanks!

**Comment by nekosaur** [comment]
Vuetify currently does not support importing individual components. You need to do

```
import Vuetify from 'vuetify'

Vue.use(Vuetify)
```

**Comment by pspeter3** [comment]
Does vuetify have TypeScript support?

**Comment by johnleider** [comment]
There were a few typescript definitions added with https://github.com/vuetifyjs/vuetify/pulls?utf8=%E2%9C%93&q=is%3Apr%20typescript @pspeter3
