### ISSUE TITLE
[Bug Report] Carousel - v-model not being updated correctly (prevents transition to the right)

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#12041]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
1. Create v-carousel with a v-model. 
2. Create buttons for model++ and model--

### Expected Behavior
When model reaches 0 and tries to model--, it should loop around to the end.

### Actual Behavior
Model is stuck at 0.

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/BaKodyp" target="_blank">https://codepen.io/pumpknhd/pen/BaKodyp</a>

### Other comments
The other direction works. See reproduction link. When at Slide 5 and you click on the plus icon, it goes to Slide 1. But at Slide 1 and you click on the minus button, it's stuck there.

Manually changing the v-model doesn't work because the transition would be in the wrong direction.

**Comment by Mert75** [comment]
The cycle props allows you to do this with the arrows (which are also shown in the example), however, if you don't want to use them you could use `watch:` on the model to set the model to the last item if the models value is -1. 

I made a [codepen](https://codepen.io/itsyeah/pen/PoNNrzd) for you.

**Comment by pumpknhd** [comment]
@Mert75 Thanks for your codepen, but notice that the animation is inconsistent between the swipe vs the buttons. At Slide 5, I'd you click the button to go next, it slides appropriately to Slide 1. But when you swipe to go next, the animation is backwards.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
