### ISSUE TITLE
[Bug Report] Height of the data table rows is not adjusted in the mobile view

### ISSUE THREAD

**Issue by MilenaMalysh** [vuetifyjs/vuetify#12049]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
open the table on a mobile device

### Expected Behavior
The height of the rows is adjusted to the text length

### Actual Behavior
the texts overlap each other

### Reproduction Link
<a href="https://jsfiddle.net/MilenaMalysh/uzhst0j5/" target="_blank">https://jsfiddle.net/MilenaMalysh/uzhst0j5/</a>

### Other comments
This bug has already been fixed before (https://github.com/vuetifyjs/vuetify/issues/8761)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by vcavallo** [comment]
Is this not a regression from the fix in #8761? Why is this issue closed?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
