### ISSUE TITLE
`v-bottom-sheet` has no events?

### ISSUE THREAD

**Issue by rmirabelle** [vuetifyjs/vuetify#12047]
Documentation for `v-bottom-sheet` shows no available events. 

As such, it's unclear how to programmatically dismiss a bottom sheet when clicked outside. Surely, the `v-model` `@input` event isn't being thwarted to capture clicking outside the bottom sheet. If so, that's an absolutely _horrifying_ API choice, as `@input` describes nearly the _exact opposite_ of the behavior we're capturing (clicking outside).

`v-menu` and `v-dialog` support `@click:outside`, but `v-bottom-sheet` doesn't?  Are all bottom sheets modal/undismissable by design? If so, I would argue they definitely shouldn't be. Clicking outside a bottom sheet should behave identically to clicking outside a menu or dialog.

To summarize:

1) How do you programmatically dismiss a `v-bottom-sheet` when clicked outside?
2) Can we expect to see `v-bottom-sheet` support `@click:outside`, like `v-menu` and `v-dialog`?

**Comment by KaelWD** [comment]
> `v-menu` and `v-dialog` support `@click:outside`

You shouldn't use that to detect if it's been closed though, they can be closed with the escape key too. 

> If so, that's an absolutely horrifying API choice

Older versions of Vue didn't have `ComponentOptions.model`, so if you wanted to use v-model on a component it had to use `:value` and `@input`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
