### ISSUE TITLE
[Feature Request] Simple information dialog API

### ISSUE THREAD

**Issue by CutePikachu** [vuetifyjs/vuetify#12048]
### Problem to solve
Use javascript code to open a simple dialogue supporting info, success, warning and error styles like sweet alert(https://sweetalert.js.org/).  

### Proposed solution
Code here https://github.com/t4t5/sweetalert can be used as guidance.

**Comment by KaelWD** [comment]
Duplicate of #3037

Not to say that it's entirely ruled out but it's not a feature we're currently pursuing.
