### ISSUE TITLE
[Documentation] v1 Documentation Site is Down: ZEIT Now 1.0 is being shut down.

### ISSUE THREAD

**Issue by bendiy** [vuetifyjs/vuetify#12042]
### Environment

**Browsers:** Mozilla Firefox
**OS:** Linux

### Steps to reproduce
Go to: https://v1.vuetifyjs.com/

### Expected Behavior
v1 documentation loads

### Actual Behavior
503 error:

```
This deployment is not available anymore.
ZEIT Now 1.0 is being shut down. As part of this, all ZEIT Now 1.0 Deployments will become inaccessible.

If you are the owner of this ZEIT Now 1.0 Project, click here to learn more →
```

### Reproduction Link
<a href="https://v1.vuetifyjs.com/" target="_blank">https://v1.vuetifyjs.com/</a>

**Comment by bendiy** [comment]
Page is loading now. Thanks!

**Comment by bendiy** [comment]
It's down again.

**Comment by StratusBase** [comment]
Is there any way that this could be self hosted? I checked the legacy-docs repo and I can't even install dependencies...
`error An unexpected error occurred: "https://codeload.github.com/vuetifyjs/api-generator/tar.gz/4c025f3cb89d055926451a33bd0c1c3e00da92c6: Request failed \"404 Not Found\"".`

**Comment by MajesticPotatoe** [comment]
@StratusBase we are still looking into this. That repo would not be the correct one that you are looking for as it an archived version of v1.3.3 (pre monorepo) and not v0.17 version that was originally hosted at v1.vuetifyjs.com. We do have another backup but it is of v0.16.

**Comment by Aymkdn** [comment]
v0.16 or whatever version would be fine I guess… I'm still working with one of this old version of Vuetify and without the documentation is difficult to do anything.

**Comment by fabiodiniz** [comment]
Same here... Looking for the doc and still offline :(

**Comment by road-cycling** [comment]
+1

**Comment by MajesticPotatoe** [comment]
just leaving this here for people that want to pull down locally:
you can clone [https://github.com/vuetifyjs/legacy-docs](https://github.com/vuetifyjs/legacy-docs)
and then checkout:
`git checkout 26a611b` -last version that doesn't rely on api-gen this is on beta 1.1.0-beta.1
`git checkout 96863ba` - v1.0.17 - last before bump to 1.1 beta
you will need older node versions for these (believe 9 or 10)

**Comment by Aymkdn** [comment]
Thanks @MajesticPotatoe 

I deployed v1.0.17 on https://vuetify-v1-doc.netlify.app/#/vuetify/quick-start

**Comment by road-cycling** [comment]
@Aymkdn This is great. Thanks for hosting.

**Comment by yuanhao-li** [comment]
+1

**Comment by johnleider** [comment]
We are not currently looking to migrate v1 to a structure that works with Zeit v2. If bandwidth changes I'm open to revisit this, but as time goes on, the less likely that becomes.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
