### ISSUE TITLE
[Bug Report] v-img does not honor cache-control must-revalidate

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#12043]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.5

### Steps to reproduce
I have a `v-img` that points to an image. The image returns the following in the Response Headers:
`cache-control: max-age=0, must-revalidate, private`

The `must-revalidate` part indicates that the browser should check with the server again when needed, and the server could reply with a 304 NOT MODIFIED.

When the `v-img` is mounted the first time, it will get the image with the server, and will get a 304 if the image has not changed. But any subsequent mounts of the `v-img` will not trigger a network request (checked from the Chrome Dev Tools).

I suspect `v-img` has it's own internal cache or something, but it should honor the Cache Control directives.

### Expected Behavior
Honor cache control directives, and request the image to the server.

### Actual Behavior
Does not request the image to the server after the first mount.

### Reproduction Link
<a href="https://codepen.io/gotson/pen/eYZJzKG" target="_blank">https://codepen.io/gotson/pen/eYZJzKG</a>

**Comment by gotson** [comment]
@KaelWD I have some kind of reproduction.

The CodePen has 2 images with different _cache control_ directives:
- on the left, cache control is public, so the image can remain in cache
- on the right, cache control has must-revalidate, so the image should be checked with the server before using the cache

I added a switch for display, i think that a `v-if` should unmount and remount the `v-img` every time it is flipped.

I recorded [a video](https://imgur.com/a/E9TPqtQ), showing what happens with the Chrome Dev Tools network tab.

You can see that with browser cache enabled, both images are requested on the network only once. When disabling the cache however, the images are requested on the network every time the image is displayed.

What i would expect for `v-img` with an image with a cache control `must-revalidate` is the same behaviour as with the cache disabled, a network request for every display. That request should return a `304 NOT MODIFIED` most of the time if the image is still accurate.

**Comment by KaelWD** [comment]
Thanks for putting that together. This appears to be browser behaviour, you'll see it with `<img>` too. Images are cached in memory so subsequent requests on the same page load won't hit the network at all. You might be able to work around this by requesting the image over AJAX instead and using [`URL.createObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to get a temporary URL you can pass to v-img. 

> cache control has must-revalidate, so the image should be checked with the server before using the cache

Only if the cache is stale, your example has `max-age=15552000` so it won't revalidate for 180 days.

**Comment by gotson** [comment]
> Only if the cache is stale, your example has `max-age=15552000` so it won't revalidate for 180 days.

You are right. It is difficult to find freely available images with cache control for reproduction.

What would happen with a `max-age=0` then ? Because that's what my application is using, and the `v-img` is not requesting the image again on the network.

**Comment by KaelWD** [comment]
I think the browser still ignores that until you reload the page. Here's an example of how you might use `fetch()` instead: https://codepen.io/kaelwd/pen/JjXGWXz?editors=1010
