### ISSUE TITLE
[Bug Report] v-radio ignores model

### ISSUE THREAD

**Issue by d11-acummins** [vuetifyjs/vuetify#12040]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 79.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create a v-radio-group with a listener on the change event.
2. Have the listener change the model value by selecting different radio buttons in the group.

### Expected Behavior
The model value set in the change listener matches the correct radio button

### Actual Behavior
The first change event updates the selected radio button correctly. Further changes will update the model correctly, but the selected radio button does not reflect the model

### Reproduction Link
<a href="https://codepen.io/d11-ac/pen/MWyaoBO" target="_blank">https://codepen.io/d11-ac/pen/MWyaoBO</a>

**Comment by MajesticPotatoe** [comment]
you need a `$nextTick()`
```
this.$nextTick(() => {
  this.radios = '3'
})
```

**Comment by d11-acummins** [comment]
Thank you so much 😃
