### ISSUE TITLE
[Documentation] Website Documentation Dark Theme

### ISSUE THREAD

**Issue by infacto** [vuetifyjs/vuetify#12050]
### Problem to solve
Please provide a dark mode for the website. My eyes hurt.

### Proposed solution
Adding a component in the toolbar to toggle dark mode. And maybe an auto detection from OS.

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/90132028-6e232100-ddb0-11ea-8be5-8b241b58ee4a.png)

**Comment by infacto** [comment]
Yes, sorry. I found it right now. Thanks. Looks like a gear for settings. 😃
