### ISSUE TITLE
[Bug Report] Cannot disable VItem in VItemGroup

### ISSUE THREAD

**Issue by dr4key** [vuetifyjs/vuetify#12055]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
Add disabled prop to VItem

### Expected Behavior
Prevent user from activating disabled item

### Actual Behavior
Switching disabled prop to false or true has no effect

### Reproduction Link
<a href="https://codepen.io/LukKu/pen/PoNNoar" target="_blank">https://codepen.io/LukKu/pen/PoNNoar</a>

**Comment by YipingRuan** [comment]
@MajesticPotatoe 
Do we actually have "disabled" for VItem? It is in the doc: 
![image](https://user-images.githubusercontent.com/5492274/93705652-74e04900-fb51-11ea-9064-f3ddb2460499.png)

But not in the code?
![image](https://user-images.githubusercontent.com/5492274/93705688-c8eb2d80-fb51-11ea-8e18-4c2a7c180a7c.png)

**Comment by MajesticPotatoe** [comment]
@YipingRuan 
Its inherited from groupable mixin, just not implemented it would seem.

**Comment by KaelWD** [comment]
This would probably resolve #13585 too.

**Comment by dom-velloso** [comment]
Are you guys planning to fix this?
