### ISSUE TITLE
[Feature Request] Developers should be able to hook Alerts dismiss trigger with custom actions

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#1205]
# Feature Request

## What will it allow you to do that you can't do today?
Developers should be able to configure at least one of these for __Alerts__:
- custom actions with buttons/icons
- change the dismiss button behaviour with a hook

## How will it make current work-arounds straightforward?
Right now, it is really cumbersome to correctly control a list of alerts that can be dismissed independently; it is specially hard if you are using state managers like vuex.

## What potential bugs and edge cases does it help to avoid?
Having to create custom components that basically mimic alerts, but offer a little more functionality.

**Comment by chrislandeza** [comment]
You can easily achieve this  by watching the model.


```
<template>
    <v-alert error dismissible v-model="visibility">
        My Alert
    </v-alert>
</template>


<script>
    export default {
        data() {
            return {
                visibility: true
            }
        },
        watch: {
            visibility (val) {
              if (val) {
                  // Custom action when the alert was shown
               } else {
                 // Custom action when the alert was hidden
               }
            }
        }
    }
</script>
```

**Comment by codetrash** [comment]
we're forced to use watcher for that

**Comment by 464bb26bac556e85b6fd6b524347b103** [comment]
Binding to `input` accomplishes this.

**Comment by tripflex** [comment]
While this may work for single alerts -- what about when there are multiple alerts showing .. using a watcher for that would be very tedious

**Comment by nekosaur** [comment]
You do not have to create a watcher. https://codepen.io/anon/pen/qwzgRK
