### ISSUE TITLE
[Bug Report] v-list-group value prop always interpreted as true

### ISSUE THREAD

**Issue by jblachly** [vuetifyjs/vuetify#12056]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 79.0
**OS:** Mac OS 10.14

### Steps to reproduce
v-list-group `value` assigned ANY value (true or false, or whatever) causes list group to be open.

You can see this in one of the documentation's provided examples, which I have saved as a codepen for purposes of the issue report.

Note that the "Actions" submenu which has no value prop passed, begins as closed, whereas "Users" and "Admin" will begin as open no matter the value assigned.

### Expected Behavior
`value="false"` or `value=false` should cause the list group to be closed

### Actual Behavior
Binding or assigning any value to value causes v-list-group to be open; whereas omitting it entirely causes it to be closed

### Reproduction Link
<a href="https://codepen.io/jamesblachly/pen/OJNNVqo?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Flists%2F" target="_blank">https://codepen.io/jamesblachly/pen/OJNNVqo?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Flists%2F</a>

### Other comments
May be similar or related to https://github.com/vuetifyjs/vuetify/issues/8166

**Comment by jacekkarczmarczyk** [comment]
You need to bind it
`:value="false"`

**Comment by jblachly** [comment]
@jacekkarczmarczyk -- thanks for your help. This should probably stay open as a documentation bug. **As I indicated, the example is straight from the vuetify docs**

**Comment by jacekkarczmarczyk** [comment]
Yup, missed the documentation part

https://vuetifyjs.com/en/components/lists/#nested-lists

**Comment by jblachly** [comment]
This also exposes another bug.

If you bind the outer (Users, in the example) to false, the inner (Admin, in the example) will always start as closed no matter its bound value.

**Comment by jacekkarczmarczyk** [comment]
That's another thing, please create a new issue and provide reproduction (if it's not same as 8166)

**Comment by ricardovanlaarhoven** [comment]
I've tried to start making a fix for this, but i guess this is already fixed?
The sub group example now has `:value="true"` at all those places

or am i looking at the wrong place?
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-list/prop-sub-group.vue

**Comment by johnleider** [comment]
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
