### ISSUE TITLE
[Documentation] Ability to change "Sort by" text on VDataTableHeaderMobile  mobile version

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#12068]
### Problem to solve
Translation issue, currently we can set all text on a data table to our custom translation with this exception.

### Proposed solution
Make it a settable property like other aspects of data table such as "items-per-page-text" etc

**Comment by MajesticPotatoe** [comment]
This does already exist, just seems like a lapse in documentation as mobile props seem to not be caught by api-gen (as the mobile portion of the `v-data-table-header` holds the props in a non-public component).

`sortByText` is the prop you are looking for and can be set on v-data-table like so:  `:header-props="{ sortByText: 'Some Text' }"`

**Comment by WhatFreshHellIsThis** [comment]
Awesome!  Thank you!
