### ISSUE TITLE
[Feature Request] v-virtual-scroll with draggable

### ISSUE THREAD

**Issue by animeshsa** [vuetifyjs/vuetify#12066]
### Problem to solve
v-virtual-scroll not working with draggable is there any way to do this?

### Proposed solution
any way out this so that I can use both.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js). If this is supposed to be a bug report then please open a new issue with the required information.
