### ISSUE TITLE
The disabled v-list-tile remains clickable for a short time

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#1206]
### Steps to reproduce
1. Create list with disabled elevtnt in menu
2. Open menu and fast click on disabled element

### Versions
Vuetify 0.14.7

### What is expected ?
The disabled item does not respond to the cursor at all times

### What is actually happening ?
Within a short time after opening the menu, the element remains active and can be pressed

### Reproduction Link
https://codepen.io/cawa-93/pen/vJKYXg?editors=1010#0

**Comment by johnleider** [comment]
Now that all events are bound to the instance, your @click event isn't actually hooking into the pre-existing click event, it's using yours. You will need to check for the disabled state yourself and prevent the action if it is. Removing this stops your issue, however, it also means we lose the ability to not have to assign .native to random events.

**Comment by cawa-93** [comment]
And what about the `hover`? He also remains for a short time.
