### ISSUE TITLE
[Bug Report] The group function in DataTable doesn't work when some item's data is null

### ISSUE THREAD

**Issue by oraant** [vuetifyjs/vuetify#12069]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows

### Steps to reproduce
Just modify the default example in the official document.
Change some item's field to undefined or null

Turns out 'undefined' works normal, 
but 'null' field will cause the components crash!

### Expected Behavior
I hope that null will work's too, because some back-end restful api will return null for you.

### Actual Behavior
Crashed

### Reproduction Link
<a href="https://codepen.io/oraant/pen/mdPELgJ" target="_blank">https://codepen.io/oraant/pen/mdPELgJ</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/8bc08b28695684de1700e7448a16187788533306/packages/vuetify/src/util/helpers.ts#L266-L268

**Comment by KaelWD** [comment]
Looks like #11970 already fixes this. Would you expect null values to actually say "null" or just be treated like an empty string?

**Comment by oraant** [comment]
> Looks like #11970 already fixes this. Would you expect null values to actually say "null" or just be treated like an empty string?

There are more options like: 

- `---`
- `null`
- `''`
- `/`
- `\`
- `*`
- `ⓧ`
- `ø`
- `empty`
- `Помещения`
- `空`

So I guess the best way is to set it as a prop, and let coders custom the string.

If I must make a choice, the empty string will be my favorite
