### ISSUE TITLE
[Bug Report] In data-table[V-edit-dialog] use v-text-field  "item.name" is not work 

### ISSUE THREAD

**Issue by luckygogreen** [vuetifyjs/vuetify#12064]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 3.0.0-rc.5
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.13.5

### Steps to reproduce
You cannot use “name” as your attribute name

### Expected Behavior
You cannot use “name” as your attribute name

### Actual Behavior
You cannot use “name” as your attribute name

### Reproduction Link
<a href="https://codepen.io/luckygogreen/pen/WNwwBMK?editors=1010" target="_blank">https://codepen.io/luckygogreen/pen/WNwwBMK?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
> https://codepen.io/luckygogreen/pen/WNwwBMK?editors=1010

This is not a valid reproduction

> Vue Version: 3.0.0-rc.5

At the moment Vuetify doesn't work with Vue 3.0

**Comment by luckygogreen** [comment]
Thank you very much ! This is not a bug ,I did the the wrong way! Thank you for ur help!
