### ISSUE TITLE
[Feature Request] Add onScroll event to 'v-virtual-scroll'!

### ISSUE THREAD

**Issue by khb1109** [vuetifyjs/vuetify#12077]
### Problem to solve
How are you?

This user is using vuetify.

There was an inconvenience in trying to implement Infinity Scroll while using vuetify.

I tried to use infinite scrolling within the component, but v-virtual-scroll didn't support the event when scrolling.

Of course, there was a bench option, but it was difficult to implement the function of requesting API whenever scrolling touched the floor.

I wonder why v-virtual-scroll doesn't support onScroll events!

If there is no special reason, I request a new function.

### Proposed solution
Add onscroll events from vuetify.

**Comment by khb1109** [comment]
Instead of using the component, html was used.

Added 'overflow-y: scroll' css to div. Then added 'v-on:wheel'.

However, v-virtual-scroll was unable to catch the event even with v-on:wheel.

**Comment by KaelWD** [comment]
v-virtual-scroll isn't passing through event listeners, workaround is to use the [`.native` modifier](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components).

**Comment by ducvietsqt** [comment]
How to keep alive state row when not invisible of view port?
