### ISSUE TITLE
[Bug Report] v-menu adds unnecessary horizontal offset when window is horizontally scrolled and activator is under fixed position

### ISSUE THREAD

**Issue by omanizer** [vuetifyjs/vuetify#12078]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Linux x86_64

### Steps to reproduce
1. Click the menu button
1. Observe the v-menu content populates in the correct position
1. Scroll to the right horizontally
1. Click the menu button again
1. Observe that the v-menu content is positioned incorrectly.

### Expected Behavior
The menu content should be positioned correctly under the menu button regardless of horizontal scroll position.

### Actual Behavior
The menu content shifts to the right directly proportional to document.scrollingElement.scrollLeft

### Reproduction Link
<a href="https://codepen.io/ohmance/pen/JjXRYeJ" target="_blank">https://codepen.io/ohmance/pen/JjXRYeJ</a>

### Other comments
This happens for v-menu as well as anything that inherits v-menu such as v-select and v-autocomplete.

**Comment by KaelWD** [comment]
This is caused by https://github.com/vuetifyjs/vuetify/pull/5527, if I remove `getOffsetLeft` then it works correctly.

**Comment by omanizer** [comment]
I think a possible solution might be to traverse up the DOM and see if any of the parent elements are position: fixed.  If so then it would ignore `getOffsetLeft`.

I'd be happy to take a bash at a PR if anyone agrees.

**Comment by Odrahcyr** [comment]
@omanizer Any progress?

**Comment by omanizer** [comment]
I'd be happy to give it a go if a PR that follows that algorithm would be entertained.  @KaelWD what are your thoughts?  I could start work on it this week if so.

**Comment by KaelWD** [comment]
This seems to have been fixed at some point.
