### ISSUE TITLE
[Feature Request] Get all items at once when filter prop is used with vautocomplete

### ISSUE THREAD

**Issue by prashanth4** [vuetifyjs/vuetify#12072]
### Problem to solve
Currently while searching in the autocomplete headers are not included in the drop list. So when filter function get's all the items at once I can push header accordingly after filtering the items with search string.

### Proposed solution
When filter prop is used with autocomplete, call filter function with all items at once instead of calling N(No. of items) times.

**Comment by darosh** [comment]
It looks like using `text` and `header` property at same item somehow works.
`[{header: group.name, text: group.items.map({text} => text).join('~')}, ...group.items]`
