### ISSUE TITLE
[Feature Request] SSR support for v-treeview component

### ISSUE THREAD

**Issue by suleymangezsat** [vuetifyjs/vuetify#12082]
### Problem to solve
Only parent items are created on VTreeview rendering part but child ones are not. So html returning from server side doesn't include child items and it causes crawl issues. 

### Proposed solution
There should be a prop to indicate creating child items in render function of v-treeview. So that html returning from server can include child items as well. Functionality will work the same as v-menu component's "eager" prop.

**Comment by franckaragao** [comment]
+ 1

**Comment by giselecpferreira** [comment]
+1

**Comment by giselecpferreira** [comment]
+1
