### ISSUE TITLE
[Feature Request] Query Builder for vuetify

### ISSUE THREAD

**Issue by chrisborecki** [vuetifyjs/vuetify#12089]
### Problem to solve
Query builder could be a nice vuetify addition.

### Proposed solution
Make it a standard component. Something like: https://vuejsexamples.com/a-vue-query-builder-library/

**Comment by jakubmatisak** [comment]
Hello, I have to ask, why this was closed as completed, is it not planned?
I'm dealing with fiterBuilder in one project, and component would be a nice a feature for vuetify.

I have found custom filter for VDataTableAPI, but a whole component like this is not possible to create.
https://js.devexpress.com/Vue/Demos/WidgetsGallery/Demo/FilterBuilder/WithDataGrid/MaterialBlueLight/

Thank you
