### ISSUE TITLE
[Feature Request] Save parent nodes values in model of a v-treeview when in leaf selection mode  

### ISSUE THREAD

**Issue by jousepo** [vuetifyjs/vuetify#12085]
### Problem to solve
In a hiearchy i want to select all the values in the hierarchy of the leaf. 
Parent nodes must be selected (or configurable) as in the individual mode.  

### Proposed solution
It will be usefull that you can configure a param (include-leaf-parents?) that forces the selection of the parent nodes of a leaf in model

**Comment by nekosaur** [comment]
There is not enough information here to know if this is a duplicate of existing issues. Please have a look at https://github.com/vuetifyjs/vuetify/issues/7799 and https://github.com/vuetifyjs/vuetify/issues/9088. If either describe what you are after, please close this issue.

If not, please add a more detailed description of how exactly the selection mode should work.

**Comment by jousepo** [comment]
#7799 and #9088 are valid!! I'll pay attention on them.

Thanks for the information.
