### ISSUE TITLE
[Feature Request] Fire events in v-virtual-scroll

### ISSUE THREAD

**Issue by dschreij** [vuetifyjs/vuetify#12094]
### Problem to solve
According to the docs, `v-virtual-scroll` doesn't fire any events, but it would be nice if it would fire one if it (almost) reaches the end of its items stream. You could hook this into a fetching function that retrieves more items and easily implement 'infinite scrolling' this way. 

### Proposed solution
When `v-virtual-scroll` reaches the end of its items stream, fire an event that designates this (for instance `$emit('end-of-stream')`). One could even make it configurable at how many items before the end of the stream the event should be fired?

**Comment by trizotti** [comment]
Hey guys, how do you scroll to an specific item on the list programatically?

**Comment by KaelWD** [comment]
#17265 adds a `renderless` prop so you could implement this by putting v-virtual-scroll inside v-infinite-scroll

**Comment by Paul-DS** [comment]
Agree, this would be really useful!

In [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller), they have [3 events](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md#events) to help handle scroll events: `update`, `scroll-start`, and `scroll-end`.

The `update` event is also useful to check when a specific item appears/disappears.
