### ISSUE TITLE
[Bug Report] items scrolling out of view in v-virtual-scroll are automatically deselected in v-list-item-group

### ISSUE THREAD

**Issue by dschreij** [vuetifyjs/vuetify#12095]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.105
**OS:** Linux x86_64

### Steps to reproduce
Place a `v-virtual-scroll` inside a `v-list-item-group` and set all items as selected.
Scroll down the list and keep an eye on the `selected` (or v-list-item-group's v-model) field in `data`. You will see that all items scrolling out of view are automatically deselected, which may be undesirable if these items should remain selected.

### Expected Behavior
Items that are selected should remain selected, even if they scroll out of view

### Actual Behavior
Items that scroll out of view are automatically deselected.

### Reproduction Link
<a href="https://codepen.io/dschreij/pen/eYZByWz?editors=1010" target="_blank">https://codepen.io/dschreij/pen/eYZByWz?editors=1010</a>

**Comment by KhanhHH** [comment]
You just need to wrap `v-list-item-group` inside `template` 🤞

**Comment by dschreij** [comment]
@KhanhHH thanks for the suggestions. I tried that in the codepen that was linked, but it didn't work for me. Maybe I am doing it wrong, so could you demonstrate what you mean in a codepen?

**Comment by KhanhHH** [comment]
@dschreij Here you go [https://codepen.io/khanhhh/pen/BazabdG](url) ❤

**Comment by dschreij** [comment]
Hi @KhanhHH, thanks for the codepen, I see what you mean but this will likely not work. Items are placed in the `v-virtual-scroll` through iteration and now you have effectively wrapped each list item in its own `v-list-item-group` component, which will operate independently from each other. I am afraid this will not solve the problem as you cannot get a list of indexes with items that are selected this way.

**Comment by KhanhHH** [comment]
@dschreij i don't know what problem you're facing , but check my codepen once again (edited) you will see that. It worked for my real usecase at least.

**Comment by dschreij** [comment]
You are right! I'm pretty amazed actually :)

The question remains however if this is intended behavior. Normally you would wrap a v-list-item-group around multiple list elements e.g.:
```vue
<v-list-item-group>
  <v-list>
     <v-list-item>...</v-list-item>
     <v-list-item>...</v-list-item>
     <v-list-item>...</v-list-item>
     ...
  </v-list>
</v-list-item-group>
```
what this solution effectively does is:
```vue
<v-list>
   <v-list-item-group>
       <v-list-item>...</v-list-item>
   </v-list-item-group>
   <v-list-item-group>
       <v-list-item>...</v-list-item>
   </v-list-item-group>
   <v-list-item-group>
       <v-list-item>...</v-list-item>
   </v-list-item-group>
</v-list>
```
I'll leave it the vuetify maintainers if this is valid workaround or an unintended side effect :)

Regardless, thanks for taking the time to place your solution here @KhanhHH

**Comment by slawekrewaj** [comment]
@KhanhHH 

It looks like there is a problem with v-virtual-scroll and v-list-item-group, although it's more subtle.
I modified your pen to show it - https://codepen.io/slawekrewaj/pen/LYZoQLo

When you select some items, and then use the slider to decrease the number of items, then the selected array is modified (cleaned) as well. It only happens when the selected items are visible. It's even stranger that, if you have some visible and some invisible items, then only the visible items are removed from selected array. Finally, if you remove the call to reverse() in computed property, everything works properly. Anyway this issue makes this use case very unstable

**Comment by KaelWD** [comment]
Yeah items automatically remove themselves from the selection when they're destroyed. This works well in most cases but not when the items are only meant to be visually hidden.

**Comment by KaelWD** [comment]
"items automatically remove themselves from the selection when they're destroyed" was removed in v3
