### ISSUE TITLE
Custom component unit tests display warning "missing <v-app>"

### ISSUE THREAD

**Issue by lattam** [vuetifyjs/vuetify#1210]
### Steps to reproduce
Run karma unit tests for custom components which contains v-dialog or v-menu.

### Versions
vuetify 0.14.7
vue 2.4.2

### What is expected ?
All test should pass without any error or warning

### What is actually happening ?
When testing components which contains v-dialog or v-menu (both using detachable mixin), the warning `Application is missing <v-app> component.` keeps displaying

### Reproduction Link
I created simple repo with three tests (using vue init vuetify/webpack + karma unit tests)
https://github.com/lattam/vuetify-test-example
- clone it, npm install, npm run unit

Note: In [Menu.spec.js](https://github.com/lattam/vuetify-test-example/blob/master/test/unit/specs/Menu.spec.js) I tried to wrap the component into `<v-app>` element, but the warning keeps displaying.

Thanks for any help!

**Comment by nekosaur** [comment]
Add the following code to your `test/unit/index.js` file

```javascript
var app = document.createElement('div')
app.setAttribute('data-app', true)
document.body.appendChild(app)
```

That way there will always be a div with data-app attribute in your tests for components to use
