### ISSUE TITLE
[Bug Report] lose selected items with selection-type="independent" and async load-children

### ISSUE THREAD

**Issue by KnyazevIvan** [vuetifyjs/vuetify#12103]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
1. select Users
2. open Users 2

### Expected Behavior
Selected items doesnt change

### Actual Behavior
Selected items disappeared

### Reproduction Link
<a href="https://codepen.io/ivanichiki/pen/jOqyZdw?editors=1010" target="_blank">https://codepen.io/ivanichiki/pen/jOqyZdw?editors=1010</a>

**Comment by johnleider** [comment]
Possible duplicate of #8791

This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
