### ISSUE TITLE
[Bug Report] v-progress-linear has a width of 0 when inside v-overlay

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#12108]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Firefox 79.0
**OS:** Mac OS 10.15

### Steps to reproduce
Put a `v-progress-linear` inside a `v-overlay`

### Expected Behavior
It should be visible, like `v-progress-circular`

### Actual Behavior
It has a width of 0, making it not visible

### Reproduction Link
<a href="https://codepen.io/ffxsam/pen/ExKZMLB" target="_blank">https://codepen.io/ffxsam/pen/ExKZMLB</a>

**Comment by MShoaei** [comment]
I have the same issue. Only solution I found was to assign width via CSS. Better solution would be appreciated

**Comment by johnleider** [comment]
The reproduction link no longer works and is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
