### ISSUE TITLE
[Feature Request] could not get selection.ids from https://vuetifyjs.com/en/components/treeview/#selection-type 

### ISSUE THREAD

**Issue by martinym28** [vuetifyjs/vuetify#12102]
### Problem to solve
only get {{selection}} within return-object
but could not get {{selection}} only keys or ids within or without return-object

### Proposed solution
how can get {{selection}} ids as array without v-for and within or without return-object from treeview

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
