### ISSUE TITLE
[Bug Report] Vuetify v-select not closed when making a programmatic click

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12107]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 10

### Steps to reproduce
Everything is described here:
https://github.com/cypress-io/cypress/issues/8376

### Expected Behavior
I should be able to close the list by programmatic click.

### Actual Behavior
I am not able to close the list by programmatic click. This causes a problem with Cypress.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/RwaKEXe" target="_blank">https://codepen.io/mikilll94/pen/RwaKEXe</a>

**Comment by KaelWD** [comment]
We might not need that any more, it was added to fix #2092 but nothing really uses `.click()` any more as far as I can tell.

**Comment by Mikilll94** [comment]
@KaelWD 
Here is the PR 🚀
