### ISSUE TITLE
[Bug Report] Expansion panel content not disabled

### ISSUE THREAD

**Issue by abhinavnigam99** [vuetifyjs/vuetify#12116]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
Open code pen and use disable check box. Panel will get disabled but text field inside panel content will remain editable

### Expected Behavior
all panel content should get disabled even if panel is open

### Actual Behavior
panel content is not disabled when panel is open

### Reproduction Link
<a href="https://codepen.io/abhinavnigam99/pen/vYGxgjG" target="_blank">https://codepen.io/abhinavnigam99/pen/vYGxgjG</a>

**Comment by jacekkarczmarczyk** [comment]
`disabled` props  disables the panels (you can't open or close the panel), not the contents

**Comment by abhinavnigam99** [comment]
@jacekkarczmarczyk Did you check the codepen I added. What should be the turnaround for the issue I am facing.

**Comment by jacekkarczmarczyk** [comment]
Apply `disabled` property to components your want to disbable (v-text-field in your case)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
