### ISSUE TITLE
[Bug Report] v-snackbar fails in tests

### ISSUE THREAD

**Issue by albertodiazdorado** [vuetifyjs/vuetify#12118]
### Environment
**Vuetify Version:** 2.3.9
**Last working version:** 2.2.34
**Vue Version:** 2.6.12
**Browsers:** Firefox 79.0
**OS:** Linux x86_64

After upgrading `vuetify` from `~2.x.y` to `^2.x.y`, tests related to the vuetify component `v-snackbar` stopped working. I created a minimal working example to reproduce the issue.
The component looks good in the demo, but it does not work as intended in the original, more complex code. Hopefully understanding the problem with the test provides insight into what is going wrong with `v-snackbar`.

### Steps to reproduce
1. Clone the repo
2. Install dependencies `yarn install`
2. Run tests `yarn test:unit`

### Expected Behavior
The test is green

### Actual Behavior
The test is red

### Reproduction Link
<a href="https://github.com/albertodiazdorado/v-snackbar-test" target="_blank">https://github.com/albertodiazdorado/v-snackbar-test</a>

### Other comments
If you modify line 17 in `package.json` from `"vuetify": "^2.2.34"` to `"vuetify": "~2.2.34"` and run `yarn install` again, the test is green. The repository was created using
```
vue create snackbar (with custom config)
cd snackbar
vue add vuetify (with custom config)
```
And then editing a couple of files

**Comment by KaelWD** [comment]
v-snackbar needs access to the `$vuetify` object since the v2.3.0 redesign, the testing page has examples of how to do this: https://vuetifyjs.com/en/getting-started/unit-testing/

**Comment by albertodiazdorado** [comment]
Thanks! That helps! :D

**Comment by tobi-fis** [comment]
> v-snackbar needs access to the `$vuetify` object since the v2.3.0 redesign, the testing page has examples of how to do this: https://vuetifyjs.com/en/getting-started/unit-testing/

Is there any update to this for Vuetify 3? (The link ends in a 404 page) 
I can't get unit tests with `v-snackbar` to work after upgrading to v3 because the component does not render in the test env. I am using jest and vue-test-utils.
I also tried mocking the `$vuetify` object, although I am not sure this is how Vuetify 3 operates since the setup has changed so much.
Cheers and thanks in advance.

**Comment by JoelYoung01** [comment]
@tobi-fis, I ran into the same issue but was able to fix it partially by setting document.body to a body element and then mounting VApp as a wrapper. Here is my code, note I am using vitest:

`const body = document.createElement("body");
    document.body = body;

    const wrapper = mount(VApp, {
      global: {
        plugins: [vuetify]
      },
      slots: {
        default: ContactsCard
      },
      attachTo: document.body
    });`

However, I have run into an issue where the v-snackbar element does not disappear after it's v-model value becomes false, in my unit tests. If anyone has been able to fully test a v-snackbar, your help would be appreciated!!!

**Comment by shirmagen** [comment]
> https://vuetifyjs.com/en/getting-started/unit-testing/
 @JoelYoung01,  using model-value instead of v-model fixed it for me, v-snackbar disappears after the mount of milliseconds defined in timeout prop
