### ISSUE TITLE
[Bug Report] Slowdown when closing v-navigation-drawer with 100 checkboxes (category/tag/brand filters)

### ISSUE THREAD

**Issue by isvaljek** [vuetifyjs/vuetify#12112]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.11
**Browsers:** Microsoft Edge, Other
**OS:** Android

### Steps to reproduce
Tap on the hamburger menu to open the navigation drawer, tap outside the drawer to close it, then immediately start scrolling down the page, after a few scrolls there will be a noticeable lag and scrolling will stop for a moment.

### Expected Behavior
Normal scrolling when navigation drawer collapses.

### Actual Behavior
Unresponsive scrolling when the navigation drawer closes.

### Reproduction Link
<a href="https://isvaljek.github.io/drawer-thrower/" target="_blank">https://isvaljek.github.io/drawer-thrower/</a>

**Comment by KaelWD** [comment]
Can't reproduce in chrome or edge on a Redmi Note 4X.

**Comment by isvaljek** [comment]
@KaelWD, have you tried scrolling more than a couple of times, like 4-6 times in a row, as fast as you can after taping outside the drawer, not waiting for it to close?
Have you opened my link with the sample page?

**Comment by johnleider** [comment]
We have the [v-lazy](https://vuetifyjs.com/en/components/lazy/) component that can help with this.

This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
