### ISSUE TITLE
[Feature request] VColorPicker cannot handle color becoming null

### ISSUE THREAD

**Issue by floydqwz** [vuetifyjs/vuetify#12117]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Linux x86_64

### Steps to reproduce
Use <v-color-picker> component and bind the value to some external value, then set the value to null.

### Expected Behavior
The color picker handles the situation of having color==null and doesn't convert the color to red

### Actual Behavior
The color picker sets the color to red.

### Reproduction Link
<a href="https://codepen.io/qwz/pen/bGpqqGM" target="_blank">https://codepen.io/qwz/pen/bGpqqGM</a>

**Comment by johnleider** [comment]
We are not sure if this would be breaking. Tagging for v2 maintenance but may end up going to v3 if the fix / change would cause issues in 2.x.

**Comment by blalan05** [comment]
Work around: Use :value="" and @input. In the input method, if value is null set to empty string.

**Comment by KickButtowski80** [comment]
AFAICT, This workaround does not work.
```
<v-color-picker
      :value="value || ''"
      @input="handleColorChange"
      :hide-inputs="!colorPickerState.includes(0)"
      :hide-canvas="!colorPickerState.includes(2)"
      :hide-sliders="!colorPickerState.includes(1)"
      mode="hexa"
      :swatches="swatches"
      show-swatches
    />
```
This still sets the value to `#FF0000FF` when I open the swatches.

**Comment by jsonArg** [comment]
Has anyone found a workaround solution to this ?

**Comment by canhkieu** [comment]
I tried many ways but it's not working.  Waiting for a workaround solution

**Comment by canhkieu** [comment]
This isn't a good solution. But It's work. You can try if you got problems with this component.

```vue
  <v-list-item>
    <v-list-item-content>
      <v-text-field
        v-model="value"
        :label="option.text"
        clearable
        autofocus
      ></v-text-field>
    </v-list-item-content>
    <v-list-item-action>
      <v-menu bottom :close-on-content-click="false" @input="(val) => show = val">
        <template v-slot:activator="{ on, value: status }">
          <v-btn
            class="rounded-circle"
            :color="value"
            fab
            x-small
            v-on="on"
          ></v-btn>
        </template>
        <v-color-picker show-swatches v-model="value" flat v-if="show" />
      </v-menu>
    </v-list-item-action>
  </v-list-item>
```
```js
  data(){
    return{
      show:false,
      value: ""
    }
  },
```
