### ISSUE TITLE
[Documentation] node-sass vs sass - conflicting information

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12129]
### Environment

**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
![image](https://user-images.githubusercontent.com/17653648/91470269-cc620080-e894-11ea-8b2a-cf5b6df103c5.png)

As you can see these two sections contain conflicting information. First section informs that you should have `node-sass` installed in version at least 3.5.0. The second section informs that you should have `sass` installed

### Expected Behavior
There should be no conflicting information in the docs.

### Actual Behavior
There are conflicting information in the docs.

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/frequently-asked-questions/" target="_blank">https://vuetifyjs.com/en/introduction/frequently-asked-questions/</a>

**Comment by KaelWD** [comment]
> you should have node-sass installed in version at least 3.5.0

It says that you should have `@vue/cli-*` of at least 3.5.0. Earlier versions do look for the `node-sass` package so you will get this error if you have (correctly) installed `sass` instead but are still using an older version of vue-cli.
