### ISSUE TITLE
[Bug Report] v-stepper-component not rendered on step change

### ISSUE THREAD

**Issue by caro3801** [vuetifyjs/vuetify#12121]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
As I need a content to be displayed at each step I binded the content with the current step of the stepper.
The first v-stepper-content is displayed on the first rendering of the page (in green in the example). When step 2 is edited it is not rendered. Going back to step 1, the content is not rendered either.

### Expected Behavior
The content should be rendered when the step is active

### Actual Behavior
The content is only rendered on the first render of the page

### Reproduction Link
<a href="https://codepen.io/caro3801/pen/jOqBXog?editors=1010" target="_blank">https://codepen.io/caro3801/pen/jOqBXog?editors=1010</a>

### Other comments
I have found a way to fix it in VStepperContent component by modifying the method toggle :
```js
toggle(step, reverse) {
      // this.isReverse = reverse;
      // this.isActive = step.toString() === this.step.toString();
      
      nextTick(()=>{
        this.isReverse = reverse;
        this.isActive = step.toString() === this.step.toString();
        })
    }
```

**Comment by cianiandreadev** [comment]
+1

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
