### ISSUE TITLE
Fix input-group extra padding

### ISSUE THREAD

**Issue by arvanoid** [vuetifyjs/vuetify#1212]
Recent stylus changes caused a padding issue to the datatable (See any table with a checkbox in [documentation](https://vuetifyjs.com/components/data-tables).

```css
-$input-group-margin := 18px 0
+$input-group-padding := 18px 0
```

Previously, there was a rule in _tables.styl that reverted margin to 0 if it was used in conjunction with `.input-group--selection-controls`. So, probably the rule below has to be changed to `padding: 0`

```css
  .input-group--selection-controls
    margin: 0
```

**Comment by arvanoid** [comment]
Same applies to the rule `.datatable__actions__select .input-group--select` that causes extra padding to the datatable footer.

in datatables.styl
```css
    .input-group--select
      margin: 13px 0 13px 34px
```

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by arvanoid** [comment]
Think I've already included a link to the problem.
