### ISSUE TITLE
[Bug Report] at click:row row.select(true) making all rows receive v-data-table__selected class

### ISSUE THREAD

**Issue by adrielwerlich** [vuetifyjs/vuetify#12120]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 10

### Steps to reproduce
Create a at click event handler for the data-table in which the row parameter gets the select procedure called with boolean true arg. 

### Expected Behavior
It should only highlight the selected row

### Actual Behavior
Is settings all rows as selected

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-sample-forked-s66jg?file=/App.vue" target="_blank">https://codesandbox.io/s/vuetify-sample-forked-s66jg?file=/App.vue</a>

<a href="https://s66jg.csb.app/" target="_blank">code sand box broken example on data table at row click event handler set selected row</a>

**Comment by nekosaur** [comment]
You're missing `item-key="name"`

**Comment by adrielwerlich** [comment]
> You're missing `item-key="name"`

the vuetify documentation doesn´t give clear hints about how to use this functionality. Would be interesting upgrading the docs to make they more clear on this point, perhaps!!!

**Comment by Nelida27** [comment]
I have the same problem.It selects all rows.Any idea?Thanks.

**Comment by adrielwerlich** [comment]
> I have the same problem.It selects all rows.Any idea?Thanks.

it seems that while you are declaring your `<v-data-table>` markup you should include the `item-key="name"` attribute. 

Something like this:

`
          <v-data-table
            :headers="headers"
            :items="desserts"
            :items-per-page="5"
            item-key="name"   **<= this thing over here should be an unique id** 
            class="elevation-1"
            @click:row="selectRow"
            :single-select="true"
          ></v-data-table>
`

**Comment by Nelida27** [comment]
Thanks for replaying, your example is very clear and helpful.I fixed it on my code.
