### ISSUE TITLE
Datepicker styling broken on iOS 9 device

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1213]
![image](https://user-images.githubusercontent.com/3471363/28868688-810a1fac-777a-11e7-8d8d-8664d83d5694.png)

### Steps to reproduce
The above screenshot was taken on browserstack with a real device: iPhone 6, iOS 9

Not sure how well iOS 9 is supported since its not the latest iOS so just close this issue if iOS 9 is not supported.

### Versions
vuetify 0.14.7

### What is expected ?
styling

### What is actually happening ?
styling seems to be broken

### Reproduction Link
https://vuetifyjs.com/components/pickers

**Comment by johnleider** [comment]
Fixed with #1162
