### ISSUE TITLE
[Feature Request] Reverse prop for v-slider

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#12132]
### Problem to solve
My application (komga.org) has a book reader, which shows a `v-slider` at the bottom to display the current position in the book, and doubles as a way to go a specific page ([screenshot](https://komga.org/assets/media/guides/webreader/reader.png)).

Books can be displayed in Right To Left direction, and in that case it would make sense to reverse the slider, going from right (page 1) to left (last page).

I am aware of the Material Design [guidelines](https://material.io/design/usability/bidirectionality.html#mirroring-elements) regarding mirroring, which say:

> Do not mirror media playback buttons and the media progress indicator as they refer to the direction of tape being played, not the direction of time.

However read progress is not really passage of time, but more related to progress:

> A volume icon with a slider at its right side should be mirrored. The slider should progress RTL, and the sound waves should emerge from the right.

### Proposed solution
I would like a `reverse` prop on `v-slider`, similar to the one on `v-progress-linear`.

**Comment by mostafaznv** [comment]
I need it too.

**Comment by kanjieater** [comment]
> However read progress is not really passage of time, but more related to progress:
> 
> > A volume icon with a slider at its right side should be mirrored. The slider should progress RTL, and the sound waves should emerge from the right.
> 
It's also incredibly standard in Japanese media, as it's the intuitive direction when consuming content in a right to left fashion. 
You can see by the previewers here from one of many Japanese book readers:
https://viewer-trial.bookwalker.jp/03/9/viewer.html?cid=a1b40331-bf44-4a97-b4c8-c1b98070c43e&cty=2
