### ISSUE TITLE
[Bug Report] v-range-slider dragging over point does not work on other point while still focussed

### ISSUE THREAD

**Issue by sjoris** [vuetifyjs/vuetify#12133]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Firefox 79.0
**OS:** Windows 10

### Steps to reproduce
Drag one point with the mouse, **over** the other point. After dragging, do not click somewhere else, but start dragging the other point and try to also drag that point **over** the first point.

### Expected Behavior
While dragging over a point, it is expected that the other point keeps in place. Example: drag the minimum over the maximum, then it switches so you are dragging the maximum. That should work every time.

### Actual Behavior
This only works with the first point you start with, when the component did not have focus. If the component already has focus on one point, and you start dragging the other point over the first point, you are pushing away both points.

### Reproduction Link
<a href="https://codepen.io/Karatekiddo/pen/YzqVbyE" target="_blank">https://codepen.io/Karatekiddo/pen/YzqVbyE</a>

### Other comments
If you click outside the component, between dragging the different points, it always works. But if the component still has focus, it only works on the first point.

![GIF animation example](https://media.giphy.com/media/mBYrn9UYXvzfBlyzS9/giphy.gif)

**Comment by KaelWD** [comment]
Fixed in v2.4.1
