### ISSUE TITLE
[Bug Report] Overriding sass variable for data table fails silently

### ISSUE THREAD

**Issue by ElSamhaa** [vuetifyjs/vuetify#12146]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.125
**OS:** Linux

### Steps to reproduce
Overriding component sass variable in a vuejs single-file component, following documentation instructions.

### Expected Behavior
for the table rows to resize its height

### Actual Behavior
data table rows are not affected

### Reproduction Link
<a href="https://github.com/ElSamhaa/vuetify-datatable-reproduction.git" target="_blank">https://github.com/ElSamhaa/vuetify-datatable-reproduction.git</a>

**Comment by nekosaur** [comment]
The repository that you've linked to does not use v-data-table or even vuetify.

**Comment by ElSamhaa** [comment]
> The repository that you've linked to does not use v-data-table or even vuetify.

I'll recheck and confirm back

**Comment by ElSamhaa** [comment]
The minification changes got deleted while pushing to the temple GitHub repo.

Will have to reupload tonight, as soon as I get access to my laptop again.

**Comment by ElSamhaa** [comment]
@nekosaur There, I've forgotten to commit the minimized version. you can check it now

**Comment by KaelWD** [comment]
You can't just set variables anywhere and have it work, they need to be injected with sass-loader: https://vuetifyjs.com/en/customization/sass-variables/#vue-cli-install

**Comment by ElSamhaa** [comment]
I'm using vue-cli, and the documentation says that the configurations are set automatically in my case.

And I'm confused, when I don't want to have a dedicated variables file, and just put everything in their respective single file components, the docs seems to support my use case and mentions it, however if I do need to have further configs set, shouldn't the docs be more explicit about it?!

So, I think you should document the case where vue-cli is used with single-file-component variables, like what is the minimum config needed for it to work?

**Comment by ElSamhaa** [comment]
> You can't just set variables anywhere and have it work, they need to be injected with sass-loader: https://vuetifyjs.com/en/customization/sass-variables/#vue-cli-install

Would you pls suggest what changes need to be added? I can't seem to find my way in the docs to make it work.

**Comment by KaelWD** [comment]
> create a folder called `sass`, `scss` or `styles` in your `src` directory with a file named `variables.scss` or `variables.sass`

**Comment by ElSamhaa** [comment]
> > create a folder called `sass`, `scss` or `styles` in your src directory with a file named `variables.scss` or `variables.sass`

Yes, I don't want to centralize my variables declarations in one single variables file. And again, the docs seems to support my use case, under the permalink for declaring variables in single file components.

**Comment by nekosaur** [comment]
You can use them, not declare them.

**Comment by ElSamhaa** [comment]
> You can use them, not declare them.

I meant overrding them. Not sure what did you understand tbh.
