### ISSUE TITLE
[Bug Report] Cannot set color prop with HEX color combined with darken or lighten variants 

### ISSUE THREAD

**Issue by fkutsukos** [vuetifyjs/vuetify#12153]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.6

### Steps to reproduce
Use any HEX color code inside the color prop of a vuetify element along with a darken or lighten variant

### Expected Behavior
The element should be colored according to the darken or lighten variant of the HEX color.
<v-chip color="#3062AA lighten-2">
</v-chip>
Instead if we set the "primary" color of the theme equal to #3062AA  and then we reference "primary" inside the color prop there is no problem, example
<v-chip color="primary lighten-2">
</v-chip>

### Actual Behavior
the element remains colorless

### Reproduction Link
<a href="https://codepen.io/fotis_kutsukos/pen/abNyJMo" target="_blank">https://codepen.io/fotis_kutsukos/pen/abNyJMo</a>

**Comment by nekosaur** [comment]
Using HEX value and variant name together is not supported.
