### ISSUE TITLE
[Bug Report] Readonly combobox input deletes selections when backspace or delete is pressed

### ISSUE THREAD

**Issue by David10Gabriel** [vuetifyjs/vuetify#12156]
### Environment
**Vuetify Version:** 1.5.24
**Last working version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Linux x86_64

### Steps to reproduce
1 - Open the codepen URL or the [Vuetify's combobox docs](https://v15.vuetifyjs.com/en/components/combobox/);
2 - Click at the readonly combobox;
3 - Press backspace or delete twice;

### Expected Behavior
No action, since the combobox is set as readonly;

### Actual Behavior
The selections are deleted

### Reproduction Link
<a href="https://codepen.io/david10gabriel/pen/zYqdRjq" target="_blank">https://codepen.io/david10gabriel/pen/zYqdRjq</a>

### Other comments
The newer 2.x.x versions work nicely, at least on Vuetify website.

**Comment by lioneaglesolutions** [comment]
Closing as this has been resolved in V3
