### ISSUE TITLE
[Feature Request] V-treeview open-all not work, only show top parents without any children, need click any children to show

### ISSUE THREAD

**Issue by martinym28** [vuetifyjs/vuetify#12151]
### Problem to solve
https://vuetifyjs.com/en/components/treeview/#open-all
here is same issue but fix it with to flatten all the items out into an array listing all parents and children at the same level.
https://forum.vuejs.org/t/v-treeview-using-open-all-not-showing-child-nodes-only-parent/88534

### Proposed solution
There are data from SQL as sample as below, but why did not work on V-treeview open-all, need click any children to show anytime :
Vuetify: 2.3.3
Vue: 2.6.11
Browsers: Chrome 85.0.4183.83
OS: Windows 10
------------------- get data at client
axios
        .get('./postcategory',{})
        .then(response => (this.categores = response.data))

------------------- data list from Controller of server
[{"id":1,"parent_id":null,"name":"Aqxcg7JMbb","posts":5,"children":[{"id":5,"parent_id":1,"name":"qcItYDgWgr","posts":5,"children":[]}]},{"id":2,"parent_id":null,"name":"PTmb9J9P8t","posts":5,"children":[{"id":6,"parent_id":2,"name":"MMPs8t0s0t","posts":5,"children":[{"id":7,"parent_id":6,"name":"fS3CDUyndf","posts":5,"children":[]},{"id":8,"parent_id":6,"name":"Kss64IxisV","posts":5,"children":[{"id":9,"parent_id":8,"name":"mlAxuVqCTi","posts":5,"children":[]}]}]}]},{"id":3,"parent_id":null,"name":"AUeggZsx1M","posts":5,"children":[]},{"id":4,"parent_id":null,"name":"89Uv6xaaS8","posts":5,"children":[{"id":10,"parent_id":4,"name":"Z4j9p4JIF4","posts":5,"children":[]}]}]

--------------------

**Comment by nekosaur** [comment]
This seems more like a bug report than a feature request? Please provide a codepen reproduction within 48 hours or this issue will be closed.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
