### ISSUE TITLE
[Bug Report] V-dialog doesn't show up

### ISSUE THREAD

**Issue by Deresium** [vuetifyjs/vuetify#12152]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
Create a typescript vue project with Vue CLI 3.
Add Vuetify
Create a new Class Based Component with the same behavior from the codepen.
Or clone the repository.
Click on the button will not show up the dialog.
It is similar to https://github.com/vuetifyjs/vuetify/issues/9175

### Expected Behavior
When I click on the button, the dialog shows up.

### Actual Behavior
When I click on the button, the dialog stay hidden.

### Reproduction Link
<a href="https://codepen.io/deresium/pen/wvGqzjr" target="_blank">https://codepen.io/deresium/pen/wvGqzjr</a>
<a href="https://github.com/Deresium/vueissuedialog">https://github.com/Deresium/vueissuedialog</a>

### Other comments
It works fine in the codepen example but not in my class based component.
I don't have errors in my console and when I try to use a v-btn in my component, it works as expected (props and events).

**Comment by jacekkarczmarczyk** [comment]
Please create a codesandbox or github repo with reproduction

**Comment by Deresium** [comment]
I create a quick repository with the issue and I edited the bug report

**Comment by Deresium** [comment]
Oh it looks like I used
`<vue id="app">`
and I have to use
`<v-app>`
to make it works.
I suppose there are some mechanisms between the giant slot of v-app and the v-dialog.
Sorry for the issue nvm.
Have a nice day!
