### ISSUE TITLE
[Bug Report] Cannot read property 'lang' of undefined"  found in  <VAutocomplete>

### ISSUE THREAD

**Issue by wocodes** [vuetifyjs/vuetify#12154]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.3

### Steps to reproduce
Create a new component with the js code in codepen and navigate to the Vue file.

### Expected Behavior
Should display Vuetify Autocomplete Select component...

### Actual Behavior
This is used in an AngularJs 1.x app and is a component. Vue and Vuetify were installed via npm, on instantiation, it produces the error below. 

Error in render: "TypeError: Cannot read property 'lang' of undefined"

found in

---> <VAutocomplete>
       <HmoSelectComponent>
         <TariffsComponent>
           <Root>

### Reproduction Link
<a href="https://codepen.io/williamodiomonafe/pen/ExKvmMZ" target="_blank">https://codepen.io/williamodiomonafe/pen/ExKvmMZ</a>

**Comment by jacekkarczmarczyk** [comment]
Please create a minimal runnable reproduction (can be codesandbox or github repo)

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
