### ISSUE TITLE
[Documentation] Medium icon not updating, same size as the small icon

### ISSUE THREAD

**Issue by pushu0** [vuetifyjs/vuetify#12168]
### Environment

**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
On the usage section. Select size as medium, then select small.

### Expected Behavior
The size of the medium icon should be 28px and the small icon 16px

### Actual Behavior
Both medium and small icon sizes are 16px

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/icons/#usage" target="_blank">https://vuetifyjs.com/en/components/icons/#usage</a>

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/76680713c5709d139339718799506df341b320e6
