### ISSUE TITLE
[Bug Report] Selected items in v-data-table are not updated if items of the table are reloaded

### ISSUE THREAD

**Issue by MilenaMalysh** [vuetifyjs/vuetify#12162]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 10

### Steps to reproduce
1) Select all the rows in the table
2) Check data in the selected array shown below
3) Click on the "reload items" button
4) Again check the selected array shown below

### Expected Behavior
Selected items array:
 {name: 'Frozen Yogurt', calories: 2},
 {name: 'Other',calories: 2}

### Actual Behavior
Selected items array:
 {name: 'Frozen Yogurt', calories: 0},
 {name: 'Other',calories: 0}

### Reproduction Link
<a href="https://jsfiddle.net/MilenaMalysh/uzhst0j5/26/" target="_blank">https://jsfiddle.net/MilenaMalysh/uzhst0j5/26/</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
