### ISSUE TITLE
[Bug Report] Slow rendering of v-menu items

### ISSUE THREAD

**Issue by AliasIO** [vuetifyjs/vuetify#12161]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Firefox 80.0
**OS:** Mac OS 10.16

### Steps to reproduce
As can be seen on https://www.wappalyzer.com, it takes several seconds for the main menu (top-right) to appear when loading the website from a cold cache. I'm using the `eager` option on the `v-menu` but content inside the `activator` slot is initially hidden and doesn't show until moments later. The rest of the component shows immediately as expected. The website is a static build so the items are already in the DOM.

I'm not seeing anything that might be blocking it. I'd like to understand how I can prevent the delay and have the menu display immediately upon loading the page.

https://github.com/AliasIO/wappalyzer.com/blob/master/components/Header.vue#L15

### Expected Behavior
The top-level menu items should display immediately upon loading the page.

### Actual Behavior
There is a delay of several seconds for the menu to appear, even though the rest of the page is already visible.

### Reproduction Link
<a href="https://github.com/AliasIO/wappalyzer.com" target="_blank">https://github.com/AliasIO/wappalyzer.com</a>

**Comment by KaelWD** [comment]
#9163

**Comment by AliasIO** [comment]
@KaelWD Thanks for the pointer. I don't really understand why but adding an empty `attach` attribute removes the delay. However, it also change the text direction to RTL for some reason, which I had to fix by adding a class `text-left`.

<img width="479" alt="Screen Shot 2020-09-03 at 9 53 16 am" src="https://user-images.githubusercontent.com/77259/92048575-5cd79e00-edcb-11ea-89ed-3dbd99be4e78.png">
