### ISSUE TITLE
[Bug Report] Too little space between v-card-title and v-card-subtitle when inside v-dialog

### ISSUE THREAD

**Issue by pascalmtts** [vuetifyjs/vuetify#12170]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Mac OS 10.15.6

### Steps to reproduce
Create a v-card in a v-dialog component and add a v-card-title and a v-card-subtitle. There is less space then creating a v-card outside of a v-dialog.

### Expected Behavior
Should be the same space when inside v-dialog

### Actual Behavior
Less space when inside v-dialog

### Reproduction Link
<a href="https://codepen.io/pascalmtts/pen/vYGWEBb" target="_blank">https://codepen.io/pascalmtts/pen/vYGWEBb</a>

**Comment by KaelWD** [comment]
@johnleider Where did the 10px bottom padding come from? I can't find it in either version of the dialog specs.

**Comment by johnleider** [comment]
Dialog's have a different title styling based upon its MD spec:

**v2:** https://material.io/components/dialogs#specs
**v1:** https://material.io/archive/guidelines/components/dialogs.html#dialogs-specs

The card elements are our primary way of portraying those styles and we specifically target the `v-card-title` component. This change causes the `v-card-subtitle` to be closer.

**Comment by KaelWD** [comment]
There's no examples on that page with a subtitle, and the title spacing looks like it should be *larger* in dialogs if anything.

**Comment by KareemDa** [comment]
Any update? Can I simply make the padding in the dialog: `16px 24px` instead of  `16px 24px 10px`

**Comment by johnleider** [comment]
It was done by either spec or what I could assume. It's also very possible that when dialog was made, there were no specific values in pixels.

**Comment by MartinX3** [comment]
As a workaround I use `<v-card-text style="padding: 16px">` with vuetify 2.6.12.
