### ISSUE TITLE
[Bug Report] VAutocomplete undefined error on blur 

### ISSUE THREAD

**Issue by anzuj** [vuetifyjs/vuetify#12178]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.5.22
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
Go to the reproduction link on Codepen
Show console
Select something from dropdown
Click on whitespace

### Expected Behavior
No errors in console

### Actual Behavior
Error appears on console:
`[Vue warn]: Error in callback for watcher 'isFocused': 'TypeError: Cannot read property 'firstName' of undefined' found in ---> <VAutocomplete>`

### Reproduction Link
https://codepen.io/jkarczm/pen/eYZeKLo?editors=1010

**Comment by YipingRuan** [comment]
On loading the page, saw:
![image](https://user-images.githubusercontent.com/5492274/93694860-6428d680-fb43-11ea-8660-8f700f50cb3b.png)
