### ISSUE TITLE
[Bug Report] v-main wrong height on Safari on iPadOS

### ISSUE THREAD

**Issue by zeyugao** [vuetifyjs/vuetify#12171]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
**The reprodce link is not my indent, use the pre-made layout is enough**

On Safari on iPadOS open [https://vuetifyjs.com/en/examples/layouts/centered/](https://vuetifyjs.com/en/examples/layouts/centered/)

It seems that [this issue](https://github.com/vuetifyjs/vuetify/issues/2901) is also related. But it is closed due to unreproduceable

I am highlighting the following element

![highlight.png](https://i.loli.net/2020/09/03/1demkSiLUCqIN4j.png)

The screenshot from remote debugger for safari

![image.png](https://i.loli.net/2020/09/03/eZ1EuYaSFjN7TtJ.png)

![image.png](https://i.loli.net/2020/09/03/QBkCYJE2KXD5pOv.png)

![image.png](https://i.loli.net/2020/09/03/36LiRvXPZoT1Qm2.png)

All of the pre-made layout are having this problem, including those without a AppBar.

### Expected Behavior
The content should not be able to scroll

### Actual Behavior
It can scroll a little

### Reproduction Link
<a href="https://jsfiddle.net/o6g51vrs/" target="_blank">https://jsfiddle.net/o6g51vrs/</a>

**Comment by SystemKeeper** [comment]
Seeing the same on iOS 14

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
