### ISSUE TITLE
[Bug Report] Tooltip with Menu on Touch Device

### ISSUE THREAD

**Issue by Yihao-G** [vuetifyjs/vuetify#12175]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
1. Turn on Chrome DevTool
2. Toggle Device Toolbar to simulate a touch device
3. Go to the reproduction link or refresh the reproduction link (important, otherwise not reproducible)
4. Click the button
5. Tooltip and menu show at the same time

### Expected Behavior
Only the menu should show

### Actual Behavior
Both tooltip and menu show on top of each other

### Reproduction Link
<a href="https://codepen.io/gaosong2101/pen/QWNOOow" target="_blank">https://codepen.io/gaosong2101/pen/QWNOOow</a>

### Other comments
similar behaviour can be also observed at https://vuetifyjs.com/en/components/menus/#menu-with-activator-and-tooltip

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/jkarczm/pen/NWNwXKP

**Comment by Yihao-G** [comment]
Thank you for the workaround. 

Just wondering, is this going to be fixed on the vuetify side, or we have to use this workaround for all these cases where tooltip and menu are used together?

**Comment by jacekkarczmarczyk** [comment]
It might be fixed in Vuetify but hard to say when, I suppose you may need to wait for 3.x
For now I suggest creating a wrapper component for menu+tooltip

**Comment by wallcrosstype** [comment]
from my finding
it was fine up to 2.1.2

contain this problem but subtle because tooltip z-index is behind
from 2.1.3 to 2.2.8

contain this problem and it damn obvious because tooltip come to front
from 2.2.9 to 2.3.10
