### ISSUE TITLE
[Documentation] Outdated v-content instead of v-main on the screen

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12189]
### Environment

**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
1. Go to https://vuetifyjs.com/en/components/application/
2. As you can see on this screenshot there is still `v-content` component which was renamed to `v-main` in Vuetify 2.3.0

![image](https://user-images.githubusercontent.com/17653648/92336046-e07bde00-f09c-11ea-8638-ae6f3ee94d57.png)

### Expected Behavior
On the screenshot there should be a `v-main` component instead of `v-content`

### Actual Behavior
On the screenshot there is still a `v-content` component which was renamed to `v-main` in Vuetify 2.3.0

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/application/" target="_blank">https://vuetifyjs.com/en/components/application/</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #11663
