### ISSUE TITLE
[Documentation] Flexbox documentation space-between and space-around missing "space-"

### ISSUE THREAD

**Issue by jblachly** [vuetifyjs/vuetify#12187]
### Environment

**Browsers:** Firefox 80.0
**OS:** Mac OS 10.14

### Steps to reproduce
Text reads:

"""
The justify-content flex setting can be changed using the flex justify classes. This by default will modify the flexbox items on the x-axis but is reversed when using flex-direction: column, modifying the y-axis. Choose from start (browser default), end, center, between, or around.
"""

However, `justify-between` and `justify-around` do not work. Inspecting the example's source code, we see that it must instead be `justify-space-{between,around}`

### Expected Behavior
Flex should work as depicted in the example

### Actual Behavior
Using `justify-{between,around}` does nothing.

### Reproduction Link
<a href="https://vuetifyjs.com/en/styles/flex/#flex-justify" target="_blank">https://vuetifyjs.com/en/styles/flex/#flex-justify</a>

**Comment by jblachly** [comment]
@ElijahKotyluk the documentation still reads with the incorrect text and I didn't see a PR?


The justify-content flex setting can be changed using the flex justify classes. This by default will modify the flexbox items on the x-axis but is reversed when using flex-direction: column, modifying the y-axis. Choose from start (browser default), end, center, **between**, or **around**.
(emphasis mine)

**Comment by ElijahKotyluk** [comment]
@jblachly I have pushed up a commit fixing the text to our docs PR.

**Comment by jblachly** [comment]
Thanks, sorry I missed it 👍

**Comment by ElijahKotyluk** [comment]
No problem at all, thank you for letting us know of this issue.

**Comment by MajesticPotatoe** [comment]
f1db86f
