### ISSUE TITLE
Text fields change event called twice

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#1218]
### Steps to reproduce
Use change event on v-text-field

### Versions
Vue @latest
Vuetify @v0.14.7
Chrome 60.0.3112.78

### What is expected ?
Change event fired once.

### Reproduction Link
https://codepen.io/anon/pen/EvgxMj

**Comment by johnleider** [comment]
Viewing the result like this is deceptive. If you use Vue devtools you can see change is only called once. The other event happens whenever you blur.

**Comment by jacekkarczmarczyk** [comment]
@johnleider so you are saying that triggering "change" event on blur is not a bug?

See the codepen https://codepen.io/anon/pen/vJyBdP - IMHO "change" should be triggered only when the value has changed as it is done in native inputs

**Comment by johnleider** [comment]
Thank you for a better reproduction.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/1251

**Comment by ArturoGasca** [comment]
You can try with @change.native="handler".
