### ISSUE TITLE
[Bug Report] Color Picker breaks once you select transparent color

### ISSUE THREAD

**Issue by marinaglancy** [vuetifyjs/vuetify#12183]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.6

### Steps to reproduce
- Go to Model example in the Vuetify documentation https://vuetifyjs.com/en/components/color-pickers/#color-pickers
- Choose RGBA
- Slide "alpha" control all the way to the left (in order to set a transparent color)

### Expected Behavior
You can set a transparent color (with property "a" equals to 0). You can continue to use color picker after that

### Actual Behavior
- the "a" property disappears from the return, 
- the alpha bar disappears, 
- there is no way to bring "alpha" control back whatever you do, even when you switch to hsla and back. Only page refresh fixes it

**Comment by lmindwarel** [comment]
Same issue here

**Comment by marinaglancy** [comment]
@ElijahKotyluk why was it tagged as documentation? It is not a problem with documentation, I used documentation page as an example of reproduction instructions, it can be reproduced everywhere

**Comment by mcipenuks** [comment]
Also have this issue. Alpha should not dissapear from RGBA object once it's value is 0

**Comment by MentalGear** [comment]
Same issue here. Even when chosing mode: 'hsla', the alpha control is gone if alpha = 1.
