### ISSUE TITLE
Laravel and Vuetify Configruration

### ISSUE THREAD

**Issue by MustafaHussaini** [vuetifyjs/vuetify#1219]
I am trying to use laravel 5.4,
 vue and vuetify. It works well with vue but when I am adding vuetify, it outputs  errors  
[Vue warn]: Unknown custom element: <v-toolbar-logo> - did you register the component correctly?
Any Idea or starter project for laravel configuration.
below is my code.

[code.txt](https://github.com/vuetifyjs/vuetify/files/1194428/code.txt)

**Comment by MustafaHussaini** [comment]
I am trying to use vuetify with laravel 5.4. But I don't know how should I configure my project.
Any idear or starter project.
I have seen #1146 vuetified project. it is using laravel 5.5 and php 7  but I am using laravel 5.4 and php 5.6.2..

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
