### ISSUE TITLE
[Bug Report] Datatables keep selected items selected after items array is updated.

### ISSUE THREAD

**Issue by PrimalMinister** [vuetifyjs/vuetify#12190]
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.11
**Browsers:** Firefox 80.0
**OS:** Windows 10

### Steps to reproduce
select all items, they are listed below the datatable. filter items, selected items dont update.

### Expected Behavior
After updating items, selected items should only have filtered items.

### Actual Behavior
selected items still selected.

### Reproduction Link
<a href="https://codepen.io/PrimalMinister/pen/JjXMZmP" target="_blank">https://codepen.io/PrimalMinister/pen/JjXMZmP</a>

**Comment by SergeyKhval** [comment]
This can be easily [fixed in userland](https://codepen.io/transGLUKator/pen/QWNPayZ). 

From your example what do you expect to happen with filtered out items? Should they be deselected, so that when you clear your filter input the data table will list those item with checkboxes unchecked?

**Comment by jacekkarczmarczyk** [comment]
Filtered items are still selected, they are just not displayed
