### ISSUE TITLE
[Feature Request] I hope that the v-data-table can monitor scroll axis events after a fixed height

### ISSUE THREAD

**Issue by cloudsnet** [vuetifyjs/vuetify#12196]
### Problem to solve
It is recommended that when the v-data-table is set to a fixed height, when the scroll axis appears on the table, you can set to monitor the scroll axis events, and you can perform other operations when the scroll is completed to the bottom.

### Proposed solution
You can set a fixed ID for the scrolling area and use the v-scroll command. At present, setting the ID for the v-data-table is invalid. Maybe I did not find a way; or other better solutions

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
