### ISSUE TITLE
[Documentation] When clicking on a codepen button i'm redirected to codepen and logged out.

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#12199]
### Environment

**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
Click on the codepen button
I'm logged out of codepen.
Now go to https://codepen.io/login and login and try it again, i'm logged out again..

### Expected Behavior
Not loggin off automatically

### Actual Behavior
I'm getting logged out

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/floating-action-buttons/#fab-with-speed-dial" target="_blank">https://vuetifyjs.com/en/components/floating-action-buttons/#fab-with-speed-dial</a>

### Other comments
I'm not sure if vuetify does something wrong or if this is a codepen issue..
![weird](https://user-images.githubusercontent.com/1246691/92594587-476ae400-f2a3-11ea-8ac5-e388b8228531.gif)

**Comment by KaelWD** [comment]
Must be a codepen bug, we just use [prefill](https://blog.codepen.io/documentation/prefill/). I've reported it to codepen support.
