### ISSUE TITLE
some problem about Pagination compenent

### ISSUE THREAD

**Issue by xchz** [vuetifyjs/vuetify#122]
[Pagination ](https://vuetifyjs.com/components/pagination)

i can consider two ways to handle pagination change:
one:
```
<template>
  <v-pagination :length="5" v-model="currentPage"></v-pagination>
</template>

<script>
export default {
        computed: {
            currentPage: {
                get: function () {
                    return this.currentPageIndex
                },
                set: function (val) {
                    this.currentPageIndex = val
                   // get next page data...
                }
            }
        },
       data () {
        currentPageIndex: 1
       }
</script>
```

two:
use vue [Watchers](https://vuejs.org/v2/guide/computed.html#Watchers).
when currentPageIndex change get next page data.

```
<template>
  <v-pagination :length="5" v-model="currentPageIndex"></v-pagination>
</template>

<script>
export default {
watch: {
    currentPageIndex: function (newIndex) {
      this.currentPageIndex = newIndex
      // get next page data...
    }
  },
       data () {
        currentPageIndex: 1
       }
</script>
```

which is the best way to do that?
thx.

**Comment by johnleider** [comment]
Either way is fine, it is really up to you on the method you would use to achieve it. This is, however, not an issue. If you would like some additional help, please ask your questions in the Vuetify gitter.

**Comment by xchz** [comment]
sorry…thanks for your reply. I will use the 
gitter next time.
