### ISSUE TITLE
[Bug Report] Using Vuetify SASS variables doubles the compilation time

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12202]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
1. Create new Vue project using Vue CLI. Pick `dart-sass` as a CSS preprocessor.
2. Add Vuetify with `vue add vuetify`.
3. Run `npm run serve` to launch the project. Do it multiple times and check the compilation times -> in my case the compilation times were about 23 - 30s
4. Add `src/scss/variables.scss` file to the project with the following content:
```scss
$font-size-root: 15px;
```
4. Run again `npm run serve`. Repeat this multiple times and check the compilation times. In my case, the compilation times were about 60  -62s.

As you can see, the compilation time increases twice  when using Vuetify SASS variables. I think this a serious issue with Vuetify performance.

### Expected Behavior
The compilation time should not increase drastically when using Vuetify SASS variables.

### Actual Behavior
The compilation time increases twice when using Vuetify SASS variables.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/yLOKewJ" target="_blank">https://codepen.io/mikilll94/pen/yLOKewJ</a>

**Comment by MajesticPotatoe** [comment]
duplicate #11901

**Comment by Mikilll94** [comment]
@MajesticPotatoe @KaelWD 
Thanks.

However, now I wonder:
1. Why `import Vuetify from 'vuetify/lib/framework` is not in the startup Vuetify project created using vue-cli-plugin-vuetify?
2. Why this important information about compiling SASS in on the "Presets" page in docs? This should be i.e. on the "SASS variables" page. Right now most developers are probably unaware that they can speed up their compilation time.

**Comment by MajesticPotatoe** [comment]
<https://vuetifyjs.com/en/customization/sass-variables/#caveats>
