### ISSUE TITLE
[Feature Request] Add custom collapse icon for v-expansion-panel

### ISSUE THREAD

**Issue by jcjp** [vuetifyjs/vuetify#12204]
### Problem to solve
This will enable the developer to use their own icon when expansion panel is collapsed and expanded. For example in collapsed mode we would provide mdi-chevron-left icon and for expand mode it's mdi-chevron-right. Add a collapsed-icon in props for v-expansion-panel just like expand-icon to enable custom icon for both action

### Proposed solution
Temporarily I use this:
1. Use v-slot:actions and set the v-icon to mdi-chevron-up 
2. Use this sass:
```
::v-deep {
    .v-expansion-panel-header__icon {
      &:not(.v-expansion-panel-header__icon--disable-rotate) {
        .v-icon {
          transform: rotate(90deg);
        }
      }
    }
  }
```

**Comment by johnleider** [comment]
This is currently possible in userland using the **expand-icon** property on `v-expansion-panel-header`. I do grab for the specific functionality that you're asking for but as of this time do not have an intention to implement to individual components.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
