### ISSUE TITLE
[Bug Report] Type error: Cannot find name 'Dictionary' in helpers.ts

### ISSUE THREAD

**Issue by thSoft** [vuetifyjs/vuetify#12201]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Firefox 80.0
**OS:** Mac OS 10.15

### Steps to reproduce
* `import {getObjectValueByPath} from 'vuetify/src/util/helpers';`
* Typecheck the code with tslint

### Expected Behavior
There should be no type errors

### Actual Behavior
The following type errors are found:

```
ERROR in node_modules/vuetify/src/util/helpers.ts(438,11):
438:11 Cannot find name 'Dictionary'.
    436 | 
    437 | export function mergeDeep (
  > 438 |   source: Dictionary<any> = {},
        |           ^
    439 |   target: Dictionary<any> = {}
    440 | ) {
    441 |   for (const key in target) {
ERROR in node_modules/vuetify/src/util/helpers.ts(439,11):
439:11 Cannot find name 'Dictionary'.
    437 | export function mergeDeep (
    438 |   source: Dictionary<any> = {},
  > 439 |   target: Dictionary<any> = {}
        |           ^
    440 | ) {
    441 |   for (const key in target) {
    442 |     const sourceProperty = source[key]

```

### Reproduction Link
<a href="https://codesandbox.io/s/sweet-ellis-bmktr?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/sweet-ellis-bmktr?file=/src/components/HelloWorld.vue</a>

### Other comments
Indeed, the type Dictionary is not imported in vuetify/src/util/helpers.ts.

**Comment by nekosaur** [comment]
You should not be importing from `vuetify/src`. If you must use this internal function, then import from `vuetify/es5` instead.

**Comment by mikeartix** [comment]
@nekosaur How do I get this to work in typescript though?

![image](https://user-images.githubusercontent.com/81088215/130605029-4857d206-496e-4f31-aa2f-19395b283fd4.png)

I tried declaring the module in vue.d.ts but it doesn't seem to work, maybe I'm missing something? Many thanks.
