### ISSUE TITLE
[Feature Request] Datepicker: Change portuguese locale text format in header  

### ISSUE THREAD

**Issue by madsongr** [vuetifyjs/vuetify#12207]
### Problem to solve
It should be similar to English format (Thu, Sep 10). The way it is it's not quite elegant.

### Proposed solution
The way it is today: "qui., 10 de set.". This is not a good approach. It could be "Qui, Set 10" or "Quinta, Set 10". 

I could not find where to change it.

**Comment by KaelWD** [comment]
This sounds like a bug report, not a feature request. Please open a new issue with the relevant information. 

If you're talking about v-date-picker we just use [`toLocaleDateString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), if it's translated wrong that's probably the browser's fault.
