### ISSUE TITLE
[Bug Report] Grid systems on xs doesn't work properly

### ISSUE THREAD

**Issue by valleen** [vuetifyjs/vuetify#12209]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
using xs="12" on v-col doesn't work as expected

### Expected Behavior
2 cards on top of each other

### Actual Behavior
screen is split in half with the 2 cards

### Reproduction Link
<a href="https://codepen.io/nycoss/pen/LYNmVOJ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fgrids%2F" target="_blank">https://codepen.io/nycoss/pen/LYNmVOJ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fgrids%2F</a>

**Comment by jacekkarczmarczyk** [comment]
> Expected Behavior
> 2 cards on top of each other

![image](https://user-images.githubusercontent.com/15625235/92901572-dfdaa300-f420-11ea-92f3-d387082727fe.png)

Also there's no `xs` prop

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
