### ISSUE TITLE
[Bug Report] Floating action button inside treeview has a weird z-index

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#12200]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
Create a speed-dial in a treeview and open it.

### Expected Behavior
Buttons inside the speed-dial should appear above the activator

### Actual Behavior
Buttons inside the speed-dial appear below the activator

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/WNwMBJj" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/WNwMBJj</a>

### Other comments
I've also posted a question on stackoverflow because i think it's really weird i can't create a dirty fix with the z-index but i'm guessing there's also something wrong with vuetify..
https://stackoverflow.com/questions/63809820/z-index-ignored-by-browser-when-not-inline-and-again-ignored-when-inline-and-no

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
