### ISSUE TITLE
[Bug Report] VMenu with VTooltip open-on-hover inconsistency

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12208]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 7

### Steps to reproduce
Tooltip defaults to open-on-hover and I've set open-on-hover on the menu.
Mouse over button

### Expected Behavior
Menu opens and tooltip displays.

### Actual Behavior
Menu opens, tooltip does not.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/gOreQvW" target="_blank">https://codepen.io/teellcory/pen/gOreQvW</a>

### Other comments
The tooltip now only opens on click and explicitly stating open-on-hover doesn't resolve it.

**Comment by nekosaur** [comment]
This happens because the `on` object for both v-menu and v-tooltip contains mouseenter and mouseleave properties, and one overwrites the other then you just spread both of them. You will have to combine them such that both are called. https://codepen.io/nekosaur/pen/RwaXJpL

**Comment by KaelWD** [comment]
https://github.com/vuejs/vue/issues/9718

You can merge them to an array instead of a function: 
```
mouseenter: [menu.mouseenter, tooltip.mouseenter],
mouseleave: [menu.mouseleave, tooltip.mouseleave]
```
