### ISSUE TITLE
Data tables tr access

### ISSUE THREAD

**Issue by robodude** [vuetifyjs/vuetify#1220]
I would like to have access to the tr elements from inside the items slot.

or maybe the `<template slot="items" scope="props">`
could serve as the tr so I could do something like
`<template slot="items" scope="props" :class="props.item.className">`

  - What will it allow you to do that you can't do today?
It will allow me to access properties of the tr from within the context of the item. My most common use case is adding classes to the row based on some items properties.

  - How will it make current work-arounds straightforward?
My current workaround either creating a new column to represent the property or applying a class to each td.

  - What potential bugs and edge cases does it help to avoid?

**Comment by nekosaur** [comment]
You do have access to the `<tr>` tag. See docs example 2

**Comment by robodude** [comment]
Doesn't that force me to re-create the default sorting logic/behavior and styling? Having to re-create all the 'default' behavior just to toss a property on the tr seems like a bit much. :(
