### ISSUE TITLE
[Feature Request] V-Select add prop to limit number of selected items

### ISSUE THREAD

**Issue by randanunn** [vuetifyjs/vuetify#12213]
### Problem to solve
Ability to limit users to only select 'x' number of items in dropdown

### Proposed solution
`:max-selection="10"`

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by HGGshiwo** [comment]
Try to use this: (a is your model-value, assume limit to 2)
```html
<v-select multiple :model-value="a" @update:modelValue="(e) => { (e.length > 2) && e.shift(); a = e }"> </v-select>
```
