### ISSUE TITLE
Decouple text-input counter's min/max props from validation rules

### ISSUE THREAD

**Issue by ChavaSobreyra** [vuetifyjs/vuetify#1221]
Previously discussed this change with @nekosaur. Creating this issue for reference since we moved away from Gitter and the conversation will likely be lost in the ether. 

### Summary
The problem is that min and max aren't used *only* for validation -- they are also used to display a min/max for the `counter`. A user cannot use a text-input with a counter and a visible min/max value (0/8), without opting-in to vuetify's validation logic. 

### How it works today
If you define a text-field with a counter and minimum of 8 characters, the field starts in a red error state.

### Desired behavior
If you define a text-field with a counter and minimum of 8 characters, the field should not start in a red error state.  

### Solution
Min/max props for the counter could be split off into something like  `counter-min` `counter-max`

**Comment by nekosaur** [comment]
This has been added in dev.
