### ISSUE TITLE
[Feature Request] Mandatory Prop for v-select

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#12219]
### Problem to solve
`v-select` lacks the automated flexibility a `v-radio-group` when it comes to automatically selecting the first item if its value is `null`.

### Proposed solution
Add the same or similar functionality via a `mandatory` prop to `v-select`.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
