### ISSUE TITLE
[Bug Report] Failed to resolve directive: ripple

### ISSUE THREAD

**Issue by canassa** [vuetifyjs/vuetify#12224]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6

### Steps to reproduce
- Use a v-data-table with the "show-select" enabled

### Expected Behavior
No errors should be displayed

### Actual Behavior
Vue displays a warning:

vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to resolve directive: ripple

### Reproduction Link
<a href="https://gist.github.com/canassa/0688187cc157bd20d4a8c967c1157479" target="_blank">https://gist.github.com/canassa/0688187cc157bd20d4a8c967c1157479</a>

**Comment by maxkobzev** [comment]
The same issue. It comes from v-simple-checkbox, adding `v-ripple` or `:ripple="false"` to the v-simple-checkbox component solves these warning. But with manual addition of `v-ripple` it looks odd.

**Comment by jacekkarczmarczyk** [comment]
workaround:

```js
// main.js
import Ripple from 'vuetify/lib/directives/ripple';
Vue.use(Vuetify, {
  directives: {
    Ripple,
  },
});
```

**Comment by ferm10n** [comment]
Potentially related: I had the same error, but it wasn't on a v-data-table. It happened because I was trying to use it in a functional component

**Comment by chrmorqmatic** [comment]
jacekkarczmarczyk workaround on main.js didn't work for me, `:ripple="false"` on v-simple-checkbox worked

**Comment by webcoderkz** [comment]
Is it going to be fixed?

**Comment by Ced-Sharp** [comment]
I created a derivative of v-data-table which makes use of "vuedraggable" (SortableJS).
Since I needed to use the "body" slot, I had to manually add the v-simple-checkbox.
As per @chrmorqmatic post above, `:ripple="false"` is what made it work for me.

If I use v-checkbox instead, I don't have that issue (but then styling is utterly broken).
Maybe this is an actual bug ?

**Comment by reynard80** [comment]
I'm also getting the ripple warning when using `v-simple-checkbox` in my `v-data-table`. The ripple is shown though.

Setting `:ripple="false"` works, but then no ripple is shown, making it inconsistent with other checkboxes. I'd rather not disable all checkbox ripples. After all, it's part of the material design.

Will this be fixed?

**Comment by Chickenbreadlp** [comment]
`:ripple=false` didn't seem to fix it in my case (maybe the checkbox being `disabled` still causes the issue?) and adding the `main.ts` workaround caused the TypeScript Parser to complain.
Ignoring the error through adding a `@ts-ignore` (and an `eslint-disable-next-line` on the line before), the workaround did fix the issue. It ain't pretty so hopefully this bug can be fixed soon.

**Comment by patrick-99** [comment]
> workaround:
> 
> ```js
> // main.js
> import Ripple from 'vuetify/lib/directives/ripple';
> Vue.use(Vuetify, {
>   directives: {
>     Ripple,
>   },
> });
> ```

I used for Vuetify 2.4.5:
import { Ripple } from 'vuetify/lib/directives';

**Comment by luancardosolc** [comment]
> The same issue. It comes from v-simple-checkbox, adding `v-ripple` or `:ripple="false"` to the v-simple-checkbox component solves these warning. But it should work from the box.

thank you so much, works just fine!

**Comment by johnleider** [comment]
Is this still occurring as of v2.6?

**Comment by maxkobzev** [comment]
Yes, it's still here, just checked with v2.6.1

**Comment by johnleider** [comment]
> Yes, it's still here, just checked with v2.6.1

Can you provide me with your reproduction steps?

**Comment by maxkobzev** [comment]
sorry for the late reply, was busy and it's not too easy to reproduce outside of a real project
https://codesandbox.io/s/v-simple-checkbox-f265h?file=/src/App.vue:675-753 - here are the main reproduction steps
and looks like it appears only when using vuetify-loader

**Comment by BorisDmv** [comment]
Had the same problem but adding the :ripple="false" to the simple checkbox fixed it...Super weird

**Comment by johnleider** [comment]
@yuwu9145 https://github.com/vuetifyjs/vuetify/issues/12224#issuecomment-2255941857

**Comment by KaelWD** [comment]
TreeviewItem is just a ListItem, you may have two copies of vue loaded somehow.

**Comment by pciavald** [comment]
for now i've proceeded to make my own treeview with a custom recursive component, but i'll keep updated here so i can check back when vuetify treeview reaches stable status

**Comment by yuwu9145** [comment]
@pciavald try https://github.com/vuetifyjs/vuetify/releases/tag/v3.6.13-3.7.0-beta.0.0
