### ISSUE TITLE
[Feature Request] Slow SASS variables build, use CSS in JS instead

### ISSUE THREAD

**Issue by XavierChevalier** [vuetifyjs/vuetify#12227]
### Problem to solve
Every time we change a SASS variable on our projects, we have to wait on average `01:17.476` for the project to build in `dev-server`.
This is due to the slow compilation of SASS. Each time we want to modify a variable, SASS has to rebuild the whole application.

Different methods exist to reduce the build time, such as transforming the path `vuetify/lib` into `vuetify/lib/framework` (https://github.com/vuetifyjs/vuetify-loader/issues/44, https://github.com/vuetifyjs/vuetify/issues/11901#issuecomment-662841866), however they do not drastically reduce this time.
Related issue: https://github.com/vuetifyjs/vuetify/issues/9612

In addition, we cannot currently override Vuetify components in an atomic and simple way. Sometimes variables are missing that would be useful, other times it is necessary to create global CSS rules to override all the components that are not always easy (eg. `.v-dialog .v-dialog-close.v-icon { // change rules }`). The implicit side of CSS also makes it difficult to understand the origin of the styles.
In complement, Vuetify use CSS variables (eg. `var(--v-primary-base)`), SASS variables (eg. `$btn-text-transform`) and theme variables in JS (`$vuetify.theme.[...]`).

## CSS in JS ?
Many libraries exist to generate the style from JavaScript. This method is more practical and answers several problems:
1. The time of construction of the application: indeed, the construction of the style is done directly when the script is launched.
2. Better detection, autocompletion and manipulation of CSS styles and classes.
3. Precise and surgical modification of component styles.
4. Use of JS variables, we can forget about CSS and SASS variables.

In addition, all the benefits mentioned in the documentation of the Styled Components library such as the automatic generation of [critical CSS](https://styled-components.com/docs/basics)...

My API proposal would look like this:
```javascript
import styled from 'vue-styled-components';
import Vuetify from 'vuetify/lib/framework';
import { VBtn } from 'vuetify/lib';

const StyledVBtn = styled(VBtn)({
  fontSize: '1em',
  textTransform: 'none',
  height: (props) => props.btnHeight * 1.5, // `props` will contain all the variables used in the Vuetify component.
  '&:hover': {
    color: (props) => props.theme.color.primary,
  },
  // ...
});

new Vuetify({
  // ...
  components: {
    VBtn: StyledVBtn, // Override the default VBtn with the new styled component
  },
});
```
This proposal will have to evolve I think, there is surely a better way to proceed.

This allows you to change the style of a specific component and use JS variables from the Vuetify theme.

But also, we can create variants of the same component easily:
```javascript
import styled from 'vue-styled-components';
import Vuetify from 'vuetify/lib/framework';
import { VBtn } from 'vuetify/lib';

const BasicVBtn = styled(VBtn)({
  fontSize: '1em',
  textTransform: 'none',
});

const ScreamingVBtn = styled(BasicVBtn)({
  textTransform: 'uppercase',
});

new Vuetify({
  // ...
  components: {
    VBtn: BasicVBtn,
    // VBtn variants
    VBtnScreaming: ScreamingVBtn,
    // ...
  },
});
```

```html
<v-btn>My basic button</v-btn>
<v-btn-screaming>My screaming button ! :D</v-btn-screaming>
```

I think that the time to build the application will be clearly impacted positively. Nevertheless, it is important to keep in mind that the build is done on the customer's machine, in real time. It would be interesting to do several performance tests.

The impact is consequent, since it is necessary to rethink the entire style generation system. However, migration tools such as [`metacomponent`](https://github.com/springload/metacomponent) can surely help.

As you can see, I didn't think about all the subtleties and the future style API.
But I think it would be interesting to consider a solution that would eliminate the need to build the application with SASS variables.

**Comment by johnleider** [comment]
In the next version the vuetify-loader is going to work similar to this. At this time, when you change variables, the project has to be transpiled and that takes time. I recommend not making variable changes beyond initial configuration as the larger a project gets, the slower this can be.

We do have some documentation on this and depending upon your project setup, you can import from `vuetify/lib/framework` and receive a speed-bump. https://vuetifyjs.com/en/features/sass-variables/#caveats for more information.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
