### ISSUE TITLE
[Bug Report] List item is not activated correctly when used with `to` (vue-router)

### ISSUE THREAD

**Issue by AndersonZhangyq** [vuetifyjs/vuetify#12221]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Edge 85.0.564.51
**OS:** Windows 10, Linux

### Steps to reproduce
I created two list. One with `to` and one without `to`.
1 Expected to see the first item was activated in both lists.
2 randomly click on the items of either list

### Expected Behavior
1 The first list item is activated at first
2 I set the `value` of the `v-list-item-group` to the same variable, so the item with the same name should be activated together.

### Actual Behavior
1 The first item was activated in the second list, while not being activated in the first list.
2 When click randomly, two list was not the same. (Click more times and you will see this. It's random. : ) )

### Reproduction Link
<a href="https://jsfiddle.net/AndersonZhang/k074ntde/" target="_blank">https://jsfiddle.net/AndersonZhang/k074ntde/</a>

### Other comments
Hope to find a solution.

**Comment by KaelWD** [comment]
v-list-item-group is not intended to be used with route links.

**Comment by KaelWD** [comment]
> When click randomly, two list was not the same

The first one uses the router as its source of truth, v-model is ignored.
