### ISSUE TITLE
Change default background color for dark themed lists

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#1222]
### Steps to reproduce
Use a `v-list` element with the `dark` attribute.

### Versions
Latest of everything.

### What is expected ?
According to the MD spec regarding dark themes, the default background color of the `v-list` element when used with the `dark` attribute should be `#303030`.

https://material.io/guidelines/style/color.html#color-themes

If users want to keep the current behavior (i.e. lists appear lighter than the background), they should wrap their lists in a card.  This seems to be closer to the intention outlined in the MD spec, but let me know if you disagree with my interpretation.

### What is actually happening ?
The background color is `#424242`, which makes lists appear lighter and not flush with a page when used with the `dark` attribute.

### Reproduction Link
https://codepen.io/anon/pen/YxGGxY

### Side Note
The navigation drawer seems to suffer from this problem as well, although it's not quite as clear cut to me.  I believe it should also default to `#303030`, but I can open a separate issue for that one if deemed to be worthy of a conversation.

### Fix
```
.application--dark
  & .list,
  & .navigation-drawer
    background: #303030
```

**Comment by johnleider** [comment]
No idea why I changed this.
