### ISSUE TITLE
[Bug Report] VTooltip openDelay default is 0 instead of 200

### ISSUE THREAD

**Issue by jensboehm** [vuetifyjs/vuetify#12225]
### Environment
**Vuetify Version:** 2.3.10
**Last working version:** 0.17.0-beta.1
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Hover a tooltip.

### Expected Behavior
The tooltip opens after 200ms

### Actual Behavior
The tooltip opens immediately

### Reproduction Link
<a href="https://codepen.io/jensboehm/pen/eYZKGQW" target="_blank">https://codepen.io/jensboehm/pen/eYZKGQW</a>

### Other comments
This is a regression. There was an issue in the past that led to changing the openDelay default from 0 to 200: https://github.com/vuetifyjs/vuetify/issues/2237
https://github.com/vuetifyjs/vuetify/commit/79508423dd5f87a716a3979120d7ee05a4c2df35

The current default behavior is annoying when hovering over a couple of elements, e.g. in a toolbar since the tooltips pop up and disappear very quickly. It's especially painful since this has to be overridden in every single v-tooltip.

**Comment by johnleider** [comment]
This was introduced in https://github.com/vuetifyjs/vuetify/pull/6111 to correspond to the MD2 spec https://material.io/components/tooltips#behavior

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by prajapatidk** [comment]
Can vuetify team update open-delay time 0 to 800 in node package in version 2.6.7 ?
