### ISSUE TITLE
[Bug Report] v-toolbar SASS variables typo

### ISSUE THREAD

**Issue by peppasd** [vuetifyjs/vuetify#12222]
### Environment

**Browsers:** Opera, Internet Explorer, Microsoft Edge, Safari, Mozilla Firefox, Google Chrome
**OS:** Windows, Android, iOS, Linux, Mac OSX

### Steps to reproduce
1. Select v-toolbar under the available components
2. Search for "prom"
3. Only $toolbar-promient-padding should appear

There is a typo in promient. Should be prominent.

### Expected Behavior
$toolbar-prominent-padding

### Actual Behavior
$toolbar-promient-padding

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables/#variable-api" target="_blank">https://vuetifyjs.com/en/customization/sass-variables/#variable-api</a>

**Comment by MajesticPotatoe** [comment]
Not a documentation bug, that is what it is actually named.
