### ISSUE TITLE
[Bug Report] Overlay for Dark theme is wrong color

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#12233]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Edge 85.0.564.51
**OS:** Windows 10

### Steps to reproduce
Make an overlay, and apply the `theme--dark` class to the app.
- This also doesn't work when `dark` is applied to the `v-overlay` itself.

### Expected Behavior
The overlay should be transparent white

### Actual Behavior
The overlay is a transparent black.

### Reproduction Link
<a href="https://codepen.io/megaroeny/pen/abNjpzq?editors=1010" target="_blank">https://codepen.io/megaroeny/pen/abNjpzq?editors=1010</a>

### Other comments
I noticed the div element with the class `v-overlay__scrim` is overriding the white background on its parent div, `v-overlay`.

**Comment by KaelWD** [comment]
> The overlay should be transparent white

Why? It's a dark theme not an inverted colours theme.

**Comment by megaroeny** [comment]
> > The overlay should be transparent white
> 
> Why? It's a dark theme not an inverted colours theme. A white overlay would be blinding an an otherwise dark app.

Well, true. But I guess my concern was the elevation gets lost in dialogs, drawers, etc. So maybe that's not enough of a good reason. Just wanted to make sure this wasn't a bug too, so by the sound of your response, I'm guessing it's on purpose. 😅

**Comment by KaelWD** [comment]
Elevation in dark themes is supposed to be indicated by a lightened background colour, which is something we want to look at in v3. Dialogs have 24dp elevation so you'd still want a darker backdrop to contrast the 16% white overlay on the card body. VOverlay has `color` and `opacity` props if you want to experiment with changing these for your application (no idea why it isn't a SASS variable). 

https://material.io/design/color/dark-theme.html#properties

**Comment by megaroeny** [comment]
@KaelWD ah yeah you're right!! Yeah, I was actually looking to see if `v-overlay` had a SASS variable. Maybe add that to the list 😉
