### ISSUE TITLE
[Feature Request] Form onsubmit support - important for keyboards of mobile.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [vuetifyjs/vuetify#12235]
### Problem to solve
If you add this feature it helps below solutions:
Add the onsubmit feature of HTML.
Onsubmit helps for:
- Submitting with **enter** keyboard key.
- On mobile it helps to submit forms without buttons, just using one of the default phone keyboard's either Enter/OK/Submit/Go key.
- It helps with validation when user presses **enter** keyboard key, validation begin its work. This is helpful when the user enters into an input then presses **enter** .

### Proposed solution
Adding support of @submit(v-on:submit) or just onsubmit.

Thanks for Vuetify creator for looking at this feature request.
I know there is a solution at least. Warm thanks from Uzbekistan by Otabek.

**Comment by OtabekSadiridinov** [comment]
@johnleider You know this works with v-text-field(input) and v-form. And as I know from Quasar framework of VueJS, the @submit is added into v-form.

**Comment by johnleider** [comment]
We aren't doing anything special to form, this works as normal.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
