### ISSUE TITLE
[Documentation] MacOS Safari docs problem

### ISSUE THREAD

**Issue by nexcode** [vuetifyjs/vuetify#12230]
### Environment

**Browsers:** Safari 13.1.2
**OS:** Mac OS 10.15.6

### Steps to reproduce
Just open the page

### Expected Behavior
It seems to me that the examples should be centered

### Actual Behavior
![image](https://user-images.githubusercontent.com/16421948/93209859-0b071e80-f7a2-11ea-9751-595bb135c881.png)
---
![image](https://user-images.githubusercontent.com/16421948/93209866-0d697880-f7a2-11ea-9f1c-d70276778787.png)

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/bottom-sheets/" target="_blank">https://vuetifyjs.com/en/components/bottom-sheets/</a>

**Comment by nexcode** [comment]
console errors:  
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (bottom-sheets, line 7)

**Comment by nexcode** [comment]
![Снимок экрана 2020-09-15 в 17 19 11](https://user-images.githubusercontent.com/10132325/93222595-c9617e00-f777-11ea-88c8-afb34fb50221.png)

**Comment by nekosaur** [comment]
The documentation has been rewritten. If you're still experiencing problems, please create a new issue. Thank you.
