### ISSUE TITLE
[Bug Report] Filtered list does not work properly

### ISSUE THREAD

**Issue by mehmeteyupoglu** [vuetifyjs/vuetify#12231]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Select a list item and see the difference 

### Expected Behavior
Whatever I select, the filtered array should be on the list, that is, only the selected item should remain on the site. 

### Actual Behavior
Only the first item (index:0) meets the expected behaviour but the ones that come later do not work properly. 

### Reproduction Link
<a href="https://codepen.io/mehmet-ey-polu/pen/abNjNzZ?editors=1100" target="_blank">https://codepen.io/mehmet-ey-polu/pen/abNjNzZ?editors=1100</a>

**Comment by KaelWD** [comment]
Use a unique key instead of the index: https://codepen.io/kaelwd/pen/mdPjPBj?editors=1010

**Comment by mehmeteyupoglu** [comment]
It worked for me. Thanks.
