### ISSUE TITLE
[Feature Request] Column dividers in simple tables

### ISSUE THREAD

**Issue by nikmanzotti** [vuetifyjs/vuetify#12238]
### Problem to solve
According to #3364, column dividers have been added to *data tables* at some point. I think the possibility to enable column dividers would be useful also for *simple tables*.

### Proposed solution
In *data tables*, column dividers can be enabled through the  `headers` property, which is currently not available in the *simple tables* API. Possible solutions I have thought about:

* add `headers` property support to *simple tables*,
* add a dedicated `divider` property to *simple tables* (this would keep the API simpler, but if the attribute is at the table level it may not be possible to allow enabling the divider only for certain columns),
* add `border` utility CSS classes (similar to [what Bootstrap does](https://getbootstrap.com/docs/4.5/utilities/borders/), this may be useful for other components also).

Unfortunately, I don't have enough free time to spend on this at the moment. If I manage to perform further research or actually implement something, I will add a comment below.

**Comment by KaelWD** [comment]
Simple tables import the data table css, so you can utilise the class `<td class="v-data-table__divider">`
