### ISSUE TITLE
[Feature Request] v-date-picker: Possibility to show dates for previous and next month

### ISSUE THREAD

**Issue by floydqwz** [vuetifyjs/vuetify#12237]
### Problem to solve
I use the v-date-picker to select a week at a time. For weeks where the whole week is within the month, it works well, but for the time period 28 september - 4 october for instance, only 28, 29 and 30 will be visible.

### Proposed solution
I would like dates for previous month and next month which will fit within the table, to be visible: For september 2020: 31:st of August and 1-4:th of October would also show.

Compare with Ubuntu calendar for instance, which has this feature.

**Comment by aldebaran798** [comment]
This feature would be great, something like this [https://fomantic-ui.com/modules/calendar.html#/definition](https://fomantic-ui.com/modules/calendar.html#/definition)
