### ISSUE TITLE
Floating Action Button icon is broken in Safari browser

### ISSUE THREAD

**Issue by Leomund** [vuetifyjs/vuetify#1224]
### Summary
After recent updates in the Safari browser, the icon in the FAB is not centered and displayed on the left side of FAB.
http://imgur.com/a/ilh2n

### Steps to reproduce
Just add FAB component and check it in Safari.

### Versions

Latest of everything.

### What is expected ?

Icons must be centered like in all other browsers.

### Reproduction Link

https://codepen.io/Leomund/pen/ZJpezg
https://vuetifyjs.com/components/floating-action-buttons

**Comment by johnleider** [comment]
Fixed with #1162
