### ISSUE TITLE
[Feature Request] Expose variables for button min-width & padding ratios

### ISSUE THREAD

**Issue by matthew-dean** [vuetifyjs/vuetify#12242]
### Problem to solve
A hard-coded ratio of 1.777777777777778 for min-width and 2.25 for padding doesn't align with our current design system.

### Proposed solution
Expose `$btn-width-ratio` and `$btn-padding-ratio` e.g. `$btn-width-ratio: 1.777777777777778`

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
