### ISSUE TITLE
[Bug Report]  Text fields have errors when using the number type

### ISSUE THREAD

**Issue by Qwwerty** [vuetifyjs/vuetify#12246]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows

### Steps to reproduce
Text fields have errors when using the number type, allowing the letter E to be used as a number

### Expected Behavior

Leave only numbers

### Actual Behavior

Leaving letters, even with the number type

### Reproduction Link
<a href="https://codesandbox.io/s/busy-morning-mf0yd?file=/src/App.vue" target="_blank">https://codesandbox.io/s/busy-morning-mf0yd?file=/src/App.vue</a>

**Comment by jacekkarczmarczyk** [comment]
That's how native `input type="number"` works 
https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
