### ISSUE TITLE
[Bug Report] v-slide-y-transition cause element to jump (not smooth)

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#12240]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.14.6

![vuetify_trans1](https://user-images.githubusercontent.com/8376035/93671153-91f01b80-fa6e-11ea-9079-d0ad3f947311.gif)

### Steps to reproduce
Click on the `Toggle` button to activate the transition.

### Expected Behavior
The transition between elements must be smooth.

### Actual Behavior
When the transition plays the new element will jump from bottom to top.

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/xxVJNyr?editors=1011" target="_blank">https://codepen.io/mtermoul/pen/xxVJNyr?editors=1011</a>

**Comment by mtermoul** [comment]
Thank you guys for the great help! I guess by doing nothing you helped me to digg-in deeper and figure out the solution. This is the codepen on how to fix the issue: https://codepen.io/mtermoul/pen/xxVJNyr

Cheers.

**Comment by fagner02** [comment]
I love seeing no actions being taken
