### ISSUE TITLE
[Bug Report] v-form submit with one input

### ISSUE THREAD

**Issue by chemoral87** [vuetifyjs/vuetify#12254]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
1. create a v-form with only **one** v-text-field
2 focus input and press enter, 
3. the alert displays

4. insert another v-text-field in v-form
5 focus input and press enter, 
6. alert not displays

### Expected Behavior
i expect the alert display with one or more inputs

### Actual Behavior
with two or more inputs, the form doesn't submit

### Reproduction Link
<a href="https://codepen.io/sergio-kvitko/pen/eYZQJQK" target="_blank">https://codepen.io/sergio-kvitko/pen/eYZQJQK</a>

**Comment by jacekkarczmarczyk** [comment]
This is the behaviour of native forms and we won't change it

**Comment by chemoral87** [comment]
This is the solution, add input type="submit"

<v-form @submit.prevent="whatever()">
...
         <input type="submit" v-show="false" />
</v-form>
