### ISSUE TITLE
[Bug Report] Icon typo in Document example

### ISSUE THREAD

**Issue by henry-chen-2020** [vuetifyjs/vuetify#12255]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 3.0.0
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.14.6

### Steps to reproduce
In V-icon document page, go to Buttons section, click 'codepen' icon

### Expected Behavior
There should be an icon for Cancel button

### Actual Behavior
No icon display for Cancel button

### Reproduction Link
<a href="https://codepen.io/wc73/pen/NWNExZv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ficons%2F" target="_blank">https://codepen.io/wc73/pen/NWNExZv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ficons%2F</a>

### Other comments
https://codepen.io/wc73/pen/NWNExZv?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ficons%2F

This code pen has the fix. Basically change underscore to dash in  'mdi-minus_circle' to 'mdi-minus-circle'

**Comment by jacekkarczmarczyk** [comment]
Already fixed in next docs https://next.vuetifyjs.com/en/components/icons/#buttons
