### ISSUE TITLE
[Bug Report] Textarea with transition css animation breaks ui

### ISSUE THREAD

**Issue by FERN4N2** [vuetifyjs/vuetify#12266]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.1
**Browsers:** Firefox 80.0
**OS:** Windows 10

### Steps to reproduce
Its all in the link.

### Expected Behavior
Shrink component according to text.

### Actual Behavior
Not shrinking

### Reproduction Link
<a href="https://codepen.io/90fernandopc/pen/gOrQjOv" target="_blank">https://codepen.io/90fernandopc/pen/gOrQjOv</a>

**Comment by KaelWD** [comment]
Don't do that then.
