### ISSUE TITLE
<v-edit-dialog> half focused when programmatically focused 

### ISSUE THREAD

**Issue by hdimmig16** [vuetifyjs/vuetify#1226]
### Steps to reproduce
When either assigning `autofocus` or programmatically calling `this.$refs[id].focus();` on the `<v-text-field>` within a `<v-edit-dialog>`, the result is a state of half focus. The input is highlighted, but keyboard input is not accepted when you type.

### Versions

Vue v2.4.2, Vuetify v0.14.8, Mac OS 10.12, tested on both Chrome 62 and Safari 10.0.1 
### What is expected ?

I expect the caret (blinking cursor) to appear and have my keystrokes recorded as shown by the normal text input box on the right of my codepen. 
### What is actually happening ?

When programmatically focused, the emitted focus payload is `undefined`, while clicking triggers a `FocusEvent`
### Reproduction Link

https://codepen.io/hdimmig/pen/NvRwwX

**Comment by jacekkarczmarczyk** [comment]
It looks like some race condition, this fixes the issue (in codepen, not in vuetify sources):

```window.setTimeout(() => this.$refs.test.focus(), 17);```

17 is the smallest value that worked for me, maybe it has something to do with request animation frame (16.666ms = 1/60s)?
