### ISSUE TITLE
[Bug Report] Formatting of the main table shifts when embedded table expands

### ISSUE THREAD

**Issue by IvanBNY** [vuetifyjs/vuetify#12264]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 3.0.0
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
Formatting of the main table shifts when embedded table expands.
click on expand and you will notice that main table formatting shifts to the right when underlying/embedded table expands.
![Image of V-data-table Issue](https://www.linkpicture.com/q/vueityfIssue2.jpg)

### Expected Behavior
No shift should be happening.

### Actual Behavior
shift happens.

### Reproduction Link
<a href="https://codepen.io/ivorona/pen/zYqayNV" target="_blank">https://codepen.io/ivorona/pen/zYqayNV</a>

**Comment by nekosaur** [comment]
You need to wrap the table in a `<td>` with colspan. https://codepen.io/nekosaur/pen/RwaqMwL
