### ISSUE TITLE
[Feature Request] Allow using components as standalone without v-app

### ISSUE THREAD

**Issue by b-strauss** [vuetifyjs/vuetify#12260]
### Problem to solve
Currently all components need to be wrapped inside a v-app to be styled properly. Not all projects need a full material app, sometimes you just want to use a specific component from material (e.g. Button).

### Proposed solution
Refactor the components to be used as standalone components.

**Comment by johnleider** [comment]
This is essentially happening for version 3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
