### ISSUE TITLE
[Feature Request] DataTable show-select ALL,  should not highlight rows that have select checkboxes disabled.

### ISSUE THREAD

**Issue by vjorihoxha** [vuetifyjs/vuetify#12263]
### Problem to solve
In the below code I have each row's select checkbox disabled if a condition is not satisfied. If I click the Select All checkbox, it highlights even rows that have the checkbox hidden. 

                        <template v-slot:item.data-table-select="{ item, isSelected, select }">

                            <v-simple-checkbox
                                :value="isSelected"
                                v-if="item.status === 'request'"
                                @input="select($event)"
                            ></v-simple-checkbox>

                        </template>

### Proposed solution
I did a work around solution where I kept my selected object in watch, and removed arrays from my object that did not satisfy my condition. In the end it did not highlight the hidden checkbox rows, but it created another bug, the Select All checkbox kept the minus animation.

What I propose is to have this feature built in the API, so we don't have to do work arounds with show-select attribute checkboxes.

**Comment by KaelWD** [comment]
#8915
