### ISSUE TITLE
[Bug Report] goTo doesn't scroll to correct element when continuous call 

### ISSUE THREAD

**Issue by spacerefugee** [vuetifyjs/vuetify#12261]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Edge 85.0.564.51
**OS:** Windows 10

### Steps to reproduce
```
<template>
  <div id="app">
    <v-app>
      <v-main>
        <v-row class="ma-2">
          <v-btn ref="btn1">button 1</v-btn>
        </v-row>
        <div class="padding"></div>
        <v-row class="ma-2">
          <v-btn ref="btn2">button 2</v-btn>
        </v-row>
      </v-main>
    </v-app>
  </div>
</template>
<script>
export default {
  mounted() {
    let options = { duration: 2000 };
    this.$vuetify.goTo(this.refs.btn1.$el, options);
    this.$vuetify.goTo(this.refs.btn2.$el, options);
  }
};
</script>
<style>
.padding{
  height:2000px;
}
</style>
```

### Expected Behavior
scroll to button 2 and stop

### Actual Behavior
after scroll to button 2 then scroll to button 1.

### Reproduction Link
<a href="https://codepen.io/BreadKiller/pen/xxVQqeB" target="_blank">https://codepen.io/BreadKiller/pen/xxVQqeB</a>

### Other comments
As we know, `goTo` stops when it's not possible to scroll more, if it stops before the duration end, the other `goTo` called before will keep scrolling, so it will make the last call become not the last scroll.

**Comment by jacekkarczmarczyk** [comment]
You need to wait for the first promise to resolve

https://codepen.io/jkarczm/pen/xxObPrO
