### ISSUE TITLE
[Feature Request] add support for show-arrows="false" on v-slide-group

### ISSUE THREAD

**Issue by econic** [vuetifyjs/vuetify#12274]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Just create a tabs component and disable the arrows 

### Expected Behavior
space of arrows is freed

### Actual Behavior
space of left arrow is not freed

### Reproduction Link
<a href="https://codepen.io/econic/pen/VwaqVKP" target="_blank">https://codepen.io/econic/pen/VwaqVKP</a>

### Other comments
The selector 

.v-slide-group.v-item-group>.v-slide-group__next, .v-slide-group.v-item-group>.v-slide-group__prev

used to do this by setting display: none, but is overridden by

.v-tabs:not(.v-tabs--vertical).v-tabs--right>.v-slide-group--is-overflowing.v-tabs-bar--is-mobile:not(.v-slide-group--has-affixes) .v-slide-group__next, .v-tabs:not(.v-tabs--vertical):not(.v-tabs--right)>.v-slide-group--is-overflowing.v-tabs-bar--is-mobile:not(.v-slide-group--has-affixes) .v-slide-group__prev

that sets display: initial

**Comment by furkan-guvenc** [comment]
Is there a workaround?

**Comment by rmarmitt** [comment]
bump

**Comment by johnleider** [comment]
This exists in Vuetify 3 now.
