### ISSUE TITLE
[Feature Request] v-data-table header should specify text field as optional, and also allow a simple string.

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#12275]
### Problem to solve
Simplifies syntax.

### Proposed solution
The data table works using a header as such:
`headers: [{value:'myColumn'}]`
In which case it does not display a column.

I feel that the default name should be the column value, unless specified otherwise.
So previous example would be same as:
`headers: [{value:'myColumn', text:'myColumn'}]`

Furthermore, a simple string should be allowed.
`headers: ['myColumn']`
that is converted to
`headers: [{value:'myColumn', text:'myColumn'}]`

Finally, documentation states:
`text: string` but could be
`text?: string`

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
