### ISSUE TITLE
[Bug Report] DataTable "per-page" dropdown is clipped in FireFox

### ISSUE THREAD

**Issue by itelmenko** [vuetifyjs/vuetify#12273]
# Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. Create DataTable where :footer-props with  itemsPerPageOptions: [ 10, 15, 20, 50, 100, 250, 500, -1 ] 
2. Open it in FireFox
3. Open "per-page" dropdown

### Expected Behavior
"per-page" dropdown has correct width. All options can be read in it.

### Actual Behavior
"per-page" dropdown is clipped in FireFox. 

### Reproduction Link
<a href="https://codepen.io/itelmenko/pen/ZEWVorK" target="_blank">https://codepen.io/itelmenko/pen/ZEWVorK</a>

![Screenshot_20200923_102859](https://user-images.githubusercontent.com/495449/93981681-f0780b00-fd88-11ea-90ed-65219bea67b8.png)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
