### ISSUE TITLE
[Bug Report] v-btn throws an error when a click is simulated

### ISSUE THREAD

**Issue by matthew-dean** [vuetifyjs/vuetify#12270]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Attach a ref to a v-btn
2. Fire this.$refs[button].click()
3. The error in console is "Cannot read property 'detail' of undefined

### Expected Behavior
A button element should allow simulated clicks. In this case, it's because, for accessibility reasons, buttons in our app are triggered with the keyboard. I would have expected to see the click animation (ideally from center, but from 0,0 if an event is not provided is fine too). 

### Actual Behavior
It just throws an error and gives no visual feedback.

### Reproduction Link
<a href="https://codepen.io/matthewdean/pen/GRZPZEj" target="_blank">https://codepen.io/matthewdean/pen/GRZPZEj</a>

**Comment by matthew-dean** [comment]
Note: I was able to workaround this with:
```js
        const el = this.$refs.button?.$el
        if (el) {
          el.dispatchEvent(new MouseEvent('mousedown'))
        }
```
Should I close this?

**Comment by KaelWD** [comment]
Use `this.$refs.button.$el.click()`
