### ISSUE TITLE
datatable doesnt sort array of class instances just plain js objects

### ISSUE THREAD

**Issue by mhorvath** [vuetifyjs/vuetify#1227]
### Steps to reproduce
click on the datatable headers to sort

### Versions
current versions of all libs
os doestn matter

### What is expected ?
the data of the array filled with class instances should be sorted

### What is actually happening ?
the data is not sorted
datatable only sorts plain js objects not selfmade class instances

### Reproduction Link
https://jsfiddle.net/6esv9arg/1/

**Comment by nekosaur** [comment]
This has been fixed in dev (see PR #1143). Will be available next release

**Comment by mhorvath** [comment]
thx, it works now!
