### ISSUE TITLE
[Bug Report] the translation to Chinese is incomplete, misleading and some are incorrect

### ISSUE THREAD

**Issue by yestodorrow** [vuetifyjs/vuetify#12276]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 3.0.0-rc.13
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
translation wrong

### Expected Behavior
translation correct 

### Actual Behavior
translation wrong

### Reproduction Link
<a href="https://github.com/wrongtranslation" target="_blank">https://github.com/wrongtranslation</a>

**Comment by KaelWD** [comment]
Translations are all done by the community, if you think something is wrong you're welcome to fix it.
