### ISSUE TITLE
[Bug Report] v-checkbox can be checked/unchecked by clicking anywhere in the containing container

### ISSUE THREAD

**Issue by rtarnec** [vuetifyjs/vuetify#12278]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Firefox 80.0
**OS:** Mac OS 10.15

### Steps to reproduce
Declare a v-checkbox in a "container" (e.g. v-container or v-col) with a large width. You can check/uncheck the checkbox by clicking anywhere in the container (and not only on the checkbox itself or on the label of the checkbox). You can experiment this behaviour in the doc, with the first check box shown in the Usage section (https://vuetifyjs.com/en/components/selection-controls/#usage) Just click 4 or 5 centimeters on the right of the  checkbox and it will be checked/unchecked. 

### Expected Behavior
The checkbox should be checked/unchecked only when one clicks on the checkbox (i.e. the grey square) or on the label of the checkbox. In case of a checkbox without label, the checkbox should be checked/unchecked only when one clicks on the checkbox.

### Actual Behavior
You can check/uncheck the checkbox by clicking anywhere in the container

### Reproduction Link
<a href="https://codepen.io/rtarnec/pen/RwavKKV" target="_blank">https://codepen.io/rtarnec/pen/RwavKKV</a>

**Comment by KaelWD** [comment]
v-checkbox is a block element by default. Use `class="d-inline-flex` to make it inline, or put it in a flex container so it can shrink.

**Comment by khavysroeurn** [comment]
<div class="d-flex">...</div>
https://vuetifyjs.com/en/styles/flex/
