### ISSUE TITLE
[Feature Request] official support for nuxt module

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [vuetifyjs/vuetify#12271]
### Problem to solve
I'm using `@nuxtjs/vuetify` community module but  it is outdated as it uses `vuetify` version `2.0`. The module also has a critical problem in `tree-shaking` as described in the [issue](https://github.com/nuxt-community/vuetify-module/issues/382) I've opened in `@nuxtjs/vuetify`  16 days ago with no response whatsoever.

### Proposed solution
Official support is needed for the nuxt module in order for it to be bug-free and always up-to-date.

**Comment by johnleider** [comment]
We already have nuxt people on the team who work with the community module. I don't personally use nuxt so I'm relying on the community for this one. @aldarund or @kevinmarrec could maybe chime in here.

**Comment by KaelWD** [comment]
> it is outdated as it uses vuetify version 2.0

It uses `^2` which installs the latest v2.x.x patch

https://docs.npmjs.com/cli/v6/using-npm/semver#ranges

> The module also has a critical problem in tree-shaking

I've replied to your issue, it isn't a bug.

**Comment by AbdallahAlhaddad** [comment]
@johnleider  @KaelWD  
Thank you for your replies.
I have a suggestion; I wonder if it will be applicable to use the same approach as `bootstrap-vue` to integrate `nuxt` (please see docs [here](https://bootstrap-vue.org/docs/#nuxtjs-module)  and code [here](https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/nuxt) ) to unify the two repositories together?

It will be quite helpful if this approach is applicable.
Thanks again for your support.

**Comment by JPustkuchen** [comment]
Hello Vuetify-Team,

thank you so much for your GREAT work pushing things forward for Vue3! :)

I hope it's okay to revive this issue and ask for an official documentation page for NUXT3 integration with Vuetify!
I guess that would be very important to make using Vuetify comfortable with NUXT3, as it's missing such integrations yet.

Here's a larger discussion and many questions, so it would be great to have an "official way" of integration, thanks :)

https://github.com/nuxt/framework/discussions/1183#discussioncomment-4280051

**Comment by kogratte** [comment]
Hello guys. I'm having some issues with nuxt and some google research point me here. I can only be aligned with what has been sayed previously, aka, nuxt support is a mess.

Nothing work as described in any docs and there are no official examples.

An official nuxt support could GREATLY improve DX.

**Comment by johnleider** [comment]
If someone sets up an initial guide we'll do what we can.

**Comment by likt0r** [comment]
Hi there, first THX for the great work done so far with Vuetify. 
There is a community nuxt-vuetify module now [nuxt-vuetify]( https://github.com/invictus-codes/nuxt-vuetify)
This works if you do not alter the sass variables and SSR. 
If you do so, you get a broken path in the sourcemap of the vuetify components.
It looks like this 
`
{
  "version": 3,
  "file": "\\u0000plugin-vuetify:components/VBtnToggle/VBtnToggle.sass",
  "mappings": "AAMA;ACGA;EACE;EACA;EAEA;EACA;EACA;... (truncated for brevity)",
  "names": [],
  "sources": [
    "file:///home/.../frontend/node_modules/vuetify/lib/components/VBtn/_variables.scss",
    "file:///home/.../frontend/assets/settings.scss",
    "file:///home/.../frontend/node_modules/vuetify/lib/styles/tools/_states.sass"
  ],
  "sourcesContent": [null, null, null],
  "x_google_ignoreList": [0, 2]
}
`
The file path includes, as I understand, a null value. 
This also happens with all other guides to using vuetify with nuxt I found out there [Example 1](https://codybontecou.com/how-to-use-vuetify-with-nuxt-3.html)
I am uncertain if this is a nuxt, or vuetify issue. But something went wrong with the bundling.  Maybe someone has a clue or hint what to do to fix it.

Greetings

**Comment by KaelWD** [comment]
Have you tried https://github.com/userquin/vuetify-nuxt-module?

**Comment by likt0r** [comment]
Thx this seems to work better, but still, inline styles have to be disabled.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/nuxt-module
