### ISSUE TITLE
[Feature Request] Does v-slide-group have any kind of page control?

### ISSUE THREAD

**Issue by JackShepard98** [vuetifyjs/vuetify#12277]
### Problem to solve
It will be useful to navigate through the slide group easier

### Proposed solution
Have page control just like v-carousel delimiter:

![image](https://user-images.githubusercontent.com/36894163/94107419-1b746480-fe46-11ea-8423-d0734cbdeaac.png)

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by shubh47-dddd** [comment]
This really is needed. Please add this if you guys can. Meanwhile, is there any workaround we can achieve this?
