### ISSUE TITLE
[Bug Report] v-tooltip does not add itself to a v-icon when initialized with disabled=true

### ISSUE THREAD

**Issue by Esurnir** [vuetifyjs/vuetify#12284]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
Click on the "Activate" button.

### Expected Behavior
The tooltip on the v-icon is active and a mouseover on the icon will show the tooltip.

### Actual Behavior
The tooltip on the v-icon does not work.

### Reproduction Link
<a href="https://codepen.io/esurnir/pen/qBZgebm" target="_blank">https://codepen.io/esurnir/pen/qBZgebm</a>

### Other comments
If you changed disabled default status to false, the tooltip will toggle properly by clicking the button.

**Comment by buglavecz** [comment]
Hi, 

try this workaround: https://codepen.io/buglavecz/pen/vYGPBKw ?

**Comment by Esurnir** [comment]
This would work, I did another workaround (use another component wrapping the icon as my activator) instead of using this one but both work.
