### ISSUE TITLE
[Feature Request] Allow module importing without (Sass) side-effects

### ISSUE THREAD

**Issue by matthew-dean** [vuetifyjs/vuetify#12282]
### Problem to solve
We're trying to extend Vuetify to export shared components within our company.

However, this is proving quite difficult for several reasons.

One of the main issues is that to use custom variables, we have to modify webpack's (or vue-cli's) sass-loader. It's very non-trivial then to import that source into another repo (as that repo would _also_ have to modify webpack settings, including sass-loader, to inject this variables file).

### Proposed solution
This WOULD be circumventable if the modules themselves could be imported as components, _and_ their related Sass could be opted to NOT be imported as a side-effect with the module.

As in:
```vue
<!-- Button.vue -->
<template>
  <v-btn>{{ label }}</v-btn>
</template>

<script>
import { VBtn } from 'vuetify/lib'
export default {
  components: { VBtn }
  props: ['label']
}
</script>

<style lang="scss">
@import "styles/variables.scss";  // our custom vars
@import "~vuetify/src/components/VBtn/VBtn.sass";
</style>
```

So, one trivially easy way to enable this is to remove `import './VBtn.sass'` from `VBtn.ts` and add it to `index.ts`.

That would mean that you could import without side effects like:
```js
import VBtn from 'vuetify/lib/components/VBtn/VBtn'
```
and you could _still_ import with side effects like:
```js
import { VBtn } from 'vuetify/lib'
// or import { VBtn } from 'vuetify/lib/components/VBtn'
```

So IMO it's a trivial one-line change that would allow more flexibility in how / when styles are imported, and would allow us to extend Vuetify to multiple repos. Downstream repos, using this pattern would need neither vuetify-loader or a modification of sass-loader to import this source (using vue-cli).

**Comment by matthew-dean** [comment]
Btw, I'm willing to submit a PR for this.

**Comment by johnleider** [comment]
This is all changing for v3 and will be easily customizable.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by matthew-dean** [comment]
@johnleider Thanks for taking the time to respond!
