### ISSUE TITLE
Bug: circular progress bar not at 360 degrees when 100%

### ISSUE THREAD

**Issue by oodgaard** [vuetifyjs/vuetify#1229]
### Versions
Vue: 2.4.2
Vuetify: 0.14.8
Chrome, FF, Opera (all the latest versions as of this post)

### What is expected ?
Expect to see the circular progress bar to be at 360 degrees when the value is 100%, 180 degrees at 50% etc.

### What is actually happening ?
The circular progress bar is not at 360 degrees when the value is 100%. It's more like 285-290 degrees.
At 70% the circle is at 180 degrees.

The maths in strokeDashOffset() is correct, but when it renders it seems to lag behind. I tested by returning a static value for 50% ('78.53981633974483px') and the circle was in the correct location.

### Reproduction Link
https://jsfiddle.net/3ym0obq2/3/

**Comment by cawa-93** [comment]
The problem is in your interval. It's too fast, the animation just does not keep up
https://jsfiddle.net/d1q5ejyd/

**Comment by johnleider** [comment]
@cawa-93 is correct, it has nothing to do with the component.

**Comment by oodgaard** [comment]
I see. It is not suitable for my use case then. The bar seems to work better. Thanks for your input.
