### ISSUE TITLE
[Documentation] Cant't read Vuetify Documents

### ISSUE THREAD

**Issue by syscom-system** [vuetifyjs/vuetify#12291]
### Environment

**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6

### Expected Behavior
Can Read

### Actual Behavior
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)

### Reproduction Link
<a href="https://vuetifyjs.com/ja" target="_blank">https://vuetifyjs.com/ja</a>

**Comment by MajesticPotatoe** [comment]
Translations are not available at this time until translators update translations via crowdin. That url is currently invalid.
visit https://vuetifyjs.com or visit https://v2.vuetifyjs.com/ja

**Comment by syscom-system** [comment]
Thanks you for supporting.

**Comment by Pixman** [comment]
Hello, same error on chrome Version 85.0.4183.121 (Build officiel) (64 bits) on Windows 10 x64
