### ISSUE TITLE
[Bug Report] Mobile Touch: cannot swipe vertically when in contact with vuetify slider group

### ISSUE THREAD

**Issue by riyaz7us** [vuetifyjs/vuetify#12293]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4270.0
**OS:** Windows 10

### Steps to reproduce
1. Create slider group (Codepen link added) 
2. Create additional content (long enough to scroll the page)
2. Use touch supported device or mobile view in browser
3. Scroll/swipe through y-axis of the slide group (vertically)

### Expected Behavior
The page must be able to scroll up/down

### Actual Behavior
The swipe is inherited by the slide group, making it prevent page scrolling.

### Reproduction Link
<a href="https://codepen.io/sdriyaz712/pen/abNMrMR" target="_blank">https://codepen.io/sdriyaz712/pen/abNMrMR</a>

**Comment by gakinson** [comment]
I am experiencing a similar issue

**Comment by riyaz7us** [comment]
Update: same issue with vuetify tabs slider

**Comment by Stelikas** [comment]
@riyaz7us Having the same issue, hope it gets fixed soon. I will use Vue-Carousel too, thanks for the recommendation :)

**Comment by natnael-wubet** [comment]
in the vue page you using the slide group, type this css
```

<style>
.v-slide-group__wrapper {
    touch-action: auto !important;
}
</style>
```
