### ISSUE TITLE
New buttons look weird

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuetifyjs/vuetify#123]
After install the new release this is how the buttons looks like

<img width="196" alt="screen shot 2017-02-10 at 19 05 00" src="https://cloud.githubusercontent.com/assets/15908060/22838109/ddb4ef50-efc3-11e6-8725-577fc47e90c0.png">

I can't find a way to make them look like in the doc. The outline options stops to work and all buttons have some kind of really bad looking toggle state by default.

**Comment by johnleider** [comment]
The buttons are now 100% material design spec. If you want white text either use the dark prop or white--text class.

**Comment by FrancescoSaverioZuppichini** [comment]
So should I go through all my app and add to every single button the new prop?
