### ISSUE TITLE
[Bug Report] v-bottom-navigation scroll up does not show only if scroll to the bottom once

### ISSUE THREAD

**Issue by SamnnyWong** [vuetifyjs/vuetify#12306]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6

### Steps to reproduce
run npm install then npm run serve
scroll down a little then scroll up the bottom nav wouldn't show up, but if scroll down to the very bottom then scroll up, everything works perfefctly.

### Expected Behavior
scroll down then scroll up the nav bar shows up.

### Actual Behavior
croll down a little then scroll up the bottom nav wouldn't show up.

### Reproduction Link
<a href="https://github.com/DavidCurryHan/tacticsApp" target="_blank">https://github.com/DavidCurryHan/tacticsApp</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
