### ISSUE TITLE
24hr TimePicker with pm/am suffix

### ISSUE THREAD

**Issue by menteora** [vuetifyjs/vuetify#1230]
### Steps to reproduce

You open Time Picker and you doesn't select anything, only click outside the box.

It save the current time with "pm" or "am" suffix

![timepicker](https://user-images.githubusercontent.com/3657745/28927151-1e1d6ac0-786a-11e7-8f4c-68deb739a9b2.gif)

### Versions
Current cdn version 
Vuetify v0.14.8
Vue.js v2.4.2

### What is expected ?

Time without suffix.

It could be useful a temporary workaround.
Thank you for your great work!

### Reproduction Link
https://jsfiddle.net/menteora/75uohy1d/5/

**Comment by sbosell** [comment]
It is defaulting to "NOW". I don't think the picker should return the time without a suffix, if you didn't select a time it should probably remain blank.
