### ISSUE TITLE
[Bug Report] Vuetify multiple v-select required rules don't work

### ISSUE THREAD

**Issue by georginklv** [vuetifyjs/vuetify#12308]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
If its multiple select rules to be required don't work  if its not a multiple its ok.

### Expected Behavior
rules to work for multiple select as well 

### Actual Behavior
rules don't work if its multiple select

### Reproduction Link
<a href="https://codepen.io/georgi-o-nikolov/pen/abNxrXG" target="_blank">https://codepen.io/georgi-o-nikolov/pen/abNxrXG</a>

**Comment by jacekkarczmarczyk** [comment]
Please create a valid reproduction, there are some errors in your codepen

**Comment by georginklv** [comment]
@jacekkarczmarczyk  I'm so sorry, now should be ok.

**Comment by jacekkarczmarczyk** [comment]
I've just noticed you're using vuetify 1.1, sorry this version is not supported anymore

Please read https://vuetifyjs.com/en/introduction/long-term-support/#vuetify-15-lts

**Comment by georginklv** [comment]
@jacekkarczmarczyk vuetify does not want to start at code pan with last version 2.3.10 and this is the only way which i found to start vuetify. Please let me know which version i can use. Also im using " !!v ", you can check it at rules -> select

**Comment by jacekkarczmarczyk** [comment]
> Also im using " !!v "

Sorry, I've updated my comment, you can't use `!!v`

And here is the 2.3 template: http://template.vuetifyjs.com/
