### ISSUE TITLE
[Bug Report] v-data-table: customGroup throws 'groupedItems.map is not a function'

### ISSUE THREAD

**Issue by SystemKeeper** [vuetifyjs/vuetify#12303]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Used the example from the pull request (https://github.com/vuetifyjs/vuetify/pull/9253/files#diff-42355413c58a2bc0bbe1e124699588dc) as a starting point. But it throws TypeError: groupedItems.map is not a function:
![image](https://user-images.githubusercontent.com/1580193/94461300-3a625600-01ba-11eb-8929-f89bed304aeb.png)

```
 groupBy: function evenOddGrouper (items, groupBy) {
        const key = groupBy[0]
        return items.reduce((rv, x) => {
          const group = x[key] % 2 ? 'odd' : 'even';
          (rv[group] = rv[group] || []).push(x)
          return rv
        }, {})
```

### Expected Behavior
- Custom group works as expected (I guess this used to work??)

### Actual Behavior
- Custom group does not work.

### Reproduction Link
<a href="https://codepen.io/SystemKeeper/pen/MWyRVPP" target="_blank">https://codepen.io/SystemKeeper/pen/MWyRVPP</a>

**Comment by nekosaur** [comment]
Seems like we changed the internal implementation. https://codepen.io/nekosaur/pen/zYqXjMK

**Comment by eran-medan** [comment]
I haven't seen this mentioned in the documentation, it still shows the old signature.
