### ISSUE TITLE
[Documentation] translation service is not working at all

### ISSUE THREAD

**Issue by Mo-** [vuetifyjs/vuetify#12300]
### Environment

**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
if its matters, i'm from russia
some of console output:

GET crwdns180074:0crwdne180074:0 net::ERR_UNKNOWN_URL_SCHEME
crwdns180074:0crwdne180074:0:1 

Uncaught ReferenceError: _jipt is not defined
jipt.js:1

### Expected Behavior
required field

### Actual Behavior
required field

### Reproduction Link
<a href="https://vuetifyjs.com/eo-UY/getting-started/installation/" target="_blank">https://vuetifyjs.com/eo-UY/getting-started/installation/</a>

**Comment by MajesticPotatoe** [comment]
Thank you for reporting this. We are aware of the issue and are looking into fixing it.
This only prevents you from doing In-Context translations. You can still help translate via https://crowdin.com/project/vuetify/.

**Comment by Mo-** [comment]
great, but your workaround is too complicated)

**Comment by MajesticPotatoe** [comment]
Unfortunately until it is fixed, that is the only workaround available.
