### ISSUE TITLE
[Documentation] No sample code in the documentation

### ISSUE THREAD

**Issue by Dec-F** [vuetifyjs/vuetify#12309]
### Environment

**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
Open link

### Expected Behavior
There are only component views in the document but the code is missing

### Actual Behavior
There are views and code as before, or sandboxes links

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons/#examples" target="_blank">https://vuetifyjs.com/en/components/buttons/#examples</a>

### Other comments
![image](https://user-images.githubusercontent.com/20250430/94528469-085cfc80-026b-11eb-8ab7-5eb18cb0eaca.png)

**Comment by jacekkarczmarczyk** [comment]
can't reproduce, please try in incognito mode

**Comment by KaelWD** [comment]
Are the buttons there in the top right and just icons aren't rendering?

**Comment by Dec-F** [comment]
It seems to be caused by adblock extension
