### ISSUE TITLE
[Bug Report] expandable v-list in navigation drawer broken on iOS14

### ISSUE THREAD

**Issue by mrtnjcl** [vuetifyjs/vuetify#12314]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS14

### Steps to reproduce
1. Open the link in Safari on iOS14.x (iPhone simulator or device)
1. Open the nav drawer & expand section 'Dining' & close drawer, keeping it expanded
1. Scroll the main content about half way
1. Open the drawer again and collapse the section

### Expected Behavior
The menu should be visible

<img width="503" alt="Screenshot 2020-09-30 at 00 12 11" src="https://user-images.githubusercontent.com/1102746/94622144-eaff5100-02b1-11eb-95d6-7cbaf38e5cf9.png">

### Actual Behavior
The menu is obscured by weird rectangle, which is not in the DOM
<img width="513" alt="Screenshot 2020-09-30 at 00 12 44" src="https://user-images.githubusercontent.com/1102746/94622116-dc189e80-02b1-11eb-89a4-2e9dd8075b47.png">

### Reproduction Link
<a href="https://codepen.io/martinjacala/pen/rNegwWv" target="_blank">https://codepen.io/martinjacala/pen/rNegwWv</a>

**Comment by rogerioufjf** [comment]
Same problem here.. Any solution? Did you solved?

**Comment by martinjacala** [comment]
I found a workaround which did the trick for me. I think the issue is the `display: block;` on the drawer component. When i applied `display: list-item;` the issue disappeared.

**Comment by l1990790120** [comment]
adding either display flex/list-item somehow worked for me, was really confused, would love to know the root cause

**Comment by gsjen** [comment]
This looks like a rendering bug in Safari. Removing the box-shadow from the v-navigation-drawer also seems to fix the issue.
