### ISSUE TITLE
[Bug Report] v-footer doesn't work with dynamic content height

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#12313]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use tooltips in a app footer.

### Expected Behavior
The content to not be hidden by the footer.

### Actual Behavior
Footer is overlapping the main content.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/eYZadQm" target="_blank">https://codepen.io/thomaskientz/pen/eYZadQm</a>

**Comment by nekosaur** [comment]
Wrapping this line https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/applicationable/index.ts#L62 in a `$nextTick` solves the problem. @johnleider you're the application expert. Are there any risks here?

**Comment by KaelWD** [comment]
Might cause layout jump? v-footer doesn't support dynamic content height, adding `height="48px"` also fixes it.

**Comment by ThomasKientz** [comment]
> Might cause layout jump? v-footer doesn't support dynamic content height, adding `height="48px"` also fixes it.

Height might depend on screen width for responsive layouts.

**Comment by KaelWD** [comment]
Duplicate of #11121
