### ISSUE TITLE
[Bug Report] prepend and append inner-icon of v-text-field has flex-start alignment

### ISSUE THREAD

**Issue by vchrisb** [vuetifyjs/vuetify#12310]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6, Linux

### Steps to reproduce
create a v-text-field with `height = "40px"` and `clearable` configured.

### Expected Behavior
Clearable icon being centred with text input.

### Actual Behavior
`v-input__append-inner` does have an `align-self: flex-start` configured, resulting in the clearable, or any inner prepend and append, icon to be aligned to the top.

### Reproduction Link
<a href="https://codepen.io/vchrisb/pen/RwambwJ?editors=1010" target="_blank">https://codepen.io/vchrisb/pen/RwambwJ?editors=1010</a>

**Comment by johnleider** [comment]
Flex alignment is to meet the specification with the default settings and unfortunately cannot support every possible use-case.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
