### ISSUE TITLE
[Documentation] Api link from component to api page incorrect for combobox

### ISSUE THREAD

**Issue by ach-abe** [vuetifyjs/vuetify#12311]
### Environment

**Browsers:** Firefox 81.0
**OS:** Windows 10

### Steps to reproduce
Click on:
v-combobox

To open api

### Expected Behavior
to open https://vuetifyjs.com/en/api/v-combobox/

### Actual Behavior
opens with 404 https://vuetifyjs.com/en/api/v-combo-box/

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/combobox/#api" target="_blank">https://vuetifyjs.com/en/components/combobox/#api</a>

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/d633e0c8519dee9ed4a3f639941b366f634ca0fd
