### ISSUE TITLE
[Feature Request] Recycler View For Very Large Lists Needed

### ISSUE THREAD

**Issue by lartheon** [vuetifyjs/vuetify#12325]
### Problem to solve
When trying to display large lists of data e.g 1million items it consumes too much memory thus locking the UI thread in order render the list. (I already do a type of pagination to retrieve all the data from the API but pagination is not suitable for displaying the content to the user).

### Proposed solution
Out of the box recycler view which which recycle the view rather than creating all new views that aren't visible to the user which wastes a lot of resources.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/virtual-scroller/

**Comment by lartheon** [comment]
> https://vuetifyjs.com/en/components/virtual-scroller/

Oh wow sorry, I did a search and didn't come across this! Can I delete this feature request
