### ISSUE TITLE
[Bug Report] Small interval event gets cutoff at the end of the day

### ISSUE THREAD

**Issue by pamantea** [vuetifyjs/vuetify#12321]
### Environment
**Vuetify Version:** 2.3.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
When adding events that last 10 minutes or less, and start close to the end of the day, the event pill does not show up in the calendar. Just the top border shows, which makes it impossible to see event title and details.

### Expected Behavior
Event pill shows entire event title as on other times

### Actual Behavior
Event pill gets cuttoff and does not display properly

### Reproduction Link
<a href="https://codepen.io/pamantea/pen/PoNvxJZ" target="_blank">https://codepen.io/pamantea/pen/PoNvxJZ</a>

### Other comments
In the attached codepen, the event is on 2019-01-09 starting at 23:55. 
I also added an event at the beginning of the day for comparison, and the event properly shows up.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
