### ISSUE TITLE
[Bug Report] VTabs - change event called multiple times

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12328]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Go to the CodePen.
2. Open developers tools.
3. Refresh the page.
4. As you can see `@change` event in `VTabs` component is called twice.

![Screenshot 2020-10-01 at 19 54 21](https://user-images.githubusercontent.com/17653648/94845389-e8bb0500-041f-11eb-9f78-cba722cecfd9.png)

### Expected Behavior
`@change` event should be called only once

### Actual Behavior
`@change` event is called twice

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/BaKgmxK" target="_blank">https://codepen.io/mikilll94/pen/BaKgmxK</a>

**Comment by nekosaur** [comment]
This is not a bug. When the v-tabs component is mounted, no tab is selected. It automatically sets the first tab as selected and emits this new value. Then in your mounted function you push a new route, which gets picked up by the v-tabs component and it emits the new value.
