### ISSUE TITLE
[Bug Report] Documentation still showing v-content instead of v-main

### ISSUE THREAD

**Issue by rustyx** [vuetifyjs/vuetify#12339]
### Environment
**Vuetify Version:** 2.3.12
**Last working version:** 2.2.34
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
Minor documentation issue on
https://vuetifyjs.com/en/components/application/#default-application-markup

It says to use `<v-main>` for the main content area.

But the picture diagram still shows `v-content` in the main content area.

### Expected Behavior
diagram with `v-main` in the middle

### Actual Behavior
diaram with `v-content` in the middle: https://cdn.vuetifyjs.com/images/layouts/app.png

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/application/#default-application-markup" target="_blank">https://vuetifyjs.com/en/components/application/#default-application-markup</a>

**Comment by MajesticPotatoe** [comment]
duplicate #11663
