### ISSUE TITLE
[Bug Report] v-rating half star missing border

### ISSUE THREAD

**Issue by rubencanovaca** [vuetifyjs/vuetify#12336]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
In the rating component, when it shows half star filled, the border is missing.

### Expected Behavior
The half star have all the border around.

### Actual Behavior
The half star haven't the border around.

### Reproduction Link
<a href="https://codepen.io/rubencanovaca/pen/ExKBOXE?editable=true" target="_blank">https://codepen.io/rubencanovaca/pen/ExKBOXE?editable=true</a>

**Comment by rubencanovaca** [comment]
Works if I set the value of **half-icon** to "mdi-star-half-full"

But I understand that this should be the default half-icon (in docs works by this way)

**Comment by ricardovanlaarhoven** [comment]
For clarification:

There is indeed a difference between the docs and the codepen.
Perhaps there are some different material design icons used?
![VRatings](https://user-images.githubusercontent.com/1246691/96240763-9d693080-0fa1-11eb-9899-3b08bd9b2c7c.gif)

**Comment by jacekkarczmarczyk** [comment]
docs use mdi-svg, not sure why

**Comment by MajesticPotatoe** [comment]
> docs use mdi-svg, not sure why

Examples should be using `mdi-` may have been accidently converted during page conversion.

**Comment by KaelWD** [comment]
mdi preset uses `star-half`, mdi-svg uses `star-half-full`
