### ISSUE TITLE
Modal v-dialog inside v-data-table cell not working anymore since 0.14.8

### ISSUE THREAD

**Issue by smxsm** [vuetifyjs/vuetify#1233]
With release 0.14.8., modal dialog buttons inside data table cells stopped working, it works fine if I go back to 0.14.7.

### Steps to reproduce

Add a dialog element to a datatable cell and try clicking it.
Here is a codepen example, if you click on any of the buttons, nothing happens any more: https://codepen.io/beffy72/pen/OjbJOp
There is no error, and the Vue console says the button is firing an event, but it seems the data table now "sucks it up" somehow... :(

### Versions

Vuetify 0.14.8, VueJS 2.4.2

### What is expected ?

A modal dialog should appear.

### What is actually happening ?

No dialog appears.

### Reproduction Link

https://codepen.io/beffy72/pen/OjbJOp

**Comment by YassineGherbi** [comment]
Got the same issue..

**Comment by karlyao** [comment]
Hi, is this bug re-surfaced in V1.0.3?

**Comment by johnleider** [comment]
If you are experiencing issues, please create a new issue

**Comment by mizzao** [comment]
@smxsm btw, that doesn't seem to be the proper way to display a `v-dialog` inside a `v-data-table`. Because you are editing the global `dialog`, it's actually creating 1 dialog for each entry in the data table, or 5-10 dialogs in your case. Shouldn't you be setting `props.dialog` instead?
