### ISSUE TITLE
Activator slot on v-dialog doesn't work when its in a "wrapper" component

### ISSUE THREAD

**Issue by YassineGherbi** [vuetifyjs/vuetify#1234]
### Steps to reproduce
create a component, lets say: DeleteButton.vue.

```
<v-dialog v-model="dialog" lazy>
		<v-btn icon="icon" class="red--text" slot="activator">
			<v-icon>delete</v-icon>
		</v-btn>
		<v-card>
			<v-card-title>Weet je het zeker?</v-card-title>
			<v-card-text>
				Weet je zeker dat je deze {{name}} wilt verwijderen, deze handeling kan niet ongedaan gemaakt worden
			</v-card-text>
			<v-card-actions>
				<v-spacer></v-spacer>
				<v-btn class="darken-1" flat @click.native="dialog = false">Annuleren</v-btn>
				<v-btn class="red--text darken-1" flat @click.native="deleteConfirm()">Verwijder</v-btn>
			</v-card-actions>
		</v-card>
	</v-dialog>
```

- Paste this in as the ```<template>```.

- Import the components and refer in in the template, let's say: ```<delete-btn></delete-btn>```

- Click on the  ```<delete-btn></delete-btn>``` element/component

### Versions
```
"vue": "^2.4.2",
"vuetify": "^0.14.0",

Chome: Version 59.0.3071.115 (Official Build) (64-bit)
```

### What is expected?
The ```<v-dialog>``` should open. (Well.. the v-card inside de v-dialog)

### What is actually happening?
Nothing is happening...

### Reproduction Link
I can't reproduce it through codepen because the compiler is required..

**Comment by YassineGherbi** [comment]
i'm sorry it doesn't appear because de v-dialog is inside a v-data-table

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
