### ISSUE TITLE
[Bug Report] vuetify v-calendar dynamic daily interval does not work on safari

### ISSUE THREAD

**Issue by TTezcan** [vuetifyjs/vuetify#12342]
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.5.17
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
I Did use the Vuetify Calendar to build up a calendar. The daily interval in Day View should be different according to business opening times that day. The logic works for Firefox and Chrome. But not on Safari.
Open the Codepen.
Click into day view.
The day time range is broken with safari. On Firefox and Chrome the Codepen day view works.

### Expected Behavior
The dynamic day view intervals work on Safari browser

### Actual Behavior
The day view is broken in Safari browser

### Reproduction Link
<a href="https://codepen.io/ttezcan/pen/KKzjEMM" target="_blank">https://codepen.io/ttezcan/pen/KKzjEMM</a>

**Comment by KaelWD** [comment]
> `new Date('2020-05-19 ' + start).getHours()`

Chrome parses that as the system timezone and returns hours in the system timezone. Safari parses it as UTC and return hours in the system timezone. Use luxon or date-fns if you need to do arithmetic on dates.
