### ISSUE TITLE
[Documentation] Contributing Playground usage example

### ISSUE THREAD

**Issue by damienrobinson** [vuetifyjs/vuetify#12352]
### Problem to solve
This is my first time contributing, I noticed a couple things while trying to understand how to get started.

1. I didn't understand how to test changes using the playground. It would have been nice to have some documentation mention it, maybe in the [Contributing page](https://vuetifyjs.com/en/getting-started/contributing/#setting-up-your-environment)?
2. I am using windows and Github desktop wanted to use windows line endings I had to add `eol=lf` to the `.gitattributes`

### Proposed solution
1. Mention `Playground.vue` in Contributing guide and what it is used for
2. Add `eol=lf` to the `.gitattributes`

**Comment by MajesticPotatoe** [comment]
There is a discussion #12297 that this should be covered under. Please move this information over to that discussion and discuss there.
Playground.vue could definitely use mentioning. As for line endings, this should actually be done via git config setting `core.autocrlf input` which is also mentioned in the discussion.
