### ISSUE TITLE
[Bug Report] Drag and drop of VCalendar not working on mobile view

### ISSUE THREAD

**Issue by blexxed** [vuetifyjs/vuetify#12353]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Open chrome devtools and switch to mobile view or use an actual phone
- Drag and drop of calendar events does not work.

### Expected Behavior
Drag and drop should also work on mobile view

### Actual Behavior
Drag and drop does not work on mobile view

### Reproduction Link
<a href="https://codepen.io/blexxed/pen/ExKqqOz" target="_blank">https://codepen.io/blexxed/pen/ExKqqOz</a>

### Other comments
Also can be reproduced in Vuetify documentation https://vuetifyjs.com/en/components/calendars/#drag-and-drop

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
