### ISSUE TITLE
[Bug Report] Error text for v-text-field does not use correct error color when different theme is applied to component than rest of app

### ISSUE THREAD

**Issue by mathew-ferry13** [vuetifyjs/vuetify#12367]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.7

### Steps to reproduce
Enter an invalid email in form (I've been using `A`)

### Expected Behavior
The error message color is blue because that is what is defined as the dark theme error color

### Actual Behavior
The error message color is green (using light theme error color)

### Reproduction Link
<a href="https://codepen.io/mferry13/pen/BazBeNd?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F" target="_blank">https://codepen.io/mferry13/pen/BazBeNd?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F</a>

**Comment by KaelWD** [comment]
This may be possible in v3 (#10985). Currently CSS is only generated for one globally active theme, the themes.light/dark option was kinda tacked on in v2 as an alternative to manually replacing `$vuetify.theme` when switching to dark mode.
