### ISSUE TITLE
v-select warning non-primitive value as key

### ISSUE THREAD

**Issue by tomeragain** [vuetifyjs/vuetify#1236]
### Steps to reproduce
plain select example  from documentation

### Versions
0.14 on previous version it was working like a charm

### What is expected ?

not see the warning:  [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

### What is actually happening ?

Displaying the warning (in console of you inspect)
If you test directly from a plain vuejs it works
but using a project creates from vue-cli is when happens

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
