### ISSUE TITLE
[Feature Request] 'return-object' prop for Color Picker

### ISSUE THREAD

**Issue by egeersoz** [vuetifyjs/vuetify#12368]
### Problem to solve
The current behavior seems to be:

1. If the color picker's starting model is null, then when the user selects the color, the model becomes an object with the various representations of the selected color (hex, hexa, rgb etc. as props on the object).
2. If the original model is a string, then selecting a color replaces that string with a string for the current 'mode'.

This is confusing and requires adding extra code to deal with the inconsistency.

### Proposed solution
It should be possible to tell the component to not return an object, which should make it always return the color as a string.

**Comment by KaelWD** [comment]
v3's color picker returns the same format you passed in, or hex(a) if null.
