### ISSUE TITLE
[Bug Report] v-text-field - wrapper.props() must be called on a Vue instance

### ISSUE THREAD

**Issue by markabruce** [vuetifyjs/vuetify#12362]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.11
**Browsers:** Other
**OS:** Mac OS 10.15.0

### Steps to reproduce
1. Create a component with a `v-text-field`
2. Create a unit test (Jest) that mounts the component with the `v-text-field`
3. Find the `v-text-field` in the wrapper (perhaps with an id)
4. Try to get props() from the `v-text-field` wrapper from step 3
5. Test falls over with `[vue-test-utils]: wrapper.props() must be called on a Vue instance`

If you follow the same steps for a `v-button`, it works correctly.

### Expected Behavior
I would expect `v-text-field` to be a Vue instance where I can access `props` with `wrapper.props()`

### Actual Behavior
The `v-text-field` is not considered a Vue instance and the test falls over when trying to access `wrapper.props()`

### Reproduction Link
<a href="https://github.com/markabruce/vuetify-v-text-field-issue" target="_blank">https://github.com/markabruce/vuetify-v-text-field-issue</a>

**Comment by KaelWD** [comment]
v-text-field passes all attributes to the `<input>` element for some reason, including `id`. The only attribute applied to the root element is `class` so that's all you can use to select it in tests. This will probably change in vuetify 3 but for now you just have to use classes. 

See also #10988

**Comment by markabruce** [comment]
Hi @KaelWD ,

Thank you for your prompt response. 

Took me a second to understand you, but I am with you now.

For clarity, the `v-text-field` passed down the 'id' to the actual `<input />`, meaning that when I ran my find on the id, I was just getting the `<input />` element and not the actual Vue instance of `v-text-field`. 

This meant that I had to find the `v-text-field` like the below instead:

```
wrapper.find('.v-text-field');
```

This is because the class is the only thing I can identify the root with which is in fact the Vue instance of `v-text-field`.

```
<div class="v-input theme--light v-text-field">
    <div class="v-input__control">
        <div class="v-input__slot">
            <div class="v-text-field__slot"><input id="emailTextField" type="text"></div>
        </div>
        <div class="v-text-field__details">
            <div class="v-messages theme--light">
                <transition-group-stub tag="div" name="message-transition" class="v-messages__wrapper"></transition-group-stub>
            </div>
        </div>
    </div>
</div>
```

Thanks for your help.

**Comment by KaelWD** [comment]
That's right. If you need to uniquely identify a field you'll have to give it a class instead of an ID.

**Comment by markabruce** [comment]
@KaelWD Just one more thing... 

It appears that props is an empty object unless I embed the v-text-field in a `<div>`, is that expected behaviour? 

Cheers!
