### ISSUE TITLE
[Feature Request] v-combobox chip clear item icon property is missing

### ISSUE THREAD

**Issue by neuronetio** [vuetifyjs/vuetify#12365]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.135
**OS:** Linux x86_64

### Steps to reproduce
There is no property to set chips clear icon. Useful when you are using custom icons.

Where I can change this icon?
![image](https://user-images.githubusercontent.com/25027696/95210109-6e0d3380-07eb-11eb-8abf-d8ed006ee67f.png)

### Expected Behavior
chips-clear-icon?

### Actual Behavior
none

### Reproduction Link
<a href="https://codesandbox.io/s/shy-wave-hfk4x?file=/src/App.vue" target="_blank">https://codesandbox.io/s/shy-wave-hfk4x?file=/src/App.vue</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/6d268193d31b5bce46edafdcb1647291ee257457/packages/vuetify/src/services/icons/presets/mdi.ts#L7

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
