### ISSUE TITLE
[Bug Report] v-tooltip ARIA attributes

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#12360]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
create a tooltip

### Expected Behavior
Tooltip activator has aria attributes as stated in https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-22

### Actual Behavior
Activator has `role="button"` which
- seems to be wrong
- adds unnecessary `cursor: pointer` to the activator

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/wvWwmgZ" target="_blank">https://codepen.io/jkarczm/pen/wvWwmgZ</a>

**Comment by ricardovanlaarhoven** [comment]
I thought this was an issue i could easily pickup, but the VTooltip uses the activator mixin.
And the activator mixin adds to role button to it's activator. So perhaps this is an issue on more components?

Should this be changed only for VTooltip? And should the exception be made inside the activator mixin?
Or should this be changed for the activator mixin globally on everything that is not an button?

**Comment by jacekkarczmarczyk** [comment]
A solution that I have in mind would be to create a mixin factory, a function that has some argument telling if it's a "tooltip-like" activator or not and returning the propely adjusted mixin

**Comment by KaelWD** [comment]
Or override the `genActivatorAttributes` method.

**Comment by KaelWD** [comment]
Or base it on `openOnHover`
