### ISSUE TITLE
[Feature Request] v-slide-group scrollable 

### ISSUE THREAD

**Issue by WilliamColmenares** [vuetifyjs/vuetify#12374]
### Problem to solve
Using v-slide-group you can scroll touch events or with arrows that are shown by default when the container is overflowing, but this causes issues when is not a touch-capable device and is a small screen (for example a 13" inch laptop in half screen mode). A lot of customization needs to be made in order to improve UX using this component. 

### Proposed solution
make the component scrollable and check if the device is touch-capable, hide arrows by default would be great and give a nicer look.

I added custom styling to arrows to avoid show them if they're disabled, but it's a little buggy (when on touch-capable devices I swipe all way to the right shows the prev icon when it shouldn't)
```
.v-slide-group__prev {
  position: absolute;
  top: 50%;
  background-color: rgba(0, 0, 0, 0.01);
  background-image: linear-gradient(
    to left,
    rgba(0, 0, 0, 0.011),
    rgba(0, 0, 0, 0.35)
  );
  left: 0;
  transform: translate(0, -120px);
}
.v-slide-group__next {
  position: absolute;
  top: 50%;
  background-color: rgba(0, 0, 0, 0.01);
  background-image: linear-gradient(
    to right,
    rgba(0, 0, 0, 0.011),
    rgba(0, 0, 0, 0.35)
  );
  right: 0;
  transform: translate(0, -120px);
}

.v-slide-group__next--disabled {
  display: none;
}
.v-slide-group__prev--disabled {
  display: none;
}
```
So, I ended up adding a computed property to check if it's a touch-capable device (most likely a phone or tablet) to hide arrows by default adding a class with display:none

```
isTouchCapable() {
      return (
        !!("ontouchstart" in window || navigator.maxTouchPoints) &&
        this.$vuetify.breakpoint.width < 750
      );
    }
```
Those are the ideas I came up with so far because I didn't want to deal with the scroll animation on toggle of the v-slide-item.

**Comment by johnleider** [comment]
This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
