### ISSUE TITLE
[Bug Report] DataTable Sorting Wrong

### ISSUE THREAD

**Issue by sknithishs** [vuetifyjs/vuetify#12375]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.11
**Browsers:** Firefox 81.0
**OS:** Windows 10

### Steps to reproduce
Click on Last percent change Header to sort

### Expected Behavior
Sorting with displayed item from the array

### Actual Behavior
Sorted by first value in the array

### Reproduction Link
<a href="https://codepen.io/skns/pen/jOrOdBz" target="_blank">https://codepen.io/skns/pen/jOrOdBz</a>

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/95427774-5d260480-0948-11eb-91cd-e18f0b1bcf1a.png)

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by sknithishs** [comment]
Isn't it the intended action it should perform?

**Comment by nekosaur** [comment]
How would the v-data-table know what you are choosing to show in a column cell? You need to either transform the array into a single value before sending it to the v-data-table, or use a custom sorting function.
