### ISSUE TITLE
[Documentation] Can't close v-select with multiple options

### ISSUE THREAD

**Issue by Nes-si** [vuetifyjs/vuetify#12380]
### Environment

**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.14.6

### Steps to reproduce
Just open select control and try to close it. Clicking inside, clicking outside, pressing Esc doesn't work. [Example](https://monosnap.com/file/rTzBDLjDvxP3UJeRo0bydCqqD6uKAB)

### Expected Behavior
Can close

### Actual Behavior
Can't close

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/selects/#light" target="_blank">https://vuetifyjs.com/en/components/selects/#light</a>

**Comment by MajesticPotatoe** [comment]
Resolved 5e3c184
