### ISSUE TITLE
[Feature Request] VLazy prerender-spa support

### ISSUE THREAD

**Issue by camhart** [vuetifyjs/vuetify#12389]
### Problem to solve
VLazy doesn't appear to support server side rendering.

### Proposed solution
I've attempted to follow the instructions at https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions but it doesn't appear to resolve the issue.

I keep getting this error:
```
vue.runtime.esm.js:4484 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.gi [as appendChild] (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:42110)
    at y (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:44729)
    at p (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:44073)
    at b (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:44815)
    at L (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:48100)
    at L (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:48035)
    at a.__patch__ (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:48462)
    at a.In.t._update (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:27008)
    at a.r (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:27814)
    at nr.get (http://localhost:5000/js/chunk-vendors.bbf44306.js:7:30684)
```

I'm using `prerender-spa-plugin` which uses SSR to produce SEO friendly static versions of the page on load.

**Comment by KaelWD** [comment]
prerender-spa-plugin doesn't use SSR, it renders the page in a browser then saves the resulting html. Using this as a base for SSR hydration is very likely to cause errors.

**Comment by camhart** [comment]
> prerender-spa-plugin doesn't use SSR, it renders the page in a browser then saves the resulting html. Using this as a base for SSR hydration is very likely to cause errors.

Ah, thanks for correcting me.  I simply want to make the site readable by googlebot (and other search engines), so my SEO results improve.  Do you have any suggestions?

**Comment by KaelWD** [comment]
Goiglebot can render SPAs if they aren't too slow, use [fetch as google](https://www.google.com/webmasters/tools/googlebot-fetch) to check. Our documentation uses a custom prerenderer based on vue-server-renderer, mostly just to get proper titles in Twitter and discord embeds. We're hoping to make this available as a standalone package at some point: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/build/prerender.js

**Comment by camhart** [comment]
Thanks for that!  Further research indicates that even though Googlebot can read the page, it'll rank lower because of the delay...  I may need to take a closer look at SSR.

I'd love to have a static renderer that's compatible with vuetify.  It seems like everywhere (including https://ssr.vuejs.org/#why-ssr) recommends prerender-spa-plugin.  Does the prerender.js file you suggested pretender most of the page?  Or just small portions to populate Twitter/discord details?

**Comment by KaelWD** [comment]
Yes it renders the entire page. It's full SSR except it saves the result to disk at build time instead of running on the server. prerender-spa-plugin plugin was written by a Vue core team member and works fine for static content, but because it just looks like a web browser we can't conditionally render things like with real SSR.

**Comment by camhart** [comment]
In case anyone comes across this issue looking for help, nuxt.js supports prerendering static content using SSR techniques that appear to place nicely with vuetify.  The easiest way to get started with nuxt.js and vuetify is just to do `yarn create nuxt-app {appname}` then it'll ask you if you want to use vuetify as one of the questions.  I found 3-4 different "setup" guides/plugins/etc, none of them worked except for the nuxt.js default create project process.
