### ISSUE TITLE
[Feature Request] add to all slots of the component v-treeview hovered parameter

### ISSUE THREAD

**Issue by businka** [vuetifyjs/vuetify#12392]
### Problem to solve
you can show elements in slots only if the cursor is hovering over the timeline, for example, the delete button.adding a v-hover to a slot does not solve this problem.

### Proposed solution
add the hovered parameter to all slots

**Comment by KaelWD** [comment]
You should do this with CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/:hover
