### ISSUE TITLE
[Bug Report] v-data-table selection continues to refer to hidden items when current items changes

### ISSUE THREAD

**Issue by davidkhess** [vuetifyjs/vuetify#12399]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.11
**Browsers:** Safari 14.0
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Click on the header checkbox to select all rows.
2. Note the selection reflected below the table.
3. Enter "3" in the search field.

### Expected Behavior
Since the user only sees that a single row is selected, the selection should be updated to remove any rows that are no longer in the current items when current items changes.

### Actual Behavior
The selection doesn't update and hidden rows are still selected. Ideally, either rows that get hidden are removed from the selection or the selection is reset to [] if the current items changes.

### Reproduction Link
<a href="https://codepen.io/dhess/pen/eYzNydz" target="_blank">https://codepen.io/dhess/pen/eYzNydz</a>

### Other comments
This might fall in a gray area and need some more finessed UX solution but at the moment, it can cause unexpected results for the user because the visible selection does not match the selection reflected in the API.

My workaround is to reset the selection to [] if the current-items event fires.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
