### ISSUE TITLE
Color changes with the new release

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuetifyjs/vuetify#124]
The old blue now is a dark blue, also all my all body went dark grey. 

What is going on?

**Comment by johnleider** [comment]
It sounds like you aren't using v-content to wrap your content. It is required.

**Comment by FrancescoSaverioZuppichini** [comment]
What do you mean? Why the body is grey by default now?

**Comment by johnleider** [comment]
Because of improved non fixed sidebar functionality.

**Comment by johnleider** [comment]
Did v-content fix this for you?

**Comment by SystemZ** [comment]
I'm already using v-content, I did something wrong? I built it with 0.8.7 docs:
https://github.com/lvlup-pro/spawn-frontend-material/blob/0904d7529f55f2861b1765c3d145f9601d0e751f/src/App.vue#L57

0.8.8 seems to have some breaking changes, maybe it should be 0.9.0 version?

**Comment by johnleider** [comment]
This is pre release. Every release will have the potential of breaking changes.

**Comment by johnleider** [comment]
For all future releases, semver will be followed 100%. If you still have issues with the colors, create a new issue.
