### ISSUE TITLE
[Bug Report] V-App-Bar with inverted-scroll freezes in position when navigating to different page

### ISSUE THREAD

**Issue by sudhakarselva** [vuetifyjs/vuetify#12405]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux

### Steps to reproduce
1.Add v-app-bar with app, inverted-scroll and :scroll-threshold="300" prop applied
2. scroll down , once v-app-bar appeared, naviage to about page by clicking link in the v-app-bar
3. Now u can see, even though page is at the top position, v-app-bar is visible and inverted scroll functionality no longer works till i refresh

### Expected Behavior
v-app-bar should restore to initial state(hidden) when navigated to another page with scroll postion is at the top

### Actual Behavior
v-app-bar freezes in position in about page and inverted scroll doesnt work once navigate to about page

### Reproduction Link
<a href="https://codesandbox.io/s/silent-snow-k9elc?file=/pages/index.vue" target="_blank">https://codesandbox.io/s/silent-snow-k9elc?file=/pages/index.vue</a>

**Comment by johnleider** [comment]
I can confirm that this is no longer an issue in v3.
