### ISSUE TITLE
[Documentation] v1.vuetifyjs.com is down

### ISSUE THREAD

**Issue by yuanhao-li** [vuetifyjs/vuetify#12406]
### Environment
**Vuetify Version:** 1.0.19
**Last working version:** 1.0.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
https://v1.vuetifyjs.com

### Expected Behavior
online

### Actual Behavior
down

### Reproduction Link
<a href="https://v1.vuetifyjs.com" target="_blank">https://v1.vuetifyjs.com</a>

**Comment by MajesticPotatoe** [comment]
duplicate #12042
