### ISSUE TITLE
[Documentation] The prepend Slot feature is available in the the document of VFileInput , but it is not actually supported

### ISSUE THREAD

**Issue by cn1001wang** [vuetifyjs/vuetify#12403]
### Environment

**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
```
    <v-file-input multiple label="File input">
      <v-icon slot="append" color="red">mdi-plus</v-icon>
      <v-icon slot="prepend" color="green">mdi-minus</v-icon>
    </v-file-input>
```

### Expected Behavior
prepend insert mdi-minus

### Actual Behavior
mdi-minusis not work

### Reproduction Link
<a href="https://v2.vuetifyjs.com/en/components/file-inputs/" target="_blank">https://v2.vuetifyjs.com/en/components/file-inputs/</a>

### Other comments
```
    genPrependSlot() {
      if (!this.prependIcon) return null;
      const icon = this.genIcon('prepend', () => {
        this.$refs.input.click();
      });
      return this.genSlot('prepend', 'outer', [icon]);
    },
```
The writing method in the source code does not support this feature, but prepend feature is support in the document

**Comment by MajesticPotatoe** [comment]
duplicate #9580
