### ISSUE TITLE
[Bug Report] Data table paginate triggers twice when loading / searching

### ISSUE THREAD

**Issue by SalaheddineChafik** [vuetifyjs/vuetify#12400]
### Environment
**Vuetify Version:** 2.3.0
**Last working version:** 2.2.0
**Vue Version:** 3.0.0
**Browsers:** Edge 86.0.622.38
**OS:** Windows 10

### Steps to reproduce
use data table pagination with vuetify version 2.3.0 +

### Expected Behavior
Only trigger pagination once

### Actual Behavior
Triggers Pagination 2 times

### Reproduction Link
<a href="https://codepen.io/salaheddine-chafik/pen/ZEOGxJN" target="_blank">https://codepen.io/salaheddine-chafik/pen/ZEOGxJN</a>

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
