### ISSUE TITLE
[Feature Request] Card Reveal Panel for Displaying More Info for a Card

### ISSUE THREAD

**Issue by sbosell** [vuetifyjs/vuetify#1240]
There seems to be pretty good coverage of cards but the ability to easily show a revealed panel is missing.   This will allow the user to:

* Configure some settings for a card
* Provide extra information for a card without having to browse somewhere else

I don't think this is an edge case, it is potentially useful for any card.

This is demonstrated in the Card Reveal Section here: http://materializecss.com/cards.html

Demo Video: https://db.tt/mNyIizI1QP

| Default | Open |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1896962/28952428-b6730f56-7896-11e7-9c29-508f292d80bd.png)  | ![image](https://user-images.githubusercontent.com/1896962/28952432-bc0dd07c-7896-11e7-8c52-ec91abb2a6fd.png) |

**Comment by johnleider** [comment]
I'm pushing this to v1.2 as it is more in line with targeted updates.

**Comment by jtorfs01** [comment]
Hi, is this feature still being considered for a future release?

**Comment by KaelWD** [comment]
This can be implemented with v-expand-transition. There's a similar example opening on hover, just needs modifying to toggle on click instead: https://vuetifyjs.com/en/components/hover/#transition
