### ISSUE TITLE
[Bug Report]  The top of letters and icons is cut off

### ISSUE THREAD

**Issue by RP-KentaroAoki** [vuetifyjs/vuetify#12401]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Use hint in v-text-field 
    - Reproduce relatively in Japanese
    - It's happening at 90-100% in the browser zoom

### Expected Behavior
The upper part cannot be cut off
![screenshot](https://user-images.githubusercontent.com/69883661/95694875-3a109300-0c6f-11eb-8874-a90741cc1f3a.png)

### Actual Behavior
The upper part is cut off

### Reproduction Link
<a href="https://codepen.io/KentaroAoki/pen/LYZVdmb?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F" target="_blank">https://codepen.io/KentaroAoki/pen/LYZVdmb?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F</a>

### Other
The top of the icon using v-icon can be cut off
https://codepen.io/KentaroAoki/pen/abZOYQN
![screenshot](https://user-images.githubusercontent.com/69883661/95695415-b60bda80-0c71-11eb-8dea-b5edd997c496.png)
![dense](https://user-images.githubusercontent.com/69883661/95926955-85a27880-0df8-11eb-92ac-bbff8475c764.png)

**Comment by RP-KentaroAoki** [comment]
Is it because overflow: hidden is specified in the element?

Also, the font-family applied to mac and Windows is different (because the OS is different), and Windows seems to reproduce because the font is larger.

It is recognized as a bug by the user that it can be cut off, so please take action.

**Comment by ricardovanlaarhoven** [comment]
Weird thing is that the font-size is the same variable as the line height, so they are both `12px`
Making the line height `13px` is fixing this issue. But i don't know if it's wise to do this for all of vuetify

For now changing the sass variable `$messages-line-height` to 13px is a workaround
