### ISSUE TITLE
[Documentation] Tab items example incorrect for vertical tabs

### ISSUE THREAD

**Issue by edwardsph** [vuetifyjs/vuetify#12413]
### Environment

**Browsers:** Edge 86.0.622.38
**OS:** Windows 10

### Steps to reproduce
Modify the codepen example to add "vertical" to v-tabs

### Expected Behavior
The tabs should appear as a vertical list to the left of the items.

### Actual Behavior
The tabs appear as a vertical list but above the tab items.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tabs/#tab-items" target="_blank">https://vuetifyjs.com/en/components/tabs/#tab-items</a>

### Other comments
The v-tab-items element should be a child of v-tabs not a sibling.

**Comment by KaelWD** [comment]
This example is demonstrating that `v-tabs` and `v-tabs-items` can be separated and kept in sync with `v-model`. There's already an example of vertical tabs with everything being children of `v-tabs`: https://vuetifyjs.com/en/components/tabs/#vertical-tabs
