### ISSUE TITLE
[Feature Request] Vuetify Expansion Panel: How to change header icons to Plus and minus icons

### ISSUE THREAD

**Issue by bhavinichauhan-easternts** [vuetifyjs/vuetify#12418]
### Problem to solve
Vuetify Expansion Panel: How to change header icons to the plus icon when the expansion content is closed and minus icon when the expansion content is open

### Proposed solution
I find solution that we can put only one custom icon and it can be rotated when the expansion content is opened and closed.

**Comment by jacekkarczmarczyk** [comment]
`v-expansion-panel-header` has `expand-icon` and `disable-icon-rotate` props, you can change the value of `expand-icon` when panel is opened

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by shubh47-dddd** [comment]
how can we change the expand-icon when panel is open?

**Comment by leonhail-nell** [comment]
You can put model on the expansion panels.

<v-expansion-panels flat :accordion="true" v-model="panels" multiple>

   <v-expansion-panel
        v-for="(loop, index) in loops"
        :key="loop.name">

          <v-expansion-panel-header>

              <template v-slot:actions>
                  <v-icon color="primary" >
                      {{ panels.includes(index) ? 'mdi-minus' : 'mdi-plus' }}
                  </v-icon>
              </template>

          </v-expansion-panel-header>

  </v-expansion-panel>

</v-expansion-panels>

**Comment by PandaBalls** [comment]
How to change the expansion-panel expand-icon size? v-icon--size-small works in Browser, but how to set it in vuetify?
