### ISSUE TITLE
[Feature Request] VSelect list item custom key

### ISSUE THREAD

**Issue by Glandos** [vuetifyjs/vuetify#12410]
### Problem to solve
In `VSelect` and derived components using `VSelectList`, menu items are generated with an id depending on the current `_uid` and the index of the item.
However, with `VAutocomplete`, item array can dynamically change, and components will be recreated every time.
I currently have an item that can load external resource depending on the input, so recreating components is costly.
I'd like to evaluate the solution of providing a key for the item, so that Vue internals reuse components in a smarter way.

### Proposed solution
If I understand correctly, [`VSelectList`](https://github.com/vuetifyjs/vuetify/blob/268fb61dda11a5e84434e3a4bd27d2acff226b13/packages/vuetify/src/components/VSelect/VSelectList.ts#L161) must be updated to use a user defined key.

**Comment by KaelWD** [comment]
Do you have an example of how this custom item is used?

**Comment by Glandos** [comment]
https://codesandbox.io/s/vselect-custom-key-m57ok?file=/src/components/Item.vue

I hope this will be clear enough. Each item is an instance of `Item` having an `id` property, and which is logging its creation and change of `id` property. As an example, a `loadData` (using a delayed callback) call is done in both situation, to illustrate the fact that a lengthy operation is needed to display the component.

If you first open the menu by focusing the input field, you'll notice that every visible items will be loading for ½ second. If you type `1`, then the `I'm the item 1` will be loading, because it's internal `id` prop changed (from 0 to 1), so it has to reload.

Instead, I'd like to provide my own key to hint Vue.js that the item could be reused using my own key, instead of the index of the item in the menu.

**Comment by KaelWD** [comment]
It isn't because of the ID, VSelectList doesn't provide a key so vue just uses the index. You can already provide your own key in the slot:
```html
<template #item="{ item, attrs, on }">
  <v-list-item v-bind="attrs" v-on="on" :key="item.id">
    <Item :id="item.id" />
  </v-list-item>
</template>
```
Note that this won't work if you make the root node of `Item` a `v-list-item`, it looks at the tag name to determine if it needs to render its own `v-list-item` or not. 

We used to stringify the item's ID to use as an ID but people do dumb shit like use an object as the ID so instead of telling them not to it was just changed.

**Comment by tongjiaqi** [comment]
https://vuetifyjs.com/    **Website not accessible！！！！**

**Comment by Glandos** [comment]
OK, now I know why Vuetify is popular. When developers take the time to understand and answer precisely with good solution, it's worthy.

So the workaround is indeed (for external readers) to use a `v-list-item` otherwise `VSelectList` will create one without `key`.

@KaelWD I let this opened if you plan to implement a new prop in the future, but for me, it can be closed.

**Comment by KaelWD** [comment]
> if you plan to implement a new prop in the future

It makes sense to me to just use `item-value` as the key if it isn't an object.
