### ISSUE TITLE
[Bug Report] VMenu open-on-hover does not close-on-content-click in mobile

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#12412]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Windows 10

### Steps to reproduce
1. Open codepen on mobile.
2. Click on the dropdown menu.
3. Click any list item.

### Expected Behavior
Menu will close when any list item is clicked on mobile.

### Actual Behavior
Menu will only close when any list item is clicked the second time on mobile.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/MWeaLqO" target="_blank">https://codepen.io/andrewspy/pen/MWeaLqO</a>

### Other comments
Problem only occurs on mobile browser. Desktop works as expected.

**Comment by kenji7157** [comment]
It seems to occur when open-on-hover is enabled.  

![Kapture 2020-11-06 at 22 26 29](https://user-images.githubusercontent.com/18192657/98371203-221a0c80-207f-11eb-8628-0b5e76035d9e.gif)
