### ISSUE TITLE
[Bug Report] [Safari] v-img with svg files results in a warning. [Vuetify] Failed to decode image, trying to render anyway. Original error: Invalid image type.

### ISSUE THREAD

**Issue by alekstar79** [vuetifyjs/vuetify#12425]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
It is very easy to reproduce this issue, just set the svg file as the source for v-img and open it in Safary on your iPhone.

### Expected Behavior
To display image

### Actual Behavior
The image is displayed but a warning is displayed in the console.

### Reproduction Link
<a href="https://codepen.io/alekstar79/pen/BazKKqa?editors=1010" target="_blank">https://codepen.io/alekstar79/pen/BazKKqa?editors=1010</a>

### Other comments
This issue already existed [Issues #4969](https://github.com/vuetifyjs/vuetify/issues/4969) but for some reason it was closed as resolved.

**Comment by johnleider** [comment]
Possible v2.x fix, depending upon what @KaelWD thinks.
