### ISSUE TITLE
[Bug Report] Vuetify Expansion Panel: How to change header icons to the plus icon when the expansion content is closed and minus icon when the expansion content is open

### ISSUE THREAD

**Issue by bhavinichauhan-easternts** [vuetifyjs/vuetify#12422]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
1. Vuetify Expansion Panel
2. Change the header icon

### Expected Behavior
Vuetify Expansion Panel: header icons to the plus icon when the expansion content is closed and minus icon when the expansion content is open

### Actual Behavior
Not able to change Plus minus icon

### Reproduction Link
<a href="https://codepen.io/etsbhavini/pen/vYKGOpv?editable=true&editors=101%3Dhttps%3A%2F%2Fv15.vuetifyjs.com%2F" target="_blank">https://codepen.io/etsbhavini/pen/vYKGOpv?editable=true&editors=101%3Dhttps%3A%2F%2Fv15.vuetifyjs.com%2F</a>

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
