### ISSUE TITLE
Website page title typo.

### ISSUE THREAD

**Issue by onimatrix81** [vuetifyjs/vuetify#1242]
Go to https://vuetifyjs.com/style/colors, the page title has the word "pallete" in it. Dictionary.com only has pallette and palette in it. "Pallette" apparently is some type of medieval armour :)

### Reproduction Link
https://vuetifyjs.com/style/colors

**Comment by johnleider** [comment]
Fixed with https://github.com/vuetifyjs/docs/commit/490406a0d0ef77ce124c585c7f885d68bb8e596b
