### ISSUE TITLE
[Bug Report] v-tooltip doesn't work with selection controls

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#12436]
### Environment
**Vuetify Version:** 2.3.7
**Last working version:** 2.3.6
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
```html
<v-tooltip>
  <v-switch />
</v-tooltip>
```

### Expected Behavior
Tooltip should be visible on hover

### Actual Behavior
Tooltip is not visible on hover

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/WNxxNyj" target="_blank">https://codepen.io/jkarczm/pen/WNxxNyj</a>

### Other comments
2.3.6: https://codepen.io/jkarczm/pen/RwRRwJN

https://github.com/vuetifyjs/vuetify/compare/v2.3.6...v2.3.7

Probably caused by https://github.com/vuetifyjs/vuetify/commit/f055c3627f76fdd9f7b966dd9a6ba1868401a325

**Comment by KaelWD** [comment]
This was removed from rippleable and only added back to VRadio: https://github.com/vuetifyjs/vuetify/commit/f055c3627f76fdd9f7b966dd9a6ba1868401a325#diff-70a7cd971468a5bb36f9986d0ba90b6868ed650e6856d089b28c00e8c4c7bdc4L30

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNq1UctuwjAQ/BXLvRJbopUqoRTR78AcHMcVLvFD9hJaofx7105BAQ5waH2yZ2dnZr3rI30PgfV7TRe0Bm1DJ0EvhSPl1H0F3ndgAgEfzjAWTlTyJBWYXoKPb4IeSYg+JDIIOiEXHbXVatf4L9JXjXEtkgtVUMKnuvwmA4IpSLdsZKx5uZ3T8XO8gk06/i53OhhQ239LfdFaJxVNALzlwu+Dzmhn3C6xz+QdbulYRqUqYYoFWY+ygm4BQlpwrlqHzFZ3po/MaeAuWI77BfPxvXpmczbnrUlwgqpONokVsay0EW5AQ2ODj1BZGa5cx0JxLkjGUCm/70RYIY3HvQNjddV6W7K8vI5hJjjTyVZN9IekI6oIOpv45MQPeN0bFy1upDn69TpWUbtWRx0fHemq7WKsq9rNaNl+yD8+zOjYh39fQtPND4LpKgw=
