### ISSUE TITLE
Increase z-index of dialog

### ISSUE THREAD

**Issue by eyeruleall** [vuetifyjs/vuetify#1243]
I think you should change the z-index of the dialog component to a much higher level. It currently shows under certain components. Attached is a screenshot of a v-select with a button in the dropdown that activates a dialog. The dialog is shown under the drop-down list items.

Class menu__content has a z-index of 6 (for the drop-down list)
Class dialog__content has a z-index of 5 (for the dialog) and should be higher than any other component's z-index value.

![Dialog under select list item](https://user-images.githubusercontent.com/9446227/28969881-5bd37bfe-78f4-11e7-856b-09eaed237181.png)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
