### ISSUE TITLE
[Bug Report] Edit Dialog - Slow Typing Response when using multiple

### ISSUE THREAD

**Issue by mendela1992** [vuetifyjs/vuetify#12430]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.7

### Steps to reproduce
* Create multiples v-edit-dialog of input fields
* Double click on the dialog to edit the content
* Start typing in the input 

### Expected Behavior
Should be able to type in with no lagging

### Actual Behavior
While typing in the input of the v-edit-dialog I experience lagging

### Reproduction Link
<a href="https://codepen.io/mendela92/pen/zYBqKEx?editors=1111" target="_blank">https://codepen.io/mendela92/pen/zYBqKEx?editors=1111</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity. Also, your reproduction works fine for me.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
