### ISSUE TITLE
[Bug Report] v-menu component empty when used inside vue app inside Wordpress

### ISSUE THREAD

**Issue by hicreate** [vuetifyjs/vuetify#12432]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 3.0.1
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
1. Add Vue to Wordpress via wordpress plugin, enqueuing applicable files
2. Add Vuetify to Vue project using Vue/Cli
3. Add v-autcomplete, v-select or v-menu to project and run project

### Expected Behavior
Component based on v-menu should open as expected depending on use-case

### Actual Behavior
<div class="v-menu"></div> is empty wherever the component is deployed. As a v-select I can see the text field, dropdown arrow and label but clicking the v-select does nothing and inspecting the element I can see the element is empty (even when items are set)

### Reproduction Link
<a href="https://github.com/hicreate/sw-book-app" target="_blank">https://github.com/hicreate/sw-book-app</a>

### Other comments
I've copied working v-autocompletes, v-selects and v-menus from other projects and from the docs that all work in standalone Vue projects but as soon as I add the same components to the Vue app embedded in Wordpress this behaviour starts.

I feel it is likely due to the Vuetify app not initialising fully/properly. I had to enqueue the vuetify and css files through wordpress to get them to load in the first instance. I can see the css in the head and the js in the body when I view the page source.

**Comment by KaelWD** [comment]
> Note that “reproduction steps” should be a series of actions another developer should take after clicking your reproduction link, not a recollection of how you discovered the bug.

**Comment by hicreate** [comment]
> > Note that “reproduction steps” should be a series of actions another developer should take after clicking your reproduction link, not a recollection of how you discovered the bug.

@KaelWD those are the steps to reproduce? does it need to prescriptively dictate how to add vue to the project, how to add vuetify to the project? etc.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
