### ISSUE TITLE
[Bug Report] v-calendar weekly view current date marker overlap on mobile view

### ISSUE THREAD

**Issue by flpgst** [vuetifyjs/vuetify#12449]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** Firefox 81.0
**OS:** Ubuntu undefined

### Steps to reproduce
Just change to mobile view

### Expected Behavior
The current date marker needs to decrease size to fit into it's own slot day at XS breakpoint

### Actual Behavior
The current date marker doesn't change it's size in any breakpoint, in resolutions smaller then 520px horizontally that marker overrun to the date at it's right side

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars/#type-week" target="_blank">https://vuetifyjs.com/en/components/calendars/#type-week</a>

**Comment by MajesticPotatoe** [comment]
Looks more like a bug bug than a documentation issue.
