### ISSUE TITLE
[Bug Report] V-Treeview selected nodes are deselected when expanding a folder on independant

### ISSUE THREAD

**Issue by JonathanYoung319** [vuetifyjs/vuetify#12450]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 3.0.1
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Steps to reproduce:
1. Expand Root1
2. Select Root 2
3. Select Root 3

Root 2 should be unchecked

### Expected Behavior
Root 2 and 3 should be checked

### Actual Behavior
Root 2 is unselected but Root 3 is selected

### Reproduction Link
<a href="https://codepen.io/jonathan-young/pen/rNLOQNZ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F&fbclid=IwAR0xHuf9SfVoY7Pw9l0nmV0vJ3CNDUzCikgKlNrA7tmr57v7mbUEFE1hnxo" target="_blank">https://codepen.io/jonathan-young/pen/rNLOQNZ?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F&fbclid=IwAR0xHuf9SfVoY7Pw9l0nmV0vJ3CNDUzCikgKlNrA7tmr57v7mbUEFE1hnxo</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
