### ISSUE TITLE
[Bug Report] iPadOS 14 v-text-field border-color currentColor glitch in Safari 14+ browser.

### ISSUE THREAD

**Issue by kunukn** [vuetifyjs/vuetify#12455]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Insert number 1 one by one until the value is 11111.
Then delete one by one until the input field is empty.

### Expected Behavior
Border colors are correct blue or red.

### Actual Behavior
Border colors are not correct.

### Reproduction Link

<a href="https://codesandbox.io/s/vuetify-2-v-text-field-72nn4?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-2-v-text-field-72nn4?file=/src/App.vue</a>

<a href="https://codesandbox.io/s/vuetify-2-tsm70?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-2-tsm70?file=/src/App.vue</a>

### Other comments
The Safari 13.4+ browser seems to have changed its behavior regarding currentColor on iPadOS.

Doing re-render in the browser might fix it.
The DOM-value can be correct but the paint was not updated.

Adding a specific CSS class to avoid currentColor usage also fixes it.

**Comment by kunukn** [comment]
iPad Pro 12.9 Safari 14

![image](https://user-images.githubusercontent.com/3199603/96595492-02978b80-12ec-11eb-89df-b93339613a8a.png)

![bug-v-text-field-error](https://user-images.githubusercontent.com/3199603/96595982-85b8e180-12ec-11eb-9bda-0a46d201962f.gif)

**Comment by mumanhas** [comment]
Any updates about that?

I have the same problem here, it only occurs on iOS / padOS 14, using Chrome or Safari

**Comment by mumanhas** [comment]
when validation is called multiple times with append-icon ...
![image](https://user-images.githubusercontent.com/39203526/96928029-5b9f2500-148e-11eb-9dbe-315418cd0b02.png)

**Comment by kunukn** [comment]
To be fair, Apple did some change to their browser.

I have added something like this to the global CSS as a workaround for `currentColor` being buggy on iPad.
This seems to fix it for me.

```vue
<style lang="scss">
$primary-base: #1976d2;
$error-base: #ff5252;

// Override Vuetify CSS
.v-application .v-text-field--outlined.v-input--is-focused fieldset {
  border-color: $primary-base;
  border: 2px solid $primary-base; // override currentColor
}
// Override Vuetify CSS
.v-application .error--text fieldset {
  border-color: $error-base !important;
}
</style>
```

Demo
https://codesandbox.io/s/vuetify-2-v-text-field-custom-css-added-e6sgn?file=/src/App.vue:1093-1484

**Comment by KaelWD** [comment]
This should be reported to webkit as it's a browser bug.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
