### ISSUE TITLE
[Feature Request] NVDA Screen reader reads all values as "Blank" when pressing arrow key to get value of v-select

### ISSUE THREAD

**Issue by Ben-SMS** [vuetifyjs/vuetify#12454]
### Problem to solve
- Create a component which has v-select control
- Open NVDA screen reader
- Focus on the v-select control
- Don't press the space bar to expand values of the v-select
- Use the arrow key (down/up) to select a value 
Actual result: The screen reader always read as "Blank" when a value is selected  
Note: The screen reader reads correctly if press the space bar to expand the value list before using the arroy key

### Proposed solution
Expected result: NVDA screen reader reads the selected value of v-select when using the arrow key to select a value without pressing the space bar.

**Comment by agreedSkiing** [comment]
This would be a great change if this was implemented, might also be relevant to check the html generated structure that was reported in https://github.com/vuetifyjs/vuetify/issues/14615 also

**Comment by agreedSkiing** [comment]
Might it be possible to assign the chosen value to the inputs value attribute? Or change the item to a real select list instead of load of divs with an item that I generated when the list is selected?

**Comment by Ben-SMS** [comment]
Hi John,
I noticed that this bug was marked as closed without any accompanying comments, so I'm unsure whether it has been fixed. Could you please provide more information?

Thanks.
