### ISSUE TITLE
[Bug Report] [Upgrade to 2.3.x] Snackbar is no longer displayed on screen

### ISSUE THREAD

**Issue by albertodiazdorado** [vuetifyjs/vuetify#12457]
### Environment
**Vuetify Version:** 2.3.0
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Firefox 81.0
**OS:** Linux x86_64

### Steps to reproduce
I can only imagine that this is something trivial, but I cannot really get the snackbar to work under Vuetify `2.3.x`. The repo contains a minimal example of the bug I have in my project.

Steps to reproduce:
1. `git clone https://github.com/albertodiazdorado/v-snackbar-test.git && cd v-snackbar-test`
2. `yarn install && yarn serve` --> observe working snackbar in `http://localhost:8080`
3. `yarn add vuetify@~2.3.0 && yarn serve` --> observe the snackbar no longer works

### Expected Behavior
The snackbar is displayed

### Actual Behavior
The snackbar is not displayed

### Reproduction Link
<a href="https://github.com/albertodiazdorado/v-snackbar-test" target="_blank">https://github.com/albertodiazdorado/v-snackbar-test</a>

### Other comments
The app has been built using the usuals:
```
vue create xxx
cd xxx
vue add vuetify
```

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0#user-content-upgrade-guide

> Changed the value to disable the timeout from 0 to -1.

**Comment by MajesticPotatoe** [comment]
it does work, its just you have custom styling that is causing it to be offscreen. removing this, it will appear again
```
.v-snack {
  position: static !important;
  padding: 5px;
}
```

**Comment by albertodiazdorado** [comment]
Hi @jacekkarczmarczyk , this fixes nothing. I have pushed a new commit to the repository where `timeout` is set to `10000`, to make even more obvious that the `timeout` is not the problem.

Could you re-open this, please?

**Comment by albertodiazdorado** [comment]
@MajesticPotatoe that is it. I did not find any reference to the styles of the `v-snackbar` in the upgrade guide :(

Thank you very much and have a nice day!
