### ISSUE TITLE
[Bug Report] v-image doesn't work for print only 

### ISSUE THREAD

**Issue by kosratdev** [vuetifyjs/vuetify#12453]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
When you click on the print button the image should be displayed on print dialog but will not 

### Expected Behavior
I have added an image in the sample code that has `d-none d-print-block` so that it should be displayed only for print

### Actual Behavior
I have added an image in the sample code that has `d-none d-print-block` so that it should be displayed only for print but will not display at print dialog

### Reproduction Link
<a href="https://codepen.io/kosrat-kt/pen/pobEjJy" target="_blank">https://codepen.io/kosrat-kt/pen/pobEjJy</a>

**Comment by KaelWD** [comment]
1. v-img is lazyloaded by default, the print dialog doesn't wait for it. You have to use the `eager` prop
2. v-img uses CSS `background-image` so you also need to check the "background graphics" option in the print dialog for it to display.
