### ISSUE TITLE
[Documentation] v-icon left/right props have incorrect descriptions

### ISSUE THREAD

**Issue by Hatead1** [vuetifyjs/vuetify#12466]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 7

### Steps to reproduce
Add v-btn with v-icon with "right" props.

### Expected Behavior
Places the icon on the right in button

### Actual Behavior
Places the icon on the left, overlap button text

### Reproduction Link
<a href="https://codepen.io/hatead1/pen/yLJamqq" target="_blank">https://codepen.io/hatead1/pen/yLJamqq</a>

**Comment by KaelWD** [comment]
The `right` prop doesn't change the icon's position, you use it to add the proper margins for when it is already on the right of something.

**Comment by Hatead1** [comment]
Sure?
From v-icon API:

left | boolean | false | Places the icon on the left, when used inside a button
right | boolean | false | Places the icon on the right, when used inside a button

**Comment by Hatead1** [comment]
Thanks

**Comment by Hatead1** [comment]
https://vuetifyjs.com/en/components/buttons/#loaders - it work here, icon on the right of text

**Comment by KaelWD** [comment]
Look at the order of them in the template.

**Comment by MajesticPotatoe** [comment]
Its still a valid documentation issue. The verbiage in prop descriptions is incorrect (hence the title change and docs tag).

**Comment by Hatead1** [comment]
Ok
