### ISSUE TITLE
[Feature Request] Component based direction

### ISSUE THREAD

**Issue by M-Nasab** [vuetifyjs/vuetify#12467]
### Problem to solve
Currently Vuetify components take their direction (rtl or ltr) from the global Vuetify configurations. So it is not possible to make an exception and set the direction of one component differently. With this feature we should be able to set the direction for each component separately and if no direction is specified for the component it should fallback to the direction set in Vuetify configurations.

### Proposed solution
Use the direction prop or direction style property set on each component to determine the component's direction and fallback to global config instead of just reading it from the global config.

**Comment by KaelWD** [comment]
In v3 you can wrap a section in `<v-locale-provider rtl>`
