### ISSUE TITLE
[Feature Request] Option to force data table sort back to ascending rather than null

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#1246]
I think it tends to be a confusing user experience to click a table header (third click) and have the table become un-sorted rather than resorting to ascending. 
This could be solved by having another pagination property, something like 'forceAscending', passed that would disable the un-sorting option. 
It should only be a minor change to the sort method in VDataTable.js:

      const { sortBy, descending, forceAscending } = this.computedPagination
      if (sortBy === null) {
        this.updatePagination({ sortBy: index, descending: false })
      } else if (sortBy === index && !descending) {
        this.updatePagination({ descending: true })
      } else if (sortBy !== index) {
        this.updatePagination({ sortBy: index, descending: false })
      } else if (sortBy === index && forceAscending) {
        this.updatePagination({ descending: false })
      } else {
        this.updatePagination({ sortBy: null, descending: null })
      }

### What will it allow you to do that you can't do today?
I think this functionality is more in line with what a typical user is used to. Typically when clicking a sortable header the only options are ascending and descending.
### How will it make current work-arounds straightforward?
Current work-around is to have a watch on the pagination and second pagination to track what was just sorted and set the first pagination - seems clunky. 
### What potential bugs and edge cases does it help to avoid?
None, just additional functionality

**Comment by xi-osman** [comment]
Could we also incorporate Multi-column ordering? So when your holding down shift you can have multiple sort options this website has an example. https://datatables.net/examples/basic_init/multi_col_sort.html

**Comment by nekosaur** [comment]
@xi-osman Please create a separate feature request issue
