### ISSUE TITLE
[Bug Report] Concatenate several prop of an item in a v-autocomplete to search

### ISSUE THREAD

**Issue by MarquesFlorian** [vuetifyjs/vuetify#12465]
### Environment
**Vuetify Version:** 1.1.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.99
**OS:** Linux x86_64

### Steps to reproduce
In the autocomplete, put "Company 28100"

### Expected Behavior
I would like to get item when i put a part of the name (rs) and a part of the address (ligneacheminement)

### Actual Behavior
Return nothing

### Reproduction Link
<a href="https://codepen.io/Flocondavoine/pen/zYBKVwd" target="_blank">https://codepen.io/Flocondavoine/pen/zYBKVwd</a>

### Other comments
So, I am using a component to search somes informations in an list of items (companies). Each item (company) has 3 values, a name (rs), an address (ligneacheminement) and a code(nofinesset).

Currently, i search a company with her name or her address with a filter props on the v-autocomplete.

But the problems is, if I put a name and an address in the input field,the component don't display me what I want.

An example : I want to find the company "Company Paris" which have an address like "75000 Paris". If I try "Paris" or "Company Paris" or "75000", that gonna be ok. But if I try "Paris 75000" i got nothing.

I think it's normal, but someone have an idea to get what I want to expect ?

Sorry for my english and thanks.

**Comment by jacekkarczmarczyk** [comment]
```js
facilityFilter(item, queryText, itemText) {
  const terms = queryText.toLowerCase().split(' ')

  return terms.some(term => item.rs.toLowerCase().includes(term) || item.ligneacheminement.toLowerCase().includes(term))
}
```

**Comment by MarquesFlorian** [comment]
Resolved : Filter function need to return true.
