### ISSUE TITLE
[Feature Request] Make <v-tabs> more simpel when populating from a v-for loop

### ISSUE THREAD

**Issue by bddexter** [vuetifyjs/vuetify#12479]
### Problem to solve
If you want to populate tabs from an array you have to do the loop twice. Once for the `<v-tab>` tag and again for `<v-tab-item>` tag. 

### Proposed solution
Our friends at bootstrap-vue make use of templates and you only have to do the v-for on a `<b-tab>` tag. Within the `<b-tab>` you can directly generate the title and body for each tab.

**Comment by jacekkarczmarczyk** [comment]
You can have loop in Vuetify as well

https://codepen.io/jkarczm/pen/OJXWKBM

**Comment by bddexter** [comment]
Awesome! Maybe closed!
