### ISSUE TITLE
[Bug Report] scrollToTime Not Working When Switching From Month to Day

### ISSUE THREAD

**Issue by bculpepper** [vuetifyjs/vuetify#12473]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Edge 86.0.622.48
**OS:** Mac OS 10.15.7

### Steps to reproduce
When the page loads the day is scrolled to the correct 9:00 position. Use the calendar type switch (dropdown) to switch to month and then back to day. When you get back to day the scroll position is midnight again.

### Expected Behavior
switching from month to day type scrollToTime should execute again

### Actual Behavior
switching from month to day type scrollToTime not executing

### Reproduction Link
<a href="https://codepen.io/bculpepper/pen/qBNqaKe" target="_blank">https://codepen.io/bculpepper/pen/qBNqaKe</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
