### ISSUE TITLE
Feature request: Input for tags

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#1247]
Would be really cool to have an input for tags (i.e. similar to StackOverflow). I am trying out `vue-input-tag`, which is great, but the styling is not consistent with the rest of my Vuetify app. 

Have a feature request?
=======================
- Remove the template from below and provide thoughtful commentary.

**Comment by johnleider** [comment]
This is now supported with ```v-select``` using the **tags** prop.

**Comment by piyushSinghalDemo** [comment]
one good example for vuetify input tags
"https://codepen.io/piyushSinghalDemo/pen/QJJyQy"
