### ISSUE TITLE
[Feature Request] When extending, get render

### ISSUE THREAD

**Issue by guy4hero** [vuetifyjs/vuetify#12488]
### Problem to solve
More convenient combination of components

### Proposed solution
Hello, vuetify team leaderI'm a novice from China. First of all, I'm sorry that I don't know English. This message was translated by translation software:)

When I studied vuetify and wanted to package components by myself, I didn't find a good way. Later, I looked at your code. For example, if the body of the render method of a component can be written in methods, and the render can refer to this method for rendering, then when I define a component to inherit the vuetify component, the render method can directly call the rendering method of the superclass in methods, And then assemble a new component.

**Comment by KaelWD** [comment]
This sounds like a question about architecture rather than a feature request. Please join our discord, there's a chinese channel so you don't have to use translation software. 

https://community.vuetifyjs.com/
