### ISSUE TITLE
[Bug Report] Unable to add DOM id to v-tab-item

### ISSUE THREAD

**Issue by lioneaglesolutions** [vuetifyjs/vuetify#12486]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.1
**Browsers:** Chrome 86.0.4240.111
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add an ID to a `<v-tab-item>`
`<v-tab-item id="example">`

### Expected Behavior
`<div class="v-window-item v-window-item--active" style=""  id="example">`

### Actual Behavior
`<div class="v-window-item" id="example" style="display: none;">` or the code is simply commented out

### Reproduction Link
<a href="https://codepen.io/lioneaglesolutions/pen/PozbrYB" target="_blank">https://codepen.io/lioneaglesolutions/pen/PozbrYB</a>

**Comment by KaelWD** [comment]
Tabs use `id` and `href` or `to` to determine their value. It doesn't look like this is actually documented very well, all the examples are just variations of the same layout instead of explaining how all the features work. This example uses IDs: https://vuetifyjs.com/en/components/tabs/#vertical-tabs

**Comment by lioneaglesolutions** [comment]
I can't see any example that shows `<v-tab-item id="something">` on that page. I don't see how this is working as intended when ID is listed as a prop, that controls the DOM ID when you actually use it, it breaks the functionality.

**Comment by KaelWD** [comment]
Ugh great it uses `value`. Before value was added you had to use ID and I guess it was kept for backwards compatibility.

**Comment by lioneaglesolutions** [comment]
So can we either remove the ID prop from the documentation as it's not supported, or is there a fix to allow the assigning of a DOM id?

**Comment by KaelWD** [comment]
ID is supported, you just have to set a corresponding value on the v-tab too.

**Comment by lioneaglesolutions** [comment]
@KaelWD got it - thanks. Might help to mention that in the documentation somewhere... thanks
