### ISSUE TITLE
[Bug Report] v-click-outside with child elements

### ISSUE THREAD

**Issue by kylawamg** [vuetifyjs/vuetify#12493]
### Environment
**Vuetify Version:** 2.3.15
**Last working version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Click outside the grey grid should change the test variable to "clicked" (its ok).
Click in the select and select an option changes the test variable to "clicked" too. (not ok because it is inside the grey div).
The same than select for time picker. 

### Expected Behavior
When the select or timepicker is selected, the v-click-outside directive shouldnt trigger testClick method because the elements are inside the div.

### Actual Behavior
When the select or timepicker is selected, the v-click-outside directive trigger testClick although the items are inside the div.

### Reproduction Link
<a href="https://codepen.io/Kylawamg/pen/YzWNqZG" target="_blank">https://codepen.io/Kylawamg/pen/YzWNqZG</a>

### Other comments
Thanks in advance

**Comment by KaelWD** [comment]
Menus and dialogs aren't actually children, they get moved to the root of the page to avoid being broken by positioning, overflow, and CSS cascade. The click-outside directive can take an options object with an array of additional elements that the click must be outside of to count:

```html
v-click-outside="{ handler: testClick, include }"
```

`include` should be a function that returns an array of elements.
