### ISSUE TITLE
[Feature Request] [v-data-table] Add index to item.<name> slot 

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#12495]
### Problem to solve

```
item.name - Slot to customize a specific column
{
  item: any,
  header: DataTableHeader,
  value: any
}
```

not able to access index in item.name slot

### Proposed solution
 add index to item.name slot like item slot

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10646
