### ISSUE TITLE
[Feature Request] show placeholder only on focus for text fields

### ISSUE THREAD

**Issue by WilliamColmenares** [vuetifyjs/vuetify#12499]
### Problem to solve
when setting both placeholder and label to a v-text-field, both are shown in the beginning and the label is stuck in the top.

To achieve the default behavior shown in most sites (show the placeholder only when is focused if there is a label) you would need to make use of data and custom methods to handle those change 

### Proposed solution
add a `persistent-placeholder` prop set to true on default so we can set it to false to achieve a more user-friendly behavior.

**Comment by KaelWD** [comment]
Pretty easy to implement:
![Peek 2020-11-18 01-41](https://user-images.githubusercontent.com/16421948/99404015-3f808d80-293f-11eb-9e00-7fae60f4443f.gif)
I don't like the idea of adding more props though, I'd be more inclined to make this the default behaviour at risk of maybe breaking forms expecting both to be shown.

**Comment by zetaraku** [comment]
Please take a look at #12839, this change now breaks my forms that expect both to be shown. :(
