### ISSUE TITLE
Fixed Toolbar + Main element positioning issue

### ISSUE THREAD

**Issue by waxter013** [vuetifyjs/vuetify#1249]
# Feature Request: Use margin instead of padding for fixed toolbars

## What will it allow you to do that you can't do today?

Currently, when using a fixed toolbar, the top part of the next element gets covered by the toolbar (or really the rendered `nav` element). Vuetify expects us to use the `main` element after a toolbar, as it should. The main element uses a `padding-top` equivalent to the size of a toolbar to offset the `main` element and prevent it from being covered by the toolbar.  In some cases, the padding is ignored by the browser to save screen space (like on mobile). Obviously, this is not sustainable because the top part of pages becomes inconsistently visible on different screens. 

## How will it make current work-arounds straightforward?
To get around this, we'd need to override the already written CSS every single time. Otherwise, we always run the risk of this issue.

## What potential bugs and edge cases does it help to avoid?
It prevents content from being covered up by the navbar when screen space is limited. 

## **Solution**

Use margin instead of padding. Margin doesn't vary on different screen sizes. **This is preferred.**

**Comment by rowild** [comment]
Does this mean, we have to put a class on <main>? Like "mt-5" (which is the only margin that works at the moment in my case, all the others are too small)? Or is there some automatism involved that recognizes the required top-distance automagically?

**Comment by volodalexey** [comment]
I found why this is closed.
Because you need to use `app` for `v-toolbar`:
```
<v-app>
    <v-toolbar fixed app>
    </v-toolbar>
    <v-content>
      <v-container fluid>

      </v-container>
    </v-content>
  </v-app>
```
