### ISSUE TITLE
[Feature Request] Translate DataTable header "group" text (show-group-by text)

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#12496]
### Problem to solve
Be able to translate/customize the "group" text on Data Table headers when show-group-by is active.

### Proposed solution
Create a slot to customize the "group" text on DataTable headers where show-group-by is active, being able to change the text or add icons.

**Comment by jacekkarczmarczyk** [comment]
duplicate of https://github.com/vuetifyjs/vuetify/issues/12130
