### ISSUE TITLE
SideBar not displayed

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuetifyjs/vuetify#125]
The sidebar is not displayed. Here my code:

```
<v-sidebar class="" drawer>
  <v-list dense>
    <v-list-item v-for="item in items">
      <v-list-tile>
        <v-list-tile-title v-text="item.title" />
      </v-list-tile>
    </v-list-item>
  </v-list>
</v-sidebar>
```

Also in the doc is not explained how the v-model is related to the sidebar behavior

**Comment by johnleider** [comment]
What are you expecting? It's a drawer, by default it won't show.

**Comment by FrancescoSaverioZuppichini** [comment]
You are right, my bad. It can be labeded as closed.
