### ISSUE TITLE
[Bug Report] VSwitch color not applied programmatically from a false condition

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#12506]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.27
**OS:** Windows 10

### Steps to reproduce
1. Tap multiple times anywhere on the `v-list-item` or `v-switch` itself and note that the `v-switch` color toggles from grey to blue as it should. (except for one condition, see next step).
1. Make your last tap directly on the `v-switch` itself until it is off/false (grey color). Then tap away from the `v-switch` on the `v-list-item` portion and note that the switch toggles as it should, but the color now never changes from grey to blue regardless of the number of taps. It stays grey.
1. Tapping on the `v-switch` itself again to toggle it to on/true (blue color) before tapping elsewhere on the `v-list-item` enables normal toggling again.

### Expected Behavior
The `v-switch` color should not stay in an off/false color state when toggled to true programmatically.

### Actual Behavior
The `v-switch` toggle color can become stuck on grey in a particular use case.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/VwjPgxj" target="_blank">https://codepen.io/185driver/pen/VwjPgxj</a>

### Other comments
[Issue 12417](https://github.com/vuetifyjs/vuetify/issues/12417) seems similar but feels a bit different too. I mention it in case there is a connection between them.

**Comment by KaelWD** [comment]
The correct prop is `input-value`
