### ISSUE TITLE
[Feature Request] buttons height vs inputs height (not really a feature but also not a bug...)

### ISSUE THREAD

**Issue by rbns-app** [vuetifyjs/vuetify#12507]
### Problem to solve
a ui issue - mismatch between inputs and buttons height (vary visible with outlined inputs, specially when the form elements are side by side)

### Proposed solution
make the inputs and buttons height the same (and add button height that matching to dense inputs).
currently I just set a new height for each button to be aligned with the inputs...

**Comment by jacekkarczmarczyk** [comment]
Buttons and input sizes should match Material Design specifications, if they don't match you can report a bug, otherwise you can use CSS or SASS variables to adjust sizes.

Closing for now, feel free to continue discussion though
