### ISSUE TITLE
[Bug Report] v-app-bar doesn't show after setting hide-on-scroll to false

### ISSUE THREAD

**Issue by derat** [vuetifyjs/vuetify#12505]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.77
**OS:** Chromium OS 13421.53.0

### Steps to reproduce
1. Initially set `v-app-bar`'s `hide-on-scroll` prop to true (done automatically in attached codepen).
2. Scroll down to hide the app bar.
3. Set `hide-on-scroll` to false (by clicking "toggle" button in attached codepen).

### Expected Behavior
The app bar should be shown.

### Actual Behavior
The app bar remains hidden until `hide-on-scroll` is set back to true and the user scrolls up.

### Reproduction Link
<a href="https://codepen.io/derat/pen/pobRQoB" target="_blank">https://codepen.io/derat/pen/pobRQoB</a>

### Other comments
My use case is that I usually want to the app bar to autohide, but I want to be able to programmatically force it to be shown (e.g. to highlight important information).

I initially tried to use the app bar's model to accomplish this, but it didn't seem to be possible to use it to show an app bar that had been hidden due to scrolling. IIRC, I was only able to use it to force the app bar to be hidden.

I tried programmatically scrolling the window with `window.scrollBy`, but that's visible to the user and unreliable.

As a hacky workaround, setting the `inverted-scroll` prop to true and then immediately setting it back to false on the next tick seems to force the app bar to be shown due to the watcher on `invertedScroll` (`this.isActive = !val || this.currentScroll !== 0`).

**Comment by matthieusieben** [comment]
A cleaner workaround is to:
```html
<v-app-bar ref="appBar" :hide-on-scroll="shouldHideOnScroll">
  <!-- content -->
</v-app-bar>
```


```js
  watch: {
    shouldHideOnScroll(val) {
      // @hack: https://github.com/vuetifyjs/vuetify/issues/12505
      if (!val) this.$refs.appBar.isActive = true
    },
  },
```
