### ISSUE TITLE
[Bug Report] v-main top padding won't be recomputed when header size changes

### ISSUE THREAD

**Issue by Velikolay** [vuetifyjs/vuetify#12500]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Mac OS 10.15

### Steps to reproduce
I have two impl for the header mobile and desktop and switch between the two using the display property with breakpoint conditions - https://codepen.io/velikolay/pen/YzWNOGB
What happens is that the padding is initially computed based on the mobile header and then the it won't be recomputed when it gets replaced by the desktop version resulting in overlapping or extra padding.

### Expected Behavior
The padding will be recalculated - no overlapping

### Actual Behavior
The padding stays the same - overlapping

### Reproduction Link
<a href="https://codepen.io/velikolay/pen/YzWNOGB" target="_blank">https://codepen.io/velikolay/pen/YzWNOGB</a>

**Comment by KaelWD** [comment]
It can't know that you've hidden it with CSS, you should control the visibility with `v-if` instead: https://codepen.io/kaelwd/pen/MWeJPaB?editors=1010

**Comment by jacekkarczmarczyk** [comment]
Padding is calculated based on the `height` prop, not on the css properties (height, display etc)
https://codepen.io/jkarczm/pen/oNLBajv
https://codepen.io/jkarczm/pen/yLJgRYj
