### ISSUE TITLE
[Bug Report] Only first header is displayed in v-select when header property in item is combined with null value for value or text

### ISSUE THREAD

**Issue by jelle-eastground** [vuetifyjs/vuetify#12517]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
See codepen

### Expected Behavior
[Header 1]
Item 1
Item 2
[Header 2]
Item 3

### Actual Behavior
[Header 1]
Item 1
Item 2
Item 3

### Reproduction Link
<a href="https://codepen.io/eastground/pen/XWKMBQj" target="_blank">https://codepen.io/eastground/pen/XWKMBQj</a>

### Other comments
Vuetify documentation states:

> Objects that have a header or divider property are considered special cases and generate a list header or divider;

In case it is intended to skip the header when value and/or text is null, it is not consistent, as Header 1 is displayed with null values for value and text. The same problem arises when using a v-autocomplete instead of a v-select.

**Comment by billerby** [comment]
So upgraded vuetify frrom 2.3.15 to the latest version today and noticed that this fix causes a javascript-error for some of our v-autocomplete:s 

`vue.runtime.esm.js:1888 TypeError: Cannot read property 'header' of null
    at VueComponent.filterDuplicates (VSelect.ts:322)
    at VueComponent.allItems (VSelect.ts:138)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.evaluate (vue.runtime.esm.js:4584)
    at VueComponent.computedGetter [as allItems] (vue.runtime.esm.js:4836)
    at VueComponent.filteredItems (VAutocomplete.ts:89)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.evaluate (vue.runtime.esm.js:4584)
    at VueComponent.computedGetter [as filteredItems] (vue.runtime.esm.js:4836)
    at VueComponent.computedItems (VAutocomplete.ts:73)`

So when item is for some reason null its not handled.

**Comment by jokamax** [comment]
Same here as @billerby 
Since this patch : **v-select/v-autocomplete** + **return-object** = **error Cannot read property 'header' of undefined**

**Comment by davidebertRA** [comment]
same here as @billerby from 2.3.12 to 2.3.23
![image](https://user-images.githubusercontent.com/79514042/134883812-2d040d8c-f89f-4687-801c-110a1487c0a3.png)

**Comment by shlomy** [comment]
Same here as. Same Error Since this patch.
Did someone find how to get around this?
