### ISSUE TITLE
[Bug Report] Items in <v-app-bar fixed shrink-on-scroll> block <v-toolbar-title> on low resolution even when the app-bar is expanded

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12514]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Firefox 81.0
**OS:** Windows 10

### Steps to reproduce
1. Open page without scrolling down (which would cause the "Vuetify.js" title to move up from the second line below icons due to `shrink-on-scroll`)
2. Reduce the page width by resizing window to move the icons on right side to be above the title

### Expected Behavior
There's no intersection, and so the title should be properly displayed

### Actual Behavior
The title becomes shorter, like "Vueti...", for no apparent reason to the visitor:

![Vueti...](https://user-images.githubusercontent.com/3118390/97186762-f99e3280-17a1-11eb-80ae-b25ae68cefb2.png)

Paradoxically, more of the text gets shown due to font size change after a scroll once there's less space.

### Reproduction Link
<a href="https://codesandbox.io/s/distracted-meninsky-osl9g?file=/layouts/default.vue" target="_blank">https://codesandbox.io/s/distracted-meninsky-osl9g?file=/layouts/default.vue</a>

### Other comments
* This behavior isn't customizable or documented (just like the inability to specify title scaling details, or any icon hiding priority).
* The documentation also doesn't properly explain that we have to put all button icons inside [`<v-toolbar-items>`](https://vuetifyjs.com/en/api/v-toolbar-items/) (which has no API description) before putting them inside `<v-toolbar-title>`, and even then the positions aren't perfect.
* `shrink-on-scroll` seems to automatically apply `prominent`, which the docs don't explicitly mention, other than "Shrinks a prominent toolbar".
* I also misunderstood this feature by assuming that it provides an additional slot below for items while not shrunk, but then realized that the only available `extension` slot is always visible (as a "third row"), so I'd like to ask, is it a design decision not to allow a similar behavior, or is it reasonable to be considered in a future?

**Comment by KaelWD** [comment]
Is this what you'd expect?
![Peek 2020-10-27 03-35](https://user-images.githubusercontent.com/16421948/97200731-b2498d80-1805-11eb-9507-135063c63a72.gif)

> we have to put all button icons inside `<v-toolbar-items>`

I don't think you're supposed to put icon buttons inside that, all it does is make buttons fill the height of the toolbar. 

> assuming that it provides an additional slot below for items while not shrunk

It's probably possible to do that, no idea how you'd position everything with respect to the title though, or how it would gradually hide as you scroll.

**Comment by scscgit** [comment]
Nice, this looks just as I expected (though maybe the complete text could appear a bit sooner based on its font size). Thanks for a quick response! :)

---

About items inside `<v-toolbar-title>`, I don't know if the Material Design Guidelines of a prominent header enforce the usage of only a simple text, but I assumed that some use-cases may require other elements, and the icons were a simplest example. However, I just figured out that when not using `<v-toolbar-items>`, this issue only occurs when using `<v-btn>` like this:
```
<v-toolbar-title>
  <v-btn icon>
    <v-icon> mdi-home </v-icon>
  </v-btn>
  Vuetify.js
</v-toolbar-title>
```
but it displays correctly when using only the icon directly:
```
<v-toolbar-title>
  <v-icon> mdi-home </v-icon>
  Vuetify.js
</v-toolbar-title>
```
so this may be just a matter of documenting the correct combinations, as I don't see any starting point to figure this out.

---

Yeah, the shrinking of items inside an extension slot would probably require those items to be placed on the first row, thus the title would move along with the same set of items instead of only joining them after a scroll. If this were an opt-in feature (as long as the width of items doesn't conflict with the header title, breaking its prominency), the icons on the left and right could be considered separately, and it could be up to the user to define the specific behavior, including hiding some icons behind an overflow menu, or specifying the transitions. There's no need to implement all of the alternatives within the library if it's outside the scope of Material Design, but it would be great if there were a guideline to explain how we could extend the existing behavior to implement something like this, without breaking forward compatibility with this component.

**Comment by KaelWD** [comment]
> maybe the complete text could appear a bit sooner based on its font size

It does overlap a bit sometimes if the title is really long
![image](https://user-images.githubusercontent.com/16421948/97217534-89cc8e00-181b-11eb-9063-248044bf6748.png)


I can add a cubic easing function so it starts off a bit slower then accelerates:
![Peek 2020-10-27 06-10](https://user-images.githubusercontent.com/16421948/97217356-42460200-181b-11eb-89c4-3cb15ac3780f.gif)

The prominent bar is based on [material specs](https://material.io/components/app-bars-top#anatomy), they don't show any items in the expanded area. I don't even think you're really supposed to use the extension slot with a prominent bar either.
![image](https://user-images.githubusercontent.com/16421948/97218575-f8f6b200-181c-11eb-856b-47d83c5e7cfd.png)

**Comment by scscgit** [comment]
Sure, it can't expand so fast, which is why the font size or a similar parameter (like `<v-toolbar-title>` height without padding, but it's probably fine even with padding) has to be taken into consideration (when specifying the minimum scroll that causes expansion beyond other items) to avoid the intersection illustrated on your screenshot. And yeah, the material specs seem to be too oversimplified for many practical purposes, which is why I thought that a guide explaining how to extend this behavior would be a better choice (so that all other v-app-bar parameters still apply), because at this moment there's no mention of what isn't supposed to be supported.

Btw. I noticed in your commit adding a new `<v-app-bar-title>` intended with `shrink-on-scroll`, out of curiosity, is there a reason why this feature can't be included in the existing `<v-toolbar-title>` (and turned on automatically by default)?

And I'll ask one more unrelated detail while I'm at it: The `<v-text-field>` in a repro example seems to lack centering due to `dense` prop; is this also an expected behavior (requiring us to add `margin-top`), or should the `<v-app-bar>` center its items automatically? The same occurs when using a simple `<v-btn> Button </v-btn>`.

**Comment by KaelWD** [comment]
> a guide explaining how to extend this behavior would be a better choice

If the behaviour you mean is adding things to the prominent area I don't even know if it's possible. Feel free to open a PR if you have anything you want to add. 

> is there a reason why this feature can't be included in the existing `<v-toolbar-title>`

It adds complexity. v-toolbar-title is a really basic functional component that just renders `<div class="v-toolbar-title">`. If combined it would now be a stateful component instead, and I'd have to complicate the current implementation too by conditionally adding watchers based on if it's actually used in a v-app-bar or not. 

> seems to lack centering

`<v-app-bar prominent>` aligns children to the top so they don't move when the toolbar expands. You can center the input with
```html
<v-responsive
  max-width="260"
  height="48"
>
  <div class="d-flex fill-height align-center">
    <v-text-field ...
```
