### ISSUE TITLE
[Documentation] html-snippet for wireframes missing

### ISSUE THREAD

**Issue by Frodo1980** [vuetifyjs/vuetify#12513]
### Environment

**Browsers:** Chrome 86.0.4240.111
**OS:** Windows 10

### Steps to reproduce
open the link and watch the browser-console

### Expected Behavior
button with html-code-snippet for wireframe expected

### Actual Behavior
no button appeared - console logs error

xhr.js:178 GET https://api.cosmicjs.com/v1/56c28240-7c2a-11ea-896e-3119d26c2507/objects?re…Bj8YT8rUI75X7ofCIMaMCP&status=published&type=ads&props=metadata,slug,title 401

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/examples/wireframes/base/" target="_blank">https://next.vuetifyjs.com/en/examples/wireframes/base/</a>

### Other comments
I saw in a youtube-video, that there should be a button at the wireframes-page to see the html-code

**Comment by nekosaur** [comment]
You're not using the correct url. Try this https://vuetifyjs.com/en/examples/wireframes/base/
