### ISSUE TITLE
[Feature Request] How to create automatically change vuetify theme by hour in the nuxt?

### ISSUE THREAD

**Issue by andrejsharapov** [vuetifyjs/vuetify#12526]
### Problem to solve
How to create automatically change *vuetify* theme *by hour* in the *nuxt*?

### Proposed solution
I do not know

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
