### ISSUE TITLE
[Bug Report] Combobox adds search term to selected items

### ISSUE THREAD

**Issue by shaqaruden** [vuetifyjs/vuetify#12523]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.5.17
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
activate combobox
type search term
select option

### Expected Behavior
add only the selected option

### Actual Behavior
adds selected option and search term

### Reproduction Link
<a href="https://codepen.io/shaqaruden/pen/vYKdNYr" target="_blank">https://codepen.io/shaqaruden/pen/vYKdNYr</a>

**Comment by shaqaruden** [comment]
Playing around with it more the issue seems to be with having `item-text` and `item-value` props

**Comment by KaelWD** [comment]
Duplicate of #8842

**Comment by shaqaruden** [comment]
@KaelWD My example is not working the way it did when I originally created this issue. For me the search term was also being added to the v-model not just the item I clicked on
