### ISSUE TITLE
[Bug Report] V-text-field calendar icon out of the outlined box

### ISSUE THREAD

**Issue by marcoprodata** [vuetifyjs/vuetify#12528]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Just click on button click me and the icon will be outside outlined box

### Expected Behavior
Just that calendar icon stay inside outlined box

### Actual Behavior
The calendar icon stay outside the box

### Reproduction Link
<a href="https://codepen.io/marcoprodata/pen/zYBpXjb" target="_blank">https://codepen.io/marcoprodata/pen/zYBpXjb</a>

**Comment by marcoprodata** [comment]
Adding this css aparently solve the issue

`input[type="date"] {
  position: absolute !important;
}`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
