### ISSUE TITLE
[Bug Report] <v-data-table> ignoring pageText slot when there are no items

### ISSUE THREAD

**Issue by josephzidell** [vuetifyjs/vuetify#12520]
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.12
**Browsers:** Firefox 81.0
**OS:** Mac OS 10.15

### Steps to reproduce
When there are items, then the `pageText` slot works as designed. However, if you change `:items="[]"`, then it completely ignores the custom slot, and a `-` is rendered.

### Expected Behavior
The custom slot is used whether items are there or not

### Actual Behavior
Custom slot is ignored

### Reproduction Link
With items (slot used): <a href="https://codesandbox.io/s/jolly-dijkstra-2zm3w" target="_blank">https://codesandbox.io/s/jolly-dijkstra-2zm3w</a>
Without items (slot ignored): <a href="https://codesandbox.io/s/inspiring-montalcini-ltjpf" target="_blank">https://codesandbox.io/s/inspiring-montalcini-ltjpf</a>

**Comment by josephzidell** [comment]
@KaelWD Can anyone look at this?

**Comment by jacekkarczmarczyk** [comment]
v1.5 reached end of life on July 31st, 2020 and is no longer actively maintained
