### ISSUE TITLE
[Bug Report] v-list-item emitting inputs incorrectly

### ISSUE THREAD

**Issue by Jtav1** [vuetifyjs/vuetify#12529]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Edge 86.0.622.51
**OS:** Windows 10

### Steps to reproduce
Click "select all" button then click one of the list items to de-select it. 

### Expected Behavior
Clicked item de-selects

### Actual Behavior
Clicked item remains selected, all other v-list-items emit input (as shown by console.log statements) and de-select.

### Reproduction Link
<a href="https://codepen.io/jttavares/pen/QWEQePa" target="_blank">https://codepen.io/jttavares/pen/QWEQePa</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
