### ISSUE TITLE
[Documentation] help translate not work!

### ISSUE THREAD

**Issue by michael829** [vuetifyjs/vuetify#12521]
### Environment

**Browsers:** Chrome 86.0.4240.111
**OS:** Mac OS 10.15.7

### Steps to reproduce
I'm just want try to translate something to "Simplified Chinese".  the button on the page at top-right with text "Help translate" is broken, I have try click sometimes but nothing happen. so......what can i do? thanks...

### Expected Behavior
help translate to "Simplified Chinese"

### Actual Behavior
nothing happen.

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/introduction/why-vuetify/" target="_blank">https://next.vuetifyjs.com/en/introduction/why-vuetify/</a>

### Other comments
er.... just want have a try..

**Comment by MajesticPotatoe** [comment]
wrong url
https://vuetifyjs.com/en/

**Comment by michael829** [comment]
Hi, I'm finished!~ 
But no one seems to be dealing with this.
And when I started to translate, a part (30%) had been completed, which seemed to be machine translation. Because there was no way to preview, so it could not be proofread at present.
Can you update it online? Then correct the inaccuracies.

![20201106-111010](https://user-images.githubusercontent.com/9690703/98322081-8c9c5f80-2021-11eb-94d5-734cfac43b15.png)

**Comment by KaelWD** [comment]
In-context works on https://vuetifyjs.com/, not https://next.vuetifyjs.com/

**Comment by MajesticPotatoe** [comment]
Project has been built, and enabled in b09bd1d
