### ISSUE TITLE
[Bug Report] V-Data-Table  default slot does nothing.

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#12539]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.111
**OS:** Windows 10

### Steps to reproduce
add default slot to v-data-table.
![image](https://user-images.githubusercontent.com/20317691/97770484-11740e80-1b34-11eb-9e23-af466fa5dfb0.png)
Neither of those does anything.

### Expected Behavior
The default item-template gets replaced by the default slot. Eliminating the need for using named slots for each item template.

### Actual Behavior
Nothing.

### Reproduction Link
<a href="https://codepen.io/timar/pen/JjKLevy?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F" target="_blank">https://codepen.io/timar/pen/JjKLevy?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F</a>

**Comment by KaelWD** [comment]
VDataTable doesn't have a default slot. If you want to replace the whole row use `v-slot:item`, if you want to replace the whole `<tbody>` use `v-slot:body`

**Comment by sugoidesune** [comment]
In that case I would turn this into a Feature Request.

I am currently looping through the header and creating a default slot for each column i want to change the default behavior for.
![image](https://user-images.githubusercontent.com/20317691/97771321-e097d780-1b3b-11eb-94e0-1bee4013cab0.png)

**Comment by BehindTheMath** [comment]
@KaelWD What is this slot for?

https://vuetifyjs.com/en/api/v-data-table/#default

**Comment by MajesticPotatoe** [comment]
> @KaelWD What is this slot for?
> 
> https://vuetifyjs.com/en/api/v-data-table/#default

nothing. its inherited from data-iterator that actually uses it and should be removed as it has no use in v-data-table as kael has described.

> I am currently looping through the header items and creating a default slot for each column i want to change the default behavior for.

There are slots already generated for these. They are the `item.<name>` slots.
