### ISSUE TITLE
[Bug Report] Appended slot disappears in v-text-field

### ISSUE THREAD

**Issue by timothymarois** [vuetifyjs/vuetify#12538]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.111
**OS:** Mac OS 10.15.7

### Steps to reproduce
Referencing: https://github.com/vuetifyjs/vuetify/issues/1360
Because I can not comment on previous issues that were auto closed. 

Slot for text-field append
```
<template v-slot:append> 
        <v-btn 
              elevation="0"
               rounded
                color="blue accent-2"
                fab
                small
       ><v-icon>mdi-magnify</v-icon></v-btn>
</template>
```

This issue is still going on. and it is not this: 

@johnleider
"I mean, this is something we could improve, but the icon doesn't disappear, it just gets the same color as the background because inputs use the application primary color and you put them inside of a nav as the applications primary color."

The appended slot does disappear, its completely gone. 

<img width="420" alt="Screen Shot 2020-10-30 at 8 20 33 PM" src="https://user-images.githubusercontent.com/2489333/97766958-6fcace00-1aef-11eb-9917-6dbf38796342.png">

<img width="418" alt="Screen Shot 2020-10-30 at 8 20 55 PM" src="https://user-images.githubusercontent.com/2489333/97766961-722d2800-1aef-11eb-8fdf-a0769571613a.png">

To note, I am using a fresh install, nothing else on this install has any customizations, this is literally the first template I put together with this project and I'm seeing this from out of the box install. 

### Expected Behavior
The appended slot should never disappear

### Actual Behavior
The appended slot is disappearing. 

### Reproduction Link
<a href="https://jsfiddle.net/" target="_blank">https://jsfiddle.net/</a>

**Comment by KaelWD** [comment]
An issue that was closed three years ago is not a valid reproduction link.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by taxilian** [comment]
FWIW I'm seeing the same behavior, this is still occurring. If I can figure out exactly what is happening I'll post more info and/or a reproduction link, but at present it seems to happen when the `items` change -- specifically in this case when they change from an empty array to a populated one, but I'm still in the initial troubleshooting stage, just wanted to post a data point for anyone in the future who may run into a similar issue.

**Comment by taxilian** [comment]
... actually, it was occurring on 2.6.0. I upgraded to 2.6.1 and now it's not happening anymore. Not 100% sure if that was the difference, since I changed a few other things too.

**Comment by maneeshmk** [comment]
on 2.6.1 but still happening with append slot of the textarea. It shows up sometimes but disappears very often.

**Comment by johnleider** [comment]
> on 2.6.1 but still happening with append slot of the textarea. It shows up sometimes but disappears very often.

If this is still a bug please create a new issue.
