### ISSUE TITLE
[Documentation] Broken Search Results

### ISSUE THREAD

**Issue by dzimney** [vuetifyjs/vuetify#12534]
### Environment

**Browsers:** Firefox 68.0
**OS:** Linux x86_64

### Steps to reproduce
Enter "v-img" into the site search bar and select the first result.

### Expected Behavior
Direct users to the v-img component documentation.

### Actual Behavior
404 Error

### Reproduction Link
<a href="https://v2.vuetifyjs.com/en/api/v-img/#v-img-api" target="_blank">https://v2.vuetifyjs.com/en/api/v-img/#v-img-api</a>

**Comment by dzimney** [comment]
Appears to be legacy issues with the search functionality of the site. For a number of components it appears the documentation has been moved from the "api" section to the "components" section and the former links are resulting in a 404. For example, when searching for "v-img" the first set of (API) results are broken links.

**Comment by MajesticPotatoe** [comment]
This is more of an issue with the old doc search recognizing links that start with vuetifyjs.com as internal, and using vue-router (resulting in 404). Given we are no longer working on those old docs (and this will become obsolete come v3 if not sooner). For proper searching you should use the new docs.
