### ISSUE TITLE
[Bug Report] Select button close. Usability issue

### ISSUE THREAD

**Issue by rnenjoy** [vuetifyjs/vuetify#12536]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.110
**OS:** Android 10

### Steps to reproduce
The current design of the select menus are very problematic. I have been watching countless of usability hours of users using our system and have noticed that normal users are having big problems with how the select menus are designed.

They are designed in a way that after opening it, it can only be closed by clicking on an item or outside. If it's multi select its even worse. 

Clicking outside could cause miss clicks, but many normal users don't understand that they should click outside to close. 

### Expected Behavior
I checked Googles material design documentation and it is clear it does not have this flaw. Then select opens below the initial square which allows you to click the same select input square again to close it. Just like a normal native select in all browsers.

This really should be fixed. 

### Actual Behavior
Select items opens on top of the initial select. Square 

### Reproduction Link
<a href="https://material-components.github.io/material-components-web-catalog/#/component/select" target="_blank">https://material-components.github.io/material-components-web-catalog/#/component/select</a>

**Comment by rnenjoy** [comment]
### Vuetify:
**Closed:**
![image](https://user-images.githubusercontent.com/6672175/101764496-6b2b0980-3ae0-11eb-9670-b9ffc20891f3.png)
**Open:**
![image](https://user-images.githubusercontent.com/6672175/101764578-7e3dd980-3ae0-11eb-9db1-48e3acbfaae1.png)

### Material design by Google:
**Closed:**
![image](https://user-images.githubusercontent.com/6672175/101764628-8d248c00-3ae0-11eb-9b53-232849a98380.png)
**Open:**
![image](https://user-images.githubusercontent.com/6672175/101764649-957cc700-3ae0-11eb-8854-b8c1e8528dcc.png)

material design has a clear way how to close the select. Vuetify does not.

**Comment by spantaleev** [comment]
This is indeed a huge usability problem that also trips up experienced users.

**Comment by MajesticPotatoe** [comment]
`:menu-props="{ offsetY: true }"` if want it to open below. This was likely an old standard that just was never updated, changing it now would likely constitute a breaking change and would need to wait for v3

**Comment by jacekkarczmarczyk** [comment]
I was about to show this workaround, but it's still not enough since you can't close the select by clicking on the field

**Comment by MajesticPotatoe** [comment]
`:menu-props="{ closeOnClick: true, offsetY: true }"` / `:menu-props="{ ['closeOnClick', 'offsetY']"` will work if you want it to close when you click the field too

**Comment by rnenjoy** [comment]
> `:menu-props="{ closeOnClick: true, offsetY: true }"` / `:menu-props="{ ['closeOnClick', 'offsetY']"` will work if you want it to close when you click the field too


THank you! That works! However, there is a bug. You cannot click on the down arrow to open the menu. You can only click near it, or click on it to close. But not to open.

![image](https://user-images.githubusercontent.com/6672175/101887660-77c16780-3b9d-11eb-8165-81a06e4fc7c9.png)

Preview:
https://codepen.io/rightnow/pen/RwGoxJx

**Comment by rnenjoy** [comment]
Ok i found the duplicate issue! Thanks!
