### ISSUE TITLE
[Bug Report] v-navigation-drawer does not trigger transitionend when set true on page open

### ISSUE THREAD

**Issue by uclnj** [vuetifyjs/vuetify#12540]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
When setting the v-navigation-drawer v-model to true to have the side panel open on page load, the transitionend event is not initially called.  Only when the user clicks off of the panel closing it will it fire.  The example shows this.

### Expected Behavior
transitionend should trigger when the page loads and a nav pane is set to auto open.

### Actual Behavior
it doesn't trigger.

### Reproduction Link
<a href="https://codepen.io/uclnj/pen/QWEmeaG" target="_blank">https://codepen.io/uclnj/pen/QWEmeaG</a>

**Comment by KaelWD** [comment]
There's no transition, why would it emit transitionend?

**Comment by uclnj** [comment]
The button to bring up the drawer is a simple @click="drawer = !drawer" - this triggers the transition.  Add this code to mounted and the transitionend does not trigger.  The page is mounted at this stage, now I'm asking it to make a change, i.e., show the nav-panel.

I updated the repo link to show that if you add
`this.drawer = !this.drawer`
to mounted, the transitionend does not trigger but if you change it to 
`setTimeout(() => { this.drawer = !this.drawer }, 50)`
it does.

So transitionend does nothing until you're out of the mounted process?

**Comment by KaelWD** [comment]
Yes, transitions are intentionally disabled for the first render.
