### ISSUE TITLE
[Bug Report] Inconsistent Behaviour when using v-combobox with keyboard

### ISSUE THREAD

**Issue by stefanKuijers** [vuetifyjs/vuetify#12567]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 3.0.2
**Browsers:** Chrome 86.0.4240.183
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) Select the first item in the list by clicking it. As Expected.
2) Open the combobox again by clicking in it and select the second item. As Expected.
3) Now hit the enter key, it will open the combobox. As Expected.
4) Hit enter again which keeps the current item selected and closes the combobox. As Expected.
5) Hit the enter key again how ever many times you like, the combobox does not open. Not as expected.
6) Click on the combobox and open the third item from the list. The combobox closes. As Expected
7) Hit enter. This will not open the combobox but switch your selection back to your previous selected item. Not as expected.
8)  With enter toggle to your previous selection (second item). Open the combobox and select the fourth item in the list. Combobox closes as expected.
9) Keep hitting enter and you will see that it toggles between the third and the fourth item. Even though you selected the second item in the list before. REally not as expected.

I'm quite sure point eight and nine won't happen once the enter->toggle problem is fixed.

You can check it in the samples as well.
https://vuetifyjs.com/en/components/combobox/#usage

#### Step 5 
I would expect the combobox to toggle its open state on hitting the enter key. 

#### Step 7 
I expect the combobox to open when it has focus and  I hit enter.

#### Step 9 
I would expect the combobox to open when it has focus and I hit enter.

#### Step 5
Instead of opening the combobox it does nothing. 

#### Step 7 
Instead of opening the combobox it start toggeling between my current and previous selection.

#### Step 9 
Instead of opening the combobox it start toggeling between my current and before previous selection.

### Reproduction Link
<a href="https://codepen.io/stefanKuijers/pen/KKMxgMY" target="_blank">https://codepen.io/stefanKuijers/pen/KKMxgMY</a>

### Other comments
As many users of our application use it with the keyboard these issues are pretty confusing for them.

Thank you guys so much for Vuetify. It's awesome!

**Comment by mariobuikhuizen** [comment]
Something similar happens for v-select. Opening the select with enter only works one time. Observed in v2.2.26 and v2.3.16 in the example page https://vuetifyjs.com/en/components/selects/

**Comment by stefanKuijers** [comment]
The joke with the v-select might need another issue. When you select a value from the list with enter it closes the dropdown and selects the right item (awesome). But when you hit the arrow up or down it will select another item from the list and loose focus. :D. 

But as I said: that might deserve another issue. Thanks for pointing it out @mariobuikhuizen
