### ISSUE TITLE
[Bug Report] list-item group with selection controls with props multiple and mandatory allows not having anything checked

### ISSUE THREAD

**Issue by transfluxus** [vuetifyjs/vuetify#12577]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
check the difference between deselecting the last item by clicking on the text and the checkbox.
by clicking on the text one mandatory item stays selected.
but with the checkboxes its allowed to deselect that last checkbox, tho the text still indicates that the item is selected

### Expected Behavior
the checkbox stays select for the last item, since its mandatory to have at least one item selected

### Actual Behavior
all checkboxes can deselcted

### Reproduction Link
<a href="https://codepen.io/transfluxus/pen/ZEOqoPY?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Flist-item-groups%2F" target="_blank">https://codepen.io/transfluxus/pen/ZEOqoPY?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Flist-item-groups%2F</a>

### Other comments
creates a confusing ui. the checkbox is not ticked but the item is still selected.
As expected when clicking on the text of the last item, it stays selected and the checkbox also still ficked.

**Comment by transfluxus** [comment]
for people who have to deal with this. I could prevent this from happening by stetting the v-checkbox to _readonly_.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
