### ISSUE TITLE
[Bug Report] v-color-picker alpha option disappears

### ISSUE THREAD

**Issue by digitalniweb** [vuetifyjs/vuetify#12574]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
If you move the alpha slider to left or just set alpha to zero the slider and alpha option disappear

### Expected Behavior
alpha option shouldn't disappear

### Actual Behavior
alpha option disappears

### Reproduction Link
<a href="https://codepen.io/dsadassdasdsadasdasd/pen/XWKxdVa" target="_blank">https://codepen.io/dsadassdasdsadasdasd/pen/XWKxdVa</a>

**Comment by MajesticPotatoe** [comment]
resolved in #12305
