### ISSUE TITLE
[Bug Report] Select blurs on keypress (up/down)

### ISSUE THREAD

**Issue by janKollars** [vuetifyjs/vuetify#12572]
### Environment
**Vuetify Version:** 2.3.16
**Last working version:** 2.3.12
**Vue Version:** 2.6.12
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
1. use tab-key until you focus the select
2. press up or down

### Expected Behavior
changes selected value and keeps focus

### Actual Behavior
changes selected value and loses focus

### Reproduction Link
<a href="https://codepen.io/kjan/pen/RwRYXBQ" target="_blank">https://codepen.io/kjan/pen/RwRYXBQ</a>

### Other comments
It appears that the problem was introduced in https://github.com/vuetifyjs/vuetify/pull/12109

**Comment by diavrank** [comment]
Hello, is there any ETA for this fix? I noticed that is still present in **2.4.2**

**Comment by KaelWD** [comment]
This seems to have been fixed in v2.4.5 by #12815
