### ISSUE TITLE
[Bug Report][2.3.16] A v-textarea inside a v-stepper-step does not take up the available width.

### ISSUE THREAD

**Issue by jaunt** [vuetifyjs/vuetify#12584]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Linux x86_64

### Steps to reproduce
In the attached codepen, I cannot find any way to get the v-textarea inside the v-stepper-step to fill up the width properly.  

### Expected Behavior
The v-text-area should group should be as wide as the v-stepper-step. 

### Actual Behavior
It's taking on a width of 195 for a reason I don't know.

### Reproduction Link
<a href="https://codepen.io/jauntcode/pen/RwRqZba" target="_blank">https://codepen.io/jauntcode/pen/RwRqZba</a>

### Other comments
Is there a work-around?

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/abWJXya
