### ISSUE TITLE
[Bug Report] v-autocomplete append-item click event no longer fired

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#12586]
### Environment
**Vuetify Version:** 2.3.17
**Last working version:** 2.3.16
**Vue Version:** 3.0.2
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
Click on the list item that was added through the template `#append-item`.
Nothing happens, `dlg` remains set to `false` despite the `@click="dlg = true"`.

### Expected Behavior
`dlg` to change to true once the append-item was clicked.

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://codepen.io/auspex/pen/KKMrEQm" target="_blank">https://codepen.io/auspex/pen/KKMrEQm</a>

**Comment by KaelWD** [comment]
@YipingRuan @johnleider #12397

**Comment by francoispluchino** [comment]
This bug is also present with Vue version `2.6.12`.
