### ISSUE TITLE
[Feature Request] Clearable inputs feature useful but ugly, could it be hidden when not focused?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#12589]
### Problem to solve
It's useful to have a clearable button on inputs, particularly on a phone but it makes forms with a lot of inputs extremely ugly looking as the clearable button is *always* present.

### Proposed solution
A property that you can set to only show the clearable icon when the control has focus

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by WhatFreshHellIsThis** [comment]
What a shame, it's a missed opportunity to clean up and beautify a UI that uses Vuetify *considerably*. Perhaps your use-cases don't consider forms with a significant number of inputs?  I hope this is re-considered in future.
