### ISSUE TITLE
[Bug Report] Problem prepend the drop down arrow on a parent v-list-group expansion panel that results in appended icon "flipping"

### ISSUE THREAD

**Issue by corbin88** [vuetifyjs/vuetify#12588]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.1
**Browsers:** Chrome 86.0.4240.183
**OS:** Mac OS 10.14.5

### Steps to reproduce
Instead of appending the drop down arrow on the `<v-list-group>` expansion panel I want to prepend it and append a search icon. The problem is the search icon flips and the down arrow stays stationary. 

### Expected Behavior
Prepended Drop down arrow "flips"

### Actual Behavior
Appended search icon flips

### Reproduction Link
<a href="https://codepen.io/Corbin/pen/RwRqVbx?editors=1010" target="_blank">https://codepen.io/Corbin/pen/RwRqVbx?editors=1010</a>

**Comment by corbin88** [comment]
I have a hacky way of getting around this by using `sub-group` on `<v-list-group>`. Here's the stackoverflow:

https://stackoverflow.com/questions/64774870/how-do-i-prepend-the-drop-down-arrow-on-a-parent-v-list-group-expansion-panel

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
