### ISSUE TITLE
[Feature Request] v-data-table: ignore the sorting of group-by and disallow the remove group button

### ISSUE THREAD

**Issue by albertwong25** [vuetifyjs/vuetify#12593]
### Problem to solve
The bug fix for [#9685](https://github.com/vuetifyjs/vuetify/issues/9685) set the default value for `group-desc` to `false`. This change set the `group-by` field to primary sort, so that the `sort-by` field or the header sorting becomes secondary sort. That's great if we want to keep the sorting of `group-by` and sort only inside the group, however, we want to sort the table by other fields first instead of the `group-by` field.

Here is our use case:
[https://codepen.io/albertwong25/pen/bGeOeaE](https://codepen.io/albertwong25/pen/bGeOeaE)

We have a product table which lists all products with update date. The category is used to classify the product into different group and user is not allow to remove the group. To find out recent updated products, we sort the table by update date in descending order. However, we cannot ignore the sorting of the category as the data table always sorted by `group-by` first.

### Proposed solution
We are able to "by pass" the sorting of `group-by` by using `custom-sort` to write the custom sorting method. Seem like the sorting of `group-by` will be ignored when `custom-sort` is existed. Instead of writing custom sorting method, it is nice to have a prop `group-sort="true|false"` to disable the sorting of `group-by`.

On the other hand, we need to write slot `group.header` in order to disallow the group remove button. A prop `group-remove="false|true"` is great to achieve the goal.

**Comment by Q-intessence** [comment]
Its now 2022 and I too am still also wanting this feature? 
Can we get an idea of what the triaged date this feature/enhancement will come out?

**Comment by johnleider** [comment]
We have multiple data table variants in Labs atm that should close this https://vuetifyjs.com/en/components/data-tables/basics/

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
