### ISSUE TITLE
[Feature Request] VFileInput Button 

### ISSUE THREAD

**Issue by Xa3lis** [vuetifyjs/vuetify#12595]
### Problem to solve
In my project we want to use button as file input, or actually the `VFileInput` is an extension of the `VText` component, i don't think I'm the only one in that case, as `input type="file"` are nearly always shown as a button, I wanted to know if it was a feature you might add in a near future ?

### Proposed solution
Let the choice to use `VFileInput` as text or as button

Thank's

**Comment by johnleider** [comment]
https://vuetifyjs.com/en/components/file-inputs/
