### ISSUE TITLE
[Feature Request] font family variable

### ISSUE THREAD

**Issue by HakimBhd** [vuetifyjs/vuetify#12590]
### Problem to solve
change font family dynamically 

### Proposed solution
Providing a way just like when changing the theme, to change the default font family.
this is helpful when changing language and you need to change the font based on the language.

**Comment by KaelWD** [comment]
Use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*)

**Comment by HakimBhd** [comment]
@KaelWD please can you show me how to make it done, using deferent font for RTL language.
