### ISSUE TITLE
[Bug Report] v-treeview selection issues after tree rebuild

### ISSUE THREAD

**Issue by Altxis** [vuetifyjs/vuetify#12594]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.183
**OS:** Linux x86_64

### Steps to reproduce
Steps to reproduce:
1. Select all
2. Unselect all
3. Toggle switch "full tree" on
4. Toggle switch "full tree" off
5. Select all one more time
6. Selection is correct, but treeview visually incorrect

### Expected Behavior
When I click select all after switching on and off "Full tree" I expect that still selecting all items

### Actual Behavior
Checkbox state issues in treeview

### Reproduction Link
<a href="https://codepen.io/altxis/pen/pobqPeX" target="_blank">https://codepen.io/altxis/pen/pobqPeX</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
