### ISSUE TITLE
[Bug Report] Map behaves like mutating method in v-data-table

### ISSUE THREAD

**Issue by dennisvanhove** [vuetifyjs/vuetify#12598]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.11
**Browsers:** Safari 12.0.1
**OS:** Mac OS 10.13.6

### Steps to reproduce
No steps required

### Expected Behavior
<tr>
  <th>Name</th>
  <th>Value</th>
</tr>
<tr>
  <td>Item1</td>
  <td>no</td>
</tr>
<tr>
  <td>Item2</td>
  <td>yes</td>
</tr>

### Actual Behavior
<tr>
  <th>Name</th>
  <th>Value</th>
</tr>
<tr>
  <td>Item1</td>
  <td>yes</td>
</tr>
<tr>
  <td>Item2</td>
  <td>yes</td>
</tr>

### Reproduction Link
<a href="https://codepen.io/CheapGamer/pen/XWKoawv" target="_blank">https://codepen.io/CheapGamer/pen/XWKoawv</a>

**Comment by jacekkarczmarczyk** [comment]
Because it does mutate your data
https://codepen.io/jkarczm/pen/GRqPOWa

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
