### ISSUE TITLE
Sidebar router

### ISSUE THREAD

**Issue by John0x** [vuetifyjs/vuetify#126]
Hey, before the new update we could just set the "router" Prop to add the active class to the active route item, since this has been removed, what would be the best way to implement that now?

**Comment by johnleider** [comment]
Apply it directly to the list tiles.

**Comment by John0x** [comment]
@johnleider okay, thanks :)
So, how do I define the link then?

I'm grateful for all the changes and improvements, but it kinda made everything harder. It is nowhere mentioned in the docs how to use links within the sidebar properly, whereas it was easy cake before the update :/

**Comment by johnleider** [comment]
Well what do you mean define the link? The list tile has a href prop along with router.

**Comment by John0x** [comment]
@johnleider ah, I'll try that.
The href prop is not mentioned in the docs:
https://vuetifyjs.com/components/lists

**Comment by johnleider** [comment]
Touch. I'll get that updated

**Comment by John0x** [comment]
@johnleider alright, thanks for the help :)

**Comment by requnix** [comment]
I'd like to point out that its half a year later, and I still have no idea how to use lists other than to add a `@click="$router.push(...)"`. That said, using the router elsewhere in the app seems to pop open the Navigation Drawer even though its `v-model` remains `false`...

**Comment by johnleider** [comment]
Well what are you trying to do? List items behave **exactly** like a router-link, so anything you use on that can be used on list items.

We also have a community for help, https://chat.vuetifyjs.com

**Comment by requnix** [comment]
Oh great, I found `disable-route-watcher` which should do what I want.
