### ISSUE TITLE
[Documentation] Examples include scripting

### ISSUE THREAD

**Issue by renenw** [vuetifyjs/vuetify#12606]
### Problem to solve
Vuetify is, in essence, a collection of user interface widgets. But, your examples frequently rely on scripting or code to illustrate things. This obscures the underlying clarity, and makes it much harder for a Vuetify noob to grasp what is being illustrated.

By way of an example, consider https://vuetifyjs.com/en/components/grids/#align

Surely this example would be much clearer if the detail was simply hard coded?

(Love your work though!)

### Proposed solution
Code the examples with the use of minimal script.

**Comment by renenw** [comment]
here's another example: https://vuetifyjs.com/en/styles/text-and-typography/#typography

You can't just cut and paste "header 4". Which is really the guidance and understanding that you are looking for.

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11340
