### ISSUE TITLE
[Feature Request] Add flex-grow-2 through flex-grow-12

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#12600]
### Problem to solve
Creating flex items without the need of cols for special usecases.

### Proposed solution
Add flex-grow-2 through flex-grow-12
I think since everyone uses a 12 column layout 12 flex-grow properties should be enough.

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
