### ISSUE TITLE
[Feature Request] Missing close Event for v-select

### ISSUE THREAD

**Issue by jarkt** [vuetifyjs/vuetify#12601]
### Problem to solve
I need either an event when the selection list closes or the possibility to close it manually.
There is a blur event, but it's not the same as close. You could also see this as a bug, because I think, that the components behaviour should be the same as for the native select, which closes on blur. This is not configurable for the v-select component.

### Proposed solution
The list should close on blur or there should be a close event.

**Comment by jarkt** [comment]
After looking at the code, I noted I can just call the blur method on blur event. Little bit weird to read and more a workaround than solution, but works.

<v-select ref="test" @blur="$refs.test.blur($event)" :items="['foo', 'bar']" />

**Comment by Toilal** [comment]
It is possible to add a watcher on [isMenuActive data of v-select component](https://github.com/vuetifyjs/vuetify/blob/c6fcf4073c6459f9aa8a8ba2335e626a55140f37/packages/vuetify/src/components/VSelect/VSelect.ts#L120). Trying to use documented events has failed for me, as many use cases doesn't trigger any event at all (ESC key, click an already selected value, click outside of the browser ...)

With the composition API and TypeScript, you can write something like this to emit a 'menu:active' event containing a boolean value as payload matching the open/close state of v-select menu.

```html
<div>
  <v-select ref="selectRef"></v-select>
</div>
```

```typescript
setup (props, { emit }) {
  const selectRef = ref<Vue & { isMenuActive: boolean } | null>(null)

  watch(selectRef, (selectRefValue) => {
    if (selectRefValue != null) {
      watch(() => selectRefValue.isMenuActive, (active) => {
        emit('menu:active', active)
      })
    }
  })
}

return { selectRef }
```

**Comment by MrAlekhin** [comment]
i think there is an issue with timing to force `isMenuActive` to be false. So if I wrap it in timeout, this worked for me. 

```vue
<v-select
        ref="select"
        @keydown="handleKeydown"
    ></v-select>
```

```js
handleKeydown(e){
            e.preventDefault()
            if(this.$refs.select) {
                e.stopPropagation()
                setTimeout(()=>{
                    this.$refs.select.isMenuActive = false;
                }, 10)
            }
        }
```

**Comment by KaelWD** [comment]
Vuetify 3's select menu can be controlled manually with `v-model:menu`
