### ISSUE TITLE
[Feature Request] Simplify v-list components

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#12616]
### Problem to solve
First of all what's the difference between `v-list-group` and `v-list-item-group` ? the first one is just a component to group list items together. The second one also does similar thing. So I am asking if the following components can be simplified:

* v-list
* v-list-item
* v-list-item-action (this has same functions as v-list-item-icon! can this be consolidated? )
* v-list-item-action-text (Why we need this we can simply hav a div inside v-list-item and apply some text classes if needed)
* v-list-item-avatar (This is seems redundant, can we simply use v-avatar inside the v-list-item?) 
* v-list-item-content (Why we need this? can we just put stuff inside v-list-item directly, and apply some classes)
* v-list-item-group (this seems replicating the v-list-group. Can this be simplified?)
* v-list-item-icon (Seems redundant with v-list-item-action. Can we just use v-icon inside the v-list-item?)
* v-list-item-subtitle (Why we need this? can't just use a div and apply some text styling?)
* v-list-item-title (Why we need this? can't just use a div and apply some text styling?)

So my main concern is that we have so many similar components that can be used inside the v-list and I am asking if those can be simplified.

### Proposed solution
The proposed solution is to have only these following components inside the list
* v-list
* v-list-item
* v-list-group (or we can simply use the v-expansion-pannel here)

**Comment by yooneskh** [comment]
@mtermoul You said "add a div and apply some text styling" many times in your issue. The components you named are doing exactly this. They are some divs which apply some styles.

**Comment by KaelWD** [comment]
Yep, most of these just render something like `<div class="v-list-item--title">` with no actual behaviour. `v-list-item-avatar` and `v-list-group` also have list-specific styles that don't apply anywhere else. 

> v-list-item-group (this seems replicating the v-list-group)

`v-list-item-group` is for selection, `v-list-group` is expanding sections like `v-expansion-panel`
