### ISSUE TITLE
[Feature Request] SSR support for v-img

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [vuetifyjs/vuetify#12613]
### Problem to solve
It seems that v-img is unable to produce html with url when using `eager` prop in server-side rendering.

```html
<v-img eager src="/images/beta-logo-wide.png" />
```
 produces:

```html
<div class="v-image v-responsive wide-logo theme--light" data-v-1a9bb128="">
  <div class="v-image__image v-image__image--preload v-image__image--cover" style="background-image:;background-position:center center;"></div>
  <div class="v-responsive__content"></div>
</div>
```

And in frontend, it beocmes:
```html
<div class="v-image v-responsive wide-logo theme--light" data-v-1a9bb128="">
  <div class="v-responsive__sizer" style="padding-bottom: 26.6046%;"></div>
  <div class="v-image__image v-image__image--cover" style="background-image: url(&quot;http://localhost:3000/images/beta-logo-wide.png&quot;); background-position: center center;"></div>
  <div class="v-responsive__content" style="width: 2898px;"></div>
</div>
```
When server-side rendered html is loaded on the screen I see no image, when nuxt kicks off rendering in frontend, it makes the image appear with fade animation.

I think server-side rendered `v-img` should contain `background-image: url("http://localhost:3000/images/beta-logo-wide.png")` when using `eager` prop.

### Proposed solution
I suggest making `eager` prop make `v-img` include the url in SSR or introduce another prop to achieve that

**Comment by KaelWD** [comment]
This depends on an implementation of `isHydrating` for vue 3.
