### ISSUE TITLE
[Bug Report] $refs misbehave when ref is declared in a v-data-table item slot

### ISSUE THREAD

**Issue by thomasleveil** [vuetifyjs/vuetify#12617]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
```html
<v-data-table :headers="headers" :items="items">
    <template #item.name="{ value }">
        <v-chip ref="chipFromTable">{{ value }}</v-chip>
    </template>
</v-data-table>
```
- open [this codepen](https://codepen.io/thomasleveil/pen/QWEYZgZ?editors=1011)
- click the `SHOW $REFS` button

or 
- use a v-data-table slot `item.xxx`
- within that slot, use a vue component with a _ref_ name `chipFromTable`
- `this.$refs.chipFromTable` should be an array, but instead is a reference to a Vue component

### Expected Behavior
`this.$refs.chipFromTable` should be an array of length 3

### Actual Behavior
`this.$refs.chipFromTable` is a reference to the 3rd v-chip component

### Reproduction Link
<a href="https://codepen.io/thomasleveil/pen/QWEYZgZ?editors=1011" target="_blank">https://codepen.io/thomasleveil/pen/QWEYZgZ?editors=1011</a>

### Other comments
might be related to https://github.com/vuejs/vue/issues/4035#issuecomment-257139418

**Comment by KaelWD** [comment]
Vue 3 adds [function refs](https://v3.vuejs.org/api/special-attributes.html#ref) which can be used for custom behaviour. I don't think this is possible in Vue 2.6 unless you write your component as a render function so you can pass `refInFor` to the slot content.
