### ISSUE TITLE
[Documentation] v-tabs dynamic example

### ISSUE THREAD

**Issue by Ty213** [vuetifyjs/vuetify#12628]
### Environment

**Browsers:** Firefox 81.0
**OS:** Ubuntu undefined

### Steps to reproduce
Click remove tab button until all tabs are removed. Continue clicking remove tab button after all tabs are removed then try to add a new tab.

### Expected Behavior
After clicking new tab a new tab should be added.

### Actual Behavior
A new tab is not added.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tabs/#dynamic-tabs" target="_blank">https://vuetifyjs.com/en/components/tabs/#dynamic-tabs</a>

### Other comments
Remove tab button allows the user to decrement the length below 0.

**Comment by MajesticPotatoe** [comment]
its only if you try to try to remove a tab when there are no tabs present, as it throws an error that breaks the example.
