### ISSUE TITLE
[Feature Request] V-text-field

### ISSUE THREAD

**Issue by PRANAVAN12** [vuetifyjs/vuetify#12623]
### Problem to solve
Number Count Validation not Working Properly. Using Fakefiller Allowing Maximum length numbers

![image](https://user-images.githubusercontent.com/42197832/99224288-3e9d0e00-2810-11eb-9a27-a74a799f3cdd.png)

**Comment by jacekkarczmarczyk** [comment]
That sounds like a bug report, please create a a new issue with valid reproduction
