### ISSUE TITLE
[Bug Report] VTextField input value can get out of sync with components value property

### ISSUE THREAD

**Issue by jelle-eastground** [vuetifyjs/vuetify#12627]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
The Codepen-example uses an event handler for @input of the `<v-text-field/>`. This event handler removes all non-digits from the value (using a simple regex) and stores the result in `value`, which is used as a property value for `<v-text-field/>`. Adding non-digits (like 'fff') to the input will result in an unchanged property value and is not triggering any change.

Steps to reproduce:
*Append non-digits to the input's initial value ('fff'), so the resulting value is for instance '555fff'. The data `value` ('555') is now out of sync with the input widget's value ('555fff').
*Then append some digits (for instance '666'), now the input widget's value is correctly updated and results in '555666'.

### Expected Behavior
Widgets input value always in sync with value property. So when typing 'fff666', only digits should be visible all the time, omitting the 'fff'.

### Actual Behavior
When appending 'fff666' to the initial value '555', the input widget's value is only updated when appending a digit ('6').

### Reproduction Link
<a href="https://codepen.io/eastground/pen/VwjRbae" target="_blank">https://codepen.io/eastground/pen/VwjRbae</a>

**Comment by KaelWD** [comment]
This will happen with `<input>` too, you aren't actually updating `value` so there's no change for vue to respond to. 

```js
this.value = value
this.$nextTick(() => {
  this.value = value.replace(/[^0-9 ]/gi, '')
})
```

**Comment by jelle-eastground** [comment]
Thank you for the quick response, using $nextTick solved it!
