### ISSUE TITLE
[Documentation] example link site has v-content errors

### ISSUE THREAD

**Issue by shaderbytes** [vuetifyjs/vuetify#12624]
### Environment

**Browsers:** Chrome 86.0.4240.198
**OS:** Windows 10

### Steps to reproduce
go to page , then click the hyperlink "Vuetify cards work" in the first paragraph. This links out to an external website named scrimba.com but if you try run any examples on this page it generates a warning " [Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead." Also the preview window does not update according to the section you are selecting , making the entire site useless. 

### Expected Behavior
preview should update when relevant selections are made

### Actual Behavior
preview DOES NOT update when relevant selections are made , on screen warnings

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/cards/" target="_blank">https://vuetifyjs.com/en/components/cards/</a>

**Comment by johnleider** [comment]
My suggestion would be to contact the scrimba team.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
