### ISSUE TITLE
[Bug Report] Ratings props.isHovered isn't working

### ISSUE THREAD

**Issue by MariaNicolosi** [vuetifyjs/vuetify#12629]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.183
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to access the isHovered prop in the v-ratings item slot.

### Expected Behavior
isHovered should be true with the icon is hovered

### Actual Behavior
the isHovered prop value does not change

### Reproduction Link
<a href="https://codepen.io/marianicolosi/pen/dyXrmEj?editors=1111" target="_blank">https://codepen.io/marianicolosi/pen/dyXrmEj?editors=1111</a>

**Comment by nekosaur** [comment]
ah, we're not passing the listeners to the scope so that they can be attached.

**Comment by johnleider** [comment]
fixed by #13410

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
