### ISSUE TITLE
[Bug Report] Snackbar transition doesn't initially run if the initial (display) value is true

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12621]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.11
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
1. Create v-snackbar that uses any transition (as a prop) with :value="true", or a v-model="variable" with a variable that's initially true. (Alternatively change the "key" prop while the variable is true.)
2. Look at the created snackbar

### Expected Behavior
The transition is properly configured, so the new users who follow documentation expect the initial animation to run, which is arguably more intuitive behavior of snackbars, and an expected default based on https://material.io/components/snackbars#behavior

### Actual Behavior
The snackbar appears immediately. Its transition only runs when closing, forcing users to research, experiment and look for root causes, along with Vue-specific workarounds (if the newly displayed component has to be rendered directly, e.g. via v-if) like setTimeout (requiring a new method without any declarative alternative)

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/oNLVNVP" target="_blank">https://codepen.io/cTAlENtATI/pen/oNLVNVP</a>

### Other comments
* Nowhere in the Component's documentation have I found a mention about this behavior exception during initial displaying, and the transition prop in API docs barely says "Sets the component transition.". This lack of transparency contributes to a steep learning curve.
* Documentation of Transitions also doesn't mention this behavior, except saying that many components support this prop. (I haven't tested all possible component combinations yet.)

**Comment by KaelWD** [comment]
No component transitions run initially. I understand how that may be confusing but it's consistent with the rest of the framework.

**Comment by scscgit** [comment]
Is there a chance you could at least systematically document (& maintain support of) some "recommended workaround" for this use-case? I'm sure there will be many users who need it to run initially (which in Vue obviously doesn't require page to be reloaded), and I'd argue that it's the most logical usage (you create a component when you want to display it). Thanks.
