### ISSUE TITLE
[Feature Request] Disable autocomplete fields in forms

### ISSUE THREAD

**Issue by dannylg** [vuetifyjs/vuetify#12650]
### Problem to solve
In all forms that have email fields and password the browser autocompletes the field with the email and password that is saved to log in to the browser. The "form" component does not have a property to disable autocompletes so it gets uncomfortable every time you have a form to complete.

### Proposed solution
In HTML the form tag has the autocomplete property that receives the "off" parameter to disable autocomplete on forms that do not require them.

**Comment by KaelWD** [comment]
v-form passes all attributes through to the underlying `<form>` element. If `autocomplete="off"` isn't working it's probably because browsers ignore it a lot of the time: #10184
