### ISSUE TITLE
[Feature Request] Allow RGB and HSL string specification in vuetify themes

### ISSUE THREAD

**Issue by DanielAsher** [vuetifyjs/vuetify#12653]
### Problem to solve
HSL provides a natural encoding of colours that is easily readable. Hex requires a great deal of experience to read effectively.

### Proposed solution
This could be supported by modifying the parsing function `colorToInt` in [colorUtils]
(https://github.com/vuetifyjs/vuetify/blob/78b0ae2bd2d8b843417250f0cd3bcecf99604112/packages/vuetify/src/util/colorUtils.ts#L26)

I would be happy to provide a PR if this was a feature that would be supported.

**Comment by KaelWD** [comment]
You should use an external library for this: https://culorijs.org/api/#formatHex
