### ISSUE TITLE
[Bug Report] v-stepper skips animation sometimes

### ISSUE THREAD

**Issue by jarkt** [vuetifyjs/vuetify#12659]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.12
**Browsers:** Firefox 82.0
**OS:** Ubuntu undefined

### Steps to reproduce
Switch some times between the two steps.

### Expected Behavior
Proper fade-out animation.

### Actual Behavior
Fade-out animation is sometimes not showed.

### Reproduction Link
<a href="https://codepen.io/JT2809/pen/RwRXwKR" target="_blank">https://codepen.io/JT2809/pen/RwRXwKR</a>

### Other comments
Years ago there was already the same error: https://github.com/vuetifyjs/vuetify/issues/3161

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
