### ISSUE TITLE
[Documentation] Old URL gets redirected to completely blank page

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#12654]
### Environment

**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
- Google search for "vuetify a la carte"
- Click the first result, https://vuetifyjs.com/customization/a-la-carte
![image](https://user-images.githubusercontent.com/5017521/99831868-98ede580-2b14-11eb-8b8f-7b73c5da7d9b.png)

### Expected Behavior
Redirects to https://vuetifyjs.com/en/features/treeshaking/#vuetify-loader, or at least to a non-blank page.

### Actual Behavior
Redirects to a completely blank page.
![image](https://user-images.githubusercontent.com/5017521/99832041-d94d6380-2b14-11eb-8e4d-e935261e7a00.png)

### Reproduction Link
<a href="https://vuetifyjs.com/customization/a-la-carte" target="_blank">https://vuetifyjs.com/customization/a-la-carte</a>

**Comment by MajesticPotatoe** [comment]
Thats because the page doesn't exist anymore. proper page would be the second result <https://vuetifyjs.com/en/features/treeshaking/>

**Comment by davidstackio** [comment]
@ascott18 It looks like this is fixed now so the issue should be closed. https://vuetifyjs.com/customization/a-la-carte redirects to https://vuetifyjs.com/en/features/treeshaking/.
