### ISSUE TITLE
[Bug Report] v-color-picker slider stops working after clicking on specific swatch

### ISSUE THREAD

**Issue by D3SOX** [vuetifyjs/vuetify#12655]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.67
**OS:** Linux x86_64

### Steps to reproduce
1. Click on the last swatch
2. Try to use the top slider

### Expected Behavior
It should work as usual

### Actual Behavior
It doesn't change the color

### Reproduction Link
<a href="https://codepen.io/d3sox/pen/dyXBjVM" target="_blank">https://codepen.io/d3sox/pen/dyXBjVM</a>

### Other comments
I don't know what it depends on, but I tried to change the order, but it only seems to happen on the gray #9E9E9E

**Comment by nekosaur** [comment]
This is not a bug. Grayscale colors are achromatic, they have zero saturation. You can see the same behaviour here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) if you use Chrome, or for example this library (https://simonwep.github.io/pickr/)

**Comment by D3SOX** [comment]
I see. When I remove `hide-inputs` and `hide-canvas` it becomes clear. Thanks for the explanation!
