### ISSUE TITLE
[Bug Report] `checked` icon no longer available in v2.0

### ISSUE THREAD

**Issue by longrunningprocess** [vuetifyjs/vuetify#12652]
### Environment
**Vuetify Version:** 2.3.18
**Last working version:** 1.5.24
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 10.15.7

### Steps to reproduce
`<v-icon right>checked</v-icon>` used inside a button (appended) will create a much wider button

### Expected Behavior
check icon should've appeared

### Actual Behavior
it appears but the button width changes drastically

### Reproduction Link
<a href="https://codepen.io/longrunningprocess/pen/PozvKLo" target="_blank">https://codepen.io/longrunningprocess/pen/PozvKLo</a>

### Other comments
simply changing to `<v-icon right>check</v-icon>` resolves it.

**Comment by KaelWD** [comment]
This depends on the version of material icons you're using, not vuetify.

**Comment by DRoet** [comment]
Also in the 2.0 release notes:

`Changed the default iconfont from Google Material Icons to Material Design Icons`

**Comment by longrunningprocess** [comment]
yep, you're right...didn't realize there would be name changes but I totally get that now.
