### ISSUE TITLE
[Bug Report] month and date picker on same page breaks date picker

### ISSUE THREAD

**Issue by Logikgate** [vuetifyjs/vuetify#12668]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on the text field to activate the Month picker
2. Click off of it to hide it
3. Use the v-select and change to two, this will hide the Month picker using a v-if and then show the Date picker.
4. Click on the text field to activate the Date picker.  No dates will be shown and a console error is produced from what looks to be v-date-picker-header.

![Nov-24-2020 12-59-22](https://user-images.githubusercontent.com/2379994/100133625-02dbf700-2e55-11eb-825b-5f6863feedee.gif)

### Expected Behavior
Both date pickers should work when used in v-ifs

### Actual Behavior
The Date picker is broken if the Month picker is shown and then hidden via a v-if

### Reproduction Link
<a href="https://codepen.io/logikgate/pen/ExgYVwr?editors=1010" target="_blank">https://codepen.io/logikgate/pen/ExgYVwr?editors=1010</a>

### Other comments
If you use v-shows instead of v-ifs both pickers will work but this should work with v-ifs as well.

**Comment by chasekafei** [comment]
Hey! Have you got a solution?
I have the same problem as you and have to use v-show instead.

**Comment by jacekkarczmarczyk** [comment]
Not sure atm what's exactly the cause of the problem, but `<v-date-picker :key="selection"` seems to fix it

**Comment by matteoc99** [comment]
had the same problem with one date-picker switching between the types: date and month
my only solution was also with a key by doing: :key="'date-picker-' + someVariable" and increasing the variable every time the type prop changed

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
