### ISSUE TITLE
[Bug Report] v-radio-group does not generate valid html

### ISSUE THREAD

**Issue by DonTomasso** [vuetifyjs/vuetify#12664]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.67
**OS:** Mac OS 11.0.1

### Steps to reproduce
Add label prop to a v-radio-group component

### Expected Behavior
Should generate valid html

### Actual Behavior
Html validation error **Element “legend” not allowed as child of element “div” in this context.**

### Reproduction Link
<a href="https://codepen.io/dontomasso/pen/GRjKKgw" target="_blank">https://codepen.io/dontomasso/pen/GRjKKgw</a>

### Other comments
Solution: v-radio-group should output as a tag `<fieldset>` instead of `<div>`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
