### ISSUE TITLE
[Bug Report] Vuetify stepper content scroll issues upper elements are not visible when switching from a step with more elements you have to scroll up manually to be able to view the contents at the top 

### ISSUE THREAD

**Issue by faithfulojebiyi** [vuetifyjs/vuetify#12665]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.183, Google Chrome, Mozilla Firefox
**OS:** Windows 10, Android

### Steps to reproduce
Check out the code in the Codepen

### Expected Behavior
when you switich from one step to the other regardless of length of the content of the previous step the you should be able to view the very frist content of the current step

### Actual Behavior
Vuetify stepper content upper elements are not visible when switching from a step with more elements you have to scroll up manually to be able to view the contents above. This can be seen when switing from step 2 to 3 and 3 to 4.  works well from step 1 to 2 because step one has fewer contents

### Reproduction Link
<a href="https://codepen.io/faithfulojebiyi/pen/PoGYoYP" target="_blank">https://codepen.io/faithfulojebiyi/pen/PoGYoYP</a>

**Comment by faithfulojebiyi** [comment]
i was able to fix this by adding this code to every `v-on:click` function that transition between steps

for example we have let say we have this on a step

        ```
  <v-row class="px-6 pb-4">
            <v-btn
              text
              @click="e1 = 2; scrollTop();"
            >
              Previous
            </v-btn>
            <v-spacer></v-spacer>
            <v-btn
              color="primary"
              @click="e1 = 4; scrollTop();"
            >
              Continue
            </v-btn>
          </v-row>
```
in my script 
```
<script>
   methods: {
    scrollTop () {
      setTimeout(() => {
        window.scrollTo({
          top: 0
        })
      }, 1000)
    }
}
<script>
```
the `setTimeout` function is to give room for the step transition to take place before setting the scroll postition back to top on the current also new step

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
