### ISSUE TITLE
[Bug Report] v-hover with v-show only working to hide sub components not show

### ISSUE THREAD

**Issue by dhubbard-ag** [vuetifyjs/vuetify#12677]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
I am attempting to use `v-hover` wrapping a set of `v-icon` elements with `v-show`in a `v-data-table` cell to only show the buttons when the user hovers over a cell.

In linked "Reproduction Link" icons are replaced with a `v-card-text`

Steps:

1) With "data.showActions" = true
- All "Actions" cells show in table on initial load - this was to check the role of the `:value` property on `v-hover`

2) When mouse hovers over an action cell and is then moved off - the cell is cleared (hidden)

3) The cell does not re-show when the mouse is moved back onto the cleared Cell.

4) With "data.showActions" = false - which was my proposed initial setting (to only show the cell when the mouse hovers over the cell)
- No data is shown in the "Action" cells

5) When mouse hovers over the cell the component wrapped by "v-hover" is not shown

6) Moving out or back into the cell does not show the content

### Expected Behavior
I was expecting that when the cell was hovered the `v-hover` would set the `hover` attribute and the contained `div` would show based on `v-show=hover`. 

I expected this to be that case when the `:value` property is `false` i.e. set `hover` to `false` initially and therefore hide the `div`, but on hover flip the `hover` slot and therefore show it.

My suspicion is that `v-show` uses `display:none;` and once set there is no element in DOM to catch the following hover over. Is there an alternative way to hide using `opacity:0`

The "Using class/opacity" column shows example of behaviour required - to only show when hover is over.

### Actual Behavior
In both cases (with :value set to false and true) hovering over a cell does not trigger showing the contents. 

It appears that some level of control is provided - in that when :value is true moving away from the cell does hide it, but in neither case the cell is shown directly on hover.

### Reproduction Link
<a href="https://codesandbox.io/s/billowing-bash-47bor?file=/src/components/DataTable.vue" target="_blank">https://codesandbox.io/s/billowing-bash-47bor?file=/src/components/DataTable.vue</a>

**Comment by KaelWD** [comment]
`v-show` uses `display: none` which prevents mouse events, use `visibility: hidden` or `opacity: 0` instead.
