### ISSUE TITLE
[Bug Report] v-carousel prev/next buttons should stopPropagation

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#12676]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.12
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
v-carousel with next/previous buttons with a parent component like a card with a @click event. See the linked repro.

### Expected Behavior
Clicking the previous and next buttons of a carousel should ~~prevent default~~ stopPropagation to stop the click event bubbling to parent elements.

### Actual Behavior
Click event bubbles to parent elements, which in some cases where clicking the parent element would navigate the app, this makes the prev/next buttons unusable.

### Reproduction Link
<a href="https://codepen.io/andrewharvey/pen/oNzNzNg" target="_blank">https://codepen.io/andrewharvey/pen/oNzNzNg</a>

**Comment by vonec** [comment]
this merge doesn't handle the :to property, this handles only the @click event bound kindly look into this,
