### ISSUE TITLE
[Feature Request] Get the interval start-end on click time

### ISSUE THREAD

**Issue by kno** [vuetifyjs/vuetify#12680]
### Problem to solve
This is a clone of https://github.com/vuetifyjs/vuetify/issues/7237 providing a reproducible environment at https://codepen.io/kNo/pen/rNMNdzJ

I clicked on 09:23 am.
My interval is from 09:00 am to 09:30 am, then i wanna take this data.
Greetings!!

### Proposed solution
The object passed to method should had info about interval.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
