### ISSUE TITLE
[Documentation] No link to VRangeSlider examples page

### ISSUE THREAD

**Issue by jblachly** [vuetifyjs/vuetify#12683]
### Environment

**Browsers:** Firefox 82.0
**OS:** Mac OS 10.14, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
There is a link to v-range-slider API at the bottom of the v-slider Examples page, but there is no link to the v-range-slider (VRangeSlider) component examples page (https://vuetifyjs.com/en/components/range-sliders/) either from the UI components list in the left menu nav, nor from the v-slider page.

### Expected Behavior
There should be a link on the left hand nav, and ideally within the VSlider component examples page as well.

### Actual Behavior
There is no link.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/sliders/" target="_blank">https://vuetifyjs.com/en/components/sliders/</a>

### Other comments
I found VRangeSlider components example page via a Google search, so it is still indexed, likely from a prior version of the documentation.

**Comment by MajesticPotatoe** [comment]
This has been resolved in b3ca076
