### ISSUE TITLE
[Documentation] language not changing 

### ISSUE THREAD

**Issue by vishnuprasadu** [vuetifyjs/vuetify#12686]
### Environment

**Browsers:** Chrome 86.0.4240.198
**OS:** Windows 10

### Steps to reproduce
change to chinese then change to english . you could see language has not changed back to english 

### Expected Behavior
complete translation

### Actual Behavior
partial translation

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/cards/" target="_blank">https://vuetifyjs.com/en/components/cards/</a>

**Comment by LuckyHookin** [comment]
![test](https://user-images.githubusercontent.com/45350455/101852527-cfa99f80-3b98-11eb-8537-c6832c6ff585.gif)

**Comment by MajesticPotatoe** [comment]
resolved in a09ff2f
