### ISSUE TITLE
[Feature Request] cell border for datatable

### ISSUE THREAD

**Issue by robertzml** [vuetifyjs/vuetify#12694]
### Problem to solve
offer more styles for datatable, 
the all cell border in table may look pretty in some situation.

### Proposed solution
add a prop for v-data-table.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
