### ISSUE TITLE
Issue in change icon sources from Material Icons to Material Design Icons.

### ISSUE THREAD

**Issue by jhon-andrew** [vuetifyjs/vuetify#1269]
I decided to use [Material Design Icons](https://materialdesignicons.com/) over [Material Icons](https://material.io/icons). The problem is there is no documented option for `v-toolbar-side-icon` to change the icon its using. It show the word 'MENU' which means its still using material-icons classes.

Currently I do this as a workaround:
```js
document.onreadystatechange = () => {
    document.querySelector('.btn__content').innerHTML = '<i class="mdi icon mdi-menu"></i>'
}
```

Is there something I missed in the documentation or changing of icons for `v-toolbar-side-icon` is not yet available?

**Comment by tommygarces** [comment]
You could use it like this:

`<v-toolbar-side-icon><v-icon>mdi-menu</v-icon></v-toolbar-side-icon>`

**Comment by yuminatwca** [comment]
No, it does not work.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
