### ISSUE TITLE
[Bug Report] No option to float a FAB on the vertical edge of a container

### ISSUE THREAD

**Issue by jorisdemange** [vuetifyjs/vuetify#12696]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 11.0.0

### Steps to reproduce
insert a v-btn FAB in a v-navigation-drawer

### Expected Behavior
FAB should be floating on the right edge of the drawer
(See https://material.io/components/buttons-floating-action-button#placement, 2nd example)

### Actual Behavior
Instead, it floats on the bottom edge of the drawer, like it would for a nav bar.

### Reproduction Link
<a href="https://codepen.io/jorisd/pen/bGwdEqq" target="_blank">https://codepen.io/jorisd/pen/bGwdEqq</a>

### Other comments
Manually adjusting negative margins and "Bottom/Right" CSS properties is not a solution because the FAB will be covered by the "overflow:hidden" of the drawer. And that's counter-intuitive.

**Comment by bigbadfatman** [comment]
I don't think the fab property is supposed to automatically decide where the fab should be positioned. It would seem to me that the only reason for the prop, is to quickly style it similar to a fab. You can play with the positioning yourself.

I've modified your code a little but to achieve the effect you are looking for, see if this works for you.
https://codepen.io/bigbadfatman/pen/GRjmKYB

It is a quick dirty hack, and might have some other unintended bugs, because I've used overflow to show the button. If you move the button outside the navigator, you could avoid that.

**Comment by Vercadium** [comment]
For what it's worth, I have now worked on 2 different Vuetify applications for 2 different companies, both of which have had their designers ask for this - overlaying a drawer toggle button over the edge. Please consider supporting this 🙂 👍

**Comment by AlexDaniel** [comment]
Just had to implement exactly the same thing. The workaround is to add a `v-btn` with `fab right absolute` and `mr-n11` class. So far didn't see any issue with that. It's a total hack but I think it works.

**Comment by jorisdemange** [comment]
> For what it's worth, I have now worked on 2 different Vuetify applications for 2 different companies, both of which have had their designers ask for this - overlaying a drawer toggle button over the edge. Please consider supporting this 🙂 👍

> Just had to implement exactly the same thing. The workaround is to add a `v-btn` with `fab right absolute` and `mr-n11` class. So far didn't see any issue with that. It's a total hack but I think it works.

Thanks guys! As said, that's a total hack. I ended up using a similar workaround, but there should be a native way to do this since this is a Material principle. Should it then be moved to feature request? 🧐

**Comment by AlexDaniel** [comment]
Just one more note regarding that negative margin hack – for `xs` views you need to remove the `mr-n11` class or figure out something else, because on portrait mobile views the button will be half way out of the screen.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
