### ISSUE TITLE
[Bug Report] icon in the Vuetify documentation / codepen isn't correct - https://vuetifyjs.com/en/components/treeview/#selectable-icons

### ISSUE THREAD

**Issue by jdl2206** [vuetifyjs/vuetify#12697]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 3.0.3
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 10.15.7

### Steps to reproduce
click on this link: https://vuetifyjs.com/en/components/treeview/#selectable-icons
Click on vue source.
Notice that the icon code specifies mdi-beer in the <v-icon part of the code but the code displays the mdi-bookmark-outline icon from the v-treeview part of the code instead. Is the <v-icon code supposed to do something?

Click on the icon to view the code in codepen.
The same issue is there. This code does not display the mdi-beer from the v-icon. Should it?
 <v-icon
                  left
                  small
                >
                  mdi-beer
                </v-icon>

I'm trying to use this code as an example of being able to selectively override the icons specified in the <v-treeview part of the code but the <v-icon code seems to be ignored.

### Expected Behavior
The icons in this part of the code
`<v-treeview
              v-model="tree"
              :load-children="fetch"
              :items="items"
              selected-color="indigo"
              open-on-click
              selectable
              return-object
              expand-icon="mdi-chevron-down"
              on-icon="mdi-bookmark"
              off-icon="mdi-bookmark-outline"
              indeterminate-icon="mdi-bookmark-minus"
            >
            </v-treeview>`

 are overriding the icons in this part of the code:
`
 <v-icon
                  left
                  small
                >
                  mdi-beer
                </v-icon>
`

### Actual Behavior
The icons are mdi-bookmark-outline

### Reproduction Link
<a href="https://codepen.io/jdl_aisd/pen/vYXOKzP?editors=101" target="_blank">https://codepen.io/jdl_aisd/pen/vYXOKzP?editors=101</a>

### Other comments
If you could please fix this code/documentation, that would be very helpful! Also, if there's a way to add a selectable icon that then displays the associated website such as the website_url from the example data, that would be extremely helpful.

**Comment by KaelWD** [comment]
The `mdi-beer` icon is in a chip, not the treeview. 
![image](https://user-images.githubusercontent.com/16421948/100692559-3b447d80-33df-11eb-9c3e-5afdc38db103.png)

**Comment by jdl2206** [comment]
Thanks very much for the clarification! I'm just getting started with Vue
js. So much to learn.
