### ISSUE TITLE
[Task] v-sheet

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#12692]
# Overview

- Related Tasks: ~~#12789~~
- Related Issues: N/A
- Related Pull Requests: ~~#12542~~

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by renoirb** [comment]
✋🏾 ,

Branch pushed?

**Comment by renoirb** [comment]
As I understand it, a `v-sheet` is basically a 2D shape we might want to add border radius in its corners, and an elevation and drop shadow.

Since there's something in the works for border-radius (roundable) there might be something missing for elevation?

**Comment by johnleider** [comment]
Yes, this is on a separate branch, but I went on vacation. Will follow-up soon.
