### ISSUE TITLE
Sidebar sidebar-under-toolbar prop not existing

### ISSUE THREAD

**Issue by John0x** [vuetifyjs/vuetify#127]
Hey, the sidebar-under-toolbar of the sidebar is missing even though it has been mentioned in the version release description.

**Comment by johnleider** [comment]
Possibly something lost in a merge. Will fix

**Comment by joshbodine21** [comment]
It is working for me when I add it to v-app

**Comment by johnleider** [comment]
That is correct. This prop is used on the v-pp component. Does this resolve your issue john?

**Comment by John0x** [comment]
Ah yeah, it does, thanks :)
The description of the version is just a bit misleading:
``Added sidebar-under-toolbar prop to Sidebar. This will position a fixed sidebar under the toolbar``
