### ISSUE TITLE
[Task] v-app-bar

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#12707]
# Overview

- Related Tasks: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
Initial implementation complete, awaiting scrolling techniques.

**Comment by johnleider** [comment]
Initial port and scrolling techniques have been implemented. Closing as complete.

**Comment by Dominic-Marcelino** [comment]
Looks like shrink-on-scroll is not included yet and haven't found a specific issue. Is there any roadmap for it?

https://github.com/vuetifyjs/vuetify/blob/104dd4f696673652ee5f4c9439ccd4c50fffb043/packages/vuetify/src/components/VAppBar/VAppBar.tsx#L62

**Comment by Dominic-Marcelino** [comment]
@johnleider the fullyHide and shrink options are still missing. Is this on purpose and they're removed or have they just been overseen?

**Comment by johnleider** [comment]
> @johnleider the `fullyHide` and `shrink` options are still missing. Is this on purpose and they're removed or have they just been overseen?

Technological hurdle. As opposed to delaying it further we released with those on the back burner.
