### ISSUE TITLE
Footer is shifted up when using a dense toolbar

### ISSUE THREAD

**Issue by ryanmortier** [vuetifyjs/vuetify#1271]
### Steps to reproduce
 - Setup simple app layout with a `dense` toolbar and footer

### Versions
- Latest Vuetify
- Latest Chrome browser

### What is expected ?
Expect footer to extend to the bottom of the window

### What is actually happening ?
Footer doesn't extend to the bottom because using a dense toolbar shifts it up slightly

### Reproduction Link
https://codepen.io/anon/pen/dzNOXJ

![screen shot 2017-08-06 at 1 10 10 am](https://user-images.githubusercontent.com/2053960/29000778-9c228b54-7a44-11e7-991a-82715cfcd4f8.png)

**Comment by jacekkarczmarczyk** [comment]
fix proposal in PR https://github.com/vuetifyjs/vuetify/pull/1275

**Comment by ryanmortier** [comment]
I noticed another issue when using the dense toolbar. The navigation drawer doesn't accomadate the height of the dense bar when using `clipped`.

![image](https://user-images.githubusercontent.com/2053960/29077745-cc1c89f2-7c26-11e7-9015-1a90e315bb5f.png)

**Comment by johnleider** [comment]
All layout issues have been resolved in the enhancement/layout branch (will be part of 0.16)
