### ISSUE TITLE
[Bug Report] V-select click:append events breaks component and potential enhancement

### ISSUE THREAD

**Issue by Dinuz** [vuetifyjs/vuetify#12713]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
Just add the click:append event  and when clicking on the icon the event completely blocks the dropdown behavior and the menu doesn't really work anymore.

### Expected Behavior
The click should not affect the normal dropdown behavior!

### Actual Behavior
The click makes the dropdown not working anymore (the click works but it doesn’t trigger the menu anymore)

### Reproduction Link
<a href="https://codepen.io/dinuz/pen/qBadXBQ" target="_blank">https://codepen.io/dinuz/pen/qBadXBQ</a>

### Other comments
The problem persists as mentioned by @pmagix also in version 2.3.19 .
I am trying to add a not scrollable header to the v-select menu, and after a bit of crazy work I was able to get it as I wanted.
Clearly would be much easier and probably cleaner if we could access directly the v-menu component inside the select using an extra slot ( I used the append-outer, attached the menu to it, and positioned the header with css); you need to have the header or the footer outside the menu list flow, otherwise it scrolls with the rest of the items.

My solution "more or less works", but to make the header appear or disappear with the menu I need to rely on the focus, blur and click:append events. Focus and blur are working as expected, instead the click:append event completely blocks the dropdown behavior and the menu doesn't really work anymore.

codepen

@johnleider do you think we can add an extra slot (maybe a couple) to allow adding elements before and after the menu content inside the menu but outside the items list?
Just think of it as something like an header and a footer around the scrollable items list.

Originally posted by @Dinuz in #10839 (comment)
 
Write
Preview

**Comment by dmoKruso** [comment]
My problem was with "click" event. And the problem only happens on the 1st fire. The first time I click on the v-select button, above the append icon, the select would not open.

For my scenario I found an workaround by adding eager prop to the v-select.

**Comment by johnleider** [comment]
This is resolved as of v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
