### ISSUE TITLE
[Bug Report] Click on v-autocomplete or v-select if it have attribute readonly, change classes on active

### ISSUE THREAD

**Issue by frOstzz** [vuetifyjs/vuetify#12719]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.66
**OS:** Linux x86_64

### Steps to reproduce
Focused on field

### Expected Behavior
don't change active classes for autocomplete

### Actual Behavior
Change active classes for autocomplete

### Reproduction Link
<a href="https://codepen.io/frOstzz/pen/abmvVOm" target="_blank">https://codepen.io/frOstzz/pen/abmvVOm</a>

### Other comments
I think this component if have readonly attribute, don't change on active classes. You have, component, but another style, which not change classes

**Comment by KaelWD** [comment]
Readonly inputs can still be focused and need some way to indicate that. If you want the field to be completely non-interactive use `disabled` instead.
