### ISSUE TITLE
[Bug Report] retain-focus on v-dialog does not work

### ISSUE THREAD

**Issue by paulamuchinski** [vuetifyjs/vuetify#12720]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.66
**OS:** Linux x86_64

### Steps to reproduce
-Open dialog
- Click tab 2x

### Expected Behavior
Keep focus on dialog

### Actual Behavior
Focus leave the dialog

### Reproduction Link
<a href="https://codepen.io/paulamuchinski/pen/OJRyZEN?editors=101" target="_blank">https://codepen.io/paulamuchinski/pen/OJRyZEN?editors=101</a>

**Comment by KaelWD** [comment]
- retain-focus is already enabled by default
 - it doesn't prevent tab focus to the rest of the browser UI or other frames, try putting a text field next to the button and you'll see the difference.
