### ISSUE TITLE
[Feature Request] v-data-table: custom-filter, custom-sort, custom-group should have a fallback to the default functionality 

### ISSUE THREAD

**Issue by HDenizD** [vuetifyjs/vuetify#12722]
### Problem to solve
if you are like me and you created a base table for all your incoming tables in your project you will have a problem as soon as you start to make one of your tables have a custom-filtering to handle edge cases for very special stuff. for me it's filtering german date time.

the problem is, once you apply the custom-filter prop to your root table, all child tables are forced to have a custom filtering as well.
having a opportunity to define the custom-filter, etc. to have a fallback to default functionality would fix this problem.

### Proposed solution
imagine you have  a base table like this.
this would be the base of all the tables in your project.
### Base Table
```html
<v-data-table
        :headers="tableHeaders"
        :items="tableItems"
        :search="search"
        :sort-by="sortBy"
        :sort-desc="sortDesc"
        :disable-pagination="disablePagination"
        :items-per-page="itemsPerPage"
        :header-props="{ sortByText: 'sort by...' }"
        :footer-props="footerProps"
        :show-expand="showExpand"
        :expanded.sync="expanded"
        :item-key="ids"
        :item-class="itemClass"
        no-data-text="no data"
        :hide-default-footer="hideDefaultFooter"
        locale="de"
        :server-items-length="serverItemsLength"
        :options="options"
        :custom-filter="customFilter"
        @update:options="$emit('update:options', $event)"
        @click:row="decideWhichClickHandler"
      />
```
you have a bunch of options to toggle and you know it's all just in this very table. that keeps the table a little bloated but makes all the child of that base table much smoother to use.

know we need to handle props from child to this base table

we define the props in the base table like this, here comes the sexy part:
```javascript
props: {
    customFilter: {
      type: Function,
      default: () => backToDefaultFilter or null or whatEver
    },
    {...}
```
with a default for the prop `customFilter` we are able to handle a fallback to the default filtering.

### Child Table

```html
              <child-table
                class="child-table mx-auto w-100"
                table-type="childTable"
                :sort-by="['x']"
                sort-desc
                :table-headers="table.headers"
                :table-items="table.items"
                :row-click-handler="rowClickHandler"
                :custom-filter="filterDate"
              />
```
then we can use the custom-filter as optional prop for our tables and it would not affect our other tables filter functionality

**Comment by KaelWD** [comment]
If you pass `undefined` to the prop it'll use the default value.
