### ISSUE TITLE
[Documentation] v-treeview-node - examples how to use this component

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12738]
### Environment

**Browsers:** Chrome 87.0.4280.66
**OS:** Windows 10

### Steps to reproduce
Hello,
Could you add some examples in the docs how to use the `v-treeview-node` component? Right now there are no examples how to use this component.

### Expected Behavior
Docs should contain some examples how to use the `v-treeview-node` component.

### Actual Behavior
There are no examples how to use the `v-treeview-node` component.

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-treeview-node/" target="_blank">https://vuetifyjs.com/en/api/v-treeview-node/</a>

**Comment by nekosaur** [comment]
`v-treeview-node` is not a public component. It is used internally by `v-treeview`

**Comment by Mikilll94** [comment]
@nekosaur 
So why it is present in the docs? Maybe it should be marked in the docs that this is an internal Vuetify component?

**Comment by nekosaur** [comment]
It is a mistake. Which is why I tagged the issue with the `documentation` label.
