### ISSUE TITLE
[Bug Report] v-range-slider doesn't obey prop track-fill-color

### ISSUE THREAD

**Issue by barrabinfc** [vuetifyjs/vuetify#12733]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.89, Mozilla Firefox, Google Chrome
**OS:** Windows, Linux x86_64

### Steps to reproduce
1. Instanciate component v-range-slider with a custom color for prop `track-fill-color`

```
      <v-range-slider v-model="hue" min=0 max=360 track-fill-color="green" />
```

### Expected Behavior
The value of property `track-fill-color` should update the color of element `v-slider__track-fill`

### Actual Behavior
Always rendered with color `primary`

### Reproduction Link
<a href="https://codepen.io/barrabinfc/pen/qBabzeP" target="_blank">https://codepen.io/barrabinfc/pen/qBabzeP</a>

### Other comments
It's working as expected on brother component `v-slider`

**Comment by dchinu97** [comment]
@KaelWD Seems like an interesting good first issue to work on, can you please assign it to me?
