### ISSUE TITLE
[Bug Report] npm run build error

### ISSUE THREAD

**Issue by TabrizGulmemmedov** [vuetifyjs/vuetify#12736]
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.2.11
**Vue Version:** 2.6.1
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
I added typescript to an existing project. The following error occurs when executing the `npm run build` command:

ERROR  Failed to compile with 1 errors11:14:41 AM
 error  in /builds/sales-and-inventory-management-group/sims-frontend/src/main.ts
ERROR in /builds/sales-and-inventory-management-group/sims-frontend/src/main.ts(13,9):
13:9 No overload matches this call.
  Overload 1 of 2, '(plugin: PluginObject<unknown> | PluginFunction<unknown>, options?: unknown): VueConstructor<Vue>', gave the following error.
    Argument of type 'Vuetify' is not assignable to parameter of type 'PluginObject<unknown> | PluginFunction<unknown>'.
      Property 'install' is missing in type 'Vuetify' but required in type 'PluginObject<unknown>'.
  Overload 2 of 2, '(plugin: PluginObject<any> | PluginFunction<any>, ...options: any[]): VueConstructor<Vue>', gave the following error.
    Argument of type 'Vuetify' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
      Property 'install' is missing in type 'Vuetify' but required in type 'PluginObject<any>'.
    11 | 
    12 | Vue.use(VueTheMask);
  > 13 | Vue.use(Vuetify);
       |         ^
    14 | Vue.use(Vue2Editor);
    15 | Vue.use(VueToastr);
    16 | 
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sims-frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sims-frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-05T11_14_41_835Z-debug.log

### Expected Behavior
.

### Actual Behavior
.

### Reproduction Link
<a href="https://codepen.io/tbriz-g-l-ov/pen/QWKNENZ" target="_blank">https://codepen.io/tbriz-g-l-ov/pen/QWKNENZ</a>

**Comment by sarahLardeau** [comment]
I got the same issue when upgrading vuetify from 2.3.13 to 2.3.19

```
ERROR in src/main.ts(121,9):
No overload matches this call.
  Overload 1 of 2, '(plugin: PluginObject<unknown> | PluginFunction<unknown>, options?: unknown): VueConstructor<Vue>', gave the following error.
    Argument of type 'Vuetify' is not assignable to parameter of type 'PluginObject<unknown> | PluginFunction<unknown>'.
      Property 'install' is missing in type 'Vuetify' but required in type 'PluginObject<unknown>'.
  Overload 2 of 2, '(plugin: PluginObject<any> | PluginFunction<any>, ...options: any[]): VueConstructor<Vue>', gave the following error.        
    Argument of type 'Vuetify' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
      Property 'install' is missing in type 'Vuetify' but required in type 'PluginObject<any>'.
 > 121 | Vue.use(vuetify);
```

In main.ts I import my vuetify plugin like this 
`import vuetify from './plugins/vuetify';`

And my vuetify.ts looks like this
```
import Vue from 'vue';
import Vuetify from 'vuetify/lib';

import en from '@/i18n/en';

Vue.use(Vuetify);

export default new Vuetify({
    lang: {
        locales: { en },
        current: 'en'
    },
    theme: {
        options: {
            customProperties: true
        },
        themes: {
            light: {
                primary: '#7A7A7A',
                secondary: '#424242',
                accent: '#C9DDFF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FFC107',
            }
        }
    }
});
```

Everything was working fine before the upgrade 🤔

**Comment by KaelWD** [comment]
Show main.ts

**Comment by sarahLardeau** [comment]
My main.ts (I removed some parts I think they are not relevant and replace them by `[...]`)
```
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import * as Sentry from '@sentry/browser';
import { Vue as VueIntegration } from '@sentry/integrations';
import vuetify from './plugins/vuetify';
import Vuex from 'vuex';
import store from './store';

import 'vue-croppa/dist/vue-croppa.min.css';
import Croppa from 'vue-croppa/dist/vue-croppa.min';
import VueRouter from 'vue-router';

// Init Sentry
Sentry.init({
[...]
});

/**
 * Called for any uncaught exceptions within any Vue instance (Vue components) throughout the application
 * Use Sentry to capture the error
 * @param {Error} err error trace
 * @param {Vue} vm component in which error occured
 * @param {string} info Vue specific error information such as lifecycle hooks, events etc.
 */
Vue.config.errorHandler = (err: Error, vm: Vue, info: string) => {
    [...]
};

/**
 * Directive to detect a click outside the element, use it with `v-click-outside` in the template
 */
Vue.directive('click-outside', {
[...]
});

Vue.config.productionTip = false;

Vue.use(vuetify);
Vue.use(Croppa);
Vue.use(Vuex);
Vue.use(VueRouter);

new Vue({
    router,
    vuetify,
    store,
    render: h => h(App)
}).$mount('#app');

```

**Comment by KaelWD** [comment]
> Vue.use(vuetify)

That's invalid.

**Comment by sarahLardeau** [comment]
You're right ! I noticed in the documentation, this part uses the Vuetify from the lib and not the instance from the plugin file ! (which what I already do in the plugin file !)
```
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify)
```
Weird it works before without throwing error 😅 
Thanks for the help !
