### ISSUE TITLE
[Feature Request] Add lazy functionality to Progress components

### ISSUE THREAD

**Issue by Bamblehorse** [vuetifyjs/vuetify#12731]
### Problem to solve
There have been various reports of the Progress components spiking CPU in different scenarios.

#### Various reports:
#2324, #785, #720, #553

#### Progress components:
https://vuetifyjs.com/en/components/progress-circular
https://vuetifyjs.com/en/components/progress-linear/

### Proposed solution
A member of my team discovered that if you wrap these components with `VLazy` you can greatly reduce the performance impact - especially if multiple instances of Progress components exist on the page.

The proposed solution is to add a `lazy` prop to the Progress components that gives them lazy functionality (i.e. not rendering if not visible on the page).

This would be either by wrapping in `VLazy` or using the `v-intersect` directive - likely requiring a minimal change to the `render` function and an added `prop` of `lazy`.

https://vuetifyjs.com/en/components/lazy
https://vuetifyjs.com/en/directives/intersect/

P.S. some kind of `lazy` directive would be cool but not sure if it's feasible/wanted and would for sure have a namespace clash with `v-lazy`

**Comment by Bamblehorse** [comment]
@KaelWD can I put together a PR for this or do we need confirmation that this is an enhancement Vuetify is interested in?

**Comment by KaelWD** [comment]
Yeah go ahead. This can be by default, doesn't need a prop.

**Comment by Bamblehorse** [comment]
Great will put together a PR 🙌

**Comment by Bamblehorse** [comment]
Hey @KaelWD 🙂 

Have been trying a couple of things out - adding the `VLazy` wrapper is easy enough but causing 7 test suites to fail because the snapshot gets reduced to `<div class="v-lazy">`:

<img src="https://user-images.githubusercontent.com/20028526/102254028-074d7a00-3f00-11eb-8c3c-391e58f62367.png" width="600 "/>

The solve I have to get `VLazy` to show it's HTML contents is this but it feels a bit hacky to do that in every test with a progress component in it:
```ts
describe('VProgressCircular.ts', () => {
  type Instance = InstanceType<typeof VProgressCircular>
  let mountFunction: (options?: object) => Wrapper<Instance>

  beforeEach(() => {
    mountFunction = (options = {}) => {
      return mount(VProgressCircular, {
        ...options,
        mounted () {
          this.$children[0].isActive = true
        },
      })
    }
  })
  ```
  
  I'm happy to go through and update the snapshots but just though I'd mention it in case you have an alternative idea that I might not have thought about. 
  
 Also was thinking of other Vuetify users and that this could affect them if it's not an opt-in change. Especially for a component like `VCard` which you wouldn't necessarily associate with needing anything special to do a snapshot test for.

**Comment by KaelWD** [comment]
Don't use VLazy, use the intersect directive to supply the transition only when the element is visible.
