### ISSUE TITLE
[Bug Report] VFileInput - readonly prop does not work

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12737]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.66
**OS:** Windows 10

### Steps to reproduce
1. Click on the file input.
2. The window with file selection pops up although the `VFileInput` is readonly.

### Expected Behavior
The window with file selection should not open, because the `VFileInput` has readonly prop.

### Actual Behavior
The window with file selection opens.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/xxEVqYY?editors=101" target="_blank">https://codepen.io/mikilll94/pen/xxEVqYY?editors=101</a>

**Comment by yuwu9145** [comment]
According to this [pull request](https://github.com/vuetifyjs/vuetify/pull/8718), `readonly` is not supposed to be used on `VFileInput`. Perhaps in `readonly` should be removed from `VFileInput` [api document](https://vuetifyjs.com/en/api/v-file-input/#props)

**Comment by MajesticPotatoe** [comment]
Was removed in that pull request, must have been overlooked when we reworked the docs.
