### ISSUE TITLE
[Bug Report] v-dialog 'leave' transition does not work when v-if is falsy.

### ISSUE THREAD

**Issue by digitalsounds** [vuetifyjs/vuetify#12742]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
I have an issue with the v-dialog 'leave' transition (default is to scale down).

* The v-dialog in question has a :value attribute always set to true (active).
* There is also a v-if on the dialog (this could also be a container div of the dialog that has the v-if, same issue).
* When the v-if condition is met the dialog transitions (scales up) into view as expected.
* When the v-if condition is not longer met, the dialog disappears without the leave transition (no scale down, just disappears straight away); 
* The 'leave' transition however works as expected when toggling just the :value attribute of the dialog.

### Expected Behavior
The dialog's 'leave' transition scales down out of view when the v-if on it is set to a falsy value.

### Actual Behavior
The dialog's 'leave' transition is not shown when the v-if on it is set to a falsy value, it instead disappears straight away.

### Reproduction Link
<a href="https://codepen.io/digitalsounds/pen/bGwpGrm" target="_blank">https://codepen.io/digitalsounds/pen/bGwpGrm</a>

**Comment by KaelWD** [comment]
`<transition>` only works when you toggle its children, compare `<transition v-if="condition><div>` and `<transition><div v-if="condition">`. With `v-if` on the dialog you're doing the first one.

**Comment by digitalsounds** [comment]
Hi @KaelWD, 

From your answer I assume you are intimating that the **v-dialog** component automatically wraps its children in the transition when you supply the transition property to it? And hence any v-if around it wont work; because as you stated, the transition needs to be the parent of the v-if?

If that is the case I have actually tried to wrap the v-dialog itself in a transition, but this doesn't actually work, I have updated my original codepen with an example of this, and if required I can raise that as a separate bug.

I have tried putting a v-if on the card within the dialog, which I would assume is now wrapped in the transition, but this also does not work, please see my fourth example in the codepen, and again; if required I can raise that as a separate bug.

I appreciate your original answer, but would you be able to supply me a solution to the problem I am having? I'm sure this would be quite a common case where you would require a v-if on a dialogue. 

In my scenario the dialog is dynamically loaded with content based on a list item you have selected. I have it as its own component, this is to keep things tidy, but also allows me to tap into the mounted lifecycle hook to focus form fields etc when the dialog opens. If I cant have a v-if on it I can't tap into the mounted lifecycle hook, because I would have to use the v-model or :value property on it to make sure it transitions correctly, which means it's mounted from the very beginning.

I would appreciate any guidance you have.

**Comment by Beats0** [comment]
Same issues

I have to use `:key` props to destroy the components

This work for me

parent:
```vue
  <v-dialog v-model="showDialog">
      <someComponent :active="showDialog"
                     @close="showDialog = false"
                     :key="'showDialog' + String(showDialog)"/>
    </v-dialog>
```

child:
```vue
<template>
  <div></div>
</template>

<script>
export default {
  name: "someComponent",
  props: {
    active: {
      type: Boolean,
      required: true
    }
  },
  data() {
    return {
    }
  },
  mounted() {
    // only the component is active
    if(!this.active) return
    this.initData()
  },
  beforeDestroy() {
    console.log('beforeDestroy')
  },
  destroyed() {
    console.log('destroyed')
  },
  methods: {
    initData() {
      console.log('initData')
    },
    handleCloseDialog() {
       this.$emit('close')
     }
  }
}
</script>
```

**Comment by ericvipo** [comment]
HI @digitalsounds , did you find any solution with v-if?
