### ISSUE TITLE
[Feature Request] Deletable selections for v-file-input

### ISSUE THREAD

**Issue by ozgurg** [vuetifyjs/vuetify#12746]
### Problem to solve
Hi. v-file-input is a good component for file upload. I created this simple demo to show you deletable selections. I think this behavior can be added to Vuetify.

Demo: https://codepen.io/ozgurg/pen/oNzzgZe

### Proposed solution
Demo: https://codepen.io/ozgurg/pen/oNzzgZe

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
