### ISSUE TITLE
[Bug Report] Prefix not aligned with text field content in dense mode

### ISSUE THREAD

**Issue by hitochan777** [vuetifyjs/vuetify#12743]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Linux x86_64

### Steps to reproduce
Enable dense mode in v-text-field and add prefix

### Expected Behavior
Prefix and the text field content should vertically align even in dense mode

### Actual Behavior
Prefix is slightly above the text field content

### Reproduction Link
<a href="https://codepen.io/hitochan777/pen/eYdzGmE" target="_blank">https://codepen.io/hitochan777/pen/eYdzGmE</a>

### Other comments
It seems that dense mode add padding `4px 0 2px` which makes it not aligned with the prefix.

**Comment by KaelWD** [comment]
Do you have a screenshot? It looks aligned to me.

**Comment by hitochan777** [comment]
@KaelWD

**with dense**
![image](https://user-images.githubusercontent.com/6002787/101462230-52efa900-397f-11eb-8f88-f26fe747164e.png)


**without dense**
![image](https://user-images.githubusercontent.com/6002787/101462170-39e6f800-397f-11eb-922e-3d7de6d5311f.png)

It becomes slightly more obvious if you remove the padding-right of prefix and use `0x` as prefix.

**with dense**
![image](https://user-images.githubusercontent.com/6002787/101462641-c396c580-397f-11eb-8552-50b3a5a5aac0.png)

**Comment by MajesticPotatoe** [comment]
This is also applicable towards the label text as well

**Comment by juddfranklin1** [comment]
Hi @MajesticPotatoe, thanks for your feedback. In treating this issue, I was looking at the vertical baseline the prefix text as it aligned with the input field content. Since by default the label text is absolutely positioned above the input, I don't see the circumstance inwhich this issue is applicable to the label text. Can you give me an idea of when this is applicable to the label text?

**Comment by MajesticPotatoe** [comment]
Visual consistency. Its possible to have a label and prefix without value, and the same results appear w/ `dense` than w/o
https://codepen.io/majesticpotatoe-the-bashful/pen/bGwqzKz

**Comment by johnleider** [comment]
The only issue here is the label positioning. It also exposes an issue with the inner appended icon that appears to have unnecessary margin applied to it, at least in the case of `v-select`.

Working codepen: https://codepen.io/johnjleider/pen/VwKWJQX
