### ISSUE TITLE
[Bug Report] V-text-field allowing 'e' when type="number" is given

### ISSUE THREAD

**Issue by rohitrg12091** [vuetifyjs/vuetify#12749]
### Environment
**Vuetify Version:** 2.3.20
**Vue Version:** 3.0.0
**Browsers:** Chrome 81.0.4044.92
**OS:** Windows 10

### Steps to reproduce
Just start typing e in the text box. Even though I have given type="number", 'e' can be typed in the text box.

### Expected Behavior
only numbers should be allowed

### Actual Behavior
other characters are being allowed.

### Reproduction Link
<a href="https://codepen.io/rohit12091/pen/VwKKpqx" target="_blank">https://codepen.io/rohit12091/pen/VwKKpqx</a>

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5224

**Comment by rohitrg12091** [comment]
Thanks @jacekkarczmarczyk for the clarification. I appreciate it. 👍
