### ISSUE TITLE
[Bug Report] hide-details auto keeps rendering empty details sections

### ISSUE THREAD

**Issue by Landen13** [vuetifyjs/vuetify#12755]
### Environment
**Vuetify Version:** 2.3.20
**Last working version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Firefox 83.0
**OS:** Windows 10

### Steps to reproduce
Check existence of details container under the field

### Expected Behavior
Details shouldn't be rendered if nothing is to render

### Actual Behavior
Empty container with fixed height is rendered

### Reproduction Link
<a href="https://codepen.io/Landen13/pen/rNMMGEK" target="_blank">https://codepen.io/Landen13/pen/rNMMGEK</a>

**Comment by MajesticPotatoe** [comment]
regression caused by [12554](https://github.com/vuetifyjs/vuetify/pull/12554/files?file-filters%5B%5D=.ts#diff-461600bc124791c50e37b10a98f91908d60bd22de5924c162a5a58408a77d311R410)
