### ISSUE TITLE
[Documentation] Cant change height of v-select as for v-text-field by scss variables ($text-field-filled-full-width-outlined-single-line-slot-min-height: 28px !default;)

### ISSUE THREAD

**Issue by mostopalove** [vuetifyjs/vuetify#12763]
### Environment
**Vuetify Version:** 2.3.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.7

### Steps to reproduce
I use vuetify cli and cant change height of v-select component by scss variables

### Expected Behavior
$select-chips-dense-selections-min-height can decrease the height of component

### Actual Behavior
$select-chips-dense-selections-min-height have no affect

### Reproduction Link
<a href="https://vuetifyjs.com/en/features/sass-variables/#variable-api" target="_blank">https://vuetifyjs.com/en/features/sass-variables/#variable-api</a>

### Other comments
Please check your documentation it is really hard to find all dependencies for component. I want to manage all the dimensions myself. THANK YOU!

**Comment by mostopalove** [comment]
I thought that variable $text-field-filled-full-width-outlined-single-line-slot-min-height will decrease the height, but its work only if v-select has full-width property
For v-text-field its work without this property

**Comment by mostopalove** [comment]
This an example of my variables.scss file:
```
$text-field-filled-full-width-outlined-single-line-slot-min-height: 28px !default;
$text-field-outlined-dense-label-position-x: 4px !default;
$text-field-outlined-prepend-append-margin-top: 2px !default;

$input-max-height: 28px !default;

$text-field-active-label-height: 8px !default;

.v-select__slot {
  height: 28px;
}

.v-label {
  font-size: 12px;
}

```

And I'm not sure if this is the right way

**Comment by Legion64** [comment]
Hello, I am also experiencing this problem right now. No matter how many changes I make in the Variables file, it has no effect.

![image](https://user-images.githubusercontent.com/35144787/195979575-46f332e3-8695-4f81-ac1f-6ed1428e844a.png)

**Comment by yhostc** [comment]
Is there an official solution to this problem?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
