### ISSUE TITLE
[Bug Report] Pressing key up/down on focused v-select inside fullscreen v-dialog closes the dialog

### ISSUE THREAD

**Issue by Nerderer** [vuetifyjs/vuetify#12769]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Firefox 83.0
**OS:** Windows 10

### Steps to reproduce
Place a v-select in a fullscreen v-dialog. Press tab to set focus in the v-select then press key up or down.

### Expected Behavior
Pressing key up or down when focus is on the v-select should select the previous or next item in the list. Alternatively it should open the menu with items.

### Actual Behavior
Pressing key up or down when focus is on the v-select will close the dialog. This only happens on fullscreen dialogs, not normal ones.

### Reproduction Link
<a href="https://codepen.io/nerderer/pen/oNzYPYL" target="_blank">https://codepen.io/nerderer/pen/oNzYPYL</a>

### Other comments
Pressing up or down currently doesn't work as expected even if it's not inside a dialog. It just select the previous or next item then loses focus. But inside fullscreen dialogs there's also this side effect.

**Comment by jacekkarczmarczyk** [comment]
Possibly related https://github.com/vuetifyjs/vuetify/issues/12723

**Comment by j1mmie** [comment]
This is reproducible without the fullscreen dialog. I've created a stripped down Codepen here: https://codepen.io/j1mmie/pen/WNGVJOw

I'm new to the Vuetify community but I would say this bumps the priority of this bug up a notch
