### ISSUE TITLE
[Feature Request] Create a theme variable for text color

### ISSUE THREAD

**Issue by keisha-rw** [vuetifyjs/vuetify#12764]
### Problem to solve
Our application uses a dark gray text color across the entire app.  We use the light theme, but there isn't a great way to override the default text color without setting custom css rules or using a globally accessible class.

### Proposed solution
Add an additional property to the theme variables called `text` (or something logically equivalent), where you can set the global font color within the theme variables list, like so:
```
export default {
  text: '#hexCode'
  primary: '#hexCode,
  secondary: '#hexCode',
  ...
};
```

**Comment by KaelWD** [comment]
The theme system in v3 has `onBackground`, `onSurface` etc. See #12542.
