### ISSUE TITLE
[Bug Report] It is not possible to prevent the default key event for left/right arrow in v-switch

### ISSUE THREAD

**Issue by yeller0205** [vuetifyjs/vuetify#12762]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
Focus the v-switch with the keyboard. As soon as it's focused, no key will do anything, except left and right arrow keys

### Expected Behavior
Left and right arrow keys do nothing

### Actual Behavior
Left and right arrow keys change the v-switch state

### Reproduction Link
<a href="https://codepen.io/yeller0205/pen/qBaqByB" target="_blank">https://codepen.io/yeller0205/pen/qBaqByB</a>

**Comment by KaelWD** [comment]
```
@keydown.native.capture.stop
```

If you want to prevent the switch from being toggled use `readonly` or `disabled`. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
