### ISSUE TITLE
[Documentation] docs anchor isn't work in other language

### ISSUE THREAD

**Issue by winter-ice** [vuetifyjs/vuetify#12779]
### Environment

**Browsers:** Edge 87.0.664.60
**OS:** Windows 10

### Steps to reproduce
open docs then click right side nav

### Expected Behavior
scroll to target

### Actual Behavior
not scroll

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables/#slots" target="_blank">https://vuetifyjs.com/en/components/data-tables/#slots</a>

**Comment by sh7dm** [comment]
only some links don't work.
https://vuetifyjs.com/ja/getting-started/installation/#webpack- does

**Comment by winter-ice** [comment]
> only some links don't work.
> https://vuetifyjs.com/ja/getting-started/installation/#webpack- does
> while https://vuetifyjs.com/ja/getting-started/installation/#-2 doesn't (incorrect id)

If the subtitle is start with English,It's work

**Comment by sh7dm** [comment]
> > only some links don't work.
> > https://vuetifyjs.com/ja/getting-started/installation/#webpack- does
> > while https://vuetifyjs.com/ja/getting-started/installation/#-2 doesn't (incorrect id)
> 
> If the subtitle is start with English,It's work

Exactly!

**Comment by YipingRuan** [comment]
Similar https://vuetifyjs.com/en/getting-started/installation/#usage-with-vuepress

End up at https://vuetifyjs.com/en/getting-started/installation/#usage-with-capacitor for me

**Comment by MajesticPotatoe** [comment]
> Similar https://vuetifyjs.com/en/getting-started/installation/#usage-with-vuepress
> 
> End up at https://vuetifyjs.com/en/getting-started/installation/#usage-with-capacitor for me

unrelated. That has to do with scrollTo not taking account the top toolbar, and the hash updating to the next available header
