### ISSUE TITLE
[Bug Report] SVG icon for v-checkbox ignores `dense` property

### ISSUE THREAD

**Issue by adamsol** [vuetifyjs/vuetify#12770]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
Uncomment the `iconfont: 'mdiSvg'` line.

### Expected Behavior
Size of the checkbox should remain 20px.

### Actual Behavior
Size of the checkbox is 24px.

### Reproduction Link
<a href="https://codepen.io/adamsol1/pen/WNGoaJv" target="_blank">https://codepen.io/adamsol1/pen/WNGoaJv</a>

**Comment by adamsol** [comment]
The same concerns radio buttons and possibly also other inputs. The following CSS seems to fix the problem:

```sass
.v-input--dense .v-icon svg
    width: $icon-size-dense
    height: $icon-size-dense
```

**Comment by jan-vodila** [comment]
The problem is in [VIcon.sass](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VIcon/VIcon.sass#L61-L63) which generates following css code:
```
.v-icon--dense__component, .v-icon--dense__svg {
  height: 20px;
}
```

Correct should be:
```
.v-icon--dense .v-icon__component, .v-icon--dense .v-icon__svg {
  height: 20px;
  width: 20px;
}
```
So the SASS version should be:
```
.v-icon
  &--dense
    .v-icon__component,
    .v-icon__svg
      height: $icon-size-dense;
      width: $icon-size-dense;
```
