### ISSUE TITLE
[Feature Request] [v3][v-app-bar] Toolbar solo style

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#12785]
### Problem to solve
I managed to have an "solo" toolbar v-app-bar style. Like this one from Vuetify demo

![image](https://user-images.githubusercontent.com/24626758/102151328-e723a980-3e72-11eb-9a15-e0b92a29fd18.png)

I like this rendering. my code is a bit hacky but I just wish I could do it again in vuetify v3 (either an officially supported feature, or always via the same hack).

### Proposed solution
I did it with this code, I would like to be able to do the same thing again in vuetify 3 or an option to get this rendering directly
```vue
<template>
  <v-app-bar app flat>
    <v-card class="flex-grow-1 d-flex pa-1 mt-3 mx-1" flat="false">
      <div class="d-flex flex-grow-1 align-center">
      </div>
    </v-card>
  </v-app-bar>
</template>
```

Thanks to everyone !

**Comment by GreyXor** [comment]
#12707

**Comment by johnleider** [comment]
This is all possible on the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
