### ISSUE TITLE
[Bug Report] Tab Slide group next and previous buttons not working

### ISSUE THREAD

**Issue by qstiegler** [vuetifyjs/vuetify#12783]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.7

### Steps to reproduce
If there are too many items in the tab bar, so you get the arrow buttons to slide through the tabs, you can't click them. Additionally sometimes (I think depending on the width), clicking works but it won't calculate the width correctly and then you can't see the last or the first element of the tabs.

If you use the `show-arrows` attribute, It works like a charm but the buttons are not hidden on mobile touch devices as they would be without the attribute.

### Expected Behavior
Arrow buttons are working and the tab slide calculation works as expected

### Actual Behavior
Arrow buttons aren't working most of the times without the `show-arrows` attribute.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tabs/#center-active" target="_blank">https://vuetifyjs.com/en/components/tabs/#center-active</a>

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
