### ISSUE TITLE
[Feature Request] V-Slide-Group support for custom slide offset

### ISSUE THREAD

**Issue by Velikolay** [vuetifyjs/vuetify#12780]
### Problem to solve
Currently the group will always slide through the entire wrapper width. This can create problems when the last slide item in the wrapper is only partially displayed - it can be a desired design behaviour to show the user that there's more content in the container. When the wrapper offset is applied the user will get to see the other side of the partial slide item, but never really the whole thing.

### Proposed solution
To give more power to developers I would suggest a prop that allows setting the offset from code, while preserving the wrapper offset as a default.

**Comment by rsvidevince** [comment]
Yes, I would love to control the width slided when clicking next or previous...!

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
