### ISSUE TITLE
[Feature Request] Support change events in VTextfield/VTextarea to facilitate easier testing with webdriver-based E2E solutions

### ISSUE THREAD

**Issue by squaredsquid** [vuetifyjs/vuetify#12787]
### Problem to solve
This feature avoids needless debugging/research of commonly used testing tool chains. It eases integration testing with webdriver based testing tools and therefore results in a better developer experience.

Currently webdriver specs  states that clearing inputs only create a blur event and indirectly a change event (see https://github.com/w3c/webdriver/issues/445). Unfortunately Vuetify only adds a handler for input events. This suffices for normal user interaction with the browser but doesn't cater to a programmatic manipulation used by testing utilities.

Therefore calling `.clear()` on DOM-Elements in a webdriver context does not work and subsequent text gets appended to the inputs text. 

Consider the following python code snippet for show-casing the behaviour:
```python
import splinter
import base64

html = u'''
<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
    <script>
      document.onreadystatechange = function () {
        if (document.readyState === 'complete') {
          new Vue({
            el: '#app',
            vuetify: new Vuetify(),
            data: {
              value: 'old value'
            },
          })
        }
      }
    </script>
  </head>
  <body>
    <div id="app">
      <v-text-field label="test" v-model="value" class="element"></v-textfield>
    </div>
  </body>
</html>
'''

prefix = 'data:text/html;base64,'
data_url = prefix + base64.b64encode(html.encode('utf8')).decode('ascii')

browser = splinter.Browser('firefox')
browser.visit(data_url)

selector = '.element input'
assert browser.is_element_present_by_css(selector, wait_time=10), 'item not present'
element = browser.find_by_css(selector).first

# does not work at all in this context
element.clear()
print('after clear:', element.value)

# appends text instead of replacing
element.fill(' - new value')
print('after fill:', element.value)
``` 

and its output:
```
after clear: old value
after fill: old value - new value
```

### Proposed solution
Register the existing onInput-Handler also for change events. 

This behaviour would also be consistent with the implementation in core vue. A v-model on a standard input element can be cleared/edited using webdriver element modification.

**Comment by KaelWD** [comment]
According to [this comment](https://github.com/w3c/webdriver/issues/445#issuecomment-273180346) your problem has already been solved: 

> This issue was originally about the input event. That has been added, which I'm very happy about!

---

> This behaviour would also be consistent with the implementation in core vue. A v-model on a standard input element can be cleared/edited using webdriver element modification.

`<input v-model="...` doesn't seem to respond to change events: https://codepen.io/kaelwd/pen/rNMdQdv?editors=1010

> ```
> element.clear()
> print('after clear:', element.value)
> ```

This isn't even going through vue, looks like `element.clear()` isn't doing anything at all.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
