### ISSUE TITLE
[Feature Request] VAutocomplete create a prop to avoid that backspace deletes selected items

### ISSUE THREAD

**Issue by mino181295** [vuetifyjs/vuetify#12788]
### Problem to solve
When pressing backspace avoid removing items even if the autocomplete is not readonly/disabled.

### Proposed solution
In the `changeSelectedIndex` method I see that `deleteCurrentItem`. I need a new prop to block this deletion and make it append only.
```
....
if (this.readonly || this.myNewProp) return
const index = this.selectedItems.length - 1
if (this.selectedIndex === -1 && index !== 0) {
        this.selectedIndex = index
        return
} 
....
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
