### ISSUE TITLE
[Documentation] URL with different language fragment is not handled correctly

### ISSUE THREAD

**Issue by YipingRuan** [vuetifyjs/vuetify#12797]
### Environment

**Browsers:** Edge 87.0.664.60
**OS:** Windows 10

### Steps to reproduce
1. Go to document and select a language that is not English
2. Click link https://vuetifyjs.com/en/components/bottom-navigation#scroll-threshold

![doc URL](https://user-images.githubusercontent.com/5492274/102513058-b5565100-40c5-11eb-84d7-45b511b276c4.gif)

### Expected Behavior
Jump to either bottom-navigation page with either language

### Actual Behavior
404

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/bottom-navigation#scroll-threshold" target="_blank">https://vuetifyjs.com/en/components/bottom-navigation#scroll-threshold</a>

**Comment by sh7dm** [comment]
Looks like issue addressed in #12790
