### ISSUE TITLE
v-switch label is cropped in v-menu

### ISSUE THREAD

**Issue by zeljic** [vuetifyjs/vuetify#1279]
### Steps to reproduce
Open reproduction link and click on button.

### Versions
0.14.8

### What is expected ?
`v-switch` component should be visible (switch button and label).

### What is actually happening ?
Label is cropped

### Reproduction Link
https://codepen.io/anon/pen/GvWqRe?editors=1010

**Comment by johnleider** [comment]
Unfortunately in this case, due to how inputs are constructed, the label is actually an absolutely positioned element that has no defined width. Which means the menu will only use the minimum width required, which is 36px.

The fix would be to add ```min-width="220px``` or some derivative of on ```v-menu```
