### ISSUE TITLE
[Feature Request] Icons Confusion

### ISSUE THREAD

**Issue by renenw** [vuetifyjs/vuetify#12793]
### Problem to solve
I have created a half dozen vue projects over the preceding year. Getting icons to work is probably the hardest part of the process of getting a new PWA up and running. There is some evidence on stackoverflow, and in your own forums, that suggests I'm not alone. And, I'm simply including the entire libraries instead of the icons I actually want.

### Proposed solution
Make an opinionated decision, and stick with it. Avoid either of the "material" options as just sorting out the difference between MDI and MI is hard. Vue is extensible enough that folk who care about a particular strategy will be able to swap out whatever strategy you pick.

**Comment by johnleider** [comment]
Icons have received quite a few updates over the years and are very easy to use in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
