### ISSUE TITLE
[Bug Report] [Documentation] V1 docs are not available anymore

### ISSUE THREAD

**Issue by Sect0R** [vuetifyjs/vuetify#12798]
### Environment
**Vuetify Version:** 1.0.4
**Vue Version:** 2.5.2
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
navigate to
https://v1.vuetifyjs.com/

### Expected Behavior
Being able to view the v1 docs

### Actual Behavior
This site can’t be reached
Check if there is a typo in v1.vuetifyjs.com.
DNS_PROBE_FINISHED_NXDOMAIN

### Reproduction Link
<a href="https://gist.github.com/Sect0R/163f657a47e4565c23cfb01b3fc484b0" target="_blank">https://gist.github.com/Sect0R/163f657a47e4565c23cfb01b3fc484b0</a>

**Comment by MajesticPotatoe** [comment]
duplicate #12042
