### ISSUE TITLE
[Bug Report] v-text-field type="number" arrows not triggering @change

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12805]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Firefox 83.0
**OS:** Windows 10

### Steps to reproduce
1. Use `v-text-field` with `type` of `number` and `@change` instead of `@input`, for example like this: `<v-text-field :value="number" type="number" @change="(value) => number = value"></v-text-field>`
1. Open the page in Firefox
1. Repeatedly try first clicking on an arrow on the right side, and then clicking on the background outside the input

![image](https://user-images.githubusercontent.com/3118390/102615009-79f36b00-4135-11eb-84f8-750a93536454.png)

### Expected Behavior
After every click outside input, the @change event should trigger; otherwise some contract in docs should describe under which situations does the event occur.

### Actual Behavior
First change triggers successfully, but when clicking on the arrow and then outside for the second time, it stops updating the value. It behaves very inconsistently, sometimes getting triggered again depending on the timing.

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/gOwmdNG" target="_blank">https://codepen.io/cTAlENtATI/pen/gOwmdNG</a>

### Other comments
* Reproduced on Firefox 83, also on version 72 on other computer. The arrows don't appear in Edge, and the issue doesn't seem to occur in Chrome.
* I'd suggest to officially document an example (as a best practice) of a correct use-case of `v-text-field` with a number type of input, for example under https://vuetifyjs.com/en/components/text-fields/#prefixes-and-suffixes where it'd be intuitive for currency & weight amounts, as it's a quite important UX factor of any serious projects; yet I haven't found it mentioned in [Material Design specs](https://material.io/components/text-fields#input-types).
  * For example, we may have to create validation rules that the number mustn't include 'e'|'E', or in case of integer that it doesn't have '.'|','; there's no easy way to avoid missing some blacklist rules.
* I'd also appreciate any documentation (to be available for new Vuetify users) about how to disable these arrows, disable changing numbers by mouse scrolling (which is a major security issue, making applications error-prone as the user scrolls the page with form, for example when dealing with currencies), or otherwise tweak the browser behavior - there are some StackOverflow CSS tips, but they don't seem to work well, and aren't standardized for forward compatibility.
* The best scenario would be probably introducing a custom number-type input option that doesn't use the browser-specific attribute, which would also address https://github.com/vuetifyjs/vuetify/issues/12246 and https://github.com/vuetifyjs/vuetify/issues/11197 (and maybe https://github.com/vuetifyjs/vuetify/issues/10745).

**Comment by sh7dm** [comment]
Not a Firefox issue. This happens in Chrome (88.0.4324.11 dev) as well.

**Comment by scscgit** [comment]
There's also one more unrelated display issue of the arrows covering a long label when a suffix is used:
![image](https://user-images.githubusercontent.com/3118390/103150790-aaf81f00-4777-11eb-87e5-e06e74bfdfed.png)

**Comment by vramdal** [comment]
#12955 was marked as duplicate of this. However, this bug "doesn't seem to occur in Chrome", whereas #12955 does.

**Comment by johnleider** [comment]
This behavior was modified as part of 6aaf52b36 to fix #5070. The change event will only fire if the internalValue does not equal the initialValue and the user blurs the input or presses enter. These are the intended use-cases of @change.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by scscgit** [comment]
Note that, in the repro link, after changing value for a few times and clicking on a background to blur, sometimes it got stuck without updating the value, but when I clicked inside the input and pressed enter, then it updated correctly.

I noticed you've covered this under a test which always performs the keydown enter:
> input.trigger('input')
> input.trigger('keydown.enter')
> expect(change).toHaveBeenCalledTimes(1)

Maybe it'd be better to also include some case without the enter.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
