### ISSUE TITLE
VToolbarSideIcon is not working well in mobile to open VNavigationDrawer

### ISSUE THREAD

**Issue by bichikim** [vuetifyjs/vuetify#1280]
### Versions
"vuetify": "^0.14.8", "vue": "^2.4.2" chrome 59.0.3071.125, Firefox 54.0.1, Amdroid 7.0.0, 

### What is expected ?
oping VNavigationDrawer when I touch VToolbarSideIcon

### What is actually happening ?
It cannot open time to time

**Comment by nekosaur** [comment]
Please provide a link to a reproduction of the problem using the codepen template or equivalent.

**Comment by bichikim** [comment]
Hello Nekosaur
https://codepen.io/bichikim/pen/zdwvjp
I made this.
However even in https://vuetifyjs.com has same problem.
In mobile opening navigation is not working well once in 10times.
For understanding I made a video. Please watch this : https://www.youtube.com/watch?v=5uiYyVtyoPM&feature=youtu.be
Additionally a navigation in Vue Material is runing well 

Thanks

**Comment by nekosaur** [comment]
@bichikim I've tried replicating this on vuetifyjs docs but am unable to (both desktop mobile and an iphone). It always opens the drawer when clicking the icon.

Looking at your video it's hard to know exactly when and where you click since there's no visible cursor, but a few times a small white ball shows up at the top of the window, which seems to indicate it has interpreted your touch as a swipe instead of a click. Could that be the problem?

**Comment by bichikim** [comment]
Yes it's hard to know Sorry.
I think the touchStart and swipe problem is one of it
The button should start event when it touch start to solve it.
And I guess it have another error. 
For example, Vue-maratial is working well.  its opening navigation is 
`<md-sidenav class="md-left md-fixed" ref="sidebar">`
`<md-list-item @click="$refs.sidebar.toggle()"... `
However vuetyify is using data(state). perhaps it can solve the problem

**Comment by nekosaur** [comment]
I do not agree that the navigation drawer should activate on touchstart. Touchstart is a mobile only event, while click works for both desktop and mobile.

I'm not sure what you mean by the button style changing.

**Comment by bichikim** [comment]
hello,
I mean  to open a navigation should use a function in the navigation element not using watching data changing.
as far as I know vue using ticks to refresh date state. But..
I am not sure that is a cause of the opening problem . I am trying to fine the cause
after fining it. I will tell you. :)
Thank you for helping.

**Comment by bichikim** [comment]
hi ! I found error! please check this https://youtu.be/AAF6x_oWjR0 and I am trying to fix it.
and Vuetify must be fixed. have good day!

**Comment by bichikim** [comment]
hello I am happy to say "It's solved" 
here's the code
`<v-toolbar-side-icon
                    @touchend.prevent.native.click="isNavigationOpen = !isNavigationOpen"
                    class="hidden-md-and-up"
            ></v-toolbar-side-icon>`
