### ISSUE TITLE
[Bug Report] Snackbar floats above the app footer even when the footer is absolute and below the viewpoint

### ISSUE THREAD

**Issue by gmichaeljaison** [vuetifyjs/vuetify#12803]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Safari 14.0.2
**OS:** Mac OS 11.0

### Steps to reproduce
Run the codepen

### Expected Behavior
Snackbar should be at the bottom when the footer is below the viewpoint

### Actual Behavior
Snackbar is floating in the middle of the page

### Reproduction Link
<a href="https://codepen.io/michaeljaison/pen/rNMwabo" target="_blank">https://codepen.io/michaeljaison/pen/rNMwabo</a>

**Comment by gmichaeljaison** [comment]
<img width="574" alt="Screen Shot 2020-12-17 at 3 51 45 PM" src="https://user-images.githubusercontent.com/4497234/102557350-c67c6f00-407f-11eb-9761-6e88356cba05.png">

Screenshot of the snackbar floating in the middle of the page

**Comment by paper-me** [comment]
I have the same problem. Is there any work around?

**Comment by paper-me** [comment]
I just add 'pb-0' to Snackbar component...
Maybe it's following the material design specification. But the material.io site can make its snackbar above the app footer!
And they only say "Avoid placing snackbars in front of **navigation components.**", not the app footer!
![image](https://user-images.githubusercontent.com/36994914/105937547-c2853900-6090-11eb-8ba6-b9f502ccb355.png)

![image](https://user-images.githubusercontent.com/36994914/105937354-5d314800-6090-11eb-91a9-44d908eb623d.png)

**Comment by paper-me** [comment]
And the vuetify document has betray this guideline.
![image](https://user-images.githubusercontent.com/36994914/105937963-928a6580-6091-11eb-8185-ca93d4ab32ea.png)
