### ISSUE TITLE
[Bug Report] v-list item visibility glitch when used with `column-count`

### ISSUE THREAD

**Issue by Kapcash** [vuetifyjs/vuetify#12804]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 11.0.0

### Steps to reproduce
- Use a v-list with a v-item-group including some items.
- Add a css `column-count` property to the v-item-group tag
- Hover on the elements, the first element of the columns should disappear for a short time (corresponding to the v-list-item:before transition duration I guess). The first column element doesn't glitch at all.

### Expected Behavior
The first elements of the new columns should not disappear on hovering other elements.

### Actual Behavior
The first element of each new columns disappear for a short time when hovering other list items.

### Reproduction Link
<a href="https://codepen.io/Kapcash/pen/dypROjN" target="_blank">https://codepen.io/Kapcash/pen/dypROjN</a>

### Other comments
This glitch is a bit tricky, it may not appear sometime depending on how the elements are placed (adding more elements to the list may remove the bug for example)

**Comment by KaelWD** [comment]
This happens when you have an odd number of columns so one of the items is split in half. Add `break-inside: avoid` to `.v-list-item` to prevent them from being split between columns.
