### ISSUE TITLE
[Bug Report] V-file-input deletes the file already filled in the field if the dialog box is opened, regardless of the action.

### ISSUE THREAD

**Issue by Flatoupix** [vuetifyjs/vuetify#12816]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Opera 71.0.3770.456
**OS:** Windows 10

### Steps to reproduce
Pick a file, then click again to change the file, then cancel, the field will be deleted.

### Expected Behavior
No changes on the field

### Actual Behavior
The field is reset.

### Reproduction Link
<a href="https://codepen.io/FlatoupiX/pen/eYdEroM" target="_blank">https://codepen.io/FlatoupiX/pen/eYdEroM</a>

**Comment by sh7dm** [comment]
Happens in Chrome, not in Firefox. Opera is based on Chromium, so it's a Chromium-specific bug.

**Comment by Dinver** [comment]
Bug still present.

**Comment by H20-17** [comment]
Happens in Edge too (which is also Chromium  based, if I understand correctly)

**Comment by johnleider** [comment]
This is the default behavior of a generic `<input type="file" />`.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
