### ISSUE TITLE
[Bug Report] Color picker alpha field ignores decimal separator locale

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12810]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.0.1

### Steps to reproduce
1. Run this project
[vuetify-color-picker.zip](https://github.com/vuetifyjs/vuetify/files/5720216/vuetify-color-picker.zip)

2. As you can see I have set the language of Vuetify app to English
```js
export default new Vuetify({
    lang: {
        locales: { en },
        current: 'en',
    }
});
```
However, the alpha field in the color picker uses comma instead of dot.

![Screenshot 2020-12-19 at 23 19 59](https://user-images.githubusercontent.com/17653648/102700764-bb2c6d80-4250-11eb-9eee-399138d364c6.png)

### Expected Behavior
Alpha field in the color picker should use dot as a decimal separator.

### Actual Behavior
Alpha field in the color picker uses comma as a decimal separator.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/VwKWJzy" target="_blank">https://codepen.io/mikilll94/pen/VwKWJzy</a>

**Comment by KaelWD** [comment]
This is based on `<html lang="">` in some browsers, and system locale in others.

**Comment by Mikilll94** [comment]
@KaelWD 
Unfortunately your solution is not working for me. If you will my check my repro project, then you can see that in `index.html` file I have this:

![Screenshot 2020-12-20 at 11 17 33](https://user-images.githubusercontent.com/17653648/102710780-f5c7f180-42b4-11eb-8a5e-d78192af2f20.png)

Thus, as you can see I have the correct language set in html tag.

Maybe you should reopen this issue?

**Comment by KaelWD** [comment]
It's just an `<input type="number">`, we don't control the localisation.

**Comment by Mikilll94** [comment]
@KaelWD 
Hm... That's strange. In Vuetify you have the following code:
```
<input type="number" min="0" max="1" step="0.01">
```

If you copy this code and put it here:

![Screenshot 2020-12-20 at 11 35 42](https://user-images.githubusercontent.com/17653648/102711097-843d7280-42b7-11eb-922e-b8ded7126d33.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Then I can enter both comma and dot in the input. Thus, I think that Vuetify is handling some events for this field.

It 's worth to note that Mozilla docs have also `lang="en"` set in html tag.
