### ISSUE TITLE
[Bug Report] Flickering in circular progress bar

### ISSUE THREAD

**Issue by DavidMulder0** [vuetifyjs/vuetify#12813]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
Play the reproduction link

### Expected Behavior
There should be no flickering

### Actual Behavior
See frame number 25, it's completely white.
![flicker](https://user-images.githubusercontent.com/20395438/102718482-984d9800-42e8-11eb-86f8-9da20d7eafc4.gif)

Note: The gif is non-looping, so the weird jump on the left is NOT an issue, it's about the white flicker on the right.

### Reproduction Link
<a href="https://codepen.io/DavidMulder/pen/ExgvyaV?editors=111" target="_blank">https://codepen.io/DavidMulder/pen/ExgvyaV?editors=111</a>

**Comment by sh7dm** [comment]
This is specific to Chrome.
Firefox 83 -- no flicker
Chrome 88 -- flicker

**Comment by polymer-coder** [comment]
@DavidMulder0  can confirm it's probably a browser issue, using Chrome version 87.0.4280.88 (Official Build) (64-bit) and I see no flicker on the code pen

**Comment by DavidMulder0** [comment]
@polymer-coder For whatever it's worth, seeing the flicker in both Chrome 87.0.4280.88 (stable) and 89.0.4368.0 (canary).

**Comment by sh7dm** [comment]
@DavidMulder0 what is your GPU? This might be relevant. Do you have any experimental settings enabled?

**Comment by DavidMulder0** [comment]
@sh7dm No experimental settings in Edge or Canary where I see the flicker.

Seeing the issue on two laptops, one has a Nvidia Quadro P1000, the other a Intel R UHD Graphics 620.

For what it's worth, not seeing the flicker on my android chrome.
