### ISSUE TITLE
[Bug Report][2.3.21] v-select in v-edit-dialog not working properly

### ISSUE THREAD

**Issue by decozo150** [vuetifyjs/vuetify#12812]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.7

### Steps to reproduce
v-select menu appears inside the v-edit-dialog.
steps:
1- click on the 3rd cell on any row to modify it, and a small edit dialog appears over the cell with a dropdown menu inside it.
2- click on the dropdown menu icon.

### Expected Behavior
the dropdown menu should appear over the edit dialog.

### Actual Behavior
the dropdown menu appears inside the edit dialog, therefore the dropdown menu's height is bound by the edit-dialog's height.

### Reproduction Link
<a href="https://codepen.io/decozo/pen/ExgvKpY" target="_blank">https://codepen.io/decozo/pen/ExgvKpY</a>

**Comment by johnleider** [comment]
This is because you forced it to attach to the dialog using the **attach** prop. https://codepen.io/johnjleider/pen/JjNWxdZ

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
