### ISSUE TITLE
[Bug Report] Menu with datepicker does not open on Safari 9

### ISSUE THREAD

**Issue by oliverclark15** [vuetifyjs/vuetify#12811]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Works as expected except on Safari 9

### Expected Behavior
Datepicker pops up upon click

### Actual Behavior
Cannot pick the datepicker

### Reproduction Link
<a href="https://codepen.io/oliverclark15/pen/eYdEZex" target="_blank">https://codepen.io/oliverclark15/pen/eYdEZex</a>

**Comment by KaelWD** [comment]
Safari 9 is technically still supported but I don't think this is worth fixing. If it's important to you you're welcome to submit a PR.
