### ISSUE TITLE
[Bug Report] Treeview emits update:active event when active prop changes

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12821]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.0.1

### Steps to reproduce
1. Open Chrome Dev Tools 
2. Click on "Update" button.
3. In the console it is logged - "UPDATE ACTIVE".

### Expected Behavior
`@update:active` should only be called after user interaction (click on treeview item)

### Actual Behavior
`@update:active` is called also when `active` prop is changing.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/dypVMKo?editors=1010" target="_blank">https://codepen.io/mikilll94/pen/dypVMKo?editors=1010</a>

### Other comments
I need a way to handle click event on treeview item. Right now this is not possible, because event `@update:active` is fired also when `active` prop is changing.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
