### ISSUE TITLE
v-edit-dialog is disabled when table cell is empty

### ISSUE THREAD

**Issue by vuras** [vuetifyjs/vuetify#1282]
### Versions
Vue 2.4.2, VuetifyJS v.0.14.8

### What is expected ?
Edit dialog should be enabled for call when table cell is empty

### What is actually happening ?
It is not possible to open an edit dialog when table cell is empty

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by vuras** [comment]
I can't reopen issue because of Github rights policy.

This is the sample code:

[https://codepen.io/vuras/pen/ZJKdgJ](url)

**Comment by johnleider** [comment]
Well there is nothing to click. You can always provide a default if none is available, but this is something the dev should address.

**Comment by vuras** [comment]
From the user and even developer perspective it does not sound like a rational argument that field cannot be clicked and updated because it is empty and there is nothing to click. 
IMHO, setting default values or trying to bypass it in other way to achieve such an obvious functionality is a bad design and that is how legacy systems are born. 

Looks like I have to pass it on your framework for now because a lot of simple things are over complicated. I hope that in a future you will make your framework more mature. Good luck :)

**Comment by johnleider** [comment]
Good luck

**Comment by majeocpi** [comment]
You can overload the css class .menu__activator to set a minimum width for the field like this : 
`.menu__activator {
        min-width: 50px;
  }`
