### ISSUE TITLE
[Bug Report] Can't select text at v-list-item on safari

### ISSUE THREAD

**Issue by NikitaKovtun** [vuetifyjs/vuetify#12826]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Safari 14.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just try select part of text with mouse 

### Expected Behavior
Selected part of text

### Actual Behavior
not selected text

### Reproduction Link
<a href="https://codepen.io/nikitakovtun/pen/MWjEORY" target="_blank">https://codepen.io/nikitakovtun/pen/MWjEORY</a>

**Comment by Altantur** [comment]
Just digging around, cause of this bug is tabindex="-1".

```
<div tabindex="-1" role="listitem" class="v-list-item theme--light">
...
</div>
```
If we remove tabindex attribute like below, selecting text on Safari works.
```
<div role="listitem" class="v-list-item theme--light">
...
</div>
```
I know it is not a solution, but it is better to exclude for Safari since tab-access is disabled by default.

**Comment by johnleider** [comment]
This is resolved by https://github.com/vuetifyjs/vuetify/pull/13697.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
