### ISSUE TITLE
[Feature Request] persistent-placeholder for VTextField

### ISSUE THREAD

**Issue by altapo** [vuetifyjs/vuetify#12839]
### Problem to solve
After version 2.4.0, the logic of placeholder behavior changed.

### Proposed solution
To save previously implemented features, need to add a parameter `persistent-placeholder`

**Comment by zetaraku** [comment]
I agree. Breaking changes better have some switch to save the existing features.
I have an app that needs the placeholders to indicate the default values and to keep the fields being consistent.
Without this behavior, it would be inconvenient to use.
Now I can't upgrade to version 2.4.0, help :(

Before version 2.4.0:
![before](https://user-images.githubusercontent.com/9212875/104083186-a8b5ba80-5277-11eb-92af-bff4d7c45b15.png)
After version 2.4.0:
![after](https://user-images.githubusercontent.com/9212875/104083231-f7fbeb00-5277-11eb-9647-49567c034e9e.png)

**Comment by johnleider** [comment]
Introduced in #12635 for #12499 and related to #5753.

**Comment by mseele** [comment]
We have the same problem. Breaks a application with a few hundred fields and makes a vuetify upgrade impossible. We are using the placeholder for a kind of "fallback value". If the user does not enter a value, the "fallback value" (placeholder) will be saved. Therefore it is essential that the placeholder is always visible for the user.

I understand that the material design spec does not "allow" these functionality but please give us an attribute to use the old behaviour instead.
I know it would be possible to work around and re-implement our needed behaviour, but the reason why we coose to use an ui framework and don't implement everything from scratch is that we don't wanted to reinvent the wheel every time and use existing features of a solid framework.

Don't get me wrong, i appreciate the work the whole vuetify team is doing. If there is something i can help, please let me know.

**Comment by boutils** [comment]
We also need this feature. A bolean `persistent-label` will be exactly what we need (even if there is no placeholder, we want the equivalent of the old trick `placeholder = " "`. For us, it will be perfect if we can define globally this parameter to `true`.

**Comment by Joebayld** [comment]
Are there any updates from the team regarding this? I'm considering downgrading to pre 2.4 until we see something resolved - or some sort of workaround.

**Comment by mseele** [comment]
@Joebayld You can work around this problem by reverting pull request [12635](https://github.com/vuetifyjs/vuetify/pull/12635/files) via [patch-package](https://github.com/ds300/patch-package). This is what we use as workaround until this feature is implemented.

**Comment by mnannola** [comment]
We have the same issue with 2.4 in our apps.  Most of our inputs have a design requirement that the label always shows (not just on focus) and this issue is preventing us from moving forward with a 2.4+ upgrade.

**Comment by Shinigami92** [comment]
@mseele Could you try my https://github.com/vuetifyjs/vuetify/pull/13001 and report if anything is working with it?
This way we have directly a real-world test

**Comment by Shinigami92** [comment]
Is this possibly also related to this?

https://vuetifyjs.com/en/components/file-inputs/#validation

![image](https://user-images.githubusercontent.com/7195563/105871743-e8133380-5ff9-11eb-9ddb-5bc10035bddd.png)

**Comment by MajesticPotatoe** [comment]
@Shinigami92 different issue <https://github.com/vuetifyjs/vuetify/issues/12864>

**Comment by UglyHobbitFeet** [comment]
FWIW I temporarily get by this by adding a class to the elements I want to affect (aka, avoid applying to v-checkboxes, other pages that may have different layouts, etc)

<v-text-field class="examplePatch" ...>
<style>
.examplePatch .v-label {
   transform: translateY(-18px) scale(.75);
}
</style>

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
