### ISSUE TITLE
[Documentation] v3.0 roadmap outdated

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12837]
### Environment

**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.1.0

### Steps to reproduce
The "Alpha" and "Overview section" are completely outdated.

![Screenshot 2020-12-24 at 15 34 39](https://user-images.githubusercontent.com/17653648/103094373-8d9f4580-45fd-11eb-8525-c711e1b5e9e1.png)

As we know these parts:
`Alpha: Q4 2020`
`Vuetify 3 is being developed with the pre-releases (alpha/beta) of Vue 3`
`is expected to release shortly after the next Vue version is officially released`
`release quarter is variable and will change according to the progress of Vue 3`

are no longer valid.

### Expected Behavior
Docs should not contain outdated information.

### Actual Behavior
Docs contain outdated information.

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/roadmap/#v32e0-28titan29" target="_blank">https://vuetifyjs.com/en/introduction/roadmap/#v32e0-28titan29</a>

**Comment by Mikilll94** [comment]
@MajesticPotatoe 
You can also update the information about alpha release. The alpha version probably won't be released in December.

**Comment by MajesticPotatoe** [comment]
> @MajesticPotatoe
> You can also update the information about alpha release. The alpha version probably won't be released in December.

That would be incorrect. We are still planning to have alpha out by the end of December containing core services, directives, grid, and layout components.
If we do not end up meeting this target, then at that time I will update it with a new target once that is known.
