### ISSUE TITLE
[Bug Report] v-sheet inside a v-carousel-item has a wrong offset

### ISSUE THREAD

**Issue by quank123wip** [vuetifyjs/vuetify#12840]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 2.6.12
**Browsers:** Edge 87.0.664.66, Google Chrome
**OS:** Windows 10

### Steps to reproduce
define a v-sheet inside a v-carousel-item

### Expected Behavior
no offsets

### Actual Behavior
offset 12px

### Reproduction Link
<a href="https://codepen.io/quank123wip/pen/oNzoYJv" target="_blank">https://codepen.io/quank123wip/pen/oNzoYJv</a>

### Other comments
workaround: add a margin-top: 12px; style.

**Comment by Fabi1Sc** [comment]
Same for me.

**Environment**
Vuetify Version: 2.4.0
Last working version: 2.3.23
Vue Version: 2.6.12
Browsers: Google Chrome Version 87.0.4280.141
OS: Ubuntu 20.04

**Comment by KaelWD** [comment]
`<v-row>` shouldn't be used without `<v-col>`
