### ISSUE TITLE
[Bug Report] New nested grid gutters in v2.4 is breaking change

### ISSUE THREAD

**Issue by stannok** [vuetifyjs/vuetify#12848]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 3.0.4
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge
**OS:** Mac OS 10.15.6, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
This feature request #11408 was added to solve nested grid gutters. See supplied Codepen and previous issue

### Expected Behavior
Should still work with old behaviour. If not this should be flagged as a breaking change.

### Actual Behavior
Old grid styling is overridden by the new changes.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/qBOMdpY" target="_blank">https://codepen.io/thomaskientz/pen/qBOMdpY</a>

### Other comments
Please add this as a breaking change and supply either a migration path or breaking change notice in the release notes. For now we and everyone relying on the old behaviour is able to update to the latest release.

**Comment by KaelWD** [comment]
That codepen is using v2.2, can you explain what the problem is?

**Comment by stannok** [comment]
I've added the Codepen from the original feature #11408 request. Therefore this reflects the change request from the old state to the new.

This is the pull request from the release notes https://github.com/vuetifyjs/vuetify/commit/d0f25fc59b29c385a6910dc48a111df811da3bdf 

These were changes on the Grid layout. Specifically the gutters when nesting. This causes problems for anyone who used the nesting of row/cols recursively and used the no-gutters prop and padding/margin to correct unwanted behaviour.

I hope this make sense. If not I will try to produce better Codepen to demonstrate the issue.

**Comment by KaelWD** [comment]
> and used the no-gutters prop and padding/margin to correct unwanted behaviour

Bug fixes generally tend to break the workarounds for the bugs, remove the workaround and it won't be broken any more. If we avoided changes like this nothing would ever get fixed.

**Comment by stannok** [comment]
No problem. I appreciate bugs being fixed, which might cause an issue on the workaround. To be clear the issue was marked a feature not a bug. So we were not expecting any breaking changes when upgrading. For now we will stay on v2.3.x

Do you suggest a feature is allowed to make a breaking change on a minor revision? If so, would it not be right to add a notice in the release note? As I understand from semantic versioning this is not the expected behaviour for a feature on a minor change. But you might be using a more liberal approach to semantic versioning.

Thanks for your quick reply.

**Comment by KaelWD** [comment]
> the issue was marked a feature not a bug

It was opened as a bug report, doesn't really make sense as a feature request. 

> Do you suggest a feature is allowed to make a breaking change on a minor revision?

We try to avoid it for the most part but if every change with the **potential** to *maybe* break something was marked as breaking we'd be on v99.0.0 by now. Semver works great for APIs but not so much when CSS changes can be regarded as breaking. 

> add a notice in the release note?

Can do. The beta release had a section on potentially breaking changes, not sure why it was removed.

**Comment by stannok** [comment]
Thanks again for clarifying!

This resolves the issue for us. We will update our code base. I have closed the issue accordingly.

**Comment by adarshmadrecha** [comment]
In case anyone comes here looking for what exactly is the problem.

Before (v2.3.22)
![2 3 22](https://user-images.githubusercontent.com/11911938/103373995-6a443100-4afc-11eb-9046-2cbd7644a0af.png)

After (v2.4.0)
![vuetify 2 4 0](https://user-images.githubusercontent.com/11911938/103373991-69130400-4afc-11eb-8c4f-6d8846c75cd7.png)

**Comment by huybuidac** [comment]
They removed vertical padding of row @@

**Comment by donalmurtagh** [comment]
> They removed vertical padding of row @@

Actually they added top and bottom margin of -12px for nested rows

**Comment by webcoderkz** [comment]
@donalmurtagh how to deal with this? Because of the top and bottom margins on `.row` now my rows overlapping each other.

**Comment by s1ntetik** [comment]
Solution without `!important.`
Add to your `App.vue `

```
<style>
.row {
  margin-top: 0;
  margin-bottom: 0;
}

.row + .row {
  margin-top: 0;
}
</style>
```
