### ISSUE TITLE
[Feature Request] Disconnect from the Intersection Observer if monitoring not required any longer

### ISSUE THREAD

**Issue by irfaans** [vuetifyjs/vuetify#12846]
### Problem to solve
The Intersection Observer could be using and taking up resources and affect performance if monitoring of a div, v-card, etc. is not required any longer.

### Proposed solution
v-intersect="required ? 'onIntersect' : false"

**Comment by KaelWD** [comment]
It does have a `.once` modifier if that solves your problem.

**Comment by irfaans** [comment]
Many thanks your response. I was hoping to still observe visibility even after first time and some stage disconnect on a certain condition.
