### ISSUE TITLE
[Feature Request] Treeview - possibility to designate treeview nodes as links

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12842]
### Problem to solve
Right now Treeview lacks the ability to designate its nodes as links. For List item groups this is possible by using `href` or `to` prop on `v-list-item`.

### Proposed solution
Add the possibility to designate Treeview nodes as links. I don't have a concrete solution but maybe you should add the following props to Treeview component:
- link - Designates treeview nodes as links.
- to - Denotes the target route of the link. You can find more information about the to prop on the vue-router documentation.
- item-link - Property on supplied items that contains the link when using `link` prop or route when using `to` prop

Treeview items should be active when the link or route matched.

**Comment by CavalcanteLeo** [comment]
I need this so bad

**Comment by dannycoulombe** [comment]
Meanwhile, here's the complicated alternative.

In your template:

```html
<v-treeview
    :items="items"
    :active.sync="actives"
    activatable
    @update:active="handleItemClick"
>
```

The method:
```js
handleItemClick(id) {
    this.$router.push({
        name: this.$route.name,
        params: { id } // Only if you need params
    });
},
```

To active your link by default:
```js
data: () => ({
    actives: [YOUR_ACTIVE_KEY_IN_AN_ARRAY],
}),
```
