### ISSUE TITLE
A component inside table headers slot 

### ISSUE THREAD

**Issue by yazfield** [vuetifyjs/vuetify#1284]
### Steps to reproduce
Hi,
I wanted to put a component inside datatables headers slot like this:
```html
<template slot="headers" scope="props">
  <my-component />
</template>
```
`my-component` contains all `th` tags wrapped in a `tr` tag which is the root. 
```html
<tr>
  <th>blah</th>
</tr>
```
but by doing so vuetify wraps my component in another `tr` which messes up the markup, the result is a `tr` containing a `tr`
```html
<tr>
  <tr>
    <th>blah</th>
  </tr>
</tr>
``` 
this is due to this line of code: [head.js:13](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/tables/mixins/head.js#L13
)
```javascript
children = row.length && row[0].tag === 'tr' ? row : this.genTR(row)
```
when using a component, the tag property is assigned the component's name thus, a new tr is generated.

is there a workaround? 

Thank you.

**Comment by nekosaur** [comment]
I thought this was fixed by someone's PR a while back.. 

We should be able to flip the check to 

```children = row.length && row[0].tag === 'td' ? this.genTR(row) : row```

Unless I'm not thinking of some edge case.

**Comment by yazfield** [comment]
@nekosaur yeah that'd do, one edge case is if the custom component isn't wrapped in a `tr` I'm not sure if there's a way to insure it is?

**Comment by nekosaur** [comment]
That'll have to end up being user error I think. You can only have one root element in vue templates anyway, so a user would have to do something like

```html
<template>
  <div>
    <td></td>
    <td></td>
  </div>
</template>
```

which isn't valid html in a table anyway.

**Comment by johnleider** [comment]
This is something that I think the dev can compensate for.

**Comment by yazfield** [comment]
@johnleider it's still a bug I think, pretty simple fix if you could add it in your next release.
thank's for the package by the way, it's great.
