### ISSUE TITLE
[Bug Report] List item groups -> selection also occurs for v-list-group

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12843]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.1.0

### Steps to reproduce
1. Click on "Users".
2. The `value` changes to 1.

### Expected Behavior
`v-list-item-group` should only allow selecting `v-list-item`s

### Actual Behavior
`v-list-item-group` allows selecting `v-list-item`s and `v-list-group`s

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/VwKrPdp?editors=1010" target="_blank">https://codepen.io/mikilll94/pen/VwKrPdp?editors=1010</a>

### Other comments
https://vuetifyjs.com/en/components/list-item-groups/

Docs says that `The v-list-item-group provides the ability to create a group of selectable v-list-items`.

However, as you can see in my example, the `v-list-item-group` model is also updated when I am clicking on `v-list-group`s. IMO, this should not work like this. The `v-list-group` should just serve the functionality of opening the group. Nothing more. It should not update the `v-list-item-group` model.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
