### ISSUE TITLE
[Bug Report] Problem with Safari Version 14.0 (15610.1.28.1.9, 15610)

### ISSUE THREAD

**Issue by mirecl** [vuetifyjs/vuetify#12854]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 3.0.4
**Browsers:** Safari 14.0
**OS:** Mac OS 10.15.6

### Steps to reproduce
Visit for example: https://vuetifyjs.com/en/examples/wireframes/base/
Result - blank screen
error: Viewport argument key "minimal-ui" not recognized and ignored.

### Expected Behavior
I'll see some examples 

### Actual Behavior
blank screen.

### Reproduction Link
https://vuetifyjs.com/en/getting-started/wireframes/

**Comment by KaelWD** [comment]
Works for me on browserstack.

**Comment by mirecl** [comment]
I visit https://vuetifyjs.com/en/examples/wireframes/base/ , but I do not see example vuetify - only blank screen.
In inspector web page - error Viewport argument key "minimal-ui" not recognized and ignored.

**Comment by KaelWD** [comment]
Screenshot?

The minimal-ui warning is unrelated and doesn't cause problems.

**Comment by mirecl** [comment]
![Screenshot 2020-12-29 at 16 06 27](https://user-images.githubusercontent.com/28476324/103285683-e3a22d80-49ef-11eb-9c0e-9cf3aeb33d5d.png)

**Comment by mirecl** [comment]
![Uploading Screenshot 2020-12-29 at 16.10.46.png…]()

**Comment by mirecl** [comment]
![Screenshot 2020-12-29 at 16 10 46](https://user-images.githubusercontent.com/28476324/103285964-7d69da80-49f0-11eb-9801-34141ebf0179.png)

**Comment by KaelWD** [comment]
SSr is broken on these pages. Easy fix would be to disable SSR for them as they don't need good seo.
