### ISSUE TITLE
[Feature Request] Different classes for first in range and last in range in VDatePicker ranged

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#12851]
### Problem to solve
Custom layout for range pickers

### Proposed solution
add range-start class to the first day in range and add range-end class to the last day in range

**Comment by jacekkarczmarczyk** [comment]
This will be eventually resolved in https://github.com/vuetifyjs/vuetify/issues/9608, but i'll leave it open as just adding these 2 classes might be implemented in 2.5

**Comment by joelpro2** [comment]
@jacekkarczmarczyk any prevision for 2.5 release?
Cus this feature would be really handy in my current project

**Comment by jacekkarczmarczyk** [comment]
2.4 was just released, so not so soon i guess
