### ISSUE TITLE
[Bug Report] [Bug Report] Tooltip doesn't add scroll bar inside content

### ISSUE THREAD

**Issue by iamr0man** [vuetifyjs/vuetify#12850]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add CSS property: overflow

### Expected Behavior
Scroll bar inside tooltip content

### Actual Behavior
Scroll bar doesn't appear

### Reproduction Link
<a href="https://codesandbox.io/s/zen-moser-w9gwo?file=/src/components/Comment.vue" target="_blank">https://codesandbox.io/s/zen-moser-w9gwo?file=/src/components/Comment.vue</a>

### Other comments
Corrected code in codesandbox. Bug can watch in the link above.

**Comment by KaelWD** [comment]
Again, we're not here to debug your custom CSS. The scrollbar is there, you just can't use it because tooltips have `pointer-events: none`
