### ISSUE TITLE
[Bug Report] Adding Elevation to outlined v-btn changes coloring

### ISSUE THREAD

**Issue by ecasetracker** [vuetifyjs/vuetify#12852]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 3.0.4
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
- create a `v-btn` with the `outlined` property
- note its appearance
- add an `elevation="1"` property
- note the appearance change

### Expected Behavior
should appear the same with only elevation added

### Actual Behavior
background and text colors change

### Reproduction Link
<a href="https://codepen.io/fontzter/pen/OJRzPrG?editors=101" target="_blank">https://codepen.io/fontzter/pen/OJRzPrG?editors=101</a>

**Comment by GaborTorma** [comment]
Same problem when depressed=true

[Reproduction Link](https://codepen.io/gabortorma/pen/VwKyWJP)

**Comment by midnightblurz** [comment]
Can confirm. Having the same issue after updating from **2.3** to **2.4**

**Comment by KaelWD** [comment]
Technically a duplicate of #12845
