### ISSUE TITLE
[Bug Report] In VDatePicker, scroll isn't locked for min and max dates

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#12856]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.1.0

### Steps to reproduce
try to go back with header arrow, and then try to go back using mouse scroll

### Expected Behavior
no scroll back behond current month

### Actual Behavior
button don't go back but scroll goes.

### Reproduction Link
<a href="https://codepen.io/joel_rodrigues/pen/abmEMPo" target="_blank">https://codepen.io/joel_rodrigues/pen/abmEMPo</a>

**Comment by dchinu97** [comment]
@jacekkarczmarczyk  Seems like an interesting issue to work on, can you please assign it to me?

**Comment by dchinu97** [comment]
I think just changing the scrollable from direct prop value to this.scrollable && !this.disabled (Same check used for disabling prev and next Icon) should solve the issue

**Comment by dchinu97** [comment]
@jacekkarczmarczyk Can you please review this PR 🙂?
