### ISSUE TITLE
[Enhancement] Bind v-app to something other than id of "app"

### ISSUE THREAD

**Issue by ryanmortier** [vuetifyjs/vuetify#1286]
### Steps to reproduce
Use Vuetify

### Versions
Latest

### What is expected ?
Since most vue tutorials and boilerplate are binding to `#app`, Vuetify should probably use something else. Laravel by default binds to `#app` as well. I'm sure many other things are too.

### What is actually happening ?
Vuetify binds to `#app` which if the dev is wrapping <v-app> inside of a <div id="app> then when the page is rendered, there are two elements that have an id of `app`.

### Discussion
Feel free to close this if you don't think it's a big deal and think the dev should just change their binding. This is just a suggestion that we were discussing on Discord and I created this issue as a reminder.

**Comment by jacekkarczmarczyk** [comment]
You can bind to any id you want, it doesn't need to be #app
https://codepen.io/anon/pen/prPyKM

**Comment by ryanmortier** [comment]
No I realize that, but internally `<v-app>` is binding to `app` by default. I actually just went and looked at the [code](https://github.com/vuetifyjs/vuetify/blob/97a852eb1672b5fef37e3ba89f16543c42767e70/src/components/app/VApp.js#L11-L14) and realized I could pass an `id` prop into the `<v-app>` component which solves the issue.
