### ISSUE TITLE
[Bug Report] v-autocomplete item-value should be different to item-text

### ISSUE THREAD

**Issue by simongcc** [vuetifyjs/vuetify#12860]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
The reproduction is used the example from the document.
Create an item list of objects with name and amount property. "Select" to store selected value and items to show the item while item-text is `name` without item-value set (default behaviour by returning the line of object selected).
```
items: [
        {name: 'Programming', amount: 1234},
        {name: 'Design', amount: 4455}
],
```

### Expected Behavior
eg. if select `Programming`, the `select` is expected to be ` {name: 'Programming', amount: 1234}`

### Actual Behavior
it returns `Programming`

### Reproduction Link
<a href="https://codepen.io/simongcc/pen/VwKQaPG" target="_blank">https://codepen.io/simongcc/pen/VwKQaPG</a>

### Other comments
Using the same setting, v-combobox behaves as expected. It returns the object of the selected item.
According to the document, `v-combobox` is same as `v-autocomplete`, only that it accepts new value not in the list. So I guess it is bug of v-autocomplete.

**Comment by KaelWD** [comment]
Not a bug, it needs a unique key so `item-text` is used if `item-value` is missing. Use `return-object` if you want an object instead of the value. VCombobox has this enabled by default (#5479).

**Comment by simongcc** [comment]
@KaelWD Oh, thanks much for your time and explanation!
