### ISSUE TITLE
[Bug Report] File Input with Label/Placeholder overlaps

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12867]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 7

### Steps to reproduce
Use both simultaneously.

### Expected Behavior
Label goes above.

### Actual Behavior
Label overlaps placeholder.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/xxEYyez" target="_blank">https://codepen.io/teellcory/pen/xxEYyez</a>

**Comment by KaelWD** [comment]
Duplicate of #12864

**Comment by inane** [comment]
Where can I find the fix for this topic?

**Comment by DRoet** [comment]
its in release v2.4.5

**Comment by inane** [comment]
I am working with the 2.4.9 and same behavior.
