### ISSUE TITLE
Footer in the Layout Pre-defined displaced by container

### ISSUE THREAD

**Issue by jamesxv7** [vuetifyjs/vuetify#1287]
### Steps to reproduce
Visible from https://codepen.io/jamespr/pen/preQrN

### Versions

vue@2.3.4
vuetify@0.14.8

### What is expected ?

Footer component should by displayed at the bottom of the page.

### What is actually happening ?

Footer component appears hidden in the bottom of the page displaced by the container class.

### Reproduction Link

Refers to link in the Steps to reproduce section

I tried to add the following classes to v-app `application--toolbar application--footer application--footer-fixed` but seems doesn't fix the issue.

**Comment by ryanmortier** [comment]
You have to add the `toolbar` and `footer` props to the `<v-app>`.

**Comment by jamesxv7** [comment]
@ryanmortier Thanks a lot!
