### ISSUE TITLE
[Feature Request] v-input allows inconsistent value prop without option of ensuring update by emit

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12875]
### Problem to solve
When using an input with a `value` prop like `<v-text-field :value="text" />`, attempts to change the prop variable can cause two quite counter-intuitive results, which are natural to how Vue passes props, however there are at least two relevant use-cases that aren't properly covered:
1. We can't use value as an **initial value**, as any changes done by user's own input are erased whenever the prop changes.
    * This includes the scenario when we want to conditionally set the value (as there's no reserved value like null/undefined that would mean "don't change"); for example when we update a `number` variable and it gets converted to `NaN`, replacing user's input by `'NaN'` even though it has currently failed the validation error anyway. (It'd be nice to be able to at least postpone replacing the variable until `@blur`.)
1. There's no way to allow forcing a prop to be **set to the same value that has been already set once**, as seen by example at https://codepen.io/cTAlENtATI/pen/zYKzZmM where if you "reset" the first input twice by setting the same initial prop value, it doesn't change the user's input anymore, as it had already drifted away from the model.
    * The correct implementation is to use `@change` or `@input` to set the variable that's passed via value prop. However, the issue here is that **there's no way to enforce that a new value has been correctly passed to the parent!** In case of any issue in the parent, there's a constant risk of the input de-synchronizing at any time, losing its variable binding, and the user won't even notice anything (a bug will stay hidden as an opposite of defensive programming), potentially submitting an incorrect form.

### Proposed solution
1. I could imagine a workaround like using some event to rollback such a programmatic change, which seems to be similar to a proposal https://github.com/vuetifyjs/vuetify/issues/12787 (but maybe the function could also have the form of a filter that provides both old and new value, setting what's returned unless it's undefined). Alternatively some other "initial value" prop probably only makes sense if the value is something like null.
2. Inputs could be safer to use if there were an option (e.g. `no-change-on-input`) to forcefully use `value`, **automatically discarding any custom user input**. We'd then only use the `@change` or `@input` to trigger parent to change the `value` prop, probably with the assumption that it'll occur in the same tick so that the user won't feel any difference while typing. Alternatively if this isn't feasible to be done so fast, there could be some soft timeout of the input reverting back to its bound value.

**Comment by KaelWD** [comment]
In vuetify 3 components no longer hold an internal state if the prop is used.
