### ISSUE TITLE
[Bug Report] Disabled contained button turns flat

### ISSUE THREAD

**Issue by ptheofan** [vuetifyjs/vuetify#12874]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Make a "contained" v-btn
1. mark it as disabled
1. button turns flat

### Expected Behavior
The button should remain contained, with background color as indicated in the [material design disabled button guidelines](https://material.io/design/interaction/states.html#disabled)

### Actual Behavior
The button turns flat.

### Reproduction Link
<a href="https://codepen.io/elecen/pen/yLaKMYx" target="_blank">https://codepen.io/elecen/pen/yLaKMYx</a>

### Other comments
I have tried to add the fab attribute but didn't work.

**Comment by MajesticPotatoe** [comment]
duplicate #12845
