### ISSUE TITLE
[Bug Report] v-select doesn't appear on click inside v-navigation-drawer & v-expansion-panels 

### ISSUE THREAD

**Issue by philchass** [vuetifyjs/vuetify#12881]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.1.0

### Steps to reproduce
open the second panel (section 2)
click on the v-select

### Expected Behavior
the menu should be displayed

### Actual Behavior
the menu is not displayed

### Reproduction Link
<a href="https://codepen.io/cphilc/pen/wvzmjPy" target="_blank">https://codepen.io/cphilc/pen/wvzmjPy</a>

**Comment by KaelWD** [comment]
You have
```
z-index: 999
```
