### ISSUE TITLE
[Bug Report] [Cosmetic] v-text-field label displays over outline after disabling solo

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12882]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
1. Get a non-empty text input with a label
2. Enable solo
3. Enable outline
4. Disable solo

### Expected Behavior
Outline without solo

### Actual Behavior
Outline goes through the middle of the label

![image](https://user-images.githubusercontent.com/3118390/103486017-04f18800-4dfb-11eb-8360-e586f1b45634.png)

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/vYXRjpx" target="_blank">https://codepen.io/cTAlENtATI/pen/vYXRjpx</a>

### Other comments
The issue is minor (as these props are usually set as constants) and resolves itself automatically after clearing the text input when the label animation runs again.

**Comment by johnleider** [comment]
These are intended to be mutually exclusive and are as such in v3 under a new prop named **variant**.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
