### ISSUE TITLE
[Bug Report] Broken columns when printing a page with Chrome/Puppeteer

### ISSUE THREAD

**Issue by Peque** [vuetifyjs/vuetify#12884]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
- Launch the app locally or use "Debug mode" in Codepen
- Print the page with Chromium/Puppeteer
- The 8+4 column width is broken and, instead, a 12+12 width is displayed

### Expected Behavior
The printed columns should keep the 8-4 width, just like when displayed in the browser.

### Actual Behavior
The printed columns use a 12+12 width (one is displayed above the other with full width).

### Reproduction Link
<a href="https://codepen.io/PequeX/pen/LYReqXM" target="_blank">https://codepen.io/PequeX/pen/LYReqXM</a>

### Other comments
Code to reproduce with Puppeteer in case a copy of Chromium is not available:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(
    'http://localhost:8081/#/',
    { waitUntil: 'networkidle2' },
  );
  await page.emulateMediaType('print');
  await page.pdf({ path: 'output.pdf', format: 'A4', printBackground: true});
  await browser.close();
})();
```

**Comment by KaelWD** [comment]
:shrug: 
![image](https://user-images.githubusercontent.com/16421948/103539655-883ed680-4eec-11eb-95f9-8b1f3582bfd5.png)

**Comment by Peque** [comment]
@KaelWD Can you try with this link? (Codepen's debug mode)

https://cdpn.io/PequeX/debug/LYReqXM/vPMKKgdqdQwM

**Comment by KaelWD** [comment]
Yeah I get 12+12 with that, and I just tried /full/ again and got this instead:
![image](https://user-images.githubusercontent.com/16421948/103540367-b40e8c00-4eed-11eb-81ea-9ac4658aa717.png)

**Comment by KaelWD** [comment]
IDK if we can do anything about this, seems like browser fuckery.

**Comment by Peque** [comment]
@KaelWD Just to add more fun, this works:

https://codepen.io/PequeX/pen/bGwajja

Note the only change is to remove the `sm` breakpoint in `<v-col>` and just assign the 8+4 with to the `cols=` attribute.

That is why I thought maybe it was a Vuetify issue and not a browser issue.

**Comment by MajesticPotatoe** [comment]
From what I can tell, when you print, it uses the current screens viewport to define what to print (eg: if you rescale your screen down to say 600px wide and hit print, you will see that the printed preview is set to sm breakpoint). Puppeteer, unless you define a viewport size defaults to 800x600 afaik. you could per puppeteer docs doing:

```js
const browser = await puppeteer.launch({defaultViewport: null})
```
to disable to force it to use max resolution

**Comment by Peque** [comment]
@MajesticPotatoe Yeah, you can change the viewport with Puppeteer. But independently of the viewport size you choose, it should show the columns with width 8+4 for `sm` and higher breakpoints. Unfortunately, it seems the printed columns always look like 12+12.

**Comment by Peque** [comment]
In example, when printing with Chromium directly, I get the same result when resizing the window:

![Screenshot from 2021-01-04 16-02-34](https://user-images.githubusercontent.com/526577/103548626-5b67d080-4ea6-11eb-91ee-c925b7b93ab7.png)
![Screenshot from 2021-01-04 16-02-23](https://user-images.githubusercontent.com/526577/103548627-5c006700-4ea6-11eb-8a49-90334ee4d791.png)

**Comment by KaelWD** [comment]
Viewport affects `$vuetify.breakpoint`, but css breakpoints are based on paper size. It is pretty inconsistent though, toggling between A4 and A3 will randomly render as 12+12, 8+8, or 8+4.

**Comment by Peque** [comment]
@KaelWD Oh, good to know that. That explains why the printed page shows "sm" but is still applying "xs" rules.

**Comment by KaelWD** [comment]
I think this should be regarded as browser quirks, if you want a consistent print layout it's probably a good idea to write your own stylesheet with `@media print` instead of relying on px breakpoints.
