### ISSUE TITLE
v-text-field @change is firing twice

### ISSUE THREAD

**Issue by juan-tonina** [vuetifyjs/vuetify#1288]
### Steps to reproduce
- Create a `v-text-field` with a `@change` (not `.native`) event attached
- Listen to that event
### Versions
Vuetify 0.14.8, Chrome 60

### What is expected ?
The `change` event should be fired once with a string as a parameter

### What is actually happening ?
The `change` event is fired twice, once with an `Event` object and once with a `string`

### Reproduction Link
https://codepen.io/anon/pen/dzMpRj?editors=1112

**Comment by jacekkarczmarczyk** [comment]
I guess it's somehow related to https://github.com/vuetifyjs/vuetify/pull/1251

**Comment by juan-tonina** [comment]
Yes, actually I think it is a duplicate of of #1218

**Comment by juan-tonina** [comment]
Yeah, pretty much duplicate, I debugged it and it is called by `blur`. 

Sorry about that, could not find it before reporting it

**Comment by jacekkarczmarczyk** [comment]
Maybe reopen it, #1218 was closed but seems to be not fixed (unless it will be fixed in 0.14.9, I'm not sure)

**Comment by johnleider** [comment]
#1218 Has not been released yet.
