### ISSUE TITLE
[Bug Report] Sidebar Causes Large CLS Issue, Which is Bad for Google Core Web Vitals

### ISSUE THREAD

**Issue by JSAustin** [vuetifyjs/vuetify#12883]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
Just visit the site. The sidebar doesn't start open. After a few seconds, it opens, but that affects the side layout and causes a layout shift.

### Expected Behavior
The content should load in the proper place, so it doesn't experience a layout shift.

### Actual Behavior
On page load or route change, the sidebar doesn't start open. I believe it is waiting for page to hydrate and for it to see if it should be open or not before it loads. However, this causes the main content to jump. This is a big issue for google. The are adding their Core Web Vitals, including Cumulate Layout Shift (which this affects) to their rankings soon. How can we either start this open by default from Nuxt.js SSR application or pad the content, so it doesn't get affected? Basically, we need to get rid of the shift, or the sidebar can't be used as it will negatively impact site SEO.

### Reproduction Link
<a href="https://jsfiddle.net/12qnoah4/" target="_blank">https://jsfiddle.net/12qnoah4/</a>

### Other comments
You can see the issue here: https://www.mobachampion.com/. I'm following the basic Vuetify layout setup with navbars and main.

**Comment by JSAustin** [comment]
I am able to prevent the layout jump by adding the following CSS to the variable.scss file that is compiled with the rest of Vuetify. It's a bit clunky, and it doesn't allow the sidebar to be closed once opened (or it'd have the permanent space), but that's at least better for now. A permanent, easy solution would be fantastic! :)

@media screen and (min-width: 1264px){
  main {
    padding-left: 256px !important;
  }
}

**Comment by KaelWD** [comment]
That's one of the downsides of SSR. We don't know what the viewport width is going to be so pages always render at the xs breakpoint. If SSR used a desktop breakpoint instead the drawer would start open on mobile which is even worse.

**Comment by KaelWD** [comment]
https://github.com/userquin/vuetify-nuxt-module/ has a solution for this using `Sec-CH-` headers: https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#ssr-http-client-hints
It will double the first response time though.
