### ISSUE TITLE
[Bug Report] v-autocomplete doesn't allow changing value without changing search-input

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12880]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
The primary use-case is that we may want to avoid letting user **accidentally revert their selection to a last selected value** by clicking away from the input while the currently searched text isn't selected as an item. (For example, with available IDs of 11 and 22, the user selects 11, then changes the search to 2 and clicks away, causing 11 to be selected again.)
* There's also a secondary issue that if the user types in a correct value into the search (e.g. 22), it also reverts the same way as long as they don't confirm it (e.g. clicking or pressing enter - actually the enter key also doesn't seem to really trigger the selection either, it just sets the element text). This is very counter-intuitive, as users may expect that the ID is already selected, or at the very least, that the "wrong ID isn't selected anymore". This creates a stressful UX of having to double-check every single form input you make (thus I'd even argue for a different default behavior of the component).
  * It would be nice if we also had the option of making a valid search-input automatically set the value; though this can be replicated manually; but paradoxically, such a workaround isn't directly possible (without using $nextTick), as that also erases the search-input, making the user input suddenly disappear in the middle of typing.

In my scenario, I want to make user confirm adding a selected item using a (+) button (instead of using inline multi-selection). To avoid adding an incorrect item, my idea was that the button could be disabled if `selected value` === `null`. However, this naturally causes a risk of user clicking on the (+) button while the `search-input` !== `selected value`, which once again adds the previously selected value (during an instant after input losing focus and before the button is clicked).
* As a solution, I decided to set the `selected value` to `null` once the `search-input` changes. However, this has an **unexpected side-effect of also erasing the input** even though the `search-input` prop value doesn't change!

### Expected Behavior
* It should be possible to change `value` without changing `search-input` (and especially the real element's input that's backed by it)
* Change of `search-input` should allow `value` to be immediately erased (or it should at least signal the pending change to the user along with the current value)
* The scenario of copying `search-input` to `value` when the search exactly matches an item (after applying a function, for example `(text) => Number(text)`) could be supported directly, for example via new boolean prop of v-autocomplete

### Actual Behavior
* Not only does documentation ignore this use-case, there also don't seem to be workarounds possible
* `search-input` cannot be changed directly to the same text that's already set (making the prop inevitably diverge from a real element's input without any option to force it to reset back) - similar to https://github.com/vuetifyjs/vuetify/issues/12875
* ~~When confirming a selection using Enter key, it enters an illegal state of setting the element input without setting its backing selection `value`~~ - Caused by a mistake of trying to use `:value.sync` instead of `v-model`; though it may be worth considering that in case we fail to set the `:value`, we may prefer to have it automatically revert rather than staying inconsistent with input

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/rNMdYjJ" target="_blank">https://codepen.io/cTAlENtATI/pen/rNMdYjJ</a>

### Other comments
There are several incorrect workarounds that one could attempt within `@update:search-input="(value) => { ... }` of
```vue
<v-autocomplete
      :items="availableItems"
      v-model="selectedId"
      :search-input="search"
```
1. De-select the selected value on input change - causes the search-input to get unexpectedly erased, removing any option to "continue typing", for example to change "22" to "222" without starting from the beginning.
```ts
search = value
if (selectedId !== null && selectedId !== search) {
    // Prevent 'last selected value' from being unexpectedly used after the input changes
    selectedId = null
}
```

2. Automatically select the value when it matches the search - works, but obviously includes the problem of previous point, (making it impossible to type a value that includes any other allowed value in its own prefix)
```ts
search = value
if (availableItems.includes(Number(search))) {
    selectedId = Number(search)
} else if (selectedId !== null && selectedId !== search) {
    selectedId = null
}
```

---

However, there is one solution that works after all! We have to set the `search-input` to null (together with `value`) and then asynchronously set it back.
```ts
search = value
if (availableItems.includes(Number(search))) {
    selectedId = Number(search)
} else if (selectedId !== null && selectedId !== search) {
    // Prevent 'last selected value' from being unexpectedly used after the input changes
    selectedId = null
    // Return the search input back in a next tick
    search = null
    asyncSetSearch(value)
}
```

```ts
methods: {
  asyncSetSearch: async function(value) {
    await this.$nextTick()
    this.search = value
  }
}
```

**Comment by KaelWD** [comment]
> `:value.sync`

Not a thing, use `v-model`

> Steps to reproduce

It's great that you've gone so in-depth, but some simple steps for me to be able to see the underlying problem would be great, eg:
 - select 11 from the menu
 - type "2"
 - blur the input
 - state should be `{ selected: 11, search: 2 }`

**Comment by scscgit** [comment]
Oh you're right, the `:value.sync` was my typo after refactoring, I just fixed it; this only affected selection by clicking on item, but all other scenarios should still behave the same. (This also fixed a side issue of pressing enter key, which was number 3 under Actual Behavior.)

Yeah sorry, there are just too many perspectives to illustrate in one simple scenario, as the root issue is more of an abstract principle (of being unable to easily implement any workarounds around various limitations), which I tried to generalize as `not being possible to change value without changing search-input` (and I already have to use $nextTick so often in similar situations that I'm worried about causing lifecycle conflicts, as the workarounds stack up and events have be delayed for several more ticks).
* Basically the **first checkbox** enables both auto-selection (when the search input matches an item) and de-selection (to avoid the stale reference), and the **second checkbox** fixes the issue of search input being erased.
* Before enabling the first checkbox, typing 22 and clicking away de-selects it (making it impossible for the user to add the ID), causing the state to be `{ selected: null, search: null }`; and when the '11' was already selected, it causes `{ selected: 11, search: null }` (visually making user make a counter-intuitive assumption when adding the ID).
* After enabling the first checkbox and typing 22, it gets selected, but typing a third 2 erases the selection, causing state to be `{ selected: null, search: null }` instead of either `{ selected: 22, search: 222 }` or `{ selected: null, search: 222 }`.

**Comment by lioneaglesolutions** [comment]
@scscgit if this is still an issue, can you please provide steps as outlined in https://github.com/vuetifyjs/vuetify/issues/12880#issuecomment-753758985. It's still unclear what the expected behaviour for this should be and also how to reproduce step-by-step.

Can you create a reproduction (without the work-arounds) and outline;
- when I do this
- I should see this
- but instead I see this

**Comment by scscgit** [comment]
When I type `22`
I should see { selected: `22`, search: `22` }
But I see { selected: *last-selected-value*, search: `22` }
So when I click away, the last selected value is selected again.

* Note there is one inconsistency in Vuetify version 3: when I change the search from `22` to `2`, it behaves the same, but when I completely clear the search `''` and click away (blur), the selected value becomes `null`.

I believe this **is the expected behavior**, so if we want the searched string to be selected immediately, we need a custom solution.

---

The workaround (first checkbox in repro) still doesn't work in latest Vuetify 2, however, **it seems to work fine in latest Vuetify 3**; i.e. I'm able to set the `v-model` within `@update:search`.

---

I also noticed one minor issue in Vuetify 3:

The `@update:search` is triggered with empty string `''` both when we **blur** the input, and also when we **clear** the text. This makes value `''` ambiguous, meaning that when we do
```ts
if (items.includes(value)) {
  selectedId = value
} else if (value !== '') {
  selectedId = null
}  
```
if `items` include `2`, clearing the search input from `2` to `''` keeps the `v-model` value selected as `2`. (This gets de-selected after blur, so it doesn't cause much harm in practice. But what if we need the value to be empty even before blur?)
