### ISSUE TITLE
[Bug Report] Mandatory is not used on list item action clic

### ISSUE THREAD

**Issue by fmontanana-calimed-sante** [vuetifyjs/vuetify#12885]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
1. Clic on the last checkbox selected

### Expected Behavior
The checkbox is not unselected (because of the mandatory). It is the behavior for the clic on item directly

### Actual Behavior
The checkbox is unselected. The list-item is still selected but with a checkbox empty.

### Reproduction Link
<a href="https://codepen.io/MuyBien/pen/mdrLbXG?editors=1010" target="_blank">https://codepen.io/MuyBien/pen/mdrLbXG?editors=1010</a>

**Comment by KaelWD** [comment]
`<v-checkbox readonly` if it's just being used as an indicator, click on the list item still updates it properly.
