### ISSUE TITLE
[Bug Report] v-autocomplete attach enhencment

### ISSUE THREAD

**Issue by hoseinmirian** [vuetifyjs/vuetify#12897]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
the functionality is correct when I add "attach" prop I see the list menu below the search input. what I want is to show the list menu above the search input. showing it not below but above of search input. 

### Expected Behavior
need a prop to change the top or down position of the list menu of the autocomplete

### Actual Behavior
it does not have a prop to customize the position of list menu in autocomplete. 

### Reproduction Link
<a href="https://github.com/FAIRsharing/fairsharing.github.io/blob/Hossein-new-Stack-Grid-Card-%23624/src/components/Records/Search/Input/FilterAutocomplete.vue" target="_blank">https://github.com/FAIRsharing/fairsharing.github.io/blob/Hossein-new-Stack-Grid-Card-%23624/src/components/Records/Search/Input/FilterAutocomplete.vue</a>

### Other comments
please let me know as soon as possible. my email is hosein.mirian@gmail.com and we are working on a project supported by University of Oxford. link to project :
https://github.com/FAIRsharing/fairsharing.github.io

**Comment by KaelWD** [comment]
`menu-props="top"`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
