### ISSUE TITLE
Some .8.8 issues

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#129]
1) :loading on button goes transparent when true.  Using a primary dark v-btn
2) clicking outside of modal not working.  I'm not using an activator, not sure how my v-model varible will get set? 
3) Clicking a v-btn getting a bit darker, maybe the active state.  last clicked button is a bit darker.  primary dark button
4) modal__container/modal__activator seems to be 20px high when not visible?  I'm not using an activator in my modal.
5) v-tooltip:left is acting weird. Not in the correct place. centered?  button is on the right side widows edge.
                <v-btn icon dark @click.native="exitStore()" v-tooltip:left="{ html: 'Exit back to the Purchase screen' }">
                    <v-icon>close</v-icon>
                </v-btn>
6) my sidebar doesn't close when clicking on body.  it did work.  I do see the button 'click', so I know something is working, the sidebar just doesn't hide.

7) updating v-model var in activated() for a checkbox wasn't updating the checkbox to clicked state, but it does work in all other instances.  setting in data, and clicks work fine. other prefs for text fields work fine.

        <v-checkbox v-model="float_main_window" label="Keep window on top" id='unused'></v-checkbox>

activated() {
        this.float_main_window = Helper.getPref('float_main_window');
}

**Comment by johnleider** [comment]
1. Fixed on branch, waiting to merge
2. Will need a codepen or jsfiddle repro
3. Fixed on branch, waiting to merge
4. Fixed
5. Need codepen or jsfiddle repro
6. Fixed potential bug causing this on master branch, if that does not fix it, will need codepen or jsfiddle repro
7. Working on a fix.
