### ISSUE TITLE
[Bug Report] Button background color

### ISSUE THREAD

**Issue by diegogarciar** [vuetifyjs/vuetify#12909]
### Environment
**Vuetify Version:** 2.4.1
**Last working version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.6

### Steps to reproduce
Create button, specify color

### Expected Behavior
Background color is set

### Actual Behavior
Font color is set

### Reproduction Link
<a href="https://codepen.io/diegogarciar/pen/OJREWvL" target="_blank">https://codepen.io/diegogarciar/pen/OJREWvL</a>

### Other comments
I thought it was a breaking change at first, as the documentation examples have also changed. But then the "text" property does nothing. Is this a bug or a feature?

**Comment by MajesticPotatoe** [comment]
duplicate #12903
