### ISSUE TITLE
[Bug Report] Data Table not Sorting

### ISSUE THREAD

**Issue by cawoodm** [vuetifyjs/vuetify#12907]
### Environment
**Vuetify Version:** 1.5.20
**Vue Version:** 2.6.6
**Browsers:** Chrome 87.0.4280.66
**OS:** Windows 10

### Steps to reproduce
The data table is not sorting my data - column header arrows switch but no sort occurs.

### Expected Behavior
sort

### Actual Behavior
no sort

### Reproduction Link
Click "Run"
<a href="http://cawoodm.github.io/powowshell/ide/" target="_blank">http://cawoodm.github.io/powowshell/ide/</a>

![image](https://user-images.githubusercontent.com/498834/103757838-9f2b1900-5011-11eb-9a99-7c8eb205c4a4.png)

### Data Preview

![image](https://user-images.githubusercontent.com/498834/103757807-933f5700-5011-11eb-8220-3f4c34726c53.png)

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
