### ISSUE TITLE
Responsive doesn't work.

### ISSUE THREAD

**Issue by paladin2005** [vuetifyjs/vuetify#1290]
![test](https://user-images.githubusercontent.com/5594428/29093808-1fa6eca2-7c59-11e7-81dc-e6492c567884.gif)
Hi. 
When I resize my browser or view the app in a cellphone, the app doesn't responsive as expected. Instead it's zoomed and everything go small.
It's me or this is a normal behavior?

https://media.giphy.com/media/3o6vY5AvRdwNYIK43C/giphy.gif

Thanks.

**Comment by cawa-93** [comment]
https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by paladin2005** [comment]
Thanks... I don't know where I got my index.html vue template. lol
