### ISSUE TITLE
[Bug Report] Button background colors broken in 2.4.1

### ISSUE THREAD

**Issue by juhasev** [vuetifyjs/vuetify#12903]
### Environment
**Vuetify Version:** 2.4.1
**Last working version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just create a regular button with color="primary" or any other color applied.

### Expected Behavior
Background should take the color -prop value.

### Actual Behavior
Color is applied to the button text instead.

### Reproduction Link
<a href="https://codepen.io/juhasev/pen/yLajdGo" target="_blank">https://codepen.io/juhasev/pen/yLajdGo</a>

### Other comments
I am using dark theme but it appears this bug also exists in the light theme, see the codepen supplied.

**Comment by abrooks693** [comment]
Can confirm bug exists for light theme too.

It looks as if you can workaround it by adding an elevation prop (even 0).

**Comment by Scaenicus** [comment]
> It looks as if you can workaround it by adding an elevation prop (even 0).

Confirmed. Adding `elevation="0"` to all buttons restored old behaviour for now.

**Comment by KaelWD** [comment]
#12892, #12845

@ElijahKotyluk You made it worse, I think I'll fix it this time  
@johnleider Can you please test PRs before merging them

**Comment by PierreBrisorgueil** [comment]
> #12892, #12845
> 
> @ElijahKotyluk You made it worse, I think I'll fix it this time
> @johnleider Can you please test PRs before merging them, or at least go over docs before release to make sure nothing is clearly broken like [FABs](https://cdn.discordapp.com/attachments/351121729164410882/796308675174072370/unknown.png)

+1  https://vuetifyjs.com/en/components/floating-action-buttons/#api
speed-dial are really broken (quick fix by "depressed" v-btn)

**Comment by Shinigami92** [comment]
Is it possible to revert the related PR for the time you are working on fixes?
That way, CDN links could work properly again.

Currently we are using `https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js` on a login page because we expected that no breaking change will occur in just two text-fields and a button.
We also use this strategy especially to not have to manage versioning or building the login view, just serve it.
This strategie worked since release of Vuetify 2.0

**Comment by KaelWD** [comment]
If the page is so simple you shouldn't expect any bugfixes to affect it either, it's never a good idea to allow floating CDN versions. The fix is done and awaiting review, should be out later today.
