### ISSUE TITLE
[Bug Report] The display of the table (v-data-table) is reset if placed on the form.

### ISSUE THREAD

**Issue by doox911-opensource** [vuetifyjs/vuetify#12900]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
Click on reset.

### Expected Behavior
Nothing should change.

### Actual Behavior
Elements visually disappear. And the displayed number of records is reset.

### Reproduction Link
<a href="https://codepen.io/doox911/pen/PoGeyay?editors=1010" target="_blank">https://codepen.io/doox911/pen/PoGeyay?editors=1010</a>

**Comment by KaelWD** [comment]
The form is picking up the "Rows per page" select and resetting its value to `null`

**Comment by doox911Finex** [comment]
> The form is picking up the "Rows per page" select and resetting its value to `null`

Is this a bug?) Even if the table is wrapped in a form
