### ISSUE TITLE
[Bug Report] AutoComplete selection leaves the keyboard open when menu-props="closeOnContentClick" is given

### ISSUE THREAD

**Issue by gmichaeljaison** [vuetifyjs/vuetify#12912]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Run the code in codepen.

### Expected Behavior
iOS keyboard should close on menu select

### Actual Behavior
iOS keyboard remains open hiding half the screen even when the menu is hidden.

### Reproduction Link
<a href="https://codepen.io/michaeljaison/pen/ExgRvje" target="_blank">https://codepen.io/michaeljaison/pen/ExgRvje</a>

**Comment by gmichaeljaison** [comment]
![Uploading IMG_3DE5979C4E7D-1.jpeg…]()

**Comment by immdevrov** [comment]
Usually, for closing native keyboard we need to blur control element (input). I'll try to do it
