### ISSUE TITLE
[Feature Request] v-select can disabled "showMoreItems" for 20 record

### ISSUE THREAD

**Issue by freedomljt** [vuetifyjs/vuetify#12913]
### Problem to solve
When i define my filter action, i can get he correct result.

### Proposed solution
Add params to config the 'showMoreItems'

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
