### ISSUE TITLE
[Bug Report] i18n translation key not found error for languages other then en

### ISSUE THREAD

**Issue by anthonysan95** [vuetifyjs/vuetify#12917]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
Change current locale to any lang other then en and use autocomplete component or datatable

### Expected Behavior
noDataText, dataFooter.itemsPerPageAll, dataTable.itemsPerPageText and all other keys translated

### Actual Behavior
Falling back to default locale translation as shown in console

### Reproduction Link
<a href="https://codesandbox.io/s/cool-cache-ud0oq?file=/src/App.vue" target="_blank">https://codesandbox.io/s/cool-cache-ud0oq?file=/src/App.vue</a>

**Comment by jacekkarczmarczyk** [comment]
`locales: {en, it, de},`

**Comment by lgarczyn** [comment]
Still getting `Translation key "noDataText" not found, falling back to default` when using autocomplete
