### ISSUE TITLE
[Bug Report] Variables.sass headings don't accept empty headers

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#12918]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
add this to your `variables.scss`
```
$headings: (
  "subtitle-1": (), //this is used for....
};
```
I'm using this to show other developer what specific headings are used for. Some of the headings are changed some not.
I thought this worked before but i don't know when it stopped working. It's not a really big deal i removed it.
But i wanted to share the issue anyway

### Expected Behavior
there is nothing changed to subtitle-1 classes

### Actual Behavior
![image](https://user-images.githubusercontent.com/1246691/103884827-66f20c00-50df-11eb-918a-92ec6f80e6ba.png)

**Comment by ricardovanlaarhoven** [comment]
This is a different and more pressing issue, i'm guessing this doesn't happen to empty headers, but the text-subtitle is broken if it's not presented to the headings variable.

When i remove all the headers from my variables.scss the text-subtitle-1 works. If i have any header variable changed, it breaks

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
