### ISSUE TITLE
[Bug Report] Halved gutter width between v-rows

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#12915]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
After the breaking change in 2.4.0 all layouts with nested `dense` `v-row`s are kinda broken.

Current workaround is to remove the `pt-0` and `pb-0` in the nested `v-col` and then add a `pt-1` in each `v-row`

This is just one breaking example and I would have around 80 more files to check with maybe some more complex layout issues.

### Expected Behavior
Working as in 2.3.23

### Actual Behavior
Has a workaround, but I want to ask if this is going to be re-worked and should I wait for more bug fixes or if I am now revising ~80 files in my project

### Reproduction Link
<a href="https://codepen.io/shinigami92/pen/RwGJxvG" target="_blank">https://codepen.io/shinigami92/pen/RwGJxvG</a>

### Other comments
https://github.com/vuetifyjs/vuetify/issues/11408#issuecomment-750868206

**Comment by KaelWD** [comment]
Was this just a workaround for #11408? As I said in #12848, workarounds generally need to be removed when the underlying bug is fixed, particularly when it comes to CSS. 

> add a pt-1 in each v-row

What's this supposed to do?

**Comment by Shinigami92** [comment]
I have made 3 screenshots
So on the first screenshot you can see that everything is normal and working
After just updating the top and first vertical gutter of the outer row are both smaller
This can be fixed with adding `pt-1` to both `v-row`
Also the right top 2 `v-col` in the nested `v-row` don't need their `pt-0` and `pb-0` now

_Screenshot 1 and 3 are visually equivalent_

---

Yes I think it was a workaround for #11408 
I didn't saw #12848 before, I will have a look into it and maybe try some of these css global workarounds :thinking: 

## 2.3 
![Dashboard-2 3](https://user-images.githubusercontent.com/7195563/103875695-0ceb4980-50d3-11eb-8385-e59bbf906a25.png)

## 2.4 broken 
![adSoul-Dashboard-2 4-broken](https://user-images.githubusercontent.com/7195563/103875698-0d83e000-50d3-11eb-963b-85cc1822b37c.png)

## 2.4 workaround
![adSoul-Dashboard-2 4-workaround](https://user-images.githubusercontent.com/7195563/103875700-0e1c7680-50d3-11eb-854d-ffa5c088ed5d.png)

**Comment by KaelWD** [comment]
Oh right, there's another bug where the space between `v-row`s is halved. If I fix that you won't need any CSS workarounds, just remove the `pt-0`/`pb-0` ones.

**Comment by Shinigami92** [comment]
Perfect :+1: 
So I will wait for the next update, thanks
You can close this issue if you want
