### ISSUE TITLE
[Feature Request] Introduce sizes for tooltips

### ISSUE THREAD

**Issue by dhanushkac** [vuetifyjs/vuetify#12924]
### Problem to solve
Sizing support is available for icons and buttons. When we are using different sizes than medium the default tooltip size is large to match with the UI.

### Proposed solution
Introduce five different sizes (x-small, small, medium (default), large, and x-large).

**Comment by NiloCK** [comment]
This may or may not suit your needs, but I'll point out that you can apply typography classes (`headline`, `subheading`, etc) to the tooltip via the `content-class` prop, which will alters the text size and the tooltip adjusts gracefully.

**Comment by dhanushkac** [comment]
> This may or may not suit your needs, but I'll point out that you can apply typography classes (`headline`, `subheading`, etc) to the tooltip via the `content-class` prop, which will alters the text size and the tooltip adjusts gracefully.

I agree that can be done. How about thinking in the perspective of tooltip as a component? in that case if we use sizes for tooltip won't that be more meaningful in component context?
