### ISSUE TITLE
[Bug Report] v-data-table outlined icons are not properly aligned

### ISSUE THREAD

**Issue by KeterSCP** [vuetifyjs/vuetify#12928]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Create data table with column for buttons with outlined icons.

### Expected Behavior
Icons are properly aligned inside buttons.

### Actual Behavior
Icons are placed outside the button boundary.

### Reproduction Link
<a href="https://codepen.io/Keter_SCP/pen/XWjBgXK" target="_blank">https://codepen.io/Keter_SCP/pen/XWjBgXK</a>

### Other comments
Manually adding `justify-content: end;` to the icon fixes the issue.

**Comment by jacekkarczmarczyk** [comment]
it's `help_outline`
