### ISSUE TITLE
[Bug Report] [v-data-table] this.options.sortBy.findIndex is not a function when multiSort is disabled

### ISSUE THREAD

**Issue by jualoppaz** [vuetifyjs/vuetify#12929]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
- Disable multiSort
- Add custom sortBy property in string format
- Add custom sortDesc property in boolean format

### Expected Behavior
- A whole sortable table

### Actual Behavior
- Execution error during header generation that avoid normal working

After a quick review in v-data-table code I saw that header generation only allows String[] syntax for sortBy property: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts#L84

However, as vuetify docs says, it's possible to define sortBy and sortDesc properties without array type and define them in options param with other configs.

Is it possible that header generation is not well dynamic? Or did I make a mistake during the sorting configuration?

Thank you so much.

### Reproduction Link
<a href="https://codepen.io/jualoppaz/pen/gOwjogb?editors=101" target="_blank">https://codepen.io/jualoppaz/pen/gOwjogb?editors=101</a>

**Comment by hannah-wj-sky** [comment]
Did you find a way around this bug?  I'm having the same issue since I've migrated from 1.5 to 2.x

**Comment by KaelWD** [comment]
> as vuetify docs says, it's possible to define sortBy and sortDesc properties without array type and define them in options param with other configs

Only the standalone `sortBy` prop can be a primitive value, in `options` it is always normalised to an array. Your codepen works if you do this: 
```js
sortBy: ['name'],
sortDesc: [true],
```
