### ISSUE TITLE
[Bug Report] v-spacer creates line break if used in v-card-actions

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#12935]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Firefox 84.0 and Chrome 87.0
**OS:** Ubuntu 20.04

### Steps to reproduce
Create v-dialog with v-card layout. Add multiple v-btn to v-card-actions. Try to align the buttons left an right with the help of a v-spacer in between.

### Expected Behavior
v-spacer should add a flexible space that pushes the buttons apart which aligns them on  the left and right side. All buttons stay in the same line

### Actual Behavior

Add v-spacer --> will insert line break between buttons instead of spacer. All buttons will be aligned left
Delete v-spacer --> line break will be gone, buttons are on the same line again. But still aligned left

### Reproduction Link
<a href="https://jsfiddle.net/rn9o1p4g/25/" target="_blank">https://jsfiddle.net/rn9o1p4g/25/</a>

**Comment by frederikheld** [comment]
Workaround:

```
      <v-card-action>
        <v-row>
          <v-col
            cols="4"
            class="text-left"
          >
            <v-btn
              text
            >
              Close
            </v-btn>
          </v-col>
          <v-col
            cols="8"
            class="text-right"
          >
            <v-btn
              text
              class="mr-4"
            >
              Back
            </v-btn>

            <v-btn
              color="primary"
            >
              Continue
            </v-btn>
          </v-col>
        </v-row>
      </v-card-actions>
```

**Comment by ElijahKotyluk** [comment]
I was having trouble with the styles rendering in your reproduction so here is an example codepen: [Working example](https://codepen.io/elijahkotyluk/pen/GRjXqNd) (v2.3.6)
This seems to be working as expected, try removing the `v-col` that wraps your buttons and you should get your desired result, you can test this in the codepen link I've supplied.

**Comment by frederikheld** [comment]
I see the same unintended line break in your example as in mine.
![Screenshot from 2021-01-29 01-15-39](https://user-images.githubusercontent.com/11460463/106214707-a89e4000-61cf-11eb-81b1-80959124d584.png)

I changed the text of the first button to make sure that the line break is not caused by the text legth.

**Comment by frederikheld** [comment]
Thanks for looking into this @ElijahKotyluk.

So I'm intended to not use grid layout in actions? Is this really intended?

This example in the docs uses v-row, so I would expect to be allowed to use v-col as well...

https://vuetifyjs.com/en/components/cards/#weather-card

The whole Grid layout system is very inconsistent. Is there any documentation on which elements can contain a grid layout and which can't? And why can I use v-spacer (which is a part of Grid) in v-card-actions, but not v-col? Very confusing.
