### ISSUE TITLE
Text field in data table loses focus

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#1293]
### Versions

Vue 2.3.4
Vuetify 0.14.8
macOS Sierra 10.12.6
Chrome 60

### What is expected ?

That text fields in data tables can be edited, without them losing focus after every keypress.

### What is actually happening ?

They are losing focus after every key press. It seems that the whole `items`-slot of the data table is re-rendered after every key press. I first thought this was caused by the text field using the `props` variable in its `v-model` (the first text field in the JSFiddle). I therefore tried to avoid using the `props` variable (second text field in the JSFiddle) or use a completely different variable for the `v-model` of the text field (the last two text fields in the JSFiddle), but that also doesn't help.

### Reproduction Link

https://jsfiddle.net/okgbzo4s/1/

**Comment by numfin** [comment]
same shit. annoying af

**Comment by emrdev** [comment]
+1 - we're also seeing this issue

**Comment by johnleider** [comment]
While I'm looking into this, I can tell you it's more than likely not something the components are doing wrong.

An easy way to test this would be to wrap your content in a tr and apply a key to it, as you can see here, it doesn't occur: https://jsfiddle.net/dqx8dg72/

I'll continue to look into this though.

**Comment by johnleider** [comment]
I love it when I'm wrong, found the issue, thank you for your patience!
