### ISSUE TITLE
[Documentation] Document how v-model works in v-list component

### ISSUE THREAD

**Issue by juddfranklin1** [vuetifyjs/vuetify#12932]
### Problem to solve
In the List component docs, there is [an elegant implementation](https://vuetifyjs.com/en/components/lists/#action-stack) of a list of messages with one highlighted. List item highlighting is controlled by the `v-model` value on the `v-list` component, but this is not noted anywhere in the examples.

### Proposed solution
Add basic v-model example to the List page, or at least indicate its usage in the `action-stack` example.

**Comment by MajesticPotatoe** [comment]
`v-list` don't have a **value** / **v-model** or any sort of state functionality. What you are actually seeing in such examples is a function of `v-list-item-group` as [noted here](https://vuetifyjs.com/en/components/lists/#caveats).
