### ISSUE TITLE
[Feature Request] <v-bottom-navigation app grow dark contain fixed> should hide itself, but stays above the keyboard on android

### ISSUE THREAD

**Issue by bitdom8** [vuetifyjs/vuetify#12931]
### Problem to solve
BUttom nav bar is staying above the keyboard

### Proposed solution
It can have event listeners and hide itself when keyboard is open by user

**Comment by bitdom8** [comment]
https://ibb.co/xhG9Gcz here is the ss

**Comment by KaelWD** [comment]
You should implement this yourself if you need it, some people may be relying on the current behaviour.
