### ISSUE TITLE
[Feature Request] v-select caret to not display when ReadOnly=true or disabled=true

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#12930]
### Problem to solve
It eliminates confusion on part of user that a control *looks* usable but isn't.

### Proposed solution
Hide the caret on readonly=true or disabled=true

**Comment by MajesticPotatoe** [comment]
This can be achieved in userland already by adding `append-icon=""`. Also isn't standard HTML select behavior, so doesn't makes much sense to force this stylistic preference as default.

**Comment by WhatFreshHellIsThis** [comment]
append-icon controls the "caret"?  That doesn't sound right at all.

**Comment by WhatFreshHellIsThis** [comment]
Wow, how bizarre is that?  Ok, that did work, my bad, I thought there was no other way, thank you, I always thought that option meant an "additional" icon not a replacement for the actual in use caret icon.  Thank you.
