### ISSUE TITLE
[feature request]: Browser’s history on Modal

### ISSUE THREAD

**Issue by ram-you** [vuetifyjs/vuetify#1294]
Would like to manipulate the browser’s history so that the user can  close the Dialog via the “back” button and the initial URL is restored when the Dialog is closed.

A good implementation's example with PhotoSwipe :
https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/history.js

**Comment by johnleider** [comment]
Could a dev technically apply this logic their-selves?

**Comment by ram-you** [comment]
Yes as an option.  For example 'hash' as an option in dialog.

**Comment by johnleider** [comment]
Unfortunately at this time, we will not pursue this functionality.
