### ISSUE TITLE
[Bug Report] How to add categories and still be able to change agenda type?

### ISSUE THREAD

**Issue by fmontanana-calimed-sante** [vuetifyjs/vuetify#12942]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Linux x86_64

### Steps to reproduce
When changing type to a category type, it's not possible to show more than 1 day. Even with the `start/end` props or the `weekdays` prop.

### Expected Behavior
The week display with the categories for each day

### Actual Behavior
Only one day with categories 

### Reproduction Link
<a href="https://codepen.io/MuyBien/pen/LYRJzRP" target="_blank">https://codepen.io/MuyBien/pen/LYRJzRP</a>

### Other comments
Is that possible to do so? How to do such display (categories for week or day types)?

**Comment by fmontanana-calimed-sante** [comment]
I found the `:category-days="3"` props but I cannot choose which day I don't want to show (weekend for example...). Is there a way to accomplish that?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
