### ISSUE TITLE
[Feature Request] Calling validation rules should keep 'this' for the sake of i18n

### ISSUE THREAD

**Issue by wglas85** [vuetifyjs/vuetify#12940]
### Problem to solve
i18n in custom field validators

### Proposed solution
Change
vuetify/packages/vuetify/src/mixins/validatable/index.ts:254
from
```javascript
 const valid = typeof rule === 'function' ? rule(value) : rule
```
to
```javascript
 const valid = typeof rule === 'function' ? rule.call(this,value) : rule
```

**Comment by wglas85** [comment]
To be more precise, I tried to add validation rules like
```javascript
rules: {
  required(value) {
    return !!value || this.$t('input.required');
  },
  email(value) {
    const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return pattern.test(value) || this.$t('input.invalidEMail');
  },
}
```
to my component, with `this.$t` referring to the translation function registered by the `vue-i18n` plugin.
I have no other solution to refer to `$t` apart from having access to the Vue instance of the component, which calls the validation function, which is actually the `this` pointer in the context calling the validation rule.
Hence, preserving `this` would solve my problem and the above mentioned validation code would work as expected.

**Comment by KaelWD** [comment]
`this` would then be the VTextField instance, not your component.

If you're defining the rules in `data`:

 - If `data` is normal function, make your rules arrow functions
 - If `data` is an arrow function, the first argument is the current component instance: https://vuejs.org/v2/api/#data

**Comment by wglas85** [comment]
OK, I wanted to put the rules into a separate ES6 module.
I now went with
```
export function makeInputRules(vm) { return {
  required(value) {
    return !!value || vm.$t('input.required');
  },
  email(value) {
    const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return pattern.test(value) || vm.$t('input.invalidEMail');
  },
}}
```
and put `rules: makeInputRules(this)` to my component's data function.
This is acceptable, but would be much easier, if you set `this` when calling the rule.
