### ISSUE TITLE
[Documentation] Contents "Events" click in calendar api scrolls to "Props"

### ISSUE THREAD

**Issue by IIFelix** [vuetifyjs/vuetify#12941]
### Environment

**Browsers:** Edge 87.0.664.75
**OS:** Windows 10

### Steps to reproduce
Click on the "Events" link in Contents. 

### Expected Behavior
Should scroll to events of component

### Actual Behavior
Scrolls to props. 

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-calendar/#events" target="_blank">https://vuetifyjs.com/en/api/v-calendar/#events</a>

### Other comments
Probably because there is a prop called "events"

**Comment by MajesticPotatoe** [comment]
This has been resolved.
