### ISSUE TITLE
[Bug Report] update:options event listener emits wrong value in v-data-table

### ISSUE THREAD

**Issue by Masa-Shin** [vuetifyjs/vuetify#12946]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. In the repro link, the table was sorted desc by `rank` at first.
2. click the blue button below the table to sort asc by `value`.
3. the table would be sorted desc, not asc.

In short, when `sortBy` and `sortDesc` was updated simultaneously, only change of `sortBy` would be applied, because `update:options` event listener emits a wrong value. 

### Expected Behavior
When `sortBy` and `sortDesc` were updated simultaneously, both of them should change properly. 

### Actual Behavior
Only `sortBy` changes.

### Reproduction Link
<a href="https://codepen.io/POPOPON/pen/BaLqBJZ" target="_blank">https://codepen.io/POPOPON/pen/BaLqBJZ</a>

### Other comments
- sort can be updated from the header so `@update:options` event listener is necessary.
- replacing the listener to `update:sort-by` and `update:sort-desc` event listeners is not a desirable solution because I want just one event fired when `sortBy` and `aortDesc` updated simultaneously.

**Comment by Masa-Shin** [comment]
The repro link was wrong, now fixed.

**Comment by ryanrapini** [comment]
Any progress on this? I'm having similar issues with v-data-table sortby. I can provide my own details soon

**Comment by iliasaddab** [comment]
just like ryan i left only the :options.sync and then
watch: {
    options(newValue, oldValue) {
      let cont = false
      if(oldValue.page!==newValue.page)cont=true
      if(oldValue.itemsPerPage!==newValue.itemsPerPage)cont=true
      if(oldValue.sortBy!==newValue.sortBy)cont=true
      if(oldValue.sortDesc!==newValue.sortDesc)cont=true
      if(cont)this.fetchItems()
    }
  },

**Comment by lioneaglesolutions** [comment]
@johnleider this does seem to be a bug with the options object being emitted with only one of the `sortBy` or `sortDesc` values correct. I couldn't find the source but will investigate further when I get a chance.
