### ISSUE TITLE
[Bug Report] Clearing autocomplete using backspace not working

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#12958]
### Environment
**Vuetify Version:** 2.4.2
**Last working version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Linux x86_64

### Steps to reproduce
1. Select any item
2. Try to clear using backspace

### Expected Behavior
Value cleared

### Actual Behavior
Value not cleared

### Reproduction Link
<a href="https://codepen.io/djaler/pen/ZEpmazq" target="_blank">https://codepen.io/djaler/pen/ZEpmazq</a>

### Other comments
Looks like it was broken here https://github.com/vuetifyjs/vuetify/commit/f1b621b3c400ef18c233850a1583ec0d0fa9f0ff

**Comment by Djaler** [comment]
@KaelWD hello

**Comment by MajesticPotatoe** [comment]
Behavior looks the same even back on [v2.0.0](https://codepen.io/majesticpotatoe-the-bashful/pen/poEqQrK) and in [v1.5.x](https://codepen.io/majesticpotatoe-the-bashful/pen/ExgGOoz). Can you provide an example where its working as intended, or are there possibly reproduction steps missing?

**Comment by Djaler** [comment]
https://codepen.io/djaler/pen/yLaGQKx this is the same code but with 2.3.17

Also, more detailed steps:
1. Open autocomplete by click on it
2. Select any item
3. Click anywhere else to remove focus from autocomplete
4. Open autocomplete by click on it again
5. Press backspace first time -> search will be cleared
6. Press backspace second time -> autocomplete value will be cleared

https://github.com/vuetifyjs/vuetify/blob/f1b621b3c400ef18c233850a1583ec0d0fa9f0ff/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L236:L255 that's the code
