### ISSUE TITLE
v-text-fields are not styled when used in a v-data-table footer slot

### ISSUE THREAD

**Issue by robodude** [vuetifyjs/vuetify#1295]
### Steps to reproduce
Create a `v-data-table`
Add footer slot
Have footer cell contain a `v-text-field `

### Versions

Vue.js v2.4.2
Vuetify v0.14.8
Chrome v59.0.3071.115
Firefox v54.0.1

### What is expected ?
I would expect the inputs within the tfoot to appear in the same consistent way across various components.

### What is actually happening ?
The input fields are missing the the underline. It does not appear correctly when the cursor is within the input element either.

### Reproduction Link
https://jsfiddle.net/tgpfhn8m/

**Comment by jacekkarczmarczyk** [comment]
There's a following rule that changes the styling of the input:

`.datatable tfoot .input-group__details {
    display: none;
}`

Not sure why it's there, but for now you can try to override it in you css
