### ISSUE TITLE
[Documentation] Missing $shadow-key-ambient-opacity, $shadow-key-penumbra-opacity, $shadow-key-umbra-opacity variables in documentation

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#12952]
### Environment

**Browsers:** Chrome 87.0.4280.141, Other, Opera, Internet Explorer, Microsoft Edge, Safari, Mozilla Firefox, Google Chrome
**OS:** Mac OS 11.1.0, Windows, Android, Mac OSX, Linux, iOS

### Steps to reproduce
https://vuetifyjs.com/en/api/vuetify/#sass-variables
search for:
* $shadow-key-ambient-opacity
* $shadow-key-penumbra-opacity
* $shadow-key-umbra-opacity

### Expected Behavior
variables be present

### Actual Behavior
Variables aren't present

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/vuetify/#sass-variables" target="_blank">https://vuetifyjs.com/en/api/vuetify/#sass-variables</a>

**Comment by MajesticPotatoe** [comment]
They have never been documented, as they are a part of elevation sass variables and there currently isn't much of a system for non-component based sass at the moment (we are only showing light/dark and global).

In the meantime you can view these in [source](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_elevations.scss)

**Comment by joelpro2** [comment]
> They have never been documented, as they are a part of elevation sass variables and there currently isn't much of a system for non-component based sass at the moment (we are only showing light/dark and global).
> 
> In the meantime you can view these in [source](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_elevations.scss)

I know, i've talked with @nekosaur about it, but i believe that those variables have a major importance when dealing with elevation(for exemple to change the color or to control the opacity) and should be present in the documentation, in the $vuetify SASS variables section.
