### ISSUE TITLE
[Feature Request] Button: Use different attribute name other than "depressed"

### ISSUE THREAD

**Issue by kareemsalah227** [vuetifyjs/vuetify#12950]
### Problem to solve
There isn't really a problem in this sense, it's only that I find the attribute `depressed` for the buttons not a good name, I personally was suffering from depression and I have a bit of trauma whenever I read stuff about depression or even reading the word itself.

### Proposed solution
I suggest to use a different name, maybe `plain` instead of `depressed`.

**Comment by KaelWD** [comment]
> or even reading the word itself

Maybe you should get some therapy then. 

This has been changed to `flat` in v3 though, we couldn't use `flat` (or `plain`) in v2 as they're already used for other things.
