### ISSUE TITLE
[Bug Report] v-select single-line label disappears

### ISSUE THREAD

**Issue by PhentomPT** [vuetifyjs/vuetify#12968]
### Environment
**Vuetify Version:** 2.4.2
**Last working version:** 2.3.23
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141, Other
**OS:** Windows 10

### Steps to reproduce
Click on the menu and select an item, then if you click again the label disappears until the dropdown menu is closed

### Expected Behavior
the label should remain visible
![image](https://user-images.githubusercontent.com/8815300/104728258-8667e500-572e-11eb-8682-656928141ab8.png)

### Actual Behavior
the label disappears
![image](https://user-images.githubusercontent.com/8815300/104728172-69331680-572e-11eb-95f1-810563caf59c.png)

### Reproduction Link
<a href="https://codepen.io/PhentomPT/pen/gOwZpep" target="_blank">https://codepen.io/PhentomPT/pen/gOwZpep</a>

### Other comments
If you switch to the vuetify version 2.3.23 in the settings of codepen you don't have the same issue.
Additionally in the VueDevTools the element `<VLabel>` under `<VSelect>` is removed everytime the issue occurs

![image](https://user-images.githubusercontent.com/8815300/104728104-515b9280-572e-11eb-84a7-f29b20d53a42.png)

**Comment by Maryna-mart** [comment]
I have the same issue

**Comment by spyua** [comment]
I guess it's not a bug.

I have the same problem. I found my problem is that the vuetify theams light setting.

If your default light setting color is white color. And your backgorund color is also white color.

When the selector hightlight the item. The color will follow the  vuetify theams light primary setting.

So it looks like disapper.

You can check that. 

The simple demo as below

![image](https://user-images.githubusercontent.com/20264622/163131016-2f8fd5bb-869c-47cd-9785-86aaba4c627c.png)

If you select in different light setting

![image](https://user-images.githubusercontent.com/20264622/163131309-0164e01f-642b-4f4c-b773-ad99acbaaf23.png)
