### ISSUE TITLE
[Bug Report] pulldown menu does not close after hitting "Enter" or clicking on "x"

### ISSUE THREAD

**Issue by ice987987** [vuetifyjs/vuetify#12961]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Safari 14.0.2
**OS:** Mac OS 10.15.6

### Steps to reproduce
Enter a value which is available in the pulldown list and hit "Enter" -> pulldown menu does not close
Enter a value which is not available in the pulldown list and hit "Enter" -> pulldown menu appears
Click on "x": pulldown menu appears
Expected behavior
pulldown menu disappear/close if hitting "Enter"
pulldown menu disapper/close if clicking "x"

### Expected Behavior
pulldown menu disappear/close if hitting "Enter"
pulldown menu disapper/close if clicking "x"

### Actual Behavior
pulldown menu does not close / pulldown menu appears

### Reproduction Link
<a href="https://codepen.io/ice987/pen/abmjjeq" target="_blank">https://codepen.io/ice987/pen/abmjjeq</a>

### Other comments
See https://github.com/Scrounger/ioBroker.vis-materialdesign/issues/142 for reference

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
