### ISSUE TITLE
[Bug Report] VDatePicker disappears with invalid time value error

### ISSUE THREAD

**Issue by gongora92** [vuetifyjs/vuetify#12969]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 87.0.4280.141
**OS:** Mac OS 10.15.7

### Steps to reproduce
In the date text field type any date with a year before 90 (For example: 11/11/0070, 11/11/0001, 11/11/0010)
Open the DatePicker
Click on the Month header
![image](https://user-images.githubusercontent.com/44581880/104740369-7ee41400-570d-11eb-8420-1be73eb2286b.png)

Click on the Year header
![image](https://user-images.githubusercontent.com/44581880/104740422-8efbf380-570d-11eb-953e-0555ea18f375.png)

As you can see the DatePicker disappears
![image](https://user-images.githubusercontent.com/44581880/104740449-958a6b00-570d-11eb-9eff-7b5d3acc6052.png)

### Expected Behavior
It should handle that kind of errors, it's a valid date

### Actual Behavior
DatePicker disappears

### Reproduction Link
<a href="https://codepen.io/AlesxRdz/pen/RwGEreY?editors=101" target="_blank">https://codepen.io/AlesxRdz/pen/RwGEreY?editors=101</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
