### ISSUE TITLE
[Bug Report] VTimelineItem Icon always gets dark theme color (white)

### ISSUE THREAD

**Issue by bfritscher** [vuetifyjs/vuetify#12971]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/timelines/#icon-dots
Switch to light or dark mode.(Icon is always white)

### Expected Behavior
Icon color should follow theme. Or is this the expected behaviour?

### Actual Behavior
Set the appriopriate icon color from theme.

### Reproduction Link
<a href="https://codepen.io/bfritscher/pen/vYXvKzx" target="_blank">https://codepen.io/bfritscher/pen/vYXvKzx</a>

### Other comments
In https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTimeline/VTimelineItem.ts
Icon is created with this code:
```js
  return this.$createElement(VIcon, {
        props: {
          color: this.iconColor,
          dark: !this.theme.isDark,
          small: this.small,
        },
      }, this.icon)
```

Why is dark inverted? And no light propagated?

**Comment by ElijahKotyluk** [comment]
If you use the [icon slot](https://vuetifyjs.com/en/api/v-timeline-item/#icon) you have more control over the styling of the icon and the icon will abide by the dark/light theme set in the `VTimelineItem`.

**Comment by patrickelectric** [comment]
I have the same problem, using with:
```
<v-timeline-item
  v-for="(item, i) in events"
  :icon="mdi-comment"
  fill-dot
>
```

**Comment by patrickelectric** [comment]
Running vuetify 3.0.0-beta.10
![image](https://user-images.githubusercontent.com/1215497/190495106-94c2eb52-43ce-45db-81c2-8b734f35827f.png)
