### ISSUE TITLE
[Bug Report] VSelect - popup moves to the left after click

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12979]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Mac OS 11.1.0

### Steps to reproduce
1. Select any item from the list.
2. As you can see, after click, the popup has moved to the left which looks strange.

![Screen Recording 2021-01-17 at 19 51 50](https://user-images.githubusercontent.com/17653648/104852923-abf71900-58fd-11eb-942f-a2a9ac5d86c2.gif)

### Expected Behavior
Popup should stay in place.

### Actual Behavior
Popup position is moved to the left.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/KKgJdVX?editors=1010" target="_blank">https://codepen.io/mikilll94/pen/KKgJdVX?editors=1010</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
