### ISSUE TITLE
[Bug Report] Full Width Text Field is not equivalent to width: 100%

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#12978]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Linux x86_64

### Steps to reproduce
Any text field has this problem.

### Expected Behavior
A text field which has `full-width` does not float label when focused or has content.

### Actual Behavior
`full-width` implies `width: 100%` but there are some differences, one is that the label does not float and some spacing are different. Are these intentional? because it seems that `full-width` should === `width: 100%`

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/yLaZNLe" target="_blank">https://codepen.io/yooneskh/pen/yLaZNLe</a>

**Comment by johnleider** [comment]
full-width is a design style that is covered under **variants** for Vuetify 3.

This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
