### ISSUE TITLE
[Bug Report] Hide on scroll doesn't remove v-main padding when scrolling using custom scroll target

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#12974]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.77
**OS:** Mac OS 11.1.0

### Steps to reproduce
1. Add a scrollable fixed height content area
2. Add an `v-app-bar` with `hide-on-scroll` and a custom `scroll-target`
3. Set the `scroll-target` to the fixed height content area

### Expected Behavior
When scrolling the content gets bumped up when the app bar extension area is hidden.

### Actual Behavior
When scrolling the extension area is hidden but the `v-main` padding is not removed so there is a gap.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-scroll-target-2f55k" target="_blank">https://codesandbox.io/s/vuetify-scroll-target-2f55k</a>

### Other comments
The reproduction link is a simplified example. The real world use case which caused me to run into this issue was using the `v-virtual-scroll` component which requires a fixed height for scrolling and also trying to take advantage of hiding the app bar.

**Comment by johnleider** [comment]
v3 reproduction: https://play.vuetifyjs.com/#eNrtV01v2zAM/SuChqEtUNtZg128NGgwBNuh2IZs2KXuQYmZRKssCRKdDwT576Nsx03SHgoM2Mk36T3qPZL2gXzY8ZG18aoEnvIBQmGVQBhmmrHBKhLWVsfDJZoKx/zMGaWiKSzFShp3m/GlzCHjBwKFWwASHNcAuIw3KpWOnBk9LHIZkSnK+XaQNNhRTOMVoUQFw9/PgadE++KQOHsHGwTtJcn9/Dz5fn/Pfn0dsy+T8fgbG03Go0FyUiM9fRYlpC22EFKzmRLeUyGv10EpI0WBY3NVyryliMzlaoiloxQHSTh3VEd1VEd1VEd1VEd1VEf9FypMt+2cejTxhvG2HvLr8ZfOJ5MxXWnolRarINhY45DlMBelQrardbQoIGUXP5TYLpwpdX5xXRO5QJGyyyt2O2SXu/1VBe+DQ6sZ9HGrgHYGYyHMzu2yUMtPxeypVk3ZwgHoTwE1K3BzZdYpEyWaCrLGS6Rxn6CpN6pEqOAlyMUSU/ax17ObClnLHJcp+9Drvad7nU5Igbz5NZdFKJH6YuM/3mhahqo0sobwGU8PdWecFpdwp8UH0fo0SWa5pmc5KLlysQZMtC2SOwpLXKlRFhDlprjrx/24R3sTirhPX8njMRuDL6KpM2sPjrQy3jSzcgvbzxscm0gyuolvaocGihR1J1i8kE7Ij7oaOdA5uLDjvK2ws2evFHcW8aLA5q/YU/eV1E/+rPEzXzX94ZDrP1VeiQWlx2C4v+bH6VIC1Tv++BdcwKiu
