### ISSUE TITLE
Issue with a text box placed inside a temporary navigation drawer

### ISSUE THREAD

**Issue by emrdev** [vuetifyjs/vuetify#1297]
### Steps to reproduce

Add a 'v-navigation-drawer' to app, set to 'right' & 'temporary'
Add a 'v-text-field' into the drawer content
Add a means to toggle the drawer visibility
Open the draw
Click to focus the text field
Start to type

NOTE: I placed the content of my navigation drawer inside a template, e.g.

`<v-navigation-drawer>
    <my-template></my-template>
</v-navigation-drawer>`

### Versions

    "vue": "^2.3.3",
    "vue-router": "2.7.0",
    "vuetify": "0.14.8"

### What is expected ?

Clicking in the text box and typing - no side-effects, text can be entered normally

### What is actually happening ?

Each character typed seems to toggle the scrim for the navigation drawer - so typing triggers a very obvious screen-wide flicker

### Reproduction Link

I tried to generate a codepen, but I couldn't get v-text-field to render using the forked vuetify codepen issue template

**Comment by emrdev** [comment]
Also, if I make the navigation drawer 'persistent' instead of 'temporary' there's no issue typing in the text box

**Comment by johnleider** [comment]
Issue reports require a codepen in order to debug. Although, the first thing I see is you are using 2.3.3 with 0.14.8. 0.14 branch requires vue@2.4
