### ISSUE TITLE
[Bug Report] Mouse wheel does not work when input type is number inside a dialog.

### ISSUE THREAD

**Issue by artmarydotir** [vuetifyjs/vuetify#12986]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Ubuntu undefined

### Steps to reproduce
mouseweel not work in dialog

### Expected Behavior
work everywhere

### Actual Behavior
not work in dialog

### Reproduction Link
<a href="https://codepen.io/artmarydotir/pen/GRjzYEz?editors=101" target="_blank">https://codepen.io/artmarydotir/pen/GRjzYEz?editors=101</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
