### ISSUE TITLE
v-text-field with label, placeholder and required does not get marked as invalid on blur

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#1298]
### Steps to reproduce
Setup the template ("yourProp" is empty):
```html
<v-text-field label="Label" placeholder="Holder" v-model="yourProp" required></v-text-field>
```
In runtime, set focus to the field, then remove focus.

### Versions
0.14.8

### What is expected ?
Field should be marked as invalid (`$theme.error` color), as view field and model are still empty.

### What is actually happening ?
Field behaves as if it has content.

### Reproduction Link
https://jsbin.com/quposazuha/edit?html,js,output

**Comment by johnleider** [comment]
This is changing next release in how it works. Required will no longer automatically trigger any type of validation. It will simply supply the asterisk in the label.  Here is an example of how you could trigger the validation:

```
<v-text-field
      label="No placeholder"
      v-model="model1"
      required :rules="[() => model1.length > 0 || 'Required field']"
></v-text-field>

<v-text-field
      label="With placeholder"
      placeholder="hey"
      v-model="model2"
      required
      required :rules="[() => model2.length > 0 || 'Required field']"
></v-text-field>
```
