### ISSUE TITLE
[Feature Request] Scrolling or Alt text Labels

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12988]
### Problem to solve
Sometimes the label for an input is disproportionate to the space needed for input. The options are then to make the input far larger than necessary, have the label cut off or use a tooltip just to show the label of the text field.

### Proposed solution
An optional property to make the label scroll on mouseover if it overflows the visible area of the input. Or to make it display in the alt text/prepend it to any alt text displayed.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
