### ISSUE TITLE
[Feature Request] Support for PNPM

### ISSUE THREAD

**Issue by avi12** [vuetifyjs/vuetify#12985]
### Problem to solve
Currently, as far as I know, I can only use NPM or Yarn to setup Vuetify
However, I wish to use PNPM as it's better than Yarn 1.22.x and better than NPM since it's reusing packages rather than downloading them every time
The problem is that when I try to use PNPM, I end up using [`--shamefully-flatten`](https://pnpm.js.org/en/2/faq#:~:text=shamefully-flatten), which defeats this purpose, and as a result, I fall back to Yarn 1.22.x.

### Proposed solution
Add support for PNPM.

**Comment by KaelWD** [comment]
Pretty vague issue dude
![image](https://user-images.githubusercontent.com/16421948/124442740-62718c00-ddc0-11eb-93d8-a205c340e657.png)
