### ISSUE TITLE
[Bug Report] VSlider lost its transition property

### ISSUE THREAD

**Issue by avi12** [vuetifyjs/vuetify#12984]
### Environment
**Vuetify Version:** 2.4.2
**Last working version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Edge 88.0.705.45
**OS:** Windows 10

### Steps to reproduce
Have a `<v-slider vertical :tick-labels="tickLabels"></v-slider>` and select different points.

### Expected Behavior
Smoothly transition between each point, as seen [here](https://chrome.google.com/webstore/detail/dmpbgbehgckaijcpmodinibhkdgbifif).
[The extension's source code](https://github.com/avi12/youtube-speed-control).

### Actual Behavior
Choppy experience, as seen in the Codepen example.

### Reproduction Link
<a href="https://codepen.io/avi12641/pen/abmXGoo" target="_blank">https://codepen.io/avi12641/pen/abmXGoo</a>

**Comment by KaelWD** [comment]
Caused by #12640

**Comment by avi12** [comment]
After iterating on different Vuetify versions, I discovered that the last version in which the transition is still working is [2.4.0](../releases/tag/v2.4.0)
