### ISSUE TITLE
[Documentation] vuetifyjs.com website breaks in Safari after clearing cache

### ISSUE THREAD

**Issue by deceze** [vuetifyjs/vuetify#12997]
### Environment

**Browsers:** Safari 14.0.2
**OS:** Mac OS 10.15.6

### Steps to reproduce
- Visit the main Vuetify page in Safari.
- Empty cache from Safari developer tools.
- Visit page again, see error message:

```
Safari Can't Open the Page

Safari can't open the page "https://vuetifyjs.com/". The error is:
"FetchEvent.respondWith received an error: Returned response is null." (WebKitServiceWorker: 0)
```

### Expected Behavior
Being able to visit the main website in Safari.

### Actual Behavior
Visiting the main website in Safari occasionally breaks, specifically after emptying caches.

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

### Other comments
I'd guess the issue is a service worker which doesn't handle the case of getting an empty cache response correctly. This can only be resolved by uninstalling the service worker by going into Safari settings and clearing all stored data for the site.

**Comment by Hanashi** [comment]
I have the same problem with Safari 14.0.3 (macOS 11.2.2).
I can visit the page only via private browsing mode.

**Comment by trainoasis** [comment]
> I have the same problem with Safari 14.0.3 (macOS 11.2.2).
> I can visit the page only via private browsing mode.

Exactly the same issue here.

**Comment by MajesticPotatoe** [comment]
Clearing history along side cache seems to resolve this.
![Screen Shot 2021-03-26 at 10 12 59 AM](https://user-images.githubusercontent.com/27827979/112644514-e4decd00-8e1b-11eb-8289-e403174a8d95.png)

**Comment by trainoasis** [comment]
> Clearing history along side cache seems to resolve this.
> ![Screen Shot 2021-03-26 at 10 12 59 AM](https://user-images.githubusercontent.com/27827979/112644514-e4decd00-8e1b-11eb-8289-e403174a8d95.png)

Of course it does yea; but that's still pretty bad (too much work); even worse, than opening in incognito. Should work normally. Anyone knows what the core of the issue could be?

**Comment by MajesticPotatoe** [comment]
> Of course it does yea; but that's still pretty bad (too much work); even worse, than opening in incognito. Should work normally. Anyone knows what the core of the issue could be?

Too much work is a lil subjective. eg: going into settings to enable dev tools to clear cache could also be considered too much work 😉 . Was meant as a workaround either way for the immediate future as I don't have much time at the moment to dig around for a proper built in solution, and any fix/solution would still require you to do this as the initial step (to be able to get new service worker registered and the site content). Very much so welcome any assistance on this.

After some google foo, its something related to how Safari is cacheing the `service-worker.js` which doesn't seem to be cleared when you clear cache via dev-tools (so its still in cache, even though the service worker is no longer available). But thats about as far down the rabbit hole i got.

**Comment by deceze** [comment]
The better workaround is already contained in the original post: go into settings, Privacy → Manage Website Data, and remove all data associated with that website only. That doesn't discard all your login cookies on other sites.

**Comment by dleute** [comment]
While this happens to me, I have a bigger problem in that safari will rarely pickup a new version of a site under development. It always displays a cached version.

I empty caches and then break my ability to see the vuetifyjs.com site.

The bigger concern here is I can't expect my users to empty their caches to see the new version of a vuetify site I am working on.

Is there a way to get safari to show updates? (On chrome, 1. reloading always fixes it, 2. updates during development are usually pushed to the browser instantly).

Is there something up with safari 14?

**Comment by deceze** [comment]
@dleute Sounds like that's unrelated to this issue. That's your general caching strategy you need to work on. Serve your HTML/JS/CSS files with appropriate cache HTTP headers so they're not cached indefinitely: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by dleute** [comment]
> @dleute Sounds like that's unrelated to this issue. That's your general caching strategy you need to work on. Serve your HTML/JS/CSS files with appropriate cache HTTP headers so they're not cached indefinitely: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

I am using `vue-cli-service serve --port 3000` under development. Are you saying the defaults used here aren't appropriate for Safari? But Chrome is ok?

If cache headers were wrong, wouldn't I be seeing the same problem on other browsers?

**Comment by deceze** [comment]
@dleute No, that should work fine even in Safari. Perhaps open its development tools, and ensure the "don't cache" icon is checked in the network tab. Either way, this is unrelated to this particular ticket.

**Comment by dleute** [comment]
> The better workaround is already contained in the original post: go into settings, Privacy → Manage Website Data, and remove all data associated with that website only. That doesn't discard all your login cookies on other sites.

I have been using that as well. I hadn't tried it as much on localhost. I can do that for development, I just need to make sure this isn't something that becomes a problem when "live" with safari. I can't expect users to do that.

I reported here because it seemed related to the main vuetifyjs.com problem. (same solution temporarily fixes both under safari).

**Comment by dleute** [comment]
FYI, safari does not work out of box on big sur for me. I have to clear the data constantly to get it back. I am using Chrome for development. It's like safari basically disconnects itself from updates at some unknown point.
