### ISSUE TITLE
[Bug Report] in the NUXT application v-tooltip is wrong position when in sticky or fixed section

### ISSUE THREAD

**Issue by sanjar737** [vuetifyjs/vuetify#12996]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Mac OS 11.0.1

### Steps to reproduce
1. Scroll down a little
2. Hover to flash button
3. See wrong position of tooltip message

### Expected Behavior
in the nuxt application the tooltip is positioned correctly for sticky and fixed elements.

### Actual Behavior
for fixed or sticky elements, the tooltip moves down after scrolling

### Reproduction Link
<a href="https://codepen.io/vitalypdev/pen/QWLmBLE" target="_blank">https://codepen.io/vitalypdev/pen/QWLmBLE</a>

### Other comments
After page scroll the attach property in the v-tooltip component incorrectly calculates the position of the tooltip content for sticky or fixed elements.
I found a similar problem on the stackoverflow, so I'll borrow an example from there https://stackoverflow.com/questions/57873429/vuetify-tooltip-is-wrong-position-when-in-footer-section

**Comment by KaelWD** [comment]
> Got it! This bug was fixed in v.2.0.16, as you pointed to. I just updated my vuetify from 2.0.5 to 2.0.16, and it fix my problem, without any additional coding. Thanks! – Vitalyp Sep 11 '19 at 13:57
