### ISSUE TITLE
[Bug Report] v-badge content props doesn't render falsey values

### ISSUE THREAD

**Issue by Alucard17** [vuetifyjs/vuetify#12992]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
Just add falsey values to content prop of v-badge i.e ```<v-badge :content="0"></v-badge>```

### Expected Behavior
It should render 0 as content of badge.

### Actual Behavior
it is rendering empty content.

### Reproduction Link
<a href="https://codepen.io/alucard17-the-animator/pen/OJRqqqb" target="_blank">https://codepen.io/alucard17-the-animator/pen/OJRqqqb</a>

### Other comments
Just let me know, if this is a bug I have already fixed it in my forked repo.

**Comment by MajesticPotatoe** [comment]
`false` is intended, 0 is likely not. simple userland solution is to convert content to string `:content="'0'"` / `:content="'false'"`

**Comment by nekosaur** [comment]
This is working in v3
