### ISSUE TITLE
[Bug Report] disable-keys doesn't affect VMenu hiding when Esc key is pressed

### ISSUE THREAD

**Issue by mattnathan** [vuetifyjs/vuetify#12998]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
1. Create a v-menu with disable-keys (and probably close-on-content-click=false)
2. Inside the menu place something that can receive text input (e.g. v-text-field)
3. Run, open the menu, focus the text input, tap the ESC key

### Expected Behavior
disable-keys says that "Removes all keyboard interaction", I would expect the menu to remain visible after tapping ESC

### Actual Behavior
The menu hides

### Reproduction Link
<a href="https://codepen.io/mattnathan/pen/jOMRLvv" target="_blank">https://codepen.io/mattnathan/pen/jOMRLvv</a>

### Other comments
You can work around this by capturing the ESC keydown event and stopPropagation on it, but disable-keys should work

**Comment by johnleider** [comment]
The PR is simple enough that we can keep them both open.
