### ISSUE TITLE
[Documentation] FAQ - outdated section about node-sass

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#13000]
### Environment

**Browsers:** Chrome 87.0.4280.141
**OS:** Mac OS 11.1.0

### Steps to reproduce

![Screenshot 2021-01-21 at 18 44 37](https://user-images.githubusercontent.com/17653648/105389921-bde7fd00-5c18-11eb-97f8-de279fead0a8.png)

Vuetify requires `sass`, not `node-sass`. This section should be updated.

### Expected Behavior
FAQ section should not be outdated.

### Actual Behavior
FAQ section is outdated.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#cannot-find-module-sass" target="_blank">https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#cannot-find-module-sass</a>

**Comment by MajesticPotatoe** [comment]
pretty much #12129

**Comment by Mikilll94** [comment]
@MajesticPotatoe 
Maybe it should be stated in the docs to which version of Vuetify `node-sass` was required and from which version `sass` is required?

**Comment by MajesticPotatoe** [comment]
its not about `node-sass` being required by Vuetify, its that older versions of `@vue\cli` (before 3.5.0) look for it even with `sass` installed
