### ISSUE TITLE
[Bug Report] Data Iterator Custom Footer Pagination, Filter etc ...

### ISSUE THREAD

**Issue by mattprogramming** [vuetifyjs/vuetify#13003]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
1)Make sure items per page selected is 4
2) Navigate to page 3 of 3 by clicking on the footer
3)Change "Items by Page" to 12
4) Data disappears, and the Page says "3 out of 1" 

### Expected Behavior
12 pieces of data should show up

### Actual Behavior
No data shows up 

### Reproduction Link
<a href="https://codepen.io/mattprogramming/pen/GRjamMQ" target="_blank">https://codepen.io/mattprogramming/pen/GRjamMQ</a>

### Other comments
This also happens on the actual documentation if you reproduce the same steps:
https://vuetifyjs.com/en/components/data-iterators/#filter

**Comment by nekosaur** [comment]
Change `page` to `page.sync` in v-data-iterator
