### ISSUE TITLE
[Bug Report] v-select baseline changes when empty string is selected

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#13007]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.96
**OS:** Mac OS 11.1.0

### Steps to reproduce
1. Choose empty option in select.
2. As you can see, the label is moving up.

![label_pushed](https://user-images.githubusercontent.com/17653648/105640228-34853480-5e7d-11eb-967a-6ff12c307d2a.gif)

### Expected Behavior
Label should stay in place.

### Actual Behavior
Label moves up.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/ZEpdWNY" target="_blank">https://codepen.io/mikilll94/pen/ZEpdWNY</a>

**Comment by KaelWD** [comment]
This element has no height: 
![image](https://user-images.githubusercontent.com/16421948/105670088-948ae200-5f34-11eb-89ea-5f3d90ba2f24.png)
