### ISSUE TITLE
[Bug Report] CSS class ordering differs from local to production

### ISSUE THREAD

**Issue by OneMoreRound82** [vuetifyjs/vuetify#13008]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
Build and deploy to production

### Expected Behavior
The dashboard-card class should take effect and the rendered component should have a box shadow.

### Actual Behavior
The v-sheet css takes precedence and results in zero box-shadow on the component.

### Reproduction Link
<a href="https://codesandbox.io/s/distracted-keller-m7rvf?file=/src/components/Card.vue" target="_blank">https://codesandbox.io/s/distracted-keller-m7rvf?file=/src/components/Card.vue</a>

### Other comments
The expected functionality works fine in development, but fails in production.

**Comment by KaelWD** [comment]
We can't fix this, you need to either fix the loading order somehow (don't ask me) or make the `.dashboard-card` class more specific. 

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
