### ISSUE TITLE
[Bug Report] some date picker's interface elements should be disabled when min/max props are provided

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#13018]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
create date picker with min/max

### Expected Behavior
- date/month picker - year selection should be disabled if min/max are within 1 year
- date picker - month selection should be disabled

### Actual Behavior
- year selection is enabled, but year list is empty
- feb-dec buttons are active although min/max allows only jan

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/QWGLGVm" target="_blank">https://codepen.io/jkarczm/pen/QWGLGVm</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
