### ISSUE TITLE
[Feature Request] Long v-stepper-step content takes all width, making other steps disappear

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#13029]
### Problem to solve
When any v-stepper-step within v-stepper has a content (description) that's too long, it spans towards the place of other steps, making them disappear without any compensation (either by turning into vertical setup, enforcing a minimum size of the last steps, or adding horizontal scrolling). And needless to say, when the container width is too small even for a single step to be fully displayed, some of its text disappears completely (and it even pushes the step number down). Reproduction link:
https://codepen.io/cTAlENtATI/pen/NWbWvQx

### Proposed solution
I'd suggest enforcing a minimum width per step to make the design responsive (as the text may not be known beforehand at the design time as a constant with predictable length), implicitly making the content multi-line by wrapping lines when needed. Personally I'd prefer the stepper height to adjust automatically instead of pushing against the width.

**Comment by maba4891** [comment]
This is a somehow related bug as it also affects the layout of the stepper on mobile devices:
#3546

**Comment by lioneaglesolutions** [comment]
Related to https://github.com/vuetifyjs/vuetify/issues/3546?
