### ISSUE TITLE
[Documentation] v-checkbox model is input-value, not value

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#13026]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
When using a `v-checkbox` with `@change` like
```vue
<v-checkbox :value="value" @change="(changed) => value = changed"></v-checkbox>
```
simply uncheck it after it was previously checked, and then look at the parameter that's provided by the `@change` event, which is set to the `value` data variable.
(Uncheck the second checkbox in the reproduction link.)

### Expected Behavior
The value should become true when checked and false when unchecked. Alternatively there should be any documentation about the expected behavior. Additionally, the [API documentation](https://vuetifyjs.com/en/api/v-autocomplete/#change) should most certainly document the expected behavior, along with the possible types (currently `any`) instead of an ambiguous "`Emitted when the input is changed by user interaction`".

### Actual Behavior
Uncheck the second checkbox in the reproduction link, and the value becomes null. Any strongly-typed code breaks a promise of returning a boolean.

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/dyObxzK" target="_blank">https://codepen.io/cTAlENtATI/pen/dyObxzK</a>

**Comment by jacekkarczmarczyk** [comment]
It's `:input-value`, not `:value`

**Comment by scscgit** [comment]
@jacekkarczmarczyk Thanks, it was certainly possible to avoid receiving `null` by not using `:value` directly; but I still think that the `null` shouldn't have occurred, or that the docs should reflect the reason at all, as I can't imagine any way how a new user could come to this conclusion. (Also notice the how the only relevant phrase in [model-as-boolean](https://vuetifyjs.com/en/components/checkboxes/#model-as-boolean) says `A single v-checkbox will have a boolean value as its value.`, but doesn't cover the scenario that if you put `boolean` into `value` you'll get `null`.) Or is my use-case just a niche scenario?

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/LYbYmxz?editors=1010 - this is the simplified version of your issue
I've closed the issue because i was pretty sure that you thought about `:value` being part of the `v-model` which is not true.
And although I don't quite understand the behaviour in my codepen it doesn't seem to be relevant to your problem, and if I'm wrong please explain what's the usecase of changing checkbox's value like you did in your codepen (keep in mind that this is not v-model)

**Comment by scscgit** [comment]
@jacekkarczmarczyk Yep I've only learned about the `:input-value` thanks to you, so my original use-case is solved (except covering its API docs learnability) as I can effectively consider this to be a "workaround" by removing the `:value` altogether (by assuming that I won't have to ever use it); but I'd suggest to make the contract (and types) of `@change` event more explicit, as it feels like there's a huge potential of stability issues if our projects wrongly assume that they'll always receive a boolean (at least in case when the `:value` isn't a "non-boolean", exactly like in your simplified version, which represents this root cause issue even better).

* e.g.: some large projects may keep performing a `falsey` check, and then later introduce a dependency that'll later suddenly break down once a less probable (non-tested) false input appears :)

Maybe it'd be worth documenting at least a single happy-path of using `@change` rather than `v-model`, as this stack of unexpected issues takes quite some effort to debug.

**Comment by jacekkarczmarczyk** [comment]
Ok, I'll reopen it as a documentation issue, but not really sure what should be added there, feel free to create a PR
This still maybe a core issue as imho v-model value shouldn't depend on the value of `value` prop

**Comment by scscgit** [comment]
Maybe the [`value` prop (a.k.a. "`The input’s value`")](https://vuetifyjs.com/en/api/v-checkbox/#value) could be the one documented (while mentioning its difference compared to `input-value`), as it's completely missing right now. Do you have some ideas about the preferred use-cases or examples that could illustrate it? I'm assuming that it's related to `false-value`, `true-value`, and `value-comparator`, and that it's meant to be used with custom objects with arbitrary fields.

**Comment by xwiggen** [comment]
v-simple-checkbox inside v-datatable issues Warning; failed to resolve directive: ripple (vue 2.6.11, vuetify 2.4.4)

**Comment by johnleider** [comment]
This process is different for Vue 3 (beyond the changes in Vuetify) and works as I would expect it in alpha:

```html
<template>
  <v-app>
    <div class="ma-12 pa-12">
      <v-card>
        <v-checkbox v-model="value" label="v-model" />
        <v-checkbox :model-value="value" label=":value and @change" @update:model-value="(changed) => value = changed" @change="onChange" />
        {{ value === null ? 'null' : 'not null' }}
        <br>
        {{ value === true ? 'true' : 'not true' }}
      </v-card>
    </div>
  </v-app>
</template>

<script>
  export default {
    data: () => ({

      value: false,
    }),

    methods: {
      onChange (e) {
        console.log(e)
      },
    },
  }
</script>
```
