### ISSUE TITLE
[Feature Request] v-treeview - move nodes with drag and drop

### ISSUE THREAD

**Issue by Steeve55** [vuetifyjs/vuetify#13021]
### Problem to solve
Enhance the component v-treeview

### Proposed solution
Add a parameter like "dragAndDropAllowed" and we can move a node. We can listen  an event when a node is dragged and when a node is dropped.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
