### ISSUE TITLE
[Bug Report] Strange render with v-combobox custom width with type="button" property

### ISSUE THREAD

**Issue by andron58** [vuetifyjs/vuetify#13038]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.96
**OS:** Mac OS 11.1.0

### Steps to reproduce
Use combobox, add class or style with custom component width

### Expected Behavior
Items should be located without huge margin on the right

### Actual Behavior
Items start rendering with huge margin

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2-template-forked-r6p3b" target="_blank">https://codesandbox.io/s/vuetify-2-template-forked-r6p3b</a>

**Comment by KaelWD** [comment]
Using `type="button"` makes no sense here, use a v-select if you want that behaviour.
