### ISSUE TITLE
[Feature Request] Add sizing utility classes (good to have)

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#13033]
### Problem to solve
Easily make an element as wide or as tall (relative to its parent) with our width and height utilities.

### Proposed solution
https://getbootstrap.com/docs/4.0/utilities/sizing/

Width 25%  `w-25`
Width 50% `w-50`
Width 75% `w-75`
Width 100% `w-100`

Height 25% `h-25`
Height 50% `h-50`
Height 75% `h-75`
Height 100% `h-100`

With breakpoints

w-sm-100
h-md-50

**Comment by andreyrk** [comment]
Bump! That would be pretty useful.
Wish it would also be added into 2.x 😄

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by andreyrk** [comment]
Why close it then? Just leave it open for discussion. Closing just makes it seem like it is not going to be considered at all

**Comment by KaelWD** [comment]
We have hundreds of rejected feature requests, there's no point keeping them open if it's unlikely they'll ever be implemented. I'm pushing for recommending something like https://github.com/windicss/windicss in v3 and reducing the number of utility classes we create ourselves.

**Comment by wicaksana94** [comment]
> $utilities: (
>   'width': (
>     responsive: true,
>     property: width,
>     class: w,
>     values: (
>       25: 25%,
>       50: 50%,
>       75: 75%,
>       100: 100%,
>     ),
>   ),
>   'height': (
>     responsive: true,
>     property: height,
>     class: h,
>     values: (
>       25: 25%,
>       50: 50%,
>       75: 75%,
>       100: 100%,
>     ),
>   ),
> );
> 
> @import '~vuetify/src/styles/styles.sass';

hy @mahammad-sixberries , I need to know the implementation, can you bring some examples?

**Comment by dcrystalj** [comment]
> We have hundreds of rejected feature requests, there's no point keeping them open if it's unlikely they'll ever be implemented. I'm pushing for recommending something like https://github.com/windicss/windicss in v3 and reducing the number of utility classes we create ourselves.

and windicss is deprecated. Why don't you at least mention on documentation to recommend tailwind if you don't plan to have basic features.
