### ISSUE TITLE
[Bug Report] @click.stop in v-autocomplete append template button do not work as expected

### ISSUE THREAD

**Issue by desian78** [vuetifyjs/vuetify#13048]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.96
**OS:** Linux x86_64

### Steps to reproduce
Click on the button on right area inside the autocomplete.
The select items will show up. They should not because of this little ".stop".

### Expected Behavior
By clicking the button to the right, the items menu to select items should not show up.
The button handler only should fire.

### Actual Behavior
The autocomplete menu to select items still show up when the button is clicked.

### Reproduction Link
<a href="https://codepen.io/desian/pen/YzpyEwM" target="_blank">https://codepen.io/desian/pen/YzpyEwM</a>

**Comment by gacedillo** [comment]
Running into this issue too.

**Comment by KaelWD** [comment]
The menu opens on mouseup, so you need `@mouseup.stop` too.

**Comment by bindrid** [comment]
I had to use @mousedown.stop.prevent on the button before it stopped triggering the menu
