### ISSUE TITLE
[Bug Report] Dialog and Overlay components z-index issue

### ISSUE THREAD

**Issue by Herbata-Sys** [vuetifyjs/vuetify#13041]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.104
**OS:** Windows 10

### Steps to reproduce
* Create a v-dialog component
* Override default v-dialog and it's overlay z-index in css (dialog z-index must be greater than overlay)

### Expected Behavior
Clicking on overlay causes dialog close event

### Actual Behavior
Clicking on overlay do nothing

### Reproduction Link
<a href="https://jsfiddle.net/7puag1h5/43/" target="_blank">https://jsfiddle.net/7puag1h5/43/</a>

### Other comments
z-index props for v-dialog will be very helpful too

**Comment by KaelWD** [comment]
This won't be changing in v2. Dialogs currently use the z-index of the click target to determine if they should close, so obviously this won't work properly if it's modified.
