### ISSUE TITLE
[Feature Request] Is there a way to disable v-text-field and keep appendIcon enabled?

### ISSUE THREAD

**Issue by 64J0** [vuetifyjs/vuetify#13042]
### Problem to solve
I want to implement a "copy" feature that copies the content of v-text-field while it is disabled. But as I noticed, when this component has the attribute of disabled it disables the append-icon too. Is there a recommended way to make only the input disabled?

### Proposed solution
Create a special attribute to control the disabled state of append-icon, like append-icon:disabled.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/YzpXdqN?editors=1100

**Comment by 64J0** [comment]
Amazing, thanks @jacekkarczmarczyk
