### ISSUE TITLE
[Feature Request] Deisable mobile adaptation of interface globally

### ISSUE THREAD

**Issue by MaxNvk** [vuetifyjs/vuetify#13045]
### Problem to solve
In some cases, when you make only desktop app and don't need mobile adaptation on mobile devices, you must put mobile-breakpoint="0" attribute in each component. So i think, that it will be a good feature to give access to disable mobile adaptation globally in config file to prevent iteration of attributes in templates.

### Proposed solution
Example of code below will be a logic way to disable mobile adaptation globally.

```
//  ./vuetify.config.js
export default {
  breakpoint: {
    mobile: false,
  },
}```

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by jacekkarczmarczyk** [comment]
This will be possible to do in v3 where you'll be able to globally set the default values of props (all of them, not just `mobile-breakpoint`)

See https://github.com/vuetifyjs/vuetify/issues/9677
