### ISSUE TITLE
[Bug Report] Adjacent month shows entire adjacent week and is missing week number on any month that ends on a Saturday

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#13044]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
* Use a calendar with show-weeks on
* Find a month that ends on a Saturday
  * July 2021
  * December 2022

### Expected Behavior
That it either does not show the next adjacent month when the entire row is filled in, or that the week number isn't missing.

Preferably it wouldn't show the next week at all because there is no calendar space that needs filled in.

### Actual Behavior
Shows an entire 7-day week for the next month, does not show week number

### Reproduction Link
<a href="https://codepen.io/douglasg14b/pen/VwmLNjm" target="_blank">https://codepen.io/douglasg14b/pen/VwmLNjm</a>

![image](https://user-images.githubusercontent.com/1400380/106675426-f2897c00-6569-11eb-9e43-0b13d733f156.png)

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/pull/13225
