### ISSUE TITLE
[Documentation] Provide template code examples also in pug

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#13047]
### Problem to solve
More and more folks are using pug. Also, sometimes I come across the documentation and then I just want to copy it, but I need to convert it to pug using an external tool first.

### Proposed solution
Automatically convert existing templates and provide an additional pug tab

**Comment by MajesticPotatoe** [comment]
Unfortunately this is not functionality that we are looking to implement at this time. The only addition we have the intention of adding to the current exampling interface would the addition of Typescript.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
