### ISSUE TITLE
[Feature Request] v-data-table row link

### ISSUE THREAD

**Issue by kami4ka** [vuetifyjs/vuetify#13054]
### Problem to solve
It will be very handy to be able to use all the features of the existing v-data-table (sorting, filtering, etc.),  but also be able to handle the v-data-table row as a router-link, as it allows to be opened in a new window and be treated as a link.

### Proposed solution
Implement something like @click:row, but that extends router-link for the table row.  
Please, look at https://github.com/vuetifyjs/vuetify/issues/3816 as it requests the same.

**Comment by Revadike** [comment]
What happened with this?
