### ISSUE TITLE
[Bug Report] fix(mixins/binds-attrs): options w/o extends

### ISSUE THREAD

**Issue by mcdmaster** [vuetifyjs/vuetify#13055]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 3.0.5
**Browsers:** Edge 90.0.782.0
**OS:** Windows 10

### Steps to reproduce
Build fails on Vue@3

### Expected Behavior
Build with no errors

### Actual Behavior
Vue.extend() is unavailable

### Reproduction Link
<a href="https://github.com/tokyo-metropolitan-gov/covid19/pull/5927/checks?check_run_id=1785169474" target="_blank">https://github.com/tokyo-metropolitan-gov/covid19/pull/5927/checks?check_run_id=1785169474</a>

![スクリーンショット 2021-02-05 002000](https://user-images.githubusercontent.com/10361533/106916563-ab0e1600-674a-11eb-94c9-8b788ed89891.png)

**Comment by jacekkarczmarczyk** [comment]
Vuetify 2.x doesn't work with Vue 3
https://vuetifyjs.com/en/introduction/roadmap/#v30-titan
