### ISSUE TITLE
[Bug Report] v-calendar event width not right in custom-daily type

### ISSUE THREAD

**Issue by geminiyellow** [vuetifyjs/vuetify#13059]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 3.0.5
**Browsers:** Chrome 88.0.4324.96
**OS:** Mac OS 10.15.7

### Steps to reproduce
- open the [type week](https://vuetifyjs.com/en/components/calendars/#type-week) sample code by codepend
- set `calendar` type to `custom-daily`
- set `start=2019-01-05`, `end=2019-01-10`,
- set `Thomas Birthday` as `start: '2019-01-01', end: '2019-01-25'`
- then you can see the Thomas Birthday show from 2019-01-06 ~ 2019-01-10

### Expected Behavior
birthday event will span from 2019-01-05 to 2019-01-10

### Actual Behavior
span from 2019-01-06 to 2019-01-10

### Reproduction Link
<a href="https://codepen.io/geminiyellow/pen/xxRZXYd?editors=1010" target="_blank">https://codepen.io/geminiyellow/pen/xxRZXYd?editors=1010</a>

**Comment by geminiyellow** [comment]
👌  i knew why now.

because when the v-calendar detect the event is contain or not, it will use this

https://github.com/vuetifyjs/vuetify/blob/34a37a06fd49e4c70f47b17e46eaa56716250283/packages/vuetify/src/components/VCalendar/util/events.ts#L45-L47

the event start at 0101, so the `dayIdentifier === event.startIdentifier` is false, the next, when it check `isEventOn`, it will check `firstWeekday === day.weekday` first. so, if i want get the right render, i should change the weekdays every time.

i don't got any information from the docs.

**Comment by shanwong29** [comment]
I would like to work on this issue :)

**Comment by richard-moats-tc** [comment]
I have verified that:
* this issue still exists in `v2.6.14`
* @shanwong29's fix branch rebases cleanly onto `master` 
* @shanwong29's PR does indeed fix the issue

How can we get @shanwong29's PR merged?

**Comment by NguyenNamUET** [comment]
I have verified that:

- this issue still exists in v2.7.1
