### ISSUE TITLE
[Feature Request] Add a "tooltip" property to data table headers

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#13057]
### Problem to solve
Sometimes, especially when dealing with large tables, there might be a mismatch between the table header text and the content. Instead of taking up a lot of space, I would like to use an acronym (or any other shorter form of the text) in the header and allow for a tooltip to explain more about it, if needed.

### Proposed solution
Add a new field to the header definition object, named `tooltip`, or `info`, or `description`, or anything like it, that when added, would add a tooltip to the header item, allowing for more freedom in naming the columns without having to customise headers.

**Comment by milikko** [comment]
I second this request

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
