### ISSUE TITLE
[Documentation] Broken github links on the v-icon page

### ISSUE THREAD

**Issue by movingname** [vuetifyjs/vuetify#13069]
### Environment

**Browsers:** Chrome 88.0.4324.146
**OS:** Windows 10

### Steps to reproduce
Click the github icon of an example, and it will lead to a 404 page on github. For example:
https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/icons/usage.vue

### Expected Behavior
Show the code example on github

### Actual Behavior
404

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/components/icons/" target="_blank">https://v15.vuetifyjs.com/en/components/icons/</a>

**Comment by ElijahKotyluk** [comment]
For the older versions of the documentation you can still find the same code that would be in the Github link within the template of the example.
