### ISSUE TITLE
[Feature Request] v-data-table index

### ISSUE THREAD

**Issue by wanidulf** [vuetifyjs/vuetify#13064]
### Problem to solve
It is not possible to add a fixed index to tables.
If the main purpose of a sortable table is to rank data, a fixed index on the left is a very important feature.

### Proposed solution
Add a fixed index to to the left of <v-data-table> (an index that doesn't change when sorting data) that lets rank data easily.

**Comment by blalan05** [comment]
This is really simple to do in userland: [Example](https://codepen.io/blalan05/pen/GRNmgZy?editors=101). I don't think its necessary to add into the codebase.
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
--
 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
