### ISSUE TITLE
[Bug Report] show-adjacent-months for date-picker has wrong text color

### ISSUE THREAD

**Issue by cbruchwaldnetfonds** [vuetifyjs/vuetify#13061]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
In the codepen example go a few month back to see a month with all days selected

### Expected Behavior
selected dates from prev/next months looks the same as the selected

### Actual Behavior
selected dates from prev/next months are disabled and have the primary color what may result in low contrast

### Reproduction Link
<a href="https://codepen.io/cbruchwaldnetfonds/pen/MWbKLyN" target="_blank">https://codepen.io/cbruchwaldnetfonds/pen/MWbKLyN</a>

### Other comments
It would be helpfull to have a special class for thoses dates to style.

**Workaround:**
```
::v-deep .theme--light.v-btn.v-btn--disabled.primary {
  color: #fff !important;
}
```

**Comment by schTi** [comment]
Its not only that the colors are wrong in your example, `show-adjacent-months` and `show-week` are not working very well together. Just have a look at January 2021 in your codepen. The week number of the last row is missing and so the whole row is not aligned correctly
![picker](https://user-images.githubusercontent.com/49444254/109334451-08d0e200-7861-11eb-9e05-a58eb5885859.png)
