### ISSUE TITLE
[Feature Request] Does anyone know if Vuetify is planning to create a comments component?

### ISSUE THREAD

**Issue by xueyongg** [vuetifyjs/vuetify#13079]
### Problem to solve
Allows users to create comments and handle the complexity of comments while leveraging on vuetify's tiptop components

### Proposed solution
3 parts:

1. Segment to write your new comments. You can use something like vuetify-tiptap
2. Segment to show the comments, show user's avatar/details, show time, allow upvote, indicate if its admin/author
3. Segment on replies. Allows them to indicate replies

Examples: https://news.ycombinator.com/item?id=26047342

**Comment by KaelWD** [comment]
We aren't. The requirements are too broad for a component library, but you can build your own with vuetify components. Here's one I prepared earlier:
![image](https://user-images.githubusercontent.com/16421948/107476130-5f83be00-6bc9-11eb-802f-ea809dd8d89f.png)

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
