### ISSUE TITLE
[Feature Request] v-menu nudge min-width

### ISSUE THREAD

**Issue by 64J0** [vuetifyjs/vuetify#13077]
### Problem to solve
Why the **min-width** of the **v-menu** when the prop **"auto"** is **true** needs to be added by 16?

![image](https://user-images.githubusercontent.com/50725287/107409315-ca11fc80-6aea-11eb-9faa-4a1cbd027ad3.png)

Source: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.ts

### Proposed solution
Remove this operation, maybe

**Comment by 64J0** [comment]
Also, I can't set the component max-height with this configuration, but reading the docs is said that it's possible.

```HTML
<v-select
      v-model="selectValue"
      dense
      :height="height"
      :items="items"
      :menu-props="{
        'allow-overflow': true,
        'auto': false,
        'content-class': 'select-options',
        'offset-y': true,
        'max-height': 200,
      }"
      outlined
      :placeholder="value"
      v-bind="$attrs"
 />
```

**Comment by 64J0** [comment]
Please avoid magic numbers. https://refactoring.guru/pt-br/replace-magic-number-with-symbolic-constant

**Comment by arsenyeghiazarian** [comment]
Hello, I also faced to this problem when I add "auto". Did you find why that happens ?
