### ISSUE TITLE
[Feature Request] Curved Range Slider

### ISSUE THREAD

**Issue by RBrothersBSI** [vuetifyjs/vuetify#13076]
### Problem to solve
A curved range slider provides better user experience on mobile devices. Also allows min/max values to populate in the middle of the slider, drawing more attention.

### Proposed solution
Create a curved/circular slider, allowing for min and max values to be set. For ease of integration, have max value on top and min value on bottom.

**Comment by KaelWD** [comment]
Thanks for the suggestion but this would be too complex to maintain in a generic way.
