### ISSUE TITLE
[Bug Report] VEditDialog with VAutocomplete strange behavior

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#13078]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.104
**OS:** Windows 7

### Steps to reproduce
My initial issue was that if I open a dialog, close it, open one on another item, every time the item list is updated, the field clears. While trying to reproduce that in a simplified form.

Click on the first row's iron, cancel it. Click in the next one. Attempt to type, the list will appear, you can't type more but you can choose from it, but they remain invisible in the box until you save.

### Expected Behavior
SearchString to function normally.

### Actual Behavior
SearchString gets very confused and breaks in various ways.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/BaQLLOz" target="_blank">https://codepen.io/teellcory/pen/BaQLLOz</a>

**Comment by KaelWD** [comment]
VAutocomplete resets if the items change and there's nothing set. You can work around this by adding `this.$nextTick(() => this.SearchString = val)` or using v-combobox instead. 

Related: #4000
