### ISSUE TITLE
[Bug Report] Can not use mouse scroll wheel to control the webpage's scrollbar when a `navigation drawer` is opened.

### ISSUE THREAD

**Issue by GoodManWEN** [vuetifyjs/vuetify#13072]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.150
**OS:** Windows 10

### Steps to reproduce
Needs python to startup webserver.
with python3.7 or above , 
follow the following command
```Python
cd server
pip3 install -r requirements.txt
python3 fastapi_test_server.py
```
then access the link `http://127.0.0.1:8079` , press the `buefy.png` logo on the left-top corner to open the sidebar drawer.

### Expected Behavior
I can use mouse scroll wheel to scrol the page up and down when a side drawer is opened

### Actual Behavior
However I cannot

### Reproduction Link
<a href="https://github.com/GoodManWEN/demo2" target="_blank">https://github.com/GoodManWEN/demo2</a>

**Comment by KaelWD** [comment]
Dialogs and temporary drawers both block scrolling of the main page by design.
