### ISSUE TITLE
[Bug Report] V-Select focus with tab key and arrow up/down error (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#13084]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.150
**OS:** Windows 10

### Steps to reproduce
Click in the first select to focus on it. Then press TAB key to focus on the second Select. Press Arrow Down and Arrow Up and it will show the error in the console:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.reactiveSetter [as listIndex] (vue.js:1052)
    at VueComponent.proxySetter [as listIndex] (vue.js:4630)
    at VueComponent.prevTile
```

and

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.reactiveSetter [as listIndex] (vue.js:1052)
    at VueComponent.proxySetter [as listIndex] (vue.js:4630)
    at VueComponent.nextTile
```

### Expected Behavior
Don't show errors in the console.

### Actual Behavior
It shows the error every time arrow down/up is pressed.

### Reproduction Link
<a href="https://codepen.io/marceloluis1997/pen/BaQLrEe?editors=101" target="_blank">https://codepen.io/marceloluis1997/pen/BaQLrEe?editors=101</a>

### Other comments
It only shows the error when the select items are empty and the the v-select is focused with keyboard tab key.

**Comment by KaelWD** [comment]
That's a lotta :+1:
