### ISSUE TITLE
v-text-field with type="time" does not hide empty value

### ISSUE THREAD

**Issue by VicarEscaped** [vuetifyjs/vuetify#1309]
### Steps to reproduce

1. Go to [components page](https://vuetifyjs.com/components/text-fields)
2. Scroll to section 15
3. Click on input with label "Suffix for time zone"
4. Click on cross
5. Click outside the input

### Versions

Windows 7 / Google Chrome 60.0.3112.90
### What is expected ?

Only label is shown
### What is actually happening ?

Label and empty value are shown
### Reproduction Link
![recording](https://user-images.githubusercontent.com/989394/29206918-bcdd0bc0-7e8c-11e7-85a9-89eb2fef6f6d.gif)

[Link](https://vuetifyjs.com/components/text-fields)

**Comment by jacekkarczmarczyk** [comment]
May be related to https://github.com/vuetifyjs/vuetify/issues/1258
I'll check it out

**Comment by jacekkarczmarczyk** [comment]
I can reproduce it in Edge and Chrome as they support input[type="time"] and show '--:--' when the value is empty. Same applies to date/week/month/... input. 

Desktop Firefox at the moment doesn't support date/time fields, maybe after 2-3 versions, so this field behaves like a normal "text" input (which can be detected as input.type is set to "text")

@johnleider - how about always marking date/time fields (those with proper input.type) as dirty?
