### ISSUE TITLE
[Bug Report] v-navigation-drawer permanent right add extra padding in v-main hide/how drawer adjust that padding

### ISSUE THREAD

**Issue by animeshsarkar-bct** [vuetifyjs/vuetify#13094]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.104
**OS:** Windows 10

### Steps to reproduce
First, it looks perfect then click on the information icon content got cropped. I noticed in <main> tag v-main class have style `padding: 0px 56px 0px 0px;` then after click information icon v-main style padding set tot 0

### Expected Behavior
expected no padding change if drawer open or closed

### Actual Behavior
padding changed if drawer open closed

### Reproduction Link
<a href="https://codepen.io/animeshsa-the-decoder/pen/dyOOrmW?editors=1010" target="_blank">https://codepen.io/animeshsa-the-decoder/pen/dyOOrmW?editors=1010</a>

**Comment by KaelWD** [comment]
You're only allowed **one** layout component with `app` on each side. You have two on the right so they conflict. This should be documented on https://vuetifyjs.com/en/components/application/ or https://vuetifyjs.com/en/features/layouts/

**Comment by animeshsa** [comment]
then how do I achieve this feature if this is not allowed
