### ISSUE TITLE
[Feature Request] How do I configure theme switching based on computer settings?

### ISSUE THREAD

**Issue by andrejsharapov** [vuetifyjs/vuetify#13092]
### Problem to solve
I am using vuetify.js along with nuxt.js where by default I have enabled theme switching with `$vuetify.theme`. I recently found a theme switcher in [nuxt/color-mode](https://color-mode.nuxtjs.org/#usage) and it has a switcher based on system settings: dark, ligth. **system**, and more.
How do I implement such a dependency with $vuetify.theme?

### Proposed solution
Is it possible to implement such a dependency with $vuetify.theme.system?

**Comment by KaelWD** [comment]
Duplicate of #7932
