### ISSUE TITLE
[Bug Report] v-list-item-group v-model intercepts all v-select nested components on any level

### ISSUE THREAD

**Issue by ptheofan** [vuetifyjs/vuetify#13108]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.150
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Check the first item to reveal the v-select component.
2. Select an entry in the v-select
3. Notice at the top, the model related to the v-list-item-group is updated with the value of the v-select

### Expected Behavior
v-select value should not affect activatedRulesMatrix in any way.

### Actual Behavior
selecting an option of the v-select it uses the activatedRulesMatrix as model 

### Reproduction Link
<a href="https://codesandbox.io/s/v-list-item-group-and-v-select-o53bi?file=/src/App.vue" target="_blank">https://codesandbox.io/s/v-list-item-group-and-v-select-o53bi?file=/src/App.vue</a>

### Other comments
Only VSelect appears to be causing this issue. TextField (see last item) does not.

**Comment by ptheofan** [comment]
The issue appears to be that everything within `v-list-item-group`, even VSelect components are considered a single group.
If I wrap the v-select in a `v-list-item-group` issue appears to go away.
I still consider this to be a bug since it's unwanted and undocumented behaviour as on a "top-level" I do not expect my VSelect to become part of a parent `v-list-item-group`

**Comment by apm29** [comment]
same issue, Parent VListItemGroup receive nested VSelect component's @change event and mutate by event
