### ISSUE TITLE
[Bug Report] Cant use badge on FAB

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#13100]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
Set a badge for a fixed fab

### Expected Behavior
Badge is positioned correctly

### Actual Behavior
Badge is not positioned correctly

### Reproduction Link
<a href="https://codepen.io/mrodal/pen/RwoKRKV" target="_blank">https://codepen.io/mrodal/pen/RwoKRKV</a>

**Comment by KaelWD** [comment]
- v-app is a flex element so children will be stretched, if you put it in a block context it works fine
- v-badge doesn't really work on fixed elements out of the box, you'll have to apply some css to `.v-badge` to position the fab correctly.
