### ISSUE TITLE
[Documentation] Allow searching of different locales

### ISSUE THREAD

**Issue by wsrfde** [vuetifyjs/vuetify#13105]
### Environment

**Browsers:** MetaSr undefined
**OS:** Windows 10

### Steps to reproduce
1. 打开文档主页
2. 选择语言-中文
3. 然后进行文档api搜索，搜索完成后出现的页面又切换成了英文

### Expected Behavior
搜索后页面也是中文

### Actual Behavior
搜索后页面变成了英文

### Reproduction Link
<a href="https://vuetifyjs.com/zh-Hans/components/lists/" target="_blank">https://vuetifyjs.com/zh-Hans/components/lists/</a>

**Comment by MajesticPotatoe** [comment]
Unfortunately at this time, searching is only available in English
