### ISSUE TITLE
[Bug Report] Tooltip not showing on Switch element

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#13102]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
Place a tooltip on a switch

### Expected Behavior
Tooltip works

### Actual Behavior
Tooltip doesnt work

### Reproduction Link
<a href="https://codepen.io/mrodal/pen/mdORLpQ" target="_blank">https://codepen.io/mrodal/pen/mdORLpQ</a>

**Comment by MajesticPotatoe** [comment]
duplicate #8647
workaround would be to wrap switch in div and apply on/attrs to the div
