### ISSUE TITLE
[Bug Report] TreeView active.sync bug, cant programmaticaly set active item 

### ISSUE THREAD

**Issue by nPaul** [vuetifyjs/vuetify#13106]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.150
**OS:** Linux x86_64

### Steps to reproduce
cant programmaticaly setting Active element in TreeView
in TreeView child component TreeViewNode has prop isActive
it is true if only click mouse, but if set this.active[0] = 'some id' that not work

### Expected Behavior
qwe

### Actual Behavior
qwe

### Reproduction Link
<a href="https://codepen.io/npaul/pen/jOVBWOJ?editors=1111" target="_blank">https://codepen.io/npaul/pen/jOVBWOJ?editors=1111</a>

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
