### ISSUE TITLE
[Feature Request] Touch Directive - Sensitivity

### ISSUE THREAD

**Issue by AlissonRS** [vuetifyjs/vuetify#13104]
### Problem to solve
I've been using the touch directive in my app, but some end-users have reported that the swipe sensitivity is too high, meaning that sometimes the swipe (right/left) are activated unintentionally.

The idea of this feature request is to allow developers to have more control over when the swipe should get activated.

### Proposed solution
I can think about two possible solutions. One would be to provide an extra parameter to the `v-touch` directive, allowing the developer to configure some threshold used to tell when a swipe should be activated (based on how much the app user has dragged):
```
  <div
    v-touch="{
      threshold: 50,
      left: goToPreviousMonth,
      right: goToNextMonth,
    }"
  >
```
> I don't have full knowledge over how the API detects the swipe internally, so I don't know what would be a reasonable "value" for the threshold, it could be how far the user dragged, or how long, I'm not sure how the API detects that as of now.

The second idea, would be for the API to provide a "value" as an argument to the "left/right" calls, and the developer can use that to control when to execute the desired action. Sample:
```
<div
    v-touch="{
      left: goToPreviousMonth,
      right: goToNextMonth,
    }"
  >

methods: {
  goToPreviousMonth(sensitivity) {
    if (sensitivity > 50) {
      // execute desired action
    }
  }
}
```

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
