### ISSUE TITLE
[Bug Report] v-autocomplete blur after selection before changing items causes @update:search-input infinite loop

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#13116]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 85.0
**OS:** Windows 10

### Steps to reproduce

Implement `@update:search-input` in a way that indirectly causes `items` to change, e.g. specifically to only consist of one item that equals the new search input.
1. type any search input
1. wait for it to appear as item
1. select it as item
1. change the search input
1. quickly click outside the input (blur to de-select) before it appears as a new item

### Expected Behavior
Once a selection gets de-selected due to its item no longer being available, it should stay de-selected. The search-input definitely shouldn't be spontaneously triggered by Vuetify just because the available items have changed (especially if it was already empty/null).

### Actual Behavior
* You should see the input start periodically appearing and disappearing, e.g. switching between `Input: 1 | Selection: 1` and `Input: null | Selection: 1`
* If we implemented a project where items changed reactively based on the input (unlike the illustrated 500ms delay here), this would cause the browser to hang up. This is extremely difficult to debug, and so any projects that implement items via computed property are at risk of becoming unstable.

### Reproduction Link
<a href="https://codepen.io/cTAlENtATI/pen/KKNWREp" target="_blank">https://codepen.io/cTAlENtATI/pen/KKNWREp</a>

### Other comments
* May be related to https://github.com/vuetifyjs/vuetify/issues/9489, though this issue seems different.
* Based on stack trace, the event originates in https://github.com/vuetifyjs/vuetify/blob/be8e7a77eafad8925432a4a3abf22f3b8e6f04f8/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L392 which triggers https://github.com/vuetifyjs/vuetify/blob/be8e7a77eafad8925432a4a3abf22f3b8e6f04f8/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L104.
  * (Can we start getting rid of the `$nextTick` within implementation workarounds, along with the requirement that developers have to use it so often in the similar situations to address other issues? I'm sure there are also other conflicting combinations if we already implement other reactive changes in our code using the `$nextTick`.)

**Comment by mohsend** [comment]
Hello community! we encountered the same bug in our project. 

Vuetify Version: 2.6.4
Vue Version: 2.6.11
Browsers: Chromium 100.0.4896.60 & Firefox 91.7.0esr
OS: Debian sid

In our case using `@blur` on `v-autocomplete` caused the infinite loop.

**Comment by scscgit** [comment]
Over a year has passed, and I'm still using the same workaround in production to at least make sure the value doesn't switch too often during a short time interval (as this can't avoid flip-flopping of a value) ;(
```ts
searchInputInfiniteLoopWorkaround() {
    this.$nextTick().then(() => {
      this.searchInputInfiniteLoopWorkaroundCounter = false
    })
    if (this.searchInputInfiniteLoopWorkaroundCounter) {
      return true
    }
    this.searchInputInfiniteLoopWorkaroundCounter = true
    return false
  }
```

```
@update:search-input="
            (searchInput) => {
              if (searchInputInfiniteLoopWorkaround()) {
                return
              }
              // Rest of the code
```

**Comment by mohsend** [comment]
Thanks for sharing your workaround @scscgit . Helps a lot. :pray:

**Comment by johnleider** [comment]
Closing because v2 is in maintenance mode now.
