### ISSUE TITLE
Invalid inner page padding in Safari 10

### ISSUE THREAD

**Issue by sitnin** [vuetifyjs/vuetify#1311]
### Steps to reproduce

yarn run dev

### Versions

- Safari 10 (MacOS)
- "vue": "^2.4.2",
- "vuetify": "^0.14.7",
- "vue-router": "^2.5.3",
- "vue-server-renderer": "^2.4.2",
- "vuex": "^2.3.1",
- "vuex-router-sync": "^4.1.2"

### What is expected ?

Expected as in current Chrome

![2017-08-11_15-52-35](https://user-images.githubusercontent.com/115604/29213788-6b7213a4-7ead-11e7-8859-79b0e1c1cba7.png)

### What is actually happening ?

![2017-08-11_15-52-27](https://user-images.githubusercontent.com/115604/29213793-702275b0-7ead-11e7-8f9d-a5042e9c9023.png)

### Reproduction Link

You name it )

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by sitnin** [comment]
It was made strictly from that boilerplate

**Comment by johnleider** [comment]
Any issue without a reproduction link gets closed.
