### ISSUE TITLE
[Bug Report] Incorrect aria roles assigned to v-list-item

### ISSUE THREAD

**Issue by mattgrande** [vuetifyjs/vuetify#13125]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.12
**Browsers:** Firefox 85.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Create a v-list-item within a v-list-item-group

### Expected Behavior
The aria-tags are valid

### Actual Behavior
The aria-tags are currently incorrect

### Reproduction Link
<a href="https://codepen.io/mattgrande/pen/qBqmgXo" target="_blank">https://codepen.io/mattgrande/pen/qBqmgXo</a>

### Other comments
This was discovered while running a lighthouse audit on my site.

Currently, when a `VListItem`  is in a group, we attach the role of `listitem`, and set `aria-selected` to an appropriate value.

Unfortunately, a `listitem` should not use `aria-selected` ([see here for listitem documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Listitem_role) and [here for aria-selected documentation](https://www.digitala11y.com/aria-selected-state/)).

I _think_ the right call in a situation like this is to use a role of `option` or perhaps `treeitem` (and I'm willing to make a PR to that effect), but I wanted to get some sort of agreement before doing so.

See here: https://github.com/vuetifyjs/vuetify/blob/34a37a06fd49e4c70f47b17e46eaa56716250283/packages/vuetify/src/components/VList/VListItem.ts#L142-L143

**Comment by KaelWD** [comment]
Makes sense, check how this actually behaves in NVDA though.

**Comment by mattgrande** [comment]
Will do; thanks for the prompt response!

**Comment by rudolfbyker** [comment]
Some feedback on this fix: Vue-Axe now complains about the `role="options"` again. This seems like a catch-22.
