### ISSUE TITLE
[Feature Request] Enhance option show-first-last-page, create a parameter for each button to data table component

### ISSUE THREAD

**Issue by Steeve55** [vuetifyjs/vuetify#13127]
### Problem to solve
In my case, I make a pagination server side without a counter to enhance the performance. So I know I can go to the first page (1) but I don't know the last page. So, I want only the button for the first page.

### Proposed solution
Create two new options :
show-first-page
show-last-page

**Comment by lioneaglesolutions** [comment]
@johnleider any plans for this one? Can be solved using some CSS in user-land. Not sure how many use-cases there would be for this.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
