### ISSUE TITLE
[Feature Request] Add routeable prop exact-path

### ISSUE THREAD

**Issue by J3L4cK** [vuetifyjs/vuetify#13132]
### Problem to solve
The routeable Components for example```<v-list-item>``` doesn't  match to routes with querys.
Since the version 3.5.0 of [Vue Router](https://router.vuejs.org/api/#exact-path) can this problem solved with the prop **exact-path**.

It would be nice, if the routable components get these prop too.

### Proposed solution
```
<v-list-item exact-path
```

**Comment by jacekkarczmarczyk** [comment]
You can use it now, we may need to add a prop and update docs though

**Comment by kakenbok** [comment]
'You can use it now' seems not to work at least in VBreadcrumbsItem. Here a workaround, just extends the breadcrumbs item:

```js
import VBreadcrumbsItem from 'vuetify/lib/components/VBreadcrumbs/VBreadcrumbsItem'

export default {
  mixins: [VBreadcrumbsItem],

  props: ['exactPath'],

  created () {
    // monkey patch item to enable v-routers 'exact-path' option
    const generateRouteLink = this.generateRouteLink
    this.generateRouteLink = () => {
      const link = generateRouteLink()
      link.data.props.exactPath = this.$props.exactPath || false
      return link
    }
  }
}
```

**Comment by kakenbok** [comment]
Danke!
