### ISSUE TITLE
[Bug Report] v-data-table not using column width with hide-default-header

### ISSUE THREAD

**Issue by pjnicolas** [vuetifyjs/vuetify#13148]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 81.0.4044.129
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-data-table` component with `hide-default-header` and set a width in the `headers` prop:
```
<v-data-table
  hide-default-footer
  hide-default-header
  :items="[
    { id: 1, name: 'hello' },
    { id: 2, name: 'world' },
  ]"
  :headers="[
    { text: 'Id', value: 'id' },
    { text: 'Name', value: 'name', width: 1 },
  ]"
/>
``` 

### Expected Behavior
The column with the `width` attribute should change its width.

### Actual Behavior
Nothing happens.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-forked-3fsm2?file=/src/layout.vue:402-409" target="_blank">https://codesandbox.io/s/vuetify-playground-forked-3fsm2?file=/src/layout.vue:402-409</a>

### Other comments
The `headers` prop is not only for creating an actual header but for defining the columns of the table. That's why I think this should work even if the `hide-default-header` is present. Also, I didn't find any straightforward workaround for this.

**Comment by jacekkarczmarczyk** [comment]
You can use `cellClass` as a workaround
Related to https://github.com/vuetifyjs/vuetify/issues/8474

**Comment by Elthas17** [comment]
This issue is still present, any fix in the pipeline?

**Comment by johnleider** [comment]
Closing as stale because v2 is now in maintenance mode.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Miaouf** [comment]
For anyone, like myself, who still struggle with this issue, I have found a simple workaround:

```
    .v-data-table-header {
      visibility: collapse;
    }
```

The instruction is supported by many browsers (cf [Can I use ?](https://caniuse.com/?search=visibility%3A%20collapse)) and let you determine your column width.
