### ISSUE TITLE
[Documentation] v-alert dense prop says it hides icon but doesn't

### ISSUE THREAD

**Issue by andrewmackie** [vuetifyjs/vuetify#13144]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 3.0.5
**Browsers:** Firefox 85.0
**OS:** Windows 10

### Steps to reproduce
Create a v-alert with a type and use the dense prop.

### Expected Behavior
The documents say that the dense prop hides the icon.

### Actual Behavior
The dense prop does not hide the icon.

### Reproduction Link
<a href="https://codepen.io/andrewmacke/pen/BaQwXWL" target="_blank">https://codepen.io/andrewmacke/pen/BaQwXWL</a>

**Comment by MajesticPotatoe** [comment]
Typo on prop description.
