### ISSUE TITLE
[Bug Report] When using form inside v-dialog, input field throws validation error even before user starts typing

### ISSUE THREAD

**Issue by Pritalee-Kadam** [vuetifyjs/vuetify#13146]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
1. Open the dialog by clicking on it
2. Close it without clicking on any input field
3. Open the dialog again, we can see the validation error on the input field which is auto focused

### Expected Behavior
Validation error should be seen only after user interacts with the input field

### Actual Behavior
Validation error is seen before user interacts with the input field

### Reproduction Link
<a href="https://codepen.io/Pritalee/pen/gOLXryK?editors=1011" target="_blank">https://codepen.io/Pritalee/pen/gOLXryK?editors=1011</a>

**Comment by KaelWD** [comment]
The input is focused then blurred, so it validates itself.

**Comment by KaelWD** [comment]
You probably want #6764
