### ISSUE TITLE
[code enhancement] v-tooltip directive's 'html' property

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1314]
It might be better calling it `text` or `content`, since as it is it doesn't accept HTML at all. It's counter-intuitive and mildly misleading as it is.

Another approach would be in fact accepting vanilla HTML (no components, so it's easily injectable into the DOM). This could lead to unexpected results but would allow for a certain flexibility. However, I understand this is using a CSS pseudo-element, which doesn't work like that. Would be cool though, but I understand it's a lot of work for a measly tooltip.

**Comment by myleslee** [comment]
came across the same issue today. `html` is confusing.

**Comment by paulrosen** [comment]
So, how **does** one do a nicely formatted tooltip? I'm happy to roll my own, but would rather leave as much styling to vuetify as possible.

**Comment by johnleider** [comment]
@paulrosen There will be an update to the tooltip directive coming before 1.0 release
