### ISSUE TITLE
[Bug Report] Category View - blank calendar day if categories are empty

### ISSUE THREAD

**Issue by devonik** [vuetifyjs/vuetify#13155]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
1. Define categories as empty string or empty array

### Expected Behavior
Calendar day without category header is visible (like in old vuetify version < 2.4.0)

### Actual Behavior
The calendard day is blank if categories are empty

### Reproduction Link
<a href="https://codepen.io/devonik/pen/OJbzaVZ?editors=101" target="_blank">https://codepen.io/devonik/pen/OJbzaVZ?editors=101</a>

### Other comments
In vuetify version < 2.4.0 there was a empty day visible if categories were empty

**Comment by KaelWD** [comment]
#12518
