### ISSUE TITLE
[Bug Report] Can't override variables

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13156]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
1. Run Project
2. See Result (compare with /src/@core/sass/main.scss)

variables inside above mentioned file isn't get used.

### Expected Behavior
variables should overriding vuetify's variables

### Actual Behavior
Variables aren't overriding

### Reproduction Link
<a href="https://github.com/jd-0001/vuetify-var-override-issue" target="_blank">https://github.com/jd-0001/vuetify-var-override-issue</a>

**Comment by KaelWD** [comment]
You can't just import them. vue-cli-plugin-vuetify loads variables from a specific set of files: https://vuetifyjs.com/en/features/sass-variables/#vue-cli-install

**Comment by jd-0001** [comment]
Thanks for the quick reply. As I mentioned, I have a different location than the loader. Is there any configuration I can set so it looks for the specific directory?

**Comment by KaelWD** [comment]
No, you'd have to configure webpack yourself.
