### ISSUE TITLE
[Bug Report] Regression in VSlider - it sends change events twice, if dragged.

### ISSUE THREAD

**Issue by ldantonov** [vuetifyjs/vuetify#13151]
### Environment
**Vuetify Version:** 2.4.4
**Last working version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Firefox 85.0
**OS:** Windows 10

### Steps to reproduce
Drag the slider by grabbing the thumb and release - in the console you will see the value being reported twice from the change event.
It can also be verified in Vue Dev Tools with a full project. The repeated events include mouseup, end and change.

### Expected Behavior
When the thumb is release there should only be one change event emitted.

### Actual Behavior
Two change events are emitted when releasing the thumb.

### Reproduction Link
<a href="https://codepen.io/lantonov/pen/poNpwYg" target="_blank">https://codepen.io/lantonov/pen/poNpwYg</a>

### Other comments
2.3.10 is the last version I've verified, but the change seems to be linked with a code change to VSlider.ts from Dec 2020.

**Comment by KaelWD** [comment]
#12640
