### ISSUE TITLE
[Feature Request] Missing api props documentation for src in carousel-item

### ISSUE THREAD

**Issue by copycut** [vuetifyjs/vuetify#13153]
### Problem to solve
The documentation of the Carousel component shows a `src` props that is not specified in `carousel-item` api documentation.

### Proposed solution
Add full list of usable props, like src and lazy-src or explain that is using the v-img props.

**Comment by mirexdoors** [comment]
Hello! I can take this. 

I think the best solution would be to list all props in the documentation, right?
