### ISSUE TITLE
[feature enhancement] v-tooltip visibility defaults to hidden

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1315]
~~Having visibility as a switch was an excellent improvement, just as with `v-badge`. However, I personally feel it's a bit cumbersome having to explicitly set the `visible` property to `true` when there's no real need to dynamically hiding the tooltip.~~

~~It might be easier for someone starting with vuetify to make the simple approach the working approach. Not defining visibility either way should make the tooltip visible. I can see myself several weeks ago hitting my head to the wall making it work before I found the tooltip is hidden out of the box.~~

~~As a plus, this would make the code backwards compatible IIRC.~~

~~PS: Sorry for spamming issues for v-tooltip, but I just wanted to help make it as useful as it was for me.~~

Edit: It seems it was my own code acting up. There might be a bug, but I need to dig a bit more into it. However, I was mislead by a mistake in the docs. Opening issue there right now.

**Comment by jacekkarczmarczyk** [comment]
@keystorm which version of Vuetify are you using? Current version has the default visibility set to true as you can see in the codepen

https://codepen.io/anon/pen/gxxGeW

**Comment by keystorm** [comment]
Woops, sorry.  0.14.8

I guess I overlooked my code when I briefly tested it, after seeing `false` was the default value in the docs I took it for granted. Thank you for checking, though. 

Feel free to close this.
