### ISSUE TITLE
[Bug Report] Cannot add events to calendar categories (objects)

### ISSUE THREAD

**Issue by devonik** [vuetifyjs/vuetify#13154]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
1. Define categories as array
2. add category-text property with the display string if necessary
3. Try to dynamically add events with a existing category as object

### Expected Behavior
Event will be added to the correct category

### Actual Behavior
The event is not added to the calendar category

### Reproduction Link
<a href="https://codepen.io/devonik/pen/PobEdPr?editors=101" target="_blank">https://codepen.io/devonik/pen/PobEdPr?editors=101</a>

**Comment by KaelWD** [comment]
`event.category` should be a string corresponding to `categories[category-text]`

**Comment by devonik** [comment]
Thank you. But i wanted to use the object instead of a string to have the uniqueness. 
For example if the name of the category exists more than once the events are duplicated. 
Example: https://codepen.io/devonik/pen/PobEdPr?editors=101

It would be nice to define the identifier myself as a property or anything like that.

May you could add examples to your docs in the future.

**Comment by KaelWD** [comment]
This feature was added by a community member, it needs to be updated to use `-value`/`-text` like other components have.

**Comment by devonik** [comment]
That would be great 👍 . 
If anyone needs a workaround:
- I put the handle (any identifier) into property `category-text="handle"`
- To display the category name we have to use the slot
```
<template #category="{ category }">
  <div
    class="v-calendar-category__category text-truncate ml-1"
    :title="category"
  >
    {{ category.name }}
  </div>
</template>
```
