### ISSUE TITLE
[Bug Report] Problem with overriding custom styles after build

### ISSUE THREAD

**Issue by Cordis00** [vuetifyjs/vuetify#13166]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 11.2.1

### Steps to reproduce
For example, I am overriding styles for tables .theme--light.v-data-table.v-data-table { background-color: red }. This works for development (npm run serve). But after build ( npm run build )  my own styles will be overridden by the vuetify 

### Expected Behavior
My styles will be more important

### Actual Behavior
My styles will be less important

### Reproduction Link
<a href="https://codepen.io/project/editor" target="_blank">https://codepen.io/project/editor</a>

**Comment by KaelWD** [comment]
This is a webpack bug (https://github.com/webpack/webpack/issues/7094), the workaround is to give your styles a higher specificity than ours (or use `!important`)
