### ISSUE TITLE
Allow value of type Object for radio buttons?

### ISSUE THREAD

**Issue by guanzo** [vuetifyjs/vuetify#1316]
I would like to provide an object literal as the value for the `value` attribute for the `v-radio` component. Object values work for checkboxes but not radio buttons.

  - What will it allow you to do that you can't do today?
Use Objects as the value
  - How will it make current work-arounds straightforward?
I won't be forced to change my data structure.
  - What potential bugs and edge cases does it help to avoid?
Provides more data structure flexibility for radio components.

**Comment by jacekkarczmarczyk** [comment]
fixed by https://github.com/vuetifyjs/vuetify/pull/1461?

**Comment by johnleider** [comment]
Correct, you should be able to do this now.
