### ISSUE TITLE
[Bug Report] Bottom navigation with shift not show correctly icon badge

### ISSUE THREAD

**Issue by JoseManueIbnzLora** [vuetifyjs/vuetify#13168]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 10.15.7

### Steps to reproduce
1.select another item from  bottom navigation and the element with the badge disappears.
2. To see it again, click on the empty space.

### Expected Behavior
Show the button if it has a badge

### Actual Behavior
Does not show the button if it has a badge

### Reproduction Link
<a href="https://codepen.io/joseIbnzLora/pen/zYoRzBx?editors=101" target="_blank">https://codepen.io/joseIbnzLora/pen/zYoRzBx?editors=101</a>

**Comment by ndyakov** [comment]
I am experiencing this as well.

**Comment by idegart** [comment]
As a temporary solution, you can set the class `v-icon` to `v-badge` and set position for example `left:10px`. This way `v-badge` will not disappear

https://codepen.io/idegart/pen/dyWbOZG?editors=1010

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqNUktv4jAQ/iuWT61Ekm73JWUp6l72uIe9Nj048QDeOrZlDykI8d87tkNEoRJFIkrm8T1m5mnPfztXDhvgNZ8j9E4LhEVjGJsPhRY7u0HWaRHCQ8PtAH6p7WsxqKBaDQ1nAXcaKLUGtVpjzb7/cNtfDScAam8tou0LIwa1EqisYb2VsTqs1RJTVaJp0bBB6E1MeejAHHMpqzprFr1UxVoFtH43r8ZYY3LNv9wSsShFYGPmDHkpBusVQpjA8/P4i+VCroBJiyxa1cIx1lltPXWvPIA5MYzW1V/u3HYCO4GZFHfCY0ET1MrAieypNMqNlJOVP5PGa24MCN/uPpxTLxz9/Qv4i1H9zV3vwNPb+abyaiiTTyCVnVzHPHReuRhmDLbOemQSlmKjke0zkxQoanZzyx4W7GafZdfsjh1uZ7HgEAFHED7jNKCXUP4P1tAZJoSGd4E2VbOncVd8jehCXVWdNFQpQavBlwawMq6v6IBRLXePX8v78r6SdCnHEDloQ5nAItJzYw5EqPooOo7qjDUnEvPopOGEFL+vSHiksspvDKoeCmn7pOXbzyzmJF5C6IvW29cAnlAangYy8kTFn+C6ZpcoLqAr4qOrLjwYCR78Zy2dtb2zdZa7sDau+sAPM577aPZJNH9+A6R0fSw=
