### ISSUE TITLE
[Bug Report]  first selected panel (index 0) is forgotten by  v-expansion-panels ?

### ISSUE THREAD

**Issue by sbernard31** [vuetifyjs/vuetify#13167]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Linux x86_64

### Steps to reproduce
1. Open the first and second panel.
2. click on `switch items` button

### Expected Behavior
expanded panel should be [0,1]

### Actual Behavior
but it was only [1]

### Reproduction Link
<a href="https://codepen.io/sbernard31/pen/RwoQVaP" target="_blank">https://codepen.io/sbernard31/pen/RwoQVaP</a>

### Other comments
I'm not sure but it seems the issue is only for index 0. 

Two bonus question about expansion-panels :
 - in my usage it seems very slow. is there recommendation ? like some bad practice to avoid. 
 - is there a way to remove expand animation ? (You will maybe advice that if I don't want animation I should rather used a `<v-data-iterator>` and just do the expand stuff with a simple v-if or v-show)

**Comment by johnleider** [comment]
Re-use the key so the instance re-uses the expansion panel and keeps the same intrinsic value.

https://codepen.io/johnjleider/pen/ExwaMBN

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
