### ISSUE TITLE
[Bug Report] VCalendar: wrong date for touchmove:time 

### ISSUE THREAD

**Issue by chumakov-azoft** [vuetifyjs/vuetify#13174]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
* start a touch operation in calendar times
* continue the touch operation to another day

### Expected Behavior
The value of `event.date` of the event should return the actual day (same as `mousemove` event)

### Actual Behavior
The value of `event.date` of the event returns the same day

### Reproduction Link
<a href="https://codepen.io/Dendroid/pen/abBqxbJ" target="_blank">https://codepen.io/Dendroid/pen/abBqxbJ</a>

**Comment by johnleider** [comment]
Duplicate of #12366 

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by yuwu9145** [comment]
@KaelWD As per discussion in pull request #14280, this issue should be re-opened and I will make a dedicated separat pull request for it

**Comment by yuwu9145** [comment]
Just a reminder this issue is still broken
