### ISSUE TITLE
[Bug Report] Autocomplete menu rendering performance

### ISSUE THREAD

**Issue by Glandos** [vuetifyjs/vuetify#13173]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.12
**Browsers:** Firefox 86.0
**OS:** Linux x86_64

### Steps to reproduce
- Open console
- Every 3 seconds, an item is added
- Click in the input to trigger the menu
- Click outside to close the menu

### Expected Behavior
The log "Updating {{ item }}" should not be there when the menu is closed.
Re-renders autocomplet could disable re-rendering of items when menu is not active.

### Actual Behavior
If the menu has been opened once, all items are updated when the autocomplete re-renders.

### Reproduction Link
<a href="https://codepen.io/glandos/pen/yLVvvbK?editors=1111" target="_blank">https://codepen.io/glandos/pen/yLVvvbK?editors=1111</a>

**Comment by KaelWD** [comment]
Duplicate of #6764
