### ISSUE TITLE
[Bug Report] chip group triggers change event on initial rendering

### ISSUE THREAD

**Issue by paulhaem** [vuetifyjs/vuetify#13185]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Firefox 87.0
**OS:** Windows 10

### Steps to reproduce
Watch the console output as the page loads

### Expected Behavior
No console output

### Actual Behavior
Console output

### Reproduction Link
<a href="https://codepen.io/paulhaem/pen/dyOmLNJ" target="_blank">https://codepen.io/paulhaem/pen/dyOmLNJ</a>

**Comment by KaelWD** [comment]
`mandatory` will automatically select the first item on mount if there is nothing preselected. To prevent this you should initialise the model with `0` or `[0]`
