### ISSUE TITLE
[Bug Report] v-treeview - input event emitted on state change

### ISSUE THREAD

**Issue by mariobuikhuizen** [vuetifyjs/vuetify#13181]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 11.1.0

### Steps to reproduce
Click the "CHANGE STATE" button in the codepen.

### Expected Behavior
Changing the state programmatically should not cause the input event to emit.

### Actual Behavior
Changing the state programmatically emits an  input event.

### Reproduction Link
<a href="https://codepen.io/mariobuikhuizen/pen/bGBvozr" target="_blank">https://codepen.io/mariobuikhuizen/pen/bGBvozr</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
