### ISSUE TITLE
[Bug Report] v-alert icon not aligned when v-btn placed inside, as show in example docs

### ISSUE THREAD

**Issue by someone1** [vuetifyjs/vuetify#13196]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
place a v-btn inside a v-alert with a type defined

### Expected Behavior
icon to be aligned with text and button in the v-alert as shown in example docs

### Actual Behavior
icon is aligned above the text/button

### Reproduction Link
<a href="https://codepen.io/s0me0ne1/pen/eYBKYyb?editors=101" target="_blank">https://codepen.io/s0me0ne1/pen/eYBKYyb?editors=101</a>

### Other comments
I've tried all sorts of buttons, raised, outlined, plain, etc.  and they all push the icon out of alignment, both with normal alerts and dense alerts

**Comment by someone1** [comment]
If the library doesn't intend for this to be a out-of-the-box alignment guarantee, adding `height="24"` to the button works to re-align the items. Maybe the examples in the doc can be updated to reflect that in #13195

**Comment by KaelWD** [comment]
This doesn't have anything to do with the button, resize your window so the text wraps and you'll see the same thing. I believe it's intentional, `.v-alert__icon` has `align-self: flex-start`.
