### ISSUE TITLE
[Bug Report] Virtual Scroller Renders all items when no height property is specified

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#13199]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
1. Remove height property from any example
2. Wait for it to render
3. Note the unbounded height

### Expected Behavior
It limits the size of the scroller to say the flex-container it's within.

### Actual Behavior
It grows endlessly

### Reproduction Link
<a href="https://codepen.io/douglasg14b/pen/poNKgbB?editors=101" target="_blank">https://codepen.io/douglasg14b/pen/poNKgbB?editors=101</a>

### Other comments
The docs specifically say:

> The virtual scroller displays just enough records **to fill the viewport** and uses the existing component, rehydrating it with new data.

I also was unable to find any mention of the `height` or `max-height` attribute being required for the scroller to behave.

NOTE: The example link will take some time to render, it's the docs example, with the height prop removed off.

**Why:** A scrollable area that is affected by the size of the window (ie. something that is in the main body of the layout, like a table, or list ), that in most cases isn't set to a specific height in pixels.

**Comment by KaelWD** [comment]
You still need to limit the height *somewhere*. None of the parent elements in your example have a limited height either.

**Comment by johnleider** [comment]
#18392 replaced the #17813 but forgot to mention this issue.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
