### ISSUE TITLE
[Documentation] Content Quicklinks of v-calendar - Wrong scroll position

### ISSUE THREAD

**Issue by ImpyKid** [vuetifyjs/vuetify#13202]
### Environment

**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
Click on Contents > Events

### Expected Behavior
Screen scrolls to the component events

### Actual Behavior
Screen scrolls to the property called "events"

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-calendar/#events" target="_blank">https://vuetifyjs.com/en/api/v-calendar/#events</a>

**Comment by KaelWD** [comment]
Props should be `#prop-events`, `#prop-first-interval` etc.

**Comment by mirexdoors** [comment]
Hello, mind I take this one?

**Comment by jacekkarczmarczyk** [comment]
All contrubutions are welcome
