### ISSUE TITLE
[Feature Request] v-treeview allow controlling selection of nodes

### ISSUE THREAD

**Issue by glennpierce** [vuetifyjs/vuetify#13209]
### Problem to solve
I have a treeview filled with a hierarchy of nodes. I would like to be able to control how many leaf nodes actually get selected at any one time.
If the user selects a parent I want to limit the selection to the first 5 children. If they sect a leaf if won't allow it if 5 are already selected.

### Proposed solution
Can we allow a function that the user provides that allows filtering of nodes before they are selected ?
That function could take an array of nodes ?

**Comment by KaelWD** [comment]
No, watch the model and validate it externally.

**Comment by glennpierce** [comment]
I don't see how this is a solution.
I can watch the model and limit limit the leaves to  say. However, when a user clicks the parent of the leaves I won't all the children to be removed. 
But when watching the mode of the input event I would check check the list of existing nodes.
I can determine that a user as clicked a leaf or a parent.
