### ISSUE TITLE
[Feature Request] Clickable time label for Day view

### ISSUE THREAD

**Issue by ann-aot** [vuetifyjs/vuetify#13204]
### Problem to solve
In Day view, can you make the time label clickable like event @click: time, so that we can select the time between the intervals correctly, from the time label?

### Proposed solution
make time label in Day view clickable like event @click: time

**Comment by lioneaglesolutions** [comment]
@johnleider any plans for this one? Not even sure what the request is...

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
