### ISSUE TITLE
[Feature Request] Allow form elements (like v-text-field) to always float their label

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#13203]
### Problem to solve
It is distracting to watch labels jump around on a form. It is inconsistent when there is a large form with a bunch of fields and some labels are floated and some labels are not (depending on which fields have inputs added by a user).  

It would be useful for form elements like v-text-field to be able to permanently float their labels.  Basically, the opposite of the 'single-line' prop, where the labels never float.

### Proposed solution
Create a property (for all form elements) that allows the labels to always float.

**Comment by KaelWD** [comment]
Duplicate of #12839
