### ISSUE TITLE
[Feature Request] Can you provide an option to show the Time labels in Date view on both left and right sides of the Day?

### ISSUE THREAD

**Issue by ann-aot** [vuetifyjs/vuetify#13205]
### Problem to solve
Can you provide an option to show the Time labels in Date view on both left and right sides of the Day, so that it will be easy to select a time

### Proposed solution
Give an option to show the Time label on both left and right side, now it's only on the left side

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
