### ISSUE TITLE
[Feature Request] Add an "active" slot prop to v-window-item's default slot

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#13217]
### Problem to solve
As stated in the component documentation for `v-window`:
> The `v-window` component provides the baseline functionality for transitioning content from 1 pane to another. Other components such as `v-tabs`, `v-carousel` and `v-stepper` utilize this component at their core.

However the contents of each 'pane' or `v-window-item` has no way of knowing if it is currently selected (making it visible). By default, the contents of `v-window-items` are loaded in lazily and don't unload themselves when they are no longer visible. Knowing when a 'pane' is active or inactive allows us to react to the change allowing us to unload resource intensive components, or update stale data.

### Proposed solution
Add an "active" slot prop (boolean) to `v-window-item`'s default slot. It would be good if the value of the prop changes between true and false by transition events.
- Change to `true` when `beforeEnter` is triggered.
- Change to `false` when `afterLeave` is triggered.

This way operations that are triggered when the `active` prop changes can occur in the least disruptive way possible. We wouldn't want to suddenly unload a component while we're transitioning between tabs as that would change the layout and look like a glitch.

Also, I would like to point out that this kind of asked for functionality is similar to what `v-item` and `v-item-group` provides.

Could this be added to Vuetify 3?

**Comment by KaelWD** [comment]
> allowing us to unload resource intensive components

#6764?

**Comment by MatthewAry** [comment]
@KaelWD #6764 is slightly related except that this method would allow for much more control and flexibility and provides a way to satisfy #6764. I would consider this to be the superior approach to this feature request as the implementer can choose if they want to unload their components or do something else when the `active` slot prop changes.

**Comment by MatthewAry** [comment]
I suppose this feature request could apply to `v-dialog`, `v-menu`, `v-tooltip`, `v-overlay`, 'v-expansion-panels` and other components with similar behavior.

**Comment by KaelWD** [comment]
I think I'll do #6764 by default as it's pretty simple to implement and is probably the most common scenario. This can then be added as an advanced feature to be using in conjunction with `eager` for whatever weird custom behaviour you'd want.
