### ISSUE TITLE
v-select autocomplete not working

### ISSUE THREAD

**Issue by mariolamacchia** [vuetifyjs/vuetify#1321]
### Steps to reproduce
- copy-paste the v-select autocomplete from the docs
- focus the select
- type something

### Versions

Vue 2.4.2
Vuetify 0.14.9

### What is expected ?

Autocomplete's list isn't filtered

### What is actually happening ?

Autocomplete's list should be filtered based on the input value

### Reproduction Link

https://codepen.io/mariolamacchia/pen/ZJJoRa

**Comment by mariolamacchia** [comment]
It is working on version 0.14.8, though: https://codepen.io/mariolamacchia/pen/wqqjYG

**Comment by jacekkarczmarczyk** [comment]
@mariolamacchia  works for me (in Chrome)

**Comment by stoked74** [comment]
Autocomplete is no longer functioning in my app either after updating to 14.9. Chrome latest on mac.

**Comment by smares** [comment]
I think the fix introduced a new problem, see https://codepen.io/anon/pen/zdpXQZ. As soon as you type in something, "Object doesn't support property or method 'forEach'"
