### ISSUE TITLE
[Feature Request] Change preset dynamically

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13213]
### Problem to solve
Currently, we can set the theme dynamically. This just includes changing colors.

Adding dynamically changing preset will allow changing the SASS variables as well, like changing button border-radius and almost all styles of the app.

This will help in minimizing the time it takes to update the style of any given app with just a preset and we don't have to take a look at each style. We can provide as many looks as we want to the single app. Looks cools and game changing, isn't it?

### Proposed solution
I guess, ability to define an array of preset in vuetify initialization and importing the preset styles only on demand at runtime.

**Comment by KaelWD** [comment]
Most of the sass variables can be set to custom properties, and we'll be doing this by default in v3.
