### ISSUE TITLE
[Bug Report] error  in ./node_modules/vuetify/lib/styles/main.sass Syntax Error: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by rockey2020** [vuetifyjs/vuetify#13216]
### Environment
**Vuetify Version:** 3.0.0-alpha.1
**Vue Version:** 3.0.7
**Browsers:** Chrome 88.0.4324.182
**OS:** Mac OS 11.2.2

### Steps to reproduce
.

### Expected Behavior
.

### Actual Behavior
.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                                                                                  12:26:00 AM

 error  in ./node_modules/vuetify/lib/styles/main.sass

Syntax Error: TypeError: this.getOptions is not a function

 @ ./node_modules/vuetify/lib/styles/main.sass 4:14-194 15:3-20:5 16:22-202
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.123.119:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by jacekkarczmarczyk** [comment]
Probably you've installed sass-loader 11.0 which is not compatible with webpack 4
If that's not the issue please provide a runnable reproduction (can be a codesandbox or github repo).

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
