### ISSUE TITLE
[Feature Request] Vite JS Plugin

### ISSUE THREAD

**Issue by maartenvn** [vuetifyjs/vuetify#13229]
### Problem to solve
You can use Vite with Vuetify 2/3 just as you would with vue-cli. 
There are a few downsides with that:
* There is no automatic treeshaking
* ~~Initial load in browser is very slow, due to the large amount of Sass files that are loaded in. These requests can block the main browser thread, making the tab unresponsive~~

With Vite gaining more and more popularity, as it is the most popular option for creating a Vue 3 app, better Vuetify v3 support would be great.

### Proposed solution
A Vite plugin version of vuetify/vuetify-loader with treeshaking support.

**Comment by KaelWD** [comment]
> replacing the SASS imports by a global, single import, of vuetify.min.css

These aren't equivalent, SASS variables can't be modified if precompiled CSS is loaded instead. If vite struggles loading even this many sass files then it doesn't sound fit for purpose, there are much larger projects than this using webpack just fine.

**Comment by maartenvn** [comment]
I have done some further research into why it was freezing my browser. It appears to be a problem with one of my extensions. A fresh install of Chromium doesn't have the same performance issue. Initial load still takes some time, but it is much more usable now.

**Comment by simultsop** [comment]
It quickly becomes annoying whenever you have a new component and introduce a new scoped styling have to refresh entire page manually. Of course there is webpack we're not ignoring the option.

**Comment by ungarson** [comment]
Indeed it would be very useful, right now it loads every possible component straight away.
Is there any way I can efficiently connect Vuetify 2 to Vite?

**Comment by ungarson** [comment]
@KaelWD  hi, I've noticed that it's on 3.0.0 milestone, so I wonder if there are going to be any plugins for vite with vuetify 2, or is it only for vuetify 3?

**Comment by shadow-light** [comment]
Looks like there is a [Vite plugin](https://github.com/antfu/vite-plugin-components) that does this already, with Vuetify support builtin. There's also a [Rollup plugin](https://github.com/vatson/rollup-plugin-vuetify) that may work too, since Vite uses Rollup under the hood.

**Comment by KaelWD** [comment]
https://npmjs.com/package/@vuetify/vite-plugin
