### ISSUE TITLE
[Bug Report] Vuetify combobox change event fires twice

### ISSUE THREAD

**Issue by vongrad** [vuetifyjs/vuetify#13231]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.96
**OS:** Linux x86_64

### Steps to reproduce
In the reproduction link provided, navigate options of ComboBox using arrow keys and select option by pressing tab, you can see in console that the event is called twice

### Expected Behavior
The onChange event is triggered only once

### Actual Behavior
The onChange event is triggered twice

### Reproduction Link
<a href="https://jsfiddle.net/tg8mzuw4/" target="_blank">https://jsfiddle.net/tg8mzuw4/</a>

**Comment by KaelWD** [comment]
I only see it once.

**Comment by vongrad** [comment]
That is strange, for me the event always triggers twice. This is how my console output looks like:
`"onEmployeeChange", {
  compoundName: "Test 1",
  id: "1"
}, [circular object Object]

"onEmployeeChange", "te", "te"`
Can you try to reproduce it exactly like this: Click into the ComboBox, type in 'te', then use arrows to select 'Test 1' and then press tab. You should see the output above (tested in Chromium and Firefox)

**Comment by KaelWD** [comment]
Yep that did it, I wasn't typing anything first.

**Comment by KaelWD** [comment]
Would you expect it to emit the typed value, or the highlighted item?

**Comment by vongrad** [comment]
I would expect it to emit the highlighted item, I think it should work the same as pressing enter.

**Comment by KaelWD** [comment]
Ah yeah that's what `<datalist>` does too: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
