### ISSUE TITLE
v-breadcrumbs-item :to and :href props are not functioning correctly in 14.9

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#1323]
### Steps to reproduce
use the :to or :href prop on a v-breadcrumbs-item causes the links to format improperly and or the links to not work (with href). Using the to="" prop causes the element to pickup the disabled class and using the :href prop with an object causes the link to not work properly. The url has an object reference in it. 

### Versions
vuetify 14.9
vue 2.4.2
Chrome latest

### What is expected ?
The to and href prop should pass the route to the router.

### What is actually happening ?
The disabled prop is being applied when the :to prop is used and the url's don't function when usingn the :href prop with an object.

### Reproduction Link
https://codepen.io/smitchell/pen/rwKPYr

**Comment by apb2006** [comment]
This looks broken again in 0.15.x. Try Reproduction Link https://codepen.io/smitchell/pen/rwKPYr

**Comment by apb2006** [comment]
Just spotted https://github.com/vuetifyjs/vuetify/issues/1525#issuecomment-327190602 which I guess is the answer for my "same page" links

**Comment by sanju4115** [comment]
its again not working

**Comment by jacekkarczmarczyk** [comment]
Please do not comment on old closed issues, create a new one and provide a reproduction codepen
