### ISSUE TITLE
[Feature Request] Fix conflict in import type adoption

### ISSUE THREAD

**Issue by mcdmaster** [vuetifyjs/vuetify#13233]
### Problem to solve
In the ```next``` branch, I tried ```yarn lint:fix``` operation. It recommended me to use ```import type``` clause specifically for types definition.

After that, when I tried commits locally, every commit shows errors that intend to correct me to write ```type```-less ```import``` clauses. I apparently think that this is a conflict which needs to be fixed.

### Proposed solution
IMHO, no ```import type``` will be fine unless it provides us with drastic improvements especially in web elements delivery, render and display at this time by far better than ever.

**Comment by KaelWD** [comment]
`import` for values, `import type` for types. 

https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com).

**Comment by mcdmaster** [comment]
That DID NOT intend a kind of `general` question.

Usually, even though the vendor provides resolutions for `general` requirements (or even `grand rules`) showing HOW-TO's (like for toddlers), we have been dealing with numbers of constraints which have prevented implementing `general` policy in any fashion.

In addition, although it is figured out that there is a mismatch found in this project's between release hooks to adopt the `general` policy, only a vendor's mantra is quoted against the issue poster (i.e. myself) instead of the direction for overcoming the issue that I am struggling with.

Anyway, whichsoever you team are comfortable with a user like myself, I intend to try to keep myself hanging on. Thank you anyway
