### ISSUE TITLE
[Bug Report] V-tooltip is not working properly when applied on button when using a mobile

### ISSUE THREAD

**Issue by Eygle** [vuetifyjs/vuetify#13241]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 3.0.7
**Browsers:** Google Chrome
**OS:** Android, iOS

### Steps to reproduce
You can also check it directly on the Vuetify Tooltip component page using a mobile: https://vuetifyjs.com/en/components/tooltips/

Using your mobile when you click on the buttons the tooltips never appear, except for the "Toogle" button which modify the v-tooltip model directly using `@click`.

### Expected Behavior
When clicking on a button with a tooltip we expect to see the tooltip appear even using a mobile

### Actual Behavior
When clicking on a button with a tooltip the tooltip does not appear using a mobile

### Reproduction Link
<a href="https://codepen.io/Eygle/pen/eYBQKbY" target="_blank">https://codepen.io/Eygle/pen/eYBQKbY</a>

**Comment by erthi16** [comment]
Related to #13323

**Comment by erthi16** [comment]
I've made a codepen with the workaround in #7114 and it introduces another bug if we click again on the button to close the dropdown liste... the tooltip shows on close!
for testing: https://codepen.io/-ric-thibault/pen/zYNrYrX

**Comment by erthi16** [comment]
I've used the workaround in #12175 and it adds another bug as it shows the tooltip if ones click again on the button to close the dropdown list

codepen: https://codepen.io/-ric-thibault/pen/zYNrYrX
