### ISSUE TITLE
[Feature Request] New selection-type of treeview

### ISSUE THREAD

**Issue by Ejden** [vuetifyjs/vuetify#13245]
### Problem to solve
In treeview we have two selection-type. Independent and leaf. But there's one case that can't be done with either of those two. Imagine that we have a shop category list like this:
- IT
   - Databases
   - Programming
      - Java
      - Python
- Sci-Fi

Let's say we have a book about Java. We want that book to be placed in the java category. But this means that this book should also belong to the programming and IT category. So selecting Java should also automatically select programming and IT. 
But if we have let's say a book about programming when we select programming this should only automatically select IT, without selecting java and python. 

### Proposed solution
Can you add another selection-type to treeview that will include this case of selecting items?

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
