### ISSUE TITLE
[Documentation] v-text-field API Chinese translation error

### ISSUE THREAD

**Issue by HideDu** [vuetifyjs/vuetify#13246]
### Environment

**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 10.15.7

### Steps to reproduce
Documentation -> API -> v-text-field -> Slots(插槽) 

### Expected Behavior
1. append-outer 在输入框<font color= #FF3434 >内部</font>，文字之后添加一个内容

2. prepend-inner 在输入框<font color= #FF3434 >外部</font>，前面添加一个内容

### Actual Behavior
1. append-outer 在输入框<font color= #4CC634 >外部</font>，文字之后添加一个内容

2. prepend-inner 在输入框<font color= #4CC634 >内部</font>，前面添加一个内容

### Reproduction Link
<a href="https://vuetifyjs.com/zh-Hans/api/v-text-field/#section-63d269fd" target="_blank">https://vuetifyjs.com/zh-Hans/api/v-text-field/#section-63d269fd</a>

### Other comments
red is error
green is correct

**Comment by KaelWD** [comment]
Translation updates should be submitted through crowdin: https://vuetifyjs.com/en/getting-started/contributing/#for-docs---language
