### ISSUE TITLE
[Bug Report] Custom set icons aren't rendered 

### ISSUE THREAD

**Issue by selobu** [vuetifyjs/vuetify#13253]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.72
**OS:** Windows 10

### Steps to reproduce
just watch the code pen

### Expected Behavior
Showing prepend calendar icon

### Actual Behavior
doesn't show custom prepend calendar icon

### Reproduction Link
<a href="https://codepen.io/Selobu/pen/BaQvMrw" target="_blank">https://codepen.io/Selobu/pen/BaQvMrw</a>

**Comment by nekosaur** [comment]
This seems like it could very well be an issue with the v-jsf library. Please provide a minimal reproduction of the issue without using the library to confirm that the problem is with Vuetify.

**Comment by KaelWD** [comment]
It's passing `mdi-calendar` instead of `$calendar`
