### ISSUE TITLE
[Bug Report] extension-height prop on v-app-bar is not applied when screen size is `sm`

### ISSUE THREAD

**Issue by jeannieism** [vuetifyjs/vuetify#13258]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.82
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a top bar using v-app-bar
2. Give v-app-bar a prop of "extension-height" of any value
3. Run application
4. Resize application browser window and watch as the browser hits `sm` breakpoint, the v-app-bar shrinks (presumably to 48px which is the default [https://vuetifyjs.com/en/api/v-app-bar/#props])

### Expected Behavior
That extension-height is maintained throughout all breakpoints.

### Actual Behavior
extension-height is maintained down until the breakpoints reach `sm` and `xs`.

### Reproduction Link
<a href="https://github.com/jeannieism/vuetify-topbar-issue/tree/main/vuetify-topbar-issue" target="_blank">https://github.com/jeannieism/vuetify-topbar-issue/tree/main/vuetify-topbar-issue</a>

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
