### ISSUE TITLE
[Bug Report] Cannot drag V-Slider with touch since 2.4.6

### ISSUE THREAD

**Issue by yrccondor** [vuetifyjs/vuetify#13259]
### Environment
**Vuetify Version:** 2.4.6
**Last working version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Google Chrome, Mozilla Firefox, Safari
**OS:** Windows 10, Android, iOS

### Steps to reproduce
Touch and drag the slider, the slider doesn't response. Only click works.
Dargging works fine with mouse.

### Expected Behavior
The slider moves with finger

### Actual Behavior
The slider doesn't response

### Reproduction Link
<a href="https://codepen.io/yrccondor/pen/JjbxeBE" target="_blank">https://codepen.io/yrccondor/pen/JjbxeBE</a>

**Comment by radimhornicek** [comment]
I was looking for any solution of this problem (@ 2.5.0), then I noticed it was due to vue2-touch-events package.. maybe it helps someone
