### ISSUE TITLE
[Bug Report] Checkbox inside menu is not updating value via v-model

### ISSUE THREAD

**Issue by kumold** [vuetifyjs/vuetify#13255]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 3.0.7
**Browsers:** Edge 90.0.810.1
**OS:** Windows 10

### Steps to reproduce
Click "Reset menu checkbox"

### Expected Behavior
Checkbox inside menu should be unchecked

### Actual Behavior
Checkbox stays checked

### Reproduction Link
<a href="https://codepen.io/kumold/pen/BaQMKjQ?editors=101" target="_blank">https://codepen.io/kumold/pen/BaQMKjQ?editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
`@click="item[0].checked = false"` should be `@click="items[0].checked = false"`
