### ISSUE TITLE
[Bug Report] fieldset google translate issue. Adds random strikethrough elements

### ISSUE THREAD

**Issue by Christianschrodahl** [vuetifyjs/vuetify#13256]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.1
**Browsers:** Chrome 89.0.4389.82
**OS:** Windows 10

### Steps to reproduce
Go to a page with v-text-field outlines. right click and translate from english to norwegian. the result will add </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> inside fieldset => legend element.

You can test this on vuetify website on v-text-field documentation. Codepen doesn't reproduse it right.

### Expected Behavior
Not adding these values.

### Actual Behavior
</s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> 

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/text-fields/#usage"> vuetify text fields</a>
### Other comments
Looks like it is only on outlined v-text-fields
![image](https://user-images.githubusercontent.com/26057919/110935343-974c6580-832f-11eb-87d8-ec9cd2206dd2.png)

**Comment by digital88** [comment]
As a workaround I use
`Vue.prototype.$fixChromeTranslate = function() {
    const spans = document.querySelectorAll('div.v-input__slot span')
    Array.prototype.forEach.call(spans, function(span) {
        span.classList.add('notranslate')
    })
}`

**Comment by Morwen-S** [comment]
I have the same problem in my project, when I translate it from russian to english. It is only on outlined v-text-fields, it could be connected with this issue: https://support.google.com/translate/thread/19809319/zero-width-space-%E2%80%8B-gets-weird-translation-to-german-and-french?hl=en
 
I had to shut down translation in all project, by adding `<html lang="ru" translate="no">` in index.html
![image](https://user-images.githubusercontent.com/52970386/118640481-d77e0780-b7fa-11eb-9d48-11954092b90b.png)
