### ISSUE TITLE
[Feature Request] Can v-list-group add props, distinguish it from the existing value, and only identify whether it is an active route?

### ISSUE THREAD

**Issue by yangmiao7** [vuetifyjs/vuetify#13268]
### Problem to solve
The current `value ` attribute, which means `Expands / Collapse` , also means whether to match the current route. When the group attribute matches the current route, click v-list-group. Although the `active-class` style disappears, no route jump occurs at this time. There should be another variable to control whether it is an active route and control the menu to match the route. Time style

### Proposed solution
Add another prop to indicate the active status of the route

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
