### ISSUE TITLE
[feature request] dialogs should close after pressing "esc" key

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1326]
Dialogs are not closing when user presses the "esc" key. Closing with "esc" key is so common behaviour that imho it should be the default behavior of Vuetify dialogs, even if it could be easy implemented by the dev

**Comment by johnleider** [comment]
After talking with the dev team we determined that this is something that can simply be done with @keydown.esc="model = false".

**Comment by bashilbers** [comment]
Do you have an example on how to do this? I am trying it with Vue 0.15.7 and I can't get it to work

**Comment by amritk** [comment]
I also can't get this to work 
```
<v-dialog v-model="open" width="400" @keydown.esc="open = false">
```

**Comment by mr-july** [comment]
Please provide working example or reopen the issue! Applying @keydown.esc="open = false" on v-dialog has no effect!!!

**Comment by botic** [comment]
Imho this is also an accessibility issue since dialogs should be closable with the keyboard and not requiring a pointer-like device interaction. Other frameworks like Bootstrap close modal dialogs after the user pressed ESC. I would think the other way around: devs who don't like this behaviour should prevent it.

**Comment by jacekkarczmarczyk** [comment]
Temporary (and not perfect) solution:
https://codepen.io/anon/pen/KXyVmX

**Comment by johnleider** [comment]
Adding the ability for the dev to bind keydown events on `v-dialog`, allowing them to perform any functionality they wish.

**Comment by GianPaoloBuffo** [comment]
I'm running into an issue when I have a `v-select` nested within the `v-dialog`.

If I open the select and then press `ESC` to close the select, I end up closing the dialog as well. Ideally there should be some sort of hierarchy between these events.

**Comment by Made-of-Clay** [comment]
As a usage note, bind to the `keydown` event on the dialog. It's not in the docs; I found it in the GitHub source (https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VDialog/VDialog.js#L154).

Example:
```vue
<v-dialog @keydown.esc="closeDialog"></v-dialog>
```

**Comment by f3ltron** [comment]
it work for me

**Comment by yabuking84** [comment]
<v-dialog v-model="open" width="400" @keydown.esc="open = false"> has issues when you have nested dialogs and each has <v-dialog v-model="open" width="400" @keydown.esc="open = false">. It closes all opened dialog boxes. 

How do you make it that it will only close the current dialog box shown?

**Comment by Made-of-Clay** [comment]
@yabuking84 I would say don't nest the dialogs. They can be side-by-side in the markup. In the case the dialog is the root element of some custom component, just wrap the two dialogs in a `div`.

I would recommend this even if it wasn't giving you issues. Nested dialogs semantically seem weird to me (even though that's *kind* of the behavior for the user).

**Comment by sense-it-gmbh** [comment]
@johnleider would it be possible to also fire `keyup` and `keypress` events along with `keydown` event? It seems a little bit odd, that only one of the well known Keyboard-Events get fired.

**Comment by josedanielcruzc** [comment]
@yabuking84 you should set a different v-model for each dialog.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
