### ISSUE TITLE
[Bug Report] Odd Scrollbar/ Appbar behavior

### ISSUE THREAD

**Issue by RoboVij** [vuetifyjs/vuetify#13269]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.82
**OS:** Windows 10

### Steps to reproduce
Check the sandbox

### Expected Behavior
Proper scrollbar appbar functioning

### Actual Behavior
When the scrollbar in the Home tab is scrolled fast enough, the scrollbar reaches bottom and then it's height gradually increases (for approx. 500ms), and in parallel to it the appbar height also changes. In my app I use some icons in a data-table (not shown in sandbox example), when the page is scrolled they dance up and down continuously as long as the scrollbar adjusts its height.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-odd-scrollbar-appbar-f8neo" target="_blank">https://codesandbox.io/s/vuetify-odd-scrollbar-appbar-f8neo</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
