### ISSUE TITLE
[Bug Report] v-flex props

### ISSUE THREAD

**Issue by mohammadreza-ae** [vuetifyjs/vuetify#13266]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.82
**OS:** Windows 10

### Steps to reproduce
add props to v-flex tag (For example; add test-tag)
<v-flex test-tag="title"></v-flex>

### Expected Behavior
<div class="flex" test-tag="title"></div>

### Actual Behavior
<div class="flex test-tag"></div>

### Reproduction Link
<a href="https://codepen.io/mohammadreza-ae/pen/xxRBjMW?editors=1010" target="_blank">https://codepen.io/mohammadreza-ae/pen/xxRBjMW?editors=1010</a>

**Comment by KaelWD** [comment]
- only `data-` attributes are passed through
 - v-layout and v-flex are deprecated, use v-row and v-col which don't do this
