### ISSUE TITLE
[Bug Report] v-show does not correctly perform display:none

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#13273]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.82
**OS:** Linux x86_64

### Steps to reproduce
v-show and v-if do not behave the same in regards to blank space shown on the display.

For example, let's say I have two v-rows in a v-container. If the first v-row is hidden via v-show there is extra padding and the second v-row is not forced to the very top of the container. If I use v-if instead, that extra padding is properly removed.

Codepen is here:
https://codepen.io/uglyhobbitfeet/pen/QWGPrMX

You can clearly see that there is tons of space between the word 'COL 2' and the yellow border above it.

### Expected Behavior
v-show behaves like v-if in regards to v-row layout (aka The row should completely disappear)

### Actual Behavior
v-show does not behave like v-if and there is additional padding that can't be removed

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/QWGPrMX" target="_blank">https://codepen.io/uglyhobbitfeet/pen/QWGPrMX</a>

**Comment by nekosaur** [comment]
Seems to be caused by this https://github.com/vuetifyjs/vuetify/commit/f33d0c1356c5eb3a685c86f754bdf85c5dd706d0 @KaelWD

**Comment by KaelWD** [comment]
There's no way to detect that, just use v-if.

**Comment by UglyHobbitFeet** [comment]
The issue is that v-if rebuilds the content (which I don't want because
it's a lot of calls, refreshing of large data etc). v-show renders it once
and only shows it if necessary.

**Comment by UglyHobbitFeet** [comment]
Unfortunately that doesn't seem to work in my situation. When I wrap the
v-row in a keep-alive, it still completely re-renders. As a basic example,
I can put a console statement in the created section of a component that is
inside the v-row/v-col and it always fires when the v-if is toggled. As a
more complex example I can watch my data getting re-pulled/re-populated

**Comment by KaelWD** [comment]
You'd have to use a workaround like `:class="{ 'mt-n3': !showMe }"` on the second element then.

**Comment by UglyHobbitFeet** [comment]
Unfortunately that also doesn't work.  The only thing that visually aligns
it correctly is v-if which I don't want to use b/c of the reasons already
mentioned

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/PobgdVL?editors=1010

**Comment by UglyHobbitFeet** [comment]
Sorry, I put it on the first object and not the second. Yes, this seems to
fix it, thanks!
