### ISSUE TITLE
[Bug Report] Use carousel and slider at the same time on your phone

### ISSUE THREAD

**Issue by ouhuang** [vuetifyjs/vuetify#13279]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 89.0.4389.82
**OS:** Mac OS 11.2.3

### Steps to reproduce
On the mobile phone, if you want to use the carousel and the slider at the same time, adding @touchmove.stop @mousemove.stop to the parent node will cause the component to fail

### Expected Behavior
In the carousel, sliding the slider will not trigger the carousel

### Actual Behavior
Sliding the slider still triggers the carousel, can the app property of the slider be set to bind itself

### Reproduction Link
<a href="https://codepen.io/ouhuang/pen/JjbqRKK" target="_blank">https://codepen.io/ouhuang/pen/JjbqRKK</a>

### Other comments
You can add a slider to cancel the event bubbling property of touchmove and mousemove when sliding

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
