### ISSUE TITLE
[Bug Report] Vertical tabs on mobile are hide the content

### ISSUE THREAD

**Issue by vlacko0930** [vuetifyjs/vuetify#13276]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Open with mobilephone

### Expected Behavior
Hide the tabs or create don't vertical tabs

### Actual Behavior
Hide the content of tabs

![vertical tab bug](https://user-images.githubusercontent.com/34010558/111346699-c429b100-867e-11eb-88dc-a0f9c09d2d06.jpg)

### Reproduction Link
<a href="https://codepen.io/vlacko0390/pen/mdOgQBO" target="_blank">https://codepen.io/vlacko0390/pen/mdOgQBO</a>

**Comment by KaelWD** [comment]
You should do this yourself with the [breakpoint service](https://vuetifyjs.com/en/features/breakpoints/#breakpoint-service) or [display classes](https://vuetifyjs.com/en/styles/display/).
