### ISSUE TITLE
[Bug Report] v-expansion-panel-header font-size is 15px and violates material design specifications for typography

### ISSUE THREAD

**Issue by KevinKreps** [vuetifyjs/vuetify#13289]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.2.1
**Browsers:** Chrome 89.0.4389.82
**OS:** Windows 10

### Steps to reproduce
Check font-size in inspector of v-expansion-panel-header in example

### Expected Behavior
font-size: 16px
As defined by material design typography https://material.io/design/typography/the-type-system.html#type-scale

### Actual Behavior
font-size: 15px

### Reproduction Link
<a href="https://jsfiddle.net/" target="_blank">https://jsfiddle.net/</a>
<a href="https://vuetifyjs.com/en/components/expansion-panels/#usage" target="_blank">https://vuetifyjs.com/en/components/expansion-panels/#usage</a>

### Other comments
Just check it in the documentation: https://vuetifyjs.com/en/components/expansion-panels/#usage
No JsFiddle or whatever necessary.

**Comment by johnleider** [comment]
MD2 has no specification for expansion panels. The only available one is from MD1, which is 15px.

![image](https://user-images.githubusercontent.com/9064066/125873379-c5dbafbf-67b9-4e5b-b2ea-bd67c4d967a0.png)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
