### ISSUE TITLE
[Bug Report] navigation-drawer model set triggered twice

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#13287]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
1. Open [Codepen](https://codepen.io/maxim_mazurok/pen/Pobvxdp); or clone, build, and start [repo](https://github.com/Maxim-Mazurok/vuetify-drawer-issue) (same code)
2. Open Dev Tools console and clear it
3. Click "Open Menu" icon in the top left corner of the webpage
4. You'll see something like this in console:
```
set
set trace
...
click @ VM32:3
...
set
set trace
...
isActive @ VNavigationDrawer.ts:248
...
```
Confirming that `set` has been called twice per one "open menu" operation.

### Expected Behavior
`set` should only be called/triggered once, when I click on the button. `set` from the second trace, from within the drawer is redundant.

### Actual Behavior
`set` is called twice:
1. From click on `v-app-bar-nav-icon`
2. From `v-navigation-drawer` due to updated `this.isActive` which is watched in this component

### Reproduction Link
<a href="https://codepen.io/maxim_mazurok/pen/Pobvxdp" target="_blank">https://codepen.io/maxim_mazurok/pen/Pobvxdp</a>

### Other comments
Note: Vue Version in my GitHub project is `2.6.12`, but I couldn't select it from the dropdown on `issues.vuetifyjs.com`.

**Comment by hubert17** [comment]
I have similar issue. 
https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack/blob/master/src/app.js 

Site: https://hubert17.github.io/GabsVuetifyNoCLINodeWebpack/

**Comment by simonmaass** [comment]
i can confirm this issue!
