### ISSUE TITLE
[Feature Request] add light prop for v-btn comonent

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#13282]
### Problem to solve
add new option: `light` to `v-btn`

### Proposed solution
by default: it'll appear like `text` option but with hover
when hovering button it'll appear like normal button

**Comment by KaelWD** [comment]
`light` is already used for theming. You should add your own css if you want this.

**Comment by KareemDa** [comment]
> `light` is already used for theming. You should add your own CSS if you want this.

thank you for answering. `light` is an example prop name, name doesn't matter, you can name it as you want. 
But the idea is to make a button with a light background (the same appearance as when hovering on light button)
then when hovering over it, it changes to appear as normal button

**Comment by KaelWD** [comment]
I don't think this is something we need. You can already implement it yourself with CSS.
