### ISSUE TITLE
[Feature Request] Add sort and group to header.<name> slot

### ISSUE THREAD

**Issue by NicoAiko** [vuetifyjs/vuetify#13299]
### Problem to solve
Full customization of a specific column head.
e.g. when building a menu for the header having access to these functions would be good

### Proposed solution
Add sort and group function to its slot properties

**Comment by lioneaglesolutions** [comment]
@johnleider another stale issue here for Data Table. I'd think you can access `sortBy` and `groupBy` by binding to `options` for the table anyway.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
