### ISSUE TITLE
[Bug Report] v-app-bar hide-on-scroll prop hides v-system-bar

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13293]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
Just scroll the content.

### Expected Behavior
v-app-bar should get hidden instead of v-system-bar

### Actual Behavior
system bar got hidden instead of v-app-bar

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/eYBwYvK?editors=101" target="_blank">https://codepen.io/jd-0001/pen/eYBwYvK?editors=101</a>

**Comment by KaelWD** [comment]
If you set a higher z-index on v-app-bar it works as expected.
