### ISSUE TITLE
[Bug Report] v-expansion-panel-header border-radius looks weird when applying color

### ISSUE THREAD

**Issue by kekhuay** [vuetifyjs/vuetify#13308]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Mac OS 11.1.0

### Steps to reproduce
applying color to v-expansion-panel-header

### Expected Behavior
border-bottom-left-radius and border-bottom-right-radius should work as before applying color

### Actual Behavior
border-bottom-left-radius and border-bottom-right-radius does not work as expected

### Reproduction Link
<a href="https://codepen.io/kekhuay/pen/KKaPvYG" target="_blank">https://codepen.io/kekhuay/pen/KKaPvYG</a>

**Comment by johnleider** [comment]
resolved by #14014

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
