### ISSUE TITLE
[Bug Report] Can't provide custom component with v-list-item to select item slot

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#13305]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
1. Open first select
2. Open second select

### Expected Behavior
They have same look and html layout.

### Actual Behavior
In first select every v-list-item is wrapped into yet another v-list-item. That's because method needsTile in VSelectList doesn't support custom components in slot (https://github.com/vuetifyjs/vuetify/blob/61839f9e63c2e082c0200581fd05d2ee97a5103a/packages/vuetify/src/components/VSelect/VSelectList.ts#L216:L220)

### Reproduction Link
<a href="https://codepen.io/djaler/pen/qBRWEpB" target="_blank">https://codepen.io/djaler/pen/qBRWEpB</a>

**Comment by KaelWD** [comment]
The only way to support this is to always assume the root element of the slot is a list item, never automatically generating one. That's probably more palatable in Vue 3 now that we can pass everything required with just `v-bind="props"`

**Comment by KaelWD** [comment]
As promised, v3 does not render a list item itself if the slot is used, the default implementation is just
```html
<v-select>
  <template #item="{ props }">
    <v-list-item v-bind="props" />
  </template>
</v-select>
```
