### ISSUE TITLE
[Bug Report][2.4.7] Navigation Drawer - expand-on-hover, mini-variant and v-main width

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13309]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
1. Hover over navigation drawer
2. Click on plus icon to expand navigation drawer (Working as expected)
3. Click again on minus icon to collapse it (make it mini and enable expand on hover - Main content should update according to navigation drawer width)

### Expected Behavior
When we click on minus icon. Navigation menu should collapse and v-main should get more width as navigation have less width.

Also when navigation drawer is collapsed it should have expand on hover functionality.

In short, when navigation drawer is collapsed it can be viewd as full on hover. And width of v-main should update according to width of navigation drawer except navigation drawer is mini and user hovers it for temporary view.

### Actual Behavior
v-main is not adapting remaining space when we collapse the navigation drawer again.

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/JjEPRqY?editors=101" target="_blank">https://codepen.io/jd-0001/pen/JjEPRqY?editors=101</a>

### Other comments
Expected behavior: https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/demo-1/dashboard/analytics

Check pinning the navigation drawer and content area width according to width of navigation drawer.

**Comment by panteparak** [comment]
Any Updates on this? I'm waiting for this fix too.

**Comment by MisterIsaak** [comment]
Also waiting to see this fixed or a workaround.

**Comment by changemyminds** [comment]
Just add key value and it will work fine. see https://codepen.io/changemyminds/pen/MWVOgJV?editors=101

This bugs I think is vue redner issue, see [can-you-force-vue-js-to-reload-re-render](https://stackoverflow.com/questions/32106155/can-you-force-vue-js-to-reload-re-render/54367510#54367510)

```
<v-navigation-drawer
  v-model="drawer"
  :mini-variant="mini"
  :expand-on-hover="mini"
  :key="mini"                   
  app
>
```
