### ISSUE TITLE
[Bug Report] Custom/Default filters don't correctly work together on a  v-table

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#13317]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 3.0.7
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
I would like to be able to search across all columns using a single v-textfield.  I would also like to create a custom filter on a particular column.  When I create a custom filter, I can no longer search across all columns from a single v-textfield.

1. Go to the codepen link shown in this ticket
2. Type the word 'Honey' into the search bar.  No results will be found because the custom filter in the calories column prevented it.
3. Comment out the custom filter in the calories column
4. Type the word 'Honey' into the search bar. It will find the row/column that contains it 

Similarly, it looks like the custom filter competes with the default filters. 
1. Go to the codepen link shown in this ticket
2. Make sure the custom filter in the calories column is uncommented
2. Type the word '408' into the search bar.  No results will be displayed in the table even though the console output shows that the calories filter is returning true for that column  

### Expected Behavior
That custom filters should only apply to the columns that they are written for and should not block other columns from returning matching searches.

### Actual Behavior
The custom filters are preventing how searching across columns works.

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/rNjVgJQ?editors=1010" target="_blank">https://codepen.io/uglyhobbitfeet/pen/rNjVgJQ?editors=1010</a>

### Note
Note that this is a simplistic example. One may have a table with 20 columns and various custom filters.

**Comment by lioneaglesolutions** [comment]
The new data table in V3 resolves this issue by giving you the power to override the whole search and implement as you wish - example below;

https://play.vuetifyjs.com/#eNqlVW1P2zAQ/itWpIlWahJa2BBZQSDGpEloQ0P7gCgf3OTaejh2Zl8KDPW/75yXNkmpQFr6oZd7znfPveR89+KdZ1mwzMGLvDFCmkmOcDpRjI2XfsKR+8inEpyCsSjOLerUnwmJYE4mXilMvApeAE/AWAIqaY0Icu30CVgLBjeABW7iBSGlUOtjya2zBwlLjkIrf1hDzpW/5DIHwhVPoQQKzsS6zoEtfSs1RqizCipSQnhC4g8yqZWMLFOdgNwi4R7JpwVyUyCs9+v6+vInuzi/uWQ/vl/d9pu2NemM+4cb/ek4bIateYbtYpPNptqkauFjGxuRYWEJT5k2yBKY8VwieyndubMR6/XZySnrVTrGynQitrc3qFUxl9oIsC1l3ZWI3W2yWXtxj6szHflq9F9Q7FbPc4Ob823Hw4/HLWTGMWKfgv2OuZmS7eiwpc2MRhAqYocdc2E0afeGH5pBVw35NbbfYmCxAZ4yy1XyKOLFLsqjg6NtysevU+6YNigf/D/lS5ohYXbS/DTapjncVdo2nTXPrnnF82gHz/tKWvUrIdZpliMk0SaB6mt389dIygDmRjVHqpMzYyhQurS/lAPIesP9/TmNrVkKNe+3y8AYl2LuqFrk3emjWaevwn07EVVFWuigD/BMB12R2+ea/djJ7qJqwC4+oJIuVMarO7c75n0t1sr6PwVc6ITauOZU7lrWK1bfgP3JwTwPim3YqnqsldUSAqnnvZemLRs421V/oiZY/qoGFUYB6hs0VPVen8Qr/QjmglugN6FimdOG6BVe2mD/8+v8V26BVUvLG3hSqAcb/LZa0S1TcJ14saVLYL1w6MZAzGwUhnGiyJLWsViaQAGGKktDup9QzJ7PDoJRMAoTYbFW+bSgbVA4c56onisKKFK3JP2UZ52oJVBErmo28ciTe3+DwhmZhSZXKFLwE50WXA6PSjINfQA29adGP9IUk5eJVxWmiOMYvyPWW+lSiC3XoftqwPiGphGMu5Tfl1LnWCutDraVWtXqlbcaeOU5qn1B2rv/B1uCa6k=

Closing as resolved in V3
