### ISSUE TITLE
[Bug Report] [Documentation] Navigation, code snippets, and general use are all broken on the desktop documentation on chrome. 

### ISSUE THREAD

**Issue by ImmaZoni** [vuetifyjs/vuetify#13312]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 3.0.7
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
I cannot click the v-btn to close the vueschool banner, just no response.

Code previews are not displaying as shown in screenshot.

Looking into the console on chrome shows this error
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS vue-router.esm.js:2208 Error: Loading CSS chunk layout-locale-index-vue failed. (/css/layout-locale-index-vue.bcc0636b.css) at HTMLLinkElement.o.<computed>.o.<computed>.n.<computed>.t.push.o.<computed>.p.onerror (bootstrap:129)

### Expected Behavior
Readability

### Actual Behavior
Non-Readability. 

### Reproduction Link
<a href="https://codepen.io/kematzy/pen/NOT-A-VALID-REPRODUCTION-LINK-DOCUMENTATION-BASED" target="_blank">https://codepen.io/kematzy/pen/NOT-A-VALID-REPRODUCTION-LINK-DOCUMENTATION-BASED</a>

**Comment by KaelWD** [comment]
"It's broekn" isn't a very helpful bug report.

**Comment by ImmaZoni** [comment]
> "It's broekn" isn't a very helpful bug report.
My bad, was in a hurry. 
Upon further inspection, I am not getting the nav menu at all, unless I inspect element, or visit on mobile version. If i close the inspection window the nav menu disappears. 

I cannot click the v-btn to close the vueschool banner, just no response.

Code previews are not displaying as shown in screenshot. 

Looking into the console on chrome shows this error
 `Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
vue-router.esm.js:2208 Error: Loading CSS chunk layout-locale-index-vue failed.
(/css/layout-locale-index-vue.bcc0636b.css)
    at HTMLLinkElement.o.<computed>.o.<computed>.n.<computed>.t.push.o.<computed>.p.onerror (bootstrap:129)`

**Comment by jacekkarczmarczyk** [comment]
> as shown in screenshot

You forgot to add a screenshot
Also does this happen also in incognito mode?

**Comment by ImmaZoni** [comment]
Incognito mode works perfectly


<img width="944" alt="Vuetify-Doc-Error1" src="https://user-images.githubusercontent.com/31865152/112193083-c4690580-8bc4-11eb-9ec2-d463729ea115.png">
