### ISSUE TITLE
[Bug Report] In treeview, the parent value is not selected

### ISSUE THREAD

**Issue by Rasool-deldar** [vuetifyjs/vuetify#13328]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.6
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
I made a proverb using Knox and composition-api to display the content of an item when it clicks on one of the items, but this feature only works on children without children.

### Expected Behavior
I want to be able to display content like children when I click on the father, but in the example I put the link, you only see that the children can be selected and the content is displayed on the father. When you click, the content is not displayed. Please, this is a problem. Solve

### Actual Behavior
The ability to be selected is only available on the child and the child can show the content, but the father does not have such a capability.

### Reproduction Link
<a href="https://codesandbox.io/s/sad-pine-19fn0?file=/pages/index.vue:4169-4239" target="_blank">https://codesandbox.io/s/sad-pine-19fn0?file=/pages/index.vue:4169-4239</a>

### Other comments
Thank you very much if you fix this problem.

**Comment by KaelWD** [comment]
Parent nodes will be selected if you don't use `open-on-click`

**Comment by Rasool-deldar** [comment]
> Parent nodes will be selected if you don't use `open-on-click`

Thank you so much for your help
