### ISSUE TITLE
[Bug Report] Don't render treeview prepend slot if it's empty

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#13320]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
1. Open [codepen](https://codepen.io/maxim_mazurok/pen/GRrpdRG)
1. Observe that both treeview-node items have the same indentation, even though the second one has an empty prepend slot.

### Expected Behavior
I should be able to remove prepend slot for some items completely as if I added this css:
```css
.v-treeview-node__prepend:empty {
    display: none;
}
```

### Actual Behavior
Even if I return `null` or `undefined` in my JSX template using `scopedSlots`, the "prepend" slot still gets rendered creating an unwanted indentation.

### Reproduction Link
<a href="https://codepen.io/maxim_mazurok/pen/GRrpdRG" target="_blank">https://codepen.io/maxim_mazurok/pen/GRrpdRG</a>

### Other comments
I think that it should not add slot if prepend returns null or undefined.
My JSX example:
```jsx
<VTreeview
  // ...
  scopedSlots={{
    prepend: ({ item, open }) =>
      (!item.file && (
        <VIcon>{open ? mdiFolderOpen : mdiFolder}</VIcon>
      )) ||
      null,
  }}
/>
```

**Comment by Maxim-Mazurok** [comment]
Potential solution:
```jsx
<VTreeview
  //...
  scopedSlots={{
    label: ({ item, open }) => (
      <div class="d-flex">
        {!item.file && (
          <VIcon class="mr-1">
            {open ? mdiFolderOpen : mdiFolder}
          </VIcon>
        )}
        {item.name}
      </div>
    ),
  }}
/>
```

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

As you have mentioned, adding 
```css
.v-treeview-node__prepend:empty {
    display: none;
}
```
will hide the slot.

**Comment by Maxim-Mazurok** [comment]
I think using internal classes isn't a good practice, so would be great to see this option in the library.
