### ISSUE TITLE
v-toolbar-side-icon doesn't work with hidden-sm-and-up class and @click.native.stop does not work anymore

### ISSUE THREAD

**Issue by JerryCBH** [vuetifyjs/vuetify#1332]
### Steps to reproduce
When using v-toolbar-side-icon with hidden-sm-and-up class - icon does not get hidden when screen size is sm.
@click.native.stop doesn't work as well. @click.stop works.

### Versions
0.14.10

### What is expected ?
hidden-sm-and-up work with v-toolbar-side-icon

### What is actually happening ?
Not working

### Reproduction Link
https://codepen.io/anon/pen/PKKXYL

**Comment by nekosaur** [comment]
You don't need the `.native` modifier anymore thanks to a recent Vue update

**Comment by JerryCBH** [comment]
Thank you

**Comment by lyquocnam** [comment]
same here, is this fixed ?

**Comment by nekosaur** [comment]
It has not been released yet.

**Comment by bharathvaj1995** [comment]
When it will be fixed?

**Comment by EliCDavis** [comment]
since `v-toolbar-side-icon` is just eating the class, you can wrap `v-toolbar-side-icon` in a `span` and apply the class to the span instead to get around this bug atm.

**Comment by steven-ferrer** [comment]
wrapping the `v-toolbar-side-icon` with span worked for me.

`      <span class="hidden-sm-and-up">
        <v-toolbar-side-icon>
        </v-toolbar-side-icon>
      </span>`

**Comment by brynearsenal** [comment]
the <span> trick worked! thanks.
