### ISSUE TITLE
[Feature Request] Be able to emit mouseover event on v-data-table row without having to use the body slot and rewriting the entire row

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#13332]
### Problem to solve
I am trying to get the mouseover event on every v-data-table row, hover it's just possible using the 
`<template v-slot:body="{ items }">` and writing the entire `<tr>` and `<td>` elements, like this:

```
<template v-slot:body="{ items }">
   <tbody>
      <tr
        v-for="item in items"
        :key="item.id"
        @mouseover="mouseoverRow(item)"
        @mouseleave="mouseleaveRow(item)"
      >
```

I want this so I can position a menu (like gmail row hover button menu) when I hover on each `<tr>` element inside `v-data-table`.

### Proposed solution
Add two events on `v-data-table` component:

```
<v-data-table
  @mouseover:row="mouseOverRow(item, element)"
  @mouseleave:row="mouseLeaveRow(item, element)"
/>
```

Both events with 2 params: The item and the `<tr>` element reference.

**Comment by JonathanDn** [comment]
Is this feature in the works currently?

**Comment by devStr0ke** [comment]
I wish there was such a feature.

**Comment by RyanQ96** [comment]
I figure out one way to add this mouse event in vDataTable.js file 
`return this.$createElement(this.isMobile ? MobileRow : Row, {
        key: getObjectValueByPath(item, this.itemKey),
        class: mergeClasses({ ...classes,
          'v-data-table__selected': data.isSelected
        }, getPropertyFromItem(item, this.itemClass)),
        props: {
          headers: this.computedHeaders,
          hideDefaultHeader: this.hideDefaultHeader,
          index,
          item,
          rtl: this.$vuetify.rtl
        },
        scopedSlots,
        on: {
          // TODO: for click, the first argument should be the event, and the second argument should be data,
          // but this is a breaking change so it's for v3
          click: () => this.$emit('click:row', item, data),
          contextmenu: event => this.$emit('contextmenu:row', event, data),
          dblclick: event => this.$emit('dblclick:row', event, data), 
          mouseover: () => this.$emit('mouseover:row', item, data)
        }
      });`
