### ISSUE TITLE
[Feature Request] Please add in v-treeview when searching open-all

### ISSUE THREAD

**Issue by Rasool-deldar** [vuetifyjs/vuetify#13339]
### Problem to solve
When the number of lists is large and they have children, all fathers must be closed, and when it searches, all fathers must be opened to be displayed.

### Proposed solution
My suggested solution is to use props to solve this problem

**Comment by Rasool-deldar** [comment]
> My suggested solution is to use props to solve this problem

You open the link below and click on all the ones to close and then search. You will see when the search opens all items and when the search is cleared all items close.

https://codepen.io/totalhack/pen/KKzzXvr

**Comment by lioneaglesolutions** [comment]
This can be solved with a watcher;
```js
  watch: {
    search(val) {
      if (!!val) {
        this.open = [1,2,3,4]
      }
    }
  }
```

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
