### ISSUE TITLE
[Bug Report] prepend-inner & append text is not aligned to input text in v-text-fieldT

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#13348]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add text to the prepend-inner or append slots on the v-text-field. Note their alignment.

### Expected Behavior
prepend-inner text and append text should be aligned on the y axis to the input text.

### Actual Behavior
prepend-inner and append text is positioned higher than the input text.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/poRNrQx" target="_blank">https://codepen.io/MatthewAry/pen/poRNrQx</a>

### Other comments
I filed this because I had expected the text to be aligned. If my expectation is in error then at the very least, this issue should be documented with any forthcoming resolutions offered by the community.

I already expect that this can be solved by applying margin or padding styles but I think an out-of-the-box solution is preferred.

**Comment by johnleider** [comment]
The append/prepend slots are designs around using icons and have margin to accommodate that. With any custom markup, you will probably need to apply a custom class or use one of the utility classes to adjust it's positioning.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
