### ISSUE TITLE
[Feature Request] Can you provide solutions for nuxt to load modules on demand

### ISSUE THREAD

**Issue by liushuai05** [vuetifyjs/vuetify#13341]
### Problem to solve
Can you provide a solution for nuxt to load modules on demand? The package of my project is very large. I want to optimize the performance.

The above content comes from Baidu translation

### Proposed solution
Can you provide a solution for nuxt to load modules on demand? The package of my project is very large. I want to optimize the performance.

The above content comes from Baidu translation

**Comment by KaelWD** [comment]
https://nuxtjs.org/examples/lazy-loading-components/
