### ISSUE TITLE
[Bug Report] Timeline divider gets hidden if max-height and overflow specified 

### ISSUE THREAD

**Issue by danny2394** [vuetifyjs/vuetify#13349]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.12
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.15.6

### Steps to reproduce
Add class="overflow-y-auto" and stype="max-height: 200px" to <v-timeline> 

### Expected Behavior
The dividers should not be hidden when scrolled

### Actual Behavior
The dividers are hidden and only the dots are shown

### Reproduction Link
<a href="https://codepen.io/dhanish-mehta/pen/zYNoPej?editors=101" target="_blank">https://codepen.io/dhanish-mehta/pen/zYNoPej?editors=101</a>

**Comment by vanishdark** [comment]
Same here, @danny2394 did you fix this?

**Comment by danny2394** [comment]
Nope, Consolidated the number of items I have to show on the timeline.

**Comment by vanishdark** [comment]
So I found just now a work around...
`<div style="class="overflow-y-auto" style="max-height: 200px">
       <timeline>
       </timeline>
</div>
`

Seems to solve the problem. I test it in your codepen URL and it works

**Comment by danny2394** [comment]
Interesting, just putting the overflow and height outside in a  div fixed it. Thanks.

**Comment by vanishdark** [comment]
Yes! I'm assuming because the line is drawn with the height of the timeline if you set some height in the timeline will draw for that height. If you put it outside the height is auto and will draw for all the height of the component. Well anyway the issue is gone 👌
