### ISSUE TITLE
v-select: vue warn when select item in v-select

### ISSUE THREAD

**Issue by abdallahridhamohamed** [vuetifyjs/vuetify#1334]
v-select
          v-bind:items="categories"
          label="Category"
          single-line
          bottom
          item-text="name"
          item-value="id"
          v-model="customer.categoryName"
          required

when i select in v-select  i get this error in the console:

[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

and my items List is like this: 

categories = [
    {
        "id": 1,
        "name": "<Non>"
    },
    {
        "id": 2,
        "name": "Public"
    },
    {
        "id": 3,
        "name": "Rvendeur"
    },
    {
        "id": 4,
        "name": "Privé"
    },
    {
        "id": 5,
        "name": "Revendeur"
    },
    {
        "id": 6,
        "name": "Droit Algérien"
    },
    {
        "id": 7,
        "name": "Algero-Etangér"
    },
    {
        "id": 8,
        "name": "AGENCE DE VOYAGE"
    }
]

**Comment by nekosaur** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
