### ISSUE TITLE
[Bug Report] $headings 'button' in _variables.scss is unused

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#13356]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.114
**OS:** Windows 10

### Steps to reproduce
I've tried to use
```scss
$headings: (
  "button": (
    "letter-spacing": 0.13px,
  ),
);
```
to override button letter-spacing, but it didn't work (while it works for 'h1', for example).

Instead, I had to use `$btn-letter-spacing: 0.13px;`.

When I try to search for `map-deep-get($headings, 'button'` in vuetify repo - it shows zero results. So it looks like this map key is unused now and should be removed. Otherwise, it should be used to initialize $btn-letter-spacing, perhaps? Either way, currently it's misleading.

### Expected Behavior
Changing $headings "button" "letter-spacing" affects button letter spacing

### Actual Behavior
Changing $headings "button" "letter-spacing" doesn't affect button letter spacing

### Reproduction Link
<a href="https://codepen.io/maxim_mazurok/pen/GRrrBGe" target="_blank">https://codepen.io/maxim_mazurok/pen/GRrrBGe</a>

**Comment by KareemDa** [comment]
@KaelWD does this task need to be closed?

**Comment by Maxim-Mazurok** [comment]
> @KaelWD does this task need to be closed?

I think instead of closing it should be changed to:

> v-btn should probably base its values on this though

That's why I didn't close it.

**Comment by Maxim-Mazurok** [comment]
@johnleider not sure why this is closed, was it addressed in some PR/commit? Probably a good idea to link it then, cheers!
