### ISSUE TITLE
[Bug Report] Bug with disabling the text field 

### ISSUE THREAD

**Issue by denkhis** [vuetifyjs/vuetify#13353]
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.12
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux, Windows

### Steps to reproduce
1. Write something in the field 
2. Press the Enter without removing the focus 

### Expected Behavior
1. The field must be functionally disabled
2. The appearance of the field should indicate that it is disabled 

### Actual Behavior
1. Functionally the field is really disabled
2. But visually it still looks like enabled 

### Reproduction Link
<a href="https://codepen.io/denkhisamiev/pen/zYNoNVL" target="_blank">https://codepen.io/denkhisamiev/pen/zYNoNVL</a>

### Other comments
This is probably due to the fact that at the moment of pressing the enter, the field is in focus, because when you click on the button, disabling the field works correctly.

**Comment by nekosaur** [comment]
It works as expected for me on Chrome (89.0.4389.82, Windows). But on Firefox (87.0, Windows) the bottom line does not transform to a dotted line.

**Comment by KaelWD** [comment]
Looks pretty disabled to me.

**Comment by denkhis** [comment]
> It works as expected for me on Chrome (89.0.4389.82, Windows). But on Firefox (87.0, Windows) the bottom line does not transform to a dotted line.

Thank you, @nekosaur 
Yes, as i just tested, in Сhrome this functionality works correctly. For Mozilla the problem is actual.

**Comment by johnleider** [comment]
This appears to be resolved in Firefox as of the latest version: https://codepen.io/johnjleider/pen/JjNWPjm

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
