### ISSUE TITLE
[Feature Request] Expose VTreeviewNodeProps with types

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#13351]
### Problem to solve
I want to get defalut value of class in my cypress TS tests, like so:
```ts
import { VTreeviewNodeProps } from "vuetify/lib/components/VTreeview/VTreeviewNode";
const class = VTreeviewNodeProps.activeClass.default;
```

But I can't. 

### Proposed solution
Expose all `*Props`, such as `VTreeviewNodeProps`, not only `VTreeviewNode`.

Workarounds for now:
```ts
import { VTreeviewNode } from "vuetify/lib";
const class = (VTreeviewNode as any).extendOptions.props.activeClass.default;
```

Or, add `declare module "vuetify/lib/components/*";` to `src/shims-vuetify.d.ts`

**Comment by KaelWD** [comment]
In Vue 3 `VTreeviewNode.props` is typed as `any`. We don't have any plans to expose the props options as separate interfaces.
