### ISSUE TITLE
[Feature Request] Customize breakpoints in nuxt

### ISSUE THREAD

**Issue by ehsan-shv** [vuetifyjs/vuetify#13359]
### Problem to solve
How customize breakpoints like bootstrap breakpoints in nuxt app?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
