### ISSUE TITLE
[Feature Request] Vuetify Blazor

### ISSUE THREAD

**Issue by doddgu** [vuetifyjs/vuetify#13369]
### Problem to solve
We need a UI component lib for Blazor. 

### Proposed solution
Because I've used Vuetify. I like the design and code very much。I want to write a Blazor version based on Vuetify. It will be open source under MIT License, can I do it?

**Comment by KaelWD** [comment]
Vuetify is just a material design implementation, there are already others for blazor. It is MIT licensed though, so you can do whatever you want so long as you call it something else. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by askycat** [comment]
https://blazor.masastack.com  ,for Blazor

**Comment by doddgu** [comment]
> https://blazor.masastack.com ,for Blazor

  
This is our team developed, the github repo is https://github.com/BlazorComponent/MASA.Blazor
