### ISSUE TITLE
[Feature Request] v-color-picker event request

### ISSUE THREAD

**Issue by arunsundaram-redhorsecorp** [vuetifyjs/vuetify#13368]
### Problem to solve
The v-color-picker event fires @input both at the time when I programmatically set a value for v-model and when the user picks a color.

In the scenario I am working, I popup a color picker dialog and when the user selects a color, I want to close the dialog. However, I could not rely on the @input or @update events for this purpose as these are fired whenever the v-model changes.

### Proposed solution
An @colorPicked event that fires only when the user clicks a color would make this widget useful in situations such as this. I understand a question occurs in this scenario: should the event fire when the user changes color by editing the numerical representation of the color --in which case we can't be sure if the color picking is complete or not. Perhaps an additional parameter to the @colorPicked event could be passed to indicate that the event was fired because of numerically editing the color allowing the 'receiver' to decide what to do.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
