### ISSUE TITLE
[Feature Request][Vuetify 3] Add file extensions to imports in order to support webpack 5

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13362]
### Problem to solve
webpack 5 cannot be used with Vuetify 3 without using a [workaround](https://github.com/webpack/webpack/issues/11467#issuecomment-691873586).

### Proposed solution
I believe that the correct fix is to make changes like this:

```diff
-import { convertToUnit, flattenFragments } from "../../util";
+import { convertToUnit, flattenFragments } from "../../util/index.mjs";
```

... which, I suppose, would be the following in the TSX files:

```diff
-import { convertToUnit, flattenFragments } from '@/util'
+import { convertToUnit, flattenFragments } from '@/util/index.mjs'
```

**Comment by KaelWD** [comment]
https://github.com/karlprieb/babel-plugin-add-import-extension/pull/4

**Comment by LaKing** [comment]
I see the same with vite, ...
