### ISSUE TITLE
[Bug Report] VAutocomplete data slot not scrollable when used with menu-props & autofocus

### ISSUE THREAD

**Issue by shawndeprey** [vuetifyjs/vuetify#13381]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 11.2.0

### Steps to reproduce
The issue seems to occur when the menu-props show the data slot dynamically, the data are loaded dynamically, and the autocomplete is being autofocused at the same time. As the codepen should show, when you do all of these things at once, the data slot is not scrollable until you either click the autocomplete manually or type a character into the input.

### Expected Behavior
When the data slot is shown dynamically, I expect the content to be scrollable.

### Actual Behavior
When the reproduction steps are followed, the data slot are not scrollable.

### Reproduction Link
<a href="https://codepen.io/raddedd/pen/OJWgamz?editors=1010" target="_blank">https://codepen.io/raddedd/pen/OJWgamz?editors=1010</a>

### Other comments
Video of Issue: https://youtu.be/QamMA6gV8zI

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
