### ISSUE TITLE
[Bug Report] How to fix the v-app-bar when use with v-system-bar and set hide-on-scroll?

### ISSUE THREAD

**Issue by shadowdreamer** [vuetifyjs/vuetify#13389]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.72
**OS:** Windows 10

### Steps to reproduce
*

### Expected Behavior
when scroll down totally hide the v-app-bar and when scroll up fix the v-app-bar to top 

### Actual Behavior
see codpen tks

### Reproduction Link
<a href="https://codepen.io/curedovahkiin/pen/jOyGVow" target="_blank">https://codepen.io/curedovahkiin/pen/jOyGVow</a>

**Comment by maxima-us** [comment]
In my case when I set the app-bar to `hide-on-scroll` and click to a new route when it is in a hidden state, scrolling up does not unhide the app-bar (I have to reload page or go back to previous one).

Removing the system-bar fixes the issues though

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
