### ISSUE TITLE
[Bug Report] VSelect, VCombobox: `dense` prop is ignored in selection list with `multiple` prop

### ISSUE THREAD

**Issue by vilyus** [vuetifyjs/vuetify#13380]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
List items are not dense for:
```html
<v-select dense multiple :items="['foo', 'bar']" />
```

Affects both `VSelect` and `VCombobox`

### Expected Behavior
Selection list is dense

### Actual Behavior
Selection list is not dense

### Reproduction Link
<a href="https://codepen.io/Vilyus/pen/gOgRdMB?editors=101" target="_blank">https://codepen.io/Vilyus/pen/gOgRdMB?editors=101</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
