### ISSUE TITLE
[Bug Report] active slot prop of v-list-item not set on mount

### ISSUE THREAD

**Issue by Guillaumedemoff** [vuetifyjs/vuetify#13398]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 11.2.3

### Steps to reproduce
You first need a router with some route setup. Then, you need some list items with the 'to' prop set to one of the routes each. The list items must be inside a list item group.

### Expected Behavior
The active slot prop of `<v-list-item>` and the value of `<v-list-item-group>` should be set at mount according to the current route

### Actual Behavior
The active slot prop of `<v-list-item>` and the value of `<v-list-item-group>` are only set when an item is set

### Reproduction Link
<a href="https://codepen.io/guillaumedemoff/pen/dyNZaVe" target="_blank">https://codepen.io/guillaumedemoff/pen/dyNZaVe</a>

### Other comments
We can see that at mount, the active class is set to the correct item of the list, Page 1 in the codePen. It would make sense to have the prop and value that match that.

**Comment by nekosaur** [comment]
I'm not sure if the bug here is that the value is not automatically set, or that the active class _is_ set.

Could there be a scenario where you _wouldn't_ want the value to be updated automatically? If so, it would be impossible to opt out of.

**Comment by Guillaumedemoff** [comment]
The bug is that the value is not set. In the codePen, you can see that the active value is false for all three items. It should be true for the first one.

**Comment by KaelWD** [comment]
v-list-item-group doesn't interact with the router at all.

**Comment by Guillaumedemoff** [comment]
> v-list-item-group doesn't interact with the router at all.

No but v-list-item does.

**Comment by henon** [comment]
Having the same issue with v-list-item-group, namely that the active parameter of v-list-item's default slot is not changing.

@Guillaumedemoff what is the state of this? Did you PR?

**Comment by johnleider** [comment]
Closing as stale because v2 is now in maintenance mode.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
