### ISSUE TITLE
[Feature Request] multiselect enhancement: auto-grow to show all selected items, remove items with X

### ISSUE THREAD

**Issue by mariusa** [vuetifyjs/vuetify#13391]
### Problem to solve
Would you please consider making multiselect more usable as a tag selector? That is:

### Proposed solution

1. Auto-grow to show all selected items
2. Remove items with X
3. Be able to add new user defined items to the list (if search term doesn't exist already)
4. Clicking on the input after previously searching something should either have the search empty or auto-selected, so that typing another character starts a new search directly, without the need to select existing old text first

Example: https://vue-multiselect.js.org/#sub-tagging

**Comment by KaelWD** [comment]
> Auto-grow to show all selected items

It does

> Remove items with X

`chips` or custom implementation with the selection slot

> Be able to add new user defined items to the list

`VCombobox`

> either have the search empty or auto-selected

you can implement this yourself with `v-model:search`
