### ISSUE TITLE
[Feature Request] v-timeline

### ISSUE THREAD

**Issue by mbj36** [vuetifyjs/vuetify#1340]
I am looking for something like timeline which i can implement in my web app

Here is the code-pen of material design timeline - https://codepen.io/samerpik/pen/OVKyVZ
Looking for somewhat same for VuetifyJS

Timeline in Angular - http://rp.js.org/angular-timeline/example/index.html

**Comment by willin** [comment]
+1

**Comment by julianobailao** [comment]
+ 1

**Comment by mbj36** [comment]
@johnleider Will it be possible in next release :) ?

**Comment by nekosaur** [comment]
It will not be included in 1.0

**Comment by menteora** [comment]
Hi, another responsive Material Design Timeline is here: https://codepen.io/piitaya/pen/vLappz

**Comment by sebastianmacias** [comment]
I'm really looking forward to this.

As a refference, this is how [vue-timeline](https://github.com/trionfo1993/vue-timeline) looks like:

![image](https://user-images.githubusercontent.com/167750/38592032-64213790-3cff-11e8-968a-943d1a108df8.png)

It allows you to define the color and the icon of each point.

**Comment by sebastianmacias** [comment]
Does anyone know when this will be released?

**Comment by KaelWD** [comment]
1.3

**Comment by johnleider** [comment]
Now you're just being greedy @duebbert ! 😄
