### ISSUE TITLE
[Bug Report] IE11 - Checkbox is not clickable with ripple disabled only label is clickable

### ISSUE THREAD

**Issue by MrAmine08** [vuetifyjs/vuetify#13400]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
Create a template with a selectable input set ripple to false and click on checkbox

### Expected Behavior
both Checkbox input and Label should be clickable

### Actual Behavior
Only label is clickable

### Reproduction Link
<a href="https://codepen.io/mr_amine/pen/QWdOemZ?editors=101" target="_blank">https://codepen.io/mr_amine/pen/QWdOemZ?editors=101</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
