### ISSUE TITLE
[Feature Request] Inverted text opacity (text--primary-inverted)

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#13407]
### Problem to solve
Currently we have the CSS properties `text--primary`, `text--secondary` and `text--disabled`. In light mode the text color is black by default and as soon as dark mode is on, the text becomes white. So far so good.

This works fine on light backgrounds which then become dark in dark mode. But if you have a container with a dark primary color as the background set, which automatically changes to the secondary color in dark mode (because of the Vuetify implementation), then the text becomes still white.

At the moment, my solution to get around this problem looks like this:

```
<template>
<v-sheet class="primary" :class="calculateTextColor($vuetify.theme.currentTheme.primary)">
     ...
</v-sheet>
</template
<script>
export default {
methods: {
    calculateTextColor(hexColor) {
      let m = hexColor.substr(1).match(hexColor.length == 7 ? /(\S{2})/g : /(\S{1})/g);
      let r = parseInt(m[0], 16);
      let g = parseInt(m[1], 16);
      let b = parseInt(m[2], 16);
      let luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
      return luminance > 0.5 ? "black--text" : "white--text";
    }
  }
}
</script>

```

But this is a bit inconvenient in my opinion.

### Proposed solution
There should be additional properties (e.g. `text--primary-inverted` etc.), which work inversely to the previous properties. That means the text is white in lightmode and black in darkmode.

**Comment by KaelWD** [comment]
Text colours in v3 are automatically generated to contrast with the background and no longer depend on the overall theme being light or dark.
