### ISSUE TITLE
[Documentation] I can not open the web site.

### ISSUE THREAD

**Issue by jppr** [vuetifyjs/vuetify#13415]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
I used japanese.

### Expected Behavior
nothing

### Actual Behavior
nothing

### Reproduction Link
<a href="https://vuetifyjs.com/ja/" target="_blank">https://vuetifyjs.com/ja/</a>

**Comment by valentingavran** [comment]
Works for me in the browser. It is probably due to an outdated version in your cache that does not allow you to open it.

I would try resetting the website cache.

**Comment by KaelWD** [comment]
It's an intermittent build issue https://github.com/crowdin/github-action/issues/60

**Comment by Tofandel** [comment]
This issue can be closed

**Comment by FossPrime** [comment]
> 

This is still a problem. If your browser has japanese in anywhere in the language list, all links in the docs will break as there are not Japanese docs, but all links get mutated to point to non existing japanese docs.
