### ISSUE TITLE
[Bug Report] v-icon TypeError: Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by Amebus** [vuetifyjs/vuetify#13417]
### Environment
**Vuetify Version:** 2.4.9
**Last working version:** 2.3.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Windows 10

### Steps to reproduce
- git clone https://github.com/Amebus/v-icon-bug-demo.git
- cd v-icon-bug-demo
- npm install
- npm run serve
- open the devTools of the browser
- click either on button `el: document.createElement('div')` or `el: '#thumbs-up__container'`
- check the console of the devTools of the browser
  ```
  TypeError: Cannot read property 'component' of undefined
      at remapInternalIcon (helpers.ts?6ebf:225)
      at VueComponent.getIcon (VIcon.ts?9c78:72)
      at Proxy.render (VIcon.ts?9c78:217)
      at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
      at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
      at Watcher.get (vue.runtime.esm.js?2b0e:4479)
      at new Watcher (vue.runtime.esm.js?2b0e:4468)
      at mountComponent (vue.runtime.esm.js?2b0e:4073)
      at VueComponent.Vue.$mount (vue.runtime.esm.js?2b0e:8415)
      at init (vue.runtime.esm.js?2b0e:3118)
  ```

### Expected Behavior
- when pressing  button `el: document.createElement('div')` adds a thumbs-up icon wrapped by a div with class `thumbs-up__element` in the square
- when pressing the `el: '#thumbs-up__container'` replaces the sqaure with a thumb-up icon wrapped by a div with class `thumbs-up__element`

### Actual Behavior
- when pressing button `el: document.createElement('div')` adds a the wrapping div with class `thumbs-up__element` in the square without the icon
- when pressing the `el: '#thumbs-up__container'` replaces the sqaure with wrapping div with class `thumbs-up__element` without the icon

### Reproduction Link
<a href="https://github.com/Amebus/v-icon-bug-demo" target="_blank">https://github.com/Amebus/v-icon-bug-demo</a>

### Other comments
Possibly related to [#12962](https://github.com/vuetifyjs/vuetify/issues/12962) and caused by [41fd082](https://github.com/vuetifyjs/vuetify/commit/41fd082dc2ae59a35b399e5d86cf4d66729ec63b)

**Comment by KaelWD** [comment]
> `new (Vue.extend(ThumbsUp))`

You need to pass `vuetify` to any Vue instances that use vuetify components.
