### ISSUE TITLE
[Feature Request] override $font-size-root according to screen size

### ISSUE THREAD

**Issue by dudif91** [vuetifyjs/vuetify#13422]
### Problem to solve
I want to be able to override $font-size-root inside variable.scss with media query so in small screen it will be 14px

### Proposed solution
support media queries inside variable.scss

**Comment by KaelWD** [comment]
> support media queries inside variable.scss

Not possible. You could do it with a media query in a separate file that sets a css custom property then bind the sass variable to that instead.

**Comment by dudif91** [comment]
@KaelWD what about doing this inside the variable.scss: 

:root {
    --font-size: 8px;
    @media screen and (min-width: 1444px) {
        --font-size: 16px;
    }
}
$font-size-root: var(--font-size) !default;

it worked. any objections?

**Comment by KaelWD** [comment]
Anything in `variables.scss` will be duplicated for every sass file in the project.
