### ISSUE TITLE
[Bug Report] v-list-item doesn't display initial input-value

### ISSUE THREAD

**Issue by alexcolb** [vuetifyjs/vuetify#13421]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.114
**OS:** Windows 10

### Steps to reproduce
1. In the repro link for `v-list-item`, the `input-value` prop's initial value of `val=true` is not reflected in the  component's active status
2. Click the button below the list to cycle from `val=false` and then back to `val=true`
3. Observe that the active status is reflected only after clicking the button

### Expected Behavior
When `v-list-item` initially gets a truthy `input-value` prop, it should display the component with the active class

### Actual Behavior
When `v-list-item` initially gets a truthy `input-value` prop, it doesn't display with the active class

### Reproduction Link
<a href="https://codepen.io/fnlnd/pen/QWdrExw" target="_blank">https://codepen.io/fnlnd/pen/QWdrExw</a>

**Comment by KaelWD** [comment]
I don't think it's intended to be used that way: https://codepen.io/kaelwd/pen/abpGmzY?editors=1010

**Comment by alexcolb** [comment]
> I don't think it's intended to be used that way: https://codepen.io/kaelwd/pen/abpGmzY?editors=1010

That works, thanks
