### ISSUE TITLE
[Feature Request] add .select() method to v-edit-dialog similar to .focus()

### ISSUE THREAD

**Issue by ecasetracker** [vuetifyjs/vuetify#13429]
### Problem to solve
When using the `v-edit-dialog` to quickly change the text of an item, it would be nice to have the current value selected so that the user can simply type over it.

### Proposed solution
add a `.select()` method that is called after the focus so that by default this happens when the dialog is opened. The method can also be exposed externally to be called if needed.

**Comment by johnleider** [comment]
`v-edit-dialog` is being removed for v3.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
