### ISSUE TITLE
[Bug Report] mdiSvg in v-badge has incorrect height/width

### ISSUE THREAD

**Issue by lrstanley** [vuetifyjs/vuetify#13425]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.128
**OS:** Windows 10

### Steps to reproduce
n/a -- see reproduction link. I am not sure if this used to work, this is the first time implementing direct imports vs including the entire mdi library.

### Expected Behavior
mdiSvg icon to be sized correctly compared to the `mdi-icon` css import method.

### Actual Behavior
`mdiSvg` version is using default icon size, and isn't shrinking to fit inside `v-badge`.

### Reproduction Link
<a href="https://codepen.io/lrstanley/pen/ExZLYBK" target="_blank">https://codepen.io/lrstanley/pen/ExZLYBK</a>

**Comment by KaelWD** [comment]
It needs width+height instead of just font-size.

**Comment by kauanschaeffer** [comment]
I'll take a look into this
