### ISSUE TITLE
[Feature Request] Shadow DOM Support for Web Components

### ISSUE THREAD

**Issue by sajith-sathyarajan** [vuetifyjs/vuetify#13430]
### Problem to solve
When a Vue web component is created, Vuetify does not work properly with shadow DOM. For example, v-autocomplete and dialog are not working properly. 

### Proposed solution
Respective changes in 'initDetach' function for the below code.

getDocument() {
      let element = this.$refs.content;
    
      if (!element) return document;
    
      while (element.parentNode && (element = element.parentNode)) {
        if (element instanceof ShadowRoot) {
          return element;
        }
      }
    
      return document;
    },

This solution should be applied everywhere Vuetify choosing the normal DOM.

**Comment by akuehnis** [comment]
When using a custom-element built with vuetify is used inside another application built with vuetify, then the inner app overwrites the tag <style id="vuetify-theme-stylesheet"></style>.

When theming is disabled in the inner app (theme: { disable: true }), then the inner Application still overwrites the vuetify-theme-stylesheet leaving it empty.

I do recommend:
If theme.disable ist set to true, then the vuetify app MUST NOT modify the vuetify-theme-stylesheet.
Even better:  vuetify does not pollute global css at all.

My current workaround is (in the inner app):

- disable theme in the inner app
- before switching the theme (dark/light), make a copy of the current content of vuetify-theme-stylesheet
- after switching write the old content back

**Comment by tsto441** [comment]
To what extend was this fixed? I build a web-component using vue's defineCustomElement func. When I disable theming in the inner app, "vuetify-theme-stylesheet" is no longer injected into document.head. But if I enable it, it is still injected in the global head and has no effect on my component in the shadow DOM.

The workaround to copy the style to the shadow DOM works, but it is only a workaround. And it requires the parent app to use vuetify, so the WebComponent is not universally usable.

Are there plans to fix this?

**Comment by johnleider** [comment]
> To what extend was this fixed? I build a web-component using vue's defineCustomElement func. When I disable theming in the inner app, "vuetify-theme-stylesheet" is no longer injected into document.head. But if I enable it, it is still injected in the global head and has no effect on my component in the shadow DOM.
> 
> The workaround to copy the style to the shadow DOM works, but it is only a workaround. And it requires the parent app to use vuetify, so the WebComponent is not universally usable.
> 
> Are there plans to fix this?

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
