### ISSUE TITLE
[Bug Report] v-overlay ignores theme / Always dark theme

### ISSUE THREAD

**Issue by marhali** [vuetifyjs/vuetify#13435]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.128
**OS:** Windows 10

### Steps to reproduce
Place a v-card component inside an v-overlay. The card will be always displayed by using the dark theme. This also occurs if I choose the light prop for the v-overlay component.

### Expected Behavior
The current theme should be used inside the v-overlay component.

### Actual Behavior
Inside the v-overlay component every component will be shown as specified in the dark theme. The rendered html always has this tag: 'theme--dark'

### Reproduction Link
<a href="https://codepen.io/marhali/pen/QWdxeNw" target="_blank">https://codepen.io/marhali/pen/QWdxeNw</a>

**Comment by KaelWD** [comment]
John: https://github.com/vuetifyjs/vuetify/issues/4482#issuecomment-421523440 "Dark shouldn't specifically be used to make text white"  
Also John: https://github.com/vuetifyjs/vuetify/commit/0a8ac4e64e53b36ee44cb3b694ebefef1416457c#diff-2ec8ed84afa5d987ad803ca32c187e8ded1ab4f1bb0038ba99e62e6571f6014c

**Comment by marhali** [comment]
Okay dark prop is `true` via component defaults. Shouldn't this be false? 
E.g. I want to inherit light / dark prop from any parent component. In this case the `v-overlay` would still be the dark variant.

For now I'm using this as a workaround. But this does not solve the issue for theme variant inheritance:

`
<v-overlay :dark="$vuetify.theme.dark"><v-card>content</v-card></v-overlay>
`

**Comment by jasonbrent** [comment]
Chiming in to agree with the expected behavior here. Came across this bug while trying to diagnose the same unexpected dark on v-card in an overlay.

**Comment by KaelWD** [comment]
I agree, but I think that it's been this way for so long changing it now would probably cause too many issues. v2's VOverlay wasn't very useful anyway, it has been rewritten in vuetify 3 and no longer has this problem.
