### ISSUE TITLE
[Bug Report] v-snackbar is not elevated, when using text property

### ISSUE THREAD

**Issue by lojza3d** [vuetifyjs/vuetify#13438]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.105
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add
```
<v-snackbar
  value="true"
  timeout="-1"
  text
  elevation="24"
>
Something...
</v-snackbar>
```
to the template.

### Expected Behavior
The displayed snackbar should be elevated.

### Actual Behavior
The displayed snackbar is not elevated until the "text" property is removed.

### Reproduction Link
<a href="https://codepen.io/lojza3d/pen/poRZWrp" target="_blank">https://codepen.io/lojza3d/pen/poRZWrp</a>

### Other comments
Elevation does not work when "text" property is used on v-snackbar, regardless of what method/property do I use (elevation="24" or class="elevation-24").

**Comment by fabiiomiiguel** [comment]
Yes, I have the same issue too.
