### ISSUE TITLE
[Bug Report] Date picker min and max limit can be ignored by swiping

### ISSUE THREAD

**Issue by francochau** [vuetifyjs/vuetify#13432]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 11.2.3

### Steps to reproduce
1. use mobile view
2. swipe pass the max limit of the picker date

### Expected Behavior
disable the swiping when passing the min max limit 

### Actual Behavior
pickerdate can bypass min and max limit when swiping in the mobile view

### Reproduction Link
<a href="https://codepen.io/francochau/pen/rNjKPGQ" target="_blank">https://codepen.io/francochau/pen/rNjKPGQ</a>

**Comment by dchinu97** [comment]
@jacekkarczmarczyk @KaelWD Can you please assign this to me? I have previously fixed the same issue for scroll so it should be pretty much the same

**Comment by jacekkarczmarczyk** [comment]
Feel free to just open the PR if you have a fix

**Comment by dchinu97** [comment]
@jacekkarczmarczyk Can you please review 🙂?
