### ISSUE TITLE
[Feature Request] Customise the tailing of date in the date picker when using different locale

### ISSUE THREAD

**Issue by francochau** [vuetifyjs/vuetify#13433]
### Problem to solve
Current locale change of date picker will bring tailing to some locale of the date picker (e.g. Chinese)
https://codepen.io/francochau/pen/JjEZxvg?editors=101

### Proposed solution
User should be able to customise the tailing of the date

**Comment by jacekkarczmarczyk** [comment]
we're using `toLocaleDateString` for displaying days in selected local, but you can use `day-format` prop to format it by yourself (`:day-format="date => date.substr(8, 2)"`)
