### ISSUE TITLE
[Bug Report] Safari: v-list-item text selection is resetting, attribute "selectable" doesn't work

### ISSUE THREAD

**Issue by Elemir1768** [vuetifyjs/vuetify#13447]
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create v-list element and set attribute **selectable** to v-list-item element or set style **user-select: text** 
```
.v-list-item {
  user-select: text !important;
}
```

It works ok in Chrome, but in Safari text selection is resetting and it's impossible select and copy text

### Expected Behavior
Text selection works and allows you select and copy text

### Actual Behavior
In Safari text selection is resetting

### Reproduction Link
<a href="https://codepen.io/Elemir/pen/YzNOxav?editors=101" target="_blank">https://codepen.io/Elemir/pen/YzNOxav?editors=101</a>

**Comment by KaelWD** [comment]
I can't figure out what's causing this, probably a browser bug. 

https://bugs.webkit.org/enter_bug.cgi

**Comment by djeikyb** [comment]
Do I understand correctly that vuetify  is a chrome-only component library?

**Comment by KaelWD** [comment]
No, Safari is a masochist-only browser.

**Comment by djeikyb** [comment]
Kk by closing this I hear you saying "vuetify is the wrong choice if you have any Safari users, this is a chrome-only library". Please update the docs accordingly. If you can't make text selection work, you don't support Safari.
