### ISSUE TITLE
[Documentation] Examples are not loading

### ISSUE THREAD

**Issue by Richard-ED** [vuetifyjs/vuetify#13449]
### Environment

**Browsers:** Chrome 89.0.4389.114
**OS:** Linux x86_64

### Steps to reproduce
Just look at the examples

### Expected Behavior
Examples will load

### Actual Behavior
Examples are not loading

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/date-pickers/#dialog-and-menu" target="_blank">https://vuetifyjs.com/en/components/date-pickers/#dialog-and-menu</a>

**Comment by MajesticPotatoe** [comment]
Seems to load fine. Try clearing cache.

**Comment by Richard-ED** [comment]
seems to be fixed now. Thank you
