### ISSUE TITLE
[Bug Report] Tab with "to" prop doesn't follow active router link 

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#13458]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.128
**OS:** Mac OS 10.15.7

### Steps to reproduce
When going from `/foo?query=123` to `/foo?query=321` the tab with the props `to="/foo"` doesn't stay active.

### Expected Behavior
The tab to be (stay) active when matching route is active.

### Actual Behavior
When setting the route's query, the tab is not staying active.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/poRQzmw" target="_blank">https://codepen.io/thomaskientz/pen/poRQzmw</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/eaf4eae44070c6331a0315089e2d2c68d6a67e94/packages/vuetify/src/components/VTabs/VTabsBar.ts#L79-L80
