### ISSUE TITLE
[Bug Report] v-app-bar-title width decreases after page reload

### ISSUE THREAD

**Issue by codewig** [vuetifyjs/vuetify#13455]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.72
**OS:** Linux, Windows

### Steps to reproduce
Change to code in the html section of the Code Pen and wait for the the Output to refresh. The v-app-bar-title is now cut off.

### Expected Behavior
Fully visible v-app-bar-title.

### Actual Behavior
v-app-bar-title is cut off.

### Reproduction Link
<a href="https://codepen.io/Ludtwigk/pen/gOgBvWN" target="_blank">https://codepen.io/Ludtwigk/pen/gOgBvWN</a>

**Comment by KaelWD** [comment]
Turns out this implementation is pretty flawed, it assumes the page is scrolled to the top initially and that the title width can't be a fraction.

**Comment by Ludtwigk** [comment]
So currently I just use this as a workaround:
```
 .v-app-bar-title__content{
  width: 200px;
}
```
Will there be a fix in the future?

**Comment by KaelWD** [comment]
Eventually, the whole thing needs to be redone to not use scrollWidth. Use `v-toolbar-title` instead, it won't have this problem.

**Comment by Ludtwigk** [comment]
Thank you `v-toolbar-title` is working fine. Didn't know i could use it in a `v-app-bar`.

**Comment by ClintOxx** [comment]
> 
> 
> So currently I just use this as a workaround:
> 
> ```
>  .v-app-bar-title__content{
>   width: 200px;
> }
> ```
> 
> Will there be a fix in the future?

thank you so much bro I been trying to figure out how to fix this for like a day. I have the same problem, I was about to start looking at what was happening behind the sytaxtic sugar for the app-bar-title

**Comment by codewig** [comment]
You can use v-toolbar-title in v-app-bar aswell. I think its cleaner then setting a fixed width.
