### ISSUE TITLE
Feature Request: Use of Material Design Icons in Badges

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#1346]
I decided to use Material Design Icons over Material Icons. The problem is with the display rendered with directive Badge, particularly the overlap props.

The Badge support only for Material Icons is understood, so this is a feature request.

Currently, I do a minor workaround to support Material Design Icons:

`
.badge--overlap::after {
    top: 0px;
    font-style: normal
}
`

**Comment by johnleider** [comment]
I will be updating the documentation to reflect the new component. You can now place whatever you want in the slot.
