### ISSUE TITLE
[Task] v-bottom-sheet

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13466]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by ruifigueira** [comment]
Is this component excluded from Vuetify 3?

**Comment by KaelWD** [comment]
This is essentially `<v-navigation-drawer location="bottom" temporary>`, I don't know that it actually needs to remain a separate component.

**Comment by ruifigueira** [comment]
Ok, that's fine, thanks.

**Comment by archnim** [comment]
> This is essentially `<v-navigation-drawer location="bottom" temporary>`, I don't know that it actually needs to remain a separate component. 

It's not as simple as that. A good implementation of a bottom sheet comprise special gestures. And a complete bottom sheet can be in several states: closed, open(normal), and Fullscreen.

**Comment by KaelWD** [comment]
v2 bottom sheet didn't have any of that either, and it was just a dialog so it didn't even have touch drag like drawers do.

**Comment by archnim** [comment]
Exactly. I think that instead of removing the component, we should improve it 🙂
