### ISSUE TITLE
[Bug Report] Vuetify v-text-field array of messages

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#13460]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 3.0.11
**Browsers:** Firefox 87.0
**OS:** Ubuntu undefined

### Steps to reproduce
```
<v-text-field
        label="Main input"
        :messages=messages 
></v-text-field>
```
Where:

```
messages: ['first', 'second']
```

### Expected Behavior
Two strings should be displayed: "first" and "second"

### Actual Behavior
Only the first string of the array is displayed

### Reproduction Link
<a href="https://codepen.io/begueradj-the-sasster/pen/oNBQRVP?editors=101" target="_blank">https://codepen.io/begueradj-the-sasster/pen/oNBQRVP?editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
use `error-count` property, not sure if that's the best name for the prop controlling number of displayed hints as well

**Comment by begueradj** [comment]
Indeed, that works. 
Thank you very much @jacekkarczmarczyk
