### ISSUE TITLE
Avoid duplicate code

### ISSUE THREAD

**Issue by Fl0pZz** [vuetifyjs/vuetify#1347]
Let's look at these two files:
* [VMenu.vue](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VMenu/VMenu.vue)
* [VMenu.js](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VMenu/VMenu.js)

The javascript of both files is identical, then why does not the `VMenu.vue` file do like this?
`VMenu.vue`:
```vue
<script src="./VMenu.js"></script>

<style lang="stylus" src="../../stylus/components/_menus.styl"></style>
```

**Comment by nekosaur** [comment]
We're currently restructuring the components. It's just a forgotten file
