### ISSUE TITLE
[Task] v-data-table

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13479]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by leosolid** [comment]
anybody working on this yet?

**Comment by Stevelriemenbill** [comment]
Is there any update to this? According to the milestones it should have come with the first Vuetify 3 beta release. This is currently the only thing holding us back from going live with Vue 3. We use this feature heavily in our Vue 2 application.

**Comment by johnleider** [comment]
Data table wasn't ready so it was pushed to 3.1, which we anticipate to come relatively quickly after 3.0 release.

**Comment by otavio** [comment]
> Data table wasn't ready so it was pushed to 3.1, which we anticipate to come relatively quickly after 3.0 release.

Is there any public branch we could look at current work in progress component?

**Comment by Stevelriemenbill** [comment]
> > Data table wasn't ready so it was pushed to 3.1, which we anticipate to come relatively quickly after 3.0 release.
> 
> Is there any public branch we could look at current work in progress component?

https://github.com/vuetifyjs/vuetify/tree/feat/v3-data-table

**Comment by otavio** [comment]
Great. Is there a place with the missing items needing work?

**Comment by diavrank** [comment]
it would be great to have a beta version for 3.1 to start testing this component with our apps.

**Comment by jacekkarczmarczyk** [comment]
https://next.vuetifyjs.com/en/introduction/roadmap/#labs

**Comment by Karacraft** [comment]
It is supposed to be addressed in v.3.1 (Q1 2023).
Finger's crossed till then or create own setup

**Comment by paulinavcole** [comment]
Is there any update on the release of data tables(and date pickers)?

**Comment by VictorTrusty** [comment]
We need it ASAP for a live-app. Please keep us informed :)

**Comment by VictorTrusty** [comment]
Yep, I saw that. But since we are almost done with Q4 2022, that's why I am asking for news here 👍

**Comment by johnleider** [comment]
Actively working on it right this minute.

**Comment by lorand-horvath** [comment]
@johnleider Is the "Labs" package available to use at this moment? All I can find is this link, but nothing more that I could use, try or install https://next.vuetifyjs.com/en/introduction/roadmap/#labs
I've also heard it mentioned in the "Views on Vue" podcast you and Erik attended last month.

**Comment by johnleider** [comment]
There are still 7 days left in the month.

**Comment by MaYoRr** [comment]
Should I expect a table component this year?

**Comment by keyboardSmasher** [comment]
Just in time for the Vue 4 launch! 🎉

**Comment by iamdeadman** [comment]
Can someone suggest how do I install the vuetify development version ? 
I want to install and use the 3.1 dev version (assuming that has the labs version with the data table components)

**Comment by lorand-horvath** [comment]
@iamdeadman @johnleider is still working on Vuetify Labs, as alluded [here](https://github.com/vuetifyjs/vuetify/issues/13479#issuecomment-1361610808) and [here](https://github.com/vuetifyjs/vuetify/issues/13479#issuecomment-1364574299).
We should all be patient and wait for the necessary work to actually be completed. I don't want to be a beta (alpha) tester. Do you?

**Comment by KaelWD** [comment]
> I don't want to be a beta (alpha) tester.

> I'm really looking forward to trying [labs]

Labs literally is alpha components

**Comment by lorand-horvath** [comment]
> > I don't want to be a beta (alpha) tester.
> 
> > I'm really looking forward to trying [labs]
> 
> Labs literally is alpha components

@KaelWD I see now that 'Labs is a new way for developers to use unfinished components in an alpha state.'
Well then... I'll have to be an alpha tester :-)

**Comment by guykatz** [comment]
will we be able to use the playground for lab components?

**Comment by adnan-razzaq** [comment]
any update?

**Comment by diavrank** [comment]
Jhon Leider published on his Twitter that it will be released tomorrow.

**Comment by TotallyNotSethP** [comment]
> There are still 7 days left in the month.

There isn't anymore

**Comment by maxchia18** [comment]
Hi, so how can we use v-data-table in our Vuetify3.0 project?

**Comment by Viktohblake** [comment]
any way for this yet?

**Comment by lorand-horvath** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.0

**Comment by MetRonnie** [comment]
I am using 3.1.0, however it doesn't seem to be there. I get
> [Vue warn]: Failed to resolve component: v-data-table

**Comment by lorand-horvath** [comment]
https://next.vuetifyjs.com/en/labs/introduction/#usage
```
import { createVuetify } from 'vuetify'
import { VDataTable } from 'vuetify/labs/VDataTable'

export default createVuetify({
  components: {
    VDataTable
  }
})

```

**Comment by yujiri8** [comment]
Is there documentation on the changes to it since v2? It seems that the `<template #item.field=...` syntax is invalid in vue 3. I can find this page on v3 v-data-table: https://next.vuetifyjs.com/en/api/v-data-table/

But the page it links to is 404.

**Comment by IAmRGroot** [comment]
> Is there documentation on the changes to it since v2? It seems that the `<template #item.field=...` syntax is invalid in vue 3. I can find this page on v3 v-data-table: https://next.vuetifyjs.com/en/api/v-data-table/
> 
> But the page it links to is 404.

It is still here in the docs, but the codepen isn't updated for the labs change so I don't know if it should work: https://next.vuetifyjs.com/en/components/data-tables/basics/#item

**Comment by nekosaur** [comment]
https://dev.vuetifyjs.com/en/components/data-tables/basics/#item

If you're getting an eslint error, see https://github.com/vuejs/eslint-plugin-vue/pull/1330. Regardless the eslint error does not prevent it from working though.

**Comment by yujiri8** [comment]
Thank you both! I am able to get it working now.

**Comment by guykatz** [comment]
@nekosaur I think I saw a closing of the data table virtualization.
the docs are not yet update: see https://dev.vuetifyjs.com/en/components/data-tables/virtual-tables/
is this supported in lab already?
thanks

**Comment by nekosaur** [comment]
Yes. You can see an example here https://dev.vuetifyjs.com/en/components/data-tables/basics/#v-data-table-virtual
