### ISSUE TITLE
[Task] v-data-iterator

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13478]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by 1Luc1** [comment]
will this task be part of v3.2?

**Comment by johnleider** [comment]
> @johnleider Can you justify your decision to close this task? Is there another way to achieve such an functionality like the v-data-iterator was within vuetify v.2 ? Thank you for the information.

@nekosaur

**Comment by MarcoTroost** [comment]
Bump. 

Our v2 application also uses the data-iterator quite a lot. 
We would very much like to see it ported to vuetify3.

kind regards, Marco
