### ISSUE TITLE
[Bug Report] Custom items-per-page prop doesn't update in footer

### ISSUE THREAD

**Issue by iblobtouch** [vuetifyjs/vuetify#13488]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.128
**OS:** Windows 10

### Steps to reproduce
Load the pen, check the footer.

### Expected Behavior
Rows per page displays the current items-per-page prop value

### Actual Behavior
Rows per page displays the default value of 5, even though the applied value is the one in the prop.

### Reproduction Link
<a href="https://codepen.io/Iblobtouch/pen/mdRaeRb?editors=1111" target="_blank">https://codepen.io/Iblobtouch/pen/mdRaeRb?editors=1111</a>

**Comment by KaelWD** [comment]
This is basically #4000, although v-data-table should probably merge the options itself. You can work around it by adding the desired option to the list as well: `:footer-props="{ itemsPerPageOptions: [5, 10, 15, 100, -1] }"`
