### ISSUE TITLE
[Task] v-date-picker

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13480]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by lorand-horvath** [comment]
May I ask whether it would be possible to prioritize the v-date-picker port to v3.1 sooner than Q2 2023 ?
I would very much like to see it in Vuetify Labs... I need it in a few projects I'm currently porting from Vuetify 2 to 3.

Thank you all for your hard work releasing Vuetify 3.1 + Labs - that's actually pretty awesome and exciting!

**Comment by lorand-horvath** [comment]
@johnleider @KaelWD May I ask whether it would be possible to prioritize the v-date-picker port to v3 sooner than Q2 2023 ?
I would very much like to see it in Vuetify Labs... it's quite needed in a few projects I'm currently porting from Vuetify 2 to 3.

Thank you all for your hard work releasing Vuetify 3.1 + Labs - that's actually pretty awesome and exciting!

**Comment by johnleider** [comment]
This task is already in process by @nekosaur https://github.com/vuetifyjs/vuetify/tree/feat/v3-date-picker

**Comment by spmsupun-certscanner** [comment]
@johnleider when will this be released?

**Comment by chuannguyen1208** [comment]
Anything new Sir. ? I'm watching this page every day

**Comment by mrserzhan** [comment]
> Anything new Sir. ? I'm watching this page every day

Same here, the only thing that stops me from migrating to vuetify 3

**Comment by johnleider** [comment]
Here are the P.R.s to keep an eye on:

https://github.com/vuetifyjs/vuetify/pull/16691
https://github.com/vuetifyjs/vuetify/pull/16234

Working on getting #16691 closed out this week because it's what prevents us from duplicating everything we are writing for pickers in calendars. Once that's in the pieces should fall into place considering #16234 is very far along in development.

**Comment by Stefanosapk** [comment]
Cannot find the v-time-picker in Vuetify 3. Do we have the plans to include it? @KaelWD @johnleider

**Comment by sulton-max** [comment]
Still can't find time picker, is this task finished ?

**Comment by johnleider** [comment]
@blalan has something ready for review #13516.

**Comment by johnleider** [comment]
This task was completed as part of the v3.4 release.
