### ISSUE TITLE
[Task] v-parallax

### ISSUE THREAD

**Issue by chris-saburo** [vuetifyjs/vuetify#13495]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by colearendt** [comment]
Just a note that `v-parallax` in Vue / Vuetify 2 looks super choppy on mobile (tested on iPhone 7). If mobile performance could be addressed / improved with the Vuetify 3 release, that would be awesome!

Interesting article, in case it helps: https://medium.com/@dhg/parallax-done-right-82ced812e61c

**Comment by KaelWD** [comment]
Resolved by 7f7fafe5e
