### ISSUE TITLE
Extra trailing commas break code - Error: Module build failed

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#135]
In: `https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/index.js` 
lines: 4,5

```
import TextInput from './TextInput.vue',
import Textarea from './Textarea.vue',
```

**Comment by johnleider** [comment]
Fixed with 66917bf8050613d458e8e4a9788b703afc70c02d
