### ISSUE TITLE
[Task] v-speed-dial

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13508]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by mspinelli** [comment]
Is there a roadmap for when the `v-speed-dial` will be included in Vue 3?

**Comment by johnleider** [comment]
Unfortunately this is being pushed to a labs release later this year. Sorry for an inconvenience.

**Comment by jo3codes** [comment]
> Unfortunately this is being pushed to a labs release later this year. Sorry for an inconvenience.

Any chances this will be in a 3.4 update instead of waiting until 3.5? This is the last component for us to move a large project from Vue 2.
