### ISSUE TITLE
v-badge with IE11

### ISSUE THREAD

**Issue by afuentes90** [vuetifyjs/vuetify#1351]
### Steps to reproduce
Open https://vuetifyjs.com/directives/badges with IE11.

### Versions

Only with IE11

### What is expected ?

We expect the icon of v-badge appears.

![screen shot 2017-08-14 at 16 50 18](https://user-images.githubusercontent.com/20858742/29277004-b4305988-8110-11e7-9cf5-f6324507e390.png)

### What is actually happening ?

The v-badge icon is empty (only with background color). 

![screen shot 2017-08-14 at 16 51 45](https://user-images.githubusercontent.com/20858742/29277062-e1685720-8110-11e7-8c74-41e4aa1e69f4.png)

The problem also appears if we put fa- prefix in icon name i.e.
 `<v-icon v-badge:save.overlap.icon.right>fa-server</v-icon>`

![screen shot 2017-08-14 at 16 54 29](https://user-images.githubusercontent.com/20858742/29277204-43b92120-8111-11e7-83a4-a4ac4e392eb9.png)

If we put without fa- prefix, the v-bagde icon appears well but not the icon.
![screen shot 2017-08-14 at 16 58 18](https://user-images.githubusercontent.com/20858742/29277419-e0033a2a-8111-11e7-82a5-7a64de8f3114.png)

### Reproduction Link

 https://vuetifyjs.com/directives/badges

**Comment by johnleider** [comment]
Fixed with 6a341bf5357b3ea004f77505f4730f2f2b51a70c
