### ISSUE TITLE
[Task] v-timepicker

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13516]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by Stefanosapk** [comment]
@johnleider @KaelWD 
Hey guys! I would like to ask you if we have any release plan about `v-time-picker` in Vuetify 3? I searched a lot and did not find anything. I appreciate the effort you put on that, I'm just asking you so to have an idea on when I will be able to migrate from 2.7 to Vuetify 3. :)

**Comment by johnleider** [comment]
> @johnleider @KaelWD Hey guys! I would like to ask you if we have any release plan about `v-time-picker` in Vuetify 3? I searched a lot and did not find anything. I appreciate the effort you put on that, I'm just asking you so to have an idea on when I will be able to migrate from 2.7 to Vuetify 3. :)

Sometime shortly after v3.4's release.

**Comment by Sevyls** [comment]
any update to the planned release of this component?

**Comment by Stefanosapk** [comment]
@johnleider  Is it possible to include it in the next release [v3.5](https://vuetifyjs.com/en/introduction/roadmap/#long-term-support-lts) please? We are been using it a lot and we want to migrate a few projects to Vue 3 and Vuetify 3.

**Comment by OvenRobert** [comment]
Hey guys, any update on this component release?
