### ISSUE TITLE
Alignment of multiple list-tile-actions

### ISSUE THREAD

**Issue by Ragura** [vuetifyjs/vuetify#1352]
### Steps to reproduce
Add multiple v-list-tile-actions to a v-list-tile, after a v-list-tile-content.
### Versions

Vue version 2.4.2
Vuetify version 0.14.8
Using Windows. Tested in Chrome and Edge.

### What is expected ?

The flex alignment of both actions should be the same or a directive should exist to alter the alignment. Doing it manually means setting multiple overrides and hoping nothing will change on Vuetify's end in the future that would alter or add to these properties.

### What is actually happening ?

The flex alignment of the first tile-action will be different from the others. This is because it seems to be adding flex alignment properties through this selector:
**.list__tile__content+.list__tile__action:not(.list__tile__action--stack)**

### Reproduction Link

https://codepen.io/anon/pen/GvRpZK

**Comment by jacekkarczmarczyk** [comment]
Replacing "+" with "~" helps

**Comment by devmedoo** [comment]
I've used this as a dirty solution in my component
`<style scoped>
.list__tile__action {
    min-width: 15px;
    padding-left: 1%;
}
</style>
`
