### ISSUE TITLE
[Task] goto

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13538]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

**Comment by jgalante-ecr** [comment]
Any update on goTo?

**Comment by johnleider** [comment]
> Any update on goTo?

Not at this time

**Comment by m50S79sM6SRNp8Jn** [comment]
What is goTo?

**Comment by johnleider** [comment]
Track this issue for goTo progress https://github.com/vuetifyjs/vuetify/pull/17286

**Comment by Rhaegal0411** [comment]
Will this be released next week?
