### ISSUE TITLE
Dialog form autofocus not working

### ISSUE THREAD

**Issue by AGPDev** [vuetifyjs/vuetify#1353]
### Versions
v0.14.11

### Reproduction Link
https://codepen.io/AGPDev/pen/dzVeGm

**Comment by Ragura** [comment]
Yes, this problem still seems to be there, quite annoying for user experience and it seems you also can't force it to focus through regular scripting.

**Comment by johnleider** [comment]
This has been resolved on dev. It was actually a bug with autofocus in general.

Here is a workaround until next release https://codepen.io/johnjleider/pen/RZxqeK

**Comment by Ragura** [comment]
Thank you for the assistance!
