### ISSUE TITLE
[Bug Report] v-data-table having progress bar as column data in mobile doesn't show

### ISSUE THREAD

**Issue by narkissbv** [vuetifyjs/vuetify#13543]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.85
**OS:** Windows 10

### Steps to reproduce
1. Create a v-data-table element
2. Set one of the columns to display a `v-progress-linear` component
3. Give proper values to the progress bar

### Expected Behavior
Progress bar should be displayed  in mobile mode

### Actual Behavior
Progress bar is not visible in mobile mode

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-forked-qtpmf?file=/src/layout.vue" target="_blank">https://codesandbox.io/s/vuetify-playground-forked-qtpmf?file=/src/layout.vue</a>

### Other comments
A workaround I have implemented locally was to override the mobile row-cell class style like so:
```
.v-data-table__mobile-row__cell {
  flex: 1;
}
```

**Comment by ricardocastanho** [comment]
How do you workaround locally?
I try to declare `<style scoped>` tag, but it doesn't work.
If I remove the property "scoped" works, but it changes all tables in my app
