### ISSUE TITLE
[Bug Report] V-Combobox Returns String Even When Data is selected

### ISSUE THREAD

**Issue by Previesam** [vuetifyjs/vuetify#13544]
### Environment
**Vuetify Version:** 1.5.22
**Vue Version:** 3.0.1
**Browsers:** Chrome 90.0.4430.72
**OS:** Linux x86_64

### Steps to reproduce
Try typing in the Combobox to search and you get filtering normally, But when you select one of the results it will not select the item as long as there is text left in the input field. I am not sure what is wrong here

### Expected Behavior
Click on search result should select the item and set the object as the value of this field

### Actual Behavior
Try typing in the Combobox to search and you get filtering normally, But when you select one of the results it will not select the item as long as there is text left in the input field. I am not sure what is wrong here

### Reproduction Link
<a href="https://codepen.io/previesam/pen/OJWrrKZ" target="_blank">https://codepen.io/previesam/pen/OJWrrKZ</a>

### Other comments
Please help. I am also trying to use it with my custom filtering server using search-input.sync along with watch property.

**Comment by KaelWD** [comment]
Seems to be caused by having a function as `item-text`. `item-text="Code"` works but ``:item-text="item => `${item.Code}`"`` doesn't.

**Comment by Previesam** [comment]
> Seems to be caused by having a function as `item-text`. `item-text="Code"` works but `` :item-text="item => `${item.Code}`" `` doesn't. Probably related to #11585

Thank for the response. I think you're right about it been related to the v-autocomplete issue, I encountered the problem reported in that issue and is why I changed to combobox. I will try the work around and give feedback. Thank you one again.
