### ISSUE TITLE
[Bug Report][2.4.11] Navigation Drawer Hover hides when a Select is used

### ISSUE THREAD

**Issue by OblivionSY** [vuetifyjs/vuetify#13555]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Firefox 88.0
**OS:** Windows 10

### Steps to reproduce
Use Navigation drawer from Vuetify Site (hover to expand)
Use Select example from Vuetify site
Combine the two
When you click on the Select, the navigation drawer closes (to mini view) 

### Expected Behavior
Draw to stay open as still a) over the content, b) using content in the drawer

### Actual Behavior
Select menu appears, but drawer collapses back to mini version

### Reproduction Link
<a href="https://codepen.io/OblivionSY/pen/dyNrYaa" target="_blank">https://codepen.io/OblivionSY/pen/dyNrYaa</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
