### ISSUE TITLE
[Feature Request] Expansion Panel named index

### ISSUE THREAD

**Issue by Sjoerd82** [vuetifyjs/vuetify#13551]
### Problem to solve
Currently the index numbering is not ordered (sometimes), a named index would make opening and closing specific panels much (much!) easier.

### Proposed solution
add a name property to v-extension-panel.

**Comment by Sjoerd82** [comment]
Actually, it's a bit worse even; I have random index numbers for my dynamically created panels, and because of that no way to tell which panel is currently open.

**Comment by xfyre** [comment]
I've been looking into this lately as well. Having expansion panels act similarly to item groups (so that each panel can be assigned an arbitrary value) will make this very easy, and sounds like a logical thing to do.

**Comment by xfyre** [comment]
Theres a similar feature req already: #8001
