### ISSUE TITLE
[Feature Request] V-Tabs Prev / Next Slot

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#13550]
### Problem to solve
Vuetify v-tabs component should implement prev and next slots as provided in v-slide-group. It would allow better customization of the buttons while maintaining consistency over similar components.

### Proposed solution
Implement slots for previous and next arrow as seen on v-slide-group.

**Comment by alexmccabe** [comment]
This is something our team is currently battling right now

**Comment by KaelWD** [comment]
You have access to these slots if you use `v-tabs-bar` instead of putting your tabs directly in `v-tabs`

```html
<v-tabs>
  <v-tabs-bar>
    <template #prev />
    <v-tab />
```
