### ISSUE TITLE
[Bug Report] Unable to import vuetify from CDN

### ISSUE THREAD

**Issue by totocto** [vuetifyjs/vuetify#13563]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.85
**OS:** Mac OS 10.13.6

### Steps to reproduce
Just import vuetify from cdn not working since yersterday ( VCalendar.ts:2 Uncaught TypeError: (0 , vue__WEBPACK_IMPORTED_MODULE_0__.defineComponent) is not a function )

### Expected Behavior
Import Vuetify from  CDN

### Actual Behavior
Error in VCalendar line 2 that prevent from importing Vuetify

### Reproduction Link
<a href="https://codepen.io/totocto/pen/yLgwWqW?editors=0001" target="_blank">https://codepen.io/totocto/pen/yLgwWqW?editors=0001</a>

### Other comments
If you have any idea of fixing it by myself (by importing others versions), don't hesitate to tell me :) I need to fix it for my actual project
This does not work on any OS (project on lambda, on mac or windows)

**Comment by jacekkarczmarczyk** [comment]
you should always pin the version when loading from cdn, same like you're doing it with every other package in your codepen, for some reason you've skipped it just for vuetify

**Comment by KaelWD** [comment]
Especially jsdelivr, it likes to ignore npm tags and just return the newest version even if it's v3 alpha (what's happening here)

**Comment by totocto** [comment]
Yes, you are right! I fixed it by pulling the right version! Thank you!
