### ISSUE TITLE
[Bug Report] bottom border not visible for v-text-field with hide-details placed in v-tab-item

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#13569]
### Environment
**Vuetify Version:** 2.4.11
**Last working version:** 2.4.0-beta.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.128
**OS:** Windows 10

### Steps to reproduce
Place v-text-field with hide-details at the bottom of v-tab-item

### Expected Behavior
Bottom border is visible

### Actual Behavior
Bottom border is hidden (unless field is focused)

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/vYgMmPJ?editors=1000" target="_blank">https://codepen.io/jkarczm/pen/vYgMmPJ?editors=1000</a>

Working (2.4.0-beta.0):
https://codepen.io/jkarczm/pen/poRBPGB?editors=1000

Caused by https://github.com/vuetifyjs/vuetify/pull/11983

**Comment by petiphan** [comment]
@jacekkarczmarczyk so prop 'hide-details' hide that section under the textfield, just don't use this prop and it will solve your problem

**Comment by johnleider** [comment]
We use the **before** pseudo element to display the bottom line.

![image](https://user-images.githubusercontent.com/9064066/125724709-68f6352a-5b70-476a-901f-dad4bbb77cb9.png)

There isn't a good way to solve this from our end that is worth the effort. Closing.
