### ISSUE TITLE
[Bug Report] VSlider miss the "append" slot in the render function

### ISSUE THREAD

**Issue by radiorz** [vuetifyjs/vuetify#13564]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.85
**OS:** Windows 10

### Steps to reproduce
just look at the codepen

### Expected Behavior
find the miss slot

### Actual Behavior
VSlider miss the "append" slot in the render function

### Reproduction Link
<a href="https://codepen.io/radiorz/pen/zYNXYBo" target="_blank">https://codepen.io/radiorz/pen/zYNXYBo</a>

**Comment by KaelWD** [comment]
Workaround is to use the old slot syntax: https://codepen.io/kaelwd/pen/RwpxyjB?editors=1010

**Comment by johnleider** [comment]
The append slot isn't scoped and shouldn't be used as such. This will naturally be resolved as part of Vuetify 3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
