### ISSUE TITLE
[Bug Report] v-text-field in nested grid is changing width after validation

### ISSUE THREAD

**Issue by TkaczykAdam** [vuetifyjs/vuetify#13579]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.1
**Browsers:** Chrome 90.0.4430.85
**OS:** Linux x86_64

### Steps to reproduce
1. Insert invalid value to one of the text fields

### Expected Behavior
The width of `v-text-field` is constant.

### Actual Behavior
The width of `v-text-field` is changing depends on the error message length.

### Reproduction Link
<a href="https://codepen.io/Chromekk/pen/VwPOpdN" target="_blank">https://codepen.io/Chromekk/pen/VwPOpdN</a>

**Comment by TkaczykAdam** [comment]
Any update?

**Comment by johnleider** [comment]
This is the expected flex behavior. If you want it to remain the same, define a grid level. https://codepen.io/johnjleider/pen/gOWmPjJ

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
