### ISSUE TITLE
[Bug Report] DIV inside BUTTON does not validate

### ISSUE THREAD

**Issue by schwoortz** [vuetifyjs/vuetify#13572]
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.72
**OS:** Windows 10

### Steps to reproduce
Set up a date picker 
<v-date-picker v-model="picker"></v-date-picker>

Inspect HTML on any given BUTTON (day)

### Expected Behavior
Text within "Day BUTTON" rendered as SPAN:
BUTTON - SPAN - BUTTON

### Actual Behavior
Text within "Day BUTTON" rendered as DIV:
BUTTON - DIV - BUTTON

### Reproduction Link
<a href="https://codepen.io/schwoortz/pen/QWdPBWY" target="_blank">https://codepen.io/schwoortz/pen/QWdPBWY</a>

### Other comments
Functionality and accessibility are both good, but HTML output does not meet validator requirements, which is a prerequisite in certain legislatives (wcag).

 Datepicker HTML Validation fails, because:
"Error: Element DIV not allowed as child of element BUTTON in this context."

The v-date-picker creates the following HTML output for each day:
<button type="button" class="...">
  <div class="v-btn__content">21</div>
 </button>

For it to pass the w3c validator, the text should be rendered as SPAN:
<span class="v-btn__content">21</span>

From what I see this would have to be changed to SPAN in
date-picker-table.js
#151: }), [this.$createElement('div', {

**Comment by KaelWD** [comment]
The w3c validator is a waste of time, make sure it follows accessibility guidelines and you're fine. I'm not aware of any laws that require sites to pass that.
