### ISSUE TITLE
[Bug Report] Item slot of combobox cannot get index

### ISSUE THREAD

**Issue by heirychen** [vuetifyjs/vuetify#13583]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Other
**OS:** Linux x86_64

### Steps to reproduce
Try to click Edit of the drop-down item to observe the console output.

### Expected Behavior
The console outputs the correct index.

### Actual Behavior
The index is undefined

### Reproduction Link
<a href="https://codesandbox.io/s/stoic-sun-15xp6?file=/src/App.vue" target="_blank">https://codesandbox.io/s/stoic-sun-15xp6?file=/src/App.vue</a>

**Comment by KaelWD** [comment]
Are you expecting the index if the item in the items array? The original index isn't stored anywhere, if you type "b" for example the only index we could give you would be `0`, so it wouldn't be useful for modifying the original array.

**Comment by heirychen** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-combobox/misc-advanced.vue

Is the index in the edit() method still recommended in this official example?

**Comment by KaelWD** [comment]
I don't know when that was added, you can see that it's not actually used for anything in the example though.
