### ISSUE TITLE
[Feature Request] v-img support for local blob urls

### ISSUE THREAD

**Issue by tgaff** [vuetifyjs/vuetify#13591]
### Problem to solve
This proposal gives `v-img` the ability to use *local blob URLs* in the same way regular `img` tags can. 

Currently if you:
```js
<v-img :src="blobUrl" />
```
You'll get an error:  `net::ERR_FILE_NOT_FOUND` from VImg's `loadImage` method.  The image will *not* be displayed.

If however you use a regular `img` element, this works fine and the image is displayed.

#### specific case

In my specific case I was implementing file uploads and generating thumbnails from them.  These in turn were passed to `v-carousel` which failed since it depends on `v-img`.  I needed to display a mix of previously uploaded remote png files, and just now uploaded blob URLs generated in the browser.  I can workaround this using regular `img` tags, but I'd prefer to have all the usual `v-img` power.

#### what is a blob url?

A blob URL such as `"blob:http://localhost:7777/b565133c-d412-40a3-84e7-552782e1f95f"` may be generated by a file uploader (Uppy does this) as a thumbnail or in other JS ways.
You can generate one by passing a `File` object to `URL.createObjectURL()`

You can quickly generate one with something like:
```js
const url = '/favicon.png';
let blob = await fetch(url).then(r => r.blob());
let src = URL.createObjectURL(blob);
var img = document.createElement("img")
img.src = src;
document.body.appendChild(img);
// image should now be at the bottom of the page
```

### Proposed solution
Detect blob urls passed on `:src` and treat them separately.  My understanding is that they always start with "blob:"

**Comment by KaelWD** [comment]
This sounds like a bug report but I couldn't reproduce it with the code sample you provided: https://codepen.io/kaelwd/pen/poRMZKq?editors=1010

**Comment by tgaff** [comment]
Will investigate.  I didn't actually use that code locally, just copied it in.  
I had a previously generated url from uppy and was comparing with a template like:

```
    <div v-for="(s,i) in allImageUrls">
      <img :src="s" :key="i" />
    </div>
    <p>v-img</p>
    <div v-for="(s,i) in allImageUrls">
      <v-img :src="s" :key="i" />
    </div>
```


I couldn't find any references to these being supported in the past so I didn't want to assume this was a bug.

**Comment by tgaff** [comment]
Let's close this.  In the general case blob URLs do work in v-img and even in v-carousel.  

For this specific case I've been able to determine that uppy was _most likely_ discarding those blub Urls (probably using `revokeObjectURL`) and a race condition existed between the image being loaded and the discard.  The issue was easiest to reproduce in a v-carousel, likely because it didn't attempt to pre-render the images before the user clicks to them.  I also could not reproduce it in Firefox (only Chrome).
