### ISSUE TITLE
[Bug] List component is broken in latest update (active tile not highlighted)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#1359]
### Steps to reproduce

Create a `v-list` and set the active list-tile item programmatically via `v-model` or pass `:value=true`.

### Versions
Latest Vue, Chrome, Win10

### What is expected ?
The selected tile should transition to the active state as described in the docs.

> v-model | Toggles the list tile active state

https://vuetifyjs.com/components/lists

### What is actually happening ?
Nothing

### Reproduction Link
https://codepen.io/anon/pen/NvaQVx (click on the second tile)

**Comment by nekosaur** [comment]
Solved in #1361
