### ISSUE TITLE
Error when using v-alert with an icon.

### ISSUE THREAD

**Issue by radicaled** [vuetifyjs/vuetify#136]
Whenever I use a `v-alert` with an icon, I get an exception. Using other elements that use `v-icon` inside themselves work fine. I'm on Vuetify 0.8.8

Using `v-alert`:

```html
<v-alert error>
  Hello, world.
</v-alert>
```

Error:

```
vue.common.js?4eb4:2658 [Vue warn]: Error when rendering component <alert>:
App.vue?27c5:163 TypeError: _vm._v is not a function(…)
```

I'm bundling with webpack. Here's the module where the error comes from -- the line that triggers the error is commented, it's the quite long one in the middle of the module.

```javascript
module.exports={render:function (){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;
  return _c('div', {
    directives: [{
      name: "show",
      rawName: "v-show",
      value: (_vm.isActive),
      expression: "isActive"
    }],
    staticClass: "alert",
    class: _vm.classes
  }, [(!_vm.hideIcon) ? _c('v-icon', {
    staticClass: "alert__icon"
  }, [_vm._v(_vm._s(_vm.mdIcon))]) : _vm._e(), _c('div', [_vm._t("default")], 2), (_vm.dismissible) ? _c('a', { // this is the line that triggers the error.
    staticClass: "alert__dismissible",
    attrs: {
      "href": "#!"
    },
    on: {
      "click": function($event) {
        $event.preventDefault();
        _vm.$emit('input', false)
      }
    }
  }, [_c('v-icon', {
    attrs: {
      "right": "right"
    }
  }, [_vm._v("cancel")])], 1) : _vm._e()], 1)
},staticRenderFns: []}
```

This only happens when I don't set the `hideIcon` attribute. If I do set `hideIcon`, and I insert a `v-icon` element directly within `v-alert`, everything works fine. `v-alert` is the only element of Vuetify that's failing to work, and only in cases where I don't supply `hideIcon`, so I do think I've got everything set up correctly on my end. I do see that the v-alerts on vuetify.com work, though -- is there something about v-alert that doesn't work with webpack?

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by radicaled** [comment]
Sorry, I can't reproduce this outside of Webpack + Babel, so jsfiddle is out of the question. I'll close this since I have a work-around already.
