### ISSUE TITLE
[Bug Report] The value of this.$refs.textField.value used for v-text-field is undefined

### ISSUE THREAD

**Issue by HelloGwkki** [vuetifyjs/vuetify#13603]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 7

### Steps to reproduce
1. Change the content of the text field
2. Click 'submit' button
3. The content of the text field output in the console is undefined

### Expected Behavior
Output the content of the current text field

### Actual Behavior
Output is undefined

### Reproduction Link
<a href="https://codepen.io/hghghghghg/pen/wvJwOjq" target="_blank">https://codepen.io/hghghghghg/pen/wvJwOjq</a>

### Other comments
I am not good at English, so I used Google Translate.

**Comment by KaelWD** [comment]
`$refs.imgLink.value` is whatever you passed to the `value` prop
