### ISSUE TITLE
[Bug Report] undefined is not an object (evaluating 'this.getContent().scrollHeight') for few iOS users

### ISSUE THREAD

**Issue by filips123** [vuetifyjs/vuetify#13608]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Steps to reproduce are not reliable and I also can't reproduce and test them myself (I don't have iPhone). Only three of my iOS users got this error, so it seems it depends on some specific browser configuration.

1. Open https://gimvicurnik.filips.si
2. Click on "V redu" and then "Razred"
3. There should be a select component on the page that allows you to choose multiple options

The other two users got the same error through the settings page, but it requires more steps to reproduce and it leads to the same component.

The only "reproduction link" I have is the actual website code. Because I can't test the website on iPhone, I also can't create a minimal reproduction example project. Page that crashed uses this component: https://github.com/filips123/GimVicUrnik/blob/main/website/src/components/settings/entitySelection/SelectClass.vue

### Expected Behavior
Select component should work correctly.

### Actual Behavior
I only received a crash report through Sentry, so I don't know what visually or functionally happened to the website. The main thing I know is that there was a TypeError in VSelect.ts (full stack trace and more details are in comments).

### Reproduction Link
<a href="https://github.com/filips123/GimVicUrnik/tree/main/website" target="_blank">https://github.com/filips123/GimVicUrnik/tree/main/website</a>

### Other comments
Exception stack trace (with applied sourcemaps):

```
TypeError: undefined is not an object (evaluating 'this.getContent().scrollHeight')
  at onScroll(../../../src/components/VSelect/VSelect.ts:743:16)
  at onScroll([native code])
  at s(chunk-vendors.03d09962.js:4:12)
  at r(../../src/module/stateFactory.ts:25:10)
```

Exception stack strace (without applied sourcemaps):

```
TypeError: undefined is not an object (evaluating 'this.getContent().scrollHeight')
  at onScroll(/js/settings~welcome.f4e8d9cd.js:1:71481)
  at onScroll([native code])
  at ne(/js/chunk-vendors.03d09962.js:5:11755)
  at r(/js/chunk-vendors.03d09962.js:21:50591)
```

This corresponds to this line: https://github.com/vuetifyjs/vuetify/blob/v2.4.11/packages/vuetify/src/components/VSelect/VSelect.ts#L743

Browsers:

* `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`
* `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`
* `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 LightSpeed [FBAN/MessengerLiteForiOS;FBAV/310.0.0.38.116;FBBV/287543612;FBDV/iPhone13,3;FBMD/iPhone;FBSN/iOS;FBSV/14.4.2;FBSS/3;FBCR/;FBID/phone;FBLC/en-GB;FBOP/0]`

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. This is a very convoluted reproduction process and has nothing actionable on our end.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
