### ISSUE TITLE
[Feature Request] Ability to override mixins (Vuetify v3 Titan)

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#13602]
### Problem to solve
In v2 of Vuetify we can't override the mixin if we want to alter the functionality of mixin Vuetify uses to generate various styles (e.g. elevation mixin)

### Proposed solution
We can check how bootstrap allows overriding mixin

**Comment by KaelWD** [comment]
I don't think this is possible with the way everything currently works.
