### ISSUE TITLE
[Feature Request] Use different shadows/elevation on light and dark theme

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13601]
### Problem to solve
Currently, the same shadow SCSS map is used in both light and dark. Even we can't change the color of shadow in a dark theme.

This feature helps create color-focused websites where developers want different shadows based on light and dark. (In Vuetify 3 there will be multiple themes as well - e.g. https://gridsome.org and using same dark shadows in themes like sepia will mess up the colors and look of website)

If you want to try out bad it looks just check the various shadows by toggling light and dark. Shadow might look good in light but in dark theme, it isn't good as compared to white.

### Proposed solution
1. Moving shadows map to $material-light and $material-dark under main theme map will do the trick
2. We can use SCSS function somehow to achieve this

NOTE: This might be big change so it can be considered for Vuetify 3 Titan

**Comment by KaelWD** [comment]
If you just want to change the color (not the spread values) you can set the `$shadow-key-umbra-opacity`, `$shadow-key-penumbra-opacity` and `$shadow-key-ambient-opacity` sass variables to css custom properties and change those based on the theme. The theme system in v3 already uses custom properties, so if you wanted your shadows to be the accent color you'd set them to:
```scss
$shadow-key-umbra-opacity: rgba(var(--v-theme-accent), 0.2);
$shadow-key-penumbra-opacity: rgba(var(--v-theme-accent), 0.14);
$shadow-key-ambient-opacity: rgba(var(--v-theme-accent), 0.12);
```
You can also do this in v2 by enabling `customProperties`: https://vuetifyjs.com/en/features/theme/#custom-properties
