### ISSUE TITLE
[Feature Request] Meaningful SCSS map key names (Vuetify v3 Titan)

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13612]
### Problem to solve
Currently, some SCSS map keys names are not easy to understand we have to dig in source code and have to find where it is being used and after that, we find the meaning of it.
```scss
map-deep-get($material, 'text', 'theme')
````

Above is used by pagination for `color` of active pagination item and its name is `theme`. How can anyone understand this? :thinking:

Also, `$material-light/dark` map have too general names:
```scss
map-deep-get($material, 'cards')
```

To find out what `cards` mean we have to dig in source code and we find that "ohh, it's for background".

Hence, using meaningful key names will make the developement easier and we don't have to clone the vuetify source code localy just to find what SCSS map key name means.

### Proposed solution
Simple, just use meaningful key names

```scss
map-deep-get($material, 'cards', 'background-color')
```

**Comment by nekosaur** [comment]
The theme system is completely re-done in v3, and the $material maps are no longer used.

**Comment by jd-0001** [comment]
Hi @nekosaur Can we check somewhere what's coming in v3 so we can get an overall idea of how we shall develop our project?

**Comment by albertkaaman1** [comment]
There is an early alpha that you can check out. Also look at the Vuetify 3 github project, and the #v3-discussion channel on Discord.

**Comment by nekosaur** [comment]
There is an early alpha that you can check out. Also look at the Vuetify 3 github project, and the #v3-discussion channel on Discord.
