### ISSUE TITLE
[Bug Report] [v-btn-toggle] wrong active button with v-model binding

### ISSUE THREAD

**Issue by lukasberbuer** [vuetifyjs/vuetify#13615]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 10

### Steps to reproduce
Click buttons randomly in provided example

### Expected Behavior
Button "1" should always be activated after change

### Actual Behavior
The clicked button stays activated although the binded variable `btnIndex` is always set to `1` inside the `onChange` method

### Reproduction Link
<a href="https://codepen.io/lukasberbuer/pen/GRWgxyg" target="_blank">https://codepen.io/lukasberbuer/pen/GRWgxyg</a>

**Comment by jacekkarczmarczyk** [comment]
You need to update selection in next tick
https://codepen.io/jkarczm/pen/LYWRWjO
