### ISSUE TITLE
[Bug Report] v-window with transition causes scroll jump (was declared fixed before but has reappeared)

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#13619]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Linux x86_64

### Steps to reproduce
- Open the link
- Scroll down to bottom
- Click on one of carousel buttons
- The screen jumps up

### Expected Behavior
Scroll should not change

### Actual Behavior
Scroll jumps up to start of v-window

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/mdWyorY" target="_blank">https://codepen.io/yooneskh/pen/mdWyorY</a>

### Other comments
There was an issue regarding this and it was declared fixed but it has reappeared as it seems.

**Comment by yooneskh** [comment]
Scrolling is ok if transition is omitted. I suppose carousel has a default transition already and this seems strange.

**Comment by KaelWD** [comment]
Duplicate of #10613
