### ISSUE TITLE
[Bug Report] Using certain icons with md icon font results in two icons

### ISSUE THREAD

**Issue by arcreative** [vuetifyjs/vuetify#13618]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use a v-icon component with a string that could be interpreted as two separate icons.  In this case "person_search" contains two valid icons, both "person" and "search".  I see both in my app when using this one icon identifier.

### Expected Behavior
One icon displays as in the codepen

### Actual Behavior
Two icons (e.g. person and search) show up instead

### Reproduction Link
<a href="https://codepen.io/arcreative/pen/PopwBzY" target="_blank">https://codepen.io/arcreative/pen/PopwBzY</a>

### Other comments
Could this be related to vue-template-compiler? I'm using that in my project as well since this is using Webpacker on Rails.

**Comment by jacekkarczmarczyk** [comment]
> Use a v-icon component with a string that could be interpreted as two separate icons

`person_search` could not  be interpreted as two separate icons

![image](https://user-images.githubusercontent.com/15625235/117508622-35a02480-af89-11eb-8a39-768e6ae26da7.png)

**Comment by jacekkarczmarczyk** [comment]
Sorry, misread the issue, anyway codepen doesn't reproduce the issue - please provide a reproduction where we could see 2 separate icons

**Comment by arcreative** [comment]
@jacekkarczmarczyk Thanks, will try.  It's only happening on my Rails/Webpacker app using `vue-template-compiler`, but we're probably converting to vanilla Webpack soon.  Hopefully that will resolve it, but will update my reproduction link if I figure out how to break it :-)

**Comment by jacekkarczmarczyk** [comment]
I'd check if you're using latest version of the icon font, maybe older version didn't include this icon

**Comment by arcreative** [comment]
@jacekkarczmarczyk Wow... upgrading did it, I feel stupid!  Sorry for bothering you with this, you guys are great!
