### ISSUE TITLE
[Bug Report] Tab does not select anything in VAutocomplete menu with multiple tag set

### ISSUE THREAD

**Issue by Tomdanizer** [vuetifyjs/vuetify#13613]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Edge 90.0.818.51
**OS:** Windows 10

### Steps to reproduce
Set multiple tag on VAutocomplete and then open the list of options.
With an option highlighted using keyboard arrows, hit tab. 

### Expected Behavior
Highlighted option is selected / saved to model.

### Actual Behavior
Highlighted option is not selected / not saved to model. Focus is instead moved to next element.

### Reproduction Link
<a href="https://codepen.io/tomdanizer/pen/OJpPzzO" target="_blank">https://codepen.io/tomdanizer/pen/OJpPzzO</a>

### Other comments
The expected functionality would mimic the control when multiple tag is not set.

**Comment by KaelWD** [comment]
This is intentional. The WAI-ARIA practices specifically mention "a single-select listbox": https://www.w3.org/TR/wai-aria-practices/#listbox_kbd_interaction
