### ISSUE TITLE
[Bug Report] Automatic Bottom Space in div with image in it

### ISSUE THREAD

**Issue by sunnykandev** [vuetifyjs/vuetify#13627]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 3.0.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 10

### Steps to reproduce
I just wrapped an <img> with <div>
Then there comes a space of about 7px at the bottom of the div.

### Expected Behavior
There shouldn't be a space unless I add padding-bottom

### Actual Behavior
But there automatically comes a space at the bottom.
I don't know how to remove the space.

### Reproduction Link
<a href="https://codepen.io/bigthunder/pen/zYZGQQN" target="_blank">https://codepen.io/bigthunder/pen/zYZGQQN</a>

**Comment by KaelWD** [comment]
This has nothing to do with vuetify.

**Comment by erthi16** [comment]
Hello to you. By default, images are displaying like text (inline) so space is left bellow them to accomodate descending characters and adjacent inline elements. To remove the unwanted space, juste declare images as d-block or d-flex.
Note: the amount of space is related to the font size. 

https://www.tutorialrepublic.com/faq/how-to-remove-white-space-under-an-image-using-css.php#:~:text=Answer%3A%20Use%20the%20CSS%20display,to%20adjust%20other%20inline%20elements.

**Comment by sunnykandev** [comment]
Thank you very much
