### ISSUE TITLE
[Bug Report] Vitejs  v-app-bar failed

### ISSUE THREAD

**Issue by ggdream** [vuetifyjs/vuetify#13626]
### Environment
**Vuetify Version:** 3.0.0-alpha.0
**Vue Version:** 3.0.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 10

### Steps to reproduce
npm run dev

### Expected Behavior
run successfully

### Actual Behavior
[Vue warn]: Failed to resolve component: v-app-bar 
  at <Header> 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

### Other comments
It's cannot work well

**Comment by KaelWD** [comment]
It doesn't exist yet

**Comment by jacekkarczmarczyk** [comment]
There is no such component as v-app-bar in vuetify 3 yet.

**Comment by ggdream** [comment]
> There is no such component as v-app-bar in vuetify 3 yet.

Oh, oh. Thanks for your reply, and expect it
