### ISSUE TITLE
v-select not open after get async component from cache

### ISSUE THREAD

**Issue by siteprofCF** [vuetifyjs/vuetify#1363]
Hi!

I use an async components in Vue.
When I call component at first time, Vuetify is working good.
If I call component again, component created from cache,  v-select does'nt work.

I try v-select with v-if.
When I toggle v-if v-select working good.
  
But it isn't good solution, can I find more optimal solution?

Can you help me?

**Comment by nekosaur** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please edit your issue with the required information, thank you.
