### ISSUE TITLE
[Bug Report] Vuetify Select on mobile don't close on click to scroll

### ISSUE THREAD

**Issue by schirrel** [vuetifyjs/vuetify#13632]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
i have a v-select from Vuetify on my app and on mobile, when user scroll on screen, clicking and scrolling the list don't close. I'm also using v-click-outside directive but the behavior continues the same.
The behavior can be seen even in the vuetify component, on mobile phone or event the browser simulator. 

### Expected Behavior
On mobile click to scroll the select close itself

### Actual Behavior
The dropdown keeps open

### Reproduction Link
<a href="https://codepen.io/schirrel/pen/VwpveMY?editors=1010" target="_blank">https://codepen.io/schirrel/pen/VwpveMY?editors=1010</a>

### Other comments
I had it on stackoverflow also
https://stackoverflow.com/questions/67470336/vuetify-select-on-mobile-dont-close-on-click-to-scroll

**Comment by KaelWD** [comment]
> On mobile click to scroll the select close itself

I don't understand what this means.

**Comment by schirrel** [comment]
@KaelWD 
On mobile phone, the user scroll to page by "clickin"and "drag"to scroll,  as in
![d6kyh](https://user-images.githubusercontent.com/6757777/118160459-b67d7700-b3f4-11eb-9b26-d77eaa3fddd3.gif)

This behavios shouldn't close too the select dropdown? Or event be listened on v-click-outside?

**Comment by KaelWD** [comment]
No, that does not trigger a click event. Menus in vuetify 3 will have an option to close on scroll.
