### ISSUE TITLE
[Documentation] Prop "medium" missing in API doc for VIcon

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#13631]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at the docs https://vuetifyjs.com/en/components/icons/ and the API docs https://vuetifyjs.com/en/api/v-icon/

### Expected Behavior
All the props that the component has are documented

### Actual Behavior
The "medium" prop is missing even though it's being used in the examples on the documentation page

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-icon/" target="_blank">https://vuetifyjs.com/en/api/v-icon/</a>

**Comment by MajesticPotatoe** [comment]
api is correct. **medium** is always false as its the "default" size. Usage example needs to be updated.

**Comment by douira** [comment]
So passing the `medium` prop doesn't actually do anything and that's why it doesn't appear in the API doc? I looked at the source and that seems to be how it works. I think the example should maybe mention that because then it'd be pointless to try and pass `medium: true` if the component doesn't even use it.

**Comment by douira** [comment]
In addition to the usage example this other example uses the `medium` prop: https://vuetifyjs.com/en/components/icons/#material-design

**Comment by MajesticPotatoe** [comment]
Gotcha, yeah then would just need to remove it from there too 👍  Thanks.
