### ISSUE TITLE
[Bug Report] Text field in app bar get focused 

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#13640]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
Press enter from a text-field anywhere in the app (in v-main).

### Expected Behavior
Nothing to happen.

### Actual Behavior
The text-field in the app-bar is focused.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/qBrbNEm" target="_blank">https://codepen.io/thomaskientz/pen/qBrbNEm</a>

**Comment by KaelWD** [comment]
Unable to reproduce in chrome 90.0.4430.93 on either linux or macos

**Comment by ThomasKientz** [comment]
Sorry, was due to [enpass extension ](https://chrome.google.com/webstore/detail/enpass-extension-requires/kmcfomidfpdkfieipokbalgegidffkal).
