### ISSUE TITLE
[Bug Report] v-combobox not closing on enter

### ISSUE THREAD

**Issue by saurabhtalreja** [vuetifyjs/vuetify#13645]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.5.6
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 10

### Steps to reproduce
Open the above codepen, or if not create a v-combobox and then
1.) Instead of model use :value
2.) Add @change event and it's handler
3.) Data property ie :items of combobox should be object
4.) Input anything which there in dropdown and then enter, do not select from dropdown, just hit enter

### Expected Behavior
It should search from the list and select that object, also it should close the drop down.

### Actual Behavior
It is not selecting the item from list ie the object item, rather its outputting a string. Also the dropdown should close automatically using update:return-value of v-menu

### Reproduction Link
<a href="https://codepen.io/saurabhtalreja/pen/abJdqbx" target="_blank">https://codepen.io/saurabhtalreja/pen/abJdqbx</a>

**Comment by eliamartani** [comment]
Hi all,

I was trying to reproduce the issue but it doesn't seem to be a real bug.

First I went to the documentation https://vuetifyjs.com/en/api/v-combobox/#props,

Adding the property `:auto-select-first="true"` solves the issue by selecting the first option available and closing the drop down.

For the second point, I could not understand how `update:return-value` is supposed to work here as it is always returning `undefined` so I just ignored it.
