### ISSUE TITLE
[Bug Report] v-icon doesn't work with custom Fontawesome kit icons

### ISSUE THREAD

**Issue by KaiFuglem** [vuetifyjs/vuetify#13649]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 90.0.4430.85
**OS:** Mac OS 10.15.4

### Steps to reproduce
1. Upload custom Fontawesome kit icon (see https://fontawesome.com/how-to-use/on-the-web/using-kits/uploading-icons)
2. Try using the custom icon with `v-icon`, example:

   ```
   <v-icon>fak fa-test</v-icon>
   ```

### Expected Behavior
- Custom icon is displayed

### Actual Behavior
- A default Fontawesome icon is displayed

### Reproduction Link
<a href="https://codepen.io/kaifuglem/pen/poeyjYg" target="_blank">https://codepen.io/kaifuglem/pen/poeyjYg</a>

### Other comments
This could maybe be a feature request... wasn't sure which fit better.

I believe that adding `fak` to this `isFontAwesome5()` function should fix this issue:

https://github.com/vuetifyjs/vuetify/blob/b04dbba82fdd03c732f7b2e5ea144037f0b59b6a/packages/vuetify/src/components/VIcon/VIcon.ts#L26-L28

**Comment by KaelWD** [comment]
Note that you should still be using the css/iconfont version of fontawesome, see #3505
