### ISSUE TITLE
[Bug Report][2.5.0] Regression: vCarousel in v-if triggers an error

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#13656]
### Environment
**Vuetify Version:** 2.5.0
**Last working version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
Put a carousel in a v-if, toggle it, notice the error in the console

### Expected Behavior
No error to occur

### Actual Behavior
`TypeError: Cannot read property 'clientHeight' of undefined`

### Reproduction Link
<a href="https://codesandbox.io/s/bug-report-forked-sq8q7?file=/src/App.vue" target="_blank">https://codesandbox.io/s/bug-report-forked-sq8q7?file=/src/App.vue</a>

### Other comments
Introduced by https://github.com/vuetifyjs/vuetify/commit/faeb8dfb8b1361f2195ea89785b747bca3e24672
Was not throwing an error in 2.4.11

**Comment by Tofandel** [comment]
@KaelWD I believe the way the VCarousel theme was fixed is flawed, it should just use the `Themeable` mixin instead of using a sub theme provider, no?

**Comment by nirmalraghavan** [comment]
I have this same issue with **2.4.11** and **2.2.34**
Vue Version: 2.6.11

**Comment by Tofandel** [comment]
> I have this same issue with **2.4.11** and **2.2.34**
> Vue Version: 2.6.11

I cannot reproduce it in those versions with my reproduction, can you post a minimal reproduction?

**Comment by mahammad-sixberries** [comment]
still the same issue with 2.5.1 using nuxt
