### ISSUE TITLE
[Feature Request] It should be easier to focus form fields whenever they come into view, such as when dialogs are reopened

### ISSUE THREAD

**Issue by egeersoz** [vuetifyjs/vuetify#13657]
### Problem to solve
It was requested that we refrain from commenting on closed issues. This is a continuation of issue [10659](https://github.com/vuetifyjs/vuetify/issues/10659).

The proposed solution posted by Kael is to use `setTimeout()`. While that works, I think it is not optimal. In my opinion, `setTimeout()` is an anti-pattern here because it is an *imperative* style of programming, whereas the real strength of (and for a lot of people, the main point of using) a UI framework like Vuetify is that it is *declarative*: the programmer does not have to worry about the specifics of each behavior and the way it is implemented; rather, they simply pass props to components to declare the desired end result , and the framework handles it all under the hood.

https://codeburst.io/imperative-vs-declarative-javascript-8b5e45a602dd

I have over one hundred dialog boxes and navigation drawers in my app, and I hate the idea of having to litter the codebase with `setTimeout`s just to make input fields autofocus.

### Proposed solution
It would be great if there was an easier, "out-of-the-box" way for common UX/usability tasks like auto-focusing an input field in a dialog every time the dialog opens. (Using the autofocus prop on the fields themselves isn't sufficient because it only works the first time the dialog opens.)

The ideal solution would be a revision to the autofocus prop on inputs, such as `autofocus="always"` so that it autofocuses the input each time it comes into view, rather than just the first time it is rendered. This would keep the behavior isolated to the input, rather than coupling it with those of parent components (dialogs/nav-drawers).

**Comment by jacekkarczmarczyk** [comment]
That should be resolved by https://github.com/vuetifyjs/vuetify/issues/6764

**Comment by KaelWD** [comment]
> such as `autofocus="always"` so that it autofocuses the input each time it comes into view

You can probably implement this yourself with a wrapper component and IntersectionObserver, I don't think it works well as a generic solution though.
