### ISSUE TITLE
[Feature Request] Horizontal Virtual Scroll

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#13650]
### Problem to solve
On mobile devices a horizontal scroll is sometimes a better UX solution.

### Proposed solution
A flag to turn `v-virtual-scroll` horizontal.

**Comment by MathieuDerelle** [comment]
is it implemented ? its not described in the docs
https://vuetifyjs.com/en/api/v-virtual-scroll/
