### ISSUE TITLE
[Bug Report][2.5.0] v-pagination first,previous,nextlast page buttons not working properly

### ISSUE THREAD

**Issue by ampminfo** [vuetifyjs/vuetify#13663]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 3.0.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Windows 10

### Steps to reproduce
I found out that my First, Previous,Next and Last Page buttons are not working properly compared to the page numbers buttons which are ok.

First and last page button trigger the @update:option events but :page.sync is triggered after so currentPage variable is not right when enterring my event function so wrong page is displayed. On first page load with my table, If I click the Last Page button and then the first page button, my last page is displayed so meaning that the event of changing currentPage variable is done after.

my data is loaded through server side paging using ajax by using the current page number, number of items per page and sorting (using mysql limit syntax)

I am using the latest from CDN

https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js
https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js

### Expected Behavior
Button should change to the right page using the First, Previous, Next, Last buttons. they are offset by one click.

### Actual Behavior
Wrong page displayed, page increment is executed after next page data load

### Reproduction Link
<a href="https://codepen.io/ampminfo/pen/dyNqxQm" target="_blank">https://codepen.io/ampminfo/pen/dyNqxQm</a>

**Comment by KaelWD** [comment]
Please provide a **simplified** reproduction link without any third-party dependencies.

**Comment by ampminfo** [comment]
I moved the compontent into the code instead of a external js file but you still need the ajax call to outside.

**Comment by ampminfo** [comment]
I updated the javascript scripts links.  Probably a left over of some tests I did.

**Comment by jacekkarczmarczyk** [comment]
the codepen link is still far from being a simplified reproduction

**Comment by ampminfo** [comment]
did my best.  sorry

**Comment by ampminfo** [comment]
any update?

**Comment by ampminfo** [comment]
I have reactivated my codepen example, Any update?

**Comment by ampminfo** [comment]
I was able to fix this with the following modification:

methods: {
  handlePageChange: function(e) {
            var self = this;                                                       <--- this line
            self.currentPage = e.page;                                   <--- this line
            this.updateTableData(self, this.filterdata);             <--- this line changed with new frist parameter
        },
  updateTableData: function(vuetifyobj, filter){
            var self = vuetifyobj;                                 <--- this line
            self.demandes = [];
            self.totalPages=0;
            self.totalNumberOfItems=0;
....
   },
 },

I had to pass my "this" to the parameters to get the good copy of the vuetify object because the one received was still on previous content before my  "self.currentPage = e.page;" adjustment.

**Comment by ampminfo** [comment]
var self=this was my mistakes.... take copy instead of this the real "this"...moron I was.
