### ISSUE TITLE
[Bug Report][2.5.0] VSelect not showing persistent placeholder

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#13666]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
Open codepen

### Expected Behavior
Show placeholder when prop `persistent-placeholder` is set

### Actual Behavior
Is not showing the placeholder

### Reproduction Link
<a href="https://codepen.io/jenaxi/pen/NWpRxmG" target="_blank">https://codepen.io/jenaxi/pen/NWpRxmG</a>

**Comment by zetaraku** [comment]
The placeholder of **VFileInput** is also not showing when `persistent-placeholder` is set.

I make a demo to reproduce these problems, please take a look :)

https://github.com/zetaraku/vuetify-demo

**Comment by KaelWD** [comment]
Duplicate of #13792

**Comment by zetaraku** [comment]
@KaelWD The placeholder of VFileInput is not showing when `persistent-placeholder` is set as I mentioned above.
Should I open a new issue to handle it?
