### ISSUE TITLE
[Bug Report][2.5.0] Multiple drawer not supported due to bad application service code

### ISSUE THREAD

**Issue by Caceresenzo** [vuetifyjs/vuetify#13665]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
Click on `go to x page`

### Expected Behavior
Handle multiple mavigation drawer in the application.left variable

### Actual Behavior
Only handling the last one by overwriting the value
https://github.com/vuetifyjs/vuetify/blob/a6cb6e5d64e81e71b3be0d2f3acb1cc12b671077/packages/vuetify/src/services/application/index.ts#L39

### Possible fix
```js
this.application[location][uid] = size
```

### Reproduction Link
<a href="https://codepen.io/caceresenzo/pen/BaWLNxQ?editors=1011" target="_blank">https://codepen.io/caceresenzo/pen/BaWLNxQ?editors=1011</a>

**Comment by KaelWD** [comment]
@johnleider was this really removed just to support keep-alive? (#9797)

**Comment by johnleider** [comment]
> @johnleider was this really removed just to support keep-alive? (#9797)

At the time it was also useful in resolving an animation issue with components being registered/unregistered and causing weight content changes or otherwise janky behavior.

**Comment by Caceresenzo** [comment]
Will this be fixed?

**Comment by Caceresenzo** [comment]
I heavily depends on multiple drawer, I was having no choice but to fix the problem in any kind of way.

The first solution was to patch the dist files. It completly broke when a new version released.... (kind of expected)

The second (and current) solution is to replace the current application function as soon as possible:

```js
$vuetify.application.register = function (
    uid: number,
    location: any,
    size: number
  ) {
    this.application[location][uid] = size
    this.update(location)
  }
```

This is a dirty hack, and will propably break if the team decide to fix the original problem.

**Comment by Caceresenzo** [comment]
Thanks
