### ISSUE TITLE
[Bug Report][2.5.0] V-Data-Footer: pagination without select is not correctly placed

### ISSUE THREAD

**Issue by robbevp** [vuetifyjs/vuetify#13678]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Firefox 88.0
**OS:** Mac OS 10.15

### Steps to reproduce
Create a DateTable or DateIterator and disable items per page in the footer props

### Expected Behavior
The pagination should be placed at flex end

### Actual Behavior
The pagination is placed at flex-start with a small left margin

### Reproduction Link
<a href="https://codepen.io/RobbeVP/pen/PopbmYg" target="_blank">https://codepen.io/RobbeVP/pen/PopbmYg</a>

### Other comments
This issue was introduced here: https://github.com/vuetifyjs/vuetify/commit/1c81605cef397d946e75a13fb4c28461e7ce7c33#diff-5f364abf7e40402fba2e33d47919cb872c0ce29fb7f9fe9c0df7ffed53c43420

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
