### ISSUE TITLE
[Documentation] v-content is referenced in documentation, although it is not used anymore

### ISSUE THREAD

**Issue by varna2** [vuetifyjs/vuetify#13675]
### Environment

**Browsers:** Firefox 88.0
**OS:** Windows 10

### Steps to reproduce
In documentation (https://next.vuetifyjs.com/en/components/application/), section " Application components " there is a picture to display page structure (https://cdn.vuetifyjs.com/images/layouts/app.png). This picture mention v-content - although v-main should be used instead of v-content.

### Expected Behavior
v-main in the picture

### Actual Behavior
v-content in the picture

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/application/#application-components" target="_blank">https://next.vuetifyjs.com/en/components/application/#application-components</a>

**Comment by MajesticPotatoe** [comment]
duplicate #11663
