### ISSUE TITLE
v-toolbar-side-icon ignores v-show directive

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#1368]
### Steps to reproduce
Add `v-show` directive to `v-toolbar-side-icon` component.

### Versions
Latest of everything.

### What is expected ?
The icon should be hidden.

### What is actually happening ?
The icon is displayed in all its proud glory.

### Reproduction Link
https://codepen.io/anon/pen/QMOGeQ

### Additional Notes
This appears to be a regression, although I didn't have time to go back to previous versions to find out specifically which one, but this has definitely been working correctly in the past.

Thanks!

**Comment by Ragura** [comment]
The same thing happens if you add a class to toggle visibility.
**class="hidden-md-and-up"** will not function. This is indeed something that has been introduced in a newer version.

**Comment by waqasraz** [comment]
I think it starts doing with 0.14.11. Because previously I had a badge on v-toolbar-side-icon now it's gone. 

<v-toolbar-side-icon v-badge="{ value: 6, overlap: true  }"></v-toolbar-side-icon>

**Comment by DedDorito** [comment]
I'll have to double check when I have more time, but I was using 0.14.5 and it was showing/hiding correctly, so perhaps there's more than one case here causing issues.

**Comment by waqasraz** [comment]
Meanwhile, I will use this. While it's being fixed.

`<v-btn icon> <v-icon  v-show="applesauce">menu</v-icon> </v-btn>`
