### ISSUE TITLE
Allow non text inputs to have both primitive and object values.

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#1369]
I think this would mainly affect `v-radio` `v-toggle` and `v-checkbox`. Though it could also be applied to `v-select` components. 

Off the top of my head I can't think of a good example use case. This may mean it is more of an edge case, but because these aren't actual html elements there is no technical limitation to passing around objects instead of just strings.

So, unless someone can come up with unintended side effect then it seems like it would be a useful feature if a developer needs it. Especially since this isn't something that takes extra code to implement it would just involve changing the allowed types for value properties.

**Comment by johnleider** [comment]
This is all possible now with 0.15.3
