### ISSUE TITLE
[Feature Request] Create new component v-terminal

### ISSUE THREAD

**Issue by Employee87** [vuetifyjs/vuetify#13695]
### Problem to solve
Allows users to display terminals that look like command prompts. The result would look like this
https://imgur.com/dYc6WVY

### Proposed solution
Create a component that uses the below css. It will have options for dark/light mode, terminal dimensions, and v-html for content.

```
<style>
.log {
    max-height:300px;
    overflow-y:auto;
    padding:10px;
    background-color:#1e1e1e;
    border-radius:5px;
    color:white;
    white-space:break-spaces;
    word-break:break-all;
}
</style>
<pre class="log" v-html="terminal_code"></pre>
```

**Comment by KaelWD** [comment]
This is outside the scope of this project. The code snippets in our documentation are rendered using https://github.com/PrismJS/prism
