### ISSUE TITLE
[Documentation] Pre-made layouts example code not found 404

### ISSUE THREAD

**Issue by renfei** [vuetifyjs/vuetify#13699]
### Environment

**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click the code button
![image](https://user-images.githubusercontent.com/6532952/119256844-35dd2880-bbf5-11eb-9e25-85619d4956ae.png)

### Expected Behavior
show example code

### Actual Behavior
Error 404 - not found
![image](https://user-images.githubusercontent.com/6532952/119256852-42618100-bbf5-11eb-9165-a1965b39f852.png)

### Reproduction Link
<a href="https://v2.vuetifyjs.com/en/getting-started/pre-made-layouts" target="_blank">https://v2.vuetifyjs.com/en/getting-started/pre-made-layouts</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/wireframes/
