### ISSUE TITLE
Is Vuetifyjs.com home page navbar responsive?

### ISSUE THREAD

**Issue by sylvaincaillot** [vuetifyjs/vuetify#1370]
### Steps to reproduce
Visit https://vuetifyjs.com/ website on your smartphone

### Versions
Chrome 59 on Android 5.0.1

### What is expected ?
I would expect to see the Documentation and Updates menu items in the responsive navigation bar. In fact, I was expecting to see the 3 line menu icon (hamburger icon) for this small device in order to access the different menu items.

### What is actually happening ?
I see only the Documentation menu item and no hamburger icon.

I just want to be sure that the navigation bar is responsive in Vuetify before going further with this library which looks very nice.

Thank you

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
