### ISSUE TITLE
[Feature Request] How to use custom Class or ID on V-img

### ISSUE THREAD

**Issue by Elkaroui** [vuetifyjs/vuetify#13709]
### Problem to solve
Hi ✋
How to add a custom class or id inside the v-img elements?

```javascript
    <div class="v-image__image v-image__image--contain [custom Class]" id="[custom ID]"
        style="background-image: url(img); background-position: center center;">
    </div>
```

### Proposed solution
n/a

**Comment by KaelWD** [comment]
`<v-img class="[custom Class]">`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
