### ISSUE TITLE
[Bug Report][2.5.1]  highlighting prepend icon in treeview

### ISSUE THREAD

**Issue by pabatt** [vuetifyjs/vuetify#13708]
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
click on prepend triangle - it's highlighted until you click in other place
click on openable list item - prepend triangle is not highlighted

### Expected Behavior
prepend triangle is not highlighted

### Actual Behavior
prepend triangle highlighted

### Reproduction Link
<a href="https://codepen.io/pabatt/pen/NWpgEKm" target="_blank">https://codepen.io/pabatt/pen/NWpgEKm</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
