### ISSUE TITLE
vuetify.min.css not found on unpkg.com?

### ISSUE THREAD

**Issue by masasron** [vuetifyjs/vuetify#1371]
https://unpkg.com/vuetify@0.14.11/dist/vuetify.min.css

File not found?

Cannot find file "/dist/vuetify.min.css" in package vuetify@0.14.11

**Comment by jimaek** [comment]
You can use jsDelivr instead. We use a perm-cache. Meaning if a file was served once it will be available for ever no matter what.

https://cdn.jsdelivr.net/npm/vuetify@0.14.11/dist/vuetify.min.css

**Comment by nekosaur** [comment]
The unpkg link loads just fine for me.

**Comment by MartinKolarik** [comment]
It works for me too, but lots of people have been complaining about random 404 and 503 unpkg responses recently.

**Comment by nekosaur** [comment]
Ah, well that seems like an unpkg problem. https://twitter.com/unpkg/status/895882834656632833
