### ISSUE TITLE
[Bug Report][2.5.1] width/max-width prop does not apply to v-snackbar

### ISSUE THREAD

**Issue by setaman** [vuetifyjs/vuetify#13714]
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.85
**OS:** Linux x86_64

### Steps to reproduce
Set `width` or `max-width` prop to `<v-snackbar/>` to control the width of the component, (e.g.  `<v-snackbar width="100px"/>` )

### Expected Behavior
The specified width applies to the visible part of the component

### Actual Behavior
The width of the component is overwritten by `.v-snack__wrapper { min-width: 344px; ... }`

### Reproduction Link
<a href="https://codepen.io/Igelex/pen/wvJqYYj" target="_blank">https://codepen.io/Igelex/pen/wvJqYYj</a>

**Comment by stickpro** [comment]
try use min-width

**Comment by erthi16** [comment]
Width less than min-width has no effect.  You could, as @stickpro said, redefine a new value for min-width at "initial" or "0"
:min-width="initial"
or
:min-width="0"

**Comment by setaman** [comment]
@erthi16 @stickpro 
Thanks for the tip, yes it works. I'm still not happy, just because the [doc says](https://vuetifyjs.com/en/api/v-snackbar/#props-max-width) "Sets the maximum width for the component". But it does not, and works only in conjunction with `min-width`. I think this should be considered as bug and fixed, or should be stated in the documentation.

**Comment by johnleider** [comment]
Snackbar has a min width applied that you must overwrite:

https://play.vuetifyjs.com/#eNqlUstO6zAQ/ZWRNxSpiUu7uYoK4n4HYeHGU2qIH7InoajKv+O4SRoKCyR2njnjOQ/76cT+O5e3DbKCbQm1qwXhQ2kAtm0mnEvHVGihzFClurKGYgs97OtGyQlKYDCietsJf2kCaCuxzlpRNzhvvytJh/uS3a1K9mVcmWzEREP2K1pocZzgfz9cPaB6OVAE16srtCCl0TY9lt3NoZkFgNMJCI8EXTczxi/OLlHE5pTFGFfsTXn1xTnJLZ8lHMtQeeUoDeHRWU8gcS+amuB03iMFiQIWt3D/AIuhBzBKKIB8g8ux3cst4CaFAtJiAGMJInP9AWRBIxSLm2G6u02H6G3LJxVsyZTuZUTtLn8N1sRPkVjLAQglK0ZtJYu/pq9LdiByoeC8kiZei6+sWp8bJG6c5o9xjPvG9Kln0urHTb7JV9kOSeQbLlWgOZpj0NnO2/eAPu4q2SA4sZHaf/yCcZiMROt8fWYYWlktdqGn+LaaR74WfebRSPTof2vs6toP5q4mvhkc3qGL6dfKvIWr4KuQQn8atf7JeVrWb3ruCbslm8uNAtI99vwJeJ5IZg==

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
