### ISSUE TITLE
[Bug Report][2.5.1] v-carousel slide animation with 2 slides isn't consistent with carousels that have more slides

### ISSUE THREAD

**Issue by estreiten** [vuetifyjs/vuetify#13710]
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
1. Click on the ➡ button of the carousel until you reach the last slide.
2. Click on the ➡ button again to reach the first slide.

### Expected Behavior
The transition from the last slide to the first slide should be as same as from any slide to the next slide.

### Actual Behavior
The transition from the last slide to the first slide on a carousel with two slides isn't as same as from the first slide to the last slide.

### Reproduction Link
<a href="https://codepen.io/estreiten/pen/xxqLEJB" target="_blank">https://codepen.io/estreiten/pen/xxqLEJB</a>

### Other comments
Included also an example of a carousel with 5 slides where the transition from the last slide to the first slide works as expected.
It works ok with carousels of 3+ slides, the inconsistency only happens with carousels that have only two slides.

**Comment by zjdd** [comment]
Seems like it not fixed yet, my solution is just adding 2x2 items.

**Comment by estreiten** [comment]
Hi @zjdd ! Please, help me understand your solution. 
Are you using 2 items per slide in two slides, making for 4 items?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
