### ISSUE TITLE
[Bug Report][2.5.1] g/j letters are clipping on v-text-field hint in last line (if more than one line)

### ISSUE THREAD

**Issue by escapedcat** [vuetifyjs/vuetify#13712]
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create an input with a persistent-hint which is longer than one line. Use the letter "g" in the second line of the hint. The lower part of the "g" is being clipped.  
The reason might be that font-size and line-height both are 12px.

### Expected Behavior
Letter "g" is not being clipped if it's in the last line of the hint.

### Actual Behavior
Letter "g" is being clipped if it's in the last line of the hint.

### Reproduction Link
<a href="https://codepen.io/escapedcat/pen/VwpzWQd" target="_blank">https://codepen.io/escapedcat/pen/VwpzWQd</a>

### Other comments
Might be related to this old issue: https://github.com/vuetifyjs/vuetify/issues/4655

**Comment by erthi16** [comment]
Yes it seems in Firefox (but not in Chrome or Edge on my Windows) that the line height is the problem.  Using a 1.5 line-height like vuoriliikaluoma said, instead of the 12px, corrects the bug (Vuetify 2.4.4).

**Comment by johnleider** [comment]
This looks correct on all browsers for me. Can anyone on @vuetifyjs/core-team reproduce?

**Comment by escapedcat** [comment]
![image](https://user-images.githubusercontent.com/1016218/125724039-0ba59b91-6a98-4460-9efa-560c6984dee8.png)
The issue still exists. Look closely at the `g`.

Browser: Version 91.0.4472.114

**Comment by johnleider** [comment]
This is resolved as of v3.

Closing as stale because v2 is now in maintenance mode.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
