### ISSUE TITLE
[Bug Report][2.5.1] v-select broken after upgrade to 2.5.1

### ISSUE THREAD

**Issue by albanm** [vuetifyjs/vuetify#13729]
### Environment
**Vuetify Version:** 2.5.1
**Last working version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
Create a v-select with multiple, item-text and item-value options. Click on the select, the model is not modified.

### Expected Behavior
model modified

### Actual Behavior
nothing

### Reproduction Link
<a href="https://codepen.io/albanm/pen/gOmXEmG" target="_blank">https://codepen.io/albanm/pen/gOmXEmG</a>

**Comment by stickpro** [comment]
add props return-object

**Comment by albanm** [comment]
But I don't want to return an object. I want to return the value property only, and it works fine in 2.5.0.

**Comment by jacekkarczmarczyk** [comment]
workaround https://codepen.io/jkarczm/pen/VwproaQ

**Comment by albanm** [comment]
the workaround works well, thanks

**Comment by albanm** [comment]
Thanks for the fix, do you know when this will be released ?

**Comment by KaelWD** [comment]
We release patches on tuesdays.
