### ISSUE TITLE
[Bug Report][2.4.11] Inconsistent behaviour of 'x more' in v-calendar month view when switching or filtering large data-sets

### ISSUE THREAD

**Issue by vandrongelen** [vuetifyjs/vuetify#13720]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. In mounted function load `this.events = this.dataset1`. After saving the page is loaded perfectly.
2. In mounted function load `this.events = this.dataset2`. After saving the page is loaded perfectly too.
3. In mounted function load `this.events = this.dataset1`. After saving click the 'switch dataset' button. Strange behaviour appears on the 12th of May.

### Expected Behavior
Consistency on how 'x more' is displayed and consistency in the amount of events that are displayed before 'x more' is displayed.

### Actual Behavior
When initial data-set is loaded there is nothing wrong. The strange behaviour of 'x more' happens when switching from one data-set to another data-set.

### Reproduction Link
<a href="https://codepen.io/keesvandrongelen/pen/dyvRXyd" target="_blank">https://codepen.io/keesvandrongelen/pen/dyvRXyd</a>

### Other comments
Might be related to issue #12767

**Comment by jacekkarczmarczyk** [comment]
#12767 is not fixed by the PR so might be a different bug
