### ISSUE TITLE
[Bug Report][2.5.1] There is a difference in the order of class between minified and non-minified CSS.

### ISSUE THREAD

**Issue by snize** [vuetifyjs/vuetify#13732]
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Edge 91.0.864.37
**OS:** Windows 10

### Steps to reproduce
1. Download vuetify-v2.5.1.zip form relese and extract.
2. Compare the order of the CSS classes.

### Expected Behavior
Minified CSS and non-minified CSS classes should have the same CSS class priority.

### Actual Behavior
In vuetify-v2.5.1.css, Class  `.v-list-group .v-list-group__header .v-list-item__icon.v-list-group__header__append-icon` is loaded first and `.v-application--is-ltr .v-list-item__icon:last-of-type:not(:only-child)` is loaded later. 

But in vuetify-v2.5.1.min.css `.v-application--is-ltr .v-list-item__icon:last-of-type:not(:only-child)` is loaded first and `.v-list-group .v-list-group__header .v-list-item__icon.v-list-group__header__append-icon` is loaded later.

Also, in the [reproduction project](https://github.com/snize/vuetify-loader-test/blob/master/dist/css/chunk-vendors.29778e39.css) for this issue, Class  `.v-list-group .v-list-group__header .v-list-item__icon.v-list-group__header__append-icon` is loaded first and `.v-application--is-ltr .v-list-item__icon:last-of-type:not(:only-child)` is loaded later.

### Reproduction Link
<a href="https://github.com/snize/vuetify-loader-test/blob/master/dist/css/chunk-vendors.29778e39.css" target="_blank">https://github.com/snize/vuetify-loader-test/blob/master/dist/css/chunk-vendors.29778e39.css</a>

**Comment by snize** [comment]
This problem seems to be caused by a bug in webpack. https://github.com/webpack/webpack/issues/7094

After applying the patch provided at https://github.com/webpack/webpack/issues/7094#issuecomment-824996535 and building Vuetify, the CSS classes seem to be in the correct order.

**Comment by KaelWD** [comment]
Does this cause any visual problems?

**Comment by snize** [comment]
Yes, it does cause visual problem. In my case, the margins applied have changed due to the reordering of the classes. The following is not a complete reproduction, but the meaning is the same.

https://codepen.io/snize/pen/WNjNMRO

![2021-06-29-15-38-25_w-h](https://user-images.githubusercontent.com/185991/123750859-06a39080-d8f2-11eb-98dc-f79fd5d68f96.gif)

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/81dfbf8e4ac6bf6fbbc0e61e121245a4e68f56bf/packages/vuetify/src/components/VList/VListItem.sass#L119-L128 and https://github.com/vuetifyjs/vuetify/blob/60844a32f51b3f4bd73811fd2b6997293744d099/packages/vuetify/src/components/VList/VListGroup.sass#L5-L10 both have the same specificity. They're both kinda incorrect - the min-width should be 24 not 48, and there's already a 16px margin set elsewhere that's then overridden and added back on.
