### ISSUE TITLE
[Bug Report][2.5.2] Range slider can no longer select same value with both slider handles

### ISSUE THREAD

**Issue by rwhite-flux** [vuetifyjs/vuetify#13738]
### Environment
**Vuetify Version:** 2.5.2
**Vue Version:** 2.6.12
**Browsers:** Firefox 88.0
**OS:** Mac OS 10.15

### Steps to reproduce
* Create a VRangeSlider
* Define a model (values don't matter)
* Try to select the same value with both slider handles

### Expected Behavior
User should be able to select the same value for both slider handles.

### Actual Behavior
The v-range-slider component no longer allows users to select a range delta of 0.  Minimum range delta is now 1.

### Reproduction Link
<a href="https://codepen.io/rwhite-flux/pen/PopEvgz?editors=101" target="_blank">https://codepen.io/rwhite-flux/pen/PopEvgz?editors=101</a>

### Other comments
This functionality used to work, but I'm not certain which Vuetify version it broken in.  I found multiple old bug tickets from 2019 where it seems a similar issue was fixed:
https://github.com/vuetifyjs/vuetify/issues/8756
https://github.com/vuetifyjs/vuetify/issues/9330

It is still possible to set the same value programmatically, but not through the UI by dragging the range slider handles.

**Comment by KaelWD** [comment]
Broken in v2.4.6 by ed0b0ca7a0ab81671a0757d8d2c00b104c61b245
