### ISSUE TITLE
[Bug Report][2.5.1] Autocomplete menu's closes for Escpae but the search-input not cleared

### ISSUE THREAD

**Issue by Nagyjano** [vuetifyjs/vuetify#13730]
### Environment
**Vuetify Version:** 2.5.1
**Last working version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Firefox 88.0
**OS:** Windows 10

### Steps to reproduce
Type 'item' in the field and it will contains all 4 items. Choose any items based of you choice. If you click outside than selected items remain and search text cleared. Now if you type again 'item' and press Escape

### Expected Behavior
The search text cleared

### Actual Behavior
The search text remains

### Reproduction Link
<a href="https://codepen.io/nagyjano/pen/WNpXmda" target="_blank">https://codepen.io/nagyjano/pen/WNpXmda</a>

### Other comments
Using search-input prop and @keydown handler I can clear manually the search input, but would be better to do it by itself

**Comment by KaelWD** [comment]
> Last working version: 2.4.11

Esc doesn't clear the input in this version either, I even tried v1.5.24 and it has the same behaviour.

**Comment by KaelWD** [comment]
The aria practices say clearing on esc is optional, so I guess it's this way so the choice is up to you. `search-input` + `@keydown` is an appropriate way to handle this. 

https://www.w3.org/TR/wai-aria-practices/#textbox-keyboard-interaction

**Comment by Nagyjano** [comment]
Thanks @KaelWD ! You are right it worked like this just our test solution changed. :)
