### ISSUE TITLE
[Bug Report] sass:math error when using custom variables

### ISSUE THREAD

**Issue by flahol** [vuetifyjs/vuetify#13737]
### Problem to solve
Error when compiling
 error  in ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/src/components/VSlider/VSlider.sass

Syntax Error: SassError: @use rules must be written before any other rules.
  ╷
4 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/src/components/VSlider/VSlider.sass 4:1  root stylesheet

 @ ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/src/components/VSlider/VSlider.sass 4:14-362 15:3-20:5 16:22-370
 @ ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/lib/components/VSlider/VSlider.js
 @ ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/lib/components/VSlider/index.js
 @ ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/lib/components/index.js
 @ ./node_modules/.pnpm/vuetify@2.5.2_vue@2.6.13/node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi ./node_modules/.pnpm/webpack-dev-server@3.11.2_webpack@4.46.0/node_modules/webpack-dev-server/client?http://192.168.1.151:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by KaelWD** [comment]
Workaround is to load your custom variables with `@use` instead of `@include`. If you're using vue-cli-plugin-vuetify you need to move the variables file out of the watched folders (`src/styles`, `src/sass`, or `src/scss`) and add the following to your vue.config.js:
```js
css: {
  loaderOptions: {
    sass: { additionalData: '@use "@/variables.scss" as *' },
    scss: { additionalData: '@use "@/variables.scss" as *;' },
  }
}
```

**Comment by flahol** [comment]
@KaelWD 
You porposed solution works, thanks

**Comment by wemod123** [comment]
how to workaround when using @nuxtjs/vuetify module

**Comment by jscottsf** [comment]
This issue just blew up my project. Also interested in `@nuxtjs/vuetify` solution. Thx for opening this. :)

**Comment by jscottsf** [comment]
This could be of interest.

https://github.com/nuxt-community/vuetify-module/issues/450

**Comment by mlockett42** [comment]
@KaelWD 's solution unfortunately did not work for me and I had to force back to version 2.5.1 in my package.json (which worked)

**Comment by polymer-coder** [comment]
@mlockett42 even after forcing my dependency to 2.5.1, deleting node_modules and package-lock.json then running npm install, I've had no luck

**Comment by tony-wong-aurizon** [comment]
this is a bit hard to fix when other modules in my repo are using vuetify and they are all breaking currently

**Comment by inane** [comment]
> @mlockett42 even after forcing my dependency to 2.5.1, deleting node_modules and package-lock.json then running npm install, I've had no luck

Same scenario and same result..

**Comment by inane** [comment]
`[npm install vuetify@2.5.1
npm install sass@1.32.13](url)`

**Comment by domness** [comment]
Looks like this needs resolving given that the documentation is now incorrect:

"Once installed, create a folder called sass, scss or styles in your src directory with a file named variables.scss or variables.sass. The vuetify-loader will automatically bootstrap your variables into Vue CLI’s compilation process, overwriting the framework defaults."

> @KaelWD
> Hello.
> I tried to do as you suggested. My app can build fine, but all scss variables do not work. No one of them change my HTML style on my app. My variables.scss is only:
> @import url('https://fonts.googleapis.com/css?family=Livvic&display=swap');
> $body-font-family: 'Livvic', sans-serif;

Same with me.

**Comment by Dickens-Shaw** [comment]
> This works for me:
> 
> npm install vuetify@2.5.1
> npm install sass@1.32.13

it works

**Comment by Oleksii14** [comment]
I am trying to migrate to vuetify 2.5.2 and sass 1.33, but I am still receving the "sass:math" errors in the console

```
"dependencies": {
    "@mdi/js": "5.9.55",
    "@vue/composition-api": "1.0.0-rc.10",
    "axios": "0.21.1",
    "core-js": "3.13.1",
    "date-fns": "2.22.1",
    "pinia": "0.5.1",
    "typeface-montserrat": "1.1.13",
    "vue": "2.6.13",
    "vue-i18n": "8.24.4",
    "vue-router": "3.5.1",
    "vuetify": "2.5.2"
  },
  "devDependencies": {
    "@types/electron-devtools-installer": "2.2.0",
    "@types/jest": "26.0.23",
    "@types/mocha": "8.2.2",
    "@typescript-eslint/eslint-plugin": "4.26.0",
    "@typescript-eslint/parser": "4.26.0",
    "@vue/cli-plugin-babel": "5.0.0-beta.1",
    "@vue/cli-plugin-e2e-webdriverio": "5.0.0-beta.1",
    "@vue/cli-plugin-eslint": "5.0.0-beta.1",
    "@vue/cli-plugin-router": "5.0.0-beta.1",
    "@vue/cli-plugin-typescript": "5.0.0-beta.1",
    "@vue/cli-plugin-unit-jest": "5.0.0-beta.1",
    "@vue/cli-service": "5.0.0-beta.1",
    "@vue/eslint-config-prettier": "6.0.0",
    "@vue/eslint-config-typescript": "7.0.0",
    "@vue/test-utils": "1.2.0",
    "chromedriver": "90.0.1",
    "cross-env": "7.0.3",
    "electron": "13.0.1",
    "electron-devtools-installer": "3.2.0",
    "eslint": "7.27.0",
    "eslint-plugin-prettier": "3.4.0",
    "eslint-plugin-vue": "7.10.0",
    "lint-staged": "11.0.0",
    "prettier": "2.3.0",
    "sass": "1.33.0",
    "sass-loader": "12.0.0",
    "spectron": "15.0.0",
    "ts-node": "10.0.0",
    "typescript": "4.3.2",
    "vue-cli-plugin-electron-builder": "2.0.0",
    "vue-cli-plugin-vuetify": "2.4.0",
    "vue-template-compiler": "2.6.13",
    "vuetify-loader": "1.7.2",
    "wdio-chromedriver-service": "7.1.0"
  },
```

vue.config.js

```
module.exports = {
  css: {
    loaderOptions: {
      scss: { additionalData: `@use "@/styles/variables.scss" as *;` },
    },
  },
};

```

**Comment by Dickens-Shaw** [comment]
> I am trying to migrate to vuetify 2.5.2 and sass 1.33, but I am still receving the "sass:math" errors in the console
> 
> ```
> "dependencies": {
>     "@mdi/js": "5.9.55",
>     "@vue/composition-api": "1.0.0-rc.10",
>     "axios": "0.21.1",
>     "core-js": "3.13.1",
>     "date-fns": "2.22.1",
>     "pinia": "0.5.1",
>     "typeface-montserrat": "1.1.13",
>     "vue": "2.6.13",
>     "vue-i18n": "8.24.4",
>     "vue-router": "3.5.1",
>     "vuetify": "2.5.2"
>   },
>   "devDependencies": {
>     "@types/electron-devtools-installer": "2.2.0",
>     "@types/jest": "26.0.23",
>     "@types/mocha": "8.2.2",
>     "@typescript-eslint/eslint-plugin": "4.26.0",
>     "@typescript-eslint/parser": "4.26.0",
>     "@vue/cli-plugin-babel": "5.0.0-beta.1",
>     "@vue/cli-plugin-e2e-webdriverio": "5.0.0-beta.1",
>     "@vue/cli-plugin-eslint": "5.0.0-beta.1",
>     "@vue/cli-plugin-router": "5.0.0-beta.1",
>     "@vue/cli-plugin-typescript": "5.0.0-beta.1",
>     "@vue/cli-plugin-unit-jest": "5.0.0-beta.1",
>     "@vue/cli-service": "5.0.0-beta.1",
>     "@vue/eslint-config-prettier": "6.0.0",
>     "@vue/eslint-config-typescript": "7.0.0",
>     "@vue/test-utils": "1.2.0",
>     "chromedriver": "90.0.1",
>     "cross-env": "7.0.3",
>     "electron": "13.0.1",
>     "electron-devtools-installer": "3.2.0",
>     "eslint": "7.27.0",
>     "eslint-plugin-prettier": "3.4.0",
>     "eslint-plugin-vue": "7.10.0",
>     "lint-staged": "11.0.0",
>     "prettier": "2.3.0",
>     "sass": "1.33.0",
>     "sass-loader": "12.0.0",
>     "spectron": "15.0.0",
>     "ts-node": "10.0.0",
>     "typescript": "4.3.2",
>     "vue-cli-plugin-electron-builder": "2.0.0",
>     "vue-cli-plugin-vuetify": "2.4.0",
>     "vue-template-compiler": "2.6.13",
>     "vuetify-loader": "1.7.2",
>     "wdio-chromedriver-service": "7.1.0"
>   },
> ```
> 
> vue.config.js
> 
> ```
> module.exports = {
>   css: {
>     loaderOptions: {
>       scss: { additionalData: `@use "@/styles/variables.scss" as *;` },
>     },
>   },
> };
> ```

try vuetify@2.5.1 & sass@1.32.13

**Comment by Dickens-Shaw** [comment]
@Oleksii14 try vuetify@2.5.1 & sass@1.32.13

**Comment by Oleksii14** [comment]
@Dickens-Shaw my question is how to migrate correctly, not to use the old version of those deps 😄

**Comment by Dickens-Shaw** [comment]
@Oleksii14 got it! I tried as well, but give up now!😭

**Comment by Oleksii14** [comment]
@KaelWD any ideas?

**Comment by Oleksii14** [comment]
@KaelWD can you take a look at my package file and tell me what may be wrong there? How can I migrate to sass 1.34 and vuetify 2.5.3 correctly?

**Comment by KaelWD** [comment]
You can't, see https://github.com/vuetifyjs/vuetify/issues/13694#issuecomment-852957010
