### ISSUE TITLE
[Bug Report][2.4.0] The sub-group icon is not displayed in mini-variant drawer

### ISSUE THREAD

**Issue by keyvanmatinrad** [vuetifyjs/vuetify#13735]
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.5.1
**Vue Version:** 2.6.12
**Browsers:** Firefox 88.0
**OS:** Windows 10

### Steps to reproduce
I created a drawer using v-navigation-drawer that uses mini-variant. The problem is that sub-group item icons are not displayed in mini-variant mode. In this case "Dinosaurs" item has an icon but is not displayed in mini-variant mode.

### Expected Behavior
Expect the sub-group icon to be displayed in the mini-variant.

### Actual Behavior
sub-group item icon is not displayed in mini-variant mode.

### Reproduction Link
<a href="https://codepen.io/keyvanmatinrad/pen/ExWooMb" target="_blank">https://codepen.io/keyvanmatinrad/pen/ExWooMb</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
