### ISSUE TITLE
[Bug Report][2.5.2] VPagination: onResize() does not work properly if parentElement is wrapped in flex container

### ISSUE THREAD

**Issue by kakenbok** [vuetifyjs/vuetify#13739]
![image](https://user-images.githubusercontent.com/491557/120434745-21c7c280-c37d-11eb-988c-1ca74f004d64.png)

### Environment
**Vuetify Version:** 2.5.2
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.77
**OS:** Linux x86_64

### Steps to reproduce
The maxButtons value of VPagination is calculated in respect to the initial width of the containing parentElement. If that parentElement is part of a flex container, it's initial width will be the same as its initial content. If more pagination buttons should be displayed (`length` increases), the initial width will be kept using, so not all buttons are being displayed.

### Expected Behavior
All Buttons are shown

### Actual Behavior
Buttons are missing

### Reproduction Link

<a href="https://jsfiddle.net/kakenbok/tobfn9xj/" target="_blank">https://jsfiddle.net/kakenbok/tobfn9xj/</a>

**Comment by cafedo** [comment]
Hi all; I am experimenting the same issue.. Is there any news?

**Comment by KaelWD** [comment]
Not feasible to fix, there's no built-in way to check "how much this element can grow by without overflowing"
