### ISSUE TITLE
[Bug Report][2.5.3] Invalid solution posted for sass warnings

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#13749]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
I'm reverting the fix for this, it completely broke projects that were injecting custom sass variables (#13737). To silence the warnings, install sass@~1.32

If you have any other questions, please join the Discord chat room.

Originally posted by @KaelWD in #13694 (comment)
----------------------------------
Sorry to post a new ticket but the original ticket is locked.
This is not a correct statement. Using sass version 1.32.13 also causes this issue.  The solution is to lock sass at the highest version of 1.32.12

In package.json

 "sass": "1.32.12"

### Expected Behavior
Wrong sass version proposed as solution

### Actual Behavior
Correct sass version proposed as solution

### Reproduction Link
<a href="https://codepen.com" target="_blank">https://codepen.com</a>

**Comment by KaelWD** [comment]
> Using sass version 1.32.13 also causes this issue

No it doesn't. The deprecation was introduced in 1.33.0
![image](https://user-images.githubusercontent.com/16421948/120656753-3adc8a80-c4c7-11eb-8845-d76eefc88e56.png)

**Comment by UglyHobbitFeet** [comment]
Unfortunately, it does and was introduced also for 1.32.13.  Feel free to
try it. It barfs on my end with the errors. Also is happening for other
users on the discord forum.

**Comment by jsodeman** [comment]
Thank you for this. I had the ^ also and it was driving me crazy trying to figure out what the fix wasn't working.
