### ISSUE TITLE
[Bug Report][2.5.3] v-card-text inside div results in incorrect card text style

### ISSUE THREAD

**Issue by tbra91** [vuetifyjs/vuetify#13745]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Firefox 89.0
**OS:** Windows 10

### Steps to reproduce
Add a v-card with a div containing a v-card-text

### Expected Behavior
Text is styled as "secondary" text

### Actual Behavior
Text is styled as "primary" text

### Reproduction Link
<a href="https://codepen.io/tbra/pen/ZEerway" target="_blank">https://codepen.io/tbra/pen/ZEerway</a>

**Comment by erthi16** [comment]
the text color of v-card-text is applied if it is a direct descendent of v-card... what was the reason for this and is it still relevant because the v-card-subtitle lack the direct descendant!

.theme--light.v-card .v-card__subtitle,
.theme--light.v-card>.v-card__text {
    color: rgba(0,0,0,.6);
}

**Comment by KaelWD** [comment]
#7920. This is one of the limitations of the v2 theme system that has been fixed in vuetify 3. 

Subtitle was added in 079904031b93b17e7c6bcd2a14405bc2bf4e91a4, probably just an oversight.
