### ISSUE TITLE
[Bug Report][2.5.3] VSelect Keyboard navigation incorrect on first opening with preexistant value

### ISSUE THREAD

**Issue by alarai** [vuetifyjs/vuetify#13747]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.77
**OS:** Windows 10

### Steps to reproduce
Click on the v-select to open it, then use hte up/down arrow key to navigate the options.

### Expected Behavior
It is expected that arrow key up/down will change the selection to he previous/next value in the select.

### Actual Behavior
The selection actually starts as if nothing was selected, starting by selecting the first or last item of the select when pressing up/down arrow.

### Reproduction Link
<a href="https://codepen.io/avandoorine/pen/BaWYXyr" target="_blank">https://codepen.io/avandoorine/pen/BaWYXyr</a>

### Other comments
Please note that this only happens when opening the field for the first time, on subsequent opening the behaviour is correct.

**Comment by matobeno1** [comment]
Works in Vuetify 2.5.9

**Comment by KaelWD** [comment]
Fixed in v2.5.6 by 8c0e2bcce1c9ccd64cbf5f5d085d2ca9becbac3c
