### ISSUE TITLE
[Bug Report][2.5.2] failure to position menu in main app bar

### ISSUE THREAD

**Issue by albanm** [vuetifyjs/vuetify#13740]
### Environment
**Vuetify Version:** 2.5.2
**Last working version:** 2.5.1
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.77
**OS:** Linux x86_64

### Steps to reproduce
Create a menu to the right of a app bar. The menu used to be opened to the left on its own, now it i opened to the right and so not visible. Also it is impossible to force displaying to the left.

### Expected Behavior
display menu to the left

### Actual Behavior
menu displayed to the right

### Reproduction Link
<a href="https://codepen.io/albanm/pen/oNZELeX" target="_blank">https://codepen.io/albanm/pen/oNZELeX</a>

**Comment by KaelWD** [comment]
> offsetParent returns null in the following situations: [...] The element has the position property set to fixed

**Comment by albanm** [comment]
Thanks. From what you told me on the previous issue I suppose this will be released next tuesday. I think it is quite a big regression, maybe an early relase is warranted ?

**Comment by KaelWD** [comment]
I'm doing another release today to fix the new sass issues anyway.
