### ISSUE TITLE
[Bug Report][2.5.2] Hidden text field shows border

### ISSUE THREAD

**Issue by ionesculiviucristian** [vuetifyjs/vuetify#13741]
### Environment
**Vuetify Version:** 2.5.2
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
Use a hidden input

### Expected Behavior
Not to see a border

### Actual Behavior
Border is visible though the input is hidden

### Reproduction Link
<a href="https://codepen.io/liviuionescu/pen/BaWYQKB" target="_blank">https://codepen.io/liviuionescu/pen/BaWYQKB</a>

**Comment by KaelWD** [comment]
There's no reason to use type="hidden" on a v-text-field.
