### ISSUE TITLE
[Bug Report][2.4.0] mdi-cross icon doesn't load

### ISSUE THREAD

**Issue by Igal-Kleiner** [vuetifyjs/vuetify#13750]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
Create v-icon element.
Pass `mdi-cross` as icon text
```lang-html
<v-icon color='blue-grey darken-2' large>
  mdi-cross
</v-icon>
```

### Expected Behavior
Should display [this MDI cross icon](https://materialdesignicons.com/icon/cross)

### Actual Behavior
Icon doesn't appear.

### Reproduction Link
<a href="https://codepen.io/igal-kleiner/pen/zYZWqJR?editors=101" target="_blank">https://codepen.io/igal-kleiner/pen/zYZWqJR?editors=101</a>

### Other comments
Just as an example, `mdi-shield-cross` does work and the icon is shown.

**Comment by KaelWD** [comment]
That doesn't exist in the release version for some reason, open an issue on the mdi repo or use `mdi-christianity`
