### ISSUE TITLE
[Feature Request] v-file-input support upload massive number of files?

### ISSUE THREAD

**Issue by cometta** [vuetifyjs/vuetify#13759]
### Problem to solve
I upload 300k total number of files using v-file-input on version 2.4.11. it works, but the browser prompted 'page is not responsive, you can wait for it become responsive or exit the page' . Any advice on how to modify v-file-input so that it support more files? I already set showSize to false. Is this due to when the even fired, the onChange file [] array parameter has too many files?

**Comment by jacekkarczmarczyk** [comment]
Is the page responsive if you load 300k files in native input? https://codepen.io/jkarczm/pen/ExWLOao

**Comment by cometta** [comment]
@jacekkarczmarczyk , i tested 435053 files, not responsive. i captured the screenshot, i added few parameters,   'directory webkitdirectory'
![ice_screenshot_20210606-222416](https://user-images.githubusercontent.com/187495/120928158-14f8f500-c716-11eb-8d18-df920e712c46.png)
![ice_screenshot_20210606-221023](https://user-images.githubusercontent.com/187495/120928170-1f1af380-c716-11eb-8eea-a328eb8005e7.png)

**Comment by jacekkarczmarczyk** [comment]
Then there's nothing we can do
