### ISSUE TITLE
[Bug Report][2.5.3] items-per-page-options array with only one option pushes v-data-table footer to the left

### ISSUE THREAD

**Issue by teammate-james** [vuetifyjs/vuetify#13751]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
As of v2.5.x, if you set the `items-per-page-options` array for `footer-props` on a `v-data-table` to a single option (i.e. `items-per-page-options: [5]`), then the footer, which is normally right-aligned, becomes left-aligned.

It appears that the difference is in the `.v-data-footer` CSS class. As of v2.5.x, the `.v-data-footer` class no longer has the following setting:

```
justify-content: flex-end
```

This link shows the behavior on v2.4.x:
[https://codepen.io/teammate-james/pen/mdWMbvX](https://codepen.io/teammate-james/pen/mdWMbvX)

This link shows the behavior on v2.5.x:
[https://codepen.io/teammate-james/pen/QWpMLPP](https://codepen.io/teammate-james/pen/QWpMLPP)

### Expected Behavior
VDataTable Footer aligned to right

### Actual Behavior
VDataTable Footer aligned to left

### Reproduction Link
<a href="https://codepen.io/teammate-james/pen/QWpMLPP" target="_blank">https://codepen.io/teammate-james/pen/QWpMLPP</a>

**Comment by robbevp** [comment]
I reported a simnilar problem, with probably the same source: https://github.com/vuetifyjs/vuetify/issues/13678

**Comment by ecasetracker** [comment]
A work around is to add a `footer.prepend` slot with a `v-spacer`

```html
      <template #footer.prepend>
        <v-spacer/>
      </template>
```

However, I also noticed that the footer height shrinks when the items-per-page select is hidden. Not sure if that is intended or not.

**Comment by douglasg14b** [comment]
Also noticing this issue.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
