### ISSUE TITLE
[Bug Report][2.5.3] Vuetify data table grouping with paging not working as i expected

### ISSUE THREAD

**Issue by Kiilse** [vuetifyjs/vuetify#13754]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.77
**OS:** Linux x86_64

### Steps to reproduce
Set a normal data-table with grouping

### Expected Behavior
After collapsing the first header, I would think the next group header would appear with enough rows to fill the page. Instead, you have to page through several "empty" pages (the number of pages corresponds to the number of rows in the first grouping).

### Actual Behavior
If you want to collapse all group headers, you have to page through was appears to be empty pages until you get to the next group header.

### Reproduction Link
<a href="https://codepen.io/vccampbell/pen/MWypbbb" target="_blank">https://codepen.io/vccampbell/pen/MWypbbb</a>

### Other comments
 How can I configure the grouping which will bring the next grouping into view when I collapse the previous grouping?

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3;
