### ISSUE TITLE
[Bug Report][2.5.3] v-navigation-drawer with expand-on-hover throws console errors when hovered

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#13755]
### Environment
**Vuetify Version:** 2.5.3
**Last working version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.77
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use `v-navigation-drawer` with `expand-on-hover` and `mini-variant`

### Expected Behavior
Navigation drawer expands and contracts

### Actual Behavior
Navigation drawer expands and contracts but throws the following console error
```
index.js:245 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at VueComponent.checkActivatorFixed (index.js:245)
    at VueComponent.updateDimensions (index.js:338)
```
in `packages/vuetify/src/mixins/menuable/index.ts`

### Reproduction Link
<a href="https://codepen.io/kotoriii/pen/zYZWyXB" target="_blank">https://codepen.io/kotoriii/pen/zYZWyXB</a>

### Other comments
The Codepen I linked does not reproduce the issue, even though I tried using as many components as I'm currently using. It's hard to reproduce my local stack, but error is caused by these added lines in `beforeMount()` and `beforeDestroy()` in this PR's recent file changes:
https://github.com/vuetifyjs/vuetify/pull/13670/files#diff-a510753fb8a85de8db6181b6c250d80bcccbf5fa2d4a97e5660e233bfc718200R193

**Comment by KaelWD** [comment]
If it's being thrown from menuable, do you have something with a menu in your drawer?

**Comment by Kotoriii** [comment]
@KaelWD The drawer has `v-menus`. I just removed them but the errors are still appearing

**Comment by Tofandel** [comment]
From your description it just looks like it's coming from https://github.com/vuetifyjs/vuetify/blob/ec8fafa9e785f6817bf6d0058a6953b0091a1370/packages/vuetify/src/mixins/menuable/index.ts#L287

But doesn't directly looks related to the PR

It would be nice to know exactly what is the value of el when it throws this error, can you put a breakpoint on this line and check the browser debugger before it throws the error?

**Comment by Kotoriii** [comment]
Sorry for the late response. Thank you @KaelWD and @Tofandel 

<img width="1215" alt="Screenshot 2021-06-07 at 10 31 20" src="https://user-images.githubusercontent.com/6981718/120985230-b5cdcb80-c77b-11eb-9f29-9a16bde12c12.png">

The culprit seems to be a [Mixpanel](https://developer.mixpanel.com/docs/javascript-quickstart) button we integrated into our website. A user might be able to click it and choose to send a bug report or feedback.

This requires some script loading into the html headers and methods like

```
    window.onUsersnapCXLoad = function configureUsersnap(api) {
      api.init({
        button: {
          isHidden: true,
        },
      });
      window.UsersnapCX = api;
    };
```

However, how does this impact the navigation drawer? Why does this create an issue right now and not all other versions before? Anything I can attempt to solve this? Your help is much appreciated

**Comment by KaelWD** [comment]
I don't think that's what's causing it, it wouldn't have got to the debugger line. Try enabling "pause on exceptions" in the top right and see what the element that causes the error is.

**Comment by Kotoriii** [comment]
@KaelWD 

Thank you. I found the issue

<img width="990" alt="Screenshot 2021-06-07 at 11 42 31" src="https://user-images.githubusercontent.com/6981718/120995226-7dcb8600-c785-11eb-9a81-d1e491985beb.png">

There is a #comment node, which is a v-menu with a `show = false` attribute inside the data-table headers. Because the v-menu `show` is false, an HTML comment inside the `v-menu` HTML element will be rendered, which triggers this not of type Element error. It must have something to do with resizing the data-table and having to resize a "comment" element breaks the resizing methods. 

I will fix this issue on my end. Feel free to close this Issue, but perhaps but you guys want to handle this exception somehow on your end as well.

**Comment by Tofandel** [comment]
Okay so the issue stems from the resize listener, basically it fires even when the element is inactive right now

2 solutions, either add/remove the listener with a watcher or if not isActive return in updateDimensions

**Comment by Tofandel** [comment]
That's weird, https://codepen.io/tofandel-the-typescripter/pen/wvJXjRy even with a v-if the button is not a comment for me when the code runs

**Comment by Tofandel** [comment]
I managed to get a comment from the activator but for me it triggers another error..

So I think the best way forward is adding a check in `getActivator` if the element is a comment => return null
