### ISSUE TITLE
[Documentation] v-container API doesn't list `fill-height` attribute

### ISSUE THREAD

**Issue by avinoamsn** [vuetifyjs/vuetify#13753]
### Environment

**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
The `fill-height` attribute is only documented in the `v-container` section of the _Grids_ page ([link](https://vuetifyjs.com/en/components/grids/#v-container)). This should also be included on `v-container`'s API page.

### Expected Behavior
Field should be documented on the component's API page.

### Actual Behavior
Field is omitted on the component's API page.

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-container/#v-container-api" target="_blank">https://vuetifyjs.com/en/api/v-container/#v-container-api</a>

**Comment by MajesticPotatoe** [comment]
duplicate #8744
