### ISSUE TITLE
[Bug Report][2.2.11] V-simple-table appearing with no content for a little time.

### ISSUE THREAD

**Issue by karambaq** [vuetifyjs/vuetify#13766]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
Sorry for the fake link, I can't provide all my custom elements and call's to api, it's just the same structure.
I don't really know what causes this issue, and wonder how can I refactor my code to know this, maybe it's known bug but I don't sure how to call it, it's not a fouc.
Also I make sure that data already loaded from api, so it's not the case.
I've tried using v-cloak, but no luck.

### Expected Behavior
The table shows when fully ready.

### Actual Behavior
Table shows all headers but without content for a little amount of time.

https://user-images.githubusercontent.com/14233969/120934193-030f5600-c706-11eb-9fea-7ba8073aa224.mov

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-template-forked-bmobx?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-template-forked-bmobx?file=/src/App.vue</a>

**Comment by jacekkarczmarczyk** [comment]
> Also I make sure that data already loaded from api, so it's not the case.

Actually that's the case, table is displayed before data is loaded, so you see only headers, and the rows appear after data is loaded
