### ISSUE TITLE
[Bug Report][2.5.3] v-simple-table loading state

### ISSUE THREAD

**Issue by karambaq** [vuetifyjs/vuetify#13765]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
It's not really a bug, I'm trying to add loading state to v-simple-data using v-if, but it doesn't work, is there another way to do it?

### Expected Behavior
Shows loading state

### Actual Behavior
Empty table

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-template-forked-bmobx?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-template-forked-bmobx?file=/src/App.vue</a>

**Comment by jacekkarczmarczyk** [comment]
`v-simple-table` renders what you put in the default slot, if you want to display the loader you need to add it to the markup by yourself

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
