### ISSUE TITLE
[Feature Request] Allow breackpoint to 0 to hide element (good to have)

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#13768]
### Problem to solve
to hide element in specific element we need to set hidden class, but it would be great by simply assigning breakpoint value to 0.

### Proposed solution
`cols="0"  --> hiddden-xs-only` or
`sm="0"  --> hiddden-sm-and-up`

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
