### ISSUE TITLE
Dark mode request for v-expansion-panel

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#1376]
This is a feature request for a dark mode for expansion panels.

In cases where a dark background is used, the expansion panel toolbar divider and the expansion up / down icon become hard to see.

I can work around the separation of the header toolbar and content by manually adding a white divider, but it doesn't appear possible to change the colour of the up/down icon without changing the source code.

**Comment by johnleider** [comment]
Christmas came early.
