### ISSUE TITLE
v-select - option "auto" is not worked

### ISSUE THREAD

**Issue by chim666** [vuetifyjs/vuetify#1377]
### Steps to reproduce
1. Click on select

### Versions
Stopped working in the 0.14.9

### What is expected ?
Centers list on selected element. Highlight selected item.

### What is actually happening ?
Centers list on begin list. Not Highlight  selected item.

### Reproduction Link
https://codepen.io/anon/pen/braWEN?editors=1010#0

**Comment by johnleider** [comment]
Also keep in mind, while this is bugged currently, you are still missing the auto prop in this example.
