### ISSUE TITLE
[Feature Request] Custom caption slot for tables

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#13773]
### Problem to solve
Currently `v-data-table` offers a `caption` attribute however it would be helpful if the entire caption area was exposed as a slot for further customization, e.g. marking certain text as screen-reader only.

### Proposed solution
Expose a `caption` slot on `v-data-table` along with any other table elements that make sense, e.g. simple tables.

**Comment by dmcknight26** [comment]
As a workaround you can leverage the `header` slot, which still renders even if you use the `headers` property.

```
<template #header>
    <caption class="d-sr-only">Ice Cream Flavors</caption>
</template>
```

**Comment by lioneaglesolutions** [comment]
@johnleider @nekosaur any plans for this in LTS?

**Comment by johnleider** [comment]
I don't know if it's worth the cycles. I'd rather have his time be used on Vuetify 3's data table.
