### ISSUE TITLE
[Bug Report][2.5.3] Autocomplete small chips field alignment moves when not filled or focused

### ISSUE THREAD

**Issue by mhio** [vuetifyjs/vuetify#13778]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.14
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Mac OSX

### Steps to reproduce
Click to focus "Tags" field, underline moves to align with text field.
Click elsewhere to blur "Tags" field, underline moves out of alignment with text field. 
A field filled with chips stays in alignment with text field. 

### Expected Behavior
autocomplete field underline stays in the same position

### Actual Behavior
autocomplete field underline moves position down a couple of pixels. 

### Reproduction Link
<a href="https://codepen.io/mio8o8/pen/eYvjGNa" target="_blank">https://codepen.io/mio8o8/pen/eYvjGNa</a>

### Other comments
These issues seemed similar but are resolved:
https://github.com/vuetifyjs/vuetify/issues/10635
https://github.com/vuetifyjs/vuetify/issues/10877

**Comment by mhio** [comment]
Both `div.v-select_selections` elements have a `min-height: 26px` but the chip or focused input are 32px.

chip: 4mt + 24px + 4mt

focussed input: 8pt + 16px + 8pt

**Comment by s900mhz** [comment]
Does this still need someone to PR a fix? Is it fixed in V3? I experience this issue still but since I am stuck on 2.6 for now, I am not sure if it's present in the new version.

**Comment by lioneaglesolutions** [comment]
Resolved in V3

https://play.vuetifyjs.com/#eNqNUl1vwiAU/SuEFzVpS+KWLGmqcdnPEB+wvY1shRKg3abpf9+FtonTB30Czv0459zL/kLfjcn6DmhOCw/KNMLDlmtCij510EDpw4OQPlVtBc2G0140HXA6wrnEIodoPGe0PEnjxmsjjrHqI0JTXHWNl6YBrrnnvhdWCu0xqdMV2EZqqMbMbcFmFaipYFcC8elKK00IEAI/prWeVFALbE0uI00lvMjJckU2W7KcMEKi0pzsF3XbLhKyOAobjlqez/HZ4XlI5uzoFrNnZFjFyxDkTAJoQlHzl8s+XatxjpGJ09KhX6wc6zg9eW9czlhZaczEWcreZho800Yx3ICX9e/uJVtna1ZJ52coxQm6LDYLnQ5cD0goVTCcKmFuWMdAZJ4c48bCvvJHEnaYxmynvVSQVq2KWl7fRjFXeAZOpUfbfjuw2IXTaTKRJyh+guuRXaS4a82QrwebWgi/BOyzlm7K/tm6id1Zm1Y90CGhYx3OPoqmhz8KHRH2

Still seems to be a slight height change when selecting chips though (doesn't change on focus): https://github.com/vuetifyjs/vuetify/issues/17130
