### ISSUE TITLE
[Bug Report][2.5.3] iOS form input controls render issue

### ISSUE THREAD

**Issue by DamoClarkson** [vuetifyjs/vuetify#13772]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.77
**OS:** Windows 10

### Steps to reproduce
Create a simple radio group and then view in iOS safari. Focus an option so that it is highlighted and notice that the round border is sometimes showing a grey square border overlap. 

### Expected Behavior
Border will always be round and correct color

### Actual Behavior
Border is sometimes showing with square grey cut offs and this is randomly positioned and intermittent

### Reproduction Link
<a href="https://codepen.io/catw4x/pen/PopapBJ" target="_blank">https://codepen.io/catw4x/pen/PopapBJ</a>

![image](https://user-images.githubusercontent.com/57627955/121015189-9a21ef80-c792-11eb-9d8e-5970a93f108e.png)

**Comment by KaelWD** [comment]
I don't think we can fix this, safari has some known rendering problems with very basic stuff like transitioning background colors.
