### ISSUE TITLE
[Bug Report][2.5.0] Error in function convertToComponentDeclarations: iconSet[key].split is not a function

### ISSUE THREAD

**Issue by fjf2002** [vuetifyjs/vuetify#13776]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.77
**OS:** Windows 10

### Steps to reproduce
Hello,
since I'm a fan of Kotlin, I had added Kotlin-esque functions to Object.prototype; minimal example:

```
Object.prototype.let = function() {}
```

This lets Vuetify fail. 

### Expected Behavior
No error

### Actual Behavior
(in my installation:)
Uncaught TypeError: iconSet[key].split is not a function
    at convertToComponentDeclarations (vuetify.js:42123)

(in codepen:)
Uncaught TypeError: slots[name$1].every is not a function
    at resolveSlots (vue.js:2541)

### Reproduction Link
<a href="https://codepen.io/fjf2002/pen/wvJxGam" target="_blank">https://codepen.io/fjf2002/pen/wvJxGam</a>

### Other comments
Vuetify is using a loop ` for (var key in iconSet) { ... `.
This enumerates also my user-defined let function and therefore fails.

Shouldn't Vuetify better loop over Object.keys or Object.getOwnProperties or at least filter for string-type properties?

https://stackoverflow.com/questions/10695506/adding-function-to-object-prototype-causes-function-to-show-up-in-all-for-x-in

(A workaround for me is to use `Object.defineProperty` with `enumerable: false`)

**Comment by KaelWD** [comment]
> A workaround for me is to use Object.defineProperty with enumerable: false

You should probably be doing that anyway. Modifying built-in prototypes is generally considered a bad idea.
