### ISSUE TITLE
[Bug Report][2.5.3] VDateFooter incosistency, pagination.pageStart is 0-indexed pageStop and itemsLength isn't

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#13771]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

## the inconsistency 
The VDateFooter expects a pagination object with pageStart, pageStop and itemsLength for the text `1-3 of 4`
But the pageStart is 0-indexed and the pageStop end itemsLength is 1-indexed

![image](https://user-images.githubusercontent.com/1246691/120995878-1eba4100-c786-11eb-8ec1-18641845a469.png)

## Solution
In my opinion, this should be changed in a later version where there can be interface breaks. (Perhaps 3.0?)
And for now the documentation should be updated with some clarification

##workaround
just -1 the pageStart before passing the prop

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
