### ISSUE TITLE
[Bug Report][2.5.3] Calendar loses last event when set first-time

### ISSUE THREAD

**Issue by kostychev** [vuetifyjs/vuetify#13785]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.101
**OS:** Linux x86_64

### Steps to reproduce
Calendar has 2 events: 10 PM - 11 PM and 11 PM - 12 PM
When first-time="00:00" - both shown
first-time="08:00" - "11 PM - 12 PM" not

### Expected Behavior
Display event "11 PM - 12 PM"

### Actual Behavior
Not displayed

### Reproduction Link
<a href="https://codepen.io/ivendy/pen/xxqajXy" target="_blank">https://codepen.io/ivendy/pen/xxqajXy</a>

### Other comments
May be problem with `calendar-with-intervals` `timeDelta` method
used in `calendar-with-events` `genTimedEvent`

**Comment by KaelWD** [comment]
Looks like a special case of #11767, anding at 23:59 instead works fine.

**Comment by Kevin-H2R** [comment]
My commit makes it behave the same way whether you put `08:00` or `00:00` for the `first-time` prop.
However, the height of the displayed event is not good (it was not good for even for the "working case" (`first-time="00:00"`)). Gonna look further into that.
