### ISSUE TITLE
[Feature Request] Dataurl support for v-img

### ISSUE THREAD

**Issue by qt911025** [vuetifyjs/vuetify#13783]
### Problem to solve
When assign dataurl to src of v-img, v-img shows nothing, so that I can't put local-generated images in v-img.

### Proposed solution
Add support for dataurl.

**Comment by KaelWD** [comment]
VImg already works with data URLs.

**Comment by qt911025** [comment]
My bad. The problem is not dataurl support, but svg+xml support.

Please have a look.

https://codesandbox.io/s/eloquent-mountain-6rvpn?file=/src/App.vue

In this demo there are two problems.
One is that v-img is unable to display image by accessing relative path.
The other is that v-img is unable to display image of svg+xml type.

I used @vue/cli to generate a demo locally, and the problem is still:
https://github.com/qt911025/v-img-svg-demo

**Comment by KaelWD** [comment]
> v-img is unable to display image by accessing relative path
https://vue-loader.vuejs.org/options.html#transformasseturls

> v-img is unable to display image of svg+xml type.
https://discord.com/channels/340160225338195969/340215499398840331/836675979589058631
