### ISSUE TITLE
[Feature Request] Autocomplete - auto-select-first attribut highlight the first option but does not select it

### ISSUE THREAD

**Issue by thomas-romuald** [vuetifyjs/vuetify#13788]
### Problem to solve
In the [issues/4207](https://github.com/vuetifyjs/vuetify/issues/4207) the [aria standards](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/combobox/aria1.1pattern/listbox-combo.html#ex_label) have been mentioned.
The auto selection is describ with 3 steps: 
![image](https://user-images.githubusercontent.com/13487830/121689274-b391a700-cac4-11eb-924f-2b0c6921de75.png)

When we use this option [autocompletes usage](https://vuetifyjs.com/en/components/autocompletes/#usage) 
the first option is highlight but not selected. 

The behavior is descrid as this in the documentation but this does not follow the standard
![image](https://user-images.githubusercontent.com/13487830/121690475-2d766000-cac6-11eb-83db-faa4cef4ab46.png)

### Proposed solution
As step 3. The automatically selected suggestion becomes the value of the textbox when the combobox loses focus

**Comment by harkus** [comment]
I'm surprised this is still not incorporated!
