### ISSUE TITLE
[Feature Request] Please release store as a separate app / repo

### ISSUE THREAD

**Issue by mariusa** [vuetifyjs/vuetify#13790]
### Problem to solve
https://store.vuetifyjs.com/ is a great example of an app using vuetify. It's also a good storefront made with Vue for Shopify. It would be great to be available standalone, for others to plug in their store + API key, customize collections/pages and have a working Shopify storefront.

### Proposed solution
Please release the Shopify storefront in a standalone repo, similar to Next.js Commerce (https://github.com/vercel/commerce)
Thank you!

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
