### ISSUE TITLE
webpack bundle too big

### ISSUE THREAD

**Issue by willin** [vuetifyjs/vuetify#1379]
### Steps to reproduce

![wx20170817-170056](https://user-images.githubusercontent.com/1890238/29404589-f6c0a7e8-8300-11e7-8033-c932d7a6dae4.png)

### Versions

- vue latest
- vuetify latest
- os os x 10.12.6
- node 8.4
- webpack 3.5

### What is expected ?

only use few components, so i expect 100kb or below.

### What is actually happening ?

now is 300kb, almost total bundled in.

besides css bundle above 200kb

### Reproduction Link

webpack source: https://github.com/AirDwing/coding-task/blob/master/build/webpack.config.js

and the project is there too.

**Comment by nekosaur** [comment]
The current version of Vuetify does not support bundling individual components.

**Comment by johnleider** [comment]
A la carte components is coming in 0.15. Unfortunately, as a framework grows, so will its size, horizontally, this cannot be helped. We have added a la carte (bring in specific components only) to 0.15 and this should alleviate the issue.

**Comment by jingzheshan** [comment]
hey @johnleider any changes for this in the up incoming version. ty.

**Comment by nekosaur** [comment]
a-la-carte components have been available since 0.15. You can find out more on docs https://vuetifyjs.com/

**Comment by jingzheshan** [comment]
thanks @nekosaur, I saw the following comments just want to check 

> The implementation details for this feature will very likely change drastically in future versions. The a-la-carte feature should be considered to be in beta

**Comment by nekosaur** [comment]
Mmm, that not _as_ relevant now as when we first introduced the functionality. I'm pretty sure there won't be any major changes.
