### ISSUE TITLE
[Feature Request] When there are too many treeview nodes, starting the filter will get stuck

### ISSUE THREAD

**Issue by chaotianque** [vuetifyjs/vuetify#13797]
### Problem to solve
When there are too many treeview nodes, starting the filter will get stuck

### Proposed solution
Don't re render DOM, just set DOM display to none

**Comment by KaelWD** [comment]
This is not a valid feature request. If you are trying to submit a bug report please use the bug report template and supply a valid reproduction link with more details about the bug.  

For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
