### ISSUE TITLE
[Feature Request] Set different colors in each v-select v-autocomplete entry based on the item

### ISSUE THREAD

**Issue by MartinX3** [vuetifyjs/vuetify#13793]
### Problem to solve
I render a list.
The list is splitted into two parts.
The first ones are the recommended items, the second ones are every other item.
I want that the recommended items in the drop down list are rendered differently to show them as recommended, while the later part of the list should be in normal colors.

### Proposed solution
2 different v-selects v-autocompletes. Or using one element and assuming which is a recommended and which is a standard item.

**Comment by KaelWD** [comment]
You can do this using the `item` scoped slot.
