### ISSUE TITLE
[Feature Request] accessibility issue in v-date-picker

### ISSUE THREAD

**Issue by mobile-simformsolutions** [vuetifyjs/vuetify#13799]
### Problem to solve
Resolve accessibility issue on v-date-picker.
Ref Links:
https://monosnap.com/file/2SiDaoTKzvu88v0BWRF51mepPRjDph

### Proposed solution
For v-date-picker accessibility solutions in below link
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_table_01

**Comment by KaelWD** [comment]
This is not a valid feature request. If you are trying to submit a bug report please use the bug report template and supply a valid reproduction link with more details about the bug.   
If you are reporting an accessibility issue please make sure you can reproduce it **with an actual screen reader**, automated tools do not accurately reflect real-world usage. 

For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
