### ISSUE TITLE
[Feature Request] Improvement of data table

### ISSUE THREAD

**Issue by cheezone** [vuetifyjs/vuetify#13801]
### Problem to solve
A series of questions

### Proposed solution
- First, the data table does not currently support multi-level headers. 
- Second, the data table does not currently have the same filtering as Element UI. We can’t let users choose to display those mobile phone that includes the 'Pro' keyword, and with NFC, and  prices are below 1999 within three years. 
- Third, both Tooltip and Dialog are very troublesome to use, and there is no global API or shortcut properties. 
- Fourth, the search needs to be improved. It is suggested that the variable can be changed to accept an array or object in order to search for a single attribute. 
- Fifth, I hope that the data table can use arrays or points to access nested properties.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

Many of these are already covered by existing issues: #3037, #11600, #12136

> I hope that the data table can use arrays or points to access nested properties

This is already possible. 

If you do have a feature to request that hasn't been already: Please open **one** issue per feature, with more details about what problem it solves and how it should be implemented, and with examples of prior art if possible.
