### ISSUE TITLE
[Bug Report][2.4.7] V-calendar types day and 4day show Sat and Sun even though weekdays are Mon-Fri

### ISSUE THREAD

**Issue by Patiopatio** [vuetifyjs/vuetify#13816]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 91.0.4472.106
**OS:** Mac OS 10.15.7

### Steps to reproduce
Choose calendar type ```day``` or ```4day``` and weekdays ```Mon - Fri```.

### Expected Behavior
Display only days from Monday to Friday on all the devices. 

### Actual Behavior
When using previous and next arrows to go to a different day of the week, you can see that all days of the week are displayed including Saturday and Sunday. Those two days are not omitted as in the case of month and week type for Mon-Fri weekdays option.

### Reproduction Link
<a href="https://codepen.io/patrycja-buczkowska/pen/dyvrdqQ" target="_blank">https://codepen.io/patrycja-buczkowska/pen/dyvrdqQ</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
