### ISSUE TITLE
[Documentation] Conflicting information on Text Fields page

### ISSUE THREAD

**Issue by obnoxiousorc** [vuetifyjs/vuetify#13817]
### Environment

**Browsers:** Chrome 91.0.4472.106
**OS:** Linux x86_64

### Steps to reproduce
Two sections of the documentation are at odds with each other about whether "filled" type text fields can use the "prepend-icon" and "append-icon" props.

### Expected Behavior
The two sections should be in agreement about the functionality; if one of them is just phrased badly, it should be rewritten for clarity.

### Actual Behavior
Under "Filled" it says "Text fields can be used with an alternative box design. append-icon and prepend-icon props are not supported in this mode."

However, the Icons section shows "filled" type text fields using these props, both in the visual example and in the code driving it.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/text-fields/" target="_blank">https://vuetifyjs.com/en/components/text-fields/</a>

**Comment by zanchettouw** [comment]
Guys, can I take this issue to be my first contribution? I tested in the [codepen ](https://codepen.io/zanchettouw/pen/PopvpxO?editors=101) (just to be sure) and v-text-field can use append and prepend-icons,

 So I just need adjust the text in documentation, right?

**Comment by MajesticPotatoe** [comment]
go ahead @zanchettouw !

**Comment by zanchettouw** [comment]
> go ahead @zanchettouw !

@MajesticPotatoe , i know this issue is related to v-text-fields but I checked and [v-overflow-btn](https://vuetifyjs.com/en/components/overflow-btns/#filled) has the same conflicting information in Filled section.

I tested in this [codepen](https://codepen.io/zanchettouw/pen/JjWqNxO?editors=101)

Can I fix this in the same PR or need another opened issue?

**Comment by MajesticPotatoe** [comment]
yeah thats fine. same context.

**Comment by zanchettouw** [comment]
hey, @MajesticPotatoe , I created a [PR](https://github.com/vuetifyjs/vuetify/pull/13835) but can't add a reviewer or anything else.
