### ISSUE TITLE
[Bug Report][2.5.2] Wrong propless v-icon size inside v-chip

### ISSUE THREAD

**Issue by SaltyMonkey** [vuetifyjs/vuetify#13813]
### Environment
**Vuetify Version:** 2.5.2
**Last working version:** 2.5.1
**Vue Version:** 2.6.14
**Browsers:** Mozilla Firefox, Microsoft Edge, Google Chrome
**OS:** Linux, Windows

### Steps to reproduce
https://codepen.io/SaltyMonkey/pen/eYvMJWO

### Expected Behavior
Icon without size prop inside chip readable and looks good.

### Actual Behavior
Icon without size prop inside chip so small visually.

### Reproduction Link
<a href="https://codepen.io/SaltyMonkey/pen/zYZWvXV"
 target="_blank">https://codepen.io/SaltyMonkey/pen/zYZWvXV</a>

### Other comments
Related to https://github.com/vuetifyjs/vuetify/pull/13412 most likely.
Broken since version 2.5.2.
Was discussed in vuetify discord: https://discord.com/channels/340160225338195969/351121729164410882/850014983411466271

**Comment by harapeko** [comment]
subtle just idea
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VChip/VChip.sass#L206

```sass
.v-icon
  font-size: #{map-get($size, 'font-size') / $chip-close-size}em
  height: 1em
  width: 1em
```
