### ISSUE TITLE
[Bug Report][2.5.4] Sorting dates in v-data-table

### ISSUE THREAD

**Issue by adamsol** [vuetifyjs/vuetify#13829]
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.101
**OS:** Windows 10

### Steps to reproduce
Click the "Date" header to sort the values.

### Expected Behavior
Dates are sorted in an ascending or descending order.

### Actual Behavior
Dates become disordered.

### Reproduction Link
<a href="https://codepen.io/adamsol1/pen/zYZXEaz" target="_blank">https://codepen.io/adamsol1/pen/zYZXEaz</a>

### Other comments
This is due to the fact that Vuetify converts values to strings when sorting, and the default string representation of a `Date` object starts with the day of week.

https://github.com/vuetifyjs/vuetify/blob/822de45f32914e54adc8f236eb760ceaea31f88b/packages/vuetify/src/util/helpers.ts#L342
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString

I know that we can use the `sort` callback in the [`headers` prop](https://vuetifyjs.com/en/api/v-data-table/#props-headers) to fix this, but it's an ugly workaround. It would make more sense to use the default ordering, instead of forcing string comparison that fails in situations like this.

**Comment by jacekkarczmarczyk** [comment]
> It would make more sense to use the default ordering

Do you mean this?

![image](https://user-images.githubusercontent.com/15625235/122677968-01a15b80-d1e5-11eb-815e-4707804a9127.png)

**Comment by KaelWD** [comment]
That's what it's already doing pretty much, the default Array.prototype.sort calls .toString() on everything first

**Comment by adamsol** [comment]
FWIW, Lodash's `sortBy` works correctly:

![image](https://user-images.githubusercontent.com/17574518/122678263-55607480-d1e6-11eb-8af5-bab317bb85d5.png)

**Comment by adamsol** [comment]
https://github.com/vuetifyjs/vuetify/blob/f42a0147b351cf91b9a181d44d9237f8b71fc870/packages/vuetify/src/util/helpers.ts#L344

Shouldn't it be the other way around? They will be sorted in the reverse order now.

**Comment by IgorIlgiyaev** [comment]
Hey KaelWD
Using timestamp Firestore date data ins seconds it is not sorting at al

https://user-images.githubusercontent.com/20319110/143540713-d3c5b947-bbec-4b14-9488-3c5068ba51f9.mov

l.
