### ISSUE TITLE
[Bug Report][2.4.0] Normal use of v-ripple cause firefox warning

### ISSUE THREAD

**Issue by Aiedails** [vuetifyjs/vuetify#13824]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 91.0
**OS:** Linux x86_64

### Steps to reproduce
- Make the browser thinner than 1200px, wait the card below getting large
- click the card to make ripple
- the ripple is unsmooth and firefox warn `Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (672228 px). Occurrences of will-change over the budget will be ignored.`
- Also can be reproduce on mobile device.

### Expected Behavior
smooth ripple

### Actual Behavior
The frame rate of ripple is low

### Reproduction Link
<a href="https://github.com/Aiedails/igemwiki" target="_blank">https://github.com/Aiedails/igemwiki</a>

### Other comments
There are just about 20 components like `v-card` or `list-item` with `link` use `v-ripple`, but when the card takes up the entire screen as I wish when the browser becomes thinner, the ripple becomes stuttering and I receive `Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (672228 px). Occurrences of will-change over the budget will be ignored.` This phenomenon also appears on the mobile devices, make the ripple looks strange. I'm wondering why I receive this without over use the `v-ripple`.

**Comment by KaelWD** [comment]
> The frame rate of ripple is low

This is probably caused by something else. The will-change warning can be ignored.
