### ISSUE TITLE
[Feature Request] Buttons inside <expansion-panel-content> has some inherent spacing that I can't get rid of

### ISSUE THREAD

**Issue by max-fletcher** [vuetifyjs/vuetify#13826]
### Problem to solve
I want to use buttons inside the "expansion-panel-content" tags. The buttons are showing fine, but the inside of the "expansion-panel-content" has some inherent spacing (padding/margin) that I want to remove but can't find a way to. I want the buttons to fit inside them with no spacing.

### Proposed solution
When using "v-btn" inside the <expansion-panel-content>, there should be a way to remove the spacing so that the buttons fit.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
