### ISSUE TITLE
[Bug Report][2.5.4] v-tooltip positioning broken if html/body element has margin set

### ISSUE THREAD

**Issue by zoton2** [vuetifyjs/vuetify#13821]
### Environment
**Vuetify Version:** 2.5.4
**Last working version:** 2.5.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.106
**OS:** Windows 10

### Steps to reproduce
1. Add a margin to the html or body element.
2. Add a v-tooltip element (in the Codepen I copy/pasted from the official documentation).
3. Hover over the element to make the tooltip visible.

### Expected Behavior
v-tooltip positioning stays the same.

### Actual Behavior
v-tooltip's positioning is off and positioned too far away.

### Reproduction Link
<a href="https://codepen.io/zoton2/pen/dyvrabZ" target="_blank">https://codepen.io/zoton2/pen/dyvrabZ</a>

### Other comments
I know technically Vuetify sets the body to specifically have no margin, so this might be a "won't fix" bug, but it used to work fine hence why I decided to post it. I can work around it in my situation by adding the margin to an element instead of directly to the body, as it works fine in that case.

Someone pointed me towards the PR #13670 which may be the culprit.

**Comment by Tofandel** [comment]
Hmm something fishy is going on as this was the case it was supposed to fix, and in your template the bug is not present before but it is after

I'll need to investigate

**Comment by Tofandel** [comment]
Okay the .v-application is missing a `position: relative` which is normally present
