### ISSUE TITLE
[Bug Report][3.0.0-alpha.6] Custom theme causes 'Cannot convert undefined or null to object'

### ISSUE THREAD

**Issue by tony19** [vuetifyjs/vuetify#13822]
### Environment
**Vuetify Version:** 3.0.0-alpha.6
**Vue Version:** 3.1.1
**Browsers:** Chrome 91.0.4472.77
**OS:** Mac OS 10.15.7

### Steps to reproduce

 1. Create Vuetify instance with `createVuetify`, setting a `theme.themes` object without a `variables` property.

   ```js
    import { createVuetify } from 'vuetify'

    export default createVuetify({
      theme: {
        defaultTheme: 'myCustomTheme',
        themes: {
          myCustomTheme: {
            dark: false,
            colors: {
              primary: '#00ff00'
            },

            // variables: {} // FIXME: If this is not set, crash occurs.
          }
        }
      }
    })
   ```

 2. Pass that Vuetify instance to `createApp({}).use()`.

 3. Notice the error in the browser console:

```
preview-e2598225bde4872f93acb.js:1 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateStyles (theme.ts:248)
    at callWithErrorHandling (vue.esm-browser.js:1408)
    at callWithAsyncErrorHandling (vue.esm-browser.js:1418)
    at job (vue.esm-browser.js:3283)
    at doWatch (vue.esm-browser.js:3330)
    at watch (vue.esm-browser.js:3186)
    at createTheme (theme.ts:280)
    at Object.install (framework.ts:54)
    at Object.use (vue.esm-browser.js:5253)
```

### Expected Behavior
Custom themes can be specified without a `variables` property

### Actual Behavior
Project crashes

### Reproduction Link
https://stackblitz.com/edit/vuetify3-bug-demo?file=src/vuetify.js

**Comment by johnleider** [comment]
fixed in b91bfff

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by lozyue** [comment]
I meet the same problem in Vuetify Version: 3.0.0-alpha.10, too.
 (setting custom themes object without a variables property will get an error. )

Seems to not been fixed completely.

#### Browsers: Firefox 90.0.2 

#### Error in console: 
```
Uncaught TypeError: can't convert undefined to object
    _loop theme.ts:285
    updateStyles theme.ts:282
    callWithErrorHandling runtime-core.esm-bundler.js:6988
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:6997
    job runtime-core.esm-bundler.js:7380
    doWatch runtime-core.esm-bundler.js:7425
    watch runtime-core.esm-bundler.js:7283
    createTheme theme.ts:319
    install framework.ts:54
    use runtime-core.esm-bundler.js:3411
    <anonymous> main.ts:99
    ts app.js:1656
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1765
    __webpack_require__ app.js:854
```


> 
> #### Expected :
> Custom themes can be specified without a variables property
>

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
