### ISSUE TITLE
[Bug Report][2.5.4] VAutoComplete does not return `object` when receiving a string value and `returnObject` prop is enabled

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [vuetifyjs/vuetify#13831]
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
Open your console on the browser, select two values from VAutoComplete and it will come with a mix of strings and objects

### Expected Behavior
There should only be returned objects since prop `returnObject` is enabled

### Actual Behavior
It returns a mix of strings and objects

### Reproduction Link
<a href="https://codepen.io/whatupnewyork/pen/vYxMRvO?editors=1010" target="_blank">https://codepen.io/whatupnewyork/pen/vYxMRvO?editors=1010</a>

**Comment by KaelWD** [comment]
`returnObject` doesn't mutate existing selections, it only changes what's added to the model array.
