### ISSUE TITLE
[Documentation] algolia search does not work for UI component name

### ISSUE THREAD

**Issue by MathieuDerelle** [vuetifyjs/vuetify#13840]
### Environment

**Browsers:** Chrome 91.0.4472.77
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. search "tooltip" or "timeline" in the search bar
2. the pages for said components are not in the algolia results

### Expected Behavior
searching "tooltip" would have as first result, the component page
https://vuetifyjs.com/en/components/tooltips/

### Actual Behavior
The component page is not listed at all.
screenshot : https://puu.sh/HRoC4/84cac27bfe.png

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tooltips/" target="_blank">https://vuetifyjs.com/en/components/tooltips/</a>

**Comment by KaelWD** [comment]
https://github.com/algolia/docsearch-configs/commit/3c18ba03422c086e2729dc785f3dd51122e0d1d4
