### ISSUE TITLE
[Bug Report][2.5.5] v-tabs slider doesn't shift after first click

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#13843]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click second tab
2. Observe the tab content vs. the tab slider

### Expected Behavior
tab slider should be on the second tab when clicked

### Actual Behavior
tab slider remains on first tab, until second tab is clicked for a second time

### Reproduction Link
<a href="https://codepen.io/codepen123456789/pen/QWpeozb?editors=1010" target="_blank">https://codepen.io/codepen123456789/pen/QWpeozb?editors=1010</a>

![image](https://user-images.githubusercontent.com/7410770/123457884-63314380-d5b2-11eb-8da5-fc08f2a354d5.png)

**Comment by KaelWD** [comment]
The click event on v-tab is not needed, just use `<v-tabs v-model="tab">`

**Comment by davidbielik** [comment]
Hi @KaelWD the problem when not using `@click` and using `<v-tabs v-model>` is that then I'm forced to make `tab` a number.

In a different implementation below, I can keep `tab` a string to align with my data model:

```
<v-tabs :value="tab">
   <v-tab to="/route/tab1">tab1</v-tab>
   <v-tabs-items v-model="tab">...</v-tab-items>
</v-tabs>
```

```
computed: {
  tab(){
     return this.$route.params.tab;
  }
}
```

Is there a way to keep the `tab` value as a string, or you can tell me which part I'm using incorrectly?

https://codepen.io/codepen123456789/pen/QWpeozb?editors=1010

**Comment by KaelWD** [comment]
It's a bit fucky, currently you have to use `href`: https://codepen.io/kaelwd/pen/ExmYdVG?editors=1010

I tried to get a `name` prop added in 2017 but it was shot down by the bossman. 
![image](https://user-images.githubusercontent.com/16421948/123549670-4745c180-d7ad-11eb-85ca-9adc7c3726ba.png)
