### ISSUE TITLE
[Bug Report][2.5.5] Rendering the File inputs component

### ISSUE THREAD

**Issue by doox911** [vuetifyjs/vuetify#13846]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.114
**OS:** Linux x86_64

### Steps to reproduce
1. The field has shrunk.
2. To reproduce the second bug, click on the file inputs

### Expected Behavior
1. The field must not decrease.
2. The border must be rendered completely.

### Actual Behavior
1. The field has shrunk.
2. To reproduce the second bug, click on the file inputs

### Reproduction Link
<a href="https://codepen.io/doox911/pen/VwbZjNB" target="_blank">https://codepen.io/doox911/pen/VwbZjNB</a>

![BUG](https://user-images.githubusercontent.com/35161922/123512822-4c621e00-d692-11eb-9993-c983f3d7b410.png)

#### Should be

![Must_be](https://user-images.githubusercontent.com/35161922/123512867-8cc19c00-d692-11eb-8c70-127c686d5d84.png)

**Comment by KaelWD** [comment]
> The field must not decrease

`cols="auto"` will shrink to be as narrow as it can without causing overflow, that's how it's supposed to work. 

> The border must be rendered completely.

You need to use v-app
