### ISSUE TITLE
[Bug Report][2.5.3] ShadowRoot is undefined in ie11 

### ISSUE THREAD

**Issue by wusongliang** [vuetifyjs/vuetify#13845]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.12
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
ShadowRoot is undefined

### Reproduction Link
<a href="https://github.com/fengsi-io/vuetify/commit/708f8de8e2055d6edf2e08492a9c8537b1672fec#diff-b06e4229c41d17195606b2c16179803128618d49fc227c3c414141c5af1f0555R29" target="_blank">https://github.com/fengsi-io/vuetify/commit/708f8de8e2055d6edf2e08492a9c8537b1672fec#diff-b06e4229c41d17195606b2c16179803128618d49fc227c3c414141c5af1f0555R29</a>

**Comment by wusongliang** [comment]
![image](https://user-images.githubusercontent.com/51825134/123506267-e37ca500-d695-11eb-8a0d-f2488c366e23.png)

**Comment by halimb** [comment]
same here, started happening in 2.5.3 as well as another error:  `Unable to get property 'lastMousedownWasOutside' of undefined or null reference`

**Comment by sgh8539** [comment]
same problem for me seems like vue-click-outside is not working on ie11

import ClickOutside from '../../directives/click-outside'
if (root instanceof ShadowRoot && root.host === e.target) return false

**Comment by glen-84** [comment]
@Malachi-M FYI.

**Comment by fskpf** [comment]
Has anyone found a workaround for it, or is this regressions the end of IE11 support?

**Comment by s-montigny-desautels** [comment]
I am still having this error in `v2.5.9`. 

![image](https://user-images.githubusercontent.com/84924528/135508970-9c0e5802-b690-46a5-9d24-eb97c7a12533.png)

**Comment by EitanYarimi** [comment]
same here with V2.5
![Screen Shot 2021-10-05 at 9 09 00](https://user-images.githubusercontent.com/251865/135969625-7a3b38be-e169-49f9-a092-9ce3ac16e257.png)
.
