### ISSUE TITLE
[Documentation] Sass Variable Browser not Working - showing empty results

### ISSUE THREAD

**Issue by AntonLugtenburg** [vuetifyjs/vuetify#13858]
### Environment

**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Open https://vuetifyjs.com/en/features/sass-variables/#variable-api, select any of the components from the dropdown

### Expected Behavior
Should show available sass variables for selected components

### Actual Behavior
Returns emtpy simple-tables with no content

### Reproduction Link
<a href="https://vuetifyjs.com/en/features/sass-variables/#variable-api" target="_blank">https://vuetifyjs.com/en/features/sass-variables/#variable-api</a>

### Other comments
I tried random components, v-app, v-list-group, v-alert and so on. Thank you for the great work, im really looking forward to migrating to vue3 :)

**Comment by heanssgen-troy** [comment]
Can confirm the issue has been present since last night (at the minimum). Seems to be a simple syntax error.

![image](https://user-images.githubusercontent.com/7853116/123877466-39a64e00-d90b-11eb-90fe-816ed2ebdaae.png)
