### ISSUE TITLE
[Documentation] Failed to resolve component: v-toolbar

### ISSUE THREAD

**Issue by skadiD** [vuetifyjs/vuetify#13860]
### Environment

**Browsers:** Chrome 91.0.4472.114
**OS:** Windows 10

### Steps to reproduce
vue create my-app
cd my-app
vue add vuetify
vue add vue-next
npm run serve

### Expected Behavior
Just work toolbar same as vuetify2

### Actual Behavior
Can't show correct component and point out
`[Vue warn]: Failed to resolve component: v-toolbar-title `

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/toolbars/" target="_blank">https://next.vuetifyjs.com/en/components/toolbars/</a>

### Other comments
Doesn't vuetify3  have such component as v-toolbar?

**Comment by KaelWD** [comment]
If it isn't listed in the sidebar then it doesn't exist yet.
