### ISSUE TITLE
[Bug Report][2.5.5] Prepending an item to a carousel puts it at the end of the carousel instead of at the start

### ISSUE THREAD

**Issue by RuurdBijlsma** [vuetifyjs/vuetify#13862]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Have a `<v-carousel-item>` for each item in given array, lets say `items`, put those in a `<v-carousel>`. Then unshift (prepend) a new item to `items`

### Expected Behavior
The new item is now the first item in the carousel

### Actual Behavior
The new item is now the last item in the carousel

### Reproduction Link
<a href="https://codepen.io/RuteNL/pen/yLbyOZE" target="_blank">https://codepen.io/RuteNL/pen/yLbyOZE</a>

**Comment by KaelWD** [comment]
Duplicate of #12818
