### ISSUE TITLE
[Bug Report][2.5.5] textarea clearable prop

### ISSUE THREAD

**Issue by vlad909** [vuetifyjs/vuetify#13861]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.106, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
insert prop "clearable" as true 

### Expected Behavior
a control angle of the number of lines (the right bottom classic controller as in standard html) moves to left with same level of cross element (cross icon for clear of value)

### Actual Behavior
the control angle of the number of lines remains in place

### Reproduction Link
<a href="https://codepen.io/vlad909/pen/oNWgNQW" target="_blank">https://codepen.io/vlad909/pen/oNWgNQW</a>

![image](https://user-images.githubusercontent.com/40794286/123841280-074f1d80-d918-11eb-834f-1da2c71399ae.png)

**Comment by simonmaass** [comment]
con confirm

**Comment by glen-84** [comment]
Related to #9681.

**Comment by Kevin-H2R** [comment]
Hello.
Looked quickly into it.
Adding `position: absolute;` and parent's padding to `v-input__append-inner` seems to do the trick (checked with `v-text-field` too). But not sure this is a solution we want to go with. I feel there can be many unwanted impacts.
