### ISSUE TITLE
[Bug Report][3.0.0-alpha.7] Missing theme documentation

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13864]
### Environment
**Vuetify Version:** 3.0.0-alpha.7
**Vue Version:** 3.1.2
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
n/a

### Expected Behavior

1. Documentation on customizing the built-in themes (light/dark), partially or fully.
2. Documentation on the `variables` property of `ThemeDefinition`.

### Actual Behavior
n/a

### Reproduction Link
n/a

### Other comments
n/a

**Comment by nekosaur** [comment]
@glen-84 could you possibly clean up this issue description further / split the rest of the points up into appropriate issues?

**Comment by johnleider** [comment]
This is mostly resolved and will continue to be updated during the beta process.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by glen-84** [comment]
@johnleider I don't see either of these points addressed in the theme documentation.

**Comment by johnleider** [comment]
The team reviewed it and that was our conclusion. We have a lot of things to update in the docs, we want to keep issues to a minimum until we are certain the content is expected to be solid.
