### ISSUE TITLE
[Bug Report][3.0.0-alpha.7] The `color` prop of `<v-list>` has no effect when nested inside `<v-navigation-drawer>`

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13865]
### Environment
**Vuetify Version:** 3.0.0-alpha.7
**Vue Version:** 3.1.2
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
See the reproduction link below.

This is caused by the following Sass:

https://github.com/vuetifyjs/vuetify/blob/0da2f852c6fd9bf19873736eef43c879843a69c5/packages/vuetify/src/components/VList/VList.sass#L87-L90

Is there a reason to force these property values, especially since it's probably the default anyway?

### Expected Behavior
I should be able to set the background colour of a list, even when it's nested inside a navigation drawer.

### Actual Behavior
There is CSS with a higher specificity that sets the background colour to `transparent` (and also sets the `color` to `inherit`).

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/MWmYQBV" target="_blank">https://codepen.io/glen-84/pen/MWmYQBV</a>

**Comment by Tofandel** [comment]
![image](https://user-images.githubusercontent.com/6115458/124263305-5fae3700-db33-11eb-9607-ed94f47bbe98.png)

**Comment by glen-84** [comment]
> I have one question then, why does the color prop apply a background color on the v-list and a font color on the v-list-item? This seems like a confusing naming.. I'd opt for the v-list prop to be renamed to background-color

It applies a font colour and also changes the background colour (on hover).

There's also a [text-color](https://next.vuetifyjs.com/en/api/v-list-item/#props-text-color) prop on v-list-item, but that doesn't seem to do anything (https://codepen.io/glen-84/pen/GRmJwEN). I'm going to open an issue for that soon.

**Comment by johnleider** [comment]
> I have one question then, why does the color prop apply a background color on the v-list and a font color on the v-list-item? This seems like a confusing naming.. I'd opt for the v-list prop to be renamed to background-color

It has to do with the variant type. There are 5 in total:

- Plain
- Text
- Contained
- Contained Text
- Outlined

Not all components share the same default variant.
