### ISSUE TITLE
[Bug Report][2.5.6] v-text-field does not display suffix clock icon for type=time in desktop Safari (14.1.1)

### ISSUE THREAD

**Issue by JeffersonSchuler** [vuetifyjs/vuetify#13869]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Prefixes and Suffixes demo page shows the issue.

### Expected Behavior
The clock icon should show like it does in Chrome.

### Actual Behavior
The clock icon does not display.

### Reproduction Link
<a href="https://codepen.io/jeffersonschuler/pen/rNmaQVo?editors=101" target="_blank">https://codepen.io/jeffersonschuler/pen/rNmaQVo?editors=101</a>

**Comment by KaelWD** [comment]
This just uses the native browser behaviour, and safari's `<input type="time">` doesn't have an icon.
