### ISSUE TITLE
@click.prevent also prevents button from losing active state

### ISSUE THREAD

**Issue by Ragura** [vuetifyjs/vuetify#1386]
### Steps to reproduce
Use @click.prevent on a v-btn.

### Versions

All versions.

### What is expected ?

The button should lose the active state as normal.

### What is actually happening ?

The active (grey) state remains after you click the button, because the .prevent modifier stops whatever else Vuetify does to remove the active state. I am doing it like this because the button is inside a list-tile that has a :to property set. If I don't use the .prevent modifier, the click function on the button will never fire and instead act as a link to the route. I assume this is because the list-tile has a higher priority?
If there is a simple workaround, please advise!

### Reproduction Link

https://codepen.io/anon/pen/zdpXrx

**Comment by johnleider** [comment]
I'm toying around with this, but I'm not sure if it is something that we can support by default due to the overlapping of click listeners.

**Comment by johnleider** [comment]
After experimenting again, I'm not sure this is something that can or even should be solved. Overlapping elements with click event listeners act as they are intended to by the browser and I don't think we should pursue this task.

**Comment by Ragura** [comment]
Alright, I understand that line of thinking. Could we then get another way
of accessing the active state of an underlying button? It's quite annoying
to have the active styling remain when clicked.

Op 19 aug. 2017 05:58 schreef "John Leider" <notifications@github.com>:

**Comment by nekosaur** [comment]
Here's a solution

```vue
<template>
  <v-app>
    <v-btn icon @click.prevent="doStuff">
      <v-icon>star</v-icon>
    </v-btn>
  </v-app>
</template>

<script>
  export default {
    data () {
      return {
      }
    },
    methods: {
      doStuff (e) {
        // target is actually btn__content so we need to go one step higher
        e.path[1].blur()
      }
    }
  }
</script>
```

**Comment by Ragura** [comment]
Thanks, I will try this!
