### ISSUE TITLE
[Documentation] v-tabs change event return type is incorrect on API docs

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#13876]
### Environment

**Browsers:** Chrome 91.0.4472.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
I can confirm that v-tabs does not exclusively return a number on the change event. I think it will return numbers if you don't specify a value for the `to` or `href` props in child `v-tab` components, but where I'm using it, it returns the string value of what I have put into the `to` prop, without the `#` symbol in the front. Simply `console.log` ing the contents of the event will show the truth.

### Expected Behavior
The document should describe the conditions in which a number is returned on the change event and the conditions in which a string would be returned on the change event.

### Actual Behavior
Currently the documentation states that the change event only returns a number.

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-tabs/#api-events" target="_blank">https://vuetifyjs.com/en/api/v-tabs/#api-events</a>

### Other comments
As a side note, I'm really hoping that Vuetify 3's tabs API will be a significant improvement over version 2. 😜

**Comment by matheuzsrlog** [comment]
Solving...I will soon be opening the PR.
