### ISSUE TITLE
[Bug Report][3.0.0-alpha.8] The `text-color` prop of `<v-list-item>` has no effect

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13878]
### Environment
**Vuetify Version:** 3.0.0-alpha.8
**Vue Version:** 3.1.3
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
See the reproduction link.

### Expected Behavior
Red text.

### Actual Behavior
Not red text. 🙃

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/GRmJwEN" target="_blank">https://codepen.io/glen-84/pen/GRmJwEN</a>

### Other comments
This is in the API documentation [here](https://next.vuetifyjs.com/en/api/v-list-item/#props-text-color). Is the API documentation automatically-generated/up-to-date?

Also, `color` and `active-color` both seem to refer to an `active` state – how do they differ?

**Comment by KaelWD** [comment]
The documentation hasn't been finished yet, `text-color` only works with `variant="contained"`.

**Comment by glen-84** [comment]
Oh, I did try that, but it changes the background colour as well (on hover ... seems to use `currentColor`). I can understand a `color` prop changing both text and bg colour, but surely `text-color` should only affect ... text?

Also, it seems like `color="red"` has the same effect as `text-color="red" variant="contained"`.

Oh well, I guess I'll have to wait for the docs. 🙂

**Comment by johnleider** [comment]
fixed in 457ff242f
