### ISSUE TITLE
[Documentation] Made With Vuetify is broken

### ISSUE THREAD

**Issue by LukeTully** [vuetifyjs/vuetify#13871]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 3.1.2
**Browsers:** Firefox 90.0
**OS:** Mac OS 10.15

### Steps to reproduce
Visit the page.

### Expected Behavior
Examples load successfully

### Actual Behavior
Examples don't load

### Reproduction Link
<a href="https://vuetifyjs.com/en/resources/made-with-vuetify/" target="_blank">https://vuetifyjs.com/en/resources/made-with-vuetify/</a>

### Other comments
I don't have a PR for this because it seems like it's just making an api call to the madewithvuejs endpoint, and they don't have their api open sourced. The request fails because the endpoint doesn't (or no longer) have the access-control-allow-origin header. Presumably this is something that the Vuetify documentation authors would need to talk to them about.

**Comment by johnleider** [comment]
Remote server has new CORS policy. Temporarily disabling nav link.

**Comment by johnleider** [comment]
This was fixed https://vuetifyjs.com/en/resources/made-with-vuetify/
