### ISSUE TITLE
.btn__content missing data scoped attribute in v-btn

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#1387]
### Steps to reproduce
Use `<v-btn>` with a `<style scoped>` in a .vue template

### Versions
Vue 2.4.2
Vuetify 0.14.8

### What is expected ?
All elements should have the data-v-xxx attribute on them for scoping

### What is actually happening ?
the .btn__content inside of the button is missing the data attribute, causing my style not to work

### Reproduction Link
Not sure how to get scoped style in codepen, if you let me know I will throw it in there.
```
<v-btn light v-for="button in buttons" :key="button.translation">
    <v-icon>{{ button.icon }}</v-icon>
    {{ button.translation }}
</v-btn>
```
![screen shot 2017-08-17 at 1 47 31 pm](https://user-images.githubusercontent.com/2039539/29433312-83c88d52-8353-11e7-8920-842419587b1c.png)
You can see that .btn__content is missing the data-v-eb6adf5e data attribute causing the following code for .btn__content not to apply.
```
    .button-container
        margin-top 32px
        button
            margin 0
            .btn__content
                flex-direction column
```

**Comment by jacekkarczmarczyk** [comment]
It's not a bug, it's a vue loader feature. To access deeper elements you need to use `/deep/` or `>>>` selector as described in docs https://vue-loader.vuejs.org/en/features/scoped-css.html

**Comment by amritk** [comment]
I see, still pretty new to the whole vue thing, thanks @jacekkarczmarczyk
