### ISSUE TITLE
[Feature Request] input event for v-chip-group

### ISSUE THREAD

**Issue by paulhaem** [vuetifyjs/vuetify#13883]
### Problem to solve
The v-chip-group currently only offers a change event that triggers when the model gets updated. When initialising a v-chip-group async after it has already been rendered triggers a change event which might not always be desired.

### Proposed solution
Adding a input event that triggers only when the model gets updated via user click.

**Comment by KaelWD** [comment]
> initialising a v-chip-group async

Dunno what you mean by this. It only emits a change event initially if there is some condition like `mandatory` that is not met by the default value you've given it.

**Comment by paulhaem** [comment]
By async I mean that when I render a v-chip-group with the `mandatory` prop and set its default value to e.g. 0 while I wait for a fetch to resolve which then sets the true initial value for e.g. a form.

But when I understand that correctly stoping the v-chip-group from rendering till the true init value is set would come to the same result?

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
