### ISSUE TITLE
[Bug Report][2.3.13] keydown does not work on v-dialog after click outside which has persistent true

### ISSUE THREAD

**Issue by karsumir** [vuetifyjs/vuetify#13882]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.114
**OS:** Windows 10

### Steps to reproduce
1. Click `OPEN DIALOG` button to open dialog
2. Press esc key to check `keydown.esc` has no problem
3. Click outside to check persistent option is true
4. Press esc key to close dialog (this does not work)
5. Click any place of dialog box and press esc key. (this work)

### Expected Behavior
Close dialog on `step 4`

### Actual Behavior
No any response (@keydown does not work on step 4)

### Reproduction Link
<a href="https://codepen.io/karsumir/pen/JjNGPqB" target="_blank">https://codepen.io/karsumir/pen/JjNGPqB</a>

### Other comments
I'm not sure this is a bug or just an intended action.
It seems like lost focus from dialog when click outside even if `retain focus` option is true.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by douglasg14b** [comment]
This is still an issue though :/
