### ISSUE TITLE
[Feature Request] v-dialog add a wrapper-class prop

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#13885]
### Problem to solve
When you want to change some styles that are on the `v-dialog__content` at this point your only option is using the `attach` prop and attach it to something else and use that as a wrapping style.
But when your dialog component is inside for example the app bar this results in unwanted styling/positioning.

### Proposed solution
adding some sort of wrapping-class prop so you could give the `v-dialog__content` an extra class of choice

work around: add a div somewhere high in the dom tree, but inside the v-app and attach the dialog to that div. the downside is that your code is splintered

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-dialog/#props-content-class

**Comment by ricardovanlaarhoven** [comment]
The content-class is attached to the dialog itself, not to the wrapper. Which makes it impossible to make a dialog stick to the top of the page, since this is done by flex-box with an align and justify on the parent

**Comment by KaelWD** [comment]
Ah yeah I thought it was the same as v-menu, doesn't really make sense to have a prop called content-class that doesn't affect the `__content` element. You can apply `align-self: flex-start` with content-class, or target `.v-dialog__content` in a `<style scoped>` block.

**Comment by ricardovanlaarhoven** [comment]
Then perhaps this is a bug?

![image](https://user-images.githubusercontent.com/1246691/124569139-f8032f00-de45-11eb-86db-113e41823f93.png)

https://codepen.io/ricardovanlaarhoven/pen/LYyGgBd

**Comment by KaelWD** [comment]
```diff
- star
+ start
```

**Comment by ricardovanlaarhoven** [comment]
Haha ofcourse..

This works, i tought the bug was that the content class was not attached to the v-dialog__content.
as you said:
> doesn't really make sense to have a prop called content-class that doesn't affect the __content element.

But now i know i can make this work without using the v-dialog__content
