### ISSUE TITLE
[Feature Request] Can I do a floating dialog from btn?

### ISSUE THREAD

**Issue by Hiroio** [vuetifyjs/vuetify#13889]
### Problem to solve
So i need to do a floating window from v-btn like v-menu but dialog apears on the center of the screen
here is my code https://codepen.io/hiroio/pen/oNWbQKN
if it possible can you help me to solve this problem
I'm not sure if it can be possible to do dialog floatable maybe it must be another component

### Proposed solution
so i need to do dialog floating from v-btn

**Comment by KaelWD** [comment]
- Your codepen doesn't run
- Sounds like you want https://vuetifyjs.com/en/components/menus/#popover-menu
- The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
