### ISSUE TITLE
[Bug Report][2.5.6] Tabs sometimes only partially visible

### ISSUE THREAD

**Issue by samalisam** [vuetifyjs/vuetify#13884]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Keyboard:
- Focus the first tab
- Press *tab* twice so "Item long name 3" is focused

### Expected Behavior
The tab group moves so the tab "Item Long Name 3" is completely readable. The official material design documentation features the expected behaviour in their "scrollable tabs" interactive demo: https://material.io/components/tabs

### Actual Behavior
The tab is only partially readable and when *tab* is pressed again, the tab group scrolls to the next page and the tab "Item Long Name 3" is again only partially readable.

### Reproduction Link
<a href="https://codepen.io/samalisam/pen/qBmbbOd" target="_blank">https://codepen.io/samalisam/pen/qBmbbOd</a>

### Other comments
The same problem of tabs being only partially visible can also occur when using the arrow icons. Some tabs are never fully readable unless you click on the tab.

**Comment by johnleider** [comment]
Related to #10416

**Comment by KaelWD** [comment]
Fixed by 583692820969f1f1ab68d172e6166b4e71354eb5
