### ISSUE TITLE
v-text-field errors if it doesn't have an id

### ISSUE THREAD

**Issue by iamianmiller** [vuetifyjs/vuetify#1388]
### Steps to reproduce
Run the fiddle with the console open.  An error will be thrown 

> Cannot read property 'id' of undefined"

Adding any property or an id removes the error

### Versions
Vuetify 14.11
Vue 2.3.4

### What is expected ?
In 13 it did not give this error.

### What is actually happening ?
It errors and doesn't render.

### Reproduction Link
https://jsfiddle.net/ianmiller/5L19txdb/

**Comment by jacekkarczmarczyk** [comment]
upgrade Vue to 2.4.2

**Comment by iamianmiller** [comment]
Doesn't appear to fix it?  (I know, mixing CDNs, gross)

https://jsfiddle.net/5L19txdb/3/

**Comment by johnleider** [comment]
I caught this during testing for 0.15 and can confirm it has been resolved.
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VTextField/VTextField.vue#L149

**Comment by sebastianmacias** [comment]
When do you think you could bump the 0.14.11 version to include this change?

Thanks

**Comment by johnleider** [comment]
0.15 will be the next release, early September.

**Comment by sebastianmacias** [comment]
It actually worked when I upgraded vue from 2.3.x to 2.4.2.
