### ISSUE TITLE
[Bug Report][2.5.6] height prop isn't working

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#13897]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.114
**OS:** Linux x86_64

### Steps to reproduce
Just check the prop

### Expected Behavior
I guess as the name of the prop: `height` it should change the height of v-text-field

### Actual Behavior
It isn't changing the height

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/VwbapxK?editors=1010" target="_blank">https://codepen.io/jd-0001/pen/VwbapxK?editors=1010</a>

**Comment by aliosman21** [comment]
The v-text-field does change the height on the prop.

Tried it using  `height="100"` & `height="100px"` both worked correctly.

However v-text-field does seem to have a lower bound around 55 ~ 60 meaning it will not be smaller than that value and will default to it when you choose a number smaller than it.

Hope this helps

**Comment by johnleider** [comment]
If you want to finely tune the field height use SASS variables or density.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
