### ISSUE TITLE
[Bug Report][2.5.6] v-date-picker not focusing on specified min and max props

### ISSUE THREAD

**Issue by mavyfaby** [vuetifyjs/vuetify#13896]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.114
**OS:** Linux x86_64

### Steps to reproduce
* Create v-date-picker
* Set the `min` and `max` props **before or after the current month**

### Expected Behavior
v-date-picker should focus on the minimum date.

### Actual Behavior
v-date-picker focuses on the current date.

### Reproduction Link
<a href="https://codepen.io/mavyfaby/pen/qBmZNGG" target="_blank">https://codepen.io/mavyfaby/pen/qBmZNGG</a>

**Comment by aliosman21** [comment]
The v-date-picker does work on the range the only problem with the pen provided is that you should set the dates as an array like this `dates: ['2019-03-01' , '2019-03-15']` in the data and make the v-model point to it `v-model="dates"` I removed the min & max props as they are not essential to the issue

You were also missing the `range` prop in the v-date-picker.

date picker
```html
<v-date-picker
        v-model="dates"
        range
        scrollable>
      </v-date-picker>
```

data
```javascript
data: () => ({
    dates: ['2019-03-01', '2019-03-15'],
  })```

**Comment by mavyfaby** [comment]
Thanks for the answer, but I don't want to have a range. I want the user to pick a date between those `min` and `max` props and focus on the minimum month of the specified `min` date.

**Comment by jacekkarczmarczyk** [comment]
Use `:picker-date.sync` prop to open the picker at specified month

**Comment by mavyfaby** [comment]
That works! Thank you so much

**Comment by mavyfaby** [comment]
That works! Thank you so much
