### ISSUE TITLE
enable-resize-watcher always opens hidden navigation drawer on resize

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1389]
### Steps to reproduce
1. Create a navigation drawer with resize watcher
2. Hide the navigation drawer
3. Resize the browser window

### Versions
Vue 2.4.2, Vuetify 0.14.11, Edge 15

### What is expected ?
Only an open drawer should respond to browser size changes leaving a hidden drawer hidden

### What is actually happening ?
The hidden navigation drawer suddenly opens

### Reproduction Link
https://codepen.io/anon/pen/jLYgzj

**Comment by johnleider** [comment]
We discussed this in chat.

**Comment by rosnaib11** [comment]
Whats the solution for this?

**Comment by johnleider** [comment]
To use the **disable-resize-watcher** or **static** prop
