### ISSUE TITLE
[Bug Report][2.5.6] VSnackbar can get stuck on mobile

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#13904]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
1. Open the reproduction link in Android Chrome
2. Click the "open snackbar" button
3. Tap on the snackbar while it is open

### Expected Behavior
The snackbar should still close after the timeout expired.

### Actual Behavior
If the user does nothing, the snackbar stays open indefinitely. The timeout is only applied again if the user taps on something other than the snackbar

### Reproduction Link
<a href="https://codepen.io/wistudent/full/ZEKObMX" target="_blank">https://codepen.io/wistudent/full/ZEKObMX</a>

### Other comments
This seems to be caused by this part:
https://github.com/vuetifyjs/vuetify/blob/6bb948463c2e9559d60f5f99e1208f79a0935b39/packages/vuetify/src/components/VSnackbar/VSnackbar.ts#L176-L177
On mobile tapping an element triggers a mouseenter event, but no mouseleave event. Instead of mouseenter/mouseleave I would recommend using pointerenter/pointerleave. On devices with a mouse it just behaves like mouesenter/mouseleave, but on touch devices the pointerleave event is fired as soon as the finger stops touching the screen.

**Comment by KaelWD** [comment]
pointerenter is only supported since safari 13 (thanks apple)
