### ISSUE TITLE
[Bug Report][2.5.6] Issue with @click:event & @click:day in calendar component

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#13900]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.114
**OS:** Linux x86_64

### Steps to reproduce
1. Click on event

### Expected Behavior
* It should only emit `click:event` according to the best of my knowledge

### Actual Behavior
* It will emit `click:day` event along with `click:event`
* Also clicking on event which spans over few days, let's say 2-3 june and you click on the event on 3rd june - it shows click:day for 2nd june

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/ZEKWaXX?editors=1010" target="_blank">https://codepen.io/jd-0001/pen/ZEKWaXX?editors=1010</a>

### Other comments
This creates an issue when we create functionality for adding new event on `click:day` and update event on `click:event`.

Regards.

![image](https://user-images.githubusercontent.com/47495003/124753072-308a3200-df46-11eb-9029-400b3e362dd4.png)

**Comment by jd-0001** [comment]
This is the same for `click:more`

**Comment by YoanChapron** [comment]
I agree even if I agree that it is better to be able to separate these events
