### ISSUE TITLE
Add property to set footer height

### ISSUE THREAD

**Issue by talski** [vuetifyjs/vuetify#1390]
What will it allow you to do that you can't do today?
Ability to set footer height.

How will it make current work-arounds straightforward?
Today you need to create your own styles overwriting original values to achieve this, and if you need to change the height, you'll need to change it in several places.

What potential bugs and edge cases does it help to avoid?
Prevent layout breaks

**Comment by johnleider** [comment]
The difficulty with this in the current setup, is it would break the application props that define main container height. Also considering how niche it is, and you usually only ever make one per application, this is not something we are going to pursue at this time.
