### ISSUE TITLE
[Bug Report][2.5.6] fill-height class does not exist when v-spacer is removed

### ISSUE THREAD

**Issue by TrevinAvery** [vuetifyjs/vuetify#13906]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.106
**OS:** Mac OS 10.14.6

### Steps to reproduce
Build a barebones application useing `vue/cli@5.0.0-beta.2` with the following commands:

```
vue create vuetify-missing-fill-height
vue add vuetify
```

This creates an app with `vue@2.6.14` and `vuetify@2.5.6`.

Then simply change the content of `App.vue` so that `<v-main>` contains the [grid example](https://vuetifyjs.com/en/components/images/#grid) from the docs ([also on GitHub](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-img/misc-grid.vue)). And then remove everything from the `v-app-bar` except the logo.

### Expected Behavior
The `<v-progress-circular>` components are vertically centered over the `<v-img>` components when loading. This is because the `<v-row>` components containing them have the `fill-height` class.

### Actual Behavior
The `<v-progress-circular>` components are positioned at the top of the `<v-img>` components when loading. This is because the `fill-height` class no longer exists for some reason.
But, if we place the `<v-spacer>` back in the `<v-app-bar>`, then `fill-height` magically returns and everything is positioned correctly.

### Reproduction Link
<a href="https://github.com/TrevinAvery/vuetify-missing-fill-height" target="_blank">https://github.com/TrevinAvery/vuetify-missing-fill-height</a>

### Other comments
Simply uncomment line 20 of `App.vue` to see the difference. Try inspecting the placeholder element and searching for the `fill-height` class.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
