### ISSUE TITLE
Slider track do not compute size correctly

### ISSUE THREAD

**Issue by talski** [vuetifyjs/vuetify#1391]
You can reproduce this in the official doc page

### Steps to reproduce
Drag the slider at the beggining or ending

### Versions
0.14

### What is expected ?
the track should be shown immediately after dragging the slider

### What is actually happening ?
![vuetify-bug](https://user-images.githubusercontent.com/740549/29441438-580be9e8-8399-11e7-9782-d491f5807d7b.gif)

### Reproduction Link
https://codepen.io/anon/pen/LjQjZZ

**Comment by nekosaur** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please edit the issue with the required information, thank you.

**Comment by talski** [comment]
updated

**Comment by jacekkarczmarczyk** [comment]
It's affected by the following lines in `calculateScale (scale)`, however I don't understand what `thumbLabel` has to do with it so i refrain from fixing it @johnleider 

```
if (scale < 0.02 && !this.thumbLabel) {
          return 0
        }
```

**Comment by talski** [comment]
I've changed it to 0.01 and it worked, but I don't know why this if statement is needed
