### ISSUE TITLE
[Bug Report][2.5.6] Dynamic steps on stepper do not allow vertical line

### ISSUE THREAD

**Issue by timothymarois** [vuetifyjs/vuetify#13910]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at codepen to reproduce the problem. Vertical line will not work if you use dynamic steps because of for requires key. 

### Expected Behavior
Vertical line should still appear, or at least have a wrapper to allow a root element 

### Actual Behavior
Vertical line is missing because the div blocks to css that creates the line

### Reproduction Link
<a href="https://codepen.io/timothymarois/pen/NWjRGVx" target="_blank">https://codepen.io/timothymarois/pen/NWjRGVx</a>

**Comment by timothymarois** [comment]
It might be that we need to adjust the CSS, so moving the border line to this would solve it. 

```
.v-application--is-ltr .v-stepper--vertical .v-stepper__content
```

**Comment by timothymarois** [comment]
As a quick fix for my project, I'll run this code to override it: 

```
.v-application--is-ltr .theme--light.v-stepper--vertical div:not(:last-child) .v-stepper__content {
    border-left: 1px solid rgba(0,0,0,.12);
}
```

**Comment by KaelWD** [comment]
Why are you adding the extra div? It works fine without it.

**Comment by timothymarois** [comment]
Because without a root element in a for loop to bind key, it's not valid. The CSS needs to be fixed, otherwise dynamic steps render different visual results.

**Comment by KaelWD** [comment]
You can use a separate key for each element:
```html
<v-stepper-step :key="step.id + '-step'" />
<v-stepper-content :key="step.id + '-content'" />
```
