### ISSUE TITLE
[Documentation] Ask to open translation for Chinese Traditional (Taiwan) on Crowdin

### ISSUE THREAD

**Issue by toto6038** [vuetifyjs/vuetify#13917]
### Problem to solve
The crowdin platform of Vuetify currently only allows translation for Chinese Simplified, which prevents contributors from translating the documentation into Chinese Traditional.

### Proposed solution
Let the translation project administrator open Chinese (Traditional).

**Comment by MajesticPotatoe** [comment]
Chinese Traditional has been added.
<https://crowdin.com/project/vuetify/zh-TW>
