### ISSUE TITLE
[Documentation] Search bar is inefficient

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#13922]
### Environment

**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Since the update to the docs i've been annoyed by the way the searchbar behaves.
When you search something it looks like the first results are the most irrelevant.

Example: search `list` or `VList` you'd expect the vlist component page to be the first result, it's the 9th
antoher example: search `text field` you'd expect the text field page (https://vuetifyjs.com/en/components/text-fields/) to be the fist one, but you'd have to scroll in the search results to find it.

![image](https://user-images.githubusercontent.com/1246691/125461114-f5581081-5202-4a73-9ea1-a3cc1fba7975.png)

**Comment by MajesticPotatoe** [comment]
likely has to do with a combination of the results returned from Algolia + sorting
<https://github.com/vuetifyjs/vuetify/blob/74ecaa9a6b918ad24f065ec1e84a2ffcaeb3cb2f/packages/docs/src/layouts/default/Search.vue#L141-L150>

**Comment by mcfarljw** [comment]
I also find it less helpful than what it was before when searching for things. I often find myself just manually navigating to what I need using the sidebar.

**Comment by ricardovanlaarhoven** [comment]
> I also find it less helpful than what it was before when searching for things. I often find myself just manually navigating to what I need using the sidebar.

Exactly what i do, and now that I've made this issue and i see the effort that vuetify put's in it, I regret not creating it earlier

**Comment by johnleider** [comment]
@KaelWD Do you have any comments regarding this? I know that I've expressed these same concerns.

**Comment by KaelWD** [comment]
We have to sort the results alphabetically because of #11349. If groupBy allowed unsorted arrays we could sort by relevance instead.
