### ISSUE TITLE
v-select - option "auto" is not worked (supplemented)

### ISSUE THREAD

**Issue by chim666** [vuetifyjs/vuetify#1392]
### Steps to reproduce
1. Click on select

### Versions
Stopped working in the 0.14.9

### What is expected ?
Centers list on selected element. Highlight selected item.

### What is actually happening ?
<img src='https://i.imgur.com/7WZEBQJ.gif' />
Centers list on begin list. Not Highlight  selected item.

### Reproduction Link
https://codepen.io/anon/pen/braWEN?editors=1010#0

**Comment by johnleider** [comment]
I can confirm that this particular bug was fixed when I addressed #1377

**Comment by chim666** [comment]
I did not miss the "auto" property in this example. Look at the GIF

**Comment by johnleider** [comment]
I never said that you did
