### ISSUE TITLE
[Bug Report][3.0.0-alpha.9] Button Prepend-icon sizing not inherited from button

### ISSUE THREAD

**Issue by Schloemicher** [vuetifyjs/vuetify#13929]
### Environment
**Vuetify Version:** 3.0.0-alpha.9
**Vue Version:** 3.1.4
**Browsers:** Chrome 91.0.4472.124
**OS:** Linux x86_64

### Steps to reproduce
Add v-btn with preprend-icon attribute and size attribute like x-small etc...

### Expected Behavior
prepended icon inherits size from button

### Actual Behavior
prepended icon keeps default size

### Reproduction Link
<a href="https://codepen.io/schloemicher/pen/dyWvzKj" target="_blank">https://codepen.io/schloemicher/pen/dyWvzKj</a>

### Other comments
Could be the same problem with other props

**Comment by KaelWD** [comment]
This has already been fixed.
