### ISSUE TITLE
[Feature Request] v-stepper create next steps content only when accessed

### ISSUE THREAD

**Issue by crThiago** [vuetifyjs/vuetify#13934]
### Problem to solve
When adding a v-stepper all the steps contents are rendered, the ideal would be to render only the content of the current step

### Proposed solution
The v-expansion-panels component works that way, maybe it would be a solution to copying itself

**Comment by K-Schaeffer** [comment]
Yep, I noticed this behavior too, It would be great to render only when the step is active.
