### ISSUE TITLE
[Bug Report][2.5.6] v-textarea color completely ignored

### ISSUE THREAD

**Issue by rmirabelle** [vuetifyjs/vuetify#13939]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.13
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Create v-textarea with color="{anything}"

### Expected Behavior
text matches selected color

### Actual Behavior
color attribute summarily ignored

### Reproduction Link
<a href="https://codepen.io/rmirabelle/pen/gOWRgER" target="_blank">https://codepen.io/rmirabelle/pen/gOWRgER</a>

**Comment by KaelWD** [comment]
It isn't ignored, it only affects the underline and the label when focused. To make the text always white you can use the `dark` prop or override it with CSS.
