### ISSUE TITLE
Navbar responsive on small devices?

### ISSUE THREAD

**Issue by sylvaincaillot** [vuetifyjs/vuetify#1394]
### Steps to reproduce
Visit the Vuetify home page https://vuetifyjs.com/ website on your smartphone, and scroll down in order to show the navigation bar

### Versions
Chrome 59 on Android 5.0.1

### What is expected ?
I would expect to see the 'Documentation' and 'Updates' menu items in the responsive navigation bar. In fact, I was expecting to see the 3 line menu icon (hamburger icon) on my smartphone in order to access the different menu items.

### What is actually happening ?
I see only the Documentation menu item and no hamburger icon.
I just want to be sure that the navigation bar is responsive in Vuetify before going further with this library which looks very nice.

### Reproduction Link
https://vuetifyjs.com/

**Comment by nekosaur** [comment]
The navbar is not available from the home screen. You need to enter the documentation for it to show up.

**Comment by sylvaincaillot** [comment]
Sorry for the misunderstanding.
My issue is how the top menu bar behaves in the home page of the vuetify website. 
When you scroll down on a deskop/laptop, you see the documentation and updates items appearing on the right in the header menu.

However, on a small device, the ''updates'' item disappears. It doesn't seem to be a normal behaviour. 
We should see the hamburger icon instead that would show the documentation and updates menu items by clicking on it.

Hope it's clear.

Thank you for your feedback.
S.
