### ISSUE TITLE
[Bug Report][2.5.5] VTabs don't go on the right when a v-menu (with v-btn as activator) is the first element of Vtabs

### ISSUE THREAD

**Issue by Raserber** [vuetifyjs/vuetify#13944]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Firefox 89.0
**OS:** Windows 10

### Steps to reproduce
* add a v-tabs component in a v-app-bar.
* add a VMenu as Vtabs in the first elements
* add attribute "right" on Vtabs

### Expected Behavior
can add a v-menu on VTabs element without problems
* with a v-btn as activator can drag menu on the right with the right attribute

### Actual Behavior
It's work when v-menu isn't the first element.

### Reproduction Link
<a href="https://codepen.io/Raserber/pen/qBmjRMB" target="_blank">https://codepen.io/Raserber/pen/qBmjRMB</a>

**Comment by KaelWD** [comment]
Workaround: `<v-btn class="ml-auto">`

@johnleider any idea why you used a margin here instead of `justify-content: flex-end`? https://github.com/vuetifyjs/vuetify/blob/13545ab4df30a1d4bdd98736c5980b3db5d93e42/packages/vuetify/src/components/VTabs/VTabs.sass#L169-L183

**Comment by johnleider** [comment]
> margin-left: auto

I don't remember. The last set of changes is from years ago so your guess is as good as mine.
