### ISSUE TITLE
[Bug Report][2.5.6] v-slider performance problems since 2.4.8

### ISSUE THREAD

**Issue by huazhechen** [vuetifyjs/vuetify#13943]
### Environment
**Vuetify Version:** 2.5.6
**Last working version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
add a v-slider
serve to localhost
access remotly from browser
(if on windows, press F12 and debug as mobile device)

### Expected Behavior
v-slider works as expected

### Actual Behavior
when drag the thumb, the thumb moves very slow

### Reproduction Link
<a href="https://codepen.io/huazhechen/pen/rNmwGmm" target="_blank">https://codepen.io/huazhechen/pen/rNmwGmm</a>

**Comment by KaelWD** [comment]
It's only slow for me if devtools is open, it's fine on a real (and quite old) phone.

**Comment by huazhechen** [comment]
> It's only slow for me if devtools is open, it's fine on a real (and quite old) phone.

2.4.5 is ok in devtools, there must be something wrong.
2.4.6 broken slider draggable in touch and 2.4.8 fixed that, it is a clue.

**Comment by KaelWD** [comment]
> 2.4.6 broken slider draggable in touch

ed0b0ca7a0ab81671a0757d8d2c00b104c61b245

> 2.4.8 fixed that

89b55e28750e39c4c6baab24d9b891e03eb35e8f

Both completely unrelated to this - eabff8a657e25100e0cfe063d0d950b1ec02466d added a transition on mousemove. As this only happens with devtools open it is not a real bug.

**Comment by huazhechen** [comment]
> > 2.4.6 broken slider draggable in touch
> 
> [ed0b0ca](https://github.com/vuetifyjs/vuetify/commit/ed0b0ca7a0ab81671a0757d8d2c00b104c61b245)
> 
> > 2.4.8 fixed that
> 
> [89b55e2](https://github.com/vuetifyjs/vuetify/commit/89b55e28750e39c4c6baab24d9b891e03eb35e8f)
> 
> Both completely unrelated to this - [eabff8a](https://github.com/vuetifyjs/vuetify/commit/eabff8a657e25100e0cfe063d0d950b1ec02466d) added a transition on mousemove. As this only happens with devtools open it is not a real bug and will not be fixed.

It's slow in my phone(MI 10)'s browsers, please check more phones：
https://user-images.githubusercontent.com/4993748/126177467-0cf06e61-8fda-4f32-b213-c1227ec2e354.mp4

**Comment by KaelWD** [comment]
Ok which browser is that? Chrome 91 on redmi note 4:

https://user-images.githubusercontent.com/16421948/126178302-8ae89529-de0f-4516-a287-fe50034eb1b8.mp4

Firefox 90 is the same

**Comment by huazhechen** [comment]
MI's default browser, no remote debugging running.

**Comment by KaelWD** [comment]
That isn't supported: https://vuetifyjs.com/en/getting-started/browser-support/#browsers

**Comment by huazhechen** [comment]
Fine.
But it's slow if devtools is open, and we don't know why, it's still a risk for code.
