### ISSUE TITLE
[Feature Request] `ThemeDefinition` is not exported

### ISSUE THREAD

**Issue by HippolyteQuief** [vuetifyjs/vuetify#13949]
### Problem to solve
In the doc, it is said we can import `ThemeDefinition` but got an error. When checkink `entry.d.ts`, we can see this definition is not exported. 

### Proposed solution
Export `ThemeDefinition` and `ThemeOptions` and `VariationsOptions` or update the doc without `ThemeDefinition`

**Comment by KaelWD** [comment]
Duplicate of #13901
