### ISSUE TITLE
[Documentation] I want to refer to the official website's navigation-drawer

### ISSUE THREAD

**Issue by TonyPythoneer** [vuetifyjs/vuetify#13948]
### Problem to solve

![image](https://user-images.githubusercontent.com/10459119/126202808-0891ffec-c2d6-44e0-93ff-91ad829f57e7.png)

Out of curiosity, I want to this component about how to implement it. I haven't found any information in the official document.

### Proposed solution

if it's available to you, could you give me a link about the implementation of the `navigation-drawer`? thx

**Comment by KaelWD** [comment]
It's all on github: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/layouts/default/settings/Settings.vue

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
