### ISSUE TITLE
[Bug Report][2.5.6] VTreeview doesn't show newly added children if the whole tree gets recomputed on children insertion

### ISSUE THREAD

**Issue by devnoel** [vuetifyjs/vuetify#13945]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 88.0.4324.96
**OS:** Linux x86_64

### Steps to reproduce
1. Create an array of treeview items in `data` (with each item having a parent id)
1. Create a `computed` that builds a tree structure from this array (by putting nodes with parent ids in the referenced nodes' `children` array)
1. Use the tree in the `items` prop of a `v-treeview`
1. Push new items to the array with parent ids pointing to existing nodes in the tree

### Expected Behavior
The `v-treeview` should update to match the new structure.

### Actual Behavior
The `v-treeview` shows the same nodes as before.

### Reproduction Link
<a href="https://codepen.io/devnoel42/pen/yLbXxjm" target="_blank">https://codepen.io/devnoel42/pen/yLbXxjm</a>

### Other comments
- This is not a reactivity issue on my side. The computed runs every time the array is updated (see console output in the linked codepen).
- When I used the filter functionality on the treeview to filter for nodes I added but the treeview didn't show, it correctly displayed the ancestor folders of the "hidden" nodes - so the filter function "knew" the nodes were actually there. (Not included in reproduction codepen.)

**Comment by KaelWD** [comment]
> This is not a reactivity issue on my side

Yes it is, the array you create with `item.children = []` is not reactive. If you replace it with `this.$set(item, 'children', []` then it works. 

https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
