### ISSUE TITLE
v-btn :to property not work from dynamic data method

### ISSUE THREAD

**Issue by alterhu2020** [vuetifyjs/vuetify#1395]
### Steps to reproduce
Code could be as following for the `v-toolbar` component:
```
 <v-toolbar fixed :dense="false" class="primary" :dark="true" scroll-off-screen scroll-target="#scrolling-main">
            <!-- <v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon> -->
            <v-toolbar-title>BecauseQA</v-toolbar-title>
            <v-spacer></v-spacer>
            <v-toolbar-items class="hidden-sm-and-down" v-for="item in toolbaritems" :key="item.text">
                <v-btn flat :to="item.to">{{ item.text }}</v-btn>
            </v-toolbar-items>
            <v-spacer></v-spacer>
            <v-toolbar-items class="hidden-sm-and-down">
                <v-btn flat ripple :to="{name: 'login'}">SIGN IN/SIGN UP</v-btn>
            </v-toolbar-items>
        </v-toolbar>
```
The ` data` method in script section like below:
```
<script>
    export default {
      data: function () {
        return { 
          toolbaritems: [
            {
              text: 'Home',
              to: "{name: 'index'}" // the router path is: /index
            },
            {
              text: 'Documents',
              to: "{name: 'uploader'}"  // the router path is: /uploader
            },
            {
              text: 'About',
              to: "{name: 'about'}"  // the router path is: /about
            }
          ],
          mini: false,
          right: null
        }
      }

    }
</script>
```
Here you can see I use the router name for the  path navigation instead of vue-router's `path`.
### Versions
1. Latest Vue 2.4.2
2. Latest Vuetify 0.14.11 
### What is expected ?

1. Click each link in toolbar it should work and navigate to correct page
### What is actually happening ?

1. Like clicking the `Home` toolbar item ,it will go to http://localhost:7070/%7Bname:%20'index'%7D
it seem that it parsed to a string ` /{name: 'index'}` ,not expected vue-router path `/index`
### Reproduction Link

 I think no need to put a url link here, just put v-btn reference document: https://vuetifyjs.com/components/buttons
```

to   String, Object | javascript:; | For router, this is passed to the "to" prop
-


```

**Comment by nekosaur** [comment]
You are actually defining the `to` variables as strings, not objects. 

This will be a string, not an object: `to: "{name: 'index'}"`. Remove quotation marks.

**Comment by alterhu2020** [comment]
great tips ,that helps me a lot ,thanks @nekosaur
