### ISSUE TITLE
transparent v-edit-dialog/menu in table

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1396]
### Steps to reproduce

Open https://codepen.io/anon/pen/NvyxNL, click "14%" and open select

### Versions
0.14.11/2.4.2

### What is expected ?
Dialog/select should not be transparent

### What is actually happening ?
![image](https://user-images.githubusercontent.com/15625235/29447072-46a3a77a-83f0-11e7-89a3-763b6ec1e57a.png)

### Reproduction Link
https://codepen.io/anon/pen/NvyxNL

**Comment by nekosaur** [comment]
This has already been fixed in dev

**Comment by bobeagle** [comment]
Hi is this released? i'm using 1.2.4 and seems it's still transparent
