### ISSUE TITLE
[Bug Report][3.0.0-alpha.9] Does Vue 3 use vuetify loader?

### ISSUE THREAD

**Issue by MrHBS** [vuetifyjs/vuetify#13966]
### Environment
**Vuetify Version:** 3.0.0-alpha.9
**Vue Version:** 3.1.5
**Browsers:** Chrome 86.0.4240.93
**OS:** iOS 14.4

### Steps to reproduce
T

### Expected Behavior
T

### Actual Behavior
T

### Reproduction Link
<a href="https://jsfiddle.net/hi/hi/" target="_blank">https://jsfiddle.net/hi/hi/</a>

**Comment by KaelWD** [comment]
Not yet

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by MrHBS** [comment]
@KaelWD I am sorry Kael I meant vuetify 3, not Vue 3

**Comment by KaelWD** [comment]
Still no, it's on my to do list

**Comment by MrHBS** [comment]
So I guess components are not tree shaken?

**Comment by KaelWD** [comment]
They can be if you import them manually. You shouldn't be using v3 in production yet so worrying about bundle size is counterproductive.

**Comment by MrHBS** [comment]
Thank you Kael!

**Comment by MrHBS** [comment]
@KaelWD So sorry Kael one last thing. Doesn’t createVuetify already does this?
