### ISSUE TITLE
[Feature Request] Ability to change overflow-y for v-select

### ISSUE THREAD

**Issue by nmalchy** [vuetifyjs/vuetify#13967]
### Problem to solve
There are times where the best solution is to just see every option instead of having to scroll, for example right now, I have only 8 options to choose from, but Vuetify enforces a scroll-bar, now I have the extra step of scrolling down to see all the options, and 8 options isn't that much, even if I add "dense" prop there is still a scrollbar, it would be nice to be able to not have to always scroll.

### Proposed solution
Add a prop "scroll" or "overflow", and just have it modify the overflow-y CSS attribute on the v-select

**Comment by KaelWD** [comment]
```
:menu-props="{ maxHeight: 'auto' }"
```
