### ISSUE TITLE
[Bug Report][3.0.0-alpha.9] Avatar/icon size has no effect on image/SVG avatars/icons in `<v-list>`

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13974]
### Environment
**Vuetify Version:** 3.0.0-alpha.9
**Vue Version:** 3.1.5
**Browsers:** Chrome 92.0.4515.107
**OS:** Windows 10

### Steps to reproduce
See reproduction.

There are 3 icon types, and only the font-based icon set appears to be affected by the `size` prop.

The `imgIconSet` uses an `img` element directly.

I wrapped the SVG icons with an `i` element, to match the `VSvgIcon` component (it's not possible to reference the other built-in icon sets using Codepen/skypack [the referencing of Sass files breaks the build, so this will probably only be fixed if/when the Sass imports are removed]).

This might have something to do with the `.v-avatar > *` styling, but I'm not sure.

### Expected Behavior
Ability to resize list item icons of any type (font, image, SVG), with correct alignment.

### Actual Behavior
Not working, unless I'm missing something obvious.

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/KKmVOmB" target="_blank">https://codepen.io/glen-84/pen/KKmVOmB</a>

**Comment by KaelWD** [comment]
@johnleider Is this intentional? v-list-item-avatar overrides the size of anything in it based on list density:
https://github.com/vuetifyjs/vuetify/blob/65fa6d36a7b2c04cf3cb96e22c6d9c5c0169d1d6/packages/vuetify/src/components/VList/VListItem.sass#L46-L50

**Comment by johnleider** [comment]
fixed by 8018fb08e
