### ISSUE TITLE
[Bug Report][2.4.10] vuetify as WC

### ISSUE THREAD

**Issue by 1shaked** [vuetifyjs/vuetify#13989]
### Environment
**Vuetify Version:** 2.4.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.107
**OS:** Mac OS 10.15.7

### Steps to reproduce
npm install 
npm run wcin
add to demo.html 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css">

open with live server

### Expected Behavior
to see all the app I have with vuetify

### Actual Behavior
Not seeing any CSS effect on my web component

### Reproduction Link
<a href="https://github.com/1shaked/vuetufy-wc" target="_blank">https://github.com/1shaked/vuetufy-wc</a>

I am trying to build my project as a web component but I can not do it with vuetify.
When I include vuetify I am not getting any of the styles. 
I already tried [this link](https://stackoverflow.com/questions/55467240/how-do-you-include-vuetify-inside-web-component)
steps to reproduce install and run wc and I added the ```<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css">``` inside
also I tried to add import 'vuetify/dist/vuetify.min.css' into plugins/vuetify.js

**Comment by rivkatiktak** [comment]
I have the same issue here!

**Comment by MajesticPotatoe** [comment]
duplicate #5054
