### ISSUE TITLE
[Documentation] Grow demo of Tabs not showing correctly if Dark theme selected

### ISSUE THREAD

**Issue by ozgurg** [vuetifyjs/vuetify#13980]
### Environment

**Browsers:** Chrome 92.0.4515.107
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the grow demo of Tabs in the docs when Dark theme selected, you'll see.

### Expected Behavior
Texts must be dark like Mixed theme.

### Actual Behavior
Texts are white, background is yellow. So, hard to read the texts.
<img width="446" alt="Screenshot at Jul 24 14-47-16" src="https://user-images.githubusercontent.com/6717356/126867457-7f127424-aa61-41e0-9cec-edb4f04e325e.png">

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tabs/#grow" target="_blank">https://vuetifyjs.com/en/components/tabs/#grow</a>

**Comment by lioneaglesolutions** [comment]
Still an issue in V3

**Comment by johnleider** [comment]
This is resolved.
