### ISSUE TITLE
[Feature Request] Style Intervals separately for each category

### ISSUE THREAD

**Issue by WobblySlug** [vuetifyjs/vuetify#13984]
### Problem to solve
Categories and intervals don't seem to relate to each other. Intervals appear to be for the entire calendar, regardless of each category column.

I'd like to style each interval "column" separately, with respect to the category.

See: https://github.com/vuetifyjs/vuetify/discussions/13971

### Proposed solution
Provide a way to check which category an interval is for, within the "interval-style" method.

**Comment by WobblySlug** [comment]
Side note: Please let me know if this is already possible, but I've spent hours trying to come up with a solution and I'm unable to :(

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/discussions/13971#discussioncomment-1050123
