### ISSUE TITLE
[Bug Report][3.0.0-alpha.9] CSS classes not created for custom theme colours

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13988]
### Environment
**Vuetify Version:** 3.0.0-alpha.9
**Vue Version:** 3.2.0-beta.5
**Browsers:** Chrome 92.0.4515.107
**OS:** Windows 10

### Steps to reproduce
Add a custom colour to a custom theme or to one of the built-in themes.

### Expected Behavior
CSS classes should be created for the custom colour.

### Actual Behavior
They're not. 🙂

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/YzVYLLz" target="_blank">https://codepen.io/glen-84/pen/YzVYLLz</a>

### Other comments
As discussed with @nekosaur on Discord.

**Comment by johnleider** [comment]
You are defining a custom variable for `green` which is already a generated helper class from SASS. Custom themes do not merge with any defaults and require every property to be defined.

<https://codepen.io/johnjleider/pen/OJxJgYY>

**Comment by glen-84** [comment]
@johnleider,

I'm still a bit confused here, because while your example does work, I can't seem to modify it to work with `dark` instead of `light`.

I've tried setting `defaultTheme: 'dark'`, adding `theme="dark"` to `v-app`, etc.

I really hope that I'm not missing something obvious.

**Comment by glen-84** [comment]
@johnleider,

Thanks ... but if you comment out the `light` theme, then the classes disappear ...
https://codepen.io/glen-84/pen/rNGOEmQ?editors=1010

What if you just want a dark theme? You're forced to define random light theme colours?

**Comment by nekosaur** [comment]
It's because of this https://github.com/vuetifyjs/vuetify/blob/5036ca135d655c1248b0039eeab9759561709dfa/packages/vuetify/src/composables/theme.ts#L297

Which as you've demonstrated is not a correct assumption in all cases

**Comment by glen-84** [comment]
@nekosaur, is it not possible to use the currently active theme object when generating the CSS classes?

**Comment by KaelWD** [comment]
There isn't really a "currently active theme", they're all generated at the same time.

**Comment by glen-84** [comment]
I meant like the configured `defaultTheme`, or is that information not available?
