### ISSUE TITLE
[Feature Request] unknown custom element in Vite project with Vue2

### ISSUE THREAD

**Issue by yaohuangguan** [vuetifyjs/vuetify#13986]
### Problem to solve
vite2 project cannot use vuetify , console error unknown custom element, did you forget to register your component.....

### Proposed solution
vite2 project cannot use vuetify , console error unknown custom element, did you forget to register your component.....

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
