### ISSUE TITLE
[Bug Report][2.5.7] Touch-scrolling a div causes v-tabs to change tabs

### ISSUE THREAD

**Issue by Agendum** [vuetifyjs/vuetify#13994]
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Edge 91.0.864.71
**OS:** Windows 10

### Steps to reproduce
1. Launch the JSFiddle.
1. If you don't have a touch-screen, change the browser into a device mode so you can imitate it.
1. Touch-scroll the div from left-right and right-left so that it scrolls.

### Expected Behavior
Only the scrolling div scrolls.

### Actual Behavior
If there is a tab in the target direction, there will be a tab change.

### Reproduction Link
<a href="https://jsfiddle.net/CodeVirtue/zab2junL/" target="_blank">https://jsfiddle.net/CodeVirtue/zab2junL/</a>

**Comment by yuwu9145** [comment]
Switch tabs by touch swipe action in touching device is a nice default feature comes with [v-window](https://vuetifyjs.com/en/components/windows/).

I guess disable touch event for switching tabs in this case should be done in user's land. @Agendum you can use `touchless` prop in `v-tabs-items` (https://vuetifyjs.com/en/api/v-tabs-items/#api-props) to disable touching event of switching tabs.

Workaround codes can be done by changing to follow sample:

```javascript
<template>
  <v-container>
    <v-tabs  v-model="tab">
      <v-tab>One</v-tab>
      <v-tab>Two</v-tab>
    </v-tabs>
    <v-tabs-items  v-model="tab" :touchless="true" >
        <v-tab-item >
          <div class="scrolling-div" tabindex="0">
            Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test
          </div>
        </v-tab-item>
        <v-tab-item >
          <div class="scrolling-div" tabindex="1">
            Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test
          </div>
        </v-tab-item>
      </v-tabs-items>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    tab: null,
  }),
  mounted () {
  },
};
</script>

<style>
.scrolling-div {
  width: 200px;
  height: 100px;
  overflow: auto;
  white-space: nowrap;
}
</style>


```
