### ISSUE TITLE
[Bug Report][2.4.11] v-autocomplete - cannot read property 'getTiles' of undefined" when use extended component

### ISSUE THREAD

**Issue by ricardo17coelho** [vuetifyjs/vuetify#13997]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
I created a base component that extends v-autocomplete. (see codesandbox.io)
(I could not complete the codesandbox because the import form VAutocomple fails, i dont know why, locally works fine)
I use this base-component to create another component: country-field.vue

so that the search works i replace the filter:
```
:filter="customFilter"
```
```
        customFilter (item, queryText) {
            const countryName = item.name.toLowerCase()
            const countryCode = item.code.toLowerCase()
            const searchText = queryText.toLowerCase()
            
            return countryName.indexOf(searchText) > -1 ||
                countryCode.indexOf(searchText) > -1
        }
```

items looks like:
```
[{
    "name": "Afghanistan",
    "code": "AF"
}, {
    "name": "Åland Islands",
    "code": "AX"
}, {
    "name": "Albania",
    "code": "AL"
},
...
]
```
![image](https://user-images.githubusercontent.com/37732431/127334121-18011167-0a5b-4ead-8405-014d9c60741f.png)

Filter works fine but when when i write  3./4. char, i become an error.
![image](https://user-images.githubusercontent.com/37732431/127333660-f1bac9b8-9242-4517-90c0-33a09bc7421e.png)
![image](https://user-images.githubusercontent.com/37732431/127333799-bafbd8ba-3def-4371-9fbf-0d0423611808.png)

### Expected Behavior
No error

### Actual Behavior
Error:  Error in nextTick: "TypeError: Cannot read property 'getTiles' of undefined"

The error  occured on this line: https://github.com/vuetifyjs/vuetify/blob/0aa692aa8a7a13de2e9c8f51cd9f52f8d10143df/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L229

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2-forked-9mvis?file=/src/components/BaseAutocomplete.vue" target="_blank">https://codesandbox.io/s/vuetify-2-forked-9mvis?file=/src/components/BaseAutocomplete.vue</a>

**Comment by lucasrusso95** [comment]
Have any workaround for it ?

**Comment by KaelWD** [comment]
https://stackoverflow.com/a/70064606/2074736

**Comment by hadise-shaker** [comment]
is there any solution? i still have same problem

**Comment by pate313373** [comment]
> https://stackoverflow.com/a/70064606/2074736

What do you want to say?
I'm doing exactly like suggested in this link and the problem still persists.
