### ISSUE TITLE
[Bug Report][2.0.0] Duplicate Date Picker issue with mapped events

### ISSUE THREAD

**Issue by mdpnixon** [vuetifyjs/vuetify#14002]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.7
**Browsers:** Firefox 89.0
**OS:** Windows 10

### Steps to reproduce
Click on an event, then click on the text field below date to bring up date picker.

### Expected Behavior
Date picker for event that is clicked will open.

### Actual Behavior
Date picker for every event that is in view will open

### Reproduction Link
<a href="https://codepen.io/mdpnixon/pen/RwVMKdJ?editors=111" target="_blank">https://codepen.io/mdpnixon/pen/RwVMKdJ?editors=111</a>

**Comment by jacekkarczmarczyk** [comment]
Vuetify 1.5 is no longer supported

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by mdpnixon** [comment]
> EDIT: also you're using same v-model for all date pickers

sorry, I'm new to Vue. How would I set a different v-model for each date picker?
