### ISSUE TITLE
[Bug Report][2.5.7] Incorrect selection in v-data-table with show-select enabled

### ISSUE THREAD

**Issue by betanets** [vuetifyjs/vuetify#14006]
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
1. Create a *v-data-table* with *show-select* prop enabled
2. Set items-per-page-options to some value (5 by example)
3. Add some items which **completely** fill 1st page and **partially** fill 2nd page (8 items by example)
4. Check 4th item on a 1st page. It'll be checked
5. Move to 2nd page and select 8th item. It will not be checked
6. Move to 1st page and select 1st, 2nd or 3rd item. It'll be checked
7. Move to 2nd page and select 8th item. It'll be checked then

### Expected Behavior
Items should always be available to check

### Actual Behavior
Items are not available to be checked when last selected index on previous page > selection index on current page

### Reproduction Link
<a href="https://codepen.io/betanet/pen/VwbXQEe" target="_blank">https://codepen.io/betanet/pen/VwbXQEe</a>

### Other comments
There's some stacktrace in a browser console:
```
TypeError: Cannot read property 'toString' of undefined
    at o.select (VDataIterator.js:184)
    at Object.select (VDataIterator.js:239)
    at input (VDataTable.js:457)
    at VSimpleCheckbox.js:79
    at Array.forEach (<anonymous>)
    at click (VSimpleCheckbox.js:79)
    at ie (vue.runtime.esm.js:1863)
    at HTMLDivElement.n (vue.runtime.esm.js:2188)
    at HTMLDivElement.Qr.s._wrapper (vue.runtime.esm.js:6961)
```

**Comment by gwheeloc** [comment]
I'm seeing the same issue in our environment after updating to version 2.5.7.  The functionality works fine in version 2.5.6.

**Comment by toddkimball** [comment]
I can confirm this issue. We were not seeing this issue until after we updated to 2.5.7.  It appears to be caused by the following changes to VDataIterator.ts beginning on line 204:

`
 else {
        const lastEntryKey = getObjectValueByPath(this.selectableItems[this.lastEntry], this.itemKey)
        const lastEntryKeySelected = Object.keys(this.selection).includes(lastEntryKey.toString())
        if (this.shiftKeyDown && !this.singleSelect && emit) this.multipleSelect(lastEntryKeySelected, emit, selection, index)
}
`
