### ISSUE TITLE
menu is opened again

### ISSUE THREAD

**Issue by JankoHrasko7** [vuetifyjs/vuetify#1402]
### Steps to reproduce
Firefox
1. click on data picker and select date
2. Click again and choose another date
Datapicker is opened again
### Versions

https://jsfiddle.net/aston77martin/cz825x4o/4/
### What is expected ?

Menu (data picker) shoudn't opened again after  select a date
### What is actually happening ?

Datapicker is opened again
### Reproduction Link

https://jsfiddle.net/aston77martin/cz825x4o/4/

**Comment by nekosaur** [comment]
I don't understand. Are you saying the date-picker should not appear when you click on the input field if you have already selected a date?

If so, then I disagree with you. What if the user selected the wrong date and want to correct it?

**Comment by JankoHrasko7** [comment]
If you click again, data picker have to appear. But if you select other date it should disappear. But it shows again. It is a bug.

**Comment by johnleider** [comment]
That is because you failed to define a **menu** data property. This was causing weird behavior when expecting the model to actually change when it wasn't defined. As soon as you add it, it works as expected.
