### ISSUE TITLE
[Bug Report][2.5.8] Text field with v-model.number : unnecessary update

### ISSUE THREAD

**Issue by dev-oups** [vuetifyjs/vuetify#14020]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Firefox 90.0
**OS:** Windows 10

### Steps to reproduce
If you want to change the value from "0.001" to "0.002" when you remove the "1" with backspace all zeros are removed.

### Expected Behavior
Keep input at least while user is typing

### Actual Behavior
Input is updated with "0" (parseFloat result?)

### Reproduction Link
<a href="https://jsfiddle.net/w7v2r5dq/1/" target="_blank">https://jsfiddle.net/w7v2r5dq/1/</a>

**Comment by MajesticPotatoe** [comment]
related / duplicate #13350

tldr, add `@input="num = Number($event)"`

**Comment by dev-oups** [comment]
Thank you but it does not work.
Issue is the same and you cannot enter a ngative number with this.

Similar issue when typing "-0.1" the minus is removed while typing.

**Comment by pg-ahenry** [comment]
apologies (i meant `@input="value = $event"`) but the issue is upstream and how custom modifiers work in custom components with v-model. you are likely better off doing something like `@input` to apply some custom modification.

**Comment by MajesticPotatoe** [comment]
apologies (i meant @input="value = $event") but the issue is upstream and how custom modifiers work in custom components with v-model. you are likely better off doing something like @input to apply some custom modification.

**Comment by dev-oups** [comment]
Okay thanks
