### ISSUE TITLE
[Feature Request] new v-calendar date api 

### ISSUE THREAD

**Issue by Ubugeeei** [vuetifyjs/vuetify#14034]
### Problem to solve
We will take a stab at getting the first day and the first day shown on the calendar for the month.
The last day of the first person displayed in the calendar is often needed in cursor pagination.
There are already APIs called start and end in the documentation, but these are a bit inconvenient since they don't actually retrieve the first and last days displayed.

### Proposed solution
I will implement a new API in this issue to solve the problem.

**Comment by johnleider** [comment]
We built a date composable that will be used across all of our date components https://vuetifyjs.com/en/features/dates/

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
