### ISSUE TITLE
[Bug Report][3.0.0-alpha.10] Breakpoints and containers do not match the MD spec

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14032]
### Environment
**Vuetify Version:** 3.0.0-alpha.10
**Vue Version:** 3.1.5
**Browsers:** Chrome 92.0.4515.131
**OS:** Windows 10

### Steps to reproduce
- View the spec [here](https://material.io/design/layout/understanding-layout.html) and [here](https://material.io/design/layout/responsive-layout-grid.html).
- View the Vuetify breakpoints [here](https://next.vuetifyjs.com/en/features/display-and-platform/) and [here](https://github.com/vuetifyjs/vuetify/blob/00e5391a9f9017c21ce3421d70241ff380038a04/packages/vuetify/src/styles/settings/_variables.scss#L90).
- Note the differences. (body sizes don't match v-container sizes either)

### Expected Behavior
If the intent is to match the spec (which it seems is the case, given that there is a link to the MD spec in the documentation), then I would expect it to match exactly.

### Actual Behavior
It doesn't.

### Reproduction Link
n/a

### Other comments
I've opened an [issue](https://github.com/material-components/material-components-web/issues/7295) in the Material Components Web repository, as there appear to be inconsistencies between the spec and their own website/components. I'm not sure if 1040px is an ideal body/container width for desktop.

See also:
- [Introducing Material Design Guidance for Large Screens](https://material.io/blog/material-design-for-large-screens)
- [5 things you can do to prepare your app for large screens](https://events.google.com/io/session/b2f0dee6-b649-4e20-8ad6-69266e353f05?lng=en)
- [Material Baseline Design Kit](https://www.figma.com/community/file/778763161265841481)

**Comment by glen-84** [comment]
@johnleider @KaelWD,

After a message (actually 2) on Discord, a GitHub issue, and 2 Tweets (1 to `@materialdesign` and 1 to `@LiamSpradlin` and `@rodydavis`), there has been no meaningful response from Google, other than:

> I'm not so sure. We're in the middle of updating the entire site for Material You, and if the external site clashes with our branded Material implementation, we take the branded approach as it's better-parameterized for the future.
>
> The issue you filed should give you the right info

_(from Elliott on Discord)_

Are you able to make a decision without any additional information from Google? Do you want to update Vuetify's breakpoints and container widths to match the current spec?

I'd love to know so that I can make a decision regarding container widths for a new design.

**Comment by johnleider** [comment]
My thoughts are to add an option to opt into the new breakpoints and deprecate the current breakpoints for v4.
