### ISSUE TITLE
[Bug Report][2.5.8] v-progress-circular not working with faster value updates

### ISSUE THREAD

**Issue by ajmdev89** [vuetifyjs/vuetify#14047]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.13
**Browsers:** Chrome 92.0.4515.131
**OS:** Windows 10

### Steps to reproduce
* Set an interval with low iteration time
* Update value passed by prop each iteration

### Expected Behavior
* Value is updated and re-rendered into v-progress-circular

### Actual Behavior
* Value is upadted into prop but is never proper rendered

### Reproduction Link
<a href="https://codepen.io/ajmiAhorro/pen/JjNwqzR" target="_blank">https://codepen.io/ajmiAhorro/pen/JjNwqzR</a>

**Comment by nekosaur** [comment]
Disable the transition https://codepen.io/nekosaur/pen/LYyMKEy

**Comment by ajmdev89** [comment]
It works overriding css. But, is posible to do it via component prop? If i do this i am overriding this transition for entire app. In my opinion the component should have a prop to manage this feature.

**Comment by pg-ahenry** [comment]
> It works overriding css. But, is posible to do it via component prop? If i do this i am overriding this transition for entire app. In my opinion the component should have a prop to manage this feature.

not if you scope it or use css to cascade eg: <https://codepen.io/majesticpotatoe-the-bashful/pen/abWPgKy>
