### ISSUE TITLE
[Feature Request] Function to manually trigger the form field validation pop animation(reddened border, placeholder/text shake etc.)

### ISSUE THREAD

**Issue by max-fletcher** [vuetifyjs/vuetify#14042]
### Problem to solve
Currently you guys have the following 3 functions to pop validation animation or remove the pop animation:
this.$refs.form.validate()
this.$refs.form.reset()
this.$refs.form.resetValidation()
However these require people to define custom validation rules on the frontend.

### Proposed solution
It would be great if there was a way to cause the pop animation to happen whenever the dev wants to (using if-else etc.). I am suggesting a function to cause the pop to happen regardless or rules. It might be useful for people using back-end validation using frameworks instead of front-end validation.

**Comment by KaelWD** [comment]
You mean like this? https://codepen.io/kaelwd/pen/rNmorBO?editors=1010

Or do you want a `this.$refs.textField.animateError()`

**Comment by max-fletcher** [comment]
I suppose what you provided me is quite useful. I can't believe I didn't
notice this before. I can make this work with my backend validation. Thanks
a lot.

>

**Comment by max-fletcher** [comment]
BTW can I cancel that feature request ? Right now, after what you gave me,
I can't think of a reason to make this feature.

**Comment by Riotsmurf2** [comment]
You probably already know this but here is my idea:
Post the form to your database via API and have the validation come back(if validation fails), then update your rules variable with the validation that came back and run $refs.form.validate(), or force the field into an error state via props.

On the otherside i have always opted for using validation on the front AND backend. Backend being the more important piece and front-end being a user convenience.

**Comment by max-fletcher** [comment]
ikr. I did implement frontend validation but I was having difficulty using
backend validation on the text-fields themselves. Up until this point I was
using a v-alert but it didn't go well with the design. I already fixed my
app and it works like a dream.
