### ISSUE TITLE
[Bug Report][2.4.2] Failed to load resource: Google Fonts

### ISSUE THREAD

**Issue by AliRezaBeitari** [vuetifyjs/vuetify#14057]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 92.0.4515.131
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set a custom font for Vuetify using `defaultAssets` like this:
```
defaultAssets: {
    font: {
        family: 'IRANSans',
    },
}
```

### Expected Behavior
Don't put a stylesheet tag for Google Fonts

### Actual Behavior
It inserts the stylesheet tag for Google Fonts

### Reproduction Link
<a href="https://codepen.io/AliRezaBeitari/pen/KKmYZgK" target="_blank">https://codepen.io/AliRezaBeitari/pen/KKmYZgK</a>

### Other comments
I have manually imported the `IRANSans` using `@font-face` in my stylesheets but still I see a stylesheet tag in `<head>` with `href` set to `https://fonts.googleapis.com/css?family=IRANSans:100,300,400,500,700,900&display=swap`. And because this font is a custom local font, it cannot find the font in Google Fonts. I need remove this stylesheet tag!

**Comment by KaelWD** [comment]
The next module isn't by us, you want https://github.com/nuxt-community/vuetify-module/issues
