### ISSUE TITLE
[Bug Report][2.5.8] Glassmorph styling issue

### ISSUE THREAD

**Issue by Mert75** [vuetifyjs/vuetify#14053]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Edge 92.0.902.67
**OS:** Windows 10

### Steps to reproduce
Hover over the dropdown button

### Expected Behavior
Alerts should maintain their color

### Actual Behavior
Alerts highlight and styling changes randomly

### Reproduction Link
<a href="https://codepen.io/Mert75/pen/MWmxxEM" target="_blank">https://codepen.io/Mert75/pen/MWmxxEM</a>

### Other comments
Affected by the backdrop-filter in CSS, toggling that style will make it work as expected

**Comment by KaelWD** [comment]
This is just caused by the opacity transition on `.v-btn:hover::before` if it's at least 11x17px and only happens in chrome, you should probably report it to webkit instead.

**Comment by KaelWD** [comment]
Workaround:
```css
.v-btn {
  contain: layout;
}
```
