### ISSUE TITLE
[Bug Report][2.5.8] v-bottom-sheet bug when using v-expansion-panel

### ISSUE THREAD

**Issue by skadiD** [vuetifyjs/vuetify#14058]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Edge 92.0.902.73
**OS:** Windows 10

### Steps to reproduce
1.Create `v-bottom-sheet` with `v-expansion-panel`
2.Create a `button` and click it

### Expected Behavior
`v-expansion-panel-header`'s color will not change

### Actual Behavior
the color is changed 

### Reproduction Link
<a href="https://codepen.io/skadiD/pen/zYwXRBj" target="_blank">https://codepen.io/skadiD/pen/zYwXRBj</a>

**Comment by KaelWD** [comment]
v-bottom-sheet extends v-dialog so it traps focus by default, you can set `:retain-focus="false"` to disable this behaviour.

**Comment by skadiD** [comment]
thanks for your reply and it works.However,I don't find any information about `:retain-focus="false"` in the document
