### ISSUE TITLE
 [Bug Report][2.5.8] v-autocomplete, When you type in Chinese characters, you get unexpected results!!! help me!!!

### ISSUE THREAD

**Issue by ZLd150** [vuetifyjs/vuetify#14056]
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.13
**Browsers:** Chrome 92.0.4515.131
**OS:** Windows 10

### Steps to reproduce
I wrote notes in "Codepen"

### Expected Behavior
I don't understand how this BUG occurs, so no suggestions

### Actual Behavior
I don't understand how this BUG occurs, so no suggestions

### Reproduction Link
<a href="https://codepen.io/zld150/pen/GRmLMKV?editors=101" target="_blank">https://codepen.io/zld150/pen/GRmLMKV?editors=101</a>

### Other comments
Come on!!!
![1](https://user-images.githubusercontent.com/66229887/129471406-b11fc5f3-b9bc-4d51-9455-4c931f1cc763.gif)

**Comment by kallydev** [comment]
I think this is to be expected, as the input tool does not give the pre-selected content to the input element. You can reproduce it in Google search, and some localization is needed to get the effect of Bing and Baidu. This involves at least Chinese pinyin and Japanese romanization.

**Comment by ZLd150** [comment]
hank you for your advice!!!! good^_^

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
