### ISSUE TITLE
[Feature Request] Please add Mega Menu Support like TailwindCSS

### ISSUE THREAD

**Issue by Soverex** [vuetifyjs/vuetify#14067]
### Problem to solve
In my opinion, modern websites can no longer be imagined without mega menus. I think this is also not a huge effort, but extremely useful. I would be very happy if you develop this

### Proposed solution
Something like TailwindCSS made.

**Comment by DamianGlowala** [comment]
TailwindCSS, as the name itself may indicate, is a CSS framework and not a UI component library. Where did you see them make a mega menu component?

**Comment by Soverex** [comment]
Sorry it is Tailwind UI.
See here:
https://tailwindui.com/components/marketing/elements/flyout-menus
https://tailwindui.com/components/marketing/elements/headers

**Comment by KaelWD** [comment]
You can already do this with v-menu and custom css.
