### ISSUE TITLE
Feature Request: "Tabbed" Component (not VTabs)

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#1406]
A "tabbed" component that allows for more comprehensive content in the tab bar.

Please Note: This is not a request to replace (or extend the functionality of) `v-tabs`, since that already serves an excellent purpose for simple tab lists containing limited content.

Here are some examples of "tabbed" components being used on Google analytics and Firebase.

![screenshot_20170818_133410](https://user-images.githubusercontent.com/411270/29459195-d692d0ae-8422-11e7-888d-a9e42a2eed46.png)
![screenshot_20170818_133454](https://user-images.githubusercontent.com/411270/29459194-d68f1b08-8422-11e7-86d9-1c650f32eb39.png)

**Comment by nekosaur** [comment]
These types of tabs are possible with the current component with very little customization.

See https://codepen.io/anon/pen/Kvogzx for an example

**Comment by wernerm** [comment]
Thanks @nekosaur that seems doable
