### ISSUE TITLE
[Feature Request] Table of contents like your documentation site.

### ISSUE THREAD

**Issue by Riotsmurf2** [vuetifyjs/vuetify#14063]
### Problem to solve
I think there are a lot of cases specially in vue CLI apps where there are scrolling documentation like vuetifyjs.com or just scrolling in general where a table of contents would be great. Vuetify v-list component currently doesn't satisfy the nested table of contents and only provides a group that is a dropdown style.

### Proposed solution
I think making either a new component or an addition to the v-list component that is similar to your website for scrolling navigation would be great and i think others might agree. 
![Vuetify table of contents](https://puu.sh/I4Byi/6e76d517df.gif)

**Comment by lioneaglesolutions** [comment]
### 

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
