### ISSUE TITLE
[Bug Report][2.5.8] example page error https://vuetifyjs.com/en/examples/wireframes/discord/

### ISSUE THREAD

**Issue by mtrucc** [vuetifyjs/vuetify#14060]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.13
**Browsers:** Chrome 92.0.4515.107
**OS:** Mac OS 10.15.7

### Steps to reproduce
open https://vuetifyjs.com/en/examples/wireframes/discord/

### Expected Behavior
can open

### Actual Behavior
can open

### Reproduction Link
<a href="https://codepen.io/mtrucc/pen/bGWJmrB" target="_blank">https://codepen.io/mtrucc/pen/bGWJmrB</a>

**Comment by KaelWD** [comment]
Duplicate of #12854
