### ISSUE TITLE
[Bug Report][2.4.11] Color does not respect parent theme

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#14062]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.14
**Browsers:** Firefox 91.0
**OS:** elementary OS 5.1.7 Hera (based on Ubuntu 18.04.4 LTS)

### Steps to reproduce
- Create a Button with a color set to "secondary"
- Put it in a parent that sets the dark theme

### Expected Behavior
I'd expect the button color to be the dark theme's secondary color. 

### Actual Behavior
It uses the light theme's secondary color

### Reproduction Link
<a href="https://codepen.io/peteruithoven/pen/QWvRYRg?editors=1010" target="_blank">https://codepen.io/peteruithoven/pen/QWvRYRg?editors=1010</a>

### Other comments
When I switch around the root theme to dark it does use the dark theme's secondary color.
Even when I set the button itself to use the dark theme it uses the root theme. 
Also applies to a List element.

**Comment by KaelWD** [comment]
This is fixed in vuetify 3, it wasn't possible without breaking older browsers.
