### ISSUE TITLE
[Bug Report][2.5.8] v-img calculating padding-bottom wrong in firefox

### ISSUE THREAD

**Issue by Nils-Kolvenbach** [vuetifyjs/vuetify#14079]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Visit the Code Pen link with Chrome and Firefox
2. Compare both and see that the Firefox one does behave differently
3. Inspect the .v-responsive__sizer element and notice that the style attribute says 100% padding-bottom in Firefox, while being 68.4932% in Chrome 

### Expected Behavior
The default image element should render the same in both browsers.

### Actual Behavior
It's different in Firefox.

### Reproduction Link
<a href="https://codepen.io/Enk4y/pen/PojozNv" target="_blank">https://codepen.io/Enk4y/pen/PojozNv</a>

**Comment by KaelWD** [comment]
See #10386
