### ISSUE TITLE
[Bug Report][2.4.0] v-card Frosted glass

### ISSUE THREAD

**Issue by Longgererer** [vuetifyjs/vuetify#14075]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.159
**OS:** Windows

### Steps to reproduce
Click the “Menu as Popover” button

### Expected Behavior
The popover's background apply this style "backdrop-filter: blur(5px)"

### Actual Behavior
The background is not blur, after a short time,the popover's background apply this style.

### Reproduction Link
<a href="https://codepen.io/longgererer/pen/QWgLErv" target="_blank">https://codepen.io/longgererer/pen/QWgLErv</a>

**Comment by KaelWD** [comment]
Looks like chrome doesn't apply backdrop-filter during transitions, this isn't anything to do with vuetify.
