### ISSUE TITLE
V-Slider 'jumps' when moved and label is clipped when min attribute present

### ISSUE THREAD

**Issue by ashireman** [vuetifyjs/vuetify#1407]
### Steps to reproduce
View the CodePen provided and move both sliders.

### Versions
I believe the latest versions of both are used.

### What is expected ?
Both sliders should move in a smooth manner.

### What is actually happening ?
The top slider will 'jump' when moved slightly while the bottom will remain smooth. The only difference between the two is the presence of the 'min' attribute. The styling between the two also differs and the labels appear to be clipped.

### Reproduction Link
https://codepen.io/anon/pen/ZJrJxE

Updated with correct CodePen link

**Comment by jacekkarczmarczyk** [comment]
PR with fix is only for jumping slider, not for clipped label
