### ISSUE TITLE
[Feature Request] How to dynamically active in treeview

### ISSUE THREAD

**Issue by newcrystal52** [vuetifyjs/vuetify#14078]
### Problem to solve

I wish there was a way to activate the added node when adding one to the leaf node in the treeview.

### Proposed solution
I would like to be able to dynamically activate what I want.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
