### ISSUE TITLE
[Bug Report][3.0.0-alpha.10] v-row justify doesn't generate css in production build

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify#14087]
### Environment
**Vuetify Version:** 3.0.0-alpha.10
**Vue Version:** 3.2.6
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
1. use tailwind and vuetify in the same project.
2. tailwind's purge css will not detect justify-center being used anywhere in the code because v-row expects it to be passed through a prop.
3. purge css is disabled in dev mode so justify-center will be present, but it will be removed from production build.

### Expected Behavior
dev and production builds work the same

### Actual Behavior
dev and production build differs

### Reproduction Link
<a href="http://cant.reproduce.in.codepen" target="_blank">http://cant.reproduce.in.codepen</a>

### Other comments
I bet a similar issue exists for all of the tailwind decorators injected to view templates only through props.

workaround: use justify-content class on v-row rather than justify="center" prop

**Comment by KaelWD** [comment]
PurgeCss will probably remove a lot of classes that are dynamically added, not just the grid system. Use [windicss](https://windicss.org/) or set a whitelist for PurgeCss. 

https://github.com/vuetifyjs/vuetify/issues?q=is%3Aissue+purgecss+is%3Aclosed
