### ISSUE TITLE
DatePicker component duplicating/skipping months after year-click

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#1409]
### Steps to reproduce
1. Visit https://vuetifyjs.com/components/pickers
2. Click an old-ish year (eg, <=2005) at the top of either **Example #1** component.
3. Scroll via left/right arrow buttons to either **a.)** March/April or **b.)** October/November

### Versions
Windows 10
Chrome 60.0.3112.90
Vuetify .14

### What is expected ?
To see the April and November months.

### What is actually happening ?
March and October are shown "again", in place of April and November (respectively). Note that the days on the second "iteration" of the month are correct, header/month is just off.

### Reproduction Link
https://vuetifyjs.com/components/pickers

![actual-october](https://user-images.githubusercontent.com/13950848/29467405-6cdf4eda-840e-11e7-8510-e169fe208480.PNG)
![should-be-november](https://user-images.githubusercontent.com/13950848/29467406-6ce45466-840e-11e7-89d8-32984837e521.PNG)

**Comment by dwyer14** [comment]
Also worth noting: when you click a date in the incorrectly-labeled October (what should be November), the side-panel (ie, blue box) has the correct date. eg, I click "October" 16, and the left text shows:

2005
Wed,
Nov 16

**Comment by johnleider** [comment]
This is due to the javascript Date object. You can test this yourself by creating a new Date object, ```let k = new Date('November 1 2005')```. After you generate it, use ```k.getMonth()```. It will return 10 when in fact it is actually 11. @nekosaur We might have to change back how we handle months.

**Comment by dwyer14** [comment]
Isn't that a result of getMonth() being zero-based? For me, the issue here only happens on those two specific "month-pairs"...March/April & October/November. If the issue was an off-by-one error, I'd think it would be consistently wrong. Am I turned around on that?

**Comment by johnleider** [comment]
You're right, I was looking at something else. Gotta stop drinking.

**Comment by dwyer14** [comment]
HA! Been there before. 🍻
