### ISSUE TITLE
[Bug Report][2.5.8] v-combobox inconsistent blur behavior with virtual keyboard

### ISSUE THREAD

**Issue by stuomas** [vuetifyjs/vuetify#14091]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.159
**OS:** Windows, Windows 10, Linux

### Steps to reproduce
1. Click once v-combobox input field and press simple-keyboard button. Combobox gives blur event and creates a one-character chip
2. Click twice v-combobox input field and press simple-keyboard button. Combobox does not blur and works as expected, allowing to type as much as you want.

### Expected Behavior
Focusing v-combobox by clicking once should allow typing more than one character on a virtual keyboard.

### Actual Behavior
V-combobox needs to be focused and then given another extra click to allow typing more than one letter on a virtual keyboard.

### Reproduction Link
<a href="https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-forked-qsng4" target="_blank">https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-forked-qsng4</a>

### Other comments
Simple-keyboard author believes this is an issue with v-combobox and its inconsistent blur behavior.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
