### ISSUE TITLE
support :to router on v-btn and v-toolbar-item

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#141]
Hi,

I would like to use `:to` with an object like used for vue routing. But currently the `:href`does not support objects even if set to `:router="true"`
```
                    <v-toolbar-item :href="{name:'types-clients-id-base', params:{id:model.id}}" router>

```

I think it would be nice to have the `:to` binding for v-btn and items, what do you think?

**Comment by johnleider** [comment]
I agree, this makes sense and should apply to all components that implement router-link.

**Comment by dohomi** [comment]
Maybe append also `nuxt-link`as well.. `NUXT` will add some nice pre-fetching features and I think it would be great to support it in-built.
https://nuxtjs.org/api/components-nuxt-link
