### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Dialog throws errors when clicking on it - Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify#14101]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.6
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
1. open a v-dialog
2. click anywhere

### Expected Behavior
no errors

### Actual Behavior
![image](https://user-images.githubusercontent.com/46789227/131513766-6612abd6-3e4f-4908-ae30-c7e8f438f2a2.png)
```
index.ts:42 Uncaught TypeError: Cannot read property 'contains' of undefined
    at index.ts:42
    at Array.some (<anonymous>)
    at checkEvent (index.ts:42)
    at directive (index.ts:54)
    at HTMLBodyElement.onClick (index.ts:76)
```

### Reproduction Link
<a href="https://codepen.io/pen/?&prefill_data_id=38d07978-3bed-476a-91be-4b6691a92fb6" target="_blank">https://codepen.io/pen/?&prefill_data_id=38d07978-3bed-476a-91be-4b6691a92fb6</a>

**Comment by DRoet** [comment]
I'm pretty sure the VDialog docs haven't been updated yet for V3 thats why the examples are not working

**Comment by lukeromanowicz** [comment]
@DRoet I'm not so sure, as simple usage as:
```

**Comment by KaelWD** [comment]
This only happens if you use it without an activator.

**Comment by lukeromanowicz** [comment]
@KaelWD can you, please, back us up with a workaround snippet? When using activator slot, I am getting:
![image](https://user-images.githubusercontent.com/46789227/132209318-34ffc331-570e-498f-afc3-d410c905fad3.png)

```
            <v-dialog v-model="showDialog">
              <template #activator="{ on, attrs }">
                <v-btn color="primary" v-bind="attrs" v-on="on"
                  >From the bottom</v-btn
                >
              </template>
              CONTENT GOES HERE
            </v-dialog>
            ```

**Comment by KaelWD** [comment]
`#activator="{ props }"` + `v-bind="props"`

**Comment by lukeromanowicz** [comment]
Nice! this one works like a charm!
