### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Module 'vuetify' declares 'ThemeDefinition' locally, but it is not exported. ts(2459)

### ISSUE THREAD

**Issue by BreizhReloaded** [vuetifyjs/vuetify#14107]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.6
**Browsers:** Firefox 91.0
**OS:** Windows 10

### Steps to reproduce
1. Create a Vue 3 + Vuetify 3 project
2. Import ThemeDefinition interface to create your own theme as explained [here](https://next.vuetifyjs.com/en/features/theme/)

### Expected Behavior
ThemeDefinition is imported and theme pushed to Vuetify

### Actual Behavior
Typescript triggers error 2459 and project can't build

### Reproduction Link
<a href="https://codesandbox.io/s/brave-moon-et79m?file=/src/main.ts" target="_blank">https://codesandbox.io/s/brave-moon-et79m?file=/src/main.ts</a>

**Comment by glen-84** [comment]
Import it from `vuetify/composables`.

The docs have not been updated yet.

/cc @KaelWD.

**Comment by KaelWD** [comment]
I'm wondering if the composables should just be available on `'vuetify'` instead. 

Or at least types used in `createVuetify`

**Comment by BreizhReloaded** [comment]
That indeed solved the problem, thank you @glen-84!

I don't have any preference about where that should be available from, but that would be nice to have access to `ThemeDefinitionColors` too, as part of types used in `createVuetify`. For example, I'm building my colour set programmatically, and Typescript complains about missing keys if I don't use this type.

That said, it may be a more global discussion.

**Comment by KaelWD** [comment]
> Typescript complains about missing keys

That's a separate issue, the types in `createVuetify` are too restrictive.

**Comment by BreizhReloaded** [comment]
Ok. Should I then open a new issue, to talk about available types when importing Vuetify?

**Comment by glen-84** [comment]
> I'm wondering if the composables should just be available on `'vuetify'` instead.
> 
> Or at least types used in `createVuetify`

I'm not sure if there's a right or wrong answer here. In [this answer](https://stackoverflow.com/a/63421113/221528) on StackOverflow, there is mention of the benefit of hiding the internal structure of the project behind a single export, but it also means that there can be naming conflicts in some cases (f.e. icon sets), so perhaps some level of separation makes sense.

I do think that it's a little unexpected to find something like `ThemeDefinition` under `/composables`, even though, technically, that's where it comes from. Importing `use*` functions from there would still make sense though.

Perhaps all types/interfaces should be exported from `vuetify`, and actual functions etc. from their respective "directories"?

**Comment by frederikheld** [comment]
I'm confused about the state of this.

Reading the thread, I would expect to be able import the type `ThemeOptions` like this:

```js
import type { ThemeOptions } from 'vuetify'
```

But I still get the error stated in the issue title. Importing it from `vuetify/composables` doesn't work at all as the package doesn't seem to exist.

I'm using vuetify 3.4.8 .
