### ISSUE TITLE
[Feature Request] Selectable adajcent-months in v-date-picker

### ISSUE THREAD

**Issue by octlap** [vuetifyjs/vuetify#14100]
### Problem to solve
If I'm a user picking a date off of the v-date-picker and I want to select a visible date from either of the months adjacent to the one currently visible, I have to click to that month before I can select the date, thereby adding a redundant click to the process. 

### Proposed solution
It would be great to have a prop, something like adajcent-months-selectable, that would allow the user to click and select days of the adjacent month directly on the current month, without having to navigate. Thanks! 😊

**Comment by z0lo13** [comment]
Please consider bringing this prop
