### ISSUE TITLE
[Feature Request] adjustable color for text on primary, etc. in the theme configuration or automatic generation

### ISSUE THREAD

**Issue by llMaxll** [vuetifyjs/vuetify#14109]
### Problem to solve
Text on primary, secondary, ... always is white. This is easily testable with a button. With a dark theme this limits the options for those colors greatly, since the color needs acceptable contrast with the dark background and good contrast with the white text on it (for accessibility). A good color for that has never enough contrast to the dark background to be a text color too. Using lighter and darker versions or manually setting a [color]--text class kind of solves it, but is a lot of work. I'd expect easier customization, since color-on is such a common concept.

### Proposed solution
It should be possible to define a color for things on primary, etc. directly in the theme configuration. I could imagine something like:
<code>vuetify.theme.themes.dark:{
&emsp;primary: {
&emsp;&emsp;base: '#FFFF00',
&emsp;&emsp;on: '#333333',
&emsp;}
}</code>

Alternatively or together with that, the 'on' color (could also e named 'text') could be automatically generated (doesn't WCAG define a calculation for that?) to have enough contrast to the chosen color.

**Comment by KaelWD** [comment]
This is exactly how it works in v3
