### ISSUE TITLE
[Feature Request] Expose theme (light/dark) text color as css class

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#14113]
### Problem to solve

Sometimes I need to access/use the text color based on if it's currently light or dark theme.

The **dark** theme color is just `white`/`#ffffff` and therefore can be used with `white--text`
But the **light** text color is mostly (as far as I know) `rgba(0, 0, 0, .87)` :thinking: and I cannot access it that easy. It's not just `black--text` because that would be `#000000`

### Proposed solution

Expose a css class for the text color based on the selected theme (light/dark).

So it can be used like 

```pug
span.theme--text My color is based on the selected theme
```

I'm not sure if the css name is perfectly named. Please propose other names if you have better ideas.

Please add documentation if we can already access this color based on theme. Didn't found it in the current docs.

_I'm willing to implement this, if the proposal gets accepted. But I would need help, due to I'm not that used to SCSS / how it is managed in Vuetify_

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/d8679b9e99a164059991b53e5defa6e6acddf7e1/packages/vuetify/src/components/VApp/VApp.sass#L8-L16

https://vuetifyjs.com/en/styles/text-and-typography/#opacity

**Comment by Shinigami92** [comment]
Ohh.... cool thx :heart:
