### ISSUE TITLE
[Documentation] Refresh error on v-treeview api page

### ISSUE THREAD

**Issue by anzuj** [vuetifyjs/vuetify#14115]
### Environment

**Browsers:** Chrome 92.0.4515.159
**OS:** Windows 10

### Steps to reproduce
1. Open v-treeview api page https://vuetifyjs.com/en/api/v-treeview/
2. Observe the bottom right corner notification "New content is available. Click Refresh to update"
3. Click "Refresh" 

### Expected Behavior
Page reloads and refreshes content

### Actual Behavior
No changes on page, error in console. 
```javascript
vue.runtime.common.prod.js:6 TypeError: Cannot read property 'waiting' of null
    at pwa.js:44
    at V (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at H (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at M.<anonymous> (asyncToGenerator.js:21)
    at M.t (pwa.js:41)
```

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-treeview/" target="_blank">https://vuetifyjs.com/en/api/v-treeview/</a>

**Comment by MajesticPotatoe** [comment]
Likely outdated content in service worker. The refresh dialog has been disabled for some time now, so unable to reproduce. Would suggest clearing your site cache.

**Comment by KaelWD** [comment]
> The refresh dialog has been disabled for some time now

It hasn't, there's just an option to ignore it.
