### ISSUE TITLE
[Feature Request] v-btn text-color attribute

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#14112]
### Problem to solve

When we have a button that has e.g. outlined but we want to override the text color we need to use the slot and add the class for each element individually.
I would like to set a `text-color` on `v-btn` explicitly like for [other](https://vuetifyjs.com/en/api/v-chip/#props-text-color) components.

### Proposed solution

```pug
v-btn(color="secondary", depressed, outlined, text-color="black")
  v-icon(left) mdi-plus
  span Add
```

### Current Workaround

```pug
v-btn(color="secondary", depressed, outlined)
  v-icon.black--text(left) mdi-plus
  span.black--text Add
```

### Alternative solution

Add a `content-class` property to override/add multiple css classes. (e.g. [v-dialog content-class](https://vuetifyjs.com/en/api/v-dialog/#props-content-class))

_If this proposal gets accepted, I'm willing to implement it_ 🙂

**Comment by KaelWD** [comment]
Outlined buttons use `currentColor` for the border, so there can't be separate border and text colors.

**Comment by Shinigami92** [comment]
> Outlined buttons use `currentColor` for the border, so there can't be separate border and text colors.

Ah I see...

So my workaround is the way to go for now?
Can't we forward the class to the slot/text only?

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
