### ISSUE TITLE
[Bug Report][2.3.14] v-virtual-scroll doesn't work in stateless components

### ISSUE THREAD

**Issue by balsanka** [vuetifyjs/vuetify#14128]
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.159
**OS:** Windows

### Steps to reproduce
Just add v-virtual-scroll  to any stateless VueJS component.

### Expected Behavior
Render template with data

### Actual Behavior
[Vue warn]: Unknown custom element: <v-virtual-scroll> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### Reproduction Link
<a href="https://codesandbox.io/s/sleepy-https-t2s89?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/sleepy-https-t2s89?file=/src/components/HelloWorld.vue</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/treeshaking/#functional-components
