### ISSUE TITLE
[Documentation] Search doesn't work correctly

### ISSUE THREAD

**Issue by Black-S** [vuetifyjs/vuetify#14133]
### Environment

**Browsers:** Chrome 92.0.4515.159
**OS:** Windows 10

### Steps to reproduce
1. Go to any page.
2. Try to find something using search field. 
3. Choose anything from dropdown.

### Expected Behavior
Close dropdown, show result page.

### Actual Behavior
1. Url changed, but page is't changed.
2. Dropdown list is showing. Couldn't close dropdown list. 
3. Other links from header/sidebar also doesn't work. Changed only url. Anything doesn't work on click.
4. Only refreshing helps to see search result.

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-calendar-weekly/" target="_blank">https://vuetifyjs.com/en/api/v-calendar-weekly/</a>

**Comment by KaelWD** [comment]
Fixed by a6e33fe8
