### ISSUE TITLE
[Bug Report][2.5.6] No image actions in right-click menu of <v-img>

### ISSUE THREAD

**Issue by KomaGR** [vuetifyjs/vuetify#14138]
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 93.0.4577.63
**OS:** Linux x86_64

### Steps to reproduce
1. Use \<v-img\> with a `src` image.
2. Right-click on the image.
3. Observe action options.

### Expected Behavior
Action options should include (in Chrome):
- "Open image in new tab", 
- "Save image as...", 
- "Copy image", 
- "Copy image address", and 
- "Search Google for image". 

Also, the user should be able to drag-and-drop the image.

### Actual Behavior
Right-click menu includes other HTML-related actions but no action for images. The image cannot be selected.

### Reproduction Link
<a href="https://codepen.io/komagr/pen/OJgWJGN" target="_blank">https://codepen.io/komagr/pen/OJgWJGN</a>

### Other comments
In essence, \<v-img\> *is not an image element*, as others have noticed (#5109).

**Comment by KaelWD** [comment]
Fixed by 93886130d1b2e2b393b15bfd4e004721bc281f86

**Comment by KomaGR** [comment]
Is this released?
