### ISSUE TITLE
[Documentation] next.vuetifyjs.com is down

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify#14130]
### Environment

**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
enter the page

### Expected Behavior
it works

### Actual Behavior
404: NOT_FOUND
Code: NOT_FOUND
ID: arn1::rf5hk-1630932899562-f1dd8c9d9cbb

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/tooltips/" target="_blank">https://next.vuetifyjs.com/en/components/tooltips/</a>

**Comment by lukeromanowicz** [comment]
![image](https://user-images.githubusercontent.com/46789227/132220952-a1179edb-ae61-424d-904b-3f82e137e7d3.png)

**Comment by KaelWD** [comment]
It's back.
