### ISSUE TITLE
[Bug Report][2.5.8] VNavigationDrawer hides on horizontal scrolling

### ISSUE THREAD

**Issue by Tinoooo** [vuetifyjs/vuetify#14134]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.63
**OS:** Windows 10

### Steps to reproduce
1. open the <a href="https://codepen.io/tinooooo/full/qBjqQqy" target="_blank">live view of the codepen</a>
1. switch to mobile view in dev tools
1. swipe left on v-main (e.g. the text)

### Expected Behavior
The navigation drawer should persist.

### Actual Behavior
The navigation drawer disappears.

### Reproduction Link
<a href="https://codepen.io/tinooooo/pen/qBjqQqy" target="_blank">https://codepen.io/tinooooo/pen/qBjqQqy</a>

![nav-drawer-issue6](https://user-images.githubusercontent.com/17991193/132326992-ebe35e98-c005-4f25-911f-b1de5d77a057.gif)

**Comment by lun413** [comment]
Just add `@touchend.stop` on scrollable div

**Comment by Tinoooo** [comment]
Thank you @lun413 !
@KaelWD pointed out in Discord, that using the prop `touchless` stops the mentioned behavior. Since this is great for my use case, I go with that solution 🥳.

The area that listenes for the touch event might be a bit large though. I'll close this issue anyways.
