### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] `v-overlay` content is not centred

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14149]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.11
**Browsers:** Chrome 93.0.4577.63
**OS:** Windows 10

### Steps to reproduce
1. See repro link.
2. Uncomment `padding-inline-end: 0;` to centre the spinner.

### Expected Behavior
The spinner is centred.

### Actual Behavior
It's pushed to the left because of the padding on the RHS.

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/gORmEdy" target="_blank">https://codepen.io/glen-84/pen/gORmEdy</a>

### Other comments
> I guess that could be added only if the offsetParent is a scroll container
> (Kael)

**Comment by KaelWD** [comment]
Not sure what I meant by that lol, the padding is added to prevent the layout jump when the scrollbar appears.

**Comment by glen-84** [comment]
The scrollbar is hidden when the overlay is visible, so there's no reason to compensate for its width.

I think you were suggesting that the padding could be added only when the container has a scrollbar.

**Comment by KaelWD** [comment]
Yeah that doesn't really apply here because it *does* have a scrollbar. The reason for the padding is so it doesn't shift when the scrollbar reappears:

https://user-images.githubusercontent.com/16421948/135759827-8c518c62-a83e-455e-b866-adb43b3c4044.mp4

**Comment by glen-84** [comment]
Would it be possible to delay the removal of the `v-overlay-scroll-blocked` class until after the overlay has closed (become fully hidden)?
