### ISSUE TITLE
[Bug Report][2.5.8] Touch event doesn't work while scrolling on bottom navigation

### ISSUE THREAD

**Issue by riyaz7us** [vuetifyjs/vuetify#14150]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.12
**Browsers:** Chrome 95.0.4636.4
**OS:** Windows 10, Android

### Steps to reproduce
Scroll up or down, and while scrolling (before scrolling stops), try tapping/clicking any of the tabs from bottom navigation.

### Expected Behavior
The screen must navigate to the desired location.

### Actual Behavior
The touch event creates a ripple effect, but doesn't navigate until the scrolling completely stops

### Reproduction Link
<a href="https://codepen.io/sdriyaz712/pen/ZEyKmJb" target="_blank">https://codepen.io/sdriyaz712/pen/ZEyKmJb</a>

### Other comments
When the user scrolls with a twitch, the screen moves with momentum, due to which the scroll event takes a second or two to end (until the momentum completely pauses). This makes taps/clicks unresponsive during scroll (although ripple effect takes place), putting the impression of lag in the app.

**Comment by KaelWD** [comment]
This is native browser behaviour.

**Comment by riyaz7us** [comment]
Hi kael, thanks for your response. Is there any way to overcome this behavior? I need to transform the app into PWA/Hybrid which would be accessible on mobile devices via webview. Even a small suggestion would be appreciated.

**Comment by riyaz7us** [comment]
Thanks Kael, 

> Not sure, you could try scrolling just the content area instead of the entire body.

Although this didn't work but I tried with the webview in android and got the desired outcome.
