### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Text button contains background

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify#14159]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.11
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
```
<v-btn text>Button</v-btn>
```

### Expected Behavior
contains no background

### Actual Behavior
looks like basic button

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=13661234-6ede-403f-85bf-9032f980d6ff

**Comment by KaelWD** [comment]
`variant="text"`
