### ISSUE TITLE
[Bug Report][2.5.8] d-flex with disabled v-text-field can't select value from fields beyond the first

### ISSUE THREAD

**Issue by TMcKinley** [vuetifyjs/vuetify#14165]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.63
**OS:** Windows 10

### Steps to reproduce
When using a div with d-flex that contains disabled fields, you can only select the value of the first field using the mouse + left click but any fields beyond the first do NOT let you select the value of the field. In this example, I can select the text 'Test1' but I cannot select the text 'Test2' or 'Test3'.

### Expected Behavior
Consistent behavior. It looks like the Vuetify example also allows text selection in the examples for disabled fields, so I'm assuming this is supposed to be allowed.

### Actual Behavior
First field you can select the value of a disabled field. Any field beyond the first you can NOT select the value.

### Reproduction Link
<a href="https://codepen.io/tmckinley/pen/MWoOmOm?editors=101" target="_blank">https://codepen.io/tmckinley/pen/MWoOmOm?editors=101</a>

**Comment by KaelWD** [comment]
This is the same behaviour as with `<input>` elements: https://codepen.io/kaelwd/pen/WNOXqjE
