### ISSUE TITLE
[Bug Report][2.3.23] v-radio doesn't support `tabindex`

### ISSUE THREAD

**Issue by nebojsa91markovic** [vuetifyjs/vuetify#14169]
### Environment
**Vuetify Version:** 2.3.23
**Vue Version:** 2.6.12
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
By pressing tab, tabindex doesn't respond

### Expected Behavior
Should focus on radio button

### Actual Behavior
Do nothing

### Reproduction Link
<a href="https://codepen.io/nebojsa91markovic/pen/vYZpxOy" target="_blank">https://codepen.io/nebojsa91markovic/pen/vYZpxOy</a>

**Comment by KaelWD** [comment]
`:ripple="false"` removes the focus indicator, it still has focus though. v-radio should only be used in v-radio-group which is why you can't interact with it.
