### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] `v-btn` transform causes overflow

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14166]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.11
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
Click or focus the button.

### Expected Behavior
No overflow.

### Actual Behavior
Overflow caused by the `transform: scale(1.25);` on `::after`.

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/KKqqxyg" target="_blank">https://codepen.io/glen-84/pen/KKqqxyg</a>

### Other comments
I can send a PR if the solution is to simply remove it.

**Comment by johnleider** [comment]
What is the use-case for the overflow?

**Comment by glen-84** [comment]
Do you mean for _no_ overflow? (I don't want it to overflow)

This doesn't seem to repro in Firefox for some reason, but it's visible in Chrome:

![image](https://user-images.githubusercontent.com/261509/144110299-551b0fae-941e-4de0-9b80-d1f47c9d92d4.png)

My example wasn't ideal, perhaps this is more clear: https://codepen.io/glen-84/pen/Exwaayw.

![image](https://user-images.githubusercontent.com/261509/144112002-c2df3b76-a494-43c1-9da3-d5be995d0179.png)

Elements (v-btn in this case) shouldn't overflow, as it'll cause parent elements to show scrollbars.

**Comment by johnleider** [comment]
There seems to be some browser issue going on with regards to focus-within. You can see the overflow go away once you tab to the `v-btn` just once.

@KaelWD any insight?
