### ISSUE TITLE
[Bug Report][3.0.0-alpha.0] Vuetify 3 'Unknown node type in node creation' bug

### ISSUE THREAD

**Issue by kamster94** [vuetifyjs/vuetify#14179]
### Environment
**Vuetify Version:** 3.0.0-alpha.0
**Vue Version:** 3.2.12
**Browsers:** Edge 93.0.961.52
**OS:** Windows 10

### Steps to reproduce
npm run serve

### Expected Behavior
App loads with vuetify components rendered

### Actual Behavior
Error pops up

### Reproduction Link
<a href="https://github.com/kamster94/FrankPress/tree/SetupInitialVueLayout/vue" target="_blank">https://github.com/kamster94/FrankPress/tree/SetupInitialVueLayout/vue</a>

### Other comments
It's just Vue 3 + Vuetify 3 alpha. There are a lot of errors like:
./node_modules/vuetify/lib/components/VBtn/VBtn.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/vuetify/lib/components/VBtn/VBtn.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Unknown node type in node creation

**Comment by KaelWD** [comment]
https://github.com/postcss/autoprefixer/issues/1391
