### ISSUE TITLE
[Bug Report][2.5.8] Icon not align center in component v-timeline item

### ISSUE THREAD

**Issue by arslan-butt** [vuetifyjs/vuetify#14170]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.13
**Browsers:** Chrome 93.0.4577.82, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.15.7, Mac OSX

### Steps to reproduce
Using v-timeline when adding an icon for timeline items: eg: mdi-circle, its not well align center
```javascript
<v-timeline-item
        color="amber lighten-1"
        fill-dot
        left
        small
        icon="mdi-circle"
      > 
```

### Expected Behavior
align-center

### Actual Behavior
Not aligned center 

### Reproduction Link
<a href="https://codepen.io/Butt/pen/BaZYooN?editors=1010" target="_blank">https://codepen.io/Butt/pen/BaZYooN?editors=1010</a>
![C785077B-D856-47E1-9A96-6F64ED80C6A3_4_5005_c](https://user-images.githubusercontent.com/24808064/133770214-2d59355f-5577-4cdc-ac3c-f8311f244663.jpeg)

**Comment by KaelWD** [comment]
Workaround: `-webkit-font-smoothing: none`

**Comment by arslan-butt** [comment]
@KaelWD not worked
