### ISSUE TITLE
[Bug Report][2.5.8] Divider disappears on v-timeline when scroll

### ISSUE THREAD

**Issue by glacierPEgli** [vuetifyjs/vuetify#14189]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
Make a v-timeline with overflow-y set to auto.

### Expected Behavior
Divider on every item

### Actual Behavior
Divider is missing on any items that are overflowing

### Reproduction Link
<a href="https://codepen.io/dhanish-mehta/pen/zYNoPej?editors=101" target="_blank">https://codepen.io/dhanish-mehta/pen/zYNoPej?editors=101</a>

**Comment by KaelWD** [comment]
Put it inside another element, the divider is 100% height: https://codepen.io/kaelwd/pen/abwamqE?editors=1010

**Comment by glacierPEgli** [comment]
Thank you that worked!
