### ISSUE TITLE
[Bug Report][2.5.8] Color prop is not working for v-list-item

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#14186]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
1. Create some `v-list-item`s with `to` prop.
2. Set the `color` in `v-list-item`.
3. The `color` prop is not working. `v-list-item` color is not changed when it is in `active` state.

According to the docs it should change the color, when it is in the active state:
https://vuetifyjs.com/en/api/v-list-item/#props-color

### Expected Behavior
Color should change to the selected one when `v-list-item` is in the active state.

### Actual Behavior
Color is not changed from the default one when `v-list-item` is in the active state.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/MWoBjLr" target="_blank">https://codepen.io/mikilll94/pen/MWoBjLr</a>

**Comment by yuwu9145** [comment]
@Mikilll94 

As [doc url](https://vuetifyjs.com/en/api/v-list-item/#props) indicates:

Colour will be applied when the item is in an **active** state or input-value is true.

`v-list` does not maintain **active** state but `v-list-item-group` does, so you can just simply wrap `v-list-item` with  `v-list-item-group`.

Reproduction link has been refactored to have a solution: 

https://codepen.io/yuchaosydney/pen/NWgOZOz

**Comment by Mikilll94** [comment]
@yuwu9145 
Hello,
Thanks for your response. Unfortunately your solution has a bug. You can see it on this GIF:
![v-list-item-group_bug](https://user-images.githubusercontent.com/17653648/134805824-0229ea29-3724-414f-86fe-63d15f379eee.gif)

When I have selected "Page 2" and I refreshed the page, the "Page 2" item is not highlighted correctly. This bug can only be reproduced locally. You cannot reproduce it on the CodePen because CodePen does not allow you to refresh the browser on a certain URL.

**Comment by yuwu9145** [comment]
Thanks for reply. I will dig further

**Comment by KaelWD** [comment]
Broken by #13719

@yuwu9145 You shouldn't use v-list-item-group with links.

**Comment by yuwu9145** [comment]
> Broken by #13719
> 
> 
> 
> @yuwu9145 You shouldn't use v-list-item-group with links.

It shouldn't be broken by that pr because issue is caused by this.isActive is always false by running reproduction sample code

**Comment by KaelWD** [comment]
Router-link active doesn't set `isActive`, the color class was always applied then overridden by `:not(.v-list-item--active)`

**Comment by yuwu9145** [comment]
I might be on wrong direction, will check out more thoroughly tomorrow based on your hints
