### ISSUE TITLE
[Bug Report][2.3.23] v-progress-linear does not appear when printing the website

### ISSUE THREAD

**Issue by sergitopo** [vuetifyjs/vuetify#14192]
### Environment
**Vuetify Version:** 2.3.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
Go to the https://vuetifyjs.com/en/components/progress-linear/
Just press Ctrl + P in Windows or print the website and look at the missing progress-linear bars of the page.

### Expected Behavior
The bars to appear in the printed document

### Actual Behavior
Then bars are missing in the printed document

### Reproduction Link
<a href="https://codesandbox.io/s/amazing-mestorf-b1ftg?file=/src/App.vue" target="_blank">https://codesandbox.io/s/amazing-mestorf-b1ftg?file=/src/App.vue</a>

### Other comments
Go to the https://vuetifyjs.com/en/components/progress-linear/#colors page and try to print it. Not printed in Chrome, Firefox or Edge

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/134668155-1621ea2f-a042-4b44-8381-218c1ab7120f.png)
