### ISSUE TITLE
[Bug Report][2.5.8] Combobox list-index doesn't update correctly on input

### ISSUE THREAD

**Issue by lgarczyn** [vuetifyjs/vuetify#14194]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Firefox 92.0
**OS:** Linux

### Steps to reproduce
Using the provided sandbox

Example 1

* Focus the combobox
* Press 'a'
* Using arrows, move to the last entry
* Press 'a' again
* The list index now points outside of the search results

Example 2

* Focus the combobox
* Press 'a'
* Using arrows, select the second to last entry
* Press 'a'
* The list index now points to another entry, because it did not change

Example 3

* Focus the combobox
* Press 'a'
* Using arrows, select the first entry
* Press 'a' until all entries disappear
* The list index is still '0', even though no entries are selected
* Press 'a' again
* The list index is now updated correctly

### Expected Behavior
The selection should not change on search input, therefore the list index should be updated on search input

The list index should never point to a result that does not exist

### Actual Behavior
The list index keeps its value, sometimes even pointing to a absent search result

### Reproduction Link
<a href="https://codepen.io/lgarczyn/pen/eYRPmJJ?editors=1111" target="_blank">https://codepen.io/lgarczyn/pen/eYRPmJJ?editors=1111</a>

### Other comments
This might be linked to another bug I've experienced, where pressing enter does not actually add a new chip. This might be because the combobox believe a search result is still selected. The new chip is created on blur though, which is kinda weird.

**Comment by yuwu9145** [comment]
@johnleider This selection in dropdown menu should have the same behaviour of `Autocomplete` [sample link](https://vuetifyjs.com/en/components/autocompletes/), it resets the selection when the list is updated in `Autocomplete`?
