### ISSUE TITLE
[Bug Report][2.4.4] The prependicon of v-list-group can't be clicked alone. Don't drop it down?

### ISSUE THREAD

**Issue by daniel-lij** [vuetifyjs/vuetify#14197]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
no

### Expected Behavior
The group icon needs to be clicked, and there is no drop-down

### Actual Behavior
Click the group icon and the children drop-down list appears

### Reproduction Link
<a href="https://codepen.io/daniel-lij/pen/jOwQOMZ" target="_blank">https://codepen.io/daniel-lij/pen/jOwQOMZ</a>

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/events.html#Event-Modifiers
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

**Comment by daniel-lij** [comment]
> https://vuejs.org/v2/guide/events.html#Event-Modifiers
> https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

Clicking anywhere will drop down the list, @ submit. Prevent can't solve this problem

**Comment by daniel-lij** [comment]
> https://vuejs.org/v2/guide/events.html#Event-Modifiers
> https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation


Clicking anywhere will drop down the list, @ submit. stop can't solve this problem
