### ISSUE TITLE
[Bug Report][2.5.8] small flickering black box when disabling / enabling a v-card with an click handler in an timeline item

### ISSUE THREAD

**Issue by illmat** [vuetifyjs/vuetify#14193]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.82
**OS:** Linux x86_64

### Steps to reproduce
1. open codepen
2. click the "toggle disable" button a few times 
3. see the flickering box on in front of the first card

### Expected Behavior
no flickering

### Actual Behavior
flickering

### Reproduction Link
<a href="https://codepen.io/illmat/pen/xxraNye?editors=1010" target="_blank">https://codepen.io/illmat/pen/xxraNye?editors=1010</a>

**Comment by glen-84** [comment]
The `v-card` seems to get a `v-card--link` class when you add a click handler.

**Comment by KaelWD** [comment]
`v-card--link` uses `::before` for a focus overlay, and v-timeline uses it for the arrow.
