### ISSUE TITLE
8.9 issues

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#142]
I was setting this to override the default upper case, but it's now gone
    $button-text-transform := none
I fixed it with plain old css, so no big deal, but it did break my old code.

Tooltips on btn are transparent and text not vertically centered

v-btn with primary dark, :disabled=true is transparent

modal-container thing is 20px like 8.8 when not showing.

**Comment by johnleider** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Not sure what this is. If it is still an issue on master, please reopen a new ticket with a reproduction.
