### ISSUE TITLE
[Feature Request] How we can pass additional params in v-intersect directive handler?

### ISSUE THREAD

**Issue by mukeshghodela-easternts** [vuetifyjs/vuetify#14209]
### Problem to solve
<v-layout
                                row
                                wrap
                                class="m-0"
                                v-intersect.once="fetchPendingProperties($event, ...additionalParams)"
                            ></v-layout>

### Proposed solution
<v-layout
                                row
                                wrap
                                class="m-0"
                                v-intersect.once="fetchPendingProperties($event, ...additionalParams)"
                            ></v-layout>

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
