### ISSUE TITLE
[Bug Report][2.5.8] VMenu - non-deterministic bug with showing

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#14204]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.61
**OS:** Windows 10

### Steps to reproduce
This bug is hard to reproduce because it's non-deterministic but I see it  very often in my project.

To reproduce it, click on the first input field, then on the second. Sometimes click on the background. Do it for about 1-2 minutes. The bug will eventally show up.

To better visualize it, here is the GIF:
![vmenu_bug](https://user-images.githubusercontent.com/17653648/135109130-1a75391f-0721-407b-8966-8bf4abd32609.gif)

As you can see, sometimes the calendar is not shown, although the input (which is the activator) is focused.

This bug was not present in Vuetify 1.x

### Expected Behavior
Calendar should be always shown when I click the input.

### Actual Behavior
Sometimes the calendar is not showing but the input is focused.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/zYzyJwO" target="_blank">https://codepen.io/mikilll94/pen/zYzyJwO</a>

**Comment by Mikilll94** [comment]
I observe that this bug is more frequent in larger projects.

**Comment by MajesticPotatoe** [comment]
duplicate #7610
posted workaround should work
<https://codepen.io/majesticpotatoe-the-bashful/pen/zYzXExV>
