### ISSUE TITLE
[Bug Report][2.2.21] V-btn Loading with delay

### ISSUE THREAD

**Issue by HenriqueAurelio** [vuetifyjs/vuetify#14215]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.10
**Browsers:** Edge 94.0.992.31
**OS:** Windows 10

### Steps to reproduce
Click the button

### Expected Behavior
Expected the button getting loading status before getting information from backend

### Actual Behavior
Doesn't get loading status before the information and gets some delay to be on loading

### Reproduction Link
<a href="https://codepen.io/henriqueSilvas/pen/XWgOPry" target="_blank">https://codepen.io/henriqueSilvas/pen/XWgOPry</a>

### Other comments
I used this kind of loading status a lot but first time getting this delay and weird behaviour

**Comment by KaelWD** [comment]
Sounds like you might be doing something expensive on the main thread, blocking vue from rendering. You can wait for vue to render first by calling your expensive function inside a `this.$nextTick(() => {...})`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
