### ISSUE TITLE
[Bug Report][2.5.9] Focusing `v-list-item` in `v-dialog` prevents closing the window with Escape key

### ISSUE THREAD

**Issue by adamsol** [vuetifyjs/vuetify#14221]
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.159
**OS:** Windows 10

### Steps to reproduce
Click the first sentence and press Esc.

### Expected Behavior
The dialog window should get closed.

### Actual Behavior
It remains open.

### Reproduction Link
<a href="https://codepen.io/adamsol1/pen/vYZMLPX" target="_blank">https://codepen.io/adamsol1/pen/vYZMLPX</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
