### ISSUE TITLE
Broken templates on documentation page

### ISSUE THREAD

**Issue by johangithub** [vuetifyjs/vuetify#1422]
### Versions

Ubuntu 16.04, Firefox 55.0.2
![screenshot](https://user-images.githubusercontent.com/15177043/29490896-7653a2c4-8510-11e7-8520-96204a3e24c1.png)

### What is expected ?

For the documentation page(https://vuetifyjs.com/vuetify/why-vuetify)
On the left is my Firefox screen and on the right is google chrome (works fine).
### What is actually happening ?
Notice that texts are overlapped on the left.

### Reproduction Link
See attached picture.

**Comment by nekosaur** [comment]
Thank you for reporting this, but could you please open an issue on the [docs](https://github.com/vuetifyjs/docs) repo instead?
