### ISSUE TITLE
[Bug Report][2.5.8] v-text-field disable: can not select text to the end.

### ISSUE THREAD

**Issue by van-huyen** [vuetifyjs/vuetify#14238]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.61
**OS:** Windows 10

### Steps to reproduce
replace this code into reproduction link (johnleider's code :D)

      <input style="width:200px" v-model="model" class="grey" ></input>
      <input style="width:200px" v-model="model" class="grey" disabled></input>
      <v-text-field 
         v-model="model"
         style="width:200px"
         label="Enable"
         single-line outlined
      > </v-text-field>
      <v-text-field 
         v-model="model"
         style="width:200px"
         label="Disable"
         single-line outlined disabled
      > </v-text-field>

After that,
Input a long text, and select text to the end.

### Expected Behavior
v-text-field disable should be like input disable tag: can select text to the end.

### Actual Behavior
v-text-field disable: can not select text to the end.

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/NWPYmjp?editors=1010" target="_blank">https://codepen.io/johnjleider/pen/NWPYmjp?editors=1010</a>

video:

https://user-images.githubusercontent.com/83264685/136127775-d8273115-7a23-40f4-bca0-738bc01900a9.mp4

**Comment by johnleider** [comment]
This is also an issue with autocomplete, combobox, and select, we should update those as well.

Playground: https://www.toptal.com/developers/hastebin/axosoliqas.xml
