### ISSUE TITLE
[Documentation] Documentation for `nudge-width` is unhelpfull/baffling

### ISSUE THREAD

**Issue by davidbludlow** [vuetifyjs/vuetify#14235]
### Environment

**Browsers:** Firefox 92.0
**OS:** Windows 10

### Steps to reproduce
Look at the documentation for `nudge-width`, on the v-menu API documentation page

### Expected Behavior
It to tell me what that prop does

### Actual Behavior
The closest I can guess, `nudge-width` might be a minimum width? but no, that makes no sense, because there is already a prop for `min-width`. I don't know what it does. I am at a loss.

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-menu/#props" target="_blank">https://vuetifyjs.com/en/api/v-menu/#props</a>

### Other comments
Also, while you are at it, how about you change the documentation of `nudge-right` from "Nudge the content to the right" to "Nudge the menu to the right of where it would otherwise be"

Also, consider renaming `nudge-bottom` to be `nudge-down`, because that is way easier to understand, because it is proper grammar. But that is a separate issue. `nudge-bottom` makes me think "Why are we just pushing (nudging) on the bottom of the menu? Where are we pushing the bottom of the menu to? Are we pushing it up? Oh! Maybe it means that we increase the bottom padding of the menu so that there will be more white white space at the bottom of the menu, below the wordy content of the menu?" I had to do experiments to figure out that my initial impressions were wrong.

**Comment by KaelWD** [comment]
> consider renaming nudge-bottom to be nudge-down

In v3 there's just `offset`

**Comment by kendallroth** [comment]
@KaelWD At first glance, `offset` seems to affect both x and y positioning. I may not understand how it interacts with the `anchor` and `origin` props, but could there be some clarification given here? For example, `anchor="bottom end" offset="64"` moves it down and to the right by `64px`.
