### ISSUE TITLE
[Documentation] NO! NO! NO! Dont use codepen... so difficult to access and loading time so heavy.

### ISSUE THREAD

**Issue by piyushdolar** [vuetifyjs/vuetify#14242]
### Environment
**Vuetify Version:** 3.0.0-alpha.11

**Browsers:** Chrome 94.0.4606.71
**OS:** Mac OS 10.15.7

### Steps to reproduce
Check with any documentation it's so difficult to access the content, I really like v2 documentation design.

so easy and instant load
this latest doc design is so heavy, please update I'm personally facing this problem and I'm thinking to move on bootstrap latest doc and version easy to use and access.

### Expected Behavior
Remove codpen or any third party javascript.
You really messed up UX.

### Actual Behavior
Stupid codepen loading time.

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/dialogs/#without-activator" target="_blank">https://next.vuetifyjs.com/en/components/dialogs/#without-activator</a>

### Other comments
Please make it simple UI like bootstrap or do by your own just clean UI.
or let me in to design your doc system.

IF ANY USER AGREED WITH ME ABOUT THIS LATEST V3 DOCUMENTATION DESIGN PLEASE COMMENT YOUR THOUGHTS, I WANNA SEE WHO ELSE IS FACING AND FRUSTRATED LIKE ME.
(YOUR 10 SECONDS TIME WILL BE HELPFULL TO IMPROVE V3 FRONTEND)

**Comment by KaelWD** [comment]
It's alpha, stop whinging. The v3 documentation is still built with v2, the embedded codepens are just temporary so we can have some examples that actually run.

**Comment by KaelWD** [comment]
Follow #14048 for the docs update
