### ISSUE TITLE
[Bug Report][2.5.9] v-scroll ignored in v-data-table

### ISSUE THREAD

**Issue by rmirabelle** [vuetifyjs/vuetify#14254]
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.71
**OS:** Windows 10

### Steps to reproduce
Add v-scroll directive to v-data-table with specified height. 

### Expected Behavior
`onScroll` callback is executed on scroll

### Actual Behavior
scrolling does nothing at all. table never detects scroll.

### Reproduction Link
<a href="https://codepen.io/rmirabelle/pen/eYEYPvW?editors=1111" target="_blank">https://codepen.io/rmirabelle/pen/eYEYPvW?editors=1111</a>

### Other comments
I would settle for another approach to detecting scrolling of v-data-table in the mean time

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
