### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] vuetify/locale/adapters not found

### ISSUE THREAD

**Issue by kangchengkun** [vuetifyjs/vuetify#14257]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.20
**Browsers:** Chrome 94.0.4606.81
**OS:** Mac OS 10.15.7

### Steps to reproduce
Follow this docu: https://next.vuetifyjs.com/en/getting-started/installation/

1. Install latest Vue Cli: @vue/cli 4.5.13
2. Choose: **Manually select features **
```
? Please pick a preset: **Manually select features**
? Check the features needed for your project: 
 ◉ Choose Vue version
 ◉ Babel
 ◯ TypeScript
 ◯ Progressive Web App (PWA) Support
 ◉ Router
 ◉ Vuex
 ◯ CSS Pre-processors
 ◉ Linter / Formatter
 ◉ Unit Testing
❯◉ E2E Testing

```
and choose **Vue 3.x**

3. cd my-app
4. **vue add vuetify**
5. Choose: **Vuetify 3 Preview (Vuetify 3)**
As there is no any choice with name **V3 (alpha)**

```
? Choose a preset: (Use arrow keys)
  Configure (advanced) 
  Default (recommended) 
  Vite Preview (Vuetify 3 + Vite) 
  Prototype (rapid development) 
❯ Vuetify 3 Preview (Vuetify 3)
```
6. main.js
```
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import vuetify from './plugins/vuetify';
import { loadFonts } from './plugins/webfontloader';

loadFonts();

createApp(App).use(router).use(store).use(vuetify).mount('#app');

```
7. vuetify.js
```
// Styles
import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';

// Vuetify
import { createVuetify } from 'vuetify';

export default createVuetify();
// https://vuetifyjs.com/en/introduction/why-vuetify/#feature-guides

```
8. Follow https://next.vuetifyjs.com/en/features/internationalization/#vue-i18n 
9. Run `vue-cli-service serve`

### Expected Behavior
Can start app properly

### Actual Behavior

```
Error  in ./src/plugins/vuetify.js

Module not found: Error: Can't resolve 'vuetify/locale/adapters' in '/Users/e0445226/go/src/vuetify-vue3/src/plugins'

```

### Reproduction Link
<a href="https://github.com/kangchengkun/vuetify-vue3" target="_blank">https://github.com/kangchengkun/vuetify-vue3</a>

**Comment by meirlamdan** [comment]
This is definitely a serious problem.
When installing with vue cli there is no option to select "V3 (alpha)"
And any other choice gives an error
Please fix it soon
