### ISSUE TITLE
[Bug Report][2.5.9] V-Tooltip does not self-position correctly sometimes on (narrow screen) mobile

### ISSUE THREAD

**Issue by adriancable** [vuetifyjs/vuetify#14256]
### Environment
**Vuetify Version:** 2.5.9
**Last working version:** 2.3.18
**Vue Version:** 2.6.14
**Browsers:** Safari 15.0
**OS:** iOS

### Steps to reproduce
Seems this is a new issue. We don't have specific code to reproduce since it doesn't always happen, but please see attached iCloud video in the 'reproduction link' which makes what happens very clear. It happens (intermittently) with any tooltip where there isn't enough space on the screen to respect e.g. the 'right' attribute on <v-tooltip right ...>. NB behaviour not affected by offset-overflow.

### Expected Behavior
Tooltip, when it appears, is a sensible size.

### Actual Behavior
Tooltip when it appears is a silly size (much too narrow, much too tall). However, scrolling the page up and down a few times by touch bit-by-bit makes the tooltip resize itself correctly.

### Reproduction Link
<a href="https://share.icloud.com/photos/0x7n9SmD95gabIzq4g8YReuOg" target="_blank">https://share.icloud.com/photos/0x7n9SmD95gabIzq4g8YReuOg</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
