### ISSUE TITLE
[Feature Request] change menu expansion arrow's direction in guides

### ISSUE THREAD

**Issue by srjthpa** [vuetifyjs/vuetify#14268]
### Problem to solve
the icon used for expanding menu content list (form inputs and controls, pickers etc) by default points downwards and when clicked on, points upwards. 
the downwards pointing of this icon is creates a confusing situation whether i have opened the list or  expanded the list . having me to double check it. 

### Proposed solution
change the icon to point towards the right to indicate unopened content and then point it down when the menu is expanded to collapse the menu.

**Comment by KaelWD** [comment]
https://material.io/components/menus#exposed-dropdown-menu

This is a very common UI pattern, the arrow points in the direction of the action.
