### ISSUE TITLE
[Bug Report][2.5.9] v-slide-group "vibrates" on Firefox

### ISSUE THREAD

**Issue by farrago** [vuetifyjs/vuetify#14263]
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.11
**Browsers:** Firefox 93.0
**OS:** Windows 10

### Steps to reproduce
1. Open Firefox 93 on Windows
2. Go to the official docs for Slide Groups: https://vuetifyjs.com/en/components/slide-groups/ (Last updated:10/11/2021, 4:33:35 PM)
3.  Press the right arrow on any of the example slide-groups

The group slides correctly initially, but then vibrates at the end for an extended period of time.
This DOES NOT happen on Edge on iOS Safari. Haven't tested on Chrome as I don't have it installed, but I assume it has the same behaviour as it's the same engine as Edge.

### Expected Behavior
Based on the behaviour in Edge, it should scroll left then have a small "bounce then settle" animation at the end of the scroll.

### Actual Behavior
On Firefox it scrolls left but when it hits the "bounce" animation it just keeps vibrating for an extended period of time.

### Reproduction Link
<a href="https://jsfiddle.net/bfm8vz95/1/" target="_blank">https://jsfiddle.net/bfm8vz95/1/</a>

### Other comments
Vuetify and Vue versionsbased on the Vuetify docs repo's `package.json` (and some investigation of Vuex repo).  Apologies if the values in the repo don't match what is used to build the official page.

**Comment by KaelWD** [comment]
> a small "bounce then settle" animation at the end of the scroll

Can you share a recording of this? It shouldn't happen either.
