### ISSUE TITLE
[Bug Report][2.5.10] Autocomplete with headers/divider wrong item highlight index

### ISSUE THREAD

**Issue by theodem** [vuetifyjs/vuetify#14279]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.13
**Browsers:** Chrome 94.0.4606.71
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select any item that is in a list with header(s) or divider(s).

### Expected Behavior
The selected item should be highlighted.

### Actual Behavior
If you select an item that is under 1 header, the selected item + 1 will be highlighted.
If you select an item that is under 3 headers the selected item + 3 will be highlighted.

### Reproduction Link
<a href="https://codepen.io/theodem/pen/WNEQyLq" target="_blank">https://codepen.io/theodem/pen/WNEQyLq</a>

### Other comments
This issue dont appear if you replace the "divider" or "header" key by "disabled".

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
