### ISSUE TITLE
[Bug Report][2.5.10] Calendar click event failing on latest Firefox

### ISSUE THREAD

**Issue by denizaygun** [vuetifyjs/vuetify#14276]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Failing on latest Firefox (and Safari). Unable to click any events on a v-calendar. A "ReferenceError: TouchEvent is not defined" is thrown. On my own Vuetify installation and the live vuetify docs.

This seems to be an issue regardless of OS.

### Expected Behavior
Clicking a calendar event should work.

### Actual Behavior
Clicking a calendar event fails. 

### Reproduction Link
https://vuetifyjs.com/en/components/calendars/#click

Could be similar to this issue: https://github.com/vuetifyjs/vuetify/issues/14243

**Comment by boobo94** [comment]
> Running 2.5.9 does **not** fix this issue for me.

Nor for me :(

The problem is encountered on both Safari Version 15.1 (17612.2.9.1.20) and Firefox 94.0.

Waiting the release.
