### ISSUE TITLE
Centering horizontally and vertically does not work within v-app

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1428]
### Steps to reproduce
Create a template with `<v-app>` -> `<v-container fluid fill-height>` -> `<v-layout flex align-center justify-center>`

### Versions
Vue 2.4.2, Vuetify 0.14.11, Edge 15.

### What is expected ?
Because of the `fill-height`. I would expect the `<v-container>` to take up all available height.

### What is actually happening ?
The container is only as high as the content inside it. The 100% height doesn't appear to work.

It works without `v-app`: https://codepen.io/anon/pen/ZJxOxo

It also works if the height is not 100% but 100vh, but this is specific to the layout of the page because as soon as you have surrounding elements, you have to `calc(100vh - other_heights)`: https://codepen.io/anon/pen/wqmWjg

### Reproduction Link
https://codepen.io/anon/pen/ayYZqP

**Comment by johnleider** [comment]
You were missing ```<main>```

https://codepen.io/anon/pen/XaEpPx
