### ISSUE TITLE
Text field label too long when prepend-icon or append-icon is used

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1430]
### Steps to reproduce
Use a `<v-text-field>` with `prepend-icon` and a long label that doesn't fit inside the text field.

Use a `<v-text-field>` with `append-icon` and a long label that doesn't fit inside the text field.

### Versions
Vue 2.4.2, Vuetify 0.14.11, Edge 15

### What is expected ?
The label should be clipped with ellipsis just like it does without icons.

Moreover, when append-icon is used, the label should clip before the appended icon, otherwise it's unpretty.

### What is actually happening ?
With prepended icons, the layout is broken and the label clips at the wrong place.

With appended icons, the icons cover the label.

### Reproduction Link
https://codepen.io/anon/pen/QMmGjX

**Comment by nekosaur** [comment]
While I do think your example is a bit too contrived to represent a real-world scenario, I have adjusted the label max-width slightly to account for icons.

**Comment by smares** [comment]
To be honest, it was a real-world scenario on mobile with German labels. :D

**Comment by johnleider** [comment]
Closed with #1459
