### ISSUE TITLE
[Bug Report][2.5.10] v-autocomplete will not display append-item if hide-no-data

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#14300]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Firefox 93.0
**OS:** Windows 10

### Steps to reproduce
Type 5 into the autocomplete.
The append-item text will not be shown

### Expected Behavior
Always show the append-item template since it should be de-coupled from the hide-no-data property, otherwise it does not make sense to me that there is a #no-data slot as well.

### Actual Behavior
#append-item is not shown

### Reproduction Link
<a href="https://codepen.io/auspex/pen/WNExqdP" target="_blank">https://codepen.io/auspex/pen/WNExqdP</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
