### ISSUE TITLE
v-select autocomplete causes iPhone to freeze

### ISSUE THREAD

**Issue by toast38coza** [vuetifyjs/vuetify#1431]
### Steps to reproduce

1. On an iPhone (I used iPhone 7) go to the (Vuetify docs page for selects)[https://vuetifyjs.com/components/selects]. Scroll to the autocomplete example. 
2. Click on the autocomplete select 
3. Everything freezes. Only way to resume is to kill Safari and restart. 

### Versions

Vuetify: 0.13 (doesn't work, but doesn't crash the browser) and 0.14 (crashes the browser)
Browsers: Mobile Safari on iPhone 7
OS: iOS

### What is expected ?

Autocomplete should show options

### What is actually happening ?

Browser freezes 

### Reproduction Link

* https://codepen.io/anon/pen/BdrQXy

Or just checkout the docs:

* https://vuetifyjs.com/components/selects

**Comment by nekosaur** [comment]
@johnleider and anyone else, can you reproduce this? I've checked on my 6S and it works fine.

**Comment by swallaaa** [comment]
@nekosaur 

It's causing my iPhone 7 Plus (Safari and Chrome) with iOS 10.3.3 to freeze as well. All the "selects" except the autocomplete work perfectly fine.

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/29687392-45f75458-88ea-11e7-967e-89332942fbef.png)
I was able to easily reproduce the issue on 0.14.11, but it seems to have been corrected from my optimization pass on ```v-select``` for 0.15. If anyone else is able to confirm on dev that would be appreciated.

**Comment by stoked74** [comment]
The autoselect opens for me in chrome but doesn't filter. It freezes Safari when you try and open the select.

iPhone 7 ios 10.3.3

![img_1063](https://user-images.githubusercontent.com/963226/29687449-808a751e-88ea-11e7-8905-bde75e54e511.PNG)

**Comment by johnleider** [comment]
This has been resolved with 0.15.0-beta.1
