### ISSUE TITLE
[Feature Request] UI kit for penpot

### ISSUE THREAD

**Issue by Silur** [vuetifyjs/vuetify#14311]
### Problem to solve
Figma and Adobe XD are both proprietary sofware which kinda contradicts the openness of vue and vuetify.

### Proposed solution
 I'd be nice to have to have the UI kit resources (as libraries) for https://penpot.app/ too, which is an open-source, self-hosted alternative for figma.

**Comment by JPustkuchen** [comment]
Penpot is suuuuuuuuper cool and stable now. Really worth a look! (And a Vuetify UI Kit) ;)

**Comment by derHodrig** [comment]
https://www.figma.com/community/plugin/1219369440655168734/penpot-exporter
https://github.com/penpot/penpot/issues/849#issuecomment-2286860700

I tested it. It kinda works. You export your figma stuff and import that in penpot (the archive). The prototypes are not working but the design is there. Components seems not to work and also some edge cases of designs.
Maybe it will work with the Vuetify Figma Lib.

In the end some work must be made in penpot to get the most of it (component variants etc.)
