### ISSUE TITLE
[Feature Request] Provide `d-table-row-group` display helper class

### ISSUE THREAD

**Issue by adrianjost** [vuetifyjs/vuetify#14325]
### Problem to solve
Allows to change the display type of `tbody`-html-tag in responsive designs. For example change it to `d-block` on mobile, but go back to the default on md and up.
While we are at it, we should probably also add  the other not yet supported but valid values listed in the spec: https://www.w3.org/TR/css-display-3/#the-display-properties

### Proposed solution
- Extend https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/styles/settings/_utilities.scss#L27 with `table-row-group` (and the others) 
- update the documentation page: https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/pages/en/styles/display.md accordingly

**Comment by KaelWD** [comment]
We don't (and won't) provide utility classes for every possible CSS property. The most common values are already covered, if you need something niche like this you can add it yourself: https://vuetifyjs.com/en/features/sass-variables/
