### ISSUE TITLE
v-select menu doesn't focus currently-selected item

### ISSUE THREAD

**Issue by kevmo314** [vuetifyjs/vuetify#1432]
This is a feature request to follow the material design spec a little closer. On https://dev.vuetifyjs.com/components/selects, currently the `v-select` menu always appears on the first item of the list (State 4 is the currently active item):

![](http://i.imgur.com/yFv3WU2.png)

The material design spec indicates that the [selected item should appear above the element](https://material.io/guidelines/components/menus.html#menus-behavior), specifically "Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element." so I expected it to look something more like this:

![](http://i.imgur.com/TNrVBye.png)

Here is a demo of the behavior from material design components: https://material-components-web.appspot.com/select.html

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
