### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] [Bug Report][3.0.0-alpha.11] white screen

### ISSUE THREAD

**Issue by devops724** [vuetifyjs/vuetify#14323]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Last working version:** 3.0.0-alpha.11
**Vue Version:** 3.2.20
**Browsers:** Chrome 94.0.4606.81
**OS:** Linux x86_64

### Steps to reproduce
Hi there 
i can't get vuetify 3 alpha 11 working 
i pasted webpack and package.json
show white screen

### Expected Behavior
show elements

### Actual Behavior
white screen

### Reproduction Link
<a href="https://dpaste.com/8TTGVRCZQ" target="_blank">https://dpaste.com/8TTGVRCZQ</a>

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
