### ISSUE TITLE
[Bug Report][2.5.10] Incorrect icons of v-alert

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#14327]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Edge 95.0.1020.30
**OS:** Windows 10

### Steps to reproduce
Create a `v-alert` component

### Expected Behavior
The icon of `warning` alert should be `mdi-alert`; The icon of `error` alert should be `mdi-octagon-alert`.

### Actual Behavior
The icon of `warning` alert is `mdi-exclamation`; The icon of `error` alert is `mdi-alert`.

### Reproduction Link
<a href="https://codepen.io/kingyue737/pen/PoKmyJx" target="_blank">https://codepen.io/kingyue737/pen/PoKmyJx</a>

### Other comments
docs:
![image](https://user-images.githubusercontent.com/40021217/139025728-cdf68870-6d6f-4c4a-b8c2-e276bec5f663.png)

actual:
![image](https://user-images.githubusercontent.com/40021217/139025843-1c7e0bdb-456d-4184-b048-d06aaa055d47.png)

**Comment by victor1014** [comment]
Me too

**Comment by KareemDa** [comment]
> The mdi-svg preset needs updating to match the mdi one.

@KaelWD 
but the `mdi-svg` shows right icons. `mdi` don't

**Comment by larryh** [comment]
I'm seeing the exact same behavior for error and warning being wrong.

**Comment by kingyue737** [comment]
![image](https://user-images.githubusercontent.com/40021217/168957688-b6985b30-abb7-465d-8299-fe12df0b8494.png)

worse now, icon of error is the same as the default close button. Why not just use the same icons as documentation?
