### ISSUE TITLE
[Bug Report][2.5.7] Calendar is not displayed correctly when used with tabs

### ISSUE THREAD

**Issue by EnricaEnrica** [vuetifyjs/vuetify#14336]
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.54
**OS:** Windows 10

### Steps to reproduce
Open the calendar with type setted to "week". 

### Expected Behavior
The header must be aligned with the scrollable area.

### Actual Behavior
The header is not aligned with the scollable area.

### Reproduction Link
<a href="https://codepen.io/EnriCodes/pen/qBXXPGj?editors=1010" target="_blank">https://codepen.io/EnriCodes/pen/qBXXPGj?editors=1010</a>

**Comment by KaelWD** [comment]
Related: #10168

https://github.com/vuetifyjs/vuetify/blob/15e28f6e701de260fbc7acf3ae1bb9cfb4e4d7e3/packages/vuetify/src/components/VCalendar/VCalendarDaily.ts#L47-L49
