### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] v-navigation-drawer position="bottom" spans entire viewport, instead of showing on the bottom

### ISSUE THREAD

**Issue by sgielen** [vuetifyjs/vuetify#14334]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.20
**Browsers:** Chrome 95.0.4638.54
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use a v-navigation-drawer with position="bottom".

### Expected Behavior
The drawer is only visible on the bottom, just as it is visible on the right if position="right" or on the top if position="top".

### Actual Behavior
The drawer has `top: 0` and `bottom: 0` set, therefore it spans the entire page.

### Reproduction Link
<a href="https://github.com/sgielen/vue3-vuetify3-ctnmkd" target="_blank">https://github.com/sgielen/vue3-vuetify3-ctnmkd</a>
<a href="https://stackblitz.com/edit/vue3-vuetify3-ctnmkd?file=src%2FApp.vue" target="_blank">https://stackblitz.com/edit/vue3-vuetify3-ctnmkd?file=src%2FApp.vue</a>

### Other comments
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass#L23

I think the issue is that if the v-navigation-drawer--bottom class is set, "top: auto" only overrides "top: 0" if "--is-mobile" is also set.

**Comment by johnleider** [comment]
fixed by 5e2e16623

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
