### ISSUE TITLE
[Bug Report][2.5.10] Speed Dial not Working in Bottom Navigation

### ISSUE THREAD

**Issue by ThcDelux3** [vuetifyjs/vuetify#14337]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.6
**Browsers:** Chrome 95.0.4638.54
**OS:** Windows 10

### Steps to reproduce
1.) Create a v-bottom-navigation and make it fixed.
2.) Put A  v-speed-dial around a button

There you go.

### Expected Behavior
The v-speed-dial should work like in the documentation 

### Actual Behavior
The buttons inside the v-speed-dial loose their styles and especially the height 

### Reproduction Link
<a href="https://codepen.io/felixruby/pen/wvqqmJL" target="_blank">https://codepen.io/felixruby/pen/wvqqmJL</a>

**Comment by KaelWD** [comment]
v-speed-dial is only intended to work with a fab.
