### ISSUE TITLE
[Bug Report][2.5.5] CSS for dev and build/production are different. Production CSS not as expected.

### ISSUE THREAD

**Issue by jtlindsey** [vuetifyjs/vuetify#14331]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.81
**OS:** Mac OS 10.15.7

### Steps to reproduce
Run in dev mode and visit localhost:8080
Run build and start and visit localhost:8080
See difference

### Expected Behavior
Styling should be the same

### Actual Behavior
Styling is different

### Reproduction Link
<a href="https://github.com/jtlindsey/vuetifynuxtbuildissue1/tree/withoutnuxt" target="_blank">https://github.com/jtlindsey/vuetifynuxtbuildissue1/tree/withoutnuxt</a>

### Other comments
Link is to branch without `nuxt`. Issue was found in new `nuxt` app and reproduced in raw `vuetify` app.

**Comment by KaelWD** [comment]
Screenshots? What styling is different?

**Comment by jtlindsey** [comment]
`col-12 col-md-6` is not applied the same in dev and production.

```
<template>
  <v-row>
    <v-col cols="12">
      <v-row>
        <v-img
          class="col-12 col-md-6"
          max-height="250px"
          src="https://images.unsplash.com/photo-1518895949257-7621c3c786d7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=688&q=80"
        ></v-img> 

        <v-col class="col-12 col-md-6">
          <div>Post Title Example</div>
        </v-col>
      </v-row>
    </v-col>

  </v-row>
</template>
```

Production
<img width="1440" alt="Screen Shot 2021-10-31 at 12 44 26 PM" src="https://user-images.githubusercontent.com/7409277/139593831-7a6dd829-3170-42e3-a541-e20ff1807b89.png">

Dev
<img width="1438" alt="Screen Shot 2021-10-31 at 12 43 30 PM" src="https://user-images.githubusercontent.com/7409277/139593832-89d37231-f383-4f64-9197-a807f3890ece.png">

**Comment by KaelWD** [comment]
It's the same in both prod and dev for me, the problem is `.v-responsive` overriding the grid rules. This isn't really fixable without increasing specificity on the grid rules everywhere, you should use the `v-col` component directly or only apply these classes to plain divs.

**Comment by jtlindsey** [comment]
_"It's the same in both prod and dev for me"_
How did you attempt to reproduce this? I reproduced this on 2 different machines with this repo.

**Comment by KaelWD** [comment]
- Cloned the repo
- `yarn`
- `yarn start`
- `yarn build` then `ws -d dist -s index.html`

**Comment by jtlindsey** [comment]
Maybe it's an `npm` vs `yarn` thing (i was using npm). I don't know. Thanks for trying. Switching to `v-col` resolved the issue.
