### ISSUE TITLE
[Bug Report][2.5.10] Autofocus input in form shows validation errors in dialog

### ISSUE THREAD

**Issue by kovalromank** [vuetifyjs/vuetify#14345]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.54, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Other, Opera
**OS:** Windows 10, Linux, Mac OSX, iOS, Android, Windows

### Steps to reproduce
- Open codepen
- Click open button, notice the Title input focused, no errors shown, as expected
- Close the dialog 
- Click open button again
- Notice the title input gets focused automatically but a "Title is required" error is shown and the input goes into an error state.

### Expected Behavior
When using the autofocus prop the input will not go into an error state when rendered.

### Actual Behavior
The input goes into an error state without the user having interacted with it.

### Reproduction Link
<a href="https://codepen.io/romankoval10/pen/jOLmKvP?editors=1111" target="_blank">https://codepen.io/romankoval10/pen/jOLmKvP?editors=1111</a>

**Comment by KaelWD** [comment]
Validation is triggered on blur, even if it was focused automatically. If you want the form state to reset when the dialog is closed see #6764.

**Comment by kovalromank** [comment]
In the codepen the `v-form` is being mounted and unmounted every time the dialog opens, because of the `v-if` around the dialog content, so I do not think #6764 applies here.

When the first time the dialog is opened,

> Autofocus processing was blocked because a document already has a focused element.

is printed in the console and the input does not go into an error state.

The next times that the dialog is opened, nothing is printed to the console but the form gets validated for some reason and the input shows an error message.

You can see this in the debug codepen, https://cdpn.io/romankoval10/debug/jOLmKvP/GnAnbXxXdRDA

In my own application I managed to fix this by resetting the form when the dialog content mounts:

```javascript
mounted() {
  this.$nextTick(() => {
    (this.$refs.form as any)?.reset();
  });
}
```

But this seems to be more of a hack than anything, that's why I decided to file this bug report.

**Comment by KaelWD** [comment]
Ah sorry I missed the v-if. This is caused by a conflict between https://github.com/vuetifyjs/vuetify/blob/6aaf52b363d9e6aa2054386b59dfb8317dcb4d7b/packages/vuetify/src/components/VTextField/VTextField.ts#L235 and https://github.com/vuetifyjs/vuetify/blob/0e31691db0bcfe0f33cfe67bd43ef17b04ddfe0d/packages/vuetify/src/components/VDialog/VDialog.ts#L191

**Comment by kovalromank** [comment]
Thanks!
