### ISSUE TITLE
[Bug Report][2.5.10] Autocomplete dropdown covers validation error message

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#14355]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.81
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use VAutocomplete, where the suggestion dropdown covers the error message

### Expected Behavior
error message would be visible 

### Actual Behavior
dropdown suggestions cover the error message

### Reproduction Link
<a href="https://codepen.io/codepen123456789/pen/GRvOWdR?editors=1010" target="_blank">https://codepen.io/codepen123456789/pen/GRvOWdR?editors=1010</a>

### Other comments
Is this expected behavior? Should I hide all suggestions in the case of an error?

**Comment by KaelWD** [comment]
https://material.io/components/menus#exposed-dropdown-menu

You can use `:menu-props="{ nudgeBottom: 12 }"` to shift the menu down a bit, but this isn't part of material design.
