### ISSUE TITLE
[Bug Report][2.5.10] Hidden-{breakpoint} classes overlap each other in some edge cases

### ISSUE THREAD

**Issue by MilenaMalysh** [vuetifyjs/vuetify#14353]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 94.0.4606.81
**OS:** Windows 10

### Steps to reproduce
1) add an element and apply hidden-md-only class to it
2) add another element and apply hidden-lg-only class to it
3) find a screen width when a lg device become an md device (947px in my case)

### Expected Behavior
Only one of the elements is shown

### Actual Behavior
Both elements are shown even though $vuetify.breakpoint.lg is already false at this point.
![image](https://user-images.githubusercontent.com/16187012/139706682-9fc0d572-5515-451a-9075-90b79ad06701.png)

### Reproduction Link
<a href="https://jsfiddle.net/MilenaMalysh/hc4n3tfu/30/show" target="_blank">https://jsfiddle.net/MilenaMalysh/hc4n3tfu/30/show</a>

**Comment by KaelWD** [comment]
:shrug: 

![Screenshot_20211102_045950](https://user-images.githubusercontent.com/16421948/139718297-3901229a-f691-494c-9797-7de4f2e9c414.png)
![Screenshot_20211102_050009](https://user-images.githubusercontent.com/16421948/139718359-204a2bda-fda2-4604-bd87-aebcec7f3d64.png)

**Comment by MilenaMalysh** [comment]
@KaelWD I just double-checked it again (now in Firefox) with the same settings you have, the problem still exists. I also checked the issue on a different Windows machine just in case.
![image](https://user-images.githubusercontent.com/16187012/139721119-ff5330d2-44a8-43c6-b7b8-23892686f8ce.png)

**Comment by KareemDa** [comment]
@KaelWD 
![image](https://user-images.githubusercontent.com/42810389/139840969-cb5f9cf7-b7d4-49e0-a834-3947d3dd1658.png)
you can notice that there is `-1` in the code which causes this problem
