### ISSUE TITLE
[Feature Request] Make Nav Drawer look better in mobile

### ISSUE THREAD

**Issue by IgorIlgiyaev** [vuetifyjs/vuetify#14352]
### Problem to solve
Drawer mobile view and disabling animations

### Proposed solution
To move the subtitles under the icons like this: 

<img width="74" alt="Screen Shot 2021-11-01 at 16 25 18" src="https://user-images.githubusercontent.com/20319110/139687818-eb270653-7b46-44a1-b038-1400f7b5c185.png">

**Comment by KaelWD** [comment]
This is implemented in v3 with `<v-btn stacked>`
