### ISSUE TITLE
Implement clickable link inside <v-checkbox> component's label

### ISSUE THREAD

**Issue by creepy00** [vuetifyjs/vuetify#1436]
### Steps to reproduce

Use a v-checkbox element with a label. Link inside it is not rendered and you cannot have something like terms & agreement link inside it.

### Versions
Latest of everything

### What is expected ?
The link to be rendered and clickable.

### What is actually happening ?
Tag is not rendered but escaped and displayed as text within tag.

### Reproduction Link
https://codepen.io/anon/pen/vJRzBL

**Comment by jacekkarczmarczyk** [comment]
Already fixed https://github.com/vuetifyjs/vuetify/pull/1265

**Comment by creepy00** [comment]
Thank you very much! :)
