### ISSUE TITLE
[Bug Report][2.5.10] v-tabs in dialog toolbar slightly move after loading

### ISSUE THREAD

**Issue by reynard80** [vuetifyjs/vuetify#14361]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.13
**Browsers:** Firefox 93.0
**OS:** Windows 10

### Steps to reproduce
Just click the OPEN DIALOG button and see the tabs slightly move after the dialog is opened.

### Expected Behavior
The tabs do not move after the dialog has been opened

### Actual Behavior
The tabs DO move after loading, which doesn't look professional in our project.

### Reproduction Link
<a href="https://codepen.io/m-fitch/pen/NWvwBEV" target="_blank">https://codepen.io/m-fitch/pen/NWvwBEV</a>

**Comment by KareemDa** [comment]
working fine on my machine, tested on chrome and firefox

**Comment by reynard80** [comment]
Might indeed be a problem with a Firefox extension.

**Comment by reynard80** [comment]
Sadly, I haven't got a clear reproduction path. 

You're right it seems to be a problem of my machine. On another machine it does indeed work as expected.

The strange thing is that it happens across browsers on that machine, but not all the time on each browser. Sometimes I have to open a dialog a few times before it happens.

**Comment by reynard80** [comment]
I've got a sample project on [GitHub ](https://github.com/reynard80/vuetify-dialog-issue) which shows the problem. The  [Codepen](https://codepen.io/m-fitch/pen/NWvwBEV) does in fact NOT show this behaviour.

Please checkout the sample project to reproduce the problem.
