### ISSUE TITLE
[Bug Report][2.5.4] Icon inside v-menu activator is pointer even when clicks are disabled

### ISSUE THREAD

**Issue by barfurth** [vuetifyjs/vuetify#14377]
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 94.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create a menu with `open-on-hover` and `:open-on-click: "false"`
2. Place an icon inside the activator slot
3. Hover the icon

### Expected Behavior
The icon should have the default cursor and not become a button. Clicking it should have no visible effect.

### Actual Behavior
The icon is wrapped in a button and uses pointer as its cursor. Clicking the button gives it a background effect.

### Reproduction Link
<a href="https://codepen.io/barfurth/pen/wvqpbNe" target="_blank">https://codepen.io/barfurth/pen/wvqpbNe</a>

### Other comments
As the icon does not provide any functionality when clicking it seems unintuitive that is appearing to the user as a clickable object. The `menuable` mixin appears to add a click handler regardless of props set on the menu.

**Comment by KaelWD** [comment]
The click listener was moved to menuable in [`553a0d8c`](https://github.com/vuetifyjs/vuetify/commit/553a0d8c1e5e98014451ef7d2253778712bbfec8#diff-a510753fb8a85de8db6181b6c250d80bcccbf5fa2d4a97e5660e233bfc718200R269-R275) instead of staying in VMenu.
