### ISSUE TITLE
[Bug Report][2.5.7] Calendar event for the whole day is displayed incorrectly (calendar type month)

### ISSUE THREAD

**Issue by EnricaEnrica** [vuetifyjs/vuetify#14371]
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Create an event that starts at 00.00 of one day and ends at 00.00 of the next day and set the calendar type to "month"

### Expected Behavior
The event is displayed in one day

### Actual Behavior
The event is displayed in 2 days.
Using the other calendar types the event is displayed correctly. 

### Reproduction Link
<a href="https://codepen.io/EnriCodes/pen/wvqprEq?editors=1011" target="_blank">https://codepen.io/EnriCodes/pen/wvqprEq?editors=1011</a>

**Comment by EnricaEnrica** [comment]
I fixed the reproduction link.

**Comment by KaelWD** [comment]
#13667 fixed this for the day view but not month.
