### ISSUE TITLE
[Bug Report][2.6.0-beta.0] v-select divider is selected when using keyboard up/down

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#14372]
### Environment
**Vuetify Version:** 2.6.0-beta.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
1. Click on a v-select
2. Select any item. This will close the v-select
3. Use arrow key to go up or down

### Expected Behavior
It should go from one item to the next, skipping the divider

### Actual Behavior
It's selecting the divider with [object Object].

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/XWaVVLZ" target="_blank">https://codepen.io/pumpknhd/pen/XWaVVLZ</a>

**Comment by KaelWD** [comment]
Caused by #12815
