### ISSUE TITLE
[Bug Report][2.5.12] v-date-picker error when switching from (type='Month') to (type='Date') and month range is selected and range is true 

### ISSUE THREAD

**Issue by morteza-mortezai** [vuetifyjs/vuetify#14388]
### Environment
**Vuetify Version:** 2.5.12
**Vue Version:** 2.6.13
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
1. switch select to "Month" mode .
2. select two month range ( for exmpl : september and oktober) from dete-picker provided
3.switch select to "date" mode

### Expected Behavior
without error

### Actual Behavior
error "Invalid time value"

### Reproduction Link
https://github.com/morteza-mortezai/bug

https://stackoverflow.com/questions/69855173

<details>
<summary>Playground</summary>

```vue
<template>
  <v-app>
    <v-container>
      <v-row justify="center">
        <v-col cols="12">
          <v-select
            v-model="calType"
            label="select date type"
            item-text="value"
            item-value="key"
            :items="selectOptions"
            dense
            single-line
            @change="selectType($event)"
          >
          </v-select>
        </v-col>
        <v-col cols="12">
          <v-dialog
            ref="dialog"
            v-model="modal"
            :return-value.sync="date"
            persistent
            width="290px"
          >
            <template #activator="{ on, attrs }">
              <v-text-field
                v-model="date"
                label="Picker in dialog"
                prepend-icon="mdi-calendar"
                readonly
                v-bind="attrs"
                v-on="on"
              ></v-text-field>
            </template>
            <v-date-picker
              v-model="date"
              :locale="currentLocale"
              :range="range"
              :type="calType"
              :first-day-of-week="1"
              scrollable
            >
              <v-spacer></v-spacer>
              <v-btn
                text
                color="primary"
                @click="modal = false"
              >
                Cancel
              </v-btn>
              <v-btn
                text
                color="primary"
                @click="$refs.dialog.save(date)"
              >
                OK
              </v-btn>
            </v-date-picker>
          </v-dialog>
        </v-col>
      </v-row>
    </v-container>
  </v-app>
</template>

<script>
  export default {
    data () {
      return {
        modal: false,
        currentLocale: 'en',
        selectOptions: [
          { key: 'date', value: 'Date' },
          { key: 'month', value: 'Month' },
        ],
        calType: 'date',
        range: true,
        date: [],
      }
    },
    methods: {
      selectType ($event) {
        this.calType = $event
      },
    },
  }
</script>
```

</details>

### Other comments
it shows error

**Comment by KaelWD** [comment]
This expects `tableDate` to at least have a month:

https://github.com/vuetifyjs/vuetify/blob/42b56bbfdfb5ae218661adcf4441984237beb558/packages/vuetify/src/components/VDatePicker/VDatePicker.ts#L191-L193

In month mode `tableDate` is just the year, so `tableMonth` is `NaN` which ends up sending `2021-NaN-01` to https://github.com/vuetifyjs/vuetify/blob/2325dd9570b0fa543277304369010853c09034f8/packages/vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.ts#L32

**Comment by morteza-mortezai** [comment]
what happend for this ?

**Comment by lyla-liu** [comment]
so how can handle it?

**Comment by davibarbosa2** [comment]
Hey, @KaelWD , do you know if there is any workaround for this ?

**Comment by davibarbosa2** [comment]
Found a solution by providing the prop `picker-date`, then watching the property that changes the picker `type` and updating `picker-date` with a default value, like this:

 ```
watch: {
    selectedType(newVal, oldVal) {
      if (oldVal === 'month') {
        const [year, month] = this.today.split('-')

        this.pickerDate = `${year}-${month}`
      }
   }
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
