### ISSUE TITLE
[Bug Report][2.5.11] Vtabs fail to navigate when using router-link/router-view

### ISSUE THREAD

**Issue by gregveres** [vuetifyjs/vuetify#14387]
### Environment
**Vuetify Version:** 2.5.11
**Last working version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.54
**OS:** Windows 10

### Steps to reproduce
I have put together a reproduction code sandbox for this issue. In the sandbox, if you switch the vuetify version to 2.5.10, then you will see the sample working properly. 
Right now it is configured to use vuetify 2.5.11 where the sample fails.

The sample is setup with a top level app component that can navigate to a parent component. The parent component is placed within the app component using a <router-view>.
The routes are such that there are three child components to the parent. These represent the three tabs in the parent. 
As you click on the different tabs, the route changes and the tab content changes. 
Note that the code in the sandbox uses the strucutre from this SO answer for using VTabs with vue-router:
https://stackoverflow.com/questions/49721710/how-to-use-vuetify-tabs-with-vue-router

### Expected Behavior
As the user clicks on the tabs, no matter what order, the tab content should change to view the content for the selected tab.

### Actual Behavior
In 2.5.10, this is what happens.
In 2.5.11, the tab navigation happens properly when moving from left to right, but as soon as you move from right to left, the display of the tab content stops and never works again.
The route navigation continues to work, but the display of the proper tab contents stops working.

### Reproduction Link
<a href="https://codesandbox.io/s/vtabfailure-w3ifd" target="_blank">https://codesandbox.io/s/vtabfailure-w3ifd</a>

**Comment by MatthewAry** [comment]
Seeing this issue in 2.5.12 as well. When you use the `to` tag in routes instead of the `href` navigation on tabs breaks. You can't access tabs that are left of the tab you have currently selected.

**Comment by gregveres** [comment]
Yes. it showed up in 2.5.11 and 2.5.12 was a quick fix for the VDialog / VMenu bug introduced in 2.5.11 so no chance it was fixed in 2.5.12.

Did you try with href? Does it still work with href? I didn't even know that was an option on v-tab until just now when I looked it up. I only ever use named routes throughout my application.

**Comment by MatthewAry** [comment]
As much as I like vuetify, the VTabs components and the way it works with the router can be pretty hard to work with. `href` does not have the same functionality as `to` so with what I'm doing, if I use `href` my browser history remains unaffected when I change tabs as opposed to `to` which does push changes to my history.

HREF works but you loose features.

**Comment by gregveres** [comment]
You aren't wrong about using VTabs and the router. I just finally figured out how to get it to not create my tab content component twice on each navigation. This was causing issues because I am using the composition API and during setup I am calling out to my server. So on every navigation, I was hitting the server twice. I finally figured out a soltuion that would work for me:
https://stackoverflow.com/a/69832105/5500101

**Comment by MatthewAry** [comment]
Rolling back to 2.5.10 fixes this issue. From what I am seeing, something _(and I don't know what it is that is doing it)_ is invoking methods in the VTabs components such that clicking on a tab left of the currently active tab will do the following according to Vue Dev Tools:

1. Change Event emitted by VTabs with new tab route value
2. Change Event emitted by VTabsBar with the new tab route value
3. Change Event emitted by VTab with no payload
4. Change Event emitted by VTabs with old tab route value (the route to the tab we're currently on and want to leave)
5. Change Event emitted by VTabsBar with old tab route value
6. Change Event emitted by VTab with no payload

So it seems that we start going to where we want to go but then something happens which ends up sending us back.

**Comment by gregveres** [comment]
In Discord, @KaelWD  pointed to these two changes:
https://github.com/vuetifyjs/vuetify/commit/c999017b6f6a267b80b9f4c1a6ff322f63168b0e
https://github.com/vuetifyjs/vuetify/commit/13545ab4df30a1d4bdd98736c5980b3db5d93e42

I can't see the disabled check doing it because disabled isn't used in my example. I don't disable any tabs in my application.
The other one is more likely, but I can't imagine either of those if statements returning true in the example because I use a named route as the to attribute. I did change the to attribute to use the path instead of a named route, but that didn't "fix" the behaviour.

**Comment by KaelWD** [comment]
3df308f3305a77b1c2354fc7529bedc18b243dce
