### ISSUE TITLE
Auto attribute hardcode dropdown list height to 200px

### ISSUE THREAD

**Issue by itanka9** [vuetifyjs/vuetify#1438]
### Steps to reproduce

Create `v-select` with `auto` and `max-height` attributes

### Versions

vuetify 0.14.5
vue ^2.4.2

### What is expected ?

`max-height` attribute shoud work with `auto`.

### What is actually happening ?

`max height` is ignored when `auto` presents

See: https://github.com/vuetifyjs/vuetify/blob/24055902b6b62e955159619a54ab755328526757/src/components/VMenu/VMenu.vue#L158

### Reproduction Link

https://jsfiddle.net/mbeloshitsky/jr0me2zj/5/

**Comment by johnleider** [comment]
At the time of creating the auto functionality, it was a requirement. It may not be now, I'll have to do some testing.

**Comment by johnleider** [comment]
I've spent some time with this and the 200 is an absolute must with the current implementation and I don't think that we have any intentions on changing it. You can still specify this value with normal non-**auto** selects, and that's the way it shall stay for the foreseeable future.
