### ISSUE TITLE
[Bug Report][2.5.12] v-calendar Memory Leak (type: day, day4)

### ISSUE THREAD

**Issue by oneMatti** [vuetifyjs/vuetify#14386]
### Environment
**Vuetify Version:** 2.5.12
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
1. Open the Reproduction link
2. Take a Heap Snapshot with your Browsers Dev Tools (choose cdpn.io: index.html as JS VM Instance)
3. Click a few times on the "Toggle Calendar" Button to destroy and remount the v-calendar components
4. Take a second Heap Snapshot. You should see a lot more reserved memory and a lot of detached elements that can not be removed by the garbage collector
5. This behavior exists only with type "day" or "day4". if you change the v-calendar type to "week" or "month" you will have no problems.

### Expected Behavior
v-calendar with type "day" or "day4" can be unmounted without leaking memory

### Actual Behavior
v-calendar with type "day" or "day4" leaking memory after being unmounted

### Reproduction Link
<a href="https://codepen.io/onematti/pen/rNzJgyp" target="_blank">https://codepen.io/onematti/pen/rNzJgyp</a>

**Comment by KaelWD** [comment]
This has the same cause as #13701, v-resize is being bound twice to the same element:

https://github.com/vuetifyjs/vuetify/blob/15e28f6e701de260fbc7acf3ae1bb9cfb4e4d7e3/packages/vuetify/src/components/VCalendar/VCalendarDaily.ts#L251
https://github.com/vuetifyjs/vuetify/blob/1a12f12cbe3cc0f3d00ff2c0460115641b33bd3a/packages/vuetify/src/components/VCalendar/VCalendar.ts#L366

**Comment by JorisAerts** [comment]
I had to revert Vuetify to 2.6.12 because this change seems to introduce an "undefined observer" in our Storybook
![image](https://user-images.githubusercontent.com/3611758/140769988-6c5ddb46-f8b9-4e0a-bb5a-23158ec5c641.png)
