### ISSUE TITLE
[Bug Report][2.5.11] v-menu not closed when parent component has a blocking v-if on created

### ISSUE THREAD

**Issue by bufferUnderrun** [vuetifyjs/vuetify#14380]
### Environment
**Vuetify Version:** 2.5.11
**Last working version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Firefox 93.0
**OS:** Windows 10

### Steps to reproduce
1. Click "open dialog button"
2. Click "dropdown button" and "do stuff list item"

### Expected Behavior
the v-menu must close (it works in 2.5.10)

### Actual Behavior
the v-menu is not close and stay open (regression in 2.5.11)

### Reproduction Link
<a href="https://codepen.io/cp10/pen/MWvQeox" target="_blank">https://codepen.io/cp10/pen/MWvQeox</a>

### Other comments
it seems the problem is the `v-if="dialog_open"` on the card which is used to avoid console error before data are available.

**Comment by gregveres** [comment]
I see that Kael added VDialog tag. I came here looking to see if it was known that dialogs are not working in this version and apparently it is known. 
Unfortunately, I was desparately waiting for the fix for Calendar...

**Comment by gregveres** [comment]
Here is a code pen that shows a simpler situation where the v-if is on the v-dialog.
When closing the v-dialog, it stays open. 
I am printing out the state of showDialog and it is clearly false when you hit the close button, but the dialog stays open.

https://codepen.io/gregveres/pen/rNzJGmd?editors=1111

**Comment by bufferUnderrun** [comment]
> I use the same v-if="showDialog" on my VDialog classes to avoid the same issue of errors before data is available and those 

@gregveres i first doing this but not working as you describe. Then i set the v-if inside a child component of v-dialog and it works.

**Comment by bufferUnderrun** [comment]
@KaelWD thanks for patch and release !!

**Comment by gregveres** [comment]
@KaelWD Thank you very much!!!
