### ISSUE TITLE
[Bug Report][2.5.13] Cannot read properties of undefined (reading 'observer')

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#14390]
### Environment
**Vuetify Version:** 2.5.13
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.69
**OS:** Mac OS 10.15.7

### Steps to reproduce
click on the select and then on the text of the first item.

### Expected Behavior
No error thrown

### Actual Behavior
Error thrown

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/MWvGQGp" target="_blank">https://codepen.io/everhardt/pen/MWvGQGp</a>

### Other comments
I think this used to work before https://github.com/vuetifyjs/vuetify/commit/64c254fce2af2d6059d107f6ace8d8320ba44382#diff-2fbb1269b11c901a265192e6afc9028e66c46b66463ccba78f3eebe2c5adc673

**Comment by cschweda** [comment]
I'm seeing this, too. Temp fix for me is converting to IMG tags where possible -- ditching v-img.

The error appears when you navigate away from a page with a v-img.

**Comment by Jecosine** [comment]
I ran into this probem too. It appears when i navigate away via a v-list-item with nuxt router like this:
```vue
<template v-for="(item, i) in menus">
  <v-list-item
    :key="`menu-item-${i}`"
    :class="['menu-item', `animation-delay-${i}`]"
    nuxt
    :to="item.link"
  >
    <v-list-item-avatar :color="item.color">
      <v-icon v-text="item.icon"></v-icon>
    </v-list-item-avatar>
    <v-list-item-content>
      <v-list-item-title
        class="item-title"
        v-text="item.name"
      ></v-list-item-title>
    </v-list-item-content>
  </v-list-item>
</template>
```

i was using 
- vuetify: 2.5.13
- nuxt: 2.15.8
----
Tempory work around for me: back to 2.5.x (x < 13)

**Comment by RomanovX** [comment]
Can confirm! We spent a few hours trying to figure out the issue but have also resolved this. Fixing the vuetify version to 2.5.12 or below has worked to fix the issue.

**Comment by Saudi30** [comment]
We have the same issues. 
The error occurs on below conditions.

- vuetify: 2.1.12
- Vue: 2.6.10

As same issues as @cschweda 's,  the error appears when you navigate away from a page with a v-img.
