### ISSUE TITLE
[Bug Report][2.5.13] Label moves from right to left when VTextField with outlined is displayed

### ISSUE THREAD

**Issue by YGNO** [vuetifyjs/vuetify#14391]
### Environment
**Vuetify Version:** 2.5.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.69
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Place the v-text-field of the following properties vertically.
    * outlined: true
    * has prepend-inner slot
    * has value
    * has label
1. Scroll the screen to display the v-text-field.
1. Label moves from right to left when v-text-field is displayed.

### Expected Behavior
Label does not move when v-text-field is displayed on screen.

### Actual Behavior
Label moves from right to left when the v-text-field is displayed on the screen.

### Reproduction Link
<a href="https://codepen.io/ygno/pen/bGrMJXz?editors=1010" target="_blank">https://codepen.io/ygno/pen/bGrMJXz?editors=1010</a>

**Comment by KaelWD** [comment]
Caused by #11816
