### ISSUE TITLE
[Feature Request] Format v-data-table/iterator pagination numbers

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#14405]
### Problem to solve
When v-data-table/iterators have a large number of items, the pagination bits are not formatted. Vuetify v1 used to do this.

![image](https://user-images.githubusercontent.com/1400380/142034743-41f47959-854c-4c32-b69a-caf19e9f1068.png)

### Proposed solution
Format the footer numbers

**Comment by KaelWD** [comment]
Old implementation: https://github.com/vuetifyjs/vuetify/blob/a0ebde164bc0fa30101a4824e2a1930772e3c4b4/packages/vuetify/src/mixins/data-iterable.js#L469

You can use the `page-text` scoped slot to override this. 

@nekosaur Any idea why that was removed in #5737
