### ISSUE TITLE
[Bug Report][2.5.14] v-edit-dialog combined with v-autocomplete doesnt work correctly

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#14400]
### Environment
**Vuetify Version:** 2.5.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
The 'dessert' column has an edit dialog
- Click on it to edit the tags
- play a bit with the autocomplete on the edit dialog saving and editing again a couple of times

### Expected Behavior
The correct options are selected and saved every time

### Actual Behavior
Some options are saved and others dont

### Reproduction Link
<a href="https://codepen.io/mrodal/pen/abyajbJ?editors=101" target="_blank">https://codepen.io/mrodal/pen/abyajbJ?editors=101</a>

**Comment by KaelWD** [comment]
Works for me

**Comment by mrodal** [comment]
Hi, please try hitting enter to save. I just tried clicking outside the edit dialog and it works, but it doesnt fire the save event

**Comment by KaelWD** [comment]
Are you clicking on an item then pressing enter? It's still focused after the click so pressing enter will deselect it.

**Comment by mrodal** [comment]
I could swear that I had tried unfocusing the items and it still didnt work.. but looks like I didnt 😅
Thanks for your time!

**Comment by mrodal** [comment]
Sorry, but do you have some suggestion on how to improve UX on this? as you can see the behaviour is weird..
Entering a value and pressing enter is what comes naturally.. having to click the little arrow on the select to close it and then pressing enter is counterintuitive

Another thing that feels weird is that if you open the select, and press enter, it unselects the first option because the first options is focused by default..

In my opinion this behaviour should only happen when the user uses the arrows to select options and not when using the mouse

**Comment by zwingpoint** [comment]
I have the same error. As a workaround, I do not use v-editor-dialog. I use v-dialog instead... Not nice

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
