### ISSUE TITLE
[Feature Request] vuetify 3  support Internationalization (i18n) but can't use createVueI18nAdapter 

### ISSUE THREAD

**Issue by xxxlrlovegd** [vuetifyjs/vuetify#14408]
### Problem to solve
Codeblock:
import { createVueI18nAdapter } from 'vuetify/locale/adapters'
import { useI18n } from 'vue-i18n';
import { i18n } from '@/locales/setupI18n';
export default createVuetify(
  {
    locale: createVueI18nAdapter(i18n, useI18n) ,
  }
)

### Proposed solution
I want to know when i can use createVueI18nAdapter，Looking forward to reply

**Comment by KaelWD** [comment]
#13336

> adapter helpers for vue-i18n and vue-intl are not included here since it would mean we'd need to depend on those packages. they should probably be separate npm packages that can be imported and used

@nekosaur are there still plans for this? Those packages can be optional peer dependencies.

**Comment by Ary428** [comment]
Hi!

When importing the `createVueI18nAdapter` from vuetify I'm getting this error:

```
Could not find a declaration file for module 'vuetify/lib/locale/adapters/vue-i18n.mjs'. 
'.../node_modules/vuetify/lib/locale/adapters/vue-i18n.mjs' implicitly has an 'any' type.
If the 'vuetify' package actually exposes this module,
try adding a new declaration (.d.ts) file containing `declare module 'vuetify/lib/locale/adapters/vue-i18n.mjs';`
```

**Comment by sueszli** [comment]
Hi! I also have a similar problem:

although the adapter exists, my VSCode IDE does not recognice the module via `import { createVueI18nAdapter } from 'vuetify/locale/adapters/vue-i18n'`.
