### ISSUE TITLE
[Feature Request] Error in method scrollIntoView

### ISSUE THREAD

**Issue by ksusha-gorskaya** [vuetifyjs/vuetify#14415]
### Problem to solve
Printed error, when 'wrapper' is undefined
Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at VueComponent.scrollIntoView (VSlideGroup.ts?151f:351)
    at eval (VSlideGroup.ts?151f:439)

### Proposed solution
Need to add 'wrapper' check in method scrollIntoView() on undefined.

**Comment by KaelWD** [comment]
This is not a valid feature request. If you are trying to submit a bug report please use the bug report template and supply a valid reproduction link with more details about the bug.  

For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
