### ISSUE TITLE
Navigation Drawer Issue

### ISSUE THREAD

**Issue by waqasraz** [vuetifyjs/vuetify#1441]
### Steps to reproduce
https://codepen.io/waqasraz/full/MvOoVR
1. Chrome mobile view or just normal view.
2. Scroll down
3. open the drawer

### Versions

2.4.2 , 0.14.11, Linux, Chrome
### What is expected?

Navigation drawer to opens normally.

### What is actually happening?

The navigation drawer moves up with the page. 

### Reproduction Link

https://codepen.io/waqasraz/full/MvOoVR

**Comment by johnleider** [comment]
I need to update that example. https://codepen.io/johnjleider/pen/prVjpw

It uses the **absolute** prop for the purpose of displaying in the documentation.
