### ISSUE TITLE
[Bug Report][2.6.0] v-datatable - previous itemsPerPage value is used when updating page and itemsPerPage at the same time

### ISSUE THREAD

**Issue by PavolHlavaty** [vuetifyjs/vuetify#14414]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.10
**Browsers:** Firefox 94.0
**OS:** Windows 10

### Steps to reproduce
only click the button in reproduction link

### Expected Behavior
itemsPerPage will be changed to 5 and at the same time page will be set to last. 

### Actual Behavior
itemsPerPage is changed to 5 but page is lowered to highest page based on previous value of itemsPerPage

### Reproduction Link
<a href="https://codepen.io/paul234/pen/WNEyqvr" target="_blank">https://codepen.io/paul234/pen/WNEyqvr</a>

**Comment by Al-0** [comment]
Hi, i will submit a fix for this!
