### ISSUE TITLE
[Bug Report][2.6.0] Development bug on autocomplete v-menu

### ISSUE THREAD

**Issue by asterd** [vuetifyjs/vuetify#14417]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 96.0.4664.55
**OS:** Mac OS 10.15.7

### Steps to reproduce
I can't reproduce the problem on codepen.
The behavior is that, if in autocomplete I select (only in development mode) an item that in not in list and press "enter" I get "cannot read properties of undefined (reading 'click') on VMenu.ts -> changeListIndex. 
I see in code that (IMHO) there is a control that lacks on this line:
(e.keyCode === keyCodes.enter && this.listIndex !== -1) {
        this.tiles[this.listIndex].click()
...
Maybe is better to check that this.tiles[this.listIndex] is not null or undefined.. 
This issue is not present in production build

### Expected Behavior
I expect not to have error

### Actual Behavior
It crashes in dev

### Reproduction Link
<a href="https://codepen.io/asterd/pen/mdMozxN?editors=1111" target="_blank">https://codepen.io/asterd/pen/mdMozxN?editors=1111</a>

**Comment by KaelWD** [comment]
How are you selecting an item that does not exist?

**Comment by asterd** [comment]
Yep..since is an autocomplete, the user can start typing and press enter even if what it search doesn't exist..

**Comment by jacekkarczmarczyk** [comment]
That's what `v-combobox` is for

**Comment by KaelWD** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
