### ISSUE TITLE
[Bug Report][2.5.11] VAutocomplete: Error in callback for watcher "filteredItems" after fix #14196

### ISSUE THREAD

**Issue by ArturWesner** [vuetifyjs/vuetify#14411]
### Environment
**Vuetify Version:** 2.5.11
**Last working version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Create a Component which extends VAutocomplete and import it
2. v-model, items are the required props. clearable for easier reproduction
3. Select a item from the dropdown menu and then clear the input
4. Errors are thrown because $refs is empty in the onFilteredItemsChanged() callback method

### Expected Behavior
No errors thrown

### Actual Behavior
$refs is called, but it is empty and then errors are thrown

### Reproduction Link
<a href="https://codesandbox.io/s/extended-autocomplete-error-g4l9e?file=/src/components/OwnAuto.vue" target="_blank">https://codesandbox.io/s/extended-autocomplete-error-g4l9e?file=/src/components/OwnAuto.vue</a>

### Other comments
The codesandbox takes quite some time to load, idk why..

Printed errors: 

> TypeError: Cannot read properties of undefined (reading 'listIndex')
>     at VueComponent.onFilteredItemsChanged (https://g4l9e.csb.app/node_modules/vuetify/lib/components/VAutocomplete/VAutocomplete.js:168:56)
> 
>     at invokeWithErrorHandling (https://g4l9e.csb.app/node_modules/vue/dist/vue.common.dev.js:1868:26)
> 
>     at Watcher.run (https://g4l9e.csb.app/node_modules/vue/dist/vue.common.dev.js:4579:9)
> 
>     at flushSchedulerQueue (https://g4l9e.csb.app/node_modules/vue/dist/vue.common.dev.js:4323:13)
> 
>     at Array.eval (https://g4l9e.csb.app/node_modules/vue/dist/vue.common.dev.js:1994:12)
> 
>     at flushCallbacks (https://g4l9e.csb.app/node_modules/vue/dist/vue.common.dev.js:1920:14)

    
And 

> [Vue warn]: Error in callback for watcher "filteredItems": "TypeError: Cannot read properties of undefined (reading 'listIndex')"
> 
> 
> found in
> 
> 
> ---> <OwnAuto> at /src/components/OwnAuto.vue
> 
>        <Playground> at /src/components/Playground.vue
> 
>          <VMain>
> 
>            <VApp>
> 
>              <App> at /src/App.vue
> 
>                <Root>

**Comment by ricardo17coelho** [comment]
I get the same error with 'listIndex'

![image](https://user-images.githubusercontent.com/37732431/142836031-ef40cfb1-74b6-4088-8cee-bb81965be8c1.png)

**Comment by KaelWD** [comment]
> Component which extends VAutocomplete

You're doing this wrong, extending the component then completely overriding its render function. Either extend it or render it with `$props`/`$listeners`, don't do both.

**Comment by ricardo17coelho** [comment]
Hi @KaelWD 
Thank you for your answer.
i don't understand what did u mean exactly..

**Comment by ArturWesner** [comment]
@ricardo17coelho In my provided codesandbox i used an component which extended VAutocomplete but also has overridden the render function by adding a template and wrapping the autocomplete component. In my case this was the reason the error occurred in the callback for the watcher "filteredItems".
I removed the extension and fixed my wrapper. The error seems to be gone now. I don't know under which circumstances the error appears in your project? If it is not the same case please describe it more detail and maybe add an codepen/codesandbox.

**Comment by KaelWD** [comment]
If you got it from https://stackoverflow.com/a/61486095/2074736, please see my comment for the correct way to do it.

**Comment by ricardo17coelho** [comment]
Hi @ArturWesner 
Thank you.

I'm also using a component that extends V-Autocomplete.

```
<template>
    <v-autocomplete v-on="$listeners" v-bind="computedProps">
        <!-- Dynamically inherit slots from parent -->
        <template v-for="(slot, name) in $scopedSlots" v-slot:[name]="item">
            <slot :name="name" v-bind="item"></slot>
        </template>
        <!-- make all slots from v-autocomplete reusable from parent -->
        <template v-for="(_, slot) in $slots">
            <template :slot="slot">
                <slot :name="slot"></slot>
            </template>
        </template>
    </v-autocomplete>
</template>
<script>
import { VAutocomplete } from "vuetify/lib";
export default VAutocomplete.extend({
    name: "BaseAutocomplete",
    props: {
        required: {
            type: Boolean,
            default: false
        }
    },
    computed: {
        computedProps() {
            return {
                ...this.$props,
                ...this.$attrs,
                filled: true
            };
        }
    }
});
</script> 
```

**Comment by ricardo17coelho** [comment]
@KaelWD my sample code is like your sample [here](https://stackoverflow.com/questions/48310902/extending-vuetify-component/70064606#70064606) or i'm missing something ?

**Comment by KaelWD** [comment]
You still have `VAutocomplete.extend`. That entire script section should be removed, just add `filled` in the template.

**Comment by ricardo17coelho** [comment]
@KaelWD thx 🤦‍♂️

**Comment by KareemDa** [comment]
> You're doing this wrong, extending the component then completely overriding its render function. Either extend it or render it with `$props`/`$listeners`, don't do both.

@KaelWD 
you saved my day. **THANK YOU!**
