### ISSUE TITLE
[Bug Report][2.5.10] V-col breakpoint sizing is broken in Safari

### ISSUE THREAD

**Issue by MilenaMalysh** [vuetifyjs/vuetify#14424]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
1) Open reproduction link in Safari
2) Enter responsive design mode
3) Change the width of the screen to 960px

### Expected Behavior
According to the $vuetify.breakpoint.name printed inside the column it's a middle device, so the column should take 50% of the screen width (md="6")

### Actual Behavior
Instead, the column takes the full width of the screen
![image](https://user-images.githubusercontent.com/16187012/142879622-93653db8-74af-4c39-82bc-6ab832fb5027.png)

### Reproduction Link
<a href="https://jsfiddle.net/p5uzskxy/show" target="_blank">https://jsfiddle.net/p5uzskxy/show</a>

### Other comments
Everything works fine in Firefox and Chrome

**Comment by KaelWD** [comment]
![Screenshot_20211123_014156](https://user-images.githubusercontent.com/16421948/142880904-34f9a730-2eb8-47ca-a7d7-10b3efc9e7c3.png)

**Comment by KaelWD** [comment]
I still can't reproduce this.
