### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Bottom navigation buttons are grayscale

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14428]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.22
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
Check repro link.

### Expected Behavior
The button colour should not be gray, and should either match or contrast with the surface colour of the bottom navigation component.

### Actual Behavior
It's gray, with no contrast.

### Reproduction Link
<a href="https://codepen.io/glen-84/pen/MWvRJPP" target="_blank">https://codepen.io/glen-84/pen/MWvRJPP</a>

### Other comments
Even though the lowered opacity helps to an extent with lighter surface colours, grayscale doesn't seem ideal for this purpose.

### Workaround

Set the `$button-bottom-navigation-filter` Sass variable, or override the CSS.

### *Update*

There is also a `$button-bottom-navigation-opacity` set to `.64` by default. This affects the opacity of the button text as well. I'm not sure what its purpose is.

**Comment by johnleider** [comment]
From your reproduction, I don't quite understand what you are having an issue with.

**Comment by glen-84** [comment]
The bar is themed (a blue-ish colour [surface: "#181E2C"]), but the button is gray (from the grayscale filter), and its opacity is also set, affecting the opacity of the text.

- Why apply a grayscale filter, if that'd only be suitable for grayscale (white to black) themes?
- Why apply an opacity to the whole button, and not just its colour (unless it was in a disabled state, or similar)?

**Comment by johnleider** [comment]
I believe this is part of a bigger problem;  Many top level components overwriting internal styling for nested components. This is a less than ideal way to propagate changes.

I have a few ideas, one involving a single component to handle the baseline functionality for items used in  `v-bottom-navigation`, `v-navigation-drawer` with the **rail** prop, and `v-tab`.

**Comment by johnleider** [comment]
This state is no longer handled by grayscale.
