### ISSUE TITLE
[Bug Report][2.6.0] v-data-table header value issue for restricted property as "constructor" or "toString"

### ISSUE THREAD

**Issue by BOISSARD** [vuetifyjs/vuetify#14425]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Can't display a **restricted property** of an object as "constructor" or "toString".
In chrome we get the error explanation : 
Duplicate keys detected: 'constructor'. This may cause an update error.

### Expected Behavior
to get the correct information in the cell

### Actual Behavior
"undefined" in header and column's cells 

### Reproduction Link
<a href="https://codepen.io/Klimoun/pen/eYEamWw" target="_blank">https://codepen.io/Klimoun/pen/eYEamWw</a>

**Comment by KaelWD** [comment]
We check if you've defined a slot with `if (this.$scopedSlots[header.value])`. That can be changed to `hasOwnProperty` to fix the header, but you'll still see `function toString() { [native code] }` if the items do not have a toString property or a null prototype.

**Comment by BOISSARD** [comment]
Thank you for your quick reply.
Don't worry for the toString, it was just another exemple, I actually use only constructor.
Thanks for your work
