### ISSUE TITLE
Feature Request Popover Component

### ISSUE THREAD

**Issue by sebastianmacias** [vuetifyjs/vuetify#1442]
A popover component would be very helpful, it would work similar to the tooltips but with content inside you can interact with. 

Here is an example:

![Popover Example](http://i.imgur.com/v8egPE1.png)

  - What will it allow you to do that you can't do today?

This is an unique component, currently the closest is a dialog.

  - How will it make current work-arounds straightforward?

By not having to use a third party library that offers this component/functionality.

  - What potential bugs and edge cases does it help to avoid?

Any that could be introduced by including a third party library.

**Comment by sebastianmacias** [comment]
Here is a [bootstrap](https://v4-alpha.getbootstrap.com/components/popovers/#four-directions) example.

**Comment by johnleider** [comment]
Isn't this the same thing as a menu?

**Comment by smares** [comment]
https://codepen.io/anon/pen/prVmem

**Comment by johnleider** [comment]
Ty @smares I'll get that prop properly added to the docs.

**Comment by sebastianmacias** [comment]
With "close-on-content-click" I'm able to achieve the popover functionality.

An example on vuetifyjs.com of a menu being used for something else besides a nav/options list would be helpful for people having the same need.

Thanks!

**Comment by cengler** [comment]
Is there a way to make a button with a popover and a menu when you click?

Because a button with menu is a menu with an activator
And a PopOver is a Dialog with an activator

**Comment by fnoop** [comment]
Is there any way in Vuetify to add the little arrow that points to the 'source' item, ie. what you click to open the menu/popover as shown in the example screenshot above?  That's quite an important little UX detail.

**Comment by sebastianmacias** [comment]
@fnoop  Agreed. Similar how github does:

![Popover arrow](https://i.imgur.com/b3uaAIH.png)

**Comment by zend** [comment]
Bootstrap popover component is based on the popper.js library.
There is an offical guide to integrate popper.js to Vue apps, see [MENTIONS](https://github.com/FezVrasta/popper.js/blob/master/MENTIONS.md) for detail. I'm using vue-popperjs and it's great.

**Comment by fnoop** [comment]
Thanks for the suggestion @zend - there's also:
https://github.com/Akryum/v-tooltip

However these should be unecessary and don't work in quite the same way - as noted here the vuetify menu works well, it just needs a styling option to make it obvious as a popover.  Looks like this issue is being ignored, so I'll open a new one.
