### ISSUE TITLE
[Bug Report][2.6.0] Calendar type=category display error in dark mode

### ISSUE THREAD

**Issue by EnOane** [vuetifyjs/vuetify#14433]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
when switching to dark mode in category mode

### Expected Behavior
fine view

### Actual Behavior
bad view

### Reproduction Link
<a href="https://codepen.io/enoane/pen/abygPOP" target="_blank">https://codepen.io/enoane/pen/abygPOP</a>

**Comment by MisterMilk24** [comment]
I did encounter the same problem yesterday. I get the same display in 2.6.1.
