### ISSUE TITLE
[Bug Report][3.0.0-alpha.0] codeblock:

### ISSUE THREAD

**Issue by xxxlrlovegd** [vuetifyjs/vuetify#14432]
### Environment
**Vuetify Version:** 3.0.0-alpha.0
**Vue Version:** 3.0.0
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
codeblock:
    <v-menu offset-y>
        <template v-slot:activator="{ on, attrs }">
          <v-btn color="deep-purple text-white" icon v-bind="attrs" v-on="on"
            ><v-icon icon="mdi-translate" /> <v-icon icon="mdi-chevron-down"
          /></v-btn>
        </template>
        <v-list>
          <v-list-item
            link
            @click="changeLang('en')"
            :class="{ ListActive: langValue }"
          >
            <v-list-item-title>English</v-list-item-title>
          </v-list-item>
          <v-list-item
            link
            active-class="ListActive"
            @click="changeLang('zh')"
            :class="{ ListActive: !langValue }"
          >
            <v-list-item-title>简体中文</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>

### Expected Behavior
A drop-down list can pop up from the menu

### Actual Behavior
A drop-down list can‘t pop up from the menu

### Reproduction Link
<a href="https://codepen.io/xxxlgloverd/pen/qBXzqPj" target="_blank">https://codepen.io/xxxlgloverd/pen/qBXzqPj</a>

### Other comments
Looking forward to reply

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
