### ISSUE TITLE
[Bug Report][2.6.0] v-tooltip won't close on button disable inside v-textfield's append slot

### ISSUE THREAD

**Issue by mavyfaby** [vuetifyjs/vuetify#14442]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.69
**OS:** Linux x86_64

### Steps to reproduce
1. Create a v-textfield.
2. Add a v-tooltip inside v-textfield's append slot.
3. Insert a v-icon within a v-tooltip with a click event that disables itself.

### Expected Behavior
v-tooltip should close on button disable

### Actual Behavior
v-tooltip won't close on button disable

### Reproduction Link
<a href="https://codepen.io/mavyfaby/pen/vYeYBxX" target="_blank">https://codepen.io/mavyfaby/pen/vYeYBxX</a>

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/rNGNBpg?editors=1010

**Comment by mavyfaby** [comment]
Thanks!
