### ISSUE TITLE
[Documentation] Counter doesn't increment and length isn't enforced

### ISSUE THREAD

**Issue by lookfirst** [vuetifyjs/vuetify#1444]
### Steps to reproduce

1. Visit: https://vuetifyjs.com/components/data-tables
2. Scroll to example 5.
3. Click on a row desert name to edit it.
4. Type in text in the dialog.
5. Note that the text counter doesn't change as I type and that the max length (25) isn't enforced.

### Versions

Latest Chrome / Vuetify

### What is expected ?

I expect the counter to change as I type.

### What is actually happening ?

The counter isn't changing.

### Reproduction Link

https://vuetifyjs.com/components/data-tables

![image](https://user-images.githubusercontent.com/85355/29551284-3560110c-873c-11e7-8260-4bbe1059716b.png)

**Comment by nekosaur** [comment]
I've fixed it not updating character count as you type in dev docs. Enforcing 25 character limit (actually not allowing user to type any more) is something you as a developer will have to do.

**Comment by lookfirst** [comment]
Thanks!

For reference, this is the commit: https://github.com/vuetifyjs/docs/commit/ffcbecb0666a446ed2e65a2015ec719d304ca369
