### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Transition classes need to specify the transition property

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#14440]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.23
**Browsers:** Chrome 96.0.4664.45
**OS:** Linux x86_64

### Steps to reproduce
Open the dialog

### Expected Behavior
Smooth transition

### Reproduction Link
<a href="https://codepen.io/kaelwd/pen/poWzYzX?editors=1010" target="_blank">https://codepen.io/kaelwd/pen/poWzYzX?editors=1010</a>

**Comment by johnleider** [comment]
I feel like having a default class, something like `v-transition`, which adds the transition property, and we can avoid adding a default transition to every transition class / component that we have.
