### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Sass error caused by `VList.sass` and `VListItem.sass` both forwarding the same variables

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14446]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.21
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Follow the README.

**IMPORTANT:** This is `alpha.11` – if you switch to `3.0.0-next-20211105.0`, for example, this error goes away, but the `.cache/vuetify/styles.scss` file appears to include far too many of the Sass files (maybe all of them?) – is that another issue, or did I do something wrong?

### Expected Behavior
No errors, able to customise v-tooltip and other components' Sass variables.

### Actual Behavior
`SassError: This module was already loaded, so it can't be configured using "with".`

### Reproduction Link
<a href="https://github.com/glen-84/vuetify-loader-issue" target="_blank">https://github.com/glen-84/vuetify-loader-issue</a>

**Comment by funkyvisions** [comment]
@glen-84 can you explain the comment about manual imports? Is that a work-around for now?

**Comment by glen-84** [comment]
@funkyvisions,

Ya, pretty much. I was doing something like this:

```scss
// Vuetify.
// TODO: Using manual imports because of:
// - https://github.com/vuetifyjs/vuetify-loader/issues/221.
// - https://github.com/vuetifyjs/vuetify/issues/14407.
@forward "vuetify/lib/styles/main.sass" with
(
    $body-font-family: $body-font-family,
    $container-max-widths: ("sm": 584px, "md": 648px, "lg": 912px, "xl": 1020px, "xxl": 1020px),
    // See also client/src/app/core/plugins/vuetify.ts.
    $grid-breakpoints:
        ("xs": 0, "sm": 600px, "md": 768px, "lg": 1024px, "xl": 1440px, "xxl": 1600px),
    $typography: (
        "body-3": (
            // 12px.
            "size": 0.75rem,
            "weight": 400,
            "line-height": 1rem,
            "letter-spacing": 0.033em,
            "font-family": $body-font-family,
            "text-transform": none
        ),
        "button": (
            "text-transform": none
        )
    )
);
@forward "vuetify/lib/components/VApp/VApp.sass";
@forward "vuetify/lib/components/VAppBar/VAppBar.sass";
@forward "vuetify/lib/components/VAppBar/VAppBarTitle.sass";
@forward "vuetify/lib/components/VAvatar/VAvatar.sass";
@forward "vuetify/lib/components/VBottomNavigation/VBottomNavigation.sass";
@forward "vuetify/lib/components/VBtn/VBtn.sass" with (
    // TODO: https://github.com/vuetifyjs/vuetify/issues/14428.
    $button-bottom-navigation-filter: unset,
    $button-bottom-navigation-opacity:  unset
);

// etc.
```

Not ideal, but there were no other options.

**Comment by KaelWD** [comment]
The weird thing is it's kinda inconsistent. Tabs forward their variables file twice as well but both tabs and lists work fine until I modify variables from **both** of them. 

works:
```html
<v-tabs><v-tab>Tab</v-tab></v-tabs>
<v-list><v-list-item>List</v-list-item></v-list>
```

works:
```html
<v-tabs><v-tab>Tab</v-tab></v-tabs>
<v-list><v-list-item>List</v-list-item></v-list>

$tabs-height: 56px
```

works:
```html
<v-tabs><v-tab>Tab</v-tab></v-tabs>
<v-list><v-list-item>List</v-list-item></v-list>

$list-indent-size: 12px
```

error:
```html
<v-tabs><v-tab>Tab</v-tab></v-tabs>
<v-list><v-list-item>List</v-list-item></v-list>

$tabs-height: 56px,
$list-indent-size: 12px,
```
