### ISSUE TITLE
[Feature Request] Mobile version of data table with horizontal scrolling

### ISSUE THREAD

**Issue by tubuanha** [vuetifyjs/vuetify#14441]
### Problem to solve
When a table with many columns is displayed on mobile, the page becomes too long vertically.

### Proposed solution
Add an option to the data table to allow the mobile version to scroll horizontally.

**Comment by mavyfaby** [comment]
Set the mobile breakpoint to 0:

```html
<v-data-table :mobile-breakpoint="0"></v-data-table>
```

**Comment by tubuanha** [comment]
> Set the mobile breakpoint to 0 to enable horizontal scroll on smaller screens:
> 
> ```html
> <v-data-table :mobile-breakpoint="0"></v-data-table>
> ```

I solved the problem this way.
Thank you very much!
