### ISSUE TITLE
Dialogs do not stack properly

### ISSUE THREAD

**Issue by toast38coza** [vuetifyjs/vuetify#1445]
Opening a dialog inside a fullscreen dialog results in the new dialog being behind the first one

You can resolve this manually by editing the z-index on `.dialog__content` to be higher than 5. However .. that can cause  further issues, if, for example you have a select inside your child container (z-index: 6)

### Steps to reproduce

Go to: https://codepen.io/anon/pen/zdjzRj

1. Click open fullscreen dialog 
2. Click open child dialog 

### Versions

This seems to effect all version as far as i can tell 

### What is expected ?

The child dialog should open stacked on top of the parent dialog 

### What is actually happening ?

Nothing. No child dialog is visible 

### Reproduction Link

https://codepen.io/anon/pen/zdjzRj

**Comment by wernerm** [comment]
The dialogs will probably stack according to the order in which they appear in the markup, so your problem should be solved if you put the markup of the child dialog above that of the parent (full-screen) dialog.

**Comment by johnleider** [comment]
@wernerm Is correct
