### ISSUE TITLE
[Bug Report][3.0.0-beta.1] vmenu nudge-* not being applied

### ISSUE THREAD

**Issue by ken-playerlync** [vuetifyjs/vuetify#14451]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.20
**Browsers:** Firefox 94.0, Microsoft Edge, Google Chrome
**OS:** Mac OS 10.15

### Steps to reproduce
- go to the link
- click on the icon toward the right of `Org Name` text
### Observe:
The menu appears cutoff, however a `:nudge-left` prop is added to it to avoid this, but the prop is not applied to the component. 

### Expected Behavior
That `:nudge-left` prop is applied

### Actual Behavior
`:nudge-left` is not applied, amongst possible other props. 

### Reproduction Link
<a href="https://codepen.io/og-neth/pen/KKXwwVV" target="_blank">https://codepen.io/og-neth/pen/KKXwwVV</a>

**Comment by nickvdwaal** [comment]
What exactly is nudge-left, cant seem to find anything? I did some digging, looks like it has to do with positionStrategies from VOverlay not acting properly to anchor and origin. However, I don't know if it is related to the same issue

**Comment by KaelWD** [comment]
The codepen has been deleted so I don't know exactly what you were doing, but the automatic positioning is much more flexible now so you shouldn't need to adjust it.

`nudge` has also been replaced with `offset="main cross"` where `main` is a distance away from the activator side and `cross` is along it.

**Comment by yacinehmito** [comment]
I think the Upgrade guide should mention something about the lack of "nudge". I am looking everywhere what to replace them with and I am finding no information.

**Comment by KaelWD** [comment]
done

**Comment by yacinehmito** [comment]
Great! Thank you very much.
