### ISSUE TITLE
[Bug Report][2.6.1] Tabs with nuxt child with props exact doesn't move the slider

### ISSUE THREAD

**Issue by sMesle** [vuetifyjs/vuetify#14459]
### Environment
**Vuetify Version:** 2.6.1
**Last working version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Firefox 94.0
**OS:** Mac OS 10.15

### Steps to reproduce
- Create a v-tabs containing multiple v-tab element using the nuxt and exact props
- Define a to path to corresponding child pages
- Use NuxtChild component after the v-tabs component

### Expected Behavior
The slider must move to the other v-tab

### Actual Behavior
The slider stay on the second tab

### Reproduction Link
<a href="https://codesandbox.io/s/demo-tabs-nuxt-chidl-forked-vu2cj?file=/pages/dashboard/parent.vue" target="_blank">https://codesandbox.io/s/demo-tabs-nuxt-chidl-forked-vu2cj?file=/pages/dashboard/parent.vue</a>

### Other comments
This worked perfectly in 2.5.9 version.

By replacing exact by exact-path on the first tab, it's working

**Comment by sMesle** [comment]
Similar to https://github.com/vuetifyjs/vuetify/issues/14431

**Comment by 4KDA** [comment]
The same problem.

**Comment by Florent-Bouisset** [comment]
Hello I face the same problem after updating vuetify from 2.5.6 to 2.6.1:

```
    <v-tabs>
      <v-tab to="/foo" exact>foo</v-tab>
      <v-tab to="/bar" >bar</v-tab>
      <v-tab to="/baz">baz</v-tab>
    </v-tabs>
```

When the v-tab has the property "exact" the slider doesn't move (but the text change of color correctly)

![image](https://user-images.githubusercontent.com/58945185/145677626-37ab91d9-d03a-47c4-ba4c-fc525dab07a3.png)
