### ISSUE TITLE
[Bug Report][2.6.1] v-textarea solo-onverted dark mood no text showing

### ISSUE THREAD

**Issue by udayan-santu** [vuetifyjs/vuetify#14467]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 3.2.24
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
try to input text in textarea. this is in dark theme and solo inverted. you cannot see the text.

### Expected Behavior
textfeield and text-area should work same in solo inverted. it also causes error in light theme too.

### Actual Behavior
please solve the issue

### Reproduction Link
<a href="https://codepen.io/udayan-basak/pen/xxXZyjW?editors=1010" target="_blank">https://codepen.io/udayan-basak/pen/xxXZyjW?editors=1010</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
