### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] `v-tooltip` throws error on hover, not connected to template.

### ISSUE THREAD

**Issue by pgoy-dod** [vuetifyjs/vuetify#14466]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.24
**Browsers:** Chrome 96.0.4664.55
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Visit https://codepen.io/pgoy-ih/pen/dyVGgdq or  https://next.vuetifyjs.com/en/components/tooltips/#examples (the error shown in the examples is what i am experiencing with my own code).
2. Open the console.
3. Interact with the presented examples.
4. Observe the tooltip always appears in the top left corner of the viewport, and "TypeError: ResizeObserver.observe: Argument 1 is not an object" errors populate your console.

### Expected Behavior
`v-tooltip` puts a tooltip on the wrapped component, appearing nearby without errors.

### Actual Behavior
The tooltip appears in the top-left corner of the viewport, unattached from the wrapped component. "TypeError: ResizeObserver.observe: Argument 1 is not an object" errors appear in the console.

### Reproduction Link
<a href="https://codepen.io/pgoy-ih/pen/dyVGgdq" target="_blank">https://codepen.io/pgoy-ih/pen/dyVGgdq</a>

### Other comments
Given that this error is present on the documentation (https://next.vuetifyjs.com/en/components/tooltips/#examples), i have a feeling you might all know about it. I didn't see an issue listed, though, so i thought i'd toss one in!

**Comment by brunopiaui** [comment]
Hi, I have the same problem...

**Comment by PashaTurok** [comment]
I am testing "vuetify": "npm:@vuetify/nightly@next" and found out that tooltips are always shown on the right. I mean that top, bottom, left positions are ignored. So, I suggest to reopen this issue.

**Comment by KaelWD** [comment]
@PashaTurok https://next.vuetifyjs.com/en/components/overlays/#connected

**Comment by PashaTurok** [comment]
@KaelWD Thank you very much!
