### ISSUE TITLE
[Feature Request] use some components

### ISSUE THREAD

**Issue by pedy4000** [vuetifyjs/vuetify#14461]
### Problem to solve
Hey
how can I use some components of vuetify instead of installing or importing all components in nuxt?

### Proposed solution
nothin

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/treeshaking/

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
