### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] VListGroup header prependIcon inherited

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#14472]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.24
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
1. Open Codepen
2. notice the `long-term-support` item is using its parent's **prependIcon**
3. Uncomment **prependIcon** in the array and it works fine.

### Expected Behavior
If prependIcon is not used, should infer false

### Actual Behavior
Nested group headers inherit parent

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/rNGeKMe" target="_blank">https://codepen.io/johnjleider/pen/rNGeKMe</a>

**Comment by KaelWD** [comment]
#14479
