### ISSUE TITLE
Checkbox and radio label too wide

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1447]
### Steps to reproduce
Place a checkbox or radio with a label that is wider than the parent and notice how the label bleeds into the padding of the surrounding container. Maybe related to #1430 

### Versions
Vue 2.4.2, Vuetify 0.14.11, Edge 15

### What is expected ?
Label should show ellipsis within the container

### What is actually happening ?
Label bleeds into the padding of the surrounding container

### Reproduction Link
https://codepen.io/anon/pen/mMLYpx

**Comment by nekosaur** [comment]
Should be fixed by #1459
