### ISSUE TITLE
[Bug Report][2.6.1] v-select with prepended/appended items highlights incorrect item

### ISSUE THREAD

**Issue by oohira** [vuetifyjs/vuetify#14489]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.69
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open v-select menu items
1. Click 4th item
1. 2nd item is highlighted

### Expected Behavior
4th item is highlighted

### Actual Behavior
2nd item is highlighted

### Reproduction Link
<a href="https://codepen.io/oohira/pen/poWEoqw" target="_blank">https://codepen.io/oohira/pen/poWEoqw</a>

### Other comments
Reproduction Link is same as the sample of Vuetify official document.

* https://vuetifyjs.com/en/components/selects/#append-and-prepend-item

**Comment by adil-portable** [comment]
@johnleider 
Hi, My name is Muhammad Adil Khan. I work for Portable, Australia and our goal is to contribute to open source projects on Github. My team and I would like to contribute to this project. Please let us know if we can work fix this issue and would like to work on other tickets as well.

I look forward to hearing from you soon.

Thanks,
Adil

**Comment by adil-portable** [comment]
@johnleider @KaelWD @nekosaur

Hi, I have created a pull request but unable to assign to anyone in your team. Could you please have a look to my PR?
We are from Portable, Australia and worked as a team on this ticket and would like to contribute on other tickets as well.
I look forward to hearing from you soon.

**Comment by adil-portable** [comment]
Before
![image](https://user-images.githubusercontent.com/94330648/145521675-bdd49539-e3ba-48ee-85a7-ef2aa6f5b112.png)
After
![image](https://user-images.githubusercontent.com/94330648/145521721-e3dc9dc2-85b7-422a-a40c-14011376ff30.png)

**Comment by arteymix** [comment]
Still present in 2.7.0. Is there a known workaround for this issue?

**Comment by jimmylee850328** [comment]
Still present in 2.7.1 when using <v-autocomplete> and <v-select>
**HELP ME!**

**Comment by jimmylee850328** [comment]
Still present in 2.7.1 when using `<v-autocomplete>` and `<v-select>`
**HELP ME!**

**Comment by jimmylee850328** [comment]
Sorry I want to ask why close the issues.
It still present in vuetify 2 when using `<v-autocomplete>` and `<v-select>`

**Comment by Dmitrii-Iakovenko** [comment]
hack:

```
<v-select
      ...
      ref="mySelect"
      @change="onSelectChange"
>
```

method:
```
    onSelectChange() {
      setTimeout(() => {
          const index = this.$refs.mySelect.$refs.menu.listIndex;
          this.$refs.mySelect.$refs.menu.listIndex = index + 2;
      }, 10);
    },
```

**Comment by truesteps** [comment]
@Dmitrii-Iakovenko thanks for the workaround, this seems to fix the highlight issue, but the scroll into view bug still persists. I opened a new issue for this here: https://github.com/vuetifyjs/vuetify/issues/19026
