### ISSUE TITLE
[Bug Report][2.6.1] v-autocomplete hide-delected prop is not working when item-value function is used

### ISSUE THREAD

**Issue by km2442** [vuetifyjs/vuetify#14487]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 96.0.4664.93
**OS:** Windows 10

### Steps to reproduce
When you choose at least one element through `v-autocomplete` with `hide-selected` prop when `item-value` prop is set to execute a custom function that return data, the `hide-selected` prop has no effect.

### Expected Behavior
`hide-selected` prop hides selected data

### Actual Behavior
`hide-selected` prop didn't hide selected data

### Reproduction Link
<a href="https://codepen.io/km2442/pen/VwMjBdN" target="_blank">https://codepen.io/km2442/pen/VwMjBdN</a>

**Comment by KaelWD** [comment]
Values returned from `item-value` are compared using strict equality (`===`). You're returning a new object on each call so they are never equal.

**Comment by km2442** [comment]
Thank you, so is there any option to hide it when `hide-selected` prop is used?
