### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-text-field icons not working

### ISSUE THREAD

**Issue by scramlo** [vuetifyjs/vuetify#14481]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.23
**Browsers:** Firefox 94.0
**OS:** Mac OS 10.15

### Steps to reproduce
Use any prepend / append props such as `prepend-icon` and there will be no icon. The only exception is `prepend-inner`

### Expected Behavior
All icon props documented in the `v-text-field` Vuetify docs should produce icons in the associated placement.

### Actual Behavior
There are no icons showing aside from when using the `prepend-inner` prop in `v-text-field`

### Reproduction Link
<a href="https://codepen.io/toltech/pen/OJxXXeb" target="_blank">https://codepen.io/toltech/pen/OJxXXeb</a>

**Comment by KaelWD** [comment]
Fixed by #14430

https://codepen.io/kaelwd/pen/RwLRebZ?editors=1010
