### ISSUE TITLE
[Bug Report][2.6.1] v-list-item isActive does not respect v-list-item-group value

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#14482]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
- set v-model to v-list-item-group
- set values to v-list-items
- make sure v-list-item-group v-model property cannot go back to undefined/falsy
- toggle selected v-list-item

### Expected Behavior
I would expect that, if I am using a v-list-item-group with a v-model, that the v-list-items under it would conform to whatever value is set against it.

### Actual Behavior
Child v-list-items can flip active state without regard for v-list-item-group v-model current value. 

### Reproduction Link
<a href="https://codepen.io/nolde/pen/jOGrLPY" target="_blank">https://codepen.io/nolde/pen/jOGrLPY</a>

### Comments:
Using `mandatory` does not help; although it stops the inactive state of the `v-list-item`s, it forces immediate `v-list-item-group` v-model value setting. Similar to a radio button group, I would expect `mandatory` to just make it unchangeable after the value has been actually set, not for the component to forcefully make a choice.

### Possible fix 1:
Make sure `v-list-item` active state abides by `v-list-item-group` v-model.

### Possible fix 2:
Stop `v-list-item-group`s `mandatory` prop from immediately forcing a value.

### Screenshots:
![vuetify-issue-00](https://user-images.githubusercontent.com/12801563/145340094-df63db5b-6be4-4f85-a4c2-bee15799d6b9.png)
![vuetify-issue-01](https://user-images.githubusercontent.com/12801563/145340140-d2bf4ad6-2316-4544-99bc-4e580fdfba37.png)

**Comment by KaelWD** [comment]
In v2 that's how every component works unfortunately, it always has internal state that is updated with watchers, so a computed setter like you have here will not affect the internal value. Instead you have to watch the model and set it back to the original value if it doesn't meet your condition: https://codepen.io/kaelwd/pen/GRMqyXE
This has been fixed in v3.

**Comment by nolde** [comment]
In my case, the value is coming straight from vuex, so it is a little more complicated, but I guess I can create a local copy to mimic what you've done on your example.

Thanks for the input, @KaelWD , appreciate it.
