### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-form + $refs. validate() method undefined

### ISSUE THREAD

**Issue by spy9teen** [vuetifyjs/vuetify#14485]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.0.0
**Browsers:** Chrome 96.0.4664.45
**OS:** Linux x86_64

### Steps to reproduce
example taken from vuetify documentation https://next.vuetifyjs.com/en/components/forms/#misc
Just open console and click validate. You'll see errors

### Expected Behavior
Make it work like in vuetify 2.6

### Actual Behavior
this.$refs.form (ref to template form) don't have  validate or resetValidation methods

### Reproduction Link
<a href="https://codepen.io/spy9teen/pen/yLzJjJj" target="_blank">https://codepen.io/spy9teen/pen/yLzJjJj</a>

**Comment by gustavorps** [comment]
Has this fix been released in the current version (3.0.0-alpha.12)?
