### ISSUE TITLE
How to sync datatable component with server side datatore?

### ISSUE THREAD

**Issue by wowcut** [vuetifyjs/vuetify#1448]
How to sync the [data table component](https://vuetifyjs.com/components/data-tables) with a server side data store? I could not find any hints about this. Thaks for your attention!

**Comment by nekosaur** [comment]
Please direct all questions to our chat at https://chat.vuetifyjs.com. Example 9 shows how to paginate and sort server side.

**Comment by wowcut** [comment]
Hmm, sorry, but I can not see anything that helps me with syncing server side code in [example 9](https://github.com/vuetifyjs/docs/blob/master/examples/tables/9.vue). 

The component docs examples number 8 "Paginate and sort server-side" 'edit' button links to [Example 6 Code](https://github.com/vuetifyjs/docs/blob/master/examples/tables/6.vue), however I can not see anything sync related neither in that nor in [example 8](https://github.com/vuetifyjs/docs/blob/master/examples/tables/8.vue) - what is a little bit irritating.

Also this is no support request, it is a feature request - from my world view a component library for table data always provides some way to actually sync that data with a server side data store - is this **not** the case with this library? I mean, of course you want to read and store the data in a synchronized way with multiple clients, not only show it, I guess?

I am generally missing that data sync feature in the vuejs world, but it seems especially important for a data table component. Maybe I am missing some major vuejs feature set, sorry for not being 100% sure about that.

**Comment by nekosaur** [comment]
First of all, if this was intended as a feature request, it was neither labelled as such (title is a question), nor did it use the template provided for feature requests. 

Second, I think you'd better articulate exactly what you mean by "sync data with a server side data store". Do you mean pushing data from server to client with any client request? Then you need to look at something like sockets.

**Comment by wowcut** [comment]
yes. no problem.
