### ISSUE TITLE
[Bug Report][2.6.1] v-dataTable in v-row "falling" out of the screen without vertical scroll appearing

### ISSUE THREAD

**Issue by SadPossum** [vuetifyjs/vuetify#14483]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Firefox 94.0, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Put v-dataTable in v-row 
2. Add too mutch columns or change screen size

### Expected Behavior
1. v-dataTable remains within the screen or parent container width
2. v-dataTable vertical scroll appear

### Actual Behavior
1. v-dataTable fall of the screen or parent container width
2. v-dataTable vertical scroll not appear

### Reproduction Link
<a href="https://codepen.io/sadpossum/pen/GRMqyBE?editors=1010" target="_blank">https://codepen.io/sadpossum/pen/GRMqyBE?editors=1010</a>

**Comment by KaelWD** [comment]
`v-row` should not be used without `v-col`
