### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Install but can't run

### ISSUE THREAD

**Issue by anfha1** [vuetifyjs/vuetify#14494]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.24
**Browsers:** Edge 96.0.1054.43, Google Chrome
**OS:** Windows

### Steps to reproduce
1. vue create center
2. cd center
3. vue add vuetify
4. npm run serve

### Expected Behavior
ValidationError: Progress Plugin Invalid Options

### Actual Behavior
run successfully

### Reproduction Link
<a href="https://codesandbox.io/s/elegant-tess-c7cvo?file=/readme.txt" target="_blank">https://codesandbox.io/s/elegant-tess-c7cvo?file=/readme.txt</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vue-cli-plugins/issues/302
