### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-text-field variant outlined notch issue

### ISSUE THREAD

**Issue by scramlo** [vuetifyjs/vuetify#14495]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.24
**Browsers:** Firefox 94.0
**OS:** Mac OS 10.15

### Steps to reproduce
Do not use `label` prop with `v-text-field`

### Expected Behavior
If not using `label` there should be no visible notch.

### Actual Behavior
The notch is always showing up.

### Reproduction Link
<a href="https://codepen.io/toltech/pen/OJxXXeb" target="_blank">https://codepen.io/toltech/pen/OJxXXeb</a>

**Comment by scramlo** [comment]
I shimmed this in my project by using a dynamic class dependent on a label prop. 

```
 .input--no-label {
    :deep(.v-field__outline__notch::before) {
      border: 1 solid currentColor;
      opacity: var(--v-field-border-opacity);
    }
  }
```

**Comment by yuwu9145** [comment]
@scramlo would you like making a pull request?

**Comment by scramlo** [comment]
Sure

**Comment by POSIO-IN9** [comment]
you are my angel
