### ISSUE TITLE
[Bug Report][2.5.3] Autocomplete wrong selection value when using filter

### ISSUE THREAD

**Issue by vanishdark** [vuetifyjs/vuetify#14503]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.14
**Browsers:** Opera 81.0.4196.61, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Write the search value in input (for example some).
- Select the value
- Check the input is different from the selected value

### Expected Behavior
The selected value displayed should be the value selected from the filtered list

### Actual Behavior
The selected value displayed is the item in index x of the array of items and not the array of filter items

### Reproduction Link
<a href="https://codepen.io/vanishdark/pen/XWeprKG" target="_blank">https://codepen.io/vanishdark/pen/XWeprKG</a>

**Comment by KaelWD** [comment]
> `v-on="data.on"`

These events are already automatically bound to the generated v-list-item, you only need to use this if you're supplying the entire item component. If you apply it to v-list-item-content as well the event will bubble up and trigger a second selection because the element is reused.

**Comment by vanishdark** [comment]
@KaelWD Thanks for the explanation. Although if I remove `v-on` from the v-list-item-content the behaviour still.

When I was debugging with two different autocomplete I notice if I do not use the `@click` in v-list-item-content the components work as expected.

**Comment by KaelWD** [comment]
Yep it's the same thing, if you set `propertyId` on v-list-item-content click then
 - the menu resets, so the first element is now the first item
 - the event bubbles to v-list-item and triggers its click handler too but with the new value

**Comment by vanishdark** [comment]
Yep, I get It now. 
Thanks for the help @KaelWD
