### ISSUE TITLE
[Bug Report][2.6.1] Deleting last character in v-combobox triggers an unexpected input event

### ISSUE THREAD

**Issue by olivierkrener** [vuetifyjs/vuetify#14507]
### Environment
**Vuetify Version:** 2.6.1
**Last working version:** 2.5.14
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
1) Select an item in the combobox
2) Delete the character one by one until there is only one left
3) Delete the last character

### Expected Behavior
Last character should be deleted as expected

### Actual Behavior
An unexpected input event is triggered, and the last character is written back
(Note that deleting it again does not trigger again this extra event)

### Reproduction Link
<a href="https://codepen.io/l1b3rty/pen/eYEBVQK" target="_blank">https://codepen.io/l1b3rty/pen/eYEBVQK</a>

### Other comments
Used to work properly until 2.5.14, just change the vuetify version to see it

**Comment by KaelWD** [comment]
Broken by #13854
