### ISSUE TITLE
[Bug Report][2.6.1] Can't drag and drop allDay events in month view

### ISSUE THREAD

**Issue by DanieleMar** [vuetifyjs/vuetify#14508]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.12
**Browsers:** Chrome 96.0.4664.93
**OS:** Linux x86_64

### Steps to reproduce
1- go to monthly or weekly view 
2- choose an event that lasts all day and drag it
3- the event sticks

### Expected Behavior
The daily event is moved to another day when you are in month view or in week view

### Actual Behavior
Only not-daily events can be dragged when you are in week and day view

### Reproduction Link
<a href="https://codepen.io/iessIsMore/pen/rNGjzpJ" target="_blank">https://codepen.io/iessIsMore/pen/rNGjzpJ</a>

**Comment by DanieleMar** [comment]
It's not really a bug. I don't know the way to do it

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
