### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Temporary Navigation Drawer Does Not Close When Clicking Outside It

### ISSUE THREAD

**Issue by turbobuilt** [vuetifyjs/vuetify#14505]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.25
**Browsers:** Chrome 96.0.4664.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
just put temporary on a nav drawer, and it opens on mobile just fine, but clicking outside won't close it, so the drawer is stuck open

### Expected Behavior
drawer should close when clicking outside

### Actual Behavior
drawer stays open indefinitely and also hides the top menu bar as well, so you can't close it with the menu button either.

### Reproduction Link
<a href="https://codepen.io/dbobby/pen/QWqdNax" target="_blank">https://codepen.io/dbobby/pen/QWqdNax</a>

**Comment by KaelWD** [comment]
Fixed by #14468
