### ISSUE TITLE
[Bug Report][2.6.1] VTooltip don't update position after update content

### ISSUE THREAD

**Issue by RuslanMelnychenko** [vuetifyjs/vuetify#14514]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.93
**OS:** Windows 10

### Steps to reproduce
1. Create `v-tooltip` component with any aligns
2. Update content to another

### Expected Behavior
Content position update

### Actual Behavior
Content position don't update

### Reproduction Link
<a href="https://codepen.io/ruslanmelnychenko/pen/yLzMYdY" target="_blank">https://codepen.io/ruslanmelnychenko/pen/yLzMYdY</a>

**Comment by KaelWD** [comment]
Duplicate of #9878
