### ISSUE TITLE
[Feature Request] v-simple-table

### ISSUE THREAD

**Issue by manimovassagh** [vuetifyjs/vuetify#14513]
### Problem to solve
I want to disable the Hover Effect and Default behavior of Vue simple Table.
i want to make each row highlited after click of user and keep the highlighted rows.

### Proposed solution
I just tried every options but it can not be disabled.
with this css
 tbody tr:hover { 
background-color: transparent !important; 
} 
it seems to be clear but after making custom classes this hover is still there .
Thanks if somebody have a soloution for that

**Comment by KaelWD** [comment]
Duplicate of #5787

**Comment by manimovassagh** [comment]
Thanks Kael,
Note that Number #5787 is for Data Table . Mein Issue was with Simple Table .
