### ISSUE TITLE
[Bug Report][2.6.1] Getting vue-click-outside error with v-select/v-autocomplete components

### ISSUE THREAD

**Issue by maksakoviliya** [vuetifyjs/vuetify#14515]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 96.0.4664.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
On focus/blur there are errors in console: [Vue-click-outside:] provided expression undefined is not a function. But there are not any methods/functions on @blur event. If add method on @blur event also there are errors.

### Expected Behavior
Closing v-select/v-autocomplete

### Actual Behavior
Don't closing component, errors in console

### Reproduction Link
<a href="https://codepen.io/km2442/pen/VwMjBdN" target="_blank">https://codepen.io/km2442/pen/VwMjBdN</a>

**Comment by maksakoviliya** [comment]
![image](https://user-images.githubusercontent.com/16371638/146185855-288d4fd4-713f-414c-8fe0-c4407c3b7fe0.png)

**Comment by maksakoviliya** [comment]
![image](https://user-images.githubusercontent.com/16371638/146185933-18eb85a9-ecc0-42eb-9d4a-4910fcb57d97.png)

**Comment by KaelWD** [comment]
That's coming from https://www.npmjs.com/package/vue-click-outside. Vuetify already had a click-outside directive, you don't need to install another one.

**Comment by maksakoviliya** [comment]
Thank you very much! It's worked))))
