### ISSUE TITLE
[Bug Report][2.6.1] When component is clicked and as a result disappears and another component moves to its place it is clicked as well but only "visually"

### ISSUE THREAD

**Issue by josefsabl** [vuetifyjs/vuetify#14516]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.93
**OS:** Windows 10

### Steps to reproduce
- In the filtered list, check the "Learn JavaScript" todo.

### Expected Behavior
- Learn JavaScript disappears
- Nothing else happens

### Actual Behavior
- Learn JavaScript disappears
- Learn Vue is checked (but only visually, the data is not changed)

### Reproduction Link
<a href="https://codepen.io/josefsabl/pen/ExwWZrZ" target="_blank">https://codepen.io/josefsabl/pen/ExwWZrZ</a>

### Other comments
Video demonstration of a bug: https://www.screenpresso.com/=R6AYd

**Comment by josefsabl** [comment]
I forgot to mention that this is true not only for v-check. I also reproduced same behavior when using v-switch

**Comment by KaelWD** [comment]
v-for requires a unique key: `<v-list-item :key="todo.text">`

**Comment by josefsabl** [comment]
Thank you very much for your prompt response.

Yes, I forgot that in the snippet. However it doesn't solve the problem and it behaves exactly the same when the key is there.

**Comment by KaelWD** [comment]
You're still missing it on the second v-for

**Comment by josefsabl** [comment]
OMG 🤣 . Thanks and sorry. I had the key in my real app so it got me confused, but the key was the actual bug as I didn't put unique id in there but just the index from the array.
