### ISSUE TITLE
[Bug Report][2.6.1] webview style error in dark theme

### ISSUE THREAD

**Issue by skadiD** [vuetifyjs/vuetify#14522]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 3.2.26
**Browsers:** Edge 96.0.1054.53
**OS:** Android, Windows 10

### Steps to reproduce
1.open in chrome
2.open in webview

### Expected Behavior
outlined style should be loaded correctly like running on chrome

### Actual Behavior
it doesn't work

### Reproduction Link
<a href="https://codepen.io/skadiD/pen/XWeRWNv" target="_blank">https://codepen.io/skadiD/pen/XWeRWNv</a>

### Other comments
pics in here
![webview](https://user-images.githubusercontent.com/50161715/146424705-b92a9bf4-a0d7-49af-aa78-19d4f51ad9a7.jpg)
![chrome](https://user-images.githubusercontent.com/50161715/146424685-06d0ba3a-4a47-4e60-b0c3-11f0be5a453e.jpg)
![webview info](https://user-images.githubusercontent.com/50161715/146424829-8afcecc1-7c04-4933-8775-c3d8e33c47b9.jpg)

**Comment by KaelWD** [comment]
I checked with https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en&gl=US and it looks fine.
![Screenshot_2021-12-17-05-10-42-414_com snc test webview2](https://user-images.githubusercontent.com/16421948/146425989-1eb755d2-250a-479f-98ee-4c6bdbb28ba4.png)

**Comment by skadiD** [comment]
> I checked with https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en&gl=US and it looks fine. ![Screenshot_2021-12-17-05-10-42-414_com snc test webview2](https://user-images.githubusercontent.com/16421948/146425989-1eb755d2-250a-479f-98ee-4c6bdbb28ba4.png)

im try to use

https://play.google.com/store/apps/details?id=mark.via.gp

https://play.google.com/store/apps/details?id=com.mi.globalbrowser

both of theme are wrong

**Comment by skadiD** [comment]
![Screenshot_2021-12-17-02-47-24-418_com snc test webview2](https://user-images.githubusercontent.com/50161715/146430695-015b59b7-9c74-435e-896d-5c3a069cf4fd.jpg)
on webview test app also wrong

**Comment by skadiD** [comment]
ok,i found the question is caused by Xiaomi os dark theme
