### ISSUE TITLE
[Bug Report][2.6.1] v-otp-input : copy/paste does not update the linked model value correctly

### ISSUE THREAD

**Issue by mathiasconradt** [vuetifyjs/vuetify#14536]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 96.0.4664.45
**OS:** Linux x86_64

### Steps to reproduce
Go to the codepen and instead of typing values into the 6 OTP input fields, **copy/paste**(!) a 6-digit-long number into the OTP field (put the cursor into the first OTP digit field, then paste with ctrl+v).
The linked model (`otpValue` in the example) output below the `v-otp-input` is not updated. The model only updates if you enter a number value into the OTP fields one-by-one. Copy/paste does not work. Interestingly copy/paste also does not trigger the "changed" event, but it does trigger the "complete" event.

### Expected Behavior
When copy/pasting values into the `v-otp-input`, the linked model  (`otpValue` in the example) should be updated accordingly.

### Actual Behavior
When copy/pasting values into the `v-otp-input`, the linked model (`otpValue` in the example) does not get updated.

### Reproduction Link
<a href="https://codepen.io/the0pe/pen/vYJoYJb" target="_blank">https://codepen.io/the0pe/pen/vYJoYJb</a>

### Other comments
This bug might look related to https://github.com/vuetifyjs/vuetify/issues/14437 but it's different and the other way around, also explicitly related to copy/pasting values into the `v-otp-input`.

**Comment by mathiasconradt** [comment]
By the way: I found that the value passed in the `@finish` method is correct, so this is what I now use as a workaround. 

```
@finish="onFinish"

[...]

onFinish(otp) {
  // the otp value in here is correct even when copy/pasted
  this.otpValue = otp
}
```

**Comment by enyoghasim** [comment]
Why is this closed?
The @finished is not working

**Comment by enyoghasim** [comment]
> I found that the value passed in the `@finish` method is correct, so this is what I now use as a workaround.
> 
> ```
> <v-otp-input
>   @finish="onFinish"
>   ...
> />
> 
> [...]
> 
> onFinish(otp) {
>   // the otp value in here is correct even when copy/pasted
>   this.otpValue = otp
> }
> ```

this is not working at the moment

**Comment by dhrumil-thakkar-pedalsup** [comment]
Try using @on-complete, it worked for me.
