### ISSUE TITLE
Allow boolean value on radio element, possibly on others

### ISSUE THREAD

**Issue by pbf** [vuetifyjs/vuetify#1454]
`<radio>` element accepts only String and Number as it's value attribute, with other types erroring on `inputValue` prop:
`Invalid prop: type check failed for prop "inputValue". Expected String, Number, got Boolean.`

I think at least with radio buttons, and possibly others, mapping selection controls to boolean model is perfectly valid mode of operation and I'd like to see Vuetify allowing this. I tracked this myself in module code, but sources on github differ in a way that doesn't entirely map for me to what's in distributed package. Probably some build step makes it like this.

**Comment by jacekkarczmarczyk** [comment]
dup of https://github.com/vuetifyjs/vuetify/issues/1369 i guess

**Comment by nekosaur** [comment]
I'm struggling to imagine a scenario where you would want radio buttons to represent boolean values. That seems like a job for a checkbox or switch.

**Comment by pbf** [comment]
Switch and checkbox represent toggling something on or off. Radio buttons represent choice between two semantically equal values. That those values are boolean (or anything else) is a detail of implementation that, I think, should not be determined by UI design.

**Comment by nekosaur** [comment]
I do agree that we should leave implementation up to users as much as possible, and I have no problem changing this as long as there are no side-effects. I am just struggling to think of a use case for booleans in radio buttons.

**Comment by fchabouis** [comment]
@nekosaur 
Example : a user can give me some details about a playground. The playground is either open at night or closed. So I want to have 3 possibilities : the user tells me it's open at night, he tells me it is closed at night, or he doesn't tell me anything. So I put a radio button with 2 choices : open and closed. By default, my data is undefined, so nothing is selected. If he selects an option, I can fill my data with a boolean value openAtNight : true/false. If he doesn't, I keep the undefined state.

Now If I put a checkbox with a label "open at night" and the user doesn't click on it, does it mean it is closed at night or that he didn't want to fill this information ?

So as far as I know I need the radio button to have a boolean value.

**Comment by KaelWD** [comment]
@fchabouis That's what `null` is for: https://codepen.io/anon/pen/yvdMMd?editors=1010

Also this is a very old issue and has been resolved. Create a new one or ask on [discord](https://community.vuetifyjs.com) if you are still having problems.
