### ISSUE TITLE
[Bug Report][2.6.1] v-slide-group rtl not work

### ISSUE THREAD

**Issue by nonomaxxis** [vuetifyjs/vuetify#14543]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 3.2.26
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
have 15 card but show only 6.5 card.

### Expected Behavior
show 15 card

### Actual Behavior
show only 6.5 card

### Reproduction Link
<a href="https://codepen.io/GarnetCMS/pen/bGoYpJb" target="_blank">https://codepen.io/GarnetCMS/pen/bGoYpJb</a>

### Other comments
hi, its not work correctly in RTL mode. i have 15 card but show only 6.5 card.

**Comment by KareemDa** [comment]
@KaelWD 
this problem is the same problem #14529 (Vtab also contain a slide group).

I've opend  a PR to fix it, please check #14538

**Comment by KaelWD** [comment]
Duplicate of #
