### ISSUE TITLE
Tabs: Pagination controls are missing (on desktop)

### ISSUE THREAD

**Issue by floqqi** [vuetifyjs/vuetify#1455]
### Steps to reproduce

1. Open https://vuetifyjs.com/components/tabs#example-8 (no pagination controls)
2. Resize browser (make it smaller) -> controls hidden
3. Full-screen browser -> controls available

### Versions

- Vue 2.4.2
- Vuetify 0.14.11
- Windows 7
- Chrome 60 / Firefox 50

### What is expected ?

There are controls if the content is too large for the tabs-bar.

### What is actually happening ?

Pagination controls are missing even if there are too many tabs.

### Reproduction Link

https://vuetifyjs.com/components/tabs#example-8

**Comment by nekosaur** [comment]
Fixed in #1341
