### ISSUE TITLE
[Bug Report][2.6.2] ColorPicker wrong color with rgba() string

### ISSUE THREAD

**Issue by digitalniweb** [vuetifyjs/vuetify#14551]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 3.2.26
**Browsers:** Firefox 95.0
**OS:** Windows 10

### Steps to reproduce
set v-model of ColorPicker to 'rgba(255,0,255,1)'

### Expected Behavior
Output should be: #FF00FFFF

### Actual Behavior
Actual output: #FFBAF254

### Reproduction Link
<a href="https://codepen.io/digitalniweb/pen/QWqQVwE" target="_blank">https://codepen.io/digitalniweb/pen/QWqQVwE</a>

**Comment by CreeTar** [comment]
what is an `rgba`-string, you are handing over what seems to be a function call inside of a string, that is not a JavaScript function either. The documentation states you are required to send a rgb-object in the form of a JSON, such as `rgba: { r: 255, g: 0, b: 255, a:1 }` and that also works as expected. Could you point to the API documentation where it says that a rgba-function call is an acceptable parameter?

**Comment by digitalniweb** [comment]
Btw. it works with hex "#f00" for example. But I misled my self to believe it worked with rgb(255,0,0) which it doesn't. So I thought to my self it was a bug, which isn't because it's not expected as you say. But it would be nice if it did when it works with hex.

**Comment by digitalniweb** [comment]
@CreeTar Btw. it works with hex "#f00" for example. But I misled my self to believe it worked with rgb(255,0,0) which it doesn't. So I thought to my self it was a bug, which isn't because it's not expected as you say. But it would be nice if it did work when it works with hex. And the documentation here https://vuetifyjs.com/en/api/v-color-picker/#props says: "Depending on what you passed to the value prop this is either a string or an object"

**Comment by KareemDa** [comment]
> And the documentation here https://vuetifyjs.com/en/api/v-color-picker/#props says: "Depending on what you passed to the value prop this is either a string or an object"

Right, but read what `value` description prop says: Current color. This can be either a string representing a hex color, or an object representing a RGBA, HSLA, or HSVA value

so it's not allowed to send rgb as a string. I don't think it's a bug.
