### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] [Vue warn]: Failed to resolve component: v-select

### ISSUE THREAD

**Issue by leonardlin** [vuetifyjs/vuetify#14563]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.26
**Browsers:** Firefox 95.0
**OS:** Windows 10

### Steps to reproduce
Steps:
* Create a blank app with a v-select component.
* open the console window
* The warning is printed that v-select is not recognized as a component.

Reproduction:
* open the reproduction codepen
* open the console area
* the warning is printed 

Other steps I've tried:
* I checked the code-repo if the component exists:
https://github.com/vuetifyjs/vuetify/tree/v3.0.0-alpha.12/packages/vuetify/src/components/VSelect
* Tried alpha.11, same error

I'm interested to help resolve this. 
Which branch should I fork for the 3.0.0 version?
The contribution-guide mentions, that it should be 'dev'? Is that correct for 3.0.0?

### Expected Behavior
v-select is rendered

### Actual Behavior
The warning is printed that v-select is not recognized as a component.

### Reproduction Link
<a href="https://codepen.io/leonardlin/pen/BawrqPm?editors=1111" target="_blank">https://codepen.io/leonardlin/pen/BawrqPm?editors=1111</a>

**Comment by KaelWD** [comment]
Not implemented yet. 

https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/index.ts
