### ISSUE TITLE
[Bug Report][2.6.2] Intellisense not working when extending component

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#14562]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
Extend any vuetify component as described: https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#extend-components

### Expected Behavior
Intellisense should work on extended property "to help adding props" 

### Actual Behavior
Intellisense not working

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
I don't know if this option is related to vuetify or vetur extension. 

But it's really annoying. It's so hard to add props without auto completion

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Comment by douglasg14b** [comment]
mhm, discord, the black hole for Q&A
