### ISSUE TITLE
[Bug Report][2.6.2] v-btn-toggle interfere with other elements

### ISSUE THREAD

**Issue by kkrell2016** [vuetifyjs/vuetify#14568]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.4
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
The first button under the v-btn-toggle turns into active state, when you use the select outside of the dialog.
Its just an example, the problem also occurs in combination with gmap.
I also tried it with a v-model, but without effect.

I use the dialog in an app to overlay some informations.

### Expected Behavior
v-btn-toggl should only react to actions in it's own scope

### Actual Behavior
v-btn-toggle changes the optical state when you use another input element.

### Reproduction Link
<a href="https://codepen.io/kkrell/pen/ExwLBEP" target="_blank">https://codepen.io/kkrell/pen/ExwLBEP</a>

**Comment by jacekkarczmarczyk** [comment]
Works fine with `:retain-focus="false"` on `<v-dialog>`

**Comment by kkrell2016** [comment]
Thank you very much, I owe you something.
The search has cost me hours of my life and the solution is so simple.

Now i feel a little bit dumb
