### ISSUE TITLE
[Bug Report][2.6.2] v-treeview return-object causes opening initial nodes not working

### ISSUE THREAD

**Issue by swuqi** [vuetifyjs/vuetify#14574]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
1. specify :open="opennodes" and return-object
2. Show tree view and check the nodes are not opened.
3. Remove return-object and check the nodes are opened.

### Expected Behavior
Specified tree nodes should be opened.

### Actual Behavior
Specified tree nodes are not opened.

### Reproduction Link
<a href="https://codepen.io/totalhack/pen/KKzzXvr" target="_blank">https://codepen.io/totalhack/pen/KKzzXvr</a>

**Comment by TheoPez** [comment]
Hi @swuqi, I think there is no bug at this point, according to the documentation https://vuetifyjs.com/en/api/v-treeview/#props-return-object

The docs says:
> When true will make v-model, active.sync and open.sync return the complete object instead of just the key



So, if you use return-object on a vTreeView then the `open` value must be an array of objects that contains at least the `item-key` (by default `item-key` is equal to `"id"`).

Example: `:open="[{id:1}]"`

### SOLUTION:

https://codepen.io/the0pe/pen/poWZxaP

**Comment by swuqi** [comment]
Hi TheoPez,

Thanks for the information. I thought it and tried it with [{id: 1, name: "xxx"}] in my code and somehow it didn't work. Then I have to remove return-object and implemented tree search for the id. Now it seems working in codepen with the format of object. I will try it in my real code.

Shangwu

**Comment by swuqi** [comment]
When I changed my code of Asp.Net MVC 5 with Vue-2.6.12 and Vuetify-2.4.6, it didn't work with return-object. Removing return-object and setting :open=[1, 2, 3] works.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
