### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] VTextField hideDetails not working

### ISSUE THREAD

**Issue by SegaraRai** [vuetifyjs/vuetify#14572]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.26
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
N/A

### Expected Behavior
The details (.v-input__details) should not appear if hide-details is set.

### Actual Behavior
The details are always displayed regardless of the hide-details property.

### Reproduction Link
<a href="https://codepen.io/segararai/pen/qBPKPow" target="_blank">https://codepen.io/segararai/pen/qBPKPow</a>

### Other comments
Setting 'auto' or other values did not work.

**Comment by KaelWD** [comment]
Fixed by #14430

**Comment by korkt-kim** [comment]
no not fixed yet

**Comment by AntoninRousset** [comment]
It works for me
