### ISSUE TITLE
[Bug Report][3.0.0-next-20220107.0] Got "Uncaught TypeError: dir is undefined" when using TextField or Textarea

### ISSUE THREAD

**Issue by BreizhReloaded** [vuetifyjs/vuetify#14578]
### Environment
**Vuetify Version:** 3.0.0-next-20220107.0
**Last working version:** 3.0.0-alpha.12
**Vue Version:** 3.2.26
**Browsers:** Firefox 95.0
**OS:** Windows 10

### Steps to reproduce
1. Start Vue project using Vuetify Nightly 20220107
2. Use TextField component
3. Get "Uncaught TypeError: dir is undefined" in console

### Expected Behavior
Text Field is displayed

### Actual Behavior
Component is not displayed

### Reproduction Link
<a href="https://github.com/BreizhReloaded/my-vue-app" target="_blank">https://github.com/BreizhReloaded/my-vue-app</a>

### Other comments
I checked the previous versions, the last working version may be 20211217. It seems to be related to the Field component or its dependencies as Text Field and Textarea both import it.

**Comment by KaelWD** [comment]
This is a compiler bug: https://github.com/vuejs/babel-plugin-jsx/issues/541

Workaround is to import the intersect directive globally:
```js
import { Intersect } from 'vuetify/directives'

createVuetify({
  directives: { Intersect },
})
```

**Comment by BreizhReloaded** [comment]
I noticed indeed last week that importing directives solves the issue, it works perfectly when adding `Intersect. Thanks for the cleaner workaround Kael, hope they'll fix that soon!
