### ISSUE TITLE
[Bug Report][2.6.2] v-combobox suggestions not working after re-focus

### ISSUE THREAD

**Issue by janwendt** [vuetifyjs/vuetify#14576]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 3.2.26
**Browsers:** Firefox 95.0
**OS:** Windows 10

### Steps to reproduce
1. Click into the v-combobox and type "Ga".
2. Now you can see the correct "Gaming" suggestion.
3. Click out of the v-combobox to the empty page and then click back into the v-combobox.
4. Now all items appear not only "Gaming" as expected.
5. Moreover if you now add "m" to the "Ga" you will see the correct suggestion "Gaming" again but if you remove the "m" afterwards all items will appear again.

### Expected Behavior
Only "Gaming" item should appear

### Actual Behavior
All items appear

### Reproduction Link
<a href="https://codepen.io/janwendt/pen/RwLBQad" target="_blank">https://codepen.io/janwendt/pen/RwLBQad</a>

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://vuetifyjs.com/en/components/combobox/ (first example)
