### ISSUE TITLE
[Feature Request] Use "start - end" instead of "left - right" in Spacing

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#14577]
### Problem to solve
using spacing helper classes: (ex: `mr-3`) is great when the application run in one direction only(LTR for example). 
![image](https://user-images.githubusercontent.com/42810389/148543276-b1bd93f3-a531-4740-a52d-0108621395f1.png)

but if tried to change the direction to RTL, this won't work, I'll need to add `ml-3` instead of `mr-3`
![image](https://user-images.githubusercontent.com/42810389/148543288-81f60886-be44-45d5-801c-158c0e926d37.png)

But what if the application should work in both directions? RTL, LTR as well?

### Proposed solution
use classes `ms-{x}` - `me-{x}` instead of `ml-{x}` - `mr-{x}`. (S: refers to start  - E: refers to end)

one way to implement it is by using `ltr()` & `rtl()` mixins to generate these classes from normal spacing classes: 

example: (SCSS)
![image](https://user-images.githubusercontent.com/42810389/148543503-ea46e0ab-efff-4616-999c-034fb19a1beb.png)

**Comment by KaelWD** [comment]
This already exists.

**Comment by KareemDa** [comment]
Thank you for your response, Can you provide a documentation link? or it's a feature in Vuetify 3?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/styles/spacing/
