### ISSUE TITLE
[Documentation] Duplicate sentences in contributing page

### ISSUE THREAD

**Issue by Vaironl** [vuetifyjs/vuetify#14583]
### Environment

**Browsers:** Chrome 97.0.4692.71
**OS:** Linux x86_64

### Steps to reproduce
Scroll to *Choosing a base branch* section.

Find the sentence in the section that is as follows: "Commit your changes following our guidelines, then push the branch to your fork with git push -u fork and open a pull request on the Vuetify repository following the provided template."

### Expected Behavior
The sentence should appear only once in this section.

### Actual Behavior
This sentence appears twice in this section.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/contributing/#choosing-a-base-branch" target="_blank">https://vuetifyjs.com/en/getting-started/contributing/#choosing-a-base-branch</a>

### Other comments
Remove either of the duplicated sentences.

**Comment by s-rigaud** [comment]
Seems to be fixed now 🧹
