### ISSUE TITLE
[Bug Report][2.6.0] VDialog, error after change "fix(VDialog): don't re-focus autofocused children"

### ISSUE THREAD

**Issue by mlankamp** [vuetifyjs/vuetify#14581]
### Environment
**Vuetify Version:** 2.6.0
**Last working version:** 2.5.14
**Vue Version:** 2.6.14
**Browsers:** Edge 99.0.1128.0
**OS:** Windows 10

### Steps to reproduce
* Create Dialog, sometime I see an error in the console:
```
TypeError: Cannot read properties of undefined (reading 'contains')
    at VueComponent.<anonymous> (VDialog.ts:190:16)
    at Array.<anonymous> (vue.runtime.esm.js:1989:1)
    at flushCallbacks (vue.runtime.esm.js:1915:1)
```

### Expected Behavior
Additional check if this.$refs.content is not undefined

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by jmarshall9120** [comment]
I get this same bug when trying to extend the dialog component

```
<template>
  <v-dialog v-bind="$props" v-on="$listeners">
    <template
      v-for="slot in Object.keys($scopedSlots)"
      :slot="slot"
      slot-scope="scope"
    >
      <slot :name="slot" v-bind="scope" />
    </template>
  </v-dialog>
</template>
<script>
import { VDialog } from 'vuetify/lib'
export default {
  name: 'DialogWHeader',
  extends: VDialog,
}
</script>
<style lang="scss"></style>

```

Not sure how this works internally currently, running it down now.

**Comment by KaelWD** [comment]
https://stackoverflow.com/a/70064606/2074736
