### ISSUE TITLE
[Bug Report][2.6.2] Set Calendar type="category" then scrollToTime() not working

### ISSUE THREAD

**Issue by jungbongjoon** [vuetifyjs/vuetify#14589]
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. set v-calendar prop type="category"
2. and scrollToTime method not working

### Expected Behavior
$refs.scrollArea's overflow: scroll

### Actual Behavior
$refs.scrollArea's overflow: hidden

### Reproduction Link
<a href="https://codepen.io/byjune/pen/NWaOXBO" target="_blank">https://codepen.io/byjune/pen/NWaOXBO</a>

### Other comments
Because scrollArea cannot scroll, this method allways return scrolltop 0.

**Comment by jungbongjoon** [comment]
> Any update or workaround on this? Would be very kind. Thanks!

It's not a good way, but I'm using the method after overriding it.

```javascript
// this.calendar?.scrollToTime(first);
this._scrollToTime(first)

_scrollToTime(time) {
  const y = this.calendar.timeToY(time);
  if (y === false || !this.calendar.$el) {
    return false;
  }
  this.calendar.$el.scrollTop = y;
  return !!this.calendar.$el.scrollTop;
},
```

**Comment by ArturWesner** [comment]
Seems to be working, thank you!
When switching the type i await the next tick and if the type is `category`, i am applying the scrollTop to the `$el`. Otherwise the calendar's internal scrollToTime method is called

**Comment by devonik** [comment]
Could you please post your snippet where it's working with type "category"?

> Seems to be working, thank you! When switching the type i await the next tick and if the type is `category`, i am applying the scrollTop to the `$el`. Otherwise the calendar's internal scrollToTime method is called

Could you please post your snippet where it's working with type "category"?

**Comment by ArturWesner** [comment]
See jungbongjoon's code snippet

> > Any update or workaround on this? Would be very kind. Thanks!
> 
> It's not a good way, but I'm using the method after overriding it.
> 
> ```js
> // this.calendar?.scrollToTime(first);
> this._scrollToTime(first)
> 
> _scrollToTime(time) {
>   const y = this.calendar.timeToY(time);
>   if (y === false || !this.calendar.$el) {
>     return false;
>   }
>   this.calendar.$el.scrollTop = y;
>   return !!this.calendar.$el.scrollTop;
> },
> ```

**Comment by devonik** [comment]
If anyone is interested in a example how this workaround works for every type: https://codepen.io/devonik/pen/VwyWQZz?%3Feditors=101
