### ISSUE TITLE
[Bug Report][2.6.2] VSlideGroup arrows are sometimes visible when show-arrows = false

### ISSUE THREAD

**Issue by bokub** [vuetifyjs/vuetify#14586]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.110
**OS:** Linux x86_64

### Steps to reproduce
Just open the CodePen with a large screen (desktop). You may see an arrow immediately even if `:show-arrows="false"`.

### Expected Behavior
`:show-arrows="false"` should always hide the arrows, not only on mobile

### Actual Behavior
Arrows are visible on desktop

### Reproduction Link
<a href="https://codepen.io/bokub/pen/xxXaebb" target="_blank">https://codepen.io/bokub/pen/xxXaebb</a>

![Peek 2022-01-10 10-02](https://user-images.githubusercontent.com/17952318/148740563-7ae9b67c-c749-466c-bd46-b4d888cbcbde.gif)

**Comment by HaimCandiTech** [comment]
Any workaround behind it except adding display: none to the arrows?

**Comment by bokub** [comment]
@HaimCandiTech a pull request has been created to fix this (https://github.com/vuetifyjs/vuetify/pull/14587), but was months ago and I'm still waiting for someone to merge it :shrug:
