### ISSUE TITLE
[Bug Report][2.6.2] `v-main` has wrong padding with `v-navigation-drawer`

### ISSUE THREAD

**Issue by DerYeger** [vuetifyjs/vuetify#14585]
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.5.0
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Windows 10

### Steps to reproduce
1. Add `v-navigation-drawer` and `v-main` components
2. Enable `expand-on-hover` for the navigation drawer

### Expected Behavior
The left padding of the `v-main` matches the drawers width

### Actual Behavior
It always is 256px

### Reproduction Link
<a href="https://github.com/DerYeger/jan-mueller" target="_blank">https://github.com/DerYeger/jan-mueller</a>

**Comment by TheoPez** [comment]
Hi @DerYeger, a better reproduction link for moderation and community developers may be: https://codepen.io/the0pe/pen/xxXyRzY

To fix it temporarily in your code, there is an easy way (use mini-varient with the sync modifier):
https://codepen.io/the0pe/pen/Jjrmbvp

**Comment by KaelWD** [comment]
@johnleider This is from this change: https://github.com/vuetifyjs/vuetify/commit/03e683f286e652b942b83a817cecc080d4c4a6eb#diff-98d92001e9cf0f207f45c674457cea37a833979a1b0f0b143cb3714454acdddeR442

**Comment by dev-ocsi** [comment]
Yes, works ok in v2.5.9 but not in 2.6.2

**Comment by dev-ocsi** [comment]
> Hi @TheoPez , You said "To fix it temporarily in your code, there is an easy way (use mini-variant with the sync modifier): https://codepen.io/the0pe/pen/Jjrmbvp "

Although this temp fix is both appreciated and way better than nothing at all, it causes the whole main area to squeeze and expand each time the drawer opens and closes (instead of overlaying the main area as it should do). As a temporary fix and if you can, I would recommend rolling your vuetify version back to v2.5.9 until this bug is fixed

**Comment by TheoPez** [comment]
Hi @dev-ocsi, I understand what you are saying. We have two interpretations.

When I read this : 
> Expected Behavior:  The left padding of the v-main matches the drawers width

For me, he wants to synchronize the size of the main area with the current state of the drawer

Indeed, if he (or you) wants the drawer to overlap the main area, you can simply remove the `sync` modifier like this:
https://codepen.io/the0pe/pen/gOGZGwo

**Comment by dev-ocsi** [comment]
@TheoPez 

Awesome, yes, I think I misinterpreted what the expected behaviour from @DerYeger was...although his problem is 99% the same as mine. I've tried what you suggested in your codepen (https://codepen.io/the0pe/pen/gOGZGwo) and it 100% works for v2.6.2.

**Comment by johnleider** [comment]
As far as I can understand, your issue is the problem my fix was meant to solve. The default behavior for expand-on-hover is to overlay the content, not move the content area.

That's not to say this isn't a valid use-case, but I don't believe it's a bug.

**Comment by KaelWD** [comment]
@johnleider `expand-on-hover` used to imply `mini-variant`, and `:mini-variant.sync` could be used to push v-main on hover. Now `expand-on-hover` still sets the drawer to mini width, but without `mini-variant` it always uses the full width for the v-main offset. 

[2.6.1](https://codepen.io/kaelwd/pen/NWaJgWE?editors=1010)  
[2.6.2](https://codepen.io/kaelwd/pen/XWeGgJb?editors=1010)

**Comment by maximiliancs** [comment]
My `v-main` has also wrong padding, when `v-navigation-drawer` and `v-app-bar` use the `app` prop. In this case the padding is not 256px. It seems that the values get doubled when they are added depending on the screen size. This has to be related. Everything worked in  v2.6.1.

@johnleider @KaelWD What's the status on this?

**Comment by johnleider** [comment]
If there are no updates in this thread then there is no status updates.

**Comment by NathanAP** [comment]
It seems I have a similar situation with `v-navigation-drawer`, but its only happening after `build`.

This is my `v-navigation-drawer > v-list > v-list-group > v-list-item` running with `npm run dev`:

![Screenshot_7](https://user-images.githubusercontent.com/12821171/191352433-c6555d4a-3cbd-420f-bc4c-52a17c3e84eb.png)

Now this is the very same component but after running in `npm run build`: 

![Screenshot_8](https://user-images.githubusercontent.com/12821171/191352639-01c52a44-d19b-41c1-82db-e78e5eb921ea.png)

While this is the padding being shown in my dev tools:

![Screenshot_10](https://user-images.githubusercontent.com/12821171/191352774-80f89497-ec99-4c7f-9c91-1f42b1e01a5e.png)

**Comment by ozgurg** [comment]
> My `v-main` has also wrong padding, when `v-navigation-drawer` and `v-app-bar` use the `app` prop. In this case the padding is not 256px. It seems that the values get doubled when they are added depending on the screen size. This has to be related. Everything worked in v2.6.1.
> 
> @johnleider @KaelWD What's the status on this?

I have exactly the same problem.
