### ISSUE TITLE
[Bug Report][2.6.2] VDataTable "no-data" slot not centered on first laod (Nuxt)

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#14580]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Windows 10

### Steps to reproduce
- Create Datatable
- add "no-data" slot
- add a centered flex container.

### Expected Behavior
it should be centered

### Actual Behavior
on first load it rendered on the left then it's centered

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
- Can't add reproduction link because the bug when using nuxt(SSR).

- screenshots:

**On first Load**
![image](https://user-images.githubusercontent.com/42810389/148641319-8ab26bdb-0f05-43d6-8b26-8fd3d8a8c45b.png)

**after finish loading**
![image](https://user-images.githubusercontent.com/42810389/148641339-39900e00-f611-45f4-865b-fac6b085ad99.png)

**workaround:** wrap the table with `<client-only>` component. 

the problem is probably because the default breakpoint in nuxt is `xs` and in mobile views, there is no `colspans` attribute in `td`

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
