### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-main padding is messed up when moving between views when using keep-alive

### ISSUE THREAD

**Issue by funkyvisions** [vuetifyjs/vuetify#14588]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.13
**Browsers:** Safari 15.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
I see something weird when routing from a page that had a v-appbar and v-bottom-navigation to a page the doesn't when using keep-alive.  The padding seems to get left behind and applied on the new v-main.

### Expected Behavior
Expected the previous layout to not remain

### Actual Behavior
Previous layout remains

### Reproduction Link
<a href="https://codepen.io/funkyvisions/pen/RwLMEGd" target="_blank">https://codepen.io/funkyvisions/pen/RwLMEGd</a>

### Other comments
I also notice that animations are applied as the app-bar is removed (collapsed).  Is there a way to prevent this.  It looks weird, especially in a tabbed component, to have that happen.   Here's a video.

https://www.dropbox.com/s/0fmnq0f0197w28t/Screen%20Recording%202022-01-10%20at%209.22.07%20AM.mov?dl=0

I was able to fix it with
```
.v-main {
    transition: none !important;
}
```
But that feels hacky.

**Comment by nickvdwaal** [comment]
There is definitely something weird going on with animations and transitions in next.

**Comment by nekosaur** [comment]
https://github.com/vuetifyjs/vuetify/pull/14657/commits/759c18aa9b6a6767e18292a4ed4bfd96807a99ff

**Comment by KaelWD** [comment]
Fixed in c08758dff1007f6c0adc165888924ae20e3b9022
