### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Theming setup isn't working as spec'd

### ISSUE THREAD

**Issue by funkyvisions** [vuetifyjs/vuetify#14592]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.13
**Browsers:** Safari 15.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
Run example and notice exception.  If you change the code to the following, then it works, but I don't think that's the intended way to do it.
```
   theme: {
        defaultTheme: "light",
        themes: {
            light: {
                dark: false,
                colors: {
                    primary: "#007DCD"
                }
            }
        }
    }
```

### Expected Behavior
Shouldn't throw exception

### Actual Behavior
Throws exception

### Reproduction Link
<a href="https://codepen.io/funkyvisions/pen/VwMEVEw" target="_blank">https://codepen.io/funkyvisions/pen/VwMEVEw</a>

**Comment by KaelWD** [comment]
Fixed by #14528

Please check the latest [nightly build](https://vuetifyjs.com/en/getting-started/installation/#nightly-builds) before reporting v3 bugs.
