### ISSUE TITLE
[Bug Report][2.6.2] When the v-switch component sets the dense attribute, the height is not set correctly, which is inconsistent with other components

### ISSUE THREAD

**Issue by danclive** [vuetifyjs/vuetify#14591]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Firefox 96.0
**OS:** Linux

### Steps to reproduce
Set the v-switch component dense attribute

### Expected Behavior
The height of the v-switch component change correctly

### Actual Behavior
The height of the v-switch component does not change correctly

### Reproduction Link
<a href="https://codepen.io/danclive/pen/PoJyeQE" target="_blank">https://codepen.io/danclive/pen/PoJyeQE</a>

### Other comments
Is it possible to add a CSS property to the v-switch component？
```
.v-input--switch.v-input--dense {
    margin-top: 4px;
}
```

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3;

https://play.vuetifyjs.com/#eNqdUW1rwjAQ/ish7IOCbcANBqUT9xv8aAVre85sTRqSa51I//uuSWVOB7p9Su5J7nm5Wx75qzFx2wBPeIqgTJUjzDLNWNpGbi+x2PUFY22k6hKql4z7M+MB3skSohIwl5ULiNQOMFyTKt/4lvXCMyXs4ei7Y6wXaKV+G427daCapeIk6OX/b+AvqoyVoJ3EA30vamXyAn+zk4qz0aSusNKgdwmfprZIJNu8qZAdB84cczYan0rGLGBj9XfNmDeUMLQNTE5oFy6dB6hIxaDEJ7yS+sPF767WtCjPQ4ady3jClqEt4ztE4xIhilLTT+KXrY01oNBGCVoxyu1h/hhP46kopcMTFNG8XOzJeqZVpjsSlKpPFqncXKiGB6885Mk4MfX1DQtz+iZso1EqWlmtvJen52DmDI/BqWhj670DSywZHybkdXrHd2jdiksSV9SC9FqwkQVdggV7b6SLth+xLt6uog2r7ng34aGPZu9N89UX8RIyUQ==
