### ISSUE TITLE
v-model should allow parent to reject input change

### ISSUE THREAD

**Issue by lkho** [vuetifyjs/vuetify#14597]
Vuetify: 2.6.0

related issues (mostly solved by hacky workarounds):
https://github.com/vuejs-tips/v-money/issues/44
https://stackoverflow.com/questions/53134629/vue-js-restore-input-value-if-model-rejects-changes
https://stackoverflow.com/questions/64908584/cant-prevent-change-value-of-v-select-component
https://techinplanet.com/vuetify-checkbox-how-to-stop-the-click-event/

With reference to the following internal lazy value implementations, the rational of "allows an input to function without a provided model" is good, but however prevents legitimate use cases where the parent ultimately want to reject or alter the value.

https://github.com/vuetifyjs/vuetify/blob/9e2edf30fb3359bea93b60084fd2327234f86a76/packages/vuetify/src/components/VInput/VInput.ts#L99-L111

https://github.com/vuetifyjs/vuetify/blob/9e2edf30fb3359bea93b60084fd2327234f86a76/packages/vuetify/src/mixins/proxyable/index.ts#L38-L44

I suggest the following patches to check for the existence of a value binding first before applying the lazy value:

for `Proxyable`:

```typescript
if (!(prop in this.$options.propsData)) {
  this.internalLazyValue = val;
}
```

for `VInput`:

```typescript
  beforeCreate() {
    // v-radio-group needs to emit a different event
    // https://github.com/vuetifyjs/vuetify/issues/4752
    this.$_modelEvent = this.$options.model && this.$options.model.event || 'input';
    this.$_modelProp = this.$options.model && this.$options.model.prop || 'value';
  },

  internalValue: {
    get() {
      return this.lazyValue;
    },
    set(val) {
      if (!(this.$_modelProp in this.$options.propsData)) {
        this.lazyValue = val;
      }
      this.$emit(this.$_modelEvent, val);
    }
  },
```

**Comment by KaelWD** [comment]
This is how it works in v3: https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/composables/proxiedModel.ts

**Comment by lkho** [comment]
> This is how it works in v3: https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/composables/proxiedModel.ts

that should work. however what if the prop value is really `undefined`?

btw, will there be plans to integrate this fix to vue 2 also?
