### ISSUE TITLE
[Bug Report][2.6.2] unexpected border-radius of the first row in a data table

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#14594]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
Hover on the first row

![image](https://user-images.githubusercontent.com/40021217/149085375-6295e997-cec2-4e52-a01e-2cf91b5d268a.png)

### Expected Behavior
There should be no ugly border-radius when the first row is hovered because the header row also has a bottom border

### Actual Behavior
With border-radius on top-right and top-left

### Reproduction Link
<a href="https://codepen.io/kingyue737/pen/zYEMomw" target="_blank">https://codepen.io/kingyue737/pen/zYEMomw</a>

**Comment by lioneaglesolutions** [comment]
Closed as this has been resolved in V3 where I don't think there are any default hover styles anyway.

@johnleider if happy, can you please close related PR  https://github.com/vuetifyjs/vuetify/pull/14628

**Comment by kingyue737** [comment]
@lioneaglesolutions I opened this issue for the stable data-table of Vuetify 2 which has not reached end of life yet. In my opinion, it's better to leave it open.

**Comment by lioneaglesolutions** [comment]
Will reopen this one for now @johnleider

**Comment by johnleider** [comment]
The PR has been inactive for over a year and this issue hasn't had any traction, closing.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
