### ISSUE TITLE
[Bug Report][2.6.2] Spacing example not working as expected

### ISSUE THREAD

**Issue by mukeshghodela-easternts** [vuetifyjs/vuetify#14600]
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.6.2
**Vue Version:** 2.6.0
**Browsers:** Edge 97.0.1072.55
**OS:** Windows 10

### Steps to reproduce
![image](https://user-images.githubusercontent.com/59353507/149307642-7a3ea48e-9ff9-4275-b636-ab10a9020918.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/59353507/149310169-f896d93e-37f5-4884-bd35-518d55851396.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/59353507/149307725-cc984c90-909f-43b2-96a0-94fc12014398.png)

### Reproduction Link
<a href="https://codepen.io/pen/?&editors=101" target="_blank">https://codepen.io/pen/?&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Report doesn't work and expected/actual behaviour images look the same

**Comment by mukeshghodela-easternts** [comment]
@jacekkarczmarczyk Thanks for the quick response, I don't know why expected and actual behavior looks same, I have uploaded different but it automatically gets converted into same ![image](https://user-images.githubusercontent.com/59353507/149310482-8150f1be-8abc-47f5-924f-c2230fde56e1.png)
https://vuetifyjs.com/en/styles/spacing/#breakpoints

**Comment by KaelWD** [comment]
Looks fine to me, I think it's just a bad example.

**Comment by mukeshghodela-easternts** [comment]
@KaelWD @jacekkarczmarczyk  I have recorded video, how is different actual example and codepen example

https://user-images.githubusercontent.com/59353507/149312683-3d50ae5f-ba5a-4b05-8c87-92aad892a5cd.mp4

**Comment by jacekkarczmarczyk** [comment]
are you talking about margins? they are different because there's different breakpoint in codepen and docs

![image](https://user-images.githubusercontent.com/15625235/149313327-1f92b0ea-5d7c-48c9-95cd-dfc9d98e3eee.png)
