### ISSUE TITLE
[Bug Report][2.6.2] v-calendar loses events if start or end time is outside visible range

### ISSUE THREAD

**Issue by usu** [vuetifyjs/vuetify#14603]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Windows 10

### Steps to reproduce
1. Limit visible intervals by e.g. using first-interval 6 and interval-count 15 (=from 6am to 9pm)
2. Add multi day events (=end date > start date) with either start time or end time in the invisible range (before 6am or after 9pm)

### Expected Behavior
All events with **some** portion in the visible range should be displayed, but cut to the visible portion only.

In the provided codepen that would be all events except event 7 which is scheduled entirely in the invisible part.

### Actual Behavior
Only events 1-4 are shown.

Events 3 and 4 are properly cut to the visible range, even though start or end time is outside the visible range.

For multi-day events only event 2 is shown. As soon as either start or end time is in the invisible range (event 5,6,8) the event is not displayed at all.

### Reproduction Link
<a href="https://codepen.io/ursu/pen/MWEZbpN" target="_blank">https://codepen.io/ursu/pen/MWEZbpN</a>

### Other comments
- Might be related to https://github.com/vuetifyjs/vuetify/issues/13785
- Further improvement idea: Event 7 could potentially (and optionally) be displayed as an all day event, but that's something that would be possible already by changing the event type manually from outside v-calendar.

**Comment by usu** [comment]
Potentially a duplicate of https://github.com/vuetifyjs/vuetify/issues/12563

**Comment by MartinX3** [comment]
Still an issue with vuetify v2.6.5
