### ISSUE TITLE
[Bug Report][2.5.10] V-carousel makes the page jump around when transition is set to false

### ISSUE THREAD

**Issue by MilenaMalysh** [vuetifyjs/vuetify#14607]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
1) open the link
2) scroll down to the point when the carousel is partially cut at the top but the navigation buttons are still visible
3) click back and forth to the next and previous slides (try clicking back and forth multiple times if the bug doesn't appear immediately)

### Expected Behavior
page and the carousel stay where they are

### Actual Behavior
the page jumps around

### Reproduction Link
<a href="https://jsfiddle.net/MilenaMalysh/5g9ten81/7/show" target="_blank">https://jsfiddle.net/MilenaMalysh/5g9ten81/7/show</a>

### Other comments
when a transition is used the bug doesn't appear

https://user-images.githubusercontent.com/16187012/149401612-9b118b9e-8def-42c5-b443-e8bf956704ce.mp4

**Comment by joaomateuus** [comment]
Im with this issue too, I`ve read the whole vuetify docs and did not find smthg that could help

**Comment by lioneaglesolutions** [comment]
Closing as this has been resolved in V3

https://play.vuetifyjs.com/#eNq1VNtO4zAQ/RXLL4BU24hdaVfZLILvIH1wE7e49Q3bCVSo/87Ybtq0SICEyJPnzPicM5NJHl7xvXN06AWucB2FdopHcdsYhOqBtNzbPgiFWsVD+N/gEWhwLjkpIhKuFxShgSythwuXCZzJKyQNSsfQ4LGk2ogtVMgJEnybEKijcDwmWjsIX4Lbmp1JFrMTFICaTVqpQ+uli7lOvDjrI+rEkvcqotdC2vHI0eXVGCLkRey9OcaomK/QwxFB03R6wHKFLh5jdKFirO1MGmuUy+060NZqJjVficBGmyw89dJ7oejarS5mU67dSfRdmc32hxUW0nc/LAHv0oj4scj8cN6VQ0lCULPDCqR1iFuV9oIe1jub09yvpCHRugr9vb52L/8m6MLGaPUxUUgzEZ5hJc0m0HWwBr6iTAafSoBdPyxMg6e9rkMnlBw8hZ6YcZrtm7/7RW/oDetkiCNEFF/ASBJZYpqDNAhKndaYaO7OVEsiK+8n3mBgSvEnFu6gjPneRKkF6azOXn7/KWYmOBVBk4W3z0F4YGnwfupZJzn+gtZn7YLEO2oGevAXIF6YTnj4HXyxpbNrJ22d5d61tl+fHd7NcLkHs8+m8fwN5T6otQ==
