### ISSUE TITLE
[Feature Request] could you please create v3.0.0.alpha.13 release?

### ISSUE THREAD

**Issue by korkt-kim** [vuetifyjs/vuetify#14610]
### Problem to solve
with v.3.0.0.alpha.12 there are too many features that do not work (like hide details in v-text-field)
so I wish you to make new release version of next branch.

### Proposed solution
new release version of v.3.0.0

**Comment by craigrileyuk** [comment]
Seriously?

**Comment by angelhdzmultimedia** [comment]
Doesn't the beta releases this month?
