### ISSUE TITLE
[Bug Report][2.6.0] v-combo-box inside v-data-table changes width on click

### ISSUE THREAD

**Issue by Teradom** [vuetifyjs/vuetify#14614]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 97.0.4692.71
**OS:** Windows 10

### Steps to reproduce
json-server --watch src/db.json
npm run serve
visit http://localhost:8080/orders/2070 and scroll down

### Expected Behavior
Fixed width for v-combo-box when it's inside v-data-table template

### Actual Behavior
Active dropdowns change their width on click.

### Reproduction Link
<a href="https://github.com/Teradom/teralogistics-vuetify" target="_blank">https://github.com/Teradom/teralogistics-vuetify</a>

### Other comments
There is a related topic on SO, but I find it overcomplicated for daily use https://stackoverflow.com/questions/68074520/vuetify-v-select-component-width-changing

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
