### ISSUE TITLE
[Bug Report][2.6.2] VSelect validation errors

### ISSUE THREAD

**Issue by apfrod** [vuetifyjs/vuetify#14615]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 97.0.4692.71
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Get HTML output for v-select component
2. Run it through W3C HTML validator at https://validator.w3.org/
3. See errors show below

### Expected Behavior
HTML markup should validate

### Actual Behavior
Three errors are returned:
- The element `label` must not appear as a descendant of an element with the attribute `role=button`.
- Attribute `aria-readonly` must not be specified on elements that have attribute `readonly`.
- The element `input` must not appear as a descendant of an element with the attribute `role=button`.

### Reproduction Link
<a href="https://codepen.io/apfrod/pen/OJxdLEw" target="_blank">https://codepen.io/apfrod/pen/OJxdLEw</a>

**Comment by agreedSkiing** [comment]
@KaelWD vuetify should follow the WCAG specification if it wants so be accessible even if the current v-select element work. Check this link please https://www.w3.org/WAI/GL/WCAG20/NOTE-WCAG20-TECHS-20090105/G134.html.

**Comment by agreedSkiing** [comment]
A stupid workaround to fix the html validation is to use mounted BUT this is not good.
`mounted() {
this.$el.querySelectorAll(".v-input__slot")?.removeAttribute("role")
}`

**Comment by agreedSkiing** [comment]
So after not being able to let it go whilst having lunch. Here is another stupid workaround that can be applied to the document from the main page on mount, since it observers the site all the time, still stupid and might be ineffcient but works... this second stupid workaround was made with typescript.
```
  mounted() {
    const callback = new MutationObserver((mutations) => {
      var inputs = this.$el.querySelectorAll("title");
      mutations.forEach((mutation) => {
        const element = mutation.target as Element;
        inputs = element.querySelectorAll(".v-input__slot");
      });
      if (inputs !== null || inputs !== undefined) {
        inputs.forEach((input) => {
          if (input.attributes.getNamedItem("role")?.value == "button")
            input?.removeAttribute("role");
        });
      }
    });
    const content = this.$root.$el.querySelector(".v-main") as Node;
    callback.observe(content, {
      subtree: true,
      attributes: true,
    });
  },
```

**Comment by apfrod** [comment]
@agreedSkiing I had to use a combination of both to get the elements that were already mutated before mounted happened. Then (when the validator worked) I got an error about div missing the 'role' attribute.

**Comment by agreedSkiing** [comment]
@apfrod We did the same after running the validator again and changed the remove attribute to `input?.setAttribute("role", "listbox");`, but after noticing that NVDA could not read the selected value we swapped over to standard  html selects.

**Comment by apfrod** [comment]
I've ended up with this to swap role=button for role=combobox and remove redundant `aria-readonly`
```javascript
    const removeAriaReadonly = function(input){
      const ariareadonly = input.attributes.getNamedItem("aria-readonly")
      const readonly = input.attributes.getNamedItem("readonly")
      if (ariareadonly && readonly){
        // remove redundant readonly property
        input.removeAttribute("aria-readonly")
      }
    }
    const swapRoles = function(el){
      const role = el.attributes.getNamedItem("role")
      if (role && role.value == 'button'){
        // use role 'combobox' instead of 'button'
        el.setAttribute("role", "combobox")
      }
    }
    // run on each future mutation
    const callback = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        const element = mutation.target
        const inputs = element.querySelectorAll("input")
        inputs.forEach(removeAriaReadonly)
        const inputslots = element.querySelectorAll(".v-select .v-input__slot")
        inputslots.forEach(swapRoles)
      })
    })
    const content = this.$root.$el.querySelector(".v-main")
    callback.observe(content, {
      subtree: true,
      attributes: true,
    })
    // run now on elements already mutated at mount time
    this.$el.querySelectorAll("input").forEach(removeAriaReadonly)
    this.$el.querySelectorAll(".v-select .v-input__slot").forEach(swapRoles)
```
