### ISSUE TITLE
[Bug Report][2.5.8] Deleting chips in select don't move attached menu to resized combobox

### ISSUE THREAD

**Issue by alfiya555** [vuetifyjs/vuetify#14612]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.12
**Browsers:** Chrome 97.0.4692.71
**OS:** Windows 10

### Steps to reproduce
Example is taken from [vuetify documentation](https://vuetifyjs.com/en/components/chips/#filtering), the last after "In select" subheading.

While using "deletable-chips", "clearable" and "attach" attributes in combobox element, and chips span two or more lines:
- clicking the "close" button in chip or "close" button in combobox to delete all chips don't move menu list to the bottom of resized combobox (as it actually works by clicking items in list menu to add/delete chip to combobox)

### Expected Behavior
- clicking the "close" button in chip or "close" button in combobox to delete all chips move menu list to the bottom of resized combobox 

### Actual Behavior
- clicking the "close" button in chip or "close" button in combobox to delete all chips don't 
 move menu list to the bottom of resized combobox (as it actually works by clicking items in list menu to add/delete chip to combobox). It is leaving white space between combobox and items list.

### Reproduction Link
<a href="https://codepen.io/alfiya555/pen/zYEyMMR?editors=1010" target="_blank">https://codepen.io/alfiya555/pen/zYEyMMR?editors=1010</a>

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqNVE1v2zAM/SuCDmsCxDb2AQzIsqI77LwCPQxD3YNsM4lWfUFivBaB//soyU6c9tD6YpMiH98jKd8f+Q/nyv4AfM03CNopgXBdG8Y2fdFa3djGPkWTsb7QtgP1vebtXrpQ8+xeS0oL5E3vyZtD8qcC4UWjIJtKNAnkjz14thW99ZTI9rZpJJzS9UGhdFOK8+DAdIVsraFM3cliKxWCL3rhpTA4pY0mxQSrbPYmMSRnEkc6grK4DqCgRZkQj0wg+rBiUcOK5aPpDR0baj7C5L6QuMmMfWmk6QglYUxUUmtSw4ikOkDkNMLNQ1plw7k38blplWwfT+Hz4Hy0jjkRz4O2PSwi5+U57ESUqAb01uyuj8ckjA3DphpdH0wT3Ld5qBPmeiENdRUCLikwOk6iq6x6amZ1uSrxdNwVclycbkLrpcMUB0/OemQdbAXNlx0zWCdQsMVyMhnzgAdvzva4TWt2f3Xr7c4LraXZXa3Y1a0Sz/TJetmBZTuhIUT3b4GUQX7qDy1VdN0pABezHlZn2LSxEfYOPYgJ9KfAy8AhfwzkGLcTcG87ypxRjqNgeRZz5riXoUz0y+BoerCYeWht4OnXNmet2MflqeJYO7+pPo0jt5GvuJLmMZR/gzV0Z1MpupGBFo+U5LSa7xGpYVXVdoYiaQll70sDWBmnK7rtKLfPN5/LT+WnqpMBJ1dBl5PIRbCI9FCbgQpKHcdWaOFeVM0HqfIoueaEFO03KNxQWOUPBqWGorM6cfnyNZOZ+UsIumi8/RfAE0rNx8akOpHxO2q9JZdKvIKuqF5P/xdPvx26EP69kl6kXch6cfZK2jjqgQ8rnvOo94k0f/gPUfvUaw==
