### ISSUE TITLE
[Bug Report][2.6.2] Hiding v-menu before `close-delay` causes undefined error

### ISSUE THREAD

**Issue by oohira** [vuetifyjs/vuetify#14619]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open Chrome DevTools' Console tab.
1. Click `DROPDOWN` menu button and show menu list.
1. Click `HIDE` button quickly (to keep menu list shown)
1. JS error will occur after 1s.

### Expected Behavior
JS error does not occur.

### Actual Behavior
JS error occurs as following.

```
vuetify.min.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at vuetify.min.js:6:129798
(anonymous)	@	vuetify.min.js:6
setTimeout (async)		
runDelay	@	vuetify.min.js:6
mouseLeaveHandler	@	vuetify.min.js:6
invokeWithErrorHandling	@	vue.js:1872
invoker	@	vue.js:2197
original._wrapper	@	vue.js:7591
```

### Reproduction Link
<a href="https://codepen.io/oohira/pen/dyVavJx" target="_blank">https://codepen.io/oohira/pen/dyVavJx</a>

### Other comments
In my real use case, users navigate to a different page (using Vue Router) when clicking the button . For simplicity, the reproducible example hide the v-menu itself.

**Comment by Sorooshmorshedi** [comment]
<3
