### ISSUE TITLE
[Bug Report][2.6.2] v-switch does not want to reinitialize 

### ISSUE THREAD

**Issue by zekuraz** [vuetifyjs/vuetify#14611]
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.0
**Browsers:** Chrome 97.0.4692.71
**OS:** Linux x86_64

### Steps to reproduce
- open the link
- active console tab
- click in "Switch 1" to set true
- click in "Reset Form"
- See in console ""[Vue warn]: Error in render: 'TypeError: switch1 is null'"

### Expected Behavior
"Switch 1: true" should become 'Switch 1:false" when i click in "Reset Form"

### Actual Behavior
"Switch 1: false" stay "Switch 1: false" when i click in "Reset Form"

### Reproduction Link
<a href="https://codepen.io/zaksil/pen/poWqQmP?editors=1011" target="_blank">https://codepen.io/zaksil/pen/poWqQmP?editors=1011</a>

**Comment by zekuraz** [comment]
I find a temporary solution

`<v-switch
                  v-model="switch1"
                id="defaultSwitch"
      inset
      :false-value="false" 
      :true-value="true"
      :label="`Switch 1: ${switch1.toString()}`"
    ></v-switch>`

`reset () {
       this.$refs.form.inputs.forEach(input => {
        if (input.id != "defaultSwitch") {
          input.reset()
      }})
      
      this.switch1 = false;
    },`

https://codepen.io/zaksil/pen/mdBaapP

**Comment by TheoPez** [comment]
Hi @zekuraz ,

In my opinion the problem you describe does not come from vuetify.
Actually the behavior of your test is distorted by your `toString()`, the form reset will change your value (either true or false) to `null`. So it's the fact of doing a `null.toString()` that causes your code to stop and give the impression that the value is not updated.

I invite you to replace this :
```
:label="`Switch 1: ${switch1.toString()}`"
```
into
```
:label="`Switch 1: ${switch1}`"
```
You can see that the value is reset.

**Comment by lioneaglesolutions** [comment]
Solution to this is mentioned above (https://github.com/vuetifyjs/vuetify/issues/14611#issuecomment-1024638684).

Remove `toString()` or handle the case for `null` in your implementation of the component.
