### ISSUE TITLE
[Vue warn]: Failed to resolve component: v-toolbar-title issue vue3 and vuetify 3.0.0-alpha.0 version

### ISSUE THREAD

**Issue by devendraghag** [vuetifyjs/vuetify#14618]
### Discussed in https://github.com/vuetifyjs/vuetify/discussions/14617

<div type='discussions-op-text'>

<sup>Originally posted by **devendraghag** January 15, 2022</sup>
I am getting below issue while running the sample application with below configuration.

package.json
> "vue": "^3.0.0", 
> "vue-textarea-autosize": "^1.1.1", 
> "vuetify":"^3.0.0-alpha.0"

Main.js
import { createApp } from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify'
import 'vuetify/dist/vuetify.css'
app.use(vuetify).use(VueTextareaAutosize)

Getting below warning and component is not visible. Can anyone help me on this?
![image](https://user-images.githubusercontent.com/31485436/149611661-c3c51494-0ee9-4cf9-b39a-14b845f39c53.png)
</div>

**Comment by anstxy-vi** [comment]
if you use **vite**, need to do in vite.config.js

```
import vuetify from '@vuetify/vite-plugin'
...
plugins: [
   vuetify({
      autoImport: true,
    })
]
...
```
