### ISSUE TITLE
[Documentation] next.vuetifyjs.com - No search bar present

### ISSUE THREAD

**Issue by AnthonyWeston** [vuetifyjs/vuetify#14626]
### Environment

**Browsers:** Firefox 96.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Go to the https://next.vuetifyjs.com/en/
Note - My device is set to Dark Mode

### Expected Behavior
The search bar is present and easily accessible to the user (I am currently seeing the search bar on https://vuetifyjs.com/en/)

### Actual Behavior
The search bar is not present, or possibly it's too difficult to find.

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/" target="_blank">https://next.vuetifyjs.com/en/</a>

**Comment by MajesticPotatoe** [comment]
Algolia only lets us index one site which is the main vuetify.com site, so dev/next will always return the results of the main branch. Theres no plan to fix this as the next site will cease to exist once v3 is released. As the next docs are still in development, we will likely disable the search bar once we finish building out its functionality.
