### ISSUE TITLE
[Bug Report][2.6.2] v-app-bar height regression in 2.6.2

### ISSUE THREAD

**Issue by donalmurtagh** [vuetifyjs/vuetify#14624]
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.71
**OS:** Mac OS 10.15.7

### Description
In Vuetify < 2.6.2, the height of a component with an `app` prop was only taken into consideration when calculating vertical padding for `<v-main>` if the component is visible. 

However, in Vuetify 2.6.2, the height of all such components is used when calculating the vertical padding for `<v-main>`. 

This means that in 2.6.2 the vertical padding for `<v-main>` will be too large if there are invisible app components.

### Steps to Reproduce
Open the app below, notice that the gap above `<v-main>` disappears if you delete the invisible header. This gap will not be present if you run the same app on Vuetify 2.6.1 or earlier

### Expected Behavior
Ignore height of invisible components with an `app` prop

### Actual Behavior
Height of invisible components with an `app` prop is included when calculating vertical padding for `<v-main>`

### Reproduction Link
<a href="https://codepen.io/domurtag147/pen/qBPvyVj" target="_blank">https://codepen.io/domurtag147/pen/qBPvyVj</a>

**Comment by KaelWD** [comment]
That was the bug, only the height of the last one was being used. There was no "if the component is visible" check, it just happened to work for you because they both have the same height. If you use `v-if="$vuetify.breakpoint.mdAndUp"` instead then only the visible one will be used.
