### ISSUE TITLE
[Bug Report][2.5.3] Different input and focus event order for VTextField `type="number"` between Chrome and Firefox

### ISSUE THREAD

**Issue by PremierJoe** [vuetifyjs/vuetify#14623]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.14
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.15.7

### Steps to reproduce
(Chrome 97.0.4692.71, Firefox 96.0.1)
1. Create a `v-text-field` with `type="number"`
2. Click on the up/down arrow while the text field is not focused.
3. On Chrome the `focus` event will be emitted first, followed by the `input` event
4. On Firefox the `input` event is emitted first, and `focus` second

### Expected Behavior
Both Chrome and Firefox should emit `input` and `focus` events in the same order

### Actual Behavior
Chrome and Firefox emit these events in a different order

### Reproduction Link
<a href="https://codepen.io/PremierJoe/pen/gOGEeQZ" target="_blank">https://codepen.io/PremierJoe/pen/gOGEeQZ</a>

**Comment by KaelWD** [comment]
Firefox doesn't focus `<input type="number>` on mousedown, so it's focused later by our click handler instead.
