### ISSUE TITLE
Tabs not position correcly when used with fixed toolbar or navigation drawer

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#1462]
### Steps to reproduce
Use Vuetify v-tabs component together with a fixed toolbar or a navigation drawer: v-tabs is not positioned correctly. Is there any workaround?

### Versions

vue: 2.4.2
vuetify: 0.14.7

### What is expected ?

When using tabs with fixed toolbar inside, I expect the tabs to be fixed too and to sits below the toolbar, but it shows behind the toolbar and there is no "fixed" prop for tabs (actualy there is but has a different meaning). Same happens when using a navigation drawer: it overlaps the tabs bar on the left or right.

### What is actually happening ?

Tabs bar is hidden behind the fixed toolbar and even if fixing the

### Reproduction Link

Fixed toolbar:
https://codepen.io/lucafaggianelli/pen/jLpogJ

Navigation drawer:
https://codepen.io/lucafaggianelli/pen/xLJoKO

Tabs bar is based on docs example # 6

**Comment by jacekkarczmarczyk** [comment]
You have incorrect markup 
https://codepen.io/anon/pen/rzrEje

**Comment by lucafaggianelli** [comment]
Thank you it works, though is not integrated like in example 6 and 7 of the docs https://vuetifyjs.com/components/tabs Well probably playing with CSS I can make it similar, but it seems to me that tabs are not compatible with fixed toolbar

**Comment by johnleider** [comment]
I'm not if this is a bug or a question, quickly looking at the markup it seems a bit weird that the toolbar and the navigation drawer are inside of the tabs component, it's definitely not meant for that.  If you are looking to place tabs into the toolbar, it should be inside of the component.

**Comment by johnleider** [comment]
https://codepen.io/anon/pen/GvBVjV?editors=1010#0

example usage

**Comment by lucafaggianelli** [comment]
Yes I'm not sure myself if question or bug.
Wow thank you, your solution is perfect, just what I was trying to achieve! Anyway consider that the doc states to put the toolbar inside tabs, quite weird to me, if it's not correct please can you update the docs?

**Comment by johnleider** [comment]
I'll take a look at the examples.
