### ISSUE TITLE
[Feature Request] Add additional breakpoints

### ISSUE THREAD

**Issue by sibinx7** [vuetifyjs/vuetify#14635]
### Problem to solve
We use vuetify in our VueJS application. There are lots of responsive issues in our application. So we look into add additional breakpoints like `xxl` or `xxxl` so we can do responsive little better.
Currently between 1264px > < 1904px* and above 1904 we have we have only 2 , like `lg` and `xl`. This will create issues in laptop resolution 1366X768 or 1440X900 resolution. We need to add one more breakpoint between 1264 and 1904

### Proposed solution
Option to add additional breakpoints

**Comment by KaelWD** [comment]
xxl was added in #13318, there are no plans to extend that any further. This will unfortunately not be backported to v2 as it could be a breaking change.
