### ISSUE TITLE
[Bug Report][2.6.2] VDataTable display issues of cells on small viewports (XS)

### ISSUE THREAD

**Issue by maximiliancs** [vuetifyjs/vuetify#14637]
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Safari 15.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a `v-data-table` that makes use of the `item`-slot as seen in the Codepen.
2. View the `v-data-table` in a window with a small viewport (xs – typically a mobile-device).

### Expected Behavior
The cell should use the full width of the `v-data-table` and the border on the bottom would not be to short.

### Actual Behavior
The cell doesn't make use of the full width. Therefore the border on the bottom is only visible until the end of the cell.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/18228028/150589811-e346182d-33ab-4052-9574-62da962a7f05.png">

### Reproduction Link
<a href="https://codepen.io/maximilian_cs/pen/RwLzzWW" target="_blank">https://codepen.io/maximilian_cs/pen/RwLzzWW</a>

### Other comments
The issue seems to be related to #11337 and the fix in https://github.com/vuetifyjs/vuetify/commit/4cc80ca7bea963be875b3ab0f9ba03a8b21c4d92.

**Comment by maximiliancs** [comment]
@KaelWD @nekosaur Are there any updates or maybe an ETA?

**Comment by Vertganti** [comment]
We also encountered this bug with our Vue app on mobile devices. As a temporary workaround we set `mobile-breakpoint="0"` for the affected `v-data-table`s to prevent them from being handled differently on small screen sizes.
