### ISSUE TITLE
Project uses Array.prototype.includes several times which is not supported by Internet Explorer

### ISSUE THREAD

**Issue by narrowtux** [vuetifyjs/vuetify#1463]
According to [MDM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), Array.prototype.includes is not supported by Internet Explorer, however it is used in this project which is said to be IE11 compatible. I have not found a polyfill in the project so I'd ask to either introduce one or replace all occurrences with `array.indexOf(search) >= 0`.

**Comment by johnleider** [comment]
This is covered in the quick-start guide. IE11 requires a polyfill.
If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by narrowtux** [comment]
Ok I somehow missed that section, I only read about how it supports IE11 and then went on using it. I'd suggest to add an asterisk with (with polyfill) behind IE11 to lead people to research about it.

**Comment by johnleider** [comment]
Sounds good
