### ISSUE TITLE
[Feature Request] Selects support in Vuetify 3

### ISSUE THREAD

**Issue by PashaTurok** [vuetifyjs/vuetify#14639]
### Problem to solve
Vuetify 3 alpha can now be tested. However, most of users test it using in some their projects. As Selects are so basic I think that it is necessary to implement selects before many other elements.

### Proposed solution
Select is one of the most used elements. So, I suggest to increase the priority of implementing selects in Vuetify 3.

**Comment by DRoet** [comment]
V-Select is actively being worked on here: https://github.com/vuetifyjs/vuetify/pull/14504

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
