### ISSUE TITLE
v-select can't select item which has `null` value

### ISSUE THREAD

**Issue by icebob** [vuetifyjs/vuetify#1464]
Hi,

I can't select an item in `v-select` where item value is `null`.

Repro: https://codepen.io/icebob/pen/YxjmQb

Try to select the "Auto-detect" item. The `v-select` shows the placeholder text instead of selected text.
Any idea what is the problem?

Thanks!

**Comment by ExCluSiv3** [comment]
NULL is the same as "nothing selected". The Select needs a way to detect if nothing is selected (espacially if you use validation, which you did with adding 'required' to it).

I don't think this behaviour can or even should be changed because logically it's totally correct.

**Comment by johnleider** [comment]
Unfortunately, null and undefined are both treated as non-values. I think that it should stay that way as well, considering it opens up a can of worms for me to say null is acceptable as a value. My recommendation for this situation would be to use an obscure value, such as -1 to differentiate.
