### ISSUE TITLE
[Bug Report][2.6.3] v-carousel-item is hidden on same page route change

### ISSUE THREAD

**Issue by janKollars** [vuetifyjs/vuetify#14647]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 97.0.4692.99
**OS:** Mac OS 10.15.7

### Steps to reproduce
Push a new route (query or hash) which is unrelated to the Carousel.

### Expected Behavior
The Carousel remains as it is.

### Actual Behavior
The active Carousel Item is hidden.

### Reproduction Link
<a href="https://codepen.io/kjan/pen/zYPYgoe" target="_blank">https://codepen.io/kjan/pen/zYPYgoe</a>

### Other comments
It seems to me that the source of the problem is that the variable `isActive` is defined both in `VWindowItem.ts` and `mixins/routable/index.ts`.

The active Carousel Item has the value `isActive` set to `true` (coming from the `VWindowItem`). There, it handles the visibility. The routable mixin, however, uses the same variable for handling if the route corresponds to the link target. When changing the route, the routable mixin's `onRouteChange` sets the variable to `false`.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
