### ISSUE TITLE
[Bug Report][2.5.14] Progress bar is not fixed in v-data-table

### ISSUE THREAD

**Issue by ER-nanako-hirano** [vuetifyjs/vuetify#14646]
### Environment
**Vuetify Version:** 2.5.14
**Vue Version:** 2.6.12
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create an `v-data-table` with the `loading`, the `height` and the `fixed-header`.
The `height` should be smaller than the height of the item to be displayed.

### Expected Behavior
The progress bar would expect to be displayed below the header regardless of the scroll position.

### Actual Behavior
The progress bar moves with scrolling.

### Reproduction Link
<a href="https://codepen.io/er-nanako-hirano/pen/dyZbxOG" target="_blank">https://codepen.io/er-nanako-hirano/pen/dyZbxOG</a>

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3;

https://play.vuetifyjs.com/#eNqlWG1v2zYQ/iucgTXyZskviZNGiLN26bpl7bYAHQYMcT7QEm2zlUiBop16hf/7jhQpiZJcG2i+RLoX8rnnjneUH7/0XmdZsN2QXti7kSTNEizJ7ZwhdLP1YyyxL/EiIX5OxJYIJUdo66c8JklIwT73MyL8DK/IbN7TggciHuB13iuMw5xgEa1BWzyU8jXBMRE5KMxTqSnWTQhbSeUnucTJvZK5FnpJhcrVJRzHlK2Uo9iUMKIE58qDJGSLJeXMH1uVWszf4mSjQmA4LX1ebTJggIQ8Uw7KW63t7IbWhK7WElST0Sj7XIg1fUCgpRMIyxMuQ7nkXBqlUovyWb3FtTfNviSfpb+kJIkt4yU+tKYx8WMiMU1yBJtEZM0TIBEsPmiakTIMggBsbegp9ifwGhOWU7kDQcTTDEdy3ru9Gda3q8MaOri+irKuKItEbYMTLiipODN/9RhcjRvQH5TRdJOiQ+vIXaYzt0kXUKENpRu8q+tgom5wIivwYhMJj84JAv/WEQKNY3aTR4JmRVlEUGUSYOVgKnM0Q4/Ful/sXiqpITp7K/h/hKF/+Woj5NnAai1BIRpPr0vpEssQXQajmplYgM3kopRkgktCWYguamZUcJCcje36e/O/CeZ3kiQ7tCCYdSE5v5q6SEZtJNcdSOpmBsnoGJJ3VL7DnXxMxy9dFJMOQi4rpCWMqyaIy2MgfoGKo6ILxORy4oIYd2XlvA2ibmZgXB2D8Su0QCIWAlprZ1qml8exXFRFVGI5DyqhrZCjnNxHBEUAJUU5ZvEzjdad/JxXbGtM121INZNa0VacnVq073mS0IxnndxcN/I0CiqBLdmqnqqSbaKYHENxt8ki/Il0ghg1zs15UIVuC/Y0Ml4eg/EbZ2QHLXDRBeRi1Dg65202XnYAuQyqAAyQi+kxJG8423Qe4ItpIyeTabs4puMuPlr1Omnk5WnOqub7FvLx+uEeeq/BhvMdi9CSSJip3hekbjoDfWWwF50ByrmQP+/gfzF59/0qLkHkRjDEyDN6EDylOfEEyXmyJWh2W5kh8JV/05TwjfS8fkNnseUSCwnIPAUC+WjcRz84UNouhMXgUDj+eMRWa8Hazp8gT2hEvH6wpIkkwlP6FjJgdYm8IvJAZRG9eIG+U6b6LZD8PX8m4g5D5P2AsijZwPp1B9ekXyPP/hkSlzjJHdiQwCJ11d9wiAjAZtKPaa6nLlMDHCQE0sSw+JgPM0GWcGfNoUOCfsF5ArPLLzY5GJotRR2epqIS3c7Qn/ry0TT+1miMqb7H1hT7vmuoYeoaDIpLc2tXUz9g847sVEFo68fRU/CJ7A6Z/iXg/uUYcyVpUKSKJlAmnocHaNGu3WpR/I+6ZMOK+NFAgaPXZbiwhouDhoaaGs7ZDJ1BaUVn6Ce7gG+3DO2Db1QN4oHQg2koIMGRowxubOo4mZj16dBHa6DOWSMp5phDy9DmYbXCAOkvmtCsU6TMwbAfoOloVAqsqmhXBh75nEHscFiXeJNIS7m6boao6CBemYb6uYc2WTZE8+EV2num05L11ZrKRPfloiUgbzwaraBXiS0cnn7VqHWjTOhKtVfNiKtSWVKHMSyq3tFBAYKTagR1HzsgNKISxp05V2cD42YPGgjs9pCJswPubzFEoGAbbxgkpzneqfniuOqJc5oz9H01ihx3M55OW+Aexhbyvq+81Rw77PpUPtW+jiHFldx8IYe6sZTS6jO7fpUxg7lrJteERd+rifZ98/CMYXCG7qBX9VkrM7mmcJqK2TlDH6QAbN4bOCkB488wEcpj0MLwjQvZ/ymRax5DROVa5Xf+10e+M+rN/oZcAOC2bXOxCPRN4qSLBOAx9OuF1eOgRr8WlkzsAUsg14R5tuOYNqMwNluyIaqsDtvTWjZVTah41EvLpIq3MdGqhubyDf3rZmg+enuDHozmT3nwEYYz/AKlUcLneA4f+WVXgh+IpMzycDiMYgaW8KsC3YqAETlkWTqE364kXe5ewb00mAxh7Esr8hO8AIrUYuaet4cNaaoap5/irLFrodA7G7bmPVhJvR+B8ArMhmLDJNzg/JinGsvFVQGmJg9InvoLwZ+Be1hl3jPE6H0U4hP2OhYubNFaeljkGu44DPq9+pHktJAabk5YDV0rNJPqfW8/6BV+wL0G3Xv6H/WG9kU=
