### ISSUE TITLE
[Bug Report][2.6.3] Hydration error when buttons are inside of expansion panel headers

### ISSUE THREAD

**Issue by wesley-spencer** [vuetifyjs/vuetify#14650]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 97.0.4692.99
**OS:** Windows 10

### Steps to reproduce
Not sure is error will produce in codepen. Navigate to code and refresh page

### Expected Behavior
display button in expansion header without throwing an error

### Actual Behavior
display button in expansion with error

### Reproduction Link
<a href="https://codepen.io/wes3295/pen/ZEaYpxm" target="_blank">https://codepen.io/wes3295/pen/ZEaYpxm</a>

### Other comments
Not sure what the cause is, but keep getting hydration errors when placing buttons inside expansion panel headers. I took the button out of the header and now it works fine with no errors.

![image](https://user-images.githubusercontent.com/94924647/151213947-f50054be-3c67-4a09-bc22-5e3b81351c72.png)

**Comment by jacekkarczmarczyk** [comment]
`v-expansion-panel-header` renders a `<button>`, you can't have button insider another button
