### ISSUE TITLE
v-select "selection" slot.

### ISSUE THREAD

**Issue by azampagl** [vuetifyjs/vuetify#1465]
The "selection" slot of v-select seems to no longer be respected in v0.14.11, even though it is in the documentation. 

    <template slot="selection" scope="data">
 
It was functional in 14.08. Checking the source there only seems to be a "label" slot now?

Not sure if bug or documentation error - either way select fields no longer render complex types for the "selection".

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
