### ISSUE TITLE
[Documentation] Incoherence in v-data-table API Documentation

### ISSUE THREAD

**Issue by hzd-artur** [vuetifyjs/vuetify#14652]
### Environment

**Browsers:** Opera 82.0.4227.58, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Go to headers in data-table API
Look at the align properties

### Expected Behavior
align?: 'left' | 'center' | 'right',

### Actual Behavior
align?: 'start' | 'center' | 'end',

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-data-table/#props" target="_blank">https://vuetifyjs.com/en/api/v-data-table/#props</a>

**Comment by MajesticPotatoe** [comment]
duplicate #14236

**Comment by scscgit** [comment]
@MajesticPotatoe and yet it should be reopened.

Current workaround for TS when using DataTableHeader:
> `align: 'right' as 'end'`
