### ISSUE TITLE
[Bug Report][2.6.3] v-virtual-scroll can not render an unlimited amount of items as was declared

### ISSUE THREAD

**Issue by aidar87** [vuetifyjs/vuetify#14669]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.99
**OS:** Windows 10

### Steps to reproduce
the code was taken from https://vuetifyjs.com/en/components/virtual-scroller/#bench
I only changed length to 700000  but I can scroll only to 524288 item

### Expected Behavior
able to scroll to the last item

### Actual Behavior
not able to scroll to last item

### Reproduction Link
<a href="https://codepen.io/aidar87/pen/KKyVpvR?editors=101" target="_blank">https://codepen.io/aidar87/pen/KKyVpvR?editors=101</a>

**Comment by KaelWD** [comment]
This is a browser limitation. `el.style.height` is correctly set to `4.48e+07px` but `getComputedStyle(el).height` is only returning `3.35544e+07px`
