### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-btn `to` and `text` not works properly 

### ISSUE THREAD

**Issue by yaquawa** [vuetifyjs/vuetify#14663]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.29
**Browsers:** Chrome 97.0.4692.99
**OS:** Mac OS 10.15.7

### Steps to reproduce
```vue
<v-btn text to="/">
  Button
</v-btn>
```

### Expected Behavior
x

### Actual Behavior
* text disappears if use `to`
* `text` not take effect

### Reproduction Link
<a href="https://codepen.io/yaquawa/pen/ExbjJdG?editors=101" target="_blank">https://codepen.io/yaquawa/pen/ExbjJdG?editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Don't you need to add and configure vue-router?

**Comment by yaquawa** [comment]
@jacekkarczmarczyk I've been using vue-router in my local project, the same problem comes up.

**Comment by KaelWD** [comment]
`text` is a property on [HTMLAnchorElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement#:~:text=HTMLAnchorElement.text)

If you want to use the text variant it's now `variant="text"`
