### ISSUE TITLE
[Bug Report][2.6.3] v-virtual-scroll is not reactive when editing items

### ISSUE THREAD

**Issue by aidar87** [vuetifyjs/vuetify#14673]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.99
**OS:** Windows 10

### Steps to reproduce
click div named "click here for append"

### Expected Behavior
items changed and showed reactively

### Actual Behavior
items changed but not showed reactively

### Reproduction Link
<a href="https://codepen.io/aidar87/pen/rNYxWwQ?editors=1010" target="_blank">https://codepen.io/aidar87/pen/rNYxWwQ?editors=1010</a>

**Comment by KaelWD** [comment]
Computed properties can't be mutated.
