### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] vuetify+vite+typescript.  error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

### ISSUE THREAD

**Issue by titou10titou10** [vuetifyjs/vuetify#14671]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.25
**Browsers:** Firefox 96.0 (irrelevant)
**OS:** Windows 10

### Steps to reproduce
Create a new project with vite+typescript (v2.7.2) and the`"vue-ts"` vite template:

    npm init vite@latest xxxxxx -- --template vue-ts
    cd xxxxxx 
    npm install vuetify@next
    npm install -D @vuetify/vite-plugin

**main.ts:**

    import { createApp } from 'vue'
    import App from './App.vue'
    import { createVuetify } from 'vuetify'
    
    const vuetify =  createVuetify()
    const app = createApp(App)
    app.use(vuetify)
    app.mount('#app')
   
**Build for poduction with vite:**

    npm run build
    > xxxxxx@0.0.0 build
    > vue-tsc --noEmit && vite build
	node_modules/vuetify/lib/index.d.ts:1:23 - error TS2305: Module '"vue"' has no exported member 'JSXComponent'.
    1 import { ToRefs, Ref, JSXComponent, App } from 'vue';
                            ~~~~~~~~~~~~
    Found 1 error.

### Expected Behavior
"npm run build" works on vue+vite+typescript project

### Actual Behavior
npm run build fails with the described error

### Reproduction Link  (irrelevant)
<a href="https://codesandbox.io/s/vue" target="_blank">https://codesandbox.io/s/vue</a>


<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by KaelWD** [comment]
Fixed by 0e7e99bb27652766198a1ce5db51d1165d9d2a2a
