### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] V-List-Group Not Working

### ISSUE THREAD

**Issue by YangHanlin** [vuetifyjs/vuetify#14679]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.29
**Browsers:** Firefox 97.0
**OS:** Windows 10

### Steps to reproduce
1. Clone repo;
2. `yarn install && yarn serve`;
3. Open application in browser.

### Expected Behavior
List sub-groups are rendered, as is shown in [the official example](https://next.vuetifyjs.com/en/components/lists#sub-group) (`Sub group` section)

### Actual Behavior
Sub-groups are not rendered.

### Reproduction Link
<a href="https://github.com/YangHanlin/vuetify-list-group-issue" target="_blank">https://github.com/YangHanlin/vuetify-list-group-issue</a>

### Other comments
The component used (`src/components/HelloWorld.vue`) in the reproduction link comes from [the official example](https://next.vuetifyjs.com/en/components/lists#sub-group) (`Sub group` section), so it seems weird that this component produces different behavior with the example on official document site.

**Comment by KaelWD** [comment]
The examples are using [nightly builds](https://vuetifyjs.com/en/getting-started/installation/#nightly-builds)
