### ISSUE TITLE
[Feature Request] Add support for fixed input labels

### ISSUE THREAD

**Issue by tihomir-kit** [vuetifyjs/vuetify#14677]
### Problem to solve
Fix the label so that it doesn't go down to the input field, becoming a placeholder. `persistent-placeholder` and `persistent-hint` already exist but `persistent-label` or `fixed-label` doesn't. 

I tried implementing a custom workaround to pin the label to the top of the field, but I couldn't do it in a reasonably easy way. It's simply not easy enough to target the label using css or even by setting a simple component property.

This was asked for in #5753, but the official reply was that `persistent-placeholder` was implemented and the issue was closed. But the issue wasn't about placeholders, it was about labels, which are two separate things. It's just that someone else in the thread brought up placeholders. So I'm creating a new issue.

### Proposed solution
Add `persistent-label` or `fixed-label` to input fields.

**Comment by KaelWD** [comment]
Did you try it? https://codepen.io/kaelwd/pen/mdqPpqa

**Comment by tihomir-kit** [comment]
Thanks for the reply. I actually did (today at work) and it didn't fix it to the top. I'll check tomorrow again and see if any other set properties might be interfering and come back with whatever I find out.

**Comment by tihomir-kit** [comment]
Hm, I tried this out now but it's not working. I realized however that I'm on Vuetify 2.4.0, so perhaps that's the problem, I'll see if I can bump it up, and that might solve it. I'll get back once I do that.

**Comment by KaelWD** [comment]
Yes, it was added in 2.5.0
