### ISSUE TITLE
[Feature Request] Missing v-text-field outlined active label transform SCSS variable

### ISSUE THREAD

**Issue by desiboli** [vuetifyjs/vuetify#14670]
### Problem to solve
The possibility to override the transformation of the active label on outlined v-text-field.

### Proposed solution
Add something like this:
$text-field-outlined-label-active-transform: translateY(-18px) scale(.75) !default;

**Comment by KaelWD** [comment]
Outlined fields use `$text-field-outlined-label-position-x` and `$text-field-outlined-label-position-y` instead.

**Comment by harentius** [comment]
$text-field-outlined-label-position-x works not as expected.
It adds 'top' value.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTextField/VTextField.sass#L390
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTextField/_mixins.sass#L13
