### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-text-field details are not showing correctly.

### ISSUE THREAD

**Issue by ammar-oker** [vuetifyjs/vuetify#14694]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Last working version:** 3.0.0-alpha.12
**Vue Version:** 3.2.29
**Browsers:** Chrome 97.0.4692.99
**OS:** Mac OS 10.15.7

### Steps to reproduce
* **Case 1**: Add `hint` prop to the `v-text-field` component.
* **Case 2**: Add `error` & `error-messages` props to the `v-text-field` component.
* **Case 3**: Add `hide-details` prop to the `v-text-field` component.

### Expected Behavior
* **Case 1**: We should see a hint text below the text field.
* **Case 2**: We should see an error message below the text field.
* **Case 3**: The area reserved for details below the text field should be hidden.

### Actual Behavior
* **Case 1**: The hint message below the text field is not showing.
* **Case 2**: The error message below the text field is not showing.
* **Case 3**: The area reserved for details below the text field is NOT hidden.

### Reproduction Link
<a href="https://codepen.io/ammar_oker/pen/VwrmMGE" target="_blank">https://codepen.io/ammar_oker/pen/VwrmMGE</a>

### Other comments
Github repo: https://github.com/ammar-oker/vuetify-VTextField-issue-reproduction

**Comment by KaelWD** [comment]
1 and 3 have been fixed already: https://codepen.io/kaelwd/pen/QWOGqXK?editors=1010

2 is because `props.errorMessages` isn't actually being used @johnleider 
https://github.com/vuetifyjs/vuetify/blob/23137bad86b9d77adcd88f4daaef6a8fc3659453/packages/vuetify/src/composables/validation.ts#L57

**Comment by ammar-oker** [comment]
Thanks for the ultra-fast response ⚡
regarding the 2nd case, it's working fine on the documentation website at the Password Input example 🤔 https://next.vuetifyjs.com/en/components/text-fields/#password-input

**Comment by KaelWD** [comment]
The documentation example is using `hint` instead of `errorMessages`
