### ISSUE TITLE
[Bug Report][2.6.1] Focus event of v-text-field is fired at icon slot clicked

### ISSUE THREAD

**Issue by k-fukuoka** [vuetifyjs/vuetify#14708]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 98.0.4758.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click "MENU" > "CLICK ME".
1. Click Vuetify icon.

### Expected Behavior
No change.

### Actual Behavior
Since readonly is true it is not visible, but the focus is on the end of the text and text is displayed as if it is right-aligned.

### Reproduction Link
<a href="https://codepen.io/k-fukuoka/pen/MWOmbgZ" target="_blank">https://codepen.io/k-fukuoka/pen/MWOmbgZ</a>

**Comment by KaelWD** [comment]
`<input readonly>` can also be focused.

**Comment by k-fukuoka** [comment]
@KaelWD 

Thanks for the answer. 

However, I think I asked the wrong question and it's not the answer I want.

It is not intuitive to focus on the text because vuetify icon at append-inner is supposed to be clicked.
