### ISSUE TITLE
[Documentation] Deprecated components

### ISSUE THREAD

**Issue by alexandrmiee** [vuetifyjs/vuetify#14705]
### Problem to solve
How to migrate deprecated components.

### Proposed solution
There are some components was removed. So we need document how to replace them.

List of components:
- VFlex
- VBtnToggle
- VListTile
- VListTileTitle
- VToolbar
- VToolbarItems
- VExpansionPanelContent
- VSelect
- VAutocomplete

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/upgrade-guide/

**Comment by alexandrmiee** [comment]
I don't see mentioned components

**Comment by KaelWD** [comment]
Most of those aren't deprecated.

**Comment by alexandrmiee** [comment]
I've installed `3.0.0-alpha.0`
And I don't see these components in `vuetify/components`
![image](https://user-images.githubusercontent.com/8451506/153167526-4aa5f140-6373-4ddb-b476-c6c26b956939.png)

**Comment by KaelWD** [comment]
[Nightly builds](https://vuetifyjs.com/en/getting-started/installation/#nightly-builds) have more. Alpha means it's still in progress, there will be a full upgrade guide with the final release.
