### ISSUE TITLE
[Bug Report][2.6.11] v-treeview - reactivity and re-render issue - have to maintain custom key

### ISSUE THREAD

**Issue by Tomanoczy** [vuetifyjs/vuetify#14700]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 97.0.4692.99
**OS:** Mac OS 10.15.7

### Steps to reproduce
v-model is provided
items are loaded dynamically
props: return-object and selectable

### Expected Behavior
treeview should mark items from v-model as checked

### Actual Behavior
After initial load of component and async loaded items v-model is not applied and items are not checked.

I have to manually change :key property for treeview so the component can react to this change.

see line 41 in codepen:
this.key += 1; // HERE ===> Why should I manually maintain key to make treeview re-render ??

...if you comment this out, it stops working and items from v-model are not checked on page load.

### Reproduction Link
<a href="https://codepen.io/michal-tomanoczy/pen/oNoBMrK" target="_blank">https://codepen.io/michal-tomanoczy/pen/oNoBMrK</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
