### ISSUE TITLE
[Bug Report][2.6.3] VListGroup value is wrong when adding item with unshift

### ISSUE THREAD

**Issue by ivaneliasoo** [vuetifyjs/vuetify#14714]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Edge 98.0.1108.50, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Click plus sign to unshift an item in the array then select the new item in the list

### Expected Behavior
To return the actual index synced with the array

### Actual Behavior
v-model is returning: length - 1 instead of 0. 

### Reproduction Link
<a href="https://github.com/ivaneliasoo/listvuetifybugindex" target="_blank">https://github.com/ivaneliasoo/listvuetifybugindex</a>

### Other comments
Hi, I have the idea that this was working previously in 2.5.

**Comment by KaelWD** [comment]
Dynamic items need an explicit value: 

```
<template v-for="(item, i) in operationalReadingConfiguration">
  <v-list-item :key="`item-${item.FieldName}`" :value="i">
```
