### ISSUE TITLE
[Bug Report][2.6.1] v-text-field is focused at icon slot clicked

### ISSUE THREAD

**Issue by k-fukuoka** [vuetifyjs/vuetify#14718]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 98.0.4758.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click Vuetify icon.

### Expected Behavior
No change.

### Actual Behavior
When I click on the vuetify icon, the cursor appears at the end of the text.

I click on the append inner "icon", but it is not intuitive that the cursor appears on the "text".

Is this a specification?

 In addition, when I set v-text-field to readonly and click on the icon, the cursor does not appear at the text and the text appears to be right-aligned.

I just clicked on the icon, but the text is right-aligned, which is an unintended behavior.

### Reproduction Link
<a href="https://codepen.io/k-fukuoka/pen/MWOmbgZ" target="_blank">https://codepen.io/k-fukuoka/pen/MWOmbgZ</a>

**Comment by KaelWD** [comment]
You can add `@mouseup.stop @click.stop` to the element in the slot to prevent this behaviour.
