### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Vuetify Renders But With Path Errors

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuetifyjs/vuetify#14712]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.30
**Browsers:** Chrome 98.0.4758.82
**OS:** Windows 11 Home 10.0.22000 Build 22000

### Steps to reproduce
Installed vuetify as per the docs.
Imported vuetify as per the docs.
Executed yarn run serve.

### Expected Behavior
Seeing the `<v-btn>` with `color="primary" `and text `SIGN IN` and no errors.

### Actual Behavior
The `<v-btn>` was missing the style, only contained the text, as if the element didn't exist and only its inner HTML was shown, so I researched a fix, and imported directives and components from `vuetify/lib`.
App compiled, vuetify button was rendered successfully with the primary color, but in the browser I get an error about those paths not existing.

### Reproduction Link
<a href="https://github.com/angelhdzmultimedia/vuetify_error" target="_blank">https://github.com/angelhdzmultimedia/vuetify_error</a>

### Other comments

Screenshot:
![chrome_eMq0N7s9ZF](https://user-images.githubusercontent.com/10191085/153700081-ff172b23-4dff-4002-affb-068c1551b888.png)

**Comment by angelhdzmultimedia** [comment]
### Update
As per the docs, I went to install vuetify 3.0.0-alpha-12 with Vite with the command `yarn create @vitejs/app my-app --template vue-ts` and it failed the first time, so then I proceeded and installed with Vue CLI instead with command `vue create my-app` and `vue add vuetify@next`. And this way I got the errors mentioned in my original message.

After submitting the Issue, I tried  `yarn create @vitejs/app my-app --template vue` again and it worked, I received the 

```
? Choose a preset:
  Configure (advanced)
  Default (recommended)
  Vite Preview (Vuetify 3 + Vite)
  Prototype (rapid development)
❯ Vuetify 3 Preview (Vuetify 3)
```

Screen and choose   `Vite Preview (Vuetify 3 + Vite)`.

Everything went smooth. I then ran yarn run dev, opened the development server's link in Chrome, and I got a blank
screen with the following error in the console:

![image](https://user-images.githubusercontent.com/10191085/153730053-e4b0420c-b60a-4064-a404-fe7be5f5a0bb.png)



This is the package.json of this current project:

```
{
  "name": "my-app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "serve": "vite preview",
    "build": "vite build",
    "dev": "vite",
    "preview": "vite preview"
  },
  "dependencies": {
    "@mdi/font": "5.9.55",

    "roboto-fontface": "*",
    "vue": "^3.2.25",
    "vuetify": "3.0.0-alpha.12",

    "webpack-env-plugin": "^0.0.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/cli-plugin-babel": "5.0.0-beta.7",
    "@vue/cli-service": "5.0.0-beta.7",
    "@vuetify/vite-plugin": "^1.0.0-alpha.3",
    "sass": "^1.38.0",
    "sass-loader": "^10.0.0",
    "typescript": "^4.5.4",
    "vite": "^2.8.0",
    "vue-cli-plugin-vuetify": "^2.4.5",
    "vue-tsc": "^0.29.8",
    "vuetify-loader": "^2.0.0-alpha.0"
  }
}

```

**Comment by nekosaur** [comment]
It looks like our vue-cli plugin needs to be updated.

For the non-vite setup, main file needs updated imports like this

```js
import 'vuetify/styles'
import * as directives from 'vuetify/directives'
import * as components from 'vuetify/components'
```

For the vite setup, the reason it's complaining about not finding `main.js` is because you chose `vue-ts` as template, which means you will have a `main.ts` file. But the vuetify plugin assumes that you have a non-ts setup and so will reference `main.js` in `public.html`

**Comment by angelhdzmultimedia** [comment]
> It looks like our vue-cli plugin needs to be updated.
> 
> For the non-vite setup, main file needs updated imports like this
> 
> ```js
> import 'vuetify/styles'
> import * as directives from 'vuetify/directives'
> import * as components from 'vuetify/components'
> ```
> 
> For the vite setup, the reason it's complaining about not finding `main.js` is because you chose `vue-ts` as template, which means you will have a `main.ts` file. But the vuetify plugin assumes that you have a non-ts setup and so will reference `main.js` in `public.html`

Thank you so much for taking of your time to reply and to try help me solve this issue.

I don't have a main.js. In both projects, I only have main.ts. Now I realized that error is coming from the compiled main.js of TypeScript when it runs on the browser. 

I tried something now:
I removed all dependencies. Uninstalled them, one by one with yarn remove.

Then, I started installing them with yarn add, adding the @next at the end to ensure latest versions.

The error persists.

**Comment by angelhdzmultimedia** [comment]
### Update
I don't know if this is relevant but I'm on Node **16.13.2**. I'm gonna try Node **17.5.0** to see if that solves it.

**Comment by angelhdzmultimedia** [comment]
> ### Update
> I don't know if this is relevant but I'm on Node **16.13.2**. I'm gonna try Node **17.5.0** to see if that solves it.

Nope. Didn't solve it.

**Comment by angelhdzmultimedia** [comment]
### Solved?
I executed npm init @vitejs/app my-app -- --template vue-ts instead of yarn create @vitejs/app my-app --template vue-ts this time, and it compiled and it's running without issues.
![image](https://user-images.githubusercontent.com/10191085/153731289-1b1a5327-8c10-4ad0-a8f5-2530f9f60836.png)

I'm gonna try with yarn again, to see if that's what's causing the issue, or to see if changing from Node 16 to Node 17 was what fixed it.

**Comment by angelhdzmultimedia** [comment]
### Solved
Solution was upgrading Node from **16.13.2** to **17.4.0**.
I had both versions installed with nvm, but I downgraded to 16.13.2 to help someone recently and forgot to change back.

**No I can finally try Vuetify 3!!!** 

Thank you everyone concerned.
