### ISSUE TITLE
[Bug Report][2.5.10] v-date-picker throws error when date is set to "0001-01-01" and clicking on header to navigate to months and years

### ISSUE THREAD

**Issue by VindyaKaruturi** [vuetifyjs/vuetify#14724]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 98.0.4758.82
**OS:** Windows 10

### Steps to reproduce
vuetify date picker change the selected date to "0001-01-01"  when you click on headers for changing months and years, when it reach to years section throws error

### Expected Behavior
should display year dropdown to select

### Actual Behavior
it is breaking on click to show year dropdown.

### Reproduction Link
<a href="https://codepen.io/Vindya/pen/gOXGoNY?editors=101" target="_blank">https://codepen.io/Vindya/pen/gOXGoNY?editors=101</a>

**Comment by KaelWD** [comment]
Related: #7401

`-13` is interpreted as `0000-13-01`

**Comment by VindyaKaruturi** [comment]
Should stop at 1. It should show years dropdown  normally as how it shows for the years
