### ISSUE TITLE
[Bug Report][2.6.3] v-virtual-scroll items are not visible inside v-dialog on the second opening 

### ISSUE THREAD

**Issue by KevinFabre** [vuetifyjs/vuetify#14722]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 97.0
**OS:** Windows 10

### Steps to reproduce
    1. Open the dialog (Items are visible)
    2. Scroll a bit
    3. Close the dialog
    4. Open the dialog (Items are no longer visible)

### Expected Behavior
Items should be visible

### Actual Behavior
Items are not visible

### Reproduction Link
<a href="https://codepen.io/KevinFabre/pen/zYPEGMX?editors=1010" target="_blank">https://codepen.io/KevinFabre/pen/zYPEGMX?editors=1010</a>

### Other comments
has workaround, key binded to dialog in v-virtual-scroll

**Comment by shadow-light** [comment]
Just a note that I couldn't reproduce this on Chrome 100 but could reproduce it in Firefox 99.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
