### ISSUE TITLE
[Bug Report][2.6.3] v-select does not update v-model when element removed from items

### ISSUE THREAD

**Issue by Feelixe-tin** [vuetifyjs/vuetify#14721]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 98.0.4758.82
**OS:** Windows 10

### Steps to reproduce
Click "Remove Foo" button to remove from element from items array.

### Expected Behavior
`selected` to be changed to null or undefined

### Actual Behavior
`selected` is unchanged as "Foo"

### Reproduction Link
<a href="https://codepen.io/feelixe/pen/RwjZzEM?editors=1010" target="_blank">https://codepen.io/feelixe/pen/RwjZzEM?editors=1010</a>

**Comment by KaelWD** [comment]
Related: #4000

If this was behaviour was changed it would probably be the other way around.

**Comment by syuu3** [comment]
#4000 has been solved with cache-items, but this problem has not been solved yet.
