### ISSUE TITLE
disabled label color in text field doesn't match MD guidelines

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1472]
Label/value color in disabled text field has 70% white in dark theme and 54% white in light theme, according to MD guidelines it should be respectively 50% and 42%

MD guidelines: https://material.io/guidelines/components/text-fields.html#text-fields-states
Codepen: https://codepen.io/anon/pen/OjogjB

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/1474

**Comment by johnleider** [comment]
Fixed with #1474
