### ISSUE TITLE
[Bug Report][2.6.3] DataTable SortDesc MultiSort

### ISSUE THREAD

**Issue by kvpt** [vuetifyjs/vuetify#14730]
### Environment
**Vuetify Version:** 2.6.3
**Last working version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4800.0
**OS:** Windows 10

### Steps to reproduce
Click on a sortable column then a second one

### Expected Behavior
SortDesc array and SortBy array are of the same size.
There is now always a false boolean in the array that add with the others boolean.
Result of the compare is in the console.

### Actual Behavior
SortDesc array have one more element than SortBy array.

### Reproduction Link
<a href="https://codepen.io/kvpt/pen/poddQNK" target="_blank">https://codepen.io/kvpt/pen/poddQNK</a>

### Other comments
It seems to have been introduced by this commit :
https://github.com/vuetifyjs/vuetify/commit/9cf48e45beef9eef109c50b8f05a6a6a98418b19
Also reported here : 
https://github.com/vuetifyjs/vuetify/issues/14423#issuecomment-1028125833

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Comment by azaricstefan** [comment]
But this is not stale, it is still the case... (tested in v2.6.16)
