### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-radio-group:   "row" attribute not working

### ISSUE THREAD

**Issue by vneznaikin** [vuetifyjs/vuetify#14739]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.102
**OS:** Windows 10

### Steps to reproduce
Just check it

### Expected Behavior
inline direction

### Actual Behavior
not working

### Reproduction Link
<a href="https://codepen.io/gradopetr/pen/dyZdXOB" target="_blank">https://codepen.io/gradopetr/pen/dyZdXOB</a>

**Comment by KaelWD** [comment]
Looks like it's renamed to `inline`

**Comment by soichiro-niwa** [comment]
Why is 'row' not working? Could you tell me some documents that explain the question?🥲
