### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-file-input: text is out of bounds of chips, no text ellipsis for labels

### ISSUE THREAD

**Issue by vneznaikin** [vuetifyjs/vuetify#14734]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.102
**OS:** Windows 10

### Steps to reproduce
Select few files with long names when file field in small column

### Expected Behavior
text of chips must intervene within the boundaries

### Actual Behavior
text is out of bounds of chips

### Reproduction Link
<a href="https://codepen.io/gradopetr/pen/KKyZNMz" target="_blank">https://codepen.io/gradopetr/pen/KKyZNMz</a>

### Other comments
And I noticed "hide-details" not working too

**Comment by subdavis** [comment]
I've just noticed that `hide-details` is not working for any input type I've tried.

**Comment by johnleider** [comment]
fixed by [94049b1](https://github.com/vuetifyjs/vuetify/commit/94049b1daa8a1fe46f824c2dc4321188ed6af723)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
