### ISSUE TITLE
[Documentation] Vuetify 3 Vite Documentation doesn't mention necessary manual CSS import

### ISSUE THREAD

**Issue by subdavis** [vuetifyjs/vuetify#14738]
### Environment

**Browsers:** Chrome 97.0.4692.99
**OS:** Linux x86_64

### Steps to reproduce
Using Vite with Vuetify 3, I must manually import styles in order to prevent strange style behaviors.

```
import 'vuetify/styles';
```

This line doesn't appear anywhere in the docs, but I found it in this third party example: https://github.com/yooneskh/vite-tauri-template/blob/master/src/plugins/vuetify.js

### Expected Behavior
Explain all necessary code to set up a project with Vuetify

### Actual Behavior
critical documentation missing.

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/getting-started/installation" target="_blank">https://next.vuetifyjs.com/en/getting-started/installation</a>

**Comment by rmortes** [comment]
That info is now appearing in [the installation page of the docs](https://next.vuetifyjs.com/en/getting-started/installation#usage)
