### ISSUE TITLE
[Bug Report][2.6.3] datepicker inaccessible keyboard / assistive tech browser/os agnostic

### ISSUE THREAD

**Issue by jsdev** [vuetifyjs/vuetify#14732]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.13
**Browsers:** Edge 96.0.1054.57
**OS:** Windows 10, Mac OSX, iOS, Android, Windows, Linux

### Steps to reproduce
try to type in the date in the textbox, you cannot. 
try to launch datepicker with keyboard, you cannot.

### Expected Behavior
that someone not using a mouse of finger/touch should be able to enter in date and or launch the datepicker, keyboard / assistive technology users can do neither

### Actual Behavior
can only enter a date using the date picker
can not launch the date picker without click/touch, enter or focus doesn't having the calendar

### Reproduction Link
<a href="https://codepen.io/jsdev/pen/BamJypO" target="_blank">https://codepen.io/jsdev/pen/BamJypO</a>

**Comment by jacekkarczmarczyk** [comment]
1. Your v-text-field is marked as readonly
2. You'd also need to add some logic for validating typed date (which may depend on the format of the date you accept)
3. There's already https://github.com/vuetifyjs/vuetify/issues/11114 and https://github.com/vuetifyjs/vuetify/pull/14135

**Comment by maxshuty** [comment]
@jsdev I spent some time spinning my wheels on this one as well. 

If you add the [**`attach`**](https://vuetify.cn/en/components/menus/) prop to the `v-menu` and then add `keydown.enter="menu + !menu"` to the input then you can open the date picker through the keyboard and navigate the date picker through the keyboard as well.

[Here is a working fiddle](https://codepen.io/maxshuty/pen/vYzXPvb).

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
