### ISSUE TITLE
[Bug Report][2.4.3] v-tabs hover background colour is set to light blue by default in mobile devices and desktop, not able to override the same with background color to white 

### ISSUE THREAD

**Issue by kishan-buku** [vuetifyjs/vuetify#14756]
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 98.0.4758.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
check on the fiddle browser, white colour is not applying on hover

### Expected Behavior
white colour should apply on hover to the tabs background

### Actual Behavior
light blue colour is applied on hover to the tabs background

### Reproduction Link
<a href="https://codesandbox.io/s/stupefied-pike-kp3ru?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/stupefied-pike-kp3ru?file=/src/components/HelloWorld.vue</a>

**Comment by KaelWD** [comment]
> white colour should apply on hover

why?

**Comment by kishan-buku** [comment]
> > white colour should apply on hover
> 
> why?

@KaelWD in some of the use cases, we don't want to show any background colour on hover, for that when i tried to give colour code of #FFFFFF it doesn't reflect on the UI.

**Comment by KaelWD** [comment]
1. You haven't shown what you're actually trying to do in the reproduction link then, there's no #FFFFFF anywhere
2. The hover effect is on `.v-tab::before`
