### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-item don't append selectedClass when active, just from v-item-group if prop dont set `null`

### ISSUE THREAD

**Issue by RuslanMelnychenko** [vuetifyjs/vuetify#14754]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.0.0-alpha.12
**Browsers:** Chrome 98.0.4758.102
**OS:** Windows 10

### Steps to reproduce
1. Create `v-item-group` with some children `v-item`
2. Set prop `selectedClass` with some class in `v-item`
3. Activated some `v-item`

### Expected Behavior
To `v-item` add class from prop `selectedClass` from `v-item-group` (default `v-item--selected`) and add class from prop `selectedClass` from this `v-item`.

### Actual Behavior
If in `v-item-group` dont set `null` in `selectedClass` then add class just from `v-item-group`, else add class from `selectedClass` from this `v-item`.

### Reproduction Link
<a href="https://codepen.io/ruslanmelnychenko/pen/yLPjMaj" target="_blank">https://codepen.io/ruslanmelnychenko/pen/yLPjMaj</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/48667eafeaf21d7d1090b6bd595e1ed6b47f367a/packages/vuetify/src/composables/group.ts#L125
