### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] Textarea not getting error theme, when rule is not fulfilled

### ISSUE THREAD

**Issue by Slash1y** [vuetifyjs/vuetify#14761]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.105
**OS:** Windows 10

### Steps to reproduce
To reproduce this, you would simply need to add the `:rules` part to a textarea component and give it some rules to follow. 
You simply press the submit button, with nothing in the component and have made sure that the field is required, it shows the message, but doesn't change any of the colors to the error theme.

### Expected Behavior
That it correctly shows the error theme on the textarea when the ruleset is broken. 

### Actual Behavior
Only shows the error message(below the textarea component) in the correct color.

### Reproduction Link
<a href="https://github.com/Slash1y/TravelityWebsite/blob/prod/src/components/ContactForm.vue" target="_blank">https://github.com/Slash1y/TravelityWebsite/blob/prod/src/components/ContactForm.vue</a>

### Other comments
I've linked directly to the component where I use it, and there is a running production link using vercel on the front page of the repo, so you can visually see it.

link to the production just in case: https://travelity-website.vercel.app

**Comment by KaelWD** [comment]
Fixed by 5d75a1dc603abf50f5a6e5f8f1f583ac93ec721a
