### ISSUE TITLE
[Bug Report][2.6.3] Date picker modal doesn't appear when clicking just above the text field label

### ISSUE THREAD

**Issue by teckel12** [vuetifyjs/vuetify#14770]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 98.0.4758.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
Note, the Codepen example is an exact copy from the Vuetifyjs.com examples page here: 

https://vuetifyjs.com/en/components/date-pickers/#active-picker

If you click just above the "Birthday date" label in the text field (I made it red to easily identify) the label will move to the top but the date picker modal won't appear.  It may take a couple tries, but once you click the right spot, it can be reproduced every time.  Note that this dead spot is only above the text field label when it's inside the text field and only over the label itself (not the the right of the label).  You must click on the text field a second time to get the date modal to appear.

And to reiterate, this behavior can also be duplicated in the Vuetifyjs.com documentation here:

https://vuetifyjs.com/en/components/date-pickers/#active-picker

### Expected Behavior
The date picker modal should appear when you click anywhere in the text field.

### Actual Behavior
Date picker modal doesn't appear if you click in the dead area above the text field label, you need to click a second time on the field for date modal to appear.

### Reproduction Link
<a href="https://codepen.io/teckel/pen/mdqzYzV" target="_blank">https://codepen.io/teckel/pen/mdqzYzV</a>

### Other comments
This isn't specific to just the year date modal, I was experiencing this on a site I was developing that had a long field label so it was quite easy to click in a spot where the date modal wouldn't appear.  As it's also happening on the Veutifyjs.com site demo, I figured that was the best place to show the bug.

**Comment by teckel12** [comment]
Seems it's a z-index issue.  Adding the following seems to make everything work correctly:

```
.v-input input {
  z-index: 1;
}
```

Of course, this is a temporary hack till it's sorted out correctly.

**Comment by alx-bd** [comment]
I just had the same issue, thank you for providing a temporary fix @teckel12! Unfortunately I'm using a `filled` input for which your workaround is not working correctly because there's additional space above the input.

My approach to this was adding a wrapping span around the text-field, something like this:
```html
<template v-slot:activator="{ on, attrs }">
    <span v-bind="attrs" v-on="on">
      <v-text-field
        filled
        ...
      ></v-text-field>
    </span>
</template>
```
Only downside (so far) is that clicking slightly below the input also opens the picker when the details of the input aren't hidden.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
