### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] This dependency was not found: * vuetify/styles in ./src/plugins/vuetify.js

### ISSUE THREAD

**Issue by bitbw** [vuetifyjs/vuetify#14777]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.102
**OS:** Windows 10

### Steps to reproduce

1.vue create my-app

2.? Please pick a preset: (Use arrow keys)
    Default ([Vue 2] babel, eslint)
  ❯ Default (Vue 3) ([Vue 3] babel, eslint)
    Manually select features
3.cd my-app
vue add vuetify
4.? Choose a preset:
  Configure (advanced)
  Default (recommended)
  Vite Preview (Vuetify 3 + Vite)
  Prototype (rapid development)
❯ Vuetify 3 Preview (Vuetify 3)

5. npm run serve

> my-app@0.1.0 serve   
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                下午4:17:11
                下午4:17:11
This dependency was not found:

* vuetify/styles in ./src/plugins/vuetify.js

### Expected Behavior
not error

### Actual Behavior
 ERROR  Failed to compile with 1 error                                                                                                                下午4:17:11
                下午4:17:11
This dependency was not found:

* vuetify/styles in ./src/plugins/vuetify.js

### Reproduction Link
<a href="https://codepen.io/bitbw/pen/yLPQWBa" target="_blank">https://codepen.io/bitbw/pen/yLPQWBa</a>

**Comment by johnleider** [comment]
This bug is resolved as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by OmarYasirR** [comment]
i have seem issues
please anyone write solving directly
