### ISSUE TITLE
Adding property scrollable in dialog actually sets the overflow to hidden.

### ISSUE THREAD

**Issue by Rud156** [vuetifyjs/vuetify#1477]
#### Setting `<v-dialog scrollable></v-dialog>` actually sets `overflow: hidden` instead of `overflow: auto`.
> Vuetify Version: `0.14.11`

**Comment by johnleider** [comment]
While you did provide a reproduction, I feel it is important that all issues **still** follow the reporting guidelines:
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Rud156** [comment]
Ok. Will reopen it with the changes
