### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-select item-text and item-value props do not work

### ISSUE THREAD

**Issue by guxuerui** [vuetifyjs/vuetify#14783]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Last working version:** 2.6.3
**Vue Version:** 3.2.25
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. use v-select
2. use item-text and item-value

### Expected Behavior
normal use 

### Actual Behavior
display error

### Reproduction Link
<a href="https://codepen.io/guxuerui-the-decoder/pen/ExbGLKj" target="_blank">https://codepen.io/guxuerui-the-decoder/pen/ExbGLKj</a>

**Comment by ImFranQ** [comment]
You don't need use `item-text` and `item-value` props..

only need use an example as this:

```
<v-select 
      label="My select" 
      :items="items"
      v-model="selected">
 </v-select>
```

```
export default {
  // ...
  computed: {
    items(){
      return [
        {value: 1, title: 'My item 1'},
        {value: 2, title: 'My item 2'},
        {value: 3, title: 'My item 3'},
      ]
    }
  }
}
```
> Remember use the objects array formated with `value` and `title` props

**Comment by mactanxin** [comment]
I guess it doesn't support Composition API yet

> You don't need use `item-text` and `item-value` props..
> 
> only need use an example as this:
> 
> ```
> <v-select 
>       label="My select" 
>       :items="items"
>       v-model="selected">
>  </v-select>
> ```
> 
> ```
> export default {
>   // ...
>   computed: {
>     items(){
>       return [
>         {value: 1, title: 'My item 1'},
>         {value: 2, title: 'My item 2'},
>         {value: 3, title: 'My item 3'},
>       ]
>     }
>   }
> }
> ```
> 
> > Remember use the objects array formated with `value` and `title` props

Works for me in Options API,
doesn't work for me either in composition API.
So I guess doesn't support "yet"?

**Comment by NicoAiko** [comment]
`item-value` and `item-text` are returning, right?

**Comment by SuperCuber** [comment]
Also, the docs say the property should be called `text` but what actually works is `title`.

And not sure if this is worthy of its own issue, but after it is selected the value shown to the user is the `value` not the `title` as one would expect

**Comment by kpturner** [comment]
The docs say that you can also include a `disabled` attribute but that does not do anything.

**Comment by kpturner** [comment]
Also, if you do define an array of objects like this:
```
[
        {value: 1, title: 'My item 1'},
        {value: 2, title: 'My item 2'},
        {value: 3, title: 'My item 3'}
]
```
then you get a Typescript error if you try to assign that array to the items property
```
error TS2322: Type '{ title: string; value: string; }[]' is not assignable to type 'SelectItem[]'.
  Type '{ title: string; value: string; }' is not assignable to type 'SelectItem'
```

**Comment by kpturner** [comment]
> 
> try using strings in the values ​​of `value`

That wouldn't help. The problem is the fact that you have to use "title" for the component to actually show anything but the typescript interface matches the docs and only allows "text".

**Comment by Tumulte** [comment]
It’s indeed dead, even in the docs : https://next.vuetifyjs.com/en/components/selects/#custom-text-and-value

**Comment by Tumulte** [comment]
Looking at the code it appears the values are hardcoded as of now. title and value works... and I suppose you'd need a temporary mapper in the meantime

**Comment by KaelWD** [comment]
> then you get a Typescript error

#14962

**Comment by Tomdanizer** [comment]
This appears to still be broken in beta 2 from looking at the docs and trying to repro in codepen it sometimes crashes. This also applies to autocompletes. The docs also note props of **item-value** and **item-title** but the red alert notes **item-text** and **item-value**
https://next.vuetifyjs.com/en/components/selects/#custom-text-and-value
https://codepen.io/tomdanizer/pen/ExQmzzB?editors=101

**Comment by AntoninBeaufort** [comment]
I'm fixing the docs on this PR: https://github.com/vuetifyjs/vuetify/pull/15110

**Comment by andreasvh-conceto** [comment]
Hello,
What about this issue here? It is fine, that the docs are maintained, but this is a critical issue in the codebase. Is there some beta version available, where this issue is already fixed?
[Code Pen Example Select with custom keys](https://codepen.io/pen?&editors=101)

Thx for your help
Best regards
Andreas
