### ISSUE TITLE
[Bug Report][2.5.0] Mac VoiceOver only reads selects Dropdown Item

### ISSUE THREAD

**Issue by deepshah-zoro** [vuetifyjs/vuetify#14787]
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 98.0.4758.109
**OS:** Mac OS 10.15.7

### Steps to reproduce
This CodePen example is from the Select Component documentation here: https://vuetifyjs.com/en/components/selects/#dense

1) Enable the Mac VoiceOver Utility.
2) Using any of the dropdowns, select an option.
3) Use the arrow keys to go up and down through the dropdown options.
4) Listen to the Mac VoiceOver repeat the selected option rather than the option that is highlighted in gray through arrow navigation.

### Expected Behavior
When using the Mac VoiceOver Utility, it should read out the currently highlighted option using the up and down arrows.

### Actual Behavior
It will continuously read the selected option. For a split second in the Mac VoiceOver Utility caption box, you see the expected read out but it is quickly replaced with the selected option.

### Reproduction Link
<a href="https://codepen.io/deepshah93/pen/ExbrPdy" target="_blank">https://codepen.io/deepshah93/pen/ExbrPdy</a>

**Comment by KaelWD** [comment]
This works correctly with android talkback.

**Comment by deepshah-zoro** [comment]
Yes, and it works correctly with most screen readers. From the testing I've
done, the issue seems to occur with just Mac VoiceOver. But other drop
downs work correctly with VoiceOver.

**Comment by KaelWD** [comment]
Feel free to open a PR if you find a way to fix it.

**Comment by kevin-ireland-tc** [comment]
This appears to have been resolved 

https://user-images.githubusercontent.com/122914506/212980897-f45eaee6-ffc6-43f0-ac55-e6696d7fb348.mov

**Comment by KaelWD** [comment]
Thanks @kevin-ireland-tc, probably was a bug in VoiceOver then.
