### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] v-text-field certain props do not work

### ISSUE THREAD

**Issue by XyphurRBX** [vuetifyjs/vuetify#14782]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.51
**OS:** Linux x86_64

### Steps to reproduce
Try to use the outlined, solo, or filled props with v-text-field.

### Expected Behavior
The props modify the appearance of the text field.

### Actual Behavior
The props do not modify the appearance of the text field.

### Reproduction Link
<a href="https://codepen.io/xyphurrbx/pen/JjOwrrZ?editors=101" target="_blank">https://codepen.io/xyphurrbx/pen/JjOwrrZ?editors=101</a>

### Other comments
The props do not work in the v3 docs either https://next.vuetifyjs.com/en/components/text-fields#usage, I stole my codepen example from the docs.

**Comment by KaelWD** [comment]
The documentation is outdated, those props have changed to `variant="something"`: https://github.com/vuetifyjs/vuetify/blob/fbbe600dc7c5cdba23ec22f5fbd72731673806f0/packages/vuetify/src/components/VField/VField.tsx#L34
