### ISSUE TITLE
Datatable with large texts

### ISSUE THREAD

**Issue by FilippiSilva** [vuetifyjs/vuetify#1478]
### Steps to reproduce
Adding large texts inside the cells

### Versions
Vuetify 0.14.11

### What is expected?
A property could be provided where the text content of the cells were shrunk so there was no line break and added to them a tooltip for viewing their content.

### What is really happening?
Today all cells have their text broken into lines to fit in the cell

### Reproduction Link
https://codepen.io/FilippiSilva/pen/oePpwQ

**Comment by chancet1982** [comment]
Isn't this ellipsis you are referring to? Isn't it currently possible using CSS ellipsis?

**Comment by FilippiSilva** [comment]
Yes, but it is necessary to customize the data outputs, it would be interesting to have a property or other means to declare this functionality, for ease of use.

I think it would help more people.

**Comment by johnleider** [comment]
There is an undocumented helper class called **ellipsis** that could help you in your efforts, but you will still need to implement it.

**Comment by FilippiSilva** [comment]
ok, thanks

**Comment by pbastowski** [comment]
If you don't want ellipsis showing on labels in text boxes, drop down lists, etc, you could use the following css:

```css
.input-group label {
  text-overflow: unset;
}
```
