### ISSUE TITLE
[Bug Report][2.6.3] Invalid HTML generated by v-radio-group may be resulting in speech verbosity for screen readers

### ISSUE THREAD

**Issue by hfroot** [vuetifyjs/vuetify#14780]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Firefox 97.0
**OS:** Mac OS 10.15

### Steps to reproduce
Use the `v-radio-group` element with a `label`.

### Expected Behavior
Generated HTML to use `fieldset` as the parent of the `legend` element.

### Actual Behavior
Generated HTML uses `div role="radiogroup"` as (invalid) parent of `legend` element.

### Reproduction Link
<a href="https://codepen.io/hfroot/pen/KKybPpz" target="_blank">https://codepen.io/hfroot/pen/KKybPpz</a>

### Other comments
[MDN docs: `legend`s do not have a meaning outside of `fieldset`s](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend)

The generated HTML should use a `fieldset` with a `legend` and no aria labels. This is in line with the recommendation by W3 : ["Radio button groups should always be grouped using \<fieldset>."](https://www.w3.org/WAI/tutorials/forms/grouping/). According to this recommendation, it would be advisable to use a fieldset even when the radio group hasn't been given a label.

Related issue : https://github.com/vuetifyjs/vuetify/issues/12664

When I check the [documentation for 3.0.0-alpha](https://next.vuetifyjs.com/en/components/radio-buttons) the HTML generated there also doesn't use a `fieldset`.

This bug was detected with the help of ANDI, a web accessibility tool. To see the alerts generated by this tool for this codepen :

* Install ANDI, an a11y checker tool : https://www.ssa.gov/accessibility/andi/help/install.html
* Open the pen in debug mode, run ANDI on the opened page.

1 invalid HTML alert : https://www.ssa.gov/accessibility/andi/help/alerts.html?too_many_legends
1 reference alert : https://www.ssa.gov/accessibility/andi/help/alerts.html?ref_legend

This final reference alert indicates the verbosity screen reader problem mentioned in the issue title.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
