### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] v-tab not working

### ISSUE THREAD

**Issue by go-rahul** [vuetifyjs/vuetify#14795]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
1. Create a new Vue 3 project using Vue CLI (version - 5.0.1).
2. Add Vuetify by running `vue add vuetify` & select Vuetify 3 Preview.
3. Try to use the v-tab component.

or,
1. Clone the given repo.
2. Run `yarn install`.
3. Run `yarn serve`.

### Expected Behavior
Tabs should show up in the screen.

### Actual Behavior
Only texts used inside v-tab is visible. Tab functionality is not working.

### Error message:
[Vue warn]: Failed to resolve component: v-tab
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

[Vue warn]: Failed to resolve component: v-tabs
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

### Reproduction Link
<a href="https://github.com/go-rahul/vuetify-v-tab-bug" target="_blank">https://github.com/go-rahul/vuetify-v-tab-bug</a>

### Other comments
Thank you.

**Comment by KaelWD** [comment]
Alpha 13 was two weeks ago, tabs PR was only merged on friday.

**Comment by go-rahul** [comment]
Thanks @KaelWD
