### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] Sass error

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#14794]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
[vite:css] Invalid argument(s): If parsedAsCustomProperty is true, value must contain a SassString (was `0 !important` of type SassList0).

### Expected Behavior
$color-pack: false;

@import "../node_modules/vuetify/lib/styles/main.sass";

### Actual Behavior
error during build:

### Reproduction Link
<a href="https://codesandbox.io/s/vue" target="_blank">https://codesandbox.io/s/vue</a>

### Other comments
cant build

**Comment by darkphoenixff4** [comment]
I'm getting the exact same error, and it's definitely coming from `~vuetify/lib/styles/main.sass`

**Comment by qxygene** [comment]
it looks like we need to wait for beta.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by nguyenhoanglong1331** [comment]
the bug is still existing on Beta
