### ISSUE TITLE
Question regarding multiple toggle buttons

### ISSUE THREAD

**Issue by ShashankaNataraj** [vuetifyjs/vuetify#148]
The [documentation](https://vuetifyjs.com/components/buttons) gives the vue html tags to create a toggle button with multiple options within. Where is the JS structure documented for what the 

`toggle_options_multiple`

in

`<v-btn-toggle v-bind:options="toggle_options_multiple" multiple="multiple" v-model="toggle_multiple"></v-btn-toggle>`

stands for? Ill try to dig through the source, in the meanwhile, do we need to document this?

**Comment by ShashankaNataraj** [comment]
OK, I found the solution to this conundrum by digging through the source and turning on sourcemaps in my local webpack. Im going to leave this comment here so that anyone else struggling with the same issue can make sense of this:

```
          <v-btn-toggle v-bind:options="categoryOptions" multiple="multiple"
                        v-model="category" v-bind:value="selectedCategories"></v-btn-toggle>
```

```
data:function(){
    return {
           categoryOptions: [{icon: 'format_bold', value: 1}, {
              icon: 'format_italic',
              value: 2
            }, {icon: 'format_underlined', value: 3}, {icon: 'format_color_fill', value: 4}],
            selectedCategories: []
    }
}
```

The above is code I ripped off of the minified example. `categoryOptions` gives the toggle buttons its source material. Since selectedCategories are going to store the toggled buttons at any given time, you will have to pass in an empty array and bind it using `v-bind:value`. 

I really think this needs to get documented so other people don't spend time digging through the source while the rest of the examples are all straight forward and 'copy-pastable'.

**Comment by johnleider** [comment]
Updated with https://github.com/vuetifyjs/docs/commit/02e71003797fb662d928abd0f0440b62e65949ef

**Comment by Ewocker** [comment]
This is actually a very helpful post.
----------
For anyone else who get this error:
      [Vue warn]: Error in render function: "TypeError: this.inputValue.includes is not a function"
      found in
      ---> \<ButtonToggle\>
             \<Root\>
      error during render : /
      TypeError: this.inputValue.includes is not a function

See the example above and notice that " selectedCategories: [] " has to be a "_**list**_", which some of you might not get it at first just like I did.

**Comment by waltergallieni** [comment]
> OK, I found the solution to this conundrum by digging through the source and turning on sourcemaps in my local webpack. Im going to leave this comment here so that anyone else struggling with the same issue can make sense of this:
> 
> ```
>           <v-btn-toggle v-bind:options="categoryOptions" multiple="multiple"
>                         v-model="category" v-bind:value="selectedCategories"></v-btn-toggle>
> ```
> ```
> data:function(){
>     return {
>            categoryOptions: [{icon: 'format_bold', value: 1}, {
>               icon: 'format_italic',
>               value: 2
>             }, {icon: 'format_underlined', value: 3}, {icon: 'format_color_fill', value: 4}],
>             selectedCategories: []
>     }
> }
> ```
> The above is code I ripped off of the minified example. `categoryOptions` gives the toggle buttons its source material. Since selectedCategories are going to store the toggled buttons at any given time, you will have to pass in an empty array and bind it using `v-bind:value`.
> 
> I really think this needs to get documented so other people don't spend time digging through the source while the rest of the examples are all straight forward and 'copy-pastable'.

Ewoker thanks for your digging.
Question: how do set 

> OK, I found the solution to this conundrum by digging through the source and turning on sourcemaps in my local webpack. Im going to leave this comment here so that anyone else struggling with the same issue can make sense of this:
> 
> ```
>           <v-btn-toggle v-bind:options="categoryOptions" multiple="multiple"
>                         v-model="category" v-bind:value="selectedCategories"></v-btn-toggle>
> ```
> ```
> data:function(){
>     return {
>            categoryOptions: [{icon: 'format_bold', value: 1}, {
>               icon: 'format_italic',
>               value: 2
>             }, {icon: 'format_underlined', value: 3}, {icon: 'format_color_fill', value: 4}],
>             selectedCategories: []
>     }
> }
> ```
> The above is code I ripped off of the minified example. `categoryOptions` gives the toggle buttons its source material. Since selectedCategories are going to store the toggled buttons at any given time, you will have to pass in an empty array and bind it using `v-bind:value`.
> 
> I really think this needs to get documented so other people don't spend time digging through the source while the rest of the examples are all straight forward and 'copy-pastable'.

what about v-model="category"?
in my case it doesn't work. maybe I set category: [] in a wrongway?


    categoryOptions: [
      {icon: 'format_bold', value: 1}, 
      {icon: 'format_italic', value: 2}, 
      {icon: 'format_underlined', value: 3}, 
      {icon: 'format_color_fill', value: 4}],
      selectedCategories: [],
      category: []    


thanks
walter
