### ISSUE TITLE
[Bug Report][2.6.4] Vuetify Data Table Issue with single-expand

### ISSUE THREAD

**Issue by rbsamoht** [vuetifyjs/vuetify#14805]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10, Mac OSX

## Issue description
The content of the `v-slot:expanded-item` slot of a `v-data-table` is not always replaced when `single-expand` is set to `true` in the corresponding `v-data-table`.
## Steps to reproduce
- Open the attached CodePen
- Open the Console tab in the CodePen
### Steps to reproduce the expected behavior
- Expand the first row of the table by clicking on the chevron icon (the corresponding slot content is created, as displayed in the console)
- Collapse the first row of the table by clicking on the chevron icon (the corresponding slot content  is destroyed, as displayed in the console)
### Steps to reproduce the issue
- Expand the first row of the table by clicking on the chevron icon (the corresponding slot content is created, as displayed in the console)
- Expand the second row of the table by clicking on the chevron icon (without collapsing the first row before)

### Expected Behavior
The content of the `v-slot:expanded-item` slot should not be re-used when a row is expanded while another row is already expanded (when single-expand is set to true)

### Actual Behavior
The content of the slot displayed under the second row shows the same id as the first row (in other words, the same `v-slot:expanded-item` slot, coming from the first row, is re-used)

### Reproduction Link
<a href="https://codepen.io/rbsamoht/pen/zYPQQvQ" target="_blank">https://codepen.io/rbsamoht/pen/zYPQQvQ</a>

**Comment by KaelWD** [comment]
Rows are already keys, but for some reason vue still reuses components in slots. If you key the slot content too it works as expected: `<test-child :key="item.key" />`
