### ISSUE TITLE
[Bug Report][2.5.10] v-navigation-drawer hides link lables horizontally if the label is too long

### ISSUE THREAD

**Issue by AbdulKadirKhann** [vuetifyjs/vuetify#14807]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
In v-navigation-drawer add a item whose lable is long
The content gets truncated

### Expected Behavior
add a horizontal scrollbar when content doesn't fit in navbar

### Actual Behavior
the content gets truncated.

### Reproduction Link
<a href="https://codepen.io/abdulkadirkhann/pen/ExbBgKL?editors=101" target="_blank">https://codepen.io/abdulkadirkhann/pen/ExbBgKL?editors=101</a>

**Comment by KaelWD** [comment]
Not a bug

**Comment by AbdulKadirKhann** [comment]
> Not a bug

But in my usecase I want to display the whole label and if it exceeds the width I want the navbar to have a horizontal scrollbar. Tried adding `overflow-x-auto` but that doesn't seem to work. Any workaround for this case?

**Comment by KaelWD** [comment]
You will need to add some CSS to remove overflow: hidden from v-list-item-content and v-list-item-title
