### ISSUE TITLE
Select is broken after commit

### ISSUE THREAD

**Issue by psychonetic** [vuetifyjs/vuetify#1480]
~~After your last commit a few minutes ago, the select is broken.~~

**EDIT:** Select is not working properly in Beta 3. The select does open, but not selecting the selected value.
The console does not show any errors.
See fiddle: https://codepen.io/anon/pen/oePaVL

**Comment by alterhu2020** [comment]
@psychonetic , Any update for this ,all the select components in website: https://dev.vuetifyjs.com/components/selects had broken ..

**Comment by HendrikGrobler** [comment]
Can confirm that multi-selects seem to work, but normal single selects do not on v0.15.0-beta.3

**Comment by psychonetic** [comment]
@alterhu2020 I only had the problem, that I included the new css file (because I did use a cdn) and had old js files. That's why it was broken and therefore my personal fault. After full update I don't had any problems with normal single selects.

**Comment by HendrikGrobler** [comment]
@psychonetic that's pretty odd, the dev docs are also broken like @alterhu2020 mentioned. Also, the error states are not working properly. The `error-messages` prop seems to work, but just setting `error="true"` doesn't work. Again this also shows in the first select example of the dev docs. Third field is supposed to have error styling. I cleared my cache before checking.

**Comment by psychonetic** [comment]
@HendrikGrobler @alterhu2020 
Yes, you are right! After upgrading to beta 3 it's not working! (in beta it was working)
I am able to open the select correct, but I it doesn't become selected.

See also this fiddle:
https://codepen.io/anon/pen/oePaVL

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/ee052a302e5cebb6b6e8b7ca0898107b0529b182

**Comment by psychonetic** [comment]
@nekosaur Still does not work!

**Comment by nekosaur** [comment]
@psychonetic It has not been released yet. There will be a new beta release later today

**Comment by psychonetic** [comment]
@nekosaur Ah okay, thank you for the update! Excuse my impatientness.
