### ISSUE TITLE
[Bug Report][2.6.4] vuetify.js as it exceeds the max of 500KB.

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#14803]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.13
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
just `npm run build`

### Expected Behavior
No warning

### Actual Behavior
[BABEL] Note: The code generator has deoptimised the styling of ......../node_modules/vuetify/dist/vuetify.js as it exceeds the max of 500KB.

### Reproduction Link
there is no useful reproduction link possible in my opinion

**Comment by KaelWD** [comment]
https://babeljs.io/docs/en/options#compact

There won't be 500KB in a single file if you use https://vuetifyjs.com/en/features/treeshaking/
