### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] Various TypeScript Errors

### ISSUE THREAD

**Issue by subdavis** [vuetifyjs/vuetify#14816]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.25
**Browsers:** Chrome 99.0.4844.51
**OS:** Linux x86_64

### Steps to reproduce
1. clone repository
1. run `yarn`
1. run `yarn type` to invoke `vue-tsc`.

### Expected Behavior
Type checking should pass.

### Actual Behavior
```
~$ yarn type
yarn run v1.22.17
$ vue-tsc -p tsconfig.check.json --noEmit
node_modules/vuetify/lib/components/index.d.ts:3:29 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

3 import * as vue_router from 'vue-router';
                              ~~~~~~~~~~~~

node_modules/vuetify/lib/components/index.d.ts:4:34 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

4 import { RouteLocationRaw } from 'vue-router';
                                   ~~~~~~~~~~~~

node_modules/vuetify/lib/index.d.ts:261:7 - error TS7008: Member '$children' implicitly has an 'any' type.

261       $children
          ~~~~~~~~~

node_modules/vuetify/lib/index.d.ts:271:3 - error TS2667: Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.

271   import type { VNodeChild } from '@vue/runtime-core'
      ~~~~~~


Found 4 errors in 2 files.

Errors  Files
     2  node_modules/vuetify/lib/components/index.d.ts:3
     2  node_modules/vuetify/lib/index.d.ts:261
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction Link
<a href="https://github.com/subdavis/ts-repro-vuetify-2022" target="_blank">https://github.com/subdavis/ts-repro-vuetify-2022</a>

### Other comments
It looks like Vuetify depends on `vue-router` types but apparently doesn't declare it as a dependency.  There are 2 other typescript errors that I am unable to resolve after installing vue router.

**Comment by KaelWD** [comment]
Vue-router isn't a runtime dependency so I don't really want to add it as one just for typescript. If you aren't using vue-router for whatever reason you can suppress the warning by enabling `compilerOptions.skipLibCheck`, I think everything should still work just with router props falling back to `any`.

**Comment by subdavis** [comment]
Thank you for fixing the latter 2 typescript errors!

> Vue-router isn't a runtime dependency so I don't really want to add it as one just for typescript. If you aren't using vue-router for whatever reason you can suppress the warning by enabling compilerOptions.skipLibCheck

I don't think this is a good solution.   It's not reasonable to ask consumers of Vuetify to abandon their entire library type accuracy checks, and I think a much better option exists:

https://stackoverflow.com/a/70096366/3347791

```
// @ts-ignore -- optional interface, will gracefully degrade to `any` if `foo` isn't installed
import type { Foo } from "foo";
import type { Bar } from "bar";
```

Consumers that have foo will see `Foo`, and those that don't will see any.
