### ISSUE TITLE
v-checkbox with prepend-icon has icon on top of checkbox

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1481]
### Steps to reproduce
Insert a `v-checkbox` with the `prepend-icon` prop.

### Versions
Vue 2.4.2, Vuetify 0.14.11 and 0.15.0-beta.2, Edge 15

### What is expected ?
The icon should be placed before the checkbox so that it lines up neatly in forms where `v-text-field` is used with prepended icons.

### What is actually happening ?
The icon is over the checkbox.

### Reproduction Link
https://codepen.io/smares/pen/gxdzXY

**Comment by smares** [comment]
Side-note: `append-icon` and `prepend-icon` don't work at all with radios even though the documentation lists those as valid props.

**Comment by johnleider** [comment]
Leaving this up because it's something I want to do for 0.16, a refactor of how those elements are processed.
