### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] v-timeline lines are disappearing after second item in horizontal mode

### ISSUE THREAD

**Issue by avan2s** [vuetifyjs/vuetify#14820]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Firefox 98.0
**OS:** Linux, Ubuntu undefined, Windows

### Steps to reproduce
1) Create a child component with a v-timeline with direction="horizontal" density="compact"
2) Integrate this child component into a parent component. 

### Expected Behavior
All lines are visible between the v-timeline-items. So they are all connected.

### Actual Behavior
The lines disappear after the second v-timeline-item until the end. Do some change in the code of child component to perform hot deployment and they appear temporary for some reason. If you press F5 all lines after second v-timeline-item disappear again.

### Reproduction Link
<a href="https://github.com/avan2s/vuetify-timeline-sandbox" target="_blank">https://github.com/avan2s/vuetify-timeline-sandbox</a>

### Other comments
The repository shows 2 horizontal timelines. One timeline inside a parent component, which uses v-app v-main tag and another timeline, embedded as a child component, which is representing the issue. Physically the lines between the items are there, but with width = 0, which is causing the disappearing effect. 

Additional info:
The lines appear in horizontal mode if you change some code in hot deployment and you can think it is working. But if you then press F5, the lines after the second timeline item disappear again.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/5322
