### ISSUE TITLE
[Bug Report][2.6.4] v-dialog max-width doesn't work as expected

### ISSUE THREAD

**Issue by reynard80** [vuetifyjs/vuetify#14835]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
- Open codepen
- Click width button; a dialog with fixed `width` prop opens
- Click max-width button; a dialog with dynamic `max-width` prop opens

### Expected Behavior
Both dialogs contain a fixed width element of width **200**. 

The `width` `v-dialog` is expected to have a fixed width of **400**.

The `max-width` `v-dialog` is expected to resize to the content, so it's width should be **200**. 

### Actual Behavior
The `width` `v-dialog` indeed has a width of **400**.

The `max-width` `v-dialog` doesn't fit to its contents, to a width of **200**. Instead, it has the same fixed width of **400**.

In fact, both props have the same behaviour, so it seems the `max-width` prop doesn't work properly.

### Reproduction Link
<a href="https://codepen.io/m-fitch/pen/zYpvLwW" target="_blank">https://codepen.io/m-fitch/pen/zYpvLwW</a>

**Comment by anamolsoman** [comment]
Hey @reynard80 I have come up with a solution, Add width="max-content" along with max-width this will solve your problem 
` <v-dialog v-model="showMaxWidthDialog" max-width="400" width="max-content">
      <v-card width="200">MAX WIDTH</v-card>
    </v-dialog>`

**Comment by reynard80** [comment]
> 

Thanks, that works. Only issue is that there's no anumation when the width of the content changes. Have to come up with something for that.

**Comment by KaelWD** [comment]
Dialogs have `width: 100%` by default, you can use `width="auto"` to override it.
