### ISSUE TITLE
[Bug Report][2.6.4] Text in components within v-dialog slightly moves after loading

### ISSUE THREAD

**Issue by reynard80** [vuetifyjs/vuetify#14831]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
Please checkout the sample project to reproduce the problem. Run `npm install` and `npm serve`.

Click the 'Open dialog' button. Button text and tab text slightly move after loading. Pay attention, because the effect is subtle.

### Expected Behavior
No components move after having been loaded.

### Actual Behavior
Some text within the `v-dialog` such as button text, table headers, tab text and icons slightly moves after loading.

### Reproduction Link
<a href="https://github.com/reynard80/vuetify-dialog-issue" target="_blank">https://github.com/reynard80/vuetify-dialog-issue</a>

### Other comments
- Happens with Vue 2.6.14, Vuetify 2.6.4 and latest Chrome, Firefox. However also with previous versions.
- Happens in all builds (dev, staging, prod).
- Tested on multiple machines.
- Can also be observed on the Vuetify docs, as per [this](https://streamable.com/lklonr) video.

**Comment by KaelWD** [comment]
I'm not seeing this on my machine, from the video it looks like subpixel AA being turned off during the transition.
