### ISSUE TITLE
[Bug Report][2.5.4] VCalendar with events doesn't update the parsed timestamp's relative flags

### ISSUE THREAD

**Issue by rahadi23** [vuetifyjs/vuetify#14836]
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
- Create a `VCalendar` with events
- Add some passed, ongoing, and future events
- Implement the `event` slot
- Get the timestamp's relative flags (`pass`, `present`, `future`) from `eventParsed` property

### Expected Behavior
The timestamp's relative flags should return the correct values relative to the value of the `now` prop

### Actual Behavior
The timestamp's relative flags appear to be remain not updated after the events are parsed

### Reproduction Link
<a href="https://codepen.io/rahadi23/pen/JjMYqNW" target="_blank">https://codepen.io/rahadi23/pen/JjMYqNW</a>

### Other comments
After inspecting the source code, I found that these lines: https://github.com/vuetifyjs/vuetify/blob/3c75edb506105f7d7405e2024dee0fc32fd1c40f/packages/vuetify/src/components/VCalendar/util/events.ts#L20-L21 probably needs to be updated to also include the 3rd parameter (`now`) when calling `parseTimestamp()`. 

By doing so, it will cause these lines: https://github.com/vuetifyjs/vuetify/blob/3c75edb506105f7d7405e2024dee0fc32fd1c40f/packages/vuetify/src/components/VCalendar/util/timestamp.ts#L122-L124 and/or https://github.com/vuetifyjs/vuetify/blob/3c75edb506105f7d7405e2024dee0fc32fd1c40f/packages/vuetify/src/components/VCalendar/util/timestamp.ts#L166-L168 to be called, therefore the relative flags will be updated.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
