### ISSUE TITLE
[Bug Report][2.6.4] v-autocomplete wrong item highlighted when using keyboard controls

### ISSUE THREAD

**Issue by ErikdB** [vuetifyjs/vuetify#14837]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
- Create a v-autocomplete with items
- Enter a search word which results with a few hits. In my reproduction link if you type in the letter 'a', a few hits show up.
- Use the arrow keys and Enter to select an item

### Expected Behavior
The next row in the menu is highlighted until the last row is reached.

### Actual Behavior
Most of the times the highlighted row skips rows in the menu. When you keep pressing enter, the index eventually lays outside of the menu item length and when enter is pressed again an exception occurs.
```
TypeError: Cannot read properties of undefined (reading 'click')
    at VueComponent.changeListIndex (vuetify.min.js:6:127633)
    at VueComponent.<anonymous> (vuetify.min.js:6:187949)
    at Array.<anonymous> (vue.js:1998:14)
    at flushCallbacks (vue.js:1924:16)
```

### Reproduction Link
<a href="https://codepen.io/ErikdB/pen/mdpVbGz?editors=101" target="_blank">https://codepen.io/ErikdB/pen/mdpVbGz?editors=101</a>

**Comment by KaelWD** [comment]
> Enter a search word which results with a few hits

Gonna need something more specific than this.

**Comment by ErikdB** [comment]
I've updated the steps to reproduce

**Comment by DennisBergemann** [comment]
Have the same behavior

**Comment by DennisBergemann** [comment]
additionally as an Example here on th official vuetify page:
https://vuetifyjs.com/en/components/autocompletes/#examples

1. go to the first example  (foo,bar,fizz..) in the list
2. when it starts foo and bar is in the list
3. type fizz and press enter
4. now sometimes the cursor will go to fizz somtimes not
5. move cursor to fizz and press enter (fizz will added)
6. press enter now again und you will see in you console the exception

```
TypeError: Cannot read properties of undefined (reading 'click')
    at r.changeListIndex (VMenu.ts:274:9)
    at r.<anonymous> (VSelect.ts:679:11)
    at Array.<anonymous> (vue.runtime.common.prod.js:6:12260)
    at ze (vue.runtime.common.prod.js:6:11659)
Ve @ vue.runtime.common.prod.js:6
Ne @ vue.runtime.common.prod.js:6
Le @ vue.runtime.common.prod.js:6
(anonym) @ vue.runtime.common.prod.js:6
ze @ vue.runtime.common.prod.js:6
Promise.then (asynchron)
qe @ vue.runtime.common.prod.js:6
Ke @ vue.runtime.common.prod.js:6
(anonym) @ vue.runtime.common.prod.js:6
onKeyDown @ VSelect.ts:678
onKeyDown @ VAutocomplete.ts:374
He @ vue.runtime.common.prod.js:6
o @ vue.runtime.common.prod.js:6
(anonym) @ vue.runtime.common.prod.js:6


```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by davibarbosa2** [comment]
Got this problem too! Has anyone found a solution?

**Comment by DennisBergemann** [comment]
@davibarbosa2  its a while ago, but i think it solved with updating the modules
