### ISSUE TITLE
[Bug Report][2.6.4] v-autocomplete highlighting with auto-select-first does not work after `No data available` state

### ISSUE THREAD

**Issue by havardthom** [vuetifyjs/vuetify#14838]
### Environment
**Vuetify Version:** 2.6.4
**Last working version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
1. Write "forms" and see that the first item is correctly highlighted with `v-list-item--highlighted` class
2. Add a typo, e.g. "formss", to trigger the `No data available` state.
3. Go back to "forms" and see that the `v-list-item--highlighted` class is missing (but it can still be selected with enter keybind). `v-list-item--highlighted` class is now missing until you actively navigate the dropdown list (arrow up or down) or until you leave and reenter the autocomplete (loose and gain focus).

### Expected Behavior
1. Write "forms" and see that the first item is correctly highlighted with `v-list-item--highlighted` class
2. Add a typo, e.g. "formss", to trigger the `No data available` state.
3. Go back to "forms" and see that the item is still highlighted with `v-list-item--highlighted` class. `v-list-item--highlighted` continues to work on first item when changing search input.

### Actual Behavior
1. Write "forms" and see that the first item is correctly highlighted with `v-list-item--highlighted` class
2. Add a typo, e.g. "formss", to trigger the `No data available` state.
3. Go back to "forms" and see that the `v-list-item--highlighted` class is missing (but it can still be selected with enter keybind). `v-list-item--highlighted` class is now missing until you actively navigate the dropdown list (arrow up or down) or until you leave and reenter the autocomplete (loose and gain focus).

### Reproduction Link
<a href="https://codepen.io/havardthom/pen/MWrKgNb" target="_blank">https://codepen.io/havardthom/pen/MWrKgNb</a>

**Comment by lukicenturi** [comment]
This is temp workaround I use
```
    watch(search, () => {
      const el = get(input)?.$el;
      if (el) {
        const className = 'v-list-item--highlighted';
        const highlighted = el.querySelectorAll(`.${className}`).length;
        if (highlighted === 0) {
          nextTick(() => {
            const elementToUpdate = el.querySelectorAll('.v-list-item');
            if (elementToUpdate.length > 0) {
              elementToUpdate[0].classList.add(className);
            }
          });
        }
      }
    });
```

**Comment by curtgrimes** [comment]
Another possible workaround:

```vue
<template>
    <v-autocomplete :items="items" auto-select-first ref="autocompleteEl" />
</template>

<script setup>
import { watch } from 'vue';
import { VAutocomplete } from 'vuetify/lib';

const items = ref([]);
const autocompleteEl = ref<InstanceType<typeof VAutocomplete>>();

watch(items, () => {
    if (!items.length) {
        autocompleteEl.value.setMenuIndex(-1);
    }
});
</script>
```
