### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VBtn inside VCardActions doesn't style correctly

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#14845]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Last working version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.74
**OS:** Windows 10

### Steps to reproduce
Open https://codepen.io/andrewspy/pen/NWXNXQy

### Expected Behavior
Should be same style as button outside of VCard.

### Actual Behavior
Button is styled as `variant="text"`

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/NWXNXQy" target="_blank">https://codepen.io/andrewspy/pen/NWXNXQy</a>

**Comment by FFxSquall** [comment]
I think these are the correct styles. Please see here https://material.io/components/cards#actions

**Comment by andrewspy** [comment]
@FFxSquall In my case, I have a primary and secondary button, which I need to style differently. Just to put things in context.

**Comment by KaelWD** [comment]
You can still set the variant yourself, it's just a default value.

**Comment by andrewspy** [comment]
I have tried setting `variant="default"`, but typescript raise an error as `"default"` is not a valid type, However, setting `:variant="undefined"` work as expected.

**Comment by FFxSquall** [comment]
@andrewspy default variant for button `contained` use `variant="contained"` inside the card component

**Comment by andrewspy** [comment]
@FFxSquall Thanks for the pointer, as this is expected, I shall close the issue. It would be good to update the documentation to mention the default variant of button is "contained", and default variant of styling with VCardActions is "text".

**Comment by sladec** [comment]
I had to set it to` variant="elevated"` to get default button, "contained" did not work.

**Comment by klondikemarlen** [comment]
Is it possible to override the v-card-actions -> button variant at the theme configuration level?
