### ISSUE TITLE
[Bug Report][2.6.4] v-progress-linear mutates data via clicking on the bar

### ISSUE THREAD

**Issue by anzuj** [vuetifyjs/vuetify#14842]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.0
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
1. Make a v-progress-linear bar and assign it a data value via v-model
2. Click on the bar in the browser

### Expected Behavior
Clicking on the bar won't change value

### Actual Behavior
Clicking changes value and mutates the data it was bound to via v-model

### Reproduction Link
<a href="https://codepen.io/anzuj/pen/PoEZNNe" target="_blank">https://codepen.io/anzuj/pen/PoEZNNe</a>

### Other comments
I'm not sure if it's intentional to allow user-facing clicks to change the v-model value

**Comment by KaelWD** [comment]
It is intentional: #5147

**Comment by anzuj** [comment]
> It is intentional: #5147

Thanks for confirming. I now found it in documentation as well, but it really struck me as a surprise. I used the progress bar to display some important statistics that.. err... let's say should NOT be allowed to visually change by a click :D

**Comment by KaelWD** [comment]
Yeah I think it is a bit weird, I would've said to just use a slider with a few lines of css to hide the thumb rather than add this to progress components.
