### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VIcon inside VTab doesn't style correctly with `left`

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#14849]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.74
**OS:** Windows 10

### Steps to reproduce
Open https://codepen.io/andrewspy/pen/NWXrWbZ?editors=1010

### Expected Behavior
Icon should space accordingly with `left`

### Actual Behavior
Icon does not space accordingly with `left`

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/NWXrWbZ?editors=1010" target="_blank">https://codepen.io/andrewspy/pen/NWXrWbZ?editors=1010</a>

**Comment by KaelWD** [comment]
left/right margin is based on height (normally px) but tabs set height to 100% and percentage margins use width instead.
