### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] VSelect on change not working

### ISSUE THREAD

**Issue by shadrqen** [vuetifyjs/vuetify#14840]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Last working version:** 2.6.4
**Vue Version:** 3.2.31
**Browsers:** Firefox 98.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create a VSelect tag with items. Add an @change on the VSelect and add a function to call.

### Expected Behavior
The function should be called upon changing of the VSelect elements

### Actual Behavior
The function is not called

### Reproduction Link
<a href="https://github.com/shadrqen/vuetify-repro-vselect-onchange" target="_blank">https://github.com/shadrqen/vuetify-repro-vselect-onchange</a>

**Comment by KaelWD** [comment]
There is no change event, it's `update:modelValue`
