### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VSnackbar doesn't render `#action` slot

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#14846]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.74
**OS:** Windows 10

### Steps to reproduce
Open https://codepen.io/andrewspy/pen/JjMXpYd

### Expected Behavior
Should show the close button in `#action` slot.

### Actual Behavior
`#action` slot is not rendered.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/JjMXpYd" target="_blank">https://codepen.io/andrewspy/pen/JjMXpYd</a>

### Other comments
- Font color is also not correct when `theme="dark"`.
- Doc page https://next.vuetifyjs.com/en/api/v-snackbar/ shows `#actions` instead of `#action`, maybe typos?

**Comment by nekosaur** [comment]
Examples have been updated https://github.com/vuetifyjs/vuetify/commit/697cd14558b321c397f7efd8072e8f663c36a737

The correct slot name is `actions`

**Comment by tve** [comment]
@nekosaur 

> Examples have been updated [697cd14](https://github.com/vuetifyjs/vuetify/commit/697cd14558b321c397f7efd8072e8f663c36a737)

Can you point to a docs, codepen, or other page that shows the new examples in action?

**Comment by nekosaur** [comment]
https://next.vuetifyjs.com/en/components/snackbars/#vertical
