### ISSUE TITLE
[Bug Report][2.6.4] v-carousel doesn't update theme

### ISSUE THREAD

**Issue by oindypoind** [vuetifyjs/vuetify#14843]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 99.0.4844.51, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Press switch theme under the carousel.
Inspect the HTML of the `v-carousel`, `v-carousel__controls > v-item-group` and `v-carousel__controls__item`

### Expected Behavior
the classes of `theme--dark` should switch to `theme--light` and vice-versa on the carousel container, and the pagination buttons inside `v-carousel__controls`

### Actual Behavior
the classes remain fixed on the `v-carousel` and `v-carousel__control v-item-group` and `v-carousel__controls__item`

### Reproduction Link
<a href="https://codepen.io/oindypoind/pen/gOorPOp" target="_blank">https://codepen.io/oindypoind/pen/gOorPOp</a>

### Other comments
As a result the pagination buttons for the carousel don't switch to the alternative theme.

**Comment by KaelWD** [comment]
Light theme on carousel looks like this:

![Screenshot_20220319_180744](https://user-images.githubusercontent.com/16421948/159111409-f14d8861-8edc-4b2f-90f9-6854a1195821.png)

It uses dark so the icons are always white.
