### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VAppBar wrong width when inside v-container

### ISSUE THREAD

**Issue by AlvaroBrasilia** [vuetifyjs/vuetify#14855]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Safari 15.4
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open https://codepen.io/alvarobrasilia/pen/JjMKzWW

### Expected Behavior
Proportional margin on right and left side

### Actual Behavior
Missing right margin

### Reproduction Link
<a href="https://codepen.io/alvarobrasilia/pen/JjMKzWW" target="_blank">https://codepen.io/alvarobrasilia/pen/JjMKzWW</a>

**Comment by KaelWD** [comment]
@nekosaur This seems to be due to layout using width instead of left/right: https://github.com/vuetifyjs/vuetify/blob/11fddffcb9334856a54938267c634774653b909f/packages/vuetify/src/composables/layout.ts#L291

**Comment by nekosaur** [comment]
I'm not sure v-app-bar inside v-container is 'valid' markup. What is the actual scenario where you want to do this? Could it perhaps be a v-toolbar instead?

**Comment by johnleider** [comment]
> I'm not sure v-app-bar inside v-container is 'valid' markup. What is the actual scenario where you want to do this? Could it perhaps be a v-toolbar instead?

I'm in agreeance with @nekosaur here; this is what `v-toolbar` exists for.

**Comment by KaelWD** [comment]
This issue is being closed due to inactivity.

**Comment by AlvaroBrasilia** [comment]
I agree with @nekosaur, the way I wrote the proper component would be `v-toolbar`.

However, the result I would like to have is a margin/padding on the sides of the `v-app-bar`, as we have in the following example.

[![Screen Shot 2022-03-30 at 13 09 01](https://user-images.githubusercontent.com/2683945/160881200-fd2d5a5f-9632-4b3d-9906-799c0b678b67.png)](https://vuetifyjs.com/en/examples/wireframes/constrained/)



In this case the correct syntax following the example would be:

```
<v-app>
    <v-app-bar >
        <v-container>
    
            <template v-slot:prepend>
                <v-app-bar-nav-icon></v-app-bar-nav-icon>
            </template>

           <v-app-bar-title>Title</v-app-bar-title>

           <template v-slot:append>
              <v-btn icon="mdi-dots-vertical"></v-btn>
           </template>
    
        </v-container>
    </v-app-bar>
</v-app>
```



According to the codepen below, we do not have the expected result:

https://codepen.io/alvarobrasilia/pen/KKZvyzz

![image](https://user-images.githubusercontent.com/2683945/160886505-65378c0b-ea35-4069-bc2a-d0d1603ef0ae.png)

**Comment by KaelWD** [comment]
> we do not have the expected result

What is the expected result? That looks fine to me.

**Comment by AlvaroBrasilia** [comment]
> > we do not have the expected result
> 
> What is the expected result? That looks fine to me.

https://codepen.io/alvarobrasilia/pen/KKZvyzz

Please, see the [codepen](https://codepen.io/alvarobrasilia/pen/KKZvyzz). 

The `prepend`(`<v-app-bar-nav-icon>`) and `append`(`<v-btn icon="mdi-dots-vertical"></v-btn>`) slot is missing

**Comment by KaelWD** [comment]
Well yeah they're slots on v-toolbar, not v-container. They don't seem to be particularly useful on toolbars either, just a weird way of reducing padding which you can do just as well with classes: https://codepen.io/kaelwd/pen/QWaMOBd?editors=1010

**Comment by AlvaroBrasilia** [comment]
Great, I got you!

This work fine for me. Thank you.
