### ISSUE TITLE
Vertical stepper transition animation sometimes skipped

### ISSUE THREAD

**Issue by MrTeapot** [vuetifyjs/vuetify#1485]
### Versions

"vue": "^2.3.3",
"vuetify": "^0.14.11"

Tested with MacOS and Chrome version 60.0.3112.101

### What is expected ?
Always see the animation when transitioning between steps

### What is actually happening ?
The animation is skipped for some steps, and not every time I go back and forth between the steps. 

### Reproduction Link

https://codepen.io/MrTeapot/pen/eEPJmB

http://imgur.com/sb1PrWb

**Comment by johnleider** [comment]
You do realize a reproduction link to an image isn't a reproduction link right? lol

**Comment by johnleider** [comment]
I have been unable to reproduce this issue, please provide a reproduction link to codepen or jsfiddle.

**Comment by MrTeapot** [comment]
I have added a reproduction link now. Press Continue, Back and Continue. Then you will see the animation getting skipped.

**Comment by nekosaur** [comment]
Can confirm (Chrome). But only seems to happen the first time you do it

**Comment by MrTeapot** [comment]
It is not happening consistently. In my own app it is way more frequent than in the reproduction link.

**Comment by johnleider** [comment]
I actually made some tweaks to the expand transition for the purposes of list-group which was having the exact same issue, should be resolved now.
