### ISSUE TITLE
[Bug Report][2.6.4] rounded prop on v-card doesn't work

### ISSUE THREAD

**Issue by reynard80** [vuetifyjs/vuetify#14859]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
Open codepen the v-card has rounded corners, despite having `:rounded="false"` prop

### Expected Behavior
No rounded corners

### Actual Behavior
Rounded corners

### Reproduction Link
<a href="https://codepen.io/m-fitch/pen/wvpzNmq" target="_blank">https://codepen.io/m-fitch/pen/wvpzNmq</a>

**Comment by AlvaroBrasilia** [comment]
Try `class="rounded-0"` this worked for me.

**Comment by KaelWD** [comment]
`tile` or `rounded="0"` also work.
