### ISSUE TITLE
[Bug Report][3.0.0-beta.0] v-list-item not highlighting

### ISSUE THREAD

**Issue by florentdescroix** [vuetifyjs/vuetify#14865]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.82
**OS:** Linux x86_64

### Steps to reproduce
Copy paste the code from the doc : https://next.vuetifyjs.com/en/components/menus/

### Expected Behavior
Highlight the list item on hover

### Actual Behavior
Nothing

### Reproduction Link
<a href="https://codepen.io/hen-sen/pen/LYexZLG" target="_blank">https://codepen.io/hen-sen/pen/LYexZLG</a>

### Other comments
It does work in the documentation for the exact same piece of code!

**Comment by KaelWD** [comment]
What you're seeing in the docs is actually a bug, the codepen is showing the correct behaviour. The list items aren't clickable so shouldn't have a hover effect. 

> It does work in the documentation for the exact same piece of code

Docs are build with every commit, the codepen is using a nightly build from yesterday. 

---

@johnleider I thought we weren't doing the `props.value` stuff, and "is in a list" also shouldn't count as clickable
https://github.com/vuetifyjs/vuetify/blob/529a5ad674f350f12aeddd064af4e028c00b2bb4/packages/vuetify/src/components/VList/VListItem.tsx#L138

**Comment by johnleider** [comment]
`props.value` is what allowed the removal of the **link** prop. The last comparison was just incorrect. If it's inside of a list and it has a value or if it's a clickable link.
