### ISSUE TITLE
v-select label moves back to its initial position right after selecting from the drop-down

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1486]
### Steps to reproduce
With a `v-select` without anything set, click on the drop-down and make a selection

### Versions
Vue 2.4.2, Vuetify 0.15.0-beta.2, Edge 15

### What is expected ?
The value should be set and the label should not move back and forth

### What is actually happening ?
When the drop-down opens, the label moves to the top and shrinks. As soon as you pick something from the drop-down, the label moves back to its initial position, is underneath the selected text and then suddenly jumps back to the top and shrinks again.

### Reproduction Link
https://codepen.io/smares/pen/prOxrK

**Comment by johnleider** [comment]
This was fixed with f63ea22705632e7d7765e8bcf9529a0374b225ed
