### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VTab: stacked tabs have no slider and density is lost

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#14863]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.30
**Browsers:** Chrome 98.0.4758.136
**OS:** Linux x86_64

### Steps to reproduce
The codepen shows 4 tabs. The fourth has an artificially reduced height and shows the slider. The other three don't. Remove the 'stacked' prop on v-tabs and all 4 show a slider.

In the JS window, remove the 'xx' from 'density' and the tabs have lesser height. Now inspect a tab and observe that the button has a v-btn--density-default class instead of v-btn--density-compact and is way too tall compared to the tab bar.

### Expected Behavior
Expected that the heights of individual tabs match the height of the tab bar.

### Actual Behavior
The tabs are too tall as evidenced by missing slider.

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/VwyPZWJ" target="_blank">https://codepen.io/codesurfr/pen/VwyPZWJ</a>

**Comment by tve** [comment]
I updated my codepen to use the latest nightly and while there's improvement the slider still doesn't show? https://codepen.io/codesurfr/pen/VwyPZWJ

**Comment by KaelWD** [comment]
You aren't using nightly css
