### ISSUE TITLE
[Bug Report][2.6.4] [wrong demonstration] Navigation Drawer Documentation

### ISSUE THREAD

**Issue by MohaElder** [vuetifyjs/vuetify#14860]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 99.0.4844.83
**OS:** Windows 10

### Steps to reproduce
Observe the [documentation page's demonstration](https://vuetifyjs.com/en/components/navigation-drawers/#bottom-drawer) and you will see what's wrong

### Expected Behavior
drawer should be jumping from bottom

### Actual Behavior
drawer jumping from side

### Reproduction Link
<a href="https://codepen.io/mohaelder/pen/PoEbqrK?editors=101" target="_blank">https://codepen.io/mohaelder/pen/PoEbqrK?editors=101</a>

### Other comments
using "app bottom" solves the issue.

**Comment by KaelWD** [comment]
> The navigation drawer will appear from the bottom on smaller size screens
