### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VDialog modal cannot center properly in window

### ISSUE THREAD

**Issue by cpainchaud** [vuetifyjs/vuetify#14861]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
I used VDialog's doc codepen example and just added a field to make it larger (1200px), as you can see  it's not centered on screen : there seems to be a fixed value for underlying overlay max-width/max-heigth that doesn't match the content width . Trying for force the component's max-xxx will apply to the root overlay element and thus not have any effect at all

### Expected Behavior
QDialog should not enforce a max width or height  OR these should be customizable

### Actual Behavior
Qdialiog enforce a max-width max-heigth which stops larger content from being centered

### Reproduction Link
<a href="https://codepen.io/shellescape/pen/LYepRPY" target="_blank">https://codepen.io/shellescape/pen/LYepRPY</a>

**Comment by KaelWD** [comment]
@johnleider Why do dialogs have a max width and height? 9c2e3636c778e17e16c8e7b91a44c267c7bc7c16

**Comment by johnleider** [comment]
From the [spec](https://material.io/components/dialogs). However, these *should* be scoped to mobile.
