### ISSUE TITLE
[Bug Report][2.6.4] V-Checkbox does not emit blur and focus events

### ISSUE THREAD

**Issue by gmeral** [vuetifyjs/vuetify#14862]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.74
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a v-checkbox to a template
2. Bind `focus` and/or `blur` listeners (`@focus` / `@blur`)
3. Click checkbox
4. Click outside checkbox

### Expected Behavior
After 3., focus handler is triggered
After 4. blur handler is triggered

### Actual Behavior
After 3., focus handler is not triggered
After 4. blur handler is not triggered

### Reproduction Link
<a href="https://codepen.io/GuillaumeMeral/pen/xxpRXzN" target="_blank">https://codepen.io/GuillaumeMeral/pen/xxpRXzN</a>

### Other comments
In the repro codepen, you can see the expected behaviour with a native html checkbox input

**Comment by gmeral** [comment]
Hi
@KaelWD this issue seems to still stand in 2.6.6 (see the reproduction link)

**Comment by KaelWD** [comment]
Works for me

**Comment by gmeral** [comment]
So here : 
https://codepen.io/GuillaumeMeral/pen/xxpRXzN

When you click the v-checkbox, you see the message "status = 'focus v-checkbox'" appearing ?
