### ISSUE TITLE
[Bug Report][2.6.0] Why won't pages that use vuetify load?

### ISSUE THREAD

**Issue by DrigaNicolai** [vuetifyjs/vuetify#14876]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 99.0.4844.82
**OS:** Windows 10

### Steps to reproduce

Open page that is using vuetify. Even official website

### Expected Behavior
The page should open, load and work like any other web page

### Actual Behavior
When you open a page, it takes a long time to load, starts to eat up RAM and in the end just gives an error stating that there is not enough memory to load

### Reproduction Link
<a href="https://jsfiddle.net/1x85ubh2/4/" target="_blank">https://jsfiddle.net/1x85ubh2/4/</a>

### Other comments
The day before the problem appeared, I was working on the code and everything was fine, but yesterday, when I tried to open the same application and did not even make a change, I encountered this error

**Comment by MajesticPotatoe** [comment]
duplicate #14871
upstream issue with icon library via cdn.
