### ISSUE TITLE
Expansion panels render slowly and incorrectly during the animation with Edge

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1487]
### Steps to reproduce
Expand and close expansion panels using Edge 15

### Versions
Vue 2.4.2, Vuetify 0.15.0-beta.2, Edge 15

### What is expected ?
The expansion panels should open and close smoothly

### What is actually happening ?
The expansion panel animations are jaggy and show either solid black during the animation, or other rendering issues occur. The problem didn't exist in 0.14.11.

### Reproduction Link
https://dev.vuetifyjs.com/components/expansion-panels

**Comment by johnleider** [comment]
This is a very weird rendering issue with Edge. For now, disabling the animation.
