### ISSUE TITLE
[Bug Report][2.6.3] Performace problems with many vuetify components in a v-data-table

### ISSUE THREAD

**Issue by npriebe** [vuetifyjs/vuetify#14873]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.10
**Browsers:** Edge 95.0.1020.53
**OS:** Linux x86_64

### Steps to reproduce
In my example I created a v-data-table with 20 header columns & 200 rows.
I then overwrote the items in the template and added a v-badge and a v-chip.
See example.

### Expected Behavior
v-data-table without performance problems

### Actual Behavior
performance problems

### Reproduction Link
<a href="https://codepen.io/npriebe/pen/oNpBVEx" target="_blank">https://codepen.io/npriebe/pen/oNpBVEx</a>

**Comment by KaelWD** [comment]
Not really possible, that's 12000 component instances and over 42000 elements. Use pagination or wait for #3435
