### ISSUE TITLE
[Bug Report][3.0.0-beta.0] v-select item are not displaying

### ISSUE THREAD

**Issue by amm834** [vuetifyjs/vuetify#14882]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.82
**OS:** Windows 10

### Steps to reproduce
- Installing vue and vutify with vite
that is

### Expected Behavior
display data in select options

### Actual Behavior
not showing data in options

### Reproduction Link
<a href="https://github.com/amm834/real-time-forum-client.git " target="_blank">https://github.com/amm834/real-time-forum-client.git </a>

### Other comments
not showing data when I try it with object and array

https://github.com/amm834/real-time-forum-client/blob/v-select/src/components/AskQuestion.vue

**Comment by KaelWD** [comment]
Duplicate of #14783
