### ISSUE TITLE
VTextfield counter does not work anymore/documentation needs update

### ISSUE THREAD

**Issue by psychonetic** [vuetifyjs/vuetify#1488]
~~### Steps to reproduce~~
~~Insert a textfield with props counter and max.~~

~~### Versions~~
~~Vue 2.4.2, Vuetify 0.15.0-beta.2, Chrome Mac 60.0.3112.101~~

~~### What is expected ?~~
~~Counter should become red, if the limit is hit and it should be possible to override the max property.~~

~~### What is actually happening ?~~
~~Max property is completely ignored.~~

~~### Reproduction Link~~
~~https://codepen.io/anon/pen/oePaVL~~

**EDIT**: It seems like the textfield was changed. There is no max property anymore. Just use the counter="50" property.

It would be great if you could update documentation at the same time, if there are significant changes in the code or properties of components.

**Comment by nekosaur** [comment]
This is something we haven't updated in dev docs yet I think. The `v-text-field` props **counter** and **required** no longer automatically apply any validation but are instead purely cosmetic. You will need to set up validation rules for these using either the built-in **rules** prop or external libraries.

Additionally you now specify counter length in the counter prop, not max. See your updated example here https://codepen.io/anon/pen/zdJmgY

**Comment by psychonetic** [comment]
@nekosaur Yes, I saw that already. Thanks anyway.

**Comment by johnleider** [comment]
Would this be considered resolved?

**Comment by nekosaur** [comment]
Yeah, I've opened https://github.com/vuetifyjs/docs/issues/192 for updating docs
