### ISSUE TITLE
[Feature Request] [Vuetify 3] Support a message slot in VMessage

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#14886]
### Problem to solve
I used to put links to more information into hints and messages for VTextField, this is no longer supported because the hint prop does not allow html.

### Proposed solution
Bring back the message slot.

**Comment by KaelWD** [comment]
? https://codepen.io/kaelwd/pen/JjMNNBZ

**Comment by tve** [comment]
Yup, that codepen looks great. And if I go back to beta 3.0.0 it works for me too. But with npm:@vuetify/nightly@3.0.0-next-20220325.0 it doesn't. If you tell me how to switch the codepen to nightly I'll work on a repro, unless it's obvious.

**Comment by KaelWD** [comment]
Same codepen with nightly: https://codepen.io/kaelwd/pen/zYpwzEM?editors=1010

**Comment by tve** [comment]
Codepen showing the problem: https://codepen.io/codesurfr/pen/BaJRZmp

The issue is when the v-text-field is in a v-app-bar. In the codepen there are two text fields in the v-app-bar. The one on the far right is plain in the app bar and does not show the hint, i.e., it's not correct, but it's a weird use-case. My real use-case is in a v-overlay that is hierarchically inside the v-app-bar and I duplicated that using a menu: click on the "menu" and the v-text-field in there also does not show the hint. I hope I didn't make a stupid mistake and am wasting your time...

**Comment by KaelWD** [comment]
Toolbars enable hide-details by default, I can see how that might be unexpected though

https://github.com/vuetifyjs/vuetify/blob/ff479075a3273fdcc5f082f23131b6802fefdb1e/packages/vuetify/src/components/VToolbar/VToolbar.tsx#L88-L96

**Comment by tve** [comment]
I see... If you really want to go down that route then V-Menu and V-Overlay would have to revert that, no?

In the end, do you really think that these automagic changes under the hood are worth it? As opposed to letting the user do that stuff themselves? The magic complicates vuetify, complicates the docs, and at least for me, cause endless hours of frustration trying to track thinghs down...
