### ISSUE TITLE
broken v-tooltip

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1489]
### Steps to reproduce
Open first tooltip example from dev docs in codepen

### Versions
0.15-b2

### What is expected ?
Tooltips should work in codepen

### What is actually happening ?
Tooltips don't show, but they work in dev docs

### Reproduction Link
https://dev.vuetifyjs.com/directives/tooltips
https://codepen.io/anon/pen/zdJMOY

**Comment by makslevental** [comment]
still doesn't work (though possibly for a different reason)

![image](https://user-images.githubusercontent.com/5657668/34132566-775941f2-e41e-11e7-908a-1df78a77bfcd.png)

my babel.rc

```
{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime", "syntax-object-rest-spread", "transform-object-rest-spread"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"]
    }
  }
}
```
