### ISSUE TITLE
[Bug Report][3.0.0-beta.0] v-list-item-avatar has no min width

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#14893]
### Environment
**Vuetify Version:** 3.0.0-next-20220329.0
**Last working version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.82
**OS:** Windows 10

### Steps to reproduce
Create a list item with an avatar and really long header

### Expected Behavior
Avatar should always take a consistent width

### Actual Behavior
Avatar collapses

### Reproduction Link
<a href="https://codepen.io/joel-wenzel/pen/abEwExN" target="_blank">https://codepen.io/joel-wenzel/pen/abEwExN</a>

### Other comments
This actually works in the 3.0.0-beta.0 version but seems to be a regression in the nightly build. Looks like this [commit](https://github.com/vuetifyjs/vuetify/commit/529a5ad674f350f12aeddd064af4e028c00b2bb4) is the culprit

**Comment by wiseadme** [comment]
There is no v-list-item-header component in the library, in the example following the link you are using a non-existent component. I tried to reproduce the issue using v-list-item-content and everything works as it should

**Comment by joel-wenzel** [comment]
This was fixed in the latest nightly build
