### ISSUE TITLE
[Bug Report][2.6.1] Child data table not taking entire width of data table

### ISSUE THREAD

**Issue by supeluri** [vuetifyjs/vuetify#14892]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.6
**Browsers:** Chrome 99.0.4844.83
**OS:** Mac OS 10.15.4

### Steps to reproduce
On opening the expanded item, you will be able to see that a data table loads but does takes the column width instead of table width.

### Expected Behavior
Child data table should occupy table width

### Actual Behavior
child data table is taking column width.

### Reproduction Link
<a href="https://codepen.io/SudeepthiRX/pen/WNdjdNJ?editors=1111" target="_blank">https://codepen.io/SudeepthiRX/pen/WNdjdNJ?editors=1111</a>

**Comment by nekosaur** [comment]
You need to use colspan

https://codepen.io/nekosaur/pen/ZEvyyVR

**Comment by supeluri** [comment]
This is not working. https://codepen.io/SudeepthiRX/pen/WNdjdNJ?editors=1111

**Comment by nekosaur** [comment]
https://codepen.io/nekosaur/pen/RwxgZrG?editors=1111

**Comment by supeluri** [comment]
Thank you. It is working.
Can we provide colspan value interms of % rather than header.length?

**Comment by nekosaur** [comment]
No. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-colspan
