### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VSnackbar is cropped when inside toolbar

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#14909]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.136
**OS:** Linux x86_64

### Steps to reproduce
I don't know whether this is a bug or "not supported/as-designed":
- open the codepen
- observe how the left snackbar looks great, but the right snackbar is cropped by the app
- the left snackbar is inside the top-level VApp while the right one is inside VToolBar
- my use-case has the snackbar nested inside a status icon that sits in the toolbar, so it's not that nice or elegant to move it to the app top-level

### Expected Behavior
I expected the snackbar to be lifted to the top of the page so it can always sit on top of everything else

### Actual Behavior
The snackbar is cropped.

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/mdpMpKR" target="_blank">https://codepen.io/codesurfr/pen/mdpMpKR</a>

**Comment by KaelWD** [comment]
This isn't technically "supported" but it did kinda work in v2. Does it actually have to be inside the toolbar? If you just want it in the same component, vue 3 allows multiple root elements so you can put it next to the toolbar instead.

@johnleider any particular reason for hiding overflow in [`8284617` (#14642)](https://github.com/vuetifyjs/vuetify/pull/14642/commits/828461718d81cbc62b59024333e9e8a6bcaf17e6)?

**Comment by tve** [comment]
The structure I have is that the toolbar contains a "connection" component that keeps track of a server connection and displays an icon in the toolbar that varies color to reflect the connection status. Inside that component, I'd like to be able to pop-up snackbars like "connection lost". If I can't do that, then I'd have to place the snackbar into the top-level app component and `provide` some handle onto the attrs of the snackbar so I can inject that into the connection component.

In general, I expect snackbars with position fixed to be pretty much above everything else. I'm not sure how position fixed is supposed to work otherwise.

**Comment by nekosaur** [comment]
Not sure how we're doing v3 snackbar, but shouldn't it be teleporting like overlay?
