### ISSUE TITLE
[Bug Report][2.6.1] On mobile, v-carousel border radius flickers during transition of images

### ISSUE THREAD

**Issue by ikushum** [vuetifyjs/vuetify#14906]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.4
**Browsers:** Chrome 99.0.4844.59
**OS:** iOS 15.3

### Steps to reproduce
1. Create a carasoul with image slideshow, like in [this](https://vuetifyjs.com/en/components/carousels/#custom-transition) example.
2. Apply border-radius (`rounded-xl` for example) on the `<v-carousel>` element.
3. Click the next or previous button.
4. Notice that the border radius flickers when viewed from a mobile device.

### Expected Behavior
The border radius should not flicker on mobile.

### Actual Behavior
The border radius flickers on mobile.

### Reproduction Link
<a href="https://codepen.io/ikushum/pen/JjMrLwZ" target="_blank">https://codepen.io/ikushum/pen/JjMrLwZ</a>

**Comment by KaelWD** [comment]
This looks like a webkit bug, report it to https://bugs.webkit.org/ instead
