### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VSnackbar does not show action slot

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#14900]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.136
**OS:** Linux x86_64

### Steps to reproduce
See codepen, the button and text in the action slot do not show up

### Expected Behavior
To see the close button and "HELLO" text

### Actual Behavior
Button and text do not show

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/mdpMpKR" target="_blank">https://codepen.io/codesurfr/pen/mdpMpKR</a>

### Other comments
BTW, the 3.0.0 docs say that the slot is called "actions" when it's still "action" like in V2 in the code.

**Comment by andrewspy** [comment]
See #14846

**Comment by tve** [comment]
Thanks, I was looking at the code in master instead of next, my bad. Also, I didn't realize the actions slot doesn't pass any props... It works now.
