### ISSUE TITLE
v-select options offsets

### ISSUE THREAD

**Issue by smxsm** [vuetifyjs/vuetify#1490]
### Steps to reproduce

I was hoping that commit https://github.com/vuetifyjs/vuetify/commit/41a3b8094b9d9ee7c5b2e5156b35026d3508852e#diff-02bc5fc96895ec8eecbcb500ed0ea24d that fixes #1377 would also fix my offset problems, but they persist in v0.15 Beta 2 and look like this:

![image](https://user-images.githubusercontent.com/1737182/29748336-3b259bc0-8b15-11e7-800a-d7f49cb39219.png)

![image](https://user-images.githubusercontent.com/1737182/29748338-48a16a9a-8b15-11e7-8ae5-3d792e0b5627.png)

I have a codepen here which at least show a "x" offset, although not as drastic as in my two integrations: https://codepen.io/beffy72/pen/vJRxop

### Versions

VueJs 2.4.2, Vuetifyjs 0.15-beta2, MacOS, Chrome

### What is expected ?

The options should align with the select

### What is actually happening ?

The options are way off if integrated in e.g. OXID eShop or a Shopware Shop

### Reproduction Link

https://codepen.io/beffy72/pen/vJRxop

**Comment by johnleider** [comment]
Due to how v-app works, the outer elements which contain margin are throwing off the calculations. Here is a way to fix that:

https://codepen.io/anon/pen/vJzbPg
