### ISSUE TITLE
[Bug Report][2.5.0] Dropdown menu not closing the second time when clicking on Babylon.js canvas

### ISSUE THREAD

**Issue by Zhernet** [vuetifyjs/vuetify#14902]
### Environment
**Vuetify Version:** 2.5.0
**Last working version:** 2.4.11
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
1. Click on the button to open the dropdown menu.
2. Click on the canvas to close the menu.
3. Repeat 1. and 2.

### Expected Behavior
The menu should close each time you click on the canvas.

### Actual Behavior
The menu only closes the first time you click on the canvas.

### Reproduction Link
<a href="https://codepen.io/Ravagent/pen/QWaMYVX" target="_blank">https://codepen.io/Ravagent/pen/QWaMYVX</a>

### Other comments
This used to work correctly until v2.4.11: https://codepen.io/Ravagent/pen/MWrvLdK

**Comment by KaelWD** [comment]
#13244

Babylon.js is stopping propagation of the mousedown event.

**Comment by Zhernet** [comment]
Thank you.
I'm not sure why it wasn't an issue before Vuetify 2.5.0 but at least I now [how to fix it](https://codepen.io/Ravagent/pen/eYyyZex).
