### ISSUE TITLE
[Bug Report][3.0.0-beta.0] v-app full-height not working - page body does not expand to full height. 

### ISSUE THREAD

**Issue by 0x199x** [vuetifyjs/vuetify#14908]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.25
**Browsers:** Firefox 98.0
**OS:** Linux x86_64

### Steps to reproduce
This issue is present on the documentation itself.  Turn on dark mode so you can see the white `html` background behind the dark background of the vuetify theme.  

### Expected Behavior
Application should fill the page when `full-height` is set

### Actual Behavior
It does not

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/api/v-app/#props-full-height" target="_blank">https://next.vuetifyjs.com/en/api/v-app/#props-full-height</a>

### Other comments
I had trouble with this on my own application, and later noticed that the same issue is visible on the documentation itself.   See reproduction link.  

It seems to be a problem with the `body` element. it refuses to expand, so the v-app can't fill the page.  Attempts to work around this have not been successful.

`html` doesn't get set to 100% height, but can be fixed with `min-height: 100%`
`body` refuses to comply with `min-height: 100%` and only responds to `height: 100%;`
`v-app` therefore can't expand to fill the page when `full-height` is configured

![image](https://user-images.githubusercontent.com/89231731/161390289-cb885979-34b4-4351-bec3-9c2da938fe2d.png)

**Comment by sgpinkus** [comment]
Still having this (?) problem on 3.0.0-beta.7: fill-height prop does nothing, fill-height class works as expected @KaelWD.
