### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Persistent Placeholder should only apply if a placeholder value is set

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#14918]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 100.0.4896.60
**OS:** Windows 10

### Steps to reproduce
Set an input with `persistent-placeholder` prop

### Expected Behavior
The label should only float above if `placeholder `prop is set

### Actual Behavior
Label is always floating even if no placeholder is set

### Reproduction Link
<a href="https://codepen.io/joel-wenzel/pen/ZEvKMgb?editors=1010" target="_blank">https://codepen.io/joel-wenzel/pen/ZEvKMgb?editors=1010</a>

**Comment by KaelWD** [comment]
Not a bug
