### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VTab not correctly selected on initial load when using vue-router

### ISSUE THREAD

**Issue by emikoshi** [vuetifyjs/vuetify#14914]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.84
**OS:** Mac OS 10.15.7

### Steps to reproduce
I believe I'm encountering a bug on the latest beta. On initial page load it doesn't seem to be set to the correct tab if using the 'to' prop (there's an issue with code sandbox loading modules, just click the refresh button in the browser to get rid of the 'cannot use import statement' message). Click the 'Foo' or 'Bar' tab item then refresh the code sandbox browser again to see the issue (if you see the import error again just refresh, it will go away). You can see the selected tab will be 'Home' even though the url is using '/foo' or '/bar' depending on what was chosen.

### Expected Behavior
Selecting the 'Foo' tab then refreshing, the url should contain '/foo' and the 'Foo' tab should be selected.

### Actual Behavior
Selecting the 'Foo' tab then refreshing, the url does contain '/foo' but the 'Home' tab is selected instead.

### Reproduction Link
<a href="https://codesandbox.io/s/inspiring-wilson-6wbbn9?file=/src/App.vue" target="_blank">https://codesandbox.io/s/inspiring-wilson-6wbbn9?file=/src/App.vue</a>

**Comment by KaelWD** [comment]
Groups don't seem to interact with the router at all. Lists have a similar problem, the last clicked item is always active even if the route has since been changed.

**Comment by yuwu9145** [comment]
@KaelWD I would like to give this issue a try and happy to work on any feedback after PR is ready. Cheers
