### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Uncaught SyntaxError: Unexpected token...

### ISSUE THREAD

**Issue by DarshanVirdi** [vuetifyjs/vuetify#14910]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.13
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Included Vuetify into a simple Vue JS 3 project and the application crash on load.
# This happens only on "Tizen OS", the same works fine on local PC, Windows 10.

Created a simple Vue3 project using command line:
vue create vuejs3sample
Build and deploy the sample on the Tizen OS and it works as expected.

Now added Vuetify 3
vue add vuetify
Selected Vuetify 3 Preview

Now when I build and deploy the project on Tizen OS, I see the error in console:
# Uncaught SyntaxError: Unexpected token...

Points to the vendor chunk js file
Absolutely no clue what is wrong with the project.
Tried to remove all Vuetify code from view and components but still the same error.
Just included Vuetify module and the application still crash on load.

### Expected Behavior
Should work on Tizen OS as well

### Actual Behavior
Not working on Tizen OS

### Reproduction Link
<a href="https://github.com/DarshanVirdi/Vue-Vuetify" target="_blank">https://github.com/DarshanVirdi/Vue-Vuetify</a>

**Comment by DarshanVirdi** [comment]
![image](https://user-images.githubusercontent.com/10285443/161410174-900f0202-d90b-411c-bc90-1abedf31236d.png)

**Comment by DarshanVirdi** [comment]
![image](https://user-images.githubusercontent.com/10285443/161410202-9df9efe1-d208-4d38-8085-1ecd7db0a8c1.png)

**Comment by DarshanVirdi** [comment]
![image](https://user-images.githubusercontent.com/10285443/161410215-484c49fa-b7f9-4303-b418-426637416da7.png)

**Comment by tve** [comment]
Browser version?

**Comment by DarshanVirdi** [comment]
The issue can be reproduced using the Tizen Mobile Emulator 4.0.

![image](https://user-images.githubusercontent.com/10285443/161410245-63994240-e093-4b95-b36f-179047f7f433.png)
![image](https://user-images.githubusercontent.com/10285443/161410254-3f0ff731-35d1-447b-9e41-bf02273a2351.png)

**Comment by DarshanVirdi** [comment]
> Browser version?

Details of the Browser, the Hardware that I am developing the application for is running Tizen 4.0 OS

https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

**Comment by DarshanVirdi** [comment]
Also on the same hardware, when I develop the sample app using Vue 2 + Vuetufy 2, it works fine.
Only with Vue 3 + Vuetify 3 get this error.

**Comment by tve** [comment]
According to https://caniuse.com/mdn-javascript_operators_spread_spread_in_object_literals spread operator in objects came to Chrome in V60. Tizen OS uses chromium "M56". Dunno, but perhaps you can write a very simple test that uses
```
const foo = { color: 'red' }
const bar = { ...foo, size: "large" }
```
and see whether it barfs on that `...`?
I may be completely off here...

**Comment by DarshanVirdi** [comment]
The following sample project with Vue 2 & Vuetity 2, works on the emulator and also on the hardware.
https://github.com/SoftwareAteliers/asp-net-core-vue-starter

![image](https://user-images.githubusercontent.com/10285443/161410683-5028d8c8-d9b0-43cb-bcfd-b704dde770e9.png)
![image](https://user-images.githubusercontent.com/10285443/161410742-41ab3ac9-1c74-4c22-8191-4af8b571e4f4.png)

**Comment by DarshanVirdi** [comment]
> According to https://caniuse.com/mdn-javascript_operators_spread_spread_in_object_literals spread operator in objects came to Chrome in V60. Tizen OS uses chromium "M56". Dunno, but perhaps you can write a very simple test that uses
> 
> ```
> const foo = { color: 'red' }
> const bar = { ...foo, size: "large" }
> ```
> 
> and see whether it barfs on that `...`? I may be completely off here...

This is a simple project, not using spread operators in the code.
If I include the same, I dont get any compile errors but the same error when run the project in emulator.

**Comment by tve** [comment]
Well, your first screen shot shows the red squiggly line starting on the `...` operator and the error message in the second screen shot says that `...` is an unexpected token.
You probably need to tune your build settings to build for older browsers, but I (fortunately) don't have experience with that stuff.

**Comment by KaelWD** [comment]
Vuetify 3 only supports modern browsers.
