### ISSUE TITLE
[Bug Report][2.6.4] v-select with custom value-comparator on list of objects doesnt work well

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#14927]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.13
**Browsers:** Chrome 100.0.4896.60
**OS:** Windows 10

### Steps to reproduce
Create a v-select with objects as items and create a custom value-comparator to use.

### Expected Behavior
The list items in the v-select menu must only activate the selected item

### Actual Behavior
The list items in the v-select menu selects all items

### Reproduction Link
<a href="https://codepen.io/Tuffy45/pen/wvpyZQB?editors=1010" target="_blank">https://codepen.io/Tuffy45/pen/wvpyZQB?editors=1010</a>

**Comment by KaelWD** [comment]
1. You're missing `:value-comparator="compare"`
2. value-comparator still needs a defined value property on the objects, or in your case `item-value="id"`
3. You probably don't need it or the slots here, just `item-value="id"` and `item-text="label"` should do what you want
