### ISSUE TITLE
[Feature Request] v-slide-groip and virtual scroll

### ISSUE THREAD

**Issue by Mioleris** [vuetifyjs/vuetify#14926]
### Problem to solve
Is there ability to add virtual scroller to v-slide-group ? 
Currently tryin to add this https://github.com/Akryum/vue-virtual-scroller virtual scroll but v-slide-group is not working correctly after.

### Proposed solution
Support for virtual scroll

**Comment by mcheung610** [comment]
bump. Looks like a cool feature to add.

**Comment by johnleider** [comment]
This should now be possible as of the latest version.
