### ISSUE TITLE
[Bug Report][2.6.1] Datatable - Cannot tab through checkboxes

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#14924]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 99.0.4844.84
**OS:** Windows 10

### Steps to reproduce
Create a datatable with `show-select` enabled.

### Expected Behavior
You should be able to use the keyboard (namely the `Tab` key) to move through the checkboxes. This is important for accessibility.

### Actual Behavior
The checkboxes rendered in the table are not tab-able.

### Reproduction Link
<a href="https://codepen.io/dmm545/pen/NWXywKY?editors=101" target="_blank">https://codepen.io/dmm545/pen/NWXywKY?editors=101</a>

**Comment by lioneaglesolutions** [comment]
Resolved in V3

https://play.vuetifyjs.com/#eNqtls1u2zAMgF9FMDC0BWo7/22NrOjQ7qfrDrsOTQ+KzaRaZcmQlHRZkXcfFTuJrdhpAswnixTJjxRl8/HN+5RlwXwGXuQNDaQZpwauR4KQ4dxPqKG+oWMOVkDI3E9lAvzjyNPAITaQjLxcEz0DTUBpVBVvGw1Dr1aegNagzEZh5f6c8hmgUtAU1gr9LF/9PEAuiDnV1gOK5tQwKfx2vvd6GJYhEXsYlnLApY4Vy8wqH/iTSWVIAhM644a85b6tNTk9Wy8JUWBmSmzXyFPkGpHHp/OtuMgTpVsZKdvZxzDDISInd3ny5LTdak3Ro5ozMT07KbmzD+VsKnC3NlQZV6mR3mYZkQnlGhztCyzQ0JaxaresrN42QLeUS8VAn5wXpvFa0GjyhSK/hS4sJtQ0b76laqwr22MraTb4qaQBJiomWS5rNrpXEi0+bC0YCqrby0e2bsH9Z2aLaNNV8i8I8ktOZ7uHsa5WRNr9K0eHdYnIIGjtmGD+Een0HHmRZER6OyY2G4yw70Br0e9jILECmhJNRfLK4udm/k73oo7/qol/Z3uJv/uf+D/jjWdqD/OgU8fcbi66S7aB3jXJoatZHgJ9O8ti+uJcvzJ1t9Wvo+4GbkUL6MHRlb48GvorfoZAjbFXkj3g/cFx5e65V2JD3g1cVdEj1QiHoH8HzhdkDFTsIb+oLXmrCfyq8XLumuTgVekh3D8k5yyT2R7qq9r2bgWueE1dPfcydS1z1c0hzN+kgEUs03EzdK/lUhTd3QB92djdg8A9tBy7VxUfwn0nxWzPt7vXry10p9/UH/3qt6xyJesbu3N8sR+YecBfayN1v11b6U7jdRy49dxQu2eQMzffxe3PdJm/5EpcDMNi1PLOPc7Eiw5+aylwqFzlOPJijYPf5r+LU6IxmY7CME4E7sShks1VIMCEIktDHEcNmyxusHmCTpgwbdYin9OxDlbOrKenkVhiQJba0c5PaeZEzRWryEWtRx56sut3EG5wW6hmwrAU/ESmK5beRQ5TkgegU3+s5CsOFuhl5BUVWsWxxAfEei9dDLHjOrQzJChfgcApFNShKTlmlbQc3U5qxVEvveW5l9th7VfQ3tM/4VovwA==
