### ISSUE TITLE
[Bug Report][2.6.4] v-item in v-item-group will not honor disabled prop

### ISSUE THREAD

**Issue by jaysonpotter** [vuetifyjs/vuetify#14923]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.84
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-item-group with one, or more v-item. Add the "disabled" prop to the v-item. Item is still clickable.

### Expected Behavior
As per the documentation, https://vuetifyjs.com/en/api/v-item/#props-disabled, disabled should "Removes the ability to click or target the component."

### Actual Behavior
Component is clickable and targetable.

### Reproduction Link
<a href="https://codepen.io/jaysonpotter/pen/xxpYqZL" target="_blank">https://codepen.io/jaysonpotter/pen/xxpYqZL</a>

### Other comments
I went as far back as 2.0.0 to see if the issue existed then and it certainly has. I do not have historical experience of this working.

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqNU0tvozAQ/iuzvnDB0CaVVkLZ3ax63tMeQw4ET4gbY5Dt0EYR/71jyIPHoc0p/mb8PYbx5sL+1nXUnJAlbOWwrFXm8HeqAVYNlwTwwlSnGiwqzB0KnqvM2l8p2xW8NrLMzDllXX93I6+0y6RGc4U60FTv9+O1Sz3OAA3fV4YoNUgNy5QNa8kRz740RonAe3hejOFSEPgyxAa690SkZ1XlqPUC0v6/BgvvEV99whBcVRQKoU0ZCGmznUIxYuuTZEaMQbJ8G9EmEHyv8AMyJQvNc9QOTTAR2o4j+J/IzHGKHVAWB+958fQ0v7HOlcyPVO1NTxsmvsm5kM0Uo6lefTv8cPywBO/df/53/gwd1ieYy8/4AS7D2cIfCG7/A0ggePV24R/+CKBtZ+ZicjcdddzPevw9CfQfdLhcvq9Sj+2j82P9+upwQ28U/ZYTtIrvj4CFTEl9tNGbrTQ9j4u/kLLc2pQlsOkpU3ZwrrZJHOdCU6dAJRsTaXSxrsuYHpaT+/N6GS2iBeWy7gZxle1s1JF5pm2qWxKUZV0Zx8usnqj2hU65QzxGTP78hYU1tcXmpJ0skYuq7Ly8/OzNDPAIbcl3NCyLhlhSFg50vONvaH0VlyRm1DHpNWi4QS3Q+PX6XqTJtVGsSW0WzcvT3rWsDVl/j2bfmWbbT5s0geQ=
