### ISSUE TITLE
[Bug Report][2.6.4] v-menu + dynamic activator, activatorFixed prop does not reset 

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#14922]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.13
**Browsers:** Chrome 98.0.4758.102
**OS:** Linux x86_64

### Steps to reproduce
- Click on "Dropdown" button, the menu is shown under the button;
- Click on "Toggle Menu" twice;
- Click on "Dropdown" button, the menu is shown somewhere at the left;

### Expected Behavior
It should work in a stable way. Menu should be shown under "Dropdown" button

### Actual Behavior
Menu shown in a different place after reinitialization

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/rNpJyzm?editors=1010" target="_blank">https://codepen.io/kasheftin/pen/rNpJyzm?editors=1010</a>

**Comment by Tofandel** [comment]
Why are you attaching it within itself? Do you realise the logic issue?

Your ref is actually undefined

https://codepen.io/Tofandel/pen/yLprVRP?editors=1010

**Comment by Kasheftin** [comment]
Attach can be considered as a reference. This case there's no logic issue - when the menu is going to appear, it should search for an activator node and attach there. It does not matter in which order the nodes are mounted.

By reporting this issue I want to point out on the bug here, https://github.com/vuetifyjs/vuetify/blob/45818a552b09ccb5d0d5c7ab0b391c50ce192c1a/packages/vuetify/src/mixins/menuable/index.ts#L284
If attach prop is dynamic, it's false initially, then `activatorFixed` variable can be set to true. If then activator becomes true, `activatorFixed` does not reset. On my opinion it should be like 
````
if (this.attach !== false) {
  this.activatorFixed = false
  return 
}
````

This change solves the initial issue.

There's one more repro: https://codepen.io/kasheftin/pen/rNpJyzm
It's more artificial but it does not use attach inside activator.
Repro steps: 
1. click on menu, notice it appears under the button
2. click outside to hide the menu
3. click on toggle
4. click on menu - it appears in some other place, but it does not matter
5. click outside to hide the menu
6. click on toggle to return the system to initial state
7. click on menu - now it appear in the different place
![Peek 2022-05-23 12-48](https://user-images.githubusercontent.com/379267/169792980-67694262-b996-4464-baf4-27927219effb.gif)
