### ISSUE TITLE
[Bug Report][3.0.0-beta.0] v-range-slider always takes up full width of the page

### ISSUE THREAD

**Issue by nielsbos1** [vuetifyjs/vuetify#14934]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
Whenever I attempt to use the v-range-slider in a project, it's elements are kind of all around the page. Even when I put it in a v-col element and set that v-col element to a certain size, the v-range-slider will take up the whole page. The v-slider does work correctly. It seems that when I add an extra element into the v-col element, such as a v-slider, the v-range-slider is displayed correctly. When I use 2 v-range-sliders, they are both displayed incorrectly.

### Expected Behavior
Correct display of v-range-slider

### Actual Behavior
v-range-slider takes up full width of page

### Reproduction Link
<a href="https://github.com/nielsbos1/v-range-slider-issue" target="_blank">https://github.com/nielsbos1/v-range-slider-issue</a>

**Comment by nekosaur** [comment]
It looks okay to me? https://codepen.io/nekosaur/pen/NWXMJOy

**Comment by nielsbos1** [comment]
Hi @nekosaur,

Thanks for your reply! I have also noticed that it does render in the correct way in codepen. The steps I have taken in the git repository are:
1. Initialize a new vite project
2. Add vuetify
3. Add the v-range-slide code in the App.vue file

When I run `npm run dev`, it's rendering as in the picture below (screenshot of full width of the page):
![image](https://user-images.githubusercontent.com/65466627/162611289-775fd4a7-ad78-49da-b4d0-c9bfcb4cda03.png)

Since I am using just the standard steps, I am a bit puzzled as to why there would be a difference between codepen and implementation in a standard project. Would you have any idea what could cause such a difference? Happy to further look into this if you have any suggestions.
