### ISSUE TITLE
[Bug Report][3.0.0-beta.0] progress-linear not clickable

### ISSUE THREAD

**Issue by cleemansen** [vuetifyjs/vuetify#14936]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Google Chrome, Firefox 100.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. use a `v-progress-linear`
2. click on the component

### Expected Behavior
- The value should change after clicking like it was before (vuetify 2.x).
- compare to https://vuetifyjs.com/en/components/progress-linear/#query
- the feature request of the expected behaviour: https://github.com/vuetifyjs/vuetify/issues/5147

### Actual Behavior
- after clicking on the bar nothing happens

### Reproduction Link
<a href="https://codepen.io/mansen/pen/oNpqRba" target="_blank">https://codepen.io/mansen/pen/oNpqRba</a>

### Other comments
You can reproduce this also with https://next.vuetifyjs.com/en/components/progress-linear/#default

**Comment by johnleider** [comment]
We are not implementing this in v3 because of it's inaccessibility and that the functionality is out of scope for this component.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
