### ISSUE TITLE
[Bug Report][2.6.4] [VMenu] getTiles is selecting too much elements

### ISSUE THREAD

**Issue by Glandos** [vuetifyjs/vuetify#14933]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Linux x86_64

### Steps to reproduce
- Focus the autocomplete text input
- Navigate with the down arrow to the fourth element
- Press Enter
- Press Up or Enter again

### Expected Behavior
In the first (non customized) autocomplete, the 3rd element is preselected on Up or the 4th element is deselected on Enter.

### Actual Behavior
In the second autocomplete, the 2nd element is preselected on Up and the 2nd element is selected on Enter.

### Reproduction Link
<a href="https://codepen.io/glandos/pen/wvpmxVE" target="_blank">https://codepen.io/glandos/pen/wvpmxVE</a>

### Other comments
This happens because of https://github.com/vuetifyjs/vuetify/blob/860be6b0bff74b6cd81320259879ae9dc5a77f1d/packages/vuetify/src/components/VMenu/VMenu.ts#L388
The CSS selector will select all `.vue-list-item` even if there are nested list items that should not belong to the menu tiles.

The following code should fit:
```js
const firstItem = this.$refs.content.querySelector('.v-list-item, .v-divider, .v-subheader')
this.tiles = this.tiles = Array.from(firstItem?.querySelectorAll(':scope ~ .v-list-item, :scope ~ .v-divider, :scope ~ .v-subheader'))
```
But it uses some recent operators such as null coalescing and [`:scope`](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) pseudo-class

**Comment by Glandos** [comment]
I have a workaround for now. Instead of
```html
<v-autocomplete>
  <template #item="{ item, parent, on, attrs }">
    <MyComponent />
  </template>
</v-autocomplete>
```
and in `MyComponent.vue`:
```html
<template>
  <v-list-item>
    <!-- code -->
  </v-list-item>
</template>
```

I have in `MyComponent.vue`:
```html
<template>
  <div style="display: contents;">
    <!-- code -->
  </div>
</template>
```
The `display: contents` enable all tag like `v-list-item-icon` in `MyComponent` to be styled correctly. And since I removed `<v-list-item>`, the nested tags are gone, and the keyboard actions are working fine.

I still think it's a bug though.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Glandos** [comment]
Closing this for "inactivity" seems a bit rude to me. I took the time to extract a basic example from my complex code, and even write a possible workaround. Making a patch is out of scope for me, because the code base is huge, and it would mean too much time to dig in.
At least, if someone could adapt the CodePen with Vuetify 3 and prove that this behavior disappeared, this would be a better help.

**Comment by johnleider** [comment]
> Closing this for "inactivity" seems a bit rude to me.

There's no one to work on it. Most v2.x issues are going away.
