### ISSUE TITLE
[Bug Report][2.6.4] v-autocomplete ajax with "cache-items" and mutliple and no-filter prop is not allowing to select more than 20 results

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuetifyjs/vuetify#14948]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.4987.0
**OS:** Windows 10

### Steps to reproduce
Try to hit a key and then select all results. Then hit another key and select more results.

### Expected Behavior
The second query will fetch more and the menu will show them.

### Actual Behavior
The second query will fetch more but the menu will not show them.

### Reproduction Link
<a href="https://codepen.io/arvanoid/pen/abEKdzz" target="_blank">https://codepen.io/arvanoid/pen/abEKdzz</a>

### Other comments
I tried to manually push results to cachedItems but with no luck. I also noticed that the only way to select more than 20 results is to scroll down triggering a new page load before scrollbar disappears.

**Comment by dionysiosarvanitis** [comment]
Possibly related to https://github.com/vuetifyjs/vuetify/issues/11365

**Comment by lioneaglesolutions** [comment]
Closing as this is resolved in V3

https://play.vuetifyjs.com/#eNqNVm1v2zYQ/iucPjQOEFlZ22GA52QtUqzN2iRFky0Y6nw4S+eINUVqJOWXtf7vO1KKrZAOWsCAxeeO9/IcybvPX5PXdT1cNJiMkrHFqhZg8XQiGRsvUquUmIJmuRJKn0wSiyAmiZf25anlVuDptaWtzKDA3HIlx1moMJHbndBYlSvyhhZbkLFFWqkCBflpbUySQDIyCDovvYL72CmMhIKCy3sSdV89Gae0DEn8/w7PBRgHV6v05Q4tUBpu14RTeDOlLUwF9jZBXmLaWuqgkheYSpUWYOERVqAFLrZ6AqY+udsSLDOeK9DI1qphM62q33dOjF0LdJHBKl3ywpYj9uL4uF799qBy6rjtU9indmol47mSzkDB00JZky5QW5774rmtpNKWeFciWo+zXv3HJte8tl4NVzURQdTMoBGWfW1duXzZ4PBhyZhG22i5W1PKbS1GbAbC4NFO4Akcsc93Payt6YjJRohHsDsLMewIdCZ2EGMHr4lkqOCgp9iiZh6BFWqiRLJrqFQk1Pw/JWN0DtKACeAzEJxOiuSh/pm7NlCoCJbSXZG8sYHkDQpY0qEIYW4sxWqZmjGy2VTTyNUfWKAmRgrmb6Fxqhc810qiiZUpLF6E6FtU+j7SfdtAFUDvKEbOA/C8gDJM9FwILhUP+TqXBYeI3HO1DKH3+9h+j9I2+XwdwB9UwynTyOwFcBnyeQHalCAEOzcCZBF6IPHa4RFsDN3+xqC10Rael/weZARTpY2yUVDcGPer65BGJ1GNjmAlbZzbJU71npN9iQuIqnuJS/YOqtqUPDpfTvYnaoMhqU5wgSt6TfYI/lF6HsL0TJTsDLSiwkcReOEbmMd8eBHS20HUuxo+UZirkoeBXM0Fnbvoxl9pvFdhNT6CgCbEUEqzFguIb+/Hhh5NxT7F2X8qqRt1MQaia9U8zUAr3MvADcWBxmBYmhtcRTfgLwtlAP2NuqIjEqKcLrTcH2gri5K+BTog8t5G5N2iseypTdxQvzE82rNWFRnro7sHf9N+bDpgCdY9/tvm0XYDNliA6LUYGgVAsGfP/N9PJyfMltwM2xbhYL/8lwq3vn4YQ4w3sfXauXv4r9BSMamPbF0EuymCR/69h66vMfKvm+38wliWsWteNa6FFgy+wKq11m9m9oZXSOdgQJ3z5LRvubPtW6Oz7DPzj/lwxoVFPcBox7bpkuzbN3ZwcDi06oNaoj4Dg4PDIZcFrq5mg8Fir/yQnbL0577FzZaqPdn6Nr6Tb47YL8fHT3BL9R1n3RCRHCV0HeZm+MUoSYOmz4EmLEPj2LaFT5LS2tqMsiwvJGnSwMcXeijRZrKuMhpRLZ+tX70YPh8+zwpqiQ9QSk3fDL0xZ+luIjfkkFduaEkrqAOvrcB77ricJGTJrb8TwitSy3QjLZWQ5qrKx/Ly1zaYHj5EU6VTrZYGNVmZJB0x3o+L+Ad8fS9dchGZzsgfTXqpRqq6Rv2jKQXbHqUVyKLUulJvks1R0u4j7n3Qyd3/LcCLRg==
