### ISSUE TITLE
[Feature Request] how  scroll to  specific row  in  v-virtual-scroll  with  code

### ISSUE THREAD

**Issue by samantrader** [vuetifyjs/vuetify#14950]
### Problem to solve
hi   
how i  can   scroll  to  specific row  in  v-virtual-scroll  with  v-list-item  with   code
 

### Proposed solution
donot  know

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
