### ISSUE TITLE
Bug 0.15: viewport offset on y-axis doesn't apply well on menu (and selects)

### ISSUE THREAD

**Issue by Kylart** [vuetifyjs/vuetify#1495]
### Steps to reproduce
Hover the buttons

### Versions
0.15-latest

### What is expected ?

The menu should open in the viewport in a way that a maximum of options are visible.

### What is actually happening ?

* The `menu` opens outside the viewport (1/2 time only at the very bottom).
* The `menu` changes the side of the viewport to fit in the page when on the bottom of the page

_Same things with the `selects`_

Here's a gif showing what's happening

![2](https://user-images.githubusercontent.com/18316666/29750307-ba49cab6-8b3d-11e7-9fee-df46f2788d31.gif)

### Reproduction Link
https://codepen.io/Kylart/pen/QMVYva?editors=1000

**Comment by baroncurtin2** [comment]
Also happening with Select components.

![image](https://user-images.githubusercontent.com/17049118/29790137-aa7f50e6-8c06-11e7-94a0-69852a8a5b1b.png)
