### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Checkbox Label Slot not working

### ISSUE THREAD

**Issue by travisricks** [vuetifyjs/vuetify#14951]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Chrome 99.0.4844.84
**OS:** Mac OS 10.15.7

### Steps to reproduce
When using the label slot for a checkbox nothing is rendered in the browser. If the label attribute is used, it works as expected. This demo code is the example from the Vuetify documentation.

### Expected Behavior
The checkbox should rendered with the provided slot label.

### Actual Behavior
Nothing is visible in the browser. In the devtools, HTML comments are inserted where the label template is supposed to be.

### Reproduction Link
<a href="https://codepen.io/travisricks/pen/gOoKJdJ" target="_blank">https://codepen.io/travisricks/pen/gOoKJdJ</a>

**Comment by KaelWD** [comment]
Already fixed by ba892ae98973b3a9ab7242db97459129099b1c20

**Comment by travisricks** [comment]
Hi @KaelWD,
That's great that it's already been fixed! I'm not sure if it said in the commit or not, but do you know when this fix will be available in the package?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/installation/#nightly-builds
