### ISSUE TITLE
Normalise "direction" props

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#14952]
https://github.com/vuetifyjs/vuetify/pull/14920#issuecomment-1093790709

- VOverlay - `anchor`/`origin` as `'top' | 'bottom' | 'start' | 'end' | 'center' | 'top start' | 'end center'` etc.
- VNavigationDrawer - `position` as `'left' | 'right' | 'bottom'`
- VBadge - `location` as `${'top' | 'bottom'}-${'start' | 'end'}`
- VSnackbar - `centered` + `top`/`bottom`/`left`/`right`

`makePositionProps` used by VSheet, VAlert, VBanner, VBtn, VCard, VFooter, and VSnackbar also includes
 - `top`/`bottom`/`left`/`right`
 - `absolute`/`fixed`
 - `position` as `'static' | 'relative' | 'fixed' | 'absolute' | 'sticky'` (uses utility classes)

**Comment by ken-playerlync** [comment]
Nomenclature is indeed important for ease of use of a framework. I think if position is tied to an understanding of CSS positioning, it should remain as one of the terms, the other I think that makes sense is location, because location can be synonymous with anchor, origin in Vuetify terms. @KaelWD
