### ISSUE TITLE
[Bug Report][3.0.0-beta.1] There is No tag field in Verify

### ISSUE THREAD

**Issue by ps000-simreka** [vuetifyjs/vuetify#14969]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 3.0.0-alpha.13
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Dear sir/Madam
There is No tag field in Verify

### Expected Behavior
There is No tag field in Verify

### Actual Behavior
There is No tag field in Verify

### Reproduction Link
<a href="https://codepen.io/virtualadrian/pen/pOeVPX" target="_blank">https://codepen.io/virtualadrian/pen/pOeVPX</a>

### Other comments
There is No tag field in Verify

**Comment by johnleider** [comment]
I'm not sure what issue you are having but this is not a valid bug report.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
