### ISSUE TITLE
[Bug Report][2.6.4] Set aria-disabled on menu items

### ISSUE THREAD

**Issue by jasonatball** [vuetifyjs/vuetify#14968]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Edge 100.0.1185.44
**OS:** Windows 10

### Steps to reproduce
Create a v-menu with v-list-item(s). Set :disabled="true". The aria-disabled attribute is not set and thus frameworks such as playwright can not determine if the list-item is disabled.

### Expected Behavior
aria-disabled is set

### Actual Behavior
aria-disabled is not set

### Reproduction Link
<a href="https://github.com/microsoft/playwright/issues/13583" target="_blank">https://github.com/microsoft/playwright/issues/13583</a>

### Other comments
Perhaps this has been addressed in Vuetify 3 but here is the link to the issue in playwright: https://github.com/microsoft/playwright/issues/13583

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/3df308f3305a77b1c2354fc7529bedc18b243dce/packages/vuetify/src/components/VList/VListItem.ts#L132

![Screenshot_20220421_203835](https://user-images.githubusercontent.com/16421948/164440976-54859c44-88fe-44d8-92dd-8f8065f334ab.png)

**Comment by jasonatball** [comment]
@KaelWD has this been released or is this the Vuetify 3 beta?

**Comment by KaelWD** [comment]
That's `<v-list-item disabled>` in 2.6.4

**Comment by jasonatball** [comment]
I think the issue is that the aria-disabled attribute gets set in the div above the div containing the text so when playwright's location matcher finds the text it only sees `disabled="disabled"`. Here's an example from my application:

```
<div data-v-6ca33932="" tabindex="-1" aria-disabled="true" id="list-item-672" class="v-list-item v-list-item--disabled theme--dark">
  <div data-v-6ca33932="" class="v-list-item__icon">
    <i data-v-6ca33932="" aria-hidden="true" class="v-icon notranslate v-icon--disabled mdi mdi-format-list-numbered theme--dark">
    </i>
  </div>
  <div data-v-6ca33932="" disabled="disabled" class="v-list-item__title" style="cursor: pointer; opacity: 0.2;">Show Call Stack</div>
</div>
```

I wanted my playwright check to be: `await expect(page.locator("text=Show Call Stack")).toBeDisabled();`
But instead I had to resort to: `await expect(page.locator('text=Show Call Stack')).toHaveAttribute('disabled', 'disabled')`

**Comment by jasonatball** [comment]
I should also note it could be the way I'm building my menus. We're constructing them dynamically to allow for radio, checkbox, or normal menu options. So I create it like so:

```
     <v-menu offset-y v-for="(menu, i) in menus" :key="i">
        <template v-slot:activator="{ on, attrs }">
          <v-btn
            v-bind="attrs"
            v-on="on"
          >
            <span v-text="menu.label" />
            <v-icon right> mdi-menu-down </v-icon>
          </v-btn>
        </template>
        <v-list>
          <v-radio-group
            :value="menu.radioGroup"
            hide-details
            dense
            class="ma-0 pa-0"
          >
           <template v-for="(option, j) in menu.items">
              <v-divider v-if="option.divider" :key="j" />
              <v-list-item
                v-else
                @click="option.command"
                :key="j"
                :disabled="option.disabled"
              >
                <v-list-item-action
                  v-if="option.radio"
                  :disabled="option.disabled"
                >
                  <v-radio
                    color="secondary"
                    :label="option.label"
                    :value="option.label"
                  />
                </v-list-item-action>
                <v-list-item-action
                  v-if="option.checkbox"
                  :disabled="option.disabled"
                >
                  <v-checkbox
                    v-model="checked"
                    color="secondary"
                    :label="option.label"
                    :value="option.label"
                  />
                </v-list-item-action>
                <v-list-item-icon v-if="option.icon">
                  <v-icon v-text="option.icon" :disabled="option.disabled" />
                </v-list-item-icon>
                <v-list-item-title
                  v-if="!option.radio && !option.checkbox"
                  :style="
                    'cursor: pointer;' + (option.disabled ? 'opacity: 0.2' : '')
                  "
                  :disabled="option.disabled"
                  v-text="option.label"
                />
              </v-list-item>
            </template>
          </v-radio-group>
        </v-list>
      </v-menu>
```
Where menus is an Array prop passed in like so:
```
      menus: [
        {
          label: 'File',
          items: [
            {
              label: 'Show Call Stack',
              icon: 'mdi-format-list-numbered',
              disabled: !this.scriptId || this.scriptId === ' ',
              command: () => {
                this.showCallStack()
              },
            },
          ],
        },
      ],
```

Here's a link to the full source: https://github.com/BallAerospace/COSMOS/blob/master/cosmos-init/plugins/packages/cosmosc2-tool-common/src/components/TopBar.vue

**Comment by KaelWD** [comment]
v-list-item-title doesn't have a disabled prop

**Comment by jasonatball** [comment]
@KaelWD that you for your support. Can't wait for Vuetify v3!

**Comment by jasonatball** [comment]
@KaelWD sorry to bother but I'm trying to get to the bottom of this. The Playwright team has issue https://github.com/microsoft/playwright/pull/5209 which says:

> This would be disabled:
> `<button aria-disabled="true">Click</button>`
> so would this:
> `<div role="button" aria-disabled="true">Ok</div>`
> but this would not be disabled:
> `<div aria-disabled="true">Enabled</button>`

Since the `v-list-item` is a nested stylized divs I think we fall into the last option which is not marked disabled.

**Comment by KaelWD** [comment]
Clickable list items in a menu have `tabindex` and `role="menuitem"`

**Comment by jasonatball** [comment]
Right and then it appears that when Vuetify marks a menu item as disabled it _removes_ the `role="menuitem"`. I manually stepped through my test and added the `role="menuitem"` _back_ as Playwright was executing and it correctly detected the menu item as disabled.

Why are we removing the `role="menuitem"` when the item is disabled? The styling was not affected by adding back the role. I think this matches the behavior that Playwright is implementing as described in my previous post. Once the `role` is removed they no longer consider it actionable (I think).

**Comment by jasonatball** [comment]
I don't think [this line](https://github.com/vuetifyjs/vuetify/blob/3df308f3305a77b1c2354fc7529bedc18b243dce/packages/vuetify/src/components/VList/VListItem.ts#L145) should be conditional on `isClickable`
