### ISSUE TITLE
Expansion panels broke in latest update

### ISSUE THREAD

**Issue by Dmitry1987** [vuetifyjs/vuetify#1496]
Hi,
for no visible reason, the CSS of expansion panels broke (I didn't updated the code all week, so it wasn't caused by my template changes).

I suspect it's because new Vuetify version was released.

### Steps to reproduce
Use 'expansion panel' with many chips inside.

### Versions
0.15

### What is expected ?
backward compatibility

### What is actually happening ?
all expansion panel titles and content goes crazy.

### Reproduction Link
Private dashboard, no link

![image](https://user-images.githubusercontent.com/9369080/29751203-41ddb0d6-8b53-11e7-89cd-0df1ac5f6852.png)

I can paste the expansion panel template, but it's massive...  Important thing is - it uses everything like in default example:
```
    <v-expansion-panel v-if="showECSclusters[routePath].indexOf(cluster.clusterName) != -1">
      <v-expansion-panel-content v-for="(oneService,serviceIndex) in cluster.services" :key="serviceIndex">
        <div slot="header">
          <v-layout row wrap>
                <v-flex xs3>
                    <v-chip class="primary subheading white--text">
                        {{oneService.serviceName}}
                    </v-chip>
                </v-flex>
                <v-flex xs3 class="mt-3 body-2">
...
```

**Comment by Dmitry1987** [comment]
I pointed my import to version 0.14.11 in unpkg.com (someone suggested, I didn't knew it's possible :D )
and it got back to normal. So consider this a bug report :) .  I can provide more details if needed.

![image](https://user-images.githubusercontent.com/9369080/29751373-4ccb67e8-8b55-11e7-954c-0c53d4f69100.png)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Dmitry1987** [comment]
Hi @johnleider , sorry if I missed something. But I did follow the template, that's why you see all those sections "Steps to reproduce"/"Versions"/"What is expected?"/"What is actually happening?".

Which details did I miss, that would help to debug this?

Thanks :+1:

**Comment by nekosaur** [comment]
Create a minimal codepen where you reproduce the error
