### ISSUE TITLE
[Bug Report][3.0.0-beta.0] V-Select typing validation of modelValue and Items props

### ISSUE THREAD

**Issue by Esurnir** [vuetifyjs/vuetify#14962]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.33
**Browsers:** Firefox 99.0
**OS:** Windows 10

### Steps to reproduce
Clone the repro.
Open it in visual studio code
Have volar installed (I personally use version v0.34.7).
Open HelloWorld.vue

### Expected Behavior
The v-select line of the template does not show any error in visual studio code

Executing vue-tsc does not show any type error on this particular file (ignoring other vue type errors)

### Actual Behavior
volar mentions two error on v-model and items.
For v-model :
For V-Model : 
`Type 'Monster | undefined' is not assignable to type 'string | number | unknown[] | undefined'.
              Type 'Monster' is not assignable to type 'string | number | unknown[] | undefined'.ts(2322)
              index.d.ts(477, 13): The expected type comes from property 'modelValue' which is declared here on type 'IntrinsicAttributes & Partial<{ transition: string | boolean | (TransitionProps & { component?: Component<any, any, any, ComputedOptions, MethodOptions> | undefined; }); ... 10 more ...; openOnClear: boolean; }> & Omit<...>' `
For items :
`Type '{ title: string; value: { name: string; shouts: string; lethal: boolean; }; }[]' is not assignable to type 'SelectItem[]'.
              Type '{ title: string; value: { name: string; shouts: string; lethal: boolean; }; }' is not assignable to type 'SelectItem'.ts(2322)
              index.d.ts(475, 13): The expected type comes from property 'items' which is declared here on type 'IntrinsicAttributes & Partial<{ transition: string | boolean | (TransitionProps & { component?: Component<any, any, any, ComputedOptions, MethodOptions> | undefined; }); ... 10 more ...; openOnClear: boolean; }> & Omit<...>'`

vue-tsc mentions two error :
```bash
src/components/HelloWorld.vue:14:19 - error TS2322: Type 'Monster | undefined' is not assignable to type 'string | number | unknown[] | undefined'.
  Type 'Monster' is not assignable to type 'string | number | unknown[] | undefined'.

14         <v-select v-model="selectedMonster" :items="items" />
                     ~~~~~~~


src/components/HelloWorld.vue:14:46 - error TS2322: Type '{ title: string; value: { name: string; shouts: string; lethal: boolean; }; }[]' is not assignable to type 'SelectItem[]'.
  Type '{ title: string; value: { name: string; shouts: string; lethal: boolean; }; }' is not assignable to type 'SelectItem'.

14         <v-select v-model="selectedMonster" :items="items" />
```

### Reproduction Link
<a href="https://github.com/Esurnir/vuetify-repro/" target="_blank">https://github.com/Esurnir/vuetify-repro/</a>

### Other comments
Other than the type error, everything work as expected and builds happens properly.
I think this comes from 
```typescript
export type SelectItem = string | (string | number)[] | ((item: Record<string, any>, fallback?: any) => any) | (LinkProps & {
  text: string
})
```
It states it expect `((item: Record<string, any>, fallback?: any) => any)` while the actual type I am passing is Record<string, any> or perhaps more specifically something like :
```typescript
interface SelectItemObject {
   title: string,
   value: unknown
}
```

**Comment by Esurnir** [comment]
Actually I'm wrong, it doesn't work completely since it pass the value instead of title to the v-text-field bellow... I guess there's some underlying issue instead of just the type error.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
