### ISSUE TITLE
[Bug Report][2.6.4] Button icon on System Bars is not center of button

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#14975]
### Environment
**Vuetify Version:** 2.6.4
**Last working version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
I have to set icon class="ml-1" to make it center

### Expected Behavior
The icon must to center of button

### Actual Behavior
The icon is on the left on button
![image](https://user-images.githubusercontent.com/136077/164361114-416f2914-be0a-4a4a-8c12-4d7423af5b43.png)

### Reproduction Link
<a href="https://codepen.io/canhkieu/pen/WNdmRaY" target="_blank">https://codepen.io/canhkieu/pen/WNdmRaY</a>

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqVUttuwjAM/ZUoz7RhbNMk1CH2HZSHtPUgo02iOC0gxL/PSRmDIg32UrX28bnYXRz4h7Vp1wKf8sxDY2vpYZZrxrIuqeXetJ6h39fwnvM1qNXaT9nr2O5yHkERhnukyaSQjm2Vrsz21IpNVRrNwoMImkolDSDKFeSclbVEDFVIJkSXiR5Mw+dxtFLPnsas1Q5kxU6zmInYuACSCStLcJHl9HrVLvy1C6VbJA+ddEpqT1UPO39yQdg/h8s1lJvC7JKilnqT0IpqpUOiIdtvRDxHvEteG/wfV+QJsc9n6O9Hpf6A9JmJ8235iJPdDaZfaDRd/RDAOS+R9jFli56Pju29xakQZaUJWUGtOpdq8ELbRtD/4tXnfv6cTtKJqBT6nxJJFphGssC0zPWRBFVjjfNJI+1AtW9E5VgJNWIK33cszAkmXKu9ov+nMk308vLWm7mop4C0E2e2CI5Ycj660AmOH9C6F5ckbqgF6XXgEge6Agfu0UiDsatYg95NtCB/DBs/jng/R7uPpvnyG+s9TUc=

@johnleider if happy, can you please also close related PR https://github.com/vuetifyjs/vuetify/pull/15918

**Comment by johnleider** [comment]
Since this has an existing PR that is very simple we can leave this open.
