### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-menu doesn't close on content click + `close-on-content-click` prop isn't helping

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#14978]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.88
**OS:** Linux x86_64

### Steps to reproduce
Click on any list item of menu component

### Expected Behavior
It should close the menu as we click on list item and provided the `close-on-content-click` prop.

### Actual Behavior
It's not closing the menu component

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/PoELEXv?editors=101" target="_blank">https://codepen.io/jd-0001/pen/PoELEXv?editors=101</a>

**Comment by Vincebe** [comment]
Looks like `closeOnContentClick` is still in TODO 

[https://github.com/vuetifyjs/vuetify/blob/cdf5e412889edf10dd850e7418290370629c6571/packages/vuetify/src/components/VMenu/VMenu.tsx#L32](https://github.com/vuetifyjs/vuetify/blob/cdf5e412889edf10dd850e7418290370629c6571/packages/vuetify/src/components/VMenu/VMenu.tsx#L32)
