### ISSUE TITLE
[Feature Request] [3.0.0-beta.1]  menu position can be controlled

### ISSUE THREAD

**Issue by mjlovesz** [vuetifyjs/vuetify#14976]
### Problem to solve
menu position can be controlled. contextmenu 

### Proposed solution
no

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. We are not currently accepting additions to v3.0.0.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
