### ISSUE TITLE
Adding property scrollable in dialog actually sets the overflow to hidden

### ISSUE THREAD

**Issue by Rud156** [vuetifyjs/vuetify#1497]
### Steps to reproduce
Create a `v-dialog` with the `scrollable` property set to `true` and insert text inside a `v-card-text` such that it overflows the body.

### Versions
Version: `0.14.11`

### What is expected ?
Setting the `scrollable` property to `true` should actually set the `overflow-y` to `auto`

### What is actually happening ?
Setting the `scrollable` property to `true` is actually setting the `overflow` property to `hidden` which prevents scrolling when the text overflows the dialog

### Reproduction Link
[https://codepen.io/anon/pen/JyaMdp?editors=1010](https://codepen.io/anon/pen/JyaMdp?editors=1010)

**Comment by johnleider** [comment]
Going to have to rethink how we currently do this.

**Comment by Rud156** [comment]
I don't completely understand the complexity of an application this size but shouldn't just modifying the `.styl` file for the specific component work if it does not conflict with anything else???

**Comment by johnleider** [comment]
Of course, but the problem is not with the style, the problem is with the implementation of the overflow functionality. It's essentially a hack that depends upon manually setting height on the ```v-card-text``` to create the overflow effect.

**Comment by johnleider** [comment]
So after looking into this, while it could be better, it does in fact work. You need to specify a maximum height on the v-card-text element, as per the example from the documentation.

https://codepen.io/johnjleider/pen/oGvpMa?editors=1010
