### ISSUE TITLE
[Bug Report][2.6.4][VCarousel] Reflow issue

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#14981]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Create a carousel with height auto, scroll down the page, trigger a reflow, the carousel has no active slide for some obscure reason (watching in the devtool the internalValue is different than the vModel when that happens but none of the CarouselItems are computed as active) and so is not displayed on the page until scrolled back in, this is much more problematic on a real site https://moljatek.hu/ (go to the second slide, scroll down the page and watch the slide disappear because the route hash change triggers a vue update, but won't appear back in even if scrolled in)

### Expected Behavior
The current slide to stay visible

### Actual Behavior
The current slide disappears

### Notes
The bug doesn't happen on the first and last slides but only in the middle slides, so I'm not sure my reproduction is accurate because the repro happens on all slides and is fixed when scrolled back in, so the behavior is slightly different

### Reproduction Link
<a href="https://codepen.io/Tofandel/pen/abExBNq?editors=1010" target="_blank">https://codepen.io/Tofandel/pen/abExBNq?editors=1010</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
