### ISSUE TITLE
[Documentation][3.0.0-beta.1] v-autocomplete search-input prop

### ISSUE THREAD

**Issue by furkan-guvenc** [vuetifyjs/vuetify#14982]
### Environment

**Browsers:** Chrome 100.0.4896.127
**OS:** Mac OSX

### Steps to reproduce
According to the [documentation](https://next.vuetifyjs.com/en/components/autocompletes/#asynchronous-items), we need to use the `search-input` prop. But this is wrong, because in [code](https://github.com/vuetifyjs/vuetify/blob/cca94faf157fecc735eb05f2d125b38bb11b258d/packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx#L62) `search` is used.

### Expected Behavior
Example need to work with `search-input`

### Actual Behavior
It doesn't work, need to use `search`

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/autocompletes/#asynchronous-items" target="_blank">https://next.vuetifyjs.com/en/components/autocompletes/#asynchronous-items</a>

**Comment by johnleider** [comment]
The documentation is still in process and `v-autocomplete` has not been fully updated.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
