### ISSUE TITLE
Disabled v-select focusable

### ISSUE THREAD

**Issue by kevmo314** [vuetifyjs/vuetify#1498]
### Steps to reproduce
1. Go to https://dev.vuetifyjs.com/components/selects
2. Click the disabled select
3. Push tab

### Versions
0.15 beta 3

### What is expected ?
The select input should not be focusable

### What is actually happening ?
![](http://i.imgur.com/K9bZMQe.png)

The select input is focused

### Reproduction Link
https://dev.vuetifyjs.com/components/selects

See pull request 1427 for fix.

**Comment by johnleider** [comment]
This was already fixed with df85e4816717bf71da315fd820fa0b89925665c7
