### ISSUE TITLE
Progress & Activity are not always applied the right colot

### ISSUE THREAD

**Issue by spaquet** [vuetifyjs/vuetify#1499]
```
<div class="text-xs-center mt-4" v-if="this.$store.getters['related/getSearchState']">
            <div>
              Searching for related questions / articles
            </div>
            <div class="">
              <v-progress-circular indeterminate v-bind:size="70" class="purple--text"></v-progress-circular>
            </div>
          </div>
```
However, the progress circular is displayed in black...
![image](https://user-images.githubusercontent.com/176050/29755594-5b4135ec-8b4f-11e7-8aef-fd5b0c8787d6.png)

Vuetify 0.14.11

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by spaquet** [comment]
Well, code to reproduce is above. Our project is private and cannot share more than what you have.

**Comment by johnleider** [comment]
I'm not asking you to share your project, I'm asking you to provide a codepen that reproduces the issue. It's important for you to isolate the problem outside of your environment.
