### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VCard's disabled prop also disables contents

### ISSUE THREAD

**Issue by SuperCuber** [vuetifyjs/vuetify#14998]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Firefox 99.0
**OS:** Windows 10

### Steps to reproduce
1. Checkbox off, click outside of button (get "outer") click inside (get "inner")
2. Checkbox on, click outside of button (get nothing) click inside (get nothing)

### Expected Behavior
pointer events should reach the button (ripple, click)

### Actual Behavior
pointer events don't reach the button

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/JjMqEMQ" target="_blank">https://codepen.io/SuperCuber2/pen/JjMqEMQ</a>

### Other comments
I want a way to disable the card without disabling the contents. Someone in the discord suggested two workarounds: 

https://codepen.io/TylerOliver18/pen/MWrdvYx has the problem that it requires to copy paste the card's contents (or use an extra component for them) 

https://codepen.io/TylerOliver18/pen/QWaRMjV has the problem of still having the ripple when disabled.

I also tried introducing the style
```css
.v-card--disabled > * {
  pointer-events: all;
}
```
With this ripple still was hidden but clicking was re-enabled since the contents' event was bubbled up.

I think an ideal solution would be that the disabled prop should disable the @click and ripple effect directly rather than hacking around it using pointer events.

I also haven't checked other components with disabled prop for related behavior - maybe this applies to them too.

**Comment by johnleider** [comment]
This is working as intended.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
