### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-hover not work over v-icon.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#14990]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Just put the v-icon inside the v-hover component.

### Expected Behavior
It should detect the hover and `isHovering` variable value should be `true`.

### Actual Behavior
It does not detect the hover-on icon.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/gOoJdxo?editors=1010" target="_blank">https://codepen.io/Alokdev/pen/gOoJdxo?editors=1010</a>

**Comment by KaelWD** [comment]
You need `v-bind="props"` to attach the event listener.
