### ISSUE TITLE
[Bug Report][3.0.0-beta.1] V-select cannot work with @change

### ISSUE THREAD

**Issue by fan9704** [vuetifyjs/vuetify#14992]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 2.6.4
**Vue Version:** 3.2.25
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Just can not work :(

### Expected Behavior
Can work @change="functionName"
then function show up

### Actual Behavior
No any response

### Reproduction Link
<a href="https://github.com/fan9704/Garbage_Classifier_Frontend" target="_blank">https://github.com/fan9704/Garbage_Classifier_Frontend</a>

**Comment by NathanAP** [comment]
v-selects in general seems really bugged in beta version. I cannot create selects with object items and as you can see [here](https://next.vuetifyjs.com/en/components/selects/#custom-text-and-value) even the docs have the same problems right now.

**Comment by KaelWD** [comment]
There is no change event, in vue 3 all default model events are now `update:modelValue`
