### ISSUE TITLE
v-form's v-model property not validate correct state for v-select or v-checkbox component

### ISSUE THREAD

**Issue by alterhu2020** [vuetifyjs/vuetify#1500]
### Steps to reproduce
1. Visit reproduce site: https://codepen.io/alterhu2020/pen/prxvoj
2. Input valid name, valid email address ,not select the dropdown list and not check the "do you agree" checkbox
3. Check the bottom validate returned result is true or false

By the way, the `v-select` component is broken after upgrade to  vuetify  v0.15.0-beta.3 .
### Versions

1. vuetify  v0.15.0-beta.3
### What is expected ?

1.  Only all these form components input is valid ,the `v-form` result from `v-model` should return true ,otherwise it will always return as false.
### What is actually happening ?

1. When the input components are valid ,then the validate result will return true, even though there's still some invalid component data.
### Reproduction Link

https://codepen.io/alterhu2020/pen/prxvoj

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/e28d9868e48fe32da679351985734b5f8bc43b9a
