### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Badge location props possible options not works.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15000]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
the two possible values of location prop `bottom-left and `top-left` do not work.

### Expected Behavior
It should align the badge to the `top-left` or `bottom-left`.

### Actual Behavior
It aligns the badge `to-right` and `bottom-right`  only

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/qBpzrjb?editors=101" target="_blank">https://codepen.io/Alokdev/pen/qBpzrjb?editors=101</a>

**Comment by alokVishu** [comment]
`top-start` and `bottom-start` values work with this but the documentation does not mention these values.

**Comment by KaelWD** [comment]
All `left` and `right` have been changed to `start` and `end`.
