### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Babel config cause components importing css file instead of sass

### ISSUE THREAD

**Issue by RValette** [vuetifyjs/vuetify#15001]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.31
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
- Install vuetify@v3.0.0-beta.1 with npm
- Go to the node_modules/vuetify/lib/components folder
- Check any component file ( for example VBtn/VBtn.mjs)

### Expected Behavior
The file should import the sass file

### Actual Behavior
Babel config automatically transform the import  statement to import css file instead.

### Reproduction Link
<a href="https://codepen.io/RomainValette12/pen/jOYjmvW" target="_blank">https://codepen.io/RomainValette12/pen/jOYjmvW</a>

### Other comments
In the babel.config.js the plugin "/build/babel-plugin-replace-import-extension" is used. This is the reason why the import statement in each component is modified to import the css file.

**Comment by KaelWD** [comment]
This is intentional

**Comment by RValette** [comment]
> This is intentional

So how is it possible to override sass variables define for each component ?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#customising-variables

**Comment by RValette** [comment]
Thanks for your realy quick answer ! Appreciate :) 
By any chance, is there any webpack alternative ?
