### ISSUE TITLE
[Bug Report][3.0.1] Chip's closable prop not work with ComboBox  Component  

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15003]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Just put a `closable` prop to the chip inside `Combobox`.

### Expected Behavior
A closable icon should appear.

### Actual Behavior
Nothing is happening.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/ExoBbpO?editors=101" target="_blank">https://codepen.io/Alokdev/pen/ExoBbpO?editors=101</a>

**Comment by johnleider** [comment]
Workaround example: <https://codepen.io/johnjleider/pen/WNzZQvY?editors=1011>

**Comment by johnleider** [comment]
Example in the wild: https://play.vuetifyjs.com/#eNqVVF1v0zAU/SuXgJRWSpyNTUKqumkIHoAHQELAwzppbnrXmdmxZTvZpir/nes4XZMMkHhpc7/OOfcjudwlb41hTY3JIll6VEZyj+erCmDZ5NyY7pGMjWiglNy5s1WieH4Khn5WSR+O2bXXpSYE9Lh3AzS50huUVOZQYulXySG2EMQYELv/YUTydVfzEWqHwMGV2uAGnNQjAFVLL4jw4CklcsvXI9etMG5vPgkmyft24WVIIbYdBCEZiGqDDxkYq42DdtBl32lIH7qokzt8JIDrV7uAwLzwEtucrIDUXg81R5XajUXGUa0pn2A64mnNhdI0i42+r5ix2GDlmfN6pGOkM+6k4Z7bsZvotdS24xGK28cpE4CjIj91NrnHB99vK7bInBQlzo4yOJ4zr78bg/YddzibTzEL0jb27OK0IxC07WjGRRzycFvF6Dr3WcOjG1AsaUTnxPDp25fPNCYrqq24eZzFE8ygqqXM4PWcaJdFSO2vvKAzj8cfoLvrH/GS6UorjAeHvo7yhDLaetiBxRto4cZqBSm9UGlUU+rKeVBuC2chY5Z+QCk1/NRWbl6k80NK1NZnXaY/avQkOc0g/Wr11nKlqIn0alDRvTVUcBnVj/Ky3vcendhWTyahDp8jQ7CvQqexN+oqyZLYVq64Yb+crujzsAt5tP0uQOe5gM4TfNRusFfJrffGLYqirszdltFiiguKFbauvFCYb7S6OGEn7Cjn0txydkoDd34YZuhUvrb63qEl4lXSq+04gty/8fRhgj9mbyJs7wqQz6AKwm/Q5hbpDbVo/yl/kvunFiYpz9oI1HTiLU1WiurOTYZaum6g/Sb/sz9aOOsA+kW2SZslI43E2tUlV78BGZPTFg==

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
