### ISSUE TITLE
[Feature Request] Vue3 - Create bottom navigation component

### ISSUE THREAD

**Issue by sunlee334** [vuetifyjs/vuetify#15005]
### Problem to solve
The components that were previously provided are not shown in next.vuetify docs.

### Proposed solution
Create bottom navigation to be used on the mobile screen

**Comment by ElijahKotyluk** [comment]
Vuetify 3 Documentation is something that is a work in progress, we are still in beta.

`VBottomNavigation` is converted for Vue 3 already. For now you will have to rely on the source code to view what functionality is currently provided for the component.
Source: [VBottomNavigation.tsx](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.tsx)

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by kieuminhcanh** [comment]
fixed prop is not work.
