### ISSUE TITLE
[Feature Request] Can we get test ids?

### ISSUE THREAD

**Issue by chrissmartin** [vuetifyjs/vuetify#15013]
### Problem to solve
Working on e2e tests with cypress for vuetify is a pain. Most of the selectors are multiple level specifiers

### Proposed solution
Need test ids (Ref: https://docs.cypress.io/guides/references/best-practices)
Eg: v-select dropdown, currently fetching by role property. Can we get ids for each dropdown item.
Any better way to inject custom ids into sections of the component is also good.

**Comment by KaelWD** [comment]
Duplicate of #7295
