### ISSUE TITLE
[Feature Request] [VDataTable] Collapsed Groups on Render

### ISSUE THREAD

**Issue by NicoAiko** [vuetifyjs/vuetify#15017]
### Problem to solve
Let's say, we have a data table that has a groupBy that doesn't change.
I want to be able to also set it up so all (or selected) groups are collapsed by default instead of expanded.

### Proposed solution
Just like the expanded property on VDataTable there could be properties like `collapse-all-groups` and a `collapsed-groups` property (which takes a string or an array of something with the actual information on which groups to collapse).

**Comment by miketierce** [comment]
I wanted to achieve to the same result just now and it felt like it should have been 

`:show-expanded: false //defaults to true would keep the same visual we have now by default`

but the presence of fault would collapse the table groups

**Comment by Flightliner380** [comment]
I want an option toggle to expand/collapse all groups or all visible groups by an API-Function.

**Comment by Flightliner380** [comment]
You closed the Issue as completed, I found in the latest documentation nothing about how to collapsed all groups .
Please can give me an example.
