### ISSUE TITLE
[Bug Report][2.6.4] Navigation Drawer expand on hover: v-main padding not adjusted on close position

### ISSUE THREAD

**Issue by florealcab** [vuetifyjs/vuetify#15010]
### Environment
**Vuetify Version:** 2.6.4
**Last working version:** 2.6.1
**Vue Version:** 2.6.12
**Browsers:** Chrome 100.0.4896.127
**OS:** Linux x86_64

### Steps to reproduce
Just see

### Expected Behavior
Content shout fit the close position of the navigation bar, like it was the case with 2.6.1 version and before. When the navigation is opened (on hover), it's placed over content

### Actual Behavior
There is a padding of the size of the naviagation bar at open position

### Reproduction Link
<a href="https://codepen.io/florealcab/pen/gOoVMda" target="_blank">https://codepen.io/florealcab/pen/gOoVMda</a>

### Other comments
Since the 2.6.2 version, the bug occurred

**Comment by Thomaswaldick** [comment]
Experiencing the same issue, though it fixes itself once I hover over the nav-drawer

**Comment by florealcab** [comment]
Bug still present in 2.6.9 version. Any plan to fix it?

**Comment by lmbak** [comment]
Also experiencing this in 2.6.10.
