### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VMenu+VueRouter performance issue

### ISSUE THREAD

**Issue by SuperCuber** [vuetifyjs/vuetify#15022]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Firefox 99.0
**OS:** Windows 10

### Steps to reproduce
1. Navigate to component 2
1. Navigate to component 1
1. Observe delay between click and navigation
1. Navigate to component 2
1. Toggle checkbox off (the checkbox icon doesn't appear because of the codepen)
1. Observe no delay
1. Navigate to component 1
1. Observe no delay

### Expected Behavior
No delay when navigating away from v-menu's

### Actual Behavior
Delay

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/eYVYzaE" target="_blank">https://codepen.io/SuperCuber2/pen/eYVYzaE</a>

### Other comments
Note how toggling the checkbox causes the v-menu's to be mounted and unmounted but there is no delay - not sure why this happens.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/944878bd71ed309225c7a48997c38a0caef75cdc/packages/vuetify/src/composables/router.tsx#L83-L85

**Comment by 94726** [comment]
> Each menu adds a beforeEach hook with a timeout, so 40 menus means a 160ms navigation delay.

Why is the timeout needed?

**Comment by SuperCuber** [comment]
> `setTimeout(() => popped ? cb(next) : next())`

Shouldn't this kind of thing be done with vue's builtin `nextTick()`? Not sure if that would fix the issue here (or if that would even work as a replacement :P )

**Comment by KaelWD** [comment]
> Why is the timeout needed?

beforeEach is called before our popstate handler, we need to wait to check if there was a popstate

> nextTick()?

Nope, that's to wait for vue to update to DOM. It'd also have the same problem, 40 consecutive nextTick isn't good either
