### ISSUE TITLE
[Documentation] Input previews dont appear

### ISSUE THREAD

**Issue by AntonyOnScript** [vuetifyjs/vuetify#15028]
### Environment

**Browsers:** Chrome 100.0.4896.127
**OS:** Linux x86_64

### Steps to reproduce
open the link and  look at the inputs

### Expected Behavior
show inputs preview

### Actual Behavior
shows a error message instead input preview

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/inputs/#error-count" target="_blank">https://vuetifyjs.com/en/components/inputs/#error-count</a>

**Comment by johnleider** [comment]
Whatever it was I'm not seeing an issue now.
