### ISSUE TITLE
Tabs not showing tab bars

### ISSUE THREAD

**Issue by vinchi777** [vuetifyjs/vuetify#1503]
### Steps to reproduce
Simple copy/use code in tab documentation. https://vuetifyjs.com/components/tabs
### Versions

0.15 (latest)
### What is expected ?

Tab bars to render and show.
### What is actually happening ?

Tab bars are not showing also not rendered in the DOM, only .tabs__content
### Reproduction Link

https://codepen.io/eclipseAce/pen/wezKNz

**Comment by jacekkarczmarczyk** [comment]
You need to remove `slot="activators"` from `<v-tabs-bar>` (specs has changed in v0.15)

**Comment by nekosaur** [comment]
You also need to wrap your `v-tabs-content` elements in `v-tabs-items`

**Comment by vinchi777** [comment]
thanks guys!
