### ISSUE TITLE
[Bug Report][3.0.0-beta.1] `v-list` components `Three line` demo has ellipsis from first subtitle line.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15036]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.41
**OS:** Windows 10

### Steps to reproduce
Try to add multiple lines in subtitles. 

### Expected Behavior
It should show two lines of subtitles.

### Actual Behavior
It only shows a one-line subtitle and then an ellipsis.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/qBxdbmY?editors=101" target="_blank">https://codepen.io/Alokdev/pen/qBxdbmY?editors=101</a>

**Comment by ElijahKotyluk** [comment]
The examples for VList need to be updated, you can use `<v-list :lines="three" />`.

**Comment by ElijahKotyluk** [comment]
[cbda96c](https://github.com/vuetifyjs/vuetify/commit/cbda96cbf2192be42821d6e13a9d0f739d3b995b) quick docs update that addresses this.
