### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Cannot override Radio component's color prop.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15037]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.41
**OS:** Windows 10

### Steps to reproduce
Try to override the default color prop of the `VRadio` component.

```
export default createVuetify({
   defaults: {
    VRadio: {
      // set v-radio default color to primary
      color: 'primary',
    },
  },
})
```

### Expected Behavior
It should override the default value of prop. 

### Actual Behavior
Not override the prop value.

### Reproduction Link
<a href="https://github.com/alokVishu/vuetify-radio-issue" target="_blank">https://github.com/alokVishu/vuetify-radio-issue</a>

**Comment by KaelWD** [comment]
@johnleider that fixes radios, we're probably doing something similar in other places though. `filter<component>Props` might be best in non-root-component scenarios - we're already doing it with most inputs, and it makes API documentation simpler.

**Comment by johnleider** [comment]
This didn't actually fix the as stated. The updated syntax would be:

```js
VRadioGroup: { color: 'primary' }
```

because VRadioGroup takes over control of the providedDefaults for `v-radio`.

We are working on some ways that we can improve this, but plan to document it fully.
