### ISSUE TITLE
[Bug Report][2.6.5] NVDA is not announcing user selection when users made a selection from v-combobox dropdow

### ISSUE THREAD

**Issue by gavinwang-au** [vuetifyjs/vuetify#15034]
### Environment
**Vuetify Version:** 2.6.5
**Vue Version:** 2.6.1
**Browsers:** Chrome 100.0.4896.127
**OS:** Mac OS 10.15.7

### Steps to reproduce
When a screen reader (NVDA) user has made a selection from the ‘Select an item from the list' in Combobox dropdown, the incorrect element role is announced. Example: “aaaa,  select an item from list, edit, text” 

### Expected Behavior
expected the NVDA to announce the user's selection

### Actual Behavior
incorrect element role is announced

### Reproduction Link
<a href="https://codepen.io/gavinwang-au/pen/WNMvQwa?editors=1111" target="_blank">https://codepen.io/gavinwang-au/pen/WNMvQwa?editors=1111</a>

**Comment by KaelWD** [comment]
Duplicate of #15033
