### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VDialog inside VDialog cause maximum call stack error on closing

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15041]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
1. Open https://codepen.io/andrewspy/pen/WNMvKwK?editors=1010
2. Click "CLOSE" button on dialog 2. (Clicking outside of dialog 2 to close works as expected)
3. Check console log to see the error.

### Expected Behavior
There shouldn't be any maximum call stack error

### Actual Behavior
Maximum call stack error.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/WNMvKwK?editors=1010" target="_blank">https://codepen.io/andrewspy/pen/WNMvKwK?editors=1010</a>

### Other comments
Error from console:
```
Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDocument.onFocusin (VDialog.tsx:82:23)
```
On another note, the position of dialog 2 seems offset relative to dialog 1.

**Comment by SuperCuber** [comment]
I don't see an error and everything works as expected (win10, firefox)

**Comment by andrewspy** [comment]
@SuperCuber It works in firefox, seems like chrome related.

**Comment by KaelWD** [comment]
Playground:
```html
<template>
  <v-app>
    <v-container>
      <!-- dialog 1 -->
      <v-dialog v-model="model.dialog1" persistent>
        <v-card title="Dialog 1" min-width="300px">
          <!-- dialog 2-->
          <v-dialog v-model="model.dialog2">
            <v-card title="Dialog 2" min-width="300px">
              <v-card-actions>
                <v-spacer />
                <v-btn variant="outlined" @click="model.dialog2 = false">
                  Close
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>

          <v-card-actions>
            <v-spacer />
            <v-btn variant="outlined" @click="model.dialog2 = true">Open</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </v-container>
  </v-app>
</template>

<script setup>
  import { computed, ref, watch } from 'vue'

  const model = ref({
    dialog1: true,
    dialog2: true,
  })
</script>
```
