### ISSUE TITLE
[Feature Request] Add variable to border-color for v-text-field in not focused state

### ISSUE THREAD

**Issue by OXXXRA** [vuetifyjs/vuetify#15040]
### Problem to solve
It's remove useless override for class if we need to change border-color in not focused state.

### Proposed solution
Add new custom varriable in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTextField/VTextField.sass#L6

**Comment by KaelWD** [comment]
That's exactly what the line you linked is.
