### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VListItem unable to set :active="false" in current route

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15042]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
1. Open https://codepen.io/andrewspy/pen/XWZbBxX?editors=1010
2. VListItem always active despite setting `:active="false"` in current route

### Expected Behavior
Inactive VListItem should be inactive at current route

### Actual Behavior
Inactive VListItem always active at current route

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/XWZbBxX?editors=1010" target="_blank">https://codepen.io/andrewspy/pen/XWZbBxX?editors=1010</a>

**Comment by KaelWD** [comment]
`active` is a boolean that defaults to false. v2 had a separate `inactive` prop which did this but it seems to be missing

**Comment by KaelWD** [comment]
@vuetifyjs/core-team v2's `inactive` also removed the automatic `link` with `to`/`href`, should we keep doing that or just make it a link without the active styling? Seems kinda pointless in v2, you could just remove `to` for the same behaviour.
