### ISSUE TITLE
[Feature Request] The button component has no loading state

### ISSUE THREAD

**Issue by Azema4ka** [vuetifyjs/vuetify#15056]
### Problem to solve
Often the user interface needs to display the loading state of the button, which is not currently the case

### Proposed solution
Use the same API that was provided in [version 2.6.5](https://vuetifyjs.com/en/components/buttons/#loaders)

**Comment by AntoninBeaufort** [comment]
I've opened a PR using the loader composable that add loading prop and restore doc like in V2.6.7: https://github.com/vuetifyjs/vuetify/pull/15278
