### ISSUE TITLE
[Feature Request] Hope the new table custom mdi-menu-down icon support

### ISSUE THREAD

**Issue by lfpak** [vuetifyjs/vuetify#15062]
<img width="999" alt="截屏2022-05-07 10 11 52" src="https://user-images.githubusercontent.com/28940798/167233866-10c9cb51-ee40-4b9e-8249-12701117ab43.png">
### Problem to solve
Now I have a problem, when I use the table component, I can use the `v-data-table-header API` to change the icon of the previous page and the next page, but I don't see that I can change the icon of the selected pagination

### Proposed solution
I hope the official can add this function.

**Comment by KaelWD** [comment]
It uses `dropdown` from the global config: https://vuetifyjs.com/en/features/icon-fonts/
