### ISSUE TITLE
[Feature Request] [RFC] Vuetify 3 codestyle etc.

### ISSUE THREAD

**Issue by zorn-v** [vuetifyjs/vuetify#15067]
### Problem to solve
Currently, only little group of "dedicated specialists" can contribute to vuetify codebase. 
Not because of "somebody does not allowed", but "why I should investigate AND WRITE in pure js/ts/jsx/tsx" *sx is react ugly (IMO) thing meanwhile ???
Why does not use pretty/great/beautifully vue SFC (single file components) ?

### Proposed solution
As first, many (I think, I'll be first) people will become vuetify 3 to reality with many missing today features from v2.
AFAIR SFC has good support of typescript now.

**Comment by KaelWD** [comment]
Not worth discussing this, it isn't going to change.

**Comment by zorn-v** [comment]
Why ?
Vuetify 3 are just die agnostic

**Comment by zorn-v** [comment]
WHY ?
In past I can understand things like "type checking" etc. Why now does not to do right ?
