### ISSUE TITLE
[Feature Request] Being able to fill only the middle boxes in v-otp-input

### ISSUE THREAD

**Issue by suleymangezsat** [vuetifyjs/vuetify#15063]
### Problem to solve
https://codepen.io/suleymangezsat/pen/RwQraWd
What I was trying to do in above link was to write a, b and c in the second, fourth and fifth boxes, respectively. But since the component takes only string as input, it writes "abc" and these letters are placed in order, starting from the leftmost box.

### Proposed solution
VOtpInput component should be customized to receive input in the form of [idx:number]:string. In this way, we will be able to add the character we want to the boxes we want.
{
   2: "a",
   4: "b",
   5: "c"
}
In this example, the inputs in the 2nd, 4th, and 5th indexes will be filled, and the 0th, 1st, and 3rd indexes will be empty.

**Comment by KaelWD** [comment]
why?

**Comment by suleymangezsat** [comment]
Consider a scenario like this: you are developing a word finder app where you ask the user to enter letters in certain boxes.

For example, if the user enters "a" in the second box and "y" in the fifth box, you are returning the word "happy". 
Therefore, letters must be bindable to v-otp-input for certain positions.
