### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Form validation not reactive in new vuetify 3 project 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [vuetifyjs/vuetify#15070]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Safari 15.4
**OS:** Mac OS 10.15.7

### Steps to reproduce
1/ vue create my-beta-app
❯ Default (Vue 3 Preview) ([Vue 3] babel, eslint)
2/ vue add vuetify
❯ Vuetify 3 Preview (Vuetify 3)
3/ Replace "src/components/HelloWorld.vue" by first form example in [documentation]( https://next.vuetifyjs.com/en/components/forms/#validation-with-submit-26-clear)

### Expected Behavior
valid data should be reactive

### Actual Behavior
valid var isn't updated to false or true, depending on the errors like in this [example](https://next.vuetifyjs.com/en/components/forms/#validation-with-submit-26-clear) 

### Reproduction Link
<a href="https://github.com/PierreBrisorgueil/Vue3FormExample" target="_blank">https://github.com/PierreBrisorgueil/Vue3FormExample</a>

### Other comments
Linked to 
* PR: https://github.com/vuetifyjs/vuetify/pull/14945
* Issue: https://github.com/vuetifyjs/vuetify/issues/14931
* Issue: https://github.com/vuetifyjs/vuetify/issues/14901

**Comment by nekosaur** [comment]
beta.1 was released before https://github.com/vuetifyjs/vuetify/pull/14945. use nightly if you need the fix right now
