### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VImg transition error on `:src` changed

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15072]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.54
**OS:** Windows 10

### Steps to reproduce
- Open https://codepen.io/andrewspy/pen/NWyxMPO?editors=1010
- Change `:src` by clicking "Dark" and "Light" button.
- First VImg with transition does not display image accordingly.

### Expected Behavior
VImg should display image accordingly after transition.

### Actual Behavior
VImg does not display image accordingly after transition.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/NWyxMPO?editors=1010" target="_blank">https://codepen.io/andrewspy/pen/NWyxMPO?editors=1010</a>

### Other comments
Setting `:transition="false"` will work as expected.

**Comment by volvachev** [comment]
Hello, I think the problem occurred in vue v3 [issue](https://github.com/vuejs/core/issues/4462) as a possible solution I can and add a key for img, but it looks like a workaround(I tried and it fixes the problem ([branch is here](https://github.com/volvachev/vuetify/tree/fix/15072-img-transition))).

**Comment by andrewspy** [comment]
I have tested and confirmed that the problem has been resolved with the latest release of Vue v3.2.34.
