### ISSUE TITLE
[Bug Report][3.0.0-beta.0]   v-text-field type number is not behaving the same in firefox and chromium

### ISSUE THREAD

**Issue by yanngit** [vuetifyjs/vuetify#15086]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.33
**Browsers:** Firefox 99.0
**OS:** Ubuntu undefined

### Steps to reproduce
Open the codepen with firefox, the field is short like expected. Open it with chromium, the field is longer than expected ... 

### Expected Behavior
Same render in Firefox and chromium

### Actual Behavior
Different render in firefox and chromium

### Reproduction Link
<a href="https://codepen.io/yannblanc/pen/YzeGGWw" target="_blank">https://codepen.io/yannblanc/pen/YzeGGWw</a>

**Comment by SuperCuber** [comment]
On windows10 here, firefox and chrome both look long to me.
