### ISSUE TITLE
[Feature Request] Vuetify with unocss 

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#15083]
### Problem to solve
Using unocss  classes with vuetify components not work  it cannot override the original component classes 

### Proposed solution
Add component-class prop which override original component classes.

**Comment by KaelWD** [comment]
Nope. Use https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#remove-all-style-imports
