### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Checkbox size not constant, label cannot removed and height is bigger

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15090]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.64
**OS:** Windows 10

### Steps to reproduce
When you wrap your checkbox to different HTML elements and these elements have different font-size then you see checkbox sizes also change.

### Expected Behavior
- The checkbox has a constant size instead of changing on its parent wrapper. 
- Height of the checkbox should be according to text (minimum as required)
- If we don't use a label it should not render its div or should not take space

### Actual Behavior
- Checkbox changes its size based on its parent wrapper's font size.
- If you remove the label from the checkbox but it still takes space.
- The checkbox takes unnecessary height compared to Vuetify 2 checkbox.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/PoQqNJW" target="_blank">https://codepen.io/Alokdev/pen/PoQqNJW</a>

**Comment by jd-solanki** [comment]
@KaelWD  Still the size of the input is larger than expected. How can we reduce it.
![image](https://user-images.githubusercontent.com/47495003/170186213-8b71be9f-73c3-4e1d-bb5b-29efa6e6c843.png)

I am also facing a similar issue with the switch. Will this commit fix that as well?

**Comment by flyercarol** [comment]
> [@KaelWD](https://github.com/KaelWD) Still the size of the input is larger than expected. How can we reduce it. ![image](https://user-images.githubusercontent.com/47495003/170186213-8b71be9f-73c3-4e1d-bb5b-29efa6e6c843.png)
> 
> I am also facing a similar issue with the switch. Will this commit fix that as well?

Try adding `hide_details=True` in the v-checkbox definition, this trimmed unwanted heights for me.

For instance:
`<v-checkbox class="ma-1 pa-1" hide-details="true">

**Comment by J-Sek** [comment]
[Example workaround](https://play.vuetifyjs.com/#eNrNU91K9DAQfZVD+cAfvmxRBKFbBfERvHQF0+zsGkyTkE7L6rLvbtIf6+q9eNHQmTlzZnp68rjPmqDyO+8XXUtZkZVMtTeS6XZlgbIT0vv+NQYeDb8ZulllG2dZNPqdClxc+t0SHQXWShohjd7aAoosU1hlYyvw4FC36gVMOz4Kyiog/zuwKRe/XL2Qeq3cTlRspzSgrdGW5rgTtVuTiaJM+FU2Vwsjq774fD9WC/zbT8gFuwcO2m5Pzw7Pc9u8mbRraIaKcmvbUnO89/fqL8NHV+SDP8p88kqZf/FQDBsVtGc0xO0A1bV3gbFHoA0O2ARX4yTa7yTBkQY0ccyoEW4S7JRDS2eJe2AbmZMde8rF8e9Kca889sOWXw1L9RL5OS4C1ajesKaNbA3jPB+gyhkXijh0vUyJQzr8jwEj71b6AukGDKEQnWjIkGLtrEhKBWfGuZcz7PttEdefpThHx76JH6hl2OqEufI7pEfMPP1u8YiqjEpkh/+2NaY/nj4Aqi498A==) for people that really need checkbox to adapt to the text size within particular paragraph:
- use `v-checkbox-btn` as `v-checkbox` does not expose `inline` prop
- `.v-checkbox-btn .v-label { font-size: 1em; /* 1rem by default */ }`
- and more CSS if you need the label perfectly aligned with the text (`vertical-align: middle` is not enough)
