### ISSUE TITLE
[Bug Report][3.0.0-beta.1] <v-text-field>Does Not Look As It Should

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuetifyjs/vuetify#15096]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.54
**OS:** Windows 10

### Steps to reproduce
1. Using a Vite Vue 3 Template from Stackblitz
2. Installing Vuetify 3.0.0-beta.1 (also tried 3.0.0-beta.0)
3. Adding Vuetify as per the docs

### Expected Behavior
All components looking as they should.

### Actual Behavior
The textifield doesn't look as it should (an it's the only one i'm aware of, didn't check other components besides `<v-btn>` and `<v-textfield>`.
When the textfield has focus, the CSS of the internal `<input>` used in the Vuetify's component seems to be messed up because it contains a border.

![image](https://user-images.githubusercontent.com/10191085/168451452-d6d7ce2f-8ffa-4a82-b855-5154e72ea256.png)

Also, the label when expanded to the top, overlays any items that is on top, in my case a <v-btn>.

### Reproduction Link
<a href="https://github.com/angelhdzmultimedia/vitejs-vite-bhc5we" target="_blank">https://github.com/angelhdzmultimedia/vitejs-vite-bhc5we</a>

### Final Words
I don't remember this happening the other times I tried Vuetify v3 alpha.

**Comment by MajesticPotatoe** [comment]
you are missing `import 'vuetify/styles'` in your main.ts
<https://next.vuetifyjs.com/en/getting-started/installation/#usage>

**Comment by angelhdzmultimedia** [comment]
> you are missing `import 'vuetify/styles'` in your main.ts https://next.vuetifyjs.com/en/getting-started/installation/#usage

Life saver! Thanks!

 I've tried it many times before, to keep track of the development until it gets enough mature. This time I forgot, in effect, the CSS imports because was in a hurry on stackblitz.com. Oops!🤦‍♂️
And when I use TailwindCSS, I always get sure to write all the imports... 

Wellp, 

> "Even the best hunters lose their prey"

.Stay safe!

**Comment by angelhdzmultimedia** [comment]
Still, is something that can be done to fix the `<v-text-field>`'s  **label** overlaying elements on top, other than by tweaking the margin/gap between the elements?

![image](https://user-images.githubusercontent.com/10191085/168452247-a4b328a4-500e-4b6e-a6e0-8a569fe8e3a6.png)

This doesn't happen in Quasar out of the box...

![image](https://user-images.githubusercontent.com/10191085/168452330-f69825da-34b0-4845-b62e-b99fe473e23a.png)

**Comment by MajesticPotatoe** [comment]
V3 is still in beta, and there may be unforseen interactions as such between components still. As far as I can tell though this is something that exists even in v2 and is likely intended. It only effects the 3 variants **underlined** / **outlined** / **plain** as these variants place the label on the bounding box.  The simple solution would be to apply margin to the the component with helper class eg: `class="mb-1"`.

**Comment by angelhdzmultimedia** [comment]
> V3 is still in beta, and there may be unforseen interactions as such between components still. As far as I can tell though this is something that exists even in v2 and is likely intended. It only effects the 3 variants **underlined** / **outlined** / **plain** as these variants place the label on the bounding box. The simple solution would be to apply margin to the the component with helper class eg: `class="mb-1"`.

It works as it should in these scenarios:

1. No variant attribute
2. variant = "contained"
3. variant = "filled"

![image](https://user-images.githubusercontent.com/10191085/168456853-d424d46f-9627-4ba9-b2b9-20865fe6305e.png)

It does **not** work in these scenarios:

1. variant = "plain"
2. variant = "underlined"

![image](https://user-images.githubusercontent.com/10191085/168456894-25de473c-cbb4-4475-9d15-8b7810b4e15a.png)

**Comment by angelhdzmultimedia** [comment]
### Update

Just tried Vuetify 2 in codepen. It works as it should there. Out of the box theres enough space between the v-btn and the v-text-field to show the v-text-field 's animated label without having to add a margin.

So this evidently proves there's something wrong with it on Vue 3.

**Comment by MajesticPotatoe** [comment]
still happens in
v2: https://codepen.io/majesticpotatoe-the-bashful/pen/PoQWvzm
v3: https://codepen.io/majesticpotatoe-the-bashful/pen/BaYpeWw
out of the 3 variants that this effects in v3: underlined / outlined / plain - plain is a new variant, underlined is technically the old default, albeit they are constructed differently in v3 (v2 had some additional margin to it) outlined though behaves the same though.
All in all I would consider that a different issue then what was initially portrayed in this bug report. Feel free create a new issue portraying this with a included codepen reproductions
