### ISSUE TITLE
Tooltip might be hidden inside datatables

### ISSUE THREAD

**Issue by psychonetic** [vuetifyjs/vuetify#1509]
### Steps to reproduce
If you use a datatable with tooltips inside, the tooltip might be hidden.
See below on the right side:
![bildschirmfoto 2017-08-28 um 21 09 03](https://user-images.githubusercontent.com/4885172/29789154-7519bc96-8c35-11e7-97d1-c124392efc6f.png)

### Versions
vue 2.1.10
vuetify 0.15.0-beta.3

### What is expected ?
Tooltip should always in foreground.

### What is actually happening ?
Tooltip is partly hidden inside the datatable.

### Reproduction Link
https://codepen.io/anon/pen/oePaVL

**Comment by johnleider** [comment]
There are a bunch of issues on this already, #1313 and #999 for a few. Thank you for the report.
