### ISSUE TITLE
[Bug Report][2.6.0] Autocomplete - render initial value only works when 'multiple' prop is set

### ISSUE THREAD

**Issue by woutercouvaras** [vuetifyjs/vuetify#15091]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.12
**Browsers:** Firefox 100.0
**OS:** Mac OS 10.15

### Steps to reproduce
Click on the reproduction link and simply view.
This example comes straight from the docs - all we did was remove the "multiple" prop.
We are not sure if this is intended behaviour or not, but our guess is that it is a bug.

### Expected Behavior
We expected that the provided, intial data would render, whether or not the "multiple" prop was provided or not.

Of course we would expect that, without "multiple",  only a single item would be rendered.

### Actual Behavior
As soon as the "multiple" prop is removed, no item gets rendered.

### Reproduction Link
<a href="https://codepen.io/woutercouvaras/pen/dydOPWy?editors=101" target="_blank">https://codepen.io/woutercouvaras/pen/dydOPWy?editors=101</a>

**Comment by KaelWD** [comment]
> without "multiple", only a single item would be rendered

That would be pretty unexpected considering the initial value is an array. If you only want to show a single item use a single value instead of an array.

**Comment by woutercouvaras** [comment]
Wow, I feel rather daft!  I don't know why I didn't try that.

The examples with pre-populated data all show arrays, so I made the stupid assumption that the model had to be an array.

Sorry for the wasted time and thanks for the quick response!
