### ISSUE TITLE
[Bug Report][2.6.5] Treeview component has performance issue when search and filter 

### ISSUE THREAD

**Issue by wyhsunflower** [vuetifyjs/vuetify#15098]
### Environment
**Vuetify Version:** 2.6.5
**Vue Version:** 2.6.0
**Browsers:** Chrome 94.0.4606.71
**OS:** Mac OS 10.14.6

### Steps to reproduce
When the items data exceeds 3000, the search and filter functions will have performance problems, the page locks up and becomes very slow.
1. open the codeopen page.
2. Type "ben" as the keywords.
3.click the delete key to clear the search input.

### Expected Behavior
The performance has improvements

### Actual Behavior
when search and filter, the page freeze.

### Reproduction Link
<a href="https://codepen.io/Hazellllll/pen/PoQzjZw?editors=1010" target="_blank">https://codepen.io/Hazellllll/pen/PoQzjZw?editors=1010</a>

**Comment by barrettathome** [comment]
Facing the same issue with just over 1200 items.
