### ISSUE TITLE
[Bug Report][2.6.5] When dynamically modifies items of Treeview, it will trigger to modify the value of v-model

### ISSUE THREAD

**Issue by wyhsunflower** [vuetifyjs/vuetify#15099]
### Environment
**Vuetify Version:** 2.6.5
**Vue Version:** 2.6.0
**Browsers:** Chrome 94.0.4606.71
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Copy "tech team" into the search input.
2. The console log: 
 "selectHandler-selectedValue" // [object Array] (0) []
This means Treeview @input event has be called.
4. clear the value, the selected node gone.
 But in the Select component, the same operation above will not change the value of v-model.
https://codepen.io/Hazellllll/pen/XWZKgbZ?editors=1011

### Expected Behavior
Modifying items values does not affect v-model values

### Actual Behavior
The v-model value doesn't change when the items value change.

### Reproduction Link
<a href="https://codepen.io/Hazellllll/pen/eYVzvJX?editors=1010" target="_blank">https://codepen.io/Hazellllll/pen/eYVzvJX?editors=1010</a>

**Comment by KaelWD** [comment]
If you use the built in filtering this won't happen: #5621
There was a feature request for the same behaviour in v-select but they are fundamentally quite different components: #14721

**Comment by wyhsunflower** [comment]
The filter you mentioned have performance issue...That's why I need to filter by myself. Yes, they are different component.But, both are Vuetify component, right?
