### ISSUE TITLE
[Documentation] vuetify3.0 textarea document example code false

### ISSUE THREAD

**Issue by zzttqu** [vuetifyjs/vuetify#15105]
### Environment

**Browsers:** Chrome 101.0.4951.64
**OS:** Windows 10

### Steps to reproduce
 <v-textarea
          solo
          name="input-7-4"
          label="Solo textarea"
        ></v-textarea>
the 'solo' property should be variant="solo"

### Expected Behavior
the 'solo' property should be variant="solo"

### Actual Behavior
nothing happend and all variant don't appear

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/textareas/" target="_blank">https://next.vuetifyjs.com/en/components/textareas/</a>

**Comment by ElijahKotyluk** [comment]
The current variants are : `'underlined', 'outlined', 'filled', 'contained', 'plain'`

Try `variant="contained"`
