### ISSUE TITLE
[Bug Report][3.0.0-beta.1] Icon get overflow in `v-btn` component if you add using `prepend-icon` prop. 

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15106]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.34-beta.1
**Browsers:** Chrome 101.0.4951.67
**OS:** Windows 10

### Steps to reproduce
Try to add a `prepend-icon` in btn using the same prop.

### Expected Behavior
The icon should not overflow `v-btn`'s padding.

### Actual Behavior
Its get overflow.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/qBxrOam?editors=101" target="_blank">https://codepen.io/Alokdev/pen/qBxrOam?editors=101</a>

**Comment by KaelWD** [comment]
`prepend-icon` is equivalent to `<v-icon start>`: https://codepen.io/kaelwd/pen/abqywaz?editors=1010
