### ISSUE TITLE
[Bug Report][3.0.0-beta.0] The createvuetify.defaults.vbtn.veriant = contained configuration does not take effect

### ISSUE THREAD

**Issue by zhengyimeng** [vuetifyjs/vuetify#15104]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.25
**Browsers:** Chrome 101.0.4951.64
**OS:** Mac OSX

### Steps to reproduce
yarn install
yarn dev

### Expected Behavior
The variant attribute of the button is "contained"

### Actual Behavior
The variant attribute of the button is "outlined"

### Reproduction Link
<a href="https://github.com/zhengyimeng/vuetify-test" target="_blank">https://github.com/zhengyimeng/vuetify-test</a>

**Comment by KaelWD** [comment]
Buttons in toolbars are flat by default:
https://github.com/vuetifyjs/vuetify/blob/24d913fef0eed3084efc55daef400b4fa5a464f0/packages/vuetify/src/components/VToolbar/VToolbar.tsx#L97-L103

This can be overridden with `defaults: { VToolbar: { VBtn: { ...`
