### ISSUE TITLE
[Bug]Toolbar not scrolling off

### ISSUE THREAD

**Issue by Huixiong91** [vuetifyjs/vuetify#1511]
### What is expected ?
Toolbar to scroll off

### What is actually happening ?
Toolbar is fixed and not scrolling off

### Reproduction Link
v0.14.11 : https://codepen.io/HuiXiong/pen/PKyXPX
v0.15 beta: https://codepen.io/HuiXiong/pen/zdmyqZ

In v0.15 beta, the toolbar doesn't seem to scroll off anymore.

**Comment by johnleider** [comment]
It looks like when this was converted to a la cart, @nekosaur didn't have the updated toolbar changes. Added them back.

**Comment by pmesgari** [comment]
The issue still persists. Here is the codepen using Vuetify 0.15.3
[(https://codepen.io/anon/pen/RLbwOB)]
The toolbar does not move as you scroll.
