### ISSUE TITLE
[Feature Request] v-data-table API

### ISSUE THREAD

**Issue by bwpows** [vuetifyjs/vuetify#15119]
### Problem to solve
Will this "v-data-table" api still be supported in the vuetify3 version in the future?

### Proposed solution
I just ask

**Comment by AntoninBeaufort** [comment]
It's in the  3.1.0 milestone https://github.com/vuetifyjs/vuetify/issues/13479

**Comment by ElijahKotyluk** [comment]
Yes, `VDataTable` is in the roadmap. You can check #13479.
