### ISSUE TITLE
[Bug Report][2.6.6] v-autocomplete does not open on append/prepend icon click when fetching item data with api

### ISSUE THREAD

**Issue by itsteddyyo** [vuetifyjs/vuetify#15120]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 101.0.4951.54
**OS:** Windows 10

### Steps to reproduce
1. Click on prepend icon as the initial click. 
2. Method for loading data is called and v-autocomplete displays loading bar
3. Dropdown-Menu does not open

On the other hand this works
1. Click on the autocomplete textbox as the initial click. 
2. Method for loading data is called and v-autocomplete displays loading bar
3. Dropdown-Menu does open
4. Click on another Element to blur and close the menu
5. Click on prepend icon as the second click. 
6. Method for loading data is called and v-autocomplete displays loading bar
7. Dropdown-Menu does open

### Expected Behavior
Dropdown-Menu opens after loading data

### Actual Behavior
Dropdown-Menu does not open

### Reproduction Link
<a href="https://codepen.io/fsaller/pen/PoQmWvX" target="_blank">https://codepen.io/fsaller/pen/PoQmWvX</a>

### Other comments
CodePen is essentially [this one from the Documentation](https://vuetifyjs.com/en/components/autocompletes/#api-search).
Only modified to have click and click:append/prepend event-handlers

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/WNMOExq?editors=1010

The prepend icon never opens the menu, you must have misclicked.
