### ISSUE TITLE
[Feature Request] $event analog for v-intersect

### ISSUE THREAD

**Issue by Madyuskin** [vuetifyjs/vuetify#15125]
### Problem to solve
I want to pass an additional argument to a handler for v-intersect. For, for example, a click event I can do this with $event.
<pre>
@click="handleClick($event, arg1)"

handleClick(event, arg1) {
}
</pre>

### Proposed solution
Is there a solution already?

**Comment by KaelWD** [comment]
`handleClick($event, arg1)` is syntax sugar for `($event) => handleClick($event, arg1)`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com).
