### ISSUE TITLE
[Bug Report][2.6.6] v-btn not visible when "disabled" prop holds an OR(| |) operator  

### ISSUE THREAD

**Issue by wesley3295** [vuetifyjs/vuetify#15123]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 101.0.4951.64
**OS:** Windows 10

### Steps to reproduce
Test in chrome refresh page

### Expected Behavior
show btn

### Actual Behavior
btn is missing until mouse activity (click)

### Reproduction Link
<a href="https://codepen.io/wes3295/pen/KKQqKBY" target="_blank">https://codepen.io/wes3295/pen/KKQqKBY</a>

### Other comments
Btn wont appear until there is activity by clicking on the screen. works in codepen, but not in chrome.

**Comment by KaelWD** [comment]
Works for me, do you have any browser extensions installed?
