### ISSUE TITLE
In ios safari, it doesn't show the ripple.

### ISSUE THREAD

**Issue by kimixu717** [vuetifyjs/vuetify#1512]
In ios safari, it doesn't show the ripple. But if you hold the element for second, it can show the ripple sometimes.

**Comment by kimixu717** [comment]
I have checked that vuetify can not use with fastclick , if i remove fastclick , it works! ios 10.3.3

**Comment by johnleider** [comment]
I assume this is resolved for you. If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
