### ISSUE TITLE
[Feature Request] VAutocomplete allow to set model value to any text

### ISSUE THREAD

**Issue by zorn-v** [vuetifyjs/vuetify#15133]
### Problem to solve
Currently v-autocomplete works just like "select with search". 
Proposed feature will allow use it as "text field with hinter". With it you can use it like "Probably you mean" for example

### Proposed solution
Add another property like "suggestion-mode" (invent better name)

**Comment by KaelWD** [comment]
That's what combobox is.

**Comment by zorn-v** [comment]
Thanks. Don't know how I missed it :eyes:
