### ISSUE TITLE
[Bug Report][3.0.0-beta.2] When using v-tooltip in v-button, if the button trigger a router event, the router change may fail

### ISSUE THREAD

**Issue by GuMengYu** [vuetifyjs/vuetify#15130]
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.35
**Browsers:** Edge 101.0.1210.32
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use `v-tooltip` components in `v-button`
```
<v-btn class="mr-2" @click="back">back
    <v-tooltip activator="parent" anchor="bottom">back</v-tooltip>
</v-btn>
```
step1: push to page 1
step2: push to page 2
step3: use `router.back()` or `history.back()` back to page1

### Expected Behavior
go back to page1

### Actual Behavior
not working,  throw error
```
Error: Navigation aborted from "/explore" to "/discover" via a navigation guard.
    at createRouterError (vue-router.esm-bundler.js:827:23)
    at next (vue-router.esm-bundler.js:1911:24)
    at vue-router.esm-bundler.js:1971:18
    at VOverlay.tsx:168:9
    at router.tsx:87:35
```

### Reproduction Link
<a href="https://codepen.io/gumengyu/pen/GRQEYOJ" target="_blank">https://codepen.io/gumengyu/pen/GRQEYOJ</a>

### Other comments
Related source code:
packages/vuetify/src/components/VOverlay/VOverlay.tsx
```
useBackButton(next => {
      if (isTop.value && isActive.value) {
        next(false)
        if (!props.persistent) isActive.value = false
        else animateClick()
      } else {
        next()
      }
    })
```

**Comment by KaelWD** [comment]
We can't tell the difference between that and the actual back button: https://github.com/vuejs/vue-router/issues/3453

I've added a `close-on-back` prop that is false by default in v-tooltip
