### ISSUE TITLE
[Bug Report][2.6.6] v-range slider with slots is laggy

### ISSUE THREAD

**Issue by KeterSCP** [vuetifyjs/vuetify#15136]
### Environment
**Vuetify Version:** 2.6.6
**Last working version:** 2.1.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 101.0.4951.67
**OS:** Windows 10

### Steps to reproduce
Open the reproduction link and try to move both sliders. 

### Expected Behavior
Both sliders update thumb position smoothly.

### Actual Behavior
You can notice that one with append and prepend slots is not updating smoothly.

https://user-images.githubusercontent.com/38229504/169805179-bd7001f2-6df6-4298-bfff-48d1c877cb05.mp4

### Additional Information
If I change monitor refresh rate to 60 Hz, it works fine. The issue appears on 100, 120, 144 Hz

### Reproduction Link
<a href="https://codepen.io/Keter_SCP/pen/abqyQeO" target="_blank">https://codepen.io/Keter_SCP/pen/abqyQeO</a>

**Comment by KaelWD** [comment]
I can't reproduce this, probably a browser bug.

**Comment by KeterSCP** [comment]
@KaelWD have you tried it on 144 Hz monitor?

**Comment by KaelWD** [comment]
144 and 165, but on linux

**Comment by KeterSCP** [comment]
Strange, I can still reproduce it on my screen with latest chrome and windows 10...

**Comment by KaelWD** [comment]
I'll check it next time I can be bothered booting windows I guess.

**Comment by KeterSCP** [comment]
After bisection, it appears it works fine in 2.4.5 and has been broken since 2.4.6

**Comment by lioneaglesolutions** [comment]
@KeterSCP is this still present in V3?

**Comment by KeterSCP** [comment]
@lioneaglesolutions no, in V3 it works properly
