### ISSUE TITLE
[v0.15.0-beta.4] v-form does not respect v-on:submit.prevent directive

### ISSUE THREAD

**Issue by roblav96** [vuetifyjs/vuetify#1513]
### Steps to reproduce
```html
<v-form v-on:submit.prevent="login()">
	<v-text-field label="Name" v-model="name" :rules="nameRules" :counter="10" required></v-text-field>
	<v-text-field label="E-mail" v-model="email" :rules="emailRules" required></v-text-field>
</v-form>
```

### Versions
v0.15.0-beta.4

### What is expected ?
Pressing enter key should not `post` form url (or refresh the page).

### What is actually happening ?
The page is refreshed with a `?` after the current url.

Awesome work on this project =]

**Comment by johnleider** [comment]
I'll have to talk with @nekosaur as this was his pet project, but I'm not sure if ```v-form``` works like that.

Also:
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
