### ISSUE TITLE
[Bug Report][3.0.0-beta.2] VCombobox rules applied to search, not items

### ISSUE THREAD

**Issue by AntoninBeaufort** [vuetifyjs/vuetify#15142]
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.36
**Browsers:** Chrome 101.0.4951.67
**OS:** Windows

### Steps to reproduce
`npm run serve`, open in browser
Select one item in first v-combobox, two in the second and click Submit button.

### Expected Behavior
The multiple v-combobox rules should work.

### Actual Behavior
Rules not working because they apply on search.

### Reproduction Link
<a href="https://github.com/AntoninBeaufort/vuetify-combobox-rules" target="_blank">https://github.com/AntoninBeaufort/vuetify-combobox-rules</a>

### Other comments
In source files it seems that rules are binded to v-text-field and the modelValue of v-text-field is the search value not the items.

**Comment by AntoninBeaufort** [comment]
I can confirm that the error also occurs on @vuetify/nightly: 3.0.0-next-20220529.0
It's only if the multiple prop is enabled, on single value v-combobox works even with complex items (array of objects instead of array of strings).

**Comment by AntoninBeaufort** [comment]
There is the same problem on VAutocomplete even on latest nightly / on Playground component of next branch, the VTextField modelValue is search which is undefined whereas the model of the VAutocomplete is working as expected.

**Comment by KaelWD** [comment]
And VSelect is passing `model.value.map(v => v.props.value).join(', ')`
