### ISSUE TITLE
[Bug Report][3.0.0-beta.2] v-select warning children undefined

### ISSUE THREAD

**Issue by AntoninBeaufort** [vuetifyjs/vuetify#15150]
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.2.36
**Browsers:** Chrome 101.0.4951.67
**OS:** Windows

### Steps to reproduce
1. clone
2. switch to branch v-select-children-undefined
3. `npm i`
4. `npm run serve`
5. Open app in browser with console
6. Try to select an item
7. Look at warnings

### Expected Behavior
No warning, like in beta.1

### Actual Behavior
Warning like this on selection

> **Warning**
> [Vue warn]: Failed setting prop "children" on \<div\>: value undefined is invalid. TypeError: Cannot set property children of \#\<Element\> which has only a getter

### Reproduction Link
<a href="https://github.com/AntoninBeaufort/vuetify-combobox-rules/tree/v-select-children-undefined" target="_blank">https://github.com/AntoninBeaufort/vuetify-combobox-rules/tree/v-select-children-undefined</a>

### Comments

I guess it comes from this PR: https://github.com/vuetifyjs/vuetify/pull/15079

I tried to remove it by updating this line in packages/vuetify/src/composables/items.ts:

```diff
export function transformItem (props: ItemProps, item: any) {
  const title = getPropertyFromItem(item, props.itemTitle, item)
  const value = getPropertyFromItem(item, props.itemValue, title)
  const children = getObjectValueByPath(item, props.itemChildren)

  return {
    title,
    value,
-     children: Array.isArray(children) ? transformItems(props, children) : undefined,
+    ...(Array.isArray(children) && { children: transformItems(props, children) }),
    ...props.itemProps?.(item),
  }
}
```

I have no warning with this update, everything is working fine on my side.

**Comment by nekosaur** [comment]
Getting fixed here https://github.com/vuetifyjs/vuetify/pull/15108
