### ISSUE TITLE
[v0.15.0-beta.4] Disabled dates on date picker are not greyed out

### ISSUE THREAD

**Issue by mmajcenic** [vuetifyjs/vuetify#1515]
On v0.15.0-beta.4 disabled dates are no longer grey. Issue can be seen in documentation, or codepen:
https://codepen.io/Sarpedion/pen/MvzgJr

I am also adding a picture from docs:

![image](https://user-images.githubusercontent.com/16826299/29813260-e8f3c3e0-8ca9-11e7-9420-6a4699e258f8.png)

**Comment by jacekkarczmarczyk** [comment]
When providing `Object` date picker expects value with `min` and `max` properties:
```
{
  min: '2017-01-01',
  max: '2017-02-02'
}
```
