### ISSUE TITLE
V-Tabs on touch devices are scrollable even with nothing to scroll

### ISSUE THREAD

**Issue by zaken** [vuetifyjs/vuetify#1516]
### Steps to reproduce
1. Create `v-tabs`
2. Use Dev tools to inspect on mobile device.

### Versions
Vuetify v0.15.0-beta.4
Latest Vue/Chrome

### What is expected ?
When there is no overflow, disable scrolling on touch devices.

### What is actually happening ?
Even with only one tab and `:scrollable='false'` you can swipe the tabs bar.

### Reproduction Link
https://codepen.io/anon/pen/aLZbBw

**Comment by johnleider** [comment]
Does it not slide right back into place though?

**Comment by dzift** [comment]
It does but I think tabs shouldn't slide when they can fit into their container.

**Comment by Perezmarc** [comment]
Any updates?

**Comment by Ritwik001** [comment]
is fix available for this? I still encouter this issue?
