### ISSUE TITLE
[Bug Report][3.0.0-beta.2] HMR not getting applied when updating an element in various contexts

### ISSUE THREAD

**Issue by TechAkayy** [vuetifyjs/vuetify#15163]
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.31
**Browsers:** Chrome 101.0.4951.64
**OS:** Mac OS 10.15.7

### Steps to reproduce
HMR is mostly not getting applied when updating vuetify tags within v-for loops, and also in various contexts. 

In the attached reproduction (please first fork the repo, and then make updates): 
- update **v-btn**'s (**within v-for loop**) color from 'red' to 'green', and save the page, and HMR is not getting applied, and requires page refresh everytime to apply the update. 
- the **v-slider** (**not within v-for loop**). Try changing the step from '5' to '10', and save file, HMR doesn't apply, and requires page refresh for every atomic update like this. 

https://user-images.githubusercontent.com/73772701/170832790-b55037ee-c649-43f1-8fc2-11172e9cee47.mp4

I have also tried numerous other scenarios, where HMR mostly is not working well within various contexts. This impacts our DX a lot, especially when working on something (template & style sections, and not script section) where we want the state preserved. 

### Expected Behavior
HMR should apply correctly when updating vuetify tags within various contexts (eg, v-for loops), at least most of the time (if not 100% of the time)

### Actual Behavior
HMR is mostly not getting applied when updating vuetify tags esp for elements within various contexts (eg, v-for loops)

### Reproduction Link
<a href="https://stackblitz.com/github/TechAkayy/vuetify3-beta-hmr-bug?file=src%2FApp.vue" target="_blank">https://stackblitz.com/github/TechAkayy/vuetify3-beta-hmr-bug?file=src%2FApp.vue</a>

**Comment by KaelWD** [comment]
Vue bug, looks like https://github.com/vuejs/core/issues/1942 wasn't fixed properly. https://github.com/vuejs/core/pull/2359 added a check for `instance.parent.type.__hmrId` but in this case only `instance.parent.parent.type.__hmrId` is set because v-app is also a non-sfc component.

**Comment by TechAkayy** [comment]
Good day @KaelWD, just wanted to understand what our protocol is for dealing with upstream bugs like this one. 

Does the vuetify team collate bugs under the upstream tag, and raise it with the upstream repo? Or should I create a ticket with vuejs/core for this one? 

I have been encountering these kinda HMR issues too frequent, so wondering if vuetify could have some workaround in place while the upstream fix is pending. 

Note, I have updated the title of this card, as the HMR issues are not only happening with elements within v-for loops, but rather in various random contexts. 

Thanks, have a good day!

**Comment by KaelWD** [comment]
There's already a pr: https://github.com/vuejs/core/pull/4077
The only workaround would be for you to use patch-package to apply the fix.

**Comment by TechAkayy** [comment]
Sweet. Thanks for the pointer @KaelWD

**Comment by johnleider** [comment]
This is being closed because it has little to do with us. Watch https://github.com/vuejs/core/pull/4077 for more relevant updates.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
