### ISSUE TITLE
[Bug Report][2.6.6] Select menu keyboard and mouse interaction differs

### ISSUE THREAD

**Issue by manuelmeister** [vuetifyjs/vuetify#15173]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.5005.61
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click in writeable multiple chip select field

### Expected Behavior
Menu should open

### Actual Behavior
Menu does not open

### Reproduction Link
<a href="https://codepen.io/manuelmeister/pen/yLvKWKZ" target="_blank">https://codepen.io/manuelmeister/pen/yLvKWKZ</a>

### Other comments
The behavior is correct if you use keyboard navigation.

This only happens if you set the menu-prop `openOnClick` to true. I've set this because I want to open the menu, if I click on a chip. Currently if you click a chip, the menu does not open (see second select in reproduction).

|Mode|Input device|Interaction|Functionality|
|:----|:----|:----|:----|
|Write mode|Keyboard|Opens|✅ correct|
|Write mode|Mouse|doesn't open|🚫 wrong|
|Readonly|Keyboard|doesn't open|✅ correct|
|Readonly|Mouse|Opens|🚫 wrong|

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
