### ISSUE TITLE
[Bug Report][2.6.6] autocomplete

### ISSUE THREAD

**Issue by himrhua** [vuetifyjs/vuetify#15171]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.8
**Browsers:** Chrome 101.0.4951.64
**OS:** Windows 10

### Steps to reproduce
Hi ,I use the v-autocomplete multiple function, select one to select two, does anyone know?

### Expected Behavior
search li and select  list_method 

### Actual Behavior
search li and select  list_method what highlighte list_permission

### Reproduction Link
<a href="https://codepen.io/hua0124/pen/qBxooMo?editors=1011" target="_blank">https://codepen.io/hua0124/pen/qBxooMo?editors=1011</a>

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
