### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-select and v-autocomplete objects for items prop broken

### ISSUE THREAD

**Issue by Tomdanizer** [vuetifyjs/vuetify#15178]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.36
**Browsers:** Edge 101.0.1210.53
**OS:** Windows 10

### Steps to reproduce
These two example sections in the docs and their respective codepens:
https://next.vuetifyjs.com/en/components/selects/#props
https://next.vuetifyjs.com/en/components/autocompletes/#item-and-selection

Passing in an object to either input and setting the item-value and item-text props on the v-select or v-autocomplete component.

### Expected Behavior
To be able to map an objects property to the item-text and item-value props of the input component(s) and have the corresponding values display in the field and v-model.

### Actual Behavior
Empty chips and boxes/fields, freezing and or crashing of browser sometimes

### Reproduction Link
<a href="https://codepen.io/tomdanizer/pen/VwQxyxO?editors=1010" target="_blank">https://codepen.io/tomdanizer/pen/VwQxyxO?editors=1010</a>

**Comment by evans23** [comment]
On this example, https://next.vuetifyjs.com/en/components/autocompletes/#item-and-selection , it appears that at least the 'selection' and 'item' slots are not working. Is that fixed in https://github.com/vuetifyjs/vuetify/pull/15110 or is that a separate issue/feature?

**Comment by mcheung610** [comment]
the 'no-data' slot is also not working. I can't get any events to fire in the no-data slot.

**Comment by AntoninBeaufort** [comment]
> On this example, https://next.vuetifyjs.com/en/components/autocompletes/#item-and-selection , it appears that at least the 'selection' and 'item' slots are not working. Is that fixed in #15110 or is that a separate issue/feature?

For the item and selection example, I've just updated the `item-text` to `item-title` so the list items should not be empty but populated by name because before the item-title attribute the component was searching for a `title` property in the array of items.

If there is a problem with slots you can search if there are already issues/PR an if not, open yours.
