### ISSUE TITLE
[v0.15.0-beta.4] Colour of v-icon (when child of v-btn) not inverted when decedent of a dark-themed ancestor

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#1517]
### Steps to reproduce
Create a `v-toolbar` with the `dark` property. Add a `v-btn` with a child `v-icon` to the toolbar. The `v-icon` color is not inverted - it is *only* inverted if the parent `v-btn` has the `icon` property set.

### Versions
v0.15.0-beta.4

### What is expected ?
The child `v-icon`'s colour should be inverted. (This used to work in v0.14.11.)

### What is actually happening ?
The child `v-icon`'s colour remains unchanged.

### Reproduction Link
https://codepen.io/wernerm/pen/dzggZb

**Comment by HendrikGrobler** [comment]
Can confirm this. Happens specifically when the app has a light theme. The dark app theme in the dev docs means it doesn't show there, but this codepen is an exact copy of the button icons section just with a light app theme:
https://codepen.io/anon/pen/OjaVyy

**Comment by johnleider** [comment]
This will actually be a chance for the button to always inherit its parent button/button__content's color. This will still be possible to override with manual colors if you so choose.
