### ISSUE TITLE
open dropdown menu under element that triggers it

### ISSUE THREAD

**Issue by miquels** [vuetifyjs/vuetify#152]
It would be nice if there was an option for a dropdown menu to open underneath the element that triggers it, instead of on top of it.

It's probably visually nice to keep the triggering element visually active (same state as hovering over it) as long as the menu is visible. 

Not sure if that is part of MD (or even allowed).

**Comment by johnleider** [comment]
This is possible with offset. In fact, it is done in the docs on the toolbar page. Or am I misunderstanding what you are asking for?

**Comment by miquels** [comment]
Ah, you are right. It's just that the docs are missing. Minor feature request then:
- could the activator stay 'visually active' as long as the menu is showing
- it would be nice if clicking on the activator also closed the dropdown again.
However feel free to close this bug.
