### ISSUE TITLE
[Bug Report][3.0.0-beta.3] VTextField does not clear input if v-model is object prop and that object recreated

### ISSUE THREAD

**Issue by zorn-v** [vuetifyjs/vuetify#15203]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.36
**Browsers:** Firefox 101.0
**OS:** Linux x86_64

### Steps to reproduce
Open reproduction link enter something in vuetify input say "vuetify" and press "Clear obj" button. Text in vuetify input does not cleared.
Next enter something else to native input say "native" (text in vuetify input also become "native") and click button again. Native input is cleared as expected, but vuetify returns previous entered "vuetify"

### Expected Behavior
Vuetify input should be cleared as native input

### Actual Behavior
Vuetify input remember what you enter and returns it instead of clear on object recreated

### Reproduction Link
<a href="https://codesandbox.io/s/cocky-murdock-zbxqcz?file=/src/App.vue" target="_blank">https://codesandbox.io/s/cocky-murdock-zbxqcz?file=/src/App.vue</a>

**Comment by KaelWD** [comment]
@vuetifyjs/core-team do we actually need this undefined check here if we're looking on the vnode props anyway?
https://github.com/vuetifyjs/vuetify/blob/0ad9d7f0efba50f0be4d56b4d13a7aaf155dc765/packages/vuetify/src/composables/proxiedModel.ts#L24

**Comment by nekosaur** [comment]
I might be misremembering, but I think I added that so that computed would recompute correctly. I don't think `vm.vnode.props` is reactive?

**Comment by johnleider** [comment]
If you're going to manually reset the value, you should target the property you are designating as the model or reset the object to contain the **prop**. 

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
