### ISSUE TITLE
Expansion List: support multiple open groups

### ISSUE THREAD

**Issue by mojo2012** [vuetifyjs/vuetify#1520]
An open list group in  the expansion list closes when clicked on another list entry.
Basically only one list group can be expanded at once.

It would be nice if this behaviour changed to not auto-close open list groups - preferably with a setting parameter.

This would allow to implement "explorer trees" more easily.

Currently what I have done to implement a similar approach, is to use multiple independent lists below each other (using a flex grid).

**Comment by nekosaur** [comment]
Use the `expand` prop.

https://codepen.io/anon/pen/vJQORO

**Comment by mojo2012** [comment]
Thanks for the quick answer.

I tried the expansion panel with v0.13 and I wasn't able to make it work as I want. I can't remember what it was, bat I think is was related to layouts and sub elements (icons, "three dot"-action button, etc).
That's why I switched to the list.
I will try it again later
