### ISSUE TITLE
[Feature Request] add Icon in error messages v-text-field

### ISSUE THREAD

**Issue by amjed-ciitizen** [vuetifyjs/vuetify#15216]
### Problem to solve
I am using v-text-fields. I wants to add icon with error messages

### Proposed solution
Add icons with error messages

**Comment by KaelWD** [comment]
There's a slot

**Comment by amjed-ciitizen** [comment]
> 

Can you share sample code of it??

**Comment by KaelWD** [comment]
`<template #message="{ message }">`

**Comment by amjed-ciitizen** [comment]
> `<template #message="{ message }">`

@KaelWD Can you share complete code /example link. Thanks

**Comment by trikarai** [comment]
> > `<template #message="{ message }">`
> 
> @KaelWD Can you share complete code /example link. Thanks

`<v-text-field  v-model="model" :error-messages="v$.model?.$errors">
    <template v-slot:message="{ message }">
           {{ message.$message }}
 </template>
</v-text-field>`
