### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Vuetify components testing in Vue 3 gets [Vue warn]: Failed to resolve component: v-container

### ISSUE THREAD

**Issue by camilaleniss** [vuetifyjs/vuetify#15217]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.13
**Browsers:** Chrome 102.0.5005.61
**OS:** Mac OS 10.15.7

### Steps to reproduce
I was trying to make unit tests in Vuetify components as I did with Vue 2 in a previous project. 

# What happened?

createLocalVue no longer exists in Vue testing utils. The documentation says that we should mount the app like this:
```
const wrapper = mount(ComponentName,
      {
        global:
        { plugins: [vuetify] }
      })
```
Where vuetify should be the vuetify instance created like in the main.js

I did it in so many ways, using a setUpFile, using the plugin/vuetify.js file and more but I obtained
```
[Vue warn]: Failed to resolve component: v-container
    If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
      at <QrCodeInput ref="VTU_COMPONENT" > 
      at <VTUROOT>
```
for each vuetify component, so I can't make like triggers, setInput or whatever I want. 

I asked for help in Discord channel but I didn't get a response 😢 

### Expected Behavior
I expected to be able to do unit testing like I did in this project https://github.com/camilaleniss/vue-testing-course/tree/master/qr-generator-vue-2 (same project but in Vue 2)

### Actual Behavior
Vue cannot resolve vuetify components in Vue 3 
https://github.com/camilaleniss/vue-testing-course/tree/modulo/montando-un-componente/qr-generator-app

### Reproduction Link
<a href="https://github.com/camilaleniss/vue-testing-course/tree/modulo/montando-un-componente/qr-generator-app" target="_blank">https://github.com/camilaleniss/vue-testing-course/tree/modulo/montando-un-componente/qr-generator-app</a>

**Comment by JuanJoseGonGi** [comment]
+1

**Comment by KaelWD** [comment]
See #14749 for suggestions
