### ISSUE TITLE
[Feature Request] Option to Disable Ress CSS Reset

### ISSUE THREAD

**Issue by skymen** [vuetifyjs/vuetify#15214]
### Problem to solve
I want to include a vuetify app into another app, and ress is messing with the parent app's CSS.

For context I'm making a tool that integrates into an app I don't own:
editor.construct.net

### Proposed solution
a boolean to disable the CSS reset. I'd rather take slightly worse vuetify looks than messing with the parent app, cause I don't have control over the parent.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/styles/settings/_variables.scss#L7
