### ISSUE TITLE
[Bug Report][2.6.6] v-autocomplete does not fire update:search-input when selection slot present

### ISSUE THREAD

**Issue by przemeq84** [vuetifyjs/vuetify#15224]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open the page
2. Open code pen console
3. Try to search for "Ala"
4. You can see that the event and watch gets called (`@update:search-input: Ala`, `search: Ala`)
5. Click outside of the autocomplete window
6. Click on autocomplete input again

### Expected Behavior
1. Clicking outside of the autocomplete should print `@update:search-input: null` and  `search: null`
2. Clicking back on the autocomplete should open empty search results

### Actual Behavior
1. No  `@update:search-input: null`, `search: null` is printed in console
2. Autocomplete displays stale search results 

### Reproduction Link
<a href="https://codepen.io/przemeq/pen/yLvxPOE?editors=1011" target="_blank">https://codepen.io/przemeq/pen/yLvxPOE?editors=1011</a>

### Other comments
You can see the expected behavior if you remove the `<template v-slot:selection="{item}">` block from the code.

**Comment by lioneaglesolutions** [comment]
Resolved in V3

https://play.vuetifyjs.com/#eNqNVm1v2zYQ/iucPjQOFtlZ22GAl2QpUqzN2iRFnS0Y6nw4S2eLNUVqJOWXtf7vPVKOpZAOWsCAxeeO9/IcybtPX5JXVdVf1JgMkxOLZSXA4tlYMnaySK1SYgKaZUoofTpOLIIYJ17alaeWW4FnI0tbmUGBmeVKngxChbHc7YTaqkyRN7TYgIwt0lLlKMhPY2OcBJKhQdBZ4RXcR6swFApyLmck2n51ZJzSMiTx/y2eCTAOLlfpyxbNURpu14RTeFOlLUwEtuKC55hKleZg4RGWowUuzAMmYOIzuSvAMuOJAY1srWo21ar8o7Vo7FqgCwNW6ZLnthiyF8fH1er3VuW8rsgftuk365FfXsqq3lF15kjvctvlfGIl45mSzlnO01xZky5QW575qrqtpNLUvq0drU8GnYNBS5NpXlmviKuKOCLWplALy740zhw7rHf4sGRMo621bNdEUFOmIZuCMHjUCnyVhuzTfQdrEh8yWQvxCHbHJIYd3c5ECzF28IpKAiUcdBQb1MwjsERNpEg2glJFQs3/VzJG5yANmAC+AMHpEEke6l+4GwW5imAp3e3JahtIXqOAJR2hEObGUqyWqSkjm3U5iVz9iTlqYiRn/oIap3rFM60kmliZwuJ5iL5BpWeR7psaygB6SzFyHoCXORRhopdCcKl4yNelzDlE5F6qZQi928f2O5S2zubrAH6vak6ZRmavgMuQzyvQpgAh2KURIPPQA4nXDo9gYyAraoPWRlt4VvAZyAimShtlo6C4Me5XVSGNTqJqHcFK2ji3a5zoPSf7GhcQVfcal+wtlJUpeHS+nOwv1AZDUp3gClf0nuwR/Kv0PITpmSjYBWhFhY8i8MLXMI/58CKkt4OodzV8ojA3BQ8DuZkLOnfRjb/ROFNhNT6AgDrEUEqzFguIb++Hmp5NxT7G2X8sqFFtYwxEI1U/zUAj3MvALcWBxmBYmltcRTfgbwtFAP2DuqQjEqKcLrTcH2gji5K+AzogcmYj8u7QWPbUJm6o4xge7Vmrkox10fbB3zQfmy2wBOse/13zaLoB6y1AdFoMTQkg2LNn/u+n01NmC276TYtwsF/+R4Vbjx4mFONN7Lxu3T38l2ipmNRHdi6ithvH4JJVAvtCzXoHj/v2kB2wn110kUfGgrjI7iOrPvZtx2SUma53QxNjgwEb8bJ27Tln8BlWjbVum7S3vEQ6YT3qyadnXctb277pOsueM98m+lMuLOoeRjt27ZxkX7+yg4PDvlXv1RL1BRjsHfa5zHF1M+31Fnvlh+yMpb90LW52lOzJ1g8IrXxzxH49Pn6ianRyTgbb8SQ5SuiizU3/s1GSplufA411hmbA3XAwTgprKzMcDLJckiZNmXyh+xLtQFblgOZiy6fr8xf95/3ng5ya7QOU0jhh+t6Ys3Q/lhtyyEs3DqUlVIHXRuA9b7kcJ2TJrb8TwjmpDXQtLZWQZrbSx/LytyaYDt5HU6YTrZYGNVkZJ1tivB8X8Q/4+l665CIyPSB/NEWmGqnqGvWPphRse5RWIItS25Z6k2yOkmYfce+DTu6/AauisJ4=
