### ISSUE TITLE
[Feature Request] Overlays should close after pressing the escape key

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#15220]
### Problem to solve
Improve the accessibility of `v-overlay` by allowing the escape key to close the overlay.

Related to the dialog equivalent https://github.com/vuetifyjs/vuetify/issues/1326

### Proposed solution
```vue
<v-overlay @keydown.esc="close"></v-overlay>
```

Parallel to the dialog equivalent https://github.com/vuetifyjs/vuetify/issues/1326

**Comment by KaelWD** [comment]
They do in v3

**Comment by aentwist** [comment]
Very much looking forward to 3.1. Thanks!
