### ISSUE TITLE
[Bug Report][2.6.6] Radio group for keyboard users A11y

### ISSUE THREAD

**Issue by Firenzo** [vuetifyjs/vuetify#15225]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.11
**Browsers:** Opera 85.0.4341.71, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Use a keyboard to select a radio button

### Expected Behavior
The underlying `<input>` gets marked as checked as you select the input with a keyboard.

### Actual Behavior
The underlying `<input>` doesn't get any update.

### Reproduction Link
<a href="https://codepen.io/firenzo/pen/abqROJq" target="_blank">https://codepen.io/firenzo/pen/abqROJq</a>

### Other comments
When selecting the radio buttons with a mouse, you can clearly see that the `<input>` gets checked. When I try to do this with a keyboard, it doesn't. I believe it's quite a critical bug, because it breaks the accessibility of Vuetify forms with radio groups in them.

**Comment by lioneaglesolutions** [comment]
This is resolved in V3 - I'm not sure if it will be updated in V2 @johnleider 

This can be shown in both repros when using the arrow buttons (keyboard) to select the radio buttons.

https://play.vuetifyjs.com/#eNrdU1tu2zAQvArLrxYwRcRtUUBVgvQEPYDlD0aiE7Z8gVyqMQLfvStSshwbQfydP80sOTO7Wm5e6C/vqyFJWtMGpPFagLxrLSHNwDpnQSgrA9nppPpM50IQvXLsMbjkC0fIwIzrpb5taed0Mralc2XCGU0Si8iMCdHiIV//7UE5S24WARQXOkmsFd+T0l3DJ6HrlddvK5+ULpSPuPQ9s0/hyrEoq3GUi8GEP+JYRu64O8g0/GSzEMYuKA/5qHz2LgDp5U4kDeSliPYCBPn8ZYaEBAkp2AXPW1UTm7ReLXSZ6hl9KB+HTCBo+DHBmAb2egymrE+wgb2Xt7mhbbEzIjwqy7TcQU3Y+rt//jnSzotOwb4mN+STMmMTwgJWinyWpCuKYf7G6k90Ft9XlsP3EWNLa7IpoVr6BOBjzXnXWzyJy6KGUFkJ3HrD8WWC2u3vv1bras17FWGmGP6/WGWxUWmL1mhYojAj/JlrKWTnaYotRaURvxPhHo/xkCwoI1nvTM7y7UcJc8JXMhr2ENy/KAOqtHSaf/YZE1/h9V67aHEhzdFvkIEFaXsZZLi2pbNrr9o6q120Ni3SgR5WtNzD2efQdPsfZ5KugQ==

**Comment by johnleider** [comment]
Closing as resolved in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
