### ISSUE TITLE
[Bug Report][3.0.0-beta.3] VTabs unexpectedly changed on v-show

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15237]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.63
**OS:** Windows 10

### Steps to reproduce
1. Open https://codepen.io/andrewspy/pen/oNEaaxq?editors=1011
2. Click toggle to hide the tabs.
3. Click toggle again to show the tabs, which changed unexpectedly to "Tab C".

### Expected Behavior
Tabs remain at "Tab A" after toggle.

### Actual Behavior
Tab unexpectedly changed to "Tab C" after toggle.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/oNEaaxq?editors=1011" target="_blank">https://codepen.io/andrewspy/pen/oNEaaxq?editors=1011</a>

**Comment by johnleider** [comment]
fixed by #15267
