### ISSUE TITLE
[Bug Report][3.0.0-beta.2] @change not working in v-select

### ISSUE THREAD

**Issue by toshikitt** [vuetifyjs/vuetify#15235]
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.19
**Browsers:** Chrome 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
<v-row>
                            <v-col cols="6">
                                <v-select
                                    v-model="data"
                                    :items="items"
                                    label=""
                                    variant="underlined"
                                    @change="console.log('Hello')"

                                ></v-select>
                            </v-col>
                            <v-col cols="5">
                            </v-col>
                        </v-row>

### Expected Behavior
when item is selected, @chnage is triggered

### Actual Behavior
@change is not working even though I select an item from v-select

### Reproduction Link
<a href="https://jsfiddle.net/" target="_blank">https://jsfiddle.net/</a>

**Comment by KaelWD** [comment]
`@update:modelValue`
