### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-table thead is not `rtl` compatible

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15234]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.61
**OS:** Windows 10

### Steps to reproduce
try to put `direction:rtl` in your `v-app`. 

### Expected Behavior
theaad text-direction should be changed as per rtl 

### Actual Behavior
Everything Change its direction except Thead

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/gOvBzjK?editors=101" target="_blank">https://codepen.io/Alokdev/pen/gOvBzjK?editors=101</a>

**Comment by nekosaur** [comment]
You're using `text-left` on the header cells, which is not RTL aware. Use `text-start` instead.
