### ISSUE TITLE
[Bug Report][3.0.0-beta.3] VFooter "shifted" right on drawer open in desktop (i.e. lg display)

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15238]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.63
**OS:** Windows 10

### Steps to reproduce
1. Open https://codepen.io/andrewspy/pen/gOvBZRv?editors=1010
2. Click menu button to close/open drawer to see VFooter shifted right on drawer open (on lg display).

### Expected Behavior
VFooter should not "shifted" right on drawer open.

### Actual Behavior
VFooter "shifted" right on drawer open.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/gOvBZRv?editors=1010" target="_blank">https://codepen.io/andrewspy/pen/gOvBZRv?editors=1010</a>

**Comment by nekosaur** [comment]
What is your desired result? Should footer render "above" the navigation-drawer, like this? https://codepen.io/nekosaur/pen/dydQVXJ?editors=1010

**Comment by andrewspy** [comment]
@nekosaur In my use case, I place VFooter inside VMain, so it should be "under" the navigation-drawer (just not supposed to be shifted). If I move VFooter outside of VMain, I will get my desired result.

In your codepen, VFooter is outside of VMain, so it should follow the priority of the existing layout system.

May I know what's the recommended way to place `<VFooter app>` (inside or outside of VMain)? maybe it's a good idea to recommend putting `<VFooter app>` (i.e. with app) outside of VMain to remove the confusion as part of the layout system.

**Comment by nekosaur** [comment]
There is no _one_ recommended way to use VFooter. It all depends on your requirements. You are correct that if you use the `app` prop, it needs to be placed outside of v-main, and that needs to be made clear in the docs.

But I am still a bit unclear on what you want to happen in your case, specifically when you say "not supposed to be shifted". 

Let's use this codepen as a starting point https://codepen.io/nekosaur/pen/MWQzXba?editors=1010. In your desired result, what do you expect to happen when opening the drawer. Should the drawer come in "above" the footer? What about the toolbar, should it be above that as well?

**Comment by andrewspy** [comment]
@nekosaur Thanks for the clarification, your codepen (https://codepen.io/nekosaur/pen/MWQzXba?editors=1010) is exactly what I am expecting, which the drawer is "on top of" both footer and toolbar when the drawer is open.

**Comment by johnleider** [comment]
This is a documentation issue at best and layer 8 at worst. Closing as such.
