### ISSUE TITLE
[Bug Report][2.6.6] V-Checkbox does not emit blur and focus events

### ISSUE THREAD

**Issue by gmeral** [vuetifyjs/vuetify#15232]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 101.0.4951.54
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a v-checkbox to a template
2. Bind focus and/or blur listeners (@focus / @blur)
3. Click checkbox
4. Click outside checkbox

### Expected Behavior
After 3., focus handler is triggered
After 4. blur handler is triggered

### Actual Behavior
After 3., focus handler is not triggered
After 4. blur handler is not triggered

### Reproduction Link
<a href="https://codepen.io/GuillaumeMeral/pen/xxpRXzN" target="_blank">https://codepen.io/GuillaumeMeral/pen/xxpRXzN</a>

### Other comments
I already submitted this error here https://github.com/vuetifyjs/vuetify/issues/14862,
but the PR proposed by @KaelWD did not seem to fix the issue. The v-checkbox still does not trigger focus and blur handlers like a native input with `type="checkbox"` would.

Sorry to seem persistent but the example in the reproduction link still behave the same as it did when i initially reported this.  I also double checked that it loads the correct version of vuetify : 
https://unpkg.com/vuetify@2.6.6/dist/vuetify.js

If i missed something please tell me because this is becoming the source of multiple issues in my own project.

**Comment by KaelWD** [comment]
v-checkbox isn't focused when you click on it, so of course there's no focus event. 

#14862 was actually a bug though, it wasn't emitting focus when it was focused with the keyboard.

**Comment by gmeral** [comment]
Ah ok, i now understand our misunderstanding and what your first fix was about.

Inputs are normally getting focused when interacted with (clicking included) and this is true for the other inputs from vuetify i use ( v-text-field for example, i did not test them all).
I was expecting v-checkbox to have the same behaviour. This is quite important because it allows building more complex inputs with v-checkbox that also need to be focused / blurred when interacted with.

**Comment by KaelWD** [comment]
It'll probably change in v3, `:focus-visible` didn't exist when that was written originally

**Comment by gmeral** [comment]
Ok thanks for the quick answers !
If anyone stumbles upon this i manually emit focus and blur on click and click-outside as a workaround :  
```
<v-checkbox
  @click="$emit('focus')"
  v-click-outside="$emit('blur')"
/>
```

**Comment by xanxuz** [comment]
> Ok thanks for the quick answers ! If anyone stumbles upon this i manually emit focus and blur on click and click-outside as a workaround :
> 
> ```
> <v-checkbox
>   @click="$emit('focus')"
>   v-click-outside="$emit('blur')"
> />
> ```

Now the thing is, how to detect when the user click on the select element (without selecting an element) to close it?, I tried a few things but none of them worked

**Comment by KaelWD** [comment]
This works on click in v3
