### ISSUE TITLE
Expansion panel color override no longer possible

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#1524]
### Versions
Vuetify 0.15.0

### What is expected ?
In prior versions it used to be possible to override the color of the expansion panel, e.g. with primary or accent colors, or a custom class using a background-color.

### What is actually happening ?
It is now only possible to have a white or dark grey background depending on whether light or dark mode is selected.

Overriding the color now requires overloading the `expansion-panel__container` class to negate the color set by the expansion-panel component, e.g.:
```
    .expansion-panel__container {
        background-color: rgba(0, 0, 0, 0) !important;
    }
```

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by shongololo** [comment]
Reopening and adding [codepen](https://codepen.io/shongololo/pen/Jyegob) link
