### ISSUE TITLE
[v0.15.0-beta.4] using the :to prop in v-breadcrumbs-item disables the element

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#1525]
### Steps to reproduce

Using the :to prop in a v-breadcrumbs-item causes the element to pickup the disabled class. :href appears to be working fine. Has :to been deprecated?

### Versions
v0.15.0-beta.4

### What is expected ?
The href should not be disabled.

### What is actually happening ?
The generated href has the disabled class applied.

### Reproduction Link

https://codepen.io/smitchell/pen/rwKPYr

**Comment by jacekkarczmarczyk** [comment]
router link is disabled if current page is same as the link, change the link to "/test" and it works

https://codepen.io/anon/pen/ZJmXEJ

**Comment by johnleider** [comment]
@jacekkarczmarczyk is correct.

**Comment by everhardt** [comment]
Not only if the current page is the same as the link, also if the current page starts with the link. So for example when you are on /people/peter and you link back to /people, its still greyed out.

**Comment by johnleider** [comment]
Breadcrumbs are a sore spot that I will be improving in the future. The current functionality is too basic as best, and terrible to work with at worse.

**Comment by stoked74** [comment]
@everhardt I worked around the issue you mentioned by setting the :exact prop to true.

**Comment by everhardt** [comment]
@stoked74, great, that works!
