### ISSUE TITLE
[Feature Request] IE support <== remove it !!!!!!!

### ISSUE THREAD

**Issue by h2atecnologia** [vuetifyjs/vuetify#15274]
### Problem to solve
How is It possible to remove the code supporting IE from Vuetify ?

### Proposed solution
What about turn the IE support an optional feature ?? Maybe turn it a compatibility layer ?

**Comment by KaelWD** [comment]
v3 doesn't support IE

**Comment by h2atecnologia** [comment]
Vuetify is a great, fantastic code. But, v3 is the future.
v2 is the present yet and for so many months or years. 
v2 not deserve this ? at least in the last release (2.7) ??
