### ISSUE TITLE
[Feature Request] DataTableHeader align type missing ' d-none' option

### ISSUE THREAD

**Issue by SlickNutter** [vuetifyjs/vuetify#15279]
### Problem to solve
Using DataTableHeader.align in Typescript would no longer show an error

### Proposed solution
Add ' d-none' value to union type in https://github.com/vuetifyjs/vuetify/blob/822de45f32914e54adc8f236eb760ceaea31f88b/packages/vuetify/types/index.d.ts#L285

**Comment by SlickNutter** [comment]
So in order not to display a column, the preferred way is to add the class ' d-none' to the header?

**Comment by SlickNutter** [comment]
@KaelWD 
> So in order not to display a column, the preferred way is to add the class ' d-none' to the header?

**Comment by KaelWD** [comment]
If you want to hide a column, remove its object from the headers array.
