### ISSUE TITLE
[Feature Request] Allow swiping the drawer across the entire screen

### ISSUE THREAD

**Issue by SegaraRai** [vuetifyjs/vuetify#15277]
### Problem to solve
Currently navigation drawer can only be slid at the edge of the screen, making it difficult to operate.

### Proposed solution
Allow swiping across the screen like the Discord and Twitter apps.

**Comment by KaelWD** [comment]
I had a go at implementing this but it's a bit more complicated, closing for now as it's not really worth the effort.
