### ISSUE TITLE
v-menu dropdown is not clickable

### ISSUE THREAD

**Issue by abnewstein** [vuetifyjs/vuetify#1527]
### Steps to reproduce
Create a v-menu with code from the main website
https://vuetifyjs.com/components/menus

### Versions

latest : https://unpkg.com/vuetify/dist/vuetify.min.js
### What is expected ?

The dropdown items should be clickable

### What is actually happening ?

tested in Firefox 52.3.0 and Edge latest.

### Reproduction Link

https://codepen.io/abnewstein/pen/prQOmE

**Comment by nekosaur** [comment]
Dropdown items are only clickable if they are set up as links in one of three way.

1) Adding `href` prop
2) Adding `to` prop
3) Adding `@click` handler

https://codepen.io/anon/pen/JyemOw

**Comment by abnewstein** [comment]
oops.   it was not mentioned in the doc.

Sorry about this.
