### ISSUE TITLE
[Feature Request] Use Vite with Vuetify 2.x

### ISSUE THREAD

**Issue by h2atecnologia** [vuetifyjs/vuetify#15275]
### Problem to solve
How can I use Vite instead Webpack in V2.x versions ?

### Proposed solution
Anyone had success about this ?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by h2atecnologia** [comment]
understood. tks

**Comment by kingyue737** [comment]
@h2atecnologia you can refer to my starter template of Vite + Vuetify2 https://github.com/kingyue737/vitify-admin
