### ISSUE TITLE
[Bug Report][3.0.0-beta.3] Tooltip remains visible while snackbar is displayed

### ISSUE THREAD

**Issue by Dillonmcewan** [vuetifyjs/vuetify#15276]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.37
**Browsers:** Chrome 100.0.4896.127
**OS:** Linux x86_64

### Steps to reproduce
1. Hover over the "Click Me" button in the linked Codepen
2. A tooltip should appear
3. Click the "Click Me" button
4. A snackbar should appear
5. Move mouse away from the button

### Expected Behavior
The tooltip should disappear once the mouse leaves the button.

### Actual Behavior
The tooltip remains visible until the snackbar is dismissed or times out.

### Reproduction Link
<a href="https://codepen.io/dmcewan51/pen/RwQqZQZ" target="_blank">https://codepen.io/dmcewan51/pen/RwQqZQZ</a>

**Comment by johnleider** [comment]
Another (maybe related?) bug I see is focusing `v-btn` with tab causes the tooltip to show and immediately hide.
