### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-select in v-dialog : space between v-select and menu after scrolling 

### ISSUE THREAD

**Issue by MrPalixir** [vuetifyjs/vuetify#15281]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.37
**Browsers:** Safari 15.5
**OS:** Mac OS 10.15.7

### Steps to reproduce
Scroll on a page with a v-dialog and after scrolling open v-dialog. Now, click on the v-select in the modal, a space appears between v-select and menu. This space is proportional to the space you scroll.

### Expected Behavior
No space between v-select and menu

### Actual Behavior
A space proportional to the scrolling distance from the begin of the page.

### Reproduction Link
<a href="https://codepen.io/mrpalixir/pen/poaqxZv" target="_blank">https://codepen.io/mrpalixir/pen/poaqxZv</a>

**Comment by KaelWD** [comment]
Fixed by 2468bcdff

**Comment by AhmadIshtiaq** [comment]
I'm also facing the same issue. 
when scroll on a page with a v-dialog and after scrolling open v-dialog. Now, click on the v-select in the modal, a space appears between v-select and menu. This space is proportional to the space you scroll.
If someone find any solution please share with us

**Comment by davidjnorth** [comment]
@AhmadIshtiaq same is happening for me. Did you manage to find a solution?

**Comment by AhmadIshtiaq** [comment]
Add
Scroll-strategy=none
in dialog

**Comment by davidjnorth** [comment]
@AhmadIshtiaq thank you! That seems to be working for me.

**Comment by aacassandra** [comment]
thankyou sir, work well
