### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-autocomplete Item slot not working

### ISSUE THREAD

**Issue by evans23** [vuetifyjs/vuetify#15280]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Last working version:** 2.6.6
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.61
**OS:** Windows 10

### Steps to reproduce
Define a custom item slot for v-autocomplete. Note that 'items' in the drop down follow the default template (i.e. show the title props in a list).

### Expected Behavior
Items in the drop down appear as defined in the slot.

### Actual Behavior
Items in the dropdown appear given the 'title' prop.

### Reproduction Link
<a href="https://codepen.io/evans23-the-selector/pen/NWyBVxN" target="_blank">https://codepen.io/evans23-the-selector/pen/NWyBVxN</a>

### Other comments
This is also broken in the documentation. https://next.vuetifyjs.com/en/components/autocompletes/#slots

**Comment by KaelWD** [comment]
9537787f2a1abd529ebb1cb0fdd449a70fcf4966
