### ISSUE TITLE
Vertical alignment of v-list-tile-content and v-list-tile-action in a dense v-list

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#1528]
### Steps to reproduce
Create a `v-list` with the `dense` property and add `v-list-tile` elements containing `v-list-tile-content` and `v-list-tile-action` elements. 

The vertical mis-alignment is caused by the height of `.list__tile__title` being too high (24px) after the `dense` property is applied, which causes its font-size to decrease from 24px to 13px. However, the element's height is not adjusted (still 24px).

### Versions
0.15.0-beta.4

### What is expected ?
The  `v-list-tile-content` and `v-list-tile-action` elements should line up vertically.
The height of `.list__tile__title` should be decreased to about 20px (maybe 18px?) after the `dense` property is applied.

### What is actually happening ?
The  `v-list-tile-content` elements are rendered too high in relation to the `v-list-tile-action` elements .

### Reproduction Link
This reproduction also illustrates how list item height adjustment might solve the issue:
[https://codepen.io/wernerm/pen/WEYabw](https://codepen.io/wernerm/pen/WEYabw)

**Comment by johnleider** [comment]
Fixed with beta.5 release.
