### ISSUE TITLE
Testless webpack-advanced template fails to run.

### ISSUE THREAD

**Issue by onimatrix81** [vuetifyjs/vuetify#1529]
### Steps to reproduce
vue init vuetifyjs/webpack-advanced testproject
(Answer NO for creating tests)
cd testproject
npm install
npm run dev

### Versions
This is on Windows 10

### What is expected ?
The template should run, as per instructions.

### What is actually happening ?
dev-server.js errors out with:
```
fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat '<project path>\test'
```
### Workaround
Manually creating empty /test directory seems to work.

### Excuse for the lack of reproduction Link
nekosaur says it's okay!

**Comment by nekosaur** [comment]
Opened https://github.com/vuetifyjs/webpack-advanced/issues/10
