### ISSUE TITLE
[Feature Request] v-select dropdown is not closing on clicking outside on safari browser

### ISSUE THREAD

**Issue by amjed-ciitizen** [vuetifyjs/vuetify#15290]
### Problem to solve
Dropdowns are not close on clicking outside on safari browser. While it is working fine on google browser.

### Proposed solution
It should close the v-select dropdown on clicking outside.

**Comment by KaelWD** [comment]
This is not a valid feature request. If you are trying to submit a bug report please use the bug report template and supply a valid reproduction link with more details about the bug.  

For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
