### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-navigation-drawer -- location = "top" -- Invalid prop warning

### ISSUE THREAD

**Issue by jamesdruhan** [vuetifyjs/vuetify#15305]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.36
**Browsers:** Edge 102.0.1245.39
**OS:** Windows 10

### Steps to reproduce
Set v-navigation-drawer location to **top**. You will see a warning in the console. All other location options work fine without warning. The location setting of top actually works for the element (even though the warning appears).

```js
<v-navigation-drawer v-model="drawer" location="top" temporary>
  <v-list>
    <v-list-item link>
      <v-list-item-title>Item #1</v-list-item-title>
    </v-list-item>
  </v-list>
</v-navigation-drawer>
```

### Expected Behavior
No console warning should occur.

### Actual Behavior
Console reports: 
```
[Vue warn]: Invalid prop: custom validator check failed for prop "location". 
  at <VNavigationDrawer modelValue=false onUpdate:modelValue=fn location="top"  ... > 
  at <AppHeader> 
  at <MainView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView key=1 > 
  at <VApp> 
  at <VThemeProvider theme="appThemeLight" > 
  at <App>
```

### Reproduction Link
<a href="https://codepen.io/jamesdruhan/pen/poaGXeg?editors=101" target="_blank">https://codepen.io/jamesdruhan/pen/poaGXeg?editors=101</a>

**Comment by johnleider** [comment]
The prop validation stems from **position** from the touch composable: <https://github.com/vuetifyjs/vuetify/blob/951940c81c948a413905a4df3aca0202eb3dccad/packages/vuetify/src/components/VNavigationDrawer/touch.ts#L15>

I can't remember our reasoning for not implementing top. @vuetifyjs/core-team

**Comment by KaelWD** [comment]
Top would conflict with the notification drawer on mobile. We could make it work but I wouldn't recommend using it.

**Comment by johnleider** [comment]
This is not something we plan to implement at this time. This is possible using the `v-layout` system `v-layout-item`.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
