### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-btn disappears when add to property

### ISSUE THREAD

**Issue by jamesdruhan** [vuetifyjs/vuetify#15309]
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.36
**Browsers:** Edge 102.0.1245.39
**OS:** Windows 10

### Steps to reproduce
Add a **to** property to a v-btn. The button part of the link will not generate. Note below there is nothing generated between the **a** element (blank).
```
<!-- This --> 
<v-btn :to="{ name : 'pageHome' }" text>Home</v-btn>

<!-- Renders This--> 
<a class="v-btn v-btn--flat v-theme--appThemeLight v-btn--density-default v-btn--size-default v-btn--variant-text" href="/"></a>
```

### Expected Behavior
The button should generate between the **a** element.

```
<!-- This --> 
<v-btn :to="{ name : 'pageHome' }" text>Home</v-btn>

<!-- Should Render This--> 
<a class="v-btn v-btn--flat v-theme--appThemeLight v-btn--density-default v-btn--size-default v-btn--variant-text" href="/">
<button type="button" class="v-btn v-btn--flat v-theme--appThemeLight v-btn--density-default v-btn--size-default v-btn--variant-text" text=""><div class="v-btn__overlay"></div><div class="v-btn__underlay"></div><!----><div class="v-btn__content" data-no-activator="">Home</div><!----></button>
</a>
```

### Actual Behavior
Nothing generates between the **a** element.
```
<!-- This --> 
<v-btn :to="{ name : 'pageHome' }" text>Home</v-btn>

<!-- Renders This--> 
<a class="v-btn v-btn--flat v-theme--appThemeLight v-btn--density-default v-btn--size-default v-btn--variant-text" href="/">
</a>
```

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/mdXobyW" target="_blank">https://codepen.io/SuperCuber2/pen/mdXobyW</a>

**Comment by KaelWD** [comment]
- You don't have vue-router installed
- `text` is [HTMLAnchorElement.text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement#htmlanchorelement.text) which replaces all the inner content
