### ISSUE TITLE
[Feature Request] disabled a11y improvement

### ISSUE THREAD

**Issue by depperm** [vuetifyjs/vuetify#15306]
### Problem to solve
When a button uses `:disabled="someProp"` this doesn't add aria-disabled which is useful for screen readers (see https://youtu.be/bUeqVNX3oLE)

### Proposed solution
make it so disabled add aria-disabled as well

**Comment by KaelWD** [comment]
Screen readers already recognise `disabled`, the problem is only with screen readers that rely on tab focus. Adding `aria-disabled` as well wouldn't change anything.
