### ISSUE TITLE
[Bug Report][2.6.6] v-textarea is not high enough to display the text.

### ISSUE THREAD

**Issue by Aruelius** [vuetifyjs/vuetify#15319]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
open dialog, then when textarea get content, it can't show them all.

### Expected Behavior
display all the content.
![image](https://user-images.githubusercontent.com/25380989/174565468-6b2c6b05-5fad-468f-b05d-9129da0d5497.png)

### Actual Behavior
the textarea tag is not tall enough to display the content.
![image](https://user-images.githubusercontent.com/25380989/174564712-487e6b09-beea-4600-b623-7b732f48df23.png)

### Reproduction Link
<a href="https://codepen.io/aruelius/pen/NWyVKBY" target="_blank">https://codepen.io/aruelius/pen/NWyVKBY</a>

**Comment by KaelWD** [comment]
Works for me, why are you trying to display 200KB of text in a tiny textarea anyway?

**Comment by Aruelius** [comment]
> Works for me, why are you trying to display 200KB of text in a tiny textarea anyway?

In my case, this problem can be reproduced with only 5KB of text.

I reopen my reproduction link, and it can be reproduction.

![GIF](https://user-images.githubusercontent.com/25380989/174610665-f1ca99fe-cbdd-4f84-9d99-89e8a7aa6528.gif)

Thanks for your reply.

**Comment by websitevirtuoso** [comment]
I have the same problem on vuetify 3.beta.5
Going to do repo to show error

**Comment by KaelWD** [comment]
I'm guessing this has something to do with your locale settings. I haven't seen anyone else complaining of this, feel free to open a PR if you found a fix for it.
