### ISSUE TITLE
[Bug Report][2.6.6] Screenreader stuck in Select component

### ISSUE THREAD

**Issue by dropsh0t** [vuetifyjs/vuetify#15314]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.11
**Browsers:** Firefox 101.0
**OS:** Mac OS 10.15

### Steps to reproduce
Navigate with a screenreader (VoiceOver on macOS) to a select component.
Use the keyboard arrows to navigate through the option and use the screenreader controls to select an option. 

### Expected Behavior
The chosen option is selected and VoiceOver can navigate to the next element

### Actual Behavior
VoiceOver is stuck on the select element and can't navigate out of it. VoiceOver lands on the input element and can only navigate within the current select component. 

### Reproduction Link
<a href="https://codepen.io/dropsh0t/pen/WNMmLZp" target="_blank">https://codepen.io/dropsh0t/pen/WNMmLZp</a>

**Comment by lioneaglesolutions** [comment]
I tried this using VoiceOver on MacOS and it seems to be resolved in V3 (tested on https://vuetifyjs.com/en/components/selects/).
