### ISSUE TITLE
[Bug Report][2.6.6] Pre made Layout Link URL is broken from vuetify website

### ISSUE THREAD

**Issue by amouratoglou** [vuetifyjs/vuetify#15321]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.7.0-beta.3
**Browsers:** Chrome 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
is not about vuetify but about the documentation and links to some pre-made layouts which are not working. thanks 

https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/layouts/layouts/demos/google-keep.vue
open any of the premade layouts none of the links work:
https://vuetify.cn/en/getting-started/pre-made-layouts/

https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/layouts/layouts/demos/google-keep.vue

### Expected Behavior
link to repo with templates

### Actual Behavior
github url is broken

### Reproduction Link
<a href="https://github.com/nolink" target="_blank">https://github.com/nolink</a>

### Other comments
thanks guys you rock.

**Comment by MajesticPotatoe** [comment]
duplicate #13699
