### ISSUE TITLE
[Bug Report][2.6.6] The v-calendar component

### ISSUE THREAD

**Issue by kot6egemot** [vuetifyjs/vuetify#15326]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Move the mouse over the event in the calendar **month view** for last day of event. See that date passed in function as event.star but not date of day.

Move the mouse lower over the event for last day of event and see corrent date of calendar day.

### Expected Behavior
date of the day over which the mouse is located.

### Actual Behavior
start date of the event in the calendar if mouse over the event.

### Reproduction Link
<a href="https://codepen.io/kot6egemot/pen/jOZoxEE" target="_blank">https://codepen.io/kot6egemot/pen/jOZoxEE</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
