### ISSUE TITLE
[Bug Report][3.0.0-beta.4] Diff height size of elements

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#15329]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Vue Version:** 3.2.36
**Browsers:** Chrome 102.0.5005.115
**OS:** Linux x86_64

### Steps to reproduce
See codepen example. 

### Expected Behavior
Expect the same height 

### Actual Behavior
Diff height 

### Reproduction Link
<a href="https://codepen.io/websitevirtuoso/pen/ExQOBqM?editors=1111" target="_blank">https://codepen.io/websitevirtuoso/pen/ExQOBqM?editors=1111</a>

**Comment by Nick-I-A** [comment]
This is due to the size of your chip.
https://ibb.co/xSRqmfJ

You can change the height to 20 pixels or use the code below to get a smaller chip
```
<v-chip size="x-small">x-small chip</v-chip>
```

**Comment by websitevirtuoso** [comment]
Yes correct. I have next use case
If somebody would like to change input variant via vuetify config they will have the same issue. It is not critical but happens only with underlined variant

**Comment by KaelWD** [comment]
You can also increase the chip density in the global config:
```js
createVuetify({
  defaults: {
    VCombobox: {
      VChip: {
        density: 'comfortable'
      }
    }
  }
})
```
