### ISSUE TITLE
[Bug Report][2.6.6] single-expand doesn't work when not using click arrow

### ISSUE THREAD

**Issue by NeonCowboy** [vuetifyjs/vuetify#15337]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. click row to expand rows
2. click another row will expand a another, but didn't close the previous one.
3. using the arrow button on the right, no issue.

### Expected Behavior
single-expand work well when not using the expand button or on the condition of show-expand=false

### Actual Behavior
single-expand doesn't work when not using the expand button.

### Reproduction Link
<a href="https://codepen.io/NeonCowboy/pen/BaYXZPY" target="_blank">https://codepen.io/NeonCowboy/pen/BaYXZPY</a>

**Comment by KaelWD** [comment]
```js
this.expanded = [slotData.item]
```
