### ISSUE TITLE
[Bug Report][3.0.0-beta.4] VCard Actions buttons don't have colours

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#15330]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Last working version:** 3.0.0-beta.3
**Vue Version:** 3.2.36
**Browsers:** Chrome 102.0.5005.115
**OS:** Linux x86_64

### Steps to reproduce
In vuetify 3 I could change the primary color for v-btn via config. But in version vuetify beta4 it stopped working

### Expected Behavior
Button expected to be colour

### Actual Behavior
Button doesn't have colour

### Reproduction Link
<a href="https://codepen.io/websitevirtuoso/pen/gOvNayj" target="_blank">https://codepen.io/websitevirtuoso/pen/gOvNayj</a>

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/15311
