### ISSUE TITLE
[Bug Report][3.0.0-beta.4] Using vDialog in a child component, the keydown event does not work

### ISSUE THREAD

**Issue by guxuerui** [vuetifyjs/vuetify#15331]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Vue Version:** 3.2.31
**Browsers:** chome 102.0.5005.115
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on the button to open the dialog, you can see the dialog opend
2. press the button key 'ESC'
3. Click the button 'open dialog', then the dialog can't open

### Expected Behavior
vDialog can be shown or hidden normally

### Actual Behavior
Not normal

### Reproduction Link
<a href="https://codesandbox.io/s/elated-chihiro-ckz8q8?file=/src/components/child.vue" target="_blank">https://codesandbox.io/s/elated-chihiro-ckz8q8?file=/src/components/HelloWorld.vue</a>

### Other comments
After clicking the ESC key once, the dialog can no longer be displayed

**Comment by KaelWD** [comment]
It uses a window listener to close, there is no keydown emitted. You can watch `dialog1` to see when it closes, which will handle click outside and the back button properly too.

**Comment by guxuerui** [comment]
ok,  thank you!  I will try again.
