### ISSUE TITLE
[Feature Request] add tree -select component

### ISSUE THREAD

**Issue by index-xiao** [vuetifyjs/vuetify#15334]
### Problem to solve
Sometimes the selected data may be in tree structure

### Proposed solution
Add a tree drop-down option on the basis of the v-select component,It supports single selection, multiple selection and cascade selection

**Comment by websitevirtuoso** [comment]
What about this one?
https://vuetifyjs.com/en/components/treeview/#item-disabled
You always can modify it

**Comment by KaelWD** [comment]
Duplicate of #3049
