### ISSUE TITLE
Autocomplete v-select with initial value is blank until clicked on (0.15.0-beta.4)

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#1533]
### Steps to reproduce
 - Create a `v-select` with `autocomplete` and an initial value on the model.
 - Note that the initial value isn't displayed
 - Click on the select, then away again to close it
 - Initial value is now shown

### Versions
Vuetify 0.15.0-beta.4

### What is expected ?
The initial value of the model should be displayed without any user input

### What is actually happening ?
The `select` is blank

### Reproduction Link
https://codepen.io/anon/pen/ayPzZm

**Comment by KaelWD** [comment]
If the value is set after the fact (in `mounted()` or from a button press) it works fine, the problem is only on initial render.  
https://codepen.io/anon/pen/rzoaEm

**Comment by stoked74** [comment]
I'm experiencing the same thing in 0.15.0-beta.4. This is a regression from 14.

**Comment by KaelWD** [comment]
After having a poke around with vue-devtools I've noticed that's it's caused by `lazySearch` not being updated. @johnleider said in discord "It just needs a mounted call to fire off this.resetSearch I think", but there's no function with that name anywhere in the repo so IDK what he meant by that.

**Comment by johnleider** [comment]
This was fixed with https://github.com/vuetifyjs/vuetify/commit/144c71dcc75387943cc81ec6f658a7386d99fdbe#diff-6657c349c82598f95633b7ccd25c08c9R270
