### ISSUE TITLE
[Bug Report][2.6.4] RoundTo value produce incorrect deplacement

### ISSUE THREAD

**Issue by LucasGre17** [vuetifyjs/vuetify#15338]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
If you have an event at 9am with a 45 minute rounding. 

Normally it is you move up you should get an event from 8:15 to 9:00 but you get an event from 8:45 to 9:30.

### Expected Behavior
The first move should produce a 45-minute jump.

### Actual Behavior
The first move produces a 15 minute jump.

### Reproduction Link
<a href="https://codepen.io/LucasG17/pen/LYQwLep" target="_blank">https://codepen.io/LucasG17/pen/LYQwLep</a>

**Comment by KaelWD** [comment]
How is this a vuetify bug? You're controlling the rounding yourself.
