### ISSUE TITLE
[Bug Report][2.6.6] When I click the first v-tab, the slider does not go to the first v-tab

### ISSUE THREAD

**Issue by daniel-lij** [vuetifyjs/vuetify#15348]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.7.0-beta.8
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
https://codepen.io/daniel-lij/pen/RwMwayv

### Expected Behavior
I want to click the first v-tab and slide it onto the first v-tab, then click the first v-tab and expand the v-menu

### Actual Behavior
When you click the first v-tab, the slider does not slide to the first v-tab But the v-menu expanded

### Reproduction Link
<a href="https://codepen.io/daniel-lij/pen/RwMwayv" target="_blank">https://codepen.io/daniel-lij/pen/RwMwayv</a>

**Comment by KaelWD** [comment]
The activator element stops click event propagation, put the tab inside the slot instead of a span.
