### ISSUE TITLE
<v-toolbar-item> can't be parsed

### ISSUE THREAD

**Issue by wi-cuckoo** [vuetifyjs/vuetify#1534]
### Versions
0.14.11

### What is expected ?
update the document

### What is actually happening ?
Here is the code snippet
```html
       <v-toolbar-items>
          <v-toolbar-item ripple nuxt>Link</v-toolbar-item>
          <v-toolbar-item ripple nuxt>Link</v-toolbar-item>
        </v-toolbar-items>
```
But I find the <v-toolbar-item> element is not be parsed by broswer. 
just like `<div class="toolbar__items"><v-toolbar-item ripple="" nuxt="">Link</v-toolbar-item><v-toolbar-item ripple="" nuxt="">Link</v-toolbar-item></div>`
I don't know why. The doc can't give answer.

**Comment by jacekkarczmarczyk** [comment]
There is no such component as `<v-toolbar-item>`

**Comment by wi-cuckoo** [comment]
@jacekkarczmarczyk  Yeah. I have such doubt by seeing the source code. But the problem is why the [document](http://vuetify.com/components/toolbars) have the example. No one to update the document?

**Comment by jacekkarczmarczyk** [comment]
You can check the documentation for 0.15 beta here https://dev.vuetifyjs.com/components/toolbars and report the issue in docs repo if necessary https://github.com/vuetifyjs/docs/issues

**Comment by wi-cuckoo** [comment]
@jacekkarczmarczyk  Sorry for disturb. I just get into the old website. It have the different content. I can't find it now.
