### ISSUE TITLE
[Bug Report][3.0.0-beta.4] Dark brackground on open sidebar (Smartphone/Android 12/Google Chrome)

### ISSUE THREAD

**Issue by TheAwesomeKoeniq** [vuetifyjs/vuetify#15343]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Last working version:** 3.0.0-beta.4
**Vue Version:** 3.2.25
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Quickly open and close the sidebar several times.

Maybe it's because of the google chrome url bar because on my smartphone it hides when scrolling down and shows when scrolling up? I'm not sure, but sometimes it happens

### Expected Behavior
Transparency

### Actual Behavior
No transparency

### Reproduction Link
<a href="https://github.com/" target="_blank">https://github.com/</a>

### Other comments
I used the ViteJS version and updated it to BETA.4 manually as it didn't happen automatically. 
I'm using ViteJS, for that reason i don't know if it happens with Codepen too, so i didn't include a link... Maybe later i could upload an example to Github

Screenshots:
- https://ibb.co/wzqZv29
- https://ibb.co/4f8FC9m

**Comment by Nick-I-A** [comment]
Small update to this problem:
I changed a few little things like removed the hover effect for containers (shadow 2 to shadow 6 on hover) and now i don't have this bug anymore... I'll check the commits later and maybe i can find the problem

**Comment by KaelWD** [comment]
Sounds like it could be a browser bug then.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
