### ISSUE TITLE
[Bug Report][3.0.0-beta.4] V-menu acting weird when RTL active

### ISSUE THREAD

**Issue by avgkudey** [vuetifyjs/vuetify#15353]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Vue Version:** 3.2.36
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
- add a v-menu component
- set Vuetify locale to RTL-enabled local

### Expected Behavior
Contents should be show shown next to the menu button.

### Actual Behavior
Contents render the far end of the corner. 

### Reproduction Link
<a href="https://codepen.io/uzvoolaiyaxe-logicstreak-com/pen/XWEWBXZ" target="_blank">https://codepen.io/uzvoolaiyaxe-logicstreak-com/pen/XWEWBXZ</a>

### Other comments
it works correctly after the second time click the menu button.

**Comment by greeto** [comment]
I got exactly this bug as well.
Still not fixed.
