### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Autocomplete not working where backed by dynamic api resource

### ISSUE THREAD

**Issue by billerby** [vuetifyjs/vuetify#15368]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Last working version:** 2.6.7
**Vue Version:** 3.2.13
**Browsers:** Firefox 101.0
**OS:** Linux x86_64

### Steps to reproduce
Trying out the example page for autocomplete and none of the dynamic-api backed ones seems to do any network calls at all. When trying out locally it seems it does not enter the watch directive. The link is a codepen copy of the "Search for public APIs"

### Expected Behavior
A list of matching public apis should be presented like the way in the v2 example page.

### Actual Behavior
Nothing is returned.

### Reproduction Link
<a href="https://codepen.io/billerby/pen/gOebVQx?editors=101" target="_blank">https://codepen.io/billerby/pen/gOebVQx?editors=101</a>

**Comment by billerby** [comment]
Seems its a documentation issue and that the examples are implemented in line with the documentation: https://github.com/vuetifyjs/vuetify/issues/14982

**Comment by johnleider** [comment]
resolved by c7aa18048
