### ISSUE TITLE
[Bug Report][3.0.0-beta.5] VBreadcrumbsItem is missing `text` property. Uses `title` instead.

### ISSUE THREAD

**Issue by mattbenimble** [vuetifyjs/vuetify#15371]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Last working version:** 3.0.0-beta.4
**Vue Version:** 3.2.25
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Install Vuetify in the default configuration
2. Add a `v-breadcrumbs` component bound to an `items` property
3. in the `items` array define breadcrumbs:
```javascript
[
  {
    text: "Dashboard",
    disabled: false,
    to: "breadcrumbs_dashboard",
  },
  {
    text: "Link 2",
    disabled: true,
  },
]
```
4. Disabled Items do not render.  the `li` has a `text="Link 2"` value but it does not render the element properly.

### Expected Behavior
a disabled breadcrumb would fallback to the text value irrespective of the `href` or `to` property

### Actual Behavior
a disabled breadcrumb without  a   `href` or `to` property does not render the `text` property but will render the `title` property

### Reproduction Link
<a href="https://codesandbox.io/s/vue3-vuetify-forked-3nwuoc" target="_blank">https://codesandbox.io/s/vue3-vuetify-forked-3nwuoc</a>

**Comment by nekosaur** [comment]
The correct property to use is `title`.

**Comment by izure1** [comment]
I have the same issue. I'm using nuxt3, and it looks successful in server rendering, but there seems to be a problem with client rendering afterwards.

**Comment by mattbenimble** [comment]
> The correct property to use is `title`.

@nekosaur im not seeing that in the documentation: 
https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/examples/v-breadcrumbs/prop-divider.vue 

Is there somewhere else I should be looking for that?

**Comment by MajesticPotatoe** [comment]
> Is there somewhere else I should be looking for that?

Docs updates are lagging ATM. Pretty much all 'text' props have been changed to title in v3
