### ISSUE TITLE
v-btn turns darker the more it is clicked. (vuetify + vue-router)

### ISSUE THREAD

**Issue by Sys0MKNR** [vuetifyjs/vuetify#1537]
### Steps to reproduce
* Create a  v-btn with a bound "to" attribute pointing to a path.
* The vue-router module is needed. 
* Then click the button really fast and make a circular motion while clicking. 

### Versions
* vue@2.4.2
* vuetify@0.15.0-beta.4
* vue-router@2.7.0
* tested with Chrome 60.0.3112.113 beta (64-Bit), Opera 47.0.2631.71 (PGO) and Opera Neon 1.0.2531.0. 

### What is expected ?
The button should only get a bit darker the first click but not get darker than that. 

### What is actually happening ?
The button continues to get darker. 
It seems like it adds ripple__container but does not remove them again. 

### Reproduction Link
https://codepen.io/anon/pen/QMzjBV

**Comment by smares** [comment]
I cannot reproduce your issue with Chrome 60.0.3112.113 (non-beta). If I click the button, I see the ripple, but it disappears again and the button is back to its normal color.
