### ISSUE TITLE
[Feature Request] Add missing `mobile-breakpoint` prop in navigation drawer like v2

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15381]
### Problem to solve
Same as v2

### Proposed solution
Same as v2

**Comment by KaelWD** [comment]
Everything now uses a globally defined breakpoint in `createVuetify({ display: { mobileBreakpoint } })`, is there a need for instance-specific breakpoints too?

**Comment by jd-solanki** [comment]
Hi kael,

Thanks for the response. I am a theme vendor at vuetify store and in our template, we are showing navigation drawer regardlessof global mobileBreakpoint due to UI & UX.

You can experience need & know why it is better UX on this page: [Materio admin](https://demos.themeselection.com/materio-vuetify-vuejs-admin-template/demo-1/apps/chat)

`980px` is below mobileBreakpoint I guess and that's why we have temporary nav drawer for template navigation but chat navigation drawer which contains chats is still visible.

I hope I explained correctly.

Awaiting your response.

**Comment by johnleider** [comment]
Isn't this solved by the **permanent** prop?

**Comment by jd-solanki** [comment]
Maybe I can bind dynamic value based on breakpoint to `permanent` prop. I will surely try it out next morning.

BTW, I am already using a `temporary` prop dynamically based on the breakpoint. IG using either `permanent` or `temporary` is the same but still, I will give it a try.

Thanks.

**Comment by jd-solanki** [comment]
> Isn't this solved by the **permanent** prop?

`Permanent` prop didn't help: https://discord.com/channels/340160225338195969/660898563139567625/998289064757313670

**Comment by jd-solanki** [comment]
What is the meaning of "Pending Review"?

**Comment by johnleider** [comment]
It means we've acknowledged there is something here, but it needs further review.

**Comment by ampminfo** [comment]
Ok I did not bind the function to the right this us vuejs

    ajaxParams:  function(){
         return {guid: this.drawer2GUID}
      }.bind(this),

**Comment by ampminfo** [comment]
Thank a lot
