### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-text-field one way binding does not work using @Input

### ISSUE THREAD

**Issue by mcheung610** [vuetifyjs/vuetify#15391]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add 1 to the v-text-field input field at the end
2. Observe the console log 

### Expected Behavior
expect the event.target.value to be 1001

### Actual Behavior
event.target.value is 100

### Reproduction Link
<a href="https://codepen.io/mcheung610/pen/bGvELKv?editors=1010" target="_blank">https://codepen.io/mcheung610/pen/bGvELKv?editors=1010</a>

**Comment by KaelWD** [comment]
Vue 3's v-model is `model-value` and `@update:model-value`
