### ISSUE TITLE
[Bug Report][3.0.0-beta.5] You cannot make `icon btn` `rounded` using rounded prop.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15397]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
Add rounded prop to `<v-btn icon></v-btn>` component.

### Expected Behavior
The button's border-radius should be 4px.

### Actual Behavior
Nothing is happening.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/qBobQBa?editors=101" target="_blank">https://codepen.io/Alokdev/pen/qBobQBa?editors=101</a>

**Comment by KaelWD** [comment]
![Screenshot_20220707_165608](https://user-images.githubusercontent.com/16421948/177710935-528721b7-6244-4729-9dba-e0e67f54cb1b.png)
