### ISSUE TITLE
[Feature Request] support referrerpolicy html tag on v-img

### ISSUE THREAD

**Issue by lfgtavora** [vuetifyjs/vuetify#15396]
### Problem to solve
i cant use v-img with referrerpolicy="no-referrer", cause some issues when using google users avatars

### Proposed solution
make v-img support referrerpolicy like normal html <img> tag

**Comment by kieuminhcanh** [comment]
+1

**Comment by arepp23** [comment]
+1 . To add context [this is necessary to load a Google Auth user's image from url](https://stackoverflow.com/questions/40570117/http403-forbidden-error-when-trying-to-load-img-src-with-google-profile-pic)

**Comment by sefgit** [comment]
Please add similar feature for <v-list-item prepend-avatar

`
<v-list-item
          referrerpolicy="no-referrer"
          :title="user_name"
          :prepend-icon="hasIcon"
          :prepend-avatar="hasAvatar"
          nav
        >
`
