### ISSUE TITLE
[request] v-dialog top position option

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#1539]
On desktop I don't like how the v-dialog is centered perfectly vertical.  I want dialogs to be centered on mobile, but have top around 10-20vh for desktop.  Add an option.  I've been  using my own homegrown dialog because of that, but still use v-dialog in a few cases.

Add this for now and that's what I want.

div.dialog__content {
  align-items: flex-start;
  margin-top: 20vh;
}

**Comment by johnleider** [comment]
This would ultimately be something you would need to (as you already have displayed) handle yourself.

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by throrin19** [comment]
It's not possible to add option to select alignment option in `dialog__content` class with dialog option ? At this time it's not compatible and I don't make that directly in global CSS but in selected component
