### ISSUE TITLE
[Bug Report][2.3.18] DataTable attributes not allow nesting

### ISSUE THREAD

**Issue by Polletz** [vuetifyjs/vuetify#15399]
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Firefox 102.0
**OS:** Windows 10

### Steps to reproduce
This is just an example of two data-tables nested one into another.

### Expected Behavior
Every data-table has its own attributes independent from the ones of the externel one.

### Actual Behavior
The nested table takes some attributes from the external one, for example "items-per-page" ignoring its own value.

### Reproduction Link
<a href="https://jsfiddle.net/exuca6h8/2/" target="_blank">https://jsfiddle.net/exuca6h8/2/</a>

**Comment by KaelWD** [comment]
https://stackoverflow.com/help/minimal-reproducible-example
