### ISSUE TITLE
[Bug Report][3.0.0-beta.4] V-Dialog Default Slot Missized

### ISSUE THREAD

**Issue by evans23** [vuetifyjs/vuetify#15403]
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Last working version:** 2.6.7
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.114
**OS:** Linux

### Steps to reproduce
Create a v-dialog with a default slot and max-width set. Open the v-dialog. Notice that the item does not expand to the max-width unless the item's contents naturally fill out the space.

### Expected Behavior
The default slot defaults to the max-width or the width of the screen, whichever is smaller.

### Actual Behavior
The default slot defaults to the size of the content.

### Reproduction Link
Broken functionality (Vuetify 3.0): <a href="https://codepen.io/evans23-the-selector/pen/rNdxXOm" target="_blank">https://codepen.io/evans23-the-selector/pen/rNdxXOm</a>

Expected functionality (Vuetify 2.6): <a href="https://codepen.io/evans23-the-selector/pen/qBobeaK" target="_blank">https://codepen.io/evans23-the-selector/pen/qBobeaK</a>

### Other comments
I've also noticed a similar behavior on v-timeline-items not filling out their allocated space by default. I can create a second bug if this is found to be valid.

**Comment by websitevirtuoso** [comment]
Have the same behavior with normal form and data inside the v-dialog.
To fix it I have to set width to body via css

**Comment by KaelWD** [comment]
Related: #14835 #6919
