### ISSUE TITLE
[Bug Report][3.0.0-beta.5] VTextField does not apply style for filled and rounded props

### ISSUE THREAD

**Issue by rbuzzibarrios** [vuetifyjs/vuetify#15407]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Last working version:** 2.6.7
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-text-field with filled and rounded props. Notice that the text field does not apply classes v-text-field--filled and v-text-field--rounded

### Expected Behavior
The v-text-field component transforms its style to pill(rounded) format.

### Actual Behavior
The v-text-field component keep current style.

### Reproduction Link
<a href="https://codesandbox.io/s/vtextfield-filled-rounded-props-roygw5" target="_blank">https://codesandbox.io/s/vtextfield-filled-rounded-props-roygw5</a>

**Comment by MajesticPotatoe** [comment]
filled and rounded props don't exist for v3 inputs, filled has been migrated to the variant prop.
