### ISSUE TITLE
[Documentation] @vitejs/create-app is deprecated

### ISSUE THREAD

**Issue by TheAwesomeKoeniq** [vuetifyjs/vuetify#15408]
### Environment

**Browsers:** /
**OS:** All

### Steps to reproduce
Install ViteJS with the current documentation

### Expected Behavior
No warnings

### Actual Behavior
Warning: "@vitejs/create-app is deprecated, use npm init vite instead"

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/getting-started/installation/" target="_blank">https://next.vuetifyjs.com/en/getting-started/installation/</a>

### Other comments
The following documentation is obsolete:
```shell
# npm 6.x
npm init @vitejs/app my-vuetify-app --template vue

# npm 7+, extra double-dash is needed:
npm init @vitejs/app my-vuetify-app -- --template vue

# yarn
yarn create @vitejs/app my-vuetify-app --template vue
```
and should be replaced with:
```shell
# npm 6.x
npm create vite@latest my-vue-app --template vue

# npm 7+, extra double-dash is needed:
npm create vite@latest my-vue-app -- --template vue

# yarn
yarn create vite my-vue-app --template vue

# pnpm
pnpm create vite my-vue-app -- --template vue
```

**Comment by ElijahKotyluk** [comment]
[32365b2](https://github.com/vuetifyjs/vuetify/commit/32365b2bf5e625a2adf0f3010ca62057118107a2)

Closing as completed.
