### ISSUE TITLE
[Bug Report][3.0.0-beta.5] `v-tabs` does not work properly in `direction:rtl`

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15400]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
Set `direction:rtl` in style.

### Expected Behavior
It should work and you can navigate to the hidden tab using arrows.

### Actual Behavior
Hidden tabs could not be accessible.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/MWVKRMQ?editors=101" target="_blank">https://codepen.io/Alokdev/pen/MWVKRMQ?editors=101</a>

**Comment by KaelWD** [comment]
You need to configure RTL, it isn't read from the DOM: https://codepen.io/kaelwd/pen/YzaqNXV?editors=1010
That's still kinda broken though.

**Comment by alokVishu** [comment]
Thanks, @KaelWD,

It works.

**Comment by KaelWD** [comment]
> That's still kinda broken though
