### ISSUE TITLE
[Request] CDN for Vuetifiy using [CDNJS ](https://cdnjs.com/) 

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#1540]
I noticed Codepen using https://unpkg.com/ won't work at my end even vue.js. I was wondering why I check already my browser popup blocker and its none. 

Other CDN sources on Vuetify might help...

Thanks..

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/vuetify. It's the fastest CDN out there.

**Comment by johnleider** [comment]
@MartinKolarik 's solution should be helpful.
