### ISSUE TITLE
[Bug Report][2.6.3] Picking a month/year in date picker fails when passing [null, null]

### ISSUE THREAD

**Issue by Prebiusta** [vuetifyjs/vuetify#15410]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
This function in **https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDatePicker/VDatePicker.ts** does not validate if dates passed to multivalued (range) date picker are nulls. Thus .sbustr will throw errors when passing [null] or [null, null]

Is that by purpose, so people will avoid passing nulls, or just bug? In our use case, it is necessary, thus we had to implement our own logic wrapper, to pass empty array instead, etc.

```
    selectedMonths (): string | string[] | undefined {
      if (!this.value || this.type === 'month') {
        return this.value
      } else if (this.isMultiple) {
        return this.multipleValue.map(val => val.substr(0, 7))
      } else {
        return (this.value as string).substr(0, 7)
      }
    },
```

### Expected Behavior
Array with nulls [null, null] should be considered as empty array

### Actual Behavior
There is an error at this line, when execution substring function 

```
return this.multipleValue.map(val => val.substr(0, 7))
```

### Reproduction Link
<a href="https://codepen.io/prebiusta/pen/MWVymwV" target="_blank">https://codepen.io/prebiusta/pen/MWVymwV</a>

**Comment by lioneaglesolutions** [comment]
Closing as this has a workaround in V2 and will likely be address in V3 date picker
