### ISSUE TITLE
[Bug Report][3.0.0-beta.5] V-text-area incorrect top padding

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#15411]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Use text area fill with text. see the problem

### Expected Behavior
Padding top should be diff for textarea. Not like on text-input

### Actual Behavior
It has the same padding as text-input

### Reproduction Link
![image](https://user-images.githubusercontent.com/5112918/178064593-dc89c65f-e718-4879-a724-e7625adbc6a9.png)

WIth V-textarea - variant: 'underlined'
it has a bit another bug, when copy paste a text into textarea

**Comment by KaelWD** [comment]
mask-image also isn't being prefixed correctly
