### ISSUE TITLE
[Feature Request] [v-calendar] - Hiding intervals

### ISSUE THREAD

**Issue by LucasGre17** [vuetifyjs/vuetify#15417]
### Problem to solve
Hello,
Currently on the v-calendar we can constrain the display time of the beginning and the end of a day (first-interval - interval-count).
But I want to hide an interval between these two values.

Example : I have events from 8am to 10am, then from 2pm to 4pm. To make the calendar more readable and less big, I would like to be able to hide the intervals from 10am to 2pm.

### Proposed solution
My solution is to put a boolean variable in each interval to enable or disable the visibility of each interval.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
