### ISSUE TITLE
[Feature Request] Support table sorting for more languages

### ISSUE THREAD

**Issue by xfq** [vuetifyjs/vuetify#15416]
### Problem to solve
Currently, there is no way to sort a table for languages other than English.

### Proposed solution
Support table sorting for more languages.

There are some functions available in JavaScript for sorting international strings, such as [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/compare) and [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare).

See also https://www.w3.org/TR/charmod/#sec-CollationUnits

**Comment by KaelWD** [comment]
- there is a `customSort` prop you can pass your own sorting function to
- the default sorting function already uses `Intl.Collator`, there is a `locale` prop to configure it
