### ISSUE TITLE
[Bug Report][3.0.0-beta.5] [Bug Report][3.0.0-beta.5] event 'group:selected' is not declared in the emits option 

### ISSUE THREAD

**Issue by apss-pohl** [vuetifyjs/vuetify#15425]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
open the console

Same issue already reported: https://github.com/vuetifyjs/vuetify/issues/15187
Still occurs with beta  5

### Expected Behavior
no warnings

### Actual Behavior
[Vue warn]: Component emitted event "group:selected" but it is neither declared in the emits option nor as an "onGroup:selected" prop. 

### Reproduction Link
<a href="https://codepen.io/apss-pohl/pen/gOewObg" target="_blank">https://codepen.io/apss-pohl/pen/gOewObg</a>

**Comment by KaelWD** [comment]
Duplicate of #15187

**Comment by apss-pohl** [comment]
It`s not a duplicate, the issue still exists in beta-5. 

> Duplicate of #15187

**Comment by KaelWD** [comment]
Look at when that issue was closed, now look at when the last release was.

**Comment by apss-pohl** [comment]
> Look at when that issue was closed, now look at when the last release was. Use nightly builds if you want every change asap.

Sorry my bad, I was misreading it was fixed in beta-5
