### ISSUE TITLE
client server hydration bug on v-data-table on 0.15.0-beta.5

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#1542]
After upgrade 0.15.0-beta.4 => beta.5 there is a client server hydration error on the v-select of rows per page:
```
vue.esm.js:5527 Mismatching childNodes vs. VNodes:  [div.input-group__selections__comma] (2) [VNode, VNode]
```

### Steps to reproduce 
upgrade 0.15.0-beta.5 and use pagination.sync and rows-per-page-items props

### Versions
0.15.0-beta.5

This worked on 0.15.0-beta.4 before

**Comment by nekosaur** [comment]
You'll have to provide more information or a reproduction. I can't repro this on docs when using both props.

**Comment by dohomi** [comment]
@nekosaur this is my current list of elements (async):
```
    <v-data-table :headers="tableHeaders"
                  :items="list"
                  v-model="selected"
                  selected-key="id"
                  :loading="!!loadingApollo"
                  :total-items="count"
                  :pagination.sync="pagination"
                  :rows-per-page-items="[20,50,100,200,500]">
```
I use this on Nuxt and on beta.4 and all versions before it worked without problems, but beta.5 has a problem with the rows-per-page-items. as the list is asynchrone the rows-per-page renders on server only 2 items and on client all 5 items. I am not sure how to set up a whole repro without Nuxt though..

**Comment by dohomi** [comment]
after 0.15.2 the error is gone 👍
