### ISSUE TITLE
[Bug Report][3.0.0-beta.5] The `box-sizing` CSS property is `inherit` instead of `border-box` on all elements

### ISSUE THREAD

**Issue by gkubisa** [vuetifyjs/vuetify#15427]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Set the `box-sizing: content-box` CSS property on an element.

### Expected Behavior
The computed value of the `box-sizing` CSS property should change only on the element on which we set that property.

### Actual Behavior
The computed value of the `box-sizing` CSS property changes on the element on which we set that property and also on all descendant elements.

### Reproduction Link
<a href="https://codesandbox.io/s/magical-pasteur-3l58fu?file=/src/App.vue" target="_blank">https://codesandbox.io/s/magical-pasteur-3l58fu?file=/src/App.vue</a>

### Other comments
The problem is that the CSS reset sets `box-sizing: inherit` on all elements [here](https://github.com/vuetifyjs/vuetify/blob/v3.0.0-beta.5/packages/vuetify/src/styles/generic/_reset.scss#L27). It should instead set `box-sizing: border-box` directly on all elements. This way we'd get more consistent, logical, predictable and useful behavior.

**Comment by KaelWD** [comment]
This is part of the CSS reset and has been common practice for years: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by jroessel** [comment]
One surprising aspect of explicitly inheriting `box-sizing`, is that the browser may have to invalidate styles for a lot more elements. Basically, once an element is style-dirty, the whole subtree beneath it is recalculated as well. This can lead to quite long »Recalculate style« occurrences when the DOM and CSS is large. Firefox is only affected on the HTML side and will not invalidate the whole subtree in SVG, but Chrome will do that for both SVG and HTML. So in essence, the convenience and flexibility to choose `box-sizing` on a sub-tree level with inheritance comes with the cost of making style recalculations more expensive by dirtying much more of the DOM than usually necessary.
