### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Arrow keys not working in V-autocomplete

### ISSUE THREAD

**Issue by freesoul** [vuetifyjs/vuetify#15428]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Last working version:** 2.6.7
**Vue Version:** 3.2.3
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Click on the V-autocomplete (last in example)
2. Press down arrow

### Expected Behavior
The first item in the dropdown gets highlighted

### Actual Behavior
nothing happens

### Reproduction Link
<a href="https://codepen.io/kener18/pen/oNqzXpO" target="_blank">https://codepen.io/kener18/pen/oNqzXpO</a>

### Other comments
The example in the documentation of prev version works
https://vuetifyjs.com/en/components/autocompletes/#examples

The one in here does not
https://next.vuetifyjs.com/en/components/autocompletes/

**Comment by WhiteSage** [comment]
Same problem seems to affect v-select.

**Comment by johnleider** [comment]
Watch https://github.com/vuetifyjs/vuetify/pull/15632
