### ISSUE TITLE
[Feature Request] v-data-table - ability to have an render function for any column in the header

### ISSUE THREAD

**Issue by ionutt** [vuetifyjs/vuetify#15439]
### Problem to solve
Ability to have a value in the items and render something else, without using scope slots for items.

### Proposed solution
that render function will receive the entire row, and you can easily attach filters, custom function to render a particular value. Example: I have value 1, but I want to render 1%. 
I know that this is something that we can do with slots, but it is much easiear to do it with that function and we can build wrapper components that can take the metadata of the grid from some external api ( to configure the grid ). 
Also for sorting that initial value will be lost ( and we need to do all weird things duplicate column ) if we will not used that slot scope.

**Comment by KaelWD** [comment]
This is exactly what scoped slots are.

**Comment by ionutt** [comment]
I understand the solution. You can close the ticket.

Thanks
