### ISSUE TITLE
[Bug Report][3.0.0-beta.5] VList is not emitting a value when an item is clicked

### ISSUE THREAD

**Issue by PedroCuadra** [vuetifyjs/vuetify#15436]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Firefox 102.0
**OS:** Windows 10

### Steps to reproduce
Click in items of the list

### Expected Behavior
In the text "Value: x" should change x according the value of the item 

### Actual Behavior
Does not change.

### Reproduction Link
<a href="https://codepen.io/pcuadra/pen/RwMoWWW" target="_blank">https://codepen.io/pcuadra/pen/RwMoWWW</a>

### Other comments
Although the list is not emiting a value to v-model, the items are activated when clicked.

**Comment by KaelWD** [comment]
`v-model:selected`
