### ISSUE TITLE
[Bug Report][2.6.7] VTextarea prop 'reverse' doesn't work correct in LTR direction 

### ISSUE THREAD

**Issue by AndrewBeznosko** [vuetifyjs/vuetify#15432]
### Environment
**Vuetify Version:** 2.6.7
**Last working version:** 2.6.7
**Vue Version:** 2.7.5
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
To pass `reverse` property in `<v-textarea reverse />` - nothing happens.

The issue located in ./vuetify/src/components/VTextField/VTextField.sass:356

### Expected Behavior
```
  &--reverse
    input, textarea
      +ltr()
        text-align: right

      +rtl()
        text-align: left
```

### Actual Behavior
```
  &--reverse
    input
      +ltr()
        text-align: right

      +rtl()
        text-align: left
```

### Reproduction Link
<a href="https://codepen.io/AndrewBeznosko/pen/abYmRoV?editors=101" target="_blank">https://codepen.io/AndrewBeznosko/pen/abYmRoV?editors=101</a>

**Comment by lioneaglesolutions** [comment]
@johnleider this is still present in V3 however I'm not sure if you have to set some sort of LTR setting on your machine/browser to trigger the inclusion of the style?

V3 repro for textarea and text-field [here](https://play.vuetifyjs.com/#eNq9k8tuwjAQRX8l8hrH6kOqhCiim676B4SFwUNx60dkT9JWiH/vOAFCAxWwYRXljj333MlkumYvZZnXFbAhGyHY0kiEceGybFTzhXcotYOQLU2lVSM3BYRvlAFkK2SZkxaeC6ZdWSF/4ncF21VqGbR0SMWlNgZUVzFyDob0t/TsZFmh5+/Bf+0E6xUYXktTJQvnMQtQQ4hdr/FIdEhbyN3tG8Nu0U6zx5WvjMrmcEWCLT9fajCqT/OqQ8QmT4e00gq4AvpuJtKRRNgVr5hl63gzlv9n0xvqKcAk7XeVlJHYbzIbMKPdZ8w/one04+t0vmCLGAs2zKbbeGyFWMahEAvl6CSB6TrkDlC40gr6O1AvfyYP+X1+L5SOuJM4pY950yx1mhVuQ4balj4gt7LsubaFxrlRkkad0vsZhAkdE6FyqC1N1NuG5fGphTnQc4iWz2khIwTqUrDBgU8ivsDrXFyyOGotyI8+Eg/gFAQIl0bqXfsTq1c7ipbsN2nimwFr79HsG2g2+wWlgpEN)
