### ISSUE TITLE
[Feature Request] FileUpload component availability 

### ISSUE THREAD

**Issue by nni123** [vuetifyjs/vuetify#1543]
Library is awesome not question about it.

Any plan to add FileUpload component. It will complete the requirement for our UI.

We love material UI design..very well done...

Thanks

**Comment by jacekkarczmarczyk** [comment]
Planned for Frontend Pack https://github.com/vuetifyjs/vuetify/issues/238

**Comment by nekosaur** [comment]
Duplicate of #238
