### ISSUE TITLE
[Bug Report][3.0.0-beta.5] position: sticky not working with `v-app` & `v-main`

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15433]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Scroll the page.

### Expected Behavior
Navbar should be sticky

### Actual Behavior
It isn't

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/ZExpqov" target="_blank">https://codepen.io/jd-0001/pen/ZExpqov</a>

### Other comments
Remove the `v-app` & `v-main` wrapper  and it will work.

Moreover, I am using custom layout in my app.

**Comment by KaelWD** [comment]
v-layout has relative position and overflow hidden, not sure if they're still needed @nekosaur

**Comment by nekosaur** [comment]
Hm, I thought I removed that already, but maybe I tried and it broke something? I can have a look.
