### ISSUE TITLE
External pagination count not synced upon table search

### ISSUE THREAD

**Issue by cristijora** [vuetifyjs/vuetify#1544]
### Steps to reproduce
1. Open [this codepen](https://codepen.io/anon/pen/PKXQmY)
2. Search for anything (e.g Frozen )

### Versions

Latest Vue, Vuetify
Browser: Latest Chrome on Windows 10

### What is expected ?
The pagination number should change based on search results.
When I search for "Frozen" which gives me 1 out of 10 items, the pagination count is 2 instead of 1,
Suggestion: Maybe provide another example in the docs which will sync the searched item count instead of the passed items to the table
``` js
pages () {
    return this.pagination.rowsPerPage ? Math.ceil(this.items.length / this.pagination.rowsPerPage) : 0
}
```
Instead of `this.items.length` maybe there is a way to expose `this.searchedItems.length`

### What is actually happening ?
The pagination count is based on the initial set of items which is changes when you search in the table.

### Reproduction Link
https://codepen.io/anon/pen/PKXQmY

**Comment by nekosaur** [comment]
The total length is already exposed on pagination object in the `totalItems` property. However it was not correctly updating when searching.

**Comment by johnboc** [comment]
Has this issue reappeared in V0.17? I'm getting this problem again and the above codepen shows the error

**Comment by nekosaur** [comment]
Please create a new issue using the [issue creator](https://issues.vuetifyjs.com)

**Comment by marcovc** [comment]
@jonhboc I realized that there is indeed a bug. There is an undocumented parameter called "searchLength" that must be changed when external search is done, and it isn't.

**Comment by Deg5112** [comment]
it seems like when i add the search property to the v-data-table.. doing that directly, while setting totalItems seems to be the cause
