### ISSUE TITLE
[Bug Report][3.0.0-beta.5] useLocale not exported in Vuetify3

### ISSUE THREAD

**Issue by firepick1** [vuetifyjs/vuetify#15441]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Chromium OS 14816.99.0

### Steps to reproduce
```
import { useLocale } from "vuetify"
```

### Expected Behavior
I'd like to test i18n

### Actual Behavior
can't localize custom components as documented in Vuetify3.

### Reproduction Link
<a href="https://codesandbox.io/s/fancy-brook-c7t0h6?file=/src/App.vue" target="_blank">https://codesandbox.io/s/fancy-brook-c7t0h6?file=/src/App.vue</a>

### Other comments
Looking at the code, "useLocale" is actually coded in locale.ts but not exported.

**Comment by firepick1** [comment]
Ah. Sorry. The sandbox was private. Here is the code

```
<template>
  <br>
  useLocale: {{useLocale}}
  <br>
  pi: {{pi}}
</template>

<script>
import useLocale from "vuetify";
export default {
  name: "App",
  components: {
  },
  computed: {
    useLocale: ()=> useLocale,
    pi: ()=>Math.PI,
  }
};
</script>
```

**Comment by KaelWD** [comment]
@johnleider wtf do you need a repro for it literally isn't exported

**Comment by firepick1** [comment]
We heavily use I18N in Vuetify2. I18N does not work for endusers as documented in Vuetify 3 docs. I'm a dad as well and understand that things are hectic with newborns.  I18N is critically important. Please don't ignore this issue. It's important and will allows us to proceed with our Vuetify3 transitions.  We are currently blocked on I18N but can work on other projects in the meantime.
