### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-list-item-avatar rounded works incorrectly

### ISSUE THREAD

**Issue by yuxqiu** [vuetifyjs/vuetify#15442]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.25
**Browsers:** Edge 105.0.1300.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-list-item-avatar with start and image props inside v-list-item.

### Expected Behavior
The image should be displayed in a rectangular style.

### Actual Behavior
The image is actually displayed inside a circle.

### Reproduction Link
<a href="https://codepen.io/timqiu/pen/poLNVRB" target="_blank">https://codepen.io/timqiu/pen/poLNVRB</a>

### Other comments
When the rounded prop is applied to v-list-item-avatar, the image is shown in a rectangular style.

**Comment by KaelWD** [comment]
v-list-item-avatar has been removed.
