### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Icon not center on v-navigation-drawer with rail

### ISSUE THREAD

**Issue by MrPalixir** [vuetifyjs/vuetify#15454]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Safari 15.5
**OS:** Mac OS 10.15.7

### Steps to reproduce
On vuetify2 the default width of v-navigation-drawer with rail was 56 pixels, now with 74 pixels the icon is not center on the larger in rail position.

### Expected Behavior
Icon center on v-navigation-drawer with rail options

### Actual Behavior
The icon isn't center with rail option on v-navigation-drawer.

### Reproduction Link
<a href="https://codepen.io/mrpalixir/pen/xxWgqLZ?editors=1010" target="_blank">https://codepen.io/mrpalixir/pen/xxWgqLZ?editors=1010</a>

**Comment by johnleider** [comment]
Reproduction link: https://codepen.io/johnjleider/pen/jOzYjde
