### ISSUE TITLE
[Bug Report][2.6.3] V-Autocomplete freezes the browser

### ISSUE THREAD

**Issue by Yonier** [vuetifyjs/vuetify#15451]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Edge 103.0.1264.62, Google Chrome, Microsoft Edge
**OS:** Mac OS 10.15.7

### Steps to reproduce
When you select an Item from the V-Autocomplete and quickly focus another element.

### Expected Behavior
The V-Autocomplete should not freeze the application.

### Actual Behavior
The whole application freezes after quickly unfocusing the V-Autocomplete.

### Reproduction Link
<a href="https://codesandbox.io/s/clever-varahamihira-lnyl45" target="_blank">https://codesandbox.io/s/clever-varahamihira-lnyl45</a>

### Other comments
(For some reason this doesn't happen when the icons property is not defined in the Vuetify options and the clearable icon doesn't appears)
(It happens with the latest version 2.6.7 too.)

**Comment by lioneaglesolutions** [comment]
Are you able to provide a simpler reproduction? I've narrowed it down to the fact that `searchInput` is being called infinitely causing it to crash (add a `console.log` within that method and you will see this happening).

This indicates it could be an issue with your code - if you can reproduce in V3 or with a simpler reproduction, please comment here and I will look info it further.
