### ISSUE TITLE
[Bug Report][2.6.7] @mdi/js icon font not sizing correctly with avatar icons

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#15455]
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.7.7
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Import an avatar icon using `@mdi/js` (https://vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg).

### Expected Behavior
The avatar icon is sized correctly inside of the avatar component.

### Actual Behavior
The avatar icon is too large and extends beyond the avatar component.

### Reproduction Link
<a href="https://codepen.io/mcfarljw/pen/PoRWmar" target="_blank">https://codepen.io/mcfarljw/pen/PoRWmar</a>

**Comment by lioneaglesolutions** [comment]
I was able to check this locally on my own install using @mdi/js and works fine in V3 - couldn't repro in play.vuetifyjs.com (couldn't work out the import map) @johnleider 

Pretty sure this can be closed.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
