### ISSUE TITLE
Allow to configure how many items are displayed in a select multiple

### ISSUE THREAD

**Issue by fgutr** [vuetifyjs/vuetify#1546]
- What will it allow you to do that you can't do today?
Control how many selected items will be displayed
  - How will it make current work-arounds straightforward?
Nothing for now
  - What potential bugs and edge cases does it help to avoid?
It will allow the select not to grow when the items are many and can be shown for example 2 and 1 more
example:
https://monterail.github.io/vue-multiselect/

**Comment by johnleider** [comment]
This can already be accomplished just setting the maximum height. https://codepen.io/anon/pen/YxBxxx

**Comment by fgutr** [comment]
if I set max-height the select that is displayed is very small, I can not see all the items, it also grows for the side.

https://codepen.io/anon/pen/gxqxyB?editors=1010#0

**Comment by johnleider** [comment]
How many items do you want it to display at a time?

**Comment by fgutr** [comment]
for example, if I select 10, that in the select shows 2 selected and 8 more, so that the select does not grow in height or in width, that it retains its size
