### ISSUE TITLE
[Bug Report][3.0.0-beta.5] `combobox` with `chip` does not have proper spacing.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15469]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
Add lots of chips in Combobox and see the spacing

### Expected Behavior
It should have proper spacing.

### Actual Behavior
It does not have spacing. Look messy.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/WNzpMqv?editors=101" target="_blank">https://codepen.io/Alokdev/pen/WNzpMqv?editors=101</a>

**Comment by johnleider** [comment]
fixed by #15495
