### ISSUE TITLE
[Bug Report][3.0.0] `v-snackbar` scale-transition is not working. 

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15474]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
Add transition prop. `transition="scale-transition"`

### Expected Behavior
It should work like other transitions.

### Actual Behavior
it is just fade in the `center` location. `localtion='center'` but it work in `start` and `end` location

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/MWVmWGE?editors=101" target="_blank">https://codepen.io/Alokdev/pen/MWVmWGE?editors=101</a>

**Comment by JulianPinzaru** [comment]
> ### Environment
> **Vuetify Version:** 3.0.0-beta.5 **Vue Version:** 3.2.36 **Browsers:** Chrome 103.0.5060.114 **OS:** Windows 10
> 
> ### Steps to reproduce
> Add transition prop. `transition="scale-transition"`
> 
> ### Expected Behavior
> It should work like other transitions.
> 
> ### Actual Behavior
> it is just fade in the `center` location. `localtion='center'` but it work in `start` and `end` location
> 
> ### Reproduction Link
> https://codepen.io/Alokdev/pen/MWVmWGE?editors=101

I'm experiencing the same issue. None of the transitions work as expected, except for `v-fade-transition`. They only work if location is set to any corner, like `top left` , `bottom right`, `top right`, `bottom left`. I hoped the transitions would work for any other locations but corners.
