### ISSUE TITLE
[Bug Report][3.0.0-beta.5] `v-combobox` with density="compact" label get messy

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15482]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
When you use `solo`, `filled` Combobox with `density=" compact"` prop then spacing between the chip and label is very less.

### Expected Behavior
They have some proper spacing to look good. Also, chip size should be `small` in `compact` density.

### Actual Behavior
It feels very messy

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/abYWYMj?editors=1010" target="_blank">https://codepen.io/Alokdev/pen/abYWYMj?editors=1010</a>

**Comment by alokVishu** [comment]
Also, all variant has different spacing between content and label.

**Comment by johnleider** [comment]
Selections for **chips** were not applying top margin, however, due to the limited space available with solo fields, my suggestion would be to use the **chip** slot to manually reduce the `v-chip` `size.
