### ISSUE TITLE
[Bug Report][3.0.0-beta.5] click:clear not working in v-autocomplete

### ISSUE THREAD

**Issue by xiscohv** [vuetifyjs/vuetify#15496]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Select option, click on the clear button and not working

### Expected Behavior
Call the function inside the click:clear

### Actual Behavior
Nothing

### Reproduction Link
<a href="https://codepen.io/xiscohv/pen/rNdmXwZ" target="_blank">https://codepen.io/xiscohv/pen/rNdmXwZ</a>

**Comment by KaelWD** [comment]
![Screenshot_20220809_190946](https://user-images.githubusercontent.com/16421948/183610984-4d88b0aa-c2e6-43db-ac4f-33999630dfb0.png)

**Comment by yuwu9145** [comment]
@KaelWD above codepen link is based on vuetify 2 but coincidentally it does exit in vuetify 3 as well:

https://codepen.io/yuchaosydney/pen/XWEBYy

**Comment by KaelWD** [comment]
I didn't notice that, if I see a repro that's broken for other reasons it just gets closed immediately.

**Comment by yuwu9145** [comment]
no worries, understand 👍
