### ISSUE TITLE
Cannot change hours of a VTimePicker with no-title wrapped in VMenu

### ISSUE THREAD

**Issue by haggys22** [vuetifyjs/vuetify#1549]
### Steps to reproduce
Wrap a `VTimePicker` with `no-title` in a `VMenu` as described in https://vuetifyjs.com/components/pickers#example-9

### Versions

**Vue** v2.4.2
**Vuetify** v0.14 and v0.15.0-beta.5
**OS** Debian Jessie
**Browsers** Vivaldi 1.11.917.43 and Firefox 52.3.0

### What is expected ?
After picking a time and saving I expect to be able to change the selected time, including hours

### What is actually happening ?
After picking a time and saving, clicking the text-field will open the picker in "minute-mode" without being able to change the hours value

### Reproduction Link
https://codepen.io/anon/pen/LjMgeg

### Additional information
Clicking the text-field and saving without having picked an hour (which will default to the current time) will show the picker in "hours-mode" as long as one does not select an hour.  
Selecting an hour and canceling the picker will result in the same bug, without having any time selected.

**Comment by johnleider** [comment]
Looking for suggestions on how you would imagine this would work. It's a very valid point, and there is no way to get back designated by the component, due to how decoupled it is from components like ```v-menu``` and ```v-dialog```.

Here's a temporary solution https://codepen.io/anon/pen/LjqjWb?editors=1111
