### ISSUE TITLE
[Bug Report][2.6.7] Disabled Vselect have none disabled hidden fields

### ISSUE THREAD

**Issue by JohnstonCode** [vuetifyjs/vuetify#15490]
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.7.7
**Browsers:** Chrome 103.0.5060.114
**OS:** Linux x86_64

### Steps to reproduce
Create a v-select component and add disabled prop

Submit the field as part of a form submission

### Expected Behavior
Disabled VSelect should not be submitted as part of the form

### Actual Behavior
Field is submitted

### Reproduction Link
<a href="https://codepen.io/c92dotdev/pen/gOeWEGJ?editors=1011" target="_blank">https://codepen.io/c92dotdev/pen/gOeWEGJ?editors=1011</a>

**Comment by JohnstonCode** [comment]
Let me know if you would like me to submit a PR

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqVU39r2zAQ/SpCDJJCbJd0MMjckMHoF+ifcRj+cV606IeRZKcl+LvvJNmOl8LaBgK5e+/uvdNd9hf6o2nirgW6oakF0fDcwjaThKRdZI4AlpxZZY+PGX24v88oKXluDEbiJcpbqzLqyZ5eKy2IhhpR93OCPGjhxUY1A16NSUK6SKgKOPIdmtErwvPC55+YNpbIXMAcdTGCt+n5p2ImLzhMYts0mXuYnM0cGuBQWrJh+Axuwv2iVmpxwJkHvUDAeGw+GyBgqEcn788jPUG1z+gwWfK2gurXJPgZnZlSYSXZlZyVJ1fZFoI5WsFVebru0UZr3NSzR90jYdG4UozcIsM5YODvAaM0mV1KakrNGksM2LbxVPdlolHakgueQ09qrQRZ4JEtvo94qSQu1l/Mo7uZpWw5v7uB3b4GeOHeZhEIARxfYiS4R7w2qFtZWqYkCWMv78glDOWKFYeYq99LJx93OW8h/gKD+tzaz9zm2F7CmTwN4X9rqsC/9JgNeWSTZQD3J3hdEV95IKqeBGKQVjMwy7vJI54vAq7ggO18yaDTj43nYzhyMIJwmoR9bOmKciZPJv5jlMR/t++d0dKYjG7IPrTJ6NHaxmySpKwkMvHIWKdjCTaRjUhwZZbVr7uHeB2vEzx7O6YivD4T+2au0yGTPQqGrUcib25UA+CVhxkzip1c/I6FHdIS3UrLBESVEt7L12/BzCwfgxFRodXZgMYuGV3NdJzjD2i9Ny5KvGmdoF4HOtIgK9CgPzrSTdk/Y91gb0YbVt3TfkVDHb69N00PfwHj7uSY
