### ISSUE TITLE
add href/router/nuxt options to v-btn

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#155]
Hi,
in some scenarios I would see benefits to add the `href/router/nuxt` options from `v-list-tile/v-toolbar-item` inside `v-btn` as well. 
Thanks!

**Comment by jrast** [comment]
It seems that `router` and `to` is working, however, these props are not mentioned in the docs.

**Comment by johnleider** [comment]
This was something resolved through a ticket on the documentation branch. Please try to avoid posting on old issues with information that relevant to the original ticket, thank you.
