### ISSUE TITLE
[Bug Report][2.6.6] v-select inside disabled v-card can still show items if clicked on the label

### ISSUE THREAD

**Issue by burimarnica** [vuetifyjs/vuetify#15501]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.6
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
-Create a v-card, make it disabled
-create a v-select with at least one item (example:"Item 1")
-set a label for the v-select
-set the v-model of the v-select as the first item of an array (e.g. "Item 1")
-run the app
-click the label, the dropdown still works

### Expected Behavior
the dropdown of a v-select shouldn't show if the v-select is inside a disabled v-card.

### Actual Behavior
the dropdown of a v-select shows even when the v-select is inside a disabled v-card.

### Reproduction Link
<a href="https://codepen.io/black-pyro/pen/xxWrdwx" target="_blank">https://codepen.io/black-pyro/pen/xxWrdwx</a>

**Comment by HelenBurbank** [comment]
I create a PR fixing this issue, please review, thanks!

**Comment by lioneaglesolutions** [comment]
This has been resolved in V3

https://play.vuetifyjs.com/#eNqNUEtuwjAQvYrlDa1EYkQrVUoDomfoErMIyaS4xB/ZJm2FcveObVJRWIBXnjcz7zPrI30zJu8PQAtaepCmqzwsuSL4yj6rK9ukgpCmsvvxvwPxsfMLTuezGad/E8JV2w5OGyeW8N61BOLh248QUjvooPakq7bQIVEciQWnpBBoxSG6nrRaTzYI9ZnUTZwMPQTY6JIlm1iW7CwBlq62wnjiwB8MIkIabT05WmgH0lotyQSDT14DD1e1Vs6TQE4WBEceovQjdkuWiJZ0Sjuh9i7/dFrhwY5xk9bOcVqQdfLD6c574wrG6kbhJJoWvc0VeKaMZKjoRfuzesrn+ZzhxfwIZZje5ZEsMG24GlAwmc5kZS5UUyMqRyRgyBTqGxZWOMbsQXkhIWu0jF6eX5KZMzwHJ7Ot1V8OLLJwOj3TCY7v0LoVFyWuqBnq9WAzC6oBC/beSBdr/2Jd9K6iBfkhXHyY0rSHt4+m6eYXAOEJNQ==

@johnleider if you're happy to close this, please also close related PR https://github.com/vuetifyjs/vuetify/pull/15810
