### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Components having ripple aren't aligned with rest of the content

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15519]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Last working version:** 2.6.7
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
N/A

### Expected Behavior
The checkbox should be left aligned with the text.

This is the same with icon-only buttons and other components.

### Actual Behavior
Due to ripple it is moved right

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/mdxBdrX?editors=1011" target="_blank">https://codepen.io/jd-0001/pen/mdxBdrX?editors=1011</a>

**Comment by jd-solanki** [comment]
![Screenshot 2022-07-26 at 6 20 06 PM](https://user-images.githubusercontent.com/47495003/181009868-eaf7a2ae-1fda-4acd-8129-e57b257db718.png)

Icon only button. It is aligned using ripple instead of its content.

**Comment by KaelWD** [comment]
That's always been the case, no plans to change it.

**Comment by jd-solanki** [comment]
> That's always been the case, no plans to change it. The ripple is also the click target so it'd cause a lot of problems if we gave it a negative margin.

Yes, you are right about the button.

Is this same for components like checkbox & radio?

In v2 ripple wasn't taking its space as shown in the v2 docs:
https://vuetifyjs.com/en/components/checkboxes/
https://vuetifyjs.com/en/components/radio-buttons/

However, with v3 ripple is taking its own space resulting in more indentation from its container compared to other content:
![Screenshot 2022-09-02 at 3 30 19 PM](https://user-images.githubusercontent.com/47495003/188115567-b6ef835b-ece3-4bc5-bbb4-91fd85e9d212.png)

v3 docs:
https://next.vuetifyjs.com/en/components/checkboxes/
https://next.vuetifyjs.com/en/components/radio-buttons/

**Comment by jd-solanki** [comment]
This is screenshot of our live template using v2:
![Screenshot 2022-09-02 at 3 32 07 PM](https://user-images.githubusercontent.com/47495003/188115736-f76fdf1b-31bf-462c-9354-1cf11ebe2c84.png)
