### ISSUE TITLE
[Bug Report][3.0.0] VBtn size options does not change icon size

### ISSUE THREAD

**Issue by davidramosweb** [vuetifyjs/vuetify#15515]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Safari 15.5
**OS:** Mac OS 10.15.7

### Steps to reproduce
<v-btn
    color="secondary"
    icon="mdi-television"
    size="x-small"
></v-btn>

### Expected Behavior
The class `v-icon--size-x-small` should be added to the icon

### Actual Behavior
The icon has `v-icon--size-default`class

### Reproduction Link
<a href="https://codepen.io/davidramosweb/pen/jOzLRXw?editors=101" target="_blank">https://codepen.io/davidramosweb/pen/jOzLRXw?editors=101</a>

**Comment by KaelWD** [comment]
#15516 was reverted

@johnleider I think it did just have a `font-size: 1.5rem` (or something) override at one point.

**Comment by johnleider** [comment]
fixed by 569b75d4

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
