### ISSUE TITLE
[Bug Report][2.6.7] [WCAG] - v-dialog does not retain focus when retainFocus is passed

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#15512]
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.7.8
**Browsers:** Chrome 100.0.4896.127
**OS:** Linux x86_64

### Steps to reproduce
Open the link.  Click the button to open the modal.  

Tab through the buttons on the modal.  You'll notice the focus jumps out of the modal instead of wrapping back to the beginning of the modal content again.  

This was previously reported in #12720, which was closed as invalid but the explanation does not make sense.  It is causing some WCAG issues being able to tab out of the modal to content behind.

### Expected Behavior
The focus to loop to the front after reaching the last tabbable element

### Actual Behavior
The modal is losing the focus.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/MWVvXxd" target="_blank">https://codepen.io/gabaum10/pen/MWVvXxd</a>

**Comment by KaelWD** [comment]
Again, you don't have anything else outside of the dialog in that codepen. As I explained in #12720 it will not trap the focus in in iframe (like codepen uses) and will not prevent tabbing to the rest of the browser UI such as the address bar.
