### ISSUE TITLE
[Bug Report][3.0.0-beta.5] `expansion-panels` title get animate twice.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15523]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.134
**OS:** Windows 10

### Steps to reproduce
Try to toggle `expansion-panel` and see the title get animated twice.
![chrome-capture-2022-6-27 (1)](https://user-images.githubusercontent.com/80033712/181189279-02f14715-fe53-4295-b792-3fd783e8130a.gif)

### Expected Behavior
it should be stable and not move twice.

### Actual Behavior
It is moved twice when the panel opens.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/QWmqqVr?editors=101" target="_blank">https://codepen.io/Alokdev/pen/QWmqqVr?editors=101</a>

**Comment by KaelWD** [comment]
This happens in v2 as well, it's just due to subpixel AA being disabled during transitions.
