### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-text-field's label when 'readonly' is set true.

### ISSUE THREAD

**Issue by jyjdal** [vuetifyjs/vuetify#15526]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.63
**OS:** Windows 10

### Steps to reproduce
You only have to use a v-text-field component, set a label and set attribute 'readonly'.

This is about v-text-field's label and readonly attributes.
In vuetify 2.x.x, when readonly is set true, labels will move up and show the value automatically.
(here's a link in your documentation: https://vuetifyjs.com/zh-Hans/components/text-fields/#section-798175284e1453ea8bfb)
But in vuetify 3.0.0, labels won't automatically move up unless you click the v-text-field component.
So is there a way to make this component behavior the same as it was in v2.x.x?

### Expected Behavior
Label moves up and the component shows its value without clicking it.

### Actual Behavior
You have to click it to make label move up, without this, value is covered by label.

### Reproduction Link
<a href="https://codesandbox.io/s/cranky-phoebe-vuw2sd" target="_blank">https://codesandbox.io/s/cranky-phoebe-vuw2sd</a>

**Comment by johnleider** [comment]
Vue 3 changed from **value** to **model-value**. <https://codepen.io/johnjleider/pen/eYMegxN>

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
