### ISSUE TITLE
[Bug Report][2.5.10] Attach with absolute behavior in v-menu

### ISSUE THREAD

**Issue by SakuraBurst** [vuetifyjs/vuetify#15539]
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Download my project and click on the second button. To understand what was the behavior before, change the version to 2.5.9

### Expected Behavior
Same functionality as 2.5.9

### Actual Behavior
v-menu-content moved somewhere

### Reproduction Link
<a href="https://github.com/SakuraBurst/v-menu" target="_blank">https://github.com/SakuraBurst/v-menu</a>

### Other comments
Prior to version 2.5.10, v-menu with attach and absolute params had the usual understandable behavior. Now I don't understand how it works

**Comment by SakuraBurst** [comment]
To clarify what it looks like to me:
2.5.9
![chrome_puARnAzVdC](https://user-images.githubusercontent.com/56797965/181758568-71a234d8-99d9-4333-a07e-6640b510c5fb.png)
2.5.10
![chrome_hn9XOYuPfb](https://user-images.githubusercontent.com/56797965/181758623-f9e71a3c-9959-4c9a-ac6f-ac2aa9750bb3.png)

**Comment by KaelWD** [comment]
Are you using 2.5.10 in the reproduction because it works in 2.6?

**Comment by SakuraBurst** [comment]
@KaelWD No, I'm using 2.5.10 because that's where the behavior came from. The latest version still has the same

**Comment by KaelWD** [comment]
Probably caused by 83f262a9
