### ISSUE TITLE
[Feature Request] Data table click middle on row

### ISSUE THREAD

**Issue by aesteves60** [vuetifyjs/vuetify#15532]
### Problem to solve
We can't catch the event `@click:row.middle` or `@mousedown:row.middle`
https://codepen.io/alexesteves/pen/poLdvov?editors=1011

### Proposed solution
Add the event mousedown:row to catch the click middle (scroll wheel) 
I think it's better to create a new event @mousedown because if you catch the mousedown and emit `click:row` you risk having 2 events `click:row` (https://javascript.info/mouse-events-basics#events-order)

**Comment by KaelWD** [comment]
Duplicate of #9720
