### ISSUE TITLE
[Bug Report][3.0.0-beta.5] RTL is not working

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15534]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Last working version:** 2.6.7
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In v2

### Expected Behavior
It should update class attached with v-application & make everything right to left

### Actual Behavior
Not doing anything

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/eYMezMY" target="_blank">https://codepen.io/jd-0001/pen/eYMezMY</a>

### Other comments
As everything is almost complete or at least partially working there are no docs on RTL. It will be great to provide RTL docs as people like me are on the verge or release and just waiting for the RTL docs for correct implementation

**Comment by jd-solanki** [comment]
After discussing with kael I think vuetify doesn't export `useLocale` as well
![image](https://user-images.githubusercontent.com/47495003/182111531-fdd5baa9-0796-4a8a-b431-3fc2d0a9a33d.png)

**Comment by jd-solanki** [comment]
BTW, here's discord message reference: https://discord.com/channels/340160225338195969/660898563139567625/1001807840547176478

**Comment by KaelWD** [comment]
@johnleider weren't you going to remove `useRtl` and make it part of `useLocale` instead?

**Comment by johnleider** [comment]
I moved the instantiation from `framework.ts` to the `local.ts` composable.
