### ISSUE TITLE
[Feature Request] Support CSS var while defining vuetify theme

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15535]
### Problem to solve
It will allow using user's custom CSS vars

```js
'on-surface': 'var(--my-custom-var)'
```

### Proposed solution
N/A

**Comment by nekosaur** [comment]
I think in theory this might be possible, but I wonder if we can run into problems when the css variable comes from an external stylesheet that is not yet loaded when vuetify is parsing the theme definition.

**Comment by KaelWD** [comment]
We'd have to just pass it though and not try to get the value, so any automatic qol features would of course not work like foreground color and variations.

**Comment by jd-solanki** [comment]
Looks promising 👍🏻

**Comment by jd-solanki** [comment]
https://github.com/vuetifyjs/vuetify/issues/16996#issuecomment-1728885005
