### ISSUE TITLE
[Feature Request] Have VDataTable and VDataIterator show contents of loading slot on a delay even if there is data

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#15537]
### Problem to solve
Consider this, we have a `VDataTable` or `VDataIterator` set to work with server-side pagination. You might also have the API for getting your data configured to include search or filter parameters. The current conditions to have the loading slot rendered involves having the loading property set to true and for there to be no data passed into the component. But what if a request that does pagination, filtering or search takes longer than usual? It would be nice to indicate to the user that a response to the request is pending. However the current implementation wouldn't let you use the loading slot to show that we're waiting for a response. It might seem to the user like nothing happened when they tried to perform an operation.

### Proposed solution
You could make it so the loading slot gets rendered, even if there is data, but on a delay. So if we've waited like 2 seconds for the request to be completed, the loading slot could be rendered. The loading slot render delay could be managed by a prop. If the prop is undefined, the default behavior, which is to not render the loading slot when there is data, could be used.

**Comment by aentwist** [comment]
I'm pretty sure this works correctly (at least now).

> The current conditions to have the loading slot rendered involves having the loading property set to true and for there to be no data

https://github.com/vuetifyjs/vuetify/blob/91f590c4ff277c1057302447afa044a3c067400f/packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx#L87

There is nothing in that condition about data existing.

> But what if a request [takes time]?

Then the `loading` prop should reflect that, and render the loading state.

Hardcoding delays is an antipattern and should never be considered. Therefore this is not a feature request, but a bug report, if I understand correctly. "The loading slot should be rendered when the loading prop is set to true". Which as I have noted above, is not currently a bug. I suggest closing this.
