### ISSUE TITLE
[Bug Report][2.6.7] Navigation Drawer v-main auto resize failed

### ISSUE THREAD

**Issue by changemyminds** [vuetifyjs/vuetify#15531]
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. click navigation drawer pushpin to hidden

### Expected Behavior
v-main content auto resize.

### Actual Behavior
v-main content doesn't auto resize.

![bugs](https://user-images.githubusercontent.com/13563347/181431326-b9b02c33-7306-4744-9c5f-a03f90a14e38.gif)

### Reproduction Link
<a href="https://codepen.io/changemyminds/pen/VwXMoRR?editors=1010" target="_blank">https://codepen.io/changemyminds/pen/VwXMoRR?editors=1010</a>

### Other comments
I see this bug is start at v2.6.2 version. 

The v2.6.2 version about Navigation Drawer issue is 
1. VNavigationDrawer: always bind mouseover events (#14523) (03e683f), closes #13309

If you downgrade version to v2.6.1, just change the codepen js setting to https://cdn.jsdelivr.net/npm/vuetify@2.6.1/dist/vuetify.min.js everything is work fine.

![fixedbugs](https://user-images.githubusercontent.com/13563347/181431910-d0769e67-850a-4d9a-8e8d-37d48cb63ef5.gif)

Is fixed the #13309 caused this bug ?

Related issue #14585

**Comment by MartinX3** [comment]
Still an issue with v2.6.10

**Comment by MorningLightMountain713** [comment]
Still an issue in `v2.6.13`

Just downgraded to 2.6.1 to get this to work
