### ISSUE TITLE
[Feature Request] OTP input & Watermark component For v3

### ISSUE THREAD

**Issue by samehdoush** [vuetifyjs/vuetify#15546]
### Problem to solve
Some nice out of the box component for  Watermark

### Proposed solution
Some examples exist like https://www.naiveui.com/en-US/dark/components/watermark 
&
https://vuetifyjs.com/en/components/otp-input/
Would love some input if somebody already created this for Vuetify
Because I only use vuetify

**Comment by KaelWD** [comment]
> OTP

Coming in 3.1 or 3.2

> Watermark

We don't have time to design or maintain something like that at the moment, you're welcome to copy the one from naiveui to use yourself though. 

---

Please keep issues to a single feature only.

**Comment by yeya** [comment]
I could not find otp-input in milestones for 3.1 or 3.2
