### ISSUE TITLE
[Feature Request] Kanban Board for Front End Pack

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#1554]
Here's some few example
https://vuejsfeed.com/blog/using-a-kanban-board-layout-component-inspired-by-invision-and-trello
![image](https://user-images.githubusercontent.com/9329005/29951074-bf773bb4-8ef2-11e7-959a-38d59404d52e.png)

Or some say  Scrumboard
http://fuse-angular-material.withinpixels.com/apps/scrumboard/boards

**Comment by johnleider** [comment]
After careful consideration I have decided this is something we will not persue, thank you for your suggestion.
