### ISSUE TITLE
[Bug Report][3.0.0-beta.5] TypeError: el.animate is not a function when using setValue on a v-field-text with a label and no value (unit-testing)

### ISSUE THREAD

**Issue by maxgrdo** [vuetifyjs/vuetify#15544]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Firefox 103.0
**OS:** Windows 10

### Steps to reproduce
Clone repo, install, then run "npm test:dom"

### Expected Behavior
Expect third test to pass

### Actual Behavior
Third test generates an exception : "TypeError: el.animate is not a function"

### Reproduction Link
<a href="https://github.com/maxgrdo/VTextField-bug" target="_blank">https://github.com/maxgrdo/VTextField-bug</a>

**Comment by KaelWD** [comment]
https://www.npmjs.com/package/web-animations-js

**Comment by trongbinh15** [comment]
I got the same error when trying to set the value of VTextField or VAutocomplete via ref in unit test. One solution I found that set `single-line` attribute to them. It seems like the problem is the animating of label of these components.
