### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Dependency mismatch when used in combination with other libraries

### ISSUE THREAD

**Issue by knightsrule** [vuetifyjs/vuetify#15543]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Safari 15.6
**OS:** Mac OS 10.15.7

### Steps to reproduce
This repo was created using "npm init vue@latest" and uses Vite and Pinia. It also uses Amplify UI.
 
1. Download this repo. 

2. run npm install

You will error messages related to Vuetify3 dependencies. 

You can bypass this with npm install --force.

### Expected Behavior
npm install should work without errors

### Actual Behavior
version dependencies errors likely due to Vite/pinia 

### Reproduction Link
<a href="https://github.com/knightsrule/Vue3_Boilerplate_UI" target="_blank">https://github.com/knightsrule/Vue3_Boilerplate_UI</a>

**Comment by KaelWD** [comment]
e9ab9166ee8ed1fb0a6e77e442354d89400bb43d
