### ISSUE TITLE
[Bug Report][2.6.8] v-tab not keeping track of v-tab--active & aria-selected when tab is partially shown

### ISSUE THREAD

**Issue by ngeorgiana** [vuetifyjs/vuetify#15558]
### Environment
**Vuetify Version:** 2.6.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Reduce screen size to have part of tabs overflowing
2. Click tabs in order
3. Click tabs skipping the second tab 
4. (Optional) Keep clicking skipping one tab

### Expected Behavior
1. Active tab is the same as the tab clicked
2. Active tab is underlined 

### Actual Behavior
1. Active tab does not get updated according to tab that is clicked
2. Tab clicked is not underlined 

### Reproduction Link
<a href="https://codepen.io/georgiana-negrea/pen/PoRErJm" target="_blank">https://codepen.io/georgiana-negrea/pen/PoRErJm</a>

### Screenshot
<img width="683" alt="Screenshot 2022-08-01 at 19 01 59" src="https://user-images.githubusercontent.com/40795417/182191133-b0c16b60-f907-4f96-b08d-f6608b52c5ab.png">

**Comment by KaelWD** [comment]
I don't really understand the steps you've given, it works for me.

https://user-images.githubusercontent.com/16421948/182602612-d6523d3b-1811-403a-81a7-da6dc97c49aa.mp4
