### ISSUE TITLE
[Bug Report][3.0.0-beta.6] VRadioGroup multiple attribute doesn't fulfill

### ISSUE THREAD

**Issue by alivadjid** [vuetifyjs/vuetify#15559]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Last working version:** 3.0.0-beta.6
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.134
**OS:** Linux x86_64

### Steps to reproduce
1. v-radio-group
2. attribute multiple
3. v-radio-group, v-model - array

### Expected Behavior
expect to put many values to array

### Actual Behavior
got one value

### Reproduction Link
<a href="https://codepen.io/alivadjid/pen/qBopzeN" target="_blank">https://codepen.io/alivadjid/pen/qBopzeN</a>

### Other comments
When trying to use 'multiple' attribute in v-radio-group and put to v-model array expect to put many values to array, but got just one

**Comment by nekosaur** [comment]
`multiple` prop does not apply for v-radio-group. radio buttons by their nature are mutually exclusive.

the issue here is that it re-uses shared selection control functionality, so that `multiple` still appears in API documentation.
