### ISSUE TITLE
[Bug Report][3.0.0-beta.6] `v-pagination`'s disabled state not visible properly.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15566]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.134
**OS:** Windows 10

### Steps to reproduce
Try to disable the pagination using the `disabled` prop.

### Expected Behavior
It should be visible a little bit.

### Actual Behavior
It is not clearly visible.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/JjLLoVN?editors=101" target="_blank">https://codepen.io/Alokdev/pen/JjLLoVN?editors=101</a>

**Comment by KaelWD** [comment]
#15156 - disabled with no color is too transparent
