### ISSUE TITLE
[BUG][0.15] Long description on stepper is wrapper to next line.

### ISSUE THREAD

**Issue by amesas** [vuetifyjs/vuetify#1556]
### Steps to reproduce
Create a vertical stepper with long description.
### Versions
Vuetify 0.15
Browser: All of them? Tested on Chrome, Firefox and Safari
### What is expected ?
Step icon and description should be aligned.

### What is actually happening ?
Description is wrapped to next line.

### Reproduction Link
https://codepen.io/anon/pen/zdeYze

**Comment by mornir** [comment]
Hi!
v-stepper-header is supposed to hold the titles of the steps. Just move the description to the v-stepper-content. From a UX/UI perspective, I think you need to keep the stepper titles succinct.

**Comment by amesas** [comment]
It has been working without any probs until now. So I don't see why it shouldn't now.
On small screen devices you don't need a long description to hit this problem.
The reproduction link is like this just to be sure that you can see the prob.

**Comment by sindrepm** [comment]
@amesas A workaround is to override `flex-wrap` like this:
```
.stepper__step {
  flex-wrap: nowrap;
}
```
I don't see the reason why the stepper label should wrap in the first place, but at least this is a simple workaround.

I don't see this being new in 0.15, though. The same behavior is present in 0.14 / 0.13 as well.
