### ISSUE TITLE
[Feature Request] add bg-color suport to v-btn-group

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15562]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.134
**OS:** Windows 10

### Steps to reproduce
try to use the `background-color` prop.

### Expected Behavior
It should work.

### Actual Behavior
Not available.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/VwXQMwd?editors=101" target="_blank">https://codepen.io/Alokdev/pen/VwXQMwd?editors=101</a>

**Comment by KaelWD** [comment]
> It should work.

And do what exactly? This isn't a bug if it never existed.

**Comment by johnleider** [comment]
After reviewing this again, since the group provides the btn values, they are, in essence, the background.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
