### ISSUE TITLE
[Feature Request] [3.0.0-beta.6] v-select with v-virtual-scroll

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#15572]
### Problem to solve
Currently, the v-select component from Vuetify 3 is not using a virtual scroll, making it very slow to open for a lot of items with images etc.

Btw, thanks for all the great work with this lib, it is amazing!

### Proposed solution
Providing a v-select which is using a virtual scroll, as it was in Vuetify 2.

**Comment by nekosaur** [comment]
https://github.com/vuetifyjs/vuetify/pull/15585
