### ISSUE TITLE
[Bug Report][3.0.0-beta.6] `v-checkbox` with `density="compact"` should change the checkbox size.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15577]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.5112.81
**OS:** Windows 10

### Steps to reproduce
try to use `density` prop with `v-checkbox`.``

### Expected Behavior
It should change the size of the checkbox.

### Actual Behavior
It only changes the ripple size.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/ExELydO?editors=101" target="_blank">https://codepen.io/Alokdev/pen/ExELydO?editors=101</a>

**Comment by johnleider** [comment]
This is working as intended. Use `v-checkbox-btn`.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
