### ISSUE TITLE
Avatar images should retain aspect ratio

### ISSUE THREAD

**Issue by haggys22** [vuetifyjs/vuetify#1557]
### Steps to reproduce
Copy pre-defined [layout #6](https://vuetifyjs.com/layout/pre-defined#example-6) but replace `v-list-tile-avatar` image source with any non-square image

### Versions
v0.14.11 and v0.15.0-beta.5

### What is expected ?
Non-square images should retain their aspect ratio

### What is actually happening ?
Non-square images get clinched

### Reproduction Link
https://codepen.io/anon/pen/EvrgXP

### Additional information
I've added a simple fix to the pen but I think we need more flexibility than that:
* The focus of the image is not always on the center (for portraits) or at the left end of the image (for landscape). As the short dimension is always shrinked to 40px we need a way to pass a value (maybe percentage) where to focus along the long dimension. For example I know that the avatar images in my company are always "face focused" at about 40% from the top.
* The orientation of the image is crucial. As you can see in the pen, applying the portrait fix on a landscape image (and vice versa) makes the avatar look even worse. The orientation should either be passed as a prop or automatically determined with JavaScript.

**Comment by johnleider** [comment]
This is out of the realm of what I think we should cover in the framework. It's an avatar, and has limitations in what you should be able to put there due to using the image itself as opposed to applying a background.
