### ISSUE TITLE
[Feature Request] Enable nuxt link attributes by default

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#15588]
### Problem to solve
When migrating to a Nuxt application, I have to find and add the `nuxt` attribute to all `<v-btn>`, `<v-card>`, etc.

### Proposed solution
Is there a way to initialize Vuetify and have the `nuxt` property enabled by default?

**Comment by Nuzzlet** [comment]
How were you able to get v-btn to work with nuxt links at all? What is the nuxt attribute?

**Comment by SkyaTura** [comment]
I think there is no need for a new feature for that, since you could use [globals](https://next.vuetifyjs.com/en/features/global-configuration/) to set default properties to any component you want if that fits better on your project.
