### ISSUE TITLE
[Bug Report][3.0.0-beta.6] Cannot scroll to the end of large `v-select` lists

### ISSUE THREAD

**Issue by movabo** [vuetifyjs/vuetify#15587]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.37
**Browsers:** Firefox 102.0
**OS:** Linux

### Steps to reproduce
1. (As per the reproduction link:) Create a v-select with lots of entries (100 should be enough).
2. Click on the select box.
3. Try reaching the last element.

### Expected Behavior
That the last element is visible when you cannot scroll any further.

### Actual Behavior
Elements at the end are not reachable.

### Reproduction Link
<a href="https://codepen.io/movabo/pen/mdxLGmO" target="_blank">https://codepen.io/movabo/pen/mdxLGmO</a>

### Other comments
This does not happen when
 - the select was opened before
 - the user resizes the window while the select is open

**Comment by artoroz** [comment]
Any timeline on this issue?

**Comment by movabo** [comment]
![Screen-Recording-2023-01-11-at-17 39 04](https://user-images.githubusercontent.com/4041740/211864766-8abdc666-d8d4-4d61-9b95-79ce2e74983b.gif)

On the initial click, the options only appear below the input and overflow the page (as one can see on the scroll bar appearing on the right). The second click behaves as expected.

**Comment by JesperHonders** [comment]
Is this still being worked on?
This is a major issue for our project

**Comment by KaelWD** [comment]
[v3.1.2](https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.2) added a default max-height, and [v3.1.3](https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.3) fixed inconsistent positioning on the first open.
