### ISSUE TITLE
Use Google Map's Autocomplete Feature on <v-text-field>

### ISSUE THREAD

**Issue by kvijay0007** [vuetifyjs/vuetify#1558]
### Versions
"vuetify": "^0.13.1"

### What is expected ?
Hi,
We can accomplish google map's autocomplete feature by
![capture](https://user-images.githubusercontent.com/15130479/29970335-bee8ad8c-8f41-11e7-812f-76ecb0e8be8f.JPG)

I want to use google map's autocomplete feature on <v-text-field>
![capture1](https://user-images.githubusercontent.com/15130479/29970342-c6ddbe2e-8f41-11e7-9d33-6c880f7c0948.JPG)

When Following code is executed
![capture2](https://user-images.githubusercontent.com/15130479/29970599-d907708a-8f42-11e7-8f83-5817ad87b8af.JPG)

I am Getting the following error
"**InvalidValueError: not an instance of HTMLInputElement**"

Please let me know how to use this feature using v-text-field

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by MartinMay** [comment]
`mounted () {
    let element = this.$refs.autocomplete.$el
    element = element.querySelector('input')
    const google = window.google
    this.autocomplete = new google.maps.places.Autocomplete(
    (element),
    {types: ['geocode']})
  },`

**Comment by KaelWD** [comment]
@MartinMay No need for the `querySelector`, `this.$refs.autocomplete.$refs.input` would work too.

**Comment by sholder123** [comment]
How do you change the value of <v-text-field> to the value selected from the autocomplete suggestions? When you select from the list, the value of <v-text-field> remains what the user typed in, not what is selected.
