### ISSUE TITLE
[Bug Report][3.0.0-beta.6] validate and other methods on ref child component is undefined in production

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#15591]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Last working version:** 2.6.7
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.0.0
**OS:** Linux x86_64

### Steps to reproduce

Init a Vue 3 and Vuetify 3 app. Add a simple text field with a ref on it, log the proxy and the `validate` property of ref. The property is defined on dev, but not on production build.
Please check out the readme of the [reproduction repository](https://github.com/paul-thebaud/bug-ref-vue-vuetify) for more details.

### Expected Behavior
Validate method should be accessible on production build too.

### Actual Behavior
The method is undefined the proxied object looks different than in dev mode.

### Reproduction Link
<a href="https://github.com/paul-thebaud/bug-ref-vue-vuetify" target="_blank">https://github.com/paul-thebaud/bug-ref-vue-vuetify</a>

### Other comments
This issue was first posted on the vue repository at this issue: vuejs/core#6418
They asked me to post here first.

**Comment by KaelWD** [comment]
Is this related to #15479?

**Comment by paul-thebaud** [comment]
HI @KaelWD, may be related, but the current state for is it is working in dev build, but not production, which does not looks exactly the same as #15479.
Tried with the nightly you gave, not working too.

**Comment by paul-thebaud** [comment]
Hello @KaelWD, thanks for this quick fix. Any nightly release on which you wish to try the fix?
