### ISSUE TITLE
Scroll directive doesn't work on body tag

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#1559]
### Steps to reproduce
In the main index, set `<body id="mainScroll">` 
In a Vue component, add the directive on a tag `<div v-scroll="{target: '#mainScroll', callback: onScroll}">`
In this very same component, write the method `onScroll(e) { console.log(e); }`
Then, try to scroll.

### Versions
Vue 2
Vuetify 0.14.11
Linux Ubuntu 16.10
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.113 Chrome/60.0.3112.113 Safari/537.36

### What is expected ?
The browser console should log the DOM of the body tag each time a scroll occurs.

### What is actually happening ?
No log appears in the console, probably because... (see below).

### Reproduction Link
A fiddle is hard to provide, because it needs to act on the body tag. My guess is that `addEventListener` doesn't work on body tag for scroll event. I tried with this fix and it seems to work:

    // vuetify/src/directives/scroll.js
    
    - 13   target.addEventListener('scroll', callback, options)

    + 13 if (target === document.body || target === document || target === window) {
    + 14     document.onscroll = callback;
    + 15 } else {
    + 16    target.addEventListener('scroll', callback, options)
    + 17 }

I'm not sure how to handle unbinding.

**Comment by johnleider** [comment]
The body is not a valid target with the current framework structure. If you are wanting to target the "body" or "document", you need to observe the window. Otherwise, it must be inside an actual element that scrolls, in this case, body does not.
