### ISSUE TITLE
[Feature Request] v-avatar tonal variant

### ISSUE THREAD

**Issue by quiquelhappy** [vuetifyjs/vuetify#15593]
### Problem to solve
there should be a v-avatar tonal variant (semi transparent background for the :color prop), as it is becoming increasingly popular on the material design language

### Proposed solution
``<v-avatar variant="tonal" color="primary"/>``

**Comment by johnleider** [comment]
fixed by https://github.com/vuetifyjs/vuetify/pull/15717
