### ISSUE TITLE
[Feature Request] CSS Cascade Layers

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#15596]
https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

https://caniuse.com/css-cascade-layers

There is a polyfill for older browsers but it doesn't support everything and could be a bit of a pain to set up: https://www.npmjs.com/package/@csstools/postcss-cascade-layers

**Comment by johnleider** [comment]
resolved by #19641
