### ISSUE TITLE
[Feature Request] v-calendar chips events

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15594]
### Problem to solve
chips events will allow adding pictures and be more eye-candy

That's totally necessary!

### Proposed solution
just style events as chips
<img width="430" alt="Screenshot 2022-08-07 at 22 41 05" src="https://user-images.githubusercontent.com/34601970/183310409-492cf403-33eb-4d0f-ad30-7a3e78359662.png">

**Comment by KaelWD** [comment]
You can use the day slot to customise rendering: https://vuetifyjs.com/en/components/calendars/#day
