### ISSUE TITLE
add option fullscreen to dialog/modal component for small screens

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#156]
Hi,

I used `fullscreen` option of dialog inside of my AngularMaterial project quite often: https://material.angularjs.org/latest/api/service/$mdDialog

It would be great to add this functionality to the dialog/modal component as well. Inside the AngularMaterial world setting the property to true means, on `xs` devices the dialog expands fullscreen and covers the whole screen.

I would think it would even be better to add `fullscreen:Boolean|String` to give set a dialog to fullscreen based on:
```
<v-modal fullscreen>
...
</v-moda>
```
Shows `v-modal` as fullscreen on all devices `xs`
```
<v-modal fullscreen="sm">
...
</v-modal>
```
Shows `v-moal` as fullscreen on devices `sm` and smaller (`sm,xs`).

Hope this feature request makes sense.

**Comment by johnleider** [comment]
Modal (now Dialog for v0.11.0) has been refactored and now includes a full screen option.
