### ISSUE TITLE
[Bug Report][3.0.0-beta.6] array.at() is undefined

### ISSUE THREAD

**Issue by shaydoc** [vuetifyjs/vuetify#15604]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.1
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the Form Dialog and notice z-index is broken on the dropdown menu's

### Expected Behavior
Expected  Dropdown to be at a higher z-index than the Dialogq

### Actual Behavior
Dropdown is behind the Overlay z-index

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/dialogs/" target="_blank">https://next.vuetifyjs.com/en/components/dialogs/</a>

### Other comments
try the form dialog here https://next.vuetifyjs.com/en/components/dialogs/

open the dropdown notices the z-index is behind the dialog

error in console: TypeError: Kc.at is not a function. (In 'Kc.at(-1)', 'Kc.at' is undefined) —

**Comment by KaelWD** [comment]
Old browsers will need polyfills
