### ISSUE TITLE
[Bug Report][2.6.9] `VData` creates undesirable behavior if the options prop is not set correctly

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#15609]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open CodePen.
2. Examine output at the bottom of the table.
3. Observe `sortDesc: [ false ]`
4. Observe that no sort has been applied to the table.
5. Apply a sort to one of the columns
6. Observe that the `sortBy` and `sortDesc` are not the same length and that `sortDesc` is too long.
7. Look at the code. Observe that we are not passing in a complete options object to start.

### Expected Behavior
It is expected that `VData` (which is being used by `VDataTable` in this example) should produce a valid result if it needs to modify the contents of the `options` prop to make it complete. The lengths of the `sortBy` and `sortDesc` arrays should always be the same.

### Actual Behavior
By passing incomplete data into a component using `VData` such as `VDataTable` or `VDataIterator`, `VData` can 'initialize' the `options` prop object incorrectly such that it contains invalid data. Once invalid data is in the `options` prop object, it seems that the invalid data does not get cleared. From the beginning, `sortDesc` will be created in the `options` object with the value of `[false]` while at the same time, the `sortBy` array will be empty. These two arrays should always be the same length.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/abYjmjx" target="_blank">https://codepen.io/MatthewAry/pen/abYjmjx</a>

### Other comments
Workaround: Specify a value for `sortDesc`. You can use the following:
```
options: {
  page: 1,
  itemsPerPage: 12,
  sortDesc: []
}
```
And see https://vuetifyjs.com/en/components/data-iterators/#api-props for the object definition.
You can also see the conversation about this issue here https://discord.com/channels/340160225338195969/351121729164410882/1006635099095302245

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqtlm1P2zAQx7+KFQkBUpP0GYg6xAZ7YOzF3k6UF25yLR6JHdluWVflu++cpE9pXWi0vml85//5d2c7uceF8zFNvdkUnMAZaEjSmGq4HnJCBjM3opq6mo5iMAZCZm4iIogDJaR2R/MPQ8c8fZoPncIfPAONQCp0lE8rD8PYxh6BUiD1yhHGVBk7xDCjmgnutgrX9cDfBFgihQiwEiXa7Q6d3IXOVML1YkEKJJJlA99Ych2GMkIcDPyNJHGoQslSnc+CPylKSQRjOo01WRRhDQI5O18OCZGgp5Kvx6RcMSCPC/IC+H8a0lhIBuq0QYTEMqCJqvCUZE+NtaqsEMrWNrIZ1vw00zGg/K4oGzlrNZsTgo8zxifnpxvhzI/GbMJxttJU6qrTUJpKBmRMYwUVbwHOaQLbumxrtFgB3a5TrORslXyhyG+gS8WYavvkWypHamt6aCx2wU8pNDC+JUkLm110LwUqTtYKhobt6Ztbtjy8h/fMFNGkK8Vf4OSXmEx3N2NZrYC0m82KD+sSkL5XNef54/xuxV4mGZDujsRkgyStk4N7upf+PsRrJoEmRFEevbLw+egUrmwpdC7sKXT+Xwqf8TXBpB27sx+7ZS99FW7FvSspuS9qcN9O05C+VO7hO8A7XrWuJXf/+Hpf1uD+iq8kkCM8NJGdvXts0btXNviOV3UtD0u/Bv13iOM5GQHlR8M3bexX1ru6KynZmzXQf4g4ZqlIa4C3LeCXVvD92O0a2N8Eh3koktHR3B0b96X1pPe93n7ybq8G+p3g0wPv9N5+7HbPdlB6LfsNtRzydp2SPzD9gF/do8Gtt7NfreoKvLoTJfahq7n+1GbFQ+HEwcAv+zSn4cSMvyjvtxIcW9Y8zaETKmwoV19l7D61TlXg+2HEcSa2rGwmPQ7a52niY7Or2Xh+g6fIa/sRU3ppcmM6Ul4ezER6GvIMF2SJ6QvdhKaVVQtHvnJZ7qGDkcz4DYQbnObLKdcsATcSSc7SvShgNuweqMQdSfGKbQdGGTplhfJ1DPE71norXVxiJ7RvOkyQrgSOPSrI96ZUkW2lVfHtpFZudeZkDafQYe1zaOfpHxsfSGI=
