### ISSUE TITLE
[Bug Report][3.0.0-beta.6] When trying to create a dialog, it does not work for me

### ISSUE THREAD

**Issue by aparna2071** [vuetifyjs/vuetify#15606]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.13
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
When I tried to open dialog box/pop-up box, it's working fine on codepen but when I insert the same code in my Vuetify app on my system, the button is showing nothing on click.

### Expected Behavior
On click, the button should show a pop-up box

### Actual Behavior
On click, it does not work

### Reproduction Link
<a href="https://codepen.io/aparnasoneja/pen/zYWLqRv?editors=101" target="_blank">https://codepen.io/aparnasoneja/pen/zYWLqRv?editors=101</a>

**Comment by KaelWD** [comment]
Read the examples on https://next.vuetifyjs.com/en/components/dialogs/ and https://next.vuetifyjs.com/en/components/menus/, the slot properties have changed.

**Comment by aparna2071** [comment]
Thanks @KaelWD for your help
