### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Unexpected behaviour if there is a long option in VCombobox

### ISSUE THREAD

**Issue by 0140454** [vuetifyjs/vuetify#15614]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.27
**Browsers:** Chrome 104.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Select a long option in VCombobox

### Expected Behavior
It should be text ellipsis.

### Actual Behavior
Without `single-line` prop, option value breaks into multiple lines.
With `single-line` prop, label is gone.

### Reproduction Link
<a href="https://codepen.io/0140454/pen/mdxePOw?editors=101" target="_blank">https://codepen.io/0140454/pen/mdxePOw?editors=101</a>

### Other comments
![image](https://user-images.githubusercontent.com/1191368/183939981-69093aef-6aa0-4980-b0d5-082ded292d24.png)

**Comment by KaelWD** [comment]
> It should be text ellipsis

Intentional, you can choose: #15521

> label is gone

I'm going to change how this works, follow #15610
