### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Typography transform helper classes getting wrong specificity

### ISSUE THREAD

**Issue by SkyaTura** [vuetifyjs/vuetify#15616]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Last working version:** 2.6.9
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.167
**OS:** Mac OS 10.15.7

### Steps to reproduce
Simply use both a typography helper (eg.: .text-h3) alongside a text transformer helper (eg.: .text-uppercase)

### Expected Behavior
`.text-uppercase` should have a higher priority than `.text-h3`

### Actual Behavior
The `text-transform` property is overwritten by the default transform set on `.text-h3`  should have a higher priority than `text-h3`

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-uppercase-helper-bug-reproduction-lk5w03?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-uppercase-helper-bug-reproduction-lk5w03?file=/src/App.vue</a>

### Other comments
The problem seems to be in the dynamic class builder, which defines the `.text-uppercase` before `.text-X` being imported.

**Comment by SkyaTura** [comment]
Question: Why does the `.text-hX` helpers have `!important` on the `text-transform:` anyway?

If set without `!important`, it would already overwrite inherited values without forcing the need for use important elsewhere

**Comment by KaelWD** [comment]
> Why does the .text-hX helpers have !important

Otherwise they can't reliably be used on components that might have more specific selectors. [Cascade layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) would fix that but don't have good enough browser support yet.
