### ISSUE TITLE
[Bug Report][3.0.0-beta.6] VSelect with no label should centered item value

### ISSUE THREAD

**Issue by trikarai** [vuetifyjs/vuetify#15610]
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Last working version:** 2.6.2
**Vue Version:** 3.2.29
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. VSelect no label 
2. select item
3. to much padding top

### Expected Behavior
item should align-center
 

### Actual Behavior
empty label make padding different on top and bottom

### Reproduction Link
<a href="https://codepen.io/trikarai/pen/rNdrGBR" target="_blank">https://codepen.io/trikarai/pen/rNdrGBR</a>

**Comment by KaelWD** [comment]
@johnleider this supports what I was saying about single-line being redundant when you can just use a placeholder, v2 used it if there was no label: https://github.com/vuetifyjs/vuetify/blob/6e3d83f24c15bf02e120e6ee1244018dfeb78c73/packages/vuetify/src/components/VTextField/VTextField.ts#L166-L174
