### ISSUE TITLE
[Bug Report][2.6.9] Dragged chips are with background corners 

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15628]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 103.0.5060.134
**OS:** Mac OS 10.15.7

### Steps to reproduce
drag the chip

### Expected Behavior
the dragged chip will appear

### Actual Behavior
white corners with outside shadow are visible

### Reproduction Link
<a href="https://codepen.io/gileneusz/pen/yLKxRbx?editors=101" target="_blank">https://codepen.io/gileneusz/pen/yLKxRbx?editors=101</a>

### Other comments
would be nice if there would be one more prop to hide the chip source that is being dragged.

**Comment by KaelWD** [comment]
> white corners with outside shadow are visible

Doesn't look like it's possible to change that

> hide the chip source that is being dragged

I don't think that needs to be built in
```js
onDragstart (e) {
  e.target.style.opacity = 0
},
onDragend (e) {
  e.target.style.opacity = null
},
```

**Comment by gileneusz** [comment]
@KaelWD for strange reason this works for me:

https://codepen.io/gileneusz/pen/yLKxRbx?editors=101

however I can't set 
```
onDragend (e) {
  e.target.style.opacity = null
},
```
because it's set on the target element, so it cannot apply directly to the chip being dragged (and trying to apply draggend directly to the chip is not working)
