### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Button outline let some traces after transition when inside navigation drawer

### ISSUE THREAD

**Issue by Zehir** [vuetifyjs/vuetify#15626]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
The easier way to reproduce is to click on A and then click outside the windows, after a few we can see a square box of white pixels around the circle.
This do happen on A with Chrome and Edge but not with Firefox.
This do not happen on B, never.

### Expected Behavior
Not having a white border when the button is a circle again.

### Actual Behavior
There is white dot around the circle in the shape of a square.

On the left it's on Chrome and on the right it's on Firefox.
![image](https://user-images.githubusercontent.com/845225/184331710-4001d2e3-f2ed-4c58-9f70-93c81aad5e89.png)

### Reproduction Link
<a href="https://codepen.io/zehir-the-selector/pen/MWVqXNM" target="_blank">https://codepen.io/zehir-the-selector/pen/MWVqXNM</a>

### Other comments
When trying alternative to figure out what causing that, I loaded older version of the css but not the js file (because it's look like an CSS issue) and got this:
JS beta.7 + CSS beta.7 issue
JS beta.7 + CSS beta.6 issue
JS beta.7 + CSS beta.5 (or lower) working fine
JS beta.5 + CSS beta.5 issue

Also this issue do not happen in Firefox, only on Chrome and Edge.

When resizing the windows left-right it's change nothing but resizing the windows top-bottom it's get fixed.

**Comment by KaelWD** [comment]
This should be reported to https://bugs.chromium.org/p/chromium/issues/list

**Comment by Zehir** [comment]
> This should be reported to https://bugs.chromium.org/p/chromium/issues/list

Ok ty i will do that. I was not sûre because it's dont happen on the B button

**Comment by KaelWD** [comment]
Yeah I can't reproduce it on linux and it definitely looks like some sort of GPU compositing artifact. 
Does it happen if you add `will:change: transform` to the card's css?

**Comment by Zehir** [comment]
No it's do not happen with `will-change: transform`

**Comment by Zehir** [comment]
I published the issue, if anybody come here because you have the same issue please upvote the issue on chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1353362
