### ISSUE TITLE
[Bug Report][2.6.9] v-calendar @dragend gives incorrect date

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15622]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 103.0.5060.134
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Drag the chip to any day.
2. dragOverTheDay shows correct date
3. dragEndTheDay shows incorrect date
4. dragEndTheDay does not recognise that the chip was dragged outside the calendar, still gives the wrong date

### Expected Behavior
1. correct date if dragged over the calendar date
2. undefined/false/empty if dragged outside the calendar

### Actual Behavior
incorrect dare

### Reproduction Link
<a href="https://codepen.io/gileneusz/pen/bGvxBEY" target="_blank">https://codepen.io/gileneusz/pen/bGvxBEY</a>

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/dragend_event - `event.target` is the element being dragged
https://developer.mozilla.org/en-US/docs/Web/API/Document/dragover_event - call `event.preventDefault` and listen for `drop`

> dragEndTheDay does not recognise that the chip was dragged outside the calendar

Again, it's bound the the element being dragged. You need to listen for dragover and drop on the target element as well.

**Comment by gileneusz** [comment]
@KaelWD well... the calendar is not recognising ```@drop``` prop
 
https://codepen.io/gileneusz/pen/bGvxBEY

**Comment by KaelWD** [comment]
`event.nativeEvent.preventDefault()` in `dragoverDay` if you want that day to be drop-on-able

**Comment by gileneusz** [comment]
I fixed it following your advice. Thank you, I'm so dumb.
