### ISSUE TITLE
v-date-picker and v-time-picker text not inverted for dark theme

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#1562]
### Steps to reproduce
Include `v-date-picker` and `v-time-picker` in a component with the `dark` theme set.

### Versions
0.15.0-beta.5

### What is expected ?
The pickers' text should be inverted (set to white)

### What is actually happening ?
The pickers' text color is unchganged

### Reproduction Link
https://codepen.io/wernerm/pen/OjdORX

**Comment by johnleider** [comment]
This has already been resolved today, ty.
