### ISSUE TITLE
[Bug Report][2.6.7] List item icon doesn't get disabled when list item is disabled

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#15624]
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.7.8
**Browsers:** Edge 104.0.1293.47
**OS:** Windows 10

### Steps to reproduce
Open the provided CodePen

### Expected Behavior
The list item icon should be disabled as well.

### Actual Behavior
The list item icon appears as if the item can still be used.

### Reproduction Link
<a href="https://codepen.io/DJSuper/pen/WNzgjqL" target="_blank">https://codepen.io/DJSuper/pen/WNzgjqL</a>

**Comment by Amibhalala** [comment]
#15834

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://play.vuetifyjs.com/#eNqlVMtu2zAQ/BWCPSQBTCmxCxQwHMM9pugfRD7QIhMz5QskJTsN9O9d6mFLspEIKE/k7nBmdrnS8wf+aW1SFhwv8SpwZSUNfJ1phFYlyaljcYtQLqn3jxlWR0KLYDLchBU9koNgYQ+pxf19E65v1/el8KE9nVcbJwLUhjnruOWaEZEbHbWYIHujeCfWrSCC5JD/ZfYa/eaCcTeG+GLXod4AtXk15lXyJDdqjBwtKfSfTwFMeLqTvG1Ls0YlntqISuKlCUtqY1nXGrEL+lLNi7/RuFdUymt2S+oE1QEggR/DNUSvgYrrgjBz0Je49SqtHYztp4MxOId779Y9cRtr5gUOcWDgMKBY+dwJ22D40RoXEOMvtJABfTQ0jAa6RLd36HGNbtsYFAEcfomezyZOqdMULNHNE8DQt4ebWT9ZUllA8mEQtM5YIBywnIbuCVoGbN3MDemq3qm//8TQ/Kqh+QRDzbT0/OTS+P83tLhqaDHBUG6kccBjnVDUvU9xsm131V29qeJItGOAZzh+ZD5580bDT6cWy3DufYZPr53hfQhgJU1zpgHJuBSlSzQPqbYqhd9VEC/vm0UyT+YpfJKhCxFJdz6pySLTNtMVCAoVx44oakeqTaJWbovOMDDF8xcWNgBLXaGDUBy+L1V7+f6jMdOLJ9wrsnPm4LkDlgy3nal1ouMJWl+VCxIX1CnoldwRB7PEXfxDTitpdG1Q1ih3UVr71BWuZri5B72vTePtP8FZ0JA=

@johnleider can you also please close https://github.com/vuetifyjs/vuetify/pull/15834 if you're happy to close this one
