### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Rounded circle smaller than 64px are oval

### ISSUE THREAD

**Issue by Zehir** [vuetifyjs/vuetify#15621]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a btn with the rounded="circle" prop and make it smaller than 64px
In the button add a text, for example one letter.
With the icon it's working fine.

### Expected Behavior
I expect that the button is a circle

### Actual Behavior
The button `B` is oval
![image](https://user-images.githubusercontent.com/845225/184122319-d9f8e719-9cc0-4806-bc4e-5f87d1441839.png)

### Reproduction Link
<a href="https://codepen.io/zehir-the-selector/pen/ExEeKgB" target="_blank">https://codepen.io/zehir-the-selector/pen/ExEeKgB</a>

**Comment by KaelWD** [comment]
`<v-btn icon>` implies `rounded="circle"` and removes the content padding.

**Comment by Zehir** [comment]
> `<v-btn icon>` implies `rounded="circle"` and removes the content padding, you can apply it without any value to use the default slot instead.

The issue is not with the icon but with a text content

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/yLKxOmm?editors=1010
