### ISSUE TITLE
[Bug Report][2.6.9] v-sparkline not showing after reload page

### ISSUE THREAD

**Issue by prabodhana** [vuetifyjs/vuetify#15634]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Firefox 103.0
**OS:** Ubuntu undefined

### Steps to reproduce
codepen attached

### Expected Behavior
Show full sparkline after reloading the page

### Actual Behavior
Only showing the labels only

### Reproduction Link
<a href="https://codepen.io/prabodhana/pen/JjLmoop" target="_blank">https://codepen.io/prabodhana/pen/JjLmoop</a>

### Other Comments
v-sparkline not showing after reload page. Only showing labels not line showing. But if change page using vue router its working only this happen reload the page. I'm using vuetify on nuxtjs.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
