### ISSUE TITLE
[Bug Report][2.6.9] v-chip close button is not dimmed by default

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15637]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 103.0.5060.134
**OS:** Mac OS 10.15.7

### Steps to reproduce
this is just a very minor detail

This used to work fine in v.1.5.24 - as you can check there:
https://codepen.io/pen?&editors=101

### Expected Behavior
close button should be dimmed by default, and brightened up after mouseover

### Actual Behavior
close button is not dimmed by default, but after mouseover 

### Reproduction Link
<a href="https://codepen.io/gileneusz/pen/WNzavEM?editors=101" target="_blank">https://codepen.io/gileneusz/pen/WNzavEM?editors=101</a>

**Comment by KaelWD** [comment]
This was an intentional design change.
