### ISSUE TITLE
[Bug Report][2.6.9] v-chip close button is too small

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15633]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 103.0.5060.134
**OS:** Mac OS 10.15.7

### Steps to reproduce
codepen attached

### Expected Behavior
v-chip close button should be larger for regular chip sizes

### Actual Behavior
v-chip close button is adjusted to x-small chip size, which is too small for other v-chip sizes.

### Reproduction Link
<a href="https://codepen.io/gileneusz/pen/ZExMdWE?editors=101" target="_blank">https://codepen.io/gileneusz/pen/ZExMdWE?editors=101</a>

### Other comments
For the default chip size and larger, the close button should be at the size of v-avatar icon

**Comment by KaelWD** [comment]
v3: https://codepen.io/kaelwd/pen/dymgyQm?editors=1000

18px is correct for the default size https://m3.material.io/components/chips/specs

**Comment by gileneusz** [comment]
you are right. It would be nice however if the size would be little bit bigger on default and larger sizes
