### ISSUE TITLE
[Bug Report][2.6.9] v-chip is going outside of given card area, close button is not visible as well

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#15631]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.8
**Browsers:** Chrome 103.0.5060.134
**OS:** Mac OS 10.15.7

### Steps to reproduce
as shown in the codepen

### Expected Behavior
v-chip will maintain given space
v-chip close button will be always visible

### Actual Behavior
v-chip is going outside of given card area, 
close button is not always visible 

### Reproduction Link
<a href="https://codepen.io/gileneusz/pen/GRxXajj?editors=101" target="_blank">https://codepen.io/gileneusz/pen/GRxXajj?editors=101</a>

### Other comments
critical issue for low-spaces chips, when you need close button be always visible, for example inside calendar days' view

**Comment by KaelWD** [comment]
> v-chip is going outside of given card area

Because you gave it a margin, chips have `max-width: 100%;` which doesn't include margins. 

> close button is not always visible

valid.

**Comment by yuwu9145** [comment]
This issue also happens to vuetify2: https://codepen.io/yuchaosydney/pen/yLjOrXj?editors=101

Before making any fix, just want to confirm should long text shown as `text-overflow: ellipsis` so it won't push close button outside container?

**Comment by gileneusz** [comment]
@KaelWD any updates on this minor bug?
