### ISSUE TITLE
[Feature Request] VDataTable should allow setting id for rows

### ISSUE THREAD

**Issue by NicoAiko** [vuetifyjs/vuetify#15649]
### Problem to solve
Currently you can only assign an id (HTML id) when using the item-slot.
But as that approach would require to recreate the whole row by oneself, that approach is (in my opinion) to be discouraged.
As we have the `itemClass` property, it would only make sense to also allow adding `id` (and also if possible other properties) to each row.

### Proposed solution
An approach similar to `itemClass` would be preferable. Although I'd like to suggest some minor changes.

Add the item's index to the parameters of the function. `itemClass` only gives the `item` but the `index` should be added as well (e.g. for creating ids like `row-${index}`)

Or add a function that allows setting multiple element properties at once.
e.g.
```ts
function itemProperties(item: unknown, index: number): Record<string, any> {
  // Check some item properties and other stuff
  return {
    id: `some-row-${index}`,
    class: 'some-class',
    'x-data-row': 'even-custom-properties',
  };
}
```

**Comment by KaelWD** [comment]
v3 has `itemProps`: #15079

**Comment by NicoAiko** [comment]
Will it be backported to v2.7? QoL updates (which I would consider this under) should make it to v2 as well in my opinion for those who can't yet upgrade to v3.

**Comment by KaelWD** [comment]
At some point probably.
