### ISSUE TITLE
[Bug Report][2.6.6] Combo box with empty list doens't show slots - with hide-no-data prop

### ISSUE THREAD

**Issue by AvinoamAlaluf** [vuetifyjs/vuetify#15642]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Use of combox with an empty list for items prop
2. Add any slot (i used #append-item)
3. Pass the hide-no-data prop (default false, but doesn't matter if you change to true - either way should be false in order to see the menu while the list is empty)
4. 
   4.1 When the list is empty - menu doesn't open and show the slots
   4.2 When the list has at least one item - menu opens and show the slots

### Expected Behavior
When the list is empty - menu should open and show the slots

### Actual Behavior
When the list is empty - menu doesn't open and show the slots

### Reproduction Link
<a href="https://codepen.io/AvinoamAlaluf/pen/wvmYNJJ?editors=101" target="_blank">https://codepen.io/AvinoamAlaluf/pen/wvmYNJJ?editors=101</a>

### Other comments
I need to use the combo box to be open and show slots while the list is empty of items - one of the slots is used to create an item for the list.
If there's a workaround for that please let me know, I thought of maybe passing one of the slots as a regular item that will be custom to that need, but I really don't like that idea and the way that it would behave since I will behave as a regular item and not a special action as I need it to be.
Thanks!

**Comment by KaelWD** [comment]
You need `:hideNoData="false"` and the `no-data` slot.

**Comment by AvinoamAlaluf** [comment]
is it possible to show the other slots (append-item) with the empty list without the no dats slot?
