### ISSUE TITLE
[Feature Request] Double Click on event of calendar

### ISSUE THREAD

**Issue by NguyenNamUET** [vuetifyjs/vuetify#15645]
### Problem to solve
So my team wants to recreate the Outlook/Team calendar which can enable double-click on an event to open another page/modal to view/edit/perform meeting action.
However, Vuetify calendar does not support double click on an event.
I proposed usage of context menu but our sponsors still insisted on using Vuetify calendar for their system integrity.

### Proposed solution
I suppose an double-click:event or double-click:date same as mousedown or click event.

**Comment by KaelWD** [comment]
`dblclick:event` should already work since v2.6.9
