### ISSUE TITLE
[Bug Report][3.0.0-beta.8] Margin-bottom on VInput is not set

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify#15648]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Vue Version:** 3.2.36
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Select version of vuetify in 3.0.0-beta 6 : the margin-bottom is present and this is no CSS messy between two VTextFields
- Select the Beta 7 or Beta 8 : The margin-bottom disapear and the label of the second VTextField and the int of the first VTextField touch each other

### Expected Behavior
Same as Beta 6

### Actual Behavior
The margin-bottom disapear and the label of the second VTextField and the int of the first VTextField touch each other

### Reproduction Link
<a href="https://codesandbox.io/s/modern-bird-5ysfst?file=/src/App.vue" target="_blank">https://codesandbox.io/s/modern-bird-5ysfst?file=/src/App.vue</a>

### Other comments
The bug appears in Beta 7 but exists in Beta 8. This is the `margin-bottom` of the `v-input__details` the problem

**Comment by KaelWD** [comment]
This was intentionally removed in d938634702d2dc5e5d43c166541110730db5a082, `<v-row dense>` will give you the same spacing as v2 without forcing a margin on every input component.
