### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Double line in v-select at zoom 150% (Only in windows Browsers)

### ISSUE THREAD

**Issue by massimiliano3100** [vuetifyjs/vuetify#15640]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.13
**Browsers:** Chrome 104.0.0.0
**OS:** Windows

### Steps to reproduce
1 -  Create a v-select with variant="underlined"
2 - zoom in page (Zoom >= 150)

### Expected Behavior
It should work as in the Vuetify samples when users also zoom in on the page

### Actual Behavior
when I use a V-Select (variant="underlined")  and zoom in page (Zoom >= 150) , a double line appears below my text.

### Reproduction Link
<a href="https://codepen.io/massimiliano3100/pen/mdxzzQR?editors=101" target="_blank">https://codepen.io/massimiliano3100/pen/mdxzzQR?editors=101</a>

### Other comments
The problem is when I use a V-Select (variant="underlined")  and zoom in page (Zoom >= 150) , a double line appears below my text.
It only happens with Windows browsers. I tested this on MacOs and it doesn't happen.
I also tested in Vuetfiy v-2.6.9, there are no these problems either. The problem only exists in Veutify 3.0.0-beta-7.

I saw in the console there is a div with the class "v-field-outline_notch" and I think the height of this div doesn't match with others.

**Comment by KaelWD** [comment]
Yeah this sort of thing has been around for ages: #3090

It has the same border width as all the other elements, I can't figure out why it looks different.
