### ISSUE TITLE
[feature request] Option to translate 'of' text in DataTable component.

### ISSUE THREAD

**Issue by nzxt** [vuetifyjs/vuetify#1564]
> - What will it allow you to do that you can't do today?

It'll allow to translate `'of'` text in pagination of `v-data-table` component. 

> - How will it make current work-arounds straightforward?

It'll simplify localization of user interface.

> - What potential bugs and edge cases does it help to avoid?

It'll help to avoid costs of manual translation.

**Comment by johnleider** [comment]
This can already be done, https://vuetifyjs.com/components/data-tables #5

**Comment by Soean** [comment]
See #1134
