### ISSUE TITLE
[Bug Report][3.0.0-beta.7] VSelect title and label stacked on on empty value object

### ISSUE THREAD

**Issue by trikarai** [vuetifyjs/vuetify#15644]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.30
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. VSelect
2. create object list with empty string value

### Expected Behavior
label not moving to center

### Actual Behavior
label and title stacked

### Reproduction Link
<a href="https://codepen.io/trikarai/pen/jOzQqZY" target="_blank">https://codepen.io/trikarai/pen/jOzQqZY</a>

### Other comments
i don't know if this related to #15610

**Comment by KaelWD** [comment]
Fixed by de15c896385b507e4d17d5ad9124cdd937c55a58
