### ISSUE TITLE
[Bug Report][3.0.0-beta.8] VOverlay should not block scroll by default when contained

### ISSUE THREAD

**Issue by SkyaTura** [vuetifyjs/vuetify#15653]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.167
**OS:** Mac OS 10.15.7

### Steps to reproduce
In a big and scrollable page, create a card with a contained overlay with v-hover, just like in the documented example, then, try to scroll normally then hover the card and try to scroll again.

### Expected Behavior
If the overlay is contained, it is expected that it won't block scrolling.

### Actual Behavior
The scroll strategy always defaults block no matter what.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-voverlay-scroll-unexpected-behavior-v62289?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-voverlay-scroll-unexpected-behavior-v62289?file=/src/App.vue</a>

**Comment by SkyaTura** [comment]
I've updated the reproduction link because apparently I forgot to save the final version of the file...

**Comment by nekosaur** [comment]
Use `scroll-strategy="none"`

**Comment by SkyaTura** [comment]
That works, but I think it should be default when `contained` is applied.

It seems counterintuitive for me that an overlay in a card would lock the entire screen if I don't explicit say so.

**Comment by KaelWD** [comment]
The default scroll-strategy should probably just be changed to none globally.

**Comment by Antti-Palola** [comment]
Is this more of a new ticket but feels related..? Should the overlay really block scrolling of every ancestor when contained?
When overlay is contained shouldn't the `getScrollParents` stop at first found scrollparent?

**Comment by SkyaTura** [comment]
> Is this more of a new ticket but feels related..? Should the overlay really block scrolling of every ancestor when contained and scrollStrategy is `block`?
> When overlay is contained shouldn't the `getScrollParents` stop at first found scrollparent?

Although is related to the same component and property, I think it should be a new issue, because is about behavior of the strategy itself, not about the default setting

**Comment by KaelWD** [comment]
Stopping at the first found parent would still be the window in that example

**Comment by furkancanzirek** [comment]
> Use `scroll-strategy="none"`

that's worked for me thank you.

**Comment by balaji-ksk** [comment]
> > Use `scroll-strategy="none"`
> 
> that's worked for me thank you.

That is also work for me. Use this on V-overlay
