### ISSUE TITLE
[Bug Report][3.0.0-beta.8] Transition-Group does not allow props hide-on-leave or leave-absolute nor do they work

### ISSUE THREAD

**Issue by skamansam** [vuetifyjs/vuetify#15656]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Last working version:** 2.6.8
**Vue Version:** 3.2.36
**Browsers:** Chrome 104.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Use a `transition-group` element with `hide-on-leave` and `leave-absolute`, with `name="slide-x-transition"` attributes
1. Toggle two elements inside that element

### Expected Behavior
The two elements should replace each other seamlessly.

### Actual Behavior
when toggled, there is no transition, the two elements appear together before the leaving one is removed.

### Reproduction Link
<a href="https://codepen.io/skamansam/pen/dymabZa" target="_blank">https://codepen.io/skamansam/pen/dymabZa</a>

### Other comments
This worked well in Vuetify 2.

**Comment by KaelWD** [comment]
transition-group is a Vue built-in component, those props only work if you use our v-slide-x-transition component instead.
