### ISSUE TITLE
[Bug Report][3.0.0-beta.8] @change not triggered in v-autocomplete

### ISSUE THREAD

**Issue by arcp10** [vuetifyjs/vuetify#15657]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Vue Version:** 3.2.37
**Browsers:** Edge 104.0.1293.54
**OS:** Windows 10

### Steps to reproduce
Change value in dropdown. @change event is not triggered

### Expected Behavior
trigger @change event on dropdown value change

### Actual Behavior
@change event not triggered

### Reproduction Link
<a href="https://codepen.io/arcp10/pen/MWVLoYV?editors=1010" target="_blank">https://codepen.io/arcp10/pen/MWVLoYV?editors=1010</a>

**Comment by KaelWD** [comment]
Duplicate of #15235
