### ISSUE TITLE
[Bug Report][3.0.0] VOverlay needs to separate notions of activator and location

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#15658]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Vue Version:** 3.2.29
**Browsers:** Chrome 102.0.5005.149
**OS:** Linux x86_64

### Problem
The 'activator' in V-overlay combines two different notions: that of activating and that of positioning when using location-strategy=connected. These two notions should be separate.

### Steps to reproduce
Open the codepen, try to edit the text in the text field, as soon as you do, the overlay pops up.

### Expected Behavior
The overlay should only activate when clicking the palette icon.

### Actual Behavior
The overlay also activates when one clicks inside the text field. If the overlay were any larger it would be impossible to edit the text field.

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/VwXgrLZ" target="_blank">https://codepen.io/codesurfr/pen/VwXgrLZ</a>

### Comment

The positioning of the overlay is still often messed-up and it zooms by going off-screen. If this happens, resizing the window "fixes" that... You can tell when the overlay is active from the scrim.

**Comment by nekosaur** [comment]
This seems more like a feature request than a bug. In the codepen you are using the entire v-text-field as the activator, which predictably will activate the overlay whenever any part of the input is clicked.

I think this might better illustrate your point https://codepen.io/nekosaur/pen/OJvqzKa

Here only the append inner icon is used as the activator, but that also means that with `overlay-strategy="connected"` the overlay will appear at the icon, not the input as a whole.

However there is a workaround. Replace `v-bind="props"` with `:ref="props.ref"`. That way you won't bind any of the mouse events that trigger the overlay. https://codepen.io/nekosaur/pen/VwXRQvQ?editors=1010

**Comment by tve** [comment]
Thanks for the workaround! I have to admit I don't really understand the stopPropagation and preventDefault stuff. I mean, I understand it on HTML input elements but in this example, which handler does stopPropagation not propagate to and why is a default handler relevant since I'm handling the event explicitly? Or am I not?

The result of your changes doesn't fully work for me. I [updated your codepen](https://codepen.io/codesurfr/pen/RwMdQvO) to update the modelValue but if I type in the text field it displays what I type, but the moment I click outside of the text field it reverts to the prior value.

**Comment by tve** [comment]
I have another use-case where I'm also running into this issue. I have a VCard that has an edit button:
![image](https://user-images.githubusercontent.com/39480/186966340-3d104500-9079-4283-a173-2e3012e564c1.png)

Hitting the edit button brings up a VOverlay edit panel below the VCard:
![image](https://user-images.githubusercontent.com/39480/186966577-325bc44f-59e8-4445-8a43-7ecedd979707.png)

I need to use `location-strategy="connected" location="bottom" origin="top"` to position the overlay. I can only do that by using the VCard as activator. I can handle the pencil edit button by managing VOverlay's model myself. But there is a ripple effect attached by VOverlay to the activator that happens every time I click anywhere in the VCard. The problem is that I need the positioning to be relative to one DOM element and the activator to be a different one. I can provide a CodePen if desired.

**Comment by tve** [comment]
I have another use-case where I'm also running into this issue. I have a VCard that has an edit button:
![image](https://user-images.githubusercontent.com/39480/187016047-885ca6ac-efd6-4608-bd14-ca4ed64fd275.png)

Hitting the edit button brings up a VOverlay edit panel below the VCard:
![image](https://user-images.githubusercontent.com/39480/187016058-57ec2237-1523-4510-a9eb-dff67c1c2251.png)

I need to use `location-strategy="connected" location="bottom" origin="top"` to position the overlay. I can only do that by using the VCard as activator. I can handle the pencil edit button by managing VOverlay's model myself. But there is a ripple effect attached by VOverlay to the activator that happens every time I click anywhere in the VCard. The problem is that I need the positioning to be relative to one DOM element and the activator to be a different one. I can provide a CodePen if desired.

Update: codepen https://codepen.io/codesurfr/pen/NWYVZpP

**Comment by johnleider** [comment]
I'm not sure the best course of action with this but I've assigned this to @KaelWD

**Comment by tve** [comment]
I updated the codepen to 3.0.0 release. The problem still occurs and has actually gotten worse. The codepen has a brief statement about what's going wrong.

**Comment by KaelWD** [comment]
- `update:modelValue` isn't a native event, so `.stop.prevent` won't work
- you can prevent the overlay from handling the click with `@click="$event.stopImmediatePropagation()" v-bind="props"`
- you can remove the ripple with `v-ripple="false"`

I do intend to add a separate `target` prop though.

**Comment by dagorod** [comment]
Any updates on position-x and position-y for the v-menu ?

**Comment by johnleider** [comment]
It's my understanding @KaelWD plans on adding that as part of 3.2 or 3.3. He'll have to confirm.
