### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Cannot use namespace 'ThemeDefinition' as a type when defining custom theme

### ISSUE THREAD

**Issue by dcb99** [vuetifyjs/vuetify#15651]
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Vue Version:** 3.2.13
**Browsers:** Firefox 103.0
**OS:** Mac OS 10.15

### Steps to reproduce
clone repo, npm run serve

### Expected Behavior
successful compilation

### Actual Behavior
compilation fails with error Cannot use namespace 'ThemeDefinition' as a type

### Reproduction Link
<a href="https://github.com/dcb99/vuetify-theme-demo" target="_blank">https://github.com/dcb99/vuetify-theme-demo</a>

**Comment by KaelWD** [comment]
Remove `shims-vuetify.d.ts`
