### ISSUE TITLE
[Bug Report][3.0.0-beta.8] readonly don't work with VSelect, VCombobox and VAutocomplete

### ISSUE THREAD

**Issue by SkyaTura** [vuetifyjs/vuetify#15655]
### Environment
**Vuetify Version:** 3.0.0-beta.8
**Last working version:** 2.6.9
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.167
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create any of the mentioned components and set `readonly` property.

### Expected Behavior
Neither of those components should allow changing their values anyhow.

### Actual Behavior
All of them allows to change the value through the selection menu.
The `readonly` property is only affecting the text input part of VCombobox and VAutocomplete.
VSelect isn't affected anyway.

### Reproduction Link
<a href="https://codesandbox.io/s/q4m079?file=/src/App.vue" target="_blank">https://codesandbox.io/s/q4m079?file=/src/App.vue</a>

**Comment by trikarai** [comment]
confirmed have the same issue..

**Comment by SkyaTura** [comment]
There is anyone working on this issue already? May I help somehow?
