### ISSUE TITLE
Can't grab the value from a v-select on serverside. Always null

### ISSUE THREAD

**Issue by Fiiinetastic** [vuetifyjs/vuetify#1565]
###

In a application, a user can select from different options. I'm using the example from the following code:

But in my case, I slightly modifed the example, so I can use it as a component.

I wrapped it in a simple form and I'm sending it to my webserver (Laravel 5.5). 

### Steps to reproduce
The regular v-inputs work perfectly, but in the case of v-select, no data is being send to the server.

Then I inspected the DOM and found out, that the v-select consists of a input field behind the scenes. But for some reason the input field is disabled in the DOM. On purpose?

Any help is appreciated. I spent half of the day googling for the reason, why I don't receive the data from the v-select fields.

### Versions

0.15.0-beta.5

### What is expected ?
I'd like to send some data from my vue.component, which consists of some v-selects as well as some v-text-fields to my server and process the data. 

### What is actually happening ?

As described above. Data is not being sent from v-select.

### Reproduction Link
https://codepen.io/Fiiinetastic/pen/brzMeK

**Comment by johnleider** [comment]
I cannot see anything on the codepen.

**Comment by Fiiinetastic** [comment]
Hello johnleider, 

apparently I didnt confirm the e-mail address.  
Should be working now:

https://codepen.io/Fiiinetastic/pen/RZvyog

Basically it's close to an example, which you posted here on github ( https://codepen.io/johnjleider/pen/jwoNrG )

In my case, I just wrapped a form around it and tried to submit the data.

**Comment by Fiiinetastic** [comment]
![disabled](https://user-images.githubusercontent.com/28737966/29994976-ef315a60-8fdd-11e7-8fe0-31d6b287bdf2.png)

I also attached a screenshot, where I inspected the <v-select>
From what I know, values from disabled input fields are not transmitted.

When I submit the form via axios to my nginx server, then all the data is transmitted. 
But I can't use axios in my project or any other ajax functionalities.

**Comment by Fiiinetastic** [comment]
In my last reply, I stated, that I can transmit the form data, even the select field via ajax.
This lead me to the assumption, that it's a vue specific thing (correct me, if I'm wrong), and that a v-select never transmits any data, when I press the submit button with form method post and an action.

My solution was now the following:

`<input type="hidden" name="wechselart" :value="wechselart">`

Is it true, that it's a vue specifc thing?

**Comment by johnleider** [comment]
That would be correct. The select doesn't natively keep any data that can be submit through a form by regular means. It's expected that you would build your dataset from your form elements and submit that yourself. The input exists primarily for **autocomplete** and **editable** prop ```v-select```s.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
