### ISSUE TITLE
[Bug Report][2.6.9] Accessibility issue with pager controls in DataTable component

### ISSUE THREAD

**Issue by speedsticko** [vuetifyjs/vuetify#15674]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.10
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
Using an accessibility checking tool such as axe you can see that an issue "Interactive controls must not be nested" is identified with the row pager control because the element: 
<div role="button" aria-haspopup="listbox" aria-expanded="false" aria-owns="list-13" class="v-input__slot">
has a focusable descendent (a Select list control).

### Expected Behavior
No accessibility issue flagged by Axe

### Actual Behavior
Accessibility issue is flagged by Axe

### Reproduction Link
<a href="https://codepen.io/ppc-coder/pen/ExEJKWZ" target="_blank">https://codepen.io/ppc-coder/pen/ExEJKWZ</a>

**Comment by lioneaglesolutions** [comment]
This seems to be resolved in V3 but please re-open an issue if it happens again in V3 data-table
