### ISSUE TITLE
[Bug Report][3.0.0-beta.9] Blank page on iPhone 6 (IOS 12.5.5)

### ISSUE THREAD

**Issue by jaromanda** [vuetifyjs/vuetify#15687]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Create a vue 3.x app - page shown
Use vuetify 3.0 <v-app> ... blank page shown

### Expected Behavior
Content shown

### Actual Behavior
No content

### Reproduction Link
<a href="https://codepen.io/jaromanda/pen/abYrdwg" target="_blank">https://codepen.io/jaromanda/pen/abYrdwg</a>

### Other comments
According to the vuetify next documentation, IOS 12 is supported

I've tried adding legacy polyfills, but that did nothing

I'd love to try and debug this for myself, but I have no way of debugging an IPhone 6

Vuetify (next) works 100% on iPhone 7 (IOS 13) and above 

While I flagged this with the beta.9 tag, iPhone 6 has displayed blank since at least beta.6 as far as I know

**Comment by KaelWD** [comment]
Minimum is 13.7

**Comment by jaromanda** [comment]
> Minimum is 13.7. 

Perhaps the documentation needs updating them. Can't believe the tome I've wasted because of poor documentation

**Comment by KaelWD** [comment]
There is a banner at the top of every page saying "examples and information may be broken or outdated". 

I think you need ResizeObserver, Object.fromEntries, and Array.at

**Comment by jaromanda** [comment]
> There is a banner at the top of every page saying "examples and information may be broken or outdated".
> 
> I think you need ResizeObserver, Object.fromEntries, and Array.at

I have read that banner. Sorry for the outburst

I take it there polyfills readily available for those

**Comment by jaromanda** [comment]
Those doc updates helped a lot - I can get the core Vuetify app displaying now! My app still breaks, but it is now unlikely to be related to Vuetify - thanks for the support!
