### ISSUE TITLE
[Bug Report][3.0.0-beta.9] `v-radio` label slot demo broke

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15680]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
just follow the code pen

### Expected Behavior
It should be work properly

### Actual Behavior
label is not propely align to properly.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/YzaMLRZ?editors=101" target="_blank">https://codepen.io/Alokdev/pen/YzaMLRZ?editors=101</a>

**Comment by MRR0GERS** [comment]
@alokVishu can you please elaborate?  This looks to be working as designed.

**Comment by alokVishu** [comment]
Hello @MRR0GERS,

I think the radio label should be aligned on top of the label.
![image](https://user-images.githubusercontent.com/80033712/187128151-6d5cb314-97fe-4d18-9be3-bfeb02245490.png)

Just like vuetify 2:
![image](https://user-images.githubusercontent.com/80033712/187128232-ef8dbe6b-5f04-47a7-a52a-8f742ad7f03b.png)

**Comment by KaelWD** [comment]
Should `inline` look like this
![Screenshot_20220908_013216](https://user-images.githubusercontent.com/16421948/188919371-66757453-cfb8-4339-831b-8e3d79108951.png)
or this?
![Screenshot_20220908_013238](https://user-images.githubusercontent.com/16421948/188919405-5c18086d-9014-4eb8-89d1-d52fe5216cdf.png)
