### ISSUE TITLE
[Documentation] Location prop incorrectly labeled on v-navigation-drawer

### ISSUE THREAD

**Issue by Kelvination** [vuetifyjs/vuetify#15685]
### Environment

**Browsers:** Chrome 104.0.0.0
**OS:** Windows

### Steps to reproduce
When looking at the code example for "Location", it is saying to use the "location" prop to attach it to the right side. But it should be using the "position" prop instead

### Expected Behavior
position="right"
Works as intended

### Actual Behavior
location="right"
Stays on the left

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/navigation-drawers/#location" target="_blank">https://next.vuetifyjs.com/en/components/navigation-drawers/#location</a>

**Comment by nekosaur** [comment]
`location` is correct.
