### ISSUE TITLE
[Bug Report][2.6.9] v-autocomplete focus issue with virtual keyboard

### ISSUE THREAD

**Issue by ledach09** [vuetifyjs/vuetify#15689]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.5
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Just add basic autocomplete component and try to type a text using chrome virtual keyboard

### Expected Behavior
the autocomplete component must save the focus and typed text should appear, same as on v-text-field component

### Actual Behavior
the text does not appear and the component loses focus.

### Reproduction Link
<a href="https://codepen.io/ledach/pen/MWVdbmW" target="_blank">https://codepen.io/ledach/pen/MWVdbmW</a>

**Comment by KaelWD** [comment]
> chrome virtual keyboard

what is this

**Comment by ledach09** [comment]
it's an extension in google chrome browser to simulate on-screen keyboard

**Comment by KaelWD** [comment]
That's not properly stopping click events then, nothing we can do.

**Comment by ledach09** [comment]
Same bug with the v-combobox component. On the other hand, no problem with a v-text-field, it does not lose focus when typing with a virtual keyboard.
