### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-autocomplete behavior issues

### ISSUE THREAD

**Issue by terziani** [vuetifyjs/vuetify#15693]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Browsers:** Firefox 103.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Autocomplete component behavior issues can be reproduced as follows:

1. Select any value then blur the component. 
2. Open the content list then blur it closed. Open it again.

### Expected Behavior
1. Label remains positioned above the selected value text.
2. The content list, when opened, remains anchored on the text field element.

### Actual Behavior
1. Label falls over selected value on blur.
2. The content list, after clicking it open once, does not anchor on the text field element on subsequent openings. Rather it expands to the top and bottom of the viewport.

### Reproduction Link
<a href="https://codepen.io/terziani/pen/oNqRdvR" target="_blank">https://codepen.io/terziani/pen/oNqRdvR</a>

**Comment by MRR0GERS** [comment]
@terziani you need to define a v-model to bind to.

**Comment by terziani** [comment]
That does mitigate the label overlapping the selected value. Still seeing the unmoored modal style option list (for longer lists) *after* the first time opening it.
