### ISSUE TITLE
[Bug Report][3.0.0-beta.9] the last child(`timeline-item`)'s padding should be removed when you set `truncate-line="both"`

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15695]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to put `truncate-line="both"` in timeline.

### Expected Behavior
Last child padding should be removed 

### Actual Behavior
There is extra padding in the last child.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/YzaMjEb?editors=101" target="_blank">https://codepen.io/Alokdev/pen/YzaMjEb?editors=101</a>
![image](https://user-images.githubusercontent.com/80033712/186913297-342479d4-c5f3-417e-9afa-03f874c61043.png)

**Comment by MRR0GERS** [comment]
@alokVishu the code in the codepen doesn't match your screenshot.  However, it looks as if you have a timeline within a card and thus the padding would be from the card and not the timeline.  Adding a `class="pb-0"` (or however much padding you want) to the card/card-text component tag should fix your issue.

**Comment by alokVishu** [comment]
@MRR0GERS  Okay

**Comment by KaelWD** [comment]
@MRR0GERS `.v-timeline-item__body` also has padding
