### ISSUE TITLE
the 7th example of navigation drawer is incorrect

### ISSUE THREAD

**Issue by wi-cuckoo** [vuetifyjs/vuetify#1569]
### Versions 
0.15

### What is expected ?
correct the doc

### What is actually happening ?
I copy the example code, but the effect no as same as doc shows

**Comment by johnleider** [comment]
I have tested this and everything works as expected. Couple points:

When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by wi-cuckoo** [comment]
Sorry for that. But it's really weird. I just can't describe what I encountered. But now I run it OK
