### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-menu console warning

### ISSUE THREAD

**Issue by SaberD** [vuetifyjs/vuetify#15696]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Browsers:** Firefox 103.0
**OS:** Linux x86_64

### Steps to reproduce
Open console: ctrl + shift + i
Click the button to activate the menu.

### Expected Behavior
no console warning

### Actual Behavior
Keyframe property value “” is invalid according to the syntax for “transform”.

### Reproduction Link
<a href="https://codepen.io/saberd/pen/eYMaxoZ" target="_blank">https://codepen.io/saberd/pen/eYMaxoZ</a>

### Other comments
same issue on buttons on the examples: https://next.vuetifyjs.com/en/components/menus/

**Comment by masteredward** [comment]
@SaberD I can confirm that I have the same problem here!
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.37
**Vite Version:** 3.0.9
**Browser: Firefox:** 103.0.2
**OS: Manjaro Linux aarch64**

Although, in Microsoft Edge 104.0.1293.63, with same setup as above, there is no such warning.

**Comment by KaelWD** [comment]
I guess firefox is wrong? `null` or `undefined` show the same warning in chrome and firefox, and omitting the empty keyframe breaks the animation.

**Comment by dimmaski** [comment]
Having the same issue on 
firefox 1.106.3
vuetify 3.0.2
vite 3.2.4
Os: Ubuntu 22.04, on chrome works fine
