### ISSUE TITLE
[Bug Report][3.0.0-beta.9] VTextField and VSelect fail to apply color prop

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#15697]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.36
**Browsers:** Chrome 104.0.5112.105
**OS:** Linux x86_64

### Steps to reproduce
See attached codepen, neither the VSelect field nor the VTextField have a color.

### Expected Behavior
Both fields should be colored similar to the way buttons are colored.

### Actual Behavior
The fields remain white.

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/GRxLZMw" target="_blank">https://codepen.io/codesurfr/pen/GRxLZMw</a>

### Other comments
The VTextField docs have a "custom-colors" section that also shows no color. Dunno whether that's supposed to be up-to-date or not, prob. not. https://next.vuetifyjs.com/en/components/text-fields/#custom-colors

**Comment by MRR0GERS** [comment]
@tve they are working as designed.  The color attribute colors the labels for the elements when the inputs are in focus, not the inputs themselves.

**Comment by tve** [comment]
Ok, you mean the little "item" being in red when in focus? That's disappointing... Any way to make the field colored?
Also, the VTextField doesn't show any color that I can see.
But if it's "as designed" then perhaps this is an enhancement request to be able to color the background?
I guess it largely comes down to whether VSelect should be able to look like VButton outside of forms or whether it's just a form field component...

**Comment by MRR0GERS** [comment]
@tve correct, you wouldn't see a color on the text field as you have it written as you didn't define a label; it's the label that gets the color.

As far as coloring the input itself, you can color the input by putting it in a wrapper such as a v-col/div/section/etc and adding the color as a class to the wrapper.

**Comment by KaelWD** [comment]
It has a bgColor prop.

**Comment by tve** [comment]
Yikes, yes! Thanks a million for posting this.
Comes from VField's makeVFieldProps called by VTextField resulting in bgColor prop on the VTextField and applied to it due to being unused in VSelect. I had looked into the source but tracing something like this when you're not sure what exactly you're looking for is almost impossible.
