### ISSUE TITLE
[Bug Report][2.6.9] V-Autocomplete runs filter function for each of the items when it should be the default filter function

### ISSUE THREAD

**Issue by RostamMahabadi480** [vuetifyjs/vuetify#15704]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.10
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-autocomplete with a filter check with the given variables (item, queryText, and itemText)
Console.log something within that function

### Expected Behavior
We should be able to write our own filter function which iterates a single time instead of iterating over each item then applying the function on every item

### Actual Behavior
It filters then applies the function to each item that it iterates over

### Reproduction Link
<a href="https://codepen.io/Rostamm/pen/qBozoRV?editors=1111" target="_blank">https://codepen.io/Rostamm/pen/qBozoRV?editors=1111</a>

### Other comments
```
filteredItems (): object[] {
      if (!this.isSearching || this.noFilter || this.internalSearch == null) return this.allItems

      return this.allItems.filter(item => {
        const value = getPropertyFromItem(item, this.itemText)
        const text = value != null ? String(value) : ''

        return this.filter(item, String(this.internalSearch), text)
      })
    },
```
Change this to check if there's a filter function that's written then apply it to all items

**Comment by KaelWD** [comment]
- This isn't a bug
- We can't change that without breaking for everyone who's already using it
- If you want more custom filtering set `no-filter` and do the filtering yourself externally
