### ISSUE TITLE
[Bug Report][2.6.9] `v-select`: `<v-select @click.stop>` blocks `click` event on `v-select`'s input element

### ISSUE THREAD

**Issue by simon-ricketts** [vuetifyjs/vuetify#15726]
### Environment
**Vuetify Version:** 2.6.9
**Last working version:** 2.6.6
**Vue Version:** 2.6.12
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set `@click.stop` in `<v-select>`

### Expected Behavior
When clicking `<v-select>`'s input element, a dropdown will display and the `click` event will not propagate higher.

### Actual Behavior
The `click` event does not emit on `v-select`'s input element and as a result, no dropdown displays on click, only on the input's appended elements (Underline and dropdown icon)

### Reproduction Link
<a href="https://codepen.io/simoniscoding/pen/vYjBwGY" target="_blank">https://codepen.io/simoniscoding/pen/vYjBwGY</a>

### Other comments
Removing `pointer-events: none` from `v-select.text-field input` seems to have caused this ([commit](https://github.com/vuetifyjs/vuetify/commit/760490da75fc531fca9edcd4ef308f2698ba02aa#diff-f95fc34d57c3b6502028a8045b08af7125d0d2f8a87788d77a2db18673cb91cdL66)), adding this property back reverts functionality to expected.

**Comment by simon-ricketts** [comment]
I have checked to see whether this bug also exists on `3.0.0-beta.10` (as per instructions within the issue creator) which it doesn't, though this is due to `click.stop()` not functioning at all there: https://github.com/vuetifyjs/vuetify/issues/15727

**Comment by KaelWD** [comment]
These both have the same cause: all events listeners are passed through to `<input>`
Workaround is `@click.native.stop` instead so it's applied to the root element
