### ISSUE TITLE
[Feature Request] Add nudge related props to VMenu

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15725]
### Problem to solve
It adds some gap between activator & menu content

### Proposed solution
Nudge props like v2: https://vuetifyjs.com/en/api/v-menu/#props

**Comment by KaelWD** [comment]
Duplicate of #14451

**Comment by jd-solanki** [comment]
Oh, sorry for the duplicate issue.

But this is not documented, moreover I also checked the source [code](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VMenu/VMenu.tsx) but there is nothing like `offset` but still it works magically 🪄

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VMenu/VMenu.tsx#L102
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VOverlay/VOverlay.tsx#L112
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VOverlay/locationStrategies.ts#L69
