### ISSUE TITLE
[Bug Report][2.6.9] Custom icons not working

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#15723]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.10
**Browsers:** Chrome 104.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a custom icon exactly as specified in the doc : https://vuetifyjs.com/en/features/icon-fonts/#using-custom-icons

```js
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import myIconSvg from 'myIcon.svg'

Vue.use(Vuetify)

export default new Vuetify({
  icons: {
    iconfont: 'fa',
    values: {
      customIconSvg: myIconSvg,
      customIconSvgPath: 'M14.989,9.491L6.071,0.537C5.78,0.246,5.308,0.244,5.017,0.535c-0.294,0.29-0.294,0.763-0.003,1.054l8.394,8.428L5.014,18.41c-0.291,0.291-0.291,0.763,0,1.054c0.146,0.146,0.335,0.218,0.527,0.218c0.19,0,0.382-0.073,0.527-0.218l8.918-8.919C15.277,10.254,15.277,9.784,14.989,9.491z',
    },
  },
})
```

### Expected Behavior
`<v-icon>customIconSvgPath</v-icon>` to render an icon.

### Actual Behavior
Icon is not rendered.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/wvjwxgE" target="_blank">https://codepen.io/thomaskientz/pen/wvjwxgE</a>

**Comment by KaelWD** [comment]
`<v-icon>$customIconSvgPath</v-icon>`
