### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-img inside v-expansion-panel errors

### ISSUE THREAD

**Issue by ECrownofFire** [vuetifyjs/vuetify#15724]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.38
**Browsers:** Firefox 104.0
**OS:** Linux x86_64

### Steps to reproduce
Open and close the expansion panel a few times (usually only twice) until it freezes.

### Expected Behavior
The expansion panel should not freeze

### Actual Behavior
The expansion panel errors and freezes

### Reproduction Link
<a href="https://codepen.io/ECrownofFire/pen/MWGgqMr" target="_blank">https://codepen.io/ECrownofFire/pen/MWGgqMr</a>

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/6573

**Comment by krausvo1** [comment]
Not sure how legit this is, but workaround that has worked for me was adding `lazy-src` with the same image as in `src` to `<v-img>` (+ `:transition="false"` to get rid of unwanted transition).

**Comment by Vincebe** [comment]
Another pen with a single `v-img` (no expansion panel here) freezing when updating src.

https://codepen.io/vincebe/pen/LYmVzXq?editors=1111

**Comment by KaelWD** [comment]
That works fine in the playground too.

**Comment by AlvaroBrasilia** [comment]
Same issue here.
Does anyone have any solution?

**Comment by tsekka** [comment]
> Same issue here. Does anyone have any solution?

Me too, (krausvo1)[https://github.com/vuetifyjs/vuetify/issues/15724#issuecomment-1235452046] solution helps.
