### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-slot:item in v-autocomplete doesn't work correctly

### ISSUE THREAD

**Issue by ppyl-datBoi** [vuetifyjs/vuetify#15722]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.38
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
Remove :title prop in v-list-item.

I looked at performance using an example from your demo. In the template v-slot:item in the v-list-item component, I want to use my content without using the :title prop.

### Expected Behavior
Correct display of my content, as it was in Vuetify 2.X

### Actual Behavior
endless console warnings
![image](https://user-images.githubusercontent.com/43649920/187867392-267521bf-124c-436d-9434-e97c29aaf844.png)

### Reproduction Link
<a href="https://codepen.io/ppyl-datboi/pen/dyebexE?editors=1010" target="_blank">https://codepen.io/ppyl-datboi/pen/dyebexE?editors=1010</a>

**Comment by KaelWD** [comment]
This has the same cause as #15721
