### ISSUE TITLE
[Bug Report][3.0.0-beta.10] align-center not working

### ISSUE THREAD

**Issue by raulpenate** [vuetifyjs/vuetify#15733]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Google Chrome
**OS:** Linux x86_64

## Steps:
```
//selecting Vue and Typescript
yarn create vite

cd project 

vue add vuetify

yarn && yarn dev
```
And adding class="d-flex align-center" to a tag.

```

<template>
  <v-app>
    <!-- This align should be working -->
    <v-container class="d-flex align-center" fill-height fluid>
      <!-- This align should be working -->
      <v-col>
        <v-row class="d-flex justify-center mb-6">
          <h1>Counter <v-icon>mdi-clock-outline</v-icon></h1>
        </v-row>
        <v-row class="d-flex justify-center mb-6">
          <h2>0</h2>
        </v-row>
        <v-row class="d-flex justify-center mb-6">
          <v-btn class="mx-5" icon>
            <v-icon>mdi-plus</v-icon>
          </v-btn>
          <v-btn class="mx-5" icon>
            <v-icon>mdi-minus</v-icon>
          </v-btn>
        </v-row>
      </v-col>
    </v-container>
  </v-app>
</template>
```

### Expected Behavior
align-center should be aligning center
![Expected contador](https://raw.githubusercontent.com/raulpenate/align-center-bug/main/src/assets/Counter2.png)

### Actual Behavior
Aligns are not working
![Result contador](https://raw.githubusercontent.com/raulpenate/align-center-bug/main/src/assets/Counter1.png)
The code is in App.vue

### Reproduction Link
<a href="https://github.com/raulpenate/align-center-bug" target="_blank">https://github.com/raulpenate/align-center-bug</a>

### Other comments
The same code works in codepen, but it doesn't in any project that I create.
Codepen code: https://codepen.io/raulpenate/pen/XWqWxWZ
I'm using  VITE v3.0.9 and yarn 1.22.19
Default CSS and the component Hello-world was removed to make the project simplier.

**Comment by raulpenate** [comment]
Here another example where it doesn't work:
https://codepen.io/raulpenate/pen/bGMGOMG

**Comment by KaelWD** [comment]
`fill-height` doesn't exist, it's `class="h-100"`

**Comment by raulpenate** [comment]
Thanks @KaelWD, also `fill-height` is in the current documentation of Vuetify 3, in case you want let people in charge of that is outdated, have a nice day.

[https://next.vuetifyjs.com/en/components/grids/#helper-classes](documentation)
