### ISSUE TITLE
[Bug Report][3.0.0-beta.10] scroll directive not working

### ISSUE THREAD

**Issue by ThisIsLamer** [vuetifyjs/vuetify#15736]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
You can reproduce this problem through the official documentation: https://next.vuetifyjs.com/en/directives/scroll/

It is also possible to reproduce the problem in the sandbox prepared by me, for this, just click on the "scroll" button

### Expected Behavior
It is expected that scrolling will occur according to the selected parameters.

### Actual Behavior
When clicking on a button with an attached click event and a goTo method, an error appears in the console: TypeError: t.$vuetify.goTo is not a function

### Reproduction Link
<a href="https://codesandbox.io/s/sad-rain-65p6sd?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/sad-rain-65p6sd?file=/src/components/HelloWorld.vue</a>

**Comment by johnleider** [comment]
goTo has not been implemented in v3 yet. Watch https://github.com/vuetifyjs/vuetify/issues/13538 for future updates.
