### ISSUE TITLE
[Bug Report][3.0.0-beta.10] `v-select`'s label get active always

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15730]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to use blank string `v-model` value and you see the label get an active state

```
 data: () => ({
    items: ['Foo', 'Bar', 'Fizz', 'Buzz'],
    standardSelect: '',
    outlinedSelect:'',
    soloVariant:'',
    plainVariant:'',
    underlinedVariant:'',
  }),
```

### Expected Behavior
v-select does not get an active state

### Actual Behavior
Refer to code pen for details 

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/wvjvgLN?editors=1010" target="_blank">https://codepen.io/Alokdev/pen/wvjvgLN?editors=1010</a>

**Comment by alokVishu** [comment]
Hello @KaelWD,

In Vuetify 2, Select does not behave the same when I use a blank string as model value: https://codepen.io/Alokdev/pen/gOzbzOz?editors=101

**Comment by KaelWD** [comment]
Sorry, power outage deleted my response. 

v3 keeps items defined in the model (#4000), so this is more like https://codepen.io/kaelwd/pen/jOxExrj?editors=1010
An initial value of `null` has the behaviour you want.

**Comment by alokVishu** [comment]
Thanks for the response.

Now, we are using null for the initial value.
