### ISSUE TITLE
[Bug Report][2.6.9] Hi! When I try to make bottom-sheet with open-on-hover bottom-sheet pops-up without stop (continiously)

### ISSUE THREAD

**Issue by MayaElf** [vuetifyjs/vuetify#15738]
### Environment
**Vuetify Version:** 2.6.9
**Last working version:** 2.6.9
**Vue Version:** 2.7.5
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
1) in code <v-bottom-sheet
        open-on-hover
        
      >
2. push the button
3. you see continious actions of bottom-sheet

### Expected Behavior
bottom-sheet pops-up and stays

### Actual Behavior
continious actions of bottom-sheet (it's blinking practically)

### Reproduction Link
<a href="https://codepen.io/MaiiaAfanaseva/pen/MWGYGaW?editors=101" target="_blank">https://codepen.io/MaiiaAfanaseva/pen/MWGYGaW?editors=101</a>

### Other comments
could you please get in touch with me when you fix it? i need it asap. thanls in advance!

**Comment by KaelWD** [comment]
This probably won't be fixed in vuetify 2

**Comment by MayaElf** [comment]
@KaelWD Hi Kael, sorry to disturb. Did I get you right that it will be fixed in next release, vuetify 3? Thanks in advance!
