### ISSUE TITLE
[Bug Report][3.0.0-beta.10] size not working for v-rating

### ISSUE THREAD

**Issue by LeoTuet** [vuetifyjs/vuetify#15746]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 104.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Add the `size` prop to the `Rating` component and set it to any numeric string value.

### Expected Behavior
The stars of the `Rating` component adapt to the set size.

### Actual Behavior
The stars format to a fixed size with no spacing whatsoever.

### Reproduction Link
<a href="https://codepen.io/leotuet/pen/bGMVYqg?editors=101" target="_blank">https://codepen.io/leotuet/pen/bGMVYqg?editors=101</a>

**Comment by KaelWD** [comment]
Buttons and chips have some pretty complex css to generate the correct sizes: https://github.com/vuetifyjs/vuetify/blob/7fe2e2671f44002d43384d74d3aaaf38610eb72c/packages/vuetify/src/components/VChip/_mixins.scss#L8-L85

I've made buttons work with just a basic width/height for now, but that needs to be refactored to be based off a single value to be able to set font size too.

**Comment by KaelWD** [comment]
Follow #15515 for that.
