### ISSUE TITLE
[Bug Report][2.6.9]  v-text-field   bug

### ISSUE THREAD

**Issue by guda-art** [vuetifyjs/vuetify#15749]
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.7.6
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
当 v-text-field使用v-bind:value="someValue"(初始值someValue=1) , @change="fn" (  fn(val) {++val}  ); 如果输入1等于初始值, 页面不会改变; 如果输入2页面会改变为3

### Expected Behavior
like v-model  work

### Actual Behavior
no

### Reproduction Link
<a href="https://codesandbox.io/s/vue" target="_blank">https://codesandbox.io/s/vue</a>

### Other comments
nothing

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
