### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-autocomplete - selection slot isn't rendering right after selecting item

### ISSUE THREAD

**Issue by kony97** [vuetifyjs/vuetify#15756]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.2.34
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
select item from v-autocomplete component

### Expected Behavior
selection slot is rendered

### Actual Behavior
item-title is rendered

### Reproduction Link
<a href="https://codepen.io/kony97/pen/xxjwWQo" target="_blank">https://codepen.io/kony97/pen/xxjwWQo</a>

**Comment by qxygene** [comment]
this issue still not fixed, nightly build has the same.
