### ISSUE TITLE
[Bug Report][3.0.0-beta.10] Can't render <v-snackbar> inside a component

### ISSUE THREAD

**Issue by ppyl-datBoi** [vuetifyjs/vuetify#15758]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
In Vuetify 2.X, I could render a snackbar inside a component by simply adding the "absolute" property. But right now, whatever I do, the snackbar is positioned relative to the entire application.

### Expected Behavior
 Render <v-snackbar> inside a component.

### Actual Behavior
The <v-snackbar> is positioned relative to the entire application.

### Reproduction Link
<a href="https://codepen.io/ppyl-datboi/pen/zYjrPJm?editors=101" target="_blank">https://codepen.io/ppyl-datboi/pen/zYjrPJm?editors=101</a>

**Comment by KaelWD** [comment]
1. The desired parent element needs `position: relative`
2. v3's snackbar is implemented with VOverlay, so you need to add `contained` to prevent it from teleporting.

**Comment by ppyl-datBoi** [comment]
> 1. The desired parent element needs `position: relative`
> 2. v3's snackbar is implemented with VOverlay, so you need to add `contained` to prevent it from teleporting.

I'm sorry, but could you show a live example? Based on your description, I was unable to get the snackbar to work correctly.

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/KKRMbmv?editors=1010

**Comment by ppyl-datBoi** [comment]
> https://codepen.io/kaelwd/pen/KKRMbmv?editors=1010

Thanks. It works.

**Comment by qxygene** [comment]
this is an ugly hack, please provide a prop > app for v3 as it is at https://vuetifyjs.com/en/api/v-snackbar/#props-app
