### ISSUE TITLE
[Bug Report][3.0.0-beta.10] Validation rules not working for v-select

### ISSUE THREAD

**Issue by heyimnowi** [vuetifyjs/vuetify#15765]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Last working version:** 3.0.0-beta.9
**Vue Version:** 3.2.13
**Browsers:** Chrome 105.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just hit Validate and you will see the only field that turns red is the text field.

### Expected Behavior
Select should turn red if it doesn't pass validation rules

### Actual Behavior
Select doesn't turn red if it doesn't pass validation rules

### Reproduction Link
<a href="https://codepen.io/noeliablopez-1472141200/pen/XWqdMbx" target="_blank">https://codepen.io/noeliablopez-1472141200/pen/XWqdMbx</a>

**Comment by qxygene** [comment]
still not working, any fix yet?
