### ISSUE TITLE
[Bug Report][3.0.0-beta.10] Sass variables override issue

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15763]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
I have created a minimal Vuetify project to demonstrate the issue.
- Install node_module
- Run the server
- Try to override the variables
You can find more details in the repo's [readme](https://github.com/alokVishu/vuetify-variabel-override-issue#readme).

### Expected Behavior
The variable should be overridden. 

### Actual Behavior
I found that this issue behaves weirdly in windows and mac systems.
I cannot override any variable in the Windows system.
In mac, I cannot override the font-family-root variable and all other variables will override normally.

### Reproduction Link
<a href="https://github.com/alokVishu/vuetify-variabel-override-issue" target="_blank">https://github.com/alokVishu/vuetify-variabel-override-issue</a>

**Comment by KaelWD** [comment]
1. You have `vuetify/styles` twice, remove it from core/scss/vuetify/index
2. Read https://next.vuetifyjs.com/en/features/sass-variables/, specifically the section where pnpm doesn't work properly

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by alokVishu** [comment]
@KaelWD,

Thanks for the response.
