### ISSUE TITLE
[Bug Report][3.0.0-beta.10] `v-list` prepend-avatar alignment issue in `density="compact"`

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15764]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Please try to use a list with `prepend-avatar` and `density compact.`

### Expected Behavior
The avatar should be aligned with the title. 

### Actual Behavior
It is not aligned. See Img

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/KKRzaNg?editors=101" target="_blank">https://codepen.io/Alokdev/pen/KKRzaNg?editors=101</a>

![image](https://user-images.githubusercontent.com/80033712/189350067-21a248b5-77bb-45e5-8885-9eea5227bdcf.png)

**Comment by steklopod** [comment]
My avatars are cut at bottom and top in `v-autocomplete`

```html
     <v-list-item
          v-bind="props"
          :prepend-avatar="item.raw.img"
      >
```

<img width="729" alt="Снимок экрана 2022-10-31 в 20 53 15" src="https://user-images.githubusercontent.com/29500153/199098437-4467ff15-4640-476c-b947-94bd712cf584.png">
