### ISSUE TITLE
[question] Material headers

### ISSUE THREAD

**Issue by idealley** [vuetifyjs/vuetify#1576]
Is there a way to reproduce this kind of layouts?
* https://codepen.io/benstr/pen/KlCyu
* https://getmdl.io/components/#layout-section (1st one)
* https://codepen.io/peiche/pen/PPPRgz

or actually a combination of the three where the transparent header solidifies and become smaller as you scroll.

That would be very useful for homepages and event websites. It something I see on Android a lot.

**Comment by johnleider** [comment]
To answer your question, yes, those layouts can be accomplished. However, the issue board is strictly for bugs. If you hop over to the community, there are plenty of people who can be of help, https://chat.vuetifyjs.com

**Comment by idealley** [comment]
Thank you @johnleider. Heading to the the chat sorry for the noise.
