### ISSUE TITLE
FAB button stays hidden when toggled within a promise

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#1577]
### Versions
0.15.1

### What is expected ?
When the "Promise Toggle" button is clicked the FAB buttons should remain visible just like the normal button on the right.

### What is actually happening ?
The FAB buttons stays hidden.
This is only happening when toggling the hidden variable inside a promise. Can someone explain this behavior ?

### Reproduction Link
https://codepen.io/anon/pen/qXvEbd

**Comment by wernerm** [comment]
The promise probably resolves before the hiding animation completes? 

If you put resolve() in a setTimeout() of a longer duration that the animation time (about 500ms+), I think your example *might* work as expected.

**Comment by SquareBeard** [comment]
So we cant toggle the visibility of a component during an animation ? Sounds like a bug to me.

**Comment by nekosaur** [comment]
What is your actual end use case here? What do you want to achieve?

**Comment by SquareBeard** [comment]
The button is used to save a form. I want to disable the button during the ajax call and re-enable it when it's complete. It works fine if the call is long enough. So, yes I could use a timeout, but it doesn't feel right to me.

**Comment by johnleider** [comment]
This has to do with Vue's data cycle and how you are telling it to hide the buttons. Unfortunately, when you have it conditionally **show**, the processing of the data within the model happens differently than when using **if**. You essentially end up with a race condition.

You can avoid this by either imposing a manual timeout after the Promise resolves, or changing your view conditional to a **v-if**

https://codepen.io/anon/pen/LjvQJO

**Comment by SquareBeard** [comment]
Thank you for the explanation.
