### ISSUE TITLE
[Bug Report][2.6.0] Why does VIcon causing vue unit test to fail?

### ISSUE THREAD

**Issue by aaqibqadeer** [vuetifyjs/vuetify#15771]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 105.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Import VAutocomplete from Vuetify.
2. Mount the component
3. Run the assertion

### Expected Behavior
the test should run successfully

### Actual Behavior
Mounting fails. It tries to read icons somewhere which is not available

### Reproduction Link
<a href="https://codesandbox.io/s/holy-darkness-kludkr?file=/src/tests/autocomplete.spec.ts" target="_blank">https://codesandbox.io/s/holy-darkness-kludkr?file=/src/tests/autocomplete.spec.ts</a>

### Other comments
I am writing unit test for vuetify components, most of the components are working fine but some components (checkbox, autocomplete, etc.) are failing to mount. I am getting this error: `Cannot read properties of undefined (reading 'icons')`

```
console.error node_modules/vue/dist/vue.runtime.common.dev.js:4516
    [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'icons')"
    
    found in
    
    ---> <VIcon>
           <DAutocomplete>
             <Root>

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:2921
    TypeError: Cannot read properties of undefined (reading 'icons')
        at remapInternalIcon (/Users/c_aaqib.qadeer/Desktop/Nuxt/dda-design-system/node_modules/vuetify/src/util/helpers.ts:233:33)
        at VueComponent.getIcon (/Users/c_aaqib.qadeer/Desktop/Nuxt/dda-design-system/node_modules/vuetify/src/components/VIcon/VIcon.ts:72:14)
        at Proxy.render (/Users/c_aaqib.qadeer/Desktop/Nuxt/dda-design-system/node_modules/vuetify/src/components/VIcon/VIcon.ts:217:23)
```

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/unit-testing/#bootstrapping-vuetify

You need `Vue.use(Vuetify)`

**Comment by aaqibqadeer** [comment]
I am sorry I missed this. Thank you so much

**Comment by aaqibqadeer** [comment]
I am sorry I missed this. Thank you so much
