### ISSUE TITLE
v-radio hint & persistent-hint not working

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#1578]
### Steps to reproduce
https://codepen.io/azaars/pen/rzRVjW?editors=1000
### Versions
0.15.2

### What is expected ?
`props.hint` should render

### What is actually happening ?

`props.hint` is not showing, even with `props.persistent-hint`
### Reproduction Link

https://codepen.io/azaars/pen/rzRVjW?editors=1000

**Comment by johnleider** [comment]
I may be wrong with this, but, when @nekosaur updated the radios to be in a radio-group, that functionality is gone now? If so that should be fixed.

**Comment by nekosaur** [comment]
hint and persistent-hint should be on radio-group now, not individual radio components

**Comment by azaars** [comment]
Ahh ok. I was following the outdated docs. Thank you.
