### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Outlined input box style problem

### ISSUE THREAD

**Issue by beshoo** [vuetifyjs/vuetify#15789]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Well, it appears on my Pc and my mobile, am not sure if this style problem may appear with other users. 
When I use the outline input box style, with a placeholder, there is a thick line around the placeholder word.

I make a code pen example so you can see what appears on my PC.

### Expected Behavior
Text box should appear with a clearly outlined border

### Actual Behavior
The text box appears with a thick border around the placeholder 

### Reproduction Link
<a href="https://codepen.io/yazanAlhaffar/pen/WNJppbm" target="_blank">https://codepen.io/yazanAlhaffar/pen/WNJppbm</a>

**Comment by yznetaX** [comment]
Yes I Have Same Problem 
Hope To Help
[https://i.imgur.com/06RFOjA.jpeg](url)

**Comment by qxygene** [comment]
any fix?

**Comment by qxygene** [comment]
something to do with v-field__outline__notch i guess.

**Comment by beshoo** [comment]
> You can try variant api
> 
> ` <v-text-field label="Outlined" placeholder="Placeholder" variant="outlined" ></v-text-field>` https://next.vuetifyjs.com/en/components/text-fields/#variant

![image](https://user-images.githubusercontent.com/4635115/194313452-09963309-a89a-4d29-bc24-3d2c63a44dce.png)

**Comment by qxygene** [comment]
Problem is line. 
![194313452-09963309-a89a-4d29-bc24-3d2c63a44dce 1](https://user-images.githubusercontent.com/2819611/194334649-931d9e13-d14a-4274-94f2-7249290a63db.jpg)

**Comment by beshoo** [comment]
I would like to mintion that this problem may not appear on some browsers.
The stage thing if I open the vuetifyjs website : 
https://next.vuetifyjs.com/en/components/text-fields/#variant
The problem dos not appear.
![image](https://user-images.githubusercontent.com/4635115/194338098-34c4dec0-2404-4bee-b346-f3533e2fd53d.png)

but when I apply the outline on my front end, it appears, as well as the codepen result 

![image](https://user-images.githubusercontent.com/4635115/194338725-0a7874a0-8a00-444c-bd75-907cf09f3471.png)

**Comment by beshoo** [comment]
It seems if we disable the "**--v-theme-on-background**" it fixes the problem

**Comment by qxygene** [comment]
yes, it fixed it.

**Comment by beshoo** [comment]
> yes, it fixed it.

Yes, but how to PL this? I can not find the source code for it!

**Comment by johnleider** [comment]
A codepen linking to an image is not a reproduction. As far as I can tell this is not an issue in the current version.

**Comment by qxygene** [comment]
is there any proper fix for this issue?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by yznetaX** [comment]
Unfortunately no
It appears on some devices but not all
I had to modify it using pure css

‫في الأربعاء، 5 أكتوبر 2022 في 11:53 م تمت كتابة ما يلي بواسطة ‪qxygene‬‏ <‪
***@***.***‬‏>:‬
