### ISSUE TITLE
[Bug Report][3.0.0-beta.10] VTooltip overlay interfering with VMenu Overlay Clickoutside behaviour

### ISSUE THREAD

**Issue by shaydoc** [vuetifyjs/vuetify#15784]
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on the VMenus on the Navigation Drawers, when the tooltip is active it prevents the VMenu from closing

### Expected Behavior
VMenu should close when clicking on a new VMenu Element

### Actual Behavior
2 VMenus appear stacked on top of each other

### Reproduction Link
<a href="https://codepen.io/shaydoc-the-reactor/pen/ExLNpxa" target="_blank">https://codepen.io/shaydoc-the-reactor/pen/ExLNpxa</a>

**Comment by KaelWD** [comment]
Overlays only close on click outside if they are the most recently opened one. I'm not really sure how to solve this because the current behaviour is useful for situations like a menu inside a dialog, where a click outside would otherwise close both instead of just the menu.

**Comment by shaydoc** [comment]
I think we need to distinguish tooltips from other overlays perhaps, as they typically only show on hover and maybe are an exclusion to this rule ?

**Comment by gkubisa** [comment]
@KaelWD Perhaps we could simply ignore clicks on overlays which work based on `mouseenter` and `mouseleave`? It should solve the issue, as tooltips are based on `mouseenter` and `mouseleave`, and they don't use `click` events.

**Comment by shaydoc** [comment]
do you have any thoughts on this issue @johnleider @KaelWD ?
