### ISSUE TITLE
[Feature Request] Open prop for <v-expansion-panel-header> actions slot

### ISSUE THREAD

**Issue by davidurco** [vuetifyjs/vuetify#15782]
### Problem to solve
I want to add multiple action icons for <v-expansion-panel-header> + I want only the $expand icon to rotate. Adding disable-icon-rotate prop to <v-expansion-panel-header> will disable all icons from rotating and there's no open prop for #actions slot - <template #actions={ open }>

### Proposed solution
Adding open prop to  <v-expansion-panel-header> actions slot like so: <template #actions={ open }>

**Comment by aelgn** [comment]
+1 would also be very useful in `expansion-panel-content`
