### ISSUE TITLE
[Feature Request] Export helpers in d.ts files

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#15781]
### Problem to solve
I want to add add custom sorting function to data-table that would make sure that folders always stay above the files, same as in Windows Explorer. In order to do that, I want to use `sortItems` function from helpers. However, I can't import it in my typescript project.

```ts
import { sortItems } from "vuetify/lib/util/helpers";

export const sortLibraryItems = function (...functionArguments: Parameters<typeof sortItems>) {
  return (sortItems(...functionArguments) as LibraryItem[]).sort((a, b) => {
    if (a.file && b.file) {
      return 0;
    } else if (a.file) {
      return 1;
    }
    return -1;
  });
};
```

### Proposed solution
This is a patch that I did using `npx patch-package`, but it's a copy-paste of the function type, so likely can be improved.

```patch
diff --git a/node_modules/vuetify/types/lib.d.ts b/node_modules/vuetify/types/lib.d.ts
index c9e4637..0b0b868 100644
--- a/node_modules/vuetify/types/lib.d.ts
+++ b/node_modules/vuetify/types/lib.d.ts
@@ -368,3 +368,14 @@ declare module 'vuetify/lib/directives' {
     Touch,
   }
 }
+
+declare module 'vuetify/lib/util/helpers' {
+  // from node_modules/vuetify/src/util/helpers.ts
+  export function sortItems<T extends any = any>(
+    items: T[],
+    sortBy: string[],
+    sortDesc: boolean[],
+    locale: string,
+    customSorters?: Record<string, DataTableCompareFunction<T>>
+  ): T[];
+}
```

**Comment by Maxim-Mazurok** [comment]
Any update on this one, please? :)

**Comment by KaelWD** [comment]
helpers are mostly internal functions, exposing types for them makes them part of the public api that we have to support

**Comment by Maxim-Mazurok** [comment]
I see... perhaps we can start by exporting just the sorting function to allow for the sort customisation as described above?

**Comment by Maxim-Mazurok** [comment]
@KaelWD what do you think about that, allowing a custom sorting function and exporting a default one? Feel free to keep it closed if it's not aligned with your plan for now, thanks!
