### ISSUE TITLE
[Bug Report][2.6.2] `v-sheet` as a `v-menu`'s activator doesn't work when `v-menu` is initially disabled

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#15794]
### Environment
**Vuetify Version:** 2.6.2+
**Vue Version:** 2.7.10
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
click on the first text

### Expected Behavior
menu opens same as on clicking on 2 other texts

### Actual Behavior
menu doesn't open

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/Vwxbvbe?editors=1010" target="_blank">https://codepen.io/jkarczm/pen/Vwxbvbe?editors=1010</a>

### Other comments
broken in 2.6.2
working repro for 2.6.1 - https://codepen.io/jkarczm/pen/NWMjGpw?editors=1010

**Comment by KaelWD** [comment]
Works with Vue 2.6

**Comment by jacekkarczmarczyk** [comment]
Doesn't work for me <https://codepen.io/jkarczm/pen/bGMWVaa?editors=1010>

**Comment by lioneaglesolutions** [comment]
Resolved in V3 

https://play.vuetifyjs.com/#eNqlUT1v2zAQ/StXLrYBSXTjTbWNdOvSrUCHKAMlnRs2FEmQlILA0H/PUR+x4mQIkE2P9+59nO7O7Ke1Wdciy9k+YGOVCHgsNMC+S4W1w+cAGiH1hEaMuoW8ll6UCutDwebPgl1osyJ0qVcm5KIKshPBOOKfwTpjPfSLhUHZPyAG2iiljroDizjTIAGpZZBCqWeYLSGFJ+Me/Z5PpEsC/qbU0uH4mxpcb0Qcmy3hXDyC8SRvVAn6ykkbwGNo41g21rgAZ3B4gh5OzjSwohuvIrky2gdo/D84xPl69QuVMvDXOFV/W20ulNdyIy+4Fjc/Ck0mf2SDpg3r9QYOx1de1gnVIrFPQnlM4Pt2G/l7PqajXCxhYzTqZLP/3mj66+dYrZgGdOcchpf4RpEjLthDCNbnnFe1prUalexcpjFwbRt+SzTuWh0oVVqb5naX7bJtWmIQ2Y5TurCcZuibtHTmyaMjrYIlC7cgT8+fcJyYZHST3YwO01OqROmjxTtpTn4dutShrtGh+2yxq7UPyl0x3hWMIfpC93R9JfWjvzp85Yej381Zv9R8EItK99GwT9gyLgUY9tj9C4SQUpY=
