### ISSUE TITLE
[Feature Request] Directive that automatically scroll to the first error in form

### ISSUE THREAD

**Issue by darkin1** [vuetifyjs/vuetify#1580]
Create directive that allows to automatically scroll to the first error in form

For example:
When we have long form and user filled all inputs without one of the first inputs he could get an error, but he couldn't see it because he is on the bottom of the page. And that is a problem for him because he doesn't see that error. So probably he will click many times to the submit button.

That is the case that I have had seen multiple times in many products, Many time business guys want to implements that kind of behavior and developers need to implement ugly hacks for his.
So there could be some directive that we could add in form, and when some error will show up form automatically scroll to that error.

**Comment by johnleider** [comment]
That is a very very very specific use case. I'm not sure this is something we would add to the framework

**Comment by darkin1** [comment]
Are you sure? Please just check google search, there are people (since 2012) that want that kind of behavior.

![zrzut ekranu z 2017-09-03 22-32-04](https://user-images.githubusercontent.com/1249151/30006399-e4f30cfe-90f7-11e7-8731-cf7b00365799.png)
![zrzut ekranu z 2017-09-03 22-32-13](https://user-images.githubusercontent.com/1249151/30006400-e4f4e5a6-90f7-11e7-8cf1-142b6a9d7020.png)
![zrzut ekranu z 2017-09-03 22-32-20](https://user-images.githubusercontent.com/1249151/30006401-e4f979d6-90f7-11e7-941a-e3e024e3d783.png)

**Comment by johnleider** [comment]
I'm not saying the functionality is not valuable. What I am saying is I'd rather make a scroll utility where you could pass it anything and it would scroll to it. Then you would only have to tell it where to go, as opposed to creating a utility that serves only 1 purpose.

**Comment by darkin1** [comment]
It also sounds like a good solution ;)

**Comment by johnleider** [comment]
As that functionality is planned, if you want to change the context of the feature request, we can leave this here. Otherwise feel free to close the ticket.
