### ISSUE TITLE
[Bug Report][3.0.0-beta.11] VImg is doing onBeforeMount

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#15805]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Last working version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
VImg is doing onBeforeMount 

### Expected Behavior
https://github.com/vuetifyjs/vuetify/blob/faf66716e6b41cbecb89de562bcc4d73b3009c8c/packages/vuetify/src/components/VImg/VImg.tsx#L165

### Actual Behavior
https://github.com/vuejs/core/issues/6658#issuecomment-1254766772

### Reproduction Link
<a href="https://codepen.io/qxygene/pen/WNJELjz" target="_blank">https://codepen.io/qxygene/pen/WNJELjz</a>

### Other comments
https://github.com/vuejs/core/issues/6658#issuecomment-1254766772

**Comment by KaelWD** [comment]
#15724 was fixed, I don't know what "weird stuff" that comment is referring to, and you haven't provided any information at all.
