### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Padding of v-list-item inside a v-navigation-drawer is breaking between dev and production

### ISSUE THREAD

**Issue by NathanAP** [vuetifyjs/vuetify#15813]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Opera 91.0.4516.16, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1 - Create a `v-navigation-drawer > v-list- > v-list-group > v-list-item`
2 - Run `npm run build`
3 - Your sub-items will have fixed padding

### Expected Behavior
I should be able to change padding with CSS.

### Actual Behavior
I cannot.

### Reproduction Link
<a href="https://codepen.io/Naats/pen/GRdOeZY?editors=101" target="_blank">https://codepen.io/Naats/pen/GRdOeZY</a>

### Other comments
1 - I was talking with John about this problem on Discord as you can see [here](https://discordapp.com/channels/340160225338195969/660898563139567625/1022986865210560592). 

2 - It is occurring in the official documentation as well, as you can see [here](https://next.vuetifyjs.com/en/components/lists/#sub-group). 

3 - Here are images of my situation:

This is my `dev` enviroment:
![image](https://user-images.githubusercontent.com/12821171/192277047-32630bf9-3423-40ec-b905-1f1beb36352d.png)

This is my `production` enviroment
![image](https://user-images.githubusercontent.com/12821171/192277087-7ba6f488-24d1-4177-8d0e-8cca54f124d7.png)

Finally, this is the CSS found in dev-tools
![image](https://user-images.githubusercontent.com/12821171/192277346-64250de9-1d0a-4465-9988-2f241590e010.png)

**Comment by KaelWD** [comment]
> I'm directly changing .v-list-item in css 
(with a !important)
like this: 
```
.v-list-item {
    margin-top: 0.3125rem;
    padding: 0.25rem 0.5rem 0.25rem 2rem !important;
}
```

you need a more specific selector, v-list-item uses `.v-list-group__items .v-list-item` with !important
