### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Skeleton app doesn't work

### ISSUE THREAD

**Issue by mrosi** [vuetifyjs/vuetify#15823]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
I've just created skeleton application following guidelines:
1. `npm create vite vuetify3 --template vue`
2. `cd vuetify3`
3. `vue add vuetify`
4. `npm run dev`

### Expected Behavior
Vuetify demo page should be displayed in the browser

### Actual Behavior
Blank page is displayed and console reports series of warnings:
`[Vue warn]: Failed to resolve component: v-*` and blocking error `Uncaught ReferenceError: require is not defined at HelloWorld.vue:6:17`

### Reproduction Link
<a href="https://github.com/TechniArch/vuetify3" target="_blank">https://github.com/TechniArch/vuetify3</a>

### Other comments
VITE 3.1.4
VUE-CLI 5.0.8

**Comment by nekosaur** [comment]
Which options did you choose for the create vite and add vuetify commands respectively?

Did you possibly select `Vuetify 3 - Vue CLI (preview)`?

The correct option is `Vuetify 3 - Vite (preview)`

**Comment by mrosi** [comment]
Hi Albert,
it works now with beta.13 and "Vite (preview)"
Thanks a lot for your support
Martin R.
