### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Label animation flicker with changing text color

### ISSUE THREAD

**Issue by tobiasklemp** [vuetifyjs/vuetify#15825]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Last working version:** 3.0.0-beta.5
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Focus the textfield

### Expected Behavior
Animation without flicker

### Actual Behavior
the text flickers at the last part of the animation.

### Reproduction Link
<a href="https://codepen.io/Tklemp/pen/jOxZgyW?editors=1111" target="_blank">https://codepen.io/Tklemp/pen/jOxZgyW?editors=1111</a>

### Other comments
This implementation worked with the version 3.0.0-beta.5 and occured after updating to beta.11.

**Comment by KaelWD** [comment]
You've set a solid background color on `input`, which is above the label. You'll have to either set the background on a different element, or tweak z-indexes to get everything in the right order.
