### ISSUE TITLE
[Bug Report][3.0.0] Textfield's append,prepend and clearable icon is not align when you change icon size

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15826]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to change the `v-icon` size and use `prepend-icon`, `append-icon` and `clearable`.

### Expected Behavior
the icon should always be in the center. 

### Actual Behavior
Icon is not in center

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/NWMYKBX?editors=101" target="_blank">https://codepen.io/Alokdev/pen/NWMYKBX?editors=101</a>

**Comment by johnleider** [comment]
This is a tricky one. The first thought that comes to mind is to scope out global v-icon changes from inputs. @vuetifyjs/core-team any thoughts?

**Comment by jacekkarczmarczyk** [comment]
Wouldn't it be enough if the icon (or whatever content is in the append/prepend slot) was just centered vertically? Or am I missing something?

**Comment by johnleider** [comment]
Append and prepend have dynamic padding top for their alignment. it assumes a default icon size. This was intentional as there were issues accounting for all of our use-cases by using flex align.

**Comment by johnleider** [comment]
This is resolved in v3.3.0:

https://play.vuetifyjs.com/#eNqNUk1vm0AQ/SvTvZBKBhw5lSqLRO2hUnuv0kPpYcMOZqP90u7axbH83zMsEMgtF2DeezPMvJm/FxZ8U56OGGV7Lp4D2zOpnfURLtB45BEfRw6u0HqrIZu0WW1qg32SNtaECBMB9+8Tby61ARDY8qOKYQ8pBHj8RVlv0SAwQcbzHrLG6paq8ieF2Wamg3xB4m6/un4Gr+k9PmOHmvip2vSz3yOYKXno4pxVlnPW9XNt2CbN/925gtqn4auI2inq/mGQVaecO5c+U+AxOJpVnhAaxUO4r5nuc36Mtmagpcn/SxE7Qu+2W9fXbMpMuRH7mLcSlZhBoCLI/TDoAk0+UA3ywfEm1mwhnUeHRuTSGPS5JAeHDoTMO6txLaSuP6TrpMBcYORSDcOMkyy04k+oCP+hSQBcCDIgvGtI8QY7qwR6kj3bzgiL3w6DvKD+19J4dkgaHLgFf6jKtTWz1QQuXo+rIGjcRVWudkRhaLx0EQLG47iqtwP22K7PNp0smZ6uVYcDXSopbrKfqJSFP9Yr8Smjo6jKsSQVY9cN2xV3xe0XupRdsSu27N8rz3wG0w==
