### ISSUE TITLE
[Bug Report][2.6.10] sub component v-image lost style (without data-v-xxxxxxxx attribute ) when I use style scoped

### ISSUE THREAD

**Issue by yokefellow** [vuetifyjs/vuetify#15837]
### Environment
**Vuetify Version:** 2.6.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 106.0.0.0
**OS:** Windows

## VuetifyDemo.vue
```vue
<template>
  Please see the reproduction link below for details
</template>
<script>
export default {
  name: "VuetifyDemo",
  data: () => ({
    show: false,
  }),
};
</script>
<style scoped src="vuetify/dist/vuetify.min.css">
</style>
<style lang="stylus" scoped></style>
```

### Expected Behavior
Components can be displayed normally when I import without using global styles. 
I am using vuetify to complete some functions of vuepress, but reset.css is included in vuetify.min.css, I don't want them to affect other styles, so I choose partial import.

### Actual Behavior
When component  is rendered, v-img (.v-image div) has no data-v-xxxxxxxx attribute. When I remove the scoped setting, it displays fine.but it also means that other styles of vuepress are polluted.
![image](https://user-images.githubusercontent.com/43605758/193799566-a9be2bda-1c10-4008-ade9-cab73c8cae8e.png)

When I manually add the data-v-xxxxxxxx attribute in the browser developer tools, the display is normal, now I want to know how to achieve it by code
![image](https://user-images.githubusercontent.com/43605758/193799147-d9818ce1-fc4e-4e35-9dcf-e45c26e63f52.png)

### Reproduction Link
<a href="https://codesandbox.io/s/damp-browser-kptbgt?file=/src/components/VuetifyDemo.vue" target="_blank">https://codesandbox.io/s/damp-browser-kptbgt?file=/src/components/VuetifyDemo.vue</a>

**Comment by jacekkarczmarczyk** [comment]
That's not a valid usage of vuetify styles, please refer to docs to see how to use the framework
