### ISSUE TITLE
[Bug Report][2.6.10] clear icon of VCombobox (and other form inputs) only showing on hover may be unusable on mobile devices

### ISSUE THREAD

**Issue by zetaraku** [vuetifyjs/vuetify#15830]
### Environment
**Vuetify Version:** 2.6.10
**Vue Version:** 2.6.14
**Browsers:** Firefox 105.0
**OS:** Windows 10

### Steps to reproduce
1. Use a mobile device to open the reproduction page.
2. Select something with the Combobox and unfocus the Combobox.
3. Try to clear the Combobox.

### Expected Behavior
The clear icon is always there and I can click on it anytime to clear the Combobox.

### Actual Behavior
The clear icon doesn't show up and when I try to focus it, the mini keyboard shows up and the autocomplete list completely blocks the clear icon and the input field.

### Reproduction Link
<a href="https://codepen.io/zetaraku/full/YzLavgq" target="_blank">https://codepen.io/zetaraku/full/YzLavgq</a>

### Other comments
Hiding available action behind mouse hover may be bad for mobile devices and even desktops experience.

**Comment by vchrisb** [comment]
This behavior changed sometime after `2.6.5`.

**Comment by KaelWD** [comment]
This is the same as `<input type="search">`
I see what you mean though, maybe we could add a media query for `@media (hover: hover)`?

**Comment by zetaraku** [comment]
Desktop users may not notice that a clear icon showed up on the right when they click the input and delete the text on the left.
As mentioned in #15876, I think it'd be better always shown even on desktop devices just like Google does.
