### ISSUE TITLE
[Feature Request] Fix for Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#15836]
### Problem to solve
When you run lighthouse in Chrome dev tools, it complains about "Ensure text remains visible during webfont load". 

### Proposed solution
The fix is to add `font-display: swap;` to the `@font-face` css property. 

https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools

**Comment by KaelWD** [comment]
Not sure what we're supposed to do about this, we don't have font-face anywhere in our codebase.

**Comment by TheInvoker** [comment]
Actually i think the Vuetify css doesn't have the font-face property. It is Vite that was generating it.

https://github.com/vitejs/vite/issues/10538
