### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Error: [Vuetify] Could not find defaults instance

### ISSUE THREAD

**Issue by stjoe4** [vuetifyjs/vuetify#15835]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
When using Vuetify components in render function throws Error: [Vuetify] Could not find defaults instance

### Expected Behavior
using vuetify components in render

### Actual Behavior
throws Error

### Reproduction Link
<a href="https://codesandbox.io/s/vue-vite-forked-zpv9ed?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vue-vite-forked-zpv9ed?file=/src/App.vue</a>

**Comment by nekosaur** [comment]
Reproduction is not working. I don't understand what you're doing with createVNode and render.

**Comment by stjoe4** [comment]
This error occurs when render function used without  providing appContext to vnode

**Comment by KaelWD** [comment]
Not a bug. `app.use(vuetify)` is required for components to work correctly.

**Comment by NieShiyi** [comment]
export default createVuetify({
  theme: {
    defaultTheme: 'myCustomLightTheme',
    themes: {
      myCustomLightTheme
    }
  },
  blueprint: md1,
  icons: {
    defaultSet: 'mdi',
    aliases,
    sets: {
      mdi
    }
  },
  components: {}
});

but it not work and also report this bug

**Comment by mikail-sw** [comment]
Im encountering the same error when using the render function, I have tried the provide/inject vuetify into the render and by using "withCtx". 
For me the error occurs when rendering components dynamically within the gridstack.js libary.

Example code:
```
const itemVNode = h(components[name], { itemId, onRemove }, {
   vuetify-instance,...
});
```

**Comment by mark422** [comment]
vNode.appContext = getCurrentInstance().appContext

**Comment by Jemory-git** [comment]
> app.use(vuetify)

Indeed, but it seems that there is no relevant explanation in the official documentation. I spent quite a while searching before finally finding the reason here.
