### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Prominent app bar is not shrinking when user scrolls

### ISSUE THREAD

**Issue by azliR** [vuetifyjs/vuetify#15838]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Scrolling

### Expected Behavior
The app bar is shrinking

### Actual Behavior
The app bar stays big

### Reproduction Link
<a href="https://codepen.io/azliR/pen/zYjamNE" target="_blank">https://codepen.io/azliR/pen/zYjamNE</a>

### Other comments
I'm using the example code from the documentation

**Comment by nekosaur** [comment]
shrink on scroll is not yet implemented

**Comment by KaelWD** [comment]
#12707
