### ISSUE TITLE
[Bug] a-la-carte imported Drawer, VSelect and VTextField don't follow custom theme

### ISSUE THREAD

**Issue by Kylart** [vuetifyjs/vuetify#1584]
### Disclaimer
No codepen for this issue 😞 

### Steps to reproduce
Import `VNavigationDrawer`, `VTextField` or `VSelect` the `a-la-carte` way and define a custom theme.

### Versions

Vue 2.4.2, Vuetify 0.15.2

### What is expected ?

The text color should follow my custom defined primary color

### What is actually happening ?

Those components don't care about my declared `$theme` and follow the default theme.

### Reproduction Link

I did not find any way to make a codepen with `a-la-carte` but this can be tested in [this repo](https://github.com/kylart/KawAnime)

_pm me on Discord anytime to discuss this_

**Comment by nekosaur** [comment]
But other components will respect your custom theme?

**Comment by Kylart** [comment]
Well I noticed this only on those components.

I just tried `VToolbar` and it seems affected as well.
My guess would be that it applies to all components 😟

**Comment by johnleider** [comment]
I believe that this should be resolved in current dev, I'll have to take another look. Neko just did a rewrite of a lot of the a-la-carte functionality.

**Comment by Kylart** [comment]
Si I tried with the `a-la-carte` template and using the current dev as a dependency and didn't work 😟

**Comment by nekosaur** [comment]
There is more to be done than just using dev. If you want to try it out before all templates and docs are updated, you can have a look at https://github.com/vuetifyjs/webpack-ssr/tree/enhancement/a-la-carte-new

**Comment by Kylart** [comment]
Ok so indeed it is working in the current `enhancement/a-la-carte-new` branch, Thanks!
