### ISSUE TITLE
[Bug Report][3.0.0-beta.11] Combining v-tooltip with v-slider?

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#15841]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Hover with the mouse over slider handle or slider track

### Expected Behavior
show tooltip

### Actual Behavior
no tooltip

### Reproduction Link
<a href="https://codepen.io/drhouse82/pen/oNdMBjO" target="_blank">https://codepen.io/drhouse82/pen/oNdMBjO</a>

**Comment by KaelWD** [comment]
`activator="parent"` will only work in components that have a default slot

**Comment by drhouse82** [comment]
Thanks for the info.
For me, the other tooltip syntax from the examples page doesnt work as well:
[https://codepen.io/drhouse82/pen/poVZOMo](https://codepen.io/drhouse82/pen/poVZOMo)
Is it possible to use v-tooltip with v-slider?
