### ISSUE TITLE
[Bug Report][3.0.0-beta.13] Primary Color still wrong in Beta 13

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuetifyjs/vuetify#15848]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
# Steps
1. Create a fresh Nuxt 3 project
2. Install Vuetify 3
3. Create the Nuxt plugin for Vuetify
4. Add a simple VBtn with color="primary"

### Expected Behavior
Seeing the button as blue after setting color="primary" as in Vuetify 2.

### Actual Behavior
In earlier betas of Vuetify 3, "primary" was purple. Now it's like lilac or pink.

### Reproduction Link
<a href="https://stackblitz.com/edit/github-sthgnz" target="_blank">https://stackblitz.com/edit/github-sthgnz</a>

**Comment by nekosaur** [comment]
How is this a bug? The default color schemes are just examples. If you want a specific color then adjust the theme configuration.

**Comment by angelhdzmultimedia** [comment]
> How is this a bug? The default color schemes are just examples. If you want a specific color then adjust the theme configuration.

You are so condescending an arrogant. I expected better from this community. Silly me.

Default color and color scheme are 2 different things.

I explicitly used the "primary" scheme that is supposed to be blue.

I haven't read anything (and I've been researching a lot) that an official change to the scheme has be done, that's why I assumed (and I had the right to) that it was a bug.

Be careful of the god complex that most programmers suffer.

**Comment by FFdhorkin** [comment]
> How is this a bug? The default color schemes are just examples. If you want a specific color then adjust the theme configuration.

they may be "just examples," but that doesn't mean projects haven't been relying on those defaults. We just migrated from 2->3 and now we're having to manually recreate the old theme because suddenly all the styling changed.

This is just one of MANY things that is missing from the migration notes.

**Comment by FFdhorkin** [comment]
If anyone else would like the Vuetify 2 color palette in Vuetify 3, I have recreated it based on https://v2.vuetifyjs.com/en/features/presets/#default-preset and https://vuetifyjs.com/en/styles/colors/


```
import colors from 'vuetify/lib/util/colors'

createVuetify({
  theme: {
    themes: {
      light: {
        light: {
          primary: colors.blue.darken2,
          secondary: colors.grey.darken3,
          accent: colors.blue.accent1,
          error: colors.red.accent2,
          info: colors.blue,
          success: colors.green,
          warning: colors.orange.darken1,
        },
        dark: {
          primary: colors.blue,
          secondary: colors.grey.darken3,
          accent: colors.ping.accent1,
          error: colors.red.accent2,
          info: colors.blue,
          success: colors.green,
          warning: colors.orange.darken1,
        },
      },
    },
  },
})
```

If you'd like to achieve the above without the import:


```
createVuetify({
  theme: {
    themes: {
      light: {
        primary: '#1976D2',
        secondary: '#424242',
        accent: '#82B1FF',
        error: '#FF5252',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#FB8C00',
      },
      dark: {
        primary: '#2196F3',
        secondary: '#424242',
        accent: '#FF4081',
        error: '#FF5252',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#FB8C00',
      },
    },
  },
})
```
