### ISSUE TITLE
[Feature Request] Calendar element: advanced navigation

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15849]
### Problem to solve
Users can navigate only to the next or previous day. It can be a problem if the customer wants to get a next year date or something like this.

### Proposed solution
I suggest adding calendar navigation to next month, next year, previous month, and previous year. Also, would be nice to have a field to set an exact date there.

**Comment by KaelWD** [comment]
For anything custom like that you should calculate the desired date yourself and set it with `v-model`
