### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v-tab doesn't fire "change" event

### ISSUE THREAD

**Issue by geeshta** [vuetifyjs/vuetify#15857]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Last working version:** 2.6.11
**Vue Version:** 3.2.13
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. Create a `<v-tabs>` component and inside of it, create a couple of `<v-tab>` components
2. Add event listener on the `<v-tab>` components to listen for change event
3. `<v-tab value="myValue" @change="myMethod">`
4. Server the application and click on some tabs

### Expected Behavior
As per documentation:  
> change: Emitted when tab becomes active

The method in the @change listener should be called.

### Actual Behavior
The method in the @change listener is not called at all.

### Reproduction Link
<a href="https://github.com/geeshta/vuetify3-tab-change-big" target="_blank">https://github.com/geeshta/vuetify3-tab-change-big</a>

**Comment by nekosaur** [comment]
The documentation is not updated. Listen to `update:modelValue` on `v-tabs` if you want to know when a tab has changed.

**Comment by Z3rio** [comment]
The issue is that you are looking at the Vuetify v2 documentation and not Vuetify v3.
Vuetify v2 documentation notes it as @change, in Vuetify v3's documentation this is noted as @update:modelValue.
https://next.vuetifyjs.com/en/api/v-tabs/

**Comment by lgiesen** [comment]
This [solution](https://medium.com/easy-coding/update-sliders-width-vuetify-90d40ee6834d) might help with ` this.$refs.tabs.callSlider();`
