### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v-chip doesn't darken on hover

### ISSUE THREAD

**Issue by carlesalbasboix** [vuetifyjs/vuetify#15853]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Last working version:** 2.6.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-chip

### Expected Behavior
Chip should darken on hover

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://codepen.io/carlesalbasboix/pen/ZEoqjEB" target="_blank">https://codepen.io/carlesalbasboix/pen/ZEoqjEB</a>

**Comment by KaelWD** [comment]
This isn't a bug the way you've demonstrated it, but it should have the hover effect if it has a click event: #10115
