### ISSUE TITLE
[Bug Report][2.6.10] disable-resize-watcher not working

### ISSUE THREAD

**Issue by WilliamColmenares** [vuetifyjs/vuetify#15852]
### Environment
**Vuetify Version:** 2.6.10
**Vue Version:** 2.7.10
**Browsers:** Chrome 106.0.0.0
**OS:** Linux

### Steps to reproduce
Shrink the page so it reaches xsOnly, when it does the navigation drawer fires up.

### Expected Behavior
The drawer should be kept close.

### Actual Behavior
It opens even setting disable-resize-watcher to true

### Reproduction Link
<a href="https://codepen.io/willcolmenares/pen/YzLjJQO" target="_blank">https://codepen.io/willcolmenares/pen/YzLjJQO</a>

**Comment by KaelWD** [comment]
The resize watcher is what would be closing it (see https://codepen.io/kaelwd/pen/GRdYEoL?editors=1010)
Explicitly setting `temporary` also prevents it from closing: https://github.com/vuetifyjs/vuetify/blob/bb2b11e3d0f39fe286b83792072afd4e97ce8121/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts#L205-L213
A simpler way of doing this would just be `mobile-breakpoint="xs"`
