### ISSUE TITLE
[Bug Report][3.0.0-beta.12] v-menu position is incorrect when it's attached to the node with transform: scale 

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#15867]
### Environment
**Vuetify Version:** 3.0.0-beta.12
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- Click on the button to open the menu
- Menu appears at the incorrect position

### Expected Behavior
Menu should appear near the button

### Actual Behavior
Menu appears in the air, somewhere detached from the button

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/dyeQBvm?editors=1010" target="_blank">https://codepen.io/kasheftin/pen/dyeQBvm?editors=1010</a>

### Other comments
Vuetify2 has the same buggy behavior. 
The trick is the menu is attached to some node which has `transform: scale(2)` (it's not necessary the node itself, any scaled parent gives the same behavior).
Hence, v-menu container is scaled by itself. The measurements (getBoundingClientRect) gives scaled size (2 times larger than it gives when transform scale is not applied). 
Menu `location=top` (top=true in vuetify2) gives incorrect offset.

The fun thing is vuetify3 tries to be smarter than vuetify2. The menu goes to the correct position after several iterations. 

![Vuetify v-menu transform scale issue](https://user-images.githubusercontent.com/379267/195057662-4409e34b-6761-4d3d-a4c5-49446cc6418b.gif)

It works even buggier when `overflow: auto` is applied,

![Vuetify v-menu transform scale issue 2](https://user-images.githubusercontent.com/379267/195058295-0477486e-8929-4d64-a9e2-2a49ac3bfe7a.gif)

**Comment by KaelWD** [comment]
Floating-ui seems to have fixed something similar: https://github.com/floating-ui/floating-ui/pull/1247
Not sure what sort of performance impact that has though, or how it would go with our existing nullifyTransforms function.

**Comment by akFace** [comment]
I also met for this problem
