### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v-select model type error

### ISSUE THREAD

**Issue by SEary342** [vuetifyjs/vuetify#15868]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-select with a list of strings for the items prop and a string for the v-model prop.

### Expected Behavior
The documentation indicates that the v-model for v-select is of type `any`. It should be assignable to a string (or applicable type based on the items prop) unless the multiple prop is set to true.

### Actual Behavior
Volar displays a `Type 'string' is not assignable to type 'Readonly<any>'.` in VS Code. 

[vue-tsc@1.0.3](https://www.npmjs.com/package/vue-tsc) also reports the error. Older vue-tsc versions do not report the error.

The run time code appears to be fine. This appears to be a type error

### Reproduction Link
<a href="https://codepen.io/seary342/pen/ExLGjmx" target="_blank">https://codepen.io/seary342/pen/ExLGjmx</a>

### Other comments
I think this issue surfaced with the recent Volar upgrade to use [vue-tsc@1.0.3](https://www.npmjs.com/package/vue-tsc)

A potential work-around to pass type checking is to keep vue-tsc < 1.0.0. Another work-around would be to change all v-model string types to string[]; however, that does add some ease of use concerns to the v-select component.

**Comment by SEary342** [comment]
![image](https://user-images.githubusercontent.com/45857544/195117594-bd803506-b069-40cd-bb5f-2c33dcf2adf1.png)

**Comment by maxgrdo** [comment]
Same issue here : 
![image](https://user-images.githubusercontent.com/3910651/195874376-795f85a3-48dd-42cb-85fb-f339ccf7ebfa.png)

**Comment by 0140454** [comment]
`v-combobox` has same issue.

![image](https://user-images.githubusercontent.com/1191368/196098245-b5259361-8126-4c68-b487-c7738f4cfb11.png)

![image](https://user-images.githubusercontent.com/1191368/196098393-e0bab86d-4376-49e1-a179-7884c636c57d.png)
