### ISSUE TITLE
[Bug Report][2.6.11] #prepend-item in VAutoComplete causes incorrect highlighting

### ISSUE THREAD

**Issue by jonatan-mobal** [vuetifyjs/vuetify#15862]
### Environment
**Vuetify Version:** 2.6.11
**Vue Version:** 2.7.10
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open codepen
2. Click on autocomplete component
3. Click on 'c' item

### Expected Behavior
'c' is highlighted (gets v-list-item--highlighted class)

### Actual Behavior
'a' gets highlighted (gets v-list-item--highlighted class)

### Reproduction Link
<a href="https://codepen.io/jonatan-mobal/pen/XWqyVVy" target="_blank">https://codepen.io/jonatan-mobal/pen/XWqyVVy</a>

**Comment by KaelWD** [comment]
Duplicate of #14489
