### ISSUE TITLE
[Bug Report][3.0.0-beta.13] hover effect breaks when using rowspans for v-simple-table (v2) / v-table (v3)

### ISSUE THREAD

**Issue by matthiashermsen** [vuetifyjs/vuetify#15877]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.40
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Hover over cell b-2

### Expected Behavior
When hovering over b-2 it should also add a hover effect for a-1 ( the whole row )

### Actual Behavior
a-1 has no hover effect

### Reproduction Link
<a href="https://codepen.io/medsmh/pen/qBYLyQx" target="_blank">https://codepen.io/medsmh/pen/qBYLyQx</a>

### Other comments
Vuetify 2 behaves the same => https://codepen.io/medsmh/pen/MWGZBPj

If this behaviour is intended, is there a way to disable the hover effect?

This might be related to
- https://github.com/vuetifyjs/vuetify/issues/3701
- https://stackoverflow.com/questions/64673717/how-to-apply-pointer-events-to-simple-table-using-rowspan-in-vue-js

**Comment by KaelWD** [comment]
You have to use the custom styles from #3701 with `tbody:hover`, and put each group of rows in a separate tbody.
