### ISSUE TITLE
[Feature Request] VVirtualScroll will not be include in vuetify3?

### ISSUE THREAD

**Issue by bimohxh** [vuetifyjs/vuetify#15875]
### Problem to solve
I use vuetify3 in my vue3 vite project, but I can't find the VVirtualScroll component, so this component will be removed? this is a so usefull component.

### Proposed solution
I need VVirtualScroll.

**Comment by UkonnRa** [comment]
The related issue: https://github.com/vuetifyjs/vuetify/pull/15585

BTW have you tried https://vueuse.org/core/usevirtuallist/, it's an useful hook for virtual scrolling and works fine to me

**Comment by bimohxh** [comment]
vueuse is great!
