### ISSUE TITLE
focus() input inside a dialog not working

### ISSUE THREAD

**Issue by evaldobratti** [vuetifyjs/vuetify#1587]
### Steps to reproduce
https://codepen.io/anon/pen/prGmeg?editors=1111
1. open dialog1 and expect focus on the text field, then close dialog1
2. open dialog2 and expect focus on the fext field, then close dialog2
3. repeat 1 and 2

### What is expected ?
The input in the dialog should get focused no matter what

### What is actually happening ?
The component only get styled, but cursor is not actually in the component

### Reproduction Link
i tried 2 implementations of this, 
one with lazy dialogs and autofocus in the text field
https://codepen.io/anon/pen/RZvmrB?editors=1111
that works once for each dialog, then when dialog gets reopened it does not work anymore

another with explicit call to focus() when the dialog gets opened. in this one the text field get 'styled', but the cursor is not blinking in the component, so i cant type anything
https://codepen.io/anon/pen/prGmeg?editors=1111

**Comment by johnleider** [comment]
In order for your implementation to work, you must wait for vue to refresh its data variables. Just add a nextTick to your method call. The **autofocus** prop will only work on initial load which is why it was available only for the first time you opened the dialog. Attached is a working example of your **focus** method call.

https://codepen.io/johnjleider/pen/dzrQBy

**Comment by evaldobratti** [comment]
that's nice :+1: 
thanks john

**Comment by deiucanta** [comment]
@johnleider your solution works with dialogs but not with menus. Any Idea why?

https://codepen.io/deiucanta/pen/VdRKJY

**Comment by johnleider** [comment]
That codepen has errors. Also, 

Please do not comment on closed issues. If you have a bug, please create a new issue, https://issues.vuetifyjs.com or seek help in our community, https://community.vuetifyjs.com

**Comment by MaritzaVst** [comment]
@deiucanta this is because you set autofocus to a component of Vuetify but it's not the root element . Use console.log of "this.$refs.text.$el" to find out the input and then use the focus function.

Pd: Sorry for my english. I still learning.

**Comment by Proffitt78** [comment]
So how do I get it focus on the text field if it is inside of a v-form that itself is inside of a v-dialog?

**Comment by aburai** [comment]
try this in mounted
```
const element = this.$el.querySelector('#myinput')
if (element) this.$nextTick(() => { element.focus() })
```

**Comment by Proffitt78** [comment]
> const element = this.$el.querySelector('#myinput') if (element) this.$nextTick(() => { element.focus() })

Thanks man, I think this is doing the trick.

**Comment by yihou** [comment]
I found another way to focus the field:
```js
this.$nextTick(() => {
  this.$refs.inputRef.$refs.textfield.focus();
});
```
