### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v select

### ISSUE THREAD

**Issue by gifary** [vuetifyjs/vuetify#15882]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Last working version:** 3.0.0-beta.13
**Vue Version:** 3.2.36
**Browsers:** Opera 77.0.4054.64
**OS:** Linux x86_64

### Steps to reproduce
just render the v select and see the console log will throw an error TypeError: globalStack.at is not a function

### Expected Behavior
show the select component

### Actual Behavior
didn't show the component

### Reproduction Link
<a href="https://codepen.io/gifaryrg/pen/NWMovpx" target="_blank">https://codepen.io/gifaryrg/pen/NWMovpx</a>

**Comment by carlosmouracorreia** [comment]
Having the same issue on the latest Vuetify version (3.1.1) - this happens only in server side rendering and in production mode. (Running with Nuxt 3 and Vuetify-loader lib)

**Comment by OnismYY** [comment]
请看这里，已经解决了[TypeError: globalStack.at is not a function](https://blog.csdn.net/OnismYY/article/details/137918251)

**Comment by pangjianxin** [comment]
> 请看这里，已经解决了[TypeError: globalStack.at is not a function](https://blog.csdn.net/OnismYY/article/details/137918251)

you are awesome!!!you saved my ass!!!!!!!!!!!!!!!!!!!!!!!!!!!!
