### ISSUE TITLE
[Feature Request] Add support for moduleResolution: NodeNext in v3

### ISSUE THREAD

**Issue by viell-dev** [vuetifyjs/vuetify#15885]
### Problem to solve
When using `moduleResolution: NodeNext` in `tsconfig.json` the `exports` field is used for imports and types. So `package.json` must have `types` fields in the `exports` field. And the type definition files need to have .d.mts extension when using .mjs files.

### Proposed solution
Change the build to produce `.d.mts` definition files or change to `.js` files instead of `.mjs`. And change `package.json` `exports` to something like the following:
```json
  "exports": {
    ".": {
      "import": {
        "types": "./lib/index.d.mts",
        "default": "./lib/framework.mjs"
      },
      "require": {
        "types": "./dist/vuetify.d.ts",
        "default": "./dist/vuetify.js"
      }
    },
    "./styles": "./lib/styles/main.css",
    "./styles/*": "./lib/styles/*",
    "./framework": {
      "types": "./lib/index.d.mts",
      "default": "./lib/framework.mjs"
    },
    "./blueprints": {
      "types": "./lib/blueprints/index.d.mts",
      "default": "./lib/blueprints/index.mjs"
    },
    "./blueprints/*": {
      "types": "./lib/blueprints/*.d.mts",
      "default": "./lib/blueprints/*.mjs"
    },
    "./components": {
      "types": "./lib/components/index.d.mts",
      "default": "./lib/components/index.mjs"
    },
    "./components/*": {
      "types": "./lib/components/*/index.d.mts",
      "default": "./lib/components/*/index.mjs"
    },
    "./directives": {
      "types": "./lib/directives/index.d.mts",
      "default": "./lib/directives/index.mjs"
    },
    "./directives/*": "./lib/directives/*/*.mjs",
    "./locale": {
      "types": "./lib/locale/index.d.mts",
      "default": "./lib/locale/index.mjs"
    },
    "./locale/adapters/*": {
      "types": "./lib/locale/adapters/*.d.mts",
      "default": "./lib/locale/adapters/*.mjs"
    },
    "./iconsets/*": {
      "types": "./lib/iconsets/*.d.mts",
      "default": "./lib/iconsets/*.mjs"
    },
    "./*": "./*"
  },
```

**Comment by viell-dev** [comment]
Note that adding the `exports` field in `package.json` doesn't just effect TypeScript, it will also effect Node ESM. And as such may be a breaking change. Also, a solution that works for TypeScript doesn't necessarily work for Node ESM as well. So testing will be required for different types of consumer projects.

Another note: I have read in one of the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) that the `types` field needs to on top. Though that doesn't always seem to be the case in my personal experience.

Also relevant upstream issue at TypeScript: [microsoft/TypeScript#50058](https://github.com/microsoft/TypeScript/issues/50058)

**Comment by KaelWD** [comment]
Yeah we probably won't be adding it in v2 because even just `"./*": "./*"` may have different behaviour. This will require a fair bit of testing as there are a lot of possible combinations of bundlers, runtime environments, typescript versions, and tsc options.

**Comment by ml1nk** [comment]
Same problem here. 

In the vuetfiy/package.json I changed
~~~json
    "./components": "./lib/components/index.mjs",
    "./components/*": "./lib/components/*/index.mjs",
~~~
to
~~~json
    "./components": {
      "types": "./lib/components/index.d.ts",
      "default": "./lib/components/index.mjs"
    },
    "./components/*": {
      "types": "./lib/components/*/index.d.ts",
      "default": "./lib/components/*/index.mjs"
    },
~~~
to get it temporarily working.
