### ISSUE TITLE
Feature request: loader on main element

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1589]
I'm trying to implement a loader so users don't see the UI based on an empty store. Right now they see a flash of wrong content because loading takes like 200ms.

I tried to implement a loader on the `main` element but since it uses padding instead of margin, it's hard to get the loader to only cover the `main` and not cover the sidebar and header.

Maybe there is an easy way to implement a loader for this or perhaps it would be suitable to add this to the `main` element (or whatever is most fitting).

**Comment by smares** [comment]
Would toggling between two main elements using v-show be an option?

**Comment by Christilut** [comment]
Good idea!

I tried it and it seems to work pretty well. Just had to make sure to use `v-show` instead of `v-if` or it triggers all the create and mounted hooks again. And the loader main z-index has to be lower than the header and sidebar or the loader covers them too.
