### ISSUE TITLE
[Bug Report][3.0.0-beta.13] `valuecomparator` shows as an attribute on `v-radio-group`

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#15896]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
```html
    <v-radio-group>
      <v-radio value="a" />
    </v-radio-group>
```

### Expected Behavior
- no `valuecomparator` attribute
- should be possible to use value comparator with radio group

### Actual Behavior
- unexpected `valuecomparator` attribute
- not possible to use value comparator with radio group

![image](https://user-images.githubusercontent.com/15625235/195983395-d9a412a4-c2a9-429f-9507-f873b2569224.png)

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/wvjOpgV?editors=1010" target="_blank">https://codepen.io/jkarczm/pen/wvjOpgV?editors=1010</a>

## Additional comments

- `VRadioGroup` passes props (including `valueComparator`) to `VSelectionControlGroup`, but `VSelectionControlGroup` doesn't have this prop defined. 
- `VSelectionControl` takes its value from props, so it would work when you pass value comparator to `VRadio` directly
- `valueComparator` could be maybe added to `VSelectionGroupContext` and `VSelectionControl` could take the value either from the injection or from props, not sure if this is the best solution

**Comment by johnleider** [comment]
fixed by #15958
