### ISSUE TITLE
[Bug Report][3.0.0-beta.13] update model value immediately on input event

### ISSUE THREAD

**Issue by thenewseason** [vuetifyjs/vuetify#15901]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.40
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Resolved same issue in vuetify2: https://github.com/vuetifyjs/vuetify/issues/11243.
And I have checked the code piece is not applied to vuetify 3.

    function onInput (e: Event) {
      model.value = (e.target as HTMLInputElement).value
    }

### Expected Behavior
The v-model should be updated on input event.

### Actual Behavior
The v-model is not updated on input event.

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/pojPmVw" target="_blank">https://codepen.io/wistudent/pen/pojPmVw</a>

**Comment by nekosaur** [comment]
From your description it is unclear if you have actually witnessed this issue in v3, or if you've only looked at the code? Please provide a reproduction for v3.
