### ISSUE TITLE
[Feature Request] When to officially release 3.0？

### ISSUE THREAD

**Issue by oday-xiexin** [vuetifyjs/vuetify#15919]
### Problem to solve
The ticket skipping of version 3.0 is too long. When can I use it. I remember the plan is to release the official version in May? But it's October now

### Proposed solution
The ticket skipping of version 3.0 is too long. When can I use it. I remember the plan is to release the official version in May? But it's October now

**Comment by oday-xiexin** [comment]
The progress of 3.0 is too slow. The authorities should actively promote it

**Comment by tidan-16** [comment]
I think they need help for the documentation. Documentation is not ready (from what I see from the checklist)

Vuetify's team want to do something good, and not just release the most quickly possible

So stop complaining and go help! :)

**Comment by KaelWD** [comment]
Couple major bugs left too, we'll get there eventually.

**Comment by oday-xiexin** [comment]
> Couple major bugs left too, we'll get there eventually.
Well, Vuetify2 is excellent, but the new project is built on vue3, so we are eager to use Vuetify3.0. Look forward to the good news from your team
