### ISSUE TITLE
[Bug Report][3.0.0-beta.13] `v-btn` with `variant="tonal"`- text get overflow visible

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15912]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use btn with `variant="tonal"` and large text.

### Expected Behavior
It should be an ellipsis like other variants.

### Actual Behavior
Overflow visible.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/MWGRJwP?editors=1010" target="_blank">https://codepen.io/Alokdev/pen/MWGRJwP?editors=1010</a>

![image](https://user-images.githubusercontent.com/80033712/196111687-e75580bd-d752-43d2-a789-567c1db0d74a.png)

**Comment by KaelWD** [comment]
> ellipsis like other variants
None of the variants have ellipsis, they just have white text so you can't see it against the background

This didn't happen in v2 but buttons didn't have `max-width: 100%` so the entire button would go off screen instead.

**Comment by alokVishu** [comment]
Hello @KaelWD,

I don't know why you close this issue. But I really need to solve it. Do you have any solution for the same?
![chrome-capture-2022-9-18](https://user-images.githubusercontent.com/80033712/196349166-9f8fca21-7b80-42cc-8879-6effa6bb5703.gif)
