### ISSUE TITLE
[Feature Request]  VFileInput: display the props of `placeholder`

### ISSUE THREAD

**Issue by guxuerui** [vuetifyjs/vuetify#15928]
### Problem to solve
When use VFileInput component, display the props of `placeholder`

### Proposed solution
Add a `placeholder` props in VFileInput.tsx

**Comment by KaelWD** [comment]
`label="Placeholder" single-line`` has the same appearance as a placeholder

**Comment by guxuerui** [comment]
> `label="Placeholder" single-line` has the same appearance as a placeholder

Yes, I made it with this.  Thank you!
