### ISSUE TITLE
[Feature Request] tooltip prop on v-btn

### ISSUE THREAD

**Issue by shiva-prasad-reddy** [vuetifyjs/vuetify#15920]
### Problem to solve
In my case mostly tooltips are added on top of buttons. It is helpful if v-btn by default can provide such props to add a tooltip, so codebase would be clean.

### Proposed solution
Adding a tooptip and tooltip-location prop in v-btn.

**Comment by KaelWD** [comment]
Nope. The closest we'd do to this is #9610
