### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v-alert close button take too wide space

### ISSUE THREAD

**Issue by azliR** [vuetifyjs/vuetify#15921]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Add closable to v-alert

### Expected Behavior
The space is just taken as the close button take

### Actual Behavior
The space take too wide than the close button

### Reproduction Link
<a href="https://codepen.io/azliR/pen/PoegMjy?editors=101" target="_blank">https://codepen.io/azliR/pen/PoegMjy?editors=101</a>

**Comment by KaelWD** [comment]
@johnleider why's it got a 90px margin?

**Comment by johnleider** [comment]
To provide some space between the content and close button. I agree it's probably too much though.

**Comment by johnleider** [comment]
closed by https://github.com/vuetifyjs/vuetify/commit/79eb58a29f0a3e85892ddf8fd0adb16a9b12e486
