### ISSUE TITLE
[Bug Report][3.0.0-beta.13] #item slot not working properly in v-select

### ISSUE THREAD

**Issue by ppyl-datBoi** [vuetifyjs/vuetify#15922]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add your <template #item="{ item }"> to v-select

### Expected Behavior
Custom elements can be selected and displayed correctly
![image](https://user-images.githubusercontent.com/43649920/196367849-df376b62-3f5a-4fab-a24b-05c45b53451c.png)

### Actual Behavior
Custom elements cannot be selected and are displayed incorrectly
![image](https://user-images.githubusercontent.com/43649920/196368288-951533a5-f7c6-46ee-948e-b8becf07690a.png)

### Reproduction Link
Vuetify 3 <a href="https://codepen.io/ppyl-datboi/pen/NWMVWrw?editors=101" target="_blank">https://codepen.io/ppyl-datboi/pen/NWMVWrw?editors=101</a>
Vuetify 2 https://codepen.io/ppyl-datboi/pen/rNvgNYb?editors=101

**Comment by KaelWD** [comment]
It doesn't create v-list-item for you anymore: https://codepen.io/kaelwd/pen/mdLYdKw?editors=1010

**Comment by ppyl-datBoi** [comment]
Thanks, now I understand.

**Comment by MaxZhurin** [comment]
is it at work? what version is it planned for?
