### ISSUE TITLE
can i use a single component with 'Vue.use()' 

### ISSUE THREAD

**Issue by liuruoran88** [vuetifyjs/vuetify#1593]
Hi, in my project，I imported Vuetify with its all components which is too big.  VueMaterial can support to import individual components as shown in the code below, I wonder if Vuetify had supported similar methods and where can i find the show example. Thank you!
``` js
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/components/mdCore/index.css' //Required to boot vue material
import 'vue-material/dist/components/mdButton/index.css'
import 'vue-material/dist/components/mdIcon/index.css'
import 'vue-material/dist/components/mdSidenav/index.css'
import 'vue-material/dist/components/mdToolbar/index.css'

Vue.use(VueMaterial.mdCore) //Required to boot vue material
Vue.use(VueMaterial.mdButton)
Vue.use(VueMaterial.mdIcon)
Vue.use(VueMaterial.mdSidenav)
Vue.use(VueMaterial.mdToolbar)



```

**Comment by sindrepm** [comment]
Check out the [docs](https://vuetifyjs.com/vuetify/a-la-carte) and 0.15 [release notes](https://github.com/vuetifyjs/vuetify/releases/tag/v0.15.0).

**Comment by nekosaur** [comment]
Answered by @sindrepm. Please ask any future questions in our chat instead (https://chat.vuetifyjs.com). This board is for issues and feature request only. Thank you.
