### ISSUE TITLE
[Bug Report][3.0.0-beta.14] v-select does not respect disabled information 

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#15933]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Firefox 106.0
**OS:** Windows 10

### Steps to reproduce
provide item information via a items object to v-select.
Add "disabled" boolean to every item.

### Expected Behavior
items with disabled=true cannot be selected

### Actual Behavior
all items can be selected

### Reproduction Link
<a href="https://codepen.io/drhouse82/pen/zYjVqOZ?editors=101" target="_blank">https://codepen.io/drhouse82/pen/zYjVqOZ?editors=101</a>

**Comment by KaelWD** [comment]
This is intentional, only title/value are used by default because you might have header/avatar/disabled etc. keys for other reasons but not want them to affect the list items (#4148). `<VSelect item-props>` will instead treat `items` as objects of `VListItem` props.

**Comment by MatthewAry** [comment]
At risk of being rebuked for commenting on a closed issue, this report likely emerged because the docs say it should work in the manner the OP described. It's well known that the docs for 3.0 need to be updated. For `v-select` the prop `item-props` is missing a description.

**Comment by MatthewAry** [comment]
https://play.vuetifyjs.com/#eNp9kLFuwyAQhl/ldEtaybGbtF0sJ1KfoEu3kIHaZwkJAwJMB8vv3sNOrHTpAnz/cT//cZnww7kyjYQ1NqH1ykUIFEd3FkYNzvoIE3jqYYbe2wF2fHUnjDCtNSFCkhpOuf5kRq2f77KKNIRb4TIJAxBV1FSDwE9DAossce/I0mEB560LNSx3AToV5LemroZe6kBZnIWZi7W+eX392L9ex3+9oh83qytnbap1YB6VgSM7LSMxATRpL13+g+zAMEhlbsTcqXRuqrxuUtoH0tRGqJfZTwKXXSBws+1Is8Ihmau7a/Vgm2F9sKkeguBc4Gt5LN/eMR9eygNefwGI14vv
