### ISSUE TITLE
[Bug Report][2.4.0] Dialogs - Please explain how to get working open/close-delay attribute

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15938]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
apply open-delay="3000" and "close-delay="3000" to any dialog (add them to v-dialog tag)

### Expected Behavior
there are open and close-delays for the dialog

### Actual Behavior
There are no open and close-delays for the dialog

### Reproduction Link
<a href="https://codepen.io/Liliya-web/pen/WNJqZbV" target="_blank">https://codepen.io/Liliya-web/pen/WNJqZbV</a>

**Comment by KaelWD** [comment]
Delay only applies to hover and focus, click is always instant.
