### ISSUE TITLE
[Feature Request] Bring back `.focus()` on VTextField

### ISSUE THREAD

**Issue by ricardoboss** [vuetifyjs/vuetify#15930]
### Problem to solve
It enables a previously removed feature to focus on text fields programmatically. It was available in 3.0.0-beta.5 and is not available in 3.0.0-beta.14.

### Proposed solution
Re-enable the missing functionality.

**Comment by KaelWD** [comment]
Works for me: https://play.vuetifyjs.com/#eNpVjkFqwzAQRa8yaJMEajlpsypKaCn0ElUXiiqBqD0S8sgUjO/ekZ1AotX8rwf/fU3iPSU5FidehRpsDolgcFTSWWPoU8wEE2TnYQafYw8bRjcaNdqIA4EPrvuBUyW2u1r7gpZCRIj40QX7C9sdTBphJeVouuKkj7YMlZ81qnZd5T0O5PrUGXKcANTYmFRFgB8HniQT0OVrtZTk/qhZNVjipMVyawHtPXUhhDdbhZi4qmlx/qwiql3+bzucHodqs3qo9s5PzE/iRT7L40HUYy/3zcWRkYej+P4HrxFwUQ==

If this is supposed to be a bug report please use the bug template

**Comment by ricardoboss** [comment]
Maybe I should clarify that I was referring to the typescript library:
![image](https://user-images.githubusercontent.com/6266356/196731690-26cc0081-ffa4-4142-a001-0e707514f815.png)

**Comment by ricardoboss** [comment]
@KaelWD Can you tell if typescript should still be available or not?

**Comment by ricardoboss** [comment]
Thanks for the quick fix @KaelWD! 🎉
