### ISSUE TITLE
Icon of active navigation drawer element not in primary color

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#1594]
### Steps to reproduce
Add a navigation drawer with a v-list containing v-list-tiles with an icon in v-list-tile-action and a v-list-tile-title.

### Versions

Vue 2.4.2, Vuetify 0.15.2. MacOS Sierra 10.12.6, Chrome 60.

### What is expected ?
That the active route causes both the title text as the icon to color in the primary color.

### What is actually happening ?
Only the title text is colored in the primary color.

### Reproduction Link
Without custom CSS to color the icon: https://codepen.io/anon/pen/jLRqyj
With custom CSS to color the icon: https://codepen.io/anon/pen/mMgPVX

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1519?

**Comment by everhardt** [comment]
Yes, apologies.
