### ISSUE TITLE
[Bug Report][3.0.0-beta.14] `item-props` not working

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15944]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Run the codepen & check the height of list item

### Expected Behavior
list item height should be 32px

### Actual Behavior
list item height doesn't change

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/WNJVwwq?editors=101" target="_blank">https://codepen.io/jd-0001/pen/WNJVwwq?editors=101</a>

**Comment by KaelWD** [comment]
It doesn't work like that, it uses the same code as `item-value`. Either an array or string with keys to lookup from the item, or a function returning an object.

**Comment by jd-solanki** [comment]
If I use `:item-props="{ minHeight: 32 }"` it gives type warning. We were passing object in vuetify 2 however in vuetify 3 it is changed.

How can I set the minHeight from `v-list` then?

Thanks for the quick response.

**Comment by KaelWD** [comment]
vuetify 2 didn't have `item-props`

---
> a function returning an object

`:item-props="() => ({ minHeight: 32 })"`
