### ISSUE TITLE
[Bug Report][2.4.0] The footer with the fixed property obstructs navigation panel

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15946]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Implement a navigation panel on the right side of the page;
2. On the same page implement a footer with absolute and app properties;
3. On the same page implement a footer with fixed property

### Expected Behavior
The fixed footer doesn't obstruct the navigation panel

### Actual Behavior
The fixed footer obstructs the navigation panel

### Reproduction Link
<a href="https://codepen.io/Liliya-web/pen/GRdVqvJ" target="_blank">https://codepen.io/Liliya-web/pen/GRdVqvJ</a>

### Other comments
When two footers are implemented on one page (the first one with app property, the second one with fixed property), the second one is placing full width, taking place of the navigation panel at the bottom

**Comment by KaelWD** [comment]
This is expected

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block
