### ISSUE TITLE
[Bug Report][3.1.2] can't apply inline styles to v-card

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15947]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open the reproduction line
2. Inspect the v-card styles

### Expected Behavior
Card shoule have min-height 100%

### Actual Behavior
style attribute is empty

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjt0OwTAUx1/l5CTixtoNV5REvIMbc1Gc0US3pjuIiHd3Zsbam/6a/9f2iasQ1O1KOENTH6ILDDXxNSzz0vlQRYYnRCrgBUWsPAxFOsxLo1utqASYfLhYJiEAc0tsaOwgR8BbV35JeLO28Sgmbm8htj/V/LjQIkfvyuRM7nTmGWRpOpjn2AX8kiQrLFd3qitPRnd98qs/FV2/7g1ooJ1mdG8yvkY4UWM1zbB5pCpN9sRWZVPcvQHAXVn5)

**Comment by KaelWD** [comment]
Vue bug.

 `vnode.props.style` has
```
{
  height: undefined,
  maxHeight: undefined,
  maxWidth: undefined,
  minHeight: undefined,
  minWidth: undefined,
  width: undefined,
  min-height: "100%"
 }
```
`patchStyle()` is calling
```js
style.minHeight = ''
style.minHeight = '100%'
```
then `style.minHeight = ''` again because of https://github.com/vuejs/core/blob/85af1398637ee91c6ebabb73bf42250320311e19/packages/runtime-dom/src/modules/style.ts#L13-L19

**Comment by KaelWD** [comment]
Fixed by https://github.com/vuejs/core/pull/7425
