### ISSUE TITLE
[Bug Report][3.0.0-beta.14] Empty space between hint and input field in VTextarea if hint is multiline

### ISSUE THREAD

**Issue by 0140454** [vuetifyjs/vuetify#15953]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Pass a very long string via prop `hint`.

### Expected Behavior
Same space as single-line hint

### Actual Behavior
No space between hint and input field

### Reproduction Link
[https://codepen.io/0140454/pen/qBodJoR?editors=1010](https://codepen.io/0140454/pen/qBodJoR?editors=1010)

### Other comments
I'm not sure whether it is a bug, but no matter how many lines the hint has, maybe it is better if the space between hint and input field is as same as single-line hint?

By the way, VMessage's prop `messages` accepts `string | string[]`, but VTextarea's prop `hint` only accepts string, is it expected?

**Comment by lioneaglesolutions** [comment]
@johnleider this is still present in V3 - not sure if it's expected or a bug though.

[V3.2.2 repro](https://play.vuetifyjs.com/#eNq9UktuwjAQvUrkNY4pIFVCtKL73gCzMPEU3MaOZQ+BCnH3jhPxKWkBqVKziOSZeZ959mzHXrzP6zWwMZsgWF8qhGfpsmxS80IFnVm15RujcfUk2bDf91vJsqJUMdLZKz6iAT6SrMGkj3AIW1QB1KGUHQF2wR8Gkp0atQpGOaTW2mkIpXGgz/seQjQRwSFfGYenRjoR6rVyy+x/fxGDccuTSdHGJdq8/pDdD8ldj+eXcK5Ec8B2PE/E8fJZj5HOR8zfY+XoWezSqGRFjJKNs1lLINkK0cexEIV2NKmhNHXIHaBw3gp6UGjePqfDfJAPhCaThxIv1SLmDVlimku3J0FjfRWQW+UvVNtGo9xUUo2Y0vmGhSmNibB2aCxwXdnGy+ixNXNWzyFavgjVJkIgFsl6ZzrJ8R1at9YliQ61IL0aAg+QbhbCvStdwL6tddHrrJbk9ynxfY+1OMq+Mc3mXwdbUOk=)

![image](https://user-images.githubusercontent.com/61766491/236078546-e5f6a051-76cb-4e6e-8fee-b018c98cfb0a.png)

**Comment by johnleider** [comment]
fixed in https://vuetifyjs.com/en/getting-started/release-notes/?version=v3.4.4

**Comment by KaelWD** [comment]
Specifically #18696
