### ISSUE TITLE
[Documentation] append-outer-icon does nothing

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#15955]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at the section on icons

### Expected Behavior
`append-outer-icon` should show an outer icon.

### Actual Behavior
There is no appended outer icon to be seen.

### Reproduction Link
[https://next.vuetifyjs.com/en/components/textareas/](https://next.vuetifyjs.com/en/components/textareas/)

### Other comments
However, the outer icon is already shown in the second field. The documentation should say `append-icon` which produces an outer icon.

**Comment by KaelWD** [comment]
Doesn't exist, renamed to `append-icon` for consistency.

**Comment by douira** [comment]
The problem is that the documentation is using `append-outer-icon` which doesn't exist. Thus the documentation needs to be adjusted.

**Comment by KaelWD** [comment]
Oops, I just skimmed the issue
