### ISSUE TITLE
[Bug Report][3.0.0-beta.14] VBtn loading is broken in Vuetify3

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#15952]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Opera 91.0.4516.65
**OS:** Mac OS 10.15.7

### Steps to reproduce
Works on website https://next.vuetifyjs.com/en/components/buttons/#loaders

### Expected Behavior
Should show loader

### Actual Behavior
empty showed

### Reproduction Link
[https://codepen.io/Ewocker/pen/mdLNKWj?editors=111](https://codepen.io/Ewocker/pen/mdLNKWj?editors=111)

### Other comments
I know vuetify3 is still beta, but just creating in case this issue is missed out.

**Comment by MstfDrmz13** [comment]
On my smartphone, it works as expected. Be sure that scripts are loaded on the codepen side. Also, you can check the browser console for any error message.

**Comment by KaelWD** [comment]
Opera is not officially supported, it may require polyfills: https://next.vuetifyjs.com/en/getting-started/browser-support/
