### ISSUE TITLE
[Bug Report][3.0.0-beta.14] v-text-field flat or elevation-0 error

### ISSUE THREAD

**Issue by stratdev3** [vuetifyjs/vuetify#15956]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Firefox 106.0
**OS:** Windows 10

### Expected Behavior
In vuetify v2.x, `v-text-field` have a `flat` prop which, combining with `solo`, remove the elevation.

### Actual Behavior
In vuetify v3.x, `v-text-field` does not have a such props to remove elevation even using `class="elevation-0"` or `elevation="0"`

### Reproduction Link

- v2 with v-text-field solo/flat : [https://codepen.io/cp10/pen/qBKWPWN?editors=1010](https://codepen.io/cp10/pen/qBKWPWN?editors=1010)

- v3 unable to remove elevation [https://codepen.io/cp10/pen/bGKbobj?editors=1010](https://codepen.io/cp10/pen/bGKbobj?editors=1010)

**Comment by 1Luc1** [comment]
Try to use `variant="plain"`. See [Docs Example](https://vuetifyjs.com/en/components/text-fields/#variant).
Interestingly, variant `plain` is missing in the [usage section](https://vuetifyjs.com/en/components/text-fields/#usage) of the docs.

**Comment by johnleider** [comment]
Use the **flat** prop.

https://play.vuetifyjs.com/#eNptUcFOwzAM/RWTS0Ei69AmIaFtEjfuHDhQDlnrtpHSJErcsmnav+OuVKkQp8TP773k2Z8XEUOZv3q/GnoUL2JH2HmjCA+FBdgNUnl/u96KgNE7G/WAUBoV474Q3Umqnlwh4FtX1DKyXa8L8ath1TFAnqpBEp5I1hpNNYMARh3RsPTdGXZKeKsrlBWS0iYmdFBBK0vMj3/4UdvGoDTaYgJrjpOqYyNLVgVWNwHPzG1aQiu3S58KOSSdmVO6zquSls05ORocFGlnJeed2ylp/l/Uw3IcIyVNdBo4Q9PEd/liE1zGMmhPEJH6aSG68y4QXCBgDVeog+sg4yVmI51/ya4EXWxgPzLuszc0xsGHC6a6yx7GByZLNhPXR7FZbVZbMZ1Pz+LrB8dro6U=
