### ISSUE TITLE
[Bug Report][3.0.0-beta.14] Prepend-item slot of autocomplete doesn't appear

### ISSUE THREAD

**Issue by lucagrammer** [vuetifyjs/vuetify#15954]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use the mentioned slot

### Expected Behavior
The slot should appear

### Actual Behavior
The slot does not appear at all

### Reproduction Link
[https://codepen.io/lucagrammer/pen/xxjvMyP](https://codepen.io/lucagrammer/pen/xxjvMyP)

**Comment by KaelWD** [comment]
Already fixed by 75c29a202637e37f59a353e7f42a9a395a972687
