### ISSUE TITLE
[Bug Report][2.4.0] v-windows-item disabled doesn't work

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15957]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add to v-windows-item disabled attribute

### Expected Behavior
v-windows-item doesn't have the active attribute (is disabled)

### Actual Behavior
v-windows-item is active (not disabled)

### Reproduction Link
[https://codepen.io/Liliya-web/pen/qBKWLaz](https://codepen.io/Liliya-web/pen/qBKWLaz)

**Comment by nekosaur** [comment]
Reproduction does not work.

**Comment by MayaElf** [comment]
@nekosaur Thank you. Sorry for delay in answer. It was our mistake. Please, close this issue.
