### ISSUE TITLE
wrap prop in v-layout not affected with false

### ISSUE THREAD

**Issue by mementototem** [vuetifyjs/vuetify#1595]
### Steps to reproduce

Add `wrap` prop to `v-layout` and then try to set to `true` and `false` it still has same result.

### Versions
- Vue: 2.4.2
- Vuetify: 0.15.2

### What is expected ?

When `wrap` prop set to `false` `v-layout` should render without `wrap` class.

### What is actually happening ?

`v-layout` still render with `wrap` class, whatever `wrap` set to `true` or `false`

### Reproduction Link

https://codepen.io/anon/pen/ZJZpBm

**Comment by johnleider** [comment]
That is because they are not true props, and are interpreted not by value, but by them existing. I can make this better.

**Comment by d3radicated** [comment]
I'm guessing that `v-container` will be updated as well.

**Comment by johnleider** [comment]
And v-flex.as.well.
