### ISSUE TITLE
[Bug Report][3.0.0-beta.14] Table hover background is not working

### ISSUE THREAD

**Issue by Bjornar97** [vuetifyjs/vuetify#15950]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
Make a v-table with thead row and tbody rows. Hover over a row with your cursor. 

### Expected Behavior
The background of the row should get a different backround than the rest of the table.

### Actual Behavior
The backround color stays the same.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctugzAQ/JWVL7kUSNKcKhepp/YDeqt7MGGTIPkls0SKovx710ApCKm+2LM7Ozsaf93FWwj5tUPxImR7jE0gaJG6UCrX2OAjwR0inuABp+gtbJi6UU45WQxs5jEgtMFoQkYA8prpkASADwOrGzeiHpOuDMLR6LZ9VaLyscYIVmd7JSaaIkkX1PVU6GcpLnCqXMoPNMbLgl/zXi9QvneEDj71edXnwlws9ZfrJFW+vs0KSXG9vx53kD4Debj5jq9kZ2l9oPZW/6OtXS1MyGJM7zdcxlO6CQy589jff4jHk3jO9/lhJ9Jjm2+zCknnu4P4/gHKYJGT)

### Other comments
I tested latest nightly, and the issue is there as well.

**Comment by jacekkarczmarczyk** [comment]
BTW - you need `hover` property
