### ISSUE TITLE
[Bug Report][3.0.0-beta.14] v-menu + v-tooltip + open-on-click does not work

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#15969]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.41
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Try clicking the button

### Expected Behavior
Tooltip appears, but the menu does not appear. There's no way to see the menu

### Actual Behavior
Clicking on the button should open the menu

### Reproduction Link
[https://codepen.io/kasheftin/pen/GRGREWe?editors=1010](https://codepen.io/kasheftin/pen/GRGREWe?editors=1010)

### Other comments
The reason is that when tooltip has open-on-click property set, there's click event attached to the activator. Due to the following line the click event is not propogated:
https://github.com/vuetifyjs/vuetify/blob/dcc1fccea0c154ee6cb3a551b15adc13b7ba8783/packages/vuetify/src/components/VOverlay/useActivator.tsx#L90
Removing this line is easy, what's not easy is to understand why it's here on the first place.

**Comment by KaelWD** [comment]
It doesn't work because you're doing
```js
const a = { onClick: () => {} }
const b = { onClick: () => {} }
{ ...a, ...b }
```
use [mergeProps](https://vuejs.org/api/render-function.html#mergeprops) or [`activator="parent"`](https://next.vuetifyjs.com/en/components/overlays/#activator-prop) instead.
