### ISSUE TITLE
[Bug Report][2.6.12] Autocomplete does not select first item on backspace when there is just one.

### ISSUE THREAD

**Issue by blaaat** [vuetifyjs/vuetify#15978]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.7.13
**Browsers:** Safari 16.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
Search 'a', backspace twice

### Expected Behavior
I would expect the selected 'a' to be highlighted first before it is deleted from the selection, as happens when you select a and b and then backspace 

### Actual Behavior
a is removed from selection without highlighting it first.

### Reproduction Link
[https://codepen.io/blaaat/pen/OJEPXNr](https://codepen.io/blaaat/pen/OJEPXNr)

**Comment by lioneaglesolutions** [comment]
Resolved in V3:

https://vuetifyjs.com/en/components/autocompletes/ (first example -> select multiple)
