### ISSUE TITLE
[Bug Report][2.4.0] v-row align-content doesn't work

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15975]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add align-content property with any valid value as v-row property. For example, align-content="end"

### Expected Behavior
The content of this row is aligned properly

### Actual Behavior
The content of this row is always aligned to the left side ("start")

### Reproduction Link
[https://codepen.io/Liliya-web/pen/QWxWeoQ](https://codepen.io/Liliya-web/pen/QWxWeoQ)

**Comment by KaelWD** [comment]
https://stackoverflow.com/a/34944673/2074736
