### ISSUE TITLE
[Feature Request][3.0.0-beta.14] "On submit only" validation on forms

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#15976]
#### Why

I know there is currently the `lazy-validation` prop on the `v-form`, but it don't solve my problem.

I would like to be able to pass a prop to form to tell it to not validate inputs until the form is submitted.

I thought it was possible with Vuetify 3 (see #3530), but it looks like it is finally not supported.

#### Example

Here is an example of a Vue component:

```vue
<template>
<v-form lazy-validation @submit.prevent>
      <v-text-field
        label="Test"
        :rules="[(v) => !!v || 'Required!']"
      />
</v-form>
</template>
```

##### What it does currently

Filling the "Test" field and clearing it will show the "Required" error message.

##### What I would to be able to do

Filling the "Test" field and clearing: no validation occurs and no message is displayed.

Submitting the form (using Enter key inside the field for example) will run validation and display the error message.

#### My workarround for now

For people interested, my current workarround is to add the rules on form submit and triggering a new validation on form after a tick.

### Proposed solution
Adding a `on-submit-validation` to `v-form` which enables this features.

**Comment by KaelWD** [comment]
Looks like we're missing validate-on-blur too.

**Comment by paul-thebaud** [comment]
Thanks for the quick update on the situation @KaelWD.

Looks like the first-fail is working normally on my side (first input validation error will stop validation run).

For the rest, I agree 👍
