### ISSUE TITLE
selected button in v-btn-toggle not styled properly

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1597]
### Steps to reproduce

Create v-btn-toggle and select one of them

### Versions
0.15.2

### What is expected ?
Selected button should have different background than not selected

### What is actually happening ?
Selected button has dark text but same background as not selected

### Reproduction Link
https://codepen.io/anon/pen/LjvQEb?editors=1010

Background is set in _button-toggle.styl:
```styl
  .btn
    .btn__content:before
      background-color: $material.buttons.focused-alt
```

It works ok in docs https://vuetifyjs.com/components/buttons, but I guess it uses older version of Vuetify

**Comment by KaelWD** [comment]
```css
.application--light .btn-toggle .btn .btn__content:before
```
Has a specificity of `0,0,4,1`, but
```css
.btn--active .btn__content:before
```
Only has `0,0,2,1`

Possible fix is to just repeat the selector, but it's a bit ugly (_buttons.styl):
```diff
/** Content */
.btn
- &--active,
- &:hover,
- &:focus
+ &&&&--active,
+ &&&:hover,
+ &&&:focus
    .btn__content:before
      background-color: currentColor
```

**Comment by johnleider** [comment]
With this fix I also added theme support for dark/light cus that's how I roll.
