### ISSUE TITLE
[Feature Request] [v-btn-toggle] Ignore active state

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#15982]
### Problem to solve
Currently in `v-btn-toggle`, clicking on a button sets an active state on it and its look is different. There is, to me, no easy solution to avoid having this active status.

I know it has been discussed here https://github.com/vuetifyjs/vuetify/issues/10622 but for me it doesn't solve the remaining active state on buttons.

Instead, doing what is proposed here https://github.com/vuetifyjs/vuetify/issues/10622#issuecomment-885612016 worked but it is IMHO heavy for such a basic behavior.

### Proposed solution
I suggest adding a prop like `ignore-active-state`, like it had been proposed in #10622

**Comment by KaelWD** [comment]
- `v-btn-group`, or
- `:active="false"` (broken)

**Comment by yuwu9145** [comment]
fix for `:active="false"` has been added to PR https://github.com/vuetifyjs/vuetify/pull/15897
