### ISSUE TITLE
[Documentation] Search bar

### ISSUE THREAD

**Issue by Angelo-Gebauer** [vuetifyjs/vuetify#15983]
### Problem to solve
The documentation page really needs a searchbar.
Trying to use Vuetify without knowing it inside out is almost not doable atm. because of the lack of a searchbar. 

### Proposed solution
Implement a searchbar that searches the components as well as the api pages.

**Comment by KaelWD** [comment]
Issues like this aren't helpful, we already know it needs to be done.
