### ISSUE TITLE
[Bug Report][3.0.0-beta.15] List item group not working in documentation examples

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#15981]
### Environment
**Vuetify Version:** 3.0.0-beta.15
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
click a list item

### Expected Behavior
the item is selected and highlighted

### Actual Behavior
nothing is happening.

### Reproduction Link
[https://codepen.io/drhouse82/pen/XWYJybX?editors=101](https://codepen.io/drhouse82/pen/XWYJybX?editors=101)

### Other comments
Examples in the docu dont work for me. They render but there is no functionality.
https://next.vuetifyjs.com/en/components/list-item-groups/#list-item-groups

The codepen is directly taken from the vuetify documentation (first example). For me, the codepen doenst even render.

**Comment by KaelWD** [comment]
It doesn't exist anymore, you just need `<v-list v-model:selected="selection">` and any v-list-item with a `value` will be selectable.

**Comment by Kugeleis** [comment]
Could this please be in the documentation. It's impossible to guess.

**Comment by adrianhand** [comment]
> It doesn't exist anymore, you just need `<v-list v-model:selected="selection">` and any v-list-item with a `value` will be selectable.

Is there any way to make this return an object instead of an array?
