### ISSUE TITLE
[Bug Report][2.6.12] Dialog - smooth scroll

### ISSUE THREAD

**Issue by OstapL** [vuetifyjs/vuetify#15990]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox, Chrome 105.0.0.0
**OS:** Mac OS 10.15.7, Mac OSX

### Steps to reproduce
open dialog, and scroll down.

### Expected Behavior
smooth scroll

### Actual Behavior
scrolling in jerks

### Reproduction Link
[https://codepen.io/OstapL/pen/ExRjwKM?editors=101](https://codepen.io/OstapL/pen/ExRjwKM?editors=101)

### Other comments
the same problem and on https://vuetifyjs.com/en/components/dialogs/#persistent

**Comment by KaelWD** [comment]
Probably duplicate of #14841
