### ISSUE TITLE
[Feature Request][a11y] separate dark theme color scheme

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1599]
### What will it allow you to do that you can't do today?

It will allow to create different color schemes (primary/secondary/error etc) for light and dark theme

### How will it make current work-arounds straightforward?

I don't see workaround for this at the moment. Dev can define his own color scheme, but it will be same for light and dark themes

### What potential bugs and edge cases does it help to avoid?

It'll give possibility to create accessible (with high enough contrast) interfaces in both themes

Here are examples of too low contract with default color scheme
![image](https://user-images.githubusercontent.com/15625235/30080067-a1304860-9282-11e7-891f-051796dccf03.png)
![image](https://user-images.githubusercontent.com/15625235/30080096-adb17b68-9282-11e7-8a9d-6bf9f1ad4dce.png)
![image](https://user-images.githubusercontent.com/15625235/30080215-1a6c8388-9283-11e7-8cf9-6722f7fc8fda.png)
![image](https://user-images.githubusercontent.com/15625235/30080247-372cef08-9283-11e7-9510-138fa58f7a99.png)

**Comment by johnleider** [comment]
You are referring to the ability to define a specific color on form inputs?

**Comment by jacekkarczmarczyk** [comment]
No, I'm talking about having 2 colors schemes - one for light app and one for dark app, so instead of having something like this:

```stylus
$theme := {
  primary: $blue.darken-2
  accent: $blue.accent-1
```

it could be:

```stylus
$material-light := {
  $theme: {
    primary: $blue.darken-2
    ...
  },
  ...
}

$material-dark := {
  $theme: {
    primary: $blue.lighten-2
    ...
  },
  ...
}
```

And in styles instead of `$theme.primary` we can use `$material.theme.primary`

**Comment by johnleider** [comment]
Dark and Light will have their own specified themes and would be applied depending upon color. This is also being touched up for md2 and might change a bit.

**Comment by agnjunio** [comment]
It would be nice to be able to change background colors (and basically anything) as well for each theme.

**Comment by jacekkarczmarczyk** [comment]
That's a separate issue @agnjunio

**Comment by agnjunio** [comment]
@jacekkarczmarczyk ok, then I will create a feature request for that

**Comment by DRoet** [comment]
this is now possible using the new bootstrap method in `v2.0.0-alpha.5`?

```
 theme: {
    dark: true,
    themes: {
      light: {
        primary: '...',
        ...
      },
      dark: {
        primary: '...',
        ...
      }
    }
  }
```
