### ISSUE TITLE
[Bug Report][2.4.0] Combination of properties type='number' and hide-spin-buttons doesn't work

### ISSUE THREAD

**Issue by Liliya-web** [vuetifyjs/vuetify#15997]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add type='number' and hide-spin-buttons properties to v-textarea element

### Expected Behavior
1. I can type in the text-area only numbers
2. Hide-spin-buttons property works properly

### Actual Behavior
Not type='number', nor hide-spin-buttons are working

### Reproduction Link
[https://codepen.io/Liliya-web/pen/zYavmva](https://codepen.io/Liliya-web/pen/zYavmva)

**Comment by KaelWD** [comment]
`<textarea>` doesn't support `type`
