### ISSUE TITLE
the text between v-radio labels can not be displayed

### ISSUE THREAD

**Issue by huobaiyu** [vuetifyjs/vuetify#16]
`<v-radio>option 1</v-radio>`
option 1 is not be displayed.

**Comment by johnleider** [comment]
This is a mistake on the documentation. Form inputs do not contain slots. To update the label, pass it as a prop. Let me know if this helps you. I will get the documentation for forms updated tonight.

**Comment by huobaiyu** [comment]
could you provide one example for me?

**Comment by johnleider** [comment]
```javascript
<v-radio id="test5" name="test5" label="Testing 5"></v-radio>
```

**Comment by huobaiyu** [comment]
it works. Thanks a lot

**Comment by johnleider** [comment]
Updated documentation 0ecfdbe0e4f2abde97da20242cec2b0222878d88.
