### ISSUE TITLE
[Bug Report][3.0.0] [sass] $string: true is not a string.

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16003]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.4
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I'm using the vite plugin in the treeshaking config with Nuxt 3, then I'm enabling the utilities with:

```
@use 'vuetify' with (
  $utilities: true,
  $color-pack: false,
);
```

### Expected Behavior
To be able to load the Vuetify mixins correctly

### Actual Behavior
```
[vite-node] [plugin:vite:css] [VITE_ERROR] ./node_modules/vuetify/lib/styles/utilities/_index.sass:19:11

Error: $string: true is not a string.
   ╷
19 │       @if string.slice($key, -4) == ':ltr'
```

### Reproduction Link
[https://github.com/ElYaiko/vtf3](https://github.com/ElYaiko/vtf3)

### Other comments
I hope you'll add better instructions in the docs with Nuxt 3 implementation

my packages:
nuxt": "3.0.0-rc.12",
"vuetify": "^3.0.0"

Thanks!.

**Comment by KaelWD** [comment]
`true` is not a valid value for that setting, if you aren't disabling or modifying anything you can just remove the key from the map.
