### ISSUE TITLE
[Bug Report][2.6.12] Combobox 'allow-overflow' is not working

### ISSUE THREAD

**Issue by MayaElf** [vuetifyjs/vuetify#16008]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. open Combobox
2. put 'allow-overflow' = false
3. and then for another combobox 'allow-overflow' = true

### Expected Behavior
Behaviour is different for 'allow-overflow' = false vs =true

### Actual Behavior
Behaviour is the same for 'allow-overflow' = false vs =true

### Reproduction Link
[https://codepen.io/MaiiaAfanaseva/pen/ZERQJXO?editors=1010](https://codepen.io/MaiiaAfanaseva/pen/ZERQJXO?editors=1010)

**Comment by MayaElf** [comment]
@Z3rio In Vuetify you have implementation of 'allow-overflow' for v-menu. I added it to examples in codepen https://codepen.io/MaiiaAfanaseva/pen/ZERQJXO?editors=1010 
I believe the implementation for v-combobox should be the same as in v-menu.

**Comment by KaelWD** [comment]
This was missed in f5a3f8296906fc63c87a60ca63c4ed9397bbe37c, and looks like it wasn't hooked up correctly even then. Since v1.2.0 the correct  way to pass additional props to v-menu is through the `menu-props` prop.

**Comment by Z3rio** [comment]
Okay, I will take a look at this.

**Comment by MayaElf** [comment]
@KaelWD Sorry, my issue was about v-combobox. So in api-documentation for v-combobox 'allow-overflow' will be deleted?

**Comment by KaelWD** [comment]
Yes, it extends VAutocomplete.
