### ISSUE TITLE
[Bug Report][3.0.0] Toolbar Progress Indicator position

### ISSUE THREAD

**Issue by Froxz** [vuetifyjs/vuetify#16005]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Added ` v-progress-linear` to `v-toolbar` with props `absolute bottom`

### Expected Behavior
The progress bar should be at the bottom (**From Docs**: Using the `absolute` prop we are able to position the `v-progress-linear` component at the **bottom** of the `v-toolbar`)

### Actual Behavior
The progress bar is in the middle

### Reproduction Link
[https://codepen.io/Froxz/pen/XWYXMRp](https://codepen.io/Froxz/pen/XWYXMRp)

![image](https://user-images.githubusercontent.com/3294939/199177523-1a4ec12c-dafd-4a79-88c4-479c93561568.png)

**Comment by Froxz** [comment]
Hi @Z3rio 

This is the behaivor I expect (Vuetify 2): https://codepen.io/Froxz/pen/poKgMxg
Progress Indicator is aligned at the bottom of the toolbar:

![image](https://user-images.githubusercontent.com/3294939/199418353-000606b8-5241-451d-96f7-c31d0f855b88.png)

Material Guidelines: https://m3.material.io/components/progress-indicators/specs

![image](https://user-images.githubusercontent.com/3294939/199418685-9fa2be70-194c-412a-a681-f1c80f0d0464.png)

**Comment by Froxz** [comment]
@Z3rio there is a pull request for this: [#15883](https://github.com/vuetifyjs/vuetify/pull/15883)

**Comment by Froxz** [comment]
Hi closing this was fixed in [3.1.2](https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.2) release via #15883

[Pen](https://codepen.io/Froxz/pen/xxJPPxw) with a fix

**Comment by stratdev3** [comment]
thanks for the merge
