### ISSUE TITLE
Default v-form validation

### ISSUE THREAD

**Issue by nelxaz** [vuetifyjs/vuetify#1601]
### Steps to reproduce
Designate a default (valid) value to a field in v-form
### Versions

Vue 2.4.2
Vuetify 0.15.2

### What is expected ?

Unfilled field should be able to be filled and enabling the button (Going from red to green)

### What is actually happening ?

I have to interact with every input in the v-form so it validates even the default inputs. When interacted with it does the expected behavior, changing the button color
### Reproduction Link

https://codepen.io/nelxaz/pen/xLemZB
### Disclaimer
I'm not sure if I'm managing this incorrectly and could/should be done another way so it can animate the button. Thanks for reading.

**Comment by Saduff** [comment]
+1, I just ran into the same issue where I have an optional text field. Have to click on the text field and blur it for validation to pass.

**Comment by nekosaur** [comment]
I'm not sure I understand. What exactly is not working in the codepen you posted?

**Comment by Saduff** [comment]
Don't touch the name field. Type in a valid email and select an item. The Submit button should turn green, but it doesn't. Now click on the name field and then anywhere else so it loses focus. Now the Submit button turns green.

I have the same problem, but in a stepper with a disabled button. There is an optional text field with no rules. Can't click on the Continue button (it's disabled) to advance the stepper without focusing the optional field first (to enable the button).

**Comment by KaelWD** [comment]
This is fixed with #1581

**Comment by johnleider** [comment]
I can confirm that #1581 resolves this. This ticket will close once that is merged

**Comment by Saduff** [comment]
> @Saduff Can you post a codepen with the stepper issue so I can test my changes against it?

It's not really related to the stepper. I'm sure if the button turns green like it's supposed to then the button in the stepper will also be enabled. The only real difference is just whether you're changing a class like here or the disabled prop. The stepper was more of an example of where this bug might be a problem.
