### ISSUE TITLE
[Bug Report][2.6.12] Cannot create eager expansion panel from v-data-table

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#16013]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.7.13
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Description:
I have a table with expansion panels. Each expansion panel contains a cutom vue component.  I need each of those custom vue components 'created' methods to be called as soon as the table is created. 

Issues:
 - There is no 'eager' prop to achieve this in v-data-table.
 - There is an 'eager' prop in https://vuetifyjs.com/en/api/v-expansion-panel-content/ but there is no way to access it from the v-data-table.
 - I am forced to create custom code to loop through all records, expand them, and then close them.  This is undesirable and showcases another bug, mentioned below
 - There is an issue with paging and creating the custom vue components in the expansion section.  If the paging shows records 1-10, then only the first ten records will have their created method called.  If there is an 11th, 12th, etc record, their created methods will not be called.  This is demonstrated in the codepen link above. You can look at the console output and you will never see the 11th record's created() function called, even though there are 11 records in the expanded.sync object

### Expected Behavior
I expect an eager property to exist on the v-data-table which maps to the v-expansion-panel-contents eager property and for it to work regardless of paging

### Actual Behavior
There is no way to access the eager property and my workaround is too buggy to use due to paging issues

### Reproduction Link
[https://codepen.io/uglyhobbitfeet/pen/dyKGeyz?editors=1011](https://codepen.io/uglyhobbitfeet/pen/dyKGeyz?editors=1011)

**Comment by KaelWD** [comment]
VDataTable doesn't use expansion panels, it's a completely separate implementation.

> I expect an eager property to exist on the v-data-table

This is possible, but "for it to work regardless of paging" isn't going to happen so there's probably not much point adding it.

**Comment by UglyHobbitFeet** [comment]
What would be the correct course to have this functionality working with
paging? Would a user have to custom code tables from scratch or is there a
better way?

FWIW The reason I am using it....
I have a data table with expansion rows.  Inside the expansion rows are
other tables with data and select (some/all/none) checkboxes. These
checkboxes need to be set regardless of whether the user visits the
expansion row or browses to the page that contains the expansion rows'
parent. Currently the content in the expansion rows show up as
null/undefined (for other pages) which breaks what I'm trying to do.

Thanks!
