### ISSUE TITLE
[Bug Report][3.0.0] VTextField should not swallow enter keystroke

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#16015]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Chrome 104.0.5112.126
**OS:** Linux x86_64

### Comment

I'm using a VTextField outside of a form. My app should take action when the text field is defocused or the user hits enter. I can use the update:focused field for the former, but the VTextField silently swallows the enter keystroke and I apparently cannot attach an event to it.

### Actual Behavior
When hitting the enter key nothing happens

### Steps to reproduce
- open the codepen
- click on the text field, the focus chip shows "true"
- type something
- hit enter, nothing happens
- hit tab, the field is defocused and the chip shows it

### Expected Behavior

- when I hit enter I expect the field to be defocused, or to have a way to capture the event and defocus it explicitly

### Reproduction Link
[https://codepen.io/codesurfr/pen/NWYVZpP](https://codepen.io/codesurfr/pen/NWYVZpP)

**Comment by tve** [comment]
Thanks to jacek in discord I learned that I can capture the enter keystroke using `@keypress.enter`, is that documented somewhere or is that something I'm just supposed to know?

Using the @keypress.enter I'm setting the VTextField's `focused` prop to false but nothing happens. Is that expected? I can provide a codepen for it, if desired.

**Comment by Z3rio** [comment]
@keypress.enter would be a default Vue function, not something that has to do with Vuetify.
I dont believe this is an real issue, more or less you are just trying to use the input incorrectly.
https://vuejs.org/guide/essentials/event-handling.html#key-modifiers

Here is a copy of your pen, edited to trigger the submit function and remove focus when enter is pressed.
https://codepen.io/Zer1o/pen/oNybOqE?editors=1111

I hope this helps
