### ISSUE TITLE
[Bug Report][3.0.0] No `v-list-item--link` if there is only `@click` on `VListItem`

### ISSUE THREAD

**Issue by 0140454** [vuetifyjs/vuetify#16014]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 3.0.0-beta.15
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Add `@click` on `VListItem`

### Expected Behavior
There is `v-list-item--link` class to make cursor be `pointer`

### Actual Behavior
No `v-list-item--link` on `VListItem`

### Reproduction Link
[https://codepen.io/0140454/pen/mdxePOw?editors=1010](https://codepen.io/0140454/pen/mdxePOw?editors=1010)

**Comment by pavloniym** [comment]
Confirmed!
In  3.0.0-beta.15 it was okey

**Comment by flahol** [comment]
Confirmed too
And item on-hover does not highlight the background if @click and no link

**Comment by stratdev3** [comment]
same here, discovered the bug to my own yesterday.

A workaround is to set a fake `:value` property to get the element appear clickable (cursor: pointer)

**Comment by NoraH1to** [comment]
pr here #16033
