### ISSUE TITLE
[Bug Report][3.0.0] value and model-value behave differently for VTextArea

### ISSUE THREAD

**Issue by Agapanthus** [vuetifyjs/vuetify#16027]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 2.6.12
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use the `value` prop to set the initial value of v-textarea and use the `label` prop

### Expected Behavior
value appears immediately

### Actual Behavior
value appears only after clicking the text-area

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtkM1OwzAQhF9l8SUg0ST8XaIUCXHhDThgDqbZIkvrteVsoqKq7866QQJuPdQXe6yZz95525unlOp5QtOZftxknwRGlCk9WvYhxSywh4xbOMA2xwCVWivLljeRRwHPXryj58iCLLAu1svqBYkivMZMw0V1ZblvFrIyVQiGRE5QFUA/r1wqj4EuFcF5hlG+CNfWJDcMnj+7hzbtrPkxHW2CO3EZHZD7QFLrcbcGutnRVLL/f6bpvvmNnYYKcUBanQ+o0xXiiaxyVdpYalKx9NQ3f/ozh2tzV9/W9zemHNq6Ne/fjVecdA==)

**Comment by TMcKinley** [comment]
https://next.vuetifyjs.com/en/api/v-text-field/#props-model-value

https://next.vuetifyjs.com/en/getting-started/upgrade-guide/#components

> value prop has been replaced by model-value on components that support v-model usage.
