### ISSUE TITLE
v-list hydration issue when <a> tag is inside

### ISSUE THREAD

**Issue by devmattrick** [vuetifyjs/vuetify#1602]
### Steps to reproduce
1. Include an `<a>` tag in a v-list's content when using SSR

### Versions
This has been tested on the latest Vuetify version (0.15.2), vue-server-renderer version 2.4.2, vue version 2.4.2. Browser version shouldn't be relevant.

### What is expected ?
List is properly server rendered and hydrated on the client side.

### What is actually happening ?
List is not properly server rendered. List rendering [is buggy](https://i.imgur.com/LkRTRGP.png) when doing a hard reload. The following error appears in console:

```
Parent:  
<li>
vue.common.js:5528
Mismatching childNodes vs. VNodes:  
NodeList [ a.router-link-exact-active.list__tile--active.list__tile.list__tile--link, div.list__tile__content ]
0 : <a class="router-link-exact-active list__tile--active list__tile list__tile--link" href="/">
1 : <div class="list__tile__content">
length : 2
__proto__ : NodeListPrototype { item: function item(), keys: function keys(), values: function values(), … }
 
Array [ {…} ]
vue.common.js:5529
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

### Reproduction Link
Due to the nature of this issue, it cannot be hosted on codepen or similar, so [here's](https://github.com/devmattrick/vuetify-list-hydration-issue) a Github repo showcasing this issue. The relevant file is available [here](https://github.com/devmattrick/vuetify-list-hydration-issue/blob/master/pages/IndexView.vue). This is based off of the vuetifyjs/webpack-ssr template.

**Comment by johnleider** [comment]
The list hydration is bailing because you are using **to**, or even **href** would cause it, which is creating an anchor tag. You are then nesting another anchor tag within it, which is invalid markup and causing the hydration to bail.
