### ISSUE TITLE
[Bug Report][3.0.5] Content does not move when navigation drawer is expanded

### ISSUE THREAD

**Issue by AniaKru95** [vuetifyjs/vuetify#16022]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.2.37
**Browsers:** Firefox 106.0
**OS:** Windows 10

### Steps to reproduce
I watch navigation drawer's width by adding resize observer.
Bind rail prop to variable, which is updated when onResize function is fired.
My content is moved to left only once. 

When I do not bind rail prop to variable, nav drawer hide my content.

### Expected Behavior
When navigation drawer is expanded,  content should move to right. 

### Actual Behavior
Main content is hide by nav drawer or is moved only once.

### Reproduction Link
[https://codepen.io/AniaKru95/pen/KKezazo?editors=1111](https://codepen.io/AniaKru95/pen/KKezazo?editors=1111)

**Comment by KaelWD** [comment]
`v-model:rail` is missing

**Comment by AniaKru95** [comment]
Unfortunately it does not work.
I've added v-model:rail, navbar-drawer is expanded but when mouse over - navbar does not turn back to its initial width.
