### ISSUE TITLE
[Bug Report][3.0.0] select with chip in compact density alignment issue

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16029]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use the select with chips and use `density="compact"`

### Expected Behavior
Chips should be aligned center. 

### Actual Behavior
chips have 4px margin bottom that causes to not align them.

### Reproduction Link
[https://codepen.io/Alokdev/pen/QWxEpBR?editors=101](https://codepen.io/Alokdev/pen/QWxEpBR?editors=101)
![image](https://user-images.githubusercontent.com/80033712/199899428-f630d2e8-1a1c-4f14-81c6-b69053c3a85c.png)

**Comment by MetRonnie** [comment]
Here's another screenshot. Very noticeable when you use a clear icon 

![image](https://user-images.githubusercontent.com/61982285/221833579-64309de2-dfee-4e1a-adec-46a8dd9094a6.png)

**Comment by MajesticPotatoe** [comment]
duplicate #15980
