### ISSUE TITLE
[Documentation] `Invert Example Color` not working when Dark/System Followed Theme is Enabled

### ISSUE THREAD

**Issue by atharvaunde** [vuetifyjs/vuetify#16032]
### Environment

**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open any component page and Select either one of the following theme from Site settings
1. Dark
2. System

In case of any of above theme, the `Invert Example Color` button on the component preview will not work.

### Expected Behavior
 In Dark / System theme mode, the dark themed components should be viewable with light theme with above mentioned toggle, which is not the case.

when same is done on light theme, the toggle works as expected

### Actual Behavior
When Dark / System theme is selected, the `Invert Example Color` toggle should let user toggle the theme of the component

### Reproduction Link
[https://vuetifyjs.com/en/components/expansion-panels/#advanced](https://vuetifyjs.com/en/components/expansion-panels/#advanced)

### Other comments
Video Demonstrating the same bug:
https://www.loom.com/share/61fc8b05968b4a23aaa3f282bf462568

**Comment by KaelWD** [comment]
This is a limitation of the theme system that is resolved in v3.
