### ISSUE TITLE
[Documentation] SASS Variables usage

### ISSUE THREAD

**Issue by eckbert** [vuetifyjs/vuetify#16031]
### Problem to solve
There are SASS variables in a widget api-documentation, but I had no idea how to use them.

### Proposed solution
Esp. for newcomer it could be helpful, to always have a link to the SASS variable feature region of the documentation in the beginning of each SASS-Variables section , to easily see how to setup und use those variables in the right manner.

**Comment by MajesticPotatoe** [comment]
v2 <https://vuetifyjs.com/en/features/sass-variables/>
v3 <https://next.vuetifyjs.com/en/features/sass-variables/>

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
