### ISSUE TITLE
[Bug Report][3.0.0] v-tooltip is located at wrong position when `:model-value="true"` is set

### ISSUE THREAD

**Issue by KojiAndoJC** [vuetifyjs/vuetify#16042]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.36
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
Put a v-tooltip with attributes `location="top"` and `:model-value="true"`

### Expected Behavior
v-tooltip is placed on the top of its content

### Actual Behavior
v-tooltip is placed on the left of its content.
When the content is hovered, v-tooltip is located at correct position.

### Reproduction Link
[https://codepen.io/kando-jc/pen/ZERpOXx](https://codepen.io/kando-jc/pen/ZERpOXx)

**Comment by kelliedlynch** [comment]
In your example, the tooltip isn't shown at the top because there isn't space for it in its container. Add padding or margin and the tooltip displays correctly.

**Comment by KojiAndoJC** [comment]
@kelliedlynch Thank you for your reply.

My example was misreading. I replaced `location="top"` with `location="right"`.

Initially the v-tooltip is placed on the left of its content (1) .
When the content is hovered, v-tooltip is located at correct position. (2)

(1) wrong position
![image](https://user-images.githubusercontent.com/106056103/201224446-63629253-cb43-41b8-8f9c-f1585ff5056b.png)

(2) correct position
![image](https://user-images.githubusercontent.com/106056103/201224483-40f77551-9505-41c5-9fe0-5c2aa7289b0b.png)

**Comment by dustin-auby** [comment]
This iussue seems to be happening again, the tooltip shows either in the top left corner or in the incorrect position also it is visible from page load. once you hover the tooltip goes away

**Comment by johnleider** [comment]
> This iussue seems to be happening again, the tooltip shows either in the top left corner or in the incorrect position also it is visible from page load. once you hover the tooltip goes away

Please create a new issue.
