### ISSUE TITLE
[Bug Report][3.0.0] V-Text-Field "underlined" and "plain" variants have incorrect spacing with single-line set true

### ISSUE THREAD

**Issue by evans23** [vuetifyjs/vuetify#16048]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 3.0.0-beta.3
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-text-field or v-text-field based component and set the variant to either plain or underlined.
Set Single-line true. (Issue is worse if density="compact")
Click into the text field.
Notice that the cursor position is not centered in the text field.

* This may have been working post Beta 3, not certain of the exact break point, code pen not cooperating when I revert the style sheet. It was caused by a breakage in the vuetify.css stylesheet at some point.

### Expected Behavior
The cursor is centered in the text field.

### Actual Behavior
The cursor is offset towards the bottom.

### Reproduction Link
[https://codepen.io/evans23-the-selector/pen/PoaodZP](https://codepen.io/evans23-the-selector/pen/PoaodZP)

### Other comments
Prior to this breaking fully, the "underlined" variant appeared slightly offset toward the bottom of the field.

**Comment by johnleider** [comment]
This works now https://play.vuetifyjs.com/#eNrVVU1PGzEQ/SsjX2glNilNpUooVOqFayvxdSAcvPZsYsVrW/ZsAkL8d8YbkqyAHBIgiFOy9ps3773R7lzfixRV/28IvVmD4lgMCetgJeGfkQMYzgoZAiS6s3gyEkFqbdz4GH5GrEeihbQgJaMGZWVKjCrHRWmlmkKQxdGPFawFEt5SURm0enkI3br5xBC2dSOxBlhZomXAfyuNgxSkYhFQRj9FdwiqiQkj6OhDAgb6OSh0xEfeMbdR0y7XTEYjHWUzma17pdElQ3d8pXzNTah7mbilxcIah8vDfteYbMjnMou0ArxirS6LwUZ/V56dZNVdst4+1L9pLBdOY8zUGoxTPkZUtJzSs/HQJPpmPIFmWbKa0QabK6D+spP6AAs7jWutyDf0Qs8rLdd2L4vz3PE0d4R/T9XAIUzziygT4G3goXcZd4n8HRWfkbEW5k8KNw/qPWOtuOWuoZ62tfuMdEu1nxFo8tbvFmeu3GeYWyndNsphf7FgFxuZH3gl8/9hv7Oq+TGpaAJ/eJGafA1g6uAjwT1ErOABquhrOOAtf5DhbM+7RKCNtH4MJxn0rZI24fdMvSBjGvFwKAa9Qe+XWPwe/RY3j+Kfg88=

**Comment by ret2src** [comment]
I think this bug is not fixed yet. Using all the latest versions, variant "plain" still has bottom-aligned content, see:

https://play.vuetifyjs.com/#eNqdUcFOhDAQ/ZVJzxZY3D1I0MSLVz0YPYiHoR13my2laQuuMf67BZZAjImJp3Ze573Om/fyybwT6a21Sd8RK1gZqLEaA91UBqDsOVo7XsdCoJMgNHp/XbF6z2uN4ggW+Sar2LltbAx0CvxNkZYzCGve+0EFGnlQt06SA9d2RpKEBnlesYWksSYdSU/8cZC8GyThQaMyBQwImDaAIBPIRXZPLiiBWn+sNXp0Ck2IKtGZMusnr8xeE9fK0AIelCQuKaDSfkbT/7n7aWcZpe3C8Kv8c5pfN3B/Zhfw3LpjpAF6oJMlEdaS89RlOmU3hRqLKdUyXaXNvi7YZbJNdmw6r3iDPq41ybN8y7MNz3bs9Rth9KmK

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
