### ISSUE TITLE
[Bug Report][3.0.0] V-Autocomplete pre selected option not working when using return-object prop

### ISSUE THREAD

**Issue by ThomasCarbon** [vuetifyjs/vuetify#16046]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
Click v-autocomplete field and see there is no option pre selected while vmodel isnt empty.
Remove return object prop and see it working

### Expected Behavior
Make pre selected option work properly when using filled vmodel and return object prop

### Actual Behavior
Pre selected option doest not work when using filled vmodel and return object prop

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkctuwjAQRX9l5A2tBOHRrmiohNS/wCxMMqiuHNuyJ2wQ/96xQ9JEohKziDJ37jxycriKvffFpUWxFWWsgvYEEan1n9LqxrtAcIWAZ7jBObgGZmydSSstQOVsJKgVKdgly8shqdf0APDB+fUWpCBNBtdSzP/0TdIvyrRJT/ItFx92bv7pZL3vPL5+pIO6cyIarAjrr2fOenY4gLTlsqPDXDghbLxRhJwBlJeF8glYmsRJo7S9Z52gWnKV4w4kHHQOtroazU6K8dnd8j62mndFtiTQ09Ikqm/t47ga+C8Gu3CnH548Lhh1yjv3MbpK80fU0EYM09lp6yJDYmem9qCeYd3rd2Z9NK0hzR88cCiXUw49LpYHXtmTSZbLEWFxm4u3YlO8r0V6WRUrcfwFOI3RcA==)

### Other comments
Thanks Andrew for your help on discord. He said himself its a bug

**Comment by evans23** [comment]
This is wider than just pre-selected items. I'm also seeing items that I select disappear as well.

**Comment by cory-weiner** [comment]
I'm having a lot of issues as well with the autocomplete. 

See example below.  Per the documentation shouldn't item-title render the "name" property of the object? This functionality has always worked perfectly in Vue 2

https://play.vuetifyjs.com/#eNpdj81OwzAQhF9l5UtAapM2wCWkSBx4Anqre7DSrWQp/lG8ySXKu7N26hbwxZ6dGevb0yw+vS+nEUUj2tAN2hMEpNF/SKuNdwPBDANeYYHr4AwUHC2klRagczYQaEIT4BAzT6cZ9KWBuq73bxuwymADxfHr+1jAcn5+j7W1FLDHjrSzt2JqxACAtG21cjABC/7e94qQFUA7bZWPaMCHhVHa3tRqjuQ6xwUkzOMmER6kSLcUeR7lljT1yF5k/WdNqh+jpS8Po8nD+wLZe1BUfzEyLI/vtCmT9mirX/uJZSNeyrp83Yv42JU7cf4B+N+Ckw==

**Comment by ThomasCarbon** [comment]
@evans23, i do not have this issue at all, i think its a problem on your side, try to post a playvuetify about it

**Comment by evans23** [comment]
@ThomasCarbon Yep, you appear to be correct!

**Comment by ThomasCarbon** [comment]
@vexleet You'r a goat. Thanks for the PR
