### ISSUE TITLE
[Bug Report][3.0.0] v-drawer rail pushed off-screen when developer tools panel opened

### ISSUE THREAD

**Issue by kelliedlynch** [vuetifyjs/vuetify#16040]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Tested in Chrome and Safari:
- Open dev tools window
- Move dev tools window to right side of screen

### Expected Behavior
Rail should stay where it is

### Actual Behavior
Rail disappears off-screen

### Reproduction Link
[https://codepen.io/kelliedlynch/pen/PoaGeeE?editors=101](https://codepen.io/kelliedlynch/pen/PoaGeeE?editors=101)

**Comment by jacekkarczmarczyk** [comment]
When you open dev tools the width of the view port changes and vuetify goes into mobile mode where navigation drawer becomes temporary, you can prevent this by using `permanent` prop

In 2.x there was `mobile-breakpoint` prop which seems to be gone in 3.x, but you can set the value globally in `display` property of Vuetify options
