### ISSUE TITLE
[Bug Report][3.0.0] V-Tooltip does not works with v-icon

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify#16047]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
MouseHover on icon : no tooltip
MouseHover on button : tooltip

### Expected Behavior
MouseHover on icon : tooltip
MouseHover on button : tooltip

### Actual Behavior
MouseHover on icon : no tooltip
MouseHover on button : tooltip

### Reproduction Link
[https://codesandbox.io/s/festive-architecture-np537k?file=/src/main.js](https://codesandbox.io/s/festive-architecture-np537k?file=/src/main.js)

**Comment by jacekkarczmarczyk** [comment]
`v-bind="props"`
