### ISSUE TITLE
[Bug Report][2.6.12] Toolbar feature 'bottom' does not work

### ISSUE THREAD

**Issue by MayaElf** [vuetifyjs/vuetify#16059]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. open Toolbar
2. put 'bottom' feature

### Expected Behavior
Aligns the component towards the bottom

### Actual Behavior
Does not align the component towards the bottom

### Reproduction Link
[https://codepen.io/MaiiaAfanaseva/pen/VwdPbVy?editors=101](https://codepen.io/MaiiaAfanaseva/pen/VwdPbVy?editors=101)

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

Bottom will not do anything without either absolute or fixed also.

**Comment by MayaElf** [comment]
@KaelWD thank you so much for your assistance! In api https://vuetifyjs.com/en/api/v-toolbar/#props I find only 'absolute'. So we do not have 'fixed' option. Is that right? Thanks in advance!
