### ISSUE TITLE
[Bug Report][3.0.0] Pressing letters on the keyboard does not select items in VSelect

### ISSUE THREAD

**Issue by rotsee** [vuetifyjs/vuetify#16055]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 2.6.12
**Vue Version:** 3.2.42
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a simple select menu with VSelect:

```
<v-select
  label="Select"
  :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
></v-select>
```

### Expected Behavior
Pressing a letter on the keyboard should select the first item beginning with that letter, as is the deafult behaviour of browsers in html select menus

### Actual Behavior
Pressing a letter does nothing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUN1qwjAUfpVDbrJBl4ruSupgCNsDbGwX1ousnkpG/kiiKKXv7mlTUXP1/Z2TL9l07HjApNqz+I9syZTxLiTooAkoE/5kD3pogzPApyyvbW3xNEYbZ2OCyYDV4+BT1z/XlhXs3XtBGbqhik1QPkHEdPBvta3KLBAkktB4TfPEAKrji/RDBugQMVLZiY08osYmXQUALf9Qr2r2lXV2c5aKFkeyNnwttWpdsEryAvjaaRfkzg34g6DajfInurDPiW88yTiA37Mzyu759ra4vHYr78oNJNeuyrvnsL5gCzEXr3P6joWYiRnbXgA3CHo7)

### Other comments
Compare 
https://next.vuetifyjs.com/en/components/selects/
to
https://vuetifyjs.com/en/components/selects/

See also: https://github.com/vuetifyjs/vuetify/pull/15632

**Comment by yuwu9145** [comment]
v2 implementation: #4853
