### ISSUE TITLE
[Bug Report][2.6.12] VAutocomplete resets search while typing

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#16064]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.7.14
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
Type within the autocomplete, trigger a v-model change while you're typing or within the request

### Expected Behavior
The search to not reset while the input is focused

### Actual Behavior
It still resets

### Reproduction Link
[https://codepen.io/Tofandel/pen/GRGWrPa?editors=101](https://codepen.io/Tofandel/pen/GRGWrPa?editors=101)

### Other comments
According to https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L400-L402

This should not happen, but using some breakpoints it seems `isFocused` is false even while typing and this is what triggers the bug

Related #4273, #4403

**Comment by KaelWD** [comment]
This is triggered by https://github.com/vuetifyjs/vuetify/blob/f16c2c506bc73074866859cbd798086801a9b1da/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L165

**Comment by Tofandel** [comment]
I was just typing to say the same thing, the repro is not reproducing my real issue correctly

**Comment by Tofandel** [comment]
Well it does seems it was a correct repro, after caching the modelValue and only changing it if the id changes, the behavior is good, maybe we could add an internal check in the watcher if the new value is really different than the last one using the valueComparator, then we can trigger the setSearch. With vuex, some watchers have the tendency to fire more than they should and give a different reference to the object (which was my issue and demonstrated in the codepen)

I do have another issue now, it's that when I backspace to clear the search the last selected item comes back into the search, instead of being cleared like on the codepen, but for now that's good enough, it's not a blocking issue, I gave up on debugging this😅
