### ISSUE TITLE
[Bug Report][3.0.0] Icon doesn't render if we use button icon as activator for menu

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#16060]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.44
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Check the output

### Expected Behavior
Icon should get rendered

### Actual Behavior
Icon isn't rendering

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UctugzAQ/JWVL7RSIFGaU0QiVT33C+IcXOKoVrCxzIIaIf69u7wKSq8xBzyz433NqRHv3id1pcVepGUWjEcoNVb+KJ2xvggIDQR9hRauobAQkTSSTrqscCWCQW1LOMBJOhhOA2gw13uIPnKT3eBTR9CunhmH7Vxxli5d95PQDASoRZ8r1IQA0jpWnodjKQGrjPtDX0gP+jRZkRfhIIUPxqpwl4JyIX+GJifeXkz8XVjNAdZ3tfqnnFa7ClSGplbYp1FBO5RiqDXIclNykyMzcTHvdc4D1PG1S/TCoRUYd9E/r/TrLRi7GM/+pu8k7lQPsVrllf4/umhm2U7crf3YNF3FpEPQtun6UbOYaB6fTz/wE8UEr210gyDZMUOTVQx6E9P1zFzRrsRbsk12O8GXTbIR519xNthN)

**Comment by jd-solanki** [comment]
On the other side, it can also be a question: How to use the button icon as a menu activator without extra markup as this usage is normal and used by many

**Comment by KaelWD** [comment]
v-btn's default slot overrides props.icon, you either have to use the menu's activator slot, or put a v-icon in the button normally.

**Comment by kappaflow** [comment]
I think it might be useful to post an example how it can be used:
```html
<v-btn
  color="orange-darken-2"
  icon
>
  <v-icon icon="mdi-content-copy"></v-icon>
  <v-snackbar
    activator="parent"
    timeout="3000">
    My timeout is set to 3000.
  </v-snackbar>
</v-btn>
```
https://play.vuetifyjs.com/#eNqNU91u2yAUfpUjbtpKwWTNneVG3QPsCUoviKEbiw0ITrxGkd99B2x3WaIq9YUN5+f7OeCXE/seQjUcDKtZg6YPnUKzlQ6g0XaAtlMpPUmG5h15axyaKFlJA0zvZuA7dNMaWt/5SOU+KvfTcK3i3jj+KNmct613lO615bRCwqNvOC75GbgRBfNzmps8heg/zIKQo59r2GbenD1vSU61+52KS0i1aAeFhT2oSN3/SNH2xh+QMpv1ev0xp/ycTpBHCOP4gU1kC3gplHjtuxF0CLRvxNnRNKmNNmApM+/BRwRt3tShQzhNrVqhquH+AZ62cD/HSB4JqOHux3ERCjZBMgjoIQuu7lZT6fhQFiS1ETMXW7HOun2qfifv6KoUUMnalCSr4WVWzH4hhlQL0WpHldp0doiVMyhc6AVdMrRvx+dN9VhtyFjCJcQ7tUtVActIr9KNRGj77I33KlywTonCPJuTjJDy/oaEZyoT8eDyALj2PWnZVN8mLWfhyqSe76L/k0wkEMnmwRSaLPgLVLfcEsUVtCC+wURO10qbmH+1rzm6aDt3dZG6cjYf9MjGFSttNPgimb3+BRBiUgk=

**Comment by italomaia** [comment]
Interesting that:
`<v-btn icon="something" />`

Is not the same as:
`<v-btn><v-icon icon="something" /></v-btn>`

But:
`<v-btn icon><v-icon icon="something" /></v-btn>`

Thank you for your example, @kappaflow
