### ISSUE TITLE
dialog styles

### ISSUE THREAD

**Issue by trippal** [vuetifyjs/vuetify#1606]
Hi,
I have fased with dialog style. There is no opportunities to change dialog style.

name: 'v-dialog',
props : {
    dialogStyle: String,
}
render ...........
if (!this.fullscreen) {
     data.style = this.dialogStyle;
}
may be better set full style, not only width.

Also, strange thing, when I use tabs in dialog, they are not correctly displayed. I should resize window to display them correctly or use v-if="tabsData"

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
