### ISSUE TITLE
[Bug Report][3.0.0] Vuetify Autocomplete not honoring item-title prop with value

### ISSUE THREAD

**Issue by cory-weiner** [vuetifyjs/vuetify#16078]
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Passing in a default to the autocomplete via :value prop does not honor item-title property. Changing :value to v-model in this example DOES honor the item-title prop.

### Expected Behavior
To see "TEST" in the autocomplete selection

### Actual Behavior
I see the ID

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj81OwzAQhF9l5UtAapM2wCWkSBx4Anqre7DSrWQp/lG8ySXKu7N26hbwxZ6dGevb0yw+vS+nEUUj2tAN2hMEpNF/SKuNdwPBDANeYYHr4AwUHC2klRagczYQaEIT4BAzT6cZ9KWBuq73bxuwymADxfHr+1jAcn5+j7W1FLDHjrSzt2JqxACAtG21cjABC/7e94qQFUA7bZWPaMCHhVHa3tRqjuQ6xwUkzOMmER6kSLcUeR7lljT1yF5k/WdNqh+jpS8Po8nD+wLZe1BUfzEyLI/vtCmT9mirX/uJZSNeyrp83Yv42JU7cf4B+N+Ckw==)

**Comment by KaelWD** [comment]
https://next.vuetifyjs.com/en/getting-started/upgrade-guide/

> value prop has been replaced by model-value on components that support v-model usage
