### ISSUE TITLE
Set v-tabs initial selected tab use v-model not working.

### ISSUE THREAD

**Issue by ufosky** [vuetifyjs/vuetify#1607]
I want a tabs as a sticky header in a list, but now I can't set the initial selected tab, this is my code on codepen: https://codepen.io/ufosky/pen/QMRWgN
When load the page,there is no selected tab, although I set the `v-model` property, but no effect.

**Comment by jacekkarczmarczyk** [comment]
You codepen is invalid:

1. you have `:v-model="current_key"`, should be `v-model="current_key"` (remove colon)
2. `current_key` must be tab name, not tab index, for example `"tab-3"`

Working codepen: https://codepen.io/anon/pen/gxJGLo

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by mixinmax1990** [comment]
hey there. I have the exact same issue. jacekkarczmarczyk  your code isnt actually working the tab is not selected upon refresh.

**Comment by jacekkarczmarczyk** [comment]
@mixinmax1990 Please create a new issue using the provided bug report template and including the link for reproduction. Thank you
