### ISSUE TITLE
[Feature Request][3.0] v-img Add full support for `object-position`

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#16089]
### Problem to solve
In 3.0, we see that the v-img component has changed it's implementation compared to 2.x and with that it's props have changed. There is no longer a way to set the position of an image. Let's say that I use the cover prop on v-image, and the focus point is on the bottom of the image. When using the cover prop, there is a chance that the bottom part of the image will automatically be cropped out. I can't do anything about it without doing css (example assumes you're using scoped css) `v-img :deep(img) { object-position: center bottom; }`

### Proposed solution
Please add a position prop that will apply a 'object-position` style and value to the `img` tag. This way we can set the position of the image.

Also, side note - Please consider this situation: https://www.youtube.com/watch?v=d9i68C628Nk

**Comment by ElYaiko** [comment]
Yes, `position` prop is necessary for using `object-position` css, any update? @vuetifyjs
