### ISSUE TITLE
Tabs inside the expansion panel won't display the tab-slider

### ISSUE THREAD

**Issue by razorfever** [vuetifyjs/vuetify#1609]
### Versions
vue. 2.4.2
vuetify 0.15.2

### What is expected ?
When opening an expansion panel with tabs inside the selected tab should have an underlining beneath it.

### What is actually happening ?
Tab slider does not calculate its length and thus is zero.
Click on tabs resolves the issue.

### Reproduction Link
https://codepen.io/anon/pen/YxgLVp

**Comment by johnleider** [comment]
Oh buddy, this is going to be interesting. The slider is called programmatically on boot, but being hidden inside the content, it doesn't know where to go actually.

I'll see what I can do to remedy this, for now, you can workaround by assigning a **ref** to the tabs and when you open the expansion panel, calling ```this.$refs.tabs.slider()``` where **tabs** is whatever you assign to the ref.

**Comment by johnleider** [comment]
So recently ```v-expansion-panel-content``` received **lazy** support. Due to how ```v-tabs``` works, this will be necessary to receive your intended outcome, or the suggestion above.
