### ISSUE TITLE
[Feature Request] Drag external event lists inside calendar

### ISSUE THREAD

**Issue by menteora** [vuetifyjs/vuetify#16097]
### Problem to solve
It's possibile to drag events inside calendar? (see picture below)

### Proposed solution
![This is an image](https://user-images.githubusercontent.com/41521881/46624532-e8fcc000-cae5-11e8-8af1-2c89da6caed4.png)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
