### ISSUE TITLE
[Bug Report][3.0.1] v-tooltip hover listener leaks to parent elements

### ISSUE THREAD

**Issue by kurbar** [vuetifyjs/vuetify#16094]
### Environment
**Vuetify Version:** 3.0.1
**Last working version:** 3.0.0-beta.15
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a VTooltip button to e.g. VToolbar.
2. Hover the button - tooltip shows
3. Hover the parent toolbar - tooltip also shows

### Expected Behavior
Parent toolbar should not show the button tooltip on hover

### Actual Behavior
Parent toolbar shows the button tooltip on hover

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUctOwzAQ/JXFl4BEU56XKq0EJ/6AA+bgNg5YcryWvQlIUf6dNQ15lOaUGc/O7s6+deLJ+7xttNiIIh6C8QRRU+N30pnaYyDoIOgKeqgC1pCxNJNOugO6SFDHD9im98vsRVuL8IrBlhfZlXTF+mjHRgxI194q0owAinalfOoA/DGolXED+sWEaPcqjJQkJvc0aRL13BChA4eQ5GT89FisT+WDKatAHci0ijBspfAqaEdSQKuCUY6YqnhKKRadxuGhXUWLtJlbdOAD+gj9omiamWv2xpWpWdKdqJLuy9Dn/x3O75G4RZSjzVwSvXK7wZHPkNAynOFtynzg5qGnyPQ3rSqjbclb1Fhqy2vwyTmw9d/1uHI8XwLHwy6mFP21uM/v8odHkX5u8lvx/gPCGL/o)

**Comment by KaelWD** [comment]
Uh yeah you have `activator="parent"`

**Comment by kurbar** [comment]
So it was actually broken in 3.0.0-beta.15? Just that it worked before hence my confusion with it since I didn't see any commit message referring to it.

**Comment by KaelWD** [comment]
You can change the version in the playground to see for yourself. This is working as intended though, don't use activator="parent" if you don't want the parent to activate it.
