### ISSUE TITLE
[Bug Report][3.0.1]  VAutocomplete - a11y issue when hitting TAB to navigate dropdown suggestions

### ISSUE THREAD

**Issue by demariaw** [vuetifyjs/vuetify#16098]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Search for an item 
2. Use TAB to access the VAutcomplete.
3. Hitting TAB closes dropdown instead of navigating through suggestions

### Expected Behavior
Hitting TAB closes dropdown instead of navigating through suggestions

### Actual Behavior
Hitting TAB should navigate through remaining suggestions

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVT8tqwzAQ/JWtLmohtfu8BCdQAm0/oJBDlIOw10YgaYUkh5aQf+/KLmkiXWZ2Z3dmd0fxFkJ1GFEsRZPaaEKGhHkMa+WNCxQzHCFiDyfoIzmQLJXKK9+STxlcGmBV+rfyE60l2FK03Y28U76p53W8iElGF6zOyAygOdzrUByAHxOnjf9jc3PM1BIPYEZYGp5NKyV2cqOt6Sl6o+UC5IYsRd1Rwe8MTTeVP5DiMCu+8FunArY/5Iwf5F6Jf5/62mit8vnPwVhwTjapp8xNfXGLOC3Ec/VUvbyKAh6qR7H/BfAvbgg=)

**Comment by KaelWD** [comment]
> Hitting TAB should navigate through remaining suggestions

No it shouldn't. Arrow keys are for list navigation.
