### ISSUE TITLE
[Bug Report][3.0.1] VCombobox - Duplicate values removed

### ISSUE THREAD

**Issue by Chloe-Bang** [vuetifyjs/vuetify#16100]
### Environment
**Vuetify Version:** 3.0.1
**Last working version:** 3.0.1
**Vue Version:** 3.2.38
**Browsers:** Chrome 107.0.0.0, Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Enter a new value (ex: "Test") in the v-combobox.
2. Press enter > created new chip "Test".
2. Enter duplicate values "Test".
3. Immidiately removed all "Test" chip.

### Expected Behavior
Do not remove duplicate values all.(like Vuetify2)
If the values are the same, the duplicated values are displayed.

### Actual Behavior
Removed all duplicated value like a toggle.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplkT1vgzAQhv/KyQutRKFtlgrRSJW6dOvUJWQwcKGWbGwZE6WK+O897CQmiTz43ude6z68ObIPY7L9iKxg5dBYYdy66gHwYLR10OKOj9LBcWYALXccHh7PEsCiG20fNcCAEhtXwCb5GdGJ3V+SQvJtdWe5UqLvkm0azcKhGsgbCVybF17KfOIguv4GUpl7EgpHGotOIZg8IFHml6lJUD9Gcod+B+X+iRvjQy8UF/1sc/Mh3WhV61oflsXJpVuU7xULi6jYMlv4gSnp7+uc5LV/9wXjgND8CnNjUPQRwkhcsmC7gHWZx7bOjRM6dR5EmKnMF7OyKWWr7DVbvbE5eM5e2PYfQ8yZ6g==)

### Other comments
Is it possible to control duplicate values of filter-mode('every' | 'some' | 'union' | 'intersection')?
But filter-mode is not working and missing description on the API Docs.

<details>

[Vuetify ver.2]
![화면 기록 2022-11-16 오후 4 58 04](https://user-images.githubusercontent.com/23013469/202121753-0ee28204-1c29-4812-8f1e-d99d07458028.gif)

[Vuetify ver.3]
![화면 기록 2022-11-16 오후 5 00 32](https://user-images.githubusercontent.com/23013469/202122053-0a5a7a4e-7954-44fa-af29-1f0590e70180.gif)
</details>

**Comment by ashxdev** [comment]
Hi, is there any news about this issue? May Are some possible fixes?
