### ISSUE TITLE
[Bug Report][3.0.1] v-tabs do not scroll when placed inside extension slot of v-app-bar

### ISSUE THREAD

**Issue by timstallmann** [vuetifyjs/vuetify#16116]
### Environment
**Vuetify Version:** 3.0.1
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Firefox 107.0
**OS:** Mac OS 10.15

### Steps to reproduce
When the `<v-tabs>` component is placed within the `extension` slot of a `<v-app-bar>` component it no longer displays left/right scroll buttons or allows manual scrolling.

### Expected Behavior
`<v-tabs>` should keep the same behavior regardless of where it is placed in the app layout

### Actual Behavior
When placed inside `<v-app-bar>` extension slot the scroll indicators disappear.

### Reproduction Link
[https://codepen.io/tim_maps/pen/zYaPYbg?editors=101](https://codepen.io/tim_maps/pen/zYaPYbg?editors=101)

**Comment by timstallmann** [comment]
Here's an image of the codepen demonstrating this issue.

![Screenshot 2022-11-17 at 2 41 21 PM](https://user-images.githubusercontent.com/6741938/202543438-3d4c665a-0e77-4118-bd21-ffcc2f0f2475.png)

**Comment by NoraH1to** [comment]
pr here #16118
