### ISSUE TITLE
[Bug Report][3.0.1] VListGroup v-model not working

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16115]
### Environment
**Vuetify Version:** 3.0.1
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I add a v-model to the VListGroup

### Expected Behavior
The value to be mutated

### Actual Behavior
The VModel not being mutated when I open the list group activator

### Reproduction Link
[https://codepen.io/elyaiko/pen/mdKqdLO](https://codepen.io/elyaiko/pen/mdKqdLO)

### Other comments
I'm trying to open/close the item group via VModel.

**Comment by nekosaur** [comment]
VListGroup does not have v-model support in v3. The entire list is controlled by v-model:open on VList
