### ISSUE TITLE
[Bug Report][3.0.1] Vitessg Unknown file extension ".css" when running build

### ISSUE THREAD

**Issue by boussadjra** [vuetifyjs/vuetify#16121]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
run the build  
       
       npm run build

### Expected Behavior
expected the build runs successfully and I can preview it locally or deploy it

### Actual Behavior
I get this error :
>TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for D:\..\vuetify3-template\node_modules\vuetify\lib\directives\ripple\VRipple.css

![image](https://user-images.githubusercontent.com/11801238/202679089-c61c7781-6f96-47dd-a061-a5686980b956.png)

### Reproduction Link
[https://github.com/boussadjra/vuetify-3-template/tree/vite-ssg-vuetify-issue](https://github.com/boussadjra/vuetify-3-template/tree/vite-ssg-vuetify-issue)

**Comment by nekosaur** [comment]
```js
ssr: {
  noExternal: ['vuetify']
}
```
in vite config

**Comment by rudolfbyker** [comment]
@nekosaur would you please explain why that works?

- The docs are very cryptic https://vitejs.dev/config/ssr-options.html#ssr-noexternal
- What does SSR have to do with tests? I would not expect anything under the `ssr` config to have any bearing on tests.
