### ISSUE TITLE
[Bug Report][3.0.1] Events not working on both v-select and v-autocomplete

### ISSUE THREAD

**Issue by pattnaik-soumitri** [vuetifyjs/vuetify#16120]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

## Setup & Run

```
git clone https://github.com/pattnaik-soumitri/vuetify3-select-issue.git

cd vuetify3-select-issue

npm install

npm run dev
````

## Reproduce the issue

- Open chrome **console** from dev tools.
- Pick a fruit from the only dropdown available on the screen.

### Expected Behavior
- You should see a console output `It Works!` upon option selection on the select element.

### Actual Behavior
- The console output is not coming up.

### Reproduction Link
[https://github.com/pattnaik-soumitri/vuetify3-select-issue](https://github.com/pattnaik-soumitri/vuetify3-select-issue)

### Other comments
- Looks like the events on `v-select` and `v-autocomplete` are not working in Vuetify 3.
- I have tried `@change`, `@click` etc on both `v-select` and `v-autocomplete` elements and found the same behavior.

**Comment by KaelWD** [comment]
v-model in vue 3 is always `model-value` and `@update:model-value`

**Comment by moinologics** [comment]
why @change was removed from vuetify??
