### ISSUE TITLE
v-tabs-bar wrong color

### ISSUE THREAD

**Issue by dorbal** [vuetifyjs/vuetify#1612]
### Steps to reproduce
Use ligth theme.

### Versions
0.14, 0.15

### What is expected ?
I can read the active tab text.

### What is actually happening ?
A can't read, because the text color and the background color are the same.

### Reproduction Link
https://codepen.io/anon/pen/QMRKXB

**Comment by jacekkarczmarczyk** [comment]
Tabs theme should be dark: 

```html
<v-tabs dark v-model="active">
```

**Comment by johnleider** [comment]
https://codepen.io/anon/pen/EvzmXP

You have light set explicitly when the background is blue. In ```v-tabs``` case, light indicates that it has a light background, dark indicates that it has a dark background. This also adjusts the text color to accommodate.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by dorbal** [comment]
I see. Thanks.
