### ISSUE TITLE
[Documentation] Vuetifyjs 3 Scroll directive $vuetify.goTo

### ISSUE THREAD

**Issue by mathieuOdobescu** [vuetifyjs/vuetify#16122]
### Environment

**Browsers:** Firefox 107.0
**OS:** Windows, Windows 10

### Steps to reproduce
1. follow reproduction link and find the form
2. Open console web. 
3. Select  "DomElement" as target
4. Select "Radio group" as the DOMElement target
5. Click on button "SCROLL"

### Expected Behavior
Expected to scroll the web page to the target element

### Actual Behavior
Nothing move, the page freeze and the console throw error 

### Reproduction Link
[https://next.vuetifyjs.com/en/directives/scroll/#usage](https://next.vuetifyjs.com/en/directives/scroll/#usage)

### Other comments
Error i have in the web console :

**TypeError: n.$vuetify.goTo is not a function**

Function goTo seem to not exist anymore.

**Comment by nekosaur** [comment]
Removed the usage example. It is not yet decided if goTo will be implemented in v3
