### ISSUE TITLE
[Bug Report][2.6.12] Taking screenshot on MacOS causes shift key to get stuck.

### ISSUE THREAD

**Issue by ax-jstern** [vuetifyjs/vuetify#16128]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.14
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Have a table with multi-select enabled in focus, hit CMD+Shift+4 to take a screenshot. Hit ESC to cancel screenshot (or just take the screenshot). Try selecting checkboxes (no keys held down). Reproduction link is from codepen for [this Vuetify documentation](https://vuetifyjs.com/en/components/data-tables/#row-selection)

### Expected Behavior
The checkboxes should select in single select mode as per usual.

### Actual Behavior
Vuetify thinks the shift key is held down and will be stuck in multi-select mode until shift is pressed again.

### Reproduction Link
[https://codepen.io/jeffreystern/pen/poKdxrb?editors=101](https://codepen.io/jeffreystern/pen/poKdxrb?editors=101)

### Other comments
This is due to a quirk of MacOS meta key handling (at least in chrome). It will give keydown events for the keys but will not give a keyup event. For example, CMD+A will give a keydown for CMD and A, but only give a keyup event for CMD. Same happens with shift here when taking a screenshot. A potential workaround would be to check for metaKey in keydown handler and clear the shift flag, and don't allow it to be set until the meta key is released. See [this line in VDataIterator](https://github.com/vuetifyjs/vuetify/blob/v2.6.12/packages/vuetify/src/components/VDataIterator/VDataIterator.ts#L163) for shift handling. Alternatively this could be deemed not worthy of fixing and Mac users will just have to live with it. Seems to be an issue with all versions since the shift selection was added.

Here's a screengrab showing the behavior. No keys are held before or after the screenshot.
![ShiftSticking](https://user-images.githubusercontent.com/88679847/202806496-36b3c129-6048-4edc-8b08-882e94ff9534.gif)

**Comment by gosear** [comment]
yes. i have the same problem.
![Peek 2023-03-22 11-08](https://user-images.githubusercontent.com/59965827/226792244-51e0219f-64e8-4c54-acc8-cd565c34d2de.gif)
I think this problem caused by  my system screenshot Shortcut key （ctrl + shift + PrtSc）. And VDATATABLE‘s shiftKeyDown value is true.
