### ISSUE TITLE
[Documentation] Some Documentation Displays Bad 

### ISSUE THREAD

**Issue by jdsm111200** [vuetifyjs/vuetify#16124]
### Environment

**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Go to see the examples of each seccion

### Expected Behavior
Show the example like the v2 of the website

### Actual Behavior
The example shows with critical errors

### Reproduction Link
[https://next.vuetifyjs.com/en/components/floating-action-buttons/](https://next.vuetifyjs.com/en/components/floating-action-buttons/)

### Other comments
I have to be reviewing the documentation of version 2 and try to guess how new things are done

**Comment by Z3rio** [comment]
Interesting, I will take a look at it! :)

**Comment by MajesticPotatoe** [comment]
This page isn't actually a valid page, its just left over from v2 docs (Its not even in the navigation bar). Guessing you probably had just taken the v2 page and added `next.` in front of it.

**Comment by Z3rio** [comment]
> This page isn't actually a valid page, its just left over from v2 docs (Its not even in the navigation bar). Guessing you probably had just taken the v2 page and added `next.` in front of it.

I seem to be able to find the page and edit it fine on my local server atleast. The issue is with the usage.vue file of v-btn-fab.

**Comment by MajesticPotatoe** [comment]
> I seem to be able to find the page and edit it fine on my local server atleast. The issue is with the usage.vue file of v-btn-fab.

The page exists because the next docs was started from the v2 docs, The page is disabled in navigation because its something that doesn't exist at this moment in v3

**Comment by Z3rio** [comment]
> > I seem to be able to find the page and edit it fine on my local server atleast. The issue is with the usage.vue file of v-btn-fab.
> 
> The page exists because the next docs was started from the v2 docs, The page is disabled in navigation because its something that doesn't exist at this moment in v3

Ahh okay, so FAB buttons dont exist at the moment? Or is it just the documentation that doesnt exist for them?

**Comment by MajesticPotatoe** [comment]
both: <https://github.com/vuetifyjs/vuetify/blob/07622363d9ff9681f427a748a0de0483f8e42cb8/packages/vuetify/src/components/index.ts#L76>

**Comment by MajesticPotatoe** [comment]
will become available when #13508 completes
