### ISSUE TITLE
[Bug Report][3.0.1] v-app-bar sass variables don't work

### ISSUE THREAD

**Issue by MaciejJanyska** [vuetifyjs/vuetify#16136]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.44
**Browsers:** Edge 107.0.1418.42
**OS:** Mac OS 10.15.7

### Steps to reproduce
none

### Expected Behavior
App bar with border

### Actual Behavior
App bar is not bordered

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-gfdcfk?file=src%2FApp.vue,src%2Fsettings.scss](https://stackblitz.com/edit/vitejs-vite-gfdcfk?file=src%2FApp.vue,src%2Fsettings.scss)

**Comment by johnleider** [comment]
Need to find a different way to do this, currently app-bar variables are mostly not being used. @KaelWD should VToolbar have `makeToolbarProps` similar to other components?

**Comment by johnleider** [comment]
Workaround for now: https://stackblitz.com/edit/vitejs-vite-nicnj8?file=src/settings.scss

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
