### ISSUE TITLE
[feature request] Adding class attribute on VDataTable table rows

### ISSUE THREAD

**Issue by haggys22** [vuetifyjs/vuetify#1613]
I think highlighting specific table rows is a common requirement and Vuetify's `VDataTable` does, to my knowledge, not support adding classes to table rows.

I'm not sure if the `<template slot="items" ...>` tag could possibly pass props to the resulting `tr` as IMO it would be the most convenient solution to be able to write something like `<template slot="items" scope="props" :class="{ invalid: !props.item.valid }">`

My current workaround is setting the class on the first `<td>` and applying a CSS rule like
```
td.invalid, td.invalid ~ td {
  background-color: rgba(255, 0, 0, 0.5);
}
```

**Comment by lucafaggianelli** [comment]
Did you look at example 2 at https://vuetifyjs.com/components/data-tables ? You can use <tr> inside the template:

```
<template slot="items" scope="props">
      <tr :class="{ invalid: !props.item.valid }">
        <td>
```

**Comment by haggys22** [comment]
I must have missed that one. Thanks
