### ISSUE TITLE
[Feature Request] Add option for opacity hidden VDialog instead of v-if

### ISSUE THREAD

**Issue by Techship-FIP** [vuetifyjs/vuetify#16131]
### Problem to solve
This would solve the issue where you need to work on components inside a VDialog component, for example access components via ref without open dialog.

### Proposed solution
I would suggesst a visibility prop that replaces v-if with opacity so the elements in the VDialog always exists.

**Comment by KaelWD** [comment]
This is basically what `eager` does, except it uses `display: none` not opacity.

**Comment by Techship-FIP** [comment]
Hey, you are right that eager does make it so the elements inside are available. The problem is that the elements are not available during for example the mounted hook. Which makes it very hard to use them without rebuilding the application.

Any tips ?
