### ISSUE TITLE
[Feature Request] Global size setting

### ISSUE THREAD

**Issue by Techship-FIP** [vuetifyjs/vuetify#16148]
### Problem to solve
Since everyone uses different targeted resolution for their websites this would make it possbile to set a generic sizing for all components, at the moment i have to configure each component i use to the size i want.

### Proposed solution
Bootstrap uses a css variable such as $font-size-base to set a base font size for everything. Do Vuetify have this and if not could that be implemented?

**Comment by djeikyb** [comment]
cf: https://github.com/vuetifyjs/vuetify/issues/16599

I really don't want to introduce a css compiler into my build pipeline. Plain ole css is powerful and sufficient. I'd love to just override a css variable.

**Comment by djeikyb** [comment]
cf https://github.com/vuetifyjs/vuetify/issues/16599

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
