### ISSUE TITLE
[Bug Report][3.0.2] useState not working with v-if when value set in watch statement

### ISSUE THREAD

**Issue by leccyril** [vuetifyjs/vuetify#16145]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 106.0.0.0
**OS:** Linux

### Steps to reproduce
Click on clik link on the menu 

### Expected Behavior
must appear LOGOUT instead of LOGIN (v-if is true normally)

### Actual Behavior
LOGIN still displayed

### Reproduction Link
[https://stackblitz.com/edit/github-q97ggk](https://stackblitz.com/edit/github-q97ggk)

### Other comments
the v-if statement is not working in completion of the useFetch and useState, if you rename vuetify.ts in other extension, it will work, so vuetify plugin is causing the issue, to be sure we print {{isConnected}} value in bracket and it works

**Comment by jacekkarczmarczyk** [comment]
Not sure why, but you shouldn't use `v-text` or `v-html` on components as it destroys the internal markup of the component
`<v-btn>Logout</v-btn>` seems to work fine

**Comment by KaelWD** [comment]
https://eslint.vuejs.org/rules/no-v-text-v-html-on-component.html#vue-no-v-text-v-html-on-component

**Comment by leccyril** [comment]
thank you it is working without
