### ISSUE TITLE
[Feature Request] Data-iterators: must-sort and multi-sort props should be visible in DOM

### ISSUE THREAD

**Issue by MayaElf** [vuetifyjs/vuetify#16159]
### Problem to solve
Our team in EPAM works on test automation framework for UI including Vuetify. We intend to test all possible props. But 'Data-iterators: must-sort and multi-sort props' are neither in DOM nor visible in iterators. So it will help in EPAM test automation framework.

### Proposed solution
Data-iterators: must-sort and multi-sort props - to have it visible in DOM. If it is not possible then to make it visible in iterators (like data-tables have arrows and numbers for that, for example)

**Comment by KaelWD** [comment]
Why should it be visible in the DOM? They affect sorting behaviour when you click on a header.

**Comment by MayaElf** [comment]
Could you, please, clarify how it should look like. When I add 'must-sort' in line 8 it does not change anything at all in data iterators https://codepen.io/MaiiaAfanaseva/pen/abKGYgY?editors=101

**Comment by KaelWD** [comment]
You'll only see a difference if you have sorting implemented: https://codepen.io/kaelwd/pen/rNKrvVW?editors=1010

**Comment by MayaElf** [comment]
Many-many thanks for your support!!! From all our EPAM jdi-testing team! :)
