### ISSUE TITLE
[Bug Report][3.0.2] Autocomplete - When using multiple prop, on click the checkbox while searching, it selects more than one item

### ISSUE THREAD

**Issue by dieguezz** [vuetifyjs/vuetify#16153]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Start typing in autocomplete until there is only 1 or 2 occurrences
2. Click on the checkbox (not the text)

### Expected Behavior
The item you clicked (and only that one) should be checked

### Actual Behavior
The item you clicked is checked, but when the list grows again there appear checked items that you didnt select

### Reproduction Link
[https://codepen.io/dieguezz-the-typescripter/pen/zYaWmEG?editors=1011](https://codepen.io/dieguezz-the-typescripter/pen/zYaWmEG?editors=1011)

### Other comments
- The wrong selected items are not really selected, only checked on the list until you close it. When you open it again they are not.

![weird behavior](https://user-images.githubusercontent.com/1161455/203683811-6710e45a-0107-446a-89a3-67fb0ea05427.gif)

**Comment by rizypb** [comment]
This issue is still happening and its pretty annoying to the user. Need to fix the test fail issue in this PR and someone please approve once it's done. Thank you.  https://github.com/HM-IKE/vuetify/commit/de93ce08c6ea33e0f5f18796f1c5db049bd5892d

**Comment by johnleider** [comment]
> This issue is still happening and its pretty annoying to the user. Need to fix the test fail issue in this PR and someone please approve once it's done. Thank you. [HM-IKE@de93ce0](https://github.com/HM-IKE/vuetify/commit/de93ce08c6ea33e0f5f18796f1c5db049bd5892d)

If you have a fix feel free to create P.R.

**Comment by dieguezz** [comment]
@rizypb maybe is it still happening because the PR is not merged yet or did you test it with that commit?

@johnleider there is a PR already linked to this issue xD

**Comment by rizypb** [comment]
> @rizypb maybe is it still happening because the PR is not merged yet or did you test it with that commit?
> 
> @johnleider there is a PR already linked to this issue xD

This issue is still happening because the PR is still not merged yet. Hope it will be merged soon. 
Thank you for your help.
