### ISSUE TITLE
[Bug Report][3.0.2] v-spacer doesn't work

### ISSUE THREAD

**Issue by mokadevcloud** [vuetifyjs/vuetify#16158]
### Environment
**Vuetify Version:** 3.0.2
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
Please see the reproduction link.

### Expected Behavior
Horizontal distribution of space as explained in the Vue 2 documentation: "v-spacer is a basic yet versatile spacing component used to distribute remaining width in-between a parents child components. "

### Actual Behavior
v-spacer is pushing the next element to the next line, instead of pushing it to the right.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UU1TwjAQ/Sshl+oMbRzUCwMKN/8BB+OhtFuoNh+TbFGH6X93QyoUGN3be7v73svmdc+X1ma7FviUz3zhaovMA7b2SepaWeOQ7ZmDinWsckaxhEYTqaUujPbIlN+weejfJC/QNIatjGvKUXIr9UxEORIigKBskyMQYmy2S3MbHBgVAZXXukcHjPCFaVVDUzJqmhKaueRkJTkTp60id+VwK+AUa2yiSayYarkhh9GJpWlv8wLcUa9n13gKEmq1zTHxrLXPgzFxPhfwlfcvOYDHVwYQ3z8Tg7vwMY8Xp0mbvXuj6U/2YUH2DS/5lB2YwNFPBCz5FtH6qRCtth+brDBKLKgnXKuxVpCWRi3us0n28CjK2uOQz8CrdO3MpwdHjpKPB+JYV99/GfRt0r3LJlG2p4LklZQg/R241IEuwYH7N/fF7Fn2i95V/uDZSd3xbszjHl31EJK//QBx6u3v)

**Comment by Feelixe-tin** [comment]
`v-spacer` is a component within the grid system. So for it to work you have to use it within a grid like this [example](https://codepen.io/pen?&editors=101)

https://next.vuetifyjs.com/en/components/grids/

**Comment by Kosalexei** [comment]
The `<v-card-title>` is not flexible. Wrap your content in `<v-row>`.
[Playground](https://play.vuetifyjs.com/#eNp9UctSwkAQ/JVlL9EqkrVQL1RQuPkHHFwPIZlANPuo3QlqUfl3Z0kMAUpz656e7s7s64GvrE32DfA5T33uKovMAzb2SepKWeOQHZiDkrWsdEaxiKSR1FLnRntkym/ZIsxvoheoa8PWxtXFJLqVOhWdHRkRQFC2zhAIMZbu48yGBEYfAZVVukdHjPCFcVlBXTAamgLqheQUJTkTp608c8V4K+AYK6y7kIF35nNESOyKrrYUOhnzJPU2y8ENIQO/wVO/jlzvMow8a+zzmVRcagMzLhDwVdFfcgSHkwTQHSsVoyPyKe+eh5Q2efdG0wMewoLsB17yOTsygaNnC1jyHaL1cyEabT+2SW6UWNJMuEZjpSAujFreJ7Pk4VEUlccxn4BX8YZ+xoOjRMmnI3Osyu+/Avox+d4ls862p4LllZUg/z242IEuwIH7t/eF9qz7xeyqf8hspW55O+XdHl31WJK//QAwdfqs)

**Comment by mokadevcloud** [comment]
Thanks @Kosalexei That does the trick!

**Comment by scscgit** [comment]
@Kosalexei this per-component flexibility doesn't seem to be [documented](https://vuetifyjs.com/en/components/grids/), do you have an idea where it should be mentioned (i.e. which component's responsibility is this)? For example, adding v-row requires additional workarounds like adding margins.

**Comment by MajesticPotatoe** [comment]
`v-spacer` is flex based (pretty much makes a div with `flex-grow-1` applied to it)
v-card-title is not a flex component (its display: block). You could simply do `<v-card-title class="d-flex>` to make `v-spacer` work inside of it
