### ISSUE TITLE
[Feature Request] Is it possible for the event-name in V-Calendar to display multiple lines?

### ISSUE THREAD

**Issue by droidwizard** [vuetifyjs/vuetify#16154]
### Problem to solve
I Want to customize in cell of the day for event- name to display multiple lines. But can't found a solution, Help me please.

### Proposed solution
You maybe add a this feature or guide me on how to customization.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
