### ISSUE TITLE
[Bug Report][3.0.2] VFileInput can't select the same file after model value is set to []

### ISSUE THREAD

**Issue by mhio** [vuetifyjs/vuetify#16167]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select file for VFileInput
Set VFileInput model value to `[]`  (Click "Clear" button in repro)
Select the same file for VFileInput

### Expected Behavior
VFileInput sets same file as model value

### Actual Behavior
VFileInput model value is empty. 
VFileInput looks like state should be set (label moves to the top)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kk1PwzAMhv+KlQsgrQ0acJkKGiAhcUbisuzQtS4rNB9K3ME07b/jpGMam+CSxn6dx2+dzDbi3rl81aOYiCJUvnV0p0yrnfUEG/DYwBYabzWccdGZMviVpBqbsu+4RBmAgNS78wveK1JUWRMImrbDALeRcD6bX8Qy4IB6b5g7qNuY3Y7iqpGWtg6TAQhQdVj6hIwRAC3bkP8wZ/MhPRyNK5MKubfPAaF2XUnIEUBRtysmliHcKqHLbKxEyrPy+sTMZ+N6glWmbY0dl6Q+SkBXLlL8gh1WhDUsuIzBtIZADFdCxm4UOQ9kYFp1bfXBB5J7bvIYv4WM4mBEshPeFfLAnxiJYd6ZLl3+Hqzhu0g/rnYCe9kPRgm+hxgrsSRyYSJlb9zHW15ZLaesSd8bajVmtdXTq3ycX99w10CH+RyDzhbefgb03FGJNMgdnNpm/VeDnczcy3w8YHepiDxBSeav0GceTY0eeST/+D6q/eX9SDvxn94BPwOxHYnhHE81mRTzb16H99A=)

### Other comments
Might be useful if the `crearable` `onClear` method was exposed, 
The comment in master/2.x VFileInput describes a similar issue: https://github.com/vuetifyjs/vuetify/blob/b0140b073ef1502d957d6234a29a0d274109c2b9/packages/vuetify/src/components/VFileInput/VFileInput.ts#L154-L159

**Comment by attevaltojarvi** [comment]
I ran into this exact issue a few days ago, and thought that it was just a random cosmic blip. Seconded!
