### ISSUE TITLE
[Bug Report][3.0.2] v-progress-circular value doesn`t work

### ISSUE THREAD

**Issue by MaxZhurin** [vuetifyjs/vuetify#16165]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
-

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UEtOwzAQvYrxpiA1cVVAQlFalR03YIFZhGSaBvzT2AlCVe7OuEmk/iBZvc+8eZ63PX92Lu1a4BnPfYmNC8xDaN1amkY7i4HtGcKW9WyLVrMZWWfSSFNa4wPTvmarqN/OXkApy14tqupmdidNLoY4CiIQQDtVBCDEWN4lhYsbGH0EdNGYaAvxJ+zQ1gjeJ2WDZasKZFlXqBZWkj8tJBfj5PBd80/6ydhEllZZJK4CcInFwtTAVFPvAphkOdnWubiSO1Umbew8gOE1uTh6JZ/z4X7kdOmnt4YuvI8DchS85Bk7MJGju0Ys+S4E5zMhWuO+6rS0WmxIE9ia0GhIKqs39+kyfXgUVePDMZ+C18kH2m8PSBslnx+Fh2b789eCUabcRbocYkcqRl5ECcrvABMEUwEC/tv7zHvS/Uy76B939tL0vJ/zYY6ueijJ338B1IXn8A==)

### Other comments
-

**Comment by jacekkarczmarczyk** [comment]
VProgressCircular doesn't have `value` prop
https://next.vuetifyjs.com/en/api/v-progress-circular/#props
