### ISSUE TITLE
[Bug Report][3.0.2] (VForm) readonly states does not apply to VSelect

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#16161]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a VSelect with items (multiple or not), wrap it inside a VForm where you set the readonly props.

### Expected Behavior
The readonly prop of VForm should apply to VSelect like if we were defining the prop directly on VSelect component.

### Actual Behavior
VSelect is still writable when wrapped in a readonly VForm.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUstOwzAQ/BXLl4DUxIjHJSoIOPABcKx7cJsNBOKH7E0RqvLvrJ20Sh+CXKLZ2Z0Zr3ax5U/OFZsOeMnnYe0bhywAdu5BmkY765FtmYea9az2VrOMWjNppFlbE5BtVNsBu48dF1ltbXa5YxoEHUZmIQ0jGWywhZJlL9Q3G0YJxSnWzw5bnpWftKwIpZYlyc/FEJMCEiAX1yoEQozNN7lyMTmjj4BWjRlRwpQMqQR+X0zl2npNOVVlTfuzpyRKJDJAC2t6aK5tBe295CmU5KxVq4Rfx8FhP1GLyDI9n9j0p4KYWorB8zDFv0ZvqEylWmtgH/ac046bWEbD47fH2n4/EQybm4vJRvmMDzdAna74DNbQlWzjANklggxLliqxRrcRseQfiC6UQnTGfb0Xa6vFI3HCdwYbDXll9eNNcV3c3omqCTitFxB0vvL2O4AnR8nTYYzi2NT05PMGI026V8X1IDuWouSJlCD9Dfjcg6nAg/8z91HvQfYj7iR/9Oyl6Xk/48McbTWF5Mtfl0El3A==)

### Other comments
Looks like it is working with VTextField, so this might not work with other inputs too.
VSelect readonly prop is working fine.

**Comment by jacekkarczmarczyk** [comment]
> VSelect is still readable.

What do you exactly mean by that? And why is this a problem?

> VSelect readonly prop is working fine.

So what doesn't work?

Sorry, I totally don't understand what this issue is about

**Comment by KaelWD** [comment]
You can still select values from the top one even though it's in a readonly form.

**Comment by jacekkarczmarczyk** [comment]
ah, I missed vform readonly

**Comment by paul-thebaud** [comment]
@jacekkarczmarczyk sorry, this wasn't clear, I updated the description. I hope this is clearer now.
