### ISSUE TITLE
[Bug Report][3.0.2] VLazy has no transition behaviour 

### ISSUE THREAD

**Issue by PedroCuadra** [vuetifyjs/vuetify#16166]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Edge 107.0.1418.56
**OS:** Windows 10

### Steps to reproduce
```html
<v-lazy transition="the transition">
   ... lazy content
</v-lazy>
```

### Expected Behavior
Using the `transition` prop, the content will be animated when load.

### Actual Behavior
No transtition

### Reproduction Link
[https://codepen.io/pcuadra/pen/YzvLRod](https://codepen.io/pcuadra/pen/YzvLRod)

### Other comments
I'm using either the full name of the transition and short, eg: "expand-transition" and "expand". No one seems to work

**Comment by KaelWD** [comment]
There is a bug here, but expand is a special case and needs to be imported:

```js
import { VExpandTransition } from 'vuetify/components/transitions'

<v-lazy :transition="{ component: VExpandTransition }">
```
