### ISSUE TITLE
[Bug Report][3.0.4] Long text doesn't clip on v-autocomplete

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#16173]
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
Make the selection of an autocomplete be big, and see that it overflows.

### Expected Behavior
I expect the content to be clipped

### Actual Behavior
It overflows

### Reproduction Link
[https://codepen.io/djcaesar9114/pen/VwddjPr](https://codepen.io/djcaesar9114/pen/VwddjPr)

**Comment by djcaesar9114** [comment]
I think this is linked to  #15708 , which has been solved, but without taking into account the autocomplete case.

**Comment by johnleider** [comment]
> I think this is linked to #15708 , which has been solved, but without taking into account the autocomplete case.

Not related.

**Comment by johnleider** [comment]
> @johnleider Would this be a good first issue? I can try to take a look at this

Yea. If you need help reach out on Discord.

**Comment by johnleider** [comment]
fixed by https://github.com/vuetifyjs/vuetify/commit/4922b2fb90cd299b29fb38685b9cf8d9733a93ab
