### ISSUE TITLE
[Bug Report][3.0.2] Autocomplete results are not showing when chips and API are together

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#16176]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
Follow the instructions here: https://next.vuetifyjs.com/en/components/autocompletes/

### Expected Behavior
I expect the results of the API to be shown in the list directly after receiving them

### Actual Behavior
I have to blur the input and focus it again to get the results displayed

### Reproduction Link
[https://codepen.io/djcaesar9114/pen/eYKKMag](https://codepen.io/djcaesar9114/pen/eYKKMag)

**Comment by lioneaglesolutions** [comment]
The issue is that you are loading the API items by watching the `search` property, which is `undefined` to start with, but changes to `""` upon the autocomplete focus.

You should load the data on mount or change the watcher to `immediate`;

```js
    search: {
      handler(val) {
        // Items have already been loaded
        if (this.entries.length > 0) return;

        // Items have already been requested
        if (this.isLoading) return;

        this.isLoading = true;

        // Lazily load input items
        fetch("https://api.publicapis.org/entries")
          .then((res) => res.json())
          .then((res) => {
            const { entries } = res;
            this.entries = entries.slice(0, 100);
            this.count = 100;
          })
          .catch((err) => {
            console.log(err);
          })
          .finally(() => (this.isLoading = false));
      },
      immediate: true // this will trigger immediately and load the data
    }
  },

```

https://vuejs.org/guide/essentials/watchers.html#eager-watchers

@johnleider

**Comment by johnleider** [comment]
If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
