### ISSUE TITLE
[Feature Request] add way to contain image or hide progress in carousel

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#1617]
### Versions

Vue 2.4.2 - Vuetify 0.15.2

### What is expected ?

* Contain the image above the progress bar at the bottom of the carousel (possibly inject card here for media contain and title and card actions)
* hide the progress bar all together
* hide arrows 
* It would also be nice to be able to add text to the carousel item to overlay on the image (could easily do this with card component.
* swipe gestures for mobile platforms would be a plus too
* ability to add multiple items per slide
* ability to slide multiple items

### What is actually happening ?

Currently the carousel is very basic and really only allows you to change the icons inside of it.

### Reproduction Link

Current Carousel
https://vuetifyjs.com/components/carousels

Link to another framework carousel
http://element.eleme.io/#/en-US/component/carousel

### What will it allow you to do that you can't do today?
 It will allow you to show an image that isnt covered by the progress bar, show multiple items at once, control how many items the previous/next actions do, allow you to place subtitles on images, and incorporate gestures into the carousel

 ### How will it make current work-arounds straightforward?
Well there are no examples of doing any of this on the main site so I'm not even sure there are work arounds for this. 
### What potential bugs and edge cases does it help to avoid?
gesture and event based bugs for sure and css related bugs trying to hide certain elements to the existing carousel

I'm not really sure what other information you may need so please let me know if there is anything you'd like more input on. I originally removed the bottom part of the boilerplate for the ticket because the directions for feature requests were a little hazy.

**Comment by johnleider** [comment]
This is a valid feature request, but I have to treat everyone the same.

When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please update this ticket with the required information, thank you.

**Comment by jameshhood** [comment]
I just updated my comment, please let me know if there is any other information you may need @johnleider

**Comment by jacekkarczmarczyk** [comment]
@jameshhood could you please create a separate issues for each feature? Some of them are already implemented afaik and it will be easier to track/manage them

**Comment by jameshhood** [comment]
@jacekkarczmarczyk I have opened up #1881 #1882 #1883 #1884 #1885 #1886 Please let me know if there is anything else I can help with.

**Comment by jacekkarczmarczyk** [comment]
Thanks you
