### ISSUE TITLE
[Bug Report][3.0.2] Dynamic asset is not fetched

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#16179]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
Put "~@/assets/IMAGE_PATH" , where "IMAGE_PATH" is where my image is in the folder assets 

### Expected Behavior
I expect Vue to find my image

### Actual Behavior
There is an error in the console:
GET http://localhost:5173/~@/assets/IMAGE_PATH

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kM1OwzAQhF9l8SUgNTYqcKnSqtw4cOeAOZjEDYb4R7YThKrw7KyTCCWtILf9Zjw72ecjuXeOdq0kG1KE0isXIcjYuh03SjvrIxzBywP0cPBWQ4bWjBtuSmtCBB1q2Cb9MnuQTWPhyfqmusiuuCnYGIdBOESpXSOixAmg6HLh0gbADwctlJmmiYhOROFnbKBK13MCEHy55eR7z0TA0oGhgTW2ttSZmpOlVzQRvY+oLpVdwYbkeQEkiwYJ/JYc1KF+wWa/RVZkPBg6HX0P1uBJj+kBn4TAyQYGkhgeMs2cvMXowoax1riPmpZWsz1qzLcmKi3zyur9DV3T2ztWqRDnnMqg81dvP4P0uJGT1Sw8qsPXXwsmGXOv6XqMnVCKPItimN9Jn3tpKuml/7f3iXfR/UQ765929tz0pF+R8R1edShJXn4AjjDZ7A==)

### Other comments
it works if I put it directly in an "image" element.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#image-loading
