### ISSUE TITLE
[Bug Report][3.0.2] Using two or three lines in a compact list item causes the prepended icon to be too far up

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#16175]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See the reproduction example. Note that this is using `density="compact"` and `lines="three"`.

### Expected Behavior
The prepended icon should be centered or at least within the vertical range of the list item's content.

### Actual Behavior
The prepended icon is floating left and above of the title.

### Reproduction Link
[https://codepen.io/douira/pen/MWXXvep](https://codepen.io/douira/pen/MWXXvep)

### Other comments
This used to work with Vuetify 2, but I'm not sure if it has previously worked on Vuetify 3 or not.

**Comment by KaelWD** [comment]
Duplicate of #15764
