### ISSUE TITLE
[Bug Report][3.0.2] Typescript error for valid values in v-select menu-props

### ISSUE THREAD

**Issue by s-rigaud** [vuetifyjs/vuetify#16174]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
When passing arguments to popup menu from v-select menu-props I got a TS error saying 

```Type '{ 'max-height': string; }' is not assignable to type 'Partial<{ location: Anchor; origin: "auto" | Anchor | "overlap"; transition: string | boolean | (TransitionProps & { component?: Component<any, any, any, ComputedOptions, MethodOptions> | undefined; }) | { ...; }; ... 17 more ...; scrim: string | boolean; }> & Omit<...> & { ...; } & { ...; }'.
  Object literal may only specify known properties, and ''max-height'' does not exist in type 'Partial<{ location: Anchor; origin: "auto" | Anchor | "overlap"; transition: string | boolean | (TransitionProps & { component?: Component<any, any, any, ComputedOptions, MethodOptions> | undefined; }) | { ...; }; ... 17 more ...; scrim: string | boolean; }> & Omit<...> & { ...; } & { ...; }'.ts(2322)
```

while using the following code snippet 
```<v-select v-model="select" :items="['a', 'b', 'c']" multiple :menu-props="{ 'max-height': '250px' }"></v-select>```

The style is applied but the TS error is still here.

### Expected Behavior
No TS error.

### Actual Behavior
TS error while working properly.

### Reproduction Link
[https://codepen.io/Hylectrif/pen/oNyyzGm](https://codepen.io/Hylectrif/pen/oNyyzGm)

**Comment by KaelWD** [comment]
Use camelCase: maxHeight

**Comment by s-rigaud** [comment]
Yes, thanks it fixed the issue 🚀 

Is it possible to let the TS validation be more permissive or to add a line in the documentation recommending camelCase ?
