### ISSUE TITLE
[Feature Request] Navigating the table using the keyboard (arrow keys)

### ISSUE THREAD

**Issue by turopoff** [vuetifyjs/vuetify#16182]
### Problem to solve
Navigating the table using the keyboard (arrow keys)

### Proposed solution
Navigation using keyboard:
1. Up Key - Previous row;
2. Down Key - Next row;
3. Page Up - Previous page;
4. Page Down - Next Page;

**Comment by KaelWD** [comment]
Duplicate of #9164
