### ISSUE TITLE
[Bug Report][3.0.2] Autocomplete : superpose actual selection and input field on focus

### ISSUE THREAD

**Issue by fgruchala** [vuetifyjs/vuetify#16186]
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
 With these implementation : 

```
<v-autocomplete clearable
                              :filter-keys="['title', 'value']"
                              :items="departments"
                              item-title="label"
                              item-value="departmentId"
                              :modelValue="props.modelValue"
                              multiple
                              variant="outlined"
                             @update:modelValue="emitModelValue">
        
        <template #chip="{ item, index, props }">
            <div class="text-truncate"
                 v-bind="props"
                 v-if="index === 0">
                <strong class="text-primary mr-1">{{ item.value }}</strong>
                <span>{{ item.title }}</span>
            </div>
        </template>

        <template #item="{ props, item }">
            <v-list-item v-bind="props">
                <template #prepend>
                    <v-list-item-action start>
                        <v-checkbox-btn :modelValue="isChecked(item.value)" />
                    </v-list-item-action>
                </template>
                <template #title>
                    <strong class="text-primary mr-1">{{ item.value }}</strong>
                    <span class="text-truncate">{{ item.title }}</span>
                </template>
            </v-list-item>
        </template>

</v-autocomplete>
```

### Expected Behavior
When I'm focus the autocomplete, input field have to be upper than selection.

### Actual Behavior
Selection and input field are superposed.

<img width="829" alt="Capture d’écran 2022-11-29 à 10 32 59" src="https://user-images.githubusercontent.com/12196721/204496796-4658d920-cc0f-4454-8513-dfe05fdb5615.png">

### Reproduction Link
[https://codepen.io/Grouquinoux/pen/jOKpvNN](https://codepen.io/Grouquinoux/pen/jOKpvNN)

**Comment by mhio** [comment]
Using the `chips` attribute produces this as well. The chip and the input text are both displayed when focused. 

![image](https://user-images.githubusercontent.com/37205532/210458880-fd3d332e-f99d-44a8-a68f-d3eaba0e4a3f.png)
From https://next.vuetifyjs.com/en/components/autocompletes/#usage

**Comment by fgruchala** [comment]
Still exist in the `v3.1.1`

**Comment by klorophyl** [comment]
Don't know if it helps but this is bugged only for `multiple=false`

**Comment by sohepalslamat** [comment]
To fix this problem just add:
```css
.v-autocomplete.v-text-field input {
    position: inherit;
  }
  ```
