### ISSUE TITLE
[Bug] Lists - cannot use 'to' and actions simultaneously

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#1618]
### Versions

Vue: 2.4.2 - Vuetify: 0.15.2 - Chrome
### What is expected ?

I have an item in my list that I would like to click the main body of for a default action but for more advanced actions I would like to click an action button, open a menu, and select an option from that.
### What is actually happening ?

When you set up the 'to' prop or click event to point to the page I would like to go to, it will override any action button you have added. So the component changes before the menu can even open up. Having one or the other works, but you cant have both because the tile will happen before the action.
### Reproduction Link

https://codepen.io/anon/pen/wqbmPv

This link will open a dialog based on a tile click or a action button click but you will notice if you click the action, both will trigger

**Comment by dohomi** [comment]
@jameshhood check this one out: https://codepen.io/anon/pen/RZmyPb
Is that your behaviour you were looking at? You missed the `@click.stop=""` on your action call to call the action dialog.

**Comment by johnleider** [comment]
@dohomi 's response is the correct way to handle this use-case.

**Comment by jameshhood** [comment]
Ok so this seems to work for plain old list item actions, but how would I do this with a menu in a list item? The slot activator throws a whole new level of complexity to it. @dohomi @johnleider

**Comment by johnleider** [comment]
For custom solutions such as that, you would want to avoid using the activator slot, and manually propagate changes to the menu through a model.
