### ISSUE TITLE
[Bug Report][3.0.2] v-btn's value props does not works

### ISSUE THREAD

**Issue by logue** [vuetifyjs/vuetify#16188]
### Environment
**Vuetify Version:** 3.0.2
**Last working version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Put a value prop in v-btn.
2. Assign a method to the `click` event to display its own value (`e.target.value`) attribute as an `alert`.
3. When clicked, it becomes undefined and does not contain the value defined in `value` props.

### Expected Behavior
The value of the value prop is displayed

https://next.vuetifyjs.com/en/api/v-btn/#props-value

### Actual Behavior
The value of the `value` prop is ignored. 
When I checked the DOM in the console log, the value attribute was not included.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UstOwzAQ/JXFl7ZSYyMel9JWhRN/wAFzSJNtCfVL9qaAqv47m6SU0ApyiDQ745nxys87cR+C3NYoJmKailgFgoRUh7l2lQ0+Euwg4gr2sIrewoClA+20K7xLBDatYdbww8EjGuPhyUdTXgxGPxJC/s1giCOYzWGnHUBuMNIQJeVxjSS3ualxdKfdXrup6kpwPANCG0xOyAhgus3y0PQC/hjYvHIH1GLCD8pWFZoSmPQlmpkWXFALUH3dkhy0kUw35ZhfFKYqNkc8f6iJPHdpxd+JjI6RDejKTFWvpBiLbmmsDPItecdrba+sD0TSYtItoZnxMhusxStRSBOlahc2a1l4qxbMqVg7qixmpbeLa3klb25VWSXqzyUmmy2jf08YOVGLcc+cqtXnXwEHmn0v5VVnexg1lmdWiv23GLOIrsSI8d/eJ9pf3U+4s/5NJj+EvdiPRXeOt9qWFC9ftdXkxQ==)

**Comment by jacekkarczmarczyk** [comment]
2 things here:
1. `e.target` points either to the `button` or `span.v-btn__content`, depending on where you click
2. `button` doesn't get `value` attribute/property anyway

**Comment by logue** [comment]
I'm not sure if it works correctly, but unlike Vuetify2, the button tag didn't have a `value` attribute.

```html
<button type="button" class="v-btn v-btn--elevated v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-elevated">
  <span class="v-btn__overlay"></span>
  <span class="v-btn__underlay"></span>
  <!---->
  <span class="v-btn__content" data-no-activator="">Button</span>
  <!----><!---->
</button>
```
