### ISSUE TITLE
[Feature Request] V-Calendar with scrollable option

### ISSUE THREAD

**Issue by escully27** [vuetifyjs/vuetify#16196]
### Problem to solve
Our running app, Trackster, allows coaches to schedule training and we use the v-calendar component for this. It works great!

This scrollable calendar feature would make it easier for a coach, while scheduling upcoming training, to easily go back to last month to see what was previously scheduled.

Now, coaches have to click a back button and then click again to jump back ahead. It works, but it breaks the flow for coaches who are writing training plans. Having a quick and smooth way or scrolling up a month or two, and then scrolling back down would great! We also have drag and drop support for sessions on the calendar. But, if the session is in a month previous, it's impossible to drag onto the next month.

### Proposed solution
Something like this example would be awesome!

https://codepen.io/GooeyIdeas/pen/ogYaqL

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
