### ISSUE TITLE
[Bug Report][3.0.3] v-date-picker doesn't exist

### ISSUE THREAD

**Issue by tassin-gauthier** [vuetifyjs/vuetify#16191]
### Environment
**Vuetify Version:** 3.0.3
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
```html
<v-date-picker v-model="date"></v-date-picker>
```
```js
const date = ref('2022-01-01')
```

### Expected Behavior
the v-date-picker component should be displayed

### Actual Behavior
It display an error: "Failed to resolve component: v-date-picker"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtOwzAQ/JXFl4DUxIjCpUpRufEHHDCHEm+KafyQ7RRQlX9n3QTJtGp9m4dnRvu6Z0/OVbse2YLVofHKRQgYe/cojNLO+gh78NjCAK23GgqyFsII01gTIuiwgWXSr4tn7DoLL9Z38qq4+TPIdcRzjpqPhVRFIKJ2HbkJAdS7cu3SBqBHQK+VmdABR/yOZauwk0CildgtBaMxggHPfam+dKrZos+Mic2cNc8KEhira55NYjM2noOcrvoM1tDB9umDmIQg2AIOTOLoTAkL9hGjCwvOe+O2m6qxmq9I4743UWkspdWreXVX3T9wqULM+QqDLt+9/QroqVGwWRYeVftzrmCSKfe2mo+xE5UiT6I45e/Qlx6NRI/+4u4j77/tR9rJ/tQ5CDOwYcbGf3TVw0j29gu4bNcM)

### Other comments
It work for v2.x versions but doesn't work for v3.x. I don't understand because it's present on phase 4 of the migration notion: https://www.notion.so/d107077314ca4d2896f0eeba49fe8a14?v=5cc7c08e9cc44021a7c86a20f189b0ba. There is also a problem with the documentation because the "date-picker" is not present on the left menu, but it's referenced on google when you type "vuetify 3 date-picker" : https://next.vuetifyjs.com/en/components/date-pickers/

**Comment by JoakimFFCG** [comment]
The date picker component isn't included in the 3.0 release. It will be added in 3.1. See https://github.com/vuetifyjs/vuetify/milestone/56

It might be released a bit earlier in a preproduction state with "Labs", whatever that is. See https://next.vuetifyjs.com/en/introduction/roadmap/#labs

**Comment by jeremyVignelles** [comment]
Is the 3.1 milestone still accurate ? I don't see any mention of `date-picker` in the 3.1 milestone

**Comment by etrielQ** [comment]
I still don't see component 'date-picker' in vuetify documentation

**Comment by JoakimFFCG** [comment]
@etrielQ Seems like the date picker component was removed from the 3.1 milestone. It still isn't released yet. See #13480 for status updates.

**Comment by stratdev3** [comment]
datepicker component missing in v3 is still the main reason why i'm always using the v2.
sad

**Comment by MarinaMWestling** [comment]
So just going to leave this here because I was also struggling to find the date picker. Looks like they have a type of date on the v-text-field. You can see it on [the advanced section of the expansion panels on vuetify 3.](https://vuetifyjs.com/en/components/expansion-panels/#advanced)

**Comment by mcrapts** [comment]
Thank you @MarinaMWestling. No idea why this isn't documented but this is good enough for me!

**Comment by stratdev3** [comment]
@MarinaMWestling the type date is the one from underlying input tag from browser/os. Not really the former in v2 which offers a ton of great features.

**Comment by MFJamil** [comment]
> So just going to leave this here because I was also struggling to find the date picker. Looks like they have a type of date on the v-text-field. You can see it on [the advanced section of the expansion panels on vuetify 3.](https://vuetifyjs.com/en/components/expansion-panels/#advanced)

Sorry but the link is pointing to Vuetify 2 page and not Vuetify 3. The equivalent link for Vuetify 3 is the following:
https://next.vuetifyjs.com/en/components/expansion-panels/

**Comment by Darmikon** [comment]
@KaelWD, why was the ticket closed? If it's a duplicate, then where is the original issue? I can't find an open issue regarding the nonexisting date picker in vuetify3 and the scheduled release date

**Comment by michael-scheurer** [comment]
It's now available in vuetify labs. You need to
- install vuetify with at least **version 3.3.4**. See https://vuetifyjs.com/en/components/date-pickers/
- `import { VDatePicker } from 'vuetify/labs/VDatePicker'`  in your component. See https://vuetifyjs.com/en/labs/introduction/
- use `<v-date-picker />` in your component

**Comment by dderrek** [comment]
Thank you @michael-scheurer for mentionning that the v-date-picker is now available. I could successfully set it up by following your steps, however I had to do one more thing:
 * include VDatePicker in the components property (using the options API)
 
Without this Vue cannot resolve and instantiate the v-date-picker component (warning in the browser log).

**Comment by BroJenuel** [comment]
any alternative? since we cant use  datepicker?

**Comment by etrielQ** [comment]
Version 3.3.4 introduced the date-picker feature to Vuetify 3
https://vuetifyjs.com/en/components/date-pickers/

**Comment by etrielQ** [comment]
> any alternative? since we cant use datepicker?

Version 3.3.4 introduced the date-picker feature to Vuetify 3
https://vuetifyjs.com/en/components/date-pickers/

**Comment by missmay4** [comment]
Im trying to use v-date-picker with Vue3 and Vuetify but the console gaves me this warn: 

> [Vue warn]: Failed to resolve component: v-date-picker
> If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

Even if in include the VDatePicker in the components property with vue-labs.
What am I doing wrong? 

This is my main.js

```
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import './assets/styles/main.css'

// Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'

// Bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap'
import 'bootstrap-icons/font/bootstrap-icons.css'

const vuetify = createVuetify({
  components,
  directives,
})

const app = createApp(App)

app.use(router)
app.use(vuetify)

app.mount('#app')
```

**Comment by dderrek** [comment]
I assuming with "include the VDatePicker in the components property" you're refering to my [comment](https://github.com/vuetifyjs/vuetify/issues/16191#issuecomment-1666857681). I only had to do it using the Options API. From your code I cannot say whether it is the Options or Composition API (I am still a Vue junior ;-)). But you should anyway make sure that you import the VDatePicker like michael-scheurer mentionned in his [comment](https://github.com/vuetifyjs/vuetify/issues/16191#issuecomment-1634752405).

**Comment by missmay4** [comment]
Thanks for the answer! 

Yes! Im import the VDatePicker like this [comment](https://github.com/vuetifyjs/vuetify/issues/16191#issuecomment-1634752405) says, but nothing happen, the datepicker doesnt show. 

`import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import './assets/styles/main.css'

// Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import { VDatePicker } from 'vuetify/labs/VDatePicker'

// Bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap'
import 'bootstrap-icons/font/bootstrap-icons.css'

const vuetify = createVuetify({
  components,
  directives,
  VDatePicker,
})

const app = createApp(App)

app.use(router)
app.use(vuetify)

app.mount('#app')`

The console give me this warning:

`Projects.vue:755 [Vue warn]: Failed to resolve component: v-date-picker
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <ProjectsDPMT onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {getProjects: ƒ, showHiddenTableElements: ƒ, showTableElements: ƒ, sortByType: ƒ, sortByTier: ƒ, …} > > 
  at <RouterView> 
  at <App>`

Im using the datepicker component this way: inside of a v-container and a v-menu. In this [example ](https://play.vuetifyjs.com/#eNptUsFqwzAM/RXhSzdYGraeFtLCYNexw47LDq6jgJljG1sJG6X/PsVpmxh2cvz89PSkl8+TiEGVL95vxwFFJWrC3htJeGgsQD0W0vv0mS7KWZLaYrhACezRDsCHa9HsG6HjGwPvHm0joFLGRSycTaVoqVBGq2+mddJEbMRNiKWurVksGkeVVKRHSS4w/QQ+OB/hnJWk/oQ/VHQaTbt+ADDymAx9oEFF2ELL2o3ISVWyXYzSDMjceOG+/kMNKFtnzW+OjsVR25ZLk7+85lCXa3vrWctsz7dZJouF5w1hWK00d5VUV8QlC8anMK558TUPbELmPLP+fI0qaE8QkYY5bt17FwhOPHUHZ+iC62HDv8hmogOwbiRYoob9RLxLod4vhLXxC4Vf63Jux43E+UHstrvtk5jPx2fx9QeSnc4z) works perfectly but in my project doesn't open the date-picker.

**Comment by kosukhin** [comment]
@missmay4 Hi.
you need to use VDatePicker inside concrete component in it's component field
for example
`
name: 'ComponentA',
components: {
VDatePicker
}
`

Or register VDatePicker component as global component like this
`
app.component('VDatePicker', VDatePicker)
`

First variant works for me, second I did not test, but it will work I think

**Comment by missmay4** [comment]
Thanks so much @kosukhin you save my life! 

I didin't know that i have to import like that and in the documentation doesnt says anything. 

Have a nice day!
