### ISSUE TITLE
v-select with error doesn't display error until the select is clicked

### ISSUE THREAD

**Issue by travbid** [vuetifyjs/vuetify#1619]
### Steps to reproduce
Compare [v0.14](https://vuetifyjs.com/releases/0.14/#/components/selects) with [0.15](https://vuetifyjs.com/components/selects), example 1, error. When no selected option should be treated as an error, that error doesn't display until the select has been clicked.

### Versions

0.15.2

### What is expected ?

The select in 0.15 should work the same as in 0.14. The error (in red) should be displayed when the page is loaded, if no entry is an error.

### What is actually happening ?

No error is displayed until the select has been clicked on.

### Reproduction Link

(https://codepen.io/anon/pen/zdQWyR)
The select should be red immediately on page load, but is not. It only errors when the select has been clicked on. Please compare to 0.14 as I posted above.  
  
Is this an intentional decision? If so, why?

**Comment by johnleider** [comment]
So this was a difficult decision. There was quite the outcry for inputs being validated in a static state (before any of the data had been modified) and showing an error when first coming up, even if the validation rule was something as simple as **required**. This created confusion as, even though technically the validation was correct, it did not make sense to put a field into error state before the user was able to do anything.

With the 0.15 branch release, @nekosaur did a massive upgrade to the validation system taking into account all of the feedback we have received thus far with the current implementation.

An option that you could use, if you want the error states to display regardless, is to wrap your inputs in a ```v-form``` and call validation once mounted.

Sorry for the inconvenience.
