### ISSUE TITLE
[Documentation] [Documentation] URL Locale broken

### ISSUE THREAD

**Issue by Stealthmate** [vuetifyjs/vuetify#16205]
### Environment

**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Go to https://next.vuetifyjs.com/en/components/badges/
2. Click the `v-badge` API link
3. On my PC, links points to `/ja/en/*` instead of `/en/*`
4. Results in Page Not Found

### Expected Behavior
When browsing the pages in language X, I want to stay there and not get redirected to a different language.

### Actual Behavior
Either URLs are broken or the site tries too hard to "guess" my language of choice.

### Reproduction Link
[https://next.vuetifyjs.com/en/components/badges/](https://next.vuetifyjs.com/en/components/badges/)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
