### ISSUE TITLE
[Documentation] Adding polish language

### ISSUE THREAD

**Issue by Marioneq4958** [vuetifyjs/vuetify#16208]
### Problem to solve
It would help for Polish developers using Vuetify.

### Proposed solution
I will be pleased to help with the translation.

**Comment by MajesticPotatoe** [comment]
Added to Crowdin.
Details: <https://vuetifyjs.com/en/getting-started/contributing/#for-docs-language>

Please note that v3 docs are not available for translations at this time but will be once they are buttoned up.
