### ISSUE TITLE
Selects with autocomplete filter the list when trying to change selection

### ISSUE THREAD

**Issue by matthanson12** [vuetifyjs/vuetify#1621]
### Steps to reproduce
Look at 0.15 documentation for selects w/ autocomplete
### Versions
You can see the differing behavior when comparing the 0.14 docs to the 0.15

### What is expected ?
After a value has been selected, clicking the select should show the whole list of options

### What is actually happening ?
The v-select is using the selected value as a filter and only showing that value in the list

### Reproduction Link
https://vuetifyjs.com/components/selects
https://vuetifyjs.com/releases/0.14/#/components/selects

**Comment by johnleider** [comment]
The current behavior is not a bug and intentional.

**Comment by matthanson12** [comment]
Can I ask why this was changed? In addition to not feeling intuitive its a huge breaking change for me.

Using the example from the docs, if the user selects Alabama by accident and wants to change states they would expect to click the select again and be able to pick a new state. Instead they only see Alabama and need to delete Alabama before seeing the other states again. 

I can _sorta_ understand this functionality if the user typed in the filter box but it _really_ doesn't make sense if the user was just using the select like a select

Thanks John for everything

**Comment by johnleider** [comment]
I can understand the breaking change issue. Maybe I can add a prop that enables that functionality.

**Comment by matthanson12** [comment]
That would be great. I guess I just don't see the use case for the current iteration.

**Comment by nocrates** [comment]
100% agree with @matthanson12  on this one.  If I click a select box that has an autofilter, I only see one option which is the choice I've already selected.  To see more options, I have to erase my selection by selecting the autocomplete text and either re-type or press delete.
That is a confusing and distracting UX.

It would better to always clear the "filter" when a user clicks the component and is attempting to make a change.  Then the user can see an empty filter, and can either scroll or type.  More intuitive.  Note that even though you are "clearing" the filter, if the user does not make a choice, but instead initiates a blur event (clicks away, or clicks somewhere else), then the previous state should be re-instantiated.  This correctly happens now.

Other than this problem, it's a beautiful UX.

**Comment by johnleider** [comment]
I'm being swayed to agree with you. It doesn't feel good. I'm you g to work
on it

**Comment by flybayer** [comment]
I totally agree with @matthanson12 and @nocrates. Current behavior had me really confused until I figured out what was happening.

Thanks for listening @johnleider!

**Comment by johnleider** [comment]
I've just pushed up some massive changes to the select component all around. I think you are going to love it!
