### ISSUE TITLE
[Bug Report][3.0.3] Combobox hide-selected does not hide selected items

### ISSUE THREAD

**Issue by H0rn0chse** [vuetifyjs/vuetify#16226]
### Environment
**Vuetify Version:** 3.0.3
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Click on Combobox to see items.

### Expected Behavior
hide-selected=true hides the checkbox and the selected items

### Actual Behavior
hide-selected=true only hides the checkbox

### Reproduction Link
[https://codepen.io/H0rn0chse/pen/RwJExVV?editors=101](https://codepen.io/H0rn0chse/pen/RwJExVV?editors=101)

### Other comments
v2 for comparison: https://codepen.io/H0rn0chse/pen/dyKwJvX?editors=101

**Comment by yuwu9145** [comment]
I managed to track down the cause and will make PR soon
