### ISSUE TITLE
[Feature Request] v-slider allow thick track high to thumb

### ISSUE THREAD

**Issue by Kugeleis** [vuetifyjs/vuetify#16228]
### Problem to solve
Give a wanted range from high to low the track should be thick in this range.   
Example: Select the accepted income:  
|---------------0#############|
low                                           high

### Proposed solution
new prop "high" setting true inverses the marking

**Comment by KaelWD** [comment]
Use `reverse`

**Comment by Kugeleis** [comment]
This is not the same. The low value should stay left, the high right (in a LTR context).
