### ISSUE TITLE
[Bug Report][3.0.4] VAppBar icon buttons have circular background

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#16239]
### Environment
**Vuetify Version:** 3.0.4
**Last working version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add an appbar with button icons

### Expected Behavior
The button icons on the appbar are flat with no background.

### Actual Behavior
The button icons on the appbar are circular rather than flat.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Uk1z2jAQ/StbXWhnkNVp0wtDmPTWY289RDkYeyFq9DXS4jbD8N+7wjYYQuOT973V27cfj3vxPcaq26FYiGVukokEGWkXV9obF0Mi2EPCDRxgk4KDGafOtNe+CT4TuLyF+8J/nP1AawP8Csm2H2aftF+qXo6FOCB00daEHAEsO1nHUgH448DVxg/RSMp1nUYEoAk2pHstYjKuTq9anKkWfTb0ymQTXKwbOpMnSRYd60Mnsw20iAkj+naSMq0sfd1Jwy2uluoGONFVk8Ym8PkRGbK4+vkcKOSpWI9fPLr2yKk3LK7JQ3HBHbvWyDZQlh0mMk1ttTga5pT/eRyhk5Hp3An/ktwYtC1bcKFFW4rkrRagxm3xy9O6Bhn+v6gh5qI/Hc6M1e8cPB/XvjzQA5G1WMARKRifVIm1eCaKeaHUzseXbcX7VA/MqbTzZBxyq+7ha/WluvumWpNpileYnVyn8Cdj4opazCfiZDZ8MrcLDDTrfq7uetkBKpJvpBTr87Bl4sVgwvSu76vcC+9X3Bv/peZB+wPP0hr/kq/G2OTjCB+fSsphLnppTj72IZ7+AXvZPD0=)

### Other comments
This seems like a regression (screenshot from the docs).

<img width="446" alt="Screenshot 2022-12-08 at 8 16 35 AM" src="https://user-images.githubusercontent.com/4167341/206456067-e066134c-daa1-4cd1-852d-e1eccfcec0a2.png">

**Comment by maspendig** [comment]
Facing the exact same problem. 
Last working version:  v3.0.3 (worked fine for me)
Even the docs are problematic: **https://next.vuetifyjs.com/en/components/app-bars/#density**
Thanks in advice!
