### ISSUE TITLE
[Documentation] Use from CDN in 3.x to include an example similar to vuetify 2.x

### ISSUE THREAD

**Issue by mfsbo** [vuetifyjs/vuetify#16238]
### Problem to solve
The example from vuetify 2.x contains full index.html code so its easy to follow however for 3.x version the import syntax just highlight vuetify objects to be included and fonts and other dependencies are not clear.

### Proposed solution
Update documentation and it would be great to include a jsfiddle or a link to codepen template that does CDN based integration.

**Comment by johnleider** [comment]
The documentation examples now use https://play.vuetifyjs.com
