### ISSUE TITLE
[Bug Report][3.0.3] v-autocomplete does not show search results when async with return-object

### ISSUE THREAD

**Issue by bdeo** [vuetifyjs/vuetify#16233]
### Environment
**Vuetify Version:** 3.0.3
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type "com a" into the search bar

### Expected Behavior
1 result is shown

### Actual Behavior
no results shown

### Reproduction Link
[Vuetify Play](https://play.vuetifyjs.com/?preview=false#eNqtVW1P2zAQ/iunaFKD1DjjZftQMcTGPk6aND4SJExyLQbHzmynBZX+953tpE1KhzRp/uL4nrvH9+rcrJOvTcOWLSaz5NyWRjQOLLq2uSiUqBttHKzB4HwKNTdPv/hqCivuygfYwNzoGiZkOilUqZV1IDWvhFrAF2+Rzrm0eNRjwmFtO+Tmdiu2yA2xRflkspXXukLZiVUr5RZYctmiJ+r8SW8KBbTWcQMQ1QwmxyenZ5NpL1K8RhJekb9fe+mm28d2J7QO2n173+6M1kG7q/ftPtM6aPd9a+e3Xb5ENU5KoeatKp3QCn63aF6uUWI4WkiP4mVdVVjIHFk706KX5zlci7qV3GEF/JE/RwaqJkC8zKBtpfPJjllncyEdmpRYLvpAvKaWyKRepHcf1sh8EBv4sI6Vjbf6cxoheH0FqjNz+odeobniFtMjJlSFzz/naTq0Oqh6BBeQHW/uKHZ/vaFeNQr+K7ln3gT+YXCTLhsz36RjqEOCPPR5vCK2e4AO1SHMR6FCgcNMpVQxSuzQy+l+VemO8zzOKU0oHei6xpeQTgDny4w3fnR9auhQc6G6ExSOBCU3FZSSW/ulSBqenQIxL7mnzj4WSa8biFqnS03k6EK7xEWcfjLJOuxF8gaaRf9JI34MVWZdDgjsvkZoyB1hYR8ijcEGVZUJpdBkgnLvHagEBbhQYv4y1O2jq5+zs6H8QVSYVei4kKEcHbPkJT5oWaEhm+uYesZGcXEjuHIE69ZJobAaot7XLNTKO/4WcsJJD/n2HIKxcTN9/0iV3Ykv26aiau6SuFf/HcW2VlStvgmoBlZqFxJJtuvgAj0hu8J2xR31waAFgHrieE89GBi9AqWzRevoAbB7eMepJU2F9IyfiWIdb2eGrxi9WpvNeR50/tU2zPXfrL2UXBuH5zUpvmGC8tGYxLXtddIfNns/PmMaf9yOUzAJgzZiTqZJ/GeSZsMerVb0Vw3vJLVGAKh+s/7lLBL6d/pzkTw419hZnreqeVowciS/JCw3rXKipq7V9eUpO2Fnn/JKWDeUM7R1dk8psGjoxiLpfhuB3IXROHxBBxPvR3YaaTuRp3xDlRP/kmbP0BiiQfOu33u6I9/3sDf+h8eXXkXKJc3ak91LY2lDCm9uvcpmmkRqUg5xJLd/AFzWwHM=)

### Other comments
I can't totally tell what the issue is here, but something definitely feels bugged with how results are shown. The documentation isn't up to date on this component which makes nailing down the problematic combination of props tougher.

**Comment by KaelWD** [comment]
Line 36: `items.values`
You're also calling `querySelections` twice, and probably want `no-filter` if you're filtering externally.

**Comment by KaelWD** [comment]
![Screenshot_20221208_042150](https://user-images.githubusercontent.com/16421948/206247541-357713e5-538d-4881-b8dc-519c179fb608.png)

**Comment by KaelWD** [comment]
Yeah the playground HMR is a bit messed up, we might have to disable it
