### ISSUE TITLE
[Bug Report][3.0.3] Badge in list items prepend slot

### ISSUE THREAD

**Issue by DasKoebi** [vuetifyjs/vuetify#16240]
### Environment
**Vuetify Version:** 3.0.3
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.1462.42
**OS:** Windows 10

### Steps to reproduce
Add a `v-badge` around a `v-icon` in the prepend slot of a `v-list-item`.

### Expected Behavior
There is spacing between icon and list item title

### Actual Behavior
There is no spacing between icon and list item title

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VE1v2zAM/SuaLu6A2NrW9hKkRXfbfcV2qHtQYjrRqi9IirshyH8fJdmG7X1iWC+GST4+8kkUH060O0IQ7bfqi6drKpQ1LpAT2TngAT7lGDmT1hlFih5b1HoEcim4B78iLV/CmNgZ7SF41nJMqTV8TUnRG0gPIjfzWhenWhMSDqBgjfQNtPwow322Cyn2h1CQ8yqCEj2C4j8ZkB8hIA4LJggZ+8tW7GbMINhz78+E8Xt+XWu6ou+trbBDPJKN3zlhQ0w92tuJcgftVHFSmKUpv0dZGL8oPoCUhnw2TjavCqTesEyHRGgEUFaidrQI2XQlt7FCbAgNxYXurWRL4WNatkdPKZBk4sbAwEq60ksT1taBBd3MQCl/y5s9kMbEK5HG3dTUQVPTBTBB41mnA0dQyz2eXHkwChC8YTm6pEd34p/3xmaSf6alDCJIuL0HHyLH0j85gGn0Px7Mv+h9eV2Dd5gPNMcBiUYenVkfOMZ5WBFp8X0bjeOcZr/uA76m42uo4yaIdk0PIVi/Zuyo7dO+2hnF7jDG3FEHoaBsjLq7rN5VV9eswY6m/gq8KrfOPHtwWLGm/ftK5PF5/6pAH0beN9VVph0WE1L+QMWQvwNXOrw+cOB+2/cCO+t9Eftj/9Od9ndapNhOkyoVadO2wWWDVySFfvKL29n5dDMPQ/GxhoeqNTrwZ/A4jamaAwlxw7HuGuu9vWSYzLiUVSKJDI+x0HlFs24smRqjj98BN4Lqww==)

**Comment by mediafreakch** [comment]
@johnleider This [doesn't look right](https://play.vuetifyjs.com/#eNq1VE2P0zAQ/SvGly5SE7MULlV3tdy4s4LDZg9uMmnN+ku2mwVV/e+M7SRKAhKLgEvVGb95b9544ocz7U4QRPu9/OrplgpljQvkTGoHPMDnfEYupHVGkVWPXVV6BHIpuAe/Ji1fwpiojfYQPGs5llQavqWimA2kB5GbudbVudKEhCMo2CJ9Ay0/yXCf45UUh2NYkcs6ghI9guJ/MiA/QUAcCiYIGfvLUexmrCDYc5/PhPH38rrSdE0/WFtihziSna+dsCGWnuxt0h28O2innpNH0ttT/oDWEHG1+ghSGvLFONm8WiH9jmVKJMMggLIS/SfqXVdwm1VSoLjQfZRiKXwsy/GYKQSSTNJ4MLCSrvDShK11YEE3M1Cq3/PmAKQx8VqkcTcVddBUdAFM0DjvNHQEtdzj9IqjUYDgHcunS3pMJ/55b2xm+VdeiiCChNt78CFyLPOTAUxP/+1g/tDt/3c1ZIftwHBcjxjkxZn1gYuclxWRFr9wo3Gh0/ZX/YGv6Pg9VPEtiHFFjyFYv2WsbjSWNSBF50oNgWmr2B3CmDvpIBQUjVF3m3JTvmMN9jZNl+BVsXfm2YNDkor231qSiZ/6C6R6ZFK4fpsl+lwh+d5HjZ+4GQp24AqH9woO3EstLcqmthZHv7U2ffrm8idtnw5lbabe3qCMFPtpUakibXqU8E3Ce5RCP/nFFdY+Xd/DID5qeChbowN/Bo8rm9QcSIgPIeveo971hmEx41KWiWTs/+9uI3FFqsfY9GVN0wix+1xBH38ApasTCA==)? Is the markup supposed to be different?

**Comment by mediafreakch** [comment]
Here's another (failing) example with a single badge inside the v-list-item's prepend slot that uses a v-icon as it's content: [https://play.vuetifyjs.com...](https://play.vuetifyjs.com/#eNrFVM2O0zAQfhXLHPZSJ4LlVBW0nHgAuG324MbT1mz8I3uSBVV9d8ZOs3LTohYBIoco8/v5+zyZxz3/5H019MCXfIVgfCcRPjaWsdUgpPf5MxtWDnorUTsrVJAvENjSOAWdGGTXw4eGY+ih4ceCXNLpiK/2q0dowincFJiA2RsfwINVJ+FcuZZqC0w5ZOg8a13nAmEGUAVkka5bZ1l6UZJRWrRuS4mreozM25M79z89VX2ix/R8AURtt7HgReWXiP1Pvjtn0mX8FuECt+jUufa54WztEJ1hboDQSZ8b3yzZZ0ckWD7SZRVo0C6KMGcVUYZfsbqI/Q+v5qpEN9wSBud3P/7SYH6F7zQs9LpGf/JO/zaZZz/3uAIoMu6AE0gyYxu0RxYB+5GoNt4FZHsWYMMObBNIiDtaK3epdsymPL7gY6Iw0lfforO0dvapvjkGYsOXLHuSjxoku+E7RB+Xdd0qS2W0dfQQKgtYW2/qB0qrQ29RGxDKmYf76r56XyuiWLoriEasg3uJEKhJwxcFDOoN3cNVqGNmRnj7boQ4+kQn1zFhnPWuCZBmQgSaJghAE3wbpVlZSWsWOqOW0A+NPZDgnbbPcaZ1G7POj9Mh/4xz7pZaPSXEw4LngxL0WMGffgIN5fQj)

I think those problems should all be addressed together, since they are all related to badges inside v-list-item's prepend slot.

**Comment by johnleider** [comment]
Margin was being applied incorrectly, I fumbled duplicating class selector. Fixed in e4e4f4c21

**Comment by mediafreakch** [comment]
Tested it using the latest nightly. Looking good, except for the example with two badges within the prepend slot: [https://play-vuetifyjs.com...](https://play.vuetifyjs.com/#eNrFVM1u2zAMfhVBO/QS2WmywxBkQ3faA2y3ugfHYhyt1g8k2l0R5N1HyXHhOCmWAS2agxGSH/nxE0Xd7/l357KuBb7iawTtmhLhW2EYW3eidC79TYYpO1WXqKwR0pdP4NlKWwmN6Mqmha8FR99CwY8JKaVRAV/sF49QxDNyU2AgZp+cBwdGnoRT5qaUNTBpkVW2sZ74PMgR3QiqKmtY/BBISyUqWxNwnfeRaWlyp9qnHeUnZzH8fgKiMnUYaaL0S6I+SuvO6jiE/xI74hxVamz1eKx09fn8sAwtSz1clkw36qLiqYyApX9NxkXud5zD+ZlcMQf01u2e3+ja/YI/yJA+/9I7eIetJfNsbfvlpki/3SeUZIbKK4csALb98ivtrEe2Zx627MC23mp2Qw/GTczt0YTjM94DhS5d9jtYQw/KPuYXx0Ao+IolT/RRgWgXfIfowirPK2kojd4T1fnMAObG6fyOYLlvDSoNQlp9t8yW2edcksSxO4OgxcbbpwCeihR8NqJBtaU5XEUVoblR9Q6b50R1uyA5AanqYr5YivkXcTvv2Y9o0ZSbEOnPaHPqpQMvPN0s8EC3+Tq1k7Sx4knoTHVkPxTmQLNolHkMkzFUIY3gfmjy3Y4jEUWWh9jMYcaTBurqtRr84S8rc/rw)

Is that something you're gonna address or not? Like mentioned this was possible in v2.

**Comment by johnleider** [comment]
I've implemented a better fix [here](e8f2e7d30)

**Comment by mediafreakch** [comment]
Looking good now! Thanks for your extra effort

**Comment by abea** [comment]
I'm confused. Why was the extra space the expected behavior? This became a breaking change for us.

**Comment by abea** [comment]
[Discussed further in Discord](https://discord.com/channels/340160225338195969/342461135343321108/1143236016220672110) (subscriber channel)

**Comment by joeriddles** [comment]
> [Discussed further in Discord](https://discord.com/channels/340160225338195969/342461135343321108/1143236016220672110) (subscriber channel)

@abea can you add context here for those of us who aren't in the Discord channel?

**Comment by abea** [comment]
@joeriddles [This was my reproduction](https://play.vuetifyjs.com/#eNp1Ul1v2yAU/StXvCSRYidb9iF5aaRq2vOmrG91VTG4aVExIMBeoij/fWCTmGbtC1zO/T6H+yNxli1ujSm7FklF1h4bI6nHTa0A1l3BqOXAJHXupibNvqCt1zWBhu6Lv4L754Culsua9PF9hhTOA0flhD8EL9ONocxfIi4xhWv/PCPlaDfbH79+bu9+rxf/eWp1nSXChGcMoCt22oYu0wjPQcxAKIi2q8kYVb1gHEW8wjoqW4xoLJg5mJZ9SWNFQ+1hdF0WCMOcaQoDOKl9ZSwaVDwL6ScWTCuo4pkaldEOXMRVo5nXXGTcZ3C2d+GFl7Gnx70/V4x2qngVODKe+85KJWwQOjyi0uFxNcbaMSvMEIV7o23Udkdb6eE4FOLU0wqmM7jZwDRhMGhQwf24yBHipBVMtkhlcScanATBAgcBargomNTsZQKn+Rspty0XqNhVBmVMt8q/k/Ndqw6tE1q512k7SZ/ynIdknWa9cYocXLaODPhDIN0xbXAQuOKIZlpmnD4+pg8wgw0ER6974iJ8oicRei/Lr58tNuH+8jEZCfg2to2tQg9ympNVuSo/keH+sCIP/wAQCSDU), which is fine on 3.3.12 but has extra margin on 3.3.13. It was a long discussion. This update does change cases like ours, but I gather the intention was to cover most use cases without assuming specific order and contents. There was no further code change, but they added a BC note in the release notes.
