### ISSUE TITLE
External pagination does not match internal pagination on search

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [vuetifyjs/vuetify#1624]
### Steps to reproduce
1. enter text in search field 
2. see that external pagination does not match internal pagination 

### Versions
Vue: 2.4.2 
Vuetify: 0.15.2
OS: Windows 10
Browsers: Only Chrome tested

### What is expected ?

The internal pagination updates correctly as you search.
The external pagination should update as well

### Reproduction Link
https://codepen.io/charlesok/pen/QMReQq

**Comment by nekosaur** [comment]
You need to use this instead

```javascript
pages () {
  return this.pagination.rowsPerPage ? Math.ceil(this.pagination.totalItems / this.pagination.rowsPerPage) : 0
}
```

Previously you were using `this.items.length` which will always be the original number of records. You need to use `this.pagination.totalItems`
