### ISSUE TITLE
[Bug Report][3.0.4] V-Slide-group is not responsive

### ISSUE THREAD

**Issue by simoneeek** [vuetifyjs/vuetify#16247]
### Environment
**Vuetify Version:** 3.0.4
**Last working version:** 3.0.0-beta.10
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Make slidegroup with max-width: 388px; item of this slidegroup should have width: 2OOpx. Try click on next button... I recommend 7 or more slides.

### Expected Behavior
I expect a mini carousel for better mobile version, like on this page on phone: https://masazenemcova.cz/

### Actual Behavior
Current functionality is on video.

### Reproduction Link
[https://codepen.io/simoneeek/pen/dyKrjXe](https://codepen.io/simoneeek/pen/dyKrjXe)

**Comment by KaelWD** [comment]
Duplicate of #10475
