### ISSUE TITLE
Transition component not working.

### ISSUE THREAD

**Issue by silvioiannone** [vuetifyjs/vuetify#1625]
### Steps to reproduce

Wrap any HTML element/ Vue component with the `transition` component (or for example `v-slide-x-transition`).

### Versions

0.15

### What is expected ?

The wrapped element/component should be subject of a transition.

### What is actually happening ?

No transition can be viewed.

### Reproduction Link
[CodePen](https://codepen.io/anon/pen/brPGab)

**Comment by johnleider** [comment]
I'm not sure what you are expecting to happen. That's not how transitions work in Vue. Could you provide some more context please?

**Comment by silvioiannone** [comment]
I looked at the `vuetify/docs` source code because I wanted to replicate the transition that you have on your docs toolbar title and I found that the title is wrapped with

    transition(name="slide" mode="out-in")
      v-toolbar-title(
        ...
      )

So basically I tried doing the same in my project

    <transition name="slide" mode="out-in">
        <v-toolbar-title ...>...</v-toolbar-title>
    </transition>

I thought that it was enough to wrap the `v-toolbar-title` component with `transition` to achieve the same effect. Am I missing something?

**Comment by johnleider** [comment]
In order for view to understand that you want it to transition, it has to have some point of reference. That reference is the **key** prop. What I do in the docs is assign a dynamic **key** that when changed, tells Vue to trigger a transition.

Here is an example: https://codepen.io/johnjleider/pen/dzBPjy

**Comment by silvioiannone** [comment]
I see, thank you for your explanation. Amazing job what you and the others are doing (y)

**Comment by rosnaib11** [comment]
Link is not working anymore. I also want to know how to achieve slide transition in your documentation. So far most stable transition I got is <v-fade-transition mode="out-in">

**Comment by morigs** [comment]
Hi. It's very easy indeed. Just look at the [Transitioning Between Elements](https://vuejs.org/v2/guide/transitions.html#Transitioning-Between-Elements) section in the documentation for the Vue transitions. There is the following tip:
> When toggling between elements that have **the same tag name**, you must tell Vue that they are distinct elements by giving them unique `key` attributes. Otherwise, Vue’s compiler will only replace the content of the element for efficiency. Even when technically unnecessary though, **it’s considered good practice to always key multiple items within a `<transition>` component.**

Also you can read the following in the API documentation for `key` attribute:
> It can also be used to force replacement of an element/component instead of reusing it. This can be useful when you want to:
> - Properly trigger lifecycle hooks of a component
> - **Trigger transitions**

So all you need to do is add the key attribute with a unique value, for example, with the title text.
Suppose you have a title in the `toolbarTitle` property, then the code is as follows:
```pug
v-toolbar(app, dark, color="primary")
      v-toolbar-side-icon(@click.stop="toggleDrawer")
      transition(name="slide-x-transition" mode="out-in")
        v-toolbar-title(:key="toolbarTitle") {{ toolbarTitle }}
```
---
@rosnaib11 Vuetify has [predifined transitions](https://vuetifyjs.com/motion/transitions). In this example: `slide-x-transition`.

**Comment by KaelWD** [comment]
You can also use `<v-slide-x-transition>` in place of `<transition name="slide-x-transition">`

**Comment by morigs** [comment]
@KaelWD hmm, not working for me
