### ISSUE TITLE
[Bug Report][2.6.12] text-h* font does not change

### ISSUE THREAD

**Issue by wonkyungup** [vuetifyjs/vuetify#16250]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
```
<div class="text-h1">Hallo World</div>
```
variables.scss
```
// Zen Dots
@import url('https://fonts.googleapis.com/css?family=Zen+Dots');
$body-font-family: 'Zen Dots', sans-serif !important;

html, body, .v-application {
    font-family: $body-font-family;
}

.v-application {
    .text-h1, // .display-4
    .text-h2, // .display-3
    .text-h3, // .display-2
    .text-h4, // .display-1
    .text-h5, // .headline
    .text-h6, // .title
    .subtitle-1,
    .subtitle-2,
    .body-1,
    .body-2,
    .caption,
    .overline {
        font-family: $body-font-family;
    }
}
```
Font doesn't change.
please tell me the solution

All font settings are applied.

text-h*
body-*
Only this class has the same font.

### Expected Behavior
.v-application .text-h1 {
  font-family: "Roboto"
}

### Actual Behavior
.v-application .text-h1 {
  font-family: "Zen Dots"
}

### Reproduction Link
[https://codepen.io/moedav/pen/rNxqjyg](https://codepen.io/moedav/pen/rNxqjyg)

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
