### ISSUE TITLE
[Bug Report][3.0.5] `VAutocomplete` is not showing the selected values

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16263]
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click in button "Set"
Open the VAutocomplete, the setted values don't show as selected items

### Expected Behavior
Show the setted values as selected

### Actual Behavior
It is ignoring the setted values despite they are the same objects.

### Reproduction Link
[https://codepen.io/elyaiko/pen/XWYwdOW](https://codepen.io/elyaiko/pen/XWYwdOW)

**Comment by yooneskh** [comment]
It seems like it needs the value objects to be exactly the same ones (identity wise). This will work
```js
setVals(){
  this.values = [
    this.items[0], this.items[1]
  ]
}
```
Although personally i would expect it to work as you said.

**Comment by vexleet** [comment]
This should be fixed when this is merged https://github.com/vuetifyjs/vuetify/pull/16114

**Comment by johnleider** [comment]
This appears to be fine now:

https://play.vuetifyjs.com/#eNqNUstugzAQ/JWVL2mkBEQeF0SiVuonVL0kORjHqG4NRsbQA+Lfu7ZBJNBIOSDvembNzu6cWlJpFr6VZdDUnMQkMTwvJTX8eC4AkmZNy9KFLmFUX/vM56owVBRcQyZrMUIO1Or35qLnS8CvOpxJtDmTO9j/rTaKKeyAG34PAjTrXF25xNqGyppXZzJlxAK7t4+7c45Lmrr6d57RWpo5wdatjTCSI8udDziug6GTOUdzU+tirdJvzswUzPHXAhVO75nkVNN0CoSTKXnxMbRtH0LXTeb4pWdVbiKuyEWTmiR0u7ndH97cLxC3k5oCXpkU7AelV9x89ns4YmwLEB/d4Z7s7TE4yN4NFrKJN1cS3pgO04ppURrAR2vvPZGXShtoca4ZdJBplcMC/bqwdBycKiozDONgSS+ny3JEvOIDnHwXLbjNxrD4sCdEi5UvjiGCbvU/aTOSNg9J25G0fUjajaRdT7p4HVldMCNUYZX70b4sofWveHWBO0YpT4p5Ug62AYC+SEK/AZw96VZkG+yCaE9ssA8icvkDdfA0Xg==
