### ISSUE TITLE
[Bug Report][3.0.4] Cant resolve component types in tsx files

### ISSUE THREAD

**Issue by andtii** [vuetifyjs/vuetify#16265]
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.1462.46
**OS:** Windows 10

### Steps to reproduce
Hover v-btn in the App.tsx file and there is no intellisense then do the same in App.vue and there we have intellisense

### Expected Behavior
The Vuetify component typings should work in .tsx files without needing to import them

### Actual Behavior
The vuetify component typings does not work in .tsx files

### Reproduction Link
[https://github.com/andtii/Vuetify3Tsx](https://github.com/andtii/Vuetify3Tsx)

**Comment by KaelWD** [comment]
Specifying IntrinsicElements can break projects that aren't expecting it. You can do it yourself in your own project:
https://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements
