### ISSUE TITLE
[Feature Request] Default component colour by theme mode

### ISSUE THREAD

**Issue by Vuexec** [vuetifyjs/vuetify#16264]
### Problem to solve
Not being able to define default values such as `color` by theme mode in components such as `VAppBar`, `VNavigationDrawer`, `VCard` under `defaults` in the instantiation of `vuetify`

### Proposed solution
```js
const vuetify = createVuetify({
    defaults: {
      dark: {
        VCard: {
          color: '#454545',
        }
      },
      light: {
        VCard: {
          color: '#FAFAFA',
        }
      }
    }
```
Something like this

**Comment by KaelWD** [comment]
This is what themes are for.
```js
createVuetify({
  theme: {
    themes: {
      dark: { surface: '#454545' },
      light: { surface: '#FAFAFA' },
    },
  },
  defaults: {
    VCard: { color: 'surface' },
  },
})
```

All the components you mentioned already use surface by default.
