### ISSUE TITLE
[Bug Report][3.0.4] v-navigation-drawer temporary scrim does not work in RTL mode

### ISSUE THREAD

**Issue by curiousyigit** [vuetifyjs/vuetify#16261]
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- Create a temporary navigation drawer
- Switch to an RTL language (example: ar)
- Open drawer (scrim will not work in RTL mode)
- Try to click outside drawer to close it (will not work in RTL mode)

### Expected Behavior
v-navigation scrim should be visible and when clicked outside drawer, drawer should be closed in both LTR & RTL modes

### Actual Behavior
v-navigation scrim is only visible in LTR mode and clicking outside drawer to close it also only works in LTR mode

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVclu2zAQ/ZWpLk6BSOqSXlzHTYFeCgQ9pEYvYQ4MRduMKVIgKTmG4X/vcJG8JQV6jU+a7c2bN9L4fpt1LXdivimebDbORN1o42ALzHDq+J8Ygx3Mja5hlHJHRBHFn0Mq08o6SAG4Pi682BIF4Ja85mMErficttLNoj2SYrF0I9hd+iSpGZXeS80oOACMk1gVnwGoGYMzLU/BHVG791+Jyi6z701TIAGkP7HMiMaB5a5tpkQN4xg+74cgfmKSYekQbS2/De3PBsUsAKLikJEizjjkX3gG0V2w1hiuXNFR2fokPwhG561iTmgFbEnVYqiLc71S+rIbIbkawbeADKgUWoFfZeiam6Hai4R+FKgnHhMwhDJc+LCnPSmjWCgTGo7XjcTFoQUw6XLaeP280Ggo2okF9VPkCarLa11xeU2y6CAZeARtqNnAvjZUM2qqwSYueXLHn33v6A6py4/TX0Mn+BGAJyV6j7K6vBKdqJBEeRzYN42/GVJhUrCVUAvQrbNY1EvhNIa05VBz1Rbw08FaSAlayQ2stVmBUHA7uwM/5VGT8rgLsnl0Cm5CH1TjcMkkm/5eC8eWHqm8m91OypB9AOA952L03n4BaJ5tIGwtMUC980dqTnVPbl+bC3wR9iyH9+Fdv72pb3JacNA/hQ671lTsR/mfNb+0J91w5deEpwL2s/bboqryEfyG3sg6B+2Stvg8KQ8+QTxq8ThhZoOXWSs8buFikBSwJBtuY7poY3xYOtfYcVm2qlktCqbr8gZjpWmVEzXPK13ffC4+FVdfykpYd+gvuK3zR6PXFk/JE8KnOxvA/S18rUEKI+6H4irC9n8pCHkGVSJ+x02Olw2/Yf/u/YP3Se4R95PYGX/f0/9JoJZSqJU9kZHZIOH9g0/ZXWYRGpPDHNnDX3wtSwE=)

**Comment by KareemDa** [comment]
any update on this issue ?

**Comment by KaelWD** [comment]
This was caused by #14657
I couldn't figure out why they were there in the first place, lmk @nekosaur if you remember.

**Comment by alokVishu** [comment]
Hello @KaelWD,

My app broke after updating to Vuetify version: 3.2.2

![chrome-capture-2023-4-3 (1)](https://user-images.githubusercontent.com/80033712/235891625-14f00961-97e1-44fe-9213-049a70141c8f.gif)
