### ISSUE TITLE
[Feature Request] Adding drag&drop function to "calendars/#props"

### ISSUE THREAD

**Issue by kdg-dev** [vuetifyjs/vuetify#16260]
### Problem to solve
Implementing a calendar that reassigns the tasks of multiple workers for the day.

We have a team meeting every day before the start of work, and at this time, the tasks of all workers are reassigned to the workers. As for the reassignment operation, I would like to be able to use the drag&drop feature.
However, An individual cannot perform more than two overlapping tasks.

### Proposed solution
Sol-A) How about implementing it by extending the functionality of https://vuetifyjs.com/en/components/calendars/#props?
Drag and drop functionality is not supported in this example. Above all, I want to be able to reassign tasks with the drag and drop function.

Sol-B) Alternatively, in the following example https://vuetifyjs.com/en/components/calendars/#drag-and-drop, it would be nice to change the header dates (10,11,12,13) ​​to the workers john, tori, david, ..., etc. . The date is set to a specific date.

And one worker cannot run more than two tasks at the same time. Therefore, it would be nice to be able to prevent overlapping tasks for each worker.
This should be enough, but it would be more helpful if the calendar changed the time zone and worker matrix.

Thanks in advance.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
