### ISSUE TITLE
[Documentation] VSelect icons example doesn't use VSelect

### ISSUE THREAD

**Issue by zephyrtronium** [vuetifyjs/vuetify#16268]
### Environment

**Browsers:** Firefox 107.0
**OS:** Windows 10

### Steps to reproduce
Navigate to "Icons" example in VSelect documentation.

### Expected Behavior
Demonstration of icons in VSelect.

### Actual Behavior
Demonstration of icons in VTextField.

### Reproduction Link
[https://next.vuetifyjs.com/en/components/selects/#icons](https://next.vuetifyjs.com/en/components/selects/#icons)

### Other comments
https://github.com/vuetifyjs/vuetify/commit/197a13bc22088ba0d7834eafc7b40b256555dc3f fully replaced the VSelect example.

**Comment by johnleider** [comment]
This example was moved to v-text-field.
