### ISSUE TITLE
[Bug Report][3.0.4] Focus after selecting item in Combobox/Autocomplete bug : different behavior with Chrome and Firefox

### ISSUE THREAD

**Issue by theo-chmbn** [vuetifyjs/vuetify#16274]
### Environment
**Vuetify Version:** 3.0.4
**Last working version:** 2.6.13
**Vue Version:** 3.2.43
**Browsers:** Google Chrome, Mozilla Firefox, Safari
**OS:** Windows 10, Mac OS 13

### Steps to reproduce
On Firefox or Safari  When selecting an item from a combobox or autocomplete component with the keyboards arrows, as the autocomplete/combobox menu closes the selected items does fill the input field, but the focus is not put back on the input field.

On Chrome it does work, the focus is put back on the input field after selecting an item with the keyboard.

The issue is only present when selecting with the keyboard, when I select an item by clicking on it, the focus is back on the input field.

I tried on Vuetify 2.6.13, and the issue is not present, it is working fine on all browsers.

I linked a codepen which is a copy of the codepen linked in the official vuetify documentation, you can even reproduce the issue directly on the official documentation interactive exemples.

### Expected Behavior
After selecting an item from combobox/autocomplete with keyboard arrows, focus is on the input field element

### Actual Behavior
After selecting an item from combobox/autocomplete with keyboard arrows, focus is not on the input field element, not sure where it actually is

### Reproduction Link
[https://codepen.io/MrTo/pen/JjZQmeP?editors=101](https://codepen.io/MrTo/pen/JjZQmeP?editors=101)

**Comment by KaelWD** [comment]
This seems to be resolved already.
