### ISSUE TITLE
[Bug Report][3.1.4] V-Autocomplete pre selected option not working when using return-object prop

### ISSUE THREAD

**Issue by ThomasCarbon** [vuetifyjs/vuetify#16279]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Ubuntu 22

### Steps to reproduce
Click v-autocomplete field and see there is no option pre selected while vmodel isnt empty and item value is good for the comparison.
Remove firstname prop from data object and see it working.

### Expected Behavior
Make pre selected option work properly when using filled vmodel and return object prop

### Actual Behavior
Pre selected option doest not work when using filled vmodel and return object prop when the vmodel has additional prop

### Reproduction Link
[Play vuetify](https://play.vuetifyjs.com/#eNqlU9uK2zAQ/RWhl20httntQsHNliz0qdAvWOVBsSaNsrohySkl5N87IyeunWwLpX4wnjlHZ2bOyC9H/hxCfeiBt3yZuqhDZglyHz4Lp23wMbMji7BlJ7aN3rI7pN4JJxxjnXcpMyWzZE9EefdC2SO9GAMrtWmZ4Hu/cyvloe68FXwxoFq17P78vdUxZSctEPsrsgUn4FTgazUro4bVXrpbvYe39L4R/7fg+v0n6n3oPIGBLoP68n8TjLqMCbdsBg/RPQwy2GBkBowYWx4qGchWOo4ByrtzNCRknz2WCAYyjHl8kOoVmCfBpx0PQ12eVmOthBRaxxzqdjqkaSLieqOr/GaPYlPAyE0p85yS7zT2rVifIM7lqFCVdTaAzOLRG/hBmp5wreag7U3WOOA497KZz32xB9OjP4VTnFs2E0f5gg8XFJmh3ifv8AqX3WHdAiTB28s2BceLS7Hgu5xDapumd+H1Oy21WSHWxN5lbaFS3q4+1A/148dG6ZSn+RqSrTbR/0BXsOJ4GYp41tuffypwhlH3vn4cZM+pCk1PpHuj12CRA8QqglMQaQ1/af6KOxvgCrsZolxi4U5oqNHuNV152aXiY/k1KP736YoCHV9TldOCD91hvXKCr38BLj5vwA==)

### Other comments
This is a side issue from https://github.com/vuetifyjs/vuetify/issues/16046 which is closed and fixed. I left a new comment but though it was better to create a new issue. 
This time it is maybe an expected behavior, but i think it could be a good functionality also depending on your goal.

**Comment by men232** [comment]
Also, issue when you provide items as a computed property
[Playground](https://play.vuetifyjs.com/#eNp9UsuO2zAM/BVBl80CfrTb9uI6iyzQv4hyUGymUdZ6QKJTFEH+fSnZMezsI4cY5FDD4ZDbC39xrjj3wCteh8YrhywA9u5ZGKWd9cguzMMhY43Vrkdo2ZUdvNXsgR49CCNMY01A1kqUbD1VrVaPbP3MLsIwgZ4IvWHbGNEPFXZQMcFP9mg2rYWCXgmeDehZdj2h31N4zRLF/JGWXsHmJM2Hz56GZ7vfwlwf6e8mL0AHDen6M8ikiVbbXSxgTJi6HCanmSlA0K6TCBQxVp9z6aIZsQcFWiozRkNC9mjj0B0gTPmoJ9e2hW4t+Ly14POaSlGvQCXRvCXUHJUL88TgYW73JyKbA53cpzYvIdhGke6W9QH8ki42ypOFVJm+H+DJQsLTd4nrvkNFM06j1+Vy9JtDlJ4sSjXJvLqcmcozPlwWVbriFKyh20tbFiMQBK9ueyc5UUzc/BHRhaose+Ne/8bllxvCSt8bVBry1urNj+Kp+PmrbFXAeb6AoPO9t//IGOo4HU0iR3X4/1mDESbeb8VIO6Yi5TuqkvjP4HMPpgUfl/CF7rvahfY77J3+dOR04uRlp8xruLOxCcnC7S6WXDM+UFNxmoPv3gDp+kVM)

**Comment by websitevirtuoso** [comment]
Have the same issue. It looks like this 
![image](https://user-images.githubusercontent.com/5112918/211254617-bbf52a5b-19a3-4780-b8e3-4ab1f59f1299.png)

Maybe 10 releases ago it worked but not now((

**Comment by ThomasCarbon** [comment]
Updated play vuetify and issue because bug still occur on 3.1.2

**Comment by KaelWD** [comment]
Hmm I guess this would've been fixed by #16546

**Comment by ThomasCarbon** [comment]
@KaelWD Exactly, this was my previous issue https://github.com/vuetifyjs/vuetify/issues/16046 and this is fixed
But when object do have different keys, if you set "item-value" props i expect it to rely on it in priority instead of anything else. 
That is this case which is not working, still on 3.1.4.
I will update my issue with new play vuetify

**Comment by yuwu9145** [comment]
I wonder probably we should start use a primitive-only "internalModelValue" that holds item-value when using return-object. This would make value comparison easier.

**Comment by yuwu9145** [comment]
It feels like using both `return-objects` and `item-value` together is an "anti-pattern," because it is disputable which property takes priority.

Currently, the implementation is such that `return-objects` override `item-value`.
