### ISSUE TITLE
v-select slots issue

### ISSUE THREAD

**Issue by jrobertson-ed** [vuetifyjs/vuetify#16273]
Hi, 

Any time I use a select list with a slot, upon selecting an item in the select list I get the following error(s) in the console, and I have to refresh the browser for the application to respond again. 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__asyncLoader')
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')

See below example of select list usage.

`<v-select`
        `v-model="_item"`
        `:items="items"`
        `:label="translation.t('global.colour')"`
        `:validation-rules="props.validationRules"`
        `@update:model-value="emitSelected"`
    `>`
        `<template` #item="{ item: colorItem, props: itemProps }">
            `<v-list-item` v-bind="itemProps" :class="`bg-${colorItem.value.id}`"></v-list-item>
        `</template>`
        `<template` #selection="{ item: colorItem }">
            `<div` :class="`flex-grow-1 bg-${colorItem.value.id} mb-1`"></div>
        `</template>`
    `</v-select>`

"vue": "^3.2.41",
"vuetify": "^3.0.4"

Kind regards,
Josh Robertson

**Comment by KaelWD** [comment]
If this still exists please open a new issue with a runnable example.
