### ISSUE TITLE
[Bug Report][3.0.5] How to use list group inside navigation drawer

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16281]
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use the list group inside the navigation drawer and make `rail` true

### Expected Behavior
The list should be adequately shown on the rail mode. how to collapse the list group when not hovering on the navigation drawer

### Actual Behavior
The list is not appropriately seen. And list group is not getting collapsed during mini-variant activity.

### Reproduction Link
[https://codepen.io/Alokdev/pen/eYKqEXE?editors=101](https://codepen.io/Alokdev/pen/eYKqEXE?editors=101)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
