### ISSUE TITLE
[Bug Report][2.6.0] Can't use VSteeper with treeshaking mode 

### ISSUE THREAD

**Issue by teixeiravictor** [vuetifyjs/vuetify#16284]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
I'm manually importing the VStepper Vuetify components and setting into each childs components (content, header, items and step) different suffix tag.

For example, instead of use suffix v-stepper-step we use if-stepper-step to register VStepper.

Basically, we manually import as VStepperStep and export with name IfStepperStep.

### Expected Behavior
Use our tag from treeshaking mode, instead of the default from Vuetify with suffix v-. 

### Actual Behavior
Force to use the default suffix v- from Vuetify. 

### Reproduction Link
[https://codepen.io/none](https://codepen.io/none)

### Other comments
If you check the [source code from the component](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VStepper/VStepper.ts#L112) you see that internally the method called as unregister() reference the default name as v-stepper-step and v-stepper-content. Both has v- suffix and maybe don't allow used the component with different tag.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
