### ISSUE TITLE
[Bug Report][3.0.5] VTextField could still clear input value by clicking clear button when readonly

### ISSUE THREAD

**Issue by MagicCrazyMan** [vuetifyjs/vuetify#16289]
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. create a VTextField with readonly, clearable and a default input value
2. click clear button, input value will be clear

### Expected Behavior
input value should not be clear when click clear button, or clear button should not showup when readonly

### Actual Behavior
clear button clickable and it will clear input value

### Reproduction Link
[https://codepen.io/MagicCrazyMan/pen/wvxwbrK](https://codepen.io/MagicCrazyMan/pen/wvxwbrK)

### Other comments
As well as VFileInput, it could clear selected file by clicking clear button and even trigger a new file selection dialog by click on input field when readonly

**Comment by KaelWD** [comment]
This is intentional, you can set `:clearable="!isReadonly"` but there'd be no easy way to replicate the current behaviour if we did that by default.
