### ISSUE TITLE
[Bug Report][3.0.5] onClick event on props VListGroup slots are missing

### ISSUE THREAD

**Issue by WizarDRW** [vuetifyjs/vuetify#16293]
### Environment
**Vuetify Version:** 3.0.5
**Last working version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
# onClick event in list group

### Expected Behavior
onClick event is expected to arrive in the slot.

### Actual Behavior
onClick event on props VListGroup slots are missing

### Reproduction Link
[https://codesandbox.io/s/reverent-cerf-ye0bxs?file=/src/App.vue](https://codesandbox.io/s/reverent-cerf-ye0bxs?file=/src/App.vue)

**Comment by jacekkarczmarczyk** [comment]
It's not missing, print out `Object.keys(props)` instead
