### ISSUE TITLE
[Feature Request] Add events @start and @end in `VSlider`

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16304]
### Problem to solve
VSlider in version 3 don't have the events @start / @end or @mouseup/down to know when the drag event ended/started, it would be also good to add @keyup/down when the drag is triggered with the keyboard arrows.

### Proposed solution
Add the events @start/end in Vuetify 3

**Comment by KaelWD** [comment]
Duplicate of #15675
