### ISSUE TITLE
[feature request] Add "right" alignment to v-tabs

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1630]
Be default, v-tabs-items in v-tabs are aligned left.  There's a prop to allow centering them, but, unless I'm missing something, no prop to allow alignment on the right.

Please add a "right" align feature to v-tabs.

**Comment by johnleider** [comment]
You can control this by simply placing a ```v-spacer``` at the beginning of ```v-tabs-bar```.
