### ISSUE TITLE
[Bug Report][3.0.5] useDisplay doesn't work if SSR is enabled

### ISSUE THREAD

**Issue by tadvas** [vuetifyjs/vuetify#16301]
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Firefox 107.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Set the `SSR`option to `true` in `vuetify.js`
2. Try to use useDisplay() with any param

### Expected Behavior
useDisplay should return real values

### Actual Behavior
useDisplay returns default values

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Ustu2zAQ/JUFL04RSyz6uBh2kQK99lb0EuagiCubjfgAuXJSGPr3LEUlUJyHL8ZqZmdnZ3l9EscByXT/639JbISxwUeCE7QRG8K/BYMRuugtrGbuSjnl8GGitt4lghmA3cvGi5NyAHRAixsW1dg1Q09/Sr3qzf5AKxjXmZRS3ADFAZUbPykn1uJnCDXrsqttaqMJBAlpCD+Ue3YZsVt6Y1/PkHe//eAI9XuEIeEvk0LfvLVe2eoE90bTYQ3W35oembdbtF2wzcKzac9IIdXHph8QLkEJaJzOf5dFpiDKbWVZhxfhgtCyGCFXANtj1YS8IfCPC9sYN1dTTfhAVWew18Cg19jvlODpPEQ+dclFWy6K4FYuBnG4JQZmBj68dxzydCo1A0kJPlhRVPmJ5FqJA1FIGykHF+72deutvGJMRg7aWKy0t1df6y/1t+9Sm0TL7zUmW91Gf58w8kQlpqPP4jn09wbMMOt+rmfZpxfLkq+kJOsfMVYRncaI8UPfZ9wX3s+wV/7zzJHfKmfZG3eXzmJs0xTh9U2mjGtRpJk87SFuHgHSQC7m)

**Comment by KaelWD** [comment]
You've done the same thing as #16298

The initial values are 0 because the server doesn't know how big your window is, it updates to real values after the first render.

**Comment by tadvas** [comment]
@KaelWD, thanks for the reply. The idea with the server sounds logical. However, it was not the route case. 
I changed `width.value` to `width` and it works as expected.
Please, take a look at the [example](https://play.vuetifyjs.com/#eNp9UstuwjAQ/JWVL1Apias+LlGoqNRrr71gDiFZwAU/ZDvQKsq/d/MoClCa2+7Mzs5OvKjZocIg19/Jp2cpk8oaF6CGwmEe8KPHoIG1MwomA3citND41VELo32AAYDZ+eC0FhrAe5dCcBUK3dwJzSL2am1CI7Qw84WTNoDHUNkXoU8GHK7Ha2nlCTL63VQ6YHmLUHl8k97u87+c94ZrOMoybCNQZiX3SLzZaGxKNnue8htCyMy041M/471lMktFQEUDAakCyA5xbtsrgD4qVC71UAHUNWk1zQDyEdoW/VzGR3qUU38RMS39HqMpry5QMQBesBS6TtujE9tasG0I1qecV9ruNklhFJ8Txh1lJhXGpVHzx+QheXrmpfRh3E/Qq3jlzNGjo42CRSPxNr9bCwaYdO+TQfb3XZHklRQn/QO62KEu0aH71/cF98z7BXblv91JkTeU5V7qnb+IsfBdhItlS2ki1ksTubuDLX8Awj0SLw==) if you want
