### ISSUE TITLE
[Bug Report][3.0.6] Theme settings are not applied to v-main

### ISSUE THREAD

**Issue by juretopolak** [vuetifyjs/vuetify#16316]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Define custom themes in the Vuetify config and toggle between them with:
`theme.global.name.value = theme.global.current.value.dark ? 'light' : 'dark'`

### Expected Behavior
Dark/light theme should be toggled for all components instantly.

### Actual Behavior
Changes are not applied for the v-main component instantly but are after rendering when pages are changed.

### Reproduction Link
[https://codesandbox.io/p/github/juretopolak/nuxt3-tailwind-vuetify/vuetify-app-layout?file=%2Flayouts%2Fdefault.vue](https://codesandbox.io/p/github/juretopolak/nuxt3-tailwind-vuetify/vuetify-app-layout?file=%2Flayouts%2Fdefault.vue)

**Comment by mnuxt** [comment]
<v-app> must be used as a root-level component to control the theme of containing components. In my case, it was <v-layout>. This issue can be closed.

**Comment by juretopolak** [comment]
`<v-app>` must be used as a root-level component to control the theme of containing components. In my case, it was `<v-layout>`. This issue can be closed.
