### ISSUE TITLE
Regression: Dialog modal adds two overlays instead of one

### ISSUE THREAD

**Issue by flybayer** [vuetifyjs/vuetify#1631]
I'm using a "routable modal" that displays using vue-router. This worked fine until 0.15.x

### Steps to reproduce
1. Click on **Open dialog** in [this fiddle](https://jsfiddle.net/7cbmwb09/1/)
2. Click **Close**

### Versions

- Vue 2.4.2
- Vuetify 0.15.2

### What is expected ?
Dialog modal should remove the dark overlay when closed

### What is actually happening ?
Dialog doesn't remove dark overlay when closed because two overlays were added on open but only one is removed on close.

### Reproduction Link
https://jsfiddle.net/7cbmwb09/1/

**Comment by KaelWD** [comment]
@flybayer You can set `showModal` to `true` in your `data`, but then the opening animation doesn't play. You should also wait until the closing animation is done before changing the route: https://codepen.io/anon/pen/YxoRGe

---

@johnleider VDialog.vue calls `genOverlay()` twice, once in `mounted()` and once again when `isActive` changes, the call in `mounted()` can probably be removed. 

To enable the animation to run initially (untested, might break things), VDialog@render:
```diff
const dialog = h('transition', {
  props: {
    name: this.transition || '', // If false, show nothing
-   origin: this.origin
+   origin: this.origin,
+   initial: true
  }
}, [h('div', data,
  this.lazy && this.isBooted || !this.lazy ? this.$slots.default : null
)])
```
