### ISSUE TITLE
[Bug Report][3.0.6] Global defaults not working for VExtensionPanels, VExtensionPanel & VExtensionPanelTitle

### ISSUE THREAD

**Issue by codeflorist** [vuetifyjs/vuetify#16314]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10, Linux

### Steps to reproduce
define global defaults, e.g.
```js
export const vuetify = createVuetify({
  defaults: {
		VExtensionPanels: {
			variant: 'popout',
		},
		VExtensionPanel: {
			'bg-color': 'blue',
		},
		VExtensionPanelTitle: {
			'color': 'red',
		},
	},
})
```

### Expected Behavior
elements should be styled according to defaults.

### Actual Behavior
alas, they are not.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVE1v2zAM/SucL+6A2N73IciGDkNvO+ww9FL1oNhMptX6qER5GYL899GWkyZOl+Zgh3qPT9QT6btt1kUktfpb/g7ZPFPaWU+whdqjJLxNGOxg5a2GfOTmwgiDm4FaWxMIRgA+nyZebYUBaHAlY0thDhwKEnR7syE0QVnzQxpsnwBBnfRKGppD7qyzkfJZQnbje5J6lJkv10VtW+tzTl62EV9I/amoxeP8Q7LH5jS3f+5eC5PNsq/OlXxYtmoRaq8cQUCK7oswB+s8ro4NG8xKLpFdr1tkk5hylXeSi3ybs+6iSlqswgGhdi17yBHAoiuk6+WBfxxoqQxH/I/9l8NpCn6ziXv6ZP0pdQIU1BswwgCDHSO3ukx+Tgs3ffVJ6rv1qEG5EDU0vakQFIHUmLoFa2LLPMhGORVUrcwasFVUwjertW3UDLwk1kbunKUiFeAx8gPZwVYuWRw620ZHTFrG8Apu5GNEqKNTjeJFBK34NuSFw+yrfQbszT1fTe6mhPEKUpAuZ1EdXRp3SeoFZjoeK2u4W4ZBECMQRDY0Xq8o+gHsY5H9InJhXlXRuId1WVtdXTNW+WhIaSwaq6/fl+/KDx+rRgU6Xi8x6GLp7Z+AnncUGTfsQbwfxP9tMMKs+6b8lGT33wOWPJOqWL9DX3g0DXr0F+uecE9qn2Bn9fd77njo2MtWmYcwsbEOg4V39z1lN8uSNJOHc2T3/wAY/LC1)

**Comment by KaelWD** [comment]
It's expansion not extension.

**Comment by codeflorist** [comment]
ah, my bad. sorry!
