### ISSUE TITLE
[Bug Report][3.0.6] Rounded image radius loss when height set

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#16315]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a contained `v-img` with `rounded-lg` class, apply a `height` to it or a `max-height` to its container, the image will loose its border radius due `to object-fit: contain` style of image.

### Expected Behavior
Border radius should remain on image.

### Actual Behavior
Border radius only remains when image can take full width.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtywjAM/JWMz8ROablk0g79DswhTURwiR9jORSG4d8rJxmghOKTd7VaSbs6sU/n+L4DlrMCK69cSBBC5z6kKcRA0JdAAO3aMgChJCn2aemiJqFHQJfKjKjHlTWBKPAXsqeVbq54fOird8m2ITjMhdiUOyAVd62YL7LDS5ZJNmmp2hKRmrztTA112jYPRBiOLURnUM025AlZucMDnbjuLaaLR+5yXATD2YW4iYPNmNLO+kBKx7/RGgrzFBvkWEDJ8qRnIkdpR3w9ujNu1/DKarGkmvCdCUpDWlu9fOVz/rYQtcJwy3NAnX55+4PgaaJksxvzoDbH/waMZfLN+HywHaloObES5L8Hn3qgoD34p3vfaf/sfleb7B9nnqU5U5atMju8i7HCPsLVOkrOMzZYk7i/g61/AeW/3l4=)

### Other comments
I don't know if it is a known issue, I didn't found it inside repo issues.

Material Design frequently uses radius on element and not being able to apply radius on some images seems sad :'(

**Comment by johnleider** [comment]
Even though you're setting a height, it's going to expand full width in the container still. 

![image](https://github.com/vuetifyjs/vuetify/assets/9064066/d6c94ece-f078-4efe-ba05-29390842d607)

Set width instead or use the **cover** prop.

https://play.vuetifyjs.com/#eNpljkEOgjAQRa/SzFpbUNmYSuI5rIsGqjRCmbQDmhjvbikGTdz992aS/09PCL4SR0Q+Dgb2IEPlLRILhgYspZixVE45SabDVpOJxJgc1xoxxQSdtu5DiaveUVTGLzJp211ZbDwoaIgw7IW46JuJlmMrNkX2yLNMAfP94GpTs7utqYnP8RKt+BaI/4bJLSsmmPdJ8bMbXivY8h3PC5hCwXM4vwGg8VAe

**Comment by agersea** [comment]
This appears to have been re-introduced.  I'm on version 3.7.1 and the border radius styling fails to be applied when setting a height.
