### ISSUE TITLE
[Bug Report][3.0.6] `v-tab` vertical is break with `stacked` prop

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16317]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use a `stacked` prop with vertical `v-tabs` 

### Expected Behavior
It should take 72px min-height same as the horizontal tab do.

### Actual Behavior
It height does not incease.

### Reproduction Link
[https://codepen.io/Alokdev/pen/gOjpPOL?editors=101](https://codepen.io/Alokdev/pen/gOjpPOL?editors=101)

**Comment by johnleider** [comment]
This was fixed
https://play.vuetifyjs.com/#eNrNWE1vGzcQ/SsDXdwCklwnzaVwAgRJC/TQNECQU90DxaXkabjLDT+UFEH+e9+Qu9LKomOlNoLoIGiXy+HMmzdvRvvXp1nw+vx53y+3ycx+mV1G0/ZWRfPsqiO63C5U3+ef+UIr3wxX+To6Z1fKk3bW+adXs95zq/y/V7PdQ9PHFpGjNc/eBuPptXdrtuby/Obqzvp+ZX+v4S1pq0LAWc1ibc1Hkq+Fdx+OzlSrsL9BtF20rjEWG7FyNZsuNeyNjuw6LG6Nj6yVPXziKL7pYohKvzPN9JayvOmyC9ikTReNn+6ZeDr6Sltlk8HTrhdPFhcH8QzPsXadHOfjM2obXiitXepixkrWbuz4M5uii4PTBFa1OsGDR6d4YJ1+d8fxj/7f8Y9PBMCEsOgd34nC4y+7MdwJhyT6wF3jPtzkzk3vy1MLRumclEapIvBWxRtLu8VFNB+PF7E8luLh541phHHvk2op2egZoFCrkuewpJeuM5p6F5LxhrbJ9imivEl5nZY1a384v2JSmtbGioFfI8Pu2qQNq0ioA0TZAdDWxITlfDhZXhnvKvYuz8Xnk0N5haO4D6klOJ/CnHyKHldbjsrMaWtC5FWyuGPSnFpn5QbCMnZeM2eVFh+fm86ojqKxNgEZcXxOK7jcNbAUTDPfAaQ0zKoY+UA8xg/inlOXOg2bA+DWrRwkQ045uvMmhR5ncAhGtlYtcrAUOJKCWxIHfl5jjzcev0r0XwXrTh/b1eKnI/aVz+trFQoWjQjbkn5LQcNF8z6Z8WJtfAvhAj6uYYc1fTtlXsOYiFzA/oEKFIGB83OK3GluRKVMPLja4LpmLKABoUHgwDkJnsuJuyurACdYaBylmD27FZyb924vrXHtsK5xc1LYX1HzVeF86JovVSpZGetwwrW1ShplApILVwE89ZMM1cwhG5BVbMgVQwqPoul1iAwaMBQOyk+qkBiPyN3yqDC2ZpGbgQJFIlCq2DMnUAN74l6nZN4Q20WvSvHX7I0CV+iFyCBBquGeg+ZuU4hMyXcKauS85iW9SF6tOCZfVQbeJKsoqJ4NanrPy1ziJnGA5I+yM4hDNUwha8PCbZBySa8EcCgK4Vz4dn9FPMhrEeE7kl2zMs3/1yS7GvJR/qfJxmDHHTZjkPIKRww4DwpXs7ejQqn83R6RG8ISFF68HlOFBa1TGyDoEE+uWRy4hB4mdFvS7x1d4+Ja6ABxNJQnXIXBT0PgAgAtmqd0zVrug3uNHrzrr5U30StBruEilQ+QbTAHBgOUWBVKZaGcNCvXKDQ9wJA2AKU0DJ08mmW1vYASIqMIYOPVlhsFcDYokhYtfuzauetq14LxjmBIo6qqmSpyDDSzizpCeaDUhemix9mbUu/FpXHtVi6NrBl7p0mlvd4byDK1wKc+een5uaWPxBhAHDVlSW/hu/Jcx3CvDSNewzwxkJz8teukFHrToH2+FLCzFmRS1Rl1am+9X58vs98W3nZKwt9Pf3mM+3IgNYNIfZO4UGg/M+VWfjCbSadHMUORIU4yBtSM/ZNCHFHa0W+U+YzHgc6ZjtuBT1VzpZjLNDdKFJyclGeZKUQ0vr+hofp356GHhkHljsYqYQnElyDcOSl3jgtrpRn4yowr2pElCsT4btX/RNJWq/+AxwNpH7pQX3gFANSGRaUeKjMlFwW4MldJ9D4CQmkfEk/uDLtxp5oegNQisUVKcmnmfjgfEsfIXC6rwwkjVbHs0TEZUJdTEVehD/5Wlj4gYQ5/0vCHHnOV1POIyjcv2f3K5KUU3kCNr8Om1uSivCm7PJ+8QcNl0J77iGBjKt5iYkSw9Im8WdNnWnvX0hlevp0V+khrBR54IfJUnvjhbHyTcPajGC/mYGj2eT57vPx5efFkJj+eLC9mf/8HdMa+AQ==
