### ISSUE TITLE
[Bug Report][3.0.6] Tooltips on buttons are incorrectly placed on second hover

### ISSUE THREAD

**Issue by jeremyVignelles** [vuetifyjs/vuetify#16321]
### Environment
**Vuetify Version:** 3.0.6
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.1462.54
**OS:** Windows 10

### Steps to reproduce
Hover the cart button. The tooltip is correctly placed.
Hover it again, the tooltip is off.

### Expected Behavior
The tooltip should be placed consistently, centered over the button

### Actual Behavior
The tooltip is shifted upwards and to the right.

### Reproduction Link
[https://codepen.io/jeremyVignelles/pen/LYBVQBe](https://codepen.io/jeremyVignelles/pen/LYBVQBe)

**Comment by Fabioni** [comment]
the tooltip gets the correct location when you scroll the page during hovering over the button.

**Comment by Fabioni** [comment]
Example from the Vuetify page itself when hovering over the GitHub icon (https://next.vuetifyjs.com/en/components/tooltips/)

![image](https://user-images.githubusercontent.com/45362676/211704171-2571b6c8-a2f1-4804-88c1-f0b719c51996.png)

**Comment by jeremyVignelles** [comment]
Yeah, the code in my codepen is actually the code from the tooltip documentation

**Comment by Fabioni** [comment]
The issue is only closed partly, unfortunately. Now, the tooltip is wrongly positioned after resizing the window
## Steps to reproduce
(1) hovering
(2) resizing the window
(3) hovering, *now its wrongly positioned*
(4) hovering, now it is correct again
