### ISSUE TITLE
[Bug Report][3.0.6] `v-menu` with custom transition does not work with RTL

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16325]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use RTL 

### Expected Behavior
It should work like previously in RTL. 

### Actual Behavior
It is getting hidden in RTL Mode, not the menu dropdown shown.

### Reproduction Link
[https://codepen.io/Alokdev/pen/oNMXyJq?editors=1010](https://codepen.io/Alokdev/pen/oNMXyJq?editors=1010)

**Comment by KaelWD** [comment]
Possibly related to #15352

**Comment by johnleider** [comment]
This is fixed as of the latest version:

https://play.vuetifyjs.com/#eNrtVsFu2zAM/RVCO6QFIhtYexiCtOiw804rhg11D6rNrGpkWZBkL4Hhfx8lO4nr5NBhBXpYL4FF8vE9ioZf7lrW1Ojlaps8ObZgsjSV9dBCblF4/N7noIOVrUqYDbWzTGcaN7E0r7TzMCTg6jnwrM00gKpyoXBBXXdPM2Fn0M1D0j9iGXMFrkSt/G1/nin569H3Rd15ptmcfTYmIR5SufRYGkU016HDsuHCmPhIh0I2kCvh3FXGSsEvwdBPxob0pPoIUfCVwg081S7I586IHLmwVa2LUY+hT4m6Bm+FdtLLShPchfH4ITTBEGqnHD6I3MtG+MoSrgVjK+OgOwJEogev6Z5VLDVWlsJuMwYUl7qIIcISEr4Ferjd08MyjeCpiHR0f5NUw5V0/pSIEOeSkES8ilLOwmkO8hykhvBMImCxxi3l5IlJnrfhXnqF120boUk8QdcFydOaIzXjmqPhTowQgmFbk3lP71DJAvnmDbcYBMCP9z2+xh63b73Hn3+5x/9ri4cQfYUP32gqGH3S97lDfPLqL11upfHg0Nc9bG9kFldj+4rWBYNrxVsiz7rriVqIA5L5fFEyX8NX3JnUa+bg4y57H+bolZNmcrheNC+FITeuNDld9E/aX0zQQsko+75Z8O1wztij98Yt0jQvNMEKVLKxiUafalOmN1SW2lp7WSIvqvLmIrlILulGnR+HE3Qlf7DVb4eWmmRskB9pghW+gGqojAyfeoYhxJV4cIHiqHVKfA1ablEXaNG+dKIJbDzVJHU0WWDv6E8F3beSeu0mV527eM3DK/GPI8dmw6o71s1Z1EnMEcDu/wCbLuzf

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
