### ISSUE TITLE
[Bug Report][3.0.6] Hitting "Done" on IOS virtual keyboard collapses menu for V-Autocomplete causing it to lose focus and close

### ISSUE THREAD

**Issue by demariaw** [vuetifyjs/vuetify#16326]
### Environment
**Vuetify Version:** 3.0.6
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on V-Autocomplete to view menu items
2. Hit "Done" on IOS virtual keyboard

### Expected Behavior
Menu stays open and input remains focused

### Actual Behavior
Menu closes and input loses focus

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtOwzAQ/BXLl1ySGPE6RKFqVQl+AIlD04PbbIpp/JDtFKoq/846DihtBT55Z2Znd2d1ogtj8kMHtKCl21phPHHgOzOrlJBGW09OxEJDetJYLUmC0qRSJYtaVGHhQZqWe8CKkPKQcRPaCT4sJBdqrEaEd15vNbaAh0i0fAPtU0UXU4ZGrhBo75BcJUveikZbJXiSkmSpW215rcP/Gb+iHuAX0HYXFa/wxV34vB21FGqXrKPprGTnW/xsi/DvuoNmOKRkkwNpSmMuqDT5h9MKkzuFhmokXEULMiABw7xCXdF3740rGOuU2e9ynMzmyDHbKS8kZLWW87v8Nr9/YLVwforn4GS2sfrTgcWJFU0n5l40x78GjDT63uSP0XaEguWVFUP/A9jMgqrBgv137wvt2e4X3NX+YWZfqR6zbIXau4sYt26IcLUOkj6l0RrFwx10/Q0n9+Vb)

**Comment by KaelWD** [comment]
There doesn't seem to be any way to distinguish this from any other blur event.
