### ISSUE TITLE
[Bug Report][3.0.6] class doesn't work as expected in v-tooltip

### ISSUE THREAD

**Issue by ErosBurastero** [vuetifyjs/vuetify#16331]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
When i try to style the v-tooltip tag it doesn't work

### Expected Behavior
Is expected to custom the tooltip with class="" or native vuetify attributes

### Actual Behavior
 the majority of styles i've tried to provide it, no one works as expected, for example, using bg-blue, all the main screen got blue.

### Reproduction Link
[https://codesandbox.io/s/compassionate-lamport-z74kwp?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/compassionate-lamport-z74kwp?file=/src/components/HelloWorld.vue)

**Comment by KaelWD** [comment]
`content-class`
