### ISSUE TITLE
[Feature Request] Export color pack in Vuetify 3

### ISSUE THREAD

**Issue by RafDevX** [vuetifyjs/vuetify#16346]
### Problem to solve
Vuetify 2 previously exported its colors (see [here](https://github.com/vuetifyjs/vuetify/blob/9169a06822dedbd0c35e227104925dd4acf0a1a1/packages/vuetify/src/entry-lib.ts#L3)), such that
```ts
import colors from 'vuetify/lib/util/colors';
```
previously worked, allowing users to patch into Vuetify's colors and use them.

However, after upgrading to Vuetify 3, this is no longer the case, despite [being listed in v3's documentation](https://next.vuetifyjs.com/en/styles/colors/#javascript-color-pack).

### Proposed solution
Export the color pack, for example, as a named (non-default) export of Vuetify - e.g.:
```ts
export { colors } from '@/util/colors';
```

**Comment by Bassadin** [comment]
> ```
> import colors from 'vuetify/lib/util/colors.mjs';
> ```

This nets me the following error:

```
Could not find a declaration file for module 'vuetify/lib/util/colors.mjs'. '[...]ttn-locator-frontend/node_modules/.pnpm/vuetify@3.2.1_vite-plugin-vuetify@1.0.2_vue@3.2.47/node_modules/vuetify/lib/util/colors.mjs' implicitly has an 'any' type.
  If the 'vuetify' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'vuetify/lib/util/colors.mjs';`ts(7016)
```

**Comment by SIGSTACKFAULT** [comment]
`import colors from "vuetify/lib/util/colors";` WorksForMe:tm: but there's no typescript defs
![image](https://github.com/vuetifyjs/vuetify/assets/14184826/99a48938-43f4-4f08-b2e2-3665a364e486)
