### ISSUE TITLE
[Bug Report][3.0.6] VBtn icon is not visible when used as parent of VTooltip

### ISSUE THREAD

**Issue by peshanghiwa** [vuetifyjs/vuetify#16357]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Copy this exact snippet which is from the official vuetify 3 docs: https://next.vuetifyjs.com/en/components/tooltips/#props

```html
<v-btn>
  Start
  <v-tooltip activator="parent" location="top">Tooltip</v-tooltip>
</v-btn>
```

which works fine, but when the button props are changed to the following:

```html
<v-btn variant="text" icon="mdi-account" color="primary" flat>
  <v-tooltip activator="parent" location="top">Tooltip</v-tooltip>
</v-btn>
```

The button breaks and no icon will be shown while the tooltip is visible.

### Expected Behavior
To show an icon button with hover effect

### Actual Behavior
There exists the hover effect but the button icon is not visible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctOwzAQ/BXjS0FqEsTrULVVufEBSBzqHlzHKabxQ/YmgKr8O+sklDStyCmzM5mdzK4P9Nm5tK4kndE5SO1KDnLJDCHzOuHOta8t0FyZHvWTLZg/3D0194obWDAK8gsYHfNKWIOkzlXChbCVuaARtrQeRc4rzf33uaDAjKezQa5jOrC2BOUIF6BqDp0l9zKuJKUVHFSbBaxjdPnaqefZ8cORZ2Twh3/7QHQsJIKuqnk2qBBhEF45IEFCFWmlnfVADsTLgjSk8FaTCXY/iWJsJgDRYUcWkb+evMiytOTN+jK/mtxE884OjeiUdl4YwqUfwRo83yFmYT0RGJ2RdhJnuCNiRt8BXJhlWWXcfpcKq7MVcpnHQygtk9zq1X16lz48ZrkKMJynMuhk6+1nkB43MjodmIMq8E6XF/Q0+t6mT51tP4qWZ1YZ+tfSJ3ioXHrp/8090p5kH3Fn+ePOhpkGuyyV2YdRjSK0Fa43UdJMaWeN4vY/6OYHgXgEGA==)

**Comment by peshanghiwa** [comment]
I believe the issue is with the VBtn component with **icon prop** as if anything injected into it as a custom slot it will override the icon by default and show the injected slot content.

ex: replace the v-tooltip component with a text and the button will show the text even tho it's an icon button

**Comment by elboukhari** [comment]
I can't reproduce it [here](https://play.vuetifyjs.com/#eNp9kctOwzAQRX9l8KYgNQkCxKIqVdnxASAWdRdpMi2mfsmeFKGq/844SR+0iJ3n3tG5M+PZVjx7n28aFCMxJjRel4QTaQHGm6z0vn22hSmVPVYLal+V0y48SbHQDWargN9SdC0APqBHW2eqcpY7TK2ySrumzhqvXVlL0cMA3jqhrxhOzmlSfq8AlBWpTUltlC8DWjrmAGhXlaTaFA48OpPXjjMuDsj9AqzwBocJUn3YLxXd5uPi5CJcxiooTxCRmmQr410g2ELAJexgGZyBAZ9ykJp560hg4gqekn89eEGtHby7oOurwU2CdzgGiaHoWDyEzz+js/wb2zSL7I0oxQhaJWmckWopPoh8HBVFY/16lVfOFFP2itBYUgaz2pnpfX6XPzwUtYp0qucYTbYI7iti4EQphidwUkv+yL8Depu5t/ljh+2lhLxAFczfYMj4z2oMGP6d+6z31+xn3sX8KXMn7Y5vqZVdx7MzVrE94WyeWnZD0aG5ud1DzH8AzsT99A==) . Works fine.

**Comment by peshanghiwa** [comment]
@elboukhari that is because your version of button **is not an icon**  if you use **prepend-icon** property on a VBtn it will still be treated as a normal button and you must have a text inside it otherwise it doesn't look symmetric (try removing the **Upload** text to see what i mean).

But in a case of using **icon property** (which is my case) your button style will be converted to a specific Icon button style and then the issue occurs (try replacing prepend-icon with icon and the issue occurs again)

**Comment by elboukhari** [comment]
@peshanghiwa In your repro link, you use a 
`variant="text"` and an `icon="mdi-account"`. But you don't have any label for your button. That's it.
Your button is not an icon one, but a text variant..

**Comment by peshanghiwa** [comment]
@elboukhari Seems like you're not getting the point, please take a look at this example [here](https://play.vuetifyjs.com/#eNp9UctOwzAQ/BXjS0FqEsTrUJWq3PgAJA51D67jFlO/ZG+CUJV/Z52EEhJETtmd8ezs7OZEn7zP60rSBV2CNF5zkCtmCVnWGfe+/W0Lw5Xtq76zA/tTd58Szj4yakqVcSFcZYHRMUc47QKSfFCGh88pQfOd1EgAGSfPBw7OPsA5DcoTLkDVHDpxHmQaTrQTHFTrCpxndPXSsZfF+eFIMyG42vfmWJ1XT0UXyrIYhIVlFEF5IFFClWBlvAtATiTIPWnIPjhDZpjyLJExowjExAN5TPjl7Flq7cirC7q8mF0l8U4Oheicdlpowufv0Vk81Cl5YT0QGV2QtpN6OCPVjL4B+Lgoisr64yEXzhRrxIqAJ1FGZqUz69v8Jr+7L0oVYdjPZTTZLriPKANOZHQ+EAe1x4v9PaCHUfc6f+hk+1aSnEgVqF/LkOGhShlk+Nf3iPvL+wib+E8zG2YbzFIre4yjGEVsI9xsE6WZ004aye0edPsFcxH+3g==) which is pure button with no extra props (with or without label property & with or without text property) the issue still exists,
I already Had figured out and explained the reason [here](https://github.com/vuetifyjs/vuetify/issues/16357#issuecomment-1368888212) 
**Buttons with icon prop doesn't work when used as parent of VTooltip**

**Comment by elboukhari** [comment]
![image](https://user-images.githubusercontent.com/36670922/210326569-f8b18b51-d780-4d73-91e7-6c913d9b4b89.png)

**Comment by KaelWD** [comment]
See #16060, `icon` is treated as a boolean prop if the default slot is used

@elboukhari `variant` and `icon` are independant

**Comment by peshanghiwa** [comment]
Thanks @KaelWD it works well now with your [solution](https://github.com/vuetifyjs/vuetify/issues/16357#issuecomment-1369535805)!
As an improvement it would be very great if we could directly use it.
I'm closing the issue now.
