### ISSUE TITLE
The theme color of vuetify@3.0.6 is different from the official website demo

### ISSUE THREAD

**Issue by rdzhaoxin** [vuetifyjs/vuetify#16358]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/35715627/210240395-744e8c78-27e3-44a1-81ca-a072cb8160cc.png">
The button color of the official website demo is completely different from that of my local project. What's the matter please

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/4fb7549c551e7ac12a02c39cd16c0fba82cb9e60/packages/docs/src/plugins/vuetify.ts#L36-L55

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
