### ISSUE TITLE
v-form validation docs should explain submittal with validation

### ISSUE THREAD

**Issue by bbcharlton** [vuetifyjs/vuetify#1635]
### Version 0.15.2

In the documentation for the [#2 VForm - Validation w/ submit & clear](https://vuetifyjs.com/components/forms) component, it only has the validate function when the submit button is clicked. This only returns true or false. While that's helpful, I think it would also be great to show how to submit the form if the validation returns true. For example:

```javascript
methods: {
  submit () {
    if (this.$refs.form.validate()) {
      this.$refs.form.$el.submit()
    } else {
      return false
    }
  }
}
```

Took me some time to figure this out, so I thought it would be a good way to help others that need to validate their form and submit it to their back-end.

**Comment by jacekkarczmarczyk** [comment]
Can you move this issue to https://github.com/vuetifyjs/docs repo? Thank you

**Comment by johnleider** [comment]
@jacekkarczmarczyk is correct. This issue should reside on the docs repo, thank you!

**Comment by bbcharlton** [comment]
My bad. Will do!
