### ISSUE TITLE
[Bug Report][2.6.13] VCheckbox - v-model set with array, but multiple selection don't work

### ISSUE THREAD

**Issue by vernou** [vuetifyjs/vuetify#16360]
### Environment
**Vuetify Version:** 2.6.13
**Vue Version:** 2.7.13
**Browsers:** Firefox 108.0
**OS:** Windows 10

### Steps to reproduce
The example is two check box that share the same v-model that is a array. Their prop value are set to two distinct object.
In the initial state, the multiple selection work.

When the check box's prop `value` is updated with new object.
The multiple selection don't work.

```vue
<template>
  <v-app>
    <v-main>
      <v-btn @click="refresh">Refresh</v-btn>
      <v-checkbox
        v-model="selected"
        :value="item1"
        :label="item1.name"
        />
      <v-checkbox
        v-model="selected"
        :value="item2"
        :label="item2.name"
        />
      <div>{{ selected }}</div>
    </v-main>
  </v-app>
</template>

<script>
export default {
  name: 'App',
  data: () => ({
    item1: { id: 1, name: 'User 1', email: 'user1@domain.net' },
    item2: { id: 2, name: 'User 2', email: 'user2@domain.net' },
    selected: [],
  }),
  methods: {
    refresh(){
      this.item1 = { id: 1, name: 'User 1', email: 'user1@domain.net' };
      this.item2 = { id: 2, name: 'User 2', email: 'user2@domain.net' };
    },
  }
};
</script>
```

### Expected Behavior
With v-model to a array, I expect the selection act multiple.

### Actual Behavior
With v-model to a array, the selection don't act multiple.

### Reproduction Link
[https://codepen.io/vernou/pen/gOjMeMo?editors=1111](https://codepen.io/vernou/pen/gOjMeMo?editors=1111)

DON'T WORK
I'm sorry, but I couldn't manage to use this tool, because it is based on a syntax that I don't know. I hope the example below will be enough.

### Other comments
With the debugger, I see that update the prop `value` trigger the watch [value](https://github.com/vuetifyjs/vuetify/blob/v2.6.13/packages/vuetify/src/components/VInput/VInput.ts#L138). Then the `lazyValue` is updated with the value and lost the selection array.

**Comment by vernou** [comment]
I can't reproduce the bug in V3.

**Comment by KaelWD** [comment]
Workaround is to explicitly set `multiple` instead of relying on the model being an array
