### ISSUE TITLE
[Bug Report][Playground] Menu stops working after first edit

### ISSUE THREAD

**Issue by yeya** [vuetifyjs/vuetify#16378]
### Problem to solve
The default playground doesn't have a style.
After adding a basic component like VSelect - the list will not shown until adding a style.
I'm doing it [this way](https://play.vuetifyjs.com/#eNqtkk1PwzAMhv9KyKUgtQ1sIKRpQ+PGD0BwWHYYrbeF5UtJOpim/nfcppu68XHiVud1H9uvPdvTbQVBLHf5u6cjKpQ1LpCke2Q+7CT4hOtO2JPCwSLAS9RJTZbOqGM+JnINn21qYbQPpBPI5PTHyz3XhIQ1KBghtITlopLhOcaJFKt1SEidcl1fcU1T+mhtjijscBxAWYmkh4Yw3mYLa9vPNlALobuojT1IKLCLTJkS5IRT5VeckpFAisdwdpMO0uEcn9gBwnqUJoj8MevVxdAXTthAPISqkY/2OFj2TWkNiU5gZXQB9cvkCaQ05NU4WV4kOOCYRRyCcNbIwiYs7sRonLk1i3eC5xQti83yZntNzOk6BOtHjFXablZ5YRSbosZcpYNQkJVGTYf5IL+9Y6Xwof+eg1fZmzMfHhxW5BRtP8KbZf1WoJORe53fR+zhmBD5I6o7qH8iMux4Cy5zoEtw4P504iz3xI0z7ZsjTc0ajxG3I4Xe+LPFFL6daDZvUuqURjQmt3PQ+Rc3gSYy)
 
but I guess I'm not doing it right because it needs a refresh each time I change something.

### Proposed solution
Set the basic playground template of vuetify 3 with style that works.

**Comment by nekosaur** [comment]
1. Your link seems to have been cut off and does not work
2. What do you mean by "default style"?

**Comment by yeya** [comment]
The link works, why do you think it cuts off?

Anyway you can try copy and paste to the playground from here:

```
<template>
  <v-app>
    <v-main>
      <v-select :items="[1,2,3,4]" v-model="msg" />
    </v-main>
  </v-app>
</template>

<script setup>
import { ref } from 'vue'

const msg = ref('Hello World!')
</script>
```
Now click on the vselect to open the list.

Do you see a list?

**Comment by yeya** [comment]
It because the workaround I found.
I added the vuetify/styles to the import map.

I'm sure there is a better way to do it, and I think the default playground
should include it.
