### ISSUE TITLE
Several styling issues with box text field having prepended/appended icons

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1638]
There are few problems with text field but all look related so I'll create just one gh issue

### Steps to reproduce

Create a text field with prepend/append icon and box prop

### Versions
0.15.2

### What is expected ?
1. Prepended icon in box text field should not overlap the input
2. Left side of error message should match the left side of label (box text field with prepended icon)
3. Not sure about the MD specs, but I think box text input paddings/icon positions should match paddings/positions of solo input

### What is actually happening ?
1. Prepended icon overlaps the input
2. Error message has too much left padding (box text fied with prepended icon)
3. Inconsistent styles of box and solo inputs (look at prepended and appended icon positions)

### Reproduction Link
https://codepen.io/anon/pen/GvbYLQ

![image](https://user-images.githubusercontent.com/15625235/30211776-97f62aa4-94a2-11e7-9bc3-aacce29199b2.png)

**Comment by jacekkarczmarczyk** [comment]
Updated screenshots in PR desc, now it's easier to see what as changed

**Comment by johnleider** [comment]
Resolved with your PR.
