### ISSUE TITLE
[Documentation] v-data-table examples use incorrect sorting for "Iron (%)" column

### ISSUE THREAD

**Issue by Shamus03** [vuetifyjs/vuetify#16382]
### Environment

**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Sort by "Iron (%)" column (either ascending or descending).

### Expected Behavior
The values should be sorted in numerical order (45% should be first in descending order, and 0% should be first in ascending order).

### Actual Behavior
The values are sorted in lexicographic order (8% is first in descending order).

### Reproduction Link
[https://vuetifyjs.com/en/components/data-tables/#examples](https://vuetifyjs.com/en/components/data-tables/#examples)

**Comment by MajesticPotatoe** [comment]
Duplicate #9704

**Comment by Shamus03** [comment]
The issue you linked is itself marked as a duplicate of #7149 (and was thus closed) but it is a different root problem.

#7149 is a request to fix a bug when object keys contain special characters.  This issue, and the one you have considered it to be a duplicate of, are both related specifically to the documentation.

**Comment by MajesticPotatoe** [comment]
document examples have already been updated in 7ed629d
