### ISSUE TITLE
[Bug Report][3.1.0] CSS specifity issue with text-color on v-badge

### ISSUE THREAD

**Issue by mediafreakch** [vuetifyjs/vuetify#16384]
### Environment
**Vuetify Version:** 3.1.0
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open the codepen provided

### Expected Behavior
The text within the badge should be black

### Actual Behavior
The text within the badge is white

### Reproduction Link
[https://codepen.io/mediafreakch-the-flexboxer/pen/rNrWKyY](https://codepen.io/mediafreakch-the-flexboxer/pen/rNrWKyY)

### Other comments
~~Doing the same on [vuetify playground](https://play.vuetifyjs.com/#eNp9U8ty2zAM/BWWPSidWpLj1od4lEx66wd02oPpAy3BFmvxMSTlJuPRvxckFdlxJjmJwC6WALhan+ixBy92z8VfR1dUSKOtJydSW+AefieMDGRntSTZyM2YYgqeIrXWynkyAuT+deHNiSlCfAsSVijawI73nf+V4qwT+9ZnM3LkVnAvUCiQat1pi6d1ZqyQ3D5nmxmJVFArsiDDbFQM7CBPEjpFZJKYEoSMWnjr57s5X24bnCEhQzrEz4DqTA1fmKIz+sOYAufCrVQepOlwrIdAqo45NyYeYyC5UKTuuHP3jBqeLxgdwQjX3DZECpW3ENpEznLO6HsFzGPJljd7CJvFkUPB17tQEIYKBWmSfFxJfouYhyefvxC2Ha8PF5KjqEC9B9mIvNUSqnJMnEkhFS8+N4+Z0P25uTQypsPMaRkYpG1U5cWWMHS1FcYTB74P8OQsC7tLP0UvJRNJt0cDIX6T/YSu0+SPtl3zKcPnqMokh0L4MkkLmzDoWq3wheJLsxFwjE5vz4K/Q8xo671xq7LslTnsi1rL8hGx0vbKCwl5o+Xjt2JRfF+WjXD+Ml+Ak/nW6n8OLN7IKJpkEg8+f++CEUbd22KeZF9+N5R8I1Wi/hFsbkE1YMF+2PcV91XvV9ib/qPX0ei4y06og7taY+3iCtebQBlmNEkjOc5BN/8BMW9fwQ==) works~~

**Comment by lioneaglesolutions** [comment]
This only seems to happen when using pre-defined colours (`primary`, `secondary` etc) @johnleider 

Repro below showing that this works when `color` is something like `blue`

https://play.vuetifyjs.com/#eNq1UstuwjAQ/JXI1xK7tPSCUkS/A3Mw8RZc4odsh7ZC/HvXTkApVJWiqjfPjD07u+vVkbw4Rw8tkDmpImjXiAgLboqiOpTCuXzMQAtliroRITxz4kQ546QXs7wRcgtFhI9Y1raxHi95kJwUZ7RpWsjQRDARibspwqGFQm2hpSp3VkPFeuJyAYlc5MKMqe680sJ/3gY4d6Sb1NEf8oxJEwCd5P/mSTjtrFsmgm6bFRtsGWGovXKxCBDbTu4IPJIJUdpZH9HG0bdgDf6RY3LjvRA4mReZSRx+ooQ52cXowpyx1rj9ltZWsyVqzLcmKg2ltHr5SB/o7IlJFeKQpxB0ufH2PYDHipxMBuZRveK8fi7Qy+g7pfedbU8lyxsrhv4H8KUHI8GD/zX31d1v2a+0m/yp5ombE86yUWYfrsZYhzzC1TnaqMa0MjQbpNfrVOQ0IV04LJcfkPUXCe8/xw==

**Comment by KaelWD** [comment]
This is because the generated theme stylesheet is inserted after the rest of vuetify's styles. I don't think there's a good way to guarantee stylesheet order, this will have to wait for #15596
