### ISSUE TITLE
[Documentation] No documentation for FABs (404)

### ISSUE THREAD

**Issue by ClixStudios** [vuetifyjs/vuetify#16387]
### Environment

**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
People seem to be unable to easily find out how to create FABs with Vuetify 3+

[Example](https://stackoverflow.com/questions/74842407/how-to-create-a-fab-button-in-vuetify-3)

### Expected Behavior
- FABs should have a segment on "buttons" page
- Or even it's own page like v2
- Enabling doc search to redirect people

### Actual Behavior
- No FAB segment or page is found (only a broken link)

Some cannot find it via search

### Reproduction Link
[https://next.vuetifyjs.com/en/components/buttons/](https://next.vuetifyjs.com/en/components/buttons/)

### Other comments
Add a segment to the [Button page](https://next.vuetifyjs.com/en/components/buttons/) called "Floating Action Button - FAB" so that the doc search feature can direct people to the "icon" prop of v-btn

If not on it's own dedicated pages (like v2)

Additionally, there's a 404 [here](https://next.vuetifyjs.com/en/api/v-btn/) for a "FABs" doc page

**Comment by lorand-horvath** [comment]
Well, the page itself exists, just not wired into the router I guess... https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/pages/en/components/floating-action-buttons.md

**Comment by mcfarljw** [comment]
Has this feature even been ported to v3 yet? I feel like a saw an issue open for it about a month ago but can't find it anymore.

**Comment by MajesticPotatoe** [comment]
FAB page doesn't exist atm (it exists in source as the doc pages are carried over from v2, but the component hasn't been completed yet, so its disabled from router). Will be available when #13508 completes.
