### ISSUE TITLE
[Bug Report][3.1.0] Border-radius v-text-field

### ISSUE THREAD

**Issue by vduggen** [vuetifyjs/vuetify#16390]
### Environment
**Vuetify Version:** 3.1.0
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
I left two examples of how I tried
First:
I sent rounded props with the values ​​that are in the documentation
Second:
I tried using a class

### Expected Behavior
Applies if the border radius on input

### Actual Behavior
is not being applied

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNU8tu20AM/BV2L24BS1ur6cV1iuRQoH/QQ5SDKtHJJvvCLuU4MPzv4Uqyoch5HXMzZ+gZkju62olL7/NNi2IpVoTG64rwd2kBVpus8r772RWmUhZqXcV4XgpfZWelGEim/2wr/isuQJ5gxRFbyV6ll+ei11/JkS+XsQ7KE0SkNtHKeBcIjg7r4AzMcnkA0vCzX9O+YtpXHPoAjr07CLiG/dCa+DRA7WwkMPEGzhP/dfYXtXbwzwXdfJl9SwP3I/JwYi56LV7M53fRWb7jrjMZiFiKJXRIwtgj1aW4JfJxKWVr/f1NXjsjL5iTobWkDGaNMxc/8iI/+ykbFWmM5xhN9j+4h4iBHUsxH4mTWj++ZjDQrLvIv/eyA5QkT6Qk628wZAFtgwHDm3NPep/NPuFO5k+e+9Lu+ZZa2fs4OWMduxNeXfct42d/KbOEW8rWCnUDwbVs2XBct7oUsKmCqixx6VpiJ2wSmBnXoGaQH5zrlNWPBfKD4bmkJEawOE3OOJnvrHL47oaVsk+wUDFdaD8X/bPzal3GxPUT/nR5WQ==)

**Comment by Dinuz** [comment]
I cannot figure out how even modify the css to get rounded corners

**Comment by vduggen** [comment]
> I cannot figure out how even modify the css to get rounded corners

It's strange because in previous versions of vuetify it had this, but you can do it with css, just inspect and find the right element to apply the border-radius

PS: I'm Brazilian and I'm using google translator, sorry if something wasn't translated correctly

**Comment by santiagoaloi** [comment]
duplicate #16722
