### ISSUE TITLE
Form validation doesn't work with tabs

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#1639]
### Steps to reproduce
1. Create form with tabs in it.
2. Add field with rules defined

### Versions
vuetify: 0.15.2
vue: 2.4.2

### What is expected ?
After calling validate() function on form reference, value of form should be false if rules are broken.

### What is actually happening ?
Value of form is true, even if there are broken rules.

### Reproduction Link
https://codepen.io/anon/pen/MvMzKY

**Comment by nekosaur** [comment]
This was fixed in PR https://github.com/vuetifyjs/vuetify/pull/1581. Will be available next release

**Comment by mirhat** [comment]
Thank you on reply. Do you know when will be next release?
