### ISSUE TITLE
[Bug Report][3.1.0] V-Select slot multiple select not working

### ISSUE THREAD

**Issue by GoldraK** [vuetifyjs/vuetify#16396]
### Environment
**Vuetify Version:** 3.1.0
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Ubuntu undefined

### Steps to reproduce
Open the dialog
click some Option or click in icon

### Expected Behavior
If click on icon write a console.log
if click in item select for multiple select

### Actual Behavior
none of the events work.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVM2O2jAQfhXXhwUkkhS2vaSA6LHn1Z4Ih+AMixv/RLbDtkJ5947jwBIg20iRPDPffPPjGW9O9GdVxccaaEoXDmQlcgerTBGyOEZ5VbXHVpA5V53UyhYEMHdWXH+I1QWIZUZrC+Yl4OgjpMh3Le7V1rnh2j5GpRwTsx3dAEbWwvFKwL3tkvPtdykXE7ZCuzYMRjkRfyBNRgdcsXjBrYtaGPYIVBFxphX6yoJHOWO6Vi5i3DBMiJI1E5yVaR9pD/r9l9rr1xcwY88UH3NRw2QwahvXOw+ZfeP5vtd18mW5JKoWgjw9kQ91zBUTdQG2H3iYmGmhDTJXhsvc/P0UKnLr70qa6HkYN1gj3iS2kB2AlTv9B4fOlFAMNiQJHflfx7AxICzc5Lbqh9qJXJWRrp3gCj6oT2EcQpNilUsgTTMwF+hzGYyHOS2S3ordu4elOi8dKi5b54Wwjz0SFC0zvHLEgqu9mctKG0dOxMCeNGRvtCQjXPCRB2NF1l1NAll62HiznfgY13aLps3Ja3mRktFsNPVnXz9KDhA1Q8ZmeoaM5veIuUdsfdwz8/XUY4CxjzQhyxVpaTxGC4iFfguWH+iPv685VIn10SkNJWJvqvi31QqfrtY96wz4RKSB0OuwdC9n9OBcZdMkqVVVvsVMy2SNtsTgrnIJUaHl+jmex9++JwVe4rU+BiujndHvmBNGzGhbaUfu+B4X4nGAzoy8s/hroO1UnvKOKkH+I5jI4DsBBsyned9ge7nf2O7y9zFxiBvsJU57aW/ayGzbwg1eXUObKQ3UCG7roNt/CFjRVA==)

**Comment by MatthewAry** [comment]
It might be possible for vuetify to add to the scoped slot a property for the selection state of the item and a method to toggle its selection state.
