### ISSUE TITLE
[Bug Report][3.0.7] ARIA input fields must have an accessible name

### ISSUE THREAD

**Issue by marjev** [vuetifyjs/vuetify#16397]
### Environment
**Vuetify Version:** 3.0.7
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use Axe or a similar static page analyzer to perceive the issue.

1. Set a label for one of the following form input elements: Slider, Text area, or Text fields.
2. Axe should report that the div element with the role (slider or textbox) misses an accessible name - depending on the input element used in step 1.

### Expected Behavior
The label (provided string or the label element) should be used as a source of aria-label (string) or aria-labelledby (element). If the label element is used for this purpose, it would be good to ensure that it has a unique ID to ensure that this fix works in case more than one input has been added to the same page.

### Actual Behavior
`ARIA input fields must have an accessible name` issue is reported and the div with role attribute isn't labeled. 

### Reproduction Link
[https://codepen.io/marjev/pen/eYjNrKo](https://codepen.io/marjev/pen/eYjNrKo)

**Comment by sniperadmin** [comment]
This is for `v-select`
![image](https://github.com/vuetifyjs/vuetify/assets/24525973/26a48645-dbc1-4382-97a7-60293d9ba390)

Noticed that the wrapper `.v-field` is missing `aria-label` or `aria-labelledby`
