### ISSUE TITLE
Cross Browser Compaibility ?

### ISSUE THREAD

**Issue by LiTiang** [vuetifyjs/vuetify#164]
I dont found any info about support cross Browser compability of **_vuetify_** ?

How about now ? IE9, Android 4+, or ? 

??????

**Comment by johnleider** [comment]
Latest version of all browsers. No ie9 or stock android browsers.

**Comment by bboydflo** [comment]
@johnleider Thanks for this library. I think it should be clearly specified which browsers are supported. Is one of the first things I am looking when I check a new css framework.

**Comment by mfferreira** [comment]
@bboydflo Would you like to help us determine that table?

**Comment by bboydflo** [comment]
@mfferreira I could try to help.

**Comment by mfferreira** [comment]
@bboydflo awesome. You can share any results on this thread.
