### ISSUE TITLE
[Bug Report][3.1.0] Select and autocomplete TAB or SHIFT+TAB behavior

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#16405]
### Environment
**Vuetify Version:** 3.1.0
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Take the focus on the select input with TAB key. The input is now focused. Use the arrow key to open the menu. Use the TAB key again.

### Expected Behavior
On the second TAB key press, the next input should be focused.

### Actual Behavior
On the second TAB key press, the next item is focused.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctOwzAQ/BXLl4DUxDwvpVQFCU7cODY9pMkGTBPbsjelUOXfWTtpG1rBKZnZ8ex4PN/yB2OSdQN8zCcItakyhGmqGJus48yY8BtAnUnVo4AdVJAjq7IlVPcpf+2gVKbBlLOxJDNHfPgSIYZnETYYlxKqYn/+aZPRctgZTCdiKNvFIHKQg5xKrRFsj1MkZomHmCnubJ+Djr1ItdrnILOD2KOBmYfd9SdiUAtBl1tpkDnAxo9lbbRFtmUWStay0uqaRdRn5MW5Vo468RWwe684m0eUJBqx6DGz3ec7Wpzf+TWdMVnyEe9c6a4m+XBa0eNsfSqqMwyo0DELjOdom8cpf0c0bixEo8zqLcl1LWY0E7ZRKGuIC13PrpOr5OZWFNLhkE/A1fHS6k8HljamfDQwR1l+/bWgH5PvZXLR2faUtzyxEuS/BhtbUAVYsP/mPtL+yn40O8nvd7apaqnLit7cHdWYu1DhfOEl7Yh31iQO9+CLH4qWA5o=)

### Other comments
TAB key should not be handle by the v-menu when the menu is used inside a input component, as this is not the default browser behavior.
This may leads to strange behavior, because the menu is by default detached (on thus, the focus will be at the end of the document).

**Comment by KaelWD** [comment]
Fixed in #17257
