### ISSUE TITLE
[Bug Report][3.1.0] Search in VAutocomplete does not work

### ISSUE THREAD

**Issue by Bjornar97** [vuetifyjs/vuetify#16403]
### Environment
**Vuetify Version:** 3.1.0
**Last working version:** 3.0.7
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use the <VAutocomplete> component. Have an array of objects with an id and a name / title and put in :items. 

### Expected Behavior
The list gets filtered, and the phrase I typed gets highlighted in the results.

### Actual Behavior
It says "No data available", even though there are items that match.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UstOwzAQ/BXLF0BqYp5CCgFRceSCBOLS9BCSLTXED9mbIlT131nbqWhTRC7x7oxnZ0eerfnU2nzVAy94iaBsVyPcVZqxcpXV1sZjLFQt9VDFzuu0R9MYugEIv/3wdfUbdLcVfyC01t8V34dpRgNL07XgiPQMtWuWbGEc80YBLqV+H9+g6aaNkh46aBDaMaOQZN4TIf7HaGhmq7rrITAOLkcYJXYB1rWCXcJdKfZW3SYidiIJRQqrFDshUukbJy0yD9gHWCprHLI1c7BgG7ZwRrEjSv8okBujfaCmDdltIB2f3IQBWzBuNyCzAKyTG9kWZ5N0DP4LVvEX8HiWFtlE6JfKzkfcqUaSB82eHocblZ6f3NDYUqQNyDuf8GSf9rb5hzea3kwUpUwjQLkX2zEVp7VCXfElovWFEL22n+855SjuCROu1ygVZK1R9xf5eX55JVrpcbefg1fZmzNfHhxNrPjgO4qjXNDT+nvAAJPuaX6dZIdWkDyQEqS/Apc50PQowf3re8Td8z7CDvwP2W4oy07qTz+KsfExwtk8UDYTnqSJHPfg8x/oWCn4)

### Other comments
Also, I didnt realize I updated to 3.1, that seems to be a beta? I just ran npm update, and had "^3.0.0" as version number for vuetify.

**Comment by paul-thebaud** [comment]
Hello,
Looks like this is due to the default value used as the `FilterKey`.
If I define explicit filter keys such as `:filter-keys="[(post) => post.title]"`, it will work.

By the way, the typing for `FilterKey` prop looks wrong (`string | string[]` even if it accept function like `itemTitle`, `itemValue`, etc.).

**Comment by yuwu9145** [comment]
> Hello, Looks like this is due to the default value used as the `FilterKey`. If I define explicit filter keys such as `:filter-keys="[(post) => post.title]"`, it will work.
> 
> By the way, the typing for `FilterKey` prop looks wrong (`string | string[]` even if it accept function like `itemTitle`, `itemValue`, etc.).

Exactly, there was a regression that breaks default `FilterKeys`

**Comment by johnleider** [comment]
The team had a lengthy discussion about this recently. Our conclusion was:

* FilterKeys should also take a function like SelectItemKey
* `item-title` and `item-value` should be used as a shorthand for the `filter-keys` prop

I think the best course of action would be to alter the props object being passed to `useFilter` and generate a custom `filter-keys` array. Something akin to:

![image](https://user-images.githubusercontent.com/9064066/212960190-56ff8a0d-1345-4840-b05e-9baf011d2f4e.png)

but with the consideration of functions, duplicates, etc.

**Comment by yuwu9145** [comment]
> The team had a lengthy discussion about this recently. Our conclusion was:
> 
> 
> 
> * FilterKeys should also take a function like SelectItemKey
> 
> * `item-title` and `item-value` should be used as a shorthand for the `filter-keys` prop
> 
> 
> 
> I think the best course of action would be to alter the props object being passed to `useFilter` and generate a custom `filter-keys` array. Something akin to:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9064066/212960190-56ff8a0d-1345-4840-b05e-9baf011d2f4e.png)
> 
> 
> 
> but with the consideration of functions, duplicates, etc.

That makes sense, I will make a time to implement it either today or tomorrow
