### ISSUE TITLE
[Bug Report][2.3.10] v-checkbox weird behavior when passing object as values inside a for loop

### ISSUE THREAD

**Issue by Nehasoni988** [vuetifyjs/vuetify#16402]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 94.0.4606.61
**OS:** Linux x86_64

### Steps to reproduce
**The creation part-**

Create some checkboxes using a v-for loop and put all checkboxes inside a dialog component.

**The Procedure-**

1. Open the dialog and select the checkboxes.
2. Before closing the dialog, empty the `v-model` variable, so no items will be selected on opening the dialog again.

**The issue-**

When opening the dialog a second time, all checkboxes are already selected even though the `v-model` variable is set to an empty array `[]`. Then if try to unselect any item, all are unselecting together and after that only one at a time is selectable.

If use `:value="item.id"`, the checkboxes are working fine. But the need is to return the whole item object so have to use `:value="item"`.

### Expected Behavior
1. An object should be passed as values
2. After opening the dialog for the second time, the unexpected behavior (All checkboxes are selected together and only one is selectable after) should not occur.

### Actual Behavior
1. After opening the dialog for the second time, all checkboxes are marked selected even if their v-model variable is an empty array.
2. The selection is no more normal ((All checkboxes are selected together and only one is selectable after).

### Reproduction Link
[https://codesandbox.io/s/vuetify-2-forked-gdnn8u?file=/src/App.vue](https://codesandbox.io/s/vuetify-2-forked-gdnn8u?file=/src/App.vue)

**Comment by KaelWD** [comment]
This seems to be related to #16360 as adding `multiple` also fixes it.
