### ISSUE TITLE
[Bug Report][2.6.13] VImg src cannot resolve path when using Vite in 2.7

### ISSUE THREAD

**Issue by VividLemon** [vuetifyjs/vuetify#16407]
### Environment
**Vuetify Version:** 2.6.13
**Vue Version:** 2.7.14
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Create a vue 2.7 app with Vite
attempt to VImg src attr without require()

### Expected Behavior
For it to resolve the img without extra necessities

### Actual Behavior
Cannot get img

### Reproduction Link
[https://github.com/VividLemon/vuetify-issue](https://github.com/VividLemon/vuetify-issue)

### Other comments
I don't believe this would be an issue with an external image. This is only images served by the app itself.

**Comment by KaelWD** [comment]
https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#asset-url-handling

**Comment by VividLemon** [comment]
> https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#asset-url-handling

ty
