### ISSUE TITLE
[Feature Request] Loading prop on VDataTable

### ISSUE THREAD

**Issue by Vuexec** [vuetifyjs/vuetify#16404]
### Problem to solve
The lack of the loading prop on VDataTable

### Proposed solution
It is already on VDataTableServer, but the same outcome can be made with VDataTable with this axios request. The one problem is that loading is missing!

const getData = async () => {
    loading.value = true;
    const axiosResponse = await axios.request({
        method: 'get',
        url: 'https://vuexec.com/requestInfo.json'
    });
    activityData.value = axiosResponse.data;
    loading.value = false;
}

Albert considered it in a subscriber help request on the Discord and said he might add it in the future, but I thought I would make this request just because.

**Comment by webdevnerdstuff** [comment]
This was recently deployed in v3.2.3 or v3.2.4 (don't remember which).

https://github.com/vuetifyjs/vuetify/pull/16829
https://github.com/vuetifyjs/vuetify/commit/0a4b9fd613e368da44b50f2b7a2b27ffa5bd6f01
