### ISSUE TITLE
[Bug Report][3.1.0] Animations broken on Chrome < 84

### ISSUE THREAD

**Issue by alifeee** [vuetifyjs/vuetify#16406]
### Environment
**Vuetify Version:** 3.1.0
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Open Vuetify (or reproduction link) on Chrome < v84 ([Chrome versions](https://vikyd.github.io/download-chromium-history-version/#/))
Console displays "partial keyframes are not supported".

### Expected Behavior
Works as normal

### Actual Behavior
Crashes app

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UU1P6zAQ/Cv7fOl7UhM/vi5VQEVcuHHkgDmEZFNM/SXbKaCq/521k0IoKjfvzHhnPH7Ysmvnyk2PbMGqiNqpOuKVMADVpqidy8c86FqaccpzxLdYdBJVC0TaFtWlYDqsBAM+1T1FA8tGyWZNfCtrZVdwCdH3KNjVnUMDA1jxrJ1eHdVf6weA7u1FWdbUvoVG1SGQxNXFxTeBiEdDdLUKKcWNsgGPxCAHQpLFVzICBvG+HQI+60nDUFzFJ4XSGBovXYSAsU+01M76CFvw2MEOOm81zOgnZkncWBMiUJ0Uk/i/s1tUysK99ar9M/u3F3w+JWnyc4iq+OBEHmzOBhvK58qXYA398zbFFCMRBFtARhJG9mkW7DlGFxac98atV2VjNV8Sx31votRYtFYvz8rT8vyCtzLEKV5i0MWTt68BPTkKNp8sj7J7P2Yw0rT3pPw/rB2htPLHKk77N+gLj6ZFj/7X3Afab9kPuB/5k+dOmB11qaRZh4Mam5ArfHhMkt2cDatJnN/BHj8AxN0Z1w==)

### Other comments
Fix: 
  in node_modules\vuetify\lib\components\transitions\dialog-transition.mjs
  &
  node_modules\vuetify\lib\components\VField\VField.mjs

Add explicit keyframes to calls of `animate()`, function.
i.e., specifying `opacity` and `translate` for each keyframe.

**Comment by alifeee** [comment]
Here is the diff that solved my problem (via patch-package):

```diff
diff --git a/node_modules/vuetify/lib/components/VField/VField.mjs b/node_modules/vuetify/lib/components/VField/VField.mjs
index 2810ad7..8a7d55a 100644
--- a/node_modules/vuetify/lib/components/VField/VField.mjs
+++ b/node_modules/vuetify/lib/components/VField/VField.mjs
@@ -113,11 +113,15 @@ export const VField = genericComponent()({
         const color = targetStyle.getPropertyValue('color');
         el.style.visibility = 'visible';
         targetEl.style.visibility = 'hidden';
-        animate(el, {
+        animate(el, [{
+          transform: `translate(0px, 0px) scale(1)`,
+          color,
+          ...width
+        },{
           transform: `translate(${x}px, ${y}px) scale(${scale})`,
           color,
           ...width
-        }, {
+        }], {
           duration,
           easing: standardEasing,
           direction: val ? 'normal' : 'reverse'
diff --git a/node_modules/vuetify/lib/components/transitions/dialog-transition.mjs b/node_modules/vuetify/lib/components/transitions/dialog-transition.mjs
index fb29634..e67394c 100644
--- a/node_modules/vuetify/lib/components/transitions/dialog-transition.mjs
+++ b/node_modules/vuetify/lib/components/transitions/dialog-transition.mjs
@@ -31,7 +31,8 @@ export const VDialogTransition = defineComponent({
           transform: `translate(${x}px, ${y}px) scale(${sx}, ${sy})`,
           opacity: 0
         }, {
-          transform: ''
+          transform: 'translate(0px, 0px) scale(1, 1)',
+          opacity: 1,
         }], {
           duration: 225 * speed,
           easing: deceleratedEasing
@@ -68,7 +69,8 @@ export const VDialogTransition = defineComponent({
           speed
         } = getDimensions(props.target, el);
         const animation = animate(el, [{
-          transform: ''
+          transform: 'translate(0px, 0px) scale(1, 1)',
+          opacity: 1
         }, {
           transform: `translate(${x}px, ${y}px) scale(${sx}, ${sy})`,
           opacity: 0
@@ -78,7 +80,9 @@ export const VDialogTransition = defineComponent({
         });
         animation.finished.then(() => done());
         (_getChildren2 = getChildren(el)) == null ? void 0 : _getChildren2.forEach(el => {
-          animate(el, [{}, {
+          animate(el, [{
+            opacity: 1
+          }, {
             opacity: 0,
             offset: 0.2
           }, {
```

**Comment by funkyvisions** [comment]
Thanks for the patch.  That seems to resolve issues on Android 9 for me (we are a Capacitor app).  But, I'm also having trouble with expand-transition.mjs.  It seems like onBeforeEnter isn't called and so el._initialStyle is undefined and blows up onEnter and resetStyles.

**Comment by KaelWD** [comment]
Removing implicit keyframes causes #16394

We don't have plans to support browsers that old, you can try [the polyfill](https://github.com/web-animations/web-animations-js) and see if that fixes implicit keyframes for you.
