### ISSUE TITLE
[Bug Report][3.1.1] Select and autocomplete menu always take full height

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#16416]
### Environment
**Vuetify Version:** 3.1.1
**Last working version:** 2.6.14
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a select with more items than the current window height could display when opening the menu.

### Expected Behavior
Height of the menu should be automatically limited to the max available space (e.g. highest space between the control and the window top or bottom).

### Actual Behavior
Height of the menu is always 100% of the window height.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9VttuGzcQ/ZWBUCAxsF6ll7w4dhAjQYEATdGiaF+ioKF2R9I0XJLmRXVg6N97hrsr+YLGL1oO53rmzNAf7xbXIbT7wouLxWXmIViT+fXKEV3uz00I9bMeBiNuOtVz512GiONRCPGsP/794iMPJCGVgXpvfaQkmczAuSGYJ+4y5xLJ9BIkdeK2xFZyS78Wa42qbAs3BEO4MR2Z0mU4CT4Vjnoh2wI9yFTclZhKIldc15AMgWMvnGkwllMxvaENnCcq0RmC3PfiW/q9SLopPKZzU0zG1zD43pOTZKlkYmhA0NJ7RyFyFhQD7V4GdhnffNuQIUTuUISG28L/4BE0C1NiWP7G1kKZa6TjVW+CrJFwL2ZAwriPPfwd7wchawCKwLt6+UvF62KhY6A84RqiDKhKHG0AT3XoYwdTYIVvFFpsjtJxmnEDUGux8ArADL+it9EAlaok0BpMSop9RQGlWUHWmaIouAad23DZCoByst619DMKZ0JqYz5TYyuSzp8Qk74hpRf6BPSjQZOBZxbXSV9cRoVAcos4e29LDrCe4GnpWjMwqLTYvTgT0WFlhzpptD6YotfkEBSJjN3Cb0tvLUohEzKwpwwos1DynXj0AZwDfUCbSh9YQkW9IHugY5B7ytE0VYYkOWSfaKc9N+yR1DvvuEOUiZwzxih/ZOEo3rNtAOitDCqqbD1RbhvNXkDLib5Tw8bWzmQIOwMAI6zGkZjnhzA2GJn7RNRAM9MRF4qK+exgovs7xH5KiF62YHuSYa7rGN9jWKCgxkpRjCdPtB/hnpLeSzbcrpwO/4QMGFNynAe/oRuNPJNpnPI/SgqM/FNiuOuggi5vQHi0vZnbOhWq5g3toB45ojbVnclXXSfQhZ3mOE4gFlmnFMEMoRWMcB9MAYmPOeBqhKmaA8i9sdgPysup+IfLA7DDGEvoW7M3A2j9Gl3VtDycgnmlr5lVJmAh7EzCTgByj5Hui2BAMCY5Kztb+lP7iJZZM3Q+KiKW0chxaDFjtQ3Hj3lhqAOMSNESJ7Q/GO7A3lrDCBHfHkFBiHly5nV0ok7dmw/2z5GGM4NM7DBw1+zYOM1GnSh+oJWcNtqxWN0MCpOqPeRB8Dqt8lBY2wQ+HElRW4b9eHpOJtrMpKv5jHycXqalPk2rfHy+TMkeSy5YRjutWbO9Wi2u7wvFhZJXC7oQLK6E2/oLwfL0DC6fvoMqO76Vehhf0cvlvdcVx9RFCVpVLnqN9wotozuKvKEDbaIf6Bme5WeqrCsVNNDwdKUaz69jNF9b1Xp+h6dlm3cX9PLFoaHnf2vver49o6vX9Pk9bOi7uyo5fD47e6WJjKERdNEsxrhIOLT/JO/wX8Cd5o1i6wXKvaAqURny0fNqscs5pIvlsrjwZdsCseUb3C0jNjm20Xnvhzc/tj+0P71cooH5vrzlNJyvo/83cUTE1aK55zzL5uv/BZiu4ff79sXodhKpyyeulvC/53gewSEQNH4z70e6D3J/dPckf415WLkDsLTivqRHMHapQvjxk6ocmsXoGsq1jsWn/wDrWV7o)

### Other comments
This is causing the autocomplete to be useless when having many items, because the user wont be able to see what he is typing in the input's search, as its hidden behind the menu.

**Comment by paul-thebaud** [comment]
Hi, for people how are searching an interesting workarround, I'm currently limiting the menu height dynamically using a window resize listener. Here is my vuetify plugin creation file:

```ts
import { createVuetify } from 'vuetify';
import 'vuetify/styles';

// FIXME Vuetify Issue: https://github.com/vuetifyjs/vuetify/issues/16416
const computeSelectionControlMaxHeight = () => `${Math.ceil(window.innerHeight / 3)}px`;
const selectionControlMenuProps = { maxHeight: computeSelectionControlMaxHeight() };
window.addEventListener('resize', () => {
  selectionControlMenuProps.maxHeight = computeSelectionControlMaxHeight();
});

export default createVuetify({
  defaults: {
    VSelect: { menuProps: selectionControlMenuProps },
    VAutocomplete: { menuProps: selectionControlMenuProps },
  },
});
```

With this, each time the window is resized, the select and autocomplete menu max height are getting updated to 1/3 of the window height. Each time a menu opens, it will use those `menuProps`.

**Comment by qxygene** [comment]
`:menu-props="{ maxHeight: '250' }"`
