### ISSUE TITLE
[Bug Report][3.1.1] Expansion panels not opened at load

### ISSUE THREAD

**Issue by olinox14** [vuetifyjs/vuetify#16427]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create a `v-expansion-panels` with the `multiple` keyword and a `v-model` named `panels`
Add three `v-expansion-panel` inside of it
Using the composition api, setup a `panels` variable like this : 

    const panels = ref([0, 1, 2])

### Expected Behavior
The three expansion panels should be opened when the page is loaded

### Actual Behavior
Only the first expansion panel is opened, other are still closed

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-dxerve?file=package-lock.json](https://stackblitz.com/edit/nuxt-starter-dxerve?file=package-lock.json)

**Comment by Alucard17** [comment]
Hii @olinox14 it seems this issue is only with server-side rendering i.e. Nuxt. I have tried a similar example in codepen it works as expected
https://codepen.io/alucard17-the-animator/pen/KKBqKLX?editors=0010

Also found the following warnings in your reproduction link
```
chunk-QO6ZHO7P.js?v=aa4c7b53:1277 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: <!---->  
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> onEnter=fn onAfterEnter=fn<resetStyles>  ... > 
  at <Transition name="expand-transition" onBeforeEnter=fn<onBeforeEnter> onEnter=fn<onEnter>  ... > 
  at <ExpandTransition onAfterLeave=fn<onAfterLeave> > 
  at <VExpansionPanelText> 
  at <VExpansionPanel> 
  at <VExpansionPanels multiple="" modelValue= (3) [0, 1, 2] onUpdate:modelValue=fn > 
  at <VMain> 
  at <VApp> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by olinox14** [comment]
@Alucard17 You're right, the bug only occurs when rendered server-side, since the panels open correctly as soon as HMR kicks in, when I edit the code in stackblitz for example.
I just tried a workaround using onMounted and this works well: <https://stackblitz.com/edit/nuxt-starter-ezvhv2?file=app.vue>

**Comment by awacode21** [comment]
> Hii @olinox14 it seems this issue is only with server-side rendering i.e. Nuxt. I have tried a similar example in codepen it works as expected https://codepen.io/alucard17-the-animator/pen/KKBqKLX?editors=0010
> 
> Also found the following warnings in your reproduction link
> 
> ```
> chunk-QO6ZHO7P.js?v=aa4c7b53:1277 [Vue warn]: Hydration node mismatch:
> - Client vnode: div 
> - Server rendered DOM:   
>   at <BaseTransition onBeforeEnter=fn<onBeforeEnter> onEnter=fn onAfterEnter=fn<resetStyles>  ... > 
>   at <Transition name="expand-transition" onBeforeEnter=fn<onBeforeEnter> onEnter=fn<onEnter>  ... > 
>   at <ExpandTransition onAfterLeave=fn<onAfterLeave> > 
>   at <VExpansionPanelText> 
>   at <VExpansionPanel> 
>   at <VExpansionPanels multiple="" modelValue= (3) [0, 1, 2] onUpdate:modelValue=fn > 
>   at <VMain> 
>   at <VApp> 
>   at <App key=1 > 
>   at <NuxtRoot>
> ```

i can confirm that it is somehow related with SSR. Following is also a Nuxt project, but with SSR put to false, and there it is working: https://stackblitz.com/edit/nuxt-starter-dmei2d?file=nuxt.config.ts when you change SSR to true in nuxt.config.ts it stops working and behaves as described in the bug.

**Comment by awacode21** [comment]
> @Alucard17 You're right, the bug only occurs when rendered server-side, since the panels open correctly as soon as HMR kicks in, when I edit the code in stackblitz for example. I just tried a workaround using onMounted and this works well: https://stackblitz.com/edit/nuxt-starter-ezvhv2?file=app.vue

Works around the issue of not being opened. But you see the open animation instead of having it opened right from the start which ends in a big reflow
