### ISSUE TITLE
[Documentation] Data Table Component Page URL is incorrect at Data Table API Page.

### ISSUE THREAD

**Issue by Nehasoni988** [vuetifyjs/vuetify#16424]
### Environment

**Browsers:** Chrome 94.0.4606.61
**OS:** Linux x86_64

### Steps to reproduce
The page of data table API has a section named "Component Pages" which has a reference URL (the title of URL is Data Tables) that redirects to an incorrect page which returns "404 not found".

### Expected Behavior
The path should be this-
   https://next.vuetifyjs.com/en/components/data-tables/basics/

### Actual Behavior
The current path is this which returns 404- https://next.vuetifyjs.com/en/components/data-tables/

### Reproduction Link
[https://next.vuetifyjs.com/en/api/v-data-table/](https://next.vuetifyjs.com/en/api/v-data-table/)

### Other comments
This is just a small issue but if the page URL is incorrect, a manual search in the doc is time taking.

**Comment by MajesticPotatoe** [comment]
No longer an issue
