### ISSUE TITLE
[Bug Report][3.1.1] v-table does not works when I downloaded vuetify&vue with CDN on html file.

### ISSUE THREAD

**Issue by Eeap** [vuetifyjs/vuetify#16434]
### Environment
**Vuetify Version:** 3.1.1
**Last working version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
v-table does not works when I downloaded vuetify&vue with CDN on html file. So I can't use v-for in v-table too. I think that v-table is not working when thead or tbody tag were in v-table tag not list tag.

### Expected Behavior
table expression

### Actual Behavior
no table. just text

### Reproduction Link
[https://github.com/Eeap/vuejs-study/blob/main/index.html](https://github.com/Eeap/vuejs-study/blob/main/index.html)

**Comment by KaelWD** [comment]
- labs components are alpha and are only available in vuetify-labs.js
- you can't use tbody/tr/td in DOM templates, this is a browser limitation
