### ISSUE TITLE
[Bug Report][3.1.1] VSnackbar gets hidden behind bottom toolbar in mobile browsers (tested chrome/safari on IOS)

### ISSUE THREAD

**Issue by eliezerp3** [vuetifyjs/vuetify#16432]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-snackbar and open it on a website from the chrome/safari on IOS (didn't try on android). The snackbar won't appear as it appears behind the bottom toolbar (as you can see if you make the height of the page larger and scroll down so the toolbar disappears). You can also open the reproduction link provided with full screen preview in mobile to see.

### Expected Behavior
Snackbar should appear above the toolbar on mobile browsers

### Actual Behavior
Snackbar appears behind the toolbar making it invisible on mobile browsers

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kMtuwjAQRX9l5A2tBIn62iCo6K5ds8QsEmdoXOKHbAdUIf69YyegNKhVNpmZO+d67ubE3qzNDi2yOVsEVLYpAr5yDbA4zApr028qVCF1X6W6DBpWopFiv+TMl7CE4FrkDIRpjKOew4qz6wasa3OEtS7EvizclZMn0JDrewmQpamwSfQE4qH73mUGHxMFBVy1tawq1FBiLXUFonZGIQRjmpHXZeFyFrWud8Wiu3iRD5Kg0gsnbQCPoY1jqaxxAU7gcAdn2JEZTCjCSRQLoz1JYx40vruPtG6fNtmUdcvkarMvbzTFformvB94zuaQOrFH0FhzVodg/TzPW233n5kwKl/RLHetDlLhrDJq9ZQ9Zs8veSV9GPYz9GpWOnP06MiRs+kAHuTu+y+Dfkzch+yhw/atiLxB5cQ/oJs51BU6dP++e6T99fbR7Ob90fPM9ZmybKTe+1GMwqcIN9soOU9ZhyZxuoNtfwDFzPgt)

**Comment by eliezerp3** [comment]
Fixed this by adding 
```
.v-snackbar {
    display: block !important;
    position: fixed !important;
    height: 100vh !important;
    width: 100vw !important;
    max-height: 100% !important;
    overflow-x: hidden !important;
    top: 0 !important;
    bottom: 0 !important;
    left: 0 !important;
    right: 0 !important;
}
```
to custom global css file.

**Comment by akuu666** [comment]
Experiencing the same issue

**Comment by meahis** [comment]
I have the same problem. I fixed it by adding these lines to the global styles:
```
div.v-snackbar:not(.v-snackbar--absolute) {
    height: 100% !important;
}
```
