### ISSUE TITLE
[Bug Report][3.1.1] The prop cols isn't work in VCol when using custom thresholds,despite having correctly set the sass variable $grid-breakpoints

### ISSUE THREAD

**Issue by dang0705** [vuetifyjs/vuetify#16433]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 7

### Steps to reproduce
1. custom the display.thresholds property before createVuetify
2. custom the sass variable $grid-breakpoints(The setting method has been verified to be correct, and I also set the variable $font-size-root to be valid)

### Expected Behavior
cols property work correctly when using custom  thresholds

### Actual Behavior
it's using default thresholds settings even i configure the js and sass correctly

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVU8Fu2zAM/RVCl2xAbCeZuw2GW3T/MOxS9eDZTOzVkgWJTlME/vdRsuc5Kdp7c4jFx6cn6ol8OItjj9TsX+I/TmSiUaazBGcoLRaEv8YcDLC3nYLVxF1JLTWeArXstCOYEnB7ufHTWWoAqlFhxqIV7ou+pZ9jvGqbQ00rGNaeVDXOtMVLFnbwj2qLru7ays0QwMllsFnDHDuVQbq7WSCqyuDb1+8LpD1ksN3s0nDKqNIykqabCRn8h/+kHj5LLdbihzExX4jtyAkVV0V45zn5MSqMCcsQqKLRUxRitoIYQjuDAbbdM+guOvREaN0iN21qoWwL526loOeI8ERRiZqpUrC5rce3O16rilepFHeEjvIk7PwQYh5hD/47FRiXVnlsttMHo9F5sngADl1pG0PgkHqfnrvV4n7Zo9yfeTJymcUvOhL5BMNt3ml+2dBTcko4Kbg9x0qkHwgfS1ETGZclSa/N0yEuO5Xccy6xvaZGYVR16v5LvIvTm4Sbl5Z4jE5Fv/nSDi2fKMXUakHcD8ZbB0xp1t3G21H233yy5CuphPWPaCOLukLrH+aduq+4F7Vf5V7VP43IwF62jX5yVzaWLlj48Ogpw1qM0kwO9xCPfwH+AWab)

**Comment by KagamiMi** [comment]
@dang0705 Can I ask what turned out to be an issue, what fixed it? I am having the same problem

**Comment by dang0705** [comment]
> @dang0705 Can I ask what turned out to be an issue, what fixed it? I am having the same problem

In my case ,  I use the vite plugin 'vite-plugin-vuetify' to handle the vuetify sass variable

**Comment by qxygene** [comment]
any fix yet? this is still broken. (thresholds settings is not updating actual sass)
