### ISSUE TITLE
[Documentation] [v-window] Touch default is incorrect

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#16438]
### Environment

**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Use a touch enabled device
2. Swipe example 1 (it has touch enabled)
3. Swipe example 2 (it has touch disabled)

### Expected Behavior
Expect default to be false, disabled per docs.

### Actual Behavior
Default has touch enabled when default is undefined

### Reproduction Link

[https://play.vuetifyjs.com/#...]
https://play.vuetifyjs.com/#eNrNU02P0zAQ/SsjX7JITawWuFRptUiLBGe4bfbgJpOt2fhDttMKVf3vjJ3QDSkFjtzy5s28mffkPJ7YB2uLQ49szcqAynYi4LbSAOUhF9amzwSUkHpECQex80Bl02C3IXDhfrJwEF2Pm2yZbZclT6WbPatsu5r3jNhfChdiv5oIPWAr+i7AJ+Hhq+nrPXzUYtdhA3fNSEkPJaptr6kgNTYlJ/Tmdc9Ej846St2Y421rA59LSmti8XOEyeeE/+sg+U6DyfzvBl/rVzHMcoAvGILUzxRCctuKzmNyOonmQfqUzb97h3WIk5ss6WX/YxSRuLzOCIZ3W/LJeyboaydtAI+hj7RU1rgAJ3DYwhlaZxRk9CNkla6N9gGi+U1k7+g2ei0lHxRoli3YME57bfHNG02/zymur0bCV2wNqRJrJBtxxfYhWL/mvNf25bmojeL3xHHX6yAV5o1R92+LVfHuPW+kD9N6gV7lO2eOHh1trNhiIh5k+/3WgpEm3WWxHGTHUpS8kuKkf0CXO6S/xaH7492z3l9un3FX98ed50qfKctO6hc/i7H2KcLHp9hyXrBBmpqTD/b0A6Yves0=

### Other comments
According to docs, the default is false.  But the default is really undefined.  The code does not check for a falsey value, and treats undefined as true.

So the actual default is undefined, with the behavior of true.

There are two issues here.  The docs generating false instead of undefined, and undefined being treated as true.

The old default in 2.0. was true.

This is where the default is defined
<img width="460" alt="Screenshot 2023-01-13 at 1 43 00 PM" src="https://user-images.githubusercontent.com/819940/212398103-a61a7bb5-7d70-4218-a5aa-205ef080d5b8.png">

This is where false instead of falsey is calcuated 
<img width="350" alt="Screenshot 2023-01-13 at 1 43 20 PM" src="https://user-images.githubusercontent.com/819940/212398182-3a8659b7-f056-4c86-8937-62c87409c926.png">

This is the generated docs

<img width="866" alt="Screenshot 2023-01-13 at 1 43 54 PM" src="https://user-images.githubusercontent.com/819940/212398296-4d62ad16-f130-41b7-9974-10330afb5474.png">

**Comment by sk-tjdownes** [comment]
To add to this, the description here says `Provide a custom left and right function when swiped left or right.`. However, run-time warnings are thrown when you attempt to use a function:

```
<v-window :touch="onWindowTouched">
</v-window>

const onWindowTouched = (evt) => {
  console.log('window touched', evt)
  return false
}
```

![image](https://github.com/vuetifyjs/vuetify/assets/132268438/7d2ba271-eeec-41c3-bb16-8cc0f91e095f)

Suggest this is part of the same issue, since they can be resolved at the same time.
