### ISSUE TITLE
[Bug Report][3.1.1] h-screen sizing class should be renamed to something better

### ISSUE THREAD

**Issue by lorand-horvath** [vuetifyjs/vuetify#16436]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Windows 7

### Steps to reproduce
In Vuetify 3 the sizing class h-screen was introduced, which applies 100% viewport height (height: 100vh).
I would like to suggest a better name for it, for example h-full or h-viewport or h-100vh

### Expected Behavior
Class should have a better name.

### Actual Behavior
The class refers to screen height semantically, which is not what it does. It actually applies full viewport height, so should be named accordingly. Thanks!

### Reproduction Link
[https://github.com/vuetify](https://github.com/vuetify)

**Comment by santiagoaloi** [comment]
I don't see that happening, the classes are formed following a certain standard.

```
h-auto | height: auto
h-screen | height: 100vh
h-0 | height: 0
h-25 | height: 25%
h-50 | height: 50%
h-75 | height: 75%
h-100 | height: 100%
```

```
w-auto | width: auto
w-0 | width: 0
w-25 | width: 25%
w-50 | width: 50%
w-75 | width: 75%
w-100 | width: 100%
```

**Comment by lorand-horvath** [comment]
@santiagoaloi I don't really understand what you are saying by "following a certain standard", because as I see it, it's not a standard:
height: auto; --> `.h-auto`
height: 50%; --> `.h-50`
height: 0; --> `.h-0`
height: 100vh; --> `.h-screen` (this doesn't follow the rules above)

If we try to make it "standard", it should in fact be renamed to `.h-100vh`

**Comment by santiagoaloi** [comment]
What I mwean with standard is consistency with the way other libraries like bootstrap of tailwind. 
Your suggestions are very appreciated, but I dont see this happening in future releases or fixes.

In addition,  that would imply breaking changes.
