### ISSUE TITLE
[Bug Report][3.1.1] SelectItemKey doesn't support title for item with value = null

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#16442]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-select, add items as objects (with a title and a value) and use null as one of the values.
After that v-select renders empty instead of with the title for the null-value

[Recreation: play.vuetifyjs](https://play.vuetifyjs.com/#eNp9kk1P4zAQhv+K5Ut3pSYW+3HJlhVIIC7cEKe6B5NMisF2LNspQlX+O2M7oaEUbpl5Zt55Z5z1nl5aW+56oBVdBdBWiQD/uSFktSuEtekzBVpIM0Yp9qCgDlOCEKzoGlDnnI6EHpgSD4ncCrPtxRYOjIdK4liPUI3QzzsjLIIMCrDCCP3eygPHNMKdUH2ENU4/dLLJOJs5j0HeacVmu2LoaydtIB5CH7HUtnOB7ImDlgykdZ0mCzzSIhbXnfEBVxrdknOyjuJ7MhmsOL2CVvQqkMPCS8TZYmV6pciwnJrGLKdgivu7XNlKNcuVr0KrDN4nXJutkv6R01NKDRRX10dKKXdK6QacFmYS2vyLatOW+SlxRTzEj+j7J2LGTsBFcrqIfMXyOfGQdEnzLfERbPnkO4P/2T5NGAG+dkVSJubwxjHm9DEE6yvGemOft2XdaXaBjLneBKmhaDp98bv8Vf75yxrpwzxfgtfFg+tePDiciMvOxINsX78aMGLUPSvPsuyYipKfpBjq78AVDkwDDty3vo9qP3g/Yp/8x5kDNwPeUknz7I/OWPt0wvUmlgxLmqWxOO1BN2/d+EFC)

### Expected Behavior
Display the title for the null-value.

### Actual Behavior
Stays empty as no-value is selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kk1P4zAQhv+K5Ut3pSYW+3HJlhVIIC7cEKe6B5NMisF2LNspQlX+O2M7oaEUbpl5Zt55Z5z1nl5aW+56oBVdBdBWiQD/uSFktSuEtekzBVpIM0Yp9qCgDlOCEKzoGlDnnI6EHpgSD4ncCrPtxRYOjIdK4liPUI3QzzsjLIIMCrDCCP3eygPHNMKdUH2ENU4/dLLJOJs5j0HeacVmu2LoaydtIB5CH7HUtnOB7ImDlgykdZ0mCzzSIhbXnfEBVxrdknOyjuJ7MhmsOL2CVvQqkMPCS8TZYmV6pciwnJrGLKdgivu7XNlKNcuVr0KrDN4nXJutkv6R01NKDRRX10dKKXdK6QacFmYS2vyLatOW+SlxRTzEj+j7J2LGTsBFcrqIfMXyOfGQdEnzLfERbPnkO4P/2T5NGAG+dkVSJubwxjHm9DEE6yvGemOft2XdaXaBjLneBKmhaDp98bv8Vf75yxrpwzxfgtfFg+tePDiciMvOxINsX78aMGLUPSvPsuyYipKfpBjq78AVDkwDDty3vo9qP3g/Yp/8x5kDNwPeUknz7I/OWPt0wvUmlgxLmqWxOO1BN2/d+EFC)

**Comment by yuwu9145** [comment]
I am checking on this ...

**Comment by johnleider** [comment]
We've long debated if null is valid. I believe consensus was it's valid in certain cases, but not universally. Can @vuetifyjs/core-team confirm?

**Comment by johnleider** [comment]
We might need to add functionality that allows the user to define a clear value. Then we can assign it to components and allow the user to change if necessary.

**Comment by yuwu9145** [comment]
In V2, we support `undefined` & `null` out-of-the-box. [link](https://codepen.io/yuchaosydney/pen/rNZbeRb)

**Comment by yuwu9145** [comment]
> We've long debated if null is valid. I believe consensus was it's valid in certain cases, but not universally. Can @vuetifyjs/core-team confirm?

I agree with `null/undefined` should be used as "no value" by default across the entire framework, and I reckon we could conclude "these certain exceptional cases" are when "users have a chance to customize VALUES to be null or undefined".

From top of my head, these senarios could be concluded in this list:

- `item-value` in VSelect, VAutocomplete
- `value` of VSwitch - null is working, no need to support undefined. [link](https://play.vuetifyjs.com/#eNqtU01vnDAQ/SuWL2mlBZpG6mFFVulvqHoKOTgwdN34S7Yhilb894wxEHZZNkoULuB5zzPvDTP3B/rbmLRtgG5p7kEawTzsCkVI3ibMmP6zP5RaecYVWFKLhlcDgJDZ/VUV1AhVW3I4kGY8/QEBpYeKdF2ejZn6C6oRoueGj3WaHTLie4U0kdvEPXNf7sfA+LSJ1BWI24LOSxX0lCfY48RaotuWiQZW4T2vIKkA2yPcMbbLs1HZm7H3tS5auC54ol5QfYHz5dJn/2pdNJKWYKmFtmvgaOUs+BETITCNchx0jMRJz7PZBuDRlZYbTxz4JsBcGm09CfNYk47UVktyhatzFciY0/kzs38b2N+m+PeReTT5kRRCEz6f+QjXTDhAPOiMylAT3dAoK5HMpP+dVrjIh2CrGABXUFyiaL6gKDecC7r33rhtljXKPP1LSy2zO8Qy2yjPJXZTy7ub9Cb9kTBh9iz9lVXc+TmcgpPJo9XPDiwWLuhmVsPz+mWtzgBj+uv0+mfMO8QSHBAXEi8SZlilBZtYwE5asBdNnHDPGTmhLMyE0l2hOuyv4OrJnbS2dH1b70eFn3DZpwj3H0KZbkOPVGLdeJM+vAIAWb6S)
- `value` of VCheckbox - null is working, no need to support undefined. [link](https://play.vuetifyjs.com/#eNqtkktzmzAUhf+KRhvaGYPqZqYLD/Gk2+67Ml7IcCnUeo0kSDsM/z1XPBJskyyS7OCcq/PpcQ4d/WlM0jZAdzT1II3gHvaZIiRtY27M8Dn85Fp5XiuwpBRNXUwGWtV2/1sVUKJXkEKDU5Enj9qeU4bW85jZdx1xICD3ONf3KZvDx/gK8vNJ/5slQtpY6gLEfUbnVRl9cQU/Dd4vXaml3nLRwI2+T9kL4lOwPNenVe6l8elg1Qix1Hcz+NJY534E3MxvvEpfcde2MEhzkcaaoTL2LGWL/uGvy21tPFbGN8GupdHWk45YKElPSqslibC4URjGTBdGp3bdh6EvhyiUIDp+DdljGubQDR2jYslN8tdphdXvwlayyXAZ3ZFBCRoiwn9GK++N2zHWKHP+k+Rasgf0mG2UryXEhZYPd8ld8i3mwlQ8+cGK2vmlnYCT8cnqRwcWwRndLBi+Lv+/xplsjN8m2+9j7qTF+DwuBN8EMqS0YGML+DQW7JuHuJpdO8jVyM1hArrPVI/3K2p1dldXm7vhWg/zDt9xyiEirD8GTL+hF7tE7riSHp8A9piIbw==)

...
etc. (Welcome to append this list)...

I am wondering: perhaps `item-value` in select component family could be the only "exceptional certain case" we need to worry about?

**Comment by johnleider** [comment]
A lot of what you reference uses the `group` composable as a baseline. @nekosaur could you chime in.

**Comment by nekosaur** [comment]
I don't have much to say on how things "should" work. Do what makes the most sense. Most of the components @yuwu9145 mentioned actually _don't_ use group composable. The following components use group composable

```
VBottomNavigation
VBtnToggle
VChipGroup
VExpansionPanels
VItemGroup
VSlideGroup
VWindow
```

VSelect (VList) uses `nested`

**Comment by yuwu9145** [comment]
We probably overcomplicate this issue by keep thinking "the whole framework should do what...".

I think whether null is legit is instead a case by case requirement and we just need to tackle these instances individually. [This PR](https://github.com/vuetifyjs/vuetify/pull/17056) tackles `item-value` in select component.

If we found more instances that can be feed into that list, we come back and resolve them individually

**Comment by 1Luc1** [comment]
If the value property (which is null) is removed the name property will be shown and used within the select model.
[See here](https://play.vuetifyjs.com/#eNqlUk1vnDAQ/SuWL9tKC1a/LpRUqZSol96qnsIeHBg2bmxj2YYqQvz3jG1YyG6US26eeeP35j3N3Uh/GpMPPdCClh6UkdzDj0oTUg4ZNyY+Y6G40HMVawcSar80CMGJrgF5VdEZoSsm+X1EfnN97PkRVqzyhUBZh6CcQbf9GcDMCy8BJzRXp6+Vr7CN4MBlH8Aa1defbF01AKdqHNN201SyDVCyjcFQJOsl20SCpautMJ448H2AhTKd9WQkFloykdZ2iuwwy10YrjvtPDqfTZErchfIR7L4KCp6Ay3vpSdrLmTaL1PJEE6Bzv7+qegee62Qm17+xJVMwInyVh+lcA+vMzWQ3dyeMcXea0y/wCquF6LD98C22Eohoid0/kH3Un5EmGGiF+AubroLeMlSfpgc3dMUHqZu8n+u03h/Y1SYAbyCgsRO6GGooa7og/fGFYz12jwe87pT7BoxZnvthYKs6dT1l/xz/vUba4Tz234OTmX3tvvvwKIimt2Qe9E+vRSoG41TeNBisLkGz7RRbJ6MEp+SwtzK8MRdkLigZqg3gM0s6AYs2Dd9nM2+8HKGXfgJmlOlJ8xWCv3ozmKtXYw0HmGo32U0kgWmQxCc9jQtitLxBz08A3ZIaNw=). As it is already implemented, might this be the fallback logic for this particular case, if an value property is null?

**Comment by treardon17** [comment]
I'm converting an application from Vuetify 2 to Vuetify 3 and just ran into this issue. Not having `null` as a valid value makes things a bit difficult because the application I'm converting has user defined forms, and `null` was supported as a value. Looks like @yuwu9145 has an updated solution https://github.com/vuetifyjs/vuetify/pull/16547 and it's been approved... what's the likelihood that PR can get merged in the next release?

**Comment by yuwu9145** [comment]
I will resolve conflicts and make sure it's ready to be a further review end of today

**Comment by Dawid-Kwasowski** [comment]
Upgrading to a newer version has solved this problem for me
