### ISSUE TITLE
[Bug Report][3.1.1]  [Vue warn]: Failed to resolve component:

### ISSUE THREAD

**Issue by disener** [vuetifyjs/vuetify#16444]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Originally installed Vuetifi 3.1.0
Then Vuetify 3.1.1 is installed on it.
**main.js does NOT WORK:**
```javascript
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
const vuetify = createVuetify({
    components: {
        components,
        directives
    },
})
```
**main.js does WORK:**
```javascript
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { VSlider,VImg,VSelect,VApp } from 'vuetify/components'
import * as directives from 'vuetify/directives'
const vuetify = createVuetify({
    components: {
        VSlider,VImg,VSelect,VApp,
        directives
    },
})
```

### Expected Behavior
should work

### Actual Behavior
[Vue warn]: Failed to resolve component: v-select...
[Vue warn]: Failed to resolve component: v-slider...
[Vue warn]: Failed to resolve component: v-img...
[Vue warn]: Failed to resolve component: v-app If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <AboutView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > > 
  at <RouterView> 
  at <App>

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U8FO4zAQ/RUrl7JSHTcUkKgKYn9hr00PxpkWF9uxbCftquq/M3YaSEMhhyieeX7z5s1kdcz+Wpu3DWSLbBlAW8UDPJeGkGVLubXpEw+VbIlQ3PunMqvoRsGBxBcVtWq0IbvGB7n5T73lAugrhD2AIVzJraECTABXZj1VSz0oEKE7xqeluq5AITX3FjP/eJB1mX0BFhKlxdKDvO8Bz0vWUw5KKFlh0Ssl9rIKb0Pyvq1OLRJtqA8OgrhAaWkQczubXQT5AYP3l0EfwGK0uNSX9KC+T4VSbwcNdo1RFzv7xYck/loT3gkMv4Vg/YIxUZk40ziSnc9FrZnUfAueWe64UvzANI7ZSa7ynd1emFG3vW1JN6rstoHhBpy/+sVYssHC4NELJ20gHkIT01Lb2gVyJA42ZOqAiyBbOJGNqzWZoLxJvCVq4wNJ/ZCnCL2Zz2Z/+vjAh3O2eCCMPF4D+IToqtysotRj10iQQcGCTIoH9jiZdrGWqwZjHVuKndJ7dOWOzUc37vDC/OcLBSvGJT7Ba1S9ZJ1L6E82zTqLqOY23/na4D+Y6MpzAld80RcoM3Qsnr+m3Bj7vk3TfcEcc40JUgOtav0yz2/zu3ucmQ/DeA5e01dX7z04rFhmZ6mJPG7LTwXOaeQt8qKjPYci5Tcqhvy4R9SBwa2PP/8vukfYC+2j3Df9ydrSnNBLJc27H9kofLJwtY6Q0zTrqBGc+sjWH7xAljM=)

### Other comments
If I import components all together I get an error. If you import the components separately, everything works.
Please help me to solve the problem

**Comment by KaelWD** [comment]
Compare this to what you have: https://next.vuetifyjs.com/en/getting-started/installation/#manual-steps

**Comment by cDnNeMeSiS** [comment]
still the problem, confirm

**Comment by uccmen** [comment]
I'm seeing this. @disener were you able to resolve the issue?
