### ISSUE TITLE
[Bug Report][3.1.1] data table pagination arrow icons not respect RTL locale

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#16447]
### Environment
**Vuetify Version:** 3.1.1
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10
![image](https://user-images.githubusercontent.com/47514686/230919345-14c6fb90-8c4e-4ef4-8775-f81db86dca9a.png)

### Steps to reproduce
change the pagination icon direction in RTL locale 

### Expected Behavior
change in data table pagination icons when selecting RTL locale

### Actual Behavior
No change in data table pagination icons when selecting RTL locale

### Reproduction Link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

**Comment by KareemDa** [comment]
any updates on this issue ?

**Comment by abumalekFayed** [comment]
no update till now

**Comment by a7madsam** [comment]
please, any near fix for this issue?
@KaelWD

**Comment by abumalekFayed** [comment]
.v-data-table-footer__pagination{
direction: ltr !important;
}

**Comment by eng-ahmad-sameer** [comment]
> no update till now but you can fix this problem by adding this class .v-data-table-footer__pagination{ direction: ltr !important; }

This will reverse the icons, I mean the first_page icon will be at the end, and so on...
The below solution will fix the above issue
```scss
.v-locale--is-rtl {
  .v-data-table-footer__pagination {
    > button {
      transform: rotate(180deg) !important;
    }
  }
}
``` 
This will keep the icons in the right position and just rotate them
