### ISSUE TITLE
[Bug Report][3.1.1] Data table column sort arrows missing with slot

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#16441]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
      <template #[`column.test`]="{ column }">
        {{ column.test }}
      </template>

Sorting is working but arrows are mssing.

### Expected Behavior
div with "v-data-table-header__content" class is missing at dom.

### Actual Behavior
      <template #[`column.test`]="{ column }">
        {{ column.test }}
      </template>

### Reproduction Link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

**Comment by RanEndelman1** [comment]
Hi, Same here.

**Comment by qxygene** [comment]
hi, i use mdi-svg only.
