### ISSUE TITLE
Pressing enter in <v-text-field multi-line> causes the wrapping <v-expansion-panel-content> to roll up

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#1644]
### Steps to reproduce
https://codepen.io/azaars/pen/oeKYpb?editors=1000#0

### Versions
0.15.2

### What is expected ?
The control should naturally remain inside `v-text-field` to allow further edit.

### What is actually happening ?
Pressing enter key propagates the keystroke event to the wrapping `<v-expansion-panel-content>` causing the panel to roll up and hide it's children.

### Reproduction Link
https://codepen.io/azaars/pen/oeKYpb?editors=1000#0

**Comment by johnleider** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/issues/1585
