### ISSUE TITLE
The selects documentation should update the "text" to "title"

### ISSUE THREAD

**Issue by suterma** [vuetifyjs/vuetify#16456]
In https://vuetifyjs.com/en/components/selects/ and the corresponding https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/pages/en/components/selects.md they talk about "text" and "value" for custom items.

However, "text" is now "title". The documentation should replace the wrong/old term to the correct term.

**Comment by messenjer** [comment]
Hello, 

It's a difference between versions 2 and 3.

And it's already correct in the documentation of the v3. That you can find here: https://next.vuetifyjs.com/en/components/selects/ 

The modification was done here https://github.com/vuetifyjs/vuetify/commit/9211544217195c67490003e4e2b06bb2aa166609 

Regards

Mathieu
