### ISSUE TITLE
[Bug Report][3.1.1] Clearable not working when svg iconset is loaded. [VTextArea, VAutocomplete, VTextarea]

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#16453]
### Environment
**Vuetify Version:** 3.1.1 &  3.1.0
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Fill in the text field (or select, or textarea).
2. Click on the clearable.
3. Notice the field is not cleared.

### Expected Behavior
Clicking on the clear icon should clear the field.

### Actual Behavior
Does nothing.

### Reproduction Link
[https://codesandbox.io/s/vuetify-3-vtextfield-clearable-4tz3ju](https://codesandbox.io/s/vuetify-3-vtextfield-clearable-4tz3ju)

### Other comments
This is also making the `@click:clear` event not work.I also tested with the MDI Svg icons and it had the same problem.

Codesandbox was being finicky, so if you get an (SyntaxError ) error, you will need to click on the Browser reload button on the right side panel so it will recompile. I tried to load an example in Vuetify Play, but could not figure out how.

**Comment by KaelWD** [comment]
See #3505, `dom.watch()` is not compatible with vue. `iconfont` is also supposed to be `defaultSet`.
