### ISSUE TITLE
Layout problem when i add Router-view on v-menu,v-navigation-drawer

### ISSUE THREAD

**Issue by zefiros** [vuetifyjs/vuetify#1645]
### Steps to reproduce
I use the template from the site to create a pwa app.

npm init vuetifyjs/pwa

I make this change on App.vue
If i remove the line with the route

 <router-view></router-view>

Is show correct the v-menu,v-navigation-drawer

When this line exist i have problem
https://imgur.com/a/QFp0j

<template>
  <v-app>

    
    <v-navigation-drawer persistent 
    :mini-variant="miniVariant" 
    :clipped="clipped" 
    v-model="drawer"     
      >
      <v-list>
        <v-list-tile 
		value="true" 
		v-for="(item, i) in items" 
		router
		:to="item.link"
		:key="i">
          <v-list-tile-action>
            <v-icon v-html="item.icon"></v-icon>
          </v-list-tile-action>

          <v-list-tile-content>			
            <v-list-tile-title v-text="item.title"></v-list-tile-title>
          </v-list-tile-content>

        </v-list-tile>

      </v-list>
    </v-navigation-drawer>

    
    <v-toolbar class="primary" dark>
      <v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon>
      <v-btn icon @click.stop="miniVariant = !miniVariant">
        <v-icon v-html="miniVariant ? 'chevron_right' : 'chevron_left'"></v-icon>
      </v-btn>

      <v-avatar>
        <img src="/static/img/icons/favicon-32x32.png" alt="logo">
      </v-avatar>

      <v-toolbar-title v-text="title" class="hidden-xs-only" dark></v-toolbar-title>
      <v-spacer></v-spacer>
      
      
       
        <v-menu bottom right>
          <v-btn icon slot="activator" dark>
            <v-icon>more_vert</v-icon>
          </v-btn>
          <v-list>
            <v-list-tile v-for="item in menuItems" :key="item.title" >
              <v-list-tile-title>{{ item.title }}</v-list-tile-title>
            </v-list-tile>
          </v-list>
          
          <v-divider inset></v-divider>
          <v-list>
            <v-list-tile v-for="itemx in menuItems2" :key="itemx.title">
              <v-list-tile-title>{{ itemx.title }}</v-list-tile-title>
            </v-list-tile>
          </v-list>

        </v-menu>

       
        <v-menu bottom left>
          <v-btn icon slot="activator" dark>
            <v-icon>public</v-icon>
          </v-btn>
          <v-list>     
            <v-list-tile v-for="item in menuLangs" :key="item.title"  >
              <v-list-tile-title>
                    {{ item.title }}
             </v-list-tile-title>
            </v-list-tile>
          </v-list>      
          
        </v-menu>
    
        <v-flex pl-5 pr-5 xs12 sm3> 
         <v-btn router to="/Login" icon class="indigo--text">
            <v-icon dark>
             lock_open
            </v-icon>
          </v-btn> 
        </v-flex>

        <v-flex pl-5 xs12 sm3>
          <v-btn  router to="/Logout" icon class="indigo--text">		 
            <v-icon dark>                       
            lock outline 
            </v-icon>
          </v-btn>
        </v-flex>

    </v-toolbar>

    
     <main>
    	  
	 <router-view></router-view>
    </main>

  </v-app>
</template>

<script>
export default {
  data() {
    return {
      clipped: true,
      drawer: false,
      items: [
        { icon: 'bubble_chart', title: 'Inspire' ,link:'/'},
        { icon: 'room', title: 'Room' ,link:'/Login'},
        { icon: 'person', title: 'Person' ,link:'/Logout'},
        { icon: 'face', title: 'Face',link:'/profile' },
        { icon: 'lock_open', title: 'Sing In' ,link:'/Login'}
      ],
      miniVariant: false,
      title: 'Go On Diet',
      menuItems: [
        {
          title: 'First 1'
        },
        {
          title: 'First 2'
        },
        {
          title: 'First 3'
        },
        {
          title: 'First 4'
        }
      ],
        menuItems2: [
        {
          title: 'First 1'
        },
        {
          title: 'First 2'
        },
        {
          title: 'First 3'
        },
        {
          title: 'First 4'
        }
      ],
      menuLangs: [
        {
          title: 'Ελληνικά',
          value: 'EL'
        },
        {
          title: 'English',
          value: 'EN'
        }       
      ]
    }
  }
}
</script>

<style lang="stylus">
  @import './stylus/main'
</style>

### Versions

I used Version of Vetify is 0.14.11
"vue": "^2.3.3",
    "vue-router": "^2.3.1",
    "vuetify": "^0.14.11"

### What is expected ?

If you see on screen i expect this layout
https://imgur.com/a/vWJnI

### What is actually happening ?

I used Visual Studio Code

### Reproduction Link

This is the layout with problem

https://imgur.com/a/QFp0j

**Comment by johnleider** [comment]
This is more of an issue than a bug report. There is no reproduction link (a picture is no acceptable). If you truly believe this is a bug, you'll need to provide a reproduction link, otherwise:

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
