### ISSUE TITLE
[Task] v-otp-input

### ISSUE THREAD

**Issue by mcrib96** [vuetifyjs/vuetify#16458]
I am looking at vuetify v3.1.0.

We want to use the v-otp-input, but it does not appear to be available.
I see it in lib/components, but it is not available when importing through vuetify/components.

Am I missing something?

**Comment by johnleider** [comment]
Unfortunately it hasn't been ported to v3 yet

**Comment by pitiphong-dev** [comment]
i can't use type number for v-otp-input into labs/component in version 3.3.15 how to solve this
