### ISSUE TITLE
[Bug Report][3.1.1] VMenu arrow keyevents do not work with VListItem

### ISSUE THREAD

**Issue by djurdjen** [vuetifyjs/vuetify#16455]
### Environment
**Vuetify Version:** 3.1.1
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Add a `VMenu` component
- Add `VListItem` components inside of the `VMenu` component slot
- Bind the attributes from the scoped slot activator to the activator button

### Expected Behavior
Using up-and down arrow key events should trigger a focus on the next or previous `VListItem` entry within `VMenu`

### Actual Behavior
Up-and down arrow key events are not doing anything currently

### Reproduction Link
[https://codepen.io/djurdjen/pen/KKBXMWP](https://codepen.io/djurdjen/pen/KKBXMWP)

**Comment by floroz** [comment]
@KaelWD would it be reasonable to say that:

- when the `activator.props.onClick` is triggered, the default slot element should be focused.

**Comment by sametaylak** [comment]
any updates on this?

**Comment by KaelWD** [comment]
Fixed in #17203
