### ISSUE TITLE
[Bug Report][3.1.2] v-data-table-server does not render anymore

### ISSUE THREAD

**Issue by C0kkie** [vuetifyjs/vuetify#16468]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Hello,

since the upgrade from 3.1.1 to 3.1.2. No data is displayed anymore when using serverside datatables.
I did attach the examples docs, because they are broken too as andrew told me

### Expected Behavior
Display data

### Actual Behavior
Does not render

### Reproduction Link
[https://next.vuetifyjs.com/en/components/data-tables/server-side-tables/](https://next.vuetifyjs.com/en/components/data-tables/server-side-tables/)

**Comment by MajesticPotatoe** [comment]
Likely related to #16419

**Comment by kvcvc** [comment]
+1

**Comment by kamils-iRonin** [comment]
any chance of getting this fixed in 3.1.3?
