### ISSUE TITLE
[Bug Report][3.1.2] v-data-table-server hide-default-footer and v-slot:bottom doesn't work

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#16470]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows

### Steps to reproduce
The hide-default-footer doesn't work. I try to use v-slot:bottom then it displays error 

![image](https://user-images.githubusercontent.com/136077/213345825-3a39ebc7-eac8-409c-9238-763a5d529bea.png)

### Expected Behavior
Default footer should be hidden 

### Actual Behavior
Default footer always display

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U01v2zAM/SuEevAGxDaarZcsDdo/sNOwS5yDEjOJFksyJCZbEfi/j5JsNx9bTzb5qEfxPWp5Fqcjktq+Fb+8mAmlW+sIzrBxKAl/Jgw62DqrIetrs8pUBv/E0o01nqAH4Pn64KdzZQBojxpnTFrjVh4b+pHirFG7PWXQTQCgMt3nyoiJeG3bgtn4LnNC3TZMtggk81Mu2zb+xkBLZfooJWpJMie5bjD36E7oRhBme5Q1Ov9cif6vEheo4kY+b9DsaM8lT/cgZ+O3EkP+vULzRCr3rMV7bq9qzPtp8621hG6AbgkWdxmeZpgcHtaWyOoFzMtRjevqefmP0QeZGBt1CkFS8IIrGMkJv3GqJfBIx1AwboHD7aX30fdkeK8jG74M5GcgRU0w9SGbwAHf+E/Vwdtr1EiNY0EfSN4DwyGaeCCMtvoWjg29ovRjJ1XP4HEC4TAfejVZ3yPkp2P+u9QRCExh4jQhz8YrlsZjZVpeemt41eKasscRYJd5WZOCVXgeIebNIWr9rCyPpj3sio3V5QtjpTsaUprdtvrlSzEtvj6VtfJ0mS/Q63zt7G82hztWIl64Jw/P5H8Neph5H4tpoh1eK1PeUZXJ/Nyxkuj4AXx075vaq7vfYHf3Dz07frGsZaPMwd/IuPFRwuUqlHQTkai5OM4hVn8BUYFrGQ==)

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/ddea99556359ff1b272dfc10e0ddecbbc8eb6171
