### ISSUE TITLE
[Bug Report][3.1.2] @update:modelValue disables rule validation

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#16474]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Linux x86_64

### Steps to reproduce
Have a look at the component "MyCustomComponent"

Clear the input field, no error message comes up

Now remove the event listener and see that an error message comes up

### Expected Behavior
When clearing the input field there should be an error message

### Actual Behavior
When clearing the input field there is no error message

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNU8mO2kAQ/ZWiL8xI2FYmycUBRDRSpBwiRYmSC+Zg7AI62N2dXkzQDP+e6rYBA5mchwN2LX71annzJ/ZRqbhxyFI2tlirKrc4zQTAuIlypcJrMOqci84iexBF8J2XKKTFFD5DkYuhBWcQKFOWWMEGNcISi9w77QZhxbEqockrh8ANfVEVzlcrYbmHHFZOFJZLAVF0LlPvo8IZK+uokLWSAoVtcaKAM8nYSsqMQXLkmfSIeqNtYZz0WiPTFJorCwat82FO0NrCl/1jqPV4LqVlDRmLk5uQH1nGPnjoFoxg2Ii1SERBxb+MFDTUJ88k6wImYykEj/cFiJReNtYqkyaJE2q7jqnTZEaxRDtheY1RKevZ2/ghfvc+KbmxfX+Mpo6WWu4MaqqYsVEP3PLV/qUCXZhw38QPLWzn8pA3UAnhN6gjjaKkver/8r7KveB+Fbvh72seMnGgWVZcbM3VGAsTRjhftCn/XIu/5P6CocrFmi7FT5+2VEhhLCgtlYEJlLjiAr96axxqhOv66Y8rBSe2Qu4EbfkwvbunB1EQpzuV4ocq6aTuBO4uP7hvd+wryQrjSq5POR6F+utdDRleTN9chQZy0own1IrAB+j/QpadGi3+sVHgenQC9bnEihoNz3aU7S/VHpwic2hgMoXBoIHnZxh+CookLWr87bjGcgiLi++Cks9SO43mnOSFd6GuQLzriXI5TcgPi3a8xU7br7wlgJkLi21zQ5RSj+t+sXd2GLH21Okyg67Y4i9JVsUJ)

### Other comments
I can't use v-model because the field value is calculated by a function so I have to rely on a prop and an update event

**Comment by KaelWD** [comment]
There's no way to tell the difference between this and you intentionally ignoring the update, you have to get the new value back to modelValue somehow.
