### ISSUE TITLE
[Bug Report][3.1.2] [Vue warn]: Failed to resolve component: v-data-table-server

### ISSUE THREAD

**Issue by osmartinez** [vuetifyjs/vuetify#16473]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add v-data-table to vue template

### Expected Behavior
Rendering

### Actual Behavior
Not rendering

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U0ly2zAQ/MoUfOCFS1mJLwytsj+QD4g6QCIoISKWAoZKuVT8ewbgYi2xiwdiugc96Aa5ubB3a/NzL1jJKhTKdhzFutYA1Tnj1sZlLBSXeqpGoOHIM+S7TmReuLNwCwnlUfBGOP9as2lVsytW0iCfdUIf8EgtL48kofFdsxn/7FB9hzLzxuEndpSNyBrRcuKy1hgUbqbuBdYPCLmZncPTziAatYaqWNK47a6K/1ifYyJuySkUY4JXWrUOT+X3TloEL7APDVJZsgMXcKKFAVpnFCR0KUlo3hvtEaYc4RU2QfwCKLETJSRPSQon8UEr2SQwpLes5kosDVPBO3nQVAodNwRr219h2zwrRr9Mkk0JzymEzbTpXSfTjICvFvw3V5EISsHx6JC8sZSN9igZm//xRtOndonjJoJuuYSIBIxsh5q+HETry6LotT0d8r1RxRtxhes1SkW3bdTbj3yV/3wpGunxGs+FV9nOmb90OTSxZvHAkzjK9uOrARNNus/5apSdoCD5IFWMl585SlI4+gG+O/dd783Z77iH84eZQ60HyrKT+uTvYtz7GOFmG1qGlI3S1Bx9sO0/KOg4PQ==)

**Comment by KaelWD** [comment]
https://next.vuetifyjs.com/en/labs/introduction/#usage
