### ISSUE TITLE
[Bug Report][3.1.1] Vchip is not responsive for small devices

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#16472]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
code is written in playground

### Expected Behavior
chip should behave responsively

### Actual Behavior
chip removes close button in small size

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUk2P0zAQ/SuWLwGpScQCl6qLFiHuK62EhJoenGTSmvWXxk6gqvrfGdvNElrBnup57/XNzMtsT/yzc9U0Al/zTQDtlAjwqTGMbaZSOJeeqdBCmkuVkG9frG5ta39ljAS2B3Xf8O4gnW94hnORnnpUQToFF0KBQNH+Ka2PVbn4Q5KUsrOGXHUvyygihURiSjsGJQ3MjdaSpvckTL8zqkSbZvpuR2SDmCwSzQ62bSW8iByCA9MvOw1SBcByEiiFCVlYz1nUizBikWPa1Iv4qPQdSheYhzBGWmpnMbATQxjYmQ1oNSso96Ix1NaHnBS7j/ybbfGIdo9Ca2n2xYoVj0oc6ckm2YNle6HBR/hJAbgo2b2dbdL6LzZPAUHMJl9FmO1edWeDRaaFOTJliQlSw03DTZ13pO34iucFKRlX/fDW0D2dYkD0QRJBaa9ZQiJGi8e64YcQnF/X9Wjc877qrK4fiKtxNLFl2Vv98L66qz58rHvpwxKvwOuyRfvTA1LHhq8W5kEOx381uNDk+666y7YXKFreWNXkP9EtIJ0IIOB/577S/jX7FXczf+x5bsyZsqTDfvZXMXY+RbjdRcl5xbM1idMefPcbPGhEvw==)

**Comment by alokVishu** [comment]
![Screenshot 2023-01-19 at 12 33 56 PM](https://user-images.githubusercontent.com/80033712/213376980-850c567e-efe6-4300-9929-07193ea97bef.png)

**Comment by lioneaglesolutions** [comment]
Not really to do with screen size but just long chips in general - repro with card and max-width [here](https://play.vuetifyjs.com/#eNqlUk2P2jAQ/SuWL7QSibu0e0HZaquq95VWqlQRDk4yAXfjD42dLAjx3zuOCcuC1B7KBc+85/c8L7M68G/O5UMPfMmLANp1MsDX0jBWDJl0bjyOhZbKUEWnWmLDtNxlr6oJ24eSL+4/uV3JT9y3X/Hzu9WVrewuISRiG+joRr1Vzpc8tVMxHnXfBeU6OAEdSJTVW2l9rLKLCyMlU7U1pKoblUUSMRQSktk+dMrAZLRUNKEn4vg/dTtZjW/6ZXtkrRwsEsy2tqoUnEkOwYFpLp1a1QXAbJCopAmJKM4ZFCIFNQVI5SnBVKRsC3GROZW+RuUC8xD6CCvtLAZ2YAgtO7IWrWYz+liz0tA7fEjRsYeIf1jNntBuUGqtzGY2Z7OnTu7pyAbVgGUbqcHH9nMH4CJl/XGSGfM4yzwHBDmJ/JBhkvunOmst0mKYPessIUFpuDEsRJqRpuNzngakZFz+21tDS3iIAdEXGgGKf8nGTuzR4LEu+TYE55dC9Ma9bPLaavFImMDeRMussfrxc77Iv9yLRvlw2c/B66xC++oBybHk8wvxoNr9e4O6McSilVUD5gaCME6LE5Ms7vK7RbI49TLaJR89brQFGQ60LUhLBAj410GuuO+GucJuBoqex9IcKVxa/Rd/lWvtx0xX09P+b9JRLUqto+NxztNLyTtd4es/L291AQ==)

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/61766491/235893368-ac2a0126-045b-4272-8348-4f5ec5c035a2.png">

Not really sure what the solution would be though in terms of something responsive. @johnleider

**Comment by hanifrodili** [comment]
why v-chip goes 100% width(parent with display flex) in latest release?
