### ISSUE TITLE
Disabled v-radio doesn't look different than enabled one

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1647]
### Steps to reproduce
Place a `v-radio` and set its `disabled` attribute to `true`

### Versions
Vue 2.4.2, Vuetify 0.15.2, Edge 15

### What is expected ?
Disabled `v-radio` elements should have a different style so you can recognize they are disabled

### What is actually happening ?
Disabled `v-radio` elements appear just like non-disabled ones

### Reproduction Link
https://codepen.io/smares/pen/RZXZjz

PS: Why is it that each `v-radio` has a `<input name="test" style="display: none;" type="radio">` (each of them with the name `test`)?

**Comment by smares** [comment]
Seems that `input-group--disabled` is not applied.

**Comment by KaelWD** [comment]
The `name="test"` looks like some testing stuff that was pushed to public. Open a separate issue for that if it's a problem.
