### ISSUE TITLE
[Documentation] Vuetify 3 "Programmatic scrolling" still accessible

### ISSUE THREAD

**Issue by weeix** [vuetifyjs/vuetify#16471]
### Steps to reproduce
1. Go to Google or DuckDuckGo
2. Search with the keyword "vuetify goto"

### Expected Behavior
"Programmatic scrolling" document for Vuetify 3 doesn't appear as a search result (from #16122, I assume that the feature isn't implemented in v3)

### Actual Behavior
"Programmatic scrolling" document for Vuetify 3 appear as a search result

### Reproduction Link
https://next.vuetifyjs.com/en/features/scrolling/

**Comment by logue** [comment]
It seems `goTo` function does not exported.
https://github.com/vuetifyjs/vuetify/blob/69dc8a2f3f18963df5b39e16144603e29851979f/packages/vuetify/src/services/goto/index.ts#L19

**Comment by denisbetsi** [comment]
Seems like goTo service is unfinished 

```

// goTo.framework = {} as Record<string, VuetifyServiceContract>
//
// export class Goto extends Service {
//   public static property: 'goTo' = 'goTo'
//
//   constructor () {
//     super()
//
//     return goTo
//   }
// }
```

The entire section is commented out

**Comment by zouyi100** [comment]
Any update till now? :)

**Comment by abea** [comment]
In April a core team member suggested using the native `scrolllIntoView` method instead. https://discord.com/channels/340160225338195969/1101913424612569239/1102141822467321876

**Comment by timmapme** [comment]
Any updates?
