### ISSUE TITLE
[Bug Report][3.1.2] Failed to resolve component: VDataTable

### ISSUE THREAD

**Issue by iampapagray** [vuetifyjs/vuetify#16476]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 110.0
**OS:** Mac OS 10.15

### Steps to reproduce
Just create a vue app with vuetify and try using the VDataTable component

### Expected Behavior
Should work like previous versions

### Actual Behavior
I get this error: 
Failed to resolve component: v-data-table
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
 at <App>

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUctS3DAQ/JWJLk6q1laFJBeXl4Jb+AIO6z0IewwCvZDkBcrlf2dkG8osr5t6pme6p7Ub2LlzxaFHVrIqonZKRDytDUB1yIVz03MCWkizoAlHfIx5J1G1QE3botrWTIfrmgFf81oRRR7FlUIob1C06MN2WB7jacXXjBc1Kr7KJTAbqfjKIMHQeOkiBIx9akvtrI8wgMcORui81ZDRZVkiN9aECGQPtqn/M/uPSlm4tF61P7JfL4TF10LaJf0B0qUlZBeknm3gIFSPBOUMA2km6yV0QgWEcfNm6L4XJsr4tBpclb4ZPm+iJFurWfFa+Wh0T3dUfI6FAmEbNmdCYbriNlhDnzwkhXpphJqVMFVSjbJKuGY3MbpQct4bd3ddNFbzM+px35NvjXlr9dmf4qT4+4+3MsR1vcCg8ytvHwJ6UqzZdNCyPMru6TOBpU17fxcn89qllFa+W8Vp/wF97tHQf6H/0vcR9433o947/0lzrM1IWSpp7sJRjE2YItztE2XcsHk1kac72P4ZzwcgQQ==)

**Comment by iampapagray** [comment]
I got this to work after importing VDataTable in main.js like so: `import { VDataTable } from 'vuetify/labs/VDataTable'`
Even though VScode couldnt resolve the file path it still worked.

**Comment by ccnwjsqdfky55** [comment]
I don't think this issue should be closed

**Comment by iampapagray** [comment]
@ccnwjsqdfky55 Why not? I had a problem and found a solution to it. I think if you are facing a similar problem and my solution doesnt work for you, you can create a new issue with all the necessary information so others can help.
