### ISSUE TITLE
[Bug Report][3.1.2] font is different when vuetify is used with nuxt 3

### ISSUE THREAD

**Issue by MaazDev** [vuetifyjs/vuetify#16480]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
1.  https://github.com/MaazDev/vuetify_bug
2.run yarn dev in the root (this is the nuxt 3 + vuetify project)
3.cd into vuetify-project and run yarn dev (this is the vuejs + vuetify project)
4. ur going to notice that the fonts weight is different

### Expected Behavior
font weight should be the same as a normal vuejs project

### Actual Behavior
font weight and maybe other font settings are different , font look thinner

### Reproduction Link
[https://github.com/MaazDev/vuetify_bug](https://github.com/MaazDev/vuetify_bug)

### Other comments
vuejs + vuetify: https://postimg.cc/Yj3Q1ysg
nuxtjs + vuetify: https://postimg.cc/xc1MgywZ

**Comment by KaelWD** [comment]
The nuxt project is missing roboto
https://github.com/MaazDev/vuetify_bug/blob/main/vuetify-project/src/plugins/webfontloader.js#L12
