### ISSUE TITLE
[Feature Request] VDataTableFooter should use i18n

### ISSUE THREAD

**Issue by janschoppenhorst** [vuetifyjs/vuetify#16482]
### Problem to solve
The v-data-table in the labs package of Vuetify 3.1.2 does not use i18n. Looking at the code of https://github.com/vuetifyjs/vuetify/blob/0732c22aed24503a24aa6359cffbcaad66351492/packages/vuetify/src/labs/VDataTable/VDataTableFooter.tsx

at line 60 for example the string "Items per page" is hardcoded and if you change the language this text will not change while at other places (noDataText for example) it works.

### Proposed solution
Two things:
1. Do not hardcode any of those strings
2. Make it possible to submit a bug without providing a running example ;) Thats the reason I put this here as a Feature Request.

**Comment by xignp** [comment]
Below is an example of English to Japanese

### Reproduction Link
https://codepen.io/xignp/pen/zYLQWzj

Looks like it  is just reading only ”noDataText” from the language definition.

**Comment by xignp** [comment]
This problem seems to be fixed in v3.1.5

**Comment by KaelWD** [comment]
Duplicate of #16625

**Comment by janschoppenhorst** [comment]
Hi,

kurze Rückmeldung da ich jetzt eine funktionierende Lösung habe und
vielleicht andere davon profitieren können, wenn ich sie informiere. Das
Problem mit dem Verlust der RTP Daten scheint bei LTE Verbindungen
aufzutreten. Eine einfache LTE Ausnahme im Speedport für die Ports bzw. den
Telekom DNS Namen einzurichten scheint aber nicht auszureichen um die
Telefonieverbindung nicht über LTE laufen zu lassen. Die Lösung ist nun die
IP Adressen direkt einzutragen (siehe Screenshot)
[image: image.png]
Leider bietet der Speedport Router nicht die Möglichkeit den gesamten
Adressbereich auf einmal einzutragen. Momentan laufen aber alle Telefonate
immer über die 164er Adressen. Sollte das wechseln muss ich eine weitere
Ausnahme hinzufügen. Funktioniert bis jetzt einwandfrei :)

Mit freundlichen Grüßen
Jan Schoppenhorst

Am Fr., 17. Feb. 2023 um 13:06 Uhr schrieb Kael ***@***.***>:
