### ISSUE TITLE
[Bug Report][3.1.2] VSelect with multiple and compact density height changes if no options are selected 

### ISSUE THREAD

**Issue by Machine-Maker** [vuetifyjs/vuetify#16488]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Safari 16.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a VSelect component with the `multiple` and `density="compact"` props and see the height of the select box change based on if anything is selected or not.

### Expected Behavior
The height of the select box shouldn't change based on if any option is selected

### Actual Behavior
The height of the box changes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtuwjAQ/BXLl7YSxCptL1Go4BvaG+YQkqW4xA/ZGxBC+feunURKQe3J3pn1zHg2V752Lju1wHNeIGjXlAjv0jBWnOalc+maBl0qM0xpDtBAhYwIW0OzlLwHoJac5YqkAmHpJKApd2lnzT76Z58HQmswQeGF8MpqV1ZImG4bVK4BJkZrMfGOQ5+qEJO0NIbKK4csALaRVtpZj+zKPOxZx/beavZA33yIy5U1AVnKxpZx43EjuTUg+YxJjmc7XA4eCNs+jS/GH46PIlOI3pk8+Yz3tpTXZd/BGir1GmNTEYmgKnKWkIhRnDhLfkB0IReiNe74lVEXYkWc8K1BpWFeW716yRbZ65uoVcApnkHQ85235wCeHCn3RBzV/vKXwUCT7nO26GUHKEreSQnSP4GfezA1ePD/5r7Z/ZX9hrvLHz07aTrqslHmGG5qrEKqcLONK92M99K0nP7Btz+0tvCB)

**Comment by drich1402** [comment]
The height is still different in version 3.3.2, with label compared to without label:
`<v-row>
        <v-col
          ><v-select
            density="compact"
        /></v-col>
        <v-col
          ><v-select
            label="label"
            density="compact"
        /></v-col>
      </v-row>`
