### ISSUE TITLE
Can't apply HTML5 autocomplete="off" to v-select

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#1648]
### Steps to reproduce
Use a ```v-select autocomplete``` as well as the HTML5 autocomplete attribute set to off (or any other value that is no "on").

### Versions
My package.json contains the following:
```
    "vee-validate": "^2.0.0-rc.14",
    "vue": "^2.4.2",
    "vue-class-component": "^5.0.2",
    "vue-router": "^2.7.0",
    "vuetify": "^0.15.2",
    "vuex": "^2.3.1",
    "vuex-persistedstate": "^2.0.0"
```

### What is expected ?
Be able to use v-select with autocomplete as well as disabling the browser autocomplete.

It's not that the current behaviour is unexpected due to the conflict between v-select autocomplete and HTML5 autocomplete. This issue is more to raise the question about how to use v-select autocomplete while also being able to disable the browsers HTML5 autocomplete function.

### What is actually happening ?
The component logs errors to the console because of an incorrect autocomplete binding due to a conflict between v-select autocomplete and HTML5 autocomplete.

```
console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 [Vue warn]: Invalid prop: type check failed for prop "autocomplete". Expected Boolean, got String.

found in

 <VSelect>
       <VApp>
         <Root>
```

### Reproduction Link
https://codepen.io/anon/pen/EvqEWy

**Comment by johnleider** [comment]
Select does not support browser level autocomplete as far as I'm aware. The autocomplete prop is just for enabling Vuetify specific autocomplete functionality.

**Comment by jacekkarczmarczyk** [comment]
I think he means that `v-select` should automaticly add `autocomplete="off"` html attr to `input`, now it doesn't

**Comment by johnleider** [comment]
Gotcha, @roryprimrose , is @jacekkarczmarczyk correct?

**Comment by roryprimrose** [comment]
Yes, because I want v-select autocomplete to allow the user to filter down the list, but I don't want the browser to provide autocomplete, therefore I also want to include autocomplete="off" on the input as @jacekkarczmarczyk as mentioned.

I don't think it should necessarily add this by default as it could cause issues with people's current implementations. It would be good however if there was an option to toggle it though. Something like ```disableBrowserAutocomplete``` or ```browserAutocomplete="false"```

**Comment by johnleider** [comment]
Great idea, will fix, ty!

**Comment by peluprvi** [comment]
It was implemented in an inverted way.
As the coments above, it is better to have `browser-autocomplete="off"` by default.
