### ISSUE TITLE
[Bug Report][3.1.0] [3.1.0+] v-chip inside select closable doesnt work 

### ISSUE THREAD

**Issue by alexanderge** [vuetifyjs/vuetify#16499]
### Environment
**Vuetify Version:** 3.1.0
**Vue Version:** 3.2.45
**Browsers:** Chrome 93.0.4577.99
**OS:** Linux x86_64

### Steps to reproduce
Set closable to v-chip inside v-combobox. 
Close button will  not be displayed.

### Expected Behavior
Close button should be displayed in chip

### Actual Behavior
Not displayed

### Reproduction Link
[https://codepen.io/alexanderge/pen/qByxKbK?editors=101](https://codepen.io/alexanderge/pen/qByxKbK?editors=101)

**Comment by KaelWD** [comment]
It's a bit weird but if you have `chips` then the selection slot doesn't nothing, you have to use v-slot:chip instead

**Comment by alexanderge** [comment]
Thanks!
