### ISSUE TITLE
[Documentation] Selection slot text (e.g. "+N others") appears for every "other" item selected

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#16491]
### Environment

**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select at least 4 items.

### Expected Behavior
Text should appear once.

### Actual Behavior
Text appears N times, where `N = len - 2`.

### Reproduction Link
[https://next.vuetifyjs.com/en/components/selects/#selection](https://next.vuetifyjs.com/en/components/selects/#selection)

### Other comments
A quick fix would be to change `v-if` value from `index >= 2` to `index == 2`.

**Comment by KaelWD** [comment]
That's how it was before 14d82d13
