### ISSUE TITLE
[Bug Report][3.1.2] Dialog get close when flat-picker dropdown closing

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16497]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use a flat-picker with dialog 

### Expected Behavior
The dialog should not be closed.

### Actual Behavior
Dialog gets closed

### Reproduction Link
[https://codepen.io/alokvishu/pen/rNrJpbm?editors=101](https://codepen.io/alokvishu/pen/rNrJpbm?editors=101)

**Comment by KaelWD** [comment]
Not a bug, flatpickr is adding elements outside the dialog so it's treated as a click outside. Either use `persistent` on the dialog or set flatpickr's `appendTo` to an element inside a VOverlay component.
