### ISSUE TITLE
[Bug Report][3.1.2] Not coherent Wireframes between v2 and v3

### ISSUE THREAD

**Issue by Amine-Smahi** [vuetifyjs/vuetify#16496]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 2.6.14
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Windows, Linux, Mac OSX

### Steps to reproduce
Open the vuetify v3 documentation and navigate to the wireframes section and click on any of the demos

### Expected Behavior
Should look and behave correctly as it looks on v2

### Actual Behavior
Inputs are not clear, dark mode on all page and not on some parts and some parts no

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVlFr2zAQ/iuaX9pCFbdpu0FISwd7GWwwBntq+qDE51iLLBtJcZOF/PedZMeW7KSl0LzEvu909+nuk85Pu+hrWY6qNUSTaGogLwUz8DCThEwrysqS8OR+FnGpS65gFjnkgNE5UyTFBY3V2ReFNIxLUGQhmNa4OOVC0Az4MjMkoamADWGCLyVdgDSg2qCHwBUzTHUm0gbKgV5fkVzT21kU4IUoFOJLBVuaMLUCSa9DF83/AXrcjH3zwzQ+pEMKAYm58d4JqWjqMgguV4RLYv91mGGygm3jEQIVU5xJg5iBjQny+267nYtK9nuPCPJDJn1yumQLUI5989hzUKDLQmpeAcnZhr7wxGSYf/z5Kii287WkaMpBJD5ASAIYwNgtLYocswTM7S/jCdAEsNlCh0i3Y42dCdc51l1Ov/UIdMQ7SaG51dRBfrZvtf7areNWcvRpxTJfUqcHVFpmUBA33tZ9mYbiU8VLv0CoLqswGxPVE6B1NzIAQ1SxlgnYsyKWAy/nJ7h+0611pBzP4hDtlCitDO/6PQmkKI+jTqED+xEqIRlquBFdW8LfD7u37+hlZSwDDXvRsGtvhwu8AmF7rBJeofq6KybfUtsbu7aBTq18tbjHS9O7YA6C6l1CH1HG35DiCcg+rnjH0b6G7T1iRRwq35070atjfR5OHIJ+vpzL5t7H2n25qrJhxcLzEKJD/p8oJYTSd/IPLhjvfJ+6Wew1Uk/A+prB52nsjUZ81QvFyzofbMpC4WCDlK2FIbs6ToJDZULOL8j9AzlvbLW+9IQ8dZzOvjGdzQumkrNLz/oTtGZL0IHxlypwlEJg+1NiJt/vuXnaX7gHPIjTuGUbXUY8t3Rxj+Xory4kTn3HDke8A3CoTQ57mEX4WWDfZ1FmTKkncbyW5Wo5woEQPyIWq7U0HKdyUuSPN6Px6PYuTlBfvn0EOqdzLLsGhRlnUcPPBTc83Z5K0MAY93o0rsM2JhtyECrG+BUonCCoJ2W/Kl7h3fMNuPewAf+mqnuspWtnr4wL7Ur49Gxd9pdRHRqd3T6i5//BG5ni)

### Other comments
for example some of the inputs present on the navbar are impossible to see specially on dark mode

**Comment by johnleider** [comment]
Saving this here: https://play.vuetifyjs.com/#eNqtVt9P2zAQ/le8vAASbqDAJlUFMWkvkzZpmrQnwoNbXxqviRPZbqCr+r/v7Pyy0wJCoi9N7s7n7777fM7DLvpaVZN6A9EsmhsoqpwZuEskIfOasqoigt8mkZC6EgqSyHk6H10wRVJc0FqdfVlKw4QERZY50xoXpyLPaQZilRnCaZrDM2G5WEm6BGkwrmL0os/cZa+ZYWowkT5bAfTyghSaXidR4C/zUqF/pWBLOVNrkPQyDNHiH2DE1dQ3383jbjuEEIBYGO+dkJqmbodcyDURkth/He4wW8O2jQgdNVOCSYM+A88m2N8P2+1cVrLfe0AQHyIZg9MVW4Jy6NvHvglo6rvgLevbi5XovDQzbCFIHhKvQFel1KIG8iS4yRDx9HPYHhdny6CpgJz7DkI44GJjSViWBeIKarW/THCgHBBdrkPPwJHGXo7Xdf1flIqjaFS5kRx4EJUYR8cAzS8NHUNtHleB5pu4Vto9dVhugWQOEFbUqQxFnBmU2ZVHj38CRsyWT2MSUbNWtzYnajLwNj3OAExXqtXV6iDKxeVCvxnWB1KBJR96B31LK+6bMf+BwOVxr9P9gf0IlBAMNcLkQ0/C3w9b23eMsodDBifDy4ZdeztdEBWcJw8VFzUqdJhexZba3ti1reulla+Se5ya0djqBDUabR9B429IUf7Zx5F33DvWsJ1OVsSh8t2Aykc8NufhhUMw3q8Qsr1SkLsvF3V2yFh4HkLvIf5PlBJC6TvxB9PFO9/jEdzZ7BhpLtdmzOBzMIHwVS+VqJr94LkqFd6ZkLJNbsiuycPxqpqR0zNye0dOW1ujLz0jDwOmk29MZ4uSKX5y7ll/gtZsBTow/lIl3tIQ2P5UuJMf99g+7c/cAx7Eedyjjc4jUVi4WGM1+atLiR8UDh1+PTgHXpWzroYkwi8O+55EmTGVnsXxRlbr1QQvjfgefbHaSCPwrudlcX81mU6ub2KO+vLtE9AFXSDtGhTumEQtPpfciHT70gatG/NeTqZN2tZkUx6kijF/DQqvD9STAvUq7lFsgH3kO8DfsrpHLl07RzQutaPw4dGG7M+jJjUGuzqix/8kMbW7
