### ISSUE TITLE
[Bug Report][3.1.1] Selects are not removing default content when item template is used.

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#16490]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a list item to the #items slot

### Expected Behavior
Remove default content

### Actual Behavior
Slot and default content appear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdU1tugzAQvMrK/aCVeKhp+4OSKD1HyAcPp3UDtmUb0gpx967NI5CoPUCEBKxnPLszsvcteZcybGpKYrI2tJJlaug24QDrJkildL+uqFLGh6oHayNygRuooRAz3Ks3CXHfhExEpI6q8GBB5LRSCal9sGW34CYGhUumTWAxaIKM8WLjOb438RJjn7a1nFCl566Dx7HJ0yjliJMwjhHNlOfjRQvXI3XuDoGZb01Lmpv7c9z7urS8OMYcMpGJ7/vzPDrbLpWGM4+E6dC7M+Guw0IKS50rJg1oamoLs0oKZaAFRY/QwVGJCjy8X54l54Jr4xLRsIG9l3o+eJl95d7BSvdiKEN80ivhCDL80oLjBW3tJJi+AzD/GNyKXcMOtk7IpzFSx1FUc3n6CNFgtEMsUjU3rKJBIardS7gKX9+iAnOar4dUV0GmxFlThR0T4s/EDTv+/NVggFH3OVz1ssOSlbyRilC/oSpQlBdUUfXv3FfcxexX2M38tmeX8A6zLBk/6asYc+0i3GPwHel80ksj2fkgh19/qZjJ)

<img width="534" alt="Screenshot 2023-01-21 at 5 22 00 PM" src="https://user-images.githubusercontent.com/819940/213889396-55e2fc45-9f43-411e-ab14-f8795762c0f9.png">

**Comment by Flamenco** [comment]
OK, so after research, this is caused by the props flowing into the v-list-item.  When I filter out all but the event handlers, the duplicate item goes away.

https://play.vuetifyjs.com/#eNrNk02P0zAQhv/KyBzSSo0DC1yqpto9wBE40xQpSR3Wu4lt2ZMuKMp/Z2wnq7QruCHtoYrnw49n3pkeBnZnDD/3gm3ZDkVn2hLFvlAAu3NaGhOOwehKqSYL4LNsUVhxgm9WGzd7KavWXaUr/Qu2kmguL1j4Fgz8N0WJrcgTVXYieYbRxflleOPT8sTV2lxkABRI+FY6TH0KnNNKqlOeNKGSUMYq3OLGn9fJfhii7dO5LZ+4f3Ucl8xdtkAu68kupJhT5+bIObu/aHxFYiwE+M/9T2XE5aDQ83Z4I+7NBYRMV1tpEJzA3odlZ7RFGMCKBkZorO4goUVMPMX/ml7VKLWC5YjjcIf4sCWUVfC1ehA1ck/4pNBK4VaTS0xmvMUjaCUR8j2N4PD2yLsS6/tV9kOrw136/Zit12vPJpUKVWvlMIzKQQ4H7x+8htukTMbNfK4W5zqhi0ffemyW2mQbFjsliQx/cFrRPy3UT9sQArQPW5g6Khgp4O2C3SMat82yXpnHn5ykz24pltleoexEetLd7Xt+wz98zE40waWfC9elldVPTlh6sWCbBRxl8/tvD0xh4r7jNxE7uTzyBSoj/lnY1Ap1ov23/6z7Kvei9qvYi/qniYykZSvVo7uSsXZBwgMJP7JxwyKakkMf7PgHj5SZow==

**Comment by KaelWD** [comment]
Yes, props includes title. You can use the title slot to override it: https://play.vuetifyjs.com/#eNrdU9tugzAM/RUre2CTuGjd9lK1VfcdpQ9A0y0rJFFi2k2If58ToIVW2wdUSIB9Dsc+Dt407F3r+FhzNmcL5JUuM+SrVAIsjlGmtX/1QZUJ2UcdWKMqFH3AkcNc0Ld2mTL/TNmZSNRBFR4cSJxGG6VtCC5sJ9wUSbgUFiOHwTHKhdwtA88P4AEFll1zHdldTeOosclObQuPQ62nQdETz/rUTTIqMO4ymZgfqGOTBIzsW17yAu/WeGfvUvJinMaRq1x93631weBqqtQvAhHOm+D/EL8jEykKbWGERrAcaweLSiuD0IDhe2hhb1QFAS1d4MiFkhb9YCwsYRNkQQhB7m5FsHXSnRjJsJB1StSCjr+skrS1jeuEDsEDdAxz8BmXowouTtknorbzJKmlPnzEZDBZE5aYWqKoeLRT1folnsWvb8mO5jTOx9xWUW7UyXJDFVMWjsRR7H/+KtDDpPsczzrZPuUkb6QS0j9yExkud9xw82/fV9xJ71fYTf+uZpvKlmZZCnmwV2MsrB/hhgbfsjZknTSRvQ+2/QVcMZ/4

**Comment by Flamenco** [comment]
I think you are missing my point.  I am passing props into v-list-item because the click events will not work otherwise.  Overriding the slot should replace the contents, but they get duplicated.

**Comment by KaelWD** [comment]
No the title slot is on v-list-item. `<v-list-item #title>` is the same as `<v-list-item><template #title>`

**Comment by Flamenco** [comment]
This  broken on your documentation site

https://next.vuetifyjs.com/en/components/selects/#selection

BTW, any reason you chose to change `item` by adding `raw` to it, instead of sending `raw` in as another slot property?

It really made my migration a PITA.  Would have been much better if I could have just aliased all my props, like this:

```html
<template #items={raw:item}>
```

Instead of having to update every reference to `item` in every slot.
```html
<template #items={item}>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
</template
```

**Comment by MetRonnie** [comment]
Any chance the https://github.com/vuetifyjs/vuetify/labels/C%3A%20VSelect label could be added to this? Would have saved me from opening a duplicate

**Comment by KaelWD** [comment]
@MetRonnie I generally search with keywords rather than labels, this issue comes up under "select item slot"

**Comment by corrspt** [comment]
Just adding a comment as it may help other people via Google, who know. I've also bumped into this using v-autocomplete and fixed with a `:title=""` 

[Playground with Buggy Behaviour and Fixed](https://play.vuetifyjs.com/#eNrVU7Fu2zAQ/ZWrOsgBJHs37AIN0KBDh07tEGeg7TNLgCYJ8qgmEPQ9AfIb+bEcqSiW4mzJkkU63r33ePdIXrdF8LvFd+fmTcRiWawIj04Lwm8bA7BqauFcDvNiZw0JZdA/p3pEJLuzzELCIQ2wVKwU1ptCNEJpsdX4SxgZhcSwKU4wrqBm1GWU8g7+oA/KmjEgydSkSCOjCG/prNgIHVMx/0/Vlxa5yWEo+JoYjG0ztQLnrQvQbYoROg+lVaA6YaCpt8rsmZOxjIS2Z8+9+D9PHUHXwWox4oy3XkwM7VNTzz7cyyt1i/tP4SUMzbwiwVseT1TfbXdKT69zBubbPlHhZdh55QgCUuwfgzo66wla8HioIClHYss7OHh7hJKfUpmIwCUTCI5BwjphZ+VP1NrCX+v1/kt5MQadny1zBunZ7ALWfPP63nkMsI74dBPmepi0heTUEsofRrI5/8oK8jlyBg0vDlpIjuW2hK46I115YR7vhQoj2sGfaBy/RfvNRkQZHx8C1HDpRVB6JLAdCXD8InDTTw5sCkVvhmlSrmNXVovecja76CoTtc6fmydm1Hev)
