### ISSUE TITLE
Date-picker Internationalization is not working for Persian local 'fa-AF' properly.

### ISSUE THREAD

**Issue by MustafaHussaini** [vuetifyjs/vuetify#1649]
### Versions

Vue 2.x, Vuetify 0.15

### What is expected ?

Date-picker Internationalization is not working properly with 'fa-AF' local, It is just changing the header of Data-picker to 'fa-AF' Local not the date-table and bounded value, they are in 'en-us' local.
A codepen template can be found [https://codepen.io/MUHU/pen/eEqGRb]

**Comment by jacekkarczmarczyk** [comment]
@MustafaHussaini 
I"m not familiar with farsi script, can you check if what I'm doing is correct?

I don't know why there is "۱۳۹۵" in the header and "۱۳۹۶" below. In english version there is "2017" everywhere. Please advise

![image](https://user-images.githubusercontent.com/15625235/30247268-b5b1b152-9610-11e7-9e50-13d2fb9a6bd1.png)
