### ISSUE TITLE
left tooltip weird at right edge of screen

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#165]
https://1drv.ms/u/s!AmVMv5w2NmcaxhxRsg255AnHLOlH

Download that app.  Go to Purchase in sidebar, click Purchase Now button, move the mouse to the X on the right top for tooltip.

**Comment by johnleider** [comment]
I downloaded the app but it would not run on my computer. Any other way I can see this?

**Comment by johnleider** [comment]
From what you showed me in gitter, this will only be able to be fixed once tooltips moves to a javascript implementation.

**Comment by johnleider** [comment]
Closing this in favor of #139
