### ISSUE TITLE
[Bug Report][3.1.2] v-list outlined variant adds outline to v-list-items

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#16502]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a list and add outlined variaint

### Expected Behavior
Only the list should be outlined

### Actual Behavior
The list items are outlined too.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUstuwjAQ/BXXF7cSsVVoLyggeusf9EA4mMRQF79kO6kqlH/vOgkohVL1ltmZzO6MvD7iF+doUws8x3kU2ikexbIwCOVNxp3rPjuguTQD6rCSIaJS8RAWxPFsRlDDveQmLoito5JGVOSsP/+RSViy5Dkbwxuq7b9U5e+q0/QUAOA5QQJ9tpyNMgMMpZcuoiBinWipnfURHZEXO9SinbcaESiLJHFpDTSgwx4tEn9PXoVSFr1Zr6o78pDMezswwhPce8ERjn4Ea6DvY7qlGIhQ4DnqJmkGOxIu8HuMLswZq4077GlpNVsBx3xtotQiq6xezeiUPj2zCsKO51QEnW29/QzCw8YCT0bmUe6+bi0YaPB9pNPedhglyysrBv6N8JkXphJe+D/vvtD+uP2Cu7o/7WwL00KX8LoO4aLGMnQVrjdJ0k5wbw3iLgfefAOaXvTx)

**Comment by KaelWD** [comment]
v-list itself doesn't actually have variants, it just passes the prop to the items

**Comment by Flamenco** [comment]
LOL This is so broken, even on your documentation site, and you are just going to sweep it under the rug.

https://next.vuetifyjs.com/en/components/selects/#selection


BTW, any reason you chose to change `item` by adding `raw` to it, instead of sending `raw` in as another slot property?

It really made my migration a PITA.  Would have been much better if I could have just aliased all my props, like this:

```html
<template #items={raw:item}>
```

Instead of having to update every reference to `item` in every slot.
```html
<template #items={item}>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
<div>{{item.raw}}</div>
</template
```

**Comment by Flamenco** [comment]
Didn't it used to have an outline property?  If so, did you remove it and not add variants to the list itself?

**Comment by KaelWD** [comment]
> even on your documentation site

Yeah shit like that is why v3 isn't the main site yet. 

> Would have been much better if I could have just aliased all my props

Object destructure does work deeply: `{ item: { raw: item }`

> Didn't it used to have an outline property

It was based on v-sheet, now it's very barebones and only has a background color. You can put it in a card or sheet if you want more options.

**Comment by Flamenco** [comment]
You should really push the added props to item as top level slot props...

It's a very difficult refactor otherwise.

**Comment by KaelWD** [comment]
Might be able to do that as part of https://github.com/vuetifyjs/eslint-plugin-vuetify/issues/28

**Comment by Flamenco** [comment]
I would have added what you call `item` as a new property called `context`, and left `item` as what you now call `item.raw` .  I like that you added in all the new fields, but it breaks convention.

Probably too late for that now though.  😬
