### ISSUE TITLE
[Bug Report][3.1.2] V-Divider Props "Color" not working

### ISSUE THREAD

**Issue by FrontDev07Axas** [vuetifyjs/vuetify#16517]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
v-divider color="primary"

### Expected Behavior
color will change

### Actual Behavior
does not change or becomes transparent

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9lE1vm0AQhv/KdnOglQyrOu0hlmOl6qX3HnoIOWBY6Nbsh2YX0sryf+8MYIKd2ImiKJx45+OZYdjZ2y3/5lzSNpIv+DJI7eosyFVqGFu2ceZc99oJnSkzqE7nGRSjHi1xUKHuAfvnu60tMOUjw+4tbJSpJlniRNqIk3/DAQ0dhWpVIYHlBL5O+UVZlilfEWtwHWZ4l5nVT6slI9pSdDo1z1B9k+fS+1eAz2IrkP/emnlxNS+Lq8u3xjpQOoOz3bbxOpgnEiaVupCTperMe8xcV/ELqlHTYwrRJ0kv/LZT6e86uIdTPz3de+t+5VCOO0ei38almGwpSp+DcoF5GRpyK+0sBLZlIEu2YyVYzSJc74iCc2t8YNpX7Jr8H6Mfsq4t+2WhLj5Enwje4xDEZ7xnYRMu+eOtwRtiS72kgwNXY8E6C9mwBumU/w7B+YUQjXGbKsmtFjfoE9CYoLSMC6tvLpN58uWrKJQPU3sivY7XYO+9BKyY8tkEHlSJA326wOBG7udk3mMHEyEfoQTyWwkxSIP/RcLZvo9iD3o/8j3qn2ruUrPDWdbKbPzRGHO6XRbs9o5CdjPeozG4+w5+9x+bJ8UI)

**Comment by floroz** [comment]
The `thickness` prop is missing.

[Playground](https://play.vuetifyjs.com/#eNq9lE1P4zAQhv+K1xwCUhMvBXaXqlSsuHDnwAFzCIlTTOMPjd0CqvrfGSdpSAMBCSGSS96Z8fNObI1v1vS/tclqKeiETr1Qtky9mHFNyHQVp9ZWn5VQqdSNqnSWQt7qNhJ76csasH0uTGmASBdp8mhgIfW8s4oNLGtx4snv0DCRy5XMBZAsgM843SuKglPi72W20MI5DB1yOgvspnSX4GyqZ1dGCRLoU1Zprj9xgfnd/u8Rvgc9r/EXvL7mdPTdTnun4yI/ReyOzfGP/dDJtzmVaQUcdPrzgdOwW50b8GxNw4LYglQpPPds//7YVv4bdHqdse4sbaPbAUfZTngQ9exPWedOQOkykNYTJ/wypKWyBjxZExAF2ZACjCIRXiZRKM6Mdp4oNydnIb8fXYqyNOTaQJn/ig4CvMYhiI5ozcImbPLgjMb7aB164U3CcTohVSTE0CNoTu+9t27C2FLbxTzJjGLnmGOw1F4qEedGnR8l4+T4hOXS+W48EU7Fd2AenQB05HTUgXtZ4FG+b9CkkXuYjGtsEwrINyiG/JWAGITGcxHwYd+92p3ee7k3/QfPDdcb3MtS6oXrbWPmqi28uQ0lmxGt0Vhc/Qe9fQH/hd9b)

**Comment by shailstar** [comment]
Actually, We were setting background-color property instead of color property by color attribute in v-divider.
