### ISSUE TITLE
[Documentation] Broken links (locale not included in url)

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#16529]
### Environment

**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on `/api/v-menu` link.

### Expected Behavior
Point to https://next.vuetifyjs.com/en/api/v-menu/#props

### Actual Behavior
Points to https://next.vuetifyjs.com/api/v-menu/#props

### Reproduction Link
[https://next.vuetifyjs.com/en/api/v-select/#props-menu-props](https://next.vuetifyjs.com/en/api/v-select/#props-menu-props)

### Other comments
E.g. https://github.com/vuetifyjs/vuetify/blob/next/packages/api-generator/src/locale/en/v-select.json#L21

This is one example, there are probably more.

**Comment by MajesticPotatoe** [comment]
can you try clearing cache

**Comment by MajesticPotatoe** [comment]
nvm, was looking in the wrong place (you didnt specify till the what link to click so i assumed the component page lol)
