### ISSUE TITLE
[Bug Report][3.1.2] V-file-input multiple not working

### ISSUE THREAD

**Issue by FrontDev07Axas** [vuetifyjs/vuetify#16523]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
v-file-input multiple v-model="files" 

### Expected Behavior
update:modelValue, witho two or more items

### Actual Behavior
single file modelValue

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kd1SgzAQhV8lkxt1ppCx6k2ndeoD+ASlFwiLxuZvkgV1GN7dDVCkrcoVu3vync3JruVPzqVNDXzF1wjaqRzhMTOMrZskd67/7QudSzNWfV3kvmSFVdZvMu681Ln/yvikmDQJSlQD8vg91wqlU8ACKCiQNUklFSTSuBpn58UfgAkMn3jCpcEPiOmjC+1uS1C0ZpyGjDMxp002c9yxOzXalvWnWdeNkZBiyiQWQ1prMUuRylB46ZBuinUcS+2sR9YyDxXrWOWtZlcU/1UUF9YEHG02UXF9E4EDgg7zBR/Ok7FL34M19Gpt9M/GAV1uxfpO7BE31hl/Q3RhJURt3OE1LawWW5oJXxuUGpLS6u1dukzvH0QpA877KQSdvHj7EcCTY8YXMzjKip78d4NxTNzbdDlgx1ZEXqAE8RvwiQdTggf/795n2pPdz2YX+0dPesGOslTSHMJZjEXoI9zto6Rb8AFN4v4efP8NhkIHug==)

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/214596147-5c906402-9148-4d16-acad-2a996831e768.png)


Am i missing something?

**Comment by FrontDev07Axas** [comment]
Y, something)
i got this also on firefox v109
![image](https://user-images.githubusercontent.com/108451669/214777811-b737812d-46cd-4873-87c0-78d27d42c951.png)
![image](https://user-images.githubusercontent.com/108451669/214777329-130e1cc2-dd4f-4fec-9f60-d17468ed3ed3.png)

**Comment by jacekkarczmarczyk** [comment]
_hm, i thought i've closed it already with the explanation, but it seems i've just added labels, anyway the explanation is the following:_

Looks like you're just selecting a single file instead of multitple files. VFileInput works basically the same way as native input
