### ISSUE TITLE
[Bug Report][3.1.2] `v-select/v-combobox/v-autocomplete` not work properly when you use it inside Navigation Drawer

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16537]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use the navigation drawer with `v-select` components. Note: do not put the navigation drawer inside the `v-layout` components

### Expected Behavior
The v-select component's dropdown position should be proper and visible.

### Actual Behavior
The `v-select` component's dropdown position is not proper and not visible if it has long content on the first load.

### Reproduction Link
[https://codepen.io/alokvishu/pen/rNrKxeR?editors=1010](https://codepen.io/alokvishu/pen/rNrKxeR?editors=1010)
![chrome-capture-2023-0-27](https://user-images.githubusercontent.com/80033712/215025512-100cf23c-84fc-419b-8214-9178cb41449d.gif)

**Comment by websitevirtuoso** [comment]
Yes I think need to implemen prop [contained](https://next.vuetifyjs.com/en/api/v-snackbar/#props-contained)
Or use custom css and apply css rules to fix it

**Comment by KaelWD** [comment]
This has been fixed, your codepen is still using 3.0.6

**Comment by alokVishu** [comment]
Thanks @KaelWD,

For fixing the same issue in the latest one. But there is a background color missing select? Please correct me if i doing anything wrong.

![Screenshot 2023-02-14 at 11 08 57 AM](https://user-images.githubusercontent.com/80033712/218649109-6d8a37f4-6a84-410e-9da9-d0238bb70a4e.png)

**Comment by KaelWD** [comment]
#16615
