### ISSUE TITLE
[Bug Report][3.1.2] v-click-outside not working in v-menu component

### ISSUE THREAD

**Issue by MetRonnie** [vuetifyjs/vuetify#16557]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 2.6.10
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Using the `v-click-outside` directive on a `v-menu` component doesn't work.
```
<v-menu
  v-click-outside="{ handler: onClickOutside }"
>
```
Adding a `debugger` breakpoint inside `this.onClickOutside()` reveals it never gets triggered.

### Expected Behavior
The `v-click-outside` handler gets run when clicking outside the menu

### Actual Behavior
The handler is never run

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

### Other comments
I tried to create a minimal reproduceable example in the playground but it kept crashing

**Comment by nekosaur** [comment]
What are you trying to do? v-menu already has click-outside functionality by default

**Comment by MetRonnie** [comment]
We have a directive that adds event listeners to multiple elements which open the menu when clicked. However, the normal behaviour of v-menu is to close even if clicking on another one of these elements, whereas we would want the menu to update its position and contents instead of closing
