### ISSUE TITLE
[Bug Report][3.1.3] [Vuetify] getUid must be called from inside a setup function

### ISSUE THREAD

**Issue by jaketig** [vuetifyjs/vuetify#16558]
### Environment
**Vuetify Version:** 3.1.3
**Last working version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add a `<v-list>` element to a `<v-app-bar>` 

### Expected Behavior
no errors should be thrown

### Actual Behavior
```Error: [Vuetify] getUid must be called from inside a setup function``` is thrown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Usty2zAM/BUOL7lY4rRpLx434147/YMwB0qCFDriY0hIaerxvwfUI5HkJPZFAJa7S3Dvz/y393nfAd/zA4LxrUK4k5axQ58p74fPoTBK26mah1mhgsQKbNT48kvy0pnaBVRFC5KzmqhY4UIFgc5JHP90stUR35gmttTLNBlY9hnzATzYKlO9QhVI4hHRx70QZWWTa9T1yynmJCy0UQ1EcXKPNve2kXzNhBpbIII/NGd/QZOrLSR2xYxKLMfGuaaFRL5GrryT+3ltrM9i63BPmyHPG9RwywLttkuy+n+SjEa17dZS+vUqaGWRIAj/8COELp2lsal0ZsB2WeWe7TXu7iAGB1v7YvXs7+3Foywmc3/Zont7VUJgYv3QSQwh4lY41VN85nxR5y1g05i+V96ojGXQHlkE7NJYG09xY2cWoGYXVgdn2A2l4iadHLGE4js+AknB56foLGX9nITkNIiS79nQST0iSPV71jrrn5ohY0eaidBZ1AZoy+Z4m3/Pf/wUFS1k2c8hmqwI7jlCIEXJdwvylNnPBKYx8X7Lb0faqZUor6gE8fcQskB5g5AS/YXvDXblfTO78p80L9JeaJettk9xs8YyDiu8f0iQy46P1AQe7sEfXgFAWFye)

### Other comments
Adding a v-list element to a v-app-bar causes the UI to break and throws errors in the console.

**Comment by nekosaur** [comment]
Hmmm

This https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/composables/nested/nested.ts#L220 is a no no, right? It's ultimately calling `getCurrentInstance` inside a computed.

**Comment by men232** [comment]
HotFix: provide any "value" except null or undefined into v-list-item
