### ISSUE TITLE
Date picker not rendering correctly on Mozilla Firefox on Android

### ISSUE THREAD

**Issue by slypsy** [vuetifyjs/vuetify#1655]
1. Open Mozilla Firefox on any Android device.
2. Open https://vuetifyjs.com/components/pickers
3. Check date picker and see how style of the text that shows date is broken

### Versions
Latest vue and vuetify versions, any Android OS, on latest Mozilla Firefox mobile browser

### What is expected ?
Datepicker to look the same as in other mobile browsers (Chrome, Safari,...)

### What is actually happening ?
Please check how the text style is broken in following image:
![thumbnail_screenshot_2017-09-04-13-28-25](https://user-images.githubusercontent.com/16080103/30249363-611cb7c4-963b-11e7-93fc-fb5932a7a8bf.jpg)

### Reproduction Link
https://vuetifyjs.com/components/pickers on Android device with latest Mozilla Firefox mobile browser

**Comment by johnleider** [comment]
Oh that looks terrible. Also didn't know firefox had a mobile browser.

**Comment by jacekkarczmarczyk** [comment]
This issue is fixed, but please don't close it till I integrate it with month picker PR, ty

**Comment by jacekkarczmarczyk** [comment]
Can be closed now
