### ISSUE TITLE
[Bug Report][3.1.2] Focus on v-text-field with label and empty modelValue does not scroll page on Safari

### ISSUE THREAD

**Issue by klorophyl** [vuetifyjs/vuetify#16553]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 2.6.14
**Vue Version:** 3.2.45
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
- Add a v-text-field with a label and an empty value
- Click on it on mobile Safari

### Expected Behavior
The window should scroll down to make the text field visible

### Actual Behavior
The window does not scroll down

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kM1uwjAQhF/F8oVWIjGl9IICove+AeYQkg24+E+2Q1uhvHvXTlqloHJKZmfzzWS3F/pqbX5ugS5pEUBZWQZYc01Icc5Ka9NrEqoUelBJV6WryRHE4RhWi9lsXbB+Nt4J8BmyRoCsCQJMDXLFqfIHToks90m9xSen7CcIKb9JUfQdCjbqhtJXTthAPIQ22kJZ4wK5EAcN6UjjjCIT/KlJXK6M9oFgKllF/0G3Uj5GZA/Bz+mU9gSMtvm7NxqvcYkN+GB4TpckTeIMyVFzegzB+iVjrbanQ14ZxTboMdfqIBRktVGb53yeL15YLXwYz3PwKts78+HBYSKn0xE8iObrv4DBRu5TPu+xwygib1AM+WdwmQNdgwN3t/fV7p/uV95N/5jZcd3hLaXQJ391xsqnE253caWb0h6Ny+k/6O4brLHW0Q==)

### Other comments
The behaviour is correct if there is no label, or if the value is not empty (I think the animation of the label prevent the native Safari scroll)

**Comment by Swoox** [comment]
I had a similar issue https://github.com/vuetifyjs/vuetify/issues/18219.
