### ISSUE TITLE
[Bug Report][3.1.3] Global default doesn't work with v-data-table

### ISSUE THREAD

**Issue by Employee87** [vuetifyjs/vuetify#16567]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
```
export default createVuetify(
  {
    defaults: {
      VDataTable: {
        elevation: 1,
      },
      VBtn: {
        color:"primary"
      }
    },
  }
);
```

### Expected Behavior
It puts an elevation-1 on the data table

### Actual Behavior
No elevation is added

**Comment by KaelWD** [comment]
VDataTable doesn't have an elevation prop
