### ISSUE TITLE
[Bug Report][3.1.2] v-text-field: Cannot read properties of undefined (reading '$el')

### ISSUE THREAD

**Issue by simonNozaki** [vuetifyjs/vuetify#16566]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 110.0
**OS:** Mac OS 10.15

### Steps to reproduce
# Target line
See https://github.com/simonNozaki/cords/blob/main/components/EditCardForm.vue#L6

# Prerequisite
I'm upgrading from vue2/nuxt2 to vue3/nuxt3, and now target components is consisted of legacy options api. The `created` hook in that component fetch items from firestore(firebase), and display it on html. Through that process the component substitute `variables` in `data`.

# Reproduction
The error on title of this issue happen on reload a page that has the component above. The error stacktrace is:

```
VField.tsx:147 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$el')
    at watch.flush (VField.tsx:147:63)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at Array.job (runtime-core.esm-bundler.js:1794:17)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
    at flushJobs (runtime-core.esm-bundler.js:397:9)
```

```
// ...
    watch(isActive, val => {
      if (hasLabel.value) {
        const el: HTMLElement = labelRef.value!.$el
        const targetEl: HTMLElement = floatingLabelRef.value!.$el
        const rect = nullifyTransforms(el)
        const targetRect = targetEl.getBoundingClientRect()
// ...
```

I guess the code expanded inline check the element nullablity (and I cannot the code of vuetiy repository...)

### Expected Behavior
Create input tag by `v-text-filed` with v-model

### Actual Behavior
The error happen(See the error in reproduction)

### Reproduction Link
[https://github.com/simonNozaki/cords/blob/main/components/EditCardForm.vue](https://github.com/simonNozaki/cords/blob/main/components/EditCardForm.vue)

### Other comments
If someone that see this issue tell me the parts of `floatingLabelRef.value!.$el` , I'll want to create a patch by myself! Thanks.

**Comment by arthurM2x** [comment]
Had a similar error, it was due to the `variant` property being set to an unknown value ('default')
