### ISSUE TITLE
v-overlay example results in [Vue warn] cannot run an inactive effect scope.

### ISSUE THREAD

**Issue by mbiciunas** [vuetifyjs/vuetify#16569]
I'm using the v-hover / v-overlay example from [https://next.vuetifyjs.com/en/components/overlays/](https://next.vuetifyjs.com/en/components/overlays/) under Examples - Misc - Advanced.

It works, but I get a console error: "[Vue warn] cannot run an inactive effect scope." every time the mouse exits the overlay.  This also happens in the codepen attached to the example on the vuetify component page.  I made a copy of it at: [https://codepen.io/mbiciunas/pen/dyjQRjZ](https://codepen.io/mbiciunas/pen/dyjQRjZ).

I'm not sure if the issue is on v-hover or v-overlay but examples shouldn't be throwing warnings - it really throws off us newbies.

**Comment by AllanChain** [comment]
It's a problem of `v-overlay`. Here is a simplified repro: https://codepen.io/allanchain/pen/oNMRLdR. A warning is printed to the console every time the overlay is toggled off.

**Comment by mbiciunas** [comment]
I ran your codepen and saw the message once only.  I forked it and updated with sample code from my app - [https://codepen.io/mbiciunas/pen/PoBvQYe](https://codepen.io/mbiciunas/pen/PoBvQYe).  

Every time you exit the card (after activating the hover) you see the warning message.  

Oddly, the code from the vuetify website doesn't seem to trigger the issue when run on the website, but when moved to a codepen [https://codepen.io/mbiciunas/pen/QWBRQQL](https://codepen.io/mbiciunas/pen/QWBRQQL) it does.

**Comment by AllanChain** [comment]
> Oddly, the code from the vuetify website doesn't seem to trigger the issue

On CodePen, we are running a development build of Vue, while the Vuetify website is running a production build. Vue warnings only appear in development builds.

**Comment by mbiciunas** [comment]
I think the key question is:  Does the warning that v-overlay throw constitute a defect that needs to be fixed?  
- If it does, there should be enough CodePen's above to replicate the error and address the issue.  
- If it doesn't, then we can close this ticket out.

Personally, I would prefer to see these warnings dealt with since it will chronically confuse new users - as it did for me.  Especially as it presents with sample code that users will assume works without warnings or errors.  As it is, I would like to confirm that the warning isn't something I need to worry about so I can move on with my development.

**Comment by mbiciunas** [comment]
Awesome @KaelWD.  Looking forward to picking this up in the next release.
