### ISSUE TITLE
[Feature Request] Vuetify v3 add VOverlay & VDialog overlay-color and overlay-opacity props

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#16580]
### Problem to solve
Let's the user change the overlay color and opacity without using workarounds. Currently you need to use css/scss, which is not always ideal. This feature will also bring it back like it was in Vuetify v2.

### Proposed solution
Add overlay-color and overlay-opacity props back. 

Vuetify v2 Reference:
https://vuetifyjs.com/en/api/v-dialog/#props-overlay-color
https://vuetifyjs.com/en/api/v-dialog/#props-overlay-opacity

```
<v-dialog
  v-model="dialog"
  overlay-color="#000"
  overlay-opacity=".75"
>
```

**Comment by santiagoaloi** [comment]
`Scrim prop`
Accepts true/false to enable background, and string to define color.

**Comment by webdevnerdstuff** [comment]
Thank you for the clarification. I have also put in a pull request to update the documentation since it was missing.

https://github.com/vuetifyjs/vuetify/pull/16779
