### ISSUE TITLE
[Bug Report][3.1.3] VTooltip "parent" activator does not work for VIcon

### ISSUE THREAD

**Issue by binaryfunt** [vuetifyjs/vuetify#16587]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Edge 108.0.1462.76
**OS:** Windows 10

### Steps to reproduce
```vue
<v-icon class="ma-8">
        mdi-account
        <v-tooltip activator="parent">
        	Lorem ipsum
        </v-tooltip>
      </v-icon>
```

### Expected Behavior
Tooltip works

### Actual Behavior
No tooltip rendered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UctuwjAQ/BXLZ2KrpSotoii99w8wB+OY1iR+yHZSIcS/dx1CGkKp1ENPya5nZmd3Vgf86hxpaonneBGldhWPcskMQosm4861v22huTJdhdD5C30lrEGi4iG8MKx59sRwD0NIFyrjQtjaxO8msKK1VVQOcRFVw6P1QHbcS4AN6Sy+WS81Ui7UeiBAe4UenHrJy08eN3FsEV1A+0WWA79Xgv9oHAyeLw1Vf+pUnEJY0EE4zOAJVtpZHwHryC5YA/kdEoV1D4HhOWo7qQcBp5rhjxhdmFNaG1e+E2E1zeGNethXaZkVVudTck8eZrRQIQ77RAadbbz9DNLDRIYnA/GotvtbA7pn0L0j05Ns10qSV1IU9BvpMzhpIb30v/oeYS+8j95u+4fML4eIwpBQ7h0XJSlkQ3NA0F3IZ7DB8yPDiXhk5ggpVMqUYRSACO3xV2f9P51EK0NagcRepyHHCT6tBeNaAp5seRXk+gtOUi6s)

### Other comments
In the playground link, I show that the parent activator works for `VBtn` but not `VIcon`. The parent activator is a much nicer syntax than the "props" activator so it would be great if you could get this working for `VIcon`

**Comment by KaelWD** [comment]
Unfortunately v-icon's default slot is already being used in a way that makes it impractical to render other elements in it. If only `<v-icon icon="mdi-account">` was supported then we could do this, but it isn't currently possible.
