### ISSUE TITLE
[Bug Report][3.1.3] Color picker not showing up as expected

### ISSUE THREAD

**Issue by SafeShows** [vuetifyjs/vuetify#16598]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Edge 109.0.1518.78
**OS:** Windows 10

### Steps to reproduce
I don't know if it can be reproduced as in play.vuetifyjs.com it worked as expected

### Expected Behavior
The sliders on the color picker should show up as in the docs
![image](https://user-images.githubusercontent.com/49234603/217036754-70e00258-d3de-4cf2-a425-eff6992f7501.png)

### Actual Behavior
But actually, it just showed up in the primary color and the slider selector dots didn't move/update
![image](https://user-images.githubusercontent.com/49234603/217036788-ef25af0e-4136-4938-9bdf-838ae5bb3597.png)

### Reproduction Link
[https://github.com/SafeShows/BattleBridge](https://github.com/SafeShows/BattleBridge)

### Other comments
the sliders are able to update the color in the canvas but the sliders themselves show the primary color and not the rainbow/color hue line and the alpha slider also doesn't show the background correctly

**Comment by SafeShows** [comment]
![2023-02-06 19-07-28](https://user-images.githubusercontent.com/49234603/217037770-93314c49-67e6-49ed-a502-4969abafd96c.gif)

**Comment by SafeShows** [comment]
there's also a difference in classes (left is my app and right is the docs)
![image](https://user-images.githubusercontent.com/49234603/217040231-1912e0df-2487-4745-9c89-8bbbf2a485a2.png)

**Comment by nekosaur** [comment]
You will have to provide a smaller reproduction than an entire laravel project.

**Comment by SafeShows** [comment]
@nekosaur as I said I don't know if it can be reproduced as in play.vuetifyjs.com it worked as expected

**Comment by SafeShows** [comment]
maybe it's something with my config?
![image](https://user-images.githubusercontent.com/49234603/217301906-ab87f7d2-9567-49aa-87f8-6728eb0c9faf.png)
![image](https://user-images.githubusercontent.com/49234603/217301938-bb443d4a-444b-48bb-9f9a-7357c62f551a.png)

**Comment by SafeShows** [comment]
Well downgrading to 3.0.0 fixed the slider dot positions but the bg color is still messed up

**Comment by KaelWD** [comment]
Color is probably from https://github.com/vuetifyjs/vuetify/blob/5872b0fb985b6664f43233ca2bc1e7f476fabe01/packages/vuetify/src/blueprints/md2.ts#L34, and position doesn't seem to work if you don't have a `<v-app>`

**Comment by SafeShows** [comment]
I fixed it by removing the md2 blueprint in createVuetify

**Comment by SafeShows** [comment]
> You will have to provide a smaller reproduction than an entire laravel project.

@nekosaur I think it can be reproduced by adding the md2 blueprint to createVuetify

**Comment by webdevnerdstuff** [comment]
I'm not sure if this is the same bug or not, or related, but I actually had something like this happen when using `Teleport`. If I teleported to the `body` or `#app` it would cause the sider to behave like your example above. But if I teleported it to anything under and including `.v-application` it did not have this issue. I would think it should still work if teleported to the body no?

Here is a replication link:

https://play.vuetifyjs.com/#eNqdUstu2zAQ/BWWPbgFTFFNWhRQlSD9gaKHopcoB1laJYzFB0jKqWH437skJUd2HkByMbw7uzOzI17v6E9jss0AtKClB2n62sNlpQgpN6w2Jv6NhayFGiusPzBGfmlF/kAPRlsPLWHsEd6wRvfaMiOaNVjS9LVzFxXttF7VtqIE6XQLPbbSxN+6HwD7D6L1d9g9z/OKXpb8mOfAf2TjBQtTm3iNhCvdbpFxQt/m0R8Ufr/HbcknL1OaOHmIMxQp6JLPPgCWrrHCeOLADwEWMp6zIxY6sied1ZIs8MstwnCjlcNTnzNKLsLGp8XHPM8Xn39Ms7PgZxNdnCh50h59+G2f3kRIkezSEa1w6HVbkK6Hf7gTeveD86LbYgzKg/IFafAX7Iiaum2FumVem4Kc5SZt7aPcKEGXNJ2J+Zjs3mmF7zIKViPgKlpMFiqK54e6onfeG1dwPiizvs0aLfkVYtwOygsJrNXy6jw7y75+5+jbz/sZOMlWVj84sKhY0eWMPFzzksAII++X7FuiHVuB8gkVR/4NWGZBtWABX9grvk9mj7yfYE/8j6HuMcteqLU7ibFxMcLrydqbDpNCZZEgbN8Ekf2SJnMoFxfozX86cGzH

**Comment by KaelWD** [comment]
Color: #16689
Position: #16586

**Comment by CUHKfreshman** [comment]
It seems that '\<v-slider>' should be included in '\<v-app>\<v-main>...\</v-main>\</v-app>'. Reproduction code for play.vuetifyjs.com:
```
<template> 
  <v-slider></v-slider>
  <v-app><v-main><v-slider></v-slider></v-main></v-app>
    
</template>

<script setup>
</script>
```
or:

> https://play.vuetifyjs.com/#eNqdUMtOwzAQ/BXjS0BqbEoPSFWoyo0/4ND0kCZua+qXvE4RqvLv7DahKi1w4OT1zuzMzi4O/DkEsW8Vn/IiKRtMldSMlY6xYp+D0Y2Ks0KeygGoQpjhYyvt6L3mUdmjWBCbBhnqFvLkUjr8Qh11SAxUaomkbfAxsQOLas06to7esgzXy4hceweJWdiwJ8JvsxdljGevPprmJrsj8V4OhfiI91q4RhBv4B0mPNAW5QBAyafs2KEeetC/5NuUAkylbF3YbUTtrZwjJmPrkrYqb7ydT8RE3OeVCdtKPMpGQzqHhQKbr6J/BxXRuOSjM4+k1x+/+Qwwyo/F+KHXHXq5qVZAwleCEl32KuZROby7in+GuOD+FOSCchWGrLvSdXhfo90OLk5bw/Gsi68N/5HyKEHzS7LpRvzblujbT/LlJ4qR62s=

**Comment by YannFFT** [comment]
I still have this problem on the v-slider using Nuxt 3.4 and Vuetify 3.1.14.
It works if I add <v-app> to my layout.
How can I make it work without wrapping everything inside <v-app> ?
