### ISSUE TITLE
[Bug Report][3.1.3] Vite Error "Failed to resolve entry for package vuetify" when importing Sass Module

### ISSUE THREAD

**Issue by nikolasdas** [vuetifyjs/vuetify#16593]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
- Create a blank project with Vite 4, Vue 3, Sass and Vuetify 3
- Add the Vuetify Sass Module with `@use "vuetify"`

### Expected Behavior
The project should run normally

### Actual Behavior
```
Error: Failed to resolve entry for package "vuetify". The package may have incorrect main/module/exports specified in its package.json.
```

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-jdslxa?file=src/style.scss](https://stackblitz.com/edit/vitejs-vite-jdslxa?file=src/style.scss)

**Comment by craigrileyuk** [comment]
I'm getting this one as well, also from trying to import a config SCSS file before `createVuetify`:

```
// vuetify-config.scss
@use 'vuetify' with (
  $color-pack: false,
  $utilities: false,
  $reset: false,
);
```

which is imported from:

```js
import "./vuetify-config.scss";
import { aliases, mdi } from "vuetify/iconsets/mdi-svg";
import { createVuetify } from "vuetify";

export default createVuetify({
    icons: {
        defaultSet: "mdi",
        aliases,
        sets: {
            mdi,
        },
    },
});
```

and results in:

```
throw new Error(`Failed to resolve entry for package "${id}". ` +
          ^

Error: Failed to resolve entry for package "vuetify". The package may have incorrect main/module/exports specified in its package.json.
```

Have confirmed that the import of the SCSS file is the only thing that causes the error

**Comment by KaelWD** [comment]
Caused by https://github.com/vitejs/vite/pull/11595, vite now has no way to resolve a different sass entry without https://github.com/vitejs/vite/pull/7817

**Comment by KaelWD** [comment]
I opened https://github.com/vitejs/vite/issues/11947

**Comment by craigrileyuk** [comment]
Yep, further to your comment in the Vite repo @KaelWD , using:

```
@use 'vuetify/lib/styles/main.sass' with (
  $color-pack: false,
  $utilities: false,
  $reset: false,
);
```

Seems to be the way to go.

**Comment by Maxim-Mazurok** [comment]
To be clear, this fixed it for me: replace in my `main.scss`: `@use "vuetify" with (` with `@use "vuetify/lib/styles/main.sass" with (` as per comments above

**Comment by KaelWD** [comment]
You can use vite 4.0 or 4.2-beta, this only exists with vite 4.1
