### ISSUE TITLE
[Documentation] The website https://next.vuetifyjs.com/ is blank.

### ISSUE THREAD

**Issue by rachitpant** [vuetifyjs/vuetify#16609]
### Environment

**Browsers:** Firefox 109.0
**OS:** Mac OS 10.15

### Steps to reproduce
The page loads blank both in firefox and chrome. I was able to load it once in chrome , but now it loads blank as well.

### Expected Behavior
The website works

### Actual Behavior
The website doesn't work.

### Reproduction Link
[https://next.vuetifyjs.com/](https://next.vuetifyjs.com/)

**Comment by johnleider** [comment]
Trying clearing your cache. You can monitor the documentation up status here: https://status.vuetifyjs.com/

**Comment by rachitpant** [comment]
@johnleider Its still not working . I have tried clearing cache , and have tried this on two different browsers : Firefox and chrome.

Here is the screenshot in chrome.
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/1474415/217354841-3bea0ecb-c02f-4b3d-81bf-9c79d0dfd70b.png">

And here is the screenshot in firefox.
![image](https://user-images.githubusercontent.com/1474415/217355039-d116574b-eaf7-464b-9393-78b68c2c54ee.png)

**Comment by johnleider** [comment]
Come to our discord so we can debug. https://community.vuetifyjs.com
