### ISSUE TITLE
[Bug Report][3.1.3] VMenu close-on-content-click is not respected when open-on-focus is present

### ISSUE THREAD

**Issue by fahmifitu** [vuetifyjs/vuetify#16608]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Focus or click on the menu
- Click on the card

### Expected Behavior
it should not close when the prop `close-on-content-click` is false

### Actual Behavior
it closes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtUj1v2zAQ/SssO7gFTEm108VIinQokCFAxw5RBlo6WawpkiBPSgxD/z1HyXZkJ8gUePG7j/fePephz387l3Qt8BW/Rmiclgi/csPYdSekc8PfATRSmQMaMZiWWQdGWCMqW7SBrQZYgpa7m5xnOWerQtsAcaKwBsGgKLQqttStpA6Q8xNjjid59lUWqDqJ1tPgnjlvXWD9MJzj8UcWEJ5RVAp0yciPJWGab8KGhDuxVqYkOCxTIZ0qpWeXHoqdKKQvWQ1qUyNtLrLMPdPmkyqxfsWnlbh09+f+/u+UeCQ5pkYwxjSFxxQjGPM9c0MwFF45ZAGwjW3VOOuR7ZmHivWs8rZhM3qwWRymVAMyOpndxP632R1obdk/63X5ZfY9ko90RMTnfOQiEy75H6yhN99HL/mhQTmt2FCJNdKIOOc1ogurNG2N226SwjbpLfVS3xpUDYjSNrfLZJlkQmpXy+QqLVXAaTuB0Ii1t08BPAnnfD7RQFXtPtKJ/dTEN9E70vmRXNEX1olFtlhmi+xnko1yh0mh5TpEvTc6KYl34IUHU4IH/+FtF7Pv3Xcx8ubGKN3npqfYtTLbcJF4EYa0H44OP+/4gTnSPkb1fs7PzJOd93j44wuF/VF0)

**Comment by KaelWD** [comment]
`open-on-focus` also means "close on blur", if you add `@mousedown.prevent` it doesn't blur the input anymore.
