### ISSUE TITLE
[Bug Report][3.1.3] rounded=false doesn't work

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#16601]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use `<vBtn rounded={false}/>` - won't work because border-radius is only disabled when rounaded strictly equals to zero, see https://github.com/vuetifyjs/vuetify/blob/11ddd2dd21630f539913a117b501ac759da00c86/packages/vuetify/src/composables/rounded.ts#L39

### Expected Behavior
`false` works just like `0` (zero)

### Actual Behavior
`false` doesn't work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUctuwjAQ/BXXl7QSsVvREwqI3voHPWAOIdmAS/yQ7VBVKP/etRMqCm0lbp6d3ZnZ9epIX6xlhw7ojBYBlG3LAAuhCSkOeWlteiagSqlHlPAmaOJMp2uo54I2ZetB0EUAHwqe2NMoou/ZCAbVgp+5IfSVkzYQD6GLtFTWuECOxEFDetI4o0iGMbPYXBntA1F+S+aRv89eoW0NeTOure+yhyg+yKEQndBBC0NY9u6Nxk2PMYsYCS/ojKRKrKFHxILuQrB+xnmn7X7LKqP4EjnuOh2kgrw2ajllU/aYl63dleyZ19KHc5qBV/nGmQ8PDo0FnZx5BNl8/uUz0ij/xKaD7FiKkldSHPUP4HIH+BcO3L/xL3p/W+Gi5WqNaN0L3eNlW6n3/uKolU8HXZ0S3rSfkpolgTi9jib9hP7IiK5pjq6/APeL6YI=)

**Comment by taozhiyu** [comment]
According to the [documentation](https://next.vuetifyjs.com/en/styles/border-radius/#removing-border-radius), you should use `rounded="0"`

playground: [here](https://play.vuetifyjs.com/?preview=false#eNqVUctuwjAQ/BXXl7QSsanoCQVEb/2DHjCHkBhwiR+yN1QVyr937YSKhrZSb56d3ZnZ9fpMn51jp1bSOS1AateUIJfCEFKc8tK59ExAl8oMKOEtGOJta2pZLwSdCroEGaDgibmMIfqai6BXLPiVE8JQeeWABAltpJV21gM5Ey93pCM7bzXJMGIWmytrAhAd9mQR+fvsRTaNJa/WN/Vd9hDFezkUohPaa2EIx96CNbjlOWYRAxEEnZNUiTX0iFjQA4ALc85b4457VlnNV8hx3xpQWua11asZm7FpXjbuULInXqsA1zSTQedbb9+D9Ggs6OTKA9Tu4zefgUb5RzbrZYdSlLyR4qh/kj73Ev/BS/9n/FHvTyuMWm7WiNadMB1etlHmGEZHrUI66PqS8F/7aWVYEojTm2jSTei3jOia5ujmExPw56c=)

**Comment by Maxim-Mazurok** [comment]
> Well, you're right, the documentation says that Boolean values are supported
> 
> [next.vuetifyjs.com/en/api/v-btn/#props-rounded](https://next.vuetifyjs.com/en/api/v-btn/#props-rounded)

Exactly, and the default value in docs is `false`, but `undefined` in the actual code:
https://github.com/vuetifyjs/vuetify/blob/395ddd7d840012c28c71a92dba1082f7ef9e2cdc/packages/vuetify/src/composables/rounded.ts#L23

**Comment by santiagoaloi** [comment]
`<vBtn rounded={false}/>` that isn't a valid Vue syntax.

`:rounded="false" shouldn't be used much really, as its its default value. I don't believe `false` and 0 are meant to do the same thing. 

0 is not radius, however `false` seems to imply don't set any border radius, leave the default radius value.

I will confirm this with the rest of the team shortly.

**Comment by Maxim-Mazurok** [comment]
> `<vBtn rounded={false}/>` that isn't a valid Vue syntax.

This is a valid Vue JSX syntax

> I don't believe `false` and 0 are meant to do the same thing.

I can kinda see this now... However, I was reading it as `rounded=false` meaning that `"button is rounded" is a false statement

> I will confirm this with the rest of the team shortly.

Thank you :) It may be just a docs fix to clear the confusion...

**Comment by santiagoaloi** [comment]
After bringing this up with the team, `false` should act as 0 , but this is a buggy behavior, the intention is to remove the false prop value and leave the default as `undefined`.

**Comment by viT-1** [comment]
Also defaults in [global configuration](https://vuetifyjs.com/en/features/global-configuration/) prop "rounded: 0" is not worked.
