### ISSUE TITLE
[Bug Report][3.1.3] Wrong font-size for text within v-dialog when wrapped with v-card

### ISSUE THREAD

**Issue by mediafreakch** [vuetifyjs/vuetify#16606]
### Environment
**Vuetify Version:** 3.1.3
**Last working version:** 2.6.13
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at the vuetify playground example. `v-card` content outside of `v-dialog` has `font-size: 14px;`, while same snippet's text within v-dialog has `font-size: 16px;`

```vue
<v-dialog>
  <v-card>
     <v-card-text>My text</v-card-text>
  </v-card>
</v-dialog>
```

### Expected Behavior
Font-size is 14px in both examples

### Actual Behavior
Font-size is 16px in v-dialog

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01v2zAM/SuELt2A2Mba7hK4QYbtvB12rHuQbbrRoi9IcrouyH8fJTub7XQDth4ChI/ke+QTfX9kH6zNDz2yNSsDKit5wE2lAcpDxq1Nf1OguNDQSO79XcUsz24rNiZTuhVcmkegOtOipBK/M0+fEjgpjJUNd+1v4IxkAb+HCVyFr5ymQYg4lPVGaC9aLIt6A6YDDoNgDp9NoKIdQmd0AC9+YD4hL15m/6XKmyCM9otUHTRsGyma/WwRuIOOS4+00EdpPA2TSmfNZ8El8TkxA4YdRmhi5v9YZPoQDXq1OReDTt/uz8YE15Mv0BhpXDwQJxR3zxEZT0Y9Z9dk3BeLehxvbl+M4o0Nx0fBcH1lMblKCn3jhKVVMPTDcQpljQtwBIcdnKBzRsEVHfRVTMZfQ89ADdNhqfRNesm3UWCgJDK2YgMbDWLzb95o+iqOiWdM+IqtISERI5UYV2wXgvXroui13T/mjVHFlnKF63UQCrPWqO1Nfp3fvi9a4cMUz9GrrHbmyaMjxYqtJuRBdOTgywJjmnjf5TcD7Qhlktc+8l7wFSRyQJc51C06dH8dflE7W2CRu1giap4qfSJDpdB7v/Cy8cnH+/No/75dYojtD1HltGLDdKSXOtjDT3CciwQ=)

**Comment by christophermiles** [comment]
I am seeing this too.

**Comment by KozakoPolako** [comment]
Is that expected behavior or it's a bug?
