### ISSUE TITLE
[Bug Report][3.1.3] @click:clear  not working

### ISSUE THREAD

**Issue by laurentMBisom** [vuetifyjs/vuetify#16611]
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Firefox 109.0
**OS:** Mac OS 10.15

### Steps to reproduce
on each component type form : VSelect, VTextField, VAutocomplete, ... with value. 
the props "clearable", show the default clear button. 
click on clear button
use @click:clear=

### Expected Behavior
expected clear the field

### Actual Behavior
nothing happened

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMtuwjAQ/BXLJ5BIrJZKlSitqLj02DvhYMgGXPyS7VAqlH/v2klQCmqlXmyvZ2dmZ1dn+mptfqyBzug8gLKSB3gpNCHzY8atTc9UKC50V6U6wClklQBZEgRNCfK5oMrvCkq2ErjjGwmsp7MBPxat8pwNHLH0WydswLdQ1rhAzqSESmhYGqw16EAaUjmjSEFx4oI+RRacUi928lqme8gYndMEmiuYIe2dB4G/S+7Kgk4ilOCSBz4ak7aXOAi1031FCIaK3DeQ0pCwB4fWiUtIky48m3GMcwlAJ7TNgLFt/uGNxv0mwaIDfEFnvUUXJ5rsQ7B+xlit7WGXb41iC8SYq3UQCrLSqMU0v88fHlkpfBj+5+BVtnHm04NDx8uISTyI6us3gw5G3bt82sp2X5nkGx91b/QYmhzBZQ50iftwfw5/1fsjwBV2EyJ6xvXiQqXQB3+1y61Pe1z1o/0/XVKI9HV0aSa0nQ79EoOuvwGN5QsM)

**Comment by KaelWD** [comment]
Works for me

**Comment by laurentMBisom** [comment]
on _play.vuetifyjs.com_, it works for me too. But not on my project.
I'm copy the `app.vue` and paste in mine. 
And clear field is not working. 
I've got the same vue & vuetify version as in _play.vuetifyjs.com._

**Comment by KaelWD** [comment]
Can't do anything about it if I can't see it happening

**Comment by laurentMBisom** [comment]
Thanks, I'm keeping looking for find issue or reproduce elsewhere
