### ISSUE TITLE
[Bug Report][3.1.4] VOverlay: Safari does not support requestIdleCallback

### ISSUE THREAD

**Issue by oskarlh** [vuetifyjs/vuetify#16613]
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 3.0.5 or some version after that
**Vue Version:** 3.2.47
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
Load a page with `<v-overlay scroll-strategy="reposition" :model-value="true" />` in Safari

### Expected Behavior
No errors in the console

### Actual Behavior
"[Vue warn]: Unhandled error during execution of watcher callback" "" " at <VOverlay" "scroll-strategy='reposition'" "model-value=true" ">" "" " at <VApp>" "" " at <App>"

OR

ReferenceError: Can't find variable: requestIdleCallback
XC — scrollStrategies.mjs:91

### Reproduction Link
[https://codepen.io/oskarlh-the-typescripter/pen/qByGxKV?editors=1111](https://codepen.io/oskarlh-the-typescripter/pen/qByGxKV?editors=1111)

### Other comments
v-overlay uses requestIdleCallback which is not available in Safari. Not sure which version didn't have this problem, but I think this is what introduced the error: https://github.com/vuetifyjs/vuetify/commit/a11138e5f75a9ef81bb3b39daeb8bd1cb07997cb#diff-6507d7b6032f95f9d2db83134495ea858ececf937b3601da1152d0e3052f30f0R128-R147

**Comment by KaelWD** [comment]
Guess I'm reverting that then. requestIdleCallback has been around for fuckin ages, didn't think I had to check compatibility there.

**Comment by oskarlh** [comment]
That's the beauty of the web, there's always surprises

**Comment by gabrieljbaker** [comment]
@KaelWD , while this error is now gone, on the latest it's been replaced by this one on Safari : 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/5530378/218836726-6c35e6a8-9738-4802-9087-d4818c45ad7a.png">

**Comment by gabrieljbaker** [comment]
@KaelWD , should I file a new issue for this one?

**Comment by suterma** [comment]
Sorry to bother, but I see no pull request (nor branch) associated. Did a fix for this go into production yet? Maybe with 4.1.6?

**Comment by suterma** [comment]
Note: A fix has been made on master: https://github.com/vuetifyjs/vuetify/commit/9a4caf331d05c31a1223712802babe7eec707d72 and has been included in Release 3.1.6, according to the release notes: https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.6
