### ISSUE TITLE
[Bug Report][3.1.4] v-autocomplete in v-navigation-drawer has transparent background

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#16615]
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 3.1.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 109.0
**OS:** Windows 10

### Steps to reproduce
Click the autocomplete.

### Expected Behavior
The dropdown menu should be opaque, hiding what is behind it.

### Actual Behavior
The dropdown menu is transparent.

### Reproduction Link
[https://codepen.io/drhouse82/pen/RwBmyGG?editors=101](https://codepen.io/drhouse82/pen/RwBmyGG?editors=101)

**Comment by KaelWD** [comment]
Probably a5539ba721a29e42c4e51f764d9944a6f51c2e28 somehow?
Was also like this from beta 8 (6d602b275f58f0ee136f5ff28f974480fdfc2aa6) until beta 11 (26c6a37990f357bc3f8a909e9ca7a46b90059d27)
