### ISSUE TITLE
[Bug Report][3.1.4] Elements with overlays not present in DOM initially attached to wrong overlay containers

### ISSUE THREAD

**Issue by luka-mikec** [vuetifyjs/vuetify#16610]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 109.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Open the reproduction link
2. Click "Change attach target (click me first)"
3. Click "Show v-select (click me second)"
4. Click on the v-select that has just appeared 

### Expected Behavior
The v-select's menu is visible. Changing attach target should only affect the v-menu, but not the v-select, which is a completely unrelated component in this code.

### Actual Behavior
The overlay belonging to v-select is teleported to the v-menu's overlay. As the v-menu's attach target has `display: none;`, the v-select's list is not shown.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU8Fuo0AM/RWLHmilALvqnmhatdrTnvcYomgCJswGZkYzhiqK8u/rAdIEml2pOUTYfn7PfpjVMXgzJu5aDNJgSdiYWhC+ZApg2UXCmP6xDxoh1RgNMaoWUkEk8uo5C3y4GaINCbtDyoIPODecueFO5CQ7Qdpy1xGM1cbBaQLu+bekgP+lKhjXo7IACunEtsbi5ddOaYtAlXSwbYm0WiZ9z7VmMllo+L1BLR197MFNfvLLYoXsQHrJYZfovAs4OtTIeR6BOQ8pKK3wiQvJtLmLZMkwV+n3jcMa85kRXTRkIZU8nmPoKszDBYRFuJ6yJUx37bh35DWvZb6/6Tc8Q3g3mTpk5Z+VUDuEIQ8j8r5ngQahlNbRw9y7udjVMqxCtkVm/s1J3nZMXygd5loVM87e6PMF+WC4rckr4tDlVhpiCmqH05ON0ZbgCBZLOEFpdQMhn2vo4QCs5Bg+GY+R96WoHT48XSA37Zogl8kgzrLBIhh0eWQT/3Fa8ddx9GTZWOBbTKHP+BzP4+MsqIiMS5OkVWa/i3PdJK9cS2yrSDYYFbp5fYwf42+RqE0l4h/8hh1dl2N0TbS1+t2hZeEsWFxpkCwP/9IZy0z//Uw7pjzlJ6qE+Tu0kUVVoEX73/Fn2FsrzCCf1vDSp0yd2Nlaqr2bmZq73tDVecIv7ddIFfcEvnvtRU6LYDIjq/Z9wfov8QydgQ==)

### Other comments
Maybe has something to do with this line: https://github.com/vuetifyjs/vuetify/blob/8275c89302a0ebc9a0dc64654c8f1ffa83f054b7/packages/vuetify/src/composables/teleport.ts#L24

It seems to always pick the first `.v-overlay-container` in the DOM, but it might not be the desired one. Note that it seems important that the attach target has changed before showing the new element (v-select in this case), otherwise it works as expected.

**Comment by KaelWD** [comment]
#16409

@nekosaur I guess that answers your WeakMap question.
