### ISSUE TITLE
[Feature Request] VTextArea missing height prop to set height of Text Area Explicitly

### ISSUE THREAD

**Issue by prajjwalarora** [vuetifyjs/vuetify#16616]
### Problem to solve
This will allow users to set the Height Explicitly of Text Area.

### Proposed solution
Implantation as of  Vuetify 2
For Ref-
https://vuetifyjs.com/en/api/v-textarea/#props-height

**Comment by santiagoaloi** [comment]
This could be a feature request, I'll bring it up to the team.
