### ISSUE TITLE
Clearable not working properly with autocomplete

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#1662]
The select is not cleared until it loose focus when using both the clearable and the autocomplete props.
It works if you focus another element before clearing the select.

### Versions
0.15.3

### What is expected ?
The input should be cleared and the items should not be filtered when the clearable button is triggered.

### What is actually happening ?
The items stays filtered with the last selected value.

### Reproduction Link
https://codepen.io/anon/pen/eEqXjZ

**Comment by johnleider** [comment]
The reproduction steps for this is to select a value and clear without blurring. If you blur then click clear it works properly. (notes for me)
