### ISSUE TITLE
[Bug Report][3.1.4] "color" and "active-color" do the same thing for VList, but none of them lets you set the color for the list when its inactive

### ISSUE THREAD

**Issue by simenness** [vuetifyjs/vuetify#16624]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
poke around at the v-list in the Vuetify Play areas (link)

### Expected Behavior
`active-color` would be the one that makes the item change color when active,
and `color` being the one that sets the color for the entire VList.

### Actual Behavior
`active-color` and `color` seem to the exact same, though "active-color" gets priority.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVM1u2zAMfhVNF7dAbKNttgFGOnTADnuAYTtEOXgWnWrRjyHJ7orA7z5KchInxQoM2LGHQCY/8uMXSuR6T4cevGifi1+OVlSozlhP9qSxUHv4njAyktYaRbIpNmOaafgdQxujnScTQO7PE6/2TBPiH0FBhaQc2rqX/luyM17bXUbGBdPjNdN0QT93XYFMqGPlQXUSiT4FgtWQ110XP6OhaqEnK9pSBAm5Mhxk5UBC44HfM3r4/GIaxygZaitq7REwvZdCA0dn3XgxQN4YaSwiT7XVQm8ROHiEbg2jx3LHgrlAjScvQQFtTLjiplmIayI0wS8sPA+qdvAcSC+8Qy17QD8mFAJlncBZYebnpXMvvEz9OQXsscmRgozjHFmVr2WeoafGTt7/1em3hp43NJjHlxyM9MZX5ezto+kaKzpPHPg+wMcJtdDO5xJnEvXiLw3k/EJwKjH4ar3BKZvHhGYitt4LXt2Mi3DcpuMuHct0vE/Hh3ETBKVc5bYTbfYVpDTkh7GSv8uwxKpMklEsznTSi3+0ww1jNM523Al4YxHA28TNkBrCwi4KNqOP3neuKsted7tt0RhVPiBW2l57oSDnRj3cFbfF8mPJsaFzfwFO5T+teXJgsSKjuF6O5GEn/a3ABCPvTbFMtIfViJQvqErkH8DmFjQHC/ZV3RexZ9ovsBf6Q018eiP2Eidp5y7a2LjYwvVB2j/9MSV0EQlCNt7uSMcFTeKwXEygmz8bDfS+)

**Comment by KaelWD** [comment]
Related: #16478
Broken since beta.1: 0897cd98c97e667f52a000d56d18111c781d4dbc

**Comment by yuwu9145** [comment]
Also related to #16686
