### ISSUE TITLE
[Bug Report][3.1.2] Focus on v-chip slot inside v-file-input

### ISSUE THREAD

**Issue by neevyaa** [vuetifyjs/vuetify#16623]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 100.0.4896.60
**OS:** Linux x86_64

### Steps to reproduce
Have chip with closable button slot inside a v-file-input

### Expected Behavior
focus should be on chip close button and click:close event should be called

### Actual Behavior
file selection dialog box opens when focus is near chip close button

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVE1z0zAQ/StCl6QzsT0tcDEtEy4MJ27Aoe5BkdetiL5GH6Ehk//OSnISJ2GYIRdHu2/f7nte+XFHP1lbbyLQlt4HUFayAB87Tcj9pmLW5r/5oJjQ4ymfA7yGahAge4JJ04N86Kjyzx0lzRGXgIOQUAltYyjRNoOrDZMRsCSlfUdLbhltjwMUyPcREa00rP88xeGYHF6M7MEh4FsGkK2JjvSGRwU6HKGSrfJoqZ6UMcaMijIIK2GkdGBB95XgRiclvagss+C4FPZQ0XIJzLGVzIMz6aFkDi4dDERHvDSh9SCBB5EJdyQp/coUeLLv6MnKSdFgkpz5AbjAeXt4vcHHqRj9bdewRVxOTpiy2/wFxz0GCPHidxrWKyblQUb5ZWOmAW5k7m+dUMxtz9FcMu+TL1DdXWaMT5ZMY0t0ja/RLuNTd3yZECC9gXlRNGWYzE/I7mQT2e8nypoi7WRbc7atV4FUcNq8I2ayx+lQNvysFI+eO2ED8RBiSgtljQtkRxwMZE8GZxSZ4ZWZJRbcFh/yzJ48JMT88enmQ6dLHO/DGJ19ASkN+WGc7N/MEqLTQ9R5O8hkw+d4L1qmtzdkl+gzcZ3vChLhEwvRlmPlpbMt0VGtwF2X197iOxlhC3KbRkCmpL7oRaV0QYtYdMnWP73R+FnIRLhtOYHr1xbqFEMT0rmjLyFY3zZN1Hb9XHOjmiXmGhd1ELgxvVHLt/Vd/e590wsfpvEavKpWzvzy4LBjRxcT8iAGXMO/NxjTyHtb3xXaMVThZvvEe8XXYJMNuMrhRQcH7p/DX2DPBFzkrkSknmjuHg2VQq/9hZfcZx8fD6P9v7rMkMqfUpf9gpbpsF+uoE9/ACdG5pw=)

**Comment by nekosaur** [comment]
This will not work regardless. The `v-file-input` is a simple wrapper around `<input type="file">` which does not support partial removal of selected files.
