### ISSUE TITLE
[Feature Request] [3.1.4] v-data-table-server disable pagination

### ISSUE THREAD

**Issue by lmunch** [vuetifyjs/vuetify#16626]
### Problem to solve
With vuetify 2 you could disable and hide the pagination. I cannot seem to find a similar functionality with v-data-table-server.

### Proposed solution
Implement something similar as in vuetify 2.

Thanks

**Comment by MetRonnie** [comment]
I have found that setting the `items-per-page` prop to `-1` and adding
```
<!-- Hide footer: -->
<template v-slot:bottom></template>
```
works to remove the footer

**Comment by lmunch** [comment]
That worked perfectly. Thanks a lot.

**Comment by MetRonnie** [comment]
Although I do think it's worth keeping the issue open because at least it would be good to have this documented and/or they might bring back a prop to disabled the footer
