### ISSUE TITLE
[Bug Report][2.6.14] Keyboard is not shown on IOS devices on v-text-field/v-textarea on focus/autofocus

### ISSUE THREAD

**Issue by Oleksii14** [vuetifyjs/vuetify#16633]
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.7.14
**Browsers:** Safari, Mozilla Firefox, Google Chrome, Microsoft Edge, Internet Explorer, Opera
**OS:** iOS

### Steps to reproduce
1. Use IOS device
2. Visit reproduction link
3. See the keyboard is not showing up

### Expected Behavior
When providing autofocus property, the input should be focused correctly on IOS devices (apart from the styling, the keyboard must be visible)

### Actual Behavior
The input receives appropriate styling, but the keyboard is not showing up

### Reproduction Link
[https://codesandbox.io/s/nameless-monad-o3d20b?file=/src/App.vue](https://codesandbox.io/s/nameless-monad-o3d20b?file=/src/App.vue)

### Other comments
Found working hack - https://stackoverflow.com/questions/54424729/ios-show-keyboard-on-input-focus

See first answer

**Comment by KaelWD** [comment]
> remember, this function must be called from a user interaction (like a click-handler)

Safari doesn't allow the keyboard to open without user interaction.

**Comment by Oleksii14** [comment]
I attached a hack that can be used under the hood. Why can't it be used?

@KaelWD

**Comment by Oleksii14** [comment]
@KaelWD I updated the sandbox with a working hack for IOS. Please check and let me know.

**Comment by Oleksii14** [comment]
Referencing to https://github.com/vuetifyjs/vuetify/blob/v2-stable/packages/vuetify/src/components/VTextField/VTextField.ts#L523

The suggested solution will look something like this:

```ts
tryAutofocus () {
   /* code from reference ... */
   
   // this.$refs.input.focus()

   const input = this.$refs.input
   const temporaryElement = document.createElement("input");
   temporaryElement.style.position = "fixed";
   temporaryElement.style.left = "-999px";
   /* disables auto zoom */
   temporaryElement.style.fontSize = "16px";
   document.body.appendChild(temporaryElement);
   temporaryElement.focus();

   setTimeout(() => {
     input?.focus();
     document.body.removeChild(temporaryElement);
   }, 100);
},
```
