### ISSUE TITLE
[Bug Report][3.1.4] v-text-field - change event not handled by component (Vuetify 2 regression)

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#16637]
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
In Vuetify 2, one could use the `change` event on v-text-field to mimic the behavior of the .lazy modifier on `input` HTML elements.

In Vuetify 3, v-text-field no longer has specific handling for `change`, so it instead falls to the HTML `input` element and receives an `Event` as a payload, rather than the value of the text field like it did in Vuetify 2.

### Expected Behavior
`change` event on v-text-field is emitted with the text field's value

### Actual Behavior
`change` event on v-text-field is emitted with the raw Event object

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUcuu0zAQ/ZXBm7ZSEgOXVWlREULiA5BYNF34JpPG3Pgh2wlcRfl3xnlUoReQ2CQez5kz5xyfe/bR2qxrke3ZIaCyjQj4IdcAhy4V1o7HsVBC6rka64A/Q1pJbEqgpimxOeZM+WvO4FTUQl/xaPSn8QD8Nrj8vz5bBKkh1AiRCSYm8Wg6TEDoMnY0WIfeA+qADoyDokHhoDJF629K6rc3coB53+eORvz+huErUN9P6ibMMMwG+cphLCbvB77KhEpfOGkDeAxtbEtljQvQg8MqoY8oguwQBqicUbChWDdxrDDaB6Bs4BiR280XbBoD34xryleb3QJY6xqRE932fNm9z3XVaiqNhiXVrRVOKKRodn1UvR7PbOvrFSDX5PPAJ/kknCVs0k6mbfbdG03vP7Lkc8PnbA/jTbwjJ7HOWR2C9XvOW22frllhFD9Rj7tWB6kwLY06PWQP2etUNLYW2TteSh/W7Qy9Sh+d+eHR0eKcJasdQVbPf9szt4n+zUI7X0XKF1Sc+Dt0qUNdokP3T/l32D9ZuIO8sBFXU8YDJdtI/eTvQi38GOh5Ufhf/pTU2UgQpy9xyZCw3zTS1nGOXX4B0Q1GWQ==)

**Comment by Hendrik-Mueller-Overzone** [comment]
I do have the same issue and currently have to workaround, by listening to the `update:focused` event while also listening to the `update:modelValue` event to check, wether a change of the value has actually happened.

It would be nice, if this would work like it did in Vuetify 2)

**Comment by throrin19** [comment]
Same need here. Or add the possibility to user the `.lazy` modifier to simplify all of it
