### ISSUE TITLE
[Bug Report][3.1.4] VSelect : on click clear triggers @update:model-value 2 times in a row 

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#16638]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click clear icon on VSelect

### Expected Behavior
@update:model-value to be called one time with `null` (or `[]` for multiple).

### Actual Behavior
@update:model-value is called 2 times in a row.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUUtu2zAQvcqAGzuIJSZNV4JsuOgZujK9oKVxooY/kJSLQtDdO6TlRnE+QFbSzJt5n+FuYD+cK089sorVEbVTMuJGGID6VEjn8m8utOzMVIlIdUCFTYRK2xZVcZKqx7Vg+SsYOPShCxFNLBqF0kPVEXugid396tueJnJbHhTCtnctqV4xWfMrtwXb1PwiNxkAOK8EqGAYmujHcfJJk/+NpuIcoeazaFSGxncuQsDYJ7jTzvoIA3g8wghHbzUs6CaLNNxYEyJkV7BOE8vFz5xI4+LmZYBMTPDdrHsJQdASb2C9gSE5S6BVWCr7uJwnXQHSMuHRl1nx9lYYilbzs2PyylbsbJdyuvJ3sIZeLpOKCQiC0VWml2IUI9WCPcXoQsV5b9zzY9lYzbeEcd+b2GksWqu3D+VDeVdI5Z5k+Z239H5zuMSgi4O3fwJ6Eia3M43YHf9+pDPBRH9/oZ1ahZKHkHjf8HESOaEvPJoWPfpPM1zNvpfjauRNliRNhx7pvKozz+Hqsk3IV91dHH49ZGZI6/ukMq7YK5MkmxfZ/h8P+DN5)

**Comment by OleksiiBrylin** [comment]
I have the same issue for 3.9.7 vuetify.

**Comment by J-Sek** [comment]
> I have the same issue for 3.9.7 vuetify.

#21522
