### ISSUE TITLE
[Bug Report][3.1.4] v-slider step wrong rounding/decimals

### ISSUE THREAD

**Issue by SeriousFresh** [vuetifyjs/vuetify#16634]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.41
**Browsers:** Firefox 109.0
**OS:** Windows 10

### Steps to reproduce
Problem when using v-slider with initial value=1.001, step=1, max=10.001, min=1.001
Move slider to see unexpected values.
Use plus and minus buttons to see expected values.

### Expected Behavior
Expected jumps: 2.001, 3.001, 4.001...

### Actual Behavior
Actual jumps: 2, 3, 4...

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVttu20YQ/ZUBgSZSLVFS4idVdt1bgDwYfUhRoAjzsCKH4trkLsFdSjIM/XtnL7xKTm2gNmxydmfOnDmzF359Dn4py3BfY7AONhqLMmcabyMBsNnPWVnaV2sUjAtvWVvlPMEKaEImmN9EQVxXFQr9N8trjAJYF1zQKP23Bjsagx2NoTSWZJlHFLSYhNoQgDhnSpFLyeZLijDZpF6XFZYokn7Efr7VorMB7uKcx48G3fL7HeMKC6IVBZ3X7XyzsIFdPYtB7UMyPjup8cbkn8Wl5FevSU4uDqMbanphfqzIa3h+7ot+OnXhnbOPi7T53Ww7QIB/ZA0xE6AQIcMKoazkNscCDhkKqBUXO/BtPnCdARdcc5bD3mS7WYXL5WoGtpn0NB1eLd2Yab2ddvlc7kj/cSwx1pjAQ12UCg6yzhPYInxwUR/d49o8wjAccv211rYRnk2eQyVrQeFMEaCkIogHJBjzguUKlASdYZPIuJs8lMPgW+ghfEttixnbc1kBJxBe1KYtFv8KGKWbw7bWWgrVw2jK+wyxLDl5P8m6ovcEISWgmOWxgTFqWuWURSoYzZPgpVQkacqP1tmG2sqMe1qLWHMpLiT7i6pr2sViXbM8fzKcM3kwIMConf3Moi62pJxM4X0j0vsLsPdPoOrdDpVJa/C0hDjD+LGTlv6k5Uodd5VwYZ9xJqVCq/uWWwyfNTxfl2aBtyeKMdxZM9gKZKq44qWmd16UstLwTDRSLvA3SbaghQ8nSCtZQBTQGRYFP0UCj9aT/Fid22fff/JsEgpW0O6JzNkXBTMzkjDNJlOwswAV6roSjQXQ32VrcAu/mTPrjsZam9QYu5BQNOT2RjPWyLmGpRs6EXf6bx0KWgC07DpCOuMqbDtw4+ymvUiHnJ2YTPsYqDOZEL6HuODdK5BWtAZd8aLA5IvZST6HqS7U8gtNid1kGhoXn+Ys7p7WgQ8jEV4dRauoiWLH70QNow2xphIT31EPuYjzOkE1iYIwCqbdJv954Jaj2NGhNh/FJnj8M/WhNLnqwqlVoxKozHMOJMMrKBivMQMX+SYC7HiBAMn4AoEuPfmcpbdxL6XvJ2+efp/cM52Z5k36TbG3QM/omDYtdeuUSslZUU7s0WiDqJKlDaCXVW+RjrOR68xbXExoZObO1+k4gT1P7eZ1Wc4WvmVAB3ezsSyhTndHrbObJX42RJ83fmS82GWaKtS97QE/dBts5CvwYMnCTYdvy7R1TCYN27lHncKiw5rCj51Bl5ZzoQwjFUtWKfyUS6Z7hbZiNhRmbWG0HeUnfqRDaXAWtStrrPno86t/2PAUHEj/WIXbTpp37/r1tHFe5UGUF7TX4XMfWuAtWiu1/1Ya0m0/2P6b7qZV5v+me9VDu8iWjJMpZLNor8dgFrgbki7VMnxQUtD3vGUS+QkVBe1V4C9LcwNmWpdqvVjUonzchbEsFnc0t6jo/uEFzhNZ3H0MP4TXq0XCle6Ph6iK+baSB0UX/APBeyUtuObp00sJ/DThrsJrB+uHDOQZ1ILw91jNSSDqEFbf5T3yHXAfzZ3xb6QlLXMuHtVIxlhZCb821N5UmLkPLYCJ/maSnGaBI0fpbEDw7V//LFPr)

### Other comments
I copied your code for calculating values and made proposal fix for your rounding function which you can see in the methods.
The problem actually is how you are calculating number of 'decimals'.
My suggestion is to check decimals also for max, min and initial value and choose the biggest number of decimals.

**Comment by nekosaur** [comment]
Feel free to open a PR
