### ISSUE TITLE
[Bug Report][2.6.14] Problem  v-autocomplete and genFilteredText when searching

### ISSUE THREAD

**Issue by chpo69** [vuetifyjs/vuetify#16644]
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.7.10
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Write a searching text in autocompleted control.

### Expected Behavior
Set highlighting text for all line.

### Actual Behavior
Serching produce a error :
"[Vue warn]: Error in render: 'TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'VueComponent'
    |     property '_scope' -> object with constructor 'EffectScope'
    |     property 'effects' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Watcher'
    --- property 'vm' closes the circle'

### Reproduction Link
[https://codepen.io/chpo69/pen/jOpggZL?editors=1011](https://codepen.io/chpo69/pen/jOpggZL?editors=1011)

**Comment by julien-seligmann** [comment]
Hi,

Since Vuetify v2.6.10, render highlight is done with vnodes instead of innerHTML ([4468e3c](https://github.com/vuetifyjs/vuetify/commit/4468e3c442284b512729e7b89768fd8762c2e9c1))

You can use a functional component to render the vnodes as html :
```html
<template>
...
  <v-list-item-title><v-nodes :vnodes="parent.genFilteredText(item[config.itemTextLine1])"/></v-list-item-title>
...
</template>

<script>
...
components: {
  VNodes: {
    functional: true,
    render: (h, ctx) => typeof ctx.props.vnodes == 'string' ? [ctx.props.vnodes] : ctx.props.vnodes,
  }
}
...
</script>
```

**Comment by chpo69** [comment]
Hello and thank you for your answer

I tested your answer, it works.

Reproduction Link
[https://codepen.io/chpo69/pen/jOpggZL?editors=1011](url)
