### ISSUE TITLE
[Bug Report][3.1.2] Missing Treeview Component in Vuetify 3.

### ISSUE THREAD

**Issue by alihdev** [vuetifyjs/vuetify#16643]
Missing Treeview Component in Vuetify 3.

**Comment by egeersoz** [comment]
@KaelWD Can you elaborate as to why this was closed as "not planned"? The component is a pretty major part of our application (a document management system with content organized inside nested folders) so if it goes away in v3 then so does our major reason for using Vuetify.

**Comment by KaelWD** [comment]
Because there's already #13518
