### ISSUE TITLE
[Bug Report][3.1.4] Data attribute not added to v-navigation-drawer while using scoped attribute in style tag

### ISSUE THREAD

**Issue by taozhiyu** [vuetifyjs/vuetify#16646]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
After adding the `range` attribute to the style tag, the style did not work. After testing, this is caused by the `v-navigation-drawer` not adding `data-v-*` block information, other components were not tested.

### Expected Behavior
`scoped` tag works in v-navigation-drawer

### Actual Behavior
it does not work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqVkt9OwjAUxl+l9pp2IiYmEw0+ByOhbAeorH/SdptIuPUFfEOfxHYrcQ4w8a7tOd/3+87Z5gf8ojWtK8ApnjoQumQOnjOJ0LQmTOv22F4kq/mGOa4kKQxrwCANRjAJ0qG8ZNY+ZVjs21OGowyh8d0kOiQXLDqQr3SkadJL4K83hKCvj09k3b4E1HC3RUubKw3FEhUKLJLKoUaZHSIkyLu+rqO1pjHQocuwYvluY1Qli9RA8Rgej4Ha6q4hVeV+qAFm+7RLmLWSjlj+DunDrX4bUPAIc6GVcUQwTV+tkn7zrTCLBb++FEWrDPtPE+4Z3jqnbZokldS7Dc2VSGa+lphKOi6AFErMJnRCbwkr9ZbR+6Tg1vXLFKwgK6MaC8aDMzzqMRxf769xYtnbj0+28SlYnlkl3r8GQwzIAgyYP+MPei+NMGg5GyMu+Og3W3K5s4Ol5uF/TNH8lPBf8wkuaWsQ1IsAOY7wr4ye2urw4ht5Cx3Q)

**Comment by mediafreakch** [comment]
Workaround is to use `:deep()` selector. Here's an [updated example](https://play.vuetifyjs.com/?preview=false#eNqVkl9OAjEQxq9S+6QJ7YqYmKxo8BwsCWU7QGX7J20XRMKrF/CGnsS2u0RcwMS3Tmfm+30z7XiHX4yh6xpwjocepKmYh+dCITRcE2ZMOqZAsbVYMC+0ItyyDVhkwEqmQHlUVsy5pwLLbToVuG1DqH83aBWyMxINKGQa0jA7chDCK0LQ18cncn5bAdoIv0RTV2oDfIq4BoeU9mij7QoREtubuqYiSeccwFzT1tYN2jVeZqxcLayuFc8t8Md4uY/01H8JrWv/Q49Qd0xNuAOoxcy18sSJd8gfbs1bh4J7WEijrSeSGfrqtAovkBqLNhHWmB8cFzg8UYwLvPTeuDzLamVWC1pqmY1CLrO18kIC4VqOBnRAbwmrzJLR+4wL54/TFJwkM6s3DmwAF7h3xPBivr3EadNBvn+Qba+i5IlUFvTXYIkFxcGC/dN+p/bcCJ2SkzHaBe/DZiuhVq6z1DL+yxyNDw7/NZ8UiiaB2D2JkH0P//IYqKkPT74BctkgGQ==).

As far as I can see, `v-navigation-drawer` is a multi-root component where attribute fallthrough needs to be taken care of manually (`class` attribute forwarding missing?)

**Comment by taozhiyu** [comment]
I know that this approach does solve the problem, but I think it should be considered a component defect? It actually defeats the purpose of the "scope" approach.

Thanks anyway.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/5446
