### ISSUE TITLE
[Bug Report][3.1.4] v-dialog :  Unhandled error during execution of watcher callback

### ISSUE THREAD

**Issue by TinyWisp** [vuetifyjs/vuetify#16641]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.36
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
open https://codepen.io/tinywisp/pen/zYLgagB?editors=101, and the expected dialog won't be shown.
error messages will be displayed in the console.

### Expected Behavior
show the dialog

### Actual Behavior
![image](https://user-images.githubusercontent.com/15992102/218272434-3ba3cf5c-9cab-4e7b-a871-832a92230510.png)

### Reproduction Link
[https://codepen.io/tinywisp/pen/zYLgagB?editors=101](https://codepen.io/tinywisp/pen/zYLgagB?editors=101)

**Comment by KaelWD** [comment]
https://next.vuetifyjs.com/en/getting-started/browser-support/
https://caniuse.com/mdn-javascript_builtins_array_at
