### ISSUE TITLE
[Documentation] Missing descriptions for slots

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#16649]
### Problem to solve
Let's consider documentation by v-data-table-server
I found that exist slot "top" in examples
But I didn't find list all existing slots for components

https://next.vuetifyjs.com/en/api/v-data-table-server/
APi has documentation by props, events even by sass variables but we don't have section for slots.

### Proposed solution
Add documentation by existing slots for each component

**Comment by KaelWD** [comment]
You mean this?
![Screenshot_20230213_174015](https://user-images.githubusercontent.com/16421948/218388409-c15eaf82-e036-4dfd-a74c-b7d8412414f4.png)

**Comment by oracast** [comment]
yes. thanks
