### ISSUE TITLE
[Documentation] VDataTable related documentation

### ISSUE THREAD

**Issue by jyjdal** [vuetifyjs/vuetify#16652]
### Problem to solve
1. VDataTable's api is still some incomplete, so I wanna ask when will these documentation be completed.
2. VDataTable has some options, like DataTableHeader, SelectItemKey etc. But I can't use it in Typesctipt because they are not exported,  so do you have plan to export these options, or give a detailed description in the documentation.

### Proposed solution
1. Finish the documentation, fill up the "MISSING DESCRIPTION".
2. Export component options or give an illustratation of these options.

**Comment by MajesticPotatoe** [comment]
Note: v-data-table documentation is still a WIP, as its a part of labs

**Comment by KaelWD** [comment]
Issues like this aren't helpful, API documentation is an ongoing project and we already know there are sections missing.

> do you have plan to export these options

Generally no. If you're trying to define props you can reuse the prop types `VDataTable['$props']['sortBy']`, and if you're defining string constants you can just use `as const`. If there's some specific type you need access to that isn't available elsewhere then please open a separate issue.
