### ISSUE TITLE
disabled radio button has ripple and hover

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1665]
### Steps to reproduce
Create disabled radio button

### Versions
0.15.3

### What is expected ?
Disabled radio button show use default mouse cursor and should not have ripple effect

### What is actually happening ?
Disabled radio button has pointer mouse cursor on hover and has ripple effect

### Reproduction Link
https://codepen.io/anon/pen/ZXzzKM

EDIT: same for chekbox/switch

**Comment by KaelWD** [comment]
Should it be `default`, or `not-allowed`?
