### ISSUE TITLE
[Documentation] [custom-sort] props for v-data-table is not mentioned in upgrade guide of version 3.1.4

### ISSUE THREAD

**Issue by DivakarSS** [vuetifyjs/vuetify#16654]
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 3.1.4
**Vue Version:** 3.2.13
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Project migration from Vue2 to Vue3.
I am using labs for v-data-table.
[custom-sort] props for v-data-table is not supporting in vuetify version 3.1.4.

### Expected Behavior
[custom-sort] props for v-data-table should be support in vuetify version 3.x.x or need an alternate for custom-sort prop that could be mentioned in upgrade guide of 2.x.x to 3.x.x.

### Actual Behavior
I am using labs for v-data-table.
custom-sort props for v-data-table is not supporting in vuetify version 3.1.4,  In upgrade Guide also not mentioning about the alternate one and I didn't see the custom-sort prop in props section in v-data-table.

### Reproduction Link
[https://next.vuetifyjs.com/en/getting-started/upgrade-guide/    (https://next.vuetifyjs.com/en/api/v-data-table/)](https://next.vuetifyjs.com/en/getting-started/upgrade-guide/    (https://next.vuetifyjs.com/en/api/v-data-table/))

**Comment by KaelWD** [comment]
Related: #11226, https://stackoverflow.com/q/76390698/2074736
