### ISSUE TITLE
Vuetify 3 with Vue 2.7 app?

### ISSUE THREAD

**Issue by MixMasterMitch** [vuetifyjs/vuetify#16657]
Is Vuetify 3 backwards compatible with Vue 2.7? I cannot find any information in the documentation one way or the other.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
