### ISSUE TITLE
[Bug Report][3.1.4] All VSwitch flicker when one is clicked

### ISSUE THREAD

**Issue by fahmifitu** [vuetifyjs/vuetify#16650]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on on of the switcher and notice how the other switches flicker.

### Expected Behavior
Only the clicked switch should react to a click

### Actual Behavior
All switches in the page flicker

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUEtuwjAQvYrlNY5BtJuIVvQcmIVJhsTFP9kmCCHu3rEJUgptpe7sefN+s7nQD++r4Qi0pqsExmuZ4F1YQlYDk96XZ/k0ziapLATSaBnjm6BessWc7DrWBTgzrbo+gWVLQUdSocWTSk1PBrZ3ATmWKEteBSWkPsA5D/DdqxZYCyivI+IREuF3Yz5xvuXCyS3Yik8CC0tnVBnvQmJG+uozOoudLpkiRiAKWpMyyTMsnf+C9in5WHN+tP7QVY0zfI0YD0eblMFgzqyX1bKaM6l9L6sX3qqYpnAF0bBdcKcIAY0FnU08ktqff/MZYZRf3GXHEdNyF7Pukx5HkwECC2BbCBD+7PCw+1OPh5WnLtn6KuwVz6uVPcSHyzaxXHVzT/j/kkUh07fZ5Tqj30KibSHS7RflNOH5)

**Comment by KaelWD** [comment]
That sounds more like a browser or graphics driver bug.

**Comment by fahmifitu** [comment]
> That sounds more like a browser or graphics driver bug.

umm could be yes. i just tested safari and firefox and it didn't reproduce, only chrome

**Comment by taozhiyu** [comment]
chrome 110 not reproduced
