### ISSUE TITLE
[Bug Report][3.1.4] Codepens in the Vurifty V3 not working

### ISSUE THREAD

**Issue by akatebi** [vuetifyjs/vuetify#16662]
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 3.1.4
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
Go to https://next.vuetifyjs.com/en/components/breadcrumbs/ click on codepen button

### Expected Behavior
Code pen should work

### Actual Behavior
Code pen is erroring in dev console

### Reproduction Link
[https://codepen.io/akatebi/pen/XWPWRMo?editors=101](https://codepen.io/akatebi/pen/XWPWRMo?editors=101)

**Comment by MajesticPotatoe** [comment]
This is due to that tags for `@vuetfiy/nightly` being incorrect (latest points to v2 atm <https://www.npmjs.com/package/@vuetify/nightly?activeTab=versions>)
Will naturally resolve itself once those are fixed
