### ISSUE TITLE
[Bug Report][3.1.4] v-overlay results in [Vue warn]: Maximum recursive updates exceeded in component

### ISSUE THREAD

**Issue by Hendrik-Mueller-Overzone** [vuetifyjs/vuetify#16661]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. npm install
2. npm run dev
3. Open Browser and click button to open dialog
4. Open Browser Dev-Tools
5. Change the value of the lines 67 or 68 in the components/base/project/MemberDialog.vue
6. Observe the warnings in the command line of the dev tools

### Expected Behavior
No warning should show and the component should refresh directly

### Actual Behavior
A warning shows, telling the developer, that the  "Maximum recursive updates exceeded" with the stack trace sometimes showing the problem being the watchEffect in the `useScrollStrategies` function in the VOverlay directory.
Additionally the warning `[Vue warn] cannot run an inactive effect scope.` is shown 100 times.

The reproduction example refreshes realtivly quickly, but once the dialog gets more and complex content, the refresh and the time until the warnings appear and the page is no longer freezed, can be up to a minute.

### Reproduction Link
[https://github.com/Hendrik-Mueller-Overzone/voverlay-max-recursive-updates](https://github.com/Hendrik-Mueller-Overzone/voverlay-max-recursive-updates)

### Other comments
This may relate to #16569

Screenshot showing warnings:
![image](https://user-images.githubusercontent.com/92714063/218750266-87a03b56-b0ac-49ef-9acb-e5c49b405610.png)

**Comment by KaelWD** [comment]
The "inactive effect scope" warning is unrelated, just a side effect of something else.

**Comment by KaelWD** [comment]
Seems to be triggered by this findIndex https://github.com/vuetifyjs/vuetify/blob/c48d7e49551f25b270f766c12e6ec05ac4cb1058/packages/vuetify/src/composables/stack.ts#L44

**Comment by KaelWD** [comment]
idk exactly how this works but this was being called with `track(globalStack, "get", 'findIndex')`:
https://github.com/vuejs/core/blob/a95554d35c65e5bfd0bf9d1c5b908ae789345a6d/packages/reactivity/src/baseHandlers.ts#L124

**Comment by KaelWD** [comment]
Probably related to https://github.com/vuejs/core/issues/6930
