### ISSUE TITLE
v-select doesn't open to selected item

### ISSUE THREAD

**Issue by kevmo314** [vuetifyjs/vuetify#1666]
### Steps to reproduce

1. https://dev.vuetifyjs.com/components/selects
2. Select "State 4" in any select.
3. Open select again.

### Versions

0.15.3

### What is expected ?

The active element should be positioned over the select:

![](https://i.imgur.com/Mzw5Uxg.png)

See https://material.io/guidelines/components/menus.html#menus-usage for an example in the material design spec.

See https://material-components-web.appspot.com/select.html for a functional example.

### What is actually happening ?

The first item is arbitrarily positioned over the element.

![](https://i.imgur.com/nqdtl1Q.png)

From the material design spec for menus over list items (which should have similar behavior):

![](https://i.imgur.com/7ZWe4Nw.png)

### Reproduction Link

https://dev.vuetifyjs.com/components/selects

**Comment by johnleider** [comment]
That is not the default behavior in Vuetify. You can enable this functionality by using the **auto** prop. An example would be https://vuetifyjs.com/components/selects #3.

I'll try to do a better job of explaining this in the future, thank you.
