### ISSUE TITLE
[Feature Request] Editable Spreadsheet DataTable: Inline editing for Vuetify DataTable

### ISSUE THREAD

**Issue by JPustkuchen** [vuetifyjs/vuetify#16671]
### Problem to solve
DataTables are just GREAT! But sometimes you need to inline-edit (some) values (like in Excel - but better of course ;) ). I guess in most cases this is called _Spreadsheet_.

Dedicated projects like this one, show how it might work: 
- https://github.com/muhimasri/b-editable-table
- https://github.com/ms-fadaei/simpledsheet
- https://github.com/handsontable/handsontable
- https://github.com/joffreyBerrier/vue-spreadsheet
- https://github.com/SheetJS/sheetjs
- https://github.com/revolist/vue3-datagrid
- https://github.com/dream-num/Luckysheet
- https://github.com/ag-grid/ag-grid
- https://github.com/olifolkerd/tabulator
- ...?
(a good comparison can also be found on https://jsgrids.statico.io/)

It would be just great to have such a functionality **natively** implemented for the wonderful Vuetify DataTables. This issue is for discussing and planning such a feature - or multiple features as this might split into cellwise, row-wise, keyboard-navigation, etc.)

### Proposed solution
If it's already possible, please explain, how to do it in an example in the documentation.

If it's NOT yet possible (or only using workarounds), provide a method to allow editing table cell values inline. As the form elements to use within the cells are individual to the value (input, select, ...) it might be helpful to combine a "click to edit" functionality (globally or per cell) with Vuetify Form Elements.
Not yet sure, how to do it best, but we should discuss that.

### References
I'm not the first one asking for such a functionality, here are some dicussions I found on that topic:
- https://forum.vuejs.org/t/is-there-any-way-to-inline-edit-vuetifys-v-data-table/114672
- https://forum.vuejs.org/t/v-data-table-inline-editing/55213/3
- https://forum.vuejs.org/t/vuetify-editable-v-data-table-and-inline-editing/81628
- https://codepen.io/Jayesh_v/pen/wvgjMva (linewise editing - might be a different mode, instead of editing the cell directly)
- https://stackoverflow.com/questions/59873652/vuetify-datatable-enable-content-editing-on-all-columns
- https://stackoverflow.com/questions/59184658/vuetify-modifying-inline-edit-data-table-content-from-method
- https://github.com/vuetifyjs/vuetify/issues/9840
- https://github.com/vuetifyjs/vuetify/issues/11273 (related issue for row-wise editing)
- https://github.com/vuetifyjs/vuetify/issues/9164 (Keyboard navigation for values in tables)

**Comment by webdevnerdstuff** [comment]
I actually built a few components for this exact purpose. Maybe I'll try throwing it together into a npm package when I have some time. Following this thread now so I don't forget.

**Comment by JPustkuchen** [comment]
> I actually built a few components for this exact purpose. Maybe I'll try throwing it together into a npm package when I have some time. Following this thread now so I don't forget.
@webdevnerdstuff thanks, is it based on vuetify components?

**Comment by webdevnerdstuff** [comment]
@JPustkuchen Yes, it's based on vuetify components. I started putting it together last night. I'll need some time to make it useable as a package as I"m copying it over from another project where I made them. It'll be the `vuetify-inline-fields` repo you can find in my repositories. You can also join my discord channel to reach me easier, I haven't really used it but this seems like a good use for it finally. https://discord.gg/RmypvQzD

**Comment by webdevnerdstuff** [comment]
@JPustkuchen I'm almost done I think with the new component library for inline fields. If you want to check it and and/or give some feedback it would be appreciated.

You can find the lib in my github page repos as `vuetify-inline-fields`. There's no demo page/documentation for it yet, but if you clone the repo, then `pnpm i && pnpm play` you can see it in action in the playground. You can also test things out in the playground file `./src/playground/PlaygroundPage.vue`

**Comment by qxygene** [comment]
https://codepen.io/Jayesh_v/pen/wvgjMva 

old version, but this may give you some ideas.

**Comment by webdevnerdstuff** [comment]
I'll just put this hear to make it easier.

https://github.com/webdevnerdstuff/vuetify-inline-fields

**Comment by s-light** [comment]
thanks @webdevnerdstuff  i just looked at your documentation - that is a solid project!!

has anybody a recommendation for a library that integrates well with vuetify with full spreadsheet like options?
(keyboard navigation between cells for example is gets very komplex to implement - i tried it a year back....)

**Comment by mercmobily** [comment]
These elements: https://github.com/webdevnerdstuff/vuetify-inline-fields Are GOLDEN.
Are there any plans to actually add them to Vuetify as default ones? I think they would be a very valuable add-on. Or at least linked from the official documentation somewhere?

**Comment by webdevnerdstuff** [comment]
If you could drop a star on that repo it would be appreciated. ;) :)

**Comment by mercmobily** [comment]
> If you would drop a star on that repo it would be appreciated. ;) :)

I did I did. But it looks like this was given a "not planned" tag, I assume because it's not strictly part of Material...
Shame, and I will certainly be using them. I hope you will keep on top of them

**Comment by klimekszymon** [comment]
> These elements: https://github.com/webdevnerdstuff/vuetify-inline-fields Are GOLDEN. Are there any plans to actually add them to Vuetify as default ones? I think they would be a very valuable add-on. Or at least linked from the official documentation somewhere?

the library is not updated since two years, not sure is it viable solution for any project in this circumstances

**Comment by mercmobily** [comment]
> > These elements: https://github.com/webdevnerdstuff/vuetify-inline-fields Are GOLDEN. Are there any plans to actually add them to Vuetify as default ones? I think they would be a very valuable add-on. Or at least linked from the official documentation somewhere?
> 
> the library is not updated since two years, not sure is it viable solution for any project in this circumstances

This is a huge shame. Oh well...

**Comment by J-Sek** [comment]
DIY - [demo](https://play.vuetifyjs.com/playgrounds/T9Ixlw)

Edit: fixed access permissions, link should work now

**Comment by klimekszymon** [comment]
> DIY - [demo](https://play.vuetifyjs.com/playgrounds/T9Ixlw)

Link is broken @J-Sek , meanwhile I did manage to build my custom solution for it, inspired by this example https://codepen.io/Jayesh_v/pen/wvgjMva 

Demo 

https://github.com/user-attachments/assets/4076cffe-74f0-4dc4-a109-acb314afbe79

**Comment by webdevnerdstuff** [comment]
> > > These elements: https://github.com/webdevnerdstuff/vuetify-inline-fields Are GOLDEN. Are there any plans to actually add them to Vuetify as default ones? I think they would be a very valuable add-on. Or at least linked from the official documentation somewhere?
> > 
> > 
> > the library is not updated since two years, not sure is it viable solution for any project in this circumstances
> 
> This is a huge shame. Oh well...

A wise dev once said, “_If it ain’t broke, don’t fix it.”_

This project is open source, and like many maintainers, I also have a full-time job. That means updates won’t always happen on a weekly schedule, especially when there are no bugs being reported. I’m not paid for this work, and over the course of many years, contributions or donations have been rare enough that I could count them on one hand. That’s true even for my most popular package, which still sees 8000+ downloads every week.

When bugs are reported or feature requests are submitted, I do my best to address them as quickly as I can. Pull requests are always welcome as well.

“Not recently updated” doesn’t necessarily mean “not viable” sometimes it just means the code is stable.

Update:
I just updated most packages, but don't have time to fully test things out yet (quick test looked ok) so haven't merged it or published it yet. If anybody wants to mess around it's on the dev branch.
https://github.com/webdevnerdstuff/vuetify-inline-fields/tree/dev

**Comment by klimekszymon** [comment]
> DIY - [demo](https://play.vuetifyjs.com/playgrounds/T9Ixlw)
> 
> Edit: fixed access permissions, link should work now

@J-Sek  Good direction with modern look & feel, the hoverable cells are neat! Love it <3 I would love to see more of your Vuetify Playgrounds with such a good demonstration of Vuetify capabilities! 

@webdevnerdstuff  Apologises for my poor judgement, I tested your library for a little bit, but I coudn't manage to integrate it nicely in my project because I use very large complex server data tables with creamped cells , so it just didn't fit to me, and I don't have enough skills to customise it or fork it. 
PS. I'm glad I make you push commit to your repo today :D Many people judge repos based on its activity. All the best mate!

**Comment by webdevnerdstuff** [comment]
> > DIY - [demo](https://play.vuetifyjs.com/playgrounds/T9Ixlw)
> > Edit: fixed access permissions, link should work now
> 
> [@J-Sek](https://github.com/J-Sek) Good direction with modern look & feel, the hoverable cells are neat! Love it <3 I would love to see more of your Vuetify Playgrounds with such a good demonstration of Vuetify capabilities!
> 
> [@webdevnerdstuff](https://github.com/webdevnerdstuff) Apologises for my poor judgement, I tested your library for a little bit, but I coudn't manage to integrate it nicely in my project because I use very large complex server data tables with creamped cells , so it just didn't fit to me, and I don't have enough skills to customise it or fork it. PS. I'm glad I make you push commit to your repo today :D Many people judge repos based on its activity. All the best mate!

At my job, where I use most of my Vuetify components heavily, we have massive datatables. So it's doable, but definitely can be a challenge when you are dealing with space constraints.
