### ISSUE TITLE
[Bug Report][3.1.5] VSelect - Prepend Inner slot button causes menu to open

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#16678]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add a v-select component with a prepend-inner slot button with @click.stop modifier
Click the prepend-inner button

### Expected Behavior
The select menu should not open

### Actual Behavior
The menu opens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUltuwjAQvMrKrQRIxKGi/CBAcA7CRwhLcYkfsh0qhLh71w5BCbSV+hXP7uzMepz1ha2M4acK2ZTNPEpT5h4XmQKYnZLcmHiMQOZC3VDEDkssPDQVgKmgeTfPWPxmrNUq8y2W1PHofMaa+l2N9BpreDEWDapdIpRC26JE061XIAqtYFmUojhy57WBpdSVw8pE1JmIM4G/eJWoqll6Qx1VKpJse5m0E0RDqi/cBEKFeyIB1Fl1Rgm6wgrjwaGvQltIo62HC1jcwxX2VkvoUfi9QKbFnIcYHswDo7+yNj/zwKqP/clowI94dv3BYBDMankSZkNWa9NShn86reg9L2E3eo7YoAeZQqyEGnkGnLGD98ZN07RS5vjBCy3TJfVSWykvJCY7LZdjPuajJC/NIefv6U44325zdDLZWv3l0JJxxoYtDy/25998bm2Sf+OTWvZWCpJPUinpn9Amlv4NtGj/XP+B+9MVHihP1wjW10xdKdlSqKN7CLVwMdB1s+G/7ieF4lEgTG+CyXXIOjuSa5xjm29OuipV)

### Other comments
I saw an older issue for vuetify 2 mentioning to also stop propagation on mouseup but that doesn't seem to do it either.

Here it is working on vuetify 2: https://codepen.io/joel-wenzel/pen/LYJERPz?editors=1010

**Comment by KaelWD** [comment]
You have to stop propagation of both click and mousedown, not mouseup.
