### ISSUE TITLE
[Feature Request] `VDataTable` Items per page allowed

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16693]
### Problem to solve
Allowing only specific ranges of items per page.

### Proposed solution
Adding a prop to set the only allowed items per page like: `[5, 10, 15, 0 // (all)]`

**Comment by effhAVE** [comment]
This is much needed.

The solution from Vuetify 2 doesn't seem to work anymore.

**Comment by webdevnerdstuff** [comment]
https://vuetifyjs.com/en/api/v-data-table/#props-items-per-page-options

**Comment by Bart-Westenenk** [comment]
This does not yet work, or I am not using it correctly

**Comment by webdevnerdstuff** [comment]
[Example](https://play.vuetifyjs.com/#eNqlVltv2zYU/iuEtiEbEEm2bDmJlg4t0nXtOmB5G4Y6D7TEOFwokiBpZ2ng/95DkZR1sd0CfTF8rt93LiL56SV6I2Wy3ZCoiK4NqSXDhvy25Ahdb2MsZfO3EWpMuZcaucIGxwavGAlKhAoKKfSrZVQRrYkyehl1jA8EV0RZs//Xs+oH8RST/yXmFXgYtSE9c5M5lkTFEq9JLKShgttcjeGWqFtQ/+20+8CWMFAO1aEfHAqpYiWeIMMLKgXb1Fyj3TLqRNgY1ZOtpuorECoZ1paIxPG8S9kTh9wa4MDBoySM8LV5GLoOgBB6TxgT6B+h2ADyOjVVn2ba4wlid5BO1R1YGCoo26lawc27Fw6iLhWVBmliNtZcQoMN8hNEr9AnG/3iMhpqGCnQ2Vs3fvTzdDJZQ6TaUr7+5ezceWFG1xy8tMHKBKUWquFWoHvMNPHaR/IMjhzXxPntmt+XFugGM6Eo0WfnbVbCK5BcYBnMo8B3GNhZSgfj7rEZh9xgtdIngkprH4fdKmEI5ScCpfMYh35QAuJ+OhZHweyC7n61k3KTCZ/eYDS2h7ZuJT4Tjv4V682+96FNBZrmV14HLSjQIpm0LlBcgbK5lz3nAs1bF0sHEKa9SfXA/4SNfkYrgvkYeXaRd5EnQ+SrEfLexSNPjiN/pOYjzHSEmk8vu6jZqOBFYNXCXvRBF8dBf4eTgaoxaLbIuqDTcZdnQ9C9i4e9OA77B3xrRK0UfKEH2pwvTmPPwwK02LMkqMKET9T8oSSoBOgaaThin2j5cKD+Wehhw+FqSKE1d5YsdOTrS/aXYIxKIQ/UftXr+yQJYlixsAv7FeujZsdRbzayxI/+lOqBTnp7PUtCcWHBvl7s5XHY94KT51LUqzHwfNJb7dmw2ssR8CIJVD3wPD+O/FbwzYEPap73epzlw+Hm03G9g/3KOn3unmwHbvoj94/njdAWsw0oXF29MoLr1J8are/UET7onA0TZycy58PM+YnMcFGOeJxw/xFebIbePyf2Un8noJMq6bbnDWODdLHr+8619Dp1tzrc59F5RGsJty+8BWTynxYcnoINHLytGgO8p4pAYBkBspXhEWeM1EWalhWHsIowulUJJyblsk5fg1uqNtzQmsSVqF/PEtjAtKLadNUJ0XW8gmcYXFmQZBl50g2MLfAboLwnIGTJ3CF4VczwSluIUerUvkngLangPiWKqG+taBDWrWpgGlXmu7+DfjPKH/Wg1aVu2txss5W/q+Qmmc10ZwF351HDE5CbgOjuCw72ipI=)

**Comment by Bart-Westenenk** [comment]
When copying your example into my project, it does not seem to work. I am testing this by changing some of the entries in the array. I copied your example into my own project into the App.vue file made by my vite instance.
The following shows the way I am adding vuetify to my app.
```
export default createVuetify({
    components: {
        VDataTable,
        VDataTableServer,
    },
});```

I wonder why it won't work? Is there any data I can provide to help fixing this issue? The console reveals nothing ...
