### ISSUE TITLE
[Feature Request] `VDataTable` default options

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16696]
### Problem to solve
Sometimes you want to store the DataTable options to be reused within the application (like actual page, filters), but when you store the options and re-render the `VDataTable/Server` the options are reseted.

### Proposed solution
Adding a prop could work to define the initial options so when the component is re-rendered `@update:options` is not called again.

**Comment by nekosaur** [comment]
This sounds more like a bug? Please show a reproduction of what you are doing.

**Comment by ElYaiko** [comment]
Reproduction: [link](https://play.vuetifyjs.com/#eNqdVttu2zgQ/RWugIUTwLr4IicRnCC76V663Ye8LuI80DJtcy2RBEk7SA3/e4e62KItplWNohF5Zjhnzgyledl7vwkR7LbES7ypJrnIsCYPM4bQdOdjIYrHYpFjyqoVQvs94kJTzhQ6HI4mc83QY5rRdHM/89Sav6F79Iv5O/Me1nRBQvM8DQvD41EXfkSDOfxfR7AdwHyBNfY1nmekPsP8dj5dVmFnXg0Abb4gWUIhNeULIn2BVwTMio1nIp9heTJv/mrXigX4VE8n82RN8IJIg1VPDayIAMiCKEWkbkAG8Xc42xoiDOcNAmmGlXEiGdlhE80f1OCD0eGUei0HbB4rYxZlzaZho5awVKmkQiNQdWtgmgsuNdojSZbogJaS56gHTdAzxinkCKZl+cDgaokzRa5roK57ie3RzDOSzrwEDfqwsIWFzcjsKgj3+7tZv7ya9Uryrag30OF4uCn7Pbq6RvcPaG9SqqIFhVwAfTfeMP6BeDMG/8qITf8qpxjomFoUeFXYCno5dUpBr/5pqjOSoN6nstjoahBFK8hG7ihbXff6TVuc0RUDW6Wx1DZkaJviJqjQ3MI25B2cTLs0fQ6N5/2RxhPOuKRE9frHaIQtYFUektaww/1PDBkY2q3eS6xdjk9YztUHrqnBXc7PkmtC2QfuorRwHfBZcvD+1eVNAQbX2vO1rPKx0PU9/U6lTQGMRJJ/JQz9x1fb8yLW6kKDxncWAsolaBJEZ+agCfTt2NqtUk3Q+MzcZAHxB84maCH7D8mydzQnmLmYjm7iS6ZRO9M7B9Nz84pp1IXpF6q/QHs5WMaD20uWQ4egEzujI82bNpKTLiT/gLc0lS6Sw8nwkuTAVfVRO8lz84rmTReaf8Grh8i5hBeYs+zx5Me5ju1mPnIdBTZQd2gnTT+nBKVANUcKs8UbTddOfUd2BQvOd+2Uz0wbl8rW/Wcu1b88y6jgwqntXUsfRIG9WV8pu69PV6qN5bALy6etSPHG+mRYJKOWez8KbNnqC9VNzNsuNP/mjLynPJ+7iI6jlqs/alfz1kF0EtjJVkTHcRemnzjbOl9Q47il5sO4vTnjgUvP1vs0tOve/IxNw3K+g8nO63vlcAdToQj+V5zBYF/kAaNSAcAgmtSZzTwY+swaBlithUrCcMvEZhVAKcJHwEK5ZZrmxF/w/HEUjILIx5lY42AcLqjSTTggKvfnkr/BVxQCz7yKbRFD02UxfLXFqWA4fhDclMdWW36G58qce3FeaEYrmOYlfOCJJPLDHM5s2/I4M7nIxYQ2UyPIm1G2UWfKpqpQtZoZuiUZ5JQFxQHG+9UEOfQ9iyNELfy812/MxsFT)

You see that when you click in 'set options' first, and then show the data table, the options are reset to defaults instead of initialize with these settings.

**Comment by KaelWD** [comment]
You're setting it to 5 through `items-per-page`
