### ISSUE TITLE
[Bug Report][3.1.5] tooltip colors not working

### ISSUE THREAD

**Issue by Martin-N** [vuetifyjs/vuetify#16690]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Mac OS 10.15

### Steps to reproduce
Hover over the button. 

### Expected Behavior
The tooltip should be the color assigned, in the reproduction it should be "success".

### Actual Behavior
The tooltip color is grey

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUktv00AQ/ivDXgJSbLcqXKIUlRvckTjUPTjrSbPtvrQzNkWR/zuz6wQlKSD1lMzje8znvd+rLzHW44BqpdaMLtqO8XPrAdZj1cVY/pbCdcaDth3Rbav6amvxBZ4GYrP9VWn0jAkiV9dXrTpgCopDsGwiML6w4L4B7cJge9ggdD7wTlA62JBaNf/KDg1aI9EJjzAdrcFYkQ286jSbseMC2ENMIRJMZ5Aiv2EviI3xveyVLdn5PntaN2V+qtKcJTC3/txwjEI6OYs5JCnmlM6wUpJOJjIQ8pDHxsWQGPaQcAsTbFNwsJDYF3lZB08Mjh7hNs/fL76itQF+hGT7d4sPmXymEyK1VDOXmIj1EwUvX26fvbSHgZy4gtLJPdHIdat2zJFWTTP4+PxY6+CaO5k1afBsHFZ9cHc39U19VXU27rr6Y9Mb4tNxjeSqTQo/CZMIt2p5opGfwb90DmOhv64/zbSHVqZ8RdUI/4ipSuh7TChP4z/2L3b/dsLFyqszsvTU+kmStcY/00WoOj/FFdwfHb7pPmd8XQgy+iGLTEt15lFUC049/AYe5izI)

### Other comments
The color option is missing from the API documentation for tooltips, making me think that this hasn't been implemented yet.

**Comment by cesxhin** [comment]
Yah, this not bug but only missing implementation. I think that you should close this issue and request implementation
