### ISSUE TITLE
Modal is not closing on clicking outside

### ISSUE THREAD

**Issue by prakash-freshdesk** [vuetifyjs/vuetify#167]
The below error throws when I use modal,v0.8.10
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.eval (eval at <anonymous> (app.js:956), <anonymous>:1619:43)
In the code
  document.querySelector('[data-app]').addEventListener('click', click, false)

 document.querySelector('[data-app]') returns null.

**Comment by johnleider** [comment]
You must wrap your app in a vapp

**Comment by johnleider** [comment]
Did this solve your issue?

**Comment by greensk** [comment]
I have the same problem when use v-modal inside Nuxt application. There is no App component in Nuxt.

**Comment by johnleider** [comment]
You must use v-app to wrap your application. Vuetify uses this to hook in for its click-outside directive.

**Comment by camhart** [comment]
@johnleider You'd think that should be mentioned at https://vuetifyjs.com/quick-start.

**Comment by johnleider** [comment]
Sure thing boss, right on it.

**Comment by bjendyk** [comment]
@johnleider I wrapped up my code in <v-app> and got rid of "addEventListener" errors, but now the modals stopped working :( I open and close the modals programmatically using v-model variable set either to true or false.

I have a button in my component:

`<v-btn v-on:click.native="openCategoryModal('main')">...</v-btn>`

That calls the component's method:

```
openCategoryModal: function (categoryType, item) {
        // some preparation code

        this.categoryModal = true // this statement does not open the modal anymore
}
```

Modal markup:

```
<v-modal v-model="categoryModal">
      <v-card>
        <div class="modal-body">
          <!-- modal body goes here -->
          <v-card-row actions>
            <v-spacer></v-spacer>
            <v-btn flat v-on:click.native="categoryModal = false" class="primary--text">Cancel</v-btn>
            <v-btn flat v-on:click.native="submitCategory" class="primary--text">OK</v-btn>
          </v-card-row>
        </div>
      </v-card>
    </v-modal>
```

Everything it stored inside single .vue file. What am I doing wrong?

**Comment by johnleider** [comment]
When you do not  use the activator slot, you must stop propagation of your clicks in order to prevent the modal from immediately closing.

**Comment by bjendyk** [comment]
Thank you @johnleider, it worked like a charm! :)
