### ISSUE TITLE
[Feature Request] `VDataTable` header slot

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16704]
### Problem to solve
Being able to change the content header of specific column like in V2

### Proposed solution
`header` `header.<name>` slot like V2

**Comment by joel-wenzel** [comment]
This is already available:
https://vuetifyjs.com/en/components/data-tables/headers/
`column.<name>`

**Comment by ElYaiko** [comment]
> This is already available: https://vuetifyjs.com/en/components/data-tables/headers/ `column.<name>`

It doesn't seem to work in `VDataTableServer` :/

**Comment by kingyyy** [comment]
same problem here.
it seems that `VDataTableServer` doesn't have `column.<name>` slot
