### ISSUE TITLE
[Bug Report][3.1.5] Documentation for `item` in VCombobox is missing

### ISSUE THREAD

**Issue by jippy89** [vuetifyjs/vuetify#16709]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open https://vuetifyjs.com/en/api/v-combobox/#props-item-title
Check for the following prop description:
1. `closable-chips`
2. `counter-value`
3. `custom-filter`
and there's like 45 more...

Just use `CTRL + F` and look for "MISSING DESCRIPTION"

### Expected Behavior
It shows description

### Actual Behavior
It doesn't

### Reproduction Link
[https://codepen.io/jippy89/pen/RwYWRRr?editors=101](https://codepen.io/jippy89/pen/RwYWRRr?editors=101)

### Other comments
I just wanted to note that it's missing. The text still exist thought in earlier v2 version
https://v2.vuetifyjs.com/en/api/v-combobox/

**Comment by MajesticPotatoe** [comment]
resolved in 7cddf6a
tracking in larger scoped issue #18248
