### ISSUE TITLE
[Bug Report][3.1.5] [v-slot:column.name="{ column }"] Column slot not rendering user defined <tr> tags..

### ISSUE THREAD

**Issue by DivakarSS** [vuetifyjs/vuetify#16701]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 3.1.5
**Vue Version:** 3.2.13
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Columns slots not rendering user defined "tr" tags which all are present inside this ![image](https://user-images.githubusercontent.com/69146417/220057255-e60b96a3-fc00-4307-85e4-bbf3fab14878.png) template tag.

### Expected Behavior
This should render the tags or other component which all are present inside the ![image](https://user-images.githubusercontent.com/69146417/220057301-5188303d-7360-4eab-90ad-e8c0fdbca0af.png) tag.
![image](https://user-images.githubusercontent.com/69146417/220041340-69a030f2-cbef-4b56-9d66-94df3c65875b.png)

### Actual Behavior
It is not rendering the components or tags which all are present inside  ![image](https://user-images.githubusercontent.com/69146417/220057351-c502e17a-842a-4ac5-bff7-60adbaff7cde.png) this template tag contains column slot. It uses v-data-table own header.
![image](https://user-images.githubusercontent.com/69146417/220041460-f709ead0-4636-4343-a120-d62473cee75b.png)

### Reproduction Link
[https://github.com/DivakarSS/VDataTable](https://github.com/DivakarSS/VDataTable)

**Comment by KaelWD** [comment]
There's no `column.id` slot in your example. If this is still a problem please open a new issue with a minimal example that actually reproduces the problem you have, ideally in https://play.vuetifyjs.com/
