### ISSUE TITLE
[Bug Report][3.1.5] VirtualScroll - Up/Down arrow key navigation

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#16703]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
* Click the `Normal List` button
* Tab until the first list item is focused
* Use the up and down arrow keys to change the selected list item
* Repeat steps for `Virtual List` button and notice the selected item doesnt change

### Expected Behavior
Selected virtual list item should change

### Actual Behavior
It doesn't

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VE2PmzAQ/SsWPUDUYFrt9hJlq+y96qnay3oPDpiNG2Nb9pBshPjvHRsSBdJWatVegPl68+aZ8XOXHFoBsj7R7z5ZJbKxxgHpSOkEB/E0xEhPamcako65KdNMi7eYWhrtgYwB8jAtzDqmCYGdaMQKQStR81bBt8FOlXzdQUr6ZYDrF0wny+TRWopgSGUNorEKsT4HjPUh59bGz2g0XOrRGmyh24sdfedy8o6XIA8cjHtgSUesM9aTniWT9AiyBU3wKXWFmTEPs74a13BFvkgP6yLmTPsUE55XaAorbnsEby6xBjvVkVI0pCbhjQ3Jai9OoxutTalkuUc7vkWVBf8CeXVd+Or7QOoCeu43ZXjDJbgmiv1XBZ+kg/avJPQ7Ia55M0DnYYDLfemMUmQVdRsFC/phmTIQmEaBJjQZMJiewr9Qe2CGkSm1meDzYWaHEM3zXx2M4X+fiIMmQksLxAtoQ/iysE7U12saV5TpYTujMribj87xEw05WfzM7hcUx/fZApeP6brVeM5Gk8vwuhJvCxKX+IiGOVKuhIMsHTNISt7jrxuycIMD2YEeEsNdHrjhUBYvF6NxpyMSih0DeFZ4KQzDs3ANBZslOwDrV0XRart/paVpig3GCtdqkI3IK9Ns7ugd/ZBzZXec3hcVHsd1mArf5Ftnjl44bMwSvF8uPcKt9Ks+YxjhP9JPA+zoyhXf+oB7g1dgk4NwuROoghPutzPMcn82xyzlZpbQGoXuUV4l9d7PlC19VPX5zPBPhqSN1DQChOqX0KRfJhOO2DXWJS8/AE4KAtE=)

### Other comments
It would also be great if there were exposed methods to be able to change the selected item in code. That way we could do things like auto select the first item when the menu opens. (this was possible in vuetify 2 but probably not intentionally)

**Comment by KaelWD** [comment]
You used v-sheet instead of v-list on the second one.
