### ISSUE TITLE
[Bug Report][3.1.5] Datatable don't work

### ISSUE THREAD

**Issue by gllanasnas** [vuetifyjs/vuetify#16700]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Windows 10

### Steps to reproduce
v-data-table is not working

### Expected Behavior
show datatable

### Actual Behavior
nothing

### Reproduction Link
[https://codepen.io/llanasnas/pen/VwGLXyK?editors=101](https://codepen.io/llanasnas/pen/VwGLXyK?editors=101)

### Other comments
It seems there is a problem with the Component definition

**Comment by KaelWD** [comment]
It's only in vuetify-labs.js
