### ISSUE TITLE
[Bug Report][3.1.5] Regression from 3.1.4 list item exact property now applies active class to not exact links

### ISSUE THREAD

**Issue by davidstackio** [vuetifyjs/vuetify#16702]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add a list item with an exact property.
2. Add a deep link list item with exact property.

### Expected Behavior
Only the deep link list item will be highlighted in the nav.

### Actual Behavior
Both the non deep and deep item are now highlighted.

### Reproduction Link
[https://jsfiddle.net/z13w0r4j/](https://jsfiddle.net/z13w0r4j/)

**Comment by KaelWD** [comment]
Works for me
```html
<template>
  <v-app>
    <v-container>
      <v-list>
        <v-list-item to="/page1" exact>page1</v-list-item>
        <v-list-item to="/page1/foo" exact>page1/foo</v-list-item>
        <v-list-item to="/page2" exact>page2</v-list-item>
      </v-list>
    </v-container>
  </v-app>
</template>
```
```js
routes = [
  {
    path: '/',
    name: 'home',
    component: home,
  },
  {
    path: '/page1',
    name: 'page1',
    component: page1,
    children: [
      {
        path: 'foo',
        name: 'page1-foo',
        component: nested1,
      },
    ],
  },
  {
    path: '/page2',
    name: 'page2',
    component: page2,
  },
]
```

**Comment by davidstackio** [comment]
I had an extra `:value="link"` property on each `v-list-item` that looked to be screwing it up after the update to v3.1.5. After removing that it seems to be working now. Thanks for looking into this so quickly and sorry for the false alarm!
