### ISSUE TITLE
Wrong type check for a carousel item prop

### ISSUE THREAD

**Issue by Claus1** [vuetifyjs/vuetify#1670]
My component has in data section:

`photos: ['images/1.jpg','images/2.jpg']
`
In template (pug) :

 ```
...
 v-carousel
     v-carousel-item(v-for='(item,i) in photos',:key='i',
       :src='item')
```

It works ok but got 2 warnings:

[Vue warn]: Invalid prop: type check failed for prop "src". Expected String, got Number. found in --->

If
`
 :src='item' `

change to

` :src='item.toString()'` 

there are no warnings.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
