### ISSUE TITLE
[Bug Report][3.1.5] border radius

### ISSUE THREAD

**Issue by hberdous** [vuetifyjs/vuetify#16722]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
# autocompletes, text-fields, selects ...  components
### Reproduction Link
[https://codepen.io/hbiori/pen/KKxVNPK?editors=101](https://codepen.io/hbiori/pen/KKxVNPK?editors=101)

**Comment by santiagoaloi** [comment]
Border radius classes on inputs isn't supported.

But you can achieve that with sass.

`$field-border-radius:50px`
