### ISSUE TITLE
[Bug Report][3.1.5] V-progress-linear needs to add z-index to make it display

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#16728]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Let's consider this reproduction link. You can see that v-progress-linear doesn't diplay until you add 
style="z-index: 99999"

But If remove v-app-bar component it display properly.
I think that something is wrong with this use case. I implemented it in the beta version and it worked. Now I had to see z-index to make it visible.
Thanks

### Expected Behavior
Should be visible without z-index even when use v-app-bar component

### Actual Behavior
This doesn't display

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-vjv3t1?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-vjv3t1?file=src%2FApp.vue)

**Comment by KaelWD** [comment]
Makes sense, you've placed it behind an app-bar which has a z-index of 1000-1100
