### ISSUE TITLE
[Bug Report][3.1.5] Opening v-dialog makes vertical scollbar to vanish which causes page content to glitch

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#16727]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce

* Use a browser that has a scroll bar that takes up actual screen space (e.g. Google Chrome or Chromium on Ubuntu)
* Go to the [Dialogs page in the Vuetify 3 docs](https://vuetifyjs.com/en/components/dialogs/)
* Click the first button "OPEN DIALOG"

### Expected Behavior
Page content should not be affected by the dialog.

### Actual Behavior
For whatever unnecessary reason, the dialog removes the scroll bar from the underlying content. This adds the width of the scroll bar to the viewport width which causes the whole page content to jump stretch several pixels to the right.

### Reproduction Link
[https://vuetifyjs.com/en/components/dialogs/](https://vuetifyjs.com/en/components/dialogs/)

### Other comments
I know that there is a very polarizing discussion in the Vuetify community whether or not this scrollbar should be there in the first case. I don't care if it is there or not. But I do care about the fact that the `v-dialog` is suddenly removing it which makes the content glitch. This makes my app look very unprofessional. If there would be any workaround to turn this behavior caused by `v-dialog` off, I'd be happy.

I was able to remove the scrollbar completely by adding

```sh
    <style>
      html {
        overflow-y: hidden !important;
      }
    </style>
```
to `index.html` but apparently it does not work with `overflow-y: scroll !important;` to force the scroll bar to stay under any circumstance. The `v-dialog` will still make it disappear.

This is not a problem with some browsers which have a scrollbar that overlays the content. You will see it go away but that won't change the width of the viewport and thus not affect the content. But some browsers (e.g. Google Chrome, Chromium) still have a scroll bar that takes space from the viewport and it looks awful on one of them.

It appears that exactly the same issue was already discussed in 2017 and the devs did not seem to understand the issue this causes. So I'm trying again. https://github.com/vuetifyjs/vuetify/issues/1197

**Comment by KaelWD** [comment]
> For whatever unnecessary reason

To prevent scrolling the rest of the page:
https://vuetifyjs.com/en/components/overlays/#scroll-strategies

> causes the whole page content to jump

`<html>` has `padding-inline-end: var(--v-scrollbar-offset)` to counteract this. I'm aware of right drawers jumping because the way their width is calculated doesn't currently work with css variables, everything else should remain in place though.

#1197 is about the default `overflow-y: scroll`, completely unrelated.

**Comment by frederikheld** [comment]
Thx for the very quick response and fix! <3
