### ISSUE TITLE
[Bug Report][3.1.5] Adding a control element to VSlideGroup

### ISSUE THREAD

**Issue by ghettoDdOS** [vuetifyjs/vuetify#16723]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Yandex 22.11.3.838, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Linux x86_64, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
I want to create a link at the end of the VSlideGroup, but if I add an element after the loop, clicking on the first element will scroll me to the end.

### Expected Behavior
Add use case as normal horizontal slider

### Actual Behavior
Strange behavior of the component that switches me to the last element when clicking on the first one

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqVVEmP0zAU/iuWuSRS7QBlLqGtZk5cOCBxnIxQmritabzIdgtVlP/Os5M028CIk/227+3vucZPWtPrheEUbxwTusod22USoc2V5FqHbyBEzmVHAQ1W3ytesi9GXXTPRSjlgGG3GQ5vhgfJO2DWyLNRM/DvgMFFkZsSFVVuPcL+SLThIjc3JAxZZ3ipSxx3Fdt50BTVtX9pYDXNJpmojEw7wZBKMsmlTxjU7hl7oq3FJhnVCEhbGK4dsswFSy60Mg5NANHBKIEyTKd+fM0z/NmjdFY1MuyAml5/kBdKWhdKZ9HWK0VPxuQ36hXbb/TxIY6pyHUU/VghHqPtDkV1SD1FvInj2IfeBgth4hVufUKKmv60SkL3a58pNC4IoHVQ0bYUXSgpfE7OaZsmyUXq85EWSiSPIEvMRTouGCmVeFzTNX1P8kqfcvopKbl1YzFlVpC9Ub8sM+A4w6uRD8cPt7/56cQA/4E+tLAdy0MuoBLAvzJDDJMlM8z8M/yZ7mspzFQWaXjXTSYbqGzF5dnOilrYUNDnPsL/yk9wSQOAt35pnSxG6bX1tV6DHMMQ9ls14t03aqpK/KD1y3ElB2XALPJMmCxI/3cMTzuNwx6nZ3bzW+/lPXfYMFsp156G7jJkGO1gHoE9Wrd5DJ3ozRh73z4iWjF5dKdlCFeyd3L3FXrTX4pet70VXvpGKDPB/BrMb0HJDlyyb0ZpG4UxCE5TFBYWujhdSVjKZoUnkwdtDtOAX/4AtITZaQ==)

### Other comments
The problem is not the key attribute

**Comment by KaelWD** [comment]
When slidegroup is focused it focuses its first focusable child instead. Adding `tabindex="-1"` will allow them to be focused instead of the button.
