### ISSUE TITLE
[Bug Report][3.1.4] VVirtualScroll is not adjusting scroll for newly added items

### ISSUE THREAD

**Issue by sanjay-bhuva** [vuetifyjs/vuetify#16725]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
As you can see in the reproduction playground link. Initially, I am having 10 items for virtual scroll and adding 5 new items after every 5 seconds.

Once new items are added, the scroll is not adjusted automatically until you scroll to the top (at least a item)

### Expected Behavior
Scroll should adjust automatically based on the number of items without scrolling to top/bottom

### Actual Behavior
Scroll is not adjusting until user scrolls to top (at least a item)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtV8ty2zYU/RUMu7BcS5T8UBaKnUmXWXiVNBvTC4iERFggwQKgFNejf+/BiyIlp1PtuohnPMLFfZ37wAX49Jb80TTptmXJIrk3rGoENexTVhNy/x0ct7LrR8rrQFjya8mYIbmgWj9kSfVjMs8SsDMTBb5zZVoqvuZKCkEWHKatpPvNElIyvi4NNm5nM5CLLdd8KdiXIHaNzc6bMxihkd8KtqKtsLpvxJobE14X7AfZH6lAKcI//L1Bx0lfkWuy35OJ24EVEEfK06H2/XSQnbg5DLTPag7pMZNbgPsmDRWL6FCngtVrU8Jx3xUsutzGxE8PmcfaV2QABaTOFW8M0cy0ls2rRipD3ohiqzGR9aNsa8MKu/yzrjxB9mSlZEUuUPkLaySXtTYeGHmwmqMn6/NCM4jXOSPfSkaUbNclMYzmJVNE00K8kkIWa9hbspy2mhEtK9ZJlG21hIjNjBMRckdosFLSShvI7Eqel2OnD01KCuiMiZBbBk0pCiJo8ZpejB0aC0LLlem0mWBrWhuIbni+OcYR1UkDnw4shwhdwjg8bflSUcPrNVnK1xMcgv79aknaGr5qBYop880JDlRBG56TnIoq2j8DwlGYJyA6iONB2H0YsLtiWnNZUxEJqTp3Xe57mGy4jWI519b5SrAdaRt4K6VBOdcnKKzrcSjbkqui7/6QxC4IjTL/xHMsW0iXFgx9S3F0tA5+ut45BtFVIiI57o1fnfqrU//vnZrVz5eHaVtjFttp+5QlFmyWjEmWuOr5JaL3i1A7TxRt5AcAnohOgkZMrydDNMGAXGfJcwSxZWoZQPjG9EKK1n5hkx717Pnxay143om69AUZ9EwArxg15UEe+fPLDffiHQJavLDc8C2LuYj58/K2vQdBuQYKPNeVMS/VMgJC1oNfFCqkQIZF1wddJBUs9ND0MuIbxAt2BziCCW3pyb9aJC8Sbt4Et26wdPhtpweZEnUGikj7RguCeDfYKI0z30GDy0ZqbsDy8Aq5C1XitZF+1TahHwKnbeLKTTW/dKc6NFHZS5dv8MCQO6oKEPCf1au2Ro3gOI7Z0SV5s2fLQ0O7FNcA9YiapyshpRq5pd2XFWR/J9ezy49DhZtzFW7PVbg7V2F+rsKH/6ag8DZTNbJqJxEevFe9rn9yyXvGHhiO5waD277pb4fWdIzbPuOwfRe2B7PsyObAVd/mgPGT7V4PDpj03agG8A8I5mH7eHK+ZyIEajvylBnDPbL/wW+nWYLku3d998BF86ot7p8H+1z+EqgRavXw6dDPUrBUyPXoghaFvTAqqZDK0Pj6wpY0MyvcXSOBryAOY7OP+Lknc/xcXYWTQcI7Hw5aljatLkeHw4NrgOCTpd6PyXw2m7lbofc+HyASjKoOaowAGnv830/96x/v/mSc+Kf/pKJN+qJljW86ZwHzwTFwmPH94bFhELYYAQs7o4xp9GI6betms05zWU0/gzdVQMIrNkEvf75Nb9K7+bTg2vT3U6aryVLJncZV/2IHR884Zjim1/sOAht2r9M7bzZsTQRdamv3xN4UTtCVE8XwBafsbfYv4I9kBwEc8U6CiKVBQgWvN/ool7mdkAvM3wDt/OicBauO0bpP9uPEo4M/p5E8/wPHdS/E)

**Comment by KaelWD** [comment]
Any particular reason you're using `visibleItems`?

**Comment by sanjay-bhuva** [comment]
> Any particular reason you're using `visibleItems`?

@KaelWD we want to keep `visibleItems` number low here. You can think of board columns (having virtual scroll) with lots of cards. Let's say the visible items are 10 for each column. It will be 50 components for 5 columns with their own sub-components.

Not sure if the `visibleItems` is an issue here because if the user is fully scrolled and the number of items changes, you have to scroll up and then back down to render them.

**Comment by KaelWD** [comment]
By default it's automatically calculated from the container height and item height. If you set it too low you'll get flickering an other problems, it was actually supposed to be removed in #16495

> Not sure if the visibleItems is an issue here

It isn't really, it's just slightly less broken without it

**Comment by sanjay-bhuva** [comment]
> If you set it too low you'll get flickering

@KaelWD I am getting a flickering issue if I remove `visibleItems` and `VVirtualScroll` do not have height. You can see the playground demo [here](https://play.vuetifyjs.com/#eNrtVc1y2yAQfpUd9eB2qp+mSS6epJM+QE5pc4lzQGgtESPQALLjevzuXdCPbXnSmdx6iC9mYb+fXRA87aKfTZOuW4zm0Y3DupHM4Y+FArh5pJUw8uN7JlQf+PChQnTAJbP2dhEVyVLiK9SvyfUiAuu2Emm2QlFWbg6X3741r4uI0As34B+FcS2TD9xoKWEuSNkThf+Q2iWG5MEVfCpwyVrpKHEHPjUGoQoS3k8gBBqcH347woTsr3AB+z0kYYZYKJiAs1P0TXbSmGHytIhDc7KuO0PrskPvaNz19ISRQsuNaBxYdK1fFnWjjYMdGFzGoNW9bpXDwg9/q7oLYA9Lo2uY0d7NPAnXyrpQkIVbj/z85DVnFildcYRfFYLRbVmBQ8YrNGBZIbdQ6KIkvhw5ay2C1TWOGVVb55TiCwwpUm+A9SwVq62jnE0leBUHPCEZFISJQeo1ElLLAiQrtuksDm68CauXbkSjxJIpR6krwVdTHwMcGtIMZgWlsJzISWktcsOcUCXkenvmQ7I/Wx+y1ollK+m0ar4680G7YJ3gwJmsB/53WJiUeWZitBiflH1sg3iXaK3Qiskh0GaUG3t/5MmX2xjkwnpx+vg20DakVmlH21meufDScb9tuTDFsfyhiWMRlrb5DeVh2/p2WYl0bhl9Adb2OuPZmZoYd2JwMj0bHyf146T+7yd1oZ6/+Pu7u7Hpro7iqLuuk5o16YvVil7SnfdMz1lYoAdtDmHGz9F17WN6Hp1r7DzLWtWsypTrOrujtczQ7S5qTApd312m39Or66wQ1h3Pp2jrJDd6Y2l7Xog+tKgnJ9/btwT6ZeK9SK862n4qkSy3nveMLyORNZrEID2eBs0/zU9yTwqYrJ0V4TXpId5TQ6VQKzvpJbehj+FN8/H7qwsMHv7sVfZx1LkjvYCInv8CzrMYVQ==) 

Is it compulsory to pass height to `VVirtualScroll`? Is it possible to use parent height?

**Comment by KaelWD** [comment]
That's a separate bug, never tested with so few items.

> Is it compulsory to pass height

No, you can see in that example it's filling the sheet.
