### ISSUE TITLE
[Bug Report][3.1.5] `v-checkbox-btn` visible state lost reactivity

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#16737]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 3.1.4
**Vue Version:** 3.2.45
**Browsers:** Firefox 109.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
See the linked example in the Vuetify Playground.

The `v-checkbox-button` is in a child component. I'm using a computed property as `v-model` of the `v-checkbox-button`, which itself is synced with the `v-model` of the parent via `props.modelValue` and `emit('update:modelValue', newValue)`.

When checking/unchecking the checkbox, the `v-model` is being updated and propagated to the parent correctly, but the visible state of the checkbox doesn't change.

This worked in Vuetify `3.0.4` and broke due to an update to `3.1.5`. I traced it back to `3.1.4`, where it seems to still work.

### Expected Behavior
Visaul state is being updated correctly

### Actual Behavior
Visual state doesn't change

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU8tO4zAU/RXLmwYpiTWvTVRGzKDZz4pN00Wa3IBpYhvbKaAo/86186hpCxLdNPfhc869Pt709I9S6aEDmtG1hVY1hYXfuSBkfUgKpfynD9qCiynC+PYByv1OvtzKVkkBwhLskBU01znlxlehyilhxyMzlvv1PVm6yDAsPWwhZAGjC0YtaxZoxNCUmitLDNjOlTmK0Zb0RENNBlJr2ZIVDrdaSue6x6aUnVXcVvBgLkopjA30Xjv4qC4aA1dO0igC6WlMRxqUrtJHIwVutXcT4FJ8weQ0Iz7jckjg4pw+WKtMxlgn1P4+LWXLbrDGdCcsbyGpZHvzI/2e/vzFKm5smE/BtMlOy2cDGhlzGgfgltevHxFMZcT9lk6wUyppip1xuGd4DEkOoBMNogIN+lPxJ73vBjipnQ3hONEUAy604WJvTnZZGr/HzSzt69N5BHd8O7JcvPxLT6KcGpOdFYHl/f9k9y94NCYoVnXWPYJ3bsWpJtspLZVBy1VQcwH/XRT5NXjKu6LpYHGUfVUY/JWygUJMF6fhqeMaqoxYjXabFou+nQmg5XbB/4eBiTarTlWoPztyrLbBEZ/GM7P4UdA9WBJdzVq87vQI4Jm9JlwEiQQ8+/TS72REF3hjsrQG4sNHN8R09Bbeo79vun0Dnyqj+g==)

### Other comments
Maybe my whole approach is wrong, but this is how I did it before with other form components and it worked. It also worked before with `v-checkbox-btn`. If this is not a bug in Vuetify, I'm open for better approaches.

**Comment by KaelWD** [comment]
```diff
const model = computed({
  get () {
-   props.modelValue
+   return props.modelValue
  },
```

This working before was a bug.

**Comment by frederikheld** [comment]
Thanks a lot for the quick response!

Now I'm confused even more, because my own code had the `return` statement and didn't work. After adding the `return` to the example, it works.

So now I'm lost in the emergent characteristics of the JS ecosystem. I'll check my code to figure out why it behaves different than the simplified example...

**Comment by frederikheld** [comment]
Some thoughs about all the breaking changes Vuetify introduces with the updates: I know that you are working against some internal expectation "how things should be done" to determine if something is a bugfix or a breaking feature. But from the users' perspective it is really hard to determine if something is a bug or a feature in Vuetify (and Vue in general). "Is leaving this out a shorthand for something or just a bug that I'm exploting?". I never really know.

So unless you write really concise documentation about how things _should_ be done, everything that breaks how things _could_ be done is a breaking change from the perspective of the developers who work with Vuetify and therefore should have an SemVer version that reflect that.

Just my 2 cents. I have seen discussions around here where Vuetify devs had a different stance on SemVer. But from an old-school requirements management perspective, things can only be a bug if a different expectation towards the functionality is documented.

**Comment by KaelWD** [comment]
We'd be at version 1000 by now if every "possible breaking change" was treated as one: https://xkcd.com/1172/

Kinda hard to do that when the documentation is written after the implementation. I am planning a set of pages that would cover stuff like this though.

Basically if both `modelValue` and `onUpdate:modelValue` are bound (eg. if you use v-model), then the prop is used as the source of truth and the component does not hold its own internal state. This is how it worked originally but was broken at some point trying to fix something else.

**Comment by KaelWD** [comment]
@frederikheld #16741?
