### ISSUE TITLE
[Bug Report][3.1.5] v-select - selected items have different order than selectable items

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#16732]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Linux x86_64

### Steps to reproduce
The value '2' is selected. Select the value '1' too.

### Expected Behavior
The selected items should be `[ 1, 2 ]`

### Actual Behavior
The selected items are `[ 2, 1 ]`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1PhDAQ/SuTXtQEWnX1QnCjv8HjsgeEWbcuLU1b1hjCf3da2G818QQzb+a9Nw8WPXsxhm87ZBnLPSrTlB7nhQbIt2lpTHyNhSqlnqqp47DByh9aADTV1tg8FWxbNh0W7BjMJPE7wuLzFFNd46Vp8NCb52KnsFclzarVnoyg3TcL/xqnsIZIDKXFDPoeogUYhv02EZ6vh97+sFCMJ+fiKAoqXWWl8eDQdwGWyrTWQw8WVzDAyrYKrijDqzBMEs5PVp7CxPXiLoH7BGbLmx06WpvQ+9DPxagxZwkb6cmX4R+u1fRl+mCPgosARUf3jf4p6BBzRi9r743LhOi02bzzqlXimTBhO+2lwrRu1fOMz/htWjZmXfIHUUvnj2GOTqVvtv10aEm4YMmRhperr990Jpjo7/jjSDu1AuUFlSD+LdrUoq7Rov3T/tnsTyecjVycEaTpJxgo2UbqjTsLtXIx0MXO4b/uU1LzSBC2l0FkSNiJR1KNe2z5DUm1G6U=)

**Comment by KaelWD** [comment]
They're in the order they were selected.
