### ISSUE TITLE
[Bug Report][3.1.6] VTextField v-model.trim eats trailing/leading spaces too greedily

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#16743]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Type something that ends with a space (in the VTextField)
2. Backspace slowly
(repeat but type in the plain input field)

### Expected Behavior
Backspacing up TO the space should not eat the space itself.

### Actual Behavior
Space is eaten unexpectedly.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUUtu2zAQvcqUG9mARbZI0YWhFMmu+y66iLJQpZHNRvyAHDktBF2ht+mFepIOJTdRHCdAdnp6M+8zvBnEtffy0KPYioLQ+K4i/FxagOKQV95PnxMwlbZHNGHCn5S3GrsGmHQNdpKCNpelMHFXClCPw40+PACG2vqezi49rqjlzonAdU191UHkTbvbwjBA3Lv7r76qMa5YZw3jeE6oUIsWCcz9CrXozTDWQXuCiNQnWhvvAsEAAVsYoQ3OQMYHy9Jw7WwkYE+4TPwq+4Jd5+CbC13zLlunkba3NWlnlyE5+hqGFCOwS2COggzIIWpcKVC7DWR/f/9JAtykUHMkDiM2Ys7DRbz8EZ3ld5uEyiMRS8EnmQuXgnMmXIo9kY9bpXrr73aydkZdMadCb0kbzBtnri7khXyfV53fV/Ijny3SkpYYTf49uPuIgY1LsVl4kG5/veRzpFn+g/w0yx5/JclnUor1DxjygLbBgOHV+Cez5yqcjDyrkaz5xiNfttP2Lp4ctY7TQW/+J3xTP6OtnATS9m0yGTfiSUZ2nfbE7T9a2Spl)

https://user-images.githubusercontent.com/12532733/220533188-01cbc0d8-5a2e-4531-94a2-917982b31bf3.mp4

**Comment by KaelWD** [comment]
This doesn't really seem feasible to fix, I suggest `@change="msg = msg.trim()"` instead of `v-model.trim`.
