### ISSUE TITLE
[Bug Report][3.1.6] [Seek Help]:Please tell me that there is no minixs file in the Speed Dial component

### ISSUE THREAD

**Issue by forestxieCode** [vuetifyjs/vuetify#16749]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
```js
import Toggleable from '../../mixins/toggleable'
import Positionable from '../../mixins/positionable' 
import Transitionable from '../../mixins/transitionable'
```

### Expected Behavior
mixins

### Actual Behavior
mixins

### Reproduction Link
[https://github.master/packages/vuetify/src/components/VSpeedDial/VSpeedDial.ts](https://github.master/packages/vuetify/src/components/VSpeedDial/VSpeedDial.ts)

### Other comments
mixins

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/index.ts

Anything commented out has not been updated to vue 3 yet.
