### ISSUE TITLE
[Bug Report][3.1.5] v-chip's close event cannot be overridden

### ISSUE THREAD

**Issue by jarena3** [vuetifyjs/vuetify#16740]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. add the `closable` prop to a v-chip
2. use @click:close to grab the click:close event and call a function that does nothing
3. observe that the v-chip is closed/hidden anyway

### Expected Behavior
I expected that calling a function from the close even would prevent the disappearance of the v-chip. 

### Actual Behavior
v-chip closes regardless of event function passed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUD1vwjAU/CuulwSJOK1olyggunXq2oEwhMQkLv6S7YAqlP9evzhQCm2lbj7fvbt7b3XEz1qTfUdxhnNHhealo4tCIpTvk1Lr4TkAUTI5ogFXLdOo4sqWG07RsuKs2mWA6bzAtXpVrmWyiScFXrxQzhU6KMPrPA2TJ18Pz8YAQmSeXlTx0FaGaYcsdR3QTGhlHDoiQ7eoR1ujBIr8DhGIKyWtQ8I2aA58HIX0N0i/iyZfknNHL4wnaL5AR2gBpOKUcNXEUa2Al0EHwz2UC3V8ETzFoYtfQpN3q6Q/4+BSjIQtcBZ84c93BFzg1jltszTtpN41pFIiXXouNZ10TNCkVmI5IzNyn5RctyV5TGtm3SVNqBXJxqiDpcYHF3h6keHY9uO3nJH29g/kKdiOX2B5Y5V6/z01iaGypoaaP+tfaX9a4UpyswZE+xv3/rKcyZ29Omplh4OuTg3/tZ9gkgwGML2GkH6Kv3X0qcMcXn8CI1AJ0Q==)

### Other comments
I realize that this might be intended behavior, but earlier versions of vuetify (at least v2.x) allowed for capturing of the v-chip being hidden

**Comment by mtermoul** [comment]
Yes, I noticed the same issue. I think that the correction behavior should be: Do not remove or hide the chip and let the event handler remove the chip through reactive data or do something else.

**Comment by lioneaglesolutions** [comment]
This looks like the desired behaviour @johnleider  can confirm if you should be able to *stop* the removable of a closable chip.

I think the best option is to use the `close` slot - example below;

https://play.vuetifyjs.com/#eNqVUU1vEzEQ/SuDOWwqZb2gwiVqoiAunLghDt0etl4nMbE9lu0EoSj/nRnvNm22gMQl2vF78z4m9yfxKQR5PGixEHdZu2C7rFetB7g71l0I5bMMrjN+nMqsdiasviXjt6AsJg3JYr7gT1LwtoCXxbJqFHrgn2UrXG/qQqmVicrqVsBaWaP2MmUMROjxK+Yd2RDSPAdorsIOT2OoScgSr3u0evV5/Jgweby042HofWVBY1LRhAxJ5wPDxgWMGU4Q9QbOsInooKJDVkymbimDS1tYMj6rvmhrEb5jtP2b6uaZcmlHxNkNLFdw4hQMotXS4nZW9ci4H3i8fOZwQxwKIuZiyEIlgvyR0NN/WVTaEUitWAy6/EYZeW7FLueQFk1z8GG/lQpdsyasiQefjdN1j259K2/lu7qzYdfJD01vUn4JS51c/RjxZ9KRjFsxf+GRzebX33xGmOTfy4+D7PjEkq+kGtI/6lhH7Xsddfxn/An3TxUmlFc12JpufKbLWuP3aXJUlcpB758S/lc/Z7wsArz9wCbnubjKSK5lTzz8BsgdMjU=

**Comment by johnleider** [comment]
This is intended behavior. The event is just to inform you that it's happened. This is the recommended workaround: https://github.com/vuetifyjs/vuetify/issues/16740#issuecomment-1532196447

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jarena3** [comment]
understood, thank you!
