### ISSUE TITLE
[Bug Report][3.1.6] Badge is on top of text when used in VTab

### ISSUE THREAD

**Issue by Bjornar97** [vuetifyjs/vuetify#16747]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-tabs element, and put v-tab elements inside it. Inside the v-tab element, put a v-badge element.

### Expected Behavior
The badge is shown top right, and not blocking text.

### Actual Behavior
The badge is on top of text, hiding the text behind it.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUEtuwjAQvUrkNbEFrVoJpYjeoTvMIiRT6oIdy55QVYi71+OYNAlqJXZ+H795M5sze7WWn1pgS1YgaHssEVbSZFlxyktr4zMCXSqTUMRY7nyPJXZMTyTTrqz3kFWNQTD4ItlcslUhEj8yv4HHX0yecVzKJ1u2mMoJX/sQ7OsS6BYpxGDBAH3llMXMA7Ykk6GjAmAzprRtHIYgyz99Y8KBzpQnk+AlW2aRIS5ckLBkH4jWL4VojT3sedVosQ6acK1BpSGvG71+4Av++Cxq5XHIc/A637nmy4MLEyWbDcJRvX//NSDJIXfOn7rYRFHkTZQI+SdwuQNTgwP3b++Jd9R9ot30p5kXaS7hlkdlDn5yxsrHE26u1e5aTCvDYwD93tKQy4x15cK4+IFtfwC2vOpX)

**Comment by xyos** [comment]
you can add the `inline` prop to `v-badge` to make it work:
https://play.vuetifyjs.com/#eNqVUkFuwjAQ/IrlM7EFrVoJpYj+oTfMISRb6oIdy95QVYi/d+0YlAS1Um+ZGe/M7CqbM391Tpw64EteIhh3rBBWyjJWnorKufSZgKm0zShhrHbhhq/MgEjUrmr2wLQ9agusbi2CxRfF54qvSpnl0cwbBByY0puxa46Jz9hiKmd8rRXhrXUE/T6lHOxJMNReO2QBsHPUqock8RnXxrUeycSJz9BautE5eqksBMWXLDGRoyNGrPgHogtLKTvrDntRt0auSZO+s6gNFE1r1g9iIR6fZaMDDnkBwRQ7334F8JSo+Gxgjvr9+7eALJPvXDz1tpmKlndWkvxP4AsPtgEP/s/ek7ej7hPtrn/MvCh7oVvSL3AIkzPWIZ1wc632r8WMtiIZxOltDLnMeF+O4tIA3/4AcH7q0g==

**Comment by Bjornar97** [comment]
Cool! Thank you. I did go with position absolute and put it in top right corner. But it is good to know about this too :)
