### ISSUE TITLE
[0.15.3] Select Tags documentation, items missing

### ISSUE THREAD

**Issue by ExCluSiv3** [vuetifyjs/vuetify#1675]
### Versions
0.15.3

### Reproduction Link
https://vuetifyjs.com/components/selects

In the documentation of Select Input, in the newly added "8 Tags" section, you forgot to bind the "items" arrray to the 4 Selects. So the examples aren't working.

**Comment by KaelWD** [comment]
@ExCluSiv3 This should be moved to the socs repo: https://github.com/vuetifyjs/docs

**Comment by ExCluSiv3** [comment]
Sorry, didn't know there was one.
