### ISSUE TITLE
[Bug Report][3.1.6] v-img src using computed value is not reactive when using defined properties

### ISSUE THREAD

**Issue by tmountjr** [vuetifyjs/vuetify#16753]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a `v-img` component with a dynamic `src`, as in the [`VuetifyImageProvider.vue` file in the provided repo](https://github.com/tmountjr/img-src-reactive/blob/main/components/VuetifyImageProvider.vue).

### Expected Behavior
As `cip.imgUrl` changes, the `v-img` source should change.

### Actual Behavior
Regardless of the value of `cip.imgUrl`, the image URL does not change. (Recommend cloning the provided repo and running `yarn dev`, and inspecting the images on the page to see the actual source URLs.)

### Reproduction Link
[https://github.com/tmountjr/img-src-reactive](https://github.com/tmountjr/img-src-reactive)

### Other comments
In this example, the custom image provider class uses `Object.defineProperty` data descriptors rather than assigning those properties directly. (In my actual use case, there are dozens of properties and it's easier to loop through a defined list of property names and create class props for them dynamically.) I have noticed that directly assigning the properties makes the image source reactive, but using `defineProperty` does not. In either case, however, Vue detects the change to the `imgUrl` property and the defined properties, so my expectation would be that the image source would be as reactive as the `<p>` tag above it that changes every time one of those properties changes. 

Took a while to figure out where this behavior should be filed - if it was a bug with Vue, Vuetify, Nuxt, or just Typescript in general. Given that it behaves as normal using Nuxt and vanilla HTML components, with the `defineProperty` class, but not with the `v-img` component, I'm inclined to think that there's something about `v-img` specifically that is causing the reactivity to be broken.

**Comment by KaelWD** [comment]
This is a bug in your own code. You're using arrow functions in `Object.defineProperty` so `this` is the original object, not the reactive proxy. Vue can't observe modifications to objects not made through this proxy.

> it behaves as normal using Nuxt and vanilla HTML components

Only because the VuetifyImageProvider rerenders when you toggle a checkbox. If you have another component that just wraps `<img>` it won't update because it doesn't see any changes to its props.
