### ISSUE TITLE
[Bug Report][3.1.6] VTextfield Error works unexpected 

### ISSUE THREAD

**Issue by derHodrig** [vuetifyjs/vuetify#16756]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a Texfield and make a rule with follwing regex 
`^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/g`
which you also can test in https://regexr.com/
It should find/ allow string with one upper char, lower char, number, special char and min 8 chars

```
const PASSWORD_PATTERN =
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/g
const passwordRules = {
  pattern: (value) => {
      if (PASSWORD_PATTERN.test(value)) return true

      return 'show some specific pattern error'
    },
}
```

and then inside the textfield

```
<v-text-field v-model="password" :rules=[passwordRules.pattern] />
```

1. Type `Qqqq123!` should work fine
2. add now several `!`

you will notice the error message pops up and hides.

### Expected Behavior
Error message should not be shown, since the criteria is met.

### Actual Behavior
The error message is shown and hiding after each input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUn9v0zAQ/So3a9B2ahJGEUJVs7US/Aulm4REU1BILm1YYru2kzKqfHfO+VG6biAtf/nund9795zlns2kdMsC2ZhNDOYyCw1eBRxgUjqhlPWxLvIw5W1V1wZ/GSdJMYuBQBFj5gcs1+uAwVgVGWp/KUOtd0LFC1u6MjQGFV+B95cmTstDATDPMNQI5l4ifN5ut5evR2f2O4x7x/Mnl80GAZUSyslR63CNoDeiIHdSSCgkhDwG4i/xKbaJd7SgLZrVJ95RJFTqSKXSgEZTWDjNpVAG9qAwgQoSJXLoUZa9gEeCawPz2c3Nl0+L99/ns9vbD4uP4Ft+71v/2ncvlqHzezVojjPna3sMgrjtTc/PXlxcv1wNLEqzhHSt/bthde6tOxlKHXxrot/rDbrmg/AJ3lvp9g3G0C/DrMAB+FcNYL80gf6pY9egNu3wgCRMoTgYVVCK3bW22aO4d6BFTsFLjNIkjTq55l0oFTteDQNe1Wl6TZwUJBuyJkt6BOn+1ILT71j7ClpAB2zcOQ0YZWzrgG2MkXrseQWXd2s3Erk3JcxTBTdpjk4s8unIHbmvnDCTm9B9Q0+uzTHsos6dH0rsNCoSDhi5O2iYNLn/l04LE/2l+7ahbVuW8hGVR/wlKkchj1Gh+q/9k9mnVjgZebSGlaaUK0o2S/mdPgk10nWgy87hs/bLU+7WBPb2yopUQ/bAI6nW99jqD2TzacU=)

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

> JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags set (e.g., /foo/g or /foo/y). They store a [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) from the previous match.

**Comment by derHodrig** [comment]
Thanks, and sorry for that unnecessary issue
