### ISSUE TITLE
[Bug Report][3.1.6] v-data-table no longer supports nested keys

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#16750]
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
In Vue 2 I used to be able to do the following:
```
const items = [{
  someKey: 'someValue',
  someObject: {
   someNestedKey: 'someNestedValue'
  }
}];
const headers = [{
  key: 'someKey',
  title: 'Some Key'
},{
  key: someObject.someNestedKey
  title: ' Some Nested Key'
}];
<v-data-table :items="items" :headers="headers">
  <template #[`item.someObject.someNestedKey`]="{ item }">
    <p>Here's a message</p>
   </template>
</v-data-table>
```

In Vue 3 I now get errors in the console:
```
runtime-core.esm-bundler.js:573 TypeError: Cannot read properties of undefined (reading 'someNestedKey')
    at MyTest.vue:34:108
    at renderFnWithContext (runtime-core.esm-bundler.js:868:19)
    at renderSlot (runtime-core.esm-bundler.js:3025:55)
```
If I console.log(items) I can clearly see the items are there

### Expected Behavior
Nested keys to work as they did in Vue 2

### Actual Behavior
The nested keys do not seem to work.

### Reproduction Link
[https://github.com/DivakarSS/VDataTable](https://github.com/DivakarSS/VDataTable)

### Other comments
I realize v-data-table is in labs and this may not yet be supported.  In case it's supposed to be supported and actually is a bug, I am submitting this ticket

**Comment by MajesticPotatoe** [comment]
Seems to work fine.
https://play.vuetifyjs.com/#eNqVVctu2zAQ/JWFisIJYEl+NUUMp0jRNEBuPRQFiigH2qJt1hIlkJTT1NC/d/nQy1KL5Kblzi6Hs0Pq8eQdC6rY9iX4Jb2lx9I8EwpOsBGUKPrD5qCErchSGDnsKOINMMMvTrmSr0QRCQlZ99ChXsSSiNPfpmiTcanAZeGmy+jiFHEAtacpXWL7mG5JkajvNh4lbLdXIyjHGtRsjUi9ABAEQbNqQGZNM9BBGfHyMuLe2Puc5wEyQGFWiqZ5ggQ+acTq6JM8N58mSAnjsEmIlDeRlxJ/EXkuadIxUcRXZJ3QahFguackpkIXuK/Ia2UZ7qdzMZWSCtVJ6px/JElBNQB7Byyu8pGqN45UTRre6ZrAYbHqZJrgSRueuuDhDk4nAzXtS1SiSq7CjgJ2qX20Sg1c1HJYnTCwQnXKMZQbwXIFkqpCp2ujCLptO8MYwjqhUgKt8Kh7u1lyYkZ+L7I/lMPPbFcINXIz1eS0PVi8hKmzAxqCJJlgFO0w/XDt1rZELeEqmNQQscb8bOHiXGSKMr6ERQ1hIsN4aiLbuUvoYUONZVOQhMfPbLMfYjUbYDWbf2yzuj5nVadbrOavZPUVTcrEEJP5EJOrWZvJtC9QtW9NpYFYKpYr+uipmqNzez1GUEwlRrG70RgI3l0sG0lF9BzhQF8wcsatrnRTc2dNARfTyWSHbhJHxneXdZ0+db/oiztgDatO3IfeE+zdaog6DPVDMTowI08f+M2q1IE65frgB9QPLt43SC2ohaGWq9DeILw7+E7Z64P3LsdnPOP4XpmxRy6Br0f99kX6wdcxvjtK5XIZhgXPDzv9Ioa3mAtFwRVLqR9n6e08mAcTnyT5ngSLMGZStdMBlam/FtkzCo8bR54bvdlDP9P/2selsf00uLJtq98QthxsZf4Pb+/n67LBpqF2CxW+oBz9SMV/NTnDDulyBulpU/1ZcFwJ4wd5NqmNNKczd0LHbxItZTwwDXQ1uqP0yrHX4Yi7mjrv6S/jsYeA

**Comment by UglyHobbitFeet** [comment]
Hi, thanks for the quick response!  Your example seems to work because you are using the item-value as the nested object.  I took your example and tried to make calories the nested object and it failed with the same kind of errors I was seeing

**Comment by UglyHobbitFeet** [comment]
fwiw my real world data has multiple nested objects (depending on the table column) and I use return-object in the data table

**Comment by UglyHobbitFeet** [comment]
I think I understand the difference now. I have to add the .value to the right of the item.  I thought .value was only necessary in composables in the setup script, not in the templates.

Thanks!

**Comment by MajesticPotatoe** [comment]
item-value doesn't have much to do with it (it just tells data-table which property to use as the unique id if you don't have an id prop) that of which also supports dot.notation.

here an example targeting calories as a nested job with return object:
https://play.vuetifyjs.com/#eNqVVd9vmzAQ/lcspolWCpBf6rQonTqtq9SXaQ/VpKn0wYFL4hYMsp10XZT/fXc2EEhY1b5xvu/Onz9/Pu533nYDRixfwkftzTyRl4UybMcSBdzAL5dje7ZURc78CuvH8gAs8EuCNPqNKK5Zxhcn6IgWsSSW8McWJYXUhlVZdtlldLaLJWNmDTnMsH0KS77JzJ2L/Uys1sZn+wGBDlsjkhYYC8PwsGpBdo0YULCP5f48lt7A+1qWITJAYeYG8jJDAl8IMd8GvCztpw1yLiRLMq71ZezlPJjGXpW06ZQbHhi+yKBeZGy2Bp6CooLqK/ZaWYH7US4FrUGZTpJywZZnG0CA5Dm0kwrMRsmgWDxCYtxybBoysWkOwj5QnzDhWaEE6NCANthvZ9ujBocTUNkPzELKvjk0u8NwxthuZ3tYLt1OexSxrp5HHfHcUluVWkhcJCWdxBg4jTvlGOpEidIwjQeldOMxBcu2qayXnIlqEdFF99S7sgFJh265UcVfkOx3sdoo41d2IHLkLJHO2KhyEnqpOiJl6JRYPfYHTBbGCeKP/Bq65BhfhMOmUi2wbDyt4lIVBoScsWkDEarAeGQj16XL8zYB+whyprlMn0Wy7iM77iE7nnxqs/p8zKpJt1hN3sjqO9peqD4mkz4mF+M2k9GpQPW+DZUDxFFxXNFeD/X1Vu+nuV1mhMmsYtd4ORynAZb52nC6XvYELxgR0VCk9ZA41Fw7r7Cz0XC4QpOprZCr86aOTn1aVD0L3cA6b+EUf8Nxg1ZXFKOvKSrSgVmNToE/nVQdaCXfKfgWRWRnHw9IUtXBUNB55F4Xviscf+5p4Zss8e9QSByD9u7jKoFDqRmpMf1HKMZxZkypZ1G0keXTigZtdIW5SG2kETkEaZFfTcJJOAx4Vq55OI1SoU07HYLOg4UqnlF93Dj2qvu3e9D0/98+VRrbj8IL17b+u2HL3lb2t/P+fgGV9TaNyDKgAgUSTQnqVU2OsH26HEFOtKl/WHhdmZBP+uimEm1PZx8Gxe8SLRcytA2oGt2x9/YDr8MRd7V13sM/1N+lmQ==
