### ISSUE TITLE
[Bug Report][3.1.6] v-navigation-drawer `$refs[refName].$el` does not return the Element

### ISSUE THREAD

**Issue by MetRonnie** [vuetifyjs/vuetify#16766]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.50
**OS:** Windows 10

### Steps to reproduce
Set `ref="<name>"` attribute on a `VNavigationDrawer`, then access `this.$refs[<name>].$el`

### Expected Behavior
The `nav` Element is returned

### Actual Behavior
Some kind of object called `#text` is returned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUu1q3DAQfBUh8iOBs0Tb0MLhlit9jDg/FHvvqpy0EtLaaTny7l354z5pocYYz45nNBrr6SC/x6iGHuRa1gQ+OkPwrUEh6qEyMY6vI/DG4oxGjGawO0M2YNUl8wZp4YSIkLxBQDqNEmy/NnL+UC7zo19D7PhCeBIIMZhkDRLLQk/OInQnYblaZ3Jm1pvq8ZLZtM62e6bagDk4UC7s7u84QlZTAnUH7uFccwxSrh9FLSgIlglw4C92Uusx6akKxjddLLUxd+ytgKnRWp81zTC3yUbid/gVQyLRwdb0jsShyDpDRtw/TKAUSX1CcRDz3sR7mfOD71ofnRqUK2l9seMEUb3mgPyLR5NmJnIj14ttI/kMFNzIn0Qxr7XuMe53qg1eb5jTqUeyHqou+M0n9VE9ftGdzXQ+V5B99ZLCW+aKX9l+dWZOdvv7bwvMNPt+UJ8n23lULG+sNPsPkKoE2EEqB+ofua++vch+xd3kX6rlLvkA7vNVjW0eK3xaov3XxrxFNRoU9XNZ5H0lp3C83CiQz38A9vwoWg==)

**Comment by carlosyan1807** [comment]
Vuetify Version: 3.3.12

same

**Comment by KaelWD** [comment]
https://vuejs.org/api/component-instance.html#el

> For components with multiple root nodes, $el will be the placeholder DOM node that Vue uses to keep track of the component's position in the DOM

**Comment by MetRonnie** [comment]
Shame that there's not much info about this in the Vue docs. I've come up with a couple of workarounds:

1. Set the `id` attribute on the `VNavigationDrawer` and access the `nav` by `document.getElementById()`
2. Use `this.$refs.<name>.$el.nextElementSibling` - see https://developer.mozilla.org/en-US/docs/Web/API/Element/nextElementSibling
