### ISSUE TITLE
[Bug Report][3.1.6] v-table removes all internal html tags (using esm script)

### ISSUE THREAD

**Issue by dipbhi** [vuetifyjs/vuetify#16772]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Use `esm` library in the script
- Add `v-table` in the html

### Expected Behavior
Display a formatted table

### Actual Behavior
Only `table` tag is rendered with all the text content showing directly underneath. `thead`, `tbody`, `tr`, `th`, and `td` tags get removed.

### Reproduction Link
[https://jsfiddle.net/dfzr50cw/1](https://jsfiddle.net/dfzr50cw/1)

**Comment by dipbhi** [comment]
This is not limited to just esm version. Using non-esm library has the same issue.

https://jsfiddle.net/dfzr50cw/2/

**Comment by KaelWD** [comment]
https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats

**Comment by dipbhi** [comment]
As pointed out by @KaelWD, this is caused by dom template parsing limitation.

**For anyone who might be looking for a solution.**

Changing `v-table` tag to `table` with `is="vue:v-table"` attribute renders the table correctly. 

https://jsfiddle.net/g9jwdcap/
