### ISSUE TITLE
[Feature Request] VDataTable mobile support

### ISSUE THREAD

**Issue by amirshaneh** [vuetifyjs/vuetify#16784]
### Problem to solve
mobile view support for Data Tables same as v2

### Proposed solution
mobile view support for Data Tables same as v2

**Comment by lingjiawen** [comment]
+1

**Comment by ckmbks** [comment]
+1

**Comment by gvnnunes** [comment]
Please, when this feature will come true ?

**Comment by gvnnunes** [comment]
worked fine for me, thanks!

**Comment by gvnnunes** [comment]
to avoid css errors, i recommend to use the code like this

```
<template #item="{ item }">
  <tr class="v-data-table__tr">
    <td 
      v-for="(value, key) in item.columns" 
      :key="value" 
      :data-label="headers.filter(e => e.key === key).map(e => e.title)"
      class="v-data-table__td v-data-table-column--align-start"
    >
      <template v-if="key === 'specific key'">specific: {{value}}</template>
      <template v-else>{{value}}</template>
    </td>
  </tr>
</template>
```

**Comment by johannesss** [comment]
> For anyone else looking for this functionality until it is fully implemented, here is how I fixed it:
> 
> CSS:
> 
> ```
> @media screen and (max-width: 600px) {
> 
>   .v-data-table thead {
>     border: none;
>     clip: rect(0 0 0 0);
>     height: 1px;
>     margin: -1px;
>     overflow: hidden;
>     padding: 0;
>     position: absolute;
>     width: 1px;
>   }
> 
>   .v-data-table td {
>     border-bottom: thin solid rgba(var(--v-border-color), var(--v-border-opacity));
>     display: block;
>     text-align: right;
>     line-height: 48px;
>   }
> 
>   .v-data-table td::before {
>     content: attr(data-label);
>     float: left;
>     font-weight: bold;
>   }
> 
>   .v-data-table td:last-child {
>     border-bottom: 0;
>   }
> 
>   .v-data-table tr:not(:first-child) > td:first-child {
>     border-top: medium solid rgba(var(--v-border-color), var(--v-border-opacity));
>   }
> }
> ```
> 
> Data Table:
> 
> ```
>  <v-data-table
>         v-model:expanded="expanded"
>         :headers="headers"
>         :items="positions"
>       >
>         <template #item="{ item }">
>           <tr>
>             <td 
>               v-for="(value, key) in item.columns" 
>               :key="value" 
>               :data-label="headers.filter(e => e.key === key).map(e => e.title)"
>             >
>               <template v-if="key === 'specific key'">specific: {{value}}</template>
>               <template v-else>{{value}}</template>
>             </td>
>           </tr>
>         </template>
>       </v-data-table>
> ```

Many thanks!

**Comment by donalmurtagh** [comment]
> For anyone else looking for this functionality until it is fully implemented, here is how I fixed it:
> 
> CSS:
> 
> ```
> @media screen and (max-width: 600px) {
> 
>   .v-data-table thead {
>     border: none;
>     clip: rect(0 0 0 0);
>     height: 1px;
>     margin: -1px;
>     overflow: hidden;
>     padding: 0;
>     position: absolute;
>     width: 1px;
>   }
> 
>   .v-data-table td {
>     border-bottom: thin solid rgba(var(--v-border-color), var(--v-border-opacity));
>     display: block;
>     text-align: right;
>     line-height: 48px;
>   }
> 
>   .v-data-table td::before {
>     content: attr(data-label);
>     float: left;
>     font-weight: bold;
>   }
> 
>   .v-data-table td:last-child {
>     border-bottom: 0;
>   }
> 
>   .v-data-table tr:not(:first-child) > td:first-child {
>     border-top: medium solid rgba(var(--v-border-color), var(--v-border-opacity));
>   }
> }
> ```
> 
> Data Table:
> 
> ```
>  <v-data-table
>         v-model:expanded="expanded"
>         :headers="headers"
>         :items="positions"
>       >
>         <template #item="{ item }">
>           <tr>
>             <td 
>               v-for="(value, key) in item.columns" 
>               :key="value" 
>               :data-label="headers.filter(e => e.key === key).map(e => e.title)"
>             >
>               <template v-if="key === 'specific key'">specific: {{value}}</template>
>               <template v-else>{{value}}</template>
>             </td>
>           </tr>
>         </template>
>       </v-data-table>
> ```

It's worth mentioning that this doesn't exactly replicate the mobile support in v2. Specifically in v2 the default mobile breakpoint can be changed via a prop, e.g. `mobile-breakpoint="1100"` or `mobile-breakpoint="sm"`, but this will always use a breakpoint of 600px.

**Comment by vollyimnetz** [comment]
The solution to override the item rending was a little bit to invasive for my taste, so i created another solution. An extra component to create some styles based on the the header informations.

In my Code
```
<v-data-table class="HistoryTable" :headers="headers" [ ... ] >
<MobileTableHelper cssClass="HistoryTable" :headers="headers"></MobileTableHelper>
```


MobileTableHelper.vue (adjust to your needs)

```
<template>
    <span v-html="styleOutput"></span>
</template>

<script>
export default {
    props: {
        headers: { required: true, type: Array },
        cssClass: { required: true, type: String },
        maxWidth: { required: false, type: String, default:"600px" },
    },
    computed: {
        styleOutput() {
            let result = '';
            if(this.headers.length===0) return result;
            this.headers.forEach((element,index) => {
                result+= '.v-data-table.'+this.cssClass+' td:nth-child('+(index+1)+')::before { content:"'+element.title+'"; display:none; }'+"\n"
            });

            result+= `
@media (max-width:`+this.maxWidth+`) {
    .v-data-table.`+this.cssClass+` thead { border: none; clip: rect(0 0 0 0); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; }
    .v-data-table.`+this.cssClass+` td { padding: .5em .5em .5em 8em !important; position:relative; border-bottom: none !important; display: block; text-align: left !important; width:100%; height:auto !important; }
    .v-data-table.`+this.cssClass+` td.v-data-table__td::before { display:block; position:absolute; left:0; font-weight: bold; width: 8em; text-align: right; padding-right: 0.5em; }
    .v-data-table.`+this.cssClass+` td:last-child { border-bottom: 0; }
    .v-data-table.`+this.cssClass+` tr:not(:first-child) > td:first-child { border-top: medium solid rgba(var(--v-border-color), var(--v-border-opacity)); }
}
            `;

            //console.log('style on v-data-table "'+this.cssClass+'" added:'); console.log(result.trim());
            return '<style>'+result.trim()+'</style>';
        }
    }
}
</script>
```

**Comment by Sko007** [comment]
My styles which are written above are not applied to the v-data-table.

**Comment by anselmoinfo** [comment]
Any news?

**Comment by RATACIA** [comment]
bruh

**Comment by vivjamba** [comment]
bruh

**Comment by cogwurx** [comment]
Are there any updates for when mobile support will return to the vDataTables or is the community expected to continue to use workarounds for a feature that should be backed in? An update would be great since the Vuetify roadmap doesn't have anything on it for vDataTables this year.

**Comment by j-osephlong** [comment]
bruh

**Comment by anri-vin** [comment]
Where is responsiveness when I need it so much?..

**Comment by Jo-Philips** [comment]
It's actually hard to believe that so little priority is given to responsiveness in 2024

**Comment by blalan05** [comment]
Using V2 as an inspiration, I used a v-if on breakpoint and VDataIterator to switch... it took an hour... nothing is stopping you from doing the same.

**Comment by joelmandell** [comment]
So it seems this is added from version 3.6.0 🎉
