### ISSUE TITLE
[Bug Report][3.1.2] custom-filter not working with Autocomplete

### ISSUE THREAD

**Issue by drennenb** [vuetifyjs/vuetify#16789]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 3.1.1
**Vue Version:** 3.2.46
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
type partial string such as "F" into autocomplete.

### Expected Behavior
Should show list of hits in dropdown

### Actual Behavior
says "No Data Available".  Error results.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE1P4zAQ/SujXChSk6jA7qEqFahauCA4LBdEenCTKfU2sbO20xaV/vcdJ07rfnFYKVI8H+/NzMs47+vgviyjRYVBPxgYLMqcGRwmAmCwCFlZ1sfaKBgXzmqClZGpJAAabN0AfU4k+jYJtCEinQReKK20kUU45blBRSmN/VCbfmIqc2njyxmR+QHLHRpucqSoYMVxcMHyygbZZLJHmbMJ5uT/bbvaBYaDeH+Qdlxyb+etc2olBrGnEJk6Vbw09RlXpVQGMpyyKjewtsCMGda5bM4ACk2lRGsBNAL14X3X5RrsUH24eCABeMYuumAHsY4nOvOsDz3YdE8AHlGqD+4BHu8d4Oo04Bknium5h3j+5RDXpxEjlvOpVMKvMmqr3JyrsoQ3qeZelTeH+OEhxu60sS/rtu8CzUxmJJBTzN8W6Niv3YW/FarPV1wZ4iSHPW31bjZJaAOG3C8C4bZOimxvkZFPcolqxDR2Lk8BXpeyBdjWvwdoZCqd2fKE2TZ1iNmh3C64xiIuMly9TDs7mksYQtiDr68dBtq2zqa3uY2wJCY9g9hb0kQE3YAXdlNpvcvoj5aC7n0tWOICdGW3kicB/RisnQQzY0rdj+NKlPOPiK5LfEexWFXC8ALDTBZ319FVdPMzzrg2vj9CXYQTJZcaFVVMAvexa3LDp5/nCrgw8fYiR+tcIV1nbXmP+GIqskAVKiSNlP2tfNP8Qe7eAAexoyFahUnQnIu5PtAy1bWO7m7/z3Q1g4WPbZVNN2i6o3o1Ihj/A713zS8=)

### Other comments
The example uses the Vuetify example code for custom filter on an autocomplete.

**Comment by erikwrede** [comment]
The problem in your repro is that `item` in the `customFilter` function is no longer the entire item, but instead `item[item-title]`. You switched the parameter order in your search function:

https://github.com/vuetifyjs/vuetify/blob/0e08cf4f5baf10bbf27a0217da7e2b76a35cb8b2/packages/vuetify/src/composables/filter.ts#L20


I fixed it for you [in this Playground](https://play.vuetifyjs.com/#eNqdVE1P4zAQ/SujXChSk6jA7qEqFahauCA4LBdEenCbKfU2sbO20xSV/vcdJ07rfnFYKVI88+bNx8s47+vgviiiZYlBPxgYzIuMGRwmAmCwDFlR1MfayBkXzmrA0sipJAIabN0AfU5J9G0SaEOJdBJ40LTURubhjGcGFYU09kNt+oFTmUmLV3NK5gM2d2i4yZBQwfJjcMmy0oJsMtlLmbEJZuT/bbvaAcNBvD9IOy65t/PWMbUSg9hTiEw9Vbww9RlXhVQGUpyxMjOwtsSUGda5bM4ACk2pRGsBNAL14X3X5RrsUH24eCABeMouumAHsY4nOvO0Dz3YdE8QHlGqD+4RHu8d4eo04RkniumFx3j+5RjXpxkjlvGZVMKvMmqr3JyrUsGbVAuvyptj/PAYY3fa2Jd123eOZi5TEsgp5m8LdOzXfsWV6cLfEtVnc7TOrd7NJgltwBD4IhBu64BIsSqy/UVGPskK1Yhp7FyeIr1W0ifZEb4naWRqOrfNEG/b2CFnx3I74RqMuEhx9TLrbJmXMISwB19fOwq0nZ2LbkMbeUlSegaxt6qJCLoBz+2+0pIX0R8tBd3+WrbEAXRxt8InAf0erJ0Ec2MK3Y/jUhSLj4guTXxHWKxKYXiOYSrzu+voKrr5GadcG98foc7DiZKVRkUVk8B98jq54bPPcwUcTHl7kUvrXCFdam3zHuWLqcgSVaiQJFL25/JN8wexewMcYEdDtAqToBkXC32g5VTXOrob/j/T1RksfWyrbLpB0x3VqxnB+B+1LM+f)


However, I believee that the docs on this could be improved, as they don't show any explanation yet. Happy to PR something if someone can guide me to the right place 🙂 
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/9725143/221805980-6d01403f-7e86-41fd-a748-11360fa21797.png">

**Comment by s-rigaud** [comment]
@erikwrede I think you can edit the value here 😃 
https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/filter.json

**Comment by drennenb** [comment]
Thank you for the fix!  Yes, the documentation example does not work with latest version.  Also curiously, it DOES WORK with previous versions.

**Comment by KaelWD** [comment]
> it DOES WORK with previous versions

There was a bug where it would pass the entire object to the first argument if item-title was changed: #16403

**Comment by KaelWD** [comment]
This example can actually be replicated with just `:filter-keys="['raw.name', 'raw.abbr']"` instead of custom-filter.

**Comment by gentlekenny** [comment]
> 
This is the best answer, I highly recommend this approach and thanks KaelWD for this.
Note to all others : **raw** is raw and leave it like that, just change the attributes you want filter to be applied on.

**Comment by gentlekenny** [comment]
Thank you @KaelWD. This is the best approach and it should be highlighted.
Note to all  : raw is raw and leave it like that, just change the attributes you want filter to be applied on.
