### ISSUE TITLE
[Feature Request] File input overwrites existing files

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#16785]
### Problem to solve
It's likely people will add files from different places on the harddrive needing to add files multiple times.

### Proposed solution
Add a flag, making the file input component not to overwrite existing files inputs when new ones are but instead adding them to the list.

3 years old:
https://stackoverflow.com/questions/58881461/vuetify-v-file-input-multiple-files

**Comment by nekosaur** [comment]
The `v-file-input` component is a simple wrapper around `<input type="file">`, which does not support this use case.
