### ISSUE TITLE
[Bug Report][3.1.6] v-text-field does not show value if not focused

### ISSUE THREAD

**Issue by Bouni** [vuetifyjs/vuetify#16788]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Windows 10

### Steps to reproduce
Fill all 4 v-text-fields, the fifth is calculated from the values of the other four. 
No value is visible in the fifth v-text-field unless you click on it, when you click somewhere else the value disappears again.

### Expected Behavior
The fifth v-text-field should show the value

### Actual Behavior
The fifth v-text-field does not show the value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVVu9u2zYQf5WDUDTyaktOO/SDFgdZseXzgAz7EhmDKlExV4kSxJOTLPDb7E32YrsjRUmW7cLDVqAFEpn3h8e7H++Od//i/VjXwbYVXuRdoSjrIkFxHSuAq+0iqWuzNESZSNVRltFUj5AWidar2CtxcRl7kAml7e5O61dZituqKQcWAJmqMlFEeVOVP9FptJ2Xv2e0jr1TmmzJaSKtj2ti1VnE6jP2sOqskdZpW7otSYW+Y3HYR3cVGggcQET1CDFhsbsKR5gSqdNG1ghaYMtiWdZVg+BQAo4OYi8IHYdvJvZ+6DVfoBE57KziBQkv2GxaKY2GZ4KGFWv55LY32xNyrMeEHVgnRKd2ETL7bA7XBkiheXPP+kyw1MEfulKUYS+MTtwJdOxFYDjMM4FGtNgg1joKw1bVnx6CtCrDG5KFTavYkUVWlTfvgnfBcpEU9SYJvg8zqXEsDoQuFx/parRo6ODYm4/OQJk/nzqnE5P5y+C9Ndux2OSBqZDsb0WzaITKRCOaz7o/0T0WwkTlIAw+eherHSFbSPVJT0BNtQH03nn4r+IrpQqMAd69toeMc/CgO5gOkFYF0D83gMu3VP5lRitaDDWyXaB4wkUuRZENRRRtk6J11cwFO66wG6nqFkn4SpQS/Yu25tzsu8XFHF6JrVAYYNI8CAyMrdnYAj7XbHxa/9ycJD6ThMCokxTHwpryWD6R7LdKRWNBtJEZpZXARJpAseFEdfJrLvUhxFEzIFz+Z6D4Ps4EilXPB2raAr9loOwDcAZMVvFLZ9MHqb9KkM7MJav4pTPp6wRp8vAXyUdREPsOW+rP6ljwZO3s4P9bjHtjxYmh4gUeE0w3bljoXlgaJdz7XTdVrekFz+galPiFKd+8Ja7VRnCHjVQP5tFzbWWPaYtowjrQIiRH9G428oGzrXfhZyK0bx6w2Ju0/e7p3ePbJN7nu/qfco/pmhsm1tp6FIZwJ/BP0UVFbrnD4VEo5diqIlALQe+9MgD7/gxW1xbNwO2Yg2+LhEUGVJn7VsVZX5EjNDa5CcjU3WEYYM2Qg/bx7139QDNCulGCgDUJaX3UkpwThKUmTBu4peShn7//4pHCfhGd32zS+n4/dX6gGTdHW6cGimVrA6l/n2dzyHEOSL+I6yFujhz8PIPXr0mBv2jWiH3oVFwCIZN5DquhQnwlHoEP9GnDGwKL/97wvoB6EJ9Nzi+g16IjBq0cZzMI4XK5XBroTD3yAeEK3i/hO/r0/H3kbVIYZQrxVj6JzH87sxdgrsB8mO6HXW839/bmORqezIzlrf8BMqgxaQ==)

**Comment by KaelWD** [comment]
Vue components use `model-value` / `@update:model-value`
