### ISSUE TITLE
[0.15.3] Reassignment carousel items causes errors 

### ISSUE THREAD

**Issue by Claus1** [vuetifyjs/vuetify#1678]
Codepen: https://codepen.io/Claus1/pen/QqLdbZ
My component has in data section:

`photos: []`
In template (pug) :

```
...
v-carousel
    v-carousel-item(v-for='(item,i) in photos',:key='i',
      :src='item')
```
When assign to photos new array (for example ['images/1.jpg','images/2.jpg'] ) I got 
`[Vue warn]: Error in callback for watcher "inputValue": "TypeError: _this.items[_this.inputValue] is undefined" found in ---> <VCarousel>` 

The second error is delay equals to 'interval' prop when component does not  update state after changing.
So the first error comes after    'interval' .

p.s. The first error in next() component method where this.items is empty although new 'photos' was already assigned. Invalid inputValue in next() is set to NaN.

**Comment by jacekkarczmarczyk** [comment]
@Claus1 please use the bug report template and add the codepen link for reproduction in both your issues, otherwise they will be closed, thank you!

**Comment by Claus1** [comment]
Sorry :) https://codepen.io/Claus1/pen/QqLdbZ but the second issue specific to image path format( fff/{number}.jpg). Can not reproduce on codepen yet.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Claus1** [comment]
Can I reopen if it closed by the owner???

**Comment by johnleider** [comment]
I should probably change the language, create a new issue.
