### ISSUE TITLE
[Bug Report][3.1.6] v-navigation-drawer rail with text avatar item rendering incorrectly

### ISSUE THREAD

**Issue by erikwrede** [vuetifyjs/vuetify#16799]
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a rail v-navigation-drawer. Add a text avatar in the prepend slot (`prepend-avatar` doesn't work in this case, as we don't want to add an image, but text - something that flawlessly worked in vuetify 2)

### Expected Behavior
The avatar should be rendered correctly like in vuetify 2
<img width="97" alt="image" src="https://user-images.githubusercontent.com/9725143/221823571-9beefbeb-48f9-4e45-a231-07d76f540740.png">

### Actual Behavior
The avatar positioning and sizing is off, the avatar should be a rounded square of the correct size. The issue also persists when removing the `rounded` prop.
<img width="67" alt="image" src="https://user-images.githubusercontent.com/9725143/221823637-61cd62c5-9dcc-4c69-853f-ce0c4a4a8be3.png">

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU8lu2zAQ/RWWPbgFLLFFih4Mx0gPBXpprzlEObDi2GbDDSSlxDD87x1SsrU4LRCdNPNm3puND0f6zbmybYCu6DqCdopH2FSGkHVbcOfybzYMb+WOR2lNITx/Bt8h6cO4wYAXx40oMGxv23GU51INlgOvuQETO1evk5WUDJGgHBFggoyH24rWVjtex4pe4i6RhcSyh/yMnBsh750HB0ZM4K63lkfuibeNESBIbZX1KPTb22czkekzAna1+X6/ZvlnRsfOfNMy2GSgr9VdRBkVbH4eyC+uIfHMoVG/Y3SYV+89LwrNq00NS9RcDsWjHeElFlsJShAErQCFM9BhV1HCRoyXtNxpvopJc2iG2ksXSYDYJFhqZ30kR+JhS05k660mCzyzRQqurcENowy5TfiHxQ9QypJ765V4t/iYyDs6JKJL2nFhEa78E6zBSz2mWqoeCBVdkexJPtRIdkX3MbqwYqwx7mlX4gGxO8SYb0yUGgph9d1NeVN+Krhye15+YQKnOIZLCLpI9xDAo3BFlyONKLeHf+n0MNJ/Lr92tL0rUV5RMeTHh1J4vFPw+GL+V/4s9rUWZiFXbSTpU2VOOFklzVOYDbUOeaAP5wrf1J+WpswEKfsxiZyWdFIjquY8+vgXs+JsEw==)

**Comment by Ax3l3rator** [comment]
Hey, have u found any probable fixes for issue?
