### ISSUE TITLE
[Bug Report][3.1.5] Range Slider in Vuetify 3 doesn't update via TextField value

### ISSUE THREAD

**Issue by may-96** [vuetifyjs/vuetify#16793]
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Type the number in the text field, and the slider won't change. 
You can change the value of the text field by sliding the slider, but not the other way around.

### Expected Behavior
Typing the number in the text field should update the position of the slider.

### Actual Behavior
Typing the number in the text field only changes the data value. It doesn't update the position of the slider.

### Reproduction Link
[https://codepen.io/may96/pen/jOvVoKv](https://codepen.io/may96/pen/jOvVoKv)

**Comment by nekosaur** [comment]
Use `@update:modelValue` https://codepen.io/nekosaur/pen/yLxXvaV
