### ISSUE TITLE
[Feature Request?] Responsive Data Tables

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1679]
It doesn't appear that the DataTables component supports collapsing table rows/columns to cards when viewed on smaller screens.

In Vuetify, is there currently a way to do something similar to the first example here?:
(Make sure "Mobile cards" is on in the first example, and collapse the width of your browser)
https://buefy.github.io/#/documentation/table

**Comment by KaelWD** [comment]
This should be possible with #2297

**Comment by tanyewei** [comment]
+1

**Comment by pSchaub** [comment]
@KaelWD #2297 is merged, does this mean it's possible now?
Will there be an example in the documentation about it?

**Comment by KaelWD** [comment]
Yes, it's in 1.0.0-alpha.1

It hasn't been documented yet, see vuetifyjs/vuetifyjs.com#19

**Comment by Taramouse** [comment]
I really need this feature, thanks for including.

**Comment by rodrigo-rafael** [comment]
Hello everybody!

I don't know if a miss something but neither data iterator nor data table does the same as [https://buefy.github.io/#/documentation/table](https://buefy.github.io/#/documentation/table) mobile cards do.

It is possible to make vuetify data table responsive as mobile--cards in buefy?

Thanks!

**Comment by redijedi** [comment]
This would be a tremendous improvement to the datatable. Anyone know if there is any movement on this?

**Comment by nekosaur** [comment]
There is already a solution to this problem using v-data-iterator. In coming data-table refactor, mobile view will be included by default. 

If you need help please visit our [chat](https://chat.vuetifyjs.com)
