### ISSUE TITLE
[Documentation] Broken Link in Vuetify 3 Documentation for Floating Action Buttons

### ISSUE THREAD

**Issue by SabeurMohamedAmin** [vuetifyjs/vuetify#16807]
### Environment

**Browsers:** Chrome 110.0.0.0, Other
**OS:** Windows 10

### Steps to reproduce
Hello Vuetify Team, While browsing the Vuetify 3 documentation, i found a broken link in Floating Action Buttons component page it shows 404 error page.

Vuetify 3 documentation page for the Floating Action Buttons component: 
https://vuetifyjs.com/en/components/floating-action-buttons/

Thank you.

### Expected Behavior
??

### Actual Behavior
??

### Reproduction Link
[https://vuetifyjs.com/en/components/floating-action-buttons/](https://vuetifyjs.com/en/components/floating-action-buttons/)

**Comment by MajesticPotatoe** [comment]
The page does not exist because the component is not available in v3 yet.
