### ISSUE TITLE
[Bug Report][3.1.7] VMenu open on blur doesn't work when the activator input is clicked near the "clearable icon" side

### ISSUE THREAD

**Issue by fahmifitu** [vuetifyjs/vuetify#16812]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click input from the far right side where the clearable button is positioned
2. The input is blurred normally but the menu doesn't open!

### Expected Behavior
Input should blur and menu should activate

### Actual Behavior
The menu doesn't activate

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1v1DAQ/SuDOSxImxhUJKTVFhWJA3cOHOoenGS2NfWXbCcFrfLfGTubbnZbqKpcMu+N38x79vWeffW+HnpkG7ZNaLyWCb8IC7AdKul9+S2FkcoeqlK3ziaCMCxBg7YH59FWzlaN7o8k0bM8vJVtUoNMLlwKtgcfnI8wCkbNIs0fqSX8naqdQt2Blg1q6v6RZEjwjVQEg1ajDLLRCEPVKNsRX7SI4q/Vot1dV2ATb1/WfjTFT0I7piNDt0DKChkreyyITHEO31FrBw8u6G7Jbfnzp2b8GD0BOftH16Xj7IZK03yLuZju98QClbENyieImPpMK+MdxbSHgDsYYRecgRU9mFVuphExASUGl5l/t5qM/MxG8M3qfVaf9EiJrdkkRlv4+ld0lh7dPi8jDgSlu4GCZIyG5Fqwu5R83HDeW39/W7fO8CvieOhtUgarzpmri/qi/lBJ7e9k/Yl3KqYlXWM0VRPcQ8RAgwVbL2YktfvzrzkHmuQ/1p8n2QOUJZ9IcdIfMFQBbYcBw3/XP+t9zsJZyxMbefQo7EjJamXv41mobSyBXs8bvsqfUbYuAvn0TR4yrtnJjjS1nGM3fwGG4WW+)

### Other comments
This is probably related to how fields work in vuetify. it reproduces on all variants
![Screenshot 2023-03-02 at 1 08 35 PM](https://user-images.githubusercontent.com/24812043/222412214-c3ecbcbc-e5c2-4faa-a0aa-d13284552c4c.png)

**Comment by KaelWD** [comment]
open-on-blur doesn't exist

**Comment by fahmifitu** [comment]
oops my bad, feel free to update title or close

**Comment by johnleider** [comment]
The actionable issue here is the click deadzone for appended fields.
