### ISSUE TITLE
[Feature Request] v-otp, v-calendar, v-date-picker not available in vuetify 3

### ISSUE THREAD

**Issue by SainathReddyKotla** [vuetifyjs/vuetify#16817]
### Problem to solve
it solve otp verfication onfinish
calender to pick date and time for time slots

### Proposed solution
pls update this in vuetify 3 also

**Comment by websitevirtuoso** [comment]
It will be available later. please close issue and read roadmap

**Comment by SainathReddyKotla** [comment]
Thank you for your response
 Will close the issue

**Comment by SainathReddyKotla** [comment]
thankyou

**Comment by websitevirtuoso** [comment]
Everything in milestones
https://github.com/vuetifyjs/vuetify/milestones
there all tickets. all component will be created as in vuetify 2
