### ISSUE TITLE
[Bug Report][3.1.7] v-menu with 'activator' property does not always show the menu

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#16813]
### Environment
**Vuetify Version:** 3.1.7
**Last working version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
The following code creates a table of 10 x 10 buttons.  When a button is clicked a menu will popup at that button location (by using the activator property)
```
<div>
  <v-container>
     <v-row v-for="x in 10" :key="`row_${x}`">
       <v-col v-for="y in 10" :key="`col_${y}`">
          <v-btn @click="showTheMenu(`btn-${x}_${y}`)" :id="`btn-${x}_${y}`"/>
       </v-col>
     </row>
  </v-container>
  <v-menu v-model="menu" :activator="activator">
    <v-list>
      <v-list-item>Some Menu Choice</v-list-item>
    </v-list>
  </v-menu>
</div>

const menu: Ref<boolean> = ref(false);
const activator: Ref<string> = ref('');

function showTheMenu(btnId: string) {
    activator.value = `#${btnId}`;
    menu.value = true;
}
```
The issue is that the menu will not always show up when a button that has previously been clicked has been clicked on again.  For example:

 - click button at row 1 column 1 (menu shows up as expected)
 - click button at row 7 column 4 (menu shows up as expected)
 - re-click button at row 1 column 1 (menu briefly flashes with no menu choices in it then goes away). 

or
 - click button at row 1 column 1 (menu shows up as expected)
 - click somewhere else on the screen (the menu disappears as expected)
 - re-click button at row 1 column 1 (menu briefly flashes with no menu choices in it then goes away).  

### Expected Behavior
The menu always shows up when the button is clicked

### Actual Behavior
The menu seems to auto-close within ms of a button being re-clicked.  If I remove the 'activator' property from the v-menu it works as expected (although the menu is in the wrong place on the screen)

### Reproduction Link
[https://github.com/v](https://github.com/v)

**Comment by KaelWD** [comment]
Because you're telling it to open (`menu.value = true`) but it also closes itself on activator click (`isActive.value = !isActive.value`). Only set `menu.value = true` if the activator has changed.
