### ISSUE TITLE
http://eslint.org/docs/rules/no-undef  'axios' is not defined ?

### ISSUE THREAD

**Issue by vipin733** [vuetifyjs/vuetify#1681]
Hey I'm using electron templates, but when i try to use axios its giving error, http://eslint.org/docs/rules/no-undef  'axios' is not defined, here is my main.js  https://codepen.io/vipin733/pen/mBbMvN and ny package,json https://codepen.io/vipin733/pen/xXKXGQ

thank you

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by vipin733** [comment]
first I asked this question on [discordapp](https://discordapp.com/invite/s93b7Fv) But I could not get any solution thats why I'm asking here

**Comment by johnleider** [comment]
I understand. Unfortunately you'll have to be more patient. Ty

**Comment by ngrcode** [comment]
I have this problem please help me

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
