### ISSUE TITLE
[Feature Request] :loading property for v-data-table

### ISSUE THREAD

**Issue by reneroth** [vuetifyjs/vuetify#16811]
### Problem to solve
The `loading` property is available on the `v-data-table-server`, and disables the table along with showing an indeterminate loading animation. This might also be handy for the `v-data-table`, since there might be situations where we don't need serverside pagination, but still have a loading event on the table. Examples for those might be cases where we load all data at once from the server, but have a button to fetch new data.

### Proposed solution
Make the `loading` and `loading-text` properties and styling available to the default `v-data-table`.

**Comment by fahmifitu** [comment]
This is a bug becuase loading prop exists on the vDataTable api https://vuetifyjs.com/en/api/v-data-table/

**Comment by reneroth** [comment]
> This is a bug becuase loading prop exists on the vDataTable api https://vuetifyjs.com/en/api/v-data-table/

I can see a `loading` slot being documented, but not a `loading` prop. The `VDataTable.tsx` does not have any slot or prop named `loading` though, so the documentation is wrong, I'd assume.

**Comment by websitevirtuoso** [comment]
create PR and fix it please

**Comment by reneroth** [comment]
> create PR and fix it please

ok since you said "please" #16829

**Comment by webdevnerdstuff** [comment]
Is it also possible to add in the `loadingText` prop along with this update? That prop is also missing, and works in tandem with the `loading` prop.

**Comment by DenielPereira** [comment]
Any update on this issue? I'm currently experiencing the same problem.

**Comment by websitevirtuoso** [comment]
Why do you need loading prop? does it make sense. If you need loading then use v-data-table-server component

**Comment by reneroth** [comment]
> Why do you need loading prop? does it make sense. If you need loading then use v-data-table-server component

Aren't you the dude above that asked me to create a PR and then deleted his comment? I've outlined my reasons in the initial post, and others have expressed interest in this feature as well. It's already implemented and reviewed, just waiting for the merge.

**Comment by webdevnerdstuff** [comment]
@websitevirtuoso this is Github and a feature request, not people asking for help or ill informed advice. I would suggest you go the Vuetify (Discord)[https://discord.com/invite/s93b7Fv] channel if you want to share your advice, or opinions.

**Comment by hesstab** [comment]
Any progress on` loading-text` prop?
