### ISSUE TITLE
[Bug Report][3.1.5] VProgressCircular - Jittery when indeterminate

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#16821]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
In the provided reproduction it seems ok but in my app and even on the vuetify [docs](https://vuetifyjs.com/en/components/progress-circular/#indeterminate) you can see a not so subtle jitter effect when using indeterminate

### Expected Behavior
should be smooth

### Actual Behavior
its not

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUU1PAjEQ/Su1FzRhdzUYY8hC8OY/8EA5lN0ClX5lpotRsv/d6bIYBGLirW/ezHtvpvM9fwkh3zWKj3kZlQ1GRjUVjrFyl8kQumcHrNSuRx0O4NegELNKQ9UYCUy7WkUFVjvSYJWRiBPBrcyeBWeovxSh0RO9K288EAigrYRPwadlcUXw6E3cj3kCh1hlcRKXIFagQ2SoYpNobYOHyPYM1Iq1bAXesgHtOUjNlXcYmcU1myT+dvCqjPHszYOpbwZ3SfwgR0J8yA9aFCLk7+gdnWqfsoieQMHHrKukGnkkLPgmxoDjomhc2K7zyttiRlwBjYvaqqz2djbKR/l9Jk3YyPyxqDXGUzpXaLMl+A9UQMaCD088ol7R4a779DTJPxxl+1Jm5BKT7oVeQSY7BRko+kVQ8OcOZ73X9jhrudglWbfCtXReo90Wzy5bYXfV+THh/5fsFNL4Irm0Q/4rJNl2g3zxDZOhAzU=)

### Other comments
Not sure why it seems ok in vuetify playground but nowhere else

**Comment by ae-meddeb** [comment]
I have the same effect too !!

**Comment by KaelWD** [comment]
I don't, it's fine in both.

**Comment by MetRonnie** [comment]
I have noticed this too on Chromium. It seems to be wobbling/vibrating! It was not the case with Vuetify v2. Also on Firefox v3 does not wobble

**Comment by joel-wenzel** [comment]
@KaelWD v2 was fine. I dont see any issues on personal computer (both using chrome). Ill spend a little more time to see if I can find a reliable way to reproduce

**Comment by MetRonnie** [comment]
This is on Edge 110.0.1587.57
![v-progress-circular](https://user-images.githubusercontent.com/61982285/222739171-71000ec8-1cb9-407d-9fb3-3f8a57157d38.gif)

**Comment by joel-wenzel** [comment]
I am seeing the same as @MetRonnie 
I think it is a combination of `hardware acceleration` being enabled and the gpu of the machine. Though if i copy the vuetify 2 svg html and replace the v3 svg with it it does lose the jitter.

**Comment by MetRonnie** [comment]
I had a quick play around with this and the problem seems to be something to do with nesting the "grow-shrink" (`progress-circular-dash`) animation on the `<circle>` inside the "spin" (`progress-circular-rotate`) animation on the `<svg>`.

Possible solution: combine the animations on the `<circle>`:
```diff
 .v-progress-circular--indeterminate > svg {
-  animation: progress-circular-rotate 1.4s linear infinite; 
-  transform: rotate(calc(-90deg));
 }

 .v-progress-circular--indeterminate .v-progress-circular__overlay {
-  animation: progress-circular-dash 1.4s ease-in-out infinite;
+  animation: progress-circular-dash 1.4s ease-in-out infinite, progress-circular-rotate 1.4s linear infinite;
+  transform-origin: center center;
+  transform: rotate(calc(-90deg));
}
```

**Comment by xiwh** [comment]
https://user-images.githubusercontent.com/8778489/224961122-e2aa98eb-a382-489f-9b64-8f00acaca40e.mp4

The same problem with win10 chrome 111.0.5563.65
