### ISSUE TITLE
[Bug Report][3.1.7] List-Group missing hover background when opened

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#16830]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When you hover over the closed item-group a background is used (as expected). Once you open the group and hover over the parent again, there's no background-color.

### Expected Behavior
Opened group-parents should also indicate the interactivity by the background-color.

### Actual Behavior
hover background color missing.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE2P2jAQ/SuWL9mVcEJFpUqUXe3eeump6olw8DoGXPwl28l2hfjvHTvJbkiAquUSPDNv5r03cdZH/Gxt3tQcL/EqcGUlDfyx1AitGsKoq+JfhJik3j+UWP0mtA6mxG34VVRhD+HFfN6GEjJhpfABNUSZisulsVzzCgrjnxJ3Ve91RMBkZB2HbEUEMzqOqgTZG8VLjIIIkkPoWzo+rooBDHqNu+2cqS1qqKwj6Kfnzg9mQl2vE/h5acKSsiAaGoyD8iPwMNaj0xnknOowjqDJi9BRXAL21vS/C6ooY6bWgTDhmARB54BebMd7mJwofydXDFY3CF805LlSYriE/7bklil/s+VDZ0fnPH1V6VWttze0TULu1mnoDMVlbOBxj4RGNBKYEFwe+BtAxCTe807PSXa07viY1PSLuNDhxoaHu/y4QJfCfbC9xnCI9xgOI+dWnjlhA/I8tNAyCGWNC+iIHN+iE9o6o1AGH4fsKwACaIE7Ha8weogVd+ssvaTZ5h7yAG8LWj+hZN3SWWffqaY7rrgO2QxlwyugahmElZyYOkihebaZ9aAfPAShd76HMLMbVW3iVBDY6gAFeIZbBURRm//yRsNX7RiLYBMpAWteohSJMVAWzyXeh2D9sihqbQ+7nBlVPEGucEBRKE4qo54W+SKfEyrtnuafiwrsHaZz7hV5ceYV/IDBJe5kpBlBbN+uzenS0P5T/qVt24Viy0mrAvo33BEH7xh33N2kP6q9JGFUMpERR59KfQJnwfiDH5nKfDK0W/Q/6oO3JE8N0i7jkNMMn3GEqQmHN38ASzERGg==)

**Comment by johnleider** [comment]
This has always been the case dating back to v15.
