### ISSUE TITLE
v-text-field deletes entry when type="number" & step="0.01"

### ISSUE THREAD

**Issue by eelcowen** [vuetifyjs/vuetify#1683]
### Steps to reproduce
Add a v-text-field with type="number" & step="0.01"
Try to type 1.1

### Versions
Mac OSX, Chrome 60

### What is expected ?
Being able to add a decimal number in a v-text-field when `type="number"` & `step="0.01"` is set.

### What is actually happening ?
The value get removed

### Reproduction Link
https://codepen.io/anon/pen/MEgEPP

**Comment by johnleider** [comment]
This is my fault, accidentally left something in from testing.
