### ISSUE TITLE
[Bug Report][3.1.7] VAppBar hide-on-scroll prop missing

### ISSUE THREAD

**Issue by mftruso** [vuetifyjs/vuetify#16832]
### Environment
**Vuetify Version:** 3.1.7
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
`hide-on-scroll` seems to be a missing prop, but is still documented on the [component page](https://vuetifyjs.com/en/components/app-bars/#hiding-on-scroll) and in [examples in the repo](https://github.com/vuetifyjs/vuetify/blob/dev/packages/docs/src/examples/v-app-bar/prop-hide.vue)

### Expected Behavior
`hide-on-scroll` works like vuetify 2

### Actual Behavior
app bar stays visible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVM1u2zAMfhVNO2QDIjtdiw3I0qC77QEG7FD3oNiMo0WWNIlOGwR591L+SZy0DVCgF0P8SH78KFK+3/FfziWbGviUzxAqpyXCPDOMzTZCOtccG6OSynRWY+fSFyzXMoTbjNsN+KW2j2KligJMxo95RCIW0veZchGsrhF6O7faemJAkFpoVa4QjLjOeO8vpF/3ZyIHYY0Iubda96jztlIGDPZA6xYofQlI1J9bQJlSIOQro/7XEMRNX2PYVCdWGLkRKrdmPktfATMzSEFrdfSiQg3zP/Ebk07hk4zgZA6+oe6OJ+4FGtaVabEGbZCqUDSH0qjlNmafREWAUt/FtQLp8UOYCotB0BKgyqW+wNhb3Z0e1ySsAA4TVAWN7fLUaHPOd28rZI32GFDJJ+owrhRFfZ9MXhs4qURabPAs4FYDBbYZU3Y1mUzc009a5aj3EDfooZHcvpUYQe9h4Dw8l65bOs/SwQMjkxpUDlkArKNbVc56ZDvmYcn2bElrzUb0MkcxmOoHZFUo2W30fxn9Bq0t+2u9Lj6Nvkbylo6I+Ji3XCTCJf+CNfS4d1FL1jlCxqesQSJGNaJNrSO6ME3T2rh1meS2Su/Il/raoKqAZlzdXSffkpsfaaECDvEEQiUW3j4G8FQx4+MBOdK6vlWgcxPvVdLRdlCkfEGVEj+NW3gwBXjwF3WfxZ5oP/O90B9r7jOzp7ukFVyHs2vMQ3OF9720dzVGf6ukIYjZD7HIfsxbcVSuSeAPz3gvzF4=)

### Other comments
The reproduction code is taken from example code in the repo

**Comment by scscgit** [comment]
It seems this will be implemented in https://github.com/vuetifyjs/vuetify/pull/16267 but it takes too long :(

**Comment by andrewspy** [comment]
It's now implemented in the latest 3.2.1 with props `scroll-behavior="hide elevate"`

**Comment by mftruso** [comment]
Confirmed this is fixed by https://github.com/vuetifyjs/vuetify/pull/16267. 

Documentation is still missing on the App Bars component page: https://vuetifyjs.com/en/components/app-bars/#hiding-on-scroll
