### ISSUE TITLE
Reassignment carousel items causes errors.

### ISSUE THREAD

**Issue by Claus1** [vuetifyjs/vuetify#1684]
### Steps to reproduce
Codepen: https://codepen.io/Claus1/pen/QqLdbZ
Press button 'Change Pics'

### Versions
vue 2.4.2
vuetify 0.15.3
Firefox 55.0.3
win 7

### What is expected ?
It has to show pics from data.new_pics after pressing the button 'Change Pics'.
The button handler assigns carousel items to data.new_pics array.

 
### What is actually happening ?

In codepen:
Nothing works without warnings - 80% probability
Nothing works and delay and `[Vue warn]: Error in callback for watcher "inputValue": "TypeError: _this.items[_this.inputValue] is undefined" found in ---> <VCarousel>`  - 20% probability

In my program:
Nothing works and delay and `[Vue warn]: Error in callback for watcher "inputValue": "TypeError: _this.items[_this.inputValue] is undefined" found in ---> <VCarousel>` 

### Reproduction Link
https://codepen.io/Claus1/pen/QqLdbZ

### Additional details
The error in next() component method where this.items is empty although new 'photos' was already assigned. Invalid inputValue in next() is set to NaN.   

The second error is delay equals to 'interval' prop when component does not  update state after changing. So the first error comes after    'interval' .

**Comment by johnleider** [comment]
I've made a small tweak that should allow you to handle this functionality. Essentially, when the carousel boots, it determines what its children are, and by that, determines which child to tell _hey! you're active_. When you dynamically change the items, there is nothing that (as far as I'm aware) that will allow you watch the changing of children from within a vnode.

To combat this, you have a few options, however, both essentially require you to reboot the carousel.

1. Apply a **v-if** conditional on the carousel and switch it on and off (make sure to use $nextTick) when you adjust your items. https://codepen.io/johnjleider/pen/eGYybW
2. Assign and reset a model on the ```v-carousel``` component. https://codepen.io/johnjleider/pen/RLwxEv

The former you can do now, the latter will go out with next release.

**Comment by Claus1** [comment]
The second trick does not work in my Firefox. Same as before. The first one is ok. Thanks a lot!

**Comment by johnleider** [comment]
I stated the second one will not work until I release the next patch.
