### ISSUE TITLE
[Bug Report][3.1.6] The window item component animation is abnormal

### ISSUE THREAD

**Issue by liub1934** [vuetifyjs/vuetify#16842]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The transition="fade-transition" property is set on the window item. When I click the next page button, the animation is OK. When I click the previous page, the animation is the default animation.

### Expected Behavior
Animation normal

### Actual Behavior
Animation exception

### Reproduction Link
[https://codepen.io/liub1934/pen/gOdRJyb](https://codepen.io/liub1934/pen/gOdRJyb)

**Comment by KaelWD** [comment]
You also have to set reverse-transition

**Comment by liub1934** [comment]
> You also have to set reverse-transition

Thanks It works
