### ISSUE TITLE
[Bug Report][3.1.7] body elements does not have any bg color that make odd color to body and v-app background color

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16853]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Download the package
- Run yarn and yarn dev

### Expected Behavior
The body element has the same background color as the theme.

### Actual Behavior
The body does not have any background color it adopts the browser's background color.

### Reproduction Link
[https://github.com/alokVishu/vuetify-body-bg-color-issue](https://github.com/alokVishu/vuetify-body-bg-color-issue)

### Other comments
Please Refer screenshot

https://user-images.githubusercontent.com/80033712/223338970-7c7d7578-0b3e-48c6-b268-ad9ec4b4051f.mov

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/discussions/16381#discussioncomment-5216013

**Comment by alokVishu** [comment]
Hello @KaelWD,

We don't want to change the theme color. I just need the same background color for the body elements. 

Please refer to the screenshot: 
![image](https://user-images.githubusercontent.com/80033712/223342349-83bda6e8-054e-4591-ba50-ceb7d90ce942.png)

Awaiting your reply 😊.

**Comment by KaelWD** [comment]
Won't be adding global styles to theme, you should be able to set `:root { background-color: var(--v-theme-background) }` though.
