### ISSUE TITLE
[Bug Report][3.1.7] v-select options becomes transparent when attach prop is used

### ISSUE THREAD

**Issue by Chris-McQuiggan** [vuetifyjs/vuetify#16855]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add the menu prop "attach";
    a. to a select, autocomplete or combobox.
    b. set the default v-menu attach prop to true.
2. Open the selection menu
3. OBSERVE the list is transparent

### Expected Behavior
The menu to not be transparent and can be clicked

### Actual Behavior
The menu is transparent and can't be clicked

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1v2zAM/SuaLt6A2F6zAQOCdOhuu++wQ5SDIjONVusDEp1uCPzfR/kjcOy2QOGDRT7qvUeKuwv/4X1xboBv+BbB+FoifBeWse05l953xy4wUtsh6mIlQyWswP571hWe7gVffwYj+Jin+rFguJEj/J2mOyBCDQqnSYG1PEBNhAN2pey/jQHb5D44H6nmIhGlOm0wNNAuSjW1lap2LEOIeJet+sM6HY7Opd9Bhoztb6+Wc5vJugwgXzaaUNbBr7Jsy5eHMM5GKtTOxsV4vFQQ2MLPAdODTL38AhnU6aaMJG/rribmaiMwPjmF1zdPQb8N23KyJRRGFbRHFgGbBGvjXUB2YQGOrGXH4AzLaL2yVKxIDpmJj+w+4R+zn1DXjv12oa4+ZJ8SeU9HRHzFey4y4Ys/0Vna0EvyIgYgCr5hXSblSCPFgp8QfdyUZWP902OhnCkfCCtDY1EbyCtnHr4U6+Lrt7LSEaf5AqLJD8E9RwikKPhqQo76+O81gQEm3rtioB1SOW1HTLwLvpJEzhDyALaCAOFN87PamwZm2KKJpNkK29JAa22f4myWKnZz3I3W3t9dx5Cu75NKu+K9O9LrbvD9f2dNiDA=)

### Other comments

Reproduction link for 1b.
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU01v2zAM/SuaLu6A2F6zAQOCdOhuu+y0oTtEOSg2E3u1PiDRaYcg/32UZAdO0hYoDCQiH/X4KJKrA9/3gO32X/HX8wVvlTUO2YFVDiTCQ8LYkW2dUSwbYjOhhYbnGFoZ7ZENALs7v3hzEJqxGray79AvWDQZe/gJuo+WwPBJRFk1C4auh+Q7zkJk+sUGFFD0yPM72VnX7hrMYtDxo9B8xr9bW5ASqmOJoGxHQr4FhuU+l9bGYzSUbPVgRbuSrh61CHxqa2zuBJ9/AiX46Kf4MWC4kSM8T90R8NBBhVOnwE5uoCPCATtRpm/RklZP8IplCB5vs1k6zMNha0z420iXsfX51fIyd9Aj6flfzh5QFuFXWZbly5WNBcsKW2r3Vc1WVuDYlZ4NhleeavkF0lXNWRilPI87ibjMNgJjH8k8NTIYqcXLctJ6Mn3lWovMA/YBPg24g+10rONIp1lWfkdzTPhN9gO6zrA/xnX1h4xmbFkmOiKicUtcJMLS8hhNYxfnWwyAF/w08SKsWbAFbxCtX5Rlr+3jrqiMKu8JK12vsVWQ10bdfy7mxZevZd16nPoL8CrfOPPkwVFGweN6DORh3V5LMMDEe1sMtIMrp+nwgfeKr6Qke3C5A12DA/em+IvYswIusKsi4qLTCtODdq1+9BdvWfn4jqtR2vuriwzh+jpkOc54Ukf54g2+/g/zv7/i)

**Comment by Chris-McQuiggan** [comment]
Seems to be related to this which was resolved in vuetify 2 https://github.com/vuetifyjs/vuetify/issues/11153

**Comment by Chris-McQuiggan** [comment]
Reproduction link for 1b.
https://play.vuetifyjs.com/#eNqVU01v2zAM/SuaLu6A2F6zAQOCdOhuu+y0oTtEOSg2E3u1PiDRaYcg/32UZAdO0hYoDCQiH/X4KJKrA9/3gO32X/HX8wVvlTUO2YFVDiTCQ8LYkW2dUSwbYjOhhYbnGFoZ7ZENALs7v3hzEJqxGray79AvWDQZe/gJuo+WwPBJRFk1C4auh+Q7zkJk+sUGFFD0yPM72VnX7hrMYtDxo9B8xr9bW5ASqmOJoGxHQr4FhuU+l9bGYzSUbPVgRbuSrh61CHxqa2zuBJ9/AiX46Kf4MWC4kSM8T90R8NBBhVOnwE5uoCPCATtRpm/RklZP8IplCB5vs1k6zMNha0z420iXsfX51fIyd9Aj6flfzh5QFuFXWZbly5WNBcsKW2r3Vc1WVuDYlZ4NhleeavkF0lXNWRilPI87ibjMNgJjH8k8NTIYqcXLctJ6Mn3lWovMA/YBPg24g+10rONIp1lWfkdzTPhN9gO6zrA/xnX1h4xmbFkmOiKicUtcJMLS8hhNYxfnWwyAF/w08SKsWbAFbxCtX5Rlr+3jrqiMKu8JK12vsVWQ10bdfy7mxZevZd16nPoL8CrfOPPkwVFGweN6DORh3V5LMMDEe1sMtIMrp+nwgfeKr6Qke3C5A12DA/em+IvYswIusKsi4qLTCtODdq1+9BdvWfn4jqtR2vuriwzh+jpkOc54Ukf54g2+/g/zv7/i

**Comment by KaelWD** [comment]
That was different, caused by VNavigationDrawer overriding VList background color. In your case the list does have a background color, it's just behind the textarea. 
Why do you think you need to use attach here?

**Comment by Chris-McQuiggan** [comment]
> That was different, caused by VNavigationDrawer overriding VList background color. In your case the list does have a background color, it's just behind the textarea. Why do you think you need to use attach here?

This was found when setting the default props on v-menu as we need every menu to be accessible with the keyboard and reader. So it's not actually needed on the select

**Comment by Chris-McQuiggan** [comment]
> > > we need every menu to be accessible with the keyboard and reader.
> > 
> > 
> > They should already be by default.
> 
> Not for what we are using it for but we aren't really using it conventionally. We are putting a mini form inside it. The docs then suggested adding the attach property which fixed it.

For now i'm going to alias v-menu it so that the defaults don't change in other components

**Comment by Chris-McQuiggan** [comment]
I've just found the other reason I needed attach on the v-select. I need to be able to know when one of the options has focus and as there is no @update:focused on the select I need to use @focusin which relies on the options to be a child

**Comment by KaelWD** [comment]
`:menuProps="{ contentProps: { onFocusin }}"` might work

**Comment by Chris-McQuiggan** [comment]
For completeness. I couldn't get `:menuProps="{ contentProps: { onFocusin }}"` to work but ended up using `[update:menu](https://next.vuetifyjs.com/en/api/v-select/#events-update:menu)` to see if the field was in use although I couldn't then see which options were focused.

**Comment by AlfreMK** [comment]
A workaround to consider is to add something like `style="z-index: 3000; position: relative"` in the v-select component (the position relative is necessary to override the position: static that is there by default).

Example:
```.vue
<v-select
  label="select"
  :menu-props="{attach:true}"
  :items="[ 'test1', 'test2', 'foo', 'bar' ]"
  style="z-index: 3000; position: relative"
/>
```

Although you will still see it a little transparent

**Comment by AlexTM84** [comment]
I solved the issue with this snippet, even though there would be a global solution to this issue:

<v-select
                    ...
                    class="my-select"
                    :menu-props="{ attach: '.my-select' }"
/>

I've added a specific class (or maybe an ID to the element) and then used that class (or ID) as a selector for the attach property.
