### ISSUE TITLE
[Bug Report][3.1.8] VDataTable: index not working in slot item.*

### ISSUE THREAD

**Issue by swiergot** [vuetifyjs/vuetify#16865]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Linux

### Steps to reproduce
See the reproduction link.

### Expected Behavior
The index property returns the index of an item in the list, starting with zero. It worked like that in Vuetify 2 and it should work also in Vuetify 3 if I get the docs right.

### Actual Behavior
The index property is undefined.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUttu2zAM/RVOL96A2EK3ARuMZOi+o86DYjObGlsSJNlNYfjfS8pOm6QXoC82r+eQR7wbxV/niqFHUYp1xM61KuKfygCsh1w5l8zkdEqbxUt+o6LKo9q1COV/VA36sKnEYlUCSk1wHEp/CtStCuxji4OK2pr8phLPiIR5oochD62NCaDQzZF6RtCmwSNMFx0A4ynxZbOBnqy9NtjANJ3Byou1PuSiz0xGxptcHP8U1VqeK3VSk4LPcrIzC33RTm6ovXYRAsae07pz1kcYweMeJth720FGL5dxcW1NiLCoDxuu+XpHiThC1LHFErIkVLaCAz6y1xwzmFY8wVkJDfBSwU4q2X57oUiveSIYJ06t5TwpzShWYh6T9nPFfbCG7mpkErqDlKBLKCFFOEbjs093E6MLpZS9cYd/RW07eUs56XsTdYd5Y7vbH8X34ucv2egQz+MFhi7fefsQ0BNjJdJOC3jU+8f3CJY04d4Uv2fYJZS3ahcY9xWeJJIBfe6RxPToPxz+qvZigavcqyWYky5rIkFbbQ7hSss6JB3phefRPr9dQuD2LbNMKzFPR3ypQ2yfALvhV30=)

**Comment by blalan05** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/cb29eb3992d72726e7f8e45a82a773f592ec8c4f
