### ISSUE TITLE
[Feature Request] VSelect, VAutocomplete - Add a persistent-options prop

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#16860]
### Problem to solve
One problem this would solve is when trying to style options via `inspect`. 

When the option list doesn't have the ability to be persistent, it winds up taking an extensive amount of time styling list options. When using a slot, you can style classes you add, but that doesn't account for generated styles by vuetify. So you wind up having to do a lot of trial and error. 

With the ability to keep the list open, it would take a fraction of the time to accomplish the goal. One could literally take hours trying to get something styled the way they want, when if the list was persistent would take only minutes.

Another scenario would be when you want to see the options, but have to click away from the screen for whatever reason. You would still be able to view the list without having to go back and forth to open it each time.

### Proposed solution
Add a `persistent-options` prop. Or some other solution like that would keep the options list open, until a user has physically clicked on an item.

**Comment by KaelWD** [comment]
![Screenshot_20230308_152824](https://user-images.githubusercontent.com/16421948/223619685-25dbebd1-a9f3-4357-97d4-9c2faa5f4f83.png)

There's also already `v-model:menu` https://github.com/vuetifyjs/vuetify/pull/16763/files#diff-557c6e7760fdad1c8b84e11a9936f8cda77de7fd4e83a80f0d1c4baa51ad577c

**Comment by webdevnerdstuff** [comment]
`Emulate a focused page` ... I'm today years old when I now just learned this. Thank you!

As for the `menu` prop in the documentation. Is it safe to assume it's very similar to v2 version? If so I can try to remember to put in a pull request to update the missing description.
