### ISSUE TITLE
[Documentation] Stopp rewriting internal links based in browser languages

### ISSUE THREAD

**Issue by rotsee** [vuetifyjs/vuetify#16869]
### Environment

**Browsers:** Chrome 111.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Set Japanese as a ”Preferred language” in your web browser
2. Go to https://dev.vuetifyjs.com/en/components/data-tables/basics/
3. Try following any link, e.g. to the API
You will now end up on a 404 page:  https://dev.vuetifyjs.com/ja/api/v-data-table/
It seems like all links are rewritten based on preferred language, even when no documentation exists. 

### Expected Behavior
The API link should take me to the API documentation: https://dev.vuetifyjs.com/en/api/v-data-table/

### Actual Behavior
User has to keep url hacking (changing e.g. `ja` to `en` in the browser's url bar for each new page) to be able to browse the documentation.

### Reproduction Link
[https://dev.vuetifyjs.com/en/components/data-tables/basics/](https://dev.vuetifyjs.com/en/components/data-tables/basics/)

### Other comments
I would argue that the expected behaviour is to _never_ rewrite links. If I actively selected English, I probably want to keep browsing the documentation in English (e.g. because it is more up to date, better writter, or whatever). I don't want to have to rewrite the url in the url bar every time I visit a new page. If I want to switch languages that's easy enough using the language widget on the top of the page.

**Comment by KaelWD** [comment]
Stop using outdated documentation, this was fixed in january. `dev.` is a staging site and is not regularly updated.
