### ISSUE TITLE
[Bug Report][3.1.7] [Checkbox] Style is broken when not wrapped in v-app

### ISSUE THREAD

**Issue by tokidoki11** [vuetifyjs/vuetify#16861]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create v-checkbox with color inside div element

### Expected Behavior
color and styles works as in documentation

### Actual Behavior
checkbox style is broken

### Reproduction Link
[https://codesandbox.io/s/objective-ishizaka-zll565?file=/src/App.vue](https://codesandbox.io/s/objective-ishizaka-zll565?file=/src/App.vue)

**Comment by tokidoki11** [comment]
Video Example
https://user-images.githubusercontent.com/7564844/223613834-32bd3fa1-02b2-4037-88e1-ffef480538ac.mov

**Comment by KaelWD** [comment]
Duplicate of #16751
