### ISSUE TITLE
[Bug Report][2.6.13] Vuetify 2 Site search seems to be down

### ISSUE THREAD

**Issue by add11e2** [vuetifyjs/vuetify#16862]
### Environment
**Vuetify Version:** 2.6.13
**Last working version:** 2.6.13
**Vue Version:** 2.7.11
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce

1.  Open v2 site and open any page for example https://v2.vuetifyjs.com/en/getting-started/installation/
2. Search for a component for example v-menu

### Expected Behavior
List of components matching the search query

### Actual Behavior
Blank search result along with bunch of errors in console as i type

### Reproduction Link
[https://codepen.io/ad121/pen/wvErxZJ](https://codepen.io/ad121/pen/wvErxZJ)

**Comment by MajesticPotatoe** [comment]
its main site as well. we are looking into it.

**Comment by MajesticPotatoe** [comment]
This is fixed. You may need to clear your cache.
