### ISSUE TITLE
[Bug Report][3.1.8] Error: No known conditions for "./settings" specifier in "vuetify" package

### ISSUE THREAD

**Issue by lecaillon** [vuetifyjs/vuetify#16866]
### Environment
**Vuetify Version:** 3.1.8
**Last working version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Windows 10

### Steps to reproduce
`npm create vuetify`
`npm install -D sass`
In the file `vite.config.ts` add `styles: { configFile: 'src/settings.scss' }`
Add the file `src/settings.scss` with this content for example:

    @use  'vuetify/settings'  with (
    $field-font-size: 13px,
    $label-font-size: 13px,
    );

Run `vite build`
Error: No known conditions for "./settings" specifier in "vuetify" package

### Expected Behavior
The build should works like in Vuetify 3.1.7

### Actual Behavior
The build fails

### Reproduction Link
Cannot find a way to reproduce the issue using one of the online editors

**Comment by rwadud** [comment]
I am experiencing this as well.

**Comment by lnxd** [comment]
So are we (@jbaquino3)

**Comment by KaelWD** [comment]
Are you using vite 4.1? Try 4.2-beta or 4.0

**Comment by lecaillon** [comment]
"typescript": "~4.9.5",
"vite": "^4.1.4",
"vite-plugin-vuetify": "^1.0.2",

**Comment by fahmifitu** [comment]
+1

**Comment by KaelWD** [comment]
> Try 4.2-beta or 4.0

**Comment by fahmifitu** [comment]
I'm using nuxt 3

**Comment by KareemDa** [comment]
How to change vite version ? 
I've installed it in Dev Dependencies but It's still using 4.1.4

@KaelWD

**Comment by lecaillon** [comment]
It works with `"vite": "4.2.0-beta.1"`

**Comment by KareemDa** [comment]
Reverting to 3.1.6 not fixing the problem even with a fresh install!

**Comment by webzhou** [comment]
i am use nuxt3, also wrong,who know why?

**Comment by KareemDa** [comment]
downgrade to `3.1.7` and make sure to remove the `^`

```
"vuetify": "3.1.7"
```

instead of:
```
"vuetify": "^3.1.7"
```

**Comment by webzhou** [comment]
@KareemDa you are right，thank u！

**Comment by Dinuz** [comment]
they changed the name of the file i had the same issue yesterday (your can look in your node modules to verify).

it should be _settings not settings (note the underscore).

```
@use  'vuetify/_settings'  with (
$field-font-size: 13px,
$label-font-size: 13px,
);
```

**Comment by lecaillon** [comment]
@Dinuz Yes exactly. Since in rename to `_settings` it works. Nice :) Thank you

**Comment by alexdeia** [comment]
I have the same since 3.1.8

**Comment by riodw** [comment]
why do they keep closing issues without updating the documentation?

**Comment by Dinuz** [comment]
@KaelWD so now is back to settings or still is _settings ???

**Comment by KaelWD** [comment]
It's always been settings. It wasn't renamed, there was a vite bug preventing it from being resolved correctly.

**Comment by Dinuz** [comment]
@KaelWD Perfect! Now works with Nuxt too!
