### ISSUE TITLE
[Bug Report][3.1.8] v-autocomplete not emitting update:search event

### ISSUE THREAD

**Issue by hbgl** [vuetifyjs/vuetify#16876]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create `v-autocomplete` and listen to `update:search` event.

### Expected Behavior
Event should get triggered when search value changes.

### Actual Behavior
Event is not being triggered.

### Reproduction Link
[https://codepen.io/hbgl/pen/WNgXLwO](https://codepen.io/hbgl/pen/WNgXLwO)

**Comment by MajesticPotatoe** [comment]
`v-on:update:search` or the short version `@update:search`
