### ISSUE TITLE
[Bug Report][3.1.8] V-Select Input details always rendered

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#16875]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-select without a hint.

### Expected Behavior
The v-input__details shouldn't be rendered if empty.

### Actual Behavior
An empty div that takes space get's rendered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUttu00AQ/ZVlXwxV7AUVJOSmVVEl4B2kPsRRtbEn7pK9aXcdiKL8OzNrR4QUKlV+mZkzPpexF3v+yftqOwCv+TyB8VomuGksY/NtKb3PZW6MVJa1WsZ43XAvyw8Nn8AMR9DQJho0iR4tV6Bx89s453+QWqEOkSyKO6nV2gWrZDFjxZ3TLsjOUf0ZS9Xl8RdwoR83vsMvGam43zmjbF8siXikvZmLo4ujaRyQ6zEONmOeuTjJiW1sg/KJRUgDwcp4FxLbswBrdmDr4Awr8EAFLbfOxsRM7Nk14a+Lr6C1Y/cu6O5V8YbIR7qJOu00qVTbUlk/pIeHDpJUOrI9eRIXrFMRrexqZp2FK3YhaL6S7aYPbrBd2dJNauaV3Vw19pAFMimf8dEpRvTVj+gsfsHM2kxAbHg96tAME1Df8MeUfKyFGKzf9FXrjLhFTITBJmWg7Jy5vawuq7el1P5RVu8FWkyncAXRlKvgfkYIKNzw2YlGUuvd/3QmGOnfVR9H2mlU4t8SifcJn0CRLYQygO0gQHg2w9nuv3KcrTzJQtJ45QOeV+PN49ll25ivujg6fHnIzECvL0nlMON/mUTZ/CJf/gaKMDUs)

**Comment by KaelWD** [comment]
`hide-details="auto"` if you want that.
