### ISSUE TITLE
[Bug Report][3.1.8] DataTable Double API call

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#16878]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

## Double API call

(_This bug encounters almost 90% (can be 100% as well) of the time so I'm sending your video as a proof_)

According to [this](https://user-images.githubusercontent.com/47495003/224260217-a18ab892-2d67-462e-b001-642d9e9023bf.mov) video and in this playground:
1. Go to last page
2. Go to second last page
3. Set page size to 10
4. Most of the time, We don't get any data rendered in table 🫣 (Due to two API calls instead of one)

https://user-images.githubusercontent.com/47495003/224260217-a18ab892-2d67-462e-b001-642d9e9023bf.mov

## Wrong pagination data

(_we used @change event for easier debugging_)

1. Go to last page
2. Search "qui" (_Hit the `tab` to trigger change event and allow table fetching data_)
3. Notice pagination data is "99-34 of 34" (🚨 WRONG!)

https://user-images.githubusercontent.com/47495003/224260425-40a3b1d4-7f73-46db-ad14-162c29f80d04.mov

### Expected Behavior
1. It should render rows when data is fetched
2. It should show correct pagination meta

### Actual Behavior
1. Rows aren't rendered
2. Wrong pagination data

### Reproduction Link
[Playground](https://play.vuetifyjs.com/#eNqVVm1v4zYM/iucUcDuENvrbcCGLMk67OXDcLjr1t0woC5WN2YSXWXZleV0QZD/PlKSX9JkB1w+tJJIPnwnfbcPfqzrZNtiMA1mzVKL2oDM1XqeBabJAmjQtPUiU6KsK21gD8uqrFuDxQQ0ribwkpvlBg6w0lUJIeGE32cqU8tKNQY2mBeoG5jDXaaAhI0wEqcQiiKcwBPuuuNhcky3/3uW7sZc9x32M6GSBVEYXnZPbeOU8fPdff9sKpPLDyPaV0TqiKJ5W+WFUGtPW+WywV60qo2gg6PNcrVbRPvDoE9LonQBiaJLmC9gz55I7Kjhxpi6mabpx6ZStcyXuKkkBSUxu1osqwITkk9z+diWTchmAQEyeJ3rvGTNCl/gwx9vbzHXy82NfY2sAx3nnnjXOAFhsGxuUN/QjTIy76xPtrlscSzxT2NySuYcIpaEGK4u4csjeeZ1FiR5XaMqovCZMnBrNIUqenaQl2TGCZvDHnjd/TyrFKUYsY4NYAFnsqYK1AoeLvYU0cMPF3uPYiovdnl4yBRnpcvLCqkmf85Nzh4OSWFiJTERalVF4a/MxHkvmLFt+EhhpnKbcOq8h1TMMNSIeyRUo7uAWl3RIMBvAInZoIo0Uv68cv4NhdgDvWvLR9TMmfhmSdZoovDv+E9mjn+qWmVCFz3++WAwPxcUFwI/s/eDXuvRWHHnuazWlshudTTbNL09TB1op47b9hgYxsBh7H5ZpkIXN2cX5Yb/2EER8bMvS9vyEQFPgDrir1wOmXoF/N534XJDgwmLLyz8wEf1TChk3G+3798lVB0NRvbY2PoQqx1r6WLoJZzKTwp5q3yvvbKJNU4XC64W1t45fMTjdXRsHq+3vS9Tl8VuBhaI9dRWGFDgrHYXu+fJuWq2mn5vUe+grSl94/ikKdgyh2eiCyxcrYsVrIS2I8Y1Oj1ER7OC4kFjYT6f02A4aysB/0KFAB9bgnFpASo9iwi5KmiWwIuQktwQ6zVqeOgBqFcB0FYRA5/TC1eun2epW0i0fuhCw4Hmp0G6Acy2MU0Re7SXMhfK3+zd4L8mXgmUBW2zR5S0ztwATZKEttq1s5leeY1c4BaVSWhOUe/5aRksZukYZgzOUYxN/igxpubZou5oAFPfxYTsT1kwotoJRzTbdEcU6RqNaH3TnUrGEtXabHg396PkDFeNOuZIEt+bMfnaFcjUx5zIw35zMRi4B38pDCcO91Q7paawp9U9bNkD1W0n2ieGLy5ls3SUymASuE8L4qztTKMPEVvgFAlLIA9JgUPMAvrC4DuF1+/VVtVPa7tEr4mWapqXosS4qMrrr5M3yTffpoVozPg9waaMH3X1QsaSxiywjefBDXX+/ynwZMK9Sr5zsP4ppiJrGPcEL3UBizVtPNRUKp8y/hXvkQOvaCdO2BFCfUMBlUI9uf0wxHLZ2Dja7zC+f753FoHF6RPsEBwmgbOO9FmJ4P4/8K5kiA==)

**Comment by jd-solanki** [comment]
> _Please don't report multiple bugs in one ticket._

Sorry about that 🙏🏻 

> _The wrong pagination data is because you are not setting :page="options.page"_

Yes, Thanks 👍🏻

**Comment by jd-solanki** [comment]
Hi @nekosaur 

Thanks for resolving in quickly. Unfortunately, DataTable still has an issue as follow:
- Visit updated [playground](https://play.vuetifyjs.com/#eNqtVttu4zYQ/ZWpsICUwpJyKVDUtd0UvTwUi9206RYFoqBRrLHNDUUpFJXUMPzvnSGpi+M0T+uHhOQMz8ycuVA3u+DHuk6eWgymwaxZalEbkLlaz7PANFkADZq2XmRKlHWlDexgWZV1a7CYgMbVBJ5zs9zAHla6KiEknPD7TGVqWanGwAbzAnUDc7jJFNBlI4zEKYSiCCfwgNtuuZ8cyu3/XqXbsdZth/1IqORBFIYn3VHbOGN8fHPbH5vK5PLTSHZKok4omvdVXgi19rJVLhvsr1a1EbRwslmutototx/saUmSjpAoOoH5AnYcicROGm6MqZtpmn5uKlXLfImbShIpidnWYlkVmND9NJf3bdmE7BYQIIPXuc5LtqzwGT798f4ac73cXNnTyAbQae5Id40TEAbL5gr1Fe0oI/PO++Qply2Ob/zTmJySOYeIb0IMZyfw9cF91nUeJHldoyqi8JEycG00URU9OsgTcuNIzWEPum7/uqoUpRipjh3gC85lTRWoFdy92xGj+x/e7TyKqfy1k/1dpjgrXV5WSDX5c25yjnBICgsriYlQqyoKf2UlznvBim3DS6KZym3CqfMRUjHDUCPukFCN7gi1tqLhAp8BJGaDKtJI+fPG+TcUYg/0oS3vUbNm4pslWaOJwr/jP1k5/qlqlQkde/zzZLA+FxQXAh9z9INdG9HYcBe5rNZWyGF1Mts0vT8sHWTHgdv2GBTGwGHsflmmQseb84tyw3/soIj42JelbfmIgCdAHfFXLodMvQD+6LtwuaHBhMVXFn7Qo3omFHLut+uPHxKqjgYju2xsfYjVlq10HPobzuSbl7xXvtde+MQWp4sFVwtb7wI+0PE2OjWP1/vel6nLYjcDC8R6aisMiDhr3XH3OHmtmq2l31vUW2hrSt+YnzQFW+bwSHKBhat1sYKV0HbEuEang+hgVhAfNBbm8zkNhld9JeBfqBDgc0swLi1ApWcRIVcFzRJ4FlJSGGK9Rg13PQD1KgDaKmLg1+zCmevnWeoeJHp+aEPDgeanQdoBzJ5imiJ2aTdlLpTf2b3Bf028EigLes3uUdJz5gZokiT0ql06n+mUn5F3+ITKJDSnqPf8tAwWs3QMMwZnFmOT30uMqXmeUHcygKnvYkL2qywYSe2EI5ltugOJdI1Gsr7pDuTMDAk7umzqjpBjiWptNvx296PmFa0adezxzsfiS1dAU29kMNdzNGgPfBBNR4T0UjvFprCjp314hfdU193VPnG8cSmdpaNUB5PAfXqQZm1nHn2o2AYgpqyAIiQDDjEL6AuE90S/f3dbVT+s7SN7SbJU0zwVJcZFVV5eJOfJN9+mhWjM+DzBpozvdfVMzpLFLLCN6cENTYa3DLA8VWK9MXJLBs6S78jxxhDj56fnF6cXZ+fJqbPolWOqz4ZNHplKHZexpscSNVXZW3G90D2I7YXsKD47fajliGsp1IN7Wgaal42l2H7C8f6LBm7BGZk+7PbBfhI4x8mV/8EIbv8DmTaDiw==)
- Go to next page (2nd)
- Search `qui` and hit enter

Notice multiple API calls are triggered 😱 

It will be less confusing if you can update the docs and describe things we need to take care of like we need to assign `:page="options.page"` in server table to avoid raising invalid issues.

Thanks for your time and efforts 😇 

Awaiting your response.

**Comment by nekosaur** [comment]
The multiple calls is due to how you have written the code, not the data-table itself.

[playground](https://play.vuetifyjs.com/#eNqtVttu4zYQ/ZWpEKzkwpJzKVDUddwULfpQLHbTpikKREFXsca2GoqSSSqpYfjfO0NSF9vbPK2BICTPcK5nhnrYBT/WdfLSYDANZnqhitqAyOTqOg2MTgPQaJp6nsqirCtlYAeLqqwbg/kYFC7H8JqZxRr2sFRVCSHpCb9PZSoXldQG1pjlqDRcw0MqgS6bwgicQljk4Riecdsu9+ND3P7vRNodSz22ujeklTyIwnDUHjXaGePjh8fu2FQmE/cD7JygFiz0+yrLC7ny2DITGrurVW0KWjhslsntPNrtO3ShMDN4rwThEYnqEVzPYcehCCR3LBCujan1dDL5R1eyFtkC15WgrCRmWxeLKseEMjrJxFNT6pD9Akoxa68zlZVsWuIr3P/+/g4ztVjf2tPIRtBK7kh2hWMoDJb6FtWt3W2oKtccgR7K/q1NRnUkh/kOxHAxgq8PbrLsBt698w4kWV2jzKNwQxW4M4pSFW1GZB+OBZzqXsrtPy8qirIYiA7t8wXnsSLuKQmfznaUyv0PZzuvxVT+2mj/KZX7vphLJDL+nJnstCCeIbYkXd2cTAtXApNCLqso/IX1MCdy1tVoXlIFiIpjVjEiikPPnOQlEw2SXqMayh5j1pGIRXkHkJg1ykghldP7w7+emJ2KD035hIolE988yQpNFP4V/8HC8U9VI03ocso/nyKWZ34xL/iYOdrbtVEMDbfRimplQQ6oxWwTdf4w2mOnIdt26QWGisPY/dJUhi5jzi9fMTs4Ij72TWZHQESKx0AN8mcm+uIdKf7ou3KxpkGF+VdWfS9HJCct5Nyvdx8/JMQZjZFdasuaYrllK20O/Q1n8s1L3ivfekc+scXpfM4MYettwAcy3kYr5vV1vnfsZVpygC7L1s92QOaI9dQSDSiL1hWXyM0YokO2d2Z/a1Btoamplm2yADqWWoM7SJLkwCrNjyls2jXPiilc2Prx32zingp6GGhDzUuDzSDtAGYvMXW5XdpNmRXS7+ze4L8mXhYocnpnnlDQQ+MmG3lA782NKyqd8oA/wxeUJqE5Ql3gnEmD+WwyVDNUznSNTfYkMCYav6BqMYCp7yfS7FdpMEDtBCLM0v8AEY7yhHX0P8A5NwS22ePtqeZYoFyZNb+qXdN/RqpGFXt9l0P4xlVv6o305roc9dJ9PihNJwnpUDtPprCjR7d/H/dEqvZqVzjeuJLOJoNSB+PAfRSQZG2nD31CWPZRpixAEZIBpzEN6NuA95R+/yA2sn5e2dfvhrCJoslWlBjnVXlzlVwm33w7yQtthucJ6jJ+UtUrOUsW08B2hVduqEffMsD4RBartRFbMnCRfEeOa0MZvzy/vDq/urhMzp1FLxwTPzWbPDE1cbmMFT1mqIhlb8V1JHsQ2xF2Ep9tfWo5yrUo5LMb8n2aF9qm2H5c8f6LBm6Vs2b65NoH+3HgHCdX/kdH8PgfB11gzA==)

**Comment by jd-solanki** [comment]
Hi @nekosaur 

Thanks for your quick response. Me and my colleague were testing it and found that there's still an issue with playground you shared. we need to pass query in watcher of `options` like below so query get considered when options are changed:
```diff
- fetchData(options.value)
+ fetchData({ ...options.value, q: q.value})
```

Moreover, we have updated the query watcher as below because if you go to 3rd page and search for `qui` then page is at 1 but table still shows pagination meta as page it at 3:
![image](https://user-images.githubusercontent.com/47495003/224699607-d0a3a1d0-3697-4f70-a91b-b71d6c716647.png)

```diff
- fetchData({ ...options.value, q: q.value, page: 1 })
+ if (options.value.page === 1)
+   fetchData({ ...options.value, q: q.value })
+ else
+   options.value.page = 1
```

With these changes, we are back to the original issue of multiple API calls:
1. Go to 3rd page
2. Search `qui`
(_3 API calls_)

Sorry to bother you but I consider this issue as help towards making data table more robust and well-tested.

Awaiting your response.

Regards.

**Comment by jd-solanki** [comment]
As this issue persist, can we reopen this?

**Comment by jd-solanki** [comment]
Hi @nekosaur Sorry for disturbing but as this issue is closed and considered as resolved in latest release I wanted to confirm, Aren't you able to reproduce the issue mentioned in [this](https://github.com/vuetifyjs/vuetify/issues/16878#issuecomment-1466047216) comment?

I also checked the latest vuetify docs but there isn't a search demo I can take a look at.

Can you please let me know if the issue is with the vuetify or from implementation in [this](https://play.vuetifyjs.com/#eNqtVm1v4zYM/iucUZydIXb6csCwLMk6bNiH4XDXreswoC52TswkXm3ZkeR0QZD/PlKSX5J0BQZcvkQSKZJ6+JD04977oaqibY3e2JuohcwqDXkiVtPY0yr2QKGuq1kssqIqpYY9LMqiqjWmQ5C4HMJLohdrOMBSlgX4ZMf/LhaxWJRCaVhjkqJUMIXHWABd1pnOcQx+lvpDeMZdszwMj+Xmv1Vpdqz11NjekFWKIPD9QXNUK+uMjx+f2mNd6iR/6MkuSdQIM/WhTNJMrJxsmeQK26tlpTNaWNkkEbtZsD+00oXEROODzEkekKoawHQGe35KjhSOEfhrrSs1Ho3+VqWo8mSB6zInVCK9q7JFmWJEiI6SfF4Xyue4gCBm61Uik4JdC3yBh98+3GMiF+s7cxqYFzSae9Jd4RAyjYW6Q3lndhvKypRfoPq6fymdUB4pYL4DIVwN4Oujm6y7gXfvXABRUlUo0sDfUAbutSSogs2A/MOpgjXdadn966p5VmQ91b5/vmAjlsQ9KeDzxZ6gPHx/sXdWdOmuDQ6fY3HokrlEIuNPiU7OE+IYYlLS5s3qNOIyxygTyzLwf2Y7zImUbdWKl5QBouKQTQyI4tAxJ9omeY1kV8ua0GOZCSRgVd4BRHqNIpBI6XTx8K8jZmviY13MUbJm5IonWqEO/D/D31k5/LGshfYtpvxzELE+84t5wcfM0c6veUXfcfPavFwZIT+okZkiauNhaSc7f7Ipl06hb9gP7S+OhW8Rs3G5jJnGEfCxKzLTAgIyPAQqkD+SvEveieFPrioXa2pUmH5lzHd6RHKyQsH9cv/pY0ScURiYpTKsyZY79tJg6G5Yl29eclG50juJiT2OZzNmCHtvHnyk43w0as5eG3vL3mAPURQ5WCzUVM5j2Ni1TW7TMlPEamyoB4SrCc5CuxlCcMz/NpBfa5Q7qCvKbgMfgOH00tRN55eQoC4xnU6pT/y/KB0H0fCDL75mF66IDaQ3GdnRQ4OGNtQMqFFqpB3AZBtS1zBLsymSTLid2Wv8R4fLDPOU5tYccxpctlNScDS/bi1J6JQHxgVuUeiI+hJVlY0k9maTUd9M3zjTP9TJPMeQymKLspEBjF19kmW3ir2e1HQ0kplyOpLktoRI1pbTkZyRIWEDF2/PLYc5ipVe85Rum8grWhXK0Nm77otvbe7HzknnrsWo0+7wIJjOAGmlpj+NYU9DvJu3B6Jkc7VNHG9sSiejXqq9oWc/MkizMt2MPkkMdwkpI6AXkgNrMfboW4P3BL8bsLWonldmmt6SbCSpU2YFhmlZ3N5E19H7b0ZppnT/PEJVhHNZvlCw5DH2TE0545pq/i0HLB+JbLXW+Y4cXEXfUuBKE+LXl9c3lzdX76NL69Eph8RPxS7PXI0slqGk4YiSWPbWu050j952Ijt7n2kcVHKEdZ6JZzs0OpgXykBsPtZ4/0UfboyzZfqEO3iHoWcDp1D+w4b39C+G53p0) playground (Same playground if you perform [mentioned](https://github.com/vuetifyjs/vuetify/issues/16878#issuecomment-1466047216) changes in your [playground](https://github.com/vuetifyjs/vuetify/issues/16878#issuecomment-1465722114)).

If you are also getting this issue, can you please reopen it?

Awaiting your response.

Regards 🙏🏻
