### ISSUE TITLE
[Bug Report][3.1.8] handle of switch is too dark in dark theme

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#16872]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.63
**OS:** Windows 10

### Steps to reproduce
Turn on dark mode. It's hard to distinguish the handle of switch from background.

### Expected Behavior
Vuetify v2 is good
![image](https://user-images.githubusercontent.com/40021217/224029777-a015e1ba-76ae-4f9f-a8e0-50e03d70b6c2.png)

### Actual Behavior
v3 is too dark
![switch-handle](https://user-images.githubusercontent.com/40021217/224029550-30f41967-3353-4963-a3f9-99a3dc9f97d3.png)

### Reproduction Link
Ignore

**Comment by KaelWD** [comment]
Duplicate of #16363
