### ISSUE TITLE
Dialog scroll position does not reset on subsequent shows

### ISSUE THREAD

**Issue by gurpal2000** [vuetifyjs/vuetify#1687]
### Steps to reproduce
You can take Dialog Example 7 (Overflow), scroll it, close it and then show it again.

### Versions
0.15.3 using latest Chrome/Opera/Edge

### What is expected ?
The scroll position for the dialog should reset to zero.

### What is actually happening ?
It could be that the dialog state is being cached, which i totally understand. But i was expecting the scroll position to be reset.

### Reproduction Link

https://vuetifyjs.com/components/dialogs - Just try the codepen on example 7 and you'll see.

**Comment by johnleider** [comment]
Unfortunately this is default behavior. If you wish to change it, you can manually change the scrollTop of the overflowed element programmatically.

**Comment by kreischweide** [comment]
Sorry for the comment on the closed issue, maybe this will help someone else who isnt as advanced in JS as me and has no idea what a possible solution would be. Here an example that could work on the first dialog example in the docs:

```js
watch: {
  dialog: function (value) {
    if (value) {
      this.$nextTick(() => {
        document.querySelector('div.dialog__content > div').scrollTop = 0
      })
    }
  }
},
```

So every time the dialog variable is set to true we let Vue do a pass of work that shows the element and so on, then scroll the overflowed element back to the top. Not even sure this is a good way but what gives.

**Comment by liebsterkamerad** [comment]
Yeah, that's working with document.getElementsByClassName('dialog dialog--active')[0].scrollTop = 0

**Comment by waldandrade** [comment]
Please add to docs that now is possible to set the container in option atributte.

Like this:

goTo ( '#divId', { container: '#scroll-target' })

**Comment by gadelkareem** [comment]
`document.getElementsByClassName('v-dialog--active')[0].scrollTop = 0`
