### ISSUE TITLE
[Bug Report][3.1.8] v-dialog off-center on small screens but only on mobile devices

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#16882]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** iOS, Android

### Steps to reproduce
Create vue 3 app with vuetify 3
Add dialog
Deploy somewhere
Open on a device with a small screen (iPhone 5/SE, Google Pixel 3, ...)

### Expected Behavior
* Dialog has same padding on both sides
* Dialog width scales down with screen width

Desktop browser with viewport width at 180px:
![image](https://user-images.githubusercontent.com/11460463/224322397-7c96c595-24a0-4844-a1be-cdf28c23be61.png)

### Actual Behavior
* Dialog is off-center (looks like right margin was added to the left)

Google Pixel 3 Web View (in Android emulator)
![image](https://user-images.githubusercontent.com/11460463/224320581-637c5636-fd3b-4d4e-9075-a57ce0ad35cc.png)

Google Pixel 3 as native app with Capacitor (in Android emulator)
![image](https://user-images.githubusercontent.com/11460463/224320739-7a4fb45e-fb4f-4223-980a-c78925ec4923.png)

I got user feedback from someone with a real iPhone 5/SE who had the same issue

### Reproduction Link

It's just a plain `v-dialog`:

[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMtOwzAQ/BXLl4LUxOIhgUKKCgIhTpw41T2kybaYxg/ZTlFV5d9Z51GFVCBx886MZ2Z3caAPxsS7CmhCUw/SlJmHe64ISXdRZkzzbAaZCdVNzVyIrNQbgoQuoJxx2gKv7s2A4vQoRbEhzu9LQM0qy7cbqytVRLkutU2IheIO1U/Pj+8vKevz8BPrI/oKCBw7hKFtl7JBaxxdboXxxIGvAi2k0daTA+asSU3WVksywXUnQZxr5TwZ9iazIDzztoLz4N26oQ+d0tYKO5j402mFBzuEKrwjHKcJaZCAYUSYOf3w3riEsUqZ7SbOtWRz5JitlBcSokLL+VV8GV/fsEI4P8RjcDJaWf3lwGIip9OBuRfr/W8BHY2+F/Fta9tBUZmtXPA98WMYsgMbWVAFWLB/lh9pfyww4k6WCJk1VzUetBRq60a3zF1zx0Vf7f/bNQ7h+zKk1FPatsO85gddfgPKtvrq)

### Other comments
This only happens on old mobile devices (iOS and Android). It does not happen if I reduce the size of the browser window on a desktop browser. Even it is way below the viewport size of the mobile device (< 200px) the dialog scales down correctly and stays centered.

So it might not be related to the screen size but the age of the device. Or maybe the scaling factor that was set back then?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/browser-support/

iPhone 5 only has up to Safari 10, and google pixel 3 is likely limited to a similarly old version of chromium. If you absolutely have to support devices that old we recommend using vuetify 2.

**Comment by frederikheld** [comment]
ok, thx

**Comment by frederikheld** [comment]
I would like to re-open this issue. The Google Play Pre-Launch report shows this issue on a Google Pixel 5 with API Level 30 (Android 11).

> "As of January 2023, Android 11 was the second most popular version of the Android OS with a share of 23,03 percent." (Source: https://en.wikipedia.org/wiki/Android_11)

Starting with API Level 31 (Android 12) the dialog is centered as expected.

So I think this should be looked into as it does not only affect very old devices.

**Comment by KaelWD** [comment]
Is that a real device? Apparently since android 5 webview has been updated from google play instead of with the OS. My old phone with android 7 (api 24) displays it fine in webview tester.

**Comment by frederikheld** [comment]
I don't know what Google Play is testing against, the emulator I presume. So it might be possible that they use the WebView that was shipped initially with that version of Andorid. But on the other hand: why would they? The idea of the pre-launch report is that you get feedback how the app performs and looks like in the real world, so they should use versions of WebView that are still out there. Unfortunately the pre-launch report gives no info about what version of web view they are using. I'll dig deeper.

Is there any chance that this is not related to WebView?

**Comment by frederikheld** [comment]
Api 24-28 seemed to use a different WebView implementation. See https://developer.android.com/develop/ui/views/layout/webapps/webview-testing

So you might be below the version that has the issue.

I dug up my old Galaxy S10, which should be API level 30 (Android 11). Just have to wait until it is charged ...

**Comment by frederikheld** [comment]
Wonderful, thank you so much!

**Comment by KaelWD** [comment]
I think I'll have to revert this, it breaks animations.
