### ISSUE TITLE
[Feature Request] Support style prop for global defaults

### ISSUE THREAD

**Issue by Q16solver** [vuetifyjs/vuetify#16896]
### Problem to solve
More flexibility in overriding specific styling in certain situations e.g. I want to allow scrolling and limit the max height for a v-container inside a v-window-item, but currently I am unable to do that without writing a custom component for this case, which is clunky and not great for bundling logic together in one component since it's just for styling.

### Proposed solution
Allow style as a global prop? This would have higher priority than all other defaults but be overwritten by the style prop in sfc

Example:

![image](https://user-images.githubusercontent.com/50786287/224520393-72287640-14c4-4763-955c-714ce3da48e2.png)

**Comment by yuwu9145** [comment]
https://github.com/vuetifyjs/vuetify/pull/16459
