### ISSUE TITLE
[Feature Request] Export Data Table Types

### ISSUE THREAD

**Issue by griest024** [vuetifyjs/vuetify#16897]
### Problem to solve
As an app dev, when creating data table headers (among other things), I want to have type hinting and autocompletion.

### Proposed solution
Export `DataTableHeader` and other types that will be beneficial for app devs to consume while building data to pass to data tables.

**Comment by andreimakushkin** [comment]
I found one of the solution. Correct me if I wrong, but it seems to be worked. 

I guess you can `import { VDataTable } from "vuetify/labs/components"` and than get type by reffering to `headers` key `VDataTable["headers"]` 

`type DataTableHeader = VDataTable["headers"];`

**Comment by griest024** [comment]
@andreimakushkin I tried that, `VDataTable['headers']` is actually typed as `DataTableHeader[] | DataTableHeader[][]` which doesn't work that well. Its a good idea though

**Comment by nekosaur** [comment]
doesn't work well how? that is the correct type.

**Comment by griest024** [comment]
when trying to build an array like `map<VDataTable['headers']>(...)` TS does some weird type inference that doesn't give me the correct type hinting and generally doesn't achieve what I want. I can post the exact code later if you're interested in seeing it.

**Comment by griest024** [comment]
`VDataTable['headers'][number]` does actually work fine so I'll close this. Its a little cumbersome not to have direct access to the types though.

**Comment by scscgit** [comment]
Doesn't work for me, I'm getting `Type 'DataTableHeader[] | DataTableHeader[][] | undefined' has no matching index signature for type 'number'.ts(2537)` even if I use the workaround of adding ['$props'] from https://github.com/vuetifyjs/vuetify/issues/16680#issuecomment-1433246791 (and the solution mentioned in that comment is giving me `Cannot find name 'DataTableHeader'.ts(2304)`)

**Comment by scscgit** [comment]
Can this issue be reopened, or does anyone have a solution regarding the extracted union type?
> `Property does not exist on type 'DataTableHeader | DataTableHeader[]'.`

![image](https://github.com/vuetifyjs/vuetify/assets/3118390/055f9843-67c7-4263-9b10-6d8a71a53736)

**Comment by joel-wenzel** [comment]
@scscgit This works for me:
```
import { VDataTable } from 'vuetify/labs/components'
export type VDataTableHeader = Extract<
  VDataTable['headers'][number],
  // @ts-ignore
  DataTableHeader[]
>[number]
```

**Comment by scscgit** [comment]
```ts
get headers(): (Extract<
    VDataTable['headers'][number],
    // @ts-ignore
    DataTableHeader
  >)[] {
// return ...
}
```

works correctly (this also variant lets me add custom fields via `& {...}`), but it still doesn't let me assign the resulting type to the `headers` prop:

![image](https://github.com/vuetifyjs/vuetify/assets/3118390/51c25177-97e5-4957-aa40-5870f776964f)

**Comment by scscgit** [comment]
For new visitors of this issue: take a look at https://stackoverflow.com/a/75993081 for a more complex explanation & solutions... (And to Vuetify team, please re-open this issue and export it!)
