### ISSUE TITLE
[Bug Report][3.1.9] inline styling of table rows in the item slot no longer works

### ISSUE THREAD

**Issue by lukasrossa** [vuetifyjs/vuetify#16909]
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
In Vuetify 2.7, inline styles worked on \<td\> as well as \<tr\> elements inside the VDataTable's v-slot: 
```
<v-data-table
      :headers="headers"
      :items="desserts"
      item-value="name">
    <template v-slot:item="{ item }">
        <tr :style=" {backgroundColor: '#ffebee' }">
          <td :style=" {backgroundColor: '#e3f2fd' }">{{ item.columns.name }}</td>
          <td>{{ item.columns.calories }}</td>
        </tr>
      </template>
```

### Expected Behavior
In Vuetify 3, only the \<td\> styling is working while the \<tr\> seems to be ignored. 

### Actual Behavior
both detail and rows should be able to be styled

### Reproduction Link
[https://codepen.io/lukasrossa/pen/poOLMGw](https://codepen.io/lukasrossa/pen/poOLMGw)

**Comment by KaelWD** [comment]
The default background-color is now on `td` instead of `.v-data-table`

**Comment by lukasrossa** [comment]
@KaelWD so what does that mean for wanting to style just rows in a table? Doing it by cell seems inefficient?

**Comment by johnleider** [comment]
@nekosaur can you provide your feedback?

**Comment by nekosaur** [comment]
I can't say for sure, but might have put it on td so that I can do fixed headers and columns?
