### ISSUE TITLE
[Bug Report][3.1.8] Color is not correctly passed to SVG icons since 3.1.3

### ISSUE THREAD

**Issue by ferferga** [vuetifyjs/vuetify#16907]
### Environment
**Vuetify Version:** 3.1.8
**Last working version:** 3.1.2
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.69
**OS:** Linux

### Steps to reproduce
1) Clone the repository
2) Download dependencies by running ``npm ci``
3) Run ``npm run prod`` and open your browser at ``http://127.0.0.1:3000``. Open the console to see the state changes
4) Click the buttons. Buttons will not change it's color, although they should based on the state you're seeing in console.
5) Kill ``npm run prod`` and run ``npm remove vuetify && npm i vuetify@3.1.2``
6) Run ``npm run prod`` again. Repeat the steps from 4) and see how the color changes correctly, **demonstrating a regression**

### Expected Behavior
Color should be changed according to the state of the elements

### Actual Behavior
No color change

### Reproduction Link
[https://github.com/ferferga/icon-issue-vuetify](https://github.com/ferferga/icon-issue-vuetify)

### Other comments
Font icons seem to work fine, based on this reproduction link with the same exact code (just the icon references have been changed). I assume this problem applies only to SVG icons (hence the title used)

[Playground link](https://play.vuetifyjs.com/#eNqVVF1v2jAU/Su3fgGkfACbtCkjlD32odq0PTZ9CIkDHkls2Q5Vh/jvu7YTCKEtmoQEts8595xrX54O5LsQwb6hJCILTStRppoukxpgsffXuja/AFjG21+RYn9pnBDzlZB2L+Mll7jJ1O9tUxQlqzdwDyMhWZXK1xFE0NQ5LVhN846zykqW7QacGO56y4RYH9aJMdCuAKqc+cqiaAsIewizQONXGW44/0UFTbVxcRfHML3lPzL1kCgt7cH0Z5gs26b1hjrdR55jUQjR1SLstRmXKpNMaFBUNwJKpCBVKxueVYJLDQeQtPDgJdXZ1oOMV6LRNIcjFJJXMMLLG307gR8ec+Zq/qgz2kGY1E1aWtMqxP6FzrfPEfMm+QbRcJK2Jz8lF2pxANPY+wiUlqaLx+V4YkGGqeHymjHPuEhLRQ2kA5xvwAGmjm9jj3t8D8YTiJfYiFrxkgYl34xHfX3X+AhGXr9ssE/Lhk6MaCd5qviO5NnRheRpuyfZxRheOmZx0od2kgroF3YKEJsnN+kwFneNgRnWMWdHoNi6D6RmN6Xml1I30NMOndT46aKenz5Culc5tmkN/G1rc6eE02WmuP8K27nqH+Ce6e0idDOCssQj7qn6VSqCP4rX+L9l3eMM2wOcnKjLkxCcDbNOyFZroaIwbGqx2wToNlzhWSibWrOK+jmvVp+CefD5S5gzpfv7AVWVv5b8RVGJFRPi9cQ1K17fK9Aeo+4s+Opk2y2/TNfK6F7phVhkTyXmx+GSVH5ofoC9CDA4uwphaprrxIbicOzUoJeZsn186qz9fzqrYOjPpsrRI84d1rMM8vwPSjsoMw==)

**Comment by KaelWD** [comment]
This is not due to SVG icons, you can reproduce it in the playground by adding the same defaults you have in the repo, specifically `color: ""`
