### ISSUE TITLE
scrollTop triggered from javascript doesn't trigger the scrolling techniques primary menu to re-appear

### ISSUE THREAD

**Issue by MyMediaMagnet** [vuetifyjs/vuetify#1690]
### Steps to reproduce
Setup scrolling techniques to work with a custom container.  Create a button that triggers javascripts scrollTop function to move the user back to the top of the screen.
### Versions

Vue: ^2.4.2
Vuetify ^0.15.2
### What is expected ?

After programatically scrolling to the top of a container, I'd expect to have the primary toolbar re-appear similar to when a user would scroll back up manually.
### What is actually happening ?

Currently, the primary toolbar remains hidden.
### Reproduction Link

https://codepen.io/developerplus/pen/mBbjBq

**Comment by MyMediaMagnet** [comment]
Here is what I have done to get things working for me.  I've updated the codepen with the solution.

```
let event = new CustomEvent('scroll')
container.pageYOffset = 0
setTimeout(() => {
  container.scrollTop = 0
})
container.dispatchEvent(event)
```

**Comment by johnleider** [comment]
I'll have to assume this fixed as the previous example does not exist anymore for debugging.

**Comment by MyMediaMagnet** [comment]
What i described in my second post has been working just fine for me.  If there is a better way of approaching this however, I'd be interested in hearing.

**Comment by johnleider** [comment]
Well I'm not sure if there is a better way, but I couldn't test the initial error.

**Comment by MyMediaMagnet** [comment]
Okay, try again.  I've done it the original way now.
