### ISSUE TITLE
[Feature Request] Types: Color type

### ISSUE THREAD

**Issue by 0x00A1FA** [vuetifyjs/vuetify#16906]
### Problem to solve
Type safe color attributes (e.g. VBtn['color']).

### Proposed solution
	type ContextualColor =
		| 'background'
		| 'surface'
		| 'primary'
		| 'secondary'
		| 'success'
		| 'warning'
		| 'error'
		| 'info'

	type BaseColor =
		| 'red'
		| 'pink'
		| 'purple'
		| 'deep-purple'
		| 'indigo'
		| 'blue'
		| 'light-blue'
		| 'cyan'
		| 'teal'
		| 'green'
		| 'light-green'
		| 'lime'
		| 'yellow'
		| 'amber'
		| 'orange'
		| 'deep-orange'
		| 'brown'
		| 'blue-grey'
		| 'grey'
		| 'shades'

	type Tone =
		| 'base'
		| 'lighten-5'
		| 'lighten-4'
		| 'lighten-3'
		| 'lighten-2'
		| 'lighten-1'
		| 'darken-1'
		| 'darken-2'
		| 'darken-3'
		| 'darken-4'
		| 'accent-1'
		| 'accent-2'
		| 'accent-3'
		| 'accent-4'

	type Color = ContextualColor | BaseColor | `${BaseColor}-${Tone}`

**Comment by KaelWD** [comment]
Impossible without requiring declaration merging, you can have arbitrary theme values.
