### ISSUE TITLE
[Bug Report][3.1.8] VBtn icon sizing is not correctly passed

### ISSUE THREAD

**Issue by ferferga** [vuetifyjs/vuetify#16908]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.69
**OS:** Linux

### Steps to reproduce
* Open the link. See how the shuffle icon is bigger than the repeat one
* Remove the ``size`` prop from the ``v-icon`` component. You'll see that both shuffle and repeat (passed as a prop) keep the same size.

### Expected Behavior
By default, icon size should match the button's size. This should be overriden only if an explicit size is set to the ``v-icon`` component.

There is actually a functionality friction, as passing an icon as a prop has not the same capabilities than using slots.

### Actual Behavior
Icon size doesn't have any correlation to the parent

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVE1v2zAM/SusLk4AfzTZgA1e3GXHHooB27HuwbHlRIstGZKcrgvy30dJduI4bYMCAWKTj4/vUaIf9+RH04S7lpKYLDStmyrT9C7lAItdsNLcPAGwXHRPsWL/aJIS85eSLpaLSkgMMvV705ZlxfgavoPXSFZn8sWDGFpe0JJxWvQ1y7xi+XZUk8DN4DUlVodVYgSMendJgLpggbJFtMNHrsDZwBf0cWHpipFftKGZNqJukgRur9mJTT8slLbs3oxrbDTfZHxNHe+DKLApRKhqEQ2mjq8ql6zRoKhuG6iwBEu1snZZ3QipYQ+Slj48Zzrf+JCLumk1LeAApRQ1eHiW3rcj+P6hYK7nT57THsKkbrPKilYRzi9yugOBmFeLrxSampSbICrHgeJJen+DKpNrS9enzs8aXUzKrFJ0ipAecJq7A9yaZMqt2cmg3ofJFJI7tM+VqGhYifXEG/K7ccfg+cO24S6rWjo1pD3lseMblCdFZ5TH8ICytzE+avTiqPfdOpUwbOwYIDEXbdpjLO4SAzPsY3IHoDi6d6hmV6nm51RX0Lc9OuX4662eLjxC+rs4sW4N/HVpc8eEO2V2d3j3um0aJjBmZruI3GYgLfGJu6BBnTXhHyU4frysetxcm8B9iXs/KcGNMO8p2WjdqDiKWt5s1yGqjZaYi2TLNatpUIh6+Smch5+/RAVTehgPqaqDlRTPikrsmBJ/QK5Z+fJWgy6NvLPwq6PtQrgeK2V4L/gibLKjEv3jZ0ZS+a74EfbMwCh3YcL0NMeJA8Xl2KrRLHNl5/jYS/u4O8tgyp9Ml4NPnDrsZyvI03+hDClM)

### Other comments
In my opinion, both the prop and the slot should provide the same functionality, so an ``icon-size`` prop for VBtn or an object like ``{ icon: boolean | string | (new () => any) | FunctionalComponent, size: string | number }`` should be used for the prop instead.

That is a bit convoluted, so I understand it's unwanted. In that case, I think it's better to leave all the "advanced" behaviour to the ``v-icon`` used as an slot as in my opinion  it's more explicit and, by default (either slotted or by prop) the icon should just follow the parent's size.

**Comment by KaelWD** [comment]
We did have that briefly but it was reverted: #15515

Icons use em for sizing and btn size affects font-size, so the scaling is too extreme.

VIcon large: 2em (32px)
VIcon default in VBtn large: 1.5em * 1.125rem = 27px
VIcon large in VBtn large: 2em * 1.125rem = 36px

This is worse when you go smaller:

VIcon x-small: 1em (16px)
VIcon default in VBtn x-small: 1.5em * 0.625rem = 15px
VIcon x-small in VBtn x-small: 1em * 0.625rem = 10px

**Comment by ferferga** [comment]
@KaelWD First of all, sorry for not looking correctly for opened issues.

Does that mean that even when passing a ``size`` prop to ``v-btn`` the scaling won't work fine? In my playground, the scaling works perfectly, the only problem is that the prop is not passed to the underlying ``v-icon`` basically.

**Comment by KaelWD** [comment]
It looks ok when you go larger than default, but try `size = 'x-small'` in your example and the first one is pretty bad.

**Comment by ferferga** [comment]
@KaelWD Fair enough, thank you very much!
