### ISSUE TITLE
[Bug Report][3.1.9] VTabs are not updating correctly when using the `to` prop and router.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#16918]
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Please clone the repo and use the `router-and-tabs` branch.
Use Yarn to setup and run.
Open in browser.
You should start on the home page. Select another page using the tabs.
Click the back button in your browser or in the indicated button on the reproduction.
Observe that the home tab is not set to active.

### Expected Behavior
The home tab should enter a selected state when you navigate back to the home page using the browser back button.

### Actual Behavior
The home tab does not update when you use the browser back button to return to the home page.

### Reproduction Link
[https://github.com/MatthewAry/vuetify3-reproduction-template/tree/router-and-tabs](https://github.com/MatthewAry/vuetify3-reproduction-template/tree/router-and-tabs)

### Other comments
It seems that when you use tabs on named child routes and one of the routes has `path: ''`, that the tab for that specific route misbehaves. I expected to see this issue resolved by adding the `exact` prop to the misbehaving tab, but it seems to not had any effect.

**Comment by johnleider** [comment]
Is this bug actually on 3.1.9? Right now `v-tabs` are currently broken pending hotfix release today.

**Comment by MatthewAry** [comment]
@johnleider I just checked to make sure, this issue exists on 3.1.8 and to my memory existed before even that. The workaround is to make the default child route a redirect to a route with a path, which is not ideal. I implemented my workaround on my project on Feb. 16 2023 so it's been around at least since then.

**Comment by KaelWD** [comment]
Seems like a vue-router bug.

```js
const link = useLink({ to: { name: 'Home' } })
watch(() => link.isActive.value, console.log)
```

`'one'` updates, `'Home'` doesn't

**Comment by MatthewAry** [comment]
So... They removed the Exact prop in Router link.
See:
- https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link
- https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#nested-routes

Is VTabs using `isExactActive` when the `exact` prop is passed into the tab? This may really be a Vuetify Bug.

**Comment by MatthewAry** [comment]
Oh yeah, I updated my reproduction to show the states with `isExactActive` in some chips in the top right of the page.

**Comment by MatthewAry** [comment]
```
const link = useLink({ to: { name: 'Home' } })
watch(() => link.isExactActive.value, console.log)
```
Works

**Comment by MatthewAry** [comment]
@KaelWD I believe this has regressed.

**Comment by MatthewAry** [comment]
Actually, it might be a different issue. I'm seeing problems with non-exact path detection on tabs.

**Comment by MatthewAry** [comment]
Okay, NM. Turns out I still don't know everything I should about the router.

**Comment by johnleider** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/9064066/6077d559-14e8-4f8f-8872-a0e1eb796e2a)
