### ISSUE TITLE
[Bug Report][3.1.9] autocomplete menu dont appear in write position in rtl

### ISSUE THREAD

**Issue by mrkayo** [vuetifyjs/vuetify#16917]
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.2.13
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
click on autocomplete

### Expected Behavior
show menu

### Actual Behavior
dont show but appear on the second click

### Reproduction Link
[https://codepen.io/sasran/pen/qBMYmJW?editors=101](https://codepen.io/sasran/pen/qBMYmJW?editors=101)

**Comment by KaelWD** [comment]
Duplicate of #16628
