### ISSUE TITLE
[Documentation] Opening blueprints subfolder in features considerably slows down browser

### ISSUE THREAD

**Issue by tantonovics** [vuetifyjs/vuetify#16919]
### Environment

**Browsers:** Firefox 110.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Open link

### Expected Behavior
Page loads normally.

### Actual Behavior
Browser slows down considerably and is unable to fully load page.

### Reproduction Link
[https://vuetifyjs.com/en/features/blueprints/](https://vuetifyjs.com/en/features/blueprints/)

**Comment by MajesticPotatoe** [comment]
Issue related to v-tabs 
```
Maximum recursive updates exceeded in component <VSlideGroup>
```
https://play.vuetifyjs.com/#eNqVUEtuwyAQvYrF2kCrdFPLitITdJNdyALH09qN+Qiwoyry3QuYSK7zkbLjzWPeZ3Zn9KE1GXpABSodCN1xB2sms6wcMNc6PiNwvLIJXfB6y6vsU0JJJ3iD3Z7UI7YxsNhOaLIKYApR0lk4JlGOWqGVcVhwTX6skj7/OaywRFiGiixOwswXDJihxjltC0p7qY/f5KAE3XiOml66VgCuldisyIq8YN7phpM3WrfWzWkCVuDKqJMF440Zymcerv36veeTaC//St4n2TTCne8bdK/0qDcZwGADsgYD5mGHxd9bPRZfrroE65HJ0Z+3a+XRLi57sPGqu0vC50tGhbC+Dy5jjv6F9LZxEe3/AMyC2OA=
