### ISSUE TITLE
[Bug Report][3.1.8] VSelect appendInnerIcon is not defined in definition and website documentation

### ISSUE THREAD

**Issue by tokidoki11** [vuetifyjs/vuetify#16910]
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I'm writing storybook, I notice appendInnerIcon in VSelect on documentation is none to be seen.

Typescript typings is also not registering

### Expected Behavior
Typings should be there

### Actual Behavior
Typings is not available

### Reproduction Link
nothing

<img width="783" alt="image" src="https://user-images.githubusercontent.com/7564844/225185085-7ea05e68-967a-4eba-8401-92a175d347c8.png">

**Comment by yuwu9145** [comment]
Try `menuIcon` instead

**Comment by tokidoki11** [comment]
@yuwu9145 thanks!
while definition comes out there is no such documentation, please advice whether to close this ticket or not
