### ISSUE TITLE
[Feature Request] v-autocomplete and ENTER key select

### ISSUE THREAD

**Issue by lmunch** [vuetifyjs/vuetify#16921]
### Problem to solve
I have recently created a small app using Vuetify (I really like it by the way) and noticed that all my test users type the full item text in a v-autocomplete box and immediately press ENTER. Now they expect that to have the same effect as clicking the item, but instead the all items are shown and nothing is selected. I have tried several methods to get this behavior to no avail, maybe I am missing something?

I am currently using Vuetify version 3.1.8.

### Proposed solution
Select the item on ENTER key press, if an exact match is available (or only one item is left).

**Comment by DWmodem** [comment]
I, like your users, wish to use ENTER to select my v-autocomplete. 

My solution isn't perfect but it does allow you to select on enter with a v-autocomplete. Note that this particular example allows for multi-select, which is my use-case. 

The crux of this implementation is to select the correct item ourselves when we hear the @keyup.enter event.
```
<v-autocomplete
      ref="autocomplete"
      v-model="model"
      :search-input.sync="search"
      :items="items"
      multiple
      clearable
      hide-details
      hide-selected
      item-text="name"
      item-value="id"
      label="Select a item..."
      @keyup.enter="selectCurrent"
    ></v-autocomplete>
```

And the `selectCurrent` method:
```
    selectCurrent (event) {
      const currentText = this.search
      if (currentText && !this.model.includes(currentText)) {
        const foundIndex = this.items.findIndex((item) => {
          return item === parseInt(currentText, 10)
        })

        if (foundIndex !== -1 && !this.model.includes(this.items[foundIndex])) {
          this.model.push(this.items[foundIndex])
          this.search = ''
        }
      }
    },
```

**Comment by lmunch** [comment]
Thanks a lot for getting back to me. Just tried your suggestion and but this.search is not updated and is empty when  when "selectCurrent" is called. I have specified :search-input.sync="search". Any idea?

**Comment by lmunch** [comment]
v-model:search="search" instead of :search-input.sync="search" worked. Thanks for steering my in the right direction.
