### ISSUE TITLE
[Bug Report][3.1.10] Event update:focused missing from v-autocomplete, v-select, v-combobox

### ISSUE THREAD

**Issue by CarnivalBen** [vuetifyjs/vuetify#16926]
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Windows

### Steps to reproduce
Issue is clearly demonstrated in playground link. Clicking in and out of the `v-text-field`, `v-combobox`, `v-autocomplete`, or `v-select` shows that only the `v-text-field` fires the `@update:focused` event. The other controls do not.

### Expected Behavior
`v-autocomplete`, `v-select`, `v-combobox` should all fire the `@update:focused` event when the control looses focus, to match the same functionality as the `v-text-field`.

### Actual Behavior
The `@update:focused` event doesn't fire.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFVE1v2kAQ/SujvbiRsA1NpUoWoSFRc+0BeopzMPY4bGPvrnbXhBT5v3d2F4IDahX1Ei72fL1585jx/Y7NlUo2HbKMTS22qiksznIBMN3EhVL+1RttwcXeAjg8p+tLKJvCmKuctTaejHM2W+LWxnccmwpieJb6yUDNBU7T9eXspHoTW5dc++SD1/2uO1URkayWZWewIvTguHP2wtJbziA9ozOgNbuV7Uqu5JZIeBSoJBoRWQhIns6ASHlIH9KgqWWFDbXfFE3OhqGMk1pubP98G3sP+zPyQ+7zzkoipBq0+E7+xaDko0Y4m2OBDZb2nRMYn/zR8h/pT8DYlwbdZhf6kYvYSpXBZDxWW9ryux+3PxewWM6X3zO/P2uuwPDfLn8bN1ThVjQrZSM1uTwX3xu+QfSoEUUEGUQaq4jQdrsgUcjo+2kaEGck0uSEqou9HqMzwplO08H5kmlKzZUFg7ZzYd4qqS3sQGMNPdRathDR3UcuuZTCWCCR4crFP+VsieSY5+ziEPQ678P3O8ttgxkc80auuvOu+ZzsfgQnSTdvkm5uyIb+4RV/MH5oUheNQQrnou5EabkU+705/o2f8AJ2ToVjceI7EIQ/glz0Xos0iEEysBELSpCEKvllpKAPn8egVfIBWqYsoDofKeTsnK2tVSZL006op8eELi29pliqO2F5i3El2+vL5HPy5WtacWOH/gRNG6+0fDaoqSPJMAC3vH75W4N9mHAnyWQccPc+WrCVccBngCl12aCONYoKNep/sj/JfTPBSexsCteT1O1J0YaLJ3MiZmm8kPcHav8xnodw9Q+uTT9igR41DCXs4Q+nJB2Q)

**Comment by yuwu9145** [comment]
Would be resolved by [#16852](https://github.com/vuetifyjs/vuetify/pull/16852)

**Comment by johnleider** [comment]
closed by #16852
