### ISSUE TITLE
[Bug Report][3.1.9] VTabs: Maximum recursive updates exceeded in component <VSlideGroup>

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#16920]
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create v-tabs, experience recursion.

### Expected Behavior
v-tabs w/o recursion

### Actual Behavior
v-tabs + recursion 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUEtuwyAQvYrF2kCrdFPLitITdJNdyALH09qN+Qiwoyry3QuYSK7zkbLjzWPeZ3Zn9KE1GXpABSodCN1xB2sms6wcMNc6PiNwvLIJXfB6y6vsU0JJJ3iD3Z7UI7YxsNhOaLIKYApR0lk4JlGOWqGVcVhwTX6skj7/OaywRFiGiixOwswXDJihxjltC0p7qY/f5KAE3XiOml66VgCuldisyIq8YN7phpM3WrfWzWkCVuDKqJMF440Zymcerv36veeTaC//St4n2TTCne8bdK/0qDcZwGADsgYD5mGHxd9bPRZfrroE65HJ0Z+3a+XRLi57sPGqu0vC50tGhbC+Dy5jjv6F9LZxEe3/AMyC2OA=)

### Other comments
Works in 3.1.8, possible cause #16775
Few doc pages are broken as a result (wont load, lock up browser):
[https://vuetifyjs.com/en/components/tabs/](https://vuetifyjs.com/en/components/tabs/)
[https://vuetifyjs.com/en/features/blueprints/](https://vuetifyjs.com/en/features/blueprints/)

**Comment by nekosaur** [comment]
Not sure what the exact underlying cause is, but moving the `defaults` value in VTabs to a computed seems to "solve" it.

**Comment by johnleider** [comment]
It's being caused by this:

![image](https://user-images.githubusercontent.com/9064066/225365358-0ba25f66-91ca-4b8a-88a7-89321b9d39f1.png)

Still investigating why though.

**Comment by johnleider** [comment]
The fix I've deployed is a temporary revert until we can identify the core issue.

**Comment by qxygene** [comment]
i fixed this issue by adding value on it.     

```
<v-tab
      value="1"
    >
     tab 1
    </v-tab>
```
