### ISSUE TITLE
[Enhancement] v-alert warning text contrast

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1693]
### Steps to reproduce
`v-alert` with `warning` prop has white text on orange background which is not super easy to read. 
I guess this is in the material design but MD states that legibility needs to have a contrast ratio of higher than 3 but it [fails](http://leaverou.github.io/contrast-ratio/#white-on-rgb%28255%2C%20193%2C%207%29)

### Versions
0.15.5

### What is expected ?
readable text with proper contrast

### What is actually happening ?
poorly readable text on v-alert as warning

### Reproduction Link
https://vuetifyjs.com/components/alerts

**Comment by johnleider** [comment]
Was working on this and this yellow darken-2 seemed like the best fit. I'm not sure how to test the proper contrast ratio.

![image](https://user-images.githubusercontent.com/9064066/30404691-d6fe61f0-98b5-11e7-9b21-6fe45df7e0ef.png)
