### ISSUE TITLE
[Bug Report][2.6] v-label cannot apply opacity class

### ISSUE THREAD

**Issue by duongxinh2003** [vuetifyjs/vuetify#16938]
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I cannot use class for v-label with text inside 2 tags
```
<v-label
    clickable
    class="text-high-emphasis text-red"
>
    Can not change opacity and text red
</v-label>
```
### Expected Behavior
Apply class for text

### Actual Behavior
Cannot use class

### Reproduction Link
[https://codepen.io/duongxinh2003/pen/yLxEqjZ](https://codepen.io/duongxinh2003/pen/yLxEqjZ)

**Comment by KaelWD** [comment]
This already works in v3
