### ISSUE TITLE
[Bug Report] v-datatable click:row event should not fire event when selecting the default checkbox(v-datatable set show-select prop)

### ISSUE THREAD

**Issue by XieWeiJie** [vuetifyjs/vuetify#16936]
### Problem to solve
```
 <v-data-table
      show-select
      :modelValue="selected"
      @update:modelValue="onSelectedChange"
      @click:row="onRowClick"
    >
...
<script setup>
const selected=ref([...])
function onSelectedChange(args){
   selected.value = args
}
function onRowClick(e, { item }){
   const currentRowReactive = item.value
   selected.value = []
   selected.value.push(currentRowReactive)
}
</script>
```
I set the show select property in the v-data table component, and the component will render a check box by default.
My requirement is that when the mouse clicks on a check box, the table supports multiple selections. When clicking on an area other than the check box, only that piece of data is selected, and other selected rows are deselected

### Proposed solution
Because only clicking the check box will trigger the click: row event, I cannot meet this requirement.

**Comment by davidstackio** [comment]
I'm having this same issue too. This might be a bug report, rather than a feature request since `v-data-table` is still in labs.
