### ISSUE TITLE
[Bug Report][3.1.10] v-tabs doesn't show scroll arrows

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16943]
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-tabs with many tabs to have a wide width. Change your browser viewport (preview iframe) size to step over 1280px width.

### Expected Behavior
The arrows supposed to appear when it doesn't fit the screen

### Actual Behavior
The arrows 'randomly' appear only when the screen width is over 1280px

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUslu2zAU/JUHXpwAphQ3BQq4SpEeey96CXOQJdpmLS4gKTWBoH/v4xJZsdEcqoOkt85wOE8jGXruxf61+O3IlghptPUwQmN57fmvVIMJ9lZLWOXeFVNM8ZfY2mjlPOQCPLwfvBmZAvBHLvkW4j9Ay/d13/mfKblqa3tarUNpwvd0+5UpsibfjSlwJzKqXGOF8d9CR4bMG+aFta/h5vYtBLDc91adY2RQ7xBKGy+0opsEF54p/QTkGFTljFZ5Lk2HRwnIVSsGEO0DI7UxjIQU89VAMYrEmI8hwrgz6O5AG91pi1NCteKgGTkXUT5PBYqHVdkKWlur/1ArDkdPd7pr8fVCde87ofhyzlg+XM91fP/RWOSYnsTyHAMMdJ84glBwf7cEA9ie+GuoLbOLbQA/UCYYRxAwZTEjShlh5s4cO0ygUBgk4aoSdY3fhdgYpksAh/eY2uZbQWski1JZG7SsVmiReNFIMhYcI7PVWDB3iBk5em/ctix7ZU6HotGyfMRaaXvlheS01fLxvvhUfP6ClJxf5gvuJN2hyo5bRGQkuycuDyb/F0Au495NsblLe3OOdihGWHy1sESUgVtquWq55fZD9he9705wUbs6RXb8hIqiWU7uQszGRSGf3qj9x/HiijD/HGCmNUn0EDCNkOe/Gkdx+Q==)

### Other comments
Despite the arrows dont appear properly, the tabs can be scrolled, but only with a touch event.

**Comment by santiagoaloi** [comment]
You missing the `show-arrows` props in `VTabs`

```html
<v-tabs show-arrows>
  <v-tab>
   ...
  </v-tab>
</v-tabs>
```

**Comment by kappaflow** [comment]
@santiagoaloi but why even when `show-arrows` is not set, the arrows still appear when the screen width is over 1280px? Are you sure it is an intended behavior?
