### ISSUE TITLE
Snackbar text getting clipped

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1694]
### Steps to reproduce
Go to codepen below and press the "show snackbar" button

### Versions
0.15.5

### What is expected ?
snackbar size adjusts to text

### What is actually happening ?
text is getting clipped by snackbar

### Reproduction Link
https://codepen.io/anon/pen/eGOaXb?editors=1010

**Comment by johnleider** [comment]
So the height is actually part of spec, but what I've done to help this, was not lock **multi-line** and **vertical** to mobile only. Using either of these props should help alleviate your issue.  Keep in mind, the maximum specced height of a snackbar is 112px. If you need something that has no specified height, you'll need to add some custom css.
