### ISSUE TITLE
VTextField icon callback isn't working as expected

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#1695]
### Steps to reproduce
Create a v-text-field with append or prepend icon and a callback

### Versions
0.15.5

### What is expected ?
the callback must do its job. For example, hide/show password.

### What is actually happening ?
Text field content is removed, or sometimes just nothing happens.

I'm unsure, but it seems the `genIcon` method in Input mixin is the reason, since 0.15.3
Here the 0.15.2 version: https://github.com/vuetifyjs/vuetify/blob/v0.15.2/src/mixins/input.js#L114
Here the 0.15.3 version: https://github.com/vuetifyjs/vuetify/blob/v0.15.3/src/mixins/input.js#L133

### Reproduction Link
https://vuetifyjs.com/components/text-fields (check section #10)
https://jsfiddle.net/64L6ozjv/1/

**Comment by vipin-pink** [comment]
Well the issue is more than this. Normal editing of text even does not work if you write something in text box it reverts back to original text. 

Example: 
- https://vuetifyjs.com/components/text-fields (try writing something in a input field and see things blow up)

**Comment by tafel** [comment]
I tried this code and icon callbacks remove content from the input field. But the last one, just a simple field, is working as expected. For this last particular case, it seems the doc has a bug. Maybe it's due to the lack of v-model in the examples.

    <v-app id="app">
      <p>field with icon and callback</p>
      <v-text-field 
        name="test" 
        v-model="password"
        :append-icon="e1 ? 'visibility' : 'visibility_off'"
        :append-icon-cb="() => (e1 = !e1)"
        :type="e1 ? 'password' : 'text'"></v-text-field>

      <p>field with icon, but without callback</p>
      <v-text-field 
        name="test" 
        v-model="password2"
        append-icon="visibility"></v-text-field>

      <p>just a field</p>
      <v-text-field 
        name="test" 
        v-model="password3"></v-text-field>
    </v-app>

    new Vue({
      el: '#app',
      data: {
        e1: false,
        password: 'test',
        password2: 'test2',
        password3: 'test3'
      }
    })

    Vue.use(Vuetify);

**Comment by raulcsj** [comment]
Try to resolve this bug like me
Edit src/components/VTextField/VTextField.vue
at line 199
inputAppendCallback () {
    // this.inputValue = null
    this.$nextTick(() => this.$refs.input.focus())
    return true
 }
