### ISSUE TITLE
[Bug Report][3.1.10] SlotProps aren't unwrapping when used in the template

### ISSUE THREAD

**Issue by craigrileyuk** [vuetifyjs/vuetify#16950]
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
- Create a standard Vuetify application
- Try to use component slotProps as in the reproduction

### Expected Behavior
SlotProps should be automatically unwrapped in the template

### Actual Behavior
Users must access slotProps using a .value property when using them inside Javascript statements.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU01v2zAM/SusdvAGRPa6DRhgpFt3GfYDBuxQ9+BaTKJFX5Bkd0Pg/z5KTtPYRQt0N/NRfI98pG8O7Jtz5dAjq9k6onaqjfilMQDrgbfO5c8c6FaaY5TjiH8i30hUAihpBaqrhumwbdjpFUATT6Twxnl0aASXxqCnxweQ4bvt+oACxllZlrjgHH7uZIB76/eB82V+4LKzZg4C1Akk8iUOj2Ll0Koe4SsUWkjedp3tTSygnsW89d7ecy+3u1gsyZb01bO9C4vBFDHP8NoRHt15TasvtrauZjueoPNdPuybwNPCUzCdwqycwtB56SIEjH1KS+2sj3AAjxsYYeOthoJui/xrDM0UItCBwFXKvy1+oFIWflmvxEXxLpFPdETEVmzioiZc+TtYQ+d5SL2QKzkRGlZDRhJGGilu2C5GF+qq6o3bb8vO6uqacpUnl6RGLqy+/lh+KD99roQM8RwvMWh+Rz4G9KTYsNUZeZSbv88JHNPEe1levp94jxhX7V1IxE8IK1IZ0HNP/wN69C92v3g7m2CRezJF0hwbM5KjSpp9WJjZhWzkzUNr/zFepkj1t0lmXLGpPRKcStjtP1joWig=)

**Comment by KaelWD** [comment]
https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates

Refs in slot props are not automatically unwrapped. Automatic ref unwrapping was a mistake from the beginning anyway.

**Comment by craigrileyuk** [comment]
So now you're going to have a situation where

```html
<v-text-field>
  <template #prepend-inner="{ isFocused }">
    {{ isFocused }}
  </template>
</v-text-field>
 ```

outputs "true" or "false" onto the template whereas

```html
<v-text-field>
  <template #prepend-inner="{ isFocused }">
    {{ isFocused === true }}
  </template>
</v-text-field>
 ```

will always output false because it's evaluating against the Ref<boolean> rather than the Boolean. 

Seems like a pretty odd intention to have the exact same variable behave completely differently depending on a small adjustment in context of use within the same <template> block.

**Comment by jacekkarczmarczyk** [comment]
That's how vue deals with non-top-level refs:

https://sfc.vuejs.org/#eNp1kM2OwjAMhF/FyoVdaUm01ypF2vfIpVu5UER+FDtwiPLuOBTBiVtmPP6UcVV/KelrQTUoS3NeEwMhl3RwYfUpZoYKGRdosOToYSfRnQsuzDGQROeYEEbJXKdLwaFHvzgX/IbmgjUbUVgiGH26TIyiAOzp91Drtq8fu9CaNeJ+mI7jCB38jlnzIqoftX1276ekzxSD1Kmd5J4DcmqAh9M9KdG1UyfmRIMxtMz9CGfSMR+NvHQugVePGsnv/3O8EWYBO9URUq2pdgeGUGzH
