### ISSUE TITLE
[Feature Request] How to make the element have variant="underlined" attribute by default?

### ISSUE THREAD

**Issue by snoopy83101** [vuetifyjs/vuetify#16964]
### Problem to solve
How to make the element have variant="underlined" attribute by default?
for example:
     v-autocomplete
The default is <v-autocomplete ref="query" variant="underlined"

### Proposed solution
Where can it be configured?

**Comment by websitevirtuoso** [comment]
Like this

```
export default createVuetify({
  components: {
    ...components,
    ...labs,
  },
  directives,
  icons: {
    defaultSet: 'mdi',
    aliases,
    sets: {
      mdi,
    },
  },
  defaults: {
    VInput: {
      variant: 'underlined',
    },
    VTextField: {
      variant: 'underlined',
    },
    .....
```

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by snoopy83101** [comment]
> https://next.vuetifyjs.com/en/features/global-configuration/ Like this
> 
> ```
> export default createVuetify({
>   components: {
>     ...components,
>     ...labs,
>   },
>   directives,
>   icons: {
>     defaultSet: 'mdi',
>     aliases,
>     sets: {
>       mdi,
>     },
>   },
>   defaults: {
>     VInput: {
>       variant: 'underlined',
>     },
>     VTextField: {
>       variant: 'underlined',
>     },
>     .....
> ```
Thank you so much for your help, I overlooked this, thanks
