### ISSUE TITLE
[Bug Report][3.1.10] VAutocomplete : input loses focus on keyboard navigation

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#16968]
### Environment
**Vuetify Version:** 3.1.10
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Focus an VAutocomplete, type to search, navigate with arrows

### Expected Behavior
The input to not loses focus and search query to be visible.

### Actual Behavior
The input loses focus and search query is not visible.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdkMtOwzAQRX/FeBOQEptSVlFalR1/wKLuIk2mrWn8kO0UoSr/zjhJUR/Agp1n7sy5c7080hdr2aEFmtMigLJNGWAuNCHFISut7Z99oUqpx2oQ22AqgwsQgOQSd/1M0OUkJU8rQecFvxw5gbD9Tepneo+Cn3lj6SsnbSAeQhtlqaxxgRyJgw3pyMYZRRI8OonDldE+EOW3ZBb1++QVmsaQN+Oa+i55iPABhyCa0oGFR1j27o3G3Md4ixgFL2hO+k7soUesBd2FYH3OeavtfsswFF+gxl2rg1SQ1UYtpmzKHrOysbuSPfNa+nAuM/AqWzvz4cGhsaDpmUeQm8/ffEYZ8RM2eRy4Yy9ryrWP4BsgR5cDuMyBrsGB+zPE1exPQa5GbsJE607oDv+3kXrvr7628v23Lk8X/iNlj4j7q2jTpfTiSvQdNunqCyGj8Ns=)

**Comment by ThomasKientz** [comment]
Maybe a duplicate of https://github.com/vuetifyjs/vuetify/issues/16926

**Comment by johnleider** [comment]
resolved in the latest version:

https://play.vuetifyjs.com/#eNqlUEtuwjAQvYrrDa2U2AW6igKiu96gC8IiJAO4xB/ZTqoK5e4dO6HiU3XTnWfe8/vM+kRfjWFdCzSjuQdpmtLDslCE5F1aGhOfcZClUOM0gK3XlcYP4IFkAv+6RUHX04TMNgVd5vyachbC9Y9S5ESPnF944+gqK4wnDnwbYCGNtp6ciIUd6cnOakkmGHoSyJVWzhPp9mQR8MfJGzSNJu/aNvXD5CmID3IoRBM6aGEIwz6cVtj7FLIUI+AKmpG4CTv0CHNBD94bl3HeKnPcMyzFV4hx2yovJKS1lqs5m7PntGzMoWQvvBbOX8IMnEy3Vn86sGhc0OTCw4vd17VPVStk1dCIzjIFnisj+chEpxmbDg7jKm3KrQsWd9Ic/TqwqQVVgwX7Z50b7m+Vbih3tYJ1X6geL90IdXQ3R65cPPD6nPBffaNYUNoEwz6hV3kxQfxIN99NnfiU
