### ISSUE TITLE
[Documentation] Broken links to components on the components all page

### ISSUE THREAD

**Issue by Yeeons** [vuetifyjs/vuetify#16967]
### Environment

**Browsers:** Firefox 111.0
**OS:** Windows 10

### Steps to reproduce
1. go to https://vuetifyjs.com/en/components/all/
2. Click on:
a. custom overlays
b. comboboxes
c. radios
d. custom inputs
f. button toggles
g. data tables (currently has the wrong link? should be https://vuetifyjs.com/en/components/data-tables/basics/ ?)
h. server side data tables
i. virtual data tables
j. virtual scrollers (seems to be missing content)
k. defaults provider

### Expected Behavior
These links should go to their correct components page.

### Actual Behavior
Most links go to a 404 page with a couple going to a https://vuetifyjs.com/en/labs/introduction/

### Reproduction Link
[https://vuetifyjs.com/en/components/all/](https://vuetifyjs.com/en/components/all/)

### Other comments
Most of these just have naming issues that are pointing incorrectly. Fixing the naming will fix the broken links. However there seems like a couple of pages are with in subfolders which may affect how Listitem.vue works and there seems to be some weird redirects that go to https://vuetifyjs.com/en/labs/introduction/. I can't see the logic on how this is happening.

**Comment by MajesticPotatoe** [comment]
Easy fixes. mostly just naming issues that will fix the 404's. The redirects to labs/introduction is intentional. (they will eventually go to the correct pages when they are released from labs).

**Comment by Yeeons** [comment]
The Data-tables related content all seem to be in a subfolder 
`vuetify\packages\docs\src\pages\en\components\data-tables`
Moving them into components would help fix their links with some renaming.

**Comment by MajesticPotatoe** [comment]
That will happen when they are released from labs. For now they will stay in labs, and the forwarding to labs/introduction will remain as intended.
