### ISSUE TITLE
UX issue with v-select and autocomplete

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#1696]
Not sure if you want to class this as a bug or a feature request. I could argue either.

### Description
There is a usability issue with the v-select when using autocomplete. It works perfectly the first time when there is no value selected by default. The issue is found when trying to select a different value after the initial value is selected. 

What happens is that v-select uses the current selected value as the filter when displaying the list the second time. This often means that only one value is in the filtered list due to autocomplete being applied. The user must use the keyboard to change the filter such that other values are displayed or delete the current value completely so that all values are displayed. This prevents mouse only operations.

### Proposal
Only apply the autocomplete filter when a key is pressed. When opening the list, always display the full list, ideally with the current selected value indicated as such and visible in the viewport.

This covers the initial selection when there was no initial value selected. The user can use the mouse or keyboard or combination to filter then select the initial value. 

Once the user clicks on the select again to select a different value, the full list is displayed with the current value selected in the input (as is current behaviour) so that keys can be pressed immediately. No filtering is applied at this point because no key has been pressed, the full list is displayed with the current selected value visible. This allows for pure mouse operations to select a new value. It also allows other values to be displayed (visual context) to allow the user to select a different value. The user may choose to use only the mouse to scroll and select or change the current value via the keyboard to run the first filter operation on the full list.

- What will it allow you to do that you can't do today?
Use the mouse to select a new value without the use of the keyboard.

- How will it make current work-arounds straightforward?
No current workaround. The user must use the keyboard to select a different value because of filtering being applied.

- What potential bugs and edge cases does it help to avoid?
Usability and visual context is the issue.

As a bug:
### Steps to reproduce
Create a list with multiple entries and enable autocomplete.

1. Select a value from the list.
2. Take focus away from the select
3. Click the list again and try to select a different value without using the keyboard

### Versions
```
    "vee-validate": "^2.0.0-rc.14",
    "vue": "^2.4.2",
    "vue-class-component": "^5.0.2",
    "vue-router": "^2.7.0",
    "vuetify": "^0.15.2",
    "vuex": "^2.3.1",
    "vuex-persistedstate": "^2.0.0"
```

### What is expected ?
The user should be able to select a different value from v-select without being forced to use the keyboard.

### What is actually happening ?
The v-select uses the currently selected value as the filter for the list when the list is displayed. In order to select a value, the user has to use the keyboard to change the filter to allow other options to be available.

### Reproduction Link
https://codepen.io/anon/pen/PJooNJ

**Comment by johnleider** [comment]
Autocomplete functionality is derived from https://material.angularjs.org/latest/demo/autocomplete
Hopefully this can give you some insight as to why some things are the way they are.
