### ISSUE TITLE
[Feature Request] Organize component props and slots as TypeScript interfaces (like Quasar)

### ISSUE THREAD

**Issue by 0x00A1FA** [vuetifyjs/vuetify#16969]
### Problem to solve
Hi,

Whenever I try to understand the source code of components, I obviously Ctrl + Click the prop I want to learn about.

Right now, the component type defs are all over the place and really hard to grasp.

Quasar neatly organizez the props and slots and even comments various component props, basically giving the user a premium IDE experience that helps in learning the components without going to the docs. Yes, I know Quasar is all over the place, but this is one thing they do right.

### Proposed solution
Use TypeScript interfaces to define Vuetify component props and slots (e.g. see `dist/types/index.d.ts` at https://www.npmjs.com/package/quasar?activeTab=code).

**Comment by KaelWD** [comment]
Quasar is written in javascript with separate types which is why they're readable, ours are generated from typescript source. I'd add declaration maps so you ctrl+click to the source .tsx files but it's not supported by rollup-plugin-dts: https://github.com/Swatinem/rollup-plugin-dts/issues/113
