### ISSUE TITLE
How to create radio group with image for each radio ?

### ISSUE THREAD

**Issue by prakashgp** [vuetifyjs/vuetify#1697]
![screenshot](https://user-images.githubusercontent.com/3513506/30327240-f37ebcc6-97e8-11e7-8e7e-888242244639.png)
I want to achieve above functionality, but i've tried with radio group, but it gives lot of space between image and radio. 
in above image i've seperated radio groups and image as seperate sibling tags, so it looks as expected, but doesn't work as expected because i haven't grouped them together under `v-radio-group`

This is the result i get when i try to include image, inside `v-radio-group`
![screenshot2](https://user-images.githubusercontent.com/3513506/30327384-7309a514-97e9-11e7-85f2-5568a8e53b05.png)

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
