### ISSUE TITLE
[Bug Report][3.1.11] v-text-field type email, when paste conted lead to error

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#16976]
### Environment
**Vuetify Version:** 3.1.11
**Last working version:** 3.1.9
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Open console log
2. Paste something in email
3. Check error in console

VTextField.tsx:148 Uncaught (in promise) DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.
    at https://unpkg.com/vuetify@3.1.11/dist/vuetify-labs.esm.js:6173:27

### Expected Behavior
without error

### Actual Behavior
show error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUUtuwjAQvYrrDa1E7CK6QlDRXW/QBWERkgm4+FfboUUod+84CVII0EWzysybeZ/x6kTfrGWHCuiMzgMoK7MAr6kmZH5IMmub36ZQmdBd1X7YC/ATklKALPoAITLbgFykFHBJpvQSDEcL9zAHX5VwMKArspChlg+4Js1WaHZjmZ+t8p7XWLQp5ryXDkufO2ED8RCqCAtljQvkhA5KUpPSGUVGeJZRHM6N9oEovyWLiD+O3kFKQz6Mk8XD6CmSt3RIRMe05UITln16o/Gyp+gl7QCf0hlpOrGHGrFO6S4E62ecV9rutyw3ii8R467SQShICqOWUzZlz0km7S5jL7wQPvRhBl4lG2e+PTgUTum4pxFEebyn08FIP2GTScvb9RJ8SR+Jrwg5qhzAJQ50AQ7cnyEGs7eCDEauwkTpOtU13lcKvfeD0+a+Oevq7PAfKRuKuL+OMvWYXrhE3XaTrn8BbxkG7A==)

**Comment by websitevirtuoso** [comment]
Another issue. Appeared class clickable in v-data-table tag "tr"
![image](https://user-images.githubusercontent.com/5112918/226813776-b55a2cc3-3049-4945-ab52-b1e91f92050c.png)

As a result all my tables on hover cursor changes to pointer.
This is also bug.

**Comment by Yves852** [comment]
Same error when v-text-field has the type `number`.

> Uncaught (in promise) DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

No error on types `text` and `password`.

**Comment by QozbroQqn** [comment]
for all the people who hates error messages, can't ignore them and don't want to wait for a bugfix can edit the file `node_modules/vuetify/lib/components/VTextField/VTextField.mjs` and replace the function "onInput" Line 103 with this:
```
// taken from KaelWD's commit:
    function onInput(e) {
      const el = e.target;
      model.value = el.value;
      if (['text', 'search', 'password', 'tel', 'url'].includes(props.type)) {
        const caretPosition = [el.selectionStart, el.selectionEnd]
        nextTick(() => {
          el.selectionStart = caretPosition[0]
          el.selectionEnd = caretPosition[1]
        })
      }
    }
```
