### ISSUE TITLE
[Documentation] Missing descriptions in tabs api page

### ISSUE THREAD

**Issue by Yeeons** [vuetifyjs/vuetify#16986]
### Environment

**Browsers:** Firefox 111.0
**OS:** Windows 10

### Steps to reproduce
1. go to https://vuetifyjs.com/en/api/v-tab/
2. search for 'MISSING DESCRIPTION' should appear for:
a. direction
b. fixed
c. hide-slider
d. slider-color

### Expected Behavior
Should so information on that api

### Actual Behavior
only shows missing description

### Reproduction Link
[https://vuetifyjs.com/en/api/v-tab/](https://vuetifyjs.com/en/api/v-tab/)

### Other comments
Recommend changing to:
```
fixed
Forces component to take up all available space up to their maximum width (300px), and centers it.

hide-slider
Hides the active tab slider component (no exit or enter animation).

slider-color
Applies specified color to the slider when active on that component - supports utility colors (for example success or purple) or css color (for example success or purple) or css color (#033 or rgba(255, 0, 0, 0.5)). Find a list of built-in classes on the [colors page](/styles/colors#material-colors). 
```

direction
Should this be removed as this seems like its handled under tabs? doesn't currently do anything.

**Comment by MajesticPotatoe** [comment]
duplicate #13573 - feel free to submit a PR with changes
https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/v-tab.json
