### ISSUE TITLE
[Bug Report][3.1.11] v-menu min-width property does not work

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#16987]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Click on the button to open the menu

### Expected Behavior
The menu should have 500px width because it has min-width="500"

### Actual Behavior
min-width property is not respected

### Reproduction Link
[https://codepen.io/kasheftin/pen/dyqQgJV?editors=1010](https://codepen.io/kasheftin/pen/dyqQgJV?editors=1010)

**Comment by sadiolem** [comment]
There is a merging of styles inside VOverlay.tsx:

```
style={[
  dimensionStyles.value,
  contentStyles.value,
]}
```
contentStyles minWidth overrides dimensionStyles minWidth value

and contentStyles gets styles from here locationStrategies.ts:

`minWidth: convertToUnit(axis === 'y' ? Math.min(minWidth.value, targetBox.width) : minWidth.value)`

so **if targetBox width is less than minWidth prop value** from VMenu, then **the value of targetBox is taken**

need to know what that condition `axis === 'y'` is for and why priority is given to targetBox in that case

**Comment by sadiolem** [comment]
@KaelWD Hi! Any thoughts?

**Comment by kevmul** [comment]
This appears to still be a problem. The repo link above still doesn't show the min-width being honored. The `width` property works just fine.
