### ISSUE TITLE
[Bug Report][3.1.11] Vuetify forces scroll to be displayed even if there is nothing to scroll on the page

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16994]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add Vuetify framework to your project

### Expected Behavior
Vertical scrollbar should be visible only if scrolling is possible `overflow-y: auto;`

### Actual Behavior
The scrollbar is always visible: `overflow-y: scroll;`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUU1PwzAM/StRLtuktdEACWl0aPwHxGXZIWs9VtakUZIWpqn/HSfNyj4EBy6t7We/5+esjrRtwJXbQ/ph6ZyWUtfGkSPJDQgHbz1GOrI1tSSj2Dviiiv4Cq15rawjESCLy8HxkStC3A4kzEmICSlgK5rKvfbFUSHMfjT1UIffbvLEFZ3SF61T5MSNMpubUrtn3xElI8NAKJwg48kpJcSAa4z6ybs+8PwhydjAmVl3qMAHbIgcSF2hBy+ZFWVLymLBqdCaU1/iLmsTzDDGkJ3ijGFr+J/No5P+ookUGi9cK3QU9uIRsJwOl+H+LXzO6c45beeMNUrv39O8lmyJGDONcqWEpKjl8j69Sx8eUdW683oKViYbU39aMKjIaXAdyf2b/CYQYeSdpbNZzxtrSSU21hPfEDJUacEkBlQBBsyf21/1Xji4wm5cxKfr8KJVqfb26pi5DYdcnVb7h71A4efXXqab0n49FOxH6Pob63kRIw==)

### Other comments
It seems like it comes from v2.0.4 [ress.css](https://github.com/filipelinhares/ress/blob/9e5b5e07494f572c32c3c86e78bf85061093e7e5/ress.css#L11).
Based on the css from Vuetify:
```
/*!
 * ress.css • v2.0.4
 * MIT License
 * github.com/filipelinhares/ress
 */
/* # =================================================================
   # Global selectors
   # ================================================================= */
html {
  box-sizing: border-box;
  overflow-y: scroll; /* All browsers without overlaying scrollbars */
  -webkit-text-size-adjust: 100%; /* Prevent adjustments of font size after orientation changes in iOS */
  word-break: normal;
  -moz-tab-size: 4;
  -o-tab-size: 4;
     tab-size: 4;
}
```
The last version is [v5.0.2](https://github.com/filipelinhares/ress/blob/master/ress.css#L7).
But actually both of them don't have `overflow-y: scroll;`

It was added by https://github.com/vuetifyjs/vuetify/commit/666360731830dc142b63a0b73f651bbece71e02e#comments and someone even asked there why it was added.

#16944

**Comment by itancc** [comment]
Any follow-up conclusions please?

**Comment by KaelWD** [comment]
There are no plans to change this.

**Comment by kappaflow** [comment]
But why was it add to begin with though?

**Comment by johnleider** [comment]
> But why was it add to begin with though?

To remove layout shift when any overlay, dialog, etc is shown.

**Comment by TeslaLyon** [comment]
Excuse me, have you found a better solution?
@johnleider @itancc @KazimirPodolski

**Comment by KazimirPodolski** [comment]
@TeslaLyon 
src/assets/global.css:
```css
/* https://github.com/vuetifyjs/vuetify/issues/16994 */
html {
    overflow-y: auto;
}
```

**Comment by andyfehrenbach** [comment]
> > But why was it add to begin with though?
> 
> To remove layout shift when any overlay, dialog, etc is shown.

Isn't this the purpose of the overscroll-behavior property? https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

**Comment by johnleider** [comment]
> > > But why was it add to begin with though?
> > 
> > 
> > To remove layout shift when any overlay, dialog, etc is shown.
> 
> Isn't this the purpose of the overscroll-behavior property? [developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)

This didn't exist until pretty recently right?
