### ISSUE TITLE
[Feature Request][3.3.x] v-data-table has no way to add styles/classes to items or cells.

### ISSUE THREAD

**Issue by dennis-damico** [vuetifyjs/vuetify#16991]
### Problem to solve
As far as I can tell, without using slots and re-writing all the tr/td elements, there is no way to add custom styling to rows or cells. 

For example, if someone wanted to make font red in all cells that contained a negative value. Or highlight entire table rows depending on some value in the item.

### Proposed solution
v-data-table [2] had the `item-class` prop, which atleast solves the issue of row styling. I think allowing column headers to support classes would help, but ultimately being able to generate cell classes based on cell information (maybe the headers can support a function that takes the cell value and returns a class/style to the td?) would allow for the most flexibility.

**Comment by webdevnerdstuff** [comment]
There is a slight work around to this, it's not great because it piggy backs off another prop, but it does work. The important part is the space before your class name.

With the align value:
```
headers: [{
	align: 'center your-class',
	key: 'id',
	title: 'ID',
}]
```
Without the align value, instead using just your class.
```
headers: [{
	align: ' your-class',
	key: 'id',
	title: 'ID',
}]
```

**Comment by dennis-damico** [comment]
Good suggestion! I imagine they'll eventually implement, but this seems like a reasonable work around for now.

**Comment by z0mt3c** [comment]
Did anyone find a reasonable workaround to add classes to the row based on the item? (like item-class in v2)

**Comment by Dgbsoft** [comment]
The item-class prop is really missing in data-table v3, to create styles on the entire line, the alternative is to manipulate each tr > td through the #item slot, which becomes unfeasible in a table with a lot of data.
It is very important that this same function is developed in v3.

**Comment by bornakke** [comment]
We are missing this feature too. Seem like a bad idea to manipulate each tr and td for such a small change.

**Comment by z0mt3c** [comment]
My temporary workaround - not great but it works for me:

`<template>
  <component :is='tag' v-bind='$attrs'>
    <template v-for="(_, slot) of $slots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
    <template #item='{props}'>
      <v-data-table-row v-bind="props" :class='itemClass ? itemClass(props.item.raw) : undefined'>
        <template v-for="(_, slot) of $slots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
      </v-data-table-row>
    </template>
  </component>
</template>

<script setup lang='ts'>
defineProps<{ tag: string, itemClass: (item: any) => string | object | string[] }>()
</script>`

Usage `<table-wrapper tag='v-data-table' :item-class="backgroundColorForItem" ...>` or with v-data-table-server like before.

**Comment by bornakke** [comment]
Great :)

**Comment by dixhuit** [comment]
My migration to Vuetify 3 (and thus Vue 2 to Vue 3) has now stalled because `item-class` is missing from `v-data-table`. Is there an ETA for this functionality being added back in? Is there anything I can do to help with progress here?

**Comment by sandeepkrishnams** [comment]
Now you can use cellProps and HeaderProp args to pass the classes and styles 
```
  const headers = [
    {
      title: 'Designation',
      key: 'designations',
      value: 'designations.title',
      sortable: false,
      cellProps: {
        style: 'text-transform: capitalize',
      },
    },
    {
      title: 'Department',
      value: 'departments.name',
      sortable: false,
    },
    { title: 'Created on', value: 'requestDate', sortable: false },
    { title: 'Status', value: 'status', sortable: false },
    {
      title: 'Actions',
      value: 'actions',
      sortable: false,
      width: '200px',
    },
  ]
  ```
  And you can pass this to data table as headerProps also you can also use cellProps args direclty to give the props to all the cells in the table.

**Comment by albadedan** [comment]
This comment is mostly for my future self, because I know I am going to forget how to do this. It's not that different to Vuetify 2, but it is poorly documented.

To set a style on a whole row programmatically, (for example when user clicks on a row):
```vue
<template>
  <v-data-table
    :headers="headers"
    :items="items"
    :search="search"
    :row-props="rowProps"
    @click:row="pushSelected"
    :items-per-page="14">
  </v-data-table>
</template>
```

Then, in methods (options api):
```js
pushSelected(event, { item }) {
  this.selected = item.id;
  this.$emit("selection", item);
},
selectedRowStyle(item) {
  return this.selected === item?.id ? "isSelected" : "";
},
rowProps({ item }) {
  return {
    class: this.selectedRowStyle(item),
  };
},
```
