### ISSUE TITLE
[Feature Request] Dialog should not rerender (or at least give the option not to)

### ISSUE THREAD

**Issue by 0x00A1FA** [vuetifyjs/vuetify#16995]
### Problem to solve
Any components that fetch data or do some expensive task would not potentially freeze the UI or cost performance.

### Proposed solution
Make a prop for `VDialog` that would basically cache the content inside.

**Comment by KaelWD** [comment]
https://vuejs.org/guide/built-ins/keep-alive.html
https://vuetifyjs.com/en/api/v-dialog/#props-eager
