### ISSUE TITLE
[Bug Report][3.1.11] v-footer doesn't work 

### ISSUE THREAD

**Issue by tadvas** [vuetifyjs/vuetify#16992]
### Environment
**Vuetify Version:** 3.1.11
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Add Footer component with any setup

### Expected Behavior
Footer is displayed

### Actual Behavior
Getting the error `[Vuetify] Could not find injected layout`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU0tu2zAQvcqUmyRAKMVNVoZjpEDR3qBAEXlBS2ObNUUK5MifGgZ6iJ6wJ+lQlmXZTrsIIEjkvDe/N6PXnfhUVcmqRjEUI8KyMopwnFmA0UrOnCP0kBsVwnMmCjkzuIH4krkzdWkz0VCZXOhVx5vOJaEy0PLXcvDwAMrouZU52hix2sinzpe9A3ln5+OvSJA7azEnLGCtaQF1AGchuFxzQIu0dn4ZPozS1iOzXYyVDJXK0Y9HaXc8g6fU3QBic55r1ZwPND/8DZk4EYZL3LZ433zssWw66NEj8Q3+SnmtLDHCyuozKOifyPZQKmNO9qZ8LvUobMrKdn2cyRxFhGorPwILPjUqXwLhho4aN7L3RN7tWL81fOb53t4lc6QvtTHfUfnbO9jv4c+v390cvtVIerbtqdwvJZ6Ou8HXUdpbm1HIva6oYeGmcp6gwJmqDcHuEKVQpIbAOZ/HcNva4CD/EF5P6tyUhZYznuLUueXN/QVAvByc/sputF1ioe0VoG0gNfeqPCGT9rS/aw772EpbvrgXuozVy1JVyY/gLP8eTbE84QbgXRkeW8oE/z/xnokFURWGaVrbajlPclemL4ylvrakS5SFK18ek8fkQSpTLVTyxJIG6sMJhlJOvVsH9Jw4E22RTY44lH/laWEOP0gGg0Pc1iaNmoYY+CpgyllW6KVHW6BH/98mLrhvNXJBuWqm1XnP+sZJhQtp89DI2m7Bu7psQkT/SUyzvxdnVXLeg6eY/AXysZSR)

**Comment by nekosaur** [comment]
The `v-footer` needs to be inside either `v-app` or `v-layout`

**Comment by Rohithgilla12** [comment]
@nekosaur How to use `vitest` to test this?
Thanks.

**Comment by tristansokol** [comment]
@Rohithgilla12 did you figure out how to test?

**Comment by Rohithgilla12** [comment]
@tristansokol Kind of got it to work in a way.

So the `mount` function also has an option of `global` that takes in a `plugins` array.


```typescript
export const mountWithVuetify = (
  component: any,
  options: ComponentMountingOptions<any>
): VueWrapper<globalThis.ComponentPublicInstance<{}>> => {
  return mount(component, {
    ...options,
    global: {
      plugins: [
        vuetify,
      ]
    }
  })
}
```


Then you can use this `mount` method in `vitest` methods.
