### ISSUE TITLE
Vuetify ssr webpack template not creating menu items correctly

### ISSUE THREAD

**Issue by jkirkby91-2** [vuetifyjs/vuetify#170]
I've just been trying to test out your framework as im reviewing vueJs and materialize boilers for my next project i initialised the ssr template by doing

vue init vuetifyjs/webpack-ssr 

I then did npm install

which through some dependency errors

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
> npm WARN extract-text-webpack-plugin@2.0.0-rc.3 requires a peer of webpack@^2.2.0 but none was installed.

I then ran npn run dev which threw these errors

> keywords if/then/else require v5 option
> server started at localhost:8080
> (node:30293) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
> parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

after loading the locahos the nav is hidden under the card and the html for the element looks like this

```
<header>
    <v-navbar>
       <v-navbar-logo>Vuetify</v-navbar-logo> 
       <v-navbar-items>
                <v-navbar-item item="[object Object]"></v-navbar-item>
       </v-navbar-items>
   </v-navbar>
</header>
```

The code in App.vue looks like

<template>
  <v-app top-navbar>
    <header>
      <v-navbar>
        <v-navbar-logo>Vuetify</v-navbar-logo>
        <v-navbar-items>
          <v-navbar-item :item="item"></v-navbar-item>
        </v-navbar-items>
      </v-navbar>
    </header>

<script>
  export default {
    data () {
      return {
        item: {
          href: '#!',
          text: 'Get Started'
        }
      }
    }
  }
</script>
er started at localhost:8080
> (node:30293) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
> parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

after loading the locahos the nav is hidden under the card and the html for the element looks like this

```
<header>
    <v-navbar>
       <v-navbar-logo>Vuetify</v-navbar-logo> 
       <v-navbar-items>
                <v-navbar-item item="[object Object]"></v-navbar-item>
       </v-navbar-items>
   </v-navbar>
</header>
```

The code in App.vue looks like

```
<template>
  <v-app top-navbar>
    <header>
      <v-navbar>
        <v-navbar-logo>Vuetify</v-navbar-logo>
        <v-navbar-items>
          <v-navbar-item :item="item"></v-navbar-item>
        </v-navbar-items>
      </v-navbar>
    </header>


<script>
  export default {
    data () {
      return {
        item: {
          href: '#!',
          text: 'Get Started'
        }
      }
    }
  }
</script>

```
Which looks like it is not interpreting the prop correctly.

NPM has installed version

    "vuetify": "^0.8.9",

My node version is 6.0.0

**Comment by johnleider** [comment]
Please review the release notes for https://github.com/vuetifyjs/vuetify/releases/tag/v0.8.8 . Navbar has been changed to toolbar, item prop is no longer a prop.

**Comment by jkirkby91-2** [comment]
ok well you need to update your code then

**Comment by johnleider** [comment]
There is no reason to be rude. It was something that was missed.
