### ISSUE TITLE
[Bug Report][3.1.11] position: sticky not working with v-window

### ISSUE THREAD

**Issue by tmichalski** [vuetifyjs/vuetify#17006]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.13
**Browsers:** Edge 110.0.1587.49, Google Chrome, Microsoft Edge
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Have any content that has an element with a position of "sticky" that is working properly. 
2. Wrap that element within a v-window
3. Sticky is no longer working. 

My codepen demonstrates the issue. Uncomment the v-window tags and the sticky position will work again. 

### Expected Behavior
Sticky elements would continue to work within a v-window container. The use case is that there are sticky elements within a tab related v-window. 

### Actual Behavior
Whenever stick elements are within a v-window, the sticky positioning no longer works properly. 

### Reproduction Link
[https://codepen.io/tgmski77/pen/BaOMLaN](https://codepen.io/tgmski77/pen/BaOMLaN)

### Other comments

This is similar to https://github.com/vuetifyjs/vuetify/issues/15433

If you take the functioning test code example within the comments of the PR https://github.com/vuetifyjs/vuetify/pull/15639 and then wrap that within a v-window the first sticky nav no longer functions. Remove the v-window and it functions properly.

**Comment by tmichalski** [comment]
In the codepen, I added a commented out CSS style for .v-window that sets the overflow to from "hidden" to "inherit" and then v-window works with sticky elements. 

Anyone who is experiencing this problem can simply add the following CSS to their Vue page to get this working again. NOTE: I am using "inherit", but that works because I don't have any parent elements that have overflow set. You might want to use "visible" or "unset" or some other acceptable value for the overflow CSS other than "hidden". 

```
<style>
.v-window {
  overflow: inherit;  
}
</style>

```

To fix Vuetify, I suspect the only change needed is in VWindow.sass to remove overflow on .v-window. See https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VWindow/VWindow.sass

**Comment by jessna96** [comment]
This is a real problem because `overflow: inherit` does fix it but introduces another bug. If this style is set, you can see that for vertical tabs when switching the content of the Window-Items and the Tabs itself are overlapping. That does not look nice. So `overflow: inherit` can't be used as a fix.
