### ISSUE TITLE
[Bug Report][3.1.11] VTextField underlined comfortable and compact drop below VSelect based components 

### ISSUE THREAD

**Issue by mhio** [vuetifyjs/vuetify#17007]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
Align field components horizontally in v-row
Look at comfortable and compact underlined text fields.

### Expected Behavior
Underline is at consistent height

### Actual Behavior
VTextField underline is below VSelect*

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVsFu2zAM/RVVF29AbCNbgQFBWnTYDrsPww5xDopNt1plSZDkdEWQfx8VOa3rzOuW2F1ziUVSfI+PksDFhn7UOlnXQGd07qDSgjm4zCQh83XMtN597hYV45Lkgll7kdGKxecZbZyk+fNRRt3trcGQK3H5GUpWC0c+qapUxrGVgHkaXA9bcd3e25fq0RAY1k7lClmDA1KAtNzdIz007YEyStJ2mg5uX2IHP11cchAFwdJVAcJXba8xXQ/MMSgWBOTuKOIdwV5jCzTL3cjyB4ihpP8Lwo8i7S3PyfVNFmAEl1CMIfiaGc6kQ/71A87wmg+I0uh+RMZTpB/73PeU8zIvUjvw6e/3tPrjh3/aBhTm1P772/2/ej/KUzhS309+UwcS5N/7/VUJ9WyHz+KYWAwkrZNH4nigI+Azv9jFHxf3oJsnYHR76dd+oAyTJi7CqDlPWyMoLm1uuHbEgqu9m1ca4ciGGCjJlpRGVSTC2TXywbmS1hHUhVx4/5voCwjs8ndlRHEWvd0H5Ddc2yZkESkJ0SRydypaYoQnECARjE5owEOiOvlhlcQReeP5Zo3DZnRGdhZvQx5+ndEb57SdpWkt9e11ghqlV+hLTS0dryAuVHX1PnmXnH9IC25d256AreIV6mTBIGJGJ63kjpf3fQCNG/NOk+k05G1ssWAr6xMfJEwRZQ0mNuBvKZg/su/EPqmg4zuowmNuM7lFRfEtuLUdMXO7E3Kxp3ZEebsUfv/Sw2wnNNBDwLCFLn8BeW7QEg==)

### Other comments
Heights in comfortable text field: 48px, 44px, 40px
Heights in comfortable select: 48px, 40px, 32px

**Comment by KaelWD** [comment]
Seems to be fixed in 3.3.0 by #17175
