### ISSUE TITLE
[Bug Report][3.1.11] VMenu - Menu closes when nested menu closes

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#17004]
### Environment
**Vuetify Version:** 3.1.11
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce

* Click the button to open the menu
* Click the inner button to open the nested menu
* Click back into the first menu (it should remain open but closes).

### Expected Behavior
Only the inner menu should close when clicking back into the first menu

### Actual Behavior
Both menus close

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU7Fu2zAQ/ZUrO7gFQslGPAlOkaJLtw4dOkQZKOkUs6ZIgqScGIb/vUdJdi2pCdAsEu/u3Xt8R/LhyL5am+xbZBnbBGysEgG/5Bpgs+fC2m7ZBY2Qeohg+MVViCXULWSlMh650bw0OqAOvFSy3N3lrBbKY87OzZHurAQfRRnkXgTjCHgE64z1cBqBO/UiaKCv1BXhOhRhfljUm7QrXpOnIx8XCr9FDFAq4X3kEHw9kblabyq5v0ArXit8mYD7mZDxafb/rF3Z8+GgMMpJTwSHDAplyl3O5r5/tgVE6bn3V/2/NQP4Fg8KCkEfqSFskX62DZG+axgfBmVnvok64EvgtURVXZw8yypsM1gvlzaOL3b+RU1IaeCjM5xKz2SHixnT55sZg/7OjmZAoS+dtAE8hjaWZWONC3AEhzWcoHamgQU9gkUE0/X1ARr/BHex/mnxHZUy8Ms4VX1YfI7kPR0RsRvWc9EmbPLbG03v6Bj3kg8FOq8MukzMkUaMc7YNwfosTVttd09JaZr0nmqpa3WQDfLKNPe3yW2y5ELZrUjWNB8frssJ+oYXzjx7dCScs5srjSDrw2s6Q5noV8lq1fMOOa5E4SPxjDAllT067lBX6NC9aWKC/ZeRCWRmJkqfcn2i+Sqpd34y2tJ3Y3047/AdLjuK2P8YZU43bLRL0u072eMfhPyZnQ==)

### Other comments
Works in vuetify 2:  https://codepen.io/joel-wenzel/pen/gOdqMgQ
I tried attaching the inner menu to the parent menu just to see if that changed anything and it doesnt.

**Comment by fahmifitu** [comment]
HEy, I have the same issue. Have you found any workarounds?

**Comment by mmwoodfo** [comment]
We are also experiencing this issue! Has there been any movement on this?

**Comment by joel-wenzel** [comment]
@fahmifitu @mmwoodfo I havent found a work around, but I was able to fix it using https://www.npmjs.com/package/patch-package
Here is the diff in VMenu:
```
-      closeParents() {
+     closeParents(event) {
         setTimeout(() => {
           if (!openChildren.value) {
-            isActive.value = false;
-            parent?.closeParents();
+            if(event && !overlay.value.contentEl.contains(event.target)) {
+              isActive.value = false;
+              parent?.closeParents();
+            }
           }
         }, 40);

-    function onClickOutside() {
-      parent?.closeParents();
+    function onClickOutside(event) {
+      parent?.closeParents(event);
     }
```

I haven't submitted a PR for this myself because I feel its kind of a hacky solution, waiting to see what the vuetify team does.

**Comment by fahmifitu** [comment]
@mmwoodfo @joel-wenzel I used a v-overlay as follows and made it function as a menu. it doesn't have this issue
```
<v-overlay
    ref="menu"
    v-model="menuToggle"
    v-bind="{
      openOnFocus: false,
      openOnClick: true,
      closeOnContentClick: false,
      closeDelay: 0,
      openDelay: 0,
      locationStrategy: 'connected',
      scrim: false,
      scrollStrategy: 'reposition',
      maxWidth: '280px',
      contentProps: { style: 'min-width: unset !important;' },
      ...menuAttrs,
    }"
  >

```

**Comment by vicdotexe** [comment]
@fahmifitu 
>  I used a v-overlay as follows and made it function as a menu. it doesn't have this issue
> ```
This is also what I ended up doing earlier today and works pretty well.

**Comment by sametaylak** [comment]
any updates on this?

**Comment by Dgbsoft** [comment]
Any adjustment predictions?

**Comment by marilgt** [comment]
Have the same problem. Any updates?

**Comment by yuwu9145** [comment]
> @fahmifitu @mmwoodfo I havent found a work around, but I was able to fix it using https://www.npmjs.com/package/patch-package Here is the diff in VMenu:
> 
> ```
> -      closeParents() {
> +     closeParents(event) {
>          setTimeout(() => {
>            if (!openChildren.value) {
> -            isActive.value = false;
> -            parent?.closeParents();
> +            if(event && !overlay.value.contentEl.contains(event.target)) {
> +              isActive.value = false;
> +              parent?.closeParents();
> +            }
>            }
>          }, 40);
> 
> -    function onClickOutside() {
> -      parent?.closeParents();
> +    function onClickOutside(event) {
> +      parent?.closeParents(event);
>      }
> ```
> 
> I haven't submitted a PR for this myself because I feel its kind of a hacky solution, waiting to see what the vuetify team does.

I have tried to fix this issue for a pretty long time, I think your fix makes sense:

- closeParents seem to be designed to close all upstream parent menus when mouse point is outside all menus
- It makes sense to stop closing parent menu when clicking point is inside that menu

I have tested all working good and it makes good sense @joel-wenzel
