### ISSUE TITLE
[Feature Request] where to put the footer in the layout?

### ISSUE THREAD

**Issue by kaboume** [vuetifyjs/vuetify#17009]
### Problem to solve
I have a Nuxt3 + Vuetify3 application containing long pages where the user has to scroll all the way down to see the whole page.

I would like to add a footer to my pages that is present at the bottom of the page so that the user must scroll to the bottom of the page to see the footer.

The problem is that when I insert the footer in my layout, the footer is always visible (without the user needing to scroll to the bottom of the page).

```
<template>
  <v-layout>
    <v-app-bar
     ...
    >
      
      <div class="text-center">
        ...logo...
      </div>      
    </v-app-bar>
    <v-navigation-drawer
      ...
    >
      ...
    </v-navigation-drawer>
    <v-main>
      <div class="pa-0">
        <slot />
      </div>
    </v-main>

    <v-footer
      app
      height="50"
      color="blue-grey-darken-3"
    >
      MY FOOTER
    </v-footer>

  </v-layout>
</template>
```

### Proposed solution
Don't know

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

https://play.vuetifyjs.com/#eNqdUrFuwjAQ/RXLM05AiAVRRId2q5CqLhVhMMkBLolt2U5ohPj3npOQQKAduuXevXvv3TmrE33WOihyoFM6c5DplDuYR5KQWcFSXqrcVVVVc63ZhpsGQCgRBYlTbu1TRB18OxaDdGAiipSWFCJrXn83SmFfCrUlL8SOO6EkSww/gm919EfdZjDjQt4msq5MARPtQez2bkpGw2Gxx0x1kpZasK1SPm0DEFIP4ORkGNEOjlWqDKKbNAe2M1CyhJsDSDbuWK0sIW+f5HW5/Hh57y5wsbqkRqCN7Yv20LPw6g3ogIpMK+OQrIMvqyQ+0snPRE3DRnRKKsRj+Iq+xsWd03YahrnUh10QqyxcYC80uXQiA5aobDEOxsGQ8VTveTDBu1h33Q7AZmxj1NGCQeOIDq48nNiWv/k0bZQfBaNRrdtguOTGeuE7wRBdCjDMgEzA+N/njyV63EeL9Ch3y3jrcyTPeN9UyIPtnTa21VlXl4T/2LKS8PNrb3Me0JuU6FtP0vUP7kgdQg==
