### ISSUE TITLE
[Bug Report][3.1.11] Label jerk while animating in textfield compact mode

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#17018]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on playground text field
2. Watch the label jumps while animating

### Expected Behavior
Animation should be smooth

### Actual Behavior
Label animations look jerky

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUMtuwjAQ/BXLl7QSiUVbqRKCin4H5hCSDXWJH7I3tAjl37t2gpSC2gOnZGa8Mzu7OfN354pjB3zBlwjatSXCmzSMLY956Vz6TUCXyowoYYRvzBsFbc3acgftSvL0lZzVYILCEzGV1a6skDgysHV6pcOesLg4i4l1BEPoUkyWIRgqrxyyANhFWWlnPbIz89CwnjXeapZRiyw+rqwJyCiGraL+kGWP0XCwoGE+48M8BbviM1hD5c8xX45CkHzBEhM58o1Y8g9EFxZCdMYd9gV1E2vShO8MKg15bfX6uXgqXl5FrQJO+QKCznfefgXwlCj5bGKOqjn9FTDK5Dsv5vPBd+RyOneIxjeGglKO4HMPpgYP/t/tr97+anCl3bSImb00PV20VeYQro5ZhXTIzWW1O+olizi/jTH9jA/rUeAwwrc/m6LrNg==)

**Comment by KaelWD** [comment]
It's smooth for me, chrome/firefox on linux.

**Comment by jd-solanki** [comment]
Hi @KaelWD 

Thanks for responding. After your comment, I tried the same in windows and surprisingly it's OK on windows too.

I'm using mac and can confirm there's an issue with a jerk. I also tried the same on another mac system.

https://user-images.githubusercontent.com/47495003/228434198-cc695ab8-73bc-420f-8ee4-20c15c5d0369.mov

**Comment by KaelWD** [comment]
I'm guessing you have display scaling set to >100%? It looks like switching between subpixel rendering which isn't really avoidable.

**Comment by jd-solanki** [comment]
> _display scaling set to >100%_

Do you mean browser zoom? I haven't increased browser zoom, it's at 100%

Can you please keep it open so other can thumbs up if they are facing this?
