### ISSUE TITLE
[Bug Report][3.1.11] v-data-table match all "remaining" columns (aka #item.*)

### ISSUE THREAD

**Issue by WieFel** [vuetifyjs/vuetify#17022]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.45
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
I have a `v-data-table` on which i customize one column using the slot `#item.counter`. But now I want to have another slot with which I can customize "all remaining columns". I saw in a few places (not in the docs) that `#item.*` should work for that, but for me it doesn't.

### Expected Behavior
Using the slot `#item.*="{ item }"` in v-data-table, I would expect to be able to match the cells of all remaining columns, except the ones I already matched using other (explicit) slots.

### Actual Behavior
The slot `#item.*` seems to be ignored and has no effect

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUk1zmzAQ/Ss7utB2DAxO0gPjdNLfEXwQINeqhaSRhB0Pw3/vSgJ/1jlkOKDdfXpv963eB/Jb62zfM1KSlWOdFtSxX5UEWO1TqnU4hqCjXE5RiFvqaOpoLRiUW0ZbZuxrRaZTRaDkSOdT4V+R0128PQvBPrVCuQDNfiB2AH+E8QoO4LbcQquYlYkDu1WHBdR9OPWiBdq4ngpxDJULlfxinsrF7//SjeqlY+ZxA0PMZ4YeZjCMI9SCPtCbU5c+zV5i8mSmD6LN1+3KlW0M1zgjc70v804r42AAwzYwwsaoDhLcW+LBjZLWweQ9vHrMt3c/9ACOO8FKSLhs2UeygB07+qj9SGBc+A7OkGmwE2iOA3D9/SwUNnqWQY44GbKWUARWgOl2CRUplk8V8dmoeI1f3uOfX36e8V54lUc30AeyINEK9FBnf62S+HIDH760UMC3Vs4KFUGLfIwv0zltyzzvpd79wSV2+RvWcoOqvGNpq7q3p2yZPb/kLbfuMp8x26W1UQfLDCpWZOo4kDu+OT4SmMrIW2RFEXmnXCpobT3xHWGOKntmUsNwY4aZT7u/wV5NcFO7myIYXMkRHRVc7uyNmY0NRob9+vgL4wUKf3/tZcYFie2hYLxC1v8A/Bp3Og==)

### Other comments
Is there any other approach to match "all remaining columns", except the ones that have been explicitly matched through named slots?

**Comment by nekosaur** [comment]
There is no such slot. If you've seen `item.*` referenced anywhere it was most likely meant as `item.<key>`

If you only need to transform the column values, you can do that before sending the items to the table
