### ISSUE TITLE
[Bug Report][3.1.12] Error when using Vite and `unplugin-vue-components`: `Uncaught TypeError: camelize is not a function`

### ISSUE THREAD

**Issue by 0x00A1FA** [vuetifyjs/vuetify#17029]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Start with a barebones Vuetify project;
2. Add `unplugin-vue-components`;
3. See it not work.

### Expected Behavior
Using Vuetify alongside `unplugin-vue-components`.

### Actual Behavior
Getting the error below:
```
expand-transition.ts:16 Uncaught TypeError: camelize is not a function
    at expand_transition_default (expand-transition.ts:16:26)
    at index.ts:26:82
```

The two files are:
1. `vuetify/src/components/transitions/expand-transition.ts`;
2. `vuetify/src/components/transitions/index.ts`.

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-sy7dbm](https://stackblitz.com/edit/vitejs-vite-sy7dbm)

### Other comments
Once I've added `unplugin-vue-components`, the whole project errored on that one thing (the `camelize` function imported from `'vue'` in the `expand-transition.ts` file).

**Comment by KaelWD** [comment]
Seems to work in your reproduction link
