### ISSUE TITLE
[Bug Report][3.1.12] VBtn in VTab has a default border radius > 0px

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#17027]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on any tab.
Observe the ripple effect expand to the VBtn container edge.
Observe the tab has a Border Radius, visible when the ripple is shown.

### Expected Behavior
VTab should have no Border Radius by default.

### Actual Behavior
VTab is getting the default border radius from VBtn

### Reproduction Link
[https://codepen.io/MatthewAry/pen/BaOEjje](https://codepen.io/MatthewAry/pen/BaOEjje)

### Other comments
User should be allowed to apply a border radius if they so desire, but by default it should not be set on VTab.

**Comment by santiagoaloi** [comment]
that visual incoherence stared happening after 3.1.11 release.

**Comment by MatthewAry** [comment]
May be related to https://github.com/vuetifyjs/vuetify/commit/133b4172550ec7d5ddaae19085761f31c5ce3548
