### ISSUE TITLE
[Feature Request] VTabs or VWindow disable drag switch tab on mobile devices

### ISSUE THREAD

**Issue by Ricky816845** [vuetifyjs/vuetify#17021]
### Problem to solve
On mobile devices, automatically switching tabs by dragging and dropping may not be my expected behavior.
May be add a disable props on VTab or VWindow for this ?

### Proposed solution
Disable automatic switch tabs on mobile devices by dragging and dropping.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
