### ISSUE TITLE
[Bug Report][3.1.12] Data table rows always appear clickable

### ISSUE THREAD

**Issue by abea** [vuetifyjs/vuetify#17025]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
Create a data table as done in the documentation.

### Expected Behavior
If not requested via prop or click event handler, rows should not get a cursor pointer style.

### Actual Behavior
The `v-data-table__tr--clickable` class is applied to all rows, adding the pointer cursor.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVltvmzAU/isW0tRWSiDk2qBs6tTu0nUPe51KHxxwUi9gkG3SZVX++465pMRgJJqH1sefz/F3Ph+b8/hqfU5Te58Ry7NWksRphCX55DOEVvshTtN8mBsxpqy0cjvEEg8lXkcEVbMIec8Eh4SLj75VjnzLZ770ZY5S2EFhIRGCcJmDMJ/jChvucZQRWMBwTOpgEGGhHElE9ljShA3dEm78nIqyU+OsjCKblVPLEkwRcJrKfBH5myZcopBscBZJ9FrEUXleXlUWQpzIjLM3G6EyUw891hnVFqifpDIiHrq4K1JHl+5otEUw3FO2vboYnK/GEd0yWC0k5lIHBbBUuntogyNBNHRHDuCoBDz3O55ZrydCtzhKOCXiYnDalbAQrCJQUMHGAF8xZKNSaPXfYGl2vcV8LTqcA4Wb3X/xRBLKOgKkxQpziHuegP8Hkz8F+Nz5qTauyrj75NVRKJl48o8w9DvZZs0jrVT2kDtbahgo6KG5PWq4gDYeGk+1+TJlD00bLiobYOJ2FkYr+R8kig5oTTAzM58sZm3MRybmSyPzpkvJfNSf+QOVD1CCRtYz97qN9dgo+FzP8kR70U563p/0F3jvKDeTHs/HbaRdc5VMTKSbLiXtRX/a3+ApI3zN4T3sKJPZvB/3qX4hTtwntg5VFf4Oze8DggKgHiOBWfhCg+cO/Sf6Wec5LE0pNJbXLql+Mu+/pD+TKKJpknZov2ytm5GtT1dXVL8bb1e0nfW4P+vbLA3wTvtYnZEetb4rE1sXtbqg/cW+7k/7e8LIIUjitZn4dNT6tExMal8bic9tXYKS+HTWn/ldwrKOB3E6a62R8cxU3DPXrLfhfo476uTtA3ssBvk/+LNyTr2aNbBorJo16PBS+49IGLSvebZ+CUBr6VX5+xb0t8qGplTKVHiOk7F0t7Xh+JwbwByeMUljMgyT+AaOx54unJAKWZ+3iYiHa568wBcfdvStkmYeXNLNwbRBCUNc13bHRdxybhjhtVCBGwEd1RgSPuTQjBBOeCd7be1ZBhrWyKLU9giKRpTthCZmIHIhy/bmXenlIZT/k9rmOLAKerBh4WI9/Qc3QTZt)

**Comment by KaelWD** [comment]
No it wasn't, that would call onClick every time the component renders.

**Comment by boris-graeff** [comment]
Yes I realized it just after I sent the comment, so I deleted it but you were too fast!
After checking, I was using the item-class property, to specify which line should have a clickable aspect or not. But this prop doesn't exist anymore
