### ISSUE TITLE
[Bug Report][3.1.12] VSelect options also scrolls with the page

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17030]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1)Open the playground link.
2)Open the select menu and scroll the page (make sure options menu is open while scrolling)

### Expected Behavior
options menu scrolls with the page.

### Actual Behavior
options menu shouldn't be scroll

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtm8uO3MYVhl+l0ptJAE1PHCMbQQ6sWAokwLKM2IggaLSoJovNUpMsuqrYnIagJ8sij5RXyPcXezRjKdEiW3N06ebtXP/zn3Mw4Jv3m8fjuD1ObvNw8yi7fuxsdn+5Hox5dLy041i+loPe+uF8VI6T61yVze0Zfjq7c903F2PnbHLGDdlFcwpTNJXPp4vr4Tovfx56FKVvrjdvLh63vavtztYXDy6euK71fL6Y+p3Vl0PoDjbbi7fXmzvFV7ea707dGqmfn+dgbEpTxIB6trE2c+uGypncOjPbtDWv2mDmEHN7MieXTXaD2YWTqd0QMreEoXaRu5w7JHP0bk6mxY/k9202oat5wMZkUojxtDWP69pnH4ZkKjuYNKURy1xtfOZMQK/tOBqnbJopDj61rt6aF1IrczBhtDH7aupsxIIjglqP6bWrfPJH150kJXlMkhjdazuCuTXfuZhJCIrwChOGvRnCEnOpx88fCQNfZbzHJ75OA4k5mSS1ATHOkGC8ke9ehr1sTedSMnsfO4mbbXfAx4wQk8aAKp9b02CYCU0JzpasDk9vCGKNggOKBgnI0TedbIqud/0OE5CAJ40fuC1MuUMGZjZIT8mnbJWihPm+579UMjMNBUkSkywuvxxJFXE7GUK9m/CkHPR4NFWtackQ4gZjqywLaz8MKJ4V9GSs5Nld50wLKIgr7mXckznD1jzvwaEH+ojpS8yiS6E7Snnrk2nsESATMpBRsniLF7uLwdYSv4s40fKtxOQ5poLEnuNzcGqXfAxTMtGOGXwmZZm86xL2RsHmY4iQYr4LnXCuOA2KUMZq4knWZdU0mmrBAKdRNbiKyNtIdEj+SwSW9Jl66joEcEcKZ6SHwDXCzDNzSS/HLVBAM7mrQt/bxWI7AXoH2iXyOYXA+RR6vB7ujMf1iO4loYNxt2A4+gpLs7Kze4cfEiEzeo8STAERQVbuHGkV64Bvnrdk46V8mqlA7KUaZPTcoqfhXyVu6VxDPhPZeGEzQSeuQ21SRbWR2Bkk3ZiUTxw1wFugQvtrURHGjzZledCDmpKrx7V35MXdVG7MwprZUWmYWOrWuR3WLAAQOrbm6ZCjs9mTwjNGSQ5uNg0uK66Nm83o7RAaeEZITJVcLSWo8Ab5ZxO19SLACmSzAhhkGcCEYY95BKJXkiwQpz6VXkqvEJONPUUYSkxNL3hBsNhGWM7I7ywRGGMpHH8DE3BxgihSG2adBFJeQJyGA8EaKJGBYuFmp+qoEUoaavjgMUGFdA7GnfA1B5KnfJQg/OTpFZDsTUUebjXracFsbsGuuKsvxAShY2QR+XMbAJWxgPL8aGcJv6qiuBrdXqR9pnBoANQ0SoLoRLRrxhgKy6qC7b1q+gUXxYMlpX8PoQdlkBXwpz7sQTQPjILiVAeCEigKAt5E62voRLE8QaB1CV8HRsSIr9AAXXG8lMKduuj4PLPZ7Ar3fD9VBy+3W1eSXYUuDK4T5sjgTJRythVtRejnCUeiXSElBSZCwUW3uG8Bb9X6jkt/VdAh3Byn8onjO/UI223N36L7ZQJzqL0HQODDHRBe0xQGUdyphdsWBBIKHVfdtDATzFoQQGwraK4A8ty8Sjhf0z9L5Tr4BUatQ2/I/kB1nzuJyE5NJzoAU5hAnQgHETmGZOGg0kbcjYv0NlVukdRKGXhT5QPlngJsXIy02K35Bz1Q9EcVaI4o/RILIBZQEwLdZk/89nYvB6ExZheuLH2rg63CqDwVJCww8HALyGjKpdIHs0JLBTfmHSQDAQGFQK/5IaCbdCv3MLyS/7G51i5H8E6EKysAY2Tpv9A7+cBW0UaoICoGA3CigUI4adA7UVvixJZgKbA/BBPg3TJB2CHNy53AFrxraqKTnzuRWrlACeQU5lBPVZkzTANwBnU0GqFv7sShC1bQ3U8HOYekOcIupim1WfofVUF9/Yq71GvipC6sr370DDiEXdW+WISDt8mV8O9BbOFA1etds/MgT770dA/RNp0DxbF3sSO8L7imsmyj+IeKp5pK1xX+azvsNTHQiEvLcoXiFrbAmQLppc3AATwK34Me9UN6hGajn3rRCzAsrZsicoRF9pQup+AvqH7CcJKGpUe0zEHCWppG4OrMEelliLzBaZ0/c6MSZ56UgpF+7IOSMEaDDh7V5G1h+h2GvMarf//zX4T6XTiAxYV95CdQpq7L8AGAik5BaEdfOTTqTzVkBGgbzwywYOeuSin4VIZODbM0ztJFybAEq750rbh+24uJWsUEwaBZkh/mAqZzL6+jVVfgbqavkhblTHaJiO7Y7WUDy6tDllntHjY0k8QDNFYw5oejlyqmqhJj/LgbG87TMvUXo9cwxsiXypd9COfRkQEe8ilUgN3kQS4DHfiZh2Q5WrCElq/Jow9H8eBTItKX+U4ueabVElBqHSLsAx23DPBViIx5pTfBc9wjvLB4YCXMTvWrUhIjIsYqUAZyUT9EfWmlr5R08ZAwkwAr107mUAappze0IDFWmSTIm4YCnN2LnomRJtNJBYyXpZU/CQrYMYjPcmAahUxhAHX+E1qLwefJJoODEs9n8k7FOnXyhjjxlyVH/YAyod/SIjQMwBhJsWAEBdoopUVszTMNMeCRKbOQh7o7llOgs+to15rncKid0k5JI3KQFxCjzqWFbnhuAnDtqZwp1WG7PgDaZYoxlID6sBAjpgBWREG2Mt+V5USduPd13TlNWZZp4keaTuXhkYUtlEx2Iom+NzHdW4US0HQaA5ZkLjOBpmuqv3Dp4hqh7B23Yncjyu78wRHG22VxXRvXtXFdG9e1cV0b17VxXRvXtXFdG9e1cV0b17VxXRt/82sjMfh8b1w3x3VzXDfHdXNcN8d1c1w3x3VzXDfHdXNcN8d1c1w3x3Vz/PLmuO6N69647o3r3rjujeveuO6N69647o3r3rjujeveuO6N69745d843v3W8dHVx7cxeQny4+uYOlhe1Hx0de8FTg5TFb3mRAYAXYYZmfLMe7DYmA/QMb3xgjc/9WYmtkOnpk97842u//7iGcAI5lWIXf27iz9I+CIOQZsHm0UWRozbd0CHl0ffy5br84V0vXloyhmdQ4eOrzdtzmN6eHXFMHrYbwnX1bdcu4oUCJPvJc3626+3X2//eGm7sbXbP19RH/n+5a1L/SVtbia1KL7ePLinI/vm9L/0nC8j/qvtV39a5J7PXfLaapLgzwReqYe7eHnujPGLTnxy739z5JNbPnNGqj9cDx+IL0PkIX0S2iqVsL65tfD/8LKI0PNvpebDg82vrETv8uTm7X8A1qHmXQ==)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-select/#props-menu-props
https://vuetifyjs.com/en/api/v-menu/#props-scroll-strategy
https://vuetifyjs.com/en/components/overlays/#scroll-strategies
