### ISSUE TITLE
[Bug Report][3.1.12] Vimg inside VBtn does not render

### ISSUE THREAD

**Issue by JChrist** [vuetifyjs/vuetify#17031]
### Environment
**Vuetify Version:** 3.1.12
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Edge 111.0.1661.54
**OS:** Windows 10

### Steps to reproduce
Adding a v-img element inside a v-btn (either in the default slot, or in the prepend slot) does not render anything.

### Expected Behavior
Expected v-img to be rendered and visible

### Actual Behavior
v-img is not rendered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFU01vGjEQ/SuDe1gi2HVDW1WigOit/6CHbA5m1ywGf8k2hAjx3zv2Llsgag+5RIqUffPm470Z83QiP60tDntOpmQWuLKSBb4oNcDskDNr02cCigndoYQDP4Z8LbisAUlTczkvifJNSYBe5wnVwFTUSGbqFUGGCYod8w0XzSZgePKti7yIOmwuAe8q/NyEYP2U0qrWUWQQ69etLyqjqFCs4Z5a5piU7EgV6naCyWJrUcKNglXQkATgB3ZeVlJUO4TpP68xdGBYqqOY6KokfTXWX5YCn6zjluv6igToYryGVNkzZfh46yie3py0C3rL9CKZB8UHM5pwvy+aFna5O6L+8BG0T+KmL0JfOWEDeB72kRbKGhfgBI6v4QxrZxRk6CGLyZXRPgA+FJhHfpj94lIa+G2crAfZw49LRqVDl/H5KtieDInhA8wXcIq6ImUkL6Rphv1VByWJZRAnFQcm9xxGc8Dt4t8oNm+DKaVHoxHic7JEW0/ohoxJawg3YYutNxp/K2lw2RG+JNNWSoyh0Yj/XnCv7a5Jl1siR91eB6F4Xhu1/FJMiq/faS18uI4X3Kt85cyL5w4nlmR81Ty+hH8N6Gjs+1g8Ttq+XSyXbOVj4zcNKU45cJe7+JAdd/9Vf5d74+COe+MizsTtnnGjUuidv1tm5dMiny7S3mEvtYj1z3HMeUxaeTiwLSHPfwDcN5x6)

**Comment by JChrist** [comment]
It works as expected if I replace `max-height` and `max-width` with `height` and `width` respectively. I updated the [reproduction here](https://play.vuetifyjs.com/#eNrNVMuO2jAU/ZWLuwgjSFzSVpUoILrrH3QxmYVJTDDYjmUbhhHi33vthOd0WqlSq0pI5NznOcdxHg/kqzHZbsvJmEw8V0Yyz2eFBpjsUmZMfIxAMaE7FLHne58uBZcVYLKpuJwWRLm6IECv64SqYSwqTCbqBUGCBYrt0xUX9cpjOP/URZ5F5VengLMlPq68N25MaVnpQNKL5cvaZWWjqFCs5o4aZpmUbE8V8raCyWxtkMINg4XXEAngwwhHz0spyg3i+M8rDO0Y9urAJsgqyLkdB5xcgXfGcsN1dZUE6GK8gtAJo0uu8D9RP/rH8pE/vTnWLugM07OoHxTvTWjEZ89oNO2CF/YtP/O/7Gf+Gz/z4Oetl/+rjwGdL1EA7fW6mYvQlVYYD477bUgLZRrr4QCWL+EIS9soSFBDEorLRjsPeOlgGvL95BuXsoHvjZVVL3n4cqoote8q3l8F29PCRP8BpjM4BF4h1Uieyabunw+0V5DQBmFTtmNyy2EwBXQXf4MwvA3GkjMaDBAfoyTaakI1ZEhaQeiEydau0fjdiYuLLuEKMm6phBgKDfhyglttNnU8uTnmqN1qLxRPq0bNP2R59vEzrYTz1/GMO5UubPPsuMWNBRleDQ9vwlsLujTOHWWjvJ3bxVLJFi4MfjWQ4pYdt6kN77Dl9pfs72pvFNzlXqkIO9HdIzoqhd64OzNLF418PFH7A3lxROh/CmuOQ9LSw4VtC3n6AR/7AbI=)

**Comment by santiagoaloi** [comment]
There isn't really a problem rendering an image comonent in that slot. 
The image dimension props as you mention are defnitely affecting how its rendered.

 [reproduction](
https://play.vuetifyjs.com/#eNqdUstu2zAQ/JUNe7ADW2IeBQq4tuHe2i/oIcqBlmiFNl8gKSWF4X/vkpIc2UF7CGxA3J3dmd0hn47kh7V523CyIMvAlZUs8HWhAZZtxqxNxxQoJnQfpTjwt5DtBJcVIGgqLlcFUb4uCNBx3TZoEBVieEBsU0pRHjBMX15hqmVOMB0wFzkLcu7G/mEk+GIdt1xXIzDRC1XDq6jCC7Y/3iGbdyUeX0KwfkFpWem4XRC7P3ufl0ZRoVjNPbXMMSnZG1XIjvoy31ucfQ1LmkhRpwjD71fsAYfy3OHI7+PRC8u6VFp58A2js3Ex6Cy96MPQl07YAJ6HJsJCWeMCHFFxByfYOaNggltMYnFptA+ARsMq4tPJTy6lgd/Gyepmcvt9qCh16CvuRsnOdASmt7BawzHOFSEjeS5NPT3fy01BYhtEpbxlsuEwWwH6i/9ZJO+SqeQczWYYn9JKtNsJtyFz0i2ETth8743Gt5aEix7wBVl0o8QcLhrj9ztstD3U6e42iFHX6CAUzyqjNo/5Q/71G62ED+N8zr3Kts68eu5QsSDzEXl8C/8S6GHkvc/vHzrePpdJtvWR+AMhRZWWu6x/H+6/01/VXmxwhX3YImqiuyd0VAp98Fdmlj4Z+TSM9on1EkXsf44ypznpxkPBroU8/wXSrmBo)
