### ISSUE TITLE
[Bug Report][3.1.12] Placeholder in Input fields does not show unless focused

### ISSUE THREAD

**Issue by markcouvaras** [vuetifyjs/vuetify#17039]
### Environment
**Vuetify Version:** 3.1.12
**Last working version:** 3.1.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Change version to 3.1.10 and you will notice that the placeholder content is visible. When in 3.1.12 the placeholder only shows once the input is focused. This seems to be the case for all input components

### Expected Behavior
The placeholder should show as long as the value is blank.

### Actual Behavior
The placeholder only shows once focused

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUU1PwkAQ/SubvVQTuhtRL6QY0LMnj5RDaQdY2a/sLKgh/HdnW0gqjR48NO28N/Pem+niyOfei8Me+IQXEYzXVYSn0jJWHPLK+/azLUyl7Llq6wifMV8r0A0j0jWgpyU3uCk5I5Eatk43EAh7BcRqA0KIksu+AoKGOvamFQWg8Ul6I9VaYRzIvXVTqaeVZLWGKlQrDRfxQvbSpqLbo5C9/ajEOigfGULcJ1oZ70JkRxZgzU5sHZxhGR0mS821sxgZbcemib/JstsLmIIM0RT9jC6yeTbKnul5yZbUUMjOmTz5iHe2lNeLd3SWfsMxxaZjtASWfMJaJGEUJ9Ul38bocSLl3vrdRtTOyBlxMuxtVAbyxpnZvRiLh0fZUJA+LgBNvgruAyGQY8lHPfGo1l+/GZxp0r0Td+NO94zlulphEh4ISnI5QMgDWPp7EP5Mf9X7Y4MrbrBF8jyV9kQX1cru8OqYNbaHXFyi/WO9ViLNL5PNacS7eGTYjfDlN2AjFzg=)

**Comment by KaelWD** [comment]
#16565

**Comment by MatthewAry** [comment]
Likely affects the `prepend` prop as well.

**Comment by SHrebeniuk** [comment]
Same problem(

```Vuetify Version: "3.1.12"```
