### ISSUE TITLE
[Bug Report][3.1.12] Why are all i18n files loaded

### ISSUE THREAD

**Issue by margintopt** [vuetifyjs/vuetify#17043]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Edge 111.0.1661.54
**OS:** Windows 10

### Steps to reproduce
Hello , I just started learning vuetify.

I would like to know why I set the language setting here
`
  const vuetify = createVuetify({
    ssr: true,
    locale: {
      locale: "en",
      messages: { zhHans, zhHant, en },
    },
  });
`
but all the language files are loaded on the network, 
![image](https://user-images.githubusercontent.com/30163907/229005504-7f36e3cd-130d-44a2-9cf1-5e2767e4718a.png)

can I load only these three languages？

PS:
Why does the console report this error?
![image](https://user-images.githubusercontent.com/30163907/229005662-4fb3de9a-c843-47c2-b510-8804b12379c9.png)

### Expected Behavior
Only load the ones I set

### Actual Behavior
load all

### Reproduction Link
[https://codesandbox.io/p/sandbox/funny-sanne-0p43vq?welcome=true&file=%2FREADME.md](https://codesandbox.io/p/sandbox/funny-sanne-0p43vq?welcome=true&file=%2FREADME.md)

**Comment by KaelWD** [comment]
https://github.com/vitejs/vite/issues/8237 - they will be treeshaken in the production build
