### ISSUE TITLE
[Bug Report][3.1.12] multiple v-tabs/v-window in the same viewport cause involuntary scroll to top

### ISSUE THREAD

**Issue by MarkusWollny** [vuetifyjs/vuetify#17046]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
When you have two v-tabs/v-window instances on a page and both are within the initial viewport and the bottom v-window has enough height to overflow the initial vieport, toggling the inactive tab on the bottom v-tab causes a scroll to the very top of the page.

If however the bottom v-tabs/v-window instance is low enough on the page to not be in the initial viewport, there is no scrolling to the top when activating the inactive tab on the bottom tabs.

### Expected Behavior
when toggling tabs on a second v-tabs instance lower on the page, there should be no vertical scrolling

### Actual Behavior
when toggling tabs on a second v-tabs instance lower on the page, the page is scrolled to the top.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNrtV81u2zAMfhVCl2xAbC/pgAGFO3S33Xese3BiJtEqS4YkOyiCvPso2U39k3Rx1wJD2yAHk/z08cekJd3s2I+iCKsS2SWLLeaFSC1+TyRAXAVpUfhHL+Qpl43k5aWSllSoD0qAxycCaLVtmZo1ApYiNeYqYV4KZvOEdVAeZ9OFAXKpMhQEJXE2gD0AoUpFiYRaKZWwAz0KrFLLlQwuaCnZwKoijvySvzEtUn2SiWynmRqt6eZNSkq1pXOabnX+rVxbLjO1PatgNTTg9Kq7hRuAE+v0fQaKvEVxrgdf0CMenH6Uh0fr6BKPKXZxH8y+9CJOLIEyXvEM9QGY10CIunH+WmolBFCYEkppuQC74Qbon1p6RNdBoFb+seK4LZS2UydJsqzXggBkWShrVQ6uocLBOz8vknGFeb3xHcJGj29djRea4KfI/qMhPlG2MUMcb+YDrfsdGW6X01H0+Y3vfz9RU/MiuB0CpQWh5BpQqnK9Ibf0+aTebrK19F4RjB+XdCGw1+fPcP6evL/v7F91Zzo1Nkd2rI+x+RibNzo2L3DcqrHdq4LTHa4TTqgvGnHUuoCQSFnywoJBWzozz90xCXagcQV7WGk6G03o5jJxYHJh6GhF5164coBPE9rgJp9bhnnPEEc1PzGzKavJKaoi/G2UpNvQzgWXNAaTsEvwGqcjp05O2MbawlxGUSmLu3W4VHl0TbZIuzNfjkGm8uuLcB5+/RZl3Ni2PkSTBwsqmUFNHhM2bZFbvro/5aAxE+8snM1r3kYXUEcYRzwgjMhLhTrQKKktkD55T0Tfw3Yy6NkGWTif+0TuqaKCyzvTK+bS+ELePIT2jPQ8hVt/69zsp6wOjxzWS9jtH8jXPOI=)

**Comment by MatthewAry** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/18447
