### ISSUE TITLE
[Bug Report][3.1.12] Component is not rendering

### ISSUE THREAD

**Issue by brunolorente** [vuetifyjs/vuetify#17041]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Hello, good afternoon, 

It's my first-day using Vuetify and there's something I'm missing... 
I'm trying to make a wrapper of the v-select component (if I add it directly to the parent component it works perfectly). I need to make a wrapper because of the chosen design pattern. 

I am using vue@3.2.45 and vuetify@3.1.12 

The code of the wrapper is the following: 
```
<template>
  <VSelect
    v-model="favorites"
    :items="states"
    label="Select"
    multiple
    hint="Pick your favorite states"
    persistent-hint
  ></VSelect>
</template>

<script lang="ts">
  import { Component, Vue } from "vue-facing-decorator";

  @Component({
      name: 'MultipleSelectWithSearch',
      inheritAttrs: false
  })
  export default class MultipleSelectWithSearch extends Vue {
    public favorites = [];
    public states = [
      'Alabama', 'Alaska', 'American Samoa', 'Arizona',
    ];

    mounted() {
      console.log('XD');
    }
  }
</script>
```
 ---
 My project's main.ts file is the following:
````
(...)
// Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'

const vuetify = createVuetify({
  components,
  directives,
})

import "./assets/css/style.css";

// MSW handler (mock service worker)
if (import.meta.env.MODE === 'development' && import.meta.env.VITE_API_MOCK_ENABLED === 'true') {
    worker.start()
}

const app = createApp(App);
app.use(vuetify)
app.use(createPinia());
app.use(router);

app.mount("#app");
(...)
````
 The browser shows: 
 ````runtime-core.esm-bundler.js:40 [Vue warn]: Failed to resolve component: MultipleSelectWithSearch If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. ````
 
When I use this wrapper on the parent component (is a view more than a component) nothing is rendered, and inspecting the element, I just can see ````<MultipleSelectWithSearch/>````

### Expected Behavior
The wrapper works

### Actual Behavior
The wrapper doesn't work

### Reproduction Link
[https://codesandbox.io/s/zealous-river-i08kh4?file=/src/components/MultipleSelectWithSearch.vue](https://codesandbox.io/s/zealous-river-i08kh4?file=/src/components/MultipleSelectWithSearch.vue)

### Other comments
As I said, if I use the Vuetify component directly on the parent view, everything works fine.

This doesn't solve the problem: ````isCustomElement: (tag) => tag.includes('MultipleSelectWithSearch'),````

Thanks in advance

**Comment by websitevirtuoso** [comment]
I have no idea what are you trying to to but I wrote many wrappers.
Here example
```
<template>
  <v-data-table-server
    v-bind="$attrs"
    :items-per-page="pagination.take"
    :page="pagination.page"
    :must-sort="true"
    class="elevation-1"
    data-test="datatable"
    @update:sort-by="sortable"
    @update:page="incPage"
    @update:items-per-page="itemsPerPage"
  >
    <!-- Pass on all scoped slots -->
    <template v-for="slot in Object.keys($slots)" #[slot]="scope">
      <slot v-if="scope" :name="slot" v-bind="scope" />
    </template>

    <template v-if="searchable" #top>
      <v-text-field v-model="rawFilter.search" label="Search" density="compact" hide-details class="px-4 pb-2"/>
    </template>
  </v-data-table-server>
</template>

<script setup lang="ts">
// this component is wrapper to add extra functions to original v-data-table-server
// added prop - searchable
// emits sort, pagination
import { rawFilter } from '@/composables/useFilter'
import { paginationInitial, sortInitial } from '@/components/datatable/index'

defineProps({
  searchable: {
    type: Boolean,
    required: false,
    default: () => false,
  },
})
const emit = defineEmits(['update:sort', 'update:pagination'])

const pagination = ref(paginationInitial)
// sorting
// datatable sorting type
declare type SortItem = {
  key: string
  order: 'asc' | 'desc'
}

const sort = ref(sortInitial)

const incPage = (page: number) => {
  pagination.value.page = page
  emit('update:pagination', pagination.value)
}

const itemsPerPage = (items: number) => {
  pagination.value.take = items
  emit('update:pagination', pagination.value)
}

const sortable = (sortItem: SortItem[]) => {
  sort.value.sort_by = sortItem[0].key
  sort.value.type = sortItem[0].order
  emit('update:sort', sort.value)
}

onMounted(() => {
  emit('update:pagination', pagination.value)
  emit('update:sort', sort.value)
})
</script>

I hope it will help you
```

**Comment by KaelWD** [comment]
Sounds like you didn't register your MultipleSelectWithSearch component, nothing to do with vuetify. 

https://vuejs.org/guide/components/registration.html

**Comment by brunolorente** [comment]
@KaelWD why do I need to do this? This is the first time that I need to do this.

Thank you very much for your last response, solved my issue
