### ISSUE TITLE
[Bug Report][3.1.12] v-progress-linear striped + color="primary" breaks striped

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#17049]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
```javascript
<v-progress-linear
  model-value="10"
  buffer-value="50"
  color="primary"
  height="10"
  striped
  stream
/>
```

### Expected Behavior
The striped class should override the background prop of the primary class.

### Actual Behavior
The primary class background prop overrides the striped class background props.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUstuwjAQ/BXXF1qJxFDUHhAgeusf9EA4mGQDLn5p7VBViH+vnUebBtRDb5kde2Zn4s2Zvlibniqgc7rwoKzkHlaZJmRxSri19WcNFBe6RTW2aPYIziVSaODYMcoUIJMTlxUsMzqdZLRjdlVZAn5TTz0qN9JgmFkUiuPnD3EAsT/4gZDzKCwUPQhcNYh1+7LewhE0URasFzFAlwclTxz4KtJCWYOenAlCSS6kRKPIKHQziodzo50nyu3JMvL3o1eQ0pA3g7K4Gz1E8UZuRce0UQor2PTdGR3KPcdNspZwGZ2TehJnwSHijB68t27OWKXtcZ/mRrF14BhW2gsFSWHUepbO0knCpT3w9JkVwvk+nYJTyQ7NhwMMxhkd9zy8KEOzt31aOshP0+ljo9vOEsl3LgpfCbLgcgp/FEEXgIB/hhicvRVkcOQqTLS+ZPoS+g1v7ugG1eaurnXTbfiPlLVEvL+NNpcx/bVl8G1u0u0XJX4Mvw==)

**Comment by KaelWD** [comment]
@nekosaur any idea why we changed theme from `background-color` to `background`?
