### ISSUE TITLE
[Bug Report][3.1.12] V-combobox #no-data #details shows empty v-list-item

### ISSUE THREAD

**Issue by FrontDev07Axas** [vuetifyjs/vuetify#17048]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.3.0-alpha.6
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
link

### Expected Behavior
no template or #no-data template

### Actual Behavior
v-list-item

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUltuwjAQvMrK/UgrkaSAxAeCil6gFyB8mMSAi1+yHdoK5e5dJ1CS0FaInyi7s57ZGXt5JK/GJIeSkSmZeSaNoJ69ZApgdoipMfVvXUjK1amq61zLtV7rT0BIF0zMMyLdNiMw5cjjsOReMoeNHS9YXDBPuXAXhvRCcRNtLqgLrNLHw8nNMsh5dgUPSscF9bQFArxpCL3WfNqJ4aZd+7vdF0ln12vw7l1D6+f2QtHca+cwli633HhwzJcB5tJo6+EIlm2ggo3VEiJ8KFEYzrVyHtAczAP+qEohns7t2iQCy2gYDSAahc84WgXFRgPZyYA0AriZSd6dVvgAj2FBDKkGMKYp1J3QQ+FQZ2TnvXHTNC2V2W8TdJouEEttqTyXmKmWi3EyTp5jKsyOJpO04M634YQ5Ga+t/nDMonBGBi0Nzzdff+mcYKQfJsNRw3vqxYKuXSC+IkxR5cBsbJkqmGX2XxO92d+M9EauzATpKlMV5iu42rtetLmrY12eN7zDZU0RzuOFVqQakM6WqNucJKtveghnoA==)

### Other comments
v-combobox shows an empty template when there are no elements matching the filter

default #no-data slot or any #details slot can fix it

**Comment by johnleider** [comment]
This is intended and in line with how it was handled in v2 (https://v2.vuetifyjs.com/en/components/combobox/). Here is a [playground ](https://play.vuetifyjs.com/#eNqtUttO6zAQ/JWVz0MOUpNQKvEQAYIf4AcaHtzEpQbf5HUKqMq/s3ZSaMtF3F6q7s7uzM7E8w27cq5Yd4JV7CwI7RQP4qI2AGfrnDuX/qZCc2nGKtWN1Qu7sI9AkG2FOq+ZxtuaQSWJB6mUQQukxkq2Im9F4FIhVKkyNm954DS05ApFzV6Zy1fqL8k1imNU0yGfnv5anrS2KcC/cWwHBLi2EHu4s1Du5fYlE4dH/22GeybGpfdMfNdDbL08g1gMD2RvmUpsvHQBUIQuwlI76wNswIsl9LD0VkNGLy6Lw401GIBMw3nE/5tOqaNtO5knYJ5NswlkJ/Fnlt1ExUGD2NmEDQJ0mSvu0Bp6yZt4IIWXAIqvgtSJPRKOdc1WITisyrIz7v62IKflJWGl70yQmrK2+nJWzIrjnCu34sVp2UoMu3AhUOcLbx9QeBKu2WRHI8jl00c6I0z002J6MvCOvVzxBUbiN4QlqayFz70wrfDCf2riYPY9Iwcjb8xE6b42PeWrpLnHg2gbTLHOtxf+wGWiiPv0QXvWT9jelaQ7bLKbZ+tngC4=) of how you can achieve what you're looking for.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
