### ISSUE TITLE
feature request: v-select tags

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#1705]
Currently v-select tags is always using multiple, it is nice that we allow user to have user input, but it would be even nicer to have something that takes user input if it is not in list but not always allow multiple value. Maybe a prop for multiple or not?
Also, if user input is not found in the list, it would be nice to have  the top list element being the text of user input or at least says something like 'Press Enter' or 'Create custom input' and so on.

**Comment by johnleider** [comment]
Please follow the specified feature request boilerplate. Re-open a new issue with it, thank you.
