### ISSUE TITLE
[Bug Report][3.1.12] component error: Tooltip (3.1.12)

### ISSUE THREAD

**Issue by Col0x** [vuetifyjs/vuetify#17059]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.13
**Browsers:** Opera 96.0.0.0
**OS:** Windows 10

### Steps to reproduce
I simply copied and pasted the code available on the site:
https://vuetifyjs.com/en/components/tooltips/

and I get this error:
Uncaught (in promise) TypeError: globalStack.at is not a function

picture:
https://zupimages.net/up/23/13/1vyy.png

### Expected Behavior
it is expected that the component works properly.

### Actual Behavior
the component works every other time and spams the error logs.

### Reproduction Link
[https://codepen.io/Col0x/pen/WNgqgJB](https://codepen.io/Col0x/pen/WNgqgJB)

**Comment by websitevirtuoso** [comment]
Please check your code before postins issues.
![image](https://user-images.githubusercontent.com/5112918/229433707-58078e8f-7bc5-4ce0-9b8a-caf803aa8290.png)

You use vue2, and vuetify 2. update and it will work

**Comment by websitevirtuoso** [comment]
can be closed
