### ISSUE TITLE
[Bug Report][2.6.1] v-data-table expand only works with 'show-expand'

### ISSUE THREAD

**Issue by laventnc** [vuetifyjs/vuetify#17053]
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.1
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click the expand button on the first row, nothing happens. Put 'show-expand' in the table props, and now the 'expand' event handler works.

### Expected Behavior
I use props on the items (`children`) to determine if the expanded item should show. In some cases *(like dynamic data in the expansion)* I pass `show-expand` to tell the base data table component to show all expansions. I would expect the expand functionality / isExpanded props to still work regardless of whether the show-expand prop is there.

### Actual Behavior
Expand functionality only works if 'show-expand' is in the props. Can still manually trigger expansion through the `expanded.sync` prop, but not through the `item.data-table-expand` slot props.

### Reproduction Link
[https://codepen.io/laventnc/pen/MWqMeyB?editors=101](https://codepen.io/laventnc/pen/MWqMeyB?editors=101)

**Comment by nekosaur** [comment]
You can use `@click:row` to manually trigger expand. https://codepen.io/nekosaur/pen/poxzMRZ?editors=1010
