### ISSUE TITLE
[Bug Report][2.6.14] Maximum call stack size exceeded in treeview then children has same id as parent

### ISSUE THREAD

**Issue by Glifaus** [vuetifyjs/vuetify#17065]
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.7.14
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OSX

### Steps to reproduce
When select the parent node, there is a Maximum call stack error. I get data grouped by categories, so the categories can have same id as a module ( categorie hasMany modules)

### Expected Behavior
Select parent node to select all the children nodes withour errors

### Actual Behavior
If has different id works fine, but with grouped data this is a problem.

### Reproduction Link
[https://codepen.io/glifaus/pen/vYzoOYa](https://codepen.io/glifaus/pen/vYzoOYa)

### Other comments
If there is another fix, or im doing something wrong, please tell me. I dont find so much information about this error.

**Comment by KaelWD** [comment]
IDs must be unique.
