### ISSUE TITLE
[Feature Request] [v-datatable] Whenever an internal item changes, an update event needs to be emited

### ISSUE THREAD

**Issue by XieWeiJie** [vuetifyjs/vuetify#17066]
### Problem to solve
Whenever an internal item changes, an update event needs to be emited

### Proposed solution
Can the component provide an event for internal item changes Or are there any alternative solutions？ Ex: current-items Event in v2

**Comment by websitevirtuoso** [comment]
It can't be done with details. because right it doesn't make sense
