### ISSUE TITLE
[Bug Report][3.1.12] v-checkbox have no update:model-value event 

### ISSUE THREAD

**Issue by mw-shub** [vuetifyjs/vuetify#17064]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Edge 111.0.1661.62
**OS:** Windows 10

### Steps to reproduce
The v-checkbox according to documentation: 
https://vuetifyjs.com/en/api/v-checkbox/#events 
only have the [click:append, click:prepend, update:focused] although non of them achieves the purpose of update:model-value.

### Expected Behavior
to add that specific event handler

### Actual Behavior
Can't detect changes using the current events as I expected.

### Reproduction Link
[https://codepen.io/mw-shublaq/pen/ExeBMLB?editors=1011](https://codepen.io/mw-shublaq/pen/ExeBMLB?editors=1011)

**Comment by sohepalslamat** [comment]
I tested it, it is working no problem.
For Reproduction Link: https://codepen.io/mw-shublaq/pen/ExeBMLB?editors=1011
you use vue2 nd vuetify2 
![image](https://user-images.githubusercontent.com/36170722/229366393-0a5da76d-fb84-4181-bf5d-57f6e627b8e8.png)
