### ISSUE TITLE
[Bug Report][3.1.12] VTextField variant outlined custom border radius not working

### ISSUE THREAD

**Issue by irsyaadbp** [vuetifyjs/vuetify#17076]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Custom border radius not working in text field variant outlined but in other variant and button is working

### Expected Behavior
All component can custom border radius

### Actual Behavior
Currently i only found in text field variant outlined not working when custom border radius, I haven't tried it on other components whether it happens or not

### Reproduction Link
[https://codesandbox.io/p/sandbox/funny-darkness-fwwl9u](https://codesandbox.io/p/sandbox/funny-darkness-fwwl9u)

**Comment by irsyaadbp** [comment]
I suggest to add this css
```.v-field__outline__start

**Comment by irsyaadbp** [comment]
I suggest to add this css
```
.v-field__outline__start {
    border-top-left-radius: inherit;
    border-bottom-left-radius: inherit;
}
.v-field__outline__end {
    border-top-right-radius: inherit;
    border-bottom-right-radius: inherit;
}
```

**Comment by websitevirtuoso** [comment]
I think this is not bug. 
1. Documentation here
https://vuetifyjs.com/en/api/v-text-field/

We have 
sass variable for border-radius
[$text-field-border-radius](https://vuetifyjs.com/en/api/v-text-field/#sass-text-field-border-radius)

2. Use css on
.v-field
and set your border-radius

**Comment by irsyaadbp** [comment]
> I think this is not bug.
> 
> 1. Documentation here
>    https://vuetifyjs.com/en/api/v-text-field/
> 
> We have sass variable for border-radius [$text-field-border-radius](https://vuetifyjs.com/en/api/v-text-field/#sass-text-field-border-radius)
> 
> 2. Use css on
>    .v-field
>    and set your border-radius

yess, i use option 1 to customize border radius, but when i tried all variant except `outlined` is working
```scss
@use "vuetify/settings" with (
  $border-radius-root: 16px,
  $text-field-border-radius: 16px,
  $button-text-transform: cappitalize,
  $button-height: 44px
);
```
<img width="558" alt="image" src="https://user-images.githubusercontent.com/23293993/229988573-0173fe99-1d2f-4fcd-82c6-28f6a935d7c2.png">

**Comment by websitevirtuoso** [comment]
Yes. this is correct I think outline made a bit differently.
When set .v-field__outline__start it works

**Comment by irsyaadbp** [comment]
it can be solve without add css
```css
.v-field__outline__start {
    border-top-left-radius: inherit;
    border-bottom-left-radius: inherit;
}
.v-field__outline__end {
    border-top-right-radius: inherit;
    border-bottom-right-radius: inherit;
}
```

You must wrap the layout with `v-app`, but in the documentation not mention it https://vuetifyjs.com/en/features/application-layout/#placing-components
```vue
<v-app>
   // ...
</v-app>
```

**Comment by websitevirtuoso** [comment]
<v-app>
must be set, this is root component. Many things can't work without it.
