### ISSUE TITLE
[Feature Request] Use the v-data-table-footer outside of v-data-table

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#17072]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.36
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
* create new vue component
* add the v-data-table-footer
I am getting this errors :
[Vue warn]: injection 'Symbol(vuetify:data-table-pagination)' not found.

### Expected Behavior
`v-data-table-footer` needs to be able to use it by itself.

### Actual Behavior
Getting this error :
[Vue warn]: injection 'Symbol(vuetify:data-table-pagination)' not found.
When using the `v-data-table-footer`

### Reproduction Link
[https://codepen.io/mtermoul/pen/VwGoQgg?editors=1010](https://codepen.io/mtermoul/pen/VwGoQgg?editors=1010)

### Other comments
In vuetify 2, I use to be able to use the v-data-footer component without any issues. However it seems that in V3 the `v-data-table-footer` component can only exists within the the `v-data-table` . I think that there are instances where there is a need to use just the `v-data-table-footer` by itself. 
Here is a code snippet on how I used the `v-data-footer` component in Vuetify 2.
https://codepen.io/mtermoul/pen/MWqNVoG?editors=1010

**Comment by nekosaur** [comment]
The current version of v-data-table-footer in v3 is limited to be used in v-data-table components. This might change in the future, but it's expected behavior and not a bug.
