### ISSUE TITLE
[Bug Report][2.6.3] v-autocomplete hide selected with many items does not show all items without scrolling

### ISSUE THREAD

**Issue by whoptidoo** [vuetifyjs/vuetify#17085]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
click the autocomplete and add all items in the list, notice that the actual list contains 40 items
and only 20 can be added before "no data available is displayed."

### Expected Behavior
All items in the list should be possible to add this way.

### Actual Behavior
All items are not available unless the user scrolls the dropdown before adding all items.

### Reproduction Link
[https://codepen.io/whoptidoo/pen/NWOKYLj?editors=101](https://codepen.io/whoptidoo/pen/NWOKYLj?editors=101)

### Other comments
This example is from the Vuetify docks  the only difference is a list of more than 20 items and hide-selected

**Comment by creage** [comment]
@KaelWD This change fails our tests

```ts
TypeError: Cannot set properties of undefined (setting 'scrollTop')

      at node_modules/vuetify/dist/webpack:/Vuetify/src/components/VSelect/VSelect.ts:757:38
      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)
      at runAnimationFrameCallbacks (node_modules/jsdom/lib/jsdom/browser/Window.js:603:13)
      at Timeout._onTimeout (node_modules/jsdom/lib/jsdom/browser/Window.js:581:11)
```
