### ISSUE TITLE
Feature request - Callback for no-data-found row item in v-select

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#1708]
Opening up a callback to the no data found row would be very helpful, particularly when using the autocomplete prop. It appears that MaterialAngular gets around this by setting a click handler in a no-results template slot (vs a text prop)

**What will it allow you to do that you can't do today?**
For example, you could use callback to take the current input value and add it to the v-select items array, and could be used in conjunction with additional logic to display a separate "add {{currentValue}} to the list" when the result returns nothing, vs the items array was empty to begin with. Easily adding an item to a list that wasn't available before is typical Combo-box behavior, and this would be an easy way to enable that feature to the v-select component.

**How will it make current work-arounds straightforward?**
I had to implement my own row logic manually

**Comment by johnleider** [comment]
Could you provide an example of what the implementation could look like?

**Comment by zcuneo** [comment]
[Buefy](https://buefy.github.io/#/documentation/autocomplete) offers an "empty" slot when no data is found. 

Here's how it might look in Vuetify.
```
<v-select
  autocomplete
  label="Select a customer"
  :items="customers"
  item-text="name"
  v-model="project.customer"
>
  <div slot="empty">
    No customer found... <br>
    <router-link to="/customer/new">Add New Customer</router-link>
  </div>
</v-select>
```

**Comment by johnleider** [comment]
Funny enough, I added that very functionality for https://github.com/vuetifyjs/vuetify/issues/1304. Will go out with next release.

**Comment by zcuneo** [comment]
Thanks, John! How would we go about using the new functionality today in vuetifyjs/vuetify#dev? I've tried adding <template slot="no-data"> to the v-select element to no avail.

**Comment by johnleider** [comment]
Keep in mind, if you are using current dev, you still have to **build** it as I do not commit files in the **dist** folder when in dev.

Once you've done that, just use the slot - `slot="no-data"`

**Comment by zcuneo** [comment]
That did the trick. Thank you for your effort and on this incredibly useful project and helpful support to boot!
