### ISSUE TITLE
[Bug Report][3.1.12] Playground and Codepen broken

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#17081]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.3.0-alpha.8
**Browsers:** Firefox 111.0
**OS:** Linux x86_64

### Steps to reproduce
Try to access any codepen sample or the official playground

### Expected Behavior
It should work

### Actual Behavior
I get two errors

> Loading module from “https://unpkg.com/@vue/runtime-dom@3.3.0-alpha.8/dist/runtime-dom.esm-browser.js” was blocked because of a disallowed MIME type (“text/html”).

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/@vue/runtime-dom@3.3.0-alpha.8/dist/runtime-dom.esm-browser.js. (Reason: CORS request did not succeed). Status code: (null).

( I also tried older Vue versions )

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdkMsSgjAMRX+FyZq2PjYOK//DukCpWqWPaQqOw/DvtoAzCOrCZXKTe3Kza0Aqa5wnKrf0ikZDBg3XScIHATlkSdeJvboSseZw8d5ixlil7e1Mj0axbdCYq7SXSpDCqO2arumC5KW95HTDCol+LFOBihycuaNwAcwhHTG8PD2+cQY52C/pctX7Dj1S5geMxjNDFii1cMQJXQgn3M8Qk9lPQSYjszAR3XLdQgql1DecvPaI3Vt3rwv/SNlZxP19xLQpvF0ZuP0m7J/W56E4)

**Comment by MajesticPotatoe** [comment]
This is a cdn host issue.
