### ISSUE TITLE
[Bug Report][3.1.13] v-lcale-provider is missing in v-range-slider example

### ISSUE THREAD

**Issue by jnz31** [vuetifyjs/vuetify#17092]
### Environment
**Vuetify Version:** 3.1.13
**Vue Version:** 3.2.47
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
load the reproduction link. the range buttons simply stay in the center.

### Expected Behavior
the range buttons should update on change

### Actual Behavior
the range buttons stay in the middle of the form

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUstugzAQ/BXLp1bCuHlIlRCN0u8IOTh407rFxrINTRXx710wNK9DcmNm7ZnZwZsjfbc2bRugGc0DaFuJAKvCEJK3rBRODt//iAU4hJEaSCfMBzBfKQluoglpma4lVG8FbUXVQEFPIx+cKsOEVzm/1JjskL70mxgEOT8LitCXTtl4Cg62doFI2IumCuQY1aQIgjw9T5AQB6Fx5oQxcZ8zI5v5S0KWL9tkmnTxoxsIBDkf3WhCK2W+ffrla4PlDVoFLb0vKOrEawX9DMH6jPNSGjyJnajWpQYCN1ZzrD2o/e96kc7S2YJL5cPEsUrsfDqo9VLbwnToqHS/HtPCXtnGwWA9LoXV98Vn9zKs8Rh3jQlKA5O1xjDzdPkaw5zxKXjNdq7+8eBQpaBjRYNPn/gBr7v7oseNNkfDFhxzYPB94Ct7cKeraxd7Xc1udht/dke7hMZ7WH5MTbd/aZgKQw==)

### Other comments
i'm completely new to vuetify so appologies, if i got this wrong. but in the example above, the slider buttons are centered and not moving, when you change the values. it took me some time to figure out the issue, but it seems, that v-lcale-provider as a wrapping component is missing. i fixed it in the following [example](https://play.vuetifyjs.com/#eNq9VEFu2zAQ/ApBFGgCmJTdtAhgJEH6gR56tXxgpLXNliIJcqXYCPz3LsmoUZygCYqiumlmdnd2KGr1wL96L4ce+JJfIXTeKISb2jJ6rgZhXKMMCB/coFsImaixRqKCslsQ0SS86AfRuRbMdc0zV/MCLzu1J2wxfwK0JUBMkIjgk2YEdtRVtIBKm1iQxqgYSaKM3lrRgEUam9Wj29E9+YjG4dIH8GDbRzqvg7BHsdFg2hFMbpJpMSjTw2h9NV+PTl53k56o7ZayMdrCE4gHn7rYvrsb/ZVnUEEri8S5HlNNO2VbsFHjgdjGdV41OCUjHkxqeq9b3C3Z5dzvp/Rts0ueSdD7lvb/nt7O5jP2AQaKSaIKW0CZFzx/Kry5qqaBjClWpx/BaazK/3Wqi/+c6hvB/TH011Nd/JNUk2Z6fX6DL6/bs0p6jU3QHlkE7D0huvMuIHsIsDmyTXAd+0h3+WOSNs5GZHkMu2YkOFuR+y/r80RuetugdpZNl9O2hf2MMk0rsYdkqjSxcJ8V1Gclpcw9y+brJBrpVW6wJtW3fFBnj+GQZFJC9FhQ22PasOx0w2ecTvBnlD+is/Q7ygbobGKs+ZKtSpI13yH6uKyqprWkpI9MD0FawMr6rqLlUW8OtxdyIRcXVasjjpgw6i7K3C21IudHmlgCFJ3yJ2MLkUdnJGHUKb2/4eGWZFXoLeqOvm/XkZlP8vNlMTPBJcRO3AV3HyFQl5rPJnOS43fMenNfmvGid0UDBwgi0D2GkC7U+3Y6KXu21wn3Yrc0ng77yI8zXuoo/OKar38B/Xwe6Q==) 
i'm not sure, if this is the supposed behavior and my fix is correct, or if there should be a default setting, that is currently missing. i suppose, it is the second one, ltr, but i can't make that decision.
and yeah, the $set functionality is not working ether and i fixed that in my example, too.

**Comment by websitevirtuoso** [comment]
About $set yes it doesn't work. Error in documentation.
About your reproduction link. I have no idea why it doesn't did you try to use this example in your project?

I have project and use this v-range-slider without issue
It looks like
![image](https://user-images.githubusercontent.com/5112918/230163798-e0d03110-4a0e-44fb-a875-f12b2de897a1.png)

Maybe issue playvuetify but I am not sure.

**Comment by jnz31** [comment]
did you check the example? on my machine the index buttons are centered and dont move a bit. and the css selector, that sets the position is `.v-locale--is-ltr .v-slider.v-input--horizontal .v-slider-thumb`, hence the `.v-locale--is-ltr` part. that css path is only set, if i place the element inside `<v-locale-provider>`...

**Comment by nekosaur** [comment]
use `<v-app>`

https://play.vuetifyjs.com/#eNqNUktugzAQvYrlVSvFOD+pEqJReo6QhQOT1i0YyzY0VcTdO9gQErJIdn4z9vvMeHemH1pHTQ00pomDUhfCwSZVhCQNE1r7oweZMHmPLpg5OLlL0ZeNUJ/AbCFzMGODkIaVVQ7Fe0obUdSQ0uumdUZmbqxsEn7LNApjY6o81IJtBMF3wq/yILSZkTq8gZOujCM5HEVdOHIOPLlwgry8DpAQA642asSYovMek91yPiPr+X42dNpwaH0BQcJ7NTqjhVQ/Nvq2lcIZe66UZtamFHnCs5R+OadtzHmWK7yJc5KNiRQ4rnTJcTtOHv+2q2gRLVY8l9YNNVaIg408W0e1T1WLirLs4rFS6IlsaHjpPhSuo1tG/MjDFq9xUysnS2B5VaKZZbR+C2au6hHYkh1M9WvBIEtK+xF5nc7xE1oP86LGHTdHwQYMM6Dwv+DfezLT5NlNrknvLlu/7Ja2Mxre4fCDa7r/ByEZE0I=

**Comment by jnz31** [comment]
that works. thanks.
