### ISSUE TITLE
[Bug Report][3.1.13] VSelect - Options Menu becomes stuck if nested menu activator is deleted

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#17094]
### Environment
**Vuetify Version:** 3.1.13
**Last working version:** 2.6.14
**Vue Version:** 3.3.0-alpha.8
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
* Click the select
* Click menu on option
* Click delete
* Click confirm

### Expected Behavior
The select menu should close or at least close when blurred

### Actual Behavior
The menu is actually stuck open indefinitely 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVE1v2zAM/SuCdmgDxPKCXIYsHTJs12GX3eIcHJtGtdqSIMluiyD/vaQcF7EdJwV6siny8T1+SNsD/2mMaGrgK772UJky9fAjUYytmyg1JvwGo0qlOlnBdlBC5lmZ7qF8SPg/cD7hbCUxiUM7fBP+jkBMl559ISfGHBj9zJmx2jh27EUHjlI6H1EMa6K9VDliQuwgspcbRYPKB/62AlD16LyPzbxsUq9tEHdZ1lnCvVdjYX+QZR0H5yWyuNfkUcostWPt1/V/ooZrdfzG+WI+6v50OTdLulXWmYJNVsrsCRVo1XLfE7ew6fMM5fzSqpD2ppRrHUTn1ApM4SYwEyVT9PvKnm/+OJxC2xvU3TBi6q4YGe3l60HRdJmVxjMHvia3rIy2nh2YhYIdWWF1xe7wNt8lKtPK+TA+xx7If79d7GbfKQvxFbXCRdGK9bo9Y4dOYUCKJi1rEM7gaNqI7giXBV7+Fi1qzhaUmWBH0tyqRH18zluJWJsR/51W+M4ECnwhggNXbdWRJhylk53wR++NW8VxliuE5VDKxgoFPlamijcYFttaeVlBlOtqsxRL8TVKS/OYim9xjiM4dwtwVbS3+tmBxWQJn5/ReVm8foDyFIlMC7FYthSnswifQEcco9wxEjZgI4sPEliwHy1tALtU3iBkVCKpwFEccQClVE9u0PvMhb5vO7Gfqz1ko1Q7YjzOeU8wSmiRfPcG+1nqBQ==)

**Comment by crThiago** [comment]
I know it is not a better solution, but you can add setTimeout in your delete function

```
<script setup>
  import { ref } from 'vue'
  const items = ref([1])

  function onDelete(item) {
    setTimeout(() => items.value.splice(items.value.indexOf(item), 1), 1000)
  }
</script>
```
