### ISSUE TITLE
feature request: allow :to prop on v-carousel-item | add possibility for any child component of carousel

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#1709]
It would be nice if v-carousel-item would follow same handling as `v-btn` or `v-list-tile` or any other link-able items.

Beside that it would be helpful if `TITLE` and `CAPTION` would be added to the v-carousel-item to show some more information on the items.

It would bring be to the idea, to make an `AnyThingSlider` component which would allow any child component to slide.. Any thoughts about that?

**Comment by johnleider** [comment]
After reviewing this, I truly like the idea, and it triggers more updates that I want to do. Unfortunately, that means I'll need to push this out to 1.0, but it will be done.
