### ISSUE TITLE
Modal on toolbar blocks entire content

### ISSUE THREAD

**Issue by hansroh** [vuetifyjs/vuetify#171]
I am a newbie to Vuetify and Vue. These're so wonderful.

Anyway,

Modal on toolbar blocks entire v-content.
I think modal's .overlay layer blocks it.

The floating button can't be clicked in below example.
Then I should set display: none to #header .overly at app mounted.
 
    <v-app top-fixed-toolbar id="app">
      <header id="header">
        <v-toolbar fixed class="indigo" id="main-toolbar">          
          <v-modal v-model="location_modal">
            <v-btn slot="activator" dark flat class="indigo lighten-1">
              Location
              <v-icon class="grey--text text--lighten-2">expand_more</v-icon>
            </v-btn>
            <v-card>
            <v-card-title class="indigo darken-1 grey--text text--lighten-2">
              <span class="subheading">Modal</span>                  
            </v-card-title>
            <v-card-row actions>
              <v-spacer></v-spacer>
              <v-btn @click.native="location_modal=false" flat><v-icon>close</v-icon>Close</v-btn>                                
            </v-card-row>
            </v-card>
          </v-modal>        
        </v-toolbar>
      </header>
      
      <main>        
        <v-content>
          <v-container>
            <v-btn class="red lighten-1" floating dark @click.native="alert ('Upload')" large>
              <v-icon>file_upload</v-icon>
            </v-btn>
          </v-container>
        </v-content>
        
      </main>
      
      <footer>
      </footer>
    
    </v-app>
  
    <script src="js/vue-2.1.10.js"></script>
    <script src="js/vuetify-0.8.10.js"></script>
    
    <script>  
      vapp = new Vue({
        el: "#app",
        data: {
          location_modal: false,
        }  
      })
    </script>
    
Thank you for your works.

**Comment by johnleider** [comment]
For this situation, you should move modal out of the toolbar and programmatically open it. When it is in the toolbar, and the toolbar is fixed, it has a z-index of 4. This makes the overlay  take a higher priority than it normally would, even though it is at -1.

**Comment by hansroh** [comment]
It works!

Thank you.
