### ISSUE TITLE
[Bug Report][3.1.13] v-carousel is always continuous (:continuous="false" doesn't work)

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17109]
### Environment
**Vuetify Version:** 3.1.13
**Last working version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set `:continuous="false"` to `v-carousel`

### Expected Behavior
It shouldn't be continuous anymore

### Actual Behavior
It stays continuous

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVMFO4zAQ/ZWRpRUg1UkLSCtV3RV74QfYG+nBxJPG1HEi2ymgKv/OJE7bxBzglMyb8Zs3Mx4/H9m/pkkOLbI123isGi08/s0MwObAc2Hr1qHuTYB1XhuvTEvQn4wVQjvMWHCVqHalJ/R+uTxjSiKXqFWlPFr+IvL9juiM7N1DhlkOTlFVQAEOvKgt0V07TSwLUDegDAyGO/GToD1+UJA6ISPpQOtKRH+yB+16YBy+7lltLzQT+avl8tfFceYjRqkOkGvh+tIlLzS+Q6G05uEovLbOq+KD52ioWBBa7cxoZGzCEzF5fPe8vI1CAI7HUCx0HTz1PzOGlCim2mb2Jh2LP7WY7FmPw3AnKAGbdDJ6Ml1uVRMY8L2prQeJhWi1h2NglcILuL45mQAWfWvNxQYInV7D81T7lTJS7eqrxQx8E9Yos4vQRpk9JbJ7NPw28lmUQD0uPflWkU8iNrxpbaMRRN4Pgd9PQ7aT/3ClYpGPyjofsT4hXX8Zgf9LZWPssW6tL2NQFXPsIqILP90AkLFJx+6zBdPUApe8utrQeg69pRvsaAXOijNWet+4dZrm0lBkv3AHmxj0qWmqlBa7v5cPd8kqWd3RRXH+hHEtXlwysPVU28x0lFFV/bh5JZoobXAMqcchZ4yYevsbDQ8UltqW3o6KHoS6IjG3yf3vIGaCJ+gq/mLrN4eWWDI2tmjI0yv+Qa5v66UcX7hTSnigJ8qikWj7jf1ZTdGxWV2R70tt47A71i1YOEfND6rZ9hMIVrGC)

### Other comments
https://vuetifyjs.com/en/api/v-carousel/#props-continuous

Suppose to work like `v-window` [here](https://play.vuetifyjs.com/#eNqNU9tuozAQ/ZWRtQ+tFEPSrLQSSqvuN+xjqVQHJsGtsZFtSKqIf98xhkLTh/aNOeM558yFpwv72zRJ1yLL2M5j3Sjh8SHXALuOn6QuzSkEAFlhtJe6Na27z9lBKIc5i6mO16ZERbDReyNsKfVxyrnKnLiw1pxCWWU6tDE1aCxUuCT1iAXGg7H0XoPUoFAffTURkpM3fKfcS0FK/NdF9y9TbuQcWEN2CgFQYSe8NJoK72YqgArlsfIBXa+XeKGEC45LflB4BqHkUfMCtUcLr63z8vA+hbXgC8oPD+Si2szBTOnx7Hn1ycWiCOCfkiXC5QIa+n7BllabucE0djhNkcLFGOP+PjAKd+litxS6wsrGD+/w3BjrocSDaJWHS2QshRcZ3NzC/QPcjBiMq8hgu5qQeeMZrEe0vx0+yPsuHYXYiimp31zy6oymUxsYc1Y4l7MMnmId3Yf3jcvStCg1vaSbkp1NNPpUN3VKRxrG/rhNNslmm5bS+QnjSuxdMrAFqudc96Qo69AZr0VzJRsTg/TYWs6IKcTfeHikZ6lt6U+okZemJjN3ye8/0cwCT9DVfB+uHi2x5GwczaATHP9A69t+SeMLd0qC9I9xi7pEG362n/V0Vfapr6vcl97GZfesX7FYR8OPrtnzfynXYig=)

**Comment by kappaflow** [comment]
Do you plan to fix this regression bug in near future? And maybe can suggest a temporary fix?

**Comment by SonTT19** [comment]
Same issue with #17586
& fixed in https://github.com/vuetifyjs/vuetify/pull/17587

**Comment by johnleider** [comment]
This works now https://play.vuetifyjs.com/#eNpdksFu2zAMhl+FEDC0BaI4SQMUCLwBu/QFuluSg2bRNhdFFiQ5SxH43StbcWPrZP4/6U8kpf2NOVtkv41ZXlpkO5Z7PBslPP46aID8wgthm9ah6iXArmi0J90G6+eBlUI5PLCYqpGq2gd3u1p9eySRS1R0Jo+W/xXFqQo4Lfv0cMLsDB6qztEFuPCysQH37FSgLIBegDQMwo380NAJP0MRjc4dOmBdjehHPfSuBuLwdXs6PjCT9ter1Y9H4psXiJIuUCjh+tElLxVeoSSlePwV/rXOU/nJC9RhWBCKKn0XBzbhJCSPV8/rTVICcLvFYaHr4KMPZoQsIKa9zXSe3YcfVxz0bMfxciduMPJscvVBusKSiQS8msZ6kFiKVnm4RaoUXsDzyygBLPrW6ocGiJvewX7a+xNpSVXztJiZ/4XVpKvENaRP4SB7Qs03Sc6ihLDj2ofcOslJRMNNa41CEEV/CXw7LTlO4vik0ibfyTqfUD8wPH+ZmH9qsqn33rTW16lJ5dx7NNHFoBuMIPLsvn3WLdjrcrPcvrE+eF2u39jxCzLADQo=
