### ISSUE TITLE
Incorrect behavior of the v-data-table component option

### ISSUE THREAD

**Issue by DanilChugaev** [vuetifyjs/vuetify#1710]
### Steps to reproduce
https://codepen.io/DanilChugaev/pen/veYrKw?editors=1010

### Versions
- Vue version 2.4.2
- Vuetify version 0.15
- OS Windows 10 Home, x64
- Browser Google Chrome 61.0.3163.79

### What is expected ?
The component `v-data-table` has a option - `select-all`. Depending on the settings sent, I want the value to change dynamically: true or false, because some tables have checkboxes and some do not have them.

### What is actually happening ?
When I pass a Boolean value false, the main checkbox is hidden without errors. When I pass a Boolean value true, errors occur, eg: 

> Invalid prop: type check failed for prop "color". Expected String, got Boolean.

OK. I pass the value string true, and the main checkbox is shown without errors. Why?
How do I do so that without resorting to hacks, like this `selectedAll: this.hasCheckbox ? 'true' : false`  dynamically change the value?

Why in this file 

>  vuetify/src/components/VDataTable/mixins/head.js

 is such a check `this.selectAll === true && '' || this.selectAll`? Such a check seems strange to me.

### Reproduction Link
https://codepen.io/DanilChugaev/pen/veYrKw?editors=1010

**Comment by johnleider** [comment]
The reproduction steps are not very clear. It's just a data-table. I have no idea what I'm looking for here. Could you please update?

**Comment by nekosaur** [comment]
Set `selectedAll: true`. This is strange though cause I remember fixing this exact problem before.
