### ISSUE TITLE
[Feature Request] [Question] How to publish vue component for vuetify3?

### ISSUE THREAD

**Issue by logue** [vuetifyjs/vuetify#17118]
### Problem to solve
I created an extension component called [vuetify-swatches](https://github.com/logue/vuetify-swatches/tree/vuetify2) in Vuetify2, but when I rewrote it for Vuetify3 and built it without including 　Vuetify code, there was a problem that the component was not output correctly after building. Did. Vuetify components are not converted, and raw Vuetify tags are output.

Since it can't be helped, the version `1.3.10` currently being distributed includes the Vuetify code.

### Proposed solution
How to write vite.config.ts that allows externalization of Vuetify3.

**Comment by KaelWD** [comment]
`external: [/^vuetify/]`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
