### ISSUE TITLE
[Bug Report][3.1.13] VSelect placeholder doesn't hide when not focused

### ISSUE THREAD

**Issue by 6XGate** [vuetifyjs/vuetify#17113]
### Environment
**Vuetify Version:** 3.1.13
**Last working version:** 2.6.12
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1. Checkout the demo repo and install the dependencies.
2. Run `yarn dev`
3. Goto the URL from the vite dev server.

### Expected Behavior
While no item is selected, the VSelect will show only the label when not focused. It will show the placeholder when focused.

### Actual Behavior
While no item is selected, the VSelect shows the label and placeholder overlapping.

### Reproduction Link
[https://github.com/6XGate/vselect-placeholder-bug](https://github.com/6XGate/vselect-placeholder-bug)

**Comment by marjev** [comment]
@6XGate Hopefully, my PR #17115 will fix the issue. Stay tuned.

**Comment by johnleider** [comment]
fixed by https://github.com/vuetifyjs/vuetify/pull/17122
