### ISSUE TITLE
Tab bar arrows are not visible for dynamically added tabs

### ISSUE THREAD

**Issue by filipsobol** [vuetifyjs/vuetify#1711]
### Steps to reproduce:
- Add few tabs, but not enough to make pagination arrows visible
- Dynamically add few more tabs, some of which will not be visible

### Versions:
- Chrome 61.0
- Vuetify 0.15.6

### What is expected:
Pagination arrows should be created for dynamically added tabs

### Reproduction link:
https://codepen.io/anon/pen/XeWBKQ?editors=1010 - Click on "Add 20 tabs". Notice that arrows for 2nd tab bar are visible, because pagination is required from the beginning.

Edit: Pagination arrows appear after pressing "Add 20 tabs" and resizing the window (for example by opening Chrome Dev Tools).

**Comment by johnleider** [comment]
This is not something that can be automatically done. There is no way for a component to watch the length of its own children, so there is no way to detect the change.

I've attached a way to handle this specific use-case. You must have the bar re-evaluate.
https://codepen.io/johnjleider/pen/GMgWez?editors=1010

**Comment by nekosaur** [comment]
I actually think this should be possible, since we're using inject/provide to allow VTabsBarItems to register themselves.
