### ISSUE TITLE
[Bug Report][3.1.12] V-combobox zero value is not displayed

### ISSUE THREAD

**Issue by FrontDev07Axas** [vuetifyjs/vuetify#17120]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.3.0-alpha.6
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
follow link|
select 0

### Expected Behavior
v-combobox selection display 0

### Actual Behavior
v-combobox no display #selection slot

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUUtuwjAQvYrlDSARG0rFAkEF5yAs8jHg4p88Di1CuXvHDkgptF10lzdv/D6T7ZVunGPnRtAFXQahnSqCeMsNIctzVjiXPhPQhTQ3lHBldWlL+0mQsrVQq5xqOOSUVKoAQOTKbDpHvJCoGwcyaAE44HdR3lONoPNb8l4OhFB56QIBEZpIS+2sD+RKvNiTluy91WSABQZxubIGAsEcZBX5oWmUGt3HyR+JLWNs431xGb5ORuwkLjAc7aJv54QedEw7G8zn2DtYg+e5xpjYIhHYY0HSJM7QPuKcHkNwsOC8Me50YHgivkaO+8YEqUVWW72esRmbZIVyx4LNeS0h9GkmQGeltx8gPBrndNzzCHJ/+c3nRqP8lE1fOt3bLFNFCVH4SZCjy1n4zAtTCy/8nyUedn8q8rDyVCZat7lp8b5KmhM8nLaCdNbtPeE/WiaJ+B5/aEvbMf2WEn27l3T3BcQp/RQ=)

**Comment by 1Luc1** [comment]
apparently string values ​​work `const itmes = ["0", "1", "2"]`
