### ISSUE TITLE
[Feature Request] Labs v-data-table body.prepend and body.append slots

### ISSUE THREAD

**Issue by mkampmey** [vuetifyjs/vuetify#17128]
### Problem to solve
Compatibility with existing Vuetify 2.x functionality

### Proposed solution
Add slots for body.prepend and body.append

**Comment by corradopetrelli** [comment]
Related to: https://github.com/vuetifyjs/vuetify/issues/17553

**Comment by datanexus-vincent** [comment]
This is the last v2 functionality that we need to bring our v3 Vuetify app to feature parity. I might have a look at implementing it myself if it isn't too difficult.
