### ISSUE TITLE
[Feature Request] [V-Banner] Let change background color similar to version 2

### ISSUE THREAD

**Issue by tokidoki11** [vuetifyjs/vuetify#17124]
### Problem to solve
Currently setting color prop for v-banner on vuetify 3 change the color of icon and action buttons(?)
whilst in vuetify 2 background color can be change via color prop while icon-color prop is used for its icon color counterpart

### Proposed solution
Let us have prop similar to vuetify 2 for v-banner to let background color change

**Comment by vukoviciv** [comment]
It looks like a bug since it's [documented](https://vuetifyjs.com/en/api/v-banner/#props-color) the same way as in Vuetify 2; but it's not working.

**Comment by dyc3** [comment]
Just encountered this today. On a similar note, `density` also seems to not be working as documented.
