### ISSUE TITLE
[Feature Request] Nuxt 3 module

### ISSUE THREAD

**Issue by NiiightmareXD** [vuetifyjs/vuetify#17137]
### Problem to solve
it fixes the problem having to manually add Vuetify for every project

### Proposed solution
I think we can do this if we combine these 2 articles:
https://codybontecou.com/how-to-use-vuetify-with-nuxt-3.html
https://nuxt.com/docs/guide/going-further/modules

**Comment by MajesticPotatoe** [comment]
duplicate https://github.com/nuxt-community/vuetify-module/issues/475
More details: https://github.com/vuetifyjs/vuetify/issues/14621#issuecomment-1016186592

**Comment by scscgit** [comment]
[@nuxt-alt/vuetify](https://github.com/nuxt-alt/vuetify) module seems to work well
