### ISSUE TITLE
[Bug Report][3.1.13] Form elements do not have associated labels

### ISSUE THREAD

**Issue by valoricDe** [vuetifyjs/vuetify#17132]
### Environment
**Vuetify Version:** 3.1.13
**Vue Version:** 3.2.47
**Browsers:** Firefox 111.0
**OS:** Mac OS 10.15

### Steps to reproduce
Go to https://www.accessibilitychecker.org/audit/?website=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fselects%2F&flag=us and assess current accesibilty issues

### Expected Behavior
That v-select statements render an label and or necessary aria attributes

### Actual Behavior
Form elements do not have associated labels

### Reproduction Link
[https://codesandbox.io/s/quizzical-moore-yrl01t](https://codesandbox.io/s/quizzical-moore-yrl01t)

**Comment by devonik** [comment]
Have this error shown by google web vitals for every v-text-field input says missing label
