### ISSUE TITLE
[Documentation] Material Design icons loading failed by Cross-Origin Read Blocking

### ISSUE THREAD

**Issue by laplacetw** [vuetifyjs/vuetify#17139]
### Environment

**Browsers:** Edge 112.0.1722.39
**OS:** Windows 10

### Steps to reproduce
Open the documentation and check browser dev tool.

### Expected Behavior
The page will display icons with navbar, sidebar, title, etc.

### Actual Behavior
All icons disappeared.

### Reproduction Link
[https://next.vuetifyjs.com/](https://next.vuetifyjs.com/)

### Other comments
Warning message :
Failed to decode downloaded font : https://next.vuetifyjs.com/assets/materialdesignicons-webfont.ef807a6d.woff2?v=6.2.95
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://next.vuetifyjs.com/en/ with MIME type text/html.

**Comment by KaelWD** [comment]
next.vuetifyjs.com is not the current site, use vuetifyjs.com
