### ISSUE TITLE
[Bug Report][3.1.14] VTextField border-radius

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#17149]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.3.0-alpha.9
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Changing $text-field-border-radius value sass (settings.$border-radius-root) doesn't change the radius well, the append part from the input looks bad rounded.

### Expected Behavior
To change the complete input radius

### Actual Behavior
Doesn't apply the border radius well

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1U81u1DAQfhXjy4K0jlu2F0KKyo034FBXK28y2xr8J9sJrap9d8Z2grZbkAqoysWen+/HM7l+pJ+9b6YRaEu7BMZrmeCTsIR0E5Pel2O5GKks6bWM8VJQL9mFoHOypBPcJ7ZXoAeCtW4AjWUm3gpKJhmUtAnvbkxaWRgwyBdkXqErJ14qacePxHQxPWggWtpbBOljnKmbqTIyNlOwheBXarudQ9ttTDIkjGvXSw2Mqch0Cutc+jT0L7jksdrZuTBAYEEOaowt2bz39+QMv3z4KOxBWGFBgwGbmuoKGzH6d5Rgh1cwgqh/sFH1z24WGx0vBsp8+qB8IhHSmIenjHf5SUiAPTmQfXCGrHDHVrmtdzYmgptBLnP+7eoLaO3IVxf08Gb1ruAWOASia1qxcEV88y06i2taJIo5gavQLqIFRY58F/QuJR9bzvvBYhsuo5pCYyFx6w2/wjIeRpuUATY4c7VpNs0Zk9rfyeYDH1RMx+kGomG74H5ECAgm6PqILqn9wwso50pkOm/OLyrFHGNa7mLmeIbNkXDKU8DBQIDwUmsnbb+zd1LyzGJWgUM+4ABwN77Hk7cvv2BLrhex/+e9oGWom8x4WNMnglFC7aQ3PwE975mP)

### Other comments
(The repo is not showing the right result because it doesn't support styles but I let you the classes that are controlling the input radius)

**Comment by websitevirtuoso** [comment]
Please check this thread
https://github.com/vuetifyjs/vuetify/issues/17076
maybe it will help you

**Comment by johnleider** [comment]
In Vuetify 3 the correct sass variable is [$field-border-radius](https://vuetifyjs.com/api/v-field/#sass-field-border-radius)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Jensworth-III** [comment]
> In Vuetify 3 the correct sass variable is [$field-border-radius](https://vuetifyjs.com/api/v-field/#sass-field-border-radius)
> 
> If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

It would be nice if this was corrected in the documentation: https://vuetifyjs.com/en/api/v-text-field/#sass-text-field-border-radius
