### ISSUE TITLE
[Feature Request] v-data-table-server: server side filtering

### ISSUE THREAD

**Issue by schlitzered** [vuetifyjs/vuetify#17140]
### Problem to solve
currently only pagination and sorting can be done server side, but no server side filtering is available

### Proposed solution
i would suggest to extend the header and add a new config called "searchable" that can be set to true/false(default), similar to "sortable".

if searchable is set to true, next to the Title a text input field should appear.
Adding/removing data in this text field should update the "options" object and trigger the update:options event.

the event object will have a new attribute called "search", which is a list.
this list should have one object for each searchable column. that takes the following form:
{"key": "$KEY_FROM_THE_HEADER", "value": "$THE_VALUE_FROM_THE_SEARCH_FIELD"}.

if the searchable field is empty, the object for the this column might get omitted.

whenever a search field is updated, the pagination field should get reset., similar to what is currently happening when the sort order is changed.

**Comment by websitevirtuoso** [comment]
You can always extend it. here How I did  it
```
<template>
  <v-data-table-server
    v-bind="$attrs"
    :items-per-page="pagination.take"
    :page="pagination.page"
    :must-sort="true"
    class="elevation-1"
    data-test="datatable"
    @update:sort-by="sortable"
    @update:page="incPage"
    @update:items-per-page="itemsPerPage"
  >
    <!-- Pass on all scoped slots -->
    <template v-for="slot in Object.keys($slots)" #[slot]="scope">
      <slot v-if="scope" :name="slot" v-bind="scope" />
    </template>

    <template v-if="searchable" #top>
      <v-text-field v-model="rawFilter.search" label="Search" density="compact" hide-details class="px-4 pb-2"/>
    </template>
  </v-data-table-server>
</template>

<script setup lang="ts">
// this component is wrapper to add extra functions to original v-data-table-server
// added prop - searchable
// emits sort, pagination
import { rawFilter } from '@/composables/useFilter'
import { paginationInitial, sortInitial } from '@/components/datatable/index'

defineProps({
  searchable: {
    type: Boolean,
    required: false,
    default: () => false,
  },
})
const emit = defineEmits(['update:sort', 'update:pagination'])

const pagination = ref(paginationInitial)
// sorting
// datatable sorting type
declare type SortItem = {
  key: string
  order: 'asc' | 'desc'
}

const sort = ref(sortInitial)

const incPage = (page: number) => {
  pagination.value.page = page
  emit('update:pagination', pagination.value)
}

const itemsPerPage = (items: number) => {
  pagination.value.take = items
  emit('update:pagination', pagination.value)
}

const sortable = (sortItem: SortItem[]) => {
  sort.value.sort_by = sortItem[0].key
  sort.value.type = sortItem[0].order
  emit('update:sort', sort.value)
}

onMounted(() => {
  emit('update:pagination', pagination.value)
  emit('update:sort', sort.value)
})
</script>

```

**Comment by lioneaglesolutions** [comment]
I don't think this would be a viable solution as it would affect the width of the table columns. If you added searchable to every column, you'd have a title and text field for for every column which would just look horrible.

**Comment by websitevirtuoso** [comment]
![image](https://user-images.githubusercontent.com/5112918/232378725-6eefe746-cdd2-45a5-a2cd-7cf83c4e2978.png)

I think you meant filtering. I have no idea how it can be implemented because every filter is pretty specific.
 On this screenshot is a small amount of filtering which I have. 
 But I think you can customize each table header and create your own filtering system. no one will do this in this package.
 Hope I helped you

**Comment by nekosaur** [comment]
Thank you for the feature request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time. You can use the available slots to customize the table to support things like per-column filtering.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
