### ISSUE TITLE
[Bug Report][3.1.14] V-select should respsect height when use chips inside

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#17146]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. we see diff in height when use chips. When something selected v-select doesn't have to change height

### Expected Behavior
shoudl have the same height

### Actual Behavior
have diff height

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVMGO2jAQ/RXLF1qJJIIiVYrYavfYa9GeyB5MPAhvbceyJ6lWiH/v2IEFAi2sFgSxZ97Mm5lnZ7nlT87lXQu85HME47RA+FHZeZfVjUWhLHjaMkYG3/xJy7SpG83oFx4qPplWnBlJq1nF94iECaChxoOh/5SKWGJUela8shUev6VpJOisE7qFmDn6T6O1WIEmR920Fv3b0C3BBoVvCWCcIO4BoBNeCYsEaFrU1JwcIkyrUTkN59Z6o1wYmDQIL1ZD5EZJyCTQ5PQgIDacoUIdO7PCwJA6AQ6tq4vKpECRIYRY/VppBJ+3gf76WShIwzzCi4NWRRLrTuUqvKpblyVhCJie50yXkt4p2FW5jofhlljXpLoQ6qpM/xLphkT/FehD8lwTJ64PV6y3H+/fvDi5m7QNtVcOWQBsHVmUcY1HtmUe1mzH1r4xbESXepQktRqQJd3YQ0R8+dqbiSBgaiqQY7mNViVLNhlHFWL7JRs9L54oy2787p2een89LxY/E+AlFtmXRQXxMe9ryoxw+WtoLL1fUgoaXHLQOEqWLNFGtcZ9xTeILpRFUUtLYVSy6nxuAQvrTPFIsMLTOJUh+Rrz+C2f5rPvhVQBT+05BJOtaJZx/q/ERCW/86Ba0zG8ybVHEsUkn8x6ir0to0MdIsdF7oIIO/CZByvBg7+3p0HYWV8D30VvkX5HAtDI6Y78DoNp1yFNenmo8nNNp2wxFcm947sx7ysl7j6Ev/wFqxT16Q==)

![Peek 2023-04-13 12-04](https://user-images.githubusercontent.com/5112918/231858778-8859dc24-e2d3-4bc5-97d3-498240883567.gif)

**Comment by yuwu9145** [comment]
#17130 15980

**Comment by websitevirtuoso** [comment]
Yes I see that after 15 releases we still have this bug
