### ISSUE TITLE
[Bug Report][3.1.14] `title` in `v-tab` doesn't show up

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17155]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add [`title`](https://vuetifyjs.com/en/api/v-tab/#props-title) tag to the tabs
2. Hover the tab with your mouse

### Expected Behavior
Suppose to see a tooltip with the title

### Actual Behavior
There is no `title` tag on the element.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01P3DAQ/SuWTyCtE9EiVYqWFT321As3zCGbDMWtv2Q7CQjlv3dsJ6skFBapt8zzvPdmnp37V/rd2qLvgFZ0H0BZWQc4cE3IvmdN7dr0napQH30uCOmZMi3IG04R5XSGj79YY6RxiFsnVO1e5rNJZhYifS07wDajgVMSRJCn6vAD5yA/NezL1PseNQzm39S7wZyjPjl4x/cuHq3pU+WxPIURo2EBnsPSYhC6NcM2nFPHooeJ6LUKYdFG4vYLFvovaKcxPlBM2awUMZT/U8yRrTUT9oHqFl8Eug5wRrDYl4tniKVvnLC5C56tcYG08Fh3MpDXrNbWoa7IxSW5OZCLCSMEo6+I7qTcZWS8TB9jNJgk6Y5Kof/44rc3Gt9/4nLaeM9pRe4zj9OnEKyvyrJpNXbixYreFRpCqa0q8c8J4vHl9mtxVVxdl63wYcaYxDdTJLUo9cD1iI5CxR2Yqu3GNh8k62kJTlEp1mdmuMW20nU6CAWsNQqH+VJcf8vDLPACvGJHZwYPDlU4naJJPnHiT3id3Rc93miXaNiDYw50Cw7cZ3fa0FZ7bc7e7DZd9kjHHc08DD9PTR/+AodFk7k=)

**Comment by KaelWD** [comment]
Someone decided to use title as a prop name too, so for the native title you have to do `:title.attr="'one'"`

**Comment by scscgit** [comment]
there is no `title` prop documented on [v-tab API docs page](https://vuetifyjs.com/en/api/v-tab/). Shouldn't this be supported without `.attr`?

**Comment by kappaflow** [comment]
Hmm, `title.attr` works, but `text` doesn't. Am I doing something wrong? 

https://play.vuetifyjs.com/#eNqdUrtu3DAQ/BWClQ0cJSBOJcgHp0yVJp3pQietYyZ8gaQkG4b+PcvHKbpzkjPccZY7MztL3r/SL9ZW0wi0oW0AZWUXYM81Ie3E+s4N6ZxQ6A6eTEyZAeQtpwg5JYcfrDfSOCxYJ1TnXjgtlCOJTJ0cARuMBmQEeA5HsP+KluSbhrZOrf9ihtn8YSaQmd9nc4n55GDjWmBhR3DKL8gjXHPHLbDI33rMQg9mPl/H2rHpYSJ6nexgHyMnr03Lavkfdo4eY3+IXcLn4H9RKOy1vlnK6RKOFQRtvfk1re+dsLkHnq1xgQzw2I0ykNesNXSha8jVNbndk6tSIwSX1xA9SrnLleU6HZYov0rSHZVC//LVT280ftfE5rT3ntOG3Gcmp08hWN/UdT9o7MTHEZOrNIRaW1XjRw/i8eXuprqpPtWD8OFYYhKfvUpiUemB6wUNhYohmOrsmWu+SM4lBaeoFPGFEe6wrXajDkIBG4xKs3zOs2zKFXjFDs7MHhyKcFpWk2ziwO+wupQWLd5I1+g3gWMO9AAO3HsTndG2qc6u3iQrT73QZUcTDRefRqYPvwE+94OB

**Comment by KaelWD** [comment]
Text is overridden by the default slot.

You don't need `.attr` any more.
