### ISSUE TITLE
[Bug Report][3.1.14] [v-skeleton-loader] bones not defined in skeleton component don't work

### ISSUE THREAD

**Issue by jojoxd** [vuetifyjs/vuetify#17156]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a v-skeleton-loader with `type="divider"` or `type="my-custom-bone"`

### Expected Behavior
It should generate a bone with the correct class (`.v-skeleton-loader__bone.v-skeleton-loader__TYPE`)

### Actual Behavior
It breaks due to the bone not being available in `rootTypes` (it is undefined)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctOAjEU/ZXazWjCtBrcSMDgzj9wQVkM04tU+kpbxhAy/+7tzJCM4ILEXc99nEfv6kTfvGfNAeiMzhMYr6sEr8ISMm/Kyvvu2QFTKTugDsc9aEjOltpVEgJJRw8LQaVqFEJBCT/v8tFyBj3tnI/kEMY6KJ9IhHTIbWW8C4mcSIAtack2OEMK9Fnk4drZmIiJn2SR+/fFO2jtyIcLWt4VD5m8p0MiOqE9F5rw7Cs6i1FP2YsYGlHQGekquYYaGQu6S8nHGee1tLgmQasmMAuJW2/4Esd4ONikDJTSmeWUTdljWWm/q9gLlyqmcZtBNOUmuO8IAckEnYzkktoeb5AcJlHpiT099xJDrdTVJmaNK26Ogg2EMoDFq+S73BbtYu2veBcjVxGzi1bYFg+gld3Hi7+vY/fvq7PZ/2Xv2DLVOiu2E/rLMFroN+n6B6OI/VA=)

### Other comments
A possible fix would be to allow `undefined` bones to pass the if statements [here](https://github.com/vuetifyjs/vuetify/blob/f55f6f9832a61e4084259e146efa45f9c15b52f7/packages/vuetify/src/labs/VSkeletonLoader/VSkeletonLoader.tsx#L96)

**Comment by cfxMusaib** [comment]
type="image, card-heading"  does not work either. 
Someone needs to take care of this issue.

**Comment by websitevirtuoso** [comment]
version vuetify 3.3.10
type="image" works, but type="card-heading" doesn't
