### ISSUE TITLE
[Feature Request] Add class to VDataTableRow if the row is selected

### ISSUE THREAD

**Issue by BenBurnett** [vuetifyjs/vuetify#17151]
### Problem to solve
In Vuetify 2 selected rows would have the class `v-data-table__selected` added to them when they were selected. This was useful to style the rows with CSS without having to overwrite the `item` slot. There is no class added in Vuetify 3.

### Proposed solution
I propose adding a class to all selected rows.

**Comment by kingyue737** [comment]
Also need a class for expanded row to apply style
