### ISSUE TITLE
[Feature Request] Add accent color generation for themes

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17154]
### Problem to solve
Currently the [color pack](https://vuetifyjs.com/en/styles/colors/#material-colors) has darken lighten and accent variations. But Vuetify theme can generate only `darken` and `lighten` variants: https://vuetifyjs.com/en/features/theme/#color-variations

### Proposed solution
Add [here](https://vuetifyjs.com/en/features/theme/#color-variations) `accent` color variants in addition to `darken` and `lighten`.

**Comment by KaelWD** [comment]
What is the algorithm for an accent variation?

**Comment by kappaflow** [comment]
https://sparagino.it/2020/06/09/sass-only-material-angular-palette-generator/
https://github.com/mbitson/mcg#color-generation
http://mcg.mbitson.com/

**Comment by dee22** [comment]
Would be a cool feature.
I checked the links and both of this tools are way off with their calculations.
And even the only official tool [Material 2 palette generator](https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors)  does not support `accent` calculation.
There is also a "clone" of the original MD2 palette generator [here](https://github.com/edelstone/material-palette-generator).
