### ISSUE TITLE
`list__tile--active` class is conflicted with `dark` style

### ISSUE THREAD

**Issue by hank-cp** [vuetifyjs/vuetify#1715]
### Steps to reproduce
1. Create a proejct with vue-cli
2. `vue init vuetifyjs/simple`
3. Change app theme to `dark`
4. Define some vue-routers
5. Update `App.vue`'s Naviation Items to match routers

### Versions
vuetify@0.14.11

### Actual Result
Activity link class `list__tile--active` is added, but the style is overridden by `dark` link style.

![image](https://user-images.githubusercontent.com/808941/30369217-43bfb164-98a6-11e7-8359-6ebee8510a0b.png)

**Comment by jacekkarczmarczyk** [comment]
Update you Vuetify version, this should be already fixed

**Comment by hank-cp** [comment]
Confirmed. After update to v0.15.6, the problem is gone.

Thanks
