### ISSUE TITLE
[Bug Report][2.6.10] <v-treeview> Errors when selecting elements

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#17161]
### Environment
**Vuetify Version:** 2.6.10
**Vue Version:** 2.7.10
**Browsers:** Chrome 112.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
When selecting elements, sometimes it also selects parent(s) that are not related parent. Sometimes it also select children that are not supposed to be children of selected elements,...

e.g.: Selecting "Base" also selects things from "Contact"... (see codepen below)

### Expected Behavior
When selecting a parent, only mark appropriate children as selected, same when selecting a leaf, only mark related parent as partially selected. 

### Actual Behavior
Currently it does weird things when selecting

### Reproduction Link
[https://codepen.io/laurent-brisbois/pen/ZEqWPXP](https://codepen.io/laurent-brisbois/pen/ZEqWPXP)

### Other comments
Maybe I don't use the component correctly ? Tell me if so.

**Comment by KaelWD** [comment]
ID's have to be unique, you're using 3 and 12 twice.

**Comment by laurent-brisbois** [comment]
Yes as I said on Discord I thought that since I was using the `leaf` selection type, only last layer IDs would have been considered when selecting.

To ensure I don't have "duplicated" IDs, I put prefix to other IDs from upper layers.
