### ISSUE TITLE
[Bug Report][3.1.11] v-list-item__content width not full filled

### ISSUE THREAD

**Issue by Ricky816845** [vuetifyjs/vuetify#17167]
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Edge 112.0.1722.48
**OS:** Windows 10

### Steps to reproduce
I set VListItem width to "100%" , the outside is working but the ".v-list-item__content" is not working and unable to set width

### Expected Behavior
inhired width or enable set width

### Actual Behavior
v-list-item width is  not working correctly.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU+1q4zAQfBUhONJCZNW9gwOTlt5zxPmhWuurrtYHkuK2GL/7reSkTewUCg2EZDWzO7Or1Xagf5wr+j3Qim4iaNeJCPe1IWTTM+Fc/psDLZQhL0rGp7ualjc3P2pKDmj+IKVTIZJOGQhIsQaQIcEEFd8wbqx2ook1PU36yGMK1c8RQnrWWo+5VwlcE2UkvF7jD5EiiprO6dUzJKVMW6Ln3udo04mQbEumTGqBtd2yyMx6Nt9YE3E04Bdghr19Icayv/sYwYcLnEORjuA3GShvFyN6JwYnzP0wkDSOwggNZBw3PJ9eLMxz5UvGEEFny35yxmcNoVGpeiXBEz6/RUx8v8Yz7IgcNwnDtErTjmEwLdmGnywfhqHxykUSIO4TrLSzPpKBeGjXHnCPVI/Nk9ZbTVa4vquUVRv0jiuYtuMOqRPtajskrTSuaiWEKOJrRPq4u06ykxBK0DWdVNCeK/4Fa/BJ5EzcqAyEmlYkn6QzFE1xTZ9idKHivJEG0yR0qveFgciN0/wBadzvTVQamLT64WdxW/z6zSVO5PS8gKDZI15JAI9Varo+0YmqffuC1oGJEmVRlpPE4Yx14jEkjUVtjoI9eOYBX40H/9WeZmlnfc2wRW9JfsQbwJHjU3sOs2k3IU96e3T5vaZztVRqlxTHNZ2covaUQnf/Aa5SglM=)

**Comment by KaelWD** [comment]
You've broken it with `class="d-inline-flex"`
