### ISSUE TITLE
[Bug Report][3.1.14] No-data-text does not seem to work in <v-data-table>

### ISSUE THREAD

**Issue by perwramdemark** [vuetifyjs/vuetify#17168]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Sending in an empty array to items and setting the "no-data-text" property I expect the text to show up, but it doesnot. 

### Expected Behavior
Expect "No Stuff here" to be shown

### Actual Behavior
Does not show at all

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU1Fr4zAM/ivGcLSFJlnvBgehKzt2HNzbvS99cBOl882xg61mGyX/fXLilLRbtvnJ1qdP+iRL90f+q67j5gA85WuEqlYCYZNpxtZNVAgUEYqdAm9gLH0AUYB1NxkPt4wHRBLX2wtwDiyegFwJ5+2goBEojY5WA1SAdhJfCMxNVYscB8DHih7BI1pUMJi1CYLgGT1kmMNDWbIHsMFns07GoqmMdTKqiZ4ut7LGrj54ro1FUlGKg0J2DKKInbL5gt1s2DzYvNS+qpTdb5eDMbSAbIOFDVH6gxIVpGz2u2ez+erqas/o2ki9X8xOgfwRSu41+ToUFs8hRzJ9OSkrhXJwhjVCHXwK36cxqx3djychd0IZK8HNlqd8oAt6UbPpng/wBP2PoBq88HfZpcAp4p2wO/cBNff4FPmfNQhSf0Cve4+pAH+tIfa3KbYkeEwdPrhddJfWD1EYG77kSupHF/93RtPCdL9N4+to3E9jQLuBWLs0SfJCk2cBSjY21oCJrquEVg1l+XL7I17Fq+ukkA4HW6TEzsVdNB9qm+mWMsrKz2lUifoibQ90qcPYZZwi+fcnGm7JLbEHjbKCqDAVifkeX//sxYzsMbgq2lnzRDNLUTIeWtPl8Yq/kOvTeinHm9iJXxKwkaWPou22X63pgnZW1wX2prbw2S1vl7znUfN71Xz7Cn14nCE=)

**Comment by KGSands** [comment]
Interestingly, it does work if you remove the `headers`.

**Comment by fahmifitu** [comment]
Related to #16710
