### ISSUE TITLE
[Bug Report][3.1.14] HREF Prop adds trailing slash when query is given

### ISSUE THREAD

**Issue by derHodrig** [vuetifyjs/vuetify#17184]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.3.0-alpha.12
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a variable (url) with `https://vuetifyjs.com`
2. Create another variable which holds the url and adds a query parameter to it 
3. Pass that variable to a VButton with an HREF
4. If you click that button you see right before the query is a `/`

So inside your script setup should be this code
```
const customUrl = ref('https://vuetifyjs.com')
const customUrlWQuery = ref(customUrl.value + '?test=true')
```

your html should look like this
```
<v-btn :href="customUrlWQuery" class="ml-4">Link with Query</v-btn>
```

### Expected Behavior
I excpect `https://vuetifyjs.com?test=true`

### Actual Behavior
I got `https://vuetifyjs.com/?test=true`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUs1O4zAQfhXLl+xqG3u7cKpSlr3vZQ8rDoRDmkypwX+yJ0Go6rszdkJVUpCQuGVmvvl+xrnd8z/ei6EHvuIVgvG6QbiqLWPVUDbe589cmEbZqcr1Bi1b7QJs1zVv+4jO/A+65ld/lX2sZJ4f4R/ib/71EJ5rzlrdxEgTo8vLiYQ9KdyxDHjLl6qjm1SMPit54p/K2AblkUXAPo2V8S4g2zOywA5sG5xhBQUvErh1NiI72mLrhPpW7BB9XElJMFTb54coWmeK72f4Mca0deyKodE9sB+s+I0QcY2B1Gh5XHcahHb3c/hizjq281olx0yUhi/4GIgu4cVDdJYecJ8OUk+DWPMVy53UowSprvlrpLaztNaBVkMQFlBab+Q1wWToLSoDZefM9YW4ED/LRvtdI5a/ZKcins4FRFNugnuKEIit5osTvXSxT2hOSJJaiuXlKDH1St1sYtI445YkOEAoA9gOAoTPZputvZtvhjnLmGwcanugJ9D0m8bZ9duYL3/76vZr4TNborpLiocFf+uYPIyr/O4FmhFKzw==)

### Other comments
NOTE: That Trailing Slash is not present if no query is given.
If you console.log both variables everything work as expected in the logs.

**Comment by KaelWD** [comment]
No slash in the DOM, likely browser behaviour: 
![Screenshot_20230419_235721](https://user-images.githubusercontent.com/16421948/233098054-e7574735-7de4-4452-80f4-e87d84f626ff.png)

**Comment by derHodrig** [comment]
For those, who might come in future
> http://www.example.com/product/?source=googleps  is actually valid.

For SEO purpose, you should be consistent with the trailing slash after the host / port part

## Further reading
- https://stackoverflow.com/questions/1617058/ok-to-skip-slash-before-query-string
- https://stackoverflow.com/questions/29855027/trailing-slash-before-a-query-string-bad-practice
- https://webmasters.stackexchange.com/questions/81252/is-a-trailing-slash-appropriate-before-url-parameters
- https://www.rfc-editor.org/rfc/rfc3986#section-3.3
- https://www.rfc-editor.org/rfc/rfc3986#section-3.4
