### ISSUE TITLE
[Feature Request] How do you like the idea of adding Material Dynamic Color to Vuetify?

### ISSUE THREAD

**Issue by AinurY300** [vuetifyjs/vuetify#17181]
### Problem to solve
It would be great if Vuetify had support for dynamic colors from Material Design 3

### Proposed solution
Now I am trying to use this utility:
https://github.com/material-foundation/material-color-utilities

**Comment by KaelWD** [comment]
You can import `@material/material-color-utilities` and use it to generate a vuetify theme

https://play.vuetifyjs.com/#eNqlVclu2zAQ/RWWLSAJ0NIsDQojCVIULXrroUV7iHKgJdpiTJECSakxAv97h4sX2U5qoD44Jt+bN29Go8n9Mx56athsmT9qPMGs7aQy6BlVihJDf3kMrdBMyRZFgRuVYkNsll1DBXA3pDtgFbohita7RKLm069A+EafUmQa2lJ7+iF7VdHPkkuVItJ1fPnTQluxFqQVI7xY/8gqS856wzgzjGrIUYpKCm28Kro5qh7v5I+jt7OP5x/eX0VJYqPpk/PoRUKNIDPqQfxcCuSVJ8j9RqimM9Jz4xxPUMTZvDFR6jHH1BsqQg6FM6QBO4AYRYSeSdW6+NgF5LpycbljJ2gV1CAXUYuToy15G7yyf+xh5aqd9aIyTIo9CeQ1Eu9YUdMrgb5PH2llcvssvgijoN2xRUsTABouffpOyU4neUu6OL5foHR4SNDN7bYFQfR+MzPxIknR8BBsgjuE4GuFU/yp63J4EjCS14a2HQfyrYWvB3j+whAmqHIX7krJP+EAxzUfDRkUd1Pi2PUsRQu6TBAT6N165L3rqlcK6sh9Z0uMJkCEMPgu8UY2pObbc/gMGZsB+w3Qc22IMvo3M00cSZFFSYkP+KChgX92fgRra0CujgB8DsDlEWDHn3dIVH1Ags/EVbeu6hiDcjoQOxdAen+comQvamo9vkAYudn4yQx9MnsQgLojMI2HItAiTrTtkY3LmmP9CJ23hNdqQqjYt1S85GmN7D5xeyX5drSK0Sx6wnr2PHk7miMyTLRfhBm8HLBqpYDJdu9FGQAYvM2yKO1StucSN8Z0elIUVS0grKacDSoX1BSiawu3aVUvDGtpVsv27iK/yC+Lmmmze51T3WZT8KmpApESh71Q4p1VfWo6z97N5G98EpgPvp8kvG0nJAhMJ37mxcNVxslU2xQH0gUUNVCVwStcU0XVyXWMw0YFjaFX2vfPf05jN73oFnPYM2DhhEi3tf025Ews9N7YVNqp36/N/FdnnZhVgl28wqsUu3ZAZheAH/4CydOP1w==
