### ISSUE TITLE
[Bug Report][3.1.14] Some of the ancor CSS properties interfere with the <v-btn> styles

### ISSUE THREAD

**Issue by set-killer** [vuetifyjs/vuetify#17183]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Linux x86_64

### Steps to reproduce
So i have defined some CSS properties for anchor active, anchor hover, anchor visited. 
Those properties however reflect on the components of type `<v-btn>`.

### Expected Behavior
I expect the `<v-btn>` styles to not be dependable on the `<a>` styles because I'm rendering a button, not a link. If i want to render an `<a>` tag I'll use the `<a>` tag alone.

### Actual Behavior
The `<v-btn>` uses the style that are defined for the `<a>` tags.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUU1P3DAQ/StTX9JKm1i0SJXSBdFb/0EPhEM2nl0M/pI9G0Cr/e+MnYDCwgGJm2fezHvznq8P4m8IzbhH0Yo1oQ2mJ7zsHMB6rPsQyrMUttdurkpN+Ej1VqNRwKBXaC46YdOuEyCXcxty0JJnsLolCq2UO+93BpvBW1nx9GWf1FqWwRc1rl7lcjEdspaLA7lMQ9SBICHtM6xt8JHgABG3cIRt9BYqdlbl4cG7RMDnwUXGv1f/0BgP/3006lv1I5NPdDM1PZkphp4JB298bHlP/YFjaba3fsQIhwUyA6NOmlB9BPUD6RFfkY3ZY+Fj6SInVmLywOZDc5e840855N1uBlInWiid3GNvue5EzjVxsINyvMY/ocfYOCTpgpVXPCbj3pG2WCtvr341P5vz31LpRMt+g8nWm+gfEkZm6cRqoUN6+/QJrXmSJc6as/NJYu7Vpt+krPGOW7Igh1lHdAojxs96Oll74+sEe+cty3PyR47caHefTtIeUkn6+uXKr5kubJnqJiseV2K6lLWnFXHzDOBnLno=)

### Other comments
Probably adding `!important` to some of the color css properties would resolve the issue (hopefully).

**Comment by KaelWD** [comment]
We can't account for every possible combination of custom styles you might apply, you'll have to account for this in your own CSS. 

> If i want to render an `<a>` tag I'll use the `<a>` tag alone.

Don't use the `href` or `to` props then if you don't want it to render an `<a>`

**Comment by set-killer** [comment]
> Don't use the `href` or `to` props then if you don't want it to render an `<a>`

Then what should I use? The other option would be to use button with the `@click` event and then manually reroute the user to the new location. This looks bad... 

And also the `<a>` tags are quite common to use. Not every anchor should be rendered as a button, and not every button should be rendered as an anchor. There should be a clear separation between the buttons and the anchors.

In Vuetify there are already some color css properties related to the buttons. Setting them to `!important` would resolve this issue. For example:
```
.v-btn--variant-elevated, .v-btn--variant-flat {
    background: rgb(var(--v-theme-surface));
    color: rgba(var(--v-theme-on-surface),var(--v-high-emphasis-opacity)) !important;
}
```

**Comment by overclocked555** [comment]
I use pseudo-class :not()
`:not(.v-btn) a {}`
