### ISSUE TITLE
[Bug Report][3.1.14] VDataTable color prop does not apply to any element

### ISSUE THREAD

**Issue by zephyrtronium** [vuetifyjs/vuetify#17186]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
`<v-data-table :headers="headers" :items="items" color="primary">`
`<v-data-table :headers="headers" :items="items" color="#f00">`

### Expected Behavior
Something changes color.

Following the source code, it seems like the badges for multi-sort indicators should use it:

https://github.com/vuetifyjs/vuetify/blob/bc00d35339cf6603af13fd19f77e0e2221b45e04/packages/vuetify/src/labs/VDataTable/VDataTableHeaders.tsx#L130-L141

Kael indicated on Discord that row select checkboxes should use it as well.

### Actual Behavior
No element uses the color.

If I make the table multi-sort, the badge div has only `class="v-data-table-header__sort-badge"`, no other classes or styles. Similarly, if I make the table show-select, the checkboxes don't apply, and I see no color-related classes or styles on them in inspector.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9VN9v0zAQ/leOgJRVWhJ+CqlqBzyAxBtCvK0TcpPLZnAcy3a6jdL/nc9O2mUtYpsm0Yctd777Pt/5vjtdJx+MyVcdJ9Nk5rkxSng+WWii2SoTxsTPaDRC6sGKdiW8yLxYKs4c2xVbml6wqNi6+SIZvhYJTSVQgyv+3zkyxfrcX2z9eW/iuGxVa+F+WtfP8YOn6ZSXmWutJ3fRXoJNcemp+I+XMVY2wl4/+DL3vMVja34gzb2rmRWjZw9GPxCzYjQoMF1ppQEC+86QEvocHB6EOC1b7TwNd6I5nQakNf3k6ymlDlyy1ekxeekVw5PS5ngc4Vsv1Oj8W7BdH3UWuHv8WOAN+oCL+GVblhcyAITEKb3ZZs6K/tK4YnKcyMagBSjV5D9cqyGFdUBC5+IBSplS9AQftBJsdNp746ZFUVYaaRUrubK5Zl9o0xTvEVbYTnvZcFa1zftX+cv89duiks6P/Tm7Jlva9hJjC5RFEusfeLys8Up3cg2RoHiRv+gZBlemxNIFigPoopdJZlnjadjet6S9tFtl7Z0dlBboNwu9QceV1D/dXrNLFxsdHzHYj6o5ggUkPHYg/BZ08rW9/Ouqw3B7S6USLshlrKzv3z1as1NdCKxoldVRR9ATSU3Gtsblw9DlcHaNjvrDDPdROb6CY8sAV/xkd4TPyS2CQdxLr8Ej6xsAms/nlI4WHV8Zoas0Kh06QGTv+QwDTid/MXyuEUrBXAkrhfZBmnzlQRn0DJZ9agcIMLNy/Bf6rWTp92960tMBar0mKy5Ph8gz2mygL5yN+1b4ardVvH3YFullCGWXbWM6zxVtqLZtQyleMw3ZUnu2tSiZvoTX6NW62wNCX2MKbvZFfDHsi4prqTlmzOLfk6PJNgYFIWJLeHQ0ofnJ3lOHtZMjbpfTN+TONPcxxuH4EG+yBxYe8xCwP8tXQnVM7yh9htYrYRynhK33bJgMQC103emIHrb/aOhiUybbrWbRdKu3Vvileyqo0il52/GwQw5Csn7us6yWVxyCwzDE7zszcCl/Ky04Pt0rVbeZEVUl9fmQ+g+dDGBhAd3e/5vjpN9iWBNxnSRnfwDXxgue)

**Comment by SveinnB** [comment]
Another Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVW1v0zAQ/ismEiqTmqYvW8eirhoaIGBf9gEJoXUf3OTamTm2ZbsZpep/55y3Jk3YkPiGVKn13T13zz0+X+923julBukGvNCbWUgUpxbmC0HILPWpUtnP7BBJYSkToAtTZrTw0/orBjwmqZ/IGPjlwkvMeuGRSHKp8aQ0S6jeoiVAZA0bPTDVjpp/fWCG4CfZksKYB82CHFKVr1Kp+bULwHCpQNstEdKSJ6kfmViTFTpSP6aW+pYuOcyCQwYkcXCURlJ2EjLUw/iY0ld0DUgyM9yCvsXjwjsAwgegMWiDIcWvhjeDoS8GY5Bfw+l8fkr5xuUXNGnkbYlTc3FqXE7gkFLLpPBHB/fcaXXorC67mmdIslz7Rdb/V5Bak89pkzXuhqsx4M6Sz/8sqL0LPJpIM2WJAbvJlWOJktqSHdGwInuy0jIhPXxSPefErMYSfBLk0vnf9D4B55J8k5rHr3on+dXkQYVUGHiXs9qVpC2zHELSe58LRt6MhsM1MtApjvhJr1/GUc7WAuOMpdoezAbpuWZDsqLcQGV/hC0GO5HL2H3xvatKXlOUnIHp9avsIGI85eCodHdAP1Jk6uh1IlfUdoGuqV6aZ2CR83cBb7W0wMQzUNwPLqIL/FlLRL7+E5Khu4Td16+snOCOO3OyOhG0/AWCfJfrTf1KSt1CMjq7qKyoSUimg2EtDLsNyfi0shRNhOS0Fub4Ya1R6xqPyHzB2duSJVDRxWRyftZkMmwzuehgUg8rmAxfYnLD7A0OQAeLs9HbJotxhyDTA9OKxvkxielLJD7g0mC6i8R4Om6SGHXdyqRNoh5W0Dhv0sD5mQX5DsHt4fW9fH34CVWDH0YK/CPOeOJ2zRy4HcOS+cLDteLOuFetVSYMgigWCMPtzFI9EGADoZLgCsMCvRGWJeDHMrmaDCaD0yBmxtbNAzCJv9TyCWcYkyy8gmhWxrIVrs0XSxWRWYVpXqEw+ZwujSvRSh24zYX/IhrfGGjQf9vREaze1ZGr1Zmrvl+IPerNmXg0R1JHJpO5eMP/2HKWrLjqvbfvexlPrJwBvPvfNcLiRQ==)

vuetify version 3.3.6

**Comment by SveinnB** [comment]
Hi @MajesticPotatoe 
Thank you for you answer

How do I change the color ("background-color") of the v-data-table ?

see

https://play.vuetifyjs.com/#eNqllG1v0zAQx7+KFYQKUtP0YetY1E1DY0iwN7xFy144ybWYOU5kX4pKle/OOQ+d04YNiVeN78H3u/+597D3PhbFZFuCF3orhKyQHOE6Uoyttj4vCmZwJ+Eq8mKePG10XqrUT3KZ65C9uf1wt7y9jLw6vE5IcoVcKNCtqTamHLmPPJbQGRkLfwBPQRu6uP2KPMcriMT6UjAGNPac1udvuSwtleIZuM4ajeyFFhnXu55LcmPvjDc+aq5MwTUodCOyUqLwTa7RQbFHP95R4sOePcEuZKM1xxGrHp9Tr1eB22anBxn7glgLaUrfq8DRmo4m0aJAZgBL66Yus4IKsz3TsGYVW+s8YyMa08iG2z6VQdZKx67YQ1Ny3xGhQAmE+qkRkL2bTacbul5vhdq8H427OC7FRlGcQa7x2Wybtp2EbM2lgYO96d+K3sVW7e/+UPKW0wgEmNH4cDuolE5NctK5B1I/cyK1eIOZjewD9XRsXkhLrH8o8ZvOEYR6IbVoIoaSv+icMt/+LVOQu0t7dEfWveiBmVlZrQg6/w2Kfc83pTuSTreQzc4vD1bSJGTLydQJo25DNj87WNomQnbmhFk+qjU7GeMRzFeQcsdi4GqIZHFx3ieZnpJcDpC4YS3J9DWSe4H39AAGKM5nH/oU8wFBls+kB4yLY4jlaxB3tESEHoKYL+d9iNnQVBanEG5Yi3HRx6D3swqaBUGrwRt7zW7wM15Mfppc0eauOaPWQdsy7Mgjj3aGPdOeRSxMGARJqigtBSm2eqIAA1VkwQ2FBbpUKDLw0zy7WUwWk7MgFQZd8wRM5sc6/0VvmC6JvBa0LoNiTQv31VJtZF1h2VRoTb7ksbElTq4O7OYC7dPGpoUH+l87OkpzuzpynXRmq1eRqkhvKdSTOZI6MbXM7X/4P1uuL2tHXXnV2Ks5qXKd4D3+AV8OTmY=

**Comment by zephyrtronium** [comment]
@SveinnB This issue is about a prop having been apparently unused, not about changing table colors in particular. I think questions like that are best suited to Discord. It may end up being a good feature request, but it is not this issue.

Regardless, multi-sort badges now use the color, so this seems to be resolved. Experimenting with the playground suggests it was fixed between Vuetify 3.2.2 and 3.2.3.
