### ISSUE TITLE
Stepper component causing error

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#1719]
### Steps to reproduce
Create a stepper, see e.g. the default vuetify stepper codepen or forked copy with link pasted below

### Versions
Seems to happen to all versions of vuetify that I've tried this for since 0.15.2 -> 0.15.6. Chrome version 61.0

### What is expected ?
For the stepper content to work

### What is actually happening ?
Stepper raises an error:
```
Error in render function: "TypeError: Cannot add property beforeEnter, object is not extensible"

found in

---> <VStepperContent>
       <VStepper>
         <VApp>
           <Root>
```
Followed by:
```
TypeError: Cannot add property beforeEnter, object is not extensible
    at render (vuetify.min.js:6)
    at createFunctionalComponent (vue.js:3519)
    at createComponent (vue.js:3678)
    at _createElement (vue.js:3857)
    at createElement (vue.js:3796)
    at vm.$createElement (vue.js:4139)
    at Proxy.render (vuetify.min.js:6)
    at VueComponent.Vue._render (vue.js:4190)
    at VueComponent.updateComponent (vue.js:2578)
    at Watcher.get (vue.js:2919)
```
In Safari a different error occurs:
```
[Vue warn]: Error in render function: "TypeError: Attempted to assign to readonly property."

found in

---> <VStepperContent>
       <VStepper>
         <VApp>
           <Root>
```
### Reproduction Link
https://codepen.io/shongololo/pen/RLwzPR

**Comment by jacekkarczmarczyk** [comment]
Should be fixed with https://github.com/vuetifyjs/vuetify/pull/1714

**Comment by nekosaur** [comment]
Related to Vue 2.4.3 and https://github.com/vuetifyjs/vuetify/issues/1712
