### ISSUE TITLE
[Bug Report][3.1.15] Vuetify tabs

### ISSUE THREAD

**Issue by trygveam** [vuetifyjs/vuetify#17194]
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.3.0-alpha.12
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
run codepen, resize window to about 320px

### Expected Behavior
Expected the tabs to get smaller when i resize, or atlest visible. Problem is that we need to utilize tabs with a screen size og 320px, cant seem to workout around the min-width element of tabs

### Actual Behavior
the need to adjust the tabs smaller, to x size

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tO5DAQ/BXLJ5DGsdhFWikaRuwX7GVvmIMnNosXv2Q7mQGUf6djJ0MmIBjBLV3uquouxzfP+Lf3VddKXON1ksZrnuSGWYTWHWl4EPk7V4lvYykQ6ohxQuorhgFleIK3/0jjtAuA+6AMD4/T2SgzCaGoniR07Uk0XGuGUcd1OyDOSoY3ek1z38m0tHNfot0H+TW/94ljFaE85DakSJLcp7n4TlnhdsscDx2zHqLgWhbxvLYh9AeQVxb4z2iHMT5QLMnNFf8C8i3FMZsjzYx9oLrEZ4EeBzghUKzp7I+FMjZB+dIl996FhIS8461O6LmoCZ54jc7O0dUGnY0YQhB9jWyr9aog/Xn+6AeDURKvsFb2IVb/o7PwVDKX4SZGhmt0U3gM36fkY01pIyx0wsWqLlRWJmq9ofDIkrp7vP5ZXVQXl1SomCaMaPhnqqw2SN0y24OjMsMOxHC/sC0H2XpcgmFQGupPZriGNhpam5SRRDgDw/yoLn+VYWZ4JaMh2+B2UQZQYXiMJvsME5/g9em+4PFGm4JhJwMJ0goZZDh1pwXtaK/F2Zvdxsvucb/ChQfhl6nx7QvV06EI)

**Comment by joel-wenzel** [comment]
Does just setting the [min-width](https://play.vuetifyjs.com/#eNqlU8tu2zAQ/JUFL0kAU2paAwUEx0i/oD0U6CHKgRbpmi0fAknJTg39e1ek5MgykKTpTTvamdkdkg9H8qWus7YRpCCrIHStWBDr0gCsWloxx+N3rALb+FQAtFRbLtRdSRAtyQhvftLKKusQr53UzD2N/waZUQgFNtLwxP/mbO1LAi1TjUDIGlGStVrlsfVfmGFv38vcOfFe161t3CV1qDyWpwj7QGkQhzCV36Ow3c8jPXVMeqjEE5rF9NwG8BWRZxb6T2inMV5QTPFNFb8j8l+KQ6xnmhF7QXWOTwI9D3BEsFjlk8uLpa+crFOXONTWBeBiyxoV4JjUOAusgOsbuFvD9YABYPQFmEapxQSJ513AEbQ0PyQPuwKWHxbg5R9RwNWBes2UuoJu4HQ38aPrhxrGIAuipPnts1/eGnxp0a8klcdrVMBD4pVkFwIa5XnFDXbiZZCty4wIual1jm80yO3T/afsNrtd5lz6MGJU4T3Lolov9ViaDh2l7vemmtUz2/QjWg+LlwSV+vqVGe6xLXeNCVILyq3GYT5my89pmAmeCa/pxtm9Fw5VSjJEE336id/g9eq+6HGhnaNhKxx1wnDhBD7Lt+00o53tNft3sdtw2B3pFiTxMPw0NXn8C9bvtPY=) work in your case?

**Comment by KaelWD** [comment]
There's also a `$tab-min-width` sass variable.
