### ISSUE TITLE
[Bug Report][3.1.15] v-window-item disabled transition still occurs when going backwards

### ISSUE THREAD

**Issue by mrgenky** [vuetifyjs/vuetify#17209]
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.3.0-beta.1
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Go from tab 2 to tab 1 for example.

### Expected Behavior
There should be no transition, same as when you go from tab 1 to tab 2.

### Actual Behavior
The transition occurs.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVk1v20YQ/SsDXtQCIlnFCVCoSpEC7a3H9BTmsFqOpGn3K7uzkgPD/72zJC0zcgIbyDGCL5zveW+f7flwV/0RQnPMWK2rDaMNRjH+3jmAzbFWIQyfg2EVuckabK1iD2jwqJi8e9tVq646x4cMVtsEUuh7NBIXc8joePwZM+CoTMap/L3Yq007BL6d+WrKfPVs5s2UefNs5usp8/Vl5mSnL6EV8DXjLc/cQ+BErvenS9SgjUpJrKDqsv28aFZWk7zAnBBYc1Qu0cTwTpmET8r/9lGqKKRsoffGR5ACUBZ5Cdq7hJqRcwTVU6Ckye3l2UiCCXspAKScZFsory/F5DT11GfHkBmM2kp7QB5bI1i1dwqUoU9ZNfAPAzqy0hsslY+jmMou4VOmBM4njllUcotREw9CgWyMstqPnUsSJSqThpYUJBlQyeJWdvIjABnFDfxZWqrMCBSzbDJiJQcRQ8QDuh6jABfH0ZscZBzKOoIUMCUETcY8MCSAMuzynhSDKwtBUFGMHBv461ZjYBTCEgkHXmuFWvJ0DtQr6SqwHIToqUdXWCxMyVCdTVAFN/jdjjQp6DFhLFHrTVlDFYJI6EgTr9k2F0oQsc2k8DKdiKCuOrnq5FmdyB/Dq06uOnlWJ/Kv8EU66fiqlB9CKY+x+REkzqdX0IP30RHOt4/l+ldBW7/5QknvDwjbvIc1nIRI+Owz7D3sorcw3HjAfvhYwU44x1slJyougQ8oXJZngUeplhYRVQLiRRJ6QvBFadJhK49GSW2NmCfiw9cFfuZk054PXwF0vnyLMd7Em3Z2K4uZdKTAomvOJUxFzwx3IpAd3I9oFnJkL0pyERZDOT7flvhPi9Xi599Ky7GJlFfLauwgo0Pzb/JOrvO7skE3BVJXrWHwFJ90LnZXHZhDWret7p2UyQFKx9g45NYF276TtLaogizWvbfvbpqb5pd6i6yaVSv08DzaYLL1NvqTKEl6ddVyNo1p9/kFE6dMGbRqVm/GEZOvFhmmMuNJ71YGHjHWcfi1wvhSZBdlX0F3kfEEYVnivnP3Qr8h91+6YF6ngfUPD7t+H/ShW2n1sUy8X1bzfWWDsbD6+D+WWKvd)

### Other comments
Whe can also notice than the tabs briefly overlap when switching, like for a few milliseconds.

**Comment by nekosaur** [comment]
There is a separate prop `reverse-transition`

**Comment by mrgenky** [comment]
> There is a separate prop `reverse-transition`

What does it have to do with transition deactivation?

**Comment by KaelWD** [comment]
You have to set that to false too.

**Comment by abea** [comment]
This would be super valuable to have documented.
