### ISSUE TITLE
[Feature Request] VDataTable slot names

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#17206]
### Problem to solve
This could help avoid confusion with the table slot naming conventions. Perhaps I'm just overthinking it (not uncommon for me) as well, but I do think there is a little bit of room for improvement. Let me try to explain without getting too confusing. If this would be better to put into the Discussions, please let me know and I'll post this there and close this feature request.

#### Headers
For example, we have a `headers` slot and a `thead` slot. Both of which pretty much do the same thing. The only real difference (atm), is that the `headers` slot includes the `thead` element in the Dom, and the `thead` slot does not. There could be a use case where someone wants to have a specific class or id on the `thead` element, but having both of these slots seems slightly redundant and unnecessary. 
```html
<template #headers>
  <tr>
    <th>
        foo
    </th>
  </tr>
</template>

<template #thead>
  <thead>
    <tr>
      <th>
        foo
      </th>
    </tr>
  </thead>
</template>
```
#### Body
The same applies for the `body` and `tbody` slots.

#### Footer
When we get to the `tfoot` element things start to veer away from consistency. We do not have a `footers` slot, but we do have a `tbody` slot. Having both would have the same situations as the `thead` and `tbody`. So if you were to keep both `headers` and `tbody` ect. it would make sense to add in `footers` slot to keep things consistent.

#### Bottom
The `bottom` slot is where the table pagination is by default. The `footer.prepend` slot is actually part of the `bottom` section. It would make more sense to call it `bottom.prepend` or something else that would make sense. `bottom.inner.prepend` seems like that might be overkill, or maybe not. 

### Proposed Suggestions
1. Either use `headers` or `thead` slots, but not both. `headers` seems like the better one to keep since that matches the `headers` prop of `v-data-table`'s. 
2. Same for `body`, `tbody`, a potential `footers` and `tfoot`. One or  the other. If both, then adding `footers` would keep consistency.
3. Change `footer.preprend` to `bottom.prepend`.

#### Some additional proposed ideas
1. We already have [`item.${string}`]. It would be nice to have  [`header.${string}`] as well as one to go along with a new `footers` slot a [`footer.${string}`] slot.

**Comment by nekosaur** [comment]
The slot setup is not final, and I think there's room for improvement here. But I wouldn't call the `thead`, `tbody` and `tfoot` slots redundant. They are there mainly so that one can add content in those sections without removing default functionality.

**Comment by webdevnerdstuff** [comment]
Fair enough about the thead/tbody/tfoot slots. I didn't understand what you meant by "removing default" functionality at first, but then the light bulb went off above my head and now I can see what you mean, and how those slots do have a good use case in certain situations. So scratch the idea of them being redundant. I do still think it'll be good to have prop data sent to those slots, which I assume is already the idea, just not implemented yet.

I do think however, that a `footer` slot would be a good addition to go along with the `tfoot` slot, as well as changing the name of the `footer.prepend` slot name to fit the slot it's actually in.

Overall, keep up the good work, it is appreciated.

**Comment by KaelWD** [comment]
> It would be nice to have `header.${string}`

It's `column.${string}` for some reason.
