### ISSUE TITLE
[Bug Report][3.1.15] VSelect prop return-object type error

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#17211]
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Edge 112.0.1722.48
**OS:** Windows 10

### Steps to reproduce
Add a `<v-select>` with prop `return-object` in template. Type error:
```
Type 'true' is not assignable to type 'false'.
```

![image](https://user-images.githubusercontent.com/40021217/233818072-6c4d4de7-f029-4189-838c-2fcf8e986c1d.png)

### Expected Behavior
`return-object` can be either `true` or `false`

### Actual Behavior
`return-object` can only accept `false`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU9tq3DAQ/RUhCtvCyiJtoGDckBDavJS89CnEC5HXs4mysmQk2WlZ/O8dWbbXuyG3J2vOzJwzN9/u6EVdJ20DNKWZh6pWwsNZrgnJWuZAwdoHg5CWVaYE9SOnA0ojnj5I7RG9+7SLjsR5pOiWZAJEUdjubkqQKOMwo/+OaDCYl15BUAgMB55WqCZ4AtXoUKLo6/lzUE8N1knnQXsWKougBd9YzUzxOPXjpL5XwJTUEICzjI/9YvcZn40CTbe2sg4OQuBvbawnJWxEozzZRbZSeEE+fxnNUXFvo2BPnpId6dtLyeKXMlaWYrEkoa0A/F6QbrlP6SeUkts9Qj6SPg++AmPv5Sz46uLl4GsorHDbWfT1z5ejL4WSG2P1nP3yVfYncmPsdsZ+cxi9mt5dfEQnGhkfVkGXFFe3dcmjMxpvtx90TtcOL2qaWE4fvK9dyvm61BiJ9ytbm2jwXNcVx6v3cvPv/Ftykpyc8hLPZsQYHpdLerZAtcp1h4qyCrtnlaiPZKOjlx42nlNkCvYbNZxjGLeN9rICVpoKi/manH6PxczwBFzFCmueHFhkyekwol4nVPwOrTf7RY1n3BwFW7DMgi7BAv597+vpKO2gryPfs96GZXe0W9KYh8OPVdPVfw/6fSw=)

**Comment by KaelWD** [comment]
@kingyue737 what versions of typescript, volar, and vue-tsc do you have?

**Comment by kingyue737** [comment]
typescript v5.0.4, volar v1.4.3
I found the error disappeared if I downgrade to v1.2.1. Maybe a bug of volar

**Comment by yuwu9145** [comment]
In my opinion, it was an enhancement in volar recent versions that makes this issue appear. And we should resolve it from vuetify side.

**Comment by ggedde** [comment]
Same issue here, but on v-select with "multiple" prop.

```
Type 'true' is not assignable to type 'false'.ts(2322)
index.d.ts(43840, 9): The expected type comes from property 'multiple' which is declared here on type 'Partial<{ reverse: boolean; type: string; error: boolean; active: boolean; direction: "vertical" | "horizontal"; transition: NonNullable<string | boolean | (TransitionProps & { ...; })> | { ...; }; ... 30 more ...; openOnClear: boolean; }> & ... 4 more ... & Record<...>'
(property) multiple?: false | undefined
```
Everything is working on `dev`, but It is preventing me from running `build`

**Comment by jcchrrr** [comment]
cf https://github.com/vuetifyjs/vuetify/pull/17212

**Comment by Ge6ben** [comment]
In my case I fixed it by this way!
```
<v-select
    v-model="select"
    :items="items"
     v-bind="{'return-object':true}"
  />
`
