### ISSUE TITLE
Keypress Issue in Data Table Edit Dialog.

### ISSUE THREAD

**Issue by GArrigotti** [vuetifyjs/vuetify#1721]
Whenever I hit a key on the input inside my `v-edit-dialog`, the `v-text-field` will automatically close. Inside the data table, it is structured:

```
<td>
     <v-edit-dialog large lazy v-on:open="props.item._example = props.item.example" @save="saveColumn(props.item._example)">
          <div> {{ props.item.example }} </div>
          <div slot="input">Update:</div>
          <v-text-field slot="input" label="Edit:" v-model="props.item.example" single-line counter autofocus></v-text-field>
     </v-edit-dialog>
</td>
```

Doesn't matter what I do, to force the text field to delay or not, as soon as I attain focus and do a keypress it will automatically save and close the dialog. I've got the latest version of Vue and Vuetify.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
