### ISSUE TITLE
[Bug Report][3.1.14] Typescript in multiple select

### ISSUE THREAD

**Issue by AniaKru95** [vuetifyjs/vuetify#17219]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
It highlights only in my environement. I cannot reproduce it.
1. Create a boolean variable
2. Bind to v-select :multiple prop

### Expected Behavior
Allow for binding boolean variable to multiple prop.

### Actual Behavior
Show an error: Type boolean is not assignable to type false | undefined 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVNtu20gM/ZWBXroLxBa6W2ABw1u0SNA223USNN0tijoPjERHrOciDEdO3ML/Xs6MHFvKQ/skXg8PORS/fC9et+1002ExK+YBTash4MulVWq+mTBqrEJUlNpMjKtR/70sVrBxngLyssiumSiGxcNBkh/NGm5T/HVG2QebTgdqNYon+A739oZsENMVVWu1dZ1X+zJqiNqiZ+KANkxiSjS+nJd7rsJ8Xh61ISpXntroUAofWueDqnEFQkJ9z4g1BFC//b5XlfIYOm8PulLEi571TEXSJwfX4zRm6svNkT2zFuPBpNSz1zIUMPDsJIm8zpJBTxVYdQ3GZYunb86KOEz2a7AMHCNOQdPKeUsp/tRp56F2WbZWJkFVF0b5Z6jhHjzGqDOZoRQNyq2UZHfmNiO9wRq9MK/VdWog+hdUeWeRY8QA8I1UpTrlvUXn7zLE2w5M/L6TYkRROq+hEW6D3HOtyTpKzZzbmiC2K6K7T9/3j52+l6fuqvV2lP+v60gY5awFkE1tLcBzA1qrc9Zg6wQgtm1URgALYIaq6RhDyHFUNXQHNssyRHYhoxPLyjG1rXQzxBCz7GpqcuFs6Olc4K3fP+4FbiCOaJB3gffqHZiWG8rPEQ3/yGajtJm1BT5QlR40ap+dX48xZJUbdQreySBzqWQ5g3XPO+komywTiJM6HsplQ+MXuVxreaa8nJce71yaxBVo6JKA1vJWb6DfuasOfXDqQ2I5APrQyKXoi8XIa9eNmGbLgelHwUZmlFkMkD7iQ16C/wI08fs/eiNzTiLJwtmjMtnwZEk/gUzZ3oXczifkoA6RYiCunGXK3q0zEnuMcPind1nYJYMo87I/LcVJIY2tefqVnZU7mg7HsqhYjtbjAVgWTQgtz8qyqq1Eyi2ljZ9aDKVtTSkXONBq++rP6fPp8xdlLb/n3jaRm8HThBahbpZ2JxXJxFs2MdCOymZHKt1fsGUhSFH/CYdXElb6zgYyOKmdETJ/TF/8lckc2afIZnLr3T2jF5Rl0Y8o1YmMf6HWT/uVGk+wSym4QT/xaOVKof/VnkZpg75Gvie99Y+9K3YnRc6T4WfWxc0PWaRCYQ==)

### Other comments
If I bind boolean variable to multiple prop, it works as expected, only highlights an error with typing. It is a little bit confused

**Comment by jcchrrr** [comment]
+1
Same error with **returnObject** prop in v-select
