### ISSUE TITLE
[Feature Request] v-avatar fallback to default slot if image is not loaded

### ISSUE THREAD

**Issue by RoduanKD** [vuetifyjs/vuetify#17217]
### Problem to solve
I'm making an avatar component where a user has no image it should show his initials.
what's currently happening is that when the image prop is provided to v-avatar, the default slot is wholly ignored even if the image didn't load for some reason.
here's a [reproduction](https://play.vuetifyjs.com/#eNrFVUtT2zAQ/itb95Ayg2xoaA8ZaGFKD1w59II5KPY6ViNLGkl2YJj8967sPOwkZYC208khXu3r+/Yh3T1FV8bETY3RJDr3WBnJPX5JFcB5w7gx7WcrVFyolURyLhrIJHfuIo0qzs7SaKMj7TvG4AYWXHnwpXDAWF9LgRvuuQVR8RlSgNJ74yZJYqwuhETWnrs401XSfjKlPSt0rfLYqFkaQaaltuRoMSep4VZQKpJ17aVQ4bCXD+D2upc9WaffkkmIzUZ6BUWvQWo9Bynm2BEVBf1jRwxIJuDQAgdtwXkhJXnwXKjZ72oyWRdF1VI+Q7WgRv0TmlB59nmf67faWqR+LrSdA7ctp8MU+pAmW8Cu1Iubti5fYbRu1AgmMApURmnU9xuwHijWSD1T475qUAnCIqpZ/wTA2ewNozaMcRmaN+ByAd7WOLQbQCEw67WC9/SXYalljtu2bMyc4Ypm5FGG7ofqsBLFrPQTODsxD9SR2+vzJBjtxk8Ge9ufACpCv0N/cfS/PxjMPOY06kZiRZPBvdAqmWLJG0HDPpyN4HIar7zC9LdbooQXXDr4kGPBa+nBSe2PwlpNERrhxFQiLErq03CrDq9QyPHxFTmc54+bLDuLq0a+zUIE95OMY/hx1W0rDUItc8BKhJsOwfEKAZuwKIXVFQhPd4JSuLrrDgQ72wtmqO4tShdQPh/h/+4cvPkG78d4yVIR59Svf6+454J683C1tu2TNlgZEl1mhaHRQF8HNc20th6ewGIBy66TI3ojR8E408qRaQ8sWX0oaMbwKETuYlGU6DjqAhECE/90WtEb+xSApCuFS6MJtCfhjBIEeVvMLFfklqMUjY0V+kSZKrkks8TWyosKWa6ry3E8jk8Yl6bk8emYuDvf18foKja1euHQUrQ0Ou7l86J4fEHOlSWlOo1PP3UpVmdM8qkLOfZiJ5SwQcvo1aDrDu1Lue24HeS3Y7PHMcBYpmpJLaCRn7ud6meurfzdGu2fkW+jhVD3IePyOBoiJgyda3T/Cy2U4pg=) with examples of what's needed

### Proposed solution
1. show the default slot while the image is loading
2. emit the inner image event up to the avatar (load, loadStart, error)
3. add the ability to pass slots to the inner image component (placeholder, error)

**Comment by KaelWD** [comment]
> when the image prop is provided to v-avatar, the default slot is wholly ignored

This was fixed by a765a6ba30558e2fb0c7b35f78f5094795953ac2

You're also supposed to be able to use a v-img with no props and it will inherit src from the v-avatar, that was fixed by c264ad40
