### ISSUE TITLE
[Bug Report][3.1.15] Pagination arrows get stuck in the "active" state on mobile, even if there are no previous/next pages

### ISSUE THREAD

**Issue by antalasztrik** [vuetifyjs/vuetify#17228]
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.15.7, Android, iOS, Mac OSX

### Steps to reproduce
Navigate to the last paginated page of the VDataTable component. On mobile you should see, that the "Next" button still has the active color, even though there are no more next pages. The "Last" page icon gets the disabled color, but the "Next" doesn't. This works great on desktop, so this might be caused by the "Tap" action?

### Expected Behavior
When on the last page of the pagination component the "Next" icon should be disabled. This should be the case for the "Previous" icon too, when we move to the first page.

### Actual Behavior
The "Next" icon stays in an active state even when we are on the last page. The case is the same with the "Previous" icon when we go to the first page.

### Reproduction Link
[https://codepen.io/asztrik-antal/pen/VwEbyaR](https://codepen.io/asztrik-antal/pen/VwEbyaR)

**Comment by KaelWD** [comment]
`:hover` overrides `&--disabled`
