### ISSUE TITLE
[Bug Report][3.1.15] v-avatar size attribute does nothing when icon attribute is set to an icon

### ISSUE THREAD

**Issue by Tomdanizer** [vuetifyjs/vuetify#17224]
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Edge 112.0.1722.58
**OS:** Windows 10

### Steps to reproduce
Create an avatar component with the icon attribute set to an icon and the size attribute set one of the defaults or a number. 

### Expected Behavior
Size of icon to increase or decrease based on setting.

### Actual Behavior
The icon size does not change.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMtOwzAQ/BXjS0BqYlqeqtKq3PgDDnUPabIFQ/yQ7QZBlX9nHaeotEhQ9WbP7Mzs7HxDH4zJmjXQMc09SFMXHqZcEZI3aWFM9+w+shCq/0WyKXxhiSi1mnAqK5GiixerD06JE5+A4OiS02nOtrNHqu9PUg9vf5UH4LtJx3Ydc7bTHb+utMJ44sCvAy2k0daTDbGwIi1ZWS1JgpFJGMYlnCfSPZNJ4M+TR6hrTZ60rauz5CKYRzs0ogMavXAJk706rfDum7AL7wnH6Zh0SMAwI/w5ffHeuDFjZaVQVkEtGpsp8EwZyWY4xuxaeSEhrbScXWWj7PqOVcL5XTwDJ9Ol1e8OLLpwOtjJief7M6ufxIhhNryJET2W1sXShYwDb4aBDdjUgqrAgv1vpz3Zj1573EG3EN9y1eLJa6He3N61S9dder7d8rTSnVuwWoTEdkDjppgdJXTxBc3cIxA=)

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNqtUctOwzAQ/BXjS0FqYspbVVqVG3/AoekhTbZg8EtrNwiq/DvrJEWlPVAEN+/O7szseL7h986l9Rr4mGcBtFNFgGluGMvqpHCufbaFLqTpqw6si1Agk6U1k5zrSibEEuTqPefMyw+g5sU5vUurLFLhUOoCCZ1mYrv9S767f+Yb3RxJGBtf97dom0wmdhKj0pcoXWAewjrCUjuLgW0Ywoo1bIVWswGZGMRhsuUD0/6JTSJ+OngApSx7tKiqk8FZJO/oiIgPecdFJlz64q2h39pEL3kP+JyPWduJPdKIdc6fQ3B+LERZGVqrQMkaUwNBGKfFjMYErk2QGpLK6tllepFe3YpK+rDbT8HrZIn2zQMSS86HOzpdoD9q9ZMkMUpH151E30tUsfRR44BbkGANmCCYChDw2Jv21r7dtYcd3Bblm9w0FLmS5tXvpV36Nun51uXfjm7ZItUiKjZD3jkl7W6FLz4B65s2hA==

If you want to change the icon size put a v-icon in the default slot instead.
