### ISSUE TITLE
[Bug Report][3.1.15] Paragraphs and lists etc. inside tooltip lack margins/padding

### ISSUE THREAD

**Issue by MetRonnie** [vuetifyjs/vuetify#17230]
### Environment
**Vuetify Version:** 3.1.15
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Edge 112.0.1722.58
**OS:** Windows 10

### Steps to reproduce
Component: VTooltip

Use `<p>`, `<ul><li>` etc. tags inside a `v-tooltip`.

### Expected Behavior
Normal margins/padding are applied

![image](https://user-images.githubusercontent.com/61982285/234611583-85ce91f1-7050-4dab-9192-6eeb735df937.png)

### Actual Behavior
No margins/padding

![image](https://user-images.githubusercontent.com/61982285/234611120-307e19a7-85dd-41a4-aa70-532af45c1c54.png)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUd1qwjAUfpWQGzewDe6HgUTRu72D8SLauGbLH0laGdJ330lbXa0MhOUq55zvJ+fL5oTXzuV1JfAc0yi0UzyKJTMI0TrjzrXXttBcmr5q62ititIhmNhCqAXDobRHhi8YFumZ3p134QWSAXHkuOcfnrvyd0zJEDxirk2BuLGxFP5PRqWuKFTJZW9ICdzHM46UDHE0omSgQsllyXMK0LnEkIouIEoGwUEZ9l66iIKIVRpL7ayP6IS8OKAGHbzVaAKJTxJ4b00AKCSHFgnwEH0lHpNmpwJ8PMWdBHi7/DNYA391Sk9g/SAwPEdtJ/VAOtUMlzG6MCdkXxigwR/J2udGRGKcJiuAEV+ZKLXICqtXz/lT/vJGCkhl2M9F0NnO22MQHlQYng58ojx83+HVI8Fils9eO4u+lym+C8njRpuAYS185oUp4B/9vTuNaFd7jWY3uyX7hpkGIlfSfIVR2vvQJr05v/J/S7dqSWqbHJsp7l4K3h0Fb38AEsQmAg==)

**Comment by KaelWD** [comment]
This doesn't have anything to do with tooltips, vuetify's CSS reset does not include margins for `p` or `ul` in any context.
