### ISSUE TITLE
[Bug Report][3.1.16] VDataTable checkboxes are not vertically centered

### ISSUE THREAD

**Issue by mwshub** [vuetifyjs/vuetify#17235]
### Environment
**Vuetify Version:** 3.1.16
**Vue Version:** 3.3.0-beta.2
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Create a data table with `show-select` and `density` set to compact.

### Expected Behavior
Checkboxes should be vertically centered.

### Actual Behavior
Checkboxes are not vertically centered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1P2zAQx7+KFWliSCTpMxB1iAn2wNiLvZ0oL9zkCh6OHdluWYf47js3bpu4SVW05VV85/P97m87ubuX4GNRRIs5BEkwNpAXnBq4mAhCxoswo4aGhk45WAMhizCXGfAPk0ADh9RANglKT/IINAOl0eXeNh6Gq1p7BlqDMhuHtYcLyueATkFzWDsyEJqZJVpTmc+kKgGcUz/K57DMXhpSTrVdHk0LapgUYbecezGOqxVgTeO4UiAOdapYYVbFwu8CE2HqGZ1zQ14cCUaT98frISEKzFyJ7Rh5nBAJubs/2ZqdCGjd2kg1zj6GGQ4JOboulSHvu53OA66oFkw8HB9VlrMP5exB4GxtqDK+UzuZEjKjXIPnfYIlBlqN63GvtdHLBuiKcqkY6KMTF5quDa0hnynyW2gXMaOmffIVVVNdm55aS3vADyUNMFELKUpbe9CNkhjxbhvB0FCfXt2y9fncv2dWRFuukn9AkJ/yYb67GWu1EtIdnns+1CUho6izE4L1J6Q38OyuyIQMdkJsNZhh34Y2ot+kQFIFNCeaiuyZpY/t/L3+aRP/eRv/zvQKf/8/8X/CG8/UHuZRr4m52y66T7aB3g0poetVHgJ9NS9S+uRdvyp1vzNsou5HvqIOevRmpc/eDP0FP0OgpnhWsj3gw9Hb5B74V2JD3o98lzsj9QyHoH8DzpdkClTsIT9tlLzTBn7eejl3Q0rwuvUQ7u+Sc1bIYg/1eePx7kS+eU1d3/cqdSNzfZlDmL9KAUv8VU/boQcdn8Kd7hbos9bTPYr8TSuxB3XzIdzXUsz3fLsHw0ahe8O28zGsf8tqV7L5YPfeLvYtM7f4a22lHnYble61XseRr+eG2t+Dkrn9Lm5/pq/lS+nEwTh2rVZwErDcdlphTovol5YC285VoRPnwPYwWZc+CbAvtWNsKo0pdBLHaSYwDHtQtlCRABOLIo8vcVqs5sKwHMJM5pf9qB91wikYGvXijGlT9Uag83Cq5DP+7XGtSeCwV9kMmy0PyOhmYqJu1B2VKZwt5HSqbY6dtWPb2YEKFQjsDUEdWpkX1lCdN2OnQrcNryg/Z+JJe8qneqW6a3v+tfTVanape5vx9SSo8iJBGRjc/wV5ikA6)

**Comment by kingyue737** [comment]
workaround:
```css
.v-selection-control {
  contain: unset;
}
```
