### ISSUE TITLE
[Bug Report][3.1.16] VMenu mispositioned after orientationchange when previously open

### ISSUE THREAD

**Issue by mediafreakch** [vuetifyjs/vuetify#17234]
### Environment
**Vuetify Version:** 3.1.16
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Go to playground example
2. Enable preview mode (without editor)
3. Open devtools and switch to device mode, emulate iPhone SE for example
4. Rotate device
5. Click on hamburger icon to open menu
6. Close the menu and rotate device once more to portrait
7. Click on hamburger icon to open menu again 

### Expected Behavior
Menu is positioned so that its content is visible

### Actual Behavior
Menu is overflowing screen

![Bildschirmfoto 2023-04-27 um 08 57 00](https://user-images.githubusercontent.com/777093/234783807-691c105e-ecdd-45ed-b8dc-24fdc5ef2fee.png)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqlVE1r3DAQ/StCl01gZZO0tLAkJb0UCi299BbnoLVnE2VlyUizTrbL/vfOyPthOVACvRjP13vznmTf7+TXriv6DciFvEFoO6sRvlROiJte6a5LrylotXGHiOLG9KK2OsbbSjZqZeFVPG8imtVWgWsqeeocZsFthPW1RuMdTSw9om/zriO56FW0Hhe6RtNr9IH6d6ILvotiPwVeojvHQpjaZ3Gvg9EOCQHhFSuZ1dTSuIZKCTqvHZW1Vl3nlWj+ABViq62dzHibdn0MsFWNDmtw+fBo87Q7L3vEszo8QiWTAOZtTPKMMuVYcJkUn0+hzE7sgGtNxNwlzihDvbn+Vdr3ggtzsYbtpTCOZDj26iex/6CxXOOCumiEnv8SdqJTaNDCyU3GVUvfbNmXbEiI3U7whNjvMzASPEGb2HGqjkyZWMAJNnOUoNt7vNhcPN5sDoY7nzlLYayD6VBEwA2XTdv5gGInAqzEXqyCb8WMPqIZN5ODEac+ilvuvbhnmtl3VvrLwWx+eP/94s/vTwHOlW9+Ewj14ZJ3GrYgfjmXwwq0e1c8R+/o890xdnUo0IVeiJThHK3GcSWfELu4KMu6cTTWgDV9KBxg6bq2vKO2MmwcmhZU49u7D8V18fEzuRVxnC8gtmoZ/EuEQCiVnI94+BfwDq5DJ1FcFVefBopDTlm9jMzxBrskwh6CCvSLgQDhvZomY5muSe2NNqanO7kny61x6zhxu47J6XSuHP+f6ITGUA/MuJ/LYVPiHkbkw18iFMSI)

**Comment by xqqp** [comment]
Tracked this down to `getBoundingClientRect()` in https://github.com/vuetifyjs/vuetify/blob/4a2b2dbdd8faac73ec9b94c4ef40a847c3303624/packages/vuetify/src/util/animation.ts#L6 reporting a wrong width for the overlay/menu. But no idea why.

**Comment by xqqp** [comment]
Workaround: Calling `window.dispatchEvent(new Event('resize'))` a few times after the menu is shown, positions it correctly.

**Comment by johnleider** [comment]
As far as I can tell this is working correctly as of the latest version https://play.vuetifyjs.com/?preview=false#eNp9U01v2zAM/SuELmmBKNkXMCBoB+wyYMCGXXare1BsudMqS4JEe80M//eSSpxEPvRii3rkI98z/TCKFOvt1xA2Q6/FTtyh7oJVqL9UDuBukCqEfMxBp4w7RRQ3ZoDaqpTuK9HI1uoX+NsnNO1BatdU4px5rNWuB+trhcY7qth7RN+VWXNzGGSyHneqRjMo9JHyRwjRhwTTkniP7hIDmNoX8aCiUQ6JAfULVqLA5N64hqBMXWKzss7KDyWSzH9NQOqUtYsab/OsT1EfZKPis3Zl8dXkeXYeduazKj7pSmQB3Lcx2TO62V4L3mbFl6+wLb7YideahKVLfCMN5Zb62zzvDQNreNaHWzCOZDj26id1/0FlpcYdZVEJPd8Sdm4n0aDVZzeZV+59c2BfiiKAcQSugGkqyEjwgm1hxxm9MmVhAV+wmVcXtL3zYjM4bzYHx50vnKUw1dEEhKSxZ9h0wUeEEaJuYYI2+g5W9BOtOJkcTLj0Ee459+aB26y+s9JfTq/Wp/Pvf/5y/hP1Bfnm+0isj7c803EK6i+mtfi4+bT5LI7v9+/E4ytHIR/P
