### ISSUE TITLE
[Bug Report][3.2.1] v-select "itemProps.prependIcon" broken after 3.1.8 version.

### ISSUE THREAD

**Issue by men232** [vuetifyjs/vuetify#17247]
### Environment
**Vuetify Version:** 3.2.1
**Last working version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Provide "prependIcon" via props of "items".

### Expected Behavior
Icons should be displayed as in 3.1.8 version.

### Actual Behavior
Icons aren't displayed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu2zAQ/JUFL24BSYSTAAVUp0gPPfRcoJfIB1laI2xFiiApNYWgf+8uKbuq0yABcqL3NbMzWt9P4rO1xTigKMUuoLZdHfBTZQB2Y15bG3/GQNfKQNPV3t9Wwtb5TSWWYix77LAJQH19ix21pAS2lYBSETKPxZcS/OZBhQ4pGfAxnHJj3Q2ci+8paV1vIym/lJRn3jN/q8a/u4X8arUbwLdlkxKmCU5rwTyfpyWNn4TKpDRZQEHyYCdX3lDoG6dsILAwcFlp27sAEzg8ZvAAMxxdr2FDvm4YqDJNbzz3L+S33Plu+/4jo6Va9IYK9zwwAbtSQiW+sxOwrUQG0ZQSthlEJ0gO+OEQbVx1nnPk1Axz9j848udFuC+PNu2qaD/utw4tmvYrhSVsdKtykhfU8ffmWZ7rNc8zPXRHFz17cmUnk8VkrshE8pc+jC1++N7QrU7R1qVAR0Hbpw9It8OXw/gPIZAsKZvW0BhdpRpdYTBIY7W8ozbpBhOUxrzt9d11cVXcfKBT8GGdL9Dr/OD6Xx4dodCyKx5W/wqupTNSbBPDksq7+uCZ4gm0JL4RXe7IcnToXivpYuwfWRe1J9KYnv4VMzneKfPTX5jd+Gh0PFCO36Q5gjHSngnnTKRFiTpOiP0fkXmEaw==)

**Comment by KaelWD** [comment]
Broken by #16775, it used to display both prependIcon and the prepend slot.
