### ISSUE TITLE
[Bug Report][3.2.1] @click:row in v-data-table doesn't include item

### ISSUE THREAD

**Issue by ianmill** [vuetifyjs/vuetify#17243]
### Environment
**Vuetify Version:** 3.2.1
**Vue Version:** 3.3.0-beta.2
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Click any row in the linked example.
Note that only two arguments are sent to the click handler and that neither of them include the row item.

### Expected Behavior
The row item should be the first object sent to the click handler.

### Actual Behavior
Now item is sent.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8Fu2zAM/RVClzRAbG/tzUuHFPuFYZe6B8VmGq2yZEhM2iHwv49SZMdJuqFAHSA29cjHR4p8PIj9Dklt/uS/vSiFajvrCA5QO5SEv44Y9LBxtoVZ8p1VJvzwLTrX1niCBMH9eejNoTIAtMUWS6ZtcCN3mn4e7ZlWz1uaQb+oTD+vjFiIh67LmYqlLAnbTjPT98Cw3Gey6+JnNFqpTLKiTfhG2UahboBB26C+rwShp0pAMXVsJMmM5FrjcAjlFmWDznNE+qrECVSsI0DxPQFWtVb1S+nsa8r0I9iVOCUrptkG6Xw4ag/GsaplMamWTV871VF0Sl1OnYPYT4BAfDMfrPA4pJ0z0xPuO8sqYWgEd/kEpUpLeJyewnl85FCk+a4q8XDBEJ691LsIykln4tNPzaezwNjJ68RwSS4DsTV4lTfMy381x0h6tdeRZ6pORjofiFukrW1Y48g8XjDcsKIFMDn/bR3i2SWEXbAac22fg9/82/sQR/8TipwjOAgLL/5bFuNk8LIct5XnqePttYaXJkrhWY0AT+tYQRX2PNg840SdL4uibgyH8aaovcsNUmG6tlixW+F2hlSLWWPb1V1+l3/J1kgyvy0a5WmK5ujbbM0r4NEx19jumC2s/wcyJk9OdJt/PWZIR5mWax9SXFEXnG+PLnNoeIjRfbSwi7B3irvwuCow3UPP3dfKvPiLxtc+Nj2N9icrj2SBiQe1F/1CTOWygBgnnv4CBbi/bQ==)

### Other comments
From the documentation:
> This event provides 3 arguments: the first is the item data that was clicked, the second is the other related data provided by the item slot, and the third is the native click event.

**Comment by ianmill** [comment]
I think I understand what's going on with Proxy's better now, so this may not be an functional issue, just a documentation issue?

**Comment by nekosaur** [comment]
Yeah this is a documentation issue. The reason the click event is the first argument is so that you can use the event modifiers like `.stop`.
