### ISSUE TITLE
[Bug Report][3.2.1] `createVuetify` TypeScript regression: Default export of the module has or is using private name 'DateInstance'

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#17242]
### Environment

**Vuetify Version:** 3.2.1
**Last working version:** 3.1
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Ubuntu undefined

### Steps to reproduce

1. `npm init vue` with TypeScript
1. `npm i vuetify` (or `vuetify@3.1`)
1. [manual install](https://vuetifyjs.com/en/getting-started/installation/#manual-steps) - create `vuetify` object in a separate file
1. export / import it into main for registration

*src/plugins/vuetify.ts*

```typescript
import "vuetify/styles";
import { createVuetify } from "vuetify";
import * as components from "vuetify/components";
import * as directives from "vuetify/directives";

const vuetify = createVuetify({
  components,
  directives,
});

export default vuetify;
```

### Expected Behavior

no TypeScript error (vuetify 3.1)

### Actual Behavior

(vuetify 3.2)

vuetify = createVuetify()
export default vuetify

![Screenshot from 2023-04-27 16-38-51](https://user-images.githubusercontent.com/46688047/234985721-ac2a877f-2e40-426f-b7ad-0c5ecbfcc463.png)

export default createVuetify()

![Screenshot from 2023-04-27 16-39-12](https://user-images.githubusercontent.com/46688047/234985764-1b216bd4-0d6b-4191-bd48-15761e8d0bc7.png)

**Comment by MarkSky** [comment]
I also use the Version3.2.1, and I have the same error. When will I get the fixed version?

**Comment by jay-zahiri** [comment]
@MarkSky you can fix it for now by opening `node_modules\vuetify\lib\index.d.ts`and edit line 310

```ts
export { Blueprint, DateInstance/** <-- Add this **/, DefaultsInstance...
```

and edit line 315
```ts
import type { DateOptions, DateInstance/** <-- Add this **/ } from './labs'
```

**Comment by MarkSky** [comment]
I find it, thanks.
