### ISSUE TITLE
expansion-panel inside of v-dialog and the scrollable prop prevents scroll handling

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#1725]
### Steps to reproduce
Placing expansion panel into a v-dialog with prop scrollable prevents user to scroll as soon an item expandable item is opened. 

### Versions
0.15.7 

### What is expected ?
open close and scroll should work

### What is actually happening ?
As soon a list item is expanded, the scroll is prevented on the v-dialog element

### Reproduction Link
https://codepen.io/anon/pen/OxPmoN

**Comment by johnleider** [comment]
This is caused, for whatever reason, by the ```v-card-text``` having pointer-events set to auto. This will take some looking into.

**Comment by dohomi** [comment]
great!
