### ISSUE TITLE
[Bug Report][3.2.1] v-window next slot class incorrect

### ISSUE THREAD

**Issue by chris-siegemedia** [vuetifyjs/vuetify#17250]
### Environment
**Vuetify Version:** 3.2.1
**Vue Version:** 3.3.0-beta.2
**Browsers:** Microsoft Edge
**OS:** Windows

### Steps to reproduce
Using example from [windows page doc](https://vuetifyjs.com/en/components/windows/#customized-arrows) to create customized arrows using slots.

### Expected Behavior
Next Slide button should have class of bg-info

### Actual Behavior
First time through, Next Slide button has class of bg-success

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVMtu2zAQ/JWF0IMNhJLj3IQkSNt7W6DHKEBoaR0xpkiBpOUEhv69S9p62T4kbXWR9jU7O0vxcR99reu42WKURrcOq1pyh/eZArhtGK/r8BmMigvVBXZCFXoHttQ7xo3RO9vldRDQMCu1S2uDzV0W7aE2urbQZtExM+CsnOosgFxLbSjXbvMcrc2iIfSQS5FvKBZQYq2+e3vI6DEBflFDobcWrBQF9r2S0KxjmUwmvUBb4Zv7JG2h1vovOf+gbp/j262ACYp0RQ1bByYKhIKboVO6wXdyP+fcFOzLXrXPXWw8lI8OlFBiw53QigqX47FKFC+l12a5WIz9ueTWkrtga4lvwKV4USxH5dDA69Y6sX7vzIqzEeRIh9vyejAGSEfysHLCYlQE8NsrB/s9KGjbEVpSXg8DkqB+wl7RiYKHc937RknDqSfj8D9MtkGmzY2o3bEG32ptHBS45lvpYD/QKbjjKczmcHcPs5HfP2H3KSyuBnc7J2MwK3SlLmw6Rgzr4KqQ+I3nm1k4Z/PTBP9MTuBsPk1oJ30GTH8o/x+mddy4nw0aEuACmiuFjYMKcAeLc7D++/BJL7+HXvnoKhKVF572VcevViu6zkIb+i9DgK6TXrssovvO21lUOlfbNEnyQlFZgVI0JlboElVXyQOlJWarnKiQFbp6uIlv4gVboePxMimEdeNojLZiK38XoiGsLDrSDt388f9Ax2MmNVrG14cORxeTfGV9izPohPqRrsygKtCg+ehgJ2UXhjvJOBvQk6BNtKS+FGpjT4TP/R2ewmPH9Z8mD2Ae6ck3bK+iMV0iEOqipz8HTQkK)

### Other comments
- Click Next Slide until you get to the end. 
- Then click Previous Slide back to the beginning, then the Next button has the proper class.

**Comment by johnleider** [comment]
You weren't binding the props correctly:

https://play.vuetifyjs.com/#eNqtVE1P4zAQ/SujaA9UqpNSbhEgdve+u9IeCRJuMiUGx7ZsNwVV+e87dpuPFg5dQS7JfL158yb2/S75bkzabjDJk2uPjZHc422hAK5bxo2Jn9FouFB9YCtUpbfgar1l3Fq9dUAJukJ5UyROigqLpK/sQSnDSe1zY7GlrB0Yq42DbsiMyCuvegug1FLbgLgpS3SuSMYQZRKHiJOmaYSagyi1ymHNpcOA22cP+AB/qLnQGwd7kn3fLDbuGWdHOnwwgsJX/58jCLXWX8D/F3Xec3fnku+3xQRF+qKWrSMtBULB1dgqf8E3cj+W3Fbs2051j31sOmGIjpxQYsu90IoKl9MZaxRPdRBquVhM/aXkzpG7YmuJr8CleFKsROXRwvPGebF+682GswnkRIjr+nI0RkhP+rD6iMWkCOBvkA52O1DQdRO0rL4cByRBw4SDokcK7o/A4JskjQeEjP3ROdoGma60wvhDDb4abT1UuOYb6WE30qm45zlczODmFi4m/vDE5eewmI/ubkbGaDboa125fIoY18FVJfEHL18u4v82O00IT4ykWv2UgvJmxwndUZ8RM/yVX4fpPLf+d4uWBPgAzdfCpVEFuIHFe7Dhe/9Jr7CHQflknogmCE/7Mumz04puvtiGDmkM0D0zaFckdDUGu0hq743Ls6ysFJXRVSdamyr0mTJNdkdpmd0oLxpklW7urtKrdMFW6Hm6zCrh/DSaomvYKlybaAmrSA60Y7fw+5/R8ZBJjZbp5b7DwcUkX7nQ4h10Rv1IV2ZRVWjRnjvYSdkHw51kvBswkKBNdKS+FOrFnQhfhss9h/ue66cmj2AB6SE07ObJlC4RiHXJwz/HlhXl

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
