### ISSUE TITLE
v-text-field / v-model binding broke between 0.15.5 and 0.15.6

### ISSUE THREAD

**Issue by richcorbs** [vuetifyjs/vuetify#1726]
### Steps to reproduce

Go to the codepen below to observe the broken behavior on 0.15.6.

- type in a phone number
- it should be formatted as you type but isn't
- change the settings of the pen to point to vuetify@0.15.5
- type in a phone number
- the number is formatted as you type as expected

https://codepen.io/richcorbs/pen/zExNGe?editors=1111

### Versions
0.15.6+

### What is expected ?
Expect @keyup event to be able to set the value of the model and have it reflected in the v-text-field component.

### What is actually happening ?
The model is changing but the v-text-field is not being updated.

### Reproduction Link
https://codepen.io/richcorbs/pen/zExNGe?editors=1111

**Comment by KaelWD** [comment]
Possibly related to #1702

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/veEpOe?editors=1010
maybe useful for testing/solving

**Comment by khyoz** [comment]
the v-select @change does not run, seems to be same kind of error

if we use v-model="myDataVariable"  @change="myMethod" 
the value of myDataVariable is updated AFTER the method is called
in the method, if we try to check this.myDataVariable ---> undefined
but in debugger, we can see that the myDataVariable has the correct value after the method

this is why I need to select 2 times the item...in order to get the value before to call an ajax get request.

**Comment by KaelWD** [comment]
@richcorbs You should also be using `@input` instead of `@keydown`, it'll prevent that slight flicker whenever the value changes

**Comment by richcorbs** [comment]
@KaelWD Thanks for the tip. My eyes must be bad/old as I really had to study it closely to even see the flicker. 👍

**Comment by richcorbs** [comment]
@KaelWD Any idea when the next release of vuetify (with your fix) might be?

**Comment by KaelWD** [comment]
No idea, depends on when john has time to review and merge it. It'll hopefully be in another patch release within the next couple of days.

**Comment by ajsutton** [comment]
This issue appears to have regressed in 0.17.1 (or possibly 0.17.0).

**Comment by johnleider** [comment]
This was fixed with https://github.com/vuetifyjs/vuetify/commit/f0b26eccad393ffce152d4e477ef4fe987e82128 and will be part of the next PATCH on 0.17

**Comment by MarcosHespanhol** [comment]
try to use ':change' instead '@change', to me it worked.
