### ISSUE TITLE
[Feature Request] Add TypeScript intellisense for Labs components

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#17269]
### Problem to solve

Supported Vuetify components have TypeScript intellisense. Labs components do not.

### Proposed solution

Add intellisense. This likely has to do with some TypeScript formality?

### Details

Component registration via,

```typescript
import "vuetify/styles";
import { createVuetify } from "vuetify";
import * as components from "vuetify/components";
import * as labs from "vuetify/labs/components";
import * as directives from "vuetify/directives";

const vuetify = createVuetify({
  components: {
    ...components,
    ...labs,
  },
  directives,
});

export default vuetify;

```

Gets this,

![Screenshot from 2023-05-02 14-50-52](https://user-images.githubusercontent.com/46688047/235758981-c2c01ade-a838-4b03-9065-c31dd2626b5e.png)

![Screenshot from 2023-05-02 14-50-44](https://user-images.githubusercontent.com/46688047/235758988-1bbf5f59-cd87-47a7-b66e-7a032ef06130.png)

**Comment by kingyue737** [comment]
Workaround: add following declaration in your project

```ts
// component.d.ts
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VDataTable: typeof import('vuetify/labs/VDataTable')['VDataTable']
    // other lab components here
  }
}
```

**Comment by KaelWD** [comment]
Or import the component where you're using it instead of globally.

**Comment by aentwist** [comment]
This move makes the divide between core and labs components greater, not more seamless.

Most people do not import core components locally. Some labs components like VSkeletonLoader might be especially well-suited to global registration as they could see very high usage across an app.

Without discussion here I do not understand the rationale for this solution. I hope there is a good reason that this can't take place like it does for the rest of the components given that users register them globally in the same way.

Will additional work be required to support this behavior when moving components from labs to core? If so, then it may as well be addressed sooner, unless it would significantly slow down more important development? If not (that is, simply moving the components would automatically add the behavior), then this solution begins to make more sense.

Maybe I missed it, but at the very least it would be nice to include the above workaround in the documentation, instead of leaving it as an exercise to users to find this issue and the actual TypeScript shim. I understand that it might be a little hacky and you might not want to officially back it, but with this documentation change it would be nice to see *something* officially backed.

Thanks for your efforts here. Obviously all of this depends on the vision and priorities, but I think these concerns are enough to at least receive some explanation.

**Comment by KaelWD** [comment]
The divide is intentional, it should be a conscious decision to use alpha features. 

> Will additional work be required to support this behavior when moving components from labs to core?

On our side? No, everything in `/components` is automatically made available. You will have to remove labs imports when they are moved to core.

**Comment by aentwist** [comment]
Thanks for explaining [the shim](https://github.com/vuetifyjs/vuetify/issues/17269#issuecomment-1534052105) @kingyue737 . I modified it slightly based on the [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) rule [`disallowTypeAnnotations`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md#disallowtypeannotations). This is what I arrived at -

*vuetify-labs-shims.d.ts*

```typescript
import "@vue/runtime-core";
import type * as labs from "vuetify/labs/components";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    VDataTable: labs.VDataTable;
    VSkeletonLoader: labs.VSkeletonLoader;
    VInfiniteScroll: labs.VInfiniteScroll;
  }
}

```

**Comment by aentwist** [comment]
> conscious decision to use alpha

already is

- have to use explicit imports from vuetify/labs and registration
- have to pin an exact version of all of Vuetify just to make sure I don't get hit with alpha Labs changes on a patch release

**Comment by KaelWD** [comment]
Ok I see what you mean.

**Comment by aentwist** [comment]
Hmmm does this mean that in the shim will be unnecessary? In that case the docs might need updated/reverted, not sure
