### ISSUE TITLE
[Bug Report][3.2.2] VTextField: Editing number with comma unexpectedly resets caret position

### ISSUE THREAD

**Issue by josteinAtProresult** [vuetifyjs/vuetify#17275]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.3.0-beta.3
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open linked playground
2. Input a decimal number with comma _(e.g. 10,65)_ in the VTextField input.
3. Remove the decimals one by one with backspace.

### Expected Behavior
The input caret should remain in place at the end of input value while backspacing, like it does when working with decimal numbers typed with period as decimal separator

### Actual Behavior
When reaching the comma, the comma dissapears, and the input caret jumps to the beginning of the input field.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUkFugzAQ/IrlS1sp2GnSXqKkSj/QD4QcCCyqW2wse6GNEH/v2pAUJT1EKidmd3ZmdmHX8VdrRdsAX/E1grZVhvCSGsbWbZJZG18j0JkyI4oY4RuTUkFVMDxa2KTcNPoALuWMyHUBlRgKQ4fK8nf8pBuet8hasa5jxGN9f2bJs72c+AcwJFvLSWKCPnfKIvOATWgrbWuHrGMOStaz0tWa3dGqd4Gc18ZjNNyE/v3jXDw9PwTNQYXm+YwPEuRtxYevDR2pCxHSseFTTrmHjCkn6YBT/o5o/UrKvDA0RpdQrRMGUBqr5ZZo0jUGlYakqPV2KZZinhwAM7GUhfI47QrwOjm4+suDI62UzyZuqMrjDY4jk4wWYjE4jKWkyg4+WFxJS/JrwSUOTAEufNXbFrsY+2O5C8bVgiEE/QI9Xb9S5tNfHD738ei7U9Z/bR7FgtI+GPYzPo1LAeIc3/8AoJ8Ktg==)

### Other comments
Discovered in Vuetify version 3.1.6

**Comment by KaelWD** [comment]
Related: #14935

We can't control caret position with `type="number"`, I suggest a similar workaround to #16743 - cast the value to a number when you use it instead of `v-model.number`
