### ISSUE TITLE
[Feature Request]  Vuetify datapicker should be in new version

### ISSUE THREAD

**Issue by eguvenc** [vuetifyjs/vuetify#17273]
### Problem to solve
I think the date picker is a very basic component and one that exists in almost every module. I believe such an important component should exist by default in vuetify in terms of compatibility among other components.

### Proposed solution
By adding it to the roadmap, developers can be notified when it will be added. If it is not to be added at all, this can be stated explicitly and at least some information about the future of this core component can be given.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/labs/introduction/#up-next
