### ISSUE TITLE
[Bug Report][3.2.2] VCardTitle or VCard Titles should not be truncated

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#17278]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a long title in a VCard that exceeds the width of the card.

### Expected Behavior
Title should wrap

### Actual Behavior
Title is getting truncated with elipses.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUs1uwjAMfpUqZ9JMDGlSxSb2DrsRDqXx1GzNjxJTmBDvPqehUlcOsKqH+rP9/Vjdntm792V/AFaxNYLxXY3wJm1RrHve1EGlz6JoujrGV8nMidcHdJJl+KgVtgSvnp5GyAfwYBXXjbNpQWneOgO5PRAT9ShU9Dx2DivU2GXV9Hy0Ohb01sWA/7e+aohJmiuUE3GEE96IkV0Ei+PyfHREqJgwswXrtP2O5Vd0li54TqOSNTFKVhXbTCZZi+hjJUSjLE0q6HQfSgsorDeCbo/682fzXC7LpVA64gjxrt7HciBLTDtpLySojXcBuan9TDU3BuUBSRgxpfqOhQ2NiXCwqA1w5czgZfWSzUzwEqLh++COEQKxSLaY6CTHD2jdi0sSN9SC9HoIPNCPBQHCo5Fma39izXo30ZL8JV38smB5j24/mGa7X5FPELM=)

### Other comments
MD3 shows an example Card with a wrapped title. https://m3.material.io/components/cards/specs#ec74bd0e-a669-4be9-91ee-bfa60fbbe507

**Comment by Maqsyo** [comment]
a dirty fix for me is
```
<VCardTitle style="white-space: unset;">
```
