### ISSUE TITLE
[Bug Report][3.2.2] the width of cards in timeline are not equal

### ISSUE THREAD

**Issue by zhaolinlau** [vuetifyjs/vuetify#17288]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Put cards as timeline item and the width of cards are not equal

### Expected Behavior
The width of cards should be equal

### Actual Behavior
The width of cards are not equal

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdV1Fv2zYQ/iuEXrrBluQ6AQZ4SVYntZcmdVssKfZQ5YGWLhZriRRISqkX+L/vKFmqTKlG2j41MCyYvON933ciz8dPj840y7wiB2finGhIs4RqOAs4ISeFS7Os/FkOUsr4blSONUshYRyIebiMK9CngfNyHDjoFej60/J0GQKQwr0XEj1/gwK4HhL2O2GclAMVOGSyhg1amRUGA9XsMIJKhJ6ILBMKQ1p+gX58rMJ5kfHebq04fkvmnqFwQyqjTjicZ+mKhAlVCpnRhK24CzwiGr5o9yFGCsg7BraKTQbGo5GRoWSIg4oH8tQgcTYUBcgOQAONmdIJnDX8yyEKOPH37B2CaEaGZr5LvVyn8mUVqxaRafe4k+FabCg4MQ/0SyOGLz7Dr1wbBWclFtp6lja08ZF3817x3KNzgLHJbR+9iBVn7+WKcvYfyAlpMEU9V6bLeH0TvQ79DWQaaia46s/NUnN8iUm5gTXQpDeHgb4SrBO/YoABerC/J/ZboJKThZBwEKFfe7+42rx/cHFy7+S2rG1bXSFwqikRZlAVj/3Txk9UKFmmCRaL3JhxJym9O/zklHwyEI8VTrlDJuTFjK8QBSTjKzKnTL4YVnZzuNG8EDyimyGZw1LmVG7IeKTj2qfciVaM85wlEf6ofarDiU6x1pma+H7BqIeMQ4hFEoH0QpH6R6PRFzzYf5m9c9qKNmgzavYgBnszW5APNKY1zrZ8WtLe8ChXGjm/A/0g5NrQe2fKiKXxNgdliXypGqda5I3OI8wjucAHNKS+X17NavCV1WCPVVvna8pDQ/siyZcHlF7ScE11LLil7F+IeEfbmEe2tguRZjnqIDchAx4CeUt3cD+isMOmrWj6enp+QMk1bLjAv5WbDCiWRPtNxbm05RzJjpxpHjEEZXn64yJ2RAYWkbaUq8vZh+kBLf+IpdAsVMSkF3AWa4MlaC6ZJee4e7z+3qScqp9SU1MZ9FBpS5pfv18cUPRrFov57fVs9rzrxGVOH4CRBU3oRjH6PErFgoVSKHGvn6LrVyocH28X5ErEQpJzGsv8eZWQj5xhF443B0ZusGFRPS/v7k/TuVS9CnYpztBhaSakNr2w91kJjrclTAQheFEpDXhzwWa06oQCB69TZhw4Nfcw4rgswn6pkB4H7fMs9V+hmy9zbhopNxLpqyNv7B3/gc2r0u15D1TqLqV4UKj6MyIhwQZHs/vNE7B2niXEuELYTbkJXSoD0QntIx4mypV41wFpuv+nSbKW7cmybB1pBh7vDVvMOPaWa2UlO1RlorFNrFj+lOYymIl0ZwC3Q6ciitDlCufuf70ZaUU=)

**Comment by lioneaglesolutions** [comment]
I don't think it's up to `v-timeline` to set the width of the items - you can do this yourself by add `width="100%'` to `v-timeline-item` in your case - [example here](https://play.vuetifyjs.com/#eNrdV8Fu2zgQ/RVCwKK7sGW5ToAFvEm2TmpvmtRtsUnRQ5UDLU0s1hIpkJRcN/C/dyhZqkypRtqemgQRRM5w3nsjcjL8+OBM0nSQZ+CMnRMNSRpTDWc+J+Qkd2maFq/FIKGM70bFWLMEYsaBmIfLuAJ96jvPR76DXr6ufhueLkMAkrv3QqLnn5AD133C/iKMk2KgfIeMV7BBK8PXNQt1ZGIOh39YUTFuRRYDqljosUhToRDB8vP1w0MZfRAa7+3WiuM1VO8ZcjegMmyFw3mWLEkQU6WQHI3ZkrvAQ6Lhs3bXEVJA7hGwZWQSMhoOjSolAxyUPJCnBomzgchBtgBqaEycjuGs5l8MUcCJt2dvEUQzMjTzberFOpUtyliViFS7x60MV2IDwYl5oF8SMtwHKf7JlVFwVmChrWNpTRsfWTvvJc89OgcYm9x20QtZfvZWLilnX0COSY0pqrkiXcbru+hV6O8g00AzwVV3bhaa40eMi/2sgcadOfT1lWCt+CUDDNCB/SOxXwOVnMyFhIMI3dq7xVXm+rSXP/Zof8HeIW8EbNqqYoJTdTUxg7LO7J9EfqICyVJNsK5kxoy7TOldnSCn5KOBeChxit0zJs+mfIkoIBlfkhll8lm/tJuDj+a54CHd9MkMFjKjckNGQx1VPsUutWKcZywO8aXyKQ8uOkVap2rseTmjA2QcQCTiEOQgEIl3NBx+xkP/r9lXp41ovSajen9isFfTOXlHI1rhbIunJe0VDzOlkfMb0GshV4beG1NiLI23GShL5HNVO1Uib3QWYh7JBT6gJvXj8ipWvW+senusmjpfUh4Y2hdxtjig9JIGK6ojwS1lHyDkLW0jHtraLkSSZqiD3AQMeADkNd3B/YzCFpumosnLyfkBJdew4QL/5dykQLFc2l8qyqQt50i25EyykCEoy5KfF7Ej0rOINKVcXU7fTQ5o+V8shGaBIia9gLNYNyxBM8ksOcft4/XfJuFU/ZKaikqvg0pT0uz67fyAot+zWMxur6fTp10nLjO6BkbmNKYbxejTKBVzFkihxL1+jK7fqXC8v52TKxEJSc5pJLOnVULec4YdOt4qGLnBhkV1fLy7f0znUvYq2KU4fYclqZDa9MmDT0pwvFhhIrBh2hnwkoONatkJ+Q7evMzYdyruQchxWYj9Ui4HHLTH08R7gW6ezLhppNxQJC+OBqPB8d/Y2CrdnB+AStyFFGuFqj8hEhKscTS73zwCa+dZQIxKhN2UG9OFMhCt0B7iYaJcifcgkOZm8DhJ1rI9WZatJc3A451iixnH3nKlrGQHqkg0tokly1/SXAQzke4M4LbvlEQRuljh3H0F+Z5yCA==).

**Comment by zhaolinlau** [comment]
> I don't think it's up to `v-timeline` to set the width of the items - you can do this yourself by add `width="100%'` to `v-timeline-item` in your case - [example here](https://play.vuetifyjs.com/#eNrdV8Fu2zgQ/RVCwKK7sGW5ToAFvEm2TmpvmtRtsUnRQ5UDLU0s1hIpkJRcN/C/dyhZqkypRtqemgQRRM5w3nsjcjL8+OBM0nSQZ+CMnRMNSRpTDWc+J+Qkd2maFq/FIKGM70bFWLMEYsaBmIfLuAJ96jvPR76DXr6ufhueLkMAkrv3QqLnn5AD133C/iKMk2KgfIeMV7BBK8PXNQt1ZGIOh39YUTFuRRYDqljosUhToRDB8vP1w0MZfRAa7+3WiuM1VO8ZcjegMmyFw3mWLEkQU6WQHI3ZkrvAQ6Lhs3bXEVJA7hGwZWQSMhoOjSolAxyUPJCnBomzgchBtgBqaEycjuGs5l8MUcCJt2dvEUQzMjTzberFOpUtyliViFS7x60MV2IDwYl5oF8SMtwHKf7JlVFwVmChrWNpTRsfWTvvJc89OgcYm9x20QtZfvZWLilnX0COSY0pqrkiXcbru+hV6O8g00AzwVV3bhaa40eMi/2sgcadOfT1lWCt+CUDDNCB/SOxXwOVnMyFhIMI3dq7xVXm+rSXP/Zof8HeIW8EbNqqYoJTdTUxg7LO7J9EfqICyVJNsK5kxoy7TOldnSCn5KOBeChxit0zJs+mfIkoIBlfkhll8lm/tJuDj+a54CHd9MkMFjKjckNGQx1VPsUutWKcZywO8aXyKQ8uOkVap2rseTmjA2QcQCTiEOQgEIl3NBx+xkP/r9lXp41ovSajen9isFfTOXlHI1rhbIunJe0VDzOlkfMb0GshV4beG1NiLI23GShL5HNVO1Uib3QWYh7JBT6gJvXj8ipWvW+senusmjpfUh4Y2hdxtjig9JIGK6ojwS1lHyDkLW0jHtraLkSSZqiD3AQMeADkNd3B/YzCFpumosnLyfkBJdew4QL/5dykQLFc2l8qyqQt50i25EyykCEoy5KfF7Ej0rOINKVcXU7fTQ5o+V8shGaBIia9gLNYNyxBM8ksOcft4/XfJuFU/ZKaikqvg0pT0uz67fyAot+zWMxur6fTp10nLjO6BkbmNKYbxejTKBVzFkihxL1+jK7fqXC8v52TKxEJSc5pJLOnVULec4YdOt4qGLnBhkV1fLy7f0znUvYq2KU4fYclqZDa9MmDT0pwvFhhIrBh2hnwkoONatkJ+Q7evMzYdyruQchxWYj9Ui4HHLTH08R7gW6ezLhppNxQJC+OBqPB8d/Y2CrdnB+AStyFFGuFqj8hEhKscTS73zwCa+dZQIxKhN2UG9OFMhCt0B7iYaJcifcgkOZm8DhJ1rI9WZatJc3A451iixnH3nKlrGQHqkg0tokly1/SXAQzke4M4LbvlEQRuljh3H0F+Z5yCA==).

I did try with add .w-100 but not working at all, thank you anyway

**Comment by lioneaglesolutions** [comment]
@zhaolinlau did it work using `width="100%"`?

**Comment by KaelWD** [comment]
It is inconsistent though, should either remove `justify-self: flex-end` from the inverted items, or add `justify-self: flex-start` to the others.

**Comment by murphy1312** [comment]
You can define the grid column width like the following (ratio here: 3:1:3)
````
<v-timeline style="grid-template-columns: minmax(0, 3fr) minmax(0, 1fr) minmax(0, 3fr)">
 <v-timeline-item class="mx-auto">
 ...
````

 This will keep the timeline centered.

**Comment by zhaolinlau** [comment]
any update?
