### ISSUE TITLE
[Bug Report][3.2.2] v-banner expands when position='fixed'

### ISSUE THREAD

**Issue by JulienChampagnol** [vuetifyjs/vuetify#17281]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Apply a fixed position to a v-banner component

### Expected Behavior
v-banner doesn't change size

### Actual Behavior
v-banner does change size

### Reproduction Link
[https://codepen.io/BotellaA/pen/oNaoZeG](https://codepen.io/BotellaA/pen/oNaoZeG)

**Comment by KaelWD** [comment]
Yeah that's how css works, you can't limit it to the card unless you use `contain: layout` or something similar to create a new stacking context.
