### ISSUE TITLE
[Bug Report][3.1.4] Click event for custom icons

### ISSUE THREAD

**Issue by unkobweb** [vuetifyjs/vuetify#17295]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
I created custom icons with eva icons but when I use it in append-inner-icon of a v-text-field, if I use the @click:append-inner="anyFunction". When I click on the icon, the function is not trigger and the input just is focused

### Expected Behavior
Function is triggered

### Actual Behavior
Input is focused

### Reproduction Link
[https://github.com/unkobweb/smart-study-web/tree/develop](https://github.com/unkobweb/smart-study-web/tree/develop)

**Comment by KaelWD** [comment]
If `eva.replace()` does what I think it does then this is the same as #3505, vue is losing the reference to the element.

**Comment by unkobweb** [comment]
Ok thanks for your answer, so it's better to I extract all svg and create a .vue for each icon and link them in my configuration ? (don't know really where for the moment but im sure documentation/tutorials will help me :smile: )

**Comment by KaelWD** [comment]
Depends what the icon library provides. If it has svg path exports you don't need a separate component for each, just do something similar to our mdi setup in the docs:
https://github.com/vuetifyjs/vuetify/blob/507d87eba74f72157f2537388e53eaaf553d427b/packages/docs/src/plugins/vuetify.ts#L33-L38
https://github.com/vuetifyjs/vuetify/blob/507d87eba74f72157f2537388e53eaaf553d427b/packages/docs/src/plugins/icons.ts#L336-L341

**Comment by unkobweb** [comment]
Ok thanks a lot i updated my Icon.vue component like that : 
````html
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" v-html="svg">
  </svg>
</template>

<script setup>
import * as eva from 'eva-icons';

const props = defineProps({
  tag: {
    type: String,
    required: true
  },
  icon: {
    type: String,
    required: false
  },
  fill: {
    type: String,
    required: false
  },
  disabled: {
    type: Boolean,
    required: false
  },
})

const svg = ref(eva.icons[props.icon].contents)
</script>
```
And it works ! I can now use click event on append-inner-icon !

Thanks a lot ! <3
