### ISSUE TITLE
[Feature Request] Mention Featue f.ex. within the autocomplete component or as a whole new component

### ISSUE THREAD

**Issue by paulwer** [vuetifyjs/vuetify#17290]
### Problem to solve
Hey everyone, is it possible to add a feature for the autocomplete component, to mention other people and/or use commands within the input itself.

### Proposed solution
Take a look here: 
https://css-tricks.com/so-you-want-to-build-an-mention-autocomplete-feature/

Would be a great addition and a great unique featue as a whole.
An other idea could be to implement this within a component called editor, which can be more customised.

**Comment by KaelWD** [comment]
Duplicate of #6820
