### ISSUE TITLE
[Bug Report][3.2.2] v-switcher inset mode with color safari bug

### ISSUE THREAD

**Issue by mr-africa** [vuetifyjs/vuetify#17300]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open link in safari
Fast click to switcher many times.

### Expected Behavior
color should change smoothly

### Actual Behavior
Opposite side of switcher button change color with delay

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUc1uwyAMfhXEaZOaIG2TJlVZ1T1H6YEGV2ULBBknXVXl3Ucg0br20J7AH/j7sTdn/ul92XfAl7wisL5RBCvpGKv6IhwN1YexYKwvbKuh+ZA8nZJn+GA0FBpImSZkxLgAlK9127QYOzwaq/CUe1aVmJmjTiUuRKtQo/GU5OHHt0hMw151DbFzZtSKFHt6nkvGEKhD91czluwtGWEHixkd8mVIQCwqMSnxBW+M+w7lV2hdHEHikbwOQfIl2+Q2yQ9EPiyFqLWLPyO/6bF0QMJ5K+LwyOxP69fypXwR2gSaoaJRu1AmspFpK90QBY0dkxVW+SvV/JCUpzySR6axvmNhHb8J7BwZG7fR2uTl7T2bucBLCLbYYXsMgJFF8mlCSWd0/IDWvbhR4oZaRL0esEBwGhDw0UhXbf9iXb3dRJtWPfBhwXNfnH0yzbe/o9j7wA==)

https://user-images.githubusercontent.com/3126299/236447980-9fd7382e-1aea-46ac-8009-74bd0dbedce0.mov

**Comment by KaelWD** [comment]
Report to https://bugs.webkit.org/

**Comment by mr-africa** [comment]
Hi @KaelWD can you explain please why I should report it to webkit bugzilla? 

It's a problem with vuetify component implementation. I suppose webkit developers will not solve issues in your library.

I tried to use switcher from w3cschools https://www.w3schools.com/howto/howto_css_switch.asp and it works fine in safari.

**Comment by KaelWD** [comment]
It's clearly a rendering bug, that isn't our responsibility.
