### ISSUE TITLE
[Bug Report][3.2.2] v-label sass variables don't work

### ISSUE THREAD

**Issue by mwshub** [vuetifyjs/vuetify#17302]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
1. add v-checkbox, v-radio, v-label, etc.
2. modify variables such as `$label-color`, `$label-disabled-color`, `$label-error-color` and `$label-letter-spacing` in settings.scss.

### Expected Behavior
The color of the text will be changed.

### Actual Behavior
The spacing between letters has been increased, but the colors have not been changed.

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-dw77gf?file=src/App.vue](https://stackblitz.com/edit/vitejs-vite-dw77gf?file=src/App.vue)

### Other comments
The current color of the text is too light, which is why I need to customize the color.

Related to [#16928](https://github.com/vuetifyjs/vuetify/issues/16928).

**Comment by lioneaglesolutions** [comment]
https://github.com/vuetifyjs/vuetify/blob/b18bde952834e103054456e71e9a5f691daaa86d/packages/vuetify/src/components/VLabel/_variables.scss#L4

https://github.com/vuetifyjs/vuetify/blob/b18bde952834e103054456e71e9a5f691daaa86d/packages/vuetify/src/components/VLabel/_variables.scss#L5

https://github.com/vuetifyjs/vuetify/blob/b18bde952834e103054456e71e9a5f691daaa86d/packages/vuetify/src/components/VLabel/_variables.scss#L7

It looks like there were a few other variables introduced in https://github.com/vuetifyjs/vuetify/pull/14359/files#diff-6e2ab35094d273d04f94386767bad15de636d9daacf92de5125b46d6a3065dda

I can see they were used in this merge into `next`;
https://github.com/vuetifyjs/vuetify/pull/14359/files#diff-f6b0995d964f4e5cf4eb1e3f1ee04d4fdef5a8586974c8a7092ad6f113bd9dd8R22

But I can't seem to follow it from there to see if/where they were removed.

**Comment by lioneaglesolutions** [comment]
Okay I can see they were removed in https://github.com/vuetifyjs/vuetify/commit/ae01ce44e6e38ab3c086b1da32a9b433cd09e72e but the Sass variables remain. To me error/disabled/color should be control by the theme and the new defaults, not Saas variables so I assume the variables just need to be removed - @johnleider any insights on this one?

**Comment by MaxenceMouchard** [comment]
I spent a long time trying to understand how sass variables worked with vuetify. Now I see that it's just an inconsistency or a bug ...

Like @mwshub I confirm that the override of a variable such as `$label-color` makes absolutely no visual difference, which is not the case with `$label-font-size`, which works as expected, for example.

A component such as label, so simple and useful, shouldn't be reporting this kind of problem. It would be reassuring if this kind of issue could be handled.
