### ISSUE TITLE
Text Fields with autofocus don't consistently work in dialog

### ISSUE THREAD

**Issue by JacksMyth** [vuetifyjs/vuetify#1731]
### Steps to reproduce
Open the Dialog, note the text-field is not focused sometimes.
If it was focused, close the dialog, open the dialog again, notice it is now not focussed.

### Versions

Latest 

### What is expected ?

I expect it to be autofocuses on render, i.e. every time the dialog opens 

### What is actually happening ?

It usually works the first time the dialog opens (at least in my application), but in the code pen doesn't seem to work even for the first time.

### Reproduction Link

https://codepen.io/anon/pen/JroVzr?editors=1111

**Comment by smares** [comment]
The dialog is rendered the first time it's opened if lazy-loaded or when the instance is mounted if not lazy-loaded. The autofocus is simply an HTML property. If you open the dialog a second time, it was already rendered and the browser already focused the textfield inside it once.

**Comment by JacksMyth** [comment]
Thanks for the response! Is there anyway to have it work each time the
dialog opens? Perhaps destroying and recreating the modal content on the
Dom?

**Comment by smares** [comment]
The way I do it is simply call focus() myself. I am not at the PC right now, but IIRC you need to set a ref property to your textfield and you can access it programatically using this.$refs.yourrefname.focus().

**Comment by nekosaur** [comment]
Another options is to put a `v-if` on the text field that uses the same variable as the dialog v-model. that way it should be recreated every time dialog is opened.

**Comment by flybayer** [comment]
@JacksMyth issue #1353 has a solution I'm using

**Comment by JacksMyth** [comment]
Thanks everyone for the responses. Both the `v-if` and `this.$refs.focus.focus();` options did work really well. I'm going with the .focus() since it'll save recreated the component every time. Appreciate the help all
