### ISSUE TITLE
[Bug Report][3.2.2] v-switch in v-list-item-action is not aligned with other checkboxes

### ISSUE THREAD

**Issue by jfrs** [vuetifyjs/vuetify#17312]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Put a `v-switch` in a `v-list-item-action`.

### Expected Behavior
According to https://vuetifyjs.com/en/components/lists/ `v-list-item-action` supports checkboxes and switches.

### Actual Behavior
The switch is not properly aligned with other actions.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9UstqwzAQ/BWhXiML0kIhpCGln9BjnINibxs1tiykjdMS8u9dKXbqR6GBQm7a0ezO7jCrI3+2Nqn3wGd8jlDaQiEsUsPYvBbK2viMRam0aapYG1Xrd4W6MiJ36gCOWXClMmDwQovEQntkxO6gF1xo0mSosYCnlL9sIdttqs+U97jEbjdjd9aBBZMPCP2BQmVhL+ZRue4yHW7WSIkNmsVcDoDRcCIMpw9XlD33fu3s/fzpxutBY7a9gRc+CrGtzkHkgEoXPlpyxm9gRov/xIuAUb7aKNLfJYuhOKe0J8knXJe2ckhMm3z4ylC8j6EhbT58ymcsIgGj/Ic65VtE62dSZrmhthwKXbvEAEpjS7kkmnR7g7oko6pyeZ9Mk4dHmdPqXTwBX4qNqw4eHE1J+aSjg/rt6wqthhklpmeFBhKF2vggMRotSa8GJxxlAhy4a08atPXOGvyNTgvyp9ScyPFCm50fmJ35aPSq3fJfN8dhYdI6CJ4m/LwoSccOvv4GfUd8CQ==)

**Comment by lioneaglesolutions** [comment]
V2
<img width="377" alt="image" src="https://user-images.githubusercontent.com/61766491/236926814-84a65916-ce08-4e16-9951-930af58af4a4.png">

V3
<img width="270" alt="image" src="https://user-images.githubusercontent.com/61766491/236927335-e5e75443-95c2-4a14-8858-8de2745d8063.png">

Will need @johnleider to confirm what the alignment should actually be here.
