### ISSUE TITLE
[Documentation] Bad document style for VDialog.theme

### ISSUE THREAD

**Issue by DevDengChao** [vuetifyjs/vuetify#17324]
### Environment

**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Just visit the website.

![image](https://user-images.githubusercontent.com/16363180/236980018-ff34d424-2d32-48e2-a2c6-a8828e1a893b.png)

### Expected Behavior
Document should be rendered properly

### Actual Behavior
No. It looks strange.

### Reproduction Link
[https://vuetifyjs.com/en/api/v-dialog/#props-theme](https://vuetifyjs.com/en/api/v-dialog/#props-theme)

**Comment by MajesticPotatoe** [comment]
try clearing cache / disabling ad blockers
