### ISSUE TITLE
[Bug Report][3.2.2] Chip Group is stuck in "column" mode

### ISSUE THREAD

**Issue by abea** [vuetifyjs/vuetify#17321]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Mac OS 10.15

### Steps to reproduce
Create a chip group with enough chips to overflow the width of the container. Do not use the `column` prop.

### Expected Behavior
The chips should overflow in a single row with arrow buttons to scroll through the hidden items. This is at least suggested by the documented column prop. https://vuetifyjs.com/en/components/chip-groups/#column

### Actual Behavior
With or without the `column` prop, the items wrap around and there is no overflow row.

The `column` prop does add the `.v-chip-group--column` class, but even without that it still wraps since the chips have `inline-flex` for their display mode.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU01v2zAM/SuELm2ByF67AgOCtGixYdjOG9ZDnYNqM4ka6wOS4iYI/N9Hy05ipYc2QGD5kXyP5LOe9+zR2qzZIJuyWUBlaxHwvtAAs4Y78wavGx/kYndXMG9FiVw4s9FVwWJOzCpNDfT3lCI2wRxDMehXiOHwDoA1NiJIoyn5+kvBTpGyFr6jsDt+C3bLr0/BI18vt5KWL6kLe4IBlNCVCMbtxqAnuTJgxQ/kAbeBWyeVoMSR+EjhqDGGABq+MK5jEEuQGujhxwTdb7rGbk0USiMJOcB+31VD2yaaeS86HnWA+llPOyU4LvVgQJdm6t4yOpNndJ7lIy9nvnTS9gW4tcYFqHAhNnWAfU9CqxNTuLyCu3u4HDCIQ07h+dTSxZNx64vJCPhlFMJvZZ1pUKEOSfCfKKPXCfjTmCoBfjjxhs4n2J+VsVbqZQI+upT+L5arBPjukPQahCcnQ1I9H07tVTzQ6mf5sBQ2YbXUa5+9eqPpEsTpC1Z68vc4fMFWIVg/zfOy0pRZYS0bl2kMubYqp+vT3ZGHr9lNdpNX0ocDxGvx4rNI1jHNC92SoFSdCVwJe6baB6Ly4ELBiKl7/6CFB0rL3UYHqZBXRsVebr/1zYzwDL3iL/SReHTEUrBhM1Gn6/gTWh+NSxLvqHPSa9Bxh7pCh+6zI52VJWOdxd6NNljdsnbC+jrafWyazf8D3Sx/cQ==)

**Comment by lioneaglesolutions** [comment]
It looks like this functionality hasn't been ported from V2 

https://github.com/vuetifyjs/vuetify/blob/e55f598bff7d7c097192c128cf21dea4cffb9a48/packages/vuetify/src/components/VChipGroup/VChipGroup.sass#L10

**Comment by CamilleXin** [comment]
any updates for this story?  How to show arrows when have many chips in chip group??
