### ISSUE TITLE
[Bug Report][3.2.2] v-data-table items-per-page-options prop not effective.

### ISSUE THREAD

**Issue by freddy-daniel** [vuetifyjs/vuetify#17326]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Edge 113.0.1774.35
**OS:** Windows 10

### Steps to reproduce
items-per-page-options prop not working

### Expected Behavior
It should show described options

### Actual Behavior
It is showing default options provided by vuetify

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdV9lu2zoQ/RVCwEVawFosL0kE36JFurcPeS3qPNDSxGUjkQJJu02D/HuH2iLTolo3TyJn4TmHM/Tk64P3qiyD/Q68xFtpKMqcanix5oSs9n5GNfU13eRgNgjZ+4XIIE8YOiq/BOmXdAv/r71q4xrkNS7XXu1sefmi1Exwhd5fawdCHvY030FCptGEaKZz/DybRmePE9sh7jnEQw6znsMMHWr7TYflG9AMpDm8+TpEifsZKAVSdwaz71fZ0chp0fFKc6pMAOSwp4aSP61NL1ZhXzIUcRX2FF2pVLJSV9rCz1JITTK4pbtck4c6s4klz563S0Ik6J3kT+saVSt0QhadDoQ0vBLSqVvp01+QTqLXNVnybBpFW4Kfe8a3z8966cwfzdmWo7fSVGrbqJCAoZmQW5orsKx3cI+BRrbDuKebq9B1gK5oLiQDdTbpTgWe4apOlLZmZ4K3FNkYCoPxt1S7Q6+o3KiR4NTY3eHXUmhgfCRBWXu4U3yQAuP/c8UzNB8G3/S+28Idv3lzFUYmKX4BJ1/Ednd8pa3K2JCLS8uGCiZkGURHIagN9ufc2m8oJ2R+FGLYmD4fLYxB8B8hz+/JBih3I5+d95uiQx65kF86kR+HNMij05F/YvoTlqAT9WJ6MYQ6dgq+tFl2sM+HQS9PB/0GXzom3aDjZTwEeuqukpkL9HFIA/v8dNjv8CkDuZH4Ho6UyWJ5Gva53RAd9llgm9oK/wfNP6RAUoReEEV59oOl30b0n9l3XXG4dFE4cu81qX0z/96kn0Wes1KUI9pfDtZNFNjbbYvavfHUosOo49NRX+3KlN5ZP1YHoKPBd2UW2KK2DXq62Benw34vONynoti4gc+jwadl5lL7wgl8GdgSNMDni9ORvxZ8N/IgzheDNRIvXMW9mLr1dvRnPFInTz+wzShZG3GxCps5zpt4OeN3KviuBMfpueK59lKFI2T3W4zzptalSsIwzTh64vTM9jLgoENeFiHO3Zrd3r/E2wjiMGNKt1t+TjcqqJKZTDdr/ogHssLMjX5BS+vU2lCd3Oi99jCTWf8Bwkt0C+WOa1aAn4miwjI/r8H09gNQhb+R4gcOG5hl7TUKVecYxH9x1p/o4hFHqUMzneL/EBInIpAg/5aSFXZAy7IdUWuu+tF7nHh1HGpfgfZufgM0YXGS)

**Comment by KaelWD** [comment]
This was only added in #17263, please check nightly builds or wait for the next release.
