### ISSUE TITLE
[Feature Request] I need the global ripple effect of the theme switching function on the official website

### ISSUE THREAD

**Issue by Lin-Yuhao** [vuetifyjs/vuetify#17333]
### Problem to solve
I need the global ripple effect of the theme switching function on the official website, and I hope to add it to the function. Additionally, I would like to know how to implement this function. Thank you very much to the production team.

### Proposed solution
null

**Comment by KaelWD** [comment]
The documentation source code is all available in this repository.

**Comment by Lin-Yuhao** [comment]
> 文档源代码都在此存储库中提供。

Can you help me find the specific location? Thank you

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/App.vue

**Comment by Lin-Yuhao** [comment]
thank you
