### ISSUE TITLE
[Bug Report][3.2.3] Build error for new projects created using create-vuetify

### ISSUE THREAD

**Issue by romcheg** [vuetifyjs/vuetify#17334]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.1.16
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create a new project using `yarn create vuetify` command
2. Build it with `yarn build`
3. See the error message

### Expected Behavior
It is possible to build a new project with a `yarn build` command.

### Actual Behavior
Running `yarn build` fails with the following:

```
$ vue-tsc --noEmit && vite build
node_modules/vuetify/lib/index.d.ts:313:34 - error TS2307: Cannot find module './labs' or its corresponding type declarations.

313 import type { DateOptions } from './labs'
```

### Reproduction Link
[https://github.com/romcheg/vuetify_bug_report](https://github.com/romcheg/vuetify_bug_report)

### Other comments
The issue seems to be introduced with the following change: https://github.com/vuetifyjs/vuetify/commit/78853f592ed415f40b994763a9ced0e64226e0f1#diff-6ba123b76a7882f99c746ce10543c759fae4bd4a0e691165327f6c53ccafeb9fR5-R6

**Comment by Gitopolis** [comment]
I fixed it by removing this line from node_modules/vuetify/lib/index.d.ts
