### ISSUE TITLE
 no support for nested searching with the default search function in VDatatable

### ISSUE THREAD

**Issue by MustafaHussaini** [vuetifyjs/vuetify#1733]
nested searching in data tables for object columns is returning null. like props.items.color.r
even using nested value in header.value.
codepen :https://codepen.io/MUHU/pen/oGXgKE

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.

**Comment by MustafaHussaini** [comment]
sorry about that john!
I will do in the future.

**Comment by AGPDev** [comment]
+1

**Comment by hpo14** [comment]
I think MustafaHussaini gave a codepen link that clearly shows the bug.
Even the newer version vuetify, this bug still exists.

**Comment by johnleider** [comment]
@hpo14 We have a specific process for reporting. This is to help ensure that all the data we believe is necessary to fix an issue is available. We also provide an issue creator to make it even easier, https://issues.vuetifyjs.com
