### ISSUE TITLE
[Bug Report][3.2.3] TS2322: Type 'string[] | Option[]' is not assignable to type 'readonly string[] | undefined'.

### ISSUE THREAD

**Issue by kalimerre** [vuetifyjs/vuetify#17336]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.1.16
**Vue Version:** 3.2.47
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
I'm using vue-tsc (v1.6.4) and it reports this error to the line of 
```
error TS2322: Type 'string[] | Option[]' is not assignable to type 'readonly string[] | undefined'.

160       :items="options"
          ~~~~~~

  node_modules/vuetify/lib/components/index.d.ts:34228:5
    34228     items?: readonly T_1[] | undefined;
              ~~~~~
    The expected type comes from property 'items' which is declared here on type 'Partial<{ flat: boolean; reverse: boolean; type: string; error: boolean; active: boolean; direction: "horizontal" | "vertical"; transition: NonNullable<string | boolean | (TransitionProps & { ...; })> | { ...; }; ... 32 more ...; openOnClear: boolean; }> & ... 4 more ... & Record<...>'

```

My options is declared like this
```
options: Array<string> | Array<Option>
```

### Expected Behavior
vue-tsc should pass

### Actual Behavior
vue-tsc is failing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU01v2zAM/SuCLtmA2ALWAQOMbGhRbL0MvRd1DnLMbFpkyaBod0Xg/15Kdho3Rb98sUk+vvcoyrd7edG2ed+BLOSKoGmtJvhROiFWfRbAwoZiEJ8+a3wN9nspp7w8VArDnYEL6X3MxzAjQxZiEzHzSa3Xtos1XVV4KClWX6mZFQ7DBk1LyRb8bz2SqGGrO0tiPzbVmrT49PkQCoFAHbpjLMRouhB7kZwUYvHLejS1XixF1I+J3wsxLI8taZxC3B4z4iPtc/AVePxjZuCri5fB11ChDrsZ+vrny+hLbc3Wo5uzX77KfiduPO5m7DdP0evH72H8GIscrNS0CrmU1rhdyP8F7/jupIMu5Sbw+h9PrJR/idpQKLWpHSP59pgecwekXNsovnVktvfnZ/mX/EzVJtAhlVldhTyRRaZ16QYWNE1cfdbo9kR1LCTlaeGlZKYYv2HhnGEKO0emgaz2TfLy9dtoZpbPITRZhf4uADJLKacTSjrR8Tu03hqXJZ5RK9brATMEVwMC/yTvG+mk7clYJ7Vno02rHuSwlGMfn30yLdcPHFZO5w==)

**Comment by KaelWD** [comment]
I don't know how you expect me to debug a typescript error without providing any types.

**Comment by kalimerre** [comment]
@KaelWD Which type do you expect? I have provided the options type which is used in the `:items`. Isn't it enough?

It looks like this

```
interface FdeSelectProps {
  modelValue: string
  disabled?: boolean
  hideAsterisk?: boolean
  infoText?: string
  label?: string
  name: string
  validations?: BaseValidation
  options: Array<string> | Array<Option>
  iconName?: string
  placeholder?: string
}

/**
 * props
 */
const props = withDefaults(defineProps<FdeSelectProps>(), {
  disabled: false,
  hideAsterisk: false,
  iconName: '$dropdown',
  infoText: '',
  label: '',
  placeholder: '',
  validations: undefined
})
```

Small addition : the issue is present for FdeSelect & FdeAutocomplete

I've also tried to downgrade to vue-tsc v1.4.4 and the error is the same.

**Comment by KaelWD** [comment]
> FdeSelect & FdeAutocomplete

I don't know what that is

> I have provided the options type

You just said `Array<Option>`, that could be anything. I also don't know what other props you're using, it has a generic type so any of these props can affect it: https://github.com/vuetifyjs/vuetify/blob/7264a1273a136d6fa164406b21bc379d96f73398/packages/vuetify/src/components/VSelect/VSelect.tsx#L89-L93

**Comment by kalimerre** [comment]
> I don't know what that is
Select & Autocomplete component my bad :smiley: 

> You just said Array<Option>, that could be anything. I also don't know what other props you're using, it has a generic type so any of these props can affect it:

Option is a custom type defined like this
```
type Option = {
  html?: string
  icon?: Component
  key?: string
  text?: string
  value: string
}
```

**Comment by kalimerre** [comment]
@KaelWD We think the issue is more on our side, as you can see on the image, the type for the items is either an array of String **or** an array of Option (type declared in the previous comment) and it looks like that the item type is expecting one type only and not two types separated by the union seperator.
![2023-05-10_12-35_1](https://github.com/vuetifyjs/vuetify/assets/5664180/9cf67f6b-9776-4e30-8a38-512123244b61)


As a workaround we could redefine the options const like this which would return one type only (array of Option)
```
const options = computed<Option[]>(() => (props.options.map(option => {
  if (typeof option === 'object') {
    return option
  }
  return {
    text: option,
    value: option
  } as Option
})))
```
And then it would give only one type to the items 
![2023-05-10_12-48](https://github.com/vuetifyjs/vuetify/assets/5664180/8c1b60d4-f2f6-47e2-bc57-6a80b387f1bb)

Question is more : why/how it has changed from Vuetify v3.1 to v3.2 ? Was it an issue before but not reported to vue-tsc or a regression had been introduced with the update ? 

Thanks!
