### ISSUE TITLE
[Bug Report][3.2.3] VSelect attach property not works and menu-props with property attach not works properly

### ISSUE THREAD

**Issue by horodynskyi** [vuetifyjs/vuetify#17337]
### Environment
**Vuetify Version:** 3.2.3
**Vue Version:** 3.2.41
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create component v-select and add attach property (attach property not works) or add menu-props with "attach" property with value of id of your v-overlay. When i am clicking on content of v-select dropdown this dropdown is closing and don't throws click event to slot:#item

### Expected Behavior
v-overlay attached to v-select and click on content do not close dropdown and throws click event to slot

### Actual Behavior
dropdown is closing and slot#item do not get event

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?ref=github#eNqlU8uO2zAM/BWtLmmByG4T9OJmF9tb/6CHOAfHZhp19YJEu1gE/vdSsvNYx0ULbHKwJQ7J4Qy9PfFvzmVdC7zgGwTtVIXwVBrGNp2onEuv6aAracZTOgdQUCOrj9IFdr6//nSrUDoF9xEqZRtQjyUfSkBT8pkChSQ6gVDpSZAZTAwJlKiAcOlZ8plKGkwrnLculjuVpsS5f4VY1ceCLfSrsB14Vb0u/obtS37RgtR4EOIiHs0XlMVEnz0yahjflozK+7Bk1rzNTVoqGVBE2JsAhRrZTa4YO53S3FlXqRZY309S8mnOJp9vsMkvfjMhrtYSfDDm1u1RECYbkvAqENlS1MoGENaI2hoEg6JWsn4h2KFSgQx5ihVH/Hmd6OayT/EwbNoNIxLebELtpUMWANsYltpZj+zEPBxYzw7earag1Y0uGWoekOnwkzSn+IfFd1DKsh/Wq+Zh8fEKSetEoG3JP5d8SQathse65LuvkVBpFMSuw3JG6C5yG9gQD77kAxWawWW/gjX08dBaUeYYoHUtWLqJd0Qxnkt+RHShyPO6MZRG34DsfGYAc+N0/kyw3LcGpQbRWP28ztbZJ7EHrLIvZGrA22gGQYu9t78DeKpFE9x0Q3kgZ/7ZcURSo1W2GjqMV0JV+xBb3JXOqR9ZKTyYBjz4/x1skjYz3ARxN2AkQbvek/pKmpcwEb4OSfTtmeu7Jk/FYiUyvuf9kt/SJQIpj+/+AD2/p7s=)

### Other comments
i see property attach in v-select and it is not works and as workaround, i used this menu-props

**Comment by KaelWD** [comment]
`'my-overlay'` isn't a valid selector, and the element doesn't exist anyway. Have a look at some other closed issues regarding select/autocomplete and attach and reconsider if you need to be using it in the first place.
