### ISSUE TITLE
[Bug Report][3.2.2] v-navigation-drawer can not be styled with scoped styles

### ISSUE THREAD

**Issue by tmwrnr** [vuetifyjs/vuetify#17330]
### Environment
**Vuetify Version:** 3.2.2
**Last working version:** 2.6.15
**Vue Version:** 3.2.47
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- use v-navigation-drawer in a scoped component
- try to change styles for .v-navigation-drawer

### Expected Behavior
Styles are applied

### Actual Behavior
Unable to style navigation drawer

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVUtT2zAQ/ivCF2AG2Qy00xkTMrQHbr31hjkotpKokSWNtE4ITP57V/LbCQM0l0j7+Pbbl/z0Fv00Jt5WPEqjGfDSSAZ8nilCZluaM1uEc7hJttcVNHeUnFHqxW7v0I8umCW5ltreZ1HBuaGmskZyUjC74YreZtF8lgyt54RSBOvgtpQZ4xWthHR4xoqS2X0W9SpjdSkUV9CKOl5DKKrYlopcK7JlVjAFCAb8BbKIPORS5JvYgTaesWU7bsk9OatPDdspzIBvCANaS68HAZLPf+/JUkjuvOdYM3FzhuXc1vWojxODBZxg7AngrSwELdlKiSUWJGCg9VcBkCd0Wf6Hf6HB0S23IHImRzANRF+8cY+xkmLFQGhFm0p3Ybe01AWXXTeG7ZY6D06oXGgAXQ6Vfmy19QNychakcN2U+F8q0MEhUvgfAoU0vPkojyPK44xKJhRxsJccIddcrNaQku/X1+blDgszYuL3ifpiDsSE/Flz0scgzSjuhJQES8hxr5Y47ATQrM6doJUrmZRo5sQrJy63nCsXD4Ih7+NoXurptjvts+2XuvXByywZPAUzhBemtuEvWGkgBV+ySgJ5q4EKBiwlF5fkfk4uGhlKQyIpWTLp+FUrXVldmZSoSspOFhqRkqeefwcS+ut3KCXnj1qfdz5hYpisvGI5VhwG55NAv5g9DYTj+iWgR/H6+g6lieZjTtV7UIuJpod6bk6HSzzUxx2DfJ32IUK5fWsGQWEtXNy9eKE9rbLFrv8PfhK67s/CkOOwacPrz0J8YjnaQAuWb3xwVaQEZ5aBJmfC7yngm3LXo3vMeXQVSaE2Lv7rtMIvUcDIotzhenZzgdsFYFyaJHmh0BLfCrG1seKQKFMm+A0DfBMfbuOb+CYpcItbEQ75wsUBzCM9Z+qAAWsyuA9mErVWhMhNLlmESP7+AYUHNEtspUCUHJ/IMnD59qMmM5DH3OEn0Oqd4xZRsqipeojjGX8i1kfpYogj6ATj4aNNLVcFt/6F/VxKE7dRWhPdUWpNpw/R4Sqq/bD2gXT0/A+ZXJ0o)

**Comment by MajesticPotatoe** [comment]
you need deep selectors for scoped styles
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

eg:
```
<style scoped>
>>> .v-navigation-drawer {
    background: tomato !important;
}
</style>
```

**Comment by tmwrnr** [comment]
@MajesticPotatoe Can you please have a look at the following [example](https://play.vuetifyjs.com/#eNqdVUtT2zAQ/ivCF2AG2Qy00xkTMrQHbr31hjkotpKokSWNtHYITP57V/IjthMGaC6R9vHtty/56S36aUxcVzxKoxnw0kgGfJ4pQmY1zZktwjncJNvpCto7Ss4o9WK3c+hHF8ySXEtt77Oo4NxQU1kjOSmY3XBFb7NoPkuG1nNCKYL1cDVlxnhFJyE9nrGiZHaXRQeVsboUiivoRD2vIRRVrKYi14rUzAqmAMGAv0AWkYdcinwTO9DGM7Zsyy25J2fNqWU7hRnwDWFAa+n1IEDy+e8dWQrJnfccayZuzrCc26YezXFisIATjD0BvJWFoCVbKbHEggQMtP4qAPKEPsv/8C80OFpzCyJncgTTQhyKN+4xVlKsGAitaFvpPmxNS11w2Xdj2G6p8+CEyoUG0OVQ6cdWWz8gJ2dBCtdPif+lAh0cIoX/IVBIw5uP8jiiPM6oZEIRBzvJEXLNxWoNKfl+fW1e7rAwIyZ+n6gv5kBMyJ81J4cYpB3FrZCSYAk57tUSh50AmjW5E7RyJZMSzZx45cTllnPl4kEw5H0czUs93W6nfbaHpe588DJLBk/BDOGFaWz4C1YaSMGXrJJA3hqgggFLycUluZ+Ti1aG0pBISpZMOn7VSVdWVyYlqpKyl4VGpOTpwL8HCf31O5SS80etz3ufMDFMVl6xHCv2g/NJoF/MngbCcf0S0KN4fX2H0kTzMafqPajFRHOAem5P+0s8NMctg3ydHkKEcvvWDILCWri4f/FCezplh9387/0k9N2fhSHHYdOGN5+F+MRydIEWLN/44KpICc4sA03OhN9TwDflrkUPEO1TecpRipKfcENSnso8uoqkUBsX/3Va4QcsIGRR7nCr+3HCpQQwLk2SvFBoiU+MqG2sOCTKlAl++gCf0ofb+Ca+SQpc/k6Eu7FwcQDzSM+Z2mPAhgyukZlEbRQhcptJFiGSv39A4QHNElspwGzxZS0Dl28/GjIDecwdfjmt3jpuESWL2maFOJ7xJ2J9lC6GOIJOMB6+9dRyVXDrH+bPpTRxG6U10R2l1nZ6H+2vosYPax9IR8//AKZHr90=). 

The root element of `v-toolbar` can be styled without deep selectors. The same should be possible for the root element of `v-navigation-drawer`. The only way to do this currently to remove the scoped style, which is not optimal.


see [Child Component Root Elements](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements)
> With scoped, the parent component's styles will not leak into child components. However, a child component's root node will be affected by both the parent's scoped CSS and the child's scoped CSS. This is by design so that the parent can style the child root element for layout purposes.

**Comment by MajesticPotatoe** [comment]
Thanks for the v-toolbar comparison, seems a little sussy though seems like something else is wonky here. Will have to look into it deeper.

To note generally shouldn't be modifying native style classes, especially for something like background which can be done via color prop (though guessing you are just using that as an example, but also doesn't seem to be working).
Usually would recommend using style or a class + increasing specificity before overriding natively classes.

**Comment by wmurphyrd** [comment]
Adding on here that v-navigation-drawer also cannot be styled from a scoped style block even when defining your own custom class like `<v-navigation-drawer class="test">`

[Playground](https://play.vuetifyjs.com/#eNqlVc1O3DAQfpVpLlBE4rYIqUoXBLeqao89sRyMM7trSGzLdgIrtO/esZNsnAUEUjmwmfHMfN/82TfP2bUxRddiVmYLj42pucfLpQJYdLngtorfUar5Vrd+kKNG8U6uuZda5ZXlj2jHM4Aub3SF9cUyG06y6ay0XIaT8JPqDdqGK1R+Ul2JWoqHwRYuYMVrh6mPqLlzdO7R+Um/J9kTl87nkpKbtARm0aCqct5xzy1F2HhvXMmY5arSTevQFg0ybiQz2nrC9441qNj38+LerFMOAF76GinGL71R8BtlNU8YgCo1iQk74jcWnUrmau1LbgKvmU3M4s6ruY6KzK3kysf0n5L0xz8ptKLDppK52GBnqU81rl4x7MtcOK/NVOtPh/2J3BcsUpnnwGaTMyqTypN+1pJKdqFIMdr4fWASfKFC5aTfEimhG8MFcQ+1nKMnOPu2JqlvdIO5oCjkOzbqJ+lI7HjdBjGYLLPIJqX8cQwuhG5pcCeEP1u43itHnL3Z/0Pla6tbk9NG1lKFXEbgvzS5LsEMk0zym4ijflpsUrzY7HTtGy4VOL+NcBuU640v4dv5F/M0wASD8d4I0aeLI4jDrTIbmoUTVpreBp/CwlHrV7ytPTz3gSpaUzj+PIoAFn1r1SSTSWRagrctnk7qkK8r4SYt8nNfrhKOwiQcncZVIWk2L0ewS8KkTlNz565Db952jM151Wfez3mE2+Q7LOVBirv+o/cgYcH21QyVDY0CJ7TB/lYpwl051u2Oi4eATDMmdK2peharH0MgAHYCraLVo4vPg9fgECHagdhwtUY4Yb1Z+F9WiOY4ht/36Z34wZ3oBoqX2WlGqT+44t5pRc9RjECL72h69+2b7mlRKbKkN0Z2tlDomTINo4fMy9X26qw4K76yisZ6VNEU3rkiBguRbpdqR4CyCbNGA2sOUPuDiDxksswoUpDfoXBFZsxSRyWNEb0kKZdEXaBr8jurH8NDc09AQzsjTCD8Aaj3siWIF6EZ4XVoc0vXCtrwTn0sowO3FPPg6EVmQ7d32e40i25U+P739h8E9qi3)

In the rendered HTML, the class is applied to the `nav` element, but that element lacks the `data-v-xxx` attribute that would make it targetable with a scoped style

```
<nav class="v-navigation-drawer v-navigation-drawer--left v-navigation-drawer--rail v-navigation-drawer--active v-theme--light test" style="left: 0px; z-index: 1004; transform: translateX(0%); position: fixed; height: calc((100% - 0px) - 0px); top: 0px; bottom: 0px; width: 56px;">
```

**Comment by jankrnavek** [comment]
This issue still persists
