### ISSUE TITLE
[Bug Report][3.2.3] overlay with  dynamic activator id not show at correct position for first time and require manually reset activator  to enable show again for same activator id  

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#17346]
### Environment
**Vuetify Version:** 3.2.3
**Vue Version:** 3.2.47
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
when using overlay which is activated by click button it need to update dom by nextTick before show to enforce show overlay in the correct position 
when click outside the overlay disappear but when click in same button th overlay not appear again else when activated by another button 

### Expected Behavior
show overlay in correct position
when overlay closed bu click outside and activated again it should be appear again

### Actual Behavior
overlay not show in correct position

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrlV01v4zYQ/SusepCDRtJawvZg2EF6KNBbLwV6WC0MWqJsdiVSICkngeH/3hnq25KdtNk9LNaAYZEznHlvOI+iP52c38rSP1bMWTlrw4oyp4Y9xIKQ9dGjZWkf7aCgXJAkp1pvYqek3q+x0xit2bBn42Wc5SkBX5myHNwKvY8dErR+nbs2Sor9w+/PFBIysiRP3BxkZUiludgTAbH+4skXIo9M5fSFABBGFQEAXCRSKZYYUkrNDZeCZFKRjCttiOEFWwdN8C6ZzLtnGOX8AX6SHMNDvF1lDMRYdqn0QT6hocXYJ+wi96nXAYS7HpwKiMcN64KnXDdUZlfWC+keKz2HrcVEhBzCqTHXyyBnCvVjKTGS0MTwI+xnSnYvTfAmZmjNFsoIyTroqzXY3IQq3FaoNGwqR2wh7OuB8f3BwMzHD4NeiE1sYMnOQLfI3K5gSkkFC1Y8hZHL0637C+Ew8WhBwRwy+LNmuVzwOwjXAD2d+Pm8Dmy8AcoaUp+zh9rWqm9CjL1tprdLyEpWTWEsuO55y1O05jKhuLkelBdqt38Bn0QKAS3A0ilPi6PboSVwFoYJM4GIE43XBPa13/VBDXpkIpvQyuZ1zUwUA3O9YLAlbEM1C+o+QlFpCtauPBNhvV9bP6qyvoamuMjkUFLhLU2F/0NTbxATAr6qJTS+S0vhV9HSayKKZkWEe11vqwRLygg7ApDb2mr6dqKS714ko4OBasKeS7uB37S/dZUkTOthi0e3Wjz6pq+NqMu6gmsKdgR2ci41a9PfkgIa3yWF6D9IYUwO7Xhzq690MKjvdOtgcNeDoU4ULw3RzFRo5kUplSEnolhG7ltVnEmmZEFcuC26GA6/QcDaSxwOASa8VsZv3A0EWWQ01+yudxm9da2H61pzVgkwwRZeXAlONZ/ROv9I84pt3J/xRkGwN6zPOH3jZFTF0HxukY/Rh1fQh6+irz1uoMfDdwZ92ACLHYAfbqFFOgKkO4gWi7vNQ7O4/YzxXdDDz9lC6Yj2JKN2aoZo9CrR2uMGUZTgDNFoSDQaEZ2nOcY1ITig16GAs2ugxUUL40osy7Ir6hxW1zY45Ijh+o+FgH8yZINyWLh/sDyX5G+p8vQnLAYczFY9oBvn3qmlA5or/X+0FPC3ymKBI9Aa4EBbkQZd7ICScBw7B2NKvQqCJBWwDA4gflS+YCYQZRE8glugKoG3NS+VxWPkR/4Hb8cM9T8GcKibodVnuvB2Sj5ppiBW7NwPshmevbwhY+MJiUI/qjM0U15OdxpTTEIHkA/q7CkmUqYY3PffRuxi2Qy5C48JwWarzlD9nIsv+qLwCb5FVuRTi/VdzG0wjPQZE57vnSFcAGDXOZ//BfZ/Aqo=)

**Comment by KaelWD** [comment]
`activator` adds a click listener to the target element, you're opening it in `showOverlay` then the other handler triggers and closes it immediately. #&#x2060;2 (nextTick) is the correct usage, but either add `:open-on-click="false"` to the VOverlay or only set `show_overlay_2.value=true` if `activator_id2` was changed.
