### ISSUE TITLE
[Bug Report][3.2.2] How to pass props to child slots when using v-hover and v-list-group in vuetify 3?

### ISSUE THREAD

**Issue by golich88** [vuetifyjs/vuetify#17345]
### Environment
**Vuetify Version:** 3.2.2
**Last working version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows

### Steps to reproduce
I am using vuetify 3 to display lists with child groups. It is necessary that when you hover over a line, a button appears at the end of the line. Faced a problem. When I use the construct, there is no problem. But when I use this construction wrapped in opening lists stops working. I understand that the problem is passing props to the child slot. But I don't understand how should I pass or merge props of parent elements?

### Expected Behavior
the v-hover component works inside the v-list-group while displaying the subgroups

### Actual Behavior
the wrapped component stopped expanding the list of subgroups

### Reproduction Link
[https://codesandbox.io/s/vuetify-vlistgroup-vhover-s0rjg5?file=/src/components/tree-branch.vue](https://codesandbox.io/s/vuetify-vlistgroup-vhover-s0rjg5?file=/src/components/tree-branch.vue)

**Comment by KaelWD** [comment]
There's two variables named props, but you're only using the one from v-hover.

**Comment by golich88** [comment]
because there is only one variable in v-list-item called props. Changing the name of one of the original props doesn't help. How to use props in v-list-item?

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring

`v-slot:activator="{ props: listProps }"`
