### ISSUE TITLE
[Bug Report][3.2.3] v-chip in v-chip-group grows to full width.

### ISSUE THREAD

**Issue by mcrapts** [vuetifyjs/vuetify#17344]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.2.2
**Vue Version:** 3.3.0-beta.5
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Look at v-chip-group example in the documentation https://vuetifyjs.com/en/components/chip-groups/

### Expected Behavior
Chips only grow as needed

### Actual Behavior
Chips grow to maximum width

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMtuwjAQ/BXXl7QStluiXlCKqHrpH/RAOIRkAbfxQ7ZJVaH8e9dJQBFUFRIXyzuzOzO7ywN9tZY3e6AzmgVQti4CzHNNSNawwlr85iEPWJQ7adnWmf0RO6HzN3zIUyaGMk5f0NP/6XREd+RQnhwxEEJ9okyMkmLpSydtIB5C1yqVNS6QA3GwIS3ZOKNIgismsbk02gei/Ja8RP4+eYe6NuTDuLq6Sx6ieC+HQnRCey2mCss/vdF4pUOXfyB8TmekQyKGHrHO6S4E62dClJXGsQpq2TiuIQhtlVhgm3B7HaQCVhm1SHnKH9kaQsGfRSV9GLMcvGJrZ749ONTK6WTkFuTm5wrHoRONpjztHQaI1cXaR4sLaYF+DTjmQFfgwF272NnYH8uddVwsGEO0uW7x+rXUX/7s8KXvjr48Zr1p804sKq2iYTuh47gYoJujq1/cBhKW)

### Other comments
Since v3.2.3, `v-chip` components have the CSS attribute `flex: 1 0` applied. This means the chips will grow as big as they can. I believe this is the cause of this bug.

**Comment by KaelWD** [comment]
#17283
