### ISSUE TITLE
Feature Request: Hide days in Date Picker

### ISSUE THREAD

**Issue by ecencio** [vuetifyjs/vuetify#1734]
Allow to hide days in date picker and let the user pick directly a month.
Here is an Element UI's example
![month](https://user-images.githubusercontent.com/1786299/30455342-ee78dd22-9975-11e7-8ec8-8de865fd93c5.PNG)

**Comment by jacekkarczmarczyk** [comment]
There is already PR for this feature

**Comment by nekosaur** [comment]
See https://github.com/vuetifyjs/vuetify/pull/1435

**Comment by ecencio** [comment]
I searched for date picker and didn't see that sry, I will keep an eye on that PR thanks
