### ISSUE TITLE
[Bug Report][3.2.3] Can't scroll bottom sheet through touching

### ISSUE THREAD

**Issue by smortexa** [vuetifyjs/vuetify#17352]
### Environment
**Vuetify Version:** 3.2.3
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
- Put a large list in `<v-navigation-drawer>` with `location="bottom"`
- Change to a mobile device with browser DevTools
- Try to scroll through touching (not scroll wheel)

### Expected Behavior
Scrolling with both scroll wheel and touch

### Actual Behavior
Only scrolls with scroll wheel

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNrtVsFy2yAQ/RWqi5OZIGWadjqjJp60h9x66/QS5YCltU2NgAFsx8n437uAJEu2Uyc5RxcJdnn7dmGfuH9OVktwfLpJ/9okT3itlXHkmZQGmIM/0Ua2ZGpUTUaN76iQhYTH4FoqaR1pDORmuPDsuZCEuDnUkCNoBVO2FO53HI8En83diGwvvJNQJRPeyw/i006NpmwUfOIzZUJMWLlAA8jW4EG254VMLpIfWqfIB7O5dlBrgXTG3ul6RUtmqvAdRkzrZoDDT5T6ObuxuIhOmMHMhDI3RVIBaKqXRgsgFTMLkPSqSMbXWd97TChFsA4uoHvDjneLpw2vmdkUyc6ksbpcgnTtVMerD0UlW1GOBScrZjiTDsEcPLoiIbel4OUitU5pz9iwNRjcjE/xq2G7D9PjG8I4pbCwhjruBIx/bciUC7B+5dCyt8xqVoKJ9Yifew4Td4SxJ4CjuuK0ZjOJh6Vhid5vBUCersvyHesr5SxdgXEcD9wApoHYFW+4x1hJPmOOK0mbSndhV7RWFYhuN/rbfeTxZ93joP9EOafqvr8/xsr4M3P0eAhuu4Pjn5zjAotI4d0HCpl590FqB1kMk6wZl8S6jQCEnINv2px8vby81I/fsVgDKr7BqC9wb5oQbHiyC0Ka47nmQhAsK2CvBXlBnSAxeYJetsY+RzfLn4BYlBWQNu0FQ+KH0fys59s2edy42P7NAhxcZz1hwCGicx1BGlVrlKpVo4o5lpOzc3IzJlHTwmzII/eCZKETqJlRS50TuRSimwsbkZP7Hf2ezOH++rZCObtTqi90eIiYWAYBHBqiYv4H6Cczx4HwBL8J6I4/Pb1Aac9ymtPyJajJnuU0q486fdTpPXV6aG8L5/gRP9fMlfPetSO0r2/1XlA35zbtfqqh3Vtjix3fW68tjZrgTURwubB4sVISLyMBr0hKi4rcSQEKqnPa5llWVhI98Y/BVyaV4DKp66y5Vt1epZ/Tq6xC4W6nqGATmwYwj/SAtx8MGK9vqIB6L2o0hMhNXoW/+PnxCQq36JaZpXS8BvxR1oHLl2+RTG8+BYsXIaPWFgyiFElTmBDHM35FrFPpYogD6Azj4a+bGpAVGP+ffV1Ke8sGae3ZDlJrtnqbbC+SuA5rH0gnD/8AjehOeg==)

**Comment by briankelleher** [comment]
Bump, having same issues, making it unusable on mobile at the moment.  Using a simple example with location="bottom".

**Comment by johnleider** [comment]
I'm looking into this one.
