### ISSUE TITLE
[Bug Report][3.2.3] `v-tooltip` doesn't work with `close-delay` (when `open-on-click="true"`)

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17359]
### Environment
**Vuetify Version:** 3.2.3
**Vue Version:** 3.3.1
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add v-tooltip with a button as an activator.
Set properties `close-delay="1000" :open-on-hover="false" open-on-click`

### Expected Behavior
v-tooltip suppose to be closed after 1000ms

### Actual Behavior
v-tooltip never close

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUs1u2zAMfhVCF7dAbKfLzXOLbs8Q7FL1oNjKokWWBIn2GgR+91Gy46XppUAvtvj3feRHvpzZ0EtU+1PxJ7CKqc5Zj3CGxkuB8tcUgxH23naQzbkZN9zIt5TaWBMQ5gA8vi+8O3MDgAfZyQrSG6CVe9Fr3E7OrBX+mK1iaKTveP+dG7ZiP5wrCJM6qkPjlcOnmDFTzggLoEABd/cXE8BL7L35b4/TI+Inoy4XzBpl5zQ1HPHrVg2g2kfOhHOcRRfHesjJSvQAZOzQQBXwpCXlnTvhfyuzta7KHtZr95aNVPezR7Sk0FyB1mpUDkSDahBoPRU64aVBzkDbRqCyhnxoiRQabYPMW6nFiXwEuiZnZZ00uTX5wQ4y1u+FDpICF3+jVXN82k5MdbmQXvomDzVOFg1E72miuqSB0/9KBTIndSCQjFPaIhdtZrqQvBOOLsYa2lDSmc+BwNmyaR5vK9qcHRBdqMqyaQ2V0XRq8IWRWBrXlc+UVvreoOpocts9b4pN8UDNBbx2FzJ0+c7bv0F6AuEs7XOmidf2Cao5kxi+FZuJYXblWuxCpPgAXRIfqZ7Txlrppf/sRDdl11PdhD5MNh/qSHprZY7hRuomJJlfLk1+aeQEFpFeI+G4YqlPYk4F7PUf/NpnWw==)

**Comment by KaelWD** [comment]
Open-delay and close-delay only apply to hover.
