### ISSUE TITLE
[Bug Report][3.2.3] Tooltip wrong position on RTL mode

### ISSUE THREAD

**Issue by smortexa** [vuetifyjs/vuetify#17357]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
- Set an RTL locate
- Use `<v-tooltip>` in a `<v-navigation-drawer>`.

### Expected Behavior
Respect location prop.

### Actual Behavior
Tooltip has wrong and changeable position on each hover (Maybe not visible).

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVEtu2zAQvQrBjVvAlIo6QAHDCdJNT1B0E2UxlsYxG34Eciw7NQz0AD1lT9KhJDvyrwlXGr7HeW+oGT5sZbNC0ouX7GeUU6lt7QOJrSgDAuGPDhM7sQjeilHPHRWucLhpqaV3kUQPiNvjgx+2hROClmhxykkrXMDK0PcuHhn9tKSR2I0TyfgSTGKloFv7rdECRi2nWwswZg7lMwPo9kBKsvtYODmWX+s6Yz9czYzQ1obt3CXSrFElhKr9biOo6z5oQweNfgLS3qkqwBrDQbKgANocG0u820Kiqwr5itQYLDh0tN86CLQSc+KL28fDpfkaLyNR/0LWufk0lBmu0hsfmFEHbSG8XKM1EDQ4YiJ5B+ZqNgMxMqlSC4MbQbghVXI9GITdKFiRF3auJqfHB2UOyk1V3dlKK4drNfebWd7vXWST94Z0fdlXWskMW/v7+883768VkBaUpBug7logpN/xH/bgb0aCcJF7yTEX01s+QRPCf/q1tzg+ay5GO7xvR+bs+zF99506yw8tzJ1ttHuOPKjecXO3g1LIMsZCTsVDn0wuieo4zfOycsys0OgmZA4pd7XN+zG9n2Sfs0le6Uj7LWVgHrM2Wcr0yNPEgt1zoCzUJ6od0Cr3A1ukhyTFb1i4Z1oeVo60RVV523q5+dKZGexnGK2aB7+OGDhLIftBb3WS43dovVUuS5ylzlmvwaC4ayoM/Ai8s6STY0dlnWBnpSX5Xbrx3Vh25/juW9Py8R+VoKv0)

### Other comments
Works correctly in `v3.2.2`

**Comment by KaelWD** [comment]
Broken by de08cb5d1c1cc680a7a9654534bfe42748bc5ba0
