### ISSUE TITLE
Feature Request: Debounce v-textfield

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#1735]
- What will it allow you to do that you can't do today?
    When using v-textfield to search in a large dataset, every time when user type, the page will run through all data to see match. With debounce, user can type without having a really slow UI because it won't run the search until typing is done.
  - How will it make current work-arounds straightforward?
    Current work around is to have another data which will change by the watcher that watch the v-model of the textfield, and upon change, do debounce then change the data, once the data change, re-filter all the data. With debounce, we simply search the v-model of textfield since it will only change once user finish typing.
  - What potential bugs and edge cases does it help to avoid?
    It does not really help preventing bugs, but it does make the UI faster in terms of searching. Ex. VDataTable is using v-textfield for search. Imaging the data set is pretty huge and each word typed will need to search through all object property of each list, debounce will come in handy in this case.

**Comment by tafel** [comment]
This feature existed in VueJS 1, but it was removed in Vue 2 because of lack of flexibility. I use debounce to achieve this, and I must admit it's not polluting my code very much.

Here the explanation why they removed this functionnality and how to do it now:

https://vuejs.org/v2/guide/migration.html#debounce-Param-Attribute-for-v-model-removed

**Comment by nekosaur** [comment]
Yeah, this is best handled the way the vue docs show, using an external library or own custom debounce function.

**Comment by ecmel** [comment]
`<v-select>` has `debounce-search` prop and there is no way to disable the timeout except setting it to zero. I prefer using my own debouncing mechanism so it should be removed as well IMHO.

**Comment by nekosaur** [comment]
Comments on closed issues won't lead anywhere. Please create an issue with the [issue creator](https://issues.vuetifyjs.com).
