### ISSUE TITLE
[Bug Report][3.2.3] v-text-field and v-textarea using textbox aria role in .v-input wrapper

### ISSUE THREAD

**Issue by userquin** [vuetifyjs/vuetify#17351]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.2.3
**Vue Version:** 3.3.1
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Open FF a11y and check .v-input wrapper in both inputs

### Expected Behavior
.v-input wrapper shouldn't have textbox aria role

### Actual Behavior
.v-input wrapper with textbox aria role

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMtOwzAQ/BXjS0BqYkFvVYrKBfEBSBzqHtJkAwa/ZLsBFOXfWTtBCumlEjfP7nhmdvY9fbC26E5AN7QMoKysAtxzTUjZ5ZW16ZmAqoSeUMIBvkLeCpANwaVpQG45Vf6VUyKrY0LPSCGPkYJDtvxcOaj+UNNgSS/ZzDqCMVTJZmER+toJG4iHcIproaxxgfTEQUsG0jqjSIZXZpFcG+0DwahkG/fX2RNIaciLcbK5ym6i+CiHQnRFRy0MYYt3bzQW1ccsfFp4TjckTeIMPSLm9C0E6zeM1Y3Gb9iO6FyhITBtFdshjbmTDkJB3hi1Wxfr4pY1wof5uACv8qMznx4cinC6mtkE0X5fYDUx0eGuWI8O0yjH7n20OJNm6NeByx3oBhy4Sy9afJtftVidXRbdB64H7FsK/eEXVdc+1bz/Dfmvk5NYVDpEw2FFU050Th/o4Qe79Qgx)

**Comment by K-Schaeffer** [comment]
Since 3.3.13 this is not happening anymore. 
Fixed on https://github.com/vuetifyjs/vuetify/pull/17786
