### ISSUE TITLE
[Bug Report][3.2.4] Autocomplete does not honor the value attribute when selecting an item

### ISSUE THREAD

**Issue by skamansam** [vuetifyjs/vuetify#17362]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.1
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. use objects for the `items` property, like `[{title: "my results", value: "results"}, {title: "my help", value: "help"}]`
2. type in the autocomplete field: "my"
3. select one of the results with the cursor keys or mouse

### Expected Behavior
the text for the 'value' field should be in the input box

### Actual Behavior
the value for 'title' is in the text field

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9WEtv4zYQ/iuEL06AyPIj6QJGkm66Bboo0N3DpughzoGWaIsJRQok5SQ1/N87Q72ohxt30dYX28N5z8eZkR72o7ssm+xyNlqOri1LM0Etu11JQq53QUR1jD8JWQpFYy63N6sRN79nMbXwZzUqDiMllIaTtchZsNXsLYipfmYymNUcghoDHOlrQHOrKnJKX4MXHtsEji7n04LsjIP5yhmyC4xQ1nnA0MyecHMXWb5j5LAalezO30wrMG9MILhkVFcn4D51/M77QrRywfcfZMFpwbeJhe+Fz5IwpKKbPpXLmFmmUy7Bz4p8ex32PKliCr0Ml6RdwNNtJRupHavdrm3Op2Vq8GN0BKTE2swswzCKJRbP8s3bk5lEKg15SrfMhFg6E2IdgjWjUTJ5yup6+SnT6qWuTkYx6Pq0gIASmB88ns1bh+44ZTL3SYQIFQE4lEQ8KGtVSoyl2vppw4/SfMuRCSMWNOueW02l4aUiI3jMgregIbbZW14NQMdVn1pX5D2B2mSmBR0voLUtC+N/gAylxgyhaNdVh4TIOZrGPIiVNQEEZXlExRBvzDCIN2CHem2UtnQtWniszVLNqUQEWCWHdDmogcfd+Psw8yIU3Fi4z4BLLOqGCgPGh1KBjAEHVX3PLLcCb5PrBIO+f4wEj55b7YLcQFXzAW4XRm2tF0xx1kYeEBF6PlaBBEBtRVzgu4tZB+kS8pa92iBiEm5xLwnXyaLNl1wBz35PJE2h9Ryuw2TRT7DJqGyLuY5YdRVoiajCJdDpQP5ebEUgPsWPo/0f/0EL8TsKgKpJo4tYWgoFr/qQd/cRjEW/P37pSYrY/6GfoF3gAtxwJso54d+ZVMVMgCCmq1/0ZcwNAh9V90dK8+kPlyqV4FmXWdC1M/llwKRDWePvkZz/p5lwVf+fU3E/ZPPfyEU/BTjaoaVlAobi8SRsNGcyHuiip6ZhiV3CzSumwNZAnhIOXbpLFMppD4ZP/0lq0X5QtcBhdDuWHQVtbq9QeW/ANRX6xgSLegMStqNcWI4BtkvXb49+3r+jlXS7A9LKDlJ3lJjvYARrh5vqt3eM20aAU1ZJ4zce88JtlDTmGxSgz/3p8T4E6k3SBlOSmnZ5hhe5Fktr+GbgcmvLwzUDVjrKhYeQqk534DLp+uwyUoTp3RgMHZSXCSt/to5be4Yf9pHE/N3+7RiaZcGbuD+SsVsdxmRJclhWN1DmeChjfdy31t9MswwubeCtOXnPx1NGvgfFIkjyRb34YGy2GQfNLq4qIvxpbTnXJtI8K5YE9prBUgWV3lC4QWRfqANjlJydV38xdAmLEKzTBrysqYTMlmT87nqNG4kJZ7hVjy8a2fnpsvOu7OJ02UVX9vJ02cuu7NXpsldt2UODaM1srqWfxgbHS4cBz2I5AZbkYfyNylhTchfT1IwvyPgnzS3U6bMSdvzoiTSQWhK3snpn2IEhht94LBG75JNmL36AxZgAa35rDENy//Xnr0tShb7lNsnXLuY6A9WvkBuTQxZmVx/ms46WPTyn4YMpePAL9nkyG5ODZ50AR+lhJ1g3FjyxC0LhIYWCJgTlw+zxmJ47wcknJaXSJ6iZH1Vzr9lOafIZnqmYfF/R4riiPHpmmnxLIYXf4ZBLYjlUCqwMMXSyPD+aZR9CXWfmXWcujwb1K5WsCIm8r+bquBqVyCOZ6Wk5XvESOX9wIfgQeHqqOsXyr5JbXLBqCSMmT1Oo3Brm5Z/MvzOWp0zldklkLoR/4d0XEIpfLxTm3rK59l7nP4Ptx+u2OLnhRch9offMJtxMSiPn/qbJN31JcMdjh25tmK0UQUe/uSWFvtbccV3i/IIsptMpWKg0lSEUQbSDSZlNFLal2rRmKbyeIGe4zbVjcbMDX/+84ohD42VTmzji142TmWD5POMYXCF0e0Om521Bk8H4ZMX5BZnVYr6jzn94ZiyG3ehiBI/xz2byZJSE93fOQVhsDCzXdbtrvyt6MrB+8Z2eSGZDmdW97uNiMp/MQ9hDbEUKYO+BGYDKUNPjSh7AIE9xuAYpzTpWiwNnuUzUagSa8P87LnwEtlDnEusLb09S58vlh8IZjz5hJg3WsL0apkHLalQmxtlBj0+w9V64YKKnOgR78D4n0FAmpvFFwWkhdcRaYXXOeqGVpT6MDhejQg5y75wePf4FMehe9g==)

**Comment by skamansam** [comment]
In the example above, The value for `group` appears to be honored in the dropdown (all items in the group are selected), but the value for the input is still the displayed text.

**Comment by KaelWD** [comment]
> the text for the 'value' field should be in the input box

that doesn't make sense, why would you want that?
