### ISSUE TITLE
[Bug Report][3.2.4] v-autocomplete dropdown list not visible

### ISSUE THREAD

**Issue by flahol** [vuetifyjs/vuetify#17366]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
When input is 100, the dropdown list appears
When input is "two", the dropdown list does not show unless I type CTRL + ENTER

### Expected Behavior
The dropdown list should be visible

### Actual Behavior
na

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVF1vmzAU/SsuLxCJjzSZNIklTfu0ve1hk/ZQqomAs7ozNrJNuinlv+/6GgjQTKpUpKrxved+nON7fX/y7uo6PjbUS72NoVXNc0NvMkHI5hjldY0/8VDlTHQnPBv6x0QHRnlJwClLyreZV+lfmUeSMS5vjCwkJKaGjpAMisV5UchGmJ+shKjOl2qaq+JxDnFWgKXWrMHdeWI8Z15fcvxZV2SY4dSms0XQcsx5M1gUNY0Skdw/0cJcSnLb1CWIcu5LijtX+lvX00B3/A1qAjHNpcG+IfpEaiVrHWIrpP1PNErHmTYRwo7RnokSojHWqjCwAvcuVvnzLkY6qW72F3w831MOtTbJKO3lvpPJGMyd0wvtxwPMw3wgBidnkgqOulCsNkSD4tbNqloqQ05wBQfSkoOSFfFhFH2bpZBCG9RIb+9dlRNhZXq9XIYE2aS+oQABg9+GE8T1HHE9R6zmiNUcsZ4j1lPE6twH8c2znHuHePSSx0aUipZ+60APVg/7w9HsRnkLQgQn5JzeP4QglJ2v76yiXxuTiobzdnF5WODLxFkysrWaBqfzfqWwIF7YF+q2CY0upf07NKIwTIoe9ZmawAEX5GQB7ECCq97i9saa+0XEtXLrCA3g//jAuKEqCOxpsb1xeUgXjBgY2+3WJSUvL86EyvVWG2GbROkyMXQ5W8MAynd9FhwsVjbZmKDrbufa28UTURefBl4Y7vpC45TVJArYwQz3BYIFAWIjzWymkHxcLm126Lq/GXgcu4vxv1DOJfkhFS+vfOC2SdxuwFZ4oecWAzaqjp+0FPA0Iy1YaHTA/qe9kJkHC2PPmfdoTK3TJClKAWHwkrKjigU1iair5BZgiYIGoemolNXtOl7Hq6SEp2Bsjqmuor2Sz5oqSAIjMypj2OHvG0p1SKiwij+4Cp0pgnvVtsSr1AnUO1IVKSpKqqh6K6NZ2JjVzPWKGY4V3A/ozZn4rWdSFxpl7p6ed1LGZDYT7H3rtaGHfUJlDPAe/gHk8m94)

### Other comments
Same behavior in Firefox

**Comment by KaelWD** [comment]
Use `no-filter` if you aren't using the builtin filtering, `item-title="id"` means the label property is ignored.
