### ISSUE TITLE
v-expansion-panel Expanded Panel Escapes Container when Browser Width Sufficiently Decreased

### ISSUE THREAD

**Issue by PieceMaker** [vuetifyjs/vuetify#1736]
### Steps to reproduce

Go to codepen at bottom.

* Open either of the two expansion panels.
* Everything fits inside of the panel container.
* Now start decreasing the browser's width.
* Around a width of a third the expanded panel begins exiting the boundary of the expansion panel rather than continuing to resize to remain inside. The non-expanded panel continues to resize to fit.

### Versions
* Vue (latest)
* Vuetify (latest)
* Chrome (60.0.3112.113, 61.0.3163.91)
* Firefox (55.0.3)

### What is expected ?
I expect the expanded panel to continue to resize the width to fit and stay aligned inside the expansion panel container.

### What is actually happening ?
After a certain point of decreasing the width of the browser (about one third on my screen), the expanded panel breaks out of the expansion panel container, while the unexpanded panel continues to resize to fit inside of the container.

### Reproduction Link
https://codepen.io/anon/pen/XebmqG

### Note
I can currently work around this by adding `style="max-width: 100%"` to the `<v-expansion-panel-content></v-expansion-panel-content>` component.

**Comment by johnleider** [comment]
This is caused because you are using ```v-layout``` to wrap the text-fields without using ```v-flex``` and you do not have the **wrap** prop on ```v-layout```, which says never wrap the children.
