### ISSUE TITLE
[Bug Report][3.2.4] v-button icon is not vertically centered

### ISSUE THREAD

**Issue by mwshub** [vuetifyjs/vuetify#17363]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Windows 10

### Steps to reproduce
Create a button that includes an icon.

### Expected Behavior
The icon will be aligned vertically in the center.

### Actual Behavior
The icon is not vertically centered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFVttugzAM/RWU50KkbdKkik3bd5Q+BHC7bElASWDtqv77nMBaepFYL4IHJGzHPsfmGGW2Ie9lGdUVkCmJLchSMAuviQqCuA6zQlnGFWjv8C5dfAdM8KV6SUgGyoJOSBttU0SAj8Ewq2zRCfpwalWQgzLcrl2BQpYsswkJOEKhQ+Y8RC6WL9aYGVOfsC+PNtbe2TfALgptWSrgcuhrQXNYsEpc2auzcPI7+Pt8iHNEzn4dw38AHavQSCbEHcdzKYPR8EfrWDC9RJWOhr8K+xkcKnS/mUOptLPMIyr1lMWYHEZtfHjRnpPANcIdRLzDinRAMQ7SyCDiukFETWR/cYrp7lpFJkRw9WWiT1MovHBt3HnUljEJmQaz9t9JPqwtzZTSLFd4MgfBax0psFSVkrYc3x6jh+iJ5tzYPxdyTU3ki7lK80RtEZDLEncjlKw8Qm0CHtl7nA8rObuHwhseo7pSlksI80I2XJ4bMh1/BEaGKc7FgMYqCZl0cJpB92L1tYsQJ6Up4tWgQw0qB+229n8tHaUdtHUUO2nNwW/dxLcT0uTh7P0Lmf8CUbqW9w==)

**Comment by KaelWD** [comment]
Looks pretty centered to me.

**Comment by mwshub** [comment]
Presenting my screenshot for your reference.
![#17363](https://github.com/vuetifyjs/vuetify/assets/103198302/7a738b46-b473-45aa-8f56-1ec4af72dae3)

**Comment by mwshub** [comment]
I have found that this issue only occurs on the vuetify playground.

**Comment by webdevnerdstuff** [comment]
I checked your screenshot and it is definitely off, but in the Vuetify Playground this is what it looked like for me (Chrome & Firefox). The logo is as centered as it can be (dimensions are not even numbers). I am on a Mac (13.3.1), so it's at least correct there.

![vbtn](https://github.com/vuetifyjs/vuetify/assets/14927668/e8961669-5d1f-42fc-93ab-df9fc59d4a7c)
