### ISSUE TITLE
[Feature Request] v-tabs not scrolling with momentum

### ISSUE THREAD

**Issue by gritworks** [vuetifyjs/vuetify#17364]
### Problem to solve
v-tabs scrolling adds inline style="transform: translateX(x)" for positioning the v-slide-group__content when user drags v-tabs on mobile.

### Proposed solution
reposition the v-slide-group__content only when user interacts with v-window-item not on the v-tabs.
remove setting the transform: translateX for v-tabs when user scrolls v-tabs.

**Comment by gritworks** [comment]
investigated some more.
- Should use native scrolling with: overflow-x:scroll and remove scrolling by code.
- Use Element.scrollLeft if possible to set the position of the tabs instead of translate.
- possible remove some of the eventlisteners like scroll on v-slide-group__container

**Comment by KaelWD** [comment]
There's already a PR for this: #17286
