### ISSUE TITLE
[Bug Report][3.2.4] Navigation drawer overlay is broken in latest v3.2.4 

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#17367]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the playground link and toggle the navigation drawer through button.

### Expected Behavior
The overlay should cover the whole page.

### Actual Behavior
It is falling down the page. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVttu3DYQ/ZXxPrXAXoC2QAvDqWMEAdoiLdC0b3EeuNLsLhPxEpJSYgT+957hRSvHCZK+7ErUcM6cmTNDvvq4uvF+O428ulxdJTZ+UIl/vbVEV9NGeZ8f6arXU3miFy6wIe3jaKh3gwsUdSJlOFHnbOQucRoDqV57HXWn7ZF40GlLzz907PFJk1EaTiL1OiZtu6TdujrkD557nRQFxla2sCDdrwtyVB5LicmOw6AKOPa8G3WPiHhiqxGEStf0UsGnhaGqMQKM9RjXYrwfY491AOt+tAlGaUQs2Qy4nuE8XfwfsuvPsP1THQWdHUDFhwrdSSdscKT2pE3mKZ984BOIctCpYA5q74J2EbuNttooOoxHhcgVy0/UgA4eJhGJMFgxNAlmiejdCE7Iv4N7UoPO3/kDeRU0iAYa9J6DIw7BhW1BvOkLOUkNIFyfWaIM70YmNUIVEgK2Y91o8SmJ6saobI+g3OEA5g9q1vNeJ/xPAmXcgPBggHIzoQzJFdx+7LSRquhhcGILSNnVSilyrFFZt8cHoX9NN5VVKZmwBwgKG2sZOk2Re5QAObguSH/ja9nDkQMytJ5BSkpnNbTIQZtgYGZFtGhLfaCHltyin88UMrHNrQD5qLKLCV4FkDo4QHiO0G8dKwjmL2XWsozkbukZPhdgeIT3rLgDLOHiQZlPuqtSvUGwIK7BwcAzMVxU0FDboWq85g1Aa9oPqCEIg3E3ei29JzWySE4SW2Ci4Ei6JBOFgjS4FwqmoEJ4Ryl5VvLY66KIXE/LqISkFE096A6h0OSG0SfQhyBbX/rgJjSwhF3U3o2DV7OoFn0DLQRXCwrJAgQUq8uUVVLSt1CSpB7yr0EiRhRu3fKwHFcc4yzkLb3IPSLTws3KqENoiZfHicye7PfstnZno9CEYzEhSHkEh5icR02Ic4uJzi7ouXQkRkmuo2Xjane+PHeaxCOz70xbZmZj18bqYoCoCDgRaJiFfa5tiy9KkRrNgjmPSamrcIvASwqTdSHKeVjPEVS9Ybdq1ZQ+qorNYXA7BcBUGkgUBc1WNZWezImPeexVcT9zJos6jtCUx3Aqo0FmTp3X9HuWQxnVecacvdVp+6BMcm4gozlBOW1VFq1ANaBZuqXLM7PFnGtl4HghqWkNgL5CTyu+QOBnjWXARcNZ5ASmOA4kUDmSRK0PZkcb0J1IQDSEdBXdn8soswGTo6muUMODdxHjWobHzLGGJcYBceMkKQ3TBoRUSWZhO4jGXtmkgTb3cuZQugpxL0ZGm4piAHeL8+Ga/pGd7YyqYTaxzhlEYxdY3Dv2ycIS1Xhyu/IBMgp3tyt62qEWb7corcd6H9R7DvSELsrT7apeUIj+dcfjwNXbLrvDt9m7VZM+Zsab6mTaQF08zF4BVgUW7mav2IlJmDaYRgZTC8Kz/UZNSKiEeUrJx8vdLoCzQ9Y5bA3vcGPZwU0KSqe4M2x3P/+yfeOPAqDTwNj4hztZesGYI0JBwp1R5qAzOK5gYpRN2vMDA9mHNrc4vO/guHPGqy4BCoRnFl/godGj2GN6vZk0v9/0Kp72ToV+EelvzjBeJzWM8nrKr48i/laYg8hl4f1m70YJtrmHnuT9C/7bal2Q10dlLbfYXbu6ik250F7tFhfdq9gF7YsjtDuKhRwe1Dgk+livKSgxffd9eyVoG61pz+8wyYCX+WZaDwqi+/JwnxfwcrWrUKv1atD2bdy+ic7i3p0doWAx3q4u6VXZdpZU11tYQp96CluMhZ31Zocbe9KHu6c/bn/Y/gSOMbWlDVoxbrMz8fT61t4DEDMQ1DZG+U9Qy4eMXAndruBJ3r8SwlOY7eQypQ1vIPoSy88lmMX6lqPZ7IN7L03xBkg1QxlHIv4GrK/RBcQj1zvg4SqwCflWJu31bZQ+2faA1iffHlGrpb5f3a9XZR9ynx9Wr/8D+c7C3A==)

**Comment by KaelWD** [comment]
Probably d345a6ab7bb222782cf51bdd4d6dabe8d1230013 in 3.2.2

**Comment by bogdanciuca** [comment]
Workaround:
```
.v-navigation-drawer__scrim {
  top: 0;
  left: 0;
}
```
