### ISSUE TITLE
[Feature Request] Missing generic types

### ISSUE THREAD

**Issue by 0x00A1FA** [vuetifyjs/vuetify#17379]
### Problem to solve
Not having type support for TS users.

### Proposed solution
Add generics wherever it makes sense. For example, for `VList` when using `:items` and `item-props`.

Is this planned?

**Comment by KaelWD** [comment]
https://github.com/search?q=repo%3Avuetifyjs%2Fvuetify+genericComponent%3Cnew&type=code

Not sure what more you want.

**Comment by aentwist** [comment]
My take:

https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/labs/VDataTable/types.ts#L33-L38

Should be `columns: T`

https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx#L35-L43

Should be `ItemSlot<T>` and `DataTableItem<T>`

https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/labs/VDataTable/composables/sort.ts#L29

**Should be `SortItem<T>` and `key: keyof T`**

**Comment by eacaps** [comment]
> columns: T

This isn't quite right: columns is actually only a subset of `T` that contains the keys from the headers(and `action` and `data-table-expand` but I'm not really sure where those are coming from). `Partial<T>` would be closer, but to be really correct you'd need to incorporate the keys from the headers as well as these weird other things that are getting added.

**Comment by mustafaekim** [comment]
is it possible that the template comply with the type of the items? I use the latest version of vuetify and in the template when we use the props slot to customize rows, the slotted props.item does not know about its type hence the editor shows errors
