### ISSUE TITLE
[Bug Report][3.2.4] Types of slots disappear since v3.2.0

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#17378]
### Environment
**Vuetify Version:** 3.2.4
**Last working version:** 3.1.16
**Vue Version:** 3.3.2
**Volar Version:** 1.7.3
**Browsers:** Edge 113.0.1774.35
**OS:** Windows 10

### Expected Behavior
In Vuetify v3.1.15, typed slots work well

![image](https://github.com/vuetifyjs/vuetify/assets/40021217/6d98f385-ddce-4283-9c75-c77db7c3c058)

### Actual Behavior
In Vuetify >= v3.2.0
![image](https://github.com/vuetifyjs/vuetify/assets/40021217/95f1e153-7426-4e4a-b6b9-7501a6688906)

All the slots of vuetify components become `Slot<any>`

### Other comments
It seems  that type declarations in `$slot` no longer exist in v3.2

```ts
// vuetify@3.1.16/lib/components/index.d.ts
$slots?: {
default?: (() => vue.VNodeChild) | undefined;
image?: (() => vue.VNodeChild) | undefined;
prepend?: (() => vue.VNodeChild) | undefined;
append?: (() => vue.VNodeChild) | undefined;
title?: (() => vue.VNodeChild) | undefined;
extension?: (() => vue.VNodeChild) | undefined;
} | undefined;
```

```ts
//vuetify@3.2.0/lib/components/index.d.ts
$slots: Readonly<{
[name: string]: vue.Slot | undefined;
}>;
```

**Comment by KaelWD** [comment]
#17231 broke slot types for non-generic components
