### ISSUE TITLE
[Bug Report][3.2.4] vue-autocomplete does not work properly with both 'multiple' and ':menu-props="{attach: true}' enabled

### ISSUE THREAD

**Issue by lengwe** [vuetifyjs/vuetify#17373]
### Environment
**Vuetify Version:** 3.2.4
**Last working version:** 2.6.0
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
See the reproduction link

### Expected Behavior
The styles and the behaviour of the autocomplete option list should not be changed with `:menu-props="{attach: true}` enabled. The checkboxed in the menu should also get (un)checked correctly when the option gets (un)selected.

### Actual Behavior
However, when the option list is expanded from a autocomplete component that has `attach` and `:menu-props="{attach: true}` enabled, the styles of the menu is completely different from the other one. The background colour of the menu becomes a little bit transparent as well.

Also, sometimes the checkboxes do not get checked correctly if you selected the options and this happens quite randomly.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1v2zAM/SucLl6B2MKSnrx06G6797BDnINrM7M2fUGi0xWB//so22mMdIcAPRgW+Ug+viftTuK798WxR1GKLaHxuib8VlmA7TGvvR+PY2BqZedoAntyjeMGJASGXYv6oRIRNTaEbSWgVDwwci5g7DVFThn+K24BecOosfjpMu+t+T+DS4O2z31wPuVPNVHddCVQ6HFg+EL35AwC4V+CDgOfHMTOvQB1fA61jb4OaJvXYtYtF8JTMFmylQurOIxNUJ4gIvUJVsa7QHCCgAcY4BCcgYw9zlJx42wkMPEXPCT8c/YDtXbw0wXdfsru3gqW4ufS3f7u6xk/+zxDttf6As6+nNuyL9kqW/O34e8+2zPJVk4787ZiJaaFWakvfkdn+S2ckuBqBtjgEsZMyrGQFFeiI/KxlLJpLbfxnaljKCyStN7IRy6TobekDOatM4+bYlOsZasiLdMFRpM/B/cSMfCQSqwWNKQOrzdQzZXMsC7uJ4Y5lev6OSaKd6Ml8x0x5HzZLb+DcKuiq7alqivonbLEPlR2YL+1sn/ildVNHG3enZf8kORxWJq0T4TDSox7MvPYIPb/ALcdWEE=)

### Other comments
The `attach` prop used to work perfectly in Vuetify 2 and I think it has now changed to `:menu-props="{attach: true}`

**Comment by KaelWD** [comment]
`attach` was originally added as a workaround for some scrolling problems that have since been resolved, it's generally unnecessary now unless you have a very good reason to be using it.

**Comment by lengwe** [comment]
Hi, thanks for the comments. My application requires to open up a Vue component in a separate window(using `window.open()`) and V-select and V-Autocomplete are used in that separate window. I have to use the `attach` prop otherwise the drop-down list will not be included in the separate window. The `attach` prop helps to solve the issue but it has the styling issue that I have specified above. Is there any better way that I can solve this problem?
