### ISSUE TITLE
[Bug Report][3.2.4] The ripple effect of a button with only an icon should come from the center

### ISSUE THREAD

**Issue by PurpleTape** [vuetifyjs/vuetify#17376]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Firefox 112.0
**OS:** Mac OS 10.15

### Steps to reproduce
Go to the playground and click on buttons

### Expected Behavior
The ripple effect of a button containing only an icon comes from the center

### Actual Behavior
The ripple effect comes from the place of the click

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VMFuwjAM/ZUqZ9JI206ITew7KIfQGhaWOFGSwjbEv88JFApoY9Lg0EPs+L1nP6eTDXt1rly1wIZsFME4LSO8VFgUoxWvLUapEHwO5JC360JqtcDnitWAEXzFimUbopp/9kL7gj2KLugLlJZttL1kTs8iFg1gUDEDWONkHQlUETsFTKO4022gspHIt4/YdCZgOv+DbW59lDMNp4w0kNTRXUgbmMtWn7VoHSBXyBHWv5J2J/LhIOFutvT0ybq2LSbRQX0BBT94MFLrG07owvCO6o5Et/f5J0+7ZrT0C1q2e/DVUgM2Mll/MOk63elGdZnjwx+Jw2+BDZhW+B7KZbBIP4xNuk/bFcisYTHZYVXsLUYXhkLUDdLNBrRa+RIhCnRG7Cc+fiwfyifRqBC7EGmdhTKDJaRphVsiVMbRC+VGujPWXSIz50iKEVI6X5EwpmvC0zYrA7yxhrSQmp2WXriEYPiMxhLAE0jFBj2a3dZcpbrWLVFcQAviW4HnnswEn57t3zo6K+t3dZa66Cyxb9O8twOWy2jwWTKbfgPfp/Sb)

### Other comments
According to the source code:
https://github.com/vuetifyjs/vuetify/blob/ecf814d545a72d3c555fe7a69276d5e2f610d3b7/packages/vuetify/src/components/VBtn/VBtn.tsx#L191-L195
the ripple effect for a button with only an icon should come from the center of the button. 

At the moment, the ripple effect comes from the place of the click, as with ordinary buttons

**Comment by Jesse205** [comment]
Is this really a bug? I didn't find a description in the documentation for material2, and the toolbar's icon button in Android 10 doesn't diverge from the center.
