### ISSUE TITLE
[Bug Report][3.2.4] VFooter height prop doesn't work

### ISSUE THREAD

**Issue by fahmifitu** [vuetifyjs/vuetify#17370]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Setting height doesn't have any effect

### Expected Behavior
height to change

### Actual Behavior
it doesn't

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkE1uwjAQha8SeU1sFLqK0oqeA7MI8dC4jX80NqkqlLt3bIIUhQ0SO7/xvPfNzOHKPr3n4wVYzZoIxg9thA9pi6IZy9b7/MzCtNrOKuuzcxGw6Nzg8F0yBCVZUfegv/pIutpuSYu7XywCkrhFN2KBZBumjXcYqdPz7+AszXRNBjl/BMnqIldSjYZOWrI+Rh9qITplyaZg0CNyC1FYb8Se2gRebNQGSuXMfsd3vBJKh7gscwimPKH7DYAUItlmgYn6/PcEau4kQsXfboS5VA7tKSTEQ7Qg3ghYIlgFCPjsRivbcqvV18NmiT5JO9G9B21/wurUXchnPtyHfGnlHJaSjgk4bViek8jZwI7/O4/UjQ==)

**Comment by fahmifitu** [comment]
Submitted PR to fix

**Comment by jcupps** [comment]
Hello, this appears to have been regressed in v3.3.6.

**Comment by johnleider** [comment]
> Hello, this appears to have been regressed in v3.3.6.

The framework is on v3.5.3 atm.
