### ISSUE TITLE
[Bug Report][3.2.4] "Component is missing template or render function"

### ISSUE THREAD

**Issue by unkobweb** [vuetifyjs/vuetify#17372]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 106.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
When i tried to load a v-app-bar component in a component or a page i got this warning :
```
[Vue warn]: injection "Symbol(vuetify:layout)" not found.
[Vue warn]: Component VAppBar is missing template or render function.
[Vue warn]: Invalid vnode type when creating vnode: undefined.
[Vue warn]: Component <Anonymous> is missing template or render function.  
```
I didn't test all component but got a similar problem with v-paginated but I don't have the problem with v-text-field or v-btn for example

Btw im using vuetify 3 in a Nuxt 3 project and here is my vuetify plugin file :
```js
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import { aliases, custom } from '../iconsets/custom'

export default defineNuxtPlugin(nuxtApp => {
  const vuetify = createVuetify({
    ssr: true,
    components,
    directives,
    icons: {
      defaultSet: 'custom',
      aliases,
      sets: {
        custom,
      },
    }
  })

  nuxtApp.vueApp.use(vuetify)
})
```

Thanks a lot in advance for your help 

### Expected Behavior
v-app-bar display

### Actual Behavior
v-app-bar and all my page doesn't display and console throw me warnings

### Reproduction Link
[https://github.com/unkobweb/smart-study-web](https://github.com/unkobweb/smart-study-web)

**Comment by KaelWD** [comment]
unkobweb/smart-study-web doesn't have a v-app-bar or the required v-app or v-layout to make it work.
