### ISSUE TITLE
[Feature Request] DataTableHeaders width should support number and string so that we can specify percentage width

### ISSUE THREAD

**Issue by WayneDT** [vuetifyjs/vuetify#17385]
### Problem to solve
the DataTableHeader type has width: number; but it used to support number | string so that we can pass a '25%' as the width.  Please add this support back in.

### Proposed solution
add support to width for number and string
`width?: number | string;`

**Comment by webdevnerdstuff** [comment]
Percentage and number values work in v3.2.4. [example](https://play.vuetifyjs.com/#eNqlll9v2zYQwL8KoW3IBkR/LFtO4qVDi3Rdtw5Y34ahzgMtMTYXiiRI2lkW+Lv3KIqyKNlugb4YvuPd/e6OJ5KfXqI3Uia7LYkW0a0htWTYkF+WHKHbXYylbP42Qo0pb6VGrrDBscErRrwSoQWFEPrVMqqI1kQZvYx6ixuCK6LscvsvWNUb8RST/yTmFVgYtSXBchM5lkTFEq9JLKShgttYzcJHoj6C+i+nPTh2CUPKvjr0naOQKlbiCSK8oFKwbc012i+jnof1UYFsNVWoQKhkWNtEJI5n/ZTbxCG2BhwYtJSEEb42m6HpAITQe8KYQH8LxQbI29RUYZppkCeI/Y10qv6G+U0FZberVnD7HbiDqEtFpUGamK1dLqHBBrU7iF6hT9b7xUU01DCyQBdv3fajHydZtgZPtaN8/dPFpbPCjK45WGmDlfFKLVST2wI9YKZJq30kz2DIcU283ROtzAZ0RfaDU+2b3xcUZnCHmVCU6ItLt7A0A6pXO0LZmQeUaZYFDB/9HYbabEFdLYRXILlgD9hcjFzusFrpM06lXXdu9z/bvrs++w9p0GjbEZuHEv8Tjv4R6+2hk76WBZoUN60OUlqgeeKqsSYAW6B81spSCUMopDTrTKgSNsVJ0OQA/gfM5zNaEczH5OlV0SdnQ/LNiHwwacnZafIHaj5Aj0fUYnLdp+ajguc+qw57FULnp6G/wndO1Riaz/M+dDLu8nQIPZi02KvT2N/gyyFqpeB7O9LmYn6ePfMD0LGniVf5HT5T8+8lQSWga6ThwHyi5eZI/VPfwyaHm2EK3XJvyHxHvjxkfwrGqBTySO03Qd+zxIt+xPwsHEYspOanqXdbWeLH7szpQbNgrqeJL84P2JeLvT6NfS84eS5FvRqDZ1kw2tNhtdcj8DzxqbbgWXGa/Fbw7ZEPalYEPc6L4eYWk3G9g/nKe33un2xH7u0Tt0mbN0I7zLagcHUFZXjTSXtqdLaT4AAPjfNh4PxM5GIYuTgTGa69UR5nzL+H95ehD8+JvaLfCeikSvrtecPYIFzs+r53Lb1N3R0Nt3N0GdFawl0KN7tM/tWCw8OuwcFLqVmA19HCJ7CMgGxleJIZI/UiTcuKg1tFGN2phBOTclmnr8EsVVtuaE3iStSvpwlMYFpRbfrqhOg6XsGjCq4sCLKM2qQbjC3wK1CtJRDyZOYIrSpmeKUtYhQ6tS8MeBkquFCJIuprKxq49asaLI0qa7u/h34zyh/1oNWlbtrcTLOVv6nkJpiNdG+B+8uoyRPIjUN0/xnUUHky)

**Comment by WayneDT** [comment]
@webdevnerdstuff thanks for that. I was looking at https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/labs/VDataTable/types.ts 

and using the DataTableHeader to type my array. is this not the best approach?

**Comment by webdevnerdstuff** [comment]
I see what you mean now. My best guess is that type needs to be updated.

**Comment by lioneaglesolutions** [comment]
@johnleider the PR looks OK and would close this issue
