### ISSUE TITLE
[Bug Report][3.2.4] rounded="lg" prop is not passed down to v-text-field when variant is set to outlined

### ISSUE THREAD

**Issue by BayBreezy** [vuetifyjs/vuetify#17380]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0, Google Chrome
**OS:** Mac OS 10.15.7, Windows

### Steps to reproduce
- Create a `v-text-field` component
- Change its variant to outlined
- add the rounded="lg" prop to the component

### Expected Behavior
Expected the border radius of the outline textfield to increase

### Actual Behavior
The border radius remains the same

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV1tv2zYU/iunwrAkgCU7aQt0XhKk2OWpDwPWFgOqPlASbbOlSI2k7HiB//s+krrZSYcMTQBbOvf7Of70kGxb7sRqn32xyTIRdaONowcqDWeOf4w4OtDK6JrOOtqzXOWK3wfSUivrqEPQzTHj+UOuiNyG13wJoRVfsVa69/H9TIr1xp3RYeaJOpxdBhaij+/5vftdcFn1EKItM4Ipt6Q80a2TQvEqTwK3/6u4ssLtPbbU9QrGsULyCUGppTYe3RhRM7OfoiSz1qOMblXFq1Su8yQiD/4LH4eLXCWz5G3TZPAWsbp2vG4knL31FNfblDVNeAwvNROqe8P7izSllZAy3XDvNAlLLCqdkdIOL43RDaXpyLJNEVoHKdxEyps8mYjIE1rJVlQDQ68G0aVtavSOfsQ3fKYduGjDZQM1EsqEIsudE2pNbUNrIypy+4aTZHuEFRYJam3LpNyT5GzLqUpXkt8TQkq2BhwWuQ3YLb4YjDe8c6JmX0AT5USSqUvBKW/Yl9b66oBDJVeOG/jCUAxqApgw5S7EQvr8+SBcXoHe1nh6g4e6wsPrI4YxFn86pipmKri9htdwoCbr2tXq2Kxeh6fsQ203rIKpDUu9uq4sAPeFcaorJAvMqRNO8jFbyF+6C9lKCy0RZZR0unkFAe+8PdfzKds3hdq2OJZbO2/T7W8+UoRQG6SLG8VqjpQ3oNlpOOI0rbmDu8w4Xg26emnf9gFGTlU9EdtIHaJ5B3m1cFlj+Bap8wHyrj3J02flnWaVLw2Y5rhvhbXWVaiuAmUJnz78NSO70S1CVoCgRm9seYVi1eo0cRN7QnRXfmKcpGvwZtrctJTRjGByeAIQfasrLgHrQwqgZEUAfRhBhv/dCsOrWx/XUfEzTHtS7URvn7+J3j9GkO/TY6L/Y0kM/1rqgkn6oZ/ZmKq+gELFVMJipO3RyoXU5Vcq2tYh6FphFuC7736LKY9pm0G7Ff9wP+FpK/jOi7Aclbphas3/I1eFU09HYhn0AtSbl3UmZbZ+q6pf9Q61NSQ0+Fvoap9eon7Gbqt5Jdp6jFcsUj8thOrmJ6CvXoYhigl2Wi9+Ufgw93ti7FcY/lQ3AOPb4XFTDS0OS0+wPe4IHIBaTmcmIBiaEYLQWcXKrwUzw1IcSmfAdJuLqMZGFalflLR0ouYYy97vxWIx8dK2Zcmt7bkG1Q8PYWDRActv2Er9zoNai12yZKUTuACOZzyCNPWpW9tdvk7TpzSsGxOJyTblvSulCPXQO4cTY8WkRROOZEcR/EVqYI/CN03a9fxobUeCXngAYReEJHTLd0I27HT/Erf9kTi8ojNEg6nLXevRwz1l+Gp6RYULimg+x2aaDEMPiwdVD77xnOfB44ufO5YweOM0QWjtyDTM/sgVGSJq2BBTVCdvCG1Iz8ASkh/Jz8565QMt5vPu1OhJjkarpz75JXxDzO5VSecXN7fdZQcbKgwOXfN4M+yE2xBrBNYZa90mEnURybZMtt4NZ1oejCIf7fexus+9VBoORu/CwJAn6OI15py/f2LNr1ocOS/ypJMDSZ0HT2l5bEJwsMMeZnT1erGIcTrg83oea6GrC7fvdm4WL4vOxkLfpxGwpAX+r5p7MuuCnS9m4T9bXF3MAL/0iMs3j7A/XdCLWGTosKg76JtHhThYIxa12+DE1wqHa1Cddwj0PU7zaEzufwz49zzZONfY5XxeVgpsmC9iazLF3Vw19fwOZHPTKj9S0krXdy+zl9nVHJPaTcEZt3VaYHah9iBkOLeDGj/bn6Gqo4SGq+xV1NCBUqxH61U8Ej2Hvi03qeEY6sZfk8/z6IRt6tUJ6pFn/W8ExBvT9qs9CXXpx+uSPvVGfpfLQZiX9NkrPMySYCc0B4bk879jlWb4)

### Other comments
I am not sure if this was intentional for the outline variant only as it worked for the fill variant.

**Comment by salarzobir** [comment]
I have the same problem with `v-textarea`
I wanted to use outlined variant with rounded xl border
Any progress or maybe a workaround?

**Comment by BayBreezy** [comment]
Weird... Still not working in the playground.. https://play.vuetifyjs.com/#eNqlUstOwzAQ/BXjS0GqYwk4VQWVG3/Aoekhjbdg8Ev2JoCq/jtrJxWhvVTilp3ZndnZeL3nTyFUfQd8wZcINpgG4bF2jC170YRQPkvReoeNdhBHqIAIXyh2Gow6goz1TdSNw4ea+w4NTaia/7KtaVIiLvrOKVDCvE7ZESX+L94L6xUYwm2aEPK4njzdLyPD+ks5iUVlaqMOyBJgN6TTNviIbM8i7NiB7aK3bEYXmeV2Wti7hIxs2UPuuJ49gzGevfho1NXsJhsMkiTG53xQE7YJ1Xvyjs66zyr1SKSaL1hBMkYuua75G2JICylb5WiMkuo+Vg5QumDlitpk7BxqC0J5u7qr7qp7qXTCKVxBsmIb/WeCSCI1n09sUO++L7AaO4vD7eAwQsI025QtzqQl+fUQRQT6dRHipYlOxqapTqizZNn9ULsD3Zse2Ec6OXWbypnXxyX/FbmIZaVNNjzMedmTnMsA3/wABhsTRg==

**Comment by lodemo** [comment]
You are right sorry, i only checked it on variant solo, which previously didnt work but does now, outlined still does **not** work for me too

**Comment by BayBreezy** [comment]
Thank you!
