### ISSUE TITLE
[Bug Report][3.2.4] Tooltip remains visible when placed on a v-btn and it is disabled when clicked, has always been a Vuetify 3 problem from what I can tell using the various versions in the playground.

### ISSUE THREAD

**Issue by gwheeloc69** [vuetifyjs/vuetify#17382]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
Wrap a v-btn in a tooltip slot and implement a function to disable the button when clicked.

### Expected Behavior
The tooltip to disappear as it does in Vuetify2 when the button is clicked.

### Actual Behavior
The tooltip remains visible.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu2zAQ/BWWPdgGLBFIejIcw30c+gc9hDlQ0qpmQ5EEuXJTGP73rqgHJOdiIIIgcLmzM7tD8fnCv3qfn1vgO75HaLxRCAdpGdufM+V9WqagUdoOUYoR3jCrNZiKUdJVYJ4kb+JvyZlY4JwzqD0zrlSonSVU4RBdI/kEI+CozT6rEvVZoQuEvDAfnI/sugAn3gLtfIdRF4W2FRWlEsmX2V2loyoMdIBh+a2lNuwt8FgaXb4SKgL+GGrWmyXqwL4bUGHRkUgtzUcSCz/7veiVPaTivUjrySmqH6waPaedyfQu6I9jQUthLIP2SGshmG68C8guLEDNrqwOrmErOtyVtPCWUhXUqjUE6UgrhYqtN31ATwBsg51CiQujdqxWJkJKXrvvddt9G8CTq+JuKhuK0pBzdsbwpGO+4GRPM9KRkZ6Z93dQYGg7BokS+8akpZf8KJ2NyOinJBBZsl79BGMc++WCqT6tNp2Zk318y3v7yHSf/4nO0pVIwnJI0D81TSk52drFkp8QfdwJUVaWyuge6HPILaCwvhFHgonQWtQNZJVrjo/5Y/4gaAKcb+cQm6wI7m+EQCSSD0YkGdT1vzukBiQpPORfeoVhKzOqiJ3EO2pBemcIWQBbQYBw70Q3ZfOpblLvJhsPiPw22r7GG6vLmGx+Hpv80MiJrGN66QSvW576JOVUwF/+A2mPmQI=)

**Comment by KaelWD** [comment]
`<v-tooltip :disabled="disableButton">`

**Comment by gwheeloc69** [comment]
What is the work around?

Regards,
Glenn
