### ISSUE TITLE
[Bug Report][3.2.4] v-app's min-height does not honour full-height=false

### ISSUE THREAD

**Issue by MarcosCosmos** [vuetifyjs/vuetify#17388]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
This can be reproduced with any instance of v-app with the full-height property from v-layout set to false.

### Expected Behavior
The height of a v-app component can be conditionally controlled with the existing full-height property.

### Actual Behavior
v-app appears to effectively ignore the full-height property, even though descendant components are still affected by it.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMtOwzAQRX/FeBOQmliirKIWlR1/wKLuIo0nrcEv2U4AVfl3xm4qRe2mEjvP494z19sTfXOuGnqgNV1F0E41EV65IWQ1lI1zpO56pcojyMMxrjntGhWA07yRd3QjzVTlOsJPLDsJShAcWgEKVTocOCXsomIzWSqQg+8Vm/GxDK2XLpIAsU9jqZ31kZyIh46MpPNWkwIPL9Jya02IBDFkneaPxTsoZcmH9Uo8FE/J/GyHRnRBz154hKs+gzWY/ZRu4dMgcFqT3Ek9ZKSa02OMLtSMtcKgDJPJwVcGIjNOsw2uMd+bKDWUwurNslpWz0zIEOftCoIu995+B/Bowulihomy+70DNW0i4bl6OROmVqmafUiIG2uGvAF86cEI8ODvTXQlm6e6Gt0kS/SRmxH/W0nzFa6+ug35m7eXI/8VOZslp10Cjgua70RyFtDdH+1z+i4=)

### Other comments
Whilst v-app's min-height is special and not exactly the same as v-layout's normal full-height behaviour, there is no particular advantage to enforcing the min-height when the full-height property is already available.

This issue is a barrier to using v-app in nested layouts and e.g. web components/custom elements.

**Comment by lioneaglesolutions** [comment]
I don't actually think this is `VApp` directly - but `.v-application__wrap` defaults to `min-height: 100dvh`

https://github.com/vuetifyjs/vuetify/blob/50dcd93c93ffccee841de9652f976968d9dc387d/packages/vuetify/src/components/VApp/VApp.sass#L14

Example showing min-height as [unset;](https://play.vuetifyjs.com/#eNqlkM9O4zAQxl/F+NJdqYlXZfeSLSv2xhtwwAi5yaQ1+J/GkwKq+u6Mk4CqckHi5vHM9/2+mbuD/J9SvR9ANnJN4JMzBP90EGK9r0xKoukH56od2O2OrrTsjcugpcj06oDrjWmfthiH0DVi4wZusViTJpbnHQCJD+nqz6/0wtI2uohcI3RcqQmmRhq/1+okBZe5RZtIZKChtK1PEUkcBEIvjqLH6MWC4y/KcBtDJuHzVlyV/o/FDTgXxW1E110sfhbzyW62Ljvwsx7ZzraGbAwPD89okjiUWN6GefVGDIEzXEx8E+ivDsfRcDaRSzn1Km9S/Zhj4IuOJnpuZC2bybb8ceZSa7kjSrlRqu0Cyzpwdo91AFIheXXNYwqHQNZD1UV/fVlf1ivV2Uyn3zVkX20wPmdANtFyeYIh279+ATVPMmFV/54I81flzCYXxCdrxbw9YIUQOkDAr250Jjvd6qz1abNC58Mf+d7Ohqd8duo2j2e+ew/5rZVHs+J0X4DHpRxzMnkUyPs3g0gdeA==)
<img width="845" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/61766491/a037fcf7-51ff-4c65-8d1b-1ce0a1d9e4ea">


So I'm not even sure what use the `full-height` prop on `VApp` is... @johnleider

**Comment by MarcosCosmos** [comment]
You're right, currently the full-height property on VApp doesn't seem to do much, as it's overridden by the default min-height on .v-application__wrap.

However, I did notice that it makes the value of --v-scrollbar-offset [inherited](https://play.vuetifyjs.com/#eNqlUs1uGyEQfhVCVbmVzK7rtD2sHSu99Q16CFG03p21aVhAMGs3svzuHWDjWE4OkXJjmJnvD+4O/JdzxW4AXvElQu90jbCShrFlq3ZMtTeSN9ZgrQx4yVOHsdTfido5VnWD1mILarNFmkU/gOQs4JMGKtd187jxdjBtxdY6tghBokTaDlsAZKfN+Y+Z+0erjdXWU+2hpaocGTObWNd+lYS9ReAG7zQs9qrFbfVtNvu8yOD5fBKf5SfQkqBWy/IFOxnL9TNxmolnaZblWUJUhsYrhywADnFc9c56ZAfmoWNH1nnbswlFO4nDFGJA1ocNu4n9L5PfoLVlf6zX7dXkawTPcCN09EfHImnRqqlRWfPwsPe1Y4cop1dmjL1igyENV5m/NriQ5hhHPp1ejkRlO0JQ8I23WpNdYbuOFiv2k6LPS0nHyM2nPEOKvnbF32ANfZLELcdGkLzKauIdWY215FtEF6qybFpDay1otfOFASyN68tbGiv9YFD1IFrb314X18WcUg54fl1A6MXa230ATyCST89oUHVP76AaJ4lhXnzPDOOV0PU6RIpX0CXx7cALD6YFH//8+xxdrJ27umi9chbZKfoj5a2VeQwXUTchxXz3LPJDlhNYRLqPhMcpTzqJOS3w+//tRF9B), which it would not be [otherwise](https://play.vuetifyjs.com/#eNqlUl9v2yAQ/yqUacomBTtLtz04adS97RvsoVQVsc8xKwYE2FkV5bvvADeN0j5U6hvH3f3+wd2B/rK2GAegFV0H6K0SATZcE7Ju5Ehkc8NpbXQQUoPjNHUISf2RCWtJ1Q5KsQ7krgs42wrlgVPiw5MCrLeiftw5M+imIls1YAsheOAB130HEMhpdfljYf/ham2UcVg7aLAqJ8pMx7bCbZKytwjs4KyC1V42oau+LRafVxk8n0/qs/4EWiLUZl2+YCdnuX4mTjPxzPW6PIsIS187aQPxEIY4LntrXCAH4qAlR9I605MZZjuLw5iiD6T3O3IT+19mv0EpQ/4Yp5qr2dcInuEm6OgPj0XSomQtgjT64WHvhCWHKKeXesq9IoNGDVeZX+iw4voYRz6dng5FZTuMYfC1M0qhXWbaFhcr8hOjz0tJx8RN5zRDsl7Y4q83Gn9J4uZTw3NaZTXxDq3GmtMuBOursqwbjWsNKDm6QkMote3LWxwr3aCD7IE1pr+9Lq6LJabsw/l1Ab5nW2f2HhyCcDo/owmyfXoH1TSJDMvie2aYrpgSWx8pXkGXyDeCYw50Ay5++vc5ulg7d3XReuUssmP0R8xbSf3oL6KufYr57lnkhywnsIh0HwmPc5p0InNaoPf/ASGQX4w=).

> Example showing min-height as [unset;](https://play.vuetifyjs.com/#eNqlkM9O4zAQxl/F+NJdqYlXZfeSLSv2xhtwwAi5yaQ1+J/GkwKq+u6Mk4CqckHi5vHM9/2+mbuD/J9SvR9ANnJN4JMzBP90EGK9r0xKoukH56od2O2OrrTsjcugpcj06oDrjWmfthiH0DVi4wZusViTJpbnHQCJD+nqz6/0wtI2uohcI3RcqQmmRhq/1+okBZe5RZtIZKChtK1PEUkcBEIvjqLH6MWC4y/KcBtDJuHzVlyV/o/FDTgXxW1E110sfhbzyW62Ljvwsx7ZzraGbAwPD89okjiUWN6GefVGDIEzXEx8E+ivDsfRcDaRSzn1Km9S/Zhj4IuOJnpuZC2bybb8ceZSa7kjSrlRqu0Cyzpwdo91AFIheXXNYwqHQNZD1UV/fVlf1ivV2Uyn3zVkX20wPmdANtFyeYIh279+ATVPMmFV/54I81flzCYXxCdrxbw9YIUQOkDAr250Jjvd6qz1abNC58Mf+d7Ohqd8duo2j2e+ew/5rZVHs+J0X4DHpRxzMnkUyPs3g0gdeA==) <img alt="image" width="845" src="https://user-images.githubusercontent.com/61766491/240019060-a037fcf7-51ff-4c65-8d1b-1ce0a1d9e4ea.png">

In terms of changes, I was thinking that the behaviour in that example could be achieved by having .v-application__wrap's default min-height conditional on the CSS class added to VApp's root element when full-height is true i.e.:
```
.v-application__wrap
...
  .v-layout--full-height &
    min-height: 100vh
    min-height: 100dvh
...
```

**Comment by hanool** [comment]
At least delete it from api doc..
