### ISSUE TITLE
[Bug Report][3.2.4] The v-data-table example in the documentation does not work in codepen.io

### ISSUE THREAD

**Issue by bibibala** [vuetifyjs/vuetify#17386]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
the example is form https://vuetifyjs.com/en/components/data-tables/basics/,

"[Vue warn]: Failed to resolve component: v-data-table
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement." "
" " at <App>"

### Expected Behavior
i want to know ,why

### Actual Behavior
to fixed docs

### Reproduction Link
[https://codepen.io/bababaZhao/pen/yLRxNER?editors=1011](https://codepen.io/bababaZhao/pen/yLRxNER?editors=1011)

**Comment by KaelWD** [comment]
Have to use `vuetify-labs.js` instead of `vuetify.js`. We're removing codepen from the docs anyway so not much point fixing this.

**Comment by bibibala** [comment]
oic,thanks
