### ISSUE TITLE
[Bug Report][3.2.5] v-tooltip - target is set to content of activator slot ([object HTMLButtonElement])

### ISSUE THREAD

**Issue by ml1nk** [vuetifyjs/vuetify#17397]
### Environment
**Vuetify Version:** 3.2.5
**Vue Version:** 3.3.2
**Browsers:** Chrome 111.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a v-tooltip with a v-btn inside:
~~~html
<template>
  <v-app>
    <v-main>
      <v-tooltip>
         <template #activator="{ props }">
            <v-btn v-bind="props">Test</v-btn>
         </template>
        Test
      </v-tooltip>
    </v-main>
  </v-app>
</template>
~~~

### Expected Behavior
target is not set

### Actual Behavior
target is set to an invalid value
![image](https://github.com/vuetifyjs/vuetify/assets/4943440/7a6333d1-16fa-4d15-8863-42f241cbd7e2)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUM1OwzAMfpUQDgVpbaRNXKYNjRsPgMRh3aFrPQg0P0q8IlT13XHSbmq3yyR6qGL78/fjbctfrM2aI/AlXyEoWxcIz7lmbNWkhbXxGQtVSD1UsUZjapQnQN89EbD7okTZFGjcOucts85Yz7qcj9E9zR41o7/UFSEjjlBv4HEl4nDCLyYO+y9gz7ZoZ+ordM7OQ9FnmjBR6UsnLTIPeAxjqaxxyFrm4MA6dnBGsYSOlARwabRHpvwHW4f5Q/IKdW3Yu3F1dZc8BvKejoj4jPdcZMJmX95ounMbvOTDgOIuWeyEHmmEOuefiNYvhSgrTWsV1LJxmQYU2iqxIZhwR41SQVoZtVlki2wuKulx3M7Aq3TvzI8HRyQ5n41kUB5+b5AakKQwz556haGV1sXeB4krakF6DbjUga7Agbs10cXaONXF6CpZUO9y3dG9a6m//cWpSx/PvD2Z/FfkSBaYdkGwm/Hok5TjAt/9AWOqGBI=)

### Other comments
Is also occuring in https://vuetifyjs.com/en/components/tooltips/

**Comment by ml1nk** [comment]
Yeah, it doesn't affect anything directly, it just saddening to see the dom polluted. I had some of these in my codebase some time ago because of bad inheritAttrs. I found this one by coincidence because when i was wondering why v-tooltip is eager by default.

**Comment by KaelWD** [comment]
Vue doesn't separate props and attrs anymore, and we need to pass target to some transitions. If the transition component doesn't have a target prop it'll end up in the DOM instead.
