### ISSUE TITLE
[Bug Report][3.2.4] v-data-table selection does not update

### ISSUE THREAD

**Issue by subinznz** [vuetifyjs/vuetify#17392]
### Environment
**Vuetify Version:** 3.2.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
two users view the same data table
both users select same item
one use deletes an item from the row

### Expected Behavior
when the table updates and it sees that the item no longer exists , the selected item should be removed

### Actual Behavior
it two users are on the same table page, if both selects the same item , but if one user deletes an item the item will be removed from both users , but the select does not update for the user that did not click the delete .

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

**Comment by KaelWD** [comment]
You need to handle that yourself, having something in selection but not items is a valid use case.
