### ISSUE TITLE
[Bug Report][2.6.15] indeterminate color

### ISSUE THREAD

**Issue by theRenard** [vuetifyjs/vuetify#17390]
### Environment
**Vuetify Version:** 2.6.15
**Vue Version:** 2.7.14
**Browsers:** Safari 16.3
**OS:** Mac OS 10.15.7

### Steps to reproduce
when selecting some elements the selectAll element loses its color 

### Expected Behavior
the color is the same

### Actual Behavior
loses the color

### Reproduction Link
[https://codepen.io/theRenard/pen/YzJONbL](https://codepen.io/theRenard/pen/YzJONbL)

### Other comments
the problem is probably due to the fact that in the props the value is false, whilst it must be true when indeterminate is also true to honor the color. 

On quick fix is to access the v-slot:header.data-table-select and do something like that
```
      template(v-slot:header.data-table-select="{ props, on }")
        v-simple-checkbox(
          v-on="on"
          :value="fixValue(props)"
          :indeterminate="props.indeterminate"
          color="primary")


    fixValue(props: { value: boolean; indeterminate: boolean }) {
        if (props.indeterminate) return true;
        return props.value;
    }
```

but I think that when the checkbox is into an indeterminate state the color must be honored no matter what value is (true of false)

**Comment by lioneaglesolutions** [comment]
@johnleider can you please confirm desired behaviour here? Same behaviour is in V3 ([playground](https://play.vuetifyjs.com/#eNqNUUtuwjAQvUrkNbGlflQpShE9B2ZhkkG4+KexkxYh7t5xLFoKC7L0m5n38/rEPkLg4wCsYW0CG4xKsJSuqtqx7rxLSjvAamcG3U9wGeyhO2z9d9VY34OpR2UGeJcs4QCSVZ03HukZUFuFR0LE49udMnH2cQGq++XLQLseEqDVjvIUcNmKP4ISMQOXjIS04rcBtmBGu0Pkn9E76uaU9yXrYpSsqdaFUbJ9SiE2QnS9o02Ko0fkDpJwwQpqNendcfXMn/ir6HVMF6g2ahv5RJaZNtKdSVDb4DHVVoUb1TKYlCckY8SU3w8srGhN4OCStlD33k5eXt6KmSucQ7T1Fv1XBCQWyRZXOtnxDK1HcUnijlqQ3ghYI9B/IeDcSDdn/2LdzO6iZflzbvy8YOWOup9Ms80PYyEHlQ==)).

<img width="627" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/61766491/952f8af6-50ea-4f2a-be23-6f81b945db57">

**Comment by johnleider** [comment]
> @johnleider can you please confirm desired behaviour here? Same behaviour is in V3 ([playground](https://play.vuetifyjs.com/#eNqNUUtuwjAQvUrkNbGlflQpShE9B2ZhkkG4+KexkxYh7t5xLFoKC7L0m5n38/rEPkLg4wCsYW0CG4xKsJSuqtqx7rxLSjvAamcG3U9wGeyhO2z9d9VY34OpR2UGeJcs4QCSVZ03HukZUFuFR0LE49udMnH2cQGq++XLQLseEqDVjvIUcNmKP4ISMQOXjIS04rcBtmBGu0Pkn9E76uaU9yXrYpSsqdaFUbJ9SiE2QnS9o02Ko0fkDpJwwQpqNendcfXMn/ir6HVMF6g2ahv5RJaZNtKdSVDb4DHVVoUb1TKYlCckY8SU3w8srGhN4OCStlD33k5eXt6KmSucQ7T1Fv1XBCQWyRZXOtnxDK1HcUnijlqQ3ghYI9B/IeDcSDdn/2LdzO6iZflzbvy8YOWOup9Ms80PYyEHlQ==)).

Yes that is the expected output.

**Comment by theRenard** [comment]
May I ask why this is the desired behaviour and on what principle is that based on ?

I know that Vuetify is strongly based on material design, and I don't see the same behaviour as Vuetify on this matter, so I wonder why Vuetify decided to go on a different path.

Those are [material design](https://m3.material.io/components/checkbox/specs) specs.

![image](https://github.com/vuetifyjs/vuetify/assets/61255863/1d4eae9d-e3f4-45e4-aac4-77bbcb6d1a4e)
  
I can see the same behaviour in other design system (element.js)

![image](https://github.com/vuetifyjs/vuetify/assets/61255863/32d7e5eb-ea0c-458d-a2fd-6ac2cf766a3f)

Pajamas

![image](https://github.com/vuetifyjs/vuetify/assets/61255863/99faaf10-84fd-4434-85c9-bf864ddec6ec)

Decathlon

![image](https://github.com/vuetifyjs/vuetify/assets/61255863/20cd05dd-07df-4d70-a11e-c0d243080161)

and many many others

**Comment by lioneaglesolutions** [comment]
See https://github.com/vuetifyjs/vuetify/issues/17390#issuecomment-1553859289
