### ISSUE TITLE
Electron + Vuetify

### ISSUE THREAD

**Issue by AngelMunoz** [vuetifyjs/vuetify#174]
Hello Good evening
I love your project, tough I'm having some issues to integrate it with electron
basically it just throws some errors to the console and prevents things do some work
I'm rather new to vue and electron and 0  knowledge on webpack but I guess it has to do with the setup i'm using
here I bring you some screenshots and a link to the repository I'm having trouble in
any help regarding of this being an issue or is just my setup would be great thanks!
 

you have to have an account in gitlab to check it 
# [REPO](https://gitlab.com/MoDeTech/punto-venta-vue)
![e3](https://cloud.githubusercontent.com/assets/8684875/23391235/b564eeae-fd30-11e6-97e3-f8b53b46a720.PNG)
![e4](https://cloud.githubusercontent.com/assets/8684875/23391234/b5647960-fd30-11e6-95a4-459c26e9c982.PNG)
![e1](https://cloud.githubusercontent.com/assets/8684875/23391233/b5640a70-fd30-11e6-927d-0a0fef501c56.PNG)
![e2](https://cloud.githubusercontent.com/assets/8684875/23391232/b56409c6-fd30-11e6-9d0a-fdf8ae035095.PNG)

**Comment by iqbalsafian** [comment]
You have to declare/initiate an array of 'items' in your data/props for v-menu, for v-modal provides modal: true and bottom: false. i think you wrongly bind the attributes in the v-card module. Same thing for the v-expansion-panels too. Ensure that you fill up the props and slots accordingly.

**Comment by AngelMunoz** [comment]
thanks, well I just copy pasted the examples from the docs I'll try your suggestion

**Comment by johnleider** [comment]
It is possible that the menu issue you are having is related to #175

**Comment by AngelMunoz** [comment]
tested modal also, the suggestion given worked as expected
my fault on not using props properly
how ever using the following code also triggers the same error
```vue
<template>
  <v-modal v-model="bottom" bottom>
    <v-btn slot="activator" secondary dark>Bottom Modal</v-btn>
    <v-card class="secondary white--text">
      <v-card-text class="subheading white--text">
        <v-row>
          <v-col xs10>
            This is an example of a bottom modal.
          </v-col>
          <v-col xs2>
            <v-btn primary dark v-on:click.native="bottom = false">Close</v-btn>
          </v-col>
        </v-row>
      </v-card-text>
    </v-card>
  </v-modal>
</template>
<script>
  export default {
    data() {
      return {
        bottom: false
      }
    }
  }
</script>
```

**Comment by AngelMunoz** [comment]
I think that error is a separate issue
thanks for the help!
