### ISSUE TITLE
[Bug Report][2.6.14] v-list-group hover/focus affects text of other v-list-items

### ISSUE THREAD

**Issue by laventnc** [vuetifyjs/vuetify#17401]
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.6.14
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
hover/focus on the v-list-group (App label) at the top and watch the text in the list.

### Expected Behavior
v-list-items in other lists aren't affected.

### Actual Behavior
v-list-items have their text transition quickly. looks really blurry on dark mode, but also happens on light mode. 

### Reproduction Link
[https://codepen.io/laventnc/pen/jOeedjZ?editors=1010](https://codepen.io/laventnc/pen/jOeedjZ?editors=1010)

### Other comments
I tried looking in the chrome debugger to see if any classes/styles were being applied, but I don't see anything. I also tried turning off ripple, as well as messing around with the markup _(such as creating multiple v-list/v-list-item-groups & setting the 'group' prop on the v-list-group to a value that will never resolve)_.

**Comment by lioneaglesolutions** [comment]
I can't reproduce this on my end - looks completely fine. Do you have a screen recording? Have you tried a different computer?

**Comment by laventnc** [comment]
odd, are you using chrome? it's most noticeable on the active item (dashboard), but also noticeable on the others. oddly enough, the icon doesn't seem to be affected. I've reproduced it on 3 separate machines, using both chrome & edge

https://streamable.com/jdksgy

**Comment by KaelWD** [comment]
Sounds like a browser bug. The elements are repainted but I don't see any visual change.

![Screenshot_20230519_233924](https://github.com/vuetifyjs/vuetify/assets/16421948/f30ed19d-8617-409d-b3cc-26d7644e17a0)

**Comment by laventnc** [comment]
curious, what tools are you using in that picture/to make that determination?

appreciate the help!

**Comment by KaelWD** [comment]
devtools -> rendering -> enable paint flashing

**Comment by lioneaglesolutions** [comment]
@KaelWD can this be closed?
