### ISSUE TITLE
[Feature Request] vuetify3 (VDataTable): Add checkboxColor prop

### ISSUE THREAD

**Issue by he-jialin** [vuetifyjs/vuetify#17402]
### Problem to solve
Add a easy way to change the color of checkboxes color

### Proposed solution
Create a checkboxesColor prop in VDataTable.ts and header.ts (the value is passed from vdatatable to header)

**Comment by blalan05** [comment]
As easy as this? <https://play.vuetifyjs.com/#eNqtll9P2zAQwL+KFWkqSCTpfyDqEBvsD2MPe5gmTZQHNznAI7Ej2y0w1O++c522iZuUVlqe4jvf3e/u7ORuXr0PeR7MpuBF3khDlqdUw9mYEzKa+Qnc0WmqlZ9LMWMJSBItRe/H3iv5dUk1/UknKUQEVxcPED9OxPNHzc06FqmQEWlJSFrz+Xzsrdyila+NmREQMvMzkUCKLhWkEGtIxp7VRA9AMayJVrytNAxhjTwBpUDqlcLI/RlNp4BKTjNYKtSDePJtACuIU6qMBxTNqGaC+x2792wUliHt0i0FJjMKSwUbqViyXC9yhOdcSE0KG/Jq4xmP5OBwuSREgp5Kvl4jY5F/RG5uj9biIneUrmWkbGcezbTpQ+vSFoQcdNrte/QoZ4zfH7ZK7sxDU3aPXWopTaV2lQrpbVfvaKrA0T7CCxqa0lbt5pXV6wroguI5YKBaR4VpvBQ0mnymyG+gC4s7qps3X1A5UZXtsZE0G/yQQgPjFRNsq5E1G11JgRbv1hYMBdXt5ZYtj+X2npkimnSl+Auc/Bb3081mLKsVkc7g1NFhXSIyDNobJph/RLp9R14kGZH+honJBiNsa2gt+lUMJJZAM6IoT55Y/NDM3+0d1/GfNvFvbC/x9/4T/yf8CjC5hXnYrWPuNBfdJVtBb5pY6GqWu0BfTPOYPjrXr0zdaw/qqHuBW9ECerh3pU/2hv6CnyGQEzwryRbwwXC/cvfdK7Ei7wWuqjgj1Qi7oH+DNH0hE6B8C/lxbcnbTeCnjZdz08SCV6W7cH8XacpykW+hPq093u3AFS+pq30vU9cyV93swvxVcHiJRTZphu63XYridDdAnzSe7mHgNs1i96viXbgvBZ9u+Xb3B7WF7g6azseg+i2rXMn6g93dv9jXTF/jr7WRetCprXS38ToO3XquqN0eWObmu7j+mc7ti1XiYhQWo5Z35KWMP6rgjxIc59dFjmMvVjgMrv67ODlqnasoDOOE404cNNlMBhx0yPMsxMlXs7uXczw8wSBMmNJLkZ/SiQoWzoyn2zGfY0CWmdHOz2juRLWKReSi1mMPPZn1GwjnuC2UU65ZBn4isgVL/9jClOQBqMyfSPGEgwV6GXtFhRZxDPEOsd5KF0NsuA7NDAnSl8BxCgW5a0qOWSUtR7eRWtHquTc/8qwd1n4B7d3+A4UEVZQ=>

**Comment by blalan05** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by he-jialin** [comment]
Hi, thank you very much for your answer. The effect I want is the background color of the selected row.
