### ISSUE TITLE
[Bug Report][3.3.0] VDataTable - `show-select` checkboxes cause any checkbox to select all checkboxes

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#17408]
### Environment
**Vuetify Version:** 3.3.0
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add `show-checkbox` prop to table and set to true.
2. Select any checkbox.
3. Notice all checkboxes are triggered

This also occurs if you have the `data-table-select` added to the `headers` array.
```
{
  key: 'data-table-select',
  title: '',
},
```

### Expected Behavior
Checkboxes within rows should work independent of each other. Only the header checkbox should affect all.

### Actual Behavior
All checkboxes are selected no matter what checkbox you select.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVltv2zYU/iuEsCEbEF0sW06ipUOLdN26DlhehzoPtMQ4XChSIGkHaZD/3sObrIvtFuiLYZ7bd76PRyQ/v0Tv2jbZbUlURteaNC3Dmvy+4ghd72LctvavXTSYcr+y6xprHGu8ZiQYESoplFBvVlFNlCJSq1XUcz4QXBNp3P7fwKsexFOsCCOVhggtt2TgtpXjlsi4xRsSi1ZTwU0t67gl8hbM/zrrPhEa7lpO+z0HXmDsiJmFo3yd9qSApaokbTVSRG+NuwIMjTwJ9AZ9digvrqammpESnb13GqBfZlm2gVy5o3zz69m5i8KMbjhEKY2lDkYlpO2uRPeYKeKtj+QZAjluiIt7tb8vHdANZkJSos7Ou6qE17ByiVVwTxI/YOjOtHQw7x7racoNlmt1Iqky/mnarRSaUH4isXUR09SPUkDez8fyKLhd0t1vZhvc3oT5c5vTbY3R0PCW4gvh6D+x2e61DzKVaFZceRtIUKJlknUhQK5E+cKvfc8lWnQhph1AmA12agD+N2HsGa0J5lPk+UXRR87GyFcT5H2IR86OI3+i+hPs6QS1mF32UfMJ4WXoqoO9GIIuj4P+UTFM5RQ0X+Z90NlU5fkYdB/iYS+Ow/4J3xqRawnf6AGZi+Vp7EUYgA57ngRT2OETnD9WBFUA3SCFef1Eq4cD/OdBQ9vD1biFzt0bsqDIt4fsH8EYbUV7gPvVQPcsCcswYmEW9iM2RM2Po95s2wo/+lNqAJoN5nqeBHJhwL5N9vI47F+Ck+dKNOsp8CIbjPZ8zPZyArxMQqseeFEcR34v+PbAB7UoBhrnxXhzi9mU72i+8p7O/ZPtwHU3OuTCwTnzRwFCO8y2YJm5LgZEQnDuWXbBuZPhYHAxrlycqAy336SPE+E/wVtE0/vnxNzVHwTII5M+53eMjcrFTsxXp9N16i5ruKaj84g2LVypcMW3yf9KcHjkWDh4NVgHvBTK0MAqAmSzhueJ1q0q07SqOaTVhNGdTDjRKW+b9C2EpXLLNW1IXIvm7TyZJ4u0pkr3zQlRTbyW4gnuISiyinzTFsYQ/A4oH2kRMofgTTHDa2UgJqVT89CAV5KES5JIIr+X0Sitz2rkmjDz6r+C3ozyRzWSulJWZjuiZv1DlG0xU+nOAL6eR7ZPQLYJ0d1Xf0A/Xw==)

### Other comments
I think this used to work correctly in the last release, I don't remember exactly.

**Comment by nekosaur** [comment]
You need to set `item-value` to a unique property on the items.

<https://play.vuetifyjs.com/#eNqllm1v2zYQx78KIWzIBkQPli0n0dKhRbpuXQcsb4c6L2iJcbhQpEDSDtIg373HJ1kPtlugeRGYvDv+7v48kfz8Er1r22S3JVEZXWvStAxr8vuKI3S9i3Hb2p920GDK/ciOa6xxrPGakTCJUElhCfVmFdVEKSK1WkU94wPBNZHG7H8NrOpBPMWKMFJp8NByS/rm/p+BxDvMtgQcOW4Gji6FuCUybvGGxKLVVHADtYZbIm9h+l83uw+Eyrra0n5xQQCY7BQwA6fNddrTDIaqkrTVSBG9NeYKGBr5atEb9NlRXtyammpGSnT23omFfpll2QZi5Y7yza9n584LM7rh4KU0ljpMKiFtdiW6x0wRP/tInsHRKOL8Xu3/lw50g5mQlKiz825VwmsYucAqmCeBHzBkZ1I6GHeP9TTkBsu1OhFUGfs07FYKTSg/Edg6j2noRykg7udjcRTMLujuN7MNbm9Co7rN6bbGaGjqluIL4eg/sdnutQ8ylWhWXPk5kKBEyyTrXKC4EuULP/Y5l2jRuZh0gDAb7NQA/jdh7BmtCeZT8vyi6JOzMflqQt67eHJ2nPyJ6k+wpxNqMbvsU/NJwcuQVYe9GEKXx6F/VAxTOYXmy7wPnU1Vno+hexePvTiO/RO+NSLXEr7RAzIXy9PsRWiAjj1PwlTY4RM1f6wIqgDdIIV5/USrhwP1z4OGNoercQqduddkQZFvN9k/gjHaivZA7VcD3bMkDEOLhV7Yt9iQmh+n3mzbCj/6U2oAzQZ9PU9CcaHBvl3s5XHsX4KT50o06yl4kQ1aez6u9nICXiYhVQ9eFMfJ7wXfHvigFsVA47wYb24xm9Y76q+8p3P/ZDtw3Y0OuXBwzvxRgJC9VKHPXRaDQoJz7qvsnHMnw0HnYrxycWJluP0meZxw/wkeLZrePyfmrv4gQB6Z9Gt+x9houdiJ+ep0uk7dZQ3XdHQe0aaFKxWu+Db5XwkOryGLg1eDNcBLoQwJrCIgmzG8Y7RuVZmmVc0hrCaM7mTCiU5526RvwS2VW65pQ+JaNG/nyTxZpDVVuj+dENXEayme4B6CRVaRT9piTIHfgfKelpA5gp+KGV4rg5gsnZqHBrySJFySRBL5vRWNwvpVjUyTyrz6r6A3o/xRjaSulJXZtqgZ/1DJdjGz0p0Bvp5HNk8g24Do7isiOEl8>

**Comment by KaelWD** [comment]
Yeah looking at it again in 3.2.5 it would appear to update but v-model:selected would remain undefined.
