### ISSUE TITLE
[Bug Report][3.3.0] VAutocomplete height is increased when v-slot:selection is used

### ISSUE THREAD

**Issue by lecaillon** [vuetifyjs/vuetify#17405]
### Environment
**Vuetify Version:** 3.3.0
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Windows 10

### Steps to reproduce
Compare the height of the left autocomplete vs the height of the right autocomplete in the playground.
The only difference between both is the use of the v-slot:selection
If you change the version of Vuetify to 2.2.5 in the playground, the height is the same.

### Expected Behavior
The height of the autocomplete should remain the same wheter or not you use the v-slot:selection. The autocomplete on the right has the right behavior

### Actual Behavior
The height is increased when you use v-slot:selection

### Comment
The issue happened with a `density` applied (either compact or comfortable). Without the density property it works : the height is the same.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1U81u2zAMfhVCFzdAbBdpsQFGUnTvMOxS56DYzKxVlgxJdn8Cv/soydniBEOzQ08SKZIfP/LT04ENPTqxf8t+WVYw0XbaODhAZZA7/BHfYIS90S0kU2xSqlLhawittLIOpgfYzBNvDqUCcA22WFDRGve8l+57tJOam+cExmWpxkWp2JJ967qMKlEfa4dtJ6nQgy+wHlKjX8I1GJWWkxFM3jtdaYpHhzCkra5Rbko2cNmjLRkUgqpZ8oSTHDUqK9wbeXwarxz5GlFjWqPjQloYuBFcOQqwWup0L6TEumR/QAn22CABWqldYVFi5YRWlHQAjwTjLAPgEP1ZaAzG8aRaPuMbXXNiR/bk/kv/P2ex+pRhXNGpv8cNzpiubWVE5+g2iWkSCATZ1NzxAm4WsHmAKCQI87MFPCV7rZMlJDtu/LEX7+/B7OnckqB8bORMOmtQ/GxcAfdfule4eRGuuVjaIpklrU6zbkNWrv+VNC68gj21iQ4pWQr1bOlLaUViDr3TeC2Nm3qPQCVrnOtskedVrSiS9iQGkyl0uerafPpQj3fZXXab18K6oyuVfGezUMxX2hI2AcaPm7a8O0ONDwF5miGpoUdvf9DCI4XlpldOtCQG3VIvq+z+a2zmxJ+hbdMdrdeioSolm0YZcHzHV2B9RJcgLkrnhDegSQ2qGg2aaymdpc1onb1dUAv79hMflyzm0exD02z7G+/hxKE=)

**Comment by yuwu9145** [comment]
The selection slot is implemented to have the same behavior as assigning chips prop because having chips in that slot is the typical use case.

It is higher because chips come with margin top/bottom, which is important when chips stack on top of each other.

**Comment by lecaillon** [comment]
I don't understand. In Vuetify 2.2.5 it is not the case. The selection slot does not add any additional margin. Is it a new behaviour ?
