### ISSUE TITLE
Select with slots showing weird behaviour

### ISSUE THREAD

**Issue by ACalitz** [vuetifyjs/vuetify#1740]
When using a v-select component that makes use of the selection slot and not the multiple prop the selected value is displayed incorrectly whilst the input has focus. An example of this is using a chip to show the selection, with the input in focus the selection in shown as plain text and when the input is not in focus the selection is shown as a chip.

Using the multiple prop fixes this issue.

### Steps to reproduce
- Single select
  - Use the 'Single Select' to select one of the options
  - The selected option is shown as plain text in the input
  - Blur the select
  - Suddenly the selected option is shown as a chip
- Multi select
  - Use the 'Multi Select' to select one or more of the options
  - The options are all immediately shown as a chips

### Versions

Vue, Vuetify all on the latest versions

### What is expected ?

The selected option should immediately be shown as a chip like when using the multiple prop on the select

### What is actually happening ?

The selected option is being displayed as plain text and then switching to a chip when the input loses focus

### Reproduction Link

https://codepen.io/anon/pen/bodRLr

**Comment by johnleider** [comment]
The reason is single select with chips is a very interesting scenario. How would you edit the text if it was in a chip? You can't, so it doesn't/shouldn't show, because it would make no sense.
