### ISSUE TITLE
[Bug Report][3.3.0] VImg aspect-ratio not working in vuetify-3.3.0

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#17413]
### Environment
**Vuetify Version:** 3.3.0
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
Swap Vuetify version in the playground to see.

### Expected Behavior
Image should reduce by the aspect ratio.

### Actual Behavior
Image doesn't change aspect ratio.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUktOwzAQvYrlTUFqYqSyqgqCOyA2mIWbTFO38UceN4Cq3J2xk5Z+NpXY5WVm3i/52PNuB1GvfsoN8jnXxrsQ2Z5VAVSE92HGerYKzrDJuDuRVlr4zquVsxjZOGBP54d3e2kZi2swMCfSGlZq18a3AU9qFbYT1k+l7e+l5VP+6n1JTORjEcH4loieE8GiK5T3+TEDo7QdUcbaNAxD9ST5OkaPcyGq2iam5GGDZeWMqF2FQhvVAIrWNQ7FOC8SKrpZ0epmHUvsGskP3DLOFXqoYhFU1I4EHv+G4mBInDhKYPC6ECcZKNxQLW16qtpZCpnLkeMAJaeKBkaZPkrC54E2WEOru1BaiMJ6I15oTYSdjdpAUTvzMitn5aOoNcbT1yWgKZbBfSEEIpGcGj/KpApukBo3s8LDoHDsTy0xSVxRC9LrIBQBbA0Bwq2JLs5OU12MrpIl9Z7+J+q71XaLF1VXmGv+OJj8V+RMlpg+k2A/5dknKecD/vkLwzgi2g==)

**Comment by y-takebe** [comment]
Hi everyone.
In my case only vertical images are affected by this problem.
If you are in a hurry, the css property aspect-ratio might solve it. That's how I temporarily work around this issue.

https://developer.mozilla.org/ja/docs/Web/CSS/aspect-ratio

**Comment by IngusSkaistkalns** [comment]
I can confirm what @y-takebe is mentioning regarding vertical images, landscape ones are working fine. I created small example what I experienced on my project https://play.vuetifyjs.com/#eNrtVMtu2zAQ/BWCF7eARdqODDeGU8Qu3C8oeglzUETaYSw+QNJKWkP/3iWlOrJzCdoccshNs9yd2V1h9uaA670IcvOLPHg8x1JZ4wI6oNKJIoif7Rtq0MYZhQZd7oBppsVTSi2N9gF1D+jqtPDTgWmEwr1QYg6kXGyKfRV+tHjAC7cboGbIdPOZaTzES2sJMEEfiyCUrYDoayRY1FlhbfpMQBVSdyhhZx6PMAVKU/UCKSTVth9ByLvyiuH7EKyfU7rNCWRk3DpRS/FISqNoPllPZsv1ejRe5fmX6XK1no0mo+/fVtPlLJ+uLsmD3TJ8ylqaWrjT0LzwVpQhc0WQBiTHZHZaRfvN0/Pu/2kcSZzgnMhAn7Z8uqukK39fjsfvuOOPH/BWHUf87IiIjn6JoHXSgvYcBtZrjQ+ZFg6B0WDBZF3WPXiGwcAtI4snI+LnaUuuoYyLStaOaBGotopeQxp1ex2kEhk36vqCXJCcculDP0yEV9kdNOyFAxKG4R4cZeIReYVUl5kURq1CF8qq4s5HiRfUFPRg8ZkTmgsHf+CVE52V9ac6e3oxWVRv4NrBviupd/5s1aVPa7752+R/jZzIItNtFGyGOPUJyqkA3/4Bd0XDmA==

**Comment by juntralala** [comment]
is this bug really fixed?
why i found `aspect-ratio` still not working in vuetify 3.10.8

**Comment by KaelWD** [comment]
Yes. Open a new issue with a reproduction if you think it hasn't been.
