### ISSUE TITLE
[Bug Report][3.3.0] V Data Table does not load on Safari and all IOS browsers

### ISSUE THREAD

**Issue by DarraghOFlaherty** [vuetifyjs/vuetify#17429]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Safari
**OS:** IOS any

### Steps to reproduce
White screen when loaded on IOS, an error code in the console `syntaxError: Invalid character '\u00a8'`

### Expected Behavior
I'd expect the page to load

### Actual Behavior
White screen, nothing loads

### Reproduction Link
[https://codesandbox.io/s/ecstatic-browser-z053nz](https://codesandbox.io/s/ecstatic-browser-z053nz)

**Comment by DarraghOFlaherty** [comment]
@KaelWD how would you suggest I reproduce this seeing as it a browser specific issue?

**Comment by KaelWD** [comment]
Something I can click on that demonstrates the problem would be a good start, the codesandbox loads fine.

**Comment by DarraghOFlaherty** [comment]
@KaelWD It's a little difficult because the issue is only happening on older versions of IOS. I'm not sure there's a service out there where I can imitate old versions of IOS 

If there is please let me know and I'll happily create this repo link

**Comment by KaelWD** [comment]
How old? https://vuetifyjs.com/en/getting-started/browser-support/

**Comment by DarraghOFlaherty** [comment]
@KaelWD It should be supported version 15.7.6
