### ISSUE TITLE
[Bug Report][3.3.0] v-tooltip: Incorrect processing of the "origin" property

### ISSUE THREAD

**Issue by PurpleTape** [vuetifyjs/vuetify#17424]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Click on the "Incorrect" button
2. Wait for the tooltip to open
3. Click on the "Incorrect" button
4. Wait for the tooltip to close
5. Click on the "Incorrect" button

### Expected Behavior
According to the specified origin="bottom center"

### Actual Behavior
The tooltip will start opening with the CSS transform-origin "center center" property set, despite the fact that prop is set to origin="bottom center"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVk1v2zAM/SuCL9mA2E7R9aJlRYeedhh22a3uQbbpRI0sCZLiNQjy30fJsuO6RdsdCgz5QExSj4/PJJ27Y/Jd66zbQ0KTtYNWC+bgupCErGvekUowa78VCTPAiiTY0dOlTinhuC5k4fxLaZCpkmkleLUbjHSwblUHBkEaJiwUSQ9CiFAVc1xJ9CAAqUA6MGe3MnzDvbNUzqn2mZ86w6TlEeFIKtVqJTGIkp+H36OPnIYjkT3yH+okXWqFcpRVjnfMKU/ySLRR2vpj44FQcukkxpdc1hgVYjDih6yUMVC5dR4izjnyiZijESW9/oViCHZAvliPxIPeGIVFkKhstPzPgkvWAiWL9pCeHYuPlfv2A8UefDOwta0M145YcHsfWDiOfWbc0yZrDAq2yPKp0U/V4qsH7CEinDuIfsAyP1Tk2LOpucWcB0oaAY94yNse9tbx5pBG8jTekehtmcHbRcnFaqUfySpaN0xTcoWWeK1ZXXO5wUrRfjGxq54kJQawVt5BcJz810iO0hIaZWAgORJZdEzwOjQTEVyGMp+istIqsXc9KiEhfXoxphfQIMxAGhtvO7ncQn99Di9ZtdsYtZe151vPqD7pwDRolIYeg+ULfgGsg+gfCmOSt6EaSs6R5MqG4pghOBHbV5O+CprW3HdtVBs70s7Exk/hbnZwaAzOlJ1yiFihv+JvVNP78ca0lNiKCbisP62WxL8/R8EQehD+1WMXS+Lfk2PhC1s2tGmyTFCBnc0erJL4hAhQRVJZHEZK7uKOSrbOaUvzvKolRtYgeGcyCS6Xus1xCnwX31xml9kKZ8y6wZQK7JIsgHmk+0KeMGE/XmnL9Cxr7wiZY0lFgkj++g0KNxiWm73E0YW0Vm3g8qXnMjFnYNu0NOqPBYMgRRLaJ6bxhN+R6q1qMcUz6BzzYVekBmQNxq/c91U0OzatauZ6s7JJLweB/6lKwct8fPrafAKVV7hFHEx2Yuuzxy7zd3u+MP3fkPO6HHYtPt0D0K210yd7XLsv1NAvJP+Bx4BQQ8P2wr2E82n2CPPDMO7s5LRMgq7INVSb3P8FsiYYxQ==)

### Other comments
According to the source code:
https://github.com/vuetifyjs/vuetify/blob/8536bd1fc0eea6789648580a074bf66a3d40a461/packages/vuetify/src/composables/transition.ts#L24
the transition property allows to specify own "Transition" by name `transition="{ name: 'my-transition' }"`, or by specifying the component `transition="{ component: mytransition }"`.

The reproduction link contains both use cases, but when specified by the component, incorrect prop origin handling occurs when the tooltip is reopened.

That is, the following behavior is observed: prop is set to origin="bottom center", but the tooltip is reopened as with origin="center center". The problem occurs with any origin value. When the tooltip is reopened, it is handled as "center center".

At the same time, when specify transition by name, the problem is not observed

**Comment by KaelWD** [comment]
You're still using createTransition from 3.3.0

**Comment by PurpleTape** [comment]
Sorry my mistake. Thanks for the fix!
