### ISSUE TITLE
[Bug Report][3.3.0] Path of types and package.json "exports" field seem to not match when using "moduleResolution": "bundler"

### ISSUE THREAD

**Issue by Llois41** [vuetifyjs/vuetify#17421]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. `yarn add` all the stuff the installation page suggests
2. try to import e.g. `createVuetify` as a named import from `'vuetify'`
3. see error in IDE or run `tsc`:

```
TS7016: Could not find a declaration file for module
'vuetify'. <...>/b-informed/node_modules/vuetify/lib/framework.mjs' implicitly has an 'any' type.
There are types at '<...>/b-informed/node_modules/vuetify/lib/index.d.mts', but this result could
not be resolved when respecting package.json "exports".
The 'vuetify' library may need to update its package.json or typings.
```

### Expected Behavior
Type imports resolve corretly work and TS shows no error

### Actual Behavior
see reproduction section

### Reproduction Link
[https://github.com/Llois41/b-informed](https://github.com/Llois41/b-informed)

### Other comments
Also tried vuetify@3.2.0 and got the same error

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/17319#issuecomment-1554526486
