### ISSUE TITLE
[Bug Report][3.2.2] slot Item in v-data-table does not reorder when sorting other columns

### ISSUE THREAD

**Issue by henrythc** [vuetifyjs/vuetify#17426]
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
See reproduction link.

Please click the first pen icon in Actions column, the data in the dialog is the data of that row.
Then sort Category Code and click the first pen icon in Actions column again.

### Expected Behavior
The data of the dialog should be the data of that row after sorting Category Code.

### Actual Behavior
The data of the dialog  in 'Actions' always remains the same

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNWG1v2zYX/Sus8DxwCkRy0rQr4CVFs7TZChR7adZ+qYtOluiYjURpJO0m8/Lfdy5JybIsKVmHFdMXW+Tl4bkvvPeK79fBaVlGqyUPJsFUHutEidIwzc2yfDaVIi8LZdiaKT5nt2yuipyNIDyqp5KFyFI/EY3PC5WfxYZfFkpwTbCQTAqpveBZkZfsxP2vJlIRZ8UlRrHH3jzONH9YTQn9uohTIbtnFzxOudJ+7v1UMjxrZoTJ+ISNThMjIDfaZ1f8Bu9x/a5BPJ6RkAXcZ59FahYTNg0Ojw7K62nAbvfbaF6rG3ZWpLzGTPwoBjYYT+/EeMGdncFnB+pjiskm3pODPrzTNGVvNVfs4pfXGzXT9OMSgx/171kfzIfahppnPDE83TitMudGxjNrzHki7mcaKJFOgwl77AlOg0oXGp0Gp9NgZ8Zq6aezZS6Fl3FK7iA/6YE+e3H+bhh9NU9Xg9hPe6BfDOO+iE3MTmWc3RiR6GH23/Rt8e5ieJN3FxWLbuQ+4JfDsC+vDVegPoj9qAf7fBj7XMhYJnwQus+b3w9Df88lV3ewPuqB/mEY+oc3Pw3CHvbA3uG/C7NMuTQVtDt4x2N3+JFe8WJ4XmZYiTfGjldhXFLeJUS85LGQ/q16MJoi9EKbwNjE58CTkf8zYhMBSH1S88GxxakHDS3MDYZTPo+XGTixubjmaegWbm9Cz4KLy4XBgsdPXOKwuGHJVVjGlxwThwcY1Yvic+iyCANhJMcMU7tpBaKy8NT5NeH+WCCZJIVKo2nQUtIqWlkGsDorjNUr8kkcy9eWEIxKi48TFJZCwtbQH9awBWbEBBIYRPNUgLdMBGLHV41fHYeXqSBLTIjXK8BhyG6TFJSUQPrZ8biG7iI53vJfc6Lpp8qjGKxdSi/O2VsgUxnsB662QraMPulCojTbgAQ5OwFek02Iosi6aFsYU+rJeJykEsvgCLFSkeRmLMt8/BxiY7WURuQ8TIv8+VF0FD0ep0Kb5nDEdR7OVPEZFQQgjfDGeiPmPu4Ht/KSdocDt4MfCrN4pmmLHegx9lshtBSX8A7i8Z4atZY1tWpN7Wjmj+Qt7J0JeaVbpk60NbOvdf9QZQtGSB/chrt9Ejb++83Xml1yc7ZU0NG8QqmmzNuSHI9rWXQFPxbgJJAZcIgqwWnw/OpmdUmEj0LZEJgG31I8jse0CzMLnMQlZ8LvU3UHiGG0Bbs89pDq7GIkHCE5s9IxkiGNuaWnP7+iliIuxXexFskFN29LWgYj2/k1UgbZEExP2uydnAdSXOOIan5hYNMcJFyn0h7EBku7QZNXqYpSV8rYF6x1cz/T254/aJRLJuzCKLSjPnI3qaQ1UaWTCftp9gmJ0A9jU5e/UCSFXvB0wr4riozHEgK3LV6Kk+wKRo+VoCRSk/zihnmOqHsXZyLtXivLpTkXPEs1hOBpJ+TVRyGcMLnMMq9LVe06B20JrGdIMzFne9a4UWWbhy6D0d4wQQSN2gLe7i1a0cqTW7MoiraX2PO8bUaeI8N7Del/7dyXeNF770dlrPUZjI1qRRBome3Q2xKgfoiqdlco1x5pcLQxRuzaZlqzPL5+zeUlteOHB/sw7u9LoSgIjIJCVXvfsmFrWfc6q/MOlTdLBE0XFZ/T6Fmxk2fswYMV+/NPNvp1ITS6AqxFINX7jDyxWnwVZZYPOz7Z0Tyqdolq2oDero2/NfbJl+A84wxMNVJMLNn/1vfAvMUnZKxwQNDyRL85+A/dBvwaytqt/g2NW8B9ajf8r+MVR2WhtKpvZML2HpIWVQ6r0kN9iCiE7NzulM0OFnugY3UNqUtIm/bPDaCxAvPQfoFi8OnB/7cavZ0Gz+a72BTKdncuFbv2rtUAz4zEmpmQKSRd/m52uGjYkOls40W9nW8C6Yf6VfEH9a51F3yfztMLd4h6QoSNrJBZ6tRjSDR/6orL8LFtIZ3E3+0foWbTXF2i2DuJVcqSDCmLjHETPuqyGAmF9tqgi8Ti0bP1ulHN2O3t8RiDu5R6cWwUrAQAai45uLAZ+ns0YbMsTq5gfbMQyZVE5NPngzeNX7cLSOVqo9k12bIRY3UxwyjqlB/pdmhFHLr1OxFu23C/Dg8ZKQDwTziw1MjBgwZdBH3dlHHCwxk3nzlHTPVAVjsXGYWG1Zjgcgrab/DH7TWCyw5GAxAehriHLoNsbLBTGzdfp65tcHQRmFiaZZxshX7Urn2Dqmsvs1xjOvxMkgLfCJzC+x7ZmU6douKzLW7rUYPifbZFc6ToIJ+MKFPdaSeE08ZQQ36hWC6y/6Dn/O1Bn/vuttmWfxsXjeSUe3ixVXG+yEv38L5X8+v4k2Zxujvzb39qoDlKKV8h01kK/mpjg2pCBFt3OrMZSFlQ/7dTrJnSqjSGz2HmkmmftUCzXuVS3XV4dFeao5qMSx/UbyiBhXRgiqXBlzVP2fMkgzUw6rqR+gPmQdUo3BEHZ/RBmQ27f7tadjBEo3CJb0IdJkIlyyxu+E/ZRI8qTWWk8Q114hskXH7hEgEnJ8ftpnENU+9T9QGFiuUlLlVcI0BlmWjusPgHZl2FHC0abq+EptNH6akmD7na6r4nvNvMhZwL1NAvtPMxLj5WPYds9/jVR8/H/Var46Ya12YuULYvy4Lb/cDe9+BCxV68BB/+AmxnQU0=)

**Comment by KaelWD** [comment]
Related: https://github.com/vuetifyjs/vuetify/pull/12605#issuecomment-726745170

**Comment by henrythc** [comment]
it is solved. thanks for the community!!

i should put the below code under the onBeforeUpdate hook, so change this
` if (props.dataItem) {  
    inputFieldsValue.value = { ...props.dataItem }
 }`

to 
`
  onBeforeUpdate(()=>{
if (props.dataItem) {  
    inputFieldsValue.value = { ...props.dataItem }
 }
  })
`
