### ISSUE TITLE
[Bug Report][3.3.1] v-overlay override icon  slot defined by prop of v-button

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#17437]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
when using overlay inside button it overrides the icon default slot and needs to be added again

### Expected Behavior
default slot defined by prop should be not overridden when using overlay

### Actual Behavior
icon slot defined by prop become hidden when using v-overlay

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9U81uGjEQfpWpL7QSu6s2PSGC0lvfIIc4B7MewK3XtuzZTRHi3TveHwqkB6JIuYDnx9/PrOfpIH6EUHYtioVYEjbBKsKVdADLrlAh9Mc+aJRxY9THhH+o2Bi0GrjoNdp7KZq0lQKqqW9qn/75YlgBPO7QQZuM24LvMFq1hxdDO1i3RN6BShBUREegajKdIh+BdjiVTc0/2iRWhyoCKKfBIWogD2sEpTWfGUPjRrWWIFlPJ93V5OhSVVesaUDOJrQpttFoKf71Dk2T2pMu7h6ksmvra0XGuyJR5MN2z0UGdFgTXmJJkpThahX1ijDRshqDM76cG/muxzkUWfF/53zqusUV9+T6aqpm4D7xQc6/vdf6G+xe3szR6U3nYHjty+psCzhMdTSBHxFSm8umCT4SHCDiBo6wib6BGa/PLDczcyLgHYD7XP88+4nWenj00epPsy8ZfIBjIDEXAxaLCOWv5B1v4CFrkWMhSbGAPpNzzJFjKXZEIS2qqtaOr/HamS6WDqlyoakeuK2KrSPTYKF983BX3pXfK94WOk+XmJpiHf1LwsggUszPaMhs9jdQjZ09w9eBYUwVVq1TpngFXTEff9eC343GiPFWR1fXzl1dlV45y+xH6Y48b2vc73Q16jr1Y36aRL7Lcg+WkZ4z4XEuep3M3F8Qz38Bo/u6+w==)

**Comment by lioneaglesolutions** [comment]
I think this is going to be a tricky one to solve as the icon has to render in the slot - but so does the overlay. 

As far as the button is concerned, I believe it would see no difference between an overlay in the default slot and text;
```html
<v-btn icon="mdi-grid">
   Test
</v-btn>
```
In this scenario, only the text will be rendered (no icon - same as your overlay example) - but do we also want the icon rendered? Probably not. 

```html
<v-btn icon="mdi-grid">
    <v-could-be-overlay-or-something-else />
</v-btn>
```

I'm not sure if VBtn is going to be able to reason about what's in the default slot (is it an overlay or just another `span` element) and if it should also show the icon @johnleider am I missing something?
