### ISSUE TITLE
[Bug Report][3.3.1] Webpack error: Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by lephro** [vuetifyjs/vuetify#17436]
Webpack-Vuetify projects are currently (3.3.1) not compiling and throwing an error 
`Module not found: Error: Default condition should be last one Did you mean './vuetify'?"`

This can be easily fixed by reordering the default condition (see link below) to be the last one.
https://github.com/vuetifyjs/vuetify/blob/1793cbb8b9c3d5e1cc18399731bb22f084c3893d/packages/vuetify/package.json#L57

**Comment by bkilinc** [comment]
This breaks our builds. Currently this is the latest release in npmjs. It would be great to have a quick release  with this fix.
