### ISSUE TITLE
[Bug Report][3.3.0] Iconify type mismatch errors

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#17433]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to run the attached repo and find the icon.ts file there you can find the eslint errors

### Expected Behavior
The type should be correct

### Actual Behavior
Here is the type error: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'DefineComponent<IconProps, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, VNodeProps & AllowedComponentProps & ComponentCustomProps, Readonly<...>, {}>' is not assignable to parameter of type 'DefineComponent<IconProps, {}, {}, ComputedOptions, MethodOptions, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., {}>'.
      Type 'DefineComponent<IconProps, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, VNodeProps & AllowedComponentProps & ComponentCustomProps, Readonly<...>, {}>' is not assignable to type 'ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: { readonly id?: string | undefined; style?: unknown; readonly onLoad?: IconifyIconOnLoad | undefined; ... 20 more ...; class?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends...'.
        Type '{ $: import("/Users/aloksoni/Projects/clevision/iconify-issue/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: { readonly id?: string | undefined; ... 22 more ...; class?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T ...' is not assignable to type '{ $: import("/Users/aloksoni/Projects/clevision/iconify-issue/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: { readonly id?: string | undefined; ... 22 more ...; class?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T ...'. Two different types with this name exist, but they are unrelated.
          Type '{ $: ComponentInternalInstance; $data: {}; $props: { readonly id?: string | undefined; style?: unknown; readonly onLoad?: IconifyIconOnLoad | undefined; ... 20 more ...; class?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_...' is not assignable to type 'ExtractComputedReturns<ComputedOptions>'.
            Index signature for type 'string' is missing in type '{ $: ComponentInternalInstance; $data: {}; $props: { readonly id?: string | undefined; style?: unknown; readonly onLoad?: IconifyIconOnLoad | undefined; ... 20 more ...; class?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_...'.ts(2769)
runtime-core.d.ts(1490, 25): The last overload is declared here.

### Reproduction Link
[https://github.com/alokVishu/vuetify-iconify-type-issue](https://github.com/alokVishu/vuetify-iconify-type-issue)

![image](https://github.com/vuetifyjs/vuetify/assets/80033712/e625a7f9-f832-47cb-a214-d06e6a8b718f)

**Comment by KaelWD** [comment]
`h` is from vue, `Icon` is from iconify. This has nothing to do with us.
