### ISSUE TITLE
v-select default v-model not show up correctly when item get from async

### ISSUE THREAD

**Issue by guanxudong** [vuetifyjs/vuetify#1743]
### Steps to reproduce
get v-select items from async/await
### Versions

v0.15.7
### What is expected ?

v-select will show up the default value
### What is actually happening ?

the default value not display correctly
### Reproduction Link

https://codepen.io/guanxudong/pen/dVoZYB?editors=1010

**Comment by jacekkarczmarczyk** [comment]
This issue looks similar to #1738 which is likely to be closed for not following the rules, so I'll paste here the my test proposal for anyone who is willing to fix it

```js
it('should not set the value that is not in the items list', async () => {
    const wrapper = mount(VSelect, {
      propsData: {
        value: 'invalid',
        items: ['valid']
      }
    })

    await wrapper.vm.$nextTick()
    expect(wrapper.vm.inputValue == null).toBe(true)

    expect('Application is missing <v-app> component.').toHaveBeenTipped()
  })

  it('should not set the value that is not in the items list (return object)', async () => {
    const wrapper = mount(VSelect, {
      propsData: {
        value: 'invalid',
        returnObject: true,
        itemText: 'text',
        itemValue: 'value',
        items: [{text: '', value: 'valid'}]
      }
    })

    await wrapper.vm.$nextTick()
    expect(wrapper.vm.inputValue == null).toBe(true)

    expect('Application is missing <v-app> component.').toHaveBeenTipped()
  })```

**Comment by bobbylight** [comment]
@jacekkarczmarczyk:  Sorry, what's the expected "fix" here?  Should we initialize our `items` array with a single entry for the initial value?  At first glance this seems to work, but I wasn't sure if there was a better approach.

What I think I really want is an editable, combo-box style behavior (whatever the user types isn't validated against the dropdown choice list), but I also want the dropdown to be asynchronous, and also have the appearance of a `v-select` (setting `editable` to true results in a much different style for the component).

**Comment by caliny97** [comment]
@jacekkarczmarczyk , I also have the same question, why this bugs has been closed????
Hit a wall with this. Building an enterprise app, a reply would be greatly appreciated. This issue is not fixed.

**Comment by johnleider** [comment]
Please do not post on old closed issues. Please create a new issue at https://issues.vuetifyjs.com
