### ISSUE TITLE
[Bug Report][3.3.0] v-autocomplete slot "selection" shows [object Object] when focused

### ISSUE THREAD

**Issue by haugero** [vuetifyjs/vuetify#17434]
### Environment
**Vuetify Version:** 3.3.0
**Last working version:** 3.2.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Select "one" from list => selection text is [object Object]
3. Click outside of the v-autocomplete => the selection text is correct

### Expected Behavior
The selection text is "-one-"

### Actual Behavior
The selection text is "[object Object]" if the component has focus and on blur it shows the correct text

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstugzAQ/BXLl14w7uuE0qr9jjgHAlvVrbEte6GqEP/etUlSSnKIVLiwr5nZWbYjf/W+HHrgFd8gdN7UCM/KMrYZRO19/sxBV2t7iOZij65xNAAIrNI0G58U34627qBiN87CTcGG2vQU3U0FOxbwy/0W7qed4iwA9sEKt/+ABolD4fyeBLFBROMwsxDJyHxwPhYsxWxS/KTr9yGFRkcUqeW8yghxr21LYBlK8Us9FWo0QD0JpMySy7TFpe7njVwwngnayD/mHpLr/SIYckA7e3FJMY4rIdMkLgAnJcvrHG9I6dMRc08+7x8ACmMTtEcW6SZzeU7QJy+47rwLSDC+/IjO0k8zJjRyKBfIx4rlTMrRX5Vixd8RfaykbFpLYy0YPYTSAkrrO/lCbTL0FnUHonXdy0P5UD7KlqxcpkuIndgH9xUhEIjixYIG9dv3FVSHzsxwOzMcUsLU+5gozqAl8Q0QRADbQoBw7UarseVWq9LZZol9UnYiv422n3FldROzzdujyH+tnMES0i4RTgXPOok5D/DdDyZ9Vio=)

### Other comments
If I add the prop "item-title="name" to the v-autocomplete the selection text is "one" if focused and changes to the correct text "-one-" onBlur

**Comment by KaelWD** [comment]
> The selection text is "-one-"

It doesn't use the slot contents for that, they are usually more complex than just some text

> If I add the prop "item-title="name"

Correct, then you wouldn't need that item slot either.

**Comment by haugero** [comment]
In my real project the slot content is indeed more complex than just some text. And there I have the same problem and cannot use the selection slot since the latest Vuetify versions.

I just made a simple example as showcase.

So you mean this issue will not be fixed and I will have to work around?

**Comment by KaelWD** [comment]
It is intentional that it won't work without item-title if the title key on the item isn't `title`

> and cannot use the selection slot

You probably also want `item.raw` not `item.value`

**Comment by haugero** [comment]
I will use v-select instead of v-autocomplete as with that component the slot "selection" works as expected.
