### ISSUE TITLE
Button active prop applies no styling

### ISSUE THREAD

**Issue by njabah** [vuetifyjs/vuetify#1744]
### Steps to reproduce
Add active prop to button
### Versions

Vue 2.4.3, Vuetify 0.15
### What is expected ?

That the active prop would style the button as active
### What is actually happening ?
Nothing. no styles gets applied

### Reproduction Link

https://codepen.io/anon/pen/qPdpKr

**Comment by KaelWD** [comment]
Is this supposed to be a feature request? `v-btn` has never had an active prop as far as I'm aware; `.btn--active` is for buttons that are also router links.

**Comment by jacekkarczmarczyk** [comment]
@KaelWD From docs: "Apples the .btn--active class", but `active` prop was not defined in VBtn.vue

**Comment by johnleider** [comment]
https://codepen.io/anon/pen/JrdmXr

If you need to manually show a button is active, you must use the ```input-value``` prop.
