### ISSUE TITLE
[Bug Report][3.3.1] navigation drawer appear when we navigate between pages.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#17442]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Clone the repo and try to run. Navigate to two routes and see a navigation drawer appear while the route transitions.

### Expected Behavior
The navigation drawer should not appear.

### Actual Behavior
The navigation drawer appears when you use the route with transitions.

### Reproduction Link
[https://github.com/alokVishu/vuetify-navigation-issue](https://github.com/alokVishu/vuetify-navigation-issue)

### Other comments
If you don't want to clone then here is the live demo of the same repo: https://lucky-kangaroo-e41445.netlify.app/

> **Note**
> This is a minimal reproducible example as per your [response](https://github.com/vuetifyjs/vuetify/issues/15747#issuecomment-1559784444). It uses Vuetify & Vue Router only.

Due to this issue, we are unable to provide other nice & subtle route transitions in Materio admin (https://store.vuetifyjs.com/collections/frontpage/products/materio-vuetify-vuejs-admin-template).

In the repo, I have the following:
- [About page/view that has navigation drawer on the right side](https://github.com/alokVishu/vuetify-navigation-issue/blob/65c70c9cad3bfd79ec9fdd688657e7a63fe93978/src/views/AboutView.vue#L13-L24)
- [Router View that is wrapped in `v-slide-x-reverse-transition` transition](https://github.com/alokVishu/vuetify-navigation-issue/blob/65c70c9cad3bfd79ec9fdd688657e7a63fe93978/src/App.vue#L31-L33)

![228147099-f2220ced-1405-40e3-9bd8-e10cc8c7d813](https://github.com/vuetifyjs/vuetify/assets/80033712/5d37c904-a5ac-403e-9f63-9c65d3c2bc5a)

**Comment by webdevnerdstuff** [comment]
At a first glance looking at your source code, you have the `v-nagivation-drawer` in the wrong place (AboutView.vue). It should be in `App.vue` as part of the layout, not inside a page and the routing. When it's in the AboutView file you are probably losing the `drawer` state on route change so it would not function properly.

**Comment by alokVishu** [comment]
Hello @webdevnerdstuff,

This is not a global navigation drawer. It is the particular page-specific drawer. If it is page specific then it should be on a particular page.

Please refer below image:
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/59342428-8051-46c1-b08b-ed8daa84f8df)

**Comment by webdevnerdstuff** [comment]
@alokVishu ah, I see what you mean. It looks like it's an overflow issue, that is why it's flashing. Maybe that's a bug? I'd have to defer to the Vuetify team on that, but if you change in your App.vue to this (adding v-responsive), the issue goes away.

```html
<RouterView v-slot="{ Component }">
  <v-responsive>
    <v-slide-x-reverse-transition hide-on-leave>
      <Component :is="Component" />
    </v-slide-x-reverse-transition>
  </v-responsive>
</RouterView>
```
