### ISSUE TITLE
[Bug Report][3.3.0] v-data-table item.columns contains only fields listed in headers

### ISSUE THREAD

**Issue by arekusu04** [vuetifyjs/vuetify#17443]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.0
**Browsers:** Chrome 93.0.4577.99
**OS:** Linux x86_64

### Steps to reproduce
`ìtem.columns.objects`show nothing, objects is only in `item.raw`
Is it intended behaviour? Should `ìtem.raw` be used for `item.<id>`-slot?

### Expected Behavior
item.columns.objects show value

### Actual Behavior
Value was not shown

### Reproduction Link
[https://codepen.io/arekusu04/pen/yLxLmpg](https://codepen.io/arekusu04/pen/yLxLmpg)

**Comment by KaelWD** [comment]
`Object.keys(item.columns)` contains both keys from the headers array, but modifiedObject doesn't exist in the objects so isn't shown in JSON.
