### ISSUE TITLE
[Feature Request] Normalize name for v-col props

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#17441]
### Problem to solve
Most attributes, if responsive, have a prefix of the attribute. Such as:

- offset => offset-sm, offset-md, ... 
- order=> order-sm, order-md, ...
- align-content => align-content-sm, align-content-md

But the cols prop of v-col is so weak.

### Proposed solution
```
v-col
cols => cols
sm => cols-sm
md => cols-sm
lg => cols-lg
xl => cols-xl
xxl => cols-xxl
```

**Comment by KaelWD** [comment]
- It's been like this since 2019
- It does kinda make sense because it applies to every size
