### ISSUE TITLE
[Bug Report][3.3.1] Scroll position of V-SELECT

### ISSUE THREAD

**Issue by ardito-kazuhisa-matsui** [vuetifyjs/vuetify#17445]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add ":menu-props="auto""

### Expected Behavior
When the select box is opened, the scroll position within the box becomes the position of the selected value.

### Actual Behavior
The scroll position is at the top

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUruO2zAQ/BWGDRPAEhFcKsMXXLr8QQrLhSSuZNp8gaScBIb/Pbu0lBN8zQGnZrQPzuwOub/yHyHUlwn4lu8y2GDaDN8bx9juUrUhlN8S2Fa7OSpxhj+5GjQYxbDoFZjnhts0NpzJdV8CA31eEkm70UBltIMltbXgpipEHxIytFP2Df9f0zgTpfeibVuxYaLrOoK+7wmUUgQAQDAMA8E4jgTH41FsFqLlE1prKp5OJ4Lz+UxgjCGw1orDq/iyxk6utqfg7stOrvzCMPVRh8wS5InK2gYfM7uyCAO7sSF6ywQaLai59y5lhm6xZ6p/Fj/BGM9++WjUJ/GFyO90SMQ3/M6FQ4T6lLzDu7rSLM1cSA3fspKhHGpQ3PBjziFtpeyVw2N4QfoSawdZumDlC7bJOLmsLVTK25en+qn+JpVOeZ2uIdmqi/53gogkDZ8dLTJZD3/fITV3FoWvd4U5VZm2SyTxhlqi3gViFcEpiBDfu9HDsfVWD6U3m5H6rXE39Buf5zk9WN2nYvN+GfJDKxcyYjqQ4G3Dy5yoXA7wwz+NPidL)

**Comment by KaelWD** [comment]
This is not currently implemented: #13489
