### ISSUE TITLE
change color of links in dark mode

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1745]
### Steps to reproduce
Create app in dark mode and put some text with links

### Versions
0.15.7

### What is expected ?
Link should be clearly visible

### What is actually happening ?
Contract between the link and the background is too low

### Reproduction Link
https://codepen.io/anon/pen/RLPMEG
![image](https://user-images.githubusercontent.com/15625235/30484087-8cf5a012-9a29-11e7-9177-58ecf2b520aa.png)

This can be marked as a duplicate of https://github.com/vuetifyjs/vuetify/issues/1599 (if the default primary color is going to be changed to more contrasting with dark background) or fixed by explicit setting the link color for dark mode in src/stylus/elements/_global.styl:
```
a
  color: $theme.primary
```

**Comment by johnleider** [comment]
Maybe we could use the accent color for links in dark? Open to suggestions.

**Comment by bretonio** [comment]
The same goes for the icons that accompany `v-list-tile-title`  in a template generated with `vue init vuetifyjs/nuxt` and the name of the project.  Highlighted items appear dark blue.

The code is `vue init` boilerplate.

```
    <v-navigation-drawer
      :mini-variant.sync="miniVariant"
      :clipped="clipped"
      v-model="drawer"
      fixed
      app
    >
      <v-list>
        <v-list-tile
          router
          :to="item.to"
          :key="i"
          v-for="(item, i) in items"
          exact
        >
          <v-list-tile-action>
            <v-icon v-html="item.icon"></v-icon>
          </v-list-tile-action>
          <v-list-tile-content>
            <v-list-tile-title v-text="item.title"></v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-navigation-drawer>

```
The stylus structure is anchored by `assets/styl/app.styl`

I have tried overriding the hover and selected styles for `<list-tile>` in `assets/style/app.styl` and its partials but no success. 

I would prefer setting the link color to white &mdash; or a very pale grey &mdash; and dispensing with the `active` decoration altogether. For now.

Thank you for your kiind attention.

**Comment by timothymiller** [comment]
This causes any website in dark mode to lose points in Lighthouse. Has this seen any attention?

**Comment by Pblfer** [comment]
a.primary--text {
    color: #e5e9ec !important;
    caret-color: #f4f4f4 !important;
}
