### ISSUE TITLE
[Bug Report][3.3.1] v-data-table-virtual Empty space appears when vertically scrolling

### ISSUE THREAD

**Issue by ConnorJohnMacaskill** [vuetifyjs/vuetify#17450]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Reproduction link:

1. Scroll down.
2. Note the empty gaps that appear at the bottom of the table.
![Screenshot showing a gap caused by scrolling down.](https://i.imgur.com/trMb4RY.png)
3. Continuing to scroll will fill in those gaps, but they will continue to appear and reappear the more  the table is scrolled.
![Screenshot showing the gap gone after scrolling some more.](https://imgur.com/y3PWblC.png)

### Expected Behavior
Rows should render to fill the entire height of the table regardless of scroll position.

### Actual Behavior
Rows sometimes don't render towards the bottom of the table when scrolling down, resulting in gaps.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqllttu2zgQhl+F0LaIDUQnn5IITtAi3UO3e7G3i9hAaWlicyNRAkm5dQ2/e4cy5UqyWMRobkJzZjjf/CTFedo774vC25bgRM5cQVakVMHDghMy37oJVdRVdJWCu2VClTTVBkKiDdAEhLxfOGa0cIyF4Rp63vh/AClBqJM9TqnUZkhhSxXLuRvWpg2w9UahbRYE9Zxezd3StASc5zSDo+Fh7vfBIfbcb9SAP2UsWKGqeuBrkQtFEnimZarI/phBrxKRwZDcP5CBmdMsVVUReapnSB1w/FNMpRCRK1MfGYRBsCY43DK+Hl5dN31pytYcfaWiQrVNEol0BRF5pqmElu0Fdhiki27GHBrj/Qnjkaa5YCCvrk/ZgCf467hIXJst4X9QrEBj90Y/U2ULfKRiJX8SGmu7LfhfkStg/CfhxdHDtsBHkWP0W1s0Q3MzdHkaJeZU2vdXy66FEfk34OS/fF12t67WNCLh9K5lQb0iMvOCjjsqEZHRpDVrCozIpOOu2TF/aN36HtiPMZBYAM2IpDz5wuKNjXg0vjknvusn7rg2iMe/TPw7fg6YsFLORueUoU3YNs0Js+tuMG8uwXwsi5i+tK5hk3McTM85x15bN4M5u0zN20sw/8RPD4gVngC8AxbU6ez1kk7ax/rEOvbahnrnZ5fA/g1puiMroNzKetMja9CPeme5Vl13gxpcQvpPnqasyAsr513PMQ289mTNeWvh7KMcXUL5V85hF+fZyoY5Cdq5zSntxby1nNKZ194SAzqZXkL6Ieel9Vs6mfaIOZr27/o0tF2m3gM6ukjQT0x9wofPwjkNe9QcWS7SrK3aibOtsqG03KL68ToMzQD3uigVJNEP+k7PpbuaRmUCVCk4efI8770QdKdbliAYevhYysFw6WW0GDDdBrXUiHMuddN0bHPu8fXFeLVh0qsf0SdG3pIwWJJDM85YPa0mhn1+s2/OHMhvb/bs8Fn3aD9iDKFxbKgwrMe1Hsf/mHDumw7PuXZYphs8F+vw/pc5x4a2qmRhDNiDnrTC/rTEXjLCwUapQka+HyccwxJI2VZ4HJTPi8x/h26+KLliGbhJnr0be2Nv4idMqua0BzJzVyL/gty4yMIxmFUaxZ53r0hlPKsM4TGDmXJTupI6xdnSvm44QbgC2x4QIF5bUSesWVXHdFaZ0f2AeqeMv8iO1LGsZDZt1S+WXC2mV1rqhIdrp+LEzFWAs/wO9/twtA==)

### Other comments
This appears to be more prevalent when the table is taller than 400px, it doesn't appear to happen when scrolling up.

Looking at DevTools shows that multiple chunks are rendered offscreen above the visible table area, suggesting it might be some kind of offset issue?

**Comment by ConnorJohnMacaskill** [comment]
Since submitting this issue I have found another scrolling bug, if you add the "return-object" prop to the table then the gap becomes even larger until eventually the table starts scrolling rapidly without user input.

**Comment by OkaSroka** [comment]
This is not going to work good :D because the way of rendering is wrong in my opinion
Check the AC grid or Rv grid

they are changing only data inside - not rerender the whole tr tags
that is why it will never work smoothly in case of many columns
I have still this issue that is above - in case of many columns
