### ISSUE TITLE
[Bug Report][2.6.12] VMenu is not mounting properly when SSR

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#17458]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.7.13
**Browsers:** Chrome 113.0.0.0

### Steps to reproduce
1. Use a v-menu
2. Render it server side
3. Open the rendered page

### Expected Behavior
No hydration error

### Actual Behavior
`"[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."`

### Reproduction Link
[https://codepen.io/Tofandel/pen/VwERKLL](https://codepen.io/Tofandel/pen/VwERKLL)

### Other comments
Worth noting that it also causes other issues because of a vue bug in the full rehydration when there is a mismatch error like mounting 3 times the components, this creates other issues with the `v-app-toolbar` giving 3 times it's height in padding to the `v-main` and other similar issues with components relying on `this._uid`

Previously reported https://github.com/vuetifyjs/vuetify/issues/804

The `eager` prop does not influence the error

**Comment by KaelWD** [comment]
> Render it server side

Are you using vue-server-renderer or some fake ssr like prerender-spa-plugin?

**Comment by Tofandel** [comment]
Using `puppeteer` so basically it's like prerender-spa-plugin or just pasting the output of the page back into itself

The preprendered markup is the same as in the codepen, does `vue-server-renderer` produce a different markup?

**Comment by Tofandel** [comment]
I see, indeed the activator is supposed to be inside the `v-menu` before hydration, instead of outside

I tried using `vue-server-renderer` which produces the correct output

Thanks for pointing me to the `detachable` mixin I made a quick workaround by preventing `$nextTick` from ever firing in the prerenderer
