### ISSUE TITLE
[Bug Report][3.3.1] v-color-picker has problem when modelValue is null or undefined

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#17459]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Nope

### Expected Behavior
v-color-picker can handle undefined and null in right errorless way.

### Actual Behavior
erros:
null:
Vuetify: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
undefined:
Vuetify: TypeError: Invalid color: undefined

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVMtu6jAQ/ZWR76KtlAeUdhMFxP2Opos8JiXFcSzb5FKh/PsdO4FEIFT62ABz7POYsc3Lgf2VMmh3yCIWG6wlTw2uEgEQt37eCJNWApUDHKSaf0Mx7ODHCoAKvUzY/DFhI1gXBD2NyInt+JkRkPNUW1794dM+yHiTb2Gd8yrfEkqijYIliB3nCVvZrzh0xO8q3f0py9msLO9IboP7X1I76aU/FDyAiuDx+dmDtwhmHmRDlUYwh4481Fv2c49NBIsZqWtS9YCTUzD12Gj+2x6t+5w4tBcOtib69Qs2GBd+yXEP7zttqvLDz1EYVNeumMvjSwqHClq/bgrkx5iUY/A8bbk9zNdvu94gmhEZG5KpneS4MqERUSpcHQ7WkAbbdXFogYkwBXXKV6Lb6vhs+5XxVcfh5M3HOleV7GVwLxtloMAy3XEDh16qSA0d4P0DLFdwP2BuEg3dWfs0vR7rHtyPzhoMosxjvBJbHbzrRtCfjWPTMWidsAheel7CNsZIHYVhXgjaSUdVtSoQaEIh65D+puyBrxfBIpiHRaXNEfJ5munAiVml10R0ZFjVtgm/TuWZa7/gnIcuEkZKtv4kwpq2hWonTFWjXzS1y/LUZ5nAAeraz2jqGhWJJGwYjLOxgW+w+qxbsriQDsmvReUrFAUq+yhu6+iMNu3qbOmis+GgO9Z5zNFo8C4ye/0PBnfvUg==)

**Comment by KaelWD** [comment]
42f7cbd4e568bca7bd9076b8f869b3deb412facc
