### ISSUE TITLE
[Bug Report][3.3.1] Defaults for sub component VMenu

### ISSUE THREAD

**Issue by praburangki** [vuetifyjs/vuetify#17465]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.1
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set the `bg-color` prop for `VList` nested within `VMenu` in the createVuetify defaults object.

```
    VMenu: {
      VList: {
        bgColor: 'success'
      }
  	},
```

### Expected Behavior
The `VList` should reflect the `bg-color`.

### Actual Behavior
The `VList` did not reflect the props.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VMFuozAQ/ZWRL2mkANrtDaVVq1632suql5KDA5PGjTHINmwixL/v2JgUkl21l40Uwfg9v3kzePzasbZBK3an+N2wlImyrrSFDnKN3OLLgEEPO12VsAjcRaYyhUdPzStlLAQA7uYbb7pMAdg9lpiSaIE73kj7a4gXUrzt7QL6lSO5f8ANcV0I8PKMqjlHFP8Qxk5igO3bUyUrTWqmyXM0hrwNSO9VrVMflpIEXn62qCU/TSTc6pUqLf5bmMCg7d68eYr7ZabYij3WdUzNoFauLZa1pF7cO8a6EC3kkhtzl7Ei2kk8wntjXJMiU/McI66rRhUZ83Ta0EYlFR8iikc5aCMjK5vy3IqW20qTYAe1rmpDPsbtQWJrQ/HDL3clEb/WouT6lLEpSGyhCo+S1hSbaAI8jnnB2ZhkS3y6D8PJrAHBkKRWzy26lUgQd+5l543eOGAF5AuPS3qAi2feANIDnojqORdIy2WDf8NmFU1NRFZYifdd5zPFPoK+d8Vdcualn9FJA2bluvD8RdcJnQd6mzVpbXIt6oEfpitMxHg2C255CjdLuLuHYbbcz/ckhdcPQx14i3R4n6TID/CM45j9Lxy+Txmb8NYvx/FYJ6E4mhEp1MHQfVMpGhNfRcZyQ1/1XEPG9tbWJk2SvFDELFCKVscKbaLqMgm3zcNtfBt/o04aOy5Fkm9N7MWc0obmkhIOt1pU8voi6wD4zKGbmbsPXfyJhQeiJbpRVpQYFVU59TJZjtGU0VZXvw1qEslYaIxP4wx/IdVn1VKKK+mE8tFVF2mkk69Rf7Wii23TnBfQVWXjPcj6FfPbqPHDc/MHDfD9vA==)

**Comment by praburangki** [comment]
I believe this is causing the issue `(VMenu/VMenu.tsx)`

```
default: (...args) => (
              <VDefaultsProvider root>
                { slots.default?.(...args) }
              </VDefaultsProvider>
            ),
            ```

If we remove the `root` will it breaks other components?

**Comment by KaelWD** [comment]
Yes: #16615
