### ISSUE TITLE
[Bug Report][3.3.1] v-text-field return a string number with type="number"

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#17460]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. default value is 0;
2. use v-text-field to increase the value. The value is changed to a string number

### Expected Behavior
component should return number, not a string number

### Actual Behavior
return string number

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs1O4zAQfhXLp12piVmxh1U2VPAcmEMaT6jBf7KngSrKuzN2QDLlAJV6yDcz319yv/C7ENr5BLzjPYINZkDYS8cY6+cG4RWbSYNRBXn/zY31CsyN5GrAQfJ6dtQKGgU4aJNqPGn3aKAx2kENK3BJ45moRm/DMOJnNjwHoJk72QPEz6OEZ5NnL1rhsWP/rsJrvbDvRW2/JFqWzOcnlm2vK5OuF1Vkekxj1AFZAjwFZgb3SAKYJM/n2gYfkS0RppVN0VsmOfW2idJ/9C5hob5htNNvpve/rn7/z0Ib9Z7vOHXwnNqn5B11vpRrPiZS6dj9FkDyI2JInRCjcrRJZes5tg5QuGAFqaKezrfX7XX7Ryid8ANqzHBIbSHLTA/SrSS4OW/sEC5Ut0FRLkjGSqTuOwu3tCbiyaG29Lq9LV7+bl4quIVkm0P0LwkikUi+q2Sy4R9IfZeWJL5QC9KbITYRnIKYP52fJbo4q1NdjL4ky+pr7nvd8XJGxRfL/OENtEUdLw==)

**Comment by KaelWD** [comment]
`<input type="number">` do be like that.

**Comment by velly** [comment]
OK, it returns numbers in 3.0.0-beta14;
 
If it was done on purpose, I will do some parse in method.

thanks！
