### ISSUE TITLE
[Feature Request] Need a solution to overwrite the vuetify 2 default sass variables when using vite

### ISSUE THREAD

**Issue by dang0705** [vuetifyjs/vuetify#17479]
### Problem to solve
There is no way to handle this question now, vite-vuetify-plugin only support vuetify3

### Proposed solution
vite-vuetify-plugin could support vuetify2 or other ways

**Comment by KaelWD** [comment]
https://vitejs.dev/config/shared-options.html#css-preprocessoroptions

There are currently no plans for a vuetify 2 plugin for vite.
