### ISSUE TITLE
[Feature Request] Is there have any solution to overwrite the vuetify 2 default sass variables when using vite

### ISSUE THREAD

**Issue by dang0705** [vuetifyjs/vuetify#17478]
### Problem to solve
Overwrite the sass variables in vuetify2 when using vite

### Proposed solution
Overwrite the sass variables in vuetify2 when using vite

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
