### ISSUE TITLE
[Bug Report][3.3.1] Text Field Error shown when cleared

### ISSUE THREAD

**Issue by rohrii** [vuetifyjs/vuetify#17489]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows

### Steps to reproduce
- Create a text field with the following attributes: clearable, validate-on="input", at least one rule that will fail when no character is written, element ref, @click:clear="refTextField.reset()"
- Enter some text
- A: Delete the text manually and click outside
- B: Click the clear icon and click outside

The Error message should now be shown

### Expected Behavior
The Error message and styling is gone and validation doesnt happen when input is empty or cleared. The validation should only be applied when typing something (see the validate-on="input") and not when clicked outside and the input is empty.

### Actual Behavior
The Error message is shown after deleting the whole input and can only be resetted with a page refresh. 
Even if a click listener is appended to the clear button which calls the function reset() on the input field.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUz1v2zAQ/SssFyWAJbZIJ8F23aXo1KlIByuDLJ1i1vwCSakpHP33HCnZZpwlQCab9+7u3b132h7p0IPn3f/ir6Ml5dJo68mRNBZqD/cTRkbSWS1JNudmlaoUPMXURivnyQyQ1evCm2OlCPF7kFBi0xa6uhf+9/TO2toeMjIuKjXeVoou6HdjCuyEcyw9SCOw0To0WA55bUz8Gx/I6WuuwM6hGPTw5POOg2hPQUIaAbWtdwIuoaEWvMXGuVarinJlel/RC1zaXoBDJP6myJBL3YJASLrHFLDQYTDQ/4jsCbRpBG8OZRwjzSksOPD30yhcq5vbSxU77cmuFw2RSYclS/TBp2ssN55gz36S6ewjDpe6F51DXaJp53HQNszDIRIw7o/AFgXrgazWQbkevhUC1KPfkzX5TJ6fSfZLo/thkU/ZQ1qPIs1ts58ghCZ/tBWYhCRLNs2Lk6Lp06i5rA2eoFZofjwa9CYC6AGeziRJFY41vCu69964krGmVViGvvDBFgo8U0ayDaYx2yvPJeStlpu74q74ylrufBouwMl8Z/U/BxabVBQv8UwTzvcdVHNmZPgyMcyhXNQ7FyjetGbIN4DNLagWLNj3bnRVlm51Bb3ZLLCP+J2h3oKrg7uSunFR5u1pyA+tHJuFTngPIx0XNM6JzLGAPrwAgW17SA==)

**Comment by lioneaglesolutions** [comment]
Not even sure if the input validation method is working... I might not understand when it should validate exactly but even simply blurring the input in this example triggers validation;

https://play.vuetifyjs.com/#eNqlU01z2jAQ/StbXQwz2G4nPTFA6aXHnjq54ByEvYCKvkaSnXQI/70r2YBDLpnJCbRv9+3u2+fNiXUtBrH7V/z1bM6EssYFOEHtkAd87DE4w84ZBdmQm1W60viSUmujfYABgOXbwsmp0gDhgArnRNrgjrcy/OnfWcPdMYPzrNLnaaXZjP20tiAmmmMRUFlJRKtIsOhybm36mx7UM3Ch0Q2hFAz4EvKdQNlcggC1RO74VuIt1HEpGiLOjV5WTGjbhord4LlrJXpC0u8Y6XJlGpQEKb8fAw53FIztf6XuI2hdS1Ef52mMcU7h0GN47EcRRk+mt6rysmd5v2iM9DosypE+9PS1EzYAcba9TNc70nAzeOahPoyPmA5I8qTbXaei61E6zTICkwwEbEi3FmG5igK2+KOQqPfhACv4Cq+vkP02ZIK4z5fsaVxPWg20WTYQp2kmBMxgMo2MySR9gZFYSLOfZPWB6z02sQYg2mNR9kvSeuSUfr9ccUu+NZock0jooAmgw5HfetoqOjy+K3YIwfp5WdaNpjI6puhcoTGU2qpyTWmla3UQCvPGqPVD8VB8LxvhwzhcoFf51plnj45IKkb2vbaJnv9AqyEzdfjWdxhCueRbH1u8oy6pX4cud6gbdOg+utFd2XirO+jdZkl6+jhJbyn00d9JXfsk8+Yy5KdWTmSRidxzZucZS3NS51TAnv4DBIyLYQ==

It seems validation on input also validates when focussed then unfocussed? @KaelWD  can you confirm what should be happening here?

https://github.com/vuetifyjs/vuetify/blob/3640ab25e227d23b744c01a2e34b85931d11ade3/packages/vuetify/src/composables/validation.ts#L145-L157

**Comment by KaelWD** [comment]
Yes that's correct: https://vuetifyjs.com/en/components/forms/#validation-state

I don't think this is a bug, your rule explicitly doesn't allow an empty input. How it got to be empty shouldn't matter.

**Comment by rohrii** [comment]
@KaelWD This problem was not about the rules itself, but about the clearing or resetting functionality. I thought it should be implementable to completely reset the validation and error state when clicking the clear button. So that it basically thr initial state again where nothing was entered yet.

**Comment by lioneaglesolutions** [comment]
@rohrii the clearing of the validation is working - it's just that on blur, it's validating again hence you see the errors

**Comment by KaelWD** [comment]
It does
https://github.com/vuetifyjs/vuetify/blob/47ac84c1e0ecf0db324e350b357b3bf8c9ccd330/packages/vuetify/src/composables/validation.ts#L169-L172
It also focuses the input though, so anything other than `validate-on="submit"` will cause it to show an error when blurred.

**Comment by rohrii** [comment]
@KaelWD okay that clarifies it for me, thank you. However, it would be cool to have a function which completely resets the text field. So i have to manually add a rule for the empty value.
