### ISSUE TITLE
[Documentation] v-row property "align-content-xxl" missing description

### ISSUE THREAD

**Issue by ConnorGDevelopment** [vuetifyjs/vuetify#17480]
### Environment

**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
Navigate to Page

### Expected Behavior
Description says:
"Changes the **justify-content** property on extra extra large and greater breakpoints"

### Actual Behavior
Description says:
"MISSING DESCRIPTION"

### Reproduction Link
[https://vuetifyjs.com/en/api/v-row/#props-justify-xxl](https://vuetifyjs.com/en/api/v-row/#props-justify-xxl)

### Other comments
If there is no longer an "xxl" breakpoint, then this section should be removed instead of the text updated.

**Comment by MajesticPotatoe** [comment]
duplicate #13573
