### ISSUE TITLE
[enhancement] close dialogs in mobile

### ISSUE THREAD

**Issue by afuentes90** [vuetifyjs/vuetify#1748]
This is a proposal for the behaviour of the dialogs when you are using the browser from a mobile phone. I think that if the user clicks the button to go back and a modal dialog is opened it should close and the action of going to the previous page should be prevented.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
