### ISSUE TITLE
[Bug Report][3.3.1] VDataTable customFilter cannot access item.raw

### ISSUE THREAD

**Issue by ctrueblood-epri** [vuetifyjs/vuetify#17487]
### Environment
**Vuetify Version:** 3.3.1
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Use the reproduction link with Vuetify 3.3.1 and enter `vanilla` in the "Flavor search" input field. Notice there is nothing found. Then, set Vuetify to 3.2.5 and enter `vanilla`. Notice there are 2 items found. The flavor search uses a custom filter that searches a hidden "flavors" item property, which is accessed using `item.raw` within the filter function.

### Expected Behavior
Custom filter should be able to access `item.raw`.

### Actual Behavior
Custom filter throws an error in the console: "cannot read properties of undefined" (because `item.raw` is undefined).

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVm1v0zAQ/ismErSVmoRuA0S0TiBg0j7BV7Tug5tcVzPHDvYl25j63zk7SZu0y17ypc69Ps+dc9fLh+BrUURVCUESnCLkheQIZwvF2GkVZhx5iHwpwQkYS9LSos7DlZAIZr4I6sMiaNRr4BkYS4rmtNUICu3kGVgLBncKC9yka9LUh1aeSm6dPUioOAqtwlmrcqHCissSSK94DrXCYybULQdWhVZqTFAXjcpTQrhDwg8ya4WMLHOdgTwA4R7Jl15zLnmlDTs0aJEWPDzZyc9O426uFlzcrzDZ7EpMop7+1KZGFOgt4a7QBlkGK15KZA91OOebsPGEzc/YuJGxBmLCRqNpK0q51EaA7QnbViTscsdmG8U9rrjkcm70P1Dst74uDe78+4FnHz73NCuOCfsYvd8zN0uyPTrpSQujEYRK2MmeuTCapKPZ237SlW+FI2PR8NslGHM/Zelap9qVrmu86Zwfo3aRAksN8JxZrrJbka6H+B0dfzrk9/lxfnumHX7Hr+NXcSWk5K9h9IPuozCDLD4eHbKYDbWpj3ZLY9+8ofHpORrP9uiqOW0mzSHVeVEiZMmOajNY6NJ32BvA0qjuPabiMBQoXUm+1xd9NGVcimsH1SL37zdwT2+ucqNeYbve35riddxBZVvntrbDAc45svH1ZMCfOvBUbmrEE86+UcPuv+qOPRGg6elwiAvqLRu/HfJ3re87X7XHVtj+5oBrndF12PatXh5jP8qn7G8J7jN20/2x3o67+LwLezNnqpSSvXvX1fk4Azq8L0CvGvf5fO4niFDXoz07ByKi0RI1dzgSKoO7n6uxDz6h6HNGC2nrMXmc9MZN9O0UD6aBFOrGRn+sVrRtPcdFkFpahtsZTJsTsbBJHKeZIktaS6IykQKMVZHHtKdRrO6/HEfH0SzOhMVWFNKispEP5iJRGzaUUORub4Q5L/ay1gqfuan1IqBI7v0ZCF/ILDalQpFDmOncYzmpsXTEEdg8XBp9S58eBVkETWV8Ggf4BameY0spDkLHlK8CExq6pmDcf5OXMdpz67LaUx0wa1q9CTbTwLtR4T3k4Oo/XEq4oA==)

### Other comments
The line below was changed from 3.2.5 to 3.3.0. As of 3.3.0, only `item.columns` are accessible within custom filters in VDataTable. In v3.2.5 and earlier, `item.raw` was also accessible, allowing us to implement custom filters that access hidden item properties.

https://github.com/vuetifyjs/vuetify/blob/9d4b9d1b76b095db8637761c2f2595d9472ccb29/packages/vuetify/src/labs/VDataTable/VDataTable.tsx#L120

Can "item.raw" accessibility be restored in custom filters in VDataTable? Thank you for considering this issue.

**Comment by nekosaur** [comment]
This was one thing I was afraid of when doing the change for 3.3.0. So yes I think we need to solve this somehow.

But at the same time, to me it feels quite strange to filter on data that is not visible in the table. There is a disconnect between the input and output..

**Comment by ctrueblood-epri** [comment]
@nekosaur, good point about the apparent disconnect between input and output. One use case is a custom filter that searches expandable rows within a table. The custom filter would need access to the expanded-row data, which may include fields in `item.raw`. Reference: https://vuetifyjs.com/en/components/data-tables/basics/#expandable-rows

```html
    <template v-slot:expanded-row="{ columns, item }">
      <tr>
        <td :colspan="columns.length">
          More info about {{ item.raw.name }}
        </td>
      </tr>
    </template>
```

**Comment by KaelWD** [comment]
Sorting should have access to the full item too: #16654

**Comment by bobrov-site** [comment]
I have same issue. @KaelWD can you provide approximate time when team fix this? For my project this is core problem for now.

**Comment by bobrov-site** [comment]
> This was one thing I was afraid of when doing the change for 3.3.0. So yes I think we need to solve this somehow.
> 
> But at the same time, to me it feels quite strange to filter on data that is not visible in the table. There is a disconnect between the input and output..

@nekosaur  nothing strange in this. We have project where our table more difficult then just show data from headers. For now, I don't have access to custom filter for table item, this is very bad. I don't know who makes this decision, but table now is not flexible for works with data in filter.

**Comment by cadriel** [comment]
We've just hit this too. Seems like its broken all of our `customFilters` because we relied on the raw object being passed through.

**Comment by ctrueblood-epri** [comment]
Here's an alternative method for custom filtering: implement the filter outside of `<v-data-table>` and then assign the filtered items to the table's `items` prop. Example:

[Custom filter desserts using hidden field](https://play.vuetifyjs.com/#eNqlVW1P2zAQ/iu3SKitVCcrZSAyYEzbkPi0fZ0oEm5ypR6OE9lugKH+950Tp01TyovWL7Xv5bl77i7nq6fga1GE5QKDODixmBWSWzybKICTkll8sGwmUKZQsixPUZ5OAoNcJ/NJAJJPK8GF5GWuYSVPJDeG5AVnB3SNarQPjIGgAAa4RrhJ0RjU1lwIaVFjejMEoYxFnkI+W6tvgLEmm5RbziyfSnQCgHhO1qhdKH+aBF5TBSJ5N0pj0KSIEktuRa7YqFE5V1ZyuUDSK55hrXAsTqJWgU5MokVhq+Twoci1hRRnfCEtPNVILt8Y+gM4PYO+l4EvUwy93rARNVnGcNWIoAGpfy4PcrnQ+V9U8Du/XWi79q8YcZlrgYQx+nS8oZlxG8Nh+LFjrqdku3+wIS10blGoGA465kLnJO2N9jaDzqrOE07PWM3vp6j14xCSeZ7krkpt42Xr/By1ywQh0cgzMFyl9yKZ7+K3Pz7a5nf8PL+OaYvf+H38Sq6ElPw9jH7QkAm9k8Xh/jaL0a42bWa7otE19zSOXqPxao+u/Wk58Ickz4qFxTReU/XfHM13i71Gu9CqPcdUHLDCSleS7/Wg94bApbh1qRrLq/sdPtLNVa63Udi29zdfvJY7qnTl3NR2N8AFt9C/Hezwpw68FJsa8YJz1ajd7r/qjr0A4Hu6G+KSegv9vV3+rvWbztfNcS2MIpj5TbhaOp9hUdCmQtrL6tGKjHaznQsT1nvqhiaFq1s03V3VbNRn298CaJP5UisaiLDOpZ+6BZmGfkpDoVJ8+Dnrt0AG8OH0FNho0EaLN9G6bOv/pdvaq00dDAORuVXNMl6Ef0yu6NWr0p94BT0hqxGfBPQsuju9L9YWJo6iJFXkRu+gKHWo0EaqyKJzMov0QrnisTTPzsfhODyIUmFsWxyiydhU5/eULoFMAp9oFcaK2eMbQnnLKsK4juBFjF5j40JsQUcUr0TNNI0LdUy/lVHHrc2qo9pi5iu/pHpLoe5Mp9SJqcrsl8R/Uq7AHBLN+zJYDoMqT4pcOQTX/wBH46GP) - implements a computed property (`dessertsFiltered`) that updates anytime `this.search` changes. `dessertsFiltered` are assigned as items of `v-data-table` instead of the "raw" `desserts` array.

**Comment by rti-Austin** [comment]
Filtering on the entire row item (raw) is broken for me also. I understand the usability and performance benefit of filtering on just visible columns, but most of my clients prefer to filter on the entire item.

Perhaps the <v-data-table> component could take an option to filter on the entire object or only the visible columns (i.e. 'filterVisibleOnly')? I added the custom functionality in one of my projects and I think would be a good improvement for the DataTables.

For example: 
`<v-data-table :filterVisibleOnly="false"></v-data-table>`

Either way, my customers really need the whole (raw) item in the filter. Thanks!

**Comment by nekosaur** [comment]
Right now I'm toying with the idea to expose the transform function as a prop, something like `filterTransform`. So for v-data-table the default value of it would be `item => item.columns` but if you need to access raw object you can pass `item => item.raw` instead.

**Comment by mustafaekim** [comment]
hi, how can we know if there a planned progress on this? We are upgrading our app from 1.5 to 3.x and custom-filtering using the raw item is all around our app hence missing that breaks our app.

**Comment by KaelWD** [comment]
I legit just pushed some changes for this like 5 minutes before you poste.

**Comment by mustafaekim** [comment]
How can I learn more about the recent update? The filter function seem to have the same signature

`(value: string, query: string, item?: any) => FilterMatch;`

**Comment by johnleider** [comment]
> How can I learn more about the recent update? The filter function seem to have the same signature

I believe this was resolved with @KaelWD's latest commits https://github.com/vuetifyjs/vuetify/pull/17832/commits

**Comment by Shujee** [comment]
I just upgraded to `3.4.8` and all of a sudden my `v-data-table-server` has started complaining about my custom column templates. Specifically I'm getting `TypeError: Cannot read properties of undefined (reading 'name')` for all occurrances of `item.raw.X`. Changing it to `item.X` gets rid of the error and the data table starts showing like before, but VSCode then keeps yelling about missing member (`Property 'name' does not exist on type 'DataTableItem<any>'`).
