### ISSUE TITLE
v-tab pagination doesn't work on mobile

### ISSUE THREAD

**Issue by sztankatt** [vuetifyjs/vuetify#1749]
### Steps to reproduce
Open a mobile browser and go to: https://vuetifyjs.com/components/tabs

The pagination controls will not appear
### Versions
Using Google Chrome and Safari.

Vuejs: 0.15

### What is expected ?
The pagination controls should appear

### What is actually happening ?
The tab is just overflown

### Reproduction Link
https://vuetifyjs.com/components/tabs

**Comment by nekosaur** [comment]
On mobile the tabs are scrollable using touch.

**Comment by johnleider** [comment]
That is correct, pagination controls for mobile have no need to show the arrows because its touch and can scroll with finger.

**Comment by sztankatt** [comment]
ah, ok. sorry for this, then.

**Comment by johnleider** [comment]
No problem :)

**Comment by BonnieDoug** [comment]
I don't agree with the outcome of this.

Even if the bar is scrollable with touch, it's not clear that this is the case. Without explaining to the end user that they can scroll the tabs, how will they know it's got more item options? Example:

![image](https://user-images.githubusercontent.com/4302775/34048102-533d83a8-e1aa-11e7-8eb2-ffeb5a96dc2b.png)

A chevron, even if unfunctional in itself, showing there are more items would definitely be a user experience boost I'm sure.

**Comment by johnleider** [comment]
Already tracking https://github.com/vuetifyjs/vuetify/issues/2530

**Comment by KaelWD** [comment]
Yep, scrollable tabs are supposed to look like this:
![image](https://user-images.githubusercontent.com/16421948/34048315-58c93cec-e207-11e7-8ca6-6536bc21ca0e.png)
