### ISSUE TITLE
[Bug Report][3.3.2] v-autocomplete & v-select forgets previous scroll location after being unfocused

### ISSUE THREAD

**Issue by m2xilon** [vuetifyjs/vuetify#17491]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 2.6.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Make a vuetify autocomplete or select with more items than the vertical height of the dropdown can show. 
2. Click on the autocomplete/select and scroll down to some arbitrary point in the dropdown.
3. Click away from the autocomplete/select.
4. Click back onto the autocomplete/select.
The autocomplete and select dropdown will show the top of the list regardless of prior scroll.

### Expected Behavior
v-autocomplete and v-select dropdown opens on last scrolled to point

### Actual Behavior
v-autocomplete and v-select dropdown opens showing top of the list on refocus regardless of prior scroll

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrlU8Fu2zAM/RVNF29AbAPrTkFatCjQDcMGDNvQHuocFJlJtMiiQMnZiiD/PkpOUC+5FNixN/KReo98ph938sb7atuDnMpZhM5bFeGqcULMtqXyPoc50eiiMg7oAGUwgAUdj4AQVi3AXjbyx4DL58rUMHvg0mNxq6xZIjmjiokobtEiqRZTfMehaTP8EZBWQ8dP+KNCCh6esDNulcLPSm+URQ8p+YoENgX3QCaqANR3Kf2mKIAeOnoLbgF6M1B+MXFtDk0EHl0LpJzObHdIGsQ9z4+UB1zzVMjGhJjS79D2Ohp0xfx5v6tZfTRjbI/qI2pkUyHCuUk34+rrsmpszPHEGP73xnJjPsFZPTpNToMm46MIEPvhQk3nkaLYCYKl2IslYScKvuoiFZk1RNGFlbhM9bfFJ7AWxQOSbd8U7xL9QMhUciIHrrJTvvoV0PGPsUsszaEQGjkVGUkYa6S8kesYfZjWtW4dP2vBmi1VDmLtfFdfc1tNvYumg7LF7vqiuqg+1K0JcQxXELpyQfibPwuTNHIykolm+fQCqUNnVng/KBygku8uJIkz6pr1tkAlQfq4QC/d6OTZeKuT0tlmSX3fuD37bY3bhBOrdcg2Px6H/K+VM1limifB/UTmOVk5P5Dzv1n5o8s=)

### Other comments
In vuetify 2.x this did not happen (see codepen: https://codepen.io/tim2x/pen/LYgozeR), both kept track of the last place it was scrolled to on refocus.
Is this going to be readded in vuetify 3? Will this functionality be dropped? You decide!
Epic Bug Battles of Vuetifyyyyyy

**Comment by lioneaglesolutions** [comment]
Believe this has to do with the way that VSelect options are rendered for performance improvements they are removed from the DOM when not focus. Just add the `eager` prop to ensure they stay loaded. and scroll position is kept - @johnleider please confirm

**Comment by m2xilon** [comment]
Thank you @lioneaglesolutions! Works as intended with eager prop.
