### ISSUE TITLE
[Bug Report][3.3.0] Failed to resolve component: v-bottom-sheet

### ISSUE THREAD

**Issue by opringle** [vuetifyjs/vuetify#17499]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. clone repo
2. npm run dev
3. go to url & open chrome devtools

### Expected Behavior
a button shows. when clicked a bottom sheet opens

### Actual Behavior
the bottom sheet card shows with no button. devtools throws error: 'Failed to resolve component: v-bottom-sheet'

### Reproduction Link
[https://github.com/opringle/vue_mwe](https://github.com/opringle/vue_mwe)

**Comment by lioneaglesolutions** [comment]
VBottomSheet is still in labs. Please review https://vuetifyjs.com/en/labs/introduction/ for how to import labs components. You are not importing the labs components at https://github.com/opringle/vue_mwe/blob/main/src/main.js

**Comment by zed-wong** [comment]
> VBottomSheet is still in labs. Please review https://vuetifyjs.com/en/labs/introduction/ for how to import labs components. You are not importing the labs components at https://github.com/opringle/vue_mwe/blob/main/src/main.js

It's better to mention this in the doc of the VBottomSheet page. It took me a while to find here
