### ISSUE TITLE
[Bug Report][2.5.5] Unable to detect overlay click on v-navigation-drawer with stateless prop

### ISSUE THREAD

**Issue by Dimas-e63s** [vuetifyjs/vuetify#17503]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Is there any solution to detect overlay click when using `v-navigation-drawer` together with `stateless` and `temporary` props, except for using `v-outside-click`?

1. Click on the button "Open Drawer"
2. Click on the overlay of the drawer

### Expected Behavior
To close the `v-navigation-drawer`(used with prop `stateless`) when its open with a click on overlay.

### Actual Behavior
When clicking on the overlay of the `v-navigation-drawer` (used with prop `stateless`) it doesn't close.

### Reproduction Link
[https://codepen.io/Dimi_0-o/pen/GRYbrKQ](https://codepen.io/Dimi_0-o/pen/GRYbrKQ)

**Comment by webdevnerdstuff** [comment]
I believe that's the intended functionality of `stateless` as clicking on the overlay I would assume is part of the automated state functionality.

**Comment by KaelWD** [comment]
It already uses v-click-outside internally if stateless isn't set.
