### ISSUE TITLE
[Feature Request] VBreadcrumbs item icon

### ISSUE THREAD

**Issue by Sulyci** [vuetifyjs/vuetify#17504]
### Problem to solve
It would be nice if we could add an icon to each breadcrumb item with or without the title. Some clients and users would be happy to see some icons. The icon should be clickable as well as the title.

### Proposed solution
I would propose a familiar solution the VBreadcrumb has. It would be nice if we could pass an icon as a prop or place it into a slot.

**Comment by foxbecoding** [comment]
Hey I've coded an example on how this can workout.  Maybe it can help you out.  [](https://play.vuetifyjs.com/#eNqlUstOwzAQ/JWVORSkJpaAUwQIvoP0kCYb1RA/ZG+CUJV/Z+0mVR9IFLjksTs7Mzv261a8OJcPPYpCPBBq11WET6UBeBiytceqqX2v1wEKxd3wWIr0LkXCMGqegSELnaWCFHXIsC1EIIx7ZGJUtTVMxc+JKY/fpQA588ljE/LIBdeOAPwbaq8cQUDqXRpR2llPsAWPLYzQeqthwQsuIhyA5QIlbwEeI+b6dae8nW02KlTrDpsC2qoLuJzr0WkBC92obGM1LvaNDbNw42qujNP7N4xskFT7+SdS8v23nMq01uuKlDU/8a5uYrK7LDlFsRS7GDNdufwtWMPXIynzqaUG34Bi9lIKdh//S7EhcqGQsm4MjzXYqcHnBkkap+Uzw6TvDSmNWWP1811+l99LXoQOyzkGzYduPwJ6JinF5DTJxJAukJqQSeF2pzCVsq5ahyhxRi1Zb0CfeTQNevSXbnQydrjVSetss6g+lmbkvDtl3sNJ1HVIMU8X9J8rJ7J01lFwXIrkk5XTgFh9AXg3Tns=)

**Comment by Sulyci** [comment]
@foxbecoding Hello there! Thanks! I will definitely check it out!

**Comment by foxbecoding** [comment]
@Sulyci no problem!
