### ISSUE TITLE
[Bug Report][3.3.2] Manual validation on VTextField uses the previous model value instead of the current one

### ISSUE THREAD

**Issue by const39** [vuetifyjs/vuetify#17501]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Create a `VTextField` (wrapped in a `VForm`) with at least one validation rule and a listener for the `update:modelValue` event
- Bind the text field to a template ref
- Trigger the text field validation manually in the `update:modelValue` event handler, by calling the `validate()` exposed function

In the repro playground, type a character in the text field and open the browser's dev console to see the debug logs.

### Expected Behavior
The manual validation should attempt to validate the text field using its current v-model value.

### Actual Behavior
The manual validation uses the previous v-model value.

As you can see in the repro playground's console, validation is triggered twice: 
- the first is the one that is triggered manually (the problematic one)
- the second is the one that is triggered automatically on input (this one works fine)

The manual validation fails because it used `undefined` as value instead of the actual input character. If you type more characters in the text field, each validation uses the previous v-model value instead of the new one.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01P20AQ/SuTVSWDFNtS6clKKEgFqVLVAy1cMBKLPYFt12t3P0xRyH/v7K5NnHCJVB8sz3uzM/Pejm/X7Lzrst4hK9jCYtNJbvG0VACLPuVdFz5DULXKcqFQD1AAV61u3uKAWPxr05VAWW9hAI2rZckizKZEnzZtjZLIxjzuUoV2Eg0xt+Ej0/jHCY313W7ametqmrkIdW64dEhHWnUd0Glqvh0835nch7vqPBLFL/KJKRSaSovOgkHrojei6VptYe0lzuGZ2+oJNrDSbQMJ2Zr4HCpuLJBAWPq0o+MtGCwZYOWkJGpLBt1EruOcowEF9LA8HdGY3ErMZPt4tJV7P6aHMpBCz6UgT4R6hJJ9WPebks2hclqjsp50GHAaMwsR8ffzbb0eZsulFxFZ+AxJegpfvl5eXlxdfP8JN+ffri9+zBIoIAmq/ROUxtmt0wpmsx5eXyG5GmcL+of0Tei2iQ5w86IqWDlVWdEqGC/0iJofj9Knwu/HDFLK9SCRy0NEDkNOLoTWKFhFjZfAn7kY8HjGvz2N8SJ350hosapR2JvnVEijcdIm8/0OoQaJXuRxt2ir2JzFtUob3mW/TKvo7wyay4EwJStGF0pGe+bjkj1Z25kiz6ta0TH6H0SvM4U2V12Tn1Farp2yosG0bpuzk+wk+5TXwtgpnKFp0gfdPhvUVIT8m7SxYvVyQKshM3T4GDsMUCr5g/Et3pXOqV+POqWbqlGjPlTR3rGpqj3qnbLB+Q35LYX6bfasrkyw+XYc8r8kh2K+0p1vuJmzMCd1DgfY3T9Dm8zg)

### Other comments
I couldn't find any reason as to why this would be an intended behaviour but I may be missing something. If so, I'd be glad to have some insight on this.

For context, I need to fetch data from an API based on the text field's input value only if this value passed validation. Because auto validation happens in the background, I cannot await on it. That's why I trigger validation manually.

**Comment by KaelWD** [comment]
The automatic trigger is from a watcher:
![Screenshot_20230601_001011](https://github.com/vuetifyjs/vuetify/assets/16421948/9e113c4e-cbca-4a12-aa42-155b55eba38b)
onUpdate is called before Vue updates the component props with the new value, so when you call validate yourself it still has the old value. if you `await nextTick()` before calling validate it should work as expected. You probably also want to set `validate-on="blur"` to prevent the duplicate call.
