### ISSUE TITLE
[Bug Report][3.3.2] No validation property on v-text-field component

### ISSUE THREAD

**Issue by NickdeK** [vuetifyjs/vuetify#17502]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a text-field with a ref and rules
2. Try and get a invalid property from the ref when the text-field is invalid

### Expected Behavior
A `valid` property that reflects that validation state of the text field.

### Actual Behavior
No `valid` property and similar data properties like `error`, `errorMessages` and `messages` are not reflecting the invalid state. Also `checkValidity()` resolves to true while the text-field is invalid.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVN1u2jAUfhXXqlSQSDzRXUWAmHZdadpFd0GQ6iYH4uE4me3QIsq779hJwKOlq9SrnN/vO3/OYk+/1XW8bYAmdGKhrCW3MEsVIZNtxOvai17JKmW5UKA7kzdaeLbRSoDMeyMhc6Hqxk5T6r/fC67WkNKTX8Oqd4bmRDcSDHoWXog1/GmEhnzUqlnVKAt6eUphfW3svDhnaWufsKAnVE2mRW19EDzXlbYkhxVvpCX7Fiznlg+GveaKtY1WJ50QK6yEhNz80CBFKRTXO4xyWDejUxSUXEiMCm2+kSTEcvhtlwnZctkAmc7I1VUrvryQm5+dOw5xCOmGcUoKnaS3TqekUdgfziV3aN4cS1BrW5AZGX/xFHdCOTEruOYZgpqQ6nCUD63QG0qwRZWH3QTbDgfoilWmkkhcrQcPoHWFdV/vbSFMfI23YGKfGXvP4WFIGCMrLg28h3AHxvC1m+YlpD6iQ1SNlBcAy/eweuf/YbICss09lyIXdvcm1j8Rg2EHaXUTtIqGX5Xe4MKeBG7pvgErVjsyvkCKKxV4O2+QeU9HcbyCkOe42G6j7RfXPGHHV0JHVJTutKOS1/FvUyn8TfjV4gP2DpPS4w2kFP8jTk9pYW1tEsayXGFaji9lq2MFlqm6ZHMMYxovWJQQ5VU5v41v468sF8aG5hhMGT3q6smARpCUdoV6GjeVD1B1kZ5h3DJ0pkjyR+MoXkEz5NuCjjTg2DToj3Z0lhZ2deZ61Vk3+QPOWwq1MWejzowf86Iv8lMtezCHtHSEhxH1dSKzT6DLv+h987g=)

### Other comments
In Vuetify 2 we had a `valid` property (not in the docs) that could be used for this.

**Comment by KaelWD** [comment]
Yeah `isValid` and `errorMessages` should be exposed at least. Checking those on input will not work though, rules are async now. 

> this.$refs.input.error

Is a prop

> this.$refs.input.checkValidity()

Is a method on the native input element, does not interact with vuetify's validation system

**Comment by jervalles** [comment]
Possible temporary solution is to use validate() but it returns errors messages if there are some.

`async function changeValue(key: keyof AccountOnboarding, value: any) {
  // TODO: https://github.com/vuetifyjs/vuetify/milestone/61  |  https://github.com/vuetifyjs/vuetify/issues/17502
  // Vueitfy should include .valid() in VTextFields on Vuetify 3.2.2
  const has_error = await test_email.value.validate()
  if (!has_error.length) {
    AccountService.patchAccountOnBoarding(account.value!.uid, {
      data: {
        [key]: value,
      },
    }).catch(() => {
      toast('Erreur lors de la modification', {
        type: 'error',
      })
    })
  }
}`

**Comment by Arinono** [comment]
Not really, it seems it's one keystroke away/late of being accurate 

[playground repro](https://play.vuetifyjs.com/#eNqlU01v2zAM/SusL06B2N7Q7RLERXYYsH+wQ9KDYtOJNlkSJNldkPq/j/pI4qWXAsvBsR4p8r1HenvOvmldjgNmq2ztsNeCOXzeSYD1WDCtw2s4NEo6xiWaBAXQ4R9XdBxFewEBDHb1LotgdoPHolctCgr19jAPbAbdUtNVCBcjEwNS0pHJVqCZJ67MINBSLPzfItWV0ZFZQGOUsSs4n9MrTFMSUd2r8EgUua5m4uloG8O1A4tuiB7wXivj4OzlwQSdUT3k5Fvu0wGornVAyqD2GYv8Bwqh4Kcyon3IH28pwZeUNIMT1Yh3TFikoA93g2wcVxKkkt977U6L8RHOURDvYOFOGlUHIzzUNeTWGS4POby9EVJ7JL9m+8m4wUjIGyalcrBHIM3uRBJ8NLmUkpwZ0AOE3lgG44nk9kLmJUaZPcnmRjXNbhFm+Q/boL4MeCA8yBY7Gkc7Y3k1hBqxV8aTZ/GWf3K/LtE8/4vWpaK1P5YC5cEd4Rk+zaTRY13FudJEs2UWR1r0TJe/rJL0BQQOuxSgDaMtigV2GY3an2kxndN2VVVNK+karSwfTSnRVVL31YbSKjNIx3ssWtVvnsqn8kvVcuvmcIm2L/ZGvVo0VGSXLWdtHO9OH2iVMkOHz19ji4QVgu2t7/GudkUNRzSFQTLe+M/rY5Lurs1l3YXeSUvWT2S44PK3vfO6scHn7YXk/2kO1XwpWswpm5ZZIEqt443s5S9RBp91)
