### ISSUE TITLE
[Bug Report][3.3.2] No way to achieve lazy binding for property with v-text-field

### ISSUE THREAD

**Issue by neptunecentury** [vuetifyjs/vuetify#17519]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Edge 113.0.1774.57
**OS:** Windows 10

### Steps to reproduce
add a v-text-field to your form and try to assign a value to it with :value and only update the property on change event.

### Expected Behavior
The property would only update when change event is fired

### Actual Behavior
When using v-model.lazy, the property is updated on each input. When using :value and change event, the user cannot type in the box as it continuously resets to original value. This behavior is not consistent with a regular input element.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtU01v2zAM/SucNiANEFvoulPgBtlt/2CHugfFZhKtsiRItNMsyH+fJCe1l+wjwHYTH8n3+Gj66cA+W5t3LbI5KwgbqwThotQARZcJa9MzBZXRJKRGd4ISSPhK2Vqiqs8gQJc1pkaVK/F9/1iyxm9KNmSVWKEKcOul3vxUC3e1Qa8nBDvjXqZDE/+b4rwTqsVrrWW1FXpzSsAjfMAONeUk3AYpT01/GC2mQegaehZIzbcM6a3QizOJlkoJkNq2BGls2Ena/pY9svppwSPHmXBRrNyYP5ENY9PeRotxMWM3/2kpnvYqFq+Mq9HN4d6+gjdK1vC+qqpf+q9l9xaEcHu/MC2FkQsenkPicAgDHI9vbXzoK/jlvUWkP8eCj840hL5y0hJ4pLa/VtlY4wgO4HANR1g708AkXPgklgMEXk/Qew8Vd5MvqJSBr8ap+t1kGgV6ykDGZqxnyxph82/e6PCbHCJLeUr4ks0hIRELKjEu2ZbI+jnnVa1DW7hw2blcI3FtG74MZdy1mmSDWW2a5UP+kH8K9j2N4Rx9k62c2Xl0gaRks5EMyfX+BqlTZVL42CucoCxcu48SV9Q86HXoMoc6fHF0tzq6aBu7ukhdOYvq4RCOYd9K6hd/serKpzU/nYf8J8uJLDI9R8HjjKU5g3JqYM8/ACljoAY=)

**Comment by KaelWD** [comment]
Use model-value

**Comment by neptunecentury** [comment]
I'm not sure I understand what you are referring to. You mean v-model? How does this achieve lazy binding? The issue is that using v-model causes the property to update on each keypress, the goal is to update only on change event. How can this be done currently? I can listen to change event with no problem, but setting the text value with :value causes problems as demonstrated in the repro.

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNqtU01v2zAM/SucNiANEFvoupPhBtlt/2CHugfFZhKtsiRItNMsyH+fJCeNl+wjwHYTH8n3+Gj6ac8+W5v3HbKClYStVYJwXmmAss+EtemZgtpoElKjO0IJJHylbCVRNScQoM9a06DKlfi+e6xY69cVO2eVWKIKcOelXv9UC3eNQa8nBFvjXqbnJv43xSKRZL1QHV4rLuqN0OtjAh7hA/aoKSfh1kh5avrDgDENQjcwsEBqvmVUb4Wen0i0VEqA1LYjSMPDVtLmt+yR1U9LHjlOhPNy6cb8iew8Nu1stBjXM3ZT/J+leNqpWLw0rkFXwL19BW+UbOB9Xde/9N/I/i0I4eZ+bjoKI5c8PM+J/T4McDi8tfFzX8kvry4iw1GWfHSsIfS1k5bAI3XDzcrWGkewB4crOMDKmRYm4c4nsRwg8HqCwXuouJt8QaUMfDVONe8m0ygwUAYyNmMDW9YKm3/zRoefZR9ZqmPCV6yAhEQsqMS4Yhsi6wvO60aHtnCisne5RuLatnwRyrjrNMkWs8a0i4f8If8U7Hsawzn6Nls6s/XoAknFZiMZkqvdDVLHyqTwcVA4Qlm4dh8lrqh50OvRZQ51+OLobnV00TZ2dZG6chbVwyEcwr6V1C/+YtW1T2t+Og35T5YTWWR6joKHGUtzBuXUwJ5/AD1xokQ=

**Comment by neptunecentury** [comment]
Ah, yes! This produces the results I was looking for. Thank you for clarifying. Replacing :value="myprop" with :model-value="myprop" and using @change="myprop = $event.target.value" fixed the issue for me.
