### ISSUE TITLE
[Documentation] Layout issues in Chinese: Documentation/Components/Buttons/Variant

### ISSUE THREAD

**Issue by williamsun1993** [vuetifyjs/vuetify#17516]
### Environment

**Browsers:** Edge 113.0.1774.50
**OS:** Mac OS 10.15.7

### Steps to reproduce
Documentation: Components/Buttons/Variant
Switch document language to Chinese.

### Expected Behavior
<img width="1028" alt="截屏2023-06-02 02 06 25" src="https://github.com/vuetifyjs/vuetify/assets/9425257/24a06ea7-ed6d-4260-aa64-8dff2051224c">

In English, the layout is correct.

### Actual Behavior
<img width="1106" alt="截屏2023-06-02 02 06 18" src="https://github.com/vuetifyjs/vuetify/assets/9425257/46e553af-c3c3-4d2d-baa0-4ff616b5568d">

In Chinese, there are layout abnormalities.

### Reproduction Link
[https://vuetifyjs.com/zh-Hans/components/buttons/#variantff0853d84f53ff09](https://vuetifyjs.com/zh-Hans/components/buttons/#variantff0853d84f53ff09)

**Comment by KaelWD** [comment]
Crowdin seems to be outputting `<table>` elements for tables with HTML in them instead of keeping the markdown syntax.

**Comment by KaelWD** [comment]
![Screenshot_2023-08-05-01-09-00-680_com google android gm-edit](https://github.com/vuetifyjs/vuetify/assets/16421948/42d6279b-741f-4439-b620-8af6fc5997f2)
