### ISSUE TITLE
[Feature Request] Add custom css class to table headers and table columns 

### ISSUE THREAD

**Issue by mahdihashemi88** [vuetifyjs/vuetify#17515]
### Problem to solve
Allow more customization on specific columns or headers only. like adding a background color to specific columns  or headers

### Proposed solution
adding a background color to specific columns  or headers

**Comment by scscgit** [comment]
Additional context:

In [Vuetify 2, DataTableHeader](https://v2.vuetifyjs.com/en/api/v-data-table/#props-headers) supported fields
* `class?: string | string[],`
* `cellClass?: string | string[],`

that no longer seem available in Vuetify 3 at
https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/labs/VDataTable/types.ts#L8
