### ISSUE TITLE
[Feature Request] Type VDataTable events and export the types for users

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#17517]
### Problem to solve
I am using VDataTableServer and triggering my update data requests using the `update:options` event. This event takes a parameter that is a "DataTableOptions" object, which contains options for servers that are required for sorting/pagination/etc.

I had to inspect the argument myself to determine its form. From there I had to define my own type for the parameter, which is likely to become out-of-sync with Vuetify.

### Proposed solution
1. Type the events

https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/labs/VDataTable/VDataTable.tsx#L97-L103

2. Export the types for users

Bonus: consider what other types should be exported, such as DataTableHeader/DataTableRow and export them as well

**Comment by scscgit** [comment]
Covered in:
* #17379
  * #16695
* #16680
  * #16897
