### ISSUE TITLE
[Bug Report][3.3.2] @update:model-value emitted before value change VSelect

### ISSUE THREAD

**Issue by MKutek00** [vuetifyjs/vuetify#17524]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
When event @update:model-value is placed before v-model inside attributes it will launch before the value of v-model is changed. The order of attributes seems to matter. For example <v-select :items="['one', 'two']" @update:model-value="test" v-model="item"></v-select> will have different behavior than :  <v-select :items="['one', 'two']"  v-model="item" @update:model-value="test"></v-select>

### Expected Behavior
Event will be emitted after the value has changed.

### Actual Behavior
Emits event before the value changed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUdtq4zAQ/ZVBLLiF2ILtPpm0ZF/2J+JAVXtMtWtdkMYOIfjfdyQnGzd9KeybNHN0btqfxU/vq2lEUYstofGDInxpLMB2KpX3+ZgvrbOktMVwGeVhxAFbug4Aas0c8bkR+8JZLDZQ0NEVh0bcILvRd6xRG9fhUE5qGJHxhJF+IbXva+hUZhCvE+1tc3MgP1p4SYOPRtNkybGVq3x8jW3QniAijUtMbbwLBGcI2MMMfXAGCq6mSHAA5o0EyQk8J8iDHYfhcdmpeLIt9KNtSTsL/9I8PMJ5saaOShP0efjajcac8vnbORFWuYb5ldkA5mR1Mce2xEYsvkqjfPU7Oss/lTm5lbyIjaivKo1gv+neiHciH2sp287yM65RT6GySNJ6I3cMk2G0pA2WnTO7p+qp+iE7HWk9rjCa8i24Y8TAJI3YrGRI96cvSF2QWeH7onAZlYN6i0niE7VkvQlDGdB2GDB8NdHds3Wqu9WnZJfmZ+570PZPvKu6jbnm/dXkf0XOZInpkATnjcg+WTk/EIe/2S4xBg==)

### Other comments
As you can see in Vuetify Playground. If the event is placed before v-model it will emit before the value is changed, so the value of variable inside function started on event will be old one

**Comment by kakulukia** [comment]
I was just the victim of this "thats the way vue works" bug .. a note right be sides the event documentation would help a lot!
