### ISSUE TITLE
[Bug Report][3.3.1] CSS v-bind() not working on modal content

### ISSUE THREAD

**Issue by renaudMonell** [vuetifyjs/vuetify#17521]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Windows

### Steps to reproduce
Create a v-dialog with a tag inside it
Add a class to an internal tag to the modal
Create a dynamic property that will be bound to this class

### Expected Behavior
Style from ref should be applied

### Actual Behavior
No styling is applied

### Reproduction Link
[https://codesandbox.io/p/sandbox/vue-3-vuetify-3-pinia-2-forked-28h2ld?file=%2Fsrc%2FApp.vue%3A11%2C8](https://codesandbox.io/p/sandbox/vue-3-vuetify-3-pinia-2-forked-28h2ld?file=%2Fsrc%2FApp.vue%3A11%2C8)

### Other comments
Is this due to dynamic rendering of VDialog that is done at the root of the application?

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/7312
