### ISSUE TITLE
[Bug Report][3.3.2] :icon="..." does not work with @mdi/js 

### ISSUE THREAD

**Issue by nwtgck** [vuetifyjs/vuetify#17529]
Hi!

Thank you so much for the beautiful project!

### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Mac OS 10.15

### Steps to reproduce
`npm install @mdi/js -D` and use `<v-icon :icon="mdiAccount" />`
The instruction is here: https://vuetifyjs.com/en/features/icon-fonts/

My workaround is using a string array `[mdiAccount]` instead of `mdiAccount`.
The array works because: https://github.com/vuetifyjs/vuetify/blob/9437361d89d595f9c28e1d732b24c2b38bf7fa86/packages/vuetify/src/composables/icons.tsx#L221-L225

### Expected Behavior
Show icon

### Actual Behavior
Not show icon
<img width="433" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/10933561/05215b85-1dcd-4fe4-b6d3-027e161fdb7f">

### Reproduction Link
[https://codesandbox.io/s/nwtgck-vuetify3-mdi-js-icon-m0pl8t?file=/src/App.vue](https://codesandbox.io/s/nwtgck-vuetify3-mdi-js-icon-m0pl8t?file=/src/App.vue)

**Comment by websitevirtuoso** [comment]
you should use import  -to imprort this icon. It works  100%. try one more time

**Comment by KaelWD** [comment]
You're missing the createVuetify part from https://vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg

**Comment by nwtgck** [comment]
Thanks!
