### ISSUE TITLE
[Feature Request]  vuetify3 (VDataTable): Add select-bg prop to v-data-table

### ISSUE THREAD

**Issue by he-jialin** [vuetifyjs/vuetify#17530]
### Problem to solve
Change the default background color of the chekbox row

### Proposed solution
Add a new select-bg property to data tables and, when using the default slots, have it apply to the background color applied to the row

**Comment by KaelWD** [comment]
You can do this with `row-props`

**Comment by qxygene** [comment]
Can you please share and example with `row-props`
