### ISSUE TITLE
[Feature Request] Expose validate from v-select/v-autocomplete

### ISSUE THREAD

**Issue by Mohamadhassan98** [vuetifyjs/vuetify#17533]
### Problem to solve
I'm not sure if it's a bug or it's the desired behavior, but previously on vuetify 2 it was possible to validate single v-autocomplete/v-select via refs (`$refs.mySelect?.validate()`) and in the new vuetify it's not possible because the validate function is not exposed from mentioned components.

This was useful when rules of input depended on value of some other input so we wanted to validate some input when other input values changed.

### Proposed solution
Add and / or expose validate function from these (all input components if possible) components like previous version of vuetify.

**Comment by lioneaglesolutions** [comment]
This is already possible.

https://play.vuetifyjs.com/#eNq9U01v2zAM/SucLm6B2EbbW5BkGTbsJ+wS9+DYNKZVlgxJ9jCk+e+jKLdxnAL9OPRg2OIj+fie6N1BfOu6bOhRLMXKY9up0uOm0ACrIa1KW/N3PBntS6nRQqN6+QQwZM3f5+OYq4Aety7EzW0hJiDDZe9NZYgMPU4hgCFtTY2K6oZS9ViIc3gpacbQld9zVJV7Lv2BTdkrP4ctNgQ2ElV90df2CkNffp+jm1V+PvFUKkGkkyLvke9QYeU/W3hk/fkh+bH2ReGn82kLIjquy7M5pHzvNWwrJauHKFTWtG5k0K/xMxRSTlzA0CRu4CqfrObKVVZ2Hhz6vuNM2XbGejgEoXCExpoWEtrpJDLTJM4D3zusQ87V9Sk8ceUSZLMpvEsaY5IFJPvSJvcnnK9qLOOUSS1bGWoHWG9ggC/rNXAOPD5CIb6XOvGwR6BQVghqGkqbXldeGh06syFX13CI7vH8GTN+Da8RjuBExcspx2BiNI4sEwuhpH5w2R9nNP35TFGIytHdL2EXexbit/edW+Z5VWvKpO2Ug800+lx3bU7+etn8295ld9ltXkvnn0IpraPLuFnoRNKORBgvKW3LbsYaAWYepdJqhD9g+doIW0rLba+9bDGtTcuz3MRZJuEMXZvuaTsdWmpSiMWEJgz8BqrX1BLFReuc+Aa0qUVdo0X7VkWzsqmqGXShbLzqozguBJeR8TyyuP8PWaPW9w==
