### ISSUE TITLE
[Bug Report][3.3.2] VForm rules that return "false" are not considered broken rules

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#17548]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type "bad" in the input field

### Expected Behavior
It should flag the form as invalid.

### Actual Behavior
The form is still valid.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUrtu3DAQ/JU1GyXASQTiVIeT4XSp06Q4udAdVwltvkBSsg1B/+4lJdnyuTHgbh+zOzNLHkf2y7lq6JHt2SGidqqNeNMYgMNQts7lMCdna2IrDfqlBDC0SgqoYRyXcJrWFuE76zUMpbYCVd2wjGjY63DGRHyKZSdRiQ1Sh38Ng73vFYY5/ZNCqvHX6QOfCVZ5lL7Xlyqz/APf2KI0nL10EQLGfnYntbM+wggeO5ig81ZDQRcpEhyA9oYIpIKcEuJb8RuVsvDXeiWuiu9vkPUcCRR9j5vW6oG6R4L1CPVNwlNwVddQnFpR3CWpsziSxXZs1lXq1lX3wRp6oDFtbJYGHWQPuZJqpDflDfsfowt7zs/C0BhdVA6+Mhi5cZrfEoz73kSpsRRW315X19VPLmSI23KFQZcnbx8DelrSsN2GJsru+RNUCzIz/JgZllKp2lNIFB9Wc+Ib0JcejUCP/rOOLsa2ri5aH5wldvq1E91bSfMQLk59DvnMx1XklyznZWkTPfXEph3LOok5D7C7F8EfLfc=)

**Comment by foxbecoding** [comment]
You're missing the rule.  Try this for example and it should work:
`const msgRules = [value => value !== 'bad' || 'is bad']`

**Comment by ffxsam** [comment]
The official docs say that simply returning false is valid. I'm talking to the team to get some clarity on the intended behavior.

**Comment by foxbecoding** [comment]
> The official docs say that simply returning false is valid. 

Yea you're right I just seen it in the docs.
