### ISSUE TITLE
Pickers are working with disabled text field

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#1754]
### Versions
0.15.7

### What is expected ?
A disabled textfield with an integrated picker should not show the picker when clicked.

### What is actually happening ?
The prepend/append icon appears disabled (thx to #1343) but the date or time picker works regardless of the disabled state. 

### Reproduction Link
https://codepen.io/anon/pen/QqboOq

**Comment by jacekkarczmarczyk** [comment]
Picker is controlled by v-menu, so if you don't won't menu to be opened when you click the activator then you should disable v-menu

**Comment by SquareBeard** [comment]
That's what I thought too, and that works, there is just a small annoyance with the cursor being different than disabled fields cursor.
But how would you disable the dialog version of the pickers ?

**Comment by jacekkarczmarczyk** [comment]
Same as you disabled v-menu - add a `disabled` prop to a dialog
Regarding the cursor on disabled menu - I agree with you, I'll create patch that sets the default cursor instead of "not-allowed"

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/1755 - PR for cursor

**Comment by SquareBeard** [comment]
Thank you for the cursor and I did not realize you could disable a dialog.
