### ISSUE TITLE
[Bug Report][3.3.X][Types] Event-only components and ComponentCustomProps augmentation doesn't work properly since 3.3.0

### ISSUE THREAD

**Issue by ferferga** [vuetifyjs/vuetify#17545]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.37
**OS:** Windows 10

### Steps to reproduce
1. Clone the repro repository or start a Codespace from master
2. Run `npm remove vuetify && npm i vuetify@3.2.5 && npm ci && npm run typecheck` to install 3.2.5 (the latest working version) and run type-checking against it
3. You will only receive 6 type errors (related to #17082, but irrelevant for this issue)
4. Run `npm remove vuetify && npm i vuetify && npm ci && npm run typecheck` to reinstall and run type-checking against 3.3.2
5. You will receive 12 type errors. Those new 6 type errors are the ones this issue is reporting, you can ignore the ones received at step 3.

### Expected Behavior
* `v-btn`, `v-app-bar-nav-icon` and `v-avatar` doesn't report any type error when being used only with the `@click` prop. If you add any of the other valid props, the issue is gone
* Module augmentation at `frontend/src/types/global/attributes.d.ts` of `ComponentCustomProps` work for the `data-swiper-parallax` type error.

### Actual Behavior
* Using `v-btn`, `v-app-bar-nav-icon`, or `v-avatar` components with only an event prop (in this case `@click`) gives a type error.
* Module augmentation at `frontend/src/types/global/attributes.d.ts` of `ComponentCustomProps` doesn't work for the `data-swiper-parallax` type error. However, the types are correctly defined according to https://vuejs.org/api/utility-types.html#componentcustomprops and https://github.com/vuejs/language-tools/issues/1077#issuecomment-1145361472

### Reproduction Link
[https://github.com/jellyfin/jellyfin-vue](https://github.com/jellyfin/jellyfin-vue)

### Other comments
I'm attaching the whole repo as a reproduction since I believe it's going to simplify debugging in this case by having the whole TypeScript and bundler configuration in place.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/8376

**Comment by ferferga** [comment]
@KaelWD Great thanks! I believe then that the `@click` handler is also related to #16190?
In that case, feel free to mark it as duplicated from that one and closing this.

Sorry for all the hassle.
