### ISSUE TITLE
[Bug Report][3.3.2] Can't reduce font-size of inputs like v-select

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#17547]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 2
**Vue Version:** 3.3.4
**Browsers:** Opera, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Try to apply `font-size: 10px` to reduce the size of an input like `v-select` (together with its value).

### Expected Behavior
inline `style="font-size: 10px"`: worked correctly in Vuetify 2
* ![image](https://github.com/vuetifyjs/vuetify/assets/3118390/e8d193db-fc3e-4ca7-8cd2-da1042e17f35)

### Actual Behavior
inline `style="font-size: 10px"`: has no effect
* ![image](https://github.com/vuetifyjs/vuetify/assets/3118390/1d7e1e49-f30c-4da6-86f7-69eddf475ace)

`.v-select__selection-text { font-size: 10px; }` in `<style>`: reduces the size of text, but the input stays huge. In case of `variant="underlined"`, this means a space between the value and line under it.
* ![image](https://github.com/vuetifyjs/vuetify/assets/3118390/8f61c986-210a-43ec-9ddb-52b57cf14026)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1kt9ugyAYxV+FcNObAvt35dzSPUdpGqufGxuiAXTtGt99H1gTY7O02bIr43fgnN8B1kf60jS8a4EmNPVQNTrz8CwNIWnHPOw9KxXoIgwIqeoCNOsy3cKTpNkul3QQusyqzHgctqYAq5WBYtR0tgONivMHDaQ2+jAqcYJKWRvPnPqChNzeNPtBFiOEAw25/xeARGFjh9J6gV6L5aKAcrH5PV6uMxfsJmB/Im6dMq9kzNhuh6+qTbyZa1oEzFRM7jWNrSI8x9WE/+ROjoP7rP1jmPbBdDSiS4rwH46/u9rgK4r7JM2dkzQh68FF0jfvG5cIkRcGV+KhqM5yA16YphL4/rwqD6t7fs/vRKGcH0cMz8LxaBacNtL0GKiqpraeVVkzSx2EmHzilxSdwv8FhBUuE7Y1XlXAirqKLA8Dy2TMwVVsZ+tPBxZNJF1OYgLwFVGX2mLEmbXAvA4ssxBeC9hrG822TVvNpLNmp5vuab+kcRsefESmm2/GUGdz)

### Other comments
I wasn't able to find a workaround, causing a blocker during migration from Vuetify 2. The documentation is severely lacking.
* 📔 (It's also difficult to set a color on label; plus it's worth considering making it easier to style the `v-list-item` options.)

**Comment by foxbecoding** [comment]
I see what you're saying.  Maybe having a sass variable for font-size in v-select would probably be helpful.

**Comment by bscNinja** [comment]
@scscgit 

Temporary workaround:

```vue
<style>
.v-list-item-title {
  font-size: 10px;
}
</style>
```

**Comment by scscgit** [comment]
@bscNinja this doesn't change the font size of the input.

It only changes the size of the individual options for `v-select`, i.e. after clicking on the input (btw. it also has very large spaces):
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/cbac869a-dc23-4e0e-bf95-32186511301c)

**Comment by bscNinja** [comment]
Try setting the prop:menu for the SelectBox
The Box should be default:open on page load and you can inspect the styles in your Browser to find the relevant class

```vue
      <v-select
        menu
        hide-selected
        chips
        closable-chips
        multiple
      ></v-select>
```

**Comment by scscgit** [comment]
@bscNinja why? I said I want to change the size of the text in the input, not the options inside `menu`
