### ISSUE TITLE
[Bug Report][3.3.2] v-responsive no longer "in-lined" with Vuetify 3.3.x release

### ISSUE THREAD

**Issue by adamarbor** [vuetifyjs/vuetify#17540]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 3.2.5
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
In the reproduction link, you can see with v-responsive it is shifted to the right. Changing vuetify version to 3.2.5 and it has expected behavior.

### Expected Behavior
Component stretches across screen

### Actual Behavior
Component doesn't stretch across screen

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctuGzEM/BVWF7eAtQKangynSG/9gx6yOWx2ubYavSDSmwSG/z2U1kkWziVAbuKQM8Ohbo/qT0rNdEC1UVtGn1zH+LsNANtJdynVZy36GLizATP0riO6btVondN7tLs9Q+fsLmjiLnOrzqRKy0gpBrITvvEGPTp8AsYn1j0GxrygVFJtjRbdAJP2cUAnNE+7VoF5FzdL9ddFBXzbdM4hyBxkaxYBpaQ+28RAyIc5p/UpZoYjZBzhBGOOHlZym1UZBxBdYpA14LpMfF/9Reci/IvZDd9WP4rBLCliaq1mNe271PynGOTAx6LSnhvUqg1UpGDiUupW7ZkTbYzphyA0SW6n3ARkE5I3NzJm8iGw9aiH6G+umqvmlxks8RJukLy+z/GRMItIq9YLG7bj8yeszpPV4efscIa06+6pWHyQNuI3YZZfCQPm8q2fS3RBW6a6aH1IVtxPbTjJvZ0ND3Rx6p7qmW9fl/xS5CpWlO6K4Wmt6p7iXAnq7gW7RBvi)

### Other comments
Working version: https://play.vuetifyjs.com/#eNqlUctuGzEM/BVWF7eAtQKa9mI4RXrrH/SQzWGzy7XV6gWR3iQw/O+htE6ycC4BchOHnBkOdXtUv1NqpgOqjdoy+uQ6xl9tANhOukupPmvRx8CdDZihdx3RdatG65zeo93tGTpnd0ETd5lbdSZVWkZKMZCd8JU36NHhIzA+su4xMOYFpZJqa7ToBpi0jwM6oXnatQrMm7hZqr8sKuDrpnMOQeYgW7MIKCX12SYGQj7MOa1PMTMcIeMIJxhz9LCS26zKOIDoEoOsAddl4uvqDzoX4W/Mbviy+lYMZkkRU2s1q2nfpeYfxSAHPhaV9tygVm2gIgUTl1K3as+caGNMPwShSXI75SYgm5C8uZExkw+BrUc9RH9z1Vw1P8xgiZdwg+T1fY4PhFlEWrVe2LAdnz5gdZ4Uh+/Nz9nhDGnX3VOxeCdtxG/CLL8SBszlWz+W6IK2THXRepesuJ/acJJ7Oxv+08Wpe6pnvn1Z8lORq1hRuiuGp7Wqe4pzJai7Z736G+g=

**Comment by foxbecoding** [comment]
Hi, I've checked out both the Reproduction and Working version links.  Do you really need the d-flex class in the v-responsive component?  When I removed the d-flex class the component stretches across the screen as expected.

**Comment by KaelWD** [comment]
d-flex was redundant before too when it already had display:flex
