### ISSUE TITLE
[Bug Report][3.3.2] v-icon doesn't support deep children, not even <template>

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#17546]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 2
**Vue Version:** 3.3.4
**Browsers:** Opera, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce

Add an element under `v-icon`; for example a simple `<template>` before the icon name. Two examples:

```ts
<v-icon color="orange">
  <template v-if="true"> mdi-information-outline </template>
  <template v-else> mdi-information-outline </template>
</v-icon>
<v-icon color="green">
  <template> mdi-information-outline </template>
</v-icon>
```

### Expected Behavior
Red element is without `<template>`, orange with `v-if`, green with a simple `<template>`
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/126782d5-3bf7-46ab-80db-7fe4b7835647)

### Actual Behavior
`v-if` displays text instead of icon, `<template>` completely disappears
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/e4cc7dcd-5cad-4418-b279-d38175db762b)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUc1uwjAMfpUqZ5JI206IIfYchENpDMvWOJGTdpoQ7z6nFVKh00A7xt+vne1JvMWo+g7EUqwy+NjWGdYGq2rVS9cErJrQBno1gsAasa68ddLhIZCvswsoQ5dbh1Ct9Mhn7W/qQDUegQ0KyPAlqmLegfFMXUH/sL8qd+0AbYKHpZOi85pHAsB5y/+YXyFiIZj+mdRHCsinPhWyEU1KRiyr7RhnxHvOMS21biwy00LrelIIWWP0mj8pu8P35lk9qydtXcqXkWzrfVKDWXHaGTxzoPMxUJa+jjepIzAkD5MyY6fyvlNhwzRNHWbnQdrghy4vY5fJWEHyck/hKwGxiRGLSUwp/EDUvW05YmatOa8HkgRogYAe3ehGNt3qBpptVtLP5d7nhRhkfPihstj9AGjNJi4=)

### Other comments
In [`VIcon.tsx`'s useRender](https://github.com/vuetifyjs/vuetify/blob/8f4781f43fe5f1cad7377b92cbe5c836f3f5ebc5/packages/vuetify/src/components/VIcon/VIcon.tsx#LL44C26-L44C35), you filter ``node.type === Text && node.children && typeof node.children === 'string'``, meaning the default slot has to be text; but it's `Symbol("v-fgt")` instead.

Console results, showing that another `.children[0]` is needed:
`> slotValue[0].type`
Symbol("v-fgt")
`> slotValue[0].type === Text`
false
`> slotValue[0].children[0].type === Text`
true

A universal solution would be preferred (but if it isn't possible, you could at least support **one** level of depth).

**Comment by foxbecoding** [comment]
Maybe try using the icon prop in the v-icon component if you have more than one icon that will display based on some conditional value.  Here's an example that I hope can help you out.
`<template>
  <v-icon color="red"> mdi-information-outline </v-icon>

  <v-icon color="orange" :icon="ORANGE_ICON" />

  <v-icon color="green"> mdi-information-outline </v-icon>

  <v-btn @click="is_orange_outline = !is_orange_outline">change orange</v-btn>
</template>

<script lang="ts" setup>
   import { ref, reactive, computed } from 'vue'

  const is_orange_outline = ref(true)

   const orange_icons = reactive({
     icon_one: 'mdi-information-outline',
     icon_two: 'mdi-information'
   })

   const ORANGE_ICON =  computed(() => {
     return is_orange_outline.value ? orange_icons.icon_one : orange_icons.icon_two;
   })
</script>`
