### ISSUE TITLE
[Bug Report][3.3.2] position of combobox is not aligned

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17544]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) open the playground link given in the issue.
2) click on the button `open dialog`
3) In dialog,please scroll and you will find combobox with placeholder age. 
4) open the combobox and you will find that options are not aligned.

### Expected Behavior
combobox options dialog should be aligned with the component

### Actual Behavior
options are not aligned with components.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtXN1y4zQUfhVhLrrMxDH9gYFOttOSZZkyFBja2ZumF7KtJGplSUhy0tLpG/ACXHHNE3APL8QjcKTEtZM4bmeBXS5OWjeO9Okcfd/5ZHemtS7voxOt+7OSRYfRwGaGa0cElZOXo8jZUUQsc6U+GklCeKGVceSeGDYmD2RsVEF2YOCO78yUtI5w+4pToSZvuOWpYOSlx74YU2HZR1tRe1tgY26s+5YWVZidnUZnwfNcsG29gm4fyQrKRVuHptbOlcnb+uikitXkIR0zDE5Cz8A6w+Xk8uroxeUVoAbJQk3QDj44VmhBHQtKDnI+Cydw+mZIIaXjTjCQfGgYgMjJnFkF0//r119+HkVLaAW+YLfu6GLKLQhJ7lRpoEYwoRwITFh/kNSglnFVEyHDqcqUnxIMt14rK6m2RHNGMmqMcvB2w7wqztyFZqGE4FppUpTjMZf9RqzGgNzQyZ+/QZBpqWn4acl1eV2mzPbJGYXYSkki+I+lMjwDnFI3EHxOx8zUER0FqxXU/MQ1lSRVEr775CsQmJkURMrJNRPiLlaNfEs+j/NalaIWY+G+OtcsLlTOBMi/7sxRVKPGpRBQUcYeIxFy6EtcwMDg3SbaGSotd1xJ6M1D0DhVzqkirrvqAY26DD6IY7KYBjnJHJ9RpwyJ4yakchP5kFYISHNPtFGg9kPDMgvGXzgJLFMuc4AFEEDId5rJKhNoBaBmjqRh2fbZDRUsAOnW5hY0X83vx1woJVK6RmRlKdQRKizUMxDTIDI1d2u0amoc7E9m1HAqnYcLykFbcpwJnt20lBUW7LJgGwF9yFMfrso9n3IHwJDDXxMpBDDxLbQkm7OpRNyc5pLShV/nR+fMOXCyBfxKe9vAc00zZkKyrVFPoVS2lUoo/KMwDlbCW+tCyDmdsZYk6855bO6YXd276oZkYYdV9/6g5hsWGSrhS2SBxS4sU2L9KvwUTgpv8YNWq/gLwWvORL5Jor4EPN51mqu5egmaBtBrDyLbUOC/jE2VyJk30Ndq2ljo1WvdPP5apcS7o1nfP7t4ngXUM4lqBrfD/x/T6neBLp7fAGY7S2Yst/5KF0/hlv+UDK9US5T3LQK6Gl2NrkZXo6vR1ehqdDW6Gl2NrkZXo6vR1ehqdDW6Gl2NrkZXo6vR1ehqdDW6Gl2NrkZXo6vR1ehqdDW6Gl2NrkZXo6vR1ejqLhHelnJ4LKGL75fbAKtUrsG6uWLHIV4/U8X7JlY9VtHF7fsOjLvT/smIrjCrCvzxe/vXv27zFkWGqkhVqm67BIGnNLq0OGnvPoR/Qy/8FC53P+uR3c97ZO9jOHbh2INjH44DOD65ehc0n1X46vGYLrKnSww8j/BUWc/900e2R85KyzN4UzPOWoYhWSSLZJEskkWySBbJIlkki2SRLJJFskgWySJZJItkkex/RhaaVjesWG5DU+/Gkyx3oKm2AGr0VxtgrOy+EvWixd5LcUF1/9oqCXs13Xs4yBA6YKaHJLT4NtiTyX8eRVPntD1MkiyXMAx04zPTl8wlUhfJMcASU0rHCxbnqjje7+/3DyC/dc3mPrNFnBo1t8xAkFHUa6RxfAy7sjyZaokMGfYWGZZNMZTK+hQboRPIN4OdVgyTUCH/R6rnMVob1mS11rXBzGd/GMkH0FtweWPXpM5skPmymuQ/ohyC+UhXPuFDLwrzhMxhQHT1N00QXLU=)

**Comment by yuwu9145** [comment]
#17126
