### ISSUE TITLE
[Bug Report][3.1.13] Updating model of VSelect and VAutocomplete in tests stopped working

### ISSUE THREAD

**Issue by isazulay** [vuetifyjs/vuetify#17566]
### Environment
**Vuetify Version:** 3.1.13
**Last working version:** 3.1.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Run `npm test` in the terminal in CodeSandbox. You'll see the tests failing. Once changing the version of Vuetify to 3.1.12 the tests work.

### Expected Behavior
All tests run successfully.

### Actual Behavior
All tests are failing.

### Reproduction Link
[https://codesandbox.io/p/sandbox/vue3-vite-vuetify-example-kcb3lw](https://codesandbox.io/p/sandbox/vue3-vite-vuetify-example-kcb3lw)

**Comment by KaelWD** [comment]
I don't have time to support whatever weird shit jsdom does, if you want to test vuetify components use something with a real browser like playwright or cypress.

**Comment by isazulay** [comment]
I don't agree. This is something that worked before the upgrade of vuetify to v3.1.13, so in my opinion this lays into the court of vuetify

**Comment by isazulay** [comment]
> I don't have time to support whatever weird shit jsdom does, if you want to test vuetify components use something with a real browser like playwright or cypress.

I don't agree. This is something that worked before the upgrade of vuetify to v3.1.13, so in my opinion this lays into the court of vuetify @KaelWD

**Comment by KaelWD** [comment]
vue-test-utils only specifies setValue for `<input>` and `<select>`, they don't say what it does to components

https://test-utils.vuejs.org/api/#setvalue

**Comment by isazulay** [comment]
@KaelWD  That is true, but it's not only about setting values. Accessing props like the items of a `VSelect` should always be possible, but it isn't

**Comment by nmsu4r** [comment]
@KaelWD I'm also running into this issue. When I check the props for a VSelect (`wrapper.findComponent(VSelect).props()`) I get the following props returned, however, `items` is missing. In version 3.1.12 `items` is still returned.

```
{
  "_as": undefined,
  "active": false,
  "appendIcon": undefined,
  "appendInnerIcon": "$dropdown",
  "autofocus": false,
  "bgColor": undefined,
  "clearIcon": "$clear",
  "clearable": false,
  "color": undefined,
  "counter": false,
  "counterValue": undefined,
  "density": "default",
  "direction": "horizontal",
  "dirty": true,
  "disabled": false,
  "error": false,
  "errorMessages": Array [],
  "focused": false,
  "hideDetails": true,
  "hint": undefined,
  "id": undefined,
  "label": undefined,
  "loading": false,
  "maxErrors": 1,
  "messages": Array [],
  "modelValue": "ASC",
  "name": undefined,
  "onClick:append": undefined,
  "onClick:appendInner": undefined,
  "onClick:clear": [Function onClear],
  "onClick:prepend": undefined,
  "onClick:prependInner": undefined,
  "persistentClear": false,
  "persistentCounter": false,
  "persistentHint": false,
  "persistentPlaceholder": false,
  "placeholder": undefined,
  "prefix": undefined,
  "prependIcon": undefined,
  "prependInnerIcon": undefined,
  "readonly": true,
  "reverse": false,
  "rules": Array [],
  "singleLine": false,
  "suffix": undefined,
  "theme": undefined,
  "type": "text",
  "validateOn": undefined,
  "validationValue": "ASC",
  "variant": "filled",
}
```

**Comment by maartenbrakkee** [comment]
You can use the following workarounds (see [Ivan AIScode's answer](https://stackoverflow.com/a/76590872/1049914)):

```ts
const selectComponent = wrapper.findComponent(VSelect);

const items = selectComponent.vm.items;

await selectComponent.vm.select({ value: 'newValue', title: 'newValueTitle'});
```

**Comment by amoilanen** [comment]
@maartenbrakkee Thanks, this workaround worked for me to select a VSelect value
