### ISSUE TITLE
[bug] Multiple selections don't show selected items in dropdown when list is a collection

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1756]
### Versions
Vuetify 0.15.7
Chrome 60

### What is expected ?
All selected options should show a checked box.

### What is actually happening ?
Selected options stay clear when the list uses collections (via `item-text` and `item-value`, or `value`and `text` props). Using simple arrays works fine.

### Reproduction Link
https://codepen.io/anon/pen/dVoEyJ
(`value` showing in the chips instead of `text` is addressed in #1757)

**Comment by johnleider** [comment]
This applies to the same response from your other issue. The **tag** prop means you can use an array of only **primitives**.

**Comment by keystorm** [comment]
My apologies.
