### ISSUE TITLE
[Bug Report][3.3.3] VPagination buttons wrong size

### ISSUE THREAD

**Issue by MeikelLP** [vuetifyjs/vuetify#17564]
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Edge 113.0.1774.42
**OS:** Windows 10

### Steps to reproduce
Have too many pages and jump to the latest > 1000.

### Expected Behavior
Buttons have the right width and do not glich into each other

### Actual Behavior
Buttons are to small and glitch into each other

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstu2zAQ/BWWF7eAJbpIgQKCU6S3/kEPUQ6KuLbZ8oXlSmlg+N+7pJREUS4BcjG8s7Mz3FndnuXPGOtxANnIPYGLtiP40Xoh9mPVxVj+lqIPnjrjAWeogAT/qDoYsFqMlQsa7HUrXTq2UqglD8PDczmr2QVQoNgdje/IBL9sCNGkU3hgE0xU2Y5/mAhsQzhAK19zNfhk6JG7fXCx62lNaCz4I52Y8PX7brfuYhi8Bp3HDfZ2Jf+yEb9Xvd4h1y9LTt1lXhmZ4tyrRcxcph5NJJGAhilt42JAEmeBcBAXccDgxIYvtMl0IVg3keCMxXVmfN78AmuD+B3Q6k+bL9lgkmQxuZWTWuW6WP9JwfOZz1mlnRuplY0oSMbYJdetPBHF1CjVa89jfFYzYu2BlI9O3TBN4eDJOKh0cDdX9VX9TWmTaAnXkFx1z6EkQBZp5XZhQ+bw+A6rmVkcdpPDDPGncJ+yxRtpxX4jYIXAt0TA9260GltutWq92Sy7X1p/4byt8X/TKuo+lZhvnx75oZWLWFa6y4aXrSzvZOcyIO/+Axs6N8Q=)

### Other comments
I debugged this and I see that the v-btn from the pagination buttons all get the v-btn-icon class although they are just numbers. This causes them to be too small and thus the calulcation to screw up too.

**Comment by ftrsoft** [comment]
I confirm the problem is in the current version. This only happens when density="compact". Because there ary styles:
`.v-btn--icon.v-btn--density-compact {
  width: calc(var(--v-btn-height) + -8px);
  height: calc(var(--v-btn-height) + -8px);
}
`

**Comment by MeikelLP** [comment]
Wow. Valid bug with reproduction link: "No we wont fix that"

Guess i wont use Vuetify in my next project :)
Other major pain points with vuetify support that decision too

Biggest of them all: No ARIA support which makes vuetify impossible to use for screenreaders, people with disabilities and automated testing with Playwright (or similar testing frameworks that rely on ARIA)

This is especially painful when you think about new EU laws which REQUIRE apps to support accessibility: https://eur-lex.europa.eu/EN/legal-content/summary/accessibility-of-products-and-services.html

Good luck selling your product if people aren't allowed to use it legally in the future :)

**Comment by habibalkhabbaz** [comment]
@MeikelLP it’s an open source project. So, you can contribute and fix the issues you find without blaming on the team.
