### ISSUE TITLE
[Bug Report][3.3.3] `v-infinite-scroll` slots don't allow to set `v-btn` color

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17577]
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add `v-btn` inside `v-infinite-scroll` slot and define the `color` attribute to `v-btn` that uses ` v-bind="props"`.

### Expected Behavior
The color changes to the one you specified

### Actual Behavior
The color stays the same

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVE1z2jAQ/Ss76nQwU2S7aXrxhDQ59tr2Fucg7AWUyJJHEiaU8X/vSgZiSGeS4SBrP96+9yTxsGf3bZt2G2QFu/HYtEp4vC01wE3HpV5KLT1yV1mjFKxRrtZ+XrLrPC8Z3CkjatqFpWSxidqOINDxpbGUTgihmYHUNb5MaYGwd9RfPOOO8mF7aieAWnZQVEo4R8mHSSv41eTQDp/hCubzOeTwAyaLFV9Z3HEVWKGmMihgMnkcgQH8JHT4tN/HqdD3pzEZzTlyzs6Un4twyvgCrY1a9tBa0zrox4Q7LhRaD37XItXE2jMOUdJRUc2XipQ8bZyXyx13raiQL9BvETUI0qJ5hdrjOQTAb9OgX0u9gi2lYWuNXqVpOi4hJguvoTIqkiVzUJPPnbBS6HBuZuOV1EinBU7+DWRdI5QKNXxBDlMg6rsYDfALvd2djcrirLHIkaFDPrryf4tD+uJ2UfysiLaUkO2AgC+tIYtrXIqN8rAfUGvhRQHJFOa3kBxiMNyvAu6tFbt0aU2T7EGhXvl1Ad9z6GeQPM+gi10dfIGv09nQ2oeP4TN4bWpCOaGGW05AtdFIha9xAIf+j2yQzE0GKqMccaSGZBIvxWT6miAWV3menyL9kUNc6ZreZCf5bMbo2J5d+uSMpoca8UtWOTqoAh6GxpKtvW9dkWVVramyRiU7m2r0mW6bjJ54uG9331L60VE5fwxxJRYujWAB6bHUPQ2UTTCcN6K9mDok4uSDzpIRUti/Q+GOyjK70Z7M4rVpIpfrgcsonKJr+MKarUNLICU7OBPHBMIfGPWeWhrxBjqjeR1abpH+amx4fx9TdNE2VnWReqPscNQ962cstpHxkTJ7/AcOdMMA)

### Other comments
Like a workaround can you pass the color as `class="bg-green"`

**Comment by kappaflow** [comment]
Oh, I found that it can be changed with API:
https://vuetifyjs.com/en/api/v-infinite-scroll/#props-color

Was confused a bit by the example where the color for the button was defined inside the slot:
https://vuetifyjs.com/en/components/infinite-scroller/#error

**Comment by KaelWD** [comment]
v-bind order matters, `<v-btn color="green" v-bind="props">` is not the same as `<v-btn v-bind="props" color="green">`

**Comment by kappaflow** [comment]
Thanks, changing the order helps to make the color redefined.

But in this example the button color is defined before `v-bind`, so as I understand it doesn't affect the color at all.
https://vuetifyjs.com/en/components/infinite-scroller/#error
