### ISSUE TITLE
[Feature Request] Add functionality to exclude columns in datatables from search

### ISSUE THREAD

**Issue by wspieterse** [vuetifyjs/vuetify#17575]
### Problem to solve
Currently if you have a datatable with checkboxes to indicate if a value is false or true for a row then the v-model of that row is true/false. Currently the search functionality of datatables still searches this column which is useless as it is contained and hinders search accuracy.

### Proposed solution
Currently, it is possible to have a header "sortable" or not, add an attribute "searchable" for headers.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-data-table/#props-filter-keys
