### ISSUE TITLE
[Bug Report][3.3.3] VCard hover prop breaks elevated variant

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#17574]
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.5.7
**Vue Version:** 3.3.4
**Browsers:** Mozilla Firefox, Opera
**OS:** Windows 10

### Steps to reproduce
Use `hover` prop: `<v-card hover>Card</v-card>`

### Expected Behavior
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/853dd2d7-c839-4c44-b27d-e33761540b2a)

### Actual Behavior
Elevation is lost (both while hovering and when not hovering)
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/4316d65e-3871-4d29-950b-28795566b233)

#### Fix (workaround)
`<v-card style="overflow: initial">`
* Found this solution thanks to #17593 (as a side-effect of fixing VOverlay). I believe this should be a default behavior.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUc1uAiEQfhXCWSCpPW22xqZJX0I84DJGWmAJ4FpjfPcObNpsNKnW43wz8/3MrE70NQQ+7IE2tM3gglUZFtIT0g6sU1GTzqqUXiR1ij1JunhDrBVj7485MqholM8IgIUBSfU/lnf9ALFOk4PJu7F+VPVxtpSPFrAs81vbHxpivMlG2V/Sd/MF00StmNyQzqg1/jPxj9R7vO+pSEnapSRpQ1alKvUu55AaITrtcVKDNUPkHrLwwQn8TDbb43LO5/xJaJPyD8Ss2iReyQrTWvozChoX+piZU+FCdWxU5YoUDJlKfcPCEsdE3PtsHDDdu+rlefQygTkkxzaxPySISCLpbCJTDN8hdSstSlxRC9TDV7AIXkOEeG+ii7VpqovWVbKifi73Ps9oXcPDV8t0/Q1ZhB8o)

### Other comments
* [`hover` prop documentation](https://vuetifyjs.com/en/api/v-card/#props-hover) says:
> Applies 4dp of elevation when hovered (default 2dp). You can find more information on the [elevation page](https://vuetifyjs.com/en/styles/elevation/).
* There is no example with hover on [Cards component page](https://vuetifyjs.com/en/components/cards/)

**Comment by Redpoint1** [comment]
Still valid in 3.3.19.

It should be fixed or the doc should be updated (if it's not a bug) for https://vuetifyjs.com/en/api/v-card/#props-hover. Maybe adding a link to https://vuetifyjs.com/en/components/cards/#content-overflow ?

**Comment by johnleider** [comment]
fixed in https://vuetifyjs.com/en/getting-started/release-notes/?version=v3.3.22
