### ISSUE TITLE
[bug] Select chips show value and not text

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1757]
### Versions
Vuetify 0.15.7
Chrome 60

### What is expected ?
Selected options with the `chips` toggle showing the `text` data of the selected object when using collections instead of simple arrays.

### What is actually happening ?
Chips show the value (usually an id) of the selected options. You could fix this using the `selection` slot, but it seems really counterintuitive to do. 

### Reproduction Link
https://codepen.io/anon/pen/dVoEyJ
(Not checked options bug is addressed in #1756)

**Comment by johnleider** [comment]
Just put more time into this than I should have :(

![image](https://user-images.githubusercontent.com/9064066/30508483-d1fa851a-9a65-11e7-8708-03e086a3e64d.png)

**Comment by keystorm** [comment]
I also put more time than I should have, I see it now.

For future reference `multiple` and `chips` do the trick.

Sidenote: I don't really understand what the docs mean by "With tags you can allow a user to create new values". Fumbling with the docs doesn't allow that. Any value not present is just ignored.

**Comment by johnleider** [comment]
I don't understand what you mean.

**Comment by Traxo7** [comment]
@keystorm 
> For future reference multiple and chips do the trick.

Not quite the same.

> I don't really understand what the docs mean by "With tags you can allow a user to create new values".

This is the difference.
When using `tags`, select field is also like input text field so we can enter non-existing values manually, and they would be added to the v-model.

Without `tags` we are forced to only select items from dropdown.

`autocomplete` is not the same as `tags` because select-text-field is usable only for filtering items in dropdown.

**Comment by keystorm** [comment]
> In order to make `chips` + `tags` combo to work, we must use return-object prop.

I don't remember if this prop was available back in September, but `return-object` would be the way to go.
