### ISSUE TITLE
[Bug Report][3.3.3] VDataTable heades[].sort function does not work 

### ISSUE THREAD

**Issue by AndreySyagrovskiy** [vuetifyjs/vuetify#17588]
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 3.1.13
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.43
**OS:** Windows

### Steps to reproduce
Try to sort table by column "Sorting of this column does not work"

### Expected Behavior
Sorting works

### Actual Behavior
It does not sort by custom sort function

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV9tu2zgQ/RVCi4UTwJJ8TyykaRfZW7f7EGCfFnEeaGnicEORAkk5mxr+9w4l2ZZlUW1d+4Xk3M4ZztDjh433S5YF6xy8yLsxkGacGrhdCEJu1n5CDfUNXXKwB4Ss/VQmwCOGitrPQPkZXcG7hVcc3IO6x+3CK5WjZ6AJKI3iarWXFOp4noDWoMxeYM/9NeW59SlouvcVc6qtAXBYU8Ok8IelqECKWHfIyU/WR2BtUX1TeCTbhVfpoabOqLjdlJJA0ddC92HwGBiy3d6EhbhyGh7nI6wnBI+O5Dc6ViwzhSb8n0llSAJPNOeGbEp31vbicrcjRIHJlTjsS/q7LEZkOOgfRFUGI/JwOCN1W/sxzHA07P2D0ZlYEflEzDPTJJY8TwVJJGgipCGvUr30as7th3K2EmirDVWmKdTo0JKOiFE5tAgjckH7ZHlJ3t3iqszm+/ek17sMuIwphzuZZlTBxbIuazh6gTcEYK/jOP72aLfZ07yjXCoGutffoweR4K50hGFLsdPB79SQi9Wlw/6JGrfpHVVL3WEcW7nb/F5JA0x0OMhKDbeLj0qi/c8ue4biY+PH2nrXeN31ZK8CNTCmTZaSn0GQf+UqxwIh27q7okWrdGPhTucNGaYyIrOgXtClCSYpIqNJ47ziHpHJiYmlhWCGnRXSweIv4PyNLIHa5LgpjK+mbRQGLgpzJ4VTk4rC4FwKn5j5VJSmG/50eN2Oc9aktcd51Y5ydi7K3/DJZqoT5Wg2chTE2IXytIYqnFfn4vwDH0pQS4Xva3dFTGdtFTF0VvWk2QR7EuOgKdpV9dnZ/hgDiZFDSjQVySuLn7szP25ed0Fm7uJyol7r0OZd/WiH/i05Z5nMum9j3iydqj8dFTVv9sOhP9vhj86Ff5dnMX2BbvSD1tdF5Jw72vb78399LoE/pYC3WKbLTgqTQTOjBYVc4NDDBCTtPK6dPGZBMyUVj8n0XCK/SpF3P5OTaWsVue9hOnTfg6OnRx2VdEC2LRelEDc4h+7GSa/vcSZedPCflgKH9ILywos1Ts37n28csY3JdBSGcSJQE4d0tlaBABOKLA1xvDfs6e3DOMBvmDBtdkc+p0sdFM6sp8eF2GJAltoB1k9p1ohaCorIVeoXHnqy+69A+IBqocqFYSn4iUwLLJMSS+04AJ36SyVfcTxBJwuvSlERxgL+hlBfY4shTlyHGG+N/2cUzlCgQH0ro4ZZnVVDdMKsuuqtt+17hRkmvoDsPX4BHgqbPg==)

**Comment by AndreySyagrovskiy** [comment]
> Looks like that was replaced with `customKeySort` in #16839 for some reason: [31a8f4d#diff-d736910ed7944c018fb42418b43cacc2bf711802355698059bc7fc7186a25e05](https://github.com/vuetifyjs/vuetify/commit/31a8f4d7349b3b6df5e6c5c082419758a0a33136#diff-d736910ed7944c018fb42418b43cacc2bf711802355698059bc7fc7186a25e05)

Thank you!
Will it be not changed again in version 3.3.4 or near future?
Or changes will be reverted?

**Comment by grolu** [comment]
The `customKeySort` callback to not get passed the raw item. So this is not a replacement for our use case. See also: https://github.com/vuetifyjs/vuetify/issues/17487

**Comment by nct124** [comment]
yes we will need access to the raw object 🙏

**Comment by timoschwarzer** [comment]
I currently struggle with this issue as well. Currently, I don't see a way to make sorting columns for optional fields work.
Would a PR be welcome that passes both raw item values to the sort function as 3rd and 4th argument? :eyes:
