### ISSUE TITLE
v-select duplicates display in some cases

### ISSUE THREAD

**Issue by spaquet** [vuetifyjs/vuetify#1758]
### Steps to reproduce
See https://codepen.io/spaquet/pen/BwNeOa

### Versions
Tested on 0.15.7

### What is expected ?
Value in a chips

### What is actually happening ?
Value is displayed twice. once in a chips and once outside the chips

### Reproduction Link
https://codepen.io/spaquet/pen/BwNeOa

**Comment by johnleider** [comment]
It is only displayed outside of chips because of the nature of **chips** with autocomplete.  Notice it goes away when you blur.

**Comment by johnleider** [comment]
This is also a duplicate of #1740 which will more than likely be closed as well.

**Comment by spaquet** [comment]
@johnleider blur is not an option. When you have to enter multiple tags then autocomplete is interfering in the process creating a terrible user experience.

**Comment by johnleider** [comment]
If you are entering multiple tags, you should be using the **multiple** prop.

**Comment by spaquet** [comment]
Same behavior...

**Comment by spaquet** [comment]
I found a workaround by using a scoped template to manage the chips. But then, closing chips becomes suddenly more complex...

**Comment by johnleider** [comment]
https://codepen.io/anon/pen/pWgrza
