### ISSUE TITLE
[Feature Request] Provide touchless option on VTabs as per Vuetify 2

### ISSUE THREAD

**Issue by lukasrossa** [vuetifyjs/vuetify#17582]
### Problem to solve
There is currently no way to disable the swipe action on `<v-tabs>` in Vuetify 3.
The lack of this option causes a lot of navigation issues on mobiles when the UI contains tabs. This is particularly an issue in two instances: 
1. when a multi-tab component contains sliders - swiping the slider will activate the tab change. 
2. when a multi-tab component contains a table - on mobiles, tables typically need to be swiped/scrolled horizontally due to their size and this causes the tabs to switch.

In Vuetify 2 we had the 'touchless' prop on `<v-tabs-items>` but this option does not exist in Vuetify 3 as V3 no longer uses the `<v-tabs-items>` wrapper.

### Proposed solution
Implement the touchless prop as in  <v-tabs-items> in Vuetify 2

**Comment by rojobo** [comment]
Im having the same problem. v-tabs-items has been deprecated and now v-window is used in its place

**Comment by etrielQ** [comment]
thank you @rojobo  you saved my life!

**Comment by davidstackio** [comment]
You can simply put this now:
```vue
<v-window :touch="false">
```

See related docs: https://vuetifyjs.com/en/api/v-window/#events

Note: for whatever reason I had to restart my dev server for it to take effect (using Nuxt).

**Comment by KaelWD** [comment]
VTabsWindow already has touch disabled by default.
