### ISSUE TITLE
Chips in Select cannot be closed

### ISSUE THREAD

**Issue by spaquet** [vuetifyjs/vuetify#1759]
### Versions
0.15.7

### What is expected?
Clicking on the close icon on the left side of the chips should close the chips.

### What is actually happening?
Chips are not closed. Though they can still be deleted using backspace if the cursor is placed on their right.

### Reproduction Link
https://codepen.io/spaquet/pen/WZvBqG
(example #7 of the documentation)

**Comment by jacekkarczmarczyk** [comment]
Example 7 is not about chips:
![image](https://user-images.githubusercontent.com/15625235/30508358-5141bc42-9a95-11e7-9d6f-e41b5bfbbbb8.png)

Chips are shown in example 8 and they are working https://codepen.io/anon/pen/OxVKJx

**Comment by spaquet** [comment]
https://vuetifyjs.com/components/chips is about chips and is #7.
But whatever is the ref in the doc, my codepen show that they are not closing.

**Comment by jacekkarczmarczyk** [comment]
Sorry, It wasn't clear for me which example you're talking about. Indeed in chips/7 the example is not working, this issue can be closed though as there is issue in docs repo which I'll ask for reopening

**Comment by jacekkarczmarczyk** [comment]
This will be handled in docs repo issue https://github.com/vuetifyjs/docs/issues/219

**Comment by spaquet** [comment]
It's still not clear if this is just the doc or some sort of bug. Why would tags be required? If you want you users to select in a list and not be able to add new elements. How would you do that?

**Comment by BernardMarieOnzo** [comment]
hi, please @johnleider @jacekkarczmarczyk . is this issue resolve ? 
I installed the latest version ( 1.0.17) , but it does not seem to work. there is no delete icon but we can still remove the chips with the key backspace keyboard

**Comment by jacekkarczmarczyk** [comment]
Use `deletable-chips` prop
