### ISSUE TITLE
[Feature Request] VAutocomplete clear search on selection

### ISSUE THREAD

**Issue by mftruso** [vuetifyjs/vuetify#17592]
### Problem to solve
When using the `multiple` prop, the user should be able to continue typing after each selection. The current behavior on selection is the input loses focus and it keeps the search text, which must be manually cleared. This differs from the behavior for a single selection which maintains focus. 

Example: Start typing `calif`. Select `California`. To continue making selections you must click on the input again and delete the original search text. 
https://play.vuetifyjs.com/#eNqlUk1P4zAQ/SuzvmRXauJD91QVBELa5QcgcWh6MMm0GPylsVNAVf87Y6cVoVyQuI3fvHlv3iSrvbgOodkNKBZimdAGoxJetg5guatVCKUsj867pLRDOkIjY0i+8zyFCU8wgFEPaC5acT3tio/+QrNTZMKqulFGbzw5raoZVDfeeFK9z/U/LnVf4P/oaTsy7vBVxVzcv3mr3bZaT4XtYJJmuxNyuZSfdzzFYfhznkIscZdycgZ+xo50SBAxDeM1tA2eEuyBcAMH2JC3UPEFq0wHYN2YwMYtXGTG7+oWjfFw78n0v6o/2WCUZDExE6NabVVonqJ3/Bn2WaU9NmIrFlCQjLFLfrfiMaUQF1J2veOxHo3eUeMwSResvGKapMElbbHuvb2aN/Pmr+x1TFO4wWjrB/IvEYlFWjGb2CS9efuG1ZFZHOajwxGq+SeI2eKLtGS/HVJN6HokpO8mOhubpjprfUmW3Q+tO/C9jXbP8ezUXSxnXp2W/FHkIpaV1tnwMBNlT3YuA2L9DnXvJJQ=

### Proposed solution
On selection, clear the `search` value and retain focus on the input. 

Make the default behavior like so: https://play.vuetifyjs.com/#eNqlUstu2zAQ/BWCFyWAJR7ck2AbDgK0H9CiPVg+MNI6YcsXSEpNYPjfsyRlmLEvAXJb7szuzI60O9IHa5tpBNrSVQBlJQ+w6TQhq6nm1qYyPXqjAxca3NzKjDGY3uAUBDi3CZH8CeS6ow8lSi94K1DJI2FXPXIpDsZpwasFqR6NNI4PJtbfsRRDav8A454z4xe8ch+LP29GCf1c7cvFapRBoNylM9XKDCBbD9z1LyiZi3JopiRMQh+E0SW8He2AmbSJ9JvLEZBp9M9b7mbFPiZyDg/bH9NLxBTuihWh49P3TthAPIQxZy+UNS6QI3FwICdycEaRCr9XFemE4F4f6fEoso6ku6q6L5HZ5gwidAGLKxC+uyfrDTlmz3ljM8V7EatQjpBT9Jsdoje6oNlcrbht/nqj8R9K490M+I6254UdRdPx3dGXEKxvGesHjWOYqphcoyEwbRXbIo25UQehoB6M2i6bZfONDcKHst2AV/WTM/89OFzS0UUhE8Th7RNSMzMpLLPC3KrxD/ZR4mY1Q70JXO1AD+DAffaiq7Hyqivo5rI5+RPmLYX+56+i7n2KeXc2+aWT07K4aR8FTwuafKJyGqD7d3EZYJI=

**Comment by KaelWD** [comment]
> Make the default behavior like so

That is how you're supposed to do it, there would be no way to have the current behaviour if that was the default.
