### ISSUE TITLE
[Bug Report][3.3.3] VOverlay contained is cropped if content is larger than container

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#17593]
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.6.15
**Vue Version:** 3.3.4
**Browsers:** Mozilla Firefox, Opera
**OS:** Windows 10

### Steps to reproduce
Use `<v-overlay contained>` with content that exceeds the boundaries of outer container.

### Expected Behavior
Both behaviors should be supported depending on our use-case: cropping the content or exceeding the outer container.

Vuetify 2 behavior with `absolute` prop:

![image](https://github.com/vuetifyjs/vuetify/assets/3118390/b313ca36-96fd-4f67-b75b-78756f71f942)

### Actual Behavior
Content is cropped.

![image](https://github.com/vuetifyjs/vuetify/assets/3118390/8546f9b5-905f-4d5b-907e-5f885f741228)

### Reproduction Link
* Vuetify 3 with `contained`: [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUUtuwjAQvYrldRxLbVdRiugJegDMwiTT4tY/2U4oQty9YwdQBIuQbOb7PuPNiX54X48D0Ia2CYzXMsFKWELakUnvS1iSToaedFrG+C6okexF0EuTkPoa4JwbIWh5JI1xPWg2Sj0AbqQwgKCkczZJZaG/7S6C5+/zAnpQaU8wPlbtLhC+yuEUaWe/SYK/NMPlE/ANKRcu8q6+5iM5mSy3fHYKWlGt7G+sf6KzeKZTnhW0i1HQhmwmIEH3KfnYcN71FifRuhpDbSFx6w3HAyf1dVy/1vjzXsV0LTEtd7EuYBlpK+wZCZXxLiRmpL9jnRqFuVRyDZFyviBhjWM8DDYpA6x3pmh5m7TMyjVEw3bBHSIEBBG0mtFkwU9QLblFigdojnz4NCyA7SFAeNbR3drc1V3rwVlmP+d7nyta1vDwRTLd/gOCzwJK)
* Vuetify 2 with `absolute`: https://codepen.io/3e30K5dl6JkG/pen/yLQYMgx

### Other comments
* In Vuetify 2, `<v-overlay absolute>` had the behavior of exceeding the outer container. Documentation doesn't provide migration alternative.
* As a **feature request**, I'd really like an option to enforce that after exceeding the outer container, the element **never goes outside the screen**; i.e. its top position will always be above 0px and, if needed, page will be scrollable.

**Comment by KaelWD** [comment]
This is actually due to VCard having overflow hidden now, not anything to do with VOverlay. 

> the element never goes outside the screen

https://vuetifyjs.com/en/components/overlays/#connected  
Follow #15658 to define which element it should stick to.
