### ISSUE TITLE
[Feature Request] VDataTableHeader Tooltip

### ISSUE THREAD

**Issue by jakesteele** [vuetifyjs/vuetify#17590]
### Problem to solve
I want to add tooltips to VDataTables through the VDataTableHeader. I can do this with a custom slot. However, it breaks the sorting icon. In my UI, I would like to describe what a header means using a tooltip on the table's header. 

### Proposed solution
Add a tooltip property that creates a tooltip on the VDataTable. Perhaps a nice icon that suggests there is more information available on hover.

**Comment by freezingjune** [comment]
@jakesteele How did you solve this issue? Can you share your fix?

**Comment by DSplawski92** [comment]
> Documentation clearly says: "Headers slot You can also override all the internal headers by using the headers slot. Remember that you will have to re-implement any internal functionality like sorting."

What about fixed-header / sticky props?
I noticed, that this functionality does not work as well when using #headers slot.
Is there any solution to remain it?

**Comment by emelendez** [comment]
my solution is in the definition of header props:
when defining the props of a header item
```javascript
  const headers = [
      { 
        title: 'Name', 
        align: 'start', 
        sortable: false, 
        key: 'name' ,
        headerProps: {
          title: 'My tootip as a text'
        }
      },
      ....
  
```

**Comment by Mohammad-Alavi** [comment]
Here is what I ended up with.
The behavior is exactly the same as the current data-table. With correct hover effect, sort icon and multi-sort counter badge.

```js
<template #[`header.YOUR_COLUMN_NAME`]="{ column, isSorted, toggleSort, getSortIcon, sortBy }">
    <v-tooltip text="something...">
        <template #activator="{ props }">
            <div class="v-data-table-header__content">
                <!-- this is the tooltip icon-->
                <v-icon v-bind="props" icon="mdi-information" />
                <div class="v-data-table-header__content">
                    <span @click="() => toggleSort(column)">{{ column.title }}</span>
                    <v-icon v-if="column.sortable && !disableSort" class="v-data-table-header__sort-icon" :icon="getSortIcon(column)" />
                    <div v-if="multiSort && isSorted(column)" class="v-data-table-header__sort-badge">
                        {{ sortBy.findIndex((x) => x.key === column.key) + 1 }}
                    </div>
                </div>
            </div>
        </template>
    </v-tooltip>
</template>
```

Some context:

‍‍`disableSort` is a variable I use to disable the sorting is some situations, e,g. while fetching data from server.

:disable-sort="disableSort" 

`multiSort` is a prop I use to configure my data-table component.

:multi-sort="multiSort"

Change these stuff according to your code.

Here is the [reference](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx) I used to write this code.
