### ISSUE TITLE
9.0 - modal has a horiz scrollbar with long text

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#176]
![image](https://cloud.githubusercontent.com/assets/287137/23540964/47509a56-ff99-11e6-9b24-4e7f248ed11a.png)

Wasn't happening in 8.9

**Comment by dohomi** [comment]
@sgehrman could you post a small codepen for this issue? maybe can you manually try to set this CSS property to the inner div:
```
                word-wrap: break-word;
```
Just curious if this would fix it..

**Comment by johnleider** [comment]
That is on the container

**Comment by sgehrman** [comment]
I added the word-wrap: break-word; and it did break the word once, but it was still sticking out.  It needs to break multiple times I guess.  I'm experimenting now.  I'm 100% sure it was working which is weird.

**Comment by sgehrman** [comment]
adding overflow-x: hidden; to .modal
gets rid of the horizontal scroll, but my text is clipped, but it does look nicer.  Maybe that's what changed?
anyway, you can choose not to fix this since it's really an odd case in my app.

**Comment by sgehrman** [comment]
OK, I think the best fix is adding overflow: hidden; text-overflow: ellipsis;  to my card and it's the best looking solution.

           <v-card-text style='text-align: left; overflow: hidden; text-overflow: ellipsis; background: rgba(255, 255, 255, .02);'> {{item.value}} </v-card-text>
