### ISSUE TITLE
[Bug Report][3.3.4] VDatePicker sass variables importing non-existing styles file

### ISSUE THREAD

**Issue by dvlalex** [vuetifyjs/vuetify#17603]
### Environment
**Vuetify Version:** 3.3.4
**Last working version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
- add `@use "~vuetify/settings";` to any scss file

### Expected Behavior
To be able to use vuetify variables inside our own stylesheets.

### Actual Behavior
It breaks the compiler because `Can't find stylesheet to import.`

### Reproduction Link
[https://codesandbox.io/s/quiet-cdn-gvgz4z](https://codesandbox.io/s/quiet-cdn-gvgz4z)

**Comment by MaciejJanyska** [comment]
Same problem here

**Comment by McCdama** [comment]
Same here..

**Comment by jodesous** [comment]
Same problem. I go back to v3.3.3

**Comment by donalmurtagh** [comment]
Same problem although in my case I'm using Vite. In `vite.config.js` I have the following configuration

```javascript
  plugins: [
    vue(),
    vuetify({
      styles: {
        configFile: 'src/styles/vuetify-variables.scss'
      }
    })
  ]
```

`vuetify-variables.scss` changes a SASS variable and makes them available to my components

```
@forward 'vuetify/settings' with (
  $card-border-color: #D0D0D0 !important,
);
```

**Comment by bjorntrondsen** [comment]
I just sted this on `@vuetify/nightly@3.3.4-master.2023-06-15`  @KaelWD and the issue remains

This one is now fixed:
lib/labs/VDatePicker/_variables.scss

But this one is not:
lib/labs/VPicker/_variables.scss

(VPicker is also imported from _component-variables-labs.sass)

**Comment by steklopod** [comment]
> Same problem. I go back to v3.3.3

Same for me. This solved the problem

**Comment by kingyyy** [comment]
same for me but v3.3.3 doesn't has VDatePicker
