### ISSUE TITLE
[Bug Report][3.3.4] VAutocomplete - Exported types for valid $emit events are incomplete

### ISSUE THREAD

**Issue by boast** [vuetifyjs/vuetify#17605]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
If you install the latest version of vuetify (3.3.4) and have a look in node_modules/vuetify/dist/vuetify.d.ts one sees all the exported type information. If we go to line 5342 (it's a big file...) we see the exported $emit events for VAutocomplete: update:focused, update:menu and update:search.

As one might note, some events are missing here (see https://vuetifyjs.com/en/api/v-autocomplete/#events). Namely update:modelValue and all click:* events.

I am not an expert in how those types are generated, I see they get "assembled" in a build step and they are definitely working, but you end up with a @ts-ignore to make tsc / ide / lint happy. I think these need to be generated, as they are implicitly available (i.e. from the "v-model").
```
import { onMounted, ref } from "vue";
import { VAutocomplete } from "vuetify/components";

const autocomplete = ref<InstanceType<typeof VAutocomplete> | null>(null); // ref="autocomplete" in template
const myDefaultModelToApply = {}; // something fancy here

onMounted(() => {
  // @ts-ignore
  autocomplete.value!.$emit("update:modelValue", myDefaultModelToApply);
});
```

### Expected Behavior
All VAutocomplete $emit events have their type information exported.

### Actual Behavior
Some events are missing.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkDEOwjAMRa9SeW6SAaZO3IMwADEi0LiVHYoQ6t1JSpGqdqnEFOXb/s/f+zf40DYcVTi2+iYNQQVvS0Vhx4JYqIpByVr3wPy3cI2xlcqYs6M05rD2HWvCaKgNZpfaDD8o+oDKNWG30Ru9Nc5LnMoaJagTN09BTiYWygkm+strBWrsnBJGSdXHk2TEwtokXoesGMkhI69NNBubMmelRbJM7y31UELt6S6zU59lOPP+t+RfkQez7HTIwL6EoTGRv+/hAw9qqX4=)

### Other comments
I am sorry for the bogus link, but the TypeScript error cannot be easily reproduced in a JS playground.

**Comment by KaelWD** [comment]
The "missing" ones are all defined as props:
![Screenshot_20230906_214904](https://github.com/vuetifyjs/vuetify/assets/16421948/2560ce5f-c9bc-490c-9ebc-8b85c823e480)

modelValue is generic so has to be omitted here so it doesn't get contaminated by `any`: https://github.com/vuetifyjs/vuetify/blob/b299930feb08b242093cf7f1d8d96318fd23aa91/packages/vuetify/src/util/defineComponent.tsx#L196

And the click events are defined as props so we can tell if they're set: https://github.com/vuejs/rfcs/discussions/397

Calling $emit on another component is not supported, I don't know why vue even exposes it.
