### ISSUE TITLE
[Bug Report][3.3.4] VSelect Value Vertical Alignment

### ISSUE THREAD

**Issue by Winter979** [vuetifyjs/vuetify#17604]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Mac OS 10.15

### Steps to reproduce
The value and placeholder in a VSelect is no longer vertically aligned, but it up a few pixels. 
It functions fine for VTextField and the VAutocomplete

### Expected Behavior
The text should be in the center

### Actual Behavior
The text is top aligned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtkk1u2zAQha8y5cYtYIlF024Mp0h3vUEXYRaMOK6Z8A/kSIlh+O4ZSjYiOF4ESFYS3zy+j5zh7V78SakdehQrsSb0yWnC3yoArIdGpzT+josuBtI2YIZCO4fXSjxZQ9sV/Pj1PT0rcXSOXsJnajYWnQEO7HAbncHMW/6ic1EJGHS2OhArsSfHqYZFg6FY2rHYRZ90R6zJeWxBhx19aqTuKdaSQ8KTDJcJr+VLqNfqBeapeEKv5ayfU7dZmdq9lrMx8LJ02SaCgtRP07A+xUywh4wbOMAmRw8LnuCi2gE4txD48h+uq+PrYjw+/IvZmS+LbxUwRXKYWIoprfE6tQ8lBn4G+5qijoWixApGpWpMqWsltkSprKTsTOBtBp0dchuQZEhe3rBN5j6Q9diY6G+u2qv2pzS20FxusfjmPsengplDlFjOMGQ3u3egjs454Sg1Tt+XingTLZk3YG4yBp4v5vfe6GzbnHlWenOzSj+ocOB+83N5LGet7srY5tvTIT905TGsJt1V4GEpRiOTp+/dC32TUWY=)

**Comment by KaelWD** [comment]
#17412

@yuwu9145 You can see this in the [percy link you posted](https://percy.io/c458cb73/vuetify/builds/27968022/changed/1555204882?browser=chrome&browser_ids=38&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280) too, and all inputs are 4px taller now just because chips didn't fit sometimes?

**Comment by yuwu9145** [comment]
The previous fix ensures that all inputs have the same height as the one that has chips.

This issue is input value/placeholder alignment in VSelect, It appears that there was a missing piece in VSelect, which was implemented in other select components.. I can draft a PR soon
