### ISSUE TITLE
[Bug Report][2.6.14] Snackbar stuck inside Toolbar

### ISSUE THREAD

**Issue by tdoan2010** [vuetifyjs/vuetify#17611]
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.7.13
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a Snackbar inside a Toolbar.

### Expected Behavior
The snackbar should be displayed at the end of the screen/viewport.

### Actual Behavior
The snackbar is shown inside the toolbar only.

### Reproduction Link
[https://codepen.io/Triet-Doan/pen/gOQPPKW](https://codepen.io/Triet-Doan/pen/gOQPPKW)

**Comment by KaelWD** [comment]
162149f4 / ff4cfd3ff2494621f2788ab0dff635471c222e24

**Comment by tdoan2010** [comment]
Thanks for the info. But how am I supposed to fix it?
