### ISSUE TITLE
conflict with lib-flexible

### ISSUE THREAD

**Issue by kimixu717** [vuetifyjs/vuetify#1761]
I found that vuetify  conflict with lib-flexible, and it seem that vuetify operate the html element inline style, and it removes the style that lib-flexible(https://github.com/amfe/lib-flexible) added. Can Vuetify change to operate html with Class.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
