### ISSUE TITLE
[Bug Report][3.3.4] After clicking VBtn becomes disabled, and the Tooltip does not disappear

### ISSUE THREAD

**Issue by lukser69** [vuetifyjs/vuetify#17624]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on the button

### Expected Behavior
The tooltip will disappear

### Actual Behavior
Tooltip remains

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkctOwzAQRX9l8AaQmngBq6qgwgew6q7pwkmmwtQv2dMgVPXfGSd9hHZTiVUy1zPn+o6XO/EWQtltUUzFjNAGowhfKwcw6woVQv/bF413pLTDeJB6sSYH01YnVRtsXypxp9NbQ7rDSsC8MbrZsHjU4AXWyiQ+OyEA3hcf54KJ5L0hHUDlEUU+MiCoiI4YaXyjSHvHWu2JvGUULA4TM3maPl+RNb7jMQVXf2NkZUg5k6P0XKYm6kCQkLYDTtvgI8EOIq5hD+voLdzz4u5zOwBzE8EoKrc9UNziY2YPNOaIiRhAhVWh/Ere8eJ3GcB76g9SJabQK1ljg1xX4pMopKmUTet4rEWju1g6JOmClXNuk3HrSFssWm/nT+VT+Sz5YWgsl5hsUUf/nTAypBKTkQ3p9c8NVofOscNBKoyqU7a4Qkv26zAW/IotRoy3JroYG3teHF0ly+77yu1530a7TbpYdZP6NS+Pl/xX5B6WSatsuJ+IvpGdh+/qF1gUIpI=)

**Comment by KaelWD** [comment]
Make the tooltip disabled too.
