### ISSUE TITLE
[Bug Report][3.3.4] v-autocomplete long text is singleline when focused

### ISSUE THREAD

**Issue by derpierre65** [vuetifyjs/vuetify#17627]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0, Google Chrome
**OS:** Windows 10, Windows, Linux

### Steps to reproduce
- create a v-autocomplete
- have an item with a long text (longer than the input size)
- focus the input field
- text is now singleline

### Expected Behavior
text should remain break into multiple lines (like if the field was not in focus)

### Actual Behavior
text will only displayed in one line

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkstu2zAQRX9lyo1bwBKDpivBKdJd/6ALywtaHMds+QI5UmIY/vcOJbkR7E2AaiGR87iHc8XtWfyIsR56FI3YELpoFeH31gNshkrFOC55o80AmU4Wn1rxajQdG/j68BDfWjFXTA09hS6wCBJewwCNYeHMjdvVT7Q2gAHlQMGA6XT/Gh9e2eBfgPCNVrtWvItp9NnQidUKSHW0TA4qGeWJk6EnazzqZfZoNFYaSRmb36OdRZXU3v47sLzOLHnoyQp59WIjFx7xNnfJRIKM1E9WGRdDIjhDwgNc4JCCgxXbuyrlDAs+E7j8Ak+l4vNsyK+QrP60+lIAkySLibWY1CqnYv07B8//6FxU2jmRW9HAGCkxppR9K45EMTdSdtpzm0ZrhlR7JOmjk89cJlPvyTg2I7jnx/qx/sajZlqGa8yu2qfwmjGxSCvWCwyZw+kDqLlySZhDlVX7XBB30pJ5fBGqhF5jwvTRiW7alsyb1N1khX5p/YX95ivzJ99Y3eXR5u31kP818ihWlHYFeFmLsZDJ03f3F5j7LRQ=)

**Comment by johnleider** [comment]
technically duplicate of #17348
