### ISSUE TITLE
[Bug Report][3.3.4] Elements that overflow are covered by those under them, even ignoring z-index

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#17628]
### Environment
**Vuetify Version:** 3.3.4
**Last working version:** 2.5.7
**Vue Version:** 3.3.4
**Browsers:** Opera, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Create `<v-card style="overflow: initial">`, place an element inside and make it overflow, for example by `style="transform: scale(7)`.

### Expected Behavior
Element covers anything outside the container, especially when using higher `z-index`.

### Actual Behavior
![image](https://github.com/vuetifyjs/vuetify/assets/3118390/d68f7179-5400-4d5a-a3d1-a2b57c3611e9)

`z-index` is also ignored - in general, it works way worse compared to Vuetify 2, and the rules behind how some components sometimes have increased `z-index` seem too arbitrary.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu3DAM/BVBpxZYWW42QFF3WyRA7/2AOAfFpmO1ekGinU2D/fdSdhZ2HKAJUN84JGc4FH3zxK9DKMYBeMUPCDYYhfC9dowdRtGo2LKEjwa+1dyPEDvjHyqmnUatTM1Zn0HWGJUSVVglLmo+Nf93+0Sg7f05YktZKy5rvuBnAYzKpc5HW7HUKAMfPn/8yv4I7Vo4VuwLfS+6YkM9PWJIlZRBN2mwReg9+iQvylLuy3JdbtVR9KDve6SuT2UZjktWnh3L2fKyAIQjik6DaTcmmVF3YCj8AZ0aDBIys7zg+CfDqKJWLo/jBzTaQbui/blAz7zPr7HZ9bXz2OcnoNxK+iBXl8B3nLh+p+JX8o6u5Cnz1bxJqeYVu5nNLqtsWkeVLRg9xsIBShespPtC3T1e7Yt9cSlbnfAMCRo5FRNZZrqt3YkEtQ0+orAqbFTnxKQ8IRkjphy/McIVlck4ONQWROvtNEs5z7KCC0hW3EX/kCASSc13K5k88Duk3nJLEq+oJenRzyAi0L1GiO91tGlbu9qkXjnL6qe879OOT220+GlkfvsXLQ9VxQ==)

### Other comments
* `overflow: initial` on `v-card` as recommended in #17593 causes the same behavior as Vuetify 2, where this worked flawlessly.
* On `.v-system-bar` I use `z-index: 0 !important;` to address this issue, as mentioned in #17580. Do we have to use this workaround everywhere?
* ✨ When using `max-height`, the width is supposed to reduce, but in old browser (reproduced in Firefox 106), the image gets cut instead, keeping full width. The old Vuetify 2 version behaved as supposed even in old browser, so why does an element as simple as `v-img` need a breaking change? Is there no way to make it backwards compatible?
  ![image](https://github.com/vuetifyjs/vuetify/assets/3118390/03f59970-6541-4a08-9439-890cbf8914c5)

* ✨ There is also a strange behavior of stacking order of `v-snackbar` - when I enable more of them, one unexpectedly gets a `style="z-index: 2010; "` (instead of 2000), causing their order to change. I wasn't able to reproduce a minimal example for this, but it always happens in my project. In any case, this side-effect is too arbitrary and seems to be introduced to VOverlay in [#05290fe3](https://github.com/vuetifyjs/vuetify/commit/05290fe3be368b1e8dba8fb1b9c6aa26cbf6ba38#r116908892). It requires a workaround of
  ```scss
  <style lang="scss">
  .v-snackbar--active {
    // Hotfix to prevent some snackbar displaying in incorrect order (with 2010)
    z-index: 2000 !important;
  }
  </style>
  ```
* In general, `z-index` override used by libraries doesn't seem to have effect (for example, [fullscreen mode of Trumbowyg](https://github.com/Alex-D/Trumbowyg/blob/c15967ca4f020c17edb340836c52bfa08ed67be5/src/ui/sass/trumbowyg.scss#L574)).

**Comment by KaelWD** [comment]
VCard also has `z-index:0` for shadows and background images

> the image gets cut instead

Seems like a firefox bug with grid, `height` works as expected

> There is also a strange behavior of stacking order of v-snackbar

Intentional, the most recently opened one is on top

**Comment by scscgit** [comment]
> VCard also has `z-index:0` for shadows and background images

I'd expect that we can at least set `z-index: 0` on `v-card` itself, but I can't get it to work.

> Seems like a firefox bug with grid, `height` works as expected

Yeah, sadly height isn't sufficient for my use-case. I'm mostly curious as to what "new CSS feature" had been used, as it's not intuitive how a feature as simple/old as this can possibly cause a breaking change.

> Intentional, the most recently opened one is on top

It really doesn't work though, I wasn't able to reproduce a deterministic behavior. In any case, I illustrate a use-case of defining a set of multiple snackbar types with priority, as in `v-for="snackbar in ['warning', 'alert']"`.

> Yeah you'll get that if it's in another element that creates a stacking context, that's exactly why stuff like [teleport](https://vuejs.org/guide/built-ins/teleport.html) exists.

Does Vuetify 3 now create stacking contexts that intentionally cannot be overridden by any library? I wonder what kinds of workaround steps could be documented for beginners.

**Comment by KaelWD** [comment]
> I'd expect that we can at least set z-index: 0 on v-card

It already has it

> what "new CSS feature" has been used

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout  
I think I'll have to revert that anyway though: #17413

> I wasn't able to reproduce a deterministic behavior

An example of this would help. It reuses the same code as dialogs and menus so it should be fine

> multiple snackbar types with priority

Typically you would have a single snackbar component and switch between them with a script, might be some ideas for you in #2384

> intentionally cannot be overridden

No, it's just a consequence of CSS that's needed for other reasons

**Comment by scscgit** [comment]
> > I'd expect that we can at least set z-index: 0 on v-card

well it gets covered by z-index: 99

> > I wasn't able to reproduce a deterministic behavior

Sadly, I'm only able to debug it in the inspector as part of the entire project (where I see that one VOverlay gets 2010 and keeps it even after the snackbar is closed/reopened). I was only able to reproduce the behavior I wanted:

* [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFU8GO2jAQ/RXLqrQg4YR2e4pgRY/9BoK0Jhl2XRzbsp0AQvn3Tpw4UKi0SHtYLnjejOe9mRevz/SXMUlTA83owkNlJPfwkitCFg1zihf7LbddSEjDdtouczqJ8IzE029VwnFKhCLrvrb7PYG12j7NrpADt0qot38wVxcFOBexTU77QyZKJHvlxow62LdzPLavY90eTlg4ah1gqQvuhVaY8tqMxZUuQbKGyxowA4pvJZTreHkkt7rGkToB8i1i3nLlxNDTFVZLyU7sgo4cXlSga49V3+fzeYQLLcP6LJQRcv4kOxm6AbuT+pARXnsds6valGjGjeRJOEyXL3falyHT3w4OEnK+7KsNnqYXU6PJxTtgrI9fY7LkW5D/se9Roz69pG4lcQUILNKrR7BAl4XxoQ6ORltPStjxWnpy7umRm0+mMcLvBnxt1SXGe72CjJzbcSHBC/wLAAaLdCSiMyqF2rvkj9MK32TolNPCuZxmcfE5fffeuCxNi1JhJY4uGpso8KkyVYqv2YvdafWcPCc/0lI4HyGG63ZJaNZ12uSqRUJRdaOxipsb1j4RmIeJcoqduvgDCSssS22tuqfASl0FLT97LVdwAq5iW6sPDiw2yemwokDTCX6A6qNpkeKudYp8+OaYBfymLeBX99hEN9eup7pJ3U02WN3SdkbDNVx8kEw3fwE+Ps6E)

where this issue doesn't appear, i.e. the priority works as I'd need it to.
* (In general, I don't agree with Material Design on only displaying one snackbar, and I can't afford to display a non-dismissible error before a dismissible status update.) At the moment I'm only upgrading Vuetify 2 project 1:1, but I'm certainly voting for an official support of snackbar queues :)

**Comment by KaelWD** [comment]
> well it gets covered by z-index: 99

The existing z-index: 0 creates a new stacking context

**Comment by scscgit** [comment]
@KaelWD what is the workaround then? How can we make it work like it did in Vuetify 2? I believe that higher z-index values should be able to override lower ones.

**Comment by scscgit** [comment]
I found a workaround: it gets fixed once I add `z-index: initial` to BOTH parent `v-card`s' styles.
* [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1k89O3DAQxl/F8qmV1nHKIlXdbiuQeu8DEA4mmRC3/id7EpaiffeOE5aEIAEXcvPnmd83M55cPfDLEIqhB77jewQbjEL4WTnG9oOoVWxYwnsDPyruB4it8Xc7pp1Grcx39k9o18DhSak463IYq41KiXKsEmcVH3EfAByR2t6eTmwOa8R5xWf9ZIlRudT6aHcs1crAp6+fF6bf6HuWFWvK6RBD2kkZdJ16W4TOo0/yrCzltiyX4VYdRAf6tkPK+lKW4TDfytMM5DSEeSQIBxStBtOsmmRG3YCh4y9oVW+QlInyjPEqYVBRK5fL8T0a7aBZYH/P0iP38X1Ws750Hrv8BHS3sN7LxbbwDSfW31T8Sd7RJj1kXsXrlCq+Y1dTs/Mo68ZRZANGD7FwgNIFK2kHUbf3F9tiW5zLRic8SYJKTsUIy6Tryh3JUNvgIwqrwsp1uhidRyVrRMrnN0q4oDAZe4fagmi8HWspp1oWcgHJipvo7xJEglR8s7DJBb/D6q1uyeIFWpIf/QwiAu1rhPjejlZpy65WVy86y+7HPO/jho9pNPixZH79HxLIYoE=)
