### ISSUE TITLE
[Bug Report][3.3.4] After scrolling to the bottom, when scrolling to the top, the data from the first table disappears.

### ISSUE THREAD

**Issue by DiegoAlessandro** [vuetifyjs/vuetify#17622]
### Environment
**Vuetify Version:** 3.3.4
**Last working version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Use `v-data-table-virtual` component and added in items props many datas.
2. Added `item` slot and build `<tr>`, `<td>`  tags. 
3. When table datas showed, scroll to bottom and one more scroll to top of table.Data will be lost at this time.

### Expected Behavior
The first data should be displayed when scrolling up.

### Actual Behavior
When scrolling up, the first data is not displayed and the subsequent data is displayed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVk1v00AQ/SuDOaSVYjs0qBJWWxXBAa4IiUPdw8bexNvsl3bXTivL/51ZfzSxU5AQAoGU287M25l5L+PM3tXBe62jqqRBElw5KjQnjt6kEuCqConW7bE1BGGyt1o7IyaHihhGpLtOA1U6ziTN0+AZ1MJy4kjoyIrTsGLGlYTvwwAJw5oWr3tYGhyGCso2hc+cEZ6dvVksqgJCuLhc6MfzMTIpKMmp8Wn60yS+Zo80D7sYgpwp6Rhh3ROnnkRFzZqrXQKkdOoQc0AKaQ1CwWvfP16swR/mkCleCmmhGcnQ3TGQcWJ9l50czqQB3GacZVtfWn7wp68+9EXtzny+yJAdcp1k8rnyqQugCtfKs+toApNDM2OqvSRb+vSMjdB4CTSoIshjuGO5KxJYLlD+Y+xRh9ij1UTeQN0p45nc7avdQ9PAVdxCjsjFLp9qFzsz/gHi0agOzpembT+yGPYzO0w0ms8j7Y1u2EeZ0bSZYdqBpa7svgUmtDIOajB0DQ2sjRIww+9n5uGAmkvrQNgNXHvE2ewT5VzBN2V4/mp2vof0k9rD7mpAWRKYSSLobA6OOU4HE5r7g4ue4nCro1KDhyH6M3oFznAOu4JKWJFsC66ggCQU54CJ5pMbHxndqIu/EDj5T/6T/8/5l/9aQ29/OfDfU/6R/90Q8H/juPXalYLLJJgH3TbBRaSjB6skPsJqD0z7AO7uBFqP9+GW8Taubee0TeK4lHq7iTIl4luMxaaUjgka5krcLqNltAgJ1wWJLuOcWXcYjqgV4cqoncV9/IBV+r7bGo6t8TlwWCfLJaJyylllIkldLLWIe2Rb6aKr0LtCTlbWlzhKHWM9fGKFhkpcfhQfQD+hM8G+RGkCOaLlSzepbFBpfJxu7UTkzLYC92v0N/m2ydpf2Rds5sGoX+ygvRjcfwfS1WXL)

**Comment by KaelWD** [comment]
It doesn't have a hardcoded height anymore, the item slot instead provides a ref that must be bound to the element to get dimensions: https://play.vuetifyjs.com/#eNqlVM1u2zAMfhXOOyTB/JOtww5GW7TYZbsOA3ZIgkGxlEaNLBmS7LQw/O4jbSexnQIbsBxik/z495H0qg4eiyKuShGkwa0XeaGYF/drDXBbRawo2tdWyJnUvdTKGbMcKmYl0/5uHZjSK6kFXwdnUAvjzLPIs60SUSWtL5m6mAFSiTkduhNsHQxNeyGf9hQ5Yyqbf1wuqz1E8OnLsnhZjJHpXjAuLIXp3yb2nXwRPOpsCPK2FGOE869KUBOVsDtljimw0pshZtAUtnUiCt5T/ehYQ2FN4UIgOYTMqDLXDpoRG52rHSsAqmgrNccgbYhxYfTLFHPUW0ci+l8hHjIlswPVr7/S209C/jDHOVUTW3acEDZpp6uLT1VU2c4QYR1zIPWpsesSkOWDeD1jYxTeAp2IztlLdJTc71O4WeJEr7FXFWKNrmD6Huq6ZZn6Wl2ybaBp4DZpIVfNJZ5P55B4O55pMtr+k/KtBb5cAZrpDE5HguL5Skjo7mcUGUWXWVl4cMKX3XnJvDDWQw1W7KCBnTU5zPAkZwTH+RvtPOTuCe4IMZ99E0oZ+GWs4u9miwukX/4etqoBaUlhplkuZiF46ZU4idBsBo7UInqhBxkR8x0j5HgMHI57oWHLsgP4vQAs3SgFGK1iqkTkEgPFGCRjft6R8Ggte42ph3kNSuinbsbQhDD/jfexgLt7QFMfQIbnnMgSzOADSGgWbXH4hwNt2UKegjDoiEKOi/jZGY2frJpw696Aa5lCqyEdEkgybqT3hUuTJOMa3bhQsrKxFj7RRZ48ICyxpfYyFxE3+cNNfBN/Trh0fqiOhcujrTVHh9v2jInCQRovd7jsf03VI4cZelWk2NZRiqvQCebDb1JkhcbRCrz9f+to4jbMOTFddUbZm7VukG/8oB/chOrMtTSvTkX+V8ttMIq0oYRNGLRAzNw9N38AUkIAlQ==

**Comment by DiegoAlessandro** [comment]
@KaelWD 
So this is the way it was done! It worked the way I expected it to work. Thank you very much 💯
