### ISSUE TITLE
[Bug Report][3.3.4] v-img with gradient flickers on load

### ISSUE THREAD

**Issue by Troplo** [vuetifyjs/vuetify#17623]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. Create a `v-img` component with the `gradient` prop (such as `gradient="to bottom, rgba(0,0,0,0.5), rgba(0,0,0,1.0)"`)

### Expected Behavior
The rendered component will have the gradient even when the image is loading/loaded.

### Actual Behavior
The rendered component has a noticeable flicker on mount/load where the gradient is not visible.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkE1uwjAQha8SedVKiQ2CViiiFT0HZpHEQ+o2/tF4SFUh7l47ATWFDVKVReznefPNm+2RvXnP+wOwkq0JjO8qgldps2zdF9q06ZRlAZsXyd6JfCiF0JzQ+c7xxhmhxV7N5qpaPS9Vs+LetpKNphYrpcFSdJLLakfkTJ5hW1cPs3z4+NPjH2HOZ48Xd9m4HjB58QCjOI4lhrnieS0m87KcaeMdUmEqzz+CszHQMRnk+SFIVmaDkrSYON1/QzXKRpuCTvfILZCw3ohNLBN4sKQNFMqZzYIv+FIoHWgqcwimqNF9BcDYRLJ8giG9/74Dda6cEs5S0VV1SIib1iLy4pIKBKsAAe9NdGWbMq+ebpIl+knaU9x3p+1nuFp1E4Y1by9D/ivy0Cx12iXgKWdDYSSP/90PuyznQQ==)

### Other comments
Present on Vuetify >= 3.3.0
[video](https://i.troplo.com/i/e7f6abfda794.mp4)

**Comment by jscottsf** [comment]
Ran into the same issue. When I set the `transition` property to a unknown value (e.g. `transition="xyz"`), the flicker goes away. Likely related to transitions with gradients. I just set `transition` to a fake value everywhere I had a gradient. A hack until this is fixed.
