### ISSUE TITLE
[Bug Report][3.3.4] [VAutocomplete] Setting color string as loading value does not affect linear progress bar color

### ISSUE THREAD

**Issue by dnasir** [vuetifyjs/vuetify#17626]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
* Add an instance of the VAutocomplete component.
* Add the `loading` prop, and set the value to `primary`, as per https://vuetifyjs.com/en/api/v-autocomplete/#props-loading

### Expected Behavior
The linear progress bar is displayed in `primary` color.

### Actual Behavior
The linear progress bar is displayed in the default color.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU0tu2zAQvcqAGyeAJaFNV4JjJECPUHQTeUFLo5otRRIkpcYJdPcOSdmVZSCfhUAN33zemxk+vbJHY/KhR1ayjcfOSO5xWymAzZDV3DbxP1laeS4UWmhlL05AhKz+ezYnXwn0ufuKfflasRlIsIFachcwj88+M1Z03B4XXgA/DsJB8AA6G+GI2hEbEAr8AWGKClW0zckZ4edj73WtSQN6BKl5Q1zdQfeyAS6dhj2G6MvIC2aFmcsooo5PCBsyPmNwqWbIOt2gpLiByx5dxS7xUlD3Q9p4LlHJ9zH2O7a8l/4KJq1C/SKHczPnDtsgZU7tDZXB/j/OhE5zT2sRbtJebIrZwpDpaiuMj174bLT10CS68JqyNdzzEm5u4X4LN9MdQBRcwtOq1Xq1htWe23C04uUlmj2du/XJO3WvJDx4p9vxNv6MgdKZBFszKdQfl/92WtF2x3oVqx01l6qlyIodvDeuLIq6UeRJExKDzRX6QpmuoHfhRXt8uMvv8m8F7aA/XWU0EZfHZCHTrlIjFRRdkJ113CyqJiBWnnTTHvQY7HcoPJBbYXvlRYdZo7s5l9l1jq7L9jQ4h5aSVGxqTSwTCH+g1HtqqcRV6oLqDWgzi4peG9qPKlqEzWsuoCtl06hHNq5ZDKPGp3P3DwHzgfo=)

**Comment by KaelWD** [comment]
a533a7e454abba660d5e4f1e519142538bdd6bb9 but then didn't actually implement it.

**Comment by dnasir** [comment]
> [a533a7e](https://github.com/vuetifyjs/vuetify/commit/a533a7e454abba660d5e4f1e519142538bdd6bb9) but then didn't actually implement it.

It's partially there. The `color` prop for `LoaderSlot` needs to be set to the `loading` value, if it's a string type. This commit simply updates the acceptable type for the `loading` prop.
