### ISSUE TITLE
[Bug Report][3.3.4] Snackbar Offset doesnt seem to work

### ISSUE THREAD

**Issue by tokidoki11** [vuetifyjs/vuetify#17632]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
On v-snackbar set offset props value

### Expected Behavior
A single value that offsets content away from the target based upon what side it is on

I expect it to be located relative to the location

```vue
    <v-snackbar v-model="snackbar" location="bottom" offset="100">
```
for example this one would be located from bottom 100px relative to body

### Actual Behavior
Relative doesnt have anything to do

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU8tu2zAQ/JUFL00AS0qbngQ7cNFLe+qhxzBAaGqFquZDINdqCkP/3qVefqRAchI5nJ3ZWVKPR/GlbfPugKIUa0LbGkX4IB3Aumo60EbFuJGC8IUyjY4wgFXZJykGDrO6bEcOtto0es/E6JTe71SADVA4IPPgR4sOfs74uhgqTuVLRZdZX6E5E5ECjNeKGu8Y3XkibxnzdR2RGPl4d7c0AnA8QmoT+l66GVsisXo0nkqlk1pcipYE2hsfWLNt3J49OhUa5ZJJ0mTgfwlrZWKKeBID+Go8Yyf1i7hpfzHkkTBLjnMvePC8umDyNurQtDRQ8KX1gaDCWh0MwXFUqhSpEm5uYfMANxMGMGuXY7erGU+xSnj+hsb4FXz/YEEt3OeJ1d8OC57nuljsxUoYnlHMf0fv+NUMTlLoGKUo4XGslOIXURvLotCVYybfa9OF3CEVrrUFvzdq6r/b+/w+/8x5I81QZtQu5oNYUnqSrmfDxqbAmVXtlet4MDhPiaVgpbR/o4Ut04pwcNRYzCpvz3s5g3OMNtsF/ydiYBEpptEMNqnhd1i9lZYtXkkX7NdhyAK6CgPyr/C+RFdl555XR6+STVfdi34lhjIe/Ph9+gcHfVwO)

### Other comments
I actually see the package v-snackbar.mjs

i cant find any offset being referenced at all

**Comment by KaelWD** [comment]
Offset is currently only used by connectedLocationStrategy which is for menu/tooltip
