### ISSUE TITLE
[Feature Request] VFileInput missing truncate-text prop, long file names overflow

### ISSUE THREAD

**Issue by hackel** [vuetifyjs/vuetify#17635]
### Problem to solve
Long file names overflow the input control.
![image](https://github.com/vuetifyjs/vuetify/assets/583677/2e54cbc7-eae6-40ba-8ca9-2d2b7c463264)

### Proposed solution
Add the `truncate-text` prop from Vuetify 2 that automatically truncates filenames to the specified length, including the extension at the end.

**Comment by freakbite** [comment]
I'm having this issue as well, it's a bit annoying since file names tend to be pretty long in my field of work.
