### ISSUE TITLE
[Feature Request] VMenu's option to set max-width of the menu to the width of the activator

### ISSUE THREAD

**Issue by exebetche** [vuetifyjs/vuetify#17634]
### Problem to solve
I want to put `v-virtual-scroll` inside a `v-menu` to manage selection in a very long list of items, but when you scroll down, the width of the menu changes continuously with the size of the items displayed by the `v-virtual-scroll`.

### Proposed solution
An option to automatically fix the width of the menu to the width of the activator (a v-text-field in my case) would avoid this confusing behaviour where the scroll bar of the `v-virtual-scroll` is jumping left and right as you scroll. Maybe `width="activator"` or `activator-width` as the option syntax?

**Comment by KaelWD** [comment]
`min-width="auto"` (default) with `max-width="0"` will do that.
