### ISSUE TITLE
[Bug Report][3.3.3] Property "isHovering" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by LikeDreamwalker** [vuetifyjs/vuetify#17644]
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.51
**OS:** Windows

### Steps to reproduce
run `npm i` scirpt
open the local server
warnings are in console

### Expected Behavior
Without these warnings.

### Actual Behavior
With these warnings while the page creates.

### Reproduction Link
[https://github.com/LikeDreamwalker/field-splicer/blob/update-to-vuetify-3/src/App.vue](https://github.com/LikeDreamwalker/field-splicer/blob/update-to-vuetify-3/src/App.vue)

### Other comments
I am trying to bring one of my programs to Vuetify 3 as a practice, and I have an issue while I am using `v-hover`. Seems like `isHovering` works, but I still receive the warnings. What causes this?

**Comment by KaelWD** [comment]
This is not in scope: https://github.com/LikeDreamwalker/field-splicer/blob/update-to-vuetify-3/src/App.vue#L153

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
