### ISSUE TITLE
[Bug Report][3.3.4] VTextField does not navigate correctly on tab press in VMenu

### ISSUE THREAD

**Issue by avarixe** [vuetifyjs/vuetify#17645]
### Environment
**Vuetify Version:** 3.3.4
**Last working version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. add VMenu with at least 2 VInputs inside (type does not seem to matter)
2. focus on first input field
3. press TAB key

### Expected Behavior
Browser focuses on second input field

### Actual Behavior
VMenu closes and browser focuses on next element at activator level

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1v00AQ/SvDXgJSbFdqT1GKyg0OiAsSh7qHjT0mS/dLu2OnKMp/Z3btNo4rpApO9rw3+9583R/FJ+/LoUexEVtC47Uk/FhbgO1QSO/zbw4aZ0kqi2GCMrgj+xICfPNo4Sva/gxxjrkAADaNdhELZ7MkWioarZrH21p0UkesxTxZNqQGSS4w7WXg7Ev+oFraM3dzdeWf5tSsrLF8GdoL7AUtCJ9oQWUy4UWnULfAXbgWNRuZ+LMWoOUuR9/lDrrgDOwxcOUge3Kda/oI1T8qfoGDtATkYNSZhJdy2+pvxT8zMzBBaQvnzTFwXl1+cbHdhIzL31azo+AwNkF5gojUj7ehjHeB4AgBOziNw1jxPa1SOgDrRgJuEW5TxvvVZ9TawQ8XdPtu9SEZjJIsJtZiVCuM9OWv6Cwf5TGp1BMRa7GBjCSMXVJciz2Rj5uqalrLz3iqagilRaqsN9Udp1Wht6QMFq0zd9fldXlTtSrSHC4xmmIX3CFiYJFarGc2pLrfb7CaMucOE1TwemOyeCVdsd+AoeDTbnnV4a0dLZ7NPRfUq86S+6m2J563VvYxLkbdxDzm++ci/6vlLJaUHpLhaS1yIjuP34c/mQBqWA==)

**Comment by setaman** [comment]
Additionally, there is an issue with the form validation inside the menu. After (unintentional) closing and reopening the menu, the validation breaks and remains in the state before closing. User nightmare
