### ISSUE TITLE
[Feature Request] VDataTable add hide-default-footer, disable-pagination props

### ISSUE THREAD

**Issue by xyos** [vuetifyjs/vuetify#17651]
### Problem to solve
In Vuetify 2 we had `hide-default-footer` and `disable-pagination` props for VDataTable, Docs mention [hide-default-footer](https://github.com/vuetifyjs/vuetify/blob/cf05b0dcb9c9097808977107ad18a82c0da5415d/packages/docs/src/pages/en/components/data-tables/basics.md?plain=1#LL81C21-L81C40) but that prop is not implemented in the code in v3.3.4

example:

https://play.vuetifyjs.com/#eNqlVt9v0zAQ/leOCCmrtCTA+Fm1Ax5A4g0h3tYJeYm7GRzbsp1uo+v/zmcnWbN2bEH0obXvvrsvPt996ck6+WhMvmp4Mk1mntdGMs+PF4potsqYMXEZNzUTqtvFfcU8yzw7k7w3Ek0vOKu4dfNF0q0WycArQBB88XfoKbXUFg5jRc3s9dBVN9KLzGnrtzZ3oS8zxyUvB8YLUfGs4kuGgGyptef2L8720bbOSrhwjMywc6GYF1r1vqI/fjE4f9i0lZkVg4ph60orjCfHfWNIMnWOI3kcNIaVWjlPXVloTidt6jX94tdTSh0OA+b0kLzwksOS0ubwLsZrz+QA8T3sXY87Dc/Q88QSD1m6/HeZQvyUng+IHoC9GAc7Ggd7OQ72ahzs9TjYm3Gwt+Ng78bBnj/bXtCsaHsEHZEcJqI26Gt0lsl/Oq0wguuAw4BEBzpnStESbJjRsMdkeW/ctCjKSiGs4lKsbK64L5Spiw+AFbZRXtRoeF1/OMqP8pcFWtwPzTl3dXZm9aXjFkkWSXeQSOPFEiP4KFWHHDJ0pkyyMxco9lIX4Ftxm1muMAYYwpEn2gkbcu649k4W2DcLtUG9pVC/3E6pSxfL3M3Jfx45JuuuOhB+D7ryTV/eK7BQEm+plMwFTRwK6o8fHpW5FdsArGgFUQsaCa0kochYbVzeNVsOY1MrkNMUUtGicqyCoWeAKS65O8Bycoeg0/Qzr8AjltsENJ/PKd0+WsavDFNVGhILSA2QreULNjA68ZvD5momJbYrZgVTPuggv/KgDOIJll1qhxRg5tLxe+j7kaKbG3rS0iHVek2WXZ50yFPabDBd8A3rVvjqVsK9/TfJbocQs13q2jSeV7ShpdU1pbjNNEQLhZfMkpWcvobbaGf1VgmYukYXBFwryfHGIMl4DQnFY8Qsfh8fTHoMDgRET3hwMKH58c5VB2XPgbuNaQvyaJj7FHFw7+eb7CQLl7mfsPXlKyYbTu8pfYrSS2YcTwm697TrDKRaqGWjYvbwZh80XSzKpNc0i6Jb1e/CJ92ZgiqdkrcN7yRkD5K1fZ9lS3HFAzg0Q1w/GoGHwt+EQVgwfB4VqjT+KlSVUOdd6ANz0iULAnRX/TeHSVQRqET7e/oHlTkdzQ==

### Proposed solution
add `hide-default-footer` and `disable-pagination` for VDataTable

**Comment by xyos** [comment]
temporary workaround:
add an empty `v-slot:bottom` slot
```vue
<template v-slot:bottom v-if="hideDefaultFooter"></template>
```

**Comment by evan-hwang** [comment]
@xyos 

I also hide **Pagination UX** that way, but I couldn't find a way to disable **Pagination**.
