### ISSUE TITLE
[Bug Report][3.3.4]v-autocomplete: When VAutocomplete is in focus, using the up and down keys on the keyboard will cause VAutocomplete to lose focus

### ISSUE THREAD

**Issue by XieWeiJie** [vuetifyjs/vuetify#17655]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
- create a v-autocomplete with multiple and chips attributes
- enter the search text in the input box, such as the text 'b'
- all matching selections will appear below 'VAutocomplete'
- using the up and down keys on the keyboard, you will notice that the input box has lost focus

### Expected Behavior
Using the up and down keys on the keyboard, the input box will not lose focus

### Actual Behavior
the input box has lost focus

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUttugzAM/ZUoL92kQrTLE+qqTdpfjD6kYLRs5KIksK0V/z4noS2lD+0DMvaxfXzsfOzpmzF53wEt6MqDNC33sC4VIas+q7it43/ytPJcKLCkaTtxACJk9c/RHXNbgp97KenDY0knYIR553WlkQw8TCFC+kzqGlqs63nbgSvpOV4IHDK0jXaOtnwba9+h4V3r57DEmEDS82j1KYybhtYrdj7iVBtCKOwkHv2T+oSOa0pbDJG0xhWb7BddV1lhfMyCX6OtJ3Uam+xTt5p7XpC7e/KyJndjjJAovCAfi0brxZIsttwG04jdLrod2s3ykJ22WCAeslN0uI8/QxjpOARd0laob5d/Oa3wMUS+klYOl4xsqbKkn94bVzBW1Qoz8VKit7kCz5SRDJ+RF83f61P+lD+zWjh/CGV4GZfHZqHTplQDEgoZZGeSmxlrAiLzqBvfQwfBvzLCK6Yx2ykvJGS1ltNZJuEcnMy2eDgHFpuUdFxNpAkD30B1TS1SXLRmyNeDzSyoGizYWxXNyqacM+hC2XjqgQ5LGstw8clu/gHHR0CS)

### Other comments
When there is a lot of option data, I need to enter search text in the input box to match the options. Every time I want to select an option through the up and down keys of the keyboard and the Enter key , I have to use the mouse to click the input box to regain focus because it lose focus

**Comment by yuwu9145** [comment]
#17641
