### ISSUE TITLE
[Bug Report][3.3.4] Typescript,VDataTableRows: The type of the `isGroupOpen`  function in the type `GroupHeaderSlot` is not properly

### ISSUE THREAD

**Issue by quangquyen1410** [vuetifyjs/vuetify#17659]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.43
**OS:** Windows 10

### Steps to reproduce
Using typescript
Create a v-data-table component with a group-header slot.
Get the function `isGroupOpen` in this slot
This function return void.

### Expected Behavior
The function `isGroupOpen` return type is boolean

### Actual Behavior
The function `isGroupOpen` return type is void

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9Vk1z0zAQ/SuLObSdiWOYcsqknUILBcoAh146TQ+KvUlFZMkjySkh4//OSrYTJa37NQVfLO/He7tPsqTLZfS+KPrzEqNBNLSYF4JZPBxJgOE8zphlsWVjgc4AMJhqVRbxeHEwivzww2IUNa5rZBlqQ55mtPJwgnX2DI1BbdcOo7StwdxojZUKZlwCCpwzy5WM37YuhxXPmSiR/JLlWDt8wVRy2wC8riutS6HQpc/sQapEmUvTA6umU4GnLqoH3PjBjwIlVC0VoQ6tbpA9+qs4hvNrBI221BLsokBQk41sbmCueAZxHCaagkk4SgVPZ1RLQL3rqtobRUGwF56nSgK9JhQewK/C84zH6TXONWlTFsOkzuhAQWFwIyNTN/KOnGHi6gwMy6Xj63u5q6q1D5OVKjTcWDGEuV4yZNrw06dJNS+sj8XfBc05ZDhhpbCwrAFd9gB29+DgEHYbG0C9OgZwuYQZ0nvHTfxOD5SmyaVPZtIdqK56bXyzNIOEjHG9uCejWbKUEXQfqmm5FUiJJ/Uaht23b95MgYZzLqd7Oysg9zDBp5JijWXabrrC8kO7r9iJNoAJo+kKnFUwXq7qOCZNp8r3VGOma0PLjzKjJu9MP2n02FSnI3EtU/sHd+vkWiOET1r9ob/hQk3LbQnaQinqS4qQamT5ZoQvh9wXaELHRid3cK7QwDCZ3fD0+j8Rf6T9iutOsmOlZnxrvp/JdFwWKZttYQVUP5mxbiZfgOqU1jXqMYmUPauz7+opbF9RiAWMkcluMprUjtaexvVNCcELVfx7ps9K4iJV+biT6lxNJvgiCp4oWXb/aS+4MM64PWPdTPeI10nUbjDVnh/QSUNHUXtURL1IcDkz/V9GSbqk+JpGUWroHrHah+jSYW1hBkmSZpIiMxR8rvsSbSKLPKHrjeWTxdF+f7//Lsm4sa0pFmxs+h7MIV2NZEWEPHeHU5yzYou1dnjmRptRREju+4ESjigs0aW0PEc6gPOwlsDcR5PHY61uaJ8lkFHUSONpXMGPoHqoW6K4BZ24owx1rGnvR436sR1tpYWcW65bnTVTXUVVL/JpJHz9vvoLIaIQ0Q==)

### Other comments
The return type of the `isGroupOpen` function on line 32 in the `VDataTableRows` file should be `ReturnType<typeof provideGroupBy>['isGroupOpen']` but it is `ReturnType<typeof provideGroupBy>['toggleGroup']`. It looks like this is a copy error.

**Comment by perwramdemark** [comment]
Got the same issue..
