### ISSUE TITLE
[Bug Report][3.3.4] v-card style v-card--variant-elevated exists in any case

### ISSUE THREAD

**Issue by he-jialin** [vuetifyjs/vuetify#17650]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.3
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The v-card--variant-elevated style should not exist when the flat props is present. variant="flat" is correct to remove the v-card--variant-elevated style

### Expected Behavior
Remove the v-card--variant-elevated style when the flat prop exists

### Actual Behavior
The style v-card--variant-elevated exists in any case

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctOIzEQ/JVec8iuFI83JBeyA2Jv+wEr7YHh4MQ9i8Ev2c4AivLvtOchDeGChCz5Ud1dVd2+O7LfIVTdAdmW1RltMDLjTeMA6o7LEECr64bRpWE92uN777LUDuMIDaCMCrLOBqngL6bcMGiJ7QZqMUQngvJ8x1AQkqB7LWYe6JnyqxnsXBQzx4GhGvg472TU0mWOBjuqUVMCwM6/8PQglX/ewk9a6/ACF1erK5S7jVoSsLok5HJDGy/bGFu1vwaGUzloq8VkobjZRx0yJMyHYhZA2+BjhiNEbOEEbfQWFjTMRUkHoC5TBpv+w3XJ+L74g8Z4+OejUd8WP3r2npLI2JINbNzKUD0m7+hH+naaMZAatp0abBiplHfDHnIOaSvEXjkqU2h0FyuHWbhgxS2liXhwWVvkytvbdbWuNkLplOdwhcnyXfTPCSORNGw5k8m6ff2E1Jg5VxghbuQuFYkP1IL0Oow8olMYMX62o7OyueZZ6ENn47+eaN5Gu6d0Nup96sd8N5n8Uss9WWG6L4KnJesTSXk4798AF3snig==)

**Comment by KaelWD** [comment]
I don't know why `flat` even exists, it should all be in variant.
