### ISSUE TITLE
[Bug Report][3.3.4] v-data-table-virtual automatically scroll down to bottom when using v-slot:item

### ISSUE THREAD

**Issue by ngotrongphuc** [vuetifyjs/vuetify#17661]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
I'm trying to custom row of v-data-table-virtual using v-slot:item like example at https://vuetifyjs.com/en/components/data-tables/basics/#item, but when i scroll down just a bit it automatically scrolls down to bottom (last items)

### Expected Behavior
Scrolling down should works normally with v-data-table-virtual using v-slot:item

### Actual Behavior
When I scroll down, even just a bit, it will scroll to bottom, and I can't scroll up any more

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqllltzmzgUx7+KhraTZCYIfE3CJJl20r10uw/7uhN7pjIotjZCMJJw1/Xw3XtkBAGM2njqFwud209/IXQe996HPMfbgnqRd6tpmnOi6f1CIHS79ROiia/JilN/y6QuCDcGhKINJQmV6m7h2dHCsxYGOcy89f9IlaJSN/aYE2XMlNMt0SwT/qg2bShbbzTYpmFYz5ls/pbwgsK8ICmtDAc+IKx50RvjCC77QwQqF551MU6yGZun5H5feeE440UqFDZ5UVneBmBrooImDIYdWYIhXcDU8YNHFUuW60MM/T/PpEYJfSIF12hfJTZZInR+ge7u0bmdMzIcBI3Q4wt1YzQ/zTSnETqz0qLzURiuEQy3TKwvzi7bvoSztQBfpYnUXZMCIrOCCD0RrmjH9kx3EGR0aceUrfG+wXggPJOMqrPLphoVCTxVSeLa7Aj/ncAKDPZg9BPRrsAHIlfqB6GxsbuC/5GZpkz8IDyvPFwJPskMot+5ohmY26HLZpTYA+HeXyO7EUZm36hA/2bror91taYRGs1uOhbQK0JzHPbcQYkIjaedWbvACE177oYd6o+cWz8A+ymmKJaUpEgRkXxl8cZFPJ5cHRPfDBP3XFvEk18m/g2+REw6KefjY8qRS9guTYPZd7eYV6dgPhR5TJ47x7DNOQlnx5wT3NXNYs5PU/P6FMw/4NND5QreADgDDtTZ/PWSTruvdcM6wV1DvfPzU2D/opzv0IoS4WS9GpA1HEa9cRyrvrtFDU8h/TvjnOVZ7uS8GXhNQ9ydrDmvHZxDlONTKP/MBN3FWbpyYU7Dbm37lg5iXjve0jnubokFnc5OIf2YicL5LZ3OBsQcz4Z3fTZyHabBF3R8kqCfmf4MF5+DczYaUHPsOEjzrmoNZ1dlS+k4RfXlVV7YAex1XmiaRC/0vXYPmprWwiTVhRToEWP8QUqyMx1LGF5guCvBc4lTkp8z0wV1xIgzoUzPVHU5d3D5QrzeMIXrO/SRoXdoFC6h32vFWWvV1t2hL2/37ZkSvXm7Z+UX06K9xFhC69gS4aIe13JU/1DwNmgaPO/S40w8K/yfygT00YdlLLxYQdvb3PPQKmudqygI4kSAZ0I520osqA5EngbQgWv2tHs/wRM8DRKmdD3lc7JS+JDMZFouRAkFWWpaSh+k61WtDIfKVk5oxgtonKOfIbwHt0AWQrOU+kmWtlla05iq1F/J7CtIBUkWnlXmUMYAv6LUz1YLJY5SB6bFpdKX0GhRSeVrV9QLa9fsmY5WZre69MpL7xAGwlf/y++JDJZt)

**Comment by rojobo** [comment]
The real problem is not that it scrolls all the way to the bottom, but that you cant scroll back up more like the items of the table are lost or truncated
