### ISSUE TITLE
[Bug Report][3.3.5] Tables aren't respecting show-select in Composition API

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#17663]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
It seems that the show-select property in a v-data-table does not work in Composition API.  I do not see a playground for Composition API but a bare bones case would look something like shown below. 

```
<template>
  <div>
      <p>Show? {{ myTest.length > 0 }}</p>
      <v-data-table
         v-model="selected"
        :headers="headers"
        :items="desserts"
        item-value="name"
        :show-select="myTest.length > 0"></v-data-table>
  </div>
</template>

<script setup lang="ts">
  import { onMounted, ref, type Ref } from 'vue';

  const myTest: Ref<string[]> = ref([]);

  const selected: Ref<object[]> = ref([]);

  const headers = [{
    title: 'Dessert (100g serving)',
    align: 'start',
    sortable: true,
    key: 'name',
  }];

  const desserts = [{
    name: 'Frozen Yogurt',
  }];

  onMounted(() => {
      myTest.value.push('test');
  });

</script>
```

### Expected Behavior
show-select to reactively show/hide the checkboxes

### Actual Behavior
show-select is not reactive and will not show the checkboxes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

### Other comments
If instead, I create a function and try to call it (aka :show-select="getMyTestValue()") I get the following error in my Chrome console:
Invalid prop: type check failed for prop "showSelect". Expected Boolean, got Function

**Comment by nekosaur** [comment]
> I do not see a playground for Composition API

not sure what you mean by this, the [playground](https://play.vuetifyjs.com/) uses composition api

> show-select is not reactive and will not show the checkboxes

are you sure you're using the latest vuetify version? this was fixed here https://github.com/vuetifyjs/vuetify/commit/6987695f2ee6045712ee47e829c20100611aa406

and it's working in the playground on latest version https://play.vuetifyjs.com/#eNqlUsFu2zAM/RVNl7RAbHfodjHSIAOG3XbaaYhzUGzG1SJLhkS76AL/eynZbpS0hwI92eQj3yMftT3xH22b9h3wnK8QmlYJhHWhGVv1iWjb8BuCSqBIUOwVjCnG+qQxFaiHgjtQUCJUBZ+x/BFEBdYROP1FmCQhj1TgHFiMII8kvVAdEKxFA1GXezRPyajkJSn6E4K5ZL3K4inPk+9Rs02pZHm86GMP7EvMskZT1wo8C3WMHtD/aMIqi8yh0JVWtsgcYDd6JJvWWGQnZvRv02kyY8ksHNjADtY0bEEWL3wnY6XRjjrjOajw5iCUg9uLksnVqWC7u0AnWwncjpueZqdQooKcLX6O9rKbr3d3NbHZXur6drGc64SStaY6h8LiOe1oD29gztB28Jo+wjPV+pvMpUP47uKh5ou+M5XvJIJf1vwHzf6aujuLvjKtstFYspQv+ehp0og2/eeMpica2IoJoHeTz/wFJ4N9TO8NsXV5lpWVpjZ6oLK3qQbMdNtkGyrLLN1HNpBUptncp/fpt6ySDuN0Cq5J9tY80TZEUvBp0CCD8vD8AampMih8HxWmVKLE3nmJN9SZvxLYxIKm44L96EZXbfFWV9Cbzbz6UOiB/FZSH92V1aULNk/X/OTKgWw69cCHJQ9zknJo4LsXJAR/CA==

**Comment by UglyHobbitFeet** [comment]
I thought I was using v3.3.5 but it turns out I was using v3.3.4.  It is fixed and working as expected. Thanks!
