### ISSUE TITLE
[Bug Report][3.3.5] v-show=false doesn't work simultaneously with class=d-flex

### ISSUE THREAD

**Issue by vessi-devs** [vuetifyjs/vuetify#17666]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Create a div with v-show and class="d-flex ...".
Set the v-show bonded value to false.
As a result, the div will still be visible.

### Expected Behavior
When v-show=false, the div should become hidden.

### Actual Behavior
The div is still shown.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMtO5DAQ/JWWL3MZxwd2L6MsYv+BG+GQR0djsB3L3Qmg0fw7bWdA0SAkJG7u6q4qVz2c1P8Yq2VGdVA1o4+uZbxtAkC96DbG8ixDPwVubcB0gQQc7AKLpuP08q9RnGZs1O390RLkhZ+JoUNYLNnOYVUbQb/hjq0jIUPvWiKZBz06fIUnkbDjmyZuE4v2Bxng00UEZjeEXbHKagG6mcEyDBNS9Wm3Ma/NdZiMrFlrs+lARuqTjQyEPK9VWB+nxHCChCOcYUyTh53Ut8vc9Vru1F6th9q3sXqiKUi9p8xvLgtq1AEKkjERyHOjjsyRDsb0QxDagM4uqQrIJkRv7uTMpDmw9aiHyd/dVDfVH0lGvIUrJK+7NL0QJhFp1H5jk/v8gdXlsjj8XR0ukHZtR9nii7QRvwWTThgGTJh+muiKtk11tfqSLLufm3CWvp0Nz3RVdU+l5oePT/4qchHLSo/Z8LxX5Z/iXAjq8R2Ghxpe)

**Comment by KaelWD** [comment]
https://github.com/vuejs/vue/issues/3761
