### ISSUE TITLE
how to group events for v-calendar?

### ISSUE THREAD

**Issue by Giovanniricotta2002** [vuetifyjs/vuetify#17660]
### Discussed in https://github.com/vuetifyjs/vuetify/discussions/17657

![Screenshot](https://github.com/vuetifyjs/vuetify/assets/115021221/0467e41d-12aa-4efe-9638-7b3d57e7e7ec)

Because I would like to group them by color but I can't since it's sort by order of appearance as in the image where we see that the color "blue darken-1" is not with the group which is at the bottom of day 19.

for it is possible to move it or group it with the others since the basic events are grouped together</div>

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
