### ISSUE TITLE
[Bug Report][3.3.5] VIcon does not work with svg path

### ISSUE THREAD

**Issue by taozhiyu** [vuetifyjs/vuetify#17667]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
shown in reproduction link

### Expected Behavior
work normally

### Actual Behavior
no icon shown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVE1v2zAM/SuCMCAdEFvAug/Mc4sU2GXnDr1UPbg2Y6uTJUOSnRVB/vuojyRu1mIBdjFE8uk9kiJ9v6XTCE6sn/MnSwsq+kEbR7akNlA5uIsxsiNro3uySNgFVwdg34ibutajckt/vhOw+V7Z7lFXplmi43YAaHQPDsyehtMVBtiT5fQbV/A7MNVaWUeSALl6mcDFlitCXAc9FKjZwLoapfsZ7YUUbecWZLf0IOGJEOTPhFRSVBaONnpissU88X1smicfEC/L2ePssaaAmtWYMDEX/92954ou6c0w5Fgctrh00A8Sa7v2kHLKqmEIR0KkrhqhWmKnNtRBwBiNEggKZuG/V5weU+f0umQxmjjKzhB2wpe68CpnonyX+nIe4Ua4jtxO7Q/PYMe6BmvXo5TPRbozZVjD20kTV7XoQkzS26NjT9ARm1KyWbPQtLURgyMW3Bh79soYHoY1DRkOKwnTpSXkUrcXRyg+TckiJ7LhK0W6rK8GXAet8LXC3PAUwIE9TBL3i+NtTjvnBlswVjcKrzUgxWRyBY6poWcrhDGDYqKHDIdkdZlf5h9ZI6ybu3OwffZo9MaCQRJO0yAFGb8CZ0glZFD4FBWSK5PVo/USf1Ez1JvAZAZUAwbMuRWdXJtXdRJ6u7LDX+DfkhG5+pJ/yL9+ZmgFprBjuGLh7aRQv+zJs9U2sN/vFf+rfYHMMz2gJN0taagZlcMF+vAHW+fMfw==)

### Other comments
It seemed to be working properly before, but I didn't found the versions worked on the playground
Configure according to the documentation:
https://vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg

**Comment by KaelWD** [comment]
You're missing `defaultSet: 'mdi', sets: { mdi }`

**Comment by taozhiyu** [comment]
I did it locally and it didn't work.

![image](https://github.com/vuetifyjs/vuetify/assets/49258735/6d4cb831-9e30-4e99-8f10-f99b93b970df)


Meanwhile, I tried to add to the playground too.

https://play.vuetifyjs.com/#eNqlVE2L2zAQ/StCFLKFWIJuP2jwLlnopeeUvaz34NgTW1vZMpLsdAn57x19OHHSLKTsxUijN++N3oz8tKNDD1ZsXtmLoQsqmk5pS3ak0JBbeAxnZE82WjVkFrGzrD0Am1I8FIXqWzt360cB2x+5qdcq16WPrDqAUjVgQR94lhjnL2bKk0uRGzA+5VyPi0K1BqzheIhJ8McnuaAlEUPuTmu+2WUtIbaGBhZIX8Im76X9FfYzKarazsh+7kCeHUFuTUbkCizinJ7HEOL0HZOvL8Zi0YdcQhhj403GUB7sWUytGs+GqV0ecWrgiDNHEz1qYmrEhJLcd/8xa+mcPnQdQ2+wqamFppNozb2DpEOSd51fEiJVXoq2ImaovA0EtFYogSC/XbjvXUaPpWf0PuXhNHKktSb8jC96cJEzUn6IvlxHuBW2Jquh+ukYTF8UYMyml/J1EXOGBO/wdtHE5hWGEBP1RnTwBAPBlJRPzMKtKbTorGt+Hzy7MPgXxpr44VQSmFTVzRGKrUl54EQ27FKgS5q8wweoWuyWH6UsHpiMHoYrc0/V7TNaW9uZBedF2WJaCVIMmrVgeds1fIkwrlFMNJDgkCxv2S37zEth7DTMwDTJWqutAY0kGY2D5GXcC7pCKiK9wpegEEOJzNfGSfxDzVFvAJ1oaEvQoK+90Vna9FZnR2/fLDboGsmAXH5jn9j3r+6/c9Gjkz/TfxsmxfqEgDVOw79jfMZ+PqRof5uz0SiMv8HTWMu7WuTJHNMzStL9nHpfUdkn0Oe/vuEUaA==

**Comment by taozhiyu** [comment]
@KaelWD would you please recheck it? thanks.

**Comment by KaelWD** [comment]
Literally in the section you linked

![image](https://github.com/vuetifyjs/vuetify/assets/16421948/5d61d3f1-9f3c-44d2-bfd9-ef81dc0fe829)

**Comment by taozhiyu** [comment]
> Literally in the section you linked
> 
> ![image](https://user-images.githubusercontent.com/16421948/247922824-5d61d3f1-9f3c-44d2-bfd9-ef81dc0fe829.png)

Yes, I have import it, but it does not work.

both locally or in playground

**Comment by LuWa-at-work** [comment]
Same Problem here 🙃
