### ISSUE TITLE
[Bug Report][3.3.5] fields are broken

### ISSUE THREAD

**Issue by yurks** [vuetifyjs/vuetify#17668]
### Environment
**Vuetify Version:** 3.3.5
**Last working version:** 3.3.5
**Vue Version:** 3.2.47
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Steps to reproduce:
- use fields components as usual with vuetify@3.3.3
- update to vuetify@3.3.5

### Expected Behavior
Field components heights and composition remains the same across minor version change

### Actual Behavior
Field components heights was unexpectedly changed and component inner value placement is broken at least between VTextField and VSelect 

### Reproduction Link
[https://codepen.io/collection/pgerpe](https://codepen.io/collection/pgerpe)

### Other comments
Don't you need more testing, guys? Latest update just break the existing app ui, can you compare it at least visually?

#### 3.3.3 -> 3.3.5
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/80b368ea-056c-4cc3-9426-d33b3929d540)

**Comment by yuwu9145** [comment]
#17607

**Comment by yurks** [comment]
> #17607

VSelect alignment is only half of this issue. Another one is changed default heights for all VFields. That is related to https://github.com/vuetifyjs/vuetify/pull/17175

**Comment by yuwu9145** [comment]
As per #17175, input height is adjusted in order to accommodate chips and selection slots

**Comment by yuwu9145** [comment]
Duplicate #17405 & #17604
