### ISSUE TITLE
v-icon in v-breadcrumbs-item not displayed correctly

### ISSUE THREAD

**Issue by DrSensor** [vuetifyjs/vuetify#1766]
I don't know if it's counted as a bug but I think its strange

### Versions

Vue: 2.3.3
Vuetify: 0.15.7
OS: Ubuntu 16.04
Browser: Chrome

### What is expected ?

Breadcrumb divider icons should aligned/vertical-centered with v-icon

### Reproduction Link

https://codepen.io/drsensor/pen/rGOOjv

**Comment by johnleider** [comment]
Breadcrumbs is going to get bulldozed and rebuilt for 1.0
