### ISSUE TITLE
[Documentation] Copy failure

### ISSUE THREAD

**Issue by taozhiyu** [vuetifyjs/vuetify#17664]
### Environment

**Browsers:** Chrome 113.0.0.0
**OS:** Windows 10

### Steps to reproduce
(On all pages with code block)
click copy button of any code block

### Expected Behavior
Copied successfully

### Actual Behavior
Copied successful, but the context copied was `undefined`

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/installation/](https://vuetifyjs.com/en/getting-started/installation/)

**Comment by KaelWD** [comment]
db1af6e2

@johnleider the code prop is optional, there's also a slot

**Comment by johnleider** [comment]
fixed in https://github.com/vuetifyjs/vuetify/commit/291e0223c477903cdfcd7d0a7943893ec704a4a0
