### ISSUE TITLE
[Bug Report][3.3.5] goTo service is not importable

### ISSUE THREAD

**Issue by vessi-devs** [vuetifyjs/vuetify#17665]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
According the docs (https://vuetifyjs.com/en/features/scrolling/#use-with-router), to try to import it:
` import goTo from 'vuetify/lib/services/goto'`

See the console with the error indicating the failed import.

### Expected Behavior
Be able to import goTo.

### Actual Behavior
Can't import goTo as told in the docs.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkM1uwjAQhF/F8oULiQ+0FxQhqj5Ce8McQrKAi//kXagqxLt3bdIKhQsSt2S8M9/srs7yLcb6dAQ5lw2Bi7YlWIgGY+sXHwCC9iDeg8dg+TuIbg/doYjb1ljohXExJGpUMYhG/Wdor32DXTKRBAIdIytiGBe78BnENgUnJswms/1R1mwUQjqZDlDtAoUJ+9U1gK1yKq/eyrWx/sLgufE5R+rhAbWci6JkjWPzv5Z7oohzpbres60Ha06p9kDKR6eWPKbS0ZNxUPXBLWf1rH5RvUG6lWtAV21S+OaCHKLl9AaT2z+AGiYL4fVKGKTKthvMiLvochBIVQLfQ4L06EYj2+1Wo6e7zTL9ov2F722NP+Do1B2WM6/+Sj61cgnLSesMvExl6cnkYpDrX8Kz5jY=)

**Comment by vessi-devs** [comment]
The issue still shows up in version 3.3.6.

**Comment by crussell42** [comment]
Seems unchanged from 3.3.4 to 3.3.7.
Shouldn't the function just be exported there in services/goto/index.mjs?

export function goTo(_target) {

**Comment by akselh** [comment]
I still get the same problem with v. 3.3.15. Would be great if someone could have a look at this.

**Comment by jthuraisamy** [comment]
Also getting the same problem with v3.3.19.

**Comment by jthuraisamy** [comment]
This is no longer an issue for me as I'm using the browser-native [`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method mentioned [in this comment](https://github.com/vuetifyjs/vuetify/issues/16471#issuecomment-1561844998).

**Comment by KaelWD** [comment]
#13538 #16471
