### ISSUE TITLE
[Bug Report][3.1.12] SVG not rendering on VCAROUSEL succeeding pages

### ISSUE THREAD

**Issue by kiefferganza** [vuetifyjs/vuetify#17675]
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.3.0
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a vuetify carousel that has an svg content. the carousel must have multiple pages

### Expected Behavior
The svg's on the succeeding pages should render

### Actual Behavior
Actual svg isnt rendered

### Reproduction Link
[https://codepen.io/swannykg/pen/wvQzjaL](https://codepen.io/swannykg/pen/wvQzjaL)

**Comment by KaelWD** [comment]
`fill="url(#linear-gradient-empty-star)"` is not unique
