### ISSUE TITLE
[Bug Report][3.3.5] How set value in VDATEPICKER i set new Date() is not works

### ISSUE THREAD

**Issue by adeari** [vuetifyjs/vuetify#17673]
### Problem to solve
How set value in datepicker becausei set 
new Date is not work get this error
TypeError: props.modelValue.filter is not a function

### Proposed solution
<datepicker v-model="dateValue" />
<script>
const  dateValue = new Date();
</script>

**Comment by adeari** [comment]
On the first openned when set model keyboard then set date by write the date
click ok
value is null

**Comment by KarlNilsson** [comment]
`model-value` takes an array as its input. Doing `<script> const dateValue = [new Date()]; </script>` should work.
See https://vuetifyjs.com/en/api/v-date-picker/#props-model-value

**Comment by marcodelgatto** [comment]
Hi Karl, I've tried with the array but me too I'm unable to make the v-model work; anything seems to be passed to the picker.

Can you share a complete sample of data binding using "script setup" ?

Thank you !

**Comment by marcodelgatto** [comment]
Thank you !

**Comment by marcodelgatto** [comment]
I didn't realize that v-model gets modified only after pressing the confirmation button :)

**Comment by adeari** [comment]
> Hi marco,
> 
> [See here](https://play.vuetifyjs.com/#eNqlUTtv2zAQ/isHLpEBiXSRdjHkIAG6dOrg0fQgS+eWjfgASSkIBP338qEEir0EyELwjve9jseJPBlDxwHJjtQepekbjw9cAdRj1RiTrqlotfKNUGiXVmp2Yboyon1GC2MldYf9nhP5+jP0OQH2Bme3+No8HLDH1mMHkWYH05QuT+7grVB/YJ5rlg1EfDZTs5XJULrWCuPBoR/yqJBGWw8TWLyU0Gpphqgww8VqCXch6V0EQnhSzkO2Cvs4XhwVvkCsi81ps576YGv/zloUG9gvcTIRHZt+wOP2RL3+dfidEcWGuuHs8n1bwrdtIAcIR82y/8BBSpKtV7Ix9J/TKvzIFOf48uA4CTvKapyEILHm5K/3xu0YazsVYOEDxGipQs+UkewxjDE7KC8kVp2Wj/f0nn5nnXB+3aboZHW2+sWhDSSclCsZLy6vn5BaJpPCj6ywtKq+ObsocUPNgt6ItrKoOrRoP5voCrZOdfV0kyyqz1zNYd+9UM/uatWtS2s+vpn8UuREFplOUXAuSfIZlBOAnP4DxvwsIA==) I hope that's what you're looking for.

I click pencil icon to set date by keyboard but not works
i change the date in textfield here then click Ok
date is not cahanged maybe help this

How to hide pencil icon in heder?

thank you  for help

**Comment by qxygene1** [comment]
https://play.vuetifyjs.com/#eNp9kMFugzAMhl/FyqWbVCDQMQ1EkfYOPa3pAdG0ipaEKAlcEO8+Q9SpvUSyovj/7PiPzzNxts++jUmnkZOaNJ4rIzvPW6YBminpjNmuW9IP2ndCcxsUgHaeQbk7LMtDwaortidG9L/cwpSo4crlkREsYwTUKL0wkqNgO33njLRN9tLymIbq/7hgBpXgpsmeXGLqeiuMB8f9GMwKZQbrYQbLb7DAzQ4KdvjB3VoOgO86v/k+rhVvZ2CkoEWZ0EOS01OR15RipJTSH0b2zzSP0iJKD1H6EaVllH5G6depoHVZYaRVVSGFy/u6xLA2XBhZ9nqUcjsuf8p+k7g=

same issue when multiple="range"
