### ISSUE TITLE
[Documentation] Broken link

### ISSUE THREAD

**Issue by vitoranacleto** [vuetifyjs/vuetify#17683]
### Environment

**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
In "Sass color pack
While convenient, the color pack increases the CSS export size by ~30kb. Some projects may only require the classes that are created at runtime from the Vuetify theme system. To disable the color pack feature, follow sass variables
 and set $color-pack: false." the link "sass variables" is not working.

### Expected Behavior
Link to a page with more information about sass variables.

### Actual Behavior
link to a not found page

### Reproduction Link
[https://vuetifyjs.com/en/styles/colors/](https://vuetifyjs.com/en/styles/colors/)

**Comment by MajesticPotatoe** [comment]
Old link left over from v2 docs. Thanks for reporting.
