### ISSUE TITLE
[Bug Report][3.3.5] When I change the date language to Turkish it does not select the date (datepicker)

### ISSUE THREAD

**Issue by eguvenc** [vuetifyjs/vuetify#17689]
### Environment
**Vuetify Version:** 3.3.5
**Last working version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.51
**OS:** Windows 10

### Steps to reproduce
I tried to add language support to vuetify date picker component. In default language (en) there is no problem but when i change the locale for example Turkish ("tr") It set to input "Nan Nan Nan"

### Expected Behavior
It should set the value to selected input 

### Actual Behavior
It set to input "Nan Nan Nan"

### Reproduction Link
[https://codesandbox.io/p/github/eguvenc/test/](https://codesandbox.io/p/github/eguvenc/test/)

**Comment by KaelWD** [comment]
Duplicate of #17615

**Comment by eguvenc** [comment]
Hi, Is it  fixed, If yes, which version should I use?
