### ISSUE TITLE
[Bug Report][3.3.5] v-file-input model gives an array when "multiple" attribute isn't set and when it's set to false

### ISSUE THREAD

**Issue by vessi-devs** [vuetifyjs/vuetify#17687]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Run the reproduction link.
- Put any file into the v-file-input.
- Its v-model will change to an array value. Its first element will be the expected file object.

### Expected Behavior
The file object must be returned immediately without being inside an array.

### Actual Behavior
The file object is returned inside an array.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs2OwiAQfpUJl9XEloO7l6a6etlkn0E8YEsju0AJ0BrT9N13oGvS6EFPwDcz38+Ew0D21uZ9J0hByiC0VTyILTMAZZ81UolMGtuFCAAofhJqw8gX4jDhZKr0mW7rVIszN7TQnQrSKhFxrvx/YVvSOXdS+/YgA3AD3Dl+/YRhgH285dKncxH7lzCOzJR05hOfvnLSBvAidDZxSW1bF2AAJ5oVXHiozjBC41oNb5j0LfZUrfEBIilsYt9iGYknKiQhK6Kk+fX5j28NrmaIM4xU3jNSwGGKx8g5BOsLSqvaYCcuQPYuNyJQYzVFqSCb626dr/MPWksfblCGi/R5IotMR2ZGFJxsZ5rbO9WpkJQTEjFkiu8nFnbYRl1ngtQiq1udvLxPXmZwLrzOTq69eOGQhJHVTCYafkHqWVqUeKCmqNcLlzlhauGEezXR3dg81V3pIVlUxz80knFF0hguPlkmxz8K8wgB)

**Comment by vessi-devs** [comment]
The obvious workaround is getting the first element from the array... but as the multiple feature is not explicitly requested, it's not desirable to deal with an array.

**Comment by vessi-devs** [comment]
The issue still shows up in version 3.3.6.

**Comment by umutcantopal** [comment]
still exists in v3.4.0-beta.0

**Comment by dkl520** [comment]
still exists in 在vuetify": "^3.4.9

**Comment by orieuxe** [comment]
still in 3.5.1

**Comment by bontrager-dev** [comment]
I just upgraded to 3.5.10 and noticed this behavior is fixed now. (The fix broke my code because I was still treating it like an array!)

**Comment by KaelWD** [comment]
Duplicate of #19297
