### ISSUE TITLE
[Feature Request] [Bug Report][3.3.5] VDATEPicker pencil icon for input using keyboard

### ISSUE THREAD

**Issue by adeari** [vuetifyjs/vuetify#17694]
### Problem to solve
When click Pencil icon, type date using keyboard, click OK, Date value is not changed to date that i write.
How to hide pencil icon?

### Proposed solution
Because enter date by  keyboard is not work well so  i need to know how to make it able work or hide the pencil icon

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
