### ISSUE TITLE
[Documentation][3.3.5] Fontawesome SVG aliases using `far` errors

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#17696]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Setup fontawesome per https://next.vuetifyjs.com/en/features/icon-fonts/#font-awesome-svg-icons
2. Use a component (ex checkbox) that uses a fontawesome alias using `far`
3. Notice icons using an alias that is using the `far` or `regular` icons do not load

### Expected Behavior
The default aliases should use the free icons instead of `far`.

### Actual Behavior
Icons do not load and it will cause errors.

### Reproduction Link
[https://codesandbox.io/p/sandbox/falling-firefly-tg5rht?file=%2Fpackage.json%3A15%2C5](https://codesandbox.io/p/sandbox/falling-firefly-tg5rht?file=%2Fpackage.json%3A15%2C5)

### Other comments
I have read multiple issues about Fontawesome and svg etc, but I haven't seen anything that specifically addresses the use of the `regular` icons (not part of the fa free version) in the icon set aliases. I'm not sure if this is a known issue or not. I know some of the fa free icons are less than optimal versions of what mdi has, but by default shouldn't it use the free ones to prevent errors?

**Comment by KaelWD** [comment]
`far` is free, looks like you also need `@fortawesome/free-regular-svg-icons`

It's been like this for years, not sure how it's only come up once before: #9995

**Comment by webdevnerdstuff** [comment]
I'm so used to using the pro version at work, I completely forgot about the free regular svg icons.

As for a solution, I guess the documentation just needs some minor tweaks.
