### ISSUE TITLE
[Bug Report][3.3.5] VDatePicker - invalid prop "range"

### ISSUE THREAD

**Issue by torerik123** [vuetifyjs/vuetify#17697]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
VDatePicker with range prop => Invalid prop: custom validator check failed for prop "range"

### Expected Behavior
Ability to select date ranges

### Actual Behavior
Error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkMFuwjAQRH8l8hnbUqEXlCL6HZiDibetIV5btpOqQvx7106RUjjALRnvzpvZ3Zm9hyDGAdiatRlc6HWGjcKmaUfeeczaIsQqVCn67+Y4pGw/ft4US0F3wHX0AxrF/qbqnCEbHmx3gthAD6PO1iNtvKwUa6LGT9i08t/YlUEqQaYI9D3P0MpZQrZgvcVTEsfkkdKfy4ZiXUqKrZvd5KbYV84hraXsDNKkgd6OUSBkicFJ6l2abJdiKV6lsSlfJd7rQxLVrDjtFV4IaF3wMXOnww11eqjkqhSNnMr/gwhbGpNxwGwdcONdzbKassxkAcnxAx0mQSQTxRYzTAn8BOpRW0LcWUvijRB5BDQQIT7b6GZt3urm6a5ZoV/KvS8LVtfo8DUy2/8CNjLnjg==)

**Comment by KaelWD** [comment]
This is all very early alpha, range is currently a separate component.

**Comment by sametaylak** [comment]
@KaelWD I cannot import VDateRangePicker from labs. I'm using Vuetify@3.3.9 and it says

![image](https://github.com/vuetifyjs/vuetify/assets/11059505/db7dfb44-2e9d-4aaa-bbbb-44bc885bd978)
![image](https://github.com/vuetifyjs/vuetify/assets/11059505/8d15045b-cbd5-4ccc-91cd-9f19153712dd)
