### ISSUE TITLE
[Bug Report][3.3.5] Chip closable doesnt remove div.

### ISSUE THREAD

**Issue by NiackZ** [vuetifyjs/vuetify#17692]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Turn on developer mode in the browser and go to the "Elements" tab
2. Click on close icon in any chip

### Expected Behavior
Div with the "v-combobox__selection" class will be deleted

### Actual Behavior
Only the content of the div tag with the "v-combobox__selection" class is removed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVMtu2zAQ/BWCh8YGLAlF2oubBumh5xbIoSiiHChpbbPhC+RaTWDo37skJVtxgia6iNznzHDJuwP/5lzZ74Gv+RWCdkogXNeGsau+aK1ubGMf45axvtC2A/W15u1OulDzbF5LSgtkTf/JmkPyUoHwolGQt0o0qchvu/dsI3rrKZHtbNNIOKbrvULpphTnwYHpCtlaQ5m6k8VGKgRf9MJLYXBKG7cUE6yy2ZrIEJ2JHPEIyuI6gIIWZap4YALRhxWLHFYsu6Y/dGyo+Vgm60Lkpm3UpZGmoyqpxgQlSZMEI5BqDxHTWG4e0iobTtrE76ZVsn04hs+Ds2sdc2I9D9r2sIiYl6ewI1CCGtBbs70+HBIxNgxX1Wj6YJrgvsxDnTDXC2lIVQi4pMBoOJKuMutJzOrZqLyibgxOwmZFSSB4fE1GEkCEOD3aFx9rnqfjqAohj/klSlQQ0f8PRfKOE0uGZ17ahtZLhykSHp31yDrYCJozdsjlOoFisZx2jHnAvTen/TjUa3Z3sjB28dPbrRdaS7O9WD33KPFEVtbLDizbCg3hLOKXQKpJIXSQNP1n3lsF4M7K3s/W6cIRnItb9CAyAHbxXWBcnQKHvBjIMF4uwJ3tKHNG9TRJc8K4k6FMrMvgaPZgMbOkM/2xyVkr9nF5bDi2zn9qT8M0ic9XXEnzEMo/wRp6c1IzelECXZyjsjXfIZLSVdV2hiLpEsnelwawMk5X9Fqh3DzdXJaX5eeqkwEnU0HjQ/BisVjpvjYDNZQ6HnehhTvrmh2p80i65lQp7t+AcENhld8blBqKzuqE5VPGMjOXEHTRePs3gKciNR+VSW0i4He0eosttXhRuqJ+PT2Pnl5Nus/+vYzO0uaszlwvmI1HPfBhxVMaCZ8g8/t/CNYLpw==)

### Other comments
https://imgur.com/a/K48T2Qu

**Comment by KaelWD** [comment]
Your slot isn't actually being used

https://play.vuetifyjs.com/#eNqNU01v2zAM/SuCLtmA2MbQ7RJkRXfYfUAPw1DnIMdMolVfkBg3heH/Xkqy8+Ee2pPFJ75HPlJ+6vkv58ruCHzF1wjaKYFwXxvG1l2xtbqxjT3FkLGu0LYF9bPm24N0oeYZXkmiBULTd0JzSj4qEF40CnKoRJNE/tmjZzvRWU9EdrBNI+FM10eF0k0U58GBaQu5tYaYupXFTioEX3TCS2Fwoo0h5QSrbEaTGbIzmSMfQVlcxQ4psWex7yWTpoXTkkpZF9hQ85GW50CpRGsohxgppebkS4ToW/viG4XJF4E2RK/3fR91S5SoYBjWVVaZmqluRx1vx1lngByTQp4ii/QI1OaGR2HYeukwUeDkrEfWwk7Q7FifC7UCxZevU8SYBzx6c4nHRa3Y0wVhbPHH270XWkuzXyxvb5R4JZR1sgXL9kJDmGX8FUialKJtRxud3T4qADeT3Vyd0yOidhaP6EHkBtjit8B4uiQO+TAkgIJ1dR4FX3IlzXMo/wdr6FUnr/RmA+3s7LPmB0TyXVXb1lAmvWvZ+dIAVsbpiv4HlLvXh7vyrvxRtTLgBBW05lAmsai0qc1ABaWOwy+0cLOq+SJVHmdec1KK8QctPFBa5Y8GpYaitTr18j33cgWXEHTRePsSwJNIzccRpTKx4U+U+sgtlXgnXVG9jn5AT/8lePCfdTSjXbuaXb1zNq564MOSJxoNPrXMN29qVo49

**Comment by NiackZ** [comment]
My bad, thanks
