### ISSUE TITLE
[Feature Request] [Feature Request] [3.3.5] Click Date number only then datepicker set value

### ISSUE THREAD

**Issue by adeari** [vuetifyjs/vuetify#17695]
### Problem to solve
How Click Date number only then datepicker set value so no need click OK and  OK and header is hiddden

### Proposed solution
How to make Click Date number only then datepicker set value.
Hide Header and footer so Pencil icon is hide and Ok button is hide

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
