### ISSUE TITLE
[Bug Report][3.3.5] VSelect Menu positioning incorrect on first open inside navigation drawer

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#17698]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Go to that URL.  
- Open the navigation menu.  
- Open the select, notice the menu positioning is incorrect

If you close/open it again, it will be positioned correctly.

### Expected Behavior
The menu to open in the right spot

### Actual Behavior
It's opening offset to the right initially.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVc1O4zAQfhWTCyDhBInlEpWK3QO3ve2NcHCTaevFsS170lJQ333HTpomKQjYXmrPz/fNr/P4lvy0Nt00kOTJDKG2SiDMC83YbMNL4ap4jjcldqbB7k6SM86D2O88+fGFcKw0yri7IqkALLeNswpYJdwzaH5TJPNZNrSeM84JrIfbcGHtCMY6WQu3KxJmnamlBn1kHzpwLTZclqbHCr+NcFJoJBiEFyySoe6+VLJ8Tj0aG6J1YguO3bGz9jS0jTFPaQZRxzDQGBX0KFHB/PeOLaUCHzzHmombt6IE11alPU4MFqhP0mAhALrVleS1WGm5pPpEDLL+LgDFiSHf//WvDHq+AYeyFGoE00EcizfuNFVSrgRKo3lX/Q2vTQWqbwcRhWk0jgZg3HQlPbJcktaTdfzvqIPmpMigoDy1Z9koyJN4xuHWQmrmcaeAENYgV2vM2e31tX0h5hFd2BgeCjUQM/ZnDexIwbqUt1IpRuUBGvklDThDMlsYRDqSla+FUmTm5SsMwXzpALRPB7yUwSlxkIbADwscCnTc4IMPXWbZYO/pSgTStlbwQh1AVsFSNArZWwtVCRQ5u7hkd3N20clIGrPK2VIoD1cH6cqZxuZMN0r1stiDnD0eM+hBwi8uS87OH4w5733alVZNUCzHiv3g/C7QL+HeB6K5/BbQg3x9/SCkiebzmJqPoBYTzRHqqTvtL+nQHrcCy3V+pIjlps4MOHEtfdq/cbE7B+UBuv3fh1Hom59cJUrqZ5/+9UbTxyEiFknpaXv63tE2IFqfZ1lZabKkDZYbl2rATNs6o88K0gN1f5PepLdZRet5ENEoLnwawQLSU6H3RCjDwiNNrZ2wtorI3GVWJIQU7p+EcE9mmWs0yhrovapjLD/aWAbiFDx9lJzZenAEUiRdZSJNCPgLVJ9lSxQn0Bnx0QPKHegKXHj2vpbRxG2Y1UR1klnX6n2yv0qiGxU+hpw8/QNU8noB)

**Comment by drhouse82** [comment]
Does anyone have insights or a workaround here?

**Comment by sathishsundar05** [comment]
For now please use vuetify: "3.1.0",
only this version solves
