### ISSUE TITLE
[Documentation] Clipboard got "undefined" when copying code by clicking the copy button

### ISSUE THREAD

**Issue by lomirus** [vuetifyjs/vuetify#17703]
### Environment

**Browsers:** Firefox 115.0
**OS:** Mac OS 10.15

### Steps to reproduce
Scroll to "Installation", find "yarn create vuetify", and click the copy button near it.

### Expected Behavior
Copy "yarn create vuetify" to clipboard

### Actual Behavior
Copy "undefined" to clipboard

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/installation/](https://vuetifyjs.com/en/getting-started/installation/)

**Comment by KaelWD** [comment]
Duplicate of #17664
