### ISSUE TITLE
VSpacer using the CSS utilities directly

### ISSUE THREAD

**Issue by seanogdev** [vuetifyjs/vuetify#17702]
https://github.com/vuetifyjs/vuetify/blob/a36926d7b584ccaf802155d5fad255c985d3c99b/packages/vuetify/src/components/VGrid/VSpacer.ts#L4

If we choose to turn off the utilities from the SCSS file, VSpacer wont work.

**Comment by KaelWD** [comment]
98cf8e54357ba03a81857971b25820b07369fab5
