### ISSUE TITLE
[Bug Report][3.3.6] VDialog SSR breaks `$vuetify.display`

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#17708]
### Environment
**Vuetify Version:** 3.3.6
**Last working version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
VDialog with SSR breaks `$vuetify.display.` all variables return true when they are not.

### Expected Behavior
To return the valid display variables.

### Actual Behavior
Returns true for all display variables.

### Reproduction Link
[https://stackblitz.com/edit/github-acro4t?file=nuxt.config.ts,package.json,app.vue,layouts%2Fdefault.vue](https://stackblitz.com/edit/github-acro4t?file=nuxt.config.ts,package.json,app.vue,layouts%2Fdefault.vue)

### Other comments
I am using Nuxt and it works well only when using it with `ClientOnly` which renders the element on client only.

**Comment by KaelWD** [comment]
SSR doesn't know the window size, assumes 0 width

**Comment by ElYaiko** [comment]
> SSR doesn't know the window size, assumes 0 width

Yes I know, so will I have to use always dialogs with the ClientOnly component?
