### ISSUE TITLE
[Bug Report][3.3.6] Prefix & suffix are not aligned in v-text-field outlined variant

### ISSUE THREAD

**Issue by ngobinh105** [vuetifyjs/vuetify#17719]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set up v-text-field component with variant outlined, and add suffix & prefix. 

### Expected Behavior
All the suffix, prefix, and input content should be aligned

### Actual Behavior
suffix & prefix seems not to align with input content

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkU1uwjAQha8SeY1jVaAuUFpRqbfALAyeCLexY9mTEIS4e8eOUFJYwNLf/Lz3xtsL+/K+7Dtga1YhWN8ohE/piqLqeYDoWxdND8WhUTF+SGYHrjpsJSusGvjJaDwSXa5WkuWpPIcwIK8NNHpERbG2xlHfm2Q3gmcPRFxn9xAm3Kg9NMS/u6DQtG6q9CoY5ZBqbYeNcaCnWuzq2gxU0uocJ3wzbZzvkP+X+qzE3OgYmdCUmVAlZidhC0ayv7H8ia2jc13SiGSHSIrrYjuuleyI6ONaiIN21KmhMX0oHaBw3go6NJr6vFmWy/JdaBPxhjglj2VeljbtpLuSoLG+Dcit8neqYyErZ5IYbUrvJxY21CZC59BY4Lq12ctq9DLDJUTL96E9RQi0RLLFTCYZfkHqWVqSeFgtSK+HQP/gNIT0X68luhubp7orPSRL6td07+uC5TE6fLbMdn9zfQm/)

**Comment by yuwu9145** [comment]
https://github.com/vuetifyjs/vuetify/pull/17607#issuecomment-1611156076

**Comment by K3NGitWork** [comment]
The fix doesn't seem to work properly the suffix is now outside of the textbox:

Reproduction Link v3.3.7:
[https://play.vuetifyjs.com/#eNqNkU1uwjAQha8SeY3jtlSqFKWISr0FZmHwRLiNHcuehCDE3TtxhJLCApb+5ue9N96c2Zf3edcCK1iJYH2tEFbSZVnZ8QDRNy6aDrJ9rWL8lMz2XLXYSJZZ1fOj0Xgg+vb6IlmaSnMIPfLKQK1HlGWFNY76XiW7Ejx5IOJau4Mw4VrtoCb+3QaFpnFTpVPBKIdUa1qsjQM91WJbVaanklanOOGraeN8i/y/1KoUc6NjZEJTZkKlmJ2ELRjJ/sb8JzaOznUeRiTbR1Isss24VrIDoo+FEHvtqFNDbbqQO0DhvBV0aDTVab3Ml/mH0CbiFXFKHvO0bNi0le5Cgsb6JiC3yt+ojoWknMjAaNPwfmBhTW0itA6NBa4bm7y8j15mOIdo+S40xwiBlki2mMkMhp+QepSWJO5WC9LrINA/OA1h+K/nEt2MzVPdlO6SDeqX4d6XBUtjdPhkmW3/AF8dCbo=](url)

The working sweet spot seems around a width of 230px. However it seems to work with v3.3.5.

**Comment by yuwu9145** [comment]
> The fix doesn't seem to work properly the suffix is now outside of the textbox:
> 
> [Reproduction Link v3.3.7](https://play.vuetifyjs.com/#eNqNkU1uwjAQha8SeY3jtlSqFKWISr0FZmHwRLiNHcuehCDE3TtxhJLCApb+5ue9N96c2Zf3edcCK1iJYH2tEFbSZVnZ8QDRNy6aDrJ9rWL8lMz2XLXYSJZZ1fOj0Xgg+vb6IlmaSnMIPfLKQK1HlGWFNY76XiW7Ejx5IOJau4Mw4VrtoCb+3QaFpnFTpVPBKIdUa1qsjQM91WJbVaanklanOOGraeN8i/y/1KoUc6NjZEJTZkKlmJ2ELRjJ/sb8JzaOznUeRiTbR1Isss24VrIDoo+FEHvtqFNDbbqQO0DhvBV0aDTVab3Ml/mH0CbiFXFKHvO0bNi0le5Cgsb6JiC3yt+ojoWknMjAaNPwfmBhTW0itA6NBa4bm7y8j15mOIdo+S40xwiBlki2mMkMhp+QepSWJO5WC9LrINA/OA1h+K/nEt2MzVPdlO6SDeqX4d6XBUtjdPhkmW3/AF8dCbo=)
> 
> The working sweet spot seems around a width of 230px. However it seems to work with v3.3.5.

resolved in #17753
