### ISSUE TITLE
[Feature Request] v-data-table

### ISSUE THREAD

**Issue by Eyeofthequeen** [vuetifyjs/vuetify#17712]
### Problem to solve
1 - You do not allow translating the entirety of the content of v-data-table. It takes a lot of effort to be able to translate the 'of' in the pagination.

2 - Pagination/footer is 'mandatory'. There should be an attribute that allows to have no pagination.

### Proposed solution
1 - Everyone that doesn't work in english or has to make bilingual website will thank you.
2 - It would be more suitable for all types of tables that we might want to have without having to use v-data-table-virtual, which should not be a workaround for an incomplete component. Additionally, it would avoid having an empty template to achieve the same result.

**Comment by KaelWD** [comment]
> translate the 'of' in the pagination

https://vuetifyjs.com/en/api/v-data-table/#props-items-per-page-text
https://vuetifyjs.com/en/features/internationalization/

Just set `dataFooter.itemsPerPageText` in the languages you're using, or use the included translations. 

> should be an attribute that allows to have no pagination

#17651

**Comment by Eyeofthequeen** [comment]
No i mean no 'bottom' at all. Right now I use :

```
<template v-slot:bottom>
<div/>
</template>
```
But i think there should be an attribute for that. Something like :no-footer="true"

Also for the pagination, you again didn't understand the need.

You have a no-data-text, you have items-per-page-text, you have items-per-page-options: does are all attributes that allows to personnalize easily the text. BUT items-per-page-text it to vague. It includes the numbers but the numbers are not translatable, so why isn't an attribute that directly consern the 'of' from that text ? I have succefully translated what I needed but it's not optimal and could be way better. Maybe something like items-per-page-text-link ...

**Comment by KaelWD** [comment]
My bad there isn't actually a prop for "of", it is under the `dataFooter.pageText` i18n key though. 

https://github.com/vuetifyjs/vuetify/blob/faab3326272d54ed9535d53fe0099e72372f03e8/packages/vuetify/src/locale/es.ts#L27

**Comment by KaelWD** [comment]
It isn't a workaround, most strings in vuetify components can only be changed that way.

> Please make an attribute to get rid of the bottom of the table when needed

There's already an issue for that: #17651

> Please add something that will allow to easily change the link between the current page and the total pages.

I don't know what you mean by "the link"

**Comment by Eyeofthequeen** [comment]
The 'of' that's what I mean. Since items-per-page-text won't be actually used to change the numbers, there's should be an attribute that allows to change strictly the text between {0}-{1} and {2}. I don't se the value of items-per-page-text if you have to rewrite the same syntax and change only the 'of' part. Does it make since ?

**Comment by Eyeofthequeen** [comment]
Anyway... Thank you for your time. I'll take it as a sign of life and progress from your end.

**Comment by Eyeofthequeen** [comment]
I just realized why there was confusion. I mistakenly mixed up 'items-per-page-text' and 'page-text.' The 'items-per-page-text' already functions as intended.

My feature request was regarding the 'page-text' and suggesting a 'page-text-link' that would only modify the word 'of' in that context.

I apologize for any misunderstanding caused. English is not my first language.

@KaelWD you were doing your best to demystify my demand. Again, I thank you for your time.
