### ISSUE TITLE
[Bug Report][3.3.6] error-messages of v-text-field doesn't show all messages anymore

### ISSUE THREAD

**Issue by Kolobamanacas** [vuetifyjs/vuetify#17711]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Windows

### Steps to reproduce
1. Make sure, Git and Node.js are installed on your machine.
2. Clone repository and navigate to `vuetify-error-messages-bug` folder in terminal.
3. Execute `npm i` to install dependencies.
4. Execute `npm run dev` to run a project.
5. Open simplified website using provided URL (usually something like http://localhost:5173/).
6. Notice that `v-text-field` prints all error messages passed to `error-messages` prop, namely `Field is required.` and `Field must contain more than 8 characters.`. This is expected behavior and everything works fine in old version 3.0.1 of Vuetify.
7. Now go back to terminal and stop application execution with `CTRL+C`.
8. Execute `npm i vuetify@3.3.6` to install the latest version of Vuetify.
9. Execute `npm run dev` to run a project again.
10. Go back to the website and refresh the page. You will see that now only one of two error messages is printed.

### Expected Behavior
`v-text-field` to print all messages from `error-messages` prop.

### Actual Behavior
`v-text-field` prints only the first error message from `error-messages` prop.

### Reproduction Link
[https://github.com/Kolobamanacas/vuetify-error-messages-bug](https://github.com/Kolobamanacas/vuetify-error-messages-bug)

**Comment by KaelWD** [comment]
> everything works fine in old version 3.0.1 of Vuetify

That was a bug: #16197

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/ is much easier than a repo btw
