### ISSUE TITLE
[Bug Report][3.3.6] Textarea: not converting ascii to characters when using v-model

### ISSUE THREAD

**Issue by gvg356** [vuetifyjs/vuetify#17717]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just open the codepen

### Expected Behavior
Expecting that ascii code for less than equal will convert to ≤

### Actual Behavior
displaying the ascii code and not converting to the special character

### Reproduction Link
[https://codepen.io/gvg356/pen/RwqpewY](https://codepen.io/gvg356/pen/RwqpewY)

**Comment by KaelWD** [comment]
Uh yeah that's how `<textarea>` works
