### ISSUE TITLE
[Bug Report][3.3.6] Vuetify + NuxtIcon: Vue warn Slot "default" invoked outside of the render function

### ISSUE THREAD

**Issue by alniv1234** [vuetifyjs/vuetify#17718]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
The warnings are produced when the icons are hidden then display like in vTabs and vMenu.

### Expected Behavior
Should have no warnings

### Actual Behavior
Produced [Vue warn]: Slot "default" invoked outside of the render function

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-fnzdtw?file=app.vue](https://stackblitz.com/edit/nuxt-starter-fnzdtw?file=app.vue)

**Comment by KaelWD** [comment]
https://github.com/nuxt-modules/icon/issues/42
