### ISSUE TITLE
[Bug Report][3.3.6] V-Radio-group isValid

### ISSUE THREAD

**Issue by simoneeek** [vuetifyjs/vuetify#17720]
### Environment
**Vuetify Version:** 3.3.6
**Last working version:** 2.6.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Expected Behavior
v-slot should not break group functionality

### Actual Behavior
v-slot break group functionality

### Reproduction Link
[https://codepen.io/simoneeek/pen/jOQmEzJ](https://codepen.io/simoneeek/pen/jOQmEzJ)

**Comment by KaelWD** [comment]
You're putting all the v-radios in the group's details slot.
