### ISSUE TITLE
[Bug Report][3.3.5] DatePicker missing some locales

### ISSUE THREAD

**Issue by petrprikryl** [vuetifyjs/vuetify#17728]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Using local provider cause fall:
```
<v-locale-provider locale="cs">
  <v-date-picker></v-date-picker>
</v-locale-provider>
```

### Expected Behavior
It should not fall.

### Actual Behavior
```
Uncaught (in promise) RangeError: Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at format (vuetify.ts:260:10)
    at VuetifyDateAdapter.format (vuetify.ts:376:12)
    at ReactiveEffect.fn (VDatePickerControls.tsx:54:22)
    at ReactiveEffect.run (vue.esm-browser.js:494:19)
    at get value [as value] (vue.esm-browser.js:1451:33)
    at Proxy.<anonymous> (VDatePickerControls.tsx:78:68)
    at renderComponentRoot (vue.esm-browser.js:2284:16)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7102:46)
    at ReactiveEffect.run (vue.esm-browser.js:494:19)
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUUtuwyAQvYrF2sAi7cZyo/QccRaOmagk/ASYtop89w64rRxnkeyYx5v3gf2VvDvH0gikIW0E7VQfYduZqmqFTNWg+hDeOiLoScFXdR5DlKdvOoCJ4DtSiEhNVNmhV0Cdt0kK8NU84+YQ/mmFKFCfOjlcwG9bfjv/qiG6kpsDcUyEp5YvcpKaKGkugZ2DNdjhmpnZFW2baj8rduQjRhcazgdhkClAyeSZgciN0xzb51a7DduwVzQJ8Q+iqj8GVsSy0qEzExpK7ayPVPdu5TpfFOeCZAyV8vwgwg5p3I8mSg1UWF2yvMxZFjCDoOnR288AHkU6Ui9scuAnrB61RYs7aY5+CTz1YPA38s8/12i1tmy1urprlt2n/N5TTcoaPnyJTA4/n0/p9g==)

### Other comments
I know that `DatePicker` is still in _labs mode_. But would it be possible to enable missing locales? At least the `cs` one please?

https://github.com/vuetifyjs/vuetify/blob/439eeddf43caac4c191356d03125bbf733d39c85/packages/vuetify/src/labs/date/date.ts#L44

**Comment by scottafraser** [comment]
@petrprikryl looks like the Czech republic uses Central European Time, you should use:
`<v-locale-provider locale="cet">`

**Comment by torerik123** [comment]
> 

`Vuetify: Translation key "$vuetify.datePicker.ok" not found in "cet", trying fallback locale
 at <VSheetheight=undefinedmaxHeight=undefinedmaxWidth=undefined ...>
 at <VPickerlandscape=falsetitle="Select date"border=false ...>
 at <VDatePicker>
 at <VLocaleProviderlocale="cet">
 at <App>`

**Comment by petrprikryl** [comment]
@scottafraser Hi, thanks for your advice. But it is not fixing my formatting problems. For example:
* Start of the week should be Monday
* Selected date should be formatted as `7. 4. 2023` instead of `7/4/2023`

You can check [Slovakia version](https://play.vuetifyjs.com/#eNqNUUtuwyAQvYrFOsAiVReRG6XnCFk4ZqKSAEYMdltFvnsH3FaOs0h2zOPN+8D+yt5DEEMPbMPqBC7YJsFW+aqqtRmq1jaIb4ppfrLwVZ17TOb0zVvwCaJihUjUgduubSzwELvBaIjVNNMmXv5phahJnwfTXiBua3k7/6oRupCbAklKRKdaznKyFbPGX1CcsfPU4ZqZirWIim2q/aSo2EdKATdSttoTU4M1QxQekvTBSWqfW+3WYi1eyQTTH8Rtc0RRxLLSQfmRDI0LXUzcNWHhOl0U54JkjJTy/CDCjmgy9j4ZB1x3rmR5mbLMYAHo+DF2nwiRRBRbzWxy4CesHrUliztpSX4DRB7B02/kn3+u0WJt3mpxddcsu4/5vccVK2v08CUyO/wAtEzqAQ==) which works pretty well and is very near to Czech formats and locales.

**Comment by KaelWD** [comment]
non-`en-US` is currently broken anyway: #17615

you can set overrides in the createVuetify options

@scottafraser it's locale not timezone
