### ISSUE TITLE
[Bug Report][3.3.6] VDatePicker selection does not reflect external changes to its model

### ISSUE THREAD

**Issue by basuneko** [vuetifyjs/vuetify#17726]
### Environment
**Vuetify Version:** 3.3.6
**Last working version:** 2.6.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In either single or multiple dates mode,
1. Select any date(s)
2. Press OK to write the selected date into the model - you should see the date displayed as json
3. Press Reset to clear the date - the date string at the bottom should disappear

### Expected Behavior
The selection in the datepicker gets cleared

### Actual Behavior
Previously selected date stays selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVE2P2jAQ/SuWLwvSJj5stQeURbtqe2m13VU5Eg4hGcDFcSzbyRah/PeOnUAD4euwByQ8M+/N85txplv6olRYlUBHNLKQK5FYGMeSkKgK0kLahEvQhGdPMeVSlTYoTbKEmJKFKHnmK32tLj7aQwsVBH8GYY8x3Wcwt3oYT7hcCiAZtiJ5kUHEMNgpqQKXChRP19i7ClyNQCbjcd8w9+5Try6OUhiCD+BzK8lzKrBoj/oNBqyDohr/P2K+7hCa8Wr8FW+tCzEi2y35MXn7FRqrkYIvNoOTAoakriPmkPv7IzVevkN9zZHXUliuWk+MN4UMdCKXMLzVnLyl6Nuzy1zxaVf2KU6dUXPJq92p2aQLi9V1o0vlA2U37SOCjycgILUkkRtvcMQw1q9612AMeftJbEE+NMflTFduBO5sV82qiotYb5crTwUk+jJopf08jom+/1UoFbKRRxsvHLLmrXDpg+5/O/4lWNM0g+yMspfUlgnO6Ai5BlDGB5WGihelEZvDdj2+iB2Ye9scd5n2S4KRiHW+M3g0qebKYm9bKiLQcNxFa9onwnNVaEu2RMOC1GShi5zc4efqrtkQ5DUIPfUsyZPDRC46nY0H09mwgSxKmVpeyBa13/bBkGwb8SfpwioRJSDpdOaq6m7/M8t+VUHvxf3XcIayryJijX/oFr2ngsu1Cf+YQuL33FPFNDVo5ohMG+KYrqxVZsRYmkmsRFJe6VCCZVLlDK21+H6fH8KH8BEHbOwuFIhkbkJP5piwf40Nm/kEeaKOujYJ37m9UkyRyZ2vSHjGMqZLaXkOQVbkXsuXRksnHILJgzkumQGNJDG977Rxgm9ode222KJHzbBfBTrQIDPQoG+90RGse6ujVO9m7ahrWt9TD0PjvWQ6+wcDKIMN)

**Comment by nekosaur** [comment]
It seems to work fine in the playground?

**Comment by basuneko** [comment]
@nekosaur 
> It seems to work fine in the playground?

Made a video, this is what I'm seeing:
https://github.com/vuetifyjs/vuetify/assets/505411/eb4e49fc-ce3d-4eff-9d60-417058bfedf8

I'd expect the selected range in the datepicker to get cleared when I click reset and the model gets reset, but it remains.

**Comment by johnleider** [comment]
The **multiple** prop is supposed to be internal. There will be a component specific for range date selection.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
