### ISSUE TITLE
[Bug Report][3.3.6] v-hover fails after unhovering a grand-child-component

### ISSUE THREAD

**Issue by HendrikJan** [vuetifyjs/vuetify#17738]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0
**OS:** Ubuntu undefined

### Steps to reproduce
* Open the reproduction.
* Move over the `v-card` and see that `isHovering` turns to `true`.
* Move over the `v-btn` and see that `isHovering` is still `true`.
* Move from the `v-btn` back to the `v-card` and see that `isHovering` turns to `false` (this is the issue).

The reproduction contains a "v-btn", inside a "v-card", inside a "v-hover":
```vue
<template>
   <v-hover>
        <template v-slot:default="{ isHovering, props }">
          <v-card v-bind="props">
            <v-toolbar>
              <v-toolbar-title>Hovering: {{ isHovering }}</v-toolbar-title>
              <v-btn v-bind="props">edit</v-btn>
            </v-toolbar>
          </v-card>
        </template>
    </v-hover>
<template>
```

When hovering over the `v-card` the `isHovering` variable is correctly set, but if you move your mouse over the `v-btn`, after leaving the `v-btn` the `isHovering` variable turns to `false` even if you still over over the `v-card` component (which is inside the `v-hover` element).

### Expected Behavior
The `isHovering` prop is always true if you hover over any component inside the `v-hover`.

### Actual Behavior
The `isHovering` prop turns to false if you hover and unhover over a child component of the child of the `v-hover` component. Even if your mouse is still inside the `v-hover` component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVMFu2zAM/RXOF69AZAPr0IORdt2wAd1thwE91D3INhNrkyVDotMVQf59lJysrp1DgSGH2BTfe+Sj6Id98rnvs92ASZGsCbteS8Kb0gCsd0L2fXyML7U1JJVBdwzFYGt3kwCHThSwE15bKhrcyEHTdZnsQfm7kK7MdgW9s72HQ5lMwKOMdA2DK2UaBsW0WVJMI2t1JafS8yNBijRCraX3zET4h0R7xVynIgrYT2uCw2Gdz9BMf0agokUUoKitto6FJoyfIK30gCkUkG4dPgutti2hER/SMllSsN1oGqHYaebpGiU0ykZwsFb6HGBu0zLjBhtFoa0zNc9NfWl+aXeYiggWLgz/4WylsYMnRS1Qi1Amx2tRJkByW6yr5ZTuWzQQk4JN4f8fNCiVyer4/mIms+2kU5LFeGhQW+ewJv0MHgnIci65AcskO6f3ZaAVyA2xzlL129fvP6EaiKyB9y5MiPn6i7MlsLK3Hbb26aS7kdrjai6IO25QbSJFPThvXYSS0vpcu1nAl3T6hVGcd/x0Ml25/NXanrKmmxlRr9Y3RMbtfgXnV1871VPobhiXX3W9dQR7cLiBA2yc7SDlD0Y67gbzeoLOb+E6ZLxP71BrC/fW6eZdehEERkomS1bJyCY62We/vDX81dnH3o8HfIl5Lceq2Z4w0IIfWqLeF3leN4ZhDWq1c5lByk3f5beclrvBkOpQNLa7vcwus495ozxNwxn6TlTOPnl0TMJ3bCJDavP8BqljZlS4GhWOIaFl5YPEgjpnPR6FcLzb6MJavK2jGWza1exo0VlQP5TmwH5rZX77mdW1jzY/nIr8r5YjWWB6DIKHVRLrZOUISB7/AsmR/zg=)

**Comment by KaelWD** [comment]
You've also done `v-bind="props"` on the button.

**Comment by HendrikJan** [comment]
> You've also done `v-bind="props"` on the button.

If I don't use `v-bind="props"`, the hover doesn't work at all.

**Comment by HendrikJan** [comment]
Oh, my wrong :-(.
Thank you a lot!

**Comment by HendrikJan** [comment]
Appropriate tag: `layer 8 issue` :-)
