### ISSUE TITLE
[Bug Report][3.3.6] v-slider keyboard change desync of track thumb slider in safari 16.0

### ISSUE THREAD

**Issue by lioumens** [vuetifyjs/vuetify#17734]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
On Safari 16.0, tab focus the slider, and press the arrow keys. Both vertical and horizontal have this issue.

### Expected Behavior
The thumb slider and track should move together.

### Actual Behavior
The thumb and bar on the track will desync when you press the arrow keys. The thumb slider will look buggy and bounce back and forth.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMFOwzAMhl+l8rlNmIY4VAWN51h2yFojAo0bJVkBTX13nKyTqu4yaTfnj/1//r0/w7tzYjwh1NBEtK7XEd8UFUUzVtq5XOZHO1DUhtDPUhZDbzr0hTX0quBJQWH1L1ebVIaIjmux4VpefeTaKCkXTiMXfCjBWDf4WFntxFcYiBc8pwE1fwQFdZGVpHGC9FbwGaMLtZRtRzzWYW9GLwijJGfljtukP1E0FqtusLut2Ipn2ZkQl7LAYKujH34CejZRUC4w0Xz83YGaOzPh5UKYparXx5AQN9aSeSP6yiPxVdHfm2g1tky1+rpJluiToonv3Rv6DqtTtyGfeX9d8qHI2Sw5HRJwKiHvyeQ8AId/pb7YvA==)

**Comment by KaelWD** [comment]
https://bugs.webkit.org/show_bug.cgi?id=137511

**Comment by lioumens** [comment]
thanks, that's good to know! Are there suggested workarounds for this visual bug? It's unfortunate this bug might show up for many of my users. Otherwise we can close this issue as it's nothing to do with Vuetify.

**Comment by KaelWD** [comment]
Not that I know of, feel free to open a PR if you find one.

**Comment by KaelWD** [comment]
You could disable the transition I guess.
