### ISSUE TITLE
v-select with clearable changes the prepend icon to cross upon item selection

### ISSUE THREAD

**Issue by iampawan31** [vuetifyjs/vuetify#1773]
### Version: 0.15.7
I am using prepend icon for `<v-select>` with `autocomplete` and `clearable`. When i select any item from the dropdown, prepend icon changes to cross.

**Before Selecting**
<img width="959" alt="screen shot 2017-09-17 at 11 10 42 am" src="https://user-images.githubusercontent.com/8089511/30518399-b128c1e0-9b9a-11e7-9954-b839511897bd.png">

**After Selecting**
<img width="953" alt="screen shot 2017-09-17 at 11 11 08 am" src="https://user-images.githubusercontent.com/8089511/30518400-b12ada66-9b9a-11e7-9f90-ac6e8c3e9333.png">

**Demo**
https://codepen.io/warlock9895/pen/QqjgEd?editors=1010

**Comment by KaelWD** [comment]
Happens on text fields too https://codepen.io/anon/pen/WZQOrG?editors=1010

**Comment by jacekkarczmarczyk** [comment]
PR https://github.com/vuetifyjs/vuetify/pull/1774

**Comment by tsauvajon** [comment]
Thanks for the fix, but the PR forces the clear icon to be appended.

It would be nice to have a choice here (prepend or append the clear icon)

**Comment by johnleider** [comment]
The functionality is only some sugar on top of what you can already do now. I'm leaving it as appended as that is what is within spec, but you can easily add it by using **prepend-icon="clear"** and **prepend-icon-cb="yourMethod"** to clear the value.
