### ISSUE TITLE
[Bug Report][3.3.6] V-date-picker: Typed date reverts to the initial value until ok is clicked

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#17743]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Open developer console.
Click on edit button you will see input to write date. change year or something you will see warning. 

### Expected Behavior
Warning shouldn't be

### Actual Behavior
We see warning

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUEtuwjAQvcrIm4KE4wVVFwgqKvUWmEWIB9UQf2Q7QRXK3Tt2ihTBAnae5zfvM7sr+/K+6jtkK7ZOaHxbJ/yUFmDd88bZVGuLoQAFCu4Cpy4mffzdSBZ93SCvg+uskuyfVXiKZLjXzRkD9Nw4hS3xMyoZiJueKIKjHb2nfmsxSUNjbIL2CSKmzpcFbbwLCa4Q8AgDHIMz8EZF3jIdgLRigmwIm0yZ7Sxe4Jvm2Xw/z/qjImmxBWu1PcfqFJ2lO1zzvmRNjJKtYDdmlewnJR9XQjTKEpMK6T5UFpOw3ggyzjfZLqtl9SGUjukG8bY+xKqIZaW9tAMZjum5qf2d6/hRnAuSMVLK85MIW6KJ0NmkDXLlTMnyPmaZwBVGww909oiBRCRbTGxy4BesnrUliwdpQX49Bh7QKgwYXm10tzZtdff10Cy7D/new4KVNTp8icz2fxrLAM8=)

**Comment by KaelWD** [comment]
The warning is gone in 3.3.12 but the typed value doesn't update until you click ok

**Comment by KaelWD** [comment]
Date parsing has been removed in 3.4.0.
