### ISSUE TITLE
[Bug Report][3.3.6] v-select doesnt respect disabled key in prop items

### ISSUE THREAD

**Issue by dkarnacewicz** [vuetifyjs/vuetify#17746]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open select
2. There are 3 options 
3. First option is disabled as declared in script but in Select this option is available to select

### Expected Behavior
Cant select disabled options

### Actual Behavior
Can select disabled options

### Reproduction Link
[https://codepen.io/dawid-karnacewicz/pen/JjeyNRK](https://codepen.io/dawid-karnacewicz/pen/JjeyNRK)

### Other comments
Should work like here
https://codepen.io/typerory/pen/LgNpWw

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/upgrade-guide/#v-select-v-combobox-v-autocomplete

**Comment by dkarnacewicz** [comment]
@KaelWD so to make it work I did

      <v-select v-model="name" :items="items">
        <template #item="{ props, item }">
          <v-list-item v-bind="{...props, ...item.raw}" />
        </template>
      </v-select>

because props doesnt have disabled key, is it right way?

https://codepen.io/dawid-karnacewicz/pen/JjeyNRK

**Comment by dkarnacewicz** [comment]
Okey, now I understand. Thank you for this link.
