### ISSUE TITLE
[Bug Report][3.3.6] Release v-date-input component which already in codebase

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#17744]
### Environment
**Vuetify Version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Code of component already exist but in roadmap and tickets I didn't find a way to use v-date-input.

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/labs/VDateInput/VDateInput.tsx

Could you check and release if it working or not.
Thanks for everything

### Expected Behavior
expect to have it in documentation and work

### Actual Behavior
code exist but vuetify says this component not found

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkLGuwjAMRX+l8twkA09v6MR/EAYgRgQat7JDEUL9d5JQpKosSIy+tu/x9eYBPvQdRxV2vT5LR9DAw1JV2akhFpqqKFkbrphrC6cYe2mMOThKaw5bP7AmjIb6YNZpzPCVog+oXBfWK73Sf8Z5iXNZowS15+4myMnEQj3DRH+8f4GaJgvh/0WYJNXu9pIRH9Ym8QZkxUgOGfnbRIu1eapF6yNZpo+WRqih9XSRxasPUt68eR/5U+Rilp22GTjWUO5M5LIA2ycSJqmE)

**Comment by nekosaur** [comment]
This is not a bug. The component is not ready yet.
