### ISSUE TITLE
[Bug Report][3.3.3] v-radio-group   There is no initial value at the beginning 一开始没有初始值

### ISSUE THREAD

**Issue by 202252197** [vuetifyjs/vuetify#17758]
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.2.47
**Browsers:** Edge 114.0.1823.43
**OS:** Windows

### Steps to reproduce
No initial value was selected at the beginning, but the first value can be automatically selected as the default value on the official website, I do not know why
一开始没有选择任意一个初始值，但是在官方网站上却能自动选择第一个作为默认值，不知道是为什么
Ask for advice, thank you thank you thank you
求大佬指点，感谢感谢感谢

### Expected Behavior
可以默认选择第一个
The first one can be selected by default

### Actual Behavior
可以默认选择第一个
The first one can be selected by default

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1U81u1DAQfhXLl4K0jktBQlptUXkHbk0PaTJbDP7TjBNYrfbSGwiEhMQJnqF3DjxOaXkLxkn6s1shVbRVTp75/sYZ7y/lyxiLrgU5lbMELtoqwYvSCzHrFFaNCeoIQxtFp1xowO6WMgI6Q2SCf7WIUErhKt9UKeBCYHjXc6/YoqtsC8zaZmAdbMCs0GK0zByxjL5wZhuyIU1tdQj2ss0AShj8kahtRcQK1NY1ECmV4H1iod+fPvz5enL+8fjs+OdMD+Ardb02WC6M6f4V9smDhj3/8uP087d7C7vzoGHPvp+c/vrPsJenYYe4tkaYUY0mJkGQ+qYQxsWASSwFwlysxByDE1u8nFu5aSGJ9d0Tuxn4aPtxFh7EWEZO5KCjXBWLNxQ87/YyK5Rjg0o5FX0l11g/n0v5OqVIU63rxjONl910WHhI2ken9ximsfXJOFBNcHtPi53i2XPdGErX6wWQU4f8EAiQVUo5ueaTzHxxC68RyRb8DQ5jSfHvo2xxQ1qzXweoEHwDCHjbkTZoa2Nt9G6Mlu1XpV/xjVvj39LGZdfUX/T+Rco7zdyLZaWDbLiayCEoW/cMefAXlM2k2g==)

**Comment by KaelWD** [comment]
`0` and `"0" ` are not the same
