### ISSUE TITLE
[Bug Report][3.3.7] Autocomplete - Strange flicker as menu closes

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#17759]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
* Create an `autocomplete` with a large number of items, say greater than 100
* Filter down the results to just a single hit and activate it with the keyboard

### Expected Behavior
The menu closes cleanly without any flickering.

### Actual Behavior
The menu briefly extends back to it's default height (showing 6 items) and shows the very first items in the menu.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstuwjAQ/JWVL6WCxKhUqpSGin4H4RCSRbhNHMvepK1Q/r1rJzwKF6Se7H3MzM7a64N4NybuWhSJSAlrU+WEb5kGSLsoNyZcQ1A0mnKl0Y6poaOlpmgYhYSQKCZwy0yEMxMgj2h5DfeZgT2VF6ocusIqQ6EJv01jCUrc5W1FcBjIvFxLWCbHBEDQmzyeEwA8EFh0HreE9eZc2DUWJr6quDB/5SOFp7m/TKd/GGDEx6Z1+8kBSFGFCTzkDzAFNYMur1qOFfSPZ1DvPZzx1Fo90hzT/Wy4DSf3p/JkWcyEqr3nqM5N/OEaza8SRuKdhgJv9eQ7E/xsPs7Ensi4RMqi1AwrsVKdjTWS1KaWK26TttWkaozKpl4t4kX8LEvl6DIdo6ujrW2+HFomycQ4aJAhtfu5Q2rsDAovg8KYiqp867zEDbVkvQ5tZFGXaNHe6+gKdunqqnTjbNx8z/uulP50V6suXFjz+jjkvywHMs/Ef7AX/UyEOVk5AMTmFzRRIbs=)

### Other comments
In the example link provided try searching for `a100` which should result in a single hit, then press `down` to highlight it and `enter` to select it and you will see the artifact.

**Comment by dmcknight26** [comment]
This used to work cleanly, at least in the `2.x` versions.

**Comment by websitevirtuoso** [comment]
If you could provide a video this would be useful. I can see ripple effect when close but everything fine

**Comment by dmcknight26** [comment]
https://www.screenpresso.com/cloud/Fue0f/

The larger menu appears again briefly after I make the selection with the keyboard.
