### ISSUE TITLE
[Bug Report][3.3.7] v-select list changes width wildly while scrolling

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#17751]
### Environment
**Vuetify Version:** 3.3.7
**Last working version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0
**OS:** Windows 10

### Steps to reproduce
Make sure your screen/window is not too large, so that some of the list items are wider than the select field.
scroll through the list with mousewheel and by dragging the scroll bar.

### Expected Behavior
the dropdown list has the width of the widest item.

### Actual Behavior
the dropdown list changes its width depending on which items are rendered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU39LwzAQ/Soh/6iwNuj8AWWKgt/C7o+svWE0TUuSVmX0u3tNuq1NkA0slOa9S+69S+/edvSladKuBZrRlYWqkdzCU64IWXVJwXXp1h7VynKhQJOtbMU+4EK6/jrAca8k+JrHnN7kdBJzUQMSCku6pKpLkLin47IFk1OSCfQwnHJfJCTfuB2vsOWttJhrxfYJppJIot7RE+KjKR8d3fviBsZXt2KTshGaQovG54bvptaWlF6b7Hy2kluekcsr8vhELkeOEGc4I29HTxfXF4spwici/iSjwE0IIxwTc2YZwgjHxJy5DWGEY2LO3IUwwjExZ+6nN/T/J8gdSkXSsZcjsz6sfD9nsxZwXEZUK+XI9Vdu0Q89eOg6uqBSqE+Tfpha4VC6BstpYXAaDu2V03drG5MxVpQKd+IUiU6nCixTTcVwnK3Y/jwv02X6wEph7J5KcJ5M6pINmda56lFQVEOfJxVvAlUfcMpjo+OstjDgExaecRvTrbKigqSsK+fl1nuZ0CmYKtngpBrQmCSn49U4mcHwGVKnqkWJKDVDvQ50okGVoEGfW1FwbFpVEIoqG391T/sFdcfw4p1luv4FtMiBFg==)

### Other comments
With the introduction of virtual scroll, there is a not so nice side effect:
If the v-select width is smaller than the width of some list items, the list does change its width once these long items render.
Scrolling through the list with the mouse wheel feels OKish, but dragging the scroll bar feels very weird, because the width change maybe triggers mousemove events.

Not sure if there is any feasible way to predict the width of all elements without rendering them...

**Comment by websitevirtuoso** [comment]
I think this is expected behaviour. because team implemented virtual scrolling for better performance. if you know max with you can use css to set width for your select

**Comment by drhouse82** [comment]
I agree that this is kind of expected with virtual scrolling.
However, it is (a) a change in behavior (to my understanding it is not optional) and (b) when dragging the scroll-bar, the behavior feels so weird/jumpy, that I think it should at least improved to feel similarly smooth to mouse-wheel scrolling.
In the screen video below I try to drag down continuously and slowly. (Watch until the end)
![scrollbar](https://github.com/vuetifyjs/vuetify/assets/16007263/cd61259b-be07-43fd-b933-3092c975f0ab)

I think, beyond the width change, a second issue is that when using the scroll bar, the scrollbar jumps to uppermost position upon every width change. So there is also a scroll-jump in addition to the width change.

**Comment by drhouse82** [comment]
Well, and sure I thought about if I know the width of the widest object and fix it... but if it is easy to do, it would be better if vuetify would do it.

**Comment by KaelWD** [comment]
Looking at a few other libraries, they either have the same problem (quasar), or limit the menu width to the same as the input (virtual-select-plugin, material-ui, element-plus, angular/material). You can do the latter in vuetify with `:menu-props="{ maxWidth: 0 }"`

**Comment by WinmezzZ** [comment]
1
