### ISSUE TITLE
[Bug Report][3.3.7] breaks Vue 3.2.X Support

### ISSUE THREAD

**Issue by mgaller** [vuetifyjs/vuetify#17755]
### Environment
**Vuetify Version:** 3.3.7
**Last working version:** 3.3.6
**Vue Version:** 3.2.47
**Browsers:** Firefox 115.0
**OS:** Windows 10

### Steps to reproduce
This breaks by import of "toValue" which is only available in vue version 3.3 and higher
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/filter.ts
https://vuejs.org/api/reactivity-utilities.html#tovalue

### Expected Behavior
Should work

### Actual Behavior
Dies with
ambiguous indirect export: toValue

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMHKwjAQhF+l7LlJ4Ff4oSffw3hQs2K02ZbdWBHpu5vEClIvgsfM7s6XmfUdfOg7jipse32SjqCBu6WqstNALDRVUbI2XDC/LRxj7KUxZu8onTls/cCaMBrqg1mlNcMXij6gcl1YLfSfXv4b5yW+6xolqB13V0FOLhbqN070h9sXrGkzIRZ6IkySarc7yYgPa5N4A7JiJIeM/G2k2VlhLp/M2egjWaaPlkaoofV0llnXeyk9r1+f/ClyMctOmwwca3jWn9DlAjYPNOap8w==)

### Other comments
If at least vue version 3.3 is required, this should at least be listed in the changes.

**Comment by rjcalifornia** [comment]
@KaelWD  How do I fix this on the project? It still gives me error even when I updated Vuetify

**Comment by KaelWD** [comment]
It wasn't released yet. Why are you guys updating vuetify but not vue anyway?

**Comment by rjcalifornia** [comment]
@KaelWD Yeah well, it was working on my computer however I use Vercel to deploy my projects. It was working well in Vercel until this week in which I pushed a small change to master. So.... That's how I got here.

**Comment by KaelWD** [comment]
That's why lockfiles exist, so every environment has the exact same packages.

**Comment by rjcalifornia** [comment]
> That's why lockfiles exist, so every environment has the exact same packages.

Yeah, that's what I thought too yet this happened. Luckily, it was just a font color change nothing relevant.
