### ISSUE TITLE
Elements with dark color classes should default to dark styled theme

### ISSUE THREAD

**Issue by CAD97** [vuetifyjs/vuetify#1776]
This is somewhat partway between a feature-request and a bug. More feature-request than bug, but I would say it could still be classified as a wrong-default bug.

Take the following layout for example: https://codepen.io/CAD97/pen/aLvweg

    <div id="app">
      <v-app toolbar>
        <v-toolbar class="deep-purple darken-3">
          <v-toolbar-title>Title</v-toolbar-title>
        </v-toolbar>
      </v-app>
    </div>

The text in the title bar is almost completely illegible. This is fixed by telling Vuetify that the element should be treated as having a dark theme by adding `dark` to the list of properties on `v-toolbar`.

The way to get the good, conformant-to-readability-guidelines is simple; just add `light` or `dark` to anything styled in a color. However, it would be very nice if the defaults were the proper color text and icons. https://material.io/color/ shows whether light or dark colored text should be preferred on top of each Material color.

However, the story gets more complicated when using a theme. If I have some element `v-toolbar.primary`, I cannot know whether the primary color has been set to a light or a dark color. Normally, just leaving off `dark` or `light` allows the default to behave correctly, since it's inherited from the app's setting, but in the case of colors that are dark in a light-styled app, or light colors in a dark-styled app, this doesn't work. This becomes even more problematic when swapping out color themes at runtime.

**Comment by johnleider** [comment]
This ultimately has to do with how Material Design handles the dark/light themes. A toolbar is light grey on a light app, so when you make it a darker color, you have to tell the toolbar that it should use the dark theme. While a minor inconvenience, I don't think this is something we are going to pursue at this time.
