### ISSUE TITLE
[Bug Report][3.3.7] v-menu will reopen if added open-on-hover transition="slide-y-transition"

### ISSUE THREAD

**Issue by yumjoetee** [vuetifyjs/vuetify#17765]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
When added open-on-hover transition="slide-y-transition" on  v-menu, the v-menu will reopen after clicked any content inside, but will remain close if click on the same content.

### Expected Behavior
Should not reopen on clicking any content,

### Actual Behavior
Menu reopen on clicking any content.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtU8Fu2zAM/RVOF7dAZAPrgAFGWrTYZZedd6h7cGxm1SpLgqR4Cwz/+yjaaWNnwAZsp4SPj3x8FP04iAfn8v6AohTbiJ3TdcS7ygBse1k7x385aKyJtTLoZ4jBDs0BrEMjrZHPtkcP0dcmqKisua1E0KpFeZRvYCVe66nDSRF6GbSNZd1E1dfReqodwHnrAoyLEpbdRQON1UxzXnW1P1aCeuyUaRmiOqqCh1M7SN1hW3Dp+QDFwvOrgFYhrkUTJhXxz3Eg1T3PcZVSG6AJ8Oc1/UCKaYolu3zBI5GZdZHra33A32cXwyzHkVFFjXfDwIo5RzCOyeyas3B0nl+sZGU/AemdT6dA4fIWEjKdymKdFIbGKxchYDxMl6Q6Z32EATzuYYS9tx1kdH1ZogO9qQkRuvANbhPjKvuMWlv4ar1u32XXbxTe7Ux6nOYagD2WkH3SqnmBL5jBuPnfOXh/yj7RONtickjexEZM5mRXu/x7sIa+qCER6T05QbdQAiMJI9MprsRzjC6URdG0hspa1Kr3ucFYGNcV90Qr/MFE1aFsbXd/k9/kH4qW3ucczjF0cuftj4CemlRinp9lotrT1/FHqZnJCh8nhRmSut6FJHHRuiA9+ualR7pYj/5vHa3Kzl2tUhfOkvpYmZH2rZV5CatVN4HXPN/EP1rmZvzWSXDcCJ6TlLlAPP0Cgt2rtg==)

**Comment by websitevirtuoso** [comment]
why do we need to set transition="slide-y-transition" ?
