### ISSUE TITLE
[Bug Report][3.3.7] v-text-field doesn't show value when using :value and label

### ISSUE THREAD

**Issue by JulsWlf** [vuetifyjs/vuetify#17762]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Safari 16.4
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a `<v-text-field :value="myValue" label="Test" />` and the label will always appear on the input, even if myValue has value

### Expected Behavior
Label should appear on top normally (just like when input has a value when using v-model)

### Actual Behavior
Label remains on input as if it didn't have a value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkMtqwzAQRX9FaJMWImuRQsE4If2H7qIsHHtM1VoPpLHbEvzvHckUTFJIupzXuffO4cxfvC/GAXjJKwTj+xphpyxj1SgQvlB0GvqWjcK4Fvqt4mPdD6A46+tTrl8houK7Si73/yCU+fAfgEou/FAZm6A9sgg4+MzXxruA7MwCdGxiXXCGrSjKKg0bZyOyrMW2aeNh1Tm3ekzcmUQMvua9th+xeI/O0gfO6VLxJkbFS3ZIVarfEH0spWxaS5v0Bj2GwgJK640kQdTd935TbIpn2eqIvy1BCWORYYl0VHYiwdm1MLW/UJ0HWTl3Uo9Iqb5hYU9rMgwWtQHROpO9PM1eFu0CohGn4D4jBIIovl7IJMN3SN1KSxJXaEl6IwQRwLYQINyb6OJsmepidJUsqU/p39Oa5zN6fLbMjz/RcgEM)

### Other comments
Thanks for the help, I couldn't find anything relating this on the documentation, but if there is and I missed it, I apologize.

**Comment by SonTT19** [comment]
@JulsWlf You should pass `:model-value="myValue"` instead of `:value="myValue"`

**Comment by Joebayld** [comment]
> @JulsWlf You should pass `:model-value="myValue"` instead of `:value="myValue"`

I have a question on this.. Why does `value` not work though? If you click on the text field the value is shown, but only if it's active. I'm curious about this behavior. The component is definitely getting the value but the behavior is different than passing `modelValue`.
