### ISSUE TITLE
[Bug Report][3.3.7] Navigation drawer opens when moving from medium screen size to large screen size

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17770]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) open the playground from the link given in issue
2) preview in full screen size
3) now try to change window size from smaller to larger 
4)you will find navigation drawer open.

### Expected Behavior
Drawer shouldn't get open on change of window size

### Actual Behavior
Drawer opens on changing in window size.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkU1v2zAMhv8Kp4s3ILawpcOAwC2yYcdhvRS9RDmoNpOqtT4gKS6KIP+9lJykhnMp0BtJke9LPlrt2W/nqn6HbMHqiNp1MuKNMAB1X0rncpiTxpoolUF/LAH8l73ayqisgTsMUZjTQ33/JxpYNp1qnq8FU+Gvly/obx0auIYv41ywG7iz222HUPM0dlav79/1h37oS21b7CaSJHGaSVP/VIiwUHRLoMZVkSL4XsxgiH6co/k5ujpHP4u1YMDfl+AXW5yI8CmSVBmI1XxEktLQeOUiBIy7AajSzvoIe/C4gQNsvNVQ0CcUA0PSpRsm2Kj160Z2Ab8lg0GSxNiMDWqllq56CtbQT+6TClHKD0GwBeRKqpFLygV7jNGFBedNa2iMsKreVwYjN07zJbVxvzNRaSxbq5fzal5d8ZbYjssVBl0+ePsS0JOIYLORTVSb1w9YHTuzw6/B4VgqO/kQksWFNCe/Hn3p0bTo0X/0osnY+KrJ08Vlyf0gzIF4d8o8hwnqJmTMq9OSnzo5iyWldTI8zFjek5zzAFu/AYG7Ook=)

![image](https://github.com/vuetifyjs/vuetify/assets/92006556/f5847c42-473d-425e-a5f6-4158946d40cc)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-navigation-drawer/#props-disable-resize-watcher
