### ISSUE TITLE
[Bug Report][3.3.7] v-text-field regex rules for lower and upper case letters not validating

### ISSUE THREAD

**Issue by tamsler** [vuetifyjs/vuetify#17787]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Enter invalid input
e.g. ABC-123 and it's not validating as invalid 

### Expected Behavior
Entering ABC-123 should make the input invalid

### Actual Behavior
User is allowed to enter ABC-123

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUV1r2zAU/SsXMUgLlpXSwJiXju5xMBj0Nc5AsW8SbZIsJNltl/q/70p2IaQvhT7p3nM/zjlXmxP77lw59Mgqto5onJYRv9UWYD1w6VwOc9J0Nkpl0c9QBiM+Rb5XqFsYuOla1Hc1M+FQM6h8rzFQuknBlhDxukxcbkvIRLYWZyIoDY1XLkLA2E9alHGdj3ACj3sYYe87AwvSv0jtAELAAx7wCR6INAFEFCIkCXAHg9Q9vbMO8Xsj+b8l/8K3p1Vxsxw/CVVGDPEq913Dy8vUuPhhCVEtWGmwgp9oD/EIK+Bws4TmKL1sIvrwFX5Z/Qy6e0QPjQwIGmMqFGB7s6MApG2hleGIYdY7yaOLkTpydLVYXKcjTLZJJyvY5Jgb6co/obP0Uac0Wc+FULMKMpIwukTKa3aM0YVKiKa1NEYfowZfWozCOiPuqU343kZlkLedub8tb8uVaFWI53CJwfCd7x4DelpSs+KMJqr98zuo5s7M8HlimCGu5S4kijerBfEN6LlH26JH/15HF2Pnri5Kb5wl9rG2I91bK/s3XJy6CfnMm1eRH7Kcl6VN20Q4FizrJOY8wLb/ARzhMiE=)

**Comment by KaelWD** [comment]
Your regex is case insensitive.
