### ISSUE TITLE
[Bug Report][3.3.8] No appended icon when using multiple set

### ISSUE THREAD

**Issue by yannmichaux** [vuetifyjs/vuetify#17797]
### Environment
**Vuetify Version:** 3.3.8
**Last working version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 11

### Steps to reproduce
1. Set up a fresh Vuetify project
2. Use multiple icons according to [documentation](https://vuetifyjs.com/en/features/icon-fonts/#multiple-icon-sets)
3. Create a select and view for the appended icon 

### Expected Behavior
- Chevron for VSelect is displayed
- Clearable icon is displayed

### Actual Behavior
- Chevron for VSelect is hidden
- Clearable icon is hidden

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqlUk2P0zAQ/SvGl4DaxIflgKoWFiQkOCAQVOLQ9OAmk6zBX7InWVal/51x0qJsellp5YvnefzevKfZHfl774u+A77iawTjtUR4W1rG1n0uvR+uQ1E5i1JZCGdoABH+YN4o0DXrc+Nq0JuSm9iWnFUaZJAHDcxDiCoiWMwHkIkpRQQNFbKVIvVIv3fZB2npZEuWbZ2R6NLtY9vSaBbT/ZvDhO5J5MK0FvMBEzLOvxYTX1TGKiiPLAJ2oz1lvAvIjixAw06sCc6wjCLJUjtjxBuRkSm2SR0vs0+gtWM/XdD1i+xVEhgpiYwv+ciWG+mLX9FZyvWYWMrzQyz5ig1Iwkgl1SW/Q/RxJURVW/pGOao+FBZQWG/ELbWJ0FlUBvLamdub4qZ4LWoKdQoXEE1+CO4+QiCSki8nMqiahydInTsHhTejwhnKtTzEJHFFLUivh5AHsDUECE91NPs2dTV7unKW1E+lPVHeWtnfcRZ1FYeYd5chn2V5IPvv90LV0LbFonWupZX2itqcEdT6rpFG6YfNF9q3oKRefE778/dxufjaIc0N9Rzf3rvF1lmY499dZ6+af9zJ4Mcs9imL05IPEVIogxe+/wdFrFEF)

![image](https://github.com/vuetifyjs/vuetify/assets/23440844/11949154-00b4-4543-ad01-7c52e8b7df4e)

### Other comments
I can't set up multiple font on Playground, the page doesn't render when i try to setup imports

**Comment by websitevirtuoso** [comment]
Yes I see your problem with icons.

1. Clerable icon displays only when input/select has values to clear.
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/c8a800da-1fbb-436b-a202-e9844b04cfb5)

2. You should provide information what kind of icon (exist multiple ways mdJS, font etc) you use.
Or provide minimal repo with your error and I will happy to help you.

Right now this is not an issue in package. Error on your side

**Comment by yannmichaux** [comment]
Hi, i finally managed to make that work with multiple font.

As you wrote, I have incorrectly initialized the loading of the various icon fonts (FA and MDI).

Thank you for your time, I'll close the issue.

**Comment by websitevirtuoso** [comment]
great
