### ISSUE TITLE
[Bug Report][3.3.8] VBtn color incorrect

### ISSUE THREAD

**Issue by ncn-mw** [vuetifyjs/vuetify#17796]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0, Google Chrome
**OS:** Mac OS 10.15

### Steps to reproduce
1. make theme background black
2. make theme background text white
3. make theme surface white
4. make theme surface text black
5. create a button with text

### Expected Behavior
button is white with black text

### Actual Behavior
button is white with white text

### Reproduction Link
[https://github.com/ncn-mw/btn-color-demo](https://github.com/ncn-mw/btn-color-demo)

**Comment by websitevirtuoso** [comment]
Yes everything correct. this is expected behaviour. you have to set prop "color" to v-btn. or via vuetify config set configuration for detault prop

example of configuration
```
{
VBtn: {
   color: 'primary'
}
}

more about this in documentation.
```

**Comment by ncn-mw** [comment]
I don't think this is the case. Your configuration is a good workaround but by default, buttons should be using the on-surface theme color as text color and the surface theme color as background.

After some digging, I found that there actually is a CSS definition that tells the VBtn to use the theme color in the elevated variant (which is the default), however it's immediately overwritten by the definition on plain html buttons where the color is set to inherit.

**Comment by KaelWD** [comment]
It works if you make sure `vuetify/styles` is loaded before any components:

```diff
diff --git a/src/main.js b/src/main.js
index daa1acf..d31eee2 100644
--- a/src/main.js
+++ b/src/main.js
@@ -4,15 +4,15 @@
  * Bootstraps Vuetify and other plugins then mounts the App`
  */
 
+// Plugins
+import { registerPlugins } from '@/plugins'
+
 // Components
 import App from './App.vue'
 
 // Composables
 import { createApp } from 'vue'
 
-// Plugins
-import { registerPlugins } from '@/plugins'
-
 const app = createApp(App)
 
 registerPlugins(app)
```
