### ISSUE TITLE
[Bug Report][3.3.7] model-value always empty with de locale (firefox only?)

### ISSUE THREAD

**Issue by derpierre65** [vuetifyjs/vuetify#17795]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
- change locale to "de" (i dont know if de is the only locale with that problem)
- use the v-date-picker
- click any day

the model value will never be updated, it works in chrome but in firefox it's always an empty array
my guess is that "new Date('11.7.2023')" (formatted date) is "Invalid Date" and in chrome not

by the way "new Date('11.7.2023')" (in isValid date adapter) works in chrome but does not return the correct german date. I think it does not matter because the date is only used to check if the string is a correct date, just as a hint.

### Expected Behavior
the correct date will set in model-value

### Actual Behavior
model-value is always empty

### Reproduction Link
[https://codesandbox.io/s/brave-field-4n3c85](https://codesandbox.io/s/brave-field-4n3c85)

**Comment by websitevirtuoso** [comment]
v-date-picker has his own configuration. please check documentation in lab one more time and check related issues before creating new issues

**Comment by derpierre65** [comment]
i have already checked the bad documentation.  
i have also searched for related issues, but issue #17615 didn't look like my problem at first glance
