### ISSUE TITLE
[Bug Report][2.7.0] $tab-text-transform interpolation including quotes

### ISSUE THREAD

**Issue by joshua-farmlink** [vuetifyjs/vuetify#17799]
### Environment
**Vuetify Version:** 2.7.0
**Last working version:** 2.6.16
**Vue Version:** 2.7.14
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a VTabs component with a VTab component inside it.

### Expected Behavior
The text should be uppercase.

### Actual Behavior
The text is displayed as entered.

### Reproduction Link
[https://codepen.io/joshua-farmlink/pen/gOQvgKe](https://codepen.io/joshua-farmlink/pen/gOQvgKe)

### Other comments
It looks like the sass string interpolation is including the quotes, giving you text-transform: "uppercase"; which is invalid.

**Comment by lukashroch** [comment]
Ref https://github.com/vuetifyjs/vuetify/pull/17771

**Comment by mcfarljw** [comment]
https://github.com/vuetifyjs/vuetify/issues/17840 is probably a duplicate of this.
