### ISSUE TITLE
v-carousel showing black screen tab is focused after a while

### ISSUE THREAD

**Issue by rohitpal99** [vuetifyjs/vuetify#178]
When browser tab get focused back after a while carousel doesn't work. It shows a black screen.

![image](https://cloud.githubusercontent.com/assets/7090592/23580496/03b3eb9a-0129-11e7-90ee-0ee7c639ff82.png)

I am on Chrome Version 51.0.2704.106 (64-bit) Linux Mint

Also, since vuetify is made to work with mobile as well. I think swipe on carousel should also be a feature.
Thanks for wonderful library.

**Comment by johnleider** [comment]
This seems to be a rendering issue with chrome. After it cycles to the next slide it always fixes. As far as the carousel improvement, I'll add it to the post 0.9.0 list.
