### ISSUE TITLE
[Bug Report][3.3.8] Fixed table headers only work if there is a single row of headers

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#17806]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0
**OS:** Linux x86_64

### Steps to reproduce
Scroll down until the sticky headers should start to move

### Expected Behavior
All table headers should move

### Actual Behavior
Only the "last" / "lowest" headers at the bottom are moving. The header above gets lost.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs1u2zAMfhVCpwSIrbTdgCFzgxa77B3qHpSIrrXKsiApXgPD7z5KzmI3QdGebJH8/ig99ezR2rw7INuwImBjtQi4LQ1A0WVB7DRCpd5QZjUKiQ5qVC91uC/Z9/W6ZGmQRkPsng7x6M7/qQn7VnsrDMFuCfR7pGqrWIcbEEbCbcFDPTHwGcUV3fZXhL0DTPUPiWJ9clmEXSuPcw3osqp1ZHGhaA8rUEbi25I+IEUQJYPNKx6pnern6CNYbvt+BMAwREgKRorTUj4ci4Znu3tn+Oyx4KfboBPVp3uio987ZQN4DAcLWpgXMhn8yaFqbOsC9OCwggEq1zZQMrrvkv2MaCAPxoeUEe7j1OLROXFc3KzXy7xSWi/MQevlkqYLPkoRMVsxrcyrz//41tDT6SNTyfaedDfwNAYoWR2C9RvO99LQpEStOpcbDNzYhpOJoKrjw11+l//gUvnwv5RpsfN5IotMz6UZSHCMkjXCXqiOjaScKrGWEm4+s/BAY9wdTFANZrJtkpdvo5dZOUffZDvX/vXoiKRkq5lMNPwFqc/SksQVNSe9Dl3mkN6MQ/fVRBeweaqL1lWyqD7EfQ8rlmC0+GSZPf8DzEFUpA==)

**Comment by websitevirtuoso** [comment]
Problem in code. we have have only 1 tr 
```
<thead>
      <tr>
        <th colspan="2">Header of col 1 and 2</th>
      </tr>
      <tr>
        <th>Col 1</th>
        <th>Col 2</th>
      </tr>
    </thead>
```
correct code

```
<thead>
      <tr>
        <th colspan="2">Header of col 1 and 2</th>
      </tr>
    </thead>
```

**Comment by websitevirtuoso** [comment]
If you want that to have 2 tr use css and apply position fixed to both elements or 1 parent element

**Comment by jtuchel** [comment]
> Problem in code. we have have only 1 tr
> 
> ```
> <thead>
>       <tr>
>         <th colspan="2">Header of col 1 and 2</th>
>       </tr>
>       <tr>
>         <th>Col 1</th>
>         <th>Col 2</th>
>       </tr>
>     </thead>
> ```
> 
> correct code
> 
> ```
> <thead>
>       <tr>
>         <th colspan="2">Header of col 1 and 2</th>
>       </tr>
>     </thead>
> ```

So Vuetify assumes there must be only 1 `tr` in `thead`? 

I don't know how to solve this but maybe this is not correct ( or can be improved )?

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTable/VTable.sass#L141

**Comment by websitevirtuoso** [comment]
Yes You are totaly right. it can be improved. 
As a temporary solution use css for your case

**Comment by websitevirtuoso** [comment]
I will open PR to implement this feature

**Comment by websitevirtuoso** [comment]
Here PR to fix it. hope they will accept it
https://github.com/vuetifyjs/vuetify/pull/17811

**Comment by jtuchel** [comment]
@websitevirtuoso may I ask why you closed the PR? I think that would fix the problem, no?

**Comment by websitevirtuoso** [comment]
@jtuchel I didn't I will reopen it soon. working on gutters for grid systen right now

**Comment by websitevirtuoso** [comment]
@jtuchel I know why it was closed. I did rollback on my forked repo because created new PR and I didn't use any branches. I reopened PR
https://github.com/vuetifyjs/vuetify/pull/17821
sorry for this.
