### ISSUE TITLE
[Bug Report][3.3.8] v-icon doesn't display "icon" when slot is filled

### ISSUE THREAD

**Issue by Modjular** [vuetifyjs/vuetify#17807]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create an empty `v-btn`. Populate the `icon` prop. An icon-button should appear
Add a comment or an empty `<template></template>`. The icon disappears, but the button remains.

### Expected Behavior
Icon remains

### Actual Behavior
Icon disappears

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkcFuwyAMhl+FcS5w2A5T1U3dYU9RekgTb2ULBmGaaqr67jNEm9L20NzANt///2Zzkm8x6uEAcilXGXzsmwyvFoVYDWqXUbg24IuVvnOKcpOsrE1uPygl3gdA0Yg2eA+YhQciIJH3Dj9JHKJQakSZyuLzHPC/i2M4rsylp3mgydwFQC5k7/Cb9BcF5MCnQrGyJbJyKTajvpX7nCMtjWk75MkOejckjZANRm94Vdl9/Kwf9aN+Np2j/FdSfbMjXWGFtLV4ZkHnY0hZ+SZeqY6Nqlwrpcakcr9jYc1jJh0wOw+qC756eRq9TMoayKtdCkeCxBArFxOZYniG1L20LHGDNqw3QFIJsIME/CHzEl09m6a6at0kK+rnsu/zQtZnvPhqWW5/Abfv94c=)

### Other comments
This is mostly annoying when using an icon-button to activate a `v-dialog`. The modal sits inside the button, but there's no actual "content" in the slot, which I assume tells the component to not utilize the `icon` anymore.

I can see this not being a bug, just unintended but technically correct behavior.

**Comment by yubaoquan** [comment]
Am I facing the same issue? 
Icon gone, a blank round button remains.
This is expected behavior?

```html
<v-btn density="compact" icon="mdi-filter" color="#e2e8f0">
    <v-dialog activator="parent" max-width="340">
      <template #default="{ isActive }">
        <v-card prepend-icon="mdi-filter" :title="$t('dutor.setFilterConditions')">
          <v-divider></v-divider>
          <v-card-text class="px-4"> building... </v-card-text>
          <v-card-actions>
            <v-btn :text="$t('common.cancel')" @click="isActive.value = false"></v-btn>
            <v-spacer></v-spacer>
            <v-btn
              color="surface-variant"
              :text="$t('common.confirm')"
              variant="flat"
              @click="handleConfirm(isActive)"
            ></v-btn>
          </v-card-actions>
        </v-card>
      </template>
    </v-dialog>
  </v-btn>
```

**Comment by emelendez** [comment]
I don't understand why this bug is closed, 
as today i faced this problem with:

```javascript
<v-btn  icon="mdi-eye" >
    <v-dialog activator="parent">
        <v-sheet class="bg-white">
            <ita-form-recommended />
        </v-sheet>
    </v-dialog>
</v-btn>
```

At least, in VDialog documentation show a warning using activator="parent" within a VBtn of type "icon"
where a correct use would be:

```javascript
<v-btn  icon>
   <v-icon icon="mdi-eye" />
    <v-dialog activator="parent">
        <v-sheet class="bg-white">
            <ita-form-recommended />
        </v-sheet>
    </v-dialog>
</v-btn>
```

**Comment by GreyXor** [comment]
I also have this issue. I've found that it's tag 3.0.0 beta 5 that introduces this regression.
