### ISSUE TITLE
[Bug Report][3.3.7] Why is :multiple="true" not allowed on v-select?

### ISSUE THREAD

**Issue by dkern** [vuetifyjs/vuetify#17817]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.2
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
It's not allowed to set `:multiple="true"`, because the type definition only allow `false|undefined`. It's working anyway, but I always get a warning:

> Type true is not assignable to type false | undefined

### Expected Behavior
No warning.

### Actual Behavior
Functional, but get warning.

### Reproduction Link
(does not show the type error there)
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctOwzAQ/JXFl4DUxBIckKoWFQ4Vf8Ch6SFNtmDwS7ZTRKv+O2snVUN6qcTJ2dndmZ3J6sCerS12LbIpmwVUVlYBn0oNMNvllbXpMxW10aESGl0PJdCjxDqcAABZbVDOS9agMiU741NB3J4aq2xpTDaB7KVy8VmK/T6VLb3rPyuqlUFYibQVXIvnHj8dxcdXRaQ7esYHZqj0tRM2gMfQdp6EssYFOIDDLRxh64yCjHLI4jgA8foAyr/DPE7cZq8opYE342Rzk91FgY6SyNiEdWy5qmzx6Y2mMA+RpewbvmRTSEjESCXWJfsIwfop53Wjaa1BKXau0Bi4toovaIy7VgehMG+MWjwUD8U9b4QPQ7hAr/KNM98eHZGUbDKQCWL7c4VUP5kUHjuFHsrph/oocUHNSW+HLneoG3TornU0Whu6GrUunEX1Y6mPlLcU+suPoq59inl1OvJflhNZZFpHweOEpTtJOS2w9S/oMg55)

**Comment by santiagoaloi** [comment]
I believe there may be some confusion regarding the usage of the "multiple" prop and the redundancy of binding the value of "multiple" to `true`. It is worth noting that in VueJS components, the implicit `true` value is sufficient, rendering the explicit binding unnecessary. 

```html
 <v-select :multiple="true" />
 <v-select multiple />
  ```
  
Would you kindly share the warning console error message, please?

**Comment by dkern** [comment]
I actually can't, because i'm on holiday now. ;)

But some thoughts:

- How would you define multiple dynamically then?

- Why does `:flat="true"` on Buttons for example works fine?

- I work on a project where a linting rule doesn't allow empty HTML attributes/properties. So in plain HTML it would be `multiple="multiple"` or `multiple="1"`, what both is not allowed too.

**Comment by KaelWD** [comment]
#17211

**Comment by dkern** [comment]
> #17211

Oh yes, it seems like the same behavior. But without using volar. 😉

**Comment by KaelWD** [comment]
How are you getting typescript warnings in vue templates without volar

**Comment by dkern** [comment]
Using phpStorm you get volar like errors within the IDE too.

**Comment by jacekkarczmarczyk** [comment]
Doesn't current webstorm use Volar as well? It's 1.6.5 though, not sure if you can update it or just have to wait for next webstorm

![image](https://github.com/vuetifyjs/vuetify/assets/15625235/96422a36-4c79-4b67-b235-7e4994dea7e1)

**Comment by dkern** [comment]
I'm using phpStorm, what should be the same base as webStorm, but I never noticed this. I thought they re-implrmented these checks. I was sure I read about it in the official youtrack. But I might be wrong here. I will definitly check this when I'm back.

But eigther way, the messages are the same it seems.

**Comment by dkern** [comment]
After a Quick search it seems we are both right. Until now they had an own Implementation but currently working on integrating Volar to it. But as far as I saw it seems to be still in testing ...

**Comment by alisacorporation** [comment]
Yeah i got same warning on Webstorm IDE but it is working...
