### ISSUE TITLE
[Bug Report][3.3.8] VSelect / VAutocomplete / VCombobox `counter` prop issue

### ISSUE THREAD

**Issue by mahsarajabpour** [vuetifyjs/vuetify#17812]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- Set 5 for `counter` prop
- Select 4 items

### Expected Behavior
The counter should show `4 / 5`

### Actual Behavior
The counter shows `20 / 5` 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUstuwjAQ/BXLF0BK4gOtVEUBUfUzCIeQbIRbv2Q7aQvKv3ftJBWCA5xszz5mdtb7C303Jus7oDktPEgjKg/bUhFS9KkDAbUPD0L6VOoGxKakfSU6KOkI5xyLHKLxnNH6xI0br6I6xqqPCE1x2QnPjYApW3fKg8Wk1znBgHXceVA+naIB3xZsFoUSC3alF5+uttyEACHwY7T1pIG2QiZyGZs2la9yslyRzZYsJ4yQKDwn+0Wr9SIhi2Nlw9Hy8zk+OzwPyZwdh38ye1jFyxCk/oujCRVcfbns02mFpkcdJa0dmoN9x8qSnrw3LmesbhRmovG8t5kCz5SRDNflefu7W2fr7I01aNQMpWi3y2Kz0OlQqgEJuQx2pLIyN6xjIDJPfuB6w3LzRxJ2mMYsboZLSBsto5aXUcsVnIGT6dHqbwcWm5R0sibSBMFPUD2aFinuWjPk68GmFlQDFn/PkxPdlF1PdRO6m2xa9UCHhMYyND5Kpoc/YskeFA==)

**Comment by smortexa** [comment]
@yuwu9145 Do you have any plans to fix this issue?

**Comment by yuwu9145** [comment]
It's in my to-do list
