### ISSUE TITLE
[Feature Request] Disable virtual scroll

### ISSUE THREAD

**Issue by djurdjen** [vuetifyjs/vuetify#17824]
### Problem to solve
I have created some custom scrolling behaviour on the list items within the VSelect component. But this breaks now because of the virtual scrolling added in 3.3.7.
Because not all the items are being rendered from the start my custom query selectors fail to get the desired list-item element from the list

### Proposed solution
A property that disables virtual scrolling for components like VSelect so that all elements can still be rendered from the start if you would choose so

**Comment by websitevirtuoso** [comment]
I worked on this but realized that implementing a new prop which disables virtualscroll is a downgrade. Because it doesn't improve code only limit it.

**Comment by websitevirtuoso** [comment]
We have this maybe related issue.
https://github.com/vuetifyjs/vuetify/issues/17751

And for this case we found solution to set
:menu-props="{ maxWidth: 0 }"

**Comment by djurdjen** [comment]
It's not really related unfortunately. The custom code I have currently implemented focusses directly on the selected value when opening the menu dropdown. But when the corresponding menu item is a little bit more to the bottom it is not being rendered because of the virtual scroll, hence I cannot focus on it.

**Comment by djurdjen** [comment]
I created a simplified version of what I did in this sandbox. 
If you only navigate with the arrow keys you will see the behaviour i'm looking for.

https://play.vuetifyjs.com/#eNqlVd9v2jAQ/lesdBJUIslDpz0gWlG1UCFtTBpseyiV6iZH8ZrYme3AEMr/vrPzo04abZP2Qsjdd99359yd70/edZYF+xy8sTfRkGYJ1XC14YRM9j7NMvvXvkSCa8o4yMpkjQoSiHRtIGTvpyKG5HLjRbmUwPU3muSw8V4R06ckl+gX/GsWo9Yn4LnrHzPMQiHAPl0PphbBTiQxmPibnRAKCCWRyLmWRxepJeWKaSY4ArngTgJN8ph+XS45M1qV5C3VdOM5MFtnwpT2jdu1m2RjDHsUmdHy351qgsD8Cfam9uLRzcwGWbsj56C7WCkSgywFus5plLDoxSXKpMhUIPiNcbThrYraNfma6QSuyOlE2ilZOykKMgnfwlsn5PrdIw5bLVVDy66pWwsN7d4ylrL1WvH4qiLJMk0U6LzsTJZmQmpyIhK2I8Lhl15j5aQgWylSMsC+HhgY8itti1PkktyXwidiCxmTwRL0DmRCeawGI2I/hLF+HJBi1MXOno+ZdlCzuz7UIgJD5+AWqz7cOpcvcHRg6y+9dDxm1CVb9qbGnzuis17cHMcjAgc27xW9A5lS7iZ3O+vDLYU8UBe2/N4HWx0gBu7AVr1sc8Y7RcwXvUeiaeKKLta9ohm2lXsgzVd4eO0Ld1Vhe2ArDc9fvVsR5UpBXHm2NFGAbgOg6sgjss15ZMaTbBmPr3k8NwGf+co2OcSWdnhOTmVu9ECZbjq1FKqlyjGfJSgVI0mKSQU/c5DHkkvI4eNZs2vcrOtVU7GxLRnWXI0waegDW1ItXZgH/phHU4q7nZEKeENTcjsGjPpT3W2RSViOMA6vN/LK6fVTmgU/lOB4BVlOXGjWgdt/XKtsPJxl877xdlpnahyGUcwxDG8btpcBBx3yLA2nCAsl3ggsBT8W6fQiuAjehzEuJ9ccgEr9JykOCiSSbLyqc6yMZlu8Tv4qVSGtwodSoTL5CX1SRuINdYh6e5A+fjm8xkD+a0WdMLeqjutNZdXJF3jeCeMvqnPUkbLHXO3E/yzZklXTVXjFyLN5orIN8B5+A8HNrrY=
