### ISSUE TITLE
[Bug Report][3.3.8] VDatePicker cannot select date in Safari

### ISSUE THREAD

**Issue by GaetanWi** [vuetifyjs/vuetify#17822]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Safari 15.3
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just open any date picker

### Expected Behavior
Date can be selected

### Actual Behavior
Model is not updated properly

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs1q4zAQfpVBlyYQWYcsyxLc0GX3tLC7pT3aObj2OFUry0KSXYrxu3ckO8WkgfaQg2bm+3Wygf00Juk7ZDuWemyMKjzucw2Q9rxstS+kRguyus6Z1KbzvHPFEXMGtepkFS/jrW1f5scMVUA/R7DvOXvf0O5xu7+X+qgQKpKCpq0wFTRcnPQ8rLiR5TNp9zzcKGJyEfebdrdx9TfMyYpYgivZ73+RcduqHQwD/Ln//y9x3hJW1q+rixxrGMdUBOR7BBEznPLR6xRw2szF0CQVi9ro6UorjQeHvjOgCn0k497NHcjGtNbDABZrGKG2bQNX1P5VgAI1ph1BL1mE64BJwzQ77FfZYT1B6k6XXrZ6Rt0hCYej1RqGyfxFuqQvVIdEmh3C1RhyTM7JJ9swJfWzS55cq+mPEYlyVjqKsYNsos3Zo/fG7YQoK02XRCp7m2j0QptGUChPfd9sk23yg6p1/jTiqnhwSSQLTKQ/kuDUDG8Kc6Y6LaLyHChnxBTen1i4oTNhO+1lg7xqm+jl2+RlMU7QNfyBPq9DSyQ52yxkguEvSH2WliQ+UAvS69Fyi7pCi/aric5gy1Rnqw/J5k89snHDIoyKj5bZ4Q1uUVpi)

**Comment by eugborisov** [comment]
same in Safari 16.4 for me

**Comment by eugborisov** [comment]
also same for v-text-field with `type=date`

**Comment by eugborisov** [comment]
Found the reason. 
It happens when the `max` prop is set

**Comment by jorwan** [comment]
> Found the reason. It happens when the `max` prop is set

In my case, it was with min `:min-date`
after remove it, select button works in safari
