### ISSUE TITLE
[Feature Request] Allow link to be in isActive:true state if the current route name is included in `to-matches` route name array

### ISSUE THREAD

**Issue by keupsonite** [vuetifyjs/vuetify#17825]
### Problem to solve
When using an AppBar with VTabs containing links, it is not possible to make the VTab button active for a route other than the one passed in :to. Adding a non-mandatory `to-matches` array property would make the link active if the named route is included in the `to-matches` prop.

### Proposed solution
Add a `to-matches` array property for all components actually having a `:to` prop and update the useLink composable in the router.mjs in order to return true if the route is included in the `to-matches` property.

**Comment by websitevirtuoso** [comment]
Please provide the playground with your code

and give more information about expected behavior. and Only then maybe somebody would try to help.
Tahnks
