### ISSUE TITLE
[Bug Report][3.3.8] Snackbar not rendered in tests

### ISSUE THREAD

**Issue by Havrin** [vuetifyjs/vuetify#17831]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows

### Steps to reproduce
Snackbar is not rendered inside of unit tests.
Checkout my Repository, install and run the tests.

The repository is created with `npm create vuetify` and the test is written with https://github.com/vuetifyjs/vuetify/blob/1b49582de80db61ba381756a65a77d85ca130913/packages/docs/src/pages/en/getting-started/testing.md#writing-tests

### Expected Behavior
Using my sample repository, there should be the rendered snackbar when printing the html of wrapper.

### Actual Behavior
the snackbar is completely missing

### Reproduction Link
[https://github.com/Havrin/vuetify-snackbar-bug/](https://github.com/Havrin/vuetify-snackbar-bug/)

**Comment by KaelWD** [comment]
Teleport does not render inside the wrapper.

> the test is written with [1b49582/packages/docs/src/pages/en/getting-started/testing.md#writing-tests](https://github.com/vuetifyjs/vuetify/blob/1b49582de80db61ba381756a65a77d85ca130913/packages/docs/src/pages/en/getting-started/testing.md#writing-tests)

That page doesn't really exist yet: #14749

**Comment by Havrin** [comment]
@KaelWD and is there a workaround to render the teleport? 
https://test-utils.vuejs.org/guide/advanced/teleport.html#example this is not working with `VSnackbar`.

**Comment by KaelWD** [comment]
https://test-utils.vuejs.org/guide/advanced/teleport.html#interacting-with-the-teleported-component
