### ISSUE TITLE
[Bug Report][3.3.9] web-types

### ISSUE THREAD

**Issue by stephenjason89** [vuetifyjs/vuetify#17835]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.67
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create an element with a directive of v-click-outside
You won't see IntelliJ IDE autocomplete this.

**node_modules/vuetify/dist/json/web-types.json
Is incomplete and doesn't have the directives or attributes**

I had to rely on the outdated
https://www.npmjs.com/package/@web-types/vuetify
Just to get the directives working

### Expected Behavior
IDE AUTO COMPLETION

### Actual Behavior
NO IDE AUTO COMPLETION

### Other comments
None

**Comment by michael-roth** [comment]
Hi, I created a PR to fix this (#19238).
I'm not sure if it's enough, in my test project it worked.
Let me know if I can do more.
