### ISSUE TITLE
[Bug Report][3.3.9] v-text-field outlined has uneven border radius when pass rounded prop

### ISSUE THREAD

**Issue by zedjarvis** [vuetifyjs/vuetify#17838]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0
**OS:** Linux x86_64

### Steps to reproduce
add a v-text-field component
set variant=outlined
give "rounded" prop

### Expected Behavior
The v-text-field should be rounded-pill

### Actual Behavior
only the border-radius top-right and bottom-right are fully rounded

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlks9OwzAMxl/F5DKQ1uYwLkwbGjfegMO6Q7d4EGj+KHELaNq746SdVHWXSdzqr/b38+d2exIv3pddi2IpVoTGNzXhc2UBVl1Re58fc3FwlmptMQxSFgl/qDhqbBR0hXEKm3UlTHyvBHR10LUlrl1LDQ8qFoNrrUIF8uIrp8ZJ6bkrOdqHy3gI2hNEpLZfSxvvAsEJAh7hDMfgDMw4yiy1A7BvJOBlYJ067mev2DQO3lxo1N3sIQF6SzYTc9G7Fab25Wd0lu9xSi7V8CJWYglZSRpTUl2JDyIfl1IelOUxzq+7UFokab2RG26TobWkDRbKmc2iXJSPUulIY7nEaIp9cN8RA5tUYj7CkD7+3oAaOjPhqScMUtHU+5gQV9aSeR2GIiB/k4Dh1kSTsXGqyaurZIl+ruyZ782/xFecnPoQ85m3lyX/FTmbJaddAp7nIu/J5Dwgdn/yGQHd)

![Screenshot from 2023-07-19 11-37-21](https://github.com/vuetifyjs/vuetify/assets/54283441/a516a152-91fe-431d-a2f0-da0160e8b004)

**Comment by JustinDugas** [comment]
When using `rounded="xl"` and `rounded="pill" `the problem occurs. This is the same issue for `v-textarea` and maybe other components when the `outlined` variant is applied. This problem stems from the fact that the `v-field__outline__start` is too small to provide a wide enough border-radius.

**Comment by xanxuz** [comment]
Thanks to @JustinDugas clue, I managed to solve it by changing the `flex` attribute of `.v-field__outline__start` class from `0 0 12px` to `1`.

```
<style scoped>
   .v-input :deep(.v-field__outline__start) {
    flex: 1;
  }
</style>
```

**Comment by JustinDugas** [comment]
@xanxuz  Thank you, this fix works well if you do not use a label (placeholder text). In my case i MUST use a label on the `v-text-field` such as `label="Foo"`. Before, the label would move to the top left of the field when clicked. Now it moves to the center. Every hotfix we found consisted in moving the label a bit to the right to increase the `.v-field__outline_start` width but this behavior remains problematic

**Comment by L3Mars** [comment]
Hi, this css fix seems to work for every density and with or without label.

```css
.v-field__outline__start {
  flex: 0 0 29px !important;
}
.v-input--density-comfortable .v-field__outline__start {
  flex: 0 0 25px !important;
}
.v-input--density-compact .v-field__outline__start {
  flex: 0 0 19px !important;
}
```
