### ISSUE TITLE
[Bug Report][3.3.9] v-text-field with v-model.number and type number backspace issue

### ISSUE THREAD

**Issue by arthurM2x** [vuetifyjs/vuetify#17842]
### Environment
**Vuetify Version:** 3.3.9
**Last working version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
backspace twice

### Expected Behavior
the cursor should remain after the period (1.|)

### Actual Behavior
the cursor is in front of the 1 (|1)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkd1qwzAMhV/F+KYb1Dajg7LSju45ml6kicK8xT/YSrZS8u6TnRZCelPYXXQsfUdHOVz4h/ey74Bv+BbB+LZEeC8sY9telN7nz1xUzmKpLYSrlEWEXxSNhrZmvTCuhlbazpwg7Aqure+w4AzPHqgcdarVjanm0KSMnls12YXKWAXtkUXAblxJG+8CsgsL0LCBNcEZtqAYi9TOGHEjsrwB26Wepxe5Xj8n8IgiCF/ykSJM6eVXdJZucEnTtHt+iAXfsKwkjeipLvgnoo8bpara0hhl1n2QFlBZb9Se2lToLGoDonZmv5Ir+apqHXEqS4hGnIL7iRAIUvDlxAZ1c37A6tqZHd5Gh6sk2vIUk8UdWpFfD0EEsDWE9D8eSzQbm6aaPd0lS+5DYQe6d6vtd5yduor5zIfbkv+KnGGJdEyGw5LnPck5D/DjH2ET/Xo=)

### Other comments
Makes it hard for a user trying to update the decimal places on a number

**Comment by DerZade** [comment]
Can confirm! Stumbled upon the same issue just now.

**Comment by ldorfmueller** [comment]
Same here. Also, if you have for example 1,07 and use backspace you have 1 instead of 1,0 (logically it make sense but annoying if you change e.g. to 1,08)
