### ISSUE TITLE
[Documentation] Add hotkey support for ⌘+k to open search on Mac keyboards

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#17859]
### Problem to solve
I live in the Vuetify docs and it requires two hands to use the `ctrl+k` shortcut on my MacBook Pro keyboard. It would be great if it could support both or detect a Mac device to allow for `⌘+k` which I feel like most docs use these days.

Here are some examples:
https://vuejs.org/
https://vueuse.org/
https://vitepress.dev/

### Proposed solution
Add hotkey support for `⌘+k` to open the documentation search on Mac keyboards.

**Comment by KaelWD** [comment]
#18110
