### ISSUE TITLE
[Bug Report][2.7.0] Tab text transform is broken by default

### ISSUE THREAD

**Issue by yelhaw** [vuetifyjs/vuetify#17854]
### Environment
**Vuetify Version:** 2.7.0
**Vue Version:** 2.7.14
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just use vuetify 2.7.0 - the component "v-tab".
By default the value for that text transform is "uppercase". But its put in the "single quotes". So the browser interpretates it wrong.

packages\vuetify\src\components\VTabs\_variables.scss

BAD:
$tab-text-transform: 'uppercase' !default;

RIGHT:
$tab-text-transform: uppercase !default;

### Expected Behavior
text should be UPPERCASE by default

### Actual Behavior
text is "normal" (Bad property for chrome browser)

### Reproduction Link
[https://codepen.io/wahley/pen/jOQKgOz](https://codepen.io/wahley/pen/jOQKgOz)

**Comment by MajesticPotatoe** [comment]
duplicate #17799
