### ISSUE TITLE
[Bug Report][3.3.9] VFileInput rules prop not working

### ISSUE THREAD

**Issue by MuslumTurk** [vuetifyjs/vuetify#17852]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://play.vuetifyjs.com/#eNqlkU1OwzAQha8yeFNATbwoG6q0KhvEDVg0XaTJpBj8J9sJQlXuzthppdBuKrHLPM+8b95ke2Qv1uZ9h2zJioDKyirgutQARZ9V1qbPVNRGh0podCcpia2QmAltuwBVXaMNq5IJVR2QP5YMZLVHScordUHqKtm64NOxsz+JfwFRGfkFn+xFpa+dsAE8hm5cTyhrXIAjOGxhgNYZBTOKNIvtAOTrAyh/gFXsuJ+9oZQG3o2Tzd3sIQJGSzJjc1o/umWqsvmnN5rucowuMVd88CVbQlKiRpRYl+wjBOuXnNeNprEGpehdrjFwbRXfUBt3nQ5CYdYYtVnki/yJN8KHqZyjV9nemW+PjkxKNp9ggmh/bkCdOhPheSScpIz+ho+IK2tOvB5d5lA36NDdmuhibJrq4ukqWaQPpR7o3lLoL39x6tqnM2/PS/4rcjKLTrsIHOYs7UnkNMB2v7jIBBU=

### Expected Behavior
The rules prop should prevent the user from uploading files.

### Actual Behavior
The rules prop does not prevent the user from uploading files.

### Reproduction Link
[https://codepen.io/marcoarosa/pen/BayqRxj](https://codepen.io/marcoarosa/pen/BayqRxj)

**Comment by MajesticPotatoe** [comment]
duplicate #17851
