### ISSUE TITLE
Select with item-value starting with dot doesn't return the selected value but entire object

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#1785]
I use Google Firebase as backend and it uses as id for objects the property '.key', so I have objects like:
```
{
  .key: '-werwj3489f3fho2',
  name: 'Foo'
}
```

If I want to feed a v-select with an array of objects like that, it breaks the logic as the selected value set by the component is the entire object, not the property '.key'. The issue seems to be with this piece of code:
https://github.com/vuetifyjs/vuetify/blob/ebdbfd3c10f4f393308a69e1d00b666685e09b1e/src/util/helpers.js#L102

Do you think you can fix this?

Luca

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
