### ISSUE TITLE
[Bug Report][3.3.9] Tooltip performance : rendering multiple tooltips freeze rendering

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#17862]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add some tooltips to a component.

### Expected Behavior
The component to render without glitching.

### Actual Behavior
The component renders with a delay (like 200ms).

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFVU1T2zAQ/SuqL7Qz2AZCoHgCQ6ffpdNrp4M5yPYmUSNLHmkTSDP5710pjvMBCXh6qC/2Svvevn1ry7ez4F1VRZMxBEnQQygryRGuUsVYbxJmqNh1LkU+ukwDO9T37JK9cvc0uEI9GEjoxT5rCUCeSWCTUPRrQBowHEIJFBbcjAjnMimXVnlRBy40zbPfZLnk1hIK4QFDCX0k6E9BG6i1RFHZXozDFT5uCNz6irqHmS6m63VIXV8bYhbULROKFWAtGLQkNRnBtN6JFC+hkeux1N6iNkucqs1EJnXOUWhFy5lG1OUG2JWuzSUBVmpMeI5iwtFrmbHK6Mqy+RbIwQoCZEIVlOaTKGU2Y750zqU2Agg3p7ZXdtY+rE9zudg0scO7xi6f6sb55Gzrt6AZrhSDoRvRP0z3h/6PsyXznjP1BT5teE6hzY2o0KfBQ6UNkqA+H0tkswVRwZG/frOMGDOAY6NWMWPO54T1ubRwuFpd9pWw2/WZr+Hc5dpM2MEno/+AYr/0YGzwYI3FXctuE3bcvdjYm29ET1N/zYHlBnjJLFfFvciHu/lPOuet+T/SiyLMHs6zk9ac78dVzkewm7Rz1G1N+lmoAZiMrCj2EHfPWhN/AymnLAOu9vCetxf8XUspKl3tYb1o7+0XrWCa6zLbTXt69LY17Qetxnve3NNue6U3Am/4Hs7u8W6Zd83zfPGw2KSgFzeffHBIh6Ia2ei31Yp+rl5GGuSWDqPms02DIWJlkzjOC0WZBUgxMZECjFVVxvRbRtGfXneiTnQRF8LicimUPLORJ3NMd6maU0FRukMmLHm1VXWx4SvXdqQBMbn4GQnXlBabsUJRQljo0ms5XWhZW47AlmFm9D0dS0SSBrVFvowT/IJSz3VLJR5Rx1RvAiY0oAowYF7a0RZsvautrUed1aOeB/PDwMPIeC85uPsLKrWrIA==)

**Comment by KaelWD** [comment]
Do you have vue devtools open?

**Comment by ThomasKientz** [comment]
Yes, no issue withtout it.
