### ISSUE TITLE
[Documentation] VHover example playground not working 

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#17869]
### Environment

**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
In examples:
https://vuetifyjs.com/en/components/hover/#open-and-close-delay
there is not working demo in vuetify playground showing that 
"Component is missing template or render function.
 at <App>"

In reproduction link is link which was generated whenI clicked to playground demo on webpage.

### Expected Behavior
To show demo of VHover Component in playground.

### Actual Behavior
Left side: code,
Right side: white screen.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVN1u0zAUfpWj7GJDqpP+wARRGUOgihvEAyzT5CRe49WxI9tJW1V9d46dljod0nYB4oYLS/b5+77vnCPf7aLPTRN3LYvSaG5Z3Qhq2U0mAeYd0Wrtr/5RKAF4zMcsmkyzCEyNt+ssOkT4mEp1TENHjFAWvTvg5pszcbkcQaNVY2CPqaphkpRM0C0GTcfjoEgPRXV5MgCkTLCOWq4kxp9KwieYXEMKyGYQXQhqHM0dXCrZc7pMAyqOQ5hwjK83hLZWDZ0V48vKiZm9Q56hp6YbsualrX7n7EjOZYkerzr0BVJ/iSWWbWxoP5F6VNKStSdBalbytobakskUXAopmLTYcX83bW65FYxMhlQGgAA/sPnw1TUfrr6r1jDwNd4MaCUBr3A2B/tp5mjwDT7uiQtQAl9/Y28KoQz7vzj/aHG+uO4PN0cw2rE/vTn9vf975knwJ+HT2K1AWCqXqNCgULdQBf4nfeG4B4mP08O3rVjNCCmpXvVAOS1WS61aWTo8pVPQy5xeXSwWixGM4/cHOTeHWg8PYYsPGRdj3D0k5+kgcjSKBJcrEz8ZJfEn3bn4LCocvxTu+uwsqqxtTJokRSkxEveYdzqWzCayqRP8gy1/3N7O4ln8ISm5sUcTETQ3sS/mKt1nco+AvG6UxtHS5gy1d3hkb3E2rOTeL1C4xbBEt9JybFmpas/lbc8lMMfM1CTHARns8BMCjQIYR/gVUC+pRYhnpRPEw6ESzWTJNNOvVXSWFqo6cz1T5tD3rt/7UeTTsPGecnT/E+Z0MMo=)

**Comment by MajesticPotatoe** [comment]
This is just because playground doesn't accept preprocessor style blocks. Temp workaround is just to remove the style block. its only really used for dark mode anyways.

**Comment by jakubmatisak** [comment]
Workaround worked. Thanks.
