### ISSUE TITLE
[Bug Report][3.3.9] VTextField autofill background colour not occupying whole text field

### ISSUE THREAD

**Issue by yuwu9145** [vuetifyjs/vuetify#17865]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open reproduction link
2. Partially type a previous used "username"

### Expected Behavior
Autofill background colour highlight should cover whole v-text-field like input does

### Actual Behavior
Autofill background colour highlight does not cover whole v-text-field

![image](https://github.com/vuetifyjs/vuetify/assets/5698884/ae4666f9-f082-4883-ac56-6848d5b3d35b)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUz1v2zAQ/SssF7eAJQ7pUsEJ0qFFp64dogy0eGrZ8gvkSa1h+L/3SCkJ4QSIgUwW3+O9d++OvjvyzyG08wS84zsEG4xEuOkdY7u5kSGUz3IYvEOpHcQVKiDCP2xGDUY9gIwZuQdz3fOvOiZk36WFrudPtCOA2ClBzJ81pRURYy7LVTWDh5CLsl0NzzJq6ZAYP6Gh5lTNygn94CkS4MuOgqI8hilts9FHugpWatPzmy/5t9uJwj3l1i5MeHmiVe3VNK/2y1jCg8nc3kcFsSnHjiVvdJU8xyp9ivOtZWRZ6k5Uy6ZjGqIOyBLgtOxc2+AjsiOLMLITG6O3bEPvZLOMjHRpuTb9ZNf5xvvNNzDGsx8+GvVu8yEbLJIkxrd8UWusDO3v5B09tmNW6Vci9bxjBckYueRzz38hhtQJMShHZQqMnmPrAIULVtzSNREnh9pCo7y9vWqv2o9C6YQ13EKyzT76vzRNEun5trJBPR4usFpvFodPi8MKNfQyUrZ4Ji3Ib6YVRXC0KYiXJjorq1OdUc+SZfdT7040b/ov/Elnox5SGfPdQ5NvilzEstJ9NjxteemTnEsBv/8P0z9nfA==)

**Comment by hermes85pl** [comment]
The behavior was correct in Vuetify 3.3.5 and got broken with Vuetify 3.3.6.

In my opinion, although the issue is not critical, it is bad for UX and it would be nice to fix this regression sooner rather than later as it is highly likely to be noticed by the end user. Also, it would be nice to find some ways of preventing such an issue from being introduced and undetected by the maintainers.

**Comment by yuwu9145** [comment]
> Also, it would be nice to find some ways of preventing such an issue from being introduced and undetected by the maintainers.

I will create percy test to reserve the coming fix

**Comment by KaelWD** [comment]
I've never been able to trigger autofill in cypress.
