### ISSUE TITLE
[Bug Report][3.3.10] [plugin:ssr-styles] [nuxt] Cannot extract styles for .sass

### ISSUE THREAD

**Issue by AloneRUS** [vuetifyjs/vuetify#17875]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows 10

### Steps to reproduce
nuxt build

### Expected Behavior
Build with all vuetify .sass when server-rendering

### Actual Behavior
Build without inlined styles when server-rendering

### Reproduction Link
[https://github.com/AloneRUS/birdsland](https://github.com/AloneRUS/birdsland)

### Other comments
Warns on nuxt build with message: "[plugin:ssr-styles] [nuxt] Cannot extract styles for ... Its styles will not be inlined when server-rendering."

Reproduced with vuetify only. Other dependences works correctly.

**Comment by keupsonite** [comment]
Why is this ticket closed? Please allow us to use vuetify with nuxt without ClientOnly...

**Comment by johnleider** [comment]
> Why is this ticket closed? Please allow us to use vuetify with nuxt without ClientOnly and full SSR compatibility...

It's closed because the author closed it, not us.

**Comment by rudolfbyker** [comment]
@AloneRUS would you care to share more info about how you fixed this? I'm still seeing this issue even when following the guide at https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3

**Comment by motercode** [comment]
https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html
dissable features inline style

**Comment by AloneRUS** [comment]
> @AloneRUS would you care to share more info about how you fixed this? I'm still seeing this issue even when following the guide at https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3

Sorry, didn't see that. I fixed it by `ssr: true` in vuetify config, and disabled that in Nuxt

Now fixed by adding in Nuxt:
```
features: {
    inlineStyles: false
  }
```

**Comment by rudolfbyker** [comment]
Thanks. It works to squelch the warning, but it's still a workaround, not a fix. A fix would be to allow the styles to be extracted somehow. I am not sure if that would require a change in Vuetify or a change in Nuxt, though.
