### ISSUE TITLE
how to freeze data table header

### ISSUE THREAD

**Issue by dtanphat9388** [vuetifyjs/vuetify#1787]
i am sorry, i dont speark english

**Comment by jacekkarczmarczyk** [comment]
At the moment there is no simple way of doing this. It might be available in future versions though

**Comment by jacekkarczmarczyk** [comment]
Dup of https://github.com/vuetifyjs/vuetify/issues/1547

**Comment by dtanphat9388** [comment]
thanks for reply, thank you very much
