### ISSUE TITLE
[Bug Report][3.3.10] VForm: can't disable some fields globally with explicitly set disabled attribute

### ISSUE THREAD

**Issue by yurks** [vuetifyjs/vuetify#17877]
### Environment
**Vuetify Version:** 3.3.10
**Last working version:** 3.3.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
set `disabled` property for `VForm`
set `:disabled="false"` property explicitly to children field

### Expected Behavior
all inner form fields should be disabled

### Actual Behavior
fields with `:disabled="false"` remains editable

### Reproduction Link
[https://codepen.io/yurks/pen/JjemGxP](https://codepen.io/yurks/pen/JjemGxP)

### Other comments
maybe related to https://github.com/vuetifyjs/vuetify/issues/17671

**Comment by KaelWD** [comment]
Use null instead of false if you don't want it to override the form.

**Comment by yurks** [comment]
@KaelWD ok, `disabled=undefined` seems to be working and understandable, as `false` on field have kind of higher priority. But:
- version 3.2.5 worked nice with `disabled=false`
- `VForm` is a fields "container", and logically it seems to be better to override any fields attributes
- usually `disabled` value is a boolean

so what becomes to be "standard" behaviour for now? Is this documented somehow?

**Comment by KaelWD** [comment]
Oh yeah it was a feature request: #17391

I do get what you mean though, if you have a form that can be disabled with inputs that can be disabled for another reason, you'd expect the inputs to still be disabled if the form is. How difficult would it be for you to just add `:disabled="formDisabled || fieldDisabled"` to those fields?

**Comment by yurks** [comment]
Sure thing, we will go with some workaround.
Just wanted to understand which behavior would be accepted as default in future.
Issue you mentioned is for v2.x

**Comment by yurks** [comment]
> if you have a form that can be disabled with inputs that can be disabled for another reason, you'd expect the inputs to still be disabled if the form is.

Exactly!

Sure thing, we will go with some workaround.
@KaelWD Just wanted to understand which behavior would be accepted as default in future.
Ticket you mentioned is for v2.x. And that kind of feature request was implemented for versions < 3.2.5.  (that's because we have `type fieldDisabled = boolean` in our app from the beginning with vuetify@3 and not `type fieldDisabled = true | undefined`)

**Comment by Lappihuan** [comment]
> Oh yeah it was a feature request: #17391
> 
> 
> 
> I do get what you mean though, if you have a form that can be disabled with inputs that can be disabled for another reason, you'd expect the inputs to still be disabled if the form is. How difficult would it be for you to just add `:disabled="formDisabled || fieldDisabled"` to those fields?

That kind of defeats the purpose of the v-form disabled prop which lets you disable a complete form no mater how deeply nested your inputs are.

We use this a lot to handle disabled products or other things on a route level.

In #17391 the problem seems quite local and not what you would need the v-form disabled for.

I'd be great if the original functionality could be restored and maybe a optional prop to allow enabled fields. But overall it seems paradox to have a enabled input inside a disabled form...

**Comment by yurks** [comment]
+1 for restoring original functionality by default.

Rare case for enabling particular inputs for disabled form could be covered by some vForm property, kind of `allow-explicit-enable`

**Comment by Lappihuan** [comment]
@KaelWD can this issue be reopened?

**Comment by MaevskiyE** [comment]
@KaelWD , just a friendly reminder regarding this issue. It seems counterintuitive to disable a property for the form, especially since the form doesn’t disable the elements contained within it. Does the disabled property serve a purpose in this context? I’m not seeing any effect from it
