### ISSUE TITLE
[Bug Report][3.3.10] VList keyboard navigation broken

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#17882]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on the text field and then press the `tab` key twice. 

### Expected Behavior
List item `2` should be selected.

### Actual Behavior
The text field is selected.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUtFu2zAM/BVCL2mByFqXPRlp0X1H3Qc3pjGttiRIjNfC8L+PkhzHTVCgQJ/sO/J4OkpPo/jtXDEcUZRiT9i7riZ8qAzAfpC1c+k3gYM1VGuDfqYSSfhGstXYNaDWfKcDLXhhpGYHGGRr/X0lbiLagjYNvt3yByIOlYDyFd+5ngoRko2IiwXZSpynAjyMY1IVpKlDmKa9WjmdO89Hm+unWAw/5opMjr1Xq3UwDAevHUFAOuat6N5ZTzCCxxYmaL3tYcOb3MR2AJ4bKGeC+9hz85RNx9NhyJawUXeb7ULEFMwt1DR/LyQ/ryUL9Ylkdy1ZqCx5vo2Zc0rOJ7YiB5R97Yq/wRp+IWko30Uq8FWVJ5tKcPCIK/GHyIVSqUNjWNZgpwdfGCRlXK8euU35oyHdo2xs/7grdsUv1fCVrOkCQy9fvP0X0POQSswnTTak2/cvWM2dyeHuR7aYOdnVLyF6XM1WbDiglx758Xn0X410IVvHuihdRYvuU2UmXninzWu42PUhpD3Pb+e7mdO0dNvRcdqKdFC2zgrx/B/pSkfZ)

### Other comments
Only the first list item is accessible via keyboard navigation. Looks like the issue is caused by the `tabindex` value, which is set to `-2` instead of `0`.

**Comment by websitevirtuoso** [comment]
IN my opinion, this is expected behaviour
here we have 2 elements
1. text field
2. v-list

When click on v-text-field and press key "tab" it redirect us to v-list after this we have to use arrows to navigate in this list.


Create pure html input and v-select and you will have the same behaviour because because v-select has many options and this is sub elements.

**Comment by bogdanciuca** [comment]
Sorry, but I completely disagree. 

First of all, the text field is irrelevant. I added it to the repro in order to easily focus on an element that's before the `VList`. 

Secondly, similar to my use case, `VListItem`s can be links / buttons and can be used for navigation. They are not input elements, as per your comment about `VSelect`.

Lastly, this seems to be a regression, it used to work as expected in previous versions of Vuetify (e.g. `v3.2.x`).

**Comment by KaelWD** [comment]
Lists are generally navigated with arrow keys instead of tab, you can add `tabindex="0"` to the items to override this.
