### ISSUE TITLE
[Feature Request] v-select auto scroll to selected item

### ISSUE THREAD

**Issue by examgoal** [vuetifyjs/vuetify#17881]
### Problem to solve
When we open the v-select item if we have many items behind a scrollbar will scroll to the preselected item.

### Proposed solution
Scroll to the selected item when the menu gets activated.

**Comment by websitevirtuoso** [comment]
yes this is good notice. here example to reproduce in playground

```
<template>
  <div>
    <v-select
      model-value="Bar"
      :items="items"
    ></v-select>
  </div>
</template>

<script>
  export default {
    data: () => ({
      items: [...Array(120).keys(), 'Foo', 'Bar', 'Fizz', 'Buzz'],
    }),
  }
</script>

```
