### ISSUE TITLE
[Bug Report][3.3.10] When setting Blueprints, the v-btn text color is the same as the v-app-bar color so that the text or icon cannot be seen.

### ISSUE THREAD

**Issue by regchiu** [vuetifyjs/vuetify#17883]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Apply [Blueprints](https://vuetifyjs.com/en/features/blueprints/#blueprints).
2. `v-app-bar` set `color="primary"` then add `v-btn` to `v-app-bar` slot.

### Expected Behavior
The `v-btn` content should be visible.

### Actual Behavior
The `v-btn` content is not visible.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU81uGyEQfhVKD06lsDRyerGcKr310HOrKOTA7o5rWmARjDeOLL97B3btrh0fUvUGM98PDB+PO95vAM3qpfqV+IIbF7qIbMeaCBrh+9Bje7aKnWOzETtT/gh07fy8LWu7gRCNx0RI5WFbsE3nE7IRw+5OLa52yjN2JC6yrvL7D8rza/4lhIp4dL4lgguWaJ8zfNkLHUJZHjai1pGcbBfvFCcpp+OL4gwNWqAKKTFCKD6SiHZQZO+JDr49dgbJXqOOk9qkevR5XhuEieaIS0F71lidEmEQtijWnwj17WEpc+tUVF7wulw8kQ1a3LKinTZ1uaW4yR7QG/YA61dOdPgaPTP0GMR2rRFth0n0ENE02hI1mxLk74DkyczHUw2THl5h2NP6BErb1EQTkCXAzfBKx9REWE1TU2LCxoS49JPSQYir2VewtmM/umjbdzPKAl2nSJIYxWJQE04HCm/nKR4lRGpsJMUXrFRyjVzyXvE1YkgLKZvWE60Fa/pYeUDpg5P3BJNx49E4oMm4+3k1r25laxJOyxUkJ+rYPSeIJKL49cQmx/kNViOyONx8HCzGmrC6Ttnjovbke/27jTX1hC+Nb2FbuXMbSfeiSIhI/wEi0H952+TOaNPpnbVeTTC77+nHl5e1xv9OZ4/apHLdx8Mx/2+4RS1LPZEn31/zclSyHhj86Q/DE7FQ)

**Comment by websitevirtuoso** [comment]
=)))

Everything working.
By default v-btn doesn't have any color and this is expected behavour in vuetify3.
here working example
```
<template>
  <v-app>
    <v-app-bar color="primary" title="App bar">
      <template #append>
        <v-avatar>
          <v-avatar color="white">
            <span class="text-h5">LY</span>
          </v-avatar>
        </v-avatar>
        <span class="pa-4 text-subtitle-1">Levi Yeh</span>
        <v-btn color="teal" icon="mdi-dots-vertical"></v-btn>
      </template>
    </v-app-bar>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const msg = ref('Hello World!')
</script>
```

Set color to your v-btn

In my project I had the same issue and fixed it via config we can pass default values
```
defaults: {
    VInput: {
      variant: 'outlined',
      density: 'compact',
    },
    VTextField: {
      variant: 'outlined',
      density: 'compact',
    },
    VTextFieldMini: {
      variant: 'outlined',
      density: 'compact',
      VInput: {
        VField: {
          style: [{ '--v-field-input-padding-top': '8px', '--v-field-padding-bottom': 0 }],
        },
      },
    },
    VSelect: {
      variant: 'outlined',
      density: 'compact',
    },
    VAutocomplete: {
      variant: 'outlined',
      density: 'compact',
    },
    VCombobox: {
      variant: 'outlined',
      density: 'compact',
      VChip: {
        density: 'comfortable',
      },
    },
    VTextarea: {
      variant: 'outlined',
    },
    VCheckbox: {
      color: 'primary',
    },
    VPagination: {
      color: 'primary',
    },
    VCard: { elevation: '3' },
    VCardActions: { VBtn: { variant: 'flat' } },
  },
```

**Comment by websitevirtuoso** [comment]
I hope it will help. so this can be closed

**Comment by regchiu** [comment]
Thank your help. 
But if  I do not set blueprints, v-btn class is not applied `text-primary`. 
So I think it might be a problem with the color?
