### ISSUE TITLE
[Feature Request] Boolean prop to show a searchbar inside v-data-table top slot

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#17888]
### Problem to solve
Thanks to this feature developers wouldn't need to create a wrapper component around `v-data-table`.
#### Example without feature
```
<!-- DataTableWrapper.vue -->
<template>
  <v-data-table
    v-bind="$attrs"
    v-on="$listeners"
    ...
  >
    ...
    <!-- make slots available -->
    ...
    <template #top>
      <v-text-field
        v-model="search"
        label="Search"
        icon="mdi-magnify"
        ...
      ></v-text-field>
    </template>
  </v-data-table>
</template>
<script>
export default {
  <!-- searchbar implementation -->
}
</script>
```
#### Example with feature
```
<v-data-table
  :headers="headers"
  :items="items"
  show-searchbar
  ...
></v-data-table>
```

### Proposed solution
Add a boolean prop to `v-data-table`.

**Comment by websitevirtuoso** [comment]
This is good notice. I will try to help but it take time to make it.

I have the same wrapper with the same implementation in one of project.

**Comment by nekosaur** [comment]
I'm not sure this is the way forward. As soon as someone needs to customize that search input it becomes a lot more complex. Not to mention if they want to prepend or append some content in the top slot.

**Comment by websitevirtuoso** [comment]
yes this makes sense. let me know if this will be valuable and I or maybe somebody can work on implementation

**Comment by simionato-mobisec** [comment]
> I'm not sure this is the way forward. As soon as someone needs to customize that search input it becomes a lot more complex. Not to mention if they want to prepend or append some content in the top slot.

Don't you have the same issue with the v-data-table footer?
