### ISSUE TITLE
[Feature Request] Automatically apply rule(s) and style(s) if input (text fields, textares, selects, ...) is required

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#17887]
### Problem to solve
This feature would avoid to repeat same pieces of code.
#### Example without feature:
```
<!-- rules which checks if value is present and not empty -->
<v-text-field label="Example*" :rules="rules" ... />
```
#### Example with feature:
```
<v-text-field label="Example" required ... />
```

### Proposed solution
Apply rule(s) and style(s) dynamically.

**Comment by KaelWD** [comment]
It isn't clear exactly that you're asking for here, you can already apply props en masse with https://vuetifyjs.com/en/components/defaults-providers/

**Comment by simionato-mobisec** [comment]
> It isn't clear exactly what you're asking for here, you can already apply props en masse with https://vuetifyjs.com/en/components/defaults-providers/

I edited the issue (I forgot to add the `required` keyword), I hope it's clearer now. By adding `required` to the input the developer don't have to manually add `*` and related rules (which checks if value is present and not empty).

**Comment by KaelWD** [comment]
This is pretty much #17192

We won't be adding anything like this preconfigured, the required attribute is mainly just an accessibility hint.
