### ISSUE TITLE
[Bug Report][2.6.16] Would be usefull if VDataFooter had color and itemColor props

### ISSUE THREAD

**Issue by lukamilikic** [vuetifyjs/vuetify#17894]
### Environment
**Vuetify Version:** 2.6.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Would be usefull if VDataFooter had color and itemColor props for VSelect component nested inside of it, since it pretty hard to edit trough css only

### Expected Behavior
You can pass color and item color to footerprops in vdatatable

### Actual Behavior
There are no such props

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtGelu2zb4VTgjqOzOlpN1xQChaZu6KxCgaIIlyH7YQaFYtM1WJjWSSpMlBvYOe8M9yT5eEnX4Shu0kETyu296/NA5ybLwNsedqEOWGeMSPaApx7HEVzmWZHaPVmjG2RIFcEh9Bwjf6XNTRoVEdhUdV6G6DxMqF3iJI8CX4Fmcp/LSfAcpmS9kgFZ9tOpNaKdvCQ+WcRZ+EYwCKwCN0MRuiEkHsKgVtQYE1feks5AyE9FwOE0ogCU4Jbc8pFgOabYcvoVjQ55TSZZ4kLDl2xfhi/DXYUKE9JdDLJaDG86+CcwByaTT98goOXYgZU9qCkeHhoRdG6TxjVA0GriHQPAW8wHHNMEc811FqoH5YtW2GqIp6qsJXYHCU0K/ipqup0LreeyY/D6ZNTaF6tpQvHofy/gDYxKYkaJ0tiAc+lsiFiKY0AkdDtGIwRGKKdif2tNXFzjFU2kdMgRYs+CeAOpOnoJ7eufUp7f7Tvqb8OWIXt5n2KOX4z7479UnlsCLfowWJE1Axyecx/cjRqVisI/OOcsUrB8tJb0HpGQ8j+eExpIw2tffZ5l6B2D1cSrxUpxjDoew2agH3lAq3nykiuhVnJIkloz7x83RITMEfJA5lhcpk8VhEB/+5ZKkwwVOM8yN+m2I28BVegjxHYiaqLhGiMY6kG8HQDkezLTtAnBvtZcBU6KIV8tC8Y2QYi1CZzdflCFjUWjulaeS1zZUEOL4r5xwnERIcjCGWV7ZZ1YodFf8pQl2JEEaZmnKol2hQGd1FqFuDx2/Rt3xyz46OoT/8BwcXfccAcdbYUDNYNMNxteO1YzjW+XHDQYuJCd03uQgOFAgyjC+SGBcuScaBVJHMyNc7ItHw9QRpfHeeBRIHY1vqUvgdw90NsBC5c02EdWxbaJ2kqY/liAgrNMTC/btg9LeRxBdnYnQO8ZSHFPvwCjnkJlatyFDxzcpLv1/zQHf/+pHINx+gGYdlrqEaPgc2bfzkz8u0ZH9kAsioNfI0wQt469YfdO5QIKhZT5dIBwLAuVTn52ylPHducs4Wcb8HhJe3bKj70JkHs+HuuDarDiFYpZLlWQsUqvvT6AJpWtdrrq9CN0YlZe0OZY5p1oNoc2mFWdBr47RIXp8dOeNxoqjSt3o+Qbw18dms0ymZv8jpnO5aCL2zincF5Jl6BU6rCrRidue0oSWNKb34+t2OVuybgjdYdcIoNJqAQYGm6GuMhCb2WqDjo+PUcB0BQh6DrHZK8FwKnCF6BzTdnYtWehVDaTqWkthnYWXWC5YUlaHPAOnLwUGdiJkeOp5jqUIH+Alkd3AAESuaPdtDQuhJSJz2n2Aftm3Yl9h61VYgXJLdZLQhoX6U6VT4aj7oOM5Qkc1eRSScygbhOViHzxNrxu04nYe/3S8P7fidYlxL7w1Zx4xGA1acI8WMYUY9cOm6/tohGi+vMF8G2Ufpr9W/2sdEbxIP1vIWUf2wkLqTO1FxOAIvbEO59JyCmKFstuIOVvResglPRcCRfJD6DZOc2DfbBTrNvl5ovhi2Pbdt1CKYYZUqGCCXJuk3GEzcrrkcnp+fuagtiQcE6IuW/gIwtTkOciiR0WuoHmaVkF+qsDMCHTCJMuYSkXqGVoRQM36rdcrhPIBx4cwDrUlvAMzPP+ewoRMIRckBNo235pCgpdOR9D4QIapNt6fPwsz/JRG6Lsxrswx20yu7e2Zt40tO2VVGEMolpL7TbH5C2JOYjUL4jSwwbY3D15zoP+qo4X7s5VU9e8KYUsjU0Fie7eoYpjaCW272tqCJPg9ljFJAdabFAo15JK1biwJ/ZMkcgF2++1ldleayfzB0Kn7nV+i6rptZqx3w3uLFLZPKRSpv9frr9JjWywUdOCSbEueW2uNVWmo62b+KvvMUzpjjYCf2iE62jBTQ+iMg//++TeAkPGj32tOXB50SaC9hfEJm44l5iDyWtDiTBOQZVvhWFZNHJt6q2fP2vm2uveUZppvzdUmjlVprINAe3bsKw2atbV93OPjDj2e+Xvj4/Q32itrVTFgS2tyJ82BmLIMJ+puQowDBTFQBaw0vqE53nz4J1vdtTJMgVWE+xX5V70KUrjyWp+d3LDicK1HWyJdmdayMP5abiv29RTyg4WEkvykkjNtLzalYSsFx/HfzAVmtJmmZPo1Qh9yOjU3YGXatiNPH24CoFpEUOv0nIWIvhQwXzAv6FTRPi/U6xRc6FVEaSscJX33Vrh/Y1iuZEHDViPRm36rsQzpPYk5SG4ww2tfrV2evT+DESiBoZbcES8wNIS+Ibcg+n0jiJ+WGyle693P2957W+Wu1m399Bj+yKZwXfW3VkobTtV5tFpEOYGxaK+lXKhdNRSWrJhcf4NnjEOTublK1ApEPAM/3QHGQRkiYZaLhQlYy1C3PlFXxqJ6q1SZUFQfeNRopmoJpv12BEgo9EGzF3OnuUxdI++u8oqka28IHagaD927VssuUroBrc5Ay43Fk0RUTO8uohPJiehEbhOxSLmN27JKqrUGz6lYkJlN9E1tFPooJupquG81+j460RejDaVsUIu7NHVqKW5jS2hfM7uYvxDYKW2LvC0XR+UM7VJp65WTmUafqCol+T6aKjTjVOVUV9XUulrZGKS2lc0ts5pKgWJgXNAfBSBzmsVGVNRudouusc6JyGIoyTb/+pYKJbNTPOTeLSPeE+XR3lUTR695U0LbpZn5sVJfB1bK+x6Nygbuyivm0oz2BzAdBH11dYsz4MFzpiI6GvcW3eah6pzTckBXtmLdlD4l/KrXWfU7+tdb+HXU/Izauf4fEagb2g==)

**Comment by nekosaur** [comment]
Not a bug. Also you can use defaults to set color prop for VSelect inside VDataTableFooter https://play.vuetifyjs.com/#eNqlUstu2zAQ/BWWF6WAJbZIT4YapEBR9N4gPUQ50NI6ZssXyLWTwPC/Z/mIITuXALlI3NcMZ5Z3e77bAqr1c/cv8iVXxruAbM/GABLhttTYga2DM6ypvc1gBwtPuXV0NiKrBfb9dPBiP1jGJljLrca4ZDlk7PanRHkjVxp+OYcQjgUq/QENI84yjCi0o57GB2VkeG4Wr6VDPZV/+eIGDBzHK/VNSTZaPWywzKfuw+fB8gX/4X1HAkh+j2C8pvtfpZZ+10rv8zEHJBWlshBqKicnktJi0nLVi5OwzlHydDBlCm4vZnwUxjEojywCbgvtcR0B1vMl5AUkY5L3Jj6Q79Rx0fwGrR3764KePjUkrhcFksBIZ0FrjfS0bGdJb3ZpqIU48KNvQ3oWKR74BtHHpRDjZGlsAq12obOAwnojrqlNhK1FZaCdnLm+7C67b2JSEefpDqJpV8E9RggEMvC6uEyTHso7qGpnZvj6pVDUXKvlKiaON9iCCHcQ2gB2ggDhvZLOxuayzkpvpOXHRW+LDNfK/o9nXo8x+3z3esmPac5oCeo+MR4WPF+UqMsEv38Bl7JLyw==

**Comment by lukamilikic** [comment]
Is this possible in version 2.6?
