### ISSUE TITLE
[Bug Report][3.3.10] VExpansionPanel eager prop not working

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#17890]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open developer console and check the contents of `div.v-expansion-panel-text`.

### Expected Behavior
Content should be rendered.

### Actual Behavior
Content is not rendered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlULFOwzAQ/ZXIcxODylSFqgzsDIil7uAmBxjii+W7hqKq/47tpBClHSqxRLn3fO/de+uDeHCu6HYgFqJksK7RDEuFWVZ2uXYu/aahapG1QfADFMCXx73TSKbFJ43Q0C9zzmVsuIF7JdKkRAb6bSR1aeUZ9ryMn1JeYkZeU/7vwilzOrGU00AR6fOWctRDGKnyxnFGwDu3LGU/BkrMhLGu9Zxb7YoPajF0eIhaaiBIiUWWkIiFkuOsxDuzo4WUVY1hrYbGdL5AYInOylV4Jv0O2VjI69au5sW8uJO1IR7DBZDNt779IvBBRInZyIbN6/cVVsPL5HB701sMWN7oLUWPM20ZDDvwuQeswYO/NtJkbRxrQp1Fi+5HhcdQeGPwkyZdV5R6Xp+O/F/mpBalNtHxOBPp0GDdb4jND+LyEiU=)

**Comment by prashantsinghb** [comment]
Workaround
```vue
<VExpansionPanels>
	<VExpansionPanel title="Panel">
		<VExpansionPanelText eager>Text</VExpansionPanelText>
    </VExpansionPanel>
</VExpansionPanels>
```
