### ISSUE TITLE
[Bug Report][2.7.0] Default $tab-text-transform is invalid

### ISSUE THREAD

**Issue by jason-wolfe** [vuetifyjs/vuetify#17902]
### Environment
**Vuetify Version:** 2.7.0
**Last working version:** 2.6.14
**Vue Version:** 2.7.14
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the codepen link, see that the tab text is not uppercase.

### Expected Behavior
Tab title is uppercase

### Actual Behavior
Tab title is left as is

### Reproduction Link
[https://codepen.io/Jason-Wolfe/pen/gOQQRKq](https://codepen.io/Jason-Wolfe/pen/gOQQRKq)

### Other comments
View the `.v-tab` element in the Chrome inspector, and you will see "invalid property value" on text-transform, because it is set to `"uppercase"` instead of `uppercase`.

This was broken in https://github.com/vuetifyjs/vuetify/pull/14545

**Comment by jacekkarczmarczyk** [comment]
duplicate of https://github.com/vuetifyjs/vuetify/issues/17799

**Comment by jason-wolfe** [comment]
Sorry
