### ISSUE TITLE
[Bug Report][3.3.10] Japanese search results are not displayed correctly in v-autocomplete.

### ISSUE THREAD

**Issue by nayo0513** [vuetifyjs/vuetify#17910]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type in Japanese, press Enter to confirm after conversion and all items will be displayed.
https://gyazo.com/f79e0ffdfb7c26540097007bbafa82f2

### Expected Behavior
Only "星野 アイ" is displayed in the search results.

### Actual Behavior
All items are displayed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1rE1EU/SvXtxmFzIxSVyEt7UJw07WLTBbTmRt9Ou+D914iErJIUIoIBV0JKloVF6JLKSL4Z0ZT8y+8701Cp+mm0M0w99xzz7n3zPQnbE/rZDxC1mU9h0JXucOdTAL0xnGudXgNRaGky7lEs4IaxsipQtEUOlzDAFV+gNV2xvbaXXbW73JyskToR4vX75eHR1DPP9bzz1EH1sDi6Zs/P5/Rc/HjpAWfvvxw+vvo3/GngL19vvzyDerZi3r21QPLX6/+nrwjYB6w7x7bv7Nfz47r+WE0OFthp5ee3319JsHn7wzEEEMvbcVDpS0M1w4sulGTEhdaGQcTMDiEKQyNEhBRspGnA5CudSDsfdj2jOvRXawqBfeUqcpr0Q1v0EiSGOuwRi0WuU4eWiXp80y8SrZq2Ix1ISAeIxdfZ+yBc9p207QoJY2VWPGxSSS6VGqR7hItNSPpuMC4VGJ3K9lKbqclt64NJ2hFfGDUY4uGRDLWadk4PnxyCasVMzjcutlYrLCY/g7rPS5op2Q4RhMblCUaNJc9aWOsfdZG68Jp3n2aySkFXnH5yG5kXdiQc3+95NVuDmpeauAdpx0WFiXrZoIN/gOiP0Wt)

### Other comments
This may occur in other languages.

**Comment by yuwu9145** [comment]
Doesn't look like it's language specific

![vuetifydemo](https://github.com/vuetifyjs/vuetify/assets/5698884/72baff89-0f32-4723-ab38-8ef3bfcb5a53)
