### ISSUE TITLE
[Bug Report][3.3.10] Version 3.3.10 still has memory leaks during ssr in nuxt

### ISSUE THREAD

**Issue by Nisekoi5** [vuetifyjs/vuetify#17917]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
node version v18.17.0

Run debugging after building with the script's build command
```
node --inspect=9229 . \.output\server\index.mjs
```
Print a snapshot of the heap once
Visit the page 1K times using the stress test tool
Reprint snapshot after clicking garbage collection
I get the following result about 30M memory is occupied and can't be freed.
The memory contains a lot of string objects with duplicate component styles and some arrays.

![m1](https://github.com/vuetifyjs/vuetify/assets/49276902/c8f43e40-5a97-4f55-81c8-29d68923926e)
![m3](https://github.com/vuetifyjs/vuetify/assets/49276902/4a70afcf-dc7c-4094-8f5b-d107ecd8fa13)

### Expected Behavior
Memory is being garbage collected normally

### Actual Behavior
A lot of memory was not freed

### Reproduction Link
[https://github.com/Nisekoi5/vuetify-memory-issues](https://github.com/Nisekoi5/vuetify-memory-issues)

### Other comments
I noticed that this is an issue that has already been raised
https://github.com/vuetifyjs/vuetify/issues/16156
And saw the instructions for fixing it in 3.3.8
https://github.com/vuetifyjs/vuetify/commit/d2bdc7f3659f6b0c14a94293619fce01824e0927
But I'm still getting memory not being freed, is this expected?

**Comment by tobiasklemp** [comment]
I finally found a fix for this and created a PR. The main problem is that watchers which are created in a nuxt context cannot be unwatched automagically by vue, so we need to unwatch manually or just watch it on client side since watcher are not run on server anyway.

**Comment by Nisekoi5** [comment]
> I finally found a fix for this and created a PR. The main problem is that watchers which are created in a nuxt context cannot be unwatched automagically by vue, so we need to unwatch manually or just watch it on client side since watcher are not run on server anyway.

This PR worked great on my code, mine made 4000+ accesses and the unreleased strings and arrays no longer appear!
Thanks for the PR!
Hopefully the repository maintainer will check if this might be causing other problems!

**Comment by memic84** [comment]
@tobiasklemp we are running the latest version, but still get the same result. Exactly the same data as in your screenshots. Memory goes up very fast, and we have excluded all other plugins/code.

Possible the problem persists somewhere else?
