### ISSUE TITLE
[Bug Report][3.3.10] v-infinite-scroll doesn't work at all

### ISSUE THREAD

**Issue by rraammiinn** [vuetifyjs/vuetify#17913]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
-

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtWN1u6jgQfpXZSEcJWhzo+ZF209LteYe9WZVehMSAwbEj20lBKO++M04CgXb3UPWcuw5qIZ7/mS9hhsdD8L0s47riQRLcOV6UMnX8fq7mCpDufmMM8Ni6e2AMj/1hzYRaCiUcZzYzWkp4kDrNZ/OA3uYBWJFzvFpot54HvVZvHGq21AbZERooxiBUzncjfAO6tqiebPke+XR5VEcDuaghyWRqLTIfw3LHPoedOnyCzzCbzWAKf0G4WLGV4XsmxWrtuEIxSCAMnwbGwDsDVRULbuBwaC+b5uhsgt76yCeDutDli/x7wctqta8TizLoEyhSoXxAx6JmqcnBur2k2j2L3K0TWArHMq0wC3dLlem1D0uji390lWTr1MV7XY2B1BNnKt6gYF9jYlNp6d2X1vGd687jwq4wAsqHdIehkBRbCi5PAZXaCie0oph2PL/F5jpdJHBjeHHbRfvn9BNGeapxQngQatUhAz8NuTlXaJI6nemiTDM3ZNapEamiUK2WGmORkiO0TgIyXXBJdeTWpis+ZKVlyVWOTVLcMIHlI7FcMIunQzmLAUmOMFH8dLhG7LKcu1RIezp9yKTItsnQMoV2YbBmhc7bqKi0PcOX+FTSU6E9yFqonIGMXne+8GAzXXJSiQkwh1bxWO76+bY9KVKzEtibtHIajxDHMfW0k++536hX/dGOdWb+oK55lQ5UZ1pM8qUbGr6b+Mh8mHeIf1E6sNxVJZ6IotTGwQEMX0IDZA9CfLiEqDpXkwlgM6xr0ThDmejRnxIdEMQevmOsXRJKbbI8A8B/gt6PlGevknoPbX5A23fT/lqq3kg++QpfWT6g51dpN6CubBDHsdqslFqtO9oWXzfqW3/V0//XR15J5mfQlYVZvJ1WP4XCZnwO6mUqbYfqsyblKPA6mD8w/R5ME6xTq8VmLTabD4D/eoCfntp6k2c61/iQ3uQ4dOCzuyN8gp9Bn+gD3m+E94sKnhEVGZ/nH4D/BYD3eH8atZMZflxWKqNhGAcflUcjHJi6+8FPNnGdyorHZWXX0fkNgn8ts0FbqIKGB2MRcv1QFIadp9MLZWivwFnxGpqr1qBfqGBG01j03Zh07ye86ACSqxWNfjfTKTRjiLZjqEcwu4cafoebkXd/zJFGd0Al2urGkGvFoRlBNySSIy15LPUqwqHND/mvR0lJ9UMcpoMj49+i4LpyUeRddwa77WwJEfnzS11oXWpcePTZU5tkagym+B/pnWfn69E24HH6BAwilGDIHITW74adHJp+xDsKnYzpzhpwnoY6DXD8kr8IG7Hxc4OOUxexmxH1CP/qH0Y9OPHRo9fzqPtNpButsbVRqLcXncJoECfTweGLpvOczF/Q0MxQYxDVUaK9w94EcdxD/PJxH4yDdu9gRVrGG6sV/pbhq46/IXgGbr5J34d5gPsIXc+DtXOlTSaTLFeohoubqE2suJuospg8oNjEVMohSFmui4cv8Zf4K25s1g2PY24LtjD62XKDRuYBfjce3Tix3F/hqpP0Hm6mrYvujOGaa8nHC9sTdFjjfmsQZdxwc21KF2rDtC5YL1Ij79ioBguOO/PWXtQ6s77OuNK1Qb4vZ2+NTCFim6AZBz5QdN1qBE//Alu+svg=)

### Other comments
it doesn't even invoke load function .

**Comment by bogdanciuca** [comment]
Seems to work just fine.

**Comment by yuwu9145** [comment]
Information being provided doesn't show any issue.
