### ISSUE TITLE
[Bug Report][3.3.10] Autocomplete with "chip" and "not multiple" not working properly 

### ISSUE THREAD

**Issue by bujji1** [vuetifyjs/vuetify#17920]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Firefox 115.0
**OS:** Windows 10

### Steps to reproduce
Please use the below configuration for auto-complete to reproduce 

    <v-autocomplete
        v-model="friends"
        :disabled="isUpdating"
        :items="people"
        chips
        closable-chips
        color="blue-grey-lighten-2"
        item-title="name"
        item-value="name"
        label="Select"
      >

### Expected Behavior
1) Click on Chip Close should clear the input box
2) Chip click is not showing clickable cursor pointer 
3) After selecting the item, it is not showing in the input field in the expected format until we focus out from that field 

### Actual Behavior
1) It should remove the content fully from the input box
2) Chick close should have a clickable cursor pointer
3) After selecting the item it should display in the format shown the format mentioned in the given template

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVk1v4zYQ/SuELkkAS/JXUEBwsptugS4KFDkkRQ9xDrQ0tphQpEBStreB/3uHlGTTstUY3ZMtzsybeY+cIV8+goeyjNYVBEkwM1CUnBq4nwtCZuswpSqzfwlJuKQZE6u7ecD0X2VGDX7Mg9qYSi4VWha8gnCl4EeYUfUOIhztPTjVGj2KbUgrI0lhwtGwNRZ0G25YZnJ0mI6bZVeCK0LJzSG+jmuMzmzxUol1g4F2mZB1WMgMOIYsFQOR6TaZI5MxTRccsrNsnAdDKWzCEiQi+6Y0Z6X2Prl0WGF3/UQTzla5QVHGPprNExpmOKCvoMVRKmdcU0Q4Y+R04fg9AYfUHCx7bVCddj9RDs2lSWyNGPJBSiVLPXAJyM7Ts9HU+vlLVs8FE1YvF+nX4eQqFZSockjX1FBL2yJHim6ieuUkwMDW+G5ddshjFteF+IRi74T+B08LewlPzrQJrfHnyX6xNL700m122PM8ZYx+ulqccV0pWZVn1NmX3ydRu3TcJW1r4TL2Vt3rVmts9kZWlCZja5aBcnna/3PR2YCZThUrjYOAbSmVIRksacUN+aiTYGvR65v2y7aF0IZolWpyd1glZJSQq9yYUidxnGbCDiTDlj/edIRVx6ygK9Cx5avjUfRWrq4Gh9jx5bHjbuzk8thJN3Z6eey0G3t7eeztcezucPIVmEoJX0a7zW6eQUKMqsDL2MzBhLy8equH8ZeQJeXaj7AnFMv8k2XCji7yTcHG51DPRgT0D2Yck+fH3x4T0rJbMZNXC0drT7L9FzOtKyQ6uv1lPOqgfJAcKJ46rOB3e/7J6IrsvOwEPZoKn6jIFCUPGS301YC4dvHCBqTuysSdu5fRax/OA2fkmxRCqgtgxr0wzwrWUpHvVGgQnwNN+oGq9B0UeSpQwv9RkBOx6d36OJxz6Kg87lX5V8WMoeS75OakmHG3mGkvqT+ogJoS+Rzmth9G5qJHmROU/h1vTs7fjHN27vCcQHU2y28lN7jtruVAdFUUuHMLBfAP+D1jWAGyMgkRFed+T7sfXKj/bahJ8+TQ2Yc2vcb3gDdP7QMEqHquYa9NznTU5Ljxr0i2JCeRWI3njvNYg2mBcGbf3ZMa75AcfdyQuBmQyXA4xAwtUsOg5nDMpQCTSzt49qkVFHIN1/bmOqbiLge8emGLmVzuZmpFbvFx6WLc1enlttzqoPs7Mrw5DtQlZynmsvYBGe3D/Dpd+bN4f5kFg4Az8a6jNy0FvotdifMg1fgW2I+7eeDP7zeNr022VpEAE4tyP+u+TqJJNBrG+OI07VqITzec8xbNQr3OxQ4zssLen2FBy07a2uBSN1rNA0Sy35/U8BXdYlUJu8NhJgtXzLSuxVuOQBfhAp8CGhSCzINGGpfGFnxBqk/pYo4T7BgTrkGFCncKFOCz6TJKnTCfVsd0Qq3Z7F2wGwQuDJWvaw5e/wUCSfsc)

**Comment by bogdanciuca** [comment]
As a workaround, you could use `clearable` instead of `closable-chips`.

**Comment by bujji1** [comment]
@bogdanciuca  - Thank you. That worked. Do you have any workaround for "After selecting the item, it is not showing in the input field in the expected format until we focus out from that field"

![image](https://github.com/vuetifyjs/vuetify/assets/10221950/94aa5011-82cf-4739-80bb-97ba6b6cf900)

**Comment by bogdanciuca** [comment]
@bujji1 Hmm, only solution I can think of is to use a ref and blur it on model update. Something like:

```vue
const el = ref<HTMLElement>()
<VSelect 
  ref="el" 
  @update:model-value="val => el?.blur()"
/>
```
