### ISSUE TITLE
[Bug Report][3.3.9] Error when combining v-range-slider and 2 v-text-fields for manual number entry

### ISSUE THREAD

**Issue by akhoury** [vuetifyjs/vuetify#17928]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try entering a value in any of the text fields before touching the slider, you will see an error

### Expected Behavior
Range slider thumbs to mover correctly and no error.

### Actual Behavior
Error: Uncaught (in promise): Cannot convert object to primitive value
and the slider doesn't properly work anymore.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9Uz1v2zAQ/SsEpxYwJQfpUsMN0r1jO1keKPGcMOUXyJNsI/B/74mybEUpkGSJpvt8793puHnmP0Mouhb4iq8RbDAS4a5yjK070ciosn3xBGo0Q77/fscjs17p3VG7B4aPwKJ0D8DqI2vTGEI4oNhpMCqxnY4JF0w6BjH6yPbamBHMN00bz2zlf+guEgjvooCCmVIkoxVE1gnSA+ZHxXO44sxqR96yt+SBrJsl2Xc9w7TxCqh0xxojU6JaJXYGDuypTUgzihRkA6IG3AM4Ahl7sozrmNcwY0bWWc0vvyd1tW+dqvi0oJNRS4dU4ls02sEsr8AljUfKN94SP87aX867WW5f5vEYgJKutTXEaar8iPo/IXyK+puPq1+X9MPGC7mczXgiY4ScdTk5b3JTE3UYquAQfEQSu5OtQfY8oCmJ8svX0WMsArbRXX2K9KJXbLNdjLHTYJxygJx1eaHhC04L+puKp+QdvbaMQ3tJqeKEMTRW/BExpFVZNspRJS1Hd7FwgKULtqR32h/i/W1xW3ynwROOIUG/KhUZrEfaVu5EhNr2gwkrw4x1SGTm8zwVJ6Tef0PCPZWVsXWoLQjlbdbybdAyCReQrKij3yeIBFLx84oyTS/4HVRvTUsUr6BL4usgigiOXnV/NO+baNY2nWqWejXZ+Vef+GnBcxstPkvm238Sv7KI)

**Comment by bogdanciuca** [comment]
This is not a bug. If you want to also use inputs to control the slider, just initialise your ref with values, e.g. 
```vue
<script>
  export default {
    data() {
      return {
        range: [0, 0],
      }
    },
  }
</script>
```

**Comment by akhoury** [comment]
Thank you!
