### ISSUE TITLE
ignore .babelrc from npm publish

### ISSUE THREAD

**Issue by pwang2** [vuetifyjs/vuetify#1792]
### What is expected ?

Link from https://github.com/vuetifyjs/webpack-advanced/issues/16.

**Comment by nekosaur** [comment]
When creating issues you need to fill in the entire template. And linking to an issue created on the wrong repo is just a little bit too lazy.

That said, we have changed the a-la-carte process for upcoming releases. We will start shipping transpiled es5 alongside the source. This should eliminate any babel headaches.

When webpack properly supports tree-shaking we will most likely move to that instead.

**Comment by pwang2** [comment]
Sorry about that. Kinda too late for me to make an update right now.   I will spend some more time to come up something more meaningful.
