### ISSUE TITLE
[Feature Request] VSystemBar on Displaying Content in the PWA Title Bar (Windows)

### ISSUE THREAD

**Issue by huggingsoft** [vuetifyjs/vuetify#17924]
### Problem to solve
When using PWA as a native app, you don't need to actively handle the code associated with custom title bars

### Proposed solution
Automatically push the portion that is obscured by the system reserved area in front of the reserved area.

![image](https://github.com/vuetifyjs/vuetify/assets/78424351/54503c72-a837-4e71-90c2-425e24f7e5a0)
![image](https://github.com/vuetifyjs/vuetify/assets/78424351/3456684e-fcca-45ce-8fc1-636bed2590bf)

**Comment by huggingsoft** [comment]
[Display content in the title bar](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
