### ISSUE TITLE
[Bug Report][3.3.7] Vuetify v-autocomplete makes chrome crash with Cypress component testing

### ISSUE THREAD

**Issue by RobbeCl** [vuetifyjs/vuetify#17922]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Open Cypress (pnpm run cyress)
2. Select component testing
3. Select chrome browser
4. Select the HelloWorld component test
5. Watch the browser crash or throw an ResizeObserver error (it alternates between the two on my computer)

### Expected Behavior
That it does not crashes

### Actual Behavior
It crashes :-)

### Reproduction Link
[https://github.com/RobbeCl/cypress-vuetify-crash](https://github.com/RobbeCl/cypress-vuetify-crash)

### Other comments
It only happens when the width is large and there are multiple items in the items array. It does not crash when running the application in development mode (so without Cypress).

To make it not crash:
- Remove 'abc' from the list
- Remove one character from 'abc'
- Turn on Transition stubbing (but this breaks the component)
- Remove the <div> which takes up a portion of the screen
- **Downgrade to a version below `3.3.7`**

**Comment by KaelWD** [comment]
I ran it like a dozen times without any problems.

**Comment by ThomasKientz** [comment]
@KaelWD please try with this https://github.com/RobbeCl/cypress-vuetify-crash/pull/1

With longer array, cypress is also crashing or sometimes throwing the following error when focusing on a v-autocomplete. 

> ResizeObserver loop completed with undelivered notifications

**Comment by thomktz** [comment]
I am having the same problem on Chrome with a v-select

**Comment by RobbeCl** [comment]
Yeah, I'm still experiencing the same issue. For now, adding the 'eager' property does seem to help in my particular use case

**Comment by thomktz** [comment]
@RobbeCl I managed to fix this by updating my vuetify version from v3.0.0-beta.0 to the current v3.4.2. There is some refactoring to do though, since (among other things), vTables have been moved from vuetify/labs to vuetify/components.

c.f. [this commit](https://github.com/thomktz/betterave/commit/c55685c4520873191f899bbb332972f93e908eee)

**Comment by RobbeCl** [comment]
I am already running on v3.4.2

**Comment by krignault-assessfirst** [comment]
Up! Do you have some news for this bug pls ?

**Comment by philly-vanilly** [comment]
For me it helped not having the autocomplete inside a <v-container><v-card flat>...

I changed the view wrappers to simple divs and the crashes stopped

**Comment by philly-vanilly** [comment]
I have the feeling this problem is memory related. The crash always comes again after it occurred at least once. When I restart cypress and the chrome instance on my macbook, the tests pass a few times before a new crash (I guess until a memory threshold is reached).


@KaelWD 
> I ran it like a dozen times without any problems.

If you have a single component running in isolation in a high memory environment, I guess you  don't encounter problems. But as you can see from replies here, the users do have these problems, because in the real world, the components are not used in an ideal environment. Perhaps you can at least make your CI a bit more battle-proven, like run it against your documentation page with cypress or something?

**Comment by philly-vanilly** [comment]
I also think this might be an issue of both vuetify and cypress. cypress does test the app wrapping it in own UI after all, so you don't have the same standalone, isolated environment as running the pure app. So perhaps the ResizeObserver leaks into the cypress UI

**Comment by halws** [comment]
Sadly, but it's still the case for us

**Comment by lehmat** [comment]
I have managed to get past this issue with [Cypress comment](https://github.com/cypress-io/cypress/issues/27415#issuecomment-2169155274). 

We are using webpack to build our application, so simple if statement into `App.vue` will do in development mode.

**NOTE!** this is only added in development mode. Production should not have such custom codes inserted

```
setup() {
  ...

  if (process.env.NODE_ENV === 'development') {
    const RealResizeObserver = ResizeObserver;
  
    let queueFlushTimeout;
    let queue = [];
  
    /**
     * ResizeObserver wrapper with "enforced batches"
     */
    class ResizeObserverPolyfill {
      constructor(callback) {
        this.callback = callback;
        this.observer = new RealResizeObserver(this.check.bind(this));
      }
  
      observe(element) {
        this.observer.observe(element);
      }
  
      unobserve(element) {
        this.observer.unobserve(element);
      }
  
      disconnect() {
        this.observer.disconnect();
      }
  
      check(entries) {
        // remove previous invocations of "self"
        queue = queue.filter((x) => x.cb !== this.callback);
        // put a new one
        queue.push({ cb: this.callback, args: entries });
        // trigger update
        if (!queueFlushTimeout) {
          queueFlushTimeout = requestAnimationFrame(() => {
            queueFlushTimeout = undefined;
            const q = queue;
            queue = [];
            q.forEach(({ cb, args }) => cb(args));
          }, 0);
        }
      }
    }
  
    window.ResizeObserver = ResizeObserverPolyfill;
  }
}
```
