### ISSUE TITLE
[Bug Report][3.3.10] Watcher doesn't correctly  report old value

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#17925]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
I am using Vuetify 3 with composition API and I am trying to capture when a value is either selected or deselected in a v-data-table.  My initial thought is to use a watcher to capture when this occurs.  However, when I use a watcher it seems that the old and new values are identical. In other words, the old value is not being correctly reported.

To demonstrate my issue, I set up a quick test at the link above. When a single row is selected or deselected, the old and new values that the watcher outputs should NOT be identical. The behavior is the same when using the 'select all' toggle.

Sidenote - In the example I am using a Record as the selection type as it better mirrors what I am doing in the real world code

If there is a better way of determining when row(s) are selected/deselected please let me know.

### Expected Behavior
For the watcher to show the old values correctly

### Actual Behavior
The watcher does not correctly show the old values

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVM2O2jAQfhUrqhSQSNJqe0pZtFUvrXpbrXoB1HWSAbzr2JHtwCKUd+/4JxDCoVv1Esfz+803M16eoq9Nk+5biPJobqBuODWwWAlC5vuENo37dZdSCkOZABVETmjgzSQbBrwi+6SWFfD7VVTr7Soi2dCuooYmhhYceiEZOGjgUBqolrGWNTxCKVX1E47xehVdzPMd0AqURvvwd6VlCN7q3DnUWEGyp7wF1P5m1VCnwLRKJLJ4wfwXsd7JQ+JB9cK+mnk2ZsJKPFHzbEAgXnWpWGOIxiQN4VRsEYBBbM6N1Y1UhpwQw2ZGDtSUO9KRjZI1ibEd8cDGHBtAw0fYjCysjVP+wMRP9ueenDzOGCuNc6KNYmL7JciQhWtZh197YkXakEArBkFMk6V3CvEwETMcchJ/k7ytBfnujONZr6acbQWqtaHKXMQaC7Btz8mGcg1n+Ssc0dgCCqLOnevpEJDrZX6ubrlGaGNYWCcGopeMGNMKivI68o1LMXapYPMXl3PI3mW7Y2cXB3+Ivp/q3HZu7qd67smfDWpaLALhp9H058t1N71qEC5WsI2fdkwTu312WFtcvwKI3IM6KGYMCFIc/UxhiwKl7jrxYHtoATvVR1GSiYDDL8pnRPIKzym5X1wI8AAEpn9GM7L8cPLWNyub1rSZvFnftxRJmnbr5zB+fRBpg2AOG8Sn+qcgSIKVtXbYnxFGNyMYp+sNzq0jFUCTE6PQ0jUHeZhnfidxA6NZ5NcrwVzpi5YCX0BXLr4hToGbmvcErCLcOHvHx8eYRudZVlYC3fABY3uVCjCZaOrsAc0y1QrDakgqWT/cpXfp56xi2gzFKeg6KZQ8aFAYZBUF0C6NYZvjO1IFS5fh00efIsgSTgttc9zEzjAhTkmiQOD2gnpvSSO3YVkj1U1p7p1ZiQ4J50y86hHXpXY8h7X+35pdtLCJXdTNIgcUU3uPaP0HWC40zQ==)

**Comment by KaelWD** [comment]
https://vuejs.org/guide/essentials/watchers.html#deep-watchers

Use a shallow watcher, computed setter, or explicit update event

**Comment by UglyHobbitFeet** [comment]
@KaelWD I have seen the watcher page you mentioned in your link before creating this ticket.  If I use a shallow watcher, the watcher never fires.  I am using a Record type to better manage entries that dynamically come and go.  I am not sure what you  mean by an explicit update event.

Thanks!

**Comment by KaelWD** [comment]
`watch(() => selected.value.someRecordKey, (newVal, oldVal) => {})`

> not sure what you mean by an explicit update event

`@update:modelValue="onUpdate"` (**before** v-model)
```js
function onUpdate (newVal) {
  const oldVal = selected.value.someRecordKey
}
```

**Comment by UglyHobbitFeet** [comment]
The issue with the code sample you provided is that I don't know 'someRecordKey' because it's dynamic.  So I can't explicitly call it out as 'selected.value.someRecordKey'.  I was hoping to be able to watch the Record type and when a new key comes in (or an entry changes in the array for that key) I could capture that.

**Comment by UglyHobbitFeet** [comment]
Interesting. I'll give it a try and let you know. Thanks!

**Comment by UglyHobbitFeet** [comment]
Unfortunately I do not think that works. If you look at the playground link, the old never gets captured to store it.  In other words, once you click a checkbox the watcher does not have access to the old value, so you cannot save the old value as you mention in your code example.
