### ISSUE TITLE
[Bug Report][3.3.10] contain class on v-img not working

### ISSUE THREAD

**Issue by stanig2106** [vuetifyjs/vuetify#17933]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
use content-class props on v-img

### Expected Behavior
the class go to the \<img\> html element

### Actual Behavior
the class doesn't apply

### Reproduction Link
[https://codepen.io/stanig2106/pen/LYXMJzB](https://codepen.io/stanig2106/pen/LYXMJzB)

### Other comments
https://github.com/vuetifyjs/vuetify/blob/4ec7f13e39f4e6da4dc70910eeab1852f47363d2/packages/vuetify/src/components/VImg/VImg.tsx#L203C5-L207C1
https://github.com/vuetifyjs/vuetify/blob/4ec7f13e39f4e6da4dc70910eeab1852f47363d2/packages/vuetify/src/components/VImg/VImg.tsx#L212C9-L213C55
```typescript
// source code of the bug : 
const containClasses = computed(() => ({
      'v-img__img--cover': props.cover,
      'v-img__img--contain': !props.cover,
    }))

// ...
<img class={['v-img__img', containClasses.value]}
```

the classes is never applied in the source code

**Comment by bogdanciuca** [comment]
If you want the css to be applied to the image container, use `class` instead of `content-class`.

**Comment by stanig2106** [comment]
`class` apply class on the div around the image

API doc : 
https://vuetifyjs.com/en/api/v-img/#props-content-class

**Comment by bogdanciuca** [comment]
Gotcha, I raised a [PR](https://github.com/vuetifyjs/vuetify/pull/17939).

**Comment by stanig2106** [comment]
@KaelWD 
The documentation does state that content-class is to 'Apply a custom class to the internal content element.' 
However, the debate isn't about that, given that content-class isn't applied anywhere. It just isn't applied at all...

**Comment by KaelWD** [comment]
The content element is only rendered if the default slot is used.

**Comment by joshuadabejero** [comment]
Do we have fix on this? Got the same issue:

```
.hero-image > .v-image__image {
  filter: brightness(10%);
  -webkit-filter: brightness(10%);
}
```

**Comment by Tyler-widd** [comment]
Same
