### ISSUE TITLE
[Bug Report][3.3.10] Multiple prop on v-file-input

### ISSUE THREAD

**Issue by simoneeek** [vuetifyjs/vuetify#17932]
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I think that multiple prop is not assigned to some funcionallity. 

### Expected Behavior
I expect that in array will be more than one file.

### Actual Behavior
I can insert only one file although multiple prop.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMFOwzAMhl/FymUgLQ1onKYNjedYduhaFwJNGiVuAU19d5y2k6ruMolb/Mf+fv8+XsSb91nXotiKHaH1dU74qh3ArpO598NzKIrGUW4chkkC+Lk++LcyNUrjfEuwtW1Nxte414JCi1pAJ21TYs2Cje9cqytWLblJGW13arYOl7EIxhNEpHbcyljfBIILBKyghyo0FlacZJXaAZgbCdgP9qnj4Xh6TNARwwCxFiNB2txnn7FxfIJLmtTTR9RiC4OSNCanWosPIh+3ShWl4zGOZbqQOSTlvFUHblOhdWQsyrKxh022yV5UaSLN5QyjlefQfEcMDNFiPbMhU/3eYTV1Dg7PT6PFpMk6P8fkccNWbNhhkAFdiQHDvZEWY/NYi6+baMm9167ng9fGfcXFrYs43Pl4XfJ/mQdaQp2SY78Ww6JsPU6I0x/cXPx4)

**Comment by bogdanciuca** [comment]
Works as expected, you can select multiple files.

**Comment by websitevirtuoso** [comment]
Working as expected. can be closed
