### ISSUE TITLE
[Bug Report][3.3.9] Invalid prop: custom validator check failed for prop "range".

### ISSUE THREAD

**Issue by sametaylak** [vuetifyjs/vuetify#17935]
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use v-date-picker with range prop

### Expected Behavior
It should support range functionality

### Actual Behavior
Throwing an error called Invalid prop: custom validator check failed for prop "range"

### Reproduction Link
[https://codesandbox.io/s/thirsty-wozniak-6838pv?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/thirsty-wozniak-6838pv?file=/src/components/HelloWorld.vue)

**Comment by KaelWD** [comment]
Range is not currently available
