### ISSUE TITLE
[Bug Report][3.3.11] v-expansion-panels v-model only works with top level object

### ISSUE THREAD

**Issue by ciknowles** [vuetifyjs/vuetify#17945]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
In the reproduction link:

 `<v-expansion-panels v-model="outer.panel" multiple>` - Not working 
Change to  
`<v-expansion-panels v-model="panel" multiple>` - Works

Panels will only be expanded if v-model is a top level object.
I've tried wrapping outer in ref,reactive, computed etc but it still doesn't work.

### Expected Behavior
As long as v-model is set to a 'ref' I would expect panels to expand/collapse as per the documentation.

### Actual Behavior
Panels are actually only be expanded if v-model is a top level object.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVU1T2zAQ/Ss7uqTM+GMonJjAQA89dXrrKeag2Bsq0BeS7KZk/N+7khIwCR3SmR65JJa07+3bt/J6sWE31lZDj+yCzQMqK3nAq0YDzDsxpIf8CK3k3l82LOA6lC3qgA66ciVxDXZZnjdsG0zhQ7kM+hmgePm5YXDdStE+0JpLScFwIyXM6xR6LFIbjRH6nf73sPM6y31D8FbdUCrToYTNBkxP4ivLNS3HcQ86lLimIy+MLlOIhy2UuCZIEqZ6GYSV2a+3wbsTgCCCRKL4akzDJttkJ+1+Mw4VCOt7BZ2RxoEXAbjCUEBrtMc2YOgd8E5Y4Vuh7wCloEOPHQEARe9JJNEpS2ChW9GJrtcB+gCSL4keMGRqBMXvNAcuxWPPK/gRALVQxA1KxIeBllwV8NgLD9r44PoOcI2uFYEHqg16KblqTWaOQcKLmClRCkvBgJyEK9JkcgGUKlTTygcu+2jIamrIVWzrnofPvTnO4C/cfRg8NXg5NeS/GPz0YfBrgyeG/MXgPKQOh0uetdsRNK8nI5iWvnXChhQioisBNuBwVdAPb4MYMFqrLA2lDkZYOaNgRrN8lvtJqSKkwxWnQQWbLMJTF+ynk90SUm0hz0S4fNkGSAIvYsJPi9uTYncwvtyWDKWBTsBVr0kSOTvlhumsrZJfFLqY0Ts/K2BGNzP/Pc1uJ/RT8jjz/5H9kMrFm6fJvBRfRMVFYi52Rb76JGTYmCqmxbx+7gMrmBT6wVf33mj6ZCYpDWu9b9gFLDKwYT9DsP6irttOUyR9OsTgKo2h1lbV1KAgVr+vz6qz6vSUOu/Dbq+k2+irxBapqJCRMubWl4rbvbT5IKXeetIwYorrdzRcU1jt6OUSCsvOqCTmPGuZbFfoVbl05pcnc+4p0fYSpDRR8BGp3i2Xchxw15RwQFc61B06pPl1XEl7sGlZe0cHpW2bPbKxYAlGzmfN7PYPwXENpw==)

**Comment by KaelWD** [comment]
`setup()` only shallowly unwraps refs, refs inside plain objects have to use `.value`

`{{ outer.panel }}` works because vue calls `toDisplayString` for you: https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/packages/shared/src/toDisplayString.ts#L31

**Comment by ciknowles** [comment]
Thanks for the response.

In my example

`<div class="pb-4">v-model {{ outer.panel }}</div>` doesn't work
nor does
`<div class="pb-4">v-model {{ outer.panel.value }}</div>`

However,
`<div class="pb-4">v-model {{ panel }}</div>` does work

I am expecting XX.XX to work - so that I can use a property of an object within a for loop to manage which panels are open. 

C

**Comment by ciknowles** [comment]
Forget that - you are correct. I'm sorry. Thanks for answering!
