### ISSUE TITLE
[Bug Report][3.3.11] TypeScript Issue when exporting slots types: TS4082: Default export of the module has or is using private name 

### ISSUE THREAD

**Issue by flaming-cl** [vuetifyjs/vuetify#17941]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. defining slots types in defineComponent with `Object as SlotsType<VTextField['$slots']>`
2. received TS errors:
TS4082: Default export of the module has or is using private name 'DefaultInputSlot'.
TS4082: Default export of the module has or is using private name 'LoaderSlotProps'.
TS4082: Default export of the module has or is using private name 'VInputSlot'.

![Screenshot 2023-08-01 at 8 49 41 PM](https://github.com/vuetifyjs/vuetify/assets/51183663/f8a6fa45-4f9f-4260-8dfd-2d55aa731a6e)
![Screenshot 2023-08-01 at 8 49 49 PM](https://github.com/vuetifyjs/vuetify/assets/51183663/f3cc110f-8818-428e-b894-64c7259d788d)

### Expected Behavior
defining slots types in defineComponent with Object as SlotsType<> will not have TS4082 errors
(VBadge does not have this issue as shown in the screenshot)
![Screenshot 2023-08-01 at 9 15 28 PM](https://github.com/vuetifyjs/vuetify/assets/51183663/e9c4fd67-8900-46f1-93d3-5d16f6ee0c9a)

### Actual Behavior
Receive a few errors saying Default export of the module has or is using private name

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU19r2zAQ/ypCDNxCbFOSJ5OVjLHBHsYeVvYSh+FYl1qZJRlJdlNCvvvupKR204f2ydbd/f7cz/L6yL90XTb0wAu+9KC6tvJwX2rGlkNqwXVGOzkAq9vKuc8lV4e06r0pOVPVIX2SwjdYnS8WJQ+ogPNw8OlOQitiibFGCkgF+Eq2xBIpLs222kKL1W8K26wSAnXd2EZLNTSmFWBxaG8aLQysHmk4q40aB/1zBzgB1LlUz6bQ1mU5NqQ7Q0w3f2dMVwpumdTsk2uNR1Hs0luxps7mBY14KrOCyoilBw7nI33+KjwqTHOIiWJpjBRLr0B4dLWVncc89CNqkJ2Ak6oz1rMjE7CTGr4aPGvQfsZ+k+kHXJud2M4axRL8kskEQ5Eg8M8DOvlORqaDXu6ec0wwsjnEERIOAYlaVd+G51Tz5hjXowAKlvzsJVH/0F3vk1lshSQL9mu7h9qzyo0ul6OPdRITTzb3AXa6pThiALg0n/FW6n8u2zuj8WoG1ZLXdC8Kto5CJW+871yR57XQOCmglYPNNPhcdyo/b7iaZ/Ps7i4X0vlLLcUr57LARlSbUp9QMWaWqqq7ko2NIH1ev+TIROd3PKxwLLe99lLh/TcqmFlEL5NyBk6lW2ueHFgkKfk5yiBDhj8g9e66qPGGO0fBASxeS42/F9iPrnQFm6511XqzWvjaFPhpxgMMk4+e+eY/MpKHNA==)

**Comment by darkbasic** [comment]
I have a similar issue with `v-btn` and `ref="download"`. I've worked it around by using `:ref="'download'"` instead.
The same with `v-card` and `ref="containerElement"`: `:ref="'containerElement'"` does the trick.

```
[niko@arch-phoenix chemical-inventory-fe]$ yarn type-check
src/components/AssetDownloader.vue:66:1 - error TS4082: Default export of the module has or is using private name 'GroupItemProvide'.

 66 export default await (async () => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 67 type __VLS_Props = {
    ~~~~~~~~~~~~~~~~~~~~
... 
204 })()
    ~~~~
205 ;/* PartiallyEnd: #3632/script.vue */
    ~

src/components/VTable/buttons/SetColumns.vue:463:1 - error TS4082: Default export of the module has or is using private name 'LoaderSlotProps'.

463 export default (await import('vue')).defineComponent({
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
464 setup() {
    ~~~~~~~~~
... 
471 __typeEl: {} as __VLS_TemplateResult['rootEl'],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
472 });
    ~~~


Found 2 errors.
```

**Comment by throrin19** [comment]
Same problem here. Any news ?

**Comment by darkbasic** [comment]
@throrin19 does my workaround work for you?

**Comment by throrin19** [comment]
> @throrin19 does my workaround work for you?

I don't try your solution, in my case I add a div arround my vuetify object and made reference to it but it's not a good solution

**Comment by ibhaar** [comment]
> I have a similar issue with `v-btn` and `ref="download"`. I've worked it around by using `:ref="'download'"` instead. The same with `v-card` and `ref="containerElement"`: `:ref="'containerElement'"` does the trick.
> 
> ```
> [niko@arch-phoenix chemical-inventory-fe]$ yarn type-check
> src/components/AssetDownloader.vue:66:1 - error TS4082: Default export of the module has or is using private name 'GroupItemProvide'.
> 
>  66 export default await (async () => {
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  67 type __VLS_Props = {
>     ~~~~~~~~~~~~~~~~~~~~
> ... 
> 204 })()
>     ~~~~
> 205 ;/* PartiallyEnd: #3632/script.vue */
>     ~
> 
> src/components/VTable/buttons/SetColumns.vue:463:1 - error TS4082: Default export of the module has or is using private name 'LoaderSlotProps'.
> 
> 463 export default (await import('vue')).defineComponent({
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 464 setup() {
>     ~~~~~~~~~
> ... 
> 471 __typeEl: {} as __VLS_TemplateResult['rootEl'],
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 472 });
>     ~~~
> 
> 
> Found 2 errors.
> ```

Got this error after updating tsconfig to default create-vuetify, this works for me, replace any ref="anything" with :ref="'anything'"

**Comment by darkbasic** [comment]
This has probably been fixed in the just released vue-tsc 2.2.4. I can't be sure right now, but I will be able to test it on Monday.

**Comment by volarname** [comment]
its sad this is not planned specially when just exporting the type is a solution, not good for community

**Comment by darkbasic** [comment]
I confirm that with vue-tsc 2.2.4 the `:ref="'element'"` workaround is no longer necessary and both the development bundle and the production bundle work as expected.

This issue was already partially fixed in the latest development builds of vuetify. Vuetify stable had issues with ref with the following component: v-btn, v-icon, v-card, v-layout. With `@vuetify/nightly@dev` these issues were limited to v-btn and v-icon. With vue-tsc 2.2.4 there is no need for the nightly version and vuetify stable can be used without the need for workarounds.
