### ISSUE TITLE
[Bug Report][3.3.11] Navigation Drawer touchmove conflicts with swiper element

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17944]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) Open the Github repo link provided in issue and clone the project.
2) Run project using commands: `npm install` and `npm run dev`
3) Open dev server in browser and make sure to open console.
4) Try swiping cards and you will see errors in console.

### Expected Behavior
Navigation drawer should not capture swiper's swipe interaction.

### Actual Behavior
Navigation drawer captures swiper's swipe interaction and showing error in console.

### Reproduction Link
[https://github.com/DeepKumbhare85/swiper-test-with-vuetify](https://github.com/DeepKumbhare85/swiper-test-with-vuetify)

https://github.com/vuetifyjs/vuetify/assets/92006556/dfb775b4-fd99-4d3d-b0be-731b6917620a

**Comment by KaelWD** [comment]
swiper is emitting a custom event on window as touchmove
