### ISSUE TITLE
[Documentation] Playground on Icon page is not working correctly.

### ISSUE THREAD

**Issue by nayo0513** [vuetifyjs/vuetify#17943]
### Environment

**Browsers:** Firefox 115.0
**OS:** Mac OS 10.15

### Steps to reproduce
Click "Edit in Vuetify Playground"

### Expected Behavior
Icons is displayed.

### Actual Behavior
Icons is not displayed.

### Reproduction Link
[https://vuetifyjs.com/en/components/icons/](https://vuetifyjs.com/en/components/icons/)

**Comment by nekosaur** [comment]
Which specific example?

**Comment by MajesticPotatoe** [comment]
> Which specific example?

seems like the FA/Material Design ones

**Comment by nayo0513** [comment]
> Which specific example?

Here is the example.
https://vuetifyjs.com/en/components/icons/#mdi-svg
The same problem occurs in others.

**Comment by JulianPinzaru** [comment]
I couldn't find any working examples on VSvgIcon component as well. 
As it was stated before, there is no examples nor some detailed documentation related to that.
Seems like the playground for icons is broken or missing some parts on the page. 
Could you please provide some help in this regard ?
