### ISSUE TITLE
[Bug Report][3.3.11] VWindowItem not full width when opening

### ISSUE THREAD

**Issue by Warnier-zhang** [vuetifyjs/vuetify#17968]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
when i use highcharts and v-row in v-window-item，the width is shrinked，not 100% at first
after i change tabs and back，the width changes to 100%

### Expected Behavior
full width when opening v-window-item

### Actual Behavior
not 100%

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/no-project)

**Comment by Warnier-zhang** [comment]
tabs vertical

**Comment by Warnier-zhang** [comment]
@KaelWD 
Reproduction Link

https://play.vuetifyjs.com/#eNrNWFtv1EYU/itHfgGktbebzVMUIhC0Uh/aIlU8sTzMjiebA+MZM5cFhPLf+43Hzl5syBZoFSmK1nP5zu0734z95kvxvG2rbVTFRXEZVNNqEdTVyhBdbkspXN397p6CtXotHEmrrXu6KlrHjXCfV0W/ZH9RGThodfXaK0evnL1mrS7nx7M98m58GKl5S1IL72GlLq+1+kTpX+nsxyNrYu1pWza2Vhpr8bgqqGanZGBrMLJVLrAUGsNfd3uAoq3QUWGJbdP2cnGwplvF0hryQbhwRU3NpZDSRhO6INLcwfq/Ohha7NlJsYr1vZbP7resrXz/TbNn/97s8qSAlfdla/meqJdfN98/+/1KfmRT24/HtTz0OK8pGTQ9oVQgy8FQZrTViQiJWOdHW4YVO85PzJRBfQpXi8UixbAbGOH0s8cOpGGr/yu3zs7OHqJby+XyIbp1fn7+09xKY4d8SyN7fD2ZyBOdn3yA/oljDw+iGTnfTsT/h3VrJqMkNSpEX9Hf0bfK1Oy9omsRJa+jn5GJRpIK1CqtlQnKf4hqDKY2CrqA5VrI6ElgIapiEI9mTwF7E9aWg1DEWJJG81KlOYzxuKZgHf7glqqpsQlnRspZ7AgUdXAM7QFy0ybkRkQHSG59bMZoQvOHKBrSvAYCYoIkiZpb9pLNhup0GFB0RpAg6yRX9CI6seYQ3RhM8yZqQV60rMyMAhvJdZJ9oMLDyB6qlUOdUWt9VA4xN61yNaswmwBUtqI/U5o9QoVN+FWN+ZdqeFJhD+qo4oZFeLDFxXWADbbiaHYCBvrcciABVu7q7FFn5aaSl3cIJyNhrQ+otLorDiakjI0Xhgx7HmgiEDSYVNHvo4wS3WD2JhUfVw5F3RVI4BohA3CQyN+ilyohXCM4ODa4mh0Zw7U3wqngRMpYzQ2yHJsfqi44AiivwOiAjCmb6hNoDW6bOjbkbS20QkFE3CAV21QDktH56MdoiQAz+gDS0saJLdcCOdqgERpG8nK/gJzoHWkb8NoSYCQ6J2CTGAdCSGl2TwaoCi58mc8UQ/Yk93N2Z5jLzOkpMUZ83nevip27P5K8XwMDCL600cF+I0KA/Z4VfeIGtajoNXwWjqfytuv6IUfPlVGgWU9lcjfWpA5oVa0qepkS3PV5R58x3rVymRpka7adKidKnxzr3Q25WZe/TByDRC9tAt3CSyNS0Nuo2xhAboL4KUT7zQCmGqWOqaFAlp3MJSZCCSAX0BeNaNJj0mjoK0QH9Z3Ru+iDnShzbqyBZoNkd1k4UC9luOmZM+v7MgnnhDYMWgQH95ovJRfKBzn4Snanjv3xuTpxIfjeY37ipv3zjvler3K70qsb4Tu97igGVSXIb1eRgzMAR4RkpG7iIKJODTrJAQEepIL/VGJ+f8e9cAJhiw0nkTk59RPacFeLPtk5N/myk0J0AVlKep/i6MR8dw+JUzeOBnXLetD1WHeSzfpSMWrVdcgBH1TEAM4xnrpeZYuIKJ8UIvRangLMtwP8Crj/pE4d8vE/9d5u/O4LAz4o5G8aO5TL+d7XDjx66bjNNtWnlGCqFW5NOtCXjFKLIC7o8RN6ekWP+zGcCmJ9QY+Gt9BHfeZvn3Q/bpOZO+BiVmg27331zluDzy0dxqqQ3q+KC3qTd66KmxBafzGfy9pgJV6Geesqo8LctM0cH2oCX39+tqyW1WKBuHwYxkqNV+qqQ0tQb1fmFhZxC0UsZSPaI7N5ojPdB4OvJeAinu/x4RmWzR0OQqhrWdumc+Y8+7I3XCnflGu8FeEbEEBWRZ+bzkxy+ART94YLGyPsOQxCmkqH4wNC4E4N6WjbflhHU6PQ+mLfFrezotuGzGefi7f/AI3QvPM=

**Comment by Warnier-zhang** [comment]
actually，there is nothing wrong with highcharts

<v-row> does't work well with <v-window-item> when tabs is vertical

**Comment by KaelWD** [comment]
The default flex value is `0 1 auto`, add class `flex-1-1` or `flex-grow-1` to the v-window if you want it to fill remaining space.
