### ISSUE TITLE
[Bug Report][3.3.6] V-Textfield not properly respecting @click.stop=""

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#17965]
### Environment
**Vuetify Version:** 3.3.6
**Last working version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
I have a dropdown list with one list element containing a v-text-field.
The user should be able to type a custom value into the field, before selecting the line of the list.
I added @click.stop="" to the v-text-field, so that the list does not close when the user clicks into the text field.

This used to work properly up to vuetify 3.3.5.
Starting from 3.3.6, it does only work when the use clicks the actual letters written inside the text field.
It does not work if the user clicks between the text and the underline. In this case, the menu now closes.

### Expected Behavior
clicking into a text-field with @click.stop="" should not propagate the event to the surrounding list element

### Actual Behavior
@click.stop="" is ignored if the text-field is clicked at the wrong position

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVE1v2zAM/SuELm2Byu6QIAc3DTJgx+20Y92DYimrFlkSJMZJFuS/j5bz4TkrmptNPj7yPdJ+3bOv3mfNWrGCTVHV3ghUs9ICTKVuoDIixpeSodoir5RFFUqW0gRoeK3sGgrjKoHaWcItHKKrzxACnTih4dE4LESFuhHoAqH34IPzEQ69gsS7QAuVMwnkg65F2JUMpAgrolloK1OcSqkQvtGDdBsL0zxVXnrnPUHnYMONjggRd0YRzUZLfC9g9PTkt8MxWiDXRDKDn4n9EvgI9+NG3PfbcJcwQLWO5C1E/Uf1w4RP21lqZWQ/AeRV7aQypLIRZq1K9m96XhldrTJi9QQZZgcGfWkNegapIzm6K0Bbo63iC1r+6hkaFVBXwnBh9C9bQK2lNIOGs1bx/0ZNiWvNp+jp3Oi1vbfuOHO6TnoarHgaq6B9V6G23gUEqZZibRD2HYsUKAq4f4CXGdzvIflSwN14wseTOzg8PLawQ0t8pmKPjKSuYvY7OkufSWIqWRXp+gp47XhL9o7oY5HnlbSEJNt1EzKrMLe+zukDQ73czUfZKJvQ7BFPIW7EImaJrGV6K+2BGuq6HZ7Xwg+6donU+aiIltuutvhshDnB8rC2qGvFpavTLONull44U7Hmi+A2UQUiKVly5NimHfiGVp+ppRZX1Dn1oyviQVmpQvubuU3RoKyvapC6UnZc9YEdHlkqI+PTyOztL3wVn8U=)

**Comment by websitevirtuoso** [comment]
What about prop :close-on-content-click="false" on v-menu? It will stop propagate

**Comment by drhouse82** [comment]
> What about prop :close-on-content-click="false" on v-menu? It will stop propagate
Thanks for you suggestion. Yet, this doesnt solve my issue. 
I do want to close the menu when clicking on the "S", "M", "L", "custom size", but I do not want to close the menu when clicking inside the text field. 
This broke with version 3.3.6.

**Comment by drhouse82** [comment]
Actually, the issue doesn't have anything to do with the menu or stopping it.

[reproduction_link](https://play.vuetifyjs.com/#eNqNU81u4jAQfpVZXygSSbrqag+BIvY5mmpl4mHx4tiWPUlBiHfvxAk0oof2EDmZn+9nPHk5iz/e512LohQrwsYbSbiuLMBK6Q5qI2N8rgThkbIaLWGoREpzQZel8E6jUUMIwMgtmtQQqRLXaJc1TqV4J02LH4lNbXR9yCM5Pzb9dS35dtIb6WSQk29a0b6En4+P/rgEpSNLPZWgrdEWs61x9WEJHQbStTSZNPqfLaHRSpkb33pVTDUPNgv2yW+rYuKeP2MdtKdUgkfvAoHCnWwNwXkAU5JkCQ9zeF7DwxmSsRJm6ZzBZb4YyhqkvVOxvLYBTFyWsGttTdrZHuhWASANG3mYnVwLe9kh3wOPCRWjzebXqsvIMJyX3sJNdG+gn1vSry1TXdG3LigMPEd/ZAtxz6CBnx+66U1KS8sPtBFBLATP+BDz/9FZ3pOEVIk6xkqU8DLgVmJP5GNZFLWyXMnXrbuQW6TC+qbgDSO9O22e8qf8N4880jWU8crEPIH1SK+VvTDhICdrpL9jHRKJeXTES9WvVPmVhA2XFaG1pBvMlGuSll+Dlkk4x9hk2+DeIgYGqcQ45kTTC/4G1VdumeITdMF8vL5ZQMsX1P9n33N01zZ1dZf65Gy86Yu4LERq48EnyeL1HcV8W/M=)

The text-field does only fire the on-click event, when you hit the innermost area with the actual input.
Here, the actual html input has a red dashed border.
If you click to the outside, there is no click event fired.

**Comment by drhouse82** [comment]
So, click inside the red rectangle => click event. click outside => no click event

**Comment by drhouse82** [comment]
I closed this for now and created a more specific issue. #17991

**Comment by drhouse82** [comment]
.

**Comment by drhouse82** [comment]
.
