### ISSUE TITLE
[Feature Request] Prevent VImg images to be draggable

### ISSUE THREAD

**Issue by ClemDee** [vuetifyjs/vuetify#17973]
### Problem to solve
In some cases, we don't want imgs produced by `VImg` to be draggable, for example when used in a card header.
But currently, there is no simple way to do that. It is not possible to prevent this behavior using css (there is a `user-drag` property but it is webkit only).
The only way to achieve this is to add the `draggable="false` attribute to the html element itself.

Here is a reproduction example about how I have to do it for now:
https://play.vuetifyjs.com/#eNq1UtuO2jAQ/ZVpXhYkbO+KPiFYUal/sdkHkwzB1DfZTmiF+PeOE2gCK1UrVX3LXHxuk7dz8c173rVYrIp1QuO1TPhaWoB1x6T3/WdfVM4mqSyGa4uaXxiDOsimkTuN0DFlDMxq3MtWpzkwNm7mWXOrAGKoNmVxSMnHlRBVbbOCpPa/jpFXzghlZINReBmk1vKnMCQqKKn50TdlMeKcVJ0OhLR8fh7bgmjvJFpnH2Q2MDupdICqjckZqFyNf9UbcE8s1LIuA00l/FcrAFvtZB2TDIlmAY3r8Pudguy2lyweT5Q7wwXXYnJZKmMVlE8QMbXDgZXxLiQ4Z6NwgX2gUJ7Ix9OQpBDTpCA52stK+lTzAhHHRCjXfGCTgWa21Xo+jkf1NJ/NYfMK50H7n4e8k7pF3mfGx5NtYC91xLx8yW4G/aS8WNBRsnRmpOfH6Cz9xj1ovlYexLJY3WjKgizl+v5ex1ijVl3gFpOw3ogtrYnQ2qQMstqZ7ZIv+VdRq5imbY7RsF1wp4iBQMpiMaHJf8AnqK6bPcPLy0Bx7TEtdzFzfMAWRNhhYAFtjQHDZy09PJvaehh9sHaN/kKBa2V/xIesq9jn/HYT+W+ee7QM9Z4ZL4uiF0rUw4vi/Tcs7IoV

It would be great to have an easy way to prevent VImgs to be draggable.

### Proposed solution
Add a new prop to `VImg` in order to alter the draggable state of the img.

I can see two potential solutions:
- a `draggable` prop, `true` by default
  ```html
  <v-img src="..." :draggable="false" />
  ```
  pros: consistent with standard html `draggable` attribute

- a `nodrag` prop
  ```html
  <v-img src="..." nodrag />
  ```
  pros: much less verbose for the only case we want to use it (removing drag)
  cons: negations are less easy to reason with

Maybe the second solution with better naming would work?

**Comment by websitevirtuoso** [comment]
I think 1 option is more readable and is native way to use it with native img tag.

I could help and create PR because this is easy to do this. But I can do this only when my previous PR will be approved

https://github.com/vuetifyjs/vuetify/pull/17927

**Comment by ClemDee** [comment]
Thanks @websitevirtuoso! Indeed the implementation is easy, I already managed to have it work, but I wanted some feedback before making a PR to be sure I was going to the right direction! :slightly_smiling_face: 

No worries about the PR, I'm going to create one on my side

**Comment by websitevirtuoso** [comment]
Yes I think you're in right direction. we have to implement prop because VIMg has multiple elements inside. So Pr is would be great
