### ISSUE TITLE
[Feature Request] Add VBtn anchor element target option

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#17982]
### Problem to solve
As a user, I want to use anchor elements over JavaScript navigation whenever possible. I want to use anchor elements for all external links that will not be handled by the router.

### Proposed solution
Add a `target` prop to VBtn so users can set the anchor element target when using the `href` (or `to`?) props.

### Alternative Considerations

Add a map type option for the `href` (and `to`?) props that allows for target

**Comment by MajesticPotatoe** [comment]
> It is very strange that href is explicitly documented.

`href` pops up in the api docs because api-generator picks up on it being explicitly set it in `v-btn`
https://github.com/vuetifyjs/vuetify/blob/05d1ab34b7336d085e2567a6b9b24846c48ad4e4/packages/vuetify/src/components/VBtn/VBtn.tsx#L200C18-L200C22
