### ISSUE TITLE
[Feature Request] outlined v-data-table

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#17980]
### Problem to solve
This feature would allow developers to have an outlined data table.

### Proposed solution
Add "outlined" prop to v-data-table.
```
<v-data-table
  :headers="headers"
  :items="items"
  outlined
  ...
></v-data-table>
```

**Comment by AtiaDjaber** [comment]
you can wrap th table in card like this
` <v-card outlined>
      <v-data-table
        :headers="Headers"
        :items="listhisory"
        single-select
        @click:row="rowClick"
        show-expand
        class="elevation-0"
        > 
      </v-data-table>
    </v-card>`

**Comment by simionato-mobisec** [comment]
> you can wrap th table in card like this ` <v-card outlined> <v-data-table :headers="Headers" :items="listhisory" single-select @click:row="rowClick" show-expand class="elevation-0" > </v-data-table> </v-card>`

I'd prefer not to create a wrapper component for such simple styling.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time. You can use the suggested solution, or apply css styling through a class.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
