### ISSUE TITLE
[Feature Request] add "disabled" prop to Data table / Server side tables (LABS)

### ISSUE THREAD

**Issue by albertotesoro** [vuetifyjs/vuetify#17985]
### Problem to solve
actually if prop "items" is assigned to a promise source like apollo useQuery result and "v-model:options" props to a reactive object used to popultate a smart query variables (ie. to change current cursor page on server side) , during data fetching prop options.page switches to 1 because there are no current data for the table, invalidating the desidered fetching that will be replaced with a new one asking for page 1:

### Proposed solution
disabling the props.page change (or the whole props.option group) then new query won't be triggered
(i actually solved using v-if="!loading" on the VTable, where loading is the state of the apollo query

**Comment by NextThread** [comment]
hey, can I work on this?
