### ISSUE TITLE
[Feature Request] [3.3.11] Add allowed-dates prop to VDatePicker

### ISSUE THREAD

**Issue by herrrta** [vuetifyjs/vuetify#17983]
### Problem to solve
VDatePicker does not have have the prop allowed-dates.[This was available in v2 of vuetify.](https://v2.vuetifyjs.com/en/components/date-pickers/#allowed-dates)

### Proposed solution
Add "allowed-dates" prop to v-date-picker to allow only specific dates in array to be selected as options.

**Comment by NextThread** [comment]
hey, can I work on this?

**Comment by nemoneph** [comment]
Need this too here! :pray:

**Comment by kkolataj** [comment]
I also need it, very much.

**Comment by NextThread** [comment]
I will work on this

**Comment by NextThread** [comment]
I'm working on this

**Comment by herrrta** [comment]
> I'm working on this

can you potentially allow it to work with selecting a range?
I know the original description was "Restricts which dates can be selected" but it would be a very nice have if we can use allowed-dates prop as more of a visual aid to show what's available but not limit a users range of dates selection.

**Comment by NextThread** [comment]
> > I'm working on this
> 
> can you potentially allow it to work with selecting a range? I know the original description was "Restricts which dates can be selected" but it would be a very nice have if we can use allowed-dates prop and the range prop together.
> 
> The range selection would return whats allowed only

ok I'll definitely try to implement in this way.

**Comment by seanc722** [comment]
In v2 it accepted a function with a boolean return value, not an array. Which you could then handle the range stuff or anything else yourself in the function. That being moved away from for a reason?

**Comment by Restlessjoker** [comment]
The function approach seems more versatile, plus has the added benefit of fewer breaking changes between releases.

**Comment by coderWhoMe** [comment]
@johnleider and @NextThread any updates on this issue?
