### ISSUE TITLE
[Bug Report][3.3.11] thead/tr/th not rendered when using v-table with vuetify.esm.js

### ISSUE THREAD

**Issue by baddonkey** [vuetifyjs/vuetify#17984]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use vue.esm-browser.prod.js, vuetify.esm.js to run vue/vuetify in browser directly without any build steps. Try to render a v-table with thead and tbody.

### Expected Behavior
```html
<div class="v-table v-theme--light v-table--density-default">
<table> 
<tbody>
<tr>
<th>Column 1</th>
<th>Column 2</th>
</tr>
</thead>
...
</table></div>
```

### Actual Behavior
```html
<div class="v-table v-theme--light v-table--density-
default">
<table>
Column 1 Column 2 Value 1.1 Value 1.2 Value 2.1 Value 2.2
</table>
```

### Reproduction Link
[https://github.com/baddonkey/issues/blob/main/vtable-sample.html](https://github.com/baddonkey/issues/blob/main/vtable-sample.html)

**Comment by KaelWD** [comment]
https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats
