### ISSUE TITLE
[Bug Report][3.3.11] Re-center dialogs when virtual keyboard shows

### ISSUE THREAD

**Issue by Parakoos** [vuetifyjs/vuetify#17981]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Build and deploy somewhere.
2. Open the app on a mobile. I tested with an Android (Samsung) and the Chrome browser.
3. Click 'Open Dialog' and you should see that the dialog is covered by the virtual keyboard. If the virtual keyboard doesn't open, click the text field.
4. You may toggle the full-screen view on or off to the see the problem in both modes.

### Expected Behavior
I expect the dialog to reposition and resize itself to fit the new viewport after the virtual keyboard has taken up some of the space.

### Actual Behavior
The virtual keyboard covers the dialog. It also makes the page underneath the scrim scrollable. In full-screen mode, using the card actions, those action will always be covered since they appear at the bottom of the page. A user would have to know to scroll down to find them, or manually close the keyboard. Not a good UX.

### Reproduction Link
[https://github.com/Parakoos/vuetify-dialog-virtual-keyboard](https://github.com/Parakoos/vuetify-dialog-virtual-keyboard)

### Other comments
I deployed a version of this code to a [temporary home](https://dev-phojo-app--vuetify-dialog-virtual-keyboard-xwfugu0y.web.app/) where it will live for a month. I also have a screenshot of the effect.

![Screenshot of the virtual keyboard covering the dialog.](https://themodernnomad.com/vuetify-dialog-virtual-keyboard.png)

**Comment by KaelWD** [comment]
Everything just gets worse I guess, they've decided to copy apple: https://developer.chrome.com/blog/viewport-resize-behavior/#opting-in-to-a-different-behavior

`env(keyboard-inset-bottom)` is pretty much useless because you have to set `navigator.virtualKeyboard.overlaysContent = true` first which is only available in a secure context.

**Comment by Parakoos** [comment]
So is the advice that you should simply not use text fields (or anything else that require keyboard input) inside vuetify dialogs?

**Comment by KaelWD** [comment]
You can use `interactive-widget=resizes-content` in the viewport meta tag to restore pre-108 behaviour.

**Comment by Parakoos** [comment]
That would not fix it on Safari. What we need is some way to resize and reposition dialogs based on the Visual Viewport instead of the Layout Viewport. I wonder if I could make a ```<div #visualViewport>``` that uses [a solution like this](https://github.com/WICG/visual-viewport/blob/gh-pages/examples/fixed-to-viewport.html) to always be the size of the visual viewport, and then tell Vuetify to attach and contain the dialog to it...  Might try that. Or, I will simply not have text fields inside dialogs... I can't risk having iOS people unable to use the app because their keyboard hides the text input field. If it was outside the dialog, the browser would have scrolled the text field into view, but inside the dialog, this doesn't happen.
