### ISSUE TITLE
[Bug Report][3.3.11] Otp input continuously gets flickers on tab press.

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#17986]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just press tab

### Expected Behavior
It should lose focus after the last input tab.

### Actual Behavior
It would not lose focus

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs1O4zAQfhWvLy1SncB2pdVGLYJX2CvhkMTTrRfbsexJoKr67kzshIaCBIdK9Xwz389MHo783rms74AXfINgnK4QbkvL2KYXTWuxUhY82+lOyViOgG+fx8fYpxn9wrbkf0r+hhAmVc8aXYUBMpWoOmxLzgIeNMTKi3hWEvcFW19fu5d3s5G5RSeUdR2yXphWgqYpqhFHocH+wz290x+a3eSzgbmLnGyc/VIXmaX35wl+Evmb5YNYvw/Uixotq3XbPLFCqlDVGiR1/lDhvkHVA7X/hUoeBhlq/UR2ek1LTMi4aaps8tkd6BkarxyyANi5OKCMaz2yIzk2lBTkinnYsRPb+dawBR1zkcIRa0BGK2HboWO5WFydy2ltI/KbgDM0ZSFwklgur9j2lh2TfU9evB2Ys77SHWQT2XY78qb60H0i6k2eQpB9vuJa2aeQ/Q+tpY8uMpa8CaHkBXtI/CXfI7pQ5HkjLXXS4VXvMwuYW2dySohqd7hbZ+vs5oauG3CqCV3VIYtsA9VjaU+kmDYmTOUuZBMQpcdoJSem4f2Fhztqy31nURkQsjXRzK/kZVbOIBhR06kDeCIp+WomMxj+htSXcUnjA3dOgj144cFK8OC/G+libB7rAvoQLV57WPhpxeMYbT555o+vp1Vw/w==)

### Other comments
I've noticed that there seems to be an issue with the OTP input field. It looks like every time I press the tab key, the input field flickers. It's quite frustrating and makes it difficult to enter the OTP code. Is there anything I can do to fix this?

https://github.com/vuetifyjs/vuetify/assets/80033712/273db4b1-41d3-4a97-9155-86f79e278e42

**Comment by johnleider** [comment]
resolved as of latest version
