### ISSUE TITLE
[Bug Report][3.3.11] Virtual table removes rows when row height is changed

### ISSUE THREAD

**Issue by jonasengelmann** [vuetifyjs/vuetify#17996]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When scrolling down and up again, the first entry disappears. This strange behavior only appears when the header is hidden.

### Expected Behavior
No rows should disappear. No extra white space at top and bottom of table should appear. 

### Actual Behavior
Some rows disappear, inconsistent white spacing at top and bottom of table.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqllltv2zYUx78KobVIAkS05FsSLQlapLt03cNeh9hAaYmxuVCUQFJuPcPfvYcW6Uiy2MZoXkLzXPg7f5LiedwG78sSrysaJMGtpnnJiab3M4HQ7TrMiCahJgtOwzWTuiLcGBBKVpRkVKq7WWBHs8BaGOQw89b/A1WKSn2wp5woY6acrolmhQhjlG/qNZzPirLlSoPTOIrcnEkbrgmvKMwLklvnPSigOnC0DhUvtOO7vx20Sxr01QSmlh/8VHrD6xDs6NC2XisM1zZcFl/CmjVBw6j8+qtx2JlkLtxkSiUr9T4V/VoWUqOMPpGKa5fP8CTo/ALd3aNzO2c02BeQoEc3g1xA/aeZ5jRBZ1ZgdB5H0RLBcM3E8uLssulLOFsK8FWaSN02KSAyxSToiXBFW7ZnuoEgI3YzZtcYbw8YD4QXklF1dnlYjYoMftVJUmf2hP9OoAKD3Rv9RLQv8IHIhfpOaGrsvuB/ZKEpE98JL2sPX4KPsoDot75oBuZm6Pwwyuy18O+vkd0II4v/qUD/Fsuqu3VO0wTFk5uWBfRK0BRHHXdQAg7quDVrC0zQuONu2GH92Lv1PbAfU4pSSUmOFBHZF5aufMTD0dUx8U0/cce1QTz6aeLf4HvEpJdyOjymjH3CtmkOmF13i3l1CuZDVabkuXUNm5yjaHLMOcJt3Szm9DQ1r0/B/AM+PVQu4ATAHfCgTqavl3TcPtYH1hFuG9zOT0+B/YtyvkELSoSX9apH1qgf9cZzrbruFjU6hfTvgnNWFqWX86bnmEa4Pek4rz2cfZTDUyj/LATdpEW+8GGOo/ba9pT2Yl57TukUt7fEgo4np5B+KETl/ZaOJz1iDif9uz6JfZep94AOTxL0E9Of4OHzcE7iHjWHnos0bat24GyrbCk9t8g9XrsLO4C9LitNs+SFvtP0QVPTKExSXUmBHjHG76UkG9OxRNEFhrcSPOc4J+U5M11QS4y0EMr0THWXcwePL8TrFVPYvaGPDL1FcTQ3rddLnLViIyaEfX6zbc7s0C9vtmz32bRoLzGW0Do2RLhwYydH/b/u9VyDF1wGnIlnhf9ThYBuel/GLEgVNL+Hdx4aZq1LlQwGaSbAM6OcrSUWVA9EmQ+gD9fsafNuhEc4jgcZU9rNhZwsFN5nM6nmM7GDFVluesoQtOssWxv2S1s9oSevoG1OfsTwDtwGshKa5TTMinwPM65ZGtOYqjxcQA8MWkGSWWCl2S9jgF+x1A/LhTWOcg9Mk0tlKKHVopLK15bUCWuW1TEdlWY3exfsLoN9GChfMwfzb2ronaU=)

### Other comments
I only had to resort to changing the css variable as the compact setting for density was not as dense as in vuetify2. If there is a more proper way to make table rows more compact, I am eager to know!

**Comment by websitevirtuoso** [comment]
Yes I think the problem with calculating offset. maybe connected with few last commits

**Comment by KaelWD** [comment]
This is the same as #17801 - items smaller than itemHeight
