### ISSUE TITLE
Error: Unknown custom element: <router-link>

### ISSUE THREAD

**Issue by gabyrusu** [vuetifyjs/vuetify#18]
I have an error when trying to build a sidebar navigation with sub-navs: 

> [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in component <sidebar-item>)

Here is my template:

```
<v-sidebar id="sidebar" fixed>
    <v-sidebar-items v-bind:items="sidebar_items"></v-sidebar>
</v-sidebar>
```
and my sidebar_items object:
```
sidebar_items: [
    { text: 'Dashboard', href: '#!', icon: 'dashboard' }
    {
        parent: { text: 'Users', href: '#!', icon: 'group' },
        items: [
              { text: 'All users', href: '#!' },
              { text: 'Deleted users', href: '#!' }
        ]
    }
]
```

This is the HTML:
```
<ul class="sidebar__items">
    <li>
        <router-link active-class="sidebar__item--active" to="#!" class="sidebar__item">
                <i class="material-icons icon">
                    <span>dashboard</span>
                </i>
                <span>Dashboard</span>
        </router-link>
    </li>
    <li class="sidebar__group">
        <a href="#!" class="sidebar__item-header">
            <i class="material-icons icon">
                <span>group</span>
            </i>
            <span>Users</span>
        </a>
        <ul class="sidebar__items" style="display: none; height: 0px;">
            <li>
                <router-link active-class="sidebar__item--active" to="#!" class="sidebar__item">
                    <!---->
                    <span>All users</span>
                </router-link>
            </li>
            <li>
                <router-link active-class="sidebar__item--active" to="#!" class="sidebar__item">
                    <!---->
                    <span>Deleted users</span>
                </router-link>
            </li>
        </ul>
    </li>
</ul>
```

What am I doing wrong here??

**Comment by johnleider** [comment]
Are you using a Vuetify template or your own? The error would tell me that you do not have vue-router installed.

**Comment by gabyrusu** [comment]
I have vue-router installed. I'm trying to build my own template based on the vuetify documentation.

**Comment by johnleider** [comment]
Could you try reinstalling your node_modules.

```
#npm
rm -rf node_modules
npm install

#yarn
yarn upgrade
```

And let me know if it continues to happen.

**Comment by gabyrusu** [comment]
nothing changed... I'm still getting the same error

**Comment by gabyrusu** [comment]
This is the firts SidebarItem component in Vue Devtools
```
group: null
group: null computed
item: Object prop
    href: "#!"
    icon: "dashboard"
    text: "Dashboard"
    router: true prop
sidebar: null
sidebar: 12 computed
```

maybe it helps...

**Comment by johnleider** [comment]
Do you have a repository that you can link me to or a reproduction link? The error you are having has to do with the registering of vue-router. The SidebarItem component only uses the router-link component.

**Comment by gabyrusu** [comment]
I just added one now: https://github.com/gabyrusu/vuetify

Thanks!

**Comment by johnleider** [comment]
You are not using vue-router in your code at all. You have installed it in npm, but that's it.

**Comment by johnleider** [comment]
You can review the official documentation for vue-router [here](https://router.vuejs.org/en/essentials/getting-started.html).

**Comment by gabyrusu** [comment]
I'm so stupid... I looked over that code 3 times before opening this issue and didn't see that vue router is missing.

Thanks a lot for your help!
