### ISSUE TITLE
[Feature Request] Reuse existing classes own frameworks on html

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#18002]
### Problem to solve
Improve performance, reduce css code

### Proposed solution
Let's consider this commit (one of many with the same issue)
https://github.com/vuetifyjs/vuetify/commit/ddf79ffa5582cc16e10c900103c1fecacb6fe330

Why framework don't reuse his own classes on html? Let's consider tailwind css. We reduce amount of repeting lines and improve reusability.

Please give me your own feedback if my thought in the correct direction. I or somebody could try to implement especially this is not so hard but good prophit

**Comment by KaelWD** [comment]
The utility classes are optional and often disabled or replaced with something like tailwind, so we never use them internally. 

> Improve performance

gzip exists
