### ISSUE TITLE
[Bug Report][2.7.0] Cannot set properties of undefined (setting 'scrollTop')

### ISSUE THREAD

**Issue by IgorIlgiyaev** [vuetifyjs/vuetify#18003]
### Environment
**Vuetify Version:** 2.7.0
**Vue Version:** 2.7.14
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
After upgrading to 2.7vuetify this error came up
I have no reproduction for this.

ERROR Cannot set properties of undefined (setting 'scrollTop') TypeError: Cannot set properties of undefined (setting 'scrollTop') at eval (webpack-internal:///./node_modules/vuetify/lib/components/VSelect/VSelect.js:641:65)

### Expected Behavior
everything is working but the issue pops

### Actual Behavior
everything is working but the issue pops

### Reproduction Link
[https://codepen.com](https://codepen.com)

**Comment by KaelWD** [comment]
#17085

**Comment by IgorIlgiyaev** [comment]
My dev said that when I add an item to the vselect it happens and the addition happens async.

**Comment by KaelWD** [comment]
Update to 2.7.1
