### ISSUE TITLE
[Feature Request] Need Slot to customize stepper's icon indicator

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18007]
### Problem to solve
It will help me to customize the component fully.

### Proposed solution
There should be a slot and prop that can disable the icon section.

Please refer images:
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/8d89c4dc-2475-40db-8ebc-93f6adb4b1b6)
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/7fa4e0bb-4b54-4a01-bb17-4e37787ab585)
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/65d02024-92e5-4008-b6e2-ad31ffcbbb20)

**Comment by NextThread** [comment]
hey, can I work on this?
