### ISSUE TITLE
[Bug Report][3.3.11] in iOS, The numeric keypad does not come out when using the otp component.

### ISSUE THREAD

**Issue by choigawoon** [vuetifyjs/vuetify#18000]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** iOS

### Steps to reproduce
here is reproduction video in iOS.
https://youtube.com/shorts/Kge6T-NgwQA

### Expected Behavior
The numeric keypad should come out of the ios keypad.

### Actual Behavior
When you type for the first time, the qwerty keyboard appears,
If you type even one, a qwerty keyboard without numbers appears.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVUtv00AQ/iuDLylS1m6pAClKSzmAuHFB4kA4bOxJsnS9u9odp42i/Hdm105q5yEVcfPON49vnv61zT47l68bzCbZlLB2WhLezwzAdC2kc+kzPUprSCqDvhO1Qumrw/sgEaRII5RahnA3y+ZL4byqpd8A4TOJEg2hn2UvdgD3sqEVy1UpSVkzLfqeXhTPxWKXsBZqwZG0lRVWs6ynlhTDI2oka0RS8H0UDjTrZ8EkLMytjzoDegC0cchKnMYSxyA9M2Viwxwi64uhEnpgfDkR1KFtQA9PZVso1NUF6iTeHxOu0ARFG0ZLWztZ0rHCWnolDbGCbUhzZ7lwQw0ehhJXVnMerCXn5cOylkrn7PBCeTDiJ4FEbSvUl+CgzFKjiAyGwEoldl/itMDGNh6SPciq8hhCnudn6v9SquMiWnJCGdfQJXascCEt09Tz05GYaDRLWjH+4RTi7nNe3Uzy17HGw0IZFaKxNV/T55lkDpSHuVRqPRAAfHl2WBJW3FTd4GQIToOT5jArC95j8YRquSIx597ytmy3gJ2D7+Rgt5sW0WQYtDiOGmkcvLaLLV1cXvb4g+sG1kNp3aZwMhDm/+aAG9xogglstxGJlIbm57dpL92frfgc3K0oac/atOidO36G0itHEJCa9uqp2llPsAWPC9jBwtsaRnwpR1Gdd8+aQFCHJdxFjavRN9Tawk/rdfVm9PZFpR3aTqkPcHfPibuB6aCF5HvQ99Zr1B2Mbm5vP15/ZEp7PF2RntdeuG7OIhrY+B62bZW6gHmaHUbJN7yJLcbl+KFq5AtxdfW2Z3NqlYjuwcjigKRodwPmn2C0tLYacYNHc1kl/gC7Mdy8v75O2e5ih9qecDeyMV/e2A5RS5f/Cdbw/ypRiSc5AmGW8bC0fmYZtym+Z9mKyIVJUZSVYTPec7X2uUEqjKuLB1YrfMN/nRpFZeuH2/w2f8eDFqgvzjHUYu7tU0DPTmbZuBeG1GLzilCdZopwc9OG6GRCy3mIMU58FxxwjV54NHyC4wF6XUpHZv20jqCT1LrS77jgfJAfw1Gty5Dq/GtP8v9yTt6iq98x4m6cJaIcurXIfv8FUxulbw==)

### Other comments
Is that something I can do, or is that a feature to be added by you?

**Comment by choigawoon** [comment]
I want to use it the same as the v-text-field. but no works now.

```html
      <v-text-field
        type="number"
        inputmode="numeric"
        pattern="[0-9]*"
        v-model="msg"
      />
      <v-otp-input
        v-model="msg"
        type="number"
        inputmode="numeric"
        pattern="[0-9]*"
      >
      </v-otp-input>
```

**Comment by hellmediadev** [comment]
This is a problem in VOtpInput.mjs. Numeric fields are currently not really supported

Add this line for testing/quickfix:
`"inputmode": props.type == "number" ? "numeric" : "text",`

![image](https://github.com/vuetifyjs/vuetify/assets/112478116/08a35520-08c4-4596-9540-efc76e7173ca)
