### ISSUE TITLE
[Bug Report][3.3.5] v-range-slider 

### ISSUE THREAD

**Issue by niZaliznyak** [vuetifyjs/vuetify#18009]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.0
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
The thumb-label is displayed separately from the thumb, even on the links that are attached to the documentation

### Expected Behavior
thumb-label is displayed above thumb

### Actual Behavior
thumb-label is displayed right from thumb

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUkFuwjAQ/IrlUyvFMQVOUYroOwgHQ5bi1nYs2wlFKH/vxk5UCge4ZWd3Z2bH2Vzoh7V51wItaBlAWyUCrCpDSNkxJ8wnMK9kDW6ACOmYbmpQ7xXthGqhogn2ASxib7MJCMdW75gSuzgr1EmcfeqtSv6fGMVKfqWMpd87aUN0AT+2cYHUcBCtCuSS6GsRBHl5nUpCHITWmb8anQ7+CrKZzzKynG2zqdOnjz4CWJR8VKMZVdJ8+/zLNwbTiFwV3Xs0jjxpraLHEKwvON/XBicxC9m53EDgxmqOOQZ5OK8X+SJ/m/Na+jBhQxg+j2wD1bYyPSpKPZzHtLA3sqkRpcejMPIh8OKRhzWOcdeaIDWwutHRzDJ5uYJz8JrtXHPy4JCkomNCUWYw/ITUw3NR446bo2AHjjkw+Pr4Yz150s3a9Vk3rbvTxqfuaZ/RuIbJJ890+wsxlP3t)

**Comment by KaelWD** [comment]
85c36e4b8fdf848903d988c7e277800eb6bcfe24 didn't work properly, rtl is only using child selectors
