### ISSUE TITLE
[Bug Report][3.3.12] v-otp-input loses focus after last field is filled; forms can not submited by pressing enter afterwards

### ISSUE THREAD

**Issue by xqqp** [vuetifyjs/vuetify#18016]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Linux

### Steps to reproduce
1. Fill all fields of the otp-input
2. Notice that the field lost focus
3. Try to press ENTER to submit the form
4. Form is not submitted

### Expected Behavior
otp-input not losing focus after the last field is filled, thus allowing pressing ENTER to submit the form.

### Actual Behavior
otp-input losing focus after the last field is filled

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUc1u2zAMfhVOF6dAbGPrTkFaZMCwF9ix6sGx6U2r/iDRHoog7z5Kcjo3vRToTfxIfj/Uw0l8876ZJxQ7sSc0XneE99IC7Oe68z4/c9E7S52yGBYog6ML5qXOiCNfK+sngrk2bkB9JwVjUtzDvl21X28dyQI9e+ThOB2NIing0GvVP70gPyxz/MzPRMQb/41wvXKSytduE1LC7NtVSC5jH5QniEhTyaqMd4HgBAFHOMMYnIGK71OlcQCNBJwB7lJ/U1U3CRwn25NyFi5ON3gDp2KGjUSnsdHu16YqfRwguf1UlgGw8QFntPQdx27StMn4OZkt9tiY2IrirDadb/5EZ/nDsoRcGlGK3UVUCnacail+E/m4a9t+sLzG/6Hm0Fik1nrTHnisDZMlZbAenDncNrfN13ZQkdZwg9HUx+D+RgxMIsV2JUNqfH6H1DKZFT5/KRILVuvuGJPGG+6WBWcMdUA7YMDw3khXa+tYV6030ZbTn/ngWtmneHXrPuY7P1xMfixzZktUj0nxvBXZKEuXDfH4D8BtNEc=)

**Comment by Dominic-Marcelino** [comment]
I'd suggest to add a prop to prevent the blur-event on finish.

https://github.com/vuetifyjs/vuetify/blob/e5c1c070fc77e0b26a6e308c3e21eb1d8753f475/packages/vuetify/src/labs/VOtpInput/VOtpInput.tsx#L113-L115

Related to #16458
