### ISSUE TITLE
v-text-field not clearing value

### ISSUE THREAD

**Issue by alvinkonda** [vuetifyjs/vuetify#1801]
### Versions

Vuetify 0.15
Vue 2.4.4

### What is expected ?

the value on the text field should be cleared after you you submit with enter

### What is actually happening ?

the value remains the same even after i set `this.newTitle = ''` on the method

### Reproduction Link

https://codepen.io/alvini/pen/mBVRaJ

**Comment by jacekkarczmarczyk** [comment]
It works when it's blured before clearing the value https://codepen.io/anon/pen/BwjZza?editors=1010

**Comment by KaelWD** [comment]
This will be fixed in 0.16

See #1729

**Comment by alvinkonda** [comment]
Thanks @jacekkarczmarczyk works fine
@KaelWD patiently waiting for the new version

**Comment by 91kiennt** [comment]
delete v-model and instead of replace equal value="1234"
