### ISSUE TITLE
[Documentation] Website and Documentation not accessible

### ISSUE THREAD

**Issue by Terr4** [vuetifyjs/vuetify#18023]
### Environment

**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
Visit https://vuetifyjs.com/

### Expected Behavior
working links, documentation accessible, menu works, pictures

### Actual Behavior
no working links, documentation not accessible, menu does not work, no pictures

### Reproduction Link
[https://vuetifyjs.com/](https://vuetifyjs.com/)

### Other comments
It seems the website has some issues right now?
I do not see any pictures, no formatted texts and the menu and documentation links are not working.
Seems some stuff e.g. CSS is missing?

br

**Comment by KaelWD** [comment]
47828613a0e67655a076b701f74e8d280c2a1d66

**Comment by lokeswari9** [comment]
@KaelWD i dont think it is still fixed please check the documentation https://vuetifyjs.com/

**Comment by Terr4** [comment]
> @KaelWD i dont think it is still fixed please check the documentation https://vuetifyjs.com/

Not working for me, looks broken as before...

**Comment by lokeswari9** [comment]
@KaelWD  Fixed now thank you

**Comment by MajesticPotatoe** [comment]
>Not working for me, looks broken as before...

try clearing your cache
