### ISSUE TITLE
[Bug Report][3.3.12] VCardText is not ssr friendly

### ISSUE THREAD

**Issue by DiscreteTom** [vuetifyjs/vuetify#18021]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Edge 115.0.1901.188
**OS:** Windows

### Steps to reproduce
Related issue: https://github.com/nuxt/nuxt/issues/22552

I'm using Vuetify with Nuxt. Here is an example `pages/index.vue` to reproduce the bug (see the reproduction repo for the full project code):

```vue
<template>
  <div>
    <div class="d-flex flex-wrap">
      <v-card
        v-for="(value, name) in result"
        :key="name"
        class="mx-2 my-2 flex-grow-1"
      >
        <v-card-title class="d-flex align-center"> </v-card-title>
        <v-card-text>
          {{ value }}
        </v-card-text>
      </v-card>
    </div>
  </div>
</template>

<script setup lang="ts">
const result = reactive({
  key: "",
});

onMounted(() => {
  result.key = "value";
});
</script>
```

With `ssr: true`, when accessing this page, got the following error:

```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <VCardText> 
  at <VCard key="key" class="mx-2 my-2 flex-grow-1" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) > > 
  at <RouteProvider key="/" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <VContainer fluid="" > 
  at <VMain> 
  at <VLayout> 
  at <Default ref=Ref< Proxy(Object) > > 
  at <LayoutLoader key="default" layoutProps= Object name="default" > 
  at <NuxtLayoutProvider layoutProps= Object key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

Uncaught (in promise) TypeError: Cannot set properties of null (setting 'nodeValue')
    at setText (chunk-BVQHDTV7.js:9152:20)
    at processText (chunk-BVQHDTV7.js:6491:9)
    at patch (chunk-BVQHDTV7.js:6397:9)
    at patchKeyedChildren (chunk-BVQHDTV7.js:7363:9)
    at patchChildren (chunk-BVQHDTV7.js:7277:11)
    at patchElement (chunk-BVQHDTV7.js:6728:7)
    at processElement (chunk-BVQHDTV7.js:6563:7)
    at patch (chunk-BVQHDTV7.js:6424:11)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-BVQHDTV7.js:7171:9)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
```

Everytime you refresh the page you will get the error message.

From the nuxt team's response, it seems like the VCardText is not ssr friendly.

### Expected Behavior
No error, and the VCardText can display the text.

### Actual Behavior
VCardText is not working.

### Reproduction Link
[https://github.com/DiscreteTom/nuxt3-issue/tree/main](https://github.com/DiscreteTom/nuxt3-issue/tree/main)

**Comment by KaelWD** [comment]
Looks like a vue bug: https://play.vuejs.org/#__SSR__eNp9Ustu2zAQ/JUFL5IBWTrkZsgp2iCHFugDbdATL4JE20wokiBXqgtB/94lKStCUORka3d2OLOzE/tobTkOgh1YjaK3qkFxzzVA3ckx/AKM+5NxR87ysVGDKEA3vdiB1OCEHxRylmCHF/GXUKGbSpGGiMZ927huj+KKSwlgmiCywTwvqOotrK5IAf2rq40u+vStkxbBCxxsBMreGofw+4HGn2gaTs70kJXVWimffRZmV+wERn81g0bRFWSjaVGOpGWZpHUQHKA12uPiEo4rLp+SZPJ7gCwrwte8S/wrbZ7v4HgPCzRxlDRBPFl0Hl8IY3WVHJEXVjD09OpJnkmy0RRKJOCsNb2VSrjvFiWp4uxwo+asUcr8+RJr6CigW729iPblP/Vnfw01zn6QLOFGimvtYePOgiIN7cdf32h3m2ZvukER+p3mT+GNGoLGBPs06I5kb3BR7ecYg9TnJ/94RaH9zVQQGhcT8ZxRFA/vWH+Ve1fexTmuZ9riNnla4pp6J05SR0ajhcYCLrfQ41PhbrkW14gmbBOCfzOT0o/XB7l1xvqCiL0y6CnO18BxcBrSEVzyjE45C7hWNd7T1WyOPSOzab5cnvxQ5js6jORmx+Z/QyQyPw==
