### ISSUE TITLE
[Bug Report][3.3.12] VDatePicker max prop doesn't work

### ISSUE THREAD

**Issue by chriskulwik** [vuetifyjs/vuetify#18028]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Make a date picker, add max prop with ISO format. Maximum date is not limited. 

### Expected Behavior
Should limit max date. 

### Actual Behavior
does not limit max date. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUL1uwjAQfpWTF6hE7LZ0QlBRqUM7dWAkDCE+WpfYsWwntEK8e89OkCJYkCpFke+7+37u1kf2Yi1vG2QzNg+obVUEfM4NwLzNCmvTMxVlbUKhDLoeSqCk6cyqco8OZrr4WeSM/q+E5gzEmSwu2RHpxOdiYEqlL52yATyGpvNW2tYuwBEc7uAEO1drGFHeURwHIF0foPeERZwaj0Z3w6Yk2OAB4sSYOgCSk/5b3Tg/vp9A/6VOL8TbomqinOShfl99rIJT5jOS56JLSNnYhHXhMl1Y/u1rQzc8RpW8b/iczSAhEaPQsc7ZVwjWz4QopSGaxEq1jhsMwlgtljQmXGOC0pjJWi+nfMqfhFQ+DGGOXmdbVx88OhLJ2WRgE9Tu9warfjI5PDx2Fj2WVcXWR48rbUGGLbrMoZHo0N260gVtuNZF62q16H7KzYkOXimz9xe3Ln268/oc8n87J7UotYmOpwlLQcm6Y7DNH3YSEFU=)

**Comment by chriskulwik** [comment]
Documentation seems contradictory. Says the type is number, but it should be in ISO 8601 format

**Comment by chriskulwik** [comment]
related issue is closed, this one remains open though. Not sure if the issue is fixed. 
https://github.com/vuetifyjs/vuetify/issues/18015

**Comment by webdevnerdstuff** [comment]
I believe this is fixed in v3.4.1

[Playground](https://play.vuetifyjs.com/#eNpdTr1qwzAQfpXjFruQSC3JFJxCoUM7dchYdxC2UkRiSZzOTiDk3XOyHQgBIem++/5+L5io0R8xqqG3uMGKbRePhu177QGqYWliHL/j0ATPxnlLMzSCrbCX0TUHS7DpzHlbo9yfgtYI+i7Wz+qMTOaVfgiVMTXkIkOy3E/ZrouBGC5Adg9X2FPooJC+RaYDiG9imDNhm1llUbw8LluBvT1BZpSyAWiV+H+FnlL5uoD5jJvZSA3m2Ge7VnH43v3smJz/z+JKTw2lG14XuFIrtcb8rtUb/t0AZ/tsAQ==)

**Comment by chriskulwik** [comment]
Thanks for the update @webdevnerdstuff, I'll close this ticket.
