### ISSUE TITLE
[Bug Report][3.3.7] VSwitch regression - readonly switch is not clickable anymore

### ISSUE THREAD

**Issue by lmunch** [vuetifyjs/vuetify#18024]
### Environment
**Vuetify Version:** 3.3.7
**Last working version:** 3.3.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a v-switch with the readonly property set to true and try to click it.

### Expected Behavior
Expected the click event to be triggered even when the state of the switch does not change

### Actual Behavior
No click event is triggered. It worked prior to version 3.3.7

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctuwjAQ/BXLl4JE4gOVKqG0ot+BOZh4aVz8ku2EIpR/r+MYisKhVD3ZO7ue2Rlvzvjd2rJrAa9wFUBZyQK8UY1Q1RXM2nRNRW10YEKDy1AC/VGEukGN4FBwiH3p0coB40bL0yvFwbVAMVrXUtSHWKcTeITIX2j2TPpfeCoyXXFARgcVuXEWS187YUMagi9rXEAc9qyVAZ1HMgWhMdyvLjVCWXA2/4EiaLQ3EkppPmZPeeJpfun3i/E2nv2wxlUYL7BQg3KhmC0/vdEx/8RMc8NTfJWnOH7QUFPchGD9ipCa6/iMgxSdKzUEoq0i6zhGXKuDUDFHo9bLclk+Ey58uIVL8KrYOXP04CIJxXnRJBPE/vSAVJ5MCi+jQoYKyXZ+kLijJlGvA1c40BwcuEcdTZ7dupq07pzl5PuYtxT64CdR1z7FvLks+S/LiWxg2g6C/QKnPaNyeoC33/wOIt4=)

### Other comments
I use this to show a "Are you sure?" dialog before changing the state of the switch myself.

**Comment by lmunch** [comment]
Tooltips are unfortunately also disabled now when the switch is in readonly mode.

**Comment by KaelWD** [comment]
b32d03c3a774087cceed17df9b1b138e3fce5ca3

Doesn't seem to be possible without #15904

**Comment by lmunch** [comment]
I see #15904 made it into v3.4.0-alpha.0. Great!
I did try v3.4.0-alpha.0 (using the Reproduction Link) but the "clicked" event is still not there in readonly mode.

**Comment by lmunch** [comment]
I just tried with v3.4.0-beta.0, but not luck. Will this issue be fixed in v3.4.0? 

Thanks
