### ISSUE TITLE
[Bug Report][3.3.12] assets folder (in nuxt 3) imports doesn't resolve in v-img src 

### ISSUE THREAD

**Issue by 3aluw** [vuetifyjs/vuetify#18039]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
just click the link

### Expected Behavior
to resolve the import as a normal img does.

### Actual Behavior
I'm getting an error : Page not found: /~/assets/Javascript.png)

### Reproduction Link
[https://stackblitz.com/edit/github-8sucmp-m2by2q?file=pages%2Findex.vue](https://stackblitz.com/edit/github-8sucmp-m2by2q?file=pages%2Findex.vue)

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin#image-loading
