### ISSUE TITLE
[Bug Report][3.3.12] VMenu inside VNavigationDrawer shifted to the right when opened for the first time

### ISSUE THREAD

**Issue by RCRalph** [vuetifyjs/vuetify#18033]
### Environment
**Vuetify Version:** 3.3.12
**Last working version:** 2.7.1
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Linux x86_64

### Steps to reproduce
Hover over the navigation drawer, then activate the menu inside the append slot. The menu is shifted to the right. Closing and opening the menu again positions it in the expected position.

### Expected Behavior
Menu is placed above the activator

### Actual Behavior
Menu is shifted to the right

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu3DAM/BVB55WFJD0Z2yD9h97iHLQW26jVCxLtJFjsv4fSPuBHsgiQozicGQ5NP+75rxibcQDe8i2Ci1Yh3Heese0orHoLA9ZXfXs1mr8KTfBCJ/UCibURklMePP7sOKYBOs5aeI3Ka0Fdz2GENEGSMvbyPOmS8tmXjSLbgK2KEby+4NXbgR8mlY9YPZpRYSiG+5hCzIeJyUXImozCEHmOMJLZGa+JXLkdX+IxQRlLmD546nLaCEzKrRt7q3IuOkrcLtH7rZyMMA8kJ/ufAUfGlSgMDVogy9+Qkd1Q7M9trjFp3KsDrgYppdmXmYU4d6zu5nhgRe58YTMe33DjYkgonIrNvxw8Xee+cLoTQJ+nZbVSanS+5d3xZ8SYWyl77YmmwZoxNR5Q+ujkA7XJNHg0DoQO7uGuuWt+SE2JpuUGshO7FF4yJBLp+GZig+bP2xesTp3V4eb2aHGqUeRdLh4rbUmG9LuIREcGCdJXIy1o01gLaBWtuB86f6CFW+P/58Wu+1z3/Hge8nuZq1qReiqOhw2vg5L1kcGf3gGer2+w)

### Other comments
It seems that any change of screen resolution fixes the problem

**Comment by RCRalph** [comment]
The same issue occurs to `VSelect` when opening the list, here's the playground showing this problem:

https://play.vuetifyjs.com/#eNqlUM1ugzAMfhUrFzYJiNpOOyA6dc9ReqDgatlIiJKUaap49zlJ6RC9VNoB4c92vh/vL+xd63w4IytY6VDqrnb4VimAcshqrUMZgOm/ryDApu+APrut2GvFbpMws9hh46AQROgXwp+WSj7N/pioRTSTDKFJx9fRQMlnxgjaxgjtwKI7R39C6t44uIDBE4xwMr2EhDIlfh3IprIOggnY+p2nfeIRrJIUYrW+VZvk8OwlowjRs5RF/kzWOv+0vaJTXTwvBQsDilZA6Pge6XpcsQ/ntC04b1pFz1rsxGByhY4rLfmO1rg5KyckZm0vd5t8k7/wVlg3b+doZXakk1g0RFKxdCbjxOnnAanrZlBYraPEtZd19dF6jTtuToIDmsygatGgeTTS4tk81mJ0F82rj5Ua6eCdUF92cevGhjvvJ5P/yxzYPNXBK44pC0ZJOr5gh1+wRAVS

**Comment by jbo023** [comment]
I have the same problem, here is another playground 

https://play.vuetifyjs.com/#eNp9UEFOwzAQ/MpiDgGJJohyQmklbvACDoSDSbapRey11psUVPXvbBJKKyFxsmc8ntHM694krovHGPOhR/NgSkEfOyu4rgJAOSxsjNN1AsEOrrXiKCwatjtkiMjeBgzyI1JZ4wZwzaoyNQXBT1mknZN6i1yZXxGA/3rWqBNWd4+hh47qKUD/v5MI+coAsWvdyNheSLGtxQ1WiJW6/Ddl8k1bRFnDB1ufoCyOxFm2cmP4qUOhJY619fFP73kdfZnnKYuz2RSmml0USCj9vJ7zkVhgD4wbOMCGyUOmi2ejHEA7JAGfWliNiqvsCbuO4IW4ay6y6zFgtlQzc7gxy3yZ35v5vLs1b98CAZJI

**Comment by RCRalph** [comment]
Is this issue being worked on?

These location issues occur in many other contexts and without any resolution to this problem the framework becomes very UX-unfriendly.

@johnleider @KaelWD @MajesticPotatoe

**Comment by johnleider** [comment]
This issue is not being worked on, it's still pending triage.

**Comment by trc-mathieu** [comment]
Also related to this issue: https://github.com/vuetifyjs/vuetify/issues/17126
More context is provided in the linked issue.
Seems this bug was introduce a long time ago in v3.1.3
