### ISSUE TITLE
[Documentation] Documentation website appears to be down

### ISSUE THREAD

**Issue by zyrif** [vuetifyjs/vuetify#18042]
### Environment

**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open web browser
2. Navigate to https://vuetifyjs.com

### Expected Behavior
Website should load as normal.

### Actual Behavior
Website shows a blank screen.

### Reproduction Link
[https://vuetifyjs.com/](https://vuetifyjs.com/)

### Other comments
`vuetifyjs.com/assets/app-20631314.js` - is failing with HTTP 404. Vercel returns error code `ID: hnd1::v2fdk-1691968210182-3d05fb3056f4`

### Screenshot
![image](https://github.com/vuetifyjs/vuetify/assets/24279322/1bbebd95-6653-4e83-b60d-2cc9cedcf2f4)

**Comment by websitevirtuoso** [comment]
Do it still persist on your side?

**Comment by ThornWalli** [comment]
Same problem.
![image](https://github.com/vuetifyjs/vuetify/assets/8287751/1b6c9e3f-ccc9-49d0-9346-836554bd74b4)

**Comment by ThornWalli** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/8287751/59ddde24-23d8-4f84-8d9b-17c4c8d5f050)

Had to flush my storage, presumably the worker?

**Comment by zyrif** [comment]
Doing 'Empty Cache and Hard Reload' fixed the issue for me. Thanks @ThornWalli
