### ISSUE TITLE
[Feature Request] Improve Access to Component Types (such as props) for TypeScript in Vuetify 3

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#18047]
### Problem to solve
I've often found myself struggling to extend Vuetify components in Vuetify 3. This is because I can't make my component wrappers know what props they can pass down to Vuetify Components themselves. Let's say that I want to make a component wrapper for VCard, how would I be able to ensure that my component wrapper has the same prop list signature as what VCard provides? What about slots? What about events? Where and how can I import that information and apply it to my own wrapper?

### Proposed solution
See:
- https://vuejs.org/guide/typescript/composition-api.html
- https://www.radix-vue.com/guides/styling.html#extending-a-primitive

```
<script setup lang="ts">
import { VCard, type VCardProps } from "vuetify/components/VCard";

interface Props extends VCardProps {
  foo: string;
}

const props = defineProps<Props>();
</script>

<template>
  <VCard v-bind="props" />
</template>
```

**Comment by NextThread** [comment]
hey, can I work on this? please

**Comment by KaelWD** [comment]
Duplicate of #16680

**Comment by MatthewAry** [comment]
@KaelWD The issue this was marked a duplicate of was closed by the OP. I don't think it's actually resolved. Anyways, I'm just letting you know so this request doesn't get forgotten.

**Comment by MatthewAry** [comment]
@KaelWD Can you please reopen this issue?

**Comment by moeshin** [comment]
```ts
import { VSelect } from 'vuetify/components';

type VSelectProps = VSelect['$props'];
interface Props extends /* @vue-ignore */ VSelectProps {}
const props = defineProps<Props>();
```

Now I am using this method. If there is no `/* @vue-ignore */` comment, an error will be reported.

```text
[@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

10 |  
11 |  type VSelectProps = VSelect['$props'];
12 |  interface Props extends  VSelectProps {}
   |                           ^^^^^^^^^^^^
13 |  const props = defineProps<Props>();
14 |
```

**Comment by cbrgpl** [comment]
The same problem. I wanted to extend vuetify component using wrapper and cannot access vuetify types because of an error
```ts
// tried different ways
import type { GlobalComponents } from 'vue';
import type { VTextField } from 'vuetify/components';

type IVTextField = InstanceType<typeof VTextField>;
```

The error:
```
[@vue/compiler-sfc] Unresolvable type reference or unsupported built-in utility type

/home/dmitry/Templates/credit-conveyor/src/shared/ui/forms/ZTextField/ui/ZTextField.vue
11 |  import { VTextField } from 'vuetify/components';
12 |  
13 |  type IVTextField = InstanceType<typeof VTextField>;
```
**InstanceType<typeof VTextField>** highlighted

**Comment by nolde** [comment]
Just leaving this here in case it helps someone else.

This is not _extending_ it per se, it is actually _wrapping_ it. It is, though, a very easy way to standardise components, and has full prop autocomplete support.

```ts
// PrimaryBtn.ts

import { defineComponent, h } from 'vue'
import { VBtn } from 'vuetify/components/VBtn'

export default defineComponent({
  name: 'PrimaryBtn',
  extends: VBtn,
  setup(props, { attrs, slots }) {
    return () => {
      const data = { ...attrs, ...props, elevation: '0', color: 'primary', rounded: 'pill' }
      return h(VBtn, data, slots)
    }
  }
})
```

You can freely add new props and play with the slots inside your render function (the arrow function returned from `setup`).
