### ISSUE TITLE
[Bug Report][3.3.12] VAutocomplete displays `item-value` instead of `item-title` on focus out for async object `items` prop

### ISSUE THREAD

**Issue by sean-lagger** [vuetifyjs/vuetify#18049]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. In the playground, search for an item in autocomplete past the first ten entries in `items.js` (i.e `Damon Calderon`)
 - Any selected entry within the first ten entries will show the title as expected
2. Click outside of the autocomplete component
3. The autocomplete will show the value of the `key` property of the selected item

### Expected Behavior
The title of the selected item should persist after on focus out

### Actual Behavior
The title disappears and only the value of the field specified in `item-value` prop is shown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV21T2zgQ/is7+UIyk9gkoffC0F6BUmiBNgPMde4Kc6M4G6JiSz5JDqQp//1WtkMWOJmbuXzAtnZXu8+zLxJfl63dPI/mBba2WzsOszwVDt9cKoCdeU/keflafiRaOSEVmnqp0iicTjRZocPVMsC8l+kJptsWhUlmry9b1Uvk8M5dtp7pkcJUmyzK0VituMJ2qsVEqmvSqN8eSSUFbElWPnftQiW/RQYTbSaW63lxz0mXIukqkeEz4VykhRfe4ILLUjEuozsvw19L4hUr8VNa/ErF2k7M2KRPmxiZO7DoiopUmeXaOFiCwWmX/ojEyTl24Va4ZAb3MDU6gw3KzMYj7RLrgziKy+/omyUtr0fhWO/FBwyvH7ZtL8GTvw0bG3DfWSt63h+rVUl4primuFSftpdeupbX6amFU5FarOXTQtHeWsHfBZrFB79Pe96BZUVhbReVGSBrZwoqpEq29vkgXt6vhHEM5zIrPMGwO/oAU/S0JSJNKzkRfSEz1IVrtzvw+s3K4Srguk5oz9LNOunRVKYOTdsvP7LzP0PpMwrafA2g1I18ZcGPH8RcJ3L6RN+i2RcW251IqgnefZ622/N/lXfgoaWqX6/Pv8ssVL8qI3WcNpUJtje70N+sqQ6RBhk6QSn1DyhX7YYvuYqBB0qfZ6PMYyW878KrTe+IXiuDslDbVal1/baeLZ5kkZYd3yGjnbiqfwLa6raqYu5lIqfC1YpGT0kyNXIpoObdXtF+2aIO8N+XrZlzud2O42SiyIzmhpybSKGLVZ7Fb0ktNoVylPPeRGdvh9Ew2oon0jq+HKHNemOjby0a2uSy1WVunJxS+7/oqtYsPfQHlYt6rUcTw3ofz/aOyeEcTc8g1YJB818hPTHjsJ6InkGrU3VPhKdS3fghwblObMnz11WQ/w9zuZvf6qryuBpL5A/vytHF5ghVVu12CTRyqTKrqfNXf5Pq0vcRLe2mQsGBkckNSWgY1Ww+tRhwC2oIOE1uxCKov/UT01fKD/hUwAU1NZqg0aDPjAymC9gz8vrahr1wHHbmaPp9ockU1n/F9AtXZApGBi3ZhYH/ujbZM3SMeqbgkzZGhuNiZO2LLPfgYTQTWdBguMUtTApnIpMGvwcNfmH6mMhUCjhEba4xjH24NnknMqJqX6QEpwH78JGJQjg02oZR/8y0UVDSYX8m1HVQnyXjHSVBqgX8LqlMVIFzEcbBrApvBV+wuaqYxcHU0CWijCuMmmXvwM1Qwamgx20Y+JAhOZhLhD2tbxoiYrS+N0Ld0NiAfZ0jQZ+EjVghHsp0jMZp2ENjwk04YO3xkfKXpghHejwOI+kzJB+pNuikPaKh0tQfzKDwZfhFN6S8z2rkWMgJkXtEB3RYn21/TH2xoNQVdA4GDdjYORbWEqFGwHnWNBSGjKVjsaAx9dmOtWmAzPJ3IqjMzx3mVCcNtLJ2PREU0Xu6yCezpqLlPtAS8AN1nUobRr7FqDqRPqwjKg404U56xYCfaDWhkTASTROEoygS8gF/NjY4q9hTur3AsdJ3YcRsd9KmcxGOhJk0HDGslshAEuIzKm7ZkIch44hM3IympkwzbRoqkFUUmSy++Tl4VFD7hb1wE0lppivbaaJQNhxMjKpPGjNJXNH/N+Go2EwbiXGqCbolDnTYA5tqIyFtii+erkNG8GimcYxwMaN/QpvuCUOWxTMxFUjQqQylc+HEM+xnM3TuRSwDhuVM31IdNh6uAzbUzqn7ZhI+4W3WcARsMXq9hYQD64yYhHtpwHJ+QVdFfxU5pEfTdGb0/iG+Z3QIPBrnV637bqu8h9I9r7oQtq7+AfmVHbs=)

### Other comments
I believe this is because, on focus out, the component clears the `search` value and triggers a refetch, changing the contents of the `items` prop at which point the component loses access to the selected item's `title` property. The example in the docs simply prevent a "fetch" request if the `search` term is empty. I don't find this ideal for my use case as I'd like to trigger a fetch request even if the `search` term is empty.

**Comment by rolu01** [comment]
Any status on this issue?

**Comment by rolu01** [comment]
@johnleider - should this be labeled with `C: VAutocomplete` and `T: bug`? Thanks

**Comment by KaelWD** [comment]
There's two solutions to this:

1. Use `return-object`. The model value will be the entire item object instead of just the value key, so its title will always be available even if it's not in items anymore.
2. Cache your items somehow. v2 had a `cache-items` prop but this is trivial to do yourself with a `Map<string, Item>`
