### ISSUE TITLE
[Bug Report][3.3.12] Carousel: height=auto makes scroll position jump

### ISSUE THREAD

**Issue by DragonFire7** [vuetifyjs/vuetify#18048]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Windows 10

### Steps to reproduce
I'm experiencing an issue with my Carousel. I want to use height=auto, however when I use it, it scrolls up or down weirdly, when transitioning. For reproduction you can jump in an example playground from the doc(like the cycle one), change height to "auto" and add some text underneath so you can scroll. If you then scroll a bit and click on the button for the next slide or on the delimiter or wait until cycle transitions the scroll will jump. Oddly enough it only does that when going forward, so not when going from the last slide (e.g. 5) to first one.

### Expected Behavior
No jumping

### Actual Behavior
Scroll jumps up or down a bit

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtWUtv20YQ/isDAoUTQJTyOhlukaBFTkUvaU+RDytyJU68D2Yfsh1D/73f7pK2rNi1nfaQBjwk3uc3M998HtKcj1fVu76fb6OsjquTIHWvRJC/LA3RybZuhLPRS0XNZaMkdZI3Xfh5WYkY7LKijltZt1Kx5iBdvRLN2QYXTEu+s+e1cM6eexzv7Fa6ZZVRb+HWuKdpW6+tw7FnXgFwRvyc2FCeeFg5PpOX2OVrgAzhOykDHTdW5bv5p//Ip8mt0c2XL178tHcL91reUqOET1619VrJC1qzUnW5Qp+iD7y+rBtpEBAJxRszTG7hHCAFeRHq7hWOXF0Vv2m3ow9pcLLAwX0Pbs1PFkMgIzWY3+KmJGJvFQt5qR9u/G4dGOTeR01t4oA8BxJahhk11ngZZIhYFC3ONGw2hHQFNyMvW2pZaDLWRH1Z0CQ7bVtKMgASmy230QSKgZRYwRKB8mxFkhYbIxJDn+MlUKQTsDiCFrStVbEPUczpXSAowJK0PkGIpok+XSqMW2oj/mXcvC8FObmKek4f4H4Ba+C2oDPhW9rElXQbJ80MzsOmoCDOWAvse2GaEAHiw93UFLDEz/zfc1fACoH/BXcFL2dl4u7H5e63yJ5QQlPpQ22VOMeOI4Irx1H8OmlaJx0oxWQbVR8DynI6jiXpvSx42ipYZFko/xwTFwkSJW00Du4irWXcsAhkolKC1qJhxT45MfLjrB8qQGFJI6A05kyTbRk8oRay96zpc2RaKWFa+NI7IT0KJCXKRYDVL18cqyEbUkmTZBE3EcGlsAefEEvySWDztk/3KOuGvkFeTdJXKtHQF98I7LCuQVuGVx04YJ8VxqbJ2iqAWWCwd6e8BnVlOYVeIHF/BTqHj4SgNCyT5jTYYir0rCCCGw/TPrjYkryQrmGoJLA1lOLUjXU93PYRPveIXlnoO6Q77FXyJ5vmHneHhAgErOG7vUnykyU01OM7dPRtEip4d+voqRIqWPfo6JskVBD/QP4U4zd2LCtwiXzKpUCCVgACNK/BEtk+JwgMJCOGOxhmjTy1PJaB1iLZG+IWrkNHWnxBFHhXarJEYBp2eptjwztBKiGTjv93Op4ettOLyjV3CGcIYYAbWchhl/8KS2NQKcCB3MxBZguRDrynZBTSrx+1qTyO/BeShhQkSgY2EDnGe3RkekpmwEzhsCCOxCS2srWRMeQ2p+YmWfdyV2j7/v64mNOv1xbHaB8w+wSLw+vUP/1N8zSlj0+Ne+T+dKU/lJHHKn3ibuLusdx9h2Vg+sYwPbon7qZvDNM3hukbw/SNYdLxPToubZPUJDlZ7DW1MPWN4770W+QFUoZo5FpEFehqyAJq7bPn44xQrfGQMTdzlOvcazqmj/sNoSOG0Db2aIhtWDwXzoDvg9WezRnsuDNp6lcHew45QdupC9h7ebDXStnXfXQ9enGQP6Rcv9k/cro3Lu0zOHn0np0PRzM6+iAhhzaN/uzY5cF7G13o8ojXGNwg7MpglxcwOVlcM1fNKoUI/PyTtwZtw0wNWnAe3bprVtD1C6H3x4tF0xqcTG3CrZsbGRam1ws0HFOn7e3r+ev5y1doivkwrtV4Hvt5RktQp0uzg0X8riBZtRb9gdmykU0POVpWQErzB3x4i2MLB4GzRhvT6uzMm+LL3vJcel2vUitTOoAsq4GjbCY5/AhTD4YLG19hL2AQJa/G20ArUWYfG9LBtf2wDra+Cm1I9q7azap8DcwXn6vTvwFlpKQI)

**Comment by lewi919** [comment]
I'm experiencing the same issue
Vuetify Version: 3.3.13
Vue Version: 3.2.13
