### ISSUE TITLE
[Bug Report][3.3.12] VSlider type error of thumb-label slot props

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#18043]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Edge 115.0.1901.188
**OS:** Windows 10

### Steps to reproduce
use `thumb-label` slotProp of VSlider in a TypeScript project

### Expected Behavior
No type error

### Actual Behavior
![image](https://github.com/vuetifyjs/vuetify/assets/40021217/ee2d5202-d8f4-4fd3-90ef-9b8400ad4e8e)

Volar give the following error
```
Property 'modelValue' does not exist on type 'undefined'
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctuwjAQ/JWVe6CVSCxKDxWCil76Cb0QDiFZhFu/ZDtpqyj/3rUJaoALUm/enZ2ZnfWmY6/W5m2DbMGWAZWVZcCXQgMs28xLUaODNlOmRrkqWFswqGTpPb1VyJ6pDIdG7TJZ7lAmGhFPMnA3AonRJZn3UjbYF2yYBug6+APyYN7EN9b3swfo+0GQny/GT5tReYZR6SsnbACPobFpWihrXIAOHO6hh70zCiaUdxLHASqjfYAWVhEn06h41CA2m7IjPVOlzT+80XSlLtKKAfAFW0DqxB7JxrpghxCsX3Be1ZpolE20LtcYuLaKr2mMu0YHoTCrjVrP83n+xGvhw7ido1fZzpkvj45ECjYd2QSx/7nBaphMDrPHo8XQi7/io8eVNifDFl3mUNON0d0a6YI2jnUBXUWL7vTZPR1cCv3pL25d+XTnzWnJ/2VOalFqGx37KUuLkvWRwba/BMkKXA==)

**Comment by KaelWD** [comment]
Uh yeah that slot doesn't have any parameters.
