### ISSUE TITLE
[Bug Report][3.3.12] VTab not selected on not exact links

### ISSUE THREAD

**Issue by victorcuena** [vuetifyjs/vuetify#18044]
### Environment
**Vuetify Version:** 3.3.12
**Last working version:** 2.7.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Play with the ref default value.

### Expected Behavior
In VTabItems this used to work.

`<VTab value="/myfolder">` should be selected on paths like `/myfolder/1234` 

It is also documented that VTab has a [exact](https://vuetifyjs.com/en/api/v-tab/#props-exact) property but it is not being respected.

### Actual Behavior
The tab is only selected on exact match.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1PwzAM/StRLgNpbbSP09ShceTEhduyQ7d6EGg+lGSt0LT/jpO20HUaQ+IWPz/7PdtZH+mjMWl1ALqgmQdpytzDA1eEZFWSGxOfMdhp5XOhwLZQBH2+daRKpC6gXHKKIadk+4rkUlsEjBUyt5+cfhd1ZaTKywMgRSvA9BNqk2cFGYvZ63Rf647+UushvY1d32MtVKHroctzhYaTiND23FgwFdv2KLdrG5fB4dXaH7zbMQLnSw5Ic4OM9W6DodtZYTxx4A/NiYQ02npyJBb25ET2VksywrOOAp0Q7Os8CXtcBsbdCA2yyXQ2H92HNGO/MzLWCKIUHdNGK5G5Sd+dVvhzjqEJbxOO0wWJSMDQQ4g5ffPeuAVju0JhGV5CVDZV4Jkykq2QxuxBeSEhKbRczdJZOmeFcL4Pp+BksrW6dmCxCafjnowXe/xoN6VaZlSYTBuJFktK/DpB46I3Q8EKbGJBFWDB/nWkQVl/rEHqYrSgfuLqhAsvhfpwg13vXNzzujP5v5ljt9BqExRPYxqNonRTQTdfQtJbpg==)

It's hard to reproduce on the vuetify playground, I'm trying to replicate it as if I was using vue-router.

**Comment by KaelWD** [comment]
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#summary
