### ISSUE TITLE
[Feature Request] V-Card-Actions > can modify the default styling of v-btn by props

### ISSUE THREAD

**Issue by asendari** [vuetifyjs/vuetify#18057]
### Problem to solve
In your documentation https://vuetifyjs.com/en/components/cards/ you say that v-card-actions modifies the default styling of v-btn and you decide to use "text" variant for button. And now we need set variant on each button in each card to define another styling.

### Proposed solution
Maybe a props for v-card-actions like: "btn-variant" where we can define defautl variant for each button or maybe in theme configuration to define default value for each component.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/global-configuration/#contextual-defaults
