### ISSUE TITLE
[Feature Request] Can we export the InstanceType of the component?

### ISSUE THREAD

**Issue by wiidede** [vuetifyjs/vuetify#18055]
### Problem to solve
I see `export { VForm } from './VForm'` in index.ts and `export type VForm = InstanceType<typeof VForm>` in VForm.tsx. But I can not import instance type of VForm.

### Proposed solution
Maybe we can export VFormInstance(InstanceType<typeof VForm>).

Why we need Instance? Because now we often use auto import component. So, we only need to import the instanceType manually

**Comment by KaelWD** [comment]
>  I can not import instance type of VForm

You just import VForm and use it as a type

**Comment by wiidede** [comment]
> You just import VForm and use it as a type

do you mean:
```ts
import type { VForm } from 'vuetify/components'
```

this is not suit for [consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/)
