### ISSUE TITLE
[Bug Report][3.3.12] Missing box-shadow for Scrollable Dialog

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#18052]
### Environment
**Vuetify Version:** 3.3.12
**Last working version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a scrollable popup and open it.

### Expected Behavior
There should be a box-shadow around the dialog.

### Actual Behavior
There is no box-shadow.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1lk1z2yAQhv8Ko0vbmcjKR08eJ5M2nU5vPaS3OIe1IDYxAg0gOU7G/70LSLJQ2mlopzfzwj7v7mIBdy/Zp7qetQ3L5tnCsqoWYNnVUhKyaHOtduSxMZY/7C+XWcmkZXqZkVKAMSjUkJ+dLzO/2q+nHIRakzavFGUCVwQBQ0yplRCwEozsOLUbnIPGqiEYw3tzDDdC2TmUlrdglca1L6TWqjbkMArwjisrSamEX1RrXoHeoxvqXFIvYRTGkO81k+RLSG9R+LijcxHV3ZFL0DT2ckpuuRXs6pYJVlpyoxpp9d4BR5NREOUtp0xfuTX9719Q2ZMlxu4Fw6Q3jK83dk4uTk/rp6jgsClAucrXWjX1q05XZ257lGiqY3lxIMFN8AGfYQMVmBPyY8Ncy0A0znwVZLR1GfuQN5A0cBlDgpICkWsBlJlNxDmKKSi9AqqwhhGolxIwTIBuIkqvJEHWvKliSFCSIPw52qROSEHIeIfCOAGwaSxEhE5IQCiBHwCMGb2SAjGSAwFJyTemn9latVzGTLcgDWnNDiaQXkrAaHjmYgzphBREIxmPEEFIQDRiDTru8iClYPQW+0q+gsFDeoTyciKpirPx4yRAI2nUlV75DWRQwyk5Pm+HkxoP3L85qN2lpKSZnsnja2iFSeYU9JbJ3B3Hreu9tDjjTFG4LgUvt8OZTS7JAwjjPue4EzdCoTqpa3xx/U/zW2j/4D30ctqTfqJ/F/iGOrPwrHCbo3b4O7p3F/hC4HXYE/ZUK20JZQ/QCEteAoeChfcf+hEhmtlGy+MYV3R34Jy8e3cyleeh0EE/hB8HL+BgUQwZZCcZr1wKeQX17NEoiY8j77PsJvAOmPfOywxfT26MN7e1tZkXRUklhuHFzFs9k8wWsq6Ka1xW4B/X8gq3SFXXF7OL2ceCcmPH8oyZKl9hhwzTCFlmXcbexr3E3mDVrfQOZ+fBotNy/KyM83jFLtCwZTrXTOJ/3z303lbSJGxc1mTqVWld6w/YcMHl1kx6XRrf57s+yX+r2dMc6t45Hk4ynyhah4js/idWJHQM)

### Other comments
This appears to be happening because of a recently introduced change to the `v-overlay__content` parent element in the DOM, which now has `overflow: hidden` when in scrollable mode which suppresses the box-shadow on the dialog.

**Comment by cll0ud** [comment]
Using this CSS as a workaround for now:
```css
.v-dialog--scrollable > .v-overlay__content {
  overflow: initial
}
```
