### ISSUE TITLE
[Bug Report][3.3.13] Data attributes doesn't work 

### ISSUE THREAD

**Issue by Rusinas** [vuetifyjs/vuetify#18067]
### Environment
**Vuetify Version:** 3.3.13
**Last working version:** 2.7.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add an attribute with 'data-' prefix
Check dev tools

### Expected Behavior
Data attribute exists

### Actual Behavior
Data attribute doesn't exist

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkE1OwzAQha9ivClITSxUVlVBZQcnYNF0kcYTMPhP9jSAqtydsZNKUbqpxM7zPPO+N7M78Wfvy+4IfM03CMbrGuGpsoxtuqL2Pj9z0TiLtbIQRimLCD9YtAq0ZF1hnAT9WHET3yvOECK+SiqHBymyxpomRnlS0Z84g8SclJQhyEZMAlIZm6A8sgh4HHIq411AdmIBWtazNjjDFrTbIrUzRr4RGaVjj6njdvECWjv25oKWN4u7BBgsyYwv+eBWmNqXn9FZOtApuVTjR6z4mmUlaURJdcU/EH1cC9FIS2N0ENWF0gIK643YUpsIR4vKQCGd2a7KVfkgpIo4lUuIpjgE9x0hkEnFlxMMqvb3CtTYmQn3qwExaoWuDzExLrwFATsIRQArIUC4dqXZ2HSt2dfFaoneV7ang2tlv+Ls1k3Md96dQ/5v5+yWrPaJ2C95DkroYYLv/wCsIgeP)

**Comment by KaelWD** [comment]
![Screenshot_20230816_201000](https://github.com/vuetifyjs/vuetify/assets/16421948/6073345d-da0b-4b9d-b0a0-145af47fe622)

**Comment by Rusinas** [comment]
@KaelWD what is the point of putting data attributes on the wrapper, while random attributes are being put where most of the people need them? 🧐
We have a lot of e2e test that are expecting data-test attribute being set on interactable components. Not really sure what would be the best way to fix it now

**Comment by KaelWD** [comment]
#7295
