### ISSUE TITLE
Prepend icon callback not implemented

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#1806]
### Steps to reproduce
Set prepend-icon-cb in a v-text-field

### Versions
0.15.7

### What is expected ?
the callback should be triggered

### What is actually happening ?
Nothing happens. Searching in the full vuetify /src folder, the param prependIconCb is defined but nowhere used :-)

### Reproduction Link
Assuming there is no prependIconCb in the source code, the reproduction link is useless.

**Comment by jacekkarczmarczyk** [comment]
Reproduction link is always useful, please provide it

**Comment by jacekkarczmarczyk** [comment]
I'm closing it as it works on dev branch, you can however provide reproduction link to be sure

**Comment by jacekkarczmarczyk** [comment]
@tafel - you're passing String to prependIconCb instead of Function, use `:prepend-icon-cb="..."` instead of 'prepend-icon-cb="..."`

**Comment by tafel** [comment]
oh, I forgot the sign! Just to know that I was using @ in my code. I was thinking of a callback like events. We use everywhere @ for this type of actions. I didn't notice that colon had to be use here (even if it's called a callback).
thanks
