### ISSUE TITLE
[Bug Report][3.3.13] VImg "window is not defined" with Vitest (flaky tests)

### ISSUE THREAD

**Issue by mdoesburg** [vuetifyjs/vuetify#18072]
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
This issue is hard to reproduce, but is resulting in flaky tests when using Vitest.

Our tests randomly fail from time to time with the following error:

```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 10 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: window is not defined
 ❯ Timeout.poll node_modules/vuetify/src/components/VImg/VImg.tsx:204:7
 ❯ listOnTimeout node:internal/timers:569:17
 ❯ processTimers node:internal/timers:512:7
This error originated in "tests/components/Header.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword
```

The errors are always pointing to: `node_modules/vuetify/src/components/VImg/VImg.tsx:204:7`

I am going to assume it has something to do with this, since it's the only `window` usage in that file:

```ts
timer = window.setTimeout(poll, timeout)
```

Hopefully someone knows what the issue is here, because having flaky test pipelines is getting quite frustrating. 😂

### Expected Behavior
Expect non-flaky tests when using VImg component.

### Actual Behavior
Flaky tests when using VImg component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkEGOwjAMRa9Sed0kGnVWXXEPwgKIRxNo3MoORQj17iShSFXZILH0t/2fv7d38GHoOaqwH/RJeoIW7paqys4NsdBWRcnaeMFcW/iPcZDWmKOjtOaw8yNrwmhoCGaTxgxfKPqAyvVh0+hG/xrnJS5ljRLUgfurICcTC/UCE/3f7QPUPFkIP80TMWuq2x8kM968TQKOyIqRHDLyp5FWa8tYq9ZbtEyfLE1QQ+fpLKtfH6X8efs68rvMxS1b7TJxqqEcmtDPDdg9ANsIqg4=)

**Comment by KaelWD** [comment]
https://github.com/vitest-dev/vitest/issues/1293
