### ISSUE TITLE
[Bug Report][3.3.13] DatePicker V-Model undefined

### ISSUE THREAD

**Issue by rafalpiechowicz** [vuetifyjs/vuetify#18074]
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Empty date-picker

### Expected Behavior
Should return object by first click in the v-model

### Actual Behavior
V-model return undefined after first click. The next one returned date object

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by nekosaur** [comment]
Needs a proper reproduction
