### ISSUE TITLE
<v-select></v-select> with @change event  doesn't provide output on first click

### ISSUE THREAD

**Issue by mjarpitanand** [vuetifyjs/vuetify#1807]
https://codepen.io/anon/pen/PJZgZG 
Here is the codepen , if you will click on select you will get null and then, on second click you will get the value of the first one click.

BUT @input in place of @change solves the problem.

Any comments

**Comment by jacekkarczmarczyk** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.

**Comment by mjarpitanand** [comment]
Ok! WILL DO NOW 
THANK YOU!
