### ISSUE TITLE
[Bug Report][3.3.13] Uncaught SyntaxError: The requested module '/_nuxt/node_modules/vuetify/lib/components/index.mjs?v=448623a1' does not provide an export named 'VDatePicker' (at vuetify.js:6:28)

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#18080]
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.3
**Browsers:** Firefox 115.0
**OS:** Ubuntu undefined

### Steps to reproduce
```javascript
import { VDatePicker } from 'vuetify/components'
```

### Expected Behavior
I should be able to import `VDatePicker` component

### Actual Behavior
Error:
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/vuetify/lib/components/index.mjs?v=448623a1' does not provide an export named 'VDatePicker' (at vuetify.js:6:28)

### Reproduction Link
[https://github.com/begueradj/vuetifybugdatepicker](https://github.com/begueradj/vuetifybugdatepicker)

### Other comments
The official documentation says VDatePicker is available in Vuetify version 3.3.4. I tried this version and some others more recent, but I can not import and use this component.
Actually, I just noticed VTimePicker is not available either. Weird

Billal Begueradj

**Comment by MajesticPotatoe** [comment]
`import { VDatePicker } from 'vuetify/labs/VDatePicker'`
https://vuetifyjs.com/en/labs/introduction/#usage

VTimePicker hasn't been developed yet

**Comment by begueradj** [comment]
Thank you for the feedback @MajesticPotatoe 
But when I tried what you suggested but I am getting the exact same issue :cry: :

**Comment by begueradj** [comment]
@MajesticPotatoe  I will downgrade the Vuetify version and see ...

**Comment by MajesticPotatoe** [comment]
i just cloned your repro, started it up, added the one line, and it worked fine...
![Screenshot 2023-08-17 at 1 25 09 PM](https://github.com/vuetifyjs/vuetify/assets/27827979/9d09bb7c-da5b-451f-9e86-e14f68994b37)

**Comment by begueradj** [comment]
@MajesticPotatoe  Wow !!! That works, indeed !!! 
I guess I did something wrong when you asked me to do that, at first place. Sorry.

Thank you so much for the help !  That is very important for my project
