### ISSUE TITLE
[Bug Report][3.3.13] Background colors of toolbars: on-surface-variant?

### ISSUE THREAD

**Issue by carpet-berlin** [vuetifyjs/vuetify#18091]
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Windows 10

### Steps to reproduce
For `v-toolbar`, `on-surface-variant` is used as background color (`$toolbar-background`).\
(Same for `v-system-bar` / `$system-bar-background`)

Instead of an "on-" color I would rather expect a non-"on-" color as background.

I'm not quite sure about the typical use of the surface-variant colors. However, using `surface-variant` as background color and `on-surface-variant` as text color seems more appropriate to me.

### Expected Behavior
Non-"on" color as background color

### Actual Behavior
`on-surface-variant` as background color

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUs1u2zAMfhVCOyQFYjtDdgqyoRuwvMCGXaoeFJtpvOoPkuymCPLupWQ7dZ0eClQHmyI/8uNH8e7E2gZDvX/O/3u2ZrWyxgU4QelQBPzXxeAMe2cUzHrsjGuu8ZigpdE+QB+A728T5yeuAcIBFa4h2QAV7kUjw9/OOZP1wyHMFl0sIf0FCpCiozsQnzRuDImHM9+4vSgxa4WrhQ6cUekvWzrL5VB8gBqdvYte0tlux+jzxR6s7h+/5xuu2YL9tDYn8TS6TUBlJWn/ESGbNhPWJjNdaExB1Bpd7wL4fbRYBqzW8Es2CAGPAebXvd2A0fCMUpon2D3AfBoeyhFHMEbuxCsDwB+jusp5nl+AxRQZPW/7i56u/U0xkkV6uwXJlLC0MEaT7vQQvA/4OMr+aXhcrXjn7BCC9euiKCtNaRXKunW5xlBoq4pbghWu0aFWmFVG3a7yVf6tqGofxu4cvcp2zjx5dFSEs/5JEk1ctg9Q9cjE8HXVUfS+TIqdjxxXtQsibNFlDnWFDt1HJU3SxrImoStpaclox2jgstaPfjLr0qc53w1Nfk5zqhZL3UfG84KlRom6y2D3L7EiWHI=)

**Comment by johnleider** [comment]
Due to time constraints we are having to push this to v3.5.
