### ISSUE TITLE
[Feature Request] Please add the ability to lock the screen when opening the VNavigationDrawer component

### ISSUE THREAD

**Issue by romanticsoul** [vuetifyjs/vuetify#18098]
### Problem to solve
There will be no double scrolling if there is a lot of content in the VNavigationDrawer component

### Proposed solution
In many components, you have already implemented the ability to choose a scrolling strategy, perhaps adding this to VNavigationDrawer component will not be a big problem.
P.S: I used Google translate to write this text

**Comment by danilpon98** [comment]
I also faced this problem. I need to block scrolling when VNavigationDrawer is open.

**Comment by KaelWD** [comment]
Duplicate of #19477
