### ISSUE TITLE
[Feature Request] VDatePicker should not have 日 character at each date when locale is ja.

### ISSUE THREAD

**Issue by motoo1789** [vuetifyjs/vuetify#18093]
### Problem to solve
The following URL issue seems to have reappeared when v-date-picker became available in vutify 3.3.4.
https://github.com/vuetifyjs/vuetify/issues/10787

Unnatural UI.
It's unnatural to have 日 character at each date of VDatePicker.
![image](https://github.com/vuetifyjs/vuetify/assets/53427863/f4dd7ae9-c743-44e1-b5a5-9513c3221a24)

### Proposed solution
If you could remove the '日', that would solve the problem.
You may also want to work on a solution to the problem link

**Comment by jacekkarczmarczyk** [comment]
probably same reason and same solution as in https://github.com/vuetifyjs/vuetify/issues/2786#issuecomment-351394458
