### ISSUE TITLE
v-text-field @change fires at wrong times

### ISSUE THREAD

**Issue by geertolaerts** [vuetifyjs/vuetify#1809]
### Steps to reproduce
Create a `v-text-field` with a value and @change binding. See when the @change fires

### Versions
Vuetify 0.15.7
Vue 2.4.4

### What is expected ?
The @change handler is only triggered once when the field changes

### What is actually happening ?
The @change handler seems to trigger when the field doesn't change
The @change handler seems to be triggered twice

### Reproduction Link
https://codepen.io/anon/pen/JrGqdX

**Comment by KaelWD** [comment]
This should be fixed in 0.16

See #1730

**Comment by jacekkarczmarczyk** [comment]
@KaelWD I've checked on dev, event is fired only once, but it's fired also when value hasn't changed - focus the field and blur - you'll see "updated" in console
