### ISSUE TITLE
Feature Request Allow Vue Components or html in v-carousel 

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#181]
This will make it usable for other purposes and will also display text or buttons inside the carousel slide

rather making it available only for images

**Comment by sebastianmacias** [comment]
+1

**Comment by johnleider** [comment]
The slot is missing from the docs, you can already do this.

**Comment by samnau** [comment]
Seems relevant to point to this newer thread about `v-window`:
https://github.com/vuetifyjs/vuetify/issues/2843

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
