### ISSUE TITLE
[Feature Request] ability to add class to row

### ISSUE THREAD

**Issue by nct124** [vuetifyjs/vuetify#18101]
### Problem to solve
add styling for the whole tr

### Proposed solution
v2 has "item-class" property, can this be introduced back?
https://v2.vuetifyjs.com/en/api/v-data-table/#props-item-class

**Comment by aazvf** [comment]
I'm trying to solve this too, there is lots of discussion online about using `item-class` which I expected to work but I'm now realising this only existed in vuetify 2, not 3... 
I just want to add a class to the row, not have to rewrite the entire `<tr>` - We're already using a lot of `v-slot:item.key` for some cells, I don't want to use the `v-slot:item` as it would require a lot of changes just to add a class

**Comment by Dgbsoft** [comment]
duplicate https://github.com/vuetifyjs/vuetify/issues/16991

**Comment by ricardo17coelho** [comment]
@nct124 u can use the `row-prop` prop and return an fn with Obj, which contains a key with `class`, then all the classes inside this key will be applied to each row.


```
... 
:row-props="getRowProps"
...

function getRowProps() {

   return {
      class: 'my-awesome-row-class'
   } 
}
```
