### ISSUE TITLE
v-text-field v-model lazy doesn't work

### ISSUE THREAD

**Issue by geertolaerts** [vuetifyjs/vuetify#1810]
### Steps to reproduce
Create a v-text-field with a v-model and add the lazy modifier

### Versions
Vue: 2.4.4
Vuetify: 0.15.7

### What is expected ?
The model is only updated on the change event and not the input event

### What is actually happening ?
The model seem to be updated on the input event

### Reproduction Link
https://codepen.io/anon/pen/WZrBMW

**Comment by KaelWD** [comment]
v-model modifiers don't work on custom components in Vue: vuejs/vue#5743  
You have to do it manually with an event listener: https://codepen.io/anon/pen/zErVJj?editors=1011

https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

**Comment by geertolaerts** [comment]
Aight, didn't know this. The change gets triggered twice though. The first time only once, but if i change it again and click outside it, the update seems to be triggered twice. Is this normal?
