### ISSUE TITLE
[Bug Report][3.3.14] VDatePicker does not scroll modelValue into view after change

### ISSUE THREAD

**Issue by simon-lorenz** [vuetifyjs/vuetify#18119]
### Environment
**Vuetify Version:** 3.3.14
**Last working version:** 2.7.0
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Linux

### Steps to reproduce
See reproduction link.

### Expected Behavior
When the v-model value changes, the calendar view should automatically scroll to the date and highlight/select it.

### Actual Behavior
The calendar view does not scroll automatically.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUc1OwzAMfhUrl4G0NOXngKYyDfEYlEPXeiLQ/ChJi1DVd8dJO9Ftl0mcGtvfn923gb1Ym/Udsg0rAirbVgG3pQYoel5Zm56pqI0OldTo5lZqNoTmVtZf6KDnyjTYPpcsdku2LcQJYMnbBw27uqU+wY1+jS9ipC8ojEyC/DEa2W+HAaIajGMhYj0nI+hptNiZkhdisRGVvnbSBvAYumkxqaxxAQZweIARDs4oWNExVhEOQLo+TKbPEXKju7a9nWaHTtdBGg1z+ptbGKZEEZ/1VdtF1uo+z3OeP/H8jkQBxphqykEJ2JpNEbiqbPbpjabfkGTKeeBLtjkKl4yixbpkHyFYvxGibjTR6Oqyd5nGILRVYkcw4TodpELeGLV7yB6yR7qZD8t2hl7xvTPfHh2JlGy9sAny8HOF1YxMDnezxdzjbbX30eNCW5Bhj4471A06dNeudEZbrnU2ulhtPv1IB2+l/vJnt659uvPbMeT/dk5qUeo9Oo5rloKS9cRg779DLSY+)

**Comment by webdevnerdstuff** [comment]
Another example that illustrates this issue (made it before I saw this issue). 

https://play.vuetifyjs.com/#eNqlU9tq4zAQ/ZVBLDRhYzuXsgshKSzs6+4P1IWqtkzc+iJkOWkw/veOLrYsaJOWPoR45szonDka3XekEUn0h/Pw2DKyJTvJSl5Qye7iCmB3DCjn+lMHSV1JmldM2JROivo0hraqAPw1+5j8iskE06hkrzLIclakcAzKOmUF1pV48CEmIM+cYVi15RMTGBf0ycOjKVOkqb7NfWZUUX1EbeFLzCqeunDFlDUKgxQ9/qcUbK8Oslqqhq5zPdD3V7s0S1aLkkrJ0r/Y+gUmr+89Nn9kg7rduLwwaoyA58kL+jwKcfcxThkTBzeH+hTQ9JkmrJJYiuvQOHSrE25PJoi6vvEWh/ydEjyR8cEYJmNewC6avAwMm0TkXELDZGseSF7yWkjoQLBsAScqkwP0kIm6hBt8WzfGFTy+kXiRZ9irwtnqdu7SWv0ALCeAUm/z6+V6g4jD/KsyRWacxx/df73NM31weKRFy+bwE1Z9NEIoxQKTpOIbso/qMI/RraFhq9gJFPnMk2L7baf2A8ls5wJmc9jjqvUernWOmJmi5apLn68d8TuU0k82ZG2VyLyuvIKh6R3pON2nHByWanTSJC76qaqtFSPZRRv1IGoLzd7hxpF+QTbhJvxN1P9tuCIPby/e0MM=

**Comment by simon-lorenz** [comment]
This has been fixed since 3.4.3, probably via 6901d24e0397c7d4cf95c2f42f9e421e6070a9c9.
