### ISSUE TITLE
[Feature Request] VDatePicker: Catch selection changes inside the calendar view without the need for action buttons

### ISSUE THREAD

**Issue by simon-lorenz** [vuetifyjs/vuetify#18122]
### Problem to solve
The model value of VDatePicker does only seem to change once a user clicks the "OK" action button. I'd like to let users select dates inside the calendar view without the need for an extra action button click.

### Proposed solution

I've got two ideas:

1. add a new event like `update:selection` which fires whenever a user selects another date/range inside the calendar view. It should contain the selected date or an array with the date range, depending on the `multiple` prop.

or

2. make `update:modelValue` fire immediatly on date/range selection inside the calendar view. The v2 DatePicker worked similarily.

**Comment by avarixe** [comment]
I think this behavior is already included with the `hide-actions` prop

**Comment by simon-lorenz** [comment]
Oh, you're right, I totally missed that. Thanks!
