### ISSUE TITLE
[Bug Report][3.3.14] v-select update modelValue is not working properly in 3.3.14

### ISSUE THREAD

**Issue by sengottaiyans** [vuetifyjs/vuetify#18124]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
1) create dropdown with @update:modelvalue
2) check the modified value is reflected inside @update:modelValue function

### Expected Behavior
The changes should be reflected inside @update:modelValue

### Actual Behavior
The changes not reflected inside @update:modelValue. It is showing previous value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUz1v2zAQ/StXLmoBS0ScToIduAjQj6FTi2awPDDi2WZLkQRJyQ4M/fdSlGTLzhIgi3D37njvvSO1PpEvxmRNjSQnC4+VkczjQ6EAFk3KjIlhTEqtPBMK7QBF0OPRp1uBkkOTVpqjXBakcruCAJ32OZRY+hEAkOw5tv7qcXKp5CKocKG0Th6ZFFttlWDJDJJHLbVlXHfx1xAKHuFvqO2u7/iNR+a64OlFV0Ltks108Ko2PHjLo8o/TNbYS50vw+du2nnlZFJ5WNDRycUbF805ATjshUToe4IC8HsEbrXh+qBmMSv3TO3QAbMISnuwuB2bhXKC42VYQQbJP8+SC5LBDw/CgdvrQ3fIWGyErh00sT7KolNdp1NnpG2XMZi37XCpwc71rXZIf+kLOnkMIXWlFaa3jUejrQeOW1ZLD6d+WBDKPn4aMwi+fG3VJQcI1Dkk31FKDU/aSv4hmV1V73JQtZTX4PwGHLS3EQjJgp6lkRkRVactrZjJ/jqtwqOOAoqh4AqSj5IKEl59lxdk771xOaUlV+FY2LVobKbQU2Uqugpt1NbKiwpTrqvVfXaffQ77dX4KZ+iq9Nnqg0MbhhRkUBxpvNi+vIFq6IwMdwPFgKXhj3Edx6vZNBA2aFOLiqNF+1ZLN8emtm5Kr6wNq2/DwqVQ/9zNrksX97weRb7Pc5zWjdp0jO2MRKGBuj9BNv8BYHSIAg==)

**Comment by KaelWD** [comment]
Prop order matters: https://play.vuetifyjs.com/#eNqlUz1v2zAQ/StXLmoBS0ScToIduAjQj6FTi2awPDDi2WZLkQRJyQ4M/fdSlGTLzhIg29274733juT6RL4YkzU1kpwsPFZGMo8PhQJYNCkzJoYxKbXyTCi0AxRBj0efbgVKDk1aaY5yWZDK7QoCdNrnUGLpRwBAsufY+qvHyaWSi6DChdI6eWRSbLVVgiUzSB611JZx3cVfQyh4hL+htru+4zcemeuCpxddCbVLNtPBV/ruppVVbXhwncf6HyZr7Jvmy+vOhwUdnVy8cdGcE4DDXkiEvicoAL9H4FYbrg9qFrNyz9QOHTCLoLQHi9uxWSgnOF6GFWQQ9vMsrCAZ/PAgHLi9PnSHjMVG6NpBE+ujLDrVdTp1Rtp2GYN52w6XGuxc32qH9Je+oJPHEFJXWmF623g02nrguGW19HDqhwWh7OOnMYPgy9dWXXKAQJ1D8h2l1PCkreQfktlV9S4HVUt5Dc5vwEF7G4GQLOhZGpkRUXXa0oqZ7K/TKjzqKKAYCq4g+SipIOHVd3lB9t4bl1NachWOhV2LxmYKPVWmoqvQRm2tvKgw5bpa3Wf32eewX+encIauSp+tPji0YUhBBsWRxovtyxuohs7IcDdQDFgafozrOF7NpoGwQZtaVBwt2rdaujk2tXVTemVtWH0bFi6F+ududl26uOf1KPJ9nuO0btSmY2xnJAoN1P0JsvkPNhKIAg==
