### ISSUE TITLE
[Feature Request] VDatePicker: hide-header prop

### ISSUE THREAD

**Issue by simon-lorenz** [vuetifyjs/vuetify#18120]
### Problem to solve
I'm trying to migrate a v2 component that uses VDatePicker together with VTextField and VMenu like [this](https://v2.vuetifyjs.com/en/components/date-pickers/#dialog-and-menu).

For this I'd like to use the calendar view of VDatePicker as standalone. I can already hide the action buttons with `hide-actions` and use an empty slot for the header, but the "Select date"  caption always stays and using an empty slot isn't very nice.

### Proposed solution
Introduce a new property called `hide-header`, which hides everything above the calendar view.

**Comment by simon-lorenz** [comment]
3.4.0 introduced `hide-header` for `VDatePicker`.

**Comment by vciloglu** [comment]
It should be for the header as well, not just for the title. `hide-title`
