### ISSUE TITLE
[Bug Report][3.3.14] marquee tag is throwing warning message

### ISSUE THREAD

**Issue by sengottaiyans** [vuetifyjs/vuetify#18133]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
1) Add marquee tag
2) open console and you can see below warning
[Vue warn]: Failed to resolve component: marquee
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>

### Expected Behavior
marquee tag should work without warning

### Actual Behavior
marquee tag is working with warning

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkE1OwzAQha9ivClITSxUVlValR0HQGJRd5EmEzD4D3sSQFXuju2kIko3ldh5nmfeN/P2J/pobd61QNe0QFBWlghbrgkpuqy0Nj1TURmNpdDgRimJCN+YNQJkTbpMmRrkhlPlXzkl7K9Ple6zBdg+g8eCnavRmc2tozKQCzbZKJS+csIi8YDtsJhQ1jgkJ+KgIT1pnFFkEY5ZxHZCgq9HEtYhm9hxu3gCKQ15MU7WN4u7CBgsgxld0sEtU6XN373RIZFTdOHjh+d0TZIStUCJNadviNavGatqHcZCAqJzuQZk2iq2C23MtRqFgqw2arfKV/kDq4XHqZyDV9nRmS8PLphwupxgUDQ/V6DGzkS4HxGjlsny6CPjwpsFYAcuc6BrcOCuPWk2Nj1r9nVxWqT3XPchcCn0h59lXfmU8/685P9uTm7R6hCJ/ZKmRQN6mKCHX2aPAcs=)

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/2255
