### ISSUE TITLE
Vee-Validate integration doesn't consistently work with v-checkbox

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1813]
### Steps to reproduce
1. Click Submit, see that all fields report required.
2. Click Clear, see that all fields required errors are cleared.
3. Click Submit, see that all fields except the checkbox report required.

### Versions
Latest

### Reproduction Link
https://codepen.io/jayblanchard/pen/ZXWaEO?editors=1010

**Comment by KaelWD** [comment]
It works if you reset the checkbox to `null` instead of `false`

**Comment by johnleider** [comment]
So is this a process issue with vee-validate, or is there more we can do?

**Comment by johnleider** [comment]
Can confirm this is the fix.
