### ISSUE TITLE
[Bug Report][3.3.14] Loader goes beyond textfield border with outlined variant and rounded prop

### ISSUE THREAD

**Issue by kkolataj** [vuetifyjs/vuetify#18130]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add variant="outlined" and rounded prop to text-field. Add :loading="true"

### Expected Behavior
Loader is trimed by input border.

### Actual Behavior
Loader goes beyond textfield border

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUs1O4zAQfhXL5zpZ1O6l6lbsYW97WGmPhIMTT6nBf7LHaSvUd2ecEggFUchtPs98P5O5eeS/Q6j6DHzJVwg2GImwbhxjq15ESMG7pHtgnZEp/Wq43QuZ0TOL4uoHC1L8bDizci92WuGWGuaLRcPLPGNrotj4aAe68lGNsEex0WDUCDLWy6ilQxr2GY12oEaG8kWfnSLoBVgaL5V2d9SPMcO018gWDOF//Z120wc8BCBcu5DxFV+v6qmjSz5H9n+0ip2Pb1x+LPDtbFs99P5xCJEdfI604pMYo6XLroOUGG51Yjtok8ZJ+k/CtOhGgym3VpND1hrfPaz/D2WZpJ7nkVK9/LZSvJ4BQat6ciV8xinTQ6ruk3d0QY9lpOFdSg1fspsTX8O3iCEt67pTjjoVGN3HygHWLtiabg/15nA9r+bV1aJWOuGICdp4qga2QnXbuCMpaht8RGFlOJM9PQzSA1IwYir1BQ/X1FbH7FBbEMrbwcyzlwlcQbKijX6XIBJJw2cTmWL4C1IX45LGO+6aBHuI9CfoXCLEr0Y6G5vGOnt6F62oH8vCjzM+jNHmT5757RPVdVzT)

**Comment by EDM115** [comment]
+1, this issue is still present as of 3.5.11
