### ISSUE TITLE
[Feature Request] v-select :attach

### ISSUE THREAD

**Issue by Knoty92** [vuetifyjs/vuetify#18135]
### Problem to solve
I wish I could use :attach prop as with the other components (v-menu, v-dialog) that are rendered in body by default. I am using shadow dom and I need all my components to render inside it. Not in body.

### Proposed solution
add :attach prop to v-select so it is consistent with the other components  (v-menu, v-dialog) that are rendered in body .v-overlay-container by default

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-select/#props-menu-props
