### ISSUE TITLE
[Bug Report][3.3.14]  V-Stepper will cause build-error if using 'prev' and 'next' provided in default slot.(TS build error)

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#18131]
### Environment
**Vuetify Version:** 3.3.14
**Last working version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
1.v-slot:default="{ prev, next }"
2. npm run build.(TS: type-check fail.)

### Expected Behavior
Build pass - beacause of type-check

### Actual Behavior
Build Fail

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVdtu2zAM/RVOG9AN8KVpuz0YSdd9wx7rAnVsptFqy4akuC0C//so2XEk20X7ZImkziEPRfn+yP40TdQekCVsrbFqykzjbSoA1gVv7YKWbZhnsoC8zJTapKzahjcpG5yjO9T4qkejNSssMddnE0AbVnWBJYEojY1KmetMOGVgCO6vArgO4CaAnwH8evCjymxrAb5CvYMZyu06PvGeEyTTNMOTjbZjkQasQekkiSu3zpM+FKDKWicF7rJDqSnuCI3ENgBBBNA5Z1zccI9ZgdLx+Zi7WhKUAC5OZUHyjG9ke/x2FJ2FefSwJ/hGPt9JmuY1EaBGWw3cgvDVtDEGwND8pS8cjyCg64hpFtdm5cEALWBgwXW2LdG3991w0hvldtKni8ZJF1KA76wAXzabqQLEaLGGWF/D2Lu4557PdF/sygsXRf3iI069C9Iu9cuP8JqX10Kj0DNV39N03uV+BOvSsj5JfAtL/rQn0JAuKezRbMhzdXk5aDVcb1eoxbreUW3UZVG1LNe8Fsob34IrcwUoiWHll3SXlzx/TsykUIj5LPrNDBk96DMfbJ/dmfDJFXCC+9cs7p8zL5C2Kpe86d8EfG1qqWEYajj2QEWms+8/TjsAifogxXlP51YJrILz3t6FBK5GU9cvOjL0KzOSB41FcoYZBHOZRi695yqi2d3QWKxcwX7DhVHxwmuCF27X/eX0zxl1J+cOgkrnAosx76GC/ktVrONRLhawkotnFf1TtaB/h806ZbmiKUjgvj+Ysr3WpEUc54WgSHpTeSsjgToWTRXTX0fz3dvddXQdrW6oQUqfbCE98iqyaAbqIRUdMfLKdCissmZC2zss9SBfygjJ7D/I4Y7CYnkQmlcYFnVlkxlyccwRqircyvpFoSSQlA3SWBqT8CeoPiyXOGbYMRG2dOElUnckys+WNDnmljVxzUobmt2xLmD2GCnf58we/gOhfnDb)

**Comment by velly** [comment]
Property 'next'/'prev' doesn't exist on type 'SteppterItem'.

**Comment by velly** [comment]
> vue-starter@0.0.1 build
> run-p type-check build-only


> vue-starter@0.0.1 type-check
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false


> vue-starter@0.0.1 build-only
> vite build

command build
env: { VITE_APP_STATIC_ROOT: '/static/' }
vite v4.2.1 building for production...
transforming (2857) node_modules\lodash-es\zipWith.jssrc/views/pages/admin/NotificationSendingPage.vue:11:37 - error TS2339: Property 'prev' does not exist on type 'StepperItem'.

11         <template v-slot:default="{ prev, next }">
                                                         ~~~~

src/views/pages/admin/NotificationSendingPage.vue:11:43 - error TS2339: Property 'next' does not exist on type 'StepperItem'.

11         <template v-slot:default="{ prev, next }">
                                                                  ~~~~


Found 2 errors in the same file, starting at: src/views/pages/NotificationPage.vue:11

transforming (2879) node_modules\ace-builds\src-noconflict\theme-twilight.jsERROR: "type-check" exited with 2.

**Comment by velly** [comment]
I find get VStepper instance by ref.

**Comment by crystalfp** [comment]
Well, the issue is still here in 3.7.6
