### ISSUE TITLE
[Bug Report][3.3.14] useLocale does not work

### ISSUE THREAD

**Issue by ELigoP** [vuetifyjs/vuetify#18140]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Firefox 110.0
**OS:** Kubuntu (Ubuntu 22.04.1)

### Steps to reproduce
1. Create `vuetify.ts` file as in reproductuion link
2. Create `App.vue` as in reproduction link
3. Run with `npm run dev` and open the page

### Expected Behavior
Expecting to get `Sveikas, pasauly!` in the rendered app window.

### Actual Behavior
Seeing `helloWorld` instead in my app, and `[Vuetify] Could not find injected locale instance` error in Vuetify playground.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU0tv2kAQ/itbXxwQ9qpKT5REVJWqHnojag9xpC72ABv2pd21U4T83zu7Xh6BVooUDsDMfI+Z8fhxn3UteL7alc8um2Z0PK4UGRMj2jVXjh6K3oV0LH2zTMKLtlvS6LqVoDzzXKsp2Xhv3JQeOM+urLX8HTi0UpWilCz8TgAq4V8ujbaegCIrqyXJ5xRUfl4R/lgRHiux9lVj0bFlVEnAPaktMA8/B1vSJ15qI1LhT4Q2sGItCr8i3OyxReI3IGGKYgnzMMS54OuNz0k/CSChayYCKgSnMMcGY52QFRNiyeotJnGelJTgHFuDOxIJzn0WELIBIfQvbUWDxO8hILhh0Xw4SISPC4t2ntcolC+OwQkyNBk78/+XX3TAt8xNiGEOJ9298lDgw6NF2ANXW8H+oT78hu9+VKlskn0xpsRl4/XMPEgjcLX3ATLrCmZM/BuDWuOpcAU2pTDZ8O5+vyf+Jj+1mI9I389oKCUqveSGzCA9o2eWGLracuOJA98aIpha31UZ3m4WaceDaR38iM/u6lg+BxyauQDzWL47gW9GWJ3RwQIFcfRBsZDM4OujFa4gbr1KBTQ+PocqvGghrrLDi1I3CmkNCN7ZEjdPlZF0jjBqW+W5hKLRcn5b3pafcB3On6dLcLJYWv3iwKJIlaWnE23CKG+wSsjo8DFZpFwh2NIFjyttioYd2MKCasCCfetIF7TzsS5KV6PFe8Nzw4ULvEp3sevaxT0/Hpp838xRLUg9Bcd+ksVG0XpgZE9/AbfguGs=)

**Comment by KaelWD** [comment]
It was made for stuff like `no-data-text` in vuetify component so only looks up keys starting with `$vuetify.`, anything else is passed through: https://vuetifyjs.com/en/features/internationalization/#custom-vuetify-components

Suggest using vue-i18n if you need anything more than very basic string substitution.

**Comment by ELigoP** [comment]
Thank you.
I tried to change `messages` format according to to docs:
```
import en from '/vuetify/lib/locale'
import lt from '/vuetify/lib/locale'

// Composables
import { createVuetify } from 'vuetify'

export default createVuetify({
  theme: { defaultTheme: 'light' },
  locale: {
    locale: 'lt',
    fallback: 'en',
    messages: {
      en: {
        $vuetify: {
          helloWorld: 'Hello world!',
          statistics: 'Statistics',
          ...en,
        },
      },
      lt: {
        $vuetify: {
          helloWorld: 'Sveikas, pasauly!',
          network: 'Tinklas',
          ...lt,
        },
      },
    },
  },
})
  ```
  and try to get translation in the template
  ```
  <script setup lang="ts">
  import { useLocale } from 'vuetify';
  const { t } = useLocale();
</script>

<template>
  <v-app>
    <v-container>
      <div>{{ t('$vuetify.hello-world') }}</div>
      <div>{{ t('$vuetify.helloWorld') }}</div>
      <div>{{ t('hello-world') }}</div>
      <div>{{ t('helloWorld') }}</div>
    </v-container>
  </v-app>
</template>
  ```
  but for no better result either in the app or in the Vuetify playground.
