### ISSUE TITLE
[Bug Report][3.3.14] Text field type time does not work in Safari

### ISSUE THREAD

**Issue by grolu** [vuetifyjs/vuetify#18147]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a text field of type `time` try to input data in Safari Browser.

### Expected Behavior
The selected time should be synced to the v-model prop.

### Actual Behavior
There is an initial time visible even if the v-model prop is undefined. Changing the time does not have any effect on the v-model property. Clearing the value is also not possible.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUs1u4yAQfhXEqZWC0So5WWnUfYbdW+mBmInCLmAEYzdV5HffATtbKz20J5tvmO9nhpcr/xljMw7AW75H8NFphIMKjO1HkSDHPmQ7AuuczvlJcX8ResBeceb1RbxZg2dCt7ud4rWr9iFcUJwsODNDjI3C9wZcIShfxW+FzoFO+ujgBpytAWEAtXVFbxa7FZ0+VpLf1sMHiu8RCMQVeNjLtY05EEEfiWYoRx0Ov8BBh2BYYWjZ9Vo9TtNe1rIKe7maDB1zl2zEygCX2CdkBk56cMius7zRqFv28MieDuxhwRirtC0bAt22AcxmLkyP9WcqOv+Z+YY7G/7m5k/uA+2mkije5ax4y17mTsXPiDG3UnYm0E2it2NqAqAM0UvaKtrT+/O22TY/dtLYjDdM0CRzU9kK1asKEylaX8IIr+Od7Fyo0ksaxYmpnL/w8EzXZBpCGa0wva9mFi8ruIHsxTH1bxkSkSi+zKbKFMPfkPoyLml84pYkOEKih0FbSZC+G+mubR3rrvQp2rLsiU8bXtto8rNn/voPKuEueQ==)

### Other comments
This issue also exists in vuetify 2.x
Works with Chrome Browser.

**Comment by KaelWD** [comment]
https://bugs.webkit.org/show_bug.cgi?id=233215
