### ISSUE TITLE
Floating Action Button z-index should be higher

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1814]
MD doesn't specify a specific z-index, but I often see 998 or 1000 being used.

### Steps to reproduce
Load codepen

### Versions
Latest

### What is expected ?
Floating action button should appear over the progress bar

### What is actually happening ?
Floating action button appears under the progress bar

### Reproduction Link
https://codepen.io/jayblanchard/pen/oGxoya?editors=1010

**Comment by lucafaggianelli** [comment]
The same bug still applies for speed-dials, tested on vuetify 0.17.6:
https://codepen.io/lucafaggianelli/pen/JpYwBb?editors=1010
