### ISSUE TITLE
[Bug Report][3.3.13] Failed to resolve component: v-stepper-item

### ISSUE THREAD

**Issue by chan-ny** [vuetifyjs/vuetify#18145]
### Environment
**Vuetify Version:** 3.3.13
**Last working version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
<v-stepper model-value="2">
      <v-stepper-header>
        <v-stepper-item
          complete
          title="Select campaign settings"
          value="1"
        ></v-stepper-item>

        <v-divider></v-divider>

        <v-stepper-item title="Create an ad group" value="2"></v-stepper-item>

        <v-divider></v-divider>

        <v-stepper-item title="Create an ad" value="3"></v-stepper-item>
      </v-stepper-header>
    </v-stepper>

### Expected Behavior
      "<v-stepper-item
        complete
        title="Select campaign settings"
        value="1"
      ></v-stepper-item>" to complete 

### Actual Behavior
Failed to resolve component: v-stepper-item
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9UstuwjAQ/BXLZxKL0hNKEVU/oUfMwSRbcBs7lr1JVSH+veukKeahwqk3ezyemX2s9vzZubxrgc95gWBcrRAW0jJWdFlAcA48M00FddapuoUnyR8k7wkpJduBqsD/4CcvmlRHmLGyIQtAOCKosY6yr1BDiaxUxim9tSwAorbbIPmRO0aYHsFFIU69KEOSotKdjsEiazyfEK7HHEO9eKB+MGWZqtjWN627Foc68v9xrgWZ/R2k90jgZGgJTPdC/K4Cn/Ba24+Qv4fG0pLsI1vyMtBg5mw1iEq+Q3RhLkRZWWLSuujO5xZQWGcErRfqt6/lLJ/l05modMARy2q1CXmvFqXW0h7IURvXeMyMcme2w0Nv3SMRI6V4v5FhSTThW4vaQFY1pg/zOGRJ4ByCyTa++QzgSUTySWITA99hdbNc8rjQFmTY0Uw8WJoJ+HtLOvuWlnX2dFFadD/Ehh8mvP9GnR8y8/U3p9NTuA==)

### Other comments
Can you fix issues ?

**Comment by wambling** [comment]
As per the [documentation](https://vuetifyjs.com/en/components/steppers/#installation) Labs components require a manual import and installation of the component. So you can do something like this and should work:
`export default createVuetify({
  components: {
    VStepperActions,
    VStepperHeader,
    VStepperItem,
    VStepperWindow,
    VStepperWindowItem
  },
... rest of your code
});
`

**Comment by egeersoz** [comment]
I have the same issue as the OP, and I've confirmed that the Labs component is being imported correctly.

**Comment by nekosaur** [comment]
We need a proper reproduction to be able to move forward with this issue.

**Comment by joelvegab10** [comment]
Had the same issue, I've resolved it adding the component manually:

```js
import { VStepperVertical, VStepperVerticalItem } from 'vuetify/labs/VStepperVertical'
[...]
export default createVuetify({
  components: {
    VStepperVertical,
    VStepperVerticalItem,
[...]
```
