### ISSUE TITLE
[Bug Report][3.3.14] Timeline's line is broken when horizental and truncated.

### ISSUE THREAD

**Issue by thenewseason** [vuetifyjs/vuetify#18149]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. set a v-timeline direction="horizontal" truncate-line="both".

### Expected Behavior
1. line is not broken
2. left/right side dots go inside about the length of line truncated.

### Actual Behavior
1. line is broken
2. left/right side dots are widen to each end of side.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNUctuwjAQ/BXLl15wrIqeUIrod2AOIVmE2/ghewmiKP/etROqEC5IvfSUeHZ3Zmd2e+Uf3hfdCfiKlwjGtxXCWlnGyk5U3uff/KidxUpbCCOUQdQGWgJZowPUqJ19V/zogv5O3a3iDMPJ1sQpUhsV9w6Piv9y3LEITRusSzlH/lnztHLLh6D7gBIy5FfKSa70jHXQHlkEPA3xauNdQHZlAQ4Ldq6wPrKeHYIz7IUu85IohqHEFvHSAm03fJXlCz4QCFP54jM6S6e8Jl41FqLiK5aRhBFjetOZEH1cSVk3lsYastOFwgJK643cUJuk0yWfonFmsyyWxZtsdMQpXEA0Yh/cOUIgEsUXExnUh8sTUmNnVngdJUZMtNU+Jo0HbkmCHQQRwDYQIDxraTY2tTUrPVhL6r2yPQVOl/+Ks6zrmHPe3pb8m+fMlqh2SbFf8LwoSQ8TfPcDcD1ATA==)

### Other comments
This is not happened on Vuetify 3.2.2.

**Comment by KaelWD** [comment]
Broken by #17923 and not fixed by #18022
