### ISSUE TITLE
[Feature Request] v-toolbar-menu and v-navigation-subdrawer

### ISSUE THREAD

**Issue by snarlynarwhal** [vuetifyjs/vuetify#1815]
I would really like to see:

1) A toolbar menu that felt more cohesive with the toolbar than the a regular menu:

![toolbar-menu](https://user-images.githubusercontent.com/3300071/30626269-b65cf624-9d96-11e7-9162-e0b22bf99fd0.PNG)

2) A secondary navigation drawer that pops up to the right of the primary nav:

![secondary-nav](https://user-images.githubusercontent.com/3300071/30626317-f60dd586-9d96-11e7-9c6c-4f51dbd8d4c5.png)

I was able to accomplish this by using existing Vuetify components w/ custom CSS and basic JavaScript, but really think it would be nice to have it build in.

**Comment by johnleider** [comment]
You can already do both of these things, so I'm a bit confused.

**Comment by johnleider** [comment]
Going to close this until further information is provided, all of this functionality already exists within the framework.

**Comment by guardiandesecretos** [comment]
@johnleider @snarlynarwhal : could you spell out how exactly to accomplish the first function, where the v-menu content is nicely aligned with the bottom border of the v-toolbar?

**Comment by guardiandesecretos** [comment]
@johnleider : could you spell out how exactly to accomplish the first function, where the v-menu content is nicely aligned with the bottom border of the v-toolbar?

**Comment by guardiandesecretos** [comment]
@johnleider : could you please spell out how exactly to accomplish the first function, where the v-menu content is nicely aligned with the bottom border of the v-toolbar, or at least provide some pointers? Thanks for any help you can provide.

**Comment by snarlynarwhal** [comment]
I haven't used Vuetify in some time so not sure if anything has changed, but I just used css to accomplish this since I did not find a built in way to do so.

**Comment by guardiandesecretos** [comment]
The offset-y prop of v-menu accomplishes feature #1 above. See:
https://vuetifyjs.com/en/components/menus#usage
Moreover, v-menu's content aligns with v-toolbar bottom border even as screen size or orientation is changed.

**Comment by blalan05** [comment]
The issue list of this repo is exclusively for bug reports and feature requests. For general questions, please join the Discord chat room. You can also check reddit or stackoverflow.
