### ISSUE TITLE
[Bug Report][3.3.14] Datepicker min property not working when it nested in menu

### ISSUE THREAD

**Issue by Ariex** [vuetifyjs/vuetify#18158]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Edge 116.0.1938.54
**OS:** Windows 10

### Steps to reproduce
1. create a date picker, with min property set as today, it works all good
2. create a menu with textfield as activator, move the date picker inside the menu, so it becomes popup content when textfield clicked
3. click the text field, it report error because min property expect number
4. change min property value to number by calling `getTime()`
5. click the text field, date picker appears, but no min date at all

### Expected Behavior
datepicker should works in the same way wherever it been used

### Actual Behavior
date picker behave different when it inside of menu

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVMFO3DAQ/RXLvVAJJ7RwaQSISv2A3gmHEE9YF2ds2ZMARfvvndjJbtgtgj2t37yZee/Fye2r/Ol9MQ4gK3lJ0HvbEFzXKMTlqHrAYforRIDuqpbpLDPCVafBHqBVa10E5VC1DgmQVGtN+8isrrERdjQc9AOoYB42xLWLs10hAA0B1djYAYr4gi2XNUtaCLb5+5L/UWgwGjIOmRLbxoLaQwvddV0EUnNLN1irnoymTT73BvORJ3z/ceafc1uyzwEscbDXaB1VTUtmbMgFpr8KH5yPYlvLmZ4SI3gm1RmwegHXSa2NZDP3Cf/NEUEQBsU6y+nnA3hArQzHyUQYOdJ1PUCjHdrZX952b1AzN+nbc68vy7W8xWP55pknD5NK5ZOkpfk9C+gUGbKwnGMbnGVXe2RjNKgpOIdxwSrOnUchPIlfPO7k6zJwn+Qu+i8bdgiB1R8KZTsrpfnKMjYluNzfIyf/9/HWxaGHYwfv6D+6Nu9oP1b+hsBHlmA8JTI8exdIaOiawZJ4zTu4vanEyVdxdS1OZiyhUIm9rNOlMGVSifQGztg2F7fT7t02eSqtwcdY/IkO+XuQBteyjXyNKnGbO2u5IfKxKstWIzM5TjOGAoFK9H3JXxIy3cvNeXFefLsotYm0YIpDjUWaNo26q3HLG00/GVR94w/W5kJaPTusJU+azh9ouGFaGQYk04PSrk9iZi0ruIDYq/vgniIEHlLLOZu0ZhL8iVUf2uUdR7NLXjhCUIHfbAh8Nz9p6aBtbeugdGRtfthbuT2VqY2Tz5rl3T+18/Bd)

### Other comments
As you can see, those are 2 identical date picker, the standalone one works all good with min prop set as a date object, but once it moved inside of menu it won't work, it asking for numbers for min, which is same as version 3.3.11, and even you give it a number it still does not working as before.

**Comment by avarixe** [comment]
Also doesn't work for VDialog, and min as a string: [reproduction link](https://play.vuetifyjs.com/#eNqtkkFPAjEQhf9K05NGukXQxBA0mHDl5JFyWHYHrGy7TVsWDeG/O21FN6CBRI6defPeN22nW/psTNasgQ7o0IMyVe7hSWhChg3z8O7ZQkJVkiqfQ/Uo6AT0mtyQidRkjEpBozaqVWjlhZdN7muLWpNb0P5bEkUlDjEjixVYMlBSo0zDJnpdXQtK+N6PJ8OEgocfFiydxffirdTLfxEmwF6312fdB9a9vwDgWOZVvfwTsUztC0Imx98xh7z15LRDK6lXLntztcbvsA0jghbOCTog0+Qo6Kv3xg04L0qNyhIq2dhMg+faKI4fycvFx6if9bPbO15K5/c1hjfgsugWrGZC7zBRKlNbz1RuDmJTI0bHSqihUzifYBihjNu19lIBK2sVYb5YWuUMnGJzW28cWDQRtNOKCcBnRJ1cFzOOvDkGNmAZvmoJFuy5Kx2Mtdc6aB2tFtJ34cJ3HRrH8OYTM519AhFJT4c=)

odd thing is it works for me in my own repo where I'm pretty much using it in this exact way, but when I tried to reproduce it in the playground, I get the same error.

**Comment by johnleider** [comment]
This is working as expected as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
