### ISSUE TITLE
[Bug Report][3.3.2] v-autocomplete resize when text larger

### ISSUE THREAD

**Issue by HuanVo** [vuetifyjs/vuetify#18159]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.2.37
**Browsers:** Chrome 116.0.0.0
**OS:** Linux x86_64
### Steps to reproduce
Open and scroll autocomplete. dropdowns resized when text larger.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVm1vGkcQ/ivTkyps6d55KUUkCjHYRAVjgd00Cvlw3I3N1ne7192FhFr0t3fuxeYwtZoo+WBF+QDHzDPPvO5y8/7O6KWpvV6h0TG6GpM0DjS+nHOA7toK0jT/mQuh4DpgHGWpypVSfHwQS6sY6KNezI3W3KhghcOVFqGgIKixCgF0GAXPWPlzbuyjmdJaB/EKyeIWN/+Ja6bjDOdBgvsGL7vOfuxqzgRRwruiSN5VVaDVwnNXeV+6TqVfJKpQslSDQr0q2saSVEgNdyDxGrZwLUUCNWp1LTMHahNXGhJ1Ay8yi6PaEONYwFsh4+in2vHOJG9JafS+yOsOqAsdqJ0PLt9Opr/VTMiqJsXZbAwODGcXPXqMLgf03Tyrwdbc5416V+cnwx3Nd33fhEmoxQIleO1DxutJ/13Fvu3aLfgEvtewf6Vny25AksCR59luk+S23chg1/abwPhx4W7f4cWod3k6mY53TtlFEE1m4LVsz4RVeiODKFjECFrADmpVUrufWeFwPBhPppTjvbb06vnts9eQfaa9sQl+s1UVm56/E++5j2ufTa7O+7s836Ey4SPTS1AaJQpQKQa3KBUcNR5+lzVX3ZxMxuPZF4/qdNC7vJoOKsTTIER40zchCEOMkY4VHWl5yHxeh+PJufXfzOgsHA5uxP5asQimqBkP4I/+FBLGmTUa9GF0QtV7vjv824Rhf+q5JvRFvNjA70wxwQlzXRc40zQSvUmPSdF6UGQDOraJTskxHi6zaTa9pl2HMPHh6J920278DHSbEbmlhbUQ0QZkoJkglu822llpv9R9SNknjInc6NQLnMh+qwlpyiBCrpjeEGMWEhYuLYmKKR1wDTdxoIgmYhTpUixYSPec6PzmqfP3DK+K+bV35cf1ePJ6/PiD/EYn4LnPHL78vfhNh/tdvO8+0KbUdYrli9YuwzSKvctKgtT+UwlOm23eK9otc4C2y8599+YG7WOZPDeWWqeq4zhhxIkWYczW0uaoHZ4mzisyc+SKa5agFYnkVd2u2w0non/0qtpGlVgLWh8VSnIyN8ra8jCaXdPi+r+hSss8gleGKHVWHCxUFuPAt0MB1yjpJcMjGpH83JIe0aplPYIOSsuib+d8Sw2PGb9Vj3odqrzP5b76tTXn3vJpZxG3ppEnSqELhvHhX9HopUk=)

**Comment by yuwu9145** [comment]
duplicates #17751
