### ISSUE TITLE
[Bug Report][3.3.14] v-dialog @update:model-value

### ISSUE THREAD

**Issue by viT-1** [vuetifyjs/vuetify#18161]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
1) Try to update text-field > console writes "onUpdate ..."
2) Open Dialog, close dialog

### Expected Behavior
v-dialog should be handled with message "onUpdate..."

### Actual Behavior
Only watcher "Dialog closed" is working

### Reproduction Link
[https://codepen.io/viT-1/pen/zYyrzVY](https://codepen.io/viT-1/pen/zYyrzVY)

**Comment by KaelWD** [comment]
FooComponent does not return onUpdate from setup. You will see this if you use the dev build of vue instead: 
![Screenshot_20230828_224157](https://github.com/vuetifyjs/vuetify/assets/16421948/a62a87cc-5cf8-4a02-9998-47a7fd4b9955)

**Comment by viT-1** [comment]
> 

Sorry. Fixed. But also not handled

**Comment by KaelWD** [comment]
![Screenshot_20230828_234054](https://github.com/vuetifyjs/vuetify/assets/16421948/b11e83f3-dae4-4c01-87d0-f824a5fd7a35)

**Comment by viT-1** [comment]
Yes, my misconception. For triggering emit "update:modelValue" I should press "Esc" or "click outside", not changing v-model by v-dialog parent component.
