### ISSUE TITLE
Menu popup doesn't close on tab if activating with button

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1817]
### Steps to reproduce
1. Click Menu Button 1
2. Hit Tab and notice the menu is still open

Behavior if you activate the menu with space and then tab is correct.

### Versions
Latest

### What is expected ?
Tabbing away from the menu should close it

### What is actually happening ?
Tab after click doesn't cause the menu to close

### Reproduction Link
https://codepen.io/jayblanchard/pen/mBPpdd?editors=1010

**Comment by jacekkarczmarczyk** [comment]
Arrows don't work as well (when opened with mouse click)
