### ISSUE TITLE
[Bug Report][3.3.14] TextField validation changes on blur

### ISSUE THREAD

**Issue by danbaechtold** [vuetifyjs/vuetify#18170]
### Environment
**Vuetify Version:** 3.3.14
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
Enter this IBAN: CH81 0900 0000 1526 4361 1. It will show a validation error. Leave field (blur), it will validate. Enter field and leave again, it will toggle between valid and not valid.

### Expected Behavior
It should validate.

### Actual Behavior
It goes from valid to invalid and back.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUM1u2zAMfhVOGOAEiKxi7WVG0nbYZQP2BlEGuDGTabNkQVK0tonfvZScNEZ6KdCDAPEj+f1wuWffrC3jDlnF5gG1beuAt9IAzCOvrc3fXKw7E2pl0B2hDAZ8DHyjsG1OIEDkumuwXUim/Vayc6NyuxY94csIi1v4FOFwAIfbMqAPkzhNZaFMrFvVFKvzpjiZEJcuEjKYnIuReSr92ikbwGPYDRmUtp0LsCfBDfSwcZ2GgnIXaRyAeH1IZmAB4vfkrvr+4/Dr53RZ8+cr/nW1/9JPpPR3r/VNP6U3hj6LrdJnKspOVCQ2KYpp8jc4Ii9sxgYzXNe2/Os7Q7ffp015bHjJKshIwshkqiX7E4L1lRDrxtAanVhFVxoMwlgt7mlMuJ0JSiNvOn1/XV6XN6JRPozhEr3mD67779ERiWSzkUxQm6d3SB0ns8LVoHCEeFs/+CTxhlqQXkTHHZoGHbr3JrpYG6e6aL1JltR7aXq6d6vMP39x6rXPZ16eTH4ociZLTKsk2M9Y9knKeYGtXgBXCB6O)

### Other comments
This is the regexp in use: /^(?:CH|LI)[a-z0-9]{2}(\s?[a-z0-9]{4}){4}\s?[a-z0-9]$/gim

With a simpler regexp, the problem does not occur (for example validate 4-digit postcode with: /^\d{4}$/).

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex#avoiding_side_effects
