### ISSUE TITLE
time pickers opens minutes dialog instead of hours

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1818]
### Steps to reproduce

Open time picker, select hour, select minute, blur input (not necessary), open picker again
I remember that this bug was reported (and fixed?) before, but cant' find it

### Versions
0.15.7 / dev - note that in codepen time is not displayed in the v-text-field (it's fixed on dev), but this bug still can be reproduced on dev

### What is expected ?
Picker should open with hour dialog

### What is actually happening ?
Picker opens with minutes dialog

### Reproduction Link
https://codepen.io/vikegart/pen/LzNNwe

### Playground.vue
```
<template>
  <v-app>
    <v-content>
      <v-menu lazy :close-on-content-click="false" offset-y>
        <v-text-field slot="activator" label="Picker in menu" v-model="e6" readonly></v-text-field>
        <v-time-picker v-model="e6" autosave></v-time-picker>
      </v-menu>
    </v-content>
  </v-app>
</template>

<script>
export default {
  data: () => ({ e6: null })
}
</script>
```

**Comment by johnleider** [comment]
I can confirm this bug does not exist in dev (pre 0.16)
