### ISSUE TITLE
[Bug Report][3.3.15] v-textarea and v-text-field variant="outlined" and rounded="xl" does not have the proper left radius

### ISSUE THREAD

**Issue by Gandhi11** [vuetifyjs/vuetify#18186]
### Environment
**Vuetify Version:** 3.3.15
**Last working version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a v-textarea or v-text-field with the variant="outlined", add rounded="xl".

### Expected Behavior
The radius on the left should be like the radius on the right of the textarea

### Actual Behavior
The radius on the left is not like the radius on the right of the textarea

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1P20AQ/SvTvaSVYq8q2ksUKnqp+gOQOGAOSzyBhf3S7NiAovx3ZteJMOGCxM3z3sx782Z9vVN/U2rHAdVKrRl9cobxTxcA1mNjUqqftdjEwMYGpANUQcZnNoTmCAGMjY89uvNO+XzXqTfCmdsKX8oI/LPo+jk7GrImsPBxYCc271iKQ+ixF/bZveH6uJw+3a4g0/JrPQslZd6QTQwZeZiyWZ8iMeyAcAt72FL0sJB7LEo7gOhmBokC56Xj++I/OhfhKpLrvy1+FINJUsTUUk1qjTepfcgxyFF3RaU7ELlTK6hIwcSl1J26Z055pfWmDzIm17MjtQFZh+T1hbRpGgJbj00f/cVZe9b+0r3NPIdbzL65pfiUkUSkU8uZDdvtyyesDp3V4efvyeKANfJ8uXh80NZiOCI1hPJEhPTZSCdj81gn1IdoxX3fhb0cXH6Vx3xy602ud74+Lvm1zFWtSN0Ux/1S1UXFeppQN68PXxL9)

**Comment by mcfarljw** [comment]
Just ran into this today. Here is an example using `v-text-field`:

https://play.vuetifyjs.com/#eNqlUstugzAQ/BXLF1opYFVtL1FSpf/QW8iB4KVxix+yF5oo4t+7BqJQconUGzu7O7MzeHvm785lbQN8yVcI2tUFwltuGFu1aeFc/9kXpTVYKAN+hHoQ4YhppaCWF5CxNtVWQr3OuQ6fOb82iLuEg60leGp+nBywYDXgQZk/c942RoKkmWM9xdvCq8Ig4bbBmk6R1664HCrml0ZkMLISE4NUhtIrhywANoNPpZ31yM7MQ8U6VnmrWULZJHGcMeINyMgUW8eJhyR5jKQDDRHwBR8YUl247CtYQ6Ge42Y+NkLOl6xHIkbMsc75AdGFpRClNLRG2anWZwZQGKfFhsaEbwwqDam0evOcPWcvQqqAUziDoNO9tz8BPJHkfDGRQVWd7pAaJ3uFp9dBYsTSutiHqHHDLUiwBZ96oJ/mwd9rabY2tTVr3ViL6l1uOgqcnsF3mGVdhj7n7eXI/3nu2SLVLip2C94fStLDBt/9AmymE8I=

**Comment by KaelWD** [comment]
:facepalm: Of course `[class^="rounded-"]` only works if rounded is the first/only class applied.
