### ISSUE TITLE
[Bug Report][3.3.14] v-text-field and v-textarea outlined variant active state floating label alignment is off

### ISSUE THREAD

**Issue by Gandhi11** [vuetifyjs/vuetify#18182]
### Environment
**Vuetify Version:** 3.3.14
**Last working version:** 2.7.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a v-text-field or a v-textarea and apply the outlined variant and a label.
When you add text or click in the field, the floating label animate to the top.

### Expected Behavior
The floating label should be aligned with the text in the field

### Actual Behavior
The floating label is not aligned with the text in the field

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstOwzAQ/JXFl4LUxELlVLWoXBAfgMSh6SFttmCIH7I3AVT131k7qQjppRK37OzuzM4464N4cC5vGxRzsSDUri4J7wsDsGiz0rn0mYqdNVQqg76HEkj4RdleYV2dQIA207bCelkIHV4L8duoy22Cn3kJHtPSoNuWXpWGuG8bqlnoT9fbxlQM9YA83SXHh0Wku3shB364DDuvHEFAajpbSjvrCQ7gcQ9H2HurYcJRTOI4APMGAvYAyzhxPXnCurbwYn1dXU1uokBHyWRiKjq2TJcufw/WcJ6HyFL0jVCIOSQkYqwS60K8Ebkwl3JXGV7j2FTrc4MkjdNyxWPSN4aUxqyyejXLZ/mdrFSgIZxj0NnW28+AnkkKMR3IkNp/XyDVTyaF216ixzJ+txA1zrglC7boM4/8Nh79pZZGa0Nbo9aZtah+LMyRA+d/5COMst6FlPP6dOT/PCe2SLWJisepSIeydLchNj8ZwRF1)

### Other comments
The problem occur also when adding the rounded props to the component.

**Comment by KaelWD** [comment]
Caused by #17995

@yuwu9145 I think you were looking at the wrong snapshot, here's the one from your PR: https://percy.io/c458cb73/vuetify/builds/29563128/changed/1639996333

**Comment by Gandhi11** [comment]
It's gonna be weird if there is a mix of rounded and not rounded on the same page. The alignment is not gonna be the same.

**Comment by KaelWD** [comment]
v2 didn't have the same alignment either: https://codepen.io/kaelwd/pen/BavKVby?editors=1010

If you're mixing them in the same form you probably don't have eyes anyway so whatever.
