### ISSUE TITLE
[Feature Request] Add buffer / overscan / pre-loading to v-virtual-scroll

### ISSUE THREAD

**Issue by LemonGraZ** [vuetifyjs/vuetify#18188]
### Problem to solve
Currently the ```<v-virtual-scroll>``` seems to only render the items directly visible to the screen with no pre-loading. This is a problem when the list items contain e.g. images that need some time to get loaded. It creates a non-smooth user experience.

### Proposed solution
Expose a ```buffer``` / ```overload``` / ```preload``` property to define a number of items (or pixel threshold) that should be preloaded and added to them DOM in in both directions to allow for smooth scrolling in both directions.

I consider this an essential part of any virtual scroller component. This is standard in other virtual scroller components like useVirtualList from VueUse or vue-virtual-scroller.

**Comment by KaelWD** [comment]
There is an extra 1/3 of the visible area on each side.

**Comment by LemonGraZ** [comment]
@KaelWD This does not seem to handle items that are larger than the list view very well.

In this case the new section of images get loaded too late (they are already visible)  in both directions. I would assume that increasing the extra area would help here. Or even better if I could simply request for one item extra to be rendered in each direction.

https://play.vuetifyjs.com/#eNq1lNuO2jAQhl9lFLUKqOQAbCs1gj20t5UqteoVQVqTGMjixJFtUhDKu3fsOBCg1e5FyVUyp++fcTyzg/NUln61pU7kTGQislLdxwUA3ZVcKEjpkmyZgoO2AaREkQh6fZjeQ8/aAIIAFFeEAV/CMAQPRuEGspysqISsgOEGJE1UxgvZZhjnrx/f5Jf9z8YVtQj9uNYIQzeCme/7T0KQfW8c9v0N3ctef+7npOydErBiutOintdKlTIKgjJL5Db3yzVXXAajMHwwzOm7A0bWz6fU/uAv3NFtuPABxuGr8PHN4J9eh9/dDP75dfjHm8GHo3/Qa/tWN6Y6LibB8Rrgh6J5yYii5lJMKq/KhNoS5mEMZ6zJjTKMktPY+b54wU4a0de/eD92mvg1zVZrhfEfw7C16RLe0TEMW4/hIrnVAZUnGVeRvZgYezC5A7xpKd1hA45NwaQ0q049R1LtGdUJDSYCV2PKnTtYkGSzEnxbpF854yKytd7DCKZTCOEBXEFTFzBlJSgtXKS0hY805MmSFJAwIvUwFN0pbz1CPYdGItQ1zhZDuimVJ/jvjsGYEm4n2z6Vt+QCax6natvt6/1yPemZxs1PGu0A8Fywhkm89CFRa0a1XfuZLqMsy1c4SJHoOhYbOxCcNxCYDrpdoqXb5iTAk2lPNjj/xTD0/B9D81mMM0C0Xs4eXgr/RfICV7dZnlqTdsjYOa7T2MHdrr9jp70rSVpgWkpZVgm/oCooyjx4xLBAbAuV5dRLef449sf+HeqUqmv2qcy9BfYiqcAisWOvj8GobLl/A8pGIuHODz3CyjXxhw3JujxGFlKjrhABcisqPEHxFAUVb+3sIq3b3YXrqkO7FmqcO8uKjbwYeSLNuGetyP/SuimqK841uB44Ri8qOEt05n8ADBBXQA==

**Comment by KaelWD** [comment]
The image loading in that example is from VImg being lazy by default, add `eager` to start loading as soon as it's mounted. 

The missing section is a bug though, doesn't appear to be fixed by #17813. I guess we don't handle having items taller than the viewport very well.

**Comment by LemonGraZ** [comment]
@KaelWD Thanks for the quick reply! Adding eager helps, as the images seem to realize a lot too late that they have to load now, especially when scrolling upwards (and the beginning of the section = v-row is not visible yet).

But as you mentioned the big problem is the too late loading of the sections. You have a suggestions how to fix that until the handling is improved on your side. Is there a rough timeline when this might get fixed / improved?

**Comment by LemonGraZ** [comment]
I did create a bug report for this: #18198.

Would still appreciate any tips to tackle that problem in the meantime.
