### ISSUE TITLE
 v-select function focus() does not work

### ISSUE THREAD

**Issue by chim666** [vuetifyjs/vuetify#1819]
### Steps to reproduce
1) create v-select with autocomplete
2) call focus()

### Versions
0.15.7

### What is expected ?
keyboard focus into select

### What is actually happening ?
select highlighted, but no focused

### Reproduction Link
https://codepen.io/anon/pen/gGrezV?editors=1010#0

Not work after commit e96ca54317995eaf56eef53cd6724a8bad57b2e2
src/components/VSelect/VSelect.vue
line 369
<img src='https://i.imgur.com/d7TS0fa.png' />

**Comment by KaelWD** [comment]
It's actually after 2d4fa52c3ad44ad3cf373d66d9d3d961b20106cb, when that line was commented out.

**Comment by Flamenco** [comment]
In my use case, the autocomplete is opening on call to focus() but the actual input does not get the focus.

Here is my workaround for this issue.

```js
watch:{
   visible(val) {
                if (val) {
                    this.$nextTick(() => {
                        const input = this.$refs.select.$el.querySelector('input')
                        input.focus()
                    })
                }
            }
}
```

**Comment by johnleider** [comment]
@Flamenco could you stop in the community so I can have a look at your issue on the v1.1 refactor, https://community.vuetifyjs.com

**Comment by Flamenco** [comment]
@johnleider https://codepen.io/anon/pen/erEPop

**Comment by Flamenco** [comment]
@johnleider Do you need for me to open a new bug for that issue, or are we all set with re-opening this one?

**Comment by johnleider** [comment]
I want to see the behavior on v1.1 first. I'll let you know

**Comment by NikoNagy** [comment]
Update for V1.1 :

Focus is done on input but select list does not show anymore on V1.1

See @Flamenco CodePen for repro

**Comment by Yong-L** [comment]
Currently on V1.5.

As mentioned by @NikoNagy, the select list isn't shown. Is there an update on this problem?

**Comment by Yong-L** [comment]
I found a workaround where you have to invoke activateMenu().

```javascript
  watch: {
    visible(val) {
      if (val) {
        this.$refs.visible.focus();
        this.$refs.visible.activateMenu()
      }
    }
  },

```

**Comment by KaelWD** [comment]
That isn't a bug, you have to call `activateMenu` to open the menu.
