### ISSUE TITLE
[Bug Report][3.3.15] v-virtual-scroll fails with items larger than viewport

### ISSUE THREAD

**Issue by LemonGraZ** [vuetifyjs/vuetify#18198]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use a ```<v-virtual-scroll>``` component with **items larger than the viewport** of the component (like the provided playground example.

1. Scroll down slowly. After passing the preloaded items, a new item is loaded only after it is already visible for about 1/3 of the viewport. In the provided example this can be seen by the white space (items have red or green background)
![scroll_down](https://github.com/vuetifyjs/vuetify/assets/105200595/3e916591-315b-46a1-b6a1-2a791f90e80e)

2. When scrolling down completely, the last item (in this example 'Section 5') is not loaded at all.

3. Slowly scroll up again. The previous item at the bottom of the viewport will get unloaded before it leaves the screen. Also in some configurations the complete list then glitches. 
![scroll_up](https://github.com/vuetifyjs/vuetify/assets/105200595/f453bd43-0263-4854-8f6c-de4d956744dd)

Of course this happens with any scroll speed.

### Expected Behavior
Item size beeing larger or smaller than the viewport does not matter and items get loaded / unloaded seemlessly while scrolling without any glitches and white spaces.

### Actual Behavior
**Works** fine for items **smaller** than viewport. 
Does **not work** with items **larger** than the viewport.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VW1v2jAQ/iunaBOgNS9AO2kRrG/qh03TOrXbJ4LUkBhwceLIdlIQ4r/v7CQ0QLtWmsincvfcPc899rmjtSVF5F5mmVPkxPKtgYwEzdTXIAUgy4wLBTGZhjlTsNYxgDhUoQ/tDgy/QruKAbguKK5CBnwKXQ9s6HkLoEk4IxJoCt0FSBIpylNZV5jkn7sf8mp1X6b8mkJ/rSoI3ZYPI8dxLoUIV+2+13EWZCXbnbGThFn7uQA7xkst6mGuVCZ9181oJPPEyeZccen2PO/ccA4/rBG5eXgu7Zy8wNs7Di98gr73Jnn/aOSf3yY/PRr5l7fJz45G3u29wr6p/tqUoU2QDtztGuAPRZKMhYqYpRgUdkGFykNmI4YzVtb6FFFyGFi3k0ecpBR9eMU7gVXi54TO5grxZ55Xx55orOYY6p7WMcOInLUCKGzJuPKrlUTsGjTxCe5YTJYo3apKsCimBfhSrRjRuEkYLWaC52l8zRkXflXxEXowHIIH59ASJG6BD62ZICRtNXthN5mFKUQslHpIRZbKnvcQsS4FwGaDniGkWVLYgj81AiYU8cqx+ivsKRfYc+tWNUxHvxuHDo403bi2rP589Bt7mML9HDJqzai2Gd/RZZTRZAYE6QS6JiLdrSIPLHB3x3DNHM1ZMdIcduCi+/XpubsXCKG7NwjDOxjrBKn102vjlXceJU/xYTZPo9akEzKwto9lYOHLrX8HVr0JUZxiWUwYLYSTEuWmWeJeIMwVeapoQuyYJxd9p++cok6pmmGHyMSe4CySCGwSWNVyGBpFp6t3UFVIw9A9KymqmM3CidQcB71dJCyIsAXBQxREvHekvbLmWHupg9Gqbd+g4YymC7nndSSNz6Na5P/NbLrpVuOSUcmIp1M62yflSUYZEbdZ+d+yedAhY/zpu4kpkZOte9GcRIsX4o8Sl0G7+EsQ40XDcRWKGVFl+ub+Jy50I5nwOGfVpXoleUckZ7nWWMKu8GVB2Q2cUfvN3Feazn7Lm6UiqayH0kKN/wZvbsD1P0Z/losGb89tc2KZ40Y7S9+t8V8GFrJn)

### Other comments
I would consider this a **severe bug** as viewport size may be changed by the user resizing his browser window and thus this case **can occur in basically every application** using ```<v-virtual-scroll>```.

**Comment by yuwu9145** [comment]
I will check if it could be included in #17813

**Comment by yuwu9145** [comment]
`buffer = 1` resolves this issue
