### ISSUE TITLE
[Bug Report][3.3.15] Upgrading vuetify version duplicates code in runtime, leads to crazy bugs

### ISSUE THREAD

**Issue by KazimirPodolski** [vuetifyjs/vuetify#18193]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Playground link will NOT reproduce, but it should reproduce locally. I wasted 2 days of debugging on this and looked at every remotely related issue, so _please_ hear me out.

1. Have an app set up with vuetify 3.3.8, vite, vite plugin and manual method from docs
2. Upgrade vuetify to 3.3.14 (I did `pnpm update -L`, no idea if pnpm/npm/etc is relevant)
3. Now dev build (`pnpm run vite`) has **both** versions and they have **separate global states** (e.g. `stack`). E.g. menus/autocompletes created from dialogs (like in repro link) now render options below dialog's overlay (see screenshot) - dialog overlay z-index is 2400, autocomplete overlay z-index is 2000 instead of 2410 
![image](https://github.com/vuetifyjs/vuetify/assets/6647438/613aaf5a-151f-4605-9dca-7fabda13468b)

When I debug it in Chrome v-dialog's overlay goes to one version of v-overlay, and v-autocomplete's overlay goes to another. And they have **separate `globalStack`**, leading to the latter overlay not knowing about the former, and giving itself z-index 2000.
![image](https://github.com/vuetifyjs/vuetify/assets/6647438/90aac814-407c-48e6-8de7-16e69154542b)

![image](https://github.com/vuetifyjs/vuetify/assets/6647438/35365982-b138-43c0-a8db-2b7248a0400e)

What is to blame in this situation - vuetify, vite plugin, vite, pnpm? What should I have done for this not to happen?

### Expected Behavior
There are only one version of lib code in dev build

### Actual Behavior
There are all cached versions at the same time

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqlUEFuwjAQ/IrlXpNYlPaCKKJv6BFzMPG2uE1sy94EVSh/79oEFOCC1Iul2dmZ8ezmyN+9r/oO+IIvEVrfKISVtIwt+1Ib1bivjDKuVdAjylh16GpHGkBgC0Py+Cb5ZlY8F/Ot5EycpeKiHQfnJPakajS9QhdIefTB+ThIPg3ZoWX0GqtpIy8Q/7F3B5YskzVtXIKuKxB56XDFEYx1MB5ZBOz8ailOkChecNN6F7Bsla++o7N0mmOykyNBH1iwPEkzul3Cku8RfVwIUWtLMg2N6UNlAYX1rVjTmgidRdNCqV27nlfz6kVoE3E6riC25S64Q4RAJpIXkxg0n78PRI2bOWH2eooYZ2WjdjFl3HkLCuwhlAGshgDh0Uo3smmtG+quWkofpB3o4I2xP/Hm1nXMd96cP/m/ztktWW1T4lDw/FGKPin49g/MrQOT)

**Comment by KazimirPodolski** [comment]
Clearing `node_modules` helps, but all of this is still really stupid as I just followed installlation docs of every piece, and nothing said that might happen.

**Comment by KaelWD** [comment]
Sounds entirely like a pnpm problem, we can't do anything about a package manager randomly duplicating things. There are some similar problems reported in pnpm issues, you might just need to run `pnpm dedupe` every time you change something.

**Comment by KazimirPodolski** [comment]
OK thanks, I'll look that direction then.
