### ISSUE TITLE
[Bug Report][3.4.0-alpha.1] VSelect as root element on reusable component doesn't allow to replace modelValue

### ISSUE THREAD

**Issue by rbastiansch** [vuetifyjs/vuetify#18191]
### Environment
**Vuetify Version:** 3.4.0-alpha.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When creating a component based on VSelect and replacing modelValue on it when it's empty string to null, it's needed due empty string is consider a valid value for VSelect and VAutocomplete, it doesn't work when VSelect is the only root element, it works when wrapped in another element or have siblings element.
Because of that when using label on VSelect is not placed in correct place(as empty value).
It works if passed 'model-value' instead of modelValue though, not sure if this should happens.

### Expected Behavior
Be able to replace modelValue value to null and it works when VSelect is a root element.

### Actual Behavior
Replacing modelValue to null only works when VSelect is wrapped in another element or have siblings.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVk2P0zAQ/SsjCykgNQ4ITlG77J4RHFiJy2YPbuOyZmM7sp3wsep/Z2wnqdtsoQhxYk+JxzPvvZnJjHLzQK7alvYdJyVZOi7bhjl+USmApdHa5ZY3fOOgz6WuebOqyJb12gjHbUWgxKe0aLQOo7ylYevg9RFjIcaitYiASqs8AfU2eBw5Xs3go3nk+KAVeLiJx18PVPd8zdYROe9Z0/G/JXvnASFEQwCEU+zLIikjHu3GiNYFWUK22jjwxbmOdd0aLSGjxd7ke5ElzpjlI/4H1uOQoPW9l/opKB2DjuxTGP8Wwmq+ZV3j4CFmvtGIprhythxNkEhfjKYDKZP1iGuw74ZnzRx7/mIPa7jrjNqfAab+lJBlEypA7E4JN9kVtoZJli3Av9r7+Ca5ERum4JpJHS1G/NCKZbcTyC7VgodlMbWILEgj1L2lX6xWOBFBUEU2Fr8H5IyBFblzrrVlUWxqhZ6Yo+gNVdwVqpUFVtWJ7ffL1/QNfZmzpr1j9FVRC+vGqxyVWxpAPeJtpXZIHJuXS9YesceLoGAoUEUQyZ9/I+US3QrTKSckz2stUROqiloSM+VW5mujv1puEKQiQ6kCjRd8BtW5WSPVjKJA3p6b3HBVc8PNuZkdhaXZHV3NMhxa7+t+OEfzNdjvd+BaqBp3gX8I9RlhLpbFeP3ryT89Yp3jdTJgI3Y6Hd5RWYyK+ycO9Q5W4O6Epc+Yc8Z6wtF7Pk0AlNLEOxkoSEDLlGC1WuHowVtQXdNAepVED7O0n+wTUzXbV/M616IPL39UcnTGhvvAp+KfLP4je/8//Myz5G8g+1fF3i1I2EJY9YNNSG5/Ag9rDCY=)

### Other comments
If it's a desired behavior, would be nice to understand better why this happens and what's the best approach to make it works.

**Comment by KaelWD** [comment]
https://vuejs.org/api/options-misc.html#inheritattrs

**Comment by rbastiansch** [comment]
Thanks mate, completely forgot about this option.
