### ISSUE TITLE
[Bug Report][3.3.15] v-field in v-text-field is getting white color style after update to 3.3.15

### ISSUE THREAD

**Issue by devonik** [vuetifyjs/vuetify#18209]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Update vuetify version from 3.3.8 to 3.3.15 occurs that every text input color will be white

### Expected Behavior
The color should be the same as in version 3.3.8 - black

### Actual Behavior
Every text input color is white and not readable

### Reproduction Link
[https://stackblitz.com/edit/github-wudebh?file=app.vue,plugins%2Fvuetify.ts,nuxt.config.ts,package.json](https://stackblitz.com/edit/github-wudebh?file=app.vue,plugins%2Fvuetify.ts,nuxt.config.ts,package.json)

### Other comments
Opened a nuxt ticket before (https://github.com/nuxt/nuxt/issues/22944). But it seems to be an vuetify issue. At the moment I am using nuxt 3.7.0 with vuetify 3.3.8 and it works

**Comment by KaelWD** [comment]
41aedfe3e41a212a63b4503c545def164697b639

You have set the background color to black `rgba(0, 0, 0, .04)` so the automatic foreground color is white.

**Comment by devonik** [comment]
So the problem is that now the v-field withing the v-text-field is getting style="color: white" because my bgColor is black rgba(0, 0, 0, .04)

A bit hacky workaround but that was the only way - may someone is interesting in
I add a custom class to the global configuartion VTextField 
class: 'v-text-field__field--color-unset'
```
.v-text-field__field--color-unset{
  .v-field{
    color: unset !important
  }
}
```
