### ISSUE TITLE
[Feature Request] Cannot customize Next/Previous buttons in VStepperActions

### ISSUE THREAD

**Issue by wambling** [vuetifyjs/vuetify#18201]
### Problem to solve
Developers can give their own look and feel to VStepperActions buttons like using icon or using different variants instead of using OOB buttons.

### Proposed solution
Right now only alternative I can see is using is hiding stepper actions and using [VCardAction](https://play.vuetifyjs.com/#eNrNVE2P2jAQ/SuuL2kl4nQXTohF21tvPbRSD4SDSSbg1l+yB7Yt4r93nAANQSrb1R4aKZI9H+/NvExmsecfvBe7LfApnyEYryXCvLSMzXa59L49tpeI4D0ENlUUFh9Kvsg+k4ndZSPWne7Pp3G2LDnbqBpyWaFyNh5xCOlEwghSO2zhxN3Z33JVMtQMFWognhbxkwVCbChxLoSYFV3MH9SiV/vfqe5vUX15cq9ENb5JtQnw/L4ugK6EbT3BPfUMXbDTjN70xSZEJbVa2zyCbsgQUQYs+UVKm7TCc2unR1XOUoqpVS4D8eQaGswrFSpNLQyjidEFCvdBGRl+XgdE9SvJEI3U+tq7k0FJixSA8IMqvPTPk05U4mWrSTun/6X9CixCoP5fkAu2fqlwQa03/7dyydIfpdNcDoYumY9roVsZdO92xuAnmcUqKI8sAm67laKMdwHZngVo2IE1wRmW0RrKun+KJIvITFyzhxTxNvsIWjv21QVdv8neJYIOksD4iHdouZFefIvO0i7bJ5Ty6Igln7LWkmzEku4l3yD6OC2KqraUVoNWuyAsYGG9KR4prAhbi8pAXjvzOBZjMSlqFbFvFhBNviKtIgQCKfmoR4Oqoe93k+oYSQwT8T6X2m+kuOuYjq5cy1VMVFcUBfHuIOSB5hFCGubndTZI63c3cF11mNgPpT2Q7lrZ73EgeRVbuRenIl+l9RY0IS4T8WHE23qpgotEvvwNOZkTqw==)
The way we can customize VCardActions buttons, can the same provision be given in VStepperActions?

**Comment by egeersoz** [comment]
This works for me:

```
<template v-slot:actions>
  <v-card-actions>
    ...stuff
  </v-card-actions>
</template>

**Comment by wambling** [comment]
Can be customized with slots as mentioned by egeersoz.
