### ISSUE TITLE
[Bug Report][3.3.14] Size of icons does not work when using material-design-icons-iconfont

### ISSUE THREAD

**Issue by DerZade** [vuetifyjs/vuetify#18204]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Install material-design-icons (does not matter if via script tag or from npm)
2. Use a icon with a size other than default (for example: `<v-icon size="large">home</v-icon>`)

### Expected Behavior
Size prop to work

### Actual Behavior
Size prop does not work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01vEzEQ/SvGly0iuxYqXKKklBscOIHgUPfg7M5uDP6S7QRKlP/O2N5E26WqWvUS7YzfvDfzZnJzoPsdRNnfNT8DXVKpnfWRHEjrQUT4Xt7IkfTealKN2IqbM1AoKQKEBdHdHMZka02AGJjusIQb+JOLUjaSEUTW97UuDtwQkiuXJH8T0kEvdip+hbgkFXItSvokXaIkhBW5j5wqv3ELGlJ+JPlW4krJYRurDDq+5oYu6EfnGmwKXVhF0E5hT1eJYbWvhXP5MwepNxLkX1hzGrRQitOrrdWwYuXtPvKRpxOJEn6Ah0hSUKRXbNIShqH10sU08650dt6Hh366h+w7GS3XYUC7EXFRfQKlLPlhvepeVTj/ihVKJEMrCluthcOzsAYtyZvg40Pg9Lwbng4oxZxuY3RhyVjbGSzrQMm9bwxEZpxm1whjfmei1FB3Vl9fNpfNO9bJEKfpBoKuN97+DuCRhNNxu1km3ccTpEZkVnj7vkiMuVqJTUgaD3JPD/b5OkpupgSNnkswnGkPvvZgOvDgn+rarGzq3OzpP/fy/wAvHHeqpPkVZutsQ17lzanJl9ma2c4Dn7h6a2JoBmsHBcJJhFnNEPqhF1qqu/UXPGovhXrzOXlXWr5NLR8XNE+KvRdJevsPZsuX6g==)

### Other comments
![](https://i.imgur.com/gFzFfT4.png)

Seems like `.material-icons` has a higher specificity than `.v-icon--size-small` (and all other classes from vuetify)

**Comment by DerZade** [comment]
For anyone running into similar issues, here is my **workaround**:

Instead of importing the css from `material-design-icons-iconfont` directly, I imported a local css file. Said local CSS file imports the `material-design-icons-iconfont` in a [cascade layer](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers#creating_cascade_layers). This works since unlayered styles (vuetfiy styles) always have a higher specificity than layered styles.

```patch
- import 'material-design-icons-iconfont/dist/material-design-icons.css';
+ import './material-design-icons.css';
```

```css
/* material-design-icons.css */
@import url('material-design-icons-iconfont/dist/material-design-icons.css') layer(material-icons);
```

If you're worried about browser support, there is a [PostCSS plugin](https://www.npmjs.com/package/@csstools/postcss-cascade-layers) to help with that.

**Comment by frankmichel** [comment]
Not 100% related, but it also looks like .v-table is overwriting icon sizes:

![Bildschirmfoto 2023-11-23 um 15 16 36](https://github.com/vuetifyjs/vuetify/assets/236225/d95c0444-070c-4d56-8f70-f5f236bf4b46)
![Bildschirmfoto 2023-11-23 um 15 16 54](https://github.com/vuetifyjs/vuetify/assets/236225/6fd71489-ca52-437b-a122-20a8dfefc6b3)

**Comment by KaelWD** [comment]
@frankmichel #18744

@DerZade Load the icon font css first

**Comment by DerZade** [comment]
> @frankmichel #18744
> 
> @DerZade Load the icon font css first

I guess that would fix it but that is not really easily doable when working with a bundler like vite (which seems to be the recommended option to start with vuetify).

How would a user easily do this, when creating a project with Vite?

I run into the same issue when following the vuetify docs step by step:
1. Create a default project using `npm create vuetify` 
2. install Material Icons from npm like it says [in the docs](https://vuetifyjs.com/en/features/icon-fonts/#material-icons-css)

**Comment by WayneDT** [comment]
I have had to hack a solution to make sure the icons resize. I placed the following in my app style sheet.

```
.v-icon--size-x-small {
  font-size: calc(var(--v-icon-size-multiplier) * 1em) !important;
}

.v-icon--size-small {
  font-size: calc(var(--v-icon-size-multiplier) * 1.25em) !important;
}

.v-icon--size-default {
  font-size: calc(var(--v-icon-size-multiplier) * 1.5em) !important;
}

.v-icon--size-large {
  font-size: calc(var(--v-icon-size-multiplier) * 1.75em) !important;
}

.v-icon--size-large {
  font-size: calc(var(--v-icon-size-multiplier) * 2em) !important;
}
```

**Comment by DerZade** [comment]
@WayneDT Check the first comment for a nice workaround using css cascade layers :)

**Comment by Clickss** [comment]
Since Vuetify 3.4.3, I have the same problem as @frankmichel. I use @mdi/font package and I naver have the problem before.

**Comment by WayneDT** [comment]
> ```diff
> material-design-icons-iconfont
> ```

Yeah tried that, sorry I am using mdi  "@mdi/font/css/materialdesignicons.css" and not "material-design-icons.css" but made no difference.
This only started happening once I upgraded to 3.4.3. and I use the v-data-table extensively.

Forcing the override works for now. I would think if the v-table is overriding the is overriding the sizing that should be fixed.

**Comment by jjoshi-cb** [comment]
This started to happen after upgrading vuetify to 3.4.3
Facing similar issue of icon sizes not updating within the v-datatable
@frankmichel @WayneDT 
As you mentioned, it is the .v-table .v-icon {} which is overriding the icon size
`.v-table .v-icon {
    font-size: 1.5rem;
    height: 1.5rem;
    width: 1.5rem;
}`
This looks like a bug

**Comment by KaelWD** [comment]
That was reverted in .4
