### ISSUE TITLE
[Bug Report][3.3.15] Data Table custom-key-filter won't work with custom-filter undefined

### ISSUE THREAD

**Issue by killkli** [vuetifyjs/vuetify#18203]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Setting custom-key-filter without setting custom-filter, then the custom-key-filter won't work properly.
(See the link provided)
once set custom-filter to a function, the custom-key-filter will work normal.

This should not be so, the custom-key-filter  should be working fine without custom-filter

### Expected Behavior
the custom-key-filter  should be working fine without custom-filter

### Actual Behavior
the custom-key-filte doesn't work without custom-filter

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVm1v2zYQ/iuEgEEOYMnvbmMkQYds2bruw4B+Gup8oKVzwoUiNZJy6wb+7z1RlCrZYp2g36R7fe65I3mfnoNf8zzeFRCsgisDWc6pgZu1IORqF6XU0MjQDYdSQMjqEWgKSl+vA/e1DpyGoW8pT0FrUKZRJJzqUg4cdtQwKaJJrUpBaGb2qExkltPE1IoyVvQEpUYDVcljk6X6PZUnhTbS+kRbxg0oNHkOBc0gdLo7K54eKhdbIJZYF0x2kebSrIzMncrWb+CLwYDAUzTIZAq8lZpwurGCj7WgrjWn0Xwd3FyN2hHqlKMuyWjznWUUdfT4qxPFcmNtWZZLZcgzUbAlB7JVMiMhdi4slfDFKlPY0oKjUZVNgynywUX9i+2QQhsUl4jJdRlpEIYXXW2bMLRB9+sbYlThhqDPbFra7SgvYEj+L0Dth7aJ1rPJXTlKDjGXDx3rBkAT+xGSJ5vdmsVGfjSKiYfBRcxEwgucskGfZx3c+be0CplQog5cyw/1h1M/d6oadmsc1rw5r8PQzTH2b+VoGjTV1gdhRT59R9HigpByPFckvFPyKwjyr3wolAldTFcS5VIxwBiTxWVHs6VmRZbx+MhcbdB2Ou9IcyUNMLEi8yNzpiRKJy1ZXZEP6vsESKKAZkRTkX5myaMP73T25hTvZT/eI9MW3tlP4v0dTyRTXozL6SnGiY/ULpYG5LF5BbJd0TmQt0We0CfwoZyNF6coZ3GXMwdy+Som374C5B94+EBtsPepF+hi+XI6591xbpDO4q7C9bwd+RzUv4DzPdkAFV6kb3ooHfcDvfQcpmPzCmhbdg7n35Jzlsvci/KyZzzHcVdYo2z3so2yB2M7wDmMf0oBe3ydNz6Q83E3s5vOXpBvPdO5jLvtqGDO28JzOH+TovDenfNFD5HTRX+/F+37pXOE+gZz+hoyPzDzgXpRLiY9TE49x2fZZaxB2WW4wth/du6bL7fJ+d8pwwy3JFcvGhlMxuMHfAvVDi+Fi249lLMHzBlqQ48fM437SbnkrLA0rqGjw8UNney+5iO0gXHrKAuHTTYQeCu5IDWjocf9jmIFJexeb2Td53hbUv8DV9san/M/VYd+4O566AvwHntJBr/4vMtWt13r9h4u7AduLFejZpUMhgFn4knH/2kpcO+33cYtXOPW3owBrvjG5Ho1GiWpQEtcftlOxQLMSOTZCPdOw7b7d7N4Fk8Wo5RpU8siXIx1bKOVoe7X4oAZq+01ymh+lLZS2NRu7NYBRir/z2B4h2YjVQjDMohSmVkw8wpLSxyDzqKNkp9xZDHIOnDc2DQl4BekOlsu5jiJPSrPCKhIYadA4db5wpKO3NplHalOSnPNPgSHYWDdkPkKc3D/DTI43E4=)

**Comment by killkli** [comment]
https://github.com/vuetifyjs/vuetify/blob/1f3206b1f80db2b4d7973a1a0b0131ad285531ac/packages/vuetify/src/composables/filter.ts#L45
The custom-filter prop should have a default setting, Here there is none, which cause this issue when calling key-filter here:
https://github.com/vuetifyjs/vuetify/blob/1f3206b1f80db2b4d7973a1a0b0131ad285531ac/packages/vuetify/src/composables/filter.ts#L91C41-L91C41

**Comment by KaelWD** [comment]
set `filter-mode="some"`

**Comment by killkli** [comment]
> set `filter-mode="some"`

Yes this would solve the problem, but I still think this is a bug issue since this was cause by the code i mentioned above,
which is that when there is no customfilter set, the function would always return false when a custom-key-filter is set on other keys and which cause intersect mode to return no items at all.
This is not a correct and expected behavoir~

**Comment by KaelWD** [comment]
There is a default here instead of in props for some reason: https://github.com/vuetifyjs/vuetify/blob/1f3206b1f80db2b4d7973a1a0b0131ad285531ac/packages/vuetify/src/composables/filter.ts#L68

Intersection means an item is only matched if the customFilter matches plus at least one other column with the default filter function.
