### ISSUE TITLE
[Feature Request] If v-data-table has pagination disabled, show a simpler footer

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#18217]
### Problem to solve
This feature would allow to easly have a v-data-table with a simpler footer.

### Proposed solution
If pagination is disabled, hide everything related to it and keep only "Items $numberOfItems".

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
