### ISSUE TITLE
[Bug Report][3.3.15] v-date-picker keyboard placeholder doesn't use locale correctly

### ISSUE THREAD

**Issue by jchown** [vuetifyjs/vuetify#18210]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Windows 10

### Steps to reproduce
Go to example, which opens a Swedish keyboard mode date picker (as per example docs).

The placeholder text will suggest you type in your "local" locale, e.g. for me in the UK it suggests dd/mm/yyyy even though the field is expecting yyyy/mm/dd in this case

Type in 1/1/1 and clock OK to see the actual format the picker is expecting

### Expected Behavior
The placeholder should use the locale of the component

### Actual Behavior
The placeholder uses the locale of the browser (I assume)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqllEtu2zAURbdCcJIWNcWkblFAcAonaJsFBO0kykCW6Ia2RBF8NOPA8N7z+PFPHlhAJrZIXt5zH39PG+pWwsr5W7YAmlPZ6s5YsiGVEaUV/+IY2ZK56VpylbRXhdoLwfVHedNVZSMOol/o9EfBXV1qK0wST2vsZbLj4X+u4KAH9/g7qXaDyZODQ1mhxDoIq06BJQlLbk9Df9oUipA4LyehQUgrAMr/ArAjJB/57vjrUXtdGbPmvexBeGZK0CoPqdP4wXb7uVB0RO+0zjAmLvDEilY3aPrTSya1dKRqSoDbgtZs3og1WazAx2eVUEgsaBCi1LGIZdp0Tta4kLGNM8HtZUEYVk3LaokiqfTKsrarvXAp3mZdaWqUT/iJbkfB3h4mBuWYFL8m/Cg/FtZItQQ8Op3C2sJyFLQCKGhOnqJjQV+s1ZBzXtUKlbVopDOZEpYr3fK0edNxNs5uviMF7K6PNeUMsuDmrZ5xNZEYzwhrS93DxoGATvtS+LPt2xcyTFHGzUpZ2QpWd20I8y1mOerOBLRsZrpXEAZNCpp2O2B84AGoi+Ui48ybI9AJw4xQuB/+TAwrqTftuKze0MXS0v0bXiFv5Gx3aSVC1lm7AP4FOUfmZ2/AkMr6c6Zfs5sf2TWfrWRTJ1ZcxT6u/5gIxf4+DkAekcbXSELXE4sEHQR8uP8w8OF+MNA/DB+hgeujwsPmb+J2RMN5wisZDzN9fgc8GSF2)

**Comment by robertbarclayy** [comment]
please can this get fixed asap.
