### ISSUE TITLE
[Bug Report][3.3.15] v-date-picker range prop not working

### ISSUE THREAD

**Issue by myungsunscott** [vuetifyjs/vuetify#18213]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.2.1
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add a v-date-picker component to your template and add the 'range' prop - try to select date range in the UI - only a single date can be selected.

### Expected Behavior
user should be able to select a date range.

### Actual Behavior
user can only select 1 date.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMtuwjAQRX9l6k1aicSiqBuUIrrrH3RBWIRkoC7xQ2OTqkL5946TIPHYILHzXM/cM3dWR/HhXNYeUMxFHlC7pgy4KAxA3qalc/2zLyprQqkM0ij1Ys3dqVPVHgmoNDtc5PJCPc2zemkQlcE/l2dcLn1FygXwGA4DXmlnKcARCLfQwZashoRXTmI7APv6ANrv4D12PCef2DQWviw19VPyEgGDJZuJiRjcUl267Mdbw7mP0aUYP3wh5tArUWNKrAvxHYLzcymr2vBYjY1qKTMYpHFaLrlN0sEEpTGtrV7OstdsOpO18uFcz9DrdEP21yOxSyEmZ5ygtn93sMZORsyy6duAGLW0KTc+Mm68JQNbpJTQ1EhI92a6GrvIdfV3ky3iu8J0fPJGmb2/unbl+0uvTls+Frp3i1brSOwmYtiU2cOIWP8D8yj6kQ==)

**Comment by 3aluw** [comment]
Range isn't available in[ date picker ](https://vuetifyjs.com/en/api/v-date-picker/).
However. It would be a good feature to add.

**Comment by johnleider** [comment]
The range prop is not intended for public usage on v-date-picker. There will be a v-date-range-picker component.

**Comment by mbeggas** [comment]
Using the multiple="range" prop is indeed the way to enable date range selection in Vuetify's v-date-picker
