### ISSUE TITLE
[Documentation] Sample code of Vuetify Calendars is incorrect

### ISSUE THREAD

**Issue by NguyenNamUET** [vuetifyjs/vuetify#18218]
### Environment

**Browsers:** Edge 116.0.1938.69, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1/ Open sample code in Codepen
2/ Edit 
<code>requestAnimationFrame(() => requestAnimationFrame(() => this.selectedOpen = true))</code>
into
<code>requestAnimationFrame(() => requestAnimationFrame(() => console.log("TEST")))</code>

### Expected Behavior
Click on an event will not show menu
Double click on an event will not show menu

### Actual Behavior
Double click on event show menu

### Reproduction Link
[https://v2.vuetifyjs.com/en/components/calendars/#type-week](https://v2.vuetifyjs.com/en/components/calendars/#type-week)

**Comment by KaelWD** [comment]
`:activator="selectedElement"` is why it opens on the second click.
