### ISSUE TITLE
[Bug Report][3.3.13] a11y: v-divider hr should not have role of separator

### ISSUE THREAD

**Issue by kmmerc18** [vuetifyjs/vuetify#18229]
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.1.5
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Using the Chrome aXe Accessibility plugin, scan the reproduction link page and see the error "Certain aria roles must contain certain children". The role of 'separator' is not allowed in the list, and is redundant anyways given the implicit role in all hr elements.

### Expected Behavior
There should not be a role of separator on the hr element

### Actual Behavior
There is a role of separator on the hr element

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=true#eNrVVD1v2zAQ/SsHDe1iSsjX4rpOnHZourRFCnSIMlDi2aIjkgJJSTaC/PceJTuVbaRJgWaIB8O8z3fv+e7mPppVVdzUGI2jiUdVldzjNNUAk4bl3IrwEyAvuXMf00itGK+9SaPerPiKtVL4glynx2e9ucvu8kvpPJRSY0j1LaVtfI9e5uqsQC7QTn8awdeT5MCe6v0cSTi3NoDKYoVaMN5wzy01Kryv3DhJcqHDYF7O10sX50YlUvEFuiQUcclRvKwW20HCx0tfIuVf2lrnBfhCOmgR76j4+Z+4xwkIz5YvaJgrjR8T6K7IIIaiXMX1I4Fzoz1rUS4KzzJTCqJkVkr4ZLQ21k2SEDyFd0pwV3yAq/dlCRmC1LA2tQUdEjNjC2MECCP1AtBaroXbgRvDZxMSoOXagzdQcIo0tT8fgE921O5NA4J3eReykSQGAXHopyFwY3k1eY535fkb7YecX9dKEdrLyx979HtcebawuCaoJAFqdkQKnG54f4Kd/644KTIrcTWC69x4P4KvqLWco92X/5d0BVxBbupS0LfCEWS1p3+FCmKCmZO2rd6V/u0ofPLUAn6rJc0nX3PnrmlnLIeZ4Opg6Ta7U/AG4Tu3xK1FAq9oRu6l0e4cvgRfCMKGKMsQ9b9t1tDWH1t6hGtLj0F6NIroet65eOmMpgN9H0LTKHcujcZw09fZ5XvpBJaysbFGn+hKJRsBLk7ik/joLBHUcWtjJc9Il1AtlLpN9QN1lKoy1jPFq722vaNr3VmCjSqF9zMYLigsoavqpUImjOrAnPZYBuYYnWKZNa1DS0XSaDRoEwC/oNWz41KPg9oJNSQhmSWJ0aJ96Uh7acOx9lwHo4XuD4Hwh1HUpRHzPebo9jfQtHiI)

**Comment by websitevirtuoso** [comment]
Everything corre. this is default behaviour
here note about changing this
https://vuetifyjs.com/en/components/dividers/#accessibility
