### ISSUE TITLE
[Bug Report][3.3.15] Slide the next tab when slide VDataTable

### ISSUE THREAD

**Issue by duongxinh2003** [vuetifyjs/vuetify#18224]
### Environment
**Vuetify Version:** 3.3.15
**Last working version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Inspect and Toggle device mobile (screen width smaller)
2. On the tab 'Landscape', slide the horizontal table to the seeable 'Iron' column

### Expected Behavior
Keep the tab 'Landscape'

### Actual Behavior
Slide to the next tab 'City' and don't keep the current tab

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV9tu2zgQ/RVCQJEWiCTf5CSCt2iR7qXbPuR1UeeBlsYONxQlkJS93iD/3iEl2bJkunbrJw7nduZwhqa+vXgfiyJYl+DF3kxDVnCq4f1cEDJb+wmVqV1bSdOFIms/y1Pgv809FOceSXKeS5RSgMIvSllw8GmSgND+BNWUs5WwnmhjdkHOvTpkE5TEa8pLQIMh6r5SkaqEFjALrdZpPELje6a3P7Ibo93HhdKSJvrQtpbUvsQNE2m+6RbZDl1Z+AypQrOlrV0QJgimIfEzbI1slk16FHb+Fam50JQJkGTJS9bwu1OnVFODikNbQRpMscms/AKkX9CVSWA3HkA+oDj3Dp3iJ6ApSEN+vepZWHd7gEqB1D0Do/d3xdCslyPhVJkAwGFNNcuFj8fYNnlveN6X1WYDFTs69izjbovm1mFVu1V3GteqPWdhq29nKpGs0NYG/ityqUkKS1pyTV6qQAbJ23eNRIgEXUqxlwlBmDERJefX+702yzGJWpqa2Jh8axfdCmdDMs3R7+pTxTJ5OxwMVgSXayZW765a4czPTg1aK02l7ioV1mR4jMmScgUdLXYgOppzOvR7PZBedoDuKc4vA3V1TTYs1U+4FQ3eoNRgAJGiVIVNGmNnuD8o1mYKOiPakmp3oHsq8bY5NxR2wuIEqgeZa8AZPTdcUdm7A36WOUZ7c140hsaHoR5b62buTvePOVBDr8z/B0H+yVdlvzGa04nJMLrr6JDrmEyDQc8FeYvJaNLZrwmIyaTnYqpBJMOT7XUU/N/A+ZYsgAo38vFNe7R2yAcu5HdO5H2XGvngcuRfmP6CzepEHQ1vj6EeOQmfdqvcwb45Dnp6Oejf8WJm0g16NB0dAz10d8nYBbrvUsO+uRz2n3ghglxIvFVPtEk0vQz7pDsQO+zjoKtqOvwnOP+cAEkQekYUPmM2LHk6wf+4e9a2hjtXCT3z1pB2T+bnh/Rrzjkr8uIE93dH+2YQdLebEe3Oxn5Ej6MeXY76viwS+tz5yzsAPTh6r4yDLqnNgF5O9u3lsP/KBWyTPFu4gU8GR6+WsYvtWyfwadCloAY+iS5H/ikX5YkLcRId7ZFR5GruaOjm2zGfoxN9sv+Dfa0WlRKFWbh7IHrXHsvMC9HPaBH8q3KB30C2XHxUWwU+huOGgLmHH0lGxqe01oWKwzBJBbrho5ytZSBAh6LIwg9oFspSaJaBn+bZh3EwDiZhypRubwegMn8h8w3++WOQuVcjtmk0W27PSFVb2gzDqEpR7/kcv2tMjl7s0Dw68etB4hMFpPkcO6+kjlu7rI6qV1pN/SsSzpl4Vh2uE2V5rp8/v1qzjWZCPZqMr9eeBYqpKw/v8TuBaPFS)

**Comment by vitorfba** [comment]
Hi! 

I'm handle this issue using model-value instead v-model on VWindow component, and setting touch attribute to false.

<v-window :model-value="tab" :touch="false">
