### ISSUE TITLE
[Bug Report][3.3.15] Reset v-select v-model when items prop changed

### ISSUE THREAD

**Issue by mohammad-zr** [vuetifyjs/vuetify#18222]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Edge 116.0.1938.69
**OS:** Windows 10

### Steps to reproduce
1 - Set select1 v-select
2 - Set select2 v-select
3 - Set select1 v-select again

### Expected Behavior
It should reset v-model value to null instead of showing value of previously selected item

### Actual Behavior
It shows previously selected value. In vuetify 2 it was ok but in vuetify 3 I should set it to null manually

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVE1v4jAQ/SuWL6ESSUSAS0oqVruXPVfqhXBIk6HNbuJEtpNlhfjvO7bzVQd1kXoBxvPevOdhPIcLbRuQ+emv90vQkOZlXXFJLiTlkEh4MTlyJSdelcTpsE7MYgZnDU0rJiTpEiT6SFxcYkZIUaVJASHRwRg6p8RZmiMuiyFNdCIkkjdgTq7qCz+uD490Sb/VtYdyaHYnoawLVHtSgF3rJnWtf+qAV3+6QIdpVQyhPhBQQCrHIzSWvEIRxfRZZ8gqptNsmKOcwLT+tpKtW1aZJpuykFmAfVNn6DTUsJekaACxFTNSq+/vCXuDbErxR/N+7/7/17HvEMTUMq5O5m7V6S3FPuqbqX6bLu/8SfcxFCnPa0kEyKZGF+wNq0sRU00bxorDaTpMzqO5lBmioXU4RghcsKYoHhBh5wMrPyLMX9OlD8b+hbSq3SFZLYnMpZ48g3NXDrl2EzigghkqQJQCHW9o9VYON5M/Epk8Vw1PAWGdnU8MBWhoieWwqXnFfmaIGPx94jBAh3fQ1jPa+h7aZkbbWLTgFm07o23nNMM6fuic/Sawc4sHEj3168FU87QM5uxGe6e8kMAXi7Mmnb1RkkRRNM6YqWDGC43sfDPAOK64Y8y8umVS41qsGO4arY5PSCdwrId1FasFquKYvktZi9D304whDR9Y3nKPgfRZXfp7hPm8YTIvwc2qcr/21t7Gz3Ihp8ceiNJ9xecmgGORmHat1TJqpd4h1SG1wmprJLozF/eDUBqz2j4KtsBdDiwDDvzeK1m06bWs1Oxq/VrHhhc5+y2sXqdC97l7N1+9s66mn7FSvC6pNorShkGP/wAyTj2o)

**Comment by KaelWD** [comment]
#4000 - this is your responsibility now
