### ISSUE TITLE
[Bug Report][3.3.15] v-color-picker: Setting a 'width' property on the component disallows a null value, defaults to #ffffff

### ISSUE THREAD

**Issue by craigrileyuk** [vuetifyjs/vuetify#18231]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Mac OS 10.15

### Steps to reproduce
- Render a v-color-picker component
- Pass a modelValue Ref containing null

### Expected Behavior
Picker respects the null value and show no colour selected

### Actual Behavior
When a `width` property is **not** set on the component, the behaviour is as expected.

If you do set a `width` prop, however, the previously `null` value now automatically defaults to `white` ( #ffffff or rgb(255,255,255) )

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUtGOgjAQ/JWmycW7RKgX716IGu87xAeENfaEtukW1Bj+/bYFFfXF5F4Iu7M7szOwOvMfY+KmBp7wmYPKlJmDRaoYmzVRZkx4DUWVSdVXVBeyYehOJcxTfpCF2yVsOpmYY8qvM2Er16W2kZH5HuwNYIz4dAElbfuJ2qZ8iHqMoB0cs3sg8QgStBp5cLS+h3GnDxEeMpfvAIdAOJHWPieTt+HKYibub7w5FGTx4p6GrvZ90QUzE4PAqMTcSuMYgqu73GRltHXszCxsWcu2VldsRFmP/DhjuVbo6On9s7kfeld1WX545o6LWPiYdzR0gYl/USv6Ume/nvYApjxhoeN7RO9rCs85g4kQeaFojbKWjY0VOKFMJZY0JmytnKwgKnS1nMbT+Issoxu2Y8Aq2lh9QLBEkvLxQMbJ7ekFqX4yKHx+dxJ9LyqzDXqNJ25Bgg3YyIIqwNKv86Klh7WhrQfoyZpXb1PVUuClVHt8yDrHkPPqcuT/PAc2T7X2iu2Yh0NJutvg6z8asSg8)

**Comment by KaelWD** [comment]
wtf
