### ISSUE TITLE
[Feature Request] Ability to hide header on VDatePicker

### ISSUE THREAD

**Issue by yannmichaux** [vuetifyjs/vuetify#18237]
### Problem to solve
When using a VDatePicker inside a VMenu, attached to a VTextField, it can be pretty useful to have something like `hide-header` props to hide the header.

### Proposed solution
Add a prop `hide-header` to hide the header (title & button to switch to input)

![image](https://github.com/vuetifyjs/vuetify/assets/23440844/77ab1b4f-7ad3-4ecd-9d6f-1f50ecf61cf6)

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/18120
