### ISSUE TITLE
Select with item-value starting with dot doesn't return the selected value but entire object

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#1823]
I have a v-select that is fed with an array of objects containing a `.key` property as `item-value`, when I select a value,  it breaks the logic as the selected value set by the component is the entire object, not the property `.key`. The issue seems to be with this piece of code:
https://github.com/vuetifyjs/vuetify/blob/ebdbfd3c10f4f393308a69e1d00b666685e09b1e/src/util/helpers.js#L102

If asking why I use .key as value... I use Google Firebase as backend and it uses as id for objects the property '.key', so I have objects like:
```
{
  .key: '-werwj3489f3fho2',
  name: 'Foo'
}
```

### Steps to reproduce

Open the reproduction link (codepen) then select a value from v-select and notice the selection value

### Versions

Vue 2.4
Vuetify 0.5.7

### What is expected ?

When I select an item from select I expect to have the value in the model

### What is actually happening ?

The model is set to the entire item object, not just the value

### Reproduction Link

https://codepen.io/lucafaggianelli/pen/JrXZrR

**Comment by johnleider** [comment]
Very interesting issue, will look into it.

**Comment by johnleider** [comment]
After careful review, this is something that I'm not sure if we can support without decent amount of work. Do to how the dot notation works, this is not something we are going to pursue any time soon.

**Comment by johnleider** [comment]
Closing as this would cause too many potential breaking issues.

**Comment by mismith** [comment]
Damn, just ran into the exact same issue (using Firebase keys as well)... wasted a ton of time trying to track this down. Is this still only a remote possibility?
