### ISSUE TITLE
[Feature Request] Vuetify and vue support for long term

### ISSUE THREAD

**Issue by gitgkk** [vuetifyjs/vuetify#18236]
### Problem to solve
Support for Vuetify 2 based applications till Vuetify 3 is not ready and stable.

### Proposed solution
I have a large Vue and Vuetify based application. I see from Vuetify roadmap the features and components Vuetify team is bringing for developers. 
I understand that the team is making huge efforts everyday but development and tests take time. Because there are some components which will not be available soon and/or not be stable, I'd like to continue using Vuetify 2.x with Vue 2.x. I'm sure there are many people like me who face the dilemma of migrating or not migrating. 
Given the fact that Vue 2 support will end with the end of 2023 and Vuetify 3 is not fully ready, will you work with Vue team to assure that Vue 2 support continues till the time Vuetify 3 is ready to be used or is it up to the users to raise this with Vue team?
Please suggest a solution because my application can't function due to lack of Vuetify functions and I can't migrate if they're not ready.

Thanks,
Gajendra Kashyap

**Comment by KaelWD** [comment]
What does "support" mean to you? Vuetify 2 will continue to receive updates until January 2025.

**Comment by KaelWD** [comment]
No. Vue 2 already hasn't been updated in 10 months, if it still works then I don't see what the problem with some arbitrary date is.

**Comment by gitgkk** [comment]
Thanks for the response.
