### ISSUE TITLE
[Feature Request] v-select: add "mandatory" prop

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#18246]
### Problem to solve
This feature would allow to have a v-select with a default value without changing associated model.
#### Example without feature
```
// I need to know which are the possible values, not good
data() {
  return {
    animal: 'DOG'
  }
}
...
<v-select
  v-model="animal"
  :items="items"
  ...
></v-select>
```
#### Example with feature
```
// first available item will be selected
<v-select
  v-model="animal"
  :items="items"
  mandatory
  ...
></v-select>
```

### Proposed solution
Add "mandatory" prop.

**Comment by KaelWD** [comment]
If v-model is set the component has no internal state, this would not be compatible with that pattern. It's trivial to set the model value when you load items.

**Comment by simionato-mobisec** [comment]
> If v-model is set the component has no internal state, this would not be compatible with that pattern. It's trivial to set the model value when you load items.

Ok, but...what is the difference between v-chip-group and v-select (about "mandatory" prop)? I'm genuinely curious.
