### ISSUE TITLE
[Feature Request] v-data-table: show ellipsis when text overflows (instead of wrapping to the next line)

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#18240]
### Problem to solve
This feature would allow to have rows with same height. It would be awesome to configure this behaviour for each header.
#### Example with feature
```
headers = [
  { text: "Long Column", value: "param1", showEllipsis: true },
  { text: "Short Column", value: "param2", showEllipsis: false }
]
...
<v-data-table
  :headers="headers"
  :items="items"
  ...
></v-data-table>
```

### Proposed solution
I know it's md2, but I think it won't change with md3: https://m2.material.io/components/data-tables

**Comment by qxygene** [comment]
this would be nice
