### ISSUE TITLE
[Bug Report][3.3.16] VTextField clears model value to null instead of empty string

### ISSUE THREAD

**Issue by KazimirPodolski** [vuetifyjs/vuetify#18247]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Make a `<v-text-field clearable v-model="model"/>`
2. Press clear icon
3. `model` is null

### Expected Behavior
Clears to empty string. Text field types doesn't help to expect this.

### Actual Behavior
Clears to null.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU19P2zAQ/yqWXwpSk2hqtYeqVGwTD0MMprE3woObXFuD7Vj2Je1U5bvvbFPIygQ8Vf3d5ffn7ny3595VxRdr864FPuNzBG2VQFiUhrF5lznwtjFedhAAxiolvD8rud5losWm5AnWYpdtZY0bKk2m0wRHjsiCsMNsJUHVCWKsy3RTgwpM4ffAEwRAOLFUT3qMbWQNWQ0opArCQ1XGlFhGkivhkRmh4VBazIuhLFlJ+I+gxjqhWpix/f7y9uY69+ikWcvVn5Po5bTvY3gieElPBPNiMBz66ysnLTIP2NoYVWrbOGR75mDFerZyjWYjmusoiVfEhCxKsLPQczK6AgrnRqeBPNEt+JgraR59/uAbQxvZh09LXnlf8hm7SylKvkG0flYUVW2okyhl53IDWBirC9JEinM+ySf5p89FLT0esIwm5vPIFqjuS9OTYnKeaWGPZFMhSkckYMQU/r/j4ZzaCtcalJrW1+hoZpq8DOAcvM6Wrtl6cERS8vFAJhj+gNS7cUnjFXdBgh04WrGhFYD7aKSjz4axjkqvogV1Oq0wcPR0DSu5Pt5yo61U4G4sSrqWf8YulGq2lxFD18JzlmoD1eN/8Ae/S5l+0hUHZ4P8KNwaMJUvbq/pmQyKdKEtPb+3ir/AN6oNHlPb19bUZHvQF91+j9dDb+u3v9gh0EN6ChWMxmnE/riPb29Ef7FL036eYj/mcfg0zrR5fv8XS/uXsw==)

### Other comments
Lots of reasoning in #4144.

**Comment by ponahoum** [comment]
Agree that this should be fixed, very annoying to upgrade your whole api to support null values instead of empty strings
