### ISSUE TITLE
Custom transition to previous v-tabs-content is ignored, uses default slide x

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1825]
### Steps to reproduce
1. Click Tab 3, notice it uses non-default transition
2. Click Tab 1, notice it uses default slide-transition

### Versions
Latest

### What is expected ?
It should use the custom transition regardless of which tab item is clicked

### What is actually happening ?
It's using the wrong transition.
NOTE: I'm not sure custom transitions are actually working correctly at all.

### Reproduction Link
https://codepen.io/jayblanchard/pen/KXMdvd

**Comment by johnleider** [comment]
So custom transitions are working, however, the built in ones behave a bit different when it comes to list-groups as generally, you want the leaving element to just disappear. You were also missing the **reverse-transition** prop. 

https://codepen.io/johnjleider/pen/PJyYQy
