### ISSUE TITLE
[Bug Report][3.3.16] Appening v-select to v-text-input changes height of text input

### ISSUE THREAD

**Issue by benjamin79** [vuetifyjs/vuetify#18250]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Append v-select to v-text-input 

### Expected Behavior
height of input stays the same

### Actual Behavior
height of input expands

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8FuGjEQ/ZWpL4DK7hal6mEFKGkVqe2hrZpKPWSjatkdwInXtmwvIUL8e8c2kIWkVaRwws/P7828mb3eMGuq7ELrdNUiy9nYYaNF6XBaSIDxKim1Dn/DoVLSlVyi2UEBdLh2yZyjqGGVNKpGMSlYYxcFgwMNDrrEsUK5nHRR1o+Ekx/pWhRYOcg5PbUkeWFM+ZDOjWr6GxAoF26Zw+gdbIfQ/zMEPoDJFDi8hdGArEU5C4VcRZUSZNvM0BRsOs722s+6j7OjCCLU7XIfB4HHeXgkxnWkQUdbGa4dWHRtTJM3WhkHGzA4hy34pqBHE+h5OgDpWgeUIUw8o9/7jEIo+K2MqN/0Bt4gSpIYG7KoljSlTm+tkjTGjVcpdhe2YDkExGPk4s8FWzqnbZ5lVS3pGY2Nr0wq0WVSN9k50TLTSscbTGrVnJ+lZ+n7rObWdeEUbZPMjLq3aEikYMOOjePzhxdY7ZjBYfQhWuywhKZovccT7YwMV2gSQ0uExs/1ZS2dPOu2dXL1pDXvvi3klgIXXN7Zk6wrG3K+3hf5up6Dmpe6iY7O0k7M+eLUVDWaCzTfteO0M0eDLmll7r8GzJkWD+lVS6zunsFv7Tqm+MNgyKKTuCvNAl28vrz6Rt9C55K++Vbsluoflz/RKtH6GiPtYytrKrvDC9V+CfvK5eKXvVw7lHbflC805B/4YQM+/af1x3Ip4MPctkMWxk1xxtzZzV8ozp4f)

**Comment by KaelWD** [comment]
`hide-details`
