### ISSUE TITLE
[Bug Report][3.3.15] checkCalendar is not a function... Why does it say this and it doesn't work if what I did was copy and paste?

### ISSUE THREAD

**Issue by drfcozapata** [vuetifyjs/vuetify#18263]
### Environment
**Vuetify Version:** 3.3.15
**Last working version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Open the reproduction link

### Expected Behavior
To make it work and show the calendar

### Actual Behavior
Does not work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNWX9vI7cR/Sqs0EJyrZV0ti+4qHfuJe4VbdHrHVID+cM2ktUuZW3MJTckJdsx9N3zhuSu9pcc+4wAORjQLjmcGb4ZzjzuXTwMjE6m3xTFZLPmg/ngreV5IWLLTy8lY283kVa3LBGxMe8uB8tMiGjFs+uVvRw4ASeSKBFe3KtZcW6ZF8Oir04q2SBglRKLWO/GGFvC5O69Ju4WLKysjzC2iXUWS9Ku1lZkkqeXg6ZE6XLOI9hvzSmhNOauNb+P0ljfcBkdtYXeJyJLbiBluD1XaXzfFGi4yJiXqHs9dW7/5k6W8WLf1iy/A8zNWZP9wsmnPBbiZdsqNN88uiV4myVKtky2hBjL0yxKVnyjlYwEX9aiWMJAWpo4/NGxkR3tL8dGu1PzxeCEMxPZzArOsG4Ju0ksuMRuOqYfHlg5N/Erttu2kYbGtjlTxAnXpyQXHlsCOZdrJlQS20xJuLJQ1qqcwWTHmaqkwG0jlJ3Hic02sXUBeWBKjllsrTZs2wNhX148rQI8OexOXbTIZApJ50m/hNunkt3JjtNwG6jJU4TB3hf8XP03XnBxQc9XiMTbqZvtWRXSCij2zPp8IuCjVN32YNKbT/tyikYbtb7hhsiM7YsFjUcZ1u0OC+2KvWNDFMBhTwCby0K2/SO+J5/aw31+VzLPdOeW85sn+/M9hH9vh3Il7erJHn0k6d/bpZPnxOyEQdq81KVyrlPzKK/rNGFXoXbcgqoRkYvH2MZs1qYbVZWsWdS8WT/rc/BFpVwQ31HJulUMyopS6CyPdYsUzPmGS0u0wz/0zRJb8jWJ2w80cEbvLUkKUIhTc8aH0GuixrNSt05Jr1SuNGnZZPwWB65XJMXp3y+yiuU1Ta8LkvuO3uoirj2UGDYxp2j2Y2q44Inl6aeCt0rpPBHKcJRZQCStgyrk6zIWpgVEo4mUOj8IDsMtMNRyCQoX3e2nl0ms00fogqDUQuPo8Mg8k9FtltoVJI9fz4q7tkCT1faxiB4q7KEIDlQ7oyBP3Gi3/1Bja47taaOstztUfeeU+gvCkmTima2kl6KsbF4PuN+CjHNE0mXOfgLyJBLyvG2teKztl+zqifpTZU204dpmOBDPbsTdWtdIzojoblcZsYh9OKfcxplABQJ8PWzDn9x+zaVROmFKmi+gZH3svH6sDAc4yNpWwelcvHaVAt2qpwjsIV9nsUy4eDr2e3dbTrb6UqNVtZuSWxMuxPSM+zOeG1wLrybRWWEZCtO6CAuzvFDaMiLEH9UaBTAdU5tiW7bUYNZD3M+HtJZglMZWBB/QQGx0UJ+rsU5MP3gDjoDM2dBRi+HYDxJNwhgRoHIIbR4jaAflgOcJGDthGDV+2N0ngicUVgNDF8OFgJdjNgSZzq4VPaWcF1Gx1oVwE8l9LOkXlZW7B6WprYShe1fLUGtfDa92+qlmePUfgXMmr0n6X0pk5BYeP59/op9zHW+4oCd3BOjh20zbVZA6U3LJNaqbM/YZ5eCejOzMuG4f0BwOgWcdzXLcs7jaZOPYBamHbZ+Ab05BRK6F6BEKuU4SLt9rIp5ShMmLqxDvKllGowP27rSMdXX728SIyASX0OTmzLVzShRELyxfrqXLexYYABs9IAS4qm0PSlUOFq8HxmnSjxMq1bBn/2VaVFobHIeN3BYqxRrJr3HZqbW2joLy4wvD7nr9GfZYpU8btQUtLGg2gNBYRZf+/atotm9VxcAIOYnb8Ia717HfVw1HH0XlA9wIFj5dNGp3uTenoSPi06gSqtmc2FgD8XKF5j+vubHfSDBV8vWfGucopMljc/VcrMxYveYHbv8BARSsJRt1Zav97lxuKPJl/IUuEoqjg8ofxqFzZ9fPNnyto2SsKj5rVcTXTm9fVGuEl+JqACxFVKadeP5QHcsLV7HKcXBDCg6/Rcm0fPTjnx+ckgnp3Z7PZnP392PwMqyJ71prYDGsODqev/4af80VdCOjbMLKCSJ/ngGhAxaR9d37AZuyN1+dzOhffbHz/IyqBxUVmY5I29jrPGRHs2BpSSdX4I6VQWz2N/y8rS3F++FhLeZeNT6HUTHxamdjdoyovcPqptQy08b5CGjyIkg3XB8TJrWd9KyvI9ZSGLH2yF/Y1w6GtiZPSNquHOHDlN/I39nRmzdszt4csL8GFX0KOr7UgnLYNlK5EFJoUqzNalQBSTmb87lvfhcBR/cyQWG6tits79XBVWjR7rhRgs09KrVh5NA82K6Nuno7D627VO/f9um38Byq/uQxqSZ8r6tOWthMedzD5rpHDCbZKB6zRbsffIztarIUSunRaAEnYkD3inB3E2ALqcopqQ9ZHLSC4To6BSI1GA88j4ryuJj8ZJTE/2k4/ZdhApR4XlrExXcNSjnHw8rawsyn0ySVWIararbRKPp2Kot8+h5iU41sBwJg+vn748nx5GSa4jtGfXjCTR4tQPgM11ByOQgYOTM2W4Lu/qapIOksvHrtTYSxSMQLQzY6uqcwiLtHBHaTguLgivi0LbWW1bfVmupsLUC/BeD4+npjWlgnxuF8UTr5sj07baQKJZYsWoNsXmbXbaMqLzLB9afCUflGoJG06vY/boxaWYWeY0Y94z8Z3OYJxc+aOyxqiIc266Y//P9/7rJTTeI7x1qEpNoz+R03SqzJRy/27VqmcLsm57z9t8tX0N1z8+EOHyBMuSly1OHv5F0GnD2y9Z27ALiK23Y8cOEGnB73wdWvHz86sg==)

### Other comments
This is the Event Click component (https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-calendar/event-click.vue) that works fine on the Vuetify documentation website but nowhere else outside of it, and I URGENTLY need it.

**Comment by KaelWD** [comment]
Calendar doesn't exist in v3, follow #13469
