### ISSUE TITLE
Feature request: use .apply() on v-form validation rule invocations so the Vue instance can be referenced

### ISSUE THREAD

**Issue by davidkhess** [vuetifyjs/vuetify#1826]
I'm new to Vuetify, but unless I'm missing something, it doesn't appear that I can reference the Vue instance from a validation rule function. I'd like to request a feature where v-form calls validation rules with `this` set to the Vue instance - it is currently the `window` object.

 - What will it allow you to do that you can't do today?

This will enable you to write validation rules where validation of one field depends on the value of another (for instance, "password" and "confirm password"). Also, in my case I like to suppress all errors until the form has been submitted once. Submission state is tracked on the Vue instance.

  - How will it make current work-arounds straightforward?

To my knowledge there is no workaround at the moment.

**Comment by KaelWD** [comment]
Example codepen: https://codepen.io/anon/pen/rGLzYK?editors=1011

**Comment by KaelWD** [comment]
It works if `data` is an actual function instead of a lambda: https://codepen.io/anon/pen/yzJzBx?editors=1011

I tried binding `this` in the component's `validate` method, but then it refers to the input component, not the parent.

**Comment by davidkhess** [comment]
Thanks, turning `data` into a function and binding a reference to the Vue instance there worked.

Perhaps I should close this and open an issue in the documentation project requesting an example pointing out this subtlety?

**Comment by KaelWD** [comment]
It's more a quirk with how functions work in JS rather than anything to do with vuetify, but it might be worthwhile to mention on the docs anyway.

**Comment by davidkhess** [comment]
Closing – simple JS workaround is available.

**Comment by davidkhess** [comment]
FYI, my solution:

```
...
    data: function () {
        var self = this;
        return {
            rules: [
                function () {
                    /* code that references self */
                }
            ]
        };
    }
...
```

**Comment by KaelWD** [comment]
With Vue 2.5, you can use a lambda for data again as it now gets passed the vm instance as an argument.

**Comment by lcherone** [comment]
This way wont work:

```
data: () => ({
  someRule: [
    v => !!v || 'Something is required',
    v => (v && this.someValidator(v)) || 'Something invalid',
  ]
}),
methods: {
  someValidator(value) {
    // validate
  }
}
```

But this will:

```
data: function () {
  return {
    someRule: [
      v => !!v || 'Something is required',
      v => (v && this.someValidator(v)) || 'Something invalid',
    ]
  }
},
methods: {
  someValidator(value) {
    // validate
  }
}
```
Had me stumped for abit.. I prefer `data: () => ({})`
