### ISSUE TITLE
[Bug Report][3.3.16] Navigation drawer title - letters are cropped

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#18276]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
![image](https://github.com/vuetifyjs/vuetify/assets/17653648/7fbb31d8-243b-4ffe-a1d3-d86a954b6393)

As you can see, the "g" letter is cropped.

### Expected Behavior
"g" letter should not be cropped.

### Actual Behavior
"g" letter is cropped.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVFtP2zAU/itWXnjBsRDTNFUdgk1IG9pNY3uiPLjJaerim2wnBaH+9x07TZreBhJv8fFnf5dz4rvnzLuCXVmbNzVko2wcQFnJA1xMNCHjhnJr02e3oFPuSGGkcR8nmXVCcfc0ydaQIYhq3lBRGE3Yod0ggoQLJJai4EEgDKtjtgvoT3a6SEO9NGGEMNBlv5/ungZNIiMqU6Wgc+AuTLIB/yGU4pUWM/TwAq40wdMGXEC9cgs9ZluhxUJvY5MdxiGq5JSWji/BEQtOcQ06HHdpHezblMIHKhBKpNDgUV9YGlS0BlPe8MBje+YhWD9izHFdGlV7cLkCxq1g1rjguAieLY0CzT6c5Qtb4R0pdTx6g8LIrRJhPsk25IT4etpBvpmqgpIIje2PjntZx4NJ8kvRiBJcOtN97/kjJWgvwhPyFEZZXsRGYoQD5E4WnfvhAKA3WuAtA2NfsIbLhss6LiPkqP7XcPCiMLWO6jqG70/kqi92PD3s7VS0cqa21NQhtn9A/Bcb7AecseG4PsrY1QdTuzek7TPQzjN+b3UUl75wwgbiIdRxW6g4WOSZOJiRFZk5o8gJPiwnCcxaNOKy06yF4t9n84U3Gp+e50g1WW+g7hFJlVjDK+J6M9FFqfFYCVI0LtcQmLaKXSKMOUxIYNtx4C/P8/P8HSvR4rCcg1d06swy/g8LJDod0IT0FLxItUYmhrP3LcW6RiWf+sixdzdDQnxAqMO+ggP3Wks7x4a2drb2rEX21USvMHAclge/k3XhU853nci3eU63xavuW8bgcXZnotolxf9ZSHA/bZyz7UZzKc3yJtWCq6FPr5hD8XCgvvCPbYq/HKQsBonjG1gB/nFx+/r2Bzzid7+pTFnL9VAd2fwN3sg6amxhn2pdouwBLqn9muZV6OqPv34M8dVam4pCU/4Jnybg83+sb+RiwH3fVqdZajfG2eae3f8DMOCI1w==)

**Comment by torerik123** [comment]
Seems to work in recent updates, except v3.3.22 where it doesn't show all the items in prepend slot.

https://play.vuetifyjs.com/#eNrtVj1v2zAQ/SsElyyliCAdWsM1kK0o2qnoVHWgKVpmIX7geJJhBPnvPUqRI9UK2gAZNYnie3d873gA7+cDT6DlfYxF1xq+4Vs0LjYKza70jG07oWLsl+OP2CtgOjQBPpU8gnUKziV/okxJwqtOWB08k0soWmzMjg5urFZoiUa7W/k34RI56mKdSE3ADdGMry54n3uPnuUTSZmrrDgaBVjyyflLLKdqbw/k4R+8KmASnQEkvc2MvZWzouWNi43n2lE5bN07FRWokwEWDTjljceXXUYw1zYbm1BYoj7vMtZYbxJJxVMo+RR4SiFUp1DlSzsixrSREpSvgmuTgcIZqaKVMQCCspjkKTjj5Yfb4nes5+n6a6EsX0g5++4sHud4avcj5Wuoa1Mx66eMqRUq08XLanG1uFpcLa4W39zi1fvUe65sZysDuxwzridwTsMq45PFM52sg4tK59eU3rH/KN5Yo+lzTBUQmtIt2/9M8BzpVNNmJAfODL/2JhfEKK1D68nPkpRvZ3a/hI+CFoLfUJOoIbRRhBZzBy4r/EE9lpbF5fabQS9IG3cnM8vViDIMgcM0Q+tZI9Fv0mAjsmSwHYZE63LDswcG5sAe2QGCYzc0WN7k2IFNPP74jt8Vd8V7PnxvP/JffwCAHi0q
