### ISSUE TITLE
[Feature Request] Expansion panel open by defualt

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [vuetifyjs/vuetify#18273]
### Problem to solve
I have a list where the user can add and remove items; each one is an expansion panel. I would like to have the panels be open by default when added to the list, then the user can close them if they wish.

### Proposed solution
A prop on `v-expansion-panel` like `open-by-default` or maybe `default="open" | "closed"`

**Comment by johnleider** [comment]
https://vuetifyjs.com/en/components/expansion-panels/#model

**Comment by SIGSTACKFAULT** [comment]
That's only helpful if you have access to the `<v-expansion-panels>`
