### ISSUE TITLE
[Bug Report][3.3.16] v-text-field slot #label with icon with tooltip doesn't work 

### ISSUE THREAD

**Issue by simonklimek** [vuetifyjs/vuetify#18270]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.3
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
tooltip doesn't work mouse over it

### Expected Behavior
working tooltip while textfield disabled
working tooltip within label slot

### Actual Behavior
not working tooltip within label slot
not working tooltip while textfield disabled

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVUtv00AQ/iuDOQSkOlZVxCFqUQFVAoQAARKHpofNepJss95d7Y6Toij/ndm149hpeUi9kpN3Xt/MN49cb7PgZfHaufG6xmySnRNWTgvCV1MDcL7OhXPpMz2kNSSUQd+KkpDwjvK5Ql3COq9sifpimlVhMc1gUqogZhpLluw/p1nnzO57OHiqxQx1p/oYX7BRtATFqM0XWatJuc49gjci0FYKUtYwEFnH0A+DCElqLch6ttuC89YF2A0ySlETpNQihFjKLD/lgKESWoO0Ojk7ryrhf7J8nc+UiQWmaEPk+NtuYVSVKl+idrlUXmocwW43QCwayH7OxaARrTA40TcCmHm7QrMnBmIr+jEG9hGlNdx39Bikz5RzaMpcmX63/zMOG+tXyiwGlMOsJjCWYLNUGpOo2Ydu5h/Rk9aoW7L+6s3IwKXUSq56CwYX8KS3bO3nIasYjh07vOO1jpJm6we58DNIrxxBQKqbdFXlrCfYgsc57GDubQUjPiSjqOSogToKOCs2ejYXOuDzg5rvRKsZvUOtLfywXpdPRmzCVCU8RspOsgYqr4Qb3wZr+FRtY5Rpq+AxmECSRBmnEN/TbEnkwqQoZGnYjU+TWvuxQSqMq4pLNit8bUhVmJe2ujwbn41fFJwx9cVjDFXOi7YJ6DnINDvpwZCa80j+Faq1TAinLxuIVpbz4QsR417sggHX6HPPi4ge/b+WdOTWL+tIda+0iM6LsmPCtTKrcMS1DInn632Sj6s5RYuhbhpECjwTc7U4BrWV47Xyn108N8NG84Gwmw9JRr7Gjj25RLl6QH4b7hoWv3hMXPQYJ+EXSI366tuneEoPSv5fq3U7VL9RfsVgdR1zbMze1KbktHt2Kdv3aV75hHwPV3eEJuyLiokm/pN9moC3fyj9kC4T3PVtd5KldjOdDe/ZzS+nIIZf)

**Comment by simonklimek** [comment]
can anybody help on how to use clickable inner or append slot to disabled v-text-field

**Comment by effhAVE** [comment]
@simonklimek Did you manage to find a solution? I'm also struggling with this and only got it to work by modifying CSS.

**Comment by klimekszymon** [comment]
> @simonklimek Did you manage to find a solution? I'm also struggling with this and only got it to work by modifying CSS.

No, I didn't manage. My workaround is instead of appending icon I place icon next to v-text-field

`
<div class="d-flex flex-wrap">
    <div class="flex-1-0">
<v-text-field />
</div>
    <div>
      <v-btn
        icon
        density="comfortable"
        variant="text"
        size="small"
        @click="$emit('emit-copy-field')"
      >
        <v-icon small>mdi-content-copy</v-icon>
        <v-tooltip location="top" activator="parent">
          <span>Copy</span>
        </v-tooltip>
      </v-btn>
    </div>
  </div>
`

**Comment by robsonash** [comment]
Alguem conseguiu resolver para o vuetify3 ?

**Comment by julian-pani** [comment]
Run into the same issue today
