### ISSUE TITLE
improve the data table view component on mobile device

### ISSUE THREAD

**Issue by sansil** [vuetifyjs/vuetify#1828]
Hi! You have done an excellent work with vuetify!

On mobile devices the columns are difficult to see. It's a better idea show only one column , and the data grouped by rows.

**Comment by johnleider** [comment]
Hey Sansil, thank you for the request. Unfortunately I have to close this for a break in the rules for posting.

When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
