### ISSUE TITLE
[Bug Report][3.3.16] v-skeleton-loader max-height doesn't work

### ISSUE THREAD

**Issue by fractalf** [vuetifyjs/vuetify#18280]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0
**OS:** Linux x86_64

### Steps to reproduce
Just go to the reproduction link

### Expected Behavior
Expect the content to adjust to given height

### Actual Behavior
doesnt happen

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUr1u2zAQfhWDsym5TdDBcIO0RYZ2aIu2W5SBli4WY/6BPMkKAr97j5TiyHISBAgn6e7jfT+86wcWfJl/cS5rG2BLtkLQTgmEi8LMhrNqediCArSGKysq8E+9eEolQvhcMN1x0aCdra2PGHaM0qLjO1lhTciPi8Vz7Rrkpkbqny9cNwXgvQNqKRmQS1LJRStQHNFcrPITqeRjlR9MsTmT2lmPXAuX3QVryPNDnFAMjVCw5SxVYo1Cif8FqxFdWOZ5WRm6VoGSrc8MYG6czi8JlvvGoNTAK6svz7Kz7DyvSOq4nEHQfO3tLoCnIQWbj2hQ3t6/gWpAJoYPn3qKocaVWIfIcTI7J8IWPPdgKJH4NG+zNLk2tjVpnViL7PvC7ClwJc02TLIuQ8r5+lHk+zynaXHUTc+IobTmVm6mpFY7qcD/ciitOX5ooZTd/Ug19A0c0itrKLfP1O8CLWhM8beHlMUocdrKDWDfvvr7Ezr6PjS1rRo1LNULzT8QrGqixh72tTEVyR7hktrvaV+l2fwLVx2CCY+motCUf8KnDfj2ivUnuRTw4d32c5aem+Lsc2c3/wEnrlnK)

**Comment by randompixel** [comment]
I think `v-skeleton-loader` defaults to an `image` type and that currently is set at 150px. The max-height is set on the `div` element that wraps this but doesn't seem to be able to contain the child. Neither `height` or `max-height` seem to make any difference.

<img width="226" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/2316601/49277f63-9968-44cf-8c2d-d90a580a3063">

**Comment by ezegyfa2** [comment]
Still doesn't work

**Comment by fractalf** [comment]
..probably never will
