### ISSUE TITLE
[Bug Report][3.3.17] Custom component v-model buggy

### ISSUE THREAD

**Issue by SimonDahrs** [vuetifyjs/vuetify#18289]
### Environment
**Vuetify Version:** 3.3.17
**Last working version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Edge 116.0.1938.69
**OS:** Windows 10

### Steps to reproduce
1. Create a custom component that has some form input component, i.e. `v-text-field`.
2. Implement the two-way v-model binding as described per [Vue docs](https://vuejs.org/guide/components/v-model.html):
 1. Set the value to the `modelValue` prop.
 2. Set an @input event handler that emits a modelValue event with the new value.
3.  Use the child component in a parent component and set v-model to some data field.

### Expected Behavior
If I type `abcd` in the `v-text-field`, I expect it to show `abcd`.

### Actual Behavior
The text does not show. If you type a character **twice** it does show once. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVVtP2zAU/itehFSQmkQDpEmlVOzCAzywaZsmTQRNJjltDY6d2U5oVfrfd2zn2iKEtL7U5+Jz+c7xl9tNoFUafyyKqCohmARTA3nBqYFZIgiZViEtCnd0QiqFoUyAqlWovKE5XImiNI3G/iZzBjw7T4K+ctMXCOH0HviEjH7LUhGBUUbjoQOssBCbDJ0uhQFF1tZ1zpQ2hIoMI+DhpZt4L4Wl5Jm7ey2XgnyRe16q5KAn5HaoJaQi5zPyriLPz6SKOIiFWZLZOTm2ipFtl+QlJr4HQg3hYIs4JumSKppikXo0jHc3yLrthCE4VZjLDDhCZhvqbHEDfryLvtX44Uzj3tBQ1KlihSEosLyQypB2RmSuZE5GUdxq7NhHZ4lAsK1nBnNacuNnlUq8LkAYRGnT3ti6hjJq6OFRM1MFplSim7DtYUJEyXnbPZc0Y2IxIXPKNdRqB4cNiIdp7OvGsoNx4CsPc1pED1oK3EwXPKkNOgmwJh8kCbAHKyfB0phCT+I4zQReQzxZpSIBJhZFHl+gW6xKYVgOYSbzi5PoJDqNM6ZNXx2BzsN7JZ80KAySBHWtLo1h8/UbUtWeLsP7Dz5FrQtx77XNsRc7xoQVqFCBwMUF9daWdq7129ox7bXm4Ef0EXDOxKPewTrVDuf6hfxvzy6aDXXnMxqNCz1ni92kuHWMg/paGCbFcNCUc/l07XRGlc0W4Z0lpI8v6B/0yqP4TYHDooe4oWoBxpsvf9zACs+tER8jssOrxu+gJS9tjd7tUykyLLvn56q9cvuKm/9TX64MCN00ZQtt1r/egM+vtN6ViwD35mbpe/CahySurOtm4/g4ahl1u/UGpHSDvYXO7FWOvivKS0Aucpz0ywo4uc7sqBvNPqqTBnbHrK3dSQN7j59br56u75siydtQ+To87esV/C2Zgl7RFVWMCoO+OAhQuM9o7d24YBYhNB9AzszhqCyQw2DStTgakwOokO4ij3XkUDhqYsws4XZoOWj7zIuiUzUshuc9UnWBPDkmQfflxJVxlkJJfF/43gbAj9HXDyjAj4lztB14x70uOqeWomsIWpJuIbHd/HGw2HraMnC3zvwJdxP/3bJ09Nw2atYcCD7iAjwatZtVz4LtOHBEhCvqGSG4+wfcKbkC)

**Comment by KaelWD** [comment]
v-model on components is modelValue/update:modelValue not value/input

**Comment by SimonDahrs** [comment]
> v-model on components is modelValue/update:modelValue not value/input

Then why does it work fine in 3.3.13?

**Comment by KaelWD** [comment]
#15904 probably, binding value to v-text-field is never expected to work correctly though.
