### ISSUE TITLE
fluid statement is not bind to boolean on v-container

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#183]
Hi,
just a small issue: currently the `fluid` statement is not a real boolean, its not possible to write `:fluid="false" => true`
```javascript
const Container = {
  (...)
    if (data.attrs && typeof data.attrs.fluid !== 'undefined') {
      staticClass += ' container--fluid'
      data.attrs.fluid = undefined
    }
(...)
  }
}
```
The same would be nice for `xs(1-12)` statements to make them as boolean. then conditionally it could be:
```html
<div :xs6="hasSideContent" :xs12="!hasSideContent">

</div>
```

**Comment by johnleider** [comment]
Grid components are currently functional and would not support dynamic binding. I see the use case, I wonder if the performance hit is worth it.
