### ISSUE TITLE
[Bug Report][3.3.17] v-intersect's isIntersecting is always true when used with autocomplete/select's append-item slot, instead of only while at the bottom of the list

### ISSUE THREAD

**Issue by mihailo-obradovic** [vuetifyjs/vuetify#18301]
### Environment
**Vuetify Version:** 3.3.17
**Last working version:** 2.6.15
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Linux x86_64

### Steps to reproduce
Try using the v-intersect directive with the append-item slot of v-autocomplete or v-select.

### Expected Behavior
I used this combination in Vuetify 2 and it worked great. The intersection would trigger when reaching the end of the list, and that allowed me to write code based on it, such as sending follow-up requests on paginated endpoints.

### Actual Behavior
In Vuetify 3, the intersect triggers twice. First when opening the list of records, and then again after reaching the bottom of the list.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1lMFymzAQhl9lTQ84ExtbthMnniQznV7aay89xJkMhbWjGVliJMHFw7t3QYQC214MaD/+XT6DXq+Rs9nqa1EkVYnRIXryeClU6vHlqAGeqmVaFO1pe5EZ7VOp0XZLgSi9yQzdhR6hWl5Mjur5GDlUmHnMf2JmbH6M4CAp21HFtivuGPUplPPZF75QR9T5sqEHACG5rChfnihiNutCEoX67D8onirao3XUlICPVOcKf3yuSKMJWQ0brkZPGpbGD0OFvuSKVL9AnweZKZvzA1yv0Pf9FhahrimrvaMzR8FjdW2r1uxoDrp0mZWFB4e+DOLlpTDWwxUsnqCGkzUXiOnPisN0lOsafCgbnht4Hn9HpQz8Mlbls/hmyHf2OvA1jElPkh9ALMBLr/AAcaBAxFAvhsiGIZspsmXIdorsGLKbIncMuZsi9wy5nyJ7huynyANDHqbII0Mep4hYc3drBv1DMDMsuGLBHAsuWTDLgmsWzLPgogUzLbhqwVwLLlsw24LrFsy34MIFM77hxje98bfRK8++0vDurzvoVOp2mwC+c8zfUXsr0S3g3fx2aCu0C5DuL6PPN3ANc8kTzP9TCpMYhYky53ncDwQUfj6jxbz5SAM5nTapUlXi7W2o182BfmiXabcL2iiiehFtk22yi8JR7KO3P/bu0F4=)

### Other comments
You can check the console log and the counter. Intersect triggers immediately when opening, and then again each time you reach the bottom or go back to the top of the list. It's like `isIntersecting` is always true when the directive is called.

**Comment by KaelWD** [comment]
It's the same in v2: https://codepen.io/kaelwd/pen/qBLpPMX?editors=1010

**Comment by mihailo-obradovic** [comment]
> It's the same in v2: https://codepen.io/kaelwd/pen/qBLpPMX?editors=1010

Thank you, @KaelWD, I forgot one important detail while writing the demo code. I didn't include the `isIntersecting` check. In Vuetify v2, that condition is true only when you reach the bottom of the page. But in Vuetify v3 it seems to always be true. I updated the playground link and the description.

**Comment by KaelWD** [comment]
isIntersecting is now the first argument: https://vuetifyjs.com/en/getting-started/upgrade-guide/#v-intersect
