### ISSUE TITLE
Nested lists - children inside children inside children items

### ISSUE THREAD

**Issue by jakub-wisniewski** [vuetifyjs/vuetify#1830]
I am trying to create nested list with more then two level of nesting. When I put children object of items inside child item in v-list it doesn't display anything.

Is is even possible to create such nested list in vuetify? If no, what solution could be to solve this problem?

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
