### ISSUE TITLE
[Bug Report][3.3.17] VDatePicker typescript Declaration problem for v-model

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify#18309]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Juste set the prop reference to other type than an array and you have TSError on VDatePicker v-model.

### Expected Behavior
Works without error because the result of the v-model is not an array if vDatePicker is not in multiple mode

### Actual Behavior
Force to use an array type for vModel. But in simple mode, the model is directly a Date object. We can't pass a simple Date or string to the vModel without an error. Why ?

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUctuwjAQ/JWtL00kkrSiUiUakJB66akHjsDBTRZwcWzLXoIQ5d9rO0DSnryemd3Zx/LMnK2KuTF5e0A2YSVhYyQnnK0UQNlm3JgYxk+lFXGh0F6hCNZenRlR7dHeUIA2a3SNcrpiDiVWhPW7l61Yr/Bwy0lo5TVPQ2KPpy/NbZ0Jb+fJIbcTNWa8CmmuR91OHzNef/MKFXljRbs7W9y6L/63H5BuurIYTO2/rrLCEDikgwHJ1dZ3QW7FrqVEY7QlOMORU7WDC2ysbuDRL/DxLSjuvMXNHzYUDwV8Hy6U7xcD0yAuY/gD4VmuZ0nqy3UZ0SkZZowgabk84CSq70kpTGdwvg9fQBSBcKA0AVfAreUnEBt/ocHhbgKhoDlIEkYihAPeCnl98jAPqblw8e3c07Q3i3aC4Kjt3sHG77lnwsRaYi71tkvMSX8sPhdkhdomaRi0E1664BKQsugO4dfOLiM2zsf5C+ve51e2/gUOu9tl)

**Comment by throrin19** [comment]
Really ?

**Comment by KaelWD** [comment]
c48c2a797f96b2bcab26c75c3b3780b3c3b3b64b
