### ISSUE TITLE
[Bug Report][3.3.17] Extending a component results in loss of styles

### ISSUE THREAD

**Issue by MarcHartwig13** [vuetifyjs/vuetify#18305]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Mac OS 10.15

### Steps to reproduce
When extending a vuetify component with `defineComponent` and passing in a new name you lose some vuetify default styles.

```
<script lang="ts">
import { VBtn } from 'vuetify/components';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'MyBtn',
  extends: VBtn,
  setup: (props, context) => {
    return VBtn.setup?.(props, context);
  },
});
</script>
```
```
<button data-v-7a7a37b1="" type="button" class="v-btn v-btn--elevated v-theme--light my-btn--density-default my-btn--size-x-small my-btn--variant-elevated">
  <span class="v-btn__overlay"></span>
  <span class="v-btn__underlay"></span>
  <!---->
  <span class="v-btn__content" data-no-activator="">Extra small Button</span>
  <!---->
  <!---->
</button>
```

Vuetify changes only some of the class names based on the `name` property. `density` and `sizes` seem to be effected. In the above example `v-btn--size-default` turns into `my-btn--size-default` so I've now lost that default styling because vuetify's sass still outputs thinking the class should be `v-btn--size-default`

It's also confusing that only a select amount of classes are changed. The class `v-btn` remains and is unchanged. And scss in vuetify is hardcoded to `.v-btn`

Relevant vuetify files are:
`vuetify/lib/composables/size.mjs`
`vuetify/lib/composables/variant.mjs`
`vuetify/lib/styles/tools/_variants.scss`

### Expected Behavior
I expected extending a vuetify component with a new name to not change vuetify classes.

If classes will dynamically change then I expect the scss/css to change with it.

### Actual Behavior
The name property is being used to change the classes added to the html. This results in loss of styles.

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-a2lpxc?file=src%2Fcomponents%2FMyBtn.vue](https://stackblitz.com/edit/vitejs-vite-a2lpxc?file=src%2Fcomponents%2FMyBtn.vue)

### Other comments
It's hard to understand why a class name was made dynamic and also why only in select places in the scss we can pass in a dynamic `name` property where in other places the name has been hardcoded. 

I think we should drop the dynamically changing class names. Leave everything based off of what vuetify has established for the component name. Then let the developers extending vuetify add and establish their extra styles if need be.

If vuetify is dynamically going to change the classes then all the classes should dynamically change. Then there should be a sass function/mixin that provides an easy way to pass in the new name of the componet to modify the scss/css output.

I currently have a hacky work around to get all the styling back based on my name change. But it requires copy and pasting mixins out of vuetify to change hard coded classes. 

```
<style lang="scss">
@use 'sass:math';
@use 'sass:map';
@use 'sass:meta';
@use 'vuetify/settings';
@use 'vuetify/tools';

@mixin button-sizes(
  $map: settings.$button-sizes,
  $immediate: false,
  $name: 'my-btn'
) {
  @each $sizeName, $multiplier in settings.$size-scales {
    $size: map.get($map, 'font-size') + math.div(2 * $multiplier, 16);
    $height: map.get($map, 'height') + (settings.$size-scale * $multiplier);

    #{if($immediate, &, '')}.#{$name}--size-#{$sizeName} {
      --v-btn-size: #{$size};
      --v-btn-height: #{$height};
      font-size: var(--v-btn-size);
      min-width: tools.roundEven($height * map.get($map, 'width-ratio'));
      padding: 0
        tools.roundEven(math.div($height, map.get($map, 'padding-ratio')));
    }
  }
}

@mixin button-density($properties, $densities, $name: 'my-btn') {
  @each $density, $multiplier in $densities {
    $value: calc(var(--v-btn-height) + #{$multiplier * settings.$spacer});

    &.#{$name}--density-#{$density} {
      @if meta.type-of($properties) == 'list' {
        @each $property in $properties {
          #{$property}: $value;
        }
      } @else {
        #{$properties}: $value;
      }
    }
  }
}

$name: 'my-btn';

$button-variants: (
  settings.$button-background,
  settings.$button-color,
  map.get(settings.$button-elevation, 'default'),
  settings.$button-plain-opacity,
  $name
);

.v-btn {
  @at-root {
    @include button-sizes();
    @include button-density('height', settings.$button-density);
  }

  &--stacked {
    @at-root {
      @include button-sizes(settings.$button-stacked-sizes, true);
      @include button-density('height', settings.$button-stacked-density);
    }
  }

  &--icon {
    border-radius: settings.$button-icon-border-radius;
    min-width: 0;
    padding: 0; // ensure that default
    // v-icon size is 24px
    & .v-btn--size-default {
      --v-btn-size: #{settings.$button-icon-font-size};
    }

    @at-root & {
      @include button-density(
        ('width', 'height'),
        settings.$button-icon-density
      );
    }
  }
}

.my-btn {
  @include tools.variant($button-variants...);
}
</style>
```

**Comment by KaelWD** [comment]
When we do that internally we use `aliasName: 'VBtn'`: https://github.com/vuetifyjs/vuetify/blob/47ac84c1e0ecf0db324e350b357b3bf8c9ccd330/packages/vuetify/src/util/getCurrentInstance.ts#L21

Note that this is not a supported use case though so don't get mad if it breaks at some point. If you're just renaming components without adding anything you should use [aliases](https://vuetifyjs.com/en/features/aliasing/) instead. 

> It's hard to understand why a class name was made dynamic

Because this
```js
useVariant(props)
useDensity(props)
useRounded(props)
useSize(props)
```

is better than this

```js
useVariant(props, 'VBtn')
useDensity(props, 'VBtn')
useRounded(props, 'VBtn')
useSize(props, 'VBtn')
```

**Comment by MarcHartwig13** [comment]
Thanks for the response @KaelWD. `aliasName` does work for me but unfortunately it doesn’t seem like a viable option as it isn’t supported.  

I figured out a workaround. I think using the composables directly in a setup function is the best route for me to take to resolve this issue. Here is my reproduction: https://stackblitz.com/edit/vitejs-vite-nxgst9?file=src%2Fcomponents%2FRawrBtn.vue  

I plan on consolidating all the Vuetify composable calls into one composable file on my end to make it easier to make the changes in all the components I’m extending.

---

I understand that `useVariant(props)` is shorter than `useVariant(props, 'VBtn’)` but if the Vuetify mixin allowed for the name to be passed through then I would be able to import the Vuetify mixin into my component and pass it the name I’d like it to use for the styling. Then if/when Vuetify updates that mixin code nothing would break on my end when updating to the new version of Vuetify. I believe the case I outlined above illustrates that `useVariant(props, 'VBtn’)` is the better option than `useVariant(props)`. 

---

A couple of follow up questions:  
- Is it recommended to use wrapper components to maintain Vuetify styles, as opposed to extending components? If so, are there performance implications?
- What is the preferred way of extending a Vuetify component while maintaining the styling?

**Comment by MarcHartwig13** [comment]
@KaelWD I realize I misspoke when talking about `useVariant` I thought you were referencing the SCSS mixins. My proposal is for component specific mixins to pass in a `name` argument as its currently hardcoded to the vuetify class name. So the `button-density` mixin would go from:

```
@mixin button-density ($properties, $densities) {
  @each $density, $multiplier in $densities {
    $value: calc(var(--v-btn-height) + #{$multiplier * settings.$spacer});

    &.v-btn--density-#{$density} {
      @if meta.type-of($properties) == "list" {
        @each $property in $properties {
          #{$property}: $value;
        }
      }
      @else {
        #{$properties}: $value;
      }
    }
  }
}
```

to:

```
@mixin button-density ($properties, $densities, $name) {
  @each $density, $multiplier in $densities {
    $value: calc(var(--v-btn-height) + #{$multiplier * settings.$spacer});

    &.#{$name}--density-#{$density} {
      @if meta.type-of($properties) == "list" {
        @each $property in $properties {
          #{$property}: $value;
        }
      }
      @else {
        #{$properties}: $value;
      }
    }
  }
}
```

Because when extending and changing the name of a vuetify component the composable changes the density classes from `v-btn--density-compact` to `my-component--density-compact`. So if the mixin passed in a `name ` argument I could import it into my extended component and pass in my new name to get the styling back.

**Comment by azygis** [comment]
@KaelWD can you please either reconsider the issue or explain how exactly one could solve this without vuetify library changes?

In our case, we are extending the components to set some defaults like density/elevation/variant etc. There's no reason to roll out our own styling for these components, we were under the impression that extending the components would be enough (like it was in v2).

I see what you guys do with `aliasName`, but it's pretty clear you can change it at any time as it's basically for internal use.

Thought maybe setting `aliases: { MyButton: VBtn }, defaults: { MyButton: {} }` would help; it does, but we lose all the typings for these components, and can't reference them as dynamic components.

Is there a way to reopen the issue with a plan to make it possible to NOT use the component name, OR set the aliasName which would be future-safe?
