### ISSUE TITLE
[Feature Request] Multiple values cannot be specified for item-title in v-auto-complete.

### ISSUE THREAD

**Issue by nayo0513** [vuetifyjs/vuetify#18313]
### Problem to solve
https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQREVpSX5yPlBXakkqTFhBIScxKTXHNkbJEVlWCSFvlQm0qRioAEwjy4AEdEsyS3JSgbJpmUXFJfF5ibkomsFKyhJzSnErKUotKS3K081PykpNLoEJ29noo7qXlv4Ay8A9Eq2ekwh1prqOOsLN6rGYemA+I04PST4FCaPGIlghOJJt9JEiH8gtTi7KLChRKAaaD0kDQI3FJeDAL1awVYiGmFgNDCKou6wU1J/NmP+yvU9dRwHhWqDo46ZFj5uWqCvU6hCv51nL7Cc7W4Hks63bSdP5fOKC5/v6XixcjFPbnM6Xy9ZgOLKx+3HjKlx6Xu6e9HT7XEw9TWBta2HaYkHBCAk4YJAp1eooGesZ65koQWhDc6VYAE9aL6M=

### Proposed solution
The feature is useful when you want to display multiple values, such as a person's name.

**Comment by yuwu9145** [comment]
`item-title` accepts a function where to customise its value to display multiple values. [demo](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQREVpSX5yPlBXakkqTFhBIScxKTXHNkbJEVlWCSFvlQm0qRioAEwjy4AEdEsyS3JSgbJpmUXFJfF5ibkomsFKyhJzSnErKUotKS3K081PykpNLoEJ29noo7qXlv4Ay8A9AuIo2NqBna6Xkwh1sYK2gjoQakOE6eNZkDBqRIIVguPZRh8p/oHc4uSizIIShWKg+ZBkANRYXAJ2UrGCrUI0xMRqYChBXWWloP5sxvyX7X3qOgoItwJFHzctety0RF2hVod4Pc9aZj/Z2Qokn23dTprO5xMXPN/X92LhYpza5nS+XLYGw5GN3Y8bV+HS83L3pKfb52LqaQJrWwvTFgsKRkjAAYNMqVZHyVjPWM9ECUIbmivFAgCmLDAd)
