### ISSUE TITLE
How can I get the current index in Carousels?

### ISSUE THREAD

**Issue by canhongpoxiao** [vuetifyjs/vuetify#1831]
### Steps to reproduce
How can I get the current index in Carousels?

### Versions
0.15.7

### What is expected ?
I want get the current index in Carousels.

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is exclusively for bug reports and feature requests. For general questions, please join the Discord chat room.

https://github.com/vuetifyjs/vuetify/blob/dev/.github/CONTRIBUTING.md
