### ISSUE TITLE
[Bug Report][3.3.16] v-btn width and rounded attributes doesn't work properly

### ISSUE THREAD

**Issue by fractalf** [vuetifyjs/vuetify#18317]
### Environment
**Vuetify Version:** 3.3.16
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0
**OS:** Linux x86_64

### Steps to reproduce
Follow link..

### Expected Behavior
Expected the width to be less and rounded to actually work

### Actual Behavior
Doesnt work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSrJUyjPTCnJsI1RMjSIUVIoyi/NS0lNgXLtKmz0wYqIUI+q2kYfySqlWh0lYz1jPRMlCG1orhQLAIRkMIc=)

**Comment by 3aluw** [comment]
the accepted values are only the ones are used in[ border-radius property ](https://vuetifyjs.com/en/styles/border-radius/), which are: 
```scss
$rounded: map-deep-merge(
  (
    0: 0,
    'sm': $border-radius-root * .5,
    null: $border-radius-root,
    'lg': $border-radius-root * 2,
    'xl': $border-radius-root * 6,
    'pill': 9999px,
    'circle': 50%,
    'shaped': $border-radius-root * 6 0
  ),
  $rounded
);
``` 
I believe it's necessary to enhance the type constraints for the "rounded" composable to ensure a more stringent typing. Currently, it accepts a wide range of types:
`type RoundedValue = boolean | string | number | null | undefined`
The type should become something like : 
`type RoundedValue = boolean | 0 | 'xl' | 'sm | 'lg' | 'pill' | 'circle' |  'shaped' | null`
Can a maintainer give us a clue on this ? is there a ts types file for scss variables ?

**Comment by KaelWD** [comment]
> is there a ts types file for scss variables?

No. Custom values can be added to that map too so we can't really go more specific than this.

**Comment by fractalf** [comment]
@KaelWD Why would you close this? 

I want to be able to set a width that is **less** than default. Right now I have to take a deep dive into weird css selectors etc etc

Setting `width="10" should reduce width. I'm not talking about min-width, don't understand why you mention that..
