### ISSUE TITLE
[Bug Report][3.3.17] VSelect incorrect z-index when used with a v-dialog wrapper component created in another library

### ISSUE THREAD

**Issue by MJB52** [vuetifyjs/vuetify#18320]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Create a library that leverages vuetify. See https://github.com/MJB52/vuetify-lib-example for example
- Create an application that leverages that library. See https://github.com/MJB52/vuetify-issue-reproduction
- Use a component from the library that wraps the v-dialog vuetify component
- Use a v-select in combination with the v-dialog wrapper component

### Expected Behavior
The v-select dropdown content is rendered in front of dialog 

### Actual Behavior
The v-select dropdown content is rendered behind dialog 

![image](https://github.com/vuetifyjs/vuetify/assets/42855565/1e202e77-feca-46f1-9006-71e41942a5fb)

### Reproduction Link
[https://github.com/MJB52/vuetify-issue-reproduction](https://github.com/MJB52/vuetify-issue-reproduction)

### Other comments
This functionality works when the v-dialog wrapper component is defined locally in the application so I would expect it to have the same behavior when the v-dialog wrapper component is defined in another library. 

If there is a v-select wrapper component defined alongside the v-dialog wrapper component and they are used in combination, the v-select dropdown content will be rendered correctly

Stackblitz here: https://stackblitz.com/edit/vue3-vite-starter-z73sje?file=src%2FApp.vue

**Comment by KaelWD** [comment]
rollupOptions.external works on module ids, not package names. You need to use `/^vuetify(\/.*)?$` instead to prevent components from being included in the library bundle.

**Comment by MJB52** [comment]
That worked! Thank you!
