### ISSUE TITLE
[Bug Report][3.3.17] hidden-xs-only not working

### ISSUE THREAD

**Issue by xiaofengorz** [vuetifyjs/vuetify#18326]
### Environment
**Vuetify Version:** 3.3.17
**Last working version:** 2.0.0
**Vue Version:** 3.3.4
**Browsers:** Edge 117.0.2045.36
**OS:** Windows 10

### Steps to reproduce
Resize the window to <600px.

### Expected Behavior
Hide the element when window size <600px.

### Actual Behavior
The element with "hidden-xs-only" doesn't disappear.

### Reproduction Link
[https://jsfiddle.net/Ltk24a38/1/](https://jsfiddle.net/Ltk24a38/1/)

**Comment by KaelWD** [comment]
This was changed in #13318
