### ISSUE TITLE
[Bug Report][3.3.17] otp-input's @finish event not triggered if length prop is provided

### ISSUE THREAD

**Issue by mattduf** [vuetifyjs/vuetify#18327]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
Set length="4" for example and fill the input. In my reproduction link this is supposed to trigger a loading to illustrate @finish event. However, it won't, unless you remove length property and refill the input.

### Expected Behavior
@finish event working, even if length property is provided

### Actual Behavior
@finish event doesn't work if length property is provided

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplkNtqwzAMhl9F+CYtNIethUFJwsZgT7C7ZRfBcTqDYxtbDoyQd58PCSv0ypI+yfp/fS3EGlq+aV3MjpErqZFNWvTI2k4C1HOuUOdcaochB5jzSQ1MNB3RvbXvPu5IIoLJG/54cNkrV6H6gcubr23RTl5HLrkNzUp+xDCRti7vNnoJdXmnx6eWGq4RLEOno0I+aWUQFjBshBVGoybIvJUsQKqkRdiFQhOaDll2/Gebrg2NvbDM08BHJylyJWFXeDjCsjlNQ8XcCxd+ReNYIl7XJ5+Ycnjw7U27TzzOxFUJrid4rqoqqlqD5WRyM4y/goGlSrMBRB+Paam1HfG3itD3kfVEzsW5uJD0Pr2Q7z9oNJrp)

**Comment by KaelWD** [comment]
It works if you pass a number instead of a string

**Comment by PasitTi40** [comment]
It works  if I pass a number, however when I use the onFinish event to call the API, it calls the API multiple time and not call onFinish function
