### ISSUE TITLE
[Bug Report][3.3.17] Click on expanding v-autocomplete throws error

### ISSUE THREAD

**Issue by vojke98** [vuetifyjs/vuetify#18328]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Opera 101.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click v-autocomplete before transition ends

### Expected Behavior
v-autocomplete input get focused when clicked

### Actual Behavior
Error gets thrown:

index-a9fbd410.js:846 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at Object.on_error (index-a9fbd410.js:846:226)
    at ewt.handle_repl_message (index-a9fbd410.js:830:1066)
    at handle_event (index-a9fbd410.js:830:122)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU22L2zAM/ivCDHoHS9rRlkHWu21f9gf2cR2cL1ZWg2MHv6RXSv77ZCdp0nCDfbItPXokS49+XZmz5fp70+RtQFawg8e6Udzj81EDHNqMN026jo/sldvBQCYhWygVd+7pyERWKXwD5A6zsxT+dGRQOH9RSM4rJFMBLx+u6dY1by/QHdmNq08QvCkNVYAeJwdAUaMOmSyNJi7pfpgyOBTwFVa1kFlyCnPWKyhAB6WObB78rTaERu3RUnTKDk+w3Wzeg5n2f1AKeRu/NcLmJVEIlbHbL+KqCKCQdD48LryvKsS08Vj6aBwlnowSqbCfyG15glbi2d3jWm4l154wziiTVVIpFPcQgdpJfyFIbDIv/SKTxQa1yKTWaMdupwbzP1pWl3u0NUELyjAznaTATKDnUrnJ/nxY30920s+aBDTKK4Jm+hredD+sZ6KkpyutbDw49KHXpqwbYz1cwWIFHVTW1LAiPa8iHID+4XyvPxoVYR52+8fJMc2ud1ZcOSR/RFRBl14aDcPU4NoXe4vJW64CUqS3YVBsSnSzRwGRuVvw9YP+N10q4j0+0lVPd1j3fRh6EvcsNSOfFnCk95bHuVPeYmjDJt+7flOlzkzwXybSgYh1H9k23+Y71p+fPrPffwEU50yj)

### Other comments
It works fine when you click (set focus) after transition ends

**Comment by KaelWD** [comment]
The underlying error is "ResizeObserver loop completed with undelivered notifications"

Does this happen on an actual page? I can't reproduce it outside the playground.

**Comment by vojke98** [comment]
> The underlying error is "ResizeObserver loop completed with undelivered notifications"
> 
> Does this happen on an actual page? I can't reproduce it outside the playground.

Yes, it happens on the actual page. 

Check this git repo for reproduction (screenshot included):
https://github.com/vojke98/vuetify3-bug-reproduction.git

**Comment by KaelWD** [comment]
Ok seems to only show up if you have a `window.onerror` handler set. I can't get the warning to go away completely, we already have a check here that prevents actual loops: https://github.com/vuetifyjs/vuetify/blob/1224416f6a2d69b375b63e6b9d198654ca21fc58/packages/vuetify/src/components/VOverlay/locationStrategies.ts#L231-L234

If the webpack overlay is a problem you can disable it: https://webpack.js.org/configuration/dev-server/#overlay
