### ISSUE TITLE
Multiple clear icons on select with preprend-icon

### ISSUE THREAD

**Issue by tsauvajon** [vuetifyjs/vuetify#1833]
### Steps to reproduce
Create a `v-select` with a `prepend-icon` and the `clearable` property

### Versions
Latest versions as of today (21/09/2019):
Vue v2.4.4
Vuetify v0.15.7

### What is expected ?
The `clear` icon should be displayed on the left or the right side only, not both

### What is actually happening ?
There are 2 `clear` icons

### Reproduction Link
https://codepen.io/tsauvajon/pen/boemYM

**Comment by jacekkarczmarczyk** [comment]
It's already fixed on dev branch
