### ISSUE TITLE
[Bug Report][3.3.17] Vuetify memory leak in Nuxt SSR when theme is defined

### ISSUE THREAD

**Issue by oemer-aran** [vuetifyjs/vuetify#18339]
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. `yarn build`
2. `yarn inspect`
3. open `chrome://inspect/`
4. click `inspect` on `./.output/server/index.mjs` item in `Remote Target` section.  This should open the dev tools in the correct screen (Memory tab). Take a look at the number below `Select JavaScript VM instance`
5. run `npx artillery quick -c 30 -n 100 http://127.0.0.1:3000` 
6. (run 5. multiple times to see that memory is always going up an never goes down)

### Expected Behavior
JS heap size is gradually going down. If not, running GC manually should reduce heap size usage properly (trash icon in dev tools).

### Actual Behavior
After each run with `artillery` the JS heap size is increasing and staying up. Each run will increase it even further.

### Reproduction Link
[https://github.com/oemer-aran/nuxt-vuetify-memory-leak](https://github.com/oemer-aran/nuxt-vuetify-memory-leak)

### Other comments
To fix this issue you have to comment `theme: {}` option in `/plugins/vuetify.ts` in the reproduction.
I can currently not migrate our Nuxt 2 app to Nuxt 3 because of this.

Related issues:
https://github.com/vuetifyjs/vuetify/issues/16156
https://github.com/vuetifyjs/vuetify/issues/17917

**Comment by nilsalex** [comment]
I have the same issue. I also thought that disabling the custom theme options (as you described) solved the problem, but I found that the heap just grows slower. The arrays mentioned in https://github.com/vuetifyjs/vuetify/issues/17917#issue-1827885985 are still leaked. Are you sure that you do not see a leak anymore?

**Comment by oemer-aran** [comment]
> I have the same issue. I also thought that disabling the custom theme options (as you described) solved the problem, but I found that the heap just grows slower. The arrays mentioned in [#17917 (comment)](https://github.com/vuetifyjs/vuetify/issues/17917#issue-1827885985) are still leaked. Are you sure that you do not see a leak anymore?
> 
> Update: I had a look at your reproduction and I could **not** find leaked arrays. So I guess that's a different problem but not relevant here :-) Sorry!

I am having memory leaks still also in my nuxt 3 app, it's really frustrating right now. It's als really hard to debug memory leaks. But this was by far the biggest leak and once i fixed that, everything was already working way better.
