### ISSUE TITLE
[Bug Report][3.3.15] Loader not displayed anymore on VTextField

### ISSUE THREAD

**Issue by lvdd-rbl** [vuetifyjs/vuetify#18333]
### Environment
**Vuetify Version:** 3.3.15
**Last working version:** 3.3.14
**Vue Version:** 3.2.41
**Browsers:** Opera 99.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on the checkbox

### Expected Behavior
The loader appears

### Actual Behavior
The loaders does not appear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUsGOmzAQ/ZWRLyRVIIl2q0ooG6n39tTekhwcMwFUYyN7oFmt8u87GEggWi7Yb2bezHuew4fwTq1/1nXSNihSsSOsai0J90cDsGtjZQ3J0qCDi27KLMB9oED172yv8ZkMtHFlM9RvR6EaT7Y6CtDyHIBfVmalyY9iv1vPq5jrzkZ4pfhSos56CCaUrdQNHsUYGIn/vtcIqpBOKkLngWx3MzkCFQia2/LQymrrJrXDMMOVlSosrOZMJvxD0hHQe80ZSZKMVYNkHnP0hmfz2lLa97jHg5Da2dyh97Fm06R7xABSHrRscWLSLBrkxkEsp4w8T0lBT8cw19V98uytbginWIFlXhDn/5jnliZDNq0qDct5BMITPSl4yF/PdqMDpu/WL0z3xOPGMDKr4atXrqwppOK1tmx3hhfZaIKPnjOTJFNYLOFtD4sB413oTEkhilYj0juYwkVqjwN6W/KhPypb1WxFlo68/NaDLOa+YwAOqXEGfksqEnZjsd1sVrw/pU9Cz0SjyamAb7DdLMeq22OK7hW+JDxE6Jx10Qqi/9IZ3qju6BuleITodAgNL9pyeeg2TgdreN0sT8+t+v+tM/RuobitxEvykryK/r/9Lk6f1jos1w==)

### Other comments
This is an example from the [docs](https://vuetifyjs.com/en/components/text-fields/)

**Comment by KaelWD** [comment]
`absolute` is redundant.
