### ISSUE TITLE
[Bug Report][3.4.0-alpha.1] [Vuetify] Could not find injected layout

### ISSUE THREAD

**Issue by hakimov-dev** [vuetifyjs/vuetify#18337]
### Environment
**Vuetify Version:** 3.4.0-alpha.1
**Vue Version:** 3.3.4
**Browsers:** Yandex 23.7.5.734
**OS:** Windows 10

### Steps to reproduce
When i add the bar component bar component shows me that bug.

### Expected Behavior
Working vell.

### Actual Behavior
Error: [Vuetify] Could not find injected layout

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjE0KwjAQha8SZm0mlnZVYsFzGBdjHTAQ45DGbMS7G9tSunrf4/1cPjCl0ZxFsLwZerCZnxIo8+CiUvbuywwViyYRfaOkeg5cKPtXPDloHAzWbOEyM8vOmt1btdOYvORaX8FF+B6gxRY7+GuHR01BHoQNXH98NTF1)

**Comment by KaelWD** [comment]
It doesn't work without v-app or v-layout

**Comment by KentuckyMC** [comment]
How to handle this in unit tests? Where we have to isolate things like this? So an app-bar without the v-app or v-layout around it in that component?

**Comment by plastichotsprings** [comment]
> How to handle this in unit tests? Where we have to isolate things like this? So an app-bar without the v-app or v-layout around it in that component?

Did you ever figure this out? I'm trying to do exactly what you're talking about - unit testing v-footer in my case - and I'm getting this injection error and my tests are failing.

**Comment by lokeswari9** [comment]
This is an issue in unit test cases when we have isolated components it throws this error [Vuetify] Could not find injected layout. I am trying do to something like this 
const vuetify = createVuetify({
      components,
      directives,
      provide: {
        layout: () => ({})
      }
    })
const component = mount( {
        template: '<v-layout><Login /></v-layout>'
      },
      global: {
        plugins: [vuetify]
      }
    })
If i wrap my component around the VLayout or VApp then my actual component is not available in the test case methods throw errors saying it is not a function
