### ISSUE TITLE
[Bug Report][3.3.17] loadingText, color props are not working in VDataTableServer

### ISSUE THREAD

**Issue by yatendra121** [vuetifyjs/vuetify#18335]
### Environment
**Vuetify Version:** 3.3.17
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows

### Steps to reproduce
Just check it.

### Expected Behavior
Show a loading message. And loading progress has a color that I have assigned to the props of the VDataTableServer component. 

### Actual Behavior
Loading message is not appearing. and color of the progress bar appears only black.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptj0ELgkAQhf/KMud2LQwCMaF7h+7ZYdLBpHUVZ7Qi+u+tLEZBp+F97w28d3wC90W06zozDgQJpEJNZ1Eoy51S6ahLFNSCZ0uaqR+pn7hSSe2DrC25Si7bHJY5BGPi+koPzxw2NOPCIrNnZGlEqVunVx+rtW3vLR6KgphnbFssa1f9CC10Fx/dB2mMUQdLyKRuWEv4zNLoT2s/J42+tsFrAbGJzRrCXW3g9AbmflcN)

**Comment by nekosaur** [comment]
The color of the loading bar is controlled by the `loading` prop. So `loading="success"` for example. But you are correct that the `loading-text` prop is actually never used.
