### ISSUE TITLE
[Bug Report][3.3.19] v-date-picker v-model only for multiple dates, not single

### ISSUE THREAD

**Issue by jannis6023** [vuetifyjs/vuetify#18348]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Import DatePicker, place one in vue template, add v-model and a ref<Date>() and put it in v-model. There will occure a type safety problem:
```
The expected type comes from property 'modelValue' which is declared here on type 'IntrinsicAttributes & { header?: string | undefined; style?: StyleValue | undefined; title?: string | undefined; inputMode?: "calendar" | "keyboard" | undefined; ... 59 more ...; "onClick:save"?: (() => any) | undefined; } & { ...; }'
```
A quick look into the typing in node_modules/vuetify/lib/labs/components.d.mts:12660:13 shows:
`modelValue?: any[] | undefined;`
this needs to include Date as is for my typing to work.

### Expected Behavior
Either date or date[] types

### Actual Behavior
only any[] or undefined

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkUGL20AMhf+KMhe3EHso20tDumxvPfRQWGgPdQ9ej7Jx8WgGSU5ZQv57NbYpIXtZ8MHzRnrfk+bX2Qn3/kvOzWlCt3N7xZjHTvG+JYD9qe5ynn/nQ59Iu4GQV8nEfP997F6eOU0UICQUqhRkyjmxwo8JdTi8fOueBPoUcyIklS1IAkpgnLVxA4+I0Kl2/REDPPaMSHJMKpu9/8/3twGKsuTb+6vcdpSeh2w5UKelfTC4BToD4wEucOAUobKRq1IOFo5EIcozfC4V76qvOI4JfiYew6Z6XwCLpZm5rVvc6tjl5o8ksr2di0u7XkjrdjArRTNKObfuqJpl530fyNoCjsOJG0L1lKN/sDLPE+kQsQ4pPtw1d81HHwbRa7lBifUTp7+CbCat215hyq7fgForZ8KHTwti1erRnqowXnl7A56Qa0YKyMhvHemm7Xqsm6tXoxX6pSX73GXr5kbb/ZLa/f4Hvrzufw==)

### Other comments
Workaround:
```
const eventDate = computed<any[]>({
  get: () => {
    return event.value.date.toDate() as unknown as any[];
  },
  set: (value: any[]) => {
    const d = value as unknown as Date;
    event.value.date = Timestamp.fromDate(d);
  }
})
```

**Comment by nekosaur** [comment]
Please provide a working reproduction. Labs components do work in the playground.
