### ISSUE TITLE
[Documentation] Can't click on subitems on the sidebar to the left (for instance, can't select Introduction/Why vuetify)

### ISSUE THREAD

**Issue by luciadarsa** [vuetifyjs/vuetify#18340]
### Environment

**Browsers:** Edge 117.0.2045.41, Google Chrome, Safari
**OS:** Windows 10, Mac OSX

### Steps to reproduce
Just click on any subitem on the sidebar to the left. This was broken today, in the latest content update. I know for sure because it stopped working on my Windows machine, but worked on my Mac, until I refreshed the content.

### Expected Behavior
Clicking on subitems navigates to the appropriate content

### Actual Behavior
Click on subitems does nothing (doesn't change cursor either)

### Reproduction Link
[http://www.vuetifyjs.com](http://www.vuetifyjs.com)

**Comment by appliquant** [comment]
Bump. I have the same problem since today (26 september). Tried on both Firefox and Chrome.

**Comment by jonathanzuniga** [comment]
hello, also home -> learn button (nav bar) -> subtitems doesn't work :(

**Comment by luciadarsa** [comment]
Seems that the v19 has fixed it. Thanks.
