### ISSUE TITLE
[Feature Request] VTabs fixed-tabs option to align left

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#18341]
### Problem to solve
This is a follow-up on #13451

Material design [spec](https://material.io/components/tabs#fixed-tabs) says:
> Fixed tabs in a cluster can be aligned to the left or right.

But there's no way to disable the center alignment of `<VTabs fixed-tabs>` without using external CSS.

This issue doesn't seem to be addressed in v3.3.19: [playground](https://play.vuetifyjs.com/#eNrFUcsKwjAQ/JWwZ9si9aJUwa/wYD2k6fYBaVKSbVXEfzdNKyj4unnanZ1h2GH2F7BGRNu2DfsOYQUJYdNKTrhJFWNJHwhucr97RDyzrKhPmI9rVgZCS23WKbSmbrg5p8C4rEvleXe2xA2lMFncTVjPZYeO1goduUNmK93JPIk8/U5NR+3UGTKtGFX4TV0ZHNwlFvQsnZD9KZhFoVX+IppARWj+m2384UO6AUwdJtFDuXCdQRzG4QLGOV/C4QYFCafm)

However, I see that in 3.4.0-alpha.1 there's no space around the tabs, so alignment becomes irrelevant, is that why the original issue #13451 was closed, @johnleider?
[playground](https://play.vuetifyjs.com/#eNrFUcsKwjAQ/JWwZ5sqepIq+BUerIdtutpCTEKyrYr47/YlKPi6edqdnWHYYTYXCF7FK+dkXRHMIWE6OI1My9QIkdSRQp93e4cYsyB25Ynyfs32kbLa+kUKzpcH9OcUBOpybzq+OQdGzykMFncTUaOuqKGtoYZckwiFrXSexB39Ts1H26gzEtYILuibuvDUumva8bN0QOGnYIGUNfmLaIoMk/9vtv6HD+laMHSYxA/lwnUEUzmVM2jnTI4j1K5AOYHtDagZqj8=)

### Proposed solution
Either add prop, like `align="right|left|center"` with `center` being default for backward compatibility.

Or, expose these margins as variables:
```
.v-tabs--fixed-tabs > .v-tabs-bar,
.v-tabs--centered > .v-tabs-bar
  .v-tabs-bar__content > *:last-child
    +ltr()
      margin-right: auto

    +rtl()
      margin-left: auto

  .v-tabs-bar__content > *:first-child:not(.v-tabs-slider-wrapper),
  .v-tabs-slider-wrapper + *
    +ltr()
      margin-left: auto

    +rtl()
      margin-right: auto
```
that we could override. Similar to $tabs-item-align-with-title-margin, etc.

**Comment by johnleider** [comment]
You're using fixed tabs, which forces them to a higher minimum width for each item:

https://play.vuetifyjs.com/#eNrFUcEOgjAM/ZWlZxkaPRk08Ss8iIcyKpCMbdkKxhj/XUBMNBE9empf32vTl3e4QvAq3jkn24ZgDQlT7TQybVMjRNJGCn0+9ANizILIikhZbf0mBeerGv0lBYG6KszAd+PA6DmFce+5KVrUDXW0NdSRexKhtI3Ok3igp9R8tp06I2GN4JJ+qUtP/XVNJ36XjihMuwmkrMk/+FFkmPx/DT1++GKpB2NaSfwSI9xmsJRLuYK+ruQ8Qu1KlAs43gHSZKIx

As far as the md3 spec, any alignment differences should be added to the md3 blueprint.

**Comment by Maxim-Mazurok** [comment]
> You're using fixed tabs

Yes, that's the point of the issue, that alignment option doesn't work with fixed-width tabs.

> As far as the md3 spec, any alignment differences should be added to the md3 blueprint.

I don't quite understand this.
Looks like link was to m2 spec but now redirects to m3.
Here's a correct link: https://m2.material.io/components/tabs#scrollable-tabs:~:text=Fixed%20tabs%20in%20a%20cluster%20can%20be%20aligned%20to%20the%20left%20or%20right.
<img width="595" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/7756211/8d68d348-0986-4895-9c5c-8b5e00f3c63a">

I will unsubscribe from this issue as I believe I described it clearly and it isn't important for me right now so I'm not going to pursue it any more, feel free to close as not planned if it doesn't make sense still, hope this helps, cheers!
