### ISSUE TITLE
[Bug Report][3.1.4] lines="three" with prepend-icon causes misalignment of v-list-item icon

### ISSUE THREAD

**Issue by danieldanielecki** [vuetifyjs/vuetify#18358]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.3.4
**Browsers:** Opera 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Download the repo
2. yarn
3. yarn dev
4. Resize browser to see a mobile menu
5. Click a mobile menu
6. Change lines="two" to lines="three" in Header.vue

Note: the repo is under activate & early development

### Expected Behavior
lines="three" with prepend-icon doesn't cause v-list-item misalignment

### Actual Behavior
lines="three" with prepend-icon causes v-list-item misalignment

### Reproduction Link
[https://github.com/Doyban/Doyban-Website](https://github.com/Doyban/Doyban-Website)

### Other comments
Screenshots below.

`lines="two"`
![Screenshot 2023-09-28 at 09 12 35](https://github.com/vuetifyjs/vuetify/assets/12736263/e73683df-7e3b-4b1c-8559-5afab5857433)

`lines="three"`
![Screenshot 2023-09-28 at 09 13 08](https://github.com/vuetifyjs/vuetify/assets/12736263/067d8697-9de0-4d1d-abf5-ff41cac66f2a)

**Comment by yuwu9145** [comment]
Could you please create a minimum reproduction link using [playground](https://play.vuetifyjs.com/)
