### ISSUE TITLE
[Bug Report][3.3.18] v-data-table selection

### ISSUE THREAD

**Issue by jgamann** [vuetifyjs/vuetify#18359]
### Environment
**Vuetify Version:** 3.3.18
**Last working version:** 3.3.18
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select one item and after unselect, the selected array will have 2 repeated items

### Expected Behavior
If unselect the previous selected item, the array would be empty

### Actual Behavior
Duplicated entry in selected array

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1vmzAQx7+KhTS1lQpJeEgblFWa2j103Yu9nZq+MHBNWQlGxqTronz3nWMgQDBKpPEm+M53/vnvO5PHjZHzcPQpy6x1AYZvzAWssoQKuFmkhMzXZkQFNQUNEpAGQtbmikWQfFwYOSQQCogWhvKECc1ztKN5TUXMUnNSufwXoBFw6S3fak+MC0p7BHkOXNSOnd3MgJsZXQJO8Joec02TQlpTuoLKwUEUPDVZ8Bu5lCl/YW+mApWGm/mouaNqjyHlUY2/EqZNMmraC2PnxxkZh5vNhlQbJtvtfCRtu3DMKONxMB81xMNhHvI4E7tZ8CdjXJAInmmRCLJRiSUJOb+ohtUO9mPcQLmmTx6fLvfmUkW07m2kGScfEYsEfHJ2p6Ql55PxeIkZ+TpOlxdnjXTyoUm8THF2LigXXecrvKNLit32bFujTb3kLU0YjyE/u6zzQhrhSCUKK7c2wReKvBKyN/6ZCn3oLeVBPhCMpxUMrPyTMwFxOpAgUzP0Ke45w/gPuvgY3e3g5tFWjTB8tvIopEyc/YWU/GLL4vDQKpV9MvFmHR8q6JOpNT4IQW18Yrsde7lln7gHIXI3uMJQWfSi34dAQg50RXKaRm9x+KLnt52rPv6Zjv9geoPf+U/8n/HCiPkA89TuY57oRe+S1dCHIQq6vctjoG+LLKSvnSZuUjtjr4/asbqKltDTk5W+Phn6K15XwAOsFewhLbg3PU1ut9sSNbljdV1ljbRXOAb9OyTJOwmApgPkV72Sj3XgM21zHoYo8Lb1GO4fLEnijGUD1LPe8h5bXXNF3T73JnUvczvNMczfWArvIVsFemh33KUoq1sDfa2t7qnVPTSF7bbNx3DfsbQYuLtdr1do29PVh9e+y1ot2V/Y9uliP8TiAT/CWmpv0qu0rW3HaVfPmrp7BopZ34v7j+lWvSgnDuaj8i+Zsb00HMuxXEP9Tq6Np3+YCb84)

### Other comments
Thank you

**Comment by KaelWD** [comment]
Related: #18356

**Comment by frankkoornstra** [comment]
I seem to be running into the exact same issue with the latest Vue (3.4.29) and Vuetify (3.6.12): [reproduction link](https://play.vuetifyjs.com/#eNq9VE2P2yAQ/SvIl7TSkoCNiRNlI61676XtKc4BA8668gcyJFUU5b93MHHkpq3UPWx98fDmg8djmN0lsr1cvBgzPx11tI42VvaVcchqdzSoFu3hOY+czaNt3qLhqxrT9Q5del2iKyr7rkEzyJ3l7Rghu9Y6dDR1J5RFz2g3Oi6jgVAeVSqP1vCnpFxSnWhMVcIxi7MCCyJXuOCKEK6SpaI6j56mqbCB0637ejbg8TWqRhz0wrSHh8BWNLeIL7LXurWvnQuUYxIzTJaYJohyTDhO2XzIH9Ov90J/ZJ0RIM3ECnOZxpilnOBCLzmWtFjFqyzmSVr+B9bkbawFJUC8EKA1UGeKCZwxqXFMyywrpeCMvj9rhpPkTaz5ii6XsSowUanCTIDgQkCv0IyTlGWJljF5d9YJjtMH1sHYh8YPTW91raXT6tu9+eGZbLriO6C7/fbDbv/x8Z28aqF0/8s7AR3QSdRHvUYzT3D2hFzlar/8HJYWnqAoPFKK2uqJgtPciQqTEp8CilyA/7FUrwWc68VNCwUMCQ/+vQwItFmEsQJDBBZON6aGzGGkbE5YCSfwkBxSTrjplK5h8DzIOWqv4J4qd4YA2TVGSDc61jcxwXOz7p4KdvX4bSyNuIfxcEjw+YYLMLTBDxx2vwGDja3rgfjBb22gocbwHqZl3+Jwzx5aDCeF05leby+X3/riet0svMtLM5EDltada42s7Awoe5u/Vlo/gUFF74S46PoUJXM2j1eRN/icxtH+J+dMtjI=)

**Comment by implank** [comment]
The bug still exists..
