### ISSUE TITLE
[Bug Report][3.3.18] Flickering scrolling behavior in VDataTableVirtual

### ISSUE THREAD

**Issue by ttonyh** [vuetifyjs/vuetify#18351]
### Environment
**Vuetify Version:** 3.3.18
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Linux x86_64

### Steps to reproduce
Open https://vuetifyjs.com/en/components/data-tables/virtual-tables/
Go to the first table and scroll down really fast with mousewheel
Then stop mouse wheel quickly and scroll up
Table will start flickering uncontrollably.
(see attached video)

https://github.com/vuetifyjs/vuetify/assets/1578211/01fab270-2743-4066-ab36-4245cde7a6e4

### Expected Behavior
Items should not flicker when fast scrolling

### Actual Behavior
Items in table flicker

### Reproduction Link
[https://vuetifyjs.com/en/components/data-tables/virtual-tables/](https://vuetifyjs.com/en/components/data-tables/virtual-tables/)

### Other comments
This was working normally in v3.3.17

**Comment by KaelWD** [comment]
Broken by 283a18f3 somehow????

**Comment by KaelWD** [comment]
Yeah I am v confuse. It works fine in the commit before that though.
