### ISSUE TITLE
[Bug Report][3.3.19] v-data-table item.columns undefined starting in 3.3.18

### ISSUE THREAD

**Issue by robertpatrick** [vuetifyjs/vuetify#18352]
### Environment
**Vuetify Version:** 3.3.19
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Change the Vuetify version between 3.3.17 (or earlier) to see everything working and 3.3.18 (or newer) to see it failing...

### Expected Behavior
Expect the table to render properly in the current version of Vuetify.

### Actual Behavior
Get an error in the Dev Tools console that says: `Uncaught (in promise) TypeError: item.columns is undefined`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVW1L3EAQ/itDSjkFE81ZKQavIBb6pbRioV88wTUZ74KbbNhszsqR/97ZzdvumVT90NJ8SXbmmZlnXrJzvfVKGR+eF0WwqdCLvDOFWcGZwk/LHOBs47OiMJ/mEItcsTRH2YqMMGGK+YrdceyEABs/EwnyKCV3pV+g9Au2wsXSM4JLlJd0XHqDQbRGlqAsCdJ+OVpjRrpYZIXIMVeOWmv9DeOVjpCzzPXscvBFoVKRa2c2l++NdDDsM6Qcu5rAu+tbbRSUik63N+Rja4JDvfQsg6ZW67SAKBZcSMKtUP3QRhf6vGeckKrK8rJxtr/jAGDbuHZhUNdOmMMmjk320Olghxqa1HVTmzrt1JKm244POpaxTAtlQCnVXyrYQoL3ZHnR9QNquJcigxmN0UwbAeAvAyUgq7h52wZ724aHJra3D+0JgDiVCtoZgAVcD6n1GP2oVHGMYGaqOjuwVQ/4RApTL1fBeLrKSRVTfJS2rra+R8N8o6kai6Kn7U2OflJaNGljvjbPVS+6O9+wlOu2jjlkY8oXXX5l1IArpEbEKccEviBNCNO/x1gMTugBPIWdrjzAY5qoNenmR+/Hed408zRMx3AL/GFAdGd0DeRKxIkb0YwG6a5oyp5cVdsDTSf4GMx3sujqOV34qXJEEL6mBy3pGKXyM5bTxbRTrFdRD4PTIPwPqPuPeLcW4sEXcTqexue01ESc/rwYgVclDRHdVRNOR2rz79JvyaVlWb2hd3+B37O/ZmTd7fw+YHZoBCcH/WVwMnNT7iDh0YAJjyZAc8vRfMqTHw6gc85tlJWCRFXJ3C65nY6mPGja5WFJhgvDEo7Uo9e2W7ajkqFai6SMhvjuPm9WuMPuHhopLBaLruUOos9ptpKIOS3NvoeAvMRxrJAsX+kN24N7yi3X5l3v6zXeL26vPvCOg+Pgg9e8w1Pv5jfj+dHo)

**Comment by robertpatrick** [comment]
Note that I was able to work around this issue by simply removing `columns` from all field references so maybe this breaking change was intentional?

**Comment by KaelWD** [comment]
Yes, I've added a note to https://github.com/vuetifyjs/vuetify/releases/tag/v3.3.18

**Comment by jerbob92** [comment]
I would say that this is not something you would change in a minor version.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/labs/introduction/#what-is-labs

**Comment by jerbob92** [comment]
> https://vuetifyjs.com/en/labs/introduction/#what-is-labs

Ah, I did not know that, sorry.

Let's just say that this change has let us known that our `yarn install --immutable` was not actually that immutable 🤡
