### ISSUE TITLE
[Bug Report][3.3.19] `eager` prop doesn't work for `VImg`

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#18367]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I'm unable to check in playground but tried in my local minimal vuetify app and can confirm eager prop isn't working

### Expected Behavior
setting eager to true should render the image in SSR

### Actual Behavior
Img doesn't render at all

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNo9jkEOgjAQRa9CZi2tBDcSJPEc4mIstZS00LQjaIx3t9jgan7+m8y8yxuCF/zsHJsfEiqoSVpnkGTTjllWz7m2ak1ZJgyGcGrhpvKl1yRbSP2iO+pjX+73W1VhcFJQ7pH0FFGxAYlK+hTj20h6IhcqzkU3rgKk768hMDFZrm3cDdyhR2PwyW108hoNG5xK55qa//Siac3/2vDZQclKdoA0iyNcv5q9SXo=)

### Other comments
Is vuetify SSR friendly and nuxt compatible because I'm having some trouble using it with nuxt.

**Comment by jd-solanki** [comment]
bumping for visibility 👀

**Comment by MarkSonn** [comment]
to answer your 'other comments': yes vuetify is nuxt friendly for the most part

with that being said, i'm also having this same issue with `eager`. it broke for me on images and carousel items when i updated to `vuetify v3.4`

**Comment by MarkSonn** [comment]
@jd-solanki this is no longer a problem for me after upgrading to `"vuetify": "^3.4.2"`, please try upgrading and if that works you can close the issue :)))
