### ISSUE TITLE
[Bug Report][3.3.19] TS error when supplying VAutocomplete with items of generic type

### ISSUE THREAD

**Issue by MelvinFrohike** [vuetifyjs/vuetify#18361]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Safari 16.6
**OS:** Mac OS 10.15.7

### Steps to reproduce
When supplying VAutocomplete with items of a generic type, v-model is marked with an error, e.g. "type 'string' is not assignable to type 'Val$2<t, false>'."

```
<template>
  <v-app>
    <v-container>
      <v-autocomplete
        v-model="selection"
        :items="items"
        item-value="value"
        item-title="title"
      />
    </v-container>
  </v-app>
</template>

<script setup lang="ts" generic="T">
  // generic="T extends Item" also fails with the same error
         import { ref } from 'vue'
         import { Item } from './Item';

     const items: T[] = []
     const selection = ref<string>(null)
</script>
```

### Expected Behavior
This should work without an error

### Actual Behavior
An error appears on v-model

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUsFuwjAM/RUrFzYJWk3ssq4g7bg7N8ohKi5ESpMocTskxL/PSQZ0GyfH7znPfk62ZxF8W344V4wDikrUhL3TknDdGIB6XEjn0jElrTUklUH/A+WKgWxr+RYSXmGAcdHbPepVIwJqbElZ04g7XSluFJhNccpEYDFKPSCzKf5jSZGObIp3trwOWv6dNCLZSF1ODHIaWq8cQUAaHGhpDlGW54ED8mXVcrppRBIpyykIeCI0+wCfLMj1UgcLnVQ6wJeiI9ARIcgeAb23/m4AVO+sJziDxw4u0Hnbw4yXP3tUE8VvRUUZ09l7HDyVsclAaSWhgs12ByvY7n5xt90zxf3qQF6Zw/rJDFo/x21k/+xPzNNPiB0KCvwT8JRmUIbQd7LFPMs5y6d3qSDLZSg9xhS6iMtcLItl8craMb68id03pXPGoA==)

### Other comments
This seems to be related to issue #17383 as this had the same kind of error if v-model was supplied with a generic type.

**Comment by bjacobgordon** [comment]
I also had this issue. I evaluated the Val$2<T, false> type myself using the declarations in the vuetify build, and it simplified to `any | null | undefined`. I ended up casting the selection to `any | null` and disabling "no-explicit-any" just to show that the issue had been investigated in my code base.
