### ISSUE TITLE
[Bug Report][3.3.19] VDatePicker - Max date is ignored

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify#18363]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Set max as ISO string
1. No change in the picker. I can set any date

### Expected Behavior
The max Date works fine and I can't select date after this max

### Actual Behavior
max is ignored

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU01rGzEQ/SuqLptS72pjF0oWpzjQQ+k5tNCqB2U1jpWuPpBkN8b4v2dWUoztEDAIVhq9eW/ejPbPjgbfs80aolpum6dAO6q0sz6SHek9iAg/8x3Zk6W3mlQFW3FTgN/E9ke4k8JF8AWzkJhYK8uk2D4FhHIDzwncWxMiKRzk9lTjascNIXEFGjqS9oRIWIr1EO9zsBrU4ypWk3zH2Pjdp9OoeEgSuZrupLYEG8H7j9zQSTJ+51yDxaDreQTtBiT5OsLmm1o4l7bpgGVHoQz4EkrBZNKp/h/61uL5ltNpO53V7Q2u+7bt0mp/c0rYKxM7pxojWWnOjirAY+i9cpEEiOtcyGEuHpbH00jtJaWzOjxiVxFxVX2HYbDkl/WD/FCh5TnLlEiG7jNbrYXDqVuDHUi94+UicHroJqeoMp45XcXoQsdYLw2mSRjUxjcGIjNOswXCmF+bqDTU0urFrJk1n5lUIR6HGwi6fvD2fwCPJJyWaSaZ8RlcIFWQSeH6JkuUWD2IhzBqvOFmKLgBX3swEjz4Sy2dpR3bOrt639rpH3GJ8knCYtpcf2la9gkFOE0PGd8x3U9oKgbnmTtB/74Axs1G8A==)

### Other comments
I think it's the same with min date

**Comment by webdevnerdstuff** [comment]
I think the format of your time is off slightly.

`2023-09-09T00:00:000Z` should be: `2023-09-09T00:00:00Z` or `2023-09-09T00:00:00.000Z`

This works (as of v3.4.1)
[Playground Example](https://play.vuetifyjs.com/#eNqlVNuO0zAQ/RWvX7KIOs62KyGqLuoKHoDnFUhgHrzJdJslvsh2w1ZV/52JbUpTbpWQLMWeOTNnZnyczzvqXc37DYR2tS0fPZ3TVlnjAtmR2oEM8CH5yJ6snFGkyNhC6Ax8I7fv/W0jbQCXMcsGA1lreCO3jx6hQsNTBNdG+0ByDnIz5rjcCU1IWIOCOYl7QhpYyU0X7pKx6NqHdSgmycf58N3H08B4CJKpmvmotggbwPtnQtNJbPzW2hKLwa4XAZTtMMmrAbbombQ2buMByw6y1eCyCY0XjJF3ujbOQR0IYz89PYvt27b+ihNR8ulG0Gk1nbHqJa67qprHVX0SlPAfHHxMkq0DyetTit/Xcybr30j/O3n5j66SJU12wY8mjkdfu9YG4iFs0uAPOnSwOlZflBPJSlL+AVWEiMviLXSdIR+N65qLAq94wVNKTIa3nbIxJS2q3Gi88agVkR1e0IN6BEWW4SzoOgTr55zXjcawBrq2d6WGwLVVfIkw7jY6tApYY9RyVs7Ka960PhybS/CK3TvzzYPDJIJm9UaaQfZnUGUkMlyXV4khm1gn7/1A8Utqjnw9OOZAN+DAndvRSdhxVyeuP3c2/gGcwzwKWE7LqxdlxZ8jgaDx3eKzpfsJjcXgdcZB0C/fAVljiaE=)
