### ISSUE TITLE
[Bug Report][3.3.19] Checkbox - Error when try to reset value(s)

### ISSUE THREAD

**Issue by f4ngwt** [vuetifyjs/vuetify#18366]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1.Check checkbox
2. Click a reset button
3. Get an error

### Expected Behavior
Forms should be able to reset validation and should set value of checkbox to an empty array

### Actual Behavior
Get an error “Cannot read properties of null (reading 'some')"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Ustu2zAQ/JUFe5ANOBJsN0VrKGl6L1AgV8sHW141hCmSpUijgeB/z/LhiAmCnEjuzJCzs9yObDBt9Uvr8uyQbVhtsddib/G+kQD1+aZTpoeHwR16bktt8IzSgsHurmEeesSuYYELMI7nvXB4ucQjidsnbE8H9T8WAAjnR7r8RknSc6mdbdgr6N/yZbIAXMJV/JsPGat3wnItcFL16oiCdOHxibgxTuBA9bBm9RM+p1fK9xKxP4SrAhgOGRjIHyqrFAB1fLBkXInQyJfb799uu1XDwD5rr4wpUl5xU1eB/1b80Arenois5CMO6NnGrznZ7334dKirbGB0HFrDtQUSOB24vNfKWBj9zOACnVE9FDTrwtOBvMrBQpok3HnWbD4Boc1U3u4ImKAQK0HbaD8x72G8BsY7mIXqz1Kg/Guf5hMGdKN1RoI1FGMqpn/zihUG/zlu8EheA77w6y43kf+RycsIYXYbKP5oy5WEZbGIBqm0LNJFH/BWGW/1CW+d8dZX3htjaXrkaTbPUklBx+9ThsHGuKn3uorDo7Gxy4Kty3X5lcV1+YPtXgBW3Se+)

**Comment by hahatulk** [comment]
form reset resetting array value to null, fix please
