### ISSUE TITLE
[Bug Report][3.3.19] v-tabs components is not ssr friendly - nuxt

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18374]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to clone the repo and run yarn  and yarn dev

### Expected Behavior
Style should be applied or `.v-slide-group-item--active. v-tab--selected` are missing on page reload in nuxt

### Actual Behavior
It should work same as Vuejs

### Reproduction Link
[https://github.com/alokVishu/nuxt-route-params-change-issue](https://github.com/alokVishu/nuxt-route-params-change-issue)

### Other comments
Please Refer screenshot:
- After reload: 
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/68fd70fb-a3e7-4f0a-9c6c-8ed968456303)
- After navigate or click
![image](https://github.com/vuetifyjs/vuetify/assets/80033712/fa80b276-3081-45d5-b3da-19065d2df224)

**Comment by KaelWD** [comment]
Don't use `value` and `to` at the same time.

**Comment by DyKv** [comment]
You can try to set initial :model-value="null" as workaround
