### ISSUE TITLE
[Bug Report][3.4.0-alpha.1] Check box not showing

### ISSUE THREAD

**Issue by hakimov-dev** [vuetifyjs/vuetify#18377]
### Environment
**Vuetify Version:** 3.4.0-alpha.1
**Vue Version:** 3.3.3
**Browsers:** Yandex 23.9.0.2271
**OS:** Windows 10

### Steps to reproduce
1. Added v-checkbox
```
        <v-checkbox
          v-model="selected"
          color="red"
          label="Lorem ipsum dolor sit amet consectetur."
          value="Lorem ipsum dolor sit amet consectetur."
        ></v-checkbox>

const selected = ref([]);


````
Result:
![image](https://github.com/vuetifyjs/vuetify/assets/83240328/e17430b8-3cbe-48f1-8735-baf169a76c9c)

### Expected Behavior
Working well showing checbox

### Actual Behavior
Checkbox not showing but label showing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkMFuwjAMhl/F8qWbtKab4DQVpN33BpRDSI2ISJrISSMkxLuTNEJw5RTH/v9f/ry7YmDV/Xkv0kz4i30k642MtB0mgH7UaSlymVp1InU+uEttAKTWupHMZsBAhlSkccDHTDnjOE/4tWnkYZH/OyYL2ofZwliEEHQEaSlm3xRKVJxZPI1JmpneN2777rl1BeoqUd+9cOZvUKx9hJDtfhFq6x1HuALTEW5wZGehySdqirzgTaHIKzZsiuxj12TaZv9Z4mtgjsLbF67ESqyxvGvx3UrjT1L84P4OtLR9FQ==)

**Comment by KaelWD** [comment]
![Screenshot_20231001_232404](https://github.com/vuetifyjs/vuetify/assets/16421948/ca3826fb-3908-447c-8670-6a0250c41ffa)

**Comment by KaelWD** [comment]
> Browsers: Yandex 23.9.0.2271

https://vuetifyjs.com/en/getting-started/browser-support/

**Comment by hakimov-dev** [comment]
> ![Screenshot_20231001_232404](https://user-images.githubusercontent.com/16421948/271827786-ca3826fb-3908-447c-8670-6a0250c41ffa.png)

It works the reproduction but not my code, i tested it in chrome broser but still not showing.

**Comment by PoloLacoste** [comment]
I have the same problem, tested on the latest version of Chrome and Firefox

**Comment by PoloLacoste** [comment]
Found the problem.
The file `@mdi/font/css/materialdesignicons.css` was not imported.
