### ISSUE TITLE
[Bug Report][3.3.19] Performance issue when using v-tooltip component

### ISSUE THREAD

**Issue by MaxenceMouchard** [vuetifyjs/vuetify#18372]
### Environment
**Vuetify Version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
Put a hundred tooltips in a component and realize that refresh takes considerably more times.
this is not the case with others components like v-btn for example.

### Expected Behavior
Should load instantly

### Actual Behavior
May take a few seconds to load

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1Ur1uwjAQfpWrl7QSEBBdWgWkqgvdkRiaDm7iFEuObdmXtAjx7j0naUiATonPd999P34/Mu+y+MXaWV0J9swSFKVVHMU61QBJPeXWNr/NITMaudTCdSUqbsUPvprSGi00rpN4fO7b+tJO4n5rjNpK66n9dr1bGF9uDJWWUBIPiNLRZ05aBC+wavlKwnUIR3CigBMUzpQQkcZocHlzedc6u00t2DSEGMntR0fVbiQMkRqPUPovWAVe99FGKGVgZ5zK76KHIKsVQhLYpInmXxbXYeWyhnpaGLdKmQapYTGfz1N2jk/xT6H6TDamFg5K0WdUT5HwUVrgGcqaY4NkuaPtKQNlMo7SaKqhsYQb2FB3CKUbHAR33pXEROwysk7dlVFXqt4KOJiK3CqJLuBekMQ/mllvvNRe5u111OLxsWPRJMAEQL83lcrppbTtZ4zc8W8gSw5QcI9kjdGAxA9ELlEI8mms4DRhy9ly9khSwnfxxD5+AfMaJA8=)

### Other comments
I don't expect loading a tooltips component to take much longer than loading any other component. Maybe that makes sense to you and you can explain. I apologize in advance for the inconvenience if this is the case.

In my use case:
I load a large data tree, in which I have several action buttons on each item, and then tooltips for each button.
Without tooltips, my tree loads instantly, but with tooltips it takes over 5 seconds to display.

**Comment by KaelWD** [comment]
You have 1000 items not 100. On my phone the initial render takes 3.5s so 3.5ms each. 400ms is in a vue internal function that I've opened a PR to fix (https://github.com/vuejs/core/pull/9739), 250ms is addEventListener that I've made lazy (000d8588d), and another 550ms is garbage collection which isn't really avoidable. Everything else is just a consequence of rendering so many complex components at once, you should use https://vuetifyjs.com/en/components/virtual-scroller/ to only render what is actually visible on the screen. 

> I don't expect loading a tooltips component to take much longer than loading any other component

One tooltip actually results in 7 components being created.

**Comment by MaxenceMouchard** [comment]
Yes, 1000 or 100 is not the relevant information here. 

Thank you for this precise detail and thank you for your time on the subject. 
Thank you, for highlighting virtual scroller here, I didn't know about it. 

Unfortunately it doesn't work in my case because it's not a flat list that I'm displaying, but nodes and I don't scroll in my nodes but in the tree menu as a whole.
I finally added a collapse effect with a v-if isOpen on each node, so my problem's solved.
Nevertheless, your commit on performances are appreciated.

Thanks again :)
