### ISSUE TITLE
[Bug Report][3.3.19-master:2023-09-30] VRangeSlider selected range indication always starts at 0

### ISSUE THREAD

**Issue by davycardinaal** [vuetifyjs/vuetify#18389]
### Environment
**Vuetify Version:** 3.3.19
**Last working version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add v-range-slider component
2. Set the max range
3. Set the min-range to anything else than 0

### Expected Behavior
Range 4-16 should show a "selected range line" between the two thumbs, starting at 4 and ending at 16.

### Actual Behavior
The "selected range line" starts from 0 and stops at 12.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjcsKwjAQRX8lzNo8bNxUQsHvUBchDhJo45BMuxH/3ZooSFcz58xl7vkJJQd9IlLLjHAExzjR6BmHSxLCLdIT1bVCeCT2MWH+qiqzT3eUZYw3zEL/wnqb/pj2zOm/khVLyJFYFOSZBqcbrid47cAqqw7Q5r6Xky+MWXWms9L00hq4vgEqtT01)

### Other comments
This is broken in the nightly build and is already visible in the docs website. Although it is not shipped to 3.3.20 yet

**Comment by KaelWD** [comment]
10e86c2

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNrNVk1PgzAY/itvevECw2XGZGSaePekxsvYoYPqiAWatjDNsv9uaffBoCgahh4I5Wnfz+eheecbJHjo3TE2KnKCfDSTJGEUS3IbpACzwsWM6aX+iMgLzqkULuNZEUeEmx0Af79zE6DNHgR4fqTlKR82kOB3H8aXDghJmFo5IFd5srzHS0J9uMB0jT/EhdpeZeunOHwTVVAaYK6spgvYOpUIDzh9JWcOsw2QWe46oXsRZqnEcUr4AdQwz9YVYHeSnkDWc3u4LMcVuh7w6maeza6jM04KwgXp5LTE6lmbQkA9Jck4l1mALJlUQ0YxJ6GMs1QZqOCqvZgGqJbBeWPZq27GPHbhhM0o1jKHkGJRppIs3etdBX2y3hPfgzI9DMf/gl2aqXDkcOkBl41SrDQ1JdDK3vc/f5scfuCyTRitSrPQ1om4X14FQ0T86udoSNQim+7C6U8XvSriT7QwpArOwX8Vqd0Gx5lAezgdCkqsMTSZ0UrtmNlq5lVmLrR10GQ0GV0h8x5P0eITYbSYGg==
