### ISSUE TITLE
[Bug Report][3.3.20] VDatePicker does not support Czech locale

### ISSUE THREAD

**Issue by oookoook** [vuetifyjs/vuetify#18397]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
Reproduction link contains all the necessary information.

### Expected Behavior
The UI of the component will be translated (e.g. names of months)

### Actual Behavior
Vuetify throw an error and does not display the component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkEFOxDAMRa9isilIpEUMK9QZiR03YEFZVImLAmlj2WkFGs3dcRtAA6vkW8/f334+GmHXPBDVy4zm3rQZR4p9xkM3AbSL7Ym2rwofFnCxF9l3xtsh4ge8zZLD8GkdThm5M9/o1hmT6yNa4rQEjwxFa6+TM3BDvQ60FNw78qFt/upfR63/s/wJ1miykleZErhtzhZRKY4DZRDMc9knjJQ4wxEYBzjBwGmESm9QrTiAS5NkGOUV9itxWT1ijAmeEkd/UV2tA4qlmpnTtdnVu/rOlPf2xrx8AWkqb2o=)

### Other comments
The problem is probably here: https://github.com/vuetifyjs/vuetify/blob/9547863639996ef6325b83ef2f4b0490aff1da60/packages/vuetify/src/labs/date/date.ts#L44

The line should be `cs: 'cs-CZ',`

**Comment by K-Schaeffer** [comment]
Hi,

It does the trick:  
![Screenshot 2023-10-03 at 22 23 37](https://github.com/vuetifyjs/vuetify/assets/37464395/d652a823-0dea-4c46-8064-f912e22d1736)

I'm just getting some warns on some datepicker translations not being found on this locale even though we have a cs locale file with them https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/locale/cs.ts
