### ISSUE TITLE
[Bug Report][3.3.20] Maximum recursive updates exceeded in component <VNavigationDrawer>

### ISSUE THREAD

**Issue by gifary** [vuetifyjs/vuetify#18402]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1. Open the web page
2. Check the console 

### Expected Behavior
No warning message and working fine when build on  production. here my package.json
`{
  "name": "web",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "rm -rf tsconfig.tsbuildinfo && vue-tsc --noEmit && vite build",
    "preview": "vite preview",
    "lint": "eslint . --fix --ignore-path .gitignore",
    "prepare": "husky install"
  },
  "dependencies": {
    "@mdi/font": "7.0.96",
    "axios": "^1.4.0",
    "core-js": "^3.29.0",
    "lodash": "^4.17.21",
    "moment-timezone": "^0.5.43",
    "pinia": "^2.0.0",
    "roboto-fontface": "*",
    "vue": "^3.3.4",
    "vue-router": "^4.0.0",
    "vue-toast-notification": "^3.1.1",
    "vuetify": "^3.3.20",
    "webfontloader": "^1.0.0"
  },
  "devDependencies": {
    "@babel/types": "^7.21.4",
    "@types/lodash": "^4.14.196",
    "@types/node": "^18.15.0",
    "@types/webfontloader": "^1.6.35",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-typescript": "^11.0.0",
    "eslint": "^8.37.0",
    "eslint-plugin-vue": "^9.3.0",
    "husky": "^8.0.0",
    "lint-staged": "^14.0.1",
    "sass": "^1.60.0",
    "typescript": "^5.0.0",
    "vite": "^4.2.0",
    "vite-plugin-vuetify": "^1.0.0",
    "vue-tsc": "^1.2.0"
  },
  "lint-staged": {
    "*.{js,ts,vue}": [
      "npm run lint"
    ]
  }
}
`

### Actual Behavior
show warning and not working when build cause leak memory and become white blank

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl1uGzcQvsp0+yAZ8EqGnQKGIql1bfSpRYP0qYjyQO2OJCJccsGlJBuCztBz9AZ97oV6hc6Q3D9JLoImNmCLM8P55o/f6MMhqWw2fijL0W6LySSZOixKJRzOFxpgukuVeDFb50/+rMVOroWTRqe5FXu0sEsLk6OaLZIgWCQw2cvcbUhyd3PDRysk6/kfH0u0hdCoHcmc3SLJfsiUzD5FG5jBSqiK5W6DBZJYyfXGLZIQBkBmlLF8GwV5jNGFeGXlWrUVuiqFJaiOVWOXSsqW4l9542GBensNn/DlCqQGPlUcLQlIS3996BZL1HkqM6NJykYj/sw6JTVnEDOaOFMbsKKNnX8mTjrFeXm9P/CVOu7BtzfZ7f3t/YCE4za7cQibBI2obhdlUSnjJqLk8Lqp5nIHmRJVRX5Lkd72CuFLsXS6rb+h+z+bNfX8SQpl1hzWUhmvC5n1rgME455LipN8doMYUxSdPHpDFi6czVWTJUVYCNm6m1rCQ5vuJO6b6rCLaNXcolqkS2GBoveOKYOlcc4UlNMGeaBI8uaeTqhwV5vQwHbnaWUMgV30UYpcYVW9Noz+OulOy50JmzcdWSl85hKvqBzt7Dip8HW3HT+pw2ca9+iMD+l+Q1MN/mNGc0+xC3o8Oh7OHAG8+/U3+PvPf/7643AATSV9osYMr0ZrdD9tlfodhR1ewfF4gk/1bgLoZxg1vfb3C8HnUNdO92K3Au/wpNfEc5GIvklTeMhzEFQmvZLEJ9wdyP3MQpq2hBVFLUvRqTvdhXhOa7r6jumq2/3TROqk+cHOHwNyfAFtRbzywqXTSj1YBMoJqm38sBfagTM0bOzw+5MCXvBRuxYZZ1+dThpRX0Y15tvx43+9/EzoDFV8zsn80R/P33JzsZ7P0spCWGbHxhURPHFq0foKlbpEDK9kcDJFfAyNPJ+PHp3w77TKrCwdKKHX/CqYxSt029LrZVEa6+DwHlfXYHF1hJU1BQxo/w3eBgf8S2NFiySuuBkbTpfGKBR6PuRXelWbxIXVM/Dbq7HwmySYDD9w+IeQFO+NCdAOyKUnszQX1WZpKOtFch1MeHNMYDAWeSH1uNEPotqPGumfGgXLj177f0GW20pqojWsTlF+bDVfDkN0imtj5TnMY6v5cpjSmnybuTOQd7X8K0CIF+qwSwt0G5OfIwU1/OLVAW+hPy40zcdCj8eRxmg4gN4Mf+GJ7z+SWT1FXdq6PG9+eslhQGIi4WXe9XiBK2v3p3ufIIj2Z/NQli74aCfUFknPz4Awj+e4gUq6yELzzjMVbSYS9qG7xPMZsD7Zy7iRd3rAnlhqqB4x9bH2UudmP6oX/WjDHZlRlwdvgUDeYy4tZp6f2f3GFEjfANb4mXFOx4GViIOS43VyN7obvUnC/9ub5OO/TTe0RQ==)

**Comment by blalan05** [comment]
I see the error calling out VAppBar. When I start removing some unnecessary elements, the error goes away. 
[Refactored] (https://play.vuetifyjs.com/#eNqtVlFu4zYQvcpUReEEiGw32QKB13GbJuhXiy62X8V6P2hpbBNLkQJF2QkMn6Hn6A363Qv1Ch2SkkjJzmKBDQxYImc4b2Y480YfDkmls8l9WY53NSazZG6wKAUzuFhKgPkuZWXpXt1Csh3fMMOVTHPN9qi9BGCXFipHcbdMmv2klcz2PDdbEtxMp9GuZtxq20e0W6IumERpSGR0jUH0UyZ49qk5AXewZqKKxGaLBZJU8M3WhO1MCaWtLWQdTBONi0fwygQlzWRVMk3wy6TT6vRSTqkJuzbmtTt3UaCsr+ATPl8Cl2BXVXDBxUUyUqT/wX6psUSZpzxTkhTs0bF9H6gJLm3o/Yw4iVHtMaszFHIjbFKc3C0GCm3ko2+n2fXt9e0olk9CoiY+A7TRbbVlQlmohDIzKhMKJM5azneQCVZVBFCy9LqXU5fVlZHhXhWd/1VtVG0eORNqs0xgthLKyXzgC/By5w+djcEmhBb52ytiH8BJ6XbRkCcF48Hc/Js0hbkmJNTpjuN+MZ/EK0jTyG5ztDNFiUhXTAO57tDI/ZUyRhUU0BZtedLOm1taocBdq0KtEdcllYAhu6hhLWqex3mMNZ2uVnuQKt3UhjyshjnOmA7H1wKfCHhNqQHDBULbm99Pp9+RoN8uPVOdsdTgE/VMY9Eu0v2WWgPca0bNQ14z6kPZLE4MAbz7/Q/49+///vnrcACJe3ikq7q4HG/Q/FIL8ScyfXEJx+MAn5LdOdAPs5H0CsIlplfCXVKj22tuK1ygvfv7PAdGyZBrTnRkbwhyV5PRze/SZiswH63i6i3YU9rm9wfLfb0LHrjbhmabdPHgkZtyD3E74ZlDNh9wrxGeVQ1V3bzsmaRbVlSI1sqPL+avNcMyG+lJAREjZpQye7p5/VwXZ0xmKLzjFPGDW572a3ewrbhS84JposdgimYB8WsRbPmsnGv+FyIY1IVd+kvzs81fP733+IKWVaZ5aUAwubElTmQOFZraqtqDvCiVNnB4j+sr0Lg+wlqrAkY0QEdvrYr/2ekjabx4tqGRRarzlVICmVxcWEq7DErNVOupuBEX6bjB4pUuPviQDm2odmjMgKg+546k0pxV25Wi4JfJVatkR8QMRhOWF1xOOo1Rp+AqjDQeO5GXHBuNr4Fb1RX1XlVhdYr3c5C9HiDRL26U5ucAH4Ls9QBLrfI6M2fg3rWSVwRjz1QPJi3QbFV+DtMrwG9OoUW2j4/2j+rKPiaThu2oqIDazX5INYzRcF6ov5jfzteqq35n1KNa+rFzPbZ6hlYDxPAjgGBoEtwt2lTFLox3TNRIGraVCJmiO4fvGSn2gEk7EVVFI4s2hy7EDPZF8C70l/EbGus54HgqQPaYboi55zJX+3H7OTHe2pu6ozoYvbVA7zHnGjPH9BZiqwqEkm3wiz2eTzzfEbslx6vkZnwzfpP45/U0+fg/v5/GpA==)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
