### ISSUE TITLE
[Bug Report][3.3.20] fill-height on v-container squashes children

### ISSUE THREAD

**Issue by Instinctlol** [vuetifyjs/vuetify#18405]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
If you put a `v-card` inside of a `v-container` that has class `fill-height` applied, for some reason this squashes the `v-card` contents.

### Expected Behavior
Shouldn't squash child components (`v-card`)

### Actual Behavior
Does squash child components (`v-card`)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVdtq20AQ/ZWxXmKDZZuklGKcQFtSSB/a0uQtzsNKGtmbrHbVvSh2E/97Z3WzJFJDoWCQ9szs7DmzZ+T7l8DoeP4xz2eFw2AZrCxmuWAWr9YSYFWEsZKWcYkaUuF4ArFgxlyug5QLEW6Rb7Z2HZTJVTrTx5xsFzJnFeS78D3k+/BDm9nmhhZ3tgVL2CNhylEkRxigCDOVoKCqmDEu1kE3uNTIEiXFnsJCsYTLzTDBCfSU7jX+clxj8tBPaClH4fkwgkyzSGAXFCwquVwPuVyt5l0FpOyftOXE4lnp5P/LOyHix5uHkgti3CqRoPZCpSUL7JXT8BbHk7IjDfNhIyLbWZOAhBtPL6GjRqnS2UBfrfpv+iOh4qeeXiWUp21cHKMx/WzDf6OvxPQG+xG7z33EuCjjZOveHTHNmbTefwILGpC+/m7qLd9IuOnqpeaQ4KP3aT00f4NVc+cXzeARspp3xpKWJtY8r3biLlfaQoIpc8LCS1UtYZYtYTyByysY1xiAb+wSUiYMThusnKYlSCdEizU3PIDr1vcrHCb0Ur1maLcqMcuGBICSt2UriUiLAfAUxiO75WbmCU1Ao3WaahwzymB9HFyC1Y6MewwbtHc8Q+XsuJY42FASnEzhfLFYTJp9h1ZIMyTjoser4gGjUQGvr3D2xTsZuGnTz4aVqufB3097I8E0sIbuLuWb2aNRkr6p5RHrIFZZzgXq77nlSpIn20atAyaEev5aYl5sXZ/2bDF+egN/NDuP0exqNKgL8nEbs97X5F4fvr79RhbrBOlDQ5+Kk8GfaJRwnmOV9snJhGh38kq2N5k3HvX7zlzvLErTiKpuq+nOOqA/ls8npB/pXswu6n7SLzhMAwJm76ih/nm+CB7+AAAy/DU=)

### Other comments
 To fix this, you have to apply `display: block` to `v-container`. However, I don't understand why `display: flex` behaves like that or if it is intended, it simply doesn't make sense to me. I have compared this behavior with latest vuetify 2.x, where it works fine.
 
 EDIT: if you wrap `v-card` with `v-row` and `v-col`, the behavior in 2.x and 3.x is the same, the `v-card` stretches over almost all of the width of the window. However, the codebase that I'm working with (2.x) does not wrap `v-card` with `v-col`, only `v-row`. As a consequence the `v-card` is not stretched over almost the full width of the window, but is rendered so that the input labels inside are still readable and not going into overflow.

The only solution I see for my problem within vuetify api is to wrap `v-card` with `v-row` and `v-col` and set width for `v-card`, I'm not sure if I like this idea, though. It's also not possible to vertically AND horizontally center `v-card` this way.

**Comment by yuwu9145** [comment]
`fill-height` use `display: flex`, and VCard is missing `flex-grow`. Try [demo](https://play.vuetifyjs.com/#eNqtVdtq20AQ/ZWxXmqDZbtJKcU4gbakkD60pclblIeVNLI3WWnVvShyE/97Z3WzJFJDoWCQ9szs7DmzZ+S7Z0+raPkxzxeFRW/tbQymuWAGL4MMYFP4kcwM4xkqSITlMUSCaX0ReAkXwt8h3+5M4FXJdTpTx5y09Jk1EvLSfw/53v9ANbD03/qrbku3yTdYmg6sYIf4CUcRH2GAwk9ljILKY8q4CLx+cK2QxTITewoLyWKebccJVqDjdqfwl+UK4/thQsc99M/GEWSKhQL7oGBhxeVqzOVys+wrIGX/pC0nFk9Sxf9f3gkRP149lOwQ4U6KGJUTmhnywl5aBa9xPCk7VLAcNyI0vTUJiLl29GI6apJIlY70Nar/pj8UMnoc6JVCOtraRhFqPczW/De6SkxtcRgx+9xFtA1TTv4e3BFTnGXG+U9gQZMy1N9PveHbDK77eqk5JPjofVqPzd9i9QC6RTuBhGyWvfmkpY4Uz+udWOZSGYgxYVYYeK6rxcywNUxncHEJ0wYDcI1dQ8KExnmLVdO0hswK0WHtDY/gpvXDCocZvdSvKZqdjPW6JQEgs5uqlUSkwwB4AtOJ2XG9cIRmoNBYRTWOGVWwOQ4uwChLxj2GNZpbnqK0ZtpIHG2oCM7mcLZarWbtvkMnpB2SaTHgVfOAyaSAlxd488U5Gbju0t+MK9XPg7uf7ka8uWc03V3Ct4sHLTP6uFZHBF4k05wLVN9zw2VGnuwaFXhMCPn0tcKc2KY+7dlh9PgK/qBLh9HsKtSoCvJxFzPO1+ReF766+UYW6wXpQ0OfipPBn6ilsI5jnfbJZjHR7uVVbK9TZzzq962+Kg1muhVV31bbncCjf5jPJ6Qf6Z4vzpt+0s87zD0CFu+ooe55tvLu/wA9L/6/)

**Comment by Instinctlol** [comment]
Thanks. However, when I render this template with vuetify 2.x, I get this (1. screenshot), which is what I want to reproduce for vuetify 3.x without setting width. Is that possible?

2.x:
![image](https://github.com/vuetifyjs/vuetify/assets/8536312/cd75d624-1811-4a55-9675-8a4aaf1bcc35)

3.x:
![image](https://github.com/vuetifyjs/vuetify/assets/8536312/06b6c266-ddaa-4cda-a894-3b813839efbf)

The blue stuff is the `v-container`.

**Comment by yuwu9145** [comment]
It's css question, remove `mx-auto`

**Comment by Instinctlol** [comment]
That's not what I want. `mx-auto` centers the form horizontally, but I want the form to have the same-ish width as in the 2.x screenshot without setting width.
