### ISSUE TITLE
[Bug Report][3.2.3] Select selection slot

### ISSUE THREAD

**Issue by camohub** [vuetifyjs/vuetify#18407]
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.2.3
**Vue Version:** 3.2.13
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
When I use this pattern from documentation it throws me an error on value.length. Can not read property of undefined.

```
    <v-select
        v-model="selectedCategory"
        :prepend-inner-icon="CategoriesIcon"
        :label="$t('category')"
        :placeholder="$t('category')"
        :items="categories"
        :item-props="true"
        item-title="company_category"
        item-value="id"
        multiple
        class="c-select-box"
        :dirty="true"
        append-inner-icon="mdi-chevron-down"
        @update:modelValue="setCategory()"
    >
        <template v-slot:selection="{ item, index }">
          <v-chip v-if="index < 2">
            <span>{{ item.title }}</span>
          </v-chip>
          <span
            v-if="index === 2"
            class="text-grey text-caption align-self-center"
          >
            (+{{ value.length - 2 }} others)
          </span>
        </template>
    </v-select>
```

### Expected Behavior
Expect to have value prop available

### Actual Behavior
value is undefined

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrq7VUTLWM9YzUYLQRgZKsQA4hgSr)

**Comment by KaelWD** [comment]
Well yeah you haven't defined value anywhere. Look at the example again.

**Comment by camohub** [comment]
Thank you
