### ISSUE TITLE
[Bug Report][3.3.12] navigation drawer is not displayed in my app and in Docs

### ISSUE THREAD

**Issue by simmisword** [vuetifyjs/vuetify#18403]
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
no steps .. navigation drawer is not displayed

### Expected Behavior
should show content

### Actual Behavior
doesnt show content

### Reproduction Link
[https://codesandbox.io/s/5-2-6-v-toolbar-v-navigation-drawer-forked-7dtsgl](https://codesandbox.io/s/5-2-6-v-toolbar-v-navigation-drawer-forked-7dtsgl)

**Comment by KaelWD** [comment]
> v-model="nav_drawer"
> nav_drawer: false

Yeah I wonder why it's not showing
