### ISSUE TITLE
[Documentation] VBtn API link is broken.

### ISSUE THREAD

**Issue by thomas-um-grant** [vuetifyjs/vuetify#18415]
### Environment
**Vuetify Version:** 3.3.20

**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just try to access this page: https://vuetifyjs.com/en/api/v-btn/

### Expected Behavior
Access to the VBtn API.

### Actual Behavior
Whoops page 404 displayed.

### Reproduction Link
[https://vuetifyjs.com/en/api/v-btn/](https://vuetifyjs.com/en/api/v-btn/)

### Other comments
I checked my cache is clean.

**Comment by mkraulich** [comment]
The link to the entire api is broken https://vuetifyjs.com/en/api/

**Comment by MajesticPotatoe** [comment]
For now, use the inline-api option (enable it in to the doc settings) till we can sort this out.

**Comment by thomas-um-grant** [comment]
> For now, use the inline-api option (enable it in to the doc settings) till we can sort this out.

Sounds good thanks, hope it's nothing bad :)

**Comment by MajesticPotatoe** [comment]
> @KaelWD I'm not sure you want to close this, the issue hasn't been resolved.

can confirm it has, make sure your docs version matches the latest 408aba9

**Comment by thomas-um-grant** [comment]
I can see the new commit, I guess it hasn't been deployed yet, right? Still can't access the page online.

**Comment by thomas-um-grant** [comment]
> > @KaelWD I'm not sure you want to close this, the issue hasn't been resolved.
> 
> can confirm it has, make sure your docs version matches the latest [408aba9](https://github.com/vuetifyjs/vuetify/commit/408aba9d125ff60e4d32646d002734d6d5b36986)

I can see the new commit, I guess it hasn't been deployed yet, right? Still can't access the page online.

**Comment by MajesticPotatoe** [comment]
<img width="372" alt="Screenshot 2023-10-06 at 12 23 00 PM" src="https://github.com/vuetifyjs/vuetify/assets/27827979/0e420e6f-69ed-4222-aacb-6e54a4e07232">
you can try clearing your cache

**Comment by thomas-um-grant** [comment]
> <img alt="Screenshot 2023-10-06 at 12 23 00 PM" width="372" src="https://user-images.githubusercontent.com/27827979/273275221-0e420e6f-69ed-4222-aacb-6e54a4e07232.png"> you can try clearing your cache

Looks I didn't properly clear it this time, thanks a lot, it works great now! :)
