### ISSUE TITLE
[Feature Request] V-Data-Table grouping behavior adjusting to behave like vuetify 2 grouping

### ISSUE THREAD

**Issue by Esgator** [vuetifyjs/vuetify#18414]
### Problem to solve
The grouping funktion of v-data-table is currently adding a group col with a button to toggle the expand of the group. In vuetify 2 where groups automatically expanded and didn't add a col to the table.

### Proposed solution
Having a prop that can controlle that behavior would be my suggestion.

**Comment by KaelWD** [comment]
Duplicate of #17863
