### ISSUE TITLE
[Bug Report][3.3.20] Unintended Japanese input with v-combobox behavior

### ISSUE THREAD

**Issue by TM0428** [vuetifyjs/vuetify#18421]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. enter text in v-combobox (e.g., "うれしい)
2. convert input into Kanji characters with space key (e.g. "嬉しい")
3. confirm with the Enter key, the same string is entered at the same time as it is registered (e.g. "嬉しい 嬉しい")

### Expected Behavior
```
嬉しい
```
Also, this is not confirmed, but is confirmed when you press Enter again

### Actual Behavior
```
嬉しい 嬉しい
```

### Reproduction Link
[<a href="https://play.vuetifyjs.com/#..." target="_blank">https://play.vuetifyjs.com/#...</a><br/>](<a href="https://play.vuetifyjs.com/#eNpNjs0OgjAMx1+l7oImCkY8mUnizTfwoB4Ah1mysWYrxITw7m4MI6e2v/w/eh+Ys3V2QUz7TrAT4yQ0qpJE8WgBeL8rEad1OmrTUilbYWc0Q12ZynxAd4okKlHw7E9/5gkt3YHEcJ4tSv3paiuRwAnqYrfUaCzBAFY0MEJjjYbE/5sEOYDPdQTaveEcFOvkKpQycDNWvVbJJhTESB/Gxi3L0zw9sjgPe/b8Aq0gVWU=)" target="_blank">https://play.vuetifyjs.com/#eNpNjs0OgjAMx1+l7oImCkY8mUnizTfwoB4Ah1mysWYrxITw7m4MI6e2v/w/eh+Ys3V2QUz7TrAT4yQ0qpJE8WgBeL8rEad1OmrTUilbYWc0Q12ZynxAd4okKlHw7E9/5gkt3YHEcJ4tSv3paiuRwAnqYrfUaCzBAFY0MEJjjYbE/5sEOYDPdQTaveEcFOvkKpQycDNWvVbJJhTESB/Gxi3L0zw9sjgPe/b8Aq0gVWU=)</a><br/>

### Other comments
I have observed the intended behavior on Windows and v2, but abnormal behavior only on mac in v3.
|vuetify|windows|mac|
|:-:|:-:|:-:|
|v2|ok|ok|
|v3|ok|ng|

**Comment by yuwu9145** [comment]
Not sure how to convert to Kanji characters with space key, could you please probably show a video?

**Comment by TM0428** [comment]
In Japanese, the space key can be used to convert various kanji and katakana characters. 
In the video, "嬉しい, 嬉しいこと, 嬉しい事, 嬉しい気持ち, 嬉しい限り" is a candidate for conversion.
The order of the keys pressed is,
U,R,E,S,H,I,I,SPACE,Enter

https://github.com/vuetifyjs/vuetify/assets/51225601/5de25864-bed6-47d5-aa53-11f6c3d835fb

**Comment by TM0428** [comment]
This is Expected Behavior.
This recording was taken at the following url.
https://v2.vuetifyjs.com/ja/components/combobox/#multiple-30b330f330dc30dc30c330af30b9
The order of the keys pressed is,
U,R,E,S,H,I,I,SPACE,Enter, Enter
The first enter is to determine the conversion candidates, and the second enter is a push to determine the string.


https://github.com/vuetifyjs/vuetify/assets/51225601/de893ff6-7514-4ae8-b9b8-02520985b66d
