### ISSUE TITLE
[Documentation] Wrong sass variable settings import statement

### ISSUE THREAD

**Issue by ahas** [vuetifyjs/vuetify#18429]
### Environment

**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
The import statement is relative path.
It should be "vuetify/settings"

### Expected Behavior
@use "vuetify/settings"

### Actual Behavior
@use "./settings"

### Reproduction Link
[https://vuetifyjs.com/en/features/sass-variables/#usage-in-templates](https://vuetifyjs.com/en/features/sass-variables/#usage-in-templates)

**Comment by KaelWD** [comment]
This is correct if you want to use your customised variables.
