### ISSUE TITLE
[Bug Report][3.3.20] Vuetify V-data-table can not control the values of the show-select checkbox when using the item slot.

### ISSUE THREAD

**Issue by bugraYvz99** [vuetifyjs/vuetify#18434]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

## How we control show-select checkbox and vmodel array
* Delete the template and try using the default data table:

Remove the existing template and experiment with the default data table settings. This can help you understand the default behavior and how it interacts with your data.
* Utilize the item-template and observe how **'show-select'** and **item template** work together:

Implement the item-template feature and observe how it interacts with the **show-select** checkbox. This will give you insights into how the checkbox and item template are related and how they influence the display of your data.
* The selected property on items does not affect the selected array:

 Notice that changes made to the selected property of individual items do not impact the selected array. Investigate this issue to understand why modifications at the item level are not reflecting in the overall **selected array**.

### Expected Behavior
Selected property on **show-select's** checkbox should be able to control from us

### Actual Behavior
We are unable to access and control the **show-select checkbox** from our end. Additionally, we are struggling to understand how the **v-model array** operates and where its data is stored

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9l91v2jAQwP8VL9JUJjUBAqElYpOmdh9d97DXqe2DSQ7IauLIMbQM8b/vTD5ITMzoqJaXxvfl+/nu3HC3tlIRtD8mibNcgOVbIwnzhFEJH+5jQkZLO6SS2pKOGSgBIUt7zkNg7++tFBgEEsJ7K9MEjKYpylG8pDLisd0tVP4MaAhCafO3UhPhhkoeQpqCkKViK7cTEHZCp4AGXlVjLylbKGlM51AoBMiFiG0+/oV5ZaJ0xp/sLFEl2EIhVgGJNCnjcpsEBksETzCB3ErZifIdV29sm8RcEphMMB7hMSmOgFAh6IrYdtVchpXV9iyDGQSPY/5cFVdPdLu/o5Jx9MMtHj+MUlWMsG5eSOvmtf0JWa9Jww5ks6ml2d7lWaVp13AUXD2cKgSG+qtdQBkXEaTH2E6oPC6kGKdH2OGrhCg+JmQksLqaHS6KdsDX2pjgme3mpJgcTCssh2IubZck1HbL9holAtSulTqM2kpWRFT+uKjthcs0EFEit1bwnHAhSQgTumCSrLPAKpPWu2JVjMVujVORb+mTu4fznTgfTZRWG6Lipx4ZSQY+ObvO5pW0up3OFCOKZRRP351VwqmHsmgao3UqqZC68hFWqFKNU9dsaqt1ueVV3jpn52VciENcZYGKzjozBviM/dRSSTb6Y7eZXa9Ujx1w3vag2f1H3nrmAHlzmkPcqJZsvTX5q46tO1dLW9yuh2urSqGOSfDfEJOffLrYL1pxyj7pekNNhyfok4HT2XPBs/GJ29fkObJP+nsuigZ30KS7vp1QlsKhpmkEuwmABALonKQ0Dp+iYGamc3sXTXRDE92eeYWu91/oPuFdE4kDRAO3iahrLpied4m075Ih6WdwKtLVIgnoo3Y9VJl6Ha+JqefomeRIgxdX6fKVkb7gNQlijF2Is2vE8gYvK1VfH8WSq+foqrz79B1OBfsGjK3IGGh8gOuisVwdE9bQeGXsu2RYuvRUqu+csSjhyQGmYeNYdRxdXDDpHbVjaiTSw5xK9JXHsAr4fGxG6nf0HPOpMiBdGqdq4OgFz6D6uvhUqmseLw78r+p7jUVyPVPnefrtXLkomgfKfe1C3UbyFj9JjExet7FKrvGSGOiHXjLp9cuI/vWG2H145L8sMiUuRu3y69XanFs9p+f0reyv27Ee/gAdlcVI)

**Comment by ricardo17coelho** [comment]
@bugraYvz99 is not possible to use it like this ?
https://play.vuetifyjs.com/#eNq9lltv2jAUgP+KF2kqlZoUwmVt1E2b2l267mHSnqa2DyY5QIaxI8fQMsR/3zG5EExMQVTjpfa5+Xw+57i5XzipDM8/JYk3m4ITOFcKJgmjCj48cEKuZm5EFXUV7TPQAkJm7kREwN4/OCkwCBVED06mCRlNU5SjeEZVLLjbKlTBCGgEUmvzVamJ8UAtjyBNQapSsZK7CUg3oUNAg25V484om2oppxMoFBLUVHJX9P9gXpkoHYknN0tUC1ZQiFVAIk3KhFolgcESKRJMILfSdrJc4+6N6xIuFIHBAOMRwUlxBYRKSefEdavmKqrsVncZjiAc98VzVYxXsLrQkmiVhBenv/LYjVzAFUhO2S2meloQlyGiONUlitb+aOYVUtP8Y8jicFzaKjEcMsjOe/m0TajzNVWV/XwDXl/FYkEqmemykeXyRbuQMiFjSPexHVC1X0jZT/eww6WCmO8TMpbYC4YdbormweXGUOGdraeqmDNMKypHaKJcnyTU9ctmvEok6FPLjtPHaVkRUfvjZuMs3KahjBO1soLnREhFIhjQKVNkkQXWmTROi10xROs9zlB+ZEDuH8/W4nyQUVptiIqf/qlYMQjIyU023aTRajaHGFHOYj48PamE0z/K4iFH61RRqUzlGOao0o2zqVlu7Bblkdd565yclXGBR7jLAhWddWIN8AX7qaGTrPXHbrO7Xuse2+G86kG7+8+89ewB8ua0h7jVLdl4a/PXHbvpXC1t8Rbvrq0uhb4mKf4CJ7/FcLpdtOKWA9LqXho6vMGA9LzmlgveTUD8jiHPkQPS2XLRNHiCIV337YCyFHY1TS3YbQgklEAnJKU8eorDkZ3Ob7+ro7u00W2ZV+ja/4XuM741sdxB1PPriFr2gpl5l0jbLhmSeQfHIl1Pk5COjeehytRuduuY2p6ZSY7UO7hKF6+M9BWfSZB97EKcXStWt3dYqTrmKJZcbc9U5d1nnrALDB+Q/MMjIEpOD6f+DozNSR8o3wH9rraWTRvzpfU92XbJmE3psbX8IRiLE5HsYLqsnbmmZ4oLJrPd1ky1RGaYY4m+CQ7zUEz6dqRO08wxHzkL0oV15HqeWfAMqmOKj6W6EXy64x9Zp1tbJL9r67yu+XRXXpH6afNfu1B3sbrD7xUrU7dVWyXf+oL0zEsvmcz6ZUSHPB/1XyXLbJEpcXN1Xn7aOsszp+21vY6T/fWbzuM/uvfeGQ==
