### ISSUE TITLE
Buttons active state have an ugly focus box on Firefox

### ISSUE THREAD

**Issue by weijarz** [vuetifyjs/vuetify#1843]
### Steps to reproduce
Press a button.
![vue](https://user-images.githubusercontent.com/8944061/30772264-b67dc4d4-a08a-11e7-9dcc-9c238a0f2e34.png)

### Versions
All versions.

### What is expected ?
Should hide the default focus box.

### What is actually happening ?
Button has a default focus box.

### Reproduction Link
<https://vuetifyjs.com/components/buttons>

**Comment by KaelWD** [comment]
Could not reproduce in firefox 55 on windows 10

**Comment by weijarz** [comment]
@KaelWD Firefox 55 / ArchLinux 
Do not need to press tab first.
