### ISSUE TITLE
[Bug Report][3.3.20] Syntax Error in `$variable: false` in the scss file

### ISSUE THREAD

**Issue by njzjz** [vuetifyjs/vuetify#18436]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Edge 117.0.2045.47
**OS:** Linux

### Steps to reproduce
I am following the [documentation](https://vuetifyjs.com/en/features/sass-variables/#basic-usage) to use SASS variables. I just copied the codes from the documentation:

```scss
@use 'vuetify' with (
  $variable: false,
);
```

### Expected Behavior
No errors.

### Actual Behavior
I got the Syntax Error in the build time:
```
error  in ./src/styles/main.scss

Syntax Error: This variable was not declared with !default in the @used module.
  ╷
2 │   $variable: false,
  │   ^^^^^^^^^^^^^^^^
  ╵
  src/styles/main.scss 2:3  root stylesheet
```

### Reproduction Link
[https://github.com/deepmodeling/dpgui/actions/runs/6477541384/job/17587893900?pr=279#step:5:42](https://github.com/deepmodeling/dpgui/actions/runs/6477541384/job/17587893900?pr=279#step:5:42)

### Other comments
I am unclear whether it's a bug or a documentation issue.

**Comment by KaelWD** [comment]
Yeah it's just an example

> specify the variables you want to override

What are you expecting that one to do?

**Comment by njzjz** [comment]
Thanks, I just realized `$variable` is not a real variable.

**Comment by treardon17** [comment]
@KaelWD I ran into the same issue following the docs. The wording in the docs makes it seem like that line needs to be copied verbatim into the scss file, and my assumption was that it would turn something off in the build. The next code block gives an example of a real variable you can override, so my though process was this:

1. I need to copy the first block to enable scss variable overrides
2. From this point on I need to override specific variables using the following syntax:
```scss
@use 'vuetify/settings' with (
  $button-height: 40px,
);
```
