### ISSUE TITLE
[Bug Report][3.3.19] VDataTable always shows loading text when loading prop is set

### ISSUE THREAD

**Issue by mathiasstamm** [vuetifyjs/vuetify#18445]
### Environment
**Vuetify Version:** 3.3.19
**Last working version:** 3.3.18
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on the "TOGGLE LOADING PROP" button and compare the results between vuetify version 3.3.18 and 3.3.19.

### Expected Behavior
Table rows remain visible while loading, just grayed out.

### Actual Behavior
Table rows always disappear, default loading text is shown.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9VFFv2jAQ/iu37IFWAqIOJm0oRGu3CU1DBW1oL6UPbmISq44d2QaEEP995yRtLlNb8TTlIb7zl7vvu8vd3TGwJgmvy3K42/JgEkSOF6VkjsdrBRDtBqwsq2NlJFo5JhQ3jQudW/l8RksKYqFtndEqi38LlXD4w40VWsFoOBpefY7C5nICq5yDYw+Sg0/AlQMm9+xgaahUWKTCmbGwzwVCpWapUFkfhOtZUNpBqa0VPorTYAXKOEDOdhwBkBl24CmNp7duSIiHHeav6bjhG234OQKEBa2QgOFYzaSbei9cDg4/aSQMrET2+AWTFpnzV4lFIal2VMYrnWVebhsKrMPeAVMpJDlTWX25qwtvh1H41MyqnUbvqWjfX9rNyvXgFHxJpEgep+vg4hKm8XOuKbxrjusAhUttEFIaUTBz8B7JrEVP4QajdUDDAsSrxWw2/w7zxfW3H7czWP5aLKOwykaBlB3eUnrepvzPkpOPY1987H1bMKx9FOLFP7pT5tig7ulE4FB4JdUblU1yzlKsKbqak3c2EdHZViV8Q8GbFP8Pv05QDPs0/PC+gcRft9bpomHR2Q1UVkvm7I7Vt3SdeE+9bTqZ0LSJEaXzk7Gt/18cbm0cHHG8NnCCjUGKPVxgPQ8HP4S27fDUoy42OFz8kt43pcH7u5rSER75YQI9xQre64MTTnI0b70Jp34XhP95QlHLym5g9zRP1RWaxcfHL3DpSh+hioT2B5qkwfwUe0Eg4xcgN0zhQ0CjF0BzXmhFMB8JU9xjVX2xssGpH/jlNg7q99Wn4P4vOL/Vog==)

### Other comments
https://github.com/vuetifyjs/vuetify/commit/deb7683b4c9c2633d67c55c2ec1d858edc77ba8f

I belive that this commit introduced the change which always hides the table rows. If the loading prop is set, the rows are always replaced. There should be an extra flag which allows the actual rows to remain visible, or something similar.

**Comment by diaeai** [comment]
+1

**Comment by hendrikbl** [comment]
Just upgraded from vuetify 3.3.16 to 3.4.0 and this behaviour still exists. In 3.3.16 labs version it was working as expected.

**Comment by dm4t2** [comment]
+1

Always replacing the rows causes page jumps and feels very disturbing.
It would be better to display the rows unless the loading-text prop is set.

**Comment by gduliscouet-ubitransport** [comment]
I had the same issue when upgrading. @nekosaur this functional change of the loading came with [this commit](https://github.com/vuetifyjs/vuetify/commit/deb7683b4c9c2633d67c55c2ec1d858edc77ba8f) to handle the loading-text prop. Was it expected ? What do you think about @dm4t2 proposition ? Would it work to check for `props.loading && (slots.loading || props.loadingText)` ?

<img width="707" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/101416921/51e022c7-bc8e-436f-abe8-8af8605467b1">

**Comment by BenShelton** [comment]
The documentation is also inconsistent with this behaviour, for example the `loading` slot states at https://vuetifyjs.com/en/api/v-data-table/#slots-loading:

> Defines content for when loading is true and no items are provided.

Other documentation talking about the `loading` prop says similar things, the loading text is not shown if there are items.

To line up with that there'd also need to be a check in the render function mentioned above that there aren't any items first before showing the loading slot or loading text.

**Comment by abdu-udwz** [comment]
Additional gifs to further clarify the expected behavior. A comparison between the old Vuetify 2 and the current behavior. 

In Vuetify 2 docs the example:

![opengl-rotating-triangle](https://github.com/vuetifyjs/vuetify/assets/22858957/beb63de6-44dc-4fdd-88df-3697a23e38ba)

In the latest version of Vuetify 3 docs example:

![opengl-rotating-triangle](https://github.com/vuetifyjs/vuetify/assets/22858957/2eda2689-efd4-4fb8-a27e-f2aef2a7c8fa)
