### ISSUE TITLE
[Feature Request] V3 v-sparkline

### ISSUE THREAD

**Issue by pilotkid** [vuetifyjs/vuetify#18448]
### Problem to solve
In past versions of vuetify v-sparkline was available. However, I do not see it in the docs, or the roadmap for V3. Is it going to be added?

### Proposed solution
Port V-SparkLine from V2 to V3

**Comment by websitevirtuoso** [comment]
Yes I think it will be added but later

**Comment by danielamguerra** [comment]
Any prevision? I'm migrating my project from version 1.5 to 3 and we use v-sparkline.

**Comment by johnleider** [comment]
duplicate of #13507
