### ISSUE TITLE
[Bug Report][3.3.20] v-data-table checkboxes sometimes don't work

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#18442]
### Environment
**Vuetify Version:** 3.3.20
**Last working version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Ever since v3.3.20 I noticed v-data-table checkboxes don't always select as they should. 
An example is in the vuetify documentation here:
https://vuetifyjs.com/en/components/data-tables/selection/#selected-values

If I select, Frozen Yogurt, then Eclair, then the 'select all' at the top of the table, it loses state and everything becomes uncheckable.  What's weird is that if the example is opened in the vuetify playground it works fine.  (So the reproduction link can't reproduce).  

I have tables in my real code which behave similarly ever since 3.3.20

### Expected Behavior
Checkbox state to work

### Actual Behavior
Checkboxes aren't checkable or become out of sync with the 'select all' checkmark at the top of the table

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlt9vmzAQx/8VC2lqKxVCCKQNyipN7X503cNep6YPBq4pK8HImHRdlP995xgIEIwSabwE3/nOH399Z/K4MXIejj5lmbUuwPCNuYBVllABN4uUkPnajKigpqBBAtJAyNpcsQiSjwsjhwRCAdHCUJ4woXmOdjSvqYhZao4rl/8CNAIuveVb7YlxQWmPIM+Bi9qxs5sZcDOjS8AJXtNjrmlSSGtKV1A5OIiCpyYLfiOXMuUv7M1UoNJwMx81d1TtMaQ8qvFXwnRIRk1nYez8OCPjcLPZkGrDZLudj6RtF44ZZTwO5qOGeDjMQx5nYjcL/mSMCxLBMy0SQTYqsSQh5xfVsNrBfowbKNf0yePT5d5cqojWvY004+QjYpGAT87ulLTkfGzbS8zI13G6vDhrpJMPTeJlirNzQbnoOl/hHV1S7LZn2xpt6iVvacJ4DPnZZZ0X0ghHKlFYubUJvlDklZC98c9U6ENvKQ/ygWA8rWBg5Z+cCYjTgQSZmqFPcc8Zxn/Qxcfobgc3j7ZqhOGzlUchZeLsL6TkF1sWh4dWqeyTsTfr+FBBn0wt+yAEtfGJ43bs5ZZ94h6EyN3gCkNl0Yt+HwIJOdAVyWkavcXhi57fmVz18c90/AfTG/yT/8T/GS+MmA8wT50+5rFe9C5ZDX0YoqDbuzwG+rbIQvraaeIm9cT2+qgnVlfREnp6stLXJ0N/xesKeIC1gj2kBfemp8ntdluiJp9YXVdZI+0VjkH/DknyTgKg6QD5Va/ktg58pm3OwxAF3rYew/2DJUmcsWyAetZb3rbVNVfU7XNvUvcyt9Mcw/yNpfAeslWgh3btLkVZ3Rroa211T63uoSlst20+hvuOpcXA3e16vUI7nq4+vPZd1mrJ/sJ2Thf7IRYP+BHWUnvjXqUdbTtOu3rW1N0zUMz6Xtx/TLfqRTlxMB+Vf8mM7aUxsSaWa6hfxzae/gGX9b8x)

**Comment by Redpoint1** [comment]
It's funny that it works for me in the playground. It stops working there when you select Vuetify 3.3.19.
