### ISSUE TITLE
[Bug Report][3.3.21] v-data-table pagination footer should be hidden with `hide-default-footer`

### ISSUE THREAD

**Issue by NickdeK** [vuetifyjs/vuetify#18450]
### Environment
**Vuetify Version:** 3.3.21
**Last working version:** 2.7.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-data-table and use `hide-default-footer` with the intention to not show the footer (with pagination).

### Expected Behavior
Footer with pagination shouldn't be visible

### Actual Behavior
Footer with pagination is visible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNlltv0zAUx7/KUSQUJrVZLk23hg2ENmBjPCDEC1r74CannbU0jmy3qJR+d5x7mphlT0nPxf6d/zl283gwBA/PP6aptduiERhXEjdpTCS+nycAV7sxSVOg0fXcoIlIKce5kXtyX0QkGUuyjLEwAQRPSCLkQsWXb3Oj9lG1duaJUCCXPc84RT5OyRpVyNhpvE80wnGEK7KN5XjFmEReucKYiGxFjHFHJGVJk3deFHCeV6Der85blamfIuQ0lSBQblOISbJWy2RMeRrdpIxLOADH1QjkPkX4gSs4woqzDZhKKjNbBArXrZLhZ6bCXV4yXMOhYHjGfQBCcpqs3xUWSWWMHRuJ6Tr5EIApJOHShL9gYhKZpVcokGxtFbBkLEaS5I5jsX/IEiGhlDrokjwuFMtjsU6JVCOYtyiyNsBbx7bXSge+U0hn5qiKy7Fqqtpc8QSwIrHA2p7XaiZkg1XssXwe6i1vSMw4RWGO6tWzSkdlcli5NamfiSLN8LSZK6J00+3Hl+KFtDDz6xK/czVlNHkhNS0idMn3nKnMN//LpMpdpS1UL5s2ludC9UyN3dtu3zJpMyE4+4MJ/GLrbbstlXYBOP6stipdAphaditMVRyAO6ktZSEBTFphGaPay+m1sgPzFeN4D0s1lDoS78I/JbH7JDMNSTusJLGHSB6ofFBDoKHwnctTClcjyLQhrTEuuhDTIYhP6j6iXAfhTt1TCEfXFa8P0Q4rMS6GML6og4x8ydUdoG2LPx1mmTRDVLN4VmOsJmRQk/sQIVQoGxAkiX7T8Emrj9eonTPN+kitkNbQNpq9dmi/sTimKUu12sw6fbKtxlCNbDNPzch2KdwhipttGpLn+rI8gbA758azmtKrgX2dGJdDGHcswX3INksdyMTuHB2vr8alBmRqNQWUIBN/iOSWJVvtAZ74nZ64fn84fEenR29e3U5fFmfZl0HxLaD++Y3jyPAsz5oYxdN1jMU/dRqPng==)

### Other comments
In Vue 2 the footer could be disabled with just the `hide-default-footer` prop as far as I know. The goal for me was to get rid of the pagination when showing all items. The only way I can achieve this now is by adding a empty `<template #bottom />` which removes the footer.

**Comment by NickdeK** [comment]
Ah, I see now this prop doesn't exist anymore. I assumed my editor would have warned me, my bad!

**Comment by dh336699** [comment]
@NickdeK What's the new attribute about it
