### ISSUE TITLE
[Documentation] (Small) Location prop description missing.

### ISSUE THREAD

**Issue by javacatknight** [vuetifyjs/vuetify#18455]
### Environment

**Browsers:** Edge 117.0.2045.43
**OS:** Windows 10

### Steps to reproduce
Open documentation page (repro link), observe "location" prop.

### Expected Behavior
Display the description.

### Actual Behavior
"MISSING DESCRIPTION (edit in github
)"
https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/VNavigationDrawer.json

### Reproduction Link
[https://vuetifyjs.com/en/components/explorer/v-navigation-drawer/](https://vuetifyjs.com/en/components/explorer/v-navigation-drawer/)

**Comment by MajesticPotatoe** [comment]
duplicate #18248
