### ISSUE TITLE
[Bug Report][3.3.21] title.attr doesn't work with SSR / SSG

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#18457]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Inspect element / View page source.

### Expected Behavior
Anchor's title attribute should be set.

### Actual Behavior
Anchor's title attribute isn't set.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-euha7v?file=app.vue](https://stackblitz.com/edit/nuxt-starter-euha7v?file=app.vue)

### Other comments
Usage of `title.attr` alongside `title` throws the following TypeScript error: `An object literal cannot have multiple properties with the same name`.

**Comment by KaelWD** [comment]
That would be a vue bug, you can see it isn't even compiling the attribute for ssr: https://play.vuejs.org/#eNp9kU1Pg0AQhv/Kuhc0sXDojVATNU2sMWrU1MteCAywlf3I7lDbNPx3Z0FaD6acmHmeXd4ZDvzW2njbAU955gsnLTIP2NkboaWyxiE7MAcV61nljGIRqZHQQhdGe2TK12wR+GX0AG1r2KdxbXkRXQmdJeN1dBEVCMq2OQJVjGXrJ+kDYPSMxYqEsWbMOrCgy5mkbywEV6WcNUaB4JOAElsgsu4AZbU/gXQgcY7oCEe/fB+djIayEmoQrU+ThKYJxsbHhVGTlYwhkylllhzT82uOnmJVso433mja2iHIgtN5K1twLxYlrUbwlA0ksJw28/049NB1cD31iwaKr3/6G78LPcFfHXhwWxr9yDB3NeCIl+/PsKP3I1Sm7Fqyz8A38KbtQsZRu+t0SbH/eEPa1fDvpa4//HKHoP00VAgazH7wBacN3p8Z/RR3Hs+Hc0L3vP8BO9vNwg==

> Usage of title.attr alongside title throws the following TypeScript error: An object literal cannot have multiple properties with the same name.

Should be reported to https://github.com/vuejs/language-tools

**Comment by bogdanciuca** [comment]
Thanks for the quick reply, I'll open a issue in the upstream.
