### ISSUE TITLE
[Bug Report][3.3.21] Nuxt: created a custom component extending `VTextFiled` received hydration warning

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18458]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Reload the page and check the console 

### Expected Behavior
It is necessary to render the slot on the server side. 

### Actual Behavior
When I used slots such as `append` and `prepend`, they did not render on the server and resulted in a hydration warning.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-onjpcp?file=components%2FAppTextField.vue](https://stackblitz.com/edit/nuxt-starter-onjpcp?file=components%2FAppTextField.vue)

### Other comments
While working with Nuxt, I received a warning related to the custom component I created. The warning was about extending VTextField through hydration.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/7095
