### ISSUE TITLE
[Bug Report][3.3.21] VChip on close removes adjacent chip too

### ISSUE THREAD

**Issue by 09Skyfall** [vuetifyjs/vuetify#18466]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a list of v-chips using v-for directive
2. pass a callback to the click:close event
3. the callback should reassign to the list used in the v-for directive the list itself filtered to remove the closed chip
4. close a chip that has another chip to its right

### Expected Behavior
Clicking on the close icon should only remove the clicked chip

### Actual Behavior
Clicking on the close icon removes the clicked chip and the one on its right

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUUtugzAUvMrUq0RyQPm0CwRRqx4jycIQI1DBtmyDqBB3D2B+WfnNvN/M860lRif+j1JeXXESkNDyUhXM8utdAGF9YEqN4QgSKSzLBdcTBbQtmNbsH103U0NdlqsZAvUhlTq6EwGZuuo7WbNJwYzps2VzOL3z0rC44CvznRR58hcMCd43SPE7RDuxX9sWXb2M+DqoE70yhH68ZELf6ZtdDfDN1sA416G/uUYPTaJzZcci3iipLZ48ZVVh0bphT2bZbj8jQHNbabFiOPsBbkeKE8WZ4kLxSfH1oHPNdMduIkpuM/k0wTpk8V2VMdebbYDNcuO5/4g2wEvzwnK9axBd0eAjijA1L0unbe7tJYT+YpZ0lJy9s3ch7j0dyeMFsbOlpw==)

**Comment by GaetanWi** [comment]
This is most likely because you're using a `v-for` without specifying a `key` attribute. Adding the `key` attribute helps out and fix the issue on your reproduction link @09Skyfall 

The issue is more Vue related than Vuetify (if we can call this an issue, as the key should be mandatory when using the v-for directive).

**Comment by sungwoong-Noe** [comment]
I am experiencing the same issue, how did you resolve it?
