### ISSUE TITLE
[Bug Report][3.3.21] VBreadcrumbs content overflow

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#18464]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Resize the window.

### Expected Behavior
`VBreadcrumbs` items should be visible and accessible.

### Actual Behavior
`VBreadcrumbs` content overflows, therefore some items can't be seen / accesed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqF0UFLwzAUB/Cv8ieXKowWnafSCYp48DrcZd0hZq8SXJqQvEyk9LubtgriDjn9ycsvL+FlP4jgVfXgXHmOJGrRMBl3kkz3bQ80u0dP8qh8NG8BtU6bYdOKOVuBKqGm+nMiLYPy2jECcXRzD22c9YwBnjqM6Lw1KNJlxcQBZfvAmDtiM5mr/VQGhiUA1nyiGsUu0su2WC3l8Scv1LOXhj6t/whZmhqy7r6y7smqaKhnydr2ea09KdZnyj9gaw3h+Ouz/DXI93/qcD39wDLzNG0xrsS6XJd3YsnbG3H4Bjy7kWU=)

**Comment by websitevirtuoso** [comment]
I think current behaviour is correct. and you can set your own style on component and get desired behavior.
personally I don't want to see scroll.
I want to get break into multiple lines. and I can make it via css

**Comment by bogdanciuca** [comment]
> personally I don't want to see scroll.
Neither do I, however it will only show up when the content overflows.

> I want to get break into multiple lines. and I can make it via css
It doesn't break into multiple lines, it extends outside of the screen. This is the other approach I've considered, so I am open to suggestions / feedback.

**Comment by despotbg** [comment]
I use this CSS code to break up breadcrumbs into two lines 

```
.v-breadcrumbs {
  display: inline-flex;
  flex-wrap: wrap;
  max-width: 100%;
}

.v-breadcrumbs-item,
.v-breadcrumbs-divider {
  white-space: normal;
  flex-shrink: 0;
}
```
