### ISSUE TITLE
[Bug Report][3.3.21] VBreadcrumbsItem anchor missing title attribute

### ISSUE THREAD

**Issue by bogdanciuca** [vuetifyjs/vuetify#18467]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Inspect element and check the anchors.

### Expected Behavior
Anchors should have the title attribute set.

### Actual Behavior
Title attribute isn't set on anchors.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9j0FrwkAQhf/KYy5pQbK09hRioT32WvBiPNjtpm5x3WV3IkjIf3c2UVAQT4958+Yb3qqnFLX6CKE8dIYqqtm4sNuweW/2QL38jGbzq2PnfhIqK8u0aGjUhqAkVKurCxmTjjYwkuEujAzrgo+MHtG0GNBG71DIsyLHAe33iTESsciZp1W2gX4SgC3vTIVi2Zmv72J2sbeSFXfLHFKllBD/U+nj3yUxnPUeh217fETKe6Fp725p6+dceKoo5WiY0bycl2806esLrU+cmmnt)

**Comment by johnleider** [comment]
Use :title.attr

https://play.vuetifyjs.com/#eNp9kctugzAQRX9l6g2JFEzTdIVCpW67rdRNyIKHSablYdkDUoT4944hKKJNuzLcOb4zd3zohTVZ8Kq17FolQrEnVekyIfUS1wD7zk+NSvLMtFVqR4nFGYHOLxoTxWKFLG0A14A1uG8bCwi/1IVrGIvrvZ92fo4d5sqwDRaOhIcogkfm98FdkH3+cHI95xKwX4p17hydLG6FMEebpKUaaxBxt3FYWar6RGfwYbugCalUMiFyGR0pR+XG/BrUQfOWguUmlyRrC4B/bWZQE1hFrR6vYKUbQ9CDUQUMUJimAo9fyZvWkDW1pSkARI5ZHabO/TzeOG0I3ker3t69zSyfmWX1TKRtGATs+GllY04zMVzPez6ExeU/J1dnt6yplm7HtQs8ReRwYtiIndzJZzGdT1tx/Ab4fcv4

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by bogdanciuca** [comment]
@johnleider `:title.attr` doesn't work in this case - title is set on the wrapping `<li>` instead of the anchor.

**Comment by johnleider** [comment]
@KaelWD Could you chime in?

**Comment by bogdanciuca** [comment]
@johnleider @KaelWD Any suggestions or recommendations?
