### ISSUE TITLE
[Feature Request] Autocomplete should display as much text as it fits

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#18470]
### Problem to solve
Currently `v-autocomplete` cuts off selected text way too early, even if there is some space still available between text and down arrow. And if "clearable" feature is used, text gets very short.

### Proposed solution
Increase the width of text displayed in autocomplete. That would benefit users of mobile devices, where even 5 more letters make a huge difference. Also it will prevent issue, when text fits during entry, but is cut off after moving focus to other element.
![Screenshot1](https://github.com/vuetifyjs/vuetify/assets/79141/9d0610ef-1147-452c-b48c-597da459b6b5)
![Screenshot2](https://github.com/vuetifyjs/vuetify/assets/79141/aa8078df-f884-4a30-a07a-1f0d1ede97d6)

**Comment by KaelWD** [comment]
#17688

I don't know why it needs `max-width: 90%`, @yuwu9145?
