### ISSUE TITLE
[Bug Report][3.3.21] Vuetify 3 - Lighthouse Performance issue

### ISSUE THREAD

**Issue by diegogava** [vuetifyjs/vuetify#18478]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
# Nuxt 3 Minimal Starter

Look at the [Nuxt 3 documentation](https://nuxt.com/docs/getting-started/introduction) to learn more.

## Setup

Make sure to install the dependencies:

```bash
# npm
npm install

# pnpm
pnpm install

# yarn
yarn install

# bun
bun install
```

## Development Server

Start the development server on `http://localhost:3000`:

```bash
# npm
npm run dev

# pnpm
pnpm run dev

# yarn
yarn dev

# bun
bun run dev
```

## Production

Build the application for production:

```bash
# npm
npm run build

# pnpm
pnpm run build

# yarn
yarn build

# bun
bun run build
```

Locally preview production build:

```bash
# npm
npm run preview

# pnpm
pnpm run preview

# yarn
yarn preview

# bun
bun run preview
```

Check out the [deployment documentation](https://nuxt.com/docs/getting-started/deployment) for more information.

### Expected Behavior
Expected Google Lighthouse performance higher than 90

### Actual Behavior
Performance less than 60

### Reproduction Link
[https://github.com/diegogava/vuetify-performance-issue.git](https://github.com/diegogava/vuetify-performance-issue.git)

### Other comments
When I run the application with the Vuetify styles and the material icons the performance gets lower than 60 (for mobile devices). When I remove the Vuetify styles and material icons, it gets 90 or higher.

**Comment by websitevirtuoso** [comment]
Lighthouse provide many detailed report if you would attach it would be great

**Comment by websitevirtuoso** [comment]
I see your issue but I don't think that we may help here.

1 You have to configure server compression (gzip, brotli)
2 Set resources caching
3 Don't load unused js/css code. in vuetify we have ability to disable css utilities. (Personally I migrated to tailwind because in bundle we get css which we used only)
4. Solve problem with font.

**Comment by KaelWD** [comment]
Here's one that's configured correctly: https://pagespeed.web.dev/analysis/https-tryvuetify-com/24cljgcifc?form_factor=mobile
Yes it is still pretty low for such a simple site but 80+ is definitely achievable.

**Comment by diegogava** [comment]
@websitevirtuoso @KaelWD thank you for your responses!

I have a few more questions, if you can answer:

@websitevirtuoso How do you use Vuetify 3 together with Tailwind? Could you show me an example?

@KaelWD Could you show me the configuration files of [https-tryvuetify-com/](url) project?
Configuration files like nuxt.config.ts and plugins/vuetify.ts.

**Comment by websitevirtuoso** [comment]
I have give you working example but I can point.

1 - Install tailwind
2- Remove all vuetify styles and include styles without untilities
In your scss file
```
@use 'vuetify' with (
  $utilities: false
);
``` 

I have next files which I include in my main.ts file
```
import './modules/shared/styles/vuetify-base.scss'
import './modules/shared/styles/tailwind.scss'
import './modules/shared/styles/styles.scss'
```
I think that's all.
I found 1 issue in missing elevation classes so I had to implement my own elevation classes when I use prop elevation on many components
here gist for elevation classes
https://gist.github.com/websitevirtuoso/4f0e1d481b34d72d42721f67740e4271
