### ISSUE TITLE
[Feature Request] VDataTable item-value - different values for different @update events

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#18475]
### Problem to solve
VDataTable prop "item-value" prop can be set only for one attribute (i.e "id").
But i would like to pass different attribute on @update:expanded and another one on @update:selected - i.e "id" and "name", because for me it's neccessary to do different things on these two events.

I found out that I can pass some item using @row:click, but it is not same as @update and also it's triggered everytime it's clicked on row.

### Proposed solution
It would be nice if I could set it like this or something similiar:
item-value:expanded="name"
item-value:selected="id"
Also, this settting would be nice for other neccessary v-models like groupBy, etc.

**Comment by KaelWD** [comment]
I suggest using `return-object` and extracting the appropriate field yourself.
