### ISSUE TITLE
[Bug Report][3.3.21] v-data-table item.data-table-expand is not toggling the row to expand

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#18485]
### Environment
**Vuetify Version:** 3.3.21
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
- create data--table component with data
- click on the item expand icon

### Expected Behavior
The expanded item need to expand and render the expanded-row section

### Actual Behavior
The item does not expand

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVlE1v4zYQhv8KIaBwAliyHSfZRvCmLdJtm6IFeuil2OyBlsYKEYoUSMrZ1PB/71ASRUqWm/aSmDOvZp75ID8fIq2yxQ9VlexriNJoY6CsODVw/yQI2exjWlXNz+aQSWEoE6A6Expztu8PjcZIybdUkR1GCTyhLzbMcAh9hNx/+lpRkdMtB/Kn/ZuSrNZGlgQaB2GYPNks/iVIyOF1HnURslpwknGq9cenqHqL12RbxIUCEE9RxwI5ecR26JQcDh0Fmo7H00DDDuTU0NjYGkK6fVzKHHjqAmFa9/MpCoXpM9AclOVqgvzSHkciZslQouTryGU98Z7yGtAtaAlDt36Wr3GbOTS7VgCHPTVMingVfjecpFsSLEpzafqaYqTBGIeGYU4yyetSaHLElg6nvTF+Lt6WkxQ/0RgLg3QfJxxEYZ4xwu9SAWFiJwndytrYodg0iS2xmYrJx1kWozRoCNf7pJ7h511xTRI/0653QZlMu32ZEyOLgkN7tnWf2c9uU7ZGjLuAZUtl5zpei3bqeAnQ6TNeWIRL8h2ZlTmLSyZqPSNpe6o4Hk6D7KliVBi7XvDVnPq/zzjLXqw7qKXNMxbf23uGRbzfZCv0PZy8k1YyfGCspX1/BjHxqDPFKkM0mLp9nlhZSYU7QRTsyJHsFD4cM3zSZlZuuyq08Xf4o5VdfP5y6X3hVXP+luvgYJsHB3v7I2gNmOxitVwWyKD2TBSXs7nTUc4KgTptqDLerBGwfdh2lGvo7S/whmK7xU577P4f+pQPFLeCgZ7NO3nmDBPinyiyWaBOu6NmSvZA1VYPhJm1TEn/UNIAEwNx1dqm5I9KovYbr2VomBL2gpPr5dThiOxTd2Y0tnu2ciX/BkH+kkUddt41KyWrm7veim1JyW2yDGRYfkqurntLV2NKrgOZLQYjjWc1QnnMgGQKaEk0lvPKsucpnqv1hyHP3SlPIAl41v+T5xM+8ExNMtxeDRlWU03x+XqIUNZCONJzEA91ldGXfs9DivXyZkixTnzdHcTtf+rEt+9A/Iy3FdQWZ5NPgtzcvt+Oa79GPck68cZuJi7SOZRfgfM3sgUqJkk+jFqyPAW5m1jWUNaCuPM5jt8k56yS1STF3Wg9lok3OArX85BixOA+8vd6s2ifcXzAo+M8Wifr5Dpq/1+toi//APGKAY4=)

**Comment by SonTT19** [comment]
i think you must change `item` to `internalItem` in your slot 
<img width="625" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/49301480/08c8ad44-6ad0-474a-8e1f-c57ea1e6052c">

**Comment by shawkiAlasy** [comment]
Solved

**Comment by pierrejoye** [comment]
Just in case someone ends here about expand and data table in 3.x, 3.7.x example not yet pushed to the publised docs:

https://github.com/vuetifyjs/vuetify/blob/1d34a8375917f47df76caa33e9625094983cff81/packages/docs/src/examples/v-data-table/misc-expand.vue
