### ISSUE TITLE
[Bug Report][3.3.22] v-card-item and v-card-actions have different indentation inside v-dialog

### ISSUE THREAD

**Issue by ivanmem** [vuetifyjs/vuetify#18489]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create v-dialog
2. Place v-card, v-card-item and v-card-actions in v-dialog

### Expected Behavior
Same indentation for v-card-item and v-card-actions when used inside v-dialog

### Actual Behavior
Different indentation for v-card-item and v-card-actions when used inside v-dialog

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNksFOhDAQhl9l0rMscZd4MGiiMdGbDyAeZmlXmpS2KQMLMb67hbosLJgsFzrf9P+n7czHN6tcHj9Zu2lqwe5ZSqK0Ckk8ZhogbSK0dlgOQW40odTC/aEB7kmPIcC7FRpeJCrzdYZ+Fx8QYE6yQTLuIWMWndCUsYk6VEHHIVdYVX5T2UZYk8kYlNhGR8mp8HSXJBe6URlJf4WLlE9y2SxgwGMpEi1FxR2U++jWu78J5MpfNo2v1eZoSRq9OFn4Xp3oClNrDl4oK6E6KIRSBnKjuA8ORh+5cIdaqW6l2uop1mga//8Qpzfq22B0tfQL7YTnmsjowWre3lmBNZdTcgJ7FNp/HpuZ8aCZjVZPwuSl8WQi2c8N2212m4SF/3bLPn8BW9fEWQ==)

**Comment by ivanmem** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/33786293/e4382628-6f2d-4999-b879-38167ba58a79)
Possible reason. v-card-actions does not have a similar style.

**Comment by Jesse205** [comment]
This is the correct behavior according to the design specifications.

https://m2.material.io/components/dialogs#specs

![image](https://github.com/user-attachments/assets/5f037569-e404-435f-af50-0e1fc1f3e15d)
