### ISSUE TITLE
[Bug Report][3.3.22] ScrollBar in VDataTable should not contain the header if fixed-header is true

### ISSUE THREAD

**Issue by flojacob** [vuetifyjs/vuetify#18487]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0
**OS:** Windows

### Steps to reproduce
Set `fixed-header` in a scrollable VDataTable or VDataTableVirtual.

### Expected Behavior
The ScrollBar should only include the part of the table that can actually be scrolled. What the header is not when fixed-header is true.

### Actual Behavior
The ScrollBar includes the fixed header.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqllltP2zAYhv/Kp0gTINE0TZpCI0Cayg6MXexmFxPlwk2+thZuHDlOB6v63+c0B+wQq0O7qvt+r53Hrw/Jw87JRTz8mGXutkAncq4kbjJGJN7MU4Cr7SAhkgwkWTAsBYBojSRBkV/Pnbo1d+oKVX1LPcE8RyHbQqkPtoQVqIop2WBTiBnJyw7IcEsk5elg1JSW9BmTQfWESlkjXa2lcgeeV7kOiAqyQYbtIGdcRjFnxSZ1yycp+w6q/7CfO3UPgF2jupJKhq7kP7MMxYzkeHoG+3098tBMY6jHoSSjrv7msaCZPHjxOeNCQoJLUjAJu2rAsncE6gnXN3Baa+XMDjlG8NAoCvC1CXBgjODktgoWTkeetwLV3NJ0dXZyrnsJo6tUeXNJhDRLT/iiCmUspp4r0nJGESwJy1Gr7bX2rsWYEcYFxfzkvB4ybgRLh89EMZegtX9JpM06I2KRG+a4VGz2H4JLpKnRIas0W5c7wZX/w6ufKkE3P7atZiPbV6YMs5yg4H8whV98VXRDb7KJYBROjYpKIYKJ63XsarYR+GNDracUwbhjL9nVyLYl60G9ixFigWQDOUmT3zRe23j94OIt77Sft2PVeIP/5P2kLgkqrIwT/y3jyBaqydJCdu0VpD6jY5CzIovJU+dYvVIGXviWMnDNzGrIybuSvHwH5Bd1WaBYqLVPrKDh5N/jHJvbuSUNXLNQr7k+8jHUb8jYCyyQpFbSi55IvX7QqeUwde0VqK4d4/zOGaMZz6yU057t6bmm2FDqa6lT9jDqAxxj/MpTfIn5ZmGDHHvmk+vd2Qt5admdE9dcjgpzrIvHOG95WljvznHYE6Qf9q93qN8vxhHq25j+e8K8p/JevbwslOGoJ0nfcnwmZmItpZlwxdh/dpoX1f7s0FAfLVfD9hPE2Z87gRu4Y6f69X3n8S+WvIsC)

**Comment by flojacob** [comment]
How can this behavior be intended?

If the header is fixed, the ScrollBar should behave the same way in relation to the header as it does in relation to the footer. If this were intended, the footer would also have to be included in the ScrollBar, which would also make no sense.

**Comment by KaelWD** [comment]
- Making tbody and thead scroll independently is a pain in the ass
- The header can also scroll horizontally if there's lots of columns
