### ISSUE TITLE
[Bug Report][3.3.20] VAutocomplete: Search text can't be clear while element is in focus

### ISSUE THREAD

**Issue by Franco-from-Owlish** [vuetifyjs/vuetify#18481]
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Safari 17.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Setup a VAutocomplete with a search function defined.
Search for an element.
Select an element.

### Expected Behavior
The search text should be removed.

### Actual Behavior
Search text remains until the element loses focus

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNF9t20zjwV7RZDkmXxu0CT6Ut0PQG29CeJlCg7QHFUWJtZctIctoS8u87M7Icm5Q95CEjz01z9/hy3rIm3nid59GsEK2t1rYTaa64E7tXGWPbsy4vnI414IQTiGLMiMnOVcuIWMiZMAdKpCJzVy1PnHVTPRaqxmADaSsurNNpdyKVEwY4CivMIT1ULBKu7zrplAB6DsI6e8dT0aBbJGlr5UiJ85VLlOZjmU0f4omUyKYuYTs7O2wzCMSJzG15VNpyEOjWcIqPyJuLRAeJtFBOQjxCNL4V0ohxeHKFybp69K+IXdDKLZqc8u5zlvPus8pUK7iJk67M8sJF9j6Lgcvj3iAq8L0q8jEkpGRv8uy0256N0gUJC+ljf2KogHnOcqNzu87wmS2uWiUnJVdJ67pICDi0qhiFBCDlZWT47ctIpFyqYBH+As9EGuu+ZLUk+TIYyWyMScDLl5Tq8oappGuXzcHWKuUdvBzvXmOLBdveaNQlyW/U7A/uN9mQpV6/gGxwwKONjcwdpJlKxoGpzEIOc5KXaa6NY3OUL5wYr2PtL9jE6JRdtaBhrlovUAtwZlDFEx4LdkYesDkZRFHbYtYZKElgBdQyXk08VMkD6EVT+XvoGCbunMjGtnZTyYkg1pl1YGajOdkOGt5ZI5VNDutp26j58nq3c3ld51ppoQe5l/xj4eMpwS5/J6S+VddYq92fOJBnUmQxCdfqwB+3SnfXysgyOWGdPzwtWsaUPX7MAraKaCUT+rNUXxY1kSjQFf3ro/mK6gWrkJXmxdcIcpV21lYysJxt4GbnC9boEKs8ZHedfSuEuR9CMpco6rctBtHWZrwdsDy7313bYiOtleAQV2iUcrJUN8EdVa8yHkrDF1bJRo5gQIEXRWqeRU6f6FthetyKskiCFHpaF6o8/x8ZiurvCVQxAPbq3OQsA1wWSJWhyp0I5oy4O510Kvk1tsu6f7MfP0LSgxO/wUq2/4ovdGSjUifCxQn2g+1UdTbjhqHPJzCewLPL5dBrD2Uq2uvtMzAJwGEBzuDzvpi112tsh+oeyeoeKgAOA81NCTziDAOEHFwpwtRlAQekt0WaA+gpOZkA7Osic1xmcDyH8UEA//dUAQbUxI+MEMj1SSilb+FwpBUy7otUI56gjMmJbMzxCg6+1DT8I51D8xGSqs/CaDQBJA0ShkZraCU4ffyIJoAe2VRxCGMCKCdymmCcjrwlQyO4N0WgawhICx0woDUNfZlhYD/pAjkuNJQLwINMpGjBsbZOKmQ41CZG+EGOBRhZDwRkEJXr7EagTL8ggZ5WqKkHW0AJIMtI5tOsSJsaCvT+tbXcM2NjI2ZoONqPwDsAqRACZEH5uJmNAc1T9MBAhyPvOx+aHiwraM5pTiHuFSMyTpoYrawbgW7Bf6bJnSNh8KJBzr8jSDSFJU6QaU84zOdrlScAm6FIkXKaiinCgeBYYgNYfTAffZ1RhKBjE8waTC9K/0+FuV/coAXnlKr2IWxNVOM+zH1tDCV5D5J8E6D3uEhHDUVvKGOQCCpjXVbZQMYoh4C65y3PpNMUK7gC7T3XkHZUWQ8wFB+VELQwmgWH8nRcmDFl/BxevajmwMBEqg5oomw6OEh960FUScOwfJQOw7KHHUjFB5D09AyPb3wXGn2DTjQMQ8IxlAg5o8v/SYEqezAUYcJ7e53MkLiPL2m89kQK21AFCKr5zEfei5Tdr+/uyJZjfovRO+BT8hkfCX/BFR1q6j7rdEQaB9xMKROcShSBnzBnMB3R5VPqweEtFtf7DP8HSmLy6n7CeEbevqAeQUCm4cEPu0OYRNTDCgfZMYQR6HX3oChjjMAg4cYPBopdX2A99ZICCoLSVYxGWL0If2oSrIJbSTZDEm3i03znDOxPvvWdJB9oC0LUe8CksEY2K1xwSvU5GEAjI8wOWMRm3BfjhRE+ODBofRkde3OHCV3WGMW+OHvw6qeGopRRJRxJg6gPUGjijmax4WN91/bS19XrsnpPTUUmDNjbgVXCbxYrW1F4ZV32wYtoorQ2HUZntEPDW5j9VTGFj6k1vIs2qOWd2rAO7NtMwstv8wWAbfZ0Ew9PntR2sdW9ZGljqfOBNeSXPGHtgN2t0rmIHs2D7OLVo/lSeBHFOvrOvwab2equG804vBujvLBJpzK6ucBXF9WyVlvkw9U1avlFUNs8IXK0PpY7aNgvamsFOLq94Rfr8qPF3SsRvllsbOmrJYZX6ngXGJEIfK3FeutZ9Cx63vLw6Wbr+j/KvAWH)

**Comment by KaelWD** [comment]
This is intended behaviour: #5926
