### ISSUE TITLE
Wrong Text Field height using MDI icons

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#1848]
### Steps to reproduce
```html
<v-layout wrap>
  <v-flex xs3>
    <v-text-field
        label="Standard"
        prepend-icon="face"
        type="text">
    </v-text-field>
  </v-flex>
  <v-flex xs12 sm9>
    <v-text-field
        label="MDI icon"
        prepend-icon="mdi-face"
        type="text">
    </v-text-field>
  </v-flex>
</v-layout>
```

### Versions

vuetify v0.15.7

### What is expected ?

All `.input-group__input` with 30px height.

### What is actually happening ?

`.mdi.icon` has 36px, forcing `.input-group__input` to have 36px too.
Related: https://github.com/vuetifyjs/vuetify/issues/609 https://github.com/vuetifyjs/vuetify/issues/907 https://github.com/vuetifyjs/vuetify/pull/1044
Can have the same issue with Font Awesome.

### Reproduction Link

https://codepen.io/anon/pen/oGYXNR

**Comment by Webifi** [comment]
I ran into the too.  

A bit of a hackish fix, but setting the line-height on the icon container seems to help:

i.mdi.icon {
  line-height: 24px
}

Example:
https://codepen.io/anon/pen/JrbYjG

It would be nice if a better fix could be integrated into Vuetify.
