### ISSUE TITLE
[Bug Report][3.3.21] DataTableServer does not honour header order with two-dimensional headers

### ISSUE THREAD

**Issue by binair-io** [vuetifyjs/vuetify#18484]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0
**OS:** Windows 10

### Steps to reproduce
When defining a VDataTableServer with two header rows, append a column in the first array with rowspan = 2 after defining columns with colspan > 1

I based my reproduction link off [this example in the docs](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-data-table/headers-multiple.vue)

### Expected Behavior
- The data for the newly appended (last) header should appear in the last column of the table

### Actual Behavior
- The data for the last header appears before the columns that are defined in the second header array (the second header row)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1ll9P2zAQwL+KFWlqkWho/hUaFaSJwcbYw14n4MFNjhLhxpHjljHU775zk6axGyPoGC+4d77z7/7FvnlxSpEcfS4Kd7kAJ3YmEuYFoxLObnNCJstBSiUdSDploASExA9AUxDl6a1Tr26dWpOhrZKnUJYgZKNIGC2VHBgsqcx4PvA2KmUyeIRn1OZ0Dm1xOShADAo6A1RGleZsctQmQsbJUQsYf5aJyAq5hoffBReSpHBPF0ySl8q1so5J/4CcnpF+LUNpjRyTm42IbCyqP4UXk96l4H8gJ7/4bCFk77C9I6GMiwzQhxeNNc09lTEZuUNju5jiXj/UpIXgErI8JqGxPRMcpZ4mW1KGSEA1kFVr3RXBVQIkEUDnpKR5+pQlD7Yw/OB4N4xxdxjG1lYYwf8J4wK7KhNW9JG/i+7ZSqAjNuzm9opdD3Qv9vNFkdBHsMEHw2gXPnD1g2v20bvyfvLv7F+zfAZiig2UWvmj0duTH+qj0gQQuLqibhzd814RfAfGnskUaG4N4LijAMNu/rFlfs3tFb8u2wv/B2csK3hhhR93tP7Q1YUbeL0htvAd6LqDvdC/8RyeEz6f2tjDoQ5Ud34n+4ml80euXryKPtSFe+F/4fnC+s0Po460+1F300T6B7A1tV1N739A6q8zea1btOEjryPvvmViR3oqG3i9HhX6u8b1rlnVLwvtNm4tjRAJkZlk6wpV1zjpe8PhjOByiV+rAz1qQijLZsjWKyU173BCSnwzqLdFjElgJRhafKqgocqpaSf4U1nQnTlp18WK/VNwfOtILIXptTrvnnNTkXBWHacX403HXeSpsl/MjQ/gB2QGK7xHYraFN8vcMJ/Xvdo7bCAhxxuoPnfTyj0zA42DS4ptoXqh0x4b3m56rvr+FeP1XNjNsbpqQF5xUI+Q3cUVDhPpf7LZq1nTjbcZ3axWB+vFSj2Zm0eyszp0AjdwQ6f673vO3V9f/AHd)

**Comment by websitevirtuoso** [comment]
Sorry I can understand problem. Could you give me screenshot with pointing on problem. I could get any desired behaviour
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/89f447d1-79dc-4b8b-9774-2aedee1f53be)

**Comment by KaelWD** [comment]
That isn't really a solution if you want the end column to not be grouped under "properties"

**Comment by binair-io** [comment]
@websitevirtuoso Did you look at the reproduction link? What more could a screenshot do than the actual working example with the problem in it. And as @KaelWD mentioned, your "solution" isn't a solution to the problem I am logging a bug for.  As stated in the bug description **"with colspan = 2"**. 

Thanks for replying though, and also for the label "bug".

**Comment by KaelWD** [comment]
Test case:
```js
const { columns } = createHeaders({
  headers: [
    [{ key: 'foo', rowspan: 2 }, { key: 'bar', colspan: 2 }, { key: 'baz', rowspan: 2 }],
    [{ key: 'fizz' }, { key: 'buzz' }],
  ],
})
expect(columns.value).toMatchObject([{ key: 'foo' }, { key: 'fizz' }, { key: 'buzz' }, { key: 'baz' }])
```

@nekosaur was there a reason for not going with the tree structure proposed in #7819? I think we pretty much have to reconstruct that anyway to fix this and it would make the relationships more obvious instead of having to manually manage rowspan and colspan.

```diff
  [
-   [
-     { key: 'foo', rowspan: 2 },
-     { key: 'bar', colspan: 2 },
-     { key: 'baz', rowspan: 2 },
-   ],
-   [
-     { key: 'fizz' },
-     { key: 'buzz' },
-   ],
+   { key: 'foo' },
+   { key: 'bar', children: [
+     { key: 'fizz' }, 
+     { key: 'buzz' },
+   ]},
+   { key: 'baz' },
  ]
```

**Comment by nekosaur** [comment]
I honestly can't remember if I tried that.
