### ISSUE TITLE
VOverlay scrollStrategiests:85:22

### ISSUE THREAD

**Issue by GaborTorma** [vuetifyjs/vuetify#18507]
Vuetify 3.3.22

You can reproduce it in Stackblitz: https://stackblitz.com/edit/nuxt-starter-ctkh8x?file=nuxt.config.ts,app.vue,plugins%2Fvueitfy3-dialog.ts

Run the app, click the refresh button on internal browser and sometimes click any button. You could see the error message in your chrome console.

_Originally posted by @GaborTorma in https://github.com/vuetifyjs/vuetify/issues/17486#issuecomment-1748456129_

**Comment by websitevirtuoso** [comment]
Your app uses https://github.com/ThomasLeconte/vuetify3-dialog package. Which our of scope to check.
Please provide repoduction without any wrappers with pure vuetify components

**Comment by 5e** [comment]
I get the same but I'm not using any wrappers, attempting to reproduce but I can't get it to error, will keep trying.

As soon as I remove v-overlay the error stops in my own project.

**Comment by JMKempf** [comment]
Vuetify 3.5.1 VOverlay

I also just started to see this error after updating Vuetify.  It is preventing the overlay from showing.

TypeError: data.root.value is undefined
    blockScrollStrategy

On this line of code:
data.root.value.classList.add("v-overlay--scroll-blocked");

**Comment by orjan** [comment]
@JMKempf what was the previous version you were running?

**Comment by JMKempf** [comment]
3.4.9 and it worked ok

**Comment by JMKempf** [comment]
My issue was because I was using the "disabled" prop which had changed in release v3.4.10.  I removed that prop and it works ok now without the error in the console.

**Comment by GaborTorma** [comment]
The problem is still in 3.5.5.

**Comment by HendrikJan** [comment]
I'm seeing this same behavior which I can't reproduce in the playground.
It seems to do this in combination with routing (Nuxt3 in my case).

I did see it with this piece of code (`v-dialog` visible from the start):
```
<template>
  <v-dialog :model-value="showSpinner">Some content</v-dialog>
</template>
<script>
  const showSpinner = ref(true);
</script>
```

I "fixed" it by changing to this (`v-dialog` only becomes visible on mounting):
```
<script>
  const showSpinner = ref(false);
  onMounted(() => {
    showSpinner.value = true;
  });
</script>
```

**Comment by Miltonbhowmick** [comment]
I was also facing same kind of error (`VOverlay scrollStrategiests`) but i get a solution by placing `v-overlay` outside of `<NuxtLayout></NuxtLayout>`.

**app.vue**
```
<template>
  <v-app>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
    <v-overlay v-model="loading" class="align-center justify-center" persistent>
      <v-progress-circular color="white" indeterminate></v-progress-circular>
    </v-overlay>
  </v-app>
</template>

<script setup>
const nuxtApp = useNuxtApp();
var loading = ref(false);

nuxtApp.hook("page:start", () => {
  loading.value = true;
});
nuxtApp.hook("page:finish", () => {
  loading.value = false;
});
</script>

```

**Comment by Kasopej** [comment]
This still happens if you use directly inside app.vue inside NuxtLayout.. seems like it could be linked to app lifecyscle because it doesn't happen if in a nested/lazy inner page inside the layout

version ^3.7.1
