### ISSUE TITLE
[Documentation] Instructions unclear with how to use VStepper's slots

### ISSUE THREAD

**Issue by Drillan767** [vuetifyjs/vuetify#18517]
### Environment

**Browsers:** Firefox 118.0
**OS:** Mac OS 10.15

### Steps to reproduce
Hello, I'm not really sure if it's an issue with the documentation or the VStepper itself. I'm having a few problems:

Basically, I would like to slightly customize my headers, to show if the step is completed, customize the subtitles etc.
 However, when reading the doc, it is said that there's a slot with some props to customize each header, but with no example of how to use them, and if I do use them, the content I'm adding sets itself as the subtitle, without the subtitle's style.

So then I tried to create my own header, but with trying to use the templates for each steps alongside as follows:

```
<VStepper
    v-model="currentStep"
    :prev-text="t('pages.stories.registration.prev')"
    :next-text="t('pages.stories.registration.next')"
>
    <VStepperHeader>
        <VStepperItem :completed="currentStep > 1" subtitle="Some subtitle" />
        <VDivider />
        <VStepperItem :completed="currentStep > 2" />
        <VDivider />
        <VStepperItem :some="props" />
    </VStepperHeader>
    <template #item.1>
        Step 1 should appear
    </template>
    <template #item.2>
        Step 2 should appear
    </template>
    <template #item.3>
        Step 3 should appear
    </template>
</VStepper>
```
Templates "item.1", "item.2" and "item.3" don't appear.

Lastly, the doc lacks explanations on how to use `VStepperWindowItem` inside `VStepperWindow`

Still, thank you a lot for this library!

### Expected Behavior
I'm expecting to use `<template #item.1>` alongside the `<VStepperHeader>` component

### Actual Behavior
The  `<template #item.1>` never appears, and I can't figure an alternative way

### Reproduction Link
[https://vuetifyjs.com/en/components/steppers/](https://vuetifyjs.com/en/components/steppers/)

### Other comments
It may be important to note that the "action" template does work.

**Comment by ascott18** [comment]
Would love to see some clarification on this. There are no examples in the documentation that use custom headers alongside custom content. All the custom header examples have no content in the stepper. There's a diagram in the Anatomy section, but its just a static picture with no interactivity or code.

**Comment by kissu** [comment]
Not sure about the syntax for the slots but you can also use [this approach](https://stackoverflow.com/q/78580355/8816585) to programmatically paginate anyway pretty much.
