### ISSUE TITLE
[Bug Report][3.3.22] v-select item-title item-id showing undefined for selected item

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#18510]
### Environment
**Vuetify Version:** 3.3.22
**Last working version:** 3.3.15
**Vue Version:** 3.3.6
**Browsers:** Safari 15.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Created a v-select component with `item-title` `item-id` `return-object` props
- set an initial value object for selected item
- the selected item text is showing `undefined` 

### Expected Behavior
the selected item text should show a value that is computed based on `item-title`

### Actual Behavior
it's showing `undefined`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUlFr2zAQ/is3MXALsc0StofgBEqh7GkvG5TRFKrY6qZN8hnp7BGM//tOVhKrfbLvu0933313T6Pwri7vuq4YeiW2oiJlOyNJ7Q8tQDXksuvm3zmosSWpW+XO0AwSojlKd0EAaiO93x2EPeafD2LBSZNRjD8qU6NVQAjkVNucoJbOF/BdGVUTyBDCq0ML9FuB0Z7gqAz+K5Zi+6q8Nk61+LnE0nLILTbKcNOYUc09K000DdJp2RITsCfDozVp1khuzLlUWZrfarYrjBoGSBMBzwdp+jCvflNzfpNfvLgZbmG3h5eP41BY+VdNkMP8H2RPL+lDp6h3bY7HP8mIsxFxtsWHRg/7n9jDZeYtjOM1YANgmqoykM6L5RJvNxuQuPiqTA6CQ1873REXoz7ehbYdOoKR5b3CFNeW8S1lgc63gC2vz/pfsAuMm+yrMgbhEZ1pPmS3CyU4eOY8RVkjaFb+aQXBly1kP/CEJDOOgzcM3EvrThlMq5S/vvK/ae9lm/DvDGkr3z/YXB88oGsS+gPWvb+wnxOpqZNR8bk1TMyqyugRuyOmldgUm+KLiN/1Wjz/BydQD/8=)

### Other comments
This use to work fine on version 3.3.15 or before that. Go to the code playground above and try to switch the version and see.

<img width="711" alt="Screen Shot 2023-10-20 at 11 02 49 AM" src="https://github.com/vuetifyjs/vuetify/assets/8376035/00bf2e71-e260-4ba1-9b8f-a21ad4dbbdc8">
<img width="738" alt="Screen Shot 2023-10-20 at 11 02 36 AM" src="https://github.com/vuetifyjs/vuetify/assets/8376035/c3316d19-b7a7-451d-bb76-6d8044165a31">

**Comment by yuwu9145** [comment]
With `item-value`, `selectedCar` should be `2`.

However, please be aware that `return-object` overrides `item-value`, they shouldn't be used together

https://vuetifyjs.com/en/api/v-select/#props-return-object
