### ISSUE TITLE
[Bug Report][3.3.22] Textarea resize icon positioned incorrectly when also clearable

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#18514]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.6
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add `v-text-area` with `clearable` enabled

### Expected Behavior
The resize icon in the bottom-right corner is fixed to the right corner.

### Actual Behavior
The resize icon is pushed to the left of the bottom-right corner.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj8EKgkAQhl9lmosFpVDQISzo1ht0yA6bjiHsusvsKIH47q2aIJ1m5pvh//95dOg5T67OxW1DeMJUyDithC5ZDZC2O+Xc2I5DbmtRVU38QyMU+ohiUjAzgHZnbEH6nKHx7wwXm1yTYvXSNKNkVk/+5QcyuafJIlUYfc6VE/AkzRSuMs6yQAdMJfRQsjUQhYei4TyY2toLhChwHi7W0Y20tnC3rItVtBkMJskghv0WD/EhPuJU93t8fgEEI1uZ)

<img width="887" alt="Screenshot 2023-10-22 at 10 17 16 AM" src="https://github.com/vuetifyjs/vuetify/assets/4167341/693805dc-3363-4748-9653-97ed606f67db">

**Comment by Kroeg93** [comment]
Any News or Workarounds here?
