### ISSUE TITLE
[Bug Report][3.3.22] button default loader cant be labelled 

### ISSUE THREAD

**Issue by DiedeGu** [vuetifyjs/vuetify#18523]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
1. press the take checkup button
2. inspect the resulting element. Note that no "aria-labelledby" "aria-label" nor "title=" is set on the element. 

### Expected Behavior
the progressbar needs an accessible name to be able to notify screen reader users about the status of the page. They need to know a loading event is taking place and for what reason. 

read more on: https://dequeuniversity.com/rules/axe/4.7/aria-progressbar-name

### Actual Behavior
Non of the discribed labels are found. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUk2P2jAQ/StPuRQkkt0uVKoiQK321EtVqfRUevAmA7Fw7MiekKwQ/73ON9lc7Jn3nmfmZf7eAmeTp+9FEV1LCuJgy5QXSjDtjxrYXsNE2LS5AokSzu2OQV6HomRzDLp0LuqwkilnHtp8eR7SLFmRT/1mS/rMGWm8m9Ki8I9UxqZuJFLNnvenSH3VjlORuMBYWApLR+mkQSU5w68+xGtGyaUsIvzgTw4nSwShUxit3sHiQg4CJ6qQS10yuQivSiYX+GZw8PCgx1vJbDTY4EwMx8IypVHXYOuDd2LwBdfQKcOxSFga7Xq4teqNNTKS56yZZ/P1GOzx0+CQCX1x2D61BM+fK4YIiJURqdRnL+5vg0WP7p8U1eHZmir8/AjP6k7pq7BS6CbvBxTqEfqWNGb0xSZgHAgzj8amxzG6aL4uHmz2xQczxIcusbLglkV1YSwjpZMoFePWPeX/voixWGK3x+KG3oEYJ6Ec4b5cDcblxJlJXTwI0XK9cIz9TmXSRf0T2IFtSRPoiA8yJ1Pyoi/3gd6WXK6wfvbfchDefQfTeW9GHIcK7qtgHa2jTdCdLy/Bv//lyAsP)

**Comment by justingish** [comment]
This same problem applies to the DataTable loading prop as well.
