### ISSUE TITLE
[Feature Request] add applicationable support to VBtn

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#1852]
https://material.io/guidelines/components/snackbars-toasts.html#usage-figure-caption-4

**Comment by johnleider** [comment]
I'm pushing this to v1.2 as it is more in line with planned changes for that release.

**Comment by johnleider** [comment]
moving to v2.0 to coincide with the button update for md2

**Comment by chr-knafl** [comment]
Hi everybody!

In my opinion this is a very important feature for usability reasons! I am building my application with vuetify? Can you provide a workaround until the release of version 2?

Best regards
Christoph
