### ISSUE TITLE
[Bug Report][3.3.22] v-select  prepend and append inner slots click event should be done without open overlay

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#18527]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.6
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
overlay menu of autocomplete and select should be not opend when adding .stop modifier to click  event.

### Expected Behavior
overlay menu should be not oppend

### Actual Behavior
overlay meu always openned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUM1uwjAMfhUvOxSktmgw7YBg2m57gx0oh64xI1oaR4kLB8S7z20KoqfE1ufvb3dRMTSLT+/LU4dqrTaMrbc143vlADanovZ++A5DQ45r4zCMq4TomBqSK2SEU9GSRrutVBt/KwVrI4RRxt1LvsxX+eu+UvdjOb/JwbMP6NHpwrhH/lHDiDJ8NNY0f2Vk8kIY8BAwHoWu1aYYp80iYR8lFpNIaTV1fQso62nCATgUMGGRMTbBeIaI3KV+TOspMFxAnMAVDoFayKTTrIcDCG9kkE5g2yNm2RdaS/BNweqnbN5DDp1r2EjOMctsDpdkrLYYeJbx0USIR+qshh8ETQ7hbFgWDCTdgQ7kNZ0dWBM5kV5768ms2FTXXK3KVfmm0rtcqv0/Lvym5A==)

**Comment by KaelWD** [comment]
It opens on mousedown not click.
