### ISSUE TITLE
[Bug Report][3.3.22] v-model not updating on VDatePicker

### ISSUE THREAD

**Issue by AlexanderHalsey** [vuetifyjs/vuetify#18529]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.6
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a VDatePicker. Pass it a v-model ref. Ref does not update. It doesn't work with the listener either ('$emit(@update:modelValue')). The event seems to be emitted from VDatePickerMonth but does not seem to be propagated to VDatePicker.

### Expected Behavior
Expect event to be emitted from VDatePicker

### Actual Behavior
Event is not emitted from VDatePicker

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj8FqwzAQRH9l0CUJ1HZJoIeiFAq99BtsH1x7E0QjaZHX7sH43yvZrQk5STM7O7wtJ9WHtnhnzseB1KvSQpZvjdBb5QA9Zg3z8l1E6500xlH4s4BPNBbOC64kYtwVA3dxu/uf66+AYktPE9K0fK4xz1tkzJKZsWm/KWDMrO/odq5Uciu1reviESA5K58u7rij7NtgWNCTDCu+seyDYEKgC2ZcgrfYxZN3KQ7E3l4WNpxTZF86+sFH1PtDfUj9a2PsUvOTOuWn/EWt7/Go6l+qd2eR)

**Comment by jakubmatisak** [comment]
Try this. It work without [].
https://play.vuetifyjs.com/#eNpdT8tqwzAQ/JVBlyRQ25BAD0UpFHrpN9Q9uPYmiETSIq+dg/G/R4oSE3KS5rGzs7+T6kNbfTGX40DqQ2khy+dG6LN2gB6Lhvn2vYHWO2mMo3CngB80Fs4LjiRi3BEDd3G6e+j6P6Ba3NOEpGKeF30sElOwaU8UMBbWd3Te1yqxtVpmdfW6PTG5nK6eSkfYt8GwoCcZcndj2QfBhEAHzDgEb7GK966SHYi5veRi+2RZO7rgO8L1ZpPSc15MUvOb2pW78l3ld7tVf1esHGXx

<template>
  <v-app>
    <v-container>
      I am not getting updated
      <br />
      {{ date }}
      <v-date-picker v-model="date" />
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const date = ref(new Date())
</script>

**Comment by AlexanderHalsey** [comment]
It's not working without []. The bug I reported is based on the v-model not updating the date, whether the date is encapsulated by an array or standing on its own. Your link seems to be pointing to the same error

**Comment by KaelWD** [comment]
The model didn't update until you clicked ok
