### ISSUE TITLE
[Bug Report][3.3.22] Ask help for VDataTable fixed column

### ISSUE THREAD

**Issue by Warnier-zhang** [vuetifyjs/vuetify#18533]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.6
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
when scrolling vertically, the fixed columns and headers is transparent, even if i had setted css backgroud and opacity
also，can't fix column to right

### Expected Behavior
no transparent

### Actual Behavior
transparent

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVlW1P2zAQx7+KFWnqkGhI0ybQqCBNsAfGXuztBLxw02tr4caR7RQ6xHef3TzYSTyyvUpyd/b97n9n5/7VEzw9+5Tn/r4AL/EWEnY5xRKuHjKEFvsxzvPj6/EjZZnEJANemY7GFZZ4LPGSwnhPuCwwrZ0IJVvAK+Di8sGr3h48y0tUNu1bgRDAZcuZUiy0DyjssSQsG09st5AHCsr9TFZym6BZEOQvtn8LZLOVKkB5bPuavMBqXMIYqwYZ7zEt9JYZ3oFZcrU4c9VYi6KcbVW0pRRtcWaJqT5FykkukQBZlJqSXc64RK+Iwxq9oTVnOzRSfRjpcKUAy4RUhRx1Q5c66uN9mfa1ppNEUkjQ6KZUEH2cBMFGpeB7km1ORqd1HKZkk6k4ITGXxixUfl1VgtaYCmjsT3BQwVoIE3tULkGSF3XcW/Xs0VxjyjgB0c8P2coYyyxpJ7jZtdnuC1aF6Wra21Tr11iOHIuuMV+Kd5al2u9a+JMzCSR7Z2leRliLuwLccqY2+OBogEMAooLbxT+emP7XZ+MvA6B7pCXi7Ddk6BfbFHZ/a20TNInmppNYJij2AytMaZGgcNZYqhLVwbLCNKjKNel1qgNzmwJKOeAdEjhbPZN06yIKp+dtonmfyAqxiKb/TfRZ3SaEOynisE0xcQljMjYYdliFcT6EcV3kKX6yzpThmAZRm2Pqm9orjPjf1LgYwviq7gbgS9UhaxYtlCgelmRmxqlhmfrGWHcmHoL5DpQe0BJwcwZaLOcdWYI+ytwxtnZYhRIMkfxglJKc5U6OeWdMAt8Yao4LB0eXIhyi+MYyOKRst3RhzAKTo5qSHsaFY0pi38hYgcyiIZIblhXOu2QWdcQIo35XoolrWHsDEg4KckfknbriHRzRpKNG6BjU2FTecBiFKorOlOr7d3FW/q/Vn9p7O/Wm/tSPvfIZht7jH/e9i0g=)

**Comment by Warnier-zhang** [comment]
@SonTT19 
can you fix column to right?

**Comment by KaelWD** [comment]
Fixed by #18512

**Comment by Warnier-zhang** [comment]
@KaelWD not full fixed in 3.4.0-beta.0！！！
when scrolling horizontally，other columns are over fixed columns；

https://play.vuetifyjs.com/#eNqVltFumzAUhl/FQpqySg0hJNAmSitN7bp1nbTdTm0vHDgkVh2MbJM2q/ruswPEDnhluwLOOeZ8/v3bcP/qCZ6MPhWFvy3Bm3sLCZuCYgmXDzlCi+0QF8X+dv+QsFxikgOvQ/tgiiUeSrykMNwSLktMmyRC8zXgFLi4ePDquwfPyhLVTedSEAK4PEomFAudAwpbLAnLh2M7LeSOgko/k1Su52gaBMWLnV8DWa2lKlAZO56RF0iHFYyJapDhFtNSvzLHGzBDLhcj1xwbUVTyWBUdqURbjCwx1aNIOCkkEiDLSlOyKRiX6BVxyNAbyjjboIFah4EuVwqwXEg1kb1u6EJXfbyv2r42dJJICnM0uK4URB/HQbBSLfiW5KuTwWlThylZ5apOSMylCQvVX89qjjJMBRziT7BTxVoIU7tXbo4kL01drf44DOrQW33tAF5hyjgB0UWCPDXBqnHSKX6vedBpfuh6g5UkWofjbnWbDMuBY9AV5kvxzrBE510Df3ImgeTvDC2qCmtwW6dbztQLPjiWzqETUcUtjX5kmTKYrQpCaifJm46AFcLjibFasw3/4jVtB60pZ78hR7/YqrSt1KyZah3NDBNWLLFvWPbizVE4PURqTdQetsr0zFSvcfP+jl41zG0CKOGAN0jgPH0mydpFFE7OjolmXSKrxCKa/DfRZ3VwEe6kiMNjirFLGNPxgGGX1RhnfRhXZZHgJ2v7Go5JEB1zTHwz9xoj/jc1zvswvqhjCPhSrZBlXgslivslmRo7HVgmvgk2KxP3wXwDSndoCdjaNBbLWUuWoIsyc9jWLqtRgj6S74xSUrDCyTFr2STwTaDhOHdwtCnCPoqvLIddwjZLF8Y0MD1ql3Qwzh0uiX0jYw0yjfpIrlleOs+SadQSI4y6qxKNXWbtGCTsFeSOyDv1TXBwROOWGqHDqLGZ+YHDKFRTtFyqz9/FqPo1UD8F3tupN/EnfuzpqzoRh0uQ2A+8xz9XH6ss
