### ISSUE TITLE
[Enhancement Request]Please add collapse list feature of navigation component 

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#1855]
### What will it allow you to do that you can't do today?
Navigation drawer in mini model can't collapse list menu like [element ui menu](http://element.eleme.io/#/en-US/component/menu)

### How will it make current work-arounds straightforward?
This feature is very necessary of admin panel's Sidebar,here is admin panel sidebar [demo](http://panjiachen.github.io/vue-element-admin/) of element ui

###  What potential bugs and edge cases does it help to avoid?
T list item icon have not any tooltip and group list has not any dropdown menu,when use tooltip in mini navigation,but it solved on version '0.16'

**Comment by johnleider** [comment]
Is this a feature request or a bug report?

**Comment by lichnow** [comment]
@johnleider I think this is a feature request,but also report a bug of tooltip component in navigation drawer,suggestion is solve the tooltip & navigation bug,then can implement the feature of 'collapse navigation list & list-group menu',thanks

**Comment by johnleider** [comment]
Absolutely. So in regards to the tooltip, that has been resolved and is currently awaiting for release in 0.16. Since the remaining request is a feature request, could you please update your post to reflect the required markup for a feature request? It would be most appreciative, thank you!

**Comment by lichnow** [comment]
@johnleider ofcourse,I has updated the post,hope and wait this feature

**Comment by lichnow** [comment]
it is collapse list not nested list ....  ，like here

![](http://static.phpna.com/images/20180703061712.png)

**Comment by Pchianes** [comment]
Hi
@johnleider does the last comment of @lichnow has been implemented ?
I'm really interested by the functionality but cannot find a way to make navigation drawer nested elements on mini-variant

Thx in advance
