### ISSUE TITLE
[Bug Report][3.3.23] Typescript and slot parameter incompatible

### ISSUE THREAD

**Issue by kenny-reyes** [vuetifyjs/vuetify#18559]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
There is no way to type the parameter of a slot without typescript marking it as an error.

### Expected Behavior
can use slot with ts

### Actual Behavior
tsc mark as error the type

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUcFOhDAU/JVnPaDRBRf2hLtrvHl3Ew/ioQtdbCxt0xYSg/13H61sxKMX0hmm781MX0diTZ09ap0OPSMl2TrWaUEd21cSYDusqNbhGECtpKNcMvNDBdIK3jADw6pTDRO7inS2rchZgZp5Jlw6Xn+sBD0G3QgTBF9CPJVwmPAX9LJhJ1zT+MUcnGQ1lfsxytOBip7BDVSEGaMMOFuXCMD7bRaEvyxki1yRmq3P+ZBYBpyYmH9xH6GtDdcOLHO9BkFli3Gcnd3yTivjMJVhJ/BwMqqDBPtNpr/uU7MYdAfjbCZEKUH23ZGZmdTKcseV/MuH/h5KsM5w2QbWhy+6tw6wfhyNq6+SJyaEghdlRHORXE8xovEQIstibYfnvMhzLH8ylpy7T4BbkMoBtZa3kh4FA6ei/WT5YJU837oHn6SQZet8g+v+/fAYiOwXpRN/S4p0k96tqNDvNF2TCRdpXpC3b5sV494=)

**Comment by KaelWD** [comment]
1. I don't get any errors
2. There's no reason to type the slot like that anyway, it already has the correct type.
