### ISSUE TITLE
[Bug Report][3.3.23] Setting the min-height breaks auto-grow functionality

### ISSUE THREAD

**Issue by Rusinas** [vuetifyjs/vuetify#18566]
### Environment
**Vuetify Version:** 3.3.23
**Last working version:** 2.7.0
**Vue Version:** 3.4.0-alpha.1
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
Type a bunch of text

### Expected Behavior
Textarea grows when content overflows (if auto-grow property is presented)

### Actual Behavior
Textarea doesn't grow

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdT8tOwzAQ/JWtLwGJOC3pqaRI3PgDDoSDlW4TS37J3oSiKP+OHQeEOFjyjGbn8T6z4LvqxTk+jchOrCHUTgnC59YANFMpnFu/K+isISEN+o1aScIbCY8CplLbC6pzy3ToWwZiJFv23n5CfCHSh0hWP27Vf7vE5LSm+tMiwtB56QgC0pjLSO2sJ5jB4xUWuHqroYgDiiQHiL6BIJaAc1LcFa+olIU369VlV9yngGy52dOXynt/p8y5pJamHFD2A53guHc32OVkYegpKZbVajtnywOr+ZHvS6HcIPiBJVzzx5p9fAM7RXYp)

**Comment by KaelWD** [comment]
Don't do that then?????

**Comment by KaelWD** [comment]
You can't really it uses this great big css calc(): https://github.com/vuetifyjs/vuetify/blob/28098001b875ed70f9a6788c6cea482f9488483a/packages/vuetify/src/components/VField/_variables.scss#L40-L43 and passes in the result of https://github.com/vuetifyjs/vuetify/blob/ae109459084b4384ff0db88c817c36e679943663/packages/vuetify/src/components/VTextarea/VTextarea.tsx#L162-L181
