### ISSUE TITLE
[Bug Report][3.3.23] VTextFiled counter feature has an issue when props changed from number to false.

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#18569]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
Step 1:  Enable counter (by switcher)
Step2: Disable counter(by switcher)

### Expected Behavior
When disabled the counter, the value of counter become false.

The counter number should disappered in right bottom.

### Actual Behavior
The counter number is always displayed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU0tv2zAM/iuELu2AOsmaDRg8N8Owa+87LDsoMt0I0AsW84Lh/17Krlq7j0svlsmP/PiJIv91IrZq+TuExfGAohQVoQ1GEm62DqA6FjKE4XcwlHcktcP2yQWg/MERtmXXxb0//fVtfa+tJvgFVp7/JBA2sJqaJdx+508jTcS+vwG6BCyh6zJjsn0D15/h+9L3mYbVEp6paDSaOjsBjNyhuduK+3RuxQtQPt2Esc9UfqHaVMtp6edOsaB40qT2b8WgkzuDuZdTVTW6qOnCMcrbIBVNwWNhfT0QzBS/kjIWnckwuuYyEx7dfEzCL7I/2F2RxUpzkpf4vo7cmimqjIxxyNMPrlCYrgh0KiwV69kDWO04bDX3yTP7fqxm3qxk6Bc4FjdvWhkJA+NfX3diuHeeZnbMxzl5xmmvlpMtYDOqVgeCiHQIXN09MDlxC4Y0bYNvCTposYEemtZbuOJluvqZctOGuMi5s5m6S8HX48hyWA56nqwRXyWsWo7VuZbob8R6sV58E+N5uxb/HwGBySkN)

**Comment by yuwu9145** [comment]
Upgrade to Vue 3.3.7 resolves the issue: [vue 3.3.7 playground](https://play.vuetifyjs.com/#eNqdU0tv2zAM/iuELu2AOskaDBs8N8Owa+87LDsoMt0I0AsW84Lh/17Krlq7j0svlsmP/PiJIv91IrZq+TuExfGAohQVoQ1GEm62DqA6FjKE4XcwlHcktcP2yQWg/MERtmXXxb0//fVtfa+tJvgFVp7/JBA2sJqaJdx+408jTcS+vwG6BCyh6zJjsn0D15/h+9L3mYbVEp6paDSaOjsBjNyhuduK+3RuxQtQPt2Esc9UfqHaVMtp6edOsaB40qT2b8WgkzuDuZdTVTW6qOnCMcrbIBVNwWNhfT0QzBS/kjIWnckwuuYyEx7dfEzCL7I/2F2RxUpzkpf4vo7cmimqjIxxyNMPrlCYrgh0KiwV69kDWO04bDX3yTP7fqxm3qxk6Bc4FjdvWhkJA+NfX3diuHeeZnbMxzl5xmmvlpMtYDOqVgeCiHQIXN09MDlxC4Y0bYNvCTposYEemtZbuOJluvqZctOGuMi5s5m6S8HX48hyWA56nqwRXyWsWo7VuZbob8R6sV58F+N5uxb/HwGB7SkQ)
