### ISSUE TITLE
[Bug Report][3.3.23] When navigation-drawers shrink, the internal avatar is also shrunk.

### ISSUE THREAD

**Issue by Nisekoi5** [vuetifyjs/vuetify#18561]
### Environment
**Vuetify Version:** 3.3.23
**Last working version:** 3.3.19
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open the playground and click on the avatar to zoom
Dropping vuetify version below 3.20 in playground works fine

.v-avatar.v-avatar--size-default {
    --v-avatar-height: 40px;
}
Overridden by the following styles
.v-navigation-drawer--rail:not(.v-navigation-drawer--expand-on-hover) .v-list-item .v-avatar, .v-navigation-drawer--rail.v-navigation-drawer--expand-on-hover:not(.v-navigation-drawer--is-hovering) .v-list-item .v-avatar {
    --v-avatar-height: 24px;
}

### Expected Behavior
The avatar is not shrunken, just like before

### Actual Behavior
The avatar is scaled to 24px

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VU2P00AM/StDLgsSSZZdVkJVF7E3hODIiXIwidsMzJdmnLDVav87nklLM03bC6KXZvwc+9kev3x7KoJv6gfnqqHHYlEsCbVTQPh+ZYRYDiU4lx7TobGGQBr0O9NoBN/+PSeLgq3taWJLVgOD3ABJa8rWw2/0U1yIodS2RXW/KnZokeMLDzKi8e8Yc+g1GDSUmz80Sja/du+Ie7EGFTB/NyM5kpeBSsltyBFO4tGhaUsYgMBz1I7IhUVdezCt1X1AX2mswcnaWU+ck0Kt0dTv7qqfbnPMWQiSpJDjfLKdEZ9RtvOiheCu5aYjxsx5PzJuYVCWFjwy5jnzS9X9IDO3c/PBSzDEZAgfac4i/iRPnx10K8umw8HzHBWuzziPra8CWXfo/4tTs0s1LetEbV5bnd3HKTCZFGOzMbZyiA1NkffPJ9xiDNGiCZK2TLSx2kHDNcW+z9lcuB2H+zHpU2c1lg2HPlX0fvwf2ekUPoDqIx6DzPFU2LQD/0gVmsb2vEAXiH7ZiofzXnu6ZwP9J8blxtvelSw4ipXpEv+vvKHhEvW4wiccLhLfY7nasXEmd8d6qFlJRaBt4tah3HS0EDd31+5xVaSU0WEqrDFTrqzRNJHfdMwkOlpGBc82iY+h8dKRCEj9KPBSR9UST8LjWjyLtbdaXPFH4SqCHDXuSaqDF5ldXpLv8dUB2634BFnWYw6OXjy/Lm6rt9V1Ccp1UL0p4vm2urktvv8BmaXMPw==)

**Comment by Ax3l3rator** [comment]
Hey, have u found any probable fixes for issue?

**Comment by Nisekoi5** [comment]
> Hey, have u found any probable fixes for issue?



Add !important for correct styles that are overridden

In my case, I added to the parent component
```
<style scoped>
:deep(.v-avatar.v-avatar--size-default.v-avatar--variant-flat) {
    --v-avatar-height: 40px !important;
}
</style>
```
