### ISSUE TITLE
[Bug Report][3.3.23] Autocomplete "delete all" doesn't clear the selection text

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#18572]
### Environment
**Vuetify Version:** 3.3.23
**Last working version:** 3.3.13
**Vue Version:** 3.1.5
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Pick a value.
- Now, focus on the autocomplete again.
- Hit "ctrl/cmd + a" and delete the text

The value gets reset, but the text in the input is not cleared to enter new filter text.  If you blur the input, the value resets back to nothing.

This used to work on our previous version 3.3.13

### Expected Behavior
When you clear the filter text, it actually gets cleared.

### Actual Behavior
It's persisting the filter text, so you can't enter a new search term without blurring and refocusing on th einput

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVT8EKgkAQ/ZVlLl5KIQ9BWBBC/UDQQT1sOsnCurOsqxTRv7eumXmaN2/ezLyXvaA1ZXTUOuw7hB0kFhstucVDrhhL+jXX2kPflKQsFwrNlxoVnaWS3BZanGjGJL+h3Odw/J/CPN8J96l1gixIuRR3MkrwYMWClCQZXtGATw6KytNnJFOPigs+eDuA65MaoeqgmA8fkmjpaDLv6KV7L/ThkugXGt4riMM43MJYNzEUH9sEWkY=)

**Comment by yuwu9145** [comment]
duplicates #18494
