### ISSUE TITLE
[Question] vuetify has any plan to use sass as style language?

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#1857]
because stylus is very less by used,and 'less' or 'sass' or 'css4' is popular,so vuetify have a plan change style source to be 'less','sass' or other style language on future?

**Comment by KaelWD** [comment]
Right now we have almost 7000 lines of stylus. There has been some discussion about converting it all to scss, but it would be a monumental amount of work for near zero benefit. No matter what language we use, there will be someone with an existing codebase wanting it to be translated over.  
If you want to use vuetify in an existing project and don't want to convert all of your stylesheets to stylus, you can just import the compiled CSS file into your scss and override what you need to. New projects should have no problem with stylus unless they rely on multiple third party frameworks.
