### ISSUE TITLE
[Bug Report][3.3.23] v-list-group closes open list even if `id` is unique after shuffled

### ISSUE THREAD

**Issue by daenamkim** [vuetifyjs/vuetify#18570]
### Environment
**Vuetify Version:** 3.3.23
**Last working version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Click `TOGGLE SHUFFLE`: make sure `NOW: TRUE` on the button
- Click `ADD` few times
- Click each group and select one of the sub menus under the group
- Some group list will be closed

Refresh the shared link and just click `ADD` with no shuffle then all group lists work as expected

### Expected Behavior
No groups list should not be closed on selection

### Actual Behavior
Some group list was closed on selection

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVm2P2kYQ/itTNxI+FRsOGlVCEPXUJFWlpK2UfAOk27PXsIrxOvba5GTx3zP74pc1BnFRvmAzr8/OPjPjdeXkWTB5SFO/LKizcJaCHtKYCPpmkwAsS4+kqXpVfwKeCMISmhkRCkNWQhCTPF9tnJR4v2+cRqdcnkQCfwYxC76gAU8ewhAt8Hc5Ubo20AQj/WDYfF9EUUxhBb+YV8sc4DPf7VD/ydi5//LjAqoKasfT6a4T/Tqy0sO/LKRZg+/wrPBJP6O69Rwy8Aea7MRewYlZLv7BC8j9WAkRl53cuPzFi0Qoj0C+DZmVngxmFUFhKb2IZ4jFrUAwEdMxlCQusAJjYElIv93ho8WxcWDxhT6jvVL2qtqk8XYZL1JYqFBorJ7r6dZX8jMv9KtZBr+SQLCSCAWqgjTjaQ6nAZc2GUNnPMcTQpJFlR4SpzoOCtQTBZPzrJMOuc+UnejnuZuy5cWTrAxWS1VKnXTjnDvUZRvSZVwBlelUtiH3+jQmn29ONWBZF/3xVVUbq7KfJq1A2Zwez/37RZIcbm/Upk+fYsb05/VJ6bFI1oWTkCU7tPyg33zf78aW/vYgkhI9p3pXvMyDjKUCcirMadgh5ZmACo5EBNhgEGX8ACMcfiNLzZOPsrVoeNkko1FPKdWILBdtB+FMQjt3vVUDRisz+rWgufhblnjQwFTAqCIS57SjbaddVyv1UZFgN/EEijTEEugE7h1UunDaXevCGt16W/eCBUtTxkfWvyPB3tUNvnpThwJQEp9hRJIENG8sa4llDFZWPy3yvdtRgp5FC+wo7ezH5InG466FwrOAtc1XK0gn0Oi/kmYlo8eRFaQTaMQvWqijXQUDOC9vBPLe3El+GUl9bQMmPxXKu5Im4goOekH/chDbzr92tdZv8qnfWASuobMmXMNV6CxDvaFWNodybEIXuY00+0jE3s9IEvIDCjyY+q/rTECxO26NaXzkA3/ahtNLVrfbtN9q6pOm7bGhJrLp3rSMRWbr0hJywPt4fM85PLx9C68qhaCe4lal1V2gbcS5R8LQu2zbvaGbs8FvcP+SjGf2P5p19sKstn2btWZizT3LawXzzmWrjeBqM02sgcs04bS+OZDkCS51P+Y7dxTsSbKj4ajhvT2NDR4TqIKQUmwukWFs3C0HGjI01gLNRcO4ZiO5JH9OAhuCBeD+XubWCrNKGr7LsFpDjoQJSOgR/scVxnLqZjIgrsrP7EB5IdxsDK+n0zuDuB9JLZ46jZV/NmvzD5RQLp26NB1KDPfF2TjTvBlJ3tz3R5UhyUiSpKe059PlmLNrMXvKW2POr8XsKbsx2ylaS3FXayovJ/rLBr9pnNPYmftz/w9HP2dzZ/sdtwH80Q==)

**Comment by KaelWD** [comment]
If you use a stable key instead of the index it works as expected.
