### ISSUE TITLE
[Bug Report][3.3.23] can't hide navigation drawer border with `border` prop

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#18581]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Edge 118.0.2088.76
**OS:** Windows 10

### Steps to reproduce
Add `:border="false"` to drawer

### Expected Behavior
Border should disappear

### Actual Behavior
Border is still there
![image](https://github.com/vuetifyjs/vuetify/assets/40021217/8a3be60d-aea7-4bd2-b44a-6ee6ad37358c)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUEtOwzAQvcrgTUAiCRBWVYrEjhuwICxMPCmW/NN4EpCq3h0nDv1I3XnevI/ffOxFpL5+DaGaRhQb0TLaYCTjS+cA2qmUISzPZXBy0jvJ2rtSkfxBgs2XJ4W07cQgTcROwFRar9AkJFM6seoBViC71VfsTkm9dyy1O0ILyPjL5aDRqLMUG3cptf6XJttL7YzkEm19Vi6NsScdGCLymDtqGzwx7IFwgAMM5C0U6S7FvEyukdcKsJ0pt0wj3p126SfronhDYzy8ezLqpkiUts5hKUYc7kVTPVcPpTThW1aPYp6b6qkRn39xDoJb)

**Comment by websitevirtuoso** [comment]
Yes everything correct.

![image](https://github.com/vuetifyjs/vuetify/assets/5112918/7ea02893-4fe3-468b-94a0-31856281265e)
On the screenshot you can see that we add class v-navigation-drawer--border if prop border="true"

To change styles and set more thin or something we have to change sass variables.
https://vuetifyjs.com/en/api/v-navigation-drawer/#sass

By default navigation always has border-right or left. It mentioned in documentation
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/faff5cd8-a544-461f-b31a-f40cca88fdf9)

use css to remove border. this is what I can say.

**Comment by kingyue737** [comment]
my bad. This border can be removed by `floating`
