### ISSUE TITLE
[Bug Report][3.3.23] V-Data-Table Destructure Property 'page'

### ISSUE THREAD

**Issue by batugkocak** [vuetifyjs/vuetify#18583]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
There is no steps to produce this bug. I only implemented v-data-table-server as shown in documentation. It has no unexpected functionality but only an error on browser console:

VehiclesOnTaskArchiveTable.vue:161 Uncaught (in promise) TypeError: Cannot destructure property 'page' of 'undefined' as it is undefined.

### Expected Behavior
There is no bug in its functionality

### Actual Behavior
Not giving an error on console

### Reproduction Link
[https://github.com/batugkocak/YilportVehicleDelivery.Client/blob/main/src/components/vehiclesonTaskArchive/VehiclesOnTaskArchiveTable.vue](https://github.com/batugkocak/YilportVehicleDelivery.Client/blob/main/src/components/vehiclesonTaskArchive/VehiclesOnTaskArchiveTable.vue)

### Other comments
I am a beginner at Vue and Vuetfiy. It might caused only on me because of my own mistake but still I wanted to report to you.

**Comment by KaelWD** [comment]
You aren't passing any arguments here: https://github.com/batugkocak/YilportVehicleDelivery.Client/blob/main/src/components/vehiclesonTaskArchive/VehiclesOnTaskArchiveTable.vue#L221
