### ISSUE TITLE
[Bug Report][3.3.23] VDataTableServer memory leak

### ISSUE THREAD

**Issue by volarname** [vuetifyjs/vuetify#18599]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 118.0.0.0
**OS:** Windows

### Steps to reproduce
using reproduction link:
- clone repository
- check README.md inside repository

without reproduction link:
- it's really simple, just create any VDataTableServer example and try to mount and unmount the component for example using changing the route
- force garbage collect and compare memory usage at start and after several mounts/unmounts

### Expected Behavior
VDataTableServer component after being unmounted should not affect memory, all its temp data inside memory should be cleared

### Actual Behavior
memory leak, after being unmounted, in memory stays some data

### Reproduction Link
[https://github.com/volarname/vuetify-memory-leak](https://github.com/volarname/vuetify-memory-leak)

### Other comments
- also on vuetify@3.3.3, so probably the issue is there from first versions
- also on vuetify@3.4.0-beta.0
- 20 unmounts are creating memory leak ~ 14MB !!! on windows chrome

**Comment by KaelWD** [comment]
I don't see any significant memory increase even with 1000 iterations.
