### ISSUE TITLE
[Bug Report][3.4.0-beta.0] Cancel on select

### ISSUE THREAD

**Issue by mirabo-giangnvh** [vuetifyjs/vuetify#18596]
### Environment
**Vuetify Version:** 3.4.0-beta.0
**Vue Version:** 3.4.0-alpha.1
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7, Windows, Android, iOS, Mac OSX

### Steps to reproduce
1. Select a file > File are displayed
2. Select file again 
3. Cancel on file select. 
Result: 
The selected file will be removed on cancel event.  

### Expected Behavior
The selected file will be removed on cancel event.  

### Actual Behavior
The selected file are displayed on selected file. 

### Reproduction Link
[https://codepen.io/onelly/pen/xxOBJjL](https://codepen.io/onelly/pen/xxOBJjL)

**Comment by KaelWD** [comment]
Works for me, you're just ignoring the change with `if (!file) return`
