### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by meepdarknessmeep** [vuetifyjs/vuetify#186]
If you make huge breaking changes such as in v0.8.8 could you change something other than the minor version? It's very uncommon for people to only change minor versions in cases such as this. 

Also is there a discussion area for vuetify? Mailing list? Forum? etc

**Comment by johnleider** [comment]
The best place to discuss Vuetify would be on [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#). As far as semver, I realize that it was not being followed properly in the past. That will not be the case in the future. Starting with v0.9.0 and on, breaking changes will only happen in major releases.
