### ISSUE TITLE
[Bug Report][3.4.0-beta.0] v-navigation-drawer overflow elipsis

### ISSUE THREAD

**Issue by maxiwolleb** [vuetifyjs/vuetify#18609]
### Environment
**Vuetify Version:** 3.4.0-beta.0
**Last working version:** 3.4.0-beta.0
**Vue Version:** 3.3.8
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
Make Navigation drawer with v-list-item where subtitle or title are overflowing.

### Expected Behavior
Overflow used to be ellipsed 

### Actual Behavior
is not ellipsed anymore

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtU01r3DAQ/StC58pqs5SWZRvIrZT2VHrq9jC1hD3B+kAae7OE/PeMvOusTRxIIGCwNG/mab7e33uZU61vYqyG3sqt3JF1sQOy13svxG5QHRxDT+NtvHsYsAHC4JVJcLBJRJsceOtJdKEekW97mbBpaS/PcRw58YpB5S7QNiYbrTdPDqfHMJNCdr1YhejQ28yUdAh7OQfOFAoGIEjs0RLFvNU6gTfB9dmmylkNEXUMiRIgZX0Iznr99VN1G5slHSF1lll+cDHit0Nql3ju/08uP0PTWJPh/EEu3+p5bjQC/ZzyeqdnJV9apWczeDIOyuCAxqYxajovHAqVMNZnpCMnWQcXoeYhCJ7ZK/o8tRPrcYLOoGq5WapmuvVOfWd4iQzQ9QUpga8o9U3JQF2H3nM9a6n8OoqbNXxKaCX4HXNSTQp9VCyUsqzrGf7hdczryZVNXUAvbsbJOqmRr8/keFGqA/Qi03F8vbVFkFtx9fljvGNdltjicJJ54Z10vlg/+fBBbqpN9UWe/lcb+e8Rmh5NUg==)

### Other comments
In the documentation there are cards around the examples, if there is a card around the navigation drawer it works but breaks expand when resized.

**Comment by KaelWD** [comment]
> Overflow used to be ellipsed

When?

**Comment by maxiwolleb** [comment]
> > Overflow used to be ellipsed
> 
> When?

Vuetify 2 
https://codepen.io/Maxxiiii/pen/eYxgvRa

and in the Docs of Vuetify3
https://play.vuetifyjs.com/#eNqVVF9v0zAQ/ypWXrZJSzKxDaTQTcADDwiEBOJp3YNrO403x7ZsJ2uY+t25cxOaZC1iUaWef77/9/PdPSfesfyjtVnbiKRIFkHUVtEgbpeakEWbMuo4ioQwRb2/WSb1JqVNMMtkBz9JHiqA31y/3UHRMtoq2pkm9OeIaNrKNQ3S6JQ7+iQcscLVVAsdCF15o5o+8l8LJf3ewwhLJWQ6xgmxTliheUpbGqiDlKoQrC/ynHGN5QVZdg8+Y6bOZU3XwucPptKZ1euhluELMigBDr7APfkqJBduruKb1aCFXj6suae7nzFrJTDK1GRSBJQxNJq0qVcmFNRi8jOtWO4q6DkK8eVvjO1rqtQ8N/xa6iTVAVSC2IRDGpIZjePkMq2FblJunvRLvdtFHjOYp59PiLKHR9MZD7LHAZpMl8sWmxuDDPJMBc3GIQoltUAellR5MU2YC+1l6OAS2m8pm9UN7Nsf/5NUbVoa5NIpXp0TeUakJij7ea+KR4GR5Qu8parBWUXns0tmVHRvHVDSda+jTE/4Q5zB4ZKiHzEGzlBeJrHTKP5rnrOrUW/SyHmIj6QaPO8IFj3PFF/LjT3wYlGM0oKEagpT8KGL768Scl2FglxeX9nN+z4T1Bg2EQbYryI84laDw6zqhWdO2p2W2FjjAjCqpI0K5HnnisNmKcjpGbm5Jac9Bi8J6VCQu31NzwSbUpCTbx35LJXwJ0Ad6Dog+N5Ko4DpJ2R7fsDkZ0Wd4LBXQ0VqMTWkjJlGh7SGnKRV4pgL2H/gY2rrATyi/0Mw2MBT9QpGYlx3xOJ7WeI7nJqwSrDHlEnHjmb2yyoDS3Jq10TwiMUnyh4bO7NgyjT8gN19L23PorDFEfdDTbbnyWV2mb1L8P8qu0hXItDsIrn/A89UCII=

**Comment by maxiwolleb** [comment]
Closed by missclick ^^

**Comment by KaelWD** [comment]
> Vuetify 2

Wasn't using `webkit-line-clamp`, two-line just made it taller

> and in the Docs of Vuetify3

That example doesn't have `lines="two"`, the default is one.

**Comment by maxiwolleb** [comment]
> > Vuetify 2
> 
> Wasn't using `webkit-line-clamp`, two-line just made it taller
> 
> > and in the Docs of Vuetify3
> 
> That example doesn't have `lines="two"`, the default is one.

Yes, but if you plan to use it outside of the Playground in your app you wont have a card around it. If you remove the card in the Vuetify 3 example the behavior isnt as planed, or is it?

https://play.vuetifyjs.com/#eNqVVFFr2zAQ/iuHX9pCbRfaMTBp2fawh7Ex2NhT0wdFPsdqZUlIshsv5L/v5NiNlTbQQSDSp/vuPt138v02cZbnn43JuhaTIll4bIxkHu+WCmDRpZL1uvXDbtgr1ok180KrtLTsGS0YtA1TqDywldOyHbljvBRuYs+QVFCdAwpgLBpUZco65pm9XSa198YVec5LFaR5UfWPLuO6yUXD1ujyR12rzKj1Mpnn8cJLJPo3OoXvKEq0cYBrV1NMyPBpXTq2/2m9lhgqzAkz6SR+ag50qZPaF8wE0VHMcMWVV+DE31DENUzKZQIds4IpT4jHjSdAcK1o15QibVC1aamf1TK5W+QDPa6bR65M4KyVh46PKAEzE0rRhU4Myad1FBAoUEih0JGmikmHJLFE5YTvCaGuGMaDbPL/HXZ2aaWDi+fh4BLEBQgFYe1iN4onDOnFEdox2YbmDWmjI67lkNhYGgPbv9+qccBeexV8gGJ0IxTMwnp0IixPWxEdzDqRDhNGlYPVU9a97UPWo8D/MXXavnqGL3JISMOo2873w5TXKNa1L+D6w43ZjAJCwP6Bh8zTCz+628JxK8y+KG6Mtp4GomKt9LDdlyrprRZwfgG3d3A+YrC3uYD7w622EC5fwNmPHr4Kie6MRoI6S0gY/0pLGsgz2F2+QfldM4slPAtfQ4MxkXGuW+XThjQJI/FUCvqiUI6Y6wg8Ef8LOX3N4vCa2q9tf4Lxs6rC24kpvEb+lHJh+Ullf4zU9OmJee0AnmB8YfypNUcMLnVbvsF7GFe7i2GxCxa/mJrsLpPr7Dr7mIT/m+wqXaFn2VXy8A9UvtoT
