### ISSUE TITLE
[Feature Request] Add "lazy" property to v-select to improve loading performance

### ISSUE THREAD

**Issue by HendrikJan** [vuetifyjs/vuetify#18608]
### Problem to solve
When having lots of v-select inputs on a page (for instance every cell in a table), it takes a long time to load.

### Proposed solution
Add a "lazy" property to the v-select component.
When `lazy == true`, the initialization of the v-select is postponed until the user clicks on the v-select.

I've got a reproduction that shows how loading multiple v-select can be slow  (around 500 ms on my computer):
https://play.vuetifyjs.com/#eNqNVs1u4zYQfpWpgIUVrC1n19tFkTrGpu2hhxY99GcPTg60NLKJUKRAUnYDw+/eISnZlKxucpI0v9/MfENqfUyMzucPdZ3tG0zukqXFqhbM4upRAiz3M1bX/tV/5EpaxiXqVuSF5sBtvgPBNijuH5O/DcJB6WemVSOLxwT2s0oVXtUYLrdfI91qOe/8LxEtr5AyVTV58nLMDb5U9GKxICU3v4d3itaFCMAFagv2pUZnJUtFfrlgxtBntZl96tkDfEVgGkGqA/h8wKIqMqc2O9IxAmV2iBZSLo1FVoAqgcWRyAAF5vYGCBcXYHdIIVFTdp4/G1DSi9o42XKjYd6D8lDaztoBiYzh0MJoZT5PBg8GXlQDOZNgEKdOG8cLZrON+hcNCEWQq4YGVjLCryHdNNa7S8QCrAqJwR54ju4zePfiqQrtjqDdRA2nQfqOx0PouERQS6XdGIBL+HB7O+i9I9FVFtdIP/49N3wj8E9vYdb86TEZ2nUEC1H+YaLBUUOmOZOWDFVjBfGYSNO3KFAabl/IwhGQEaKBwR2nohyFQqo/asuVNH2rwGqvvyrTTXGIHoXpzQvgwAu7oyTUqndDBBulC9R9mScpVdMTxmSHms0Ww0hf/KTHOgz3YHWDQ4fV8djS4dxiOJ18tcO6YhrMe2dKK+qWfHzvXUu+sc4HpiXx700b7fYl7LNgeksb3lQbR3vq7U1bjd+MsUUc7NXSWK3kdkXkN2DZM60TRSUJOOxuWdx2LeetWfbKeoyx/npT+to3Mf01nr/C8tc5Psbw65k6o/6N4dvgL5QeKejT5JrXltpsm+DOq1rRwI+gsYQTlFpVMKE7ahIp/6KEPzvCBG027wTuMiNDZ0oAjA1H+uUKIX5T2LRkRDN/iAWrXr2tzTrUMlFeCh8m077g41CwGAo+DQXfDwWfg+CJoFzA7P1sCcX6KYiJGJAKugQ4CW9/pMfSMYRe3r+/gWMIGbyyujG7tFdO5jVrDu/gs0sEcIqzxXxqKw+hovb0j4muPyFY2cjc13K+j9MzJuetBGZCbdNJq51cQ6jMto05+RWFUEDzEsV3zpJWyvODmJFM/R9LPOnr35aC7zsOtrv4Gy2mv0yVegY6xtyi0rcLQ0cYVFxwg4SjMOf17QIIZeEusqfFiL78T4yzaQkeUr+d3kq2HZnS609IQ0YvmI4Q3zk6AhjLtPXQ7+nWPsAvlCeNBhUXFzp621KrlyKlEd2vuin9f9DT2bkbbc8x5MwbrVGOByDUF0SBiGQTeWRb9E+KO7sAuUg7FDEPTtNkkS2yH4gQ7vlxkTz9B3qCYME=

As you can also see in the reproduction, if you use a v-sheet instead of v-select and replace the v-sheet with the v-select upon clicking, the loading is quick (around 40 ms on my computer).
Downside of this solution is that the code becomes more complex, and that you have to click twice to select something in the selectbox.

**Comment by KaelWD** [comment]
This is exactly what VVirtualScroll is for: https://play.vuetifyjs.com/#eNrFVs1u4zYQfpWpgYUVrC1712lQuI6xaXvooUWB/u3BCQpaGllEKFEgKbuB4XfvkJRsUnG3ufVii8P5+TjzzZCb40irbPbQNOm+xdFytDJYNYIZXD/WAKv9lDWN+3SLTNaG8RpVJ3JCfeAmK0GwLYr7x9EfGuEg1TNTsq3zxxHsp5XM3Vareb37HOytV7Pe/uLR8AopUtWQJS+umcGnij4M5rTJ9c/+m7z1LjxwgcqAeWnQatWFJLtMMK1pWW2nt5E+wGcEphBqeQAXD1hwitRu65L2GIHSJaKBhNfaIMtBFsBCT6SAAjNzA4SLCzAlkktUFJ1nzxpk7USdn3S1VTCLoDwUpte2QAJlOHQwOpmLk8KDhhfZQsZq0IgTuxv682rTrfwbNQhJkKuWClYwwq8g2bbGmdeIORjpA4M58Azt0ltH/mSFpiRoN0HCqZAu42ERei4R1EIqWwbgNXyYzwe5tyR6FcUm0pV/zzXfCvzNaegNf3ocDfV6gnkvfzLR4lVFpjirDSnK1gjiMZEm1six1ty8kIYlICNEA4Ulp0NZCvlQvzSGy1rHWp7Vbv/VMW0Vh+hR6KheAAeem5KCUKreDRFspcpRxTJHUjpNJAzJDg2bLoaePrlKX8sw3INRLQ4N1sdjR4dziuF0cqcdniukwSyaKZ2ob/LrfW9T8oV2PjBVE//e1NG2X3w/C6Z21OFttbW0p9zedKdxnXGtEQd9tdJGyXq3JvJrMOyZ2om8kgQsdtsstrtWs04t/Y/22E/3XJmWianOlBRiMESEtEw9gmXcxP3+igWc4qIopMIrgVqH0jNLH5RiL2mhZJUcQWC9M+XSNiCcJpD8RV5v4H5Nv7FTaz0tke9Ki+DuY7j7lsZdKrSN20FO95Ysb21asvm/+jYsvi1YXJ0vkNcqx1ejq7e7OSP205Kc8cYQn0zrzXnVSGL2kUpJ1QVbKxjTZTwONn+ngN/bzvC76awX2FubFK0qAdDG312Xu5IamdwmBaN+ctPaa0VJ6HQ2/ixj6aTwYTyJBR+HgsVQcDsUfD0U3HnBE0G5gHH0sCg2T15MdwUkgm47TsL5t/S3spylj/fvb+DoXXqrtGl1mUTH8XTbcHgHdzYQUMsE0UK2dSf3roL0xPOwz493VrR15s5yfngkZ0zWWgpMhdwl4253/BpCpXedz/GPKIQEqpfIv7KaNDscP4gZo4l7moWVfv0+y/m+52A3dH6iCeReDVI+A81rO5Fobd3QrIaKC66RcOT6PKd6BzRwYBnoU7cEK/daszodwX3ot9Nb1l1GJvT5HVKR0QkmV4hvDS0BtGHKOOj39Dw5wA8UJwkKFR7OZ3TeUSsKkVCJaMx1Vfp3p6ezcV/ayNDHzFpFQ/e6A0J9QeSJSDqBRbpD909+pxcgF2mPIuTBaTJapIv0GyLEIr1N59MtGpbOR0//AEWmozA=
