### ISSUE TITLE
[Bug Report][3.3.23] VTextField type="date" year mask allows to input 6 digits

### ISSUE THREAD

**Issue by an-lev** [vuetifyjs/vuetify#18603]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Type '01' digits for day.
2. Type '01' digits for month.
3. Type '202323' or 6 digits for year.

### Expected Behavior
Field contains value 01-01-2023

### Actual Behavior
Field contains value 01-01-202323

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjsGKwjAQhl9ldi7dhW26u92TVMGbb+DBegjtVAtJMyRjUcR3N2kVxNt8P8P3/7srBt8Ua2Y1nggXWAlZNlpoVQ8A1Zhr5umcoHGD6H4g/4imUOgsedeTaWHMrWvJLGu04VAjyIUpQht9kYqnqHg3pWQuqoqXARFD43sWCCSneUdv2XmBK3jq4AaddxayuD1L7wDRGwRiOyzTx2e2IWMcbJ037Uf2lQpmZZTh7RtL9a9+cm34qNUvJi7VX4n7O91hWr8=)

**Comment by KaelWD** [comment]
This is browser behaviour, it's just using `<input type="date">`
