### ISSUE TITLE
[Bug Report][3.4.0-beta.0] Inconsistent styling with "Disabled" prop on Button components

### ISSUE THREAD

**Issue by chris-oleson** [vuetifyjs/vuetify#18601]
### Environment
**Vuetify Version:** 3.4.0-beta.0
**Vue Version:** 3.4.0-alpha.1
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
Disable a button inside a v-app-bar component, disable a button in the v-main component.

### Expected Behavior
They should have the same opacity

### Actual Behavior
They have different opacity levels

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADNhHN2kxCKoAFgoqSRPISWzODEpJzXFLiM1JyffRh8sCtMF5KFqA2rKTcyEyWMa4oHdELgeqIlAto0+kmuVanWUjPVM9Ax0E3MKMhL1DJVg/KTUkkQ9A6VYAJiiSK4=)

### Other comments
Temporary fix:

.v-btn__overlay {
    display: none;
}

.v-btn--disabled {
    opacity: .26 !important
}

**Comment by KaelWD** [comment]
Toolbars set `variant="text"`: https://vuetifyjs.com/en/features/global-configuration/#contextual-defaults
