### ISSUE TITLE
Feature request/Question: Disable text-overflow for multi-select

### ISSUE THREAD

**Issue by AshwinTayson** [vuetifyjs/vuetify#1861]
Feature Request:

There should be an option in select component, when there are multiple options selected and if options are too big to go to the next line it should show "+n options" selected.

What will it allow you to do that you can't do today? How will it make current work-arounds straightforward? What potential bugs and edge cases does it help to avoid?

**Ans**: Suppose there is a multi-select component with 200px width. Then selecting more than 2-3 options will make the component grow to the next line. With a lot of options selected this will grow exponentially and break the UI further. Ideally for a fixed layout there should be a prop which disables this "text-overflow" and show just "+n **text here" -> +2 selected or +3 filters. This will help the UI not to break and give sense to the user how many options are selected.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement.
