### ISSUE TITLE
[Bug Report][3.3.23] V-data-table item.raw issue

### ISSUE THREAD

**Issue by devcoder111** [vuetifyjs/vuetify#18612]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
As I remember, in vuetify 3.3.18,  vuetify had breaking changes. item.raw and item.columns have moved to a new internalItem property. so I replaced these on our project
But on body slot, item.raw and item.columns are not yet gone.
https://prnt.sc/g5bW_mNkgXjx

It would be great if item.raw can be moved on body slot also
Thanks

### Expected Behavior
No need functionalities

### Actual Behavior
No need functionalities

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtll1v2jAUhv/KUaSpq1RCSAgtEas0tfvouovdTqUXJjE0qokjx6HrEP99Nk5CbOIIpHGDfc557cevP+Bp6xQsHn7Oc3dTYidyZhyvc4I4vp1nALPNIEEcDThaECwDANELRglmxae5U7XmTpVJhVbGE1wUmPEmIeODDSIlFskMrXGdiAkqpAATvEE8pdlgpFL7ycX0NQxsBgWhPFrQ5F3Ub/dDFrCbO1WlrGWiakmZyMsspJmqmjsQvWIpk12XoTdXMTTTxyUrKBvkNM14a0Q5ZnK7VZM1OtjtZkMRb+YdclbjDnXzhm33REjLi24RszTn+1r8J6eMQ4KXqCQctmpAqf54WfcAGOYlyw59gGoLIng6xKBdID885QRHcHGv9gU+jjxvBaK5SbPV5cWVXo1IuspEdcER42ZS+LRfTQRLRApsZIXNQihd0nU7rbdtgO4QoSzFxcVVJY3rgFXyFQl+CV0plojbi+8QWxRaeSwjdsEvRjkWB6ctyVXMLnpgVCg+HBSpCOjlz612fTv690yaKJfL6F+cwW+6Ko83o3YrglE4NXLClwgmrnckEeuPwB8b8WqREYyPJHI1Yoa+De1Ef4gxxAyjNRQoS97S+MXO7wfXXfxTG/9ReYs/+E/8X8TzkLIe5onfxTyym26SNdDHEgWtr/IU6Lsyj9Grcf3a1IEXdlEHruloBT052+mbs6G/iWcIs4U4K0kPeDg5z+6xeSUa8sA1U9UZ0Wc4Bf0HJuQdFhhlPeTXnZZ7NvCp9XIeSxS4Hj2F+yclJM1p3kM97TzenmuGa2p939vUncz6MKcwf6cZfo/pemGHHnsmRXW6LdA31tM9cc1NU9hjPXwK9z3Nyp63exx2Gu2HtvMR6m+ZdiW7D7Z/vtmPKX8UP61W6nDU6bRvvY4T08+G2twDxWy/i4cf051qqKTozIbNXypnd+UErnjWHPXtB87zP0fttlc=)

**Comment by KaelWD** [comment]
Hmm yeah that is inconsistent I guess. In the other slots it's free because we're already iterating over `items`, to do the same thing in the body slot would require an extra `items.map(item => item.raw)`

**Comment by devcoder111** [comment]
Thanks
