### ISSUE TITLE
[Bug Report][2.7.0] v-date-picker not working on build production, justo works in dev

### ISSUE THREAD

**Issue by martseguel** [vuetifyjs/vuetify#18611]
### Environment
**Vuetify Version:** 2.7.0
**Vue Version:** 2.6.1
**Browsers:** Google Chrome, Mozilla Firefox, Safari
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
In npm run dev works fine, in build production im getting error: Uncaught (in promise) TypeError: e.dateRange.start.getMinutes is not a function

### Expected Behavior
Work as npm run dev, choosing sate

### Actual Behavior
in dev its not working. Getting error: Uncaught (in promise) TypeError: e.dateRange.start.getMinutes is not a function

### Reproduction Link
[https://github.com/martseguel/error.v-date-picker](https://github.com/martseguel/error.v-date-picker)

**Comment by KaelWD** [comment]
I think you're using a different library, none of the props you're using there have ever existed. And why did you comment on #18558 if you're using v2.7?
