### ISSUE TITLE
[Bug Report][3.4.0-beta.0] VStepperWindow - touch is not disabled by default

### ISSUE THREAD

**Issue by Gandhi11** [vuetifyjs/vuetify#18621]
### Environment
**Vuetify Version:** 3.4.0-beta.0
**Vue Version:** 3.3.8
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Make sure to use device mode in console to activate the touch in chrome
- Try to swipe the window right to left

### Expected Behavior
Based on the documentation (https://vuetifyjs.com/en/api/v-stepper-window/#props-touch), the touch property should be `false` by default therefore the windows should not swipe right to left.

### Actual Behavior
The windows can be swiped by default.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdk81OwzAMgF/F5DIQtKUrp6qb4MadAwfGIWo9VpE2UZJ2SNPeHfcP0q1DY6c29qfPsRW/7ZjRafCklF9XyGKWWCyU4BaXqxIgqT2uVPvbHlJZWp6XqPtQGzQWlUINtVfIDMVixZrIiv0wRA1WgoyQNs5wzSthHcRVeRvkmVPkKJ+TD+KaiwqpXEi1XigDYRKMmXMN88Ewv9QQDYboT4ObnGjS0W/zMpPb0+W7/FmTcNB/+qbncrlvekqnfMfMqWHx1OayNOPLPKYiTz/jEr9s/yZhAe3nFmhQk7DSWB/A3iG8dO/VV3bfejBaoYNGhl2iyHiZmki3ayMBHU2qc2XBoK26VcwLJbWFHWhcwx7WWhYwo/WdNTgAeY2FwnxQB0Rcz55RCAmvUovsanbzi/RdNkxI4SToKlENtr9jkf/g33tcqA33Q9acI38esfdvpatMwg==)

### Other comments
Maybe related to https://github.com/vuetifyjs/vuetify/issues/18605

**Comment by Disservin** [comment]
that's actually because it's undefined (instead of false) by default https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VWindow/VWindow.tsx#L69
