### ISSUE TITLE
[Bug Report][3.3.23] v-table does not handle ctrl-click

### ISSUE THREAD

**Issue by LaKing** [vuetifyjs/vuetify#18624]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 118.0.0.0, Mozilla Firefox, Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a simple v-table like in Vuetify playground. This is what we are after: `@click.ctrl.exact="console.log('ctrl-click')"`
Open the console, and observe that shift-click and mouse click is logged on the console while ctrl-click is not.

### Expected Behavior
ctrl-click should be logged according to vue documentation

### Actual Behavior
the ctrl click is not captured

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kcFugzAQRH/Fcg9pJWOaJu0hdVH7HSEHYzYFxcEINogI8e+xSYKJhHKxPDvz9jC77WhdqfCvLHlzArqhAuFYaokQxQUhoglQJvoqrMQMZHoTTlbjfzCjFxHad/TDMeDmHhWYmPQ83ePXNMHeVD8xbUlekO2SfbAVW7NP9rWLqU9tDnB2oensV+lcHbjCSnNopUIbUKaojQauzf/rwjnBEFq8zYB1lu9xnhysJ+gsdDSnGu7Qt6ceOkujriMt6Xvb0KTZh+bGskTo72Hn/lK0Z3TF1/w9kLrMJF/Su04AndxdAFUGjkw=)

### Other comments
firefox marks the selected td element, chrome and other browsers not.

**Comment by KaelWD** [comment]
Works for me in linux. This is unlikely to be caused by vuetify anyway, v-table just renders a `<table>` with a bit of CSS.

**Comment by LaKing** [comment]
I checked it on linux, and indeed it works there, so it really seems to be platform specific.

Isn't this functionality provided by vue3?

**Comment by KaelWD** [comment]
Yes, vue is https://github.com/vuejs/core/

**Comment by LaKing** [comment]
I think this is even rooted deeper.

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey

On mac (...) ctrlKey is not detectable on click events. :/

**Comment by KaelWD** [comment]
Incredible design, thanks apple. I think on mac you have to use cmd instead with this check https://github.com/vuetifyjs/vuetify/blob/33feacf46d0250ec28584f34c39239f34c9d35d4/packages/docs/src/components/app/search/Search.vue#L188

**Comment by LaKing** [comment]
Yeah, that would possibly do the trick.

Thank you very much!
