### ISSUE TITLE
[Documentation] Provide additional documentation for VDataTable header slot and show sort icon on hover

### ISSUE THREAD

**Issue by 1Luc1** [vuetifyjs/vuetify#18628]
### Problem to solve
As stated [here within the docs](https://vuetifyjs.com/en/components/data-tables/headers/#column-slot):

> You can also override all the internal headers by using the headers slot. Remember that you will have to re-implement any internal functionality like sorting.

I just don't know how to show the sort icon on hover the VDataTable header. Like the default functionality.

### Proposed solution
Update the [example](https://vuetifyjs.com/en/components/data-tables/headers/#column-slot) to include this functionality.

**Comment by jakubmatisak** [comment]
I don't know if this will help you, but this is how I'm using sorting on mobile devices.
I hope that you can find here what you need.

And yes, it was hell to find out how to do it.
```

    <template
      #headers="{ columns, isSorted, getSortIcon, toggleSort, sortBy }"
    >
      <v-expansion-panels
        variant="accordion"
      >
        <v-expansion-panel
          elevation="1"
        >
          <v-expansion-panel-text>
            <v-list>
              <v-list-item
                v-for="item in columns"
                :key="item.key"
                :title="item.title"
                :value="item"
                @click="item.sortable ? toggleSort(item) : null "
              >
                <template
                  v-if="isSorted(item)"
                  #append
                >
                  <div class="align-center d-flex justify-center">
                    <v-badge
                      class="mx-3"
                      :content="sortBy.indexOf(sortBy.find(el => el.key === item.key)) + 1"
                    />
                    <v-icon :icon="getSortIcon(item)" />
                  </div>
                </template>
              </v-list-item>
            </v-list>
          </v-expansion-panel-text>
        </v-expansion-panel>
      </v-expansion-panels>
    </template>
```

**Comment by 1Luc1** [comment]
thanks for your reply. This is kind of the same answer as [here](https://github.com/vuetifyjs/vuetify/issues/17590#issuecomment-1588835819), but still this doesn't cover the hover effect like you have with the default behavior (see image below).

![grafik](https://github.com/vuetifyjs/vuetify/assets/25635952/d44c8c02-a8d7-4325-b0c6-1ddeefe45a79)

**Comment by MajesticPotatoe** [comment]
Same concept as both of those, just stick a v-hover around it and hide/show the icon.

```html
<template v-for="column in columns" :key="column.key">
  <v-hover>
    <template v-slot:default="{ isHovering, props }">
      <td v-bind="props">
        <span
          class="mr-2 cursor-pointer"
          :class="isHovering ? '' : 'pr-6'"
          @click="() => toggleSort(column)"
        >{{ column.title }}</span>
        <v-icon
          v-show="isSorted(column) || isHovering"
          :icon="getSortIcon(column)"
        ></v-icon>
      </td>
    </template>
   </v-hover>
</template>
```
Mashing hover into this particular example gets kinda janky with the remove column icons being there. The sorting itself is still there the icon just pops up when it is sorted by clicking the header instead of on hover.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com)

**Comment by Mohammad-Alavi** [comment]
Here is what I ended up with.
The behavior is exactly the same as the current data-table. With correct hover effect, sort icon and multi-sort counter badge.

```js
<template #[`header.YOUR_COLUMN_NAME`]="{ column, isSorted, toggleSort, getSortIcon, sortBy }">
    <v-tooltip text="something...">
        <template #activator="{ props }">
            <div class="v-data-table-header__content">
                <!-- this is the tooltip icon-->
                <v-icon v-bind="props" icon="mdi-information" />
                <div class="v-data-table-header__content">
                    <span @click="() => toggleSort(column)">{{ column.title }}</span>
                    <v-icon v-if="column.sortable && !disableSort" class="v-data-table-header__sort-icon" :icon="getSortIcon(column)" />
                    <div v-if="multiSort && isSorted(column)" class="v-data-table-header__sort-badge">
                        {{ sortBy.findIndex((x) => x.key === column.key) + 1 }}
                    </div>
                </div>
            </div>
        </template>
    </v-tooltip>
</template>
```
Some context:
‍‍`disableSort` is a variable I use to disable the sorting is some situations, e,g. while fetching data from server.
:disable-sort="disableSort" 
`multiSort` is a prop I use to configure my data-table component.
:multi-sort="multiSort"

Change these stuff according to your code.

Here is the [reference](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx) I used to write this code.

**Comment by vvenkataratnam** [comment]
I would like to have a filter icon next to header column. If i see filter icon, the sort of icon is missing. How can i add sort icon with all of its functionality

Here is my custom component

`
<template>
  <v-data-table
    v-bind="$attrs"
    :headers="headers"
    :items="filteredItems"
    :loading="loading"
    :search="search"
    :no-data-text="$t('noDataAvailable')"
  >
    <template
      v-for="(col, i) in searchFilters"
      v-slot:[`header.${i}`]="{ column }"
    >
      <td class="pa-0">
        <div style="display: inline-block">
          {{ column.title }}
        </div>
      </td>
      <td class="pa-0">
        <span style="float: right">
          <v-menu
            :key="i"
            density="compact"
            :close-on-content-click="false"
            transition="v-slide-y-transition"
            offset-y              
           
            
          >
            <template v-slot:activator="{ props }">
              <sup>
                <v-icon
                  color="teal"
                  icon
                  v-bind="props"
                  size="small"
                  :color="
                    searchFilters[column.key] &&
                    searchFilters[column.key].length > 0
                      ? 'warning'
                      : 'primary'
                  "
                >
                  mdi-filter
                </v-icon>
              </sup>
            </template>
            <v-list
              :list-props="{ maxWidth: '300px' }"
              elvation-1
              density="compact"
            >
              <v-list-item density="comfortable">
                <v-autocomplete
                  v-model="searchFilters[column.key]"
                  density="comfortable"
                  
                  multiple
                  clearable
                  :items="uniqueFilterColumnValues[column.key]"
                  :label="$t('searchByField', { field: column.title })"
                  color="teal"
                  item-color="teal"
                  :type="
                    column.type == 'number' || column.type == 'text'
                      ? column.type
                      : 'text'
                  "
                  :no-data-text="$t('noDataAvailable')"
                  :search.sync="searchFilterInputs[column.title]"
                  style="min-width: 200px; width: 100%;"
                >
                 <template v-slot:prepend-item> 
                    <v-list-item 
                      @click.stop                                          
                      style="cursor: pointer"> 
                      <div
                      style="display: flex; align-items: center; cursor: pointer;"
                      @click.stop="toggle(column)"
                    >
                      <v-icon small :color="isAllSelected(column) || isIndeterminate(column) ?'teal':''">
                        {{ isAllSelected(column) ? 'mdi-checkbox-marked' :  isIndeterminate(column)?'mdi-checkbox-intermediate':'mdi-checkbox-blank-outline' }}
                      </v-icon>
                      <span style="margin-left: 4px;">{{ $t('selectAll') }}</span>
                    </div>
                    </v-list-item> 
                  <v-divider></v-divider> 
                  </template>

                  <template v-slot:selection="{ item, index }">
                    <span v-if="index === 0" class="text-grey text-caption">
                      {{ searchFilters[column.key].length }} item(s)
                    </span>
                  </template>
                </v-autocomplete>
              </v-list-item>
            </v-list>
          </v-menu>
        </span>
      </td>
    </template>
    
    <template
      v-for="(_, scopedSlotName) in $slots"
      v-slot:[scopedSlotName]="slotData"
    >
      <slot :name="scopedSlotName" v-bind="slotData" />
    </template>
  </v-data-table>
</template>
`

**Comment by J-Sek** [comment]
If you can provide an example on VPlay, it will be better to ask on [Discord](https://community.vuetifyjs.com/)
