### ISSUE TITLE
[Bug Report][3.3.14] Value requires a double tap

### ISSUE THREAD

**Issue by hgalytoby** [vuetifyjs/vuetify#18635]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When using version 3.3.13, there is no issue with entering values. However, in higher versions, it requires a double input to register a value.

### Expected Behavior
Same as Version 3.3.13, value is obtained with a single input

### Actual Behavior
Value requires a double tap

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU01vEzEQ/SuWLylSdk2UglCUVqGolcoBEHBjOWzWk9TFX7Jnt0FR/juz3gRMWkWR9rLz3pv3Zmz/2PIYGvHe+7Jrgc/4PDZBeWQRsPXXlWVMGe8Csi1rI9y5YNiOrYIzbNQBFF2tlawRRpXtuY2zsadSuYU4ZhJWysK99S3eKCsjaa8OfS5e5RowtdIEHisuRgkZEXkuhmyUin4QjNfknDLOuwJhg8VKgZasK5Ykvap4klac6XoJmv7vVCArWxuo+PVc5CJqMxdZTz7mGCnaSq3Lx+gsrWbbO1W8ccYrDeGzR0XRKz5jCemxWmv39DHVMLQwPtSbB2h+vVB/jJu+VvEvASKEjnL9xbAOa8ABvv32iZJmoHGy1cQ+AX6F6HTbZxxoN62VFDvjpbT36XiVXX+PtxsEGw9D9UF75i7xK07348OJ0f/FnZbTpKssfbTH4QIVpvZHmxyA/9uQyxD3AdHHmRCNtCSToFUXSgsorDdiQTQRWovKQCGdWZBneSmkipiXS4imWAb3RLulJtnopEe1+n2G1Z6ZHCbTwWJfK+hexd7jWW+RDjMUAayE0C/9vJGOZPlYR9CJ0bJnec58GX1xWU4m5bv9kBnwfMgUV0KHzulY1F6dO2KuWbwt35SvhVZLQQaCHi1skk12f3ZjnrZAF2k4Av7zD+I3lr8=)

**Comment by KaelWD** [comment]
#15904 probably changed the order of some events. If it ever worked it was not intentional, components should use `modelValue`/`onUpdate:modelValue` not `value`/`onInput`
