### ISSUE TITLE
[Bug Report][3.3.23] card-border-color sass variable override does not work for outline card

### ISSUE THREAD

**Issue by yuridesnaijer** [vuetifyjs/vuetify#18630]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
clone repository, install packages and run the project. 

### Expected Behavior
The border of the card should be red as settings.scss contains the following override:
```$card-border-color: rgb(255,0,0),```

### Actual Behavior
The border takes the currentcolor which is rgba(0, 0, 0, 0.87)

### Reproduction Link
[https://github.com/yuridesnaijer/vuetify-border](https://github.com/yuridesnaijer/vuetify-border)

**Comment by Tauromachian** [comment]
Any chance to reopen this? I could get it done
