### ISSUE TITLE
[Bug Report][3.4.0] v-otp-input wrong type on Mobile

### ISSUE THREAD

**Issue by loihp** [vuetifyjs/vuetify#18647]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.0.0-alpha.0
**Browsers:** Chrome 119.0.0.0
**OS:** iOS, Android

### Steps to reproduce
When i use v-otp-input, user type otp now keyboard showing on mobile is text althought i set number

### Expected Behavior
show number keyboard
![Screenshot 2023-11-10 at 17 11 55](https://github.com/vuetifyjs/vuetify/assets/67997721/07051623-f598-4b8b-bd9c-820bcd4f5aff)

### Actual  Behavior
show text keyboard
![Screenshot 2023-11-10 at 17 02 15](https://github.com/vuetifyjs/vuetify/assets/67997721/3111bcb1-99b7-482b-845a-8d55e6d53ab6)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUctOxDAM/BWTS0EiLQIOCHVX4sYfcKAcsqkLQXkpcSpWq/133JZHd0+JZ+yxPX49iJx08xRjPRYUj6IldNEqwm3nAdpRqhjn7xzo4EkZj+kHYrA3I2irct50QocepfGxUIZeDha/4LNkMsNeavSECdxO3nbir3oWzR+IBDrYkFgjlzQojSdJc1qguGivcYAh6JKxPwVH6XgUy3Jc1YkzUiWjPE29uOc5S/uITPnidpjOybmZVNau4W3brKZb78b4vNy/Ww3b9Wsns6d+Tshid9uszsBh1slEgoxUlmsYF0MiOEDCAY4wpOCg4gtWUzqwmT4TuPwOmynjsnpGawO8hGT7i+pqarBIspg4Xou7+q5+ENN7X9+It28OEqAl)

**Comment by jacekkarczmarczyk** [comment]
Check `inputmode` attribute on the input

**Comment by KaelWD** [comment]
It has `inputmode="numeric"` in the repro link and shows a numeric keyboard in both iOS 15 and Android 13

**Comment by loihp** [comment]
Oh, tks everyone! i think its should show number keyboard when type is number... anyway just contribute ideas!  <3

**Comment by KaelWD** [comment]
It does.
