### ISSUE TITLE
[Bug Report][3.4.0] Luxon date adapter doesn't work anymore with 3.4

### ISSUE THREAD

**Issue by mullerch** [vuetifyjs/vuetify#18642]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Ubuntu undefined

### Steps to reproduce
Open Vuetify playground linked, open the year selector (arrow next to the selected month/year).
OR
Create a project with the Luxon adapter, try to build.

### Expected Behavior
No error

### Actual Behavior
Playground error : `adapter.getNextYear is not a function`

Build error :
```
 error TS2322: Type 'LuxonUtils' is not assignable to type '(new (options: { locale: any; formats?: any; }) => DateInstance<any>) | DateInstance<any> | undefined'.
  Property 'getNextYear' is missing in type 'LuxonUtils' but required in type 'DateInstance<any>'.

20     adapter: new LuxonAdapter(),
       ~~~~~~~

  node_modules/vuetify/lib/index.d.mts:210:5
    210     getNextYear(date: T): T;
            ~~~~~~~~~~~~~~~~~~~~~~~~
    'getNextYear' is declared here.

```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVMGO0zAQ/RXLl7aiiVmKBKqyVRfYAwgBgooL4ZBNpq13E9uynbSo6r8zttNsUthVb87Mm3lv3kz760CNzllTg+XrP/G9oXPKKyW1JQeSa8gs/Aw5ciRrLSsyarGjVKSihX6u91LcFJmyoFvUssDSiEtWupwHw96DcymMJW0Xcj1kGR9SQYjdQgVzVFDAOqtLuwrfo5JvtnZEjlMHcgSIcU9CskA+JwJ2AznjiQe7kuMkFXTq571RKkYFOGxioVIltlo4WNJEmVL+6T9Qq824AN2GMLi9WnxAeMLw0QWbyI+reP6ADjRRJQsor1PqoildJGwAOPXH6JDARQJ/wnq68NPkmitLDNg6yOuWpGHdX413upd2Wle8gg7zuA/SrsIpwz1go/EJHQu5G0/Qr4QFZuRE66zBijXf4J1IgeZ581Oay0rxEvRXZTl2TGm3lpRmZSl3n3zM6hr8MnzNFvKH/8Tvzd7FUvpNgwHdoH1dzmZ6Azakb398gT2+uyRaXpeIfib5HYwsa6cxwN7VokDZPZxX+9F7x8VmZW73FoQ5DeWEno7JodHu98+M/ih3Fs98Hd6g9zFsJ6oydeZkSAzbIEuQu7VWmTljeSGwDA+MNzoWYJlQFVsijOlaWNxeVMhqiZzxW1ZwY/vhGEwV3Wm5Q2+xSW/09gd5AVWLRIbX8cvA0IaiMrszjuKf1szvUkcaRAHaeX7ZRGdl/anOUk9P5i/+AkKP81PN2Avs1mvR/ZvlUl+0jT5++Sq+eoNOPdXzUn3DgmHX3nkdp9S7hHfmN0R//wVhGPhs)

### Other comments
To me, it looks like the component now uses a function that is not part of date-io, or not implemented by Luxon adapter.

**Comment by UkonnRa** [comment]
+1, `@date-io` adapters do not work anymore...

**Comment by throrin19** [comment]
+1 same with `@date-io/dayjs`
