### ISSUE TITLE
[Bug Report][3.3.23] Rounded xs doesn't work with icon buttons

### ISSUE THREAD

**Issue by hakimov-dev** [vuetifyjs/vuetify#18656]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Yandex 23.9.4.837
**OS:** Windows 10

### Steps to reproduce
Add button then i've added icon then i added `rounded="xs"` but it doesn't work ?

### Expected Behavior
I want to use rounded=xs

### Actual Behavior
rounded xs doesn't work in button 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj81OwzAQhF9l2UtAoglSOSCUVuLGG3AgHIyzBQv/ab2JKlV9d9YJSO3J/kajmdn3Exa23UvO7TwRPmMvFLI3QvshAvTzxuS8fBewKYpxkfhPWsRPiTAbdibKbkChowwITq1KYXQb+032RyVOUxxpVPVYFK03pSgMuIe+W2L+i5Sum6qyDum7i4GKxbLLAoVkWne6kBMLnIDpAGc4cArQ6G1NtQNobhEI5Qt21XHbvJL3Cd4S+/GmuasFa6SG4fket+22fcL6PrYP+PELr6xiwA==)

**Comment by KaelWD** [comment]
There is no xs: https://github.com/vuetifyjs/vuetify/blob/21fbd137bee0dcec2b98fd667db687ea88863cd7/packages/vuetify/src/styles/settings/_variables.scss#L62-L73
