### ISSUE TITLE
[Feature Request] style or add class to (data-table row) based on a condition

### ISSUE THREAD

**Issue by ahmedabdelhafizoo** [vuetifyjs/vuetify#18662]
### Problem to solve
What problem does this feature solve? it will improve the UX for example i want to style the un-selectable row by highlighting it or adding some style to it. it will be more clear for the users.

### Proposed solution
maybe by adding a dynamic class yo can make it like (item-selectable) prop
```
:item-selectable="(item) => !item.is_deleted"
:item-class="(item) => item.is_deleted ? 'class-name-1' : 'class-name-2'"
```

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-data-table/#props-cell-props
https://vuetifyjs.com/en/api/v-data-table/#props-row-props
https://vuetifyjs.com/en/components/data-tables/basics/#customisation
