### ISSUE TITLE
[Bug Report][3.3.23] VDataTable v-slot:item[FIELD] fails due to call to {raw}

### ISSUE THREAD

**Issue by geraudmathe** [vuetifyjs/vuetify#18661]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
It seems that there is still a call to `item.raw` in https://github.com/vuetifyjs/vuetify/blob/3f57ee09948d4f9e949bee95f6c31bb5cbd57f8d/packages/vuetify/src/components/VDataTable/VDataTableRow.tsx#L60 which makes the prop `item` unavailable in later calls

### Expected Behavior
calling `item` in the slotProps from `v-data-table-row` should return an object instead of being empty

### Actual Behavior
calling `item` in the slotProps from `v-data-table-row` returns `undefined`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1kT1vwjAQhv/KyQtL4lSiQ4WgEkOrVurWERguyVVYCo5lmxQpyn/vOSYFg5hsv/e85/vY9MLZqlgbI7sjiYVYejqYBj29bjXAssvRmPE6PqpWe1Sa7FkaxRo95h7LhmCh2O5WWzGeW/GPMTglhi53TetHlMkewiUDpWs6DYnlJntu2182l0ze+iAY4dr54EOp8UCJ25PV2Hze5EpT9RGHYeDrtYWFMRh9Q1J6kUzyIt+1xPGrMd3bUsu0DBbTbQQlLivJwU9XWWU8OPLHuEs2Oj+25GAFm5ixn/4LI1rAbP1jVYUa3hoye9R+lk2AM1Qpcsx8tae2DlUARhovVK3IM/JBtlRda+kS2WOpPIbgN3aoNWbwzoDzbmKG81kUIKWEA0djuUHehQ5jT9yNGDIxl3P5IsL5LJ/E7g+bPOBp)

**Comment by KaelWD** [comment]
v-data-table-row is supposed to take `internalItem`

**Comment by KaelWD** [comment]
8030d407 will show a type error there. This isn't a bug, use `:item="internalItem"`
