### ISSUE TITLE
[Bug Report][3.4.0] <v-date-picker> does not take up full width

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#18674]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce

Simply access the link

### Expected Behavior
That the component adapts to the width automatically

### Actual Behavior
Does not fit width

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UEFOAzEM/ErkM9msVJAQCkh8AHFnOZjEVSN2g5WEsAjxd9zQVu2qPSUe2zOeefmBnJx5ZO7qJ8Ed2EITj1joYYhK2aqRuX1b4TB5NeGsv4Ivm/sBbvp+gF3/aEYXmssp7IVTc3DvlJQ5bvlQlRsxZ6Hzej3SfMLYlt9KVBVTwFhkai33DaA4EVP0OriPKOjkgxZk/JZ19ZyoKmva5pIsM7rFEZdFxP5CI28w0VbjSTye0bBGHO0jk+4yjz0mZYtYyv+MrTlkD79XsOpW3S1s3+uuh9c/7HV+1w==)

**Comment by johnleider** [comment]
There was a bug with passing width but you will still need to declare it manually:

https://play.vuetifyjs.com/#eNp1UctOAzEM/JXIEjeyCSpICAUkfgBxZzmExFUjdoOVhLCo6r/X3b5Wq/aUeGzP2OOPNeTk1CtRU38RnsAU7KmzBV/aKISp0hKN3zFwNnnR20H+BV9Wzy08aN3CIX+qkAWHcgJH2DOjpOC+MYlj753WNy0INa30oQrX2Zw57+Wyw2FCf+D6KlFUm4KNhauWPCyzUELC6GVwP5HR3gfJSPfP7eI9YRVGjZ1zskzW8UzTIa6LsBczjbyyCXcab7zyBQ2jeKOzP5yfG3TE9n5zsDfcqMkhYHMLi2bRPMLuvW80fG4BlgmDBg==

**Comment by alanscordoba** [comment]
Ok, so it will be corrected?

**Comment by johnleider** [comment]
> Ok, so it will be corrected?

Nope, going to leave it broken forever. 😉
