### ISSUE TITLE
[Bug Report][3.4.0-beta.1] VDataTable too many nested headers breaks design

### ISSUE THREAD

**Issue by dcrystalj** [vuetifyjs/vuetify#18679]
### Environment
**Vuetify Version:** 3.4.0-beta.1
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
* have some columns with children
* make many columns until table headers breaks into new line

### Expected Behavior
table should be wide as much as I need

### Actual Behavior
table becomes impossible to use

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtlt1q2zAUx1/l4JtskDiyndhJSAtLWjrYBmOD3TS5UO3TWMxf2HJYVgp7hz3K3mCPsieZ5I9aSV2a9LL4Svb/nCP9/rLF0fWdlqXu8F2S6NsctZk25xgmAeV4vooA5tuBRzkdcHoToBQAZj5SD9PsbKVVTyutijBRK/VirFX5MviOO6FHNERVzgYJpoOEblAEx2XkfD5U1xQU86GCJF4zN2UJhwx5nhSQbhxlHCoYOIPrcoU74IwHOIPe511KQ+b1+rClQS4VSdKD+/5h5sfYpZzFkZIa1FJL+lKunOaujMOFIFTqCqoqVoSa+nKAh2kuWIhRJvKyXpUCQAO2ieQ0GHFMG931WeClKEKVzX2i98g2Poc34VsFxS/EBmC/ZEEzPCi4EdJT6d/iIA9lwd8/asm2kNWidfXU2e5sd7Y7253t12F7Lbtw3XWLNq703LpENlgx11WKlEPVfyG+hSv2kzZbUPdWkXm52SW8iZRGhW6MbN1udOlHqKZF9FGjlshSH08sczJWNvmgC8vvoINII/9+/TbHNoHFss5+9FUrEwr+B5/epqLLn2LAslXU2oAx1q0WA8bIcUbHGHCOIf+CXr35pzGTFmKTtPHaxJxMj+CdHsO7EEfkhcCGbjxCNiYT9d9poE1C7Kli5wlom5z4e3Af4Wsubo8t6J/wB3PjFnZb2b2HvVY0BdtyyNR5FltQLy/3qcWZnQ/Li7O4Mmv3fc3SLd3R5DjSibb+D+93dXc=)

**Comment by websitevirtuoso** [comment]
Does it possible in the same issue to fix problem with wrapping text
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/9314ad2f-5c66-430e-9419-09497c7e81bc)

```
<template #[`item.first_name`]="{ item }">
          <div class="flex items-center gap-x-2 whitespace-nowrap">
            <m-avatar
              :initials="`${item.first_name.substring(0, 1)}${item.last_name.substring(0, 1)}`"
              :src="item.avatar?.original_url"
              size="36"
            />
            {{ item.first_name }} {{ item.last_name }}
          </div>
        </template>
```
I have this template for the user, but as you can see it can't calculate the width for the whole col properly. I know that I can set "width" but this is not very flexible.

**Comment by KaelWD** [comment]
Not related, and we don't actually calculate column widths so it's a browser thing.

**Comment by dcrystalj** [comment]
@johnleider sorry but it doesn't look like this is fixed https://play.vuetifyjs.com/#eNrtlktu2zAQhq8y0MYtYMt62JJsKAFqJ0iBtkDRAt3EXjDSxCKqFyTKqBsE6B16lN6gR+lJSuoR0Y6C2FkGWlH6Z4b8fkrE8PpOyTNv/C5N1W2BylxxGUZpSBier2IAdzvyCSMjRm5CFALAPEDiY5afrZT6aaXUEcprhV6OjSpeRt9xx/WYRCjL+SjFbJSSDfLgtIqcu2N5TU7hjiUk/pp7GU0Z5MiKtIT0kjhnUMPAGVxXK9wBoyzEOQw+7zISUX8whC0JC6EIkgHcDw8zPyYeYTSJpdSwkTrSl2LlrPBEHC44oVRXUtWxMtTWVwM8THNBI4xznpcP6hQAEtJNLKbBmGHW6l5AQz9DHqpt7hO9R7oJGLyJ3kooQSm2APslC5LjQcENl55K/5aERSQK/v6RS7alLBet66fedm+7t93b7m2/Dttr0YWbrlu2cannNiWiwfK5rjIkDOr+C8ktXNGfpN2CprfyzMvNLmVtpDLKdX1iqVarCz9cNUxNnbRqhSz0qWMazlTa5IMuLL6DCjxN+/frtzG1NFgsm+xHX7U2IeF/CMhtxrv8KQZMS0ZtDOhT1ewwoE9se3KMAfsY8i/oN5t/GrPWQWxoXbyWZjizI3hnx/Au+BF5IbCu6o+QdceR/50W2tA0aybZeQLa0k78PViA8LXgt8cO9E/4g3pJB7sl7d7DXkuahG3a2sx+FptTLy/3qfmZdcfVxZlfmZX7oWKqpuooYpyohrL+D++IdXo=
