### ISSUE TITLE
[Bug Report][3.4.0] I couldn't copy content or create a copy button to copy content of the v-tooltip's content.

### ISSUE THREAD

**Issue by chinese-small-cabbage** [vuetifyjs/vuetify#18677]
### Environment
**Vuetify Version:** 3.4.0
**Last working version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Use v-tooltips with close-delay
2. Hover and copy the content,  but I can't select the words in tooltips.
3. Try to use a button but it is not interactive.

### Expected Behavior
I can copy content in tool tips or I can use a interactive button to meet my needs.

### Actual Behavior
No way to copy the content in v-tooltips.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNU8FSwjAQ/ZU1l8KMtHXw4DDA6E3uzniwHkIbMJommWRbYTr8u9sUkCJ69pRk83bz3r7NS8O8y5MHa+O6EmzCpihKqziKeaYBpvWIWxu24ZAbjVxq4fYhChayPh4CBo1RKC2g2OAsYwt4rzzCJ9cIaCA3dgv4JmijUWjMGOTKeDEqhOJbwo/TNM3YSUkqeuAE9cgrgxOeo6w5Gkf4Bqwz1sPuLClwWaKmnKXUBSEDjlBPHcFpEu77LyU9+YfgUdS37KTTfdoG8LhVgh4quVtLTTl2Ajep3fSYnXTovwv/4W4Iecv1fPGrodMkAC4yus+VzD+IUZtEhNrlMpuzqfrDgcN9fzTbSDe5PWV09LmTFsELrLpisrTGITTgxAp2sHKmhIg+Q9S5S3VpfEu/hlmLGESPQikDz8ap4ioadqBVpckZo0M3BkNoOl5trlEiVmY9iEKj9k1q84CcI3YdH2LCdtdsHI/jO9aut3HKXr8A6X0bMw==)

### Other comments
Hope you can help me soon. Thanks.

**Comment by websitevirtuoso** [comment]
tooltips is component to display message not to interact with it.
I think in your case you can use component
menu + prop "open-on-hover" and there implement button to copy paste to clipboard.

I don't think that this issue as issue

**Comment by KaelWD** [comment]
#9717

**Comment by chinese-small-cabbage** [comment]
Thanks for your reply and suggestion!
