### ISSUE TITLE
[Bug Report][3.3.7] missing functions in the prototype ($ref)  

### ISSUE THREAD

**Issue by CristiP19** [vuetifyjs/vuetify#18673]
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a v-slide-group with options
2. add 2 separate buttons
3. add a @click event on these buttons
4. event = $ref.slideGroup.next() / $ref.slideGroup.prev()

### Expected Behavior
in the API it says it should work but it doesn't work and shows error

### Actual Behavior
Error: runtime-core.esm-bundler.js:221 Uncaught TypeError: _ctx.$refs.slideGroup.prev is not a function

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU8FuwjAM/RUr2mGTljIGmibUoe204z5g3SG0KWSkaZSEDoT49zkB1gTQDvTS+Pk5fnbszy2xphy8aZ11K04mJHe80ZI5Pi0UQN5RpnU4BqNslWNCcXOAAmjanz/zwJK9DVBKZu1LQSpaS76G75V1ot5Q65hxvdVQrirQM/pUkCS6lT54+JjCtkFwHGORhqBi5lSM9DqYQcXeTSWvHTSGJvf4T2ChyGwqQcsF70y7557SOmYEUw6Zjq/PvK+lFOUSnTeG1zazUlT83bQrnWnDu9u7lD+4Qr8R88VZ2gvaL/KuFa+Q/Z/4fBAmoJ8QtPcjEs1MuI/O/YWACTBPn6EgYBdYYajTpqMVxVGBowodrVuD4QqEguEDxk6WfOMBPB471jD/xGmDrWZqCh/aiVZZ2G5BwW6HYgOeVnOaNCktch73JDQgXhSP7PcoH0T7RXb3ZJSNsmfi/+PsgXz9AmoLBkw=)

**Comment by KaelWD** [comment]
> in the API it says it should work

No it doesn't

**Comment by CristiP19** [comment]
> > in the API it says it should work
> 
> No it doesn't

![image](https://github.com/vuetifyjs/vuetify/assets/90213678/14b26eba-829f-41ed-b508-9ab48e2e6c10)

**Comment by KaelWD** [comment]
That's `<template #default="{ prev, next }">`

**Comment by CristiP19** [comment]
> That's `<template #default="{ prev, next }">`

Ok, man. But how can i do that i need?

**Comment by CristiP19** [comment]
@KaelWD can you help please?

**Comment by CristiP19** [comment]
Ok, i use your example but how can i iterate the items i need @KaelWD
