### ISSUE TITLE
[Bug Report][3.4.0] styles in a v-html htmlString are being applied to the whole document

### ISSUE THREAD

**Issue by Ben-Avrahami** [vuetifyjs/vuetify#18680]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Edge 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
press open dialog, the <p>test</p> will change to red

### Expected Behavior
htmlString style should not be applied outside the v-html div, only to the elements that are in the htmlString.

### Actual Behavior
as you can see in the playground, the test <p> changes to red

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9VE1v2zAM/SuELr0sdoZuwJC5xorsOGDA0J3qHmRbbYTKkiAxboMg/72UbKfxR3uy9MRHPj7Ruj8y76r01tqk3Qu2YRmKxiqOIi80QNauuLVxGTeV0cilFq6HIlhLrswTvMgadzcF+75eF+x8ThFDRmhXXhnc8Aply9E4Cj6CdcZ6OI0oMW2Jmhil1DXFxaiCAYpXpO1fKzT8jnWJCFkaw8cZbI7CY5YO8iOYXrT3icRaPPK9CpWOIP1tECyWNFbc1SMsomiMKrmDyqjYpHWy4e5A8mvungElKkFwkCf1E4RwlHaS/cIFSbbPzs6ViAqXllruhEYqpkzFURpNWGkQTVOweRKAfGvsAf7/+wN3BrZK2tJQV8HSQdiMtCwmymxqGaeEJNDXHkKeRf1Ld9ahvX3Tk1q20xztaoeNov6usrCgQfB4UCK3cOzM3zhR/zxlaQdDtvua3/WuJ0mSpbSnkpF7NXUnz1IqOZqTi1tfBcuN9kt35i2v6BcJvfTLaZLhauc+9gO+VcaL84TPw35VSlbPFDhMZ9JytRdwA49ceTGnRDXLfn/YznD40Q/0HtU9AcM7EWijhyIg3Tsy4rPTF3adXCc/WPh+S9bs4Q3XOUoH)

**Comment by KaelWD** [comment]
Not a bug, and not related to vuetify.
