### ISSUE TITLE
[Bug Report][3.3.23] How can i change v-select arrow icon ?

### ISSUE THREAD

**Issue by hakimov-dev** [vuetifyjs/vuetify#18681]
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Yandex 23.9.4.837
**OS:** Windows 10

### Steps to reproduce
Install vuetify add v-select

### Expected Behavior
I just want to know how to change the arrow icon.

### Actual Behavior
I just want to know how to change the arrow icon.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkEFrwzAMhf+K5os36JJBdxglLYzCtvsGPbQ9eIkSDI5lZCdslP732fFC25OfPoln6e1PwnNdvjpXjAOKlagC9s6ogJuDBajGR+XcJKeiJhuUtsj/aIIeDdZhBgBGfaNZH8Rn5uLSWeno7mNrL7fK6JbYaiUXILdkiFVDSb9FqZsJvyNxlye+8Ef5JHa/1GvbyeO18ahYKxuiMw3BxAWbS3dTlfOO8yER3F6SSD60Kq8CiKWvWbsAHsOQc9C9Iw5wAsYWztAy9SBjdjKNA0RfH6D3HazTxL38QGMIdsSmuZMP6YNsGc3EeSGWxbJ4Eel9Lp7E8Q/Ppn1D)

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com), [Stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js), or [GitHub discussions](https://github.com/vuetifyjs/vuetify/discussions).
