### ISSUE TITLE
[Bug Report][3.4.1] css of ul and li elements

### ISSUE THREAD

**Issue by cropr** [vuetifyjs/vuetify#18684]
### Environment
**Vuetify Version:** 3.4.1
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Mac OS 10.15

### Steps to reproduce
create a VContainer  (or any vuetify component) with  `<ul><li> ` elements

### Expected Behavior
the bullet of the `<li>` element is slightly indented in the container

### Actual Behavior
The bullet is placed outside the container

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplj8EKwjAQRH9lzaUK2lDrQSQWvOlZwYN6KHWrhaQJSVqE0n83aasUPWXmsZmdvTTE6IzulArrCsmGMItC8dRici0BWL1IlepkZzJZ2rQoUX/QM0qOUiCc8GUZdW7gFR+U07xI4OBiIWLU6X++HHFGv18Z/V3oSd+H0VFPZ02mC2XBoK36uoVQUltoQGMOLeRaCgjciYEfB3C5xoIwD9j6iWmwR84lnKXm90kw8wv6SBdG2jmJwzhcE/+uwojc3o2WYCg=)

**Comment by websitevirtuoso** [comment]
I think we have missing reset css rule for ul,ol
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/a855b995-f6ae-4896-a64b-e7d9952e2baa)

But I can't really say if this is issue
