### ISSUE TITLE
v-icon cannot resolve .styl file associated

### ISSUE THREAD

**Issue by mkhanal** [vuetifyjs/vuetify#1868]
### Versions
    "vue": "^2.3.3",
    "vuetify": "0.15.7"
    nodejs : v8.4.0

### What is expected ?
v-icon should display as expected. I think styles should be resolved in the vuetify package during installation. The app should not be expected to compile resources for vuetify. I should not need to use a 'stylus' loader if I don't use '.styl' files in my app.

### What is actually happening ?
Error on console when webpack compiles the project. This only happens with v-icons. If I don't use them, everything works fine.

These dependencies were not found:

* vuetify/dist/vuetify.min.css in ./src/main.js
* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../../vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6406ec7f","scoped":false,"hasInlineConfig":false}!stylus-loader?{"sourceMap":false}!../../stylus/components/_icons.styl in ./~/vuetify/src/components/VIcon/VIcon.vue

To install them, you can run: npm install --save vuetify/dist/vuetify.min.css !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../../vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6406ec7f","scoped":false,"hasInlineConfig":false}!stylus-loader?{"sourceMap":false}!../../stylus/components/_icons.styl

### Reproduction Link

Just install vuetify 0.15.7 with webpack  and use v-icon

**Comment by mkhanal** [comment]
I've resolved it. This happened because I imported v-icon after I had included vuetify in the global context (i.e. not in al-a-carte mode)

**Comment by KaelWD** [comment]
- Are you using one of Vuetify's vue-cli templates?
 - Are you importing VIcon separately anywhere?

**Comment by KaelWD** [comment]
That timing though

**Comment by mkhanal** [comment]
I don't use vuetify's vue-cli...i prefer a different PWA template
