### ISSUE TITLE
[Bug Report][3.4.0-alpha.1] I can't add change event handler in v-checkbox

### ISSUE THREAD

**Issue by hakimov-dev** [vuetifyjs/vuetify#18698]
### Environment
**Vuetify Version:** 3.4.0-alpha.1
**Vue Version:** 3.3.8
**Browsers:** Yandex 23.9.4.837
**OS:** Windows 10

### Steps to reproduce
Added v-checkbox and i added `@change` event handler.

### Expected Behavior
When i added the `@change` event handler checkbox works fine 

### Actual Behavior
When i added the `@change` event handler checkbox not working fine

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNpVUH9rwjAQ/SpHNqiCtgw3GKXK9hm2/6xgTa8aTJOSxDIo/e7LNa1VArncy7sf7+07Zg1Pvpsmbm/IUpY5rBtZONzlCiBr10XTDM8h4Vq5Qig0I+TBUrTQritttjlzutQgFFC0ObuTQu0F+fWk/2YQgGs5FL5sPujk7PGzXde6RDn2jUut8JnwxS+FOqMn+FhK/PW0Z0Yqi9PQ4fjaDU3o6lMYM2rZHx9LdlkybzqLTLzKyQUiPNlASHApSx7c86nlRjQOLLpbMFHUjTYOOjBYQQ+V0TVE3viI6GSHsi64B1vYh4HdtAXhKUQ/ukZ3EeoMdnpFq4lDilKoCmlxxPohHsKA6qa4E1rBbNhiOU2g6VpiLPV5EXEp+BXLaEl/PUkLYrwM1q/YJt7En4zie/zGDv+NH7ND)

**Comment by KaelWD** [comment]
`@update:modelValue`
