### ISSUE TITLE
menus misaligned in toolbar (inline-flex deleted from .menu__activator)

### ISSUE THREAD

**Issue by miquels** [vuetifyjs/vuetify#187]
If you havea toolbar with  v-btn's and a v-menu with a v-btn , they are misaligned.

This seemed to be caused by commit https://github.com/vuetifyjs/vuetify/commit/9744bc2c71dd191b96cb4088152e7c44763f3a2f , where in _menus.style "display: inline-flex" was commented out (and in a later commit, deleted).

Adding it back solves the problem.

Example at http://codepen.io/miquels/pen/zZZqvY?editors=1101.

**Comment by johnleider** [comment]
This was in relation to the height declaration.
