### ISSUE TITLE
[Bug Report][3.4.2] DateAdapter format function has wrong type

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18709]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
1. Try to use `useDate().format(new Date(), 'd MMM yy HH:mm')`
2. See that there is no Typescript error

### Expected Behavior
The type should be specific and only allow `keyof DateIOFormats`

### Actual Behavior
Typescript doesn't throw an error, because any string is valid

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVd9P2zAQ/lesvDTV2phf0qaoQwUGgk2MaVR7WfYQkksbSGzLdkqrqv/7znYS0lJQt6cmd9993+e7c/N75SmZ0HkFOs+WwaPyQi8vBZearEgiIdbwy+XImmSSl6RXY3sRa4GsaLMpVgwzpmjBk7iAF9QXTFwxdZbGQoOs0WMLzzltyhAfMVjYioQzpUktRz5v2vFXESNEz6CEEB2kkMVVoSfuvVfk05nukfXAgAw3YswjIbHTDwmD5y1P/oo405jEA/VtsaFY9yPmDWyjzoQI0BF2aaShFAUSnBrYaD6MhbCP9gW96zhnIOsQBmeHp0ZvRPGhDYrT1cr4W69HtC2n2/Um4uhHtCOLryqRudBEga5ceTsTCVl3ZNjYTrJSYLzsmKmBucYbW9h15PFruN8PMi7LWPtN8/z+gPSyqijMyyQv4ehk1utjuwihtMNz9AbR+fJey5xNNwlTcnt7S5ZLcn0dlqXlqxkvKimBaaKXAsI65piI78Y8GdQBRxwSZX/7zcNGUSOPA+fYxEqY9kD6IsdRLnFyalPPn8dFZfSM60bzGyxD8gRLntnD3Nxd2bB6X30n1Zv2R9TNHKeNO6kVNjnLp3hzOcOttFseeQkvRV6AvBM6xyFEXrv/kRcXBX/+amNaVmC33NbMIHnaEX9UCxOLvB8SFMg5RF6b07Gcgnbpy/vvsMDnNlnytCoQ/U7yJyheVMajg51XLEXbHZx1e2P3Fo8/UZcLDUw1hzJGm1tq0LjHF+8c/cXucXBs6/By2z66mzEsY7HVSZfYpEEVZ3emtVAhpUnKsCyFIp/LgIGmTJR0jDAqK6bxWgxTXo5RM/hE01zpbjgAVQ4fJH/G3iJJ5+j1pdxDqkaiwklw5BTq0LCIH5SReEVN7SzlEO9TCtL0fL8TbZV1T7WVevtkzb/9HpoNdHwUHB8EB/QDku5gqj83/0HoCrd52w9TwuVew+7ikfrw42uvrz52/8Lbsd3h7uzweuDZUeAy2zXw/vwFdZKhGg==)

**Comment by KaelWD** [comment]
This is also pretty much the same problem as #18710, it accepts `string` because you can define custom formats.
