### ISSUE TITLE
[Bug Report][3.4.2] VDatePicker with Dayjs and show-week: TypeError: date.year is not a function

### ISSUE THREAD

**Issue by dbt-unruh** [vuetifyjs/vuetify#18707]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use date-io DayJsAdapter and add the show-week prop to the v-date-picker

### Expected Behavior
DatePicker renders, week gets displayed correctly

### Actual Behavior
Date picker does not render, JS console error occurs

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVMtu2zAQ/BWCFydoJNZJgRaGUzhtc2gObdEGvYQ5MNLapi0+QFJ+wPC/d0XKjuW2gYEABiztzs7sDCU9bKh3BVvUEOR4nc88HVCprHGBbEjhQAT4nXpkS8bOKNJrsT2uW+AXsb7zN6WwAVyLGZU4mEnDSrGeeYRyDasILoz2gbQc5LqrcbbhmpAwBQUDEq8JKWEs6ircp2KvkpNp6F2kHmPN/zbeNYr7IZG2GXR2i7AGvD3nml5E4zfW5rgMuh4GULZCko8NbLjIhLXxMt7g2kFIDa4txWI0aWUxR98DJfU1p9Hv2TmnxE/NMlsCzAnb0bBjnqaSZIbsQB5vfeGkDcRDqNMWbdaRvw15l+2QJTTi0FXwqDGWEzxLo9FXTITTwigrK3DfbZB4BJzus+JUVJVZ3sVacDW04eLMFIr5P+ozv2pqnP5w4MEtgNN9Lwg3gZDat7++wQqv901lyrpC9AvNn+BNVTc7JtinWpe49gEubvs1xiH15N7frgJovzPVLPr8UHCKh/v5BevP617lV3EOH4+YYwo8U8IeJZkaXRpUSetOQ7B+wFhRahwroZILl2sITFvFRghjrtZBKshKo0aomX9gpfThsJyDV9mTM0vMFkkOrLevzQlSLRIV3uWXSaEtZZV48o3EX9QsnqXLHOgSXJP5aY6Oxg5dHbX+76z7wThFuTMwusz77/O37A0KHLCeSpY4+nkffzuSzsNQST33x2+Uj9QPrzyJSPOYhLYXNIaHihFOH/8AHanhog==)

**Comment by KarlNilsson** [comment]
@KaelWD I have a PR that fixes this issue
https://github.com/vuetifyjs/vuetify/pull/18649
