### ISSUE TITLE
[Bug Report][3.4.2] VDatePicker opens in current month even when min-date is in the future

### ISSUE THREAD

**Issue by MelvinFrohike** [vuetifyjs/vuetify#18705]
### Environment
**Vuetify Version:** 3.4.2
**Last working version:** 2.7.1
**Vue Version:** 3.3.8
**Browsers:** Safari 17.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
As the playground link shows, opening a VDatePicker without a modelValue but a min-date that is in a future month, the current month is shown where nothing is selectable. 
In Vuetify 2, it used to open in the month of the first selectable date.
I think the previous behavior was better as the user is not required to first move to the first selectable date.

### Expected Behavior
Opens the picker in the month of the min date

### Actual Behavior
Opens the picker in the current month

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj80KgzAQhF9l2Yst1MSqh1K00OeoPUiMEJo/kuhFfPcm2kIpBLIzDN/OPhb0jtG7tWSeOF6xCVxZ2Qd+6zRAM+e9tdu4CWZ06IXm7mNt5hDTuRXsxR3MuTIDl22Hye0QlNBRlEVZ58U5vmjRL4/+A5Oz72voT48oPXPCBvA8THsdoaxxARZwfIQVRmcUZPGELMUBItcHSB2gTZGDnqQ8Ju5OigxcT1iRilww/TUp8fkG0y1V+w==)

### Other comments
Ideally, I would like a prop that defines a month to open the picker in. If a date is already set, it should of course open at that date

**Comment by ae-meddeb** [comment]
You can do it like this
[[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj80KgzAQhF9l2Yst1MSqh1K00OeoPUiMEJo/kuhFfPcm2kIpBLIzDN/OPhb0jtG7tWSeOF6xCVxZ2Qd+6zRAM+e9tdu4CWZ06IXm7mNt5hDTuRXsxR3MuTIDl22Hye0QlNBRlEVZ58U5vmjRL4/+A5Oz72voT48oPXPCBvA8THsdoaxxARZwfIQVRmcUZPGELMUBItcHSB2gTZGDnqQ8Ju5OigxcT1iRilww/TUp8fkG0y1V+w==)](https://play.vuetifyjs.com/#eNqNkE1ugzAQha8y9QaQiklJFhUirSpV3fUAVekCkUmLio1lDFUV5e6Z4SeBrCIh7Jn35rOfPw+isUX0YozsWhSJSB0qU+UOnzINkHZhbky/7Yui1i4vNdqx1Td35A5NWfyinboAXajqHVbbTLCciYuSKIL8kDCMvHO10P8xt2f5g4rldKlJpP/rghtNl4yub8mdIUQazcJR2RS2NA4adO2QsVSmtg4OYHEPR9jbWoFH7+KxHYC4jYPxaNiCF6/iTbh6oI8ck855SSSEr9uqCi7KLDAZ7tgou7xqEZ5B4x8w1h/xgfxG11v9ABJg0jWIn+Y2zhtNs3uGSqMhPeUWx3uxlmv5KHjdyFh8nQAuManA)

**Comment by vincentauger** [comment]
Still a problem with 3.4.10. It defaults current date even with min prop set. Work-around suggested by @ae-meddeb does work.
