### ISSUE TITLE
[Bug Report][3.4.2] v-virtual-scroll does NOT virtualize

### ISSUE THREAD

**Issue by LemonGraZ** [vuetifyjs/vuetify#18713]
### Environment
**Vuetify Version:** 3.4.2
**Last working version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Go to the playground link, but this works with any kind of v-virtual-scroll that has enough items, so that some should be virtualized.

Look at the DOM and see, that ALL items of v-virtual-scroll are immediately added as v-virtual-scroll-item to the DOM. So basically there is no virtualization at all, it acts like  not using the v-virtual-scroll component. 

In the example all 9 sections are added as children to the v-virtual-component:
![Screenshot 2023-11-17 144844](https://github.com/vuetifyjs/vuetify/assets/105200595/b3b36a34-bc55-4df4-83d5-3ff9e21ed4c0)

### Expected Behavior
Virtualization happens and only about 3 v-virtual-scroll-item divs are added to the DOM. These then get updated with the correct content when scrolling.

Screenshot shows the same example with 3.3.x, which works as expected (regarding this issue only):
![image](https://github.com/vuetifyjs/vuetify/assets/105200595/5c7891ce-96d7-40a8-a034-bae2b39fd316)

### Actual Behavior
All items are added to the DOM and no virtualization is happening.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFlW9v2jAQxr/KKdoUojVxCLRrLWjV7e2kSZv2CpDqJoZ4hDiyTQpC+e47508b1km8YvgN8Pi5+90d0WV2cLSKyWNRBOWWO9SZ6FiJwtzPcwC+K6QykPAl22YGDlYDSJhhFAYeTO9h0GoAhICRhmUglzAMwYcoXIPYsBXXIHIYrkHz2AiZ6y6ivvz145v+sv/ZXNEOYY/bijB0KcyCIHhUiu0Ho9AL1nyvB94i2LBi8BaAGZOdLeopNabQlJBCxHq7CYpUGqlJFIYPNXP64YDO6ukt1Lv6Bzc6Dxc+wSg8CR+dDX5zGj4+G/zuNPz6bPBhdJp+c1H654vSby9Kv/v/9Kr9VjVSNc8n5HX94Q/DN0XGDK+X4aT0S6HMlmU+emSWNbFUoEtP587359/YSVP0+9XmzZ3Gn3KxSg36r8Ow015EYlKUhuNOq4nI7CqA0teZNLRdxeg9gAVf4W5N+A5Ld9oQDEpECVSbfcat75nF65WS2zz5KjOpaBvxESKYTiGEB3AVT1yg4K4U57nbz4XZdMFyiDOmbZOG74yfRug4NAVAVeHM0NIPKX0lX3pCLcWynVh3Sn8pFeZ8nVbbjGffF+8nOLO4RTey7lCcN+aoA/++Q6KtGavt60d11ZWJzQo44hROTcU2WwufO0CO2yB1H/1eUek3OyE4/e7fI8cPEFqPnyCUjzxOdeWMglFw69jPcRA5iz/kqC/v)

### Other comments
This seems to be since the rewrite of the vvirtual component in 3.4. It's the same with 3.4.0 and 3.4.1.

It works in 3.3.x, but there is the issue with the items larger than the viewport #18198.

In this state, the component is basically useless, as it doesn‘t do anything more than a usual v-for.

**Comment by KaelWD** [comment]
It 

- assumes one line high on the first render if `item-height` is not set
- doesn't remove already rendered elements until you've scrolled past them

**Comment by LemonGraZ** [comment]
@KaelWD Thanks for the quick reply! But I see some big issues here:

1. From what you're saying it sounds like one should **always** define `item-height`, because otherwise a huge amount of items will get rendered which may cause a big DOM overload. In your [documentation ](https://vuetifyjs.com/en/components/virtual-scroller/#item-height) however you state that one should omit this prop in case of dynamic item height:
![image](https://github.com/vuetifyjs/vuetify/assets/105200595/249b16f9-fd65-4f13-933f-4df7ebc48bb2)

2. Even when specifying the **exact** `item-height` in the playground example (which is not realistic to do), scrolling upwards causes an unusable amount of gittering. It's hard to even scroll up and the user completely uses orientation and track where he was. And thats with uniform and static item heights.

https://github.com/vuetifyjs/vuetify/assets/105200595/f73b9c35-95d7-40b6-8f08-00b906b2fd16

From the current standpoint the 3.3.x variant did work better, because one could at least work around the "item bigger than screen" issue (#18198) by making the containing div bigger than the screen and manually adjusting the scrollbar height.

I'd really be glad for any comment or support on this, as this is a showstopper for our application.

**Comment by KaelWD** [comment]
1. Yeah that should be updated. You only need item-height if they're significantly larger than the default, and it doesn't have to be exact.
2. The measured item height is 168 until the images start to load which messes up the offsets for everything below
