### ISSUE TITLE
Playground for the Grid system

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#1871]
I noticed there were a lot of properties that don't a have a specific documentation, so probably having a visual presentation for the Flex Box Grid System would be helpful. 

https://demos.scotch.io/visual-guide-to-css3-flexbox-flexbox-playground/demos/

**Comment by jacekkarczmarczyk** [comment]
Please use docs repository for this issue, thank you
https://github.com/vuetifyjs/docs
