### ISSUE TITLE
[Bug Report][3.4.2] VStepper default slot missing type definitions

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18717]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
Copy the example at [documentation](https://vuetifyjs.com/en/components/steppers/#dynamic-steps)

### Expected Behavior
expect prev and next to be typed

### Actual Behavior
prev and next do not exist according to TypeScript

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1VFFu2zAMvQonDOgGJE6T7mMwkmw7wz7nAVUtphHqyoYsuy0M372U7DiWIn9JpB4fxSdS/zpW63zzp6qStkGWsr3B16rgBo+ZAti3a15VbuuMvFSGS4V6dDlnbbCqUEO7fi0FFoeM4TZjE4IwF06C1EVpUoEn3hSGkB1UGtsVKHw30HtRc+71GbmYZb3lPZWa6BRIBTamzhikL/hBvsevneod0WPAH+SQRBceA6R5SUnQoKsLjqAyFkFZEpvsL63QdaCg7ylfBNnyorFkUR4U0vCnAsOT437jX5QKiZQiZCtJJ9JDnpwcXw6HUA/K69hGbKjpxmuAqzvyFgtv9SaVKN9C3vA8KnfsHUOM96y2IVGZiNLLOsd6IOdaQF4WLvuzxo91IZ/PRL2mVoYzWoNOdvf3o3o24Ea6aI2LOk46LejIcyNLVftJUiFr2yB0mXEXlvc7L2T+ktq5IpBdFhB25qw+tPgIr9nGW8zH+bZFZgGXz8Jq5P0W1jN8Jh4BmXWuZWUcCN+rUhsYPwjoBjLBDf/2/WIBaDSNVleb4rYpbFdX2/VOCrvJ1Q+bnhzDzo51Y1CkV5pR0HmmKZc5yzqh+T/QQG3nYv2CO6vx3dyXenC3H5rZj7PKB3GNotJJMjHde6xgWKmK/WaSi/Ur9pA8JD+ZXX8kO/b/EzKZowQ=)

**Comment by sreenivasulureddysura** [comment]
@mtdvlpr Is this PR will fix this issue mentioned ? https://github.com/vuetifyjs/vuetify/discussions/18784
