### ISSUE TITLE
[Bug Report][3.4.2] DateAdapter.parseISO() returns unknown instead of Date

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18711]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
1. `const date = ref<Date>(useDate().parseISO('2023-11-17T12:35:37.903Z'))`
2. See error

```javascript
Argument of type 'unknown' is not assignable to parameter of type 'Date'.
  Type '{}' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 38 more.ts(2345)
```

### Expected Behavior
I expect the type of DateAdapter to either by automatically correct or be adjustable

### Actual Behavior
Date type is always unknown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVFFv0zAQ/itWXtqKJW4b0KDKqg4Y0nhgiE08QHjIkmub4diW7XRFVf87ZzvNsq5MZW/23fd99/nu5J+bQKucrmow5fxPdKeDSVBWUihDNiRXkBn47nNkS+ZKVKTXYHspb4GctdkCGeGca8pEnjF4QH3ExCeuz4tMGlANeubgpaA7GuJTDmvHyAXXhjTlyNljO/1NygkxS6hggg4KmGc1Mzf+3mPlYml6ZHtiQVYbMfZISObrTwiH+z1P/Q3xpjGJDxo4spXYDlIenLhGnUsZoSPsUmKgkgwFphaWrMJMSnd0F/RuspKDakIYXI6mtl5C8dAG5XSzsf6224S2dLrPtxEvn9BOWbzqXJXSEA2mloRlfHGWBkangaO181Ew744Pm9xJ1hqsrwPztTA/BGsRJ4A6icVO+w2pP4hkpjRcXl/1e+PhOA5Ho3B0ejMaT+I3k/g0ejeMf/QG2L+EeqtoDFtpNOrOywUunODYTDecNMhFJUsG6kqaEuumQTu2NMgYE/efXcyoGtxwHGcJ+e8D8Tu9trE0+KpAg1pBGrQ5k6kFGJ++uP4Cazy3yUoUNUP0M8lvoAWrrUcPe1/zAm13cM7tpWtxyRc3+mJtgOvdo6zR3XJZNLb8wzNPf7AbR7Hj4U66PvohhlUm9zrpE49lsIq3uzRG6gmlecGRVgArVyriYCiXFZ0hjKqam7KCsBDVDGtGb2lRatMNR6Cr8FaJe+wtinSe3uzPEaUaJFZ4HY19hSYUsuxW2xJPpKmbpQoV8AKU7flxL9qjdV+1l/r3y3af1BE1d9DZOIqH0ZC+QtEDSs0v+QJBT9zXbf/TXKijht3Fo/To9KnXJ3/0/+h2bHe0Ozu8PQncKHCZ3RoEv/4CVS4uMw==)

**Comment by KaelWD** [comment]
I'll roll this in with #18710, there's currently no way to tell typescript what adapter you're using.
