### ISSUE TITLE
[Bug Report][3.4.2] v-data-table footer pagination buttons wrong density

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [vuetifyjs/vuetify#18715]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- setup a data table component
- set density prop to compact

### Expected Behavior
all data table components to be compact as well

### Actual Behavior
the first, previous, next, last buttons still have v-btn--density-default class 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8HKwjAQhF9l/730F2wL6kGkCt58Aw/WQ0y2EkiakKxFEd/dtFWop90dhplvT0+MQZZ774vuRrjBisl6I5h2dQtQdbnwfliHQ7qWhW4pfKRBZLpz3mgyCrrcOkVmW6ON1xqhTL6JUwkWOYuLIVDURs2P5JTOeiG5xh1U5dTzrU3ib2+vjFhVOcFNZ5RBe4ZIfBuptfUuMDwhUAMvaIKzkKVPs5Er5UaGxArb3vGfHcgYB0cXjPrLZn3BGJnC8DXHZbEs1tjPVbHA8xvUWWcE)

### Other comments
checked by opening dev tools

![Screenshot 2023-11-17 at 14 36 33](https://github.com/vuetifyjs/vuetify/assets/11082362/17bce23e-68a9-4cda-84cb-999e832d623d)

**Comment by slamoliveltd** [comment]
Somewhat related, I've been seeing issues with density="compact" in  latest version. Changed the density to "comfortable" and  everything  is  aligned.

**Comment by Ribeiro-Tiago** [comment]
for me same issue with `density="comfortable"`

**Comment by kuzeofficial** [comment]
any update about this??

**Comment by johnleider** [comment]
This is resolved as of https://github.com/vuetifyjs/vuetify/commit/d84591ec6ae8351aa237f360f160c815ec760598
