### ISSUE TITLE
[Feature Request] DateAdapter: support formatByString function

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18710]
### Problem to solve
I want to use the date adapter to format a date with a custom string format. Currently you have to use the format function with predefined options.

### Proposed solution
Implement the @date-io formatByString function:
` formatByString(value: TDate, formatString: string): string;`

**Comment by KaelWD** [comment]
This is not supported by Intl.DateTimeFormat, use a more complete library like date-fns for custom formatting.

**Comment by mtdvlpr** [comment]
@KaelWD, I am using the @date-io/date-fns adapter in the Vuetify config, so I expect the function that it supports, to be supported in the useDate function. Now that I try it in [Vuetify Playground](https://play.vuetifyjs.com/#eNqdVMtu2zAQ/BVCF9uoJeZRoIXhBk7aFGmBPtAEvVQ9KNLKZsoXSMpxYPjfuyRlRXHSwI0PBrU7OzucXfDXOrGmpMsGHKvvshubTBImtDKOrElpoHDwM+bIhtRGCTJosYNcdkDJu2yFFWktLeWqLDjcoz5g4qO0p1WhHZgWPQtwpui2DPG5hFWoKJW0jrTtyLuHcobrXBLiFiBgggoqqIuGu6v4PeBsvnADshl7kOdGjD8SUsT+EyLhdkfTcE2iaEzihUah2FNsRrlMxsGoU60zVIQuTR0IzZHgxMOmy7TQOhzDB2p3BZNg2hAGF4cnvt+U4qEL6pP12uvbbKa0K6e79T4S6ae01xY/bWmYdsSCa2J5NxMDdX9kaGwv2VjwWp6YqYdF470sdB15hlFXWzQcZbUyonBnd5fOMDkfbq0cjsa4ABX5gj9yhz9ycTERYmLtAB0kBP+mNCpGreios9iqZnPcOyXR0zCjPCmV0IyD+aYdQyl50k0vTwrO1e3nEHOmgTCjULOA8s8T8Ru78rE8+W7AgllCnnQ5V5g5uJg+v/wKKzx3SaGqhiP6meQPsIo3XmOEnTWyQtk9XFD7KbiORl3Z85UDabeX8kK3O+bROIX3z1z9Xu5xdhzqcDWDj3GuqSj0jpMx8ZAGu0S5C+e0nVBaVhLLKuBsaTIJjkot6Axh1DTSMQFppcQMe2ZvacWs64czsCK9NuoWvUWS3tXbldqjVYvEDq+zo9ihDaW8uLa+xSNqGmZpUgOyAuM93+9GO2X9W+2k/n2z7Vu1R88tdHaUHR9kB/QVkj7B1D6WLyCMhbu83bNaKrPXsPt4pD5881jro6f6f3h7snvcvR3ejJMwClzmsAbJ77/IIjLf), it does work, but TypeScript says the function doesn't exist. So I guess this is more of a Bug Report...

Should I make a separate issue for this?

**Comment by KaelWD** [comment]
Hmm yeah we probably need some way to configure the types if you're using a full adapter.
