### ISSUE TITLE
[Bug Report][3.4.0] VPagination display error on mobile breakpoint

### ISSUE THREAD

**Issue by jieun-yj** [vuetifyjs/vuetify#18726]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.0
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
After creating the pagination, if you minimize the display to mobile size, the arrow button is not visible.

### Expected Behavior
Show arrow buttons on both sides of pagination

### Actual Behavior
The arrow button and, in severe cases, the pagination button are not fully displayed.

### Reproduction Link
![Screenshot 2023-11-20 at 15 51 55](https://github.com/vuetifyjs/vuetify/assets/129261903/472df857-acb4-4be5-873d-cdb765a1c495)
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkN0KwjAMhV9l5Npt/iKMKfgczotYowZqW7JsIuK7203F6U2bnO+QcLK9Qy0m34SQtQ1BAaXSJVhUWlcuSco2xRD6sm+Md4rsSN5SLwY8sUNl7z5ikhSW3EnPqwom43EFXyC+cQc6RGBYjKUhQ6PcUlxivURDEL6g3IaOoj77a3pkqTW1GJ+4m6JVpfmZpF7Rpi3XvLcdX3xh/kmT/8fplFfaMh9cAR4jmGWzbAndP8+msHsC+XldjA==)

**Comment by KaelWD** [comment]
If you don't set `total-visible` it will automatically resize to fit the available space.
