### ISSUE TITLE
[Bug Report][3.4.2] VCombobox - Can enter a duplicate value if you use the tab button

### ISSUE THREAD

**Issue by Ali-Nasir-01** [vuetifyjs/vuetify#18729]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Enter a new value "test"
2. Press tab
3. Enter a new value again "test"
4. Press tab

### Expected Behavior
Not allowed to enter duplicate value

### Actual Behavior
The duplicate value has been entered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUEFugzAQ/MrKF1opgNT0UEWkUhW1/UClHoCDgSW1ZHst26BEUf5eA6HQnNYzu+PZ2fzCnK3TN2OSvkO2Y5lHZST3+FpogKyPuTHjcwQ1ac+FRnujbqSqqKLTTAH0saIG5b5gPZcduoItvZ0IDi60xrruqE56YSQuTP0jjFtBSY5XEuM7XvJqNHvXHi2cqbMw+i6fp3OE9D7DwEwRs3QVPUBXW2E8OPTddAGhDFkPF7DYwhVaSwqicLVoGA/bkXZ+MnawH4Ye8ujApWjJasGjDUQHkmR5Q1H5uCjGOwRBPq34TzJTs24mPgIWzTLwiWSPK8EXnrj7Q99nUkIfJ1wOSadsIRW7btg22SYvbKjPyRMrfwGV/aON)

![Record_2023_11_20_20_50_53_413](https://github.com/vuetifyjs/vuetify/assets/45720799/0937f5fb-a2cc-440d-bc1e-d4f1d36f87a0)

**Comment by KaelWD** [comment]
Rolling this in with #16100
