### ISSUE TITLE
[RFE] release on bower.io

### ISSUE THREAD

**Issue by bmhm** [vuetifyjs/vuetify#1872]
### What will it allow you to do that you can't do today?
Usage using webjars (webjars.org) for Java Web && JavaEE applications

### How will it make current work-arounds straightforward?
No manual downloads needed, can be checked out and updated using maven.
Sonar scans won't need another exclusion filter.

### What potential bugs and edge cases does it help to avoid?
Old versions.

### Steps to reproduce
Open https://bower.io/search/
Type in vuetify

### Versions
any

### What is expected ?
find any current release

### What is actually happening ?
empty result set

### Reproduction Link
https://bower.io/search/

**Comment by KaelWD** [comment]
Vue doesn't have a bower.json but still appears on bower: vuejs/vue#4040  
Any idea how they do that?

**Comment by KaelWD** [comment]
Bower is dead and webjars supports npm; there's no reason to do this.
