### ISSUE TITLE
[Feature Request] How to disables the inlined vuetify variables (using Nuxt3)

### ISSUE THREAD

**Issue by MarcoTroost** [vuetifyjs/vuetify#18721]
### Problem to solve
Hi Guys,

Love the easy of use of the vuetify3 in combination with Nuxt3. 
Thank you for your efforts!

Could you tell me how to disable inlining the vuetify theme stylesheet?
My goal is to place the vuetify variables in an separate stylesheet, not to inline them.

_Dont want this:_

<img width="642" alt="275730236-324d333c-21a1-4988-955d-b998da154a53" src="https://github.com/vuetifyjs/vuetify/assets/16369103/d68732ec-f1e7-45ac-a7ce-e37fe2af026d">

kind regards, Marco

### Proposed solution
Not inlining the vuetify variables.

**Comment by KaelWD** [comment]
You can't it's dynamic. The only option is to disable the theme system entirely.
