### ISSUE TITLE
[Bug Report][3.4.2] v-data-table-virtual adds extra, not visible table rows (0px height)

### ISSUE THREAD

**Issue by cjhudson101** [vuetifyjs/vuetify#18730]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Inspect the first or last visible row in the v-data-table-virtual component.  There will be one additional table row with a 0px height that seems to be a product of this component.  Regular v-data-table does not have these rows.  I can forsee this causing issues with UI testing like Cypress where we may count rows and get a number that is potentially more than we expect when using selectors...

This codepen is from the example virtual data table in the vuetify documentation.

We have been using a tr:last-child style to manage a subtotal row.  This is not a show stopper for us, but I'd hate to adjust our code and then you guys remove this last row in the future.  :)

### Expected Behavior
The last row of our dataset is the last table row in the virtual data table

### Actual Behavior
No matter what, there is one additional 0 height table row in virtual data tables.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtll9v2jAQwL/KKevUIEGAAKNFgNQ+dHvYtGlUqyZAqkluYBGcyHHQGOK7z05C/hUjkMoLvjvf+ec7X+zp3gi503wIAmsboTEwhgI3gUcEjmcMYLhtuESQhiALDxtbykVEPGUAGKyQuMjD0cxIRzMjtVAZQ+nT+Y8+EZlxhXS5EtLYbbWOOjW/sSVehFLPyAYTw3jYPLW8BBs2C5RSDB1OAxET49/A5wJc/EMiT8A+WUFFAbN2FAE4ioizXFZg8SYGMM11AHsQVHg4gFu1C3jeBXhbB+LRJZO6UBAupLzGnZQU+S0c6qf9JwGiC+aa+SKsFWIgc7MIoZqjD/EV2VKswNzo/L14gj7AD04dBPNG5x8ou979NxKu8dwpU8lxXhgv1AmoZrYoAKjkHbMUCpTrlO1xagbQ6VX0yZYHYNsVQ7wX6dBSv4pN0UqXlt0uGSr7Pgn43UHCvpEziLYO8Q17itg7i1g2XIL4y9+RpR6vutIRr6vB65/Da99fjfdCtvgzYkxL2NURVhbLCO04g7oElg/GJYQTJI8c8Z9s9dMpvNNVuHyeMsDuOcB2OdolgF8IX/j8c0S47MCTiJWgOWKvipEi3p2tcv/6HHrUWT9Rpuvjjq6Pu5o+Plvj6/t4Iny+kVUma32nVD8pWZmryU0ZP71zI79Q5k4I9XQ11n1oeppOvn/nTn6Sn8Fn6urapFM+NYUaa86gHR/C6/s4v2oOyUAZk5Hjb4JIKJpsC8VXSelNkL0KppZlPXBOdmZbAdUseceFZm1ubUhgUhiNy/lwfBaK+I6DkbwtpbNY0dCKL70phY+Qi1aSgvkRNL8eLZVT6f96s8/EA3y42dPDa3Fuiqjm5OpDLUtAmorkX64ybKaPI+NQNzpWx+ob6r9r2cb8P545fWc=)

**Comment by cjhudson101** [comment]
Found that there is a row on the top and bottom when applying a table row height style to ALL rows in our data table...  Updated description accordingly.

**Comment by KaelWD** [comment]
They don't have 0px height if you scroll, they're used to reserve space for the elements that aren't being rendered.

> Cypress where we may count rows

Pointless with virtual tables

> We have been using a tr:last-child style to manage a subtotal row

Use the `body.append` slot or `rowProps` prop.

**Comment by cjhudson101** [comment]
We are using virtual tables to disable pagination since the prop was
removed from regular data tables.  Is this the correct approach?

The two reserved rows ARE 0 height if your entire data set is displayed (no
scrolling needed/available). They’re just always there hiding from you, but
in the dom.

It seems like a normal v-data-table with pagination disabled may be a
better solution for us. Do you agree and how would we accomplish this?

I refactored to use body.append last night and it worked great in place of
our grouping solution we used in version 2.
