### ISSUE TITLE
[Feature Request] Side navigation component and Horizontal Menu

### ISSUE THREAD

**Issue by eguvenc** [vuetifyjs/vuetify#18735]
### Problem to solve
To create enterprise applications  side navigation and horizontal menu is very important.

### Proposed solution
What do you think about adding a side navigation and horizontal navigation components like this ? 
https://atlassian.design/components/side-navigation/examples
https://atlassian.design/components/atlassian-navigation/examples

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/navigation-drawers/
https://vuetifyjs.com/en/components/app-bars/
