### ISSUE TITLE
[Bug Report][3.4.2] VInput defaults not working on Vuetify form controls

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18731]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
```javascript
export const vuetify = createVuetify({
  defaults: {
    VInput: { hideDetails: true },
  },
})
```

### Expected Behavior
VInput defaults should be used by VTextfield, VTtextarea, etc.

### Actual Behavior
VInput defaults are ignored

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UcFOwzAM/RWTS4e0NhLjgKYOCYkD3NE4UA5V625BaRolbjVU9d9xkzINpF2S+PnZefb7GIV3lRx6JNV8Z19ebIVqbecIRqgcloT7mIMJGte1kCzcpDCFwVOgVp3xBEsCdn8LV2NhAOiILW4hvAFqbMpe01sEE60OR0rWMSflfE8hWnj+XLh/NbYnDuGoanxGKpXmLLkel5L5nG4LI9ZhsidrMxbGY+WErdWs63Gm5UNaWhueIeARuJdBt0ABJDxR2ijUNQxp29Wod4Vo/aEQIK/wZllpHXVdJf3iufz/8YxEXbm80Muhr5yyBB6pj7LPNjlsLs0JxsDiCYtlP5ixSl5Q6w7eO6frm4QXlMvYkpuJaS022SZ74KVtsvvsTnz+AIllsJs=)

**Comment by KaelWD** [comment]
It did work like that originally but it ended up being pretty inconsistent and confusing. You will have to define hideDetails for each top-level component you want to set it on.
