### ISSUE TITLE
[Bug Report][2.7.1] v-calendar shows wrong week number

### ISSUE THREAD

**Issue by jstropel** [vuetifyjs/vuetify#18738]
### Environment
**Vuetify Version:** 2.7.1
**Vue Version:** 2.7.14
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create v-calendar with properties

:show-week="true"
:value="date"

having date = new Date("2024-01-01")

the week numbers are wrong

### Expected Behavior
Week #1 should start according to ISO 8601 with the starting year's first Thursday in it

### Actual Behavior
For example week 1 in 2024 starts on jan 7 which is wrong.

### Reproduction Link
[https://codepen.io/jstropel/pen/eYxMeGr](https://codepen.io/jstropel/pen/eYxMeGr)

**Comment by jstropel** [comment]
> @jstropel I had the same issue and found out about this option on the calendar: `locale-first-day-of-year="4"`. Adding this to the v-calendar or v-date-picker should show the right week number for you.

This works and is in line with the documentation. Thank you!

**Comment by jstropel** [comment]
See above.

**Comment by fedelaport** [comment]
This is wrong anyway.

**Comment by J-Sek** [comment]
> _This is wrong anyway._

Something missing after #21910
New bug report #22340
Thanks for letting us know 👍🏼
