### ISSUE TITLE
[Feature Request] VDataTable support for date range

### ISSUE THREAD

**Issue by chriskulwik** [vuetifyjs/vuetify#18733]
### Problem to solve
If I want to select 10 dates, as of v3.4.2, I have to select all 10 dates individually which is a pain. Would be great to be able to select a range of dates instead. This was implemented in the date-picker labs release, but changed once date-picker was out of the labs. 

### Proposed solution
There is already a `multiple` prop, which allows for multiple single date selections. Previously, setting multiple to true enabled date range selection, but this has changed. 

I'd recommend changing the functionality back to how it was in labs, where `multiple` enables date range. If there's a reason you need to support selecting multiple individual dates, maybe the prop could be `selectionType`, with options of `single`, `multiple` or `range`.

**Comment by KaelWD** [comment]
This will be a separate date-range-picker component.

**Comment by chriskulwik** [comment]
@KaelWD Not a popular question I'm sure, but any idea of the timeline for the date-range-picker component?

**Comment by chriskulwik** [comment]
Looks like Q1 2024 in the 3.5 release?

**Comment by adamjimenez** [comment]
Is there a spec for the upcoming `VDateRangePicker` component?
I'm hoping we will be able to select a comparison range - similar to Google Analytics.
