### ISSUE TITLE
[Bug Report][3.4.3] VSelect all items not being displayed in menu by default

### ISSUE THREAD

**Issue by kyle-johnson-admin** [vuetifyjs/vuetify#18748]
### Environment
**Vuetify Version:** 3.4.3
**Last working version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Not all items are displayed in the dropdown by default

### Expected Behavior
To see all items injected in the items prop

### Actual Behavior
Not all items are visible when the dropdown is displayed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFWe1u4kgWfZVS9kfPSJ1uaWeklVo9qy3swjiAnbEho/T0/ChMxTgYF1226SGtfot9lH2DebE9JgFuQZHJDwi2z731ce+5p65//3ZVm+w9X6/fbVp19eHqY52ZYt2wWjXt+t+fK8YyXdUNPtuqMdtRgf9/Yb93Nxj7xpZq+4G9mUbhRPhsGEaBH4/fvGUPpcxxPZ/h/1LOVNk9VBWNmrNhUeVzvXrDvr+1jfB+MOBRmE54dLQgH4gF/pAvZIURyMoBH/HIZ2HafaXEwJ/UQCmrOQvr7qt2mehhAJyASws8g3PpggUiobD5kwXLlXHCxkB5PGIpH8fUaU3RK4AzWbFUrrTLSOTHSULRc4qu5toYJyyIRxSlLVSuSzdoGo4sWGHD2qJ0Ayc88SaYLIF+saCNNFmDiTrBYTDlrNvdHk96U59ayW0rRd5K1u1xT5pZO3eZSwIBixE1YqgRkyvYqZzQsbDDY2UBV8odHsm0R0FfLVA7c0Gm6SThI8tXS2Ft3RhZOr11UAvYnAKdsE8i6fHwxso9K4yflJnJ4tGVej0+4GNOkm5GQ7gnF3KFoHbBEh4Sh7OFDTOycHqLghH3RTogSBr1PVnlpZyreuECY5p+TMdKOaoLGznXrsGKETaS4rYUp0ppWjcsCKeEEmfKhuVF6+BCwMJPgqDoVgBVPCkXKLJW89HCVM61FMnYSqgZDemeMitnEvUGU4ulZzTGeovWSdC9eBTe0ci0femy2FiR+fzFDuiIh4l4y9IwmjCBKOeTcJriN++ya//w3jT4bH/p6KGShVFAFFXDBDJBNkVb47dEDr48ftF7iszfcdBAJJ9EEN/tKOTU7cEOdVuDFnakNFDmSeV607HLqb+Do0n6G6fsNKN80dNN/VW6yKkXT+/E5KX+EfTGQrcb1bzUP4eJhH8KRwRLebFn5FNRXt6eJJyE6YCFkR+ipMWewOdEJLgcJ/dnC1W49scUTVEvWFjNCxS8OFP4nCiDy9og2S4sWDKNRMj8LjlTaACaapU1/rZSBfO7NK1lCeo+NzUdBdzizhktL722zKWTPHvTBNKHsz5PYwKm0qXXmiW2nfVlrZ0Gplg4gqWFFdgWa3IO8/i4F2O9j7glZVBPrmYaa+kEiiSOSQZnNBcBVEZrRw5DrnBKFyjYFFZJF1t4/FawO5H4hNAyGpeeXCt2p8zcQWoevx8jlM503ZLSrye3KwTLubCzg9RD5UdZZbz/LLwScTvtjULvLDwzbN1peHqQBai5jD88C7JErdtZWWSXAtMbcJKHDS1Q3gIqzQEIR3SFqPb0FkXpWpyBJWQyGvCAuHjCGySQ2KjWZ1SRUaXsLQx0Nsr2OVucrGnsxSn7YShQsaLgx+NGnS7pYaHIkupM18AqFLQqB/Zl/y6taDyKxz0a7hmVrZ4u9WrmDPd4HCe05i+taNcrbaySfzpDiGXmi3HsJag53ithA7o4nyPUNPPVSmcG9Sb7+7jZuTv6OBi3Imhn9WDKYSQenudMtrRM6OXloxA2dcJZlyYETuuBp1E/WeKU7N5f/50I5od3MSo2wVNS8/76X6OYX2w0arLDRBJjrYnzheXcaKyly7MltTOqmT2n0vamCfc4Ye2MlluvNTLD2egcdn9ricHMYqPt2qkFvU/CG7h2loo770lli1d21hfRmCdDctikm+qraiXN0gG7CaEQJqTEzKk89B+LmW4bR43BeT6MrDCY0+Tx9aqonEGwB1KaPZigebs3QSj1zJjwplDtydGCQv4cLIishWg3DlhwfzshIFrORb5dNw7ICIpydGd7q2m1EiUUY7m54PHXKYfiCVFlcFiOBFm3nJ54xZdWQtYUKChBW1TKsYDoDkwSakDRFBCQRcYJSyexdUpV9MQh6kY7T6liMgjjWwtHRb1oFoVeu4B9Phq6Wy8PNDL7sly+3n3p8yQWDis0VvrSaPWKifCGRPgDjfB+8eiI7n4Y2UXwgXJUv6jcSrmf8MgjzPZAd6ZvZJU5KK2fiAj5j7Cw9H1OZWLfqArpj5BwivwXE7fx6D4SKd2stcPKrS63lapfOVS92EvBDDjWHAV7KM4LeOPQRC+OUlDHQpmjWi/UxSIecJzkyOypgAzkzCU6A8hcOtecElAAkesKy0DESWChaBoESpvcDUsgN3FgOVCVDTPQmVsHDJ1L6ovK8AA9S5enEOetERpjBEaDLyhmkJvoizmgiRA0/HIafoFRyhV+Hegk2HMqMTvchXAH1Jb9OdUiALp1P7p2vhjF01s61DVFgrZVqdu1a7hTepTLaSUHzHF6A2AixjgBEhRlMKAatcLJzwVF8KeC7HpOK0XQIrZr5dr2U4qnAvwSrz+DrnshzqtTgqXC4xl7PStwVm1dJu7teKPyI2i3zoAbcBzRiaCiizOQOHtfpImB4Im/a36MPR99mBEh+xOWWCA3T1lioKSZ7xog42yOJkx5LAIXSGIQRz6EGakCC7qyA13NocwcBQDAgA3xQZC0CgGZsyE+HNBphNM/iYEFjblBW+Hw7wiB0ENjkCZVQXufYYbGoCuldn0SAqLT2zVAnJD4hPULmoeA6VO630NRrwiK0kWIauUE/EoAVLkA8MUFOF0GypuhubQM6UiwuM/AuQRK+R2Roph+YGPnMNOEC9KxQoOKIo1UtGO1B034iGxzQfMgbGTp2OQbtLctDfxIh3iD9rZTAt/wWzqvR8p9N3LtmtGNSCwieqTLeKOMk4Zu4sS3HFHJdKPN3OVpyD/x4cB+27akJ5GhfJLLhftl21BE97TtREc5VNXWsRjDMAl7ONMRFC13w8IUMxzqHMA4je/ICe1PmtBDXeuN44A2nP4GuiO+KLsO26/guz3oj+6jRF90bQocnrYRRtGxVNFs8aazasuye+ChrfCCSlfdi9Hbswd/wKvN1Y973nQa6p7obn//XH18//ySFa9XP+LqukRl2r1q/bi5luvnt667H3j12uAdiDIvl3YXa1WqrNlfYGxzvdIoo798vjr3+/nq+BzcZGqhy7kyeDbdWWFgDPZg9IpBwDGsjv5qQRBwaAOh83VN0Mf7H7pJ1bBG3g5TfHf7eiPLVuEZbMzZvaZoyu7ebmfo3U3Xaa0a3ELrUxn0h9Sc3v+Al23t9drodef+UK/2f1mpaxVXaJN0g/dwplx+YI1p1aE47f+wE7osU7T2GpV3kVNhSY41bFedjo4P+4Cd2O8c+0c3lW4Uuzl1j5PHdltWYl2u9wFARynrbvgvD+hNJ5/nis6z+/tP1o0fz70SejbG8o8RzIvNwdmqvP4ZI/z2PNp3ux1g379/fI+H7HG/JwOnE39vxez+0eew3McuLtjB2115jm0Lf/X97dVP735696+r7vvnd/+8+uP/XJ9ogQ==)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-select/#slots-item
