### ISSUE TITLE
[Bug Report][3.4.3] [VCheckbox] click event triggers before update:modelValue

### ISSUE THREAD

**Issue by simon-lorenz** [vuetifyjs/vuetify#18745]
### Environment
**Vuetify Version:** 3.4.3
**Last working version:** 2.7.1
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Ubuntu 22.04

### Steps to reproduce
- Create a `<v-checkbox>`
- Add a v-model and @click handler
- Observe v-model value inside @click handler

### Expected Behavior
I expected the modelValue to be already updated when accessing it inside the @click event handler.

### Actual Behavior
The modelValue seems to be updated after the @click event.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptULFuwyAQ/ZUTSxKpsQd3qCI7apWpU5eqS92BkHOKggFhbFVC/HvBOKmTZuLu3XuPe/fpSGdY/qJ1NvRINqS02GpBLW5rCVAOa6r1WI4NU9JSLtFMUAK/kZ326geGdasOKKqajBAeagLPTHB2CpCSu1gFSND9SHpXx6NAaDFg+Z+h3u6SegPOweQE3pf5eZE5CQYqegQuYfpgrvqIs1f5liZXHmV+myYiKWyZz44Q2o4Zri10aPsk561WxoIDgw14aIxqYRHut4h0gODb2cvmVWQtGyo6XP2b3mx4zY3sppfMcnWJt1yBSwnuOmTpHNV5mvoo8DFXShIyEP9AiqzInkh8H7OCfP0CY8Wt+Q==)

### Other comments
It's easy to prevent this issue by creating a watcher for the modelValue, but Vuetify 2 behaved differently so I was confused for a bit and would like to know if this is working as intended?

**Comment by simon-lorenz** [comment]
I just noticed that `@click` isn't part of the [API](https://vuetifyjs.com/en/api/v-checkbox/#events) anymore.

**Comment by KaelWD** [comment]
This is consistent with `input type="checkbox"`, and you should be using `@update:modelValue` anyway.
