### ISSUE TITLE
[Bug Report][3.4.3] VDatePicker update month or year events not triggered

### ISSUE THREAD

**Issue by algarpe** [vuetifyjs/vuetify#18747]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.7
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open month (or year) view mode and select any month (or year).

### Expected Behavior
Events update-model:month & update-model:year are triggered after selecting a month or year.

### Actual Behavior
Events aren't triggered and view mode doesn't change when selecting current v-model month/year

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1kOFKw0AQhF/l2D9VaC5gBaFcgz5AH0CMP4500eA1d1wuASl9d3f3jKaa/hoyO3yZuZcT9LEpn0LQ44CwBdM3sQ1J9ZiGUNWdUo3v+qSGcLAJ975L72qnjlkrdeJEzniH2vm3m5UcV+scuuXA+S/nGW0kzKfIMoVvBGFZZuz9AZ10Eb3WhY7ShXTimDKPpHkm4TE4oslUMxY25NXyQahk2w7jtyUm/7sIbfOBcXKVesydtrJ5V8PsuWr4H+NVPyl+jKWQdC5G6wacEcn7DVemvCg0VSf3sjs7eZopZ5PhvIaN3ugHYL3Xd/D6BXyQq/4=)

### Other comments
When selecting a month (or year), from the proper view (that is, "months" or "year" view-mode), the events update-model:month/update-model:year aren't triggered.
Also, in Vuetify 2 Datepicker when selecting same month/year that v-model had (in "months"/"year" view mode), it came back to "month" view mode.

**Comment by KaelWD** [comment]
And when you use the arrows it emits 11 for year when going backward.
