### ISSUE TITLE
[Bug Report][3.4.3] Icons under data table slot doesn't have correct size

### ISSUE THREAD

**Issue by gamekingv** [vuetifyjs/vuetify#18744]
### Environment
**Vuetify Version:** 3.4.3
**Last working version:** 3.4.2
**Vue Version:** 3.3.4
**Browsers:** Edge 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just like the reproduction link shows. In v3.4.3 Icons under data table slot doesn't have correct size, when in 3.4.2 is correct.

### Expected Behavior
Icons has correct size

### Actual Behavior
Icons doesn't have correct size

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVl9v2jAQ/yq3PCxUwqEdm1QhQK2maao0rXuY9lL64CZXatVJLNukMMp339khTQgZ7bRJ28OCBLl/v9ydf1zuah0YHQ/OlYqKBQajYGwxVZJbnM4ygHHBuFL+1gtxnlkuMtRblVcm3HJm+Y3ESgkwukOeoDaTWbC9mwUNq6CnOJv/bVqcghVcLtBZ1X4QU6iZ4nNnZydNe4KZEXZF+jhPFY9tbXzKlvKt6oOCGZnbkc0VhaxhrvOFwuTCPaQPwnx08qXCrA82n88legVsZkEDjfASUewofEtubAYF14JnlsAtLikZiHOZaxKVFinXqxZQZ3JKI2WQTB2moOZP00QwJRdmPNgqYDyogtpo0wwfnB8ls2tq5/uKMTij42dinuUagbHOitr47QLb9r162w5nsRTxPXm0Dc2reS6H/ACiWyEt6l4Pj2AyBYzsSiFMJhMIPUh49Fx8rj/w+K7Xm3uABgec5vGxSQTSHIBrl/Tyk97HbB49LhXPEsalZPnCSvonvogIZdh/LvwxLrx+/fe5QC2VXBn8ZTZUgc/zYTzYnW416KGJ6ua0H6nuZm9gliH1C6SpTcDYlXSj/UEk9m4EJ++O1bID4DAZ68uI7w5tyUxKXTpErucIXF+uv+TmJzFmsXhq/s+DpttW/6t1JCjR4m/VQdToJCxp1yUTIkFvz82gklJu7kl+QVy2IBZ1O5KyyaQOfrqM6wWl2mRIubvKOE256exgkGhiLZQFg3ZRLkIiVbm2sAaNt336ok1DFAgbuNV5CiHNztAFupmXGQvb9Qcmzr93VSawBiusxBGE5++/Xlx+DvtwjysSHViehbDptx0vvjw5CdXl8O3TeY1DPat8rmk21en4JconU+bdu1r7ohQFnUT+E/owdz4jeHPqBYIj+/D4mEoD2DjI8aDsDPUk2PSDYTSMTgP3+zYaBtc/AHtUurs=)

**Comment by jmeij** [comment]
In addition to this, the text in the data table also is smaller in v3.4.3. You can see this in the example @gamekingv provided.
