### ISSUE TITLE
[Bug Report][3.4.3] VDataIterator does not display pagination

### ISSUE THREAD

**Issue by MarcHartwig13** [vuetifyjs/vuetify#18751]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.7
**Browsers:** Firefox 119.0
**OS:** Mac OS 10.15

### Steps to reproduce
Add items prop and itemsPerPage prop to VDataIterator component

### Expected Behavior
Pagination should appear below displayed items

### Actual Behavior
Pagination does not appear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1Ul1v2zAM/CtXvzTBHAdbNgww0gLFsIcB+wfLHhSbyYhaH5Vpr0WQ/z7KdlI4wB5sitTdiTzp1ylrY7V+CqHoO8rKbCtkQ2OEHncO2PYrE8KwHJLKOzHsKE6loVgbMSsWikZ8RKkr2z7ssiHuMpTBHEnzFFI61FeB4mra+LTLrnIqeGkA/aptvJQ1HUzXiAJPGLg4zwhzysFHRS4SMAcvwW4kpZOf6S31dcMeBzOxVvaeXT21XkTzV5Hb9biplBvSPmI9b2M98+6/xSQ58+zibzpqZnCqjP7PZDRtq8hBBhC9Bh8Fk004jWLpgBKLJR4esZhqQHK8xMf8kg/WlHiK0bwVh+jt4oSG3FH+KOoLzjkWzzn6GxVAWBoVuv+hfNzjA3r93mUVQK+i+z99VACHtrOofaPPo2WBsSTQSVuqhKSLMDUHbrlidwQ1LAW+eWt9zTnUIPaOdLw9C7d46fRHraAxexVH75suiIL2XXuH7+alI1Rd4Jq1SLDs2JocRqDuVaRRvBh9G9YcHY9NkU2snhwbC0cpUUujR8N70hApav+dq9+PI3t3fx33vFxO6/O4OKcLu15Rds6zTbEpvmYpfi422e9/0VcWgw==)

**Comment by websitevirtuoso** [comment]
Yes everything correct. Pagination is optional slot
https://vuetifyjs.com/en/components/data-iterators/#anatomy

Here playground with pagination
https://play.vuetifyjs.com/#eNp9UsFu2zAM/ZVXX5pgjoOt3WFGWqAodhiwP1h2UGwmI2pJrkx7LQL/+yjbSeAM6MGmSPGRfI/6dUyaUKyf6jrrWkryZCNk68oIPW4dsOlWpq6H4+AU3olhR2EKDcHSiFmxUDDiA3I92eZhmwx2myCvzYHUj2abnIEKPbVCt2oqL3lJe9NWorlHDGj0M8AcsvdBMxcxMQUvwW4ExZYv9B4nuEKPFEwoFb1jV05DZsH81czNerxUyBVoF7Cej7GeqfRR8Jrj3ntVaqAYBXn2rZP/aXYrvWRnhL1TpPUlVWcJkVfkDvJnCgwlpvkvqI8Hi7mztZ1WHDWY7ThGxicwK6NuUwSuZUiit9oHwbQ/HMdisUGOxRIPj1hMMQysc3xOT/6wsxxPIZj3bB+8XRwx8svx5Sv6FIuXFN1VFUBYKi10+0PxuMUndPpdymoCvYne//RBE7huWovSV/pCGxYYSwJl2lAhJG2AKbnmhgt2B1DFkuHZW9WdU6hAKigpvR0LN3ht9UeNoDI7LY7OV20tmrRrmxt8N68toWhrLlmDBMuOrUlhBKpeQWrFi9FHa83B8TgU2YjqyLGxcBQdlTR4VLwjNYGCzt+68tKO7M3tmW6/XE7nfjz0cWHnFSV9mtxld9m3JNr77D75/Q98rUBi

![image](https://github.com/vuetifyjs/vuetify/assets/5112918/1dff61da-3abe-478d-a40e-3e6336818f88)

I hope I could help you. But this is not issue

**Comment by websitevirtuoso** [comment]
You also can find all example in repo code.
