### ISSUE TITLE
[Feature Request] Allow Nesting Menu/Drawer

### ISSUE THREAD

**Issue by mstaack** [vuetifyjs/vuetify#1875]
Currently the specs have nested menu feature. Maybe sometime this can be integrated into vuetify.

- Nested Items in Drawer (left side bar)
- From Dropdown / Toolbar 

Currently nesting in the left menu does not work.

Some Links:
http://www.material-ui.com/#/components/menu#menuitem-properties
https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior

Related to
https://github.com/vuetifyjs/vuetify/issues/898
https://github.com/vuetifyjs/vuetify/issues/1830

Example inside Menu:
https://material.io/guidelines/components/menus.html#menus-menu-items
![image](https://user-images.githubusercontent.com/10169509/30819671-bf96c598-a21f-11e7-8106-e8b2a7009b7b.png)

**Comment by KaelWD** [comment]
This is already possible, but Probably doesn't follow the MD spec to the letter. 

https://codepen.io/anon/pen/LzxZzR?editors=1000

**Comment by mstaack** [comment]
@KaelWD cool thats a starting point. i have a usecase inside left side bar (drawer) that is not possible atm

**Comment by KaelWD** [comment]
That looks like https://vuetifyjs.com/components/expansion-panels

You can see that the docs site uses them in its sidebar.

**Comment by mstaack** [comment]
okay cool!
so its basically just a list inside drawer....
but deeper nesting isnt on the docs page... and currently not supported. or am i wrong?

**Comment by KaelWD** [comment]
There is some buggy behaviour with the arrows on the right inheriting the wrong state, but that's a separate issue. 

https://codepen.io/anon/pen/YrNGNv?editors=1000

**Comment by KaelWD** [comment]
This has been split into #1877 and #1878

**Comment by mstaack** [comment]
@KaelWD @nekosaur thank you! stunning community & framework. happy patreon. cheers max
