### ISSUE TITLE
[Bug Report][3.4.3] colors are pale when using v-slot:prepend or append

### ISSUE THREAD

**Issue by umutcantopal** [vuetifyjs/vuetify#18760]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.4
**Browsers:** Firefox 119.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
give any color a component inside prepend or append slot

### Expected Behavior
color should be same

### Actual Behavior
color is in light color than actual

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UcFuwjAM/RUrOwASLUidNKkCJDTtvIlxoxxMGkZEmkRJ2oEQ/76ktFDYdmmdZz/72W91ItbQ0VzruCoZScnEsUILdGyWSYBJFVE0OVCB1k4zUhwiLJ3KCBR4iL557nYeTcbjjNT1NUNw6yBn0nJ39FmqCo3UXSuuNZEtNzuGOTOzxdvH+2L5ORn9ymTykcW9whYDqKKtMn5KP8BD4APgEkJsM3KrSvcsSOF3WIWiZAENDTsJqkTdUhteoDneUtcFvJj2TF6AFcql2jDNZN4pqRVzqiSk4dsMikPs79cOeUowwQ311wnLh2R3yqjjRgfuXCJy3ImgwrGDa2eEuOn4UHjzoJtrvWuwi/X+Ebz3jwcZE0sN15cqdtDKBLe3WAoHp0ujHB2m0B/AdAb9BoOLKymsboucIChNobdgKKIlL1jPW+hv4KEi5xEViu57cB7+QZmXOWeSPjCQUlVK9w/nVcmKGcuVtPe0rcCvLmfdROdBHZzDDa5bk/OQJHESv5Dwf44Tsv4BL+4ABA==)

**Comment by websitevirtuoso** [comment]
You can just remove opacity from element
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/3399ae8c-a952-4531-a0e0-12ce6c6f9d92)

**Comment by umutcantopal** [comment]
> You can just remove opacity from element ![image](https://private-user-images.githubusercontent.com/5112918/285560838-3399ae8c-a952-4531-a0e0-12ce6c6f9d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjM2NjUsIm5iZiI6MTcwMTA2MzM2NSwicGF0aCI6Ii81MTEyOTE4LzI4NTU2MDgzOC0zMzk5YWU4Yy1hOTUyLTQ1MzEtYTBlMC0xMmNlNmM2ZjlkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMDUzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTcyOTcyZjVhZGMwZjIyMWE1Njk0OGYwNTMxYjdlNjQwMDg2NTMwNDRiYWU4Nzg5YmFhZGVkYzU1ZDk5ZjYyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lakg-IcprqyvX7S9pU7uPvo-ubZO3SPwcnrWOHJNHoI)

@websitevirtuoso ok but how? do you suggest writing css?

**Comment by websitevirtuoso** [comment]
yes I am. no one will fix this issue because this is desired behaviour for material. 
I think you know how to change css for element I already gave you selector

**Comment by umutcantopal** [comment]
> yes I am. no one will fix this issue because this is desired behaviour for material. I think you know how to change css for element I already gave you selector

yes I know how to change css but this behaviour was not the case when using v2. when switching to v3 from v2 I except same visuality on the page. And I don't think writing custom css is not a good choise because if I use a component library I shouldn't modify them with css.  I think this is a issue and shouldn't be closed.

**Comment by websitevirtuoso** [comment]
In my project I have to write so many css that I can't count because I wanted to style my elements, + used different themes.
Right now exist already md 1,2 and version 3.
Maybe it can be fixed with an option when we remove opacity and use rgba option for icons. like on material ui
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/92525b6b-95da-4c7c-a600-662f5088d340)
Member of the repo will decide which option better
