### ISSUE TITLE
[Bug Report][3.4.3] Closing v-overlay cause scrolling unnecessarily when scroll behavior is smooth

### ISSUE THREAD

**Issue by ktc-chrisl** [vuetifyjs/vuetify#18763]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Scroll down to bottom
2. Click "open overlay" button
3. Dismiss the overlay by clicking anywhere

### Expected Behavior
Dismiss the overlay only

### Actual Behavior
Dismiss the overlay, scroll to top then scroll back to bottom

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVEFugzAQ/MrKl7RSgQM9VClB7Qty6a304NBFoNjYshdLEeLvsbGRkj9wsnd2ZjSX2d+ZWdMW31rnbkJ2ZBWh1IIT1s0IULmMa71+16FVI/FhRJMgD+r6By1VxcbaoR3aoQ1y2YVG+GrF0F5PDVMaRzgBmQkbVp/DdHZoBL9VxUr1ygetijtwmVT/KJKBVwZ2Wm7l9MhzOwMSy1sVD6X2o23NoAks0hSjDlIrQzCDwQ4W6IyScPD34BDTeF9LkLJ7ykvHhcXXYBytki3dRDwbPUkBcwzmGUqI7II9d4MyR7BSKeo/w3ZZLZKMLW+szMv8g4X3PS/Z3x1QoFjM)

**Comment by ktc-chrisl** [comment]
I edited the title and content as I faced the issue while closing v-dialog, but it turns out it is dismissing v-overlay that causes the bug.

**Comment by ktc-chrisl** [comment]
Seems like I can use props `scroll-strategy` to control the scrolling behavior, hence it is not a bug as I thought. 
https://vuetifyjs.com/en/api/v-dialog/#props-scroll-strategy

**Comment by hanamurayuki** [comment]
`scroll-strategy="none"` solved this problem.

```javascript
<v-dialog
  content-class="custom-dialog"
  max-height="800"
  max-width="800"
  persistent
  scroll-strategy="none"
  transition="slide-x-reverse-transition"
  v-model="isDialogActive"
>
...
</v-dialog>
```

**Comment by frederikheld** [comment]
I don't think that this should be closed, as scroll-behavior="none" is very different from scroll-behavior="block". "none" allows the background to scroll, while "block" doesn't. Both have their use cases, so both should work properly. I filed a new bug about this in #19109
