### ISSUE TITLE
[Bug Report][3.4.3] the "filterable" property of "v-data-table" does not work

### ISSUE THREAD

**Issue by titou-from-mars** [vuetifyjs/vuetify#18774]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.9
**Browsers:** Firefox 120.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
- Create a v-data-table
- Set the filterable property on one of the header item to false. 
- Despite this, the column is still taken into account for row filtering.

### Expected Behavior
Make the column no longer searchable as described in the documentation.

### Actual Behavior
no effect

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1vmzAQx7+KhTS1lUqekzYoqzS1e+g6TZP2amr6woEjserYyJisWdXvviNAAgajRBtvgu98vp//dzZ5fHVi5Xc/RFFnk4DjOTMN64hTDTdzQchs4/pUBSREC9FMc3g/d74nWjHNpJg7u0k4rQgiGzfmUnsaXnTu2y2Sjt2QAQ8KI8GpaxkAxwVjoMpfzZ2Dj9PFzvOz5okURCAClwkBymW+FDhtHTB3TZeChdvy3JiJJQeXMwGltFQxKjRGyUSnrqAcsmIBuAFoynhcWG9m3fIOij13S0rlpo0bUE1dTRd8n9FbAQ1AxZgwfzvk8xiukXoCiGNQuuzKRKmps4M5ZMmqhKa0TDgwqGaxr1iUlQJeIqk0CSCkCdfkNVsvXer8ohgRokAnShzGqOIuv0fOzi5LOmVb8cjjwUbKUelDOVsKDIw1VbocnT7PsEWXoGswPbs+Q99dJgo57/d6S8RQG6znhTk7ZFyDSrXwSEh5DJek2yUz13WJkATCEHxdjnirxBvEGZRPuVQMYhvYrcX/jyh59pCiVvtcn/DgneOuLZOx7AvkKKHhuC0gUlIDE6WQH5mlLYgpWY64xyE5f2dMfyq9F/3c3h9p8dMtKvkHBPkll0m9TYpaeKQ/npp6U+2RSadXC0ENPDIYGfZ86x4Z1ULSDWKGirW1UXL0ex+Ir4CuSUxF8Jv5Kzv/YHjVxD+18deml/iH/4n/o88pUy3Mk0ETc98uukm2h66HZNDVXR4DfZtEPn2uXRsH6mFv3EQ97JiK5tCTk5W+Phn6M95doBbYK0EL+Hhymtwj80jsyYcd05X3SDXDMehfgfMtWQDFO8BKftUoec8GPrUeznpIBl61HsP9TXLOIhm1UE8b27vXMc0FdbXuZepG5uoyxzB/kQK2vlwv7NCjnkmRd7cF+tra3ZOOWbQMe1Q1H8N9J0XScnePxo1CD8a2/hhX77LKkWxu7MHpYj8w/ZB+bG3U436j0gPrcZyYeu6pzRpkzPazePiYvmUvmRMHs+7+P53zdukMO3jSnfQX7yrn6S+e6vBe)

### Other comments
Note that the example in the documentation doesn't match its description: the example doesn't use the filterable property and it uses graphic cards, whereas the description talks about a table with desserts. There may have been an inversion with another example, but I haven't been able to find it.
https://vuetifyjs.com/en/components/data-tables/data-and-display/#filterable

**Comment by websitevirtuoso** [comment]
In your case you can write your custom function 
https://vuetifyjs.com/en/components/data-tables/data-and-display/#custom-filter
and check if item with column "name" in it exclude it. or something like that

**Comment by titou-from-mars** [comment]
That's the impression I got when exploring the code: the functionality doesn't seem to be implemented. If no implementation is planned in the short term, perhaps the documentation should be corrected. How do I report documentation errors? Like a regular bug?
