### ISSUE TITLE
[Bug Report][3.3.15] V-select scroll bug (focus not changed)

### ISSUE THREAD

**Issue by GrinkoVeronika** [vuetifyjs/vuetify#18776]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
in vuetify2 for v-select, then I press any key it leads to first element, which starts with this letter, then changed to vuetify3 it doesn't change the focus of the list (countryCode is correctly changed based on pressed key, but focus on the list is not changed) .For example here was Yemen selected, then menu was open, I pressed  A key, and it took for countryCode Afganistan, but focus still on Yemen. When I close and reopen select then focus is on Afganistan. 

### Expected Behavior
How to make focus change automated?

### Actual Behavior
When I close and reopen select then focus is on Afganistan. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdWG1v4zYM/itCNsA5II577d2XrL3ry3rYgG04bMW+tEWg2EoiVJEMSU6bBd1vH/ViW7Kddm2/tJIeUuRDiqR7ux8pmWcXZTndVmQ0G51qsikZ1uTLHUfolKQFxUys0oUodmiLJcVcn92NNqLA7G5kQSFsTXBBJDrPGc0fZjkTigCabKgeJ3aVfGikENrvEVXXG0wZ+op+BEhVFnD1nJitOS4KSZRKPqBZeFiuBSdzXm0WRMLZ87O3IesY0bMtF1wTrpvbTwu6RTnDSoGJTrnF4FynsMBp7KRXpsmTTpeUsKLdRmib0iVo8d7cjeIzUESY5aF3qOg/hiGG5YrEJzOGF1bK+M7JY5eVEJ2FNhq3tilhijTeFemSkSe0wmV6HDlkXVKEkVyHm6HRuai4lrsrWMYGvmQ8aq624QJe+9KRg/6WuQHGvlkohbQ02hyMEtVFGECqqWbGII43vdssYItZZQBUCXtT754N4VVaSlGay/bxIUKPtNDrGUpOPh2VT0l8+tzVJYnJCO/XX5biP8kyRkWRgFjUjw/9YMw1JiBrzMSab+7oSDThXlBeGLYNegAFuG3KqNKpUdQ/beNFAljHI89RjdyjJNCZpvBu6JYkM2vrtKYYnZ2doSCH+kTVCRe70McMOBVRZqM/CAKYtyB16eiqxzDUeOjAJlGMKxI/Nu4MGx9KpSb7QtGhbAzE2gcSCoXv4ZBw+OoDV7OohHcPg5D1cymDZOrm5CF1AfOugFDBbVYcTFVT7qPUqGv3m+P01gi9i+QuvQeYMI3HEdCtq8OtIqyt1qw/nJNvqK291hD3xBge9YZOgKMWaFp8eoKs1SuJdyrHjHw+OupE8n817fmWSLqkOTZZYfmdrynXppeHug609cPSYcbEzoSrYBaIm347DJhiJbhqxUm60DyYcDSRmmK5uxv5aeaFOcaSYrsY5jlhkZ3GFtDcvajR2XLpiLCrC8fi2Iw+bvt7mynjwastZbsXrg5ICZ0Ptk0CwF6U57BUuaSlRoroqrQidFMKqdEe/f0blJJf7XNHSyk20BAqosGMjNFFlgvAcSBfZRZoG2Yje30JLNRi5w8fjzXJ1xl5EIKloCVdSiibj0I+ZGZADXQZwY4q113fp83JdhTewBv4Zh7u+3Q24pFaF4brny3Zk2h1CczHOxcuRPHmlUvmePMXO+3avXcZ67R0CLgSm4VYiKf3qaylY6W4pK26DFbxMcxLE/SIdb6eIC1gVIKpR/DfTYkmxQRx4PQGnkyYarGCShH4jrkRWAWpkFWaMpVpsxvCr1zpD55VIxF40keZz6QBPd8YXrV2QdVxXWwJ26mx3IpALQLT9ohIKWRt51loNzxteHE10pQbOC/IknKoC1Sr8a2vPhOUqGoBW8k9iNQCdnRqJL6b1dinXTM4z+pEREjvSjJDFxJqvU8pZERxxfQMQe05+4Ju7/3Js//ty1VPyyVkBcG8r2eJ4UMkUvLcWAwiU8i9sbXbd2MwMfDINhXwCJJjnEDNbV0NAjdwHA6c/vj62gBaSL/cAhKrHc+9795DUNM6ix8xxARydzpQra2xU/uNYU0xP65l+FhNTPAdfQF2Al2HUaOtmGNgjFeMeZLMk4YumK/RmHxorWgTCLY9zjLb9S5M70HnAjI9V51Y1FdOIaOKsafVKPB/HpzzOzx8jYatqSTQYHJywdg4SU02u+C9wnbYBIOPs1DzrHWmyUXk9vxw4RH1c7YRqJE16/24veW21++BGdBOOEHEeza8NfKnmWvUvmnrHSOIYb6CGUPlCr6okMpFSQrbws99+Ur+DTu2FVIZdHpN+UpldhpawFbyUyz0ajcwN3p1TtZHcOAfLLVzBVWQEzuoGPCvCiuD7J8wnUj3dTED7lm14f4Q/psxQ8fwJW7XjgFzIzg4ep6MTqYn008j9/vj59H9f4dE2N0=)

**Comment by KaelWD** [comment]
This issue is being closed as it lacks a valid minimal reproduction, please review our [guidelines](https://vuetifyjs.com/en/getting-started/contributing/#reporting-issues) and open a new issue if the problem still exists.
