### ISSUE TITLE
[Bug Report][3.4.3] Datepicker does emit update:modelValue when in keyboard mode

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#18775]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.4.0-alpha.1
**Browsers:** Firefox 119.0
**OS:** Linux x86_64

### Steps to reproduce
Start typing in the textfield

The update:modelValue event won't raise

### Expected Behavior
I would expect an event ( although I don't know WHEN it will be raised )

### Actual Behavior
There is no raised event

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkDFPwzAQhf/KyVMr4WQoEhKkCCQWJMSCxIIZHOfSRHVsy7FTUNX/ztlpaTvZ5/vu+d772rPRq/LZuWKKyO5ZNSrfuwAjhuhAS7NZCxZGwR6FAegHZ32APXhs4QCttwMIRpOCPQiTCGXNGEBF79GEFxkQ1gleGNxBKhfL5ZFso1Ghtwasecdd7hGUziXsEzCLWY2FtpuFYJzDK3RyQqgRDSipNTbAuWBJMvPnb4tJ6pg+P2pm4iBMVc4GyQ4VAQenqZvNVROXzuVrLhpqcNerLfr5jfwbFwMfbIOUyhZ/ayt9I9h1mxQVdlY36In6cKj6tlfQWj/IALUcaWuyrS05oOCuhwP+BJp6kzVq2FgcoUN/QXV9g7xDSeKnp/u0j+bZMI1ehHAee4ou2ZnRzyP5H/yJK+ccylMQVXkREDvcsFWxKu5YOm+LFfv+A6KXvDM=)

**Comment by jtuchel** [comment]
Seems to be a duplicate of https://github.com/vuetifyjs/vuetify/issues/18529

**Comment by KaelWD** [comment]
b50e9ad559fc4d958ff2f6ed7f873c3efcd592af

keyboard mode was not supposed to still exist
