### ISSUE TITLE
[Bug Report][3.4.3] Buttons and other active elements are rendered as black on initial load

### ISSUE THREAD

**Issue by ulfgebhardt** [vuetifyjs/vuetify#18773]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
When the page is loaded initially content is not rendered in the correct place yet. As this is expected due to missing css the black active elements and buttons are unexpected.

It seems to effect those components which are not fully calculated yet (active menus).

To reproduce just load the page provided in the repro - once loaded it utilizes client navigation so you need to shift-reload to reproduce again.

### Expected Behavior
No black buttons or other artifacts.

### Actual Behavior
There is black buttons and artifacts.

The loading phase:
![image](https://github.com/vuetifyjs/vuetify/assets/1238238/4a6a03e0-7bf4-4df3-a5d5-6d6b6461060c)

The loaded page:
![image](https://github.com/vuetifyjs/vuetify/assets/1238238/17c7f5fc-f290-4072-9c8d-83e94aefb839)

### Reproduction Link
[https://github.com/IT4Change/boilerplate-frontend/tree/2b162f84825ba78875a882f2716c15c86a22b4e9](https://github.com/IT4Change/boilerplate-frontend/tree/2b162f84825ba78875a882f2716c15c86a22b4e9)

**Comment by mercartem** [comment]
I have a similar problem
