### ISSUE TITLE
[Bug Report][3.4.3] Uncaught SyntaxError: Invalid or unexpected token when including plain vuetify.js file

### ISSUE THREAD

**Issue by mahozad** [vuetifyjs/vuetify#18781]
### Environment
**Vuetify Version:** 3.4.3
**Last working version:** 3.0.5
**Vue Version:** 3.3.9
**Browsers:** Mozilla Firefox, Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open the HTML file in a Chrome or Firefox browser or use the HTML file (along with its acompanying files) as popup of a Chrome extension.

### Expected Behavior
A Vuetify card component should be rendered

### Actual Behavior
A JS exception/error is thrown and nothing is rendered

### Reproduction Link
[https://github.com/mahozad/vuetify-bug-repro](https://github.com/mahozad/vuetify-bug-repro)

### Other comments
When using a CDN URL of the libraries, they work but when downloading them and serving them locally (like now) the error happens.

**Comment by KaelWD** [comment]
You need `<meta charset="UTF-8">`
