### ISSUE TITLE
[Feature Request] v-text-field v-label should not be created when empty "label" prop is passed

### ISSUE THREAD

**Issue by jandrij** [vuetifyjs/vuetify#18793]
### Problem to solve
In the case when labels have to be outside the v-text-field due to layout requirements accessability issues arise. If you create an outside label and link it to the v-text-field, an issue of multiple labels arise as well as having an emtpy label sitting there.

### Proposed solution
Check if hasLabel.value is not empty before creating the VFieldLabel here: https://github.com/vuetifyjs/vuetify/blob/a47ec9af018693bc95d06304521fe04ca8bf40b5/packages/vuetify/src/components/VField/VField.tsx#L296C1-L298C27

**Comment by websitevirtuoso** [comment]
Does it make sense? what MDI specification says about it?

**Comment by websitevirtuoso** [comment]
If you provode that this is really importan and give more details. I will be happy to help and even create PR
