### ISSUE TITLE
[Bug Report][3.4.4] Can't close the chip on V-autocomplete 

### ISSUE THREAD

**Issue by devcoder111** [vuetifyjs/vuetify#18796]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.9
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
Make v-autocomplete without multiple props and add closable-chips

### Expected Behavior
When we click the close button, input should be cleared but now it's opening the listing
And close button cursor is not showing.

### Actual Behavior
No need function

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9WEtv4zYQ/iuEL06AyM+kRYUk23QLdFGgu4dN0cNmD7REW9xQpEBSdlIj/70z1It6bdztwxdL5Dy/Gc4M9ek4MTqa32XZbJ+zSTi5tizNBLXs9kEScr0PIqpjfCQkFIrGXO5uHibc/J7F1MLLw6TYjJRQGnY2ImfBTrPnIKb6kclgWVMIagxQpE8Bza2qllP6FBx4bBPYulwtimWnHNRXxpB9YISyzgKGao6Em7vI8j0jLw+TktzZm2kF6o0JBJeM6moHzKeO3llfsFYm+PYDLxgt+C6x8L/2SRKGq2imv8plzCzTKZdgZ7V8ez3vWVL5NPcQLpf2AU93FW+k9qw2u9a5WpTQ4A9CBkuJtZkJ5/Molhg8y7fPX8wsUumcp3THzBxDZ+YYh2DDaJTMvmR1vHzItDrU0ckoOl3vFimgBOKD28tVa9Ntp0zm/hIhQkWQHEpiPihrVUqMpdr6sOFPab7jSIQeC5p1962m0vBSkBE8ZsFz0Cy2yVtWDaSOiz61LshHArHJTCt1PIc2tgyM/4NlCDUihKxdU10mRM7QNOZBrKwJwCnLIyqGaGOGTjwDOcRrq7SlG9HKx1ot1ZxKzACr5JAsl2pgcdf/fpp5HgpuLJxnyEsM6pYKA8qHoEDCgIOovmWWW4GnyVWCQdt/jASPHlvlgtxAVPMBaudGra3nTLHXzjxYxNTzcxWWIFFbHhf53c1Zl9Jlylv2ZIOISTjFPRCuk3WbLrkCmuORSJpC6Xm5nifrPsAmo7LN5ipiVVWgJKIIB6CTgfQ93wpH/BXfj/Y7vkEJ8SsKJFUDo/NYWgoBr+qQd/YxGYt6P37oSYq5/10foH3gHNxyJso+4Z+ZVMVMACPC1Q96GHODiY+i+y2l+fWbSwUlWNYlFnTjVL4fUOmyrLF3BPP/FAkX9f8Zivshnf8GFn0IsLVDScsENMVxELaaMxkPVNFTYQixSrh+xRToGsAp4VClu4tCOenB8O7fgRb1B1UJHM5uR7KnIG2UpArQRyZY1OuP/YLcbWroR9PPLpzKwa5WBA+o+xuntDYAPNMsg5gFFJooRZhQ10zTw6xYGWHDBPOJh3EosxEN7Ds93skGEEFFpyPylfb2T2B5g66+eQWYMnc8+jFsgNrkmwGGnVZ5b2p6tZt2IO02Wv8Ef0NT6vYZXCt7Ud2bYr6HYU47K6tnbxvn1gDnNSWN38LMgdsoadQ39QRt7s8hrxeT+k5igwVJTfugD18JWiStMS4Dk1v3BRxY4XJAufBqTXXk78Bk0rXZIVK46SU7ug7CS8DKx9Z2a2L13R4B5ms3OUfQjJ3e7PaGTN0QOiUhyeHas4Uwx0OI9Sto6yJVnRlvYM57Np4yPHqpWDhJ3quDn4zNXOxSs5tX1SK8dKrMtYk0z4qBkz1lMKBDrLc0F5YcC4Ggjp6dV2/ou4SZGm5mBsysVwlZhmT66k0Nj6qZL/GCNr1oeFen8666vOvTeddd3svTeS+7vFen8161eV+alNbM5lr6MDaJHLok8DSWw0RIPk0/UhlrSu5imprpBZn+pLm1lLxTwk4/eyxNToXE3X68PazC4MNvPJaYvOStZgffwWLiAG1+bZzPyf2Hnz+EpHJ9x22Sb5zPNQLV05wbkwMKy6vvV8uOlCNc+fEbB1jwC1Z3spySF087AYrSwo6zrhl4bBek6D+hS8pPy89jcu4EJ2+VlEqfIGY1KuZes73S5B1cz5l8XdB6XFAePTJNPqYA4TcY5EAsu0qRK0MEHZRXoyj7KdQ1ZtU15nLUqV+pZIVL5HUxV+NiVCJHkOlJGY94mTl/cCH4UPL0RHWC5R8lN5Zg1BJGTJ6mELkNNMw/mX9mLE+Zym1IZC6Ef+DdHywUTwcKjS9sjn1zTM9gjvaKLXZu+KR2X4g9swk3s1LHuT8k8i3pcYI1HjkUa8NsJQgK+s0tKeS1+o4rEucXZL1YLEBDJan0oPCh7UvKbKKwKtWqNUvhQ9cZTmRtV1znwO+IT9jhUHdZ0mZu8cPW8bjx0NONvhVMtzdkcd5mNBl0T9CF+xdkWbP5djrz4eND1ekmLxeT9Ww9+2GC/5ezy8nnvwDRPFeA)

**Comment by yuwu9145** [comment]
Simplified [playground url](https://play.vuetifyjs.com/#eNpdUEFqwzAQ/Mqii1qI7UJyCk4gBNoPFHqIc1DsdSKQtUKSTUvI3yvJDVF62xlmRpo5XJmzbbUzppxGZGtWexyMEh63jQaop0IYk84EWtJeSI32j5oVo6eWggs93mmA9iKNe8CpGKhDtWmY8yG9YZlSkRMnhcU/ixKnZNjl+ZlvLcNfXRAc+F4o2ZPVUvAF8D0psqKjeL+HU3aJ/kCy51nxid/CxePrhwapz/z4CN7W1XOne/1AP/dPwjRPXWWzBehaK40Hh36c15ODIevhChZ7uEFvaQAeFudRHiYg7YI8LgObqHnJK73GB+bIEMZuC7YsV+VbIZS5iHLJZrxix1/0WZHP)
