### ISSUE TITLE
[Bug Report][3.4.4] v-data-table-virtual multi-row header is not correctly displayed when fixed-header is set with density compact

### ISSUE THREAD

**Issue by Tobias-Doerner** [vuetifyjs/vuetify#18795]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.9
**Browsers:** Firefox 120.0
**OS:** Linux x86_64

### Steps to reproduce
Usa a v-data-table-virtual with a multi-row header and the fixed-header property set. When using density='compact' there are an unwanted spacing inside the rendered table header. The issue occurres only in v-data-table-virtual and v-data-table is working as expected.

### Expected Behavior
Correct spacing in the data-table headers.

### Actual Behavior
There is an unwanted vertical spacing between the header rows.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVdtu2kAQ/ZWVX0gkMAaDuYhUKgSl90ZJ1ZeQh409wCa+ab2mpFGk/kM/pX/QT+mXdHZtxxvHSaESEvY5M7tnzqx3Lu6MhLvt13FsblIwxsZEQBD7VMCrRUjIZNOicawe1YsbhYKyEHgOKdCjgrYEvfKhtWFcpNQvSELGa6Ae8ORoYeRPC0NjGe4mOfWvMx6ECRO3SLlREFNX6OQa2GotkOv0LR2Xq7RuQGaFNIAqlbRi4K2YrgAD+jq7ZFvwWssoEsCraCa7QNuFF+2qGRLJvJq0NQ/xNXE5iwVJQKSZlSyIIy7IHeGwJPdkyaOANND+hgwnBNdNBBap7CJHMurgItv2jggmfBiTxuktpwHzGk2yoX4qEVlyg9w3q5EfIpcKFoVaqF9ANeEzuTtPXcmTYyxCy1PKck5RZX5hULHMMQtkCzGhkYcQQn22CuUyEKLRJe6ume9xQCov87GiN6rd5CA41KRkZ6AU8DhlShOoJFwh9Fz418hPA5nw+5eeslGwnnSZP2XI5aHeMHXEKu0q8mRvcMETDlSQvHUkWpIT9p2WPhRtwcj56jYWJZNVi3in55hOicuiEO3altkr0Uy3xPtDuzvsa05XGiibYRIMs/78+NntOxaZzoroJ63Ni9Dkv1/TJccDsk8BtqNLLQro9E27poBObzDo7VLAYBflZ+AV5u+n2apR3LXq9DpWdzjaQe9oF71T/E7+U3DH7DyR3BkO9bNTiu5aljPSynlGtGPteTzEGsh5ihdPjfSPsGVuVKPd0dx78FrDNNn2wBoN/ikbVc/mj1XLD3fSzu5lvJGNpiESzF6ylXmdRCGOQVVVNnyYD/xzLBfFCTUu6l0Y1Pejb+8UhrtCvgHmrMG9qcGvk63EFsYphwT4BufTAycoXwHOOEnPzz/BFp8fyCDyUh+jXyDPIEFbpMYsbJqGHsrW4pTat2rwsHD1JZlvRX4/F0JlZGbPwsBhNHuh9FKubdoqbxHiz7hvGgiYIzTUNntmz7j8C0rgc+Q=)

**Comment by binair-io** [comment]
Still valid in latest version of Vue & Vuetify.

Problem seems to be located in this line of styling added to the column element (<td>):

`top: calc(var(--v-table-header-height) * 1)`

When removing this line, the element is displayed as expected.
