### ISSUE TITLE
[Bug Report][3.4.4] Vuetify date picker closes unexpectedly when used with Vuetify Menu

### ISSUE THREAD

**Issue by shabab477** [vuetifyjs/vuetify#18797]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.4.0-alpha.3
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- click on any whitespace in the datepicker
- also can click on any year after navigating to the year viewmode through the controls

### Expected Behavior
Since `close-on-content-click` of the VMenu is set to false so any click in its content, i.e, the datepicker should not result  to close

### Actual Behavior
The menu content closes even if the `close-on-content-click` is set to false.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUctuwyAQ/BVErsVpEx8qy63U76h7IHitohJYwdqqFOXfu7brB1JuzOww7DCfN5miOX4gFkMPspI1wRWdJnhvvBD1oDTidJyACZ609RD/qYm8gu8XKEQVELwKXnXB9OmtkRR7aOROYFxIMCpGN/CkjLPmh5WddimXIsRk0yh6YERR+2TJBs/DZLQDtVGbcF2Vl13CiYM2ZAdNIfLdm8AYMIl7I3fiKRvBL6nOgmvFoC7WtyyfxCytj/v5/plj9omrWcuMQs4KUfigyJIDYYKbljicytNL+dpIUSUTg3P64mBNnblnTlsTzI9VLG0xzOsambnNbEGG/KBFEgmoR441Qx7J+5M8F2XxrLTDb12c5YxL+fUHtsew0Q==)

**Comment by ipanamski** [comment]
> @davidstackio thanks for the suggestion. It does look like working in most cases however the menu now doesn't close after a right click, clicking anywhere surrounding the menu pop up. Does look like a bug to be fixed within the `v-menu`. [Playground link](https://play.vuetifyjs.com/#eNplUkFu2zAQ/MqCPUgGTLlAchLsoAXantpT0FPdA0OuarUUSZCUU8Pw37OkpIhBfLDEneHuzKx+XVnwcvfZueY8ImvZPuLgtIj4cDQA+zMf0IxAD6tQH45MEfSDSkcGrdQ2ILeGS2simsil7uU/InVCBzyy3IKaLC3hg5CxP4toPZGu4Lx1AW6vxDwv4v/Iux61WopQjEejvlCnbxlnK0OLp4x/NQqSxBLzKJQ1+lL2e+qNInpWsHIf9rtSwKJ/9yaTrDLN4I7col8uryI76wdSKZpZ7TpAWp29O98Pwl9WIJzsMxfqr5Apx4HyPIUF+zS6NK7N7flZ6BGLRcAB5rgnfvZQyJv2SLW0SDq8cUPHIH3vIgSMo8vcfnDWR7hSbt2WFA9ujKjgBp23A1T0mVSJRjsPERarpILo9XXSMPtuweAzpLd6s03IbbPeLPSnm9lDAZeLJsoio643cJjX8BpzjmQJu4n2u5VCYzo8Rt+bP3WFhv98rLYw6wO4oPAtVGYc0PeyyurSLydPAO3Dx7WsxOU9e3JDf/vdFCLpYrctu2vum49caHcSzR2bzvfs9wtzYBfC)
> 
>  Screen.Recording.2023-12-04.at.17.02.52.mov

I worked around this problem by using **min-width** on the **v-menu**
