### ISSUE TITLE
[Bug Report][3.4.4] Checkbox label text is greyed out, which doesn't match the Material Design specification

### ISSUE THREAD

**Issue by ldavisCEI** [vuetifyjs/vuetify#18804]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.9
**Browsers:** Edge 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Go to https://vuetifyjs.com/en/components/checkboxes/#usage
2. Compare that to https://m2.material.io/components/checkboxes

### Expected Behavior
Label text should be a dark black by default

### Actual Behavior
Label text is a greyed out, disabled looking color.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQRDAjNTk7Kb9CIScxKTXHNkbJGSoQo2Rno4+QhxkDEkIxByQCscZGH269Uq2OkrGesZ6lEog20TNRigUAJx02gw==)

**Comment by korggy** [comment]
Can someone tell me why this was closed without comment? The text color currently used for checkboxes is confusing to my users and does not match the Material specification.

**Comment by J-Sek** [comment]
It is an automatic process, as visible above your comment: "_github-action [bot] closed this..._".

Link to [MD3 spec](https://m3.material.io/components/checkbox/specs#5d746841-f46c-4840-8d82-be01e7bfafef) matches with your request. There is no point in this label having 60% opacity.
