### ISSUE TITLE
[Bug Report][3.3.21] Return object is selecting all the values with same name.

### ISSUE THREAD

**Issue by sahiln1** [vuetifyjs/vuetify#18801]
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.0
**Browsers:** Chrome 119.0.0.0
**OS:** Windows

### Steps to reproduce
i am v-modeling the object to a variable. In the autocomplete when i select any item , those items are also getting highlighted which has same name as selected one.Although v-model is happening only of selected item. But It should only highlight  the selected item instead of all those items which has same name or title.

### Expected Behavior
It should only highlight  the selected item instead of all those items which has same name or title.

### Actual Behavior
It is highlighting the items which has same item title as the v-model one.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUEFugzAQ/MrKl7RSACVwKaJIfUOPIQcDW9WVMRY2qBLi710MxHCI1JN3ZmfHu3Mbmemq6EPrcOiRpSyz2GjJLeaFAsiGgGvtSgeqVlkuFHYrtSh621YtTaHFjQZoemkFcZ6RvET5XrBPlFjZgvlOKuhXQy337jtD0LS1mzJuCut9t/oW2njYoe07FbTlz+z/oGfTwAorkWwUb9Bb5Fl03N/fZTRX+Thu305TFjlqzYLmjmE4J5dVFu0yzEzVCW2dBH9121mo8YtTODAuVjW3/OV1Q9sVHgNsO6SgeinPx8tMCjfPAIwwn5jCiZ/OQGeVtOGMLgQFWVxg2jk8119X/fWf+njVx8/05VGfrPrkoL8/6mkpliYBin9Lkk1nFodx+MbmNwkTdv8D60rN9g==)

**Comment by KaelWD** [comment]
You still need to set item-value with return-object.
