### ISSUE TITLE
v-select autocomplete does not allow space to be input until the menu is opened

### ISSUE THREAD

**Issue by jachien** [vuetifyjs/vuetify#1880]
### Steps to reproduce
1. Open https://codepen.io/anon/pen/eGgvaE
2. Focus on the input search.
3. Try searching for "United States".

Note that this is only reproducible if the menu has never been opened, so you will need to reload the page in order to reproduce it a second time.

### Versions

Vuetify 0.15.7

### What is expected ?

You expect to be able to type "United States".

### What is actually happening ?

You end up typing "UnitedStates".

You cannot input any spaces until the menu is opened at least once. This seems like it cannot happen until items has at least one element. If the ajax call that populates items is slower to respond than you want to type a space, then you cannot type it.

This example simulates a really slow ajax call taking 5 seconds to respond. If you delete the body of querySelections(val) (such that items never gets populated) then you'll see that you can never type a space in the input.

### Reproduction Link

https://codepen.io/anon/pen/eGgvaE

### Additional notes
The particular problem of being unable to type a space seems related to https://github.com/vuetifyjs/vuetify/blob/v0.15.7/src/components/VSelect/mixins/autocomplete.js#L27

```
    onKeyDown (e) {
      // If enter or space is pressed, open menu
      if (!this.menuIsActive &&
        [13, 32, 38, 40].includes(e.keyCode)
      ) {
        return this.showMenuItems()
      }
```
Personally I don't think pressing spacebar (keycode 32) should try to open the menu.

**Comment by johnleider** [comment]
I agree with you and think we should remove it.
