### ISSUE TITLE
[Bug Report][3.4.4] VOtpInput displays custom loader even when loading is false

### ISSUE THREAD

**Issue by WarpedPixel** [vuetifyjs/vuetify#18809]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.8
**Browsers:** Safari 16.6
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just create a v-otp-input with a loader slot used

### Expected Behavior
Loading not rendered until loading property is set to true

### Actual Behavior
Shows immediately. And in each in of the input controls (not for the whole control as the default loader shows)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplj0sKwzAMRK9itK6dQrIKodBztF2IRLQGxxa2kk3p3ZtfS0x2modmNLq9IcW2uDKbcSCooRHq2aHQ5e6VakaNzMu4iDZ4QespbmiBQVhbz4P84YR/MWrUyQWpXcBuZ9usHMMzUkraTaEYlfUdCcXe+rlBUxw29ieKrOqKjm1mlteeyfpVFgGfE5SmMmeNjl9oSlh1BY8vVDRckA==)

**Comment by shengzhou1216** [comment]
+1
