### ISSUE TITLE
[Bug Report][3.4.4] Floating label animation is not smooth and appears to have a jump effect at the end

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18802]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.9
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Kindly refer to the provided playground example to see the effect of the label. Simply click on it to view the changes.

### Expected Behavior
It is crucial that the animation of the floating label is smooth and seamless.

### Actual Behavior
I noticed that the animation for the floating label is not very smooth. Additionally, there seems to be a jump effect at the end of the animation.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVcFKw0AQ/ZVlzjZBGwQlFrx4VRRPxsOaTHRhshs2myiI/+40Dc2mpFBKDk1PyXtv9oX3yDJvv1DZNLwvy6CpEW4hdliUJB2uEi1E3CxyY4v2vUWp0U4qjbajWtKa7y3spqjHQjCs7hK4vErAp6uCyeshV2TMRT7nObfeDn/cIldImS8IQfIDiQ8/42dN0g5theBMKX4ZytDy0FOPhoOrOPQ/4cdigYMwczJRXwyZ3ZyNtEpqx2o1op5jCw+KCLMjk/qF5SNGs2risXbEd3OKLsyo1aza4JxKT1AFH9n1mVUPr5rjTfVf1HvMDmmkx/3C2Kj+Tlkz3c6Jw+0ygr8LWAbL4AbWzyiI4P0fH2vEHg==)

**Comment by KaelWD** [comment]
Looks pretty smooth to me
[Kooha-2023-12-07-18-09-16.webm](https://github.com/vuetifyjs/vuetify/assets/16421948/af113289-66f3-4917-b0de-7d8a05b71d7c)

**Comment by websitevirtuoso** [comment]
look fine. don't see problems. we have diff but this diff because outlined transition take more time because we move label a bit higher

**Comment by KaelWD** [comment]
Looks font rendering related, not much we can do about that. Feel free to open a PR if you find a fix.
