### ISSUE TITLE
[Bug Report][3.4.4] VSelect auto scroll on keypress

### ISSUE THREAD

**Issue by akkashk1** [vuetifyjs/vuetify#18818]
### Environment
**Vuetify Version:** 3.4.4
**Last working version:** 3.4.4
**Vue Version:** 3.3.9
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on the select and then press 'z' on keyboard. After pressing 'z'  'zeel' will selected but auto scroll to 'zeel' is not happing like native browser select.

### Expected Behavior
When we press any key on keyboard then that option selected with that auto scroll to that option.

### Actual Behavior
Current when we press key on keyboard then that option is selected but auto scroll to it is not happening.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1mu1u48YVhm+FUIG4BWxv2+RPjU0WFEVJY484xJD0rpvND9niNkIlS5BkZwPD954zw69zyFcIAu959BxyON8c6de30fHw9CHc769fX8rRzejjqdzuN8tT+cvX5yD4eJ+Vm/Lp5P4dBKvy+bg+/fnz19HTbrtfEh5VH2yWj+WGcPbn9nG3aejNmq51JLx8Xa5J2ZRmf1rvno+T5WnZSK9X293KJx/9ncpVLTWCu8jVaX3alOScyu/tTf0Hr8vNi/vA/21vvC2fX672h93e3f0t2C6/f16vTr/fBP+8DJYvp91NcDq8lJdBufxfeaiC4L3N9tTdjHAFfV1QbTR1E/ytKiyVk7yVf5zaIWu1fv3l7S1w+NO1K+Wn68Pyj0/XrvDB+/vHD06or/hBVLe4hcvEVw+eNsuje7Tt6erfX0dUh+tvtSlu+Hu5XJUHlkzpj23y/rtLhiWtEn1ZH7s7s3K7nqHXx5OiHF6af/nSlJtjSX8e18+rtli+Neh2dJk2E1cCCVWno0h8ROHx6bDen4JjeXrZe3m93e8Op+AtOJTfgvfg22G3DS6oJ184PQieqCOdAtT/gp9dyt9/rYrwFvgOdBM8v2w2l4FrqZvgIt2US3qSqq2DZbCr0oPn5ba8CN4vm9yquihBPa/K7/yT+kLjMLlL1DR/uLhsbsTY0O+757ypSvpqi4b2Qk2itO8ziJ4oO+2e/n8EFwtDmyuVTNilWgTs8ZiLFEHH5JSuQqk2EGVEYaryUIuEhiF/aqXrYuBFEbcoAs4kTFSc5Fxs0Bk7NTbP+n4FQYa+ixdc9jHwFuPiNoyk2zLgp0ZrMzdZyhM6eC4jf7DxIMNDkJHNzZ2OeTdrEbJVmKShknXZQZSRW9noFQBmXgjPhcAq3GDkXgWQaU06D+1C9NEOgowvKutfvUFoorgNb6/CIjdipmjhmQwa9Nl9P6OCMIM+CpOItyeDKEPfWZXJ0c4gzLDhIpqrRGY0EE6Rk3mYjEVNMYgn1XFozYS3BYMoI6ceJSeYjgE/5p3HRcixs7jfexkEGdRVwnxq7IxndBBn5Ir+F8XpIMqQRXchsJSJjGihCgDTZNFc56L9GwTsNBJ3dyGwLE3TtFiJ1mgZ8DMzFZXs46EXUYfhnaiKoUddfm4WfBwwCDLmNLPqaWx5MRhEGUaHdEHh1wjYKtW8NqoYeCbU/X7cMeS7jiUesybI1amYW2uAzCQyVpgeINOaBQ1l0ScZBBn0WZqLvtkiYBd8d+Ei5CwWNCHKOYzBYcYkHBf88aoYeboavcJtGPBjmhruklxcu2XI13lItcUX7I4BX92rTIe8SlqE7C+imqsYeHrKLYqAY208mfBlvyFDN1bRPLYLw2utY8DP6HHF9qkhwP2iJrFs6RaBTXQ8iWn3IFceBocZs1DxnuxDYOk4WYSWX7VFwF5YlUwtH9ItAnYy5VtUHwLLTGx8G/GO06Jzdkp7mYHvIciwYVLomDdKi6CdKb5NrQEwi9tZmMnlpmNDfy4mLBch5z7Wmhe1IcCNdB5Hc+7WBLiTaUSbGu7WBLu9vWCLsK3VlE/bLQJ2TPOjyWn95n4HQQYNh1BLv0HYjkyaxnzaYhBnpHFu+zeoGPaLROn7/h1qOMxQ40LPs5lcXxkEGRH912uCjp3xZ6pvEznjprbQA72CIGMS8/HuQ2SJse5DbE2VzXI+7zMIMuIvXKUIODM+slwEHNqjm1ys7S2Ctuq9rrbojE0zJl8lOob9Ge9wNYBm4RZ+sVVk8ExGbj6LEcAgypjyxdCHwDKieSkCThqFcklvCHBtlIsr+hh40oLOrZ8QMtm6DIKMO2pJeS7SImBnn+k68uoNAnZBG21j+LLQoqF9Z/KQ3gXFWO/Y0NchbXTzuaxmBlFGYQu3r+LLCoMgg3Y4/QmrY8Dn9UgBMH7Ip3ylqmJ0JbH2+hBZYovlQ2AVqXwCH4MDxzAJ07Sgl35+4NhBlGGVWJFqAM0i5zNtDYAZTWh8an3Fi8wgyuAzo4uA41YxOgRTvL4YBBnTjPdzHwJLzLguAs4PokIpgo7sZjUApslpn5CJt4COAZ/OujL52DUBruVvDS4CTpHPjcl7pe0gOB4Pc2WSUBe8GhhEGQUdVgnbA2Te0zytC/FmyyDIiLNc9143Ogb8xYRPvD4EVp4Ky4VDy9BJk1FWiyN9BkHGNONN50NgJTN+dx8OrTSc9Z67IcAVk7yLkGOpG+Vy9WAQZdCAS2Lp1wjYYiPlIuCoidLKfeXA1Q6ijL58xkv4wuIi4Bj9EIkFqCHIpV3HzCpx75YB/55eJw2f2RoydN05rZG7tBYBe6x762xDgBvTqxQvcg2Qqek7AHFK3aKhncl3ch8Ca6yi0PLbNwS6vdevhkCXz14+BNbcxrGs1RZBW1Gly3mRQZCh3D6LD++GAFfMzC4CTpEMvuzoGPRz/jVEFQPvIZnFiajZmgzdnM7n6VSI11mLzthmMbAdOmcnmVhHGMQZ7oXa8kpmEGf4UdlLqBj2+1vijgE/EkWhCDh0dCEe0cfAc4fv3PMx8Iyl9cj1Ai53EGRYOalXMfDuM1+TXG3Q0Ka9PxNdBBxNXw3SABO7SgZBRiquStHQuY8nXPIhsAyd0vLmqcHQ/ExnBLyAVTz0/is7hg+B9UAvpb25q2O1/9s/uh9I9H56U/82wv0WgqSPH6pfXdDvLUbvl6Mfr3+8/s/I/f3p+qfRb38BjZlGVw==)

**Comment by shengzhou1216** [comment]
+1

**Comment by prempopatia** [comment]
Yes, I also wanted the same behaviour when the user is writing the name of an available option in v-select list and that particular option gets highlighted in v-select. I guess that currently,  due to the virtual loading of the list, it is not working as expected. Can we have a flag on v-select where we can select the behavior, like whether we want the virtual loading of the list or whether it should be working as normal select without virtual loading?
It is going to be much helpful for end user also.
