### ISSUE TITLE
[Bug Report][3.4.4] data-iterator navigation

### ISSUE THREAD

**Issue by johntom** [vuetifyjs/vuetify#18819]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.10
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
1 I copied first example in data iterators with navigator but can't get navigator to work.
2 I'm using the following and selected vue 3.3.10 as there is no option for nuxt
"nuxt": "3.7.4",   
    "vuetify": "^3.4.4"	
	node  19.7.0
	Edition	Windows 10 Home
Version	22H2
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Expected Behavior
to have navator work

### Actual Behavior
 navator missing if I replicate example

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1Uk1v2zAM/SuvviTZbGdBu4vRFiiKHQrsHyw7yDaTEbUkV6a9FoH/+yg7TZuhvYgS9R4/HvnrkHShWt+1bT70lBTJtZBtGyN0u3XA9ZDVRkzGQsGIDyj0ZrubbTLZbYKiNXvSdzTbZCIp7TUIhqxrvBQ17UzfiOIOmJgYT+Bz+M4HRS0jKAWvwG4mxFSP9BIzv2NOFVYm1Mos2dXHwvJg/irqej1/KvwdoQxYv6Ven/X7keMiy+DoWXCqUmtyXqKhZ6M+QtkLHtRRNX1NNYxErCDLPhNk571KOumBKN29752cizJk+sHOCHuHoiG3lz9HoSf0scE30McdRMzZDNV7BtFnVwVuZYKzbX0QHBBohxG74C0WuhqL+EnP0+dxmjjMCWP0AssVbm6xPPrmrgps0tf3NMUCdyGYlzyGXR4wN6Wo7xhTLB9TDP9FAYSl0UCLB+Vjga9YDviCjV42q1NwhemEFPXTB4Vx2/UWtW90YzsWGEuCyruOKiHpA0zNLXdcsduDGpYc995aX3MK1Ui1JG2yZOEOT70e1AkaU2pwDL7pW1FQ2XcX+GGeekLVt1yzOgmWHVuT6gpABa5IrXgxuszW7B3PRZGNrIEcG6u7FR8qbPBouCQ1gYLW37v6LR3Zi8Wp3XH12vo4X8Y409MUkzFNLvPLfPMtiZer/Cr5/Q9j0kOP)

**Comment by shengzhou1216** [comment]
You should bind modelValue to `v-pagination` ,  so that the `data-iterator` can listen to the `navigator` 's event.
```
<template v-slot:footer="{page,  pageCount, }">
      <v-pagination :length="pageCount" v-model="page"></v-pagination>
    </template>
    ```
