### ISSUE TITLE
[Feature Request] Carousel - Contain Image above progress bar

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#1881]
### Versions

Vue 2.4.2 - Vuetify 0.15.2

### What is expected ?

* Contain the image above the progress bar at the bottom of the carousel (possibly inject card here for media contain and title and card actions)

### What is actually happening ?

Currently the carousel is very basic and really only allows you to change the icons inside of it.

### Reproduction Link

Current Carousel
https://vuetifyjs.com/components/carousels

Link to another framework carousel
http://element.eleme.io/#/en-US/component/carousel

### What will it allow you to do that you can't do today?
 It will allow you to show an image that isnt covered by the progress bar

 ### How will it make current work-arounds straightforward?
Well there are no examples of doing any of this on the main site so I'm not even sure there are work arounds for this. 
### What potential bugs and edge cases does it help to avoid?
gesture and event based bugs for sure and css related bugs trying to hide certain elements to the existing carousel

I'm not really sure what other information you may need so please let me know if there is anything you'd like more input on. I originally removed the bottom part of the boilerplate for the ticket because the directions for feature requests were a little hazy.

**Comment by jameshhood** [comment]
breaking out issues from #1617

**Comment by johnleider** [comment]
I'm moving this to v1.3 as we now have a very clear path forward with this component and its siblings (v-stepper, v-tabs). With `v-img` being done, we can start to look towards implementing this.

**Comment by johnleider** [comment]
With the introduction of `v-item-group` and `v-window` this will exist as a userland solution as `v-carousel` will not be receiving any updates for v1.3.
