### ISSUE TITLE
[Feature Request] For when the v-calendar in vuetify 3?

### ISSUE THREAD

**Issue by cvaroregidor** [vuetifyjs/vuetify#18816]
### Problem to solve
Hi, will the v-calendar be implemented un vuetify3 and if so, when?
In the roadmap it only says: "Q1 Q2 Soon™️ 2023" but we are in Q4

### Proposed solution
We used in vuetify2 and miss it in vuetify 3

**Comment by blalan05** [comment]
Duplicate #13469; There is a PR under review #16803, it will be in Labs "Soon".
