### ISSUE TITLE
[Bug Report][3.4.4] Cant filter on v-chip-group

### ISSUE THREAD

**Issue by altsniffer** [vuetifyjs/vuetify#18820]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.10
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
1. Select a few
2. Use search to filter v-chips
3. Select or Unselect one more

### Expected Behavior
Selected array should not clear / remove ids not in filtered list

### Actual Behavior
Only visible items are listed in selected array

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVNuO2jAQ/RUrLwRpCWyX3hBB2tJKXalP7Up9WPbBOJPEquNYtgOLUP6941wa0uwGXsh45py5Hfvp7BnN5vdKBYcCvJW3tpApQS1sdpKQ9WFGlao+K4Pl0lIuQTdH1aHOjxtiQACzEK3I+fzPIGW5ntcB/8W3ZnVg4cXOYg4iIodZlkcgwp1ngGqW7ryNY+giOqIhMUu5miU6LxTJCmG5EtAjrItCyl52h+oOCCLiXGM8x0kQLknMhQUN0QPaZuddhq4OVBTQxAYcqXveP3B6y8dyUSVRmmdUn/rODY6wQlX0zRD7ZfbG0PXdbsod9lblTupNrucXG0bTMM2VxZXZBs4zlWtLzkRDfIOFZqqoVklinWdkgjKZOKDrQRoHbHYdOoA/mUwvfW6Hr3lce6ZxPNVFn9uWOIro9qa1qhmsyORXYVw/dM8Ft6dJ4y+b/x743QD8CCyVOPJkHHg3AN5ry2POOBXkQVoQgicgGYyyLAcs34EKmxIqI/IbOSQYM8rwfsDwEyQc6R4F/Q1XeqWNDwP4V55wiz08aioNyjujludylOTjgGQrUKsWyDalMhkfwafh+hRlWPyLQt1fT/55mPy0B22AFfra9m8XA/AXnts3FPCMouxk2bvrKM9W/b4/JeGmzcNj4tfSrm9oIEAmuN8wDMli2lWj8U5pWWu9jmwyExAGxuKCuhC/eoPCi/eqexYCm//Ij6C31IA/DbhkoojA9AvrxVTXz/2aj9L9lWis5/UjgHm88sa7C5bBYkaFSmmw9Gp76T3/BRvY2U8=)

### Other comments
Is this a bug or is it somehow intended that you can filter a large list of 100 chips via a search?

**Comment by shengzhou1216** [comment]
Maybe you shouldn't update the ChipGroup's children.
