### ISSUE TITLE
[Feature Request] Carousel - Hide Progress Bar Flag

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#1882]
### Versions

Vue 2.4.2 - Vuetify 0.15.2

### What is expected ?

* hide the progress bar all together

### What is actually happening ?

Currently the carousel is very basic and really only allows you to change the icons inside of it.

### Reproduction Link

Current Carousel
https://vuetifyjs.com/components/carousels

Link to another framework carousel
http://element.eleme.io/#/en-US/component/carousel

### What will it allow you to do that you can't do today?
 It will allow you to show an image that isnt covered by the progress bar, incorporate gestures into the carousel. On Mobile mode, you may not want a progress bar

 ### How will it make current work-arounds straightforward?
Well there are no examples of doing any of this on the main site so I'm not even sure there are work arounds for this. 
### What potential bugs and edge cases does it help to avoid?
gesture and event based bugs for sure and css related bugs trying to hide certain elements to the existing carousel

I'm not really sure what other information you may need so please let me know if there is anything you'd like more input on. I originally removed the bottom part of the boilerplate for the ticket because the directions for feature requests were a little hazy.

**Comment by jameshhood** [comment]
Break out from #1617

**Comment by jameshhood** [comment]
this is already done in a newer version but could need a little rework in order to hide arrows as well

**Comment by jacekkarczmarczyk** [comment]
Docs, example 4: "You can hide the bottom controls with the `hide-controls` prop."
