### ISSUE TITLE
[Bug Report][3.4.4] VDataTable fixed column  width is invalid

### ISSUE THREAD

**Issue by Warnier-zhang** [vuetifyjs/vuetify#18821]
### Environment
**Vuetify Version:** 3.4.4
**Vue Version:** 3.3.6
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
just open

### Expected Behavior
set fixed column width

### Actual Behavior
the width is auto and background is transparent

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1v2zYQgP/KQW1hG4sZ+TWJkRQo0nXLOmz7OiQBSku0TVSmBIpy4xn+7ztKlEhLXL2i/WJLx7vjcy868vEQ5DK6fJdlZFewYBHcKrbNEqrY2ycBcLsb0iwrH8uXKBWKcsGkEZXCmCo6VHSZsOGOS1XQpF4EWGwYjZnM754C8/QUOKscd9Nrxu49y3Mm1YlOlNBcq7CE7ajiqRiO3OVc7ROGy194rDYLmIZh9uKubxhfbxQq4IorX/EXFg8rJivVPMMdTQrtUtAtsyZNxBhznSN4pQ2ISFH7wEXMXi5KF/grFJOCJg/lW+nx+BQ4PgAOaGGVSGkOP8HoeHR2ujwpRyXyZbwuES6e1khLqhKe+MLXPJI8U5AzVVQV5tsslQoOINnqAqJ0mxWKxXCElUy30MP+6GlDLEkqcoWZLesJd1q//1gBHGpMxVXCFtD7I+1d1DKa8LVAWa6oVFac4646lgWsaJKzRv6Z7VFZOA7Koi1AycJqmcKPwtCIjua/g2K6C/qou8a45Y6L9eB78bBJfhTgPU1SyVneRWIitsJq46il3Hht3H2gGKsO8NSNsV9R1fMY3VO5zL9iFul1n+FfMlWMi6+YZpWGY9xOwINM0cEbT008CeCo3Mr8n6sVtrObawAcH+pDpywVwvPAtnNsZs9/9LOus86pTP9hAv5O14XbI3UxcOvZjWWiyDInlqVM3gLG00ZicoKDy1HTkeFeo05pWzAPEYNIMrqFnIr4C482PqLx5OqU6KZL5Kg4RJNvJvoZpzWXXor5+JRi5EuM3bHBcNUMxtU5jPsii+hn57u0HJNwdsoxITZ2gzH/f9m4PofxC84XJpdYIad5HZTZ/HxKpradGpYJscK6MvNzML+xJNnDklHno3FYrlppCbsoN562ddUMSniO5Pc0SXiWZl6Om1abhMQKao5rD0ebYnyO4tdUsD0ecksfxjS0e5gu6WBce7pkTmwaDch0do7kfSoK7yyZzlrJGM+6VZmNfM3aaZDx2YR85OojngkejtmolY2xp1HnNvKGw2bIULS6VM9fO4Fbl0AcxPUdpN8fwN3bmljijUUKeCSEvJOS7vV5PiB4KOT9wTPZ0qzPHe3WfEevB0DLetyT8m72yOFNcwJUIpIwsVabZ2iuY2ad6Hyhm0+vD67kCK9eH3h5gftUWxhSo2YiL88c/Xt7WV3B8PIVHC+CCZmQeaD/p2QaPP8LjA5F2A==)

**Comment by jakubmatisak** [comment]
Add minWidth to first fixed column.

   {
      title: 'No',
      align: 'start',
      sortable: false,
      key: 'no',
      fixed: true,
      minWidth: 100,
      width: 100,
    },

**Comment by Warnier-zhang** [comment]
very good
