### ISSUE TITLE
[Feature Request] Carousel - Hide Arrows flag

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#1883]
### Versions

Vue 2.4.2 - Vuetify 0.15.2

### What is expected ?

* hide arrows 

### What is actually happening ?

Currently the carousel is very basic and really only allows you to change the icons inside of it.

### Reproduction Link

Current Carousel
https://vuetifyjs.com/components/carousels

Link to another framework carousel
http://element.eleme.io/#/en-US/component/carousel

### What will it allow you to do that you can't do today?
it would be nice to hide the arrows dynamically especially if you were on mobile with gestures

 ### How will it make current work-arounds straightforward?
Well there are no examples of doing any of this on the main site so I'm not even sure there are work arounds for this. 
### What potential bugs and edge cases does it help to avoid?
gesture and event based bugs for sure and css related bugs trying to hide certain elements to the existing carousel

I'm not really sure what other information you may need so please let me know if there is anything you'd like more input on. I originally removed the bottom part of the boilerplate for the ticket because the directions for feature requests were a little hazy.

**Comment by jameshhood** [comment]
Break out of #1617

**Comment by jacekkarczmarczyk** [comment]
Already implemented  - use `left-control-icon` and `right-control-icon` props:
https://codepen.io/anon/pen/RLKdjV

**Comment by joaocpribeiro** [comment]
`left-control-icon` and `right-control-icon` were replaced by `prev-icon` and `next-icon`.
