### ISSUE TITLE
[Feature Request] First day of the week for date picker

### ISSUE THREAD

**Issue by Yakov-Varnaev** [vuetifyjs/vuetify#18844]
### Problem to solve
There is no way to set Monday as the first day of the week. [There is](https://v2.vuetifyjs.com/en/api/v-date-picker/#props) `first-day-of-week` prop in vuetify2, but I don't see it in latest version(3.4).

### Proposed solution
Unfortunately, I'm not good enough.

**Comment by capoaira** [comment]
I was looking for the same feature and found this: https://github.com/vuetifyjs/vuetify/issues/17992#issuecomment-1670932902
So you can set the first day of a week in the `createVuetify`
```js
locale: {
  locale: 'de',
}
```
Or if you use vue-i18n:
```js
locale: {
  adapter: createVueI18nAdapter({ i18n, useI18n }),
},
```

But the prop would be nice anyway ;)
