### ISSUE TITLE
[Bug Report][3.4.6] Threshold values for display are incorrectly assigned

### ISSUE THREAD

**Issue by jjoshi-cb** [vuetifyjs/vuetify#18849]
### Environment
**Vuetify Version:** 3.4.6
**Vue Version:** 3.3.9
**Browsers:** Chrome 119.0.0.0
**OS:** Linux x86_64

### Steps to reproduce

1. Observe window size with "x" upon resizing the window
2. sm is assigned a value of 744
3. Once "x" goes below "1024" the direction is updated
4. Expected: Direction to update only when "x" is below or equal to "744"
5. Observation: sm contains md value, and xs contains sm value
6. Upon updating the check of direction from sm to xs,
 we get to see the direction updating when "x" goes below or equal to "744"

### Expected Behavior
Threshold values to be correctly assigned thereby enabling us to use the same at differnt places
In the below provided playground, the direction should be updated only when window size is less or equal to assigned sm value (744)

### Actual Behavior
Threshold values are incorrectly assigned
As mentioned in "Steps to Reproduce", sm value contains the value of md, and xs value contains that of sm

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vl2v2zYM/SuEX5ICiZ3mBmsbJBnWtUAHbLjAdrs+zHtwbCZWJ0ueJCe5DfLfS0n+TNMPFOiLbZGHh+KRRemfc6BVGh0qNGz3GL7XwTJgRSmVgTOkChODf3sfXGCnZAGjGjuKRSzw5KCpFNpA7YD1MHB8jgVAxnTJk8cluBGAyRXqXPJMtyaAEw3uXswmzVgXS3i2WLTjIlvC09m8M/A9GebPu4gTJ8Ni0TM4y7P589pycW//NDkW2KbPcJdU3Dx444izfW5GdVQUNVGXJ7EIJk60X8oypJpJsZXBgqozuLGw1WGq5BHoiZp9wHUcSPGn+4wDSIhXkClFYVCR4X2lrUo9kyNxNKnkkPJEa/IaPJnpFYRAGTsMIbraGmY4TucEe8dERlP5i3KvIoK2ceczHJ3PuuByqVNGLqevgr6pjKaiNFFZNzGTbHVDdZgWMkNu8yfbOGjM272lkorspWJFoh473zJjClPDpFVCF/Az/VWoDEsTPgLSPpeKfZDC0LAJ6ip22eGQ8MpLS6pufqMFgHtBRTrv58DmKBvww1F+DUx/aMv9YAfDgHqkadgtGKk0tcvQJ/VCX+vUInqYKbO5hqXZslyuHqRN+YVoX6ut87ui6+J94TcY6ujW3hOlE6EdWufmx+yLMpk+nV3tiM3LyjaGEH4lEllQhqxrONRVgGmgaMpoHZL6znB3dBzz0MKpv5mECU0NyCt0A/6GSiMqhaWSWZXi8gpTb6t6xNnmfqtRHbDeh2B1oG+TQxycqP6qlILYyMzE3raqGriKKHbIdFVQ4ucIcmeb5w38vUixzrKXqGGLnCYQB7a1ks3majeoZa7KjHpbdoOpGwG8PpUUgtSiX7XBJIgPBin4IxxzFHViovVppQL8v0q4xcYBTbhrE/Z3+nTyTrbE0i9vrs0EEpHRknYeQtWr9gnbW6uym2Kjcppj+p/VrpPAnXtE4v6UyVdkOCLs0Vispo0z1LJN1BOitwI9KfqMX1ZlFbV/1u32vYp6pxMNdapYaWh2piodtD3vFe4mtFB/yIo2XGY/X+JOKnwrCmvq3wDo9O8FVhpf+fP9xi0B6uvB2Up4odtBhx7TYdq4betd2ymMRcU5OTpX76TyiDOcljCbAF0nZmBP5A7btBRCjp/AetOc7h1H6HfHmiZELN4eMiFQvWOZyR1r3/oG7U0A3BFJD/tqNRoPcjS5fVlNzjDJstcH6mG/M22QCMcj3wBHVmEf4QKaQq5kH+aoORUW8oDfTLuK/KrTegeXSXAX3oUv6BZzFy7Cn4J/PwI70DFM)

**Comment by KaelWD** [comment]
Thresholds are min-width, `sm: 744, md: 1024` means sm is 744 to 1023px

**Comment by jjoshi-cb** [comment]
@KaelWD thanks for the quick response
If I want to update the direction once width hits 744 or below, which pre-defined display breakpoint I should be using?
In above playground, I tried replacing the 'sm' check with 'smAndDown', which unfortunately gave same results
