### ISSUE TITLE
[Bug Report][3.4.6] Typography classes with breakpoints override font family (like text-mono)

### ISSUE THREAD

**Issue by mschoeffmann** [vuetifyjs/vuetify#18845]
### Environment
**Vuetify Version:** 3.4.6
**Vue Version:** 3.3.11
**Browsers:** Safari 17.1.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
See reproduction link.

### Expected Behavior
When using classes like `text-h3`, `text-sm-h2` and `text-md-h1` in combination with `text-mono`, the font of `text-mono` should not be overwritten by the classes with breakpoint.

### Actual Behavior
The class `text-h3` works as expected with `text-mono`. All classes with breakpoint override the `text-mono` font family.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUEFOxDAM/IqV8zZV6YoDCpW4cuVIOaSJtQm0SRS7XQTi76QtoBXak2fGsj2e509B2dQPKcllRnEnFOOURs3Y9QFALZVOaYMbMTGw9gHzj1RE6xcwoya670UaqmMvuseZGMjoEYEdwtkHG8+ggwXCXcpI88gkpVR1WXB9G+M7V1MMETbk2r3SVLmbHU62ck05+DsO8OTiPFoYENZBStrgAV43P/4DwTgdTgjamJitDyfgCENG/ZaiD/zn4sKTqv9/vSp7KKq+CKtQMtmncgl5Tp2qd1pa4usgWtnKphErOMpb8fINQGx6rA==)

**Comment by shawn-mty** [comment]
> I think this is because styles with a media query always have higher priority than the ones without media query, especially when both have the `!important` flag set.
> 
> A workaround could be, to additionally provide `text-mono`, `text-uppercase`, ... and other helpers with the same breakpoint variant. This would result in a big class list but I guess this would be the easiest fix (to avoid changing the `text-h*` classes).
> 
> Result: `class="text-h3 text-sm-h2 text-md-h1 text-mono text-sm-mono text-md-mono"`
> 
> Could also be helpful for #15616

I could be wrong, but I think it's because they are hardcoded here:

<img width="336" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/45756873/15f044e8-24cc-4e0e-b602-a06da3283459">

**Comment by shawn-mty** [comment]
> I think this is because styles with a media query always have higher priority than the ones without media query, especially when both have the `!important` flag set.
> 
> A workaround could be, to additionally provide `text-mono`, `text-uppercase`, ... and other helpers with the same breakpoint variant. This would result in a big class list but I guess this would be the easiest fix (to avoid changing the `text-h*` classes).
> 
> Result: `class="text-h3 text-sm-h2 text-md-h1 text-mono text-sm-mono text-md-mono"`
> 
> Could also be helpful for #15616

I could be wrong, but it seems like they are hardcoded here:

<img width="368" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/45756873/97fc628e-becf-4ff8-8f72-4461cd10f893">

**Comment by J-Sek** [comment]
Fixed since v3.4.11
