### ISSUE TITLE
[Bug Report][3.4.2] NVDA prevents selecting options in autocomplete

### ISSUE THREAD

**Issue by hd-allanvillarreal** [vuetifyjs/vuetify#18858]
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.11
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
1. Open the NVDA tool with the speech viewer.
2. Focus on the autocomplete using the tab key and open it by pressing the down arrow key. 
3. Try to select the different items in the autocomplete only using the arrow keys.
4. Check what the speech viewer from NVDA reads.

### Expected Behavior
Be able to select and read each of the items in the autocomplete by moving using the arrow keys in the keyboard.

### Actual Behavior
It reads the first one, and pressing on the arrow keys don't move it to any other option. The speech viewer also reads stuff outside of the autocomplete.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9ks1qwzAQhF9l2R58iW3S9BTcQDC0L1DoIc5BsbZBoGiFLJuWkHevJDdxTC899TYavtWMfnZn7Fxbbq0thp5wjZWnk9XC06YxANWQC2uTTIuWjRfKkPuxRqL33HKYIk9XG0CLA+nnBuveOTIeZhRO3FqFxC6Au6wWWn2wM0pkC8hq1uyE5KhfglQy2a/E7jgSb/Qpuijev/ikzDHbTxtvqnLeLDT+c+etlCTBsSbwDKngf1SeEm6vAA8xK0SdU40FWMe2g0uDd3Q6kVadzyMDQ35QRoaZxDaYDhKWbL1iEyYh3s2Nv48tZ68/Wr+u8WrPP0MC01+Z7YKXBa6KVbFcYhRPxSPuvwFHwcJC)

### Other comments
My form of solution was adding the `role="option"` to the `v-list-item` (like the second autocomplete in the playground) [based on this pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#wai-ariaroles,states,andproperties).

**Comment by Martin-Idel** [comment]
Can confirm. All other notable screen readers such as JAWS and Orca are also affected.
