### ISSUE TITLE
[Bug Report][3.4.6] Components nested in VExpansionPanel nested in VExpensionPanel lose state

### ISSUE THREAD

**Issue by alex0ptr** [vuetifyjs/vuetify#18859]
### Environment
**Vuetify Version:** 3.4.6
**Vue Version:** 3.3.11
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open 'foo' expansion panel. Open first nested panel. Change slide. Close 'foo' panel. Open 'foo' panel. Open first nested panel.

### Expected Behavior
Slider preserves last set value.

### Actual Behavior
Sliders are reset.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVd9r2zAQ/lduppB0xPbSjI4aJ2xjo+xlFAJ7afqgOkpqkG0hyV5D8P++k/xLjt2ugT7Fvu909913n5X7oyNF5H/j3Cty6gROqGjCGVF0tUkBwsIlnJtH8xJlqSJxSkUdMkH6zEkq4yx18Zcy2WKI3ok4ots1jRTioGLF6HLj7LJs41hp/ytTlcqkuhV0FfrN0/smhP7ro/i9WToBXj6mob5iOlIJGvqW0PgqIxFzBZKqvNI7TngmFBxB0B2UsBNZAhPc0cQC6zFq0GvG0qvspfWW0Cbb0fpI6Fc8kIEzM84YZI155GT+zi8ngGsM0EknMbo6HoGLjEvPgFCWSELHe1lQuPEOnVNlck0KPiwhzRlDJ4ELbZUKK0tIUPkndkDNzywHESNSIqros3IjwvXoG6ezwmp60u0jzK90ywMlgh0uO2tYnUd80pNjTC3sb/FmmQL/tWpN+gj4FsehVaWq5oIlbOkObXun36bHqqmhG8BaiTjdz6qYESCA33nySIWJlTj/iI86aw4dNH5L1EdwIYHpgqH5wlt8aa+OcB0RhlTWLN5S0QgVJHGKqZ+6jQUJecbIlRUq3CTbUqYtsP+FY5M0orKDGXk0oKawF1RC3OQApwLweY+8qux2JeexubkZZ7NWmcDqt49DNj+IIsgEbr8bFushi+ElddY9M4O/REVPL143b75H2iM9TdojvWh9xHJgtxH0IdKazhfmm2rgVqIGvkZYJxj2U+v8DApYrqD2rz6fMeqxbD+dWFkTTDMNtHXtOm2jV+u0Wb06w09gMPXwQ2j/auOU56rZvzpwbX5B0m7f6KOCsFzHjXf+6JcO/GoKIHhBk1hNJznfYpOgS0WuF7SgqfIUEXuqPFPt8tROb/qrsq+K+4nV48GoUcE/kYeGh0x0lq1WOXPwM/fmc9Rt4X32rp2HfxqX0ik=)

### Other comments
Not sure if this works as intended, but it doesn't feel right to me.

Initial discovery in Discord (thread closed): https://discord.com/channels/340160225338195969/954061264865349652/1184208427971526686

**Comment by c-harding** [comment]
The contents of `v-expansion-panel` are only initialised/rendered when the panel is opened. As a result, the internal state of components lying deeper than `v-expansion-panel-text` are not persisted when the panel is closed and reopened. The solution is to add `eager` to the `v-expansion-panel-text`, so that they the contents are rendered once and stay alive ([source on StackOverflow](https://stackoverflow.com/a/70789356/2275559)).
