### ISSUE TITLE
[Feature Request] Sliders: Variant that shows a uniform track for all values

### ISSUE THREAD

**Issue by derwaldgeist** [vuetifyjs/vuetify#18851]
### Problem to solve
I would like to create a slider for aspect rations (21:9, 4:3, 1:1, 3:4, 9:21), using 5 ticks. For usecases like this, it does not make sense to have the slider show one side of the track differently (thicker, darker) than the other side.

<img width="250" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3984535/26acecca-932e-43d7-a86a-6b8e5a18fe72">

### Proposed solution
Add an option to remove the highlight of one part of the track, so the slider is uniform along its length, independent of the value that has been set.

**Comment by KaelWD** [comment]
```
color="transparent" track-color="surface-variant" thumb-color="surface-variant"
```

**Comment by derwaldgeist** [comment]
Oh, cool, works! This was not obvious to me.
