### ISSUE TITLE
[Feature Request] v-img should proxy fetchpriority attr to img tag

### ISSUE THREAD

**Issue by hareku** [vuetifyjs/vuetify#18860]
### Problem to solve
web.dev says `fetchpriority` is important to improve LCP.
https://web.dev/articles/optimize-lcp#optimize_the_priority_the_resource_is_given

### Proposed solution
v-img proxies fetchpriority attr to img tag

**Comment by websitevirtuoso** [comment]
extra information
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority#high

**Comment by websitevirtuoso** [comment]
Created PR. hope they will accept it soon. sometimes it may take months
