### ISSUE TITLE
[Bug Report][3.4.7] VDatePicker don't show adjacent months creates whitespace under date picker

### ISSUE THREAD

**Issue by NickdeK** [vuetifyjs/vuetify#18863]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add the date picker
2. Go to oktober 2023

### Expected Behavior
No extra whitespace added below date picker

### Actual Behavior
Extra whitespace is added below the date picker because of positioned adjacent months days.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj80KgzAQhF9l2Yst1P9CoahQ6FvUHkRXKhoTkmgP4rs3iS1UyGFmGL7ZPBZUsg5vQgTzRHjFTBMTQ6WpKEeAbPYrIZx0puajrrqR5DdyYWPavujqniTMPuMNDXmJNi0R9IsYOSv7Eoss3PV/ZJPu0TbZlrPw7yJjVS07oUGRnrbDOia41LCApBZWaCVn4JnPeLYOYLhKg92EHEZ6w93Ig5dESerHkXne0Y5sWAPE9YRpkAZxjFacgws+P9rAXh4=)

**Comment by KaelWD** [comment]
This is to prevent layout shift when visiting months with 4 or 6 weeks like December 2023
