### ISSUE TITLE
[Bug Report][3.4.7] VDataTable headers prop maxWidth doesn't work.

### ISSUE THREAD

**Issue by mwshub** [vuetifyjs/vuetify#18862]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Firefox 120.0
**OS:** Windows 10

### Steps to reproduce
Create a table and set the maximum width of column to 200px.

### Expected Behavior
The maximum width of column is 200px.

### Actual Behavior
The column is not limited by maxWidth. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNV9tu4zYQ/RXCQGG5tRT5mkSw027Tpk1ToHkoWiySPNDyxCZWFgWK8sYb+N93KJGiJCuQ82KKc2Z45krm6b2XivDiU5J4+wx6QW8hYZdEVMLNc0zIYu+uqaSupKsI3BTEHoTaJ2Tv7vgaooAhPnUTEG5CN7B87uUbjyAe8fO5V4CDLdA1iBTFelVKCv0I4o3colhySaN7tVdHoKg4vS6LOF2zeINSvTISpeTuaZQpSjHdlVR+yRL0CAKeSMZjZVdpVqzeLC5anMZoLC4qocHPNBQskXmYQrQkyRpSBMuULMlTcdh78UOIYhCQ/p3g3yAmn/kmE7I/NNKQRlwwSAMyml2Xu69UBmTu+RWYWCFmPC13EsElsDgg0wqMCY47/ZGxf9S/TTJ/QRQdyApo3MZkcjmrM/FPmVy3MKnCNBO/i8kDkw+0NR6z0VWdxbglIHPLtKRx2SQx7yLxexhRJtpIjOfjOolRW1YmpySqME3jsovGH1jEIFYC26Q1LbN5N5epLaKSy8Szm6ZCOmNyHwIJkcqOpDRef2XhtjU+ExvtnNP1KaUKpFK0NmbnFu3fPIpYwpPW2Fw38uR7dsOUrK0nW7JNFuMuFrdZEtIv0ErCb/TNxLOum4I9LxhXXTT+5DEcQr5btRGZ+o3WmZxG46qFyNyzDmgi01kXk994nLU28HTWyMl4dlocs1FbPE7qddzIy4saw2b43mE+Pj3e4+zV3Gh6iEPyCjLcOu9EXU7D/FYwd9OQpFzIXw/kOLDuCJCZiEkMX8mj4DuWgiMg5dEeyPLGwghJQf7LdsAz6TiDhsxQSiUVEgk56nDiktGA/FijcKoC8RoVCsWfOrC5FNHm2vHSiIXgDIqomD/2SpzCUa+4ZCve1sgi5gEO6vQc/eS/eF/g8BH0H4G3eA3M1U4dnjP0FMRx6JCsTgNljdL/1GWNFumTpoLpbQOuDHD1IVBnscJzuSR9jFPYJz8bA645MjALV4vq5o4Y0MpXPboFJcwvi/FdoHKnfc5TkedxqJLaSIquKazLHB5YC0OSv4ACbadIWY3DcUhmvl9uGFHREpoevCXoO1bGK80iaUKuHjUBKcrVKdNQLTJsxbLp9EMtMG+ZWturP8lklPd+UX/EGfn+BhtD7PEKG9hhkDdjxDaqhfOI1EUqS+qhFeB8iFKoybAAUUnNmLrOjr79z9Zyq4aC7ydvVakZUTnfkuStnkj9oTZqRhRuGHKYp/4H6ncU/VNOaW0cZecp3qoJV1PNZ955yjiC1DCsqesBeZ6BexycxPnBaqtJ+rHqS7mqvLWxAOy+fmUHRIrMpso+2u1lehzoxQ7klq9RUhZP+eA+fy7jGVuG7VAcj22mzrdCPfy9s6a9J7cQO9VyMn2om0+dfDqocgKVuJheb0HZeCim6qMFZH3J674xZMzS9nnt6kPE4qL8B6R3HPYm3sQbjXpqMfUuey/fAfjJ6jA=)

**Comment by plundermun** [comment]
Having the same problem

vuetify@3.2.1
vue@3.3.4

**Comment by websitevirtuoso** [comment]
I can do PR and fix it
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/88765bee-d4ef-4298-8ec5-e16a92fb6934)

But before doing it. I would like to know does maxWidth will help?
Even when I used maxWidth it doesn't affect
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/f84da907-a466-445c-bbf5-030c406a54dd)

**Comment by plundermun** [comment]
Thank you for the fast reply.
You are right setting max-width just on the th will not do anything.
It will also have to set the max-width on the corresponding td. 
There may also be some overflow:hidden or text-overflow: eliplsis necessary.

**Comment by websitevirtuoso** [comment]
Yes I think overflow will do the job. I will do PR

**Comment by plundermun** [comment]
You are talking setting overflow on the TH or also on the TDs for that column, because setting it only on the TH doesn't work if content of some TD is to long.
Thank you in advance.

**Comment by websitevirtuoso** [comment]
Created PR. it was pretty clear and simple to implement. but only now I found time to check it. I hope one day they will accept it., Because this is already 4 PR in review

**Comment by Ribeiro-Tiago** [comment]
Just ran into this exact issue (v.3.5.8). Any ETA on this fix ?
