### ISSUE TITLE
[Bug Report][3.4.7] Selection in VDataTable broken when using return-object and Composition API

### ISSUE THREAD

**Issue by MelvinFrohike** [vuetifyjs/vuetify#18877]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Safari 17.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
In the given example select any table item, then deselect it. The "selected" ref now contains the item twice. Continuing to select other items messes up the "selected" ref even more.

### Expected Behavior
Selecting and deselecting should add and remove from the ref

### Actual Behavior
Items are added to the ref twice

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1lltP2zAUx7+KFWkqSCS9JCk0K0gT7MLYw14nyoObHEpGYkeOU8Sqfvcdk4vSxXEpaH1K/Pc5Pr9zcXO7sXIRDj9lmbMuwAqsuYQ0S6iEiwUjZL62IyqpLekyAbVAyNpOeQTJ+cLKIYFQQrSwSiV4ABqByFGqnholRq9qPYI8ByEbQa3ba5oUgCKjKbSF3M5A2BldKdGvFQGyEMzmy994eLmUP/Anu4xGLVzMh+2wEeQFJRNwsdmQOmqy3c6Ham3B5sMWNL7moYgziTtlkZGEshWer2J+SQnGlmZcSLLBUGgo4zWQLbkXPCUDTOHgo9rU2nK/o5Ye6l/IWa7OqSI6V9uPbu+OdbuqlOKm212ZkM2/C4TIWCYQkMFVmXByNB6NVniSWMdsdTw46VrQJF4xtMglFVK34RGeUVZF6qrbzsqmCeGSJlzEkA9OmjOARfhWOgxr2ejkC0UGFbjWxz2VZvNLKpa5wUGodLOLn4JLiJnBSVbuMLu5Fhx9fOjzEaPcdXCna4h6ll7ZEapwKpGC/wFGfvFVoS9zXY+AjP2ZRsdcB2TqjLSmmMWATDyNViUnIJ7WVHHjia9prF606xBIiDOZkpyy6CkOH8x8E/e0j29m4tOatfjc/8T3OUxoLPYwTSd9TGNz0XRRN1B60xKqm41DoC6LLKSPmiulTeWO/D4q19FVo4KavrlSZ++C+oqXLIgl9iJOthHMn76tXJ5uNBsy19HJVQ92TzwE7TskyTNZAmV7yE57SzYygc2Ml4fetATrKodw/eBJEmc820M16x2vkaOTaqpuP7Wpepm6Lg9h+sYZPIc8XZqhvJEuumq6DFBnxumaOroGKLG8rnQI1xVnxZ7/Ls/vLdTEN/Wf372jd66M/sGavK9YN7G8wc8YI5U/7q3UxHhdTHW1aKh0dSyZ9t8V+GkyH5YfzPh5bG1PLNdxnfHYUg+ec2rd/QUaROi9)

### Other comments
When translating the example above to the options API, it works flawlessly. 
This issue was already mentioned in the discussions here: https://github.com/vuetifyjs/vuetify/discussions/18509
While there  is a  proposed workaround, it is too complicated IMO.

**Comment by davidkhess** [comment]
Ran into this myself and debugged it down to the composables/select.ts file. The test if an existing item (which is an object when return-object is true, the value of `id` when false) is in the `selected` Set doesn't work correctly and it keeps adding the same row repeatedly to the Set.

It looks like this use of Set doesn't test membership correctly when working with reactive objects. MDN says it does a `===` comparison. I think the problem may be because even with the same underlying table item, the test ends up comparing two different ProxyObjects to the same item.

Workaround is to not use `return-object` for the moment.

**Comment by websitevirtuoso** [comment]
it worked on 3.3.19. but right now this is bug

**Comment by websitevirtuoso** [comment]
I made a fix but this is a rollback to the previous state. I can't be sure that it will not break. It has to be reviewed by Kael. he knows better about the current part and changes for the last 7 months.

**Comment by johnleider** [comment]
Caused by https://github.com/vuetifyjs/vuetify/commit/5f20f48e2e52bfb92706d1f57e854bb5cb1bf00e

**Comment by MatijaNovosel** [comment]
This is still an issue 4 months later. There are a few workaround but it is interesting that this is still a active bug on such a vital component.

[Playground](https://play.vuetifyjs.com/#eNq1lltv2jAUx7+KFWmilZoQQkJLRitN7S5d97DXqfTBJKc0a2JHjqFiiO++Y3IRLI4prcZT4v/x8fmdi8n92ipE1P+U585yAVZoTSRkeUolXE0ZIZOlHVNJbUlnKagFQpZ2xmNIL6dWASlEEuKpVSrhE9AYRIFS9dQoCXpV6zEUBQjZCNt1Owdh53QOaBDUigC5EMzms994RrlUPPEXuzxULVxN+rvRYbzbiHMBV+s1qYMjm82kr9ambNLfYcPXIhJJLtFSLnKSUjbH81VoW3KMLcu5kGSNodBIJksgG/IoeEZ6mKneR2W0Y/K4p5Ye6l/EWaHOqSK6VOYn9w+nOqsqc2h0vy8Tsv53gRCZyBRC0rsp80pOBq47x5PEMmHz095ZewdNkznDHYWkQuoMnmGFMqMZtNVNa2XdhHBNUy4SKHpnzRnAYnwrHUa1bHTyhSKDClzr45FK8/ZrKmaFwUGkdLOLn4JLSJjBSV5amN3cCo4+PnT5SFBuO3jQNUQ9Mq/sCFU4lUjB/wAjv/h8oS9zXY+QDIKxRsdch2TkuNqtmMWQeL5Gq5ITEl+7VXHjia9prE602whIhDOZkYKy+CWJnsx83vC8i29s4tNu2+Eb/ie+z1FKE3GAaeR1MQ3MRdNF3UDpt5ZQ7WwcA3W9yCP6rLlSdqmGbtBFNXR01aigRm+u1MW7oL7iJQtihr2Ik20EC0ZvK5evG82GbOjo5KoH2yceg/Yd0nRFZkDZAbLzzpK5JrCx8fLQby3B2soxXD94miY5zw9QjTvHy3V0Uk3V7qddqk6mtstjmL5xBquIZzMzlO/qoqumywB1YZyukaNrgBLLb0vHcN1wtjjw3+UHnYXyAlP/Be07eu/K6B4s733FukvkHX7GGKmCQWelPON1MdLVoqHS1bFkOnxX4KfJpF9+MOPnsbU5s4aO73gDSz0Ezth6+AvfG+Cl)

**Comment by johnleider** [comment]
> This is still an issue 4 months later. There are a few workaround but it is interesting that this is still a active bug on such a vital component.

It's interesting how people who comment about the delay of fixes never lift a finger. Literally.
