### ISSUE TITLE
[Bug Report][3.4.7] V3 Snackbar variants are too transparent

### ISSUE THREAD

**Issue by VijeshDatt** [vuetifyjs/vuetify#18871]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Edge 120.0.0.0
**OS:** Windows

### Steps to reproduce
Create variant tonal or outlined snackbars over any other content.

### Expected Behavior
Have an opaque background for tonal or solid (coloured) background for outlined

### Actual Behavior
Background is almost completely transparent/see-through

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFWV1vGzcW/SuEXtwCkmIn6S4aeBOkRnYbIAEW7aL7sN4HikNpWHPIAcmRIhT97z2XHFJj2Rpr3BZ98IdGM5f349xz75H+98vMO/Hifdsut52cvZldB9m0mgf59tYwdr1d+FrKwITm3v/jdlYt1lp+YfRrIazuGnM7i3emew0Xdyvu2JugGmm7gCdeXl5e3s4YbrYOL1unGu72uLLlTnFDtwRruC52YCn7wGBS2/CGi6C2PEQDv7DW2dazXwcPxMNXwZxzSgml4YuXdMNipUwVn4HZ29nBJmNvbSvN9Yto+3D94OeLQbLyxR9zDnYq1OzaB2fN5m08/PpF/yp7tewzhxNy6oql89LpOyGkh9uDQHGjVkZWf2hGxw/6a5Kaz5+W17Yc9d+aB6Y8+2SdbNjH1nfNu+ELes8rOLNnVdc0exbkl8DsmoVaImfKBGU2jJsqGwz7VnoZ4mXE38Gt/fKexZp7tpLSRBP5lgscE2CGuyodVOzReXIrHdwwQsaHrr65vPRztqthhBvWmTtjdya5gxuDtXeMsw3XWu6jr/Ap28MZzAvHm5WWFVMBd7OG30k8QLcx30oBpBm2gpUl+xiiv75zW7XFA8YieqOLe2tcZUKa0Dkl4dOqC4xrb6OfWvIWEeIEqaWg+igxTNCcIStcGfyb7QFfMKbg+h5xiZqbjayiGzu40dq206ivJ9dTAq++/dulT5iglw4ncS8Rdbb4SQaHK4FFFvNAswnpzHtVaQFevqEQKEMN3oEtCgyOkPVsrpL+LtiWtd1KK1+TGW/XYcfxgFbI43uNirJ/w9ZnpNXBT6G7iu5DEb2yxg+dO3iwBBYBMst2knWIQIV3FDbwx5kGspGawOOZCH6N5kW8wC6Hm7ySLlvcKa0BL1YpwAp34eYVUBtTwysYQLmQAQRGyOCIeyMTkjQKHsGMQ4PP9jTfo8eW7D+Ed4ti0mMdsHg/fXAzugNAEV54zODCuoUmxuhtGesarpNrCkhBMsiaBhqQGmQeqWlbS9UFZtIhFze9t7V0cp59zxbp4sWcABz7LcQgUh1KuB/MhrK2ZJ+5QYIf1C/basEShIAIgJ1cpdTISoEiPXzfxbIMg4a/SKxyMLrmnQ4IupJ62LkJTZx5yZ2o2do6dgEyhQVFFi5SuQB0Sx3ekIN0slcBfvhAb6rCgOksZdbcCHDKT2gEC6gVWNUcvSi3VlOjRoNU9j2ORm69bSSNEHBPaV4uhKqQzeG7KEnbOSoC+0qZn9G2MFZ3je1cjCX2NfL7NeEV2QdiZSkwCiBgia2dBY1S5RxGMBWz71wgUyu5nh9jh2ilp1mHU2wzTGJhIWctGhiND9gqNCeBJ04dJQCrTxycAt+AJQ46Sl6w19+w727m2dwBKDE/NElTgpjVoJkfFBgHDPxZ3GCqBCvuUMDeMMbYGlhGBXmB3/e8aZHAxY/7yoBqbywYF5jB3T8ptwHJ8HlEJFLYtUht9JgyGPnFrryAn4UL4jE76yqUCzj3lHsEMk+BwI+HdJXwtUFfbmDX2W5TiIqOERFH/ZlkmVw7ZOyQqzk1ZQQh9R5u7lCEbkWEU/zzgICQ92cZVdsn/8jdCMOr5dXl8tXL6Fn6/xW5gMVRsn8iJ6uu4OU7C0qAGbDzZ46+6BosDl8R1Xz4EnBKcv5f1qKHYO3DVumvic5ulJDOYgI6Beowgx6J5Sa2AqhogiX+hC0kl8ZCGhr4scAlbMtQK4F8I/J9Bmmhesy0mFfJfpCGK2QcEzhR4Vo5D7bB6kFWBimZI9D0MnY42gNxlRQCeBydtlzezqjGJXmgeDKF6vRpzFlMp5XVQNQY9o/PD2InjPb7SwKF7ySgW3WCJoHUoDFioVBTh8d9AXMFI7asWWNljL4OC/l4BQ8MkwrFaDjGrWDgS5rfIDT5hYaZdQoNA1DCOyQR1GSblhsV51c211P5gfKiQ2kNuHqNMnPjsTZS/oCS79HQ4PSax9lKXCWwLX1kG1kamHjvHaWYHMRPZOC4QaYkoLZ5MTiqM+NbrjT1R1x6hl3X8J8RTdgnQvbdeh3biuvYbeQc1TnyZIwVrh4x7RzpyBYTH8aVJ3IDhjVYCrgyF/24w3YIe1ptalpWIsNuyTHw5pphelNk2VpPFTRdaeXrg3uAYXrKyDSHsUxg/Yugwm/lce5hmdyjf2g3abBfY82KI7tWFUgxL2gNXmEKEwlFLn+PmUbXB+cV56ShDNG47Rv1IwHUAFzo8ugMAIRWBhlLzFxa/FNLoMkxRDASEI7bH9M9fIyTuu/a4Dp5OOv4qDhtkB3ijUrFZiAZ2VtEGHlyHBN2A71DRaJVlKP2plp3mh6IWwEamzYXcaBTuCGIe/EwAuv9ub9gpFJTkamNuYcrsa7ECfmBojwerGMoFwBGnbfje+oV2c9ESmJQFNl8DHnGmgXNQ9oisXMHLO8JgTII6qhzldOBT8cE1ATlNGy2kwJqgnIqG+CYgDpbOWVr4wLqTOVUdNFTAmpcOZUIJwioEeX0GOSeElBjyqmIjbMF1BPKKRucIKBOK6fCxJME1IhyOtmxpwTUU8qp8PHZAmpEOT0I9ykBNa6cDmxyroAaV05Fa5wvoE4op2xpuoA6oZxKl00WUCeUUyG66QLqceVUgDJVQD2mnLKxZwioE8qp1HaSgDqtnMqnVFME1EnllK1NFVCnldM9/6YIqNPKqazKEwXU48qpAHCSgBpTTocPDqcIqBHldJgdUwTUiHLKBicKqEeVU7E1VUCNKKdBk5wtoE4rp+LhNAH1qHIqhPoMAfVQOZVF+ZkC6oFyKh+RPkdAHSmnw4eGzxJQRTmV/e53CaiBcipC5XcJqKFyGm7bzxdQQ+V04hOvMwXUkXI6Eo/PEFBHs3QQ758poPL3U+m7qPg9Fa3ZeHXv66/Zr/PZq+Wr5bcz+vt6+ffZ/38Dt38iFg==)

### Other comments
The functionality in V2 was spot on for what's needed

**Comment by Estheisia** [comment]
May I asked if this is a feature now ? (link to try : https://vuetifyjs.com/en/components/snackbars/#timeout 
Also, the `tonal` and `outlined` variant seems to always be transparent (not only for Snackbar) maybe we can inherit background ?
