### ISSUE TITLE
[Bug Report][3.4.7] VTimelineItem不支持自定义tag

### ISSUE THREAD

**Issue by goinjoyCN** [vuetifyjs/vuetify#18887]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
VTimelineItem不支持自定义tag

### Expected Behavior
无

### Actual Behavior
无

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjkEOgjAQRa8yzgZNBIyamBgkcecNXIiLigNp0tKmHdgQ7m4BTdRd/+vMm3/r0bsyPVubdC3hETMmbZVgyosGIOtiYe30nEJpGhayIfdGE2SpSQUYy7ALLOpTgd6KpsA8S/++P6rAf10jmU9l6VeFEH3ppGXwxO3cRGprHEMPjioYoHJGQxTaR+M4QPB6Bu1rOI0Ty+hCShm4Gqeei2g1HpiVQYbDGnfJPtnED2KRbHGOB7y/AIyqW9A=)

### Other comments
 <v-timeline-item tag="span"></v-timeline-item>

**Comment by KaelWD** [comment]
Timeline items use `display: contents`, there's no point changing the tag.
