### ISSUE TITLE
[Bug Report][3.4.7] `VOverlay` leaks memory through `keydown` listener

### ISSUE THREAD

**Issue by peter-gy** [vuetifyjs/vuetify#18880]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Safari 17.1.2, Microsoft Edge, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Use `v-if` to toggle a component using `VOverlay`, such as `VTooltip` and set `:model-value="true"`. 
2. Toggle the component back and forth.
3. Check the *Memory* tab or *Detached Elements* (on MS Edge) tab of your browser dev tools to see that the `VOverlay` cannot be garbage collected.

### Expected Behavior
After a component using `VOverlay` is removed from the DOM, there are no detached elements, everything can be garbage collected.

### Actual Behavior
Whenever the `v-if` expression evaluates to `false`, the component is unmounted, as expected. The `VOverlay` component is removed from the DOM, but it can never be garbage collected, it ends up being a detached HTML element.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUctOwzAQ/JWVTyA1CQIkpCpUKjcOiAMVHAiHTeK2Fo5tOZu0VdV/x3aa1OW2M/ue+T6y1lbZ0pi07zibs5x4YyQSXxQKIO8TNCaEATQo1BkFXJICUT8XrDkkZUekVcHA8rVjJtijFajIUcT3VLCpP0wgrSUJc+EA+kT4Ae1W71bnLIvzWJHokbS93huXzBtdc5n0KDvuF9uOXxdIXSEJrfyh2vU3cTq6EODtAJ/vPbcSD/AlpITVVqhfeAVs4IM8sfT38OirbHormvQSzoSgwSigK3QKxoK2O0HV1kkQHvivAkgsA7vSm43kMCUWftTQO5rliMktDwYf8yzy18G2ssJQKOJ7oy1BzdfYSYLjMKdGwpvbEYEzlzqrLhggunAOa5Qtn43J0xCcAuFAnk372GnGHtLH9C4pOWF6zwb4xH7+ACEJyec=)

### Other comments
This behavior is caused by the following code chunk in `VOverlay`:

```js
IN_BROWSER && watch(isActive, val => {
      if (val) {
        window.addEventListener('keydown', onKeydown);
      } else {
        window.removeEventListener('keydown', onKeydown);
      }
    }, {
      immediate: true
    });
```

The global listener is removed only when the model value is `false`.

I could get rid of the memory leak by patching the dist file locally by adding:

```js
onBeforeUnmount(() => {
      window.removeEventListener('keydown', onKeydown);
});
```

thereby making sure that the listener is removed whenever the overlay is unmounted.

As long as the listeners are not cleaned up, the component can never be garbage collected, it will remain a retainer.

**Comment by boutils** [comment]
@KaelWD @johnleider We also noticed these memory leaks, preventing us to execute our test suite entirely. Of course without a full "green" test suite, we can't achieve our vue3/vuetify3 migration. We reached the browser memory limit before the end. To give you some data, here is a chart showing the memory used (JSHeapSize) across our test suite. You can see the difference between Vuetify 2 and Vuetify 3. 
`vOverlay` seems to be the major culprit.

![Screenshot 2023-12-18 at 06 47 56](https://github.com/vuetifyjs/vuetify/assets/1707229/0afed365-a148-4da5-a29a-8aad306e2cb8)

**Comment by peter-gy** [comment]
Also, please not that the `onUnmounted` change I suggested in the PR description removing the `onKeydown`  `keydown` listener patches only a single source of the memory leak.

As the screenshot below illustrates, there are scenarios where the `onAfterLeave` callback of the `VOverlay` prevents the component to be garbage collected.

![image](https://github.com/vuetifyjs/vuetify/assets/40776291/64ec66ef-f1b2-473c-a274-4ae0c3f673e0)
