### ISSUE TITLE
[Bug Report][3.4.7] VPagination ARIA attributes on buttons do not render correctly

### ISSUE THREAD

**Issue by tahornback** [vuetifyjs/vuetify#18885]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.11
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use a VPagination component, view the generated HTML (without browser interference)

### Expected Behavior
buttons in a VPagination have `aria-label` and `aria-disabled` attributes

### Actual Behavior
buttons in a VPagination do not have `aria-label` and `aria-disabled` attributes, but instead `arialabel` and `ariadisabled` attributes

### Reproduction Link
[https://github.com/tahornback/vuetify-vpagination-issue](https://github.com/tahornback/vuetify-vpagination-issue)

### Other comments
I discovered this when working with VDataTable, which was converted to using VPagination in 3.4.2.

**Comment by johnleider** [comment]
What am I supposed to do with the repository to reproduce the issue?

**Comment by tahornback** [comment]
I have updated the repo with a bit more information, documenting HTML behavior, JS behavior, and better outlining current and expected behaviors.  Since it seems like the browser does some magic to cover up the issue, I'm not sure how to reproduce without staying in a test environment.  If direct Vue HTML generation is needed to "prove" the issue, I'll try to find a way.  I'm not familiar enough to know other ways of demonstrating the issue.

**Comment by johnleider** [comment]
@KaelWD Is this a non-issue?

**Comment by tahornback** [comment]
I do not see any other instances of an ARIA attribute being used in a camelCase style.  Everything I've seen in kebab-case, such as 
- VAlert.tsx:141
- VBase.tsx:89-91
- VChip.tsx:142
- VTab.tsx:118

**Comment by websitevirtuoso** [comment]
maybe unit test can help to check this issue? At least I think so

**Comment by johnleider** [comment]
A single search returned this:
![image](https://github.com/vuetifyjs/vuetify/assets/9064066/b049a98b-5494-4634-a75a-38f8d7f2ea41)

**Comment by tahornback** [comment]
I just threw together a test quick over lunch w/ VWindow, appears to behave similarly to VPagination.  I will add tests to the reproduction repo.

```js
describe('VWindow', () => {
    it('renders with arialabel', () => {
        render(VWindow, {
            global: {
                plugins: [vuetify]
            },
            props: {
                showArrows: true
            }
        })

        screen.debug()
    })
})
```

```html
<body>
  <div>
    <div
      class="v-window v-theme--light"
    >
      <div
        class="v-window__container"
      >
        <div
          class="v-window__controls"
        >
          
          <button
            arialabel="Previous visual"
            class="v-btn v-btn--elevated v-btn--icon v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-elevated v-window__left"
            type="button"
          >
            
            <span
              class="v-btn__overlay"
            />
            <span
              class="v-btn__underlay"
            />
            
            <span
              class="v-btn__content"
              data-no-activator=""
            >
              <i
                aria-hidden="true"
                class="mdi-chevron-left mdi v-icon notranslate v-theme--light v-icon--size-default"
              />
            </span>
          </button>
          <div />
          
        </div>
      </div>
    </div>
  </div>
</body>
```
