### ISSUE TITLE
[Bug Report][3.4.7] v-combobox v-slot:no-data appears even if search prop is empty

### ISSUE THREAD

**Issue by desousar** [vuetifyjs/vuetify#18897]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.9
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
go on https://vuetifyjs.com/en/components/combobox/#no-data-with-chips
and use the demo for the no-data slot

### Expected Behavior
you select all the items in the list and the no-data slot never appears

### Actual Behavior
you select all the elements and hold your cursor in the text field. The no-data slot appears and reads 'no result matching "". Press Enter...'.
the no-data slot should not be displayed since the prop search is empty

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Uk1v2zAM/SuEMCAJUDuHrhhmuAF62mlDD8MuTQ+KTSdC9WFIdJoh8H8fLdlx0gH1hdR7JE0+8uUsgq/WT22bHzsUhSgJTasl4WZrAcpjVjlLUln00OhO1REeCbNzO3dKAMAxM65G/bgV0W7FB6IIKH11YD45c0BxUDVm1mW1JMl8I3XAK1pxT4HxaGc8ZgXUWBHWM2iJQ3/KkzKdAdfAA5DcX6VpuYtdPtU1BGfwA206TarVOL1b9EEFQkvZUHuCg5FaZ9VBtSFBozAszaQgDx60o2Ic7BIQ1dNcMxsGuoJviYwU6bSG+fvlwGPgFgMYSfx7u4etKAN5Z/eb8xmSttD35XoEtyKHZ04KUL7t6g0Pgr5cDy6Qg8rj0KoEi+/g7GXs2M36s3Zu2Hn69c0BpbDpVNJNRWA8KkZuMvgZKq9aiqF4ap0nqLGRPDKcU8VBzAKWK3jcwHLEAOJxFPCy+CENq7K4g8Wzd3svzfT80+FoSDV/F693l5XH8+TU/6kkZwG203oE+xU7yX0fVlBMfY2FYHmUejWD3FoTsVyj3dMBNvBwQwPQQYX8i8UT/VbV2zKNFsFYMW9du1yt5ox+cvupp2gZ5q0n+UR/J+7z+/y7GOzX/Jt4/QczwzKt)

**Comment by yuwu9145** [comment]
I don't think this is an technical issue, the confusion is from slot text doesn't cover the case of empty search.

Maybe tweaking slot text to something like this would improve the example: [demo](https://play.vuetifyjs.com/#eNqtUz1v2zAQ/SsHoYBtIJKHNEMFR0CmokOLDEWXOAMtnWwiFEmQJ9uBof/eIyVZVjJ06XTke3fHdx98uSTelesna7Nji0mebAgbqwRhsdUAm2NaGk1CanRQq1ZWER6IZmd25twDAMe0MRWqx20S7Tb5QOQehSsPzPeHySE/yApTbdJKkGC+FsrjDS1Zk2c82gmPUR4VloTVBGpi15/iLJu2AVPDA5DY34QpsYsqn6oKvGnwA920iqRVON4tOi89oaY05B5h3wil0vIgre+hoTHcmrGDXLhXhvKhsKtD7J7inGko6AaeEylJUiGJrG96NnMH+GXAoWfJHhpBLEfvYZtsPDmj98XlAn0cdN1mPYDbJINnDhp0X59+21UFV4lusw5HIAOlw1CHAI0nMPrak+i//qT136VgGOzs2eKHti3Bu2kdmJOGo1Atv6grsEHjf5Y1Y6eJrWdL37uN693/gwgMH4GRWQRffemkpeiKZ2scQYW14LHApc8YFiCH5QoeC1gOGEBc6BxeFt9Fw5Nb3MHi2Zm9E814/dPiYEjW74vXu+uaxi/FoZ+pfuQ56FapAexWfOiPp7Am+ahrSLTktq8mjJXVELBMod7TAQp4mNEAdJA++6LxTL9l+bbsK4tgTJhZY5er1RTRjcdulBQtw7yYY/eS7i65z+6zb0mwX9m+/gUk1mm8)
