### ISSUE TITLE
[Bug Report][3.4.7] VInfiniteScroll keep emiting load event without interval after done('empty') is called.

### ISSUE THREAD

**Issue by tlserver** [vuetifyjs/vuetify#18895]
### Environment
**Vuetify Version:** 3.4.7
**Last working version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open the Browser debugger console.
2. Scroll to bottom for 2 times, so that "No more" is shown.
3. The console show that infiniteLoad is continously called many many times.

### Expected Behavior
When "no more" is shown, load event should not be emited or it should be emited at a configable interval.

### Actual Behavior
load event is emited many many times without any delay.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVNtu4jAQ/ZXZvCSoJLAq25VYoK20PFSqENqivgAPbjIBq4kd2Q4tQvz7jnPjUqru8kI8czznzM3znaNV2LnPsmCTo9N3BgbTLGEGRwsBMNj4LMuKz+IQSmEYF6gqExmfH0TMBTf4FCqZJHCXSBYNFw6vzI90XDgN3t545NpAmDCtCZdt/e6JnxC1Btj4sVQE8riI8L0FXEDEDFs40H/FbcFC9rPrluI33/AIFQXgcQ2DERATdD6ArZ4H4jy1AySUqZUoBS6cc2fKhb9GvlobQtzcZKTiHFKnmFB8n0qR+mu5QeUX9nP4mapjXTNukrIfZwidMdGwGHw3vk6h+F+TMJ+quGaaa4ipbf5bIdZPMeJ5+qFk5W8iDY95yAyXAnY7qret235/gbtjyT+K7nyh+pDVU/5i/j2xdyrYCGZIk/M19SehjxCn89Y5GfoT8GHQO2eTXm9F53wtrKXcmpPAdNSh4pkBjSbPIGFiZbOzidlrPM2kMrADhTHsIVYyBZeW0v1l7wKYbYbwnOM45UZPmWIpGlR6MG7DBKhEKCIN2iguViMYluJctGC3cdPSyBjGpfMWxvMKsGwQtLa0NpZjRnwNsDo3sD8YShUNJm3wgiBgaqX71dVpC4YjYGJb1ecWpuVHHwTS9H9+qPKkYlKT7SuCEQxtNbxui3y1xz4Al+wZWyHZ573rNvR+LKtoTG9FCHEuwmKmbdj7hKlUey3YlfQ8Bq+kCzYsyREGRawgQbEy6wZGsd4YN6T1DabUHK7RU6hlsiHakW3qjKcoc1Nb2/C92+22So32Z5VXFFfDgmN+zHt1ZUWXUEUjosrHrnRWnmoTK3dO60kjiVHhJd+FjI/fYdurOZVamGWTli2eTChbufLcY3Af3DYU4DqD4hBE9Bx6rhVOk+bWPqO2h0KVDaFClaWmrpSlO65+k+qJgMld77ogPlz+NhweEqVxcuWrSyNDk5uZbcN/ou5/L++BnrxwDR4qJdVRx2tthb3yXiJ0C9chXtUOeqmKjadVcPZt5zroBV3/Bamn1055/Oks/wKJLEiq)

**Comment by KaelWD** [comment]
This was supposed to be fixed in v3.3.6: #17358
