### ISSUE TITLE
[Bug Report][3.4.7] VDataTable - headers prop typescript error

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#18901]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.12
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Load reproduction link
2. Notice the headers type error

### Expected Behavior
Should not error

### Actual Behavior
The `align` property of the headers array when added causes the error.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVm1v2kgQ/isjdBLmDjs4BDgQ5I5Wl1xb0aImfZGSfNiYAawa29pdU9GI/97Z9fotgCBq+QLsMy/PzszOzN1TTXDvbBzHzjrB2qA2lLiKAybx8j4EGK7tGZPMluwxQFsgXyNX5wBrexXNMBj4JC/sGLkdswWO7mv6YIp8Sn/va6nwYIlshlwQbH7lSKofYLiQS4JlJFnwRp1VJQhKvVexIGIzP1wQan5liFKy1yxIFKWQrXIq/yYx3QgHUSz9KFR2lWbJ6uXwbM+lKRrDs1Jo6K/wuB9LECiTWAfLX8URl/AEHOewhTmPVlCnqNaVOIBH7iR4jAsYwV3K5in9AlAUB1C/ivgMJomQLFzUmxm4jLjAOPqOfAAXnVZ+Pk8oAVC/ZiIK/BALhYj7Cz8k6NPNuDiNue+Rk06n1cpsbM33cx63KAIGE5VhuNlPpNvbIfJfgJ4kJycS6fXpc4TIq8kXmLT3M+i02i8IxTXyFQs3uywoGsfCMU5mPny86R7g0Xd/Aw+31T9O5PUS1zwKUMJrtmI8OpCaX66R7vlxLlPy6C0R+q67n0a7l2X31+LiHufyli0SxuHKvt3EJeOVLPU6LwnKu92YnMBjwn7M6N18tTv7Sbh/v6RU3rKYhTs8zrvHebz3hWAhXN/aHw9Eo/uSaOwn4rrtzsXRiCD3cIbCHk+uic8BNue/4yW7boeeUIXPQ7n1XrFvOJ6+oe5rSDKxCT2Yo/SWYD2BGmBNPTmy+dUEQR391Qa2jeJinBo+DyHE7zClFu8LtDgS2TXC6LIQAzUZbv0VRom0rMYzLONEnZ5Gxggs5RxscBvwZ4XCrgqGM1JIFf86IqtRklZTxxEBhclqlKX8OVjpFZ10BJfuWaFJMu9wo/xq6bvWg/MNN4dEP3Ca8RVhmmvZ5pD7VtwcJWJZrAmPuyEqjLLPapSTRXZnqFBm9wk+ZoKPBwVN/ko8RyOoU4l6dfgnM2BnLgfZD9tAVXPbSji3uxmgvPoh7QwqZ+bGOg06f02VzIoFU0lUjVp4UOg3Qe9GA2MlTVfF/7ZJI7GVH2RQ+hI0tVJRmJIhVrStWB0tm8JmQzNItqiA9GWgRxD1Wb0Y1JtAJUAn6qXTHxb4C/U89c3qRUPINf/PX3yuWjSBkgGKyT71K2oMkPZ3o61axSmOP+jOkauljeQUxalqLGD90ch1davZz/WhFMPSrprFsQybZdVAkidYAosV2OBpSudJ6KmVVSun8Kk9y7hz9D5MRpXDFDEt0dE98Jg5Ry4xtLLSNPWo3JTfbenmuT8tnwkU1yv4qKMMf052zgJh2KYVTZU8PEuX78vatllrO22nX1PfF06v9vATOn7O4Q==)

### Other comments
As per @KaelWD  it needs `as const`

[Example without `align`](https://play.vuetifyjs.com/#eNqtVm1v2kgQ/isjdBLmDjs4BDgQ5I5Wl1xbcUVN7q5Skg8bM4BVY1u7ayoa8d87u16/BSMStXwB9nl259mZ2Zm5e2oI7p1N49jZJtgYNcYSN3HAJF7ehwDjrb1gktmSPQZoC+Rb5GodYGtvogUGI5/4wo6R2zFb4eS+oRfmyOf0976RkkdrZAvkgmDzK0fS/QGGK7kmWEaSBe/UWpVBUGq9igURW/jhilDzK0PUJnvLgkRJCtkml/JnEtONcBTF0o9Cda7aWTr1cnxWc2nyxvis5Br6KzzuxxIEyiTWzvI3ccQlPAHHJexhyaMNNMmrTUUH8MicBI9xARO4S9U8pV8ASuIImlcRX8AsEZKFq2Y7A9cRFxhHX5GP4KLXydeXCQUAmtdMRIEfYrEh4v7KDwn692ZarMbc98hIr9fpZGfszfdzHbcoAgYzFWG4qRfSHxwI+StAT5KRFwoZDOlzQsib2f8w69Yr6HW6r3DFNfINC3eHKsgbp9wxTRY+fLrpH9ExdH+CDrczPC3k7Rq3PApQwlu2YTw6EpofzpH++Wktc7LorRGGrlsvozvIovtjfnFPa3nPVgnjcGXf7uLS4ZUoDXqvccqHQ5+8QMeMfVvQu/ls9+pFuL+/JlXes5iFBzrO+6d1/OMLwUK4vrU/HfFG/zXeqBfiut3exUmPIPdwgcKezq5JzxE15z/jJbtuj55QRc9DufResS84nb+j6mtEMrELPVii9NbWE6j+1daNI2tfbRBU0N/sYN8q7sWp3vMQQvwKc6rwvkCLI2ndIkwuCxqoxnDrbzBKpGW1nmGZJCr01DEmYCnjYIPbgl8rEg63YLigDenG305wNUps1XQcEZCXrFaZ5S/BSq/opB24dM+KTOJ8wJ2yq9l3nQfnC+6OUT9yavEVMrW1bHDIbSttjqJYFmvD46GLikPZf6qT04nszkihwNYRHzPi41GiiV9J52QCTcpQrwl/ZAfYmclR9sM2UPW4fcWd+8MIUFz9kEYGFTNzYx0GHb+2CmblBJNJlI2aPCr2t0GPRiNzShquiv19mzpiJ1/IoPQhaGmlpDApQ6poWLF6mpvCZkAzSDangPRloDsQlVk9FzTbQClAK+qhN4v3nzP/zh94Ti3efN2GK3r5kBZww1e1oI75UZeCnJZWhjriXFUGsH5p5VxdKzLqQ+nepfEyu3sZNvOlgSRPsAQWU6vB0zAsk9BTU6berOGXlhljzdETLJ2p7KWIKWLOi6qWI9cYWlk2mRRSZspPrXTx3J7mZ4TidoUetZThz8UuWSCM2jQJKfnGZ+m4TINyY99udJ2uM2yo7wtn0Hj4DmZYt3g=)

Error
```
Type '{ title: string; key: string; align: string; }[]' is not assignable to type 'readonly { readonly key?: "data-table-group" | "data-table-select" | "data-table-expand" | (string & {}); readonly value?: SelectItemKey<Record<string, any>>; ... 11 more ...; readonly children?: readonly any[]; }[] & readonly { ...; }[]'.
  Type '{ title: string; key: string; align: string; }[]' is not assignable to type 'readonly { readonly key?: "data-table-group" | "data-table-select" | "data-table-expand" | (string & {}); readonly value?: SelectItemKey<Record<string, any>>; ... 11 more ...; readonly children?: readonly any[]; }[]'.ts(2322)
index.d.mts(21300, 9): The expected type comes from property 'headers' which is declared here on type 'Partial<{ page: string | number; style: StyleValue; expanded: readonly string[]; tag: string; sticky: boolean; noDataText: string; loadingText: string; itemsPerPageText: string; sortBy: readonly SortItem[]; ... 27 more ...; fixedFooter: boolean; }> & ... 4 more ... & Record<...>'
(property) headers?: readonly {
    readonly key?: "data-table-group" | "data-table-select" | "data-table-expand" | (string & {});
    readonly value?: SelectItemKey<Record<string, any>>;
    ... 11 more ...;
    readonly children?: readonly any[];
}[] & readonly {
    ...;
}[]
```

**Comment by matheus-agne** [comment]
Same issue here!!

**Comment by weekyear** [comment]
same issue..

**Comment by agne-matheus** [comment]
I've found a "solution", just give a type `any` to the Headers array:

const tableHeaders: **any** = [
	{
		id: 1,
		title: "Cliente",
		value: "descricao",
		sortable: true,
	},
	{
		id: 2,
		title: "Venda Bruta",
		key: "venda_bruta",
		sortable: true,
	},
	{
		id: 3,
		title: "Desconto",
		key: "desconto",
		sortable: true,
	},
	{
		id: 4,
		title: "Venda Líquida",
		key: "venda_liquida",
		align: "end",
		sortable: true,
	},
];

**Comment by webdevnerdstuff** [comment]
A better workaround solution would be to type it `VDataTable['$props']['headers']`

**Comment by KaelWD** [comment]
#16680

`headers = [...] as const`

**Comment by webdevnerdstuff** [comment]
To help others understand how to use this (as I wasn't sure at first either).

```typescript
const headers = ref([
  { title: 'Plant', align: 'start', sortable: false, key: 'name' },
  { title: 'Light', align: 'end', key: 'light' },
  { title: 'Height', align: 'end', key: 'height' },
  { title: 'Pet Friendly', align: 'end', key: 'petFriendly' },
  { title: 'Price ($)', align: 'end', key: 'price' },
] as const)
```

**Comment by Employee87** [comment]
i think things like align and other props whos values are fixed set of string values, need to be declared as const. Alternatively, you can also declare typings like this

```
type VDataTableItem = Exclude<NonNullable<VDataTable["$props"]["items"]>[number], Readonly<unknown[]>>;
type VDataTableHeader = Exclude<NonNullable<VDataTable["$props"]["headers"]>[number], Readonly<unknown[]>>;
```

and set your header as those types.

**Comment by itelmenko** [comment]
issue closed? why? important types are not exported yet.
VDataTable["$props"]["items"] - is  very dirty and does not work

**Comment by sataqi** [comment]
> To help others understand how to use this (as I wasn't sure at first either).
> 
> ```ts
> const headers = ref([
>   { title: 'Plant', align: 'start', sortable: false, key: 'name' },
>   { title: 'Light', align: 'end', key: 'light' },
>   { title: 'Height', align: 'end', key: 'height' },
>   { title: 'Pet Friendly', align: 'end', key: 'petFriendly' },
>   { title: 'Price ($)', align: 'end', key: 'price' },
> ] as const)
> ```

in my case, as `sortable` property is optional, I assign it to few columns that are `true` and leave others. I get the TS error: `type 'unknown' is not assignable to 'boolean'`, earlier I fixed by assigning `false` to remaining columns.
for now, this solution also works but I'd greatly appreciate an insight to how it does.
