### ISSUE TITLE
[Bug Report][3.4.8] When @click:control and  @click:append-inner are in the same element, the  @click:append-inner event can't be triggered.

### ISSUE THREAD

**Issue by CamilleXin** [vuetifyjs/vuetify#18915]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.4.0-beta.4
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. click the input filed
2. click the append-inner icon

### Expected Behavior
the append-inner icon should change

### Actual Behavior
the append-inner doesn't change

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U8GS2jAM/RWtL+zObKDt9tBmgLa39rBfABzcWAHPOrbHUSjMDv9e2YQkZBYOAUlPeZbec1bvog7F7Jf3032DIhdzwsobSbhcW4D5PitdqFKcssJZktpiaEupGNy/Lm27DPBTL9bi85e1GIAJJjxQVmo0aggA7LPKKTT8VoV1Lbe4FtcNufQercq05QkyzcPEXhneMMAPmFRKZ5X0/MTKBPJxKXNlORmT7mXQ0hIzuYYM76bGHUb+TVO9fjwVHT0yGrcaQz8Lo4u3PKoWXKQgt90afE3T3Gge7nj3jeV8NtRyaAEDrH/vEee9SWd06GOstD7PZ4MLwGldBO0pdeHBu0CgsJSNIXg/sylJMofHJ1gs4bGtAbQGsgO/8fgwee7qaY8cKDTYFaORf6zCQw6frop1Dqt+q2QmVo4i1FOOAF7NmduoQqluo3goNOGdhh27c7wNW2woyDvH1/dOJ2e3Dfb4po1OTxycw8JVvuEJ84v8Z6FY/i4HCEhNsEA7XU+TjKsuTDJvLq2nywEdf4W0c4p17+iG9+/6mETafn0LeBikH/Hzb7xd3X0Sp2fxMn2Zfhfx/+v0m9j8Bz8oWEI=)

**Comment by KaelWD** [comment]
They're both called, nothing happens because you're toggling it twice.
