### ISSUE TITLE
[Bug Report][3.4.8] Virtual Scroll component's scrollToIndex has no effect when an item has just been added to the list

### ISSUE THREAD

**Issue by MaxenceMouchard** [vuetifyjs/vuetify#18917]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add an item to the list used by v-virtual-scroll, try to use scrollToIndex at the last added index.

### Expected Behavior
Scroll to the last index added

### Actual Behavior
Nothing happens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptU8Fu2zAM/RXCGBAHdRx36bYuSwoUO+Ww03prClSzmVioIhmW5DYI/O+jJLtLtPpi8ZF8fCSlx1Oi23J+3zR5ZzFZJiuDh0Ywg3dbCbDqZqxp/NEbpZKGcYntAHmw462xTMx02SohYFkj39dmvU0WRbFNYMmJUpPp/wS0uCNryPrtk7DdJu+URDqKgG6mhTLLCnfMCsd5AkcDPcXDaTR6WM0vdHuSeSxt7IMcl404JPR5wUMmJfLGgEZjwxj4oVGtgZPrIgMlfykrDVbQw65VB5jQFCcuE4BKaANRm7B2iam0Qkx//Ivyoxl8j0HlxLc2g2KSXQLXMfA5BhYxcBMDX2Lgawx8i4HbGPj+n7BB6lPoTCD1JSt8o76uC4Ic+D6wNJ3CmlYYKFhVbdwI0pDaT0P0zsrScCXP/GMGbeSBH1BZc8lEG3I1r648kbddYt4xYTFvrK7T50Hvp5MP7Z9D0Q90uG8+h59MI8zuYAMSadUviA0Ml50Z+KOMoc2/1kg6ZbiRXDsqij1jSe9lReKgdGxHZUHb/R5p+UwYbCUzvEOdjUWMCnVMjWe1nDXUs1Kg1nA4jm6qKZVja5FVxyj6XIfgL0iL8G7zyk1ZQ1kzk8FOtYBvjO4/TvMxI7rAwyBDzQe1cRNM/RzHkfUZrbsoaIV0di8qvCF6PUmfJYt8kV8vEne4yW+Tp78Bxme+)

### Other comments
I need the same scroll effects as twitch chat for example but I'm already blocked just by the scroll at bottom request.

**Comment by KaelWD** [comment]
Vue batches updates, you have to wait for the new items to actually be in the DOM: `nextTick(() => virtualScroller.value.scrollToIndex(index))`

**Comment by MaxenceMouchard** [comment]
> Vue batches updates, you have to wait for the new items to actually be in the DOM:
> 
> ```
> setTimeout(() => virtualScroller.value.scrollToIndex(index))
> ```

Ok, It was my first thought, but this method doesn't seem very safe to me and depends on the client. Wouldn't it be better, if it doesn't require too much dev effort, to have an event on your component so as to know that a new element is available for scrolling ?
