### ISSUE TITLE
[Feature Request] v-list-group multiple prop

### ISSUE THREAD

**Issue by rojobo** [vuetifyjs/vuetify#18913]
### Problem to solve
The multiple prop for the lists-groups is missing from vuetify 2

### Proposed solution
Ability to select multiple v-list-items based on the multiple prop in the v-list-group

**Comment by websitevirtuoso** [comment]
could you provide repo or playground code?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-list/#props-open-strategy
https://vuetifyjs.com/en/api/v-list/#props-select-strategy
