### ISSUE TITLE
[Bug Report][3.4.8] default filter in VAutocomplete not showing all matching options

### ISSUE THREAD

**Issue by nsakiya-incomm** [vuetifyjs/vuetify#18918]
### Environment
**Vuetify Version:** 3.4.8
**Last working version:** 3.3.23
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0, Microsoft Edge
**OS:** Linux

### Steps to reproduce
1. Click on the Autocomplete 1. You will see a cursor prompted right after "Microsoft Corporation"
2. Click backspace key multiple times until you get the word "Microsoft".

### Expected Behavior
It should get 6 matching items shown in the dropdown menu. Try the same steps on autocomplete 2

### Actual Behavior
It shows only 2 matching items with some empty whitespace in the dropdown menu.

### Reproduction Link
[https://play.vuetifyjs.com/#eNqtW21...](https://play.vuetifyjs.com/#eNqtW21v4zYS/iu8fOhmgbVzvS0Oh8W2QOI4jhM7NiwnuettcaAl2mZDiy4lJXHa/e/3UC/mi+ikLfpl15pnxJfhcObhUPnvr0eZik9Ot9vuY8GOPh19ztlmK2jOfviSEvI54Y8kFjTLvv9ytKWd70jOnvPOQia7zj++HJU6hAyzrGBEsa2SSRHnXKbkiedrQsmyEIJwNEkEz/IuORYsXQH5nvz6awn2BGdpPtJgBVUtfv36vvrx+bFDi1zGEoNiOauEhAi6YAJDOrUw8u2XowZ/7GxkUmpkTLA4Z0nVkdH4pEelZ+WOolH44fOJ2zOmWiH9523ZIFmwNX3kUjVzzdZS5Uwdmm71dq3UmvafmzGW4E/MuDWG1yaNAZ3ACfDr84nlGnjMYsW3eanCN1s0SXqjYf9m/r/RMJqTpZIb8q57opuiKWdZ9+dMpu8qK7LnUj9hS1qInNS2SemGfSLvLpkQ8l4qkbz7UAEJzekncvyefP8DOa6VYUpnnnhxzGMlM7nEQKRCB1R7YtPG1/f4Uf3UQyrw4qemY+K5InraIwR+nRcqtSfXYF/rtgPL6jYRyzTLSbahQmgQ/mC11l1ygXePj/X6fCA8TdhzOVWrAZh4SY5LiHwm//w7+e230s+6PI1FkbDs2Mz+3Xunb2sK+g0b+GoeGu+ztPfD9adb/Y+XP5/sfQAPf+t0yGmSEDhYLLcs+XJEaJ4rvoCtSS6xJTYcSxNF+iFf86xcCJnCYkSmYkc6HTR09KEMSK7bIC79V/cJ97+YE352+5/p5L4/+3JUjgTSUW9C+todlEx5nJEeTWlCD+MjPRY9xEZhNhtGZM7idSqFXO0+kGEaGzS6jeBTpdcoIPg3LZ2LCqMTA/K71TI01LUkOX9kiI8tTch5hiaNaENfoHhRCPiH2GgrRUw98phl5eisRtMHpuwn3mp+K7GnyvmR2+jUe13lGdQ1YGRFwuWjfHaNanbVXvFsGEX90Yhcyg2LqWKu4c5Gt2RaJYXMCOliR+aKpYk3Dw28y8iVhPexnY8JQVVCpjTmSx6TGcugBltYGngrI9+QG7kQzIgZVWQGoxsLQZRn9swsJH4oo3lEBdrqSQsRD9yadvnom7mWugNn2O9nxY4gxQpGSsP+9WDjnIfw+d0h5J7m8foQyKfU7JEWJgNYZdsZWxZqUSm2dUYDciaKjqK7NhbRTVakq7cV5hSrbHvVXkGmGMbB119Fb9OHVD7Zy1wBXYSjtyxt6QSsbaFhi5cKrf454gwiJHxawStPN0zx2PI3mekBBXalzMsdCafJ5cbDFF+t9D6JcryF1slUPiFONfuUjEY9Wzmnz6S35iKB6Zcst6ymZL7242FrS4SVQmMusnWK1E8mRZ5I0KpW4EDT7cjZo1sMUZAzRdOkFfh7FDG1sZsXbnosQWgIhYEW0mqWI8V1Rjx9yHbWa4hQXLoG7MmFom9G0Z7M8ljWmwfz3piNXkPYM54cMypyf0pgABsKG4X6KJTi8M0mxyG3+m8XKkdWDue3ENgyy27BVOlNe9H5N2N4okh4Cp9zejv/2CsWDDkA5rKkgxEZKFlsjeRqSPqFAqMgZ907S1Ob3x/B+bSKk3DvO54wY65zmiLrBH0cEAwcaUZq1vIcnmg/5LTaBEhbRsxXlesJnH7cuUnFBLkqHlnKrQhYiUfI9OnKE45lumALS1Vhdk9SPVhDUshiZMwSuLIg5yzjqxTzHC+ttnYgS+5Ty0Kl8IKmLafu65jgLXBfP20Vz5ANnRm+oex5Vr9LxjxbwzOxSXUMbimckgHYv5ls/6ze0bakVCEdtFVTXQNSRNEpS83k9xLSR+6Pcqpcbb1NrmVC4UIl1TRxrd6sonh2KBHEJQkLBYy+EFzmOcwa51LtsJr4D1zF9qi+eORmffvbjAssRLA1eHsHrmoE8KMl+NsFw+JbrtN/ho+7T87+3kMXN7Cv3lWe2S+40naoEkD/l4Jvyyl6jgEt2NKP4DUblssD4fWC5wvuB6gLhEhWOUpOeVr2doKhMZaSEUWiG6apfCw7sUYv1dUrznVR/AxKKJA9u1H3tNtCUwo+bALiW/AU62JcZdAHmGYFplj67jBNigyHGisyQuUaYf/BCCaj07PIPEbR0O1U+3GUy23FRqaC7uCfTrAeULUpmeQr0XbAUqYgvgTDhVdAGQPDQNPct9CAL/SmD9l2IOFoDmcfSLmyYlb1WLbXGkAF2bH0knIYyucpkCpyh+NcDqc8mSq+odgkk9T0con5whHDqecPg/5AoaNrAvUytnjFJcJBmZ/aceVSczX3THPJnkA88w5OIg/6ROL35cNedLmEB6eatnmv1WJ9Ogtl7xrvoLkYw7XkOY3XvN7CcymFNS9Qv5JzcmQ4fZzxugRBFDgFv2YZucWBBoahabFEbCu0oxm0yH55xKmL6heXLNPHVxi/acVzwmFvcqN9VehiGXYS4gPOa6avYcIokjaOeSvjF8MNXWkOrDdmMLI1Po3MiH7jQpVB2oJRr8RxJFagVrY9r85Gvj2u7nqN51YszUHGcmGn8iusLWLW3nQR8oW7s64oOKJhHL4fXNGXF4M6lrrCucYeqlynevvWvNj0cH3euebJC6iA4Kt1HaGxSjCG0aEq1vzbm2sjDp8rrumLO6JrhpVf7SP1WBapDt+Y1HLJGJlJuCSzR8aTDLXJ5kmuBejCBYI36g+jvLVnQG4riRd8IX+FhHuonatHw9Gov0A5wUgY3aIkuXIYjd9gSMexw4g9I3Q9eNHGVYF/5rrOYscMW9jqtYh5yyLjaGh+Uw3nL7aAa4e4g6fD4Q2/tiPxGBsnvkIQsiR6kchIxi3aPKa7hVTG5UAymfATui1sNVCz0kGBfYFwY4BQTfZ1tNX2Xukaxgepc3zEoBH+eQK9sCAdUmrndnd0G2r3mogq4R9c6kZlhvWQB+an9+VpRu5xnPDNqWvC1klpjH1hzidVfdIf1M3d8HwYThA3dV0kTMYa1G+PagdCzQ02FfLJbOAblq9AK/zn1vvsSZ/YZ8UCB78NhR/rEEFjQ11vcF2E99zBcNg0TSSZ7LljEKs6wwExT8zLE7ED88wOzHOCA3h6CMsU3ZBoJx7BREyPU/SC3YSaYkcH6U2Bnx5JslVChN3Gq7JLk3QDKp4JpzhV8q2ux4yw4p1JSppj5T6ltEu2zUv79OMWGNqKr4TRKbpgXhPH6PG912VAzW9Jgt1LHcwCwzJaSuIg9OQX262eoIDtpKjFw6otFu2wYzamKUfqj2ZGH3BA0Ye8RUlwWzFrpvfuOL5BZdnkiRl9aWdLCHGcsxPMTD4U1sMOy7Vfc30iJ8fz+ZBcCORrXRV/v9eNBvdkIOTCYrDRsG//PkPMtsof0XA2xO3Dv8d1mHFMFU1uJvoUbjJNRME6XwtahxT8OTd11gPi0MoGsHBeDylORuctfDjumzTYCCfbXHbsN/0QEoFm4ayMeoNeSY92VaDDZ4PhNMKV9458+x05TVdM6DVsQ75pGF3hctR/bqmt6WoNoyOq2TL1gND3s6OGpPRW4TDC+DX7ZE/VRLzJhtDWeLjiiKdwsHqtXHd5wM1ojJ3Sfk+fXe3x6eubw2jF5M3hoa1ge3EAfLN/j6G38LvT4cRFLcLs1iSMWk5TgbuoM4FdWR5bznFFZGVtXViq2LfdFTIJSAlefEMPIcULflGOTPwEt1F1hS8rey2Lmu45NCo2OsQO0yVFEcVpZN4b2b99y82nndHw5rolnvcPB+V9OMNboJzhc8OcqhXLMfvRwJfVt5m4c2AUlQ3jBw1e3XFxuLhV83NAnVkPo9cMFBbkM4yiEBhzE3IdzLqtceS3qQBVDmPuHY4DOXdmHrJGDj2EWbdpDaKEIVK1rLwiaAlxDxSSoajNKLy19YKuqYeqQQ3slJFrYVXP+33SujLUW+PKAtfCVr3CVdBL6kN1pcMX48DeEtGnRcCg1xxrw9JT3jJo4OLRIG03CApvcF/ny1DoxTUXOceubo3mVawmTL9XPptc3/qykgK0hHWujPSBCdGk7avuNWoL9VJZIy4vT8+nJ5dzH3JCTi1q2c6/3qzFd/xFX9I599sOVHLq+Rqub0Xe361xjxUD2Wl4dQhGQFrLwnY69owikFVRNchabspqDC5ET+NYV0JsTOls0RSJrTrVfK0g2lRHcD/wynSFIL6qiWHr45S5zNZ8oRPzUuKUVZ6Ra9LrR2m5w6gzfSp1ZTNyq4lSGYOv8RmRlSctvAqVfhFQK8wAH3IZpIMxR5fIT3YBYo4LQzSHgIW6hzfj24RHZbnTGf1tqj/TyEpCujd8kPbcDX8cTtyX76iwyl6VV4R47V1Zh3EPep4V78dIYdOpH6/vx/iYRfNYoj8nComd73CMvL4DDyDljXZAjtuhoLy6FggBbtHeAFV5PAAEoqQF6ouxgLypYwUgv2JgIfwhOBnce6T+EcKg5UEsIPdpXUglZ0zgWyl7/xkUXobKbQDgM5wUjV/fU1GWm/bMZE4Na3FBHX3s/O2iY2pIm4t4rMQFrfDpAi73cDGHfPwByHV0DwzMzKUhf0baOz0MuPxjD1THk3o9YtxoZLhrfUON43sEizIeUsoDa+voHFgqRyewYn8IDy+soxJcRE8juJaeTmBJaw29v/5qzM/7DRxe51BkqqHJzU1Ltk9LbesevF5tFFBYqSxSf7B2PJ8NTK1mrxUefheV41e9zFEIRA+Dh73L4O25GSzkEjbaXmqNBveeBoJrooHQAv8Z+UFryk1I5n1E2EK80pKNH5gjkAOTBHLY+Uo45GwH6KUn93mITTvb7665Eltc5lrjaTWAGzmUE/ABUDxAzeCkT8sjl6BPe5X/8JJW1uVjI8ZnRQg2qOtI8C19c2SgAkVeo/kjW+hPo+qPYd3iEorBXjWS4wwOTdApmwd6abV6fO2+ZyO3a44Pie1Gtt8s21XwlxlDwUaAUOPbQa4vk1EzeWRCll+xGLUfx1iv6vM597iLG1h8st7H7q/bKXV0/YJnZjylVvNdq1bEN9n4EN84SKlgSoq67v0MU+nr8PLCAEUl48BvKfPM7/qg8jXM5zWMC5mgMbQ27jPhca7+fuZ2u6cJNVvxsNqV88HWK3o4+Pj9egmiZsMy1fzfDtSOclvrS/oT/mLg64ejj92P3W8/4m8HPna/6/7r6Kf/AygOITg=)

- OR -

[https://stackblitz.com/edit/vitejs-vite-9rks1e?file=src%2Fcomponents%2FHelloWorld.vue](https://stackblitz.com/edit/vitejs-vite-9rks1e?file=src%2Fcomponents%2FHelloWorld.vue)

### Other comments
I suspect it has something to do with number of items in the list. I don't see the the issue if the list is less than 66. However, the number is not consistent across different browsers or running environment. I put 441 items in Autocomplete 1 to make sure we can consistently reproduce the issue. When we have a small number of items, it seems to work fine as shown in Autocomplete 2. By the way, I see this issue in all 3.4.x versions starting 3.4.1. Vuetify 3.3.x works fine.

Thank you

![image](https://github.com/vuetifyjs/vuetify/assets/58954685/03c3bb2b-72e1-4bb0-8e7d-9aed61945b6a)

**Comment by nsakiya-incomm** [comment]
Happy New Year. Can someone help me on this, please? Not whether I missed something or it's a bug.

**Comment by exidniy** [comment]
Hi, I faced the same issue. Also Ive noticed that if you have this empty list with only one or two results and then you scroll it will show to you all the results. So probably its related to virtual scroll or something.
