### ISSUE TITLE
[Bug Report][3.4.8] Cannot focus append-inner icon of v-text-field by keyboard

### ISSUE THREAD

**Issue by kobakei** [vuetifyjs/vuetify#18911]
### Environment
**Vuetify Version:** 3.4.8
**Last working version:** 2.7.1
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. In the playgroud, first click the preview area to focus
2. Press TAB in keyboard

### Expected Behavior
When TAB is pressed a second time, the append-inner icon should get focus.

### Actual Behavior
When TAB is pressed a second time, the append-inner icon does not get focus.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUMtKxTAQ/ZUxmyiYFqkLufSK7vwDF9ZFaaYSzIsktwil/+4k7aXl7mbOnJxHvmYWw1C/e19NF2Qn1iY0XvcJXzsL0E6i976MZRmcTb2yGDaogAn/khgVankFASZhnER97piJPx3bDySHVgplSUQo0ssUqUQk9Mh7G7Qafk9HOjGzFZyBlyNKvr+oKdF1nmcoxGXZgte3yTOyFmvrQ2Fa4xCUTxAxXdbeyngXEswQcIQFxuAMcPorvvqRbkxAJSkWMe75B2rt4NMFLe/4w07ZohdOxtt6tSITtjyypmqqp4bl4bl6Yd//W+OAlQ==)

**Comment by TIM56887** [comment]
If I add a tabindex="0" attribute to the append-inner icon's <i> element, it becomes focusable.
