### ISSUE TITLE
[Documentation] Get started with Nuxt 3 results into IDE error "Type argument cannot be inferred from usage"

### ISSUE THREAD

**Issue by pschaub** [vuetifyjs/vuetify#18927]
### Environment

**Browsers:** Edge 120.0.2210.77
**OS:** Windows 11, 23H2 (Build 22631.2861)
**IDE:** IntelliJ IDEA 2023.3.2 (Ultimate Edition), Build #UI-233.13135.103

### Steps to reproduce
Follow the steps in the official guide "Get started with Vuetify 3" -> "Using Nuxt 3"

Dependencies in `package.json`:
```json
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "vite-plugin-vuetify": "^2.0.1",
    "vue": "^3.3.12",
    "vue-router": "^4.2.5",
    "vuetify": "^3.4.8"
  },
  "dependencies": {
    "@mdi/font": "^7.3.67"
  }
```

### Expected Behavior
No IDE error in file "nuxt.config.ts"

### Actual Behavior
IDE error "Type argument cannot be inferred from usage" in file "nuxt.config.ts"
![error](https://github.com/vuetifyjs/vuetify/assets/11846736/74b9ebd3-e2e8-46b0-b19b-b2d2b0f21a89)

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3](https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3)

**Comment by pschaub** [comment]
Why is there `@ts-expect-error`? Is there a way to easily solve this without ignoring any errors/warnings?

Could we use `nuxt.hook` instead of `nuxt.hooks.hook`? Is there a difference? See https://vite.nuxtjs.org/advanced/modules/

**Comment by Jan-Heussner** [comment]
For me this solution is also blocking the option to add modules from the nuxt devtools. Is there another way to extend the config?
