### ISSUE TITLE
[Feature Request] VDatePicker should have a day-format props or simiilar to customize the display of day in Calendar

### ISSUE THREAD

**Issue by yns-ivan** [vuetifyjs/vuetify#18921]
### Problem to solve
I have a problem similar to https://github.com/vuetifyjs/vuetify/issues/18093 but currently I think it cannot be solved in Vuetify 3 because it has no day-format props. I apologize in advance if I'm mistaken

### Proposed solution
Add day-format props or simiilar to customize the display of day in Calendar

**Comment by y-kashima-iandc** [comment]
As you pointed out, VDataPicker does not have day-format props, but we have confirmed that it is possible to change the format as shown below.
```ts:main.ts
import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'

// Vuetify
import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import DateFnsAdapter from '@date-io/date-fns'
import { ja } from 'date-fns/locale'

const vuetify = createVuetify({
  date: {
    adapter: new DateFnsAdapter({
        formats: {
          year: 'yyyy年',
          monthAndYear: 'yyyy年M月',
          normalDateWithWeekday: 'M月d日(E)',
        },
        locale: ja,
    }),
  },
  components,
  directives,
})

createApp(App).use(vuetify).mount('#app')
```
```vue:App.vue
<template>
  <v-app>
    <v-date-picker></v-date-picker>
  </v-app>
</template>
```
![DatePickerAdapterJa](https://github.com/vuetifyjs/vuetify/assets/106800911/ffd319bf-7493-4551-8316-626e89e5c77d)
If you can read Japanese, please use the details below as a reference.
https://zenn.dev/iandcinc/articles/0a9cffe7012711
I have also published an implementation example below.
https://github.com/y-kashima-iandc/vuetify-date-picker-ja

**Comment by KaelWD** [comment]
#18375
