### ISSUE TITLE
[Bug Report][3.4.8] Vite 5 support: getting `The CJS build of Vite's Node API is deprecated` warning

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18937]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
"I have just created a new Vuetify project and updated Vite to the latest version."

### Expected Behavior
CJS warning should be removed 

### Actual Behavior
there is warning: 

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UcsOgjAQ/JVmzwoHPahBEx9/IR4KLAZTWtJuMcb475YWhJsH46Hpzs52Jt05P8HoPN43TdRahA0khHUjOOEulYwl7TxXknglUfuGb2l1ZzdrqCof2xRylIQ6BcZFdZWTRv+gVxHMHeNobklNSE9nJFmB0lTkFVXd8Jzc0DFU7GCJlExiPznqOuxEHf7BqVSaeCYwuA3ob44FltyK7m+nUH11GpDbesjEM2MoSfyJDF4zWESLaA3dvYxWcHkDrnmXrQ==)

**Comment by KaelWD** [comment]
You have to update the vite plugin too.
