### ISSUE TITLE
[Bug Report][2.7.1] Unable to drag&drop events on monthly and weekly calendar on touch screen

### ISSUE THREAD

**Issue by NguyenNamUET** [vuetifyjs/vuetify#18935]
### Environment
**Vuetify Version:** 2.7.1
**Vue Version:** 2.7.16
**Browsers:** Safari, Other
**OS:** Windows 10

### Steps to reproduce
Please install
Vuetify version: 2.7.1
Nuxt: 2.15.8
Vuejs: 2.6.14
Nodejs: 16.19.0

### Expected Behavior
Drag&drop event on monthly calendar 

### Actual Behavior
Event can only be drag&drop ONCE then cease to function. User need to touch on screen AGAIN to drag&drop

https://github.com/vuetifyjs/vuetify/assets/52781343/aef70dd6-47c2-430d-9f40-7b9fa2b07619

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9Vd9r2zAQ/lcOw6izJk7Sdklx026D9mEPgcIKe2j6IKJrbObIRpbThpL/fSfJPxQ7ZuxlJtjW6bu77767yM8fXi7X4+9ZFuwK9EJvoXCbJUzh3UoALHYjlmXm1SzWqVAsFihLkzWyBAVnsjIBhLhDofLblWdfVl6z902lxTrKFZPKwghlTD+16UFb+uCc7QkcMcETfKpd7tm+67BNd9jFL8l6Ek78u+gHwVtgtc+QMFtSIWrsd4txI0KllTYdiaUtVsvF2NGYlvlaxpkyIHzPUqmA4ysrEgUf2ibYFkM4+yE4vj+yDZ4NtZUzxULwB3B7B77BkU2yzQa50TAEUSSJgdqNpSb9FOtYzo7tTwjPVTFlKH3FPIRpidNXSeQX4u9kD0tEFYuNZWMv2yWYzieXs9l8NtGXs61Ftpvz6cXx5qF+a+W/6OZfsjyCx1QxlWLel35+fdWf/vpLi1uV/sU8DwPz2KKKUk7alJRaQ+p/ECEV79CshlbJRyZz5BShqUNFcR64nYFbFxvEIivUjUVXPE6MOKXbI5NDMMM3pP7vhxClhbbEolBIzi4hhwHNYa7Ir8iRcgt8g3uaPd8JN5qeCDgINqj0wPiDkh615BX8TkFOqiqZaQUl62ADs1PHc+Sp55PcLNeRDVODD70ilf/rv2qkTf9JqX/TwaJpQk9iyd5C8kJSAanQs0RObaUsiPib6WmJ2lW89uuhWZGSaSG4qdMN3dR8knl/9XBe19E///YQpnOOmnQMatgoulFb0jeth5IFdlpqsSltzyY3MB6XjctPoO4pTKlY5fWZvOg2pSOjJbFBoGFBeM2gmeyvoHmR4IYffDoOP3C+lhZ4Dv4xgT7PRnCJqpDCZVEJac6xlaDfYlx/X7zD0LsMroLJSK6DS88urr2XPyI3hA4=)

### Other comments
The problem is @touchmove:day does not fire after drag&drop ONCE

**Comment by NguyenNamUET** [comment]
Does anyone have encountered this issue?

**Comment by blalan05** [comment]
I don't think we are going to fix this for v2.
--
 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
