### ISSUE TITLE
Light DatePicker in dark app not possible

### ISSUE THREAD

**Issue by bonflintstone** [vuetifyjs/vuetify#1893]
### Steps to reproduce

Have a <v-date-picker> in a <v-app dark>

### Versions

Latest versions as of today (26/09/2019):
Vue v2.4.4
Vuetify v0.15.7

### What is expected?

Either `light` or `:dark='false'` should make the datePicker light

### What is actually happening?

The DatePicker stays dark

### Reproduction link

https://codepen.io/anon/pen/VMPVNW

**Comment by jacekkarczmarczyk** [comment]
Fixed on dev branch
