### ISSUE TITLE
[Bug Report][3.4.9] Uncaught TypeError: Cannot read properties of undefined (reading 'global')

### ISSUE THREAD

**Issue by UnforgetMemory** [vuetifyjs/vuetify#18949]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.0
**Browsers:** Edge 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
`"dependencies": {
    "vite-plugin-vuetify": "^2.0.1",
    "vue": "^3.4.0",
    "vue-i18n": "^9.8.0",
    "vue-router": "^4.2.5",
    "vuetify": "^3.4.9"
  }`

vueI18n
`const uI18n = createI18n({
	legacy: false,
	locale: DEFAULT_U_LOCALE,
	fallbackLocale: DEFAULT_U_LOCALE,
	messages: locales,
	globalInjection: true,
});`

It's a bit strange. `any` type encountered (`TS2561`) exception

What's even more deadly is that

> Located on the console

`Uncaught TypeError: Cannot read properties of undefined (reading 'global')`

It is normal for me to call the `uI18n`（my alias like. const uI18n = createI18n(）) global callback before and after createVuetify

but error that
`export function createVueI18nAdapter ({ i18n, useI18n }: VueI18nAdapterParams): LocaleInstance {
  const current = i18n.global.locale
  const fallback = i18n.global.fallbackLocale as Ref<any>
  const messages = i18n.global.messages ...
`

### Expected Behavior
Normal type and normal calling

### Actual Behavior
Wrong type and incorrect call

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUslu2zAQ/RWCFyWAJbZoD42AAu4x5y6XsgdaGstKuQjkyK1h6N8zXJIoThDkJGrm8S0z/H3mwXfiOAOO+1NzF3jLRzM5j+zMOg8K4VfusYXtvTOsKthK2pfA249f7LdeTQj+Ei+065QGoXI7RM16JPyaaA6JYlMY43nN84CXtnM2IJsT4OsKfXWWljENg+pOLdsrHWATK4N2O6Vv7R10ODrbMvRz7mRbLavA1j+/V6lmIAQ1QGjJUqnHI0JAAsZPRbYWwi7X0Q38T/6zqZL30VaZX3aGBzAkls6M9bBXs8YfuVjpcThgdsCYEPEbNZ48lmtC4GmCGrx3PlfKUNtXN3FFc81TLeNly3WifQjAN2XntVETvQFn6RUkLVkaQfJHdckpYfyX/IA4hVaIrrd0rQc9Hn1jAYWdjNgSTPjZ4mig7p3Zfmo+Nx9EPwZclxsIpt559y+AJxLJS/4kEwf3DqmCTAo3WaGUaq12IUq8oBakdwRfe7A9ePDvTXRxbZ3qovVmsvSUn2vOdvo7NJ1LeVJ/eyN5WhTtida0bHhSo32lpPzPPfwRRAI=)

**Comment by KaelWD** [comment]
Learn javascript, `{ uI18n }` is the same as `{ uI18n: uI18n }` so of course it's invalid.

**Comment by UnforgetMemory** [comment]
> Learn javascript, `{ uI18n }` is the same as `{ uI18n: uI18n }` so of course it's invalid.

Haha, I sincerely apologize. I momentarily thought this was interpolation. I am indeed a novice.
