### ISSUE TITLE
[Bug Report][3.4.8] Bugs and problems in date picker in Solar and Lunar calendars (used for Persian/Farsi and Arabic locales)

### ISSUE THREAD

**Issue by mahozad** [vuetifyjs/vuetify#18942]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open the reproduction link and see the date picker in it (it is using Persian/Farsi locale which uses Solar Hijri calendar). Read on to see what problems exist in it.

### Expected Behavior

![Problems shown on an image](https://github.com/vuetifyjs/vuetify/assets/29678011/ef5b7c9f-f09b-414f-9cc5-bb3814adeaf6)

Many other related issues were closed and were referred to #1892.
The issue #1892 was closed and the authors requested a new issue for new versions of Vuetify.

These bugs and problems are for [Jalali/Solar/Persian calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar) used for Persian/Farsi (`fa`) locale and also for Lunar calendar used for Arabic (`ar-SA`) locale.

1. The "year month" label should be concatenated in reverse order for `fa` locale (instead of `‏۱۴۰۲ دی` should be `دی ۱۴۰۲`)
2. The previous/next month buttons should be swapped (reversed) for **RTL** layouts (including `fa` locale)
3. The month labels in the month selection section are [off by one](https://en.wikipedia.org/wiki/Off-by-one_error) for `fa` locale (the default selected month is one less than what it should be and selecting a month selects the month after it)
4. The year numbers (labels) in the year selection section are off by one (one less than what they should be)

The following problems are less serious:

5. The title and header have not been localized (translated) for `fa` locale
6. The days in the picker do not start from `1` (they start from `9` or `10` or `11`) (because the first day of month in Solar Hijri calendar corresponds to `9`th or `10`th or `11`th day of a Gregorian month)
7. The months in the month selection section  do not start from `فروردین` (they start with `دی`)
(because the first month of Solar Hijri calendar corresponds to March in Gregorian calendar)

### Actual Behavior
It was hard to separate expected and actual functionality. Please see the expected section above.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUMtOwzAQ/JXFFxepTYTCAVUBiRsfgOBAOLjOpg11bMt2KlCUf2djp49cLO/s7OzOfA3MO5mfegxt85f9eLZlbWeNCzCAdCgCfqQejNA40wGfubzSlcbfSJVG+wBzA56Xg6uh0gDhgB1uIf4BamxEr8J7Arlq94fA11NvjK8yUqgr/VzyRiQWQCOU2gl5JBD1dXS8rzRbR0+v1mZ0EhkqA3ZW0UUvE608bYS18RsLOj6IVqOboQjWxN7YVh7Rwc64mrplvoDPAoQuFSYkLSjzm8VUeulaG8Bj6NP+S9IOm9t8Y7Ywx9r5PUVKjBV/Q6UMfBqn6jtOTss8SZIYG9esyIrsoSD7RfaYPbHvf3d4ngk=)

**Comment by SoheilHasankhani** [comment]
I've been following this discussion and I believe there might be a different approach to using the Jalali calendar with Vuetify's date picker. According to the [Vuetify documentation](https://vuetifyjs.com/en/components/date-pickers/#guide), it's recommended to use [date-io](https://github.com/dmtrKovalenko/date-io) adapters for handling different date formats and locales.

I've created a sample to demonstrate this approach, which you can find [here](https://play.vuetifyjs.com/#eNqlVM1u00AQfpWRLymithsKl6hUqdQTUkWlInqoe9jak3jT9a61u0mpokicCoe+R4BDq76NAzeehNm18wtIEfhg7+7M930zOzO+GAdGp/FoiJb3bqOBCToBL0qlLYwh1cgsvq9tMIGeVgW0Gt9WIhvHwYkqUNrGXPhNOGCCMcGXXm/qg6OMlRZ149zNSCDkKl66N2yRUCw7RW04kztjyDgTmNoOtMr6LCxUhlq2dmFosPE75n1uTQesHiJMniUykQItOA14DeNEArBavrMRzq6z9ZQumMN7TwDp9uKY0Ofc5ueI1xm7pQgGx5QyPS2PAiiUtPlZTkk646oljkn89m3vxHl0mkAO/Tfqo3XUO8+874Tek3nAQqWU7TzkekfUPVbzFmgM6+My0B5bLMGTn/L02iW5OATgFgtzhu4SMSOy8d4ETLOdh+sezWSfxFaQAJZbH0A1nd1V36qHalp9AVpMq6cf99XDz4/3s0/VdJUFIEdG9XGgTT+onug1++yOq0f4/nV2R9bHVbi7jS3FV2F/0NxCjMtySJVby7gULMVciX+gW8Y+X9XfRYXxg5+HVEljoRkmqvXasO34aFwpPbZuAb+0ORbL+mTYY0Nh39WHLcH7uV0230KWRiHY9YN+VJYRadKUH1BDUJoWD53bwShkZemXfuPnsvRtBCZXNyHLBnQlNNi+2w3ENSye4w7iBR9J1TMfFqykX4qSJOcDThqDSYJFCklA8bh9EuTWlqYTx2kmCZah4CMdSbSxLIu4S26xHkrLCwwzVXT3o5fRi3accWNXzyM0RXil1Y1BTSxJ0FyH13F3u4VW40kSr6L2fi3RnIWCXRmn8Rt3TIIj1KFGSW2DetucNmBreW3Y/p7b+l93C+l1QHcvau/Fz4l+hXPz57xNQhsQSqbd0Ppm9CNA/SG4vDYbrZEa3xYX/1sbz3NZK0125VAI/7r8BayigAg=). 

However, I've noticed two small issues in the date picker code implementation:
1. **Text Computed Value**: In the current implementation, the `text` is a computed value that counts the first day of the month but it doesn't use the adapter abstraction to modify the date. So when using the Jalali adapter, the computation is incorrect.
```js
const text = computed(() => {
  return adapter.format(
    adapter.date(new Date(year.value, month.value, 1)),
    'monthAndYear',
  )
})
```
it should be:
```js
const text = computed(() => {
  let _date = adapter.date()

  _date = adapter.setYear(_date, year.value)
  _date = adapter.setMonth(_date, month.value)
  _date = adapter.setDate(_date, 1)

  return adapter.format(
    _date,
    'monthAndYear',
  )
})
```

2. **Header Computed Value**:
When we are passing the date value to v-model in the header, it's passing the model value to `adapter.format` without using the adapter abstraction to create adapter compatible date object, which results in an error.

```js
const header = computed(() => {
  return props.multiple && model.value.length > 1
    ? t('$vuetify.datePicker.itemsSelected', model.value.length)
    : model.value[0] && adapter.isValid(model.value[0])
      ? adapter.format(model.value[0], 'normalDateWithWeekday')
      : t(props.header)
})
```
it should be:
```js
const header = computed(() => {
  return props.multiple && model.value.length > 1
    ? t('$vuetify.datePicker.itemsSelected', model.value.length)
    : model.value[0] && adapter.isValid(model.value[0])
      ? adapter.format(
        adapter.date(model.value[0]),
        'normalDateWithWeekday')
      : t(props.header)
})
```

**Comment by pilevar** [comment]
Hey guys.

I've got the same problem.
I'm using Nuxt 3 and Vuetify V3.5.16.
When I want to change the date adapter into the vuetify.config.ts file, I get a warning with this message:
```
[vuetify-nuxt-module] Ignoring Vuetify Date configuration, date adapter "@date-io/class MomentUtils extends DefaultMomentUtils__default["default"]
```

<img width="911" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/1252853/4b858076-7001-47de-b6ef-75cba52e799e">
