### ISSUE TITLE
[Bug Report][3.4.9] textfield with type number, label does not stay active when you type e(floating number )

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#18943]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type the number starting with `e`

### Expected Behavior
The label should stay active 

### Actual Behavior
The input value is hidden. Check below gif

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNj8EOgjAQRH+l2bOFAxzUIIkXf8J6KHQNTdrStAtijP9ugRA5bfJmZ2f2/oEY2vzqfTYOCGeoCK03krAWjrFq5AGj713UI7LWyBgvAuzE5UC9AGblxF9aUZdoUZYCFtfiI5yIPzUatSLGjGzQpMWbDpGYkxYFbFqnFXKFJLWZE9bzm0hvjwm6wTYYNlxX+T5krZvQv29CVb57B74HKLIiO8E8y+wIjx/Pc1FU)

![chrome-capture-2023-11-28](https://github.com/vuetifyjs/vuetify/assets/80033712/e4615f82-1c83-4895-b89e-a48e466848fc)

**Comment by ShetlandJ** [comment]
For anyone else who investigates, this is standard HTML input behaviour. You can recreate using this code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Input Change Logger</title>
</head>
<body>

    <label for="myInput">Type something:</label>
    <input type="number" id="myInput">

    <script>
        document.getElementById('myInput').addEventListener('input', function() {
            var inputValue = this.value;
            console.log('Input value changed:', inputValue);
        });
    </script>

</body>
</html>
```

Console log examples:

![image](https://github.com/vuetifyjs/vuetify/assets/29278616/c464196b-8145-4267-a52e-abf83dc7ef74)

![image](https://github.com/vuetifyjs/vuetify/assets/29278616/220d8507-c79f-4fb0-830b-fec03e202cb9)

A work around with this would probably be to use a text field and add validations via regex, for example:

```html
    <v-text-field
      :rules="[rules.eNumber]"
      label="Input with e at start"
    />
```

```javascript
export default {
  data: () => ({
    eNumberRegex: /^e\d+$/,
    rules: {
      eNumber: value => this.eNumberRegex.test(value) || 'Your field must match the following pattern: the letter e then numbers only',
    },
  }),
};
````
