### ISSUE TITLE
[Bug Report][3.4.9] The problem with entering characters from the v-textfield keyboard inside the component working with the v-model

### ISSUE THREAD

**Issue by lna1989** [vuetifyjs/vuetify#18947]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.0-rc.3
**Browsers:** Yandex 23.9.1.1077, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Start typing "123" in the second field (CustomForm component).

### Expected Behavior
You will see the text "123" in the field.

### Actual Behavior
You will see an empty field.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1Ul1L7DAQ/Stzg9C9sG0veF9uWcWLKD4Kgj64PsRtWgL5IpkUZel/d5K6ZhV9aucjc86cM497Fvyu/e9cM0XBOrZBoZ3iKM63BmAz1dy5/JuDnTXIpRH+PZWTKF6wHqRQPUy1tr1QZ1umw7hl0Ja+yxjQ6mvr9Y9dm/YrQsosBDbtETEKw85LhxAExoWf1M56hD14McAMg7caKtqpOioecVjqTVtSSQBqTu1EIiAQOThL41bVjVDKwoP1qv9V/U5sFnxCZuus4Oc53wk5JNiLEJ+1xMZ5MQmDJMGJoHhVLXmazYraRdiDit3EVRRJuCTgfQq27FAkoYTpa2lIvVrSDqmvl7Xmo5HDa2mcuJc8g9uIisTuS+1CGhePeEXX0w5dwavWcJK5N8j9KLDJlIj3MuE8WVaIf7iYtv/ZRsXNSJgY6BqKpYsN+4I9kx+9GIjxrbcurPYLZmno4D0FgK+Owjv00ozrQ5Ie86iwgyqfBcCcPjM5mms0+Iq2DqvH7/Y+ePT05QDmNTtt/jZ/ar9rTukcUvCPPb0BBScbdg==)

### Other comments
I also want to note that if you quickly enter the same character, then every other time it gets into the field.

**Comment by KaelWD** [comment]
You need to use modelValue not value/input.
