### ISSUE TITLE
[Bug Report][3.4.8] DataTable with select-strategy="single" and return-object allows multiple checked rows

### ISSUE THREAD

**Issue by briankchan** [vuetifyjs/vuetify#18950]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.13
**Browsers:** Firefox 121.0
**OS:** Windows

### Steps to reproduce
Attempt to select 2 items

### Expected Behavior
The checkbox of the first item should get un-checked, and the second checkbox should get checked instead.

### Actual Behavior
The checkbox for the first item remains visually checked, and the second checkbox also gets checked. However, the model-value only includes the second value.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVlVtvmzAUx7+KhTSllQqBQNIUpZWmdpeue5i0p6ntgwMnCStgZJtUWZTvvuNwcUrc0j4B5+bf+ftg328twaPh56Jw1iVYoTWTkBUplXD1kBMyW9sxldSWdJ6CMhASroDGwMXlg1W/PVi1J8FcZY9BCOCydUQpFcoOKaypTFhueySb20HjX0GyXEkMCFy3sala9pqmJaA9pxk0Dg6y5LnN5n8hkpVJrNizLbB6a9i/20JybGS5wQoiyZfYQV1jbWcshlTZ95EQV56r2fCwYZRgL0Jx9bsOC8l226TsdrNhgSGz4YFk+CkinhQSGWSp3NhKVjAuyRbRF2RHFpxlZIBqD6ryEcuFRA32WpJLcl8xbqsHITKRKYRkcFOpSk48111ieb7Gnk4HZ00cTZNljnFCUi61WeDaqpmQLGgqoLU/wQaDlbJN7K5+btslr2nKeAJicNZWhzzGryo5atyG1K8USRWeMXNBpSnpmvK5eCMtUn5T4i/OJCT5G6lFFWFKvuUMMz+9lpmgu0l71BvWDLlhx5SoSgLO/kFO/rBlebghjWoh8cYXrRUVCcnkIAg7DckoaC11AyHRJkWG63hHG9gBuY2ARBxoRgTN4+ckWploRv75SxoNV9McBGgax/8wzxc8EBJuZJiMXjJ4x5Lo9VoIHVQjnPchXJdFRJ/a0T9k8N3xSwbf0X3XEJP3KTHtw/iGvzDwOe4NzpsBZaw7e0WOQO9SS+I72tjsyaQP5Qek6YbMgeZGkvOOKG4X5MIwqjqoxnD7KH6yNE0KVhgZLjrD4Tra0FBM30Ex6qP4znLYRCybmzACV69Rz8cRxtQwHxNHS1iDBOM+khuWl8azIxh3xBjp6jXE2DMN6dFojHrluEvkHR7YBoqx19FidDSgE83VUmh1aobOdOIxqw/a5r7FgxYv0JP7x1N151a3LN6v1u7M8h3f8XxLvQTO1Hr8D/T0fmw=)

### Other comments
It also doesn't seem possible to deselect the value--the last-clicked item remains in the model-value even after its checkbox has been un-checked.

**Comment by ShetlandJ** [comment]
A side-effect bug here is that if you untick the (wrongly visible) selected Frozen Yoghurt entry, it puts it back into your selected v-model.

**Comment by websitevirtuoso** [comment]
fixed in https://github.com/vuetifyjs/vuetify/pull/18908
I have no idea when it will be reviewed
