### ISSUE TITLE
[Bug Report][3.4.9] v-switch vertical direction not working

### ISSUE THREAD

**Issue by salarzobir** [vuetifyjs/vuetify#18952]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.0
**Browsers:** Edge 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set `direction` prop to `vertical`.

### Expected Behavior
The switch appears vertically just like `v-slider`.

### Actual Behavior
the switch itself doesn't affect, the label becomes vertical but each char on new line.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjssKwjAQRX9lmFULfQi6sbQF/8GddRHTEQN9hGQahdJ/N01VXM3cw3DuXGa0RuYnrTM3ERZYMvW6E0x1MwCULrVPxfIBLu3HlrqqwTAbhE7cQj6TZR9bZUiyGgePHBlWUvirusy/Ci8s8z+7j1YapTk00UuPhqGlu5g6hnllAK1gUUAUQ1VD9GEA4YMC2EyUbGyJw7KsFT8pLgnus0O2w20e8foGNZFNUQ==)

**Comment by De-Hann** [comment]
This doesn't seem to be a feature of the VSwitch component. Made a PR for this https://github.com/vuetifyjs/vuetify/pull/19504. Might need to change direction from horizontal and vertical to something like up, down, left & right if user wants to specify what is the "active" state
