### ISSUE TITLE
[Bug Report][3.4.9] Lazy Fetch 100% CPU with VVirtualScroll & Nuxt3

### ISSUE THREAD

**Issue by BlackYuzia** [vuetifyjs/vuetify#18958]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.3
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open / page
2. Open `/async-data-lazy` or `/fetch-data-lazy` to get a 100% CPU + page freeze bug

### Expected Behavior
Page load fast & don't consume 100% CPU for a 5-60+ seconds

### Actual Behavior
Page will consume 100% CPU and freeze for a 5-60+ seconds

### Reproduction Link
[https://gitlab.com/BlackYuzia/nuxt-3-useasyncdata-bug-reproduce/](https://gitlab.com/BlackYuzia/nuxt-3-useasyncdata-bug-reproduce/)

### Other comments
This bug reproduces only with nuxt3 `useLazyAsyncData (lazy: true)` or `useLazyFetch (lazy: true)` and `VVirtualScroll` from `Vuetify`. 
I make one [issue](https://github.com/nuxt/nuxt/issues/24879) on `nuxt3` repo. But, they [can't reproduce](https://github.com/nuxt/nuxt/issues/24879#issuecomment-1873877072) it without `VVirtualScroll` component and `vuetify`.

Don't sure, but suppose main issue in next line:
https://gitlab.com/BlackYuzia/nuxt-3-useasyncdata-bug-reproduce/-/blob/master/pages/fetch-data-lazy.vue?ref_type=heads#L70
```js
 return Array.from({ length: Math.ceil((arr.length || cols) / cols) }, (_, i) => arr?.slice?.(i * cols, i * cols + cols))
```

**Comment by KaelWD** [comment]
Duplicate of #18806
