### ISSUE TITLE
[Bug Report][v3.4.1] v-slot item is of type never or unknown

### ISSUE THREAD

**Issue by sreenivasulureddysura** [vuetifyjs/vuetify#18955]
### Environment
**Vuetify Version:** 3.4.1
**Last working version:** 3.4.0
**Vue Version:** 3.4.0
**Browsers:** Chrome 120.0.0.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Windows 10

### Steps to reproduce
npm run build is failing because of the unknow type

### Expected Behavior
npm run build code should work as expected
https://github.com/vuetifyjs/vuetify/discussions/18784

### Actual Behavior
template slot should work as expected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9lm1v2zYQx7/KQVjhBLDlZycRsm5rumVdB2yvChRNX9AyoxChSYGk3KaBv3uPEmVLtGgghdG8Ccm7P3m/uyOtT8+RVunwjzyPNwWNkuja0HXOiaGv7wTA9WawIoYMDFlyahcAkgdKVlTpX+8iN7qLnIWh1q6vqNZUmb0hU7LIB8sntJXDN0+1yUoGG8ILijZB1rQylIfj8XUwsBloLo3bqDoXBc+lvg+p5MVa6D4YmWWc3lqvPjBdDv7LqYDtXeT2tLuq3djOVpDgBjonArd0W8Wcisw8NFSl74c3RjQXADT7ZkPXa8J5DVX/bYhiRBg0G/rV+NaEpdKe2AjzzOKcw2/Q+4V+xXhWPUhwLFDd8+W/p5ylj3bvPXOlb3u+vh7aqFscz1Xi4jLx9rgbKQxhQkPGC0NFeextOYR7RWkPtttGxoZmtU/mcJdNHLZ6Z9hsHlxq2XGqU8VyU/oirVQGVvSeFNzAc7WhVZ+d1zMARU2hxH4O4LopgU8tvHamHik69BxZv22TCjsJrUSnbdO2MfvcGLueP36iYYZT3PVtdRHgbDwaZYDDDRPZuR8D4SwT6K0NUcY3asyLzV8C94Rr6lkrNHtvwtFjdLuAbgiXilHd6ztpWi8EJX8RjN8G7RT3xISdb4ha6pZ7alfCgv+VNJSJliSv1sKid0qi4tVewXCh7d4sWf0cHa+ZTaLFVfIbdv1HmRWHxaizlcB4fuXZMC8JLOLRgQT5E5jMvHUHmcDsQGJpMJLxK//4qoW7OsHLVCfZu5RCqihZg8aX5QtLH8J4k+lFF95VCO/AvYE3/Tl4f6acMHUEaTHpQhqHS+YHvmM6lDimiyCTUcXLkW6KPCWP3tVuMk1H8y6maeyXwyEtXl6my9Mi3eIDSNUS23B1BGu+eFmpZv5l3HFNY99Ut9/itGD/UM6fYEnJwU9Mg+uis1yjENZV8NE4lDis0Ylv1b+Sc5bL/AjUVee9GsX+cg11GYTqRpqcGOlvKehTKtfLMNNs5Afp7lWA6TJ4rxaxX3JHNZuftv/eSlEc+b2azTurNJmHem8+Dj8VgSs1CVfqh5DeM/MePzaCTPNxZ5UmwWdi4ddix+TXzxH94Bux//hwX82VESfXw91Hb7TtR9MY36fI/sekRp+/A3sZY5Y=)

**Comment by nativeB** [comment]
@sreenivasulureddysura were you able to resolve this? currently facing the same issue

**Comment by KaelWD** [comment]
I see `Group<any>`, if there's a problem here it's most likely caused by vuejs/language-tools.
