### ISSUE TITLE
[Bug Report][3.4.9] VCalendar: rendering issue when events minuts are not 00

### ISSUE THREAD

**Issue by AntoninHuaut** [vuetifyjs/vuetify#18967]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.4
**Browsers:** Firefox 121.0
**OS:** Windows 10

### Steps to reproduce
Create events with minutes other than 00, like end date is HH:30.
You can also adjust the interval division and the problem gets worse

### Expected Behavior
Events must be placed correctly according to the calendar's time scale.

### Actual Behavior
The placement of events is dysfunctional. An event with an end date in :30 will be placed in the second part of the interval instead of the first.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNk91ugkAQhV9lsjdoIohAk0rQpEnjC9SrihcURyXlL7MrXhjfvQPrX6tYEhJ2Tk72fBMOi4OQFA/fytKqdih8ESjMyjRSOA1zgKAyo7Jsjs0QF7mKkhzpJGkxSjFfRQSVmRUrTCehyOQmFFAluG8kVvaI3yz5WGGuJAv6EIppMLxecU6qpV9RtaJJguENIY8ypqRUIFHtNGiSlQUpOADhGo6wpiIDg5czajsA3ysV6HSYwEInHs77qESl6IMxS0gqY3CWpYpI+ZDjHt45umc4tuOZ9sh0nLnt+LbNz6fRv/h5mza357t/3XGRFsShXyljntTj6X1H9oG8wqoLmju3X+7D2tDY/dqORniJbCWbbxPqCvYg6gnYuB1sQ4j5v2izYkdq24XNa77nqCMbu7179xO25W0L+TfhCnJPe4uHe4+uXVn26+rrsnPNxXEgXMuzbJNiyxV6GIvlDwL9EOE=)

### Other comments
I think the problem is with the calcHeight method in the VCalendarIntervalEvent component.

**Comment by tiberiuarva** [comment]
When will this issue be resolved?
