### ISSUE TITLE
[Documentation] Vuelidate example TS issue

### ISSUE THREAD

**Issue by VividLemon** [vuetifyjs/vuetify#18969]
### Environment

**Browsers:** Firefox 121.0
**OS:** Linux x86_64

### Steps to reproduce
:error-messages="v$.name.$errors.map(e => e.$message)"

### Expected Behavior
Value should work just fine

### Actual Behavior
TS error

### Reproduction Link
[https://dev.vuetifyjs.com/en/components/forms/#vuelidate](https://dev.vuetifyjs.com/en/components/forms/#vuelidate)

### Other comments
The issue is that Vuelidate by default returns a string | Ref<string>, this is a type mismatch with the error-messages. Afaik, passing a ref through the slot should unwrap it, but I don't know the outcome with its a Ref[]. 
It would be nice if error-messages accepted a Ref[] as well, that way existing apps migrating (as I am doing) can make the transition easier

**Comment by KaelWD** [comment]
https://github.com/vuelidate/vuelidate/issues/1217

**Comment by VividLemon** [comment]
> [vuelidate/vuelidate#1217](https://github.com/vuelidate/vuelidate/issues/1217)

It seems more indicative of an issue with Vue (though not really an issue), rather than solely vuetify/vuelidate. The only way I can think of fixing it is by vuelidate unwrapping the ref with something like `reactive`. Tbh I think there's not much that can be done without a breaking change, which makes things difficult
