### ISSUE TITLE
[Bug Report][3.3.5] When opening navigation drawer Edge shows black overlays at 100% zoom on laptop screen.

### ISSUE THREAD

**Issue by vkdeveloper07** [vuetifyjs/vuetify#18974]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Google Chrome, Microsoft Edge
**OS:** Windows 11

### Steps to reproduce
1 - Open the link in both Edge and Chrome browsers (latest).
2 - Open the Navigation drawer by clicking hamburger icon.
3 - Observe the behavior

### Expected Behavior
In both browsers, the navigation bar should open without overlay on laptop screen having 100% zoom.

### Actual Behavior
In Chrome browser, the navigation bar is opening without overlay which is expected but in Edge its showing overlay on laptop screen having 100% zoom.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNplkDFPwzAQhf/K9ZaAROOhsCC3AsQAC2wwEAbLvVQWdnyy3TBU/e9ciZK26mTf+bv33vlrhzlZ9chc91vCe9SFAntTaNV0ALqfG+b/qxQfb6Z3G1Nc7J6T+aUE/TzENfllgy6/M3UNrrS6wKZ5sXkyY3lsCP9qYwcP1jv7U+cSeVKEJcxOtc8mRuGxPWRWY2itTpaRMtvkuECmsh12coFjKrCDRC3soU0xQCX/UB1wAHHIBULeSAghrqoX8j7CZ0x+Pauuj8gU9UC1xmeSR60GP3HC/Q0u6kV9i8N5h99/4MR71A==)

**Comment by vkdeveloper07** [comment]
I am afraid I cannot post the screen shot of the application. But attached is the app structure. With this structure, the app works fine in chrome i.e it automatically open navigation bar by default and does not show overlay,
but shows overlay in Edge with nav bar closed by default.

![app-structure](https://github.com/vuetifyjs/vuetify/assets/52969107/25799a16-248d-4cb9-9564-bf9d67995854)

**Comment by KaelWD** [comment]
"laptop screen" means nothing, if it's close to 1280px a 1px difference in viewport width is enough to explain this.

**Comment by vkdeveloper07** [comment]
viewport on chrome is 1280px but on edge its 1272px. I guess that's causing the issue.

**Comment by KaelWD** [comment]
Well there you go then, not a bug.
