### ISSUE TITLE
[Bug Report][3.4.9] VTabs layout breaks with non-default density

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#18970]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.4
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set `VTab` default `density` to `"comfortable"`, see the line under selected tab is way higher than expected

### Expected Behavior
Line under selected tab stays at the bottom of `VTabs` when using custom density for tabs or buttons.

### Actual Behavior
Line under selected tab is way above the bottom of `VTabs` when using custom density for tabs or buttons.
![image](https://github.com/vuetifyjs/vuetify/assets/7756211/c43b298b-70be-48de-a4bd-f8aa43c2bc3a)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUrFOwzAQ/ZXDS4pUkoEuVCkSG0wsURkIg5te2iDHtmynpary75ztJGqRUJfY797zyz37Ps/Mmio7dOia+pR+W7ZkTauVcXCGyiB3uI4c9FAb1UIyaJNSlhJ/grRS0joYCFhdH5ydSwng9tjiEsIeYIs174QrYjERzW7vknnkssyvfUCDzk4H1wXfTMDz0jbuRBaVamtqhW8EjkbRwn/7+1KyeUj6onVKjVLM3GGrBfX57GX54YFrHbYBUCTHG4lmKIUi2VvY7IgUyqxKpk3TcnMq2SQaZXDgokOSKIlEv9G/4F1ingX2f7k7qlFeHNVt+d7g5F948PfIgO2YjOB1NF+JyfPs4kYI2so02oFF18WLmQbDYH05DmEUYJiC1u5oAkgxS15RCAUfyojtXUJPkGfRksxYP2eP6SJd0LP49Yl9/QLnNNHa)

### Other comments
In my actual case I modified `$button-density` SCSS variable to have `"default": -1`

This creates a "loop" kinda. Here you set `--v-btn-height: var(--v-tabs-height)`: https://github.com/vuetifyjs/vuetify/blob/v3.4.3/packages/vuetify/src/components/VTabs/VTab.sass#L6

but then because of this https://github.com/vuetifyjs/vuetify/blob/v3.3.13/packages/vuetify/src/components/VBtn/VBtn.sass#L33

the button height will always be `--v-tabs-height` plus the modifier. So with my default `-1` modifier buttons inside of tabs are always 4px smaller.

**Comment by Maxim-Mazurok** [comment]
I think the kinda-core problem is that `$modifier` is included in `--v-tabs-height: #{$tabs-height + $modifier}` in here: https://github.com/vuetifyjs/vuetify/blob/v3.4.9/packages/vuetify/src/components/VTabs/VTabs.sass#L13

**Comment by Maxim-Mazurok** [comment]
It seems like there is a hard requirement, that `v-btn` inside of `v-tab` should follow the total height from `v-tab`, they have to match exactly.
This means that `v-btn` in this case can't have its own independent `density`. Otherwise `v-tab` will need to know about `v-btn` implementation to correctly set `--v-btn-height` taking into account all modifiers that will be applied to it when calculating the actual `height`. This seems to be an overkill to me.
So quick and dirty workaround also seems to be pretty close to a proper solution:
```patch
This is a patch for v3.4.3 but is same code for latest
diff --git a/node_modules/vuetify/lib/components/VTabs/VTab.sass b/node_modules/vuetify/lib/components/VTabs/VTab.sass
index e8539dc..5ca4acd 100644
--- a/node_modules/vuetify/lib/components/VTabs/VTab.sass
+++ b/node_modules/vuetify/lib/components/VTabs/VTab.sass
@@ -3,7 +3,7 @@
 .v-tab
   // override v-btn size specificity
   &.v-tab
-    --v-btn-height: var(--v-tabs-height)
+    height: var(--v-tabs-height)
     border-radius: $tab-border-radius
     min-width: $tab-min-width
 ```

The only downside is that we're losing CSS variable here, and as I understand Vuetify has a direction of using more CSS variables as the truth source. However in this case I think it doesn't make sense to have it anyway, button height inside of tab should be overriden to have tab height, so one would use `--v-tabs-height` instead if they wish to override it...

Any thoughts from maintainers, please? If this makes sense - I'll be happy to make a PR.

**Comment by KaelWD** [comment]
Yeah I think that should be fine, it doesn't really make sense to set density on individual tabs anyway.

**Comment by Maxim-Mazurok** [comment]
Thanks, working on a PR now

**Comment by Maxim-Mazurok** [comment]
[It is ready for review now](https://github.com/vuetifyjs/vuetify/pull/18971)
