### ISSUE TITLE
[Feature Request] Let User change Teme via Color Picker

### ISSUE THREAD

**Issue by SaiCode-DEV** [vuetifyjs/vuetify#18976]
### Problem to solve
I Tried to allow the users not only to switch between dark and light mode, but to also customize the Primary and Secondary Color via a Color Wheel. 

So far the only solution was to create 10 themes to give more color options or to store the color preferences and override the color in each component manually. 

Is there a easier way to change the primary and secondary (accent) color on the go?

### Proposed solution
make the colors not read only. 
=> something like name exposed 
theme.global.current.value.colors.primary = color.value;

**Comment by KaelWD** [comment]
`theme.themes` is not readonly
