### ISSUE TITLE
[Bug Report][3.4.9] V-card-text and v-card-actions do not have the same padding

### ISSUE THREAD

**Issue by Bart-Westenenk** [vuetifyjs/vuetify#18994]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.5
**Browsers:** Firefox 121.0
**OS:** Linux x86_64

### Steps to reproduce
1. Make a card with a v-card-text element and v-card-actions element
2. Fill the v-card-text with something
3. Fill the v-card-actions with something

### Expected Behavior
I expected the button (from the reproduction link) to have the same indentation as the text.

### Actual Behavior
The button is indented 0.5rem while the text is indented 1rem

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUctOwzAQ/JXFl4BEEyHgAEoj9cYZDhwIB+NuK0t+ab2NQFX/HTsmJS2cvLOzs2OP3/YikmpWIdTDDsWjaBltMJKx6x1AOyxkCGM5AuUdS+2QflqlKWl9xMfOgjUb7J5xqyMTErq2OWH+UeAnd/DiLUIu4VeQib/zUrH2Ls6YkftgB4MkLR0ve8HeSdMLUN54SjiQtpK+etGtRjncZJukOV8Tg1RI0MyNpwudO0/ElFSGJ1HlTkmybWYJJxgV6cAQkXclaG2DJ4Y9EG7gABvyFqr0OVUeh/QOFxls3MIyT1xWT2iMh1dPZn1RXWWDsjItE4drcVvf1feinA/i/Rtlf5tF)

### Other comments
According to the docs, this should have worked. The docs did not use any other styling and does have the same indentation.

**Comment by johnleider** [comment]
Card actions apply the **slim** and **variant="text"** props as part of MD2 spec. There are use-cases that aren't covered by this default behavior so it's recommended to use a different element for spacing.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
