### ISSUE TITLE
Event to capture the fact a dialog has closed 

### ISSUE THREAD

**Issue by dmundy2** [vuetifyjs/vuetify#1899]
I have a quick question around the dialog component. 

I currently have a non-persistent dialog. One that closes when clicking off the dialog. 

Is there an event that occurs when a dialog is closed in this way? How would I detect that something like this has happened (So that I can let the other components know we have closed the dialog)

**Comment by jacekkarczmarczyk** [comment]
To answer your question, you can watch the dialog `v-model`. However, the issue board is strictly for bugs. If you hop over to the community, there are plenty of people who can be of help, https://chat.vuetifyjs.com
