### ISSUE TITLE
[Feature Request] Export useColor and other color-related composables from vuetify package

### ISSUE THREAD

**Issue by PWie** [vuetifyjs/vuetify#18997]
### Problem to solve
Vuetify uses awesome color computing utils that translates color names (both theme and pallete) into valid css classes or style definitions, together with calculating proper foreground color specified background, etc, (`useColor` composable).
It would be awesome to be able to easily use this composable (and others like `useTextColor`, `useBackgroundColor`) in custom components and other places.

### Proposed solution
Export the `useColor`, `useTextColor` and `useBackgroundColor` so that it is possible to import it from vuetify package

**Comment by Drillan767** [comment]
Seconding this, plus exporting all the available colors from Vuetify's palette as it was in Vuetify 2, in a composable such as "usePalette" or something.
