### ISSUE TITLE
[Bug Report][3.4.9] Font appears blurry in dark mode in Chrome and Edge (not in Firefox)

### ISSUE THREAD

**Issue by lecaillon** [vuetifyjs/vuetify#18992]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.5
**Browsers:** Google Chrome, Microsoft Edge
**OS:** Windows

### Steps to reproduce
In dark mode with Chrome and Edge only (tested only in Windows), text appears a bit blurry in button but not only. In combobox, autocomplete etc
A good example is the official Vuetify documentation : https://vuetifyjs.com/en/components/buttons/#usage
See how the `tonal` button appears blurred in dark mode and perfect in light mode. Particularly the letter `a`, where the inner hole disappears almost completely in dark mode. 

![chrome-light-dark](https://github.com/vuetifyjs/vuetify/assets/19413950/f054b496-274f-4c9c-8c08-f2935b298c53)

### Expected Behavior
Text in dark mode should display like in light mode in Chrome and Edge (works fine in Firefox)

### Actual Behavior
text in dark mode is blurry in Chrome and Edge under Windows 11

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVTruuwjAM/RUrS++VSjKUBVSQ+AIWxEIYQnFFoUlDYhBQ9d9J0yLBZJ+Hj8+uZd4V4n5DqsonP3s2Z5W2jSNooXCoCLeDBh2UrtGQjN5EGmnwEa1FYzzBKMDi9/CvlQaATqhxDnEHOGKpbjVtBjI5KndJ0kESop9dQN2/NCyN/VbW8hAfyuWE2tYhfdnb8vtEWRvXCEIRUpVBN1KRPJABX71wIdlj4rWqa8mWsD5cLeQiyp+AgH4TemZ4kIuvx6xLWcYzPgv1Mj4Nc/8G7mhr1Q==)

**Comment by miroslavgeorgiev** [comment]
This doesn't seem related to Vuetify, in my opinion.

The text looks just as blurry in dark, as in light - probably related to how Windows renders characters on your monitor resolution.
Try turning on ClearType, if not (it is on by default).

**Comment by lecaillon** [comment]
ClearType is on. And there is clearly a difference between the 2 mode (at least in my case). It is like in dark mode the font-weight is higher. 
In my "test" i can see it is somehow related to the transparent background added in the selectedItem in case of the Autocomplete component
In the example below I removed the class `bg-transparent` . You can see the second `sequel.db` text becomes clear after I remove that class

![Blurry](https://github.com/vuetifyjs/vuetify/assets/19413950/6372e8a7-c330-48d7-b1f0-8f72573ab0bc)
