### ISSUE TITLE
Support for Community Material Design Icons

### ISSUE THREAD

**Issue by Async0x42** [vuetifyjs/vuetify#19]
The base material design icon set is pretty limited, but https://github.com/Templarian/MaterialDesign supplements it nicely with community additions.

Perhaps this could be made the default icon library, to provide more choices out of the box that's still consistent with the design?

**Comment by johnleider** [comment]
I had actually not heard of that until just now. I'll have to look through it, but looks nice.

**Comment by johnleider** [comment]
After much consideration, I think that this choice should be on the developer.
