### ISSUE TITLE
[Bug Report][3.4.9] Input text alignment on safari

### ISSUE THREAD

**Issue by steviemarshall** [vuetifyjs/vuetify#19003]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.0
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OSX

### Steps to reproduce
Type in input field and the alignment of the text is positioned to the left with no spacing

### Expected Behavior
I would expect it to work the same as windows

### Actual Behavior
.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8GKwzAMRH9l0CUtNMlhF5YNaWAv+xObPbiJDAY7MY4aCiX/3sRuS3uS9DRiRn9XmkJX/nhfzGemimph560SbtoBqOdceR/bOHTjIMoMHO4oQuGL5Nqw7THnbuzZHlvSJkwyKMctwapTZL8bQ4IN6vL19OGxwneTjaQMdfmSbR2nLhgvUWScH4PgisAaC3QYHbL1oWwTAnyJ6561OttVlrx6JarCbo9jg92dAc/gFbLskOiyj82yZXi60nKgj+Kz+KJUv+n/BiERaos=)

**Comment by steviemarshall** [comment]
![3a5142d9-d680-4316-b16b-7f2c40f2a7d3](https://github.com/vuetifyjs/vuetify/assets/189005/182bd712-490b-4ca5-8df1-64854e758126)

This a screengrab of what his happening on ipad.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/browser-support/

Looks like whatever that is is missing [`padding-inline`](https://caniuse.com/mdn-css_properties_padding-inline).
