### ISSUE TITLE
[Bug Report][3.4.9] Non-clickable list items get a hover effect when marked as active

### ISSUE THREAD

**Issue by jay-zahiri** [vuetifyjs/vuetify#19005]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.7
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Hover over an active list item and compare hovering over a non-active list item.

### Expected Behavior
List items marked as active are expected not to have a hover effect, as the list items are not clickable.

### Actual Behavior
List items marked as `active` get a hover effect because they generate the `v-list-item__overlay` element by `genOverlays`.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkb0KgzAUhV/lksWlKq2W0hKEjn2GtkMIEQL+XJKri/jujUkVCw520ZyP72Q4eQ7MGpneEZO+U+zGOKkaK0GqeDUAvI8Foj/6INuGhG6U+SIPK21pyQuJtbupeLgPHHm6ZtsqCEm6V6Fx+ruR7WkENd+vnrfVmc7DuPi7zETCcDxdDeqilUYjgVXUhV11ja0hGMCoEkYoTVtD5N4imrrBdh4bDyxL8uTCwv/K3h/XRIue)

### Other comments
I don't know if this is intended. I noticed that `isActive` is checked when calling `genOverlays`

```ts
genOverlays(isClickable.value || isActive.value, 'v-list-item')
```

[Link to VListItem.tsx](https://github.com/vuetifyjs/vuetify/blob/dc619a2cb50f888aad176c920df8dead9f0e9ed9/packages/vuetify/src/components/VList/VListItem.tsx#L229C19-L229C19)

**Comment by De-Hann** [comment]
Hey @jay-zahiri, from what I see in the docs this is expected behavior. Refer to https://vuetifyjs.com/en/api/v-list-item/#props-active

**Comment by jay-zahiri** [comment]
Hi @De-Hann 

The docs state the following about property `active`
> Controls the active state of the item. This is typically used to highlight the component.

It doesn't say anything about any hover effect.

The use case is when your list items don't have any click actions. Nothing happens when you click on them; it's just a static list of some things and none of the list items have any hover effect. But if you then set one list item as `active`, it behaves like something will happen when you click on it, i.e., hover effect.

I'm not saying an active list item shouldn't be highlighted; I'm talking about the hover effect being applied on top of the highlight when set `active`.

**Comment by De-Hann** [comment]
Made a PR for a fix https://github.com/vuetifyjs/vuetify/pull/19506
