### ISSUE TITLE
[Bug Report][3.4.9] v-data-table sorting data incorrectly with foreign chars

### ISSUE THREAD

**Issue by simenkf** [vuetifyjs/vuetify#19008]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.7
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
See playground link. Click table header to sort. It will consider 'Å' < 'A' and 'Æ' < 'E'. 

### Expected Behavior
Letters such as Å and Æ should come after A and B lexicographically. Thus, when sorting the table in the playground, the order should be ASKER, BERGEN, BÆUM, ÅLESUND.

Æ, Ø and Å comes at the very end of the Norwegian alphabet.

### Actual Behavior
It sorts it incorrectly as ÅLESUND, ASKER, BÆRUM, BERGEN.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAlsSRRtyQxKScVJqigYJWRmpiSWlRsG6MUXV2SWZKTaqWg7peYm6quo5CdWgnk5IE4tbExSkiaMoGWQ7SAZIGKHIO9XYPUa3UUYAKHW31cg0P9XJDFnA63BYX6ooi4Brm7+qGYrg/zhD66L0AiEE/a6CN5XqlWR8lYz0TPXAlCWyrFAgALjVsr)

**Comment by KaelWD** [comment]
It uses the current locale set in https://vuetifyjs.com/en/features/internationalization/
