### ISSUE TITLE
[Bug Report][3.4.9] Hydration class mismatch on VslideGroup, VNavigationDrawer

### ISSUE THREAD

**Issue by Josepdal** [vuetifyjs/vuetify#19002]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.7
**Browsers:** Chrome 120.0.0.0
**OS:** Windows

### Steps to reproduce
Visit the reproduction Link.
IMPORTANT: The viewport have to be large. I have extended the browser to my second monitor to increase the website width size.

### Expected Behavior
There should be no vue warns

### Actual Behavior
There are mismatch vue warns

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-14rqc1](https://stackblitz.com/edit/nuxt-starter-14rqc1)

### Other comments
This happens since Vue 3.4.5

[Vue warn]: Hydration class mismatch on <div class=​"v-slide-group v-slide-group--has-affixes v-slide-group--is-overflowing" style tabindex=​"0">​…​</div>​
- rendered on server: class="[object Set]"
  - expected on client: class="[object Set]"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <VSlideGroup show-arrows="" >

This also happens with other components, VNavigationDrawer and VBanner, all of them using computed display classes --mobile.
Don't know if this has anything to do with: /vuetify/src/composables/display.ts
const displayClasses = computed(() => { ... }

Another similar bug has been solved recently in Vue v3.4.6
https://github.com/vuejs/core/issues/10006

As I don't know how to reproduce the error without Vuetify and have no idea what is exactly the root cause of this issue, I am opening the same issue in both projects.

Link to Vue issue: https://github.com/vuejs/core/issues/10051

**Comment by Josepdal** [comment]
Ok that was quick, thank you. Don't know how it worked before.

**Comment by Josepdal** [comment]
Hello again @KaelWD, that code fixed the error I had with VSlideGroup, but now I have many other mismatch warns in other components.

Examples:

Hydration attribute mismatch on <input...
https://stackblitz.com/edit/nuxt-starter-14rqc1

Also migueabellan is having same issues with VNavigationDrawer and VAppBar.

Hydration attribute mismatch on <header...
Here is his code: https://stackblitz.com/edit/nuxt-starter-wtdujy

We are talking about this in a thread at Discord/vuetify-3-help

Thanks for your help!

**Comment by migueabellan** [comment]
Hello @KaelWD, I add to @Josepdal examples, Hydration style mismatch whit VNavigationDrawer and VAppBar together.

**Steps to reproduce** 

Follow https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3 and minimal code

const vuetify = createVuetify({ ssr: true })

```
// app.vue
<template>
  <v-layout>
    <v-navigation-drawer />
    <v-app-bar />
    <v-main />
  </v-layout>
</template>
```

**Reproduction Link**

https://stackblitz.com/edit/nuxt-starter-wtdujy

Thanks for your help!

**Comment by antonin-11** [comment]
Same error
