### ISSUE TITLE
[Bug Report][3.4.9] v-date-picker chinese language package is wrong

### ISSUE THREAD

**Issue by AndyBeat** [vuetifyjs/vuetify#19013]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.6
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Expected Behavior
Translation correct weekend

### Actual Behavior
Weekend translation error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAnPzkxJ1W3oCi/LDMltUgBwreNUarK8EjMK45RgisGK08BGq5bkJmcDVRaklkCVvlsa/eL9VNjlBQyUhOBRgBFgLps9FEUI6wEiqPZCXMhUAbViSARiA9s9JF8plSro2SsZ6JnrgShLZViAf9BVmY=)

### Look at the picture
![1704852850204](https://github.com/vuetifyjs/vuetify/assets/59676227/804f0499-c5bf-4353-bd57-005650653fff)

**Comment by yawkale** [comment]
also Hebrew - in 3.4.8 is working
the issue is in getWeekdays packages/vuetify/src/composables/date/adapters/vuetify.ts
it's wrong to take first letter

**Comment by AndyBeat** [comment]
@blalan05 The problem has not been solved, and there is still no translation into Chinese.
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAnPzkxJ1W3oCi/LDMltUgBwreNUarK8EjMK45RgisGK08BGq5bkJmcDVRaklkCVvlsa/eL9VNjlBQyUhOBRgBFgLps9FEUI6wEiqPZCXMhUAbViSARiA9s9JF8plSro2SsZ6JnrgShLZViAf9BVmY=)

**Comment by KaelWD** [comment]
Would you expect "周一, 周二, 周三, 周四, 周五, 周六, 周日" or just "一, 二, 三, 四, 五, 六, 日"?

**Comment by AndyBeat** [comment]
I expect is "一, 二, 三, 四, 五, 六, 日", same as version 3.4.8.
