### ISSUE TITLE
[Bug Report][3.4.10] Nuxt 3 / Vuetify: Hydration attribute mismatch on readonly

### ISSUE THREAD

**Issue by swissmexxa** [vuetifyjs/vuetify#19014]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.3.7
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open Chrome Dev Tool and see hydration warning in console

### Expected Behavior
No hydration warning

### Actual Behavior
```
Hydration attribute mismatch on <input name=​"test" size=​"1" type=​"text" id=​"input-0" aria-describedby=​"input-0-messages" class=​"v-field__input">​flex 
  - rendered on server: readonly=""
  - expected on client: (not rendered)
```

### Reproduction Link
[https://stackblitz.com/edit/github-onmumt?file=package.json](https://stackblitz.com/edit/github-onmumt?file=package.json)

### Other comments
If playground keeps hanging in nuxt loading screen just open chrome dev tools or vice versa.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/commit/972facee0d892a1b6d9d4ad1da5da9306ed45c3f
