### ISSUE TITLE
[Bug Report][3.4.9] Hydration style mismatch VNavigationDrawer and VAppBar together

### ISSUE THREAD

**Issue by migueabellan** [vuetifyjs/vuetify#19015]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.7
**Browsers:** Chrome 117.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1.- Follow instructions exactly from https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3 
2.- Add ssr on plugin `createVuetify({ ssr: true })`
3.- Add minimal code on app.vue with VNavigationDrawer and VAppBar together 

```
<template>
  <v-layout>
    <v-navigation-drawer />
    <v-app-bar />
    <v-main />
  </v-layout>
</template>
```

### Expected Behavior
There should be no vue warns

### Actual Behavior
There are mismatch vue warns

[Vue warn]: Hydration style mismatch on <header class=​"v-toolbar v-toolbar--density-default v-theme--light v-locale--is-ltr v-app-bar" style=​"top:​ 0px;​ z-index:​ 1004;​ transform:​ translateY(0%)​;​ position:​ fixed;​ left:​ 0px;​ width:​ calc((100% - 0px)​ - 0px)​;​">​…​​flex

rendered on server: style="[object Map]"
expected on client: style="[object Map]"

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-wtdujy](https://stackblitz.com/edit/nuxt-starter-wtdujy)

### Other comments
Only occur using VNavigationDrawer and VAppBar together

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/5300 doesn' actually seem to be fixed

**Comment by jscottsf** [comment]
On latest of everything and it's just class mismatch on everything. Really impossible to debug and dev because of the log spew on all components.

Never saw this problem before until recent updates.

```
+onRenderClient.js:18 [Vue warn]: Hydration class mismatch on <div class=​"v-progress-linear v-progress-linear--rounded rounded-md v-theme--light v-locale--is-ltr" style=​"top:​0;​height:​0;​--v-progress-linear-height:​2px;​left:​50%;​transform:​translateX(-50%)​;​" role=​"progressbar" aria-hidden=​"true" aria-valuemin=​"0" aria-valuemax=​"100">​…​</div>​ 
  - rendered on server: class="v-progress-linear v-progress-linear--rounded rounded-md v-theme--light v-locale--is-ltr"
  - expected on client: class="v-progress-linear v-progress-linear--rounded rounded-md v-theme--dark v-locale--is-ltr"
```

**Comment by danilpon98** [comment]
I encountered the same problem when using the VItemGroup and VItem component. I change the color of the button depending on the isSelected flag.

```
- rendered on server: class="v-btn v-btn--elevated v-theme--light bg-background v-btn--density-default v-btn--size-large v-btn--variant-elevated v-btn--customize flex-1-1"
- expected on client: class="v-btn v-btn--elevated v-theme--light bg-primary v-btn--density-default v-btn--size-large v-btn--variant-elevated v-btn--customize flex-1-1"
```

**Comment by Zebnastien** [comment]
FYI, vuejs/core#5300 is marked as closed and issue is still present with:

Vue 3.4.19
Nuxt 3.10.2
Vuetify 3.5.4

**Comment by KaelWD** [comment]
15229 fixed this too

**Comment by thorge** [comment]
Same over here with `vuetify@3.5.11`:

```console
[Vue warn]: Hydration style mismatch on 
<header id="nav-main" class="v-toolbar v-toolbar--fla… v-app-bar text-primary" style="top:0;z-index:1006;trans…sition:none !important;" app="" data-v-a254f246=""> 
  - rendered on server: style="top:0;z-index:1006;transform:translateY(0%);position:fixed;transition:none !important;"
  - expected on client: style="top:0;z-index:1004;transform:translateY(0%);position:fixed;transition:none !important;"
```

**Comment by nbro** [comment]
See https://github.com/nuxt/nuxt/issues/26483

**Comment by ElYaiko** [comment]
Still happening in `3.5.13` with any `app` component like `VAppBar`:

```
[Vue warn]: Hydration style mismatch on <header class=​"v-toolbar v-toolbar--flat v-toolbar--density-default bg-transparent v-theme--dark v-locale--is-ltr v-app-bar position-fixed d-print-none" style=​"top:​ 0px;​ z-index:​ 906;​ transform:​ translateY(0%)​;​ position:​ absolute;​ left:​ 0px;​ width:​ calc(100% + 0px)​;​">​…​</header>​flex 
  - rendered on server: style="top:0;z-index:906;transform:translateY(0%);position:absolute;transition:none !important;"
  - expected on client: style="top:0;z-index:904;transform:translateY(0%);position:absolute;transition:none !important;"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.```

**Comment by chriscpty** [comment]
> Clearly an issue with SSR ids and client rendered ids that are used in classnames (they mismatch when the app is mounted).

yeah, all the issues related to this i'm seeing amount to this. the worst offender I think are v-tooltips - in my project, the SSR issue gave them all the same ID, leading to not only loads of warnings but also all of them displaying the same tooltip :D

For now, wrapping them in a v-no-ssr is a workaround for that last issue, but obviously still throws a hydration mismatch warning.

**Comment by alokVishu** [comment]
I'm also facing the same.

**Comment by ZumelzuR** [comment]
me too

**Comment by ribrewguy** [comment]
I am seeing this as well. VMain appears to exhibit this behavior. Removing it resolves the warning.

**Comment by psgganesh** [comment]
Only the below steps fixed for me...

I updated package.json to use vuetify": "3.6.5" and ran `npm run update` and it was fixed!!

**Comment by rudolfbyker** [comment]
Still seeing this in v3.6.6, too.

**Comment by tommie** [comment]
If you followed the [Nuxt 3 Installation guide](https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3), and came here... Don't forget to add `ssr: true` in `createVuetify()`.

**Comment by rudolfbyker** [comment]
@tommie In my case, I already had `ssr: true`, and still getting `Hydration style mismatch` warnings related to the `z-index` CSS attribute.

This made me think: Should it really be `ssr: true`, or rather `ssr: !!process.server`?

**Comment by tommie** [comment]
> Should it really be ssr: true, or rather ssr: !!process.server?

The code already does the in-browser check on top of `options.ssr`:

https://github.com/vuetifyjs/vuetify/blob/665c616254e5a5727482c4f5d894d1e958675edb/packages/vuetify/src/framework.ts#L88

https://github.com/vuetifyjs/vuetify/blob/665c616254e5a5727482c4f5d894d1e958675edb/packages/vuetify/src/util/globals.ts#L1

Same where it tries to retrieve the display details:

https://github.com/vuetifyjs/vuetify/blob/665c616254e5a5727482c4f5d894d1e958675edb/packages/vuetify/src/composables/display.ts#L102-L121

**Comment by rudolfbyker** [comment]
OK, I don't fully grasp what the code in the body of `if (IN_BROWSER && options.ssr) {` does, but the fact that there is a check for `IN_BROWSER && options.ssr` tells me that I should NOT set `ssr` to `False` in the browser, otherwise the code inside `if (IN_BROWSER && options.ssr) {` can never run. So it must be `ssr: true` and not `ssr: !!process.server`. :thinking:

**Comment by corbinu** [comment]
I am also seeing this on v-tabs where the selected tab is missing the selected classes on the server side.

**Comment by bogdanciuca** [comment]
Still present in `v3.6.9`, `VChipGroup` is also causing hydration issues.

**Comment by Miltonbhowmick** [comment]
> I am also seeing this on v-tabs where the selected tab is missing the selected classes on the server side.

I am also facing on v-tabs!

**Comment by benlavalley** [comment]
Nuxt 3.4.12 / Vuetify 3.6.13 / Vue 3.4.34 and my v-navigation-drawer only works if I wrap it in ClientOnly.

**Comment by Mitschiro** [comment]
Hello,
Vuetify: 3.7.2
Nuxt: 3.13.0
vue: 3.5.12

I get the same with v-data-table

![image](https://github.com/user-attachments/assets/72bf5ee5-c75b-4f97-8464-33e805c23d90)

Also with the v-navigation-drawer, v-main and v-tabs

![image](https://github.com/user-attachments/assets/3b5e3245-1880-4cf3-b553-39690bc7d14c)

![image](https://github.com/user-attachments/assets/62c2c4fe-9368-4863-84ce-ae5afc0255a1)

![image](https://github.com/user-attachments/assets/3336c4d4-eaf1-4804-8e7d-36503c84d448)

**Comment by TheRoccoB** [comment]
Still happening for me in Vuetify 3.7.4 + Nuxt. Using mobile-breakpoint seems to be doing a good job working around this issue without forcing `<ClientOnly>` (I want the drawer to render server side for SEO).

```
      <v-navigation-drawer width="300" :mobile-breakpoint="computedMobileBreakpoint">
        <v-list>
          <v-list-item title="Navigation drawer"></v-list-item>
        </v-list>
      </v-navigation-drawer>
```

```
const computedMobileBreakpoint = computed(() => {
  return process.server ? 0 : 1264; // On server, force desktop mode; on client, use default breakpoint
});
```

**Comment by DylanWarrener** [comment]
Same issues here. I am using versions:

- Vue (latest)
- Vuetify (3.7.5)
- Nuxt (3.14.1592)

I kep removing components from my website until the error dissapears. Found out that it was the `v-tooltip` throwing the errors.
![hydration-mismatch](https://github.com/user-attachments/assets/32a61697-2ab5-46fe-974d-1a545167c566)

**Comment by x-wink** [comment]
same problem, why closed this issue?
`createVuetidy({ssr: true})` don't work
"vuetify": "^3.9.5"
"vue": "^3.5.20"
"nuxt": "^4.0.3"

**Comment by jpujol880807** [comment]
> On latest of everything and it's just class mismatch on everything. Really impossible to debug and dev because of the log spew on all components.
> 
> Never saw this problem before until recent updates.
> 
> ```
> +onRenderClient.js:18 [Vue warn]: Hydration class mismatch on <div class=​"v-progress-linear v-progress-linear--rounded rounded-md v-theme--light v-locale--is-ltr" style=​"top:​0;​height:​0;​--v-progress-linear-height:​2px;​left:​50%;​transform:​translateX(-50%)​;​" role=​"progressbar" aria-hidden=​"true" aria-valuemin=​"0" aria-valuemax=​"100">​…​</div>​ 
>   - rendered on server: class="v-progress-linear v-progress-linear--rounded rounded-md v-theme--light v-locale--is-ltr"
>   - expected on client: class="v-progress-linear v-progress-linear--rounded rounded-md v-theme--dark v-locale--is-ltr"
> ```
> 
> UPDATE:
> 
> If I start manually assigning `id` properties on some components, like an autocomplete, then the problem goes away. Clearly an issue with SSR ids and client rendered ids that are used in classnames (they mismatch when the app is mounted).
> 
> The issue above, was due to light theme on the SSR, and a dark theme being set in an onMounted handler in the client, which is reasonable if using localstorage to remember theme state. This used to work.

I faced similar uses when updating the theme from light to dark and using pinia. I found a nice article from nuxt team explaining the warning with an example using the theme [https://nuxt.com/docs/4.x/guide/best-practices/hydration](url) from there I used the following code and solved the issue for this case and the `pinia-plugin-persistedstate` module.
 ```
import {defineStore} from 'pinia';
import {ref, watch} from 'vue';
import {useTheme} from 'vuetify';

export const useThemeStore = defineStore('theme', () => {
    const theme = useTheme();
    const cookie = useCookie('theme');
    const initialTheme = cookie.value?.darkMode ? 'dark' : 'light';
    const darkMode =  initialTheme === 'dark' ? ref(theme.global.current.value.dark) : ref(theme.global.current.value.ligth);
    theme.change(initialTheme);
    watch(darkMode, (newValue) => {
        theme.change(newValue ? 'dark' : 'light');
    });

    return {
        darkMode
    };
}, {
    persist: {
        storage: piniaPluginPersistedstate.cookies(),
    }
});
```
I also solved the issue when reloading pages the default light theme was loading before rendering the page
