### ISSUE TITLE
[Bug Report][3.4.10] VTabs - When wrapping VTab in another element the animation of the slider fails

### ISSUE THREAD

**Issue by MarcHartwig13** [vuetifyjs/vuetify#19012]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.7
**Browsers:** Firefox 121.0
**OS:** Mac OS 10.15

### Steps to reproduce
Wrap the `<v-tab>` component in another element. Then notice the active slider/border for the tab does not animate correctly when changing tabs.

I did some investigating and it looks like `querySelector` fails on line 46 in vuetify/lib/components/VTabs/Vtab.mjs , in the updateSlider function, which is:

```
const prevEl = rootEl.value?.$el.parentElement?.querySelector('.v-tab--selected .v-tab__slider');
```

Dropping the `Vue` version to `3.3.8` like I suggested in this ticket:  https://github.com/vuetifyjs/vuetify/issues/18892 does not resolve this issue.

### Expected Behavior
The tab active slider/border element animates correctly

### Actual Behavior
The active slider/border just toggle between being displayed or not displayed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUr1qwzAYfJUPTQlEdksLBeMYOnbqkq3uoNhfW4MsCVm2U4LfvfpxVKeEQDNZd77TcYfejqTTVfqsVDL0SDKSG2wVZwaLUgDkA62Yrv3ZI8P2HQy0lTXybUksLAnsP2kludSWULppmf4uyWyxpk4xUQQrDIz3aGVSoJW82Cx4FZin/m+Rp1571WlGeXLuRvkv55fGmLpz4KJ7JjsLY2u3ATV4ML8JAx0bUcvx7xhRsdDQxkWed3e9fdZCEiOvuEN/1/0m97xB6H/hhtkd+cUo5yOcGAvydPFmLOwq3aigwoOS2kCNH6znBo7htpoZlsFqDdsCVjMHYOfLQPScbwIzrf1hcgHxSjJtyEPymDyR8L2/I+8/HXfgRQ==)

### Other comments
Could be related to this issue: https://github.com/vuetifyjs/vuetify/issues/18892

**Comment by KaelWD** [comment]
Wrapping VTab in another element is not supported.
