### ISSUE TITLE
[Bug Report][3.4.10] Textfiled border color change when switching to other textfield. 

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#19016]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.7
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Switch to textfield one by one.
while leaving the textfield you will notice that there is a change in the border color like purple. 

### Expected Behavior
border color should not be changed.

### Actual Behavior
border color changes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNkU9LxDAQxb/KOB6qoG1FQZDsghfx5En0YD3EdiqB/COZFmHZ7+5kKyiy14XNJXmPxy/DvLcN5tQ39zHW80R4h4rJRauZ1p0HUPOljnH33Ik+eNbGU/qxxHx5pi9+MGQHmHUy2vOqwzCxldjQIVj9QVasJ+1IZB9sSCJPx7GV0+FaNb+Io8W2bQEfAFvA+7Gq+b/v4ix1qOZPTSJzn0xkyMTT0pZxMSSGDSQaYQtjCg4qabgqcZABfGZw+RNWJXFWPZK1AV5DssNJdV4+WJACw+0FXtc39S0u91WL798Oa7ew)

https://github.com/vuetifyjs/vuetify/assets/92006556/4e44a42d-bf1d-49ab-a1a5-28eaa32c333c

**Comment by KaelWD** [comment]
It transitions from solid red to 38% black, there is dark red in there briefly but no purple.
