### ISSUE TITLE
[Bug Report][3.4.10] `VSliderThumb` leaks memory

### ISSUE THREAD

**Issue by peter-gy** [vuetifyjs/vuetify#19022]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.7
**Browsers:** Edge 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Force the mount and unmount of a component using `VSliderThumb`  internally, such as `VRangeSlider`. In the linked repro this is done via a `VSwitch`.

### Expected Behavior
The slider component can be garbage collected after getting detached from the DOM.

### Actual Behavior
The slider component keeps lingering in memory, it is immune to garbage collection.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqNU1Fr2zAQ/itCL2khtjYyGIS0dBt92B62sYa9zHtw7YutTpaEdE4yQv77zpLtOOkoDcFI3313990n6deBe1eIbQsoN3/TJ8+XXDbWOGQHVjjIEX7GGDuyjTMNm/XcWaYzDftALYz2yPoAuzlPvDpkmjGsoYElC2vGStjkrcJ1BGdKVjXO5l3sSN/jdab5PAj7YG1KdUnVCqGxisredrTVNsmtDcuwIQWYSw2uhwLodxKLmm2TxpSgbjLua7N7ULIEl3Gm8scArk1VKWADfrsSQ+a0lst1BYkPJKooN5flxCCG0s/VdEgUuxKTIWjrCyctBlLvZG/M6FOO+dX1sGPMAbZOn/aMnTQsGboWgond7xgXnZ9hsxJjN/IWPWncyIpO3GhyN1TMeGEaKxW4bxYlnWnGxxPLeK6U2X0J2KQR5dRQ/PkP/uT3HZbx7w48uC1kfIxh7irAGL5/+Ap7Wo9BOq1WEfuF4A/wRrWdxkj72OqSZE94Qe3ncJOlrtb+fo+g/TBUJ3S4bR2brtinF0Y/yV2ki95P+pOP8a0kTW4vnIyB8zLUJcqtEa1fClGUmtLobsqtSzWg0LYRd0QTrtUoG0hK09wt0nfpe1FKj1M4Bd8kj87syFsqMhm9f4evaNUzQ4e3b2KLHkvoefiux7PaIhymSxxounWd6a8b6SJtOtZF6NloE8uPcx4Syfuomv/+B7htlVk=)

### Other comments
The `useElevation(computed(() => !disabled.value ? elevation.value : undefined));` line in `VSliderThumb` seems to be the problem. The `computed` value is created inside a closure instead of having it extracted as a variable.

I could work around the leak via the following patch:

```
diff --git a/node_modules/vuetify/lib/components/VSlider/VSliderThumb.mjs b/node_modules/vuetify/lib/components/VSlider/VSliderThumb.mjs
index 1865905..4575e0e 100644
--- a/node_modules/vuetify/lib/components/VSlider/VSliderThumb.mjs
+++ b/node_modules/vuetify/lib/components/VSlider/VSliderThumb.mjs
@@ -113,11 +113,12 @@ export const VSliderThumb = genericComponent()({
       const newValue = parseKeydown(e, props.modelValue);
       newValue != null && emit('update:modelValue', newValue);
     }
+    const elevationProps = computed(() => !disabled.value ? elevation.value : undefined);
     useRender(() => {
       const positionPercentage = convertToUnit(indexFromEnd.value ? 100 - props.position : props.position, '%');
       const {
         elevationClasses
-      } = useElevation(computed(() => !disabled.value ? elevation.value : undefined));
+      } = useElevation(elevationProps);
       return _createVNode("div", {
         "class": ['v-slider-thumb', {
           'v-slider-thumb--focused': props.focused,
```

**Comment by boutils** [comment]
@johnleider @KaelWD Could you please have a look on this issue and review the PR? Thanks a ton.
