### ISSUE TITLE
[Bug Report][2.7.1] Inside a VSelect v-list-item--highlighted class is offset by the number of VListItem's I add into the #prepend-item and #append-item slots

### ISSUE THREAD

**Issue by truesteps** [vuetifyjs/vuetify#19026]
### Environment
**Vuetify Version:** 2.7.1
**Vue Version:** 2.7.16
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Whenever you include a VListItem in the #prepend-item slot or #append-item slot, the position at which the item gets highlighted is offset by the number of VListItems included. This is also true, whenever I put 2 VListItems into the #prepend-item slot. Due to the nature of the v-list-item--highlighted class, whenever this gets added it even scrolls items I did not click into the viewport.

### Expected Behavior
When I click on the item, the item I clicked get highlighted and scrolled into the viewport.

### Actual Behavior
The highlighted item in menu is offset by the number of VListItem elements inside the #prepend-item or #append-item slot

### Reproduction Link
[https://jsfiddle.net/nh8ky3eq/11/](https://jsfiddle.net/nh8ky3eq/11/)

**Comment by AbdulKadirKhann** [comment]
I found a fix through CSS. You can try it as well:
```
:deep(
    .theme--light.v-list-item.v-list-item--highlighted:not(.primary--text):not(
        .v-list-item--active
      )::before
  ) {
  opacity: 0;
}
```
