### ISSUE TITLE
[Bug Report][3.4.10] Autocomplete retains focus after router link

### ISSUE THREAD

**Issue by cmjdev** [vuetifyjs/vuetify#19035]
### Environment
**Vuetify Version:** 3.4.10
**Last working version:** 2.7.0
**Vue Version:** 3.3.11
**Browsers:** Edge 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to clear the autocomplete as soon as it is clicked (or menu changes)

### Expected Behavior
As soon as menu closes it should clear the model

### Actual Behavior
It does not clear the model until focus is lost.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUEtugzAQvcrIGxIpgaJ0hUjVqgfoAUIWyBkaq8a27DFdIO4eGweBshu/z/i9uYzMWV58GZMPHlnFasLeyJbwo1EA9XBsjZnH+cG1olYotE8oKTxproMLCRcY4NObW1hT9aj8uWFcYmt/1LcU/K9hq2w49vqGMijoLtTvlqpEyOIWxq1UsQQqXhNFJAWui02R8HTcCkPgkHzqI3qjLcEIFjuYoLO6hyzcIItygLDXEaSf4RxFu0sWA4FWmB0gzfSv1/luEbPr/sX9NCsvZaAi2XnFSWgF25vs9jCmVrMrH1rpMXijL+JTrJRKhPhsOrBTfsrLksXhPS/f2PUB+9eTlQ==)

**Comment by KaelWD** [comment]
You would have to reset v-model:search too
