### ISSUE TITLE
[Bug Report][3.4.10] Vuetify version 3.4.10 not work correctly with nuxt 3

### ISSUE THREAD

**Issue by AMRWERY** [vuetifyjs/vuetify#19030]
![Screenshot 2024-01-11 223541](https://github.com/vuetifyjs/vuetify/assets/92232676/81c95d71-2720-4250-9178-1f3e23bc969a)
![02](https://github.com/vuetifyjs/vuetify/assets/92232676/443d3d4d-ded2-4670-baf7-7ed3b435a4e7)
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.6
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
i noticed that last release of vuetify 3.4.10 not work correctly with nuxt 3.
i used nuxt 3 a lot with vuetify, but this is first time face this issue

### Expected Behavior
work as expected

### Actual Behavior
not work as expected

### Reproduction Link
[https://github.com/AMRWERY/vuetify-3.4.10-bug-report](https://github.com/AMRWERY/vuetify-3.4.10-bug-report)

### Other comments
i noticed that last release of vuetify 3.4.10 not work correctly with nuxt 3.
i used nuxt 3 a lot with vuetify, but this is first time face this issue

![03](https://github.com/vuetifyjs/vuetify/assets/92232676/f8130137-78be-4687-a584-6b1aee84f09e)
![04](https://github.com/vuetifyjs/vuetify/assets/92232676/d7d2bf07-7dd7-46ef-9cf5-3d431c3085eb)

**Comment by Josepdal** [comment]
Solved in Vue v3.4.11 https://github.com/vuejs/core/commit/08b60f5d0d5b57fcf3347ef66cbeab472c475a88
