### ISSUE TITLE
The events of v-menu do not trigger

### ISSUE THREAD

**Issue by telvin** [vuetifyjs/vuetify#1903]
### Steps to reproduce
Create a menu with a activator button

### Versions
 "vue": "^2.4.3",
 "vuetify": "^0.15.7",

### What is expected ?
The `activate` & `deactivate` events are similar to onOpened & onClosed events for the menu. They should trigger when the menu is opened (by activator) or closed (by an action or click outside of the menu's content) 

### What is actually happening ?
Both of events `activate` & `deactivate` are not triggering.
### Reproduction Link
Code Example
https://codepen.io/anon/pen/WZpeQw

**Comment by jacekkarczmarczyk** [comment]
`activate` and `deactivate` or not events, they are just VMenu methods. You can watch the model and perform some action when it changes
