### ISSUE TITLE
[Bug Report][3.4.10] VColorPicker: vue 3.4.11 is causing error: Maximum recursive updates exceeded in component

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#19041]
### Environment
**Vuetify Version:** 3.4.10
**Last working version:** 3.4.10
**Vue Version:** 3.4.11
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
This used to work with vue 3.4.10, something that was introduced is causing it to error the Vuetify component.

### Expected Behavior
No Errors

### Actual Behavior
Error is thrown:
```
Uncaught (in promise): Maximum recursive updates exceeded in component <VSliderThumb>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUEsOgjAQvcpkXLCRj9GVKSSeQ1wQLEkjpc204IJwd0uLUjfNvE/evOl9RkNtftM6m0aOV2SWS903llf1AMCmtNHajx60arCNGDhtlCdJvX9wc/UR8aUUpVq0L04wpVI9eV/W6OkaK5b/W+K8IO0LHd43BjUutTKhM8ujWxw0LQltwXA7hpOE1IoszEC8gwU6UhIS9w3Jagdwuca619WCEpJDVxROYXnIcQm4HPGcXbLTCbehwMcHK8JoMg==)

**Comment by volarname** [comment]
its ok with 3.4.14

**Comment by webdevnerdstuff** [comment]
Confirming that 3.4.14 does not have the issue.

https://play.vuetifyjs.com/#eNpVUEsOgjAQvcpkXLCRj9GVKSSeQ1wQLEkjpc204IJwd0uLUjfNvE/evOl9RkNtftM6m0aOV2SWS903llf1AMCmtNHajx60arCNGDhtlCdJvX9wc/UR8aUUpVq0L04wpVI9eV/W6OkaK5b/W+K8IO0LHd43BjUutTKhM8ujWxw0LQltwXA7hpOE1IoszEC8gwU6UhIS9w3Jagdwuca619WCEpJDVxROYXnIcQm4HPGcXbLTBbehwMcHK+ZoNQ==
