### ISSUE TITLE
[Bug Report][3.4.10] VDatePicker - min, max does not work if the initial display month is specified.

### ISSUE THREAD

**Issue by y-negishi** [vuetifyjs/vuetify#19058]
### Environment
**Vuetify Version:** 3.4.10
**Last working version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set min, max.
Set the month within the display range.

### Expected Behavior
Dates in the min to max range should be enabled and the month set should be initially displayed.

### Actual Behavior
A date that should be within the display range is invalid.
If you move the month and return to the first display month, the date is valid.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?ref=github#eNp9kU1rwzAMhv+K8CXptny0zRiUdDAYgx3GDj2NZQeTOp1Z4hhH6QKl/31ykhK3sF6MXunVIxl9Hlhj8uhJ63DfCrZiKYpKlxzFY6YA0n3Ate7DXuS1Qi6VMGOqT27JHWiZ/wgDq0qqdcbozRgJ3lnBu15Q7zdJqSRKXr5ZSfnoRI8u8TYzTE8jZyuSTW6kRmgEtsNystK1QTiAEQUcoTB1BR59yLN2AOI2CLTUMyFgDUr8gg19bxEvlkGcBPHcm505yUUsf+wJsX7dvG/QSLXzZ+R0vLz7h/oQLOMzKu9O1KHnCjVvjREKPwQ3LnkW7gS+tGVpC77DRm6oMtrt+Km0lUUxFhxX4I645PS3If/9VHCvNv7C9d5OY25gvqDN0mi4Et2HHe/YMkzCecLGIGZffyYcz0Y=)

### Other comments
Or are there any other props other than month that are initially displayed?

**Comment by FiXiLiX** [comment]
While running your code,
` const initialMonth = ref(targetMonth + diffYear * 12)`
return -7 as month value
![image](https://github.com/vuetifyjs/vuetify/assets/50845827/d8f6ffb4-50ec-4829-b269-e1cb5b291a70)
Setting month as a positive integer
`<v-date-picker :min="min" :max="max" :month="5" year="2023" />`
`<v-date-picker :min="min" :max="max" :month="7" year="2023" />`
Works as expected i.e. for 5th month days are selectable, for 7th they are disabled.
While there is no documentation for month prop given (https://vuetifyjs.com/en/api/v-date-picker/#props-month) I don't think -7 is valid value.
I don't think this is a bug.
