### ISSUE TITLE
[Bug Report][3.4.10] v-window-item doesn't scroll through card text

### ISSUE THREAD

**Issue by kfung21** [vuetifyjs/vuetify#19068]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Using the v-tabs with v-window, the card text won't scroll for long lists. When the tabs and windows are removed. The card text resumes scrolling as normal

### Expected Behavior
scroll through card text on each tab

### Actual Behavior
card text does not scroll

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1l82O0zAUhV/FZFOQaDOOOwygDBI7HgCJBWWRJm4bKX9y3AxoNO+O4zTltsnlDEKzauv71XG+3PjI3x+D1qTh56ZZdUcdfAxiq8umSKz+tKmEiLtl0jT+q/+R1pVN8kqb05AftPqnXe5yXWSiW5Z1pov7TVC2+00gQscR8iGvsvqBUAddFPW32hTZ12S7Cc6zDvMm25ZnxXbvllPUxpW2xVEv90b/uphinER0ias77Es/g0P8Zxz64t94fzHH+88pfxppL1edJia7nnS472Xu3E4WQ9HzBCItkrZ1lHeb6spq4275oPP9wbrhu9vuMPnv+d/+iUyKrtwMty5kHI4PdbYegboC9TWo34L6O1C/A/X3oP4B1OUNApBBiRRK5FAiiRJZlEijRB4lEimRyQiZjGAvIpMRMhkhkxEyGSGTETIZIZMRMqmQSYVMKvhaI5MKmVTIpEImFTKpkEmFTK5nTfa7Obd5jrXLfd0Nko39Khiu8H8IhjF15oPhfyNgLsOvLPkFcBlBCKadCMH0EyGYhiIE01GEYFqKEExPEYJpKkIwXUWNMW8oRbBVLjkogr1y6UERbJZLEIpgt1yKUATb5ZKEIs/oWWyXyxOKYLtcplAE2+VyhSLYLpct9E3Fdrl8ocgztgRsl0sZimC7XNJQBNvl0oYi2O584pyCgt2OXzKR/qDj4W6ylH5kOPzFITkUup9tavLGilbb43BXednUxopHYfROPImdqUuxcOfJRV8stHWpRc5u4r7nXi8Wb/qyu2hrhTsujsNDSHv4VY/E4XA9d6Xg6W2gVuuVXAenLzfBj986F4gh)

**Comment by KaelWD** [comment]
You're gonna have to elaborate on what you mean by that.

**Comment by kfung21** [comment]
Normally you would be able to scroll down a card and view all the items in the list. In this case "Hello 1-40".

**Comment by johnleider** [comment]
If you set a maximum height you have to tell it to overflow: https://play.vuetifyjs.com/#eNrtmcGO2jAQhl/FzYVWKmQds922ylbqrQ9QqYfSQwgGIhkSOSbbarXvXschdCDM/ltVveUEeD4c8zGZAfv7Y1TbPP5cVbPmoKOPUer0rjKZ058WeyHSZppVVXgaXuTl3mXFXtvjUBh0+qebrgttVqKZ7sqVNveLaFdvFpGIPUfIh2K/Kh8ItdXGlN9Ka1Zfs+UiOs3azZsta54Vy41fjimtDy3NQU83Vv86m6KfRDSZj3vsSzuDR8JjGofgc3y4mOfD45A/jtTnq84zu7qctPvc08K7HSyGoqcJRG6yuvZUcJvrvdNWlI22a+PnyQ7Ov1NsdbHZOg/d3TbbwUynucL3Mwj6cNWJEDKN+6/4ajwBcQXicxC/BfF3IH4H4u9B/AOIyxsEIIMSKZTIoUQSJbIokUaJPEokUiKTCTKZwFxEJhNkMkEmE2QyQSYTZDJBJhNkUiGTCplU8LZGJhUyqZBJhUwqZFIhkwqZnMO7eyyPY3kcy+NYHsfyOJbHsTyO5XEsj2N5fL48tjsD3F/vPna+R+AHySbBxSbDBf4Xmwz9Dsb1TYZ/3UC4th90YSksgOsRhGDSiRBMPhGCSShCMBlFCCalCMHkFCGYpCIEk1XUGHOHUgRb5ToHRbBXrntQBJvlOghFsFuui1AE2+U6CUVekLPYLtdPKILtcj2FItgu11cogu1yvYXeqdgu118o8oKSgO1yXYYi2C7XaSiC7XLdhiLYLvuDvG0UbDn+nx3pD9ofFAyW0o50BwlpTA4Y/Ms6t0XlRK3doftUxa4qrROPwuq1eBJrW+7ExJ9NTNqg0c53LXIOIO5b7vVk8qYN+4vWTvijh364a9IBftUiadxdz18penobqdl8JufR8clN9OM3kSbQkQ==

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
