### ISSUE TITLE
v-dialog persistent prop is not reactive

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1906]
### Steps to reproduce
Create and open v-dialog with persistent set to false.
Change persistent to true while dialog is open.
Click outside of dialog and notice that the dialog is not persistent.

See:
https://codepen.io/anon/pen/zEZqdj

### Versions
0.15.7

### What is expected ?
Changing persistent prop to true should make dialog persistent.

### What is actually happening ?
Dialog is not becoming persistent

### Reproduction Link
https://codepen.io/anon/pen/zEZqdj

**Comment by jacekkarczmarczyk** [comment]
`persistent` is reactive: https://codepen.io/anon/pen/ZXeOVd
But i'm not closing it as I'm not sure if closing both dialogs (in the original codepen) is intended

**Comment by Webifi** [comment]
Closing both in the original is not intended.  That's more of a side effect of clicking outside the dialog closing other non-persistent dialog below it.

Looks like in the original codepen, dialog2 is getting set false, and as a result setting the first dialog's persistence to false before the click has finished propagating up the tree? 

So my original assertion in this bug report seems to be wrong.
