### ISSUE TITLE
[Bug Report][3.4.10] Changing select-strategy in DataTable does not update the select all button

### ISSUE THREAD

**Issue by oowais** [vuetifyjs/vuetify#19069]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Chrome 120.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- Make sure that the initial value of select-strategy is 'single'
- Change the value using a button or some other means to 'page' or 'all'

### Expected Behavior
The select all button doesn't render on changing the select-strategy from 'single' to 'page'/'all'

### Actual Behavior
The select all button should render

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNlUFv0zAUx7/KUy4DaWnTrQiosooxIYQQaNKGJrHu4CaPxprrRI6TMlU9IySGBJwRJ458Nz7C7KRp0kR1o+6y5JA8v/f8fn7527mcW7HwusdR1EkTtAaWK3EaMSJxOOIAbmqPJYcXHqPe9dHIiqVQrsnN0V5M+YTh3sga5m9uNwvdkhWRSZajn+0yCGM6QT3K+CwjEggeI3GswiNpH6ig+RyKxMXC7aqIIji1fSKJLcmYoR4ASO1p6CPTtZChJ9EfWblnQFUL9KzZsxjVhp0SlqDycDLFwhEH4czO51jm54a9WkO5nDxnqFdS8ihGt1vpujJjT9BIZp3Bz1EoJPj4iSRMwjyvobMfPS4sAIEyEby0Fday5ACKT7VfcS6XPIDLq8pwtmA1Vo5AdUp96ZWrKf//uf0OSjTr0+qLhR6RNOQq6ILEgSotQ14PCpBOAqlCnE6v7huTWFdwOs7TuisNWZKVV07HqWUu1qyN2N/gJeHqNnC/8hLih8IAfbAZ+okZupbZEvoLvBYkwtgA/UYSdmNArleuMjdc68w7dvorXCgFiimypgAq4CdKI42vUQHvb+Q+NGHXnC2Zb+GUciRbhH0eEMoI9w3UDbYVtbnZNfm0xP4JJwEKQY0KOU/ENT4oifz9B+8In4QmWXOfmtTRa+y3FXPjZFlH3q3Tv+BMHayzsep2o5UV7A9nx6ZGb1ZH01Vr9G4HyA84ReIF99iGzvPNzM/MzLUd3FIbv+EtnVED8XucwUckWzZi80BufVYbNF3+NRf5S+5Uhttd/bytxb512Ol3en1r+eJYV3eVrW8T)

### Other comments
Also worth noting, If the initial value is not 'single', and then later changed to single programmatically, the select all button doesn't get removed, it stays, however it is unclickable.

**Comment by websitevirtuoso** [comment]
This has been fixed in this PR
https://github.com/vuetifyjs/vuetify/pull/18908

But still in review

**Comment by oowais** [comment]
> This has been fixed in this PR #18908
> 
> But still in review

This PR is merged but unfortunately doesn't fix the issue.
