### ISSUE TITLE
[Bug Report][3.4.10] VMenu - VOverlay refs not being forwarded

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#19062]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
* Open the sandbox
* Right click the example and view the console log
* VOverlay refs do not seem to be in the VMenu refs

Its possible this is intentional but based on the VMenu and VDialog source code it looks like the intent was to have the overlay refs as well such as `contentEl` and others:

```
// v-menu source
return forwardRefs({ id, ΨopenChildren: openChildren }, overlay)
```

### Expected Behavior
public VOverlay refs are exposed through VMenu ref: 
```
return {
      activatorEl,
      animateClick,
      contentEl,
      globalTop,
      localTop,
      updateLocation
    };
```

### Actual Behavior
They dont seem to be there

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkDFPwzAQhf/KkxlaJEhAdEJpEQMjqsTAQhkc9wKREtuyLwFU9b9zTtKqWazz3ad3797HQcVg8mfvs74j9agKptY3mmmzs0DR32rvh3L4GGdZ15bC1BqaLdkOgar1TqXyjaqdOs+FOCniShuue80uCHqAD85HHGfwIFiyhby13Qs3UMJsPVm8in6RD8Tlhnxm+qxjdNhvwPTLgkzfs29pJLen29J8dlzqjLfP5OUbTag9IxJ3YzR1611gHFIIOKIKrsVC4lwkHBDdyJiiwTpRy+txlOfQgfBDiJ33LtIe7FASdNlQKrUxFCN8Vza1EY22pBDhKrxvewqN/hu36SEZkX+aVGNnvqFj2s1k+aU5GXENZY37Wk52xEeRjwfJKep4ox6yVXa/UlNxpz7/Abuzr4g=)

**Comment by KaelWD** [comment]
Refs aren't set until after the component is rendered: https://play.vuetifyjs.com/#eNpVkEFrwzAMhf+K8KUprMnGeipp2Q47jsFgp2UHL1FGwLGNI4dByH+fbGdNepM+W9J773MSg6uLZ2vz0aM4iZKwt0oSXioNUI4HaW0sY1MbTbLT6BYU4TfpawvwZlHDK2pf6RXyr54ROGzPlQjlO7aVAFlTN0oyjqmVDjUxfPK2YQGn3jSoDqNUHvnZ6I+IK7E5lkRJ11yA8JegLJZ2c5pROLgqZrBKjhM3rgJJpstiEwa3Q+06SzAg+ZRJ11vjCKbgC2ZonelhxznuknfeOxAsbuEcfmX79NR6zdaNhn9b2R6mpChMGYW5Mj/ZMpvHEPJrWi+K1wDMQWISxXLEfCce82P+cBRLcS++/gCkXZk2
