### ISSUE TITLE
[Bug Report][3.4.11] Clicking on VAutocomplete label removes selected element

### ISSUE THREAD

**Issue by hd-luisaguilar** [vuetifyjs/vuetify#19071]
### Environment
**Vuetify Version:** 3.4.11
**Last working version:** 3.4.6
**Vue Version:** 3.4.15
**Browsers:** Edge 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
A combination of a VAutocomplete field that uses the `multiple` and  `closable-chips` props and is wrapped in a custom `<label>`, makes the label to remove a selected element when clicking on it

### Expected Behavior
`<label>`should not remove selected elements on click

### Actual Behavior
`<label>` acts like a clear button 

### Reproduction Link
https://play.vuetifyjs.com/#eNplUsFqwzAM/RXhSzpIk5UNBiUbjLHzBj3s0PbgJmprZsfGVkJH6b9PjZsm606WnqT39ISXRxF8mb86l7UNirkoCI3TkvBlVQMUWm5QdyHAWxPIGuigFEqtym8wGGtFO5UN2dLyMNIFBGinxlaon1ei3CsXVqIvzBXrBMa7d8BjW59oG+RG4/QGRenPcA+YRpNi2auo9ErWxOTBattz59FQ3jsq8pFTTkPplaOuCQ/OeoIKt5Kp4RgJKklyctdnAB6p8fWQX5afw3JAAJJPb3deGqPqXZL+rWj5wyi0qkILO2kw3HR8SWJObjG2Vf+qC43obmjXo7g7La+TLMijjAtA8i7pHA2NpxicGIiRQdrbiidHVnkBnJwJRwcAoL0KWec6C47/A05GiKorPHxs41QKs7ur4EU6vixf5Nfji1MqHrLH7EnEd3Yv1r/TpcpA

### Other comments
It looks like this is the change that broke it.
https://github.com/vuetifyjs/vuetify/pull/18571/files

**Comment by yuwu9145** [comment]
Why not use built-in label prop? [demo](https://play.vuetifyjs.com/#eNplkE1rwzAMhv+K8CUtpMnKBoOSDcbYeYMedmh7cBO1NbNjYyuho/S/T4n7kXYn630s6ZW0OIjgy/zNuaxtUMxEQWicloSvyxqgaCeyIVtaZkjYIYB2YmyF+mUpyp1yYSkinikuDUz790xjSgy1DXKtcXLDUPoORmkaTYqtotJy3du8N4GsiTLlElX+gMGzQyu9kjVxXrDaRprz9EU+WIVlKL1y1K+Fe2c9QYUbyYZwiI0qSXI0PisAj9T4+qpPy8xgcSUAyZe3Wy+NUfU2SW9/tPxlCq2q0MJWGgx3Gd+SuCenGNuqf79zjeju2q4GcX9oHieZk0cZB4DkQ1IXXROPMTgyOF0ZaWcrrhysygPgqGs4OAAA7VTI+q2z4PjuOBoQVVe4/9zEqhSm44vhyTq+bF/kl+OLYyoes6fsWcR3+iBWf5LmxAI=)

**Comment by hd-luisaguilar** [comment]
> Why not use built-in label prop? [demo](https://play.vuetifyjs.com/#eNplkE1rwzAMhv+K8CUtpMnKBoOSDcbYeYMedmh7cBO1NbNjYyuho/S/T4n7kXYn630s6ZW0OIjgy/zNuaxtUMxEQWicloSvyxqgaCeyIVtaZkjYIYB2YmyF+mUpyp1yYSkinikuDUz790xjSgy1DXKtcXLDUPoORmkaTYqtotJy3du8N4GsiTLlElX+gMGzQyu9kjVxXrDaRprz9EU+WIVlKL1y1K+Fe2c9QYUbyYZwiI0qSXI0PisAj9T4+qpPy8xgcSUAyZe3Wy+NUfU2SW9/tPxlCq2q0MJWGgx3Gd+SuCenGNuqf79zjeju2q4GcX9oHieZk0cZB4DkQ1IXXROPMTgyOF0ZaWcrrhysygPgqGs4OAAA7VTI+q2z4PjuOBoQVVe4/9zEqhSm44vhyTq+bF/kl+OLYyoes6fsWcR3+iBWf5LmxAI=)

We use <label> a lot in our app for customization and accessibility reasons. It used to work very well since v3.4.6. After that point  we started to notice this issue

**Comment by yuwu9145** [comment]
close chip is a button, if autocomplete holding the button is nested inside label tag, button is programmatically associated with the label too. To avoid this, use `for` and `id` attributes to associate input with label.

Same accessibility result but no issue with close button

[demo](https://play.vuetifyjs.com/#eNplUsFqwzAM/RXhS1pIk5UNBiUrjLHzBj3s0PTgJmprZsfBVkJH6b9PidM2606WnqT3noTXJ+Fdkb7WddI2KBYiIzS1loTLvALItNyihp11L7kg9JSLJbw1nqyBvhRDoVXxDQYhS3skzLUz2ZAtLHMhYQcBtDNjS9TMVBxU7XMR4IViSc9o/17Q0NKHqryKDzVtvdxqnI2aCo3SdWBITaNJsfagLJ2SFTGNt9oGmpSNZuloW0594VRN/QZ4rK0jKHEnmQpOgaiUJCfTSwbgkBpX3fLB9wLWNwQg+nR276QxqtpH8d+Klj+MQqtKtLCXBv1dx5ck5uQWY1v1r7rSiPUd7WYU9zdlO9GKHMpgAKJ3SV10azyH4MzAcD+kgy15crQqG8BJRzg6AAAdlE/6rRNf81/AyQhRVYnHj12YimE+vQoO0uFl+Sy9Hl+cY/GYPCXPIrzzB7H5BTGRz1w=)

**Comment by hd-luisaguilar** [comment]
> close chip is a button, if autocomplete holding the button is nested inside label tag, button is programmatically associated with the label too. To avoid this, explicitly use `for` and `id` attributes to associate input with label.
> 
> Same accessibility result but no issue with close button
> 
> [demo](https://play.vuetifyjs.com/#eNplUsFqwzAM/RXhS1pIk5UNBiUrjLHzBj3s0PTgJmprZsfBVkJH6b9PidM2606WnqT3noTXJ+Fdkb7WddI2KBYiIzS1loTLvALItNyihp11L7kg9JSLJbw1nqyBvhRDoVXxDQYhS3skzLUz2ZAtLHMhYQcBtDNjS9TMVBxU7XMR4IViSc9o/17Q0NKHqryKDzVtvdxqnI2aCo3SdWBITaNJsfagLJ2SFTGNt9oGmpSNZuloW0594VRN/QZ4rK0jKHEnmQpOgaiUJCfTSwbgkBpX3fLB9wLWNwQg+nR276QxqtpH8d+Klj+MQqtKtLCXBv1dx5ck5uQWY1v1r7rSiPUd7WYU9zdlO9GKHMpgAKJ3SV10azyH4MzAcD+kgy15crQqG8BJRzg6AAAdlE/6rRNf81/AyQhRVYnHj12YimE+vQoO0uFl+Sy9Hl+cY/GYPCXPIrzzB7H5BTGRz1w=)

Thanks! That was really helpful
