### ISSUE TITLE
[Bug Report][3.4.11] Click Events fire on mouse up when not over the element in Firefox

### ISSUE THREAD

**Issue by seriouslysean** [vuetifyjs/vuetify#19078]
### Environment
**Vuetify Version:** 3.4.11
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Everything is in the editor, but to lay it out plainly:
- Add an event listener to a VCard
- Hover over the VCard
- Click on it and hold the mouse button down
- Move your mouse off the VCard
- Let go of the mouse button
- The even will still fire as if you let the mouse go on top of the element

This only happens in Firefox as far as I can tell, and it also does not happen on standard click events applied to other elements (like a div).

As far as I can see, it looks like event handlers are proxied from the element to the document level and maybe some form of target caching is taking place between the mouse down and mouse up (and then firing against the cached ref), but I'm not entirely sure.
![image](https://github.com/vuetifyjs/vuetify/assets/414475/188c2da6-1c3b-4475-9c0e-534e5f6d2165)

### Expected Behavior
Click event does NOT fire when releasing the mouse button and not within the element (in Firefox).

### Actual Behavior
Click event DOES fire when releasing the mouse button and not within the element (in Firefox).

### Reproduction Link
[https://codepen.io/seriouslysean/pen/oNVWmVJ?editors=1111](https://codepen.io/seriouslysean/pen/oNVWmVJ?editors=1111)

**Comment by seriouslysean** [comment]
For what it's worth, I also put together a vanilla JS reproduction that works as expected in Firefox, so I think it's just something to do with the event proxying. https://codepen.io/seriouslysean/pen/VwRbBJK?editors=1111

**Comment by KaelWD** [comment]
Firefox bug caused by overflow hidden: https://codepen.io/kaelwd/pen/rNRmEbR?editors=1111

**Comment by seriouslysean** [comment]
@KaelWD I had the wrong element selected when I looked in to that, whoops. Appreciate you outlining that so quickly. Removing overflow hidden and setting it to initial on the card does fix the issue - thanks! This seems to be the bug on Firefox for anyone else looking, https://bugzilla.mozilla.org/show_bug.cgi?id=1259357.
