### ISSUE TITLE
[Bug Report][3.4.10] Heavier DOM with VTooltip as compared to VMenu

### ISSUE THREAD

**Issue by harmeet101** [vuetifyjs/vuetify#19074]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
.

### Expected Behavior
.

### Actual Behavior
.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNrNVEtP3DAQ/itT97Ct1Gx2y7aHNCAVLly48TgQDiZ2spYS27JnAyjKf2fyADYJSEhw4BDJ/mbmm8c38XXNvEvD/9Yuq51kEYtRlrbgKI8SDRBXAbe2O3aX1GjkSks3QAQKVYHHh0IeJkwoT7EPEeROiX+QcxvBwW97T0cCgidqoil2pfYRrDPXfgl75nsH4/pvy3inBG6JflXdjcKJYLs5uvBK53B5JvUuDuk+sj/VAVWQGUdZNCgN69WEhzw7gjEGYKzUgdHB1lTSTY2RyTIvkUj/JGxqLEzKURlN1lRqpOiZi3EqV63DrUE0JQ2CO5y6Tcrcb+k7T1FVHLu+arDOWA/NrLO+u2PUgPK+rfa0bQa20smE0VxulRaEduEEhPOM4d6izIyXJ9yJZxEtF4Lk6JWjUqCuQUPTEEnnOJ162I19rNl+uheQVmWU/jN359yYApX90PoMHK8J/5bSX13bQbuZZEOr71dtfovD6QvTIv0DNKkp9qlTFoF+tV2fU5XWOIQanMyggczRSBf0pi36FojXI5Q+h8PW48fiVBaFgSvjCvFt8bNN0FMSGWt+sYPlZrnesOGwYjePMlt7gw==)

### Other comments
On a screen that has a table, with each row having multiple items that require tooltips, it is noticed that `VTooltip` lead to a heavier DOM since all tooltips are attached to overlay-container in DOM and hidden. Whereas with `VMenu`, only one tooltip gets generated on demand leading to lighter DOM since overlay-container is not loaded with too many divs in advance.

Considering the facts above, what should be the ideal choice for tooltips? And it will be great if someone can share what was the reasoning to design tooltips in this manner?

**Comment by KaelWD** [comment]
Tooltip content has to be available to screenreaders.
