### ISSUE TITLE
[Bug Report][3.4.11] v-data-table-virtual always display "No data available" when search prop change.

### ISSUE THREAD

**Issue by regchiu** [vuetifyjs/vuetify#19073]
### Environment
**Vuetify Version:** 3.4.11
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Reference: [server-side-search](https://vuetifyjs.com/en/components/data-tables/server-side-tables/#server-side-search).

### Expected Behavior
Should be work as this: [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV+ty4zQUfhWRGYgDsXNr2l1PU1i6LJRdoDPLMMO0/aE4SitWkTyynBI6eXeOZMmyHHfTgf5orHPTd47ORbp56hUyG73J82Rbkl7aO1dkkzOsyMUtR+h8G6+wwrHCS0bigsgtkZqO0DbeiBVhKQX5Is6JjHN8Txa3PUO4JvIalre9SjgtCJbZA3Crj5r+QPCKyAIY9qvmVHYZ4fdK6ymhMLvStFDCmNSoQh4TeEX5PXDtl+NopXiLWamhcrypIX5X5uApSUWuqODartZsWDXxgIi4+EAECiZUqtZCKMvUbFl/69WqsTLhVORvFa8pYSsXwhoIeqArEq+IwpQVCDbJyINgEBWQ+GjihrRgkiQgmzFcaJQbHE9huSK8oGoHhExscpyp297F+ai5XRPWKMD1WZRNRn3qehvMhKSkDrn7a/oQckKHfqGcbsoNes6O2uXmiMrNElKuxQydD3kdkWgKvDAqsHAHCZ9BSYD+QU0AJxCDZZFJmitUEFXmRpFuciEVekKSrIfoESs4zz1aS7FBfai9vtYC1yD5FDhRgGFVoAW6qVA8OWQ6BVLUfyfFP4SjP8V9KVV/6LgunCmazF/X1DVWKTptCMklSExPakouhSKUp8iTqBSw7k+c7b39bQP5mTC2Q0uCeReK2dk8RDFuo3jdgcILWRTjYyjeU/Ued8ZhPnkVIpgeBOLUY6whnLUhnB6D8ANkJZVdEKan0xDC5PAsZocQvJCFcHYMwo/Q6YhcSuilnYcx9yafwXHik6bGMUs80WXF0WhcZQRlAGSDCsxXjzR76IzMzMfZIPI7WUANAZ+kiY/WS9P0g2CM5iLvjMvr1vmME09waeqz6Pk0nR5DcVnmGf5EOkGMW5UyS7zrLlFfFoxXx2D8JDjZQXtcdgE5GbcKZnYYjVcdQE4T74AFcjI/huSt4GVn2Z7MW2cy9dYtiPmkKxoHuTptncqdb7Pv4CzeXF9Bl7W4cLHjGVoT3ZujJ6SvNENzZ3A3miEqoIl/v4PfaiLvB94nCb1ecsTJI7qGtk4LEklSCLYlaHHhxZAeCr/TDRGliqJBi+ewFQrDtFigSINAMZoM0NcBlEMVwlegUCl+c0TWcEHaTZqkYDQj0SBZU6aIjDT/ABnEdI2iyvNEnyD66iv0hRY1q0SJD+KRyEsMng8SyjNWgv2mQigyaATP/dkgrjErAthwfOFyNEIEQHMVr2hhZjHXYx0oBA6JY/lXMcph1sLVtIC+CPylEAzmVFxt8axjLgmNcyYQnnSxQL+aK0lb+P/5YgWVLAO5/aC5MhBN9iXVvfhgR5s5IPOe7HQqGOmb8V3yieyeE/1Nwo0sEBaa0gqPTpdEi0QRHqLlYdZ6o/gPfb8Gi/jGQjEldyi4dILLZwVtYBo4FwvUh6TK+uhbZyB2W6buI7asVtCDcAZHUAGCUqMcbnC6jKzHpipMSQ11fQUWbHFDozDCqdcfIvNgSa2V6riC/fdDNB+Pa4JjVS3KQGvUqa1iQAX5HM2NbMW2zybLad8VFVXMdNmqyFE0GY/vofvILRTEwLddzOi9bpXGT0/WUdeFlVYZXNMhmUBYl/NBe6+3vLR10R9acVcoQHDbQTz7HarvMCDV8KwmtP/jSpd6JgRqZkocV4ROrUdHoGrHyXHlKxgxKPrSa+qZ06121zi1xpPVnVyTbd+slqWbQoPpX8KWXyVRxTQ9uSL3+w163b86eHaQBZx1yTP9DjZQqs0+Ow4bY9CCT8wjG6z6nmanbWLG64umawqhri4KZnYYk8PGJcF92c32ACNRD4RHriRtHWp4zX7ViH+N08jXhVMH2fuhSY7fdrLR4atKNhVs3niRhj5EwZy3s8Npf1QSjEVvoXMkXDzCXDQmzP/KhnP0v9o5H1XP0YveftibJSfJWa/6nUx6d/8C/MpHsg==).

### Actual Behavior
 The table always display "No data available".

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFWH1z2zQY/yoiHIsDsfPWdFuuKYyOQdmA3o3jjuv6h+IoiZgi+WQ5JfTy3XkkS5bluKTsuKN/tPbzpt/zLvf2oZPLdPAqy5JdQTqzzoUi24xhRS4/cIQudvESKxwrvGAk3lGpCsw0A6FZTrBMN/MPnfLhQ8fSNwQvicyBYZ8qDgXbmp4TuSPyWr9VPCbwkvI1cO2T42ileIdZQYDH8ZY4xjdFBtjITGSKCq7tas2aVeMB+OA8Qp8rkVmicU2K++rVEFLBagRDUuRPFa8oYcs6A6FdvBVLwhqY3M+GLkm8JApTloccQJKSjWAQGNB9b0KHtIkkSZpWUoZz7dcWx+Mmb0l4TtUeuKnYZjhVocDlxaCOve4mMEI/P9XxFDMhKaly+G+d/4lyui226DE7ap+ZnBfbBZH/S2z0uy+Si0HYG8A8bg5gBXLwmqeSZgrlRBVl+dFtJqRCD0iSVR/dYwUlcEArKbaoC13Y1VrgIRS1Al9yaBeVozm6LWE8OHS6amao+0aKvwhHv4t1IVW377guqjM0mr6sqCusZui8JiQXIDE+qyiZFIpQPkOeRKWA9+7I2T7Yv00gPxLG9mhBMG9DMXk+DVEMmyhetqDwQhbF8BSKt1S9xa1xmI5ehAjGR4E49xgrCM+bEM5PQfgOipPKNgjj83EIYXSci8kxBC9kITw/BeF7mKBELiRM4NZkTL3JR3Cc+aKpcEwST3RVcTIa1ylBKQDZohzz5T1NN62Rmfg4G0T+JAuoJuCLNPHRemqZvhOM0UxkrXF52cjPMPEEV6a+ih4v0/EpFFdFluKPpBXEsNEpk8S77gr1acF4cQrGD4KTPUzJRRuQs2GjYSbH0XjRAuQ88Q5YIGfTU0heC160tu3ZtJGTsbduQUxHbdE4qtVxIyt3fsy+gVy8urmGKWtx4XzPU7QiMJujB5ThNembq0h+Q+SNecthhn+7h7/lDj/0vEsSRr3kiJN7dANTneYkkiQXbEfQ/NKLIb0TfqVbIgoVRb0Gz0HLFYZlMUeRBoFiNOqhLwMoxyqEL0GhVPzqhKzhgrRbNEnOaEqiXrKiTBEZaf4RMgjpCkUhRXujI5HohKJnz5rcz7Qlw0yUeCfuibzCEJheQnnKCjg+qumHIr3QVi3S7sdGfIVZHvgIqQ5fBwNEwEOu4iXNzeLm+iYAFAIZ5Vj+kQ8y2MtExjnMUOAvhGCw0+LyiCdHwRVwWyRMUL3E5Rz9bC45LgKO8186bgWVLAK5Q3CE9qes64QRvlaboxNtTYLMW7LXRWakb4d3yUeyf0z0Fwk3vkBYaEojlroQEy0SRbiPFsf94I3i3/QHAVjEtxaK6eVjwYUTXDwqaANTwzmfoy7UY9pFXzsDsTty5h5iy2oEPQhnkIISEDQx5XA11A1qPTb9Zpq1rzs3sGDHBowgIzzz+n2khMJsZq2U6QrOP/TRdDisCI5Vzj4DrTYB7HwAVFD80dTIlmz7FWc5zUuoooqZ8V2ODxSNhsM19IDcQff0/DzHjK71DDZ+erKOuu7CWVnBFR2KCYT1JDjaG9WRV7ZLun0r7toGCO44iGe3RfUNBqQantWEvXJa6Uovm0DNrJ/TirAD9E4KVO2eOq18DbsLRV94Tb3M2tXualmrfWO7zNXZ9iPbsvRQqDFNYdVVyyIqmWa6l+Rut0avplkLz67IgLMqeKo/3A0Uc9g/7tnafrXYE/NPATDqR5rd4old29WdQNup7gJ14/UyhF1evRq8M8hCeTkxG8kc169dTNyTBeJSd+glakN45HrWNqp2oD7QagmqPDHyVWdVWfCeapLjN8NQWwFlq5sWN1+XkXagj4Irhl01Tvu9kmAseg2jJeHivtq5OoGw/xIm1m47GZXyBPO7PMJF41OO0XYuBuV3Mnwhdw79ziQ5S0bTjn0Yde7+BsSOXg4=)

**Comment by websitevirtuoso** [comment]
You made something wrong here working example
https://play.vuetifyjs.com/#eNrFWH1z2zQY/yoiHIsDsfPWtJuvKYyOQdmA3o3jjuv6h+IorZgj+WQ5JfTy3Xn0ZlmOS8aOO/pP7OdNv+dd7s1jrxTZ6GVRJNuK9NLeuSSbIseSXLxnCJ1v4xWWOJZ4mZO4JGJLhKIjtI03fEXylIJ8GRdExAW+I4v3PU24JuIaXt/3jHBaEiyye+Cah5p+T/CKiBIY9qnmGLs5YXdS6UkucX6laKGENqlQhbyc4xVld8C1T46jlOItzisFleFNDfGbqgBPScoLSTlTdpVmw6qOB0TExQd9LnlhiTpQgj/Ur5qQ8bxB0CRJ/pTxmpJ81WTU0Wxhcn/3dEXiFZGY5mXIASQZuec5hA503+ngImUiSZK2lSzHpfJrg+Npm7cirKRyB9yMbwqcyVDg4nzUxN50Exihn5/qeIZzLiipc/hvnf+JMrqpNugpO3JX6JxXmyXU8P8RG/Xui+R8FHYaMA9aDTiBGLyWmaCFRCWRlak+uim4kOgRCbIeogcsoQL2aC34BvWhpftKCxyEmpbgSgmGZYkW6MageHTgVNGkqP9a8L8IQ7/zu0rI/tBxXVBTNJm/qKlrLFN02hASS5CYntSUQnBJKEuRJ1HB4b0/cbb39rcN5EeS5zu0JJh1oZidzUMU4zaKFx0ovJBFMT6G4g2Vb3BnHOaT5yGC6UEgTj3GGsJZG8LpMQjfQW1S0QVhejoNIUwOczE7hOCFLISzYxC+hwFKxFLAiO5MxtybfALHiS+aGscs8URXFUejcZURlAGQDSoxWz3Q7L4zMjMfZ43In2QBNQR8kSY+Wh9bpm95ntOCF51xedHKzzjxBFemvoqeLtPpMRSXVZHhD6QTxLjVKbPEu+4K9eOC8fwYjB84IzsYkssuICfjVsPMDqPxvAPIaeIdsEBO5seQvOKs6mzbk3krJ1Nv3YKYT7qicVCr01ZWbv2YfQ25eHl9BVPW4sLljmVoTWA2R49IXZSG+ibi7klDVMIM/3YHv2aF7wfeJQGjXjDEyAO6hqlOSxIJUvJ8S9DiwoshtRN+pRvCKxlFgxbPQSslhmWxQJECgWI0GaAvAyiHKoStQMEofnVEVnNB2i2apMxpRqJBsqa5JCJS/ANkENI1ikKK8kZFIlEJRc+etbmfKUuamUj+lj8QcYkhMIOEsiyv4PiooR+KDEJbjUi7PxvxNc7LwEdIdfg6GiECHjIZr2ip9zZTFwGgEMgow+KPclTAXobbcQkzFPhLznPYabE54qOj4Aq4KxI6qF7iYoF+1nccFwHH+S8dt4JSVIHcPjhC+WPqOjH3+IMTbU2CzBuyU0WmpW/Gt8kHsntK9BcBF75AmCtKK5aqEBMlEkV4iJaH/eCN4t/U9wBYxDcWiu7lQ8GlE1w+KWgD08C5WKA+1GPWR187A7E7MnUPsWW1gh6EM0iBAQRNTBlcDVWDWo91v+lmHarODSzYsQEjSAunXn+I9AdWaq2YdAXn74doPh7XBMcys09Da0wAOx8AFRR/NNeyhm0/8yynfQmVVOZ6fJvxgaLJeHwHPSC20D0DP89xTu/UDNZ+erKKuurC1FRwTYdiAmE1CQ72Rn3kpe2S/tCKu7YBgjsO4tnvUH2NAamCZzVhrxxXulTLJlDT6+e4IuwAtZMCVbunjitfwe5C0RdeUy2zbrXbRtYan9guc022/ca2LDUUGkz/5W75pogMU093Q+73G/R6mnXw7IoMOOuKZeq7XUPRh/3jnm3sV4s90f8TAKN+pNktnti1Xd8JlJ36LtA03ixD2OX1q8abQhbM5URvJH3csHExcU8WiEvdfpDIe8Ii17O2UZUDzYHWSFDtiZavO6vOgvdUkRy/HYbGCjCtrltcf11GyoEhCq4YdtU47XdSgLHoFYyWhPEHu3ONIWPDufupds5H5kMYPoF7+2FvlpwkZz3zO5n0bv8GVfptiw==


You can't create issue when it works in documentation and examples.

**Comment by regchiu** [comment]
@websitevirtuoso But what you provided me was "v-data-table-server" as an example, if `v-data-table-virtual` can not support search props, I think it needs to be noted in the document.
