### ISSUE TITLE
[Bug Report][3.4.10] VTabs odd behavior closing last tab

### ISSUE THREAD

**Issue by dajester2013** [vuetifyjs/vuetify#19077]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.3.11
**Browsers:** Chrome 120.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Closing the last tab causes the 'openTab' model to become null, causing no tabs to be activate.

### Expected Behavior
"openTab" updated to "tab2"

### Actual Behavior
"openTab" is null

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1kk1vgzAMhv+KlUs7qcDYx4WxajvuvlvpIYXQRYMkSlLWCfHfZxJgpR8HUGw/8WvF76YlRufRu1Jhc2AkIalltaqoZetMAKRNQJVyRwwK3qzbFqRi4pPuoOvSqE8N1SaoKRdD5GJLdwYwLQtWvWZkuJeRiRkphEqpEVlisMLvQxTseAdcjGImI5A0tDowpBAILbcVm7UCaNup0nWnBVTZWXGaAZTkpe/lxGAN9xmZIzyXApG64EFeSYNy8/pbXvH8GwlXxSnd+DDNf84b+1v188+zADupC6YTEFKwl8viMTBftJA/N4Ca6j0XCdyrIwTxM/77U3+4QBUtCi72jj0rzqeKTlcUuR39L9bHZtw7htPi+8AbJo1OjIShyTVXFgyzB+8nXiupLbSgWQkdlFrWsEAPLnocAJ/e2Mlqrz21XKBsvLi7ApiB2PiZWnAmSMDfgG51Jf9wI/845rczpXHHqFQeRG65FOD3zdGprW80jhM6q4ZGoUHYkh9XEGMzAHRlGvmnwEcg3Yo8hk9h/EyGQ0y2f+jlCmA=)

### Other comments
Closing 'tab2' first works correctly - 'openTab'  is  updated to 'tab3', activating that tab.  The problem is when you try to close the last tab.

**Comment by KaelWD** [comment]
You need `@click.stop` on the close button.
