### ISSUE TITLE
[Feature Request] V-Timeline-Item property for left and right equals to v2

### ISSUE THREAD

**Issue by mthoer** [vuetifyjs/vuetify#19085]
### Problem to solve
Allow to apply specific styling depending on which side the opposite is located along the timeline

### Proposed solution
Provide a boolean left or right which indicates on which side the slot is going to be rendered.

**Comment by KaelWD** [comment]
Do you have an example? v2 didn't provide anything to the slots.

**Comment by mthoer** [comment]
Yeah sure. In the the documentation of the v2 https://v2.vuetifyjs.com/en/api/v-timeline-item there are properties for "left" and "right" to handle manuel the orientation of the time-line-item. This was awesome a blocks me now to upgrade to v3 :/

**Comment by mthoer** [comment]
Do you need more Information?

**Comment by mthoer** [comment]
@KaelWD hey do you need more informationen?
