### ISSUE TITLE
[Bug Report][3.5.1] VDatePicker unable to select dates if current day of month is the 31st

### ISSUE THREAD

**Issue by louisbourque** [vuetifyjs/vuetify#19087]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Firefox 121.0
**OS:** Linux x86_64

### Steps to reproduce
1. Set your computer date to the 31st of the month. For example, January 31.
2. Open the VDatePicker and select February. 

### Expected Behavior
The dates should be correctly displayed and when selected, the correct date should be selected.

### Actual Behavior
The dates presented go up to 31 even though there's not 31 dates in Feb. Select a date, observe the date is selected in March, even though February is selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAFqFq3IDM5Gyhso4/Kh+oEiqJqBYlATLbRR7LRpji5KLOgRKE4taS0AGgYhAuUUKrVUTLWM9EzNFUCMUz1DJViAbw5PGU=)

### Other comments
This appears to be related to https://github.com/vuetifyjs/vuetify/issues/18794

Video demonstrating the behaviour:
https://github.com/vuetifyjs/vuetify/assets/1115170/93bdef86-caf2-4a9e-82a2-d0f96d2f86ed

**Comment by SergienkoD** [comment]
![BUG-VDatePicker3 5 1](https://github.com/vuetifyjs/vuetify/assets/113579300/00d3f22d-9121-470f-b53d-f22a56721235)
More errors found:
VDatePicker the component does not allow you to select a date in February
