### ISSUE TITLE
[Bug Report][3.5.0] Remove old unused range prop from VDatePicker

### ISSUE THREAD

**Issue by herrrta** [vuetifyjs/vuetify#19081]
### Problem to solve
Will prevent confusion for users when reading documentation or previous range prop usages

### Proposed solution
Remove unused range prop and update documentation for multiple. Currently, doc says multiple is type strictly boolean which is untrue.

view commit
https://github.com/vuetifyjs/vuetify/commit/07781b385c0712baa8ec1974b11bd380d3548860

**Comment by herrrta** [comment]
Looks like tests need updating too
https://github.com/vuetifyjs/vuetify/blob/132dce26e2a16d249470276b77576d9d4fdf6ba8/packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts#L675C1-L675C54

**Comment by johnleider** [comment]
> Looks like tests need updating too [`132dce2`/packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts#L675C1-L675C54](https://github.com/vuetifyjs/vuetify/blob/132dce26e2a16d249470276b77576d9d4fdf6ba8/packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts#L675C1-L675C54)

Old tests

**Comment by johnleider** [comment]
closed by 3fad1e311
