### ISSUE TITLE
[Bug Report][3.5.1] Nested V-menus not keyboard accessible

### ISSUE THREAD

**Issue by kmmerc18** [vuetifyjs/vuetify#19093]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.7
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use keyboard controls to put focus on the initial menu activator button. Use the up and down arrow keys to navigate the options in the menu 

### Expected Behavior
Focus should move to each and every item in the v-menu, and the nested v-menu should not open unless the user presses 'enter' on it

### Actual Behavior
The nested v-menu opens as arrow keys are pressed, preventing access to all menu items after the nested v-menu button in the menu list

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVVE2LwjAQ/StDLirYyn6xUFSQPS/sXT3ENkLW2IYkLUrpf99JWtumFrzsHvbUzLx5b76SbkuiVbzYSBkWOSMRWRp2loIatt6lAMuEFxALqvVqR5LgKNgFvnNt+PEaaEljFlCV5WmyIy4cCUVwZmneWGjf5KAItMhMRGPDC2oyhYIlSJVJDVVLbyQOJoU4Ey5IKn6m6rojqHDgaeJcyEIObG5iYLVhuXDULvnCa6YRF1wbP531BBxjMcXRJZ1aaw6Yjl1m+AFrY0qITuyKuAOsWVCRs87R0/WVA8ONYOuydEqhs6CqbMXDmF5pfRT9j2fk5f+iiqUG2on3BdpNdbDVcYyBzNjQ7hscYvBwlvcMf7gj+GDaw4i7An9hB+ObGMP83aPTewi1q387/9XVG23Va3K5wH8FnrxHh6aOFZc1g11kpgwk7EhzYaCsVRJqaATTGazWMG18UHcdwbYrqQRXZASTD8HjE3yyCVTzv8ThuR+xb07VzB0q22rbHKnm5CV8Dd+J/b6FT2T/A5L1ljA=)

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNrVVMGOgjAQ/ZVJL2oikqyeCJqYPW+yd/FQoSRdKzRtIRrCv+9QESiy8bJ72JOdefPezJtWDhXRKvb3Uq7KgpGAhIZdpKCG7aIMIEx4CbGgWm8jknipYFf4KrTh6c3TksbMoyovsiQithwJpXdhWdFGGD/koPS0yE1AY8NLanKFghVIlUsNdUdvJU4mgzgXtkgqfqHqFhFUOPEssSlkIQf2DzFotCH0LbVv7jtmWnHBtXHbNRmPYy22SG3TeRMtAdux6wJ/oImxJQRndkPcAk1YUlGwPjHQdZU9w41gu6qySisbQV03E49rBqMNUcy/3pHT/5MqlhnoNj4U6G6qhxsdy0Bfujg51/jT8p6NjjF4udNnhrvkCXy09XHF04C/cBfTNzKFuW8Ak6NNjl/pv3qCk1Ydk6GP3ww8OX8+DHWsuLwz2FXmykDCUloIA9VdJaGGBjBfwHYH8zYHd9cBHPqRKrBDBjB7Fzw+wwebQb38SxzehhXH9lQv7KFurHbmSL0k69Vmtd6QZVYIcfwGAzuaAQ==
