### ISSUE TITLE
[Bug Report][3.3.0] v-combobox no input after backspace

### ISSUE THREAD

**Issue by KR34T1V** [vuetifyjs/vuetify#19100]
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.2
**Browsers:** Chrome 120.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Click on a combobox input, type a new entry into the combobox and press enter to select it as an option. Now press backspace to delete the chip.

### Expected Behavior
Chip gets deleted and it is possible to input text.

### Actual Behavior
Chip gets deleted and it is no longer possible to input text into the combobox. Unless the focus  is lost and recovered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFUk1PAjEQ/SuTXlYTWILKhSwkJl68mZh4YTmUMotN+pW2u0gI/91pWV3QkycPTdt5b17e63R1ZMGLyaNzZdcim7MqonaKR1zWBqDqxsKayKVBD41q5TaXM+Dtvr/0PAW0wqJm07uafUM9qDd2Yz+GIkA31naLivgBFYpYs0t0LslIEsv7Nab4Jve95j7g0PDOeiICF1F2Mh7AehAeKQahBvdgDV5r6FZF6RQOtWU1GYwOyXJR/XPSZ2gDgniX7gfhdwzoaX/KlW5f8zwj/dCpUk0uvkQVhJcuQsDYukyX2lkf4QgeGzhB462Ggv5SUZsEk1JI9DypRSLdrIq3FqNsDsUIihdvd55rLc2uWN9e9uTnoJbVFYdanjDInUkn0um3LLdOZs8GyRo7jdh9+VBOZywdZuWUrT8BLtDh/g==)

**Comment by yuwu9145** [comment]
@johnleider @KaelWD Is this behaviour intentional? It's consistent with v2

**Comment by johnleider** [comment]
The behavior is intentional.
