### ISSUE TITLE
Refactor setSelectionRange?

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#1910]
This line appears more than once.

https://github.com/vuetifyjs/vuetify/blob/f7e3c6a3d2e9d6975d600f6a246e79a4a9e4c015/src/mixins/maskable.js#L73

**Comment by KaelWD** [comment]
We can do a refactoring pass once all the functionality is down. That line doesn't really stand out to me as being particularly WET. 

This question is also more suited for discord, github issues are only for bugs and feature requests.

**Comment by azaars** [comment]
@KaelWD I was in code view page when I created this issue. Honestly, I had no idea it's going to end up in the global issue page. That's why I immediately changed the title to be more descriptive. Blame my ignorance ;-)

@jacekkarczmarczyk #1912 is more than what I expected and it's brilliant.

**Comment by azaars** [comment]
#1945
