### ISSUE TITLE
[Bug Report][3.5.1] v-stepper starts at 0 when using v-stepper-header

### ISSUE THREAD

**Issue by lenn1** [vuetifyjs/vuetify#19107]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
step is a number with value 1.   
the content shows the second values content and the stepper header is at the second item. 

### Expected Behavior
The v-model (step) starts at 1
The first item is highlighted

### Actual Behavior
The v-model (step) starts at 1
the second item is highlighted

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUl1rwzAM/CtCL91gSUjLYAy3sN+x7MEkKjMksbGd9KH0v8+Ks9b9gvbJ8unudCB979HZuvgyJh8Hwk8UnjrTSk+bqgcQYyaNmcrpU+veS9WTnaEJdJ6MIQtj1umG2nWFjFR45KSs7Jdkk+gvuiqMB698S7MNlBXCKNuBAa6Lx6XLRMp1KhXFjUg3A+9U3+jdvamxG4cnMTcQw5/NSbjP2IXos93yAbtrxmlXp9b/SgNyvlNG4spFkZyCcLVVxoMjP8R7UJ3R1sMeLG3hAFurO1iEG1pwM3i6QObMaya8lK9sGE2CHA9vuMpX+Qfy+56X+PMH68nMzA==)

### Other comments
When i dont use v-stepper-header the first item is at "1".  Why is there a difference?

**Comment by lenn1** [comment]
a more clear example is here: 

[playground](https://play.vuetifyjs.com/#eNqVUsuOwjAM/BXLl+xKtN1SrbRCAWm/g3KIihGR+oiStBfEvxO3FAJc4BRnxjN27GxP6GyV/RuTDj3hCqWnxtTK06ZsAeSQKGPGcLxUXeuVbsleoRF0nowhOyMAQ9J0e6rXJTJV4p1Z6WDvArEVTEEuFlOwnINC7O6Cjcxu9qHia82XUre+4qzkSGof9fzEck/gta/pagN5iTCoumfgJ8TZ+9JlJGWbD6RFJGWbWBoN4vk1jzOakcdNMTItUmbRgqWrrDYeHPl+2rJuTGc9nMDSAc5wsF0DIvwMwWTwdCGZe11zwlf+zYaTSZDjeYFFWqR/yOdvmuPuArRAud0=)

You can see that the v-model is the same ref and the upper one uses 1 at the first entry and the bottom one uses 1 for the second entry

**Comment by johnleider** [comment]
The issue is that the model being passed is an integer and the values assigned are strings.

**Comment by johnleider** [comment]
The P.R. addresses the issue of values not being properly inferred when not provided. The other examples in here are implementation issues.
