### ISSUE TITLE
[Bug Report][2.7.1] Events on calendar are overlap

### ISSUE THREAD

**Issue by NguyenNamUET** [vuetifyjs/vuetify#19117]
### Environment
**Vuetify Version:** 2.7.1
**Vue Version:** 2.7.13
**Browsers:** Edge 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create 3 schedules which 1 schedule end at 24:00 (Event 1) and 1 schedule start at 00:00 (Event 3)
Then create a schedule at date of the latter (Event 2)

### Expected Behavior
Event 2 is not overlap with Event 3

### Actual Behavior
Event 2 is overlap with Event 3

### Reproduction Link
[https://codepen.io/Jack-Knight-the-vuer/pen/rNRppqK](https://codepen.io/Jack-Knight-the-vuer/pen/rNRppqK)
![image](https://github.com/vuetifyjs/vuetify/assets/52781343/617805c8-467c-4d95-8938-a67037a2d95a)

**Comment by KaelWD** [comment]
They do overlap though, I don't see what the problem is here.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
