### ISSUE TITLE
[Bug Report][3.5.1] VListItem does not hide slots in minimized VNavigationDrawer

### ISSUE THREAD

**Issue by slonopot** [vuetifyjs/vuetify#19111]
### Environment
**Vuetify Version:** 3.5.1
**Last working version:** 3.4.10
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create an [expand-on-hover navigation drawer](https://vuetifyjs.com/en/components/navigation-drawers/#expand-on-hover).
Add slots to the first list's item.

### Expected Behavior
When minimized, the prepend-icon should be visible with the default line height

### Actual Behavior
When minimized, the prepend-icon is visible with margins

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U01v2zAM/SucLtmAKUaw9RK4BXbbbaehh2UH1WJcAfoCJbvpiv73UXYdO0nTi2E+vUeRfOKfF5GoqX7EuO47FFtRZ3TRqox3Ow9Q91LFOPwOgVe9aVU2wUtN6gkJ8BCV15KBx9BzvCVl7O1OZOpwJ6CXLmgswMj/FdHvxFvCIaU1KcNDK5tgAzEvknGKnlmr0SeTnxlrgouqyQvhUSoNFwzJGgeRkLNraZrgWeS0kY0NictYyFg4dcjFJRvyNpts8Q7uHxkrLdTVyQyu6lL3MEqXLOZp00NjVUqla7m3eIDykRSeQFnTetmgz0hndV1oHckNc34nJK8c1hUfXir6oV9I5h+y5iCTU9by9BZTsKENXZleXY3s84ovMr87gqI+jny28A1lYOEqJzQaabhx+j8hDLa/4zDwE4PpLSTkYvXwGq44vyz6uv9LVg58Vp1hxUaGpydwdqpaPlOnIB5KuUdgaPTD4UzhxQrN2+WUma3hmPvIDDFFJV20MzDnO4pKMC7riXscpoZMzJAwd+MuGxcDZXgBwj28wp6CgxXv/2q0iK9hc1xq4bYwPq9+orUB7gNZ/Wn1pVB6RTBvNPOGfeebx7v4FvH6VXxbf19vbkT5uVlvxN//VsBfOA==)

**Comment by KaelWD** [comment]
Your custom styles are preventing `text-overflow: ellipsis` from working, you'll have to account for that yourself.
