### ISSUE TITLE
disabled button inside v-dialog still can trigger the dialog open

### ISSUE THREAD

**Issue by guanxudong** [vuetifyjs/vuetify#1911]
### Steps to reproduce
add disabled attribute to v-btn
### Versions

0.15.7
### What is expected ?

the button should not be triggered
### What is actually happening ?

the button still can be triggered, and the dialog open
### Reproduction Link

https://codepen.io/guanxudong/pen/qProEz?editors=1010

**Comment by jacekkarczmarczyk** [comment]
Menu is triggered by clicking the activator slot container, doesn't matter if the activator contents are disabled or not. If you want menu to be disabled use `disabled` prop for `<v-menu>`

**Comment by guanxudong** [comment]
@jacekkarczmarczyk don't you feel strange that the button is disabled, but the dialog can be opened? although it can be disabled at `<v-dialog>` or others

**Comment by MoonWatcha** [comment]
I'm having the same issue. The button is conditionally disabled but it can still trigger the dialog.
