### ISSUE TITLE
[Bug Report][3.5.1] DatePicker any day in February is returned as March

### ISSUE THREAD

**Issue by VictorO15** [vuetifyjs/vuetify#19129]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.7
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Select any day from February from any year an is returned as March

### Expected Behavior
Return a February date

### Actual Behavior
Return a March date

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8sKwjAQRX9lmE0VbIuoCNIW/A7roqQpBPMiSbsJ+XeTxoJdJXO4nLnz8mgNqZ9aV8tM8YGNo0LzwdGulwDNUg5ar991IEq6gUlqfgjAexhjGkLYSIwlUmpGPtTAUgo1Ut72mGiPXVPvAps80r09kby8qf9KxdESw7QDS92cuzGhlXHgwdAJAkxGCSjiPUWKA0SvdblmmyIHOXN+TN5sig4MJ7xU1+qO6b1VZ3x/AXauXBg=)

![chrome_JFbtA9pLss](https://github.com/vuetifyjs/vuetify/assets/49377494/59ce5767-1efc-477e-bf48-d7a3a5b25095)

**Comment by KaelWD** [comment]
Does this not show up for you or something?
![Screenshot_20240131_012643](https://github.com/vuetifyjs/vuetify/assets/16421948/6a58076d-4a4c-4423-b57c-2040e4493242)
