### ISSUE TITLE
[Bug Report][3.5.1] Move forward a month in calendar - moves to wrong month

### ISSUE THREAD

**Issue by cvaroregidor** [vuetifyjs/vuetify#19126]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
I am currently using v-calendar and have encountered an issue. When I display the calendar, the component sets the current date (to January 30, 2024). 
When I navigate to the next month, it jumps to March instead of February. On the other hand, when I go back one month, it correctly sets the month to February.

### Expected Behavior
When I move from January to next month, it should move to February

### Actual Behavior
When I move from January to next month, it goes to Mars

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjssKgzAQRX9lmE0VfCCtm6BCoX+hLoKOVIgaYowt4r83irbdzT0D99x8wVFV4V3KwEyEDBNNnRRcU1b0AInxKy6or7kCRU1a4BkLBON3Q03CQsPFRJYw09K8Uwv1W1qWJeGvw3Ym4Z/AxrFSrdS7jF5yUBpqavgkNCwbA6i55gwcF9IMnIMBbOUMLt3Q6+fFO+m+g0He0wwPq3Dc8vit7n6s24CvElcPr8EtiGLcjjiIsPwA/fZWpA==)

**Comment by cvaroregidor** [comment]
@KaelWD This bug is about the v-calendar and https://github.com/vuetifyjs/vuetify/issues/19087 is the v-date-picker

**Comment by KaelWD** [comment]
It is a separate problem this time though.
