### ISSUE TITLE
[Bug Report][3.5.1] checkbox lost reactive when click

### ISSUE THREAD

**Issue by Math-chen** [vuetifyjs/vuetify#19124]
### Environment
**Vuetify Version:** 3.5.1
**Last working version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows 10

## The bug will be reproduced in the following steps
1. click any v-checkbox
2. then click the btn `all false`

### Expected Behavior
after the step 1, when the all false clicked , all the v-checkbox clear

### Actual Behavior
the button works fine when v-checkbox not checked before, but when click the all false, the reactive lost

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkUFuwjAQRa8y8gaQIBG0bFBAZdMTdNd0YZyJiHBsy3aiSlHu3nFMIVRppW6i7z+el5nv9445K9KjMUnbINuxzGNtJPd4yBVA1q64MYMcDkIrzyuF9mpF84zictKfsKt1gXLVctngPmcOJQqPReLR+XXODll6v/xvwGYaMFg/piLkySsQWmpLGLRW25zBi5CVuJBx5qqQeJTylUuHxOVSQhl0oFHrNMc1QqBzk6Q323yDPMkxJ+gYYpaOwqWjE7YyHhz6JmZc1UZbDx1Y5MJXLUIPpdU1zOhxZqEHaBrlQk+MBva3u/MuTj2kvYv7LO/WZmz1i/AtG0WdWsHDGvMFXEmPD0i/CqtNlDajUj8NHpL+gzyM9gv6ViN2lsbQKC7WL9lT8pystyyIbbJmH18bd+/t)

**Comment by yuwu9145** [comment]
You are using single-way binding `:model-value`, when checkbox is clicked, it doesn't mutate `selected.test1`. Use `v-model` instead

https://play.vuetifyjs.com/#eNqVkUFuwjAQRa8y8gaQIBG0bFBAZdMTdNd0YZyJiHBsy3aiSlHu3nFMIVRppW6i8R//l5nv9445K9KjMUnbINuxzGNtJPd4yBVA1q64MUM5HIRWnlcK7VWK4hnF5aQ/oV3VukC5z5lDicJjkXh0fp2zQ5be7/3Hu5n2DtKPWYh28gqEltoSBq3VNmfwImQlLiScuSokHqV85dIhcbmUUIY60Mg6zXGNEOjcJOnNNt8gT+WYE+oYXZaOIqWjE7YyHhz6JiZb1UZbDx1Y5MJXLUIPpdU1zOhJZsEDNI1ywROjgf3t7ryLUw9B7+I+y7u0GUv9InzLRpFTK3hYY76AK+nx7ehXYbWJ1mbU6qfBQ9J/kIfRfkHfesTO0hgaxcX6JXtKnpP1loVim6zZxxfVdewr
