### ISSUE TITLE
[Bug Report][3.5.1] v-date-picker type issue on prop "multiple"

### ISSUE THREAD

**Issue by inroma** [vuetifyjs/vuetify#19131]
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use the newly reworked prop "multiple" with a number value or 'range'.
This leads to a Lint issue and build issue/fail (using Vite on latest version).
The prompted error is the TS2322 stating that "multiple" can only accept boolean value.

### Expected Behavior
"multiple" prop should accept: boolean, string, 'range', number as declared in the 3.5.0 release

### Actual Behavior
"multiple" prop can only accept boolean

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj0EKgzAQRa8yzKYKVZHWTdFCobeoXYiOJdQkQxLtQrx7E22hdDf/8Xn5uc1oTZtdmNNpJDxh6Ujy0Dg61wqgnJKGeT3X0GrlGqHIfNAKO99OWLRPMjAlUnc0VDUGWiPIcXCCB/LENOoRUPb1Zf/CQLb3yuxnh4+2NYIdWHLjNkdI1sbBDIZ6WKA3WsLOf2EX6gDeax2EDVCFSqToBVcfozgO9s3nTbjs8ZAe07zAcBRpjvc3vCFZ+Q==)

**Comment by KaelWD** [comment]
c48c2a797f96b2bcab26c75c3b3780b3c3b3b64b
