### ISSUE TITLE
[Bug Report][3.5.2] VMenu closes when removing a chip while another VAutoComplete dropdown is open

### ISSUE THREAD

**Issue by ExaltedJim** [vuetifyjs/vuetify#19138]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows

### Steps to reproduce
Click "Open Menu" button.
Open the dropdown for "Foes" autocomplete component.
While the dropdown is open, remove one of the "Friends" chips by clicking on the "x" icon.
The menu will close when it should remain open.

### Expected Behavior
Menu remains open

### Actual Behavior
Menu closes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVM2K2zAQfpXBl7QQx226pWDSQlooy0LpYQs9bPYwkSdErCwZWfYGQt69YzmxlR8n0EMPNRh75vs0v5p52kalFcm8KCZ1RVEazRzlhUJHXxYaYJbJGoTCsvy8iBxtXCxIO7KLyMNMqOOl03sB4GdBGn6Qrhb6oGJG7hWtCMCyyUixQa+PegSFkzU6Yxkr0LKnEH2VmVszgpUzoT4VypQUGx0Lw7FpjlFJ8cLMFaqSemoXpQ9KoM261PJN3JqFHDfxwdPd9F2XaHduZWx+pGutsWuUmuwJ5EFrXiEjXbY1PYOFUcBvE8f76YnDgNYEKAw3hxxdooSVXVlJOivDMoVPKrnLjb+CDNsboom1LMoBiGuOS0XxFU7jJHbSKWJPGvNBP55Yo6puERUufXrfr6eXV8rJJq8LaHKpB4lvAiP/rD+G/t/mXMnt7ztzruepOp1Dz740iA1yMriezDugUzWKZiMdNhuLh9U2S3gP8t8sCbYji6WwsnCeQpvCWMdjvkLOEbatkQwdvnl7kAAsucrqXuaKsMcU/KYa99r9/KbwNHpEnVmEeYZ5ORrD6KuVziHcG+VGz+ERLnvDnysJ34zWxpZHeHubmBHWZQtNR1M49gK74FxACk0PcX5Zqo2Fe+R1p4dZlXghC4+5dOtBUpjpEOcBNd0w82DW+gZln/1vqZQ8K0BfxF3704IszJLuAkS7cfRhcjf5FDXfj5Np9PwHr9/q6w==)

**Comment by yuwu9145** [comment]
duplicates #17004
