### ISSUE TITLE
[Bug Report][3.4.10] When V-Select is readonly, set the menu value to true and do not display the items added on the focus

### ISSUE THREAD

**Issue by AndyBeat** [vuetifyjs/vuetify#19144]
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
1.Create a VSelect component, set `readonly` and `menu`
2.Add focus event to display items when focus is obtained

### Expected Behavior
The dropdown menu should show the items that were added on focus, same as version 3.4.9

### Actual Behavior
The items does not show

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUk1PwzAM/StWLtukrWMrElK1ITjyB7hsO5TUFZXSJspHEar637HTjnWDA+KU2O/p2X72oRPOyvWzMUkbUGRi57E2Kvf4eGwAdu0qNyZ+YyB14/OqQTumYtKhQunPCYCsIg23P4r4HsUFeQqmIOms1DI4LIji3vXHyy3NYl7oRn1OJGtsAtH5mTK5wqrNVUACpS7wB+grrxgs0Mkp2K5qoituIbb/yiIXwmW+9XnAswuUuLaBM4NLu/XEPQqdtJXx4NCHwcSqNtp66GjEEnoora5hRsbPmA5Aus7Hvh3smTM/DEU74P4zmLFXsJktiVogxcyFTYwoaaw2LmN25fI3hUUG3gakSv3yN6HtjdD2v0LpjVD6V6HTYjo5r3ccvMyVwytwsqeRczX9yC1DI32lG/i+rHm8tgV0Q+NcI4knQyoR4nzPyxvWRYsS/VKkSZo8CH7vk82dOH0BRcv+bw==)

### Other comments
When V-Select is readonly, I want to see what other option values the dropdown menu

**Comment by KaelWD** [comment]
@johnleider what's this for? 48906bd4514559aba32a013284fdf4c23dd48c52
disabled is just supposed to stop the activator events
