### ISSUE TITLE
[Feature Request] Would like to change the default close icon used for chips in AutoComplete Component

### ISSUE THREAD

**Issue by myathetchel96** [vuetifyjs/vuetify#19143]
### Problem to solve
We have the flexibility to customize the close-icon props in v-chip; however, these props are not extended to components such as autocomplete and combobox, which utilize the chip function in 'multiple' option
https://vuetifyjs.com/en/api/v-chip/#props-close-icon

### Proposed solution
Request the addition of a feature that allows the customization of the default icon used for closing chips in autocomplete and combobox components.

**Comment by blalan05** [comment]
Easy enough with defaults provider. You could even do this with the [global defaults](https://vuetifyjs.com/en/features/global-configuration/#contextual-defaults) and/or create an [aliased](https://vuetifyjs.com/en/features/global-configuration/#using-with-virtual-components) component.
https://play.vuetifyjs.com/#eNplUU1rwzAM/SvCDLxBk7KPXkJaKDvtD+zS9pAmympwYmMrGaP0v092liXZ7INlPfH09HS4Cu/K9d7atO9QZCInbKwuCHfHFiDvk8LaGMZPaVoqVIvuJxWTFdZFp8kn1pleVehGDCAbse1RXOF935EpDfMjYQaceL0oG4JSG49vzJ6BvGMhpOovuQJdnFFnQK5DuIV7FCP3r4BB5Ix4AgBK5vfzRKZ4vqDmIE2L3ELSp4nPxSFKOE0dwumTxlSoub7xH0soSC7OGpM/PXb5eqlnsoqBf16N3jK2NDfSRO/z9Wwn/PWlU5bAI3XDalRjjSO20WHNLtXONCDZRRnKWalpPQEPANtQcR8nfwi8AxNziNtKPKcv6eNGhGCTPonTN3h/ptU=

**Comment by blalan05** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
--
 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
