### ISSUE TITLE
[Bug Report][3.5.2] Sort by raw in v-data-table did't work

### ISSUE THREAD

**Issue by claussma** [vuetifyjs/vuetify#19147]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Firefox 121.0
**OS:** Linux x86_64

### Steps to reproduce
I'v copied the code from the documentation. The data in the example is mainly sorted by location, but the resulting table is not sorted correctly. I tested the function locally and got the same problem.  Maybe sortRaw did not work properly.

### Expected Behavior
The row Location should the sorted by name

### Actual Behavior
random sorted values

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlWW1T2zgQ/is7+QLMxCl55WVoZwLtlfZKywE3nbvrfVBsEavYkivLoWmH/36PZDvYmSZF1084tiXvs/vss7vin++dXIfPplnWWxS8c9w5MTzNEmb4i0+S6GQRsCxzl+5HqKRhQnJd3XI3I2ZYYNgs4XQccxZxnT//1KmuPnXoWGBPe8v9/dR5cfKsuajeHTfb29s75ddPnjWsws881CIz7iX+NVPaUMRvWZEY+l5uZnc/pt09ev6Cdqt7RJVJx/RPfYfoOxlhEn5MO+9Zyne6dMeX+CHtD3roNl58vKTVmncqZEYoudN4kaotkh8+y2HtFbvfZV2a7bU3JRK3tMt69UI6odnqxx5pbgotKehvXfPiR2uwpL0Ijs7hNDh0Ss+J9dxvXYSGR708S4TZ3Ql29nqZynb3ekaLdHdv0wan2GD2tA3aW1S2OSOcyQk/U2nGNN91+3apkAgr6BB11x1FJIuUaxEeE77KWx52XuYyF0YshLGRmLEckW2/89AC1Ax0K+irSJ89AlyRpAF6jSurZS95yVXHg2pZ1LjXWPbv6srlSZulTWMtN7HNa82ZoculZqmISN3Sa/GNtWHWRMDbr+bLzLSfNszHC4Px4SgYjCd9Oj1rv9ew97jtxJ2bmJNK8IIhJiNKmJ7baxhj8MTEmnPKSgtzEtLdtWbWN2ED8pp/7TW/uDHrKuDnTM6FnNNrpiPE2X7tlM2WyXqqNdC/0ezLNvCT/X0f2FNJLA+5jKwZOXjInRVGcM0jmpd2dSlnQGgUxWzBaca5pFkhIFJwBJOh4NLUhnvhvzbMFPD7Lf3Ni5xAgg/JMs3E5uCDKjxcS4G2A0bDsZcDaC4YzM9BQSC+FfNCryzqUgqdpdnShTsPiyQzStNlLCLBci+oN1b23cZTjaQQDu2rLOZ5kW9Ee1NoJNo2tOOxX7hLYpMrQhxvRgIfA27E1kKcqwir89rGLinpbLbPrvkCcf+oIGW6JAluTqvof1Q6ibwccsGKXCW8SK0jzlkCQ7Rk+a+5Yzj2SvopcKezisu3iGxplA08A+eNZlkN9BKgQRR6BXpq7oX0TCXK4rJbXcUK9vwCvQdHg2Bw6Bn0fJVnTrbwkTvKCxkg3HTOE6EAGAlvP1FrW4iC82iwF953Yh6bWBV5SXeIIhRVb0nqnyu6L+Dk0YQyuFUKXxpQLmUipN8heJFKQXD3QOSJlX3YexkzrfwAl/XrI0sSu8FZLORmrD942sZ6YGKCIKOjWAIzBdSfjEY0fekT7pWOg9NG3Nocx4t5qWa4nRvkNdo2tB13oLoFDidoPDdYyhI/+JccibIR8FulI7ZWz9aStj/wi24sAAC2s6Sk6Z1U99LlrzA5aRXeBWGBOq7DGA1ICFdyB/LewrMfjwoBxV/mEDk/EWefIRExSzaXZ1TSreHtT4aDoD8ZD71CKkkslF4G9xYQwqTtiJKuFLQica4KkGfG5F2d6n+xtJCMtFhw7anOYVzQpQjxZyNYaOLawzWsI1SnbTAdsjcyhK4ikCBnAu4axHce1zo0RbnJ6UIVbp7yIyZyLYxRs96YLe3kBf8qQvWzlsor/8oam2keQPqLdGbrhiUj46gEc8db9PRr0nTBlmgmuUJd9gJ5pVJsX9YYcGEzMw1LttbOg/0AMuvHSrUAFpZmoCVGUoM8q8sHFKzso1rFRKV+4K6tUCGE87Wa2MD1p4Qro1rPt+rMvuuNIamD8sojpAhmrTqUKjuyoemx2+OmbZ0BzqZZeYVyWzXU1nw/zk7l/A5C9pGtFcRmCWHpTP1MZgaNMuIRUzsG1bOPRmcwFyiij4ir6N7bbg/NocZzibK3bH4dAwV8cS6gslWf6ac8igkqBwNXwl4xyLSmN65Abyuryda+qT8Y7wf9sV8qXyipcAIAGaG4sGlWjgc5oVddAGmVulcsY/S+EFX6WjluWe05E2IgoWuFnNosWk8YDIYHfqKF8olziKo5/KDRPUXqK5oZbRkO6BnSWzgVS1BicmEb9i64YmHi8QeDVhp/RZq5FgKcyb+g57R1F+UZjEjRjRV+9XaaxOD6lubiOkNR2Br24RPzwCU5S1hYmmwbJwQakS7H+vKjZXv8WjPJIuaF5DelZwKzFZQaWvj/u8P+aH8S9EcDz4pUIavBAIQTaITplIvPkCqM+FwvrGYhey2nY0i1TT8kMNcKA5/1Ch4IjUeIZIzDEt9qbKlUJgyPOAfbNvrhVLNvYq3LWnPE0QB91NGw//MGA8MsveShaoxBb+3YXZHbeuNKKKyjt0wCoPLjaKhVBpVwYjUFOvkr49241f17HeNUk3jdSNWEhRihMqEnRgUujDWW2EzhGKdZmEu7PQ80tGahMobBwekvUHowmgSD/YlfPQ5VkqCzt+fEtsd4tKU8pHEiHfFM4BVw2kJlOq2Goj8Q8OtY0HmB47eue3grNIiA2d5yfTXE+U1BDJrJ5ZajuyecXY0OgtHw0M8VlXBXRzrVKOACamV7Rc/ultMe+7If2ht1j2/CUe8wTW3B/PTurL9/cOgnaquGLESxBfQG4y06CQlvT0NXdgyiG9QUEKGhgSUGL/zvcToYxvcMCDh2OnMWbI4816iNW+t1/3ByFPQPDyd+PugfmTioBcONAtyV3Su+ELY3r4S/FIFiPod70CmhZ19JwAI/GcYV+OhcWRVwsOas2OCP+nD/Yc9dPNj/aa3+i9V56HaGvVGvP+7Yi3Fv0Pn3P1KZ+OI=)

**Comment by moltinginstar** [comment]
The `sort` and `sortRaw` properties of a column define how the table should be sorted when the given column is selected.

In your example, if you want the data to be sorted by location by default, you can set the [`sort-by`](https://vuetifyjs.com/en/components/data-tables/data-and-display/#basic-sorting) prop to
```ts
[
  {
    "key": "location",
    "order": "asc"
  }
]
```

You can also set `must-sort` to force the table to be sorted by a column at all times.

[Playground](https://play.vuetifyjs.com/#eNqlWd1y2zYTfZUd3dieERXr17bGyYzs5IuTL05c251MW/cCImERNQmwIChH7fjdewCSMqmpFKPJjSmABPZgz57dRX77u5Pr8NUsy3rLgnemnVPD0yxhhr+5k0Sny4BlmXt0P0IlDROS62rIDUbMsMCwecJpGnMWcZ2/vutUT3cdmgqsaYfcXzuQK22C+QpD9ulsddd5c/qquVC9IwbbW9qR0qLTVw1L8TMPtciMe4l/y7AsRfyeFYmhv8vF7OpT2j+g129ovxojKg2Y0m/1ANXvl//uOg8c9k3xkKiQGaHkXafbfkNpIC3fYXl413mefaoff19/Up1Le0cywiR8SnufWcr3uoQ98UPaH/TU2K1lWv3Np8quvZZZ5RK1ze05C/qaPe6zLs0P2osSiXvaZ736Qzql+frHAWluCi0p6O/85s2/fYNP2h/Bszm8BA/O6DWxnvuti9DwqJdniTD7e8HeQS9T2f5Bz2iR7h9sW+AMC8xftkB7ico2Z4QzOeHnKs2Y5vtu3S4VEjwC/6Lu5kERySLlWoRTwq68dcLulLnMhRFLYawn5iyHZ9vvPLUANR3dcvra0+fPANckaYDe4Mr6s7e8DA7Hg+qzqDHW+OyZpy5Yt8eF5SaWea85M3S10iwVEal7ei/+Ym2YNRHw9rvFKjPt2Yb5eGEwPh4Fg/GkT2fn7fca9k7bh7h3G3NSCV4wxGRECdML+wxjDGZMrDmnrLQwJyHdqDWzHoQNEBL+rdfccWvUVcAvmFwIuaD3DMEvc7vbGZuvks1Qa6D/oNmfu8BPDg99YM8kQW24jKwZOXjInRVGcM0jWpR2dSlnQGgUxWzJac65pHkhoIo4CCZDwaWpDffCf2OYKXDu9/QrL3ICCb4kqzQT250PqvBwIwTaBzAajr0OgBaCwfwcFATie7Eo9NqiLqXQWZqvnLvzsEgyozRdxSISLPeCemvzjFt4phEUwqF9l8U8L/KtaG8LjUDbhXY89nN3SWxyWY/jzUhgM+CGby3EhYrwdV7b2CUlnc127oYv4fevClKmS5JgcFZ5/6vSSeR1IJesyFXCi9QexAVLYIiWLP+x4xiOvYJ+BtzpvOLyPTxbGmUdz8B5o1lWA70CaBCF3oGemnshPVeJsrjsUtexgj0/QO/BySAYHHs6PV/HmZMtbPJAeSEDuJsueCIUACPg7Ra1toVIOM8Ge+H9JBaxiVWRl3SHKEJR9Y6g/r6i+wJOnk0onVuF8JUB5VImQvo/BC9SKQjuJkSeWNmHvVcx08oPcJm/vrIksQucx0Jux/ovs22sRyYmCDIqihUwU0D9yWhEs7c+7l7rODhtxL2NcbyYl2qG4dwgrlG2oex4ANUtcByCxrzBpyzxg3/FEShbAX9EYcs28tlG0PYHft6NBQDAdpaUNH2Q6lG6+BUmJ63ChyAskMd1GKMACXGU3IF8tPDs5lEhoPirHCLnJ+LsD0hEzJLt6RmZdKd7+5PhIOhPxkMvl0oSS6VXwaMFBDdp2yelawWtSJyrAuSZM/lQh/ovLC0kIy2WXHuqcxgXdCVC/NkKFpq4MbmBdYTstAumQ/ZBhtBVOBLkTMBdA/8u4lqHZkg3OV2qwjVwfsRErIUxctYHs6OcvOTfRKi+V1J5xV+ZYzPNA0h/kc5t3rBkZByZYOF4i5p+Q5ou2QrFJFfIy14gr1WK5cscAy5sZ6Zhyc7ceXQYQGb9WKmWwMLSDLRES2oQZ3X6gIKVdVQrmajUD9yNFSq4cLGRExu4fpY4yqjW8506c+hqY0jqoHzycCmcWasOpcq2bCh67PIYtKUzwNkwK5+QbquC2prvx9mZXDxAyL6yjYTYTCEsnavvycygkUY8fGrboLr30agMFgJJ9Blx5d1HW+2hONSYl0h7q+buaChwFhcCKlvVmX7Ko5igsjFwKewdg0xr+uAS9K60muysm/qD8WHQH/uF8qWSCjcAkBGKCxtmZXuQE2rVJZBWoXvNMkafC1GFr5XjltWePSEaErpRiKntovWCxmB45CdaSJ+4h6iKwy8a1VOkvqGY0ZbhgJ4hvIVTsQQpJhe2YO+CKxYmpr8YlNL4K9LMlRDgTP4nak6bd5GewYgU1Vjhl29nSQyu7ygubjIkhZ1uH74wDlyQs4SFpcm2cIKj4emyrS83Lcvj95pJFjEvJP9Tei7QW0GpoYX/vTrsjw4nQX808MxIFbIaDEA4gYabzrj4A1KFFp/rpdUsRK/ldAyptuGHAOZaoeGzp4IJoTEFT8a4LPHNxpZKZcDwiHOwbes5nGn2l9iosjYO4mSAOupk2P9+gYFmlt7yUDXaoI+27a7IbU/jWih8Rx+ZBEDlx9FQqwwq4cRqBnTyR9q7cav697rGqTrxupCqCQsxQmZCTYwMXBhrLLG5wjVOMzGXdnteaGjNQmUMwwGnP0DpwWgSDA4nfvk4VEmCyt7eE9sa49mW8pLGiXTEM4FXwGkLlem0aop+gsNvYkEXBa7fum7yXmgQAb295fq6ifPrghg0k8sdV3cvuLsaHQWj4bHfUVTCXV3pVK2Ac6iV7TU9uztue+zLfmhv1SP2xEF9Qje1A/PLq7P+4dGxn6itC7IQyRbQG4y36CQkvN0NXds2iG6RU0CEhgaWGLzwf8btYBg/MiDgWOncWbDd81wjN+7M1/3jyUnQPz6e+J1B/8TEQS0YrhXgLu1e86WwtXkl/KUIFIsFjgeVEmr2tQQs8ZOhXcEZXSirAg7WghVbzqO+3H86cA/4z6nTV+v/Nus8dTvD3qjXH3fsw7g36Pz+D3TRHBE=)

**Comment by claussma** [comment]
in my own example I use:

`
sortRaw (a, b) {
        const orderStatus = { 'finalized': 1, 'ongoing': 2, 'new': 3, 'completed': 12 };
        return orderStatus[a.status] - orderStatus[b.status];
        }
`
The resulting sorting has no order. What's wrong?
