### ISSUE TITLE
[Bug Report][3.5.2] v-date-picker not updating month and year when date is changed

### ISSUE THREAD

**Issue by cintek** [vuetifyjs/vuetify#19146]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.3.1
**Browsers:** Mozilla Firefox
**OS:** Linux

### Steps to reproduce
1. Initiate Date Picker with a date ref.
2. Change month and/or year of the date ref.

### Expected Behavior
If I change the year of the date I expect that the Date Picker will show the year where the dropdown menu for month and year is. The same is true for the month.

### Actual Behavior
Month and year remain the same in the dropdown menu in the Date Picker.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplT8FqhDAQ/ZUhl1VYY7XrpahQKL3tB5Tag+gslcYkxMQexH/vxLRl3T0kzLx5M++994VNpkufteazQ/bESoujFq3FupEA5Zy0Wm/l1nRK2naQaH6hDeyJneih+0IDczKqHkXVMI82rC7THeHvFKH7Wx4JUmV6ZYHaqTODtjChdcHJMGplLCyg5Fk5abGHFS5GjXCgDIcdxeDlZujHJD1Z8Lag8pRI4je8UBvlD/npCFnmXxwH9r9MFMVQ1bCEDH6dz61wyMnbqxPiDVvjLxS0eM84U97PKMu34Up/mYZoFIqtR/bITzwrmC8KnrOPHxhthBg=)

**Comment by KaelWD** [comment]
Date should be treated as immutable: https://play.vuetifyjs.com/#eNpdUMFugzAM/RUrl4JUwmDlMgHSpGm3fsA0dkDgamiQRCGwA+Lfa0OLSg+R4veen5/9PYneVuG7MXIcULyJ1GFn2tJhXiiAdAxKY5bvUlRaubJRaG/QAtakDkxT/aGFMeh0jW1WCEYLkafhTnC3InTvxcg6Kg0fIlDZV7YxDnp0w5qk6Yy2DibQ6qwH5bCGGS5Wd3CgHQ47icXLE8k0je4dcCzIWOIp/IcPKr34JT4dIYr4+f6q3sZ4ng9ZDtO6w82EHLZudpRj2Q5IraypJcX+HNr2C0vL5skjcaYL/HpRfMe2bvKsGZuJScP1ALS6mI/iVZ5klAj+JDIWP1dtJY62
