### ISSUE TITLE
[Bug Report][3.5.2] v-text-field type="number" bug

### ISSUE THREAD

**Issue by Thomas-jqt** [vuetifyjs/vuetify#19158]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1- Use a v-text-filed with type="number" 

2-enter a decimal number like 1,2 

when we hover v-text-field even if there isn't any rules, a text is shown with "please enter a valid value. The two closest valid values are "2" and "3"."
but I've never tried to check whether my number is an integer or a decimal

I don't think this message should appear 

### Expected Behavior
don't show any message on hover is there is no rules

### Actual Behavior
a message appear at hover even if there is no rules

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWLAktaJENy0zNSdFoaSyINU2RimvNDcptShGSSEnMSk1ByjgA6JjlOxs9JGVw8wFCqIaDBKB2Gujj+QepVodJWM9Ez1zJRBtqmekFAsAsQU9Bg==)

**Comment by jacekkarczmarczyk** [comment]
That's native input behaviour

**Comment by Thomas-jqt** [comment]
is there a way to mask it?, without using decimal step ?
