### ISSUE TITLE
[Feature Request] Full Calendar

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#1915]
Google will introduce soon their new material design full calendar. So maybe, having a calendar on Vuetify component would probably attract more users ;)

https://9to5google.com/2017/08/14/google-calendar-desktop-redesign-testing/
![image](https://user-images.githubusercontent.com/9329005/30911654-15515730-a3bc-11e7-946e-1ef668096d46.png)

**Comment by jdriesen** [comment]
That would be really great....

**Comment by Kung-COUL** [comment]
+1

**Comment by CodeSkills** [comment]
Just wanted to mention that the Google Calendar is now fully updated to Material Design and it looks  and works great. Most of the components are already complete in Vuetify, so basically the only thing left is the calendar itself (Day/Week/Month/Year view).

**Comment by jdriesen** [comment]
That's SUPER COOL and AMAZING News !!!

Thanks for sharing.

Kind regards

**Comment by mesaglam** [comment]
Yeah it would be great. Vuetify calendar...

**Comment by sbowler** [comment]
We are very much in need of something like this very soon as well. It may be advantageous for us to send in a pull request with perhaps some initial work on this. I'm not sure where to really begin or if you would be open to that.

**Comment by ClickerMonkey** [comment]
I've started the development of some new calendar components in https://github.com/vuetifyjs/vuetify/pull/4846 based on the experience I gained with dayspan-vuetify

**Comment by scottpage** [comment]
Will this receive support for scheduling resources, with timeline view?  i.e. People, rooms, etc.
I'm currently using https://github.com/CroudTech/vue-fullcalendar but it depends on https://fullcalendar.io/

Great work, BTW, thanks for doing this.

Example:
![timeline-view](https://user-images.githubusercontent.com/4706279/51913409-a6f8d200-2393-11e9-8188-84b877c4f72e.png)

**Comment by jdriesen** [comment]
Super interesting thread ... I'm following !

**Comment by promentol** [comment]
Is there an update, regarding supporting event resources in daily or weekly mode?
