### ISSUE TITLE
[Bug Report][3.5.2] Setting global default prop 'hide-details' as 'auto' did not work to VTextField

### ISSUE THREAD

**Issue by 1552980358** [vuetifyjs/vuetify#19168]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Same in Reproduction Link, setting prop `hide-details` as `auto` to `defaults` in `createVuetify` does not work, while other prop, e.g. `variant`, set in `defaults` work well. It requires man-setting prop `hide-details` to VTextField, so that the `hide-details` prop can take effect, but not in `defaults`. Reproduction Link provides testing on `hint` and `rule`.

### Expected Behavior
Work to global with setting `hide-details` to `defaults`.

### Actual Behavior
Did not follow `defaults` in `createVuetify`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU9tOwzAM/RWTl4K0tuL2Mm2TEBJfgHihPJTWpYE2iRK3Ao39O07aXRgIDXhp4mPHPse175fC2SLtOyRZvSXPTkyFbI22BEsoLOaEd4MPVlBZ3UI0xkaZyhS+htBCK0cwOmD++eHxMlMAVGOLUwh3gBKrvGvodgCjRj7VFE0GX5r6cxWsMc5tHt7d4ivdSGzKDQQQ1bLEuETKZeMizpd3pNfpAPrcylwR47qjRios176hiP+uTjIlJqEXV8YkLIUbMSNsTcNKFj5s1se5MeEaDBbNBRXaEQogMb248vygj1tdYjPPROueMgG1VMSGP9hKt69K2S88GnfOqwiK411J8aMm0u0s9ZG+7YeV2yZg0LfkIBIO94obq82fGExt16CvfY/WantdY/Hy8LVqcI7a/1nxe82/4uHl/8AjRKf7P98jw2zM0p2ZYdMVVhoCztoNo7NZLovV7kqFdYJxk1gNbxFHHPNYbuEtffb2MF+sV8Byeqvg6KiH93eIQhwn5NH2jAYOXF2sJuI8uUhOL3nUz5PL5Ew8fACJFlMB)

**Comment by yuwu9145** [comment]
>  When set to auto messages will be rendered only if there’s a message (hint, error message, counter value etc) to display.

https://vuetifyjs.com/en/api/v-input/#props-hide-details

**Comment by yuwu9145** [comment]
Use camel case "hideDetails" in globalConfig

https://play.vuetifyjs.com/#eNqNUktuwjAQvcrgTahEErWUDQKkqlVPgNg0XaTJBNwmtuVMIirI3Tt2wqes2NieN29+z/NxELXN4rZBksVv9F2LuZCV0ZbgAJnFlHDT+6CDwuoKgoEbJCpRuPfUTKuaYHDA8n/g+JAoANphhXPwb4Aci7Qpad2DQSm3OwomvS+O3d15a+DV58DNGvf0LrHMzxDATub4hpTKkolkGxwyAbSplakiLqEbKqXC/FSlz+/O7iFRYuJleDEm4ilYgwVhZUoeYuVoizZMjfFPb/C8XE2hHSAPEncWFq41aMNK51guE1HV20Rwg4rYcBdb8SUql+3KoWFTYzgMG7px2PDzhF+aSFeL2DGd4veUm19nYNRJclcXNd5UN1abmxZ8RHyrgUN6iRbxlXRs1pmVhoBTN72C5/WyWFwvlV8oGHaJB+E9YsaYf+cCo7Xavu4w+2FvC8vVaQksp7cKRqMWjkcIPI8T8g+7jvoeuLroJmIaPUePM/7xaTSLnsTnH7bM/k8=
