### ISSUE TITLE
[Bug Report][3.5.2] Maximum recursive updates exceeded for large forms

### ISSUE THREAD

**Issue by N1XUS** [vuetifyjs/vuetify#19161]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create form with large amount of controls that have validation rules applied to it

### Expected Behavior
No error

### Actual Behavior
Error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNlUtvm0AQx7/KiEtAthc7TVXJxW4itT1UVQ+9hqjawBDTLgtdFseR5e/eWR7OYgerPqTqwTLMf54/9nG7dUoV+TdFwdYVOnMn0JgVgmtchhIgWE+SXGWwnmR5jGIROmsu0jh0arXWo1xqnkpUrYmMXQoKo2gKUvkj5AnQXxk6MP+FT42RpTLGzT5bm5EEy9AWEUC/ksJml5Qii+npqhfYemrc6EmSooj7ElgzmMpJqkr9jWcYOoeOc1UJNKUkyd/N8ws+UV5JjWa42fRYFvy+rvTZVAGT59hH4e8qVXjU5yqNcRIjQRVlX1sGvj1gHxJJRIhsr45O8H9A7isVGQA3DGgI6n8CDjNq+QS1Wh/A1nH5NHk5yWtBsS32xgz83kHRhdhngbGY04Neet70WkYqLTSUqKuCRpMPNJmmqeu4NCtypWGrMNlBovIM6NipaCG8bypRlXZt1KxgAbf9yeiMqhAWS9gekkgTcGvVIyi6UhK0osy9T98Qq8ULs8whLfcE2UXfczc+u/IHJlA+6BUEC5hNz+kjq2jsewSauQS94pLiIVpxxSPaT+Xp3u4Ino3vea0d8hua4e/YdR0367Rjd4Su39ypkj4bXbNRGDI28pnGUrdNnNNFR66+vIYbMYyeCdXOBIeWoZtwUaLXyp2Duc5aXeIj3CjFn9zZdOrR5SKEKyshPJbxwnV/jKG+6Twzo2sNub+F5rTGv+QrGTpWP91Ba8SPOW0AS6M7dN4ktYz1RzXeP1mc4zVuOG06ZFGeWbE7zzOTBH6zCWnLObux84ZdsXeO+X/LLp27PxVROfQ=)

**Comment by N1XUS** [comment]
More information: if you create same form with lazy validation, yet. trigger form validation when component mounted, error is not present.

**Comment by petrprikryl** [comment]
I have same problem with v-checkbox https://play.vuetifyjs.com/#eNrtVEtv00AQ/isjX2oryTqhRUIhKa0EHDhw4FpXaGOPG9N9mN11mirKf2fWj3YNtCJ3IkX2fvP65vPM3hwia/L0uq7ZrsFoGa0cylpwh5eZAljtZqU2EnYzqQsU6yzacVEVWdRaW3uuleOVQtNDBA4pKIyiKcjoB9Al0MNmESzv8bEDWaUK3D9l6zOSIQD6IgLobyls8YZSyILeLkaBg+cW8/uN3geUfaGyMtZ95RIpWPBNi3/2GKgOTMcl07YmYf+J/E4kRMJPtUpHozOEhNPhET9PdBh509HmpqodWHRNTXzUHdFxNC1tXCVrbRwcDJZHKI2WQIPYEMn3XSWq0vP+1gi0sIabsQw0tQ3C+hIOY5xSlxC31gQM1TYKnKHMI7n9rzeeecWgsnT+2VQGC3Y29jxOT678gQlUd24LqzUs5qfwkA21vUGgni24LVcUD/mWG547NPZ1brckXigfSl6Jv+r3Ug//pt3A+NPMFxi0+0O6MbnXSqZscsUmWcbYJGUOretJnMJiUK69zl4m4jV6Vqh1JnFoDOOSC4tJbx4c/AXX2xU+wLUx/DFezOcJbZsQsWqESJjkdRx/n0J79yW+xzho8mktlzTjX/RWZVHAR/Bn40dNCxDY6FZddkkDsP2o3vsHKzRe4Z7T0iHLtQxij0niO1ml3RLSykXHaXTOLtjiXeRf3rLz6PYXaG/EEA==

**Comment by KaelWD** [comment]
There isn't actually an infinite loop here, a watcher is just being called for each component in the form and vue has an arbitrary limit of 100 calls in development.

**Comment by N1XUS** [comment]
But if you change the validation to be async, and still call the validation over full form after it's being rendered, then there's no issue. I'd say there something wrong with refs/computed triggers, as they trigger multiple times per form control
