### ISSUE TITLE
[Feature Request] Style code in documentation in light mode when the site is viewed in light mode

### ISSUE THREAD

**Issue by oldgrognard** [vuetifyjs/vuetify#19166]
### Problem to solve
Improves legibility of hard-to-read code examples.

### Proposed solution
Add a light mode theme for the code examples.

**Comment by KaelWD** [comment]
![Screenshot_20240204_164011](https://github.com/vuetifyjs/vuetify/assets/16421948/e4da7beb-2d55-4fbd-bd62-4a1d17b2fe22)
