### ISSUE TITLE
[Bug Report][3.5.2] Focus order for v-items in nested v-lists 

### ISSUE THREAD

**Issue by kmmerc18** [vuetifyjs/vuetify#19179]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.7
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Tab into the list, then use arrow keys to navigate between the items in the list

### Expected Behavior
The focus indicator should move from the first item in the list consecutively down the list to the bottom of the list

### Actual Behavior
the focus moves to the first, third, fifth, second, fourth items in the list. If there is an even number of items in the v-list, the focus only reaches odd-numbered items. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkF0LgjAUhv/K4VznhD5BTOgi6ELoB7QuRJaM5jZ0CSH+95yVdbKr7X14zhl7Ty3WVR7urGXNTWCEsROlVZkTCdcAcRNk1g7XIeRGu0xqUb3QAJWs3Zj/kZ69t0ITXEy15ahBalhzhOgq7j5zJBPjnkD2s+BM7xTGFEqw3JQTmeqBk06JBA77ND1C24KGroM4nCo/T34b9AMh6YXqnzIo8JE25smzULIQuxku2JJt0J8rNsfzAzmGdnE=)

### Other comments
Obviously the recreation link is missing any reason WHY you'd nest v-lists, but we do several times for several reasons, so this does need to work in this scenario

**Comment by yuwu9145** [comment]
I'm interested in knowing your use case that requires nesting v-list. Perhaps there are better and right ways to achieve your use case

**Comment by KaelWD** [comment]
I think the best solution for this if you can't restructure it is to add `@keydown.stop` to the inner list yourself.
