### ISSUE TITLE
[Bug Report][3.4.8] Unable to left align v-timeline while side="end" and having v-timeline-item span full width

### ISSUE THREAD

**Issue by henrychoy** [vuetifyjs/vuetify#19174]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
I'm trying to have my timeline left aligned on the page, with all timeline items to the right of the dot, and have the v-timeline-item span all available width of the page.

1.  Create a v-timeline with items on the right side (side="end")
2. Set v-timeline-item width="100%"
3. Put an outlined v-card in v-timeline-item
4. Try to left align the whole v-timeline

There's no way to left align the whole timeline without affecting the 100% width of the v-timeline-item.  I've tried making the v-timeline a flexbox item with class="d-flex" but that breaks the "side" prop.  I've tried wrapping the timeline in v-row but that breaks the 100% width.

### Expected Behavior
I should be able to left align v-timeline without affecting the 100% width of the v-timeline-item

### Actual Behavior
Adding d-flex breaks the "side" prop.  And wrapping in v-row, breaks the 100% width of v-timeline-item

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkMsKwjAQRX9lGHBnX6ggEgt+h3ERmpEG0jQ0aRXEfzdtfaRLd3MvZ+48zg90XZWdrE2HnvCAzFNjtfBUcgPAhkRYO5WT8KohrQyBU5KOHMlIjlBp4VxQMrlqunN884uORIVguCnp60AWeb6KuImsRCdhEJ0Sxgek7f3YF/JLqEnrFlg2Q7/4YCzyP4tGfrC+2/83YRTz8SyLnoLPNW7SbVrscC72eHkBorhmwA==)

**Comment by johnleider** [comment]
You've added the "d-flex" utility class which is overriding the default grid implementation.

https://play.vuetifyjs.com/#eNrFUc0KwjAMfpWSs9sQFUSq4HM4D2UNWOi60ma9iO9uf2RO0IOn3ZJ8P/lILnfwrmvO1tZhRDgAJ+ytFoSn1jDGQyWszWVuSPWolUHmlcRjC2hkCy/4g1Cp6DMBGeqEkywIp4ShKB1GSsSkZzfUemC8KaS3Xxx8M5zPf2fzJBwtn27K99+G1JTT82b2EnisYFNv6/UOSrGH6xO5QI8J

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by henrychoy** [comment]
Thanks for the reply, I only added the d-flex to illustrate that there seems to be no way to left align the timeline item while having the v-card take up all available width.  

For example in your link, I want the timeline left aligned, and the hello card to take up all available width.

**Comment by johnleider** [comment]
> Thanks for the reply, I only added the d-flex to illustrate that there seems to be no way to left align the timeline item while having the v-card take up all available width.
> 
> For example in your link, I want the timeline left aligned, and the hello card to take up all available width.

Please submit a new issue, thank you!
