### ISSUE TITLE
Allow adding classes, style and click handler to v-dialog's dialog__content, and its associated overlay

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1918]
Since there seems to be little interest in making dialogs and their associated overlays stack based on when they were last made visible rather than when they were first added to the dom,  it would be nice to at least be able to target specific and active dialog's  div.dialog__content by allowing us to pass dialog-content-class, dialog-content-style, overlay-class and overlay-style parms to a v-dialog.   

Adding a dialog--content--active class to the parent div.dialog--content when there is a child div.dialog.dialog--active would also be needed.

This would allow using CSS to target specific active dialog containers and their overlays to allow us to set the z-index to what we need.

In addition, allowing some way to hook the click event of a dialog's overlay would be helpful.  Stopping its propagation, etc.

## What will it allow you to do that you can't do today?
Allow more control over dialogs and overlays via css.

## How will it make current work-arounds straightforward?
Current work-arounds to having stacking dialogs require changes to coordinate when dialogs are added to the dom.  This cannot always be easily controlled.

To work-around this with css, we need to be able to target specific  div.dialog__content based on if they contain active div.dialog.dialog--active. 

## What potential bugs and edge cases does it help to avoid?
Trying to deal with multiple open dialogs from different components.  For one example, a notification dialog that's opened by the parent of a component currently showing a dialog.  

Currently, depending on when it was added to the dom,  the parent's notification will not be visible until the child component's dialog is closed, even though the application may need that parent's dialog addressed before operation on the child's dialog can continue.  (Reaffirming expired access, notification of a record lock, etc.)

Regardless of when a dialog was first added to the dom, the associated overlays will always be behind ALL open dialogs.  This stops you from blocking access to other larger dialogs below.

**Comment by johnleider** [comment]
Can you clarify this statement please

> Since there seems to be little interest in making dialogs and their associated overlays stack based on when they were last made visible rather than when they were first added to the dom

**Comment by Webifi** [comment]
The "little interest" refers to previously closed issues that generally center around the behavior of multiple active dialog.  Broadly, the reason given for closing the issues was that opening multiple dialogs at the same time is an edge case. If there is interest in getting multiple active dialog to stack in a more palatable way, great!

"stack based on when they were last made visible rather than when they were first added to the dom" refers to how the order of how dialogs are added to the dom determine how they will appear when multiple dialogs are visible.    A dialog added first (but maybe not yet active) will cover a dialog added later when both are eventually set active.   It would be better if a z-index on the dialog's "dialog__content" container was set based on when it was last active, making sure it's z-index is greater than that of the previously and still active dialog.  Then its position in the dom doesn't matter.

Add overlays to the mix and things become even more pear shaped.  Currently, all active overlays will appear behind all active dialogs, when you would expect that the overlay for a topmost active dialog would mask an active dialog below it.  Again, setting the z-index of the overlay to 1 less than most recent dialog, but greater than the previously and still active dialog, would correct the issue.

**Comment by johnleider** [comment]
There have been 2 props we have added to help aid this, **z-index** and **content-class**. When it comes to the components being loaded into the DOM, Vue builds bottom up, so if a dialog contains another dialog, it's child is going to be positioned before it.

Another reason for generally not focusing on support for this, is it is not something covered explicitly under MD spec. That doesn't mean it's not valuable, but it does mean that generally, time can be better spent elsewhere.

Could it be better? Of course, and I really appreciate your well worded feature request. But please don't confuse interest with triage. There are plenty of things I'm interested in doing for the framework, most of which get pushed to the side for more critical priority changes/fixes/updates.

**Comment by Webifi** [comment]
Thanks for taking the time to respond.  I understand it's low on your priority list.

What version was content-class added and z-index added in? Doesn't seem to work in 0.15.7 (Nor do I see any obvious code to support it in the dev branch):
https://codepen.io/anon/pen/oGWXLy

Additionally, if possible, it would be great to have overlay-class, overlay-z-index and overlay-click (to hook overlays click method) or overlay-click-stop (to stop propagation of an overlay's click after handling it) props in v-dialog for dealing with overlays.

**Comment by johnleider** [comment]
The reason I do not like to add erroneous props is because you start to run into what I call **"prop bloat"**. I'd much rather setup a model where you can hook into a slot or scoped slot and then do whatever you want as opposed to providing tons of options that have to be maintained, I hope that makes sense.

As far as the z-index/content-class for dialog, this has been added to menu but potentially not to dialog. I'll check tonight and make sure, if not, I'll get it in.

**Comment by Webifi** [comment]
I understand wanting to keep the number of props low, but in the case of simply wanting to control the z-index and click handler of associated overlay, a scoped slot seems like overkill, and potentially more difficult to implement.  

That said -- I'll take a slot for the overlay if it'll work!

**Comment by johnleider** [comment]
Could you give me an example of a use-case for overlay z-index and click handler?

**Comment by Webifi** [comment]
For z-index on overlays; I'll quote myself from above:

> Add overlays to the mix and things become even more pear shaped. Currently, all active overlays will appear behind all active dialogs, when you would expect that the overlay for a topmost active dialog would mask an active dialog below it. Again, setting the z-index of the overlay to 1 less than most recent active dialog, but greater than the previously and still active dialog, would correct the issue.

The issue here is that without being able to adjust the z-index of the overlay, a topmost dialog's overlay will not mask a dialog below it, allowing the user to click on items in what otherwise should be an inaccessible dialog.

For the click handler:   Unless I'm missing something, the click handler in the overlay seems to be what closes the dialog.  That click handler doesn't appear to stop propagation of the click through other overlays, so if you have multiple dialogs open, clicking one dialog's overlay will dismiss all active, non-persistent dialogs below it.  

Since the current click propagation may be desired(?), having a prop to signal stop of click propagation would help in the aforementioned instance.  

A prop that allows you to override the default click handler for the overlay could more flexible, provided the click event was passed to it, allowing you to stopPropagation() in the override method and/or use it for other potential use cases -- though I'm not sure what those cases would be.

Perhaps I'm barking up the wrong tree on the overlay click handler being the culprit for all active dialogs closing when an overlay is clicked.  Here's an example:
https://codepen.io/anon/pen/qPmObG

**Comment by Webifi** [comment]
Merging PR #1932 would make this request moot.

(Sorry for any confusion in closing #1931.  I that request was a bit premature.)

**Comment by KaelWD** [comment]
The underlying problem has been solved, and in 1.1 you can now target the dialog's classes in scoped styles.
