### ISSUE TITLE
[Bug Report][3.5.2] Using VDataTable or VDataTableServer #item.data-table-select slot causes @click:row to fire when clicking select checkboxes

### ISSUE THREAD

**Issue by cojohnson1999** [vuetifyjs/vuetify#19188]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a `VDataTable` or `VDataTableServer`.
2. Implement the `@click:row` event.
3. Add the `#item.data-table-select` slot prop to the component, adding a `VCheckBoxBtn` to it as expected.
4. Add a `handleRowClick()` method to handle `@click:row` events, and have it log to the console when run to capture that the event was handled.
5. Notice that the console logging occurs when clicking a row AND its select checkbox.

### Expected Behavior
When using the `#item.data-table-select` slot prop, the `@click:row` event should not be triggered when a select checkbox is clicked.  Only clicking the row outside of the select checkbox should trigger the `@click:row` event as `VDataTable` does without using `#item.data-table-select`.

### Actual Behavior
When implementing a custom select checkbox with the `#item.data-table-select` checkbox, the `@click:row` event is triggered when the custom select checkbox is clicked.  This behavior is different than the behavior of the select checkboxes when that slot prop is not defined.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVt9P2zAQ/ldOGVKL1KQCxksFbIjtYZo0TYNtD4CEk1ybgBtHttOiRfnfd3Z+Oe0YvCBe+tT47vz5/H13V1+XnpLR9DzPg1WB3sw70bjMOdN4dpMBnKx8luf20y4ikWmWZigbExmTo+4b4KdKswXoBOFdSkBBzDTzNQs5+go5RhoUFxrSDH59IteV8UDECoUKogSjh1A89mgRT6MHBVrAPJUIH+16JsW6O3zqnE7p9cf1ICs/TLP49MYrIQiCPaa1VFDdeG7EUsTIKaTOEeMvlLtyQ2ZcsJiuRjFzxhW6PnNRf8V4geRN48E241PGvAVoLT7HbKGTNiCol26cSsS6oc7ZLFEXMvNFeE922q1lMUipZ4qcY5zYHPfh9AwSlsUcf4j1hYloXR8CG9BDOJJ2BfGUpJZa4yIsddkwOCHVFguO9drw7UDWpdTI7Yc6c110PStHT2kHOi7BGmf2OKichJt7FzmlhxsAbibPQEzdi08HrVCb3Bojc+cIpbN32BPfqOCLl/XFknrL9BfVPIXiY26v/S9dIcSErVIhYZ3qpOsdaqM52frm2nXKK3eKUf0lVXBFgiq2dKfYhoZPVQaxKEBEUSFVD2d39DJfolyhfF5swnQDd5rvpuNrTcem1F7YHudZDJl9GUS8MLVkJ6Adirb+h5MxElIa4roGoqHXY+3a4u1GYVsHw4eisdTvyEHZ0FJFMs3p349yq5+Z6TIXUkMJEudQwVyKJYzoaTqq64hwlQl3KIdTEzu+vt3vAywzraPOqmzTTOMZjA5Gk3ad0VQmy3fU2BvvRUi2z9mC7oCytVfN7xDrcAvrfEmMsU20iwTn/0c62kL6qhMmF+zPJtZvJrmQ8RDOMNBzMFSNyBho2hxsQgXHgIvF+M75a9pWfa/EagJ7pUGo9u8s2ZURtJaQxPOqiXcUvA8Ojj3zcRwcerd/AdUEwEM=)

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

**Comment by cojohnson1999** [comment]
@charlesg99 Sorry for the wait, just now saw this.  I believe this was how I figured out what to include in the slot content.  The [Veutify v-data-table docs](https://vuetifyjs.com/en/components/data-tables/basics/#simple-checkbox) mention stubbing in checkboxes in data tables as `v-checkbox-btn` components, since they're used internally by the table.

Given that, I just threw a `v-checkbox-btn` in the `#item.data-table-select` slot and wired up all the events to make the table's select boxes work.  Here's how I used the `#header.data-table-select` and `#item.data-table-select` slots.  From what I can tell, this replicates their behavior and allows you to stub in your own custom styling too:

```vue
<template #header.data-table-select="{ someSelected, allSelected, selectAll }">
  <v-checkbox-btn
    :indeterminate="allSelected ? false : someSelected"
    :model-value="allSelected"
    @update:model-value="selectAll"
  />
</template>

<template #item.data-table-select="{ item, isSelected, toggleSelect }">
  <v-checkbox-btn
    :model-value="isSelected({ value: item })"
    @update:model-value="toggleSelect({ value: item })"
  />
</template>
```

You could probably do some snooping in Vuetify's implementation of the data table components and see how closely this resembles what they do, this just worked well for me.

**Comment by charlesg99** [comment]
@cojohnson1999 Thanks for taking the time to answer. That's pretty much what I'm doing but it's time consuming when all is needed is a minor change to the default. Thought there was an easier copy/paste way that I missed :)
