### ISSUE TITLE
[Bug Report][3.5.3] v-tabs/v-window broken in Vue 3.4.16

### ISSUE THREAD

**Issue by donalmurtagh** [vuetifyjs/vuetify#19193]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.16
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
 - When a tab is selected, the content of the corresponding `<v-window-item>` should be displayed
 - It does not work with Vue 3.4.16
 - It works with previous Vue 3.4.X versions

### Expected Behavior
When Vue 3.4.16 is used, and a tab is selected, the content of the corresponding `<v-window-item>` should be displayed

### Actual Behavior
The content of `<v-window>` is empty when a tab is selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUrFugzAU/JUnT4kUQFXaDoggdezUJVvp4MBri2SwZQykivj32timJlLTodu787173InXC+lkmTwJEQ89kpRkChvBqMK8aAGyISqprOZ5RoqeOgsAhqjhFbJDQTRbEE+fPqKSMy41L2TdUPnl35yNN4KBsh61jLdYkPxZX4aXFrNkfv1NrEbuxceR/yX+lLh4Hw1YLzjUabhENIEjhWcVmo51W/HxOvKiCDRRbW6to/3IwCQMtvT9YG35jBuONn/oqGv4n6MraeU5czdcr/mg0HWBntEgS4KfS8OulLWwKjwLLhVU+E57puBi3SqqaAqbLRxy2DgOQFefQtsztrPMtJ2HyRxwlmTakX18H989EjM8xHvy9g2DeuDD)

**Comment by KaelWD** [comment]
#19191
