### ISSUE TITLE
[Bug Report][3.5.3] With vue 3.4.16 Switching VTab tabs make the content disappear (works with vue 3.4.15)

### ISSUE THREAD

**Issue by leo91000** [vuetifyjs/vuetify#19192]
### Environment
**Vuetify Version:** 3.5.3
**Last working version:** 3.5.3
**Vue Version:** 3.4.16
**Browsers:** Chrome 121.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Switch tab on the view, you will see the body disappear

### Expected Behavior
The VWindowItem child should not disappear

### Actual Behavior
The VWindowItem child disappear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U82O0zAQfpVROASkOll2gUPproQ4cUBCooJD04OTOK3BsS3b6Y+qPhDPwYsxduJtEgS5xJ4ZfzPzfTObS2JNlX/QOjt0LFkmK1sZrh1Y5joNgsrdY5E4WyRPhQTgrVbGwQUMa+AKjVEtpPgwfV9I76+UtA4cLS08wsZbAIMPVHRsCak2quEiXSBsyQQavkQDx4d456St+ZJWleqkQ/OBGk6lQ49jJ5fCdTGHpKWSkrUshEfYz0oCrfe/f1mu5By9MqzmjlTU1NMMSlIRU2yB2r4Zf3NnzWBNS+zJH1UTOtzIri2Z2W7SUEy6nRCAscjRCl89vYyNvyrkKu/5RTbx4lirBXUscLuq+QEqQa1Fxvek6YSAY/9rBDsBx2hLrKMowI/OOt6cSYWNMzOIgxDfPmJbzyAtPZEjub+7G3Ce43wkVmbhQFpVM+ElpmWRQLkjlRLKoEEb3lJzRmOEs3taqyM5jXEGpNsVELMJAA64DEQVydi9/MnO3psF1ma+YPuPN4g1+MN5HDEqCsuK3MILbZhmsp64e7qnFswQW3WZn5lpev9Fv8EBrVk9qINbQARrceqcIraTuDueyZ2hNUeBCFoNaHI/x8unFeeTcYjf5QIuC5MN1+uI9tzzftMzXG0Yq6iLn4U17s1ErO9coohz4aeFDEGfsJ5+0cI4+BHGSFjvGfSLy3zaW+wo+T9hbvsaob52ZdgIXNW/4EbN9vZxv7P2Bku/SjmKi6cJpcl1kTxkb7LX7xJ/eJs9JNs/swGJLA==)

### Other comments
This is probably an upstream bug due to vue 3.4.16 (it works on 3.4.15)

**Comment by KaelWD** [comment]
#19191
