### ISSUE TITLE
[Feature Request] Disable `v-data-table` sorting through a reimplementation of the `disable-sort` prop

### ISSUE THREAD

**Issue by cojohnson1999** [vuetifyjs/vuetify#19197]
### Problem to solve
In Vuetify 3, `v-data-table` doesn't contain an easy way to prevent sorting on columns based on the value of a prop, much like how the `disable-sort` prop worked in Vuetify 2.

In Vuetify 2, I was able to disable sorting when a data table was loading data by adding the `:disable-sort="loading"` prop to my table.  That allowed me to only allow sorting if we weren't loading in content, which could prevent any race conditions that led to an incorrect ordering of data due to multiple requests for data at once.

I could prevent users from sorting things by exiting early from a sort function if my `loading` flag is true.  However, the issue is that users are still able to spam click the sort icons, and being able to prevent them from doing that by disabling those icons while data is loading would be preferable.

### Proposed solution
Reimplement Vuetify 2's `disable-sort` prop or something similar for `v-data-table` and `v-data-table-server`.  That prop should completely disable the sorting icons in the data table header so that users aren't allowed to spam click the sort buttons while data is loading or other things are happening with a table.

```typescript
<v-data-table
  :loading="loading"
  :items="items"
  :disable-sort="loading"
/>
```

**Comment by websitevirtuoso** [comment]
This is not wrong. each column has own prop to disable sorting.
you can use this props to disable flag,  while data loading

**Comment by cojohnson1999** [comment]
I believe you're talking about the `sortable` prop, right?  While I do think it's helpful, seems like removing `disable-sort` adds a lot of hassle to table usability for something that could be a prop set once directly on the table.  Adding a dynamic `sortable` field to each data table header in the application I'm working on, especially since some of those are common headers defined in a TS file for multiple tables, adds a lot of logic that feels unnecessary to me.

Are there any documented examples of dynamically setting the `sortable` prop on a set of table headers?  I tried that and had some reactivity issues, but I may have been doing something wrong there.
