### ISSUE TITLE
[Bug Report][3.5.3] v-list-group not opening with vuetify v3.5.9 and vue v3.4.16

### ISSUE THREAD

**Issue by roseyda** [vuetifyjs/vuetify#19191]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.16
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Reproduced in vuetify playground (see link)
When switching from 3.4.15 (or lower) to vue 3.4.16, v-list-group is not opening properly on click anymore ("Admin" or "Actions" group stay closed)

### Expected Behavior
The group should open on click

### Actual Behavior
The group stay closed on click

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9VU1vGjEQ/SsjXwCJhVS0PawIUtQeeumlVU7AwbUHYtW7tmwvTYX47xkv2WU/AKFEysn2+M28N/O03uWeeSemD9ZOdgWylM0DZlbzgItVDjDfJYI7CUJz7+9XLHtOeBHMisE/JcMTRWZ3dytWYku0Vj7ALsmMRJ0aizlKAsVNjapxiSIusA7pViZKmDwySJU8mQyJIqigkUI/yuNiPm2kUa1uta0zhYUd10VMevTofIOTcFVnpM9rE1IugtrxYBzB96TDWA+HVkpbajMOVOSPymNzZeKKtW/PdMWFMEUeEqGc0NRQO6Fq9lV387LXeS1u2jCrET47kAeZqaYJbx5Jx7/uHOpOKsJL6i/qvz71TSluuCxpxhAHvKZlBCoHHil7XqR/8T+lqF68UlquvduOhXHpYarhnqlwxbWmP7c4R6aY2NYHeldTfqB7whXydvOujP791t5u3pVwFTy+pHSITykdOoObe+GUPaLw2RoXQOKGFzrA/lhI8sBTGI7gfgHD1xhAfFRTWA7KF2OwHlfx40dANyfVy8FPnvMtZpiHwRgGzecoIyJlNSamCFrl2KgUE39jCCrf+ipNmO0Z5GlXmtgh/+aQmq0qWF34C2S/kMsKtlEXNT1amkhdrzie2pDvqPEEoZ9RPPX1Hkbl5hBNqW1ghzGbTT5PPn1lcfNlMmPrF6+2HfE=)

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/10294

**Comment by amit-feldman** [comment]
Vue 3.4.16 breaks also `v-img`. All images now have inline style `display: none`

**Comment by KaelWD** [comment]
Yes it broke anything using v-show with a transition.

**Comment by KaelWD** [comment]
This should be fixed now in 3.4.19
