### ISSUE TITLE
v-tooltip stays visible even if activator is removed or hidden

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [vuetifyjs/vuetify#1919]
### Steps to reproduce
```
<template lang='pug'>
v-toolbar.grey.darken-1(dark dense)
  v-spacer
  v-tooltip(left)
    v-btn(v-if='editMode' fab @click.stop='editMode=false' slot='activator').indigo
      v-icon add
    span Add User
</template>
```

### Versions

Vue: latest, 
Vuetify: latest-dev, 
OS: Windows 10, 
browsers: Only chrome tested

### What is expected ?

v-tooltip should be be removed/hidden if it's activator control is removed/hidden

### Reproduction Link

![screen](https://user-images.githubusercontent.com/1735005/30934398-665420a0-a3c5-11e7-9f0f-ec70b7fc5554.png)

**Comment by johnleider** [comment]
Since ```v-tooltip``` wraps the activator, you need to apply your if conditional to the tooltip, not the button.
