### ISSUE TITLE
Does Vuetify SSR Webpack  build generating pages?

### ISSUE THREAD

**Issue by roslaneshellanoo** [vuetifyjs/vuetify#192]
Basically SSR should generate pages, like in Nuxt.js or vue-server-renderer.

For example, if i'm creating views/About.vue, and adding About component in the roouter.....SSR should generate about directory .

**Comment by johnleider** [comment]
Vuetify SSR template is just that, a template. I have no intentions of creating functionality that competes with nuxt, I barely have extra time after working on Vuetify.
