### ISSUE TITLE
[Bug Report][3.5.3] v-list-group. has stopped working from vue 3.4.17

### ISSUE THREAD

**Issue by blakejp1** [vuetifyjs/vuetify#19203]
### Environment
**Vuetify Version:** 3.5.3
**Last working version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
this is from you code sample of a v list item with v-list-group.  if you select vue 3.4.17 it works.  moving to 3.4.18 it stops

### Expected Behavior
clicking parent expands child list items

### Actual Behavior
clicking drop down on parent list item just shows up arrow but not child list items show

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9VU1vGjEQ/SsjXwCJhVS0qrQiSFF76KWXVjkBB9ceiFXv2rK9NBXiv2e8ZJf9AIQSKSfb4zfz3szTepd75p2YPlg72RXIUjYPmFnNAy5WOcB8lwjuJAjNvb9fsew54UUwKwb/lAxPFJnd3a1YiS3RWvkAuyQzEnVqLOYoCRQ3NarGJYq4wDqkW5koYfLIIFXyZDIkiqCCRgr9KI+L+bSRRrW61bbOFBZ2XBcx6dGj8w1OwlWdkT6vTUi5CGrHg3EE35MOYz0cWiltqc04UJE/Ko/NlYkr1r490xUXwhR5SIRyQlND7YSq2Vfdzcte57W4acOsRvjsQB5kppomvHkkHf+6c6g7qQgvqb+o//rUN6W44bKkGUMc8JqWEagceKTseZH+xf+UonrxSmm59m47Fsalh6mGe6bCFdea/tziHJliYlsf6F1N+YHuCVfI2827Mvr3W3u7eVfCVfD4ktIhPqV06Axu7oVT9ojCZ2tcAIkbXugA+2MhyQNPYTiC+wUMX2MA8VFNYTkoX4zBelzFjx8B3ZxULwc/ec63mGEeBmMYNJ+jjIiU1ZiYImiVY6NSTPyNIah866s0YbZnkKddaWKH/JtDaraqYHXhL5D9Qi4r2EZd1PRoaSJ1veJ4akO+o8YThH5G8dTXexiVm0M0pbaBHcZsNvk8+fSVxc2XyYytXwCvwR3y)

**Comment by hyperstown** [comment]
Tested with vue 3.4.18 and vuetify 3.5.3 from master branch. Can confirm that v-list-group doesn't expand after clicking on other element. This issue should be reopen.

**Comment by blalan05** [comment]
Its on Vue: https://github.com/vuejs/core/commit/c224897dd4e189a10ec601a97fe08cb638ebee19#diff-c051711fb0e3daf0c252e1d9b3fda8ee413a5525086428d4fd00c1ea30831e40L25

**Comment by KaelWD** [comment]
This is still #19191
