### ISSUE TITLE
[Bug Report][3.5.3] v-menu does not restore focus to activator when programmatically closed

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#19206]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Click the Menu button
1. Type into Menu Field 2
1. Press Enter

### Expected Behavior
Activator button is re-focused like it is when pressing Escape

### Actual Behavior
Nothing is re-focused, resetting tab flow to the start of the document

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVMGO2jAQ/ZVpeqCVNgS6rFQhFnVVUfXSVQ+Veig9OM5ksXBsy54AK8S/d5zAkrTQPSUev3lv/GbsX/skeJk9ODfc1JhMkxlh5bQgnC8NwGyTCuea32YhrSGhDPpjqAkS7igtFeoCtMhR3y+T7x43ytYBvsTwMpnPsi6um12hqYE/tmgyrUOzTGAqtQ2YWtNIoqFUaiXXDCiFDsiMJwomOZUMb4UktRFkPQP34Lx1AQ49cKOZk2HJXJmCcQ2KJaUWIfC6ytM7TvnGdcWqGdvVynr+vDBK4QvYqoJWzDAZjdzuX9ULPkWR1iMYcwlnG6rwxOvsOkV3Ay7xfVgmfcxf5P3NT2t8dh5DGLLXGO2LjYB7ONrdRXerig7Fs587yoHY0lcG5JFD14fjJdfqc1t0OoGK0vGo33yt5p/jaACtEKLyLONQH/Dj2SEoQxa6Bl0A8tyGAItowYXdrgmLnUNJWExbyrwmsgZUAI9paWUdkA+r1ixLMbpdsZuNwco8wSJI4bDr4n+1HiTVQk/h0dIqpvdUbvg/IFHcIJFDqe0W+KTRjkDCE9gyLrqEBaeyVXSlgllm9enOx/72Ln2MtG9C7y7wMkivHAEXU7dPhqqcZf09V1jCAUpvKxjwMzNoO8y8gYCHkceMEe8GX1FrCz+t18Wbwfsz5DiKEdOMI2/NslaNdZLDTXI7nAzHH5P4cze8TX7/ASF0dwI=)

**Comment by mlankamp** [comment]
Downgrade vue to 3.4.15 or 3.4.15

**Comment by ascott18** [comment]
I'm not seeing any difference in behavior with those versions.
