### ISSUE TITLE
[Bug Report][3.5.3] Vue 3.4.16 breaks v-img

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#19200]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.16
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
images are not visible

### Expected Behavior
images are not visible

### Actual Behavior
images are not visible

### Reproduction Link
(https://play.vuetifyjs.com/#eNpVj8FOwzAQRH9l8SUgUbtVoBJRWokbf8CBcLAcJ3Vlx9Z6G0BV/x07oUq57cyuZt98nFlEJV5D4ONJs4rVpF2wkvS+GQDqcSVDmMZJKD+QNIPGP2syjeuvCqD6Mi0ddg0r1+uGLb6MQStaoSTj03azFS+3a+VHjYtMTOnoQBRiJYRqh0xHpvs5Rq68E8bJXkcRJEpr5bdwCRiNtPwY+iV2X4uJ7sqf1P8C2Zn71eKmd5JRoQkEUdNprm9c8EhwBtQdXKBD76BIUEU+z/xDJHCxh12+uC/etLUe3j3a9q54yA/myBTGLo+s5E98s2V5eOYl+/wFJ6J6jg==)

**Comment by KaelWD** [comment]
#19191
