### ISSUE TITLE
[Bug Report][3.5.3] V-Color-Picker slider not working for specific initial values

### ISSUE THREAD

**Issue by darrinsworlds** [vuetifyjs/vuetify#19201]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
If you set the initial value of the model to #ffffff OR #000000 the slider does not respond until after you move the dot to another location on the canvas.

### Expected Behavior
The slider should always work regardless of initial valid value

### Actual Behavior
The slider does not work.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFT8tuwjAQ/JWVe3ArkbgVbQ+RQep3EA5p2BSLJLbWS1oJ8e+1HRAPgfDB3p3Z8c4sdsJTrb6cy4ctikJoxs61FeO87AH0kFXOpTI1te25Mj3SATqAraXMmXqDdIQBhqyzK2xnpUh8KU5UERkfmIWkn285Abn2bXrwTy5Pk3OtLn8/GknwuZOIjEa1OgsQWl+TcQweeTvmMJ2zxLADwgb20JDtQIbsMo4DKAW8Nh5WFj30luHX0iYSYaHncAc3MIviZ/nUpCNfHkgDcUv9ms61Oop8cVcwrtNqzBUSif1ETPP3/O1TxOIjn4rlP4LTktQ=)

### Other comments
This was working previously.

**Comment by KaelWD** [comment]
Broken by https://github.com/vuejs/core/pull/10101
