### ISSUE TITLE
[Bug Report][3.5.3] v-list-group does not expand as expected for vue v3.4.18

### ISSUE THREAD

**Issue by thammons** [vuetifyjs/vuetify#19215]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Edge 121.0.2277.112
**OS:** Windows 11

### Steps to reproduce

See link.
Set vuetify v3.5.3 and vue v3.4.18
Attempt to expand Admin
Attempt to expand Actions

### Expected Behavior
Admin and Actions expand

### Actual Behavior
admin and actions do not expand

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVcGO2jAQ/ZWRL4BEYCtaqYpYpFV76KWXVnsCDq49sFad2LIduhXi3ztOMAQCFLWHlovt8ZuZ9+aBmW+Zd2L8ZO1oUyHL2TRgYTUPOFuUANNNJriTcQsgNPf+ccGK14xXwSxYE/6hZHih8OThoQnVmXWuVj7AJiuMRJ0biyVKAsbNgu1RB1ymqDNYh3QrMyVMGVtJlb2YAhcMggoaKfSpPs6m41Ya1TqvtnamsrDhuopJzx6db/UkXNJJ/Lw2IeciqA0PxhF8SzyM9bA7STml2o4DFfmmyiiuTkyjSZ8LqrgQpipDJpQTmgSdJiSxe97ty47yA7lxy7pW+OJAnmSh2ib88UhuDeV3Yznq3NM5vb6q9KrW2w6taiH9ed10CNGMJS0DUCXwSKBDMP+OPylFdeKJd712bs/sjksHk4y4UOGGw20v73GZDDRR1n/jcyL075wWrpL3G33Dpr//Gtxv9I1wCjbvNR3ig02Hs8FNvXDKNih8tcYFkLjilQ6wbQpJHngO/QE8zqC/jwHExzqHea9+iXrLYYo3Pxi6ObKe9z7zkq+xwDL0htBrP3MFNVJWY2aqoFWJrUox8SuGoMq1T2nCrC8gj7vaxLPmHxyS2FTB6spfafYFuUywlbrK6dnSRA71quZ0CvmIGo8Q+pOLpy7f3aDe7KIpexvYbsgmo7ejN+9Z3LwbTdjyF2hgLsM=)

### Other comments
Looks similar to this issue: https://github.com/vuetifyjs/vuetify/issues/19191

Noticed on my own site after upgrade. Not a nested list-group, but the first item clicked would expand as expected (which ever item is clicked), but subsequent items clicked would not expand.

Vue 3.4.17 works. Downgraded for now.

**Comment by KaelWD** [comment]
This is still #19191
