### ISSUE TITLE
[Bug Report][3.5.3] Clearable prop not working for v-file-input

### ISSUE THREAD

**Issue by chriskulwik** [vuetifyjs/vuetify#19211]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
upload a file, clear icon does not appear, even on hover. 

### Expected Behavior
Should appear on hover.

### Actual Behavior
Does not appear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAtMydVNzOvoLREITknNbEoMSknVUEfpkkfXRdIBGKojT6SZUq1OkrGeiZ6hhZKIIapnrFSLADdfzEr)

### Other comments
This seems to work with vue version 3.4.17 and older.

**Comment by mhio** [comment]
I've noticed this on a VAutocomplete. The clearable icon will occasionally appear on the first select/clear, but not after that. 
I see the issue from vue 3.4.16 and up.  I went back as far as vuetify 3.3.23, same behaviour.  When I switched a vuetify version back to 3.4.15, clearable icon worked as expected

https://play.vuetifyjs.com/#eNqFksFuwyAMhl8FcckmNYmmbjtUabW9xC5ND4Q4LRoBBE6mqeq7z5B2SU89gf/vNwab/ZkHL8tP54pxAL7hFULvtEDY1YaxasyFc2mbAmkNCmXAX6XJMaCVlrIA4SYzNua9bUFva96HY81nsFFUIpCe1iXRokkJX0Iv5VF4JQwSGEwLXlP9dslbMEHhL3G6RWc9ikbD0hCUOWrIY+IsnlQLeQv0HB1mVZ6UW4YahE/H/UsOfFABwWCe6ExiH/IAGiTmnfIBb2hXlfddWnavQcM+pFbye2oV27LMGshqvhMxj/gjO/7YaG/u7TG6n1e6RhpnVS7GTGGQXjlkAXCYpq16R41kZ+ahYxfWeduzjH5IFiGdGpBNxYk/mUHr5xmkuV7RPr1lNd0xLicPkB3IXZVTUSrHLyu+Ll6Ll3ceN2/Fmh/+ALL9zW8=

[vue 3.4.16 bugfixes](https://github.com/vuejs/core/blob/main/CHANGELOG.md#bug-fixes-1)

[vue 3..4.15 -> 3.4.16 changeset](https://github.com/vuejs/core/compare/v3.4.15...v3.4.16)

**Comment by mhio** [comment]
maybe related to issue https://github.com/vuejs/core/pull/10161 / pr https://github.com/vuejs/core/issues/10151 on a quick browse

**Comment by flahol** [comment]
Same problem with v-combobox, clearable icon is hidden

**Comment by KaelWD** [comment]
This is still #19191
