### ISSUE TITLE
 [Bug Report][3.5.3] Using v-if on a VTab causes selection highlighting on the wrong tab

### ISSUE THREAD

**Issue by basuneko** [vuetifyjs/vuetify#19213]
### Environment
**Vuetify Version:** 3.5.3
**Last working version:** 3.5.1
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click tabs 1, 2 and 4 - observe they all get highlighted correctly
2. Click tab 3

### Expected Behavior
Tab 3 gets highlighted

### Actual Behavior
Tab 2 gets incorrectly highlighted instead

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UmFrwjAQ/StHvqigLc4NhqvCGPsHg32Y+xDT04alTUiudSD+911SFZVthZK83HvvLpf72IvgVf7sXNa1KOaiIKydkYTLVQNQdBPpXNomoGxDUjfoj0d8eIrG773CBiSQXIMOIMsSS9hpqqCb6M0YqELYWGPsTjfbxGqwQw9bpACV3laGf8Ly7J1H8zOyBpSRISxWwpnJw0pcZC6MXr4Yrb6S7azIGV9HX78dKjafw1tkwBqVrZGrVKQ7/EXwrKiVZg68MiH5lhZDMyBQlWy2fBdv6+R2dyUvcmsu6+4mrA2grLGeaw+tUhjCdfmJs4xe0yLvwW00NTHqK7tj4h0bpNwwPLd49Jc2Mbkr/0Tvb6NHHE6vz/D6+eNJPx1FfjE1DIPy2hEEpNaB4V5x2XS6sa6d9QR78LiBQ9/EAQ/foG8Z5wgsPV4SFpE23EgTcPTUM9j2TddoWxoOR7BYstWJnnXStMgi8rwcxjCNoiLvC+L04jAWs+w+mz6KuHnIZuLzB6cK7AQ=)

**Comment by mlankamp** [comment]
Have the same problem, workaround is to use v-show.

**Comment by KaelWD** [comment]
Dynamic tabs need to be identified with `value`: https://play.vuetifyjs.com/#eNqFUt1q8zAMfRXhm7bQJvRn8NEvLYyxNxjsYt2F56iNmRMbW0kHo+8+2UlLOzYWCLakc47kg14+RfAqv3cu61oUa1EQ1s5Iwu2uASi6mXQuXVOgbENSN+iHFCfP1fg9V9iABJJvoAPIssQSjpoq6GZ6PwWqEPbWGHvUzSGhGuzQwwEpQKUPleGfsLxo51H8ElkDysgQNjvhzOxuJ646F0ZvH4xW70l2WeQc31YfPxwqFl/DU0TAGypbI0+pSHf4A+FeUSvNGvhkQNItLYZmRKAq2Rz4Ld7WSW1xQy9ya67n7mbMDaCssZ5nD61SGMLt+AkDnTQtMmTOxag7L/JU+AHJhkatyh4ZuNiJC5fvibuA8cX6ye86A2s5sNi5P5CrAbn6jhzicN4WDm/XJWb6bSryqy3jMCivHUFAah0Y9pb70NkhXTvrCT7B4x5OvekjXtZRbzH3CEwdjIBNhI330gSc/O8RLPuka7QtjccT2GxZ6gzP0quYRJ6P0xTmkVTk/UDcXpymYpmtsvk/ES932VK8fgH5t/qm
