### ISSUE TITLE
[Bug Report][3.5.3] [v-text-field]If you combine a clearable with a rule, the clear button will not appear.

### ISSUE THREAD

**Issue by rararax16** [vuetifyjs/vuetify#19216]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
# step1.
Enter values in the label1 entry field.  
Click the clear button (x) on the right to clear the value.  
Remove focus from label1.
If you enter a value in the input field of label1 again, the clear button will appear.

# step2 .
Enter a value in the label2 entry field.
Click the clear button (x) on the right to clear the value.
Remove focus from label2.
If you enter a value in the input field of label2 again, the clear button is not displayed.

### Expected Behavior
Clear button appears after pressing the Clear button and re-entering a value.

### Actual Behavior
The Clear button is not displayed after pressing the Clear button and entering the value again.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUctqwzAQ/JW1LrlENmlaKME29Bjosbc4B9letwZVVqWVKTT99+rhkARKoSftjmZnRtrDF7OmK560zmeHbMdKwnctBWHdKIBy5kLrWMammxSJUaFZIA9mnMN+gD1og9YCvSF0EoWB1hFNCoTqwSBHRWjirXES17FaGJZGKcH7+CmbA+cX8ZkTfhIfRpR9khWtRJCiRVk17Dmcm4bVZXHN9PM38V4uXv2EFtREix2IIcSK0Uf1+nf6MyGl+W/Mu4bBLrzdesTghxsN9r9Fj4oevP3rgKRVlMXVinxrOzNqAovk0qb8oCWfOllABYdZSIdQ1ZBlqTydYHUmZNnqGFSTjldg32u2ze/zzSMLxUO+ZccfNsW2MQ==)

### Other comments
The phenomenon occurs only when the rule is whether the input is required or not.
Otherwise, the clear button appears without any problem.

**Comment by KaelWD** [comment]
?
https://github.com/vuetifyjs/vuetify/assets/16421948/1b48a4b7-bee0-4244-8907-dea46e25b96f

**Comment by KaelWD** [comment]
Ok I can reproduce with those steps, you didn't say to lose focus before clearing. This is #19191
