### ISSUE TITLE
[Bug Report][3.5.3] Infinite loop for v-for inside v-window

### ISSUE THREAD

**Issue by a-n-i-s** [vuetifyjs/vuetify#19224]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.18
**Browsers:** Firefox 120.0
**OS:** Linux x86_64

### Steps to reproduce

   Click tabs 1, 2, 3
   

### Expected Behavior
Windows items are changed

### Actual Behavior
 Sometimes Window items are missing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNp9kcFOwzAMhl/FygmkrdUoSGgUJEAc4AAIkDgQDqVzS1iaVEnaDVV9d5x03XZh0rTG/j87f+yPjlmTx9d1HbUNsjlLHVa1zBxecQWQtlOXfVlop5VeoLzkzIecBXGUYd5mskESZ6T4xCyNg/IPdrLBTg5jyQZL9rHN2Y72VkIt9OqAwQGYCnoXUYU2xAgQCqg9zJf462N/HK+lYCgGuHofuncdCOh7/821slpiJHV5JI4pubmIbO3dtLU65ChM473BUmhzI2oHMlOlN02WwaJr6lAZx/5fVLU2DjowWEAPhdEVcEZr4uzC696Kg7CfS88cJceUT+OhNTViE2pMVCHK6MdqRevtfCFnua5qIdE81U5QF87mEBSvZVLq1UPIFZm0OBmF/Bvz5SA40+zyP3btc5w9G7RoWvK31VxmSnSDfPf6iGs6b0VaWSOJPiC+IE278SYH7KZRC/K9xwW792FUQpVv9m7tUNnxVd6oJ/vAh+ndHnj7zm4SJaGOK/qxfsKS6DSandNIk+gsStjnH0YyB30=)

### Other comments
console log shows infinite loop

**Comment by KaelWD** [comment]
#19191
