### ISSUE TITLE
[Feature Request] Support for Ionicons

### ISSUE THREAD

**Issue by Q300Z** [vuetifyjs/vuetify#19226]
### Problem to solve
Possibility of using Ionicons instead of Material Design icons

### Proposed solution
Add Ionicons support

**Comment by websitevirtuoso** [comment]
It is pretty poor icons, I don't think that somebody will implement it. but PR are welcome

**Comment by KaelWD** [comment]
Icon support is extensible, you can add this yourself if you want to use it: https://vuetifyjs.com/en/features/icon-fonts/
