### ISSUE TITLE
[Bug Report][3.5.2] v-select placeholder doesn't show without clicking in the field

### ISSUE THREAD

**Issue by desousar** [vuetifyjs/vuetify#19227]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
in vuetify 2
```
<v-select
    label="Resource"
    placeholder="Add Options"
    :value="''"
    @input="handleSelect"
    :items="items"
    item-text="label"
    item-value="id"
    outlined="outlined"
  />
```
produces a field with "Resource" at the top, "Add options" in the middle and the list closed. I can then click on the field, select an option and the placeholder disappears.
![Screenshot from 2024-02-14 15-09-29](https://github.com/vuetifyjs/vuetify/assets/44868857/65e982b6-bcb8-4458-872f-2aadf146174b)

In Vuetify 3, I've migrated all the props (modelValue, itemTitle and variant) correctly, but the behavior has changed.
![Screenshot from 2024-02-14 15-21-38](https://github.com/vuetifyjs/vuetify/assets/44868857/d40a39b9-bc48-4b44-885f-66bfec046918)

Is there a way of displaying the placeholder without opening the list?

### Expected Behavior
works like in Vuetify 2

### Actual Behavior
the label is on the top (good) but the placeholder isn't display

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNkrFOwzAQhl/l8OKlTgSUgShUQpXgAUBlaDq4zrW1uNiR7UREiHfHSaiSrkxdrN/fnf67X7rtN/NOpc91nbQNsozlAauaZMBVYQDyVsi6HuTwUdYEqQ26PxThjRCgDWwaDPrQwR1kraQGnwrGecEAjdwTQuMhWCi1j94dxEfhyVKJLjKHijoQYvJshUdCFc4AgOQeKXq+jZxNlayyJdJmNnOqzebEmkfp1IkbUKTV54WHjql9bNnytSR9sM5oyRfA15ask6Xt9UuUuhzwK1p3HDve8Uv6Xnx0ttLmyHeT8SpPz0litn+lu6oEw/YRXF5BT8YjydPZ8bCfBbtPlsntI+vFQ7Jku19ZD7yz)

**Comment by yuwu9145** [comment]
- v2 behaves the same as v3. [v2 demo](https://codepen.io/yuchaosydney/pen/abMPazE?editors=1010)
- Empty string isn't a nullish value, so it overrides placeholder
- You might want to use `persistent-placeholder`

**Comment by desousar** [comment]
mmmh yes ... strange behavior of my application in the previous version. I set my modelValue to null with a ternary operator and added the `persistent-placeholder` prop.
