### ISSUE TITLE
[Feature Request] Prop to control disapearence of parent scroll bar on v-dialog

### ISSUE THREAD

**Issue by Botibas** [vuetifyjs/vuetify#19220]
### Problem to solve
In Vue2 the scroll bar does not disappear when opening a dialog. I upgraded to Vue3 and now the content of my page shifts to the right.

### Proposed solution
I know this issue has already been discussed in #16727, but in my opinion it should exist a prop on v-dialog that controls the behaviour and not padding-inline-end: var(--v-scrollbar-offset)

**Comment by KaelWD** [comment]
Pass your own custom function to `scrollStrategy`. The method used in v2 didn't hide the scrollbar but it was quite buggy and had some pretty bad performance implications.
