### ISSUE TITLE
[Bug Report][3.5.4] I can't give vertical border "data-table headers" 

### ISSUE THREAD

**Issue by hayrandere1** [vuetifyjs/vuetify#19236]
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 121.0.0.0, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
*

### Expected Behavior
headers border is not working

### Actual Behavior
headers border is working

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1vmzAQx7+KhVSllRoCBGjDsklTu4eue7G3U9sXBq4pqoORbbJ2Vb777PCQxOBoQeWVfef787vzGXz3ZnGWTD4Xhb0qwYqsuYBlQbCAT/c5QvPVOMUCjwWOCSgDQtET4BTYx3urGvB7q3ZkMpRLewqcAxOaY1wAGxd4AXJF0LgSgrkKAQIrLDKaj93KVb19svt6aZpPdujklCcsK8RmLbwUlAmUwiMuiUBvlb6KPj1rZggxECXLt3OE6iQidLe1od0F6hHwIiI0uq4SQ6eu4yyQHK6yfHE2Ot9fjEm2yOVqLjATupNLSJVMhB4x4aB5V5iU0jXK8RL0yE2ppC8puaDLccW9v2i9N3trsK8woSwDPjpvX5BsTf26Jq2vWKavcm6lHrFM8kiVK8xirukkyna00i9GBWS5plVU1qPVbhiVUie7Upk0/Z/Ow864OQKH20pts6opo38hR7/pouw2TLNTEXKDmeaTpY9QaDudEFnJCHm+Zq+rEiG/E6KylCTuycGG6qW/SQAlDPAScZynf7LkyZyCN73oS2FmSqGzfCeF6ful8EXubqadpT3s0OvDds2l1+Fa7m5IzX0xgPuqLBL83P1StOBTJ+gDn9p6XWvu8Ph6Xw7g/iY/m8Bi2TTpAfYgPK7ovn48WviprbuaZgkH0P8AQl5RDFh+F4zwF72Fd0zsM+NZ7YbU7M4A9J+UkKygxQHwWW+rO7ZubsAvjeD92N4A7O80h9eELmMzt+/oIHWnG7gvjZ0e2vrW1eR+MAD9mublgW+6H/SW2wtMjRK45hNqaHJvSMlvM3Grfuwm8MDtrbdnPJ2hXtUWXN+JGvvQ0dz+atfVoHLKyXzS3gnV/VC8EkA8oQWkm1uivff/bnKPKZMzSV+8yAsayVIUE5w8f9hqKh0pYK3Prant2+7MUoPA9q2Hf5jE0Dc=)

**Comment by websitevirtuoso** [comment]
DataTableHeader has next type
```
export type DataTableHeader = {
  key?: 'data-table-group' | 'data-table-select' | 'data-table-expand' | (string & {})
  value?: SelectItemKey
  title?: string

  fixed?: boolean
  align?: 'start' | 'end' | 'center'

  width?: number | string
  minWidth?: string
  maxWidth?: string

  headerProps?: Record<string, any>
  cellProps?: HeaderCellProps

  sortable?: boolean
  sort?: DataTableCompareFunction
  sortRaw?: DataTableCompareFunction
  filter?: FilterFunction

  children?: DataTableHeader[]
}
```

I don't see option to set class to them
