### ISSUE TITLE
[Documentation] No props documented for VDatatable API

### ISSUE THREAD

**Issue by DevFromAnotherGalaxy** [vuetifyjs/vuetify#19237]
### Environment

**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open repro link

### Expected Behavior
1. Vuetify users can find the props documented.
2. Component page link is found under the "Component Pages" header and the ads above the header

### Actual Behavior
https://imgur.com/a/foyi0jJ

### Reproduction Link
[https://vuetifyjs.com/en/api/v-data-table/#links](https://vuetifyjs.com/en/api/v-data-table/#links)

**Comment by MajesticPotatoe** [comment]
resolved in 136dd51
