### ISSUE TITLE
[Bug Report][3.5.4] v-model:search binding with VComboBox doesn't react on change value

### ISSUE THREAD

**Issue by booknu** [vuetifyjs/vuetify#19240]
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Type some text in v-combobox.
2. Click 'clear search' button to set `search` value as empty string.

### Expected Behavior
Search text on v-combobox should be cleared when 'clear search' button is clicked.

### Actual Behavior
Search text on v-combobox remained.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkM9OhDAQxl9l0kt3E4EY14MENvoSXsQDdEtsLG1TBrIJ6bs7bcUQT53O/L75831sbPaienOuXBfJatagnJzuUV47A9CsRe9cCtNHWIO9MtL/pgDee71IsCPwWfZefPEa+LblOAS+Y6RFecdiVFLfYC0me5O67VgGO3ZtqiPx1z7NnAY72PuuqrPmv3jHjtIBDbwKrcQ30UITTnB6IWujkKD9wNTmeGHMZAOa6mAMfWfhlUNqg0v2R03OeoQNvBwhwOjtBJw8JQtimfrOEY9ToY3QiaOckZ9zfVyMQGUNpPVOZ9jyTllRrsnmFnhyNMR98gY0m4UH9lReyscXFoPn8sI+fwCRzJoB)

**Comment by yuwu9145** [comment]
search should be only modified by user input so it shouldn't be two-way binding
