### ISSUE TITLE
[Bug Report][3.5.4] The "v-img" component behaves differently in versions 3.5.3 and 3.5.4

### ISSUE THREAD

**Issue by ftrsoft** [vuetifyjs/vuetify#19246]
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Please change Vuetify version to 3.5.3 and you see different image

### Expected Behavior
As 3.5.3

### Actual Behavior
-

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkFFLwzAQx7/KmZcq2Kbb6tqNTfBBFJ9888GKxOYyA0kTkrSIY9/dtHOuQgj5X37cHb/XPfGuoXfWZn2HZE02AbVVLOBt3QJs+pRZOz7H0Jg2MNmi+y2NxYBfIRUSFYc+1Yaj2tZE+11NgE451rPAHHj5jRGo8vjvTNdy5DHG9MeOtNS7cwaIW0bqMwTr15R2jqnMyw/rjJAqcx3VyCWjMfOuCf5darZDTxd5PMt5JXiZ4qJs0tkMWVrlIl4VL8WSibyYF7RcFctV9vR8/1CT89TJ9vS0/slFLPyXMSKjqw2dOIzRN07aAB5Dd1QptTUuwB4cCjiAcEZDEvUnAw4Q+/oAUSBsB+IyeUSlDLwYp/hFcjUMOLaMzcjhmiyyIputyPC4yQry9gPsb4+b)

**Comment by KaelWD** [comment]
That was a bug: a83c336f34c14f8cb768264440ad67abf5413c33
