### ISSUE TITLE
[Bug Report][3.5.5] Image in v-list-item doesn't display correctly

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#19259]
### Environment
**Vuetify Version:** 3.5.5
**Vue Version:** 3.4.19
**Browsers:** Firefox 121.0
**OS:** Ubuntu undefined

### Steps to reproduce
When I put an image instead of a prepend-icon in my v-list-item, the image is growing instead of staying the same size like the prepend icons, and it it's not aligned like the prepend icons.

### Expected Behavior
I expect the image to behave like the prepend icons.

### Actual Behavior
It grows and is not correctly aligned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVc2O0zAQfhUTLiBtkgJbBFUXsRJICIG0F06Ug7GnjcGxLWcSWq367ozdpvntBXqp58cz33wznnx/TCov8nvnsqaGZJWsEUqnOcK7jWFs3aSCexnPUdL8YGs8y1FjeKN2HJU1qfT8D/jWxliTllaCvtskZ0vS2Vaeq2AJf329A19yAwY71Xuhlfh99mV3bMt1Bd2dC5gTQFVhqqiITktBPTgwMuUNR+4pUoHoqlWee26kLesKfFZCzp3KnfVIebDKSzD5m2X2y+36+BhDhRooxmdbGPYFlBwWxhgx0ok9dISvJZeoqbTFFXcB18AnVvETzVBHZHKvuEFKjLDHYcbwU8IaMpZSpaKAxlM/NGxnHE90ZhVa13H6ZNyHiH2dRyjDGvLBhLTKHvOkH7REqiaQFKO155FLuMskmErhgUAJWzouCHvgcpj9Soe7Hvd4KGwJqaCQ48LaFn4ih7Gt4boOtnB5aIsF9Kv8R1hcCFvTgF8B9fXA7uc9WmizASboruG7JPrw8eGBKG6jSnBuk4xn8TKxT8+VjBxi7NO7mliiTZW7qZ4xTxVIkHMmWki9J0rZBRRWy0zY/PVisb9dLKZDHX5ch9cRnqWZdPzCEMGZVkD62RJmZ3067f83B+mOuHAprVWtzGQc22Z9ox1VXRuIsMBGxqvD2uq7HU6KyRLvb/iSK8MqPEQcBahdgSv2crlwexqXcDs4tJ+IEL37RgTx/AEZcEliJbxyJy/Yh61L73/La43s8RRKUkOePW8lmhjA2ptOJo8IdcXQ13DTqcMqGymPp8MxKkhY55f0yfEmeZXdZi/eJuGwzJbJj7+hCf94)

**Comment by aaronthomaswebster** [comment]
This could be an issue with how the avatar is prepended in the v-list-item, I will dig into the code to see what can be done, in the meantime, you can add the update your v-avatar tag to something like this  <v-avatar size="x-small"> to prevent the size from changing. You can see my adjustment here [playground link](https://play.vuetifyjs.com/#eNqlVUuP0zAQ/ismJ5A2SYEtgqqLWAkkhEDaCyfKwdjTxuCXbCe0rPrfGTtN82ov0Es9D89888148u0x846V99YWTQ3ZKlsHUFbSAG83mpB1kzPqeDonSdKDqcNJThpNG7GjQRidc0d/g+tshDS5Mhzk3SY7WbLetnJUREv8G+otOEU16NCr3jEp2K+TL7kjWyo99HfOYFqAwodcYBG9FoM6sKB5ThsaqMNIVQjWr8rSUc2Nqj24QkFJrSitcQHzBF8q0OXrZfHT7ob4CAkiSMAYn0ylyWcQfFwYIchILw7QIb6OXKTGSxNW1EZcI59UxY+gxzokkzpBdcDEAfZhnDH+BDMajYqLnFXQOOyHhO0Fx5bOwgdje06fTPuQsK/LBGVcQzmakE45YB71o5Zw0USSUrTuPHGJdwkH7UU4IChmlKUMsUcux9mvdLjv8YCHyijIGYacFta18CM6TG0NlXW0xctjWypgWOU/wqKMmRoH/AqoLwdyf9mjg3YxwAzdNXznRO8/PDwgxV1UDtZusuksTif2VM/ELWVoXxfx4k8Mt8+9ohJnauaanIXazfWEOCyMA79kwj01eLkIikFlJC+YKV8tFvvbxWI+6/FHZXw08bXq2SCciUM485JQ39Y0JeXSE5g/gv8bj3yHXNgct60UejalXQ+/4ury1+Yk7rWJ8eoMd/p+taNittuHi19RoYkPh4SjArGrwoq8WC7sHnseb0eH7ssRo/efjiievisjLlH0zAnbesE+LmNcC1tay0Ae21AcG/L0WSfhxECone5l9EhQVyS4Gm56ddxwE+WxPRyTAoV1eU6fHW+yl8Vt8fxNFg/LYpl9/wuNygfV)

**Comment by KaelWD** [comment]
The density is only being set if you use `prependAvatar` for some reason: https://github.com/vuetifyjs/vuetify/blob/4cad91f5607adb19ba93f707c642a256ab7ac48c/packages/vuetify/src/components/VList/VListItem.tsx#L254

**Comment by djcaesar9114** [comment]
> This could be an issue with how the avatar is prepended in the v-list-item, I will dig into the code to see what can be done, in the meantime, you can add the update your v-avatar tag to something like this `<v-avatar size="x-small">` to prevent the size from changing. You can see my adjustment here [playground link](https://play.vuetifyjs.com/#eNqlVUuP0zAQ/ismJ5A2SYEtgqqLWAkkhEDaCyfKwdjTxuCXbCe0rPrfGTtN82ov0Es9D89888148u0x846V99YWTQ3ZKlsHUFbSAG83mpB1kzPqeDonSdKDqcNJThpNG7GjQRidc0d/g+tshDS5Mhzk3SY7WbLetnJUREv8G+otOEU16NCr3jEp2K+TL7kjWyo99HfOYFqAwodcYBG9FoM6sKB5ThsaqMNIVQjWr8rSUc2Nqj24QkFJrSitcQHzBF8q0OXrZfHT7ob4CAkiSMAYn0ylyWcQfFwYIchILw7QIb6OXKTGSxNW1EZcI59UxY+gxzokkzpBdcDEAfZhnDH+BDMajYqLnFXQOOyHhO0Fx5bOwgdje06fTPuQsK/LBGVcQzmakE45YB71o5Zw0USSUrTuPHGJdwkH7UU4IChmlKUMsUcux9mvdLjv8YCHyijIGYacFta18CM6TG0NlXW0xctjWypgWOU/wqKMmRoH/AqoLwdyf9mjg3YxwAzdNXznRO8/PDwgxV1UDtZusuksTif2VM/ELWVoXxfx4k8Mt8+9ohJnauaanIXazfWEOCyMA79kwj01eLkIikFlJC+YKV8tFvvbxWI+6/FHZXw08bXq2SCciUM485JQ39Y0JeXSE5g/gv8bj3yHXNgct60UejalXQ+/4ury1+Yk7rWJ8eoMd/p+taNittuHi19RoYkPh4SjArGrwoq8WC7sHnseb0eH7ssRo/efjiievisjLlH0zAnbesE+LmNcC1tay0Ae21AcG/L0WSfhxECone5l9EhQVyS4Gm56ddxwE+WxPRyTAoV1eU6fHW+yl8Vt8fxNFg/LYpl9/wuNygfV)

If I do that the text is not aligned with the other texts, as you can see in your playground.

**Comment by cesar-lizurey** [comment]
Not planned? It's a bug, though, isn't it?
