### ISSUE TITLE
[Bug Report] v-select read only cleareable is active on form read-only

### ISSUE THREAD

**Issue by marco-mastella** [vuetifyjs/vuetify#19252]
### Environment
**Vuetify Version:** 3.5.4
**Last working version:** 3.5.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
create a form, set it to readonly and then check v-select "cleareable"

### Expected Behavior
on readonly cleareable icon is disabled\not visible

### Actual Behavior
on readonly cleareable icon is active and reset the v-select

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplUUFOwzAQ/MriS0BqbVWUA1GK4MYL4ND04CYbMDi2ZW8jVVH+ziYpbaXevDNjz8x624sUK/UWguwOKHJRELbBasKX0gEU3VKHMB2nofGxhYi69s4eT/BEVN6RNg7jGZzghBYrgsqijnpvEbpl62u0m1LMFNYf2pYCcsO+6QwzeMDEuLqYqFuXERsjzVl5mMMW6qoEj6mKJhAkpMPcxbTBR4KeqzQwQBN9Cxn3z0Y5ANskgjZ9wWZU3GfvaK2HTx9tfZc9XCRXHU7S1Q07VznR2x5MncNqAWTIYg7ZKoNhx5cKNafkfGIhrHG/Sf4k7/hL+vHJUlSJF5LDthTfRCHlSlW1Yw2v03RROiTlQqu4Bpnm+Poon+Ra1SbRP7S0ep/k9MyudAMbDQvxKNdy9cyWk17s/gALq608)

**Comment by yuwu9145** [comment]
Duplicate #16289, it's intentional
