### ISSUE TITLE
[Bug Report][3.5.3] v-table cannot loop through data when using a singlepage app

### ISSUE THREAD

**Issue by ferryvandegraaf** [vuetifyjs/vuetify#19254]
### Environment
**Vuetify Version:** 3.5.3
**Vue Version:** 3.4.19
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just run the only HTML file in this example. It gives an error. When i change the <v-table> to <table> everything works fine.

### Expected Behavior
Show a list of routes

### Actual Behavior
Gives an error

### Reproduction Link
[https://github.com/ferryvandegraaf/vue_issue](https://github.com/ferryvandegraaf/vue_issue)

**Comment by blalan05** [comment]
There isn't a `to` in your example... `to` is a feature of vue-router, so you'd need that included...

**Comment by blalan05** [comment]
This isn't directly related to Vuetify and is more of a Vue bug, I was able to get it to work with: 
```
              <template v-for="item in routes" :key="item.id">
                <tr>
                  <td>{{ item.customerName }}</td>
                </tr>
              </template>
```
