### ISSUE TITLE
Navigation drawer is over system bar

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#1926]
### Steps to reproduce
Create system bar beside navigation drawer

### Versions

vuetify: v0.15.7

### What is expected ?

System bar should be above navigation drawer

### What is actually happening ?

System bar is hidden by navigation drawer

### Reproduction Link

https://codepen.io/anon/pen/zEwPrJ?editors=1010

**Comment by johnleider** [comment]
This has been resolved in 0.16
