### ISSUE TITLE
[Bug Report][3.5.5] Clicking already selected item in v-select sets model to null

### ISSUE THREAD

**Issue by argoyle** [vuetifyjs/vuetify#19261]
### Environment
**Vuetify Version:** 3.5.5
**Last working version:** 3.5.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click already selected value

### Expected Behavior
Model to stay the same

### Actual Behavior
Model is set to null

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj80KgzAQhF9l2Uta8IfSeqhooc+hHmxci2A0JNGL+O7dqJTS285k8u1ssaA1Mn5qHc0TYYqZI6X72tGjHACyOay13sZNyHFwdTeQOazNtNSTdDCHamyoz0tU9l0ipB2jLMtC1C8pAtFQKyp+iL+fl4Wj63rg43++d/b1WfxTi6WVptMOLLlpb9cpPRoHCxhqYYXWjAoEXyR8HIC51gEvg9wnTlujs+fuJGbgGuA1ukWXO/ohiRKsPsraWz4=)

**Comment by KaelWD** [comment]
#19242
