### ISSUE TITLE
[Feature Request] Possibility of globally defining the delete button icon in v-text-field

### ISSUE THREAD

**Issue by Co-7** [vuetifyjs/vuetify#19265]
### Problem to solve
Currently, to change the default icon for the clear button in text fields (v-text-field), you can use the clear-icon property. However, I'd like to be able to set this icon globally, to improve visual consistency and ease of management throughout the application.

### Proposed solution
Is it possible to add a global option to set the delete button icon in v-text-field without having to specify this property individually for each occurrence ?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/global-configuration/ or https://vuetifyjs.com/en/features/icon-fonts/#extending-available-aliases
