### ISSUE TITLE
[Bug Report][3.5.2] C:VTabs are not clickable when the number of tabs is changable

### ISSUE THREAD

**Issue by IrinaTitovich** [vuetifyjs/vuetify#19266]
### Environment
**Vuetify Version:** 3.5.2
**Last working version:** 3.5.1
**Vue Version:** 3.4.19
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click action [Change number of tabs] twice
Check the last tab

### Expected Behavior
last tab is opened

### Actual Behavior
task tab  is not opened
the wrong content is displayed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkj1PwzAQhv/K4aWtRNIvGIAkgrE7YiEMieuAhWNb/khBVf8757gtbemAYLPvnnvv3rOf18QaOn7QOu08I7ckc6zVonKsKCVA1iWuqi10SauWTOQlod4YJt1jVS/kkn2UpOd2JFAllEFMG95W5hPTgOEJZOM+fwx3CW+Q5faJW14LVpJz9dhq+s/62VH99mzxsvW44nKpVr9zGdmE454KiIMdhqLmKXlm1ALiVH8snp8pjtZi7Ntc7eTPtcA9FZy+Y0jJhdTeDUeoSt8q+cpA+rZmBlQT3s4GTdRAwWx88Dnwaqnh2oFlzmsQWIpyzm6XxVutjIM1GNbABhqjWhjgHxuEJFXSOjjZMuSBzWL3YjgZ3UUPEd67zxEaOuPZKKYbL6njSsLeybrvv+PTrhKe5RcngcBsgqfoondUSrK5JPP0Kp3ekHC4Tmfk5Qu/XA7w)

**Comment by KaelWD** [comment]
Dynamic tabs need to have `value` set.
