### ISSUE TITLE
[Bug Report][3.5.6] Uncaught (in promise) Maximum recursive updates exceeded in component <VSlideGroup>. 

### ISSUE THREAD

**Issue by rexchungsf** [vuetifyjs/vuetify#19274]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
I don't know why it can work in vuetify playground, but it not work for my private project
1.When VChipGroup children component is a CustomChip which is wrapp by VChip, and then you just use console.log in the setup script, it will throw error :  "Uncaught (in promise) Maximum recursive updates exceeded in component <VSlideGroup>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function."

### Expected Behavior
can support custom chip in chipgroup

### Actual Behavior
not work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUr1u2zAQfpUDFymALbVx2sFVDBQu2mbr5A5RBlY6KUT4B/LkJhD07iFFxXGQIZN0x/uO3w9vR+ZdU363tjgOyLas8o0TlkBy3V/XjHzNwCMNdldrAKGscQQjOOxggs4ZBVkAZt/OTveDJ6P298IuA0X52orXpOnGaE9AvPdwHfflt7ELkP017iFbLcVvoxBulHXmiAo1nQ4OvOEkjD41fhrTpuLuotZVmYQE2qEgVFZywllEddhz186/cxFY/XJmsKAGScJKDIIlNoTtupHc+2gDPtLaOqG4e6rZAg3gM6nHdWdcHOU9CD3rCtZtH/ApNWMR15yq8oVB+Uoh8QuNRLAqz4iz1RzVWys/TOy/oPsf2PEgzectdkLjH2esr27CJ27Z5RcrGBOVyG8LWXJxCi7OqWpC1/EmxLBA3o57ckL3MyIBynLJVpkW5YHLAVPC1T9jJHK9y8kNGNanRxB6hTR9/vlyc/VhcpExjON8N0zTi3vvzJpWbFNcFZefgm2b4kvxld09A3ZK9p8=)

![image](https://github.com/vuetifyjs/vuetify/assets/154295537/8cf18df5-3714-40cf-b8db-74356ded75f2)

**Comment by rexchungsf** [comment]
@KaelWD sorry, I can't reproduction it, but it happen in my project, I'm not sure if it's a bug belonging to Vuetify

**Comment by KaelWD** [comment]
We can't do anything about it if you can't reproduce it outside your project.
