### ISSUE TITLE
[Feature Request] v-calendar add event on click on cells

### ISSUE THREAD

**Issue by roseyda** [vuetifyjs/vuetify#19284]
### Problem to solve
Please add the quivalent of click:date, click:event, ... like in vuetify 2 

### Proposed solution
Add @click events

**Comment by theadell** [comment]
Any update on this? Doing this manually is such a pain. it seems like a basic feature that should be built-in into the v-calendar component

**Comment by ivan006** [comment]
Wait how do you do it manually?

**Comment by ivan006** [comment]
> Any update on this? Doing this manually is such a pain. it seems like a basic feature that should be built-in into the v-calendar component


Wait how do you do it manually?

**Comment by blalan05** [comment]
Duplicate of #19020
