### ISSUE TITLE
[Bug Report][3.5.6] v-autocomplete custom checkbox in item's slot using v-list-item has selection issue

### ISSUE THREAD

**Issue by Thomas-jqt** [vuetifyjs/vuetify#19298]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.3.4
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
You can reproduce the bug by 

1- click on the autocomplete to deploy the menu , 
2- make selection by clicking only on the text of the checkbox label 

the depoyed menu disapear, this is not normal, it should stay open. (the same as when you click on the checkbox or on the area of the list item you want to select)

other bug, 

when you click on the autocomplete and write "Wyo" to select "Wyoming" if you click on the checkbox or the list item area all works well, 

but if you click only on the text of the label it will select "California" and not "Wyoming" as expected

### Expected Behavior
When you click on the checkbox or the text of the label or the list item area, the menu should stay open

When you click on the selection "Wyoming" after writing 'Wyo" to find it easily, it should select "Wyoming" and not "California"

### Actual Behavior
When you click on the text of the checkbox label, the menu disapear,

When you search "Wyo" to find "Wyoming" and click on the checkbox label to select it, it select California and not Wyoming

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUk1PwzAM/Ssml16WTnwJqQIkhAR/AIkD2yFrvS2QxlXjdpum/XecjLJupzrPfvbzq7/2KrTl9KVp8r5DVahHxrpxhvF55gEee22aJoXpUZJnYz22f9CxomMqSVjIOMAAzizQPc3UyzirTvm6c2wFPSGFldlBKF/Zq3F2Sa23JptA9kqOWlNRjN8ktFWC35Ha1bHiA7cmxOBzR7X1q2x+GvUvVcQOy0GvgyNOE2XgHpqWmjCB+IbDTI04aUVnA+uU7PXC+ko4iTFTULBlhwJ0vsKleFNd0KXBldbwRi3w2gYQqdENsFkNXRCxYKRrucbyZ0HbCSw6Buuh3kVR31jKK+sRjBcmGxlSQY9tsOSBliMmRJfJo2fYWF7HBrTxEHgnw7S+1DQiFsO/ihvmaR9ZLBEFrI247LXDJRdw3WwlNT33ZzoyaOz29OyWhtLxuQyXJfD5aaXCdHlnXdRhom7zu/xBxe99fqPmv2KL3AM=)

**Comment by actionjacks** [comment]
Yes, this is clearly a mistake. The component generally has a problem when `slots` are overwritten
