### ISSUE TITLE
[Bug Report][3.5.6] VDatePicker display-value not displaying value

### ISSUE THREAD

**Issue by JessieVela** [vuetifyjs/vuetify#19299]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.21
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create `v-date-picker` and set a value for `display-value`. 
2. Change date and observe `display-value` is not showing.

### Expected Behavior
Expected for `display-value` to override the display of `v-date-picker`.

### Actual Behavior
Displays the date selected. If multiple prop is set to range then the total of dates are show.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj80KwjAQhF9l2YsX2+DvQargc1gPod1KsE2XZFOQ0nc3TRXE287H7OzsbUTvKnVlzodAeMJCqONWC11KC1AMmWZOYxJVb0UbS+6DEqyjO2NTPclBbXzcfmWDbgOdSxTyUiJ0oRXD7Uyctg+KSH1T1X/sTJarhfppE6WvnGEBTxKWUqbj3gmM4KiBCRrXd7CKj6ySXS3+6MRpjbt8n283OA+H/Ij3NzlJUnY=)

### Other comments
In vuetify 2 we were able to use `selected-items-text` to display a different date value.

**Comment by alexkunin** [comment]
You can use `header` slot to override that text. Not sure if this is the best option (and if the following is the best way to use it), but it works:

```vue
<v-date-picker multiple="range">
  <template v-slot:header>
    <div class="v-date-picker-header">
      <div class="v-date-picker-header__content">Custom text</div>
    </div>
  </template>
</v-date-picker>
```

[Playground](https://play.vuetifyjs.com/#eNqNkc1qwzAQhF9l2UsutU1/D8EtlD5GXYKQN62oLC/S2hRC3r1rqylRTrlph29ml9H7AVO0zStzPU+EW2yFBvZG6KULAO1cGeb1uQ52DGJcoPgnrWKvdMXOflOEYfLi2NNzh9GET+rwn1T2lA1zlfwo2y8y/VnWyvRuButNShpRZFeZLhKvcux2y9kURK1vU5JxAKEfaRs1lrsvlLYpyshSseHUjKplNYuSmytCdEw2OhZIJFMu1g08RoEDRNrDEfZR79voZ2wWb6aVw+MN3tcP9d0tLo/H+gk/fgEMRoxl).

But of course, this replaces header unconditionally, i.e. you need to display selected date or range manually if you still want it to be there.

**Comment by JessieVela** [comment]
Thank you that will work for me.
[Playground](https://play.vuetifyjs.com/#eNqNkT9vgzAQxb/KyQsgFejfoRFEqtSlU4dUXZIoQnBJrRpj2YaqQnz3noGgOFMXZD//7t7dY9szo8v0Ramka5GtWGaxVqKwuN5JgKyLC6XG43gpG2kLLlHP0ihWRMeKl9+ooW6F5UpgvmO6kCfcMejiuqlQkOLAz0K0pC711OHsSKQRjV19YVFdOIxMxTsoRWEMtfEc44n2Ov6r4nBwy6C0VNr3YFBgabF6dYMMQ5ZSvT/ClZKlXlKT5BmdYyPVz80pU6xeE7qaUnNlaRjbTqnzWjXaQg9lU6uW5oMBjrqpIaDfFXiExuPVo3smZ2NhSR5yx4USf8BtGkbRJeaFkC+eYRhBvoZ+2keghfp3RpZGi0PSuS+1daymRbSc8cQ2b5v3jdVcnsIoMUpwGwYfQbS93Tt8oKIsnSKg5dlwwx6Sx+T+jrnDU/LM9n95493G)
