### ISSUE TITLE
[feature-request] emit mobile-breakpoint event on v-navigation-drawer when isMobile state changes

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1929]
## What will it allow you to do that you can't do today?
Let parent know when the state of the navigation drawer has changed to be able to react in other ways, like modifying props on other components to suit the change, without having to watch v-resize for the same breakpoint.

## How will it make current work-arounds straightforward?
Simplify watching for a breakpoint

## What potential bugs and edge cases does it help to avoid?
Having parent's mobile breakpoint be different from navigation drawer

**Comment by johnleider** [comment]
Going to need an example of how you would use this.

**Comment by KaelWD** [comment]
How would this be different to simply listening for the `input` event with `enable-resize-watcher`?

**Comment by NothingWeAre** [comment]
@KaelWD 
`Input` represents *active* state, and not *mobile* state.
So for example if i want to display or hide some control in other parts of application depending on whether drawer is in *mobile* state listening to `input` will trigger changes every drawer opened or closed

**Comment by jacekkarczmarczyk** [comment]
And what about watching `$vuetify.breakpoint.sm`?

**Comment by NothingWeAre** [comment]
@jacekkarczmarczyk 
breakpoint for for drawer be different than any `vuetify.breakpoint....`. Not that it should.

**Comment by KaelWD** [comment]
Well you can watch `$vuetify.breakpoint.size` instead and compare that to whatever you have set for the drawer's mobile breakpoint.

**Comment by johnleider** [comment]
As I try to avoid $emit calls when at all possible, I'm leaning towards this should be handled by the developer. Kael is a good solution and I believe that's acceptable.

**Comment by andrewharvey** [comment]
> Well you can watch $vuetify.breakpoint.size instead and compare that to whatever you have set for the drawer's mobile breakpoint.

Just in case anyone else lands here (like me) you need put `$vuetify.breakpoint.size` in quotes in the watch. eg.

```js
watch: {
   '$vuetify.breakpoint.xs': function (value) {
   }
}
```
