### ISSUE TITLE
v-text-field gets weird in a flex container (9.0 dev branch)

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#193]
(found fix, but leaving here incase there is something wrong)

This use to work, just noticed this.  On dev branch

I'm putting a text-field and btn side by side.  The line is messed up, should be at the bottom and I can't click to edit it.

Sorry, I don't know jsfiddle well enough, but should be easy to repro. 

Code:

  <div class="choose-directory-holder">
    <v-text-field label="Source" v-model.trim="sourceDirectory" @keyup.native.enter="enterKeyAction('ignore')" v-tooltip:bottom="tooltip('src')"></v-text-field>
    <v-btn class="green--text" v-tooltip:bottom="{ html: 'Choose a directory' }" icon light @click.native="chooseDirectory('src')">
      <v-icon>folder_open</v-icon>
    </v-btn>
  </div>

.choose-directory-holder {
    display: flex;

    // ADDING THIS FIXES IT
    // THIS WORKED BEFORE WITHOUT THIS
    align-items: center;
}

![image](https://cloud.githubusercontent.com/assets/287137/23822660/1b8a5f9c-0606-11e7-9c88-76d193b83dfe.png)

**Comment by johnleider** [comment]
Can you provide some additional information? How can I produce this? What am I looking for? I need context to be able to help you.
