### ISSUE TITLE
[Feature Request] Handle an event for a click on the badge and the badge only

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#19303]
### Problem to solve
For the moment, when you click on the element "badged", it's the same as if you click on the badge. There is no way to handle a click on the badge and the badge only. Here is a demonstration: https://play.vuetifyjs.com/#eNptkO8KgjAUxV9lXAILchL9gcSkniP7sGzJaOnQJa7o3dtmxZZ9u/fcs3N/u/sHNHUe7YTA7Y1CDImkV8GJpGlWIpS0IRHClrbJq1ISVtL6LVnxSE4FRducs/yyyUB7mopTzKtiHHRdMMng69b+Tz5qw4ZXMravHYONZDrElRAyig4faUrJzioDf9ywO9XjLuSkLujv9D+bUsrAudY0ifrlLnHkncRjHGINSIaRRnB/bXr/sEbp7+4th+cU5niBZ2swxRKv4PACAuCDYA==

### Proposed solution
To create a event "click-badge" which handles the click only on the badge.

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
