### ISSUE TITLE
[Bug Report][3.5.6] VSwitch - flat prop doesn't remove elevation

### ISSUE THREAD

**Issue by AndreyYolkin** [vuetifyjs/vuetify#19307]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add `flat` prop into v-switch as described in https://vuetifyjs.com/en/components/switches/#props-flat

### Expected Behavior
Elevation removed

### Actual Behavior
Elevation presents

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWLC4PLMkOUNBH4tYGtAkuISNProBIBGI+Tb6SPYCucXJRZkFJQrFqSWlBXY2+hAuUEqpVkfJWM9Ez8hQCcQw1TNTigUAA189gw==)

**Comment by KaelWD** [comment]
Is this something you actually need, or is it just because it's documented? It kinda looks like shit in v2: https://v2.vuetifyjs.com/en/components/switches/#flat
