### ISSUE TITLE
[Feature Request] Set default color for range slider

### ISSUE THREAD

**Issue by crystalfp** [vuetifyjs/vuetify#19310]
### Problem to solve
Normal VSlider by default is colored by primary color. Instead VRangeSlider has no default color. To have a look similar to normal slider you have to pass the option `color="primary"`.

### Proposed solution
Make `color="primary"` default.

**Comment by KaelWD** [comment]
> Normal VSlider by default is colored by primary color

No it isn't.

> you have to pass the option

No you don't https://vuetifyjs.com/en/features/global-configuration
