### ISSUE TITLE
[Bug Report][3.5.7] goTo target is not reachable if container not loaded

### ISSUE THREAD

**Issue by IgorIlgiyaev** [vuetifyjs/vuetify#19317]
### Environment
**Vuetify Version:** 3.5.7
**Vue Version:** 3.4.21
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://gigjockeyapp.web.app/en
used the goTo option to scroll to IDs

### Expected Behavior
Should scroll

### Actual Behavior
need to click 3 times to scroll to contact

### Reproduction Link
[https://github.com/Gig-Jockey/gigjockeyapp](https://github.com/Gig-Jockey/gigjockeyapp)

### Other comments
if i scroll manually to bottom and then to top the goTo works

**Comment by IgorIlgiyaev** [comment]
I tried to reproduce this in play but some how when I import the page is blank
[link](https://play.vuetifyjs.com/#eNq9VttOGzEQ/ZXRVuqClPsFoihEJQi19AFooepDtw/OxtkYHHtlexeiKP/esXNhI1JgBVkpD/bMrH3O8WRm/sw9rcLqaRxX0oR6Xa9n6DTmxNB+IAB6aZmTmUyM27k9iePVBreXJB0QBdUnS1oOpTCECaog5ETrk8AbRmVFR4EHY56wEbAR2iaUc1lHmzYzTp2BRRPThXqtlk4Cb3Minjmp97/ZcKj3qrje3FXNXPYqgkjR2Q4IjZwQGu+AMOQJ3QGhmRNC8z0QlHwQOzC0cmJoffxLtHNCaH/8SxzlhHC0h5c4zonh+B0Ydv8rOzkRdF5FYG3rumHXm5rSq2bKTU+HisUGNDXJMpZNY6kMrKrMWMkp+FVbr87k1BUs3x6x/Aw/8Eqe0Xj3mEWVOy0FlrO5PSbwQoxnnKqr2DApdOB1wXmsjyCHh+/OZlRCS2t7OKHh/Q77nX60tsC7VlRTlWIibXyGqIiapfv85pI+4nrjnMpRwjH6BedPqiVPLMZl2CARI4SdiXNoL5wuTES3+vzRUKHXpCxQG7lw8YGHElmp/kf9CW6z0nTfBQJ/qGNW5F1dAV+zPMQ3CSWXyiYTJ+H9Jj+28s2lVzYVMfGzeWRjuT3IJmUd63HG6dxDI7IWgJQoRoTBcONE3PZ+CTkL79EZyVt54H9adhq/BPNRoogVwaVzbSUpJRqF7IKPC3ohrhJzlgxZ6K/ccjzGfOxCuVMrLQ6379oCCjCggo6Z0VvwMdsR/z4oNQqgdE1lzCnckFlBpJpFkCLKYGIW9U6tAij9nhADF0UxahfCaAa/tCtmBTA6KoDRj8+n/htf6BkF6BqJmzkIMqUIZjkp+FivvT6cp1QYnee4Pgy4jPYpaGcfgsJmdol5GRvFC2Kf2fYTmpflXo4qfGt0eWpOzweZ1RhjG9+bZ5c5JJp+RWVgsRpgsKMaNp7h6IJ8sCMbsMLByTrw4HB7qFmUvGalVWnUsS03K+3Ksff3H855/TI=)

**Comment by KaelWD** [comment]
Your images have no height until they're loaded, goto can't account for that.

**Comment by IgorIlgiyaev** [comment]
Thanks, Wouldn't figure it out in a 100 years :-)
Just added 100vh to parallax and it worked.
