### ISSUE TITLE
[Feature Request] Clarification Needed: Default Behavior of `sortable` Prop in v-data-table

### ISSUE THREAD

**Issue by loukacodes** [vuetifyjs/vuetify#19329]
### Problem to solve
Issue with sortable Prop in v-data-table
It's a bit unclear how to use the sortable prop for v-data-table. After a quick test, it seems that the default value of sortable is true, implying that if we don't explicitly add the sortable prop to the column header, it's automatically considered sortable.

This has led to misunderstandings across various codebases I've encountered. People tend to add unnecessary sortable: true and omit the prop when they want a column to be non-sortable. This inconsistency is confusing.

A small comment in the prop documentation explaining its default behavior would be immensely helpful.

### Proposed solution
Include a small comment in the `sortable` prop documentation to explicitly mention the default behavior. For example:

```javascript
// If not specified, the column is sortable by default
sortable: {
  type: Boolean,
  default: true,
},
```

**Comment by y-kashima-iandc** [comment]
I also didn't know the default value of the sortable property, so I looked at headers.ts.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/composables/headers.ts

Currently, the default value of the sortable property is true if the key or sort properties are set, and false if the key or sort properties are not set.
However, there are exceptions when the key property is 'data-table-group', 'data-table-expand',  'data-table-select', which will be false.

I would appreciate it if there was an explanation somewhere about the default value of the sortable property.
