### ISSUE TITLE
[Bug Report][3.5.7] Maximum recursive updates exceeded in VForm

### ISSUE THREAD

**Issue by Cubxx** [vuetifyjs/vuetify#19325]
### Environment
**Vuetify Version:** 3.5.7
**Vue Version:** 3.4.21
**Browsers:** Edge 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
you will see this bug after playground loaded or changing vuetify version

### Expected Behavior
no error

### Actual Behavior
error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj81OwzAQhF9l5UsTicbiT0jFicQDcENcCAeTbKgl/8neRKDSd8eOUVtOXmtn5tt5O7AYBv7kfbPMyHZMxCEoTxCRZg9a2s+2ZxR71vUWQBnvAsEB9nCEKTgDm2Tb/FsNLk0WLcVLDanpO+mycnA2Ehg3ooYWRpyUxef8Ex/OaZQWfsDOWndV/XjWB7QjhmSoamg72FdnTvP6gl8kA8psELxUSAcLQuO1JFyPF8t2csHAsl3Zqdf6/lVL+1Mi7FRM60Iq4KpOOsFPkpLIS2RG8QsWO16x2+auublmebhvHtj7Ly99eK8=)

### Other comments
it will be right when I use `:is="render"` or remove `v-model="model"`. but I can't do this because of some actual question, I just use playground to minimize bug reproduce

**Comment by KaelWD** [comment]
> :is="() => render()"

This is unstable, it will create a new function every time the parent component updates. Use :is="render" instead or cache the setup function outside of the template.

**Comment by Cubxx** [comment]
> > :is="() => render()"
> 
> This is unstable, it will create a new function every time the parent component updates. Use :is="render" instead or cache the setup function outside of the template.

Thanks for the precise answer.
Unfortunately, I want to pass default slot props to the custom render function in order to use VForm instance methods.
This is my component: 

```vue
<script setup lang="ts">
import { type VNodeChild } from 'vue';

const model = defineModel<boolean | null>();
defineProps<{
    display: {
        cols?: number;
        render: (
            ...args: Parameters<NonNullable<FormRef['$slots']['default']>>
        ) => VNodeChild;
    }[][];
}>();
</script>
<template>
    <v-form
        v-model="model"
        #="slotProps"
    >
        <v-container >
            <v-row
                v-for="(configs, index) of display"
                :key="index"
            >
                <v-col
                    v-for="({ cols, render }, index) of configs"
                    :key="index"
                    :cols="cols"
                >
                    <component :is="() => render(slotProps)"></component>
                </v-col>
            </v-row>
        </v-container>
    </v-form>
</template>
```

I try to pass slot props as props for this dynamic component, but it's unrealistic to define props for every `render`.
So the only way is to use render function instead of template?

**Comment by KaelWD** [comment]
`<component :is="render" v-bind="slotProps" />` maybe?

**Comment by Cubxx** [comment]
Thanks for your helpful answer, it works !
