### ISSUE TITLE
[Bug Report][3.5.6] Disabling utility class generates warning

### ISSUE THREAD

**Issue by ikuosaito1989** [vuetifyjs/vuetify#19321]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.19
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Clone git@github.com:ikuosaito1989/nuxt3-template.git
1. bun install
1. bun dev

### Expected Behavior
Disable utility classes and no warnings.

### Actual Behavior
Disabling the utility class will result in the following warning

```sh
Sourcemap for "plugin-vuetify:components/VLayout/VLayout.sass" points to missing source files
...
[Vue Router warn]: No match found for location with path "/_nuxt/%EF%BF%BDplugin-vuetify:components/VBtn/VBtn.sass"
```

### Reproduction Link
[https://github.com/ikuosaito1989/nuxt3-template](https://github.com/ikuosaito1989/nuxt3-template)

### Other comments
Disabling sourcemap is a workaround, but I don't think it is a fundamental solution.
I also want to disable TailwindCSS so that it does not conflict with TailwindCSS
sourcemap
```sh
sourcemap: {
    server: false,
    client: false,
},
```

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-loader/issues/290
