### ISSUE TITLE
[Bug Report][3.5.7] v-date-picker with dayjs crashes when using range selector

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [vuetifyjs/vuetify#19330]
### Environment
**Vuetify Version:** 3.5.7
**Vue Version:** 3.4.21
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
use date-io/dayjs adapter 
```
import { createVuetify } from 'vuetify'
import DayJsAdapter from '@date-io/dayjs'

export const vuetify = createVuetify({
  date: { adapter: DayJsAdapter },
})
```
configure date picker with multiple=`range` 
```
<v-date-picker color="primary" multiple="range"></v-date-picker>
```
try to select a range

### Expected Behavior
when using dayjs as a date adapter for the vuetify instance, expected when choosing the second date in the range, the range would be selected

### Actual Behavior
selecting the second date in the range causes the window to hang which leads to a OOM crash

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUstOIzEQ/BXLl+wjY7MvrRSFVZD2tOcVF8zBjDvEYfxQ2xOIovw7PR6DMiCknGbcruqq6vbNgSds5a6HbNd7sU18wa2LATM7sBZBZ7ge79iRrTE4NqvYmfIV+IXpxP7q/b90ZXTMgBW4MsRubJBG77eJ8MrDU2G0wafMaiN2ORX6dFCesbwBBwtW/hkzsNZ9l/+PxVln7zd5Nh/vpBy+x3IaFInE9GhkMbElapeCPX5Wns9L+KsYBXmh5MsMLnbU48/QbLlryGjW1gOWQilheGTbPg1OLxVPUbfQaAy9N4pXVMGV8NG2DzSPNnQBCR3ROo17xZkjHzZ2QEXU/h6Iu5QT0osiVUlyNET/p46W8sQvhRn30TgdaZHBU6AyPlUvkuKvA1WcEg9nxTc5x7SQsjWeaAY6u0PhIUsfnVwRTGLvs3XQmOBWP8RP8f2bNDbl07qA5Jo7MppozltSqsspOsOsztCqSJL4JX6PCrXUdPouDRLvWkvS2wE2CN4AAp4b6Q1tEuvN3cfRpg/8HOkJgUQvxIX8Sv0VL2+YniUt8jjnox1aaZkFv30GlIA96Q==)

### Other comments
running locally with devtools open, the browser debugger gets triggered instead of crashing, `Paused before potential out-of-memory crash`

![Screenshot 2024-03-04 at 11 14 31](https://github.com/vuetifyjs/vuetify/assets/11082362/d66b9d28-751a-45f4-b427-9a048b0a1eed)

**Comment by agentschmitt** [comment]
the same issue occurs with other dateAdapters e.g. date-fns

Reproduction Link
[date-fns sample](https://play.vuetifyjs.com/#eNqVU9tuGyEQ/RXEixPVu6Q3VbKcypGqfkHVl9IHsoxj0uWigXVqWf73zAKJvE6iJE/AzJk55wzwZ88jdmI7QDLrXXsb+YIbGzwmtmcdgkrwu+TYga3RWzar2Jl0FfiDQD9dvNIqJMCKWmmKNsaLvK5dJLx08D9XdN7FxGojdjklOttLx1jagIUFy3vGNKzV0KdfJTjrzc0mzeYlJ8S4HvJpJKMipoqWBXNwd6Lv7DxjD+fS8Xk2fxVCS1rI+TKBDT3Bv4/NltuGhCZlHGAO5BD6O3Y7xFHppeQxqA4ahX5wWvKKyrjsO5juH42k871HQgc0VuFOcmbJjQk9UBCVuwGqXYpJ0QMjRYmyCKL9saKlONJLZsp9NFYFukjvyFAen6yJKPnjQCUnx+NZ8k1KIS6E6LSjMg292WLrIAkXrFgRTODgkrHQaG9Xn9sv7aePQpuYjuMtRNtck9AISF0kr5eTecZZvYGrIonia/utMNRQ06vrOFI8aS2IbwvYIDgNCPhWSydlE1snuZetHb3x3Zh4nXpSQKQX7YX4QP2fb1o+zvv6lppJ6/w96MXTGznMeXFKryWPmf+9B9XVW2s=)
