### ISSUE TITLE
[Bug Report][3.5.8] Autocomplete v-model:search = ' ' behaves differently between @update:model-value and @keydown.enter

### ISSUE THREAD

**Issue by dturnsch** [vuetifyjs/vuetify#19342]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.3.7
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
define a search variable with v-model:search
define a method to clear the search variable
use @keydown.enter to clear on enter (expected behavior)
use @update:model-value to clear on blur (unexpected behavior)

### Expected Behavior
always clears on enter (and click if @update:model-value is used)

### Actual Behavior
only clears on blur

### Reproduction Link
[https://stackblitz.com/edit/typescript-ideca6?file=index.html](https://stackblitz.com/edit/typescript-ideca6?file=index.html)

**Comment by yuwu9145** [comment]
search shouldn't be two-way binding, it's being exposed as `update:search` event in doc

**Comment by dturnsch** [comment]
how else are we supposed to clear the field without loosing focus?

**Comment by yuwu9145** [comment]
> how else are we supposed to clear the field without loosing focus?

Clear v-model

**Comment by dturnsch** [comment]
But that does not work. It only clears on blur then. 
https://stackblitz.com/edit/typescript-ideca6?file=index.html

**Comment by KaelWD** [comment]
> search shouldn't be two-way binding

false

Search is updated after modelValue, you just have to `await nextTick()` before clearing it.

**Comment by dturnsch** [comment]
> Search is updated after modelValue, you just have to `await nextTick()` before clearing it.
Thank you, this helped

**Comment by yuwu9145** [comment]
I just couldn't come up with a reasonable good use case that has to mutate search externally
