### ISSUE TITLE
[Bug Report][3.5.8] v-autocomplete | after selection and setting items asynchronously, menu re-opens

### ISSUE THREAD

**Issue by emikoshi** [vuetifyjs/vuetify#19346]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Select option from dropdown

### Expected Behavior
Menu should stay closed after items data is updated regardless of how.

### Actual Behavior
Menu will open after items data is updated.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVUktuwjAQvcrIG0CC8GkrVRGgVuqm++4IC5M4jVUnjpJJqEC5eye28wFO0IU1nzczfvPsw5WVRbh8z3OvrgTz2RZFmiuOYh9kANt6EfIiMr6NdIZcZqKAWFWyAwxU6HMfuloFdMpdwNabgI1AA/MKdajpMoFiDAHUi1RHQlFfzVUlyoDd4r4kku1YY+9RxU+m90PEvFL40Kw0j2T2TRXOu63Yb5e33O55nzCDt1DJ8IdGlAI/LYk9uWAItQOoaCwGZUiJQS2KB7ks6nS1srcZq/t2OXoQCsuwkDmaKvGb6wIhsnvC1U6LOHIfpjPY7WHqcmCJ+XCYxFpP5jA58aI1sbxcTFiRPc67aiu7T3hb3WWdXD7EXJXCpZuZc84cw8TvWHQzpvVsSAFgIkvPzYEdYFGNnp4E/JKp0BVOLf1Ro2s1a1Bjv0diDYoSzR5uH8UpPj60DzebFQa8mcN6tVrNukzTbedsKjDRESnSU+oenpj++/2a9pv1H4s1c/bkPXubNWudF++VHf8AlD8vwA==)

### Other comments
I added a button to show that programmatically setting items works fine, even with some delay. Also if the watcher delay is removed the menu stays closed. This affects v-select and probably v-combobox as well.

I tried the `hide-no-data` prop to see if that would help but didn't seem to have any affect, since there are items initially present it's probably not relevant.

**Comment by KaelWD** [comment]
Broken by 12c9e27b64a2dc8e65828879287f40b40fb3f3a0

**Comment by yuwu9145** [comment]
@KaelWD Is the behaviour correct only when the `hide-no-data` is applied? However, when `hide-no-data` isn't used, menu remain closed when items change

**Comment by KaelWD** [comment]
The old logic was open if `!oldVal.length && val.length`
