### ISSUE TITLE
[Bug Report][3.4.1] VCombobox - performance issue since 3.4.1

### ISSUE THREAD

**Issue by b-maslennikov** [vuetifyjs/vuetify#19348]
### Environment
**Vuetify Version:** 3.4.1
**Last working version:** 3.3.23
**Vue Version:** 3.4.21
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows

### Steps to reproduce
1. Open playground link
2. Select any 3.4.1+ Vuetify version
3. Try to find couple of 2 digit numbers one by one (like 25, 47, 94 etc) - you'll see freezes
4. Switch Vuetify to 3.3.23 or any lower version
4. Try to search again - no freezes

### Expected Behavior
should be smooth with out any freezes

### Actual Behavior
huge ui freezes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVUuP0zAQ/iujcGgKSfpYuFTtSiskxAFu3ChaOYnbGhzb2E4fdPPfGdttmrQLXDggcmjsmW9mvnlk+vkYGV2MHpTKtjWNZtHc0kpxYun9UgDMtylRyh/9pZDCEiaoPolOwiqXudyfRQCc5JQvltH7ek2hVUcXwIxhGIMI/+5qnCC1zHLqtF2NprbWIpX5V1rYjquiNlZW6YpxSzUahfs7f73Yt4SR8jlFeGEoR2dMCrQ7+tjQLKMO1ifImbGpU3blGLmliapMk10munw9xNT5DaqXlUdtCa9/Dyk4Ma5eap+O+7oe2V5ySlNFRXkFCC3bMBW6BIb9cKFNRThfRm2gSqd3sMJ2pzvK1hub5pKXV6UJz6djqJwnbqFpbuKNQsBrpqPeqHXRbcG7XXsO3snWwdsuJqC0VOafbOb/1rBeCrgtfpFBbsUtlS3RjAiL9C3d2+tSuqef7a2+kFy6r36t6eE5PcOV5apTslQitZSJVNDdLXL016fTV/G0+84b1Iu6K9RJwobtecCrKTRTFgxuvdAIVimpLRxxEa4St1VVbWkJDay0rGCA63vgDF1JhLHQXYOwgNiPZQLfa6oPie//EBb3cAzMsBFBNUWsP2RWfpA7qt8SQ+NhQIUVDPE5xcu30kdnTBS8LqmJg88hPD3d2LA/2AQD/8IJvSTm/zKQ5bkCcdxN5ETxQWtyyFxl4iNwKtZ2M4PJeDyGJoH4EQvgjeKTFdKawYCVjwN4BSw5CwUK/Rd/JdczmI7bm53BR2I32YpLqWN/1ESUGHoIL+HNEE0nLZijS87EtyuPxoWv1j1pMwzJ4+98FMYBByFqkugue51NJ1E4TKIvPwGyojbW)

### Other comments
I have a huge array of items (around 1000). I'm using combobox component (with custom filter) to render them.
Before 3.4.0 - 3.4.1 it was working without any issues. Since 3.4.0 - 3.4.1 there are huge ui freezes when I'm filtering items.

3.3.23 - no freezes
3.4.0 - small freezes
3.4.1 - huge freezes

**Comment by KaelWD** [comment]
You need `v-bind="props"` for the virtual scrolling to work, otherwise it displays all 1000 items.

**Comment by b-maslennikov** [comment]
wow. that did the trick. thank you so much
