### ISSUE TITLE
[Feature Request] ssr and client mismatch hydration generated input-*

### ISSUE THREAD

**Issue by marekbuxobucek** [vuetifyjs/vuetify#19357]
### Problem to solve
I would  like to have properly defined input-${number}
for ssr and client hydration.

### Proposed solution
I suggest setting up for all input fields if a name is defined his equivalent to an id attribute.

**Comment by tarreislam** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/9095570/42017cf6-937e-4758-9cf6-bf20ea8ede02)
guys please fix the site, this keeps pooping up everytime you scroll
