### ISSUE TITLE
[Bug][3.5.8] Labs Speed Dial

### ISSUE THREAD

**Issue by markedro** [vuetifyjs/vuetify#19355]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I know Speed Dial was just released but I was trying to get a feel for it. I wasn't able to get anything to visibly show up yet with it in my project. That seems consistent with the result on the link locatied in the Speed Dial docs that point to the vue playground example.  (the info above is simply to the vue playground on the vuetify speed dial docs page)

### Expected Behavior
a visible speed dial 

### Actual Behavior
speed dial isn't visible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUstOwzAQ/BXL4khT9YGEolCJP+BOOGycTWWR2pa9DSpV/51NaJoNHOqTPTszHq/3/axTNMvXELLuiDrXBeEhtEC4K51SRbeAEIbtcDDeEViH8QoNYAqI9aK20I6gUmDIdkA+vpQ6QERHpZ6qrTdA1jsuVp7IH5RhBkbJoQgu2SurgRoXEzLxbjk4yZhccaTWUy4znFWIPqR8CvbWn9Wl1MJieE4DlUQU21XW1Wwy18qw/Ur2G5nUQtzj35rlxnHtgXtMtjnNy7tiOdwq37KcfUO/RJEDkVOfeGLLValv7uloDCYONjgyRzpK0VqIrGv8fcVGKL4gOuv290VbIcIYPf/vP0l/ngZonDQG56PWI7+TKFqjL496k22z9Ur3m6fsWX/8AN+O1cM=)

**Comment by YouthGuy** [comment]
In practice, I found that when I moved the v-fab outside, it was functional, but it was invisible in the speed dial. I also found this quite strange.
```
<v-speed-dial activator="parent" location="bottom center" transition="fade-transition">
    <v-btn key="1" icon="$success"></v-btn>
    <v-btn key="2" icon="$info"></v-btn>
</v-speed-dial>
<v-fab size="large" icon="$vuetify" color="#587ea1"></v-fab>
```

**Comment by jo3codes** [comment]
You can get it to work by putting wrapping SpeedDial with Fab

```
<v-fab ...>
  <v-speed-dial activator="parent">
    ...
  </v-speed-dial>
</v-fab>
```

**Comment by m50S79sM6SRNp8Jn** [comment]
> You can get it to work by wrapping SpeedDial with Fab
> 
> ```
> <v-fab ...>
>   <v-speed-dial activator="parent">
>     ...
>   </v-speed-dial>
> </v-fab>
> ```

Confirmed, but the question begs would this be considered a workaround or just how it's supposed to be used?

**Comment by jo3codes** [comment]
Workaround. I think this is how you would expect to use it: https://github.com/vuetifyjs/vuetify/issues/19422
