### ISSUE TITLE
[Bug Report][3.5.8] Poor layout in Chrome browser (win 10)

### ISSUE THREAD

**Issue by RadBe** [vuetifyjs/vuetify#19358]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open link https://vuetifyjs.com/en/components/text-fields/#usage (or any vuetify app with forms)

### Expected Behavior
Good layout

### Actual Behavior
Bad layout

### Reproduction Link
[https://vuetifyjs.com/en/components/text-fields/#usage](https://vuetifyjs.com/en/components/text-fields/#usage)

### Other comments
The paddings and positions in the form layout are not working. I've tried it in Chrome on Windows 7, as well as in Mozilla on Windows 10, and it works fine there. But in Chrome on Windows 10, for some reason, the layout is messed up.

windows 10 chrome:
![windows 10 chrome](https://i.imgur.com/dCSkoTk.png)

windows 10 firefox:
![windows 10 firefox](https://i.imgur.com/Lg8vVum.png)

windows 7 chrome:
![windows 7 chrome](https://i.imgur.com/kR38tPE.png)

**Comment by KaelWD** [comment]
This is either something specific to your setup (extensions probably) or a bug in chrome itself.
