### ISSUE TITLE
[Bug Report][3.5.8] Checkbox hint flickering

### ISSUE THREAD

**Issue by dcrystalj** [vuetifyjs/vuetify#19352]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click multiple times on checkbox label

### Expected Behavior
hint shown only when checkbox is checked

### Actual Behavior
hint is hidden when you click outside
clicking on checkbox label multiple times feels like hint flickering

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj02LwjAQhv/Ku3PpLuy2rB8gUgVvevbgwXqIdbTFpAlJFEH87yatot7eeZh5ZmZ9JWfLbGZMej4xjSn3rIwUnqdFA+TnP2FMG9ui1I0XdcP2gTpYcXnc6guquvGTgpZacZsLghRbloEtIBQqtlzQNM9eM091RB/uSLrVefZ2UihdaWvj4difustqZbT1uMLyHjfsrVZIwjdJbAeC13kod8Akdnwnc5ZSY6Wt3H0lP3FBpwwyuv1SPx2kvX+KYZiOaHMHw0tehA==)

![hint-flicker](https://github.com/vuetifyjs/vuetify/assets/1460727/f3247329-b6af-4c00-8947-edc510f03b27)

**Comment by yuwu9145** [comment]
Hint flickering is resolved as in latest version 3.5.13: [demo](https://play.vuetifyjs.com/#eNpVjz2LwkAQhv/Ke9PkDryEQ66RKNhpbWFhLNY4muB+sbsRQfzv7iaK2s08zDzzzuZK3tXF3Nr83DFNqAysrBSBZ5UGyvOvsLYv+6Y2OohWs3ugATZcn3bmgqbVYVrRyiju64ogxY5lZEsIhYYdVzQri9fOU53QhzuR4XRZvEWKra9dawM8h25I1iprXMAVjg+44eCMQha/ydI4EL0+QPkjpmniO1uwlAZr4+T+K/tJBwZllNFtpDspRzTO//O/MW3vtaBfAQ==)

But when exactly should hint be shown for checkbox? For text-field, it shows when focused. @johnleider @KaelWD

**Comment by johnleider** [comment]
It should be shown on focus.

**Comment by dcrystalj** [comment]
😢
