### ISSUE TITLE
[Feature Request] Expose validated inputs present in forms

### ISSUE THREAD

**Issue by charlesg99** [vuetifyjs/vuetify#19365]
### Problem to solve
Please expose the actual vinput associated with the validation in the v-form "items" array. Atm we only have acces to its id and validation state. In vuetify 2, a form would include all vinput vnodes in its "inputs" array, which was very convenient to track all vinputs present in the form, no matter their hierarchy. This feature was lost in vuetify 3.

### Proposed solution
When the validation [registers](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/validation.ts#L126) to its parent form(s), include a reference to the actual vinput vnode instead of its uid only. So each item in the vform's "items" array would have an additionnal property that would be the actual vinput vnode.

**Comment by KaelWD** [comment]
What is the use case for this? "Please do this" isn't a problem.

**Comment by charlesg99** [comment]
As I said it was convenient in vuetify 2 since it was possible to access all the inputs no matter their nesting levels. In a parent component containing a form, where "form.validate" and such would be called, it made it possible to check custom properties set on each input nested in the form. 

https://github.com/vuetifyjs/vuetify/discussions/19282

This isn't a problem per say, that's why it is a feature request.
