### ISSUE TITLE
custom component - Cannot read property 'getTiles' of undefined

### ISSUE THREAD

**Issue by pate313373** [vuetifyjs/vuetify#19362]
### Discussed in https://github.com/vuetifyjs/vuetify/discussions/14077

<div type='discussions-op-text'>

<sup>Originally posted by **AlexLin-hub** August 22, 2021</sup>
when i use [v-autocomplete] to make custom component, appear this error message. (**Cannot read property 'getTiles' of undefined.**)
This's my component code 
```
// customAutocomplete.vue
<template>
  <v-autocomplete
    v-model="newValue"
    :items="items"
    item-text="text"
    item-value="value"
    :filter="fillter"
    :filled="filled"
    return-object
    @input="$emit('input', $event)"
  />
</template>

<script>
import { VAutocomplete } from "vuetify/lib";
export default {
  extends: VAutocomplete,
  data() {
    return {
      newValue: this.value,
    };
  },
  methods: {
    fillter(item, queryText) {
      return (
        item["text"]
          .toLocaleLowerCase()
          .indexOf(queryText.toLocaleLowerCase()) > -1 ||
        item["value"]
          .toLocaleLowerCase()
          .indexOf(queryText.toLocaleLowerCase()) > -1
      );
    },
  },
}
</script>
```

This is error message, when i change select.
![截圖 2021-08-23 上午10 32 19](https://user-images.githubusercontent.com/62922047/130382939-584e651d-9e4f-4cc6-a2e9-2c7cc927cdfc.png)

![截圖 2021-08-23 上午10 32 38](https://user-images.githubusercontent.com/62922047/130382965-a52d1de1-f304-480e-a768-4bd4daf6377d.png)

</div>

**Comment by KaelWD** [comment]
This was already answered in the discussion.
