### ISSUE TITLE
[Bug Report][3.5.8] VDatePicker multiple range loses data when changing month or year

### ISSUE THREAD

**Issue by PseudoCoder19** [vuetifyjs/vuetify#19366]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Firefox 122.0
**OS:** Windows 10

### Steps to reproduce
Select a day in January, then change month or year (with dropdown) and select the 2nd date of range, the first date will be replaced/removed

### Expected Behavior
It should have all days between 

### Actual Behavior
It starts from first day

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj90KwjAMhV8l5EYFt+EfiFTB57BelBml2Hahy3Yz9u62TkHvki8nJyeXAdtYV2fmsu8ID6iEPDsjdNIBQPWFYX6X76ZughgbKH4QwDDAzYiBcfySJEuECrb1kyL0hW9u5I4as04j+M6JZUeJRBMepPGkqr+d771E/w9mMuVR1U9O1dbRskBL0k1hrecmCgwQ6Q4j3GPjYZYenOmQx8m1lSn3MUvmoXNukV0np+SB4xI35bZcrzAXu3KP1xd9MGJH)

**Comment by alexkunin** [comment]
It seems the problem occurs when year or month picker view is activated: day picker is destroyed, and its local state in `rangeStart`/`rangeStop` is lost.

Adding following snippet right after `rangeStart`/`rangeStop` declaration in [packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx) seems to fix the problem:
```ts
if (props.multiple === 'range') { 
  if (model.value.length > 0) {
    rangeStart.value = model.value[0];
    if (model.value.length > 1) {
      rangeStop.value = model.value[model.value.length - 1];
    }
  }
} 
```
I'll try to prepare a PR.

**Comment by alexkunin** [comment]
And... added a test, because why not.
