### ISSUE TITLE
[Enhancement] Dialog should be scrollable by default

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#1936]
### Steps to reproduce
- Go to https://codepen.io/anon/pen/dVRJKv
- Reduce the browser window height

### Versions

Tested on Vuetify v0.16.0-beta.2

### What is expected ?

By default, the dialog action buttons should always be visible, and only the content should be scrollable, no matter window/browser height.
https://material.io/guidelines/components/dialogs.html#dialogs-behavior
https://codepen.io/webifi/pen/KXqmYN

### What is actually happening ?

Scrollable prop should be true by default. If not, in most use case scenarios the developer needs to use the scrollable dialog prop.

### Reproduction Link

https://codepen.io/anon/pen/dVRJKv

**Comment by Webifi** [comment]
I don't think your codepen is using 0.16.0-beta2, but in 0.16.0-beta* you can add the "scrollable" attribute to your v-dialog to correct this.

**Comment by peluprvi** [comment]
I expected the dialog as scrollable=true by default and its scrollable content height depending on the height of the screen. And I think no matter resolution, display position, etc, the scrollable dialog have to automatic deal with the available screen height.
In other words, even without set the v-card-text height, when using scrollable=true, I expected a scrollbar for the title+content and a fixed dialog actions:
https://codepen.io/anon/pen/LzLyye

**Comment by Webifi** [comment]
Here it is on 0.16.0-beta.2
https://codepen.io/webifi/pen/KXqmYN

**Comment by peluprvi** [comment]
Thanks @Webifi ! I forgot to change the codepen settings (also, I edited the version of my first post). I thought https://dev.vuetifyjs.com/ was already running 0.16.0-beta.2.

Sorry for not be clear from the beginning. Sometimes English gives me a little bit challenge to explain what I'm looking for. The behavior on 0.16.0-beta.2 is absolutely correct!

I also think the most used cases are scrollable dialogs.

**Comment by KaelWD** [comment]
Edit the issue if you want `scrollable` to be the default, otherwise you can just close it.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
