### ISSUE TITLE
[Bug Report][3.5.7] VWindow's model-value cannot mapping to a correct index when the items' order be changed

### ISSUE THREAD

**Issue by bksmate** [vuetifyjs/vuetify#19367]
### Environment
**Vuetify Version:** 3.5.7
**Vue Version:** 3.3.0
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. use v-for in items to create v-window-item
2. change the items' order
3. see dom, vue do re-render correctly
4. change v-model  to check v-window
5. final, we find the v-model mapping to the old index before change

### Expected Behavior
v-model of v-window should work correct after the order of items be changed

### Actual Behavior
v-model of v-window works incorrect after the order of items be changed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFVE1z2jAQ/SsbDzPYDeIjJNMMBaadnnroTO8hB2PLWI0seWTZkDL8964swJbjdKanHDB439vV7r6Hno5eoaLJtzwfVyX1Ft5S0yznoabrjQBYViTM8/pn/RJJoUMmqDqH6mCu5E7RoiAckVBBRTIZU77aeLmi1a8zuvHWy8kbcrvOnolY7jvpP0RMDxsPilTuSaiU3BeIpLKiCqOmHyZKWRbXQq1ShOEwWC+RCnN8ORgBGwTABJjK2BEsXugrQnKA3TUFsETMqvY7QKFfOUWqGwXYs1inC5hPp/nhSxdMKdul+j3UbID8m6LpQZOQs51YQESFpqpDcRtyZgA4HkEO4HRyJpvgaO1loSatbTV6XONNCDNxmyzBNdzc1Csccyp2OjVK8LAwysQk4fQAv8tCs+SVFHkYUdRNliJ2dowibbVod8ZQTCyQxczqTDhNNNEyJ1vJMbnNrULFQqGRTjmt0K0dvFYF0ftHN2633QN8jTiLXtqe+56GYkd9Mgs6O/6J3gMtIUHvmS05Y7QnxNmdAfstdDbQ/eMb+S/W6IEc6/TgpjdSsD90AbPx3QPNOngkuVQLULutj6v0CamITmmGNbEk2i3VQeCktLt2XIYe8687g1uYBfgYwgQ/t/ZvdvaI48PlxCzn/+ygTFsf7od37bANo5f37dD+2xmWe5GaiL1nl5PW/YuvRaRYrqGgurTXMMtyqTQcQdFkhDpmeYnTwgkSJTMY4iU+NIlGYlFoqwCsDNt/Gk6HIxjOzOPOPObD56BLtjrahOkb9HKZI+FytO8HsFrD0c6msFElwG88Ma5CXlLrjE8wm04DNIc1Ro1crhBMP/V3YzePR8ZM0UgzKVoHcqohKpW69N05tyEJur9wGv5tU7NhcpYxfS7lNgkEZpbHEvCvFZeAQ7Xq1wV6eGuLONxpc26xD3P32Kdrp8+W1o91ki7Ve3KuEKaY4xpGW6vVtcFaFeNK60N0oHcaefPxfDzzzPfD+LP3/BcepnPg)

### Other comments
Thank you very much for your contributions. I really like this Vuetify, it does help.
If there are any updates, please feel free to send an email to my inbox at longxd233@gmail.com.
I would greatly appreciate it.

**Comment by bksmate** [comment]
Now I get one manual solution:
I use ref to get the instance of v-window, and then I change the group.items like:
`let items = win.value.group.items.value;`
`let swap = prevs[currIndex];`
`prevs[currIndex] = prevs[newIndex];`
`prevs[newIndex] = swap;`
`swap = items[currIndex];`
`items[currIndex] = items[newIndex];`
`items[currIndex].value = currIndex;`
`items[newIndex] = swap;`
`items[newIndex].value = newIndex;`
It is indeed useful, but a bit funny XD.
I want to confirm whether it is a feature or a bug.

**Comment by KaelWD** [comment]
You have to set `value` on the items if they're dynamic.
