### ISSUE TITLE
[Bug Report][3.5.8] v-menu doesnt close when item is selected with arrows and enter

### ISSUE THREAD

**Issue by Ayax0** [vuetifyjs/vuetify#19361]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Opera 107.0.0.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Click on "Open Menu"
2. Press Arrow Down
3. Press Enter

### Expected Behavior
Menu should be closed

### Actual Behavior
Menu stays open

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkE0OgjAQha8yGbcKATUxBokewHgAcYG1i0YoE1rYEO7utPwYEhdumnkz37xO3r1DU4vwQhS0jcQjJlaWVORWppkGSNpNTuRLL0qpm1GxnlBY5cKqNrdVfcqwA6orMtBnOKN++Wk18Kv0iynPMHEjqeHKtknoia97uLhk9CiUsUtX19koZuEsCiXe7gL3deQM5+F/O/Hvnak75cByDsKJIaLFwSyNqBVZMNI2lCbhIHmE/Rq3wS6II3TFPjjg4wOgMXlR)

**Comment by rajithaeyee** [comment]
@Ayax0 I added a fix for this [here](https://github.com/vuetifyjs/vuetify/pull/19368). Hopefully you can use this once the PR got approved!

**Comment by rajithaeyee** [comment]
@Ayax0 I added the fix for this. Hopefully someone would accept :)
