### ISSUE TITLE
[Bug Report][3.5.8] When interact with menu the page beside should not be scrolled 

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#19373]
### Environment
**Vuetify Version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to hover on the menu dropdown and scroll the mouse wheel key

### Expected Behavior
The behind page should not scroll. Refer mui menu: https://mui.com/material-ui/react-menu/

### Actual Behavior
Behind the page get scrolled

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtWE1v2zAM/SucL24B28G+gC1wOwwbduqA3ZseFJtphciSKtFeCsP/fZQyp0533aWATpbIx8f3KJ94O2beNauv1lZDj9k6qwk7qwTh9UYD1K0coFHC+6tNRnigskFN6DZZTDNgKD0qbAiGsjMtKsYp0wiSRm8yWEumC7VzzHNQiW3E3Zxw1/Vq5nnm7VD3sJ4Lz3j/ghg2q+X2Xhlai4bkIMg4xo9gnbEepkVBZN6ShsaoCLJOdsI9saxWuD3TbKVuY5xLuRC+86E1vzUEjVz53Hu1GNUpOJRK+tnFIlKGSTD9Lna9CLcCuBUeLvkDcU5hYHt84nxMnMk+JypJksLrcYyFVbzBNAWJLzELJcvswsaZ5HANkz95qu0JemMce5DW9x20YX7gJYHokHic2vPrIfUORCut9LKR+h5QSargR3/PQN9rmqn4T2F470EbT475LDpvuYZf2Ic/hFu9gV/LoIuPjyCVMrATjWTVM501zpkCNPpGchd47CXgARwG6qjtsResrQgZAQ8ixLV8kCoEPCBfGYFf5iHMppP75D65T+6T++Q+uU/uk/vkPrlP7pP75D65T+5fs/t6xds9Pr1YZNW+cdKyIbZ7BMqOFRCM3HEHE+yc6SDndWF+3BEFBQTzdg6uAuwiR93ml0tAXHFx9vaoYoS4n1pD/k3JZg8/MYep+N85eDdn7/6VGtXkZGxeQL41RKYLJ0/CUTgEC/w5rjxzJqhXx9nwVLKpyN5XH6q3n7Nw+Fh9yu7+AFaIXXo=)

https://github.com/vuetifyjs/vuetify/assets/80033712/a3980331-e9c9-47db-8313-a8fc2df0e789

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/overlays/#scroll-strategies

**Comment by alokVishu** [comment]
Hello @KaelWD,

Thanks for suggesting scroll strategies, but there seems to be an issue with menu components. Please refer to the video:

https://github.com/vuetifyjs/vuetify/assets/80033712/98951e92-6f92-4e2d-8143-44ebe2d7ac7c

It would be great if there is a resolution or workaround available for this issue.

https://play.vuetifyjs.com/#eNrtWclu2zAQ/ZWBekgCWDK6Aa3hBAhybYEWPcY50CJtTEOJNBfBhqF/75DyItku0kN7SXkSZ3vDN0/UgXrcZtaU43uti8aLbJJNnai0ZE7czWqAKccGSsmsvZ1lPF9IsYaf3jpcbHKrWSlyZpSv+SyL6VTQ5JWoPdjSKClz6wxBLTdUPZeqfD7kUea+ETS5lcpNWOmwYU4ZSt6CNkpbaHsFEXzuaiiVjEnaYMXMZpYRwhxrHl1URTVwvweDgA3TcSw9Nh8PaO7AJVo3bBc8OVIutVjEptfBGgG1E+sbekCwqSVMnkWgGQPBbJj04ujo4Q6Rc4dOirvtNiIV0YK2DTs+zeltrR/tsRpwCGYQg8yDOBfndwD4xoyoHRyU2Bcede2LpGM2cX1Z7EvjHY6h74cXpz3MHo7+JHaiQz862MxfUOV3upwpM9Bmb3bv50ApDO90SMuPkmQX9IMfOJdYL4/yXEI8E/DNGfQfHNvXfEyCQV+8bqV38S/KEDHU1lfAw+hHYJEOSSUcSVFbUTrhvAHGUaPFMuggJLoCHrzUrKvsoOaS1Rwdou2QCLdUVaU4ghUrjyNgEunJw+evQR4O48orDpLNlUFlWRX7dmgVW9bkWHkmYMFKJE6w8EsGWhmjRlD7imKhhSEPBWknZHopg9NrpK2QzEWH9t2ruJqOO+KJf+Kf+Cf+iX/in/gn/ol/4p/4J/6Jf+Kf+L92/mkCiX/in/gn/v8r/8EvMjLp1wDq7s5crAnNARcL5qWDbVfOmWMTuL6B2zu43vmgu/efwOPxUn4L8Zp+AlcPEstn+CquoB39yzi862c87VbtTVy0geqBXNaOsvfFh+Lt5ywsPhafsqdfZQMWjw==
