### ISSUE TITLE
[Bug Report][3.5.8] Override theme color reverts to default in component with scoped scss styles

### ISSUE THREAD

**Issue by Lnola** [vuetifyjs/vuetify#19384]
### Environment
**Vuetify Version:** 3.5.8
**Last working version:** 3.5.3
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Clone the github reproduction link or to do it from scratch:

0. Make sure you have SCSS configured in your project
1. Add a color value to the theme - `primary` will work correctly, but `grey-lighten-4` will not. Make sure the value is something noticeably different from the default `grey-lighten-4` value of `#f5f5f5`
2. Create a new single file component and make sure it has a scoped style with lang scss defined. You don't have to use the class you define, you just need to add it to your SFC.
3. Use a vuetify component you can assign a color to, like `v-sheet` and add it to the SFC. Assign it the color you defined before.

[GitHub repo](https://github.com/Lnola/vuetify-scoped-scss-issue)

### Expected Behavior
The `v-sheet` should be the color you defined in your vuetify theme

### Actual Behavior
The `v-sheet` is the vuetify default color for `grey-lighten-4` which is `#f5f5f5`

### Reproduction Link
[https://codesandbox.io/p/github/Lnola/vuetify-scoped-scss-issue/main?file=/src/App.vue](https://codesandbox.io/p/github/Lnola/vuetify-scoped-scss-issue/main?file=/src/App.vue)

**Comment by KaelWD** [comment]
Remove global.scss and preprocessorOptions.scss.additionalData, it's duplicating all of vuetify's styles for every component.

**Comment by Lnola** [comment]
> Remove global.scss and preprocessorOptions.scss.additionalData, it's duplicating all of vuetify's styles for every component.

How do you use `$display-breakpoints` SCSS variables without that?
