### ISSUE TITLE
[Bug Report][3.5.6] VComboBox readonly prevent combobox open

### ISSUE THREAD

**Issue by AndreasPantle** [vuetifyjs/vuetify#19388]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.3.3
**Browsers:** Chrome 122.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
If you have a VComboBox which should not be editable (readonly) it prevents to open the selection.

### Expected Behavior
readonly should not prevent the opening of the selection menu.

### Actual Behavior
It blocks...

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNqNVG1r2zAQ/itCDNpC6rztk0lLt9FB92Eb69iXOAzHviZKZclI58wl+L/vLL/JtISCwdJzz52ee3zy+sStSaaf8jw4FsBDvkLIchkj3EaKsdXxOs5zt3SbRCuMhQLTQi2YbfVWlx3EWCioir2JePbiVhH3YplOQV4fY1kAMSxISBDSB+L5tLsiT0lFw/7Tkhvsr8MuP8ARFF75SQbiVCv50iGDyukg05e+RcXuEimSZycFaxVfhbEY8dtHQDarE4k0brfz4HRiuBc28HtgVdUcNjbqNVYjjberqec5bW1iRI6OBGWuDbIUnuJCIjs1xciE+PKq29VtY2HUsGes9T1k6wFjjOQKlBCyC6d0fjFh7jOEbMaqyRnmYmDOzzOXA3MxYm68te9XyFQhZR+smkWXmdAXJaLf7GvHbxqs7Xk934xrZIB7nZIXfYnRGNVJenvwTnj7jJbXC+0l+2PjC32H1FkrdSjXvMmF1bQfAz7haGl4nsQuOFit6Ja6QyJOI50LCeZHjkIrumZ9kxGPpdT/vjkMTQFtfcrZQ/L8Bn6wZY1F/KcBC+YIEe9jGJsd0J2ow/eP36GkdR8kGwtJ7DPBX2C1LGqNDe1zoVKS7fGc2oesnnahdr/tfYmgbNdULdT54vgRp1/VlzOtD3KXwbL1kx5eTfgy+Bgs5uQoRYIF3/wHkU+L6w==)

**Comment by KaelWD** [comment]
This is not a bug.

**Comment by AndreasPantle** [comment]
> This is not a bug.

What is the possible way to block the user input into the combo box with the option to select an item?

**Comment by AndreasPantle** [comment]
> This is not a bug.

@KaelWD: Please consider to update the documentaiton "Puts input in readonly state." is something different than blocking the menu opening...
