### ISSUE TITLE
[Bug Report][3.5.9] the open-all property of component v-treeview does not seem to work properly

### ISSUE THREAD

**Issue by hoekstrajan** [vuetifyjs/vuetify#19389]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
There is not much to reproduce. When the property open-all is added to the VTreeView component all the nodes should be opened

### Expected Behavior
Alle nodes opened

### Actual Behavior
No nodes are opened

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUE1rg0AQ/SvDXmwhuvTrUElKSrGQWylpSok5GJ2QLbouuxtDEf97x1VLai4BYZ03M++9eeuaGZ3yZ6WC6oAsZFOLhcoTi0+xBJhWfqKU+3VFWkqbCIm6hwBWH9Fy8foFy/coWi2iz3BoTFdLjVgJPEIoiNTMYubemEGpUPpJngMfqPmYu0U66Sk/sUSlSbVQFgzaQ+dMFKrUFmrQuIMGdroswKNrvHYcgHiNBScNs3bmat2J1oNVK2yOIXhviUZpvcmAp3uRZwSFsK7/hl5a0INmQoJjbNOvNu7dXLfmO7tklE1Y59QvEhV8m1JS3M4DBeMaFE04uIoZXdDWMdtbq0zIeZpJWsswF5UOJFouVcHnNMb1QVpRoJ+VxfwuuA9ub3gmjD3FAzSFv9Xl0aAmlpj1Vp2OFbufC7T6SZJ4CB47hR7y82RrWokzak56FWqfYsxQo770pNHav7NGvbPTWvkmlvSxZsK6TUrf2WabX94U+Dc=)

**Comment by MajesticPotatoe** [comment]
you data is missing a unique identifier (default `item-value` is set to `value` in the object
[Playground](https://play.vuetifyjs.com/#eNqNUV1Lw0AQ/CvLvUShyeHXg6GKIhX6JlIr0vQhTbb0JLkcd9sUKf3vbi5JqS1IIZC72dmZnb3ZVjibyWdjonqNIhZDwtIUKeFjogGGdZga44/+klWaUqXRdhDA9GM0Gb9+weR9NJqOR59xX2A2WcRa4QZixaruIRH+nwioDOowLQqQvbY8Fm+Q1nsoD2biq8usMgQOad2OpkpTWYItWFzCDpa2KiHgOEFDB2BdR+Ct4aHhXMxa020/a50Wa4zhatADpKhgIHhLLWoK9ni2UkXOUAydhJfp+68H+8aXhhjAbt95QLv5hzbvTi0yv2zSt3k5qRiINmpYpib6dpXmB/MheLO+wLuN+1iJ4BU090SsiIyLpcxyzW05Fqq2kUaS2pTyiWnSrjWpEsO8Kp9uotvo+krmytEhHqErw4WtNg4tqySiG9X7kFr+nOHVMdniLrpvHTooLNKFayxOpCX71WhDXnuOFu25kY7a/sQ6qp1Ea+x3ieZP7Aai7eTt+7HF/BctKQgm)
https://vuetifyjs.com/en/components/treeview/#open-all

**Comment by fengdy** [comment]
not work  use remote server data
