### ISSUE TITLE
[Documentation] Autofocus Search Textfield on opening Search Dialog

### ISSUE THREAD

**Issue by fabianbernhart** [vuetifyjs/vuetify#19385]
### Problem to solve
The Search Field is not automatically auto focused on open with click but with Ctrl + K it does autofocus. Maybe a Bug

### Proposed solution
```vue
<text-field
   :autofocus="true"
/>
```

**Comment by fabianbernhart** [comment]
I want to fix this issue.

**Comment by MajesticPotatoe** [comment]
duplicate #18456
