### ISSUE TITLE
[Bug Report][3.5.9] VTreeview: Load an children afects the load state of all other children

### ISSUE THREAD

**Issue by ricardo17coelho** [vuetifyjs/vuetify#19390]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See the playground

### Expected Behavior
When the fn "load-children" is called, only the affected node, should have the "loading" state

### Actual Behavior
When the fn "load-children" is called all other nodes have the "loading" state

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptU02P0zAQ/StDhGiKWncr6GGj7SIkOII4wGm70hrHaQyJHdmTlqrKf2fsfBdyif3efL7xPF0jZ8XmY1WxUy2jJHpAWVYFR/l40AAPp7XgNg3n4bZGhYUEUXDn9ofo53GtdKqOBlD+wfU5VyjbY747RJ0rwA8nLXxSVgo09tIF3Ewj3mahEIM3gWilPCl57iGAhDKVvoTwP0QTpjA8XYtcFamVmiwyiSL3JczMhCmMJfbMrVb6OKVSqZ3CC5HClBUXOCV9vrZm4jUv5T/kiRe1J1U6UkMz1E6vMpzWrjCYVFZWUqfkcQ0BoJlI1wmghNFkrzKyeuWNWN8g2UKZqjUXwtQag67eeppxMxtsr34vaq/9MJBe/B6hyywEXZ2wqkJwEusq2KqyMhbhSrqWVY0yXYGV2QrOnMSHBjJrSljQO1t4fy+/dggVr52EPZQO9o+g5Rm+kZ1yMrbSmeJE3KNP8l2V0tTYoytyWC6ngQpVKqRAlDPeEdPj7reqOvhuAqNBXkzwkQnPqWOeWmGuvWh+2gkswlNarHq0H0QCT88d2IT/cxeYu4sWkNVaoKIpjs8x9smWfXx+5tRCUCTe7u7acoEKwdp2XvFLjli5ZLNJ67K8/HJGM9J7Qy7WfQga7F9fw5+FV9i88QLst3cvXTQAhrnUXkgvLf2YjxJ7Nae8B73B0Hurjykk8wsT+MEFWvnblKRdqCtAo4WvY27gkZEPE5kbBGi0CFjolGXGfuYkh7opsV3AYTVYVbs8nvHUH2NqmF3nlCbwhWPOssIYG4ej5To1ZbyEt7ClWdx4tC9BsUxZh1/pcsP/5020XzMRbTyPJyb8vsTSWt/aTHLC2ik1fh3bBaTVi5pV9I69Z9v7yB927D56/gstWs28)

**Comment by b-maslennikov** [comment]
[correct playground example](https://play.vuetifyjs.com/#eNqNU02P0zAQ/StDhGiKWncL9EC0XYQERxAHOG1XWuM4G0NiR/akpary3xk732UP5BL7vfl8M76/RM6KzceqYsdaRkl0i7KsCo7y7qABbo9rwW0azsNtjQoLCaLgzu0P0c+ntdKpejKA8g+uT7lC2R7z3SHqXAF+OGnhk7JSoLHnLuBmGvE6C4UYvAlEK+VRyVMPASSUqfQlhP8hmjCF4ela5KpIrdRkkUkUuS9hZiZMYSyxJ2610k9TKpXaKTwTKUxZcYFT0udrayZe81L+Qx55UXtSpSM1NEPt9CrDce0Kg0llZSV1Sh6XEACaiXSdAEoYTfYqI6sX3oj1DZItlKlacyFMrTHo6q2nGTezwfbq96L22g8D6cXvEbrMQtDVCasqBCexroKtKitjES6ka1nVKNMVWJmt4MRJfGggs6aEBe3Zwvt7+bVDqHjtJOyhdLC/Ay1P8I3slJOxlc4UR+LufJLvqpSmxh5dkcNyOQ1UqFIhBaKc8Y6YHne/VdXBNxMYDfJigo9MWKeOuW+FufSi+WknsAirtFj1aD+IBO4fOrDp/s96vvkP14euJu7OWkBWa4GKFmDc5NjXuewT8BOn7oOY8XZ303YK1APWtvOKH3PEyiWbTVqX5fmXM5rRqDbkYt2HIN/+5SX8WVjg5pXXbr+9eeyiATDMpfYz8FOhH/NRYj+IKe9BbzA030prCsn8Wwv84ALt5NqUJHuoK0Cjha9jbuCRkQ/DnBsEaLQIWOiUZcZ+5iSHuiqxfbvDq2JV7fJ4xlN/jKlhdp1TmsAXjjnLCmNsHI6W69SU8RJew5ZmceXRroJimbIOv9Llin9mJ9qvmYg2nscTE/6pxdJa39pMcsLaKTX+Jbdvl15t1Kyit+wd276P/GHH3kcPfwHNN93I)

**Comment by ricardo17coelho** [comment]
@b-maslennikov on the playground on the description is also reproducable ( after the 2n level ).
But thx for your example 👍

**Comment by HendrikHuebner** [comment]
I'm having the same issue: [here](https://play.vuetifyjs.com/#eNpdUMFuwjAM/RWrl7YSa9kVARKbdkU7oF0ohygxI1KbRIkLQ6j/PqddC+zixHnP8Xtvf0uCl+XGueLcYrJIlkF67QgCUuvWlQHQjbOe4AYej9DB0dsGUianlYmwtCYQaMImwCpysv0NSFONC0i9tZTOQJ50rTyaBewP0B3yx0klSPDgPt0wMX2L5T09DAwRrkbCsTWStDVQW6G2+ENbqzBkhmsOt8gD3kutN2DwAp8sUAfMPKzW0cZON2hbyvwMXufzeZ4XdEKTZXnE/8ahl1Ecrf8Q8pSpJwggripGE4VrwymbPKr/9tjdMDXehrOrzLIcwuVYueHEXC0I+5CX5xcpvOrv3H3tPOJZ42X8a9EHvKqS/qyS6T1m8jIKYPwpoztP2tp6hi/CG22+74BCEzRdGZK2cULSHSIvIsbJDy+juHJSN0gvJ+3L8sEUt4GuNUKQ1qFas/vYMpJ0M9PWdV8Ov5CYz9U=)

**Comment by pangjianxin** [comment]
same issue
