### ISSUE TITLE
[Bug Report][3.5.9] Datepicker range problem with daylight saving time

### ISSUE THREAD

**Issue by yvangrdv** [vuetifyjs/vuetify#19395]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.19
**Browsers:** Firefox 123.0
**OS:** Mac OS 10.15

### Steps to reproduce
1 - Create Vuetify a Datepicker with "multiple" prop to "range".
2 - Select a start date before 31st March (daylight saving time start for europe)
3 - Select an end date after 31st March
Exemple : Range from 14-03-2024 to 10-04-2024

### Expected Behavior
The range must include all dates between start date and end date

### Actual Behavior
The date before the end date is not in the range.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVTksOgjAQvUozaykYcYGpJp7DuiBl1CqUpkwhxnh3x6oJ7t68eb/DA4Zg8r33cowIG1CEnW9rwp12QqgxM72j2joMiUhU6CdxjQPZ032rwaAjDBq+/6RoOCDz1twwiC62ZH2LLA21O6MGMdmGLnyXRcE+lf8Zfj3MctFnBuP5DpXPVsJzAStZymUFb7CWFRxfHERE/g==)

### Other comments
I reproduce only when 31st march is in the range so i deduce that this issue is due to daylight saving time.

**Comment by charlesg99** [comment]
Seems to happen even when March 31st isn't in the selected range. March 1st to March 10th works fine, but it doesn't with March 1st to March 11th and up.

![Peek 2024-03-18 20-48](https://github.com/vuetifyjs/vuetify/assets/33044886/785b971f-31b8-4798-8be0-eda827b26193)

**Comment by yvangrdv** [comment]
It seems to have been resolved but I don't know since when.
