### ISSUE TITLE
[Bug Report][3.5.9] The first form entry will not be validated if the form is reset and validated at the same time

### ISSUE THREAD

**Issue by kschwedler** [vuetifyjs/vuetify#19399]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.19
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Use the example from the documentation: https://vuetifyjs.com/en/components/forms/#exposed-properties
- Add button and function that resets the form and validates it to show validation errors
- Fill out form
- Use the button

### Expected Behavior
All fields are in an error state

### Actual Behavior
All fields are in an error state except the first input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVcFu2zAM/RXWGOoEaNxm7Q4Nkm4FhgG77NDDgKHpQZGZRqgsZZLspmjz76PsWFbaZNnQS0zzUeQT/cjcPifW8NPr5TKrSkxGydhhsZTM4dVUAYyrgV0gOuCSWTuZJsVqwEqnpwk8itwtyHN+djZN6uA6fK5NAQbnhHgzQDXocOUGc4Eyb50A1aDQOUqKV6zAadIhI65L5dAQNKQaEWBKiZ6NP3Hj7RiVbFan+/EqncHfpTAYSl+NT2NGxDNialEid7tYbpCYjqCeeTr1cyfR2womV3B0VMHLC6TfKQ6EDYzSu138fdRB/g2bbe58gfxhple72AfsMMtfuoSitA7YvUEEp4Fr5YQq8Wg34a8anuhMHf75IPOWScw9F1VQWj6YS1yB/xlwLctCRVqq7zlzqtOlG1yQKClQe73YknO09C1gJjV/gC9cCv5AQMWkyEndW7kAfrbuLj9RpAIRu0M10Rht3lY0aJHkslXuxvvgm5+PdxR8ZEYJdb+n5OZKQm/3rS0ewe+gsDSiYOZpD4VrlYfG7uJA+F87376TLNoFQ5hfK81y8vr324nexqfR3qJXy41YegAAV0ttHOQ4Z6V08NxkoppsBL2+V3xv4wPwC2UEaXoSO+oNM4LbaJ7iOfF7Zmuaw+FNYK+C42OoMonq3i1gPIHhWb87Ws/YDIGKWHALpggGvmCGcVp+tkt3F6xm6kegSimDs94+RLNZL8P0ZLNoPgbrPFgXaZesHcQRzJm0uPGv+2Q0ZoFuoXNKHdrE7JPi0M4SNTEglE4rus9zg8IaJsAemXB0M2GzD/TPYDP/BbPudCw3Mad2eaQPTKJxvdRPiW9v7U0puAlcB/611LY5vK61CdlzthuFf8gSB7/N1zTmtfj/ixwlOdiv7bLNc+2HIMg+WZ8k59lFNrxMvPEpu0zu/gDBDFyT)

### Other comments
When filling out the wrongly validated form, it is possible to submit the form with an empty first input  when the form doesn't get validated after pressing submit

**Comment by b-maslennikov** [comment]
try

```
import { nextTick } from 'vue'

async resetAndValidate() {
        this.$refs.form.reset()
        nextTick(async () => {
          await this.$refs.form.validate()
        })
      }
```

**Comment by kschwedler** [comment]
> try
> 
> ```
> import { nextTick } from 'vue'
> 
> resetAndValidate() {
>         this.$refs.form.reset()
>         nextTick(async () => {
>           await this.$refs.form.validate()
>         })
>       }
> ```
> 
> [playground](https://play.vuetifyjs.com/#eNqlVU1v2zAM/SusMcwJ0LjN2h0aJN0KDAN22aEYBgxND4pMN0JlKZNkN0Wb/z7Kn0qbLBt6iWm+J/KJJpmbp8gafnK1WiVlgdEkmjrMV5I5vJwrgGk5sktEB1wya2fzKF+PWOH0PIIHkbolec5OT+dRRa7omTY5GMwI8WYHVaDDtRtlAmXaOgHKUa5TlMRXLMd51CMTrgvl0BA0phwBYAqJXo0/ce3tEJVsUYX7/iKcwd+FMNilvpyehIpIZ6DUokTudqlskFCOoJp5OdVzp9CbEmaXcHRUwvMzxN+IB8J2iuLbXfo966D+Ws22dr5Efr/Q613qO+ywyl+6gLywDtidQQSngWvlhCrwaLfgLxoe6UxF/3RQeask1J6Ksuu0dJRJXIP/GXEti1wFvVTdc+FU35dudE5NSUTt+8UWnKOlbwELqfk9fOZS8HsCSiZFSt29FQvgZ+vu45NEShCoO5QTjdHmdUaDFqldttJdex989fPxhoQPzCih7vakbK4k9Hbd2uQB/AYJKyNyZh73SLhSaVfYXRoI/2vl23dqi3bBEObXSr2cfP/77URv05Ngb9Gr5UasPAAg8pU2Dp5A0az/IHmwgczoHGLaeLFn4LpipJixQhKzzkWq2AQGQz8Tg8YH4FfOBOL4OHRUO2gCN8HEhZPkN9HWvHeHG+KghPfvoUwkqju3hOkMxqfD/mg1hQsESmLBLZkiGPiSGcZpPdo+3G1n1XthAqqQsnNW+4lk1gtoHB83q+hDZ5111nncB2tHdQIZkxYb/2ZIRm3m6JY6pdBdmZh9VBzaaaMidgiF04ru81Sj9DFmwB6YcHQzYZN39N9hE/+Nk/502JAio3J5ZAhMonGD2M+RL2/ljYlcEzed/qoZtzW8zNVQ9pzth+UfooTkPfGCwfgvWdRtTQ8P6gLX3RkEoMofrGXL3LySVz83fpy6AYo2x9FZcp6MLyJvfEwuots/JnRx3w==)

Wow that was fast, works for me!
But in general my example should work right?

**Comment by b-maslennikov** [comment]
i dunno
but it stopped working in 3.3.0 (almost year ago)

**Comment by KaelWD** [comment]
Reset is also asynchronous, it uses nextTick itself between clearing the value and re-running validation. The correct way to do this will be

```js
await this.$refs.form.reset()
await this.$refs.form.validate()
```
