### ISSUE TITLE
[Bug Report] Missing First day of week prop in v-date-picker in Vuetify 3

### ISSUE THREAD

**Issue by ibujan-iar** [vuetifyjs/vuetify#19398]
### Problem to solve
Not able to set first day of the week because first-day-of-week prop from v3 is missing.

### Proposed solution
Adding First Day of Week prop or documentation to configure this property in a nuxt 3 project and translation with vuei18n that allows to modify this attribute independently of the locale

**Comment by m2xilon** [comment]
Seconded please.
