### ISSUE TITLE
Adding tooltip to a button causes pagination issues (9.0 dev)

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#194]
If I remove the tooltip, it's fine.  This use to work fine in 8.10   

     <v-btn icon dark  v-tooltip:left="{ html: 'Exit back to the Purchase screen' }">
          <v-icon>close</v-icon>
        </v-btn>

with tool tip

![image](https://cloud.githubusercontent.com/assets/287137/23823125/90096304-0610-11e7-8534-9e75de25858f.png)

without tooltip (notice no horizontal scroll at bottom)

![image](https://cloud.githubusercontent.com/assets/287137/23823136/c44ad5c6-0610-11e7-8da1-77394bee4068.png)

**Comment by johnleider** [comment]
I am unable to produce this. The after element should not trigger horizontal scroll. Will need additional context, reproduction steps, or something.

**Comment by sgehrman** [comment]
This looks ok now with latest dev branch.
