### ISSUE TITLE
[Bug Report][3.5.9] Treeview: search and filter props do not work

### ISSUE THREAD

**Issue by b-maslennikov** [vuetifyjs/vuetify#19404]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows

### Steps to reproduce
use Search text field and enter John

### Expected Behavior
should filter items

### Actual Behavior
nothing is happening

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVltv2jAU/itH0SSohGlp6cNQYdq6h2nTLtqkvbSVZpKTxcKxI9uhIMR/33EuJGmBamy8YJ/L5+9cfJy7TWBNeP42y4bLHINJcOMwzSR3OLtXADdLFnIT+SVAKLm10/sgXTGeO30flOKUr9ijiFxCquuLi1JceBf+NkF0O9+MszHMf7PMiJSbNZPid+JQscv7oHIpnByuHIsFyupo/1uyVEcoCcQiN2FSn19SIxEToVaeXyRYKLVFFgpDGqZzJ4XCtoPk8wLqRwEFtzrNuFrDe2EwdNqsn4HzucRGFHGzaHYx5avZJSJCFqHjQtpGarXUTKglGoe7oGY35+1Y2xkIEwwXc73aF3/ILf5AZYUTy71R3ZIB2NqCVk/z1eW/j3FBrSZRV5NERTmb6vruKCLoVM8gLgU+PuM+0Rn6Cvm/Np1JLKRDQ5py0dEJ6kjfOsV/R1PGtachdmSITt3PxMFK7SaZQTo9Iq8NeEjYtlqvCsA3UlvkAxBxxWEYJkJGphtBybTsv1++AV9tClsRwXQ6hRG8gV6iU2RLbgRXrgcT6MVaRmiYQveozaK3/dVFLErgMdvhnHfuZ12VOuOtQnUrU0to04GgrQ2NyBw1icuzwlakmTYONhDSrcipXQdgMIYtxEan0KM50fOOdDG0sq5IooWpt+nfledvam4imsBoUO+ccBIp7p85OhGv4UOecgXf0erchGh7O8M6wxOoADugNfDlzr4NfqsNgkOeNnAHIZ/B7qAvGtZPD/ioE9XFBtg+2R8A7TJug37iKE8EvToI+gUX2vLcnAg8PpwCHuLiRNTrg6hvFRXo8TjsQ2vX1jxrjm5WdkdEqVDCOsNpyLca7u875OpIh3wWCzwpO1dHOuRDTlPj/+SmW9jm4ihnxJxe9n/LzPhIZr4lUr9Q4YOoh1PzznAV6dMu5fjI/aGPgxdA96e8lpaSh7NmVvqHrx6VowFctnXlI1ZpVS5lS9d58SuTmEuLLZvy6SRlPbb7/TOYzuqwDc13o7pIwyWXOdLb1PdDfFBRGND4XLlPuC7cveauEjwMhYpw9TXul5ZnMAM2oqcsJ3FMn1jFl82WSN2cl8/KLNgOgqvheDh6HfjF9fB18PAHetHGzA==)

### Other comments
played a lot with this. no results. does not work at all...
PS: v-model:open does not seem to work as well (should be raised a new issue?)
PSS: noticed that almost everything does not work properly. which is ok for 1st version of labs component.

**Comment by liunnn1994** [comment]
3.6.4 also has this problem
[example](https://play.vuetifyjs.com/#eNq1Vttu4zYQ/ZWBUMAJYGqT2NsCQpzFNn1YdNELukBfkgBLS6MVa4oUSMqxYejfO9TFkmzDCbqpXySeGc6ZmzzzsAs+FkW4LjGIgluHeSG5w7tHBXC7ZjE3iX8FiCW3dvEY5BvGS6cfgwbO+YY9i8RlJHp/ddXA9e36vs0Q3f5uwdkclt9YYUTOzZZJ8S1zqNjNY9BeqS853DiWCpQttf+tWa4TlGTEIjdx1vE3rhHERKyV9y8RLJbaIouFIQnTpZNC4fCC5Mva1JfaFNzrvOBqC78Ig7HTZntknC8l9lDCzao/pZSv/pSJBFmCjgtpe9RqqZlQazQO90Hd3b4bxjrMQJxhvFrqzan4Y27xCyornFifjOqeFMB2GvR2mK+x/6c8rl3rnOiqSVBdzr66vjvqCEbVM4hrgc9Hvke6QF8h/xi6E6VCOjQkaV5GMkEd6Vunfo4kTVwnGmLvDLnT9TP5YKV2UWGQ2BO6tQNvEqpB67UB+EYaQj4AkbY+hHEmZGLGETSeNv331TfgD7taVySwWCzgGj7AJNM5sjU3gis3gQgmqZYJGqbQPWuzmlRfxxbrEnibw3Dejb7PripdxgeFGlemQ+gwMkFHGxtRNFq4KbRxkGDKS+lg11hLuOMRXFzC4g4uWgzq3NkIHnrf9qJanERwPR0iTjiJFPXfJTqRbuFTmXMFf6HVpYnRTkbKXY5HBEckHdHN6O6Q7F4bBIc8H5s/S3GSZk91NY7qkPBXnaljLoDqBHaG5DiiIclnjvINSGZnSX7Hlba8NG9AND+fMh7j6g1Y3p9l+aio2M+vo3k6QA41TjbhcTb31EkulLDOcBotB43+3ztx9kIn/iZW+N1Znb3QiZ9K+i/7/3J63Dj9h62cEUvaQ94uo/MXMvpnJvUrO+gsy/mU/my4SvT3/4nMX/i+afV5Jcn50g2lvaRH/bCnOlxP4aYHm4kdgSql3IOjvSaClEuLrbC6bF9i2tRKWqGiPvBmZ/ADapALg640ClwmbDjelwauf4ALP8amrTtTmhQb9xm39ajzkocWeAqFSnDzR3rRaF7CHbDroakIStJIac3cb3ddMppn5SdvO2uDaUAL6cqG/1itaOne0U5nabeJHp4qkoncj2GW82Kg0IBeaVdVQTUNZuE8vPmJ1Gfhj+E8mDpT4tO/a9/1pw==)

**Comment by gcc-master** [comment]
Confirm, search function don't work properly.
Result tree is broken. Hide some top elements
Search sample: cormier.agnes
Sample Tree JSON data  for test attached 
[tree.json](https://github.com/vuetifyjs/vuetify/files/15341718/tree.json)

**Comment by lubuger** [comment]
Still not working on 3.6.14

**Comment by yuwu9145** [comment]
> Still not working on 3.6.14

v3.7+

**Comment by Employee87** [comment]
I was just trying it out on 3.7, but seems the search doesn't work still?
https://play.vuetifyjs.com/#eNq1Vttq4zAQ/ZXBLKSFKL2zYJqWbvehbNkLW9iXtlDFGtcismQkOU0I+feVfIntJCRlm82LrRnNnLkcZ+ZxHhgdHd1k2WCSYxAGlxbTTFCLV08S4HJCIqqZfwWIBDVm+BSkU0Jzq56CUpzSKXnjzCZOdXF8XIoL68LeJIh2aZtRcg6jV5JpnlI9I4K/JhYlOX0KKpPCyOLUkpijqKD9b0JSxVA4JwapjpIavwzNiQiPlPTxMU4ioQySiGunISq3gktsGwg6Klw9FK7gVqUZlTP4yjVGVunZmnM6EtiIGNXj5hS7ejWnhDMkDC3lwjRSo4QiXE5QW1wmdXV51M61XYEowWg8UtNN+UfU4ANKwy2fbMzq1l0AU99wb6v16sa/KeIitDqIuptOVLSz6a5nR5FBp3saccLxbS32UGXoO+Qf7XDCmAuL2mnKl46OO0Z66hTPjqbMawMhlsG4cGo+uxiMUDbMNDp05qzm4F3CokW9KgFPpLbIJ8DjKoZBlHDBdDeDMtKSfy+egJ/mxV3OYDgcwglcQy9RKZIJ1ZxK24MQerESDDWRaN+UHvcWL12PRQu8z3Y6R53vs+5KXfFWo7qdqSXu0HHhjibSPCtv4TRT2gLDmObCwrz0xqilIRwcwvAKDioZFLUzITw2sS1VhZqFcNJvSyy3Al3Wf3K0PJ7BXZ5SCb/RqFxHaHqdy3WNOwBrIDXQace2DXarNIJFmnbdb4XYCLOEOu5mtQr4TSVyHQtgsUG2BWQ9ozbIPUWxB5CzrSA/cKwMzfUegM63l4xGON4DysVWlBvpmv32PpjnFcnqjY0kXK/mEpqlXHJjNXWjZYXo/87Esx1M/M7H+OGqnu1g4l3u/sv+X03XidN82NJqPnJ7yP4qer6jor8Sod7JoK0o20v6RVPJ1Mf/RM53fN9u9XknyPbWtbWNppH6Ye/6cNKH00ZYTuwQZC7EUtjZa0KIqTBYKReH1UvkNrXcrVBhk3i5M/gB1aqFRptrCTbhZtDdl1qhX8OBH2P9Kpy+mxRTe4+zYtR5zWMleB5wyXD6Mz4obx7CFZCTtqsQcncjdmvmcruri1E+F37yVrM2WPSLxIOzwefBcfD8F2Ah30Q=

**Comment by lubuger** [comment]
> I was just trying it out on 3.7, but seems the search doesn't work still? https://play.vuetifyjs.com/#eNq1Vttq4zAQ/ZXBLKSFKL2zYJqWbvehbNkLW9iXtlDFGtcismQkOU0I+feVfIntJCRlm82LrRnNnLkcZ+ZxHhgdHd1k2WCSYxAGlxbTTFCLV08S4HJCIqqZfwWIBDVm+BSkU0Jzq56CUpzSKXnjzCZOdXF8XIoL68LeJIh2aZtRcg6jV5JpnlI9I4K/JhYlOX0KKpPCyOLUkpijqKD9b0JSxVA4JwapjpIavwzNiQiPlPTxMU4ioQySiGunISq3gktsGwg6Klw9FK7gVqUZlTP4yjVGVunZmnM6EtiIGNXj5hS7ejWnhDMkDC3lwjRSo4QiXE5QW1wmdXV51M61XYEowWg8UtNN+UfU4ANKwy2fbMzq1l0AU99wb6v16sa/KeIitDqIuptOVLSz6a5nR5FBp3saccLxbS32UGXoO+Qf7XDCmAuL2mnKl46OO0Z66hTPjqbMawMhlsG4cGo+uxiMUDbMNDp05qzm4F3CokW9KgFPpLbIJ8DjKoZBlHDBdDeDMtKSfy+egJ/mxV3OYDgcwglcQy9RKZIJ1ZxK24MQerESDDWRaN+UHvcWL12PRQu8z3Y6R53vs+5KXfFWo7qdqSXu0HHhjibSPCtv4TRT2gLDmObCwrz0xqilIRwcwvAKDioZFLUzITw2sS1VhZqFcNJvSyy3Al3Wf3K0PJ7BXZ5SCb/RqFxHaHqdy3WNOwBrIDXQace2DXarNIJFmnbdb4XYCLOEOu5mtQr4TSVyHQtgsUG2BWQ9ozbIPUWxB5CzrSA/cKwMzfUegM63l4xGON4DysVWlBvpmv32PpjnFcnqjY0kXK/mEpqlXHJjNXWjZYXo/87Esx1M/M7H+OGqnu1g4l3u/sv+X03XidN82NJqPnJ7yP4qer6jor8Sod7JoK0o20v6RVPJ1Mf/RM53fN9u9XknyPbWtbWNppH6Ye/6cNKH00ZYTuwQZC7EUtjZa0KIqTBYKReH1UvkNrXcrVBhk3i5M/gB1aqFRptrCTbhZtDdl1qhX8OBH2P9Kpy+mxRTe4+zYtR5zWMleB5wyXD6Mz4obx7CFZCTtqsQcncjdmvmcruri1E+F37yVrM2WPSLxIOzwefBcfD8F2Ah30Q=

not sure why, but in playground on other versions of vuetify it doesn't work as well. Might be issue with VUE versioning or something else? like week ago or two it was working perfectly. Now it's not working even on vuetify website in examples section

**Comment by b-maslennikov** [comment]
confirming

**Comment by yuwu9145** [comment]
`item-value="id"`

https://play.vuetifyjs.com/#eNq1VttO4zAQ/ZVRtVJBqrnvS0RBLPuAFu1Fi7QvFAnXnhCrjh3ZTmmF+u9rJ82NRgUt3T40ycx4zplLMnP/MrCGHV5l2cE8x0E0OHeYZpI6vJgogPM5YdRwYJJaO54M0gWhudOTAaR0QZ4Fd4mXfj46mgwK++KETRBdfSSj5AymTyQzIqVmSaR4ShwqclIfKQ45XDgSC5S8EgLMSao5Su/EIjUsmQwaHZNeRATTKtDigjCpLRImjNcQnTspFLYPSDotXN0VruBapxlVS/gqDDKnzXLDOZ1KbEScmlnzFPsMNU+J4Eg4OiqkbaRWS02EmqNxWAd1cX7YjrWdAZYgm031oi9+Ri3eobLCiXlvVNfeAGxl4e9e56vLv49xQa0iUVXTi4pyNtUN/VBE0KmeQZwLfN7gHukMFXLPMNy0CUWxkA6N15Q3HZ3wXRiap7h2NGVkvS0RjMmcyhzDSd6oaqaea9XenqCV2kWZQU8sEHwpHMCq1Zfr6EKXtUUhOhGv6R2wREhuusGVQZTN+Ri689NLYSs4jMdjOIZLGCY6RU/XCKrcECIYxlpyNEShe9ZmNlw9dj0W9Qk+2+Ecdl7XqmRVOVpV7JatkviHjgv/aJkRWWmFi0wbBxxjmksHL6U3Th2NYG8fxhewt5YBhPJGcH88gpOHUSUsyuelDeHavlDzCI5r4/Bzwkn0qfiToxPxEm7ylCr4jVbnhqEddoyrxHcANkAqoJPO2TbYtTYIDmnadb8VohemhjrqRvUa8JtO1CYWwKpHtgVkM6I2yC1FuQOQ060gP3CmLc3NDoDOtqeMMpztAOXzVpQr5Yv9/D6Ypsv7LXqbcDObNTRPhRLWGeqH0atG//dOPH2jE7+LGX44q6dvdOJN7j9w/y+nm43TvNjKGTH1C8vuMnr2RkZ/JVK/s4O2omxP6RdDFdcf/4icvfF++2XpnSDbS9fWNppG2js9ygkfgcqlrIWdTSiCmEqLa+Vqf33D/G6X+6UragIvdww/tFqpMOhyo8Alwh50F6wW80vYC1NstGYz8oNi4W5xWYy/oLlfCx4OhOK4+BnvlZb7cAHkuO0qgtxbxH4vrdfBKhfldRWmcT1/B6tREXn4e/gLZWbqzA==

**Comment by b-maslennikov** [comment]
@yuwu9145 this does not work when I have return-object

**Comment by yuwu9145** [comment]
`return-object` doesn't work

https://play.vuetifyjs.com/#eNqtVl2P2joQ/SsjdCV2JczudrcvaNmqd6+uqvtZtVJfyko19qRxcezIdoAV4r/XcXDiUKAq7QvEM8cnM2fGnnzcDKxhV6/LcryscDAZ3DssSkkdPswUwP2SMGo4MEmtnc4GxZrQyunZAAq6JivBXe6tL6+vZ4OADztsjujaLSUldzD/TEojCmqeW2CAOlw7kgmUPBoBlqTQHKXfapEals8GnY9JbyKCaVUHwwVhUlskTBjvIbpyUihMN0g6D1TvAxU86qKk6hn+EAaZ03U4e+R0LrEzcWoW3SrzunSrXHAkHB0V0nZWq6UmQi3ROGyTeri/SnNNFWA5ssVcrw/lz6jF96iscGJ5MKtHDwAbEf5pX69+/IciDqHFIGINvSkUsatp3QUhg171DOJS4Kp7gy5RESplZ5mwyjpd+MSlQ+Njbh7+VGmYE+G7rm6W8N/zNDkdbIYaTJZUVljv5KnLoKuMInr+xZe5TbXzt13u1bZSu0lp0IfOPdEm8MI2adRdunXbpaa6VCLbRT1muZDcYC+vJremWz/V7frbJmAFh+l0CjfwCoa5LtBnYQRVbggTGGZacjREoVtpsxhuP/UZQ8FqzjSdq96pjTWM9UnK2q9jtPhFj8IvLTOidL6lXFUGrChKbRxsvLYZbCEzuoChvzOGNdwfHq2sC9JZmNaYi4/NWzcxIsEncDOKKyecRJ/thwqdyJ7hTVVQBe/Q6sowtMMWGHWdwI6wRxqJX7T4lPxRGwSHtOjojlJ+Q9tSX3dR77/gL52rPjfAdm99hLQfcUr6N0V5JuntUdL/cKEtrcyZxHfHJaAMF2eyvjzK+lr5Aq1O0z4lq9TzTXP0VWlfwQuhhHWG+kGQNNyPd8jtiQ75VyzwLHVuT3TIm8rfFb9Gm35hu4OjnBFzP+p/Tpm7E8q8zaX+ToWPsh6X5ndDFdfnHcq7E+fHf0B8h/Sw5NHaWJ4uu7uynpXxqrwZwYvU1wy7nVdVUia+3lfBDpJRaTHBxCHr3VmlmBNawUUYlaMd9yjc1ZdRiGZg9rnHYUNM5FXYMA56jIXiuP4/u2i4LuEByE0ETlKg0//oFZr6Q+Xicm9b39mRbOtp1MwfP3kG21EtQPh5+gremtv/

**Comment by b-maslennikov** [comment]
'return-object' works. search and filter does not work with it

**Comment by yuwu9145** [comment]
Yeah, I mean `return-object` doesn't work in this issue context (search & filter)

**Comment by frafrafrafra** [comment]
Working for me on 3.7.0 :+1:

**Comment by J-Sek** [comment]
> _Yeah, I mean `return-object` doesn't work in this issue context (search & filter)_

Could be covered by [#20459](https://github.com/vuetifyjs/vuetify/pull/20459)
