### ISSUE TITLE
z-index prop for VDialog similar to VMenu

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#1940]
It would be great to support `z-index`prop for VDialog similar to VMenu handling. This would enable the use of multiple dialogs visible in one time. Thanks!

**Comment by Webifi** [comment]
Pull request #1932 would negate the need for this, if accepted and merged.

**Comment by johnleider** [comment]
Please update this issue with the specified boilerplate and I'll re-open.
