### ISSUE TITLE
[Bug Report][3.5.9] RouterLink.useLink is not a function when using vitest & nuxt

### ISSUE THREAD

**Issue by hareland** [vuetifyjs/vuetify#19407]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set up a new nuxt environment, install vuetify => you could use: https://vuetify-nuxt-module.netlify.app/

The component this happens for, is VCard, please see output below:
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  lib/products/components/product-card.nuxt.spec.ts > displays the correct details
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: RouterLink.useLink is not a function
 ❯ Module._createVNode node_modules/.pnpm/vuetify@3.5.9_vite-plugin-vuetify@2.0.1_vue@3.4.21/node_modules/vuetify/src/composables/router.tsx:73:16
 ❯ Object.setup [as _setup] node_modules/.pnpm/vuetify@3.5.9_vite-plugin-vuetify@2.0.1_vue@3.4.21/node_modules/vuetify/src/components/VCard/VCard.tsx:157:21
 ❯ setup node_modules/.pnpm/vuetify@3.5.9_vite-plugin-vuetify@2.0.1_vue@3.4.21/node_modules/vuetify/src/util/defineComponent.tsx:131:3
 ❯ callWithErrorHandling node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19
 ❯ setupStatefulComponent node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7554:25
 ❯ setupComponent node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7515:36
 ❯ mountComponent node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5845:7
 ❯ processComponent node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5811:9
 ❯ patch node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5290:11
 ❯ ReactiveEffect.componentUpdateFn [as fn] node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5955:11

This error originated in "lib/products/components/product-card.nuxt.spec.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "displays the correct details". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  1 failed (1)
      Tests  1 failed (1)
     Errors  1 error
   Start at  22:18:03
   Duration  5.41s

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit

### Expected Behavior
That the useLink exists.

### Actual Behavior
Not defined.

### Reproduction Link
[https://not-reproducible-on-playground.github.com](https://not-reproducible-on-playground.github.com)

### Other comments
Please let me know if there's any changes i need to do.

**Comment by JessieVela** [comment]
I think what you want is the [to prop](https://vuetifyjs.com/en/api/v-card/#props-to).
[Playground](https://play.vuetifyjs.com/#eNpVj8uKAjEQRX/lTm16Bma6GR8LpRXc+QcubBehLTWY7oSkFEH8dxOjoJBF3UPlVNX6SsG31cK58nximlIt3DmjhOdND9TnP+Xco3yE1vaidM/+iTJUfgvRYnjWkHCQhiB8kZQOOiA+BaP7Y+I20qqhOeoq/3zJU/ywJ5KH19XbUjGG1msnCCynvJvunPWCKzzvcMPO2w5FvKdI7UD0BkEX9pilju9iycZYrKw326/iJw3Iyiij2y8Ny1E5+KdUjMsJbe7rI15L)

**Comment by hareland** [comment]
@JessieVela thanks for your suggestion. I am however already using that prop. It is the underlying mechanism used by the VCard when providing `:to` that mess this up, i believe it is because the correct extension on RouterLink is never applied, or applied to late in the process - maybe something with vitest/nuxt since it only happens when i run the test suite.

**Comment by hareland** [comment]
Related:
- https://github.com/vuetifyjs/vuetify/issues/17490 
- https://github.com/vuetifyjs/vuetify/issues/19300

**Comment by SvetlozarValchev** [comment]
I am not using the to prop anywhere, but I also get this error. This is not a problem with 3.5.8

**Comment by KaelWD** [comment]
The components won't work if you have stubbed router-link or have another component named router-link that isn't from vue-router.
