### ISSUE TITLE
[Bug Report][3.5.9] Weird animation glitch of Text field loading progress linear when loading is started or ended

### ISSUE THREAD

**Issue by IeTerin** [vuetifyjs/vuetify#19410]
### Environment
**Vuetify Version:** 3.5.9
**Last working version:** 3.3.14
**Vue Version:** 3.4.21
**Browsers:** Edge 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
This animtion glitch is more noticible when the text field variant is outlined or solo.

### Expected Behavior
It should be smooth animation like it used to be in version 3.3.14 or older.

### Actual Behavior
It  is glitching when loading is started or ended

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUMtOxDAM/BUrl4JEW/E6sOoiIa7cOFIOaeuyEWkdJW5ZabX/TtJmacTNnrHHnvk4CWfb8sWYYp5Q7ETFOBgtGZ/rEaCac2nMUi5NSyNLNaKN0AoesP1u6AhaNqj3tXg/0A+8kezU+FULmPOBuoXQf1iZCjAeOe8V6u4CQrI0OL+wES1psh5u9IQpvovi6ZlETlolR/YkTay9g25jL79U5X+DAVn9V2WSi29da5VhcMjTGo8aDFmGE1js4Qy9pQEyH2kWSK/qGOJbsA8zV73UDq831tuMTPYaAgUmcCHIuJb52apc7/qL4nwj7ouH4u5WhOKxeBKfv1n8ka4=)

**Comment by KaelWD** [comment]
#18169

**Comment by yuwu9145** [comment]
Is this the glitch you meant?

<img width="135" alt="Screenshot 2024-03-15 at 8 42 28 pm" src="https://github.com/vuetifyjs/vuetify/assets/5698884/f8499fc7-68e8-4aa8-9e71-f11c08ad53ce">

**Comment by yuwu9145** [comment]
Due to inner border radius is bit different from outer border radius, it still has a little tiny overlap, but overall optimised a lot.

**Comment by IeTerin** [comment]
> Is this the glitch you meant? The animation itself runs pretty smooth in my end
> 
> <img alt="Screenshot 2024-03-15 at 8 42 28 pm" width="135" src="https://private-user-images.githubusercontent.com/5698884/313143031-f8499fc7-68e8-4aa8-9e71-f11c08ad53ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzgyNTksIm5iZiI6MTcxMDczNzk1OSwicGF0aCI6Ii81Njk4ODg0LzMxMzE0MzAzMS1mODQ5OWZjNy02OGU4LTRhYTgtOWU3MS1mMTFjMDhhZDUzY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDQ1OTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc1NzIzOTBmMGE3MTg4NjkyNjcwYzBjNDViMjJhMGRhM2JlZWE1NzM3MDY4MzM0YjExODkyYWY0MDNiNTVkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d888SROmCOSiuOKjNC1VfJFBqjrxTB6Z6SS2GhxobrA">

The glitch I meant is not like that. 
Please look in the following screen record GIF.
![VuetifyPlayground-GoogleChrome2024-03-1813-04-04](https://github.com/vuetifyjs/vuetify/assets/138089851/2663cc31-ce2f-4578-80cc-e314c51fb993)

After doing a few research. it appear to occur only in Chromium based browser. (Tested in Edge and Chrome)
It is completely smooth on Firefox,
It's hard to say browser's bug because even on edge and chrome, it was perfect before Version 3.3.14.

**Comment by IeTerin** [comment]
I also added Temporary Solution here. ( Put Progress Linear to loader slot of Text Field )
[Vuetify Playground](https://play.vuetifyjs.com/#eNrNUsFOhDAQ/ZVJPaCJQHT14IbdxHj1tt7EQ4FhaSyUtAXXbPbfnS6wlETv9tS+N515M/Pej8zoPH5u26jvkK1ZYrFuJbe4TRuApA95256v50euGstFg3qEBrDC/DNTB5A8Q7lJ2a5SX/CqeCGafcqgD2tVnAl5wWI/gcWDDUuBsphA8D7Vhj7MRK6k0gRnskMfX4/J/TJeOq4FbyyRqrOSOihm1tNSiB5yyY2hwGoFdRbep2z7RiNRmn/DTsnOCtUkMQX+ow4uUkjMtD+4ckm8TY1SW632Go0JXQ6ufdZpNrS73wW4U6HYV04DjWXJ/NWUO6Ip0KKuRUO6fGqePEmLF84bIH+ykwsJXNrQIYNLFznoaXItWgsGbTeYWLhFWjiCxhJOUGpVQ0DGDxxJWY2FsXPYuJjrkkuDNzNLqxyZ4MXZHqwCN7LpW0CxSTzUpYrsdMtW0UN0f8fc5TF6Yh8/8ygJvA==)

![VuetifyPlayground4--MicrosoftEdge2024-03-1814-18-49-solution](https://github.com/vuetifyjs/vuetify/assets/138089851/46c04d9e-a031-4456-ae68-2697dc841944)

**Comment by yuwu9145** [comment]
Thanks, I can constantly replicate in Windows
