### ISSUE TITLE
Label animation in v-select with non null data

### ISSUE THREAD

**Issue by luiber** [vuetifyjs/vuetify#1941]
### Steps to reproduce
Use a v-select with label="somestring" and v-model="somedataprop" with non null initial value
### Versions

0.15.7
### What is expected ?

Initial data is displayed without the label animation triggering, as in v-text-field
### What is actually happening ?

Every time the component is initialized the label animation is started: the behaviour is different between v-select and v-text-field
### Reproduction Link

https://codepen.io/anon/pen/rGmNOZ

**Comment by luiber** [comment]
Thanks a lot! Works well on codepen, but i still have the same behaviour in my nuxt app; will try to figure it out....

**Comment by johnleider** [comment]
@luiber if you can reproduce it in a repository, create an issue and we will square it away

**Comment by luiber** [comment]
Sorry to reopen this, but seems i cant'figure it out...I create an example repository at https://github.com/luiber/test-nuxt.git.
Is a basic nuxt app using vue 2.5.4, vuetify 0.17.1 and latest dev of nuxt: when the page is loaded animation is triggered on v-select.
In a codepen as https://codepen.io/anon/pen/LOOMrb with vue 2.5.4 and vuetify 0.17.1 all is ok: but i noted that if i change vue version to 2.5.1, as here at https://codepen.io/anon/pen/vWWvaJ ,animation is triggered again.
Not a big issue, but annoying in pages with many v-select: hope someone can help...
