### ISSUE TITLE
[Bug Report][3.3.22] Adding third party package.

### ISSUE THREAD

**Issue by sungjinKwon92** [vuetifyjs/vuetify#19411]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.4
**Browsers:** Chrome 122.0.0.0
**OS:** Windows

### Steps to reproduce
manual process.
1. pnpm i
2. pnpm run dev

### Expected Behavior
Not working with third party package.

### Actual Behavior
working with third party package.

### Reproduction Link
[https://github.com/sungjinKwon92/vuexy-playground](https://github.com/sungjinKwon92/vuexy-playground)

### Other comments
Hi, I'm trying to add more packages to my vuexy-vue-template.

I followed the package installation guide (like pnpm add "package-name") in the third party website, but it was not working well with vuexy template.

I felt that I need to set additional things to work with third party package.

Could you let me know what things I need to set for using third party package in vuexy-template?

I'm using vue.js for my project.

Thank you.

**Comment by KaelWD** [comment]
This is not related to vuetify.
