### ISSUE TITLE
[Bug Report][3.5.2] Switching VTab tabs make the content disappear

### ISSUE THREAD

**Issue by obadahalak** [vuetifyjs/vuetify#19424]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.19
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
when I switch between tabs sometimes the content disapper

### Expected Behavior
content should not disappear

### Actual Behavior
.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl9P2zAQ/yq3vBQk3KiDSagqTNN42TSmaaDtYd2DmzitIYkj+1KoEN99Z9dJ83fwABLV+e5+9z9n/3kKjI7CT0Ux3ZYimAcLFFmRchSXyxxg8euneoC70qBMdhfLIBI5Cr0MnNCKP6sUIpUaks3eLwNI15aaEZXFFc9knudRDsd1XB8t45avzOEMsGWZikVKSOSrZdAUJfJRxIzYLYARqYiQBFHKjY1ntWZrLXYs5vpe5OwUUDwie9hIFE17jSh8HLDlaSnIwp1aXQnkMjUUO3xVK4j3R1iEVvE/UIMcSwe7cdTLiFhFTv9KRWVGZX4FpNgoVA70w1EvIzJeWPVrXvR19wxDnGZfbKNuqXAdo79lHtNkzF2TWGXetQqqBmTIzhtNb0O/0Jx1wmorAlhuh7V4xxgsqBM2g/ASGOuaDxv2W6mMOq+r2HXmBWMh+Jq/URS+/V1vjj0WAY1KT2j/5olMhe0ADfANKi2mRNh/B2h9SzXEyHVOg6r93B9gtWAI+EbJ119L14MXDBYgltvDqD0y2jQ9uFPuDVG1YGRCyHd1shzt6kPzcZqKfI2b4ULBweeOne13ykrFOzaDROW0X4Rcb4iV8uh+2MJglADfFVQRwE7gYCphMVDvxkB8kwb3+2Ys50RpCv3IezqBe7E7BplDrwpj2c8JQRbod0xDGsbjTHb6XuO9A7LhqWE7Q5NVZRpS699m8FobvuuMhNXCH59AP0bNT2ZsEKlBdpuOVC03qMsIpcpHmqfFHV1wjCIaCOhVpafYeqEO177PfW3RByTtO6Z3oXhe9aSgk0r3j4/Qvj6IXISNRwkdTaRlgXTjY1k4TZkVSiM8gcqvVUlPlPiEypXAMyRaZTChp83E6kVUXAS6peDCyo8mk2NrfW+PLAXPJ8Hp9Gw6Ow8s8WF6Gvz9B/h7aec=)

**Comment by paradix** [comment]
I'm faceing the same issue

**Comment by obadahalak** [comment]
> I'm facing the same issue

You have to update vue version to "^3.4.19"
its work with me.
