### ISSUE TITLE
[Bug Report][3.5.9] bug in v-list

### ISSUE THREAD

**Issue by Quentin-Guillemin** [vuetifyjs/vuetify#19425]
### Environment
**Vuetify Version:** 3.5.9
**Last working version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Google Chrome, Firefox 124.0, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. Check list item by clicking on item
2. Try to unckeck by clicking on item

### Expected Behavior
Item should be uncheck

### Actual Behavior
Nothing append

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVVsFu2zAM/RXC5zntsO7QoitQbMCwyzCs2GnZgZGYWJgseRKdNCj676NkO7VzyIakPfQUWXx8FPlIKT8fihjU2W3TzNYtFVfFNVPdWGS6mTuA63WpMOi0BFAWY/wwL+r7Elv286LbrvG+3BjNlZguzs+77eyd/dl7u8AAylsfBNK0obE0L3pExizYgVHeJXJtyppcK4Drs2wR4Aja05Vs2NLNHTEbt4oJOrVMnGKDikIm7JcT8354XDmz3E5OkJFPQXb+4m1NZLDGUaoNV4H2kkv2MraLilBL5B+RAnz0joO3+dx79snJss2IJDvC6XafbKIjx7A0lilIQXa8I9AT8R6HxB4Qgx1AKgtckci2Rw2W1mSBPQSKHIxiwKbhKGhkUOhgQaD9xlkv+fStM5TvQNCJ+agqfJP23PigT0/+O/1pTSBoekZY+gDSuKrCSCDrVn52xnEpBtDRaY/3xl2mzdqk9ki2Yf2PJoRIlpT0FgeZ59VWLHmEjTrYoJ/JUUD7360Ja7QtCbnzbJZGIRvv4iiEwIdLBWQAreerJlBDTovTA5h4q9isCR6zz1iHiVIoKO8gMoZUmSdUd01VpH4v/H0e5qvaa7LlcLAhQj/RY+iEaCpVF2+cxdnobjzYiV/HlTi9HTPdFmoCXPiWoW20HEImzqfRi6khV1injTSCX15q+nZCR986fbTAr1/eu5T/6bLeyiNadlp2Oop46LbApqYZfEJGkLskrETYGrcJYrcvI6g83yvi42f29UuatUCtoS/F86hbyw2g0FoRT6grLxMcldzNbggDm0o+hnmN8trKcYmf7fnoPtJfOPkYVaN4fFO8m13M3l4WafF+dln8+gu0ZD6u)

### Other comments
Checking the box does not update selected v-model anymore

**Comment by Winter979** [comment]
Similar one here with the same issue

https://play.vuetifyjs.com/#eNptkMuKhDAQRX+lyMYZ8IGvxYgOzHK+oe2FxPQQiBqSUhjEf+9otG2Cq1RVDlX33ttMtKLRj5ThNDJSkBJZJ0WD7LvuAcopaKTcyq2hQ48N75naR9tQcI1HCzAF3dAyUWgmGEXWVjU5ypqcWMHNIW0+t/f9x9KBRmVU/P0bhIpGa05PKHqdn+edZy0sy64zcoWuE+ujjN78mVZTxSWaHTham7yTg0KYQbEHLPBQQweeicZbcQCzVyNsmqGCmz04w9SIkRUQ+4Acham8X4NA7MHiO0ziMMkFkzpMesFkDpNdMLnD5AdzP7284qtWyx/9KMTnmpNNxmRCFp+kYRYmMVmLPPwi9ydxpK7Z

**Comment by Tennyleaz** [comment]
Can confirm, same issue on v-list in 3.5.9.

**Comment by KaelWD** [comment]
Fixed by fa5f351f9636f32c998614ada1bfd09fa94bde2b
