### ISSUE TITLE
[Bug Report][3.5.9] Calendar type is always month

### ISSUE THREAD

**Issue by cometurrata** [vuetifyjs/vuetify#19427]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Setting calendar type to something else than Month

```
<v-calendar color="primary" type="day"></v-calendar>
```

You can also see that from the documentation page: 
https://vuetifyjs.com/en/components/calendars/#type-day

### Expected Behavior
Should match V2 : 

https://v2.vuetifyjs.com/en/components/calendars/#type-day

### Actual Behavior
Calendar is always shown as month

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjk0KwjAUhK8SZq0J/i2UWPAcxkWoDxTTJrzGliLe3TQttruZ4WNmrh80XKpLCLJ9E07QkargbKTC1ELods2+yzKb0rvJZNs8iOI/GAnrqL5bFgn1fDYI/Kws9wYi9oFS0BG9DAqtZnjuTOGyNEPT5qDHM1otTuK7wk7u5XaDQRzkEbcfJdBBOg==)

**Comment by blalan05** [comment]
The correct prop is viewMode
