### ISSUE TITLE
<v-data-table> - Changing rowsPerPage throws TypeError.

### ISSUE THREAD

**Issue by shinrel22** [vuetifyjs/vuetify#1943]
### Versions

Vuetify 0.15, Chrome, Vue 2.4

### What is actually happening ?

It throws TypeError when I change rowsPerPage while setting hide-actions=loading. Any help?
```
vue.esm.js?65d7:563 TypeError: Cannot set property 'listIndex' of undefined
    at VueComponent.eval (vuetify.js?f395:7171)
    at Array.eval (vue.esm.js?65d7:698)
    at nextTickHandler (vue.esm.js?65d7:645)
handleError @ vue.esm.js?65d7:563
(anonymous) @ vue.esm.js?65d7:700
nextTickHandler @ vue.esm.js?65d7:645
```

**Comment by KaelWD** [comment]
Please provide a reproduction link

You can use this template: https://template.vuetifyjs.com/

**Comment by shinrel22** [comment]
Oh sorry, I forgot my reproduction. Here it is...
### Reproduction
https://codepen.io/shinrel22/pen/qPjJYx
