### ISSUE TITLE
[Bug Report][3.5.9] drawer item not deactive when navigate to another route

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#19434]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Edge 122.0.0.0
**OS:** Windows 10

### Steps to reproduce

![bug](https://github.com/vuetifyjs/vuetify/assets/40021217/55647572-28a5-44d8-b9df-4aebb96f49f1)

To reproduce this bug, you must visit `/` first. If you directly visit `/about-a` or `/about-b` via the address bar, there is no such issue.

### Expected Behavior

If you navigate to `/about-b` via a `RouteLink`, "About A" on the drawer should be deactivated.

### Actual Behavior

Both drawer items activated 

### Reproduction Link
https://stackblitz.com/edit/node-3v7ez8

**Comment by KaelWD** [comment]
Fixed by fa5f351f9636f32c998614ada1bfd09fa94bde2b
