### ISSUE TITLE
[Bug Report][3.5.9] VSelect #selection VListItem #append not appending

### ISSUE THREAD

**Issue by eductivegmbh** [vuetifyjs/vuetify#19437]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Safari 17.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a VSelect with a #selection slot that holds a VListItem with #append slot.

### Expected Behavior
The appended content should show at the end of the VListItem, like seen when doing the same within the #item slot.

### Actual Behavior
The content ist not appended.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9UstqwzAQ/JVFPTgBP0jSHmocQ7+h0Eucg2opIFBkIcmmYPTv1cM2dig95iLtY2Y0i/YyIq3a4kPKfOgpKlFl6F1ybGjdCIBqyFqsSIhj1gmDmaAKbrxnc8O1vj4pp62BkjkBfW5QuBsEQ3bvCOWuMmDeU1daSI42vwYvHu9AI/ggBak6qcFu0MEBZ9pkHuOUv5kgjhOwD8iNNpaSClKDG9PdUBWbIRdCsVJfm/wLvlLXYXLWicX+v74fba5amWGG03qMKnnIwNqNsQnzvFmrYvrbeQscdVmDuCW+Etdkw3epbhWTkUl/ZKcMEHrDPTcwRjWCDS5ht4dzDbupBmF8XcIlOSQpJEd/nJJrOrfjJpXg27Fm9yGw3sHyJrIpOuWv+fGAfPCWv6PrL4vs4oI=)

**Comment by KaelWD** [comment]
It's right here idk what you're on about
![Screenshot_20240320_192322](https://github.com/vuetifyjs/vuetify/assets/16421948/1d75edfc-52d5-43d2-8136-75249ebaee87)

**Comment by eductivegmbh** [comment]
Then it might be a misunderstanding on my side. I was expecting the #append in the selection slot to work like in all other cases of the list item #append slot, as can also be seen in the #item slot. If this is by design then thank you for the clarification.

<img width="905" alt="append" src="https://github.com/vuetifyjs/vuetify/assets/79569279/cf4f6671-ca5b-4b37-881a-98fb68bb8bfb">

**Comment by KaelWD** [comment]
v-select__selection doesn't fill width, it isn't really intended to use a list item there.

**Comment by yuwu9145** [comment]
There is no plan to change v-select__selection default auto width behaviour, but 100% width could be achieved via overridden custom css. [demo](https://play.vuetifyjs.com/#eNqlUttqwzAM/RWRMdJC0sv2lrWBfUdbihcrzOA6JnayjpB/n2w3WbKNMdiLL9I5Rzq2Dl1k6mL9rPWqbTDKop3Fi5bMYn5UALs2LVjN/TncKmWZUFhDKRsxJHzKoMTCQiZIweyPkd+PEbTppeIoKdIy2SCFRhbxhnJw5/AE6sAdEtB1pQ30M7SvI4WxqcOQ8otQnDge+wU502Zao+I5kE/agbHdeuZzpKwn+tM2f4JP9IN3UanRwO+dG/sukbBvgtvXDLabzf339ieE1AorMe+C9srfoO9n7d4wf32D/7+Agwbjw3xQYByQMD8uEgZoJkBXU9RCByZedVVb4FiyRlroghpnlmWwWMI+h8UtBt6/yeAQb+ME4ge3PManZEiHEcvApUOsX/pD7zoYa7r67gvAFJXGMMYZR9SL1eDpfB4/dTm0VEq80m89fQo6EWJHfaIaKf1y+gDNtAcc)
