### ISSUE TITLE
[Bug Report][3.5.10] OTP input broken - No numbers are accepted by keyboard

### ISSUE THREAD

**Issue by pm-consultancy** [vuetifyjs/vuetify#19439]
### Environment
**Vuetify Version:** 3.5.10
**Last working version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Firefox 124.0
**OS:** Mac OS 10.15

### Steps to reproduce
Just enter a number in version 3.5.10. 

### Expected Behavior
Responding to input

### Actual Behavior
No input. Selected input is cleared when typing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjUsKwjAURbcS7tgk9COixILrMA6qPlRI0kd9CYi4d9NZ4Q4uZ3DO+Yv3fLMnZlMy4QAnFDmMQoNPSrmiJ2H9SpxFBUoPeR49dh4qTncKuowhUyVd2/R1lcuHF5ByvNLsMTi7UlSns6sAfht0pjdtg+VszR6XP/yyLpk=)

**Comment by pm-consultancy** [comment]
The examples on the documentation pages aren't working either.

**Comment by archit-credilio** [comment]
Yes I can confirm the issue is occuring after version update

**Comment by b-maslennikov** [comment]
confirming. Firefox, Edge

**Comment by KaelWD** [comment]
#19345
