### ISSUE TITLE
buttons inside v-card-action unclickable

### ISSUE THREAD

**Issue by JerryCBH** [vuetifyjs/vuetify#1944]
### Steps to reproduce
In a v-toolbar, create a v-menu with v-card and v-card-action containing one or two buttons. Apply CSS class to v-card with the style:
`position: fixed !important;`
v-card is now fixed at a position when menu clicked, However, buttons inside v-card-action can no longer be clicked. This seem to happen in Microsoft Edge and IE 11. Chrome and Firefox works ok.

### Versions
v0.15.7, Microsoft Edge and IE 11.

### What is expected ?
Ideally buttons clickable and functional after the absolute position style is applied.

### What is actually happening ?
Buttons cannot be clicked.

### Reproduction Link
https://codepen.io/anon/pen/NagbBq

**Comment by KaelWD** [comment]
Use `content-class` on the menu instead of giving the card a class directly. This is caused by a quirk in IE where a positioned element must overlap all its parents for clicks to register. 

![image](https://user-images.githubusercontent.com/16421948/31013838-4c73f506-a55b-11e7-933c-b12ab7d375b5.png)

**Comment by JerryCBH** [comment]
Thanks KaelWD, this works great! 

Although for IE 11, I have an extra long menu even after setting left to: `left: initial !important`

![untitled](https://user-images.githubusercontent.com/1642948/31017591-7f4e8c5a-a585-11e7-88b5-473455048d9c.png)

**Comment by KaelWD** [comment]
TIL that IE doesn't support initial http://caniuse.com/#feat=css-initial-value

Does `auto` work instead?

**Comment by JerryCBH** [comment]
`auto` works, thanks!
