### ISSUE TITLE
[Bug Report][3.5.11] Module '"vuetify"' has no exported member 'GlobalComponents'

### ISSUE THREAD

**Issue by pashoo2** [vuetifyjs/vuetify#19448]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Safari 17.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. `import type { GlobalComponents } from 'vuetify'` - import the type either from 'ts' file or 'vue' ts module.

This type may be useful for the following reasons:
1) To derive a type of all component names.
2) As discussed in this issue comment: https://github.com/vuetifyjs/vuetify/pull/16843#issuecomment-1458189844

### Expected Behavior
Imports the `GlobalComponents` type

### Actual Behavior
Typescript shows the error: `"Module '"vuetify"' has no exported member 'GlobalComponents'"`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjs9qwzAMxl9F8yUbLPF9pIOxw/YGOyw7uLFSDPIfbCW0lL77FLeF0IuQPun79Ps9q5JH/ZFSt8yo3lTP6BMZxvchAPRLa1KqbR3GGNi4gPkmVZHxyO3kkCwsrY8WaTcoXw6DAn236kfvqlyje715KWMZs0sMBXlOQCYcJI3LoKrN+RQzwxkyTnCBKUcPjZA3myWfEsrFF8W9oc8oYsDAZXvObjppcnvtgsVjZzvPRSLWEMEsDIIPu/XJc/ONRBF+Yib71LysvFdC4VGX1zAT1fL3D5gkcI8=)

**Comment by KaelWD** [comment]
GlobalComponents is a vue interface

> To derive a type of all component names

`keyof import('vuetify/components')`
