### ISSUE TITLE
[Bug Report][3.5.10] v-autocomplete adds multiple items

### ISSUE THREAD

**Issue by rnenjoy** [vuetifyjs/vuetify#19444]
### Environment
**Vuetify Version:** 3.5.10
**Vue Version:** 3.4.21
**Browsers:** Edge 123.0.0.0
**OS:** Windows 10, Windows

### Steps to reproduce
Write "one" without " and press enter (selected is now 1).
Now write two and press enter. Selected is now 3.

### Expected Behavior
The @update:model-value should only fire once for each select.

### Actual Behavior
@update:model-value Runs twice.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplUstygzAM/BWNL0mmhTR9XBiaaX+glxx6CDkQUKbugO2xRXJg+PcKG+fRXLAt7UqrFdteOFstP41Jjx2KTOSErWlKwnWhAPJjUhrjr/5RaUWlVGinUEB0pCvNLCSMYYBMciX3Xgh/FuKS+ehMzQ2yVtfYJMey6XCCbbDBirC+RlukzqpE7385dQmPTRPn8clBWndOrfPlrSSWGnN9D4GCNQxDvrewXIfvBbMhNA5Ic2PTyIqFgrF632CbRWgAfluWDIXQCgsBJ0k/uiN+Q6lqpqBzgIrQwvzcUzpQ+gSrRRpKffHjNJaJNemk/9NTiK5E+ks67YMHvV2IH93vK19e7ZGfrrLSEE9PXVinbI22BD2PeYABDla3MONfYBac4LpuhE+d30fY/GlxnfR75cw2qOnPM0hqMIMZ+zJ7jEG/5QxWU2CYzjsSG3BHer4h7YKGQ6cqklp5GdGh+SJWjMpTX+PhYYwOoy3BCLZADI/iJX1Nn1divLylqyex+wOrSPbS)

**Comment by KaelWD** [comment]
> Now write two and press enter

Did you press backspace first?

**Comment by rnenjoy** [comment]
> > Now write two and press enter
> 
> Did you press backspace first?

Correct!

one [ENTER]
[backspace] [backspace] [backspace]
two [ENTER]

**Comment by KaelWD** [comment]
Clearing the input emits null.

**Comment by rnenjoy** [comment]
Ok i see. I get what you mean now. Thanks!
