### ISSUE TITLE
[Documentation] VTreeview expand nodes on click and parent nodes cannot be activatable

### ISSUE THREAD

**Issue by pchetelat26** [vuetifyjs/vuetify#19441]
### Environment
**Vuetify Version:** 3.5.10

**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on any nodes in the basic activatable example

### Expected Behavior
- To work like the [Vuetify 2 example](https://v2.vuetifyjs.com/en/components/treeview/#activatable)
  - Node expand only with icon click
  - Node can be activated

### Actual Behavior
- Node expand on click anywhere in the line
- Node cannot be activated

### Reproduction Link
[https://vuetifyjs.com/en/components/treeview/#activatable](https://vuetifyjs.com/en/components/treeview/#activatable)

**Comment by xuxu-1997** [comment]
me too

**Comment by jelle-eastground** [comment]
I encounter the same issue.
