### ISSUE TITLE
[Bug Report][3.5.10] Padding inside v-list-groups was fine in version 3.5.1, but became too excessive between versions 3.5.1 and 3.5.10

### ISSUE THREAD

**Issue by MaxenceMouchard** [vuetifyjs/vuetify#19440]
### Environment
**Vuetify Version:** 3.5.10
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-list with v-list-group sub items and add options like 'slim', 'density compact', 'nav', ...
Switch 3.5.10 to 3.5.1 and and see the padding left increase excessively in
sub items in the 3.5.10. 
It doesn't look very good

### Expected Behavior
Look more compact, like in 3.5.1

### Actual Behavior
Exessive padding left

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVVktv2zAM/iuEL2mB2G2X7RK0Bbquhw3YA+16intQJSZRK1uCJLspivz3UXKcuHntgWHAgASSSIr6+JESPXpJnOVHF8ZkdYXJMDn1WBjFPJ7nJcDNk/R8CoPsXXZyDF43M2CliH+HCH6KYJgQspyAwrEHWXKLzCHgjKNzskb1TMLgzlX3IOkAl9EAQqMrex6U1o9Qo32GidYij5andcqZFcAVc+4sTwqfnryDYpayyus8gScp/JTkg+PjPIlQ4x4lnYeS1eCULEBg6aR/JjOuC8O4p411WmiBaqgNlihIFSZLF0sn6cTqykDNVIVkdOvQuo4V2bU8kUentB+Se1kzry2Zv4Cx2jiYv9qych446MqBnNzLMsCJG/PktdZYJJQilVyXgQwhU8a5rkqfcmm5wvUNXnrVwd1Vnp8edVB0IzrqpL4j3krIhSgopWvR/Qkl+0j5GS2rOBdw1tW/zdtOcnbSsz+p4xj7wSji7EPAcUfDId0HYAHzRkzDRwwFKzfka7GEYcOmpSOOG9o2d1u0e4qim/5fKQzKuQ5h/e3S2KiFVfKXR/7D7HFbif8ueXvErTAuwyI8v7RYI+7UcStNY4Uzoy094zhmlfLw0jgSzLMhHBzC2TkcLGQA4ZUdwqgXH6TeXb+VN5eANCvUo95nVrIJFlj6Xh963Vtb0EHSKEx15ZUsseMpbLxB76kPuXYb15MtlqtZTOLa4ZfUvDy2Hoyq3I7DrpGJ1mwsd2K6NcTI0l/VrF6bfECFKxPqTmG1iXd+GCfzkJRlGpJ+4h2V01hOsgenS2rhkfSm5xEs+9UsrsewTVGeMKX006co87bCxQG0Z4r8cYv8wc2CLE++WaQM1lSBS51ndoLUWoP66uYLzmi+VFKzrUK97lFeo9OqChgbs/dVKQh2xy6i/ViEaqPsfndXMx86+yKoADTyEu3zhL5jLveEvoI7yAYLPumXzPvJIHubvTkhRpvvneTuB7V8uYI=)

**Comment by KaelWD** [comment]
1f63ca88dfb5d5c57331a68d94b1ff660ac989f1
