### ISSUE TITLE
[Bug Report][3.5.11] Card loader prop doesn't work

### ISSUE THREAD

**Issue by gagiD** [vuetifyjs/vuetify#19451]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Firefox 125.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
If we set loader color prop it's ignored, but settings loading as string works.

### Expected Behavior
Loader color to change

### Actual Behavior
Loader is default color

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVzk0KwyAQBeCryGyySQ39WYkN9By1CzFDEYzKVENLyN2bxAaa3bxvMe/dR3iRaW4x8iEjCJAJ++h0wlZ5xuRw0DGu5xpM8Elbj/Sjgpo6lvCdrgo45wqYcEF31j9nSJRxE6QZRmaCCyRYFcn2mj7VpKCVTfmzVS1x17VImSKbv4kw1XDmF346Qu2zc48vlj1C5A==)

**Comment by b-maslennikov** [comment]
https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQRDCxKEWhJLWixDZGSU9PL0ZJISc/MSUzLx3IL0pNiVGys9GHqIIZBOKimAQSgVhko4/kAKVanbzSnBwwEQsAW9M3iQ==

**Comment by b-maslennikov** [comment]
`loader` is a slot. not a prop
