### ISSUE TITLE
[Bug Report][3.5.11] v-switch not accessible by keyboard: enter key doesn't switch between values

### ISSUE THREAD

**Issue by maja-fredstrom** [vuetifyjs/vuetify#19459]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Make a simple v-switch. 
Try to change the value by keyboard

### Expected Behavior
Enter key should change the switch value

### Actual Behavior
Nothing happens 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by miroslavgeorgiev** [comment]
Usually it is done by the space key not by enter key.
And by space key is actually working 👍

**Comment by maja-fredstrom** [comment]
@miroslavgeorgiev Thank you for your input. Yes it is working with space key.
