### ISSUE TITLE
[Feature Request] Adding decimals props to v-number-input to control the decimal length  

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#19450]
### Problem to solve
always display decimals with specific length

### Proposed solution
adding prop for display decimal length

**Comment by yuwu9145** [comment]
This should be handled in mask.

Although #19207 is working in progress, there is a [playground](https://play.vuetifyjs.com/#eNqNVN9v2jAQ/lcs94FOI3ELRZpQitimPmzSfmjrW9MHk1zAxXEs2wlUiP99FztQoGsFQiS5++6777szedhQazL2Weu4qYGOaeKg1JI7mKSKkGRxPfnB7ZInDO98RE9qK9ScNFHZJsYP/vJLO1Ep+0hWlVnahOmufDBBXJWDHJPNhrTQe1g7st0i4SBgmshhKCoEyPwt1o7kNqU7ipQShvUJO9CLjzYzQjtiwdVBgih1ZRzZkMb7IFtSmKokPc/fO0IY4JkTDfTxrtgDcSwIa4EZSnEvHm5b2OVodPPhOLlT7QGB8XLTQohPj0nvIr7wn14/hIHPwYxJwaUFH9oiZcKCl86Xe5YwwZi/por2qbPYsxDz+MlWCjfne6Q0q0otJJhORUpx8qFNSrmU1eq7jzlTh16+ZgHZ8j/xJ7tuYyn9bcCCaSCl+5zjZg64hjZ99/enX8k+iduqJaLfSf4BW8m61RhgX2qVo+wDnFf7zW8HD9y9vVs7UHZnqhXqZ+XxKcU9fX3H+ovcYTz0danCL84x7B/PnT6ZZEgc02CXIHfhnLZjxrJcYRmeTdGYWIFjSpdsijBmauVECVFeldNhfBNff2K5sO4wHoMto5mpVjhcZDnwjgROFM9n9OqQ2GIUD0OHLhRJPrNti1fUzC/TRAZUDqYd+nmWTsqObJ3k3rbm/yNndPS46SCw+4dXPiKhdI2vDp7x/Jy9nJaggav4KpqB4/GIfUTJKT04G9u+qqX0P4//APA/vL4=) using maska where you could further experiment.
