### ISSUE TITLE
[Bug Report][3.5.3] vProgressCircular FPS Leak

### ISSUE THREAD

**Issue by mrfrase3** [vuetifyjs/vuetify#19454]
### Environment
**Vuetify Version:** 3.5.3
**Last working version:** 2.7.2
**Vue Version:** 3.4.18
**Browsers:** Chrome 121.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- add indeterminate to a v-progress-circular (or loading to a button)
- wait a few minutes, ideally with the window visible
- the longer it runs, the worse it gets

### Expected Behavior
indeterminate to run forever without slowing down the page

### Actual Behavior
the "frame rate" of the spinner begins to slow down, the longer it runs, the worse it gets.
- chrome task manager shows 100% CPU usage, with no real increase in memory footprint

![Peek 2024-03-23 11-04](https://github.com/vuetifyjs/vuetify/assets/3320430/26995074-ab0d-4f8e-88b7-4da7f9b9d98b)
![image](https://github.com/vuetifyjs/vuetify/assets/3320430/7c85be27-91a1-46de-b7e0-4834cc18e51b)
![image](https://github.com/vuetifyjs/vuetify/assets/3320430/aec088e0-c82e-4d9d-913a-ddbdacf8aed1)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UcsOwiAQ/BXCWe3d1CY+/sJ6oHTbYOhCYKkxxn+XQJv25sF4gDAzy0xgri/unSyO1u7GAHzPS4LBakFQ1chYOW6lQRIKwSUiUc48mNCqx0PNJSCBqzm7B0+qe66o6cLkollcPsoikFmJSW4IWQvoFSUDM1ghKQ6d84mdApHBskiTi2/E0TTiH5I640g0GnLajP6W2EIngo5vY9qIVmFfXTLzNXFG8fdzN0lZyimLVXX8vcGgddpuH1k5nG0=)

### Other comments
- observed in the latest version of vuetify in the playground
- this does not occur on V2 on my PC
- My computer has Linux, an AMD GPU and 1080p monitor, which differs completely from the previous 2017 report
- performance monitor show the painting as taking a long time, no affect on the GPU
- navigating to another tab appears to reset the framerate, sometimes

**Comment by b-maslennikov** [comment]
Confirmig high CPU usage in Chrome, Edge
And everything looks good in Firefox
