### ISSUE TITLE
[Bug Report][3.5.11] In VNumericInput change buttons erases the manually entered value

### ISSUE THREAD

**Issue by crystalfp** [vuetifyjs/vuetify#19464]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Enter a numeric value in the field
2. Try to increase or decrease the value using the buttons.
3. The value disappears and is changed to the step value

### Expected Behavior
The increase/decrease buttons should act on the entered value increasing or decreasing it.

### Actual Behavior
The manual entered value disappears and the step value appears. Seems like internally the manual entered value is ignored and the value is zero always

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU8Fu2zAM/RVBl2xALCVZezHcoAP2CcMu0w52zCwaJFmQaK9DkH8fZSuJkx7ankzxPfHxkdbPI49hJ4ceUO//iT+Rl1xb3wVkR7YLUCP8mDB2YvvQWbbI3IVyF6JtN/ewbEwPPmiHkZjKwcvI3XUuIssc9nQr8emoHGN4AAslG2PGWtjXvcHvU3Jh9O8DLpapYkKlTN8TnRm7CJapH0qdPivHl6O/r94LEiVzFYL1hjS36U41FNQR1tpBGBNjKnR/8yEzDPVt4pPi643iVJ2iBwqinYILmeiHx+23qeVKUnxuNJdyvW0gFNr5Hq8AS2PB0JliqIOuHVLZ7FvxOa2MCJ7AlVitVus5tq3kbfWrAQKo+7M7Op3tTcjVfSVns6HBTestbO3pv+gcDW/cicpAVPyyJcVpuums+AHRx1LKXevoWgtGD0E4QOm8lc9Ek6F3qC0UbWefv4gHsVnLVkec5wVEWzTUaIRAVRQfN5x10q/yDq3MJIlHsc4SOVeYuolJ41VtSYIDzTCAayFAeK+nu2s3vu6wN73Nns7HbRrdzO5LTZovwiaZ8aXQq6DdnpZ8apAvXW/Mr//k7lTp)

**Comment by yuwu9145** [comment]
Duplicates #19442
