### ISSUE TITLE
[Bug Report][3.5.11] v-tabs render vertical scrollbar on empty page ( Google Chrome )

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#19468]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Only use v-tabs in the root template

```html
<template>
  <v-tabs bg-color="primary" />
</template>
```

### Expected Behavior
I would not expect a vertical scrollbar

### Actual Behavior
There is a vertical scrollbar

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTLUlMKlZIStdNzs/JL7KNUSooysxNLKqMUVLQByqx0UdSr1Srk1eakwMmYgF6wx9Y)

### Other comments
Everything is fine in Firefox. But I can reproduce this in Google Chrome

**Comment by b-maslennikov** [comment]
does not seem like it's component related issue (?)
I see the same behaviour for each playground link... [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptUctugzAQ/BVrz5gkoj2U0kpVz+0PhBxccMimxlj2QoMQ/17zqMOhJ2tnZ2c8u8cB3oyJu1ZCChnJ2ihB8jXXjGUdV6JvWmKFEs695GCbVpeyZOvL6zKHmTqTteiwEoSN5qUVP9KurUUJHYU6IBy9IyMkJb38ZxBgi4BXz3Yb5l1wRf/Mffmfe/iaMIZ/CRucfGSFxWLl8dVnZW0Ha4E6xC/5WckbEworzQupSVp2bR3huV/LHJijfraoUfOLxOpCKUv2e3N7Drti7GOSfW/8iKZ7hMls2fwUb169L7NduApEoFB/u/jqGu3vNeRQOJdDejyNvoe1aSx5GbMhLOBEGsYRxgiS+CE+PHl6Ej/GhwQisq08/QKH1aqJ)

have you tried your code
