### ISSUE TITLE
[Documentation] Wrong `color` documentation for CSS example colors

### ISSUE THREAD

**Issue by ItsPierre** [vuetifyjs/vuetify#19469]
### Environment

**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See documentation of the `color` property of [some components](https://github.com/search?q=repo%3Avuetifyjs%2Fvuetify+%22or+css+color+%28for+example%22&type=code).

### Expected Behavior
The examples for css colors should be a css color like `green` or `purple`.

Alternatively tbe documentation should only be: `supports utility colors (for example `success` or `purple`) or css color (`#033` or `rgba(255, 0, 0, 0.5)`).`

### Actual Behavior
The examples for css colors are `success`, which does not exist as css color.

### Reproduction Link
https://github.com/search?q=repo%3Avuetifyjs%2Fvuetify+%22or+css+color+%28for+example%22&type=code
[https://vuetifyjs.com/en/api/v-card/#props-color](https://vuetifyjs.com/en/api/v-card/#props-color)

**Comment by jojomatik** [comment]
I'll take a look tomorrow

**Comment by johnleider** [comment]
When we say CSS color, we are referring to the colors supplied by the color pack.
