### ISSUE TITLE
[Feature Request] Edit combobox selection

### ISSUE THREAD

**Issue by clevel21** [vuetifyjs/vuetify#19466]
### Problem to solve
When going back on a combobox that is used to select an address from an API or directly from user input, it is not possible to edit the selection once it's done.
I have to clear it completely and then search again, but I would like to just be able to add or remove some letters in the middle.

### Proposed solution
It would be great to have something that put the selection in editable mode, like when we first input text.

**Comment by yuwu9145** [comment]
Do you mean you want to partially a selected item when multiple is applied?

In single mode, it works as you described
