### ISSUE TITLE
[Feature Request] Vsparkline labels are not readable when too much data points

### ISSUE THREAD

**Issue by pokecheater** [vuetifyjs/vuetify#19474]
### Problem to solve
Too much data inside a list (30 date labels are already enough)

PS: I wanted to add an image, but that seems not not possible with this form.

<img width="1150" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/20928617/dc0e453a-1a33-4d6c-ad09-0d9fb5d143f9">

### Proposed solution
Either support vertical alignment xor support auto hide of too much in between content.

Also a nice feature would be that when hovering over the sparkline the datapoints are shown as a label (x and y values)

**Comment by pokecheater** [comment]
PS: For vertical alginment all you need to do is: apply:     writing-mode: vertical-rl; css style on the text attributes.

**Comment by pokecheater** [comment]
Another problem: the y axis values are not shown. Can't use it as a diagram in this condition.

**Comment by johnleider** [comment]
What are you asking for specifically? Seems like you have multiple things. Can you consolidate please?
