### ISSUE TITLE
[Bug Report][3.5.11] VTreeView not working with a key 'type' in items

### ISSUE THREAD

**Issue by pm-consultancy** [vuetifyjs/vuetify#19476]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Firefox 124.0
**OS:** Mac OS 10.15

### Steps to reproduce
as you can see `items` work because of the lack of a `type` key in the items

### Expected Behavior
a message that an illegal key has been used

### Actual Behavior
no message or nothing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFUsFuGjEQ/RXLF1qJ3S3QXlYkShvl0B7aKu0ty2GzO4BTr23Zs0CE+PeO7YUsEEVIPVRCrP3mzcx743nYcmer7LMx6aoFnvMpQmNkiXBdKMamq6Q0JhzDpdIKS6HAdlAA0QKsBKxZLijZXRU8fAt+Pc1eohdkjF9P8dBxY49EXdOsp5eurrLCIHOAbZQtGqMtsi2zMGc7Nre6YQOyOvB0xqiuQxa6syvPefcQm273ckWdsw/D/Q0FSsjZ4F5rHBzQailkbUHlrMsOFULqaHjIufWs0YDtDnl70viENO6TZt0pIrP3Z8LH/6Acn40H7f+0M83iq9F78SFHR9bmYpE+Oa1oIYOdgle6MUKC/WFQkPWC53ujBS+l1OtvAUPbQteAcpZQ/XkFf3IbjxX8pwUHdgUFP8SwtAvAGL779R02dD4EG123kthvBO/Badl6jZH2pVU1ye7xgtqvYS2FWvx2dxsE5famvFDPjOMpOK3q7RvWX+RO0knIKxT9aI5x8ZOmNCeTjIHjMtQlyl0iGpdnWVUrSqtBipVNFWCmTJPdEC2zrULRQFLr5maSfkzHo6wWDvt4Cq5JHq1e03CpSs87FUAxf76gV8ekFp/SUdeiwxJZPjrf46x2Fl7TJrS7NVg/9cs8naQd+TqJnXnrDX03VK2U4W/2F4gnshs=)

**Comment by simon-lorenz** [comment]
I also ran into this. A warning message would've been nice.

**Comment by b-maslennikov** [comment]
same here
