### ISSUE TITLE
[Bug Report][3.5.11] VTreeView active-strategy="single-independent" attribute not in effect

### ISSUE THREAD

**Issue by xuxu-1997** [vuetifyjs/vuetify#19472]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.3.2
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
ex

### Expected Behavior
Can take effect

### Actual Behavior
Not effective

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vstu2zAQ/JWFLk4Aq67cPBrBMeC2l17aS9Ee4hwoch0ToEiVougYgf+9lGRFVCw/0qYX2aQ4M+Tuzop3T0Gu6WiWZe9sgUEcTAymmSAGp3MJMLGh0YiW46ocAsTcvc9v50H1Ow/qWUINt8SQRKA3gWFutGN6WLv1OZcPAkMuGWboHtLU4Olk1Go4zcnI24Ab5lTzzFSbwcdMaQMMF6QQBp5qKeZ0Yzg7h9spnG3nAKrtxXDXjKFZvn3NYoiG/ozhRmAMAxcJwSkxXMkc4kFnDV1ywTTKDm/FXRGOh88sn4lwhyQaYiBZNoBNh6cBfPAAS61SPLz8ol3+C5PcKJ32A+69kf9mJwSXvSH4omiRugS94vzdYU1+9eIQrYCrNMMX65f0ByV6ZRqp6x0eX84VeJ/UUbk28h/byJcF/OjCbvLdNHVBNy0oUcqUXsgOAv209aWvf9VOrfTlInq/Nxmps5rmRIzfLh1R11pvn4/Is5oNEyNPSkjk+c2GlGh2GszznQ1XrgDU6r/n8WQLR/s8vJJCEfbaHhZdtYf9To1KsOxhGVvsa0rRdQv4piymxxGem34Urou54nOIpUnFXzey6KY3Cj85Q/WPbWy83zrN7ncUjlunpo7aSHwiOacgyFoVZeOFNLvor68t1HPAjFkiKTIwSJeS/y7wFALPDDMhgCROuPyYOCjjug96tPPUxJ5dvkqjVbkXZfdVw/jS+wgquUAXMorASyQr3DVCleYmlp9WG83s5rz6sykvFM9XiGAzlIUQ1eP+D+NMNSM=)

**Comment by Jeast85** [comment]
Yes I have found the same. No matter the activation strategy, it will never return a node if it has children. The active-color does affect a parent node. Its just that parent nodes will not be returned in the activated array.

**Comment by xuxu-1997** [comment]
how to do?
