### ISSUE TITLE
Buttons change color when used as vue-router link (.btn--active)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#1947]
I am not really sure if this should be filed as a bug or feature request.

Create a Vue app using `vue-router`.
Add a `v-btn` with a `to` prop
When clicked, the button style (color) changes because the `.router-link-exact-active` and `.btn--active` classes are added

I understand this happens because it uses a router-link underneath,, but in my opinion buttons should revert to their initial state after they have been clicked. For example in my app I have a FAB that opens a  panel (and navigates to a different route), and the color of the FAB is different depending on whether the panel is open or not which looks a bit strange.

It seems that passing an empty string for the `activeClass` prop prevents the class from being added. Just wondering if this could be handled in a better way?

A simple example:
https://codepen.io/anon/pen/aLwWzp

What do you think?

**Comment by johnleider** [comment]
This is a very specific example, and luckily, you do have an option! Just specify **active-class** as nothing.

https://codepen.io/johnjleider/pen/RLgYqL?editors=1010
