### ISSUE TITLE
[Bug Report][3.5.11] VTreeview selection not working

### ISSUE THREAD

**Issue by d-schoenfeld** [vuetifyjs/vuetify#19471]
### Environment
**Vuetify Version:** 3.5.11
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See the playground

### Expected Behavior
Selected items should be exposed in v-model or in v-model:selected

### Actual Behavior
v-model and v-model:selected stays an empty array

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9VMtu2zAQ/JUte3ACWDIcJwEqOAaKHnrroe3N9oGW1g0TmhQoWmkg6N9LUg+SthoebHF2dji7XGnbkK9lmdZnJBlZazyVnGrc7ATAuk5yKTRlApUDHFQhx1x3W4A6OckC+dOOdDiT4vd7iTsyEDJmNCsT38440uNsDjMmCizR/Ag923smpwcn9GsQAh0obdaL4WzvRcm3ftO75ePWAVoh1gzfPDjp2HuIHLv/i9iYk1hz/y/bLmmKTCjnIaZQn5VI5OElaKJdnQ49cPSoq3mowRdqwLBSU2fBalagghqVZjnlLrEHLxrk1XNOK1tmSZPH0LghWTjAwqYOE2L6yI6G9mlsQMpR/NHPOxLQAX5IEKbfVV8gFmkgtojm7foE5FUYMkFTVLi313mUyviwhwAT/TFXl2qu7hXfe17KijganQHQNM5zKugJoW0jAwvjIHR7XUJ8P3Y3jGkX8W9UlGy2Va5Y2Y03/i2l0lDgkZ65hqYTK6imGdzcwtMGbnpsGJ1+BDPo37OraAbb/Yi62TaIr2SUc+Eig+VItkszza34Tym1F3fz8sx4odDqX7TRydzNx9xvlgmflzNoI4WBurqi3k1Q423n9f6C5P32QqvY84e+vaEHb+i7oqJwKZMF+JzH6ZyJSgD8fXQrZoRRHxnQ9tY9mOlcL/rBIXPCmXit0pdKCvM5b3Ykr8wXLNvuWxNjJztTyYmWAaEDLalpW9LOySq9T5dfDH2VPqTLJZlrdcb9P0gds24=)

### Other comments
All features that are dependent on selection do not work.

**Comment by angrymarker** [comment]
+1

**Comment by ryan-gusti** [comment]
+1

**Comment by benlavalley** [comment]
I tried using the "selected" parameter too, no dice. I love Vuetify and wish I had the time to dig into it's internals myself. 

https://play.vuetifyjs.com/#eNqVU02P0zAQ/StDOHRXalq1C3uIupUQB24cgFvbgxtPWYNrR46bZRXlvzN24jhpAwhL+fCbmTfPM+NdnZQmX34oikV1wSRLNhbPhWQWt3sFsKnSXCvLhELjAQ+VKDG37RagSs+ao3zaJy0utPr2WuA+CQ6ZIM6S7LuZRHaazWEmFMcC6aXs7BA9JTt6oq+BCOyAabtZhtxRi9Ev3aZTK4Eel2213ifb4AI9ZQZ13QttGnCkzsN9KfI/yJBHLuT/pOq3HrAGsRL4EsHJSsba+EqGZL0L8iuPUGv/nYwm1tSV9c8Nc0tTe1Im5RAzaC9Gpfr4Y9B+t1oedpQYUV+FcMpYitvScFEJjgYqNFbkTPrADrzphmSlO13B0sd9EppDv8PihgmmeooTmd/0x1xIVN/ts2vlZw2Kil122pEvSNto9m/ZUJZDExlJJuEnbSiNowOhOkLfO8h+4mtnWghq1baufdqFYmeEptksiWGY7VbCuGJhxPzl9JZ4O0fBtC1zI4r2quCvQhsLHE/sIi3ULRlnlmVwdw9PW7jrsNDMbigy6O7s2OpGf3e4Av3lGqB+BAmJx+tzeDNxrHpnt6yw0mX8orWNGd3Kn4XkBh3/ECZGT7Oe97EfnSe8Xc2gGTEE14cb1/WE63jban135RT1dkQPY81/1R0FvY+CPhmmuA+ZPECMeZyOmTgJQOxHu8YeQ2u0BLS59z+Nm61+mpJmri5S+tfhNw47zEA=

**Comment by cleemansen** [comment]
This does not work (again?) in vuetify 3.6.13: [playground](https://play.vuetifyjs.com/#eNp9VE2P2jAQ/StT98CuRIKALZUiFqnqobce2t6Ag0mGrneNHTkm21WU/17b+bAN7PoA8Zs3z2/Gk2wb8q0s0/qMJCNrjaeSU42bnQBY10kuhaZMoHKAgyrkmOtuC1AnJ1kgf9yRDmdS/HkrcUcGQsaMZmXi2wlHepxMYcJEgSWaH6Ene8/k9OCEfg9CoAOlzXo2nO29KPnab3q3fNw6QCvEmuGrB2869h4ix+7/IjbmJNbc+2XbJU2RCeU8xBTqsxKJPDwHTbSr06EHjh51NQ81+EINGFZq6ixYzQpUUKPSLKfcJfbgRYO8es5pZcssabIKjRuShQMsbOowIaaP7Ghon8YGpBzFX/20IwEd4KcEYfpd9QVikQZis2jerk9AXoUhEzRFhXt7nUepjA97CDDRH3N1qebqXvCt56WsiKPRGQBN4zyngp4Q2jYyMDMOQrfXJcT3Y3fDmHYR/0ZFyWZb5YqV3Xjjv1IqDQUe6ZlraDqxgmqawd09PG7grseG0elHMIP+PbuKZrDdj6ibbYP4SkY5Fy4ymI9kuzTT3Ir/klJ7cTcvT4wXCq3+RRudzGI65n63TPg8n0AbKQzU5RV1cYMabzuvDxck77cXWsaeP/TtDX3xhn4oKgqXcrMAn7O6nXOjEgB/H92KGWHURwa0vXcPZjrXs35wyJRwJl6q9LmSwnzOmx3JK/MFy7b71sTYyc5UcqJlQOhAS2ralrRTskwf0sVXQ1+mq3S+JFOtzrj/D0gos3A=)

**Comment by yuwu9145** [comment]
> This does not work (again?) in vuetify 3.6.13: [playground](https://play.vuetifyjs.com/#eNp9VE2P2jAQ/StT98CuRIKALZUiFqnqobce2t6Ag0mGrneNHTkm21WU/17b+bAN7PoA8Zs3z2/Gk2wb8q0s0/qMJCNrjaeSU42bnQBY10kuhaZMoHKAgyrkmOtuC1AnJ1kgf9yRDmdS/HkrcUcGQsaMZmXi2wlHepxMYcJEgSWaH6Ene8/k9OCEfg9CoAOlzXo2nO29KPnab3q3fNw6QCvEmuGrB2869h4ix+7/IjbmJNbc+2XbJU2RCeU8xBTqsxKJPDwHTbSr06EHjh51NQ81+EINGFZq6ixYzQpUUKPSLKfcJfbgRYO8es5pZcssabIKjRuShQMsbOowIaaP7Ghon8YGpBzFX/20IwEd4KcEYfpd9QVikQZis2jerk9AXoUhEzRFhXt7nUepjA97CDDRH3N1qebqXvCt56WsiKPRGQBN4zyngp4Q2jYyMDMOQrfXJcT3Y3fDmHYR/0ZFyWZb5YqV3Xjjv1IqDQUe6ZlraDqxgmqawd09PG7grseG0elHMIP+PbuKZrDdj6ibbYP4SkY5Fy4ymI9kuzTT3Ir/klJ7cTcvT4wXCq3+RRudzGI65n63TPg8n0AbKQzU5RV1cYMabzuvDxck77cXWsaeP/TtDX3xhn4oKgqXcrMAn7O6nXOjEgB/H92KGWHURwa0vXcPZjrXs35wyJRwJl6q9LmSwnzOmx3JK/MFy7b71sTYyc5UcqJlQOhAS2ralrRTskwf0sVXQ1+mq3S+JFOtzrj/D0gos3A=)

- `return-object` doesn't work on master branch yet, but fixed on dev branch #20038
-  `selection-type` -> `select-strategy`
- `item-value="id"`

The example attached in playground is actually the v2 version, the proper v3 example is also dev branch now

https://play.vuetifyjs.com/#eNp9UsFu2zAM/RXOO7gFYgdpthyMNMCww247bLslOagW0wpTZENW3BWB/32UZFtWklaHxHyPfHqkuD0njS7n3+o6b0+YFMna4LGWzOBmpwDWbVZWyjChUDvAQQ1KLI0PAdrsWHGUj7vE46JSf95q3CVDQiFIsyF+m0pkh3QGqVAca6QfZdJ9yJTsyQn9HoTATJQ26/lwd/Ciq9c+6N3KMXSA0YitwNcAjo4Lr4V8aj2Yiay7/5izUNYyeULL84tCL5g1RtMsn9/en449nmJPEgPquh3chxYJnPZIHXLRCo4aWtRGlEy6wh68GA2UkjW2nZplq10CBNmIPqdDGzaA5iQORH8anecS1bN5oXT4WYGiITa9d+Q5eYt251oNZTOliCSbhB8qTddYORCqF3RPAcVftKOzVG5HvDmf3bW5YkeErlvPSWF627WFeGI2GlbGM2G7o2IKm1KL2q8a/qsrbYDjgZ2kgbMX48ywAu7u4XEDdz02PGb/zgX0O3/FFrDdj6hbL0JCJ6Oco3kBizHZHiOMtOK/qsoEcXvKFyG5Rqs/hUnRyTzMxtrvNhM+L1LoIoUhdXmV+nAjNQ691y8XScFvL7SMPX/oOxj6Ggz90ExxV3KzgVCzul1zoxOA8B7+xBlTNjAD2t27j86u0bg4STdTJylnyTJf5Ytlsv8PnX2KPQ==
