### ISSUE TITLE
[Bug Report][3.5.9] Why does the VSelect document have a item-children attribute but it doesn't work if it doesn't work why put it there

### ISSUE THREAD

**Issue by universeK** [vuetifyjs/vuetify#19470]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
VPlay

### Expected Behavior
Work like VList-itemChildren

### Actual Behavior
no work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1j81qwzAQhF9l0MUtJHV7NU6gzxH7YNQNFciykNa+GL979GOFBJKLtPuxOztzWYV3sv619muZSTSiZRqtHpjOnQHa5ThYm8rUyMnwoAy5HSXoSZNkNCqs+lMn0t8JxP8o/5X+c2QCL2UnzmjrslfEA3hWjyQfb+sHU6H10inL8MRz9qZGOznGCkdXbLi6aUQV8lRxHAi6npMdj1Oc+bjko2tJwYo1Nah+qkNBy6DngL7voNhvsG8/KbxReakEbPe636tM+s+YNucLycR2MLPW6elvPv6B8g==)

**Comment by De-Hann** [comment]
Hey, I can't seem to find this attribute you are talking about. Can you link some documentation or code snippets where this attribute is defined? Does not seem ```VSelect``` supports this ```item-children``` prop.

**Comment by d-schoenfeld** [comment]
@De-Hann https://vuetifyjs.com/en/api/v-select/#props-item-children

**Comment by johnleider** [comment]
I'll update the description. The property currently has no effect on select components. It works on `v-list` because it's designed to support it. It shows up as available because `v-select` uses the `items` composable.

**Comment by UglyHobbitFeet** [comment]
FWIW I did the following workaround to select from a nested list. Hopefully it will help somebody

```
           <v-select :items="mainItems" v-model="singleSelection">
              <template v-slot:item="{ props, item }">
                <v-list lines="one" select-strategy="classic">
                  <v-list-subheader>{{ item.raw.mainItemLabel }}</v-list-subheader>
                  <v-list-item :value="`nestedList${index}`"  v-for="(subItem, index) in item.raw.subItems" :key="index">
                    <v-list-item-title @click.stop="()=> setSelect(item.raw.mainItemId, subItem.name)">{{subItem.name}}</v-list-item-title>
                  </v-list-item>
                </v-list>
              </template>
            </v-select>
```
```
<script lang="ts" setup>
           const singleSelection: Ref<string | null> = ref(null);
           const mainItems: Ref<SomeCustomObject[]> = ref([{
               mainItemId: 'someId',
               mainItemLabel: 'foo',
               subItems: [{
                 name: 'bar'
               }, {
                 name: 'baz'
               }]
           }]);

           function setSelect(mainId: string, subItemName: string): void {
              // Force the select box to display the selected item
              singleSelection.value = subItemName;

              // Do whatever custom things you need to with the values
              console.log(mainId, subItemName);
           }
</script>
```
