### ISSUE TITLE
[Bug Report][3.5.6] file-inputs not working on Chrome

### ISSUE THREAD

**Issue by makerovski** [vuetifyjs/vuetify#19489]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.5
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click in the file input field

### Expected Behavior
Open file select dialog

### Actual Behavior
Nothing happens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjkEOgjAQRa9CZg0liC4klcSNl6AsKpSkWsqEtmxI724pmuBu5s3Ln9+scEckixNQAbViRMWtqJlOErpkHDGOcekmbbnUYv6iCAepRCY1Opso/hTqxuARUBIRg5rmR+cXFuB/2kb2ZzQ/lHC6F0OQekhBSf025GUmHZquDDpjGFRN68NNjjjNNhs5HoQdbtLqPfgUSnImxTXoJbmQ4gSpnZ1oPwLGVCE=)

### Other comments
Dialog to select files simply does not open on Google Chrome, I also used the latest version from Vuetify and the same happens, also in the Vuetify playground it does not work.

no logs or erros are shown on console

**Comment by d-schoenfeld** [comment]
I cannot confirm this. The Playground works as intended with Mac OS 13.3, Chrome 123, Vue 3.4.5 and Vuetify 3.5.6, even with the latest versions.

**Comment by makerovski** [comment]
I just tested with Chrome 123 and it worked again. Some of our developers have many other issues with Chrome 122, I think that explains already what is happening. But since many users still using 122 I would look at this Problem more deeply.

Thank you very much.

**Comment by KaelWD** [comment]
If it's a chrome bug there isn't really anything we can do about it.

**Comment by userquin** [comment]
Using the reproduction with 123 just works (after an inital delay: using `@use`  instead `@forward`)
