### ISSUE TITLE
[Bug Report][3.5.12] VList Slots not working

### ISSUE THREAD

**Issue by Husky-70** [vuetifyjs/vuetify#19485]
### Environment
**Vuetify Version:** 3.5.12
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Build & run the project

### Expected Behavior
Item added to slot e.g. <v-btn> inside <template #append> should make the button show at the end of the list

### Actual Behavior
Content added inside <template #append> seems to be ignored

### Reproduction Link
[https://github.com/Husky-70/vuetify-3-list-slot-test](https://github.com/Husky-70/vuetify-3-list-slot-test)

**Comment by b-maslennikov** [comment]
use playground to share your code...
[https://play.vuetifyjs.com/#eNqNUssKwjAQ/JWwXrWhVi9SA36H9RDbgIGYhibtRfx386wEQXLJzA472WV3ry/QU48vSlXLzOAErWFPJahhpJMItcuOKuWpD/pRGsolm6LkRcG1WWOrpB/QxnAjGPEv0mI0Lc5+/8nX8z1YEilyPRgdbEcBSutE08qKfGpiismBRCzy2Pk5S4Aix8AX7nqLWOThlhL3/MkOm9r5LD/dcwceO0Bp4FZK1Kr4u2ac7dmF+S04JZxKVhzeW2iqQ7WvwZFjVTdw+wBGsc3V](https://play.vuetifyjs.com/#...)

**Comment by blalan05** [comment]
When items are passed, the slots work just fine.

https://play.vuetifyjs.com/#eNqNkcEOgyAMhl+FsKubd8NM9hzqgWmTkTBspHoxvvsQ0IQsJhzgb5t+tOFvVm6nvnwhPpYZeMUFwRe1JKhbw5hY7hLRhz7pR0NSGZhiyRe1ssQq5UD7bHmzbgULp2v52ec6j5fZjRRpqP3NrB5JlMnUv347vwNyBFnUB+TgNg2SOydCZ5TF4QQIZqijZjHuX3ckSBYxqEXtu0W9YkQZLDlcc2lq214JriY03woza+2v7gfOE7Ke

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Husky-70** [comment]
> When items are passed, the slots work just fine.
> 
> https://play.vuetifyjs.com/#eNqNkcEOgyAMhl+FsKubd8NM9hzqgWmTkTBspHoxvvsQ0IQsJhzgb5t+tOFvVm6nvnwhPpYZeMUFwRe1JKhbw5hY7hLRhz7pR0NSGZhiyRe1ssQq5UD7bHmzbgULp2v52ec6j5fZjRRpqP3NrB5JlMnUv347vwNyBFnUB+TgNg2SOydCZ5TF4QQIZqijZjHuX3ckSBYxqEXtu0W9YkQZLDlcc2lq214JriY03woza+2v7gfOE7Ke
> 
> If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

I apologize for the misunderstanding, I actually thought, the slots are for the list itself, not the items...
