### ISSUE TITLE
Fill height with toolbar overflow remaining space

### ISSUE THREAD

**Issue by stecapra** [vuetifyjs/vuetify#1948]
### Steps to reproduce
-create a simple app with this template
```
<div id="app">
  <v-app id="inspire">
    <v-card height="200px" class="pa-0">
			<v-toolbar dense class="primary">
				<v-toolbar-title>Title</v-toolbar-title>
			</v-toolbar>
			<v-container fluid fill-height class="red">
				<v-layout>
					<v-flex d-flex justify-center align-center class="text-xs-center">
						<v-progress-circular indeterminate :size="20" :width="4"></v-progress-circular>
					</v-flex>
				</v-layout>
			</v-container>
		</v-card>
    <v-btn>add</v-btn>
  </v-app>
</div>
```

### Versions
-vuetify 0.15.7

### What is expected ?
`v-container` should fill the remaning height of the `v-card` component and not overflow it and go beyond the `v-btn`

### What is actually happening ?
`v-container` overflow the `v-card` space and go beyond `v-btn`. It's clearly because of the toolbar, because if i remove the toolbar everything works fine, but, even inserting the toolbar in a `v-card-title` and the `v-content` inside a `v-card-text` the behavior is the same.

### Reproduction Link
https://codepen.io/stecapra/pen/KXmbwG

**Comment by KaelWD** [comment]
Just needs some more wrappers: https://codepen.io/anon/pen/mBwMrm?editors=1000

This is some more css fuckery that we can't fix without setting pretty much everything to `display: flex`
