### ISSUE TITLE
[Bug Report][3.5.13] VTreeview with return-object still returns item keys

### ISSUE THREAD

**Issue by jelle-eastground** [vuetifyjs/vuetify#19499]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Firefox 124.0
**OS:** Windows 10

### Steps to reproduce
Open/activate/select items in the tree, the corresponding arrays only contain item keys, not the item objects.

### Expected Behavior
Arrays with item objects

### Actual Behavior
Arrays with item keys

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU7FugzAQ/ZUTS1opBLVpF0QiRZ06dejQIcngwKVxZWxkDFWF+PceOAZTJVUm7HfvPT98520TlDqNNkWxqCsM4iAxmBeCGVzvJEBSh6wo+mW/SZU0jEvUZ4jAjNfrtwIlZjE0Dah++UouJbRtEnXlCXeTGl6Tv6Uzt/tH8Y4CUycoz5sr/Do0GrHm+O0ggJh33NUu6L+7YKzUYa4yFLENTQwv/SXekJao0+SX2C4qkSepfe7ZhR0EjqBlT7GeiGFpNJ35+dP9jcyQ4mYoje9oxTcQNZpKy1Advojv4HUSjVfo+k7QtPEdYuciibx5oW2Zal4YCmEqOzY8L5Q20NBxR2jhqFUOMxq1WUcHIN/SQN8YWMHWHti4NDUTFcbwMHeA4UYQMKN5FTxlhpN8NlSPSlHtwPQIpScuMo0ydt69vzN+nA+OL0zQFXVSzwbawchTLT3Vif4Hb9A8jZoPPJRG6fyaan9eWWQ/3pL/tFbdfd5t9/dj+c9TusCYvh2PkES2b9SxoJ3LSoh5sFw8Lx6Wwf4XBGlO1A==)

**Comment by Youfka** [comment]
are there any plans to fix this issue? or any ways to overcome it? I really need this to work

**Comment by angrymarker** [comment]
Looks like team is aware
https://github.com/vuetifyjs/vuetify/issues/19533#issuecomment-2124555585

**Comment by yuwu9145** [comment]
Fixed in v3.7+ https://github.com/vuetifyjs/vuetify/releases/tag/v3.6.13-3.7.0-beta.0.0
