### ISSUE TITLE
[Bug Report][3.5.12] [Bug Report][3.5.12] VNumberInput: resets entered with keyboard value on component blur when use step props like a float 0.1

### ISSUE THREAD

**Issue by rexchungsf** [vuetifyjs/vuetify#19494]
### Environment
**Vuetify Version:** 3.5.12
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
enter number value using keyboard
click outside of component

### Expected Behavior
a float value should stay the same  like int

### Actual Behavior
component resets value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkM1OwzAQhF9l8SUgkQauUVqJG7wAHAgHN9mApfWP1nYuVd8d26E0kXqxvLOjGfv7PAnPQ/Pi3G6OKFrRBdSOZMBDbwC6uZbOlWsZBmuCVAb5TyqiifqIXCvjYrjIAC3jjOxx34tJksdeXHc5hi29S1bShOQYcZKRwtrT+oAurZ52z2uZ5BEpyRvrjxrxLdffKmuV8XhzM//3e0u2nhQRjlfDoWu2n7twSPIWRFYWTl2z4pdGP7ByAdID4oJRaWc5wAkYJzjDxFZDldBX2V7I+ADaf8M+O+6rVySy8GGZxrvqIRcskSlMnB9NJCrH1y8u0JCN)

**Comment by coderkatze** [comment]
I also experience this and another related problem with the VNumberInput, and extended on the reproduction https://play.vuetifyjs.com/#eNptkctuhDAMRX/FYjNTqUAfO8SM2mU/oN2ULjJg2kgmifJgg/j3OqF0QJoNIvfYvn58TpmzbflqTDEGzKqs9jgYEh7PjQKox1wYk37To9XKC6nQ/klJVGG4oM2lMsGvMsCYD7pDOjUZ8ya7gsriiNYhk16Qwy2L9a2mD2GlUJ4jOuxFIL/Ldx4No4ficSuTuCS3XeiP7PAt9nXLrJLK4U0y/vs7TTrvJRF224CXYDreUZVGzEdBIY6j1XuSr5HnutzvZ10ly/tdRmVZdV1uTsBP11ppPHCrYbmEHIy2Hiaw2MMMvdUDHPh6hwi5qvOwdgInnoXgdIZpMY5YExakv49M7qI6R5s1k5vlJK58fCqeGdfl4s/O2XyvAlH6fP0CHPKzjw==

There you can see, when using the increment/decrement buttons that the @update:model-value event is - I assume - only fired when the parseInt result of the value changes to a different integer (clicking until 3 is put out in the console, then decrement by 0,1 and it gives a value of 2 again)
