### ISSUE TITLE
modal__container 20px when closed (9.0 dev)

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#195]
I reported this earlier, just a reminder, I'm seeing that extra 20px for closed modals.  

You mentioned it was because of line-height or something.

Thanks.

![image](https://cloud.githubusercontent.com/assets/287137/23823338/234a2b22-0615-11e7-89c7-c49545ca4571.png)

**Comment by johnleider** [comment]
Will need some repro steps, this is fixed on dev, at least as far as I can tell.
