### ISSUE TITLE
[Bug Report][3.5.13] v-data-table progress and loading text defaults to 0 colspan

### ISSUE THREAD

**Issue by AwziNihilist** [vuetifyjs/vuetify#19507]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Firefox 121.0
**OS:** Linux x86_64

### Steps to reproduce
When `headers` prop is not provided to the `v-data-table-server` but instead injected via the `headers` slot, the loading progress bar and loading text only span the first column. 

### Expected Behavior
Loading progress bar and loading text span the whole table.

### Actual Behavior
Loading progress bar and loading text span only the first column.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UEsOgjAQvUpTt2KjS1ObeA5xMcJEmtTStIUN4e4ORRQCbtp5n7503q3jwRfi6tyhbZCfuYz4cgYiqtwyJtsMnEtjAkVtI2iL/kMlsoQIWYSHwSygb9EzU0Op7fNrItsUy3YVQok+zMRB/iVOTKVGJztKQeCvfFrJRMzjCM53Wn1I03jJeTfcfc7V1gMpNvaceiFtWczAjL0togiGwmsXWcDYOCXFCEni/d42xqTj/gavbXwC)

### Other comments
This is because the colspan on `<th>` is set to 0 (same goes for the text with `<td>`). `colspan` should be set to `100%` instead when the headers are not provided.

**Comment by blalan05** [comment]
You could `:headers="[{}, {}]"` with using blank objects for as many columns as you need. Per spec, 100% is not a valid value for colspan, and may have unintended side-effects in some browsers.
