### ISSUE TITLE
[Bug Report][3.5.13] VTimePicker ends drag on area-leave

### ISSUE THREAD

**Issue by KIDS-interactive** [vuetifyjs/vuetify#19508]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
Start to drag and leave the clock on dragging

### Expected Behavior
it should be possible to change the clock-input while dragging outside - just check if the pointerdown-event starts in the clock itself

### Actual Behavior
the input stops if i leave to clock on drag
![v-time-picker-drag](https://github.com/vuetifyjs/vuetify/assets/75635412/70504fc7-a613-4e0c-8a74-1602b4b4ee72)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdT8sKwjAQ/JU1lypYc5coePMPPFgPJd1KMC+SbRFK/90kFVEvy87sMDN7nVgMkp+8340Dsj0ThMbrlvDYWAAx1q33ZS1AOkutshjeVCEJn1T3CnUHY21ch/rQMBPvDQP+o1MGa6/kA8PnIPi/aWaWTMG/uiQYZVCeICINSyVlvAsEEwTsYYY+OANVeqPKcoDkGwlSEThkxbo6o9YOLi7oblVtcsBimczYvLWD1mXcXsNPW5g=)

**Comment by blalan05** [comment]
This matches V2 behavior.

**Comment by b-maslennikov** [comment]
@blalan05 this does not match material design specs
https://m3.material.io/components/time-pickers/overview
try to set time on android device. this is how it should behave

**Comment by blalan05** [comment]
The current implementation is using mouse/touch events on clock circle, which no longer fire when the mouse leaves that element. I believe you would have to create a window event listener and destroy it after, to make what you want work. PRs welcome.
