### ISSUE TITLE
[Bug Report][3.5.13] Nested VMenu causes error when left open on route change

### ISSUE THREAD

**Issue by NickdeK** [vuetifyjs/vuetify#19505]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Have a nested menu
2. Open the nested menu
3. While the nested menu is open change the route
4. Get an error in the console

### Expected Behavior
Route change with no error in the console

### Actual Behavior
Route change with error in the console

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-fhewvt?file=package.json](https://stackblitz.com/edit/vitejs-vite-fhewvt?file=package.json)

### Other comments
Nothing visually seems to break, but the error is causing error tracking issues.

As far as I can see it's caused by the [setTimeout](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.tsx#L78) in the VMenu component which causes the function to be executed after the route has changed and when the component no longer exists.

I created a stackblitz reproduction link because there is no option to add the vue-router in the Vuetify sandbox.

**Comment by Arinono** [comment]
I missed this one when I opened: https://github.com/vuetifyjs/vuetify/issues/20248
