### ISSUE TITLE
[Bug Report][3.5.13] VAutocomplete: using #selection slot breaks the input editing when focused

### ISSUE THREAD

**Issue by DSplawski-CC** [vuetifyjs/vuetify#19510]
### Environment
**Vuetify Version:** 3.5.13
**Last working version:** 3.4.6
**Vue Version:** 3.3.8
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create example project.
Add VAtuocomplete element with some items.
Add #selection slot to use custom appearance of selected item.
Focuse VAutocomplete and edit input.

### Expected Behavior
It must be possible to edit input characters one by one(not whole input at once).
Control must not expand.

### Actual Behavior
Currently it looks like input is empty and placed below the selection value.
Editing input causes removing whole input.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UstugzAQ/JWVc+ASoG0UqYpopP5CryEHBzaKJYIte6GNEP/etSmNkza+gGdmZ72P3SCcrfJ3Y7K+Q7ERBeHZNJJwW7YARZ9KY8JvuFS6JalatD/QpOhIV5qjkHCGARxdGnwrxaeq6bSBl/WT+SrFlbd4ZJbQ0QceY6LG1im6MOlNZUUx2UurZEtM6o4afkkdsydVY1ojP7FxV3SjuCbHIbtE3p9kCckhPsn+avhbJJc5twUW3o3NBjBWGwdjKSJdaEijHKVeBn16UG3N6qAtBeSxZx71+r9UfapCj2yHHLpw2GBFSrche/D/k7xW/XaYyKyXTYcwjkXu0Qd5Z+h2jPPEGb4deRCGjbh7feEqqwyBQ+qmhVFnoy3B4CcNIxytPkPCS5b42EnNOjEuxSpbZa/Cf9fZ80rsvwHwjsuL)

### Other comments
From versions 3.4.7-3.5.6 there as only strange behavior that input caret was placed randomly in middle of text.
Mentioned issue appears from 3.5.7 and exists up to 3.5.13.

**Comment by yuwu9145** [comment]
Selection slots are treated the same as chips because it's impossible to guarantee slot content is text only. 

For selection slots and chips, placing input next to selected item is intentional #19294
