### ISSUE TITLE
[Bug Report][3.5.13] [Bug Report][3.5.13] v-data-table not sorting when data is too long

### ISSUE THREAD

**Issue by onetaek** [vuetifyjs/vuetify#19521]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
go to reproduction Link and click order button

### Expected Behavior
data = ['200000000000000000001','200000000000000000002','200000000000000000005','200000000000000000003'']

When there is data like above, it should be aligned as below.
['200000000000000000001','200000000000000000002','200000000000000000003','200000000000000000005'']

### Actual Behavior
It is not aligned and exists as it is.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUMsOgyAQ/JUNFy8KrWkvBk36HeqBWg4miATQi/Hfy0MT214aObAwMLOzUy/I6I48lMLzxFGBqOWDEszyqpEAdM6YUuEYLt0oLesl1xsUwBezLLPsKTgUvaObskGhNqii5Pi+CznwU8kjsRElBwPUdLpXFgy3U3ThaMZCUIcS6qi37GZ8pwKS/PK7rkkaf61b/YeUnyHdz5Bu3yRCAGMMw6h5HNfDrc8nZuLSQGsqJyHC1r4BnSl/jw==)

### Other comments
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/composables/sort.ts

```
if (sortA !== sortB) {
        if (isEmpty(sortA) && isEmpty(sortB)) return 0
        if (isEmpty(sortA)) return -1
        if (isEmpty(sortB)) return 1
        if (!isNaN(sortA) && !isNaN(sortB)) return Number(sortA) - Number(sortB)
        return stringCollator.compare(sortA, sortB)
 }
```

There is a problem with the code on the above path.
```
if (!isNaN(sortA) && !isNaN(sortB)) return Number(sortA) - Number(sortB)
```

The problem is that the Number function in the above code returns only 17 digits and removes more digits and returns them.

For larger numbers, use the bignumber.js library to sort rather than number

I think we need to modify the conditions so that we can process it to sort with strings.

**Comment by KaelWD** [comment]
You can pass a custom sort function through the header object if you need special treatment for certain values.
