### ISSUE TITLE
[Bug Report][3.5.13] (VNumberInput): the <input> tag does not have an id attribute by default

### ISSUE THREAD

**Issue by guenbakku** [vuetifyjs/vuetify#19526]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open Developer Tool of Chrome Browser
2. Confirm the `Issue` panel

### Expected Behavior
id attribute is added automatically to `<input>` tag which is being used inside VNumberInput component

### Actual Behavior
id attribute is not added automatically to `<input>` tag

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkM1OwzAQhF9l8SUgkQauUVqJG7wAHAgHN9mApfWP1nYuVd8d26E0kXqxvLOjGfv7PAnPQ/Pi3G6OKFrRBdSOZMBDbwC6uZbOlWsZBmuCVAb5TyqiifqIXCvjYrjIAC3jjOxx34tJksdeXHc5hi29S1bShOQYcZKRwtrT+oAurZ52z2uZ5BEpyRvrjxrxLdffKmuV8XhzM//3e0u2nhQRjlfDoWu2n7twSPIWRFYWTl2z4pdGP7ByAdID4oJRaWc5wAkYJzjDxFZDldBX2V7I+ADaf8M+O+6rVySy8GGZxrvqIRcskSlMnB9NJCrH1y8u0JCN)

### Other comments
When a `<label>` tag uses a non existing id in `for` attribute, Chrome will warn you about "incorrect use of label for=form_element"

![2024-04-02_13h52_20](https://github.com/vuetifyjs/vuetify/assets/15353516/a82c73a8-5eb7-4e38-ae47-bbac63adceb1)

**Comment by yuwu9145** [comment]
fixed in #19714
