### ISSUE TITLE
[Bug Report][3.5.14] v-tab not able to assign data in v-model after V-tabs data array changes. also not selecting v-tab on navbar

### ISSUE THREAD

**Issue by IshmamAbir** [vuetifyjs/vuetify#19535]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
- click the items in navbar on homescreen when the page loads. [eg: Home 1, Home 2] . It works properly
- Now click on the buttons(Home, Account, User) to change the navbar. It changes the navbar.
- Now click the navbar tabs with the new data. it will act weird from here and selected data can not be get from the v-model. also, selected navbar is not active.

### Expected Behavior
value will assign in v-model variable, and v-tab will be selected on the navbar.

### Actual Behavior
data acting weird, and data value not selected. selected navbar is not active.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVttu4zYQ/RVWKGAbiKQkm30R4iBJgaIFWqBAu32J80BLE5tZiSQoyl7D8L/vjK6ULDveNQKF4gzPnLlwNC97Lzdx+KR1sCnAi7x7C5lOuYWHhWTsfuNzrctl8+IvuWEJyFzY3XzhxSrTPLYLjy2VScDUuq62b4VNK7xWJGIlGT0QIkuEH6tVjhghanV6zzwH9o+BHGyOvxY5PIZ2rFq+zNnGz1QCKaLj68LrG8ctVHhTBsUC/WVCsrxYZiCL/wVskUf0Fcg5EgaliR4EY/s962TscHDgkRziuwZ/8f3WKk8LIFJbhYh/ku3/tmrkzEB9bYAoVAfopTnCfL+LeLWXN+nqwtQGCHEl34gVt0JJPzF8C4YZLlIG3zSXiY+7a7XBTQ0m4xKkdROaitz65HjHVBvQgAf5hltOAV1bq/MoDA3CqazIwQQZhFyLUCtj0ZbNQ4x0eHsbvOvVwuugymAiwt8mYE/Pv7kiJN28uCWClBKxEVR25G2z7ikQ56NsU6r/QsF4qkfLGyn0EzQSDMaiJh51bZewtHa9QbXGV9esq9Bkfq2ygeQxTkX8laituVzBv1XdTglo5mqWEWk5jtTjKP8BfbqaPI5VITEErl6bqx17GpM3/EcPn3BhUiNNLvTjh13wV0YV2leFTYUchLVx6AsWLHaiMV+olgeiU56UKGf9GF5ckjgX9+iWdj0449Su7K6kuwaxWtuI3X6+1t+wQ9BZUnBv/NJKFqu0vABLdAWLeZz370Zlz4W1Sk4nf2DhkQMPtCBUROk4uJA7SFNFTfNjUCfBrfNN+bSunzRkILnIShv8B1q5kHVLxPV96Hzn8DWPjdBVArATYqPCHvDGi9SyfcUlwfYWsemMzR/YtN7DquHLiF1fdQ2naSwRe+lS36rTj8oyYhMqS7rcEzw8qEKUltHvServU42972mymwk7XLHB5i1uvjoYB2d9ilF9UcZJNdk7w8uVoJXh0YroR0pE/EOlT5co3Q2VfjIe/cYxHp2q6n4iNuXB85GpVM7GpVI5isq4w92uM/YgxWb/MKsXGdi1SvKoC1C/0dmdhpkbPbsWeeCAsjkjnWar/ObWyh2dUzd5HJ0GozmTRZqeN0tbjc3gTaQWzLSXZpoF8DY7g9x8XtHt1GYv169j5GuTv+JYEcMXjd0BprOhZ83/2ADKk+msduUjtqM2yxkTH/dh26u8K09k1Kyw5evgPVcSB/jSBg4WpQA/V23uFh5O+PTezWhxIvEYzsliYwIJNpQ6Cx9RLTRY9SIDH0e4x0/BXXB7EyZIxd0PIM/8pVFbGvHe0VLtbWnHirfdBbZqTTTxObi5q0zUe36KoyzZOMIO0SCOqL7BrzwYMJf6NDjW82sgO/KtDj7+eYcrqr3y8fodVVEIMA==)

**Comment by KaelWD** [comment]
Dynamic tabs should have a value assigned.
