### ISSUE TITLE
[Bug Report][3.5.13] Scroll breaks

### ISSUE THREAD

**Issue by jazzybeat** [vuetifyjs/vuetify#19530]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.4.21
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Swipe the overlay down and it will stop scrolling. It works in the playground because of the iframe, but please try it on the docs, it does not work there.

Video
https://drive.google.com/file/d/14lYRPxErQB1goFYEaXHU0jig-QCO4cbT/view?usp=sharing

### Expected Behavior
The scroller should move up and down without locking.

### Actual Behavior
The scroller stops/locks when swiping down.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtWl2PHcUR/SutfcnL3QsIIiUWkDgY8iFwHCUmD5iH3pne3Yb5uEzPXIws//ecUx89fb1G2UhBxt69d6a7uurUqVM1892bq6en0/G8pasnV5+uaTwNcU2fv5pC+LTP59ANsZTPXl2d4vUnYU2v1+suTWtaXl3JNbjqfN3nOMx3YYyvr3/O/XqPy3/34Yf1Clzj64bzdRnm9Uns1nyO67zg0jfhtMyn8iTUD1/w9/C2WUC2uVmn/feApW7y1GOBy/teXbUX0WJc8vdTmsIzMbP9/vNPP5Bld0M/aDzwq9b36TZuA9d9E3J5yu3TQ3O7uPRhzeuQcOHLksKf5/luSL8pYZi7uOZ5CiUt59ylP1zc+p4NeYqLK0L4el7SGPKpbGPo52FeQslriGNaD1h2PKUl/LTlgl/iKePwuQ8TfPTTlkIa8noMz+eyLjFsyxRDxE1jvJOfwpR4UUm9/B8R7JC5Xp+5tu41xm3JJXTbUrYSzlzxoP+EaZ7EAqzTHcO387CtJ6zKT5bc524bcAdO16UFHw9pPoS43WHHjPt6mBzkC2AiT6Gbpz6PABxOiV9jSHd6wD7cpsW+4G/nVNZ8g7XHcI5Lxhaxo0X7p27IvHQ5bKt4QZYLQA7+HMPLYV0QjQJHlS6t2xKmbRhiuFviOffwDV0Rl247hhf3cUl033I/Tx12G+flJms4Drht6oC88QRP9ekmr4yDhuqUhoH5U+Bj2JfXiIP3CFUcaZT5FW6w++Gc04ob6NZj+Afcw+DAtlMuYkbBgtifsYYzuxU/D5v8IweVA5qRx/AU8EAEEZnWNWNcYSF8PY5zj3DoqeOQsRWcPeWbe4QjpgI7DvBbMr/LdcfwT/gR4WRU3Su0nU4RSCmeLg+uWwAwEuzjnmuWADdLk3/639+2ss4hvZajckUzs8POcRQUTgkQF8wDEbwMKBfjq5s8lPADfiPibjfEOkTcGyeBBcFnrsAvM9Z4CYiIwwWfuGuFVxEZhGQbx19wtB7nI6IlezoilckIbB/DV3Hr4Gc4BygDGwASeRjmsMYOuAhzn5kAjMsZLLLAebBnSEABzyhhlb8qTg/MughQAZ+KOsTgyymPjjgm87KtCyIkGG9yyHaybxV9dhdWxoYEGsALZFm8W5zYwcnzWA8JOIiHJbzmQJiKsMq6k/DLwbGg6UYzAXe4EaZI+pU1wjfbcM5TRA7+1fYY8g2c3+x+UDfcDBGnAZ00TjL87oQgyMDO4q+HeFcKE08onShv8aYROULcIxsRvQY4kg34tPG9QAjbKA5/EHiaKUJjdNfS089pAL3OA9xlvsHOub+gJ4Hdzo+EjzvFlgamQafpnldEBvUcuSKsN9vDz7nQrYKlfWU4acNVYn3s3OWPSrkvCUrY62f07BFj2wio75T3LhM9BhwJMSnA4YJIC9UfcLaF+edlRdntWyXucebdtbboh6QKxz/DyehEQkILV5bVvQTxYjiogA4RJKJpvsG9dH8ajBPkDNiZTlMoa8Q9S2vhFPqznyXTR+xJghFqba5fkh69JyxQJehtJaGvlZDP23DaVpb1SKKBS1gUhSThEa+IJLSxIJfEm236SQHBomAU2XCMCVoMTgWcqQWEv+gcqyLuL8G7cJA5k9tacrRlQBAqBJ9vcQy/RJ1jaaxEnzb8Aev4lULkm8GERzLDzBDaJKdJcAeItaYmvYcausuCmbVOYloKyghuXlmFUJGrozxm1WFMY3EcYAObJCqMk3wIp9yCaXECHm2niFosQpn7OCQWR9RsNavMXVbKBS6xbh5Rjt0WBNprPu/bYg+j4HgJeVUZbXYUOhZsv/UsOMrJlUZYUbSASEpIrCAWjAaNViWHvWRoLtYoOV5wgIYzIMkhNuKCLQBccFxlI5xFs8QKPI+JCvJUEEv4NZ6lL519mKueuOaghgxN+2jagWtWuGQnvYbFCXsRUjOE55IMUFjeK4mKBkUOap1VYiv6MMALk4lcOKbLJ1Zbz3Fg5WhqoUbI2QSnEyDi/DNKrda6fxnFQzACLvs6+JJHEDYyaaXHrzB6FIsCV6RzghZiSdHm9USZpElCyyABE+/SyPNXGNe7tNMqomlPftoBo6kma0jn5gcnaanxsrQeh/Vk0GhUN1YEWy56SYOdB008JP9OVlYW+cvBnaSqpPqRlxVgA2AFzr6oADFdqJVAwMO9T9QDqoomqbCNc5Te4LOtoJ/rc0FT1ZYbOb1qDKTDv2msVh/rZgQwyFbdTQ6wauzviWNYCdYoFARS4OBcBakLdVee6P3QKGSSxjOkLxc3XUIwiZxC4qBHVOVX67eFTyuYLil/A/oEpQptcIFb2BzdiEDKHuNVTcBijDVrqwgkbgPngNq4NcUARZUzMQLgCkv1yzulohGHjdv3vRCBXROx4BBp3bzQsWxfmO/036aHRrgVfif0BbmlXWROmyNf0P6LULKkGDXvJVG9AFGdtruMEOkZmCcmu53TtA/eJXfdv5ZgqTAtHNXllmAe6dgjKZAZ050pUoNVS+lWczSeIBgHPvJBE9Ta7lbtwTg3tcKE55HM0Yw2EePS/Ri+kZq4TagV0tox0qAESUwmjAld3MNumj9WrlQY/OUXLBXTbA27Uq/pajQf0kSZ7rZqTx0r0Zw08R2YrUyR4mXqV8wXM7yE44C25M5mmvi162am6awBMQKW75HaC2onOlWoLnjGTLRgN7lPRz2Kgr9aEEG0XdqZVk2jcwcpOESq0S4JApysifmixWTtbzmZIGKtDjYoQYxNYKoQE+5kZE0SsZ0ugwbQybNtILwjaprZveGWtoK4UN3E7tT9bDodx7qjdxpprbF/zrogfjeEO+Ef9gLfNPlkWtpZy24tC7VPlFpg9OkngQReEuPH8LWNqmr/1QIpFu/JqRyENMJ5BAdKOKLJZGCRIfBLAa2rqTKyunUKUALTgk4CI4QcnExBr0KWNDt8UIytIrhixjFVIN8AstDx9IjwBhJMpkbcWPRDy3sux0tEAyB+9GKsFR5GurEeXQYSyOdyCBj7ORWvX4Pem/mKzhdgZ7zLAiQ7LDUUIFinTTIHoacoV8VH1EmcnwHIXsdloEi3F3REsBP5RYkmx+EvUvP84IZh3O6nizc+tDGm8CCRZnVJYy8dfl2MW+yeR+XqN7VngF436a7da5Vdgk/zRZ3GSIRsX6cvYgGXwhFtbTEOr8RrnAD/CY2yxvLOphMS2HpUd1TTba3Qp4L0yWitK7WiUJDXwnxbGQlYdH2hWliaBEQYtAtk6lGsUHk/K8E2KpYMYR/cyBCrC1XaViftqURkkLm9xuqwWHlRmhDiuPfj0LnVxeLbjaSiQvPe64qUe/MNi3Ht8ygbvBZV7bjmqcv9ho+8NwHKusZEJXyfsu1lQeccmukw4zGgskyvRngsZfpXzWzIwYfSlp7K1zL/xSVLhnuYAZUERGPJ0IbKSmuzFGbptvYWm+chsjRVanss8kD1gzGppi9sNaGOJkIiLRXK2iqxx8p9ZQ22Al06raBSad/mE540OPqaWqYD4ypVWkHzbk9y2b96J1R7S+s3+M2sjjKnNTTeRpsC/VLDyyiEuQTMRTRkwvqWyjgrLdGLtFmwJxU6SSLlKRSYEpOWpQzoP8cXdaStUFJUV1LZawPnLCJcrdvbH4GoYrkYJjWpyzzhVB67W/neoVU7POvArG1nd6LZJLrd2tIqIPZObh/I8oHKvqkgzNQEKoaKK+UCGmxuU0+x8qNDaby49/b8SxUjU/mZzETFOvlGa3SlSA+lkNNlA2IhVy1pWu/CX4ZyjZpXQvVwFXhqiKt0mv1UH3vopNi7TB1WaKWTp1eKtMe14ZLPF4MXfdDi0qaOqkWC2BBJDNOmSaYn3sFZFljt1eZMIUTqBZZtWrU3HNWFD9oc3LEPpoQZQNzKSOKJXV0aJwmMoXAE/OZ5a9uczoeIi7Qy7N0dcqGZm9W5GJ26T0qoKl1anH3c7FUINOT1vwoOj84+UlPnkFS6POOYrUDeCyMjLnTGqnsMf7LSJXCSMQYVgGsLlnDXYoJSapcLmNnUgxoN3pC01Wmvfi6lvZ5H4S0MreRhSt51oFbihuArtC9m1tXd1alKA76P6m57Nug3sn3dH10CUrYwtiSrV+0pc00qfOHxOlPltjqaiizhraxBK0XHiezZZaRXV5nX+vjTHv0IV+hhrYOwx5Te5NPJC9SRNB7mPJZ2aEZkifcegoiLp06QaJUglHw9zf6Xeq3zJj7wbcvTO4PxyrCXk3NJX38QWR/NWmkScaQVYn/ATPHhT9LRbmuRpQpzJmeyWktnJVgdALKwZ0pwdaURuDVPeBymT4xF7DdFVZLYxXujbB0GWNNKO6uT6efwnA+mFC9aROrA1555SW5cMMzlgxA+bncO9jm2/yvp8o3QdM1ca+ZtjGaObrsfe2rpT88Zb5EWWhX0kG2tx7kePlKsc2XOyITd6rn2yZw99L54UeJ9r2s0r19c89UQnP+ddyfwbTkxYeX9D/vxASwfvHDSvE/yLJd4B4K9fNlE3kpBBwkY4Bpe+vD7P3YA8o/42l8cOeI5HsL0Gfh4KA8WbN5QeYx5HWGIxcu2gN7TtVnz0Aw7x9P/dohbOPf/eYg2dr8aI//q/a/l+BX61pG+qfQBXlXCT811V4erIU8/luMPZZ7watObV1ddwctBT777/i2+AxujKF6P8dRcoB/yojdv3169PVx9fPzk+NHvcfnHx98eP/r46gB+S9//B1GuMXk=)

**Comment by tipsy** [comment]
Can confirm that this is an issue.

**Comment by jazzybeat** [comment]
Can someone help with this?
