### ISSUE TITLE
[Feature Request] Date and time input on the mobile using text field input.

### ISSUE THREAD

**Issue by jazzybeat** [vuetifyjs/vuetify#19532]
### Problem to solve
Right now, on the mobile, there is no way to enter date and time using a numeric keypad. This would be useful when working with forms and you want to have a consistent way of entering data on the mobile phone.

### Proposed solution
Please provide an option to enter the date and time using the keypad on mobile devices.

**Screenshot**
![IMG_0652108CD09D-1](https://github.com/vuetifyjs/vuetify/assets/815706/f0477b1d-543e-457d-9efc-6969ae1c50f5)

**Video**
https://drive.google.com/file/d/14nVAaxtNI4NTQwbpkX4ybTdHurPXQpWx/view?usp=sharing

**Comment by b-maslennikov** [comment]
would this work for you? [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj90KwjAMhV8l9GYKzt7LJvgczouxZVDoH202lNJ3tz9DxZuQc0i+nNwD827iN2vP24rswjpCZeVIeB00QLe1o7WlLWIymkah0e1WMQmf1C4C5Qxbq8yMsh/YnBADA3pZ/Cr+WQsBsgcx7mz+D89Ovd3xn0xJ+skJS+CR1hpNKGscQQCHC0RYnFHQpHeaPA6QuJ7quT6PHI6ZWSlpn8WTXqUs5fEGUzNafA==)
