### ISSUE TITLE
[Bug Report][3.5.13] VTreeView Select Functionality (Prepend slot, selectable prop v-model value, click:select event)

### ISSUE THREAD

**Issue by angrymarker** [vuetifyjs/vuetify#19533]
### Environment
**Vuetify Version:** 3.5.13
**Last working version:** 2.7.1
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Use a prepend slot in conjunction with the selectable prop on the tree

- Utilize the "selectable" prop to populate the v-model array with selected values

- Trigger a method when a selectable checkbox is selected

### Expected Behavior
- Checkbox shows up next to prepend icon 

- Selecting the "selectable" checkbox adds the value to the v-model array

- Event click:select is triggered when checkbox is selected

### Actual Behavior
- Prepend slot overwrites the checkbox when the "Selectable" prop is selected

- Event click:select does not trigger when selecting the built-in checkbox

- v-model array for treeview does not update when selectable checkboxes are selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl1v2jAU/SsWLwGpCU97iShbpfVxmrTXUk3GuQkujh0lTkqF8t93bZPEpjCGtD6Afc69x/fLpi/HWVOz5VNVJV0Ls3S20lBWgmpYbyQhx6OuAfoeF7SqBDR9b+BVF2+1JN+Y4Gz/uJlpaPQ8ograaLGZrc1itbQ2VgXNjUzH4d1sCeniUmUgjCfim5lDU45nNwja7xFVFUjIDCy55lSIj5+IDLSxjffwgbyk5ahFmeYd1XQrwAFGJVYytiE7qAEBzDNx6aQOPmXl9GwWmMdQG0ygEUqnVQ0oa2I72kAe7DGkxxo4D5s7Z0qiB89PqSVsx0VWmxxGM1Nq5/yVRGXG41yJDOrYQBFJfSwirglWHats5C8cB6KBNbFuXECcKdaWIHWsWi24hHPX1TJovGGHniEQsLhtWM0rbS3hUKlakwxy2gpNjk6uBL1TWZMOe0JMNVOStxI7gwHOTSUWE40GO94kbsqSqm12zmLg+we3Gr4zbG5K5gvyuCbzUSUYkZS8RFW7xaZGrycvQkwx/LAI2elSnAosqCxaWkBssC/R6ETIG/pYE4mD+9aElMKjLMmQjM3e58vsXL2k9T5T74FVleVDl027cBtv1SGwkIVvwUuU8nl9wPpO/HnDfdODGNKxpnBgICZ+KDFK4gRgFafqufYEkL2siHiTPC1RgmuBGlFScO2HMB1yxcEU+jc+Ey0e6DuegkAL+94ETEdFaxim2F1nnaYk0BouaZDaJwVfpdFUn6v8Vemimq8oVKES7PtnzWGUTfCXeT9p9zf17LLF1cRy2pmXIsGPzyddj+Kf9bnM4JCYO3dV/hIZ6vvZ3Wy4mUZeSFUH12I8Da/SXfOzpVsQCZYo50USvg6jZgjfHknK9njBUS18TTy9kLip+Ov56fuP56TMLsqF8E0x/Gfh/+b7QWuZCMX29zVk6Hq/sAv8YVwtxx+nWf8gWyHsx+sfluhydg==)

### Other comments
documentation on how to use v-treeview-item would be nice

**Comment by yuwu9145** [comment]
Would be awesome if you could help test PR #19795, this is what I fixed so far

![vuetify-select-3](https://github.com/vuetifyjs/vuetify/assets/5698884/b41280ae-4fdb-471b-a540-2e3bf52a3817)

**Comment by angrymarker** [comment]
The return object does not seem to be working, and is returning the object keys

**Comment by angrymarker** [comment]
@click:select also does not seem to fire still
i'm also unsure how you got the prepend slot next to the items with children and the down arrow

**Comment by yuwu9145** [comment]
> [@click:select ](https://vuetifyjs.com/en/api/v-treeview/#events-click:select)also does not seem to fire still

Fixed

**Comment by angrymarker** [comment]
>  i'm also unsure how you got the prepend slot next to the items with children and the down arrow. Checkbox as well ![image](https://private-user-images.githubusercontent.com/22374821/332201966-81a43078-5f4e-43ba-9eea-af7ab70890c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODUxOTIsIm5iZiI6MTcxNzA4NDg5MiwicGF0aCI6Ii8yMjM3NDgyMS8zMzIyMDE5NjYtODFhNDMwNzgtNWY0ZS00M2JhLTllZWEtYWY3YWI3MDg5MGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE2MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NGE4NzA1ZmMzMWI0YWY4OGJhMWRjZmE3YzdkOGU1M2I4ZTVhMzJiMThmMGRhYjE1M2MxMjVjM2Y4NjM1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5NqEn_eIbGsYunE9tKCkXnHdjP-YKiWX5fxxqyLxDIQ)

Turns out the prop "activatable" was causing this for me. i didn't need it, so i removed it. I also needed to set
`select-strategy="classic"`. if you want the activatable prop, you should be able to use `active-strategy="classic"`
