### ISSUE TITLE
v-card-actions doesn't reduce margins on v-btn used a v-dialog activator

### ISSUE THREAD

**Issue by ajsutton** [vuetifyjs/vuetify#1953]
### Steps to reproduce
https://codepen.io/ajsutton/pen/JrJmEJ

<v-card-actions>
                   <v-btn flat>Button</v-btn>
                   <v-dialog>
                     <v-btn flat slot="activator">Dialog</v-btn>
                   </v-dialog>
                </v-card-actions>
              </v-card>

The "Button" v-btn instance gets reduced margins because of the ".card__actions>*" selector but the "Dialog" v-btn does not due to it not being a direct descendant. 

### Versions
Problem is present in v0.15 and v0.16-beta2.

### What is expected ?
Buttons should both get reduced margins.

### What is actually happening ?
Direct v-btn gets reduced margin but v-btn used as the dialog activator has default (larger) margins.

### Reproduction Link
0.15 (latest release): https://codepen.io/ajsutton/pen/JrJmEJ
0.16 beta: https://codepen.io/ajsutton/pen/veZVgj

Adding class="mt-0 mb-0" to the v-btn used as an activator works around the issue easily enough.

**Comment by ajsutton** [comment]
Actually you also need to set the left/right margins to 4px using CSS to get the layout exactly right.

**Comment by KaelWD** [comment]
You don't need to add any css, `class="my-0 mx-1"` works.
