### ISSUE TITLE
[Bug Report][3.5.14] (VNumberInput): non-numeric characters can be entered in browsers on iOS

### ISSUE THREAD

**Issue by guenbakku** [vuetifyjs/vuetify#19544]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Google Chrome, Safari
**OS:** iOS

### Steps to reproduce
1. Diplay VNumberInput by Safari on iOS
2. Try to input non-numeric characters (alphabet or etc)

### Expected Behavior
Non-numeric characters are cleared immediately after they are entered

### Actual Behavior
Non-numeric characters remain when typing or losing focus

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkM1OwzAQhF9l8SUgkQauUVqJG7wAHAgHN9mApfWP1nYuVd8d26E0kXqxvLOjGfv7PAnPQ/Pi3G6OKFrRBdSOZMBDbwC6uZbOlWsZBmuCVAb5TyqiifqIXCvjYrjIAC3jjOxx34tJksdeXHc5hi29S1bShOQYcZKRwtrT+oAurZ52z2uZ5BEpyRvrjxrxLdffKmuV8XhzM//3e0u2nhQRjlfDoWu2n7twSPIWRFYWTl2z4pdGP7ByAdID4oJRaWc5wAkYJzjDxFZDldBX2V7I+ADaf8M+O+6rVySy8GGZxrvqIRcskSlMnB9NJCrH1y8u0JCN)

### Other comments
This behavior is confirmed in both Safari and Chrome on iOS.  
The input field shows text, but the corresponding model-value is empty.  

![image](https://github.com/vuetifyjs/vuetify/assets/15353516/ed8aa3da-3c63-40d3-930a-9153cd2ea9f1)

**Comment by yuwu9145** [comment]
fixed in #19605
