### ISSUE TITLE
[Bug Report][3.5.14] (vAutocomplete/vCombobox/vSelect): Selected item from dropdown half displayed when input has focus

### ISSUE THREAD

**Issue by devCodeHub-star** [vuetifyjs/vuetify#19540]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.19

### Steps to reproduce
**Issue 1:**
1) Select **test 2** item from dropdown and blur out the input
2) Now click on input 
3) The selected list item not displaying from starting, it's displayed half

**Issue 2:** 
1) Type **test 2** in the input field
2) Only one result found which is not highlighted, in the vuetify v2 if the single item found, it has gray background. Compare old v2 
![image](https://github.com/vuetifyjs/vuetify/assets/148462347/4e92bd8d-beb3-4d62-90f7-e3e7d426cb27)

### Expected Behavior
**Issue 1**
Dropdown item should display selected list from the start

**Issue 2**
Found single result should has gray background color like attached image

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlttuozAQhl9lxEVJpJIoaXsTJZH2avduH6D0woCjeuUCsg3tKuLdd2xzskNWIDXKwXj+mfnGh1Fer4EU6fZHWW7qigaH4KjoR8mJouc4BzjWUUpEZsb2qcgVYTkVcOEV6wzGJIrP/rHVcsCPPMXBbh8HI6Mxk0oVaYHJqKJjE8CBIYR2M79x4FpTTokgCfectDZSTHGKjjn5oL6fEdSEV1pgfl2Fw4eE3UJAHUleKAOFnhlRxCvGyLUGdN6WOw7QMWF5dt/HLEPGapZRcWtD4lxSNWWoI3bBsOpvSYsL6OgbnXIjyCecTicIfyd/aKpCeHiAsE0QYjhX6i+QWYTjtkea5uVMqkhWyTsld7DriHJJLeLKybg2QNZzHg8ehm5PHe2mTT9VwgQ2FuVy/6c2ncLduk0pihLPIXQoZm91kRNh3ED2RJ6vV5den5Om6bFGynkBp1RYuZ8mozIVrFSsyCezTYX5XgL6RfQN/+7sN3nMfZ67oo7q9iZv9VX2u8HW6YvjSOM+Nm6AaMLuN3RIfB5apLW2vdS2Wj1je62TDB/tJhoV/SoLoSCjF1JxBVcbTa/FAVZrOJ1h1c7ZhicP8Dow9Sb9shfhAOEvM4Bd+DiYm9HY8dInF30Ulcr1QIrhtGnFO5OAb63cjW2uU3tA0KEd+VHNzqJ5Od5+Lt5+CZ4XtcNzpmfhPc3Fe1qC50Xt8JzpWXjPc/Gel+B5UTs8Z/ouXn9if/IiIRy9BdN/BOTi4l7mFveypDgvalecMz3gvfUjI8Sbmlect5PN2gwa3Qz66x80j0aiv97+AWDHrZU=)

**Comment by KaelWD** [comment]
Essentially the same as #19125, you have to pass the item ref to the divider and subheader too: https://play.vuetifyjs.com/#eNqtVktu4zAMvYrgRd0AdYKk7SZIAsxqZjcHaLpQbAbVQLUNSXY7CHz3ISX/5DgDG22Qj0w+ko80/ZCXS6BVvPqR58uygGAb7Ay855IbOBxTxnZlFHOV2LO7ylLDRQqKnWUhGod1qeyjvayxkuFH74/BenMMek7r5oXJ4gyLgYG+i7GtQBIUZn+Pge+NJXDFT3IQRNjICCMBA1P+DsM4Cyi5LAhgf32Exw8ZNoNgZaRlZiwpjEy44YNmLJwwjOrWvI8BBp5EmtyOsWNIRCkSUNc+ZJxqMGOOMhJnTGv+5pCdGWVfUsml4h9sv9+z8PfpD8QmZHd3LKwLhJjOhw4HVA9fAeW2yFxluV6iYQx62K1a9uOtSaFNpIvTG/AbHZYRSA2um3uP3MJyd5GTqTe338Mu6/Jf7HakQ+zfb/E/YyA2/kK4ergmDWu7MTSPkTR+Irfnh8vFb5S2r6paWj3ktIRjKOx8WCYBHSuRG5Glo9XG0nwvA/jkpBvfXf2qjlWJqRP1UNf6sCKBGGrMylPbfqa+OvZlFV2oqZ3u4nUnvM5bK7QTcLI4BfeK4aW7iRYFn3mmDEvgzAtp2MVlo1ls2f2C7Q/svrY5GdVb9tJxal30cg/CloW/7IGtw4fOXfXOXhRtLsYY0MaPQBbdthHiTWiGb0Ku+z4/qF4QDKhPw6z2zqJ7Pr3NVHqbOfQGWRt6nnkSvcep9B7n0Btkbeh55kn0nqbSe5pDb5C1oeeZb9JrN/anzE5cYrQS9PdCz27ueWpzz3OaG2RtmvPMHb3X9mSB+KSmhZS1sVrYQ0Vi0D7+QfVgIfT1+g9FpMPX
