### ISSUE TITLE
[Bug Report][3.5.14] Weird/broken interaction between v-btn, vue-router and npm run dev

### ISSUE THREAD

**Issue by nagaflokhu** [vuetifyjs/vuetify#19549]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Firefox 124.0
**OS:** Linux x86_64

### Steps to reproduce
- `npm create vuetify`
- `npm i vue-router`
- Create and  router in `main.js` using `app.use(createRouter(...))`
- Add `v-btn` in `App.vue`
- Run project using `npm run dev`

### Expected Behavior
Rendered button

### Actual Behavior
No button, stack trace in console

### Reproduction Link
[https://github.com/nagaflokhu/v-btn-bug](https://github.com/nagaflokhu/v-btn-bug)

### Other comments
Not sure if this is a Vuetify issue, a vue-router issue, neither, both. Please let me know if I should open an issue with vue-router instead.

**Comment by BatmanTheBlind** [comment]
I run into a similar issue with v-list-item
**Vuetify Version**: 3.5.15
**Vue Version**: 3.3.13
**Browsers**: Chrome 123.0.6312.107
**OS**: Win 11

Downgrading to Vuetify 3.5.11 fix the issue. Seems to be introduced in 3.5.12.

The error in the console give the following message
```
Uncaught Error: No match for
 {"params":{}}
while being at
{"path":"/","params":{},"query":{},"hash":"","fullPath":"/","matched":[],"meta":{}}
```

But printing list routes with `router.getRoutes()` (trough composition API) display routes correctly.
Probaly an issue in the way vuetify components access vue-router ?
