### ISSUE TITLE
[Feature Request] Vuetify Plugins

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#19550]
### Problem to solve
Currently, Vuetify does not provide an official way to integrate plugins that use composables. This can lead to an inconsistent experience and make it difficult to use plugins with Vuetify.

### Proposed solution
Provide an official way to integrate plugins that use composables in Vuetify. This would allow plugin developers to create a more seamless experience for Vuetify users.

Benefits:
- More consistent experience for Vuetify users
- Easier to use plugins with Vuetify
- Reduces boilerplate code
- Improves maintainability

```
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import * as composables from 'vuetify/composables'

import { pluginComponent, pluginDirective, usePluginComposable } from 'plugin-name'

const vuetify = createVuetify({
  components: { ...components, pluginComponent },
  directives: { ...directives, pluginDirective },
  composables: { ...composables, usePluginComposable }
})
```
Usage:
```
import { usePluginComposable } from 'vuetify'
const { nameComposable } = usePluginComposable()
```
or:
```
<template>
  <v-btn @click="$vuetify.plugin.function()">Click here</vbtn>
</template>
```

**Comment by KaelWD** [comment]
> import { usePluginComposable } from 'vuetify'

It's impossible to add exports dynamically, and how is this better than importing from plugin-name?

> $vuetify.plugin.function()

https://vuejs.org/api/application.html#app-config-globalproperties
