### ISSUE TITLE
[Bug Report][3.5.14] autocomplete="new-password" doesn't work well with chrome autofill when editing

### ISSUE THREAD

**Issue by tongxuanbao** [vuetifyjs/vuetify#19559]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
```javascript
<VForm>
	<VTextField
		label="Password"
		name="password"
		autocomplete="new-password"
		type="password"
		v-model={form.password.value}
	/>
	<VTextField
		label="Confirm Password"
		name="confirmPassword"
		autocomplete="new-password"
		type="password"
		v-model={form.confirmPassword.value}
	/>
</VForm>
```

### Expected Behavior
With the form above, after using google's password suggestion, editing the first password field would subsequently update the second field without jump to the second field.

### Actual Behavior
Everytime we change the first field, focus jumps to the second one.

### Reproduction Link
[https://github.com/tongxuanbao/vue-project-example](https://github.com/tongxuanbao/vue-project-example)

Go to About route and check out the issue

**Comment by KaelWD** [comment]
Does it do the same if you use `<input>` there instead?

**Comment by tongxuanbao** [comment]
It's working fine with `input`.
I'm on my phone so couldn't create a side by side example, but here's an example of `input` in codepen from my colleague @Maxim-Mazurok [https://codepen.io/diegoleme/pen/qBpyvr](https://codepen.io/diegoleme/pen/qBpyvr)

**Comment by tongxuanbao** [comment]
I added a quick PR for maintainers to have a look, essentially focus event fired an extra time. It has to something to do with the line I removed in #19572

**Comment by XStarlink** [comment]
I have the same problem,

I use `v-text-field`, and the autocomplete for the `new-password` only works from time to time.

**Comment by meganspaulding** [comment]
We are also seeing issues with VTextField on password fields calling focus() too many times, specifically on Chrome mobile we are seeing a maximum call exceeded error from some sort of focus() recalling. We are not manually calling focus()
