### ISSUE TITLE
[Bug Report][3.5.14] Label obstructs input content when setting the :value attribute for text-field and text-area

### ISSUE THREAD

**Issue by QuantumStudioOfficial** [vuetifyjs/vuetify#19561]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
When the :value attribute is set for a text-field, the label obstructs the input content. The label is only briefly displayed when focused, but upon losing focus, it obscures the input content again. 
This issue becomes more pronounced when the `readonly` attribute is also set.
This behavior persists for both text-fields and text-areas.

### Expected Behavior
The input content should always be visible.

### Actual Behavior
The label obscures the content.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjz8LwjAQxb9KuKWLtXuJBTcHdwfjcDYnFM4kxCQo4ne3jQbjcn9+7+DeOz7h5sdu69w6RYIeZKCrYww0KCOETC06l8e8jNYEnAz5L8ow0D20l4lYFygE45l4o2C/dAU/oU/IkWal2RGzFQfrWTf1hSfU1vCjkEF29Y9iZob/bhbyMSu7KgS8ViYy53J6A3R6SoA=)

**Comment by QuantumStudioOfficial** [comment]
```html
<v-text-field label="Label" :value="'Hello World'" readonly></v-text-field>
```

**Comment by KaelWD** [comment]
model-value not value
