### ISSUE TITLE
[Documentation] Wrong example code for mobileBreakpoint

### ISSUE THREAD

**Issue by HijackHornet** [vuetifyjs/vuetify#19563]
### Environment

**Browsers:** Firefox 124.0
**OS:** Windows 10

### Steps to reproduce
The documentation say it will show how to change mobile breakpoint value, but the example code is a duplicate of something else earlier in this page

### Expected Behavior
Should show how to change breakpoint

### Actual Behavior
Show how to see display info

### Reproduction Link
[https://vuetifyjs.com/en/features/display-and-platform/#usedisplay-overrides](https://vuetifyjs.com/en/features/display-and-platform/#usedisplay-overrides)

### Other comments
I actually dont know how to change the breakpoint so i'm really looking for clarification ^^

**Comment by HijackHornet** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/166139343/f0b25953-1cb9-4cc4-91ab-3116683c3d00)

**Comment by b-maslennikov** [comment]
do you want this?
```
const { mobile } = useDisplay({ mobileBreakpoint: 580 })
```

check this as well: https://vuetifyjs.com/en/features/display-and-platform/#options

**Comment by HijackHornet** [comment]
Thanks
