### ISSUE TITLE
[0.16-beta] tooltips performance

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1957]
### Steps to reproduce

Compare loading time of old and new tooltips

### Versions
0.16-beta

### What is actually happening ?
New version of tooltips slows down page rendering time and displaying tooltips on hover is slower than in 0.15.7

### Reproduction Link
0.16-beta: https://codepen.io/anon/pen/BwZvLw?editors=1000
0.15.7: https://codepen.io/anon/pen/mBwaOW

In 0.15.7 directive just added mouse event handlers, new version renders tooltip component and detaches it (mixins/detachable.js)
Approx timing of displaying page is about 2sec for 0.15.7 and 10sec for 0.16-beta (rough values, just counting in my mind) on i7-4700HQ@2.4GHz
Might be same problem as for VEditDialog issue https://github.com/vuetifyjs/vuetify/issues/1897

**Comment by KaelWD** [comment]
Here's the absolutely monstrous call stack from rendering that page:
![image](https://user-images.githubusercontent.com/16421948/31046632-6dcadcbc-a63f-11e7-8059-8fe7bb0d6e03.png)

And hovering a tooltip:
![image](https://user-images.githubusercontent.com/16421948/31046650-c6ffe16a-a63f-11e7-8922-3b92b97a0bfd.png)

For comparison, here's 0.15 rendering: 
![image](https://user-images.githubusercontent.com/16421948/31046671-1cc0d9c4-a640-11e7-9341-7064d76c75d8.png)

Note the 55 thousand nodes and 22 thousand event listeners that are created and then immediately garbage collected. The vast majority of these listeners are `document.load`, so something definitely has to be done about that.

**Comment by johnleider** [comment]
This is mostly fixed, leaving open until kael finishes his **load** changes.

**Comment by johnleider** [comment]
kael's changes are up, this is considered resolved as of now. We will have to re-visit performance again in the future, but there are still potential points of failure we can address.
