### ISSUE TITLE
[Feature Request] Way to programmatically reset and focus VOtpInput

### ISSUE THREAD

**Issue by greggarson** [vuetifyjs/vuetify#19589]
### Problem to solve
`autofocus` works great for focusing the first input on pageload. I am however not seeing a way to achieve the same behavior programmatically after a form submission etc.  I've tried setting a `ref` on the otp and calling `focus()` on that but it doesn't appear to have the expected effect of emulating what `autofocus` does.  

Relatively new to vue and vuetify so may be missing something simple.  Does this functionality already exist?

### Proposed solution
Have `.focus()` emulate the behavior of the `autofocus` prop or add an additional function that does so.

**Comment by b-maslennikov** [comment]
can you provide the code that replicates your problem?
I'm able to focus it anytime [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkNFqhDAQRX9lyIsudBVtobCotF9Q6Gvtg01jtY1JMKNFxH/vJHa3LmxhIYRMcnLvzH2Zme15/GhMNA6CHViGojOyQlGUCiAb9xrNvlVmQOhFnZeM6mdRlwykUB/Y0M09FZ1+F3I/VnIQdHObJne0SlZk8UaBJH9F31DBA5ct/yK61nywT2gS4v0ZEveNmGMPF/H0hKd/eBZv+qfS8r41CFbgYLxa2xndI8xuGlig7nUHAY0erL1xrSzCOiPkDgrVIOVu+3rql4DKTopDuIO8gNkhANV31RIkkDdh0CAae4hjamlyCWNbT5824roLSNPhq1fko4u8dOhflkuWKVmemV1hE2EjVHj2639X8j26Z/EaHsXGlhuXgt9efwDdAruG)

**Comment by greggarson** [comment]
@b-maslennikov Thanks, good to know this should work.  I'll put together a failing case.
