### ISSUE TITLE
[Bug Report][3.5.15] v-data-table headers filter do not work

### ISSUE THREAD

**Issue by jaysonpotter** [vuetifyjs/vuetify#19596]
### Environment
**Vuetify Version:** 3.5.15
**Last working version:** 2.7.2
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set filter on headers object. 
```
...
{
    text: 'Calories',
    value: 'calories',
    filter: value => {
        if (!this.calories) return true
            return value < parseInt(this.calories)
        },
    },
}
...
```

### Expected Behavior
Entering value in the less than text field below the table should filter results based on desserts calories less than the entered value. Should work just like in the demo for v2 @ https://v2.vuetifyjs.com/en/components/data-tables/#custom-filter

### Actual Behavior
Nothing is filtered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtV21v2zYQ/iusgTUyEDt+byPYAQov3bIGS7CsH4omH2jpHAulSYGivHhF/vuOkiiLlGQ4wPTBpu6Nzz13J1Hff3YSGVx8iuP+LoWO35kr2MaMKrh65ITMdz0ax9kyuwkEVzTiIAtRJgypoj1FVwyMkBB/AzQEmSweO8XqsVPRRriL1oWQJCCVpdS63g/Yo5rTLVRVAaOJdgMGO6oiwXtDK2wCVAYbNMgXli5IEyW2vXXEFEg0yRd3nO2XNE7+hhd1MC+zw/wMH2TXS5hQvhKGj5IAhc4YGFhYVRD02IoQWCMefTG6yrQPmZZ4X+/vr/8iy08P1+Tuz9tvXdfepL996U1s3dX8ogqjiv/CKmhLUisR7vtYaeBVX214qLSRhLgZ/tTFtuQoMzY7AWVCRmB1gbnUPgbdCel2BbLJwJB4i61E1IbyulE7OwVDDdmQQLAkphwjI9f1lFFQpaaBZr3pYTTMDKHQHiItyWfMioG3SSCjWGVG8BILqUgIa5oyRX7mwXR0r2vuCJGgUskP94TkfeeTs7PzyhQVdDtiM4s++V5NtBJNX3ok0fGzFP8CJ9/EcypVNYq9wXB66ejWVPlk1h/UXOQK7UcTRx5LoSDiPpnUXCIpUD60pK/WXTP0mwBIIIFuSUJ5+E8UbNrxj8YfmvBftuGvmVfwj/8n/Nf4GIjkEcyzURPmYTvpLrISdN0lB21neQroZRoH9Ae0ox4Ppk2ox32X0QL07M1Mf3wz6N8i/gxyhb0SHgE+nb2N7ok7EiXycd9VFT1i73AK9D+AsT1ZAeVHkH9opHzQBvyydTjrLjlwW3oK7lvBWBSL+Ajqy8b2HvRdsUFt172KuhGzHeYUzL8LDvtAbFftoCcDF0XR3S2gP7Z296zvFi2HPbHFp+D+VfD0yLN7Mm0kejRt64+p/SyzRrK5sUdvJ/tLpL7QI6inw0amR63jOHP5LFG7Ncgxt8/iU7l+zRdGib0RpwpC/5BTcSiuvr3L9/ex168+xejS5e9q4g0Hg2d8y8sdPqq6LiuURc+I+CxRtP6STvBAoQ8mPhLEEnC0O8pSTbdm3fY8WqQC3rIoh7uniWrK5erzM7mf25HFlRsea7Am3ju1iZK+idE1tCmZ4geI61Ao84hzElOZwA1Xnh3D9rJTdBI2OX6mSL/mvMwKG+2szXqpm82xzxqw1eM+b0PHp2jOVq8b7FHi/VJ10W1r2z+VfVoIzf8W1EaEOBQl7/WvJC+Le14cLc+zz7WmLvaq+HL63y0ITxkj799XdXmgFqU+/ou1aYjFQjezxF4/c+wyg74SD5nW6+LyVmB54St+1MglTQBlEQ/h5W7t5Tt2ccsFwS/IMkzZBjYvOM3zi/Iw3nk91zizn6f/AOVL2dE=)

### Other comments
v3 multiple filter criteria workaround: https://codepen.io/jaysonpotter/pen/abxYgbp

**Comment by b-maslennikov** [comment]
did you notice that filter property has `FilterFunction` type?

```
export type FilterMatch = boolean | number | [number, number] | [number, number][]
export type FilterFunction = (value: string, query: string, item?: InternalItem) => FilterMatch
```

**Comment by jaysonpotter** [comment]
@b-maslennikov I did. So I tried to update the accepted params in this [VPlay](https://play.vuetifyjs.com/#eNrVVttu2zAM/RUtL02wJM29jZEUGHrZuvYHhrYPss00QhXJk+W0WZF/H31LZMdqm2XAsD40Mknx8JAUpbvXWqi84y9B0F5GUHNqEw2LgFMNZ/eCkMmyRYMgWSYfnhSaMgEqEyVCn2ra0tTlkAsJceZAfVDh9L6Wre5rhpYhSqzzIQxB6YIy1rWeYIVqQRdgqjxOw3gbcFhSzaRodbfqTUgYVE6CLFshl9pxpb9qBwoCEL5hF1tuqeSSokVGUsOLbs0YcL+sJAiykD7wioDzP70KANWxkyo1p26y/SJNB6l2czY5NuMox328E/hBVDzKpWJQKE2JjogWLqi3CN0iIaLnVPxrNjNamfj/j4hHlXtYTS5fqIctZrHbkw0KzAOEn+b4SEXmhMhHCQqLsySWpKOm4AM/Q0+xQCdG8BJIPB4+zGjENXlNncXeHVJvkOkZqWcykpwhhxwdNXNB3tAFIfZFyQjTW5DkI8ohd1ueGxQD6UrJXyDID/kYKb3dX4TuDscFTYI/andK5kkQvYEhXRvrKvRrD4ingC5ISIX/zLy5LYRe/2Q3hHF1CAXT90K4xPHMlBV21NuF7dqo9/fAPY8Cjz6BDbjfGe4C99vFJGS4o334fmXiEZSLSfet2MPRx0kPzNZ4D/w7cL4iLlBhxT6p4N2phh7v02q3knMWyMAKPK6odKddFObAp3sAf5MCVp5cuDbkQcd0tyl1JfLpPqW+kCKynunBsIJvb1id6WF3D9gbpm+oFXfYrWDbszTXyGyGLe5Dtlo3sgWmN4g0+M42oOwBhwPWiFGBjpQwZ2KJAt5ITPMkedmrpt7tdB4JLpd4cBpFVnjFUR7F1jH1si7EqR/fHg7RKoKScsa4BoUXQOKhSX5GoFbN5BmZXAmlqDahp/bkMw77xu5t2dbyVj6DOqch1Kv0THg8wsuhrucsbMdRF7eU9pilLn9Z8naeVdqWqbwTyvo8ISm/qgywGal/SuLOfTTyrMQJtiQs9TchAVUhXAudMt94OJjvFcUesTcGtvchTHH7n5OMN/+FeuJJfIthclQPqyY6+DjL6XSnlvH+jxJ9yJe5MP1dx0+4zaOttm6KiPPk38NvCQ2mcQ==), but nothing changed. 

Maybe I'm not understanding how I need to use this now, entirely possible. ;) Did you have a working demo using the headers filter approach?

**Comment by KaelWD** [comment]
Broken in #14728 by 614335814256a342646e579bb171b3d2e044e136

**Comment by stephane303** [comment]
this broke all my custom filter, investigating ....

**Comment by stephane303** [comment]
Here is the working version: [VPlay](https://play.vuetifyjs.com/#eNrVVttu2zAM/RXNL02wxM29jZEUGHrZuvYHhrYPss00QhXJk+W0WZF/n+RLIjtW2ywDhuUlMknx8JAUpbtXJxbB8ZcocpcJOJ4zkbCIKJZwds8QmizbOIrSZfoRcCYxYSByUSoMscRtiX0KhRAhbw44BBFP7518de8YWqJQtC6EOAYhS0qtaz/BSqkZXoCpCiiO9TagsMSScNbumuoZoRJEe8FDUEYJUwZb9SZiFXPBES3bMeXS83m4ciMBEbDQsNOWW6aFpGyR50DCi2zPCNCwqkQKREdEa/gUP7mKdMTaSZ2aYj/dfpFlC9W7OZscm3FU4z7eCfwgKgGmXBAoVa5ChyULH8RbhG4VISTn2CjTv2Ezw7WJ//+IBFj4h9Xk8gUHqsUsdnuyUQLzAKlPc7pkInOAFJNGCcujRkuySVTyoT7jQJBIpkbwEnF1PEKY4YRK9Jo509491Gii6Rlq5DKUniEPHR21CkHR0CWh6ouKkUpvSVJMMA/dbXluUAykK8F/AUM/+GMi5HZ/Gbo7HJc0Kf7I7VTM0yB6A0O6NtZ16NcBoEAAXqAYs/CZBHNbCL3+yW4I4/oQSqbvhXCppjcRVthRbxe2a6Pe3wP3PIkC/AQ24H5nuAvcd8tJyHFH+/D9StgjCF8lPbRiD0cfJz0wW+M98O9A6Qr5gJkV+6SGd6ceerxPq91ySknEIyvwuKbSHbcsLIBP9wD+xhmsAr7wbciDjuluU+pa5NN9Sn3BWWI904NhDd/esD7Tw+4esDdE3mAr7rBbw7Znaa6R2Qxb3Id8tW7mC5XeKJEQetuA8vedGrBGjAJkIpg5EysU1I1EJE2Tl79qGt1O5xGp5VIdnGaZlbriME20taZe1cVq6uvbw0NSJFBRZo9CdQGkHlroZwJi1UpfmemVUIlqE3pmjz6rYd/cvS1dyW/5M4hzHEOjTk9YQBN1OTTknMSujrq8pbLHLHX1y5K387zStkwVnVDVFwnJ+NVlgMxQ41Mad+GjWWRFJ9iSsMzfBEVYxHDNZMZ84+FgvldY9Yi9MVR7H8JUbf9zknrzX6inOolvMUyP6mHVVA4+znI63aml3v9Rog/FshBm/2v9hNs82px1iyWUtpy+O3JPnYff9oWvew==)

Notice the usage of `filter-mode="union"`
