### ISSUE TITLE
[Bug Report][3.5.15] table-server header-type error

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#19599]
### Environment
**Vuetify Version:** 3.5.15
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The expected type for the header prop of the v-data-table-server component isn't compatible with the needed format.

### Expected Behavior
I'd expect the following header to be type compatible:

```
const headers = ref([
     {
       title: 'Dessert (100g serving)',
       align: 'start',
       sortable: false,
       key: 'name',
     },
     { title: 'Calories', key: 'calories', align: 'end' },
     { title: 'Fat (g)', key: 'fat', align: 'end' },
     { title: 'Carbs (g)', key: 'carbs', align: 'end' },
     { title: 'Protein (g)', key: 'protein', align: 'end' },
     { title: 'Iron (%)', key: 'iron', align: 'end' },
   ])
```

### Actual Behavior
It thwows an typescript error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVV91u6zYMfhUiwGB3i938NGlrJN3OunXrOmC9GAYMbS8UR0mM40iGLOcgK/Luo2TZlh11x7sxbPIj+YmkKPnlfZCL+PJTloWHgg6iwULSfZYSSe9eGcDiEJAs06/6I+ZMkoRRYURauCaSBJKsUhrkVByoqHQAh2DP1zSNEvSaBxkVQUa2dPk60IJnKp7x83XQGEQ7StZU5Agxby2tNkNdGedRfZ3rg5SyrdwhTHJJ0nNUysk6YVsEmLeWNqdExMq6fLF1yn1wIGmhlsDIvkX9hyLDTNCIZzLhTLFU3jvR7xaXjoRVCUZdO8NKUhZgcWkVBj/zWCSZhJzKIoOU6NVIDFS6SvYZFxLeQdANnGAj+B48LLCnbAEwSC5hTXMML3NYwovh914vR60uAu9B8H8og7/5thDSG9bqmKRcJDSPYDy7bcQbIiOY2zCxQszkqhFlgkuasAgsWSI4CrxxHeBUvZwR+o2m6RFWlDAnm+n1rMNmdMbm1sXGghk2ox5snhL5RNx5mY1vOkwm54mZW2xrKtdnVOY9qPwcpyQRTiqT+aRDZeyo0dRBxYIZKtc9qPyCW4qKlcAN7C7SzPL7EZ8rq61qPtPQklZd0yc7jzGFGAntISds/SWJd+5MTa3ka2ZWPEPMhjTNHFrp+x/t/DtP0yTjmTtPt926jUJLUrWz1Wf/0c6THmzuiywmn6mbzKi7s6ahlYmqofsm56YHnV85o8eY71dOQlej7gabOrJz4yI0D621GEJXsx6MfuKscG/3q1m3VhMrhiEzGzuzc97Tk7NqvelnObgfsEafnh9xblcESX5kMWyojHfgv4M6ZIf6tKrO2CHkeCD8eITThbUqgaeHYMDoF3jGIyLJqS9oztMDheWdhQN1zvyZ7CkvpO9fdJUVr1wSPHSW4Kv4EMD4Ar5tsXDYULZGi9Lyu6+BtRrh1ckV5mkSU/+iBU024JeLDcuLgL3iFl0EPdGjCq/hL6O38DM9foj9Q+B9pIXmStLBa46hwvg+GcLKka3GLflLXSbQJ3kxbMo6nyNXFXL1MdKU0+K6XIKHyYo9+L7yEFRBo+olMKqOv1M7rSdHPbDOCcMriSqhWbcuiC7nUNW27cM0F3aoRkeNgyHou1pk3JSFa1M4DWE2GjWSWml2SEnQahTTR8gNb0H+rISXenO3NKrz249MZKr3e9lo4I9Hoy1uAnHAo+3CGgAkTbZqw+oVW3JVA3XBi3AWpDltFNhgCFfjxDFu6rj3Zq54Q2NQDRoUVCExu57L9oEgX0XSmOIw6mF1ryZUy07PrB6WODnUIGvZmuHWw/oRBx743zSmagJ+YPdml7C8nZsKel5bVf8dVBVumZpbv9FJUVBb2/w0GIDpuU3BYnWz1+alvveoNRFD/e+AblVMozLDPNTD+2sOQ7mjzK/2j9k0KlBrxljrryNqg6a/6zU2lJSoBnQJ6y6u+rXMB+63xWX5G4I/HYPTkBVpqh9v/wKagxUb)

### Other comments
Could be related to #16680 but not 100% sure

**Comment by KaelWD** [comment]
The workaround for that is `as const` so the string literal types are inferred correctly, but yes #16680 will allow you to import the interface instead.
