### ISSUE TITLE
[Feature Request] Chnage order of tabs with mouse drag

### ISSUE THREAD

**Issue by LeonSnajdr** [vuetifyjs/vuetify#19592]
### Problem to solve
Changing the order of tabs by dragging it with the mouse

### Proposed solution
The dragging of tabs could maybe work like in the browser.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
