### ISSUE TITLE
[Documentation] global theme

### ISSUE THREAD

**Issue by aigolee168** [vuetifyjs/vuetify#19595]
### Environment

**Browsers:** Safari 17.3.1
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://vuetifyjs.com/zh-Hans/features/theme/#section-66f465394e3b9898

### Expected Behavior
I  can change the theme during runtime

### Actual Behavior
I  can't change the theme during runtime

### Reproduction Link
[https://vuetifyjs.com/zh-Hans/features/theme/#section-66f465394e3b9898](https://vuetifyjs.com/zh-Hans/features/theme/#section-66f465394e3b9898)

### Other comments
documentation is error

**Comment by johnleider** [comment]
Can you please expand on the issue your having? It doesn't make sense.

**Comment by KaelWD** [comment]
#19588 is wrong, those are refs so you do need .value

**Comment by b-maslennikov** [comment]
[working example](https://play.vuetifyjs.com/#eNpVT8tuwyAQ/JURFxKpte+Rk7b/0FvdA6HYQcGAYLFUWf738pCq5IJmmN3Zma+NxSD7D++7NSl2YgOpxRtB6jJaYFhfhfcVVnIli3dptLyfR0Zuno36vKlFjezSGKjQoa+jzSLj5jH0D96ZRhm0J0RFqZ3Qi3eBsCHFZosdU3ALeM5GevrlZQ+QzkZql3D+Hz4cmzolK0k7i4d8hyO2VqJudbNxV2E6KzJehUnF50mRKQRlqYndjwh3vIEbPd+I4wRefnIaYC+9WpPcge0vNhlTn+8/1uF4rg==)

**Comment by KaelWD** [comment]
#19888
