### ISSUE TITLE
Placeholders not working on v-text-field (9.0 dev)

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#196]
This use to work...

            <v-text-field label="Computer Name" v-model.trim="computerName" @keyup.native.enter="enterKeyPressed('computer')" placeholder="My Macbook Pro">
            </v-text-field>

Now no place holder.  Maybe a design decision, no idea, but I found it useful in one case.

**Comment by johnleider** [comment]
The placeholder is the label per spec. If there is a large enough request for floating label and placeholder I will see what can be done. Will leave this open for a bit to gather feedback.
