### ISSUE TITLE
[Bug Report][master branch] Possible bug where string values are passed as transition hooks

### ISSUE THREAD

**Issue by yyx990803** [vuetifyjs/vuetify#19617]
### Environment
**Vuetify Version:** latest master
**Vue Version:** latest main (soon to be released 3.4.22)
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
This is discovered in Vue core ecosystem-ci after merging https://github.com/vuejs/core/pull/8953

See linked ecosystem-ci log for the test cases affected.

### Expected Behavior
No string values passed to onBeforeEnter hook

### Actual Behavior
String values are passed to onBeforeEnter hook

### Reproduction Link
[https://github.com/vuejs/ecosystem-ci/actions/runs/8692149431/job/23836077334](https://github.com/vuejs/ecosystem-ci/actions/runs/8692149431/job/23836077334)

**Comment by KaelWD** [comment]
We're passing functions not strings, this is a `transition-group-stub` from vue-test-utils.

**Comment by alecgibson** [comment]
I've opened https://github.com/vuejs/test-utils/issues/2411
