### ISSUE TITLE
[Bug Report][3.5.15] v-menu be closed in second time trigger by selecting month or year when used in shadowRoot

### ISSUE THREAD

**Issue by wyhsunflower** [vuetifyjs/vuetify#19616]
### Environment
**Vuetify Version:** 3.5.15
**Last working version:** 3.5.15
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7, Windows

### Steps to reproduce
1. Choose one date from "Second DatePicker" which is using in a shadowRoot. For example, Apr.30, it works!
2.Let's change the Second DatePicker again,  If you click the those icons to switch the month or  year, the menu will be quickly closed even if using the :close-on-content-click="false" in v-menu.
<img width="415" alt="Second Picker" src="https://github.com/vuetifyjs/vuetify/assets/8914703/416f8328-0381-4e5a-a244-dc90b1a03a42">

3. The operations of the above 1 and 2 steps can be successfully completed in the first DatePicker

### Expected Behavior
v-menu won't be closed in second time popup if it using in the shadowRoot 

### Actual Behavior
v-menu was be closed when using in shadowRoot even through using close-on-content-click="false" 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVV21v2zYQ/iuqWkAKYEl9yxcvKTJkHbYv27AW24e4aBXpHDGhRI2klGZG/nvvSEqi5DhpBcM2yeO9PHf3kLrYhUoW2c9tm/YdhOvwREPd8lzDu00TBCd9kret+WsGhWh0zhqQbgonS9a/+5VJpU8y+jvO/4I6/mLFDcqeZN7A6cqWymhmsJU8/Wyak8xzFYeqkKzVgQLdWS2sboXUQZRmSt9xUGmhVOQtTE4FWylqEpymCA5feGf9rlb2t4Qten7eKS3q9xxqaLRbuQJ93kmJE783SudNAW6hkIDaEWk3bqXoWWlX750HS6Nu0z8daLa988Vo7Iuei7odw6BBWsAYgzMVR6IHyfO7aBWUoujI6/S/DuTdB+BQaCHjKO0TJ5SMCSqjoyNSg2OlgyIvKig/GEiD02B37y2RE6dTpDE54m11fo8iLq7YgasrBHI9QG1AzjuuP9rpiLOrSkcOvXuLm1OO4XYKYqcfJyebmA+jgHyNj4LTd4N+tg3iZ34wFwOuRj76dDR58pgY6j0A5rA7CKLnbk9iYkxsQVYA2uSHHhMJRmR/JFaxbB61a+Kf4rQq0ZkLqyGqtG7VOsuKskmvVQmc9TJtQGdNW2dndcmyLeb37Dj9mmFjZDXmQ7Kcl6DYVcNIaVqzxjSNw/xxlc67szfpcfrqGMlA6WEu4fmlbT+jybg+ZmespE7yR9OD67OcTGG7DjyciS8XlYTt6SZ8sUMt95vw0xeH9yK3ZAPV+FqfzAvtWSTjN+Bc/CskLz3X9iljKPxadI2GEstzEZ0Ugrbqiqn0BfAU4fobp/4Q2Myuyulx/LYV8j06Fs+BHLQJDikXV3G0xQcZYISe5G2D24eMpkjF0JTnFeNlPJdMCy4asC6Mu6gRfdcHY2P3ebIP6R+EPOVadkCbhm0PkJjR9AMENtAGIkanRIwqW7UHOnO8jcDvkznBboX/vLxGk2muqF/iYRMFdo5m4ateWWL6TF7g8KmNLj612DbOe1C4KrR0VhmWXRE+GMw+O9pG8stOUR3FUUVFmtxSlSI+AwoLSVu1c+HVfn0bS9gA9DP24KUo72aJbuB2f2u8u6fsnGT2AMejO1yF9lRL6rxFohENXkyMexu3oDbheE5sQmQZGm/CgZ+6pr25ShFGIqCzNyMXpaDq5FKKW4UH/DUqcdVgVBBRzdU8TXOvH6A5tLGnO0ODWJQJVlIJEuR32Dl7YBsafZu+fmWNLtb2YnMZwQ/iyVlzoxZQIh+THxc/EvABXkdCHSzRddK7f9CV8tDNbIeFvD109/m+29nQsUzj0cX+hxKbFpXG25wrMEWJVj+yGkSn4/nxP+1J+5x31O5EOQa2VXD88uW8KBcXY7rrfkRaDvDjucqaQFV5KW6JpqcbsRH/AOhtOZ8M+oTRueR5swmHO/JjV2hPzUh4hIblu2AN+RVIVGxCCnH/KEWx+Fdnl7M5uE+mbYWhEo0t0jflZPDp1AlOvD27npVo1uWM2IG8cEeFO98rcevhu8yuFQI876yKjvNH09YnSDmdxXeda43HJYLkPLM9Q/RKKQE+jHETHkgc5+beDOtrPLQUJKIxBw5SWlJwFEB546gVG5I6+BM8zwvN+hwPLRTcGfbGi8n0AtUnRP/JlgEvA2w04wAZ34SeR4SfmbhkTYljo8clfNo/vnXN0DBGSEHS2nic6YPABIg0oMtMNLj4+u00v3RomD/rWppYm9XE9NkejJg7DydEinz33BpfDyl1B6p3esPDysUrAJ46mALj6efPtzJvbdvjhTapgN4j1sHbl30VPLM1nTf6p/31cilADHe/oiIzX5++Ab+HIz0=)

### Other comments
Hi, Vuetify team, since Front-end micro app more and more popular, this could be a common problem, so I did in-depth research about this issue, and we have a result.
The root cause is that the v-clickout directive using the wrong lifecyle, so, I want to try to fix this issue.

**Comment by cgodo** [comment]
This issue actually affects all components that use VOverlay in the Shadow DOM, like VMenu, for example. The following Playground.vue demonstrates the issue.

Whenever a menu is opened and closed for the first time in the Shadow DOM, the next time trying to open the submenu, everything is closed immediately.

```
<template>
  <v-menu v-bind="$attrs" location="right">
    <template #activator="{ props }">
      <v-btn v-bind="props" class="ma-5">Normal Menu</v-btn>
    </template>
    <v-list>
      <v-menu location="right">
        <template #activator="{ props }">
          <v-list-item v-bind="props" title="Submenu" />
        </template>
        <v-list>
          <v-list-item title="Submenu item" />
          <v-list-item title="Submenu item" />
        </v-list>
      </v-menu>
    </v-list>
  </v-menu>

  <div ref="shadow" />
</template>

<script>
  import { createApp, h } from 'vue'
  import vuetify from './vuetify'
  import { VBtn, VList, VListItem, VMenu } from 'vuetify/src/components'

  export default {
    name: 'Playground',
    setup () {
      return {

      }
    },
    mounted () {
      const shadowRoot = this.$refs.shadow.attachShadow({ mode: 'open' })
      const shadowApp = document.createElement('div')
      shadowApp.id = 'shadow-app'
      shadowRoot.appendChild(shadowApp)
      document.querySelectorAll('style').forEach(styleElement => {
        shadowRoot.appendChild(styleElement.cloneNode(true))
      })

      createApp({
        render: () => h(VMenu, { location: 'right' }, {
          activator: ({ props }) => h(VBtn, { ...props, class: 'ma-5' }, 'Shadow Menu'),
          default: () => [
            h(VList, {}, () => [
              h(VMenu, { location: 'right' }, {
                activator: ({ props }) => h(VListItem, { ...props, title: 'Submenu' }),
                default: () => [
                  h(VList, {}, () => [
                    h(VListItem, { title: 'Submenu item' }),
                    h(VListItem, { title: 'Submenu item' }),
                  ]),
                ],
              }),
            ]),
          ],
        }),
      })
        .use(vuetify)
        .mount(shadowApp)
    },
  }
</script>

```
