### ISSUE TITLE
[Bug Report][3.5.16] Unnecessary letter spacing in Arabic buttons distorts the button appearance

### ISSUE THREAD

**Issue by YasinDehfuli** [vuetifyjs/vuetify#19627]
### Environment
**Vuetify Version:** 3.5.16
**Last working version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Firefox 124.0
**OS:** Mac OS 10.15

### Steps to reproduce
To fix this bug, I'm trying to add a class with letter spacing 0 in component style or main style. And it works carefully.

```
<style scoped>
.v-btn{
  letter-spacing: 0 !important;
}
</style>
```

### Expected Behavior
<img width="381" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/110921275/1de90cb7-ff5b-4fc3-b6e4-1128fbb7a5ec">

### Actual Behavior
<img width="382" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/110921275/ca896b21-7d92-46af-bf96-4bec7b36374e">

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1U81O20AQfpWRLwGpS6gKVRWFqH2BqnfCYW2vw4q111qPTRDKoVJDOfAetBwaofIw6/Iynd3EfyBWSrwz38zOzzdzeh0UJhp/yfODqhTBJJiiSHPFUczmGcC0YkpHXH0zupKxMBBLczIPDKp54A28ScRNvBUAIsWLgkzSJeMlakiv2CcwusxiEbOlgnDBQsWji3nQeITa0MvkonMeSbxix4dQpB0ulKg4Sp2RyfuPnT7lS3YpYzwn/YejowbYpUWJyXQBVBzB86DLi7NjEhvH40MSuMKt0bhz3lbFJLWjVXZqlKjEDOpb+0i/DUzHA2CevXYpyrABGwjA/rKP9v75Duy93dj7el3/BPtUr0l8pCvJt2RCBvUPsH98KOfgApMFSf9+1zfPd3Zz0AvY5PIqYovsquoVm2iTwmfySCUe5EZUIsNBz3rEvcnYsFEolsgSKVQ7G+5ULNWxUOScSFPgV56KjlJ3JqZUwkX13yGmeOhd32hR33jmiu1SeElJiD2ZsuJG8sxNQUKzPwwa0gZc9BWRVtpVH6ryRe5Nw3xc3y3YXktEnUGiM2SXQi7OkaUilmXaboZaQM5Zb7p7g+wH5cGV6JgeEk11DOh1PDaLuWN7u8gkDDaZtNNxb9dJLCIjc/TmYplrgxCLhJcK4Xr7YsyRT2BvH05msLfTAbQ8TmA0etdoPXsTOO3SrTj1y7m2nu7IBPY8sg9GYGkyQENtHbCzA0b1d6J8bR+68bdPduNWZkPSXwfc1GtqEs2DQ0bdI6s2sbPdbbXvLyvXh7Zy1wW8UgKKSOcipiHyIiHB6l1WKuX/zv4DlzfKWg==)

**Comment by Ai80-8** [comment]
Delete it all
