### ISSUE TITLE
[Bug Report][3.5.16] v-carousel-item gradient not working

### ISSUE THREAD

**Issue by thany** [vuetifyjs/vuetify#19631]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Firefox 124.0
**OS:** Windows 10

### Steps to reproduce
1. Open the repro link
2. Notice how only the first carousel item has a valid CSS gradient.
3. Inspect the document
4. Verify how the first item has an additional `v-img__gradient` element, which doesn't do anything useful.

### Expected Behavior
That `v-img__gradient` item should probably contain the gradient specified in the `gradient` prop.

### Actual Behavior
The gradient in the `gradient` prop has no effect.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9kkFuwyAQRa+CWLWSbfaRG6nnqLsgMLFJMCAYXFVV796xkzQkm0iRkg2CN/DnD/ofPzxFJd5DaKYMfMVbhDFYibDuHGPtVMsQlu1yUN6hNA7iER2gjD4nsP/sgtaGFM8VxqjfW8cHxJBWQijt5s5ott+71Cg/CjPKHpKg9zoJ7dU+NbvQd7zUUH6CWII+Sm3AISlb8idjfSIv6NnGI/qxYl8DmanYxkq1fy0V1624ckzDPGCcwSPYm+M8y03KLg30W/cZOpopKqeczOgiKDM55KgVRb6y07ClS7pz/Ldy2dpl+fwDHdnRzA==)

### Other comments
The documentation is ambiguous on what exactly the `gradient` prop is _supposed_ to do, so we are left with nothing but the assumption that it is meant as a gradient overlay over the background image, and underneath the content, that is set using `src`.

**Comment by SonTT19** [comment]
`gradient` only supports [linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) syntax
for example: `gradient="to top right, rgba(100,115,201,.33), rgba(25,32,72,.7)"`
or with you reproduction link: `gradient="to bottom, white, black"`

**Comment by thany** [comment]
Oh I see. Can this be added to the documentation please?
