### ISSUE TITLE
[Bug Report][3.5.16] [VBtn] has no background if in absolute parent

### ISSUE THREAD

**Issue by KIDS-interactive** [vuetifyjs/vuetify#19636]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create an absolute parent, put an v-btn in it and set a size of `size="50px"`

### Expected Behavior
The button has all functionality from before

### Actual Behavior
The button has no background and so no click transition etc

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkctqwzAQRX9lqo1biB+ldOM6ge76B13UXfih2IKRJTRj9xHy75UcG1zIIhuBNHPPvTP6OAlyTfpqbTKNUuSiYKktViwP5QBQtGoC4h+U+1JYQ4qVGXKoajI4siwFNFgR+aLG+DErxazyuimueYBV4esbCanfgHvO7LcXAEtiKNJZscprB+nhci4vIcjqVXdxjeOMWqJ9qZb7HALyBXqpup7X27XUCxRm78Ug9Q5X7P+FuGEq0hWidwjk7VArv0g3C/ZXapyyDCR5tHOj0tY4hhM4eYQzHJ3REPm/iUI7QGMGvy5NHexDx330JhENvBuH7V30EAwuSA8T590wIu7EU5Ilmfj8A3tMoPU=)

**Comment by KaelWD** [comment]
Buttons have max-width:100%, your absolute element has 0 width.

**Comment by KIDS-interactive** [comment]
@KaelWD the max-width is set by vuetify and should be removed if the user sets a size with px!
That's not an issue made by me
