### ISSUE TITLE
[Bug Report][3.5.16] No clearable for VNumberInput

### ISSUE THREAD

**Issue by etienne-monier** [vuetifyjs/vuetify#19643]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Chrome 121.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Add clearable prop to `v-number-input`.

### Expected Behavior
A cross on the right to clear input. As suggested in `clear` slot

### Actual Behavior
Does not clear

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkLsOwjAMRX8lygx0j0IlRn6AhTC4rSsiuW6URxfEv5MGKlqpi2Wfe+XX/SWDb6uLc6cpoVRSRxwcQcTasBB6OoJzJS1FO3IEy+h/qEBOQ4P+aNmluGAhlMcJfcCzkT1QQCP/2tzGj3QDb4FjdnTYQ6K49hA0SFlaM/W0HV7nOXtdleWAu0pLCB4awgXVutruvZyY8fbGmXxfoKvVaxLnlbOpMyzfB05EJTw+mxdp1A==)

### Other comments
It seems this property was not implmented yet, is it ?

**Comment by johnleider** [comment]
We may need to omit that prop because design wise it has too many loopholes. What do you think @yuwu9145 ?

**Comment by J-Sek** [comment]
I can see `clearable`, persistent icon, custom icon and events all working as expected after refactoring (PR #19714).

**Comment by yuwu9145** [comment]
Yes, number input is just a wrapper having numbering features on top of text-field. It doesn't hurt to have that prop by default offered by text-field
