### ISSUE TITLE
[Bug Report][3.5.16] VTextField density of button icon

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#19644]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

![image](https://github.com/vuetifyjs/vuetify/assets/136077/5024f8ad-c578-4910-a43a-0de0638fcdac)

### Steps to reproduce
It's look like the VTextField's height is different if we have a Button Icon in templates. 

### Expected Behavior
The "density" should be the same for VTextField and Button Icon

### Actual Behavior
The height is different when Button Icon in template

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtlE2P0zAQhv+KZQ4FqYlZunCouqsuSEgrwQUhLoSD20wXg2Mbe5JlVfW/M5OENv0AekVaKYoyk3ee1/Yk83ktU1yqmxDypgY5lTOEKliNcF04IWZNpkNoHzmotHF9QOGnD/5+G3H8xttBzJmP8BPfGrClsHoB9qqQnFlxppCiBJcMPlB26augl1jI65naFe1YnN6nn3K7qdEzyQLC2YZDBEF+b188CRECuDIzzkE8kLHba3TCLL0TjY5GOyQqVRp3lk+HuOVyZpCyKk2WftQ6wkkxy9+DqwXRTKPRR/YjtTsN7yremYS3tCWBBi1QRYu4oCWq0x6qNTm1WNWu9vgcFB/E4Smq7VfEgmFf/teePvbvX/2jcDcQZmo3LOi5nyIDbuEoTMtoAooEWHdDxlTBRxRrEWElNmIVfSVGNJhGLBeCNpBQoF6IK1Y8Hd1Zv9B29IzRHYwwciw7TlbpkH9L3tFcW3N90b9IhZyKNsM54nNcyK+IIU2VWpaOykqwpom5A1QuVGpOMhVrh6aCrPTVfJJf5i8mqqQWDfM5pCpbRH+fIBKlkOOBD5rVwxlevZIsXuYXrzqLPpfRP5DY44idRV8jxH187cL3u5yax/W9Yn6ZT/LnW2qf/eu6FSUbiBl9riXEQ5M/n9dB2d6ZHbw78mf7TeHokpuxq61tb19+AXw9AcI=)

**Comment by yuwu9145** [comment]
It's because default density icon v-btn height 48px exceeds compact text-field.

V-btn can have `density="compact"` applied, just like the second one does in playground

<img width="323" alt="Screenshot 2024-04-19 at 4 25 11 pm" src="https://github.com/vuetifyjs/vuetify/assets/5698884/51879b94-944d-40a6-867f-2fc11b2ab80a">
