### ISSUE TITLE
[Bug Report][3.5.16] All Input Components #append slots somehow losts ability to react on isValid prop

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#19650]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create VTextField
2. Add #append slot
3. Add VIcon component or something similiar, actually you just need condition -
 {{ isValid ? 'mdi-check' : 'mdi-close' }}
4. I want to change icon and color based on isValid state (based on docs it is bool or null)
5. Condition is ignoring changing of isValid prop (I have also tried v-if)

It is also not working in VSelect, VAutocomplete, VTextArea, etc and been tested in 3.6.0-alpha2, but it's not working there either.

In playground is working (workaround), and not working example.

### Expected Behavior
I expect condition to react on change of isValid state.

### Actual Behavior
It is doing nothing.

I have found workaround - to add isValid._value to condition, but it shouldn't work that way.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU0tv2zAM/iusB1QJEOex7jAESYddBuyyww67JMGgyHQtVLY8SXayufnvo+RHnO5U7GJQ/Pj4SH7eNZE1YvG5LOd1hdE62jjMS8UdPu4LgE0d2wzRgVDc2u0+ys8xr5zeR3CSicvI87Bc7qMQHMJTbXIwmBLizQEKoMOzi1OJKumdAHWc6wQVxRc8x310RdZCV4VDQ9CKeowAUyn0bHzGd2+PUcWPody3V+UM/qqkwaH1QIyo9UPDO16WWCSU3oC0P7iSCVxGQ4TouziGQjs4afMsiyeI41u8jqXQheevtGffF/oEzFZCoLUM1sDQGG0YrdLKP+iH/PiqEUBzZUHJeSJjkaF4DunhpbRFBpfLTf9FS4Bq/UP7jZTnP2uuKvwv5qMabx/g6rrRZR91FVSvQHJ63bXqpUeQL71uCtDTCiNLBxZdVYZgmZfaOGi8eOECqdE5MPonWLtFomMdBHVvfchkOvZLKm4J2LGvZMGKzaC13g/Ww2B9YIdxrhdxV5Mxqjr2B3F34K6dsIbtI9zd1fDyAsxrnPY8aJvNRkGTGu7voZ4rLJ5cBpstrJbTa1peUZMjAnWw4DJeEAwi44YL+ulsW+owImRRoXAdm6JSaoSFqx71uUNTrix2G+L2dyEgrQrhJEmMxCATOsNkCk1Ltq3QtAitfgv8xGW77HnQjv92Sb2mZUrzee8UuELjJuyLvw3tInjbRZKqNov20nTj6DLzrMPn8BeHC4Oi)

### Other comments
Before submitting I have found this and it may be related, but I'm not sure. I'm sorry if it is duplicated.
https://github.com/vuetifyjs/vuetify/issues/18355

**Comment by KaelWD** [comment]
Yes this is the same as #18355
