### ISSUE TITLE
[Bug Report][3.5.16] Problem with dynamically removing and adding items of an expansion panel

### ISSUE THREAD

**Issue by derwaldgeist** [vuetifyjs/vuetify#19655]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.3.13
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In Vuetify Play

- first click on the delete button next to the B item
- then click on the Add item button
- now try to open item D

(Please note that in the original implementation, I use ids generated by uuidv4. But somehow I was not able to add this library to VPlay, so I am using a random number instead.)

### Expected Behavior
Item D opens, if you click on it.

### Actual Behavior
Item C opens instead. It is impossible to open item D.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVk1z0zAQ/Ssac7DDxHZTPmYwTWmBCwdmOHDDHFRr3QhkSSPJoZ1O/zsr2Uns2NBAp5PEq6e3X28lf3uIrKnya62zbQtREV3YynDtiAXX6stSEsIbrYwjD8RATR5JbVRDYgTHpfTLlZLWkcoAdfDJQUPWxHEngKwvSfLgEUjBCvKZuk1WC6VMEn4aKplqkgV5TlZnZ2eLZQcNe/vfSO1AuoLEcbA8LoYuOTqz6A3DSr4d/CfxdbxYDgJK4vfHhg/x4vuIS8lrxvroMSQMfRe5d5JtqWgh063dJEOaj/ECWTCuMdVHEOAwf5LAFsNfBpKv6j10C2zIHxCZdUp/MUrTW+q4kklg3ecpGdwh2zCUGo2fvD3xVs/nvzPOyHrdIQf+0NwTDimsFryCJLAvyWqXyEXeCQBbjw+I1wLzDUK42KZUd5oID749lEswvSkY4U5TaTGJFL9BWFIJau26jGhVKcNwoYz2+LkdZJvWyuCGkBmXXdBlRIqfcN+bMaMRyxxPGpQ0AiFslxB5Ritfah/ZAwlbGTAswJi2p+aY6rEZ27PPzDOV0RRR+I2I2PO/I3HDeFptYGsw0FbHBNU9NDH1S8ZTrvx/wyIsiGAuuj447/3PoKsKZfLT5+CV6pW2E/hQ3YunI77IR2Ka7QmDmrbCndQTo34RqdLb1jkwdoLoFSr25WBpLXCOfrTW8fo+tY4ah6pCiF9drWa89CwO7lxacxBsDkBQsI3CAu60GXQ3V0r/h4lWsFGCgZf4179BN5wBNgZHTNg/OKaGU+nLZZVQGKIQgIMxB57qx3ckVGhaXLRjdU/rnwc/PXlz44lVPXbxZFf/rafnsz3tO0rxID9uXX/hIMXMvM1Wa65WsyUZZzsDORyi07VDITD4GycPM85Y6iNPb7Bg/gw6zOv+Sjs+b/3YX/qh16K13lkwHCC4Lcz0MB70uTv3QxmGB7+3dPfCSCL4aN19r4PsKNDd9ddQc8tlitdfQc5f6bu3h1uo3xsto+4FJG2ozn5YJfElJezGnoUFvBuKHV8Zta2/Gwr8tXFO2yLPKyZxH3aZb00mweVSN7mHXb3JzrJVzrh1ebgGs4Z7aBn17x9lhK85J5BdISw3rXS8wYlVzdWL7GV2/qJjHtgzsFgAlIsFM/HjFXyCrx6JLl5lq9edi96WCnpjvY8Jd44Ot2BSA5imAXNqTkfbRnkdrU1y6zuJ/9HjUrZChI/vvwFchyhP)

**Comment by johnleider** [comment]
A workaround for this is to explicitly define values on the expansion panel.

https://play.vuetifyjs.com/playgrounds/4Srsag
