### ISSUE TITLE
[Bug Report][3.5.16] VAutocomplete value-comparator uses deep `value` for b

### ISSUE THREAD

**Issue by NickdeK** [vuetifyjs/vuetify#19669]
### Environment
**Vuetify Version:** 3.5.16
**Last working version:** 3.3.15
**Vue Version:** 3.4.24
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Have a v-model with a object to preselect a item
2. Open the dropdown

### Expected Behavior
Item from the v-model should be selected in the list

### Actual Behavior
No item is selected from the list

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFU8tOwzAQ/BWTS0BqWgQShyogISQedyQOtAfH3jSGTWzZTgWq+u9s3IY6qqhy42R7dnZnMrHfN4mzYnZvzHTdQjJPcg+1Qe7hbtEwlq8zbkzYhoPQjeeqAbuHdozWa6GpCzz0MGPrrNYS8HaROEAQHuQiOVQFAre8wKgBeRHo9/G4qGWuyJojQljjSt2iV8Q/IB0l88ojEL/h9WBQKH7CdzdqYMqCb22T6eKD/EZeK2VcbF27znk2wO/y2TCJPjSCh6kFYgg1n0Vh09EJq4xnjmzsMle10dazDTkr2ZaVVtcspf+UdnRyohvnWe1W7LZjnKfPgKjZm7Yoz9KLmBQy29Ped842vXUl5yzlhUgnPdIlRtgDR1Vq2yh+KK05tlT7bWas4q56CSMOrO1+169DrULIYy2N2nKpRykVY5WELI+UHklIyXGfFGVyWkiWqyOhJ9B2NTK7KJDTQuWqOhJ6hS/uRsnAXzJLui39Xenf639dl85LPts9BnoGyXbStIiT5Hp6M73MOJqKT6+S5Q/gTFgj)

### Other comments
It seems that the `value` from the object is being passed into the value-comparator which does not have the key used in the parent list item object to compare to.

A workaround for the moment is to utilize the `value-comparator` prop on the component to make your own comparison.

**Comment by yuwu9145** [comment]
Change `item-key` to `item-value`
