### ISSUE TITLE
[Feature Request] Lazy prop on v-data-table expand

### ISSUE THREAD

**Issue by amesas** [vuetifyjs/vuetify#1967]
Lazy v-data-table expand would be improve ui experience.

**What will it allow you to do that you can't do today?**

Lazyload content

**How will it make current work-arounds straightforward?**

Exactly the same as for the lazy prop on v-tabs.

**What potential bugs and edge cases does it help to avoid?**

Lagging with long list or complex content.

This is supposed to be something very similar to the lazy prop on the v-tabs

**Comment by KaelWD** [comment]
#1994 made all `expand`s lazy.
