### ISSUE TITLE
[Bug Report][3.5.16] [VTreeview] node without children isn't displayed as a leaf

### ISSUE THREAD

**Issue by simon-lorenz** [vuetifyjs/vuetify#19672]
### Environment
**Vuetify Version:** 3.5.16
**Last working version:** 2.7.2
**Vue Version:** 3.4.24
**Browsers:** Firefox 124.0
**OS:** Linux

### Steps to reproduce
1. create a treeview
2. add an item with `children: []`

### Expected Behavior
The node has no children, so it should display the same as other leaf nodes where `children` is `undefined`.

### Actual Behavior
The node displays a chevron for expansion.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjj0OgzAMha9iZWGhRV2jgNRzAAMKlhopDVFi6IC4e4MD/Vlsv8/ye25XEYOu7t5flxmFFIrw6e1A2HQOQC2XwXseWejJ0WAchgMxpIC4GHyBNOk41p3g3olGVd/taZLQv8tOcoiqfsKTjDoYTxCR5vxDOowE7A41tNlxPV8xo4RbeSoyZFFCMTksPlA/jB0DOgltf8CNe7+n57yUJLbSzdZy6d/+kF0v)

### Other comments
Not sure if bug or feature request, but this used to work in Vuetify 2.

**Comment by d-schoenfeld** [comment]
IMHO it highly depends on the use case, so it should be configurable. Sometimes you want exactly what it's currently doing.

**Comment by KaelWD** [comment]
You can pass a custom itemChildren function that returns null if !children.length.

> but this used to work in Vuetify 2

v2 was inconsistent, it depended on whether `loadChildren` was set.

**Comment by simon-lorenz** [comment]
I see, thanks for your response!
