### ISSUE TITLE
Validation on submit

### ISSUE THREAD

**Issue by stecapra** [vuetifyjs/vuetify#1968]
### Steps to reproduce
-using the code in the docs https://vuetifyjs.com/components/text-fields, at step 16, pressing the submit button doesn't make it appear the rule text when rule not passed(e.g: require rule)
### Versions
-any version of vuetify

### What is expected ?
-pressing the submit button without touching the text field should show the rule text if the rule not passed
### What is actually happening ?
-the validation rule text appears only if the text-box is focused and blur

### Reproduction Link
https://codepen.io/stecapra/pen/VMzZoV

**Comment by stecapra** [comment]
My apologize, but i've just noticed that using `error-message` directive it can be reproduced the desire behavior.
Sorry for the incovenience

**Comment by KaelWD** [comment]
As this is a problem with the example, this issue should be on the docs repo: https://github.com/vuetifyjs/docs

`v-form` has that behaviour built-in, that example is for if you want to roll your own validation for whatever reason.
