### ISSUE TITLE
[Bug Report][3.6.5] VDatatableserver items per page not working

### ISSUE THREAD

**Issue by nrichard-coexya** [vuetifyjs/vuetify#19684]
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.4.14
**Browsers:** Firefox 125.0
**OS:** Linux

### Steps to reproduce
Just try following the documentation on v-datatable-server with items-per-page
simply doesn't work

### Expected Behavior
5 items in the table when items-per-page="5"

### Actual Behavior
table displays all elements regardless of items per page

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kk1ugzAQha8y8oYNLiEt/UG0Us8RsnDpJEUytmUPbBB3r4FGpDFhY3nevM/SeN6hZ85WyacxD12LLGcFYWOkIPwoFUDRcWHMdJ2KSisStUL7J03ityDBSXxJ5A5th/bSA8hr/5zjBi034ozvJctKdrfNtaFaK+dthyxOd8cVr0R1ph/vSPdhdwQXDaBXosE8QokNKtpFQ3wjpV66D+xD4HETeAqBbBN4DoGXTeA1BN42gXRtaj/2Qlz98rLVZGWtlxj43v8cjMockyK5io8vXWVrQ+CQ2jlFdWO0JejB4gkGOFndQOSTF43s7PY+NsSqlXI6jr88HdDl)

**Comment by devseckobz** [comment]
Just update to the latest version

**Comment by nrichard-coexya** [comment]
Just updated to latest version 3.6.3

https://play.vuetifyjs.com/#eNp9ksFugzAQRH9l5QsXDCGUtEW0Ur8j5ODSTYpkjGUvXBD/XgONSALhZs/Ms7TeOXbMmiL80jpoG2QpywgrLQXhZ64AspYLrcfjeClqRaJUaP6lUfwRJDiJb4ncomnRXD2AtHTPWa7RcC0u+JGzJGdPbV5rKmtlXeyY+NHutJKVqC706xLRfukO4KwBdEpUmHoosUJFO6/3H6TISc+B/RKIN4GXJZBsAocl8LoJvC2B900gWpvajT0TN788bzVcWeu1Bs6778GgTDXJwpv6uKstTKkJLFIztaisdG0IOjB4hh7Opq7Ac83zBnZKuxzrfdVI6bM4OAQxO/0BqLjQZg==

The bug is still there

**Comment by nrichard-coexya** [comment]
I tried updating to 3.6.5

The bug is still present: [repro link](https://play.vuetifyjs.com/#eNp9ksFugzAQRH9l5QsXDCEpaYtopX5HyMGlmxTJGMteuCD+vQYakdaEmz0zz9J659Qza8r4Q+uoa5FlLCestRSE74UCyDsutJ6O06VsFIlKofmVJvFLkOAkPiVyi6ZDc/MAsso9Z7lGw7W44lvB0oI9tHmjqWqUdbFTGia780pWorrSt0ske98dwUUD6JWoMQtQYo2KdsEQ/pMSJz0G9j5w2ASefCDdBI4+8LwJvPjA6yaQrE3txl6Iu19ethqvrPVWA+f97cGozDXJ47v6uKstTaUJLFI7t6iqdWMIejB4gQEupqkhcM0LRnZOuxwbQtVKGbJDdIxSdv4BqL7QaA==)

**Comment by KaelWD** [comment]
This isn't a bug, you have to do the pagination on your backend.

**Comment by sbaum2s** [comment]
> This isn't a bug, you have to do the pagination on your backend.

What then is the purpose of items-per-page if it does not split the chunk coming from the server into smaller pieces?

**Comment by KaelWD** [comment]
It controls the dropdown in the default footer and can be two-way bound with v-model, you still have to do the pagination yourself.

> split the chunk coming from the server into smaller pieces

Feel free to open a PR if you come up with a generic way to do that.
