### ISSUE TITLE
[Bug Report][3.5.17] [HMR] Something went wrong during Vue component hot-reload. Full reload required.

### ISSUE THREAD

**Issue by superCong** [vuetifyjs/vuetify#19698]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.25
**Browsers:** Chrome 123.0.0.0
**OS:** Windows

### Steps to reproduce
 <v-app>
    <v-navigation-drawer>
      <v-list>
        <v-list-item title="Navigation">{{a}}</v-list-item>
        <v-btn @click="sum">4516</v-btn>
      </v-list>
    </v-navigation-drawer>
  </v-app>

### Expected Behavior
The webpage can be refreshed when saving

### Actual Behavior
App.vue?t=1714120443791:106 TypeError: Cannot assign to read only property '_' of object '#<Object>'
    at assign (<anonymous>)
    at updateSlots (chunk-AZ23VQUG.js?v=ec09baeb:5952:9)
    at updateComponentPreRender (chunk-AZ23VQUG.js?v=ec09baeb:7620:5)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-AZ23VQUG.js?v=ec09baeb:7535:11)
    at ReactiveEffect.run (chunk-AZ23VQUG.js?v=ec09baeb:434:19)
    at instance.update (chunk-AZ23VQUG.js?v=ec09baeb:7602:17)
    at updateComponent (chunk-AZ23VQUG.js?v=ec09baeb:7411:18)
    at processComponent (chunk-AZ23VQUG.js?v=ec09baeb:7345:7)
    at patch (chunk-AZ23VQUG.js?v=ec09baeb:6800:11)
    at patchKeyedChildren (chunk-AZ23VQUG.js?v=ec09baeb:7755:9)
(anonymous) @ chunk-AZ23VQUG.js?v=ec09baeb:2015
(anonymous) @ App.vue?t=1714120443791:106
(anonymous) @ hmr.ts:77
(anonymous) @ hmr.ts:311
(anonymous) @ hmr.ts:277
queueUpdate @ hmr.ts:277
await in queueUpdate (async)
(anonymous) @ client.ts:205
handleMessage @ client.ts:203
(anonymous) @ client.ts:91
Show 8 more frames
Show less
App.vue?t=1714120443791:106 [HMR] Something went wrong during Vue component hot-reload. Full reload required.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUk1v2zAM/SuCLm3R2EaWZgOCtMg29LAdumHbbd5BsZlUrSQL+nAyBPnvpSTHddKiKGAYJh/J9/jovztqTVV81jpvPdAZnTuQWjAHN6UiZN5mTOv4GQPFWr5mjjcqqw3bgOmgCApuXR/3mYzjROK4E3Bd0rt+QElvdju238+LQd1x+9IpsqgErx6x03qJLVfT8cfQgdAzdTfhIBPD13UGJK0zLwZrYmgrw7UjFpxP23KpG+PIjhhYkT1ZmUaSM3ToLJQTIsARRq4Dej6+CJmVV1XgI6jz/ILskhaWt0x4uLxMYdUo64i0a2ztoADsg6AkAcnpiDqLlSu+zh9so/AocVpJq0ZqLsD80IHJlnR24CkpE6LZfI85ZzyMDvnqHqrHV/IPdhtyJf1pwIJpoaQ95phZg0vw7e872OJ3D8qm9gKr3wB/gW2ET0cOZV+8qlH2oC6q/RY95mr9x95uHSh7WCoIjb7E+pKi71/fWP1Z7iSfdH7igz6mK2aS6RMnE3A8BlmS3HvntJ0VRVUrbKtB8NbkClyhtCwWWFYYrxyXkNWNXEzyq/zDtKjxBxzmc7AyW5pmg+bilMHuOMDx1f93cHWVSDHNx58SRZfLBFvawPFidhGvaTIDqgYTXH/fTidtR3udYC92G5i+HykvRHz9ewIr8HIp)

**Comment by tyekx** [comment]
Hello, I am experiencing the same but on linux, just opened an empty project to test it, after adding a single v-nav-bar and v-nav-bar-title the error appeared.

Digging through, seems to be a vue issue, i made a comparison between a working repo and a new install. I found that reverting to `vue@3.4.22` does fix this issue. Whereas npm list shows `vue@3.4.25` from a fresh npm update.

**Comment by webarn** [comment]
I had the same problem
<img width="752" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/23495159/698d4e3c-a406-4d96-909c-99a4151dcc0e">

**Comment by superCong** [comment]
> 您好，我遇到了同样的情况，但在 linux 上，刚刚打开一个空项目进行测试，在添加单个 v-nav-bar 和 v-nav-bar-title 后出现错误。
> 
> 深入研究，似乎是一个 vue 问题，我在工作存储库和新安装之间进行了比较。我发现恢复到确实可以解决这个问题。而 npm 列表显示来自新的 npm 更新。`vue@3.4.22``vue@3.4.25`

Yes, I also discovered it yesterday and the issue has been submitted to Vue

**Comment by superCong** [comment]
> 3.4.25

Using Vue 3.4.23 can solve the problem

> I had the same problem <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/23495159/326234391-698d4e3c-a406-4d96-909c-99a4151dcc0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTc0NTQsIm5iZiI6MTcxNDI5NzE1NCwicGF0aCI6Ii8yMzQ5NTE1OS8zMjYyMzQzOTEtNjk4ZDRlM2MtYTQwNi00ZDk2LTkwOWMtOTlhNDE1MWRjYzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjZlNDExYWUzY2MyYjkwNmNiZDEzMjY1MTEyNGJlMWY3MmE1MzMxM2FlYWIyYzgxMGMxNzA0OWU5YTgwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yZGzd8VXTF2qDTixyr3aJJ_ziFKjJ2YUOdPXJAIMyw">

Using Vue 3.4.23 can solve the problem

**Comment by cyberdestiny12** [comment]
Using Vue 3.4.23 can solve the problem
