### ISSUE TITLE
[Bug Report][3.5.17] v-file-input "dirty" property is not working like in v-text-field

### ISSUE THREAD

**Issue by jvcruz-fastlab** [vuetifyjs/vuetify#19699]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.25
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://play.vuetifyjs.com/#eNq9kc9qwzAMxl9F+NINlvle0sEugz3DuoOXKGBwHCHLYaX03Ws7bZP+OfdirO8npA99P3sVuNGfRO9jRLVWtWBPzgh+bD1APVaGqHxL0QxejPXIJ6mInXVYWU9RziLAWPVDi26zVZl+F6hmvG4tyy5R4YhXoHFo2Pw5fAQJOdgg6KUqfXc9OvlaOBP8l2QPXfvIWaZfBS52yI7y6uz6WYaLWX173KxMt6/1IpNUhoYtCQSUOEVjexpYYA+MHRyg46GHVYpzlWGaGgQuKcAmd728zuhyhhnVetqRpqvDm4/Olef3COyDr1A=

### Expected Behavior
Clear icon button will be visible when the dirty and persistent-clear property is true in v-file-input

### Actual Behavior
Clear icon button is not showing even the dirty and persistent-clear property is true in v-file-input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9kc9qwzAMxl9F+NINlvle0sEugz3DuoOXKGBwHCHLYaX03Ws7bZP+OfdirO8npA99P3sVuNGfRO9jRLVWtWBPzgh+bD1APVaGqHxL0QxejPXIJ6mInXVYWU9RziLAWPVDi26zVZl+F6hmvG4tyy5R4YhXoHFo2Pw5fAQJOdgg6KUqfXc9OvlaOBP8l2QPXfvIWaZfBS52yI7y6uz6WYaLWX173KxMt6/1IpNUhoYtCQSUOEVjexpYYA+MHRyg46GHVYpzlWGaGgQuKcAmd728zuhyhhnVetqRpqvDm4/Olef3COyDr1A=)

**Comment by yuwu9145** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/04a1a44434c9311a0ec9acb07ea3f4b896c558e0
