### ISSUE TITLE
[Bug Report][3.5.17] v-chip throws error in tooltip

### ISSUE THREAD

**Issue by markusheiden** [vuetifyjs/vuetify#19707]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.25
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I wasn't able to build a reproducer that shows the problem. But in my app
```html
<v-tooltip text="tooltip">
  <template #activator="{ props }">
    <v-chip v-bind="props">chip</v-chip>
  </template>
</v-tooltip>
```
causes:
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=true  ... > 
  at <Transition name="fade-transition" appear=true persisted=true  ... > 
  at <MaybeTransition appear=true persisted=true transition="fade-transition"  ... > 
  at <VOverlay ref=Ref< Proxy(Object) {…} > class="v-tooltip" style= {}  ... > 
  at <VTooltip key="EXACT" location="bottom" text="Exact Match" > 
  at <Anonymous align=undefined fixed=undefined fixedOffset=undefined  ... > 
  at <VDataTableRow key="item_4" index=0 item= {type: 'item', key: 4, index: 0, value: 4, selectable: true, …}  ... > 
  at <VDataTableRows loading=false loadingText="$vuetify.dataIterator.loadingText" hideNoData=false  ... > 
  at <VTable class="v-data-table action-adjustment" style= {} fixedHeader=true  ... > 
  at <VDataTableServer class="action-adjustment" ref="tableRef" modelValue= []  ... > 
  at <VCard key=1 > 
  at <VCol cols="12" > 
  at <VRow dense="" > 
  at <VContainer fluid="" > 
  at <MyOverview onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {_pStores: {…}, …} > > 
  at <RouterView> 
  at <VSheet class="h-100" color="secondary-darken-4" > 
  at <VMain> 
  at <VApp id="app" > 
  at <App>
```

### Expected Behavior
Works.

### Actual Behavior
Error.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1P20AQ/SvW9hp71aaoUpQi2opDe2gr4IY5bOwhWdgv7Y5NUJT/zuxuEuyAEBKSZXnfe/PmzXivNyz4hv9wruo7YDM2R9BOCYTT2hTFvC+Fc+kzHRprUEgDfgclEK1VKF2BsMbvNdsda3bQkGrvWnwSDcpeoPUk3RTOWxeK7UicO63IsS8X0rQkTDISRXTOMzu056PUGToE28ePdaP8EcnjjQzoGBovHRYBsHOnc56PRLEJw0Amt3JZ3QVraGGb6FSzxmonFfh/DqU1lHVWJCZyQin78Cdh6DuY7PFmBc39K/hdWEesZv89BPA91OzAofBLwEyfX/6llQ9IbdtOkfoN8gKCVV3MmGU/O9NS7IEupf2tnfUozfIqnK8RTNgPFYNG5Tbpa0a35tcboz/HnVbTVFcbemiPMnUotXBHm8zE2Ia65LgrRBdmnDetobIWlOx9ZQC5cZqfkYz7zqDUULZWn02rr9WXE97KgEO8gqDLhbcPtFxyGcxOBihvH9/Ra6ekFifV52+5xQ4rlViE2OOFN09/05ceTAs+bv19Mx2VjeY64l7MNlq6kuY+HN/ckHZ9/dGBk89N7rSdmE6p9Lp5AsMjdZ4=)

### Other comments
When removing `ref` from `props` my v-chip works fine again. 

I processed `props` with
```javascript
const activatorWorkaround: (activatorProps: any) => any = (activatorProps) => {
  const patchedActivatorProps: any = { ...activatorProps };
  delete patchedActivatorProps.ref;
  return patchedActivatorProps;
};
```
like so
```html
    ...
    <v-chip v-bind="activatorWorkaround(props)">chip</v-chip>
    ...
</v-tooltip>
```
and my v-chip works again.

`props` logged via the console:
```
{ref: RefImpl, targetRef: RefImpl, onMouseenter: ƒ, onMouseleave: ƒ, onFocus: ƒ, …}aria-describedby: "v-tooltip-20"onBlur: (e) => {…}onFocus: (e) => {…}onMouseenter: (e) => {…}onMouseleave: (e) => {…}ref: RefImpl {__v_isShallow: false, dep: Map(1), __v_isRef: true, _rawValue: Array(1), _value: Proxy(Array)}targetRef: RefImpl {__v_isShallow: false, dep: Map(1), __v_isRef: true, _rawValue: undefined, _value: undefined}[[Prototype]]: Object
```

**Comment by KaelWD** [comment]
> [Vue warn]: Unhandled error during execution of scheduler flush.

There will be another error before that. Is this #19685?

**Comment by markusheiden** [comment]
For me it does not really look like #19685, but I am no expert.

There is a type error after the reported error. The full log:
[localhost-1714377903553.log](https://github.com/vuetifyjs/vuetify/files/15146543/localhost-1714377903553.log)

**Comment by markusheiden** [comment]
I tried the workaround from #19685 and it works for me too. So this seems to be a duplicate of #19685 and could be closed as such.

**Comment by ElYaiko** [comment]
> The v-chip is inside a v-data-table-server using a loop. Without the loop it works fine. So it looks similar to #19685. I still wasn't able to build a reproducer from our application, though it reliably fails in our application.
> 
> There is a type error after the reported error:
> 
> ```
> runtime-dom.esm-bundler.js:593 Uncaught (in promise) TypeError: Cannot convert object to primitive value
>     at Proxy.join (<anonymous>)
>     at Proxy.toString (<anonymous>)
>     at patchAttr (runtime-dom.esm-bundler.js:593:10)
>     at patchProp (runtime-dom.esm-bundler.js:760:5)
>     at patchProps (runtime-core.esm-bundler.js:5784:11)
>     at patchElement (runtime-core.esm-bundler.js:5665:9)
>     at processElement (runtime-core.esm-bundler.js:5487:7)
>     at patch (runtime-core.esm-bundler.js:5344:11)
>     at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6112:9)
>     at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
> ```
> 
> [ The complete log](https://github.com/vuetifyjs/vuetify/files/15146543/localhost-1714377903553.log)

I''m having same issue with Tooltips.

**Comment by ElYaiko** [comment]
It happens only in the dev server, in build works ok.
Help please, I'm using `nuxt@3.11.2`.

@vuetifyjs
