### ISSUE TITLE
[Bug Report][3.5.17] --v-icon-size-multiplier value within .v-chip .v-icon class

### ISSUE THREAD

**Issue by treybradshaw** [vuetifyjs/vuetify#19715]
### Environment
**Vuetify Version:** 3.5.17
**Last working version:** 3.4.2
**Vue Version:** 3.4.14
**Browsers:** Chrome 124.0.0.0, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. Create a v-icon and take note of it's height/width. Also take note of the --v-icon-size-multiplier.
2. Create a v-chip and either A) place the v-icon in the content area of the chip OR B) use prepend-icon or append-icon and note the difference in the height/width of the icon. Also take note of the --v-icon-size-multiplier.

### Expected Behavior
Consistent value of --v-icon-size-multiplier. We want the icon to be appropriately sized relative to the surrounding font size (as is v-icon's design) regardless of the component it's within.

### Actual Behavior
--v-icon-size-multiplier produces undesired sizes within v-chip due to
.v-chip .v-icon {
    --v-icon-size-multiplier: 0.8571428571;
}
within vuetify-labs.css

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdksFOwzAMhl/F6gmktWVjYwgNJI7cERwYhzR1V4s0iRJnMBDvTpoOWCdOXCznS+zff+Snj8w7Wd5aW2wDZlfZirGzSjDerDXAapsLa1OaDtJoFqTR7VGCFCn04XqddTXlskX5ss5AGmVcZKRbdMSRlIdlsiUL1qFFXaceR+VR+O+bnyb/Vk+FSlSogPGN46u7vound/TwStySBm4R0oi1AW0YOsGyTTQpVtgYF3Muxr7KwdgvqNzY9kj2PrbL88FE3svnXVBMVhE6IA/BB6HUDqYTqAJ/j7b/O+L+yVlxuVhO57M+Hs1yJPaIvRGSWEcbsVK2Qm8QRMNRTGgIduNEjdA408FDQKZmB+fFvJgBm5gsiukFnHgmpSBOkcDy9EAymR9tSE+GBVqVB4sVj146sgweOQzXA4hp9jnRQakUnr8A29/XEQ==)

### Other comments
Thank you!

**Comment by KaelWD** [comment]
I don't know what the reason for this was: 6969bf78a66b08b81c5d8da8a8ea54bb0b5aa3a4

**Comment by treybradshaw** [comment]
Still occurring with vue@3.4.27 and vuetify@3.6.8
