### ISSUE TITLE
[Bug Report][3.5.17] Failed to execute 'observe' on 'ResizeObserver'

### ISSUE THREAD

**Issue by ker-nicolaib** [vuetifyjs/vuetify#19713]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.25
**Browsers:** Chrome 124.0.0.0
**OS:** Windows

### Steps to reproduce
Change the Version of Vue to 3.4.24 or 3.4.25. Then just add v-for to the v-select Tag like v-for="item in [1,2,3]".
Then click on one of the select-fields.

### Expected Behavior
No Error should appear in the Browser Console.

### Actual Behavior
An Error appears in the Browser Console.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1k8FqwzAMhl9F+NIWkpSuG4PQFnbYZbDT2KnpwW20zovjGNvpBsHvPsVpthRGoYXlYkv/zyfJKOuGPWidHGpkKVs4LLXkDleZAlgcYosSdw5SQYJdZiycGYP2jJ1wEimpeImUk3yLksJXiyZjgUCMnggEk5ULJDI1oE2lbRRI4H/8oaoU1sVBOMRboXLyBzcVSW297eu2jsTwzyRHzY0rUTniLKYDQN/F9HQwsnSTUXiiUWh3RuhWAMAvXRkHOb7xWjpoOljOHU9hPIHlCsbHHIQ5bArrPobe3n3tG6Uweqre1SgaCr+9k/zMTYFOqP3Q4wf3P5lc4Rnmo9oLhWgupVbnoC9cor20SfcPXfLiXJtXvueuuG70zfHmJ+Hi2+U6rhOLmBSqsMmHrRT9aU3GdpYWOl1vPGmibDctLrkeGLpka2q8Zz5i8+Q2uZmRfZ7cJbN7FjlT4+YbvDkVHw==)

**Comment by yuwu9145** [comment]
The error seems to only occurs when manually change Vue version and tweaking code at the same time.

The error couldn't be replicated when Vue version & code stays the same, they don't change when running a project. [demo](https://play.vuetifyjs.com/#eNq1kj1rwzAQhv/KoaUJ2A7px2Kc0AxdCp1CpziDbF8SYUUWkuwWgv97ZdlyEyiBBOrFurtXz706aXMiWuWzlZRRUyOJSWLwKDk1uEwFQNKEGjnmpgsAYmarepES909Jn+2C0DDD0VYEPaIvcJoht7lPjcrnmnBXqYEATECPX6lB4Lravt6F1WteGdfY7jqBVJXUgesJbUoGvXPKmTahKzRhxkRh9U6dEoh1nXmHnSJS9CsqUFJljiiM5SSzM4B3MbschpX0dvswq42pBLzmnOWlBY9HiWStD5P51GJXRQFrl09mvd7uveDaUOeKyR6K37JSBgrc0ZobOPVGCmpoDJMpLJYwGXLwO7oYNvMA5tvAV9z12KyPwYP6r7ujGB7eq4N4GPe4PuNEbPmDqhINE/tzTXu2/pNJBV5hvok9E4jqVmp1DbqmHPWtJs0/uKTlNZt3zjMv7zu6fw3t1C3a7tmND420AXmKnqPHFxKImvPtD16UKqo=)

Is this issue causing any issue in your project?

**Comment by KaelWD** [comment]
Looks like https://vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for but the v-for is sometimes leaking through the slot which would make sense if the ref wasn't also provided by the slot.

**Comment by naka87003** [comment]
I have same issue. In my case, it is not possible to change the value.
So we refrain from upgrading vue from 3.4.23.
How can I fit that?

**Comment by KaelWD** [comment]
Same thing here actually: #19685

I can reproduce both of these in our dev environment but not play.vuetifyjs.com

**Comment by yuwu9145** [comment]
Pass in `:ref="el => {}"` to slot root`v-list-item` stops v-for leaking it to an array, could be a wordaround.

**Comment by KaelWD** [comment]
that'll break the virtual scrolling

**Comment by yuwu9145** [comment]
What about `:ref="el => props.ref = el"`

**Comment by ker-nicolaib** [comment]
Hello @yuwu9145 and @KaelWD ,
thank you for your efforts :-)
So will this Problem be fixed in the next Version of Vuetify?
