### ISSUE TITLE
[Feature Request] Default Value for v-data-table cell

### ISSUE THREAD

**Issue by atharvachavan68** [vuetifyjs/vuetify#19712]
### Problem to solve
Currently, if key is missing in item, the only way to provide a default value is to use a slot for rendering the column which is very inconvinient

### Proposed solution
There should be a defaultValue key in the headers object, which can be used to populate the cell whenever that value is missing in the items object.

**Comment by KaelWD** [comment]
`value: item => item.a ?? item.b`
