### ISSUE TITLE
[Bug Report][3.5.17] Vuetify Component and Vue Render Function h()

### ISSUE THREAD

**Issue by azampagl** [vuetifyjs/vuetify#19722]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.21
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on the second input box and type in whatever you want. Then click off and watch it go back to it's initial state.

### Expected Behavior
app-text model-value should not go back it's original state on blur.

### Actual Behavior
app-text model-value goes back to it's initial value on blur.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVFFr2zAQ/iuHX+yAay8ZYxDcbGMwGGzrS9aXtg+KLcemsmQk2WkJ/u87ybKjNmVbG0gi6b777jvd6W6OgZJ5+qVtk76jwTrING1aRjTd3HKArL8gbWuXdpMLrknNqXRH9lCKw7x1KAb4VZe3wXJ1G5xsAJttVSs4CHmvgCigDy3NNS1iyCvC9xR0RaEnrKNAeGF3NW87DWVNWWHOfLKGKkXQqWsLFKySLLWxT5C/ytpku83x2Kj9chiydLdx3v+fCpo1fdAXVptvAVg3oqDswmaCribIU2eAz6PqEXntgFG/gMsNRMYBLqFf+F7pmUSz92//TcUoBFXw62r71qr4jMb8vCqwrSiHnNX5PYiytJgD0Xl1Vt69gB3J731CLaDWoUJYrWvCQGnkhGiHPnhHKyRSLlCBWUqJutnjIoErDjvWSaiVz5aTTtV8j5SG2IUzSyUaI+UU4tMre8k20so00mubCN+XbaMXegax/2yT1avbZLT679icjM88S73nj1uVy7rVoKjuxilQN62QGnBebI3mUooGwsTMD7M3MyT0YEeQtITBwUajMWN4ZQtomhwhUfjd1fena553y3DxBGnyfBm5MsgsHaWiyCCeRtokyYy12eyJq2KkVIL19KvAM065fiYWbzN18GvD9s326YzQdfmY5pOvSk8Ylyi+JONb0JJ0DEOOFeCkoWsIp8qH8XjcStGqNdyEp1qHd85Gm1pb21k7zBBbpMiS/KB7kj/GmCLRWqoYFBMa/wwL/qIoRWFYTHqma7a+v+gBr3q24JSdQ61HxMienM6dAPMJBf99pnANvWlXj3NMKHohm9h084wbZuphWkhMU3KI7AuooucFjEJ/KoeLeM7K0Y6USOe3zBDzjrE4eJ98SJYfg7s/U+01og==)

### Other comments
Vuetify components don't appear to be keeping the proper model-value state when passed into the vue h() function.

See https://vuejs.org/guide/extras/render-function#v-model

(I could perhaps be misunderstanding how to properly use the vue render ( h() ) function.

**Comment by KaelWD** [comment]
> `modelValue: propsLegacy.modelValue`

setup is only run once, you're always passing the initial value to the text field. This should either be a computed or inside the render function.
