### ISSUE TITLE
[Bug Report][3.6.1] Checkboxes in VDataTable is not showing as selected when returning an object on item-value

### ISSUE THREAD

**Issue by joelmandell** [vuetifyjs/vuetify#19724]
### Environment
**Vuetify Version:** 3.6.1
**Last working version:** 3.5.18
**Vue Version:** 3.4.26
**Browsers:** Edge 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
If you select the checkbox to select all items in the v-data-table, they are not selected. But the ref() that contains them (selected) has items on it.
This happens with :item-value="item => item" if you instead do  :item-value="item => item.name", it works.

### Expected Behavior
The checkboxes should be selected

### Actual Behavior
Only the checkbox in the v-data-table header is selected.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNls9u00AQxl9l5EtBqh0nLQUiN1KJEEIIVKlFlWh6mNhDvGKzttZrBxTljJAoEnBGnDjybjwCa7dJHLveWumlycGe+fbPb8ffrn0+txLpd47i2MlSsvqWp2gac1Q0GAmA+RwS4uQrCmCxyDNeZgeo0FY45mQnJDOSeR4gs6dRQPxwZC27jKwrpc/0oIkWiutm1uYkJirUYs91V1KMExpGqVA63y3l8y52hjyl69HgcAD5ddkiCaOZpsrnzxMDr3MDr16a1ymtU4eJL1msijXTxziSCgJ6jylXML8aOB/kwcNlBCBJpVKsYz319ar7cH6xu04Xq9S5dUaXtRwACJxSH3b+/b78BvpJcNop9c9/PPJRsUjoRmeYhExXLBLVRiGxSah0E9fpVrUxJvkMruM+rkpZxNNiei26bqXnYiNqxP4Kz1Dov4H7uZ9iEEkDdK8Z+pEZutKzJfRneCExpsQA/VIh/2RArs5cZq5Jm8xbVvoLnGnPyinxugFK4EPtkdrTKIHvN3LvmbArYkvmSzhmgvAWY5+GyDiKwEBdY1tRm4tdsU9L7B8wDElKZnTIaSo/0L2yyJ+/8BrFJDLZWgTM5I5ubb+tmGsnyybydpX+CSdK4mysq10rZQn77cmRqdDN7qhLlUJvd4B8h2NCP7zDNnSfNjM/MTNXdnBLb/yCV2zGDMRvaAbvCG/ZiPUDufVZbfD0+q1ZfGksRR14ndX72VrsWnvOvtM7sPKbA6drXfwHlqEz2g==)

**Comment by dmtransfer** [comment]
Same here

**Comment by joelmandell** [comment]
Closing this as this is not an issue anymore as of 3.6.3.
