### ISSUE TITLE
[Bug Report][3.6.3] The font-weight of the header of the data-table differs between the normal and the mobile version

### ISSUE THREAD

**Issue by rauhur** [vuetifyjs/vuetify#19737]
### Environment
**Vuetify Version:** 3.6.3
**Vue Version:** 3.4.26
**Browsers:** Firefox 125.0
**OS:** Windows 10

### Steps to reproduce
Just a normal <v-data-table> element

### Expected Behavior
Header title with font-weight:700 in normal data-table view

### Actual Behavior
Header title with font-weight:500 in normal data-table view

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9kTFrwzAQhf/KVYtbiOMG2iU4gQwtGbp16BBnuNjnRiBLQjqbgPF/r2zHxG3X0kXSvfvQe8cdWuFdnuysXTY1ibVImSqrkGmbaYC0idHa4TkUudGMUpO7SoPIdOG4lKQKaOLKFKQ2maj8ZyYgmXMFMsaMJ0WwlsHGB2y4M7FNk3l/Mgzid8deGQOlySxoKH3upGXwxPWYV1bWOIYWHJXQQelMBVGYMepxgPCvZwgpYdMT99GelDLwYZwq7qKHOTRkDNhhTNVOI2msaA3RrnQyRw0viuwZNUeLCfCWckk+MG/mYop+EsCRxhtVSOKA7MmdZGMc3TpnPEnGvvmODWqNC3gNgGc/Md31/pFp9fg7w+pp+fzvnqs/dDz2Sx/XHBYsuoWulRqO4xfw5tuS)

### Other comments
In mobile data-table font-weight is 700

**Comment by webdevnerdstuff** [comment]
Should be an easy fix, I'll submit a pr.
