### ISSUE TITLE
[Bug Report][3.6.1] VDataTable mobile shows header for sort & select when neither is applicable

### ISSUE THREAD

**Issue by Brunosil97** [vuetifyjs/vuetify#19730]
### Environment
**Vuetify Version:** 3.6.1
**Vue Version:** 3.4.21
**Browsers:** Chrome 124.0.0.0
**OS:** Windows

### Steps to reproduce
Use mobile prop on VDataTable where sortable is false and selecting are not applicable

### Expected Behavior
To have mobile format for VDataTable without the header for sort/select

### Actual Behavior
Mobile format for VDataTable with added header for sort/select

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU11r4zAQ/CuLobiFpI5Lk7szaeDocXD05V5L3YeNvUkFsmQk2ZSG/Peu4th1lZb2xR+zM9rZWfthF1lTJL/r+rJtKMqipaOqluholSuAZTvFuj488kspWhDlTR4xlkdHNCAdgQqFGiEHrESHU4drSeMCQPZEWJLhc7uHPArqgj1ZLpdkLRlnQ0Ih0fo6SWrRCa2maUip9Fq875uMDSeBYw+MBk948lUPemxlc7VMRlHxqy2MqB1Yck0nFFWtjYMdGNrAHjZGVxBzyrEvFlpZB93AcOMp5w9dt11vwtGzyyD+000N5+lstuXjTSvU9iKe9DSUYquYZx0a9wZb7u2zzmCD0tKAtygbBmOFFfXs/fG+63veotRGkI0nA794g4KjT+V/ke16j4N6g2zta+EtmrUNpIXHviP+b7QjoQJ53aHfOeCf0aw+G6sFQ59KHy/84vtd9l/nJ9v0eftojH4hBfd624y31aebQTr/NaCcWgaLy9mIxllkcHU9IMfxMrge0bxr7pWenSw4cHMn3J3fzKmNefrzvY2rD3ws5qc+foQuFoELn9oy6f4W/k+i/UQ1Uh4uj699glS2)

**Comment by webdevnerdstuff** [comment]
The bug where select was in the mobile header when not enabled was fixed in v3.6.2. The sortBy, not yet.
