### ISSUE TITLE
[Bug Report][3.6.3] VDataTableServer - on mobile - is ignoring #headers slot

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#19746]
### Environment
**Vuetify Version:** 3.6.3
**Last working version:** 3.5.18
**Vue Version:** 3.4.26
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
After upgrade from version  3.5.18 to 3.6.3 - VDataTable started to ignore #headers slot on mobile.
I have custom component for headers on mobile (since version 3.4.0 was released) but it is completedy ignored now.

In Reproduction link is demo with #headers slot inserted.

### Expected Behavior
to have #headers slot also on mobile

### Actual Behavior
Doing nothing. It is automatically inserting new funcionality of sorting/selecting.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/playgrounds/G_29vQ)

### Other comments
I have found workaround.
After setting prop :mobile="false" is everything working, but it shouldn't work like that.

**Comment by KaelWD** [comment]
How should the headers slot be displayed on mobile? It's a completely different structure.

> setting prop :mobile="false" is everything working, but it shouldn't work like that

#19744

**Comment by jakubmatisak** [comment]
Sorry, I did a test again and it was my missunderstaning of this updated structure. I'm closing the issue.
