### ISSUE TITLE
[Bug Report][3.6.0-alpha.0] data table sort field in header is always showing in version 3.6.0 and higher

### ISSUE THREAD

**Issue by Ethanjfobrien** [vuetifyjs/vuetify#19749]
### Environment
**Vuetify Version:** 3.6.0-alpha.0
**Last working version:** 3.5.18
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
you can see how it used to look on the veutify docs e.g. the example here: https://vuetifyjs.com/en/components/data-tables/data-and-display/#search
but when you go to the playground and use a version of vuetify 3.6.0 or later it always adds a sort dropdown

### Expected Behavior
possible to have data table with no sorting dropdown above the table

### Actual Behavior
always displays a sort dropdown even when is column has sortable set to false

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVlm1v2jAQx7+KFWmilUgIj20jWmlq99B1mibt1VT6wiQHWHXsyDZsDPW770LiOISwdq/A/7uzf/7fJfC487SKe++zLNiswYu8qYE049TAzUwQMt34MVUJMcxwuJ5539ZGMcOkmHlkgVn7JEyzRWTjay5NZOC3je03ydf+ggFPrEgwNZUJcNxVA1Xxaua5GKfzfeTHUSRTkIFIfCYEKJ/FUmBamjA/pUvBFtt67oYqRoXBBLk2nAlI6tEVS8BPwFDGtVM1E0sOfp5txZtpr34De+dezalS2vgJNdQ3dM6r6mgFNAGlkaL85iAihnvkkQS0BmXqocKUI3f2MO6Uokso5W3CRYNqqmPFMkM0mHW2z2VpJpUhO6JgQV7IQsmUdLD1neIS6KfO0/MjyXWedNbpnLtIeQUMPRY8OwtMOVuKiHS0ocp0ulZ+hi2KgqbgNI0EOXxEFpRrqPT9lGH2XeEGOeuH4RJh1Aabcm7rX8rPXbl3TLlUDHSnW21w66TGWUfVC4qwVeFHiqfmR71ah37PD4/E9RtrMyUNMFGr/l4ob6xnStaL73FJzt6drnxy/bOD1tLAvEe5BUr+AUF+yuW63kfrckT646tKRfciMqkloQkRGYwqpbxqRJyU0+MuzW42MO5jILECmhJNRfKLxas2lsHw4pDFoZUstQTHEgz/k+ZDzClTrQSTwSFB/9gOd1qF4JIKAEt5CuB2ncX0ufYMOYJhOD4kGAbuziXC5E0uXL4C8QkfQ1Bz7ErSCjJ2tzphxcj1p+IYBk4su2HrToF8Ac63ZA4UH4MWjouGIWET46plQF1SAWHXpxi+Ss5ZJrNWgqvGUISBEyyDdfsfDLboFMNnKWAby3TeBjEK3QnlXBxBXLbMxSRw9hUYIyuc4riTYt36rhiNG0YM3N4lwtg+ewej2RyJwWtWPDDzkL/KjxnG/YYPg6OxnDiqisE5UxAcziS+Uqe94scVf1a9l65Yc971hsEk6ONfEW1ABYNwMPLDsR/2vae/D3+uGA==)

### Other comments
I see other issues filed mentioning that the sort docs could be clearer. ideally defaults like false and not showing a dropdown would be used over defaulting to true.

**Comment by tarreislam** [comment]
Ofc... ZZZZ Time to revert until they fix it I guess.

While your'e at it, remove the stack option or something, I rather have 20 miles horizontal scroll to see all columns than having the columns stack.

Its ugly and useless.

**Comment by tarreislam** [comment]
A workaround is just to set

` :mobile-breakpoint="-1"` or whatever value that isnt a real value. Eslint bugging you? No problem just ignore the error
