### ISSUE TITLE
[Bug Report][3.6.3] VDialog location and offset props do not affect dialog

### ISSUE THREAD

**Issue by MoShizzle** [vuetifyjs/vuetify#19755]
### Environment
**Vuetify Version:** 3.6.3
**Vue Version:** 3.4.25
**Browsers:** Firefox 125.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create a dialog
2. Define location and offset overrides
3. Open dialog

### Expected Behavior
Dialog location will be affected by location and offset props

### Actual Behavior
Dialog appears in middle of screen

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkTFrwzAQhf/KVR3cQmOHpukQnECg0BYKHTvUHVRZDgJZJ6SLF+P/HklOgp1F6J6evtM9/fbMO1Hsrc27o2QbVpJsreYkd5UBKLsFtzZtUyHQEFdGurOUxFpxjQfQKDgpNNuKEdqKwQabxksK9Xq5rNj1Srh0aQL3XJDqOKELth6sQ+thmJlTj38yEFZl6uBLruB5+9x/fb+XRTqe4ovZEFeI4K6+BUdtQYq03PU9tP4AwxCJE30KvoFEYRz/klF0zEKKypjh7Fmh9MIpSxAiOo4Rq9aiI+jByQYGaBy2kIVvyaIdIHA9pSduo+Mh+5BaI/yg0/Vd9hgbjMgAY8MTW+Uv+fOaxc1rvmJ/J2KSl9Y=)

**Comment by johnleider** [comment]
@KaelWD Should these props be omitted by Dialog? I'm not sure what they would do.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/1ff7faafc0a04a49e55c91af95776815444dc2d8/packages/vuetify/src/components/VOverlay/locationStrategies.ts#L110-L112

**Comment by MajesticPotatoe** [comment]
This inherently effects `v-bottom-sheet` as well (which would have a use for location to say the least)
