### ISSUE TITLE
[Bug Report][3.6.3] labs/number inputs (v-input-number) unable to tab out of control

### ISSUE THREAD

**Issue by its-bru** [vuetifyjs/vuetify#19757]
### Environment
**Vuetify Version:** 3.6.3
**Vue Version:** 3.4.26
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I'm not sure that playground will work or not, looks like I would have to subscribe to log the issue. You can see the issue occur on your web page for number inputs.
https://vuetifyjs.com/en/components/number-inputs/

### Expected Behavior
you can tab out of the control

### Actual Behavior
you can't tab out of the control

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by yuwu9145** [comment]
It's a known issue and fixed in #19714. I will do final regression soon
