### ISSUE TITLE
[Feature Request] v-select item-text with 2 or more values

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#1975]
### What will it allow you to do that you can't do today?
Show a text build by 2 or more properties shown in v-select's item-text.

### How will it make current work-arounds straightforward?
Create a property in my item and set it to the value.
So I have to do something like:
```js
{
  "prop1": "TextValue1",
  "prop2": "TextValue2"
}
```

```js
{
  "prop1": "TextValue1",
  "prop2": "TextValue2",
  "newProp": (prop1 + " - " + prop2)
}
```

### What potential bugs and edge cases does it help to avoid?
Just syntactic sugar 😸
Also comming from AngularJS Material, you can do something like this:
```html
<md-select ng-model="ctrl.userState">
    <md-option ng-repeat="item in items">
        {{item.prop1}} - {{item.prop2}}
    </md-option>
</md-select>
```

### Steps to reproduce
```html
<v-select label="Text" v-model="item" :item-text="prop1 + ' - ' + prop2" :items="items"></v-select>
```
Notice my colon in front of item-text.
Currently :item-text expected a string like :item-text="'prop1'".

### Versions

- Vue: 2.4.4
- Vuetify: 0.15.7

### What is expected ?
A text should be displayed which looks like, ie: 'TextValue1 - TextValue2'.

### What is actually happening ?
The provided text isn't shown.

### Reproduction Link
https://codepen.io/anon/pen/dVzOQe?editors=1010

**Comment by Shinigami92** [comment]
One addition:
I can do something like this:
```html
<v-checkbox :label="item.prop1 + ' - ' + item.prop2" v-model="item" :value="item.id"></v-checkbox>
```

**Comment by KaelWD** [comment]
That... isn't how vue works. v-select has a scoped slot that you can use for this: https://vuetifyjs.com/components/selects#example-6
