### ISSUE TITLE
[Bug] v-data-table leaves last item in the table when model is empty

### ISSUE THREAD

**Issue by anthonysan95** [vuetifyjs/vuetify#1976]
### Steps to reproduce
* Make a table with a model
* Modify the model data of the table until all items have been removed

### Versions
0.15.7

### What is expected ?
The table should became empty, showing the empty message ''No data available".

### What is actually happening ?
The last item remains in the table even when it has been removed from the model.

### Reproduction Link
https://codepen.io/anon/pen/veJxGG

**Comment by KaelWD** [comment]
Not vuetify related https://vuejs.org/v2/guide/list.html#Caveats

https://codepen.io/anon/pen/rGzyvE?editors=1010
