### ISSUE TITLE
[Bug Report][3.6.4] Error in v-text-field size when using slot

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#19769]
### Environment
**Vuetify Version:** 3.6.4
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just see the link

### Expected Behavior
I would expect the v-text-field to not resize when using the slot, when passing any property in "variant".

### Actual Behavior
If the "variant" property is passed in "outlined" and the slot is used, it changes size. In all other variant options, it works correctly, that is, the size is not altered no matter how much the slot is used.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkcFqwzAMhl9FeNd5ZjuObrDD3qCHQtODG6tgUBSTKKFQ+u5V3KRNCoVejP3714d+aXsybVO6v5Q++g7Nt1kJVom84G/BAKve+pTyNT/KmsVHxmaUVAyxh5J82/4UJtgD4bEwt99cJHgUe4hIAcjvkdS4/t+s4bMw0PsmehaVOg7YkLKDyu41wtdTwqxeCVMmeNM0yMFGnmcYXS3VAuwrVNbc90Abe9oLQ9R5qLkK0aq9jGTrToYOHiLkEjfwl325xbAncZ73Pmeng54WoZblJgbluqgF05zfuSPKx+4CaeGUzA==)

**Comment by yuwu9145** [comment]
When using slot, it's user's responsibility for not using an oversized content. 

Just applying `size="xs"` to slot button to fit it into v-text-field: [demo](https://play.vuetifyjs.com/#eNqNUUFqwzAQ/IpQr1VFeyxpoYf+IIdC3YNibWBhvRbW2piW/r1r1U7sQCAXY41mRzOznz82d7V/S+lh6ME+251AkygIvFZszG5wIaXyWw51yxKQoZshBSMOpqaQ80tlozsSjJU93ZYhgVHcEYGioXAAUuL+/WNvHitrhtBhYFGo5wgdqXZU2N+m8HRVYTWvCksmc6dpgKNDXmeYWZlaMRwaUK0170Jt9nQQNqh9KLmJ6JReI7m2l8mB+sr4PQmN+SJOGffTW1uPflP8Aq6znzv3WvqyFKVstzIh/0vbaNrfe+6JyufrD8wNmMs=)
