### ISSUE TITLE
[Bug Report][3.6.3] VDefaultsProvider doesn't work with local component 

### ISSUE THREAD

**Issue by kieuminhcanh** [vuetifyjs/vuetify#19761]
### Environment
**Vuetify Version:** 3.6.3
**Vue Version:** 3.4.26
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Registration a local component.

![image](https://github.com/vuetifyjs/vuetify/assets/136077/3f32ef70-4978-4028-91de-d8ebdbf3ba6b)
![image](https://github.com/vuetifyjs/vuetify/assets/136077/7769e449-1863-425e-a2c5-d4c4a7dd2a8c)

### Expected Behavior
It's should be work with local component.

### Actual Behavior
None work with local component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/playgrounds/R6oUqg)

**Comment by KaelWD** [comment]
Vue doesn't expose this, aliases need options.name changed: https://github.com/vuetifyjs/vuetify/blob/20ffadc9d73fe57d357edde56d7e907a7135bcee/packages/vuetify/src/framework.ts#L70-L74
