### ISSUE TITLE
[Bug Report][3.6.4] TextField does not change text alignment based on the input

### ISSUE THREAD

**Issue by mahozad** [vuetifyjs/vuetify#19776]
### Environment
**Vuetify Version:** 3.6.4
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open the playground.
Type or copy some RTL text in the text field (for example: سلام؟)

### Expected Behavior
The text should be displayed on the far right end of the text field

### Actual Behavior
The text is displayed on the far left end of the text field

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj8EKwjAMhl8l9jIF5+5jE7z5Bh6ch7FlMkjXkmZFGHt3205BvITkI3z5c1+U4664WHvyM6pSVYLaUit4biaAyuettalNQ2cmaccJ+YMSFHxJPoxIPfhcmx6pbpR2z0ZByeiRHQYwtOQwoOJrK/51kWzXquInRRhdx6MVcCjzFmbU1rDAAowDrDCw0ZCFB7K4DhC8TiBEgDpu7LMrEhm4GaZ+lx3igU0ZZGo9TjNRKo83jGha4g==)

### Other comments

I think this issue more relates to text **alignment** rather than text **direction**.
Text direction seems to work fine but text alignment has problem.

If the locale is set to some RTL locale (like `fa`), then all the text will always be RTL (even for, for example, `hello`). So, text alignment should be based on the entered input and not depend on the locale. Or at least, there should be an option to customize it.

There is a property called [`reverse`](https://vuetifyjs.com/en/api/v-text-field/#props-reverse) for text field but it is only a `boolean`. The workaround would probably be for the developer to manually implement the bidirectional algorithm and then check the text on change and set the `reverse` property based on text.

I want to mention that, in [Android Jetpack Compose framework](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/TextDirection), the text field text direction (set via [paragraph style](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/TextDirection)) can get these values:
  - **Ltr**: always left to right
  - **Rtl**: always right to left
  - **Content**: based on the first strong directional character in the text according to the Unicode Bidirectional Algorithm
  - **ContentOrLtr**: based on the first strong directional character in the text according to the Unicode Bidirectional Algorithm or **Ltr** if no strong directional character is present or the text field is empty
  - **ContentOrRtl**: based on the first strong directional character in the text according to the Unicode Bidirectional Algorithm or **Rtl** if no strong directional character is present or the text field is empty

The last two options are specially useful to set the alignment of the cursor when the text field is empty.

<br>

Maybe related:
  - #4248
  - #9700

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir
