### ISSUE TITLE
[Feature Request] allow for v-data-table's prop 'no-data-text' to accept html

### ISSUE THREAD

**Issue by brunen9** [vuetifyjs/vuetify#1977]
**- What will it allow you to do that you can't do today?**

It will allow to show to the user helpful hint stylized by CSS (and may be contained icons and even pictures) about what he can to do to fill/get data.
Something like github uses in it's list:
![01-10-2017 22-19-11](https://user-images.githubusercontent.com/7408605/31056849-5ffdec94-a6fa-11e7-9f55-31b213e726ab.jpg)

**- How will it make current work-arounds straightforward?**

I don't know any clear workaround for this moment. All I can think of is very awkward ways to achieve needed behavior.

**- What potential bugs and edge cases does it help to avoid?**

It just will help to make UI more user friendly and prettier.

P.S. may be you can go further and allow `no-data-text` prop's type to be not only string and html, but even a Component?

**Comment by johnleider** [comment]
I'll have to check, I added this to select, should definitely be in data table as well.
