### ISSUE TITLE
[Bug] v-dialog with tabs hides the tabs slider until you click any of the tabs

### ISSUE THREAD

**Issue by anthonysan95** [vuetifyjs/vuetify#1978]
### Steps to reproduce
* Create a v-dialog with tabs inside
* Open the dialog

### Versions
0.15.7

### What is expected ?
The tabs slider showing on the active tab.

### What is actually happening ?
The tabs slider is hidden until you click on any tab.

### Reproduction Link
https://codepen.io/anon/pen/wrqeav

**Comment by johnleider** [comment]
This is unfortunately part of how `v-tabs` works, it needs to know its dimensions to calculate the bar position. You can manually do this, or you can just add the **lazy** prop to your `v-dialog`.

https://codepen.io/johnjleider/pen/gGxGBZ

**Comment by BennyAlex** [comment]
@johnleider How do I know when the dialog is ready when using lazy? I have soem properties inside the dialog and I get errors now. Without lazy it works fine

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js). Do not forget to create a reproduction that shows your problem

**Comment by mrodal** [comment]
This is an annoying bug. 

Have you considered something like [this](http://marcj.github.io/css-element-queries/) instead of the window resize event for example? I made a quick test adding that on the resize directive and it fixes this. 

Im not sure how it might affect the rest of the codebase, but they even claim that it performs better than the window resize event that is used currently on the resize directive.

**Comment by simonmaass** [comment]
@mrodal i agree

**Comment by simonmaass** [comment]
any news here if this will be refactored?

**Comment by thomas-topway-it** [comment]
hello, I confirm that using "lazy" attribute it works,
here is our app https://app.mappd.io

**Comment by MTakashiMori** [comment]
Hello, if anyone have this issue outside a dialog, just wrap with "v-lazy" component. As it's described in docs, they will render when needed.

**Comment by yoji0806** [comment]
This may not be your case, 
but in my case, binding <v-tabs> and <v-tabs-items> solved this issue.
(using the same v-mode attribute which is defined 'null' in Vue object's data bracket )
