### ISSUE TITLE
[Bug Report][3.6.5] VDataTable: Translations for missing

### ISSUE THREAD

**Issue by cs-nero** [vuetifyjs/vuetify#19799]
### Environment
**Vuetify Version:** 3.6.5
**Vue Version:** 3.4.27
**Browsers:** Firefox 125.0
**OS:** Linux x86_64

### Steps to reproduce
Just watch the errors, that the translation keys are not available.
The translations are missing, so the fallback language ('en') is used. ('No data available').

### Expected Behavior
The texts are set to german

### Actual Behavior
The texts are set to fallback ('en')

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUcFOxCAQ/ZUJl2qyu9ybromJFw/ejJftHrBMLUqBwHTjpum/S6HVuhyAefNmeI85jSz4hl8GJNVeD5+BlUz1znqCERqPgvAt52CC1tseioVb1KY2+J2ojTWBYEnA8X/h3VgbAOqwxxLSHUBiKwZNrxkstProqNjlHOfzOaVI20bov7I1LCRm9sya7mvDdsnGo3OHqCJ6qAh7p6OIh5lWXfbCuXRNQdRLQhn0C5RAKUjsSbxrXEGAUsU+4Viz07lmG7hDIdGnxCItL1KU9D0/rW7y+sJrRJWMn7ZC06YjX6XxW20zkqVXfGMphqHxyhEEpCE7+x2bNS92MIRyO7L4csVzTWSzaWcGrdN2/gH0qqPu)

**Comment by KaelWD** [comment]
You're missing
```
import { de } from 'vuetify/locale'

messages: { de }
```
