### ISSUE TITLE
[Bug Report][3.6.5]  (VNumberInput): interpretes negative numbers as NaN

### ISSUE THREAD

**Issue by guenbakku** [vuetifyjs/vuetify#19798]
### Environment
**Vuetify Version:** 3.6.5
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Enter a minus sign (≒hyphen `-`)
    (Copy&Pasting a minus also causes same behavior)

![image](https://github.com/vuetifyjs/vuetify/assets/15353516/5f16f68f-2420-4f90-9b97-dd33c278e015)

### Expected Behavior
The input field should accept negative numbers if the `min` prop is set to a value less than zero

### Actual Behavior
As soon as you enter a minus, the input will be replaced with a literal string of `NaN`.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkM1OwzAQhF9l8SUgkQauUVqJG7wAHAgHN9mApfWP1nYuVd8d26E0kXqxvLOjGfv7PAnPQ/Pi3G6OKFrRBdSOZMBDbwC6uZbOlWsZBmuCVAb5TyqiifqIXCvjYrjIAC3jjOxx34tJksdeXHc5hi29S1bShOQYcZKRwtrT+oAurZ52z2uZ5BEpyRvrjxrxLdffKmuV8XhzM//3e0u2nhQRjlfDoWu2n7twSPIWRFYWTl2z4pdGP7ByAdID4oJRaWc5wAkYJzjDxFZDldBX2V7I+ADaf8M+O+6rVySy8GGZxrvqIRcskSlMnB9NJCrH1y8u0JCN)

### Other comments
This may relate to the following issue: 
https://github.com/vuetifyjs/vuetify/issues/2359

**Comment by kchobantonov** [comment]
The same happens when chars like 'e' or '+' are entered for number is exponent format like 4e+100

**Comment by kchobantonov** [comment]
@yuwu9145 yes I can use that but then I need to use that for all numbers since I do not know upfront in what kind of format those number are going to come when loading the forms (e.g. when the data is already specified)

**Comment by jakubmatisak** [comment]
It also happens when I'm writing decimals like 3.5, but when I do a missclick and put there two dots, like 3..5, then it's automatically changed to NaN -  I would expect to ignore second dot, cause this will be common mistake. 

Also when starting with dot (e.g: .5). it'ts changed to NaN, guess it should be changed to 0.5 or ignored.
