### ISSUE TITLE
[Bug Report][3.6.5] text / background color issues in v-chip

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [vuetifyjs/vuetify#19802]
### Environment
**Vuetify Version:** 3.6.5
**Vue Version:** 3.4.27
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- use v-chip component
- give it a lighter background color
- give it flat variant

### Expected Behavior
to exist contrast between and background and text so the text is readable

### Actual Behavior
almost no contrast, can't really see text

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQRDAjs0AhOT8nv8g2RknZxMzA2MDYMClGSSEnMSk1R6EssSgzMa8EKJcGNDdGyU7BGaTBRh+iE2Y4iItiOkgEYrmNPpKjlGp18kpzcsBELADEuD26)

### Other comments
imo, since the text color changes based on the background color, there should be a check to ensure there's still a contrast between the 2 colours and fallback to a another color that would still be visible

**Comment by Ribeiro-Tiago** [comment]
@johnleider Does the label mean that you need more information from me or ..? :p

**Comment by johnleider** [comment]
If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
