### ISSUE TITLE
[Bug Report][3.6.6] Undefined date methods when using VCalendar with Luxon Adapter

### ISSUE THREAD

**Issue by farrance** [vuetifyjs/vuetify#19814]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Install Vue, Vuetify and the LuxonAdapter

### Expected Behavior
The calendar to work and not report any errors.

### Actual Behavior
Lots of date functions fail.

```
@date-io_luxon.js?v=aaaa9179:129 Uncaught (in promise) TypeError: date.hasSame is not a function
    at LuxonUtils.isSameDay (@date-io_luxon.js?v=aaaa9179:129:19)
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUsFOAyEQ/RWyl2rSZYyamjTVtHePxot4oMvUYoAlwNaapv/uLLut3RqTXgjw3pvHm+FtV8RQwabBpFff/DMW00JbX4fEdqwKKBO+dhjbs1WoLRv13JFwPfG52dZuoaRPGHrOXJGw1DWYFiOqcLjN5Kp2MbG+BnscelzthGOs1U5Z3jImu7rTgcu4xfZ5TWu0v2yFK9mY9NJdjoz+WKdR5jEGcFDtr4Urxjn4wntOj6HUs4TWG7J+ammzTSm9z9t8qKRBp2Rg0MFwwGdwoqNjrIL2iUVMTSc/djPg6rSH1JQZdGzi0XM6YmmlpzHUjp6UQ4keiKI4xhQFFWjPolin5OMUoFKOZAqN3gTuMIHzFuZEg9C4pC2WqrbzO37Pbx9A6ZhO7zlGWy5D/RUxUBVR9C3LPu1gLvDqmWQx4ZPOob8qjVzG1uJPaSC/DYYyUG8xYLg00plsEOsM+z/a8I9eYj0QkOkNv4Flo40CTWZbrng7pfzL6JPRUPdj1xiTl/cfhxotEQ==)

### Other comments
It seems the object type for each date argument is the generic Date object and not Luxon's `DateTime`. I can make the errors go away if I polyfill each function that the VCalendar component calls by doing the horribly hacky solution below (wrapping each instance of date with `DateTime.fromJSDate`...

```
// Create the adapter
let luxon = new LuxonAdapter({ locale: 'en', formats: CUSTOM_DATE_TIME_FORMATS } );

// Clone the broken functions
let isSameDay = luxon.isSameDay;
let startOfMonth = luxon.startOfMonth;
let getWeekArray = luxon.getWeekArray;

// Convert to luxon dates
luxon.isSameDay = ( date, comparing ) => isSameDay( DateTime.fromJSDate( date ), DateTime.fromJSDate( comparing ) );
luxon.startOfMonth = ( value) => startOfMonth( DateTime.fromJSDate( value ) );

// Export the completed function
export default luxon;
```

Any help on a fix or better workaround would be much appreciated. Thank you all!

**Comment by mathiasrando** [comment]
This is broken once again: https://play.vuetifyjs.com/#eNqNVMFu2zAM/RVNFydAbK3bimFGOqRADz3sWGyHqgfFphtvsmRItJMiyL+PltzUSVG0gGFI5CMfySfpfs+9K0TfAdbVU/bX85zXTWsdsj0rHCiE39HHDqxytmHJiE2kGYG/up0116VqEVzESL4qKTKtrdCDU3JppIFdgBfWeGRjFnZ1yjLbS8PYEJyzsGRMxcz5Cc9i8B3CHzfQvKBLqFSn8S4aE10/bjAJOMaEeI46zKXhi9D6ddtmVAz1vURoWk3UPwfYsk9V24Zl2FDZqGoDbjQFI8IO06oGXbI+bWwJ+kryxj9KzsQUVygNplSO5dCDQU+ouCBgX8M2xJJxC/BvErsU57yDJZa1FJNyaesLV7fIPGAXqz7K6KCaikfCDe4oA9VKEhBiltyC1pb9sU6XnxKazwsoljri7p9l0fpGPeWsUtrDOODCaktCSb7WHUg+WqnznBnYshsqdnZczDOq9dZ2zs8uLhfsc/zm8zHKqEFAye/A4zGVR+XwvWTfzpMdHqidpYgTotmQ8nE4aaNaOvPWkPqhLTk6SJfjiZKchjbsJd8gtj4XoigNhZHade8yAyhM24gVwYTrDNYNpKVtVl+zy+zLhShrj1N7Br5J185uPTjKcuwt8Ax34ANcI5IofmTfI8NoSrVa+4HiVWpBfD241JEe4MB9tKWzsJO2znxvt3b+Hkyph2JpPuL1m0HS0V3lhwWPpCRc6Jgv4qk7ucDR9vAfuCSYtw==
