### ISSUE TITLE
[Bug Report][3.6.6] VTabs scoped class works strange

### ISSUE THREAD

**Issue by WhoisUnknown** [vuetifyjs/vuetify#19817]
### Environment
**Vuetify Version:** 3.6.6
**Last working version:** 3.5.18
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create components with root VTabs element
2. Use this component with scoped class
3. Scoped styles does't working

### Expected Behavior
Scoped styles should work

### Actual Behavior
Scoped styles does't work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdkMFuwyAQRH9lyyWX2FavqWup6i/0VveA8aayigHBOlVk+d8Li11FSi7JBbFiZ5g3n7MIXlVvzpWnCcVB1ISj05KwaQ1AfSqkc3yNw7sdHSgtQ3htBWGggmQXWtFAXaW3LKk2TV1deMUxKD84goA05dVhdNYTsO3R2xF2JfukKLukz4pVTWeNEJR12LO6/E8Acw7YSfXz7e1k+kJZbf0BPPYv6W1ht+QQpWLPzNtPt6DZ9Yq0GIxBH3nXPnivgQ/ZwXPCTtNWQdq/o4M5Rj3CstbwIP8KfUat7S88ZWtp6EYFy95MWvPx9QccGLEH)

### Other comments
First issue https://github.com/vuetifyjs/vuetify/issues/19752

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/5446
https://github.com/vuejs/core/issues/6861

We have this workaround but once there's more than one layer it's out of our hands:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/scopeId.ts
