### ISSUE TITLE
[Bug Report][3.6.6] v-html:text used on v-card breaks it

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#19811]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Firefox 125.0
**OS:** Ubuntu undefined

### Steps to reproduce
Check reproduction link.

### Expected Behavior
v-card keeps working as usual.

### Actual Behavior
v-card breaks.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9kk1LBDEMhv9K7Hl3B8XTUgfEiweP4sURtp1GN5BOa5uOivjf7c7s+nkVoQ0JfWjevOT2VeXUN+cxrsaCaq20oI9sBNtuANDjMoWnKZ2KPjDUm886dXzSKfCuZqed2hMzY5I7lAC5WCFhrNz1ljLUY2CHfLx06pMWfJZKXoWEHijm4sEFDgkyCRiPUrsPGXtBKQmMo0iZehoeAJlkBRfB++BoAckIhQHBoSWpPR9LDZgF2Nj6OYyBS5QK2ZKPvin4JfaHyFY384wHV3Zl4P/zaFxuxfN6b9XmEpkDaNveFBS6f9GNbTd/NtEunzdAN182Q70thsI8hbt37+e25Q==)

**Comment by KaelWD** [comment]
https://eslint.vuejs.org/rules/no-v-text-v-html-on-component.html
