### ISSUE TITLE
[Feature Request] VTextField ability to disable size="1"

### ISSUE THREAD

**Issue by jakeflorentine** [vuetifyjs/vuetify#19818]
### Problem to solve
The current application of size="1" to the VTextField does not allow for the VTextField to auto-grow inside of a v-col with the auto prop on it. This is different behavior from Vue2. It would be nice to have the ability to have the previous functionality optionally.

### Proposed solution
add an "autoGrow" prop to VTextField which optionally sets size to null instead of 1

**Comment by jakeflorentine** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/31462184/3bd49cb8-20dc-4a59-a81b-7bccde0bf150)

**Comment by jakeflorentine** [comment]
https://play.vuetifyjs.com/#eNqtUz1PwzAQ/SuHl4BEyF6lSFUZmFgYGAiDSS4l0sW27HNBVP3vnB2+hBBQkcGW78Pv3T2fb3cq+LZaOXe2jagWqmYcHWnG88YA1NtSO5eP2fD2ETo0YYq+OltLICssG6Uj20a9B3OY8YnLfkDqgPQ9kqRdYK8jMZSwkguwttQoqD4wqwz6heMA1Cubgf8AemDhb+XC9fCMsH7QZoOd0CyC2BI3kX5qJVki4f/0TL7WyiMh45yK/oI7j6bfksyoajpPE1tXnyZZzND6wTEE5DgN9DA66xl24LGHPfTejlDIJyhSOkgTJjCMYQPLlHFcXCKRhRvrqTsqThLBBClgan+aaszb3QuvgwTM

**Comment by yuwu9145** [comment]
v2 demo: <https://codepen.io/yuchaosydney/pen/XWwmNzm?editors=101>

**Comment by yuwu9145** [comment]
Although we could look into the possibility of removing default `size={ 1 }`, the best practice of using v-col is really explicitly define columns as opposed to let every column auto-grow. The latter results in very fragile layout outcome.

**Comment by jakeflorentine** [comment]
The goal here would not be to remove size=1, rather, to provide a prop to VTextField allowing the size to be nullified. This keeps default behavior, yet provides ease in migration from Vue 2.
