### ISSUE TITLE
[Documentation] The VStepperVertical is introduced in v3.6.6 . But the developer website indicates that "This feature requires v3.5.14", which is wrong.

### ISSUE THREAD

**Issue by wingyippp** [vuetifyjs/vuetify#19821]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.5.0-alpha.2
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The VStepperVertical is introduced in v3.6.6 . But the developer website indicates that "This feature requires v3.5.14", which is wrong.

### Expected Behavior
This feature requires v3.6.6

### Actual Behavior
This feature requires v3.5.14

### Reproduction Link
[https://vuetifyjs.com/en/components/vertical-steppers/#installation](https://vuetifyjs.com/en/components/vertical-steppers/#installation)

**Comment by MajesticPotatoe** [comment]
resolved in [3363612](https://github.com/vuetifyjs/vuetify/commit/33636128a3360a27b5e6cc533d92c3fac60b2aa1)
