### ISSUE TITLE
[Bug Report][3.5.13] v-table not render inside v-html

### ISSUE THREAD

**Issue by mubarak117136** [vuetifyjs/vuetify#19831]
### Environment
**Vuetify Version:** 3.5.13
**Last working version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
https://play.vuetifyjs.com/#eNq1VMtOwzAQ/JVVzoRQ3lRpJQRnkLhSJJzEIhGOY9lOCqr676ydJypVZQOXKOvdmd1Zefy8CZRMo1shjpuaBvMg1rQUjGi6XHGAOCsaSBlRarEKNP3QYcJI+r4KbBbzYvkoi7eCEwYZ0WQeR6JLbTaaJIze4+l2a7kiJMOk/RcDa6nD2QkSPlGeUQnrQufQhLku2UC2ZwooEwvtyk2u74h839q1v+3EO50fKlmSsRvWWB4oTBFuZd6E9mBQbSqSKvscQnMgJ5GJc0grpgThSDLDIWW1HqMlLu6uYnXJYWb6xpHOPfGnv8Sf/YDHcCpnV1x2iDwbdGXu0F6SB7RXM4X+gZpz/4ku/KGX/yMGrvxHuvaH3hxSg8HEVRgZ07UPQOdlPBtfp1ilshAaFNV169y04krD8AjAAl6xbK+ZexfbJXo51sumXt5sN9VP6mQ/V8+5Gs11tNFLrgZydY3z0kZjuLrB1QL9aN2Vn9x2c2Wj9mpjFGyPeM2Y/bx8AaoyTWI=

### Expected Behavior
v-table properly render in v-html

### Actual Behavior
v-table not rendered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VMtOwzAQ/JVVzoRQ3lRpJQRnkLhSJJzEIhGOY9lOCqr676ydJypVZQOXKOvdmd1Zefy8CZRMo1shjpuaBvMg1rQUjGi6XHGAOCsaSBlRarEKNP3QYcJI+r4KbBbzYvkoi7eCEwYZ0WQeR6JLbTaaJIze4+l2a7kiJMOk/RcDa6nD2QkSPlGeUQnrQufQhLku2UC2ZwooEwvtyk2u74h839q1v+3EO50fKlmSsRvWWB4oTBFuZd6E9mBQbSqSKvscQnMgJ5GJc0grpgThSDLDIWW1HqMlLu6uYnXJYWb6xpHOPfGnv8Sf/YDHcCpnV1x2iDwbdGXu0F6SB7RXM4X+gZpz/4ku/KGX/yMGrvxHuvaH3hxSg8HEVRgZ07UPQOdlPBtfp1ilshAaFNV169y04krD8AjAAl6xbK+ZexfbJXo51sumXt5sN9VP6mQ/V8+5Gs11tNFLrgZydY3z0kZjuLrB1QL9aN2Vn9x2c2Wj9mpjFGyPeM2Y/bx8AaoyTWI=)

**Comment by KaelWD** [comment]
https://vuejs.org/api/built-in-directives.html#v-html
