### ISSUE TITLE
[Feature Request] Allow v-toolbar's extended height to be set independently

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#1983]
**What will it allow you to do that you can't do today?**
Currently the height for the toolbar and the extended area of the toolbar are based on the same computedHeight.  If we can set an extended-height property and have it's height set based on that first, it can allow for independent sizing with data-binding.

**How will it make current work-arounds straightforward?**
Currently you have to use CSS with !important, and it's not versatile as a result.

**What potential bugs and edge cases does it help to avoid?**
N/A

**Comment by johnleider** [comment]
This has been resolved in 1.0-alpha
