### ISSUE TITLE
[Bug Report][3.6.6] divider vertical didn't work

### ISSUE THREAD

**Issue by jemu75** [vuetifyjs/vuetify#19838]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Android 10, Windows, iOS, Android

### Steps to reproduce
only to use simple codesample or take a look into current vuetify documentation samples

### Expected Behavior
Vertical divider should be showed

### Actual Behavior
Vertical divider will not be showed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj0ELwjAMhf9K7GUKzt1lCt78Bx6ch7FmUkjXkmZFGPvvdpvKvITk4/Hey31QgZvi4v0h9qiOqhS0nmrBc9UBlDGvvZ/X+WhcJ7XpkD9ohoIvyVuDpCHm1mmkU6VseFYKirVOm2g0MkRkMU1N57L4wW9EIv8ZE1kqlMWqWjpDw8YLBJR+aWisdywwAGMLI7TsLGTpq2ySAyTfIJB6wWlSbLMrEjm4OSa9yXZTwGKZzNS473qieTzezxlhgw==)

**Comment by J-Sek** [comment]
It actually seems to work on `3.6.6`, but disappears on `3.6.7`. If you wish to make it visible I would recommend `h-100` class in that scenario (although I don't get the point of the linked example) or wait until I can fix #19889 to use `length` prop instead.

If you wish to prepare future reproduction examples, please consider using `thickness="2"` and `opacity-100` class or `outline: 2px solid red` to make the `v-divider` more prominent.

**Comment by MatthewAry** [comment]
[With this](https://play.vuetifyjs.com/playgrounds/WUCHgQ), I can see the divider. I don't think this can be considered a bug unless there was some kind of regressive change with how it lays it's self out. Try fiddling with the display style for the parent of the `VDivider` component like in my example. @J-Sek seems to be working on adding an enhancement to allow you to force a specific length to the component
