### ISSUE TITLE
[Bug Report][3.6.6] VAutoComplete not show all items when using slot #item

### ISSUE THREAD

**Issue by williamlinn93** [vuetifyjs/vuetify#19845]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Please check in playground.
The first one can show all items(1 to 100)
The second one which is using #item slot can only show 37 items out of 100.

### Expected Behavior
Show all items (1 to 100)

### Actual Behavior
Show only 37 items (1 to 37)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqt1Mtum0AUgOFXOaULWimxyx0ix5LVTStl10UXcRbUnbSWMCAY3IXld+8Ahn9QttnYZ47PzOe5Pl+ctjmsd3W9OnfKeXA2Wp3qItdquy9FNuf7vK6HcGgcqlLnx1I1t5TIj7/VP9k9Pcl307Gdsn2/TleHyoyltJIi/6WKx72zs5J7Rx6OfSeTH773znazXnY0zDTk17wsK/3O3tTfjDDNWz72P5qauqnqZc3gFMdW3/clW7lcZCha9c3VOS86Jder9JOgyiLWi7UdU2/mO6WXSz0UDjuxGMU020NzrLW0SnfjRh1PddVouUijXuUqr011EtdsrjuupRm31XJq/8hjX/HJ/aaKopKfVVP8/uB+pmRYI1P0PP4n13PvbpE/R8EchXMUzVE8R8kcpXOUzZH3hRDFg/FwPCAPyYPysDwwD81H8605ofloPpqP5qP5aD6ajxagBWiBtYRoAVqAFqAFaAFagBaihWghWmjtGFqIFqKFaCFaiBahRWgRWoQWWQcELUKL0CK0CC1Gi9FitBgtRout84gWo8VoMVqClqAlaAlagpagJdbxR0vQErQULUVL0VK0FC1FS9FS67ahpWgZWoaWoWVoGVqGlqFlaJl1ue3bfeNe+sdrfK7MQ+Vc78quKIaPl//Ad5bw)

**Comment by KaelWD** [comment]
```html
<template #item="{ props }">
  <v-list-item v-bind="props" />
</template>
```

I'm putting this with #19396 we don't really have any good examples for this yet.
