### ISSUE TITLE
[Bug Report][3.6.6] v-model value is undefined when clicking same key of button group.

### ISSUE THREAD

**Issue by ENIACElec** [vuetifyjs/vuetify#19851]
### Environment
**Vuetify Version:** 3.6.6
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Testing with code:
```
<template>
  <div class="d-flex align-center flex-column pa-6">
    <v-btn-toggle v-model="toggle" variant="outlined" divided>
      <v-btn icon="mdi-format-align-left"></v-btn>
      <v-btn icon="mdi-format-align-center"></v-btn>
      <v-btn icon="mdi-format-align-right"></v-btn>
      <v-btn icon="mdi-format-align-justify"></v-btn>
    </v-btn-toggle>
    <div>{{toggle}}</div>
  </div>
</template>

<script>
  export default {
    data: () => ({
      toggle: null,
    }),
  }
</script>
```

Click any key twice.

### Expected Behavior
Binded value stay same.

### Actual Behavior
Binded value become undefined.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdkUFqxDAMRa8ivJqBcbPrImQCPUfThRsrqYtiG0cOU0LuXsfOlEI3bTfGeuj/L6TnVcyhr568f1giilo0jJMnxdh2FqDRZoGe1DxfO6HlQHgDRWa0skfLGGAnsncUJwteycdOZF1SLvKVrWQ3joSwyMlppGRSQCdgUcEoywm5yGQs6gRTnNGoD4+7C5je2dQ4aSMHFybFsgxBOHBKbKrc9ltVGf3vumDGt3/EvceZzfDxQ3hUx4ruMG2gXdfCtq2p9jpf4vg11bcDpXLug/GcW/DmXWDQOKhIDGtx1IpVDaczXFs4HQygBNRgI9GlwO2cP9ue8eUqtktu2Z+XTy18uN8=)

**Comment by KaelWD** [comment]
There is a mandatory prop.
