### ISSUE TITLE
Speed dials with generated data and tooltips not vertically aligned correctly in Firefox

### ISSUE THREAD

**Issue by FiniteReality** [vuetifyjs/vuetify#1985]
It seems that the vertical alignment of tooltips in a speed dial with generated data are not correct in Firefox, while in Chrome and Edge they appear as intended.

### Steps to reproduce
1. Create a fixed v-speed-dial
2. Use a v-for to generate the contents (e.g. `<v-btn fab small v-for="link in links">`)
3. Apply a tooltip from the generated contents (e.g. `v-tooltip:left="link.tooltip"`)

### Versions
Vue: 2.4.4
Vuetify: 0.15.7
OS: Debian Linux (buster), kernel version 4.12.0
Browser: Firefox 52.3.0 (I have had people reproduce this in Firefox 56 and 57 as well)

I am also using Nuxt 1.0.0-rc11, but I can also reproduce this without Nuxt installed.

### What is expected?
Tooltips should be vertically aligned with each button in a v-speed-dial in Firefox.

In Chrome and Edge, they appear correctly aligned:
![Example](http://pacman.is-eating.us/i/E76NkBoMqyUkBW26o4GM.png)

### What is actually happening?
They are not correctly aligned, instead appearing at the top of the element:
![Example](https://user-images.githubusercontent.com/21000186/31097956-f9ad4bb4-a7b8-11e7-98cd-ae7a6c3d03b2.png)

### Reproduction Link
https://codepen.io/anon/pen/YrryYg

**Comment by FiniteReality** [comment]
If the data is hard-coded instead of being provided by a v-for, it appears to work correctly: 
![screenshot_20171002_214618](https://user-images.githubusercontent.com/21000186/31098622-255cf136-a7bb-11e7-9a22-e1f0b70ec1f5.png)

**Comment by johnleider** [comment]
This has been fixed with 0.16.

https://codepen.io/johnjleider/pen/pWWEmQ?editors=1011
