### ISSUE TITLE
[Bug Report][3.6.7] makeVExpansionPanelTextProps Error using Vertical Stepper

### ISSUE THREAD

**Issue by gwenf** [vuetifyjs/vuetify#19852]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.3.0
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to import and use the vertical stepper in your project. You can copy paste the example from the docs and make sure to import it from labs and include in your component:
```js
import { VStepperVertical } from 'vuetify/labs/VStepperVertical'
```

### Expected Behavior
It should work as shown on the website.

### Actual Behavior
It throws an error: `chunk-OC35QOBJ.js?v=24e0ea0a:2667 Uncaught TypeError: makeVExpansionPanelTextProps is not a function`

### Reproduction Link
[https://github.com/search?q=repo%3Avuetifyjs%2Fvuetify+makeVExpansionPanelTextProps&type=code](https://github.com/search?q=repo%3Avuetifyjs%2Fvuetify+makeVExpansionPanelTextProps&type=code)

**Comment by Ajay-lodhii** [comment]
makeVExpansionPanelTextProps is not a function

**Comment by mikestu** [comment]
I had a very similar issue which started happening with version 3.6.x, where we have a separate repo of custom components utilizing Vuetify, built in library mode with Vite (Vuetify as a peer dep though).  Apps that used that library would get this same exact error (but different chunk filename).  Once I switch the app to use "unplugin-vue-components/vite", just like you now get when you create a new Vuetify app using "npm create vuetify@latest", it then went away.  Prior to that, we were only using vite-plugin-vuetify, which does the autoImport for us, so not sure what's going on with it, like if something isn't exported properly.  We will likely just give the unplugin a try, and see if that works out.  If unplugin is really the recommended way to autoimport now, I'd like to see the documentation get updated to reflect that though.  Anyway, hope this info could help in some way.

**Comment by gwenf** [comment]
Thanks, I will try it out now.
