### ISSUE TITLE
[Bug Report][3.6.7] VMain breaks unit tests

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#19857]
### Environment
**Vuetify Version:** 3.6.7
**Last working version:** 3.5.18
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Unit test a component that includes a `VMain`

```js
test("displays foo with a v-main", () => {
  const wrapper = mount(
    {
      template: "<v-app>foo<v-main></v-main></v-app>",
    },
    {
      global: {
        plugins: [vuetify],
      },
    }
  );

  expect(wrapper.text()).toContain("foo");
});
```

### Expected Behavior
Test passes

### Actual Behavior
Test fails

### Reproduction Link
[https://github.com/ThomasKientz/vuetify-test-unit](https://github.com/ThomasKientz/vuetify-test-unit)

### Other comments
Removing VMain works as expected 

`<v-app>foo</v-app>`

**Comment by KaelWD** [comment]
This is basically the same as #19736, v-app waits for its children to be ready.

Browser based test runners will automatically wait for elements to be visible, but with vitest you can use https://vitest.dev/api/vi.html#vi-waituntil

**Comment by ricardovanlaarhoven** [comment]
@ThomasKientz What did you end up using?

await vi.waitUntil(() => document.querySelector(".v-toolbar"), { timeout: 5000 });

timed out at my code
