### ISSUE TITLE
[Bug Report][3.6.7] v-date-picker range selection when cleared doesn't start a new range

### ISSUE THREAD

**Issue by svannierswm** [vuetifyjs/vuetify#19854]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Firefox 125.0
**OS:** Linux x86_64

### Steps to reproduce
1 - Select the start of the range
2 - Clear the date using the clear button
3 - Select the start of the new range

### Expected Behavior
On the third step should create a new range

### Actual Behavior
On the third step end the range using the start range that has been cleared

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUEFOxDAM/IqVy+5KdPeO2goEv2h7CGmKAmkSOUkRqvp37CygInHZS+SMxzNjd6uIqC6PIZyXrMW9qJOeg5VJt70DqJdKeZekcRoLUCD0H/CWYzLTZ9OLGKTSlUSf3diLb1bhjSRTBaPeNcJSzX7UlviM9gLmbJMJVhOC0r0S1NaXPzM/hoSS4+32L8nBg7KkRTRltcTnYt0+cc2yxPjHhOv91vVldxP6RoUmJIg65VAGzBw8JlgB9QQbTOhnONA5D0wHIK2YgBeDhinHbjjtO7/RqH08QdPCeg3FI+dF2sydbmBw4zjXAGQttjuXrS3P8AVtO5jU)

**Comment by KaelWD** [comment]
It works fine in the link you provided.

**Comment by svannierswm** [comment]
> It works fine in the link you provided.

My bad, I copied another link instead of `:multiple="true"` use `multiple="range"`. **I will edit the link**
