### ISSUE TITLE
[Feature Request] target element for automatic created v-overlay-container should be configurable

### ISSUE THREAD

**Issue by mkohns** [vuetifyjs/vuetify#19853]
### Problem to solve
V2 did create the v-overlay-container on same level as the app was mounted to. V3 does create the v-overlay-container by default on body root level. This causes problems when running vue+ vuetify apps in a shadow DOM scenario within a running "other" webapp (i.e. drupal). It would be necassary to configure where the (singelton) v-overlay-container should be created. 

### Proposed solution
to be discussed

**Comment by ahmedy00** [comment]
This request will be useful for my current project as well. Could it be prioritized? I believe it would be valuable for many other users in the community as well.

**Comment by KaelWD** [comment]
This is what `attach` is for.

> in a shadow DOM scenario

Should be working correctly since v3.6.15: #20276
