### ISSUE TITLE
Drawer scrolls away / vanishes

### ISSUE THREAD

**Issue by joshribakoff** [vuetifyjs/vuetify#1987]
### Versions

0.15.7

### What is expected ?

I should be able to scroll without the drawer vanishing

### What is actually happening ?

As I scroll down, the drawer scrolls away.

### Reproduction Link

https://codepen.io/anon/pen/zEEoxY

**Comment by KaelWD** [comment]
Remove the `absolute` prop.

**Comment by joshribakoff** [comment]
Thanks, but why is the `absolute` prop in the official demo then if it breaks scrolling?
