### ISSUE TITLE
[Bug Report][3.6.7] v-text-field not updating correctly with @input and :value

### ISSUE THREAD

**Issue by michibe** [vuetifyjs/vuetify#19876]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a v-text-field and use @input and v-bind:value. Then enter a value. The update is only working on every second key stroke. Using v-model is no option for me, because i have to run logic with the old value before updating the field.

### Expected Behavior
The value is  updated on every key stroke as it is working with the normal input element.

### Actual Behavior
The value is only updated on every second key stroke.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UstuwjAQ/JVpLilSQ6QeUUDtrT/Q9lB6SJMNWDi25WxCEeLfu3GA8Dj3Yu3ueGdnvP7aR40v0lfnpl1L0SzKmGqnc6bF0gBZl+TOhTAkhTWcK0P+WJLi+vkcA++ulFZYvcPW+o0yK1gD6sjv0JB0l9iQhOzthrBVvEaXMP1yUinSJUhTTYbP5OkFu4wfb44ju+RHmXLW5bql+TKqm9UyGtEXZVzLUhcNhjFfoA0SH0M+5dyviKeheTL2pVf2jqbuDN06kWdTBmHgyci1gQD9r3KAd65nG2bdOcrS2yX2lWHHWXqxe0mbwivHsjduhy+gamc9Yw9PFQ6ovK0Ry7eJe1BYG4aYwLzHH+M30tri03pdPsSTnhGoWlOwkhc8ejG0/QgOsB/0Sf/gSVhOYI8cenmDIJESHZ5Mq3U4vv8AxfrlBA==)

**Comment by michibe** [comment]
Last version worked as expected: vuetify 3.3.13

**Comment by KaelWD** [comment]
https://vuejs.org/guide/components/v-model.html#under-the-hood

**Comment by michibe** [comment]
I don't understand, why this is not a bug in vuetify as it worked fine with the newest version of vue and until vuetify version 3.3.13.

**Comment by KaelWD** [comment]
You should use modelValue and update:modelValue on components.

> until vuetify version 3.3.13

#15904 changed the way bubbling events are bound.

**Comment by michibe** [comment]
Based on the link i could make it work with modelValue and update:modelValue. Nevertheless it feels a little bit cumbersome because the v-bind:value and v-on:input is working fine with the standard input field. As a neewby i would expect it also working with v-text-field.
However thanks for the answer and for providing such a rich open source component framework.
