### ISSUE TITLE
[Bug Report][3.6.7] Treeview item-disabled not working

### ISSUE THREAD

**Issue by b4rthm** [vuetifyjs/vuetify#19882]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
This is the example from the documentation, just click on a locked and an unlocked node. There is no visible difference, nothing seems disabled.

### Expected Behavior
locked node

### Actual Behavior
no locked node

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VsFy2jAQ/RWNLyQzQGog0HgIM7S99NJeOu0BOAhpGdTIkivJJhnG/14J41oOhphpewJp9+2z9ulJWuyDeZL0sxSCKJgaiBOODcyWAqFp1jMKIGOwc0OEImbj+nEZHH6XQTHrBj3KNF5zoDbIJXkCWkY1cCDGxdx4Nr2rilqS6Z3HaIeaKJaYAzs8J1IZRGGDU27QvihHscERurlFjzN0c5wrPkFHaFGOUZl+DNMIhV1/xjDDIUIdu3TOCDZMCo2iTi2nWEeEjEqhFiBbxqkCUSM8kB6YBt0/5T9iDoJihSKEk6SD8lqdEjD0AFslY7icPqrSf8BaG6niZsDKG/mRk97cN/bmkyRpDMKcNOb8+uvDovj41SIqArvnDNu8vC5/kaKRpqSanNTx6bQiTVQXpW71PZU07ytpmKDwbHUx+lTHOuihAq2lNNoonFwE+ro26ducdbKZmsQK351VK7YmVQzzwb/TK6yb8grBWuoRel7MemsjWgkSeobMegQr2g7mGTPr7ewGkLv/rmNrj4fnTL4TXGJ6hcmLcuNqsV+JkWtwh1xCN51uzU1nzrBwUsG/yAzia/Ge076l9gi0G9Pitybmlwu079dDY7++MwryL0/EwXmTlWs5YXjbZEXpsOrLB6wZQRy/yNSd4ShORs078Qj1vDKnGRYEKDJAtoL9SqFNAc82c84RXltidy9ZKGWqCfrmGVUU9oz1WRgl3bfI7Nz9OLj37lMpNmBbRgAxh6QpcXe9uy8z1u6+LGfz28Of3D1ajs+UoBtwJp50/6eWwj6f9suAaPsuihar3MZY7F4wvRgnXkIx6ZL2eR7k3WDYH/UHE5s+7I/79tdt2tVvh4hhCw==)

**Comment by yuwu9145** [comment]
`item-disabled` has been removed from v3 for select components, and treeview should be the same. `item-disabled` example should be excluded from doc

<img width="1211" alt="Screenshot 2024-05-26 at 10 16 37 pm" src="https://github.com/vuetifyjs/vuetify/assets/5698884/7049fe8c-b0b5-497d-9aa3-03d4c49c0381">

**Comment by b4rthm** [comment]
Then you should remove this here

![image](https://github.com/vuetifyjs/vuetify/assets/33357276/df58c18e-71e4-4ae9-bae1-c6ccc575aa01)
