### ISSUE TITLE
[Bug Report][3.6.7] Missing rounding to nearest step in VNumberInput

### ISSUE THREAD

**Issue by J-Sek** [vuetifyjs/vuetify#19899]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Use `<v-number-input>` side-by-side with native `<input type='text'>`
2. Use up/down to change value

### Expected Behavior
Rounding to nearest step - consistent with native behavior

### Actual Behavior
Blindly adding step value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrlWG1v2zYQ/iusO9Q2EMqxmxaDZnsoun3YhxX7UOTLPLiUSNlcKZKgKMdGlv++I6lX23lZsQwB5gCOxDveHZ97SN7599tBYdLJrmSWZ4foz2IQD3iulbHoFqWGEcuugwzdocyoHA0r3eFKriTbe9VUycKiSoAW/Ymj25VEyG5ZzmLknxGiLCOlsJ/D4FDwzdYOL4LMaxaNKkJe2nlH4E8o01Vxn4SkXzdGlZKCxddT5v5qm+5z1zzXT+F/+K4iao1efyrzhJlfpC67znfEcCJhZKhKK7hktPVBmSy4PYAsVbkmabMkF7G0RonrZnZhIdx2chvK3XglBxc+Kx+0jgBUSMncslwLwHTp1OY7TLT2j/7FGScQiqmGwiAxFKWCFMViNcj3mJRWIU3we5Qf8NVqgAp7EMzJyB7fcGq3MZrOLi/1fjVo7IAlvZwny5/3mqWWUZSwLdlxZeaTpKMEaqVonGmB3/dseAXBl2XB5aaGokCjUk+oupFjVGxVKSjyyQOERckQB0YxAg4BYyoOiFDqJn+BUf1lPgFrPfeTUnSDntToVGBQvuOUmRaPA34LIc4njairD0ONZgbR4hvmKIgTJSjM+kQs37H5BNT6Xoy66UflUgO4wGLB0hlMuo7yJIRU5ESI5citczGcXg7H80kYOnboLXBHz/4Y7KCDdomVnsCrwbG49pgo4zABTszQDZ5eXp6q7nCuKBOgzPYEGMiuXXKmp4qxj3c1mJ4xEudcguishOz9pBPZ5Ci9Hsl/Gdzo3UsEd3Y/uNG7e8E9l5Ia3H+KrRvpU7mPpYUz5My2qI77l7EvdjgkCJ/NoSCJx/2zskQgquAyeWp6IJb/BfefDUC4el4Yv70G3Jb1heondG9UNxIu3PmkcxHDa5Eari0qmC01gCI3EJAFKPy0po4yLOtWT8Mf3FxfE0DV1DtYoXYC5dEMaoBz8lktj6b3aLx9xMJVzwIwwC8Awq1KDtNL+33VR1ene6f2KDPoEMDf6X4kgevcXaucCfpRyYxvGvY2btBrQJtJCoZ6RU0hlEWS5O787Wr0C5Yd5rBucMUz0PuOWGuKCApSqqQ4QAxNvLBWoFUoJuF9Y9gB+1qTSXx0Ci9zyrFQ6VdcVX2OEs5Nq9Shk4uzIVMfO5jWBembKeUKzBIKsgtUFuyDW+L9DPMIQN5rzdEYxLUwVFsLV//Csn51+fLyVkMbpd30oPGbe5tX5XBCikCrH2MUloX+ggchvAOEtlBZ/cRgJ4kCNBKlBCMSVIauGHVBeiNwfbTSapBAIuRHJi0zR7K75VF8Pp/MRViDMhqN0WJZ1+wGkDSyreDP1XRxWGXk3pqa/YTSGKc+ola/E+aD07aQR9b1UwOHXi0gMTJgS9GbN2cVfJIi/133CwGLPhKdTfVkNKIo8vxoOxUHZ1yj2nMKaYG8ObuCWde3qSxrGhhECkTkoY2rc7g4WrtuAxWp0iwctNERSiiOoRhnTI+iHfYrwe7QhU3O6LiOF+NapkNDgEEOfcv3eh8cP9WyNuzIdG2QS7e/MfRnBvq06ay1/KjtrmC9rvqcxkHVY82uHrYIdirWVO0kXEa+mfwGV9DMPeSq5vMpQOu1V2gMWra32JMdmBHmvApnEXSzj7iouO/tnDiKpbKdtDBjlBn7uwtsNcFUh+567bPiGffMjkA73cZxwjJlAv3/G4ckq4+SZ/YH5D/dVKFpwQro5n/HmDZHtB/3N2WMlHFxnCEA7Hi3y101cXfhrgH/9cffUgOcoQ==)

### Other comments
Although the general behavior may be a matter of opinion, I would rather be consistent with native control.

Example implementation:
```ts
const canIncrease = computed(() => {
  if (model.value == null) return true;
  return model.value <= props.max; // removed ` + props.step`
})
// repeat for canDecrease

// inside toggleUpDown
if (canIncrease.value) {
  let newValue = +(((model.value + props.step).toFixed(decimals)));
  newValue = Math.round(newValue / props.step) * props.step;
  model.value = Math.max(newValue, props.max); // canIncrease won't prevent going over the limit
}
// repeat for decrementing
```

**Comment by yuwu9145** [comment]
I believe "round to nearest step" is one of the native `<input type="number" />` weird behaviours that we want to avoid. Check out #19605.

Checked two other UI frameworks (primevue & element-plus), their number input don't support rounding either.

**Comment by J-Sek** [comment]
It is weird in the "_not backed by HTML spec and left for browser vendors to implement_" sense, yes. But I would argue number input is more pleasant to use when "_step=X_" translates to "_snap value to increments of X_". You might notice PR implementation improves on dumb up/down adding/removing specific value, but avoids the rest of weird behaviors, like using `min` to determine snap points or inability to hit `max` value in certain scenarios.

I also don't agree with everything in #19605. For example, given `max='100'` I would rather accept the number pasted from clipboard "150" and show validation error instead of confusing end user "_wait... wtf... I would swear I had 150 copied to clipboard_", but this is material for another issue.

**Comment by J-Sek** [comment]
Assuming I fail to convince you, how about making it optional with `snap-to-step` boolean prop?

**Comment by yuwu9145** [comment]
It's probably subjective, but for me, it's more intuitive to see the increment by step without rounding. At this stage, I'm not convinced to introduce `snap-to-step` either, as overall so far, I can't think of a practical use case that must use "snap value to increments of X". In addition, it's hard to define the exact spec to cover all cases, e.g. if initial value is 2, step is 3, max is 7, how should rounding work in this case?

Introducing `strict-range` could be nice, feel free to create a feature request

**Comment by J-Sek** [comment]
> _if initial value is 2, step is 3, max is 7, how should rounding work in this case?_

Step with rounding (snapping) would be predictable to yield only increments of `step` value except for min/max unless they are increments themselves. `2` would become ↗ `3`, `6`, `7` or ↘ `0`, `-3`, `-6`, etc. I wish the implementation could be simpler and without _good enough_'s... but yeah... JS and math... make my case weaker.

In my project around over 1/3 of the instances of number input have `min='1' max='9999'` and steps are `.01`, `.25`, `1`, `50`, `100`, `1000`, `100000`. The implementation in PR is the behavior I got used to because:
- (as a user) if I increase/decrease value I immediately see what the `step` value is
- by deviating from native behavior I have predictable steps even if min/max do not fall on the increments in the example above `min=1` means positive integer required, while `max=9999` means up to 4 digits. With `strict-precision` (i.e. feature I am yet to suggest for VNumberInput) they make UX the most straightforward... but I am also used to it :) so I understand it might be a matter of taste.
