### ISSUE TITLE
Missing accent attribute in v-btn

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#199]
When you put accent attribute on the button the accent class is not appended because the v-btn component doesn't have an accent prop

**Comment by johnleider** [comment]
What is the accent attribute?

**Comment by ralphchristianeclipse** [comment]
@johnleider in the docs we have a primary attribute on the v-btn with other context like success , info etc...

i've found that the accent attribute is missing or prop in the v-btn component which would likely
 change it color to accent

**Comment by johnleider** [comment]
I don't intend to support that out of the box. You can simply use the class yourself on the button.

**Comment by Moustachauve** [comment]
Why support every other theme attribute but the accent color?

**Comment by johnleider** [comment]
Ths behavior will more than likely be converted to the new colorable mixin, all colors are represented semantically already, having them as an explicit prop only exacerbates conversations like this.
