### ISSUE TITLE
[Bug Report][3.6.7] V-Menu prevents form submit when user presses Enter key in a text-input field

### ISSUE THREAD

**Issue by sigridsb** [vuetifyjs/vuetify#19920]
### Environment
**Vuetify Version:** 3.6.7
**Last working version:** 3.5.14
**Vue Version:** 3.3.11
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Click open menu
2. Write some text in the input field and press enter

### Expected Behavior
Pressing enter in a text-input field will submit the form

### Actual Behavior
Nothing happens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1VMtu2zAQ/JWFerADxHGcAj0YstDHuSjQ9Fb1QEsrmyhFEuRKSRDk37ukLJuVlYMNc2aW3NmHf79m3lXrL9be9R1m2ywnbK0ShEWpAfJ+JayNP+OhMpqE1OhOUAT3pEHWuzJzxtDXjsjoMivgh0UN31F3sIF8HWVpVMvMeATgs6lR8SUB35TZhdpWynhcGR1fR02rSsnqL0sboTymUlGR7AUZx+SHNJuL5IjycCTmP97f2+eUUaYSJI1mjoxNmSdZ05Hhh0+TEIvOSx9yGrGzw+ixMa6Fz77btzI8Ofzg2lxEQ1WFq//DzuiKJCks0jIm8HyI5A5OqEg683QFn5qqgD+eM9w8TLJLZITPtGokqnrarV/MlBkosY/Yo2kRgpqx9dyTwYVR1zkyfp3k2fOMr9Fy6LvRfs61t6JCF/OYYcPo9sJJoUN/hpwL+CZ0hepqaCdxbCEOmnWyFe6FzU5vAnqxmPYdHkWP79x79jlnZiTT8WIozNdlpxgI7Ri3NVY5XdeADNucr5Mt56OvnLQEHqmz3EZ9CBb8aRRka40jeIWf2NyCwwbeoHGmhQX/YyyGsvJDniAOwzbo8r0xCoUuYBcilnFTbybKMDaD2pOT+jCKF4tEOdSOmeUN7IoI8s13yhyWi4EjrENAvh5ccM7Z263ulIpff/4BYvRuDA==)

**Comment by TIM56887** [comment]
caused by #19519
