### ISSUE TITLE
[Bug Report][3.6.8] Click-outside directive does not handle touch events correctly

### ISSUE THREAD

**Issue by borisgraeff-pxo** [vuetifyjs/vuetify#19924]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.7
**Browsers:** Chrome 125.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
On mobile, open a menu and do a drag move outside the component => the menu is not closed.

Do the same on desktop, the menu will be closed.

### Expected Behavior
Any touch event outside the menu should close it 

### Actual Behavior
If you do a 'drag move' (click, move then release) the menu stays open

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVs1y0zAQfpUll9KZuM7AzSQBhoEDw8ABhgvhoFhKrCJLGmntNNPJu7OS7finocBAD6282p9vV9/u9tv9zLs8fW3tTV2JWTZboiitYijWGw2w5LKGXDHvV5sZijtMcqFRuM0sXpOCbQ8An6zQUApdzQELOqI7AhrwQokcIRjDQWIRLqE0lRdgHHhZViEaMOCO7emiFp3D1brRJZcgPcEwXvA2bNrFHQD4aA5zMAFFMLNsL0ASIrOVSkAtxaGJfzSVgx2rjZMUl4sajVF+DtxEO8/KMwIUHkcwPLKjjzGGONrz1kHaoRqe6yTYdj7py3ChqJ5ROuvkWcwvMTrJDZVYU6mVzH+Q3o4pL3pFnzujVOLRUd32R1KIlr2CMjlDaTTdCM07+blM5xcmKF4ZzFiOsmZoHBncg3XGejidX7hNYYsacqOiktRc7s1mRg62dCZJNCKTngTLNNr0UdMBsc7COsmZ41BKnRwkx4JcPV8sprGV9DiQnGUJPWA5lAOhF4SAJ4wSYgFrgWh9lqY514HhKHfHW3+TmzKVJTHEp7em0De3dt/Xry1ztUWJSpCPd6bSXDgwO/jauJgqd5rvyRl8EJK0xyoj+JfewAbYE62u8FNpJEvTk8RjeAlXsTWd4FeQwdXVFF34kcSqwDkuk0Iwh5d0auYk09i2+iWNVz0na1jBE/rzUG09ffsLDBiKB485fPdWPqBLrAdNpFDeGKQ7T1Qe5csUFT0AjYW8mGYx7FPviSoPE+36wVbOqgv3im2jg7eabWkEtX6oT6aKBWWRcIFMKj++i2k2AB+t2v/LtpAaL0D8y1x/4eXfE/0dPcI8ScJEM9pPOeAty1vmtMcHhQtjbtoGPevjDljR8ogDeQ1vmM6FilimfJ+MTOto3DiaG3/ufVyfz6xfjF3+45hBcjH77qLbR/QZQj26uJqvL6MV3uzFZUpdRxqTgb6ktSRt03bizhqHtFp3rFII940zThM5g6fXYaE+bWUQFnFG/ypUYt5JArasqcJAFltnKo4sG5mfruPhFPCdEQV0eFTN3NkafuwgFULuC8zg2WJRFy96w1Z5dprrSqn46/tPHG+rOg==)

**Comment by KaelWD** [comment]
Browsers don't fire click events for touch drag, and handling this manually seems too complicated for something that isn't actually a problem in my opinion. We can't just close it on touchstart because that would break scrolling.
