### ISSUE TITLE
[Bug Report][3.6.8] VAutocomplete with auto-select-first selects highlighted option even when clicked outside

### ISSUE THREAD

**Issue by eric-pa** [vuetifyjs/vuetify#19929]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
1. Type anything that highlights an option
2. Click outside of the component

### Expected Behavior
Same as when aborted via ESC. Not select the highlighted option but keep the search text.

### Actual Behavior
Option is selected like it was clicked despite it was not clicked. This can even be reproduced in the docs:
https://vuetifyjs.com/en/components/autocompletes/#new-tab 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUcFugzAM/RUrFzapEG2TpgnRavuCHXYsPaQhaNlCEiUGaUL8+0woLb0kjp/t955zHFkMkn94Xwy9YiWrUHXeCFSH2gJUQy68T2F6SGdRaKvCJbVU9Oikoy6Fak0DDHnnGmX2NYvKKImqqdkNLTXxRALTvUXmafnSkrc6RLxB0igRxNlcWQ4Vv6e/yYpe2MPXhbmEcYRVBkxTxRN8sUUz7n2lqcl2xTfroGeUQXukUdgvW9GddwFhhKBamKANroOMNpnN5aTY2YiQPMJ+rnk4Zp8etbPwlO1gjZ838Ut2etw2X2Uv/bY3hnBykKSQCLZjRtvfWPxEZ+kHx7m3ZjLSWks41uwb0ceSc9lYqqE/0UMorEJufcdJK+r27/2leC3eeKMjrqnciHMs0phTbScimnYzezpO/98Xu3I=)

**Comment by dnasir** [comment]
Sorry for reviving this issue, but the description for `auto-select-first` says:

> When searching, will always highlight the first option and select it on **blur**. exact will only highlight and select exact matches.

I added the emphasis on blur. The `blur` event is fired the input element loses focus. This can occur when the user `Esc`apes, `Tab`s, or clicks away from the input field. So either the description is wrong, or the implementation is wrong, or there's confusion on what the `blur` event means in this context.

**Comment by eric-pa** [comment]
I guess the description is wrong as it doesn't make much sense to select something on a `blur` event like `ESC`.

**Comment by KaelWD** [comment]
Yeah I don't think this was a bug @yuwu9145, only escape should cancel selection: #13788

**Comment by dnasir** [comment]
@KaelWD I sort of understand the reasoning behind the fix. Like, how do you "escape" on mobile? But you can always just turn off `auto-select-first` for mobile if you don't want this behaviour.

**Comment by KaelWD** [comment]
Ok yeah I could see that for combobox because you still need a way to enter a custom value, autocomplete only allows you to select something from the list though so "just keep the search" doesn't really make sense.

**Comment by dnasir** [comment]
So will this change be reverted, or will the documentation be updated?
