### ISSUE TITLE
[Feature Request] VAutocomplete add option to disable removing of already selected items on Backspace keydown when search si focused

### ISSUE THREAD

**Issue by volarname** [vuetifyjs/vuetify#19926]
### Problem to solve
Several users that are using our product based on vuetify have problems with VAutocomplete (chips, multiple):
When you search/filter something and you want to remove/clear the search text an you hit Backspace more times it will also remove data. It will be great to have possibility to disable UX jump from search field to latest item using Backspace.

### Proposed solution
New prop to disable option to jump from focused search input to latest selected item on backspace press. Hitting backspace key in focused search field will only remove the text, the remove can be done for example by arrows selection or close icon on chip for example. It will be completely optional, so user can choose to rnable/disable this feature

**Comment by J-Sek** [comment]
[Workaround](https://play.vuetifyjs.com/#eNqlVm1v2zYQ/iusClQKYFMpmqKoEXfZS4cV24ChLfYlzgdaOtls+KKRtBMjyH/fHUnZslMMAWZAlnR3vHvu7jlS1w+F1L11YapFz795a4pZ8bAwjC2ywi+KGYsSkm03QO+LYh1C72d13bQGl7Wg5NZxA6E2va6v0Kx2GxOkhmlr9dUb/pZfvK5b6cNYzsHr6dLZOw8OvSyKyShOjcItuKkD04ID99y4J8uOYp/o/jN+kN3uGTGz5dUFf83fpyhZNFVi6SlEdE2eHxfmsZgUSppbf1LsxsdCXw8A/lfM6Iw83aSA3jX1j33P0QgjXgbQvRIBPpDJ5XYq+p6FNWiYL4pWuNtFETVR11gThDTgsigL9dIu7f0gYmw71RZBogMPCpogrUkI0k9vVJC9goOkWcveP1k/8yBcs45u6GHsYyYRt0fVdSnKCSuX9NeUN2MbBx0adBJUexDXQzb1aTokweTx+bIeFQVffeNkH5iHsOmZEmaFbmkU4rI0GOyBWfOnRTZDO6HI7JF1zmpWYplL8oJZWuMDi3jYnGyqs4M4pZjlZXmkyTXMypOM0ZJs99Gr6ozNPwxDGqPxrVAb4JSus+ozdFy07cctmPAHsgWwAFV5C7vW3hl0WsGM/Q67pRUuGY39Yb4dWnA0Z/P5nJU/iebW96KBkr16xV6kNFLAs8MixoD3DsjbL9AJJEDKfdD5YPtPWkMrseh/OduLlaCUD1Y4LfEWBfR/Wae2YBMyqTX2kgePpN73pHGADpHtJ+3YG+RJ2av5MDsHI1o9KPPcHJQoi7SILU79ogGaHyJXeCFclFIDOrni4Jx1vwnTKnBoCVReWmoVJF0Fsam0ZOOhyoj2Mk2NrsqX+Ew8ydlHGCl9B9pu4UvYKfgqVlRDLKmWHrhQqrpWVrS/Iheqswmj508UvDpLTOo2JpHt2AlDVsVuphwDSuastc1GY0v5Pxtwuy+Rp4i+fDnsP3EfmXry4dcAIdGaGPQCPZxhjLBxkb74ynuBW3H4qHAN+kzxf15L1VZkjJvXET5CHtFFz6xa42xkjMktM3DHcuJV5QDruwWazW8Ic8zplBLtw+OcUgMzmqokdYLPoiniU2hejpIbKQkMauk2kj6dOkoCRy6DG7t/ahupEY1jAsl2D3dp2x1HRuBhVpGD/Zw8rRr1ft/PXKvjalblcOJ0aOv5ytqVAtFLPE2srvFE+aETWqrd/DPu/MHOXp+fT97gdYHXW7ze4fX+/JwK9jR+5NtzAXz/aNetjNCu3vF7goOzH8BJoVrwcmUkReAatwPUZRB5TDI1v7tP/H2yGRy2goWB+2iauDLsGsOY54VVTCiSfv+V1Kbt7msSIo1W61DmL4u6jk3CN2pU8Tgp0ucJQo2HeTHphPJwfGQPsoyhmDzsH2d52ePNv90HSxw=) - bind `keydown` handler to the field ref and conditionally suppress `backspace`. User can still use arrows and [Delete] key for removing.
