### ISSUE TITLE
[Bug Report][3.6.7] v-model custom modifiers doesn't seem to work with v-date-input

### ISSUE THREAD

**Issue by msquare98** [vuetifyjs/vuetify#19930]
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.21
**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just create a Dateinput and add a custom modifier to change the date format.

P.S I am new to Vue and Vuetify, forgive me if i miss any basic principle here.

### Expected Behavior
Change the format of date from mm/dd/yyyy to dd.mm.yyyy

### Actual Behavior
format stays default mm/dd/yyyy

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUMtug0AM/BWLC0Tica9IpUo5NqecqpDDljXtSvuSWaiiiH+vF0JCOIAZj8eeOd+Sntrqw/tyHDB5S+qAxmsR8L2xAPVYCO/ncv5pnQ1CWaQ7NIOS2YWyfggrCNA67WjfJJ6UEXRtkmeL1Vv8dVpiJEhZGlNery+UsTBOoi47R0aEqM/MPggKB663TC2+UXPzFJtMHMyLjiAlbIjDfE/RKa1RPglPE9XWxWqXwVe/EVniqKtNTHXfkvIBegzDkpUy3lGAG0jsePoYzcAEHTkDKeecNjbSWL0PcH4Yy4Ftq04h9RfYb4ez9EFKc7gtB/K+bBR6wN2K8OYOsofIJr8NBYD4ULJg8Q+i4l2kDO7TtUJjxE6BlP3JUhn3pYdDeTyWX/yku1VmWoopj9+J4bpacuAEkim3g9bz6/IP2k7E2w==)

**Comment by KaelWD** [comment]
Modifiers are for the component `defineModel` is used in, in your example `<App v-model.formatdate>` works but v-date-input would need to implement the modifier itself for `<v-date-input v-model.formatdate>` to do anything.
