### ISSUE TITLE
VAutocomplete performance on large lists

### ISSUE THREAD

**Issue by b-bika** [vuetifyjs/vuetify#19941]
### Environment

Vuetify Version: 3.4.1
Last working version: 3.4.0
Vue Version: 3.4.27
Browsers: Google Chrome, Mozilla Firefox
OS: Windows

### Steps to reproduce

1.  Open playground link
2.  Select 3.4.0 Vuetify version
3.  Try to open the autocomplete menu & search in the text field. Notice how it works instantly.
4.  Switch Vuetify to 3.4.1+ version
5.  Try to open the menu again & type into the text field. It becomes super laggy

### Expected behavior
Should work smooth in newer versions

### Actual behavior
Lagginess

### Reproduction Link
[vuetify playground ](https://play.vuetifyjs.com/#eNpdj1FqwzAQRK8yqIUkoNop7ZexA/nsGerSCHXTCGxJSKuUYnz3SnYLJfrR7jJvZ/Z1EjHo+uh9dU0kGtEyjX5QTIfeAu31QXm/lEujnWVlLIXf0apI7LTLFDGhMXlB7Hqx/L1A/UfXt3iZrNvb+p9rbqMOxjMicVrNzehdYEwoPonpQyLQWeJLsb5gxjm4EZt8wabwyDIbGUsEdDiGoL6rotlOGMh+8qXB4748zBLbdwmzQ3fA6SUTuLufzHzalVhrkBxBzNKmYZDiqXqu9uLtB2KLZh8=)

### Other comments
My array is pretty big - 100k items and I don't expect the items to change. I came across [this discussion](https://github.com/vuetifyjs/vuetify/commit/f5b13c153262b8d4b5e12a23d62d574b2f36ec48#r132500274) and it makes me wonder if this is the cause of the autocomplete becoming slower in 3.4.1. If so, is there a way to disable the deep watching of the items? I tried wrapping the items I pass non-reactive via `shallowRef` & `markRaw` but none had any effect

**Comment by KaelWD** [comment]
With vue 3.5 we can specify `deep: 1` to only update when an item is replaced, this should shave off 1.4 million iterations in your example.

**Comment by TicTak21** [comment]
@KaelWD Hello. Can you provide a code sample with a workaround for this? I also have a large dataset.
