### ISSUE TITLE
[Bug Report][3.6.8] VListSubheader doesn't automatically contrast to background color

### ISSUE THREAD

**Issue by karanb0** [vuetifyjs/vuetify#19956]
### Environment
**Vuetify Version:** 3.6.8
**Last working version:** 3.6.5 and < 3
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Change the background color of a parent of VListSubheader. See playground link.

### Expected Behavior
VListSubheader text should contrast to background color

### Actual Behavior
Color always remains the same regardless of background color

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdkj8LwjAQxb/KmaUK2qKCiMSCm4KbooN1aOOpxbQJSeoi/e6m/8AqiLPbvcsv9zjeHR5EK+YtpHTvGZIZoQYTyUODfpAC0PsglLIsrditY21q0chNFl0xPKHyt6gNLMuaem9v7T8r6+FDyRclDGu+7H9HR7+j40+07rT2gegyYIILNQ9IxEN2C8i/rEi9Jj7qvcRqpWYqlgY0mqxKN06kUAYeoPAMOZyVSMCxF+EUOAATqfVM9AXmBdF1lsi5gL1Q/NRxeoVBNdIOI3k/zTjvk7E7cafk+AQ8g8TM)

### Other comments
This hasn't been working for most of Vuetify 3, but [briefly worked in 3.6.5](https://play.vuetifyjs.com/#eNrdkj8LwjAQxb/KmaUK2qKig8SCm4KbooN1aOOpxbQJSeoi/e6m/8AqiLPbvcsv9zjeHR5EK+YtpHTvGZIZoQYTyUODfpAC0PsglLIsrditY21q0chNFl0xPKHyt6gNLMuaem9v7T8r6+FDyRclDGu+7H9HR7+j40+07rT2gegyYIILNQ9IxEN2C8i/rEi9Jj7qvcRqpWYqlgY0mqxKN06kUAYeoPAMOZyVSMCxF+EUOAATqfVM9AXmBdF1lsi5gL1Q/NRxeoVBNdIOI3k/zTjvk7E7dSfk+AQ8esTJ) and then stopped working again.

**Comment by karanb0** [comment]
Here's the commit in 3.6.5 that fixed it: https://github.com/vuetifyjs/vuetify/commit/43529fa936cbb0d58d78e1c48aebc1e6c7fe3d1e

It was shortly reverted in 3.6.6: https://github.com/vuetifyjs/vuetify/commit/1b56e4e601c098620daf6eb077d797174703e0da

**Comment by J-Sek** [comment]
Workaround: add `theme="dark"` next to `bg-color="black"`
