### ISSUE TITLE
[Bug Report][3.6.8] Custom border classes are not generated

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#19960]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Firefox 126.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Create a custom theme.
2. Add a new color called "test".
3. Try the automatically generated class called "border-test".

### Expected Behavior
The div's border where the class is used should change.

### Actual Behavior
The div's border where the class is used doesn't change.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1v00AQ/Suj5WCQ8iWFU+RWAtQDCAGCigvLwbXHzpb90u44JIry35ldJ8atqkr1YT375s3ovdn5dRQx1Mtdj6Taw+I+io1QxrtAcIQ6YEX4c8jBCdrgDBRnbiGttLjP1NrZSHBOwNXDwtdHaQFoiwY3kGOABtuq13Q7gEXdR3Lms+q2VMwGRubHsQBgwpmgjDvtwpSYqzEyq3jVrlaXhuk7jfElGv7pPL2RVszyNN55v2AzPIqS0HjNXq4TrdzNK+9zmC9smyplMZwhBhu1g1pXMV5JcdfNkw4pINJBIyNbHOSvVyu/l+K6XDL/6WJD87fAHXxQpgoHuHOhwfCShuXyscKEDAbK5cQYu6bIzFZ1vADOsu88TClqZ7zSGL56UvzEUoxjlqLS2v39lDEKPZ7nyTVbrP88gd9HFrjh4FvAiGGHUow5qkKH7Culb358wT3HY9K4ptfMfib5HaPTfdI40N73tmHZE15W+zEvtrLdbbzZE9p4MZWEXvYgsfnxPzxj/b/c9WKd63h9eI6nme21zsfvf5j+FEY=)

### Other comments
The other generated classes like "bg-test" work.

**Comment by modos** [comment]
you must set a width for border, for example use ```border-xl```

demo:
[https://play.vuetifyjs.com/#eNp9U01v1DAQ/SsjcwhI+yUtp1VaCVAPIAQIKi6YQ5pMEhfHjuzJNtVq/ztj56NZRJuDM37zxp73Mvl1Et7l22OHpMrHzb0XB6Ga1jqCE+QOM8KfQw7OUDrbQDJyE2mkwT5Sc2s8wZiAq8vC1ydpAKjGBg8QY4ACy6zTdDuASd55ss1nVdWUrAZG5Pu5AGDBWaCMW23dkhir0TMreVXudtOB4TnP8RQN77Ce30gjVtGNd227YTFsRUrYtJq1XAdaelxnbRvDuGHZlCmDboQYLNQRcp15fyXFXbUOfUgBnh41MlLj0P5+t2t7Ka7TLfMvihe6xlMaWr8FPuqhVoRwZ12Bbt3rKfJWq2LaDNc9nfHMvRPh4v50+6+ggAx60+3CBzaJPDNLVfG8WMM2Re+lyG3TKo3ua0uKJ0KK+atIkWltHz5FjFyHo/1cU2P+5z/4vedGDxx8c+jRHVGKOUeZq5CFhvTNjy/YczwnG1t0mtkvJL8ju9aFHgfa+84U3PaCF7v9GP8DZapbf9MTGj+JCo1OYxPYPCsfXpD+1O5+s491PG3s43llOq3j8vsvA4cg1g==](https://play.vuetifyjs.com/#eNp9U01v1DAQ/SsjcwhI+yUtp1VaCVAPIAQIKi6YQ5pMEhfHjuzJNtVq/ztj56NZRJuDM37zxp73Mvl1Et7l22OHpMrHzb0XB6Ga1jqCE+QOM8KfQw7OUDrbQDJyE2mkwT5Sc2s8wZiAq8vC1ydpAKjGBg8QY4ACy6zTdDuASd55ss1nVdWUrAZG5Pu5AGDBWaCMW23dkhir0TMreVXudtOB4TnP8RQN77Ce30gjVtGNd227YTFsRUrYtJq1XAdaelxnbRvDuGHZlCmDboQYLNQRcp15fyXFXbUOfUgBnh41MlLj0P5+t2t7Ka7TLfMvihe6xlMaWr8FPuqhVoRwZ12Bbt3rKfJWq2LaDNc9nfHMvRPh4v50+6+ggAx60+3CBzaJPDNLVfG8WMM2Re+lyG3TKo3ua0uKJ0KK+atIkWltHz5FjFyHo/1cU2P+5z/4vedGDxx8c+jRHVGKOUeZq5CFhvTNjy/YczwnG1t0mtkvJL8ju9aFHgfa+84U3PaCF7v9GP8DZapbf9MTGj+JCo1OYxPYPCsfXpD+1O5+s491PG3s43llOq3j8vsvA4cg1g==)
