### ISSUE TITLE
[Bug Report][3.6.8] No item matches when all headers use custom filter

### ISSUE THREAD

**Issue by hitochan777** [vuetifyjs/vuetify#19970]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Use `filter` key for all headers in v-data-table.

### Expected Behavior
Items  should match according to filter functions.

In the current doc of Vuetify 3, it says `intersection: There is at least one match from the custom filter, and all columns match the custom key filters.` 
I am using default filter-mode which is  `intersection` so the behavior seems to follow what the docs says.
However, in the doc of Vuetify2, it says `intersection: There is at least one match from the default filter, AND all custom column filters match.`
If I understand correctly, they are supposed to behave the same if I don't specify custom filter and let it use default filter.

One workaround is to use `every` for `filter-mode`, but I just want to know if the current behavior is intentional or not . If it is intentional it would be better if the documentation gets more clarification.

### Actual Behavior
No item matches even when there are actually matches. In Vuetify2, they matches properly.

### Reproduction Link
[Vuetify2](https://codepen.io/hitochan777/pen/LYojbRG?editors=101)
[Vuetify3](https://play.vuetifyjs.com/#eNqdU9tuwjAM/RWrL4AEFJjGRFSQpl2kfcIEPHipgUihrZy0m4b49yXcWhh00vJQ2Sc+59iuMt0EhmX4mGXdIqdABJGldabR0mSWAERFJ0aLHYsfmkCsCGNiM54Fh2gWgFCO4aGYjCG2DptEYZXnlKKwIutSI1lldmdBX1nKFmJaYK4tbDwG4NnN1jEDYLI5J2UOYAhZrgQ0Gu0SPLQlYFpiUGX5U6DOyRETXFOV7I9VVvu75/0w0Oz3ekvnxYVKlq3L6oXSlliA63Q8Acs5nRVsz7LNyViiTlmRabRPfk8l9Fv0ptACbUXjFV2/vsm/JOaV+PjX6lfmV+UdOP2mBN7TZc7O+bzmOJWA/v3oclFoBQy7vbr1XHV8kwSSCddgMIk/lVzdth3cPVyzHf3D9kVqVFxjNRxcs+rXjVhufbsP9pcuicLTewi27STXeveZ/wASevem)

**Comment by hitochan777** [comment]
I missed the fact that `filter-mode` defaults to `intersection`.
I am trying to migrate from Vuetify 2 so it would have been nicer if the default behavior remained consistent...
But anyways sorry for my misunderstanding.

**Comment by partment** [comment]
When all columns use custom filter, have to use `filter-mode="union"` to matches properly.
On the other hand, If at least one column don't use custom filter, use the default filter-mode which is intersection to matches properly.
Quite frustrating when migrating from v2.
