### ISSUE TITLE
[Bug Report][3.6.8] When selecting time, model value of v-time-picker is not updated

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#19975]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
First select an hour and minutes, you will see that the model value is updated correctly. Then try to change the selected time, the model value, it will not update.

### Expected Behavior
Every time the time is changed, the model-value is updated.

### Actual Behavior
The model-value is not updated when the time changes. If you change the minutes it works fine.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplTksKwjAQvcqQlYIxe0kFD+AJrIuQTCGYpiGZFkW8u/mI+NkM8x7vd7qzFLU4hLBdZmQ7JgnH4BThvvcAcuEqhPpWoCdPynqML6qSZEfkweoLRlj4OBl0Xc9MzugZiC8lXokPFp35F0ZUZvLu9nZI8dtXmDZHio+ZGSYdbSBISHNbm42JoERDBwaHnHEsfat1MTd5FrLHxs/O1XN+Atr+WW0=)

**Comment by modos** [comment]
it updates the value after you change both hour and minute. so, if you want to only change the hour, you must change minute and then select the previous selected minute.

**Comment by alanscordoba** [comment]
Ok, but it is assumed that if you only want to modify the time, you should also update the model-value.

**Comment by dekart** [comment]
Right now if you change hour but don't change minute - the model is **NOT** updated.

I strongly believe that if you change hour and already have minutes set - the component should update the model value on hour change as well as minute change. There should be two updates, each for every part of the time value.

Sample case: 

I have time picker where user selects time. It has some default value, say 10:00. If player changes an hour (to 11 for example) but don't change the minutes - they expect the value to be set to 11:00, but with current implementation the value in the model isn't updated and the change is not stored.

I have to add special event handlers to handle hour changes in such cases. I have dozens of pickers across my app so such handlers bloat the code noticeably.

**Comment by blalan05** [comment]
duplicate #19545
