### ISSUE TITLE
[Bug Report][3.6.8] v-data-table maxWidth doesn't work

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#19980]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Firefox 126.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Create a v-data-table
2. Set the "maxWidth" of one of its headers.
3. Load data with long strings.

### Expected Behavior
maxWidth value is taken into consideration.

### Actual Behavior
maxWidth value is ignored.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptk01v2zAMhv8KkUsurlPsGKQFhhU7rbvs69D2oEhMQlSWXEpKVxT973vljyzFBhi2RdF8H76i714XSe3qY9+3x8KL9WKTueu9yXx9H4g2xwvT98PrsLAxZCOBdQoNQWeyuchm65nWBzaONV3dL6a3+wWtBTVraHjeL643q/OP5uoIvi9fI6P6ZnVGhWWyKn2mxLmMcPgwZZok6YruxpqvlCV7XtPye30uG3rkF6yG6JLemiltbmbOvuFRQWJYTjk0fer+t9WZ37/E5QP2P1xeLmm1oue6pueoj2nMGsUeKv/MO/hxRvsPRqSXWJQOseNa6a/gGcV6jhEtv0TljqRPpSMXfVRKksl0nJtBkm2GZUrGSS/JStgTe8kt3cTAlryxJY33BhDBiishE+85U8/ec8icngrTzhQr25qFqk46bEDxyJ5M2Rdu6TbqVkgCgQFEqJCyQbo3WKMaIABAR8mGG5KuZ3WCuBPTtfQjky2awDLlsRpA3pqiWMwtnXJAVlJLP6EBKA+SZNkzcsHa0FMxIMjAO4gt3rxrpaGoVsjLvu4IWvdVL8Gw2k7C2LFSjoqrRqB90h/hWvpU1Gyl+go30H5DRQOKhXfunL03GJihlam9HuWRX4+t4iKyU5yNeCCBgDoZYKBZ+/zGjsSN3H1MhRWKRw4cTK7sQTACASE5sqqZtFr6XGAL7STUkzs9vWxZI87AkZasADVqCxlrS5dMoGr8OB1zJexNI4YpqLYcODiF3ZiUUrvewSbofS3gryjDqaIRR5A8YOJ4smRIsFFhcTvP9uk32azGEcf/vXhrAnKH28MfJeegZQ==)

### Other comments
I found this [issue](https://github.com/vuetifyjs/vuetify/issues/18862) and tried what was written [here](https://github.com/vuetifyjs/vuetify/pull/18961), but it didn't work. That's why I decided to open this issue.

**Comment by monkameddle** [comment]
I always forget it myself and it is kinda counter intuitive but you also have to set 

nowrap: true

on the headers column

**Comment by steveulfelder** [comment]
looks like it's actually `wrap: true`. is this documented anywhere?

doesn't work: `{ title: 'Product', key: 'product', maxWidth: '20px' }`
doesn't work: `{ title: 'Product', key: 'product', maxWidth: '20px', nowrap: true }`
does work: `{ title: 'Product', key: 'product', maxWidth: '20px', wrap: true }`
