### ISSUE TITLE
[Feature Request] Change Button Color in VNumberInput

### ISSUE THREAD

**Issue by joaopalopes24** [vuetifyjs/vuetify#19982]
### Problem to solve
Add an option to change button color in v-number-input component.

### Proposed solution
Add some option, as:

`<v-number-input button-color="error" />`

**Comment by J-Sek** [comment]
What does a red button mean to the end-user? I wish I could help, but I struggle to see utility of this feature. Would it be static ([example with defaults](https://play.vuetifyjs.com/#eNpdUU1PwzAM/StWLh3StnCeOiS4ceGEdqEcSueyonwpcSpQ1f+Ok36ocEniZ+fZz+9tEME3so9IXftz/AriJDrtrCcYoPFYE16mHIzQequhmGuLylQGv3NpY00gmBNw/vtxN1QGgG6o8QT5DXDFto6KXiewUN3njYr9lJMy3WOO5rqwfry8RP2B/tm4SCvI8BOZTQg8kbKemdF76xfmhXW50zneVUbs8xIenTuyBt5ASaidYgkPqazsD7Vz+ZkDVkt1Z9DPUAZNnuvQpcGgP2h7RXWuRLAaL7WKWAmQC4X8z5GQqUUpN605DI3vHEFAitMEqzke260lbEdSnXxYe7ITXLW7Z4mlnJiYQ4x7E5XKx/svdsWpgA==)) or dynamically changed?

**Comment by joaopalopes24** [comment]
I didn't know you could change VBtn inside VNumberInput like that. It solved my problem.

**Comment by KaelWD** [comment]
Dynamic props are possible too with VDefaultsProvider.
