### ISSUE TITLE
[Bug Report][3.6.9] VDateInput

### ISSUE THREAD

**Issue by Roruchi** [vuetifyjs/vuetify#19994]
### Environment
**Vuetify Version:** 3.6.9
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Windows

### Steps to reproduce
Open the datepicker and ensure that the calendar opens above the datepicker input.
Switch using arrows between May and June
See that the calendar changes in height

### Expected Behavior
Height of the calendar to stay the same regardless of the selected month

### Actual Behavior
Height of the calendar  (sometimes) changes when switching between months

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNj91qwzAMhV9F+KqFeimMjRHSwJ5hl8suvFhZPBzXxHKWUvLuk+P+3fjn6JPO0edZhLEt3r1/miKKUlSEg7eKsG4cQKXNBIFOFg+NGIyTPZqfnkp42e/93Ii6Kphg9Aa3VoXAsJadxRl+YyDTnWSLjnDkhgQyOknNHtI4HylLAJMcjhptckp3I64Fq75X+QMttgQKUu+9PKhZ/hlNPSPPr2/XAmd7dMn7XOJWxcOa/A3taHxGcPbHkUBjp6IlOOdhPEeVsNnCoYbNRWPnlLMEF63dZW3Zro8lWdyGimW3Iun4+gcd3ncN)

**Comment by EDM115** [comment]
this is normal behavior because these months doesn't have the same number of weeks
use `weeks-in-month="static"` to keep the same height
