### ISSUE TITLE
[Bug Report][3.6.8] Dialog overlay breaks css position: sticky

### ISSUE THREAD

**Issue by adam-kiss-sg** [vuetifyjs/vuetify#19991]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Firefox 126.0
**OS:** Windows 10

### Steps to reproduce
1. scroll down a bit, see the red sticky banner on top
2. click on "OPEN DIALOG"

### Expected Behavior
sticky banner should stay in place

### Actual Behavior
sticky banner disappears

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U8Fu2zAM/RXCwG51k2HYxU2DFdtxwHZfdlAkJiEqS5pEeSmC/vsoJ05iN50Phi2+98gnkr8OVYp69hTCfZexaqoFYxusYlyuHMDCULdMvkXQ3jE6BrX2HcIOlcG4mJXwgANtVUqPqyr4REze1YlJP7+sKkj8YlEi7EMD8wdYK/28jT4700BE8wB/yfCugY/z+YdV1SuCkApbsM5h7JNc0nW1CuEsu0Pa7riBT/P5POzPAoIqVSsS/unoVOmU+PnIg9kF1tWGlPVbaNW+7ssTvODO6j1quCzo6mQ9N0ozdYp9FPABQvQhNXA+/Fn+4XUk0adas7s+AZFbkzMiMuauqjFMe9unSjlulMa6U5GU4ymMcc+C+hHQwbfe1RRxIgpoI3bG0eVi1ld47Xt2NSX/uQ6DG5VtkT0ApafiBW/51yoaYOK+KUOFI9AZVhczkxDAdx+xBQopt2DKpYCMIKgW+a5MbkLNyDmCMhQoaXJbQEsSTGiEMJVDyqn1UpL4ES1ymgyZLOOfGaysQERAPmZCmZCtU6As/cnqflK0XN111bctlSZLkW9cSTwF6WvsW3D6nIrcHqCrtn+1PuE7fS/PF21l0QQ4dOi+UzYjPMJG2YRvKTcGYuT1lp0h+N4QXVDHtRtWuNBGO1xOZPfle8SvXu9ctrZ//f4HU9VyZQ==)

### Other comments
The closest I came to solving this is something like:
```
html.v-overlay-scroll-blocked .position-sticky {
  position: fixed !important;
  top: 0 !important;
}
```

But with this, the whole body jumps up a bit. I guess that's because `--v-body-scroll-y` is calculated before the css class is added, and so the sticky banner position change messes it up.

**Comment by KaelWD** [comment]
This is a firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1437761
