### ISSUE TITLE
[0.16-beta] select doesn't close when clicked outside or pressed ESC

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1999]
### Steps to reproduce
Create v-select, open it and click outside or press ESC

### Versions
0.16-dev

### What is expected ?
Select menu should close

### What is actually happening ?
Select menu doesn't close

### Reproduction Link
https://codepen.io/anon/pen/veWLzL - beta3 works fine

### Playground.vue
```vue
<template>
  <v-app id="inspire">
    <v-content>
      <v-select label="Age" required :items="['0-17', '18-29', '30-54', '54+']"></v-select>
    </v-content>
  </v-app>
</template>

<script>
export default {
}
</script>
```

**Comment by KaelWD** [comment]
I've only seen this happen when HMR refreshes part of the page. It goes away again on reload.
