### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by srinivasdamam** [vuetifyjs/vuetify#2]
I loved this a lot, I want to use this right away, Please let me know if this is ready for production apps? Is this only SSR or can also be used for client side rendering?

**Comment by johnleider** [comment]
I would say outside of personal projects, no. I am working towards a 1.0 release, but I still have more testing and features I would like added before then.

**Comment by coderabsolute** [comment]
Is this a production ready now? I know we haven't reached to 1.0 release yet, but just checking?

**Comment by coderabsolute** [comment]
Just wondering, what's the status now. Is it production ready? I know it's not released to v1.0 yet, but just wondering.

**Comment by johnleider** [comment]
I don't see why not, there are plenty of individuals using this in production already.
