### ISSUE TITLE
.91 Slider and mouse up event when mouse outside of window

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#200]
Open the docs page for sliders:

Grab any slider, move mouse to the right and let go of mouse outside of window bounds.

Move mouse back to window and the slider thumb is still tracking the mouse when the mouse is now up.

Must not be getting the mouse up event when out of windows bounds.

**Comment by johnleider** [comment]
After some testing, while this is a bug, the behavior is not critical enough to put additional time into this. You are welcome to put up a PR.
