### ISSUE TITLE
[Bug Report][3.6.9] VTreeview: Append/Prepend Slots not usable on parent nodes when activatable

### ISSUE THREAD

**Issue by ConnorNoddin** [vuetifyjs/vuetify#20009]
### Environment
**Vuetify Version:** 3.6.9
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a VTreeview node.
2. Make the VTreeview activatable
3. Add a template using the append or prepend slots
4. In the template, insert a node

The node will not be visible in parent nodes on the tree. It will be visible for child nodes.

### Expected Behavior
The nodes append and prepend to parent nodes in the tree.

### Actual Behavior
The nodes do not append or prepend to parent nodes in the tree.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVEFu6yAQvcrIm7RS7az+xkoj/RP0AE0XBIhLiwHZY9dV5Lt3oCbGqVOVBYZ5b94Mw+Dnc9Y2fPvfuaLvZFZmO5S10wzl/mAAdn2OjZS9kh9QKoLax0MWvocMGEfVM2RH/U0menSGPm+1xdI10kkjyOkM3g3GQzZxg7ji1uyhFio/2voIu+1kmuS2y2QIjdmQYYHStuWNchiYcnC2QRDyxDqNcP6WE5RrCXf38LiHu8kGoIxCxbT+fKJMS3jeuO6oFd+8PETGSWnZllHFj1esdQkbn7dmpupYJXNv+7e5OAG8kU+gGCvkW7uELIUKICcw9/sUr8W1es2ad2E/FiwnThPNZ5jTlqo4LBimShmqJqkUxwFTXFje1dJgbjvUyiyog47HCVQ5cKlnfLys/AVRFefqhW4hyyyVFJL4CjU5xKonEQH4q9KiCbeSmq8UUpUWGV6r/Kq0qpYqalvZgur4UzO2hk9+HZ+rEsdclnXGzYOdWO8fRkHTz0i3s/izvjJCDoXv4Zvya+BSPz1diqxeeFHRu6uMbRZtdolGrZnaZ7kYZLwPi9H/CC5PPxsfTKd1mF6+APHDULA=)

### Other comments
 Note, using selected instead of activatable works fine. Using neither selected nor activatable also works fine.

**Comment by jelle-eastground** [comment]
I have experienced the same problem: icons defined in the prepend slot are only visible in leaf nodes. This problem also appears in [the example in the documentation](https://vuetifyjs.com/en/components/treeview/#append-and-label). Version 3.6.7 works, 3.6.8 or newer doesn't.

**Comment by ConnorNoddin** [comment]
> I have experienced the same problem: icons defined in the prepend slot are only visible in leaf nodes. This problem also appears in [the example in the documentation](https://vuetifyjs.com/en/components/treeview/#append-and-label). Version 3.6.7 works, 3.6.8 or newer doesn't.

I'm not sure the "activatable" keyword is available in 3.6.7? It appears when using that Vuetify version that the keyword has no effect

**Comment by yuwu9145** [comment]
> I'm not sure the "activatable" keyword is available in 3.6.7? It appears when using that Vuetify version that the keyword has no effect

There was a select/activate regression in v3.6.7 #20024, it's been fixed, cy tests are also added to prevent it happens again.

Stay tuned for next release

**Comment by ConnorNoddin** [comment]
@yuwu9145 After testing the new release, v3.6.11, the example that was originally posted still does not work with the icons.

**Comment by yuwu9145** [comment]
> @yuwu9145 After testing the new release, v3.6.11, the example that was originally posted still does not work with the icons.

What I meant specifically was activate/select regression, I quoted your "activatable" keyword in my previous comment. This issue is more about slot in ItemGroup. I am doing Treeview enhancement recently, it should be fixed soon

**Comment by ConnorNoddin** [comment]
@yuwu9145 Awesome! I am most excited!

**Comment by ConnorNoddin** [comment]
@yuwu9145 While you were working on your recent merge request, did you notice that the VTreeview search functionality doesn't appear to work? Maybe I am using it wrong https://vuetifyjs.com/en/components/treeview/#search-and-filter

**Comment by yuwu9145** [comment]
Didn't notice, let's track it in <https://github.com/vuetifyjs/vuetify/issues/19404>
