### ISSUE TITLE
[Bug Report][3.6.9] VOverlay unable to locate target undefined 

### ISSUE THREAD

**Issue by xarenas107** [vuetifyjs/vuetify#20001]
### Environment
**Vuetify Version:** 3.6.9
**Last working version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. In v-overlay set prop contained

### Expected Behavior
Open overlay

### Actual Behavior
Throw error with message: Unable to locate target undefined 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkL1OxDAQhF9lcROQCOlRLhIdHSUFobCSDVjyz2q9sUCne3dsh9xPY3lHn2Zn9uOoIk/dC9FTWlE9q17QkdWCw+gB+tRqovqtwxS8aOOR/6UqCv5Iuxi0M6TWhRntYVQufo3qTFUuJGSrf0FPYpKWwBkjzehlVBAIfRt8+10o2PfMVw7Zg4a3zaPv9lBV787ml1xZuwTbG2TxtkJRtoZ9d9U8j3FiQwIRZd12GUeBBY7AuMAJFg4Omny0puBQIkeBXBsOhbhvXtHaAO+B7XzXPJQFm+WgTo9+tbY+n39ioX2d)

### Other comments
It appears to be related to: https://github.com/vuetifyjs/vuetify/pull/19947

**Comment by Mikrovolnovka** [comment]
I'll add the error text so others won't duplicate the issue:
```
Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
```

**Comment by josephlbarnett** [comment]
Seeing a similar issue in unit tests of components that include v-dialogs , where it warns `[Vue warn]: Unable to locate target undefined at <VOverlay ref=Ref< <ref *1> {...` and then unit tests that open dialogs can't find the components inside the dialog (v-dialog is attach=true in the context of unit tests to allow the tests to find components which worked in vuetify 3.6.8)

**Comment by JiriKr** [comment]
Not sure if it's related, but when I use v-dialog with `:attach="true"` and activator it raises 
> Cannot read properties of undefined (reading 'classList')

**Reproduction Link:**
https://play.vuetifyjs.com/#eNpVkMEOgjAMhl+lmVeVO0ET38GbeKhj0SVzW0YhJoR3tyuCcFnaf1///O1tUG3SxSXGY98ZVaqKzDs6JHOuPUDVHzBGKaXRwRNab9JPErGx6MITSiRC/TrVilJnarUgDM2msENNtkcKibkBYgqxhXEDi+eDPPBrfcOcUMzA1bQEVSHfa/tiFXolc15MDZAlZ3KsPC1NrYDMhxaNa7bPxnngvxsL03LzBTKxOUFWpgttQqhx7zvn5Ll/Ade5cKo=

**Comment by jflemingframe** [comment]
+1 
VMenu 'attach' prop affected by this as well. Console error shows but it does seem to still work. https://play.vuetifyjs.com/#eNq1UUtuwjAQvcrIm4KEE4l20yggVe22JyAsjGOEhbEtZ5KCoty9EyeFhH1Xmc+b94l3LauCTD+8T5pasYzlqC7eCFTbwgLkpW5AGlFVm4KhuiKXyqIKBYtrAjT8omwNAlHIEzivLHeWn1yjwggh0B8nNLwyDjMhUTcCXSDWFnxwvoLuzjnyHtCCdCaCfNAXEW4FI4aDtmUc0RXdwBcVpfuxkKfx6CGbTrLchw03usK5VD/hmtBEf4yCi75bAUmp65I+0PckB9lZ3WgfFzPHcyKOGo3atm08TGIHXddbfMZMnEy3kxgzy33b//LhfVJ6IKqeouaVDNoPF+rqXUAo1VHUBqEdWEqBIoPFEjZbWIwzGEJmsHtYaiGazODl02h5hm/1At3qP/ewniL2Y9UtY9H1Ue/hWLdir8lbsn5nK1sbs/8Fl+XdMw==


This bit here seems to be a change that brought shadowdom stuff in. Not sure what that's about, but this looks to be what started affecting this.

https://github.com/vuetifyjs/vuetify/compare/v3.6.4...v3.6.9#diff-797e0d87fcc4e46ffbe545df7707d4565185aaa039c2f04eaf74a2539b3fc5baR159

packages/vuetify/src/components/VOverlay/VOverlay.tsx:159
```
about:srcdoc:168 DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at https://cdn.jsdelivr.net/npm/vuetify@3.6.9/dist/vuetify-labs.esm.js:10619:21
    at ReactiveEffect.fn (
```

**Comment by ax-jstern** [comment]
In our app, this issue prevents menus from working for a period of time, after which they start to work again. I didn't find any particular rhyme or reason to when it would start working again, but we were seeing the same error as posted above. Not to add any pressure or anything, but just to help scope the impact: for us this will prevent any further upgrades to Vuetify until the bug is fixed.

**Comment by Tennyleaz** [comment]
I have errors in v-menu, when multiple v-menu could attach to a component.
```html
<v-menu
    :model-value="isShowSubFunctionMenu"
    :location="tbLocation"
    :disabled="isMenuDisabled"
    :close-on-click="false"
    :close-on-content-click="false"
    persistent
    no-click-animation
    max-width="46"
    offset="10"
    transition="fade-transition"
    z-index="22"
    content-class="overflow-hidden elevation-4 fixedMenu"
    contained
    attach="#mainNav"
    scroll-strategy="reposition"
  >
  <template v-slot:activator="{ props }">
    ...
  </template>
  <div>
    ...
  </div>
</v-meun>
```
The browser console show this:
```
Uncaught (in promise) DOMException: Node.appendChild: Cannot have more than one Element child of a Document
```
Which is from `teleport.ts` line 29 `targetElement.appendChild(container)`

**Comment by malopgrics** [comment]
Attach is broken with `v-dialog` too.

See [this Vuetify Snips](https://play.vuetifyjs.com/#eNrFks1qAyEUhV/l4qqFTmc/TAOFvkWnC0dvU4lV0Tu2EPLuVTM1MyHZBbIRf47nfB5837PgRfvq3HOckHWsJ/x2mhNuBgPQSxVBaB7Cy8AIf6kRaAj9wMpxEsRGKq7tdl6nnX8DiE3QljouSEVO1ieLPThvXYBDNZhNRjJJPyojk6pokgJ+rN8ps4VjBDwYC5yIi69H6Nty6RTbrsAvkkj85JOmdbLgXgIp0piS30rQCq6Kmvz+DVSGgnA6WJjO+9fZsqLWdlYkdEf7XLifcMFyy2ZHb3doarFzZA68Y7ULiluVm5fpD6fZSscOT2bSugwff/4l84E=) for reproduction

```
<v-dialog :attach="true">
  <template v-slot:activator="{ props }">
    <v-btn v-bind="props"> broken dialog (attach=true) </v-btn>
  </template>
  <template v-slot:default>
    <v-card title="Dialog">
      <v-card-text> attach=true </v-card-text>
    </v-card>
  </template>
</v-dialog>
```

**Comment by JoniLieh** [comment]
This also happens to the [Misc > Advanced Showcase](https://vuetifyjs.com/en/components/overlays/#advanced) on the Vuetify webpage ([Playground](https://play.vuetifyjs.com/#eNp9VEuP0zAQ/iuDudbJ0paCqrLSHkBcuAC37R5cZ5q469iW7WRbVf3vjJM+koLIJbbnm8c3r+cje3IuaxtkS7aKWDstIj6uDcCqUG13oGPLK9uih5YHbeOXNTuCCt/TkzLlBJy3LsBpzc74TkMKX1yuAFKLEEix3nPRRLtmN1Et9vxNFbEi8Ww+H4pavlGmoPfOw01y9dN5UnUJwUuCVTG6sMxzWZjEKartYRcyaetc1aLEkKegQr61HkPkwsds50oKe5V3VsjsyHBC84j7OPBHgmp6pZOEvFpA93eevPjDIA3994Ncm2jhW+c2jGzl1XSE/u1FixoIHSuEDeHBNrGw1gPuHeUbjUSwBqhQBiN8JRJVBk/QCimiIsHBNvCmtAaDqWTEtcT4bsCLuA6J/YOxirrvgYHEk3VTjokta1ug5q3QDVIyRqVL30bI19LbxhRcWm09YawXpsR74LU7kE//kv1Xs0ATcPzUterwqStvH/+YVXDCjEt5LmFfz9BsulSkmB4Xc/iJrcK3sMqT3rAFrxk9J26U0hSNFoeh47u83UZpzO4SmdCqNFxSD1E9d01IbX2+jhWCpPBJ4f3DbDH7+PnOmjVRKIODobyv8SYa6iOvhEkzvqVVQMR/IUJNnQvKbG2iSqg78meKt+k/J+SyPujaFaXfK3m/WFb5dd2wCdPKvIZsF6yhRXRcMxlo3JfPLyeSqdpZH3kt3ADQPybQ8XRipwmbZfNs+ongs2yRfXhgk+gbfPkDBWJy5g==))

**Comment by Mikrovolnovka** [comment]
Still happens in v3.6.10

Link: https://play.vuetifyjs.com/#eNqFVN1uqzAMfhWLXbBJzbpW59xUZTrn8jzDOk0phDZaSFBiaCfEux+TFAq007jg54v92f5s/NZEzqbLv2X5XFci2kRbFEWpOIrXnQbY1oyXpX/1H6nRyKUWFmSW7CJ3kpgehd1FFxNvVAhdAUfk6ZFsHpRJuRLsagsdgtJoOt0bRFMQZvLcCSSE/X4Z0RFhnxA88BRlzdFYMmugtKZ00E6Mffw96jECkCruHPmUZ7aG0ljMjZKGuSO3Uh/YntuPj1mWcDpKCrk3NhOW4VFq5sgpYwfLv8CaSmciY+oAGcuVOEOlKXuG4kw3y7XLjS2AK3kgP7SCOHfRNCnKU+pORF/H9HRSka9JkvKBr5MduUXSrK+rsOwXyaA3J7HfLoPxnMKVXF8dlHdompqrSrTtdtkdfxN15MQrND4QSVRbo1lmTvpuxA6kPoz7uBxN1giumZIOrz3i7OWO7E5QhIzbsfa3ne+YGPWtmEtN7SDu7gSkhu45Uxxg8ym+LjbPXpYbgz7FZooDOKFEiiLbeObgDUmSgH9bTM1pYKfAn1TJ9JN4H58geQ0+kIyofpqNoWqGEpUYN2y1nonUXU0TyIN1284IqXMzxpvODueT/gb8ugkI6FZBvz3oc1gfYbkQErbLbDa2LrWyRNIVq7B8ZNH9ttCAFfkCUlOUFekNLeTWFBDT6orDUFEEGqZeQ7J+jH0dq/jpeuz7T8c9z2NQ/i0kOrTX176B+F83Nqt46KNnJ/xCfMHby/O++/ob9wEP7u+UJf2MvnwqPGoXulLK397/AzxutN0=

**Comment by johnleider** [comment]
Because it hasn't been released yet.

**Comment by Mikrovolnovka** [comment]
Ok, I'm sorry, I didn't know the issue could be closed prior to release :)

**Comment by donalmurtagh** [comment]
> Because it hasn't been released yet.

I was initially confused by this comment, but I think @johnleider is saying "this fix hasn't been released yet" **not** "v3.6.10 hasn't been released yet.

**Comment by MajesticPotatoe** [comment]
Tickets get closed when they are completed which is usually when a commit for that fixed the issue has been merged into `master`/`dev`. It becomes publicly available in the next patch/release.

e.g. The fix was committed to master ~20hrs ago, and will be available in the next patch(v3.6.11). v3.6.10 was released last week v3.6.11 has not been released yet thus the fix has not been released yet.

**Comment by jflemingframe** [comment]
> > Because it hasn't been released yet.
> 
> I was initially confused by this comment, but I think @johnleider is saying "this fix hasn't been released yet" **not** "v3.6.10 hasn't been released yet.

If you click on the commit that completed this fix, you'll see that its only in the `master` branch. When it's released you'll see other branches and version tag in that list.

**Comment by batyki** [comment]
sorry, but I don't think it's quite right in 3.6.10-master.2024-06-27

'a' || 'b' || (true) ? true : false = true  but should be 'a'
so <v-overlay attach='#container' is ignored. I think parentheses should be used

VOverlay: useTeleport(computed(() => props.attach || props.contained || ( potentialShadowDomRoot.value instanceof ShadowRoot ? potentialShadowDomRoot.value ?? true : false ) ))

**Comment by johnleider** [comment]
> sorry, but I don't think it's quite right in 3.6.10-master.2024-06-27
> 
> 'a' || 'b' || (true) ? true : false = true but should be 'a' so <v-overlay attach='#container' is ignored. I think parentheses should be used
> 
> VOverlay: useTeleport(computed(() => props.attach || props.contained || ( potentialShadowDomRoot.value instanceof ShadowRoot ? potentialShadowDomRoot.value ?? true : false ) ))

attachand contained are booleans though. 

https://github.com/vuetifyjs/vuetify/commit/27b4b1e52060b6bee13a290a4829f935f1bd9c05#diff-797e0d87fcc4e46ffbe545df7707d4565185aaa039c2f04eaf74a2539b3fc5baR159

Whether it's attach, contained, or potentialShadowDomRoot, the condition, if true, will attempt to use the value of the shadowDom OR default to true if it's not available.

**Comment by batyki** [comment]
> attachand contained are booleans though.
> 
> [27b4b1e#diff-797e0d87fcc4e46ffbe545df7707d4565185aaa039c2f04eaf74a2539b3fc5baR159](https://github.com/vuetifyjs/vuetify/commit/27b4b1e52060b6bee13a290a4829f935f1bd9c05#diff-797e0d87fcc4e46ffbe545df7707d4565185aaa039c2f04eaf74a2539b3fc5baR159)
> 
> Whether it's attach, contained, or potentialShadowDomRoot, the condition, if true, will attempt to use the value of the shadowDom OR default to true if it's not available.

sorry everything is fine! I was unable to reproduce my problem on the playground. the error is on my side

**Comment by KaelWD** [comment]
> Whether it's attach, contained, or potentialShadowDomRoot, the condition, if true, will attempt to use the value of the shadowDom OR default to true if it's not available.

It uses potentialShadowDomRoot even if it isn't ShadowRoot
