### ISSUE TITLE
Tooltip with :value="true" is not initially visible

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2000]
### Steps to reproduce
Open the codepen

### Versions
0.16 beta

### What is expected ?
Tooltip should be initially visible

### What is actually happening ?
Tooltip is hidden. It shows when you click "toggle tooltip" button twice

### Reproduction Link
https://codepen.io/anon/pen/VMrKwR

### Workaround
https://codepen.io/anon/pen/XezNdL

**Comment by nekosaur** [comment]
Looks to be fixed in current version. Codepen works.
