### ISSUE TITLE
[Bug Report][3.6.9] v-stepper-vertical: Data Loss on Step Change 

### ISSUE THREAD

**Issue by vciloglu** [vuetifyjs/vuetify#20025]
### Environment
**Vuetify Version:** 3.6.9
**Vue Version:** 3.4.29
**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
In the v-stepper-vertical component, data filled and displayed via a button within a v-stepper-vertical-item is lost when navigating away to a different step and then returning. This issue negatively impacts user experience by causing loss of form data. Resolving this problem would ensure a more consistent and reliable user experience.

### Expected Behavior
The data entered and displayed within a v-stepper-vertical-item should persist when navigating between different steps. Users should be able to move back and forth between steps without losing any previously entered data, ensuring a seamless and uninterrupted workflow.

### Actual Behavior
Currently, data entered and displayed within a v-stepper-vertical-item is lost when navigating away to a different step and then returning. This causes users to lose their input and disrupts the workflow, requiring them to re-enter data.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVttOGzEQ/ZUhL4C0SVToBUUhKqXtEw9VK/WF8ODsTmBUr73Ys1uqKP/e8V6CE5aiXlUpym7m5jPnjO1crgbepeOzohhVJQ4mgyljXmjFOJsbgGk19IxFgW5YoWNKla7t4uniQEK05UmGS1VqPp0PVhByYD0ftLG9dYYkFTo/wCS1Ug8ZpUCdPoNn88G935cLJtbB/QGdt0ZpyJAVaR+HdTGfQglrMPZVSpfBF9XdAATAOxUA3BsedGjwrmkvvGy117a4YAOp1dZJVOEoV+7bfACvU03pFzGFNEmajuvIKHk6jkj/AYDCYSXpWwo1+Y/QG5X7JQWOHlHg3BpWKcPbJwTgr7ZPgKhszEJG1Taj56Vnm58LLFHSMIy3OGvC/3e9agDh5TEAlXKkTAAquWRiACHtaQB/cga2NV6SyxWTFVCPCXzjsHePHcfGpqFOD2vOw8/3ZMjf9E7ChXWYAxW+zCEL+oAnBpUji1zGY8rIpQOVUUGeUjLXgJp4BDIquc0ouS/lavwoR8WCmDzclvKFnkGrhawCldVlwRK0KP0evFO3JUJaFpSRGBFyAZmrqJ5iEN5TlCdbVnkCubo21MDEPKRXaEjlMnThR2Gds6BpgfJw6KSj0mTRKdMBwHzvbwwzN2kd2f98uIe0lKC9Zb0+ZoLgZ+b9YcXYIuQNUfuIzHo+m44/okdpcCd+d+1t9wZIBxdOYanCCluBv78he1L6wsWxo8bUp44KrjNIjkXHsHtILp3NYX803rGH630/pOFdndZe17Bq0GSK1QQODuF0BgetDaDjYdLQ0O6D9aG8NK+yJW9s5iddGZA7N9rdUm/jEGVuyI8iatmVol20t7T0fbDfpGK2f9i51t3C7TNcVHVT8cI7/W6lrAORG+oGSf2fp4egh/9/7u+k6ec3MtCbEVFZduackj02O8uy6Th4u0iZ49lqpYL7gjyv19NxMDUyNxX7dQWZ2bKI1V3JobGEdatqp2E4BeVA7BYQLiXq4PJKGIvcLULxNrq2VG3SRvVhLe7LZwkcJXCcwPMXCcjnZQKv5HOSwMlVD3/rxJRa119X3wG3nzYZ)

**Comment by KaelWD** [comment]
You can set `eager` on each item, it should be inherited from the parent though.
