### ISSUE TITLE
[Bug Report][3.6.9] Maximum recursive updates exceeded with v-for on snackbars

### ISSUE THREAD

**Issue by sev-b** [vuetifyjs/vuetify#20026]
### Environment
**Vuetify Version:** 3.6.9
**Last working version:** 2.7.2
**Vue Version:** 3.4.29
**Browsers:** Chrome 126.0.0.0, Other
**OS:** Windows 10

### Steps to reproduce
To reproduce this just create an Array to store the Objects with data needed to populate a simple snackbar and then use v-for to display v-snackbar elements with the data found in said array

### Expected Behavior
I would expect the snackbars to be shown/hidden as intended. 

This used to work just fine in Vue/Vuetify 2 (of couse a little different with the refs)

### Actual Behavior
No snackbars are displayed or sometimes only the first one but without a functional button or timeout.
You get the error message: `Maximum recursive updates exceeded in component < >. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU02PmzAQ/SsjLoE2IWmrriq0WbW976XXzR4cM2itGBvZA8oqyn/vGIcE90OttBwAv/c8fsw8nk6Zd3L9revKocesyu4J204LwoedAbgfVqLrxtdxIa0hoQy6CzSC3gh52As3QQDDqrFuu8tyRpegTI3Hgh8wKf0uu4kdNiydqB/YJGx1wFemmSkJjwTv4VHQS+mEqW2bF3PpsGptjfqiHpRXe41JLVIt2p6menGVKKTVo/PAj+/pfnYwM5Nwnl41MlkrT8JI/G6J2GH8+Jvy2jhu3dRqdu61pUpIUtb4mWTs757MHPmXy3B9lVrJQ9oJ2EIjtE86Ei7FQ2VlW6uV1PZXfj03vE7CEaHb/KeYMJTmJCAxRkkFXnrpVEfgkfqYMtV21hGcwJpH2xvCehkCAmdonG1hwSFdhJ0AfITnnVOi+OtYlz89F7+TIVNzPiiu9fO8gO0DnKL5a71yELrHsuv9S37hOGGxkxWQ63E5oeMEKlj4Xkr0fnElQkYYJ2QvHz5+mhExeRXcbTabC3oejb/NATpn3d/O/08H4R6eTW/GOMIfAz31y/HknOEzbMcn8d8ZeXgHd5959aXg26I78sy4cph/nDjPOjsvTa/1eHv+CcytYVo=)

### Other comments
I skimmed through some of the issues involving the `Maximum recursive updates exceeded` on here but wasn't able to find one involving snackbars and/or a fix for this specific case.

This also doesn't work in an Electron 29 environment where I usually work

**Comment by KaelWD** [comment]
This is because of the random key.

**Comment by sev-b** [comment]
> This is because of the random key.

🤦‍♂️🤦‍♂️🤦‍♂️ ofc it's the one part I never questioned
