### ISSUE TITLE
[Bug Report][3.6.9] VFileInput do not work well with Firefox (Android)

### ISSUE THREAD

**Issue by BlackYuzia** [vuetifyjs/vuetify#20022]
### Environment
**Vuetify Version:** 3.6.9
**Vue Version:** 3.4.29
**Browsers:** Mozilla Firefox
**OS:** Android

### Steps to reproduce
1. Open website (URL) via Firefox (Android)
2. Try to upload files.
3. Select file(s) and press "allow" (or upload)
4. Nothing happen

### Expected Behavior
While you select files and upload/allow them, files upload to input

### Actual Behavior
Happen nothing, files won't upload to input (or something like that)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUktqwzAQvcrgLuKCE9MugxMohUKhtNBFKdRdKMrYcZEtIcnOwnjTs/QcOUN6o47sJrHlhTUz781PTx9tYDSP75RaNDUGyyCxWCrBLK7TCiBp5kyp3uwdLivLigr1f4iCb69yf/acfy8FLLkUZpUGN7dpMAId/FAIfKxUbcdhAME2KCjj+HM8/H4fD2kwxblAptlG4DTMOEdlKa8oWY6xqvIIBvNL4dnOi+xk7nGj/Nq0L8edFFvUVMmgQG59TjMv5bafsDT5FJwsSCuebhCuhlKFrCithYw2f2YlGui8W3FfOyF0IDU8vbx7peOJOpfw5VbHUsROC1+bdd/GLF1DWsW18ojkXjRNYl91FxkexWQccg3XhbJg0NbDmylKJbWFFvbM8h10kGlZwoxe2mwCa8w80MHU1th+xpVjhNcu2FcKh9nCa1itHSEa++1pD5cvBS6EzMMZsWaR4y4aJmrsawEJQQfZSTzMTlMHXVTVQvS/zz9mm+3s)

### Other comments
In Google Chrome (Android) all works fine. Maybe this is Firefox  super “access checks” issue?
Oh and also same issue while you open website in "Telegram Web Viewer" (like you open it as **web app** or something like that?)

Firefox when you select files:
![image](https://github.com/vuetifyjs/vuetify/assets/25010528/5a8e1dfe-89ba-47d0-a1f8-d468775624a2)
Chrome when you select files:
![image](https://github.com/vuetifyjs/vuetify/assets/25010528/86d0bffe-9ac3-4490-8136-5659893b4b12)

**Comment by KaelWD** [comment]
Works for me with firefox 128.0b3

**Comment by BlackYuzia** [comment]
> Works for me with firefox 128.0b3

I have 127.0 firefox (andorid)

**Comment by KaelWD** [comment]
Same with 127.0 (#2016024687)

Yes, android 13

**Comment by BlackYuzia** [comment]
> Same with 127.0 (#2016024687)

idk how it possible.
Tested with 4 users.

2 has this bug (include me)
2 don't have this bug
Total 5 users (with you), 3 don't have issue and 2 have this issue.
How it possible? FIREFOOOOOOX!

My video:
https://github.com/vuetifyjs/vuetify/assets/25010528/16dbfacf-606b-4f8b-bab3-4dd9d10ff7b4

**Comment by KaelWD** [comment]
Does the demo on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file work?

**Comment by BlackYuzia** [comment]
> Does the last demo on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file work?

lol, nope, same issue.
So, this isn't a issue of vuetify, okey.
