### ISSUE TITLE
theme definitions using teal color for active select control instead of accent or secondary

### ISSUE THREAD

**Issue by mr-july** [vuetifyjs/vuetify#2003]
### Steps to reproduce
make theme changes as explained on https://vuetifyjs.com/style/theme
place some checkbox on the page
activate the checkbox
the ckeckbox color is teal

### Versions

Vuetify v0.15.7

### What is expected ?

the activated checkbox color should reflect the configured theme, e.g. "accent" or "secondary" color should be used instead of teal

**Comment by jacekkarczmarczyk** [comment]
Can you reproduce it with 0.16@beta? If yes - can you provide a repo that we could download, install and check?

**Comment by mr-july** [comment]
here is the [PR](https://github.com/mr-july/vuetify/pull/1)

**Comment by mr-july** [comment]
there is one more place in the same file, where "$teal" is used, but I don't know which color could be used instead. :-(

**Comment by johnleider** [comment]
The teal colors are part of the base md-spec for selection-controls.

**Comment by mr-july** [comment]
@johnleider According to the [specification](https://material.io/guidelines/components/selection-controls.html):
> Selection controls use an app’s accent color.

**Comment by johnleider** [comment]
@mr-july when you're right, you are right. I misunderstood the usage of the teal color. Thank you for clarifying it.
