### ISSUE TITLE
[Bug Report][3.6.10] VDataTable group is not sorted when key is not in header

### ISSUE THREAD

**Issue by SystemKeeper** [vuetifyjs/vuetify#20045]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In the example `groupBy` is set to the key `group` with a sort order of `desc`, but the `group` is _not_ included in the headers

### Expected Behavior
The grouped values are correctly sorted descending

### Actual Behavior
Sorting is not applied. It does work however, if the column `group` is also included in the headers.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9lt9P2zAQx/+VUyQESP2Rpk2gUTeJwcYYe9jrRHlwk6NEuHHkON06xP8+u02CXWx1eWB9aC7fO8f38Z2d3D17JU+GF0UxWFfoxd5M4KqgRODHeQ4wW/dTIkhfkAVFiJecVUV/sfkw97bmp83cg/gRSYq8lGJtKTGTz1FSimWJXChNSf01oRVKPScrnHu7SYb6LFKaDbUk5G2Z8KwQ0h4O4SJNYe49g8gExRiOr1Uexz14wo2822Z1DC89OZ1gUOejzJJxAQnjHBNBN/McfxdKSfGBVFTAs0pEJXFyurMBOIqK580dQE0cw12jwKtT/fQUerqDcZmFdMm1SHSPTLO271urTtmcpaW92q0mnIx8fwnSXGf58rTFV4u6pbcMvSSU8QzLNjhpBMeAL0TOoz38gQj3s/miNIITpbjCf3AmMMuNAcVOcw254UzGH73GZ1LQg19XsOk4d6HUMilAzv5gDj/ZsuLCrFizNjGMwqnhkasQQzTw98IlbQzBxFBrpBgme+Eqdzn/6MicdEkrgdLxQGiJpkf1lMzF2jt2uJsEIeFIVlCSPP2VJY8uwmB89pZwaifcC9UIx/+d8HNCScadVFHwlmrkKpyZfYu1H15jnTmwBK+sVHomh6guqyIhT+jCGvvhW6zxwCxLTRV1K9b5O1Jdy2MK+UL2Y+okC6N/L9jE3JQt2nhgOpo+jN6R7RtSuoEFktyJdmYpmm8nmzrOkP3wmszvusO6kH1nlGYF23ubaVxTyx7zB6bYcJ07uGxUQVcqvaEPUX1lOW4Stlq4sCa+mWu9x6xY5449Fg3Mktdgk7BjI3YBu2J55XyPTUJLrYLQ3oShfg4bJ4d1ewWuermo9B4/RHWbiVv55eHACkeWWgWOUyMya9JimTWsoboeGXam5rPkRV2ULI3ZsP2g9V56eUXp9u/+L75E840=)

**Comment by SystemKeeper** [comment]
Workaround to allow sorting, but hide the column:

```
{ title: "ABC", key: "abc", align: ' d-none' },
```

Far from ideal, but works.

**Comment by chudson-incomm** [comment]
I am experiencing this issue, and appears to have been introduced in 3.6+.

Issue goes away if you back vuetify down to 3.5.18

**Comment by chudson-incomm** [comment]
Curious if there is relation to issue 
https://github.com/vuetifyjs/vuetify/issues/20046

**Comment by chudson-incomm** [comment]
@johnleider @MajesticPotatoe thoughts?
