### ISSUE TITLE
[Documentation] code example of v-data-table prop filterable is not showcasing filterable

### ISSUE THREAD

**Issue by YannikWeissenfels** [vuetifyjs/vuetify#20052]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.30
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
https://vuetifyjs.com/en/components/data-tables/data-and-display/#filterable
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-data-table/prop-filterable.vue

### Expected Behavior
Expected the v-data-table to be "Nutrition"

### Actual Behavior
The v-data-table is "Find a Graphics Card"

### Reproduction Link
[https://vuetifyjs.com/en/components/data-tables/data-and-display/#filterable](https://vuetifyjs.com/en/components/data-tables/data-and-display/#filterable)

### Other comments
The actual example doesnt showcase the prop filterable.

**Comment by c4mbr0nn3** [comment]
I think there is no filterable props in v-data-table. I cannot find it in API docs or in code.

**Comment by lmunch** [comment]
There is some mention about "filterable" props in docs (packages/docs/src/pages/en/components/data-tables/data-and-display.md) but it indeed seems like its not implemented. I would was just needing such a feature. Perhaps there is a work-around with a custom filter?

**Comment by MajesticPotatoe** [comment]
the proper prop is called `search`

**Comment by lmunch** [comment]
There is no mention of search prop here:
https://vuetifyjs.com/en/api/v-data-table/#props-headers

Tried the following to no avail:
headers: [
        { title: 'Type', key: 'icon', align: 'start', search: false},
        { title: 'Name', key: 'name', align: 'start', search: true },
        { title: 'Owner', key: 'owner', align: 'start', search: false },
        { title: 'Group', key: 'group', align: 'start', search: false },
        { title: 'Time', key: 'mtime', align: 'start', search: false }
      ],

**Comment by MajesticPotatoe** [comment]
> There is no mention of search prop here: https://vuetifyjs.com/en/api/v-data-table/#props-headers
> 
Thats because its not a part of the header props, its a `data-table` prop (and is shown in the "filterable" example
<https://vuetifyjs.com/en/api/v-data-table/#props-search>

**Comment by c4mbr0nn3** [comment]
I achieved similar behavior using the [filter-keys](https://vuetifyjs.com/en/api/v-data-table/#props-filter-keys) prop for v-data-table. You need to populate it with keys you want to be filterable. You can use `filterable` field in headers objects and then create a computed to create the `filter-key` array.

**Comment by lmunch** [comment]
@c4mbr0nn3, I am not sure I follow. Do you mind showing an example?

I am currently using a custom filter where columns.name is the only column I want to filter on, but this get called for all cells which is not very nice:

```   
    filterOnlyName(value: string, query: string, item: any) {
      return value != undefined &&
        query != null &&
        value === item.columns.name &&
        value.indexOf(query) !== -1
    },
```

**Comment by MajesticPotatoe** [comment]
`:filter-keys="['name']"` will only filter on the name prop in the item
[example](https://play.vuetifyjs.com/#eNqtVm1vGjkQ/isWOh13UpclCeXKHtfTqdJV/dJKTVVFCpHqeIfFjde2bC8KjfjvHXtZbDaBqlH5AOt5sZ955hkv1w8Da1j+n9ajdQODYjB3UGtBHbxeSELm64xRU5IlWoJhb8ocdwIIE9TafxaDMlsKuCdU8EpmDKQDQzRk54vBLi0kcqYk8V+YUZc8W/MSVMalblzGVK2VxExMmedt7Gvyu7y1+m/yP5cloeStoXrFme22fINAFjI5wGrKwIT83eOB28G9y5YcBGa1RkLWWa1KEIjIAjVstRhEXwnScrdBn0dHGWKLTkFvQ9rlozRtQIMssTAJJhSyq7emleTLTRq7poZT6fzxSigEJwSUaYCnPq5WyFhWgqNc7FkgxHJZCcgEl9AZAwex3q55aIzd25OD1JTcN6OlrnuOTupo5uit2G+/Y61oOXuCvIKjkLwywm9ixwpRHNkdbLz3eihpDcObLiCqpdMhHmWFcsUKKGIaWafY3T4K4xDsXoWhXmQeJXTp4+Y5euOWeaLto+d4vCOOnQLc8IH4JdkmMo5D0Z1ab7zOCQhYU8dDs/3aqEaW0DEfZ6CuUgsyggOIKV9Wzmlb5DkrpZ9Fh0L5akcovLxUzOYBks2r3QjklW5s/ttDhLv9ksomiAV4tfLSmk76LqbWYFJTO3N1lda5E8tzCDTIhKxOMNgGpAiKoKhsTUXjqU+2OQTPcE4MBihDZYXDQM0dSN+BNOjk5PqB+ebPsDUV4tBjUGZKik20BWZaIM9hIgj2KBFH1NvTDFtx3RNNx0I8g/xLhpUBkENSkKGBcthveuFPeJTzTpLwHNI+NI6o5c7wSDQp0EZrMIxa6Ecd53Z3Zz6SnS/vQHdHp7aTZbyQ2tdUVGqvM3PLDNftuwvutTIOpbGkjXDkod3Ob/XHn93KC8A1RsY1FhSuNiRn+CIaw7VWkOu0mCTHf/zNhlnv4bYR+O76dEUuxq/G6SZhIz+7GHY20rLqO7XhDJ3T2Ww0m/V8rSQL8rJnD70riDMNHHi2B6unsb6lgt5vyMcfYD0/gfWvU1gnT2NdUmF/HuwHg5ct+XhFpq/GY3L16Rjai1PMTk6gvfiFzH5G6eEfpJbZ2VFmJyewnk2eQe2zwL5RtlY2SPZsOh2TywZn/Rjklycgn/9yMdzsn7ftQ+vExTzfz/pg+0I2QoSvm+9AkAm6)

If you have specific questions about how to use Vuetify please check out the following resources:
- [Discord community](https://community.vuetifyjs.com)
- (Github Discussions)[https://github.com/vuetifyjs/vuetify/discussions]

**Comment by lmunch** [comment]
@MajesticPotatoe, thanks a lot.
