### ISSUE TITLE
[Bug Report][3.6.10] The update:activated event of the VTreeview component did not take effect

### ISSUE THREAD

**Issue by MapleWithoutWords** [vuetifyjs/vuetify#20059]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.21
**Browsers:** Chrome 126.0.0.0
**OS:** Windows

### Steps to reproduce
I can't get the current active node information,

### Expected Behavior
Console has output

### Actual Behavior
No output

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU01r4zAQ/SvClzaQD9ubUMebli3sYQsLe9iFpTQ5qPIkEZVlI8suIfi/d2RHTmzHheogNHrz8eZp9HJ0MsVmj2k6LXJwQmelIU4F1fCwloSsIl5UBzwWE60ACg7v9QUhTNAsu18721yI/zzS+7VjoZBjHoNFkFKlY5D6H0b/pJpOK+jsasyJ5loAuksaQwcqqMgNxKMzQJnmBeZ6FdC6gkmmFZLfHUyAxOKAm9TnyB9McPYWnhJAhH6mrccqOvpFpYhAWXfb+uzcey3LrNZlNbtQC82MKZ5qIqjcmbzYJMlA5+kpD4/TRGlyJAq2YwU1Y1KSrUpicoP635gsxrOgivSVu7cxt8dLhbLwxZrNvVlWzRBPT5LtyW++22vyDBQbHLc9sRQWekKJjbfbwxNVyRISrwOwPRcRxhqsoWFXi841Wn91j8sQJy9w54G3XLpeMA/uFr7nB4ORA2yvs5Y4vQNuZuSa2r479xeB6/nuXeBi7W5IeXmx6cjUytTtwrqWTdDgO/6RQK6I9oUHdD95wJ4UHeKBu1z4y2D+DZVoETeHTW2Vo+92ire5xHFNJOn/sFszuCGVh1HTKktklgiYimRXoaNTPvPN6o91+mT6IIBkLEkhekDImIg45biib7bNBwTRWzk=)

**Comment by KaelWD** [comment]
You've used click not update.

**Comment by MapleWithoutWords** [comment]
> You've used click not update.

How do I set it?
