### ISSUE TITLE
[Bug Report][3.6.10] The VTreeview component setting select-strategy='independent' is invalid

### ISSUE THREAD

**Issue by MapleWithoutWords** [vuetifyjs/vuetify#20067]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.21
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Set the VTreeview component properties:

```  javascript
:selectable='true'
select-strategy='independent'
open-strategy='multiple'
```

2. Bind event `@click:select='multipleSelectHanlder'`

```  javascript
function multipleSelectHanlder(items:any){
console.log(items)
}
```

### Expected Behavior
Multiple selection is possible, and the console prints multiple elements in an array

### Actual Behavior
Multiple selections are not possible, and the array printed by the console contains only one element

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVV1r2zAU/SvCL20hH7aXUMdLywp9WGGwhw7GSPKgyjeJNlk2suwRQv77ruzYke2k62AwmB+MpHN0z/3y9WLvZIqNH9J0VOTghM5cQ5wKquF+KQmZR7woF7gshloBFBx+VgeEMEGz7G7prHMhvvJIb5dODYUc7RgsgpQqHYPUX/D2I9V0VEInqtkONdcCkC5pDB2ooCI3EI8s85RpXsAo20mGUAYCmIbosRGz7JdU1H0R0DqCYaYVBrrZGeMSHQV8SW2pKNC5ksPk5TuaR5ZWueVdWMkawz2sgn6rkOCJTYpzoXmKjjaMD3kaIVoFjIuolAJ4KEOIPlIpIlAWnwnOfhxdsyw+lwcdel3a8am2VdnHVd3nY6sbcJsxxVNNBJUb4wYmGQPVeXq0w+M0UZrsiYL1QEGVZXIga5XE5Ar768pYMcyCqmOKWkW7qy9dL1Y3J2a/h07Evd0rWbiot825eeq+CnH1JNmWfOKbrSbfgGIqBm0mSqHQEzabYbs9PFFlAkPidQC25SLCuwZr3Kifljvn3HrWPV8u+eQF7iTwZjPXCybB7dT3/ODizQvenvda4nd8gWY+vkbbdyf+NHA9370NXNTuXjnYB6tOmlqWulHU1ENz6a119P+LQs7+YSFR+y8V0rL0hkJ+lkDOJO0PCui+UsBeKjqOY9xTfxZM3mEmWh1oFqtqd7h5Xw+udS5x7iSS9GfwtZlAIZW7myZUlsgsETASyaZEB2dm3nHOoV5H4ezkLs1kr6tYJufjamQfx7feCSAZw79OdI+Q2SLiHAZllsxr9Qu7ckEG)

**Comment by yuwu9145** [comment]
`click:select` is supposed to emit selected item.

You might want to use `update:selected` instead to be able to work with select-strategy.

Also please be aware there is a select-strategy regression #20024. Its fix will be available in next release

**Comment by MapleWithoutWords** [comment]
> `click:select` is supposed to emit selected item.
> 
> You might want to use `update:selected` instead to be able to work with select-strategy.
> 
> Also please be aware there is a select-strategy regression #20024. Its fix will be available in next release

ok, thanks
