### ISSUE TITLE
esc not closing selection items as expected when pressing the arrow to open a select component

### ISSUE THREAD

**Issue by dewdad** [vuetifyjs/vuetify#2007]
## Recreate:
1. navigate to the docs here [https://vuetifyjs.com/components/selects](https://vuetifyjs.com/components/selects)
2. mouse click on the arrow of any select with multiple e.g "example-6"
3. press ESC key on the keyboard

## Expected Behavior:
Selection items should be closed when hitting ESC key.

## Note:
The ESC key does close the selection items after the input area is clicked. So different behaviors to achieve the same state the diverge in behavior depending on the source behavior.

**Comment by jacekkarczmarczyk** [comment]
ESC doesn't work only after clicking the chip, if I click in other places (input field, list item, etc) it works. is it what you are experiencing?

**Comment by KaelWD** [comment]
This is the same as #1817, it works in 0.16.

**Comment by dewdad** [comment]
I meant that after clicking on the dropdown arrow on the right of the input field, ESC does not close the selection list. I would add that clicking on the input arrow a 2nd time also does not close the selection

**Comment by KaelWD** [comment]
The first one has been fixed in 0.16, the second one is #1837
