### ISSUE TITLE
[Bug Report][3.6.10] v-menu attach

### ISSUE THREAD

**Issue by chunlampang** [vuetifyjs/vuetify#20086]
### Environment
**Vuetify Version:** 3.6.10
**Last working version:** 3.6.8
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Windows

### Steps to reproduce
Just input v-menu attach as document said

### Expected Behavior
No error

### Actual Behavior
Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUctOxDAM/BXTS0Gi25W4rborceMPOFAOIXUhIi8lbjlU/XecZKHdSxTPTOzx5G2pYpDts/eHecLqVHWExmtBeOktQDc3wvt8zYV0loSyGEBqEeO5rxLSV1dF1nyQ/S8zoFhzMYNqRqUJQ9deoRuRQTttAICQpGZBLvAMLwKmKXv+JLWL2DibPTHdSK3kN6tHoSPeigWRkF/MHYrdjduZKAuKMMCPGiipn45HXm1ZTPxc12Q7sXvbDCXf2/YMbOvnF3+BlTgZKXl27S5nLqMMyhNEpKnErYx3gWCBgCOsMAZnoOYvqpMcgPtGAjYG56S4r19QawevLujhrn5IA0pLblatj3bSOh/vv7semfQ=)

**Comment by donalmurtagh** [comment]
The same issue occurs in the latest release (v3.6.11) if you try to set the `attach` prop of a dialog
Here's a [demo that reproduces the bug](https://play.vuetifyjs.com/#eNpVkLGuwjAMRX/FyhveAgQGFlSQkBhgZqQMJo1opDSJUreAEP+OSWlFlyg+9tX19ekp6qjkNoRZ22ixEhnpKlgkvckdQNZOMYT0TYXyjtA4Hb8owcKg9Ve4mYLKdS6W83kuYIVEqD41xUbnYhCwpLeAP1RkWiQfee4JIfpQw2s0nBwu5EB5m8ZCNBXGB1swN65IiHUMSN+Jy2Ppb7BLSzGUv85ylO4Ly8VmbyZw+K8AoQuTSYZDRNlnZDTAwrSgLNY1O3bdKWG8auL1M8nd/mqsHp/tQ7qrjvYRr4lrrE3P+Q1b+X9r)

- If the default value of `false` is used for attach, it works as expected
- If a value of `true` is used for attach to disable teleporting, an error occurs
- If we try to attach to a specific element e.g. `attach=".dialog-target", the same error occurs

The error that appears within the play demo is 
> Cannot read properties of undefined (reading 'classList')

But if we look at the console error, it seems that an attempt is being made to append the dialog to the document itself
> DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
