### ISSUE TITLE
vMenu in vDialog displays behind vDialog

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#2009]
### Steps to reproduce
Visit:
https://codepen.io/webifi/pen/jGaKjo

1. Click "Open Dialog 3"
2. Click menu button in dialog 3.
3. Notice menu displays behind dialog 3.

NOTE:  PR #1932 would fix this issue

### Versions

vuetify 0.16.1

### What is expected ?

I would expect menu to display above dialog

### What is actually happening ?

Menu displays behind dialog

### Reproduction Link

https://codepen.io/webifi/pen/jGaKjo

**Comment by valpet** [comment]
I have the same problem
