### ISSUE TITLE
[Bug Report][3.6.11] VExpansionPanels value prop not working

### ISSUE THREAD

**Issue by Icebreaker83** [vuetifyjs/vuetify#20109]
### Environment
**Vuetify Version:** 3.6.11
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add value prop to v-expansion-panels or v-expansion-panel
2. Give the value prop an array of indexes of panels that need to be opened by default

### Expected Behavior
Panels with indexes that are in value prop should be opened by default

### Actual Behavior
Panels are not open by default.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUcEKwjAM/ZVQDyqo8+BJpiB+gkfnocyIha4tbTaEsX8365xsMMFL2+S9viQv11oEnycn5zZViWIvUsLCaUl4zAxAWq2lc/EZg9waksqg/6RiEl9OmqCsWfONOsC+krrEQyau21smvtQp8gBkuK8NM1KkuxYG8HN3vNgCIYJpwuHodzJqfUoUXzSheeah0NB/gmnye4YJLPTeMTQ2r8103o7qcBhyrxxBQCo761XhrCeoweMDGnh4W8Cc1zVv6QCsGwhi4TscWtKCjV+2wp0Ui4hmZUqt43F7Azg9myQ=)

### Other comments
I've tried with `:value="[0]"` , `:value="0"`, on v-expansion-panels and on v-expansion-panel.
Currently only way of getting the expansion panel open by default is through v-model.

**Comment by KaelWD** [comment]
v-model is `model-value` not `value`

**Comment by Icebreaker83** [comment]
@KaelWD I think you misunderstood. This ticket is not about v-model, its about [value](https://vuetifyjs.com/en/api/v-expansion-panels/#props-value) prop

**Comment by nguyentranchung** [comment]
@Icebreaker83

Panels are not open by default, because you don't set a value for `v-expansion-panel`

```vue
<template>
  <v-app>
    <v-container>
      <v-expansion-panels :model-value="[0]">
        <v-expansion-panel :value="0"> <-- this is point
          <template #title>
            <h4>Some title</h4>
          </template>
          <template #text>
            <h4>Content</h4>
          </template>
        </v-expansion-panel>
      </v-expansion-panels>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const expand = ref([0])
</script>
```

https://play.vuetifyjs.com/#eNqNUcuOwjAM/BUre2BX2m457KkqSKv9BI6UQ1SMiJSXErdCQvw7bkqBiB64JLFnPLHH27OIoS3/vP/pOxSVqAmN15Jw3ViAui+k9+mZgtZZkspiuKVSEk9e2qicLfhGHaEybo+66KXucNWI7XLXiHvBXAlUE3eZMZk7tQMfpEiPXT3Bx9/1xhmEBNYlh1l1mU0zJ4onmtH85znR0nuCdfky0MOeVyxOdjKU+zlkRruzfziMbVCeICJ14zaU8S4QnCHgAS5wCM7Agje4GOgArBsJ0sd7WA2kT97C1yA8SrGIuHzbTut07K6HX6FC

**Comment by Icebreaker83** [comment]
@nguyentranchung Makes sense. Thanks!

**Comment by nguyentranchung** [comment]
This issue can be closed

**Comment by KaelWD** [comment]
The default value is the index, the problem here was just using value instead of model-value.
