### ISSUE TITLE
[Bug Report][3.6.8] Treeview wouldn't rendered if I add active-color property

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20102]
### Environment
**Vuetify Version:** 3.6.8
**Vue Version:** 3.4.27
**Browsers:** Edge 126.0.0.0
**OS:** Windows

### Steps to reproduce
Simply open the link

### Expected Behavior
Tree will be rendered and the active treenode will be displayed green

### Actual Behavior
The browser freeze anthing will be rendered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVcuO0zAU/RWrm4DUUFLmwUSdSgU2bGCDYDHtwrFvqSXHNraTMqr679hJ0zht+gCmiyaO7znX99yHnzYDo8loptSbsoBBOphYyBXHFqZzgdCkjK0GKBms/RKhlLl98zgfVM/5oP7qF7HSUpl6jYllJcREcqmd7U9HIRpbAxyIxRkHv55ORq0L53IyCvy7pSGaKetAtlDViViupLZogzQs0RYttcxR5I4eeXOEiBTGVucx6NHbvHqq3W7qhyOgKUqGzcoyyyFFkROAM4Itc3iURvt9yow/qsNYXcD+M1kxTjWIFO3oKxcV93i4J/2IOQiKNUoRVipC2z2+MX4XGK9cKHDa9KY1/QGZsVLnx8aL3VvzpRP17VHUnyQpchC2E3J/bO1rTXYXHLAldImwbPkc0p2kPKJtqO872JDeleoh9ZkkXfTeivu+FZcJCr+dstZ0s9AFPLSATEprrMbqJKjJSvPrWoS7nbQfSp687dU8d82iGebj/1M9aZviStmv0DUJuqGMMysuCpsELVHGBGt6GRK0RhmvXQLl+kVzcbarkr62WgsuMb2irWqKuzaAr8TKDPzIUHQZDQ9qu2cuJPct+IssIf87dFD53wo3VFwhOfTK5vwc/LwiD0eKfGcU5D9MmXF/yTcn7TCeL/maLmmj/YANI4jjZ1n4+YdydXNcLztYUMUzWmJBgCILZCXYrwIugYOCnnGOcOYc+rntYJTpQ9jJaVCTBaX+WVgtvW9Z9t0X49vgbpFiCU4WAoh5FC3cBS19M+KSnb4/Fq/9hVxfwdPBdigKzqu/xR8yvS+I)

**Comment by mueller-jens** [comment]
After some tries, i can see a lot of message like *[Vuetify UPGRADE] 'active-color' is deprecated, use 'color' or 'base-color' instead. * 
followed by 
*Property "toJSON" was accessed during render but is not defined on instance.*
in* the console, So many times, that the browser freeze

**Comment by mueller-jens** [comment]
Also newer versions are effected

**Comment by yuwu9145** [comment]
#17267 

In VList, 'active-color' is deprecated, use 'color' or 'base-color' instead. Treeview will do the same
