### ISSUE TITLE
[Bug Report][3.6.13-3.7.0-beta.0.0] focus function is missing for VNumberInput

### ISSUE THREAD

**Issue by b-maslennikov** [vuetifyjs/vuetify#20135]
### Environment
**Vuetify Version:** 3.6.13-3.7.0-beta.0.0
**Vue Version:** 3.4.31
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows, Android, Linux

### Steps to reproduce
click "FOCUS NUMBER INPUT" button

### Expected Behavior
should focus on number input

### Actual Behavior
"focus is not a function" error appears

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UU1PhDAU/CsvvexuIgWC0cTARo9ePHkTD1BLQiyl6QcxIfx32/KN661vOp03M/3okZIkfBECd4aiJ5Rq2ghWaHrNOUDaBYUQ/ugH0nJd1JzKCfIgN01JZVBzYTRIWmU5GqFXh+QIwi271HyeADT90ZZetcQoGB+B18nRSnomrCbfM+1tK72SCCuUspymDOJovditdtuCqqbsa7LpgP9M7r25YXZ2MPR+QyQNj105ZKwyDTcV21ERWQsNimozNl03opUaemcSBqhk28DJ/s7J0W3Slis9leX3QuaYZ24Yu6yEJdv+eiUc27S88wWyK/Rjhs0G3BXMUOxfnP2O4Y/SUsNRZzFyUyUNx/w2ORruUILvcRIjd3jAcRIk+BFHQUl1gSMcoc9fkAjecA==)

**Comment by wyhsunflower** [comment]
Hi, I already work on this issue and will raise PR later.
