### ISSUE TITLE
[Bug Report][3.6.13-3.7.0-beta.0.0] Opening a v-bottom-sheet inside a v-menu via a binded prop doesn't open the bottom sheet until you open the v-menu as well

### ISSUE THREAD

**Issue by darkbasic** [vuetifyjs/vuetify#20137]
### Environment
**Vuetify Version:** 3.6.13-3.7.0-beta.0.0
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1) Click on the + New button
2) Notice how the v-bottom-sheet doesn't open.

### Expected Behavior
The bottom sheet should open as soon as the binded prop (toggle) gets flipped.

### Actual Behavior
The bottom sheet doesn't open until you click on the three dots to open the v-menu as well.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVU1v2zAM/SuEN6AtUDkOgn2gSIsNQ6/ZYb0tA6rYiiNMlgSJdoIF+e+j7cSxYzWH+mBYFPVEPvLRv/eRd+nku7VxVYroIZqjKKziKJ6WGmBeMW5t89ksUqORSy0cpIp7/7iMMrZWYgf1i3ZVWWjgSuaaeeQOIefs6zI6AhBEJqtu0SAWQpc9C9lOAcAHnqKsOBpH9+zBOmM9HHpoHYikuKB+kWORSZYZ9KwSDmXK1TKCiq2kzmizwSDDZHjlpJf0YKNiSnocX7gyiKZgfiMEEnphMqEIHk2eKzGK8B1J9W5nkg6PUgj4t5HhIIPzY52wQmcNV0eaaJ1K4id84FRhFDtk2mjKK+xYcSe5xjo2Rc0RdgvGC/CcSQxmMmlSCbFCOx0tY6LfKuU1erz8Jyj6HVPc5cE0T1xY4yVKoxlfeWp2qicayxJwMt8gS0JHe3ynyvgg/JnBmuyQx7dUyfRv12LwCGuuQmDDzj5pLnAlk+tex76dcqPs3Jktm4Jl0wRWOdtuiHwISJ/k/mkMFqjij5+Ll+fFy7h8wwHRtUJPbxfSHUm0Ng2mygm0W1+0wdVGD8lGlSTAs8uV/n+oMWnjdSG2cHusnfTwcf8LndT50XR3uHvtHxtXG13ZC+tpKI961U3mdm6TpR3cF4KY+9RJi+AFlu1cl4U1NKj34MQaDrB2poAb+hfctIQRrkfq8mMc5HTbdN5dDd2CEUx0uNelUvfRLP4cT2dsFn+JE7YSyOMkTqI//wEGPcKN)

**Comment by KaelWD** [comment]
Menu content does not exist by default unless it is open https://vuetifyjs.com/en/api/v-menu/#props-eager
