### ISSUE TITLE
v-menu activate and deactivate events

### ISSUE THREAD

**Issue by paladin2005** [vuetifyjs/vuetify#2013]
The oficial documentation describes two events on v-menu named activate and deactivate.
But looks like they are not functional.
How I can trigger when v-menu is shown?

**Comment by jacekkarczmarczyk** [comment]
You can watch the v-menu model.
BTW - the issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
