### ISSUE TITLE
v-text-field lost their background color.

### ISSUE THREAD

**Issue by Riotsmurf** [vuetifyjs/vuetify#2014]
### Versions
vuetify@0.15
vue@2.4.4
### What is expected ?

https://i.imgur.com/QoiVqFp.png

I expected the fields to have this style.

### What is actually happening ?
https://i.imgur.com/mBnsL8M.png

Ended up with no underline and no slightly greyed text. I inspected the elements and they are the exact same as the example in your [documents](https://vuetifyjs.com/components/text-fields)

### Reproduction Link
Reproduced on code pen [here](https://codepen.io/Riotsmurf/pen/rGGOgv?editors=1011)

I did inspect your websites CSS and saw that my text fields didn't have this
.application--light .input-group:not(.input-group--error) .input-group__details:before {
    background-color: rgba(0,0,0,.42);
}

but on your documentation page; it did.

**Comment by Riotsmurf** [comment]
Sorry! figured it out. I needed the v-app element or apply .application--light class to the main container element.

**Comment by jacekkarczmarczyk** [comment]
You're missing the <v-app> in codepen
https://codepen.io/anon/pen/VMrNjR?editors=1011

**Comment by Riotsmurf** [comment]
@jacekkarczmarczyk "You're missing the in codepen" what?
