### ISSUE TITLE
[Bug Report][3.6.12] v-textarea and v-text-field icon/button alignment issue

### ISSUE THREAD

**Issue by mschoeffmann** [vuetifyjs/vuetify#20159]
### Environment
**Vuetify Version:** 3.6.12
**Last working version:** 3.6.11
**Vue Version:** 3.4.31
**Browsers:** Safari 17.5
**OS:** Mac OS 10.15.7

### Steps to reproduce
Switch from v3.6.11 to v3.6.12 in the Playground to see the alignement issue.

The provided workaround in #20154 does have some unwanted side effects:
- It makes the ripple/pressed background too small
- It does not work with "text" buttons

The center-affix also has unwanted side effects:
- It makes the field single-line which does remove the label

### Expected Behavior
Everything should be aligned as in 3.6.11.
If center-affix would not remove the label, this would be a workaround.

### Actual Behavior
- Layout is broken
- Text-Buttons are aligned to top
- Ripple/pressed background too small
- CenterAffix removes the label

![Screenshot 2024-07-13 at 14 03 26](https://github.com/user-attachments/assets/b2314688-9115-4319-bfbb-aadde172c61b)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtll1v2jAUhv/KUXaRTWpA3aZJY2wS3dI2Gi0TULpq7MIkJ41Vx45sh5Uh/vtOAi1JC6yt1LveIHJe53w/in/NHaPDZifLGtMcnZbTtphmgln8MpYA7anHsqz8Wz6ESlrGJeqViYwRn0IomDGfx05mvfdj51YDODMINkEY5Wh5PIMpasOVBIMCQ6s0WAVhguFVeSricYwaZYgGGo1Ge6KhWXH2QyAjf0wYBSmXUflOoshnMxQ8vMIIjKXMgRmSuAGTqD/0q1KECQuvLrXKZbT2FyqhdOO2kCZVsr0syCbeu1pt573+906/d3b6Db72vvlw0PV753AeDI9hdOYPg8MLGPn9QdA7hXeND439tzAYBt0uHHcGcNQNhl+P/cGW4FMvwpjlwhov02rKI9TruK0bjTKbu6MDK93W3E2QXybWbbkst8rdcyOUhtsZGUKVZiy07h64hv9FtwUklh7cxWLs3DiuVEbxLV5bL+YoKv0CmHqpilBQYC6z3K5fLvPS1G2S9u+YU3btraSPdYn2LMRECSqPxAuVazhBY9gl0vTrRwWblHGDIi4ktCV1fco0Z9LSCZVbQRsa1fVVO0indsRKWzYRd1yU61BMW/OU6VldLLpaNFKgxSJIHNd1qTyNRXurxoQGR5MkYoRZ2yuNplbf4AavMo0ZysjjssrX7UQmVlaqLOYzdoATkPSURtwLhTJUUY2YYrEqPG8JTIQ/Mu6XIRrbbpbi4zM1FG13omtjdRPXfJD5HiCV+h4Ab68fHAWnnW4NXQJ6sAPg/a20bqJlBysbSdnKyYMp2c3IbkL+y8cOOnazsYGMTVxUp/4QJp5IxBYeHkLDY1l4GgkbOLhHwTPv+VvoFN80/3To9zuHh8HPtbuDsyH0/ZPeyB9At3Pgd1+QeD4kKAJKi9pjccyvX0B5PCg3xvq1tbAsb7V3imybUPPM0u3U5stLL08zGjzMQWMMC4i1SsGli7K77An5NRbKZYbPxZnXblGkV66b+6YIsHS5cm9nYpltY1nyfJni+nJKmdJOtUAUl7lLzWafihOL0tHqZWexJ3Mh9pwlq87vf1XFf0w=)
_(v-btn style just for better visualisation of ripple/hover background)_

### Other comments
Could be related to #20064, #20134 and #20154.

**Comment by yuwu9145** [comment]
- VTextarea has to display affixes aligned to top with input when using multiple rows, so textarea's affixes cannot be expected to be able to occupy whole row the same as VTextfield does
- For VTextfield, it always has only one row, you can use`center-affix` to get buttons occupies the whole field

<https://play.vuetifyjs.com/#eNrtlm1P2zAQx7/KqXvBJi2tgGnSWEEqECBaaac+MbTuhZtcGgsnjmwno0N8913SQpMu7Vq0veNNlNzZ9+D7/xR/f6hp5TZacVxPE6wd1ZoGw1gwgyfjCKCZWiyO89f8w5WRYTxCtTCR0eMpuIJpfTyuxcb6MK49+wCGGsEECKMEDfdnkKLSXEagUaBrpAIjwQ3QvctXedz3UWHkooZ6vd6cKGgUgn0VyCgeE1pCyCMv3xNIitlwBXfv0ANtqHJgmlxcgw7kT3rKEGHC3LupkknkLeO5UkhVf26kQZ2sbwviiXVY6u2m2/vS6nWHnXM4657bcNq2uzdw4wyuYDS0B87FLYzsXt/pduCw/rG+fwD9gdNuw1WrD5dtZ3B2ZffXJE8tD32WCKOtWMmUe4UDz90G743lcxSFdgBSK5QeCqqYR3FixrWi80jRYZBrf8Ucsntr4fpUdpEMXAykoOzkvJWJgmvUmk2RhlNeKtgkz+tkeSGgIZb9KVOcRYZWyMQIEpBX9nsYaW5m5Hdl6Etl2ESshMinlQ1D8ZCpWdnJEiNpZyzQYJbE91c2Y2RQWcz3+X3RHklLoea/sGgM6LxpACR0oZf2wgBoBE+UwJtYYYyRZ/GoiMXzpCYmKnSfzW1cA04c0VfoccsVUlOnJaFneihguCYxgblj3pMBatNs5M7dK9WUbXOhS2NRoUtZk7lK1zsw1+05l06n1S4RRxz2N3C3vxayKoo2MFRJ0Fp+tqZnMzubyfkrNxuo2cxMBRnVEFXRUtTCNqS8kJM1lGzDyK6EvIyPCjr+YOM/q/8AWtkPyu4M7F7r4sL5tgx3OhxAz77ujuw+tFundvsVlH8DSvUPpAqfV1C2B+XJWL6DZpb5FXWlyaZ2FY8NXTVNMr/B8jCmwcMDKPThEXwlQ9ijW+/e/EworjaQixmOszVv97ImrVxue++yBPOQi/BmJubV1uctP8xLXN40qVLS1BEIPg3MVLHZ52zFYx5osbn2+D5KhMgfP34DKqJvAw==>

**Comment by yuwu9145** [comment]
@mschoeffmann I had the same pain. bc2f96a7d1e8f46eacd0704e986a978dc4b556d8 has been made on master branch.

So center-affix will only set single-line when it's default null, but showing labels can be enforced by explicitly set single-line to a Boolean false

**Comment by yuwu9145** [comment]
@mschoeffmann We are going to revert this breaking change #20173, but all changes that were talked about in this thread will be available in future release
