### ISSUE TITLE
[Bug Report][3.6.12] isHovering not defined before an actual hover

### ISSUE THREAD

**Issue by kaplan512** [vuetifyjs/vuetify#20150]
### Environment
**Vuetify Version:** 3.6.12
**Vue Version:** 3.3.2
**Browsers:** Chrome 126.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
add `<v-hover v-slot="{ isHovering, props }">`
you should find that isHovering not defined and make any logic impossible 

### Expected Behavior
isHovering should be false when component mounted

### Actual Behavior
isHovering is not defined which make some complex logic implementation impossible until element was actually hovered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUkFOwzAQ/MriS0AihBtS1YK49QccCIfU2SRWHduy3VAR5e+s3UIc1J7wIcrujGc3mXkfmbO8eDXmYTggW7G1x97IyuNzqQDWQ14ZE19jwbXylVBoz63Y9Hj0eSNQ1jDkva5RbkrWu7ZkUKS8Tg9oieKk9sQYQbhtaAnVwgaaSjq8B2O1cTCV7PdmvLvzaq6BRHZC1SQS6SVLsRWXlXOEpc35zEMv4+G8QBY/aicrvs+u81Zn3mcnPF7g/V1MS23/u9i1WclO19ZeTjYWDao6F2RqMKwWOe9wsFrlVrSdX7Kd+EJiHXNZ2RaXWIeBT+jTYwokDgJwKfgexoXp05R4XEST57xQHQPzEz6ql+kLnVM410USWiodt8J4cOgPp+yK3mjrYQSLDUzQWN1DRnmnfxRg0nUeKLEUQ2LcZluUUsObtrK+ye7CgJMkibHpXh2kjI+Pb8ZR4rE=)

### Other comments
Hi all! I found out that isHovering is not defined from the very beginning until it was actually hovered. I use some complex logic with element intersection on scroll and I need this to be true/false when component mounted

**Comment by KaelWD** [comment]
https://play.vuetifyjs.com/#eNqlUj1PwzAQ/StHlrRSQ9iQqhbE1p2BgTCkziWx6tiW7YaKKP+ds1uIg9oJD1Hu3vN9+L33IbGG5S9a3/dHTNbJxmGnRenwqZAAmz4rtQ6/IWBKupJLNJdUSDo8uazmKCros05VKLZF0tmmSCCPea3q0RDFCuWIMQC3O5/isoEt1KWwuAJtlLYwFsnvzXB37+QUAxXZc1lRkUAvkhhbM1FaS1icnM7U9DruzzOkYam9KNkhvc1bX3ifLXd4hfd3MCWU+e9gt3pFM90ae95ZG9Qoq4yTqF6wimesxd4omRnetG7OtvwLiXXKRGkanGMtej6hjw8xECkIwARnBxgGeHV+xcW07RLGMdI6D2JPvqE4GOfHhBTPXegzZ5Nu8si8FFpmuHZg0R3PHuadVsbBAAZrGKE2qoOUfE9v5WGqax2Qc8mOxFikOxRCwZsyorpLl77BuSQVS8aVPAoRPh/fByDleQ==

**Comment by kaplan512** [comment]
> https://play.vuetifyjs.com/#eNqlUj1PwzAQ/StHlrRSQ9iQqhbE1p2BgTCkziWx6tiW7YaKKP+ds1uIg9oJD1Hu3vN9+L33IbGG5S9a3/dHTNbJxmGnRenwqZAAmz4rtQ6/IWBKupJLNJdUSDo8uazmKCros05VKLZF0tmmSCCPea3q0RDFCuWIMQC3O5/isoEt1KWwuAJtlLYwFsnvzXB37+QUAxXZc1lRkUAvkhhbM1FaS1icnM7U9DruzzOkYam9KNkhvc1bX3ifLXd4hfd3MCWU+e9gt3pFM90ae95ZG9Qoq4yTqF6wimesxd4omRnetG7OtvwLiXXKRGkanGMtej6hjw8xECkIwARnBxgGeHV+xcW07RLGMdI6D2JPvqE4GOfHhBTPXegzZ5Nu8si8FFpmuHZg0R3PHuadVsbBAAZrGKE2qoOUfE9v5WGqax2Qc8mOxFikOxRCwZsyorpLl77BuSQVS8aVPAoRPh/fByDleQ==
@KaelWD 
but this is string, I need actual value to apply some styles, not just render text. I add text here just for test

**Comment by blalan05** [comment]
so: !!isHovering, undefined is a falsey value.

**Comment by kaplan512** [comment]
@blalan05 it should be, but it is not. It is ok for me if this would work like this (undefined == null == false), but any logic just ignored.
I think I should add some styles to be more prominent, but I don't want to create very complex example.
This issue also discussed here https://github.com/vuetifyjs/vuetify/issues/19601

**Comment by blalan05** [comment]
![image](https://github.com/user-attachments/assets/6500b9d2-fe4b-4ecf-a49c-a52719cbff58)

**Comment by KaelWD** [comment]
`!!isHovering !== test`
