### ISSUE TITLE
[Bug Report][3.6.12] v-date-picker range selection needs to select start date twice when cleared

### ISSUE THREAD

**Issue by svannierswm** [vuetifyjs/vuetify#20167]
### Environment
**Vuetify Version:** 3.6.12
**Vue Version:** 3.4.31
**Browsers:** Firefox 127.0
**OS:** Linux x86_64

### Steps to reproduce
1. Make a normal selection (two dates for a range) [ex. 9 to 16]
2. Clear the range
3. Click to select the start of the new range [ex. 10]
4. Click to select the end of the range [ex. 14]

### Expected Behavior
Should end the range [ex. 10 to 14]

### Actual Behavior
On the fourth step this sets the start of the range

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMtOxDAM/BUrl92Vtq0AiQNqKxD8RdtDSFMUSJMojyJU9d+xs4CKxIWbPR7PjN2tLHhRPThXLkmyO1ZHOTvNo2x7A1AvhbAmcmWkz0CGvH2H1xSimj6angXHhSy4t8mMPftiZd6IMoVT4k16WIrZjlIjn9CewZx0VE5LRDw3Lwi1dfVr59sQUXT8v/1zNHAvNGohTWjJ/VO2bh+pJllk/GFC9f7qutr9BNsgvHIRgozJ5QU1O+sjrODlBBtM3s5wwHceiA6AWiECHQYNUY7dcNpPfqLh+HiCpoX1EopWyoXrRJNuIHCjOJcAaM22s0lan9lNeVteXbPhE8oHmIU=)

### Other comments
This has a great chance to be linked to this issue : 
https://github.com/vuetifyjs/vuetify/issues/19854

**Comment by yvangrdv** [comment]
I notice that the bug does not occur with the VDateInput component : https://vuetifyjs.com/en/components/date-inputs/#range

**Comment by svannierswm** [comment]
This seems to has been fix in v3.6.13 from #20169. Linked to this issue to #20168
