### ISSUE TITLE
[Bug Report][3.6.13-3.7.0-beta.0.0] Types for components break if imports are mixed up

### ISSUE THREAD

**Issue by Fuzzyma** [vuetifyjs/vuetify#20177]
### Environment
**Vuetify Version:** 3.6.13-3.7.0-beta.0.0
**Vue Version:** 3.4.31
**Browsers:** Firefox 128.0
**OS:** Linux

### Steps to reproduce
```bash
npm create vuetify
```

Open `main.ts` and move the `App.vue` import in front of `import { registerPlugins } from "@/plugins";`

Types for components are broken now

### Expected Behavior
Types should not break

### Actual Behavior
They indeed do break :D

### Reproduction Link
[No repro possible in plaground](https://play.vuetifyjs.com/)

### Other comments
In my own projects it doesnt even matter what imports I move in front of the vuetify import. It always breaks. In this example here, it only breaks if I move the App import

**Comment by Fuzzyma** [comment]
This seems to have been fixed in 3.6.13 in [bd1f63d](https://github.com/vuetifyjs/vuetify/commit/bd1f63dcfc57ef0b15b8cfd2847bd40ba7751a39)

**Comment by KaelWD** [comment]
You should still import vuetify before any components though, import order matters for styles.

**Comment by Fuzzyma** [comment]
@KaelWD true, in my project it broke when I had _any_ import before vuetify so I am glad it is fixed nonetheless :)
