### ISSUE TITLE
[Bug Report][3.6.12] VNumberInput: null value for min/max attributes is interpreted as 0

### ISSUE THREAD

**Issue by Mutusen** [vuetifyjs/vuetify#20175]
### Environment
**Vuetify Version:** 3.6.12
**Vue Version:** 3.4.31
**Browsers:** Firefox 128.0
**OS:** Linux x86_64

### Steps to reproduce
```vue
<v-number-input :min="null" :max="null" />
```

### Expected Behavior
I'd expect a `null` value for the `min` and `max` attributes to be interpreted as the absence of min/max value (e.g. when the value comes from a computed property which may return a number or `null` when the field doesn't have a minimum value).

### Actual Behavior
`:min="null"` has the same result as `:min="0"`.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9j8EKwjAMhl8l9OzsfXQDn8N56EoOhTaGNh0D8d3tuh1ExUvI94U/JNeHysnpC/N5Kah6ZQQjBys4TgRgls4yt7aBu5NYT5gO1SSVOGPqPHER6KOnYVJUQpgUBDtjqFglDHBI/Sds1x9hu36Hjf68ZjP7sUa/PVExu+RZIKMUHo3esY7U87RtbeX2AvYGWAQ=)

**Comment by KIDS-interactive** [comment]
use `undefined` as value.
Otherwise the prop cannot fall back to the default value (`-Inifinity` and `Infinity`)

**Comment by Mutusen** [comment]
Thanks! It works, it should be explained in the documentation.

**Comment by KIDS-interactive** [comment]
> If a default value is specified, it will be used if the resolved prop value is undefined - this includes both when the prop is absent, or an explicit undefined value is passed.

https://vuejs.org/guide/components/props.html#prop-validation

**Comment by yuwu9145** [comment]
It should be an issue in Vue, `null` seems to be able to bypass type check and skip validator, while using `undefined` will enforce the default value

<https://play.vuejs.org/#eNp9UstOwzAQ/JXFl4JUkgOcorQSIA5wAAQcfQnJtnVxbMuP0qrKv7N22qRIqCevd2ZWs489uzMm2wRkBStdbYXx4NAHM+dKtEZbDw8rIRtYWN3CJMvTLwomXJV5ryAufTy2RlYe6QdQ9qqiFWrGmQpScpYTUuYnNDZl3tVaLcQyWzutyMM+ijmrdWuERPtqvNDKcVZAQiJWSal/nlPO24DTY75eYf39T37ttjHH2ZtFh3aDnA2Yr+wSfQ8/frzgluIBbHUTJLHPgO/otAzRY0+7D6oh2ye85PYpTVKo5ad73HpU7thUNBqZXeJzRnN9ONP6aPcmu006rjqa4rCUcYs0Xtym/TW4qIL0fRVjtXFDRdrOEAP4ncECXkL7hfbgH47qAq6faE9K+N0AbSopmsprW8QQZvOxFACtlUaDmdTLy0mEhRoFk2mMr0a2pZOziQAXsxmkezmA1OLwxHbPn10jNimg0Mz3+9ghdF2Zx3umXN7jf6+w+wVWdfsF>
