### ISSUE TITLE
[bug]upgrade to new version(0.16.1) error

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#2017]
do this
`vue init vuetifyjs/webpack-advanced`
`yarn install`
`npm run dev`

all will be work fine

but after I upgrade vuetify to v0.16.1
`yarn upgrade vuetify`
and then `npm run dev`

the chrome devtools console tell me this error
`Uncaught TypeError: Cannot read property 'install' of undefined`
and give a blank page,what's wrong?

**Comment by KaelWD** [comment]
Either you didn't follow the upgrade guide or you're importing a component somewhere without being set up for a-la-carte. This is not a bug, it's a problem with your project. 

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
