### ISSUE TITLE
[Feature Request] When creating a virtual component, inherit its defaults, which has already been redefined.

### ISSUE THREAD

**Issue by lna1989** [vuetifyjs/vuetify#20182]
### Problem to solve
What is the idea: If you redefine defaults for VBtn, for example color: 'red' and make allias VCustomBtn: 'VBtn' at the moment it does not have a red color like VBtn.  Do not know if you originally intended this behavior or if it is a bug.

Example: https://stackblitz.com/edit/vitejs-vite-wtue87?file=src%2Fmain.js,src%2FApp.vue,package.json&terminal=dev

### Proposed solution
I think it would be interesting to add a flag where we could use both the first option and the second one when the button turns red.

**Comment by KaelWD** [comment]
This would make it way too complicated, we also have to lookup defaults provided from other components.
