### ISSUE TITLE
[Feature Request] v-treeview with append-icon

### ISSUE THREAD

**Issue by bintheext** [vuetifyjs/vuetify#20186]
### Problem to solve
I'd like to be able to add append-icon to the parent node at the first level of the treeview

### Proposed solution
none

**Comment by yuwu9145** [comment]
Can you use `append-slot`? https://vuetifyjs.com/en/api/v-treeview/#slots-append

**Comment by bintheext** [comment]
> Can't you use `append-slot`? https://vuetifyjs.com/en/api/v-treeview/#slots-append

![Snipaste_2024-07-18_12-36-17](https://github.com/user-attachments/assets/24548f84-08c6-4459-8980-a7d2c4b9d712)
I want to set icon the green position(father node)

**Comment by bintheext** [comment]
i found it

**Comment by bintheext** [comment]
I found out that he was removed after 3.6.8

[https://play.vuetifyjs.com/#eNqNVFFuozAQvcqIn7RSIB+rXa1QGmlPsAdo+uHYDnXX2BYMlFXE3Xfs4mBSsiofCZ735s34eczzJWsbvvvlXNF3MiuzPcraaYbycDQA+z7HRspeyXcoFUHt0zEL/8cMGEfVM2Qn/UEmekyGPm+1xZI5J42gnAv4LBiP2UQN2opbc4BaqPxk6xPsd1NoUtsteyE0NkOBBUrLljfKYWDKwdkGQcgz6zTC5UNOUKslPDzC0wEephiAMgoV0/rvb+q0hOeN605a8c3LNjLOSsu2jCr+ecVal7DxfWtmqo5VMvex75trEsAb5QSKsUK+tUvIUqkAcgJzv07xWtyq16z5I+z7guXEeaL5DnNakovDgmGqlKFqkkpxHDDFheVdLQ3mtkOtzII66LidQJUDl3rGx+ubPyBycXYvDAtFZqnESOIr1JQQXU8qAvBXpUUTTiUN3yikKi0yvFX5r9KqWqqobWUL8vGzZhwN3/w6PrsSn9mWdcbdjZ1Z7y9GQT+fK93v4sv6ygg5FH6G78qvgUv9dHcpsnrgRUX3rjK2WYzZtRqNZhqf5WKR8TG8jP5DcL362bg1ndbb7Fvxo/iZvfwDqY9PwA==](url)

![Snipaste_2024-07-18_12-47-23](https://github.com/user-attachments/assets/92c36701-06f7-4233-a08c-a52444f860c9)
![Snipaste_2024-07-18_12-49-27](https://github.com/user-attachments/assets/07520cf7-d3a7-46a3-aee1-4373a188f71a)

**Comment by yuwu9145** [comment]
It's currently available on dev branch. https://github.com/vuetifyjs/vuetify/issues/20095

**Comment by bintheext** [comment]
Problem solved by https://github.com/vuetifyjs/vuetify/issues/20009  
Note, using selected instead of activatable works fine. Using neither selected nor activatable also works fine.
