### ISSUE TITLE
[Bug Report][3.6.13] When I bind a value in text-filed or select component with readonly prop, label does not go up

### ISSUE THREAD

**Issue by molaei2000** [vuetifyjs/vuetify#20184]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
when the page loaded label doesn't move up while the value bind to that. in some case I need to show conditional value.

### Expected Behavior
![image](https://github.com/user-attachments/assets/1ebb04f8-241b-4d3e-8a08-4a953a52370b)

Label should go up and the value appears.

### Actual Behavior
![image](https://github.com/user-attachments/assets/e0c1c7a4-19d0-430c-9e9d-691bf76fdb98)

Label doesn't move up.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdj82OwjAMhF/FyiW70rK9Vw2IG+9AOYTiQiTnR4lbgRDvTtJSgbhY9ng0+mZ/Fyl21TaE/3FAUYuG0QbSjOvWATTjSocwrdPRecfaOIwvaRIZr7zqDdJpEQHqUdOAqhU2nZVS8mLkRu6MrOUOibxsxdtL+oiUrclb5Itx589nRH3yjm6LUi0w1TdNUWbYpvookc/URRMYEvIwdzE2+Mhwz+k9PKCP3oLM/WWxA+TcxJDJQRXHT6H/LbFzUI4Qjz83EE3j8ATGL2cc)

**Comment by yuwu9145** [comment]
Use `:model-value` instead

<https://play.vuetifyjs.com/#eNpdkE2KwzAMha8ivPEMTCb7EM8wu95h0oWbKK1B/sFWQkvp3WsnDS3dGOvp6fFJ/1eRYl//hfA9Tyga0TLaQJrxp3MA7VzpEJbvUvTesTYO40NaRMYzV6NBGjYRoLF+QKpmTROqTth0VErJk5G/cmdkI3dI5GUnnhOkD0jZmrxFPhl3fG1G1IN3dNmUekOq35mKsiK39csquUx9NIEhIU/rRsYGHxmuOX2EG4zRW5D5CrLYAXJuYsjkoIrjo9B/ltg1KEeI25ebiJZnfweB02la>
