### ISSUE TITLE
[Bug Report][3.6.13] v-data-table does not select row with item-value returning an object

### ISSUE THREAD

**Issue by cleemansen** [vuetifyjs/vuetify#20188]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.32
**Browsers:** Firefox 128.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Open the reproduction link. The initial selection (model) is not present in the table.

### Expected Behavior
- the select-all in the table-header should indicate some selection (OK)
- the row _Windows / 3.11_ should be selected (NOK)

### Actual Behavior
- the row _Windows / 3.11_ is not selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VE1vozAQ/SsjDiWVQj52Ve1uFCKt+gNaqVJbqenBCdME1RhkG9oK8d87BuOYHHKoBAfwm4ffzBvDvNSBkvv5/6KYVSUGq2CtMSs407jZCoB1FSVMs0izHUcTAKiiLE+Qx9tAIce9TnOxDTpqdUSWoFTE2ZVjUpKNKsZLJNIAiDcwqQXLcAUGz8xyChVtIkUbs6i5djqtRLTPs4JJpnNp1W5dYJDRVJKgUii1K6WNRwXKqGAHU81Nz6hj/hF1pkxgs5777tt+1LUz3TRbsZ573SKo9jItdPsmfha51JDgGyu5hrpLYeQm1z0CkKhLKU6Yiuj1V/BSQ9ef8CkVSf6hQq8/4e/ZchlC8zo97bVNp52nGNXsAwCdam4076gFTKfiAA9fimyEnpC5GE8PJo/STOpz8h2/iDLVDZlmgGqX7LErmwz0sigSQp2ONUVuvO2+sf4MLzs7b9aQPevcpbJ/JvvvZgzRvyOI/losFiPIPt+PIPqY0gc4gu6fETTHOKvlGCd16fs//Xc04HwyQ33ME/oHXdLh5J2wKey82eamG2tnO8RxDLtueXVFQVuOjVvkctuk3bMdtW64Bs1UlJy3t9dvoFzP+A==)

### Other comments
Another, similar issue:

1. select the eg 2nd item (_Windows / 95_): notice that an item gets pushed into the model
1. deselect the same item: notice that the model does not remove the item but pushes the same one again

**Comment by thezboe** [comment]
This is also an issue for me using the `return-object` boolean prop, which I think is just a shorthand for returning the entire item in `item-value`.

Completely breaks the data table functionality.

**Comment by iann838** [comment]
I am also having this problem, does not remove from model but pushes it again

**Comment by iann838** [comment]
It is still an issue in version 3.7.3.
I am leaving my temporary solution here:
```ts
// swap `ItemType` and `itemValueFn` with yours.
const selected = ref<typeof ItemType[]>([])

watch(selected, (after) => {
    const itemValueFn = (item: typeof after[number]) => Object.values(item).join(",")
    const occurrences: Record<string, number> = {}
    for (const item of after) {
        const itemValue = itemValueFn(item)
        occurrences[itemValue] = (occurrences[itemValue] || 0) + 1
    }
    if (Object.values(occurrences).filter(count => count > 1).length) {
        nextTick(() => selected.value = after.filter(item => occurrences[itemValueFn(item)] <= 1))
    }
})
```
This watch function removes any duplicate in the selected array, counteracting against the unintended push twice behavior.
The checkbox for select all is also buggy and requires clicking twice to work.

**Comment by MatthewAry** [comment]
Adding the `return-object` prop fixes this see: https://play.vuetifyjs.com/playgrounds/aT3Hrw

@thezboe this prop makes it so `v-model` will give you an array of objects instead of an array of whatever property or from an object you use to identify the object with.

@iann838 I don't understand from your comment the problem you're having in relation to this issue. Please feel free to file a new issue regarding what you are experiencing.
