### ISSUE TITLE
[Feature Request] [VDatePicker] Change week names via prop

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#20197]
### Problem to solve
Currently the Week days are titled in english: S M D T W T F S S

It would be great if I could change them via a prop so I can use vue-i18n to localize them. Doing this via a prop instead of built-in localization would also allow for other use cases like labeling weekdays with emojis.

### Proposed solution
Introduce a prop that takes an array with the weekdays names following the same scheme as the already existing `weekdays` prop.

`<v-date-picker :weekdays-titles="['S', 'M', 'D', 'M', 'D', 'F', 'S']" />`

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/dates/#localization

**Comment by frederikheld** [comment]
Yeah, I know. But I don't use the Vuetify localization and run my own localization solution. The whole stack is complex already, so I don't want to deal with the baked in magic of a framework like Vuetify, because then I have to maintain two localization approaches that are same same but different in the details.
