### ISSUE TITLE
[Feature Request] Better Naming Scheme for Slot Props

### ISSUE THREAD

**Issue by SOONwasTaken** [vuetifyjs/vuetify#20194]
### Problem to solve
When using something like `<v-data-table>` with slot props, you can use the `<template #item.<key>="{ item }">` syntax. However, this can be a problem if you want to include another element with slot props. When using `v-select`, you can also use `<template #item="{ item, index, props }">`. When nesting the `<v-select>` inside of the `<v-data-table>` column, the `item` slot prop name is conflicted, and you aren't able to get any of the properties from the data table item.

### Proposed solution
Thankfully, you are able to use `<template #item.<key>="{ internalItem }">` with `internalItem.raw` as a workaround. However, needing to use all of the slot props for complex designs and page layouts is a real possibility that needs to be addressed. If there is a way that you are able to ensure uniqueness for each element's slot props so that there are no conflicts, it will resolve the issue of needing workarounds, and make sure that any configuration of these elements is compatible.

**Comment by KaelWD** [comment]
This syntax is just https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment, you can name it whatever you want.
