### ISSUE TITLE
[Feature Request] Textarea with auto grow needs max rows

### ISSUE THREAD

**Issue by JackHeroes** [vuetifyjs/vuetify#20195]
### Problem to solve
Currently it is unfeasible to use a textarea that grows infinitely without a limit, so I propose the solution of adding a new "maxRows" parameter, the same as it exists in the react material UI, to define a maximum size to which the textarea can expand.

### Proposed solution
Add a new parameter "maxRows" that delimits how many rows the textarea can increase in height, the same as in the react material UI.
https://mui.com/base-ui/react-textarea-autosize/

**Comment by KaelWD** [comment]
You mean this? https://vuetifyjs.com/en/api/v-textarea/#props-max-rows

**Comment by cbkmutlu** [comment]
for tailwindcss 4
```
@utility max-grow-* {
   .v-field__input {
      min-height: min(var(--v-input-control-height, 56px), --value([*]));
      min-height: min(var(--v-input-control-height, 56px), --spacing(--value(integer)));
   }
}
```

```
<v-textarea
   class="max-grow-32"
   auto-grow
   no-resize />
```

all my respect, i guess this issue for feature request should be reopen
