### ISSUE TITLE
Feature Request Border, Flex Properties and Viewport Height Helpers

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#202]
Please add this so everyone can also use these helpers
http://codepen.io/anon/pen/NpvGGB?editors=1000

**Comment by johnleider** [comment]
I think that flex properties are a definite. I'm not fully convinced on viewport and border seems like it would add more size than it would be used.  Thoughts?

**Comment by dohomi** [comment]
about flex properties, we going to have this as soon the new flexbox properties will land. With the border helpers.. I'm not thinking that this is an oftern-used feature to be honest.

**Comment by johnleider** [comment]
Closing this as there is a complete project setup for updating Vuetify's layout system.
