### ISSUE TITLE
[Bug Report][3.5.14] Unable to add a class to v-btn-toggle > v-btn through Vuetify defaults

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#20209]
### Environment
**Vuetify Version:** 3.5.14
**Vue Version:** 3.4.21
**Browsers:** Firefox 128.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Add following class to your main.css
```
.custom {
  font-size: 30px !important;
}
```
2. Update Vutify defaults
```
defaults: {
  VBtnToggle: {
    VBtn: {
      class: 'custom'
    }
  }
}
```
3. Create a v-btn-toggle with two v-btn inside of it.

### Expected Behavior
v-btn font size changes.

### Actual Behavior
v-btn font-size doesn't change.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUttuwjAM/ZUoL90k2mxC2wMCxC6fgHhZ9hBaA51yU+IyJsS/L00D4zaJlyQ+PrZzbH9sqXclWzeA9eKn+PJ0QGtljUOyJaUDgTDrfGRHFs4okiVuxjXXsInU0miPJDnI6DTwbss1IbgCBQMS34RUsBCNxGkHZrJerjDrdT7G2nsXrcTzh8DZK+qpWS7lX64OPDIJKaXwISYrG49G7RPvk+7v9tzdc017sQcv1hZBQmjAEEFZGRSMW9pwnQtr4zMaQSyKWoNLUATnqHOM/zqge5wgbHDE6ZtATsdDFsF/We9meYWV7NMSLXj6mRbp/jpkRxqCwG6muRI2zNjoIDK2iyeH5/TQQE5DF1qb0xWi9QPGykqHsApkvXaFBmTaKjYJNOYajbWCvDJq0i+eiodcSLsSRZ9VtcdjdwFe5XNnvj24kIzTNItYrt2TG0omZqj0XDymEgnLpZj7tsZFbhYKrsHlDnQFDtyt0s7Crsk7o1xIjFsWliyMYNfTjZTx+PwFWeckOw==)

### Other comments
The reproduction link is incomplete cause I didn't know how to include a CSS file.

**Comment by KaelWD** [comment]
The class is applied, your css just isn't specific enough to override the default size.
