### ISSUE TITLE
[Discussion] RTL <3

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [vuetifyjs/vuetify#2021]
This file ***rtl.pdf*** contains my ideas for RTL/LTR Support, please read it.
And ***stylus.zip*** contains the RTL'ed files that i made.

[rtl.pdf](https://github.com/vuetifyjs/vuetify/files/1359981/rtl.pdf)
[stylus.zip](https://github.com/vuetifyjs/vuetify/files/1359982/stylus.zip)

**Comment by KaelWD** [comment]
Can you make this a PR instead of a zip file? It'd make it a lot easier to see what you've changed.

**Comment by NadhirBoukhenifra** [comment]
@KaelWD i can't now, until we start with process that i mentioned inside `rtl.pdf`,
and the files contains only the `RTL Support Code` for all files inside `stylus `folder.
and its not file or two, there is a lot.

**Comment by jacekkarczmarczyk** [comment]
2 thoughts

1. i believe that it's possible to do in stylus something like this
```styl
dir($start, $end)
  .some-class
    margin-{start}: 8px
    margin-{end}: 0
```
and then
```styl
dir('left', 'right')
```
for LTR, and
```styl
dir('right', 'left')
```
for RTL

That could allow to have common base and avoid duplication

2. some poeple may want to include both LTR and RTL at the same time, so i guess the .rtl.styl should do
```styl
[dir="rtl"]
  dir('right', 'left')
```

**Comment by NadhirBoukhenifra** [comment]
Well,
1. {Start} and {End} method Great, i'm not very experienced with stylus. but i support DRY :).
my point is to let users use ONLY what they want.

2. LTR & RTL at same time? i don't think that anyone do that! Or you mean like that:
```
<link href="https://unpkg.com/vuetify/dist/vuetify.css" rel="stylesheet">
If (Dir == “rtl”)
<link href="https://unpkg.com/vuetify/dist/rtl.css" rel="stylesheet">
Fi
```
I've worked as Freelancer at fiverr with RTL Support GIG.

i believe that the users divided into:
1. User Latin Only (LTR)
2. User Arabic Only (RTL)
3. User Multi-Language (RTL First)
4. User Multi-Language (LTR First)

see this four picture, they are in A4 size, and i loaded them in PDF file included below.
just to figure the problems, and choose the right solution.
1.
![1](https://user-images.githubusercontent.com/13006236/31279424-5540b9be-aaa9-11e7-90f8-9292bbc30bf5.jpg)

2.
![2](https://user-images.githubusercontent.com/13006236/31279425-55498936-aaa9-11e7-977f-47ccd7c87f10.jpg)

3.
![3](https://user-images.githubusercontent.com/13006236/31279426-556f4d2e-aaa9-11e7-83b1-e226fd48470f.jpg)

4.
![4](https://user-images.githubusercontent.com/13006236/31279427-558412e0-aaa9-11e7-8b74-5548a7a66ed6.jpg)


and im waiting for you to choose the process to start RTL, i mean what files will be generated at the end.

[rtl_discussion.pdf](https://github.com/vuetifyjs/vuetify/files/1362784/rtl_discussion.pdf)

**Comment by jacekkarczmarczyk** [comment]
What I mean in 2. is the you could load all three css:
```html
<link href="vuetify.base.css">
<link href="vuetify.rtl.css">
<link href="vuetify.ltr.css">
```
and switch LTR <-> RTL by adding/removing `dir` attr to `<html>` (when user clicks "change language"). It will load 290kB and cache

**Comment by KaelWD** [comment]
I'm not really a fan of most people having to load two CSS files. The default build should be LTR, and RTL support can either be an entire new file for RTL-only, or a smaller addon for the base file to allow both. 

LTR only: `vuetify.css`  
RTL only: `vuetify.rtl.css`
LTR + RTL: `vuetify.css` and `vuetify.rtl-plugin.css`

**Comment by peluprvi** [comment]
If choose the direction of adding .css files, I think it needs all possibilities:
- vuetify.base.css (without LTR or RTL styles)
- vuetify.ltr.css (only LTR styles)
- vuetify.rtl.css (only RTL styles)
- vuetify-ltr-only.css (base + LTR styles)
- vuetify-rtl-only.css (base + RTL styles)
- vuetify.css (base + LTR + RTL styles)

For example, moment.js did this with the locales files. They have a single file for moment.js, another file for moment-with-locales.js and separated files for each locale. https://cdnjs.com/libraries/moment.js

In this way, it's up to the developer to choose the better solution for their product. So, we can either load every styles at once or lazy load them depending on the user language or locale.

**Comment by peluprvi** [comment]
Just to add more to this discussion:

Material guidelines:
https://material.io/guidelines/usability/bidirectionality.html

The application can have both LTR and RTL elements in the same page. The last example of the Material guidelines displays different languages in the text. Application examples: simultaneous languages like Google Translate. In my option the most usage of this will be only text alignment.

Icons can be a little tricky.

**Comment by NadhirBoukhenifra** [comment]
@jacekkarczmarczyk , yes it can be.
@KaelWD Yes im agree wiht you, some people NOT need to load two files, and take look at the all possibilities of @peluprvi ( and i mentioned that in the first pdf file ).
@peluprvi yes excalty what i want to say! and you have added all possibilities thank you:
```
vuetify.base.css (without LTR or RTL styles)
vuetify.ltr.css (only LTR styles)
vuetify.rtl.css (only RTL styles)
vuetify-ltr-only.css (base + LTR styles)
vuetify-rtl-only.css (base + RTL styles)
vuetify.css (base + LTR + RTL styles)
```
@jmichaliga , for me NOW, i have RTL'ed every component inside stylus folder.
this is the folder https://github.com/vuetifyjs/vuetify/files/1359982/stylus.zip
and i have added `rtl.styl` that load this files and generate `rtl.css` and call this file in HTML.
look at this pictures! i hope it help you <3.
![30](https://user-images.githubusercontent.com/13006236/31306462-ddae0df4-ab50-11e7-8f9b-61bb58ad2a66.PNG)
![31](https://user-images.githubusercontent.com/13006236/31306463-ddb1cb60-ab50-11e7-9829-68ce67152262.PNG)
![32](https://user-images.githubusercontent.com/13006236/31306464-ddbd6b64-ab50-11e7-99ce-01baa7526ef2.PNG)

and generally, as I've said the end-user must have the choice, and I'm with: **`generate all possibilities`**.

**Comment by peluprvi** [comment]
Do not forget the scrollbar to the left, with `direction: rtl;` on CSS

**Comment by sksadri** [comment]
why would you add a different folder for RTL. IMHO it will lead to confusion as to what files to load/add.
 
I [forked vuetify](https://github.com/sksadri/vuetify) and added RTL support using stylus mixins, you just need to add `dir="rtl"` in your html tag and `rtl` prop in v-app. The advantage here is that you don't need to edit 2 stylus files for the same component. A `margin-left: 12px` would be written in one place with the mixin `bidi-style(margin-left, 12px,margin-right, auto)`, a `text-align: left` is written `bidi-value(text-align, left, right)` and that's it!

The resulting CSS file sizes (v 1.0.0)
original unminified: 338 kB -> with RTL unminified: 358 kB
original minified: 263 kB -> with RTL minified: 277 kB

**Comment by MajesticPotatoe** [comment]
Great discussion. with 2.0 on the horizon, we will be providing full rtl support!

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com). 👍
