### ISSUE TITLE
[Bug Report][3.6.13] VTextField opacity prevents Bitwarden from autofilling details

### ISSUE THREAD

**Issue by merlinz01** [vuetifyjs/vuetify#20218]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.33
**Browsers:** Chrome 126.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Have the Bitwarden Password Manager browser extension installed. Use a VTextField in a login page.

### Expected Behavior
Bitwarden shows autofill dropdown when input is selected.

### Actual Behavior
Nothing happens when input is selected.

### Reproduction Link
[https://merlinz01.github.io/vuetify-bitwarden-demo/vuetify-default](https://merlinz01.github.io/vuetify-bitwarden-demo/vuetify-default)

### Other comments
The demo shows a workaround that doesn't seem to affect the functionality otherwise.

**Comment by merlinz01** [comment]
I noticed that my fix interfered with the placeholder, so I added CSS to the demo to handle that.

I tested this on Brave and Firefox on Linux.

**Comment by yuwu9145** [comment]
Can you provide a screenshot?

**Comment by merlinz01** [comment]
See https://merlinz01.github.io/vuetify-bitwarden-demo .

![image](https://github.com/user-attachments/assets/481bebc7-4120-4c19-9aab-48ac4b201b10)

![image](https://github.com/user-attachments/assets/571e4710-895d-4b2a-ad67-9abb0e13d1cf)

**Comment by yuwu9145** [comment]
It works for me

<img width="722" alt="Screenshot 2024-08-01 at 10 39 24 am" src="https://github.com/user-attachments/assets/c6b326c6-340d-42a6-b93f-c0db066c39fb">

**Comment by merlinz01** [comment]
What browser are you using?
What version of the BW browser extension are you using? I'm using version 2024.7.1.
I just confirmed this also works incorrectly in Microsoft Edge (on Windows) with the BW extension freshly installed.
![image](https://github.com/user-attachments/assets/5bbcedc4-4f9b-48fc-b99e-87f444a72757)

**Comment by yuwu9145** [comment]
I tested on Chrome 126.0.6478.127 & Firefox 127.0.1 on Mac, both are working.

**Comment by KaelWD** [comment]
https://github.com/bitwarden/clients/issues/1621

https://community.bitwarden.com/t/add-option-to-allow-filling-fields-that-arent-visible/4381/3

**Comment by merlinz01** [comment]
Another workaround I have found is to use the `persistent-placeholder` prop, which IMO makes a nicer login experience anyway.

**Comment by MinerMax555** [comment]
I'd just like to add the information for other people stumbling across this issue when searching for autofill problems that I had a similar issue with Enpass and Vuetify 3.8.6. 
The `persistent-placeholder` workaround proposed by @merlinz01 solved that issue as well.
