### ISSUE TITLE
Pick wrong date in text field

### ISSUE THREAD

**Issue by CasperLaiTW** [vuetifyjs/vuetify#2022]
### Steps to reproduce
1. open https://vuetifyjs.com/components/pickers
2. Section `#3 Date pickers - In dialog and menu`
3. Click TextFields
4. Pick a date
5. Get date after 1 month and 1 day on textfield

![pick wrong](https://user-images.githubusercontent.com/5094008/31236616-3a2a89a6-a9ba-11e7-87cf-a04e953159f6.png)

### Versions

Vuetify: 0.16.0
Browser: Chrome  61.0.3163.100

### Reproduction Link
https://vuetifyjs.com/components/pickers

**Comment by KaelWD** [comment]
What timezone are you in?

@jacekkarczmarczyk Looks like it might be that timezone bug back again...

**Comment by CasperLaiTW** [comment]
My timezone is +08:00

**Comment by johnleider** [comment]
Can you please check one more time to see if this issue is happening.

**Comment by jacekkarczmarczyk** [comment]
This issue might occur on some specific hours, so it's best if you check at the same time of the day as before (and write in comment what time did you check)

**Comment by nekosaur** [comment]
Or you know, change the system time :)

**Comment by jacekkarczmarczyk** [comment]
I know, but system automatically reverts to the real time, probably it could be blocked somewhere

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/31265870-dba8ff6c-aabc-11e7-8669-5e90d176e60d.png)

**Comment by jacekkarczmarczyk** [comment]
OK, I didn't see this because it shows only when you're logged in as an admin

**Comment by CasperLaiTW** [comment]
Hi, I recorded my screen.
This is my local time, `Friday, 6 October 2017`.
<img width="216" alt="2017-10-06 11 14 06 pm" src="https://user-images.githubusercontent.com/5094008/31284815-4bb18f9c-aa7f-11e7-8761-68e6f456b6f6.png">

And this is using picker and get results.

![datepicker](https://user-images.githubusercontent.com/5094008/31284853-72376f7e-aa7f-11e7-842b-36e7408624a1.gif)

`Section #1`, `Section #2` and `Section #4` display date is correct, but day of week in head is wrong. 5th Oct. is thursday not friday.

`Section #3` and `Section #5` is wrong when pick

**Comment by jacekkarczmarczyk** [comment]
That's weird, the information given by you looks perfect, however I still cannot reproduce it... I've set CST+8:00 time zone and checked now in Chrome/Firefox/Explorer/Edge and everywhere I'm getting correct results :/
Can you run `Intl.DateTimeFormat().resolvedOptions().timeZone` and `new Date().toISOString()` in console and send the result?

**Comment by CasperLaiTW** [comment]
something interesting, I got timezone `America/Chicago`
![2017-10-06 11 37 23](https://user-images.githubusercontent.com/5094008/31285989-70a2a4d2-aa82-11e7-9b0b-dc57ae2a4ee3.png)

But my system time zone is Taipei Standard Time. weird.
<img width="780" alt="screen shot 2017-10-06 at 11 42 49 pm" src="https://user-images.githubusercontent.com/5094008/31286230-2aca759c-aa83-11e7-86aa-97254d4a6121.png">

**Comment by jacekkarczmarczyk** [comment]
Last question (for now) - what browser are you using?

**Comment by CasperLaiTW** [comment]
![screen shot 2017-10-06 at 11 51 50 pm](https://user-images.githubusercontent.com/5094008/31286619-60d6c8ce-aa84-11e7-8771-98751b4b0409.png)

Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by CasperLaiTW** [comment]
For now `Section #1` day of week name is correct. I didn't do anything.
![screen shot 2017-10-06 at 11 52 36 pm](https://user-images.githubusercontent.com/5094008/31286658-8201ba2c-aa84-11e7-9d59-2bc724fde4d1.png)

but `Section #3` still diff a day
![screen shot 2017-10-06 at 11 53 16 pm](https://user-images.githubusercontent.com/5094008/31286689-98484f6c-aa84-11e7-86dd-5f6318b33f3d.png)

**Comment by KaelWD** [comment]
Open Terminal and run `echo $TZ`

**Comment by jacekkarczmarczyk** [comment]
And run this in console `new Date()`
And BTW maybe you can chat on discord channel? https://chat.vuetifyjs.com

**Comment by CasperLaiTW** [comment]
@KaelWD got nothing.

@jacekkarczmarczyk got timezone is +00:00
![screen shot 2017-10-06 at 11 57 08 pm](https://user-images.githubusercontent.com/5094008/31286865-20246768-aa85-11e7-939b-cbbae929ae39.png)

**Comment by peluprvi** [comment]
I found some related issues in moment.js:
https://github.com/moment/moment-timezone/issues/441
https://github.com/moment/moment-timezone/issues/517

They use `Intl.DateTimeFormat().resolvedOptions().timeZone` too.

**Comment by eelcowen** [comment]
I found that March was duplicated in my view:

![schermafbeelding 2017-10-09 om 09 58 01](https://user-images.githubusercontent.com/2821403/31329220-5400e826-acd9-11e7-9655-c53fa7f12d84.png)

I clicked in March 1 and the date correctly got selected.

Then i went one month further and I see March again.... 

![schermafbeelding 2017-10-09 om 09 58 08](https://user-images.githubusercontent.com/2821403/31329249-7a93a802-acd9-11e7-9940-c8695189cb74.png)

Now i click on March one and April two gets selected....

**Comment by jacekkarczmarczyk** [comment]
What vuetify version?

**Comment by eelcowen** [comment]
Latest 0.16.4

**Comment by jacekkarczmarczyk** [comment]
and chrome@OSX?

**Comment by eelcowen** [comment]
Yes

**Comment by KaelWD** [comment]
Looks like a chrome bug from a few years ago: https://bugs.chromium.org/p/chromium/issues/detail?id=364374

**Comment by elceka** [comment]
Chrome 61.0.3163.100
OSX 10.11.6

March 2017 multiple 26 day in order.

<img width="290" alt="snimka obrazovky 2017-10-12 o 12 28 35" src="https://user-images.githubusercontent.com/2307558/31491934-594a2d70-af49-11e7-8945-a8f8408c8c38.png">
<img width="386" alt="snimka obrazovky 2017-10-12 o 12 28 52" src="https://user-images.githubusercontent.com/2307558/31491939-5b6e1c6a-af49-11e7-968a-87fb132907cf.png">
<img width="290" alt="snimka obrazovky 2017-10-12 o 12 29 00" src="https://user-images.githubusercontent.com/2307558/31491941-5d32de78-af49-11e7-8230-29cae98057b1.png">
<img width="387" alt="snimka obrazovky 2017-10-12 o 12 29 08" src="https://user-images.githubusercontent.com/2307558/31491944-5ef6b93c-af49-11e7-89ef-b44bd8bb1363.png">
<img width="288" alt="snimka obrazovky 2017-10-12 o 12 33 18" src="https://user-images.githubusercontent.com/2307558/31492021-971b426a-af49-11e7-85cd-949b0d47ea5e.png">
<img width="382" alt="snimka obrazovky 2017-10-12 o 12 33 29" src="https://user-images.githubusercontent.com/2307558/31492024-9a25d9e8-af49-11e7-97ef-8683aa0f8302.png">

**Comment by elceka** [comment]
Error presence from the Vuetify version 0.16.0-beta.5, in the version 0.16.0-beta.3 is not this error.

**Comment by peluprvi** [comment]
@elceka Please try it on v0.16.5

**Comment by elceka** [comment]
@peluprvi Please, check my issue #2156

**Comment by jacekkarczmarczyk** [comment]
@elceka can you check your issue using the following template https://codepen.io/CasperLai/pen/MEGJOL? (Use your code, don't change external javascripts)
It uses Vuetify with PR that should fix time zone related issues

**Comment by elceka** [comment]
@jacekkarczmarczyk Seems like be OK with that template.
