### ISSUE TITLE
[Documentation] Upgrade guide information on updated components

### ISSUE THREAD

**Issue by angusprecisionai** [vuetifyjs/vuetify#20221]
### Problem to solve
We have a wonderful upgrade guide [here](https://vuetifyjs.com/en/getting-started/upgrade-guide/).
Users upgrading may not find this page easily while upgrading certain components, hidering their ability to understand changes. Eg: v-data-table has had the class and cellClass props replaced with headerProps and cellProps. The documentation for these new props is vastly different than the previous in implementation and usage. 

### Proposed solution
Adding the upgrade guide for an indiviual v-component on the API page.
Eg: v-data-table now has a heading above Props (or wherever best suits) that has the same information for v-data-table found at the upgrade guide page.

**Comment by KaelWD** [comment]
Thanks for the suggestion, I don't think we have the capacity to do something like this at the moment though.
