### ISSUE TITLE
Use CSS layers by default

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#20232]
v3.6 added cascade layers behind a variable (#15596). We should remove this option so we can make proper use of them in components instead of having to make sure styles work without layers too. 
This is a breaking change as it reduces the specificity of vuetify styles to nothing, including utility classes. Custom styles may need to be rewritten with layers, and external stylesheets modified if they are to overridden with utility classes.

**Comment by andyfehrenbach** [comment]
this would be especially nice in instances in which vuetify uses !important in the component scss files, as these declarations have been quite difficult to override in the past.

**Comment by KaelWD** [comment]
You can already make use of this today: https://vuetifyjs.com/en/features/sass-variables/#enabling-css-cascade-layers
