### ISSUE TITLE
[Bug Report][3.3.15] The sibling v-menu is not opening when it's used within a reusable component, and this reusable component is being utilized in multiple places throughout the application.

### ISSUE THREAD

**Issue by ashwindevx** [vuetifyjs/vuetify#20238]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.4.0
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I created `MenuComp` (reusable) that i want to use in two components, but it is not working if i add it in more than one component

### Expected Behavior
it should open the menu no matter where that component is used and the activator is triggered.

### Actual Behavior
it is not opening menu if used in more than one component

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9U01v2zAM/Such6EJECVOMWCBkw0Ydt5l13kHRVJsbbIkSLSToOh/H2XFaYOih14K+EN8fCSfSOn3QxGDWH33fjn0qqiKHarOG47qW20Bdj+V7X+4zjurLMKKwN3qGYPMKIL2CFFh78Fw23ytC4x1McZrigwIt1kOwXVQF8vVBKfSdbFNuXM2ii0Wo7DnlJfqpB7Sn+pIqqplXWRTGB4jIZIdjDpB+jDhTN9Z+NtH1IczE6REBeBGN3Yy9g1DbZGtSwiut1JJZpopZ8SzUZSzVbppsYLPG3/awlFLbCdD9CG6UIF3lEWFHDkqBXBeWehoN6PwFSnPWxjYBAJwgXrg6AKV+Wj5oBuO2lnmgztoQy3KNGUUschBtHICMXAb9QWNRkvFzuwJnGiVMC4qRkmFI420WWG0+EcxB27itcSTMzeSOhOtO7Jjq/FKqiYW6fOJ9ZDxS6+qyQK4u7RpXZaf4EM+FNziFjp+Yhff/aZMPUTnK/hyn5awd0GqwAKXuo/EGAl7d2Kx5dIdCfEnWKc3LcgLodnzWbmAy7MsN/NrHipPjOioN4k3G3iYMTYwbFWnWBPUmQY/n2/vFln448380pSmtuQR5sm95Ua8PN6/uJWue/2Av+P1u719jwvbGzN+/vwHOs9joQ==)

**Comment by KaelWD** [comment]
Are you using the same ID everywhere? They'll all be binding to the first one.

**Comment by ashwindevx** [comment]
> Are you using the same ID everywhere? They'll all be binding to the first one.

Yes, how can I use different IDs without losing reusability of the component?
