### ISSUE TITLE
[Feature Request] Ability to dynamically disable Pull To Refresh

### ISSUE THREAD

**Issue by filips123** [vuetifyjs/vuetify#20242]
### Problem to solve
I want to allow users of my website to disable pull to refresh if they want, using my settings page.

### Proposed solution
The `v-pull-to-refresh` component should provide a `disabled` prop (or `enabled` or similar) that can reference other sources such as Pinia stores. When `disabled` is passed, scrolling should no longer trigger the pull to refresh (including the animation).

**Comment by yuwu9145** [comment]
When "pull-to-refresh" is disabled, user has no way to load more items
