### ISSUE TITLE
[Bug Report][3.6.13] v-autocomplete append-inner slot props are Objects instead of Booleans

### ISSUE THREAD

**Issue by emailnikola** [vuetifyjs/vuetify#20253]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.3.4
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
No steps needed.

### Expected Behavior
isActive is Boolean

### Actual Behavior
isActive is Object

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUMtqwzAQ/BWhHnzxgxLoIbiBEGh/oNBCnIOwN+mCrBWSbBKM/z0bJY7j22g0M9LMfpDe1cXW2rzvQK5lGaC1WgXYVEaIss+UtRHGQ00mKDTgHtRd0QWqiV0QYKKFsOA8+gAmZJxXwz/pBtx833Y6IHteHLPss5J/r6lyVq2Rf+hZsE92SuORnEGVpCLZkSanGrrhL4bYRPobyJ3uih84K38Dvxdq0ZySwxz8LMSVpgnEG5cH02RouDI/OQj02zpgD2Ks5EYMgwgXC3R88uMoymIxYUwslitNgzK9XDQK4+CLFDmmptM6lav8I39fycMVntOMRg==)

[Complete example](https://play.vuetifyjs.com/#eNp9UstqwzAQ/BWhHnyJY9pjcA0hkN56KrQlzkHIm3RBloQepiXk37uR49puaS72eHZmV6P17sS9k8Xa2mUXga94GaC1SgSoas1Y2eXC2gTThzQ6CNTgrlSviMFIQy4IMNCMWXAefQAdcuon4cOoBtxYb6MKSJ6JY5Q91vxt2pWPqhXSCT0JdtlGKDwYp1FkC5ZtjDJONOaCtwSxSfQTGHfsFS/wKfwFvH6ZFvUx24+NfwJRpOEK2B2FB93kqCkyjTwx9GsZsIMFoa2R0UPDzjWfuMlvWZfjgfSDetkJFSlF9X5fFsN1TsSgPFTPf2veCl3lZZHe/424HmOc8XBjxq9aWczW3VPzjQ7LJ3q+/SRMP8esCz8vdFQqPfbfkm249w==)

**Comment by emailnikola** [comment]
When we add this inside <template> it doesn't work:

<p v-if="isActive">YES</p>
<p v-else>NO</p>

**Comment by KaelWD** [comment]
It's a ref.

**Comment by emailnikola** [comment]
1. isActive never changes its value.
2. all other similar slots' props are booleans.
