### ISSUE TITLE
[Documentation] Documentation page is broken

### ISSUE THREAD

**Issue by bLind17** [vuetifyjs/vuetify#20259]
### Environment

**Browsers:** Firefox 128.0
**OS:** Ubuntu undefined

### Steps to reproduce
1) Visit the page.
2) See that code and examples are missing.
3) Try to go to the "Selects" components.
4) See that that does not work at all.

### Expected Behavior
Docs should be visible and complete.

### Actual Behavior
Docs are incomplete or unreachable.

### Reproduction Link
[https://vuetifyjs.com/en/components/combobox/#api](https://vuetifyjs.com/en/components/combobox/#api)

**Comment by Andrioden** [comment]
The page tends to not respond the first time you access it, but if you refresh after 10sec it works. Seems buggy thou.

**Comment by bLind17** [comment]
It works again now (on another PC). Maybe I need to force refresh the page. 
I've used the docs page a lot, it has been painfully slow at times but recently it was faster in general until the `Selects` part stopped working at all.
