### ISSUE TITLE
[Bug Report][3.6.13] Breaking dynamic slot-names for VDataTable with vue-tsc 2.0.28

### ISSUE THREAD

**Issue by martn001** [vuetifyjs/vuetify#20255]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.34
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Clone project from playground
2. Make sure Vue, Vuetify and vue-tsc match the same versions as the playground
3. Make sure App.vue and DataTable.vue contains the same code as playground
4. Run the command "yarn build"

### Expected Behavior
Application should successfully build

### Actual Behavior
Typescript fails because dynamic slot-name is not allowed/ known in vuetify component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVltv2zYU/isH6oMdzKLWeBswzQ6yLn1oH9piKbAHy0Bpi7aZUKRAUk4Mw/99h9TFlBoYQWsYtniu37noHC6OkdHr5O+yJPuKRWk0s6woBbXsJpMAs31My9I/+sNaSUu5ZLohITGnlsaWrgSDlKOymWeR/88iSHeM5kw7UvOURZ0m6ra+4M3im9Mhkhbs2xLFj+DOcOrJAxxrupeD0wnGx6M/s4JycTpdBbaTXiA16Yy1DSkZxuQodcg9C3g0a81LC4bZqgRB5RZh2jYgXpRKWziCZhs4wUarAkaY0VHAvEPvX32iPDuLSNKRXPaz6C/nCAARGesDNTB3FseLGi5Gn6fwdgIu/hRGH9VOwp1iown4DCDpAUkkV+yWPVNEz8haFSM4TUID12cDVDK4L7jdhSaQSIwjXjIy7Yy8UytwSIySgZWVWhEHBqkvmVlirc6xNt0xjNZyK5yHD3do+JEd8JHnIZBW4BMi6UQcrNDNLKlLh4WKJlgydLnhW/KAyLDhj04sixBayQXTn0vLEVIWpeA5jkeFUE8fPc3qijXeUWfH1o8v0B/Ms6Nl0RfNDNN7rGzHs1Rvma3Z7+8/sWd87piFyiuB0heY/zKjROUw1mLvKpkj7EDOo/3gW47L7Vfz/tkyadqgHFAnWacni7Dv/rkQ+hnulEy9Xibxi3msmzouaDnIZM3om/Hd7eDurC1NmiTrXKJazgTfayKZTWRZJLcoluhKWl6wOFfF7ZT8Rqa/Jzk3NqQTZop4pdUTJhetBLGjAcs3h1f4aiTRxR/k7bR20dBiQVfG+fjOduKrqWPNJLary/rrYhqo9eIa8C7GFmPzvi42J3l7TX4l138mv6DJLOoVT3D5aIZvgPE1W/xs4rydZevJbZfelHM75uIoDYZpZdi9UNa0E7VppGZMAuRsg4P7i1almTW95j7NNEmBysNiidItw4/UPvl0M77q7NXDyHiX8867FziznRFPT8FYja/YYonCn1cPbG0JTiAz9gauyIYLy/TYH92AuoJ5E2BLIQbfL2v+w1E7rrcmyaIrX3HnMxhceBgu5h9cvMHSPQsdMTZRFRIzHWzcmT3v+VBxH2+URq1aB7hstZ1nzEDHcukYbPCZzcMjJlVQ4yBYnHZ1OHGNCzyl1Lyg+gArpZEWr7BpBCY6lgo3l5eQKn7StKw7/PxJW8NHGHk5zbc7C6O0AUuo4FsJ8/kcRvju4cLoW+ihRtympPIG7x+Ntt88eAXBGjlGL8TE5mHeXrqJdJkd3DJ6iW7F23y3beMy3nXhGfWbRSvgblC45kqWD0Sa6rRyLSO4zfF9V5FSGe42As4mRMPdGgvDckYgdcu2ZxHRrrjMhwhuMFH4FF7G+P6lHNRXsN5N7bubmD0gHQ36fxwzp4mshPA/y/8BHBKAvQ==)

### Other comments
The playground is a small example how to reproduce the issue. Since vue-tsc 2.0.28 the issue start appearing. In vue-tsc 2.0.26 the dynamic slot-name was still accepted for the `v-data-table`. Other dynamic slot-names that are not directly passed into Vuetify components do still work. So the syntax ``#[`item.${slotName}`]`` doesn't seems te be incorrect.

The error that is appearing:
```
src/DataTable.vue:32:9 - error TS2537: Type 'Readonly<{ [x: `item.${string}`]: ((arg: ItemKeySlot<any>) => VNode<RendererNode, RendererElement, { [key: string]: any; }>[]) | undefined; [x: `header.${string}`]: ((arg: VDataTableHeaderCellColumnSlotProps) => VNode<...>[]) | undefined; ... 23 more ...; 'footer.prepend'?: (() => VNode<...>[]) | undefined; }> & Mak...' has no matching index signature for type 'string'.

32       #[slotName]="scopedSlots"
           ~~~~~~~~
```

**Comment by KaelWD** [comment]
try `` `item.${string}`[] `` instead of `string[]`

**Comment by martn001** [comment]
> `item.${string}`[]

Oh wow, that already worked! 😄But is this the right solution? Or should there be a change on how Vuetify defineSlots?

![image](https://github.com/user-attachments/assets/dfec57af-0ed5-45ad-94d8-7ee0a34da675)

For now, the project successfully builds, thanksyou so much!
![image](https://github.com/user-attachments/assets/14c21bfd-c5c4-4524-8245-01e2718e626d)

**Comment by martn001** [comment]
De issue can be closed, because the workaround of KaelWD works!

**Comment by KaelWD** [comment]
The error tells you exactly what's going on. 

```
Type 'Readonly<{ [x: `item.${string}`]: ((arg: ItemKeySlot<any>) => VNode... has no matching index signature for type 'string'
```

`string[]` would only work if there was a `[x: string]` slot.
