### ISSUE TITLE
[Documentation] Vuetify 3 upgrade guide is missing removal of v-banner `value` prop

### ISSUE THREAD

**Issue by Paul-DS** [vuetifyjs/vuetify#20261]
### Environment

**Browsers:** Chrome 127.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
The `value` prop of the `v-banner` component is described in the v2 documentation, but not in the v3 documentation. I supposed it has been removed. If that's the case, I think it should be mentionned in the upgrade guide.

Link of the v-banner API documentations:
For Vuetify 2: https://v2.vuetifyjs.com/en/api/v-banner/#props-value
For Vuetify 3: https://vuetifyjs.com/en/api/v-banner/#props

### Expected Behavior
Upgrade guide doesn't mention the prop removal

### Actual Behavior
Upgrade guide should mention the prop removal

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/upgrade-guide/#v-banner](https://vuetifyjs.com/en/getting-started/upgrade-guide/#v-banner)

**Comment by MajesticPotatoe** [comment]
Thats because it was a framework-wide change, and is listed as the first item under general changes
<https://vuetifyjs.com/en/getting-started/upgrade-guide/#general-changes>

>  `value` prop has been replaced by `model-value` on components that support v-model usage. (Vue 3 requires this change

**Comment by Paul-DS** [comment]
Ok, so in this case the `model-value` prop is missing in the [VBanner API documentation](https://vuetifyjs.com/en/api/v-banner/#props) ?
Because I can find it on the [VAlert API documentation](https://vuetifyjs.com/en/api/v-alert/#props-model-value) for example
