### ISSUE TITLE
Floating toolbar issue

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#2026]
I'm having a weird issue in 0.16 where my floating toolbar in a couple of components is being pushed up underneath my main (fixed) app toolbar, but in another component it is perfectly fine, sitting just below the main toolbar. This was working previously 0.15.3. The toolbar code looks like this:

```
        <v-toolbar floating >
            <v-select
                    :items="getCommunityTags"
                    v-model="searchTags"
                    label="Select categories"
                    autocomplete
                    multiple
                    prepend-icon="search"
                    single-line
                    chips
                    @input="changeRoute"
            >
            </v-select>
        </v-toolbar>


```

It's the same code across all 3 components and I can't figure out why there would be a different behavior.

**Comment by KaelWD** [comment]
Please update your issue using the provided template for issues, including a reproduction link, or the issue will be closed.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
