### ISSUE TITLE
[Documentation] Can not access vuetifyjs.com website.

### ISSUE THREAD

**Issue by tzfun** [vuetifyjs/vuetify#20264]
### Environment

**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
Everything was OK an hour ago. Just access home page, got error message in console: 

Failed to load resource: the server responded with a status of 404 ()  /assets/index-DsbvDbUp.js:1 

### Expected Behavior
No

### Actual Behavior
No

### Reproduction Link
[https://vuetifyjs.com/](https://vuetifyjs.com/)

**Comment by yuwu9145** [comment]
It works, check your firewall settings

**Comment by tzfun** [comment]
I found the cause of the problem. It was blocked by Tencent Butler. It should be that Tencent Butler updated the security patch this morning, which made this js file enter the blocking rules. It is their bug. Thanks for your reply.
