### ISSUE TITLE
Error when loading the page in IE11 and Edge

### ISSUE THREAD

**Issue by endsalone** [vuetifyjs/vuetify#2027]
### Steps to reproduce
When the page is loading

### Versions
0.15.7 in IE11 and Edge

### What is expected ?
The full page
<img src="https://i.imgur.com/aLHZRzo.png" width="450"/>

### What is actually happening ?
The Page is crashing and it is opening this
<img src="https://i.imgur.com/ZZeAP6O.png" width="450"/>

I cant post it because its a secret projetct here in company and we have big company as Europa Films working with us in this project, we are working perfectly in other broswers, and just on Internet Explorer 11 and Edge we stuck in this ISSUE, we've already try to add  polyfill.io and babel-polyfill and got same error.

If can someone help us we appreciate.

We are using it with Laravel as backend, thanks for you time.

**Comment by johnleider** [comment]
I'm going to need some type of additional information. Without some sort of reproduction, I cannot help you, it's all hypothetical.
