### ISSUE TITLE
window is not defined 016.1 SSR

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#2029]
### Steps to reproduce
It looks like this issue is back https://github.com/vuetifyjs/vuetify/issues/191
Use the webpack-ssr template and update vuetify to version 0.16.1
I'm not sure if this affects it but I am importing the following components a la carte
```
Vue.use(Vuetify, {
    components: {
        VApp,
        VAvatar,
        VBtn,
        VCard,
        VDialog,
        VIcon,
        VTextField,
        VToolbar,
        transitions
    }
})
```

### Versions

Vue: 2.4.4
Vuetify: 0.16.1
OS: Ubuntu 16.04
Browser: Happens on the server, before the browser

### What is expected ?
It is expected not to blow up, works fine on 0.15.7

### What is actually happening ?

```
ReferenceError: window is not defined
    at server-bundle.js:175:2
    at server-bundle.js:164:46
    at module.exports.module.exports (node_modules/style-loader/lib/addStyles.js:67:0)
    at Object.<anonymous> (node_modules/vuetify/src/stylus/components/_app.styl?4cc8:12:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 01055ce4a5b3515c16fc:19:0)
    at Object.<anonymous> (node_modules/vuetify/src/components/VApp/VApp.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 01055ce4a5b3515c16fc:19:0)
    at Object.<anonymous> (server-bundle.js:1823:64)
    at __webpack_require__ (webpack:/webpack/bootstrap 01055ce4a5b3515c16fc:19:0)
    at Object.<anonymous> (server-bundle.js:1617:86)
```

### Reproduction Link

Can't make a codepen since it happens during SSR

**Comment by johnleider** [comment]
Are you using `style-loader` in webpack?

**Comment by amritk** [comment]
Yes, from the [webpack-ssr template](https://github.com/vuetifyjs/webpack-ssr/blob/master/template/build/webpack.base.config.js)
```
      {
        test: /\.styl$/,
        loader: ['style-loader', 'css-loader', 'stylus-loader']
      },
```

**Comment by johnleider** [comment]
Can you try removing that for me and try again.

**Comment by amritk** [comment]
Yup, changed to 
```
            {
                test: /\.styl$/,
                loader: ['css-loader', 'stylus-loader']
            },
```
and it works now

**Comment by amritk** [comment]
Hold on a second had the older version of vuetify loaded

**Comment by amritk** [comment]
Yup confirmed works with 0.16.1

**Comment by johnleider** [comment]
If you consider this resolved, close the ticket please, ty!

**Comment by amritk** [comment]
@johnleider should I make an issue on the template repo?
