### ISSUE TITLE
Feature Request: Add Modal Header, Content, Actions Components

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#203]
![image](https://cloud.githubusercontent.com/assets/25447231/23896165/5ac426f4-08e3-11e7-924b-3f53ac618b6a.png)

Regarding to this image you can see the modal has an overflow that looks ugly so what i propose is we can have these three components for the modal

v-modal-header
 This would be likely fixed to the top part of the modal without overflow
v-modal-content
  The content would have overflow on this area so it doesn't look ugly like on the presented image
v-modal-actions
  The buttons so it would stick on the bottom part of the modal rather scrolling it with the content

**Comment by johnleider** [comment]
Technically the modal is just a wrapper. You could use v-card, v-card-title and v-row(actions). Thoughts?

**Comment by ralphchristianeclipse** [comment]
@johnleider yeah maybe and add some css when inside the modal
