### ISSUE TITLE
Add non-`button` buttons

### ISSUE THREAD

**Issue by qm3ster** [vuetifyjs/vuetify#2030]
## Feature request

Add div-based buttons, with a named slot at root, for instance to put `input[type="file"]` inside them

**Comment by johnleider** [comment]
Please take the time to properly review the required boilerplate for a feature request. Take the time to let us know what you actually mean, because from one sentence, I have no clue. Once you have done that, I will re-open this.

**Comment by qm3ster** [comment]
Well, the only template questions applicable here are:

Q: What will it allow you to do that you can't do today?
A: It will allow making elements that look like `v-btn` but fulfill the role of `input[type="file"]` (open file dialog on click, represent selected file(s)/directories) even with js completely disabled. May also have other uses.

Q: What potential bugs and edge cases does it help to avoid?
A: A popular way of styling a `input[type="file"]` is by putting it inside another element and making it transparent. However, `input` elements are not allowed inside buttons, so placing it inside the button makes the input unusable on some browsers (eg. FF)

Q: How will it make current work-arounds straightforward?
A: Currently, I just did
```pug
  v-btn(@click='click') {{text}}
  input(type="file" multiple @change="change")
```
```js
    click () { this.$el.querySelector('input').click() },
```
Which works even on mobile, and I am completely satisfied, but that is only because I am not using this in a submittable form.

**Comment by qm3ster** [comment]
Actually, the slot would not even be needed in this case.
```
  input(type="file" id="fileElem" multiple accept="image/*" style="display:none" @change="change")
  label(for="fileElem"): div-v-btn {{text}}
```
This is another less hacky solution than the most popular one (why is it popular?!) that doesn't cause tooltips and other side effects. It doesn't work with `button`-based `v-btn` though, since the click is captured and doesn't hit the label.

**Comment by johnleider** [comment]
The structure of form components have been rebuilt for v1.1. You now have an entire `v-input` component to extend off of or use inline.

**Comment by PratsBhatt** [comment]
@qm3ster, I am currently trying the use the input field as well. Would be able to provide a code snippet that I could use.
I am new with vuetifyjs and currently trying to make this working.
Also if you had tried using v-input tag it will also be helpful if you could provide a light on it.

`<v-input type="file" accept="image/*;capture=camera"></v-input> `
I tried to extend like this but no luck. I tried to find tutorials on extension as well but had no clue how to do it. It would be really helpful if you could throw some more light on this matter.
Appreciate your help.
nice work!

Thanks and Regards.

**Comment by PratsBhatt** [comment]
@johnleider thank you for your reply. I am trying to use the `v-input` to use the input tag but was unsuccesfull. 
`<v-input type="file" accept="image/*;capture=camera"> </v-input>`
I tried to use the `v-input` tag in the above fashion but it didn't work as there aren't props for the same.
I am new to Vuetify.js and not aware how to extend the component in a correct manner. 
Would you be able to throw some light on how shall I approach this.
I was able to use the solution described by @qm3ster . Thank you for that.
Appreciate your help.
Nice work!

Thanks and Regards.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
