### ISSUE TITLE
[Bug Report][3.6.14] Autocomplete menu does not open after first click when items are loaded asynchronously with `hide-no-data` and `hide-selected` options enabled

### ISSUE THREAD

**Issue by canbax** [vuetifyjs/vuetify#20301]
### Environment
**Vuetify Version:** 3.6.14
**Last working version:** 2.6.12
**Vue Version:** 3.5.0-beta.1
**Browsers:** Chrome 127.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- open the autocomplete with a selected item
- click on the selected item to load items async
- The menu does NOT appear when you first click. It needs to be clicked again

### Expected Behavior
the menu to be open after items are changed

### Actual Behavior
the menu doesn't open

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkctugzAQRX9lxAYiQRJ1iQhK1G66TrsKWTh4UlANRniglSL+vX6EVzdgH8/cude+PDzV5rtT02z7Dr3YSwirRjDCNKsBkj5iHclcaoaEBgH0USU5ikPm9Ux0qDLP8bjUvUpj+x9pUXKMahlxRmxBFArMCblDgt2s4BveWSdo7D1WslPI5U+tz4Rk/H1WTpPd2txo+EY1HHNR5t+6qUWFdCadJ/NSuzFtukRXJ7tFVr1VeVs2ZGXwt5EtAXd24OHsmAgxBBs4pBA8GYBNG8PFv0vpX8MRu7uJweInHTbPRYVUSK5PJ5UpnZafIEAuayUFboX8CnxFTJsylW6ov5kLdbKPskLZUeAMLkQAqCjV1vbAQTv9PJ/8EPzXoqyZWVjny/rVWNdnxiJfjhxCeNnv9xMZpuzzra/TWBvuYrQPO/bf4exx5WmUdv/BvN30Wt4Q1p0Q9nP9AwSn3Z4=)

**Comment by yuwu9145** [comment]
Use `menu` prop to manually open the menu after loading finishes

```vue
<template>
  <v-autocomplete
    v-model="values"
    :items="items"
    :menu="menuOpen"
    hide-no-data
    hide-selected
    label="Default"
    @mousedown="loadItems"
  ></v-autocomplete>
  <v-btn @click="resetState">reset</v-btn>
</template>

<script>
  export default {
    data: () => ({
      items: ['foo'],
      values: 'foo',
      menuOpen: false,
    }),
    methods: {
      loadItems() {
        console.log('start load items')
        setTimeout(() => {
          this.items = ['USA', 'China', 'foo']
          console.log('items loaded')
          this.menuOpen = true
        }, 2000)
      },
      resetState() {
        this.values = 'foo'
        this.items = ['foo']
      },
    },
  }
</script>


```
