### ISSUE TITLE
[Bug Report][3.6.14] VMain interfere with Nuxt SSR useFetch

### ISSUE THREAD

**Issue by AlexMili** [vuetifyjs/vuetify#20300]
### Environment
**Vuetify Version:** 3.6.14
**Vue Version:** 3.4.31
**Browsers:** Firefox 128.0
**OS:** Mac OS 10.15

### Steps to reproduce
- Create an endpoint at http://127.0.0.1/api/items returning array of object with `id` key:
`[{id: 1}, {id: 2}]`
- Run applications using `yarn run dev`
- Go to `localhost:3000/`
- Open Network inspector and see requests to the server being done while SSR is activated both on nuxt and vuetify

### Expected Behavior
SSR configuration should be respected when `NuxtPage` is encapsulated within `VMain` in `app.vue`.

### Actual Behavior
SSR requests using Nuxt's `useFetch` or `$fetch` are executed client side even when SSR is set to true both on Nuxt's side and Vuetify's side. This only occurs when `NuxtPage` is encapsulated within `VMain` tag.

### Reproduction Link
[https://github.com/AlexMili/vmain-nuxt-error](https://github.com/AlexMili/vmain-nuxt-error)

### Other comments
I don't know what is interfering but at least making clear in the documentation that `VMain` produce this error.

**Comment by userquin** [comment]
move `v-app + v-main` to `layouts/default.vue` using `<slot></slot>`:
<details>
<summary>layouts/default.vue</summary>

```html
<template>
  <v-app>
    <v-main>
      <slot></slot>
    </v-main>
  </v-app>
</template>
```
</details>

then update your `app.vue` to use the layout:
<details>
<summary>app.vue</summary>

```html
<template>
  <div>
    <NuxtLoadingIndicator />
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
    </div>
</template>
```
</details>

**Comment by AlexMili** [comment]
Looks like it does the trick, thanks!

Do you know why it is happening ?

**Comment by userquin** [comment]
I guess it is related to suspense, iirc v-app/v-layout (and maybe also v-main) also  using suspense and it seems they are breaking nuxt page router logic.

**Comment by userquin** [comment]
It is no vuetify, if you remove v-app and v-main from the app.vue same behavior, it seems a bug in nuxt.

**Comment by KaelWD** [comment]
There's nothing special about VMain it's just an async component (or was until 3.7). If async components can break this then it's either a problem with nuxt or vue, or should be documented by nuxt.
