### ISSUE TITLE
Input Masking - Cursor Issues on Android Oreo

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#2031]
### Steps to reproduce

1. Using Load [the Google Contacts example](https://vuetifyjs.com/examples/layouts/google-contacts) from documentation.
2. Click the FAB in bottom-right corner, to add a new contact.
3. In the phone field, type the number "1234567890"

### Versions

Vue 2.4.2
Vuetify 0.16.1
Android 8.0 / Chrome 59

### What is expected ?
A masked version of the number "1234567890".

### What is actually happening ?
Masking characters cause incorrect cursor position. If you don't manually adjust the cursor position in between number-clicks, your final/formatted number will be "(234) 789 - 0651".

### Reproduction Link
https://vuetifyjs.com/examples/layouts/google-contacts (on Android/Chrome)

![screenshot_20171005-195022](https://user-images.githubusercontent.com/13950848/31258824-9ea69efe-aa07-11e7-874f-a874196e43b4.png)

**Comment by KaelWD** [comment]
For some reason this works fine if the input type is `tel`

[`vuetifyjs/docs@93103b9f`](/vuetifyjs/docs/commit/93103b9f6cc05c6e760fad2fbb7aa8320c628453)
