### ISSUE TITLE
[Bug Report][3.6.14] VPagination unusual jitter in flexbox layout

### ISSUE THREAD

**Issue by molon** [vuetifyjs/vuetify#20321]
### Environment
**Vuetify Version:** 3.6.14
**Vue Version:** 3.4.36
**Browsers:** Chrome 127.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In the given playgroud link, refresh several times, you will find that the display has abnormal jitter. And the devtools console will always report an error 

```
Uncaught TypeError: Cannot read properties of null (reading 'includes')
at Object.on_error (index-B-SM1cih.js:588:226)
at zre.handle_repl_message (index-B-SM1cih.js:572:1066)
at handle_event (index-B-SM1cih.js:572:122)
```

If you give it a long enough width, this problem will not occur.

### Expected Behavior
normal display

### Actual Behavior
abnormal jitter

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNUNtqwzAM/RXhl25QL7DBHkpa2HcsezC2mhoc28hK1lL671UTcnkxOhd0rPN7V4Vs9ZPzx9CjOqiascvBMJ6aCFA7P4ANppRjo5w+B7yCCb6N2mJkJGiN/m7U6BX3oEs2FulUV8u4SNm0Phr2KU4UwKFc0r8+eyqsJYNfFpQgph4btbgo9dGhO+4aZT3ZINpuER3G4vk2iqmTSN6ogvyA2qaQSPZm8p2h22Z1wNjyRaSvlRx0lxyGl1++M/PjSesJUzuV1CNTXW1KE1gs+cyjBa85EYPDs+kDw31a5gybt/cZARByT3HFAK/oA3zuZ+YxDY+REFBXS4h67GMfwvj8PQF/r5M1)

**Comment by KaelWD** [comment]
This seems related to #18853, at certain widths it has `maxButtons = 4` and shows `1 ... 2 ... 3` which makes it too wide for the space so it goes down to `maxButtons = 2` and `1 2 3` but now there's more room so it expands again.
