### ISSUE TITLE
[Feature Request] Add responsive rounded value

### ISSUE THREAD

**Issue by Harm-Nullix** [vuetifyjs/vuetify#20328]
### Problem to solve
When using SSR, we want to use CSS classes instead of setting values dynamic. The rounded values are not responsive, what makes it impossible to do this.

https://play.vuetifyjs.com/#eNq1Uj1PwzAQ/StHBtJKpKk6MJS0AomBgU4dQCIMJnbBkr90tkurqv8dJ07TBqmVGJAix/f8dO+9073tEotV/mDMaO1ZMk0Kx6QRxLF5qQCKdUaMaa5NUWnlCFcMWyiCBClUWmiclQkyWiaA2ivKaKg3okw6ckfPHHeCzV+fD0wo8t5L176FT/WsIRVDqASxNiiYbTYJkvkfLIGkmZXnjR1hgPly0ZnUChaP194A5TYMaQsDpaHy1mkZ7Qz7MY59/juQlRcD/QqxXPRCXEhwzndT9pahRuKuFPnJDoXSVsiNA8ucj6vEpdHoYAfIVrCHFQbxNKxfWtMhxFTWgbSfMKsZg/SJCaHhRaOgV+mwFogt2/Zu2/q8l4xyAgPJVfbNqfuawu14bDZD2EXXo3YGYVbhO6AAHxopwwwJ5d5OYWI2cBVNEuXuImtf/8IRxFvBZH+jvBDN8f4D9/ULDw==

### Proposed solution
Add `responsive: true` to https://github.com/vuetifyjs/vuetify/blob/e1ed75f684bf413147d3988aca8ee7d7d725b78d/packages/vuetify/src/styles/settings/_utilities.scss#L368 and beyond is probably the fix?

I do want a workaround solution to do this, but I do not know how to target all the `rounded-*` classes in a way that I can add those extra classes in my own scss file

**Comment by KaelWD** [comment]
Utilities are merged so you can set this yourself with https://vuetifyjs.com/en/features/sass-variables/

```scss
$utilities: (
 "rounded": (responsive: true),
),
```

**Comment by Harm-Nullix** [comment]
Alright! Very cool! Thanks very much Kael!
