### ISSUE TITLE
[Bug Report][3.6.15] VNumberInput - when typing using keyboard @update:model-value is not triggerred, counter not visible when clicking

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#20337]
### Environment
**Vuetify Version:** 3.6.15
**Vue Version:** 3.4.38
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. write numbers to VNumberInput using keyboard, not using buttons.
2. expecting to see validator counting or rules updating immediately
(@update:model-value is not triggered)

I have also found that counter is not visible when clicking on buttons up/down - I canot say if this is intended behaviour but I would expect to see it there - to have app consisent - it is there in other  types of input. 

Thanks.

### Expected Behavior
1. trigger update model instantly as in VTextField - because counter is not counting and rules validator not working immediately.

### Actual Behavior
1. update model is triggerd after leaving field  and it is clicked outside VNumberInput 

### Reproduction Link
[https://play.vuetifyjs.com/#...][(https://play.vuetifyjs.com/#eNpdj8tuwyAQRX9lxCatVIduuonsqP2AbrupuyD2RLUEA+LhjcW/Z4AkirKxPGcucO7vJoKf5Jdz+zWhOIg+onFaRTyOBNCvnXKu/tZhshTVQuiviGFwio6wbUDm5CFn6GVF98DaUTIn9N1CLkX4TG7m6w/Gzqi7VemEwyj+Fc0avwv7KWgUMNlEET0vP3iSNwn5bFFIk+zlgzyPYfKLixAwptZhMc76CBt4PEOGs7cGdtx7V+LAL1KIrcdQIi/vr4+LZ0cOVX0YuH+zK2f3V9iWheei1mRYQ+Q3SlrXz98FGl2BZA==)](https://play.vuetifyjs.com/#eNpdkc1ygjAUhV/lykJ0RkSXZcBpH6BdtDPdqIsAV2UmhDR/G+Tdmx8sVBYh+e5Jcu7JsY+kqNI3zrdGY5RFucKWU6LwcGIAuUkI537qF1XHFGkYihF5yHRbokgaxrV6YACTtF2NNPNjYgjVWJwi1pbiFE0qSkqkln/4M+aVV81ra+Np/42wmuK7Y98OzXdUnWYKhVXtd3OeCU1RWuz/UyWdmpCcsAN8otRUZdD34HzCMECe+tIYQPqcgCMhoDydBWeXshINVyBR6ZBf0/JOKOhB4AUGuIiuhdhmHju5M8+kCtcWTrJ6+fvWc4XvYZQcgy0DxQEWCwP3O8QhSGikVfzoRmAdbybZo+GVgeUSvpRo2HVl1luK7KpukBew363n57Ta3lmixVDdiCCVDVhCJ8C6kOHk8z9/zw9krfq3cx77cL1rcjvCUHR8cBmG1KzNaNgwTakfzr/Nc9bN)

**Comment by yuwu9145** [comment]
This behaviour is intentional: https://github.com/vuetifyjs/vuetify/issues/20171

**Comment by KaelWD** [comment]
Perhaps a middle ground would be good? `if (isValidNumber && clampToRange(value) === value) emit()`
