### ISSUE TITLE
[Bug Report][3.6.14] v-radio-group overstepping and triggering model changes for nested checkboxes

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#20331]
### Environment
**Vuetify Version:** 3.6.14
**Last working version:** 3.5.16
**Vue Version:** 3.4.37
**Browsers:** Chrome 127.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Go to the sandbox link.
- Click the button to open the modal.
- Check the box in the modal.
- Notice the radio value is reset to `true`.  

We discovered this after upgrading from v3.5.16 to 3.6.14, so it broke somewhere in between those releases.

*Note: this was previously reported here: https://github.com/vuetifyjs/vuetify/issues/16245 and https://github.com/vuetifyjs/vuetify/issues/17570 in version 3.0.4 and 3.3.3.  Those were closed as duplicates with a rough workaround that doesn't really work in all conditions.*

To be clear: the workaround mentioned in those other issues doesn't scale well.  Do you need to wrap the checkbox in a group in _every_ possible checkbox that could be used in this configuration?

### Expected Behavior
The checkbox to not update the radio-group model.

### Actual Behavior
It's updating the radio-group model.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFkk1vgzAMhv+KxaWbVMYd0WqTdq80TbuMHQJxW9SQRCFhlSr++/IBBKROvSDex69jO873LelUnb1J+dIbTPKk0NhKRjTuSw5Q9CmR0v96UQuuScNRjchDRWgj0pMSRkKftoIi25WJp1+EGSyT2R39wEjlfR9eHbi1Qe/slgmn9kU2etfplebwWrOmvjinRP7eECZOsAOtfLGDZS7XGteZNBhjjzF71WMY9Yz1pRLXhd0jpLbRqXlPoHW9Z8tatnoo9njyz1+xmFw79d/kd9PPCpdXp4O+c8RMwqqmpVq63qojYelFtngMVna1aqT2JrxKoTRQPBLDNNzCYZRo8vQ8KQCF2igetSXzq8hhY9e82cZY3EYOR8I6tLEYHS8/hgIews/ggRVFNneZDFtuGPOfnz+Ywul4)

### Other comments
You may wonder why you'd want a layout like this.  If you want the radios to represent the selection of a user input where they need to fill out additional information, you need to be able to inline other components under the radios. 

In our case, it's an RTE with a button to open a modal to insert a link.  Inside that modal is a checkbox to "open link in new window", which resets the radio selection, and subsequently unmounts the input/dialog.

**Comment by gabaum10** [comment]
I take it back. This didn't work in 3.5.16.  This is essentially. duplicate of the linked issue, which was closed with an unscalable workaround.  

I'm going to leave this open to see if there is any possibility of reconsidering here.  This just continues to be something we run into in one specific place in our UI.

**Comment by KaelWD** [comment]
#16245 is still open.
