### ISSUE TITLE
[Bug Report][3.7.0] The v-avatar border property doesn't seem to be working properly

### ISSUE THREAD

**Issue by AndyBeat** [vuetifyjs/vuetify#20345]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.38
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Expected Behavior
No border when v-avatar is set to border=false

### Actual Behavior
The default value of v-avatar border is a border, and setting it to false also has a border

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9jUELwjAMhf9K6Elh2vuoA3+H81C3DIS6hSwtQul/t7ZMPIiXJF/e471LVCsP+kx0DB5Vq4zgg5wV7PoZwISDJSpnhWDFMrS3hUfkU68m61bsVWf0Jv4xC/sf3oKlxOiv8ozrwHeSYsInLSww4mS9E4i1ZMwhu/1GAIzieYaY6iM1753B6E+USs3snSvj+gIBO1SX)

**Comment by Drillan767** [comment]
It's interesting to note that borders are also displayed when setting `:border` to undefined

**Comment by wyhsunflower** [comment]
I already fixed this issue and raise PR in a week.

**Comment by ricardo17coelho** [comment]
Maybe as "quick fix".. the border is not displayed if `:border='0' ` 😅
