### ISSUE TITLE
[Bug Report][3.7.0] VTab color prop not working with prop href & to

### ISSUE THREAD

**Issue by xiaofengorz** [vuetifyjs/vuetify#20348]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.38
**Browsers:** Edge 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
See the playground link.

### Expected Behavior
Color the VTab according to the color prop.

### Actual Behavior
Color prop doesn't work when prop href or to is attached to the component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UNFqwzAM/BWh7bFOBhljlGywx33DPGiaKI2Zawdb8TpK/32q07BBoS9CJ92J030cMYa2fBvHIk2Ea6yZ9qNtmF61A6iTigMRA1lKDRvvXjQ+aczLvOZmG2cA0HrrgxCM68zOa1zmjg6sTJvF+86oJgT/rYLZDay23nZSDspPbI2jP9UYKF2rLPW3RHEQTmZeXF2cLl5hCNTLwTuNkFQ/2wXjoHqQyfqLfs6Dc8tiWvrNuwQC90dz2sjbdZmvLO/PKM5RCchZCarLfyniaYVV8VhUz7hyk7Wfv+pEdp8=)

### Other comments
Issue #18756 mentioned the same situation. But it hasn't been solved so far.

**Comment by KaelWD** [comment]
That issue shouldn't have been closed.

**Comment by david2242** [comment]
For me it is an issue as well. 

`  <VTab color="red" value="myValue" to="myRoute">
{{ someText }}
</VTab>`

Color is not red unless i delete the "to" property.

I recommend solving this.
