### ISSUE TITLE
[Bug Report][3.7.0] VTreeview opened prop does not work when combined with return-object

### ISSUE THREAD

**Issue by jelle-eastground** [vuetifyjs/vuetify#20350]
### Environment
**Vuetify Version:** 3.7.0
**Last working version:** 3.6.15
**Vue Version:** 3.4.38
**Browsers:** Firefox 129.0
**OS:** Windows 10

### Steps to reproduce
Load the example in de reproduction link. The opened prop is initially filled with some item id's (or even item objects when the opened prop value is changed to opened_by_items).

### Expected Behavior
A tree with 'Documents', 'vuetify' and 'src' initially opened.

### Actual Behavior
All nodes are initially closed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVttum0AQ/ZURL04kDG3TxC3Clqr2F6o+2FG0hom8DeyiZXASWfx7uQSWBYJD1beGF5azc85cjr2wPVmpCtxvSeIcM7Q8yyeMk4gRbnYCwD8uWZJUy+ohkIIYF6heoAokhXjk+NhAAB4vVNL1zqruO0vvlMDyyKIMy92wu+XJBAWGBV4v7vbPdzw02AopU2Ip978xoAbe+K6uQdeVbAwZD04nMBDIc99teusTyrr7lBIzSGVicyIlUg/MdzuDLB7TQPGEqiB8SqQiCPGeZRHBqRaLZSYIw4vLBgBwXfgpAhnHKAjowFMgCTF7wGKM8CjVg9OJLPedulpYw/bahhsbVrd1RG7X95AR86DIsd7ARZunN6iW+0IyAurBbLUnrUplb+jBdUsrL+IUoQeLHzLIyj5S8BZGQHDgUahQGKID4Ub8xuB2ExQ/X+L3z335yRSjaZpUq4FON13xrxlLdTZdlbLS/2K3YlyE+AQeULporRonfdWkvZSUkmLJJFGbqK9hZD/KjOjudncG1pvunHFmnvFDN844MW36XAf+Yvr/aKZm4xNNvz7POc3ObHS8DY2+4bz4ONpg8UaKeMCISzHjyKgEP+niv7MIRchUUXtxLL/W7VWHcFAyxunwzzr8F+5TkioeJ7zZ4/cj8/84Mhs0v6wWefmZ0H4YWLktsiiyrStn5Xywbv8AbM1ldw==)

### Other comments
Even when return-object is used, I expect that I can use item id's in an array as value for the opened prop. When using a v-model:opened combined with return-object, the v-model:opened is filled with complete objects. Even when I use those item objects in the opened prop, those nodes are not opened. This can be verified by using :opened="opened_by_items" in the example of the reproduction link.

This issue is related: https://github.com/vuetifyjs/vuetify/issues/19414

**Comment by yuwu9145** [comment]
Need to make sure assigning the same object

https://play.vuetifyjs.com/#eNqNU9tu2zAM/RXCL2mBZNmt6yY4AYbtH/bgBIVisagGWRJk2m0R+N8rK5Flx0jRPFjUIc8RdRQWx6x25fq3tZ/aBjOW5YSVVZxwu9MAebvi1oYwbEqjiUuN7gwFkBxiK/E5QgBMepV6s8vCustSpgdWLVcN9lkxTrWryghUzFjUKHz6FDwcXh9mMg6pcXplDv+xpAhv83VqJjVotyMhUTM4HmGCQNfl63jJS0J/8iWlxyak/uCpNT1yci5fjxz127p00lIo8pSagiU1bKA4aR1jH1Iw+LKMO5KkkMHCv5SSJSfpucAWQ758kko41CzqBK0g8nU5sP9whVpwBwx8dwvoBn4s/jYqfnKmwuul31PpPzzUZFw1L96fo4hMrnc3u95fUzYVavrA3VJ4EvsxajAJ+n81ycfXsdxVyZlslL6fcMfyfngupd+VT+79TO5JLfDFW0f11OYp4VciHIyhmhy3V0nR9vibVoyz155q33/wxRpHIPCRN4qiOYITZ3BzC5st3AyGXUxZcbf0TwL36azZVBVhLT7vU805E5bYzm0Iun6UhuHJuqVulAqf/Rs1oVmO
