### ISSUE TITLE
[Bug Report][3.7.0] v-carousel-item can't use an alias as src if it comes from an object

### ISSUE THREAD

**Issue by EDM115** [vuetifyjs/vuetify#20361]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.38
**Browsers:** Chrome 129.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a `v-carousel`
2. Make the `v-carousel-item` use a v-for and takes its values from a variable
3. The field for the image have to use an alias (see `vite.config.js`)

Repro link is concise enough, but to be put clearly the `vite.config.js` should have :  
```js
export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url))
    }
  }
})
```

and in a vue file :  
```vue
<template>
  <v-carousel>
    <v-carousel-item
      v-for="b in a"
      :key="b.id"
      :src="b.img"
    />
  </v-carousel>
</template>

<script setup>
import { ref } from "vue"

const a = ref([
  {
    id: 1,
    img: "@/assets/test.jpg"
  },
  {
    id: 2,
    img: "@/assets/test.jpg"
  }
])
</script>
```

### Expected Behavior
The src prop should resolve the image with the alias from an object

### Actual Behavior
The image with alias from an object isn't resolved. This is even weirder as if we put the alias directly as src's value, it work (as demonstrated in the repro link)

### Reproduction Link
[https://github.com/EDM115-alt/repro](https://github.com/EDM115-alt/repro)

### Other comments
I guess it's the same problem as #3745

**Comment by KaelWD** [comment]
https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md#asset-url-handling
