### ISSUE TITLE
[Documentation] Documentation website is down

### ISSUE THREAD

**Issue by eldhosereji541** [vuetifyjs/vuetify#20367]
### Environment

**Browsers:** Chrome 127.0.6533.120
**OS:** Windows 11 Home
### Steps to reproduce
just open the documentation website

### Expected Behavior
open and load contents normally

### Actual Behavior
blank page, error on the console: 
GET https://vuetifyjs.com/assets/index-CmOmPrj2.js net::ERR_ABORTED 404 (Not Found)

### Reproduction Link
[https://vuetifyjs.com/en/](https://vuetifyjs.com/en/)

**Comment by maniper** [comment]
I encounter the same issue. I cannot view the documentation anymore.

**Comment by b-maslennikov** [comment]
Looks ok to me

**Comment by KaelWD** [comment]
We've been having intermittent CDN problems in some regions:

![Screenshot_20240821_202402](https://github.com/user-attachments/assets/9f8cb62d-73f4-49ce-86bb-aed32c9ac2f5)

Does https://vuetify-3-jojqdczgg-vuetifyjs1.vercel.app/ load? If not you can try running it locally: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/pages/en/getting-started/contributing.md#local-development

**Comment by eldhosereji541** [comment]
works now. thanks for the support

**Comment by steeevio** [comment]
Down for me
request url: https://vuetifyjs.com/assets/index-BohZX1iR.js
x-vercel-id: cdg1::zwwd4-1725372979425-a3884859715e

**Comment by joel-wenzel** [comment]
Also me:
request url: https://vuetifyjs.com/assets/index-BohZX1iR.js
x-vercel-id: iad1::89lmz-1725372978834-79c720d0e137

**Comment by userquin** [comment]
Same here:
```yml
x-vercel-error: NOT_FOUND
x-vercel-id: cdg1::zwwd4-1725372979425-a3884859715e
```

**Comment by KaelWD** [comment]
Does https://vuetifyjs.com/assets/index-BohZX1iR.js load in an incognito window?

**Comment by jacekkarczmarczyk** [comment]
it does
![image](https://github.com/user-attachments/assets/ad32ae9c-2c9e-4359-87e4-161987fefd76)

**Comment by KaelWD** [comment]
@jacekkarczmarczyk were you having problems though?

**Comment by jacekkarczmarczyk** [comment]
> @jacekkarczmarczyk were you having problems though?

Actually no, I've just tried if .js opens in non-incognite mode and it redirected to https://vuetifyjs.com/en/assets/index-BohZX1iR.js/, but in network tab (when I'm on the page) it loads fine

**Comment by steeevio** [comment]
No, still 404 for me in incognito

**Comment by userquin** [comment]
@KaelWD everything inside the assets folder shouldn't be immutable? I'll check the sw handlers. Looks like the sw has old version but requesting previous `/assets/index-BohZX1iR.js` and it shouldn't, maybe wrong `globPatterns` or excluding `assets` to generate the revision:

![imagen](https://github.com/user-attachments/assets/911b9a95-042a-4818-a4c6-dcf276fbded6)

**Comment by userquin** [comment]
forgot previous comment, I guess the problem in vercel chache headers...

**Comment by KaelWD** [comment]
Yes BohZX1iR is current. Is the page loading for you now @userquin?

**Comment by userquin** [comment]
no

**Comment by KaelWD** [comment]
How about https://vuetify-3-eod0x2mgd-vuetifyjs1.vercel.app/assets/index-BohZX1iR.js

**Comment by userquin** [comment]
yes, it is working:
![imagen](https://github.com/user-attachments/assets/37e3a86a-beb2-4d0d-8bbc-5a426e85a698)

**Comment by steeevio** [comment]
Yes, that looks good

**Comment by KaelWD** [comment]
But https://vuetifyjs.com/assets/index-BohZX1iR.js is still broken? I'll try purging cloudflare, it shouldn't be caching 404s though.

**Comment by felicienfrancois** [comment]
I have the same issue on chrome right now.
Work correctly on Firefox

**Comment by steeevio** [comment]
All working for me now

**Comment by KaelWD** [comment]
I didn't even touch cloudflare yet lol.

**Comment by brettvd** [comment]
I'm still seeing the issue. Receiving a 404 on the GET for an index file. Different index file name (index-D0V9Cts6.js). I tried using the same direct URL @KaelWD provided above, but replaced with my file name and that didn't work (not sure it should, though).

I've tried Incognito and tried other browsers, all get the same error.

**Comment by KaelWD** [comment]
There has been another deployment since then, the new one is https://vuetify-3-ngene0f1n-vuetifyjs1.vercel.app/

**Comment by reno184** [comment]
Me too, on Edge on firefox, it's impossible to navigate into the documentation, it's a critical a bug 
![error_vutify](https://github.com/user-attachments/assets/c106a4eb-f93a-4054-b513-33133e36068d)

**Comment by j-tap** [comment]
https://vuetifyjs.com/en/api/v-app-bar/
<img width="713" alt="image" src="https://github.com/user-attachments/assets/2439fc81-9567-4ef1-a06f-9e4235f1f076">

https://vuetifyjs.com/en/
Correct display

https://vuetifyjs.com/en/api/
Correct display of 404 page

My location: Ecuador
Using vpn doesn't change anything

**Comment by sbglasius** [comment]
Denmark:
```
Request URL: https://vuetifyjs.com/assets/index-DK_ffwoj.js
x-vercel-error:NOT_FOUND
x-vercel-id: cdg1::tdtnk-1727958708330-5705deab4c5e
```

**Comment by KaelWD** [comment]
We no longer use vercel.
