### ISSUE TITLE
The v-slider component requires the present of v-app or a non-body wrapping element with the [data-app] attribute.

### ISSUE THREAD

**Issue by webmasterslava** [vuetifyjs/vuetify#2036]
# Issue

This issue happens when Vue app is mounted into virtual DOM element, that is not yet inserted into browser's DOM.
```
The v-slider component requires the present of v-app or a non-body wrapping element with the [data-app] attribute.
```
# How To Reproduce

index.js
```
$(document).ready(() => {
  let $elApp = $('<div id="my-app"><div></div></div>')

  new Vue({
    render: h => h(App),
    el: $elApp.children().get(0),
  })

  $('body').append($elApp)
})
```

App.vue
```
<template>
  <v-app>
    <v-slider v-model="value" thumb-label step="10" snap></v-slider>
  </v-app>
</template>

<script>
  export default {
    data() {
      return {
        value: 50,
      }
    }
  }
</script>
```

# How To Fix
Moving `$('body').append($elApp)` above creating Vue app fixed the issue.

```
  $('body').append($elApp)

  new Vue({
    render: h => h(App),
    el: $elApp.children().get(0),
  })
```
But what if I need to render Vue app on document ready event and insert it into browser's DOM in some time in the future?

**Comment by jacekkarczmarczyk** [comment]
There is a problem with iOS (console warning was added later):
https://github.com/vuetifyjs/vuetify/commit/c89ba842d124269fb74c94a13b9b52f7c64f2971

**Comment by johnleider** [comment]
I'm updating the language to correct the miss-spelled word, but I do not see a bug here. Getting into Vue with jQuery as well is something that I don't think should be the responsibility of the framework to work with.

**Comment by webmasterslava** [comment]
jQuery is just for example here. We can replaces it by Javascript.

```
let elApp = document.createElement('div');
elApp.innerHTML = '<div></div>';
elApp.id = 'my-app';

new Vue({
  render: h => h(App),
  el: elApp.firstChild,
})

document.body.appendChild(elApp)
```

This issue happens when Vue app is mounted into virtual DOM element, that is not yet inserted into browser's DOM.

It works perfect without Vuetify, therefore it's not Vue issue.

Also it works perfect with Vuetify if Vue App is mounted into element that is already inserted into browse's DOM.

```
let elApp = document.createElement('div');
elApp.innerHTML = '<div></div>';
elApp.id = 'my-app';

document.body.appendChild(elApp)

new Vue({
  render: h => h(App),
  el: elApp.firstChild,
})
```

**Comment by nekosaur** [comment]
What is your real life use case for waiting to insert it into document?

**Comment by webmasterslava** [comment]
Inserting Vue app into WordPress Media Library lightbox on Edit Post page that appears when user clicked Add Media button.

**Comment by webmasterslava** [comment]
just updated from 0.15 to 0.16 and it already fixed there
