### ISSUE TITLE
[Bug Report][3.6.15] [ v-menu] activator-props not reactive

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20370]
### Environment
**Vuetify Version:** 3.6.15
**Vue Version:** 3.4.27
**Browsers:** Edge 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
change select to an other item than 'end'

### Expected Behavior
The button should be enabled and the output should be false false

### Actual Behavior
The button stays as disabled and the activator props are out of sync with attrs. Output is false true

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vd2O0zwQfZVR9ElZpCb5xCIhlXb5vwDxJ+Buy0WaTBezjh3Zk25R1Hdnxom7aRcQXCBVje05M3NmbB9f9ol3VfG0bfNth8k8WRA2rS4JL1YGYFGrLVS69H65Sgh3lFVoCN0qCWYGbDOPGiuCbdbYGjXjtK1KUtasEpgrDie+cc3zoi7XAffmgLtYFDHOkLbgvMPouW1amEf3k+i18uVaYz1ZhuUSUjR1Co+BXIcwh02pPTK84IiLYlLfwldOtQQeqWuZlrmSKpniWJxqWusIAoWNsw2keSETaVUqkBHQO9zsR0Q0AVRcLckA4FD9Ei5Tsm06g3RtiWwjI0+lIxkIbf4MLU6/nIQ59AA43VkA35OChiKYcjJj8gzfqKv8m7eGd7OXGKukYtJKo3vfjnswh2ARW6m1vXkd1qRfs7hefcXq+ifr3/xO1lbJB4ce3ZY7e7BxIVdIg/nlp3d8XiZGPh6dZvRvjB/RW90NuyuwZ52pmfYEF9i+Cm1X5uqzf7kjND4WJUQFuQ/4VcKbIfv1q9Jv6Z7n58FvZfjHfRw2NmvK9qSTg+E4DGcZ6H4lav28KKrasBtfBrV1uUEqTNsUTxhWuM6QajCrbfPkPH+Q33/IJ93TdD1H32RrZ2+4uRxlUjsHILX5/ge5RiSneJj/P2QYlzK+fF5S3AldhM10meODhU6a/mclnbgdlXViu1PaUc9Fh+LtuiNEff9fSeR8Hq/8np2C/DRouiOBaJ1tfT6VibIitS3JuizYGDMEu1WxmItVzGtLtx6M7SF4MdEIFzpDlmM2oyCuyfCt1cG5daopHe8Z1KW75vBrZUSugjsHhBc8qO2NYc0LnpHRVKcOUqu5qQcO4zwTieXAm5DvTGYz4CS4u8cfCAIsTbjG72wPhkkhx2EyUqTxou+DWx5msN8LtVPMgcXUdiA/oSoT2aO/EV/xG3RvaP0Satwogx9kdjZevLjDc/hEjsUgHOY9S2IwR9kcHiC4vC24h1DBHNLnWlXX8BbTUTD+lR3uTxGs6xPRjm04fX3i0zJWLhfDGn4YYHxoRtl5FE8H7gKe0WWnw/fIKzYNwJRN4MamdOQkTZu+I/uZ6bQOf19+AEVksDc=)

**Comment by KaelWD** [comment]
attrs isn't reactive: https://vuejs.org/guide/components/attrs.html#accessing-fallthrough-attributes-in-javascript

**Comment by mueller-jens** [comment]
But why attrs value is changed, but not the activator props 🤔

**Comment by KaelWD** [comment]
VNode props change always triggers a render, but that doesn't continue to children. If you create a new object on each render with `{ ...$attrs }` you will see the prop update triggering VMenu render too.
