### ISSUE TITLE
[Bug Report][3.7.0] VTreeview opened prop 2-way bind issues with return-object

### ISSUE THREAD

**Issue by robertzak** [vuetifyjs/vuetify#20376]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.38
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click the close button. The tree will close
Click the open button. The tree doesn't open

### Expected Behavior
The tree should toggle the Application node open when clicking the open button

### Actual Behavior
Nothing happens despite opened being set to the exact object in the item list that should be open

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNk0uPmzAQx7/KiEt2paT0/UAkarW999hDglYGZrVujW2ZgWYV8d1rnBhDELvLAcbz+DHzt2Z/impTxD+0ftM2GCVRSlhpwQh3BwmQthumtTPdoVCSGJdoLi7nJIPYcvznXQAJt5R6e4jc9xCFSO/YtEw02EfLcajdVKpEkSiNEksbPhv3+dP9DGOQGiM3Kv+DBXn3Lo1DM6FBvbsCJXA6wZUPui6N/aBuqpwkEB7JNvLL5h4i+F4IXvydNwZb2Dtj/zbLbF68gLkTqsYXOOP6fpyp4L3nfB9pPLone6wLwzW5JFtSkxPaEc+sk2+Jlwm8W/sTcRKYwMrev+2JEbe1kKyGePHIRWlQJp7jWA7yfj1U3zGBsmQGErDdraAb6n3yh1Hyo1EVLqd+DKm/Ma9JmWqenF0s75mM92k23k9VNBVKesVswTzDPo8aDEC7K8Qfnsa4ReQM69FfJrVjvF3Ja/Sz+KDe16AelyUerXRUT2WeFnwLBblSVJNherHIy+6facY4unRVWf/Co1aGoMQH1gjy4pSMWAI3t7Ddwc0g2Gx3w6oNv7hE3Mf/7dYZXb8pw25E3Vo2QrhX9h8MEGrP)

### Other comments
I'm not sure if there some configuration I'm missing, but I saw that #20350 was closed and so I'm submitting this more specific example. I have code that is trying to update the tree's opened list when something happens outside of the tree and it doesn't seem to work. This is an oversimplified example. It seems to work ok with an empty list, but not actual items in the treee.

**Comment by yuwu9145** [comment]
`items` in `data` has been converted to a deep reactive proxy so `items[0]` in template isn't the original object.

[Refactored working playground](https://play.vuetifyjs.com/#eNqNlE2P2jAQhv/KKBdAAtLvjwhQq6167bEHQCsTzy5uHduyJxSE+O91DE4cKNVyiO2ZeR/PjDUsj5mzZf7VmOmuxqzIZoSVkYxwsVIAs92EGRO24VBqRUwotBdTMJJF3An8E00AhfAUN19lYV1lnacxTHZM1th4eeraTSrNURbaoELu3efN4+bweIOxSLVVE735hSVF82KWd8l0CZrFFaiA4xGubHA6zfJYaKhqQwoI9+QT+eFjVxl8KaUof18S+y6sI2/M72gepHZ4LUovnMNyneib3PvdbSzn5s/y5FH80ZVWGApBXuIodDUQz6xjTEnwAl6P44kESSxg4B/b58RIeC0Ug9ZfboXkFlUROYEVIG/GrfqBSVScWSjAZzeAU6uPwW+T4K3VFd4PfdeF/sSNI22r2+D1ZRctvfLe35T3TZd1hYpeUFu3PcM+JAl2QD8YJJ4OKe4u8gYb0R972hTv5+8a/V98171PXfeE4rj3rSPXb3Nf8LkTbLQmR5aZu6LY9vjrR6Tee0+1bj64N9oScHxitaTYHM6IFTAcwXwBw7ZhN4O6DOvy1bq77uIJS7xtdNlUSFvNmwFPiWFU/VXJu9BWuOk/JrK9LobG0uJa6VoR8pTWjKCWOJX6eRi4ETKCPPd5DhwwMFbvD2NQmkBb8SwUk5D+e535p2bW2+nOTmNVSxk+67/wT6CW)
