### ISSUE TITLE
[Bug Report][3.7.0] List Item throws "RangeError: Maximum call stack size exceeded" when using to prop

### ISSUE THREAD

**Issue by ldavisCEI** [vuetifyjs/vuetify#20387]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.38
**Browsers:** Edge 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Click one of the list items shown on the HomeView
1. Issue: it doesn't show the HelloWorld view but the URL has been updated
1. If you open the dev tools you will see the error message in the Console tab

### Expected Behavior
It should show the HelloWorld component.

### Actual Behavior
It stays on the HomeView with the list items.

### Reproduction Link
[https://github.com/ldavisCEI/vuetify-list-item-to-prop-issue](https://github.com/ldavisCEI/vuetify-list-item-to-prop-issue)

**Comment by J-Sek** [comment]
Router links usually respond to URL changes by setting active class (so your navigation item looks different when it's address in `to` matches registered path). I noticed computed value get's called a lot there.

![image](https://github.com/user-attachments/assets/e5042a7e-3402-4450-8255-6eba5a96b7e5)

Even if you think having 1000x links with the same route is somehow a valid use-case, it seems you should rather focus on Vue Router or Vue itself if you want this problem eliminated.

**Comment by KaelWD** [comment]
Yeah this is all in vue and vue-router's code, I imagine you'd get the same thing if you had 1000 components with just `useLink(props)`

**Comment by ldavisCEI** [comment]
Took a look at this again. The issue is fixed by updating to Vue 3.5.6. [https://github.com/ldavisCEI/vuetify-list-item-to-prop-issue](https://github.com/ldavisCEI/vuetify-list-item-to-prop-issue) has be updated and works now.
