### ISSUE TITLE
[Bug Report][2.7.2] Vicon - aria-hidden should no be set to true in the svg if the aria-hidden attribut have been passed to false

### ISSUE THREAD

**Issue by 4dr1en** [vuetifyjs/vuetify#20382]
### Environment
**Vuetify Version:** 2.7.2
**Vue Version:** 2.7.16
**Browsers:** Firefox 129.0
**OS:** Ubuntu undefined

### Steps to reproduce
When a `v-icon` component is used with `aria-hidden="false"` and the `@mdi/js` library is used

### Expected Behavior
When the attribut `aria-hidden` is set to false, the svg tag should not have a `aria-hidden` attribut

### Actual Behavior
 the `svg` tag generated have an `aria-hidden="true"` attribut.

### Reproduction Link
[https://codepen.io/4dri/pen/MWMGaZY](https://codepen.io/4dri/pen/MWMGaZY)

**Comment by KaelWD** [comment]
This is fine, aria-description is set on the parent element. If the problem is screenreaders still not reading it you might want to try `role="img"` and aria-label instead.
