### ISSUE TITLE
[Bug Report][3.7.0] Vuetify Issue Creator Feature Request Stalled

### ISSUE THREAD

**Issue by angrymarker** [vuetifyjs/vuetify#20385]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.5.0-beta.3
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open link
Click feature request
enter in title, problem, solution
Click Preview

### Expected Behavior
Preview of feature request shows up

### Actual Behavior
Preview button stays in loading state

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkNEKwjAMRX+l5HmrooIwpuA/+OZ8qFuF6taGNhvC6L8bO5Xtrbk5Se7tZYQTohx6DQWUpDtsFeljZYUoh1whpmcqamdJGav9V0oiOdeSQUH6RYcKzlNZwZ9h6rdVDHloHRWqJjMocp4HRoHeYRBxMZJW38jyxM3YhrlEMfM9UK5Sf35ltTA/SX9/vxSsLGN8lCnlYkFvG31nqIEMWmOfQT6Cs/xFYwV1YCPF5Rq5Zzp0nvJO4QyYxA80xggxg63cyc2e8a3cyzVk5Ht9fQO1gHjI)

### Other comments
https://issues.vuetifyjs.com/

**Comment by angrymarker** [comment]
Error in console:
![image](https://github.com/user-attachments/assets/db39532c-6169-4ac4-bdfb-b38362d0f108)

**Comment by angrymarker** [comment]
Title used:
Programattically Update Global Configuration
Problem used:
I would like to be able to update the default table height value based on the display - height value. I have a default value of 275 set, but would love to apply more logic to have a larger (or smaller) table height based on display
solution used:
Utilize UseDefaults to update values provided
plugins/vuetify.js
```
export default createVuetify({
  defaults: {
    VTable: {
      height: 275,
      density: 'compact',
      fixedHeader: true
    },
  }
})
```
Home.vue:
```
<script setup>
import { useDefaults, useDisplay} from 'vuetify'
import {onMounted} from 'vue'
const defaults = useDefaults()
const { height } = useDisplay()
onMounted(()=>{
  defaults.defaults.VTable.height = height.value - 270
})
```
</script>

**Comment by KaelWD** [comment]
It works for me, is this still happening? I don't know how it's even possible, there's nothing in that route that can return a 403 response.

**Comment by angrymarker** [comment]
I was able to submit when not on my company's network so i'm okay with closing this.

**Comment by KaelWD** [comment]
How the hell is that XSS, it's on the same domain.
