### ISSUE TITLE
[Feature Request] Programattically Update Global Configuration

### ISSUE THREAD

**Issue by angrymarker** [vuetifyjs/vuetify#20397]
### Problem to solve
I would like to be able to update the default table height value based on the display - height value. I have a default value of 275 set, but would love to apply more logic to have a larger (or smaller) table height based on display

### Proposed solution

Utilize UseDefaults to update values provided
plugins/vuetify.js
```
export default createVuetify({
  defaults: {
    VTable: {
      height: 275,
      density: 'compact',
      fixedHeader: true
    },
  }
})
```
Home.vue:
```
<script setup>
import { useDefaults, useDisplay} from 'vuetify'
import {onMounted} from 'vue'
const defaults = useDefaults()
const { height } = useDisplay()
onMounted(()=>{
  defaults.defaults.VTable.height = height.value - 270
})
</script>
```

**Comment by KaelWD** [comment]
Use https://vuetifyjs.com/en/components/defaults-providers/ if you need dynamic props.
