### ISSUE TITLE
Feature Request: Tabs Tab Item can be also used as bottom bar

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#204]
![image](https://cloud.githubusercontent.com/assets/25447231/23896397/410291fa-08e4-11e7-9088-2a43eb355459.png)

Can we make an alteration for the position of the tab items and tab content 

for instance i want to make the tab content before the tab item like a vice versa

so the tab items would act like bottom bars

maybe put a prop bottom ?

**Comment by johnleider** [comment]
Bottom-nav is being developed and I think that this functionality belongs there.
