### ISSUE TITLE
Vuetify Kitchen Sink

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [vuetifyjs/vuetify#2040]
i was searching and i found this idea: Kitchen Sink

https://foundation.zurb.com/sites/getting-started.html
https://foundation.zurb.com/sites/docs/kitchen-sink.html

**Description:** 
_See every single element on a single page! yes, every component and every element on single page._

can we see this in Vuetify?

**Comment by KaelWD** [comment]
This is more suited for the docs repo (https://github.com/vuetifyjs/docs) I think, please resubmit it there.
