### ISSUE TITLE
[Bug Report][3.7.1] Error `eslint(vue/valid-v-slot)` when using component slots with dot notation (e.g. #footer.prepend)

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#20410]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.4.29
**Browsers:** Firefox 129.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Bootstrap new Vue project with `npm create vue@latest`. Select ESLint linting.
2. Add Vuetify [like this](https://vuetifyjs.com/en/getting-started/installation/#existing-projects)
3. Add code as shown in example (the Playground does not support eslint though)

### Expected Behavior
No error thrown as the code is exactly as [shown in the documentation](https://vuetifyjs.com/en/api/v-data-table/#slots-footer.prepend)

### Actual Behavior
VSCode shows error `'v-slot' directive doesn't support any modifier. eslint(vue/valid-v-slot)`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkM1OwzAMx1/FlAtIZLlPVSUuXPcAgFTTGIjIEstxAwjx7mRpkVZpl8T/n7/9+NNlmew9867M1O27XunIAZWGpwjQF4PMzWxiSlHRR5IVNehQ0Si+hCVn5VfGQKQvhVDj90C5/gpvvlAGEkkC48JuamNbMHhniskh6S1gdHBE+cgwshBTdCN8en0HBCEH0yzhe61rzHnT/+Hh+jUlJdmt6cPD4dDbzWot3l6Y/gS3e57IcoZNjSrzJJ4VMunMQ28XWV3d712cQ2jP8x/pOXZG)

### Other comments
I found some old issues about this that have been abandoned or closed:
- https://github.com/vuetifyjs/vuetify/issues/1333
- https://github.com/vuetifyjs/vue-cli-plugins/issues/235

My 2 cents about this: from my understanding there must be a reason why ESLint enforces this rule. So I assume that it is unsafe to use component props with dot notation in Vue. Therefore it would be better to comply with it and not use slot names with dot notation at all. If it is safe to use dot notation, the rule should be changed (which would be a Vue issue). If Vuetify, for some reason, takes a calculated risk although Vue does not recommend this notation, there should be a ELint plugin that adds on top of `eslint-plugin-vue`. I've looked into [`eslint-plugin-vuetify`](https://www.npmjs.com/package/eslint-plugin-vuetify), but it seems to be focused deprecated style which is not the issue here.

**Comment by KaelWD** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/1165

> So I assume that it is unsafe to use component props with dot notation in Vue

Yeah it just isn't though, there's no reason for this restriction to even exist.

**Comment by frederikheld** [comment]
Interesting. Thanks for the link!

I assume that disabling the `vue/valid-v-slot` would also disable it for other cases where the `v-slot` is actually invalid.  

This workaround works for me https://stackoverflow.com/a/63309643/10043870 to get rid of the error without disabling the rule.

**Comment by KaelWD** [comment]
https://stackoverflow.com/a/64609434/2074736
