### ISSUE TITLE
[Bug Report][3.7.1] Unable to use vuetify with typescript and JSX

### ISSUE THREAD

**Issue by Yamadetta** [vuetifyjs/vuetify#20411]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.4.38
**Browsers:** Chrome 128.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Sorry, no option to upload to github, here is the link to gitlab
https://gitlab.com/yamadetta/vuetify-jsx-problem/-/blob/main/components/example.tsx

How to reproduce:
1. `git clone git@gitlab.com:yamadetta/vuetify-jsx-problem.git`
2. `cd vuetify-jsx-problem`
3. `bun i`
4. `npx tsc`

### Expected Behavior
No TS errors

### Actual Behavior
Thereis en error:

```bash
➜  vuetify-jsx-problem git:(main) ✗ npx tsc                          
components/example.tsx:13:17 - error TS2322: Type '{ onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Partial<{ symbol: any; replace: boolean; flat: boolean; variant: "flat" | "text" | "elevated" | "tonal" | "outlined" | "plain"; exact: boolean; ... 12 more ...; ripple: boolean | ... 1 more ... | undefined; }> & Omit<...>'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & Partial<{ symbol: any; replace: boolean; flat: boolean; variant: "flat" | "text" | "elevated" | "tonal" | "outlined" | "plain"; exact: boolean; ... 12 more ...; ripple: boolean | ... 1 more ... | undefined; }> & Omit<...>'.

13                 onClick={() => {
                   ~~~~~~~


Found 1 error in components/example.tsx:13
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by J-Sek** [comment]
[Reproduction on StackBlitz](https://stackblitz.com/edit/vuetify-sass-variables-zvjxlp) - I got the same error, but I have never used TSX components, so something obvious might be missing there.

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/3029

**Comment by J-Sek** [comment]
Workaround:
- put unrecognized props in `{ .... { here } }`
- and include at least one additional property

Stackblitz reproduction link [[1](https://stackblitz.com/edit/vuetify-sass-variables-zvjxlp?file=components%2Fexample.tsx)] has been updated.

```
return () => (
  <VBtn
    // onClick={() => ...} // won't compile
    {...{ onClick: () => (isShow.value = !isShow.value) }}
    // requires any regular property
    prependIcon={isShow.value ? 'mdi-check' : ''}
  >
    Click me
  </VBtn>
);
```

**Comment by KaelWD** [comment]
```ts
declare global {
  namespace JSX {
    interface IntrinsicAttributes {
      [name: string]: any
    }
  }
}
```

**Comment by Yamadetta** [comment]
In the end, it was possible to fix it using a wrapper in the form of UiBtn. This solution autocompletes all props from VBtn:
```ts
import { defineComponent } from 'vue'
import { VBtn } from 'vuetify/components/VBtn'

type VBtnProps = InstanceType<typeof VBtn>['$props']

interface UiBtnProps extends VBtnProps {
    onClick?: () => void
}

export const UiBtn = defineComponent({
    name: 'UiBtn',
    setup(props: UiBtnProps, { slots }) {
        return () => (
            <VBtn {...props} {...{ onClick: props.onClick }}>
                {slots.default?.()}
            </VBtn>
        )
    },
})
```

**Comment by Yamadetta** [comment]
If anyone could tell me how this could be fixed using type declarations, that would be great

**Comment by Yamadetta** [comment]
I was able to achieve full autocompletion of props from components and eliminate errors related to onClick by creating a types/global.d.ts file with the following content:
```ts
import 'vue/jsx-runtime'
import type { HTMLAttributes } from 'vue'

declare module 'vue/jsx-runtime' {
    namespace JSX {
        interface IntrinsicAttributes extends HTMLAttributes {}
    }
}
```
