### ISSUE TITLE
[Bug Report][3.7.1] Cursor class doesn't work on v-text-field as expected

### ISSUE THREAD

**Issue by piris-jose** [vuetifyjs/vuetify#20423]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.1
**Browsers:** Firefox 129.0
**OS:** Windows 10

### Steps to reproduce
Place the mouse cursor on the Textfield.

### Expected Behavior
The cursor should change to the "hand" pointer.

### Actual Behavior
It changes, but to the normal text selection pointer. The "cursor" class set for the v-text-field gets ignored by Vuetify.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjcsKgzAQRX9lyEpB616i0A/orrvaRUhGGogmJBOxhPx7fUBxMzCHe899JRa8bO7O3ZaIrGWccHJGEPbDDMCXmnCletRoFEgjQugGJqMP1tfO6pnQD6yHxxeMJjIIzy1+pnlzLW863lzc2xuk146OHVyd9QQKRxENQdoZwIT0sSq0kHJ1EiVItFCU0PVQpFweOO/qv4zlao7GHOf9Ayf+TNY=)

**Comment by KaelWD** [comment]
Classes are applied to the root element but `.v-text-field .v-field` already has `cursor: text`. You will have to use CSS to override this.

**Comment by crystalfp** [comment]
Yes, but overriding the v-field setting as below has no effect.
```
.v-text-field .v-field {
    cursor: pointer !important;
}
```

**Comment by KaelWD** [comment]
`.v-text-field input` will also have a default cursor from the browser.
