### ISSUE TITLE
[Feature Request] Why do all dialogs feel stuck?

### ISSUE THREAD

**Issue by moom-en** [vuetifyjs/vuetify#20430]
### Problem to solve
I looked at all the dialogs, and I saw that it takes about 1 second to open or close them. Why is this? It feels very laggy.

### Proposed solution
Can I control the laggy when opening and closing the dialog through configuration?

**Comment by MatthewAry** [comment]
Hey there, this issues sounds more like a bug than a feature request. I am not able to independently reproduce your observation. You can reach out to the community on Discord if you need help with more ambiguous problems.
