### ISSUE TITLE
Tab component transitions with swipe with :touchless="true"

### ISSUE THREAD

**Issue by huysamen** [vuetifyjs/vuetify#2043]
### Steps to reproduce

- Add tabs component to page
- Use property `:touchless="true"` on `v-tabs-content`
- Swiping with finger still causes transition

### Versions

vue - 2.4.4
vuetify - 0.16.1
All OS and browser

### What is expected ?

When adding `:touchless="true"` to `v-tabs-content`, swiping should not trigger transition

### What is actually happening ?

It transitions

**Comment by jacekkarczmarczyk** [comment]
You should use this prop on v-tabs-items not v-tabs-content

**Comment by jacekkarczmarczyk** [comment]
`touchless` prop exists in the `v-tabs-content` API but actually it shouldn't be there, I guess that caused the confusion

**Comment by huysamen** [comment]
Yeah. Also the docs need to be updated, as it shows `v-tabs-content` has the property and `v-tabs-items` not.  Thanks!

**Comment by jacekkarczmarczyk** [comment]
It will be fixed soon as we have now the tool to detect which props are missing or unnecessarily shown in the docs
