### ISSUE TITLE
[Bug Report][3.7.1] Not Working v-select @update:modelValue via CDN implementation

### ISSUE THREAD

**Issue by Risvana** [vuetifyjs/vuetify#20443]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.3
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
create an HTML file and js file to use vuetify in cdn mode for v-select and try update:modelValue.
  '<div id="app">
      <v-select :items="['Foo', 'Bar', 'Fizz', 'Buzz']" label="Test"
                v-model="selectedItem"
                item-title="name"
                item-value="id"
                @update:modelValue="showSelectedValue()"></v-select>
   </div>'
<script src="https://unpkg.com/vue@3.5.3/dist/vue.global.prod.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify@3.7.1/dist/vuetify.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/vuetify@3.7.1/dist/vuetify.min.js"></script>

<script>
const { createApp, nextTick } = Vue;
const { createVuetify } = Vuetify

const vuetify = createVuetify()

createApp({  
    data() {
        return {            
            selectedItem: '',
            ad: {
                id: '',
                cityId: '',
                makeId: '',
                modelId: '',
            },          
        }
    },
    mounted() { },
    computed: {},
    methods: {
        showSelectedValue() {
            console.log('hit')
            console.log(this.selectedItem)
        },     
        
    },
}).use(vuetify).mount('#app');
</script>

### Expected Behavior
on select change 'update:modelValue' event will execute showSelectedValue()

### Actual Behavior
Not executing 'update:modelValue' event in CDN mode

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

### Other comments
This issue is found in CDN implementation which is why play link not provided as play doesnt allow to do CDN implementation.

**Comment by KaelWD** [comment]
https://vuejs.org/guide/essentials/component-basics.html#in-dom-template-parsing-caveats
