### ISSUE TITLE
Transitions don't work on badges

### ISSUE THREAD

**Issue by tsauvajon** [vuetifyjs/vuetify#2044]
Transitions don't work at all on badges !

### Steps to reproduce
Check the reproduction link

### Versions
Vuetify 16.1

### What is expected ?
Exemple 1: the whole button should animate
Exemple 2: the badge + icon should animate
Exemple 3: the badge should animate
Exemple 4: the icon should animate

### What is actually happening ?
Exemple 1: OK
Exemple 2, 3, 4: Nothing happens
Exemple 3: the badge position is broken

### Reproduction Link
https://codepen.io/tsauvajon/pen/qPxWEw

**Comment by KaelWD** [comment]
[That isn't how transitions work.](https://codepen.io/anon/pen/vedKLZ)  
I don't know if there's currently a way to do \#3, but all the others work fine.

**Comment by jacekkarczmarczyk** [comment]
I believe that this is the correct markup for example 3
https://codepen.io/anon/pen/QqQEMo
It still doesn't work, but as you look in the dev tools you'll see the transition classes are toggled when you click the button, so it's just a matter of adding proper transition styles

**Comment by tsauvajon** [comment]
Oh indeed, this is a stupid mistake by me!
T'y @kaelwd

**Comment by johnleider** [comment]
Is this resolved?

**Comment by KaelWD** [comment]
I'd say so.
