### ISSUE TITLE
[Bug Report][3.7.0] Mount order of components of a VLayout inconsistent

### ISSUE THREAD

**Issue by Joebayld** [vuetifyjs/vuetify#20456]
### Environment
**Vuetify Version:** 3.7.0
**Last working version:** 3.6.15
**Vue Version:** 3.5.4
**Browsers:** Chrome 128.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Open the link and view the console
- Toggle Vuetify versions between 3.6.15 and 3.7.0 while observing console

### Expected Behavior
The mount order used to go from parent down to child, so the console would read: 
```
Mounted Layout
Mounted Child
```

### Actual Behavior
Since version 3.7.0, the mount order is from child up to parent. The console reads: 
```
Mounted Child
Mounted Layout
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtUj1PwzAQ/SunLGmlNBZCMFRpJcQKG2IhDCa5tgbHjhwnUFX971xsJ21phw4sid99vLv37Ldd1JiCdS1asdqmn000j0RVa2NhB4VBbvHV5xLo0DRCK9jDyugK4tAU5ypXhVaNlphKvZ7EoWNomMdj77SvxR/H37dYCCSwOJ022eUKwG6wwjm4M0CJK95K++KDsRTrjY0Tn2Os/+8J7WlGlDhVD3WdEj9JyixWtST6ZV+WdTNe1+7oAG1iuVBoQoiCT3yrWwtsKGJ/q/qIJ8nYETnBpjCittCgbf2M4Geg9N6lzMN+PzIwY76L6sPuh/Sl9aXLHhQo3ok1t+TwrDT8Gw3MK12inHVctrjII2tazCPyXGpD8EPy4ovwqO9xI2QZYC9tHHCtOk8wiHMoaBtLdqDVs26VxfL4Dbn3A4fchDdbVcBkCovlcPUnz2vg8BbFdN908/Q9N3Fc49zDUnRLl85Yf7xe6H+rcEtcFrFPVCtlEt2m9+nNXfT+C6quQJc=)

### Other comments
I'm pretty sure this is related to https://github.com/vuetifyjs/vuetify/pull/15229

The behavior obviously is different between the versions and this actually broke a feature of my app. I was relying on properties being set in the parent's `onMounted` call before the children get mounted. I can make either option work, but I'm not sure what is expected behavior in the lifecycle chain.

**Comment by KaelWD** [comment]
This is back to how it worked in 3.5, #15229 was reverted in 3.7 because suspense is still unstable and broken.

> I'm not sure what is expected behavior in the lifecycle chain

child -> parent for synchronous components, parent -> child for async:
https://vuejs.org/api/composition-api-lifecycle#onmounted
