### ISSUE TITLE
[Bug Report][3.7.1] VTreeView load-children no longer working after upgrading

### ISSUE THREAD

**Issue by kensington133** [vuetifyjs/vuetify#20450]
### Environment
**Vuetify Version:** 3.7.1
**Last working version:** 3.6.15
**Vue Version:** 3.5.4
**Browsers:** Firefox 130.0
**OS:** Mac OS 10.15

### Steps to reproduce
The example given is taken directly from the Vuetify Docs: [Load Children](https://vuetifyjs.com/en/components/treeview/#load-children)

To reproduce: 

1. Expand the tree-view item
2. The load-children function fails to run so no children are shown

### Expected Behavior
The `fetchUsers` function should be called and the children should be shown in the tree-view

### Actual Behavior
Nothing happens as the function is never called

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVWG1P3DgQ/ivu6gTLqdmlV6iqPeBUaNWTri8I6PUDVFdvMrtxcezIdnZZEP/9xnayiZMs0G93SGgTezwvzzwztnN5N9AqHr/J89GigMFkcGAgyzk1cHQlCDlYRDFViXtev0WGGQ4k5lTrw6vBdB4xkbC5JAZuTLRMmQH/mO5fDcqlhHzRoMhbpiA2Uq1KheOmRhRd21FyWS2s7OQ02rsaVKM/Cm3YbIXjOqcxRFMwSwBRCazNWp8lJ/hvdTQdcnNGASwYrI3Zv0WUyQT4hMaGLRCJBBe6Z6jNN+VkDsIJ2YdQZIJYZNaw+23NcUmTKE4ZTxQIlJmBiVMLU0sQfZcK55dUCSbm4WQCQjNjcYhlhkiYcNra9eiihKBZKwQ3vaC8sNMsCSfL+OmUQ3PYRhlJEcWcxdfNCaOo9YXJMo1BHhzeFbcQOs2lmeQKUJmF7s65Qu6D/JQ5YrEUuILNUO6ZFRtVoHWkCckSFtE4loUwLUXINasp9Ggc0L2WrHhR88hSVfI1R51nCVuwBGm9AGVYTPmRlSoHQ0lcWhuoGJ1EMw43vlZiEAZUnYCQpjpWkvNohX5VGBNLPku6wmD9tZA4QCfC8Cv8NHCsQGiluvbJF+4r79RcwSribJ4aTPkLMpMC6xvsux9tK9Fm5YhGcVZEaGo2IT6w30PRVtrOnVOEuiYR5gcDCSPzHaMdHHAdkBTL6xpcdyjjHbXZ3WgsJnpFspuIFka2ZTJ6Ey1ZYlKU29vdbU/PkDoPxLVumAhmh6k4SW15BQEHySqnWzYd0OzW4vz6dXeyY8fXUDbvjiNI2PxRz/fUmFxPxmNnkVKlR0yOf7nzDtx/73Ohxi+bRq/6JFw1oOFu5DjuVXen0pctKu4T1P9bT6UTcndH1um1vY3c33dNpS+7RpBUoZUpdsCn2YGMMt5rqM3UByzpYpoCTbCZBzU1lRxJ+ogDBZbIxmC7PtRbbJeDdQdrNa6WUGMz7m0XHGadVoDbAZ2jQMN6W6SvIoI+2WtMWahIBtFembAe+fVm353zXmmjZHsn3VA8J3ZbFatJH4n9htAXxFEzZW5nFquKow+v/I+F/xWmuN/Az4bf04RobwNKFdhW932M7WYN2NIb3dR4sHHMweCqf6aciuve3tPEv1TnoKe93eh/k47TVIqfTkYTi9wq2EhCO4rV3jojBZeAaqjnSNJzWGorbSgLzl74igpZ7lsUHtM0HgfcFqHJIbn0irb/wJMdaC0VA32xyuHw2OZ/ywueu8PHCVMxh60Yj5cpnLiT8ynVBvh7PNGJctytPU+ZMuexlPkniK+3YOWHvzLUiC9TdNkNfBHMPn+iplCUb81ozCj/kzLltaMLuLoedWs+Srye0DiFj3QuimwrXYufYsDMDmV4cEud8IkUMfZ0SLb0NRNe7IIKO2Bk7kQuCjWlYvv5JhzOCzG3tAT9GBjvFV3t/vYEHN6t4AwTHEBxRpmG5N1NjNWUdJA4C8Z8fgBzjRgAXtbiBgpWNKXGv3y1N8YGHhdLTAG6XaPxlqrrY3RCrAH5gAVjrRwXD6ByqsCTCrmJMT+CjE9kG5i/A1DOC5Uri0EAyxsxV6seYkiRQAcRx9gaiVJqDYYn62esqXkTk/OMBYh4Z9tofJLmQkr7thmUM7waJU8rmdKLBiSf8aZDPSk8dbnU0MVic61shmSuaJ6y2CeO3d7SACQbbQujYzxJNRECxbDqGhh9sL25yxjmfjYD9FehzJOq6EUTGXTxFpSjzCNseQszWnDzpPLpIGNvSqIJTVBJFhIk+kOldErxtY3JSaH4yiPyzV9bfQfOKZ42sf9m2ISPiIAlOVUyw4iGWFmSL3DuCLcWc8EyQJvV6HNcsLPjFcFNLpXBzxQuaHLnUU8Q3QkZ7tj1w3Ks/OAAE3L5rUwODrk8TIgoOF8P2i8QgZQ9E+vGyP0OPvhHe/YqsFtNKtP+o4e2xtcjhChAxopqoylP3eHeaE9vE7LtPtBU7Fnv8eUHiQkxKdPujK4DkfvGG0LcHqy255ZXbEaGz5xGD80Ikz836U7lLlYyzBhuFPW3hip1LMG8NZZe7paZDeKtvR2hnmRoH21O7C/emMnh4SFqwlSGDttf/7Sk+M2qgW0VCAKFzSOR2RuXwAqvemEGJpUJJq3Ovl6JmNQfwcjQJirAYzwmZ5BJ5B0TBO/seHdKNUE7RNPyk2IptpLFNoplNAGki2EZu8V9F5F5RibrcNDmkrKS5sMX+7u7JWkDjJxHw+3qivxDS4GnlhhSvK0hSmaV42elBOwpf+yg3G4YIGSEHULYyrC44s/IKhja8mjL2AlXEME3rlFe6HQ4Grl1O611sYV/CMolzSZechjZ74R2rJatidZMSotsnix+5rA6fF1+pCYdzbiUaugevQJc+WslUpGyQ2v/i7fUg3F5thvcPx+8HO2P9gbPbUF/+xc4w7le)

**Comment by yuwu9145** [comment]
It works, probably check your network

![treeview](https://github.com/user-attachments/assets/30db9d65-2d0d-4e24-87fb-97ac89e90f2b)
