### ISSUE TITLE
Comment gone wrong?

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#20452]
So I found this, and I wonder if this is a JS/TS keyword I don't know of or if this is a comment that went wrong?

https://github.com/vuetifyjs/vuetify/blob/4e41c7e2bef649551c6f4032cda220f2dd605780/packages/vuetify/src/composables/filter.ts#L74

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com), [Stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js), or [GitHub discussions](https://github.com/vuetifyjs/vuetify/discussions).
