### ISSUE TITLE
Dependencies Not Found: vuetify/es5

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetify#2046]
ERROR  Failed to compile with 10 errors                                                                                                                                                                          22:17:46

These dependencies were not found:

* vuetify/es5/components/Vuetify in ./src/main.js
* vuetify/es5/components/VApp in ./src/main.js
* vuetify/es5/components/VNavigationDrawer in ./src/main.js
* vuetify/es5/components/VFooter in ./src/main.js
* vuetify/es5/components/VList in ./src/main.js
* vuetify/es5/components/VBtn in ./src/main.js
* vuetify/es5/components/VIcon in ./src/main.js
* vuetify/es5/components/VGrid in ./src/main.js
* vuetify/es5/components/VToolbar in ./src/main.js
* vuetify/es5/components/transitions in ./src/main.js

### Steps to reproduce
* vue init vuetifyjs/webpack-advanced
* yes in all prompts
* npm install
* npm run dev

### Versions
 "vue": "^2.4.2",
 "vue-router": "^2.7.0",
 "vuetify": "^0.15.7"

### What is expected ?
Resolution expected

### What is actually happening ?
*Below is suggested:*

To install them, you can run: npm install --save vuetify/es5/components/Vuetify vuetify/es5/components/VApp vuetify/es5/components/VNavigationDrawer vuetify/es5/components/VFooter vuetify/es5/components/VList vuetify/es5/components/VBtn vuetify/es5/components/VIcon vuetify/es5/components/VGrid vuetify/es5/components/VToolbar vuetify/es5/components/transitions

I have tried these as well, but not get success.

**Comment by nekosaur** [comment]
Upgrade vuetify to 0.16.1

I have updated the template as well.

**Comment by jrvaja** [comment]
@nekosaur Thanks for your response.

Now, It has been updated. Even the **vue init vuetifyjs/webpack-advanced** comes with `0.16.1` version.

It's working now.

Great Work!!
