### ISSUE TITLE
[Bug Report][3.7.1] password type v-combobox shows the password when it's not focused

### ISSUE THREAD

**Issue by canbax** [vuetifyjs/vuetify#20479]
### Environment
**Vuetify Version:** 3.7.1
**Last working version:** 2.6.12
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0
**OS:** Mac OS 10.15.7

## Way 1
1. Type something on the input field. It won't be shown since it's a password.
2. Click outside of the input field. The password is revealed unexpectedly.

## Way 2
1. Select some value from the combo box list
2. Click outside to move focus to elsewhere. The password is revealed unexpectedly.

### Expected Behavior
The password is NOT revealed

### Actual Behavior
The password is revealed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNUF1PgzAU/StNY8KDE4JsLk7EoA8ajW8aTcZiCtxhY2mbtoOh8b/bIgSeeu75yO092x+sVRGkUvrNAfAGxwZqyYiBJOMIxc0ZkbKH/VAIbgjloAZqIOtc5OI4UgiZTsJ1hiXRuhWqzPAkMZIDs1qK7oYYaqn5RKMXaWBQmHlkQ+2ftM1svdHlLZC3XFark1d16/DD+jv/euKn6VXx+LFPblQbdc+XTrkHoSpKwvPITS9wfCfaobcuFDXllbebr2qIooQbu0sLJiYliYPpzrGOnpr34Zj/uuJgVuOBl7C3pjLj+HeBI3/lX2D3rv0Q7/4AsK52lg==)

**Comment by canbax** [comment]
I showed input element always and hide the select div. It seems OK for now

**Comment by yogender-kulshrestha** [comment]
Use this code to mask the password in your v-combobox:
```
<template v-slot:selection="{item}">
  {{'*'.repeat(String(item.value).length)}}
</template>
```
This code will display asterisks in place of the actual password value, keeping it hidden.    
        
Working Code Link:
     https://play.vuetifyjs.com/#eNplUe1KwzAUfZVLEbrp3JibiLVOpj8URRCmKGxDsvZuC6ZJSNNus/TdTfqxFvwT7j05536cO8+cWAWDqZT9NEHHc3yNkWRE42TBAfz0nEhZhEUSCK4J5agqqAKjlViJfQ0BpOeRCJHdLpwYGQYawzcSxzuhwoXTsBhZFZwpPFQVYEf1FmTFhVLclnjUjBcbzdytWW4P3PF4c3nyoe5t/HT1u/p54WfTm+D5ez25U7vR4fXa/jyiUBtKhhcjm73j/ovENvo8DEVE+cZdtlulRFHCtd1BMNH8HDc3u9demYVjJrRXDkwFN6rMjpq3Kxptlrmnbl+hRKI7M61M147l9VPCEuz2GfKN3nbz3B/UtRt94/mgMd2ARzik6WRWGQ614x5kWeVkcwawHSy9umxRsH1ai5SXbyYpWvlxoKjUBQn3UigNIa5JwjRkZbGQaNLp1hmAQp0o3uTwbxoPeMJYrybkZZAXgEn8wbGnk/cKqn2Wf6Bd3ec=

**Comment by KaelWD** [comment]
None of our components have special handling for `type`, it's just passed through to the `<input>`.

**Comment by canbax** [comment]
@yogender-kulshrestha Thank you for the suggestion but if you try to type sth into the input field when sth is already selected, it messes up, it shows both the selection `<div` and also the `<input`. Always showing only the `<input` element solved my issue.


![Screenshot 2024-09-17 at 17 51 38](https://github.com/user-attachments/assets/6c63df93-d2ce-499e-98a0-630fb5a60188)
