### ISSUE TITLE
[Bug Report][3.6.10] VMenu - activator="parent" can't be tested with VUE test utils

### ISSUE THREAD

**Issue by YukiYu729** [vuetifyjs/vuetify#20471]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.29
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
I wrote three use cases for `VMenu`; they all work, but the third one (with `activator="parent"`) cannot be tested in the unit test script. The other two are fine, but I really need the third solution.

Here's my code (also in VPlay):

```html
<!-- first -->
<VMenu v-model="show">
  <template #default>
    <div class="menu-content">Menu Content</div>
  </template>
</VMenu>
<VBtn @mouseenter="show = true" @mouseleave="show = false">
  Open Menu
</VBtn>

<!-- second -->
<VMenu :open-on-hover="true">
  <template #activator="{ props }">
    <VBtn v-bind="props">Open Menu</VBtn>
  </template>
  <template #default>
    <div class="menu-content">Menu Content</div>
  </template>
</VMenu>

<!-- third -->
<VBtn>
  Open Menu
  <VMenu :open-on-hover="true" activator="parent">
    <template #default>
      <div class="menu-content">Menu Content</div>
    </template>
  </VMenu>
</VBtn>
```

And here's my unit test:

```javascript
import { mount } from '@vue/test-utils';
import { VMenu, VBtn } from 'vuetify/components';
import PopupMenu from '../PopupMenu.vue';
import { createVuetify } from 'vuetify';
import { nextTick } from 'vue';

// Create a Vuetify instance
const vuetify = createVuetify();

describe('VMenu', () => {
  it('renders menu content when open', async () => {
    const wrapper = mount(PopupMenu, {
      global: {
        plugins: [vuetify],
      },
    });

    // Find and trigger the activator button
    await wrapper.findComponent(VBtn).trigger('mouseenter');

    // Wait for the menu to be visible
    await nextTick();
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Check if the menu content is rendered in the document body
   // Third solution will fail here
    const menuContent = document.querySelector('.menu-content');
    expect(menuContent).not.toBeNull();
    expect(menuContent.textContent).toBe('Menu Content');
  });
});
```

### Expected Behavior
When use  activator="parent", there should be some way to write the unit to verify it

### Actual Behavior
Unit test can't pass, don't know why

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFU7tOxDAQ/JWVKQ4kQvpTDvGoER0NoTDJRhfJsS2/KE7372zsu+BEECQamijeGc+Ox97XA7OmKe+1vgke2ZZVDgctuMPbWgJUoeBax9+4aJR0vJdoTiUqvjyh9BCKQbUodjWze/VRswknxlkRLlrsuBcuAwlu+wCN4NbS5oG0YhOUjkSi9GNaViURc9ly5jSVopnM24OTcDcob5EU0JzswQ6c8VizEyaQB/zCOi4sgVmvZ40SRumsE0kTYxHDVhGzULLYqxDbpT7fp8Eb1wfu1Mg7gDZKWzjOyOcjhOK9ly3RIokok6HJyEos/3MFs0tYy/K38CDPSXOTfM38rx/v7wf8Kc7lO8svoSqXYzJW0hTN1GhpG9NrBxadT0PWD1oZBwcw2MEROqMG2NBgbkaQVC2R0yMlwmV8qFejbBIiCXa8ll6I+Hn7BDYwMbk=)

**Comment by KaelWD** [comment]
There is a few ms delay between the component rendering and when the event listeners are added, you shouldn't hover over it immediately.
