### ISSUE TITLE
[Bug Report][3.7.1] VFileInput does not provide file path anymore

### ISSUE THREAD

**Issue by crystalfp** [vuetifyjs/vuetify#20486]
### Environment
**Vuetify Version:** 3.7.1
**Last working version:** 3.6.0
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
Load any file and you see that the output below changes from "None" to an empty string.
Is there any way to obtain the file path? As is it is a widget not useful.
I'm running inside Electron.

### Expected Behavior
To have somewhere the file path to open. Note that I have to send the file path to the Electron main process to open and process the file.

### Actual Behavior
The widget provides an empty string.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkM1uhCAUhV/lho3TpOp+gqbddNHFdNFl7YLqpSVBIAhmGuO7zxXHaGZD4Hz35xy+Jjb4tnx1rhgjsjPjAXunRcC6MQB8zIVz6ZoerTVBKIP+LiVRKo25Mi6GTQQ497ZDnY9CR6waJhu2My1+UJP4Rn2w9h3oS3QdrX8YoK3olvq9sublcfXmkcRHk9MEV5jnlIfwGoiXh6B8aL1yAQYMcU2remd9gAk8SphBettDRj+ULZAWDIFmVgs9ZRdrMHvagbyDg7TZJyKgqmFanV2LlI/U98+PSzEEr8yvkv8nUTgR/tIA8s3L1R85Y/OziVqn4/sGcAmO2Q==)

### Other comments
Don't know when It was working.

**Comment by KaelWD** [comment]
https://www.electronjs.org/docs/latest/api/file-object

> Warning The path property that Electron adds to the File interface is deprecated and will be removed in a future Electron release. We recommend you use webUtils.getPathForFile instead.

**Comment by crystalfp** [comment]
Thanks for the suggestion! Electron documentation is a little shallow on this, for example does not mention that winUtils should be accessed in preload.js. Anyway, solved and thanks again!
