### ISSUE TITLE
[Bug Report][3.7.2] VTreeview search and filter returns empty results with return-object

### ISSUE THREAD

**Issue by alfianwahid** [vuetifyjs/vuetify#20488]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
 Using the example from the "Search and filter" section of the Vuetify documentation, , I added the `return-object` prop to the v-treeview. 
The search functionality returns empty results, even when there should be matching items.

### Expected Behavior
The search should filter and display the correct matching tree items, even when the `return-object` prop is used.

### Actual Behavior
With the `return-object` prop enabled, the search returns empty results, even when there are matching items in the tree

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl1vGysQ/SvIupITyeSjSV+sOFVvrq6q+9FWrdSXOlIxzHapWVgBazuy/N8LrNkFx3ZVty/2MnM4O2dmYPbzemA0vXxd1xeLBgbjwZ2FqhbEwv1UInS3wJRohqggxkymg2qFSWPVdIAqssJLzmzprC+vrqaDgA87TAlguy01wbdo9hXXmldEP3XAALWwsrjgIFg0IrTAlWIg3FYDRNNyOuh9VDgT5lRJHwzjmAplAFOunQerxgouId0gyCxQfQxU6EFVNZFP6C+ugVrlw9khJzMBvYkRPe9XhctLvyo5A8zAEi5MbzVKKMzlArSFTtT93WWqNc0ALYHOZ2q1Tz8lBj6CNNzyxV5VDw6ATES4p9185fHviziEFoOINXSmUMS+pr4LgoKsehpgwWH5LPaxqkECcxH6hzSgMW2MVZXLg7CgHaB9+DsHcdeEvnfCf+ZpJe7tDQ/GCyIa8DtZ6tJgGy2xmn1zVe+U9/6u6Z0AI5Qd1xpc4F7AOvCiTdK3W/W+C1OTV8+LbdQXtOSC6Vx8q61t3i++e/9YByxnaDKZoGv0Cg1LVYFToTmRdojGaFgowUBjCXap9Hy4+ZIzhvp5zlTOZXaIY0ljuZIq52WNFrfIKNzSUM1r6zrMNnXA8qpW2qK1y22BNqjQqkJDd4UMPdydJSWNDakzaOIxZ5/bt65jRJyN0fUoriy3ApzaTw1YXjyhN01FJPoARjWaghl2wJjXMdoSZqSR+EWHT8kflAZkgVQ93UHKZ7Qd9VUf9e4L/lGlzLkR2uysD5DmEaek/xIQJ5LeHCR9C3NlSKNPJL49nAJCYX4i68uDrK+lK9DyOO1jsko9z5ojz0r3ClZxyY3VxM2FpOF+vkNujnTI/3wOJ2Xn5kiHvGncXfF7cpMXtj840mo+c5P/1zJzeyQz70uhflDhg6yHU/OnJpKp0w7l7ZHz474nfkC6P+XR2loez/u70k/KeFVej9CL1NcOu61XNkIkvuwjYQspiDCQYOKQde6ikdRyJdFZGJWjLfco3NXnMRHtwMy5L8KGKOQVCssLLhms3hVnLc05ukf4OmLGW4xV/6klaP+1cna+syN39vs3fga1U8fNm8Fm5GWHn8fvkc3ddw==)

**Comment by yuwu9145** [comment]
Duplicates #19404

**Comment by alfianwahid** [comment]
> Duplicates #19404

I apologize for this duplicate
