### ISSUE TITLE
[Bug Report][3.7.2] sass@1.79.1 Legacy API deprecation warnings

### ISSUE THREAD

**Issue by jakubmatisak** [vuetifyjs/vuetify#20489]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
After upgrading sass to 1.79.1 in my project there are many warnings.
"Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0."

In version 1.79.0 was this warning message added by sass team. In reproduction link are included release notes.

### Expected Behavior
Change Legacy API

### Actual Behavior
Warnings everywhere :)

### Reproduction Link
[https://github.com/sass/dart-sass/blob/main/CHANGELOG.md](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md)

**Comment by b-maslennikov** [comment]
I have the same, but... why you've decided that it's vuetify issue?

**Comment by userquin** [comment]
If you're using Vite in your application try replacing `sass` (legacy) with `sass-embedded` (modern): https://vuetifyjs.com/en/features/sass-variables/#build-performance

**Comment by KaelWD** [comment]
This is the responsibility of whatever bundler you're using, not vuetify.

**Comment by weicheng000** [comment]
```js
export default defineConfig({
...
css :{
    preprocessorOptions : {
      scss: {
        api: "modern",
        importers: [
          new sass.NodePackageImporter()
        ]
      },
      sass: {
        api: "modern",
        importers: [
          new sass.NodePackageImporter()
        ]
      },
    }
  },
...
})
```
Maybe can help you, if you are using vite.

**Comment by jakubmatisak** [comment]
Thank you all for help. I will replace sass to sass-modern. My bad.

**Comment by jakubmatisak** [comment]
If this would help anyone with the same problem in future:

1. I have changed dependency from sass to sass-embedded.
2. I have addded:
```
    css: {
        preprocessorOptions : {
            scss: {
                api: "modern-compiler",
            },
        }
    },
```
    to vite.config.mjs

After these changes everything works fine.
Thank everyone.

**Comment by MetRonnie** [comment]
I was confused why this was closed as not planned when there *were* deprecated calls in the vuetify SCSS files, e.g.:
```
Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use map.get instead.

More info and automated migrator: https://sass-lang.com/d/import

   ╷
48 │     'lighten-5': map-get($shades, 'black'),
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    ..\..\..\vuetify\lib\styles\settings\_colors.scss 48:18  @forward
```

Looks like these will be updated in the next release though: https://github.com/vuetifyjs/vuetify/commit/2b22da169f9923628c4f6d8623ddd8899e5d60eb

**Comment by gabrielrbarbosa** [comment]
Can this changes https://github.com/vuetifyjs/vuetify/commit/2b22da169f9923628c4f6d8623ddd8899e5d60eb be merged to 2.7.x?

**Comment by mrjackwills** [comment]
> ```
>     css: {
>         preprocessorOptions : {
>             scss: {
>                 api: "modern",
>             },
>         }
>     },
> ```
> 
> to vite.config.mjs
> 
> After these changes everything works fine. Thanks everyone.
> 
> Edit November 2: We have changed modern-compiler to modern, because npm run build could not end when build was executed more than once.

I have always had this exact setting in my `vite.config.ts`, but as of now it is resulting the following error:

`No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'api' does not exist in type 'SassPreprocessorOptions'.`

Any ideas?

**Comment by Unkrass** [comment]
> > ```
> >     css: {
> >         preprocessorOptions : {
> >             scss: {
> >                 api: "modern",
> >             },
> >         }
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to vite.config.mjs
> > After these changes everything works fine. Thanks everyone.
> > Edit November 2: We have changed modern-compiler to modern, because npm run build could not end when build was executed more than once.
> 
> I have always had this exact setting in my `vite.config.ts`, but as of now it is resulting the following error:
> 
> `No overload matches this call. The last overload gave the following error. Object literal may only specify known properties, and 'api' does not exist in type 'SassPreprocessorOptions'.`
> 
> Any ideas?

I have the same issue

**Comment by KaelWD** [comment]
https://vite.dev/guide/migration#removed-sass-legacy-api-support
