### ISSUE TITLE
16.1 The initial value on an async v-select that uses the :search-input.sync prop is not being set

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2048]
### Steps to reproduce

The v-model value of a v-select that's loaded asynchronously is not set when the v-select uses the :search-input.sync prop and the autocomplete prop.

If I push the v-model value in to the items array when it arrives the default value is set but the select doesn't behave properly. I'm assuming it has something to do with the select not having a defined lazySearch value because when you click on the input the ajax request is fired even though nothing has changed. The value also gets cleared from the input even though the text (item-text) is visible until the input blurs.

### Versions
Vuetify 16.1
Chrome Latest
Mac

### What is expected ?
If the select v-model is updated asynchronously and the items array is empty I think the item-text value should be displayed in the search input.

### What is actually happening ?
The underlying input gets the correct value (item-value) but nothing is displayed in the input.

### Reproduction Link

https://codepen.io/smitchell/pen/JJgmvB

**Comment by johnleider** [comment]
There is no way that it can, you have the items applied asynchronously, and even though you are designating a value, there have been no items given that allow it to determine the selected one.

Another issue, even if you had not used async items, you were setting the object as the value, but were not using the **return-object** prop. So it would have still not worked.

In light of this, you have a few options. You can have the values already present, or use the **tag** prop. The reason for this, is that a standard select should only ever show items selected that are in fact _selectable_. If there are no items in the array, that's like saying the user is selecting an item that doesn't exist. The tags however, do not require a defined list to pull from. Example here:

https://codepen.io/johnjleider/pen/MEVWwL

**Comment by ecmel** [comment]
This may be very useful for async selects. If cache-items prop is present in the component the v-model array can be pushed to cached items.
