### ISSUE TITLE
[Bug Report][3.7.1] Empty button icon when using mdi-palette-swatch-variant

### ISSUE THREAD

**Issue by MattTheCuber** [vuetifyjs/vuetify#20481]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Create a `v-btn` with `icon="mdi-palette-swatch-variant"`

### Expected Behavior
The button should show the icon.

![image](https://github.com/user-attachments/assets/c9ee712f-9fcc-4ef3-9a0d-cecb60439277)

### Actual Behavior
The icon is empty.

![firefox_dsij7kU9fg](https://github.com/user-attachments/assets/0738a8d0-6923-4a46-a160-9b6e86e9648d)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtkcEOwiAMhl+FEI/O3Q2a+BzOQ8WqGOwIlC3G+O5WnNlOHowHSPp/8Lf8bO86RVtvQlh0GfVSG8Zr8MC4bkgp01W2JQZHGItQpNj2Crw70arRFokxNlpdcmJ3vE2k4cLg4pWsJBgytxNY8J5JOekk+HpwVfA5yRFTFzL6SC0mUv/kPJMXvkb8v3OZGTwyY5V6YHuuOogOiL/2+lSS5zvtQsa4TT35DP2YU/a+bLsnUXyJzA==)

**Comment by MajesticPotatoe** [comment]
Make sure your mdi-js or mdi-svg library is up to date. This icon was added in `v6.4.95`

**Comment by MattTheCuber** [comment]
> Make sure your mdi-js or mdi-svg library is up to date. This icon was added in `v6.4.95` https://play.vuetifyjs.com/#eNqtU2FLwzAQ/Ssl+HFJEFFhTJm/w/oha0/NTK4luXbK2H/3knaubDBFhbZwd7n37r1cH7cihko/tK3qOxBzsSDwrTME9yUWxaKXVYNkLELIiZwKzaYwzr7gXSkqQIJQimLdRbLPH5PU2DCiuILfyGXTUTMp5vKKsLDMxGVfW9m6LvKRhc6VAw7HDMLxr5AvWGEa8f+R88zGARHIuDFUvcreBGuQznLtI/ZzcDtXDnYv9OQyxExY3zaBpDetWscG+ba2qa0cC2zZvMiZlGOxKS7FK1Eb51pXNXJbDc72QSGQxtbrJR/ToUOyHmTd+OWVulY3uraRpmkF0csVzxkhMEgpZhOawdNvqcaTzHCrLgeGMSWdWcVEcQKtma+HIANgDSEt1c8UHbVNVR2VTpQl9l2J/LDjzuJbPDK7itnox/2YfxKdwb4UnxfGW6afeT2WN+pdc6P2vBm8Za6GyD9j2sWovMUBNGE+DTp2M+ycy5+nTxMDTrg=

What version of MDI does Vuetify come with? Should it be updated?
