### ISSUE TITLE
[Documentation] Item key slot for v-data-table is disallowed by ESLint

### ISSUE THREAD

**Issue by Kwintijn** [vuetifyjs/vuetify#20487]
### Environment

**Browsers:** Firefox 130.0
**OS:** Windows 10

### Steps to reproduce
Copy the code as showing in the example into a project with ESLint as linter.
```
<template>
  <v-data-table
    :headers="headers"
    :items="vegetables"
  >
    <template v-slot:item.calories="{ value }">
      <v-chip :color="getColor(value)">
        {{ value }}
      </v-chip>
    </template>
  </v-data-table>
</template>
```

Relevant dependencies from package.json:
        "vue": "^3.4.27",
        "vuetify": "^3.6.0",
        "@vue/eslint-config-prettier": "^9.0.0",
        "@vue/eslint-config-typescript": "^12.0.0",
        "@vue/language-server": "^2.0.6",
        "@vue/test-utils": "^2.4.6",
        "@vue/tsconfig": "^0.4.0",
        "eslint": "^8.37.0",
        "eslint-plugin-storybook": "^0.8.0",
        "eslint-plugin-tsdoc": "^0.2.17",
        "eslint-plugin-vue": "^9.21.1",

### Expected Behavior
I expected the code to work as described

### Actual Behavior
ESlint gives an error saying `'v-slot' directive doesn't support any modifier.eslintvue/valid-v-slot"`

### Reproduction Link
[https://vuetifyjs.com/en/components/data-tables/basics/#item-key-slot](https://vuetifyjs.com/en/components/data-tables/basics/#item-key-slot)

### Other comments
The correct syntax appears to be:
```
<template>
  <v-data-table
    :headers="headers"
    :items="vegetables"
  >
    <template v-slot:[`item.calories`]="{ value }">
      <v-chip :color="getColor(value)">
        {{ value }}
      </v-chip>
    </template>
  </v-data-table>
</template>
```

**Comment by KaelWD** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/1165

https://stackoverflow.com/a/64609434/2074736
