### ISSUE TITLE
[Feature Request] Add event update:currentItems to VDataTableServer

### ISSUE THREAD

**Issue by YukiYu729** [vuetifyjs/vuetify#20492]
### Problem to solve
Hi team,
I'm using the VDataTableServer component and need to retrieve the current items, similar to the event in VDataTable.

### Proposed solution
Could you please add this event or let me know if there are any workarounds?

**Comment by KaelWD** [comment]
It doesn't do any pagination or sorting, that would just be the same as what you're passing in.
