### ISSUE TITLE
[Bug Report][3.6.14] v-menu in each row of v-data-table

### ISSUE THREAD

**Issue by dombrga** [vuetifyjs/vuetify#20491]
### Environment
**Vuetify Version:** 3.6.14
**Vue Version:** 3.4.36
**Browsers:** Edge 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
I provided a vuetify playground link for complete example.

The idea is that I want to put a menu (for actions like edit, delete, etc, that item in the table) in every row.
Problem is if I put a menu and click it, multiple menus will open, and they will be overlapping with each other. If you have 10 rows currently showing, 10 menus will show. So, if you try to close the menu, you will have to close 10 overlapping menus.
And the menu only opens for the first row.

Important bit 
```
<template v-slot:item.actions="{ item  }">
  <v-btn id="menu-activator"> open menu </v-btn>
  <v-menu activator="#menu-activator">
    <v-list>
      <v-list-item>
        <v-icon class="me-2" size="small" @click="editItem(item)">
          mdi-pencil
        </v-icon>
      </v-list-item>
      <v-list-item>
        <v-icon size="small" @click="deleteItem(item)"> mdi-delete </v-icon>
      </v-list-item>
    </v-list>
  </v-menu>
</template>
```

### Expected Behavior
Menu will open specifically for each row of v-data-table.

### Actual Behavior
Menu opens only for the first row, and there will be multiple overlapping menus. The number of menus that will open depends on the rows currently showing in the table.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdWV9v2zYQ/yqENyAOEDt2EruNEbsrknbruq1D1z0MSR5oiY65UKJA0U5c1999R4mSSIqyHaxD1+ahkI+8u9/94fGOvV63UhEcv0yS7nJBWqPWhSRRwrAkk5sYoYtlJ8QSdySeMqIICI3mBIdEpOOblv66aekVCryKHpI0JUJWCykXsjNdwdL1Gt2T1QgdBJhxQUl6cIS4AClAwmlwgDa3OVemHgAUcNCykzIuR5IneilDJzlnUyzQDPaUdHOlI6lkZPLrCl2+//Pq4thdsHhCuqSABQUMp8qQ6LFzdtNCNE6JREswiQLsiRKid9rsaYIDoKl1/elIB5vvwJCIh4QpP2UEUBDhx84DDeUciINeL3m8aRmsHi/gQNIlllwAwxolgicp2jhMmc6pjCtrpp0TUBZw8Dz8TASNsFgBJcTiHiRPaRxmdJBWk4XQb+QBvQEgjg4wFpTYcI+tJDLgBFiEdZCKWguHXgVHVhZI8ig78wGAW6/RjIvog2JCm83FsdrnSgZolugGxSC0rhcWeSwxja0oGsuCP3gWNCdTXlaI+8rjkXKrSqQ0go+hx7dV1ioLZ5Sw0L8FGelDQjhwoQpJN8YRKU5b/Y/hacZwlZ9LtG13lr0VCr+JyrGc/X/ML4rJbhdc7tj5VZo/w3K35a+xRO27w28s7mK6V9Bh2zdnPNRpSWi82/zf843/nQPUiq8c5hz+KloV57z8+muzuud4nPrK87bL1r7+9H03ZQsC3Yy4J3GnD4FZYkFxLPW1AoQfAkaDe/gdMJ5CgfRYeonjgDCfne4d+K8ApHjp1/+HWthLe+lfnwuLRbM/yZoa1Y/s1bRcEUYkYNzduuy+9OvXu2vi5KUgaMUXKF3ojwdwHJIcASbAgeScpki1ny/sS98W1ADiCyZZ4cZ6pCd5qung1hzih1EX04CrvtEFWt9RIs99rmrQJY9nVERe/O/ePgH7Lj9/hmw2Wv9itnDb1FqbrTKqq1VmnbYiIKvT1vGnqtxHJF5kCLPWHDYhnpAYKXLtlAJfRjc7+e9qAqyjyGhqN6qa1lGo6rlNofRWvT/Jev+UfiSqvkSYMTMZ1bWiAtpWouCWqMUoCmkHbAmoU/yUWUpRLSB+YHsgboJYZV0JMkOlK8CTgBR0KzmU8/fOjJhng7GbBvXZqsRPYyohI8E6hfw9USOlnRSO1iyHy+EbSNY6/EwDQZPcBvKYwIgN1XCGF0yidS5QcY9Q+xCNJ6itaUDNzsUIzTBLyZFNzeuRu6bn/BG6rlxYilN/Wa2FCb4YMNr9Xu8OweeSxneHB6Ug9QcuuIthbyqxkPaSeiZQtrr61V/+aqAmF5NnY3yvSxhFkw9vC85jQwOD7o3L/dBQN20te0lDOFCathu9V8mgG7cmlpd5vSm36/oDvx3/GPy3VRz12wsEqyLqrjEOyeMIdfouHdJqZAZUeRkUm44uPDhCPYMKfrIJmS9skrbWJFa4dcJ+MQSbQ/jIPwMeJQvwhoGjfGGAI2SAE0QuRJz1HF3Ds2g8HoNz0Qt0UDyVHCAw4hVsyX/VtJfKH7AM5obm/DS2l5hZmuE3+vQp15z1D+1Dj0+Nk7xbgt5Xk1NhCwSBkhOaPsjYq4JWcFc8EZFzHkIcShZztwkoE1UkLRqbJcYpMmVWvBb8I1yrf/G7hVtBzDTpD86dtSxZhl0zN4yUOTlz6GXenDks5rltAvkmgL4WPBehFMfhAw3mzUhPTp/5kJ43Ia1tN5CePhnpK+gRqNiCbnjiQ9dvdqSNwYDnsuwD73KRBPjeqvo2vtPewIfvtOt6ScMbflbv/Qg3HBFTiHS4BeJg+DQXnrmpW2I87dpL+2D8mTC2QlOC4y0Qn3m92GtCeN54WlyWfRD+whmjCU+24Dv3ZmGv65ILfM8b8T0Z3U88Jiu4H6bN8M56rj6dhA3wnjcm4bBrB2IfgFc8XmyphGcDr+9OBk3BHVQtQu2IPD393lL5FhqqRniDvtd3J42nY+imagnP9qoJ7ta84Mz+p5ooateSdbnbNxXcfkB9N9OziJdPzYpj9G76NwlkF8Yw6Hvb681RNkS6LPqZBbSIRflqYUJ1x58vDzbvHPaCrN8Jttz83TSBOYm0XVOOUN/V3ti2FN+6M6rrKnycdc/O4vcxPHt8gFGtnc9L9nyzh6O0OWU/a8D2RgieYaoxptmOwtAGa8ogfCU2qZdN2xg6Q7WoowmIsnYhB52VPNcu/62GXplnIN8gooanujPKXEwW6dzC5AjwJaS/g842w39OFpN6a3MULxjL/rn9BxbAc9A=)

### Other comments
Thank you for any fix or recommendation anyone can provide!

**Comment by KaelWD** [comment]
Use one of the other ways of setting an activator (https://vuetifyjs.com/en/components/menus/#usage) or make sure you give each one a unique id.
