### ISSUE TITLE
.91 modal__container taking 20px

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#205]
I saw your commit for this, but it didn't fix it.

I noticed if I turn off display-inline on the .modal__container the problem goes away. maybe a clue.

// temporary fix
.modal__container {
    display: inline;
}

Open the docs page, remove the modal__activators and that is what I'm seeing.  Normally it's not noticable but I have a case where I'm getting double scrollbars.

![image](https://cloud.githubusercontent.com/assets/287137/23896994/c1130b26-0868-11e7-95ec-0920bcdfd362.png)

**Comment by johnleider** [comment]
I am unable to reproduce this from your steps. Could you please provide a simple jsfiddle or codepen showing the issue?
