### ISSUE TITLE
[Bug Report][3.7.2] v-data-table preserve v-model:selected even after change items props

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#20509]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.8
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
v-datatable should be update after update items props  

### Expected Behavior
v-model updated after update items props of datatable

### Actual Behavior
v-model not updated after update v-datatable items prop

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNld2K00AUx1/lkJtVaJusH6glW1wXERFloSsLtr2YJsdm2MkkTCapUnotgiuo1+KVl76bj+BJ0rRpQmdLvdkW2sz5n49fTs5MRgsrUZ59Gse9LEWrb7kaw1gwjYOxBHDj4g9giAI9DUkUInBySUAHKMET3LsChQlq8Jlm5JAqD6FDKmTdMPJRkBwyLiHO3aQu83HKFUSp8GGKkMYUi35R0C4ruj7PBotFUpRFf7l07dxSSFl3qiU8LWqfjK0C52Q0GVuDFohrF85VXK50NZsKLClWhJSkKjS2SqVfZl1lr6z5opsxkSIpkoVYCXQv826ZIzcM8rqbYlTetWt9pWXiKR7rggs/xJEianzPUqFhUWbMo+/crVZATdSpkps11Vwh92E06eRJK6FAJuvGAvW4/JOz9+Ho76/rr0DPXuARZag7iMhjmkeSnC5ZEnA505FsOgXIZ4EmF6d33NSmLMkrOD3nUVPKIpEW5Ul0nEbkcmu1E/sLPGOSvgbu517K/EgZoO/thn5ohm5E7gn9CV4oFmNigH6pmfhoQG5WrjO3pG3mAzv9GS5palWIoj0ANfAzmpHW06iBP9jJfd+E3RD3ZL6Gcy6R3TDYFwHjgknfQN1iW1Obm90Ynz2xv8NZgEpx44RcpOoKb9WI/P4Dr5mcRaaxlj43Tcdxa7+tmVsnyzbyYZ3+AUOt2HxK3W61sob9dnhqavTu6WhLjUYfdoB8g3NkXvAf29B5spv5sZm5sYP3nI2f8IrPuYH4Dc7hHbIbNmL7QN77rDbMdP7eXFnLi1KkhWuv39DWsiNTIYqfyT+thl4n)

**Comment by KaelWD** [comment]
This is essentially the same as #10922
