### ISSUE TITLE
[Bug Report][3.7.2] vuetify conflict same name import variable font awesome by i18 locale fa

### ISSUE THREAD

**Issue by mmtaheri** [vuetifyjs/vuetify#20504]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.4.29
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
vuetify conflict same name import variable font awesome by i18 locale fa

### Expected Behavior
yes

### Actual Behavior
yes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#:~:text=You%20can%20rename%20an%20export
