### ISSUE TITLE
[Bug Report][3.7.2] Website broken

### ISSUE THREAD

**Issue by eudatatex** [vuetifyjs/vuetify#20500]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.6
**Browsers:** Chrome 128.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
navigate the link 

### Expected Behavior
https://vuetifyjs.com/en/ css 

### Actual Behavior
https://vuetifyjs.com/en/ missing css

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

**Comment by KaelWD** [comment]
This has been an ongoing problem: #20367
