### ISSUE TITLE
$vuetify.application does not get updated when removing elements

### ISSUE THREAD

**Issue by SteffenDE** [vuetifyjs/vuetify#2051]
When removing an element, e.g. a navigation drawer, v-content does not resize properly (0.16):
https://codepen.io/anon/pen/gGvegv

### Steps to reproduce
Click on bar, application is still padded left 300.

### Versions
0.16.1
Chrome 61, macOS

### What is expected ?
The v-content container resizes.

### What is actually happening ?
The v-content container keeps it's old dimensions.

### Reproduction Link
https://codepen.io/anon/pen/gGvegv

**Comment by KaelWD** [comment]
This was fixed with f51e2ab4151b8872941c0a3931e0b9ba10b6ae1c
