### ISSUE TITLE
[Bug Report][3.7.0] VBtn disabled state use black color with opacity

### ISSUE THREAD

**Issue by marcinwmichna** [vuetifyjs/vuetify#20511]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.29
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
Define color in vuetfiy config. 
For some colors `--v-theme-on-[your variable]` is black (before applying opacity), for some its white.  
In this case very gentle`primary-lighten3` with `disabled` prop turns out to be dark grey.

### Expected Behavior
Opacity on currently used color, not black/white.

### Actual Behavior
Opacity is made from black/white, instead of currentColor.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUclOwzAQ/ZXBHFyktjlwq9JKRID4AAQHwiFNJq2RN9lORRXl3/GSRCk+2LM8v1neV0+sqbNLh4611+2PJTvChFbGQQ+1wcrhR8rBAK1RAuiIpaUsJf5GaK2kdTAmYH/7cdWXEsCdUeAOog3QYFt13L2nIOXsdHZ0nXIRaWcoQMwufPD1uDJLSDhUGyYqc91EPMpH6pnvi+L55bWYuMMZZnuy0hvu4aGUZB1X8qT11k/k95E7FJr7gQ4Bll82ldbRjI6f3VVMohlDMXh0EhpmqyPHJnW7L8n//kpyyLOIndi8d0sXIqlani268K6tDdMOLLouNTOrZrBdahV1CisLEgl78vJ4xIq+IecKPpXhzR31Y+dZovRkZFjLjvN4ff8BG8mx7g==)

**Comment by KaelWD** [comment]
It does use currentColor.
