### ISSUE TITLE
[Bug Report][3.7.2] v-tooltip directive has no effect when VTooltip imported explicitly

### ISSUE THREAD

**Issue by ioptrv** [vuetifyjs/vuetify#20518]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.8
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10, Linux

### Steps to reproduce
add `import { VTooltip } from 'vuetify/components'` to the script section to stop the button tooltip from showing up

### Expected Behavior
importing VTooltip should have no effect on the v-tooltip directive

### Actual Behavior
Tooltip not showing up

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUcFu2zAM/RVBl1xiC1gwbAi8otvQw3bYhi3YperBsZlUrSwJEu2mCPLvpSSnddOiKGAYIt8j+fh4uefBN+Krc+XQA1/yCqFzukY4k4axaihq59IzBV2tzBileI2GIezwi+QrCCg5Gwq0VqNylJqt8nMm+VklEvvYiqLHXjHIUyoxmU5haLxyyAJgn0WozlmPbM88bNiBbbzt2IyEz56B/8e5Uwaqzb1oLFEMGAxUUIncnhrzOcfQWLNR2/ImWEM+7GNHyWOF0uB/O1TWBMmXLCERq7W2dz9TDn0P82O+uYbm9pX8TdjFnOR/PATwA0j+iGHtt0D+Rfji3y+ydAJ2tu01sd8A/0Kwuo8aM+1bb1qSPeEltT+SRcpsV+Fih2DCcakoNDIPiS85Ofb9jdWf5C7KRaqThj7yMR+BjutOnMzA8zY0Jcu9RnRhKUTTGiprQavBlwZQGNeJc6IJ3xtUHRSt7c4X5cfys2hVwGm6hNAVa2/vyFtqMll9PP87Ro1MmvCp/JAnjKlC1+sQR7xoLdItfeHBtOCj5+/b6KRsutUJ9GKzieOHuem1Tr+rB1T9R2s=)

**Comment by KaelWD** [comment]
I think this is a vue bug, their docs say only `vTooltip` would be interpreted as a directive: https://vuejs.org/api/sfc-script-setup#using-custom-directives
We can't just add the directive hooks to VTooltip options because they conflict with component lifecycle hooks.
