### ISSUE TITLE
Picker scrollable incorrect behavior

### ISSUE THREAD

**Issue by ecencio** [vuetifyjs/vuetify#2052]
### Steps to reproduce
scrollable date is jumping from january of one year to january of another

### Versions
0.16.1

### What is expected ?
month to month

### Reproduction Link
[https://codepen.io/ecencio/pen/GMQGZp](https://codepen.io/ecencio/pen/GMQGZp)

**Comment by KaelWD** [comment]
Here's a 0.15.7 codepen showing the correct behaviour: https://codepen.io/anon/pen/qPxKrG?editors=1010
