### ISSUE TITLE
[Documentation] documentation for each version

### ISSUE THREAD

**Issue by drforse** [vuetifyjs/vuetify#20548]
### Problem to solve
Can't understand what is wrong with code because can't really understand differences between versions

### Proposed solution
A possibility to view documentation for each version. Not just for v1, v2 and v3, but also like for 3.3.11, 3.3.12, ..., 3.7.2

**Comment by MajesticPotatoe** [comment]
This would be a lot of upkeep for something that is already available elsewhere. Sitewide documentation is broken out by each major (v1, v2, v3, ...) Features/enhancements are the only things that are added between major versions and its usually in the form of a component or prop release, and their version requirements are general flagged on the component page. patches are bug fixes.

If you are experiencing something wrong with your code (that was working in one version and then you updated and now its not working, chances are it was bug that was fixed, an actual bug, or layer8 issue. Release notes for what has changed in every version can be found in GitHub or via docs at https://vuetifyjs.com/en/getting-started/release-notes
