### ISSUE TITLE
[A-la-carte] It shouldn't matter in what order we import the components

### ISSUE THREAD

**Issue by zaken** [vuetifyjs/vuetify#2054]
**How will it make current work-arounds straightforward?**
Currently we need to be importing the components in [this order](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/index.js) ...

**What potential bugs and edge cases does it help to avoid?**
... otherwise there are issues with css cascading.

**What will it allow you to do that you can't do today?**
We will be able to add new components to our a-la-carte projects easier. No need to consider import order.

**Comment by nekosaur** [comment]
@zaken Could you possibly include a minimal reproduction with two components where this happens?

**Comment by zaken** [comment]
Sorry for the late response.

I think it was just an edge case. I am using a similar nav drawer + list as in the docs. 

I cannot narrow it to two but using this sequence:
```
    VApp,
    VCard,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VGrid,
    VToolbar,
    VTabs,
    VDataTable,
    VMenu,
    VDivider,
    VSubheader
```
makes Subheaders get their color from [here](https://github.com/vuetifyjs/vuetify/blob/f90b3a605e7ea517ee3ab7372b1a6100822eaed7/src/stylus/components/_lists.styl#L15)

while this one ([taken from here](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/index.js)):
```
    VApp,
    VBtn,
    VCard,
    VDataTable,
    VDivider,
    VFooter,
    VGrid,
    VIcon,
    VList,
    VMenu,
    VNavigationDrawer,
    VSubheader,
    VTabs,
    VToolbar
```
makes Subheaders get color from [here](https://github.com/vuetifyjs/vuetify/blob/f90b3a605e7ea517ee3ab7372b1a6100822eaed7/src/stylus/components/_navigation-drawer.styl#L14)

**Comment by johnleider** [comment]
@nekosaur any update on this?

**Comment by nekosaur** [comment]
Haven't had time to look at this yet. Probably this weekend

**Comment by nekosaur** [comment]
I haven't been able to replicate this (on dev). Subheader always used the correct css as far as I could tell. I did however realize that it did not follow md spec.

Spec states

>Subheader color can either be the secondary grey text value (54% black) or the primary color of the app.
>In long lists of complex information, consider using colored subheaders to delineate content. Android settings contain an example of how color can be used on subheaders.

Which means that the following rule in `_navigation-drawers.styl` is incorrect

```
a:not(.list__tile--active),
.subheader,
.list
  color: $material.text.primary
```
