### ISSUE TITLE
[Feature Request] VTreeview update:activated should also provide the unactivated value

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20556]
### Problem to solve
In my use case I need to know which node was active before the user activate the new node.
Actual I only gt the new selected id, not the old one 

### Proposed solution
Provide both values in *@update:activated*

**Comment by KaelWD** [comment]
```
let old
function onUpdate (val) {
  // do stuff
  old = val
}

**Comment by mueller-jens** [comment]
Yes thats hiw i have done it actually, but i think a better way is to not have that global variable. But anyway ..
