### ISSUE TITLE
[Documentation] No link from "Virtual tables" to the corresponding "v-data-table-virtual" API

### ISSUE THREAD

**Issue by HendrikJan** [vuetifyjs/vuetify#20559]
### Environment

**Browsers:** Firefox 131.0
**OS:** Ubuntu undefined

### Steps to reproduce
When looking on the Virtual tables documentation (https://dev.vuetifyjs.com/en/components/data-tables/virtual-tables), there is no link to the v-data-table-virtual API page (https://dev.vuetifyjs.com/en/api/v-data-table-virtual/).

You first have to go to the Introduction page (https://dev.vuetifyjs.com/en/components/data-tables/introduction) to find the link to v-data-table-virtual. This is not intuitive.

### Expected Behavior
A link to "v-data-table-virtual" to be found on the page about "Virtual tables"

### Actual Behavior
There is no link, so you first have to guess that you can find a link on the "introduction" page.

### Reproduction Link
[https://dev.vuetifyjs.com/en/components/data-tables/virtual-tables](https://dev.vuetifyjs.com/en/components/data-tables/virtual-tables)

**Comment by MajesticPotatoe** [comment]
resolved in d795591
