### ISSUE TITLE
[Bug Report][3.7.2] VDataTableVirtual New Items may not be rendered if scroll position is not initial

### ISSUE THREAD

**Issue by grolu** [vuetifyjs/vuetify#20566]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.11
**Browsers:** Chrome 129.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use the Vuetify Playground link. You can either reduce the items using the switch or filter the items using the text input. In both cases the table will not render all items after resetting the switch / filter text. This only happens when the scroll position is not initial (at the top). The issue resolves itself if you start scrolling the table.

### Expected Behavior
All items appear

### Actual Behavior
Only parts of the table rendered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtWHtv2zYQ/ypEMCAOEMeOH01rZAOStuk2tOsQZ+2Gpn/Q0tkmQlMaSTn2gnz3HamHZTmnxoEMJDbvyOPvnjzy28OB0UHnIo5PlgkcjA7OLSxiyS38cqsYO1+2Q2552/KJhPZSaJtw6RiMjebAQ9Dm59uD7NftQcYRKMPR/XdOnYOYzS1Sh91uTnMT2ksuE0C64gvYYmxW9OJVzpmKFYTIcjtm2xngOpjjvKmQFql+Zgq/8xT+lBWKJQskNw7ogreHLGxPJeA+nu1VN/fCBnO2bC+iECTOk2BQHxZEMtI4jLVYcL1GiuQTP+EjTmCXEbduWmcjycLKtqcCZJiS2GZr2R7mujG24Kv2vQit06bf7W7UZmzJteDKmSNRqLsUCsINdwdSzsiRXXnbsBtniJLQQrWy7dB6znIb0Jkx0WR5VARcZ6qUbZgvz9EYCCIVlvBYYaXz9ZfUE+wdOifFxK7BqSXUjP1mTFJgNMkkXzS2EBtmI6Yh1lGYBNmkjZkdKg87IyExkQXC2Ju6YCFTitKIsffKJBqYneOfxyQMM4GOpISQhdG9YlMdLVJ+FLOWiiwTyo+FElbkqZF+4sggLVJHJ6UdO1tbVgH8ZdLds8Dzqjo9PVEliwl6MJr67DAsFAYTdY3QMgwec2kzxi6cTxW3YglyfYy542PA4/UiEuPs7dei0VBOnFichR5/PubPEwN66SByy5xFuJSZeI7G1N6tCJJP3d4aDFib75rpGWWZnGcG5nM+I4eM8OohjS3XNvNWoZR3oreiiaTHmANyU4SLs5MtWeedJC0Pae3YjqecgoPzTqlM4hD3FXE6C1ZxhEhCmPJEWvaQSnNVqHWUjxiisIlWm7ErbE7TETs8PN4Qs8o6Yt/KFnpI8wjnulLDbtYxHB6j3cVMIc04S+D4DtY4clX1kD2WZJbXj2NA17Tu0G/miJRh3CxayEdQMztnrQUtQfoptIg/tcAob/1ES8DCFtQo8g/GDLl27ZhbS7+Xfk9cua5auDxgzBkxt5ZBL5Vd5IuUY4xYf1ihp2qPWK9XYXhtcEHXfSo8hxaXdHunW4yK5k8C/BwAV594DcQeBXEHewYRT+saiNuM50D8Eq35jIZX3SmHNyDgndXBO32zN7yvfAnXiVIkwgGFsLJZgbDnLUgZcDswnoNwDPxSA/yHKf+0CV9THt6OpwLgoA7g6ba05wD8letJpD8kWCkJiBWhG4jDKowM4utaL5/tb0Mpgrsroag87lN5PCDyuNbH++fx2EZ6gV7md3SmVEtK4eaqcTOMrxpO5K9ChWMuJOVjqtAMiUx+03AmX2EZvBEhlSb97agp+ZiIwZ4Pwuby+OLfhP8OeEg9DY9yb68am3kI9poNwUu8lLliSIXfKyr8CPMNas23f/iNE/V2zrH1pABWU7U4SQiAwzoDviD+rgGm71cxXoRIjDtHRpEjRL/wurZU718HXX6MEz0jk4TyciWgNlF42mySfHI3AdB/U06mkrhPFOqBr4LNZck7gDjtaCiEVUMVYUi4+Kzh0/hm7p8LalJ558D4YUfjS3WDHc0cc6S26dopKkUcEofdwHfWzVUb31hfSk53XVTLsJNC+XFclykvKDdvI81lnZepQNyp5LkJG76bjAXewHVN00UV7B4RhrV960tOFNd0XWNFJKOQShSyLaytNvsnyh8Q20RBfcGhGocBAfKs4XMPD+YxQE3jSt5PCD8PfSQ2VxE/SPRx7SWZvuMR5abnr6H7O7r8DOHelkdsyqWBgvqY/siXBNECH+gcwkIz/9BWflhC0pS17FyYEydxi1M8O3m2f/c4MXgVglb3mPWPNhOzfZ9cUWDLQKXfuOK8U7yCHTweq0RK/+/7/wIHG+M=)

### Other comments
There was already an issue for this: https://github.com/vuetifyjs/vuetify/issues/18926
This issue has been closed. However, this is clearly a bug that renders VirtualDataTable unusable in our scenario with a reactive data source. While a potential workaround is to reset the scroll position when the filter changes, the issue could still arise when the data updates due to the dynamic nature of our source.

**Comment by rousos87** [comment]
Hey @grolu.

I have the same issue with virtual-scroll and search input. Did you find any way to fix it?

Thanks

**Comment by J-Sek** [comment]
Upon inspection, there is a bug in how browsers handle scroll after reducing content height in scrollable containers.
I was able to easily reproduce it even on the dumbest [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event).

1. Scoll to the bottom
2. Open DevTools and reduce inner element height from 200px to 20px
3. `scrollend` is not fired

![image](https://github.com/user-attachments/assets/28640abc-1f42-4f43-aa48-2722198f4484)

Vuetify waits internally depends on `scrollend` to reset scroll direction. In the scenario from the playground, scroll direction is changed upon `items` reduction, but is not reset and execution cannot go through this [if statement](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/virtual.ts#L199).
