### ISSUE TITLE
[Bug Report][3.7.2] VTextarea max-rows does not work

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#20565]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.11
**Browsers:** Edge 129.0.0.0
**OS:** Windows 10

### Steps to reproduce
drag the resizer of textarea

### Expected Behavior
number of rows is not limited by `max-rows`

### Actual Behavior
no limit

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVzk0KwjAQBeCrhKytRdxJLLjwFMbFGEcITH5IJ7Ug3t2QWms3s/gew3uXl+yTaU8xboeM8iAVo4sEjJ32QqihMcEzWI9JPCjbe+UaMI4MCWECISBzMKE8I+NRS3RgScs5JbghFT6vOYVnX3S3iIOx+ep+1k61S980rMBvWRHV/u2W743PRPVcP2nKSTE=)

**Comment by KaelWD** [comment]
It only applies to `auto-grow`
