### ISSUE TITLE
[Feature Request] @click:day and @click:event is missing in v-calendar component

### ISSUE THREAD

**Issue by RonaldTandazo** [vuetifyjs/vuetify#20574]
### Problem to solve
This would be very useful in various use cases, such as editing established events and adding a new event to the calendar.

### Proposed solution
Add the @clcik:day and @click:event functionalities of the v-calendar component established in predecessor versions such as those that were available in version 2.6.x

**Comment by blalan05** [comment]
Duplicate of #19020

**Comment by piris-jose** [comment]
I took a look at Vuetify 3's v-calendar, but unfortunately it wasn't what I was expecting due to the lack of the functionality you mentioned. I hope it gets its @click:day back soon!

**Comment by MatthewAry** [comment]
As stated before, this is a duplicate issue.
