### ISSUE TITLE
[A-la-carte] Component Lists (Unknown custom element)

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetify#2058]
Reporting a bug?
================
-  This may not be bug
-  I was using 0.15.1 version. I have just migrate to new version *0.16.1*.
-  The document of last version looks much cleaner. *Layouts* has code markup (templates). 

### Versions
vue: "^2.4.2"
vue-router: "^2.7.0"
vuetify: "^0.16.1"
node: v8.6.0
npm: 5.3.0

### What is expected ?
* It would be great if we have some guideline to use this components.
* Also will be great if you could provide the code templates that we had in *0.15* version for `Layout  —  Pre-defined` but could not see for *0.16*.

### What is actually happening ?
I could not get below elements to board:

* v-radio
* stepper-header
* stepper-content
* stepper-step

**Comment by nekosaur** [comment]
VRadio has changed and is now used inside a VRadioGroup, which is the component you need to import.

VStepperHeader, VStepperContent and VSepperStep are all included when you import VStepper.

**Comment by jrvaja** [comment]
Okay, I got it.

I was having difficulties as I am using the `0.15` old codes. I have imported to new version.

Well, can we have the `Layout  —  Pre-defined` demo codes?

**Comment by KaelWD** [comment]
Click the button in the middle of the demo page.
