### ISSUE TITLE
[Bug Report][3.7.2] v-navigation-drawer renders non-element root node that cannot be animated

### ISSUE THREAD

**Issue by KayvandenHeuvel** [vuetifyjs/vuetify#20584]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.11
**Browsers:** Chrome 129.0.0.0
**OS:** Windows 10

### Steps to reproduce
Wrap the v-navigation-drawer with a Transition

### Expected Behavior
To not give any warnings. This works with v-ap-bar and I expected this to work the same.

### Actual Behavior
[Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtUrFOwzAU/JWHl4BEiYANpZXYQIINwUAYTOJUTzi2Zb8EVVX/nee0aZMg2oXF8p3P987yva9F8EV679xV2yhxJzJStdOS1CI3AGPEuJ1J53agg4U1JNEovyeZfvHSBCS0Boys1TwXlSxVLgaa7rKRLS5l1M1KL79HJjuJxkAz5BjjEwBC0tH5eQWcXmPR+eRiqgvNZy99bRRhtZpqFlk6mPM7Qoktlpwtyvr93zlBo/nap3tiGh4jfc3PPzHopMfNP3jcHvWIJ8d+JUsPf3uoAV+a9iByfVWydFCjEWAYCo+OIChqtmqsnfUEa/Cqgg1U3taQcDmTKAfgQfyUOixhHhXnyYPS2sKb9bo8Sy7igK0lm4nNpWm07paPH/aM5TI=)

**Comment by KaelWD** [comment]
VAppBar doesn't have a scrim.

**Comment by KayvandenHeuvel** [comment]
@KaelWD But the v-navigation-drawer variant we use does not have a scrim. To my understanding the scrim is only present when v-navigation-drawer has a temporary option.
