### ISSUE TITLE
[Bug Report][3.7.3] Expand-transition doesn't work with V-Menu

### ISSUE THREAD

**Issue by piris-jose** [vuetifyjs/vuetify#20593]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Firefox 131.0
**OS:** Ubuntu undefined

### Steps to reproduce
- Click the Open menu button
- The menu will be shown

### Expected Behavior
The menu should be displayed with a nice and smooth expand transition

### Actual Behavior
The menu is shown suddenly, with no transition

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjkEKgzAQRa8yZF2VtnQjVuiyqx6gdhE1i0CchGQMBfHuHQNW3QRm8v77855E8F3xcC6PoxKlqEgNzkhSdYMAVcwGhSOQlxg0aYv3Rqivk9hn264RCWZ8DUPMgrFUyo50lGQ9xyZw3roA8x9P/paQ6VZjz0wi+B9eTiGk6qpIzNpQHO5LBqMD7Y3LnGnmanjymwzbbvXscsuwdPFw8Iv5JK75LT9fxAlHYz4/Pwti7w==)

### Other comments
If you replace "expand-transition" with "fade-transiton", the last one makes the menu fade correctly.

**Comment by KaelWD** [comment]
It's a javascript transition, you have to pass the component definition not just the class name:

`:transition="{ component: VExpandTransition }"`
