### ISSUE TITLE
Form not submited!

### ISSUE THREAD

**Issue by tuvshinjargal** [vuetifyjs/vuetify#206]

**Comment by cawa-93** [comment]
@tuvshinjargal, Please add a reproduce link

**Comment by tuvshinjargal** [comment]
<ui-modal ref="modal" size="large" title="Customer form">
            <form @submit.prevent="saveNode()">
              <v-card-text>
                    .......
              
                <div class="text-right">
                  <v-btn flat="flat" class="indigo--text" v-on:click.native="closeModal('modal')">Cancel</v-btn>
                  <v-btn flat="flat" class="ml-2 indigo--text" type="submit" >Save</v-btn>
             </div>
            </v-card-text>
            </form>  
        </ui-modal>

I updated 0.9.1 => not submited.
0.8.9 => submited done.

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by tuvshinjargal** [comment]
`<script async src="//jsfiddle.net/n319n07m/1/embed/"></script>`

**Comment by johnleider** [comment]
That does not work for me.
