### ISSUE TITLE
[Bug Report][3.7.3] clearing v-number-input with backspace resets to 0

### ISSUE THREAD

**Issue by thedaaron** [vuetifyjs/vuetify#20607]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 129.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type any number for example 3
Delete number by pressing backspace
Input rewrites value to 0 (i consider it as not wanted behaviour)
Delete zero by pressing backspace (validation is not called and no required message is visible)
Click outside of v-number-input and validation is called and required is displayed

### Expected Behavior
When i delete value by backspace or delete validation is called immediately on input

### Actual Behavior
When i delete value by backspace or delete validation is not called immediately on input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1znDAM/Ssqh8DOsEvSmVwysNNObz20h/aW5MAuYuMZY7vG3jZD+O+VPwgszaG5GKQn6UlPuh+SXh+Lz0rtzhaTu6Q02CleG9w/CIDyvK2V8r/eOEphaiZQR5d3CtsdUG+ZUNZMbgCNbfWQBGcyu+862SDfnmtukXBvXeDacuwJ8d8lQimsoca2UrxV+JNVDl3Vl+LLUy1OOEcWc+sHvbSUxv0wgC/8U3798f0bjGNZOHecv1gL4DxBn7JY6EZmf9RMGejR2CAf65TUBganSw5H2RELNjBCq2UHKYmfukQgSPQmdAGVi842S8CP9xbg9YrAfWi4KMj6ZZkmoqgekz7Fq2kRqj0MkwCujOS44/KUpVNemodIoprWaqwWkM3CZ6HUh6oCYTmHqyswzwplGzkckFrRYEu6NanDF0C6gZeXudhMPPki85i/ztQx8R/jxEYDsK/glngg7Z+k5Q0cEE4aaVsapAairDncRsolU/3nvUxlBTfXKyoufy+Jbq4vmB4v1jgdLG1yzXSxoClutSB/HruYGRAHjP/cVrzw6vUUs2yz4IozuZhdbzQTJ9Y+Zz4zVM/9snP46IlHessiHD2dezLmHnXP419GtWEc)

**Comment by thedaaron** [comment]
Also i cannot call validate by myself, because validate method is missing on v-number-input ref

**Comment by KaelWD** [comment]
> validate method is missing on v-number-input ref

It's there, it just won't show up in json.

**Comment by thedaaron** [comment]
@KaelWD You are right, sorry  [validate](https://play.vuetifyjs.com/#eNqVUz1v2zAQ/StXDZEMyFZSIEsgGSm6dWiHFl3iDLJEOUQpkqVIp4ai/97jh6IPeGgX2rx3797p3fGpjzpVZZ+k3J0NiR6iXJNWslKT/YED5OdtKaX76y6V4LqknKgQckFu2iNRW8ql0WMYQJGmOEQ+GE3hh1bUhG3PJTMEcXdb4Mow0iHifucIUmiNjW0Fv1b40UiLruoL/vml5CcyZWbz1o+aw2PFaPXL5f4MEodoP6rlmcuaSEc1LyEV2fc9uG5+iC/fv32FYcgzGw6mIX/pmo14U/NsZjZeu0pRqaEj2njPaSuF0tBbM1OoRIsqpIYBGiVaiHFisSUCQrzTvgsobHaymQPOk2uAMzkAT77hLMPbb0MVCgUTqHAUNwJDoNhDPxpgywhGdkycknjkxanPRKlxF7RRHJJpWokv9aEogBvG4OYG9EUS0QQNC8SG16RB3+rY4jMg3sDb21RsEh5jQXlI37+ppfwfPic06oF9AfeoA3H3Igyr4UjgpAhOS4FQgJIlg/sgOVcq//yvUl7A3e1KionXudDd7ULpeTHGcctxkmulxYDGvNWA3HrsAtMjFhiWEuPjwJSyu/AKks1KBzewc1k25bWkYSN9ZXs6vt3AdWf4ggJzSK+SHGfR0PzJFe9vI1k0FUy2ObtOK8pPtLkks/qp274UPvr6eOaZf4X4/qIhdag9nv8CQBakBw==)

**Comment by matt-duffett** [comment]
Have noticed a partial workaround for this is to have a min value on the NumberInput, however this only works when that value is > 0
