### ISSUE TITLE
[Documentation] Inconsistent Clipboard Behavior on Homepage (Create Vuetify Project)

### ISSUE THREAD

**Issue by atharvaunde** [vuetifyjs/vuetify#20618]
### Environment

**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Upon opening the homepage and refreshing it multiple times, the displayed code snippet alternates between npm create vuetify, yarn create vuetify, and pnpm create vuetify. When clicking the copy button, it does not consistently copy the correct command displayed in the snippet.

Steps :
1. Navigate to the homepage.
2. Refresh the page a few times.
3. Observe the code snippet, which displays various package commands. Click the copy button.

### Expected Behavior
The clipboard may not always reflect the command shown when the copy button is clicked.

### Actual Behavior
The copy button should consistently copy the command currently displayed in the code snippet.

### Reproduction Link
[https://vuetifyjs.com/en/](https://vuetifyjs.com/en/)

**Comment by atharvaunde** [comment]
Added a Quick Patch Here: [https://github.com/vuetifyjs/vuetify/pull/20619](https://github.com/vuetifyjs/vuetify/pull/20619)

**Comment by johnleider** [comment]
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
