### ISSUE TITLE
[Feature Request] File drag and drop area (VFileDrop)

### ISSUE THREAD

**Issue by MattTheCuber** [vuetifyjs/vuetify#20617]
### Problem to solve
VFileInput is great, but many times you want to have a drag and drop zone in your app. I know you can build one yourself using divs, but it would be great if Vuetify had a nice stylized component. This would be useful in websites/apps where the user can upload files into a server file management system.

Kind of like this:

![drag and drop](https://i0.wp.com/css-tricks.com/wp-content/uploads/2015/11/drag-drop-upload-1.gif)

### Proposed solution
Here is the JavaScript implementation: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

**Comment by frederikheld** [comment]
This would be awesome. In my current project there's still this empty area where "some time soon" I have to stitch together my own solution. Having this out of the box would be great!

**Comment by frederikheld** [comment]
There's another issue #20576 that asks for the same.

I like the design of this one here better though.

**Comment by MatthewAry** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/20576
