### ISSUE TITLE
[Feature Request] v-dialog compatibility with Google Place Autocomplete Widget (Preview)

### ISSUE THREAD

**Issue by no11111111111112** [vuetifyjs/vuetify#20614]
### Problem to solve
When the Google Place Autocomplete Widget (Preview) is placed inside a v-dialog, the ability to select from the dropdown via a click does not work. The arrow keys work to traverse the dropdown and the enter key works to select. The input works correctly when not placed inside a v-dialog.

### Proposed solution
Allow the dropdown to be clicked.

**Comment by KaelWD** [comment]
Either increase the z-index of the autocomplete menu or create your own with vuetify components and the google maps json api.
