### ISSUE TITLE
[Bug Report][3.7.3] VNumberInput doesn't allow scientific notation

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#20639]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Edge 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to type 'e' in VNumberInput, fail

### Expected Behavior
Users should be able to type number like `1e7` in VNumberInput just like HTML number input `<input type="number" />`

![image](https://github.com/user-attachments/assets/50616c93-fac6-4eab-b4fb-b1aa81468c0c)

### Actual Behavior
Cannot type scientific notation number.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjz0LwkAMhv9KuMVFLTpKFRxdHF2sQ1sjHNxHyOWKpfS/e70qikvI++TrzXVQgdviSLTuIqqdKgUtmVrwUDmAslvVRDnNovVOau2Q3yhB7SgKtKYOYV8p26y2lQLpCZNy0TbISQfpzQQaz3fkHWzoCcEbfU+14rvrcs4Dp7zyw8vi/+5EZltl8WM3ydCyJoGAEmfX2pJngQEYHzDCg72FRfp0Mc3O3alPjUsXjcnh9gJhFVus)

**Comment by J-Sek** [comment]
It is by design. Regular people would consider `1e7` value a bug and annoy devs with support tickets. IMO if Vuetify would ever support this notation, it should be behind an explicit boolean prop.

@kingyue737 could you share what type of application you are building and who actually would type values this way?

**Comment by kingyue737** [comment]
@J-Sek
> It is by design. 

Maybe not. It has been marked as "bug".

> Regular people would consider 1e7 value a bug

HTML native number input supports `1e7`. I didn't see regular people consider it as a bug. I think `VNumberInput` should have the same behavior as `<input type="number">`

> could you share what type of application you are building and who actually would type values this way?

I'm building a "current meter“ related app, mainly for engineers or researchers. They need to type both regular number like `10 A` or very small/large number like `1e-13 A` or `1e7 n`. It's not acceptable for users to type `0.0000000001`

**Comment by J-Sek** [comment]
Apologies for not being precise. I meant "regular users" which interact with controls like VNumberInput would without a doubt consider the control misbehaving if it accepts anything but numbers and typical formatting signs and separators. And once QA find out, convincing them it is a "feature" might be a challenge ;) Overall I guess that significant portion of devs using Vuetify might not be happy with dirty JS internals reaching end-users even if native controls behave the same.

Again, I don't mind supporting it behind a new `scientific` prop. Maybe we could make an extra step with instructing the component to display numbers with this notation above certain number of digits.

Until we get there, would you consider `<v-text-field type="number" v-model.number="..." />` a good enough workaround?

**Comment by kingyue737** [comment]
Thank you for your patient explanation. I replaced all the vtextfield with vnumberinput since the arrow buttons of latter are more in line with the style of vuetify and has intellisense for props like max and step. If the team doesn’t decide to fix this, I can patch vuetify locally
