### ISSUE TITLE
[Bug] v-select with autocomplete changes the items text

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#2066]
### Steps to reproduce
Select "Alaska" in the select component.
Reopen the dropdown and look at the items.

### Versions
0.16.3

### What is actually happening ?
Almost all the state names are wrong. eg: American Samocan Samoa, Arkansasas

### Reproduction Link
https://codepen.io/anon/pen/jGZQpo

**Comment by KaelWD** [comment]
> Massachusettchusetts

lol
