### ISSUE TITLE
[Bug Report][3.7.3] v-combobox placeholder is not consistent with v-textbox

### ISSUE THREAD

**Issue by giuliohome** [vuetifyjs/vuetify#20660]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Google Chrome, Microsoft Edge
**OS:** Windows, Linux

### Steps to reproduce
A placeholder bound to an empty but non null model value

### Expected Behavior
The combobx placeholder should show up as the v-text-field placeholder does

### Actual Behavior
The placeholder remains hidden instead and strictly requires a null 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkM0KgzAQhF9lycUWar0XW+ihT1F70LhqIH8kqwjiuzeJpUivvSy7w/Axs8+FeceLu7XnaUR2YSWhsrImvFUaoJzy2tq0poMbTbXQ6D5SEglnyjuBsoUpV6ZFea2Y8n3FIJA4Dka26IL20IQOaEBQ6H3dY3AUX9KOyI1qTGPmP3hl8Zs2KluZstiVDKfnTlgCjzRuXYWyxhEs4LCDFTpnFGThP1m0AwSuJwiJ4Bodhyw7RuiGCQC2nvQoZRqvN49udbg=)

**Comment by MatthewAry** [comment]
May be related to https://github.com/vuetifyjs/vuetify/pull/17122

**Comment by giuliohome** [comment]
> May be related to #17122

_Maybe_ note also the git blame at [line 421](https://github.com/vuetifyjs/vuetify/blame/master/packages/vuetify/src/components/VCombobox/VCombobox.tsx#L421) pointing to a [search empty (but not null) ](https://github.com/vuetifyjs/vuetify/commit/d6a500be40baaa44d58c151fb898cde8ab875e1a#diff-6ced29d29b4c82dda92cb46413480ef7c0b84c00508f9cfdad342dbf340cfa19R324)condition

**Comment by giuliohome** [comment]
Also the `wrapInArray` can be problematic, especially in conjunction with the logic around the `model.value` and how the empty values are handled. For `null` or `undefined`, `wrapInArray` returns an empty array `[]`. When `v` is an empty string `''`, the `wrapInArray` function will wrap it in an array, i.e., `wrapInArray('')` will return `['']`. So, if `model.value` is set to an array with an empty string `['']`, it won't trigger the same behavior as an empty model `[]`. This can lead to the placeholder logic being broken because the model value isn't truly empty even if the input visually appears empty.

**Comment by yuwu9145** [comment]
I think the previous conclusion of whether empty string is really empty is:

- For select components, empty string is legit, `null` & `undefined` are real empty
- For text field, empty string, `null` & `undefined` are all real empty

So in my opinion, the behaviour is expected, the real confusion is it's missing in docs and it's not clear to users #https://github.com/vuetifyjs/vuetify/issues/18737#issuecomment-1841165502

**Comment by giuliohome** [comment]
Just to know so that I can tell my point of view to my colleagues in my company, have you considered what I have noted here?

> This contradicts the logic in `onUpdateModelValue` which [correctly resets](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VCombobox/VCombobox.tsx#L421) the `model.value` to `[]` also when `v === ''`.

Thank you

**Comment by giuliohome** [comment]
I have already deleted my fork of vuetify, I'm going to unsubscribe from this thread, I have no time to waste, sorry, bye

**Comment by J-Sek** [comment]
> * For text field, empty string, `null` & `undefined` are all real empty

VCombobox is really just a text field with suggestions, so it would make sense to make recognize empty string as no value. But also, opinions aside, unless empty string is a `value` in one of the items - null, undefined, `''` there is no visual difference from end-user perspective.
