### ISSUE TITLE
[Bug Report][3.7.3][VTreeview] update:activated is fired twice on leafs

### ISSUE THREAD

**Issue by r05323028** [vuetifyjs/vuetify#20665]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- open the browser console
- click on a leaf
- see two times the message 'update:activated is called with ' +id

### Expected Behavior
the event is fired once per click

### Actual Behavior
the event is fired twice

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vktz2jAQ/isaX4ApjxpCaDyEKW0vvbSXTnsIOcjSEjQjS64s28lk+O+VbBzLYB5p05Ot1X672se30t2zlygyWsbxMEvBC7y5hijmWMNiJRCaZwOtADIGuV0iFDCzn9yuvOK78kopkVwqI8yxEkw8VGJMNMuwxiGHUmBBgwzzFKwFWunJGMQAc16uPqYxNf6DHRpooYtuF8aNSCSHIZcP3c6+FmIJIsaI+cuZ3qDOO0Z7pYfFfFTHYeKaj5wgzTIhisW6CBgeY6k0orDGKdfouTyS8YQD1O3ZQ3R3sjKaJEB31RpV6rttGiC/70o00xwC1DHZ5oxgzUw8KOg0dMiGcapANOwWtguD4/6Llc+Yg6BYoQDhOO6gbcNOBZg4gI2SEZxWv6rVf0GYaKmidsC9s3J3DlIwbU3BF0nSCIR+RfzNZWn8ei+I2oHpZs3WT/vmT7podVO5mh3Ycd0ZErW5OuuuzvyHOvNMUHg0adfJYZmaoJsaFEqpE61wfBLolq2tfO1aB73SVgv//dFiRIZqimE+frty+E1qvX09fIdq2SDU4qKC+A7fsgHBil4Gc3iXDXLTADL/73W8mML+MQ7ngktMXzvD/Os62O9EyxDsDIvp+thQ8mc14JvMIDqPcNj0IzVTzDSfQWx0xP96kPk3rVn4ySjIfxxj4+PUqU5/4OE8dUrTfp2JTzhhBHH8JFM7eFEUX7X31w7qMGBJMyyIuVs1kI1gv1O4xIBDhiXnCIfGsb1MDJQy1QY9O3lKww5dvgqtpD2LzI51w3jqXIJSrMGkjABiFklT84CQltw4Y5f1RiXd9oqfrX1QvDwhvG3fmwynQ3/s2Z/ZcOLd/wH/TVRi)

### Other comments
this issue was fixed in 3.7.0 (#20106)
but I have encountered this issue again in 3.7.2+

**Comment by ministerstvopravdy** [comment]
Can confirm this as well... Made my playground as well https://play.vuetifyjs.com/#eNptUsFuwjAM/RWrl4I0QHCsAA3tF3ajHEJqIFuaRIlbNCH+fU5pacumSm38nv1iP3d/S4KXi51z87rCJEvWhKXTgnCbG4B1PRPONccmkNaQUAZ9CzUgecRa4bWDADLFKmGTJyWaKuRJzxRogqIfpqQtnZA0JDlUtSBx1NiDUWpWC10hF6limN9QpEhHyogSh6RHqryZ2eMX8i1PuJ6VtkCdtXdh0Xb5yUPsOmyo8165grFRQW5y6p4n/nER5sy1PfdUWXQOLl4tjMjD4fVi4DyHQXrlCAKP8ViAKp31BDee7AR3OHlbQspLSyPJqoHgzyCwidmT/WE6TgpM7B893bomVZHB8q2Lop0ZpISBlmmL3tvvqGT1X8lqXHLob3+1ixuZTGGz7URjltU41/Y86YRTuqgAJ+UxAF2VRLhe0PRSIFutidRKfvPBGoh/JRje9bQxCKCx4B6NfljLpib3N1Np3bwOvwbr9oc=

**Comment by digitalniweb** [comment]
Can confirm this as well... Made my playground as well https://play.vuetifyjs.com/#eNptUsFuwjAM/RWrl4I0QHCsAA3tF3ajHEJqIFuaRIlbNCH+fU5pacumSm38nv1iP3d/S4KXi51z87rCJEvWhKXTgnCbG4B1PRPONccmkNaQUAZ9CzUgecRa4bWDADLFKmGTJyWaKuRJzxRogqIfpqQtnZA0JDlUtSBx1NiDUWpWC10hF6limN9QpEhHyogSh6RHqryZ2eMX8i1PuJ6VtkCdtXdh0Xb5yUPsOmyo8165grFRQW5y6p4n/nER5sy1PfdUWXQOLl4tjMjD4fVi4DyHQXrlCAKP8ViAKp31BDee7AR3OHlbQspLSyPJqoHgzyCwidmT/WE6TgpM7B893bomVZHB8q2Lop0ZpISBlmmL3tvvqGT1X8lqXHLob3+1ixuZTGGz7URjltU41/Y86YRTuqgAJ+UxAF2VRLhe0PRSIFutidRKfvPBGoh/JRje9bQxCKCx4B6NfljLpib3N1Np3bwOvwbr9oc=
