### ISSUE TITLE
[Bug Report][3.7.3] V-List-Items should not have property "aria-selected"

### ISSUE THREAD

**Issue by kmmerc18** [vuetifyjs/vuetify#20666]
### Environment
**Vuetify Version:** 3.7.3
**Last working version:** 3.7.2
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Run the axe DevTools Chrome extension on the page to view accessibility issues : https://www.deque.com/axe/devtools/chrome-browser-extension/?utm_term=axe%20chrome%20extension&utm_campaign=Search+-+axe+DevTools+Extension+-+Branded&utm_source=adwords&utm_medium=ppc&hsa_src=g&hsa_ad=626089536231&hsa_tgt=kwd-1186988429008&hsa_mt=p&hsa_ver=3&hsa_acc=7854167720&hsa_kw=axe%20chrome%20extension&hsa_grp=142979637051&hsa_cam=17378411167&hsa_net=adwords&gad_source=1&gclid=Cj0KCQiA_qG5BhDTARIsAA0UHSLdeJ9Sqz7AWxRyxMgv0xbuOZUaa288baPX3SoHfQ84FeVmFKc2JvEaAlnmEALw_wcB

### Expected Behavior
No issues related to aria-selected should exist

### Actual Behavior
Three issues appear under the title "Elements must only use supported attributes"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkMtqw0AMRX9FaJNFYwfqQsC4gS4L/YM4C9dWihp7ZpjRGIrxv1d2Xk52o3MPYnT3A344l/aRMMdCqHNtJbQrDUDRJ5Vz83MeamukYkP+gmbYchBolYb3Eq2hEm/pLU9Y994pQJ8crVffABvISlxm+Yn+puiJCktLylefugtW8AJPRojfV+fLenXYhdhBY1vrIbBA1ZGA3hCoFpLooWrYceCazQ9Qy7Lctys2i7/fD77Qayk6PrYykXNpxWZRZjQNHVVqcI1a1imkv8EabXwosQ6hxHx/GDXjzlkvSVe5hXCGkzSMI45rzNK39HWrepZu0wzX4iMd/gHH6ov2)

### Other comments
Looks like all v-list-items in the latest version of vuetify have the attribute "aria-selected=false" by default. According to the Deque tool, this attribute should not appear on v-list-items

**Comment by gosear** [comment]
![PixPin_2024-12-04_15-50-49](https://github.com/user-attachments/assets/91751c36-d49e-4746-afea-355dcfe4018a)
![PixPin_2024-12-04_15-52-42](https://github.com/user-attachments/assets/97011054-7776-4fc6-8c39-0723cc8e2f09)
But `VListItem` component still have the "aria-selected" attribute when It in `VListGroup` activator slot.
Please see this [example](https://vuetifyjs.com/en/components/lists/#sub-group) on the official website.
Did I misunderstand the fix commit ?
@KaelWD

**Comment by kmmerc18** [comment]
@KaelWD From your official examples, why would this still have the aria-selected attribute on the v-list-item children?
https://play.vuetifyjs.com/#eNqVks1qhDAUhV/lki5mBtT5sXQgOEKXfQZ1EUxK0yYaTLSC5N2bGAXptItx4z33nHxerxYTelUqGXqGMMoMk0oQw/KyAciGuCYd9SVALYjWtxLJMSa9aUsU2pKM8Ten5sNZ6ekU2vPp+bzg2gQBgLmje8R8XwEAXsaGG8Gc1xDJflkDEb23OF2NPDsGdBjTCT+nE9lx8wJO6rrjKqTYqNrOAGXvpBcGpkCixBAM+wPcctgvvfBYjaFYNazxcPkZMezeXAqezrto63GK4bzp2E39P+RyD7k8DEnvIemfkGqp7GEurN/bsikUIcGbL5186rZxP8RUolq7b4WLyjqPS7/EWBK1CYSmD03WIhuhNHlOLlcXT5Nr8oIi0/Ws+gEWh6qj

**Comment by cschweda** [comment]
I still see a11y errors in the list-item children. Checked with latest axe-core 4.x.

Any updates on when a fix might be implemented?
