### ISSUE TITLE
[Bug Report][3.7.4] The v-data-table-server is duplicating results with the same key

### ISSUE THREAD

**Issue by Some-Random-D-e-v** [vuetifyjs/vuetify#20675]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.4.37
**Browsers:** Chrome 130.0.0.0
**OS:** Windows

### Steps to reproduce
In the code, I added an extra object to the data array, as shown below:
```Javascript
{
  name: 'Frozen Yogurt',
  calories: 159,
  fat: 6,
  carbs: 24,
  protein: 4,
  iron: '1',
}
````
The table is using the `item-value="calories"` attribute.

Even after replacing the data, the issue persists: duplicate items continue to appear in the table.

Steps to Reproduce:

1. Set "Items per page" to "all" , 100 or 50.
2.Click the sort button for the 'calories' column multiple times.
3.Observe the following:
A warning appears: "Duplicate keys found during update."
The row for "Frozen Yogurt" is duplicated.
Some values sort correctly, while others do not.

### Expected Behavior
A warning about duplicate keys appears in the console. The expected behavior is either for the result to be updated correctly, or for the operation to have no effect.

### Actual Behavior
A warning is displayed, and duplicate key items are added twice. When replacing the table data, the old duplicate key items persist in the table.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNWG1v2zYQ/iucgdXyZskvidPWSLJ16bpl7bYA3QYMST7QMp1wpUmBopJ5gf/7jm8iJStzUHTY8iGWeMfjcw/vzb586JUyH70qiuyuIr1571iRdcGwIqdXHKHjAt2lgs9zRvMPJ1e9Ff5Afi2WIE4GV71T+4gUXjCC7jCryPGosBvvUhDh1IjSksg7IvU6AntrsSRsTuGgMi2ITAt8Q8C2Wbgg8gJer3pWeX5L8JLIEsTuqZYYdVi3ts/1W1OWMsJv1C2oKKEwa2owgZeU34DQPdWSkmCZ6132wa9rk6lxEUQ5ZkJSUpv7ujJEzEWhqOAalbYanWg4AVY8ucBCyYSaq5UQygm1WNbP+m0ZvRlKFflTpStK2DIW1JzCuRyva/L8X85wqTGtcTpty5aEl1RttE9iXeBctRUAbk5uBQPuQem94QTpU7Isa+ve0iVJl0RhyspYcno8irHHPo4aTn6Uy+3L+Bfc/pFyuq7W6LGj1KbQYcGr9QLC/NOyAi8+KuCxkZywfyfJQNJQg9cyl7RQqCSqsslJ14WQCj0gSVZDdI8VXOkWraRYoz5Ugb7eBfxBJCtgqgTDqkQn6NKiePDIdBTMUf+NFH8Rjn4XN5VU/aGXeq7maDJ7Wa+usJqjo0hJLkBjelivFFIoQvkchSUqoQKh/sTb3rrP/y2QHwhjG7QgmHehOHg+a6IYt1G87EARlByK8T4Ub6l6izt5mE1eNBFMd4g4ChhrCM/bEI72QfgWcpDKLgjTo2kTwmT3Lg52IQQlB+H5PgjfQW0nciGhe3RexiyYfATHYQiaGsdBFhZ9VOxl4zwnKAcga1Rivryn+W0nMweBZ4MonOQARQohSLPA1lPD9J1gjBai6OTlZet+xllY8GEaoujxMJ3uQ3FWFTlMFZ0gxq1MOciC6z5Qn0bGi30wvhecbKAZLLqAHI5bCXOwy8aLDiBHWXDAATmc7UPyWvCqM20PZ607mQbrDsRs0sXGTqxOW7dyHVd8Tu7fwIW8hs7yeNH/b0B6iGEMBYTJAJ2ceoDRNJiZaU278GCmNzg5cm2IzFTYWMvsxIi25qhtTIpWeXVxDtbcQbjc8BytCPTO5AHpEXZoT3ET7BCV0GO/2cCnnZm2g0CihFYsuT4aXUDXpSVJJCkFuwO4tSvWHfULXRNRqaThpuPTQCsVhmYOPGgQKEWTAfqiAWV3C+FL2GA3frlH10hB2w8CWQnfBWD8z1aUKSITLd9BBpe4QklzRXujmch0CKFnz9rSz7QlI8yUeCfuiTzDQMwgozxnFRyfRPubKoOmrYhp/+cYX2FWNnw01xy/jkaIgIdcpUtamrmK6xENVgjcKMfyj3JUwNwE31tKaC0gXwjBoNWn9ogns+BTposJQ2rQOD1BP5nR0jPgJZ/ScaeoZNXQ2zaO0P7YuHa5snOii0nQeUs2OsiM9uX4OvtANo+p/ixhzm4oC73S4tIktVZJEkjfxW4+BKP4N5f7+NJBMSm9q7jwiotHFR0xEc6TE9SHeMz76CtvIPVHzv1D6kQt0ht0Nq7AAoIkphwKm05Q57HJN5OsQ525DQuubEAJciWu3l8XOGvFl7Zo93aIZuNxveBFttoaaFEFcPUBUEHwJzOja8Xui7mTtPuFooqZhmHLB0om4/GNKdOQPYPQQTCjN7rqGz/DsmZdZ+HcRnC9DsEEyroS7LTT+sgzlyX9oVP3aQML/jjgs9+x9Q0GpBqe2wmdbP+mM93eGttMw9u/EXqA7oKNra4z7t98Dt0SJZ+Hnbp9dm+7jm4tapT+5mKx+1XEiXRRiITh9xQnt0Hkxgdd3e1yvx+t19WsQ+ZaZEOyqniuf00xUMxh/9hno/7qsNf9P5Q018Uz17brKUTbqaeP2HgchtDL61eDdw63YMch05HMccNoFPJPDoi/uu0gU7eEJz5nXaJqB+KC1jXJGP06s+pbCJ7qJS9v0xC1AJvqJsXNt/9EOzBsT1Km1fjd75UEYwmMSSTj4t71XGvI2vDufqyd45H9oQJ+ouhth7xizPy7/hsUE/gC)

I also managed to do this for the v-data-table
https://play.vuetifyjs.com/#eNrNkj1vgzAQhv/KyUsWAmq7IRKJIW2HdGq3kOGAi2IJjGUfqFKU/15jh4ZkbId28cd7750f27c7CWuqJNc6HnoSqciYWt0g07pQANmwRK390m+qTjFKReYiebFGxiVj2RCk0qXbVSH8XIh1lszjUyEn3lYalXBQlswAMlsZqRkscR8oXJpl8NVhBbtQ7zTByDqFh2jaKWwphUV+MLJCBZuG9BEVL74NVlMlyTrPtvvs6pEIMLjx6qolsbO8kinl0Bm6Ro5YSsYx+I4DKoURPDuDZTt5zpf5hvDpnnArO/VDqrdN/vFroMd7oBdp8DC76B891L/8yiSBOI6hddHQh6O8Hxs3NKtrU3GOVN80fth/ATv+BmQ=

**Comment by MatthewAry** [comment]
The [documentation for the `item-value` prop](https://vuetifyjs.com/en/api/v-data-table/#props-item-value) in VDataTable (and also VDataTableServer) says that `item-value` is used as the key [and it does](https://github.com/vuetifyjs/vuetify/blob/1ba11c95343ac742d7e0f011129dc0221497d679/packages/vuetify/src/components/VDataTable/composables/items.ts#L51). Keys are supposed to be unique otherwise Vue can have problems understanding which DOM elements to update. You are using the `calories` field as the key here and in your `desserts` object array you have two duplicate objects, both with the same value for `calories`. Thus, _you do have duplicate keys_. The error message is correct.
