### ISSUE TITLE
Toolbar & navigation (Flexibility missing in 0.16)

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetify#2067]
Bug
=======================
In the *0.15* version
- we could easily switch navigation position `right` or  `left` by passing value from computed property.
```
<v-navigation-drawer
    class="pb-0 no-overflow vuse-sidebar"
    height="100%"
    persistent
    :mini-variant.sync="miniVariant"
    :clipped="clipped"
    v-model="drawer"
    :left="navDrawerPosition === 'left'"
    :right="navDrawerPosition === 'right'"
    enable-resize-watcher
  >
```
- Based on nav position (`navDrawerPosition`), `main` element sets its padding `left` or `right`
- Clipped was also working fine. In Toolbar, it will auto adjust space for `navigation-drawer`.

### Versions
"vue": "^2.4.2",
    "vue-router": "^2.7.0",
    "vuetify": "^0.16.1",
    "vuex": "^2.4.1"

### What is expected ?
It would be great, if we could have *0.15* flexible functionality here as well.

### What is actually happening ?
In the *0.16* version
- Above things, we complicated.
- Toolbar has new property in this version called `clipped-left` & `clipped-right`. If we don't set value and we move clipped == false state. It still keep space(width of menu) in toolbar.

[See the file](https://github.com/jrvaja/vuetify-0.16/blob/master/App.vue)

**Comment by jrvaja** [comment]
I would rather describe this in very short words.

In version *0.16*,

`padding` for below elements needs to be fix on change `navigation-drawer`'s *position* with/without *clipped* :

- `<nav class="blue toolbar toolbar--fixed" style="margin-top: 0px; padding-left: 0; padding-right: 300px;">`
-  In `<main>` tag, `<div class="content" style="padding: 64px 300px 0px;">`
- `footer` tag

**Comment by johnleider** [comment]
I'm adding a fix for the right prop changing on the navigation drawer, but the other issue is due to your comparison/logic:

https://codepen.io/johnjleider/pen/oGqNdZ

**Comment by jrvaja** [comment]
@johnleider Thank you!
No problem. 

This is add-on feature. If I completely switch to left/right from the beginning it works. But once I start swapping the position and clipped/unclipped. It massed up.

## Just to be on same page
Ref: [https://codepen.io/johnjleider/pen/oGqNdZ](https://codepen.io/johnjleider/pen/oGqNdZ)

**Step 1**

* Click on `CLIP LEFT TOOLBAR`
* again click on `CLIP LEFT TOOLBAR`
*It works like charm*

**Step 2**

* Refresh
* Click on `NAV RIGHT` (*here is the problem*)
   * Left side still leaving space for `Drawer`. It should clipped to left.
* Once I tried to clip it left by clicking `CLIP LEFT TOOLBAR`, toolbar does clipped to left. But drawer at right does not looks good.

**Step 3**

* In the same stage, click on `CLIP RIGHT TOOLBAR` (this is good.)
* clipped false to `drawer` does not reflect perfectly.

## Problem
If I have drawer at left initially, if I move it to right by passing argument.

* Clipped works
* On un-clipped mod, 
   * Toolbar overwrite the drawer
   * Toolbar left, main left, footer left padding should be removed
   
This is what was happening smoothly with `0.15`.

**Comment by johnleider** [comment]
I'm pushing a fix for this, however, even with it, the logic I initially proposed has to be changed slightly, but everything does work wonderfully.

https://codepen.io/johnjleider/pen/oGqNdZ
