### ISSUE TITLE
[Bug Report][3.7.4] VList v-model:selected not working correctly with objects

### ISSUE THREAD

**Issue by Husky-70** [vuetifyjs/vuetify#20685]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When using v-model:selected with array of objects on VList, the default items are not being used by the component, they dont show up as selected. 

### Expected Behavior
VList's v-model:selected should support array of objects

### Actual Behavior
When an item is already selected in setup, it does not show up as selected in the component, it gets duplicated when selected manually

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UkFuhDAM/IqVC620FMGhB8RW6rFvAA4UslWqAFFiqCrE3+uEhQaqXlbaAwR7xsaeTD4xo+voVamnceAsZRnyVskK+UvRAWRjWCnlPl1Q9x1WouP6mnJJ3X9t4ZUlgR5zLthzwTwMYJoMl7xG3sTz7ANUJoVBPwWQCprGtnFnwfboGLZ9w2W6diTe1vzIXYDQoKbVPr6JWsvKGFEfiZrjoLuwf/8k/h6yQ4RjJQduJ2qOlQ5GgdLC7twzIl+kyKl0g2zJPWVLbpbtjtrY+NdiC+q70GYWk2aRZ14KTa2FQloCh8XDolW9Rpjoli8ww0X3LQTk+8DSgcTvDLpZDZwhX344gWhSiE/gxk4heCMc4gDmk09IDoRkJZR+782f1J9meMj/714+/i1L1rLYolm0LEirsfnUDVK6V/kD+pgdzg==)

**Comment by MatthewAry** [comment]
Hey there. I was able to fix your problem by making a small change. Please see https://play.vuetifyjs.com/#eNq1UsFOhDAQ/ZVJL2iyiHDwQFgTj34DcEDompoCTTtgDOHfnZYFC9422QO0M+91OvP68okZXUdvSj2NA2cpy5C3SlbIX4sOIBvDSim3dUHdd1iJjutryiV1/72FV5YE+sy5YC8F8zCAaTJc8hp5E8+zD9AxKQz6KYBUUDe2jFsLtkfHsO0bLtO1IvG24kfuAoQGNY32+UPUWlbGiPpI1BwH3YX9xxfx95BtIhwrOXDbUXM86WAUKC3s1j0j8kWKnEo3yJbcU7bkZtnuqI2N/yy2oL4LbWYxaRZ55qXQ1FoopCFwWDwsWtVrhIle+QIzXHTfQkC+DywdSPzOoOvVwBny5cIJRJNCfALXdgrBO+EQBzCffEJyICQrofRrb/6k+tTDQ+4uy5/L8vE/KVlJsUWzaBmHBmHzqRukdL/yF3KdGVI=

When comparing values in arrays, the comparison is made on the memory address of an array value and not it's internal value. This is why you're not getting the desired behavior.

**Comment by Husky-70** [comment]
> Hey there. I was able to fix your problem by making a small change. Please see https://play.vuetifyjs.com/#eNq1UsFOhDAQ/ZVJL2iyiHDwQFgTj34DcEDompoCTTtgDOHfnZYFC9422QO0M+91OvP68okZXUdvSj2NA2cpy5C3SlbIX4sOIBvDSim3dUHdd1iJjutryiV1/72FV5YE+sy5YC8F8zCAaTJc8hp5E8+zD9AxKQz6KYBUUDe2jFsLtkfHsO0bLtO1IvG24kfuAoQGNY32+UPUWlbGiPpI1BwH3YX9xxfx95BtIhwrOXDbUXM86WAUKC3s1j0j8kWKnEo3yJbcU7bkZtnuqI2N/yy2oL4LbWYxaRZ55qXQ1FoopCFwWDwsWtVrhIle+QIzXHTfQkC+DywdSPzOoOvVwBny5cIJRJNCfALXdgrBO+EQBzCffEJyICQrofRrb/6k+tTDQ+4uy5/L8vE/KVlJsUWzaBmHBmHzqRukdL/yF3KdGVI=
> 
> When comparing values in arrays, the comparison is made on the memory address of an array value and not it's internal value. This is why you're not getting the desired behavior.

But v-select works with array of objects, why shouldn‘t it work v-list?

**Comment by MatthewAry** [comment]
> But v-select works with array of objects, why shouldn‘t it work v-list?
The comparison operation works differently with VSelect because it's comparison function (which is used to determine what is selected) is designed differently to support a broader set of use cases. Clearly, what's happening here has more to with the way arrays are treated in Javascript and in most languages.

```js
let arrOne = [{ a: 7 }, { b: 8 }, { c: 9 }];
let arrTwo = [{ a: 7 }, { b: 8 }, { c: 9 }];

console.log(arrOne[0] === arrTwo[0]); // false
```
