### ISSUE TITLE
[Bug Report][3.7.4] NPM Webpack reported moderate security risk

### ISSUE THREAD

**Issue by LarsEmbloom** [vuetifyjs/vuetify#20693]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
With NPM run: `npm i vuetify`

### Expected Behavior
No vulnerabilities found

### Actual Behavior
The following vulnerablity is found:

```
webpack  5.0.0-alpha.0 - 5.93.0
Severity: moderate
fix available via `npm audit fix`
node_modules/webpack
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

### Other comments
Output from `npm ls webpack`

```
`-- vuetify@3.7.4
  `-- webpack-plugin-vuetify@2.0.1
    +-- file-loader@6.2.0
    | `-- webpack@5.88.2 deduped
    +-- null-loader@4.0.1
    `-- webpack@5.88.2
      `-- terser-webpack-plugin@5.3.9
        `-- webpack@5.88.2 deduped
```

**Comment by KaelWD** [comment]
It's an optional peer dependency, you already have that version of webpack installed.
