### ISSUE TITLE
[Bug Report][3.7.4] License banner missing in build files

### ISSUE THREAD

**Issue by OwlHowl3** [vuetifyjs/vuetify#20692]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.4.31
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Build the project that uses Vuetify
- Go to dist/.js file generated
- Look for Vuetify License Header

### Expected Behavior
License banner is present in build files

### Actual Behavior
License banner is missing in build files

### Reproduction Link
[https://github.com/OwlHowl3/barebone-vuetify-test/blob/main/dist/assets/index-p3nkI8pW.js](https://github.com/OwlHowl3/barebone-vuetify-test/blob/main/dist/assets/index-p3nkI8pW.js)

### Other comments

**Goal:  Fix possible license conflicts in applications using Vuetify due to Vuetify license not being included**

The build files of projects that use Vuetify are missing the license header. 

The reproduction link points to the dist of a barebones Vue & Vuetify project which is missing this part:  

```
/*!
* Vuetify v3.7.4
* Forged by John Leider
* Released under the MIT License.
*/
``` 

Issue is present in multiple apps presented in "Made with Vuetify" section, e.g.:
- https://demos.themeselection.com/sneat-vuetify-vuejs-admin-template/demo-1/login?to=/dashboards/crm
- https://berrydashboard.io/vue/?ref=madewithvuejs.com

The legal comment is present only in dist files and this is generated by rollup config. However, the "main" and "module" properties from "package.json" point to "lib/framework.mjs". After adding the legal comments on top of this file and building the project again the license header will be present in project bundle. Not sure what is the solution, this is where I stopped the investigation.

**Comment by MatthewAry** [comment]
Forgive me, I'm not really sure why an MIT licensed project, which is maximally permissive would need to be concerned with ensuring it's license is visible in builds. I believe that this concern is only necessary for projects that require attribution, viral open source, or other restrictions.

**Comment by KaelWD** [comment]
Yeah this isn't really needed, the license only matters if you're distributing unmodified source code without attribution.
