### ISSUE TITLE
Unknown custom element: <v-subheader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#207]
Code snippet - 
  <v-row>
        <v-col xs4>
          <v-subheader>Visible</v-subheader>
        </v-col>
        <v-col xs8>
          <div>
          <v-text-field
            name="input-10-2"
            label="Enter your password"
            hint="At least 8 characters"
            value=""
            type="text"
            class="input-group--focused"
          ></v-text-field>
          </div>
        </v-col>
      </v-row>

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by vaishali-ghayal** [comment]
@johnleider please check https://jsfiddle.net/12r5zjgu/1/

**Comment by hemantrai88** [comment]
@johnleider Fiddle for the text field example with same errors https://jsfiddle.net/kq5vxw23/3/

**Comment by vaishali-ghayal** [comment]
@johnleider It was version update issue. The version I was using was not updated. Now it works fine.

**Comment by rahmatnazali** [comment]
> @johnleider It was version update issue. The version I was using was not updated. Now it works fine.

Hi @vaishali-ghayal, sorry to bother.

I faced same problem, already tried to update the vue and vuetify but the error stands.

Could you give me reference to "version update issue"  you mention and how you managed to solve it?

Thanks in advance.
