### ISSUE TITLE
[Bug Report][2.7.2] V-tooltip on button opens and closes immediately on click event. Click the buttons on demo page

### ISSUE THREAD

**Issue by cpassafaro** [vuetifyjs/vuetify#20715]
### Environment
**Vuetify Version:** 2.7.2
**Vue Version:** 2.7.10
**Browsers:** Chrome 130.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Click the buttons with tooltips. The tooltip will immediately open and close itself.

### Expected Behavior
Do not open the tooltip on click

### Actual Behavior
Opens and then immediately closes

### Reproduction Link
[https://codepen.io/techformist/pen/wvGeYQZ](https://codepen.io/techformist/pen/wvGeYQZ)

**Comment by cpassafaro** [comment]
The problem I'm having with that fix is that when the button is tabbed to it doesn't trigger the tooltip. So it's not supporting keyboard navigation

**Comment by KaelWD** [comment]
retain-focus-on-click will also stop this.

**Comment by cpassafaro** [comment]
Where? I don't see that as a prop you can put on the vuetify 2 v-tooltip
