### ISSUE TITLE
[Bug Report][3.7.4] VTextField does not sync with model-value prop until blurred

### ISSUE THREAD

**Issue by emmettxt** [vuetifyjs/vuetify#20723]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.13
**Browsers:** Firefox 132.0
**OS:** Windows 10

### Steps to reproduce
Type any text into text field input

### Expected Behavior
Text should not update 

### Actual Behavior
Text updates, but then on blur will show value of model-value prop

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UstOwzAQ/BXLl4LUxociIVUF8RAHOAACbphDSDatwXEs7zoUVf131g6FChBSFMUz49nZUR7XEkOlTr0v+ghyJucErbclwbF2Qsz7Sel9/syHqnNUGgfhE8ogwYomjQFbi1nb1WAnfWkjHGnZ4kJLcRJ9zYa/OXEkRkuwthuxSm2nqJ9jEjKkmKuddHzEKhhPAoHiENK0vgsk1iJAIzaiCV0rRrzYKMmFYF8kMUxmxd7n9P3kPHixixxLQlY2ZlG8YOe4lHW6rGXVtd5YCDeeDDtpOROZSVzJRm9XGaMQYbzFqyVUr3/gL7hKmJa3ARBCD1p+cVSGBdBAX9xfc707JLcYLav/Ie8AOxtTxkF2Fl3NsXd0Oe1lLsu4xQNerAgcbpdKQZNyk/VacoHn/6z+HXdaTPM97fjhHq1xr/izRMy3H7VcEnmcKVXVjjX8b5g+FA5IOd8qnkmmeT+ZFofFgaoN0haa2PIZi2zzNAzajF20Nr+ePgCzu+7Y)

**Comment by J-Sek** [comment]
What is the actual use case? I wish the example was slightly more realistic.

**Comment by emmettxt** [comment]
There are many reason you might want control of the display value while component is stilled focused. [For example preventing input greater than a certain number of characters](https://play.vuetifyjs.com/#eNp9UmFP2zAQ/SuWNakgtTFTJ02qysQ28WH7sCHgG+ZDSC6twXEs3zkUVf3vnB1CK0BIURS/9+7du4tvthJDpX56X/QR5EIuCVpvS4If2gmx7Gel9/kzH6rOUWkchBcogwQbmjUGbD2CQizargY760sb4VTLFlda7tmz6Gtu8V4kTsUX6MFRgdZUcHQyFV9Pjvelaoyi3mZJyBB1qQ5G4CNWwXgSCBSHSUzru0BiKwI0Yiea0LViwtNPklwI9kUSQxhWHE3WYG03OU7Ogxe7yKkkZGVjVsU9do43t03FWlZd642F8N+TYSctFyIziSvZ6PFvxihEmI54tYbq4QP8HjcJ0/IiAELoQctXjsqwAhro86t//A8OSF5stKz+hLwE7GxMGQfZr+hqjn2gy2n/5GUZt7rG8w2Bw3GoFDQpd1mvJS/w9yej7+POi3mu044f3qM17gHfLhFz9Y2WayKPC6Wq2rGGr4vpQ+GAlPOt4p5kmqezefG9+KZqgzRCM1veYZFtbodGu6mL1ubX7TO5Vfbm)

Another use case might be only allowing certain characters to be entered.

I understand you can use vuetifies validation framework, but its not equivalent to actually just preventing the invalid input from showing at all. 



```
<template>
  <v-app>
    <v-container>
      <v-text-field
        :model-value="msg"
        @update:model-value="msg = $event.slice(0, 10)"
      />
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const msg = ref('hello')
</script>

**Comment by J-Sek** [comment]
There are dedicated solutions for these use cases:
- `maxLength` (note that for some reason needs to be always pascalCase)
- `@keydown.{key}.prevent` for a single key input prevention or `@keydown` handler function for more robust logic
- `v-mask` abstracting `keydown` handling

By hooking into the event dedicated to **emit** changes, you fight against the nature of the form control itself.
