### ISSUE TITLE
[Bug Report][3.7.4] VTreeview: Expand a root  have the "loading" state for all roots.

### ISSUE THREAD

**Issue by cvaroregidor** [vuetifyjs/vuetify#20721]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.13
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
A VTreeview with more than one parent node.
Expand one parent, al parent nodes get the "loading" state
This is fixed for child nodes (https://github.com/vuetifyjs/vuetify/commit/488fc0221e7957dbfac6d680f2ea40bb25412d5d)

### Expected Behavior
Should show "loading" animation in the root node to expand

### Actual Behavior
Shows "loading" animation in all root nodes when expanding one

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE1vEzEQ/SvDCpENSpyGqkKKmiIkOII4wKmpVOP1dg1ee2XPJkRR/jtj73foATWXtd+bD8+bmdyfEu/E6mNVsX0tk01yi7KsNEd5tzMAt/ul4C6L5/62RIVagtDc++0u+fm0VCZTTxZQ/sHloVAom2Nxs0taV4AfXjr4pJwUaN2xDbgaR7zMQiF6bwLRSblX8tBBABvKVIYnxO8uGTHa8mwpCqUzJw1Z5BJFEZ4wMRNWW0fsgTujzNOYyqTxCo9ECltWXOCYDPmaNxNveCn/Ifdc14FU2UD1xVA5ncqwX3ptcVM5WUmTkccpBoDzSLpWACWsIXuVk9WrYMS6AskWykwtuRC2Nhh1DdbjjKtJYzv1O1E77fuGdOJ3CF0mIejqhVMVgpdYV9FWlZV1CCfStaxqlNkCnMwXcOAkPpwhd7aEGc3ZLPgH+Y1HqHjtJWyh9LC9AyMP8I3slJepk97qPXF3Icl3VUpbY4cuyGE+HwfSqlRIgShnekNMh/vfqmrhqxGMFrke4QMTx6ll7hthTp1oodsbmMVRmi06tGvEBu4fWvDcfp/1XL/c9d1/uD605XB/NALy2ghUNDvDEqShxHmXgB84CRf7kK5vrhqRgMrH2rVe6WOBWPnNapXVZXn85a1h1OUVuTj/ISq/fX2KXxZn//wmyL5dXz220QAYFtKE9oWG0oeFKGno4ZgPYDDoi2+6YrVkYU0j37tA0/QmJXUsvitCg0V4x9QgIAMf52BqEKHBImKxUpZb95mTHOriic3a9wvJqtoX6YSn+hhTfe9ap2wDXzgWLNfWujQeHTeZLdM5vIU19eLCoxkFxXLlPH6lywX/zEw0v/NItOE8nJgIW5pK50JpE8kJa7p0Dn8CzdrTwifnham1XiTX7D27Th7+AnMv7hk=)

**Comment by KaelWD** [comment]
Root nodes still need a unique id too.
