### ISSUE TITLE
[Bug Report][3.7.4] Readonly Form is inconsistent when inputs have readonly false

### ISSUE THREAD

**Issue by charlesg99** [vuetifyjs/vuetify#20730]
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.13
**Browsers:** Chrome 131.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Set a form to readonly with its readonly attribute. Set readonly to false to inputs within the form.

### Expected Behavior
All inputs within the form are readonly

### Actual Behavior
All inputs aren't readonly, you can still edit the textfield

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1kMFqwzAMhl9F88UbNDPdbsEd7LY32KHpISTyCMixsZWwUfruU+LAskMvwr/8/ZZ+n68qp868x/g8T6hqZRl9pJbxrRkB7Fy1Ma7HVbiQPNQJ2z6M9HNqFKcJG7UBK8L4zZUbkHqYKx96JMF8/mrUP6NrKYsTzN6bkbDjna807ljrQXbN0jjroz6AflnKq77sXrWm7FzCiChprNmlFJm7NESGjDyVsIOPITFcIaGDG7gUPGj5IL3gAF0YM4OEgtNCPOoPJArwGRL1D/rpD9kCbdRxubKmTJM56nYYJ6K1XH4Bzip/tg==)

### Other comments
Seems like some work was done for selects in https://github.com/vuetifyjs/vuetify/issues/16161. Probably need the same fix for textfields.

**Comment by MatthewAry** [comment]
The expected behavior should be that all inputs with the `:readonly="false"` prop applied, in contradiction to the `:readonly="true"` property set in VForm should be editable. VSelect is not working correctly.

**Comment by charlesg99** [comment]
I feel like the other way around would be more helpful, but I agree that a child should have the last say. If the resolution makes it that all child inputs have the same behavior, that's a win.

**Comment by KaelWD** [comment]
Null or undefined will cause it to inherit from the form, if it's coming from an expression you can use `expr || null`.
