### ISSUE TITLE
[Feature Request] VSelect - Add a slot in menu, but before scrollable list

### ISSUE THREAD

**Issue by pmarchut** [vuetifyjs/vuetify#20731]
### Problem to solve
I wanted to have fixed search input above the list of items in menu regardless of the scroll position. I tried to set fixed position to search input in #prepend-item slot, but the entire slot content is in scrollable list, so search input overlaps with menu items. I don't want to use VAutocomplete, because i want to show users directly that there is a search functionality, so I need separate search input and moreover I send custom requests to backend using this search input 

### Proposed solution
A slot in VSelect that places content in menu, but before scrollable list. Then we can place fixed content (for example custom search input) above the scrollable list of VSelect. Or maybe You see another possible way to achieve it?

**Comment by J-Sek** [comment]
You might be better off with custom implementation ([example](https://play.vuetifyjs.com/playgrounds/Brmevw)). This way you can have highlights for matches. I had seen implementations with VSelect, and I cannot recommend going this route as you would give up this vital feature.

**Comment by pmarchut** [comment]
That can be a workaround solution, but in our project we have many functionalities in app Select component and changing code into this approach will take quite long development time. Also I think library should provide easy solutions for users instead of forcing them think about workarounds. I think this new slot can be a nice option for users and of course save my team a lot of time, so I am curious if creators will consider it

However, thank You for the idea in example! It looks very nice and I might consider it, when building some project from scratch

**Comment by KaelWD** [comment]
This would require changing how scrolling works for all menus, not just VSelect: the scrolling element is the menu content, there is no "before scrollable list". If you use sticky instead of fixed it won't overlap.
