### ISSUE TITLE
[Bug Report][3.7.2] v-color-picker eye dropper bug on 4k resolution

### ISSUE THREAD

**Issue by PetukhovArt** [vuetifyjs/vuetify#20735]
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.13
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10 

### Steps to [reproduce](url)
1) use 4k resolution on the screen ( i use nvidia geforce 3550)
2) on vuetify web page with color picker or in vuetify playground  choose eye dropper and try to pick color from some points of your screen

### Expected Behavior
- dropper do not grow on mouse move with active pippette in 4k resolution
- dropper do not have black background  in 4k resolution

### Actual Behavior
-  dropper grow on moving dropper
- dropper  have black background 

![photo_2024-11-25_15-10-25](https://github.com/user-attachments/assets/ad144fe7-4d91-4a30-a10d-7fc617e2d9e4)
![photo_2024-11-25_15-25-19](https://github.com/user-attachments/assets/f65aa1b7-9915-4b3d-a663-872661839aa8)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdjsEKhCAQhl8l5lwGWxCELOxzVAcpF9xKB7Uu4ruvmQfpNvPN98/M4OCDSM6DQw/U8h03Zvl7lEVBz4ohxjI2s5KWCcl1QgluSlco5jVwWj9Aykachy9y76Z1dvOQC/8GaYESNiFXQ35GyfCYG2E2ZoR+mHyYiR2VttXOMBNueEnOe/AlNKQlry7oDelIC6XVB5/+S0pOZA==)

**Comment by KaelWD** [comment]
This just uses https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper, the dropper ui is part of the browser so either a browser bug or a problem with your gpu drivers.
