### ISSUE TITLE
[Bug Report][3.7.5] v-textfield events key are not dispatched when placed in a v-menu

### ISSUE THREAD

**Issue by lfirdion** [vuetifyjs/vuetify#20755]
### Environment
**Vuetify Version:** 3.7.5
**Vue Version:** 3.4.15
**Browsers:** Chrome 131.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- insert a v-textfield with a key event inside a v-menu
- the v-menu catches and prevents the key event originated from the v-textfield (even with .stop or .prevent modifier)

### Expected Behavior
the v-textfield event keypress should not be prevented by the v-menu event hander 

### Actual Behavior
the key press event emmited by the v-textfield is prevented and can't be used (i.e. I want to redirect user to a result page when they press enter after typing in the v-textfield)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUstugzAQ/JUtqkQiBbhHpGpUVeof9FB6cMwSWTG25QdqhPj3rk1J4RLFu7MzO7N8jZmzvDobUw4Bs2NWe+yNZB5fGgVQDwUzJv1ND66VZ0Kh/SsBjCPggMq/Bed1D9O0NAjdowpw5FI7LLRKw4QsuBT8dmqyjkmHTfagoplFHIbCSe2PjHsxMK8twUcwVhsH02YkCV28Aq5lghkrembvTUYcF6HaVKI5moLzQgeRHeoqja4XqDb2HwIef3zRCZTtWpkc6hYlKfTu2mTr1usN78GUZBdtScmY0tiUE4FT6z12ds+ptl/PVg/luF6McImfntv8Y2U+z2ZvejpuhfHg0If5eqI32noYwWIHE3SWbpXTxfMIBwpPOQ/kAk4Rscs/UEoNn9rK9inf/0PWt56h1IztLigKVytYuZvNwTjvHwm0xFLq6y4nFKRw8sPMmTRgzV8OTAYklVSLbfq26mq2Rqay6aCClOnn+xchMugy)

### Other comments
I saw the workaround with using a v-form around and using a @submit event (issue https://github.com/vuetifyjs/vuetify/issues/19920) but that won't cover 100% of use cases

**Comment by KaelWD** [comment]
You need `@keydown.enter.stop` too (or instead) so the menu can't call preventDefault.
