### ISSUE TITLE
[Bug Report][3.7.5] No class to remove padding-inline

### ISSUE THREAD

**Issue by Makkalay** [vuetifyjs/vuetify#20760]
### Environment
**Vuetify Version:** 3.7.5
**Vue Version:** 3.5.13
**Browsers:** Chrome 131.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
I have button in v-list-item > v-list > v-menu. I see what it have padding or margins and not look like a menu item. I want to remove it but p-0 and m-0 not help. 
I set padding-inline:0 in style.

### Expected Behavior
To have possibility to remove padding-inline

### Actual Behavior
p-0 and m-0 not have effect 

### Reproduction Link
[https://github.io](https://github.io)

**Comment by mak7an** [comment]
[padding-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end)
[padding-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start)

**Comment by J-Sek** [comment]
There is no `p-0`, use `pa-0` or `px-0` if you don't plan on supporting vertical writing mode.
