### ISSUE TITLE
[Bug Report][3.7.5] VFileUpload seems to be missing in labs

### ISSUE THREAD

**Issue by OxySynth** [vuetifyjs/vuetify#20777]
### Environment
**Vuetify Version:** 3.7.5
**Vue Version:** 3.5.13
**Browsers:** Firefox 130.0
**OS:** Windows 10

### Steps to reproduce
Install Vuetify 3.7.3, 3.7.4 or 3.7.5 with Vue 3.5
Try to import the component using
```import { VFileUpload } from 'vuetify/labs/VFileUpload' ```

### Expected Behavior
VFileUpload imported

### Actual Behavior
Vue: Cannot find module vuetify/ labs/ VFileUpload or its corresponding type declarations

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjkEKgzAQRa8is9YUaosgqdBzGBfBREgbk8EkQpHcvVFb0N3Mm8ef3y7wRCRzkFAD9XJEzb1smMkyOhcccRu3pbfGc2Xk9EMbHJSWRUBtuciENE75z4OBkAMP2jNo6OXk/NMSPcetZP9GL4cWwaSoJAnIQSvzduTlrElVFwa9cwzqtovppka0ky9Gjgdhh6u0xAgxh5LcyLVKekkqcofcT0F2X08DVLM=)

### Other comments
Trying to open the component using the playground link of the docs page of
https://vuetifyjs.com/en/components/file-upload/

But you can already see that in the playground the component cannot be found. If the component isn't available yet, the version requirement might be wrong.

Thanks for the component tho! It's looking great.

**Comment by lock4u** [comment]
i find too! miss fileupload

**Comment by lock4u** [comment]
When will version 3.7.6 be released?

**Comment by Dhanush-S-Gowda** [comment]
![image](https://github.com/user-attachments/assets/b8a2e8eb-7bab-4023-9491-67f04fd7d0dc)

On vplay, if you enable nightly and click on any of these versions, it is working.
