### ISSUE TITLE
[Bug Report][3.7.6] VRangeSlider right thumb won't go all the way to the right when setting the step

### ISSUE THREAD

**Issue by SalehKhaled7** [vuetifyjs/vuetify#20797]
### Environment
**Vuetify Version:** 3.7.6
**Vue Version:** 3.5.13
**Browsers:** Firefox 133.0
**OS:** Windows, Linux

### Steps to reproduce
Add the step prop and set it to 29.

### Expected Behavior
The right thumb should be able to slide to the end of the track.

### Actual Behavior
The right thumb is not sliding to the end of the track.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVj0EKwjAQRa8SZm0TmrpRYsFzGBehGaVQxyFJuxHvbhsV2u66+/Pm8+BfXhBDo87McugRjmASPrhzCWtLQpihcMw55qN5UnItYfihDIOjOxaxaz0GERPyyYI+WKiNWj7/nhGvRVvcpd7insh3g1GzbT15vI0lbwneO6jkXpYaplBJDdcPpKRZRQ==)

### Other comments
It works correctly for some values, like 12.
the issue exist on all Vuetify versions

**Comment by KaelWD** [comment]
If you want it to go all the way to the end you have to set max to be min + a multiple of step.
