### ISSUE TITLE
[Bug Report][3.7.6] Key cannot be obtained when clicking sort three times

### ISSUE THREAD

**Issue by w-nakai-enzan** [vuetifyjs/vuetify#20791]
### Environment
**Vuetify Version:** 3.7.6
**Vue Version:** 3.5.13
**Browsers:** Chrome 131.0.0.0
**OS:** Windows 10

### Steps to reproduce
Sort three times.
Check the console.

### Expected Behavior
key can be obtained

### Actual Behavior
[] is returned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNklFrgzAQgP/K4UtbaBX2KFbWwcZge9tj24erXtuwmAQTpaX43xejtlEY1Adz3n25fJHb3gJdZtFGqbCuKIiDxFChOBpKdwIgqVeolAvdRyaFQSao7FMumaPBlcEDpyEJEDPbR693gVt3waPyWim7gWItS/N2tcQvXdfpicwXXec2XjzgNIn87oOGTY492kynmUSefqKzkinjELooex7kdMSKG7h1rdreMcwXsE5h3ucAnHIM24fzvdQ+AguKYbY5lixDAe+c1BmFmS19SCvKGNkus295kXmrC9jtwDGZMzIW+6TywGpZ0rh6xgMz2AI/WKMQuIQPC2mjfa7x4mdcX56XnaBT20n5f90R6PtGEYRhCIXFuj8/lPY91Cz6oCBzlrnVvF/Rmxr/3nY6tOQUcnnqJqqvDMd2a9OOy31EgmYpKs7da/8HJjvnGg==)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-data-table/#props-must-sort
