### ISSUE TITLE
Inputs should start unvalidated

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetify#208]
Right now when you use rules with inputs and selects they start out invalid on page load if any of the rules return false. They should instead not validate at all until first focus or input.

**Comment by johnleider** [comment]
I'm now looking into this. I don't know if I completely agree, but I'm willing to discuss. Why could you not handle this within your function logic that you pass into the rules prop?

**Comment by nekosaur** [comment]
Yeah that's what I ended up doing after creating this issue. Right now any text field that I want to start out unvalidated I set its initial value to null, and in my rules I do a first check against null and return true. That way when I focus an input and it sets the value to an empty string, I get validation. So that's a solution.

**Comment by johnleider** [comment]
That's my intended way to handle this particular situation. I think it covers as many bases as possible without being too frustrating (imho).

**Comment by johnleider** [comment]
We discussed this on chat. The dev can handle this on their end. My intent atm is to not attempt to create a half-version of the many validation plugins that exist, but that basic validation exists and plugins hook up nicely.

**Comment by ash-rain** [comment]
How did you resolve this? I have a similar problem - my first required field starts as invalid, with red styling and all. How do I make it start as valid until input or submit occurs?
