### ISSUE TITLE
[Performance] v-select re-renders when another input changes

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#2080]
I'm not sure if this is just something Vue always does, or if it's something we're doing wrong. Either way, it causes massive framerate drops during typing if there are multiple selects on the page - particularly on mobile devices. 

### Steps to reproduce
Start performance profiling and type into the text field

### Versions
Vuetify 0.16.3
Chrome 61
Windows 10

### What is expected ?
Only the text field should re-render

### What is actually happening ?
The `v-select` is also rendering, including generating all of the list items which takes several ms per keypress

### Reproduction Link
https://codepen.io/anon/pen/ZXxYNX?editors=1010

![image](https://user-images.githubusercontent.com/16421948/31314347-70fe00a6-ac4a-11e7-9b17-213b750c532e.png)

**Comment by cb109** [comment]
Nice find. Can confirm experiencing that exact issue, would love a performance improvement here.

**Comment by jacekkarczmarczyk** [comment]
Probably related: https://github.com/vuejs/vue/issues/6898#issuecomment-338919058

**Comment by jacekkarczmarczyk** [comment]
Only text field slows down, try this codepen - type something in the text field and then type something in v-select.tags

https://codepen.io/anon/pen/POoWOv?editors=1010

**Comment by KaelWD** [comment]
That isn't anything to do with the text field, regular HTML inputs do it too: https://codepen.io/anon/pen/qVBRYY?editors=1010

If you don't update the value in the parent then it's fine: https://codepen.io/anon/pen/GORrdL?editors=1010

Or put all the selects inside a child component: https://codepen.io/anon/pen/ZaELjK?editors=1010

**Comment by jacekkarczmarczyk** [comment]
I know, was wondering why tags field isn't slow, the answer is that it doesn't update the value while typing

**Comment by johnleider** [comment]
This no longer occurs on 0.17 branch and up.

**Comment by KaelWD** [comment]
Yes it does, this is on latest dev:
![image](https://user-images.githubusercontent.com/16421948/36068983-6ad55b40-0f35-11e8-8b37-6ee9aad958b4.png)
It's worse if you have lots of inputs of course

**Comment by solojuve1897** [comment]
Is this applicable to v-autocomplete and v-combobox also?

**Comment by KaelWD** [comment]
Yes. This is a vue thing, nothing we can do about it.
