### ISSUE TITLE
Links with router in navigation drawer do not behave as expected on page load

### ISSUE THREAD

**Issue by tmpjr** [vuetifyjs/vuetify#2082]
### Steps to reproduce
Load page. Observe navigation links. Home is default route.

### Versions

2.4.4 / 0.16 / Chrome  61.0.3163.100 (Official Build) (64-bit) Windows & Mac

### What is expected ?
 On initial page load I expect Home link and icon to be the only link active/highlighted with Home content loaded. About link should be inactive/not highlighted/not selected.

### What is actually happening ?
Home content is loaded, however, About drawer item is selected, about icon is highlighted. Once user clicks Home link after page load, functionality works as expected. Issue seems to only be on initial page load. Is there something I need to code to handle this on page load? 

### Reproduction Link
https://codepen.io/tmpjr/pen/LzdZqy

**Comment by johnleider** [comment]
That is because you bound **value** to **item.active**, but didn't actually use bind, so it was just putting the text item.action. Essentially you forced it to be active.

https://codepen.io/tmpjr/pen/LzdZqy

**Comment by tmpjr** [comment]
Thanks so much for your help!

**Comment by sehmbimanvir** [comment]
how i can use route names in sidebar links ?

**Comment by johnleider** [comment]
@sehmbimanvir the issue board is not for questions. https://chat.vuetifyjs.com
