### ISSUE TITLE
Icons show the text of the icons, not the icon itself.

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#2083]
### Steps to reproduce
1. Install a webpack base project using vue-cli
2. Install Vue, include the JS/CSS into the Vue App in main.js.
3. At this point, the other components work.
4. Attempting to use `<v-icon>home</v-icon>` shows a large "home" in text instead of the icon

### Versions

Vue: 2.4.4  
Vuetify: 0.16.3  
OS: OSx Sierra 10.12.6  
Chrome, Firefox (including nightly), Safari

### What is expected ?

I expect to see icons.

### What is actually happening ?

I see the text instead. "home" instead of an icon of a home

### Reproduction Link

I can't reproduce from the given fiddle.

**Comment by NMonst4** [comment]
Same here

**Comment by NMonst4** [comment]
Found my error. I need to add this 

`link: [
            {rel: 'icon', type: 'image/x-icon', href: '/favicon.ico'},
            {rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'}
        ]`

in nuxt.confi.js

**Comment by jaesung2061** [comment]
I'm not able to find that file? @NMonst4

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by vaniakosmos** [comment]
I had same problem, deleting `<link href='semantic-ui'>` from `index.html` I solved it.

**Comment by Mbarsila** [comment]
Including <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet" type="text/css"> in my index file solved my problem

**Comment by yhc44** [comment]
In Windows you need to include 

link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material Icons' rel="stylesheet" type="text/css"

Without '+' sign between Material and Icons.

**Comment by bakossandor** [comment]
with Vue CLI 3 we has no index.html in the src folder so alternatively you can
`npm install --save material-design-icons-iconfont ` 
and import it in the main.js file
`import 'material-design-icons-iconfont/dist/material-design-icons.css'`

**Comment by alan1111** [comment]
I have the same problem in chromium browser, however, it works fine in firefox browser.

**Comment by Mikilll94** [comment]
So this was working in Vuetify 1.5, without importing any icons?

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by nscozzaro** [comment]
I spent many hours trying to resolve this issue today, and this is what worked for me. I hope it might be useful to someone else. (Sorry @jacekkarczmarczyk)
```
// src/plugins/vuetify.ts

import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css';
import '@mdi/font/css/materialdesignicons.css'

Vue.use(Vuetify);

const vuetify = new Vuetify({
    icons: {
        iconfont: 'mdi'
    }
});

export default new Vuetify(vuetify)
```

```
// other_file.ts

import vuetify from './plugins/vuetify';

new Vue({
    vuetify,
    ...other stuff...
)}
```
Thanks to @skirtle for helping me on StackOverflow
https://stackoverflow.com/questions/58189596/vuetify-icons-not-showing-correctly-they-appear-as-as-vuetify-icons

**Comment by MHM5000** [comment]
And more importantly:

Since the default font is `mdi`, instead of writing `visibility` for the *eye* icon, you should write `mdi-eye`.
Most of the documentations that have icons in them, use the wrong font!

I wasted 3 hours on this!

**Comment by jacekkarczmarczyk** [comment]
> Most of the documentations that have icons in them, use the wrong font!

Any example?

**Comment by MHM5000** [comment]
> Any example?

in [this page](https://vuetifyjs.com/en/components/text-fields#examples) search for password input. The code inside is based on other material icons font. Not the default one.

**Comment by jacekkarczmarczyk** [comment]
Thanks, we've updated all examples to MDI (all except the ones that we missed, like this one), please create a separate issue if you've found other places where MDI should be used

**Comment by MHM5000** [comment]
I was planning to contribute (search and replace) but if you're already looking for them, then I'll find something else.

**Comment by jacekkarczmarczyk** [comment]
Well, i'm not looking, that's why I asked you :) I was just planning to update the password example, but feel free to create a PR for password and other places if you want to and if you find more

**Comment by jacekkarczmarczyk** [comment]
@MHM5000 i've updated the password example, if you have other places where material icons are used please create an issue or PR

**Comment by MHM5000** [comment]
@jacekkarczmarczyk sure...

**Comment by Niedzwiedzw** [comment]
why is this not working out of the box? I've created a fresh project with vue-cli and it shows "search" text instead of actual icon?

**Comment by sypher-samurai** [comment]
With Vue CLI 3 we have no index.html in the src folder so alternatively, you can
run 

**npm install --save material-design-icons-iconfont**


and import it in the main.js file

**import 'material-design-icons-iconfont/dist/material-design-icons.css'**

**Comment by altynbek07** [comment]
I solved this problem by adding the `icons: 'md`' option to `defaultAssets` in `nuxt.config.js` file:
```js
buildModules: [
    ...
    ['@nuxtjs/vuetify',
      {
        ...
        defaultAssets: {
          icons: 'md'
        }
        ...
      }
    ],
    ...
  ],
```

**Comment by leodahal4** [comment]
I cannot use the icons which contains underscore( _ ) on it like ( arrow_downward ). No any issue found till now. All other icons containing single word works well. But these type of icons are not working, I tried many of them. **Help**!

**Comment by xgdgsc** [comment]
This is confusing and should be fixed.

**Comment by Chandher05** [comment]
> And more importantly:
> 
> Since the default font is `mdi`, instead of writing `visibility` for the _eye_ icon, you should write `mdi-eye`.
> Most of the documentations that have icons in them, use the wrong font!
> 
> I wasted 3 hours on this!

THIS JUST SAVED ME

**Comment by pgdesigning** [comment]
> Found my error. I need to add this
> 
> `link: [ {rel: 'icon', type: 'image/x-icon', href: '/favicon.ico'}, {rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'} ]`
> 
> in nuxt.confi.js

This works!
