### ISSUE TITLE
tooltip flickering (and wrongly positioned?) with two-line list

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2090]
### Steps to reproduce

Create two line list with tooltipped list tiles

### Versions
0.16.4

### What is expected ?
Tooltip should not flicker when you're moving the mouse

### What is actually happening ?
![tooltip](https://user-images.githubusercontent.com/15625235/31327235-24e481fa-acf8-11e7-8c40-4bec45ddce5a.gif)

### Reproduction Link
https://codepen.io/anon/pen/eGMVvM?editors=1010

Also the list markup is not a valid html:
![image](https://user-images.githubusercontent.com/15625235/31327255-51c5a7bc-acf8-11e7-8bce-a24096413f72.png)

Maybe that causes the problem and there is a way to make tooltips without wrapping the tooltip activator with spans?

**Comment by johnleider** [comment]
This was fixed as a consequence of da8936139874f343c8a88b9e1c8a899d9d7ccd61
