### ISSUE TITLE
dialog closes after pressing ENTER in autocomplete

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2092]
### Steps to reproduce
Open the codepen https://codepen.io/anon/pen/eGMKyr, click the "Open dialog" button, click the select, type "x", press ENTER

### Versions
0.16.4

### What is expected ?
Dialog should not close

### What is actually happening ?
Dialog closes

### Reproduction Link
https://codepen.io/anon/pen/eGMKyr

Last working version is 0.16.1: https://codepen.io/anon/pen/dVmKLP

**Comment by barnabas-avalara** [comment]
For what it's worth, the behavior does not happen when the dialog is persistent, as demonstrated here: https://codepen.io/anon/pen/mBamLw

**Comment by jacekkarczmarczyk** [comment]
Probably the same issue: https://codepen.io/anon/pen/NaeOdw?editors=1010
