### ISSUE TITLE
[Bug] Flat button gets both btn--flat and btn--raised classes

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2095]
### Steps to reproduce

Create a flat button:
```
<v-btn flat>Button</v-btn>
```
The button element gets these classes: `btn btn--flat btn--raised`.

### Versions
Latest

### What is expected ?
Flat buttons should have the `btn--flat` class and not the `btn--raised` class.

### What is actually happening ?
Flat buttons gets both the `btn--flat` and `btn--raised` classes.

### Reproduction Link
https://codepen.io/anon/pen/gGejQe

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/abc26838e5a3689618e3dfeb5e6422d08ec9acc1

**Comment by KaelWD** [comment]
What happened to "no booleans that default to true"?

**Comment by johnleider** [comment]
merged in 6634da14d018651de8a56d59270157c3f80ce0b9

**Comment by KaelWD** [comment]
I think you mean d72b54873b1e05266a19da2e754814c78730c17b
