### ISSUE TITLE
V-Select selection slot without multiple option not beign displayed until blur

### ISSUE THREAD

**Issue by Eylen** [vuetifyjs/vuetify#2100]
### Steps to reproduce
Add a V-Select, without multiple option, with slots for item and selection. The value that's shown when the item is selected and has the focus is the value from item-text and not selection slot. Once you blur from the select, the correct slot is shown.

### Versions
Vuetify 0.16.4

### What is expected ?
The template from selection slot should be shown even if the field has the focus

### What is actually happening ?
The selection slot is only shown once the field loses focus

### Reproduction Link
https://codepen.io/Eylen/pen/RLMEbQ

**Comment by johnleider** [comment]
This comes up often, there are two ways to approach this, the current implementation is our leading choice.

**Comment by Eylen** [comment]
@johnleider Sorry, I don't understand.... Is that the expected behaviour? Seems really strange...
Isn't there any workaround?

**Comment by johnleider** [comment]
Well, think about it, you are using a custom selection scoped slot, that doesn't just fit into the text input. So the other option is to show your selection (which could be standard or custom markup based upon the scoped slot) along with the input where you are typing. If you remove that slot, you can see it behave more than likely how you expect it to.

**Comment by Eylen** [comment]
@johnleider Sorry but I still don't get it.
I know that you can type whatever you want to fill the select with the autocomplete option, but once I select an option, I expect to see that option selected, not what I was typing.

**Comment by johnleider** [comment]
I'm going to need to see an example of what you expect to happen in some way.

**Comment by Eylen** [comment]
I expect the same behaviour that when the v-select is multiple. Once you select a value, the selection slot is what's shown in the field.
Check this example and compare with the previous one.
https://codepen.io/Eylen/pen/Qqxdxm

**Comment by jacekkarczmarczyk** [comment]
It is shown:
![image](https://user-images.githubusercontent.com/15625235/31582114-2136f25c-b1a5-11e7-97ff-bfa9611da0bb.png)

**Comment by kno** [comment]
@jacekkarczmarczyk It's correct, but when it's not multiple and you select an option you get
![image](https://user-images.githubusercontent.com/235579/31583380-ec4263f6-b19a-11e7-8c08-43d2f1035abd.png)
When the expected is:
![image](https://user-images.githubusercontent.com/235579/31583390-1cce6646-b19b-11e7-918e-17cb8f2c322a.png)

**Comment by jacekkarczmarczyk** [comment]
Ok, I think it's clear now

**Comment by huyvm** [comment]
change slot from selection to item.
