### ISSUE TITLE
[Bug Report] Datepicker not working iOS / OSX

### ISSUE THREAD

**Issue by Birssan** [vuetifyjs/vuetify#2102]
### Steps to reproduce

Click in one of the two text fields

### Versions
Latest version of Vuetify.

Tested on:
- Mac OSX Yosemite 10.10.5, Safari 10.1.1
- iOS 10.3.3
- iOS 9.3.5

### What is expected ?
For the first text field the date picker is supposed to open in a menu component.
For the second text field, the picker is supposed to be opened in a dialog

### What is actually happening ?

Nothing opens when the text field gets the focus

### Reproduction Link

I took the demo code available in the doc.
https://codepen.io/anon/pen/VMXVyP

**Comment by jacekkarczmarczyk** [comment]
@Birssan can you please check it with this codepen? https://codepen.io/anon/pen/PJeaJw

**Comment by Birssan** [comment]
So far:

On Mac OSX Yosemite 10.10.5, Safari 10.1.1, still the same
On iPad with iOS 9.3.5, need to set up a environment, codepen doesn't seem to load on the browser (can only see the code, nothing appears in the preview frame)
Not tested on iOS 10.3.3

**Comment by KaelWD** [comment]
This doesn't seem to be in progress any more.

**Comment by jacekkarczmarczyk** [comment]
Unassigning myself as I don't have ios/osx to check it

**Comment by FabianSilva** [comment]
seems that it is the same problem of z-index on ios with v-menu
https://github.com/vuetifyjs/vuetify/issues/2111

**Comment by Vincebe** [comment]
Not fixed in 1.0 alpha 3

Any workaround?

**Comment by johnleider** [comment]
@jacekkarczmarczyk is this still an issue with your recent picker updates?

**Comment by jacekkarczmarczyk** [comment]
No idea, it's a IOS/osx issue, i'm not able to check it

**Comment by Yoann53** [comment]
Vuetify doesn't work on iOS 9.3.5. I get a blank page too on iPad 3. I think it's due to flexbox. Not supported on safari 9

**Comment by johnleider** [comment]
@chewy94 please check this out

**Comment by jacekkarczmarczyk** [comment]
nothing has changed since my previous comment https://github.com/vuetifyjs/vuetify/issues/2102#issuecomment-346664225

**Comment by joke1** [comment]
I guess it's not an issue anymore. Tested on iPad with iOS 12.1.4 without any problems.

**Comment by KaelWD** [comment]
Unable to reproduce in Safari 10.1 on Sierra, and codepen no longer works on iOS 9.

**Comment by GicaGashy** [comment]
This is still an issue. It is happening in Chrome and Firefox unfortunately.
