### ISSUE TITLE
[Bug] Active router links in a dark v-navigation-drawer are receiving incorrect styling

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2105]
Create a dark v-navigation-drawer in an app with the light them specified and click on a router link in the drawer. When the link is active it's inheriting the active css class from the light theme when it should be using the css from the dark component. The link virtually disappears when it's active. 

This didn't occur prior to 16.4

### Versions
Vuetify 16.4
Chrome
OSX

### What is expected ?
The link should remain blue when it's in an active state.

### What is actually happening ?
The link turns grey causing it to disappear. I'm not sure if this is a bug or if I need to change or add a prop etc, but the links have always functioned properly in the past. 

### Reproduction Link

https://codepen.io/smitchell/pen/KXoJrZ

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/2042/commits/be3e1554224630851faaae5941f3de2fd9e1e141

**Comment by bretonio** [comment]
A similar difficulty here. In dark theme list items visited &mdash; `v-list>` followed by `v-list-tile` &mdash; are styled dark blue. 

Changing the `v-list` theme visited or current links are dark blue and the background white but then so are the icons white.

My dropping drawer follows.

```vue
    <v-navigation-drawer
      :mini-variant.sync="miniVariant"
      :clipped="clipped"
      v-model="drawer"
      fixed
      app
    >
      <v-list light>
        <v-list-tile
          router
          :to="item.to"
          :key="i"
          v-for="(item, i) in items"
          exact
        >
          <v-list-tile-action>
            <v-icon v-html="item.icon"></v-icon>
          </v-list-tile-action>
          <v-list-tile-content>
            <v-list-tile-title v-text="item.title"></v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-navigation-drawer>
```
I have rummaged through the `.styl` files to see where this behavior is defined. Nothing yet.
And I would really like the drawer to `fill-height` while we are at it.
Bug me if I have not been clear and thanks.

**Comment by jacekkarczmarczyk** [comment]
Please create a new issue using [issue creator](issues.vuetifyjs.com)

**Comment by bretonio** [comment]
Will do when time.

cb
