### ISSUE TITLE
Select not allowed dates in Datepicker when changing month

### ISSUE THREAD

**Issue by Birssan** [vuetifyjs/vuetify#2106]
### Steps to reproduce
- Forbid some dates in the picker
- Pick an allowed date
- Change the month with the month picker, the same day of the month selected will be picked even if it's not allowed

### Versions
Latest version of Vuetify

### What is expected ?
The selected date shouldn't change when you are changing the month displayed and not picking another date yet

### What is actually happening ?
The day of the date already picked stays the same but the month is changed to the selected one even if the date is not allowed (and we haven't technically changed the date by just picking the month).

### Reproduction Link
https://codepen.io/anon/pen/NaYJbY

**Comment by johnleider** [comment]
I'm struggling to understand what your actual use-case is, and what you expect to happen.

**Comment by Birssan** [comment]
Ok maybe I wasn't clear enough sorry.

Let's take the codepen above:
- On the date picker in the dialog.
- You can only pick Mondays that are posterior to today, so let's say Monday 16th of October 
- Click on the month (currently October), you now have access to the month picker, we didn't use the arrow to change the month
- Right now October is selected, we want to change the month to November
- Just by clicking November, the date set in the text field changed to November but the day is still the same, and the 16th of November is not a Monday, which means the date is not allowed but it's been selected anyway.

**Comment by jacekkarczmarczyk** [comment]
And what would be the expected behaviour here?

**Comment by Birssan** [comment]
Well the new date is not allowed, I mean it seam logical that the date shouldn't change just by changing the month right ?
When you use the arrows to browse the picker month by month, the selected date is not changed, I think the behavior should not be different when you use the month selector
