### ISSUE TITLE
Bug opening a menu from left from another menu 

### ISSUE THREAD

**Issue by FilippiSilva** [vuetifyjs/vuetify#2107]
### Steps to reproduce
Create a menu with another menu inside, make it open from the left

### Versions
Vue 2.4.4
Vuetify 0.16.4
OS Arch Linux

### What is expected ?
That the second menu opens to the left of the context menu

### What is actually happening ?
The second menu is opening above the context menu

### Reproduction Link
[https://codepen.io/FilippiSilva/pen/dVmrKN?editors=1010](https://codepen.io/FilippiSilva/pen/dVmrKN?editors=1010)

**Comment by KaelWD** [comment]
This should be added as part of #1877
