### ISSUE TITLE
Icons inside buttons don't respect color prop

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2108]
### Steps to reproduce
https://codepen.io/darkside73/pen/YragvV

### Versions
0.16.4

### What is expected ?
Red icon inside button

### What is actually happening ?
Icon with default color

### Reproduction Link
https://codepen.io/darkside73/pen/YragvV

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/1800095ed3d5dcee1a2d1d8fa4ece158fc52c434#diff-8d33bad6218db5d4b123d7a512c67850R86

**Comment by KalpiKK** [comment]
I'd like to fix this issue. Could you please add me to contributors so I'll be able to assign myself to this bug and commit fixed code?

**Comment by KaelWD** [comment]
Fixed with #2115
