### ISSUE TITLE
Possible bug in components example

### ISSUE THREAD

**Issue by leRenart** [vuetifyjs/vuetify#211]
Hello, I'm trying to use the v-select field as explained in the example page, but I think it is broken.

https://vuetifyjs.com/components/text-fields

`<v-select ... :items="options" v-model="e14" />`

Once an option is selected, reopening the selector menu hides the others

![image](https://cloud.githubusercontent.com/assets/1085151/23942342/387e000e-096c-11e7-9a3a-e94d14a7b4b1.png)

![image](https://cloud.githubusercontent.com/assets/1085151/23942353/43cf550c-096c-11e7-9aa8-8c893e017aa7.png)

**Comment by mfferreira** [comment]
@leRenart Can you create a codepen reproducing the issue?

**Comment by leRenart** [comment]
Yep, here it is

http://codepen.io/leRenard/pen/PpJqbP

**Comment by johnleider** [comment]
While this is a bug, it is only because I forgot to remove autocomplete prop from that example. It was not ready for release so we pulled it. As such, it should not be in the docs in the examples. I have corrected this.
