### ISSUE TITLE
The v-icon appeared double icon

### ISSUE THREAD

**Issue by satrong** [vuetifyjs/vuetify#2122]
``` html
<v-icon>icon-menu</v-icon>
```
will be rendered:
```html
<i class="icon icon icon-menu"></i>
```
The `class` appeared double `icon`

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VIcon/VIcon.js#L50

**Comment by mfferreira** [comment]
@satrong Please share an example reproducing the issue.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
