### ISSUE TITLE
[Feature Request] Other icons libraries in predefined Components

### ISSUE THREAD

**Issue by ram-you** [vuetifyjs/vuetify#2123]
Feature Request

- Answer those questions:
  **- What will it allow you to do that you can't do today?**
Using mdi icons or other icons supported by the Icon component in case of Material Icons is not installed in the application
Components like Steppers, Selects, Pickers, Data table, Selection Controls : Checkboxes, Radios and Carousels all needs Material Icons.
  **- How will it make current work-arounds straightforward?**
Reduce application size if we don't need Material Icons in the rest of the application
  **- What potential bugs and edge cases does it help to avoid?**

Thank you in advance

**Comment by nekosaur** [comment]
Please update this issue with the filled in feature request template, or it will be closed.

**Comment by johnleider** [comment]
With the exception of checkboxes and radios, can you provide an example of a component you cannot do this with/what library you are wanting to use? The logic probably allows for it already.

**Comment by ram-you** [comment]
Hi @johnleider 
Those ones:
**Steppers**, **Selects**, **Pickers**, **Data table** and **Carousels**

**Comment by johnleider** [comment]
But you can do it on those components.

**Comment by ram-you** [comment]
We can not change icons with Steppers, Selects, Pickers, Data table and Carousels as icons are predifined.

**Comment by johnleider** [comment]
Can you please come to https://chat.vuetifyjs.com? I'm not going to stub out each example, but the components you listed, you have the ability to modify the icon. Maybe we can go through it?

**Comment by KaelWD** [comment]
I think there should be a setting somewhere to set the default though, it'd be a pain to create scoped slots for every component just to change the icon.

**Comment by jacekkarczmarczyk** [comment]
And it's not possible in date picker (only the year icon can be changed)

**Comment by jacekkarczmarczyk** [comment]
closed with https://github.com/vuetifyjs/vuetify/pull/2709
