### ISSUE TITLE
Vertical swipe on carousel should not cycle through items

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2125]
### Steps to reproduce
1. Open https://codepen.io/darkside73/pen/mBLQdV
2. Switch to mobile view
3. Try to scroll up and down touching the carousel

### Versions
0.16.5

### What is expected ?
Carousel items shouldn't be cycled

### What is actually happening ?
![peek 2017-10-10 18-09](https://user-images.githubusercontent.com/339596/31394314-ad53a680-ade6-11e7-9c3d-d3e8c62532d8.gif)

### Reproduction Link
https://codepen.io/darkside73/pen/mBLQdV

**Comment by nekosaur** [comment]
I think you mean vertical :)

**Comment by KaelWD** [comment]
Same goes for tabs, there should really be a higher threshold on swiping when scrolling.
