### ISSUE TITLE
IE 11 Resizing Issue for child flex

### ISSUE THREAD

**Issue by JerryCBH** [vuetifyjs/vuetify#2129]
I am not sure if this is a bug or the way I am using v-flex is incorrect, but after upgrading to v0.16.4 from v0.15.x, child flex within v-layout no longer resizes in IE.

### Steps to reproduce
Please see code pen example. Apply child-flex-sm attribute to v-layout and put multiple children v-flex components in. I put 3 v-flex per v-layout and have 3 v-layout. Resize the browser window. For Chrome / Edge, v-flex components will fit the screen automatically, when running out of space, they are stacked vertically which is expected. However for IE 11, the v-flexes are not responsive.

### Versions
IE 11

### What is expected ?
v-flex child components will fit the screen automatically, when running out of space, they are stacked vertically.

### What is actually happening ?
Not responding to window resizing. This used to work in v0.15.x.

### Reproduction Link
https://codepen.io/anon/pen/aLKOVG

**Comment by johnleider** [comment]
Not sure if my eyes are playing tricks on me but I opened that up in chrome and ie11 side by side and I couldn't see a difference.

**Comment by JerryCBH** [comment]
Hi John,

Thanks for your reply - if browser width reduced to less than 400px, can see the resize difference:
Chrome left, IE11 right.
![image](https://user-images.githubusercontent.com/1642948/31419329-d3de2fa8-ae97-11e7-94d7-3d2e9a982c93.png)

**Comment by johnleider** [comment]
IE11 and flexbox have a love hate relationship. In this case, IE **needs** some type of declared width or flex-basis. You will need to assign breakpoints to your v-flex. Here is an example:

https://codepen.io/johnjleider/pen/rYmJLZ
