### ISSUE TITLE
[Request] Retain the original timestamp values of "allowedDates" in the Date Picker component 

### ISSUE THREAD

**Issue by slurmulon** [vuetifyjs/vuetify#2130]
## Problem

The `<v-date-picker>` component currently modifies any `allowedDates` you provide it by:
1. converting the dates to a `String` , and
2. setting the hour and minutes to `00:00` (midnight): https://git.io/vdwpT

This is a problem for a project I'm working on because we need the date to retain its original value (UNIX timestamp, `valueOf`) in order for the date selector component to be useful (we need to look up an entity again by its date).

As outlined in the above Pull Request, the only way to avoid this modification of the raw input date is to [provide `allowedDates` as a function](https://git.io/vdwpr). Unfortunately this isn't the most elegant solution for many scenarios because it involves needlessly processing every possible date on the calendar in order to determine if it's valid or not. When you are trying to simulate a list of `allowedDates` using this approach, it becomes an O(N2) problem (i.e. you need to compare against a user's list of dates every time you iterate through a single calendar date).

## Proposal

It seems to me that `allowedDates` (and more generally the `<v-date-picker`> component) is better off working with either native `Date` objects or UNIX timestamps (`Number`) as its underlying format instead of converting to a `String` first and then back to a `Date` again. This gives the user way more control over the data, preserves data accuracy and allows the current functionality to be retained.

Perhaps something like a `:normalize-date` or `:value-of-date` property would be useful. The default value would be a function that floors any date to midnight, retaining the current functionality but also allowing for customization. The idea is to allow the user to define the normalized/intrinsic value of their date objects. The `<-v-date-picker>` component would need to support `Date`, `String`, and `Number` return values and would also need to display an error message when unsupported return types are encountered.

If I am missing something here or am totally off base then please show me the way. We can get by with the `allowedDates` as a function approach, but it's not ideal since we will have some relatively large lists that will need to be iterated through (365 calls to `DatePicker.isAllowed` X 100 element array = 36,500 ticks on each change).

By the way, thank you for all of your incredible work on the Vuetify project, we absolutely love it!

**Comment by johnleider** [comment]
@jacekkarczmarczyk is in the middle of a big refactor of the `v-date-picker`

**Comment by jacekkarczmarczyk** [comment]
As John mentioned the date picker is being refactored to use only string values in ISO 8601 format as an input/output (`v-model`, `allowedDates`, arguments for formatting functions etc). The main reason for this is that using the Date object caused problems with time zone (also because of the bug in Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=364374). This is also how native `<input type="date">` works

Having said that please provide the codepen example which shows the problem with your current code so we can move on with this issue

**Comment by slurmulon** [comment]
Interesting, I didn't know that's how the native date input works. I've experienced timezone issues before with `Date` though so that all makes sense.

I will create a Codepen for this shortly. Thanks for the speedy reply.

**Comment by slurmulon** [comment]
Codepen, as requested: https://codepen.io/anon/pen/OxEGEw

As you select through a couple dates you will notice under `Chosen` how it modifies the `allowedDates` by zero'ing them out to midnight (i.e. `1507754206385` pre-selection vs. `1507708800000` post-selection).

Here is the code that's modifying the date: https://git.io/vdwpT

**Comment by jacekkarczmarczyk** [comment]
So as I wrote before in order to simply the mechanism and avoid time zone issues we're changing the date picker to accept only strings in ISO 8601 format, so there's no more time included in the input or output values, neither in allowedDates, it's just "2017-10-10" format. Even (similar to native `<input type="date">`) the ISO format with time ("2017-10-10T12:00:00") won't be accepted.

There's already a PR for this. and although it removes functionality of operating on datetimes/timestamps I personally think this is the right approach. This is a DATE picker, not DATETIME/TIMESTAMP picker

I'd like to ask for clarification of this "36,500 ticks" issue, I not quite understand in what conditions it can happen. When displaying month/year view we don't check allowed dates, it's only for date view, so there would be max 31x100 = 3100 checks, and actually if you do it clever (for example keeping allowed dates as object properties) the cost will be `O(31 * log (N))` (thanks to binary search of object props, I believe checking for object pros is internally optimized to use binary search, but I'm not 100% sure), so it should more like 31 x 7 = 217 check

**Comment by jacekkarczmarczyk** [comment]
Closing this issue as invalid (allowed dates don't accept Date objects any longer, so there's no more timestamp that might be retained or modified)

**Comment by slurmulon** [comment]
> So as I wrote before in order to simply the mechanism and avoid time zone issues we're changing the date picker to accept only strings in ISO 8601 format, so there's no more time included in the input or output values, neither in allowedDates, it's just "2017-10-10" format. Even (similar to native <input type="date">) the ISO format with time ("2017-10-10T12:00:00") won't be accepted.

I believe that decision inhibits the applicability of the Date Picker because it imposes a strict opinion over the allowed accuracy of the data (i.e. the lowest you should ever be able to go is date. Hours, minutes, etc are irrelevant). If you disagree with my perspective I completely respect that, but here is my two cents.

We are unable to map our data properly back without doing a nasty workaround, which is to convert our full dates back and forth between midnight and the original date. For instance, when a date is selected in the calendar we need to map this back to a parent object. Instead of just being able to `filter` or `find` against a native `Date` or a UNIX timestamp, we now have to modify the data in place so that we compare by the date at midnight instead.

We are forced into this because we can't associate arbitrary ID information or anything really since you aren't using an `Object` as the primary format but are instead are using a `String` without any time info.

Another reason is that the data we originally give the component is being mutated, flooring it to midnight at the current date instead of retaining its accuracy. To me this is an anti-pattern, because now people can either ONLY use the time component or ONLY the date component. If you're stuck in between (which really isn't uncommon, and Vuetify offers no native solution for this), then too bad, you need to do sloppy workarounds and introduce inefficiencies. Or just keep building around the issue until Vuetify offers some combo Date+Time Picker component.

> This is a DATE picker, not DATETIME/TIMESTAMP picker

The way I look at it is a full date object (whether its UNIX timestamp, native `Date`, full ISO 8601, whatever) gives you the best of both worlds so you might as well just use it. Is having such a strict interpretation of the domain of this component worth the limitations that it introduces? For me the answer is "no" because you can always infer a date from a timestamp and you can also determine the microseconds or anything else in between, it gives you complete freedom.

You can always make the default _interpretation_ of the value be day/date because that's what this component revolves around, but to me it doesn't mean that the underlying data format has to be (or should be) compromised in terms of accuracy or purity. Especially when you're trying to make highly generic, non-invasive components that provide for hassle-free integration.

> I'd like to ask for clarification of this "36,500 ticks" issue, I not quite understand in what conditions it can happen. 

I was speaking in terms of ticks that take place across the entire calendar for the year, because we have customers with info that spans across several years.

> there would be max 31x100 = 3100 checks, and actually if you do it clever (for example keeping allowed dates as object properties) the cost will be O(31 * log (N)) (thanks to binary search of object props, I believe checking for object pros is internally optimized to use binary search, but I'm not 100% sure), so it should more like 31 x 7 = 217 check

Even on a per-month/year basis that's not ideal (needlessly inefficient and clumsy) but we can surely live with it. It slows down scrolling through the component but it's hardly noticeable, maybe 25ms or so.

---

I don't think I'm going to convince you otherwise, and that's OK. This is just my experience, however many others will be in a similar boat as Vuetify grows in adoption.

The majority of people are not _just_ storing or working with the date, they are storing and using either UNIX timestamps, full ISO 8601 strings or native date objects because they want to be able to utilize the full accuracy of the data whenever they see fit.

That's what it really what all boils down to for me, especially because we need to use this date to refer back to other information and we have no way of associating IDs or any other unique information to the data being stored by the Date Picker component. It's less about the efficiency and much more about the interoperability and ease of integration.

**Comment by jacekkarczmarczyk** [comment]
Thank you for this comment, there's always a place to improvement, but now the 0.17 is ready for release so even if we decide to accept Date objects probably it won't happen before 1.0 (personally I'd leave it as it is now, but I don't want to speak for all team)

> We are unable to map our data properly back without doing a nasty workaround, which is to convert our full dates back and forth between midnight and the original date. For instance, when a date is selected in the calendar we need to map this back to a parent object. Instead of just being able to filter or find against a native Date or a UNIX timestamp, we now have to modify the data in place so that we compare by the date at midnight instead.
> 
> We are forced into this because we can't associate arbitrary ID information (such as the IDs of the parent objects of our dates) or anything really since you aren't using an Object as the primary format but are instead are using a String without any time info.
> 
> Another reason is that the data we originally give the component is being mutated, flooring it to midnight at the current date instead of retaining its accuracy.

Can you show some codepen example with your code so I could understand the issue? 

> It slows down scrolling through the component but it's hardly noticeable, maybe 25ms or so.

The performance issue is something we've discovered recently and will try improve it for 0.17 patch
