### ISSUE TITLE
v-layout documentation missing some props

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [vuetifyjs/vuetify#2131]
### Steps to reproduce
Open https://vuetifyjs.com/layout/grid#api
In `Props` tab, select `v-container/v-layout/v-flex`

### Versions
Vuetify 0.16

### What is expected ?
v-layout has `row` and `column` props to set flex direction, so it should be documented, otherwise the `reverse` prop makes no sense.

### What is actually happening ?
Both props are not listed in the docs.

### Reproduction Link
https://vuetifyjs.com/layout/grid#api

**Comment by KaelWD** [comment]
Please submit issues with the documentation to the correct repo https://github.com/vuetifyjs/docs
