### ISSUE TITLE
[bug]VTextInput validation displays all the error messages

### ISSUE THREAD

**Issue by KingMario** [vuetifyjs/vuetify#2133]
### Steps to reproduce

Goto https://vuetifyjs.com/components/text-fields, scroll to #11 Validation, click the input for email, click other item in the page, you'll get:
![image](https://user-images.githubusercontent.com/3956876/31424342-45036d8e-ae1f-11e7-80ae-ed4b0472c856.png)

### Versions

v0.16.4

### What is expected ?

For this case, only the message for required is needed, as the behavior for earlier versions such as v0.15.7.

### What is actually happening ?

It's too crowded to show all the error messages. 

### Reproduction Link

https://vuetifyjs.com/components/text-fields
scroll to #11 Validation

**Comment by KaelWD** [comment]
a8fd957aef113a597c45cd09852d47764c35789d

**Comment by nekosaur** [comment]
I know I talked to @johnleider about this change, but I can't remember if we decided anything.

I am on the side of only showing the first error.

**Comment by KaelWD** [comment]
I agree. There's no examples of multiple errors on the [material guidelines](https://material.io/guidelines/patterns/errors.html#), and it's usually redundant having similar messages displayed twice (no shit it's an invalid email, it doesn't even exist).

**Comment by KingMario** [comment]
It also says (an error message)
> When input isn’t accepted, text fields can display an error message below the input line, with instructions on how to fix the error.

What about stop running the following validations after the first string returned, just as I have learnt from the movie Fracture, one criminal should not be judged twice(sorry for don't know the exact phrase, it's about due process of USA law, if you happened to have seen this movie).
