### ISSUE TITLE
custom theme not work ...

### ISSUE THREAD

**Issue by otygoo** [vuetifyjs/vuetify#2135]
Install the latest  vue  vuetify .....

webpack.base.conf.js roules add

  {
        test: /\.styl$/,
        loader: ['style-loader', 'css-loader', 'stylus-loader']
 }
App.vue
<style lang="stylus">
  @import './stylus/main'
</style>

stylus/main.styl

@require '../../node_modules/vuetify/src/stylus/settings/_colors' 
$mynameXX := {
  primary: $red.darken-2
  accent: $red.accent-2
  secondary: $grey.lighten-1
  info: $blue.lighten-1
  warning: $amber.darken-2
  error: $red.accent-4
  success: $green.lighten-2
}
@import  '../../node_modules/vuetify/src/stylus/main' 

app use as ..
<v-app mynameXX>

but no change ....

help ...

**Comment by sindrepm** [comment]
You need to use the variable **$theme**. Vuetify will not recognize your custom variable name.
https://vuetifyjs.com/style/theme

**Comment by otygoo** [comment]
Duplicate of # yes , i do as that  ,no change still ... one day ....i am crying...

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

**Comment by otygoo** [comment]
@KaelWD   thank you

**Comment by huangyanxiong01** [comment]
custom theme can't work well +1

**Comment by otygoo** [comment]
@huangyanxiong01  中国的？ 我的好了。。。

**Comment by nekosaur** [comment]
Please keep to english in issues, so that everyone can understand and participate in discussions. With that said, @huangyanxiong01 if you have a specific problem with themes, please create an issue, or join us at https://chat.vuetifyjs.com

**Comment by gyang274** [comment]
Any update? I changed theme and it works on an vuetifyjs version 0.13.0. I recently updated to vuetifyjs 1.0.0, same code, the fond

```

**Comment by KaelWD** [comment]
### READ THE PATCH NOTES IF YOU'RE UPDATING BETWEEN MAJOR VERSIONS
