### ISSUE TITLE
Menu inside another menu opening on hover

### ISSUE THREAD

**Issue by FilippiSilva** [vuetifyjs/vuetify#2142]
### Steps to reproduce
Use a menu within the other menu

### Versions
Vue 2.4.4
Vuetify 0.16.5
OS Arch Linux

### What is expected ?
When moving the mouse out of the first menu to the second menu, do not close the first

### What is actually happening ?
I picked up another bug when the two menus have their opening on hover. The second menu closes the first when the mouse exits the first menu.

### Reproduction Link
[ https://codepen.io/FilippiSilva/pen/pWKQGO?editors=1000](https://codepen.io/FilippiSilva/pen/pWKQGO?editors=1000)

**Comment by KaelWD** [comment]
Duplicate of #1877
