### ISSUE TITLE
Dialog does not open in Edge

### ISSUE THREAD

**Issue by sullivanpt** [vuetifyjs/vuetify#2146]
### Steps to reproduce
- Visit https://vuetifyjs.com/components/dialogs
- Clock any "Open Dialog" button

### Versions
Vuetify 0.16, Windows 10, build 1703, Edge 40.15063.674.0

### What is expected ?
dialog should render 
(in my memory this feature worked on edge in the previous release)

### What is actually happening ?
nothing visible changes. 
If console is open the message is "Object doesn't support property or method 'Symbol(Symbol.iterator)'"

### Reproduction Link
https://vuetifyjs.com/components/dialogs

**Comment by mi1971** [comment]
Hey guys.....Actually, John this is the exact same bug I've been talking to you about with iOS. Might be actually easier to trace what is going on with edge browser. Here is my video about it.  https://youtu.be/I_Ghdsu6aLk

**Comment by KaelWD** [comment]
Looks like edge doesn't support iterating over `HtmlCollection`s. Here's a codepen that fixes it by installing babel-polyfill: https://codepen.io/anon/pen/NaBvzO?editors=1011

#2150 Will fix this without a polyfill by converting the `HtmlCollection` to an array first.
