### ISSUE TITLE
Prevent temporary drawer from closing when clicking on dialog?

### ISSUE THREAD

**Issue by SteffenDE** [vuetifyjs/vuetify#2147]
### Versions
Vue 2.4.4
Vuetify 0.16.5
Chrome 61, macOS

### What is expected?
Clicking inside a dialog opened from within a temporary (or persistent on mobile) navigation drawer should do nothing. Clicking on the dialog background should close the dialog, but not the drawer.

### What is actually happening?
Clicking inside a dialog opened from within a temporary navigation drawer closes the drawer. When the dialog is only rendered if the drawer is open, it will close immediately. Clicking on the dialog background closes dialog and drawer at once.

### Reproduction Link
https://codepen.io/anon/pen/JrZgPo

**Comment by johnleider** [comment]
You can now handle this manually with the **stateless** prop a little bit of creativity.

https://codepen.io/johnjleider/pen/MOvxoP

**Comment by SteffenDE** [comment]
Perfect. Thank you very much!
