### ISSUE TITLE
[New Feature] Include a Playground.vue in the repo

### ISSUE THREAD

**Issue by KingMario** [vuetifyjs/vuetify#2148]
Suppose somebody wants to contribute, but doesn't read the [contributing](https://vuetifyjs.com/vuetify/contributing) section of the homepage.

After he cloned the repo and looked around, he is able to install dependencies and run the dev script all by himself. But in the browser he'll get only a blank page, and he'll notice some error messages in the console if he is a little curious.

I'd like to propose that providing a Playground with exactly the name of Playground.vue with directive information and a link to  [contributing](https://vuetifyjs.com/vuetify/contributing) to make it more straightforward.

The file could be something like this, but more _vuetiful_.
```
<template>
  <v-app>
    <h2>Vuetify Playground</h2>
    <div>You are now ready to contribute for vuetifyjs. You may want to modify the file in the dev directory called Playground.vue, whose content is what you are currently seeing.</div>
    <div>For more information, please visit <a href="https://vuetifyjs.com/vuetify/contributing" target="_blank">Contributing Vuetify</a>.</div>
    <div>Happy contributing.</div>
  </v-app>
</template>
```

Thanks.

**Comment by KaelWD** [comment]
You can have ignored files that are still in the repo.

**Comment by johnleider** [comment]
Kael loves to slam dunk me lol 🥇

**Comment by KingMario** [comment]
Right, keeping the file listed in .gitignore could avoid accidental committed changes.

**Comment by KaelWD** [comment]
Turns out ignored files aren't actually ignored if they exist in the index. This isn't really going to be possible.

**Comment by smiller171** [comment]
Could you use a pre-commit hook to make sure you're not committing changes to that file?

**Comment by KaelWD** [comment]
Yes, and we did for a bit. It caused too many problems though so I had to remove it. Ultimately it comes down to that fact that if you can't read a simple contributing guide then your change probably doesn't meet our standards to begin with.

**Comment by smiller171** [comment]
@KaelWD Your contributing guide actually doesn't say anything about the Playground file. I only figured out how to set it up by doing a google search when Webpack complained about the fact that it was missing, and landed here. As of right now this issue seems to be the most accessible instructions for how to set up that Playground file.

**Comment by KaelWD** [comment]
It does mention it here: https://vuetifyjs.com/en/getting-started/contributing#local-dev

You're right that the contributing.md file in the repo doesn't have that though, thanks for pointing it out.
