### ISSUE TITLE
[suggestion] Move from buble to babel (performance isnt everything)

### ISSUE THREAD

**Issue by robbiemu** [vuetifyjs/vuetify#215]
I know buble produces faster code, and I imagine that is why you use it. I've found two issues:

1. the rest operator does not work _inside of vue components only_ - it works just fine in, for example, a router.js file. The work-around you applied to get it working in places like that apparently does not apply to the vue component itself, and instead you have to rewrite it to object-assign style.

2. buble does not, and has never supported async/await. there was 8 months ago, a discussion thread about implementing it in buble, but it was described as contrary to the typical style of buble, and it never was added. I've talked with John Leider about this. I'm just voicing my opinion here for anyone working on the project.

Right now you have to manually convert your async/await functions to promise chains, (or, for example , manually run babel on your source file, copy the changed async/await function, and replace your code with that).

For these reasons, especially the second, which requires some more serious rewriting ont he part of developers in order to work with buble, I feel going back to babel is worth the performance hit.

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/tree/babel test branch up

**Comment by johnleider** [comment]
We talked about this in gitter. Your suggestion was in reference to the webpack template, which can be changed to babel, vuetify isn't  reliant upon buble.
