### ISSUE TITLE
[Feature] Allow redefinition of `$colors` object

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#2155]
I am creating my own theme, following the guide provided in "[Style-Theme](https://vuetifyjs.com/style/theme)" section. 

As I am already tailoring my CSS package, I would like to reduce the number of colour palettes, as I don't need it all and removing the unneeded ones can reduce my CSS size. Also, I would like to add my own palettes, and use it like the built-in ones, like `class="mybrandname lighten-2"`.

However, in the file [src/stylus/settings/_colors.styl](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/settings/_colors.styl) you guys use the overriding attribution operator from stylus, so I can't easily update the colour palettes.

Changing line [318](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/settings/_colors.styl#L318) to `$colors := {` would allow that to be done, without any prejudice to the current setup.

**Comment by jacekkarczmarczyk** [comment]
This is not fixed by theme PR, it's about redefining palette colors
