### ISSUE TITLE
VTextField does not submit VForm

### ISSUE THREAD

**Issue by lukeed** [vuetifyjs/vuetify#2159]
### Steps to reproduce

Navigate to _any_ `(v-)form` + `v-text-field` combo.

### Versions

* Vuetify: `0.16`
* Browsers: all vendors

### What is expected ?

The `form` or `v-form` should attempt a `form.submit()` action.

If any validation is connected to the TextField or its `(v-)form` parent, a validation attempt should be made first. Then, if validation passes, the `submit()` should continue.

Laslty, once implemented, `textarea`s and more complex inputs should stop the `enter` event from bubbling upwards to a `submit` event. This aligns with native behavior & user expectations.

### What is actually happening ?

Nothing.

### Reproduction Link

See https://vuetifyjs.com/components/forms -- all

See https://vuetifyjs.com/components/text-fields -- 11 & 16

**Comment by jacekkarczmarczyk** [comment]
Actually it does and it does it in the same way as native forms/inputs:

https://codepen.io/anon/pen/NwWEpZ?editors=1011

Focus any input and press enter - submit will be fired
Now check the "2 inputs" checkbox and do the same - submit won't be fired in both forms

**Comment by KaelWD** [comment]
To have enter submit a form with more than one input, you need to have a submit button: https://codepen.io/anon/pen/eeYQVg?editors=1011

Closing as this is consistent with the HTML specification.

**Comment by lukeed** [comment]
Great, thanks guys! I must have missed the `type=submit` and/or tried it at a time without my `@submit` handler attached. 🤦‍♂️
