### ISSUE TITLE
Stepper with v-for loop

### ISSUE THREAD

**Issue by roslaneshellanoo** [vuetifyjs/vuetify#216]
im trying to use this great new feature with v-for loop.
It's working fine except isActive on the v-stepper-step of the first "step" item.

```    <v-stepper v-model="activeStep">
      <v-stepper-header>
        <v-stepper-step
          :step="step"
          :complete="activeStep > index+1"
          v-for="(step, index) in steps"
          :key="step"
        ></v-stepper-step>
        <v-divider/>
      </v-stepper-header>
    </v-stepper>```

```   data () {
      return {
        steps: ['1', '2', '3', '4'],
        activeStep: 0,
      }
    },```


![Image shot 2017-03-16 at 0 54 37](https://cloud.githubusercontent.com/assets/20886073/23974469/0be34522-09e4-11e7-936d-a29f16356e49.png)

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by mfferreira** [comment]
@roslaneshellanoo You'll have to use the <template> tag. Here's an example: https://codepen.io/mfferreira/pen/vxeRZg?#

Note that you'll have to deal with that extra appended divider.

**Comment by johnleider** [comment]
Thank you @mfferreira

**Comment by roslaneshellanoo** [comment]
@mfferreira 
yes i know that i have to use template tag ..lol!
Sorry, it was my mistake. I didn't provided the full code.
You answer was very helpful. What i did is i just removed :

`:complete="activeStep > index+1"`
