### ISSUE TITLE
Color support for pickers

### ISSUE THREAD

**Issue by namlook** [vuetifyjs/vuetify#2163]
Feature request
============

It would be an improvement to make the picker components to support the `color` prop.

  - What will it allow you to do that you can't do today?

Specify color on the pickers (date/time) without overwriting vuetify's CSS

  - What potential bugs and edge cases does it help to avoid?

For now, we have to override the picker's css to make the color theme consistent.
It would prevent from having to update the ovewritten CSS each time a new version of vuetify updates the picker component internal markup

**Comment by KaelWD** [comment]
Please update your issue using the provided template, or the issue will be closed.

**Comment by namlook** [comment]
Done. Sorry for the inconvenience
