### ISSUE TITLE
v-select shows the string 'undefined' with vue 2.5.0 when nothing is selected

### ISSUE THREAD

**Issue by jaromero** [vuetifyjs/vuetify#2168]
### Steps to reproduce
Just use a `<v-select>` component.

### Versions
vue 2.5.0
vuetify 0.16.6 (also tested with 0.15.7)

### What is expected ?
When nothing is selected, only the label is shown.

### What is actually happening ?
When nothing is selected, the string 'undefined' is shown underneath the label. Selecting an option makes it disappear, and unselecting all options (if multiple or the v-model is reset) makes it show up again.

This only happens when using vue 2.5.0.

### Reproduction Link
https://codepen.io/jaromero/pen/yzxMJq

**Comment by jacekkarczmarczyk** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/commit/f5811774f8ec34c68eba40256600583a8a3311a7

**Comment by jaromero** [comment]
Hah! Suddenly this issue was fixed in my app, because I happened to upgrade vue again to test a different thing, and it turns out v2.5.1 came out literally 20 minutes ago. Hope it doesn't break again with this fix.

Thanks either way!
