### ISSUE TITLE
Update Docs for vee-validate

### ISSUE THREAD

**Issue by lobosan** [vuetifyjs/vuetify#2169]
### Steps to reproduce
Use $validates: true to activate vee-validate

### Versions
vee-validate 2.0.0-rc.19

### What is expected ?
Do not show warning in chrome dev-tools

### What is actually happening ?
This warning appears 

> $validates option has been deprecated please set the $_veeValidate.validator option to "new" instead

### Possible solution
Replace `$validates: true` with
```
$_veeValidate: {
    validator: 'new'
}
```

**Comment by nekosaur** [comment]
Please open this issue on docs repo instead. Thanks!

**Comment by lobosan** [comment]
Updated in docs
