### ISSUE TITLE
How to set text-field in toolbar?

### ISSUE THREAD

**Issue by SidKwok** [vuetifyjs/vuetify#217]
I see there is an [example](http://material.io/resizer/#device=window&width=840) about text-field in toolbar. I also see this in the doc: 
<img width="430" alt="396ae750-091e-420f-b83d-332397584576" src="https://cloud.githubusercontent.com/assets/13268747/23992033/6b8fb086-0a76-11e7-8ce7-6683268db384.png">

When I click search icon, I expect it will spread and become a text-field:
<img width="418" alt="0f7a0c06-5c17-46a5-84b9-1109d81c144f" src="https://cloud.githubusercontent.com/assets/13268747/23992169/e95d1bc0-0a76-11e7-8204-853b73582b82.png">

 but I can't see any information in the doc. How can I achieve this or it just can't?

**Comment by dohomi** [comment]
@SidKwok think this is duplication of https://github.com/vuetifyjs/vuetify/issues/158 
Currently not implemented but will come soon.

**Comment by SidKwok** [comment]
@dohomi  ok, I will close this issue for now.
