### ISSUE TITLE
VTooltip is documented to accept nudge-* options but doesn't use them

### ISSUE THREAD

**Issue by nborko** [vuetifyjs/vuetify#2170]
### Versions

vuetify 0.16.6

### What is expected ?

The `nudge-*` options should either be implemented or removed from the documentation.

### What is actually happening ?

The `nudge-*` options are not taken into consideration in calculateTop and calculateLeft

### Reproduction Link

by inspection of https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VTooltip/VTooltip.js

**Comment by johnleider** [comment]
This was triaged with #2175, would you mind if I closed this in favor of the other ticket?

**Comment by nborko** [comment]
No problem
