### ISSUE TITLE
date-picker set v-model in string mode fails

### ISSUE THREAD

**Issue by xevimayo** [vuetifyjs/vuetify#2173]
### Steps to reproduce
Open any date-picker with the v-model variable set with string mode and no number days appear in the calendar.

### Versions
v0.16.0-beta.5 and up

### What is expected ?
If the variable is set to '' or '2017-10-31T00:00:00+01:00' the days should appear and in the second case, the date must be selected.

### What is actually happening ?
No number days appear in the calendar and the picker title shows 'Invalid Date' text

### Reproduction Link
https://codepen.io/xevi/pen/KXxZjE

**Comment by johnleider** [comment]
Tagging this for #2109 @jacekkarczmarczyk

**Comment by lukeed** [comment]
Confirmed. Passing the string as `Oct 13, 2017` results in "Invalid Date" even though it's an acceptable form for `new Date()`.

**Comment by jacekkarczmarczyk** [comment]
With https://github.com/vuetifyjs/vuetify/pull/2109 empty strings (in ISO 8601 format) are accepted as a input value.

Note that this PR removes `formatted-value` and `date-format` props - in fact formatting function is passed to the date picker only to be called there, there is no reason why you can't call it by yourself. See the modified version of your codepen using the Vuetify with applied PR:
https://codepen.io/anon/pen/zEJyob?editors=1010

I also need to mention that the formatting function used in this (and yours) codepen is not timezone safe, some people may see the next or previous day, so it might be better to use some external lib for date formatting like moment.js

**Comment by xevimayo** [comment]
Thanks Jacek, 
Just little note: the modified version in codepen with de PR is working right in Chrome, but not in Firefox (v. 56) and either in Edge.
![image](https://user-images.githubusercontent.com/32779472/31576811-49b8effc-b103-11e7-9d44-c5bb81252aa5.png)

**Comment by jacekkarczmarczyk** [comment]
Yes, it's already fixed in the PR but not in the codepen
