### ISSUE TITLE
[Ennhancement] Change color of select multiple data (check box and text data)

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#2174]
It would be nice if we could change the color of the text of the select data and change also the color of the checkbox, or at least it should inherit the color that we set in the color prop for both checkbox and text.

**Comment by johnleider** [comment]
Can you please put a little more explanation into this request. Things such as example markup, example implementation or event a codepen demonstrating what you might like to see.

**Comment by 4eveRS** [comment]
Made this example.

https://codepen.io/anon/pen/dVqgOz?&editors=101

Created a select with multiple prop, with chips to show in full detail.

Check the text color inside the select ( selected data = blue)
Check the text color of the marked check box (teal)
Check the color of the chip when you remove it (blue)

Color setted in v-select. (green)

I think that all these elements should inherit the color from the color prop that is setted in the v-select component.

**Comment by johnleider** [comment]
This was added with #2189
