### ISSUE TITLE
[Bug Report] Toolbar icon highlight getting stuck after routing on mobile

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#2178]
### Versions
Vue 2.5.2
Vuetify 0.16.6

### What is expected ?
I'm expecting to be able to navigate between routes using icon links without the icon remaining selected or highlighted after the route has changed on mobile devices.

### What is actually happening ?
When switching between routes or using button on mobile they seem to be getting stuck in a highlighted state until the user clicks focus somewhere else on the screen.

![screen shot 2017-10-14 at 4 22 41 pm](https://user-images.githubusercontent.com/4167341/31574172-92513130-b08f-11e7-86e2-a006dbd0b2b5.png)

If you load the fiddle up below in Chrome using the mobile device viewer and click the back arrow the issue reveals itself.

### Reproduction Link
https://jsfiddle.net/mcfarljw/83r0bhmh/1/

**Comment by johnleider** [comment]
For whatever reason, on mobile, https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VBtn/VBtn.js#L111 gets called but never blurs properly.

**Comment by mcfarljw** [comment]
I spent a bit of time looking into this and it seems to be 100% caused by the `:hover` rule in the stylesheet. Just called blur doesn't dispose of that property on mobile. Might be other solutions, but it seems most places recommend binding to the mouseover and mouseout events to toggle a custom hover class. Something like this could be implemented:

```
routable.js

mouseover: this.mouseover,
mouseout: this.mouseout

VBtn.js

mouseover (e) {
  // add hover class
},
mouseout (e) {
  // remove hover class
},
```

@johnleider I could start working on this, but want to get your feedback first. Is this something that seems reasonable?

**Comment by afuentes90** [comment]
I have the same problem with v-tootltip component with a button inside, any idea to solve this? Thanks!

**Comment by johnleider** [comment]
@afuentes90 that is a completely separate issue, please create a new ticket.

**Comment by mcfarljw** [comment]
I have stumbled across a temporary fix that I've been using in my code that might also work as a more permanent fix. It could be combined with the touch detection class `.application--touch-support` to just globally disable `:hover:before` background colors.

```stylus
:hover:before
  background-color: transparent !important
```

**Comment by raslan3333** [comment]
Hello, 
I just want to say that the Button Animations are a little bit slower on mobiles than materialize Framework Buttons

**Comment by KaelWD** [comment]
Cool story.

**Comment by rkoval** [comment]
I have the same issue with the `v-hover`. Touching any element with a wrapping `v-hover` will cause any styles to persist until any other interaction with the page happens.

**Comment by 185driver** [comment]
From @jacekkarczmarczyk :
> Alternatively `:hover` rule could be applied only for `@media (hover: hover)` (not supported by IE, but who cares, and by Firefox, but the latter could be detected with `@supports` query)

As of Firefox 64 (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover#Browser_compatibility) or [CanIUse](https://caniuse.com/#feat=css-media-interaction)), this feature is fully implemented, meaning all major browsers now support it.  It would be awesome if Vuetify could implement something like this in v2.0 and remove this niggle on touch devices.
