### ISSUE TITLE
System bars is always fixed on top

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#2186]
System bars is now always locate fixed on the top of the windows which is not the correct behavior.

Expected, I can be placed anywhere. Ex. if it is wrap in v-card, it should be inside the v-card instead of being on the top.

Reproduction can be found in the code-pen example:
https://codepen.io/Ewocker/pen/WZaGvO?&editors=100
Each is overlap on top of another.

I found this when upgrading from Vuetify@0.15.x to Vuetify@0.16.6

**Comment by KaelWD** [comment]
Please update your issue using the provided template for issues, including a reproduction link, or the issue will be closed.

**Comment by Ewocker** [comment]
Hi, sorry for the bad link.
You should be able to see the problem now.
It is taken directly from the vuetify codepen example section for system bar
