### ISSUE TITLE
Enhancements for Sliders

### ISSUE THREAD

**Issue by flaviocordova** [vuetifyjs/vuetify#219]
I miss an option to force the user to select only values on steps, for example: If I define step of 5, s/he could only select 0, 5, 10, 15, 20, not the values in between...

Also, It would be nice if the steps could work as enumerations, that is, a discrete set of values with labels (so the user won't se the actual value for each one).

Last one: A "reverse" option that would fill (draw it blue) the line from the right to the left.

**Comment by flaviocordova** [comment]
The second suggestion (enumerations) could also be considered a "multi-value switch", where you would not only have on/off options but other intermediate states.

**Comment by johnleider** [comment]
I have this working in dev, but the way I show the ticks makes it look like it is off as it reaches the end of the range. Will keep poking and keep this thread updated.

**Comment by juanjoDiaz** [comment]
Any chance of this happening in the short term? I need this and I wouldn't have to implemente my own :)
I'm happy to help with a pull request if you point me in the right direction, @johnleider

**Comment by johnleider** [comment]
You are more than welcome to submit a PR. I have started this process on the enhancement/sliders branch, but it does have some complications that I have not had time to sort out yet.

**Comment by juanjoDiaz** [comment]
Did you forget to push that branch? I can't find it.

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/tree/enchancement/sliders

**Comment by juanjoDiaz** [comment]
Ohh. I couldn't find it because enhancement is misspelled. Thanks!!

**Comment by sentbyravens** [comment]
> Last one: A "reverse" option that would fill (draw it blue) the line from the right to the left.
Is it enhance done?
