### ISSUE TITLE
v-stepper step doesnt initiate by default

### ISSUE THREAD

**Issue by mixinmax1990** [vuetifyjs/vuetify#2191]
### Versions

Laravel 5.5, Blade, VueJs 2.5, Vuetify 0.16, All Browsers are effected 

### What is expected ?

I am running Vuetify on a Laravel Backend (with Blade Templating). I am having trouble getting the stepper active on load. The fiddle code below is the exact same code i am running (I pretty much just copied and pasted it). It works inside fiddle. Using v-model="e1" the first step is active. Thats driving me nuts

### What is actually happening ?

The stepper head is loaded,  without the first step active (so v-content isnt schowing). I therefore cannot click on continue/cancel

by the way im having the exact same issue with v-tabs, the tab/its-content bound using v-model does not activate. Again the code works on fiddle but not on my localhost. I feel like I am missing somthing obvious.
### Reproduction Link

https://jsfiddle.net/jg73x2ut/

**Comment by jacekkarczmarczyk** [comment]
As the code is working in the jsfiddle I'm closing this issue as invalid. If you need help finding solution for your problem or just discuss about Vuetify please visit official Discord channel http://chat.vuetifyjs.com
