### ISSUE TITLE
New Component / Multi-Select option

### ISSUE THREAD

**Issue by flaviocordova** [vuetifyjs/vuetify#220]
I'd like to suggest a new component (or an option to multi select) that could render its values as chimps, just like the example bellow.

![screen shot 2017-03-16 at 18 10 26](https://cloud.githubusercontent.com/assets/17955980/24018732/e6558b5e-0a73-11e7-98e8-452e23466eb8.png)

**Comment by ralphchristianeclipse** [comment]
@flaviocordova it's already in the docs please read :)

**Comment by johnleider** [comment]
Here is a [link](https://vuetifyjs.com/components/selects) to the section.
