### ISSUE TITLE
[Feature Request][v-dialog] fullscreen reactivity

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#2201]
Feature Request

When applying fullscreen for v-dialog based on the docs so it could be reactive.
`<v-dialog :fullscreen="$vuetify.breakpoint.xsOnly">
    ...
</v-dialog>`

Knows issues

- Overlay needs to be shown only if the fullscreen is true, otherwise it could be destroyed and again generated only when resize happens with fullscreen false.
- Scrollbar is hidden when fullscreen, even if the dialog is not visible yet (#5566).

**Comment by johnleider** [comment]
I'm a bit confused by this request. Are you asking for the `v-dialog` component to automatically use the breakpoint object to change its state?

**Comment by CodeSkills** [comment]
No, by reactivity I mean the possibility to resize the window while the dialog is open (for ex. from landscape)

Now the state is taken before the dialog is open, now while its open. Mostly for the backdrop now. When you open the dialog in fullscreen and then the viewport changes to classic dialog the backdrop is missing and vice versa. 

Most usages of this are on portable devices like tablets.

Hope I answered your question.

**Comment by KaelWD** [comment]
@CodeSkills Can you find the codepen you posted in discord and put it in the issue?

**Comment by CodeSkills** [comment]
It was this one

https://codepen.io/anon/pen/yzRdMJ

But it was to show the problem with backdrop not disappearing after fullscreen dialog close, which was already fixed. But the backdrop is not reactive, which you can see there also.

**Comment by bartmichu** [comment]
Shouldn't this be treated as a bug? I was just going to open a new issue when I found this one and I believe it describes the same problem.

Code:
```<v-dialog value="true" :fullscreen="$vuetify.breakpoint.xs" persistent max-width="90%">```

When you open a dialog on XS it is in full screen mode as expected. But now if you resize to something bigger and toggle ```fullscreen``` programmatically there is no shade in the background - and that's a bug.

**Comment by KaelWD** [comment]
Yeah probably

**Comment by bartmichu** [comment]
It's not only a visual problem (no backdrop). Everything in "background" will react to events now.

**Comment by johnleider** [comment]
This is being moved to v1.4 as it is directly tied to https://github.com/vuetifyjs/vuetify/pull/5015

**Comment by TheInvoker** [comment]
was this ever fixed?

**Comment by narkissbv** [comment]
Hey guys,
What's the status here? I've just tried reactively change the state of fullscreen like so: `:fullscreen="$vuetify.breakpoint.mdAndDown"` and it seems to not work.
Using Vuetify v1.4.4.

**Comment by HY0606** [comment]
> It's not only a visual problem (no backdrop). Everything in the "background" will react to events now.

@bartmichu  Have you solved this bug

**Comment by bartmichu** [comment]
Now it works as expected in my case, #5707 fixed it for me.

pon., 13.05.2019, 10:04 użytkownik 黄遥 <notifications@github.com> napisał:

**Comment by HY0606** [comment]
@bartmichu  @johnleider 
I actually want to ask, a full-screen dialog, when I type something into the text-field on my phone, I can see and swipe the background content, I can see all the background content。
If you know，please tell me
