### ISSUE TITLE
v-icon not centered in navigation drawer with less than 80px width 

### ISSUE THREAD

**Issue by njouanin** [vuetifyjs/vuetify#2205]
### Steps to reproduce
Create a navigation-drawer with `mini-variant-width` < 80 . See https://codepen.io/anon/pen/ZXqagr

### Versions
0.16.7

### What is expected ?
v-icon should be centered in the drawer

### What is actually happening ?
v-icon are right "shifted" which is not very nice. It's ok when the size is set to default (80px)

### Reproduction Link
https://codepen.io/anon/pen/ZXqagr

**Comment by swordwolt** [comment]
If you look at your example code with the developer tools, you can see that the v-icons aren't centered any ways. You have an left padding wich just fits in the "80px" width. Any changes to this width would cause that the Icons won't appear centered.

**Comment by njouanin** [comment]
so, what do you recommand to have a mini navigation drawer showing only (without text) centered icon ?

**Comment by johnleider** [comment]
As @swordwolt stated, there is not enough room. You would need to remove the padding. With that being said, the example no longer works.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
