### ISSUE TITLE
Editable Selects (with async query)

### ISSUE THREAD

**Issue by flaviocordova** [vuetifyjs/vuetify#221]
Select fields should enable user to type to filter options.
Furthermore, should enable async queries to the server for dynamic options.

**Comment by johnleider** [comment]
The first point is being added on the enhancement/select branch. The latter can be done by the developer, is there a specific reason it should be baked into the select?

**Comment by flaviocordova** [comment]
Actually they are different things mostly used together...
The first on just is to enable user to type to filter options (but they could be fixed, not dynamically loaded from the server). 

The second one could be done by the developer if he has the proper events to do so. However, since it might be needed often, the select component could bring some features to ease developer's life, as some control to wait N ms before calling the query, ignoring a response if something has been typed after the request sent, a "Loading" message, etc.
As I said, all of this could be done by the developer, but a smarter component could save some time coding.

**Comment by johnleider** [comment]
Well as I said before, the filtering is being added. As far as async queries, something like select2 wouldn't be bad perse. I'll test it out as I poke at select.

**Comment by johnleider** [comment]
This is going to be a wont fix. After deliberation, I've determined that ultimately, the dev can do this and does not need to be part of the select.
