### ISSUE TITLE
input-group--error does not have red color styling.

### ISSUE THREAD

**Issue by marcstedman** [vuetifyjs/vuetify#2212]
### Steps to reproduce
Use a <v-radio-group> component inside a form with validation and set input group to be required.
Use the following rule to make radio group a required field:
[(v) => !!v || 'This is required.']

### Versions
Vuetify 0.1.6.7
All browsers (chrome, safari, firefox)

### What is expected ?
When the input group is not set, the validator adds a class 'input-group input-group--error' but the CSS red color styling is not set. In version 0.15.x the following was applied:

.input-group.input-group--error label {
    color: #ff5252!important;
}

### What is actually happening ?
The red css styling is not applied. Only styles applied:

.input-group.input-group--error label {
    animation: a .6s cubic-bezier(.25,.8,.5,1);
}

### Reproduction Link
https://codepen.io/anon/pen/WZYWpo
Select an option. The error message should be red. It's not.

**Comment by marcstedman** [comment]
Could it be related to this change?
https://github.com/vuetifyjs/vuetify/commit/513ac208f0fe31488da48af2c8755f381776f625#diff-588ee44cf9da7ad2d60b7450b47bd81f

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1969?

**Comment by johnleider** [comment]
Not a duplicate @jacekkarczmarczyk
