### ISSUE TITLE
v-select does not render all items in IE

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#2213]
### Steps to reproduce
 - create a v-select with many items
 - open the select in Internet Explorer 11
 - scroll down

### Versions
 - 0.16.7

### What is expected ?
 -  You should be able to scroll to the last element

### What is actually happening ?
- You can only see the first 20 elements
- Errormessage: `[Vue warn]: Error in nextTick: "ReferenceError: "EventTarget" is undefined"`

### Reproduction Link
https://codepen.io/anon/pen/vevYer

**Comment by KaelWD** [comment]
Regression from #1821
