### ISSUE TITLE
VSelect only showing placeholder text on focus

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#2214]
### Versions

Vuetify 0.16.7, Vue 2.4.4-2.5+

### What is expected ?

Placeholder text should be visible when field is not focused

### What is actually happening ?

Placeholder text is only showing when field is focused.

### Reproduction Link

https://codepen.io/kdholt34/pen/jGXOeb

**Comment by KaelWD** [comment]
Regression from #2172
