### ISSUE TITLE
v-navigation-drawer with enable-resize-watcher covers toolbars and content when in desktop open mode

### ISSUE THREAD

**Issue by mikebaldry** [vuetifyjs/vuetify#2218]
### Steps to reproduce
Simple template with `v-navigation-drawer` using `enable-resize-watcher`, `persistent` and `app`
Followed by a toolbar and a container - see codepn

### Versions
0.16.7

### What is expected ?
When navigation drawer is open because the viewport is large enough, it should resize the rest of the content to fit in the remaining space

### What is actually happening ?
It covers it up and you can't see the start of the toolbar or the main container

### Reproduction Link
https://codepen.io/anon/pen/EwGNmq

### PS
Thanks for the great work!

**Comment by KaelWD** [comment]
You need to put `app` on the toolbar too, and wrap your container in `<main>` and `<v-content>`

There are layout examples on the website with complete source that you can refer to,

**Comment by mikebaldry** [comment]
Ah yes, you are correct. I missed that. My bad.
