### ISSUE TITLE
v-select causing errors when inside a v-else

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#2219]
### Steps to reproduce
1. Choose a value from the select
2. Check the browsers console error log (not the codepen one)
3. There should be an error
### Versions

Latest version of Vuetify and I've tested on Chrome and Firefox.
### What is expected ?

No errors in console.
### What is actually happening ?

This error is occurring I believe because the nextTick call is happening after the v-else removes the component. But I think because nextTick is async it gives me different errors in different browsers in different projects. 
```
//These two are related since listIndex is a property of $refs.menu

//Original project Firefox
[Vue warn]: Error in nextTick: "TypeError: _this12.$refs.menu is undefined"

//Original project Chrome
[Vue warn]: Error in nextTick: "TypeError: Cannot set property 'listIndex' of undefined"


//Test project Firefox
TypeError: _this.$refs.input is undefined

//Test project Chrome
Uncaught TypeError: Cannot read property 'setSelectionRange' of undefined
```

Also, because the errors are associated with conditional rendering they are avoidable if you use v-show (with an appropriate conditional statement) instead of v-else.
### Reproduction Link

https://codepen.io/anon/pen/xXmRrx?editors=1011

**Comment by qw3n** [comment]
@KaelWD will this fix the issues I was having with `$refs.menu.listIndex`? Or will you need a reproduction of that specific problem to fix it?

**Comment by KaelWD** [comment]
Make a new issue for that please, with reproduction.
