### ISSUE TITLE
Stepper Vertical Doesn't work with Modals

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#222]
![image](https://cloud.githubusercontent.com/assets/25447231/24025161/cea6f120-0af3-11e7-8092-4401e0bb5ddb.png)

I've followed the docs and used the vertical mode of the steppers and put it on the modal and the out come is in the image

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
