### ISSUE TITLE
question: how to set css selector in v-text-filed

### ISSUE THREAD

**Issue by JinSung-Hwang** [vuetifyjs/vuetify#2221]
hi
i have a question. im using nightwatch(2e2test) , vuetifyjs and vue.
im coding method bowser.setValue in nigthwatch 
im known that i need css selector

my vuetify code 
                    <v-text-field label="put in email" v-model="Email" dark >
                    </v-text-field>
i want to set emailValue in nightwatch code
i need to set css selector(id,class) in v-text-filed

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

**Comment by a1292717155** [comment]
@JinSung-Hwang hello, do you solve this? how to set the value?
