### ISSUE TITLE
Chip in-select : remove chips with backspace doesn't actually remove the items inside data array

### ISSUE THREAD

**Issue by baadillahnabil** [vuetifyjs/vuetify#2225]
### Versions
Vuetify: 0.16.3
Vuejs: 2.4.4
OS: Ubuntu
Browser: Chrome

### What is expected ?
The data removed from the array when keyboard backspace is pressed

### What is actually happening ?
The data doesn't removed from the array when keyboard backspace is pressed

### Reproduction Link
https://codepen.io/baadillahnabil/pen/MEZrEE

i have write in codepen to demo this :
https://codepen.io/baadillahnabil/pen/MEZrEE

when 'x' is clicked, it's removed from the data array, but when use keyboard backspace to remove it, it doesn't remove from data array

**Comment by KaelWD** [comment]
Yes it does: https://codepen.io/anon/pen/NaeXQg?editors=1011

**Comment by baadillahnabil** [comment]
oh, i'm sorry i didn't noticed that, i thought it will call `remove()` methods,, so how i can perform something when it removed with backspace ?
