### ISSUE TITLE
Feature Request: check if input has been destroyed before checking input.validate(true) in vForm validate()

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#2233]
In some cases Vue 2.x will not remove instances that have been "destroyed", but instead marks them as "destroyed".  When this happens, if a removed v-text-field, or any other validatable, was left in a state where it would fail validation,  but still exists in Vue's virtual DOM, vForm's validate() will fail validation.

Could be implemented by changing vForm.js's:
const errors = this.inputs.filter(input => !input.validate(true)).length
To something like:
const errors = this.inputs.filter(input => !input._isDestroyed && !input.validate(true)).length

### What will it allow you to do that you can't do today?
Use vForm validate() in cases where child elements have been "destroyed", but not removed from virtual DOM.

### How will it make current work-arounds straightforward?
Use vForm's validate() instead of having to loop form's inputs to implement what validate() is missing.

### What potential bugs and edge cases does it help to avoid?
Allow v-form's validate() to work in cases where Vue has removed an input from view, but it still exists in Vue's virtual DOM.

### Versions
0.16.7

**Comment by KaelWD** [comment]
Do you have a codepen or something that can reproduce this issue? As far as I'm aware, if a form component is removed (via v-if or similar) it should no longer be in the `inputs` array.

**Comment by Webifi** [comment]
It's more likely to happen when form elements are nested in a v-for, when the variable that a key is based on changes.  Don't really have time to work-up a code pen right now, but I'll try to find time over the next week.

**Comment by Webifi** [comment]
Closing this.  May re-request later, but for now I've refactored my code to not run into this issue.
