### ISSUE TITLE
Bad style behavior for icons inside chips 

### ISSUE THREAD

**Issue by shanemgrey** [vuetifyjs/vuetify#2236]
### Steps to reproduce
create a chip with an avatar-icon in it as shown in docs
add a "close" property to see correct behavior in contrast

### Versions

Vuetify Current version (16.6?)
MacOS +?
Chrome +?

### What is expected ?

The icon color on the left of the chip should change with the text-color property set for the chip

### What is actually happening ?

 - The icon color is not set to the default like the text and close button
 - Setting the color on the chip text changes those, but not the icon.
 - Setting the color on the icon directly has no impact

In effect, the icon color can't be changed in any way when inside an avatar in the chip, and when not inside the avatar, it is positioned wrongly.

### Reproduction Link

https://codepen.io/shanemgrey/pen/BwMKXr 

### Maybe related
The outline property doesn't produce an outline at all when there is no color specified.  Though the background does go away and the text color does change to what looks like the default color.

Also, the docs indicate that "Outlined chips inherit their border color from the current text color." when it is the other way around. The text inherits from the "color" set for the chip, and can be overridden with "text-color", but the text color does not currently impact the border color.

**Comment by johnleider** [comment]
Here an example markup that will work after release: https://codepen.io/johnjleider/pen/MOOBbr

The only difference is that when you use an icon that is not in an avatar, you must designate **left** or **right**
