### ISSUE TITLE
Tooltip open-delay default 0 needs to be changed to 200

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#2237]
Tooltips currently are very annoying unless the open-delay is changed to 200.  Make the default 200 or at least 100.  Thanks. 

  - What will it allow you to do that you can't do today?

Don't want popups coming up so fast users get confused

  - How will it make current work-arounds straightforward?

Every tooltip I've seen on Windows/Mac/Web etc have some delay before showing. Seems like Vuetify should too.

  - What potential bugs and edge cases does it help to avoid?

None

**Comment by nekosaur** [comment]
Please use the provided template when creating issues. Update your description or the issue will be closed. Thank you.

**Comment by sgehrman** [comment]
Out of the box, tooltips pop up instantly as the mouse is hovered over.  The default is 0 which is not what anyone would ever want.  Just suggesting that the default for 'open-delay' be changed to something reasonable like 200.  I did read the instructions.  For suggestions the template is not necessary.

**Comment by johnleider** [comment]
Even though you forgot to use the boilerplate, this is something I'm already looking at. @sgehrman would you mind updating this to match the required markup for a feature request? Thank you!

**Comment by sgehrman** [comment]
updated, but I still don't know exactly what the markup is exactly.  Not sure if I did it correctly.
