### ISSUE TITLE
Text selection controls in mobile Firefox are being activated

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#2239]
### Steps to reproduce
Tap on the first v-select in the examples
or
Single tap on the disabled text-field
or
Single tap below the disabled text-field
(This one's positioning is a little particular. If you double tap below the disabled you will see where the selection occurs and if you clear and then single tap near that it should cause a selection to occur.)

Also, while this normally occurred the first time I tried it occasionally I would need to scroll or resize the page before the selection handles appeared.
### Versions

v.16 on Android mobile Firefox

### What is expected ?

No text selection handles should appear and empty elements shouldn't be selected
### What is actually happening ?

As best I can tell the `<div.input-group__input>` is being selected with the `v-select`. <div.input-group__input> and `<div.input-group__details>` are the elements being selected for the the disabled and for the area underneath the text-field.

Double tapping causes selection, but these single taps should not (Firefox might be partially to blame for this though). The problem is especially with the `v-select` not only are the selection handles distracting, but sometimes the context menu option for "select all" appears on top of some of the options.

Also, if there is text selected in the `v-select` the selection handles no longer appear.

### Reproduction Link

https://vuetifyjs.com/components/selects
https://vuetifyjs.com/components/text-fields

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/pull/2241
