### ISSUE TITLE
Simple select

### ISSUE THREAD

**Issue by Zeph33** [vuetifyjs/vuetify#224]
New select is more complex.
No real input => can't move to select with keyboard
No simple value ? v-model is not the value of select, is object {value, text} can't attach directly on value, use of computed !
No input => can't disabled all input of form with fieldset
Can you add a simpler select with real input (type select V0.8.10) ?
It would be better and simpler to represent a database field
Thanks

**Comment by johnleider** [comment]
This is currently being worked on.

**Comment by suitedjimster** [comment]
Also, if it's a v-modal, you can't close the dropdown unless you select an option ( even ESC key doesn't work)
http://codepen.io/suitedJimster/pen/xqWVBP

**Comment by johnleider** [comment]
Also in the update.

**Comment by johnleider** [comment]
All of the requested functionality minus keyboard navigation of items is now in dev. Will be working on the last bit in the coming days.

**Comment by UngererFabien** [comment]
Also, can you update the doc ? It's not quite obvious for every one that items need to be objects {text: 'text', value:'value'} and if value is missing there is a strange behaviour where every thing is alway selected.

**Comment by johnleider** [comment]
You no longer are required to use objects as of 0.10.0.

**Comment by UngererFabien** [comment]
Really ? I just updated to 0.10.3 and struggled to make it work because the doc says:

v-model	Array, Object	-	Single select requires model, multiple requires array
items	Array	[]	The array of items. Item object is required to have a <code>text</code> property

https://vuetifyjs.com/components/selects

**Comment by johnleider** [comment]
That part was missed on the update. You can use an object, and if you do, you should use text/value, but you can also define your own ```item-value``` and ```item-text```. If you simply  use a primitive, it will act as the text and value.  I'll get the docs update today.

**Comment by johnleider** [comment]
closing this in favor of #400 as it contains all discussed functionality here as well as others we are working on.
