### ISSUE TITLE
The future of Vuetify

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#2240]
## The beginning
When I created Vuetify, it was a personal project meant to help spec out prototypes more efficiently. Only after sharing it with a co-worker was I convinced to release it as an full open-source project. The amazing [community](https://chat.vuetifyjs.com) and extremely talented developers that I have had the pleasure to be around are what make working on this project mean so much to me. But you cannot have the sweet without the sour. Maintaining the level of activity needed to accommodate the growing needs of the user-base has lead to many sleepless nights and time away from my family.

## The transition
With **v1.0** around the corner, the pressure is on and has no signs of letting up. After talking with my current employer, we both agree that this is a dream that should not be passed up. Starting on **November 1st**, I will officially transition my day job to Vuetify. Providing the best possible quality for developers and enterprise users will only be possible if I dedicate 100% of my time to building out the Vue and Vuetify ecosystem. I want to give developers and businesses from around the world a platform that they can use to succeed.

## The future
If this project has enabled you or your organization to do great things, I'm calling for your support. In the coming months I will be expanding the reach of Vuetify's community and support network by working with project backers and community members to help fine-tune the underdeveloped areas of the framework. The documentation will be updated with new guides, better examples, more resources and better i18n support.

<a href="https://www.patreon.com/vuetify">![become_a_patron_button](https://user-images.githubusercontent.com/9064066/31748879-24719c1e-b444-11e7-9c11-7600a5ca7199.png)</a>

Some other exciting features on the **Roadmap**:

- **Front-end component pack** 10 new components catered towards enhancing the front-end capabilities of your application _(from backers)_
- **Back-end component pack** 10 new components focused on providing solutions for common issues in dashboard based applications, CRUDs, etc _(from backers)_
- **Vue/Vuetify video course** A video tutorial series for Vue and Vuetify _(from backers)_
- **Alpha theme** A pre-built premium theme made for the front-end
- **Improved and additional free themes** I will be improving the current offerings and adding additional templates that are, and will always be, _free_
- **Improved international support** I will be working close with the community to ensure that Vuetify has the best possible support for all languages and locations
- **Improved enterprise support** Many Vuetify developers are part of organizations that want to know their investment is going to be supported. We will reach stable version **v1.0** in December with additional plans for LTS _(long-term support)_ following

## Thank you
These are just a few of the _many_ features and enhancements in store. I cannot wait to share the rest with you in the near future. I want to personally thank you and everyone else for your unwavering support. By whatever means you ended up here, I cannot express to you how grateful I am that you gave Vuetify a chance.

**Comment by sloan58** [comment]
Awesome news, John!  Can't wait to see what's coming. Vuetify rocks!

**Comment by donPuerto** [comment]
Future is coming ...

**Comment by logaretm** [comment]
Great news, John. Let me know if you need any help with the "validation" side of things 😄

**Comment by Dantiff** [comment]
Awesome! Vuetify rocks!

**Comment by alex-red** [comment]
Awesome news, and congrats John! Hope to see this project continue growing :)

**Comment by andrewdalpino** [comment]
Way to fucking go dude

**Comment by KuroroSam** [comment]
Awesome John!

**Comment by miseeger** [comment]
Brilliant news, John! And I hope this will last for a long, long time in order to have a reliable framework that's going to stay. To have this commitment and view of the future is a very important point to convice bosses using open source like Vuetify. Thanky you very much! 👍

**Comment by tobto** [comment]
good news!

**Comment by lea-anthony** [comment]
Awesome!

**Comment by cb109** [comment]
Wow, this keeps getting better! Wishing you the best of luck on this journey, John! :bowing_man::+1:

**Comment by MahdiMajidzadeh** [comment]
what about RTL support?

**Comment by jdriesen** [comment]
That's wonderful news, John.
Question to all colleague devs... which templates (styles) are you using for the moment ?
Do you maybe have some links or inspiration available ?
(I'm a dev, and no designer at all, that's why I'm asking)

Thanks in advance for your time to reply,
Johnny

**Comment by ritvikshandilya** [comment]
Excited 💯

**Comment by devatquarxss** [comment]
Vuetify provides an edge to Vue other libraries.  ;)

**Comment by azaars** [comment]
Way to go @johnleider

**Comment by DanilChugaev** [comment]
Awesome! You are the best!

**Comment by IamManchanda** [comment]
What about Sass support/port?

{ PS: I think I am well experienced in Sass, knowledgeable in stylus and would like to help }

**Comment by StratusBase** [comment]
Awesome news! Congrats!

**Comment by dohomi** [comment]
great news John!

**Comment by syncai** [comment]
Awesome, vuetify has been awesome so far!

**Comment by ysk8** [comment]
Awesome!, and all is becoming in a dream job for you @johnleider Go for it Vuetify and Vue

**Comment by raul-mg** [comment]
Excelent news

**Comment by BlackCode7** [comment]
Awesome! Vue and Vuetify for ever <3

**Comment by holuborhee** [comment]
Nice work @johnleider, i will love to see the style also improve so much. For now i still combine **Bootstrap 4** with **vuetify** in order to have better styling.

**Comment by hellosylvee** [comment]
Congrats!

**Comment by alexanderpepper** [comment]
Thank you for your hard work John! Vuetify has brought much joy to my dev life.

**Comment by Musbell** [comment]
Awesome!

**Comment by nassimBo55** [comment]
Brilliant work @johnleider!!! hope you the best.. and also @logaretm nice work on vee-validate 
you guys ROOCK!!! 🥇 🥇

**Comment by aero-no1-ks** [comment]
I am so appreciative of your great work!!

I am really happy to meet VuetifyJS. Thank you!!

**Comment by jdriesen** [comment]
@holuborhee : Small question.
Saw you're combining Vuetify with BS4.
Do you recommend this (in other words, this it work well ?)

As you can see in my post above, I'm also looking for a bit more attractive / creative themes...

Grtz,
Johnny.

**Comment by holuborhee** [comment]
@jdriesen Yeah, i recommend it, it at least satisfy to my own taste of attractiveness. Will be launching soon an application, where i combined the two

**Comment by jdriesen** [comment]
@holuborhee ... Well, these days, I'm a bit lost in the 'template' world.
We are having Bootstrap, Material, and Material for Bootstrap ...

If I can ask ...
The application you're going to launch.... is it public ?
Are you maybe willing to share some printscreens ?

Grtz,
Johnny

**Comment by argueta15** [comment]
Excited 💯

**Comment by sgehrman** [comment]
Great decision. I could tell on day one this was 'the shit'. No doubt you'll be successful.

**Comment by johnleider** [comment]
@jdriesen I'll release more information very very soon, ty for your patience.

**Comment by FreeCodePro** [comment]
Awesome！！

**Comment by jdriesen** [comment]
@johnleider : Thanks for your time to reply.
It's 7 AM, but you already made my day (and weekend)
Kind regards,
Johnny

**Comment by tbsvttr** [comment]
Very good!

**Comment by kdlslyv** [comment]
This exact ui framework made me pick up vuejs in the first place, amazing.

**Comment by rodrigo-rafael** [comment]
You made the right choice, congratulations!

**Comment by SirPoot-** [comment]
Amazing news!

**Comment by hoang17** [comment]
Awesome! Thanks for amazing works!

**Comment by DaleBeckles** [comment]
John:

After too many years with software pioneers, four startups, and six years of early retirement, vue and vuetify have inspired me to get back into the game. Congratulations on your move - I look forward to the fruits of your boldness..

_“Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.”_

— Goethe

**Comment by RGFanker** [comment]
As a UI/UX Designer, I am really enjoying the elegant way Vuetify works and the huge support from the Vuetify community.

**Comment by jdriesen** [comment]
@RGFanker : This is just a friendly question from an non-designer...

The current default topmenu and especially the tabs are looking rather 'block-ish'.
Can you maybe give us some hints / tips to make this a bit more attractive 
(I'm thinking about a transparant background, but, once again,  I don't know if this is the way to go..)

Grtz,
Johnny

**Comment by timobehrens** [comment]
Thank you for doing this John!

**Comment by RGFanker** [comment]
@jdriesen ,

Where in particular are you referring? The Vuetify website, actual components?

**Comment by jdriesen** [comment]
@RGFanker : 
Thanks for your reply.
I'm currently travelling... 
I'll give more details in about 24 hrs.

**Comment by luisfrocha** [comment]
Congratulations!  Looking forward to the new stuff coming. I can help out with Spanish translations.

**Comment by MathewsLima** [comment]
Muito obrigada por fazer o Vuetify @johnleider 
:+1:

**Comment by jdriesen** [comment]
@RGFanker :
Sorry I wasn't able to reply yesterday.
I'll hereby give you some more details.
I'm currently working on a "Sports Teams Mgt System" (non-commercial project)
In a couple of words... it's an App in which I can CRUD Teams, their players, their sponsors, etc...

As you can see in this printscreen, ![in this printscreen](https://www.driesen.eu/images/vuetifyjs.png), the layout is a real disaster.
I've been playing a bit with the colors in stylus/main.styl, but that's where my knowledge stops....

I'm an ex-bootstrap user. One of my favorite themes is named [the_project](http://htmlcoder.me/preview/the_project/v.2.0.5/template/components-tabs-and-pills.html)
It's sober, light, and very user friendly. (it has a clear and lightweight topmenu, nice and goodlooking tabs, etc)
I'm aware the "rounded" tabs are maybe not possible when using Vuetify (and I'm not expecting this :) ), but I really hope there is a possibility to get rid of the current "block-look"...

I've been searching a lot on the net to try to find an good-looking layout for a CRUD App, but I couldn't find anything....

I really hope somebody can give me some tips or guidelines,

Thanks in advance for any reply.
Grtz.

**Comment by jacekkarczmarczyk** [comment]
@jdriesen For any questions about Vuetify please visit official discord channel: https://chat.vuetifyjs.com

**Comment by jdriesen** [comment]
Sorry @jacekkarczmarczyk 
Didn't know about the official Discord Channel.
Appologies !

**Comment by itservices-tanger** [comment]
I always found vuetify an amazing project, When I use it, I am always surprised on how evrything was well designed, I am sure with this step the project will have an even brighter future.

**Comment by JW01F** [comment]
Awesome! Just in time when I'm about to build a back-end app for a project. Thank you for doing this.

**Comment by jundialwan** [comment]
Awesome John!
Vuetify is just amazing you know.
Glad to see those clear roadmap.
Thank you for your dedication.

**Comment by omadoyeabraham** [comment]
Thanks John for your excellent work and dedication. You rock

**Comment by doubledare704** [comment]
Congratulations! Looking forward to the new stuff. I can help out with Ukrainian translations.
just write to doubledare704@gmail.com

**Comment by alansaldivar87** [comment]
Not only providing an excellent framework but also a great guy. Thanks man! you can be sure that your work is helping many others to achieve their professional goals.

**Comment by Smona** [comment]
Awesome news! Vuetify has made building my first complex web app so much more manageable. I'm excited to see what the future holds

**Comment by FrancoisH** [comment]
@johnleider This is really a great news, which means we will have strong support in the future for your project, and it's a really, really good news. I just have a question, probably because I didn't fully understand the meaning of "from backers" in your future addition. Do you mean the components will be developped by project backers? But will be freely available? It's just we are a starting business and can't patron right now, but will probably be in the future as Vue+Vuetify will be our working base in the future. Thanks for your answers.

**Comment by johnleider** [comment]
Great question! It means that the feature was possible from the generous
donations from backers. The component packs and video series were stretch
goals for the patreon campaign.

**Comment by leandrobortolotto** [comment]
Great job @johnleider, Vuetify is awesome!

**Comment by jelofen** [comment]
Great news @johnleider, Vuetify is awesome!
on behalf of your international fans I hope you release RTL support soon. 
thank you

**Comment by detsanza** [comment]
Vuetify is just great, thanks for all the hard work and best of luck man, cheers!!

**Comment by wxs77577** [comment]
Thanks for your working, you are the best! 👍

**Comment by redvisual** [comment]
Great news!

**Comment by hudarui** [comment]
thank you! very like your project

**Comment by mitar** [comment]
Is there a plan where backers could give towards implementing a feature? Like bounty source approach?

**Comment by johnleider** [comment]
@mitar Backers have a special channel in discord where they already communicate these requests. There is currently no bounty source but I'm not opposed to it.

**Comment by cncuckoo** [comment]
@johnleider 祝你成功！

**Comment by maslunde** [comment]
Best of luck! The community needs people like you with that passion and drive!

**Comment by Gregory-Han** [comment]
I applaud your efforts.

**Comment by reticmanager** [comment]
Thankyou John for your hard work!! I will be backing / donating to the Vuetify project, it truly is amazing!

**Comment by adolt** [comment]
Best material designed component framework for Vue.js.

**Comment by ray-winkelman** [comment]
I'm using Vuetify for a large project, and would love to fix a bug I found in the text field component. It's driving me nuts. I'll pull the source and check out the internals soon.

**Comment by johnleider** [comment]
@ray-winkelman can you head over to https://chat.vuetifyjs.com ? We can hash it out there.

**Comment by AdnanMoghal** [comment]
Great way to go. Looking forward to have best vue material library. Thanks.

**Comment by Heunsig** [comment]
Thank you

**Comment by enix223** [comment]
Vuetify is an awesome project. Thank you for your great job, john...

**Comment by yoavfish** [comment]
Thanks dude! awesome news!!!

**Comment by connectedgrid** [comment]
Great things are in store for you, John!!  Keep up the amazing work!!

**Comment by AGhasemzadeh** [comment]
Hello,
We need RTL support too.
Thanks.

**Comment by kenng** [comment]
nice, looking forwards to use Vuetify soon!

**Comment by tobyhourst** [comment]
Awesome. I have just started developing an app with Laravel + Vuetify and I am loving it so far. Thank you for you great work.

**Comment by dotnet54** [comment]
great news :) thanks a lot for all contributors, this project has helped us a lot

**Comment by Maxhodges** [comment]
why don't you and the quasar guy partner up? seems a shame to see resources duplicated on two separate projects.

**Comment by Alex-TrioPoint** [comment]
Great News, The best UI Framework for me, am a beginner and this day marks the start of my Vuetify journey, Anyone out there with good tutorials help a beginner out!.

**Comment by adamelevate** [comment]
Been using this a few weeks now and it's also my first time with Vue, couldn't have been luckier to find this framework. Keep up the good work!

**Comment by KodiakSA** [comment]
Amazing framework! I'm.using in a reasonable sized project.  Is there a date 1.0 is expected?  Would like to upgrade if I have the time.

**Comment by scp-nm** [comment]
@KodiakSA - according to the roadmap it will be this month - https://vuetifyjs.com/vuetify/roadmap

**Comment by mrts** [comment]
> What about Sass support/port?
> { PS: I think I am well experienced in Sass, knowledgeable in stylus and can help }

@IamManchanda, it would be awesome if you could help! Please take a look at the discussion at the bottom of #2371. In short, @johnleider is willing to support SASS if someone takes care of Stylus-to-SASS compiling (which is not as scary as it sounds, see discussion).
