### ISSUE TITLE
v-text-field the displayed value is higher than the v-model value

### ISSUE THREAD

**Issue by thoss** [vuetifyjs/vuetify#2244]
### Steps to reproduce
Edit the number text field with the up arrow

### Versions
Vue: 2.5.2
Vuetify: 0.16.7

### What is expected ?
The displayed value is the same like v-model

### What is actually happening ?
The displayed value is higher than the v-model value

### Reproduction Link
https://codepen.io/anon/pen/jGdKRp

**Comment by nekosaur** [comment]
You forgot to fork the codepen before pasting it in here.

**Comment by KaelWD** [comment]
Not a vuetify problem, here it is with just a regular html input: https://codepen.io/anon/pen/qPgyYr?editors=1010

**Comment by thoss** [comment]
Thanks for your solution
