### ISSUE TITLE
Fab button overlap toolbar

### ISSUE THREAD

**Issue by stecapra** [vuetifyjs/vuetify#2246]
### Steps to reproduce
Go to docs, https://vuetifyjs.com/components/buttons, step 6. If set button to fab, it overlap the toolbar.

### Versions
v 0.16

### What is expected ?
The button should stay behind the toolbar

### What is actually happening ?
The button, if setted to fab overlap the toolbar

### Reproduction Link
https://vuetifyjs.com/components/buttons, step 6

**Comment by EvanZ** [comment]
Glad someone else noticed this!

**Comment by tutley** [comment]
+1

**Comment by johnleider** [comment]
This has been resolved in dev.

**Comment by pianointhedark** [comment]
fab still overlapping for your reference https://codepen.io/anon/pen/ppNrdz?&editors=101
