### ISSUE TITLE
vuetify 16.8 not work with nuxtjs lastest version only 16.1

### ISSUE THREAD

**Issue by dinho-afsn** [vuetifyjs/vuetify#2247]
nuxtjs not work with vuetify 16.8 only 16.1 
broken navigation drawer overlay

**Comment by nekosaur** [comment]
Please use the provided template when creating issues. Update your description or the issue will be closed. Thank you.

**Comment by dinho-afsn** [comment]
Hello, I can not reproach because the project is great with nuxtjs.
everything was working until version 16.1 any version above presents the problem.
do as you wish.
If you can check what happens in the next version please if not okay I use another framework
tanks.

**Comment by johnleider** [comment]
I am able to reproduce this issue with the vuetify nuxt package, however, fair is fair. I close all tickets that do not follow the reporting guidelines. Please update this issue with the proper boilerplate and I will re-open.  Thank you for your patience.
