### ISSUE TITLE
v-dialog hides scroll bar depending on window width.  Remove or make mobile-only

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#2250]
### Steps to reproduce

open a browser, make window  less than 1270px wide
Show a v-dialog
notice that scrollbar disappears

I'm on Windows chrome.

### Versions

0.16.8

### What is expected ?

I never want my scroll bar hidden when showing a dialog

### What is actually happening ?

scrollbar stays if window is wide enough, hides if window is narrow.
Inconsistent UI which is confusing.

### Reproduction Link

// here's the reproduction.  Didn't think it was necessary since every dialog has the same side effect
https://vuetifyjs.com/components/dialogs
Open Dialog 2 with different window widths on a desktop machine.

No need for reproduction, remove it or make it 'mobile only'
On desktop it's distracting

inside mixins/overlayable.js

  hideScroll () {
      if (this.$vuetify.breakpoint.mdAndDown) {    // ###### <--- this
        document.documentElement.classList.add('overflow-y-hidden')
      } else {
        window.addEventListener('wheel', this.scrollListener)
        window.addEventListener('keydown', this.scrollListener)
      }
    }

I don't ever want overflow-y-hidden set on my document no matter what the screen width.
Get rid of this entirely, or make it mobile browsers only.

**Comment by jacekkarczmarczyk** [comment]
Please include the reproduction link, otherwise issue will be closed. Thank you

**Comment by johnleider** [comment]
This was changed in 0.17. Will now only hide on smAndDown which should only occur for devs and mobile/tablet devices.
