### ISSUE TITLE
Select dropdown list does not retrack when null value selected

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#2254]
I really like the new changes to v-select but have found a few issues. Keep up the fab work :)

### Reproduction Link
See Scenario 1 on CodePen - https://codepen.io/anon/pen/aLMZPm

### Steps to reproduce
- Focus on select
- Select 2006
- Select Unspecified

This is possible the same issue as #2200 but hit via a different way

### Versions
Vue 2.4.2
Vuetify 0.16.7
Windows 10
Chrome 61

### What is expected ?
Dropdown is hidden and the model value is null

### What is actually happening ?
Dropdown is not hidden although model value is null

**Comment by KaelWD** [comment]
Cannot reproduce in your codepen.

**Comment by roryprimrose** [comment]
![scenario1](https://user-images.githubusercontent.com/2044291/31847297-0cf1e936-b665-11e7-8092-dd162cd16c70.gif)

Hmm, this isn't about null values. That just happened to be the scenario that I hit this with first. The issue is more that if a value is selected, then the list is opened again without loosing focus, the next selection does not hide the list.

**Comment by KaelWD** [comment]
I think it's because you're clicking on the icon, which is what #2200 was caused by.

**Comment by jacekkarczmarczyk** [comment]
I'm just looking at it

**Comment by roryprimrose** [comment]
Yes, that is true. I also just noticed that the arrow changes on the section of the next item but that is where the list stays open.
