### ISSUE TITLE
Clicking on list does not select the current text

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#2255]
I really like the new changes to v-select but have found a few issues. Keep up the fab work :)

Clicking on list does not select the current text forcing redundant actions and regular misuse for keyboard only actions.

### Reproduction Link
See Scenario 2 on CodePen - https://codepen.io/anon/pen/aLMZPm

### Steps to reproduce
- Focus on select
- Type '2006'

### Versions
Vue 2.4.2
Vuetify 0.16.7
Windows 10
Chrome 61

### What is expected ?
Existing text is selected when the dropdown is displayed so the user can start typing a new value

### What is actually happening ?
Immediate typing is appended to existing value. This almost always produces no matches.

**Comment by Webifi** [comment]
This would be nice to have.

The current work-around I've found is very much a hack:
https://codepen.io/webifi/pen/zEbJOB?editors=1010

The input element's value in the DOM doesn't seem to match the selected text on focus, so my hack simply waits until it does before select()ing the input element.  There may be a better way to wait for the input element to be in a better state, but it'll still be a hack.  

Would be much better to have a "selectAllOnFocus" prop.

**Comment by jacekkarczmarczyk** [comment]
@Webifi 

1. Your hackish solution could be much simpler:
```js
    selectAll() {
      setTimeout(() => this.$refs.select.$refs.input.select(), 200)
    }
```

2. The click behaviour is same as for v-text-field or native text input (it doesn't select the value), however it's different when TAB is pressed

3. The following patch does the thing, however it looks laggy (it selects the value after releasing the TAB key)
```diff
--- a/src/components/VSelect/mixins/select-generators.js
+++ b/src/components/VSelect/mixins/select-generators.js
@@ -135,6 +135,11 @@ export default {
           ...this.genListeners(),
           input: e => {
             this.searchValue = this.unmaskText(e.target.value)
+          },
+          keyup: e => {
+            if ([9, 16].includes(e.keyCode) && this.$refs.input && this.isAutocomplete) {
+              this.$refs.input.select()
+            }
           }
         }
```

I'm not sure why "The input element's value in the DOM doesn't seem to match the selected text on focus", this is probably the reason why it doesn't behave as native text inputs
