### ISSUE TITLE
Selecting a value by typing does not assign value when select looses focus

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#2256]
I really like the new changes to v-select but have found a few issues. Keep up the fab work :)

Clicking on list does not select the current text forcing redundant actions and regular misuse for keyboard only actions.

### Reproduction Link
See Scenario 3 and 4 on CodePen - https://codepen.io/anon/pen/aLMZPm

### Steps to reproduce
- Focus on select
- Double click or Ctrl+A on Unspecified value
- Type '2006'
- Press {Tab} or mouse click on other text field
- Model value remains at null

### Versions
Vue 2.4.2
Vuetify 0.16.7
Windows 10
Chrome 61

### What is expected ?
Model value is assigned when focus is lost due to a tab key press or focus on another field using the mouse

### What is actually happening ?
Model is not changed without the {Enter} key being pressed first

**Comment by jacekkarczmarczyk** [comment]
@roryprimrose thanks for detailed desciptions, could you please however create a separate issue for each problem? It will be easier to track it and implement changes. Please also note that scenario 3 is a duplicate ot https://github.com/vuetifyjs/vuetify/issues/2094
Thank you

**Comment by KaelWD** [comment]
I'll add that scenario 4 can be achieved by using the `combobox` prop.
