### ISSUE TITLE
Displaying the dropdown list has list scrolled to top

### ISSUE THREAD

**Issue by roryprimrose** [vuetifyjs/vuetify#2257]
I really like the new changes to v-select but have found a few issues. Keep up the fab work :)

### Reproduction Link
See Scenario 5 on CodePen - https://codepen.io/anon/pen/aLMZPm

### Steps to reproduce
- Select 1945 using the mouse
- Take focus away from select
- Select 1947

### Versions
Vue 2.4.2
Vuetify 0.16.7
Windows 10
Chrome 61

### What is expected ?
The dropdown to display the currently selected value in the viewport of the list

### What is actually happening ?
List displays from the top often causing a lot of unnecessary scrolling

**NOTE:** This works as expected if the list does not loose focus between selection attempts

**Comment by KaelWD** [comment]
Cannot reproduce in your codepen.

**Comment by roryprimrose** [comment]
I'll figure out how to make a gif of what I see and post it

**Comment by roryprimrose** [comment]
![scenario5](https://user-images.githubusercontent.com/2044291/31814700-2722af96-b5d6-11e7-8f68-555424a8132d.gif)

You can see here that when focus is taken away from the list and then the list is opened again, the list is scrolled to the top and does not show the current selected value.

Does this help?

**Comment by jacekkarczmarczyk** [comment]
1. That "Select 1947" point was probably misleading
2. "NOTE: This works as expected if the list does not loose focus between selection attempts" - without losing focus it behaves for me same as in your gif (click on select, chose 1945, click on select again), it's scrolled to the top

**Comment by Webifi** [comment]
Don't you just need to add the "auto" prop to the v-select?  Like:
https://codepen.io/webifi/pen/PJLeYd

**Comment by roryprimrose** [comment]
@Webifi Ah, that is perfect. Missed that one.
