### ISSUE TITLE
[Bug] Invalid css. Name of keyframe `query` replaced

### ISSUE THREAD

**Issue by qm3ster** [vuetifyjs/vuetify#2265]
### Steps to reproduce
`
vue init vuetifyjs/nuxt vuetify-test && cd vuetify-test && yarn && yarn build && code .nuxt/dist/common.*.css
`
Search for `@keyframes only screen`
### Versions
at least Vuetify 0.16.1 - 0.16.9
at least nuxt@1.0.0-rc9 - nuxt@1.0.0-rc11

### What is expected ?
`@-webkit-keyframes query{0%{right:-90%;left:100%}60%{right:-90%;left:100%}to{right:100%;left:-35%}}@keyframes query{0%{right:-90%;left:100%}60%{right:-90%;left:100%}to{right:100%;left:-35%}}`

### What is actually happening ?
`@-webkit-keyframes only screen and (min-width:1904px){0%{right:-90%;left:100%}60%{right:-90%;left:100%}to{right:100%;left:-35%}}@keyframes only screen and (min-width:1904px){0%{right:-90%;left:100%}60%{right:-90%;left:100%}to{right:100%;left:-35%}}`

### Other details
`query-short` unaffected.
The [affected keyframe is here](https://github.com/vuetifyjs/vuetify/blob/ebff54f8798ceb9ab23f9588e14e0a3c796f0e6a/src/stylus/components/_progress-linear.styl#L83).
This is [the only place where a variable called `query` is created](https://github.com/vuetifyjs/vuetify/blob/24d0b895ff70da2940abca57919dea9745176e7c/src/stylus/trumps/_display.styl#L1).

**Comment by qm3ster** [comment]
Changing `vuetify/src/stylus/trumps/_display.styl` to
```styl
for size, $query in $display-breakpoints
  .hidden
    &-{size}
      @media $query
        display: none !important

// ...
```
fixes it. But why this was happening in the first place is not 200% clear.

**Comment by qm3ster** [comment]
Can we deploy a temporary fix in the meantime?

**Comment by jacekkarczmarczyk** [comment]
I don't see it in https://unpkg.com/vuetify@0.17.0-beta.1/dist/vuetify.min.css
What version of stylus?

**Comment by qm3ster** [comment]
It doesn't end up in `vuetify.min.js`
In fact, the keyframes there are renamed `a` `b` `c` and `d`.
It happens if you run the commands I specified though.

**Comment by johnleider** [comment]
As of 0.17.0-beta.3 I am unable to see this in the un-minified version of the styles. If you are still able to reproduce it through other means, please let me know.

**Comment by qm3ster** [comment]
I tried the commands above again, currently resulting in
```
    "nuxt": "^1.0.0-rc11",
    "vuetify": "^0.16.9"
```
and the problem is there.

Manually updating to `"vuetify": "^0.17.0"` doesn't fix it either.

**Comment by johnleider** [comment]
To my knowledge nuxt does support vue@2.5.2 yet. Only 0.16.9 is compat.

**Comment by qm3ster** [comment]
It's not in package.json of the latest npm version, but it works for me. I'll report back here when there's a new release.
