### ISSUE TITLE
[v-select] with autocomplete, when positioned on top, should reduce items to the bottom

### ISSUE THREAD

**Issue by brenogazzola** [vuetifyjs/vuetify#2269]
### Steps to reproduce
1. Go to the "selects" documentation page (https://vuetifyjs.com/components/selects).
2. Place the v-select of the item #5 at the bottom of the browser screen.
3. Type "ala"

### Versions
Vuetify: 0.16.7
OS: Windows 10
Browsers: Chrome

### What is expected ?
As you type, the list of available items should reduce to the bottom.

### What is actually happening ?
The list keeps the same behavior as when it is positioned below the v-select,, reducing to the top. This causes a large white space to appear between the available items and the v-select element

### Reproduction Link
Use the #5 item on the documentation page: https://vuetifyjs.com/components/selects
![vuetify_issue](https://user-images.githubusercontent.com/1793280/31823149-e38696b8-b589-11e7-9b6a-c428614bc3d4.png)

**Comment by dwyer14** [comment]
+1. I see this issue with an autocomplete-select that's one of the last elements on a page...so the filtered items always appear _above_ the select input itself.

**Comment by jrast** [comment]
Will this issue be addressed in 1.0.0? At least alpha1 still has this bug.

**Comment by KaelWD** [comment]
I'll see if we can fit it in.
