### ISSUE TITLE
Modal Bottom row width problem in iOS/chrome

### ISSUE THREAD

**Issue by mstaack** [vuetifyjs/vuetify#227]
![img_2591](https://cloud.githubusercontent.com/assets/10169509/24060499/c00a9d3c-0b53-11e7-9b19-86f5b943ab9a.PNG)

There must be some problem with the modal bottom width

On latest iOS with latest chrome

**Comment by mstaack** [comment]
Same on safari / iOS 
![img_2592](https://cloud.githubusercontent.com/assets/10169509/24070235/871a9fac-0bb9-11e7-891d-a8491b77140c.PNG)

**Comment by johnleider** [comment]
No bug, just didn't set the grid properties right for xs devices.
