### ISSUE TITLE
Long v-list-title in flex layout will break after passing breakpoint

### ISSUE THREAD

**Issue by napalmduo** [vuetifyjs/vuetify#2270]
### Steps to reproduce
Have a v-list in for example a flex md4 with a long text in "v-list-tile-title" that will be cut off because of text-overflow: ellipsis.

Resize window to a size lower than the breakpoint of md.

The text-overflow ellipsis won't work because the div with the flex class doen't have a max-width anymore.

@media (min-width: 960px)
.flex.md4 {
    flex-basis: 33.33333333333333%;
    max-width: 33.33333333333333%;
} --> under 960 px no max-width is on the div and it will be as large as the text because the text isn't wrapping because of whitespace: nowrap from the style .list__tile__sub-title, .list__tile__title

### Versions
0,16,7

### What is expected ?
Either let text wrap or give the div.flex max-width: 100%

### What is actually happening ?
No wrapping and no max-width on div

### Reproduction Link
https://codepen.io/napalmduo/full/WZmXyY

**Comment by johnleider** [comment]
That is because **md4** only covers medium breakpoint and up, not down. You need to specify the other breakpoints.

https://codepen.io/johnjleider/pen/rGRRRa?editors=1010
