### ISSUE TITLE
[v-data-table] column header border rendering glitch

### ISSUE THREAD

**Issue by mikere** [vuetifyjs/vuetify#2271]
### Steps to reproduce

1. Create a simple v-data-table with at least two columns
2. Observe the result

### Versions

0.16.7
Chrome 62
Windows 10

### What is expected?

Table heading's bottom border is the same color everywhere

### What is actually happening?

The second, third, etc columns' heading border is slightly darker than the first column's.

### Reproduction Link

https://vuetifyjs.com/components/data-tables

**Comment by johnleider** [comment]
To confirm, are you referencing this?
![image](https://user-images.githubusercontent.com/9064066/31846669-b67f4d60-b5dc-11e7-8b79-7775b21122e9.png)

Where part of the header looks like a double line?

**Comment by KaelWD** [comment]
@johnleider In your screenshot, the bottom border is lighter in the first column.

**Comment by sindrepm** [comment]
This is actually a bug in Chrome which I have reported a while ago [here](https://bugs.chromium.org/p/chromium/issues/detail?id=769730). It happens if there is a colspan row with rgba border (the datatable__progress). One possible workaround is to use a solid border color (like `#dddddd`) instead of `rgba(0,0,0,.12)`.

**Comment by mikere** [comment]
@johnleider Yes, as @KaelWD wrote, the bottom border of the first column is lighter.

**Comment by ckitt** [comment]
@sindrepm 

Thanks @sindrepm for reminder, we encounter the same problem as well, and solve it by changing the border to solid color (solid 1px #DDD).

```
  .table >>> .table thead {
    border-bottom: solid 1px #DDDDDD;
  }
  .table >>> .table tbody tr:not(:last-child) {
    border-bottom: solid 1px #DDDDDD;
  }
  .table >>> .table tfoot tr {
    border-top: solid 1px #DDDDDD;
  }
```
