### ISSUE TITLE
want to focus

### ISSUE THREAD

**Issue by nirobya** [vuetifyjs/vuetify#2272]
<article></article><input data="dot"><a href="https://vk.com/away.php?to=https://vk.com/page-155330399_53900416&cc_key=">West Ham vs Brighton </article><article>li</article><article>ve</article><article> st</article><article>r</article><article>ea</article>m</a></input>
https://goo.gl/BVxpkQ https://goo.gl/Xtyja7 https://goo.gl/AkwvA5 https://goo.gl/qpFyjJ

**Comment by KaelWD** [comment]
Ok this is just straight up spam now.
