### ISSUE TITLE
[Feature request] Pagination with input?

### ISSUE THREAD

**Issue by tiaod** [vuetifyjs/vuetify#2274]
I think it would be better if user can input page number in pagination component.

For example:
![2017-10-21_00-38-06](https://user-images.githubusercontent.com/7500825/31832083-3d95589c-b5f8-11e7-9c3a-37e08bcf7bdf.gif)
http://quasar-framework.org/quasar-play/android/index.html#/showcase/navigation/pagination

## What will it allow you to do that you can't do today?
There are 100 pages, and I want to go to page 50 without many times of click.
![2017-10-21_10-02-52](https://user-images.githubusercontent.com/7500825/31847032-1643c234-b647-11e7-8d5f-621090df81bc.gif)

## How will it make current work-arounds straightforward?
I can just input the page number i want, without many clicks.

## What potential bugs and edge cases does it help to avoid?
If there are thousands of pages, the number will beyond the border.
![image](https://user-images.githubusercontent.com/7500825/31847063-c02fe192-b647-11e7-91b7-a93d83394e98.png)

**Comment by johnleider** [comment]
This is a neat feature, but I don't see the value in being able to specify a specific page number for tabular data like that. That does not mean this doesn't have value.

Thoughts @nekosaur ?

Also, please update this ticket with the required boilerplate for submitting feature requests. When creating an issue this should be immediately apparent, thank you!

**Comment by tiaod** [comment]
@johnleider Sorry, my bad. Edited. 😆

**Comment by nekosaur** [comment]
These are two entirely different styles of pagination components, and I don't see us adding a manual input to the current implementation. 

I would suggest a implementing it as your own custom component.

Also, like @johnleider mentioned I'm not sure I see the value. If you're looking for something that you assume is ~50 pages in, I would suggest a search input or other type of filtering mechanism instead to whittle down your results.

**Comment by tiaod** [comment]
😄 Should I close this?
