### ISSUE TITLE
Problem using v-tooltip inside v-menu

### ISSUE THREAD

**Issue by davi5e** [vuetifyjs/vuetify#2276]
### Steps to reproduce

Just try to combine v-menu with a tooltip via v-tooltip

### Versions
0.16.9

### What is expected ?
There should be a way to show a tooltip if the user hovers a dropdown menu

### What is actually happening ?
Before 0.16, the directive v-tooltip had no problem being used with other components... Since it turned into a component, it fails to do basic stuff it once did...

### Reproduction Link
https://codepen.io/davi5e/pen/boZjXO
Please note that one button doesn't show due to the problem I'm describing...

### Comment
As I complained above, the old way was way simpler... Worked everywhere without any problems. If there will ever be a vote to revert to the directive behavior, I'd support it...

**Comment by johnleider** [comment]
Unfortunately the previous method could not work in a large majority of cases because it was a CSS only solution. I would much rather fix/improve this implementation than be crippled by the previous methods deficiencies.

**Comment by johnleider** [comment]
Here is a working example of the provided code, https://codepen.io/johnjleider/pen/zEbbMG. You did not have the tooltip properly slotted.

**Comment by davi5e** [comment]
I see. Thanks for the fix and explanation.

**Comment by MeoMix** [comment]
@johnleider In the working codepen you link to the menu displays at an incorrect position in the "fixed" example. It seems that using a tooltip wrapper messes up the "offset" logic for the menu.
