### ISSUE TITLE
Better integration with Vee-Validate plugin

### ISSUE THREAD

**Issue by filipsobol** [vuetifyjs/vuetify#2288]
Hi,

Vee-Validate team recently [released an update](https://github.com/baianat/vee-validate/pull/868) that allows better integration with 3rd party plugins. IMHO this is the best Vue validation plugin and better integration with it would be really nice.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
