### ISSUE TITLE
Warning Message In Console ({width} property)

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetify#2293]
Warning Message In Console ({width} property)
================
I am getting below error on several pages.

- console.log('The {width} property is being deprecated, please use {max-width}.');

### Versions
"vuetify": "^0.16.1"

### What is expected ?
* Solution to this warning message.

### Reproduction Link
* Once I change any component it show me this warning message in console.

**Comment by KaelWD** [comment]
Can you read? It says to replace `width` with `max-width` on your dialogs.

**Comment by jrvaja** [comment]
@KaelWD Yeah, I understand this. 
It was my mistake. I just see the message from `vuetify.js`, so I thought I was pending to resolve.

I am sorry for inconvenience caused to you.
