### ISSUE TITLE
Best way to change font

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [vuetifyjs/vuetify#2295]
Hi,

First I want to thank you for this awesome project.

I have a question please, what is the best way to change anything related to the font(font-family, font-size, etc.) per element and globally?

All the best,
Mohammed

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
