### ISSUE TITLE
Toolbar bouncing

### ISSUE THREAD

**Issue by arhont375** [vuetifyjs/vuetify#2296]
### Steps to reproduce
Documentation site of Vuetify. Step to reproduce:
1. Open documentation and keep attention on toolbar height
2. Notice that after full load it was changed
3. Reload page several times if not noticed at the first time

### Versions
vue          2.52
vuetify     0.16.7
webpack 2.7.0

### What is expected ?
During loading top toolbar keep required height

### What is actually happening ?
During loading top toolbar will change it height

PS
I'm not sure is it problem of Vuetify or WebPack and is it possible to fix it or not. But if possible it will be great!

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.
