### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by ackzell** [vuetifyjs/vuetify#23]
Hello, very interesting library :)

I'm getting started with Vue, and attempting to use an integration that is now being created for Meteor + Vue: [here](https://github.com/Akryum/meteor-vue-component).

I came across vuetify and thought I would just need to install it the way the docs state:

> Existing Projects
> If you are wanting to use Vuetify in an existing project, you can install by using npm or yarn.

In theory, this should work, correct? I mean, I don't need the template, I can use the library in an existing codebase with the setup that meteor-vue-component already has for compiling / serving etc.. ?

**Comment by johnleider** [comment]
You most certainly can. Right after that you should see the remaining information for hooking it up.
