### ISSUE TITLE
[Feature request] Emoji support for text fields

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#2304]
I don't know if this is the part of the direction Vuetify is going, but it would be super nice to have some kind of emoji support for text fields, similar to iMessage, Twitter, FB, etc. Specifically, to have a toolbar of sorts that enables searching and inserting emojis.

Short of direct support, or in the meantime, would love to hear suggestions how to implement this feature or see examples.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement.
