### ISSUE TITLE
Icons don't render inside v-btn components when using Samsung Internet Browsers

### ISSUE THREAD

**Issue by cappe** [vuetifyjs/vuetify#2306]
### Steps to reproduce
1. Have access to Samsung Internet Browser (an actual device, some emulator, Browserstack)
2. Go to project's quick start page https://vuetifyjs.com/vuetify/quick-start
3. Notice that the hamburger menu icon doesn't get rendered even though the actual menu button exists and works.

### Versions

Samsung S7 / Samsung Internet Browser 4.0.01-89 / Android 6.0 / Vue 2.5.2 / Vuetify 0.16.7
Samsung S6 / Samsung Internet Browser 4.0.01-89 / Android 5.0 / Vue 2.5.2 / Vuetify 0.16.7

### What is expected ?

Icons should be visible inside v-btn components when using Samsung Internet Browser.

### What is actually happening ?
Icons don't show up inside vt-btn components when using Samsung Internet Browser.

Now, I realize Samsung Internet Browser's market share being roughy 5%, it may not be the most popular browser around the block. I'm still submitting this bug report in case someone else encounters similar issues.

### Reproduction Link
Go to https://vuetifyjs.com/vuetify/quick-start by using Samsung Internet Browser.

**Comment by manico** [comment]
I have installed Samsung Internet Browser 6.2 and icons are visible.
Not sure if it is relevant to solve this as manufacturer obviously fixed this problem.

**Comment by KaelWD** [comment]
Is this still happening? We already have that rule on `.icon`

![screenshot_20180529_184036](https://user-images.githubusercontent.com/16421948/40647687-d7622ef8-636f-11e8-8999-7a2c67e7f7d7.png)

**Comment by cappe** [comment]
I am unable to test it on the same Samsung Browser version as I previously reported. I tested in on the same device though with a newer version (5.4.30.65) and all the icons work fine.

As far as I'm concerned, this issue can be closed.
