### ISSUE TITLE
[Bug Report] Number inputs and their validators don't work when using Samsung Internet Browser

### ISSUE THREAD

**Issue by cappe** [vuetifyjs/vuetify#2307]
### Steps to reproduce
1. Have access to Samsung Internet Browser (an actual device, some emulator, Browserstack).
2. Open CodePen https://codepen.io/anon/pen/zEQejp?editors=1010
3. Notice that the validators fail to validate the input. It actually reverts back to the initial value no matter what the input value is.
4. If the input type is something else than number (e.g. text), the input and its validators work just fine.

### Versions

Samsung S8 / Samsung Internet Browser 4.0.01-89 / Android 6.0 / Vue 2.5.2 / Vuetify 0.16.7

### What is expected ?
Number inputs and their validators should work as expected when using Samsung Internet Browser.

### What is actually happening ?
Number inputs neither accept new values nor validate them when using Samsung Internet Browser.

Similar to issue https://github.com/vuetifyjs/vuetify/issues/2306, I realize that Samsung Internet Browser's market share being roughy 5%, it may not be the most popular browser around the block. I'm still submitting this bug report in case someone else encounters similar issues.

### Reproduction Link
Go to CodePen https://codepen.io/anon/pen/zEQejp?editors=1010 by using Samsung Internet Browser.

**Comment by KaelWD** [comment]
Does it work with babel-polyfill? https://codepen.io/anon/pen/gGJEwP?editors=1010

**Comment by cappe** [comment]
It does not, tested with babel-polyfill version 6.26.0.

**Comment by don41382** [comment]
Using Samsung Galaxy S7, Android 7.0, Samsung Browser 6. It also looks like on a `type=number` the model doesn't get updated.

**Comment by manico** [comment]
Same as #2306, it works on my device (Moto Z, Android, Samsung Browser 6.2).
Seems to be issue with Samsung Device + Samsung Browser?

**Comment by blalan05** [comment]
Is this still an issue? Working on a Pixel 3, Android 9, Samsung Browser 8.2

**Comment by johnleider** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
