### ISSUE TITLE
Date picker performance

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2308]
`toLocaleDateString` should be replaced with `Intl.DateTimeFormat`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#Performance

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/2305#issuecomment-338976596
