### ISSUE TITLE
Datepicker in Chrome does not show October 2017

### ISSUE THREAD

**Issue by pbastowski** [vuetifyjs/vuetify#2310]
The datepicker does not show October 2017 in Chrome, but does in the current stable versions of Safari and Firefox.

### Chrome version - notice "MAR" shows twice and "OCT" is missing

![image](https://user-images.githubusercontent.com/5649024/31967310-d57b7336-b90d-11e7-8e64-83d454180766.png)

### Safari - as expected, shows all months

![image](https://user-images.githubusercontent.com/5649024/31967327-e3aa6688-b90d-11e7-9216-8f0954deff68.png)

### Steps to reproduce

Visit the Pickers section of Vuetify documentation in Chrome and in Safari and then pick any datepicker. Notice that in Chrome OCTober is missing and MARch is shown twice.

https://www.vuetifyjs.com/components/pickers

### Versions

Chrome Version 61.0.3163.100 (Official Build) (64-bit) for MacOS
Safari Version 11.0 (12604.1.38.1.7)
Vue 2.5.2
MacOS Sierra 10.12.6

### What is expected ?

I expect to be able to see OCT in Chrome.

### What is actually happening ?

In Chrome OCT is missing and MAR is shown twice.

### Reproduction Link

https://www.vuetifyjs.com/components/pickers

**Comment by CrystalMethod** [comment]
Seems to be fixed with Version 62.0.3202.62 (Offizieller Build) (64-Bit)

**Comment by pbastowski** [comment]
Indeed it is. Thanks @CrystalMethod .

**Comment by MrIndomitable** [comment]
I'm using Version 62.0.3202.94 and it's still happening.
