### ISSUE TITLE
Navigation drawer doesn't work in iframe

### ISSUE THREAD

**Issue by kulek1** [vuetifyjs/vuetify#2316]
### Versions
Vuetify 16.9
Vue 2.5

### What is expected ?
Navigation drawer should be visible and have "navigation-drawer--is-booted" class.

### What is actually happening ?
There is no "navigation-drawer--is-booted" class so dark overlay over content is fired but navigation drawer is still outside container.
Others components like v-select are working without any problems.

### Reproduction Link
It's kind of like that but it's impossible on codepen to include .js file to iframe. 
https://codepen.io/anon/pen/EwqYZZ?&editors=101

**Comment by KaelWD** [comment]
Codepen uses an iframe, you must be doing something else wrong. I'll close this unless you can provide a working reproduction of the problem (maybe a [codesandbox](codesandbox.io)?).

**Comment by kulek1** [comment]
Yes, codepen uses an iframe but not in that way. 
There's a difference between that because I'm using "npm run-script build" and afterward including that script in html using javascript.

Preview: http://teest-vuetifytest243840.codeanyapp.com/
index.html: https://pastebin.com/hyPDfEiS
script.js: https://pastebin.com/Uym2Mtcb

**Comment by KaelWD** [comment]
That iframe doesn't fire a load event, so nothing will boot:
https://github.com/vuetifyjs/vuetify/blob/307926a067bed1a8bea303b651bd8a94b6513b2c/src/components/VApp/VApp.js#L31

You will have to manually trigger `runCallbacks` on the `v-app` at an appropriate time.
