### ISSUE TITLE
Bug? v-card don0t accept @click event

### ISSUE THREAD

**Issue by xmorell** [vuetifyjs/vuetify#2317]
### Steps to reproduce

Create a v-card that throws an event when the user clicks over the card

### Versions

Vuetify : 0.16.9
Vue: 2.5.1

### What is expected ?

I expect that the onclick trigger executes the event

### What is actually happening ?

If the user clicks over the card nothing happens

### Reproduction Link

https://codepen.io/anon/pen/LzwpQa?&editors=101
the @mousedown is working fine. but the @click isn't

**Comment by KaelWD** [comment]
Use `@click.native`

**Comment by ultraN** [comment]
@KaelWD how come you guys change it back to it was. I thought @click is pretty cool. Any specific reason?

**Comment by KaelWD** [comment]
Did we change it? Buttons and the like can still use `@click`, but we don't re-emit the click event on everything, so you have to use `.native` sometimes. For example, this is just using vue (no vuetify): https://codepen.io/anon/pen/WZVMPN?editors=1010

**Comment by ultraN** [comment]
@KaelWD Thanks for replying. It's all good.

**Comment by jacekkarczmarczyk** [comment]
> Did we change it?

@KaelWD Seems like we did https://github.com/vuetifyjs/vuetify/issues/409#issuecomment-296350661
