### ISSUE TITLE
Slot-Scope documentation update from Vue 2.1.0 and above

### ISSUE THREAD

**Issue by psychonetic** [vuetifyjs/vuetify#2318]
Vue 2.1.0+ changed the scope to slot-scope. If you use eg. datatable with custom slots for header, items and footer, you will get a warning, if you use only scope.

Therefore the documentation needs to be updated for all components which are using slots with scopes.
See also: https://vuejs.org/v2/guide/components.html#Scoped-Slots

Vue version: 2.1.0+
Vuetify version: 0.17.0-beta.1 and also 0.16

You also may need to check some components itself if they consist of child components. Haven't reviewed all so far.

**Comment by jacekkarczmarczyk** [comment]
1. The docs repo is better for this kind of issues
2. It has been already updated https://dev.vuetifyjs.com/components/data-tables
