### ISSUE TITLE
Datepicker and Timepicker in dialog are aligned to the left

### ISSUE THREAD

**Issue by Aterbonus** [vuetifyjs/vuetify#2320]
### Steps to reproduce

Put a datepicker or timepicker in a dialog like in the docs and open it.
![screenshot_20171025_184842](https://user-images.githubusercontent.com/15003767/32025103-57116b9c-b9b5-11e7-9d17-d64237a30e03.png)

### Versions

Vue: 2.5.2
Vuetify: 0.17.0-beta.1
Chrome: 61.0.3163.100

### What is expected ?

The picker should be center aligned.

### What is actually happening ?

The picker is aligned to the left.

### Reproduction Link

https://codepen.io/Aterbonus/pen/pWMWWv

**Comment by jacekkarczmarczyk** [comment]
v-dialog needs to have `width="290px"` prop, fixed in docs (beta)
