### ISSUE TITLE
Weird behavior on select options list

### ISSUE THREAD

**Issue by lucas-dev** [vuetifyjs/vuetify#2322]
Maybe it's just me using the library improperly, but I need help with this problem.

As you can see on this picture, the select options are wrong positioned

https://ibb.co/hD5MQm

I could not fix the problem with the solution from this post:
https://github.com/vuetifyjs/vuetify/issues/1490

Please take a look at this code:
https://codepen.io/anon/pen/JrgMaY

Thanks in advance!

**Comment by KaelWD** [comment]
You need to use the `v-app` component: https://codepen.io/anon/pen/yzmvVB?editors=1010

**Comment by luiguild** [comment]
<v-app> component are already used in the main component but the select does not works correctly
![captura de tela 2017-11-02 as 23 52 55](https://user-images.githubusercontent.com/16566338/32358015-17c4a1e6-c029-11e7-95ae-2812e2b9465e.png)

**Comment by jacekkarczmarczyk** [comment]
This issue is closed, create a new issue using https://issues.vuetifyjs.com/
