### ISSUE TITLE
date-format prop doesn't work on the date-picker component  in 17.0-beta.1 

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2323]
### Steps to reproduce

Create a datepicker with the date-format prop and the formatted-value.sync prop in 17.0-beta.1

### Versions
17.0-beta.1

### What is expected ?
The format function should be called by the date picker as it is in v16

### What is actually happening ?
The format function isn't called and the date doesn't format.

### Reproduction Link
This behavior can be seen in example 12 on the dev docs site. 

https://dev.vuetifyjs.com/components/pickers#api

I also noticed that the dev docs don't contain an example for "Date pickers - Custom format". Example 5 on the v16 docs site.

https://vuetifyjs.com/components/pickers

Screenshot from the dev docs example 12

<img width="641" alt="pickers" src="https://user-images.githubusercontent.com/963226/32033835-f42e5c10-b9dc-11e7-9765-3728737c4cd2.png">

**Comment by jacekkarczmarczyk** [comment]
`date-format` and `formatted-value` has been removed from API. You can format date just by applying your formatting function the `v-model` value.
This month picker example should be removed from docs though (as it was done with date picker example)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/docs/commit/782c6fc22e8872dc15966a636a6fdbd698b1a054

**Comment by stoked74** [comment]
Thanks for the clarification @jacekkarczmarczyk. Definitely makes things simpler, which I like 👍

**Comment by gpassero** [comment]
@jacekkarczmarczyk  Could you please provide an example of applying a formatting function to v-model without using the deprecated date-format and formatted-value props?

**Comment by vikegart** [comment]
@jacekkarczmarczyk 
> You can format date just by applying your formatting function the v-model value
How I can do that? Can't find correct example

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/components/pickers#example-5

**Comment by hrvylein** [comment]
Unfortunately this isn't working if - like in my case - i need to format the value displayed in v-text-field. I need the date to be displayed like dd.mm.YYY but always fail with adapting the example from the 1.0 docs.

Whatever I try will break a) the cancel button not resetting the input field, b) date error leading to empty picker table, c) selecting a date in the picker, clicking on cancel, opening the picker again -> previously selected date is still marked.

Any hint?

**Comment by jacekkarczmarczyk** [comment]
This is issue is closed, if there is a bug please create a new one using the template http://issue.vuetifyjs.com
