### ISSUE TITLE
High CPU usage for v-progress-bar component. Ridiculous HIGH

### ISSUE THREAD

**Issue by ultraN** [vuetifyjs/vuetify#2324]
### Steps to reproduce
Just go to https://vuetifyjs.com/components/progress, open your chrome task manager sort by cpu usage.
### Versions

Vue 2.5.2
Vuetify 0.16.9
Webpack 3
Npm 5.xx
Ndoe 8.xx
OS: macOS 10.13
Browser: Chrome 62.0.3202.62
CPU: Core i7 (I7-3740QM)@2.7GHz, 4 cores 8 threads

### What is expected ?

Low or reasonable cpu usage. Not like ~30% all the time.

### What is actually happening ?

![qq20171026-150503](https://user-images.githubusercontent.com/3374628/32034591-1cc024e2-ba5f-11e7-9d09-ce652407f0b9.png)
As shown in the picture, the progress component is taking significant system resources to render/calculate the spinning circle.
### Reproduction Link

https://vuetifyjs.com/components/progress

**Comment by nekosaur** [comment]
This has been brought up before (https://github.com/vuetifyjs/vuetify/issues?utf8=%E2%9C%93&q=cpu%20progress). It seems to vary pretty wildly between setups. For me (CPU i5 3570, Win 10, Chrome 62.0.3202.62) it hovers around ~10%.

The docs page is also not representative of most real use cases for progress bars. That said, as a comparison, how's the CPU usage of this page (https://material.angularjs.org/latest/demo/progressCircular) for you? It's pretty similar for me at around 10%.

**Comment by KaelWD** [comment]
There's what, 15 loaders on that page? I don't think 2% each is too high, you aren't likely to have more than one or two on an actual page. There isn't really any way to create this animation without repaints anyway, as it is constantly changing length.

**Comment by ultraN** [comment]
@nekosaur @KaelWD I used docs page just because it's fastest way to represent this. In our own project, a single circle will take ~25% cpu resources. This metric is measured under 15'' retina screen.

**Comment by KaelWD** [comment]
What's the resolution of this "retina" screen?

**Comment by ultraN** [comment]
@KaelWD 2880 x 1800

**Comment by nekosaur** [comment]
Please create a codepen reproduction or github repo with your setup in which a single circle consumes 25% CPU

**Comment by peluprvi** [comment]
Testing here (i5-4690 + GTX 970 + Chrome 61.0.3163.100 64 bits) it consumes ~2% for a single circular progress and ~3% on the docs. I tested other implementations (with SVG, canvas and CSS only), and I got the same results.

**Comment by ultraN** [comment]
@peluprvi What’s your screen resolution?

**Comment by peluprvi** [comment]
@ultraN I'm on Windows 10, 1080p. I have the "Use hardware acceleration when available" option marked in `chrome://settings/`

**Comment by ultraN** [comment]
reproduce codepen example (like I said just a circle, nothing extra): [Code](https://codepen.io/arthur_zhu/pen/gXOKVj)
Screen Record:
![ezgif-5-44a636612a](https://user-images.githubusercontent.com/3374628/32139437-47d322d8-bc94-11e7-9e0e-7e03d0d9f584.gif)

**Comment by ultraN** [comment]
@peluprvi That setting in my browser is on. I think it's because retina screen's resolution is very high, and somehow chrome doesn't render it through GPU but CPU. And an interesting thing is: Safari seems like uses less CPU to render this and it is more smooth.

**Comment by ultraN** [comment]
I just had a look on my Chrome GPU acceleration status, some interesting find:
Macs with NVidia GPUs experience rendering issues on High Sierra: [773705](https://bugs.chromium.org/p/chromium/issues/detail?id=773705)
Disabled Features: accelerated_2d_canvas, gpu_rasterization

- Graphics Feature Status
- Canvas: Software only, hardware acceleration unavailable
- CheckerImaging: Disabled
- Flash: Hardware accelerated
- Flash Stage3D: Hardware accelerated
- Flash Stage3D Baseline profile: Hardware accelerated
- Compositing: Hardware accelerated
- Multiple Raster Threads: Enabled
- Native GpuMemoryBuffers: Hardware accelerated
- Rasterization: Software only, hardware acceleration unavailable
- Video Decode: Hardware accelerated
- Video Encode: Hardware accelerated
- WebGL: Hardware accelerated
- WebGL2: Hardware accelerated


- ATC | Software only
- ATCIA | Software only
- DXT1 | Software only
- DXT5 | Software only
- ETC1 | Software only
- R_8 | GPU_READ_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE_PERSISTENT
- R_16 | Software only
- RG_88 | Software only
- BGR_565 | Software only
- RGBA_4444 | Software only
- RGBX_8888 | Software only
- RGBA_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE
- BGRX_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE
- BGRA_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE_PERSISTENT
- RGBA_F16 | GPU_READ_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE_PERSISTENT
- YVU_420 | Software only
- YUV_420_BIPLANAR | GPU_READ_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE_PERSISTENT
- UYVY_422 | GPU_READ_CPU_READ_WRITE, GPU_READ_CPU_READ_WRITE_PERSISTENT

**Comment by ultraN** [comment]
I think this is probably why it takes so much CPU, because this job is supposed to be done by GPU. You guys can close this issue, since it's browser bug in very specific system and environment.

**Comment by nekosaur** [comment]
Thanks for the detailed investigation @ultraN
