### ISSUE TITLE
VDatePicker allowedDates as Object only working with both min and max

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#2333]
### Versions

Vuetify 0.16.8/0.16.9

### What is expected ?

Passing allowedDates as an Object should work with only min or max as well as with both. The return statement `return (!min || min <= date) && (!max || max >= date)` in v-date-picker's method isAllowed suggests that is already the intended behavior.

### What is actually happening ?

When min or max is null or missing from the Object, it gets caught on an error trying to format it for comparison.

### Reproduction Link

https://codepen.io/kdholt34/pen/wrVrRV

**Comment by KaelWD** [comment]
This behaviour has changed in 0.17 due to the date picker rewrite: https://codepen.io/anon/pen/xPKbyb?editors=1011
