### ISSUE TITLE
Horizontal scrolling of overflowing content in tabs changes the tab

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2335]
### Steps to reproduce
Create swipeable tabs with content wider than the tab width, scroll the tab content

### Versions
0.17

### What is expected ?
Content should be scrolled, tab should not change

### What is actually happening ?
Content is scrolled, later tab is changed

### Reproduction Link
Go to the API section https://dev.vuetifyjs.com/components/tabs in mobile and try to scroll the content to see the props description

**Comment by KaelWD** [comment]
tl;dr use `touchless`
