### ISSUE TITLE
v-checkbox need compare objects by a attribute and return object.

### ISSUE THREAD

**Issue by thiagoaos** [vuetifyjs/vuetify#2337]
### Versions
Vue https://unpkg.com/vue/dist/vue.js
Vuetify https://unpkg.com/vuetify/dist/vuetify.js

### What is expected ?
I expect the 'v-checkbox' component to be checked when the 'v-model' is initialized with an already existing object among the options. And I want the 'v-model' to save as selected objects rather than primitive types. This expected behavior already happens with 'v-select' using 'item-value' and 'return-object'

### What is actually happening ?
Currently the 'v-checkbox' is not getting marked when using it with object.
example:

when i set :value = "item.id" the comparator works however the object returned is the id
when i set :value = "item" the comparator does not work because, although the instances have the same content, they have different reference

### Reproduction Link
https://codepen.io/thiagoaos/pen/eeOoWj

I think using return-object with 'v-checkbox' will resolve the problem. But currently 'return-object' has no effect on 'v-checkbox'

**Comment by thiagoaos** [comment]
@nekosaur Do i need correct the issue structure?

**Comment by jadeOnlyone** [comment]
我的vuetify.js网格不能换行，这是为什么啊

**Comment by nekosaur** [comment]
Please keep all communication to english, or we'll be unable to assist.

**Comment by Renato66** [comment]
Fixed on 1.1 no breaking changes
