### ISSUE TITLE
When v-select is clearable, clear reopen it

### ISSUE THREAD

**Issue by DeltaEvo** [vuetifyjs/vuetify#2339]
### Steps to reproduce 
Create a clearable input and click on clear icon
### Versions
Latest

### What is expected ?
Select is not reopened when cleared

### What is actually happening ?
Select is opened when cleared

### Reproduction Link
https://codepen.io/anon/pen/vWYBvd

**Comment by johnleider** [comment]
This is currently the intended functionality.

**Comment by simzen85** [comment]
I think this should be configurable

**Comment by johnleider** [comment]
The current functionality was something that was iterated upon and ultimately decided. I think we could potentially add a prop for this in the future, but it is not something we should pursue atm.

**Comment by loucass003** [comment]
Yeah please add props for this
