### ISSUE TITLE
[<v-carousel>] Dynamically item loading problem.

### ISSUE THREAD

**Issue by waqasraz** [vuetifyjs/vuetify#2340]
### Versions

Vue: 2.5.2, Vuetify: 0.16.7, OS Ubuntu Linux, Browser: Chrome

### What is expected ?
Dynamically loading carousel items not working. 

### What is actually happening ?
When loading items from ajax request, the carousel HTML get updated but the item is invisible. 

### Reproduction Link
https://codepen.io/waqasraz/pen/YEKGMN

Images:
https://imgur.com/a/tRa2z

**Comment by nekosaur** [comment]
Has been added in https://github.com/vuetifyjs/vuetify/pull/2190 and https://github.com/vuetifyjs/vuetify/commit/d3e7d409d09120689b85f9bf8ebbde21847b0df4

Will be available in 1.0
