### ISSUE TITLE
Improvement Request: Add Ability to Programmatically Close Expansion Panel

### ISSUE THREAD

**Issue by theWebDevNick** [vuetifyjs/vuetify#2341]
Expansion panels can be opened or closed using the clicking the header. They can also be set to expanded on component load. However, it would be nice to have the ability to open and close the expansion panel programmatically.

For example, I am using an expansion panel to hide a search form. I would like to close the expansion panel when the user clicks the search button and begins a search.

**Comment by KaelWD** [comment]
You can control expansion panel visibility with `v-model` or the `value` prop: https://codepen.io/anon/pen/wPvoyx?editors=1010
