### ISSUE TITLE
suggest v-tooltip default 0ms delay before opening

### ISSUE THREAD

**Issue by kyorry** [vuetifyjs/vuetify#2343]
After I experience the 200ms delay, i most like the previous setting, feel more responsive faster.

**Comment by nekosaur** [comment]
Please update your issue using the provided template or it will be closed. Thank you.

**Comment by kyorry** [comment]
But, this is not issue.

**Comment by KaelWD** [comment]
Looks like one to me
![image](https://user-images.githubusercontent.com/16421948/32140285-96cf2704-bcaf-11e7-828a-63426f415794.png)

**Comment by kyorry** [comment]
I am not quite understand,  you can turn it off

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
