### ISSUE TITLE
Card Media Unescaped Url

### ISSUE THREAD

**Issue by manico** [vuetifyjs/vuetify#2346]
### Steps to reproduce

Bind image with space in path to card media src attribute.
Example: https://www.gamblinginsider.com/img/news/balkan bet.jpg

Card media will not show it until you encode it:
https://www.gamblinginsider.com/img/news/balkan%20bet.jpg

Not sure if this should be handled by vuetify component as it translates this to inline css (but it should be quoted then).
This is a common case when binding to data coming from different sources.

### Versions
"vue": "^2.5.2"
"vuetify": "^0.16.7"

### What is expected ?
Image should be displayed.

### What is actually happening ?
Image is not displayed.

**Comment by jacekkarczmarczyk** [comment]
URL with spaces is not a valid URL: https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space
I've opened PR that just adds quotes to the URL

**Comment by KaelWD** [comment]
It should probably be run through [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) instead.
