### ISSUE TITLE
v-navigation-drawer overlap content when width < medium (1264px)

### ISSUE THREAD

**Issue by davi5e** [vuetifyjs/vuetify#2348]
### Steps to reproduce
Go to the Google Calendar example (https://vuetifyjs.com/examples/layouts/google-contacts) and open Chrome's Dev Tools (F12). After this, check how the drawer makes the content re-position itself whenever the page width is > 1264px while overlapping it for < 1264px. The same thing happens if you switch to the mobile view (CTRL-SHIFT-M).

Also, having the mini prop on yields the same results...

### Versions
0.16

### What is expected ?
The content should always take the drawer into account OR close itself when the mouse clicks in the content (keeping the overlap, but closing for mobile browsers) 

### What is actually happening ?
It always overlaps, making some content appear behind the drawer.

### Reproduction Link
https://vuetifyjs.com/examples/layouts/google-contacts

### Images to help

Expected Behavior (width > 1264px | try to open and close the drawer)
![regular-ok](https://user-images.githubusercontent.com/25727609/32136952-448e87b4-bbf6-11e7-9f78-153c5dc9462d.png)

Overlapping (try to open and close the drawer)
![regular-overlap](https://user-images.githubusercontent.com/25727609/32136953-476489ac-bbf6-11e7-8dec-69855985366b.png)

Mobile without drawer
![mobile-ok](https://user-images.githubusercontent.com/25727609/32136955-4a3325b2-bbf6-11e7-8958-ba68617f01e8.png)

Mobile with drawer
![mobile-overlap](https://user-images.githubusercontent.com/25727609/32136957-4b99f250-bbf6-11e7-9468-5990d2f7c216.png)

**Comment by johnleider** [comment]
That is because the example was not setup properly. I have resolved this with https://github.com/vuetifyjs/docs/commit/b1471da59062d01ec7813288b1d8ba623e486fda#diff-75f631062aa831f521cbfd2498d86e0cR8
