### ISSUE TITLE
[Bug] [v-tooltip] curious behavior when reaching scrollbar/border

### ISSUE THREAD

**Issue by FrancoisH** [vuetifyjs/vuetify#2351]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Chrome,Firefox,Microsoft Edge
OS: Windows

### Expected Behavior
The tooltip should be aligned to the right side, not idented to the left as it is
When on Windows, the tooltip should be nudged to the left... not below the scrollbar

### Actual Behavior
The tooltip seems to correct the position and double the correction each exceeding pixel.
The tooltip positioning ignore if on Windows and is shown below the scrollbar.

### Reproduction Link
[https://codepen.io/francoish/pen/POoeGP](https://codepen.io/francoish/pen/POoeGP)

### Other comments
The margin manually assigned is to make sure the button is shown as it should, not bumped to the left (because being included into a tooltip).
This is not related to the nudge property being ignored, but the nudge option should allow to solve this case.

**Comment by shanemgrey** [comment]
This also happens on a Mac, but probably at different ranges of tooltip width. 
https://codepen.io/shanemgrey/pen/xPxzGK 

If you change the length of the string in the tooltip you can see there's a width of text where it looks good centered, and a width where it moves over.  But in between there is a small window where it is still centered and the side cut off by the window edge.

**Comment by johnleider** [comment]
@FrancoisH you are removing all of the margin from the button. What this does it make the tooltip want to overflow based upon its position. When it does, it will try to **not**. If I remove your class to disable the margin, it appears to be working as normal.

I can say, that since we always show overflow the calculation may need to be adjusted.

**Comment by DRoet** [comment]
This seems to be resolved somewhere in `> 1.x.x`: <https://codepen.io/anon/pen/PVgEjZ>
The tooltip is still a bit to the left, but it should never completely hug the browser window.

**Comment by KaelWD** [comment]
Previously it was accounting for the scrollbar (even when not present) + an extra margin, now it just stays at least 12px from the edge.
