### ISSUE TITLE
[Bug] VeutifyJS wont render anything with Google Fetch as Bot

### ISSUE THREAD

**Issue by vinaybedre** [vuetifyjs/vuetify#2361]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.3.3
Browsers: Chrome
OS: Windows,Linux

### Expected Behavior
Fetch as Google, should have rendered the page as seen on browser.
If we remove VuetifyJS from the main.js and deploy, the Google Fetches the rendered text. Something is wrong in VuetifyJS, which prevents Google crawling

### Actual Behavior
Fetch as google bot and google page insight, should be able to render the VuetifyJS app as rendered in a eg. Chrome browser. Or as a normal VueJS app does.

### Reproduction Link
[https://github.com/vinaybedre/vuetify-seo](https://github.com/vinaybedre/vuetify-seo)

**Comment by vinaybedre** [comment]
Adding more info.
Firebase app: https://axiomatic-port-517.firebaseapp.com/#/

Screenshot
![snip_20171030094427](https://user-images.githubusercontent.com/2630384/32154798-24481092-bd59-11e7-8bd8-be816e419470.png)

**Comment by KaelWD** [comment]
Can you try this? https://blog.codaxy.com/debugging-googlebot-crawl-errors-for-javascript-applications-5d9134c06ee7

**Comment by vinaybedre** [comment]
@KaelWD Thanks for providing this. I deployed with the code with windows.onerror in head section.
I still get a blank page. 
Thing is even under google page insights, I get a blank page,
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Faxiomatic-port-517.firebaseapp.com%2F

**Comment by KaelWD** [comment]
I'm not seeing the `onerror` section anywhere in the deployed page source, are you sure it's live?

**Comment by vinaybedre** [comment]
Hi,
Yes. Open in a incognito window. As firebase caches all documents by default for 1 day. 
Also I am sorry, I was doing some more trial and errors to the repository, but nothing seems working. I will wait until your further comments.

**Comment by KaelWD** [comment]
The google bot [uses a modified version of chrome 41](https://developers.google.com/search/docs/guides/rendering), so you need a polyfill to use modern javascript features (try opening the page in IE11). [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) was only added in chrome 45, so clearly the google bot won't be able to render that page. I'd recommend installing babel-polyfill, as that is what both the docs site and the dev environment use.

**Comment by vinaybedre** [comment]
Thanks. That helped.
