### ISSUE TITLE
Google Robot can't render Vuetify's Data Table

### ISSUE THREAD

**Issue by xerq** [vuetifyjs/vuetify#2363]
# Versions and Environment

Vuetify: 0.16.7
Vue: 2.4.4
Nuxt: 1.0.0-rc11

# Expected Behavior

Google should render the Data Table correctly, instead it shows that there is no data. It might have something to do with the javascript. The all other Vuetify elements in view-source are shown as simple HTML, in the Data Table there is some javascript object, which contains all table items.

# Actual Behavior

Google renders all elements correctly except the Data Table.

# Reproduction Link

Use https://github.com/vuetifyjs/nuxt to create the template and put a Data Table there, then render the page in Google Webmasters.

**Comment by johnleider** [comment]
Are you fetching the data that goes into the `v-data-table` component asynchronously?

**Comment by KaelWD** [comment]
Please provide an example project that will demonstrate this behaviour.

**Comment by vinaybedre** [comment]
I pulled in https://github.com/vuetifyjs/pwa repo, and deployed a firebase app at https://axiomatic-port-517.firebaseapp.com/. See the screenshot. 
![snip_20171030094427](https://user-images.githubusercontent.com/2630384/32154540-62145810-bd57-11e7-84dc-4535673fcd7e.png)

**Comment by KaelWD** [comment]
Can you try this? https://blog.codaxy.com/debugging-googlebot-crawl-errors-for-javascript-applications-5d9134c06ee7

**Comment by KaelWD** [comment]
The nuxt template does not come with a polyfill, you'll have to install one to enable your page to be rendered correctly in older browsers. See my other comment here for more information: https://github.com/vuetifyjs/vuetify/issues/2361#issuecomment-340396029

**Comment by xerq** [comment]
I got it fixed by setting the 'total-items' property.
