### ISSUE TITLE
[Bug] Carousel on Firefox only lazy loads images

### ISSUE THREAD

**Issue by drw112** [vuetifyjs/vuetify#2364]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Firefox
OS: Windows

### Expected Behavior
All of the images should download on page load rather than lazy load on Firefox

### Actual Behavior
Firefox is always lazy loading the images

### Reproduction Link
https://codepen.io/drw112/pen/wPBqzK?

**Comment by KaelWD** [comment]
You have to click save on codepen.

**Comment by drw112** [comment]
Updated with the correct link.

**Comment by johnleider** [comment]
I have no idea what you are referencing. Can you show a gif of the behavior or what is wrong? I don't see it.

**Comment by drw112** [comment]
![image](https://user-images.githubusercontent.com/9697868/33102826-3c69fae0-cee4-11e7-9502-620c227981a7.png)

Firefox is on the left.  All of the image resources finish loading at 7.87s or after the first turn of the carousel.  You can see the delay of loading sky.jpg in the Network tools where it doesn't try to load it until after 5.12s.

Chrome is on the right. All of the images resources finish loading at 1.05s.  You can see both images being loaded in the Network tools on the page load and not after 5 seconds.

For whatever reason Firefox is lazy loading the second, third, fourth image in the carousel.

**Comment by KaelWD** [comment]
This is because firefox does not load background images for elements with `display: none`. The carousel should be refactored to use `<img>` elements instead of css background images.

**Comment by KaelWD** [comment]
Turns out that has already been done in 1.0, see this codepen: https://codepen.io/anon/pen/vpyNYO?editors=1010
