### ISSUE TITLE
[Bug] The v-icon color prop isn't styling the icon with the assigned color

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2365]
### Versions and Environment
Vuetify: v0.17.0-beta.1
Vue: v2.5.2
Browsers: Chrome
OS: Mac OSX

### Expected Behavior
The icon should be colored

### Actual Behavior
The icon is the default grey/black

### Reproduction Link
[https://codepen.io/smitchell/pen/WXbvEy](https://codepen.io/smitchell/pen/WXbvEy)

### Other comments
This behavior can also be see on example 5 in the the dev docs

**Comment by jacekkarczmarczyk** [comment]
Fixed already on dev branch
