### ISSUE TITLE
[Feature Request] Add option to VDataTable for Disable Sorting

### ISSUE THREAD

**Issue by lukeed** [vuetifyjs/vuetify#2366]
### New Functionality
The DataTable component _always_ sorts the first column if no other sorting config is passed. This adds extra client-side work, even if/when the assumption is correct.

I should be able to pass a `default-sort="false"` to the table, to let the data show exactly as it was received.

Here is a minimal representation of the behavior: https://codepen.io/lukeed/pen/MOYwEL

The feature is definitely a nice-to-have, but I should be able to opt out of it when needed, and without needing to provide an alternative sorting method.

### Improvements
I should expect to see table rows in the order that my service returned. This also removes the need to have prior knowledge of _how_ the external data will be pre-sorted and returned to me.

### Bugs or Edge Cases it Helps Avoid
It allows me to render data _exactly_ as it was received. It also prevents extra/unnecessary client-side sorting calculations. The sorting function takes place even if the rows are pre-sorted by first column value too.

**Comment by buckwheat24** [comment]
In searching for a very similar thing, I ran across: https://github.com/vuetifyjs/vuetify/issues/442

I think it will provide a solution to what you're looking for. Setting all the headers to sortable: false, like:
```
headers: [
        {
          sortable: false
        },
        {
          text: "Headline",
          value: "headline",
          align: "left",
          sortable: false
        }
      ],
```
seems to completely disable the sort. Hope it helps!

**Comment by lukeed** [comment]
Right. I still want to retain sorting as a behavior. I just want a flag for turning off the initial/default sort.

**Comment by ckitt** [comment]
Seem by using the pagination.sync prop, we can achieve similar result as disabling sorting in DataTable, but I am not sure if we should do something like this in our project.

```
pagination: {
    sortBy: ''
}
```

**Comment by supraniti** [comment]
as stated in the docs regarding the 'headers' array, you can define the column following properties:
{
  text: string
  value: string
  align: 'left' | 'center' | 'right'
  sortable: boolean
  class: string[] | string
  width: string
}
if you define sortable as false, sorting will be disabled (for the specific column)

**Comment by blalan05** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

  
Thank you for your contribution and interest in improving Vuetify.
