### ISSUE TITLE
[Bug] V-Tooltip doesn't open with 'disabled=true'

### ISSUE THREAD

**Issue by flakekun** [vuetifyjs/vuetify#2372]
### Versions and Environment
Vuetify: v0.17.0-beta.1
Vue: v2.5.2
Browsers: Chrome
OS: Linux

### Expected Behavior
Tooltip is visible

### Actual Behavior
Tooltip is invisible :(

### Reproduction Link
[https://codepen.io/flakekun/pen/PJMvqR](https://codepen.io/flakekun/pen/PJMvqR)

### Other comments
I think that new 'disabled' property of v-tooltip clashes with usage of 'disabled' property in 'Menuable.watch.isActive'. When new property was named 'disabledHover' (in one of the commits) all worked fine.

**Comment by flakekun** [comment]
I don't mention that in issue: I want to control v-tooltip visibility with v-model property. In codepen property toggled with 'Info' button.

**Comment by johnleider** [comment]
In order to do that, you must remove the activator and control it specifically with the model. You were almost there,

https://codepen.io/johnjleider/pen/qVdgNw?editors=1010

Hope this helps.

**Comment by karlitos** [comment]
When the activator slot is removed the content inside the tooltip is not being displayed.

**Comment by jacekkarczmarczyk** [comment]
@karlitos create a new issue: http://issues.vuetifyjs.com

**Comment by karlitos** [comment]
My bad, I was investigating this now in further details and the right statement is:
> When the activator slot is removed AND the tooltip still envelopes the content, the content is not being displyed.

I overlooked, that the tooltip in the above _codepen_ example is is not enclosing the button, but it is a sibling element. I almost created a false bugreport 😃 

In Addition to that, you can use the _position-x/position-y_ properties and than something like event.target.position i the callback
