### ISSUE TITLE
[Bug] Menu is closing on enter key while autocomplete select is focused

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#2373]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.4.4
Browsers: Chrome,Opera
OS: Windows

### Expected Behavior
Item from select should be selected

### Actual Behavior
Menu is closed

### Reproduction Link
[https://codepen.io/anon/pen/yPygxO?editors=1011](https://codepen.io/anon/pen/yPygxO?editors=1011)

### Other comments
It is happening only if menu is inside card

**Comment by jacekkarczmarczyk** [comment]
Fixed in 0.17.0-beta.1

**Comment by KaelWD** [comment]
Duplicate of #2092
