### ISSUE TITLE
z-index conflicting for v-snackbar and v-dialog

### ISSUE THREAD

**Issue by Rud156** [vuetifyjs/vuetify#2378]
This is a question regarding the `z-index` for `v-snackbar` and `v-dialog`. The snackbar has a `z-index` of 7 whereas the dialog has a `z-index` of 192. This causes the snackbar to be hidden in case a full screen dialog is shown. Shouldn't it be opposite as a snackbar is meant for notifications. 

Also I tried asking this in the chat but no one replied back. So I created this issue.
In my project https://github.com/Rud156/News-Weaver/blob/master/client/src/components/Dashboard.vue#L9 I needed to explicitly set the `z-index` higher to display it.

Affects all vuetify versions on all browsers and across all operating systems.

**Comment by johnleider** [comment]
I can understand the frustration of someone not answering your question within the time you expected, but that doesn't change the fact that this board is strictly for bugs and feature requests. If you can reproduce your issue within a codepen or similar service and you consider it a bug, please use the [Vuetify Issue Creator](https://issues.vuetifyjs.com) to create a new ticket.
