### ISSUE TITLE
[Feature Request] v-textfield mask to allow signed numerical values

### ISSUE THREAD

**Issue by jess8bit** [vuetifyjs/vuetify#2379]
### New Functionality
I wish I could use the mask prop to allow user to enter a sign in front of a numerical value.
For example, if I want to enter a latitude, I should be allowed to enter -xx.xxxxx or +xx.xxxxx or xx.xxxxxx values. For now only positive values can be used when using numerical mask.
Here's what I try to achieve (though I can't really show  the expected behavior) : https://codepen.io/jess8bit/pen/POwVxO
Maybe use a 's' mask to position a sign ?
ex> s## . #####    where s can be '+' '-' or '' (which stands for +)

### Improvements
Without this possibility, we can't use the mask prop when the purpose of the input field is to store both negative or positive values.

**Comment by KaelWD** [comment]
See #2235

**Comment by jess8bit** [comment]
Brilliant!

I suppose the "General numeral mask" will cover my use case, so I close this request.

Looking forward to having it in the next release then!

thanks :)
