### ISSUE TITLE
Vue Datatable props expand , Bug... 

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify#2380]
I dont know why i my v-switch is not switching... 
i wont experiece it if i had  like so
on the tr tag...
```
<tr @click="props.expanded = !props.expanded">
```
but the behavior is not what i wanted (the whole row is toggle everytime i click any button) 
since i have buttons to click in a table row

if i move it on somewhere else let say a span or a button
```
<td class="title text-xs-left primary--text">
        <span @click="props.expanded = !props.expanded">{{ props.item.id }} </span>
 </td>
```

I cannot toggle anymore  one of  my v-switch
```vue
<template slot="items" scope="props">
            <tr @click="props.expanded = !props.expanded">
                <td class="title text-xs-left primary--text">
                    {{ props.item.id }}
                </td>
                <td class="title text-xs-left primary--text">{{ totalAmount(props.item) | currency(currency) }}</td>

                <td class="title text-xs-left primary--text">
                    <v-switch
                        :label="`${props.item.payment.paid ? 'Paid' : 'Unpaid'}`"
                        v-model="props.item.payment.paid"
                        color="primary"
                        light
                        :disabled="!hasRole('admin')"
                        >
                    </v-switch>
                </td>

                <td class="title text-xs-left primary--text">
                    <v-switch
                        :label="`${props.item.shipment.sent ? 'Delivered' : 'On-Hold'}`"
                        v-model="props.item.shipment.sent"
                        color="amber"
                        light
                        :disabled="!hasRole('admin')"
                        >
                    </v-switch>
                </td>
                <td class="title text-xs-left primary--text">
                    <v-switch
                        :label="`${props.item.shipment.received ? 'Received' : 'Pending'}`"
                        v-model="props.item.shipment.received"
                        color="green"
                        light
                        :disabled="!hasRole('admin') | !hasPermission('update-order')"
                        >
                    </v-switch>
                </td>
<!-- THIS ONE IS NOT RESPONDING TO CLICK EVENT -->
                <td class="title text-xs-left primary--text">
                    <v-switch
                        :label="`${props.item.payment.done ? 'Completed' : 'On-Progress'}`"
                        v-model="props.item.payment.done"
                        color="teal lighten-2"
                        light
                        :disabled="!hasRole('admin')"
                        >
                    </v-switch>
                </td>
```

The last TD has a problem when toggling the switch button, it is not updated or switch...
I just cant find the solution to this...  can someone please help me, ill be glad to share my whole vue component

I also try to watch the props, coincidentally, the 3 switch button updated my nested object.
but the completed switch button is not updating at all...

its really weird behavior

**Comment by codeitlikemiley** [comment]
the error was on my object, sorry im closing this now

**Comment by miketierce** [comment]
Could you elaborate on where you found the error? I'm having a similar issue. When I first started using the template code the rows expanded fine but now I can't get them to expand anymore. 

`<v-data-table
                :headers="headers"
                :items="results"
                :search="search"
                >
                <template slot="items" slot-scope="props">
                    <tr @click="props.expanded = !props.expanded">
                        <td class="text-xs-left">{{ props.item.SAP }}</td>
                        <td class="text-xs-left">{{ props.item.SubmissionDate }}</td>
                        <td class="text-xs-left">{{ props.item.Submitted_By }}</td>
                        <td v-if="props.item.Submission_ReasonCode == 1" class="text-xs-left">Training</td>
                        <td v-else>No</td>
                        <td class="text-xs-left">{{ props.item.Requested_Amount }}</td>
                        <td class="text-xs-left">insert date calc</td>
                        <td class="text-xs-dleft">{{ props.item.Request_Status }}</td>
                        <td class="text-xs-left">
                            <v-btn :to="{
                                name: 'Product',
                                params: {id: props.item.ID} }" 
                                flat small color="primary">Process
                            </v-btn>
                        </td>
                    </tr>
                </template>
                <template slot="expand" slot-scope="props">
                <v-card flat>
                    <v-card-text>Peek-a-boo!</v-card-text>
                </v-card>
                </template>
                <v-alert slot="no-results" :value="true" color="error" icon="warning">
                    Your search for "{{ search }}" found no results.
                </v-alert>
                </v-data-table>`

`export default {
  data() {
    return {
        search: '',
        results: [],
        headers: [
            {
                text: 'SAP',
                align: 'left',
                value: 'SAP'
            },
            { text: 'Received', value: 'SubmissionDate' },
            { text: 'By', value: 'Submitted_By' },
            { text: 'Type', value: 'Submission_ReasonCode' },
            { text: 'Requested Amount', value: 'Requested_Amount' },
            { text: 'Days In Pending', value: 'pending-days' },
            { text: 'Staus', value: 'Request_Status' },
            { text: 'Process', value: 'process', sortable: false}
            ],
    };`

**Comment by alansaldivar87** [comment]
@codeitlikemiley well I'm stuck on the same bump and it would be helpeful that whenever you found a solution you post the code so we can all check your code ;) IMO
