### ISSUE TITLE
[Feature Request] Opening a menu so that right side of the menu is aligned with right side of the activator

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2383]
### New Functionality
I would like to configure menu to open so that the right side of the menu is aligned with right side of the activator (and that menu is strictly under the activator).

### Improvements
See example here:

https://codepen.io/anon/pen/jaPbyR

If you click on avatar, it opens a menu. But menu is aligned on the left. To align on the right, extra custom CSS is needed, which is fragile and might break as Vuetify develops further.

### Bugs or Edge Cases it Helps Avoid
It is mostly a cosmetic thing, it allows one to precisely define the location of the menu and thus make menu predictable.

**Comment by johnleider** [comment]
You can already do this:

https://codepen.io/johnjleider/pen/xPGEom

**Comment by mitar** [comment]
Oh, I swear I tried this combination as well. Maybe because I added `offset-x`, too.

Oh, it seems the issue is that this does not work with short menu entry, see reproduction: https://codepen.io/anon/pen/GOJBzX

It looks like sometimes it works, sometimes it does not. Especially if one clicks it repeatedly in fast succession.

**Comment by JamesCoyle** [comment]
@johnleider This doesn't seem to solve the issue completely. The position is still defined based on the left edge of the menu so if the content of the menu changes size it will no longer be positioned correctly.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
