### ISSUE TITLE
[Bug] Data Table sortBy become null

### ISSUE THREAD

**Issue by nueko** [vuetifyjs/vuetify#2386]
### Versions and Environment
Vuetify: v0.17.0-beta.1
Vue: v2.5.2
Browsers: Chrome
OS: Windows

### Expected Behavior
pagination.sortBy keep and just toggle the descending boolean value

### Actual Behavior
`pagination.sortBy` become `null`

### Reproduction Link
[https://codepen.io/nueko/pen/dZoXeZ](https://codepen.io/nueko/pen/dZoXeZ)

**Comment by nekosaur** [comment]
Please include steps taken to reproduce the bug.

**Comment by jacekkarczmarczyk** [comment]
@nekosaur see issues for issue helper

**Comment by nueko** [comment]
I think I wrote the steps here https://issues.vuetifyjs.com/ but that's not included here

**Comment by nekosaur** [comment]
That's a feature, not a bug. If you don't want to allow the ability to cancel sorting, use prop `mustSort` available in 0.17.0-beta1

**Comment by nueko** [comment]
@nekosaur sorry, 
where is the docs for 0.17.0-beta1 ?

**Comment by azaars** [comment]
Here. https://dev.vuetifyjs.com/

**Comment by madi-madi** [comment]
add props must-sort 
                   <v-data-table
                            :items="Items"
                    >
