### ISSUE TITLE
[Feature Request] More Designs on Letter Avatar 

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#2387]
**New Functionality**

As per example on Letter avatar 
https://github.com/uttesh/ngletteravatar
![image](https://user-images.githubusercontent.com/9329005/32257739-d0bf01de-bef1-11e7-9840-82ea2e2f9424.png)
![image](https://user-images.githubusercontent.com/9329005/32257747-d92eb22e-bef1-11e7-83c4-7745b2991c64.png)
![image](https://user-images.githubusercontent.com/9329005/32257756-e1b798b6-bef1-11e7-8dc4-1c6c918def00.png)
![image](https://user-images.githubusercontent.com/9329005/32257767-f26c8b4e-bef1-11e7-8590-c2d0dda977a8.png)

**Improvements**

**Bugs or Edge Cases it Helps Avoid**

.

**Comment by nekosaur** [comment]
I feel like this is already possible with the v-avatar component? Border can be done through css. Or am I missing something?

**Comment by EvanZ** [comment]
Square and round is already done through `tile` isn't it?

**Comment by nekosaur** [comment]
Closing since I can't see anything not already possible through existing props and/or custom css.
