### ISSUE TITLE
[Bug] Vuetify Components do not render IOS Safari 7.1.2 Chrome 7.1.29.16.arm on Android 4.4.2

### ISSUE THREAD

**Issue by TimeBandit** [vuetifyjs/vuetify#2388]
### Versions and Environment
Vuetify: v0.16.9, v0.17.0-beta.1
Vue: v2.5.2
Browsers: Safari,Chrome
OS: Mac OSX,Linux

### Expected Behavior
To view the component on a device when running on local host via 192.168.x.x:[port#]

### Actual Behavior
Blank Screen

### Reproduction Link
[https://codepen.io/timeband-it/pen/mqyxMK?editors=1010](https://codepen.io/timeband-it/pen/mqyxMK?editors=1010)

### Other comments
Running Vue on it's own does work. On a side I have not had issues with react apps on these platforms. I think that for some reason vuetify is not loading, maybe it's the way the path is specified.

**Comment by KaelWD** [comment]
You need to use a polyfill if you want to support older browsers. https://babeljs.io/docs/usage/polyfill/
