### ISSUE TITLE
Icons not Displaying

### ISSUE THREAD

**Issue by tenjojeremy** [vuetifyjs/vuetify#239]
Hello,

Icons are not displaying  such as <v-icon medium class="grey--text text--darken-2">lock</v-icon>.

I just get the lock text.

This is my setup:

![example](https://cloud.githubusercontent.com/assets/25231946/24111516/0d7f2586-0d6d-11e7-96c4-c05bc62fff15.PNG)

Thank you in advance.

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by iamike** [comment]
reproduction? almost all of the android didn't show icon well. don't you notice it?
![980929239](https://user-images.githubusercontent.com/526854/27983889-9a6adef2-63fa-11e7-9e73-5ccd5325706d.jpg)
