### ISSUE TITLE
[Bug] Radio group and tooltip don't work

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#2393]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Chrome
OS: Mac OSX

### Expected Behavior
Radio group should work properly, selecting only 1 radio element.

### Actual Behavior
Radio group don't work properly if there's a tooltip in a radio, making the radio element with tooltip always stay selected.

### Reproduction Link
[https://codepen.io/4eveRS/pen/dZorqV](https://codepen.io/4eveRS/pen/dZorqV)

**Comment by KaelWD** [comment]
See also #2171

**Comment by KaelWD** [comment]
This was fixed in 0.17 
https://codepen.io/anon/pen/XYWJvy
