### ISSUE TITLE
[Bug] Page scrolls up when sweetalert2 dialog appears

### ISSUE THREAD

**Issue by knagyorg** [vuetifyjs/vuetify#2395]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Chrome,Safari,Firefox
OS: Mac OSX

### Expected Behavior
When click on any button the page content should stay on the same place

### Actual Behavior
Page content always scrolls up - go to the end of page and click button

### Reproduction Link
[https://jsfiddle.net/xvce8r9k/3/](https://jsfiddle.net/xvce8r9k/3/)

**Comment by KaelWD** [comment]
Doesn't happen in 0.17: https://jsfiddle.net/z89bc5ky/

Also I'd just like to go on record as saying [this might be the dumbest use of promises I've ever seen](https://github.com/limonte/sweetalert2/blob/f3af222c3f2dce7be601946ef26a5c1909b6c9be/src/sweetalert2.js#L653-L666)
