### ISSUE TITLE
Select menu animation buggy

### ISSUE THREAD

**Issue by zcyzcy88** [vuetifyjs/vuetify#240]
`btn-dropdown` or `select

![v](https://cloud.githubusercontent.com/assets/15178410/24163416/7c3b6230-0ea5-11e7-824f-e5806925785f.gif)

1. active menu
2. select item (menu will close)
3. active menu again
4. selected item won't animate, but not selected items animate.

https://github.com/vuetifyjs/vuetify/blob/00e7bbcff95f4211e197ac5811bf687733cabbd4/src/stylus/components/_menus.styl#L45

**Comment by johnleider** [comment]
That is there for auto with single select so that the selected appears above when opening menu, but it doesn't make sense for multi. Will fix.
