### ISSUE TITLE
[Feature Request] Quill integration / component

### ISSUE THREAD

**Issue by tbsvttr** [vuetifyjs/vuetify#2403]
### New Functionality
Rich text editing within text fields and maybe other cases.

### Improvements
You do not need to fiddle in Quill on your own or via nearly unknown external packages (like https://github.com/lioneil/vuetify-quill).

### Bugs or Edge Cases it Helps Avoid
Avoids problems with incompatibility cases, for example propagation problems with modals/ dialogs.

**Comment by johnleider** [comment]
Do you have an example implementation of this plugin and Vuetify so we have something to go off of?

**Comment by tbsvttr** [comment]
@johnleider Well, there would be that  (https://github.com/lioneil/vuetify-quill), but I do not know how well it is done.

**Comment by KaelWD** [comment]
Do you have anything that'll actually run? I just tried that package ind it's absolutely useless.
