### ISSUE TITLE
[Feature Request] Allow hex color codes for checkbox colors

### ISSUE THREAD

**Issue by jakobrosenberg** [vuetifyjs/vuetify#2405]
### New Functionality
Use hex color codes as well as the builtin colors for checkbox boxes.

### Improvements
You would be able to write
<v-checkbox color="red"> and 
<v-checkbox color="#ff0000">

### Bugs or Edge Cases it Helps Avoid
If you want to match a checkbox with a color code -- for instance one found in a DB entry -- you'd have to write a fairly large amount of javascript and css.

It would be much easier if Vuetify simply didn't translate colors that were prefixed with a hashtag.

### How could this be implemented ###
``if (color.charAt(0) === '#')``

**Comment by nekosaur** [comment]
I think you're missing some images perhaps? Or code blocks?

**Comment by jakobrosenberg** [comment]
Sorry, no. I just meant to illustrate that it would be very easy to check if a string if prefixed with a hashtag in order to preserve it.

**Comment by nekosaur** [comment]
And this?

>You would be able to write
and

**Comment by jakobrosenberg** [comment]
Ah, you're right. My bad. I have no idea how that got removed.

Anyway, you would be able to write both ``<v-checkbox color="red">`` and ``<v-checkbox color="#ff0000">``

At the moment colors are translated to a corresponding hex code. Hex codes, however, should just be left as they are.

**Comment by johnleider** [comment]
I'm not sure how I feel about this. While it sounds thematically that the **color** prop should accept any color type, this is out of the scope of what it should handle. I think that the best way to do this would be to simply create a class representing your color.

If any other team members disagree, please feel free to re-open.

**Comment by jakobrosenberg** [comment]
The issue with classes is, it becomes troublesome to have dynamic colors.

Imagine a table of users, cars etc, each with their own color code. If you want to be able to select a user with a checkbox that corresponds to that user, you could simply write ``<checkbox :color="user.color" :label="user.name">``

There are countless situations where you would want the checkboxes to represent a color-coded item. The fix seems very simple, the workaround I wouldn't even know where to start with.

**Comment by nekosaur** [comment]
While I'm definitely in favor of the proposed functionality, I do agree with @johnleider that it is currently out of scope of what the colorable mixin can handle. 

Your "How could this be implemented" section does not contain enough information on any actual implementation. Sure we can easily detect if a hex code has been passed in, but how do we apply it to the element? Any concrete implementation I can think of right now would involve a pretty heavy rewrite of colorable and all components that use it.

I'd be fine with re-opening the issue and putting a `help wanted` label on it.

**Comment by mizzao** [comment]
One reason this would be helpful is to be able to hash strings to colors using something like https://github.com/zenozeng/color-hash, for the ability to map arbitrary strings to unique colors. I've found it very hard to do this at the moment.
