### ISSUE TITLE
[Bug Report] Inconsistent handling of clicks on v-btn or items from Select component. 

### ISSUE THREAD

**Issue by Patsky** [vuetifyjs/vuetify#2406]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Google Chrome
OS: Mac OSX

### Steps to reproduce
In Chrome browser test mouse button clicks on any v-btn or Selects component's item. 
You can go to https://vuetifyjs.com/components/dialogs and play on #Simple Dialogs

### Expected Behavior
clicking a mouse button and releasing it within an element (like v-btn or select menu item) should fire a corresponding method.

### Actual Behavior
sometimes releasing a click within a button or Selects item don't trigger any action. It's easier to notice if you move the cursor within a button or Selects component. Haven't tested this behaviour on other elements yet.

### Reproduction Link
Use "OPEN DIALOG 2" button on #Simple dialogs page [https://vuetifyjs.com/components/dialogs](https://vuetifyjs.com/components/dialogs)

### Other comments
I have noticed some inconsistency when clicking on buttons or selecting items in my project.
Sometimes I need to click twice or 3 times to trigger relevant action. Then I started investigating and noticed the same inconsistency on the official vuetifyjs.com page. 

![2017-11-02 18_01_58](https://user-images.githubusercontent.com/2119455/32342312-f1e80d04-bff7-11e7-95de-ff02c48cb7c4.gif)

You can that the 1st click doesn't trigger anything. 
Then 2 following clicks on "OPEN DIALOG BUTTON" open that dialog successfully. 
Next 7 clicks don't trigger opening a dialog box. 
Then clicking on "State 1" item in Selects component also doesn't make it as selected. The 2nd click on that item selects it properly. 

Better quality video is here: https://cl.ly/1I310c0e2w0j

I understand that clicking within an element (like button) and then releasing the click outside that element will cancel the action. However it's not the case here I click and release within the same area. **I am also not sure whether moving a cursor is the reason of this behaviour.** 

**Note:** I cannot reproduce this on Safari.

**Comment by stoked74** [comment]
@Patsky are you using the Magnet app on your mac? If I'm remembering correctly I noticed this issue awhile back and it drove me crazy until I found out that it was being caused by an issue between Magnet and Chrome. If you are using Magnet and you disable it the issue should go away. I'm also pretty sure there's a bug filed with Chrome regarding this exact issue.

**Comment by Patsky** [comment]
@stoked74 Unbelievable! You are right! I'm using the Magnet app! (and the issue was driving me crazy too!)
I have just disabled the Magnet app and all is working like a charm! 

Thank you very much @stoked74 👍 you have just saved me a lot of time trying to debug it. I really appreciate it. 👍

**Comment by yalmasri** [comment]
I have the same problem, buttons does not respond on safari and I don't use magnet app.
can we reopen this issue?
Vuejs: 2.5.2
vuetify: 1.5.5

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
