### ISSUE TITLE
[Bug Report] Baseline Example Layout - v-navigation-drawer overlaps content when width < medium/1264px

### ISSUE THREAD

**Issue by g8rdev** [vuetifyjs/vuetify#2408]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.4.4
Browsers: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
OS: Windows, Mac OSX

### Steps to reproduce
Browse to vuetify URL https://vuetifyjs.com/examples/layouts/baseline
Size browser width < 1264px.  Open/close navigation drawer.

### Expected Behavior
Content should be resized when navigation drawer is opened/closed,

### Actual Behavior
Navigation drawer overlaps content.

### Reproduction Link
[https://codepen.com/USE-VUETIFY-BASELINE-EXAMPLE-SEE-STEPS](https://codepen.com/USE-VUETIFY-EXAMPLE-SEE-STEPS)

### Other comments
This is nearly identical to Issue #2348, which was for the Google Contacts layout.

 
**Width 1263px: nav drawer overlaps**   
![vuetify-baseline-1263w-overlaps](https://user-images.githubusercontent.com/29379683/32353797-516eb39a-bffd-11e7-8742-8b03f3218edd.png)

**Width 1264px: nav drawer resizes content**
![vuetify-baseline-1264w-resizes](https://user-images.githubusercontent.com/29379683/32353821-6a060390-bffd-11e7-98b4-bf8388af55b0.png)

**Comment by g8rdev** [comment]
Note: my "Reproduction Link" is not needed.  Use the Vuetify "Baseline" example layout here:

[https://vuetifyjs.com/examples/layouts/baseline](https://vuetifyjs.com/examples/layouts/baseline)

**Comment by johnleider** [comment]
The google contacts issue was a little different. It was in regards to not actually resizing at all. What you have displayed is the expected behavior. When it goes into the mobile-break-point, its changes the `v-navigation-drawer` to be temporary, thus overlaying the content.

If this solves your issue, please close the ticket. Otherwise, please further clarify what you mean, thank you.

**Comment by g8rdev** [comment]
I see now, thank you for the explanation.  Closing the ticket.  Keep up the amazing work with Vuetify!
