### ISSUE TITLE
[Bug Report] External pagination sync with search - Data Table

### ISSUE THREAD

**Issue by raharida** [vuetifyjs/vuetify#2409]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.4.4
Browsers: Google Chrome
OS: Mac OSX

### Steps to reproduce
There seems to be an issue with external pagination with search prop
whenever external pagination is used the number of pages is not modified based on search result
Lets say that total items is 10 so there are two pages in pagination since page size is 5
when you do a search and data items now display is just one, there is still a pagination showing page two.

### Expected Behavior
Number of pages in the pagination should match the search result count

### Actual Behavior
Number of pages in the pagination should matches the original size of the items.

### Reproduction Link
[https://codepen.io/anon/pen/MOKWXd?&editors=101](https://codepen.io/anon/pen/MOKWXd?&editors=101)

**Comment by pSchaub** [comment]
Same issue here; I think this would be a good enhancement

**Comment by nekosaur** [comment]
You need to use `this.pagination.totalItems` instead of `this.items.length`. The data table does not modify the original input array.

https://codepen.io/anon/pen/ZvpEbw?editors=1010
