### ISSUE TITLE
[Bug Report] Vertical steppers  FADE OUT transition between stepper-items not working sometimes

### ISSUE THREAD

**Issue by iam-raihan** [vuetifyjs/vuetify#2410]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.4.2
Browsers: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36, Google Chrome
OS: Windows

### Steps to reproduce
1. Visit [Steppers Doc](https://vuetifyjs.com/components/steppers/#example-6)
2. Click CONTINUE 5-10 times

### Expected Behavior
while using Vertical steppers, FADE OUT transition on last stepper item between stepper-items should work properly every time.

### Actual Behavior
You'll see FADE OUT transition between stepper-items not working at least twice or thrice or may be more times. It occurs randomly.

### Reproduction Link
[https://codepen.io/iamraihan96/pen/pdgxJE](https://codepen.io/iamraihan96/pen/pdgxJE)

**Comment by johnleider** [comment]
I discovered this recently, it has to be a race condition somewhere as its reproduction is spotty at best.

**Comment by johnleider** [comment]
As of current DEV, this is no longer reproducible. Will review again once 0.17 releases.

**Comment by KaelWD** [comment]
I'm still seeing this on current docs

**Comment by peluprvi** [comment]
This gif can be used for the transition reference: https://github.com/vuetifyjs/vuetify/issues/2338#issuecomment-348283282
