### ISSUE TITLE
[Bug Report] fill-height doesn't work properly on beta.1

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#2412]
### Versions and Environment
Vuetify: v0.17.0-beta.1
Vue: v2.5.2
Browsers: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
OS: Windows

### Steps to reproduce
See Codepen.

### Expected Behavior
The card should be centered and vertically aligned.

### Actual Behavior
The card is centered and top aligned.

### Reproduction Link
Stable: [https://codepen.io/dEradicated/pen/oobrMx](https://codepen.io/dEradicated/pen/oobrMx)
Beta: [https://codepen.io/dEradicated/pen/xPZomG](https://codepen.io/dEradicated/pen/xPZomG)

**Comment by KaelWD** [comment]
Already fixed on dev: 7203c7d41a03de2078e8a094cfbf7c57055232c6 and 1825d2ac7a7593bafc9d198b3fd5ac6dbbc92e4f
