### ISSUE TITLE
[Bug Report] Permanent floating v-navigation-drawer does not float

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#2413]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
OS: Windows

### Steps to reproduce
Create v-navigation-drawer with permanent and floating props
or look at the example from https://vuetifyjs.com/components/navigation-drawers

### Expected Behavior
v-navigation-drawer floats

### Actual Behavior
v-navigation-drawer is always fixed

### Reproduction Link
[https://codepen.io/anon/pen/jaqEXO](https://codepen.io/anon/pen/jaqEXO)

### Other comments
I think position: fixed needs to be changed from 
.navigation-drawer
 to something like
.navigation-drawer:not(.navigation-drawer--floating)

**Comment by KaelWD** [comment]
> A floating drawer has no visible container (no border-right)

Looks fine to me. If you're talking about **positioning**, you're probably looking for the `absolute` prop.
