### ISSUE TITLE
[Bug Report] Invalid character count documentation

### ISSUE THREAD

**Issue by Craz1k0ek** [vuetifyjs/vuetify#2415]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.3
Browsers: Apple Safari
OS: iOS

### Steps to reproduce
Take a look at documentation #9 here https://vuetifyjs.com/components/text-fields

The documentatio says: 
`:rules="[(v) => v.length <= 25 || 'Max 25 characters']"`

When inserted into file, it produces an error:
`[Vue warn]: Error in mounted hook: "TypeError: null is not an object (evaluating 'v.length')"`

### Expected Behavior
Documentation to be clearer about this i.e.: 
The value should be predefined in the data 
OR 
allowing the check to happen on the <v-text-field> value.

### Actual Behavior
Console error, other than that, works as intended.

### Reproduction Link
[https://codepen.io/anon/pen/YEqGPV](https://codepen.io/anon/pen/YEqGPV)

### Other comments
Has been checked at Discord by johnleider

**Comment by johnleider** [comment]
This has been corrected in the new documentation, thank you for the report.
