### ISSUE TITLE
[Bug Report] Integration v-bottom-nav with vue-social-sharing

### ISSUE THREAD

**Issue by menteora** [vuetifyjs/vuetify#2421]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.3
Browsers: Google Chrome
OS: Linux

### Steps to reproduce
I've 2 component in my sample:
1) ButtomNavVuetify - with vue-social-sharing & v-bottom-nav with :active.sync="e2" like vuetifyjs.com sample that should change colour of Nav when clicked.
2) ButtomNavSocial - with vue-social-sharing & v-bottom-nav with static "active" option

### Expected Behavior
I try to integrate these vue-social-sharing & v-bottom-nav component:
1) In the ButtomNavVuetify i try to change the Nav colour when email is clicked. 
2) In the ButtomNavSocial i try only to change the icon colour.

### Actual Behavior
1) In the ButtomNavVuetify component the Nav does'nt change color, i think i made a mistake when i integrate two component (vue-social-sharing & v-bottom-nav)
2) In the ButtomNavSocial i try only to change the icon colour, this could be my second mistake.

### Reproduction Link
[https://codesandbox.io/s/3yv7q36lq](https://codesandbox.io/s/3yv7q36lq)

### Other comments
There's a general documentation that I can study to integrate 2 different and nested component like this two? 

I'm sorry if there is't a bug, but i want to learn deeply vuetify, I think it's a great framwork.

**Comment by johnleider** [comment]
This is more of a question than a bug. Integrating a custom component into an existing Vuetify component is not something that generally calls for a bug report (unless we specifically say that we support it, such as the v-form validation).

 Please any further questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by menteora** [comment]
Sorry, you're right, I read your guide to add github issue and I get the bug template for this question only because is one of the two more detailed template to explain my problem and I think is useful understand how integrate two different component. 
Thankyou anyway

**Comment by menteora** [comment]
Solved with: `v-footer`
