### ISSUE TITLE
[Feature Request] optimised datepicker for date of birth

### ISSUE THREAD

**Issue by Redani** [vuetifyjs/vuetify#2422]
### New Functionality
It'll be great to have a datepicker that allows the following things:
1- be able to firstly select year, then month and then the dat
2- set a years range, for example [1950-2000]
3- automatically close the datepicker when the user selects the day which is basically the last action

Thanks again for your great work

### Improvements
better UX

### Bugs or Edge Cases it Helps Avoid
better UX

**Comment by jacekkarczmarczyk** [comment]
At the moment it's easy to by setting the `activePicker` after opening the menu/dialog
https://codepen.io/anon/pen/rpYyjy?editors=0010

**Comment by Redani** [comment]
thanks Jacek for your message.
it's almost what i'd like, few points are missing :)
- display a years range, for example starting 1950 to 2000
- automatically close the picker when selecting the day
- when opening the picker while a date is already selected, it'll be better to preselect the date in the picker

Thanks and happy new year :)

**Comment by dmitrij-schmidt** [comment]
ad. 2
There seems to be a way to set allowed dates for the picker, as per 
https://vuetifyjs.com/components/pickers#example-6

Main issue is, that it works only for days select. User is able to select year and month out of the range (making 2 steps out of 3 necessary) just to find out that days are greyed out and disabled.
It would be nice to:
- limit years visible in year picker (or at least disable years that are out of range) 
- disable months that are out of range

**Comment by jacekkarczmarczyk** [comment]
@dmitrij-schmidt Could you please create a new feature request for this?

**Comment by jacekkarczmarczyk** [comment]
@dmitrij-schmidt Could you please create a new feature request for this?

**Comment by dmitrij-schmidt** [comment]
@jacekkarczmarczyk - I thought that this is should be a part of this thread. as per your suggestion, posted new request https://github.com/vuetifyjs/vuetify/issues/2991 

thanks for quick reaction :)

**Comment by jacekkarczmarczyk** [comment]
ad 2. this will be possible with https://github.com/vuetifyjs/vuetify/pull/3029
