### ISSUE TITLE
[Bug Report] List items overflow over bottom navigation

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#2423]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.3.3
Browsers: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
OS: Windows

### Steps to reproduce
Create app with list and bottom navigation. Add many items to list, for list to get higher than screen height.

### Expected Behavior
List items doesn't cover bottom navigation.

### Actual Behavior
List items overflow over bottom navigation.

### Reproduction Link
[https://codepen.io/anon/pen/qVNBed](https://codepen.io/anon/pen/qVNBed)

**Comment by johnleider** [comment]
The `v-bottom-nav` had the **transparent** class. I understand this is what is in the current example, it has already been updated.

https://codepen.io/johnjleider/pen/XzKjMr

**Comment by johnleider** [comment]
@jacekkarczmarczyk informed me that the main issue you were referencing was in regards to something different.

**Comment by joshas** [comment]
Main issue is with layout: I expect bottom navigation to push list view up and not to cover it. Could be that I've set up layout wrong, but I didn't find any example how to do it correctly.

**Comment by johnleider** [comment]
You are correct @joshas, I was looking at the wrong thing. This is a bug.
