### ISSUE TITLE
[Bug Report] "@click.once" on v-btn triggers twice

### ISSUE THREAD

**Issue by mornir** [vuetifyjs/vuetify#2424]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Google Chrome
OS: Windows

### Steps to reproduce
Add the .once modifier to a click listener on a Vuetify button.

### Expected Behavior
Event fires once.

### Actual Behavior
Event fires twice.

### Reproduction Link
[https://codepen.io/mornir0/pen/bYeNVM](https://codepen.io/mornir0/pen/bYeNVM)

### Other comments
@click.native.once on v-btn works fine.
@click.once on a normal button tag works as expected.

**Comment by KaelWD** [comment]
This was reverted with #2619, I guess the answer is "use `.native`"
