### ISSUE TITLE
[Bug Report] Dev / Prod Webpack configuration is obscured or missing

### ISSUE THREAD

**Issue by methodbox** [vuetifyjs/vuetify#2425]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.3
Browsers: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
OS: Mac OSX

### Steps to reproduce
This is being reported as a bug because it is required functionality for many dev environments that is already included in vue-cli and has either been removed or obscured in Vuetify.

### Expected Behavior
The default webpack config would be included in the project root folder ./config and include both a dev.env.js and prod.env.js for configuration of dev and prod environments, respectively, for webpack settings.

### Actual Behavior
The entire ./config folder is missing. The location of certain webpack configuration is obscured from the end user (exa. --port isn't allowed when running 'npm run dev' and the port configuration doesn't appear to be able to be overridden in the webpack.config.js) and can't be overridden properly.

### Reproduction Link
[https://codepen.io/nathanlisch/pen/xGrwQP](https://codepen.io/nathanlisch/pen/xGrwQP)

### Other comments
This is a stupid approach. It makes no sense to take Vue's default configuration and obscure it to this extent. Add what you bring to the table; don't bastardize the existing vue-cli.

Due to this stupid configuration I will not be using your library.

**Comment by johnleider** [comment]
I wish I could offer something, but I have absolutely no idea what you are talking about. Are you referring to the Vuetify package itself or one of its templates?

**Comment by jacekkarczmarczyk** [comment]
If you want to use advanced features of webpack you need to use https://github.com/vuetifyjs/webpack-advanced
Vuetify's `webpack` template is forked from https://github.com/vuejs-templates/webpack-simple/tree/master/template
