### ISSUE TITLE
[Feature Request] VDataTable: Make Footer Label Text "1-5 of 10" configurable

### ISSUE THREAD

**Issue by adriansuter** [vuetifyjs/vuetify#2428]
### New Functionality
For a `v-data-table` we can set currently the `noResultsText` and the `rowsPerPageText`, but there is no such feature for the text in the footer indicating which items we are seeing of the total number of items. There should be an option/prop for that. 

See also `vuetify/es5/components/VDataTable/mixins/foot.js` at `line 86`.

### Improvements
-

### Bugs or Edge Cases it Helps Avoid
This would be really helpful in order to support i18n.

**Comment by KaelWD** [comment]
This already exists with the `pageText` scoped slot. The documentation could probably be improved in that area though.

**Comment by adriansuter** [comment]
Thanks. I haven't seen that.
