### ISSUE TITLE
[Feature Request] Add "infinite scrolling" via touch support

### ISSUE THREAD

**Issue by tutley** [vuetifyjs/vuetify#2429]
### New Functionality
I would like to be able to use the touch support feature to determine when a user is on or near the bottom of a list so that I can fire the "up" action at that point to call an API to return the next N results. So think of  a comment system or a search result, I want to get the next N items when they attempt to continue scrolling, but only if they are near the bottom of the page.

### Improvements
The current workaround is to use the window height to try and determine when the user is near the bottom of the set of results by basically saying "when position = height - X" where X is a number of pixels. But this isn't responsive and changes behavior wildly between different display sizes.

### Bugs or Edge Cases it Helps Avoid
I just think it is a cool feature that would add to the touch support.

**Comment by nekosaur** [comment]
This functionality is outside the scope of the current touch support. I would suggest you take a look at the plugins available here https://github.com/vuejs/awesome-vue#infinite-scroll and here https://github.com/vuejs/awesome-vue#pull-to-refresh.

Do any of those fit your use case?
