### ISSUE TITLE
"[Vue warn]: Unknown custom element:" when running unit tests

### ISSUE THREAD

**Issue by edoecohen** [vuetifyjs/vuetify#243]
I've imported Vuetify in my main.js file:

```javascript
import Vue from 'vue';
import VueResource from 'vue-resource';
import Vuetify from 'vuetify';
import App from './App';
import router from './router';

Vue.use(Vuetify);
Vue.use(VueResource);
```

When I run any Karma unit tests that test components that include Vuetify elements in their templates I get the following errors:

![image](https://cloud.githubusercontent.com/assets/952779/24175355/f6e04b0c-0e52-11e7-8363-22fa5427e257.png)

The test itself actually passes, I would just like to clean this up.

Any ideas? Is there another way to register Vuetify components for testing purposes?
Thanks!

**Comment by johnleider** [comment]
It looks like vuetify is not being registered in your tests. Those are all valid components.

**Comment by edoecohen** [comment]
Solved!
Correct, Vuetify was not getting registered. So I added:

```javascript
import Vuetify from 'vuetify';
Vue.use(Vuetify);
```

in the test file itself but that still caused issues. Then I

**Comment by albizures** [comment]
for me, I had to add this in my setup file
```diff
const hooks = require('require-extension-hooks')
const Vue = require('vue')
const Vuetify = require('vuetify')

require('browser-env')()
Vue.config.productionTip = false
+Vue.use(Vuetify)

hooks('vue').plugin('vue').push()
hooks(['vue', 'js']).plugin('babel').push()

+window.Vue = Vue

```

**Comment by john-espina** [comment]
Thanks! This helped me solved similar issue!

**Comment by HarinderKaur11** [comment]
For me, this solved the issue:

In the test file:
`import Vuetify from 'vuetify'

const localVue = createLocalVue();
localVue.use(Vuetify)`

**Comment by HarinderKaur11** [comment]
Thanks for the above solutions. That helped.

I got the same issue with Vue Test Utils with Jest test runner. Adding this to the test file fixes it:

`import Vuetify from 'vuetify'`
`const localVue = createLocalVue()`
`localVue.use(Vuetify)`

Hope this helps others! Thanks :)
