### ISSUE TITLE
break the vertical aligned

### ISSUE THREAD

**Issue by nueko** [vuetifyjs/vuetify#2432]
### Versions and Environment
**Vuetify:** 0.17.0-beta.2
**Vue:** 2.5.3
**Browsers:** Opera 48.0.2685.52
**OS:** Windows 10

### Steps to reproduce
add fill-height to v-container

### Expected Behavior
vertical center aligned

### Actual Behavior
top aligned

### Reproduction Link
[https://mjjow19pwj.codesandbox.io/](https://mjjow19pwj.codesandbox.io/)
https://codesandbox.io/s/mjjow19pwj

**Comment by KaelWD** [comment]
1. You need a `v-content` tag
2. You need to tell the layout that you want it to be centered

```html
<v-app>
  <v-content>
    <v-container fill-height>
      <v-layout wrap align-center>
        <v-flex md4>...</v-flex>
        <v-flex md8>...</v-flex>
      </v-layout>
    </v-container>
  </v-content>
</v-app>
```
