### ISSUE TITLE
[Bug Report] close permanent navigation-drawer

### ISSUE THREAD

**Issue by derwish-pro** [vuetifyjs/vuetify#2435]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.2
**Browsers:** Chrome 62.0.3202.75
**OS:** Windows 10

### Steps to reproduce
` <v-navigation-drawer  v-model="drawer" permanent   clipped  app>`

### Expected Behavior
Switching the drawer variable should close the panel.

### Actual Behavior
Does not respond to the value of the variable.

### Reproduction Link
[https://codepen.io/derwish-pro/pen/YEGdxW](https://codepen.io/derwish-pro/pen/YEGdxW)

### Other comments
I need the sidebar to open/close by pressing the button, and the rest of the content is moved to the side (not covered by the panel). The panel should remain open until the button is pressed.

**Comment by KaelWD** [comment]
That's what [the MD spec](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior) says:

> Permanent navigation drawers are always visible and pinned to the left edge, at the same elevation as the content or background. They cannot be closed.

**Comment by derwish-pro** [comment]
The persistent sidebar does not shift the content, but overlaps it. How do I make it so that the panel has moved the content to the right?

**Comment by KaelWD** [comment]
`app` prop

**Comment by derwish-pro** [comment]
It is not working. Check https://codepen.io/derwish-pro/pen/YEGdxW

**Comment by nekosaur** [comment]
It _is_ working in that codepen? The toggle button is displaced when drawer opens.

**Comment by KaelWD** [comment]
@derwish-pro Do you have a narrow screen? There is currently a bug with that which will be fixed by #2430

**Comment by derwish-pro** [comment]
Yes, I noticed that it works when I set 80% scale in the browser. In normal mode, it does not work. How can I reduce the threshold at which it starts to work? I want it to work up to 400px width.

**Comment by derwish-pro** [comment]
Do I need to add feature request for this?

**Comment by henripal** [comment]
Not sure this should be closed? I have a wide screen and the codepen only works when my zoom level is set to 80% as well.
