### ISSUE TITLE
[Bug Report] v-btn as anchor has wrong text color

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#2437]
### Versions and Environment
**Vuetify:** 0.17.0-beta.2
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 10

### Steps to reproduce
Create a `v-btn` component with an anchor tag

### Expected Behavior
Text color to be white

### Actual Behavior
Text color is blue

### Reproduction Link
[https://codepen.io/jayblanchard/pen/LORaoo?&editors=100](https://codepen.io/jayblanchard/pen/LORaoo?&editors=100)

**Comment by KaelWD** [comment]
This can be fixed by changing `.application.theme--light a` to `.theme--light a`, but I don't know if that will break anything else.
