### ISSUE TITLE
[Feature Request] VDataTable: hide rowsPerPage select, if only one option is provided

### ISSUE THREAD

**Issue by backbone87** [vuetifyjs/vuetify#2438]
### New Functionality
Hide the rowsPerPage select, by not rendering it, if only a 1-item array is provided via `rowsPerPageItems` prop

### Improvements
No custom styling needed

### Bugs or Edge Cases it Helps Avoid
Removes UI clutter, if the feature of adjusting page size isnt used or desired

**Comment by nekosaur** [comment]
This can easily be achieved with the `hide-actions` prop.

https://codepen.io/anon/pen/MObpVz

**Comment by backbone87** [comment]
hide-actions also skips the pagination, which isnt what this feature request was about

**Comment by nekosaur** [comment]
Pagination is just as superfluous as rows per page when there's only one item in the array.

If you want to hide only rows per page, apply a custom css class to data table when array is only one item that sets rows per page element to `display: none`.

**Comment by jacekkarczmarczyk** [comment]
He meant only one item in `rows-per-page-items` array, not items array, and i think it's not a bad idea to hide rows per page in this case

**Comment by nekosaur** [comment]
Oh. I guess I totally misunderstood the whole thing then :D

**Comment by backbone87** [comment]
tyvm

**Comment by ducptit** [comment]
rows-per-page-text=""
:rows-per-page-items="[]"

**Comment by blak3r** [comment]
Not a big deal, but this error is showing up in the console.
`[Vuetify] The prop 'rows-per-page-items' can not be empty in "v-data-table"`

**Comment by johnleider** [comment]
Please do not post on old closed issues.
