### ISSUE TITLE
[btn-toggle multiple] Last 2nd selected button have no border-right

### ISSUE THREAD

**Issue by zcyzcy88** [vuetifyjs/vuetify#244]
https://vuetifyjs.com/components/buttons

Select all button:
<img width="350" alt="2017-03-22 18_06_21-button component _ vuetify js" src="https://cloud.githubusercontent.com/assets/15178410/24192715/d6a82d68-0f2a-11e7-8335-a11de6a14cdc.png">

https://github.com/vuetifyjs/vuetify/blob/9c8e2d14e2732d8b2aec5113209feab0d944fcf6/src/stylus/components/_button-toggle.styl#L25

**Comment by cawa-93** [comment]
+1
