### ISSUE TITLE
[Bug Report] Clearable doesn't reset progress bar in v-text-field

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#2441]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.2
**Browsers:** Chrome 60.0.3112.113
**OS:** Mac OS 10.12.4

### Steps to reproduce
Create a text field with a progress bar and attribute clearable.

### Expected Behavior
When clearing the text field I expect the progress bar length to go to zero. 

### Actual Behavior
The progress bar does not go immediately to zero. Instead, when a user starts to type again, then it goes to zero.

### Reproduction Link
[https://codepen.io/anon/pen/NwbqxE?editors=1010](https://codepen.io/anon/pen/NwbqxE?editors=1010)

### Other comments
Guessing there's some reactivity bug.

**Comment by KaelWD** [comment]
That codepen doesn't work.

**Comment by EvanZ** [comment]
@KaelWD It works for me. Are you saying when you type something you don't see a progress bar?

**Comment by nekosaur** [comment]
It's because input value is set to null when clearing it. You need to check for that in your computed.

See https://codepen.io/anon/pen/JObmPY?editors=1010
