### ISSUE TITLE
[Bug Report] Autocomplete v-select has poor scrolling performance while searching

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#2442]
### Versions and Environment
**Vuetify:** 0.17.0-beta.2
**Vue:** 2.5.3

I'm not following the rules because I'm a bad boy, and I'll fix this myself anyway so who cares. 

### Steps to reproduce
 - Search a large set of items (25000 in this case) for something that won't have too many results (999 works)
 - Scroll around in the bottom 200px of the menu

### Reproduction Link
[https://codepen.io/anon/pen/yPVaQG?editors=1010](https://codepen.io/anon/pen/yPVaQG?editors=1010)

**Comment by KaelWD** [comment]
I'm bumping this to 1.1, it's low priority and will require some fairly large changes.

**Comment by KaelWD** [comment]
Nothing really actionable on this, the list is now shown all at once so there's no scroll listener messing shit up.

**Comment by KaelWD** [comment]
Turns out that was a mistake, will need to revisit this.

**Comment by johnleider** [comment]
We've added back the fake virtualization when scrolling and improved other areas to make this work as expected.
