### ISSUE TITLE
[Feature Request] Add an option to v-select to manually trigger the dropdown menu

### ISSUE THREAD

**Issue by HugoCrd** [vuetifyjs/vuetify#2443]
### New Functionality
I'm using a `v-select` with `autocomplete`. This component works great, and almost answers our use-case :)
Almost, because right now it shows the dropdown menu on **input focus**.
In my use case, I want to only show this when a user starts **entering text in the input**.

### Improvements
The current workaround is to use `max-height` and set it to `0` when nothing was entered on `search-input` but I find it quite hacky.
Adding an option like `trigger` would allow us to do that in a better way.

### Bugs or Edge Cases it Helps Avoid
That would prevent users to add hacks on top of this element.

If you think this would fit in Vuetify, I could help adding it and provide a PR.

Thanks for your work, it's an amazing framework you have there!

**Comment by HugoCrd** [comment]
This would be a really good enhancement.
My workaround does not remove the shadow, making it not perfect to my eyes ;)

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/534015/32845376-d98f7670-ca24-11e7-981a-9ce122d2742c.png">

Once again: I'd be happy to work on it if you think that makes sense (or if you can think of a better solution to achieve the same).

Cheers

**Comment by johnleider** [comment]
This is currently how this behaves.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
