### ISSUE TITLE
[Feature Request] v-badge can not set size and adjust overlap position.

### ISSUE THREAD

**Issue by playersun** [vuetifyjs/vuetify#2444]
### New Functionality
The default badge is too large.

### Improvements
Is any way to resize badge and adjust overlap position?
`<v-btn icon>
    <v-badge overlap color="red">
      <span slot="badge">6</span>
      <v-icon color="grey lighten-1">notifications</v-icon>
    </v-badge>
  </v-btn>`
I adjusted in chrome developer tools by styles, and which html tag can i add style about above code.

### Bugs or Edge Cases it Helps Avoid
Hope the v-badge like apple IOS badge size.

**Comment by nekosaur** [comment]
This reads more like a question than a feature request. If you need help with this, please come by [chat](https://chat.vuetifyjs.com) instead.

**Comment by fontenele** [comment]
@playersun 
my solution:
```
<v-badge overlap top color="red">
    <span slot="badge">6</span>
    <v-avatar size="40" color="teal">
        <v-btn flat dark fab icon>
            <v-icon>notifications</v-icon>
        </v-btn>
    </v-avatar>
</v-badge>
```
