### ISSUE TITLE
[Bug Report] Snackbar z-index is has low value

### ISSUE THREAD

**Issue by mzahradnicek** [vuetifyjs/vuetify#2449]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.2
**Browsers:** Chrome 60.0.3112.90
**OS:** Linux x86_64

### Steps to reproduce
Try to open modal dialog, and than invoke snackbar.

### Expected Behavior
Snackbar should be above modal dialog. This component is intended for notification, so it should be on top of all.

### Actual Behavior
Snackbar is hidden under modal dialog. You cant interact with it - eg. cant click close button, etc...

### Reproduction Link
[https://codepen.io/anon/pen/rYWgGa](https://codepen.io/anon/pen/rYWgGa)

**Comment by KaelWD** [comment]
Turns out [this cssnano rule](http://cssnano.co/optimisations/zindex/) was resetting all the z-index declarations to be as low as possible.
