### ISSUE TITLE
[Bug Report] Month Picker Bug 

### ISSUE THREAD

**Issue by ilovejlj** [vuetifyjs/vuetify#2451]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.2
**Browsers:** Chrome 61.0.3163.100
**OS:** Mac OS 10.12.4

### Steps to reproduce
https://vuetifyjs.com/components/pickers #9 Month pickers - In dialog and menu

### Expected Behavior
When Month Picker is shown, should show months as: Jan, Feb, ... if Jan is selected, should show 2011-01 in text field

### Actual Behavior
Months are shown as: Dec, Jan, ... when Jan is selected, text field will show value 2011-02

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
You didn't save the codepen.
Please also check first with vuetify 0.17.0-beta.2 https://codepen.io/anon/pen/GOroxq?&editors=101

**Comment by ilovejlj** [comment]
@jacekkarczmarczyk

**Comment by ilovejlj** [comment]
@jacekkarczmarczyk 

The codepen is the one on vuetifyjs.com, anyway since 0.17.0-beta.2 looks fine, I will go use this version :)

thx
