### ISSUE TITLE
[Feature Request] Stepper custom step label

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#2452]
### New Functionality
Allow you to override the label currently set by the 'step' property (limited to first 2 characters).

### Improvements
there currently is no workaround that i know of. 

### Bugs or Edge Cases it Helps Avoid
this would allow you to dynamically customize the label of the step without sacrificing the order
the step could still be numerical (1,2,3) but the labels will not need to be so.

**Comment by johnleider** [comment]
Stepper is being scrubbed from updates until 2.0 due to issues with backwards compatibility.

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
