### ISSUE TITLE
[Bug Report] VStepper Step final step content doesnt get hidden

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#2454]
### Versions and Environment
**Vuetify:** 0.17.0-beta.2
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 7

### Steps to reproduce
This bug occurs when more than one v-stepper is in use. even though they are not nested.

It may be that it occurs when a stepper is no longer rendered?

From the reproduction link follow these steps:
Click next to go to step 2.
Select 3 or more in step 2 then click next.
Follow through the sub steps till you get to step 4.
Go back to step 2, click next

### Expected Behavior
All sub-steps content in step 3 except for the first one should be hidden.

### Actual Behavior
The last step content isn't hidden, so two are displayed at the same time.

### Reproduction Link
[https://codepen.io/anon/pen/gXgpEd](https://codepen.io/anon/pen/gXgpEd)

### Other comments
This isn't a breaking bug. May apply if vertical stepper is hidden

**Comment by johnleider** [comment]
All `v-stepper` updates are being moved to v2.0 due to backwards compatibility issues.

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
