### ISSUE TITLE
Vuetify problem problem with rendering in IE InternetExplorer 11 

### ISSUE THREAD

**Issue by jakub-wisniewski** [vuetifyjs/vuetify#2456]
I am trying to run vuetify app on Windows 10 and _IE 11_.

After render I got errors in console:

**[Vue warn]: Error in render function: "TypeError: Object does not supports property or method "includes.**

I've included polyfil in index.html:
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>

**Comment by mornir** [comment]
Try this polyfill:
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Array.prototype.includes"></script>

If you need more help, come over to the discord channel.

**Comment by jacekkarczmarczyk** [comment]
Quoting the issue template:

IMPORTANT: Please use the following link to create a new issue:

  https://issues.vuetifyjs.com

If your issue was not created using the app above, it will be closed immediately.

**Comment by jakub-wisniewski** [comment]
Mornir, I included this in html file before, but it didn't help. However I installed babel-polyfil via npm and now it works.
