### ISSUE TITLE
[Bug Report] VTextField gets rendered as `<!---->` in unit test

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#2458]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 10

### Steps to reproduce
npm install

npm run unit

Look at the console.log output which is `<!---->`

### Expected Behavior
Rendered VTextField component which is something like this
`div > div.input-group__input`

### Actual Behavior
`<!---->`

### Reproduction Link
[https://github.com/JeremyWalters/vuetify-text-field-not-working](https://github.com/JeremyWalters/vuetify-text-field-not-working)

### Other comments
All other components I tested gets rendered fine in the unit tests.

**Comment by nekosaur** [comment]
You forgot to include the actual error message.

```
[Vue warn]: Error in render: "TypeError: undefined is not a function (evaluating '['time', 'date', 'datetime-local', 'week', 'month'].includes(this.type)')"
```

This indicates that it can't find the includes function. I was able to fix it by installing `babel-polyfill` and modyfing the files section of `karma.conf.js` to look like this

```
files: [
  '../../node_modules/babel-polyfill/dist/polyfill.js',
  './index.js'
],
```

**Comment by JeremyWalters** [comment]
@nekosaur Thanks for your time, solving my issue. 

Should `babel-polyfill` not be part of the packages for the start?

**Comment by nekosaur** [comment]
Which template did you use?

**Comment by JeremyWalters** [comment]
I used the Webpack template. Ah Webpack template probably doesn't have it by default.

`vue init webpack`
