### ISSUE TITLE
[Bug Report] v-parallax transform: translate3d() is off until first scroll event after route change.

### ISSUE THREAD

**Issue by Coletrane** [vuetifyjs/vuetify#2464]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Mac OS 10.13.1

### Steps to reproduce
Go to http://bikeva.com click on 'Results' at the top, click on the logo image at the top toolbar to navigate back to the base route. Do not scroll when you are back at the base route.

### Expected Behavior
The image has the correct translate property and shows up before a scroll event is fired.

### Actual Behavior
You will see the v-parallax image is translated to where it is out of the viewport, and fixes itself when you scroll. 

### Reproduction Link
[https://github.com/Coletrane/mountain-bike-virginia/blob/master/components/MTBVAHeader.vue](https://github.com/Coletrane/mountain-bike-virginia/blob/master/components/MTBVAHeader.vue)

### Other comments
I thought this may be an issue with the Vue router resetting the scroll, so I disabled that (before switching to Nuxt) but no dice. I've tried `created() { window.scrollTo(0,1)}` but that did not work either.

**Comment by johnleider** [comment]
Thank you for the report, but you need to provide a reproduction outside of your environment.

**Comment by armaldio** [comment]
Hello, same problem here

**Comment by johnleider** [comment]
Please do not comment on old closed issues @armaldio , if you are still experiencing problems, please create an issue with https://issues.vuetifyjs.com
