### ISSUE TITLE
After close the dialog and scroll the page a javascript error appears in console

### ISSUE THREAD

**Issue by esorribas** [vuetifyjs/vuetify#2467]
How to reproduce:

Click on "open dialog" button,
Close dialog with "close" button

After dialog closes scroll the page and take a look of Chrome's development tools console for this error: "Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

Link:
https://codepen.io/anon/pen/ooZExg

Version of Vue: 2.5.0
Version of Vuetify: 0.16.9

**Comment by KaelWD** [comment]
- You didn't follow the required template for issues, please use https://issues.vuetifyjs.com in the future
 - You are missing the `v-app` component, which you would know if you'd bothered to read any documentation.
