### ISSUE TITLE
[Feature Request] is there a way to use scope at footer slot because when i add scope property the footer disappear

### ISSUE THREAD

**Issue by stanleyleoo** [vuetifyjs/vuetify#2474]
### New Functionality
Use Scope feature at Datatable Footer

### Improvements
i need data from header / item

### Bugs or Edge Cases it Helps Avoid
i dont know if bugs but it can help other people if they wanted to search each specific column in a Datatable

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
