### ISSUE TITLE
Breadcrumbs alignment

### ISSUE THREAD

**Issue by c0h1b4** [vuetifyjs/vuetify#2476]
### New Functionality
I can't change the alignment of v-breadcrumbs from center to left or right

### Improvements
`<v-breadcrumbs class="text-xs-left">` doesn't works.

### Bugs or Edge Cases it Helps Avoid
Better design options.

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

Also this is a flexbox based framework, the class you're looking for is `justify-start`
