### ISSUE TITLE
[Feature Request] Make v-card use v-on:click and cursor: pointer instead of <router-link>

### ISSUE THREAD

**Issue by Coletrane** [vuetifyjs/vuetify#2477]
### New Functionality
Put links in the card's text

### Improvements
I have defined my own v-card component that piggy backs off vuetify's style and implements this here (need to work out some cursor issues): https://github.com/Coletrane/mountain-bike-virginia/blob/nuxt/components/PostCard.vue

### Bugs or Edge Cases it Helps Avoid
I was trying to get server side rendering up and kept getting issues since it was rendering an `<a>` inside of another `<a>` It wasn't immediately obvious that this was what was getting my server and client rendered pages out of sync.

**Comment by KaelWD** [comment]
I don't understand what this is supposed to solve, v-card is already a `div` unless you give it a `href`

**Comment by Coletrane** [comment]
So say I want the whole card to be a link, but I want some of the text to be a link to a different location. This will work with a client rendered app but not with a server rendered one since nested `<a>` tags are invalid markup.

**Comment by KaelWD** [comment]
You can already do this just by using an `@click=""` handler on the card and do your route change in that. Replacing all linked cards with click handlers is bad for SEO so will not be done by the framework itself.

**Comment by lcherone** [comment]
To add to this, for some reason unknown'st to me `@click` didn't work. but native does.

**No work:**

```
<v-card @click="doSomething()">
  ...
</v-card>
```

**Works:**

```
<v-card @click.native="doSomething()">
  ...
</v-card>
```

**Comment by egeersoz** [comment]
I can reproduce @lcherone 's issue. `@click` doesn't work for `v-card` components. Have to use `@click.native`.

**Comment by b3autydata** [comment]
same for me, can anyone check this issue?

**Comment by Decipher** [comment]
@KaelWD Is there a process to re-open this issue?

**Comment by allanchua101** [comment]
I think with all these guys raising the concern, the ticket is definitely worth re-visiting. It feels weird to not have event on cards especially that it's highly used.

**Comment by KaelWD** [comment]
Fixed, but there's at least 12 people here who could have just opened a new issue considering it had nothing to do with the original one.

**Comment by diegotejadav** [comment]
@lcherone [solution](https://github.com/vuetifyjs/vuetify/issues/2477#issuecomment-402751423) worked for me, thank you!
