### ISSUE TITLE
[Bug Report] Tooltip on focusable elements does not close automatically when changing route

### ISSUE THREAD

**Issue by raymadrona** [vuetifyjs/vuetify#2480]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.4.3
**Browsers:** Chrome 62.0.3202.75
**OS:** Windows 10

### Steps to reproduce
Using vue-router, having the `router-view` wrap with `keep-alive`.
Changing of route using elements such as buttons or &lt;a&gt; tags causes this behavior. The tooltip still appear even the `activator` is now hidden.

Check the reproduction link to see it in action.

### Expected Behavior
The tooltip must be hidden after changing route.

### Actual Behavior
The tooltip still visible after changing route.

### Reproduction Link
[https://jsfiddle.net/ott3jgah/4/](https://jsfiddle.net/ott3jgah/4/)

### Other comments
I recommend also to have a functionality of showing tooltip when a focusable elements such buttons, inputs and &lt;a&gt; tags has focus. This feature/functionality will automatically fix this bug.

We can add this code on the tooltip component:

```
focusin: () => {
    this.runDelay('close', () => (this.isActive = true))
},
focusout: () => {
    this.runDelay('close', () => (this.isActive = false))
}
```

**Comment by KaelWD** [comment]
This can probably be done by hiding the tooltip in the `deactivated` lifecycle method.

**Comment by Utwo** [comment]
Same on v-select

**Comment by raymadrona** [comment]
The issue still occurs on mobile.

**Comment by johnleider** [comment]
If you are still encountering issues, please create a new ticket: https://issues.vuetifyjs.com
