### ISSUE TITLE
exact is always false

### ISSUE THREAD

**Issue by atorkhov** [vuetifyjs/vuetify#2484]
I'm using Vue 2.5.2 and when `this.exact` is checked in this line it is always false when it is not specified in template:
https://github.com/vuetifyjs/vuetify/blob/b2b1a4a96bf87d938c415ffbc8197131e67b276f/src/mixins/routable.js#L43

This makes links to `/` to work as non-exact.

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
