### ISSUE TITLE
[Bug Report] Button text in snackbars does not match context text color

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2488]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Firefox 56.0
**OS:** Mac OS 10.10

### Steps to reproduce
Create a "close" button inside the snackbar.

### Expected Behavior
The close button has by default the same text color like the content text.

### Actual Behavior
It is black, while the content text is white.

### Reproduction Link
[https://codepen.io/anon/pen/Vrbdwo](https://codepen.io/anon/pen/Vrbdwo)

### Other comments
Looking at the example from documentation (https://vuetifyjs.com/components/snackbars), example #2 Contextual, it uses `dark` prop to set the color of the button to white. As I understand, one should not be setting `dark` for this purpose, and moreover I do not think it should be even necessary to set it because color should match the content's color.

**Comment by johnleider** [comment]
This is the exact purpose for you to use the **dark** prop. Dark means I am on a dark background. Well, green is a dark background, so in this case you would explicitly define dark.

**Comment by mitar** [comment]
Hm, OK about the dark prop. But shouldn't color still match the content color by default?

**Comment by johnleider** [comment]
It's currently working as intended. If you feel we should add theme support to `v-snackbar`, please open a feature request.
