### ISSUE TITLE
[Bug Report] Output not correctly escaped on v-select elements

### ISSUE THREAD

**Issue by kreischweide** [vuetifyjs/vuetify#2490]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 10

### Steps to reproduce
Go to reproduction link, use the "Select" dropdown and test each element by selecting it.

### Expected Behavior
Output escaping should be consistent. The v-select display should either always show and fill the escaped version or the unescaped one.

### Actual Behavior
Its a mixed bag.

- "test1" is shown equally on the first two elements, but selecting one or the other differs in the value filled into the input.
- "test2" is the same.
- "test3" allows the given value to contain html.
- "test4" finally allows for script execution if the backend is not escaping the content correctly but also shows the correctly escaped content once selected.

### Reproduction Link
[https://codepen.io/kreischweide/pen/yPbwwy](https://codepen.io/kreischweide/pen/yPbwwy)

**Comment by jacekkarczmarczyk** [comment]
Already fixed in https://github.com/vuetifyjs/vuetify/pull/2391
