### ISSUE TITLE
[Bug Report] Broken CSS in version 0.17.0

### ISSUE THREAD

**Issue by frapa** [vuetifyjs/vuetify#2491]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Firefox 56.0
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
Nothing, with the last version 0.17.0 the layout of the app is broken (main is shown below sidebar instead of on the side).

Simply chaning my css to 0.16.9 fixed the issue.

### Expected Behavior
Correct layout.

### Actual Behavior
None

### Reproduction Link
[https://codepen.io/wernerm/pen/LjggoV](https://codepen.io/wernerm/pen/LjggoV)

**Comment by frapa** [comment]
It's also in the CDN.

**Comment by ClaudioEyzaguirre** [comment]
I had the same issue, but I could fix it.

https://codepen.io/anon/pen/dZRRvO

**Comment by nullism** [comment]
I'm having the same issue -- it's also present in the live layout examples: https://vuetifyjs.com/examples/layouts/baseline

**Comment by azaars** [comment]
If you happen to have the toolbar and navigation drawer ordered this way:
```javascript
<v-navigation-drawer></v-navigation-drawer>
<v-toolbar></v-toolbar>
```
would it helps if you switch the order?

**Comment by nullism** [comment]
Well, that doesn't appear to fix the issue present in the official examples, which is that all page content starts below the bottom on the drawer, regardless if the toolbar is even present. It seems to me that the issue with the official examples is the same issue @frapa is reporting, and is specific to the drawers.

For example, the `<>` was centered in 0.16.9, but now it's at the bottom of the page:

https://vuetifyjs.com/examples/layouts/baseline

**Comment by snarlynarwhal** [comment]
I tried going back to 0.16.9 and it still appears all broken. After changing the package version in package.json to `"vuetify": "0.16.9"`, I delete node_modules, ran `npm cache clean`, and then ran npm install. That should have taken care if it, correct?

**Comment by nullism** [comment]
I had to re-webpack as well.

**Comment by snarlynarwhal** [comment]
What do you mean exactly? o.0

**Comment by nullism** [comment]
Sorry for the confusion. Well, if you're not bundling the CSS, you'll need to load the `0.16.9` CSS instead of the unpkg default which is (as of a few hours ago) returning the `0.17.0` version. 

e.g use `https://unpkg.com/vuetify@0.16.9/dist/vuetify.min.css` instead of `https://unpkg.com/vuetify/dist/vuetify.min.css`

**Comment by snarlynarwhal** [comment]
Ahhhh, thank you sooo much!

**Comment by jvillego** [comment]
How can I to repare it my layout?  all your documentation about layout is now wrong.  See your example of predefined layouts (dark)
[https://vuetifyjs.com/examples/layouts/dark](url)

**Comment by jrast** [comment]
@frapa, just apply the changes as described in the release notes.

I fixed your pen: https://codepen.io/jrast/pen/yPXzZq?editors=1010

**Comment by waldandrade** [comment]
The css broke in this style ...

(in vuetify.css)
.list__tile--active {
  color: $list-tile-active-color;
}

Note that it is the unique variable usage in all css file.

**Comment by johnleider** [comment]
This is covered under the breaking changes section of the release notes.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by toblender** [comment]
Have the same issue with the styling for input fields.  The errors were not highlighting and animating.

`    <link href="https://unpkg.com/vuetify@0.16.9/dist/vuetify.min.css" rel="stylesheet">
`
Fixes the problem.

**Comment by piyushSinghalDemo** [comment]
got the same issue with styling
<link href="https://unpkg.com/vuetify@0.16.9/dist/vuetify.min.css" rel="stylesheet">
fixes the problem
