### ISSUE TITLE
[Feature Request] Defining Theme by name

### ISSUE THREAD

**Issue by mwaldstein** [vuetifyjs/vuetify#2492]
### New Functionality
Prior to 0.17, themes could be defined by color name - e.g. 
```
$theme := {
  primary: $blue.darken-4
   ...
}
```

Under the new system, colors must be defined in hex, a more complex, less immediately obvious method which creates a mis-match from the rest of the color system, where there is an encouragement to use named classes to set colors.

### Improvements
Currently, setting theme colors using the pre-defined palette is a multi-step process of picking colors then using a dev tool to identifying the raw hex color. Enabling a method of setting theme by name would avoid the multiple steps and chance of transcription error in the process. 

### Bugs or Edge Cases it Helps Avoid
Because of the multiple steps, there is a risk of color mis-match which may not be completely trivial to track down.

**Comment by johnleider** [comment]
We will be making changes to the color palette docs so that selecting these colors will be easier. As of now, we will not be adding this functionality.  Thank you for your interest.

**Comment by KaelWD** [comment]
See #2567
