### ISSUE TITLE
[Bug Report] V-Content is not working properly with a Permanent Navigation Drawer

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#2493]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.89
**OS:** Mac OS 10.12.6

### Steps to reproduce
Try to resize (reduce the size) the window until it automatically resizes the content

### Expected Behavior
v-content should always have the padding-left equals the size of the navigation drawer if it's defined as permanent.

### Actual Behavior
v-content resizes and hide it's content (lose the padding-left) below the navigation-drawer (set to permanent)

### Reproduction Link
[https://codepen.io/4eveRS/pen/Xzgzbw](https://codepen.io/4eveRS/pen/Xzgzbw)

### Other comments
I think this all this automatically resize option should be optional and defined at the v-app component.

**Comment by johnleider** [comment]
After checking the notes I see that this change did not make the list. This is something that the team discussed recently and we decided to have all drawers be treated the same in regards to mobile. Permanent was causing too many issues and you can now achieve the same behavior by just adding **disable-resize-watcher** to `v-navigation-drawer`.

Sorry for the inconvenience.

**Comment by 4eveRS** [comment]
Sorry, but I think the problem persists even with disable-resize-watcher...

It's not the permanent drawer that I'm worried about, but the v-content content that doesn't retain the padding-left when the window is resized.

**Comment by johnleider** [comment]
Tracking

**Comment by chirag97** [comment]
![image](https://user-images.githubusercontent.com/6772446/32766022-1093f7d8-c933-11e7-8b70-8f015514e813.png)

Why my projects using started behaving in a wrong way. all layout is disturbed and content in main is going outside.
Did anyone made any changes to repo by mistake?

**Comment by KaelWD** [comment]
@chirag97 That isn't related to this issue at all, please create a codepen with reproduction and post it in discord.

**Comment by 4eveRS** [comment]
I think that the change to make the content resize is very welcome in most cases, but I also think that the framework as it self, should embrace all kind of app/websites cases as possible.

So in my opinion, this resize funcionality (toolbar, navbar and v-content) should be setted as a prop in v-app which wraps all the contents.

It can be enabled by default, but also, could be disabled if the app or website doesn't benefit from this functionality.

Something to Vuetify team to analyze and verify the possibility of adding this.

**Comment by KaelWD** [comment]
@4eveRS They won't resize unless they have the `app` prop.
