### ISSUE TITLE
[Bug Report] V-select items could inherit the theming from their V-select instead of V-app theme

### ISSUE THREAD

**Issue by jess8bit** [vuetifyjs/vuetify#2494]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 10

### Steps to reproduce
Have a page with a v-app dark theme, then inside include a v-card > v-form > v-select hierarchy.
Specify the light attribute for v-card and v-select.
Add a few items to the v-select
DropDown the list, the items appear with a dark theme.

### Expected Behavior
One would expect the items to be rendered in the same theming as the v-select input (which is light in this scenario)

### Actual Behavior
It seems the items inherit their theming for an upper container, most likely the v-app, whatever th e v-select theme is.

### Reproduction Link
[https://codepen.io/jess8bit/pen/KymzQB](https://codepen.io/jess8bit/pen/KymzQB)

### Other comments
It could remain like this, as the "default" behavior, but then we could use a new v-select attribute that would allow to override this.
Or it could be changed so that the default behavior is to inherit from v-select, and still have the possibiltiy to override this in some way.

**Comment by johnleider** [comment]
We are exploring other ways to handle this. Currently we leverage css cascading and specificity but it has an obvious breaking point.
