### ISSUE TITLE
[Bug Report] Error in generated css file

### ISSUE THREAD

**Issue by elbarto132** [vuetifyjs/vuetify#2497]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Vivaldi 1.93.955.48
**OS:** Mac OS 10.13.1

### Steps to reproduce
Install the npm package and look at dist/vuetify.min.css or just look at https://unpkg.com/vuetify@0.17.0/dist/vuetify.min.css

### Expected Behavior
.list__tile--active{color:$list-tile-active-color}
should be replaced with a color

### Actual Behavior
.list__tile--active{color:$list-tile-active-color}
is not replaced with a color, but the variable name is put in the css code

### Reproduction Link
[https://github.com/vuetifyjs/vuetify](https://github.com/vuetifyjs/vuetify)

### Other comments
Webpack throws an error and won't compile

**Comment by KaelWD** [comment]
This variable was removed in c52bf1f448dda10e6fee9f9cbaaabb58b8fde187 but references to it weren't checked. I'm not sure if it's still needed for anything else.
