### ISSUE TITLE
[Bug Report] v-text-field with focus does not reflect v-model changes

### ISSUE THREAD

**Issue by ybycode** [vuetifyjs/vuetify#2498]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Firefox 56.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1 - enter some value in the text field,
2 - hit Enter.

### Expected Behavior
The v-text-field should be reset.

### Actual Behavior
The v-text-field is not reset, and does not reflect the value bound to it's v-model.

### Reproduction Link
[https://jsfiddle.net/e7z05hop/](https://jsfiddle.net/e7z05hop/)

### Other comments

The click event on the 'reset' button is bound to the same reset method, and works as expected, indicating that this might be related to the focus.

This behavior appeared with the version 15.6 apparently.

**Comment by KaelWD** [comment]
This is new in 0.17, it's caused by @azaars's mask changes.
