### ISSUE TITLE
No heading style

### ISSUE THREAD

**Issue by Zeph33** [vuetifyjs/vuetify#2499]
No heading style :
[https://codepen.io/zeph33/pen/JOJxEe](https://codepen.io/zeph33/pen/JOJxEe)
Vuetify doc on typography not use tag h1, h2 ... use display-x in div !!!
https://vuetifyjs.com/style/typography

1 november 2017 commit : Enhancement/theme part 2  remove
``` STYLUS
for heading, options in $headings
  ...
```
on file src/stylus/elements/_headings.styl

[https://github.com/vuetifyjs/vuetify/commit/7f98f838b2c0d3e21ad4cbf0da8ea22e8709c76b#diff-ba5ea9e2c80c40d43ee43c2f2c5272ac](https://github.com/vuetifyjs/vuetify/commit/7f98f838b2c0d3e21ad4cbf0da8ea22e8709c76b#diff-ba5ea9e2c80c40d43ee43c2f2c5272ac)

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
