### ISSUE TITLE
[Bug Report] No heading style

### ISSUE THREAD

**Issue by Zeph33** [vuetifyjs/vuetify#2500]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** All
**OS:** All

### Steps to reproduce
No heading style Use h1, h2, ...

### Expected Behavior
Define style, ok on V0.17.0-beta1 see comment

### Actual Behavior
No style !!

### Reproduction Link
[https://codepen.io/zeph33/pen/JOJxEe](https://codepen.io/zeph33/pen/JOJxEe)

### Other comments
Vuetify doc on typography not use tag h1, h2 ... use only display-x in div !!!
https://vuetifyjs.com/style/typography

1 november 2017 commit : Enhancement/theme part 2  remove
``` STYLUS
for heading, options in $headings
  ...
```
on file src/stylus/elements/_headings.styl

[https://github.com/vuetifyjs/vuetify/commit/7f98f838b2c0d3e21ad4cbf0da8ea22e8709c76b#diff-ba5ea9e2c80c40d43ee43c2f2c5272ac](https://github.com/vuetifyjs/vuetify/commit/7f98f838b2c0d3e21ad4cbf0da8ea22e8709c76b#diff-ba5ea9e2c80c40d43ee43c2f2c5272ac)

**Comment by KaelWD** [comment]
This is intended behaviour and is not a bug. See #2085 for the discussion.

**Comment by Zeph33** [comment]
It does not make sense for "Material Component Framework"
Vuetify css can be encapsulated with stylus import
``` stylus
.vuetify
  @import '../node_modules/vuetify/src/stylus/main'
```
The people don't want default style from the Framework override by include file style after vuetify.
And do not provide an incomplete framework or change title is not Framework is SDK !!!

**Comment by Zeph33** [comment]
If this is intended behaviour and is not a bug.
Why this file [https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/generic/_reset.styl](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/generic/_reset.styl)
Create two css files vuetifyreset.css with all reset style include heading :) and vuetify.css without _reset.styl
If user want all in one file create stylus with :
``` stylus
@import '../node_modules/vuetify/src/generic/_reset'
@import '../node_modules/vuetify/src/stylus/main'
```
Or generate multiple css from framework 
vuetify_full.css
vuetify_reset.css
vuetify.css
...
