### ISSUE TITLE
[Bug Report] v-edit-dialog does not work with multi-line v-text-field

### ISSUE THREAD

**Issue by ulfmaier** [vuetifyjs/vuetify#2506]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Linux, Windows, Android, iOS, Mac OSX

### Steps to reproduce
open the edit dialog and try to enter something with multiple lines

### Expected Behavior
return key results in new line

### Actual Behavior
return key triggers save

### Reproduction Link
[https://codepen.io/anon/pen/zPzVGQ](https://codepen.io/anon/pen/zPzVGQ)

### Other comments
v-edit-dialog captures the return key on keydown. The edit dialog should ignore the return key if the inner text-field uses the multi-line option.

**Comment by johnleider** [comment]
I actually went back on this one and verified that this has been present since v0.13.0, crazy!
