### ISSUE TITLE
[Bug Report] Wrong toggle button behavior when I reset the buttons it contains

### ISSUE THREAD

**Issue by Seraf** [vuetifyjs/vuetify#2509]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chromium 62.0.3202.75
**OS:** Ubuntu undefined

### Steps to reproduce
On the codepen, click on the "BOUM" button, and try to select a button in the toggle button bar

### Expected Behavior
The toggle button bar should be completely reset and work with the new set.
It looks like the listeners aren't reactive

### Actual Behavior
I'm resetting all my buttons + selected one when I click on the "BOUM" button to let the user select a new button, but it's not working anymore.

If you select the button "Test 3" before resetting all buttons by clicking on "boum", it will select the "test 5 button", the place of the old test3 button

### Reproduction Link
[https://codepen.io/Seraf42/pen/eeENxL](https://codepen.io/Seraf42/pen/eeENxL)

**Comment by Seraf** [comment]
On the codepen, by changing the key to `:key="group.name"` it seems to work better.
I let you judge if it's a bug or not ;-)

**Comment by johnleider** [comment]
Because you are looping your items like that, you need to assign a key to avoid Vue from re-using the exiting buttons husk when it re-hydrates.
