### ISSUE TITLE
[Bug][V-Stepper] Transition glitch & Error label hover design

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#2510]
Hello,

When moving between steps with different height, the transition is wrong. 

![stepper-transition-glitch](https://user-images.githubusercontent.com/3975293/32799874-304159f4-c979-11e7-9178-8770bbabb505.gif)

When you try to use the Rules prop, if the error is shown, the design on hover and transitions is not complete.

<img width="214" alt="screen shot 2017-11-14 at 20 15 50" src="https://user-images.githubusercontent.com/3975293/32799650-a86338ae-c978-11e7-8a3c-b4944d8118ff.png">

**Comment by nekosaur** [comment]
Please use the following link when creating a new issue:

https://issues.vuetifyjs.com

If your issue was not created using the app above, it will be closed immediately. Also, please create a separate issue for each problem.
