### ISSUE TITLE
[Bug Report] Two left drawers doesn't play well

### ISSUE THREAD

**Issue by shine-on** [vuetifyjs/vuetify#2512]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Firefox 47.0
**OS:** OpenBSD amd64

### Steps to reproduce
Please run codepen provided.

Click menu button while on desktop to open menuDrawer, search button - to open searchDrawer.

### Expected Behavior
menuDrawer should pop up without toolbar overlay (respecting "app" prop being set).

### Actual Behavior
menuDrawer does not respect "app" prop being set and overlays toolbar.

### Reproduction Link
[https://codepen.io/anon/pen/MOvvmw](https://codepen.io/anon/pen/MOvvmw)

### Other comments
searchDrawer, which is "app" prop-ed too, demonstrates completely expected behaviour - no toolbar overlay. Adding "clipped" to both menuDrawer and searchDrawer gives even more fun.

**Comment by KaelWD** [comment]
You will need to use `$nextTick(...)` with this fix to prevent race conditions, see the PR for an example.
