### ISSUE TITLE
[Bug Report] [V-Stepper] Transition glitch

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#2513]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.89
**OS:** Mac OS 10.13.1

### Steps to reproduce
Click Step 2 and then click Step 1

### Expected Behavior
The transition should not hide the steppers.

### Actual Behavior
Step 2 content height is different from the step 1 so the transition hides the steppers for a while.

### Reproduction Link
[https://codepen.io/anon/pen/OOjoma](https://codepen.io/anon/pen/OOjoma)

### Other comments
![stepper-transition-glitch](https://user-images.githubusercontent.com/3975293/32799874-304159f4-c979-11e7-9178-8770bbabb505.gif)

**Comment by nekosaur** [comment]
Wrap all your `v-stepper-content` elements in a `v-stepper-items` (see https://github.com/vuetifyjs/vuetify/issues/943)
