### ISSUE TITLE
[Bug Report] [V-Stepper] Error label hover design

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#2514]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.89
**OS:** Mac OS 10.13.1

### Steps to reproduce
Click step 1 then hover over step 2

### Expected Behavior
The background below alert icon (on hover) should match the design and the title too.

### Actual Behavior
The background of the icon on hover is not correct & the title is different then in the docs when used statically.

### Reproduction Link
[https://codepen.io/anon/pen/OOjoma](https://codepen.io/anon/pen/OOjoma)

### Other comments
<img width="214" alt="screen shot 2017-11-14 at 20 15 50" src="https://user-images.githubusercontent.com/3975293/32799650-a86338ae-c978-11e7-8a3c-b4944d8118ff.png">

**Comment by johnleider** [comment]
This is moving to v2.0 to coincide with other functionality updates.

**Comment by sh7dm** [comment]
seems like problem isn't present in v2.0.0-beta.2
![image](https://user-images.githubusercontent.com/19504461/59286750-f53eab80-8c78-11e9-8153-710ba21b0e02.png)
