### ISSUE TITLE
[Bug Report] Links are not adhering to theme

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#2515]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
See https://codepen.io/anon/pen/OOjoxr. When I use a different theme, links still appear in blue, both regular `<a>`'s and for example when used in a breadcrumb.

This is by the way also the case if I define my theme already with `Vue.use(Vuetify, { theme: {...}})`, but failed to get that working at all in codepen.

### Expected Behavior
Links color with the primary color of the theme, as they did in the past as well.

### Actual Behavior
Links are colored using the default primary color

### Reproduction Link
[https://codepen.io/anon/pen/OOjoxr](https://codepen.io/anon/pen/OOjoxr)

**Comment by dholladay** [comment]
According to https://material.io/guidelines/style/color.html#color-color-palette

> _Secondary colors_ are best used for:
> 
> - Buttons, floating action buttons, and button text
> - Text fields, cursors, and text selection
> - Progress bars
> - Selection controls, buttons, and sliders
> - **Links**

Also says: 

> You can use your primary color as a link accent.


The change from primary to default-blue was changed in commit [#2397](https://github.com/vuetifyjs/vuetify/pull/2397/files#diff-2ea9da606bfef4bc29f59b8ce2b7325b)
