### ISSUE TITLE
[Bug Report] Hint too far to the right on text fields that use prepend-icon

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#2517]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
Create a text input that uses the prepend-icon prop and the hint prop.

### Expected Behavior
Hint left aligned with the left of input the element

### Actual Behavior
Hint is 40px too far to the right (the padding in `.input-group--text-field.input-group--prepend-icon .input-group__messages`)

### Reproduction Link
[https://codepen.io/everhardt/pen/VrzgBJ](https://codepen.io/everhardt/pen/VrzgBJ)

### Other comments
An earlier issue (#895) was filed and closed that reported the opposite: that the hint was too far to the left.

**Comment by KaelWD** [comment]
*This* one is caused by aba924a7e159fe703b3fd1ceae895ac0220f6e10
