### ISSUE TITLE
[Feature Request] Take error-messages into account in form validation result

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#2519]
### New Functionality
The `v-model` property of a form is `true` if no component within the form has failed any validation rules. Errors that are shown using the error-messages prop are not incorporated in this property, while they do "put the input in an error state" as the docs state. Also having the  `v-model` property of a form return false if there is at least one element in the error-messages-prop of at least one component would allow using the form component when using error-messages.

### Improvements
A current workaround is checking both the form v-model and the error-messages arrays before submitting a form.

### Bugs or Edge Cases it Helps Avoid
It helps avoiding submitting forms while they still contain errors.

**Comment by nekosaur** [comment]
Are you using a 3rd party validation library to pipe errors to `error-messages`? If so there's really no reason to use the `v-form` component. Its purpose is mainly to complement the internal validation engine.

**Comment by everhardt** [comment]
> Are you using a 3rd party validation library to pipe errors to error-messages?

I'm not. I'm using error-messages for validations that require multiple fields. An example: I have two input boxes, one for a start date and one for an end date. I'd like to show an error at the end date if it differs too much from the start date. Validation rules don't work in this case: changing the start date to something closed to the end date will not trigger the validation for the end date and thus not remove any error messages.

The concept of a form that summarises the status of all input forms would be an attractive addition, similar to how it is useful when using validation rules.
