### ISSUE TITLE
Responsive display incoherent

### ISSUE THREAD

**Issue by suitedjimster** [vuetifyjs/vuetify#252]
Hi,

For the helper classes, it seems like the $grid-breakpoints and the $display-breakpoints are not very consistent.

.sm-and-down is using ( max-width: $grid-breakpoints.md - 1 )
.sm-and-up is using ( min-width: $grid-breakpoints.md )
shouldn't it be using $grid-breakpoints.sm ? 

Same with .md and .lg
.md-only is (min-width: $grid-breakpoint.md) and (max-width: $grid-breakpoint.lg - 1) 
but .md-and-up start at $grid-breakpoint.lg ?

there's no display classes that are using $grid-breakpoints.sm (576px)?

is it possible to have the breakpoints corresponding closely to material design? https://material.io/guidelines/layout/responsive-ui.html#

**Comment by johnleider** [comment]
This is actually a bug we just found yesterday. Working on it.
