### ISSUE TITLE
[Bug Report] Text field with character counter when cleared with clearable props return vue warn because cannot read property length of null

### ISSUE THREAD

**Issue by extraxt** [vuetifyjs/vuetify#2520]
# **Versions and Environment**

**Vuetify:** 0.16.0
**Vue:** 2.4.1
**Browsers:** Chrome 62.0.3202.89 64 bits
**OS:** Windows 7

# **Steps to reproduce**

Use a 'v-text-field' with props 'clearable' and ':rules="[(v) => v.length <= 25 || 'Max 25 characters']"'
Insert any string with any size, then clear the field with the 'clearable' icon

# **Expected Behavior**

Just clear the 'v-text-field' like usual and present no error or warn in the console

# **Actual Behavior**

" [Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'length' of null"

found in

---> <VTextField> "

# **Other comments**

I tried to make a 'computed:' method that change the value of the model from 'null' to empty ('') but the warn persists.

**Comment by KaelWD** [comment]
You haven't provided a reproduction link, and you're still using an ancient version of vuetify. Please open a new issue with and up to date reproduction.

**Comment by tiagodurante** [comment]
![image](https://user-images.githubusercontent.com/5533291/54078783-28098a00-42ad-11e9-8e73-c75b6e374d28.png)
![image](https://user-images.githubusercontent.com/5533291/54078793-3b1c5a00-42ad-11e9-9097-f26e42f722e2.png)
![image](https://user-images.githubusercontent.com/5533291/54078794-3f487780-42ad-11e9-8201-5d1fa40abb32.png)
I have an equal problem. Here are some pictures of the code. If necessary, I can make the code available.

**Comment by tiagodurante** [comment]
I have an equal problem. Here are some pictures of the code. If necessary, I can make the code available.
![image](https://user-images.githubusercontent.com/5533291/54087086-52e7f280-432e-11e9-9646-49499a4ad39e.png)
![image](https://user-images.githubusercontent.com/5533291/54087089-57141000-432e-11e9-9155-f423a74fa12a.png)
![image](https://user-images.githubusercontent.com/5533291/54087092-5a0f0080-432e-11e9-815e-7dc922efefa7.png)
