### ISSUE TITLE
[Bug Report] Datatable width 

### ISSUE THREAD

**Issue by YouriBeketov** [vuetifyjs/vuetify#2521]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.3.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 10

### Steps to reproduce
Change the width of headers 

### Expected Behavior
headers width is set by 'width' param in JS

### Actual Behavior
Width set in JS doesn't affect the grid 

### Reproduction Link
[https://codepen.io/YuraB/pen/qVXegp](https://codepen.io/YuraB/pen/qVXegp)

**Comment by KaelWD** [comment]
That codepen is using a scoped header slot, you have to add the width attribute in there. It works fine in regular tables without using slots.
