### ISSUE TITLE
[Bug Report] Absolute footer on top of content on screen with small height

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#2522]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
Reduce the height of your browser and you'll see that the footer overlaps with the bottom part of the v-card.

### Expected Behavior
The footer is displayed below the content.

### Actual Behavior
The footer is displayed on top of the bottom part of the content.

### Reproduction Link
[https://codepen.io/everhardt/pen/POJoOj](https://codepen.io/everhardt/pen/POJoOj)

### Other comments
Note that:
* with `fixed` instead of `absolute` the content cannot be scrolled far enough to display the bottom of the `v-card`, so that's also not working as expected
* without `fixed` or `absolute` there is no collission (as expected)

**Comment by KaelWD** [comment]
If you want a fixed footer, use the `app` attribute: https://codepen.io/anon/pen/zPEYQY?editors=1000

Otherwise, place it below the `v-content`: https://codepen.io/anon/pen/LOzYoZ?editors=1010

**Comment by everhardt** [comment]
Thanks @KaelWD, that second option solves my case. Just for the docs: I still don't understand how I should interpret the `absolute` attribute. Is it (based on my codepen): "footer will be placed below all content as long as there is space left"? That does not sound too useful.
