### ISSUE TITLE
Data table expanded props error:   Invalid array length

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify#2524]
Hi im Using Vuetify 0.16.4
I had a weird issue pertaining to expanded props of data tables...

This Only Happens When I Sort the Items in the tables...

If i didnt sort the items and i click the button that trigger the props to expand...

there is no problem, but when i already sort it,

i cant toggle the expanded table row props.expanded...

its giving me error Invalid array length

**Comment by codeitlikemiley** [comment]
ok ive fixed it by adding the props expand on the data tables

**Comment by rosnaib11** [comment]
I had same issue I added expand also doesn't work for me

**Comment by jacekkarczmarczyk** [comment]
@rosnaib11 please create a new issue and provide a codepen
