### ISSUE TITLE
I'm new in vue and I'm using materialize css is it require to have jquery whne using this? I'm planning to avoid jquery because its very large

### ISSUE THREAD

**Issue by rosnaib11** [vuetifyjs/vuetify#2529]

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

Jquery is not required and the use of it is actively discouraged.
