### ISSUE TITLE
v-text-field broke after 0.93

### ISSUE THREAD

**Issue by jakobrosenberg** [vuetifyjs/vuetify#253]
Inputs are unclickable in the latest release. Delaying render with v-if seems to help.

**Comment by cawa-93** [comment]
@jakobrosenberg, Please, add reproduce link

**Comment by Zeph33** [comment]
Input are also unclickable in tabs see sample : [http://codepen.io/anon/pen/oZdMgp](http://codepen.io/anon/pen/oZdMgp)

**Comment by Zeph33** [comment]
Height of input is 0, in the file TextField.js 
```javascript
calculateInputHeight () {
      this.inputHeight = this.$refs.input.scrollHeight
}
// this.$refs.input.scrollHeight  => return 0
```

**Comment by Zeph33** [comment]
Not completely corrected

calculateInputHeight also call on: 
```javascript
watch: {
  ...
  value () {
      this.lazyValue = this.value
      this.validate()
      this.calculateInputHeight()
    }
}
``` 
If input is hide when assign value input.scrollHeight => 0 and inputHeight assigned to 0
See sample : [http://codepen.io/anon/pen/WpaQOg](http://codepen.io/anon/pen/WpaQOg)
click button => _**hide and change**_ 
click button => _**show**_ 
now inputHeight is 0
