### ISSUE TITLE
[Feature Request] Make tabs match material spec better

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#2530]
The tabs do not currently match the material specification and are rather difficult to use on mobile and narrow browser windows. 

In particular, the side margins need to be looked at:
![image](https://user-images.githubusercontent.com/16421948/34324583-61eee116-e8cc-11e7-9a63-2fac1c419501.png)

Also see the discussion in #1789 and #1749

https://material.io/guidelines/components/tabs.html#

yeah, I didn't use the template. Sue me

**Comment by nekosaur** [comment]
Consider yourself sued!

**Comment by BennyAlex** [comment]
@nekosaur @KaelWD 
Another missing feature of the tabs are an working menu like this:
![unbenannt324](https://user-images.githubusercontent.com/17402724/32937956-dc092598-cb7a-11e7-80ef-8b330fc8e36d.PNG)
I really need this feature for the new application for my company. Do you think you can implement this?

**Comment by KaelWD** [comment]
Create a new feature request for that, it's outside the scope of this issue.

**Comment by nekosaur** [comment]
That is also already possible. See example #7 on docs.
