### ISSUE TITLE
[Bug Report] Tooltip not work with Floating Action Buttons

### ISSUE THREAD

**Issue by canhkieu** [vuetifyjs/vuetify#2532]
```html
      <v-tooltip :value="true" top>
        <v-btn color="primary" fab dark small fixed bottom right icon style="bottom: 70px;">
          <v-icon>shopping_cart</v-icon>
        </v-btn>
        <span>Booking now</span>
      </v-tooltip>
```

I got this error when use Tooltip with Floating Action Buttons
`ReferenceError: document is not defined`

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
