### ISSUE TITLE
[Bug Report] Can not use Tooltip v-model with Float Action Buttons

### ISSUE THREAD

**Issue by canhkieu** [vuetifyjs/vuetify#2533]
### Versions and Environment

Vuetify: 0.17.0
Vue: 2.5.3
Browsers: Chrome 62.0.3202.94
OS: Windows 10

### Steps to reproduce
I got error below error when try to alway enable Tooltip for Float Action Buttons by v-model. If remove v-model attribute, everything OK. 
`
ReferenceError is not defined
`

### Expected Behavior

Error page

### Actual Behavior

Tooltip alway show.

### Reproduction Link

https://codepen.io/canhkieu/pen/mqBvGZ

**Comment by johnleider** [comment]
This is a bug, but not for the reasons you are explaining. You cannot use `v-model="true"`, true isn't a model, it's a primitive boolean, and that has to do with Vue, not Vuetify.

With that being said, there is work that can be done to make sure tooltip can be programmatically opened properly

**Comment by KaelWD** [comment]
Update to 0.17.6 then use `:value="true"` instead of v-model. There's also a `disabled` prop if you don't want it to respond to pointer events.
