### ISSUE TITLE
[Feature Request] DevApp like ionic

### ISSUE THREAD

**Issue by msaelices** [vuetifyjs/vuetify#2535]
### New Functionality

See:

http://blog.ionicframework.com/announcing-ionic-devapp/

Or see this video:

https://www.youtube.com/watch?v=tbTo60fAJcc

### Improvements
A Better Way to Test Apps in Development

### Bugs or Edge Cases it Helps Avoid
Problems when publishing apps you think are correct but fail in the device

**Comment by robodude** [comment]
This might be **way** beyond the scope of a material design component library ^_^

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement.
