### ISSUE TITLE
[Feature] text-field append-icon clickable

### ISSUE THREAD

**Issue by misterigl** [vuetifyjs/vuetify#254]
It would be nice to be able to call a function once the appended or prepended icon in the text field is clicked, e.g. to start the search or do something else.

**Comment by suitedjimster** [comment]
If you look the source files, there is a undocumented prop called appendIconCb which serves this purpose I think. I might be wrong...

**Comment by johnleider** [comment]
@suitedjimster is correct, this will be added to the public api. Also added a cursor: pointer for icons that have callbacks assigned to them.
