### ISSUE TITLE
[Feature Request] Pagination flat/outline styles

### ISSUE THREAD

**Issue by talski** [vuetifyjs/vuetify#2541]
### New Functionality
Pagination can't be styled out of the box as flat or outline buttons

### Improvements
you need to create your own styles to achieve the desired effect that buttons have by default

**Comment by BennyAlex** [comment]
That feature would be really nice

**Comment by andrew-aladev** [comment]
It is easy, we need just to replace:

```
return h(
  'li',
  [
    h(
      'button',
      {
        staticClass: 'pagination__navigation',
        class: {
          'pagination__navigation--disabled': disabled
        },
        on: disabled ? {} : { click: fn }
      },
      [h(VIcon, [icon])]
    )
  ]
)
```

with

```
return h(
  'li',
  [
    h(
      VBtn,
      {
        props: {
          disabled,
          icon: true,
          flat: true
        },
        on: disabled ? {} : { click: fn }
      },
      [h(VIcon, [icon])]
    )
  ]
)
```

I've created such component:

```
import VPagination from 'vuetify/es5/components/VPagination'
import VBtn from 'vuetify/es5/components/VBtn'
import VIcon from 'vuetify/es5/components/VIcon'

export default {
  name:    'flat-pagination',
  extends: VPagination,
  methods: {
    genIcon (h, icon, disabled, fn) {
      return h(
        'li',
        [
          h(
            VBtn,
            {
              props: {
                disabled,
                icon: true,
                flat: true
              },
              on: disabled ? {} : { click: fn }
            },
            [h(VIcon, [icon])]
          )
        ]
      )
    }
  }
}
```

It looks ok. But it doesn't like good solution. `flat`, `light`, 'dark', etc wants to be a properties.

**Comment by alvaro-canepa** [comment]
Another props can be `left`, `centered` (default) and `right` to align content  buttons.

**Comment by Radiergummi** [comment]
Should this ever get a backport to Vuetify 2 - the easiest option would be to provide slots for the buttons. I'm thinking of the following in particular:

| Slot name | Slot scope | Description |
|:--|:--|:--|
| `item` | <pre lang="scala">{ page: number; currentPage: number; active: boolean; disabled: boolean }</pre> | Pagination button |
| `item.prev` | <pre lang="scala">{ currentPage: number; disabled: boolean }</pre> | Previous page button |
| `item.next` | <pre lang="scala">{ currentPage: number; disabled: boolean }</pre> | Next page button |
| `separator` | <pre lang="scala">{ currentPage: number; disabled: boolean }</pre> | Ellipsis between segments |
