### ISSUE TITLE
[Bug Report] Temporary Navigation Drawer does not close

### ISSUE THREAD

**Issue by jingzheshan** [vuetifyjs/vuetify#2544]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
Use Ipad safari to open the https://vuetifyjs.com/examples/layouts/google-contacts. Then open the site navigation drawer. The main page had an overlay.

### Expected Behavior
When touching the overlay the drawer should close.

### Actual Behavior
It does not close.

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

**Comment by KaelWD** [comment]
Please include which version of iOS and Safari are affected https://www.whatismybrowser.com/

**Comment by jingzheshan** [comment]
Safari 11 on iOS 11.1 - https://www.whatismybrowser.com/w/HED8KBZ

**Comment by manico** [comment]
On 0.17.1 drawer does not move content to the right when changing from mini to normal.
On 0.17.0 it is ok.

**Comment by KaelWD** [comment]
@manico Why are you saying that here? It's completely unrelated. Make a new issue.

**Comment by manico** [comment]
It's related to navigation drawer and issues are on the same version.
If new issue is required, no problem.

**Comment by johnleider** [comment]
Is this still happening? Unfortunately the newer versions of webpack-dev-server declare variables as const and let, basically making it impossible for me to test this.

**Comment by jingzheshan** [comment]
Sorry, it is still happening under 1.0.0-alpha.1. I guess you could try to add a touch event when click on overlay to invoke the mouse click on the overlay.

**Comment by johnleider** [comment]
Well, I cannot test, that is my issue. Does anyone here have the ability to test this that could help?

**Comment by johnleider** [comment]
Head over to https://chat.vuetifyjs.com
