### ISSUE TITLE
[Bug Report] Incorrect display of v-tabs-slider on narrow screens

### ISSUE THREAD

**Issue by Neiromaster** [vuetifyjs/vuetify#2548]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
When I'm at [http://localhost/incidents](http://localhost/incidents) and I update the page on a narrow screen (1250px), I get a problem with the moved v-tabs-slider [img](https://yadi.sk/i/UBluSEMt3PnYhY)

### Expected Behavior
Correct display of v-tabs-slider on all screen sizes

### Actual Behavior
Incorrect display of v-tabs-slider on some screen sizes

### Reproduction Link
[https://codepen.io/Neiromaster/pen/EbbLVq?&editors=101](https://codepen.io/Neiromaster/pen/EbbLVq?&editors=101)

**Comment by jingzheshan** [comment]
I am facing the same problem.

![image](https://user-images.githubusercontent.com/2770401/33042026-4809dbac-cea5-11e7-9bb9-35dabfc59377.png)
