### ISSUE TITLE
[Bug Report] v-tooltip containing a v-badge with a v-icon removes the element containing the icon when activated

### ISSUE THREAD

**Issue by nborko** [vuetifyjs/vuetify#2550]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
Create a `v-tooltip` that has a `v-badge` somewhere in the child tree with a `<v-icon slot="badge">`. Activate the tooltip.

### Expected Behavior
The tooltip should appear without affecting the child content.

### Actual Behavior
The `.badge__badge`  element is removed from the DOM.

### Reproduction Link
[https://codepen.io/nborko/pen/wPPQPo](https://codepen.io/nborko/pen/wPPQPo)

### Other comments
The layout is pretty messed up after the tooltip is activated, see pen.

**Comment by nzxt** [comment]
Confirm. Inside v-tooltip > v-icon compiles empty span.

**Comment by jacekkarczmarczyk** [comment]
Vue 2.5.4 broken something, probably https://github.com/vuejs/vue/commit/13196b25b8a0a84b3936982177195d2e04f13f79

With 2.5.3 it works fine https://codepen.io/anon/pen/VrXJRV

**Comment by jacekkarczmarczyk** [comment]
Fixed in Vue 2.5.9

**Comment by jcepek** [comment]
This use case appears to be broken as well. Upgraded to vue 2.5.13 and vuetify 0.17.7 and this example is not working.

[](https://codepen.io/jacCodePen/pen/VQedyd)

**Comment by tvkit** [comment]
@jcepek try adding `slot="activator"`  to the `<v-badge />` element to show the content.
