### ISSUE TITLE
[Feature Request] Having an horizontally centered FAB

### ISSUE THREAD

**Issue by jess8bit** [vuetifyjs/vuetify#2553]
### New Functionality
Currently Floating Action Buttons can be only positioned to the left or to the right of an horizontal top or bottom border of their container (toolbar, card-text etc).
But we can't position them in the middle of the edge. 
Having this extra feature would enhance user experience in some cases.

### Improvements
This would avoid additional custom css to achieve this.

### Bugs or Edge Cases it Helps Avoid
none.

**Comment by johnleider** [comment]
I want to move the fab features into its own component which coincides with the new md spec planned for 2.0

**Comment by jblachly** [comment]
Great news. I came here after seeing the new material design case studies from google, and in particular Reply (https://material.io/design/material-studies/reply.html#product-architecture) which has a very nice centered FAB.

**Comment by gotenxds** [comment]
@johnleider 
is this marked for v3.0? has you removed it from 2.x but did not add it to anything

**Comment by johnleider** [comment]
It's slated for release in version 3.
