### ISSUE TITLE
When selecting router, v-navigation-drawer (right side v-model) is automatically set to true.

### ISSUE THREAD

**Issue by Gregory-Han** [vuetifyjs/vuetify#2555]
<template>
  <v-app id="inspire">
    <v-navigation-drawer
      fixed
      v-model="drawerRight"
      right
      clipped
      app
    >
      <v-list dense>
        <v-list-tile @click.stop="right = !right">
          <v-list-tile-action>
            <v-icon>settings</v-icon>
          </v-list-tile-action>
          <v-list-tile-content>
            <v-list-tile-title>Right Drawer</v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-navigation-drawer>

    <v-toolbar
      color="blue-grey"
      dark
      fixed
      app
      clipped-right
    >
      <v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon>
      <v-toolbar-title>Toolbar</v-toolbar-title>
      <v-spacer></v-spacer>
      <v-toolbar-side-icon @click.stop="drawerRight = !drawerRight"></v-toolbar-side-icon>
    </v-toolbar>

    <v-navigation-drawer
      fixed
      v-model="drawer"
      app
    >
      <v-list dense>
        <v-list-tile @click.stop="left = !left">
          <v-list-tile-action>
            <v-icon>home</v-icon>
          </v-list-tile-action>
          <v-list-tile-content>
            <v-list-tile-title>홈</v-list-tile-title>
            <v-list-tile-sub-title>Menu</v-list-tile-sub-title>
          </v-list-tile-content>
        </v-list-tile>
        <v-divider></v-divider>
        <template v-for="(item, index) in items">
          <v-list-tile :to="{name: item.name}" :key='index'>
            <v-list-tile-action>
              <v-icon light v-html="item.icon"></v-icon>
            </v-list-tile-action>
            <v-list-tile-content>
              <v-list-tile-title v-html="item.title"></v-list-tile-title>
            </v-list-tile-content>
          </v-list-tile>
        </template>
    </v-list>
    </v-navigation-drawer>

    <v-content>
      <v-container fluid fill-height>
        <v-layout justify-center align-center>
          <v-tooltip right>
            <v-btn icon large slot="activator">
              <v-icon large>code</v-icon>
            </v-btn>
            <span>Content</span>
          </v-tooltip>
        </v-layout>
      </v-container>
    </v-content>

    <v-footer color="blue-grey" class="white--text" app>
      <span>Vuetify</span>
      <v-spacer></v-spacer>
      <span>&copy; 2017</span>
    </v-footer>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      drawer: true,
      drawerRight: true,
      right: null,
      left: null,
      items: [{
        name: 'home',
        router: true,
        title: 'Home',
        icon: 'home'
      }, {
        name: 'examples',
        router: true,
        title: 'Example',
        icon: 'extension'
      }, {
        name: 'about',
        router: true,
        title: 'About',
        icon: 'domain'
      }],
      title: 'C2i-Studio'
    }),
    props: {
      source: String
    }
  }
</script>

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
