### ISSUE TITLE
[Bug Report] Scroll shrink (scrolling techniques) in combination with drawer not sizing content area correctly

### ISSUE THREAD

**Issue by Mathem8tic** [vuetifyjs/vuetify#2556]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.5
**Browsers:** Chrome 62.0.3202.89
**OS:** Linux x86_64

### Steps to reproduce
Run the codepen and notice the content text flows past the sidebar

### Expected Behavior
The content area resizes to to match the behavior of the toolbar 

### Actual Behavior
The content area does not resize, thus the drawer is over top

### Reproduction Link
[https://codepen.io/anon/pen/yPpYpP#anon-signup](https://codepen.io/anon/pen/yPpYpP#anon-signup)

**Comment by KaelWD** [comment]
You need a `v-content` to respond to drawer size changes.

**Comment by Mathem8tic** [comment]
Indeed, but that then breaks the scrolling technique scroll shrink...

**Comment by Mathem8tic** [comment]
You are 100% correct, I could swear I used the <v-content> 100 times to no avail.  Seems be be working now though.  Sorry and thanks!
