### ISSUE TITLE
[Bug Report] Icon button styles are incorrect in v-toolbar-items

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#2557]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Chrome 62.0.3202.89
**OS:** Windows 10

### Steps to reproduce
Hover one of the buttons

### Expected Behavior
Buttons should be circular, evenly spaced, and vertically centered

### Actual Behavior
Buttons are vertically centered but the hover effect is stretched and they are too close together

### Reproduction Link
[https://codepen.io/anon/pen/BmJQZb?editors=1000](https://codepen.io/anon/pen/BmJQZb?editors=1000)

**Comment by johnleider** [comment]
`v-toolbar-items` only exists to make buttons full height.
