### ISSUE TITLE
[Bug Report] v-navigation-drawer doesn't update isMobile when temporary

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#2559]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.5
**Browsers:** Chrome 62.0.3202.89
**OS:** Windows 10

### Steps to reproduce
- Make the screen narrow (<1264px)
- Set the drawer to temporary
- Make the screen wide again
- Set the drawer back to persistent and try to open it

### Expected Behavior
The drawer should open when resized back to large
The drawer should be persistent

### Actual Behavior
The drawer is still in the mobile state and is therefore temporary with an overlay

### Reproduction Link
[https://codepen.io/anon/pen/MOrbRJ?editors=1010](https://codepen.io/anon/pen/MOrbRJ?editors=1010)

**Comment by davi5e** [comment]
I don't have this problem, but I did manually configure a lot of stuff, as in:

**Comment by davi5e** [comment]
I don't have this problem, but I did manually configure a lot of stuff, as in:

`<v-navigation-drawer app
                         absolute
                         :persistent="! isMobile"
                         :temporary="isMobile"
                         :clipped="! isMobile"
                         light
                         :mini-variant="mini"
                         v-model="drawer"
                         overflow
                         :mobileBreakPoint="mobileWidth"
                         enable-resize-watcher
                         class="grey lighten-3 pb-0"
                         @click.native="disableMini">`

And `isMobile` is a variable I use to keep track of the page width.

**Comment by KaelWD** [comment]
isMobile is also an internal variable in the drawer, which is what this issue is about.
