### ISSUE TITLE
Help...... I cannot set it Horizontal !!!!! please help

### ISSUE THREAD

**Issue by mhmetsus** [vuetifyjs/vuetify#2561]
<div class="grey-top counter-container">
        <div class="container main-splash fixed">
            <div id="splash-counts">
                <div>
                    <div class="s-count-items fixed">
                        <div class="downloads-served"> 942860 </div>
                        <div class="splash-count-title">Downloads </div>
                    </div>
                </div>
                <div class="v-spacer">&nbsp;</div>
                <div>
                    <div class="s-count-items fixed">
                        <div id="latest-updates">12 Minutes Ago</div>
                        <div class="splash-count-title">Last Update </div>
                    </div>
                </div>
                <div class="v-spacer">&nbsp;</div>
                <div>
                    <div class="s-count-items fixed">
                        <div id="windows-programs">970</div>
                        <div class="splash-count-title">Programs </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
