### ISSUE TITLE
[Bug Report] v-navigation-drawer "mini" don't set the padding

### ISSUE THREAD

**Issue by davi5e** [vuetifyjs/vuetify#2562]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Chrome 62.0.3202.94
**OS:** Linux

### Steps to reproduce
Open the Sandbox (https://vuetifyjs.com/examples/layouts/sandbox) and click the "mini" option to see that the page does not correct itself.

### Expected Behavior
The old padding worked and the content automatically responded to the mini version

### Actual Behavior
No padding, so nothing changes. If you actually use the persistent option and close the drawer, upon re-opening the padding will be applied though

### Reproduction Link
[https://github.com/vuetifyjs/docs/blob/dev/pages/SandboxView.vue](https://github.com/vuetifyjs/docs/blob/dev/pages/SandboxView.vue)

**Comment by KaelWD** [comment]
Duplicate of #2547
