### ISSUE TITLE
[Epic] Add tests to the codebase

### ISSUE THREAD

**Issue by zevektor** [vuetifyjs/vuetify#2568]
### New Functionality
I noticed that at every slight update of vuetify, something breaks.
Being able to write a working piece of code is becoming harder and harder. After hours of desperation usually I come to vuetify issues just to see that it's a bug introduced by the latest update or a regression. Could you please enhance test coverage? 

### Improvements
Developers will quickly realize if their update adds bugs/regression, making the vuetify framework more stable than a house of cards.

### Bugs or Edge Cases it Helps Avoid
Potentially most of the bugs.

**Comment by KaelWD** [comment]
Coverage is slowly improving (https://codeclimate.com/github/vuetifyjs/vuetify/trends/test_coverage_total), and we have status checks on all new PRs to make sure they have adequate tests. Coverage % alone isn't an indicator that there are no bugs, all of the navigation drawer bugs from 0.17 were from covered lines with incomplete tests.

**Comment by johnleider** [comment]
Removing milestone as this is an on-going effort.
