### ISSUE TITLE
'rightdrawer' is automatically set to 'true' whenever a router is selected, even if 'rightdrawer' is already 'false'.

### ISSUE THREAD

**Issue by Gregory-Han** [vuetifyjs/vuetify#2570]
# Versions and Environment

Vuetify: 0.17.0
Vue: 2.5.3
Browsers: Chrome 62.0.3202.94
OS: maxOS 10.13.1(17B48)

# Steps to reproduce

At https://vuetifyjs.com/examples/layouts/complex ,
`<template v-for="(item, index) in items">
          <v-list-tile :to="{name: item.name}" :key='index'>
            <v-list-tile-action>
              <v-icon light v-html="item.icon"></v-icon>
            </v-list-tile-action>
            <v-list-tile-content>
              <v-list-tile-title v-html="item.title"></v-list-tile-title>
            </v-list-tile-content>
          </v-list-tile>
        </template>
 and added data
items: [{
        name: 'home',
        router: true,
        title: 'Home',
        icon: 'home'
      }, {
        name: 'examples',
        router: true,
        title: 'Example',
        icon: 'extension'
      }, {
        name: 'about',
        router: true,
        title: 'About',
        icon: 'domain'
      }],
`
# Expected Behavior

The  v-model rightdrawer should not change.
# Actual Behavior

when a router is selected, then 'rightdrawer' is automatically set to 'true'

**Comment by KaelWD** [comment]
Please provide a reproduction link and more details as to what the problem actually is.

**Comment by suica** [comment]
I met the same problem and I fixed it by adding `disable-route-watcher` to `v-navigation-drawer` tag like this:
` <v-navigation-drawer disable-route-watcher v-model="whatever">`.
The drawer will automatically "be activated" after route changes. That may be the cause.

API document: [https://vuetifyjs.com/components/navigation-drawers](url)
> disable-route-watcher | Boolean | False | Disables opening of navigation drawer when route changes

**Comment by Gregory-Han** [comment]
In the same way I have already done it, but thanks for your reply.
Thank you, suica
