### ISSUE TITLE
default icon in data table head can't be in Font-Awesome

### ISSUE THREAD

**Issue by elkebirmed** [vuetifyjs/vuetify#2571]
I'm using **Font-Awesome** instead of **MDI**. How to change the default icon in *Data Table heading* `arrow_upward` from **MDI** to **Font-Awesome**?

**Comment by KaelWD** [comment]
<https://vuetifyjs.com/components/data-tables#example-3>

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
