### ISSUE TITLE
Using checkbox in long data-tables with ripple enabled has serious performance issues in Chrome

### ISSUE THREAD

**Issue by shig2k1** [vuetifyjs/vuetify#2574]
### New Functionality
Try creating a v-data-table with v-checkboxes in it. After 150 rows the performance in Chrome / Chromium is seriously affected. Removing ripple effect and it's peachy

### Improvements
I won't have to bugger about overriding the css

### Bugs or Edge Cases it Helps Avoid
Serious performance issues in Chrome / Chromium. Yes, I'm aware that pagination would help, it's not always convenient to split longer lists.

**Comment by shig2k1** [comment]
I should also add - Vuetify is AMAZING! you all should be so proud of your work

**Comment by shig2k1** [comment]
On closer inspection, I can simply improve performance in Chrome/chromium by adding the following override: 

.input-group--selection-controls__ripple {
  border-radius: 0 !important;
}

performance afterwards is fine.

**Comment by KaelWD** [comment]
This looks like it's supposed to be a bug report. Please open a new issue with the required information and provide some reproduction.
