### ISSUE TITLE
[Feature Request] More Designs on Carousel

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#2576]
### New Functionality

<p align="Left">
  <a href="https://surmon-china.github.io/vue-awesome-swiper/?ref=madewithvuejs.com" target="_blank"> Just saw this maybe useful,  See Link
</a>
</p>

### Improvements
...

### Bugs or Edge Cases it Helps Avoid
...

**Comment by nekosaur** [comment]
There is not enough information in this feature requeset. Please fill in the missing information, and exactly which features you are referring to, or the issue will be closed.
