### ISSUE TITLE
[Bug Report] Text for 'Accent' changes inconsistant with other theme colors on light/dark

### ISSUE THREAD

**Issue by shanemgrey** [vuetifyjs/vuetify#2581]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.89
**OS:** Mac OS 10.12.6

### Steps to reproduce
Click the 'Dark' switch at the bottom to see that the color of text in the Accent button changes, but none of the others do.

### Expected Behavior
It should not change text color.

### Actual Behavior
It does

### Reproduction Link
[https://codepen.io/shanemgrey/pen/gXvKdd](https://codepen.io/shanemgrey/pen/gXvKdd)

### Other comments
I haven't tested to see if this behavior happens outside of buttons.

**Comment by jacekkarczmarczyk** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/pull/2589
