### ISSUE TITLE
[Bug Report] Multi-line Text-field's height does not expand on load when inside a v-tabs-content

### ISSUE THREAD

**Issue by hrayr-artunyan** [vuetifyjs/vuetify#2582]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
1. Create a `v-tab` component with one or more `v-tabs-content`.
2. Add `v-text-field` with `multi-line` and `auto-grow` properties inside one of the `v-tabs-content` containers.
3. Set the `v-model` of the `v-text-field` to contain multiple lines of text that is longer than the rows set on the text field.

```pug
v-tabs
	v-tabs-bar
		v-tabs-item(href="#1") Tab #1
	v-tabs-items
		v-tabs-content#1
			v-text-field(v-model="text" auto-grow="" multi-line="" rows="1")
```

The text-field does not automatically expand to contain the entire text when first loaded. It only expands when you try to update the v-model.

### Expected Behavior
The text field's height should expand to show the entire multiple lines of text.

### Actual Behavior
The text-field remains the same height of rows that was originally set, and does not increase the height to display the entire text. 

### Reproduction Link
[https://codepen.io/anon/pen/MOQqOB?editors=1010](https://codepen.io/anon/pen/MOQqOB?editors=1010)

### Other comments
When you set `lazy` property on the v-tab-container the text-field's behavior is correct.

**Comment by polmabri** [comment]
The same behavior can be found in v-expansion-panel-content.

**Comment by johnleider** [comment]
This issue has been corrected as far as I can tell. If you are still able to reproduce this issue somehow on beta.2, please let me know.

**Comment by jjbluesky** [comment]
I'm experiencing the same issue with the v-stepper. You can check it out here: https://codepen.io/jjbluesky/pen/jxpXZx 

The lazy property (which was mentioned above) didn't help in this case.

**Comment by jacekkarczmarczyk** [comment]
Please create a new issue
