### ISSUE TITLE
[Bug Report] v-btn icon routing to '/', active class is added

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#2583]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Linux x86_64

### Steps to reproduce
Add a v-btn with the "to" attribute pointing to "/"

### Expected Behavior
There should be no btn--active class added.

### Actual Behavior
The class gets added, changes the color which causes the faint circle.

### Reproduction Link
[https://codepen.io/amritk/pen/WXMaxa](https://codepen.io/amritk/pen/WXMaxa)

### Other comments
This icon button is used as a home link.

**Comment by KaelWD** [comment]
Not a bug https://router.vuejs.org/en/api/router-link.html

**Comment by ecaldwell** [comment]
@amritk I had this problem too. It took me a minute to find the solution at the link @KaelWD provided. The solution is to add the `exact` property to the button. https://codepen.io/anon/pen/gXvqYG

**Comment by amritk** [comment]
good call @ecaldwell
