### ISSUE TITLE
[Bug Report] V-Bind:id Doesn't Work on V-Data-Table

### ISSUE THREAD

**Issue by MexicanRaindeer** [vuetifyjs/vuetify#2584]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
1. Use v-bind:id on a v-data-table

### Expected Behavior
v-bind:id should add an id tag to the table html element

### Actual Behavior
The table's id tag is empty

### Reproduction Link
N/A

**Comment by jacekkarczmarczyk** [comment]
It adds "id" attr to table's container:
![image](https://user-images.githubusercontent.com/15625235/33068379-ac8410c8-cee3-11e7-844f-a90973e029e6.png)
