### ISSUE TITLE
[Bug Report] Mouse scroll right after Dialog/NavigationDrawer is closed will cause "getComputedStyle" error in Chrome

### ISSUE THREAD

**Issue by johnyluyte** [vuetifyjs/vuetify#2586]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
0. Use **Chrome**
1. Go to https://vuetifyjs.com/components/dialogs
2. Click **#2 Without activator** Open Dialog
3. Close the dialog and scroll the mouse like crazy
4. You should see the error output in the console

### Expected Behavior
Should not output error.

### Actual Behavior
Output error.

### Reproduction Link
[https://codepen.io/anon/pen/VrXYLJ](https://codepen.io/anon/pen/VrXYLJ)

### Other comments
If you scroll your mouse right after closing a **Dialog** or **NavigationDrawer**, Google Chrome will output **getComputedStyle** error in the console.

If you just wait for a second then scroll, the error doesn't occur. It seems like the error only occurs when you scroll at the same time the **Dialog/NavigationDrawer** is doing "fade out transition".

Another thing to note is that the error only occurs in **Chrome** where you can scroll during the "fade out transition". In Firefox 57, the page will not scroll when Dialog/Drawer is doing the transition, so Firefox output no errors at all.

**Comment by KaelWD** [comment]
Doesn't happen for me, the page doesn't scroll until the animation is complete. 

Chrome 62 on windows 10.

**Comment by johnyluyte** [comment]
I just tested again with 2 computers. Some browsers can scroll while the animation is occurring, and output error.

**Windows 10 64 Bit**

Error:
- Chrome 62.0.3202.94 64 bit
- Opera 49.0.2725.39

No Error:
- Edge
- Firefox 57

**macOS Sierra 10.12.6**

Error:
- Chrome 62.0.3202.94 64 bit

No Error:
- Opera 49.0.2725.39
- Safari
- Firefox 57

I think I'll go do some testing tomorrow. Since the Opera's behavior is interesting within 2 different devices

**Comment by rabelfish** [comment]
Same thing happening for me:

Chrome 62.0.3202.94 64-bit
Mac OS X Yosemite 10.10.5 

No issues with Firefox on the same Mac

**Comment by KaelWD** [comment]
Can someone who is getting this error please create a pastebin with the stack trace?

**Comment by johnyluyte** [comment]
Hey I actually did further tests but forgot to post here, sorry.

I've found out that this behavior only occurs when AdBlock or Adblock Plus (These are browser extensions) are enabled in my browser, both Chrome and Opera. 

If I disable them, I cannot scroll during Dialog fade out (i.e. the page doesn't scroll until the animation is complete) and no error will be output.

Here is the pastebin with the stack trace.
https://pastebin.com/Qg0U3x6J

**Comment by KaelWD** [comment]
So for some reason, adblock adds some extra elements to the composedPath

With adblock:
![image](https://user-images.githubusercontent.com/16421948/33523265-4f652c2a-d856-11e7-8b03-1d2934acafd0.png)

Without adblock:
![image](https://user-images.githubusercontent.com/16421948/33523269-5b96e0c4-d856-11e7-8e1a-3841dc6de8cd.png)

Stopping once we get to `body` should be enough to prevent this, we don't care about anything past that anyway.

**Comment by johnyluyte** [comment]
Thanks. I subscribed to uBlock origin and ditched Adblock right away. I've had other issues with adblock when devleloping web apps and tried to get rid of it for a long time.

FWIT: adblock not only inject extra element into DOM, but will occasionally disable the site's function (javascript, image..) if the URL of the site is "suspicious". I had fun debugging my `/gg/index.html` just to found that it was blocked by adblock. (Adblock setting -> Show all request -> See what's been blocked)

**Comment by mkhennoussi** [comment]
Hi everyone, 

I have the same issue and I don't think it is related to Adblock but only to Chrome (My version is 63.0.3239.108 (Official Build) (64-bit) running on macOS Sierra).

- I don't have Adblock in Chrome, but I have the issue.
- I do have Adblock in Firefox but I don't have the issue.
