### ISSUE TITLE
[Bug Report] Browser lag on character input on text field email

### ISSUE THREAD

**Issue by ppietris** [vuetifyjs/vuetify#2588]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94, Google Chrome, Microsoft Edge, Internet Explorer
**OS:** Windows 10, Windows

### Steps to reproduce
Try to enter as many as possible characters on the  email input (not a valid email address)

### Expected Behavior
Normal validation

### Actual Behavior
Browser lag

### Reproduction Link
[https://codepen.io/anon/pen/jazEJK](https://codepen.io/anon/pen/jazEJK)

**Comment by KaelWD** [comment]
Complex regex is slow:
![image](https://user-images.githubusercontent.com/16421948/33068404-4c708aaa-cf05-11e7-9ab5-a5d5afe75451.png)

Use `validate-on-blur` to prevent the frame drops while typing.
