### ISSUE TITLE
[Feature Request] Have the ability for v-menu's menu-keyable.js mixin functionality to either be disabled or customized

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#2598]
### New Functionality
https://codepen.io/anon/pen/VrXyLN
The menu-keyable.js mixin gives functionality that does not make sense when the menu is extended up (using the 'top' prop).
The highlight can will only show by pushing the down-arrow, when it seems like the user should push the up-arrow and start at the bottom of the list.
By allowing some form of customization (like being able to set the initial listIndex, or maybe having the list loop so when listIndex is -1 and up-arrow is pushed it is set to this.tiles.length - 1) would make the mixin way more useful.
The other option could be a way to disable the mixin with a prop.

### Improvements
There is not a work-around other than using a custom list.

### Bugs or Edge Cases it Helps Avoid
This is just added functionality.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
