### ISSUE TITLE
Sliders update images but not number of images

### ISSUE THREAD

**Issue by csik** [vuetifyjs/vuetify#26]
When using sliders I'm trying to set the images dynamically. In the new Vue() constructor I have data like:
`slider_items:  {urls: [{},{},{}]}`
and I if I later state:
`myVue.slider_items.urls = newUrls;`
the images change successfully, and `myVue.slider_items.urls` is exactly what I'd expect.

However, the number of images the slider has is unchanged. 

If there were three urls in the view constructor, and the new `myVue.slider_items.urls.length === 5`, only the first three images cycle and only 3 slider_controls buttons render. Likewise, if `myVue.slider_items.urls` started in the constructor with 3 urls and the newly minted `myVue.slider_items.urls` contains only one object, the slider will show that new image but then two blank screens.

**Comment by johnleider** [comment]
Fixed with 8749d0302a0a092026a6a53980e32982c0def77d.

**Comment by csik** [comment]
Everything I'd been working with is now broken... both sliders and navbars now show up as "undefined."

I've reduced everything down to a single slider and here is what it gives me:

vue.js:525 [Vue warn]: Error in watcher "current" 
(found in component <slider>)
warn @ vue.js:525
run @ vue.js:1752
flushSchedulerQueue @ vue.js:1548
(anonymous) @ vue.js:477
nextTickHandler @ vue.js:426
vue.js:439 TypeError: Cannot read property '_uid' of undefined
    at VueComponent.current (vuetify.js:2842)
    at Watcher.run (vue.js:1746)
    at flushSchedulerQueue (vue.js:1548)
    at Array.<anonymous> (vue.js:477)
    at nextTickHandler (vue.js:426)
logError @ vue.js:439
backend.js:1 [vue-devtools] Ready. Detected Vue v2.1.7

**Comment by johnleider** [comment]
Make sure you are using Vue@2.1.6. Vuetify does not support Vue@2.1.7 yet.

**Comment by csik** [comment]
Thanks, got it. Sorry for the confusion.
