### ISSUE TITLE
[Feature Request] The tree view component is so necessary!

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#2600]
### New Functionality
Many other vue component libraries has this component!
like
-  `element ui` http://element-cn.eleme.io/#/en-US/component/tree
- `iview` https://www.iviewui.com/components/tree-en
and another material vue framework `quasar framework`
http://quasar-framework.org/components/tree.html
can do this work for vuetify? thx

### Improvements
I use v-list do this current,but is not perfect plan

### Bugs or Edge Cases it Helps Avoid
will generator tree-view component fast and perfect

**Comment by rosnaib11** [comment]
Up

**Comment by DrSensor** [comment]
Just maybe... use this as a basis
https://vuejs.org/v2/examples/tree-view.html

Some feature/demo that end user would like to have:
- [ ] Tree View inside Navigation Drawer
- [ ] Tree View inside Expansion Lists
- [ ] Tree View with Icon
- [ ] Tree View with Icon and Badges
- [ ] Tree View with Checkbox
- [ ] Tree View and Breadcrumbs (File Explorer Demo)

**Comment by auvansang** [comment]
Another nice sample for this feature:
http://ej2.syncfusion.com/15.4.23/demos/#/material/treeview/checkbox.html

**Comment by hyounoo** [comment]
Since there's no tree view component for vuetify, what other options do we have if you want to emerge trreview with other vuetify components as much as possible?

**Comment by Vincebe** [comment]
Same question @hyounoo 😄

**Comment by hyounoo** [comment]
@Vincebe I had to do it myself https://www.npmjs.com/package/v-treeview

**Comment by Vincebe** [comment]
Thanks a lot @hyounoo !

**Comment by aaarghhh** [comment]
Vooo Great! Thank you @hyounoo !

**Comment by jvbianchi** [comment]
Checkout this [post on veutify's medium](https://medium.com/vuetify/building-a-treeview-component-part-i-93d19733682f)

**Comment by Extarys** [comment]
Tree View from MetroUI looks awesome too: https://metroui.org.ua/treeview.html
