### ISSUE TITLE
[Feature Request] Provide a programatic way to use a confirmation dialog.

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#2602]
### New Functionality
Easily use a confirmation dialog that returns true/false in a promise so that we can continue/cancel actions.

I'm hoping I can do something like this:

    methods: {
        confirmDelete() {
            this.$vuetify.confirm('Are you sure you want to delete this?', options).then(confirmed => {
                if (confirmed) {
                    axios.delete(path).then(mutateState)
                }
            })
        }
    }

### Improvements
Right now, I'm attempting to use 1 dialog with a variable message from the VueX store. I also store the confirmation/cancellation callbacks on the store temporarily until the confirmation dialog is complete. When the user confirms/cancels, I call the relevant callback and clear the store variables. Finally, I call another mutation call to mutate the state.

This feels very long-winded. Perhaps there is a shorter way but not that I can find right now?

### Bugs or Edge Cases it Helps Avoid
It provides a simpler interface for using confirmation dialogs.

**Comment by KaelWD** [comment]
You can define your own implementation of that on the vue prototype: 

```js
Vue.prototype.$confirm = function myConfirmFunction (message, options) { ... }
```

**Comment by jaesung2061** [comment]
Ok, I've created a custom setup using promises. One semi-related question. I have a stateful drawer that uses a confirmation that shouldn't close after I confirm something. How can I prevent it from closing?

**Comment by KaelWD** [comment]
`<v-navigation-drawer :stateless="dialogIsOpen">`

**Comment by johnleider** [comment]
This is something that would be a great example to show on the docs, but not something we are going to bake into the framework. Thank you for the suggestion.

**Comment by eolant** [comment]
@jaesung2061 @johnleider
I've made a Gist with a confirm dialog component:
https://gist.github.com/eolant/ba0f8a5c9135d1a146e1db575276177d

**Comment by yariksav** [comment]
I wrote package https://github.com/yariksav/vuetify-dialog
it has prompt, confirm, notify messages and etc. Please look at it)
Demo: https://k2910xo07r.codesandbox.io/
