### ISSUE TITLE
[Bug Report] v-menu activator element is removed when activator slot is assigned to v-icon/v-avatar

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2604]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 7

### Steps to reproduce
Create a `v-menu` and assign the `activator` slot to a `v-icon` or `v-avatar`.

### Expected Behavior
The activator element should show.

### Actual Behavior
The activator element is not added to page making the menu unusable.
Instead an empty menu tag is added:
```
<div class="menu" style="display: inline-block;"></div>
```

### Reproduction Link
[https://codepen.io/anon/pen/OOvYvv](https://codepen.io/anon/pen/OOvYvv)

### Other comments
The behavior differs slightly depending on where you place the menus as you can see from the provided codepen. Also, I noticed if I add a menu with an icon before the menu with an avatar the last one shows. However, if I remove the one with the icon then the avatar one also is hidden. Very strange.

This issue seems loosely related to #2603. It appears that something is fundamentally wrong with how these components manipulate their slots causing different weird rendering issues.

If you add a wrapper element for the slot around the actual icon/avatar it works correctly, so it seems to be some wrong logic where it takes the children of the slot and not the slot itself.

If this is by design (requiring a nested element for the slot) it should be documented, but I don't think this is the intended behavior?

**Comment by jacekkarczmarczyk** [comment]
Duplicate https://github.com/vuetifyjs/vuetify/issues/2603#issuecomment-346297972

**Comment by amyngb** [comment]
What wrapper element are you adding to make it work?

**Comment by jacekkarczmarczyk** [comment]
It was a bug in Vue 2.5.4, you need to update it to 2.5.9
