### ISSUE TITLE
[Bug Report] v-checkbox component is not functional with value attribute

### ISSUE THREAD

**Issue by mr-july** [vuetifyjs/vuetify#2605]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.1
**Browsers:** Chrome 62.0.3202.75
**OS:** Linux x86_64

### Steps to reproduce
create v-checkbox component like one of this:
```
<v-checkbox :value="true" label="this checkbox should be checked"></v-checkbox>
<v-checkbox :checked="true" label="this checkbox should be checked"></v-checkbox>

```

### Expected Behavior
the checkbox should be checked, because the 'value' (or 'checked') attribute is set to `true`

### Actual Behavior
the checkbox is not checked

### Reproduction Link
[https://jsfiddle.net/mr_july/Lkx49q2L/](https://jsfiddle.net/mr_july/Lkx49q2L/)

**Comment by KaelWD** [comment]
Checkboxes use `input-value` as their model.

**Comment by dschreij** [comment]
Why exactly is this? the v-checkbox does have a v-model attribute, which suggests it uses the :value property and @input event mechanisms, which is how v-model is implemented.

**Comment by KaelWD** [comment]
Vue lets you change which prop and event the v-model uses: https://vuejs.org/v2/api/#model

Selection controls already use `value` to set their value, so something else had to be used for active state.
