### ISSUE TITLE
[Bug Report] Setting v-list-tile active state using v-model doesn't support v-bind directive

### ISSUE THREAD

**Issue by THLabs** [vuetifyjs/vuetify#2608]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
(see codepen link)
1. Create a `v-list` component with 1 or more `v-list-tile`s
2. Use a v-bind directive to programmatically set the active state of a `v-list-tile` (via v-model)

### Expected Behavior
The addition of `list__title--active` class, the same as when you set it via a variable:
```
<a class="list__tile list__tile--link list__tile--active" ... >
```

### Actual Behavior
While the expression is correctly evaluated, it is then just added as an attribute of the resulting link:
```
<a v-model="true" class="list__tile list__tile--link" ... >
```

### Reproduction Link
[https://codepen.io/thlabs/pen/gXzOeE](https://codepen.io/thlabs/pen/gXzOeE)

**Comment by KaelWD** [comment]
Codepen looks fine to me
![image](https://user-images.githubusercontent.com/16421948/33127236-c0901dde-cfdb-11e7-8a50-eeb7526ddbe7.png)

**Comment by THLabs** [comment]
That's odd, because it's definitely broken for me. I've tried it on a colleague's machine, and he get's the same behaviour I do:
![image](https://user-images.githubusercontent.com/1153879/33127690-7f7e0900-cf81-11e7-8ffd-1c2580eff2b2.png)

**Comment by KaelWD** [comment]
Ok wtf, I just checked again and now I'm getting the same thing as you
![image](https://user-images.githubusercontent.com/16421948/33128072-2e1ff376-cfdf-11e7-9259-0f5805542d4e.png)

**Comment by THLabs** [comment]
Ah yeah, sorry - think codepen autosaved while I was playing around with it.

Great, thanks - the `:value` thing works - is it worth adding this to the API docs for `v-list-tile`? I hadn't realised that was an option?

**Comment by jacekkarczmarczyk** [comment]
@KaelWD I think he has changed the codepen:

```html
        <v-list-tile @click="" :v-model="1==1">
```

**Comment by KaelWD** [comment]
It's part of vue - `v-model="somevar"` is the same as `:value="somevar" @input="somevar = $event"`
