### ISSUE TITLE
[feature] Snackbar container 

### ISSUE THREAD

**Issue by breadlesscode** [vuetifyjs/vuetify#261]
Hi,

first. Awsome work! But I miss a snackbar container. 

Something like this: https://josephuspaye.github.io/Keen-UI/#/ui-snackbar

**Comment by johnleider** [comment]
I'm not sure what you are asking/suggesting?

**Comment by dohomi** [comment]
@breadlesscode are you looking for this: https://vuetifyjs.com/components/snackbars ?

**Comment by breadlesscode** [comment]
No. I mean a container for the snackbar. If you have a container for the
snackbar the placing is mutch easier.

Look again at Keen Ui

2017-03-25 0:33 GMT+01:00 Dominic Garms <notifications@github.com>:

**Comment by dohomi** [comment]
I think our snackbar is doing the exact thing you are asking. the snackbar of Keen-UI has the only difference, that its attachable to a different parent. Check out the demo of the Keen-Ui playground. @johnleider do you think we should allow defining the parent of a snackbar?

**Comment by johnleider** [comment]
I think we can just have an absolute option. That should solve this.
