### ISSUE TITLE
[Feature Request] Allow select autocomplete slot="item" to have custom "empty" template, enabled

### ISSUE THREAD

**Issue by cassvail** [vuetifyjs/vuetify#2610]
### New Functionality
When no results are found in a select autocomplete the slot="item" template is rendered as disabled.
if a user overrides the template it should be enabled to allow custom elements and behaviour inside the template.
Current situation: Type "D" in the select input https://jsfiddle.net/aj1sek2v/1/

### Improvements
The user will be able to add custom active elements such as buttons or links

### Bugs or Edge Cases it Helps Avoid
None

**Comment by jacekkarczmarczyk** [comment]
Use `no-data` slot for this:

```html
  <template slot="no-data">
    <v-list-tile>
        <v-list-tile-content>
          Not found <a href="#">Create New</a>
        </v-list-tile-content>
    </v-list-tile>
  </template>
```

**Comment by cassvail** [comment]
That was what I found in the docs examples.
I found the slot you suggested it in the API box. Thanks!
