### ISSUE TITLE
[Feature Request] draggable mixin

### ISSUE THREAD

**Issue by paganaye** [vuetifyjs/vuetify#2614]
### New Functionality
Allow the user to manually change the order of elements in a list.

### Improvements
At this stage you got the option to use vue.draggable.
If you look in detail though vuejs and the sortable library it is based on are fighting each other.
I made another alternative here:
https://codepen.io/paganaye/pen/ZaJVwp

this is functionnal but it is a hack. it would be better from within vuetify itself

### Bugs or Edge Cases it Helps Avoid
drag dropping is a bit fiddly in my sample. It would be better if it was working on the full line and applyable to more vuetify components.

**Comment by nekosaur** [comment]
I feel like a draggable feature might be outside the scope of Vuetify. @vuetifyjs/collaborators thoughts?

If we do anything I'd prefer making integration with existing 3rd party libraries as painless as possible.

**Comment by johnleider** [comment]
I'm okay with an integration example, not a from scratch feature.

**Comment by johnleider** [comment]
This should be posted on the docs as it is where it would be implemented. 
Thank you for your contribution.
