### ISSUE TITLE
[Bug Report] Time picker reverting to current time with clearable text field

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#2616]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
1) Select a new time from the time picker
2) Click the clear button on the input

### Expected Behavior
Input value set to null

### Actual Behavior
Input value set to current time

### Reproduction Link
[https://codepen.io/anon/pen/QOrMrv](https://codepen.io/anon/pen/QOrMrv)

### Other comments
This only happens if the v-model has an initial value

**Comment by Dylan-Chapman** [comment]
Just wanted to update that this issue isn't entirely consistent, but I can't figure out the exact cases for when it happens. As far as I can tell, it only happens when the newly-selected time is a "PM" time. It works properly when the newly-selected time is "AM" though?

**Comment by Dylan-Chapman** [comment]
Just wanted to comment that this is still a problem even after the most recent picker updates. You can view this codepen [https://codepen.io/anon/pen/QOrMrv](https://codepen.io/anon/pen/QOrMrv) to see it with the latest version of Vuetify.

**Comment by AlexKovynev** [comment]
1.0.0 beta.4 work correctly, maybe it's a new bug connected to allowed properties.
