### ISSUE TITLE
Vuetify - how to make pagination? (help wanted)

### ISSUE THREAD

**Issue by pirmax** [vuetifyjs/vuetify#2618]
I want use pagination from **Vuetify** framework for **VueJS**.

**Pagination component from Vuetify:**

    <v-pagination :length="pagination.total / 5" v-model="pagination.page" :total-visible="pagination.visible"></v-pagination>

I want execute function from **methods** when user click on button. I want get the page number and execute function with this page number.

**Code from getItems from methods:**

    this.pagination.page = response.body.page
    this.pagination.total = response.body.total
    this.pagination.perPage = response.body.perPage

**Data:**

    data () {
      return {
        items: [],
        pagination: {
          page: 1,
          total: 0,
          perPage: 0,
          visible: 7
        }
      }
    }

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/azFN8.png

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
