### ISSUE TITLE
[Enhancement] rtl support

### ISSUE THREAD

**Issue by DJafari** [vuetifyjs/vuetify#262]
do you plan to support rtl languages ?

**Comment by johnleider** [comment]
I'd really need an example of what you are asking for, excuse my ignorance.

**Comment by DJafari** [comment]
for example this is rtl material design version :

http://mdl.rtlcss.com/

**Comment by johnleider** [comment]
I have some unfortunate news. While Vuetify most certainly **will** support RTL, it will not make v1.0 release.  The form components were going to create a difficult set of changes that would be most suited for what v1.1 is (Form patch). It would of added too much potential risk for issues on 1.0 release next month.

While this feature is being worked on, one of the community members, @Devo has started to work on an implementation in the mean time, https://github.com/devmedoo/vuetify. I've opened a channel on the community specific for RTL discussion and invite everyone to join, https://discord.gg/C4j9SKg.

**Comment by zahrahajilary** [comment]
please release RTL version

**Comment by johnleider** [comment]
We will, just not for 1.0.

**Comment by Pezhvak** [comment]
+1 really need RTL support!

**Comment by familysoltani** [comment]
please release RTL version sooner

**Comment by johnleider** [comment]
RTL is a very large task and is something we take very seriously. There is no point in releasing an implementation that is going to not be up to par or cause potential issues in the long run.

We hear your voices and we will continue to work on this.

**Comment by Pezhvak** [comment]
can i be any help? @johnleider

**Comment by DJafari** [comment]
@johnleider currently you are in v1.0.4 but any news from rtl support ? :-(

**Comment by johnleider** [comment]
These are patches. RTL won't come until minor releases. The input refactor
for v1.1 is the start of the RTL conversion.

**Comment by ArsanGamal** [comment]
Adding `dir="rtl"` attribute to the `v-data-table` solves the issue for me but with some small customizations

**Comment by kouchakyazdi** [comment]
@ArsanGamal 
it won't

**Comment by meyt** [comment]
Another try https://meyt.github.io/vuetify-rtl-style/
https://github.com/meyt/vuetify-rtl-style

P.S: Currently i have no issue and works fine, but still its an Alpha!

**Comment by johnleider** [comment]
The first round of RTL updates is in v1.1

**Comment by alireza4050** [comment]
There is a much simpler way to accomplish RTL support:
1. Don't have any direction dependent __inline__ css styles like margin-left, translateX, etc. put them in classes instead if possible.
2. Add postcss-rtl plugin

Then all you need is this:
```bash
npm i -D postcss-rtl
```
and add this to .postcssrc file or postcss section in package.json:
```json
    "plugins": {
     ...
      "postcss-rtl": {}
    }
```

**Comment by johnleider** [comment]
If you have better ways to accomplish this, please reach out to me in our community.

**Comment by osman-mohamad** [comment]
I have started to use vuetify to build simple pwa mobile app for arabic (rtl language) customers . and I need to know is the first round of vuetify supporting rtl is enough for production ready applications ?

**Comment by johnleider** [comment]
While there is always room for improvement, at this point in time we have fully added RTL support to the framework.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
