### ISSUE TITLE
[Bug Report] Selection Menu overlaps input field on v-select

### ISSUE THREAD

**Issue by jrast** [vuetifyjs/vuetify#2626]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
- open the code pen
- note the configuration of the select: the most important are `single-line`, `autocomplete` and `hide-details`
- make a selection in the select field

### Expected Behavior
The menu should not overlap the textfield. If the "Hide details on v-select" checkbox is unchecked, the menu behaves as expected.

### Actual Behavior
The menu overlaps the textfield, hiding the actual input. 

### Reproduction Link
[https://codepen.io/jrast/pen/NwMaZE?editors=1010](https://codepen.io/jrast/pen/NwMaZE?editors=1010)

**Comment by KaelWD** [comment]
Regression of #2377, looks like the fix for that only applied to non-autocomplete selects for some reason.

**Comment by jrast** [comment]
The menu also overlaps the input field if there is not enough space below the input to show the menu. I think the menu should never overlap the input, specialy if autocomplete is enabled. Should I create another issue for this?

**Comment by johnleider** [comment]
@jrast create a new issue please
