### ISSUE TITLE
[Bug Report] Temporary navigation drawer scroll issue

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2629]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.6
**Browsers:** Chrome 62.0.3202.94
**OS:** Linux x86_64

### Steps to reproduce
Scroll to bottom of the page and click togle

### Expected Behavior
Content in navigation drawer should not be scrolled up

### Actual Behavior
Content in navigation drawer is not visible because it scrolled up

### Reproduction Link
[https://codepen.io/darkside73/pen/GOGXMa](https://codepen.io/darkside73/pen/GOGXMa)

**Comment by jacekkarczmarczyk** [comment]
Use `fixed` prop instead of `absolute`
https://codepen.io/anon/pen/wPXEZW
