### ISSUE TITLE
routing from v-menu results in a "TypeError: Cannot read property 'removeEventListener' of null"

### ISSUE THREAD

**Issue by edoecohen** [vuetifyjs/vuetify#263]
If I have 'v-menu' in a component and I use Vue Router to load a different component, then I get the following error:

![image](https://cloud.githubusercontent.com/assets/952779/24306806/1903c0e6-107f-11e7-9997-736e3e044d13.png)

"TypeError: Cannot read property 'removeEventListener' of null"

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
