### ISSUE TITLE
[Bug Report] Browser autofill doesn't work for text fields in forms?

### ISSUE THREAD

**Issue by praveenpuglia** [vuetifyjs/vuetify#2636]
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.8
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
- Try entering any email and password and hit login. 
- The browser asks to save email and password. Save it.  
- Next time you come back and try the Email field the browser autofill should work but it doesn't.
- It does work for the password field though.

### Expected Behavior
The text fields should support browser autofill.  

### Actual Behavior
Browser autofill doesn't work

### Reproduction Link
[https://codepen.io/praveenpuglia/pen/aVKgYm](https://codepen.io/praveenpuglia/pen/aVKgYm)

**Comment by KaelWD** [comment]
Autofill requires the inputs to have a `name`, which is why the password works but the email doesn't.

**Comment by praveenpuglia** [comment]
That's something I learned. Thanks so much. :)

**Comment by KaelWD** [comment]
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
