### ISSUE TITLE
[Bug Report] v-radio not found

### ISSUE THREAD

**Issue by Dream5561** [vuetifyjs/vuetify#2637]
**Versions and Environment**

Vuetify: 0.17.2
Nuxt: 1.0.0-rc11

**Steps to reproduce**
Using v-radio-group and v-radio apperens error _[Vue warn]: Injection "radio" not found_
As an example, I used: 
` <v-radio-group v-model="test" column>`
      ` <v-radio label="Label 1" value="0"></v-radio>`
       ` <v-radio label="Label 2" value="1"></v-radio>`
        `<v-radio label="Label 3" value="2"></v-radio>`
 `</v-radio-group>`

On versions 0.17.1 everything works correctly...

**Comment by nekosaur** [comment]
This is because v-radio-group and v-radio uses optional injects which is a feature introduced in vue 2.5.0, while nuxt 1.0.0-rc11 depends on vue 2.4.2

**Comment by nekifirus** [comment]
Any way to solve this?

**Comment by nekosaur** [comment]
Make sure you're actually using vue 2.5.0 or higher

**Comment by nekifirus** [comment]
@nekosaur I'm use 
Vuetify: 0.17.2
Nuxt: 1.0.0-rc11
as ts.

Correct way to change VRadio component in my current build with component from previous version of Vuetify? Or is there any way to change injection type of VRadio for nuxt`s verion of Vue?

**Comment by nekosaur** [comment]
As I said, you need to make sure you're using vue 2.5.0 or higher. Since nuxt currently depends on a lower version of vue, you will need to force it in your package.json file most likely.

**Comment by ram-you** [comment]
Hi @nekosaur 
Vuetify 1.0.0.6 beta + Nuxt 1.3.0 (depends on vue  2.5.x)  and can't inject v-radio.
Help please

**Comment by nekosaur** [comment]
@ram-you If you need help please go to our chat at https://chat.vuetifyjs.com

**Comment by gomezmark** [comment]
@nekosaur 

Hi Sir,
im using starter-template on nuxt, but eventually i added vuetify.
and some components like v-select is not rendered as from the sample on the site.

please help. 

TIA

**Comment by nekosaur** [comment]
Please do not comment on closed issues. If you have a problem. Join our [chat](https://chat.vuetifyjs.com) to get help, or create a new issue using the [issue creator](https://issues.vuetifyjs.com)
