### ISSUE TITLE
[req] Option to translate 'of' text in data-table component

### ISSUE THREAD

**Issue by leyvicaz** [vuetifyjs/vuetify#2638]
Can you do some option like 'rows-per-page-text' in v-data-table component for 'of' text in pagination?
Thanks!

Same problem [#1553](https://github.com/vuetifyjs/vuetify/issues/1553)

vuetify/src/components/VDataTable/mixins/foot.js
<img width="1061" alt="metodotranslate" src="https://user-images.githubusercontent.com/2257768/33231120-793c9da0-d1b5-11e7-81ea-2fed5b9324de.png">

**Comment by jacekkarczmarczyk** [comment]
You can use the `pageText` slot *undocumented though`

https://codepen.io/anon/pen/aVjOVM?&editors=101
