### ISSUE TITLE
[Feature Request] Add input event to carousel that triggers when the user changes the slide manually

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#2639]
### New Functionality
Detect when the user changes a slide manually vs. when it changes automatically based on the interval

### Improvements
You currently cannot detect whether the slide changed because of the interval or because the user clicked on the controls

**Comment by nekosaur** [comment]
In what scenarios is it necessary to distinguish between these?

**Comment by smares** [comment]
I agree this is a very special scenario where I kind of needed it. 😄

I have an image gallery that uses a carousel to cycle through images. Below is a paginated grid of thumbnails. Whenever the image in the carousel changes, it highlights the matching thumbnail. If the thumbnail is on a page that is not visible, it also switches to the right thumbnail page.

The scenario where I needed this is the following: If the user is browsing through the thumbnails and changes to a different page, when the carousel cycles to the next image it will **not** switch the thumbnail pages because that would disturb the user browsing the thumbnails. If the user didn't change thumbnail pages for 10 seconds, the regular behavior would kick back in and the carousel would also switch thumbnail pages. What I wanted to do additionally is when the user manually changes the large image of the carousel by pressing on the arrows, that should immediately also restore the behavior where the carousel syncs the highlight of the thumbnails. For that I need an input event for the carousel to know that the user manually triggered the carousel to display the previous / next image.

**Comment by KaelWD** [comment]
Any reason just listening for a click wouldn't work?

**Comment by smares** [comment]
Well, click is pretty generic, one can click anywhere inside the control without causing it to cycle images.

**Comment by nekosaur** [comment]
Yes, but the MouseEvent will tell you what element has been clicked.

**Comment by smares** [comment]
Thanks, that will do in my case! :)
