### ISSUE TITLE
[Bug Report] V-Select Combobox V-Model value changes on focus blur 

### ISSUE THREAD

**Issue by CarbonFactory** [vuetifyjs/vuetify#2645]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Firefox 56.0
**OS:** Windows 10

### Steps to reproduce
1. Click the Select
2. While the select has teh focus, v-model has categoryId as value. On focus blur, it changes to Name 

### Expected Behavior
V-Model should have the value from the property defined in the `item-value` of V-Select

### Actual Behavior
V-Model has the value from the property defined in the `item-text` of V-Select

### Reproduction Link
[https://codepen.io/anon/pen/YEjaQZ?editors=1010](https://codepen.io/anon/pen/YEjaQZ?editors=1010)

**Comment by johnleider** [comment]
So this is actually not a bug, but a failure on my part as far as documentation. **combobox** is the single select equivalent of **tags**. Currently, **tags** and **combobox** only support primitive values.

![image](https://user-images.githubusercontent.com/9064066/33339552-85911ede-d447-11e7-9e1b-21f045728f02.png)
