### ISSUE TITLE
[Feature Request] Make SelectBox component local to div instead of global

### ISSUE THREAD

**Issue by ashwinkshenoy** [vuetifyjs/vuetify#2646]
### New Functionality
Targeting the selectbox in css becomes difficult. Now if we add select box it gets added after div 'app' class, which becomes difficult in targeting the popup of selectbox. Either make the selectbox popup local to its parent div or add content-class option to selectbox!

### Improvements
no workaround available at the moment

### Bugs or Edge Cases it Helps Avoid
any class we add to select box options, it gets added globally

**Comment by jacekkarczmarczyk** [comment]
There is `content-class` prop for `v-select`
![image](https://user-images.githubusercontent.com/15625235/33261688-3e54dbac-d396-11e7-97d9-1e9b5c380858.png)
