### ISSUE TITLE
[Feature Request] Request for Vertical Slider Capability

### ISSUE THREAD

**Issue by jfuehner** [vuetifyjs/vuetify#2647]
### New Functionality
Would love to have the ability to make a slider component vertical. The use-case would be to provide users with a slider for zooming in/out similar to the capabilities Google Maps provide with their zooming slider.

I tried simply applying a css transform rotating the control 90 degrees but the slider movement wasn't as expected.

### Improvements
n/a

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by mattnathan** [comment]
I would also like this, my usecase is for a vertical volume slider.

**Comment by HugoCrd** [comment]
Hi! 
This would be a great enhancement ;)

**Comment by theraudmickael** [comment]
I would also like this for zoom slider :)

**Comment by AMontagu** [comment]
+1

**Comment by simongcc** [comment]
thumb up 👍

**Comment by mido5219** [comment]
I'm trying to make a volume slider for a music player and I would really love to have this feature.

**Comment by graham-sportsmgmt** [comment]
We need vertical sliders too.  Thanks!

**Comment by nekosaur** [comment]
Fixed in #6424
