### ISSUE TITLE
[Feature Request] Get the current item displayed in Carousel

### ISSUE THREAD

**Issue by dipu-bd** [vuetifyjs/vuetify#2651]
### New Functionality
I can display detail information about the carousel item

### Improvements
Will allow me to use vuetify's carousel instead of using another library

### Bugs or Edge Cases it Helps Avoid
Improves flexibility of the carousel components

**Comment by dipu-bd** [comment]
I can just use v-model. Did not see it clearly, my bad

**Comment by andrewharvey** [comment]
For the benefit of others, here is an example:

```js
<v-carousel v-model="carouselIndex">
    <v-carousel-item v-for="(src,i) in images" :src="src" :key="i"></v-carousel-item>
</v-carousel>
<span>Current Index: {{carouselIndex}}</span>
```

**Comment by amanrathore10** [comment]
Is carouselIndex a predefined attribute/property or we need to define it into the data?

**Comment by amanrathore10** [comment]
carouselIndex is not working in my case @andrewharvey . I want to get the current index of active slide and then push to a different route if that carousel item is active.

**Comment by jacekkarczmarczyk** [comment]
Ppease do not comment closed issues. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
