### ISSUE TITLE
[Bug Report] Dialog not scrollable in IE11

### ISSUE THREAD

**Issue by jrast** [vuetifyjs/vuetify#2654]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.8
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Open the dialog in IE11

### Expected Behavior
The dialog should be scrollable, as in Chrome, Edge, ...

### Actual Behavior
The dialog is not scrollable and no scrollbar is visible.

### Reproduction Link
[https://codepen.io/jrast/pen/gXdxXQ?&editors=101](https://codepen.io/jrast/pen/gXdxXQ?&editors=101)

### Other comments
I could not reproduce the issue in the codepen because some polyfills are missing. I discussed this with @johnleider in the chat and we think it is a issue, even if the pen is not working right away.

**Comment by KaelWD** [comment]
Codepen works fine with the correct polyfills: https://codepen.io/anon/pen/zPeavx?&editors=101

**Comment by jrast** [comment]
I updated the pen with the correct polyfill. And it seems that I have fiddeled around with the pen after I have created the issue to find a solution.

It works if a fixed height is given for the v-card-text, like `<v-card-text style="height: 300px;">`. If no height is given, it's broken. I have adjusted the original pen. I would expect that no fixed height must be given, and in Chrome it works without the fixed height.

**Comment by everhardt** [comment]
I found the same thing and fixed it with the following hack.
In the template:
```
<v-card-text :style='`height: ${textHeight}px;`'>
```
In the `computed`-section:
```
textHeight() {
  return window.innerHeight - 200;
},
```

**Comment by KaelWD** [comment]
This is caused by the card having `height: auto` for some reason

**Comment by darylteo** [comment]
@KaelWD @johnleider ran into similar problem on IE11 and Vuetify 1.0.0 (1.0.1 and 1.0.2)

Hacked it by putting height="100vh" on v-card. I can only assume that height="100%" on IE11 does not mean the same thing. Seems to work. 

Regards,
Daryl
