### ISSUE TITLE
[Bug Report] v-menu not opening if route components contain its own v-app instance

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2655]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 7

### Steps to reproduce
I am using different layouts for different routes. For simplicity lets say a login page has an "empty" layout with just the login box and a dashboard page contains navigation drawer, toolbar, etc.

Because these components do not share anything in common they have their own `v-app` root. The components are assigned to routes in vue-router and rendered with a `<router-view>`.

When navigating from one route to the other (login => dashboard), the `v-menu` in the toolbar does not work. If I have a transition for the route change, the menu does not open at all. If I don't use a transition the menu opens, but does not close on "click outside".

This issue may affect other Vuetify components as well but I only noticed it for menus so far.

### Expected Behavior
Everything to work as normal even if each route component contains its own v-app instance.

### Actual Behavior
Menus does not open.

### Reproduction Link
[https://codepen.io/anon/pen/ZaMvQY](https://codepen.io/anon/pen/ZaMvQY)

### Other comments
The bug is not really related to vue-router at all. That is just how I discovered it and I think it is a likely use case. I have created a simplified codepen here that shows the same problem but without vue-router: https://codepen.io/anon/pen/qVMpoV

**Comment by sindrepm** [comment]
I have done some debugging and it seems the issue is that the `mounted` hook in the `detachable` mixin (which `v-menu` uses) is called before the DOM has updated because of the transition delay. Thus, the menu content is inserted under the wrong `[data-app]` element.

The issue with closing the menu is similar. The `click-outside` event listener gets bound to the "old" app element because the DOM hasn't updated yet when the directive's `bind` hook is called.

I have been able to make it work by making these changes:

1. Modify [detachable.js](https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/detachable.js#L13) so that the content element is inserted to DOM after booted instead:

```
watch: {
    isBooted () {
        this.initDetach()
    }
}
```
This will add the detached element to DOM after the first time the component is activated.

2. Modify [click-outside.js](https://github.com/vuetifyjs/vuetify/blob/master/src/directives/click-outside.js#L61) so that `componentUpdated` hook is used instead and add event listener if "app" has changed.

```
let currentApp = null

export default {
  name: 'click-outside',

  componentUpdated (el, binding, v, oldVnode) {
    const onClick = e => directive(e, el, binding, v)
    // iOS does not recognize click events on document
    // or body, this is the entire purpose of the v-app
    // component and [data-app], stop removing this
    const app = document.querySelector('[data-app]') ||
      document.body // This is only for unit tests

    if (app === currentApp) {
      return
    }
    app.addEventListener('click', onClick, true)
    el._clickOutside = onClick
    currentApp = app
  },

  unbind (el) {
    const app = document.querySelector('[data-app]') ||
      document.body // This is only for unit tests
    app && app.removeEventListener('click', el._clickOutside, true)
  }
}
```

This feels extremely hacky, though. I wonder if this worked before [this PR](https://github.com/vuetifyjs/vuetify/pull/2470) was merged?

**Comment by KaelWD** [comment]
Or you could just use `mode="out-in"` on the transition.

**Comment by sindrepm** [comment]
@KaelWD that worked! Should have thought of that.. Still, do you think there is room for better support for this scenario in Vuetify? Perhaps always select the last app element if there are multiple. Or if there is a better way to obtain the true parent app without querying the DOM directly.

I realize this might be an edge case, though, so as long as `mode="out-in"` does the trick I am happy with that.

**Comment by nekosaur** [comment]
Is there any specific reason why you're using multiple `v-app`s?

**Comment by sindrepm** [comment]
@nekosaur Because I need some pages to have a completely different layout (i.e. no nav drawer, toolbar, etc) and would rather create those components as separate `v-app`'s instead of toggling lots of items conditionally. I am also using it to toggle a "splash screen" while the app is loading initially.

I cannot place the `v-app` in the common parent as the child component template can only contain one root element and the `v-navigation-drawer`, `v-toolbar` and `v-content` needs to be immediate children of the `v-app`, or...?.

**Comment by KaelWD** [comment]
No, they can be pretty much anywhere. You'll still need to use `out-in` though otherwise the transition is jumpy. https://codepen.io/anon/pen/yPRrmY

**Comment by sindrepm** [comment]
@KaelWD ah, that helps a lot. I never actually tried that, just assumed the layout had to use this exact structure for the positioning etc to work correctly.
