### ISSUE TITLE
onclick is not working on v-checkbox

### ISSUE THREAD

**Issue by sumit366** [vuetifyjs/vuetify#2658]
Onclick event is working fine with v-checkbox if i click on checkbox but not working or generating events if click on label. The checkbox get selected on click of label but onclick function not getting called.

**Comment by jacekkarczmarczyk** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.

**Comment by ericjohnston** [comment]
Experienced same behavior.  Opened a new issue using template with repo. #2673
