### ISSUE TITLE
[Feature Request] VDatatable .:. Sorting on multiple columns

### ISSUE THREAD

**Issue by jdriesen** [vuetifyjs/vuetify#2659]
### New Functionality
Will allow the user to sort on multiple columns...
e.g. it can be interesting to sort on person.lastname AND on person.firstname....

### Improvements
mmm ... don't think there is a workaround at this moment.

### Bugs or Edge Cases it Helps Avoid
This feature request is just a usability improvement...

**Comment by marcoiai** [comment]
How the hell is this a usability improvement? For some people looking through a table is a must multi ordering...

**Comment by aljaxus** [comment]
👍 very nice
![very nice - gif](https://share.aljaxus.eu/2018-12-11/11%3A12%3A07pm-tenor.gif)

**Comment by grishnyakov** [comment]
temporary solution
https://codepen.io/grishnyakov/pen/mawOXg

**Comment by blalan05** [comment]
Available in the 2.0 alpha
