### ISSUE TITLE
[Bug Report] V-Select scrolling behaviour

### ISSUE THREAD

**Issue by asiFarran** [vuetifyjs/vuetify#2660]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 7

### Steps to reproduce
Give the select component a largish number of items (anything above 50 will do).

Open the select and start scrolling

### Expected Behavior
The scrollbar thumb should be of constant height (representing the relationship between the overall height of the item list and the height of the popup element), and scrolling should be fluid and linear

### Actual Behavior
The scrollbar's thumb starts off too high and as you begin to scroll, changes it's height and jumps to a different location on its track - basically disappearing from under the mouse cursor - thus leading to a jittery and uneven scrolling action making it almost impossible to reach the bottom of the list

### Reproduction Link
[https://codepen.io/anon/pen/RjYmJb?editors=1010](https://codepen.io/anon/pen/RjYmJb?editors=1010)

**Comment by KaelWD** [comment]
v-select lazy-loads items 20 at a time for performance reasons. This could be done with a set number of items at some point in the future though.

**Comment by asiFarran** [comment]
I understand the perf concern but shouldn't the UX concern take precedence here? 

The current strategy makes the component practically unusable when in effect (i.e over 20 items) so what's the point of having nice perf in a context that no-one would ever use unless they like to hear their users complain.

**Comment by cars10** [comment]
Yeah, that behaviour is really annoying and not at all user friendly. Any updates on that?

**Comment by KaelWD** [comment]
It was removed in 1.1 bit had to be added back because of the massive performance impact of you have a lot of records. We're planning to add proper list virtualisation at some point, but probably not in 1.1

**Comment by cars10** [comment]
How about changing it into a prop? In my current project for example I have a fixed amount of about 150 records, would be cool if I could set the value myself.

**Comment by cars10** [comment]
Great, thank you! Using `auto` will indeed render the whole list, guess i missed that in the documentation. Sadly this seems to break `max-height` (now having no effect), but i will use it anyway. Thanks!

**Comment by Webifi** [comment]
I think this could be solvable if we could easily change the default value of 20 for VSelect.lastItem to something else via a prop. 

Could it be as simple as just adding something like this to VSelect.ts?:

```
props: {
  ...
  defaultLastItem: Number,
  ...
},
mount () {
  ...
  if (this.defaultLastItem > this.lastItem) this.lastItem = this.defaultLastItem
  ...
},
watch: {
  ...
  defaultLastItem (v) {
    if (v > this.lastItem) this.lastItem = v
  }
  ...
}
```

**Comment by avrtau** [comment]
Is there any news on this issue? Is there a work-around?

**Comment by londos** [comment]
Updating `:auto="true"` to `:menu-props="{ auto: true }"` worked for me.

**Comment by johnleider** [comment]
This is pending the completion of #10944. Otherwise it will be bumped.

**Comment by VitaliyDemchuk** [comment]
`:menu-props="{ auto: true }"` dont work in version `1.5.22`. In which version does it work?

**Comment by avrtau** [comment]
> `:menu-props="{ auto: true }"` dont work in version `1.5.22`. In which version does it work?

Works on Vuetify 2.2+

**Comment by nikalsh11** [comment]
> Updating `:auto="true"` to `:menu-props="{ auto: true }"` worked for me.

Thanks. 

This also solved another issue with v-select where the scrollbar would occasionally not function at all. Can confirm this works in Vuetify 2.4.2.

**Comment by hosseinmirhosseini76** [comment]
I fixed this by removing my `height` style on the page :)

**Comment by halimb** [comment]
`:menu-props="{ maxHeight: 'none' }"` worked for me

**Comment by handhikadj** [comment]
i'm having this on v2.5.8

**Comment by bifshteks** [comment]
That's really a problem, because in case, when the height of menu is large enough to include 20 items visible on the screen, 
the scrollbar does not appear, so user have to ways to scroll (thus, lazy loading will never load the rest of items)

**Comment by johnleider** [comment]
> That's really a problem, because in case, when the height of menu is large enough to include 20 items visible on the screen, the scrollbar does not appear, so user have to ways to scroll (thus, lazy loading will never load the rest of items)

This is absolutely a flaw in the system. I did it this way as a stop gap to not having a virtual-scroll component and it sort of stuck that way over the years.

No worries though, it is something we are addressing for Vuetify 3.

**Comment by juhasev** [comment]
Hi guys, the only way to fix the scrollbar issues  is to set the menu props as follows:
```
:menu-props="{maxHeight: '80%', overflowX: true}"
```
Yeah it is kind of weird that you need to add overflowX: true.

**Comment by jsodeman** [comment]
As a related note, the lazy loading creates problems when doing e2e testing like cypress because the value you want might not be rendered yet. While I understand the performance issue, having to add `:menu-props="{ auto: true }"` to every v-select in our app so we can test is not fun.

**Comment by jhonpridedev** [comment]
Any update? The problem persists with 80 elements in "vuetify": "^3.4.6", is this bug still being worked on? Regards

**Comment by johnleider** [comment]
> Any update? The problem persists with 80 elements in "vuetify": "^3.4.6", is this bug still being worked on? Regards

Provide a reproduction and create a new issue, please do not comment on closed issues.
