### ISSUE TITLE
How do I use the icons!?

### ISSUE THREAD

**Issue by pentool** [vuetifyjs/vuetify#2663]
I'm trying to use the icons (v-icons) in my basic project. So I go to the icon section in the documentation at https://vuetifyjs.com/components/icons. Twirl open the very first example (#1) to look at its template. It shows: `<v-icon>home</v-icon>`.

When I put that line into my project, I don't see any icon. I thought I need to install the material design icon set (even though the documentation does not say so). So I went ahead and installed it using `npm install material-design-icons`. However, their documentation page doesn't say anything about how to use it beyond the `npm install` stuff. What do I include/import into my project, if anything? I tried `import '../node_modules/material-design-icons'` but the icons still don't show up.

What am I missing in order to use the basic icons that are used in the v-icons documentation section? Thanks.

**Comment by jacekkarczmarczyk** [comment]
You must add the fonts to your index.html
And this board is strictly for bug reports or feature request, if you have any questions visit the official discord channel http://chat.vuetifyjs.com

**Comment by salomaaharri** [comment]
"npm install material-icons" helped me

**Comment by gnulnx** [comment]
The documentation could certainly be improved in this area.
If you are here and still confused add this to your index.html file

```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

Cheers

**Comment by Stoom** [comment]
The above is for material icons, not MDI.  I'm also very confused about MDI icons... there is  no good example available.

**Comment by nekosaur** [comment]
Please do not comment on closed issues. If you need help, join us at https://chat.vuetifyjs.com.

Instructions on using MDI can be found on their website https://materialdesignicons.com/getting-started
