### ISSUE TITLE
[Feature Request] Cannot click a link in v-checkbox's label without checking the checkbox

### ISSUE THREAD

**Issue by cappe** [vuetifyjs/vuetify#2669]
### New Functionality
Quite typical use case would be accepting terms of contract by checking a checkbox. Usually the checkbox's label includes a link to terms so this feature would allow the link to be opened without checking the checkbox.

Example: https://codepen.io/anon/pen/jaejop?editors=1010

### Improvements
A link can be implemented next to label but all the styles need to be implemented manually. This enhancement would allow adding a link in the label without the need of writing some hackish styles.

### Bugs or Edge Cases it Helps Avoid
It would allow opening a link without checking the checkbox.

**Comment by KaelWD** [comment]
Use `@click.stop` on the link.

**Comment by cappe** [comment]
Good call, thanks! And kudos for the fast reply. Could I have found this information from somewhere? I browsed and searched through the documentation but had no luck.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/events.html#Event-Modifiers
