### ISSUE TITLE
[Bug Report] v-bottom-sheet :scrollable property is not setting v-card-text overflow

### ISSUE THREAD

**Issue by TheOrdovicianGoat** [vuetifyjs/vuetify#2671]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.4.2
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.12.6

### Steps to reproduce
Attempt to set the v-card-text height and observe scrollability.

### Expected Behavior
The card should scroll

### Actual Behavior
Doesn't scroll

### Reproduction Link
[https://codepen.io/anon/pen/VrVjYO](https://codepen.io/anon/pen/VrVjYO)

**Comment by nekosaur** [comment]
scrollable will no longer be available in vuetify 1.*
