### ISSUE TITLE
[Feature Request] DateTimePicker

### ISSUE THREAD

**Issue by cn-xufei** [vuetifyjs/vuetify#2674]
# New Functionality

Components  —  Pickers

Hope to choose the time while choosing the date

Element.io has a similar feature http://element-cn.eleme.io/#/zh-CN/component/datetime-picker

I think it'd be cool if this was available in vuetify too:clap:

**Comment by jacekkarczmarczyk** [comment]
duplicate of https://github.com/vuetifyjs/vuetify/issues/459
