### ISSUE TITLE
[Bug Report] Navigation Drawer right-watch always resets application padding

### ISSUE THREAD

**Issue by sjoris** [vuetifyjs/vuetify#2679]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
I installed the webpack-advanced template with vue-cli and had problems with the right temporary Navigation Drawer.
- Click on the top-right button to open the temporary drawer
- Now use the 'Switch drawer' button

### Expected Behavior
Because the right Navigation drawer is temporary, you would expect it to switch from right to left and back, without changing the application paddings, because it is temporary.

### Actual Behavior
You'll see that the toolbar, content and footer lose their left padding. Now the toolbar is behind the left Navigation drawer and it will not come back.

### Reproduction Link
[https://codepen.io/anon/pen/EbOeVq](https://codepen.io/anon/pen/EbOeVq)

### Other comments
The problem is not only in the webpack-advanced template, I think it is also a small mistake in the source of the Navigation Drawer. 

To match the *webpack-advanced* template with the *webpack* and *webpack-ssr* templates, the **app** property of the right Navigation Drawer should probably be changed to **fixed**.

To fix the Navigation Drawer:
File: *vuetify/src/components/VNavigationDrawer/VNavigationDrawer.js*
In the **watch** of property **right** on line **192**
Original: `if (prev != null)`
I think it should be: `if (prev != null && this.app)`

After these changes all works well and as expected.

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/pull/2703
