### ISSUE TITLE
[style issue]: Border of first th of data-table is lighter

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#2681]
Hello, in latest Chrome the border of the first th is lighter than the others of the data-table
![tablefail](https://user-images.githubusercontent.com/17402724/33440351-07de8bfc-d5f0-11e7-9afb-4f3a39e7adfe.PNG)
In latest firefox, it works fine

**Comment by KaelWD** [comment]
Duplicate of #2271
