### ISSUE TITLE
[Bug Report] Switch as secondary action for list item has incorrect spacing

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#2684]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Firefox 57.0
**OS:** Windows, Linux

### Steps to reproduce
Add a `v-switch` element inside a `v-list-tile-action` element.

### Expected Behavior
Have the correct/same spacing as other elements like `v-icon`.

### Actual Behavior
The switch is positioned too far left.

### Reproduction Link
[https://codepen.io/anon/pen/vWvymr](https://codepen.io/anon/pen/vWvymr)

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/commit/4f9d982980c8a86b38008687446b50fe973734ae
