### ISSUE TITLE
[Bug Report] v-select with readonly can still be changed

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#2690]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
1. Click on the right-side dropdown arrow of the v-select
2. Select a value

### Expected Behavior
A v-select with the ```readonly``` prop should not be editable.

### Actual Behavior
A v-select with the ```readonly``` prop can be edited by clicking on the right-side dropdown arrow (although clicking on the field itself does not spawn the options list, which is correct).

### Reproduction Link
[https://codepen.io/anon/pen/NweebX](https://codepen.io/anon/pen/NweebX)

**Comment by KaelWD** [comment]
Goddamn that was a lot of spaghetti.
