### ISSUE TITLE
[Feature Request] V-select object comparison could be more generic

### ISSUE THREAD

**Issue by scoobah36** [vuetifyjs/vuetify#2692]
### New Functionality
allow for more generic object comparison like compare on itemValue.

### Improvements
there is no work-around if you try to set an object that has an attribute that is slightly different

### Bugs or Edge Cases it Helps Avoid
vselect will not display that an object is selected if all of the attributes are the exact same

**Comment by scoobah36** [comment]
I went ahead an made a PR
https://github.com/vuetifyjs/vuetify/pull/2693

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/pull/2712
