### ISSUE TITLE
Option of Disabling Swipe for v-tabs (mobile)

### ISSUE THREAD

**Issue by RGFanker** [vuetifyjs/vuetify#2695]
In some cases the user may not want to "swipe" to view another tab and instead want to "tap" the tab (like a button). For instance, when you have two parent tabs and other child tabs within them, the two parent tabs could "swipe", but the child tab "swipe" could be disabled.

**Comment by jacekkarczmarczyk** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
