### ISSUE TITLE
[Bug Report] v-select value removed on tab keypress when using chips and autocomplete

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#2697]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.1
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
1. Select a value from the ```v-select``` dropdown
2. Press tab
3. Notice that the selected option was removed

### Expected Behavior
Standard select behavior - you tab out and the value is retained.

### Actual Behavior
The selected option is removed.

### Reproduction Link
[https://codepen.io/anon/pen/QOYdJp](https://codepen.io/anon/pen/QOYdJp)

### Other comments
This seems to only happen when using ```chips``` and ```autocomplete``` in conjunction.

**Comment by johnleider** [comment]
Your reproduction links the currently live files, 0.17.3.

**Comment by Dylan-Chapman** [comment]
Updated reproduction link to use 1.0.0-alpha.1.

**Comment by stoked74** [comment]
@johnleider I just updated to alpha 2 and now when you tab through a select with autocomplete and a pre-selected value it resets the value to the first item in the array. Thought I'd post here because it's probably related. Let me know if you want me to post a codepen. Thanks

**Comment by johnleider** [comment]
Create a new issue please @stoked74

**Comment by stoked74** [comment]
@johnleider issue created. #2754
