### ISSUE TITLE
[Feature Request] v-select defaultText is not selectable

### ISSUE THREAD

**Issue by bombicode** [vuetifyjs/vuetify#2698]
### New Functionality
On my specific use case, I have objects that reference other objects. For example, a User as a property roleId referencing a Role object. But this property is not required, which means that roleId can be left undefined/null.
From a UX perspective, on the select input I have two options:

either I set a label to it and have the first select option for None, to be able to not have a Role selected for this User. Problem: I'm not able to select "None" if I have another option selected.

or I don't set a label and have the first select option as the "label". Problem: Looks weird, specially cause all the other inputs have labels set.
Thanks in advance

### Improvements
why there is no property defaultDisabled in the latest version 0.17?
https://github.com/vuetifyjs/vuetify/issues/57

### Bugs or Edge Cases it Helps Avoid
https://github.com/vuetifyjs/vuetify/issues/57

**Comment by KaelWD** [comment]
You've just copied a comment from that year-old issue. I have no idea what your issue is as there is no defaultText property any more.

**Comment by bombicode** [comment]
You have a wonderful Framework. But I do not understand how to make the autocomplete field optional, (none), so I give an example of an issue with github 2016. photo https://cloud.githubusercontent.com/assets/882713/21580383/9b2e9588-cfd8-11e6-97f9-bff038aa6a7e.png

**Comment by KaelWD** [comment]
That screenshot doesn't help explain what you're trying to do at all.

**Comment by bombicode** [comment]
an example from the documentation. I need the field to be optional, but now in your example, if I chose Alabama, then erase and leave the field blank can not be done. It is necessary to make that the field could remain empty.
https://vuetifyjs.com/components/selects#example-5

**Comment by smares** [comment]
You can use `clearable` to display an X on the right of the dropdown that clears the input

**Comment by bombicode** [comment]
Thanks, it partially solves my problem. Tell me please how to track the event if the user erased the field using clearable. Let's say I want to make a notification as soon as he cleared the field. Thank you in advance.

**Comment by KaelWD** [comment]
Just watch the model and check if it's `null`
