### ISSUE TITLE
Source map error: request failed with status 404

### ISSUE THREAD

**Issue by gitsakil09** [vuetifyjs/vuetify#2700]
Hello, I am sorry to post this problem.I don't get what to do actually. I am using the latest version of vuetify and of course vue.Suddenly i am getting the following error.

`Source map error: request failed with status 404
Resource URL: http://localhost:8000/js/app.js
Source Map URL: vuetify.js.map`

Any help will be appreciated cordially.

Thanks,
Sakil

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
