### ISSUE TITLE
[Bug Report] Use clearable - Error in render: "TypeError: Cannot read property 'state' of null"

### ISSUE THREAD

**Issue by bombicode** [vuetifyjs/vuetify#2701]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Chromium 58.0.3029.110
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
1. Add a prop in v-select - clearable
2. choose any option in select, for example Florida
3. click to clear the option
4. see an error in the console
Error in render: "TypeError: Cannot read property 'state' of null"

### Expected Behavior

There should be no errors in the console, because props are used from the documentation

### Actual Behavior
error

### Reproduction Link
[https://codepen.io/bombicode/pen/gXqgby](https://codepen.io/bombicode/pen/gXqgby)

**Comment by KaelWD** [comment]
That's a problem with your code, not vuetify. You'll need to check for null before setting the hint.

**Comment by bombicode** [comment]
I apologize, you could not prompt how to make such a check to be correct, or to give more details.

**Comment by bombicode** [comment]
do :hint="`Регион: ${a1 ? a1.id : select.id}`"  its work! 
How add event onItemClick for example @click in <v-select>  ?

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
