### ISSUE TITLE
<v-checkbox> Loading issues

### ISSUE THREAD

**Issue by sgangadhar02** [vuetifyjs/vuetify#2702]
On refresh of view, web fonts load first on a slow network or medium network. Is there any way to fix this?
Please check the screenshot for the same

<img width="1680" alt="screen shot 2017-12-03 at 2 33 32 am" src="https://user-images.githubusercontent.com/16475764/33519721-d1f85736-d7d2-11e7-9335-a51d89e13590.png">

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
