### ISSUE TITLE
[Bug Report] v-text field with solo prop in a dark toolbar has white background and white text

### ISSUE THREAD

**Issue by jmattheson** [vuetifyjs/vuetify#2705]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.1
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
put a v-text-field with the solo prop in a v-toolbar with the dark prop

### Expected Behavior
make the text black

### Actual Behavior
the text is white

### Reproduction Link
[https://codepen.io/anon/pen/EbMYpg?&editors=100](https://codepen.io/anon/pen/EbMYpg?&editors=100)

### Other comments
should be an easy fix right?

**Comment by darylteo** [comment]
If anyone still looking for this fix, I ended up putting a "light" attribute on the element, which seems to work. Works in the codepen as well.


```html
        <v-select
            :items="items"
            item-text="value"
            item-value="value"
            v-model="select"

            :search-input.sync="query"
            :class="$style.quicksearch"
            :loading="loading"

            max-height="500"

            label="Search for companies by name, products etc."
            autocomplete
            required
            light
            color="grey darken-3"
            prepend-icon="search"
            append-icon=""
            clearable
            single-line
            solo
        >
````
