### ISSUE TITLE
[Bug Report] <v-pagination> has duplicated keys for pages

### ISSUE THREAD

**Issue by onlyurei** [vuetifyjs/vuetify#2707]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.1
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
- use <v-pagination> component with the following props settings:
set `value` (v-model) to 100
set `totalVisible` to 9

- SSR a page with such <v-pagination> component

- click on next button in the <v-pagination> component in the SSRed page in a browser

- when the button representing the active page switches position with the omitted pages indicator (...) - from its left to its right, the whole page's JavaScript execution breaks, and browser console reads the following error messages:
[Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.
TypeError: Cannot read property 'key' of undefined

### Expected Behavior
- on SSR page load, there should not be warning in browser console about Mismatching childNodes vs. VNodes on the <v-pagination> rendered markup

- user should be able to keep clicking on next/prev button to keep changing pages, no matter if the pagination button representing the active page being on the left or right to the omitted pages indicator (...)

### Actual Behavior
- on SSR page load, observed the Vue warnings in browser console (I'm using SSR and this component is rendered on server side):
Mismatching childNodes vs. VNodes:  [span.pagination__more] [VNode]
vue.runtime.esm.js:5892 Parent:  <li>​<span class=​"pagination__more">​...​</span>​</li>​

- when the button representing the active page switches position with the omitted pages indicator (...) - from its left to its right, the whole page's JavaScript execution breaks, and browser console reads the following error messages:
[Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.
TypeError: Cannot read property 'key' of undefined

### Reproduction Link
[https://codepen.io/onlyurei/pen/eeXXgd](https://codepen.io/onlyurei/pen/eeXXgd)

### Other comments
Blame:
https://github.com/vuetifyjs/vuetify/commit/f09a5165b77ead7b7e81e61a977a39d60e5c849c#diff-79ad00af4d60169a3e20640b9456f6bcR149

**Comment by johnleider** [comment]
You're going to have to provide some additional reproduction steps. There is nothing I can do with that file, and testing `v-pagination` in SSR docs is yielding no issues.

**Comment by onlyurei** [comment]
@johnleider updated Reproduction Link to https://codepen.io/onlyurei/pen/eeXXgd

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/pull/2718
