### ISSUE TITLE
Can't have a left and right sidebar

### ISSUE THREAD

**Issue by artemk1** [vuetifyjs/vuetify#271]
I was playing around with another framework, `Vue Material`, and I was able to come up with a layout that had both a left and right sidebar. The left sidebar was a drawer, and the right was activated on a button click.

I tried to do the same with this framework, however I found no success. Here is the example from`Vue Material` that I am referring [too](https://vuematerial.github.io/#/components/sidenav)

It would be awesome to have support for both sidebars at once! If you like, I could post my code snippet, perhaps I have done something erroneous. 

~ Artem

**Comment by johnleider** [comment]
You most certainly can. http://codepen.io/johnjleider/pen/evjemO

**Comment by artemk1** [comment]
@johnleider My apologies. The combination of `fixed` & `drawer` seems to have emulated exactly the behavior I was looking for.  `fixed` seems to play a major role in making it work correctly. Thanks for the quick response! Really enjoying the framework so far, great work.
