### ISSUE TITLE
[Feature Request] Color Picker Component

### ISSUE THREAD

**Issue by cn-xufei** [vuetifyjs/vuetify#2717]
Hope to choose the color
For example : http://element-cn.eleme.io/#/en-US/component/color-picker
![image](https://user-images.githubusercontent.com/14144811/33586953-dad4f97e-d9a6-11e7-9e71-310e163d3f60.png)

**Comment by pSchaub** [comment]
How about a color picker from this? https://github.com/xiaokaike/vue-color

**Comment by Gompje** [comment]
Suggestion: https://saintplay.github.io/vue-swatches/

**Comment by AGPDev** [comment]
+1

**Comment by bdeo** [comment]
@AGPDev Please do not comment +1 on issues, comments are for discussion. If you'd like to show your interest in this ticket, please Vote on OP's comment with the 👍 emoji.

**Comment by lokimx88** [comment]
the is a project :https://github.com/chmjs/vuetify-colorizer
But it looks a little complexd.It's  just a small function after all.

**Comment by nekosaur** [comment]
@zeing Please do not report issues for other libraries in this thread.

**Comment by zeing** [comment]
@nekosaur okay , sorry

**Comment by supraniti** [comment]
I have implemented a color picker (based on material color values from vuetify/es5/util/colors)
You're welcomed to use the code for your needs (the relevant part is on ColorPickerV2.vue)
https://k58qkrmol7.codesandbox.io/

**Comment by johnleider** [comment]
Resolved with #6988
