### ISSUE TITLE
BUG: v-text-field(type="time") doesn't emit the real value of v-model correctly

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#272]
http://codepen.io/anon/pen/ryrGWo?editors=1111

- Change the time of the end schedule less than the start

### What is Expected
- Time end will change its value on the input according on the v-model

### What is happening
- Time data is not emitting the right value event to the text-field

**Comment by johnleider** [comment]
This is an interesting one. If you manually type in the time, you can see what you have working. But using the up and down arrows does not. Will look into, not sure if this is a Vuetify quirk or not.

**Comment by ralphchristianeclipse** [comment]
@johnleider this bug isn't happening on the native input type time i think the real problem is the input event emission value

**Comment by johnleider** [comment]
After some testing, you need to wait for Vue to finish the DOM update cycle. http://codepen.io/johnjleider/pen/YZOJEP?editors=1011
https://vuejs.org/v2/api/#Vue-nextTick
