### ISSUE TITLE
[Bug Report] v-text field with return-masked-value prop returns unmasked if text is not changed 

### ISSUE THREAD

**Issue by Netsplits** [vuetifyjs/vuetify#2722]
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.3
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Create a v-text field with return-masked-value and mask
Set initial value unmasked (also failing using a initial correct masked axios request in my case)
Don't change control text
Value returned is unmasked

### Expected Behavior
Return value should be masked with return-masked-value prop set to true

### Actual Behavior
Value is returned masked only if text is changed

### Reproduction Link
[https://codepen.io/anon/pen/BmbrNM](https://codepen.io/anon/pen/BmbrNM)

**Comment by KaelWD** [comment]
This is why #2572 is needed.
