### ISSUE TITLE
[Feature Request] VSelect with textinput and async data without the autocomplete (or alternatives) needed

### ISSUE THREAD

**Issue by darylteo** [vuetifyjs/vuetify#2726]
### New Functionality
I just want a select box (or a text field with the dropdown without fussing about with positioning etc.)  that will show me the async retrieved results, without manipulating the results. Trying to build search box results powered by backend services like SOLR (and not just partial value matching) which are displaying most relevant results.

### Improvements
 - Currently, the autocomplete flag allows the display of the text input box (works).
 - If you use scoped slots, you can customise the display of the results (works)
 - If you have other types of items in the results, like dividers or spacers, they do not display because the autocomplete does not treat them as valid results (as it is doing a partial string match on the item value) (works as designed)

Therefore the current workaround to make everything display the way I want is to set the value of each item in the result to the contain the input box value. For example, stringifying the item object into JSON, then parsing it back when interpreting the value.

### Bugs or Edge Cases it Helps Avoid
New feature.

**Comment by darylteo** [comment]
If there is an alternative I have missed, happy to hear it. 

Regards,
Daryl

**Comment by johnleider** [comment]
Going to need to see an example implementation of what you are trying to do vs what you would like to do.

**Comment by darylteo** [comment]
@johnleider here's a codepen.

https://codepen.io/anon/pen/ZvEGPa?editors=1011

If you, say, search for "flo", I would like it to say "flowers", but it should also have the divider and header, as well as both "Flowering Season", and "Botany", despite "Botany" not having "flo" in it.

----

Basically, I'd like a quicksearch, that is exclusively driven by our Solr/Lucene api (i.e. all results that are returned are assumed to be relevant), and not substring filtering. VSelect seemed like the fastest way to do this:

 - already has dropdown
 - already has text field
 - already has prepend and append icons where I need them to be.
 - already has lazy loading of data

It just keeps hiding things when I don't want it to. Which I understand... it's doing a autocomplete. If there's another way to solve this or I'm misusing it in some way, please let me know.

Regards,
Daryl

**Comment by KaelWD** [comment]
You can get the divider to show up at least with `text: v` instead of `value: v`

**Comment by johnleider** [comment]
If you are pulling this data from the backend, chances are you have already filtered it, maybe just creating a custom filter that returns every result? https://codepen.io/anon/pen/OzJmBJ?editors=1011

**Comment by KaelWD** [comment]
Nice solution, didn't even think of that. You can simplify it to `:filter="v => v"`

**Comment by darylteo** [comment]
That's exactly what I needed =) Thanks @johnleider. Happy to close if that's the official support for this kind of functionality.

**Comment by KaelWD** [comment]
Maybe open an issue on https://github.com/vuetifyjs/vuetifyjs.com to have it as an example

**Comment by KaelWD** [comment]
nvm, did it for you
