### ISSUE TITLE
[Feature Request] Nothing password field in form

### ISSUE THREAD

**Issue by blackinitial** [vuetifyjs/vuetify#2727]
### New Functionality
i can't add password field

### Improvements
how can i add password field

### Bugs or Edge Cases it Helps Avoid
passwords can be seen by other people

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
