### ISSUE TITLE
[Feature Request] v-text-field should have number type to handle number types specific input

### ISSUE THREAD

**Issue by HitIt** [vuetifyjs/vuetify#2729]
### New Functionality
v-text-field with number type input will open a number input keyboard only for mobile apps by default for Cordova application, and it will be helpful to get data we take in form like zipcode, phone-number, card number etc as per business requirement otherwise we would be require to integrate our own keyboard to handle those functionalities which Cordova/Hybrid app already gives.

### Improvements
Since "input type='number'" gives the straight number type keyboard and number type validation directly to the developers, so it will not take developers to override those functionalities for different environment.

### Bugs or Edge Cases it Helps Avoid
Many form cases can be resolved like taking zipcode, card number, phone number, ssn etc.

**Comment by KaelWD** [comment]
Use `<v-text-field type="number">`
