### ISSUE TITLE
Using tabs component and vue-router

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#273]
I am integrating vuetify into an already existing project and I was trying to convert the main navigation using the tabs component. Here is an example http://jsfiddle.net/xgrjzsup/1552/. So this works to change pages, but it doesn't get the cool transition effect and more importantly the active tab indicator doesn't move. If you add dummy content into 2 `v-tab-content` elements things work as expected except for of course the `router-view` component doesn't transition. 

Could there be some update that works with the `router-view` instead of `v-tab-content` element? Or if there is something basic I'm just missing could the docs be updated to give examples using the `router-view` element? Actually whatever the case it would be helpful if the docs contained at least one sample including the use of vue-router.

**Comment by johnleider** [comment]
There are some updates that can be done for route indication using the tabs. However, as far as animations, that would be up to you to wrap your router-view in whatever you want.

**Comment by qw3n** [comment]
I wondered if the animations might be tied to the content elements. Also, this is probably a separate problem, but I noticed that if no id is set then the generated element has `id="undefined"`

**Comment by johnleider** [comment]
Which element? TabContent?

**Comment by qw3n** [comment]
Sorry didn't make myself clear. The `v-tabs` element. I get this if no id is set `<div id="undefined" class="tabs">`.

**Comment by jonno317** [comment]
I used named routes inside of `<v-tab-content>` and everything works great.
Ex:
`<v-tabs>
  <v-tab-item v-bind:href="'#tab1'" slot='activators'>Tab 1</v-tab-item>
  <v-tab-content v-bind:id="'#tab1'" slot='activators'>
    <router-view name='tab1'></router-view>
  </v-tab-content>
</v-tabs>`

**Comment by johnleider** [comment]
You'll have to wrap your router-view in a transition. http://jsfiddle.net/h4kpvk4v/
