### ISSUE TITLE
[Bug Report] v-tabs-slider disappears with v-if after unloading and reloading

### ISSUE THREAD

**Issue by smanji** [vuetifyjs/vuetify#2736]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.2
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.10.5

### Steps to reproduce
1. Click the checkmark button in the top right
2. Observe that the tabs now appear
3. Click on any of the tabs
4. Observe that the v-tabs-slider is visible
5. Click on the close button in the top right
6. Observe that the tabs now disappear
7. Click on the checkmark button in the top right
8. Observe that the tabs now appear again
9. Click on any of the tabs
10. Observe that the v-tabs-slider does not appear anymore

### Expected Behavior
If a v-tabs-bar is controlled by v-if, the v-tabs-slider should be visible when the v-tabs-bar is visible when the v-if condition changes from true to false and back to true.

### Actual Behavior
If a v-tabs-bar is controlled by v-if, the v-tabs-slider is only visible when the v-tabs-bar becomes visible the first time. When the v-if condition changes from true to false and back to true, the v-tabs-slider is no longer visible when the v-if condition becomes true the second time and onwards.

### Reproduction Link
[https://codepen.io/smanji/pen/qVGpLL](https://codepen.io/smanji/pen/qVGpLL)

### Other comments
This bug is only present with v-if. If changed to use v-show, this issue is not present. However, this is not a suitable workaround because with v-show, the height of the toolbar is always extended to include space for the v-tabs-bar even which v-show evaluates to false. This is especially undesirable for mobile due to the limited screen real estate.

**Comment by jacekkarczmarczyk** [comment]
In issue description you mentioned Vuetify 0.16.9, in codepen you're using 0.14.x, you should actually provide a repro using the latest Vuetify version (0.17.4 or even 1.0.0-alpha.1)
I'll reopen the issue when you provide a correct repro

**Comment by smanji** [comment]
Hi @jacekkarczmarczyk,

Sorry about that, it was my first codepen -- I copied it from elsewhere and didn't realize I could specify the Vuetify version.

I have updated the repro link to use 0.17.4 and the issue is still present: https://codepen.io/smanji/pen/qVGpLL

I was also able to reproduce this with 1.0.0-alpha.1:
https://codepen.io/smanji/pen/aVgmMK

Please re-open and let me know if this can be resolved. Thanks!

**Comment by johnleider** [comment]
This is a tricky one. You are conditionally rendering elements that are used to bootstrap the initial display. This means they are not available when `v-tabs` boots up. I started to spec this out and it would be a pretty large refactor, moving the slider functionality out of `v-tabs` and into `v-slider` so that it can control the state.

**Comment by KaelWD** [comment]
Here's a workaround: https://codepen.io/anon/pen/WdNoqo?editors=1010

**Comment by smanji** [comment]
Thanks @KaelWD, adding :key="showTabs" to the <v-tabs> tag worked! I've tested this using 0.17.4 as well and it works.

That being said, I'm not sure how or why it works... it would be great if this could be added to the docs in case someone runs into this in the future.

@johnleider: I understand if this is a lot of work to resolve, I'm good with using this workaround as long as it doesn't break in a future release. Do you think that it could break in the future?

**Comment by johnleider** [comment]
It **should** be added to the docs. The reason _why_ it works is because the key forces Vue to re-hydrate the component when it changes, essentially forcing it to boot again.

**Comment by smanji** [comment]
Thanks @johnleider, that makes sense -- I'm still a Vue/Vuetify newbie so I appreciate the explanation and support! Keep up the great work, I love Vuetify and appreciate all that you and your team does!
