### ISSUE TITLE
Why pick stylus over less or sass?

### ISSUE THREAD

**Issue by frizadiga** [vuetifyjs/vuetify#2737]
sorry for dumb question, just curious

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

Thi has already been asked several times before: #1857, #2371

**Comment by mrts** [comment]
@frizadiga, please vote in #2371 if you would like to see SASS support.
