### ISSUE TITLE
[Bug Report] Too big margin/padding on VIcon on VListTileAction in grouped list

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#2742]
**Information**
Vue Version: 2.5.9
Vuetify Version: 1.0.0-alpha.1
Browser: Chrome (latest)
OS: Linux x64 (Arch Linux, latest)

**Description**
I think that the margin between the icon and the text "Pages"
in the following codepen / screenshot is too big.

![bildschirmfoto von 2017-12-07 12-00-58](https://user-images.githubusercontent.com/11846736/33712965-92f42a7c-db49-11e7-83cf-03d064bd3c46.png)

**Reproduction link**
https://codepen.io/anon/pen/JOqgVm

**Comment by KaelWD** [comment]
Please update your issue using the provided template for issues, including a reproduction link, or the issue will be closed.

**Comment by pSchaub** [comment]
I try to reproduce it here but I have another issue while reproducing it in codepen:
https://codepen.io/anon/pen/JOqgVm?editors=1111

Can you have a look into it?

**Comment by pSchaub** [comment]
@KaelWD I added the missing information and a reproduction link.

**Comment by johnleider** [comment]
Unfortunately, this design is not covered in MD spec. Right now, a icon should have 56px of space between its left edge and the left edge of the title text. Since there is no explicit definition of what spacing it should be under spec, we are going to leave it uniform as is for now.
