### ISSUE TITLE
[Bug Report] Wrong click behaviour on grouped lists with mini variant in navigation

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#2746]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.1
**Vue:** 2.5.9
**Browsers:** Chrome 63.0.3239.84
**OS:** Linux x86_64

### Steps to reproduce
See codepen (section "Reproduction link")

### Expected Behavior
The second entry on the codepen should be normally expanded after clicking on it (or it should not be expandable)

### Actual Behavior
The second entry on the codepen looks wrong after clicking on it

### Reproduction Link
[https://codepen.io/anon/pen/gXNORe](https://codepen.io/anon/pen/gXNORe)

**Comment by johnleider** [comment]
Referenced the wrong issue, https://github.com/vuetifyjs/vuetify/commit/a45089a6c646811a7fd08a6df66eb2f2e6d01a83 was meant to close #2745

**Comment by johnleider** [comment]
Your issue is because you are not using the **.sync** modifier. https://codepen.io/anon/pen/LeYPBg

**Comment by pSchaub** [comment]
@johnleider I think the official templates should use `sync` to prevent from this issue.
See e.g. the nuxt template here: https://github.com/vuetifyjs/nuxt/blob/master/template/layouts/default.vue#L4
