### ISSUE TITLE
[Bug Report] Mask with regular chars

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2747]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Linux x86_64

### Steps to reproduce
Try to type numbers to inputs in example

### Expected Behavior
As we type characters constant part of the mask should remain at the place defined in mask

### Actual Behavior
In first case typed chars inserted at random places
In second case input does not accept chars at all

### Reproduction Link
[https://codepen.io/darkside73/pen/RjzNvz](https://codepen.io/darkside73/pen/RjzNvz)

**Comment by johnleider** [comment]
Please refer to the table within the [docs](https://vuetifyjs.com/components/text-fields). You are using characters that are not recognized in the masking process. I understand **what** you are trying to do, but that is currently not supported.
