### ISSUE TITLE
[Feature Request] Header slot for v-data-iterator

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#2748]
### New Functionality
Enter markup that appears before the ```item``` slot. For example, I'm trying to make a table that has multiple ```tbody``` elements. This could be done easily with ```v-data-iterator``` if, like ```v-data-table```, it had a ```header``` slot. Also, why have a ```footer``` slot and not a ```header``` slot?

### Improvements
If you need your elements grouped (as is the case with a table), I'm not aware of any way to achieve the equivalent of this functionality currently.

### Bugs or Edge Cases it Helps Avoid
Just an enhancement.

**Comment by johnleider** [comment]
Can you please provide an example implementation of what you are looking for, vs what you may have to do now (if possible).

**Comment by Dylan-Chapman** [comment]
My desired markup is something like:
```html
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
```

Thinking about my use-case a little more, I don't think this request really helps with that, though (in terms of not having to copy Vuetify's table classes and such). However, I do still find it odd to have a ```footer``` slot and not a ```header``` slot. I'm not sure how you can justify one without justifying them both, I guess?

**Comment by johnleider** [comment]
Sorry, what I mean is how would you expect to use this with the component?

**Comment by Dylan-Chapman** [comment]
Apologies, I guess I'm not entirely understanding. The request is for something like:

```html
<v-data-iterator content-tag="div" v-bind:items="items">
  <div slot="header">
    HEADER
  </div>

  <div slot="item" slot-scope="props">
    {{ props.item }}
  </div>

  <div slot="footer">
    FOOTER
  </div>
</v-data-iterator>
```

Which seems reasonable to me. Currently, only the ```item``` and ```footer``` slots exist. I'd expect the exact same use cases as any anticipated usage of the ```footer``` slot. Like I said, I guess it doesn't apply to what I had in mind, so I don't have a specific example. Feel free to close if you need an example to justify it.

**Comment by johnleider** [comment]
Thank you for the example. Basically I'm trying to see how you imagine this feature would look like for the dev.

**Comment by samuelcolburn** [comment]
I can't speak for @Dylan-Chapman but  have a header-like component on my data-iterators as well. It holds similar aspects to a header like sorts and search fields. Something like: 

```
<v-data-iterator content-tag="div" v-bind:items="items">
  <div slot="header">
    <div>Search Items: </div>
    <div>
      <h3>Sort by:</h3>
      <div>Prop1 <v-icon>arrow_upward</v-icon></div>
      <div>Prop2<v-icon>arrow_upward</v-icon></div>
  </div>

  <v-flex slot="item" slot-scope="props">
    <v-card>
      <v-card-title>Item Card</v-card-title>
      <div>Prop 1: {{ props.item.propOne }}</div>
      <div>Prop 2: {{ props.item.propTwo }}</div>
    </v-card>
  </v-flex>

  <div slot="footer">
    FOOTER
  </div>
</v-data-iterator>
```

**Comment by creamosdavid** [comment]
Hi guys, anyone can explain why data-iterator show "Unknown custom element: <v-data-iterator>" this is my code:

<template>
  <v-container fluid grid-list-md>
    <v-data-iterator content-tag="v-layout" row wrap :items="items" :rows-per-page-items="rowsPerPageItems" :pagination.sync="pagination">
      <v-flex slot="item" slot-scope="props" xs12 sm6 md4 lg3>
        <v-card>
          <v-card-title><h4>{{ props.item.serial }}</h4></v-card-title>
          <v-divider></v-divider>
          <v-list dense>
            <v-list-tile>
              <v-list-tile-content>Calories:</v-list-tile-content>
              <v-list-tile-content class="align-end">{{ props.item.ip }}</v-list-tile-content>
            </v-list-tile>
            <v-list-tile>
              <v-list-tile-content>Fat:</v-list-tile-content>
              <v-list-tile-content class="align-end">{{ props.item._id }}</v-list-tile-content>
            </v-list-tile>
            <v-list-tile>
              <v-list-tile-content>Carbs:</v-list-tile-content>
              <v-list-tile-content class="align-end">{{ props.item.ip }}</v-list-tile-content>
            </v-list-tile>
            <v-list-tile>
              <v-list-tile-content>Protein:</v-list-tile-content>
              <v-list-tile-content class="align-end">{{ props.item._id }}</v-list-tile-content>
            </v-list-tile>
          </v-list>
        </v-card>
      </v-flex>
    </v-data-iterator>
  </v-container>
</template>
<script>
import axios from 'axios'
export default {
  name: 'dispositivos',
  data () {
    return {
      headers: this.$ls.get('token'),
      headersFile: {
        'x-access-token': this.$ls.get('token')
      },
      rowsPerPageItems: [4, 8, 12],
      pagination: { rowsPerPage: 4 },
      items: []
    }
  },
  created () {
    axios.get('http://ec2-18-219-32-177.us-east-2.compute.amazonaws.com:3000/dispositivos', {headers: {'x-access-token': this.headers}})
    .then(response => {
      this.items = response.data
      console.log(response.data)
    })
    .catch(e => {
      this.errors.push(e)
    })
  }
}
</script>

**Comment by johnleider** [comment]
@creamosdavid please do not ask questions on the issue board, especially on a closed issue.

https://community.vuetifyjs.com
