### ISSUE TITLE
[Feature Request] Date and Time Pickers need a disabled and/or read-only mode

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#2750]
### New Functionality
Allow date and time pickers to exist on a form in a display-only non-interactive way.  This is a common need in business applications.

### Improvements
Only work-arounds are :allowed-dates="() => false" and :allowed-hours="() => false" / :allowed-minutes="() => false"
But it has visual flaws, and still allows some interaction.

### Bugs or Edge Cases it Helps Avoid
None, just confusion from the end-user's perspective.

**Comment by FabianSilva** [comment]
need this too, also if  text-field is activator, still if it is disabled when get focus open date-picker in a enabled mode

**Comment by johnleider** [comment]
Can you please provide an example implementation that represents the typical business application need?

**Comment by Phlow2001** [comment]
![image](https://user-images.githubusercontent.com/4063783/34019763-63c77596-e0fe-11e7-922b-431500603660.png)

So, as an example, we have user roles where one user can modify the date of something as well as some other options, and a lesser user cannot modify the date, but still needs to see the calendar.

The current workaround is to set :allowed-dates="() => false" but as you can see it has a less than desirable effect, and still allows interaction with the month/year and arrows.

What we need is a disabled state where it's clearly visible what is selected but no interaction is allowed.
