### ISSUE TITLE
[Bug Report] Carousel images not 'covering' 

### ISSUE THREAD

**Issue by typerory** [vuetifyjs/vuetify#2751]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.1
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
I used one high-resolution image and two low-resolution images to exaggerate the issue.

0.17.4 Pen:  https://codepen.io/typerory/pen/oorwvb
Alpha Pen: https://codepen.io/typerory/pen/mqZmoO

### Expected Behavior
background: cover

### Actual Behavior
not covering

### Reproduction Link
[https://codepen.io/typerory/pen/mqZmoO](https://codepen.io/typerory/pen/mqZmoO)

### Other comments
Looks like it's using img tag and not a background css.
Carousel or jumbotron may need to be refactored somehow to fix that.

**Comment by persun** [comment]
I believe the Carousel component should have an option to render images as CSS background images (as 0.17.6 does). The carousel may have different aspect ratio depending on the client viewport size and I need my images to "cover" the carousel no matter what.

The way it works now I can't upgrade to 1.0.

What are your thoughts on this @johnleider?

**Comment by daithi-coombes** [comment]
+1 to this

**Comment by daithi-coombes** [comment]
solutiont to this, I've overwritten the `jumbotron__wrapper` class. 

```css
  .jumbotron__wrapper{
    max-height: 95vh !important;
  }
  .jumbotron__wrapper img{
    max-height: 100% !important;
  }
```

Max width seems to be respected, overwrite to suit ;)

**Comment by razakhtar** [comment]
👍🏽
