### ISSUE TITLE
[Feature Request] Input reset() method should allow for a value to be set. Currently hardcoded to null as value.

### ISSUE THREAD

**Issue by adammcfadden** [vuetifyjs/vuetify#2752]
### New Functionality
Currently using the `reset()` method as found [here](https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/validatable.js#L90) means that the user's input is always set to `null`. This also has the affect of setting related v-model attributes to `null`. 

Allowing a user to either pass a value to reset could alleviate this issue, as then the user can effectively reset the input to a default value. 

### Improvements
The current workaround I am using is a simple re-write of the reset method, with the null value replaced with the default value that I want to use.

Current workaround:
```
        // Rewrite of the vuetify reset method to allow for keeping a default value
        // https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/validatable.js#L90
        this.$refs[key].$emit('input', this.model[key]);
        this.$refs[key].$emit('change', this.model[key]);

        this.$refs[key].$nextTick(() => {
          this.$refs[key].shouldValidate = false;
          this.$refs[key].hasFocused = false;
          this.$refs[key].validate();
        });
```

Allowing the user to pass in a value to reset would simplify this greatly

Updated reset method:
```
    reset (value=null) {
      // TODO: Do this another way!
      // This is so that we can reset all types of inputs
      this.$emit('input', this.isMultiple ? [] : value)
      this.$emit('change', value)

      this.$nextTick(() => {
        this.shouldValidate = false
        this.hasFocused = false
        this.validate()
      })
    },
```

Use of updated reset method:
```
this.$refs[key].reset(this.model[key]);

// or if the user wants a null value, then there is no change in behavior
this.$refs[key].reset()
```

### Bugs or Edge Cases it Helps Avoid
In my opinion the current behavior of reset is a bit unexpected as it nullifies values regardless of the input type. I first noticed this when using a checkbox type input that I expected to always be either `true` or `false`. When the checkbox was reset, it became `null`. 

This change would give users more control over their forms if they need it.

**Comment by adammcfadden** [comment]
I'm happy to make a PR for this if it's determined that this is a desired feature.

**Comment by johnleider** [comment]
How would this look when using the top level `v-form` reset?

**Comment by adammcfadden** [comment]
That's a good question. With the implementation proposed in this issue all fields in the form would behave as the current implementation does, since they would fall back to the default value of null. 

An alternative could be to add an optional prop to inputs where a user could put in a default value. This value could then be used in the scenario of a reset of the individual input, and would also allow for the user to control the default on a top level `v-form` reset (which I would guess is more widely used). It also seems more intuitive to me as you can control the behavior with a prop instead of manually setting an argument.

I think for implementation of the alternative the [validatable mixin](https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/validatable.js#L90) could be updated in the following way to achieve this.

```
props: {
    error: {
      type: Boolean
    },
    errorMessages: {
      type: [String, Array],
      default: () => []
    },
    rules: {
      type: Array,
      default: () => []
    },
    validateOnBlur: Boolean,
    defaultValue: this.isMultiple ? [] : null
},

  ...
  
reset () {
   this.$emit('input', this.defaultValue)
   this.$emit('change', this.defaultValue)

   this.$nextTick(() => {
     this.shouldValidate = false
     this.hasFocused = false
     this.validate()
   })
},
```
^ Note - this doesn't solve the isMultiple workaround that has a TODO note, but just moves it elsewhere.

**Comment by KaelWD** [comment]
Any reason you can't reset the values yourself? issues.vuetifyjs.com does:

```js
    clearAll () {
      this.$refs.form.reset()
      this.newIssue = this.$options.data().newIssue
    },
```

**Comment by adammcfadden** [comment]
@KaelWD In my particular case the inputs all have validations, and are all bound with v-model. Setting the value as suggested triggers the validations and displays the error on the form. Also, because of the v-model binding the associated data is set to `null` on `this.$refs.form.reset()` so `this.newIssue = this.$options.data().newIssue` will just keep `this.newIssue` as `null`.

**Comment by stevencherry1** [comment]
Alternatively, perhaps form.reset() should just clear the validation errors alone, and not touch the bound v-model at all, leaving it up to the dev to set reset and properties on the bound v-model.

**Comment by dobeerman** [comment]
@stevencherry1 Good idea, but I think it would be better to make a something like `form.resetErrors()`. It will not affected to whole form state.

**Comment by myrgato** [comment]
@dobeerman that would be cool!

**Comment by bt-dd** [comment]
@HaykoKoryun - thank you! This worked for me, inside the component in question, when it is accessed/opened, I call form reset and increment a key on the html element wrapping it.

This seems to solve the bug/issue I was seeing with switches not being in sync with the model value.

**Comment by HaykoKoryun** [comment]
@myrgato [here's](https://jsfiddle.net/HaykoKoryun/eywraw8t/220977/) a quick demo.

**Comment by KaelWD** [comment]
v1.2 adds `resetValidation` (#3316), so now you can set your own values then call that instead of reset()
