### ISSUE TITLE
[Bug Report] v-select resets the model value to the first item in the array when the user tabs out.

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2754]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.2
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
Create a v-select with a v-model value. Tab out of the select. 

### Expected Behavior
The v-model value shouldn't change.

### Actual Behavior
The v-model resets to the first item in the array.

### Reproduction Link
[https://codepen.io/smitchell/pen/NwZyqR](https://codepen.io/smitchell/pen/NwZyqR)

**Comment by jacekkarczmarczyk** [comment]
This is where menu index is being set to 0: https://github.com/vuetifyjs/vuetify/blob/master/src/components/VSelect/mixins/select-watchers.js#L99
