### ISSUE TITLE
[Bug Report] Missing list colors in css since the 1.0.0 alpha

### ISSUE THREAD

**Issue by Seraf** [vuetifyjs/vuetify#2755]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.2
**Vue:** 2.5.9
**Browsers:** Chromium 62.0.3202.94
**OS:** Ubuntu undefined

### Steps to reproduce
Apply the dark theme to a navigation drawer component containing a menu list. The list won't get the colors of the dark theme

### Expected Behavior
The behavior should be the same than the 0.17 : https://codepen.io/Seraf42/pen/yPrVOR

### Actual Behavior
Using `dark` theme on the navigation drawer doesn't apply the colors to the menu list.

It looks like it has been removed in this commit : https://github.com/vuetifyjs/vuetify/pull/2563/files#diff-1c84484c46965d6c4c0f3a929a6371b4L11

### Reproduction Link
[https://codepen.io/Seraf42/pen/QOPGEr](https://codepen.io/Seraf42/pen/QOPGEr)

**Comment by johnleider** [comment]
Your codepen is referencing alpha.1, in which this bug existed. It has been since fixed in [alpha.2](https://codepen.io/anon/pen/wpwVqE)
