### ISSUE TITLE
[Bug Report] Tabs don't have same size when wrapped in toolbar and the fixed prop is used.

### ISSUE THREAD

**Issue by cairinmichie** [vuetifyjs/vuetify#2756]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.1

### Steps to reproduce
The link shows the actual versus the expected.

### Expected Behavior
The tabs should be the same size.

### Actual Behavior
The tabs are automatically sized according to content.

### Reproduction Link
[https://codepen.io/anon/pen/JOQwbr?&editors=101](https://codepen.io/anon/pen/JOQwbr?&editors=101)

**Comment by johnleider** [comment]
Fixed tab items should not exceed [264px](https://material.io/guidelines/components/tabs.html#tabs-specs). In your example above, you are actually breaking the css inheritance by adding the toolbar as the direct child of the `v-tabs`.

That's not to say there isn't improvement we could make, so I'll tag this as an enhancement.
