### ISSUE TITLE
[Bug Report] The v-select in the v-list are not correctly displayed

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#2758]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
Use v-select in v-list with text whose length exceeds the width of the v-list

### Expected Behavior
The height of the list item is adapted according to the content

### Actual Behavior
If the content does not fit into the list item, it is clipped

### Reproduction Link
[https://codepen.io/cawa-93/pen/vWqMVv](https://codepen.io/cawa-93/pen/vWqMVv)

### Other comments
Is it a layout error, or is this behavior deliberately preinstalled?

**Comment by KaelWD** [comment]
List tiles are fixed to 48px hight by design

**Comment by cawa-93** [comment]
:(

**Comment by KaelWD** [comment]
I don't think there's an option to change that, but you can override it with CSS:
```css
.list__tile {
    height: auto;
}
```
