### ISSUE TITLE
[Bug Report] Server-side data-table with search val breaks pagination

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#2761]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.12.6

### Steps to reproduce
Enter something in the search field.

### Expected Behavior
The totalItems set after data fetch would still be used for paging.

### Actual Behavior
Paging breaks.

### Reproduction Link
[https://codepen.io/kdholt34/pen/mqNbQP](https://codepen.io/kdholt34/pen/mqNbQP)

### Other comments
I did check v1-alpha.2 and the bug seems to still exist there.  Related to the fact that computed prop itemsLength returns searchLength if there's a search val without first checking if there's a totalItems prop (server-side processing) and elsewhere searchLength is never set if there's totalItems.

**Comment by nekosaur** [comment]
The solution here is to not use `search` prop when using server side data.
