### ISSUE TITLE
[Bug Report] Material Design And Fontawesome Icons not work

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#2765]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
Links in the docs https://vuetifyjs.com/components/icons to the codepen doesn't display any icons for fontawesome and mdi.
For fontawesome it doesn't display because codepen link doesnt include font-awesome.min.css and instead it include material design.
Dont know why it doesn't work for MD since it seems to include MD icons. 

### Expected Behavior
Icon displayed

### Actual Behavior
Icon not displayed

### Reproduction Link
[https://codepen.io/aldarund/pen/qpWWww?&editors=100](https://codepen.io/aldarund/pen/qpWWww?&editors=100)

**Comment by pSchaub** [comment]
I think this is the wrong repository, you should write this issue in https://github.com/vuetifyjs/vuetifyjs.com

**Comment by aldarund** [comment]
@pSchaub  im not sure. For fontawesome - yes. For material design icons - not sure, it include icon font from google and it doesnt work for me in project too..

**Comment by jacekkarczmarczyk** [comment]
it includes Material Icons, not Material Design Icons. This should be reported in vuetifyjs.com repo

**Comment by pSchaub** [comment]
Material design icons != Material Icons

The included CSS from Google are "Material Icons" and not "Material Design Icons".

Your reproduction link loads "Material Icons" but tries to use "Material Design Icons".

Material Icons (no prefix): https://material.io/icons/
Material Design Icons (prefix "mdi"): https://materialdesignicons.com/

**Comment by KaelWD** [comment]
Duplicate of #2599
