### ISSUE TITLE
[Bug Report] VStepper.js line 65 bug with .step property

### ISSUE THREAD

**Issue by Brennan99** [vuetifyjs/vuetify#2772]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.2
**Vue:** 2.4.2
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.12.6

### Steps to reproduce
Observe the console output:

console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'step' of undefined"

found in

---> <VStepper>
       <VContent>
         <VApp>
           <Root>
(anonymous) @ console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1
console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 TypeError: Cannot read property 'step' of undefined
    at VueComponent.mounted (vuetify.min.js:6)
    at callHook (vue.js:2878)
    at Object.insert (vue.js:4053)
    at invokeInsertHook (vue.js:5807)
    at Vue$3.patch [as __patch__] (vue.js:6026)
    at Vue$3.Vue._update (vue.js:2620)
    at Vue$3.updateComponent (vue.js:2748)
    at Watcher.get (vue.js:3096)
    at new Watcher (vue.js:3085)
    at mountComponent (vue.js:2755)

### Expected Behavior
Want to be able to add steps by changing the number of steps

### Actual Behavior
Unable to add steps because the .step property is throwing the above error on line 65 of VStepper.js

### Reproduction Link
[https://codepen.io/Brennan99/pen/BmgwKz](https://codepen.io/Brennan99/pen/BmgwKz)

**Comment by jacekkarczmarczyk** [comment]
VStepper checks only for direct children, probably it should use registrable mixin
