### ISSUE TITLE
[Bug Report] Memory leaks in IE?

### ISSUE THREAD

**Issue by errrken** [vuetifyjs/vuetify#2779]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Internet Explorer 11
**OS:** Windows 7 Enterprise

### Steps to reproduce
Open up the memory profiler in Internet Explorer. Go back and forth through some of the component pages in the official docs. 

### Expected Behavior
Heap should not grow (that much)

### Actual Behavior
Memory usage just continues to grow, there is no stop (until IE crashes). Just for fun, compared to https://material.angular.io/components/categories which works as expected in this regard.

### Reproduction Link
[https://jsfiddle.net/x713mja1/](https://jsfiddle.net/x713mja1/)

**Comment by jacekkarczmarczyk** [comment]
Vue 2.5.10 has been just released with some memory leak fix, can you check if the issue still appears?

**Comment by errrken** [comment]
@jacekkarczmarczyk Will try when Vuetify docs has been updated with Vue 2.5.10. What I noticed though is that I tried above on IE Edge and Windows 10, and noticed the same issue (still with Vue 2.5.9).
