### ISSUE TITLE
[Bug Report] Cannot create large v-icon inside large v-btn

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#2783]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.89
**OS:** Mac OS 10.12.4

### Steps to reproduce
Create v-btn with attribute large and v-icon with attribute large inside.

### Expected Behavior
Should be able to create a large icon within a large button.

### Actual Behavior
The icon is not large.

### Reproduction Link
[https://codepen.io/anon/pen/EoxMGM](https://codepen.io/anon/pen/EoxMGM)

**Comment by blalan05** [comment]
Per codepen and latest version 1.5.8 this seems to be working as intended... Icon in first button is 36px. Icon in 3rd button is 36px. Am I missing something?

**Comment by blalan05** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
