### ISSUE TITLE
[Feature Request] Date pickers - Internationalization  ‘日’ in zh-cn  is unnecessary 

### ISSUE THREAD

**Issue by shihanjun19** [vuetifyjs/vuetify#2786]
## New Functionality
none

## Improvements
I hope there is no ‘日’ in date picker component
![bug](https://user-images.githubusercontent.com/10006241/33929693-55ee6e86-e025-11e7-9404-44a871d2d349.png)

like this
![default](https://user-images.githubusercontent.com/10006241/33929732-7a7dd4ee-e025-11e7-96f6-57dc3c4e7f50.png)

## Bugs or Edge Cases it Helps Avoid
none

**Comment by jacekkarczmarczyk** [comment]
This is how `toLocaleDateString` works

![image](https://user-images.githubusercontent.com/15625235/33941644-ea73fcb8-e045-11e7-8d92-82ffdb7f8812.png)

You have possibility to override the default formatting with your own function, use the `day-format` prop:

`<v-date-picker :day-format="date => date.split('-')[2]">`
