### ISSUE TITLE
[Feature Request] Generate CSS colors for styling SVG

### ISSUE THREAD

**Issue by salomvary** [vuetifyjs/vuetify#2793]
### New Functionality
The current CSS color pack provides classes for styling borders, backgrounds and text color but does not allow setting colors of SVG elements (stroke and fill properties). See also:
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

### Improvements
With SVG classes provided one could do stuff like
`<svg><circle class="blue--fill darken-2--fill red--stroke lighten-3--stroke"></circle></svg>`

As an alternative, the classes without modifier would apply to fill to achieve the same:
 `<svg><circle class="blue darken-2 red--stroke lighten-3--stroke"></circle></svg>`

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by KaelWD** [comment]
You can import the color variables, add them to your component's data, and do  
`<svg><circle :fill="colors.blue.darken2" :stroke="colors.red.lighten3"></circle></svg>`

**Comment by salomvary** [comment]
Sure you can do that, but what if you want to style your SVG using CSS?

**Comment by johnleider** [comment]
Then you can use the pre-generated css classes that are already [available](https://vuetifyjs.com/style/colors)

**Comment by KaelWD** [comment]
The current classes don't affect stroke and fill, but I don't think that's a common enough use case for us to add it to the framework. You're able to define them yourself if you want, the source for the current classes is freely available to copy and modify.

**Comment by salomvary** [comment]
>  I don't think that's a common enough use case for us to add it to the framework

Sure thing, it's your call what to include in the framework.

One more small gotcha. Colors don't seem to be exported as JavaSript variables as part of the cdn distribution (at least not in a documented way). I was looking at https://unpkg.com/vuetify/dist/vuetify.js.

**Comment by KaelWD** [comment]
That is correct, you have to import the file.

**Comment by salomvary** [comment]
👍 and thanks for your great work on Vuetify!
