### ISSUE TITLE
[Bug Report] Badge doesn't work for FAB button

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2794]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.10
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
Create a FAB button with badge

### Expected Behavior
Badge should be visible

### Actual Behavior
Badge is not visible

### Reproduction Link
[https://codepen.io/anon/pen/JMdRLo?editors=1010](https://codepen.io/anon/pen/JMdRLo?editors=1010)

**Comment by NothingWeAre** [comment]
Still an issue in 1.1.6

**Comment by marchofreason** [comment]
Hi guys,

I've just experienced this with Vuetify 1.3.12 - Still an issue it seems?

**Comment by nekosaur** [comment]
No long reproducible in 1.5.14 or 2.0
