### ISSUE TITLE
[Bug Report] Selected items not highlighted in the v-select's menu when using the tags prop

### ISSUE THREAD

**Issue by silvioiannone** [vuetifyjs/vuetify#2796]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.10
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OSX

### Steps to reproduce
Create a `v-select` component with the `tags` prop.

### Expected Behavior
The initially selected item should be highlighted in the dropdown menu.

### Actual Behavior
The initially selected item is not highlighted unless it's removed and selected again.

### Reproduction Link
[https://codepen.io/anon/pen/MrwbpW](https://codepen.io/anon/pen/MrwbpW)

### Other comments
Removing the `tags` prop will result in the dropdown menu highlighting the initially selected item already from the beginning.

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/34033965-118ce2c8-e1af-11e7-8c21-fffedfcbd79d.png)

**Comment by silvioiannone** [comment]
The thing is that it does work. The item is marked as selected in the dropdown but only if it's selected from the dropdown itself and not if it's set as selected from the beginning.

To make it clearer: in my example Text 1 is selected from the beginning. Opening the dropdown will show that both Text 1 and Text 2 are not selected even though Text 1 should be since it's in the select box (and also in the `selectedItems` data property of the `v-select` component). Now, clicking on Text 1 will remove the item from `selectedItems` and it will be removed from the select as expected. At this point if you click it again it will be added back to `selectedItems` and it will also be marked as selected in the dropdown (like it should have been from the very beginning).

Also the event fired from the `v-select` is correct:

<img width="231" alt="screen shot 2017-12-15 at 10 01 56" src="https://user-images.githubusercontent.com/8558526/34034454-e170b860-e17e-11e7-917c-7afbb4a67b28.png">

**Comment by jacekkarczmarczyk** [comment]
Values are compared using strict equality operator (`===`), so if you are comparing two different objects (even if they have same properites) it will return false. 

Here is the modified example that uses same object for `selected` and `models`, and it works as expected:
https://codepen.io/anon/pen/MrwbpW

**Comment by silvioiannone** [comment]
Sorry, you linked my example ^^

**Comment by jacekkarczmarczyk** [comment]
Sorry, correct link: https://codepen.io/anon/pen/badZEb

**Comment by silvioiannone** [comment]
Thank you, your comment helped me find an issue with my code :)
