### ISSUE TITLE
[Bug Report] wrong position of v-tooltip in tabs

### ISSUE THREAD

**Issue by itdpong** [vuetifyjs/vuetify#2800]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.4.3
**Browsers:** Chrome 63.0.3239.90
**OS:** Windows 7

### Steps to reproduce
access the following url

### Expected Behavior
a v-tooltip should show in page 2 and pointing to a folder icon only

### Actual Behavior
the v-tooltip content show in the top left corner on page 1

### Reproduction Link
[https://codepen.io/itdpong/pen/XVbBja?editors=1010](https://codepen.io/itdpong/pen/XVbBja?editors=1010)

**Comment by nekosaur** [comment]
Problem still exists on 1.1 https://codepen.io/anon/pen/OEKNKX. It can be somewhat mitigated by using `lazy` prop on `v-tabs-item`, but tooltip does not currently update its position if activator moves (during tab transition).

**Comment by KaelWD** [comment]
I don't think this is something we *can* easily fix. I suggest either waiting for the tab to be fully visible before showing the tooltip, or use `attach` (position may need adjusting to prevent clipping): <https://codepen.io/anon/pen/ErXjaO?editors=1010>
