### ISSUE TITLE
[Bug Report] Footer height property

### ISSUE THREAD

**Issue by zokipirlo** [vuetifyjs/vuetify#2802]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.11
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.12.6

### Steps to reproduce
Without using height property: `<v-footer>...</v-footer>`
With "auto" workaround: `<v-footer height="auto">...</v-footer>`

### Expected Behavior
Style with height attribute shouldn't be set on a footer component if height property is not specified. Or there should be at least an option to not set it (or make it auto), so it will wrap content.

### Actual Behavior
Footer style height is 32px, even if not set as a height property on a component.
Vue:
```
<v-footer>
   <the-footer />
</v-footer>
```
Html:
```
<footer class="footer" style="height: 32px;">...
```

There is a workaround with `height="auto"`property, which doesn't set style, but it creates an error in console.
```

[Vue warn]: Invalid prop: custom validator check failed for prop "height".
found in

---> <VFooter>
       <VApp>
         <Main> at src/layout/Main.vue
           <App> at src/App.vue
             <Root>
```

### Reproduction Link
[https://codepen.io/anon/pen/opXmvL?editors=1000](https://codepen.io/anon/pen/opXmvL?editors=1000)

**Comment by KaelWD** [comment]
Auto height will not work with `app`, that's why only pixel heights are supported. The validator could be changed to allow any string as long as `app` isn't set.
