### ISSUE TITLE
[Bug Report] Some problems with v-select

### ISSUE THREAD

**Issue by boshark** [vuetifyjs/vuetify#2805]
'auto' property of v-select does not always work - does not scroll to selected item in the list.
looks like the problem is related to number of items in select, and type of items.

There is also a problem with 'autocomplete' property and 'TAB' key when entering v-select. When value is already selected dropdown should not appear. In some cases it does. 

I've reproduced the problems in this link:

https://codepen.io/anon/pen/gopLvd?&editors=101

Good luck :)

**Comment by KaelWD** [comment]
Please follow the issue template, and only report **one** bug per issue: https://issues.vuetifyjs.com
