### ISSUE TITLE
[Bug Report] Auto propery of v-select does no work in all cases

### ISSUE THREAD

**Issue by boshark** [vuetifyjs/vuetify#2806]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.11
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
Click on v-select to activate dropdown menu
(first dropdown ok, second and third - fail)

### Expected Behavior
When click on v-select a menu should be opened with  selected item visible.

### Actual Behavior
Does not scroll to selected item in dropdown menu

### Reproduction Link
[https://codepen.io/anon/pen/gopLvd?&editors=101](https://codepen.io/anon/pen/gopLvd?&editors=101)

### Other comments
Looks like the problem is related to number of items in select ( test 2), and type of items (test 3)

**Comment by johnleider** [comment]
The **auto** prop is not compatible with **autocomplete**. One requires typing, the other requires the menu to be positioned over the select, doesn't make any sense.

**Comment by boshark** [comment]
In this case auto and autocomplete are not in the same v-select.  First and second v-selects are with auto only.

**Comment by johnleider** [comment]
That is because the first one is hitting overflow detection and the second one works as far as I can see.

**Comment by boshark** [comment]
If you reload page and directly click on v-select with "item 21" dropdown should be opened and item 21 visible. But it does not work. Same with "item 22".

Only "item 20" works as expected.

**Comment by johnleider** [comment]
Doing so still yields the same results for me, it is working. I will need some additional reproduction steps, or a third party to help confirm this.

**Comment by KaelWD** [comment]
The first three all open scrolled right to the top for me.
