### ISSUE TITLE
DatePicker type property works incorrectly

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#2808]
Here's the example, https://codepen.io/kasheftin/pen/VyvYoK
We can switch the picker from the type=date to type=month, but the revert switch does not work - only the picker's header changes, but the rest of content stays in type=month.

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.
