### ISSUE TITLE
[Feature Request] Speed-Dial: disabled options

### ISSUE THREAD

**Issue by DrSensor** [vuetifyjs/vuetify#2810]
### New Functionality
Because `v-speed-dial` is like a `v-btn` that contains`v-btn`, it is nice to have a similar option. (Also, sometimes when building complex apps there is an issue with `v-if`)

### Improvements
By make `v-speed-dial` similar to `v-btn`. Breakdown `v-btn` component into parts, something like `VBtnOpts.vue` and `VBtn.vue` then use `VBtnOpts.vue` in `VSpeedDial.vue`. By doing that it can make the module more maintainable and resist unexpected break changes (something that happened with `v-breadcrumbs`).

### Bugs or Edge Cases it Helps Avoid
None, just confusion from the end-user's perspective.

**Comment by KaelWD** [comment]
speed-dial options are just buttons, you can already use the `disabled` prop on them.

**Comment by DrSensor** [comment]
@KaelWD I see... I will test it out. 

Out of Topic. Currently, I'm using `v0.16.9` and afraid to upgrade it to `v0.17.x` because it destroys the layout of apps that I'm currently building.

**Comment by KaelWD** [comment]
Join https://chat.vuetifyjs.com for general questions like that. It's probably just the drawer changes: https://github.com/vuetifyjs/vuetify/releases/tag/v0.17.0
