### ISSUE TITLE
[Bug Report] DatePicker loses text on the current date when another date is selected

### ISSUE THREAD

**Issue by AlexKovynev** [vuetifyjs/vuetify#2812]
Vuetify 1.0.0-alpha.3
Vue 2.5.11
Browsers: Firefox 57.02
OS: Linux x86_64

You can see it in https://next.vuetifyjs.com/components/pickers
![date-error](https://user-images.githubusercontent.com/3380440/34068297-0c39e1d0-e241-11e7-9f92-5fdf55cdb72b.jpg)

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
