### ISSUE TITLE
[Bug Report] Material Icons, included via <link> index.ejs are working in electron-vue dev mode, but not after build

### ISSUE THREAD

**Issue by dverlik** [vuetifyjs/vuetify#2815]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.10
**Browsers:** Google Chrome
**OS:** Windows 7

### Steps to reproduce
Run npm run dev, press the playlist button - the checkboxes are working as intended.
Run npm run build, go to build folder and install the newly built exe.

### Expected Behavior
The checkboxes should be normally visible as checkboxes, not as text.

### Actual Behavior
 Run the installed exe, press the playlist button - and the checkboxes are not visible.

### Reproduction Link
[https://github.com/dverlik/emepetres](https://github.com/dverlik/emepetres)

### Other comments
I've tried importing the css locally, in the html, in main.js, in <style> tags. Nothing seems to work.

**Comment by nekosaur** [comment]
@dverlik If this is still a problem with latest electron template, please open an issue at that [repo](https://github.com/vuetifyjs/electron)
