### ISSUE TITLE
Make spacing helpers responsive

### ISSUE THREAD

**Issue by masteroleary** [vuetifyjs/vuetify#2823]
### New Functionality
Instead of applying padding-right to all screensizes using pr-1 I can apply pr-md-1 to apply padding-right to medium screen sizes and up

### Improvements
it matches what you are doing with the rest of the framework

### Bugs or Edge Cases it Helps Avoid
The obvious

**Comment by KaelWD** [comment]
You can do it by binding to `$vuetify.breakpoint`, but I agree that media queries would be a cleaner way to go about this.

**Comment by nekosaur** [comment]
Using `$vuetify.breakpoint` is the current solution. See previous issue https://github.com/vuetifyjs/vuetify/issues/1434
