### ISSUE TITLE
[Feature Request] Allow creating additional values in multiple select input.

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#2824]
### New Functionality
Multiple selects currently only allow selecting existing values. I'd like to allow adding additional ones.

### Improvements
I add an `@keyup` listener and add it to the array as it goes.

### Bugs or Edge Cases it Helps Avoid
It gives a way for the user to add custom options if the one they want isn't provided.

**Comment by KaelWD** [comment]
Duplicate of #1069
