### ISSUE TITLE
[Bug Report] Toolbar with tabs cuts off toolbar on mobile

### ISSUE THREAD

**Issue by smanji** [vuetifyjs/vuetify#2825]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.11
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.10.5

### Steps to reproduce
1. Navigate to: https://codepen.io/smanji/pen/mpVZPx
2. Shrink the window width-wise
3. Notice that the toolbar's title and its icons start to get cut off vertically

### Expected Behavior
The toolbar content should not get cut off vertically on smaller screen sizes -- either when viewed in portrait or landscape orientation with the device

### Actual Behavior
The toolbar content gets cut off vertically. It's really bad on mobile when viewing the device in landscape orientation -- portrait orientation isn't terrible, but it still gets cut off.

### Reproduction Link
[https://codepen.io/smanji/pen/mpVZPx](https://codepen.io/smanji/pen/mpVZPx)

### Other comments
I'm happy to change my code to workaround the issue if I'm doing something wrong. In any case, I appreciate your support with this!

**Comment by KaelWD** [comment]
This is because `<v-tabs icons` is taller to accommodate the icons, you should leave `icons` off if you are just using text. In v1.0 you can also use the `extension-height` prop on the toolbar to work around this.
