### ISSUE TITLE
[Feature Request] replace the default font 

### ISSUE THREAD

**Issue by shihanjun19** [vuetifyjs/vuetify#2826]
## New Functionality

Roboto fonts not contain Chinese characters, can I replace roboto font to noto

[https://fonts.google.com/earlyaccess#Noto+Sans+SC](url)

## Improvements
none

## Bugs or Edge Cases it Helps Avoid
none

**Comment by KaelWD** [comment]
This is already possible, just set the font the way you would normally.

**Comment by johnyluyte** [comment]
In Vuetify 1.04, if you change the font-family the normal way (e.g. put them index.html / yourStyle.css), your style **will be overwritten** by Vuetify.

Instead, you should follow this official document and change the `$body-font-family` variable of Stylus.

https://vuetifyjs.com/en/style/theme

````
    // main.styl
    $body-font-family = "Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI",
    Roboto, "Helvetica Neue", "微軟雅黑", "Microsoft YaHei", "微軟正黑體",
    "Microsoft JhengHei", Verdana, Arial, sans-serif !important;

    @require '~vuetify/src/stylus/main.styl'
````
