### ISSUE TITLE
Bug: v-select can not switch data after change event 

### ISSUE THREAD

**Issue by kristoff2016** [vuetifyjs/vuetify#2827]
Hello Team,
I have some issue that I need all of you help me find out.

I have code below:

for((item, index) in items){
 <selecte v-bind:items="items" v-model="main_select[index]"></select>

To

<selecte v-bind:items="chil_items" v-model="child_select[index]"></select>  (noted: this one is get each items list by main select ID)

}
issued: after I selected main_select: A 
then child display: items list [A1,A2,A3]

after that I switched main_select : B 

then child it should display: items list [B1,B2,B3] but it still display  [A1,A2,A3] I have to select on child select twice time in order child select show the correct  [B1,B2,B3]

I wish everyone could me out of this bug 

thanks in advance!
Here is the video that could you more understand

https://drive.google.com/file/d/1RHT5Wi_hMPLTkHfjFnmQ_XDC-ReEwJLA/view?usp=sharing

**Comment by KaelWD** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template.

Also you probably just need `nextTick()`, not that I can tell from the description you've given.
