### ISSUE TITLE
[Bug Report] Wrong V-Date-Picker year selection

### ISSUE THREAD

**Issue by willypuzzle** [vuetifyjs/vuetify#2828]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.11
**Browsers:** Firefox 57.0, Google Chrome
**OS:** Linux

### Steps to reproduce
Open a v-date-picker and select the year field then select a year.

### Expected Behavior
When I select the year the v-date-picker keeps open

### Actual Behavior
The v-date-picker closes and I have to open it again in order to select the month, then again for the day.

### Reproduction Link
[https://codepen.io/willypuzzle/pen/NXqVae](https://codepen.io/willypuzzle/pen/NXqVae)

### Other comments
I don't know if it is a willed behavior but I think that from da user point of view, open and close the datepicker, is a waste of time.

**Comment by KaelWD** [comment]
Look at [the examples](https://vuetifyjs.com/components/pickers#example-4), they use `:close-on-content-click="false"` to prevent that.

**Comment by willypuzzle** [comment]
I think that this option should be reported on documentation but I don't see it anywhere, do I report this as a bug in vuetify/doc?

**Comment by willypuzzle** [comment]
At this point is important to report the "hierarchy" of components, otherwise, we have to look always to the code.

**Comment by KaelWD** [comment]
I don't understand what you're saying. Menus have nothing to do with pickers aside from the fact that you can put one of them inside the other.

**Comment by willypuzzle** [comment]
Sorry I thought I should add the prop to picker
