### ISSUE TITLE
add new examples to docs

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#283]
add more complex example to the docs

**Comment by ruvido** [comment]
+1

A couple of things that came into my mind:

(1) One thing that I find quite obscure is how to use transitions with vuetify components. I am familiar with v-if but not so much with the bind method used (e.g. in alerts). I ended up wrapping v-alert inside a v-if, surely there is a better way for doing this:

```
<div v-if="error.show">
   <v-alert error v-bind:value="true" class="mb-5">{{error.message}}</v-alert>
</div>
```

An illustrative example would be of great help

(2) I add difficulties in setting up stylus, a brief explanation on how to set up the thing would be very appreciated

(3) concerning the vue-cli template, I was not able to have vue-router working with it. At the end, using the official webpack template from vuejs and then adding vuetify has been much simpler. Guess that was not the intent to have vuetify templates in the first place.

**Comment by jamesxv7** [comment]
I would add an example on how properly use $refs in order to share values between components. I'll try to help with a PR.
