### ISSUE TITLE
[Bug Report] Grouped list looks wrong on mini variant if opened before

### ISSUE THREAD

**Issue by pschaub** [vuetifyjs/vuetify#2830]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.11
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
1. Open to extended view in navigation by clicking on the arrow icon
2. Open the grouped list "Content Management"
3. Close the mini variant by clicking on the arrow icon

=> 4. Now you will see the bug: There is an empty space after the "content management" icon in the mini variant.. this looks wrong to me.

### Expected Behavior
In mini variant the items in the group list should not be shown as empty spaces.

### Actual Behavior
In the mini variant the items in the group list may be shown as empty spaces if opened before enabling the mini variant mode.

### Reproduction Link
[https://codepen.io/anon/pen/Rxarqw](https://codepen.io/anon/pen/Rxarqw)

![bildschirmfoto von 2017-12-19 10-02-16](https://user-images.githubusercontent.com/11846736/34148977-c9dc068c-e4a3-11e7-8048-c0cca2e65c7c.png)

**Comment by KaelWD** [comment]
#2962 was closed, seems john doesn't want to support mini with groups.

**Comment by ChadWithCalDigit** [comment]
If you don't want the spaces there when a group is expanded and then the drawer is toggled mini, you can add a `v-if="!miniVariant"` on your subitem `v-tile-list`. Here's a slightly modified version of your codepen example. https://codepen.io/anon/pen/PrRajw

**Comment by johnleider** [comment]
This _may_ slip to v3.
