### ISSUE TITLE
[Bug Report] In  picker component, @input event of <v-text-field> doesn't work

### ISSUE THREAD

**Issue by shannonliang312** [vuetifyjs/vuetify#2832]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
create a date picker component, I need emit a event when I  select one date, so I bind a function 
 (textfieldInputTest) to @input event on v-text-field.

### Expected Behavior
when pick one date, there should be an output string  in the console

### Actual Behavior
nothing happend. If I bind a funciton to the @input event of v-date-picker, it works!!! But I can't find anything about input event of v-date-picker in the document, so it's a little confused.

### Reproduction Link
[https://codepen.io/shannonliang312/pen/jwajBM?editors=1011](https://codepen.io/shannonliang312/pen/jwajBM?editors=1011)

![inputbug](https://user-images.githubusercontent.com/23253715/34151400-09f92ff0-e4e6-11e7-96f8-1f5066b072f6.png)

from the vue-dev tools, we can see that the input event is emited by picker component, not by the text field component.

please forgive my poor English, thanks!

**Comment by KaelWD** [comment]
Not a bug. The text field in the examples is just used to display the selected date.
