### ISSUE TITLE
[Feature Request] Carousel on mobile should flip images on slide, touch or by using time interval

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#2833]
### New Functionality
The Carousel should only move when either the arrows are pressed or a finger is slide across it or the timer moves it automatically.

### Improvements
It will improve support on mobile for Carousels

### Bugs or Edge Cases it Helps Avoid
Currently on mobile if we touch or slide on page the images are getting flipped in Carousel.

**Comment by KaelWD** [comment]
Can you elaborate more on what you mean by this? Those two statements contradict each other.

**Comment by vaishali-ghayal** [comment]
The Carousel should only move when either the arrows are pressed or a finger is slide across it or the timer moves it automatically.

**Comment by KaelWD** [comment]
It already does all those things though...

**Comment by vaishali-ghayal** [comment]
But if we touch anywhere on screen, then also images are getting flipped in Carousel. This should not happen.

**Comment by KaelWD** [comment]
That sounds more like a bug report than a feature request. Either way, I couldn't reproduce it. Please create a new issue with the appropriate information and reproduction steps.
