### ISSUE TITLE
[Bug Report] Toolbar items aren't vertically centered when <router-link> is added

### ISSUE THREAD

**Issue by AlexAlabyev** [vuetifyjs/vuetify#2837]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
See the codepen.

### Expected Behavior
Items to be vertically centered on the toolbar  when `<router-link>` is added on the button

### Actual Behavior
Items aren't vertically centered on the toolbar  when `<router-link>` is added on the button

### Reproduction Link
[https://codepen.io/anon/pen/NXNEeV](https://codepen.io/anon/pen/NXNEeV)

**Comment by KaelWD** [comment]
`v-btn` extends `router-link`, you should use `to=""` on the button directly.
