### ISSUE TITLE
[Bug Report] Datatable lenght incorrect when using custom-filter without search input

### ISSUE THREAD

**Issue by BatmanTheBlind** [vuetifyjs/vuetify#2847]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.3
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
1) Define a custom-filter based on a checkbox
2) Don't use the "search" string attribute
3) When checking the checkbox to filter the attribute, the  number of result is not updated

It works fine if the search string is used (even if it contains only a space)

### Expected Behavior
The number of result should be updated even if the search string is empty

### Actual Behavior
The number of result is not updated if the search string is empty, even if something else is used in the custom-filter function

### Reproduction Link
[https://codepen.io/BatmanTheBlind/pen/JMKWLv](https://codepen.io/BatmanTheBlind/pen/JMKWLv)

### Other comments
I think there is something to do in the following function inside `data-iterable.js`mixin. But I'm not comfortable enough to suggest a good fix.
```
    itemsLength () {
      if (this.search) return this.searchLength
      return this.totalItems || this.items.length
    },
```

**Comment by nekosaur** [comment]
Hm. I'm no longer sure this is a bug or something that needs to be changed. If you have a need to filter items based on things other than text input, you can just create a computed prop that filters items, as seen here https://codepen.io/anon/pen/ERqyrY

**Comment by KaelWD** [comment]
Correct, same goes for v-select. The filter functions are only called if there is a search active, non-search filtering should be done externally.
