### ISSUE TITLE
[Bug Report] CSS is overriding standard input controls

### ISSUE THREAD

**Issue by ttonyh** [vuetifyjs/vuetify#2848]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.13
**Browsers:** Firefox 56.0, Google Chrome
**OS:** Mac OS 10.13

### Steps to reproduce
Add any standard input control to a page with Vuetify included.

### Expected Behavior
Standard inputs (INPUT, SELECT, BUTTON etc.) will be show in a plain, default style.

### Actual Behavior
Most of the default styling is overridden in Vuetify's CSS. So, SELECT for instance, has not border, or click down button etc.

### Reproduction Link
[https://72nw8pk92j.codesandbox.io/](https://72nw8pk92j.codesandbox.io/)

### Other comments
It should be taken under consideration, that all input control styling should be left alone unless specific Vuetify classes are used.

**Comment by KaelWD** [comment]
That is from https://github.com/filipelinhares/ress, I'm not sure if it's something that can be easily removed.

**Comment by johnleider** [comment]
As stated above, this is part of our reset, which is common for entire frameworks to have. This helps reduce the amount of one off logic written for specific browsers during development and there are currently no plans to remove/change it.

**Comment by lauriharpf** [comment]
I understand the rationale, but the behavior increases the amount of work needed to bring Vuetify into existing Vue projects. A less intrusive CSS reset would be great if possible.
