### ISSUE TITLE
[Feature Request] Actions in data table without pagination buttons

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#2849]
### New Functionality
I want to have the actions in the data table but without the pagination buttons (because they are externally). The "Rows per page" feature should still be there.

### Bugs or Edge Cases it Helps Avoid
See: https://codepen.io/anon/pen/OzRLyV?&editors=101
There is no feature to disable the pagination buttons inside the "actions" area
of the data table **without removing the "Rows per page" feature**.

**Comment by nekosaur** [comment]
I think we assume that if you do external pagination then you take care of any potential rows per page feature yourself as well.

**Comment by nekosaur** [comment]
Use the `pagination` prop. It has a property `rowsPerPage`
