### ISSUE TITLE
Adding focus / blur / input events on text-fields

### ISSUE THREAD

**Issue by darkylmnx** [vuetifyjs/vuetify#285]
### Steps to reproduce
I would like to listen to a blur or focus event on a text-field (https://vuetifyjs.com/components/text-fields) but there seems to be nothing about this kind of things in the docs and unfortunately juste adding and @event didn't seem to do the trick any idea on how to acheive this ? as it's not a real input but a custom element ?

### Versions
0.9.4

**Comment by ralphchristianeclipse** [comment]
@darkylmnx maybe you can try to do @blur.native="blurHandler"

**Comment by darkylmnx** [comment]
Will this would work only if the component's base node was an input, which
I doubt because there's a label

**Comment by hereiscasio** [comment]
it's surprise for me that i can directly to use `@blur` with modifier `.native` on `<v-text-field>`

actually, it will not work if i use `@blur.native`
so . . . i think `<v-text-field>` is a **_Vue_** component . . . 

Would it be a " proper way " if we only let `@blur.native` work, not `@blur` on `<v-text-field>` ?
