### ISSUE TITLE
[Bug Report] Using clearable on a Select - Customized item text and value results in a console error

### ISSUE THREAD

**Issue by CarbonFactory** [vuetifyjs/vuetify#2850]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.10
**Browsers:** Firefox 56.0
**OS:** Windows 10

### Steps to reproduce
Select any item
Remove the item by clicking on the X icon
[Vue warn]: Error in render: "TypeError: Cannot read property 'text' of null"

### Expected Behavior
No errors should be logged and the persistent hint should be cleared

### Actual Behavior
[Vue warn]: Error in render: "TypeError: Cannot read property 'text' of null" error is logged
Persistent hint is still retaining the old selected value

### Reproduction Link
[https://codepen.io/anon/pen/xpEOVK?editors=1011](https://codepen.io/anon/pen/xpEOVK?editors=1011)

**Comment by CarbonFactory** [comment]
Hello, I modified the hint expression to handle NULL case and it works as expected. 
Please check if this can be built into the component itself to avoid extra code.

Please close if it cannot be done.

**Comment by KaelWD** [comment]
Create an issue on https://github.com/vuetifyjs/vuetifyjs.com if it's from there. There is no way for us to handle errors like that in the framework, you have to do it yourself.
