### ISSUE TITLE
Footer applies a dark tint get text color same backgroud color

### ISSUE THREAD

**Issue by phainv** [vuetifyjs/vuetify#2852]
For example:
``` vue
<v-footer dark class="p-3">
  <v-spacer></v-spacer>
  <div>© {{ new Date().getFullYear() }}</div>
</v-footer>
```
I apply theme `dark` only for this component. This text color same background color
Not applies dark in `v-app` component.

Thanks.

**Comment by jacekkarczmarczyk** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template. For general questions please join the official [discord chat](https://chat.vuetifyjs.com)

**Comment by phainv** [comment]
thanks. i've send other issue
