### ISSUE TITLE
[Bug Report] v-time-picker broken when `pm` is selected

### ISSUE THREAD

**Issue by hikaruworld** [vuetifyjs/vuetify#2855]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.11.6

### Steps to reproduce
1. Set system time to morning `am` ( example 10:20)<br />
1. popup `v-time-picker`.
1. select `PM`

### Expected Behavior
change `pm` time

### production mode
browser hung up.

### develop mode
console error.

```
vue.js:584 [Vue warn]: You may have an infinite update loop in watcher with expression "period"

found in

---> <VTimePicker>
       <VApp>
         <Root>
````

### Reproduction Link
[https://codesandbox.io/s/91r26o2vw](https://codesandbox.io/s/91r26o2vw)

### Other comments
sine 0.14.8

**Comment by jacekkarczmarczyk** [comment]
This has been fixed in https://github.com/vuetifyjs/vuetify/pull/2664
