### ISSUE TITLE
[Feature Request] Adding first and last page button to data table component

### ISSUE THREAD

**Issue by devistar** [vuetifyjs/vuetify#2859]
### New Functionality
Go to first and last page in data table. 

### Improvements
It's more convenient than making multiple clicks on previous or next.

### Bugs or Edge Cases it Helps Avoid
Nothing more to say.

**Comment by johnleider** [comment]
@nekosaur can't this already be done with a custom slot?

**Comment by devistar** [comment]
Maybe it can be done with a custom slot but why not add it basically or as an option ? This is a convenient and common feature in pagination. Do not you agree?

**Comment by nekosaur** [comment]
No I don't think we have a slot for customizing actions footer actually. And I might agree that this is common enough functionality (and a small enough implementation) that it might be worth it to include through a prop. Drawing a blank on a good prop name though. Should probably start with `show-`.

**Comment by chongma** [comment]
is this documented?  how does it work?

**Comment by nekosaur** [comment]
It is available in 2.0

https://next.vuetifyjs.com/en/components/data-tables#customizing-footer
