### ISSUE TITLE
Add Sidebar example

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#286]
Please add an example of a sidebar implementation, such as on YouTube, Google Keep, Google Contacts etc.:
* On Desktop sidebar can be opened and closed by changing the width of the content. Sitebar is under the header and does not overlapping it
* On Mobile The sidebar can open and close overlapping content and header

**Comment by dohomi** [comment]
@cawa-93 we have the plan to introduce all sidebar options from the specs. It is currently target for 0.11 release

**Comment by johnleider** [comment]
All sidebar examples from spec are now in docs on the next branch.
