### ISSUE TITLE
Question: how to create a fluid layout like inline-block?

### ISSUE THREAD

**Issue by averri** [vuetifyjs/vuetify#2862]
I would like to create a layout that resembles the following:

![image](https://user-images.githubusercontent.com/1898447/34310059-341be53e-e74d-11e7-847c-b6bb8b0657f3.png)

Please note that the checkbox is positioned just after the button, with a very short and constant space regardless the window width. If there is no space to render the components in the same row, they can be positioned in multiple rows.

How to achieve this with Vuetify components?

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by averri** [comment]
Thanks @johnleider, I've posted there.
