### ISSUE TITLE
Is it possible to add multiple value in a single column header in datatabe?

### ISSUE THREAD

**Issue by rosnaib11** [vuetifyjs/vuetify#2863]
I have a table that has only single column that contains all of my data inside. I need to set values to those data inside for the search function

Its like 
```
headers: [
        {
          text: '',//Transaction No.
          sortable: false,
          value: 'transaction_id',
          align: 'left'
        },
        {
        	value:'employee_name',
        	visibility :'hidden',
        	sortable: false,
        	position:'absolute'
        },
        {
        	value:'business_date',
        	visibility :'hidden',
        	sortable: false,
        	position:'absolute'
        },
        {
        	value:'restaurant_number',
        	visibility :'hidden',
        	sortable: false,
        	position:'absolute'
        }
]
```
Is it possible to make it something like, since I have only single column that I merge all my data

```
headers: [
        {
          text: '',//Transaction No.
          sortable: false,
          value: ['transaction_id', 'business_date','employee_name','restaurant_number'],
          align: 'left'
        },
]
```

So that I don't need to specify each td to put values.

I can't even properly set blank `<td style="position:absolute !important; visibility:hidden !important;">`</td> to hidden there's always remain some white-space.

**Comment by jacekkarczmarczyk** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
