### ISSUE TITLE
[Feature Request] Datatable Conditional cell or row color

### ISSUE THREAD

**Issue by natxocc** [vuetifyjs/vuetify#2864]
### New Functionality
It is very usefull for conditional format on cells depending their value to have color to identify, for example, values out of range.

### Improvements
Can be a prop on Datatable column to identify a method function to describe the limits of the value

### Bugs or Edge Cases it Helps Avoid
Difference from row and cell class color.

**Comment by KaelWD** [comment]
This is something you can handle yourself with class bindings: `<td :class="['text-xs-right', props.item.calories > 300 ? 'red' : 'green']">`
