### ISSUE TITLE
[Bug Report] Raised button inside navigation drawer has incorrect text color (white instead of black)

### ISSUE THREAD

**Issue by dima74** [vuetifyjs/vuetify#2865]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
Create basic layout with `<v-navigation-drawer>` and put `<v-btn color="primary">` inside it

### Expected Behavior
button text is white

### Actual Behavior
button text is black

### Reproduction Link
[https://codepen.io/dima74/pen/NXbREQ](https://codepen.io/dima74/pen/NXbREQ)

**Comment by jacekkarczmarczyk** [comment]
Fixed in 1.0.0-alpha.3 https://codepen.io/anon/pen/qpqxmy
