### ISSUE TITLE
v-text-field is generating unused space when using 'single-line'

### ISSUE THREAD

**Issue by averri** [vuetifyjs/vuetify#2867]
The v-text-field is creating an unused space when using the attribute 'single-line'.

![image](https://user-images.githubusercontent.com/1898447/34326407-164c0b9a-e8a3-11e7-9678-1a2b928d1687.png)

https://codepen.io/averri/pen/xpRLML

**Comment by nekosaur** [comment]
Please use the following link when creating a new issue:

https://issues.vuetifyjs.com

If your issue was not created using the app above, it will be closed immediately.
