### ISSUE TITLE
input height

### ISSUE THREAD

**Issue by Zeph33** [vuetifyjs/vuetify#287]
#253 Not completely corrected

calculateInputHeight also call on: 
```javascript
watch: {
  ...
  value () {
      this.lazyValue = this.value
      this.validate()
      this.calculateInputHeight()
    }
}
``` 
If input is hide when assign value input.scrollHeight => 0 and inputHeight assigned to 0
See sample : [http://codepen.io/anon/pen/WpaQOg](http://codepen.io/anon/pen/WpaQOg)
click button => _**hide and change**_ 
click button => _**show**_ 
now inputHeight is 0

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/TextField.js#L103
