### ISSUE TITLE
[Feature Request] Access theme colors in stylus files

### ISSUE THREAD

**Issue by WouterFlorijn** [vuetifyjs/vuetify#2875]
### New Functionality
Not having to declare theme colors twice (in JS and stylus).

### Improvements
Allowing for a single source of truth regarding your theme colors.

### Bugs or Edge Cases it Helps Avoid
Mismatching styles when you change a color in JS and forget to update in in stylus or vice-versa.

**Comment by KaelWD** [comment]
This is something you'll have to implement yourself. I've tried doing something similar before but it doesn't really work on a framework level. 

https://github.com/shama/stylus-loader/issues/113#issuecomment-240307873
