### ISSUE TITLE
[Bug Report] local material icon dislocation

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#2877]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.13.2

### Steps to reproduce
In an icon button with `fab small`
If use google.com url link of material icon,every thing is work fine like [codepen link](https://codepen.io/anon/pen/WdRLaP)
But when link the icon font under local by `import 'material-design-icons/iconfont/material-icons.css'`
will dislocation position
![dislocation position exmple](https://ws2.sinaimg.cn/large/006tNc79gy1fmvkf5et07j309g02saa2.jpg)

### Expected Behavior
local icon font show small as url link font in `fab small` icon button

### Actual Behavior
button dislocation position

### Reproduction Link
[https://codepen.io/anon/pen/WdRLaP](https://codepen.io/anon/pen/WdRLaP)

**Comment by KaelWD** [comment]
The codepen works, and is no different using https://unpkg.com/material-design-icons@3.0.1/iconfont/material-icons.css

Please create a reproduction that will actually show the error, such as a github repo.

**Comment by eduardo76** [comment]
I had the same problem.
When using import **'material-design-icons/iconfont/material-icons.css'** the icons gets displaced.

**Wrong**
![wrong](https://user-images.githubusercontent.com/12026259/36632854-9e941f54-196a-11e8-9ee6-6e2d51ea1ff2.PNG)
**index.html**
`<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel="stylesheet" type="text/css">`
**main.js**
`import 'material-design-icons/iconfont/material-icons.css'`


**Right**
![right](https://user-images.githubusercontent.com/12026259/36632866-c0e9d080-196a-11e8-924a-c9e5767e34ec.PNG)
**index.html**
`<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet" type="text/css">`
**main.js**
`//import 'material-design-icons/iconfont/material-icons.css'`

**Comment by philwolstenholme** [comment]
This is a CSS cascade/specificity issue.

If you load the the local Material Icons CSS before loading Vuetify's CSS, then the icon will be displayed as `inline-block` (from `.material-icons`), and this will cause the icon to be positioned at the top of the FAB button.

If you load the local Material Icons CSS after loading Vuetify's CSS, the the icon gets displayed as `inline-flex` (from `.icon`), and the icon is correctly positioned.

**Comment by sorxrob** [comment]
Thanks @philwolstenholme ! I just added this to my vue files with misplaced icons in buttons.

```
.icon {
  display: inline-flex !important;
}
```

**Comment by PaulPatena** [comment]
@philwolstenholme, the inverse of your suggestion fixed it for me, including Material Icons CSS before Vuetify CSS is correctly rendering. 
![wrong](https://user-images.githubusercontent.com/14339232/41412883-c330f768-7024-11e8-91af-dd0317d4172d.png)
![right](https://user-images.githubusercontent.com/14339232/41412897-d72c42fe-7024-11e8-8436-1bf471294216.png)

I'm using the following {"material-design-icons-iconfont": "^3.0.3", "vue": "^2.5.2", "vue-router": "^3.0.1","vuetify": "^1.0.0"}

**Comment by NikoNagy** [comment]
@philwolstenholme Thanks, you saved me hours !

@PaulPatena Thanks for the screens 👍
