### ISSUE TITLE
[Bug Report] v-select with combobox option uses searchValue when blurring

### ISSUE THREAD

**Issue by rokkie** [vuetifyjs/vuetify#2878]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
1. Create a v-select with combobox option
2. Make sure items are _objects_ (not just primitives)
3. Select an item from the list
4. Blur the field by e.g. clicking outside

### Expected Behavior
The `itemValue` to be the the `value` option of the selected item.

### Actual Behavior
The `itemValue` is the `text` option of the selected item.

### Reproduction Link
[https://codepen.io/rokkieb/pen/XVpOEg](https://codepen.io/rokkieb/pen/XVpOEg)

**Comment by johnleider** [comment]
Not a bug, I mean, technically. Yes, it does not work, but it is outlined in the docs that the current implementation only accepts primitive values.

**Comment by rokkie** [comment]
Do I need to change/update the issue then?

**Comment by johnleider** [comment]
I'm going to keep it around and tag for 1.1 as that is the form components refactor.
