### ISSUE TITLE
Sidebar removeEventListener

### ISSUE THREAD

**Issue by routegroup** [vuetifyjs/vuetify#288]
Sidebar throws removeEventListener when is removed by conditional statements. Probably can be related to #263, beforeDestroy method.

### Steps to reproduce
1. Look to reproduction link
2. Click sign in
3. Click logout
4. Check console

### Versions
Vue: 2.2.6
Vuetify: 0.9.4
OS: macOS Sierra 10.12.3
Browser: Google Chrome 56.0.2924.87

### What is actually happening ?
Throws "TypeError: Cannot read property 'removeEventListener' of null".

### Reproduction Link
https://jsfiddle.net/fudin/u7kuLb6f/

**Comment by johnleider** [comment]
Applications all require the ```v-app``` component. https://jsfiddle.net/fwrc3hw1/
