### ISSUE TITLE
[Feature Request] Add Cordova/Phonegap + Webpack template into documentation

### ISSUE THREAD

**Issue by kevinqqnj** [vuetifyjs/vuetify#2880]
### New Functionality
Vuetify is a very attractive framework for both Mobile and Desktop app, so if want to build Cross-Platform application, there should be a ready-for-use Cordova+Vuetify+Webpack template, and put this information into document.
> Reference: 
- http://framework7.io/vue/
- https://github.com/centrual/cordova-template-framework7-vue-webpack

### Improvements
I've built several Mobile-only Apps successfully by using cordova template. So prepared a template here - [Cordova+Vuetify+Webpack template](https://github.com/kevinqqnj/cordova-template-vuetify-webpack). This template need to be reviewed and refactored if needed.

### Bugs or Edge Cases it Helps Avoid
This [template](https://github.com/kevinqqnj/cordova-template-vuetify-webpack) need to be reviewed and refactored if needed. Now it only includes vue-router function.

**Comment by johnleider** [comment]
@maurop123 can we get this integrated?

**Comment by maurop123** [comment]
@johnleider Yes we can! I can provide an ETA later today.

**Comment by ksankumar** [comment]
@kevinqqnj Not working when i create project with 
`phonegap create HelloVue --template cordova-template-vuetify-webpack`

```
Error: Unhandled "error" event. (  Error from Cordova Fetch: Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: cordova-template-vuetify-webpack@latest
```

**Comment by kevinqqnj** [comment]
@ksankumar, just published to npm. now it's ok:
phonegap create <your_project> --template cordova-template-vuetify-webpack

**Comment by ksankumar** [comment]
Working well.

**Comment by ksankumar** [comment]
npm run dev command not working

**Comment by johnleider** [comment]
There is now a repository for this template, please post any issues there, thank you.

https://github.com/vuetifyjs/cordova
