### ISSUE TITLE
[Feature Request] Custom Filter on autocomplete

### ISSUE THREAD

**Issue by nueko** [vuetifyjs/vuetify#2881]
### New Functionality
it will allow limiting and filtering the result 

### Improvements
it will make app faster for big data as it can be limited
maybe like `autocomple="bool|filterFn"`

### Bugs or Edge Cases it Helps Avoid
-

**Comment by KaelWD** [comment]
Already possible, use the `filter` prop. 

Here's the default filter function: https://github.com/vuetifyjs/vuetify/blob/74553209a26255e9bff33ad98a6fac0d62f0212b/src/components/VSelect/mixins/select-autocomplete.js#L14-L23

**Comment by nueko** [comment]
that's not listed here https://next.vuetifyjs.com/components/selects#api

**Comment by KaelWD** [comment]
Yes it is, 2nd item on page 3

**Comment by nueko** [comment]
ah, pagination. sorry

**Comment by KaelWD** [comment]
vuetifyjs/vuetifyjs.com#122
