### ISSUE TITLE
[Feature Request] Data Table expand all expandable per default 

### ISSUE THREAD

**Issue by eggnaube** [vuetifyjs/vuetify#2890]
### New Functionality
Expand all slots on a v-data-table per default. Currently i have to click each row to expand. 

### Improvements
I have to iterate all rows and emit a click event.

### Bugs or Edge Cases it Helps Avoid
Invalid "expanded" value on row.

**Comment by zikeji** [comment]
Sounds like the user wants an "expandAllByDefault" prop of some sort.

A temporary solution: https://codepen.io/anon/pen/aEJeVo

**Comment by johnleider** [comment]
@nekosaur thoughts on this?

**Comment by nekosaur** [comment]
I think we should perhaps expose the internal `expanded` array through a `.sync` prop, similar to how we do it for `selected` through the `v-model`. That way you can easily get the functionality request in this issue, and you get fine-grained external control of expanded rows.

**Comment by MateiNenciu** [comment]
+1 for this feature

**Comment by johnleider** [comment]
Please don't lost comments saying +1. Github added reactions where you can
voice your interest and have it be sortable for the devs. Thank you

**Comment by johnleider** [comment]
Is this something you think you can still do for v1.1 @nekosaur ?

**Comment by AakifMushtaq** [comment]
Could anyone please let me know if this feature was ever implemented and if so how to use it ? I can't seem the workaround to get to work it is not letting me compile. 
![Capture](https://user-images.githubusercontent.com/7447174/57798621-2af48100-771b-11e9-89f5-8d4c931361dd.JPG)

**Comment by MestreKarin** [comment]
@AakifMushtaq I got this error too, so I typecast to `any` and compiled with no errors.

    let table: any = this.$refs.dTable;
    this.$set(table.expanded, item.name, true);

**Comment by VitalickS** [comment]
Try look at this example
`<v-data-table :expanded="items" .... > `
or
`<v-data-table :expanded.sync="copyArrayOfItems" .... > `
First way just expand all items; second way for tracking selected items by `copyArrayOfItems`

**Comment by miryamfv** [comment]
@VitalickS yes that works

**Comment by darkbasic** [comment]
Shouldn't expanded be a v-model instead, like for the selected rows?
