### ISSUE TITLE
[Bug Report] Checkbox does not have docs in https://vuetifyjs.com/components/

### ISSUE THREAD

**Issue by virtuecoder** [vuetifyjs/vuetify#2892]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.11.6

### Steps to reproduce
.

### Expected Behavior
.

### Actual Behavior
.

### Reproduction Link
[https://codepen.io/](https://codepen.io/)

**Comment by KaelWD** [comment]
Issues with the documentation should be submitted to the documentation repo. 

That said, checkboxes **are** documented, under selection controls.
