### ISSUE TITLE
[Bug Report] Navigation Drawer Activates on Route Change

### ISSUE THREAD

**Issue by campbecf** [vuetifyjs/vuetify#2894]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.108
**OS:** Mac OS 10.12.6

### Steps to reproduce
1. Pull repo
2. yarn
3. yarn run dev
4. Change to any other route (click living, etc..)

### Expected Behavior
Drawer should stay closed

### Actual Behavior
Drawer pops open and will stay open forever

### Reproduction Link
[https://github.com/campbecf/vue-city/tree/5abf412f699c20ee45ce59430ebd965df20aa2ab](https://github.com/campbecf/vue-city/tree/5abf412f699c20ee45ce59430ebd965df20aa2ab)

### Other comments
Hopefully I'm not doing wrong, this is a learning project for Vue.

**Comment by campbecf** [comment]
Adding 

```
    temporary
    hide-overlay
```

Seems to fix this, but I'm not sure if that is intended?

**Comment by johnleider** [comment]
In the docs there is a prop **disable-route-watcher**.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by KaelWD** [comment]
We've decided that this behaviour doesn't really make sense, only temporary and mobile drawers should react to route changes, and they should never open themselves, only close.
