### ISSUE TITLE
[Feature Request] Easily positionning a fab in top of a footer (position relative to other components)

### ISSUE THREAD

**Issue by slimee** [vuetifyjs/vuetify#2895]
### New Functionality
Currently if you have a footer and a bottom right button, the button will be bad positionned.
A good position for my bottom right button when using a footer (the button should go up)

### Improvements
It would be nice if the bottom attribute will take care of the existence of a footer. The button should be at the bottom, but upper than the footer instead of walk on it.

### Bugs or Edge Cases it Helps Avoid
A layout conflict between the footer and the fab.

**Comment by slimee** [comment]
Maybe a more general system would be nice, like new attributes defining relative positionning:

<button top-of="footer" right/>
<footer/>

**Comment by johnleider** [comment]
Along with this update, I want to integrate snackbar into the application so that, per spec, the fab can be moved up if a snackbar comes under it.

**Comment by KaelWD** [comment]
Snackbars are already covered under #1852

**Comment by morgler** [comment]
Looking forward to this feature! Is there a workaround I could use in the meantime?

**Comment by morgler** [comment]
Btw: just saw, that this behavior is **not** in line with Material Design guidlines:

![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1gXnDalMO0XMkGKSe-fqAfbSX_4kk9z-9%2Fanatomy-fab-dont.png)

The FAB should rather overlap the bottom bar like so:

![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1hIkcwMS6C3V2ZdFJmYV_VAIWPfU6dxXC%2Fanatomy-fab-overlap.png)

I will try to alter my mixin from above to create this recommended behavior.

**Comment by johnleider** [comment]
Unfortunately this did not make the cut for v2.0 as we intend to pull the `v-btn` **fab** functionality into its own component to better scope this functionality and not to bloat `v-btn` any further.

Thank you to everyone for your patience on this.

**Comment by johnleider** [comment]
Closing as duplicate of #1852

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
