### ISSUE TITLE
[Bug Report] fill-height prop is broken, and renders rows as columns.

### ISSUE THREAD

**Issue by ray-winkelman** [vuetifyjs/vuetify#2896]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 61.0.3163.100
**OS:** Linux x86_64

### Steps to reproduce
Paste This:
```
<div id="app">
  <v-app>
    <main>
      <v-container fill-height>
        <v-layout row wrap align-start>
          <v-flex class="text-xs-center">
            <v-btn>test</v-btn>
          </v-flex>
        </v-layout>
        <v-layout row wrap align-end>
          <v-flex class="text-xs-center">
            <v-btn>test</v-btn>
          </v-flex>
        </v-layout>
      </v-container>
    </main>
  </v-app>
</div>
```
JS:
```
new Vue({
  el: '#app',
  data:function(){
    return {}
  }
})
```

### Expected Behavior
The first button should be at the top, second should be at the bottom of the screen. 

### Actual Behavior
No.

### Reproduction Link
[https://codepen.io/anon/pen/XVRKde](https://codepen.io/anon/pen/XVRKde)

**Comment by KaelWD** [comment]
What are you expecting it to fill the height of? `<main>` does not have a set height, so it's only as big as its content. Either remove the `<main>` or use a `v-content` instead.

**Comment by ray-winkelman** [comment]
Go to the codepen and remove the `main` tag. Nothing will change.

**Comment by ray-winkelman** [comment]
Update: Replacing `<main>` with `<v-content>` fixed it.

**Comment by mitar** [comment]
I had the same issue, I resolved it by adding one column layout first:

```
<v-container fill-height>
  <v-layout column>
    <v-layout row wrap>
      <v-flex>
        ...
      </v-flex>
    </v-layout>
    <v-layout row wrap>
      <v-flex>
        ...
      </v-flex>
    </v-layout>
  </v-layout>
</v-container>
```
