### ISSUE TITLE
[Bug Report] Not able to get selected item when i was go with scoped slots, can't close selected item

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#2898]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Windows 10, Android, Windows, iOS

### Steps to reproduce
Select the item
check the selected item model in on-change action
click the close icon in selected item(v-chip)
Try to search city instead of name

### Expected Behavior
Need to get selected item with any action/method
Need to close/delete the selected item
Like to find 2 or more item properties

### Actual Behavior
Not able to receive selected item
Not able close selected item
Not able to search with 2 or more properties. (In my core i m trying to search either name or city)
On-change event triggering 2 times

### Reproduction Link
[https://codepen.io/ksankumar/pen/rpmWyO?editors=1010](https://codepen.io/ksankumar/pen/rpmWyO?editors=1010)

**Comment by johnleider** [comment]
We discussed and resolved this in the community.
