### ISSUE TITLE
Modal button becomes unresponsive after page refresh 

### ISSUE THREAD

**Issue by rusenask** [vuetifyjs/vuetify#29]
I noticed that modal buttons become unresponsive after page refresh, navigating to some other page and back again makes it responsive again. Not sure how to debug this, currently just trying to  avoid modals

**Comment by johnleider** [comment]
Could you please supply the following?

* browser
* vue and vuetify version
* example of your code

Thank you.

**Comment by rusenask** [comment]
* browser - Chrome Version 54.0.2840.98 (64-bit)
* vue - 2.1.0, vuetify - 0.7.6
* nothing fancy, just took some code from the docs - https://github.com/vuetifyjs/docs/blob/9e3ed67cbf9f0e4acc74d5d0b45b5c6a26eabb17/src/views/ModalsView.vue, since I noticed that it's not always working - I never commited it. If you don't see this happening on your machine - I could add some code back. It would also be interesting to test it on different browsers. Anyway, really good work with vuetify, thanks! :)

**Comment by johnleider** [comment]
Could you upgrade to vuetify@0.7.9 and vue@2.1.6? There were build changes in vuetify to compensate some updates in vue and I think you are right around those version releases.

**Comment by rusenask** [comment]
Updated, added modal back and now I cannot reproduce that problem anymore. We can probably close this issue, thanks!

**Comment by johnleider** [comment]
tyvm!
