### ISSUE TITLE
v-select drop down menu doesn't align with input box at first click

### ISSUE THREAD

**Issue by leopsidom** [vuetifyjs/vuetify#2900]
Trying to use `v-select` with autocomplete feature, my code is as follows:

```
  <v-app>
    <v-card color="grey lighten-4" flat>
      <v-card-text>
        <v-container fluid>
          <v-layout row wrap>
            <v-flex xs12 sm6>
              <v-select
                :items="[1,2]"
                label="testTop"
                autocomplete
              >
              </v-select>
            </v-flex>
          </v-layout>
        </v-container>
      </v-card-text>
    </v-card>
  </v-app>
```

But at the first click of the select field the drop down doesn't align with the input box, it's left shifted. How should I fix this?

![image](https://user-images.githubusercontent.com/12235069/34451102-bab1f678-ece9-11e7-8841-3ac689e0f600.png)

**Comment by jacekkarczmarczyk** [comment]
When you created this issue, you were given a link to a template in order to supply us with the information we require to help you. Please open a new issue using that template. For general questions please join the official [discord chat](https://chat.vuetifyjs.com)
