### ISSUE TITLE
[Bug Report] V-chip avatar destroyed inside the v-list

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#2906]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Windows 10

### Steps to reproduce
Created v-chip inside the v-list, avatar got destroyed

### Expected Behavior
v-chip avatar should be visible properly 

### Actual Behavior
avatar image shape got destroyed

### Reproduction Link
[https://codepen.io/ksankumar/pen/LeyrXO](https://codepen.io/ksankumar/pen/LeyrXO)

**Comment by zikeji** [comment]
Expected behavior. The avatar / action slot on a v-list-tile does not support v-chip elements.

**Comment by KaelWD** [comment]
This has been fixed in 1.0, but you have to use the correct markup. Using `v-list-tile-avatar` inside a `v-chip` will never work. 

https://codepen.io/anon/pen/JMNaRq?editors=1000
