### ISSUE TITLE
[Bug Report] Problem with form validation in Safari 

### ISSUE THREAD

**Issue by cristoferfb** [vuetifyjs/vuetify#2907]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Safari
**OS:** Mac OS 10.11.6

### Steps to reproduce
1.- Insert a valid e-mail
2.- Insert any password

(in safari) 

### Expected Behavior
v-button set from "disable" to "enable"

### Actual Behavior
v-button don't set his validate status and get some errors in javascript console

### Reproduction Link
[https://codepen.io/cristoferfb/pen/JMNqxJ](https://codepen.io/cristoferfb/pen/JMNqxJ)

### Other comments
it works fine in other browsers like firefox and chrome, it own form (https://issues.vuetifyjs.com/) dont works in safari

**Comment by nekosaur** [comment]
And what are the errors in console?

**Comment by cristoferfb** [comment]
U can see it in the Reproduction link but this is one of these:

`[Vue warn]: Error in callback for watcher "errorBag": "TypeError: Object.values is not a function. `

https://issues.vuetifyjs.com/ have the same error.

**Comment by KaelWD** [comment]
- what Safari version?
- are you using babel-polyfill?

**Comment by praveenpuglia** [comment]
I don't have `Mac OS 10.11.6`. I have 10.13.2 and I don't see any error in Safari Console.
![image](https://user-images.githubusercontent.com/313363/34469493-3f906df8-ef46-11e7-8852-99862ce69756.png)

**Comment by cristoferfb** [comment]
I am using Versión 9.1.2 (11601.7.7) of Safari

**Comment by KaelWD** [comment]
Safari 9 requires a polyfill. 

https://codepen.io/anon/pen/XVgpoZ?editors=1010
