### ISSUE TITLE
[Bug Report] Route not updated when swiping tab items

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2911]
### Versions and Environment
**Vuetify:** 1.0.0-beta.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Windows 10

### Steps to reproduce
1. Open the reproduction link
2. Click the tabs and look how route changes
3. Swipe the tab item (content)

### Expected Behavior
3. Route should upate after swiping the content

### Actual Behavior
3. Route doesn't update

### Reproduction Link
[https://codepen.io/anon/pen/zpzZOa](https://codepen.io/anon/pen/zpzZOa)

**Comment by jingzheshan** [comment]
https://codepen.io/jingzheshan/pen/rpwowr?editors=1010#0

**Comment by johnleider** [comment]
After toying around with this, I'm not convinced that this would be easy, due to how router-link treats the **to** property.
