### ISSUE TITLE
[Bug Report] v-card ripple throws warning when used like v-ripple directive

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#2912]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
- Use `:ripple` attribute with an object in a `v-card`
- Click the card

### Expected Behavior
No warning polluting the console, and `v-card` ripple behaviour that is compatible with `v-ripple` directive.

### Actual Behavior
Ripple works using intended colour, but throws warning: 
```
[Vue warn]: Invalid prop: type check failed for prop "ripple". Expected Boolean, got Object.
```

### Reproduction Link
[https://codesandbox.io/s/n08k1lv2w0](https://codesandbox.io/s/n08k1lv2w0)

**Comment by jacekkarczmarczyk** [comment]
That's fixed in 1.0 (however 1.0-beta doesn't properly pass prop value to the ripple directive, this is fixed by ec9fcae39d982eddb0b51f866684eb85682c8ba8)
