### ISSUE TITLE
[Bug Report] Wrong hover color for dark themed list

### ISSUE THREAD

**Issue by Seraf** [vuetifyjs/vuetify#2914]
### Versions and Environment
**Vuetify:** 1.0.0-beta.1
**Vue:** 2.5.13
**Browsers:** Chromium 63.0.3239.84
**OS:** Ubuntu undefined

### Steps to reproduce
Just go hover a list item and you will see a really dark background

### Expected Behavior
The hover on the list shouldn't be so black but more faded.

### Actual Behavior
Currently, the background is using the expansion-panel focus one : https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_lists.styl#L18

The expansion panel has a value of `0.7` while it was a `0.12` before.
The change have been introduced here : https://github.com/vuetifyjs/vuetify/commit/f0764a769124778f60ad007cb2ed6fe7f402c8b1#diff-5a5680a23ec40dee49d87a222c29863aL65

I'd recommend switching back to `0.12`, or a `rgba(255,255,255,0.07)`

### Reproduction Link
[https://codepen.io/Seraf42/pen/QOPGEr](https://codepen.io/Seraf42/pen/QOPGEr)

**Comment by TizianPlaying** [comment]
Hello,
i´m not sure but i think the bug is back.
I found it in the Selects Input Components.

https://vuetifyjs.com/en/components/selects

![github123](https://user-images.githubusercontent.com/29901011/49924913-bc836c80-feb7-11e8-9521-9acc459d02ec.jpg)

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
