### ISSUE TITLE
[Feature Request] Allow keyboard/string entry for dates when using date picker

### ISSUE THREAD

**Issue by m2de** [vuetifyjs/vuetify#2915]
### New Functionality
Ideally the user should be able to tab through the UI and when hitting a date field, enter the date using the keyboard (e.g. 21/11/2018). Currently the user has to click a date.

### Improvements
This shouldn't break any existing functionality

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by jacekkarczmarczyk** [comment]
It is possible now, see the example in docs https://vuetifyjs.com/components/pickers#example-5

**Comment by joeydebreuk** [comment]
Can you update the link? Its broken...

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/components/date-pickers#date-pickers-formatting-date
