### ISSUE TITLE
[Bug Report] Console warning when I click on a tab

### ISSUE THREAD

**Issue by Seraf** [vuetifyjs/vuetify#2921]
### Versions and Environment
**Vuetify:** 1.0.0-beta.1
**Vue:** 2.5.13
**Browsers:** Chromium 63.0.3239.84
**OS:** Ubuntu undefined

### Steps to reproduce
Click on the `application` tab, then click on the `pipeline` one.
You will get a warning message in the console.

### Expected Behavior
There shouldn't be any warning

### Actual Behavior
When you click a tab, `activeTab` gets changed twice for some reason.

### Reproduction Link
[https://codepen.io/Seraf42/pen/rpwGXL](https://codepen.io/Seraf42/pen/rpwGXL)

**Comment by jvanst** [comment]
I have also run into this issue. 
Seems to happen when using named routes with the :to prop on `<v-tab>`.

Here is the named routes, eg `:to="{ name: 'about' }`
https://codepen.io/jvanst/pen/vpZvWE

Here is the same code but with a string location, eg `to="/about"`
https://codepen.io/jvanst/pen/eyRxwp
