### ISSUE TITLE
[Bug Report] Undefined props end up as classes

### ISSUE THREAD

**Issue by lyzs90** [vuetifyjs/vuetify#2922]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.4.4
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
Create a v-layout or v-container element with some prop like 'red' or 'your-custom-class'

### Expected Behavior
Should not apply any classes / styling unless it was specified in the component API

### Actual Behavior
Applies the props as classes

### Reproduction Link
[https://codepen.io/lyzs90/pen/WdOgaX](https://codepen.io/lyzs90/pen/WdOgaX)

### Other comments
Not sure if this is a feature or a bug

**Comment by nekosaur** [comment]
I think you mean prop and not directive. Directives are something different.

And I would not call this a bug, it's simply how the grid components have been designed. Currently any prop found on them will be turned into a class.

What is your use-case where this is not desired?

**Comment by johnleider** [comment]
This is the desired and intended functionality for grid components. What is your specific use-case?

**Comment by lyzs90** [comment]
ah right, props. @nekosaur @johnleider thanks for clarifying. no particular use case at the moment, just wondering if this behavior will change in the future and if i should directly use `class` instead

**Comment by KaelWD** [comment]
This is intentional behavior, and there are no plans to change it. You can still use `class=""` if it helps you sleep better.
