### ISSUE TITLE
[Feature Request] Elevation level transition on hover

### ISSUE THREAD

**Issue by AlexAlabyev** [vuetifyjs/vuetify#2924]
### New Functionality
If you could specify elevation level on hover It would make elements look more dynamic.

### Improvements
Right now attribute `hover` doesn't do anything if the element already has `elevation` . 

So this would be useful if, for example, you want to have `elevation-20` -> hover -> `elevation-6`  transition

### Bugs or Edge Cases it Helps Avoid
None

**Comment by johnleider** [comment]
Thank you for the suggestion. This is not something we are going to pursue at this time.
