### ISSUE TITLE
[Bug Report] Tabs at the top of Cards cover the 2px border radius at the top corners of the card.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#2926]
### Versions and Environment
**Vuetify:** 1.0.0-beta.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Mac OS 10.13.2

### Steps to reproduce
See CodePen link

### Expected Behavior
It's expected that the rounded top corners of the card remain.

### Actual Behavior
The tabs seem to be either overriding the default border of the card or the rounded corners at the top of the card is being covered by the tabs.

### Reproduction Link
[https://codepen.io/MatthewAry/pen/pprexa](https://codepen.io/MatthewAry/pen/pprexa)

**Comment by KaelWD** [comment]
This fixes it, and doesn't break anything else as far as I can tell: https://codepen.io/anon/pen/zpdwVr

**Comment by MatthewAry** [comment]
Okay, I had considered adding overflow-hidden to the card. But does this mean that this a bug in Card? Should card have overflow-hidden set by default?

**Comment by KaelWD** [comment]
Probably, idk if there's any reason not too. That's something to test for whoever decides to fix this.
