### ISSUE TITLE
[Feature Request] Possibility to override JS breakpoints

### ISSUE THREAD

**Issue by DmitryLobachov** [vuetifyjs/vuetify#2928]
### New Functionality
I'd like to override default breakpoints inside JS. As mentioned in docs https://next.vuetifyjs.com/style/theme#stylus-guide we can change style breakpoints but there is still hardcoded breakpoints in app-breakpoint.js.

### Improvements
There is no work-arounds, except forking vuetify

### Bugs or Edge Cases it Helps Avoid
As I mentioned before, we can override breakpoints for css but not js and this will definitely lead to discrepancy and potential bugs when css applies some styles but JS don't.
Also it will definitely help newcomers to switch existing applications to Vue + Vuetify. 
The problem is that we want to switch our existing project (that is based on Bootstrap) to Vuetify but without huge changes to UI design. As far as I see default vuetify breakpoints will definitely break stuff.

**Comment by johnleider** [comment]
Thank you for the suggestion. This is not something we are going to pursue at this time.

**Comment by vouza** [comment]
I cannot believe this. You cannot customize the breakpoints of vuetify?

**Comment by jacekkarczmarczyk** [comment]
@vouza follow these PRs: https://github.com/vuetifyjs/vuetify/pull/4705 and https://github.com/vuetifyjs/vuetify/pull/4675
