### ISSUE TITLE
Is there anyway to change the z-index on a v-edit-dialog?

### ISSUE THREAD

**Issue by apblack96** [vuetifyjs/vuetify#2929]
I am trying to put a v-edit-dialog from data tables within another v-edit-dialog and because the z-index is set to 6 by default they are not showing up correctly. Any suggestions

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
