### ISSUE TITLE
[Feature Request] Add router-link-active class to navigation links for partial matching

### ISSUE THREAD

**Issue by devistar** [vuetifyjs/vuetify#2932]
### New Functionality
Today it only adds "router-link-exact-active" class then it must match exactly url. 

### Improvements
Could you add "router-link-active" class via an option to match partially url like with &lt;router-link&gt;?
For example if I have a link "/user" and "/user/profile", I would like the link "/user" to be highlighted if I am on "/user/profile".

### Bugs or Edge Cases it Helps Avoid
Nothing to add.

**Comment by KaelWD** [comment]
That is already the default behaviour as far as I'm aware. I'll reopen this if you can provide something that  shows otherwise.
