### ISSUE TITLE
[Feature Request] Change tab size in your docs

### ISSUE THREAD

**Issue by AlexAlabyev** [vuetifyjs/vuetify#2934]
### New Functionality
Vue files in VS code by default have `tabSize: 4 spaces` as well as the example code in the official Vue docs. 

So when you copy the example code from Vuetify docs all the tab sizes gets mixed up in your files, since all the code has the indent of 8 spaces

### Improvements
It will make everything look unified

### Bugs or Edge Cases it Helps Avoid
None

**Comment by nekosaur** [comment]
This is in the end a matter of taste, but 2 spaces _is_ more common in the js world (see for example https://hackernoon.com/what-javascript-code-style-is-the-most-popular-5a3f5bec1f6f). 2 spaces also means that code examples will look better on smaller screens.

**Comment by KaelWD** [comment]
Not to mention:
 - This is not the correct repo for documentation issues or questions
 - All the examples follow vuetify's internal style guide
 - It's incredibly trivial to just reformat the examples yourself when you copy them.

**Comment by AlexAlabyev** [comment]
@nekosaur  @KaelWD sorry, you're right, I actually agree with you both after hearing your point of view. 

P.S. Thanks for maintaining the library, it's awesome.
