### ISSUE TITLE
[Bug Report] Fixed property ignored

### ISSUE THREAD

**Issue by nueko** [vuetifyjs/vuetify#2938]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
add `:fixed="false"` to `v-toolbar`, `v-footer`, `v-navigation-drawer`

### Expected Behavior
`x---fixed` class not added

### Actual Behavior
`x---fixed` class added

### Reproduction Link
[https://codesandbox.io/s/61n5xv7wzw](https://codesandbox.io/s/61n5xv7wzw)

**Comment by nekosaur** [comment]
`--fixed` gets applied when you use the `app` prop.

https://github.com/vuetifyjs/vuetify/blob/e070ac605118b7bce38431894d5fbd99f8e830b8/src/components/VFooter/VFooter.js#L85

So it is by design and not a bug. However I can't speak to the decision behind it (paging @vuetifyjs/collaborators)

**Comment by KaelWD** [comment]
It doesn't make any sense to have a non-positioned app-level drawer. You can either apply the `absolute` prop to make it absolute instead, or remove the `app` prop to make it static.
