### ISSUE TITLE
[Bug Report] TAB key clears the v-select data

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#2939]
### Versions and Environment
**Vuetify:** 1.0.0-beta.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
- Focus the v-select field;
- Select any option from the list by pressing up/down arrows and then press enter;
- Press TAB key;

### Expected Behavior
The selected value in the v-select field should stay 

### Actual Behavior
The value in the v-select dropped

### Reproduction Link
[https://codepen.io/kasheftin/pen/LezqGK?editors=1010](https://codepen.io/kasheftin/pen/LezqGK?editors=1010)

**Comment by johnleider** [comment]
This has been resolved in the new betas, yay!
