### ISSUE TITLE
[Bug Report] Activator in v-dialog not stopping event propagation

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#2942]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Mac OS 10.13.2

### Steps to reproduce
Please see the CodePen. It's a synthetic example, but it shows the problem with propagation.

### Expected Behavior
-- From the API Docs --

activator

When used, will activate the component when clicked (or hover for specific components). This manually stops the event propagation. Without this slot, if you open the component through its model, you will need to manually stop the event propagation

### Actual Behavior
The click event from the activator propagates up the DOM tree.

### Reproduction Link
[https://codepen.io/MatthewAry/pen/NXaQbP](https://codepen.io/MatthewAry/pen/NXaQbP)

### Other comments
Here is a GIT Blame. It seems that the code necessary for this behavior was removed.
https://github.com/vuetifyjs/vuetify/blame/0bee4c6316cc63d7212f1bc9972835fbdfab1c8a/src/components/VDialog/VDialog.js#L99

**Comment by nekosaur** [comment]
So this looks like it might be a casualty of my big component refactor for a-la-carte. @johnleider can you answer if the `stopPropagation` should be put back in?

**Comment by johnleider** [comment]
Yes, it is intended for all activator slots to eat the events. Can you take this one @nekosaur for sprint 6?
