### ISSUE TITLE
[Feature Request] Support dot notation in item-key

### ISSUE THREAD

**Issue by felipe-muner** [vuetifyjs/vuetify#2943]
### New Functionality
refer a property in object like as:
 *item-value="value.matricula"*
*return-object*
from component<v-select>

### Improvements
more easy to manipulate array, 

### Bugs or Edge Cases it Helps Avoid
https://codepen.io/felipemuner/pen/zpPOpb

**Comment by johnleider** [comment]
This is already supported in data-iterator/data-table and treeview. It has no need for select et al.
