### ISSUE TITLE
[Bug Report] Side menu scrolling is not smooth on iPhone X, maybe others

### ISSUE THREAD

**Issue by adam-zpos** [vuetifyjs/vuetify#2947]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Mobile Safari 11.0, Google Chrome
**OS:** iOS 11.2.1

### Steps to reproduce
Used mobile device to scroll through the side drawer menu on https://next.vuetifyjs.com/getting-started/quick-start

### Expected Behavior
Smooth scrolling 

### Actual Behavior
Glitchy shaky scrolling 

### Reproduction Link
[https://jsfiddle/not applicable ](https://jsfiddle/not applicable )

### Other comments
Tested with the mobile chrome app too on the same device.

**Comment by adam-zpos** [comment]
Here is a gif example (20mb) https://petya.convertio.me/p/xXjJl_k_Vi_AOrlkpSimMA/a91a5d2d2e542348c2029744ba098b84/22D85919-1087-404D-8290-C896FF90E8CC.gif

**Comment by KaelWD** [comment]
Possibly related to #2773

**Comment by ecmel** [comment]
Yes this is the case with iphone 8 with safari

**Comment by nekosaur** [comment]
Not seeing the problem on an iphone SE with ios 10.2

**Comment by ajsutton** [comment]
#2773 reportedly doesn't apply when the mobile styling is applied, though I'm unable to verify that (web inspector won't connect to my iPhone for some reason...).

I can reproduce the issue with scrolling inside the navigation-drawer on an iPhone 6S just like in the video linked above.  Main content panel scrolls perfectly though.

**Comment by adam-zpos** [comment]
This doesn’t appear to the case any more in 1.0.0-beta 4. Can anyone else confirm so we can close this?

**Comment by ajsutton** [comment]
I can no longer reproduce this. Seems like it can be closed.

**Comment by KaelWD** [comment]
Must have been #2773 then

**Comment by ishitatsuyuki** [comment]
Performance is poor on Firefox on Android (I'm on nightly). Maybe a reopen is desirable.

(Firefox performance is still inferior to Chrome, but in general not that slow)

**Comment by KaelWD** [comment]
@ishitatsuyuki I don't know if that's related, does it look like the video that @adam-zpos posted? Please create a new issue with valid reproduction and information about your device.
