### ISSUE TITLE
[Feature Request] Add progressive image loading to v-card or even as a separate component

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#2951]
### New Functionality
Allowing to specify 2 images (low/high res) and adding fade transition on load would make image loading look good.

### Improvements
No other material visual frameworks have progressive image loading yet. So it would be nice for Vuetify to have it.

### Bugs or Edge Cases it Helps Avoid
None

**Comment by adallow** [comment]
This would be really useful for us as well!

++ please!

**Comment by darren-dev** [comment]
Just stumbled upon a situation where this would be amazing. Here is a Vue plugin that allows for progressive image loading, would be great to integrate this into the card media system.

https://github.com/MatteoGabriele/vue-progressive-image

**Comment by KaelWD** [comment]
![2018-07-11_17-22-44](https://user-images.githubusercontent.com/16421948/42556510-2df3106c-852f-11e8-80c7-c716b28a73f2.gif)

**Comment by AlexSHoffman** [comment]
@KaelWD it looks great!
