### ISSUE TITLE
[Bug Report] Object.values is not a function in older browsers

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#2954]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Google Chrome, Mozilla Firefox, Internet Explorer, Microsoft Edge, Safari
**OS:** Mac OS 10.13.2

### Steps to reproduce
1.) Load up a vuetify in an older version of Chrome 53 or less

### Expected Behavior
I expect that the web application will load.

### Actual Behavior
It crashes with the error: `Uncaught TypeError: Object.values is not a function`

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/pull/2842](https://github.com/vuetifyjs/vuetify/pull/2842)

### Other comments
I think it might be too early to make the change to using `Object.values` and force people to use `babel-polyfill` just for this. I have referenced the pull request I think it causing this as the reproduction link.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

**Comment by jacekkarczmarczyk** [comment]
Vuetify uses features that should be polyfilled in many places, this PR is not the only one. Supported browsers are listed here https://next.vuetifyjs.com/getting-started/quick-start#supported-browsers and that's not going to change in the near future (and if it changes it will be rather something like removing IE11/Safari9 support than adding support for older browsers, but that's definitely not for now)

**Comment by mcfarljw** [comment]
Would it be useful to include a general indication of minimum versions for the supported browsers? It sounds like even though those browsers are supported it's still highly recommended to polyfill then, not just for IE11 and Safari 9.

**Comment by KaelWD** [comment]
Chrome and firefox are evergreen, so it's expected that 99.9% of users are on the latest couple of versions. Everything else is updated fairly regularly, so the same thing applies there too. IE is a special case because of the number of stubborn people that still use it, and I have no idea why safari 9 is even on the list at all.

**Comment by mcfarljw** [comment]
Fair enough, I've been living on the China side of the world too long.
