### ISSUE TITLE
[Bug Report] Combobox: item value instead text displayed

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2959]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
Open codepen

### Expected Behavior
Item text should be displayed when set initial value via v-model

### Actual Behavior
Item value is displayed

### Reproduction Link
[https://codepen.io/anon/pen/JMMrOw](https://codepen.io/anon/pen/JMMrOw)

**Comment by Darkside73** [comment]
Upd: So I see combobox does not play well with ```{ text: '', value: '' }``` kind items
I've accomplish desired behavior on plain array https://codepen.io/anon/pen/LeeObp

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify/issues/2645#issuecomment-347634598
