### ISSUE TITLE
[Feature Request] Allow to expand a list group in mini drawer mode

### ISSUE THREAD

**Issue by devistar** [vuetifyjs/vuetify#2962]
### New Functionality
If a navigation drawer has expandable list groups. When you pass into mini drawer mode, you cannot expand list groups and see sub item icons.

### Improvements
It would be possible to use expandable navigation drawer in mini drawer mode. 
N.B. Sub items icons should have no left padding to be visible.

### Bugs or Edge Cases it Helps Avoid
...

**Comment by johnleider** [comment]
This is not something we currently plan to pursue. Thank you for your request.
