### ISSUE TITLE
[Bug Report] First button in grid list is automatically added with the "btn--active" class

### ISSUE THREAD

**Issue by ch-luke** [vuetifyjs/vuetify#2963]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Safari 11.0.2, Google Chrome
**OS:** Mac OS 10.13.2

### Steps to reproduce
1. Create a grid of tiles (i.e. button components) for a multi level navigation system
2. Clicking on a tile navigates to another list of sub-level titles

e.g. <v-btn :to="navigationItem.link" color="amber">

### Expected Behavior
A new grid of tiles/buttons displayed which are not active or highlighted.

### Actual Behavior
The first grid item/button on the newly loaded page has the active class added and the button you clicked on the parent page (i.e. same DOM position as the newly loaded page) is also "css :active".

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

### Other comments
Using href instead, as it should, works as it reloads everything (<v-btn :href="navigationItem.link" color="amber">) but using the router-link "to" attribute keeps the v-data IDs and think this is the course of the mixup. 

<img width="669" alt="screen shot 2018-01-08 at 11 15 23 pm" src="https://user-images.githubusercontent.com/20023331/34698431-fd4be0a0-f4cf-11e7-9e48-dca9c7170d83.png">

<img width="660" alt="screen shot 2018-01-08 at 11 15 32 pm" src="https://user-images.githubusercontent.com/20023331/34698436-04f0d36a-f4d0-11e7-8322-48702e26716e.png">

**Comment by jacekkarczmarczyk** [comment]
You didn't save the codepen, please provide a valid reproduction link

**Comment by ch-luke** [comment]
The screenshots gave a clear overview of the issue. Here is a pen in addition. https://codepen.io/chluke/pen/KZoGYa?editors=1010

**Comment by KaelWD** [comment]
https://router.vuejs.org/en/api/router-link.html

> `<router-link to="/">` will be active for every route! To force the link into "exact match mode", use the `exact` prop

**Comment by ch-luke** [comment]
@KaelWD, cheers! 

Fyi in my actual app I don't use "/" but the "exact" mode does the trick anyway.

There is the 2nd point about <btn> click focus. Think it might need to be a feature request. A new attribute like resetFocus would do it e.g. <btn to="/page" resetFocus>. So the btn on the loaded page isn't focused (i know the pen doesn't illustrate this, but it does happen).

**Comment by KaelWD** [comment]
It's probably Vue reusing the existing Dom elements. Give them all unique keys to prevent that.
