### ISSUE TITLE
[Feature Request] Tag for flex or button component to make width / height match

### ISSUE THREAD

**Issue by ch-luke** [vuetifyjs/vuetify#2964]
### New Functionality
Easily create square cards / buttons

https://codepen.io/chluke/pen/wppZRV

### Improvements
"v-flex height-match-width" or "v-btn square"

This would be sweet.

### Bugs or Edge Cases it Helps Avoid
Can't see any.

**Comment by ch-luke** [comment]
Yeah defo!

**Comment by peluprvi** [comment]
Related to https://github.com/vuetifyjs/vuetify/issues/1536 and https://github.com/vuetifyjs/vuetify/issues/2389

**Comment by KaelWD** [comment]
Duplicate of #1536
