### ISSUE TITLE
[Bug Report] Active icon v-btn has applied color when disabled

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#2967]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Open the codepen

### Expected Behavior
Icon button should be grey

### Actual Behavior
Icon button is blue

### Reproduction Link
[https://codepen.io/anon/pen/yppmNm](https://codepen.io/anon/pen/yppmNm)

**Comment by johnleider** [comment]
An icon button is assumed to have no background (it is treated like a flat button). If you want to use a background but also have disabled functionality, use the **fab** prop instead.

https://codepen.io/johnjleider/pen/OzQddM
