### ISSUE TITLE
[Bug Report] Snackbar-bottom/top doesn't work properly on sm size &  Snackbar-right/left don't work properly on xs size

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#2970]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- Put 150 or more characters of text in a snackbar (just open the reproduction link or the Vuetify docs page)

- Resize window to xs size and trigger the snackbar, you will see that a snackbar with an attribute <br>`right or left` is moved down beyond the window and you can't see half of it.

- Resize window to sm size and trigger the snackbar, you will see that a snackbar with an attribute <br>`bottom or top` is too small to contain all the text because it's just sm6 in width

### Expected Behavior
to work properly

### Actual Behavior
Described in "steps to reproduce"

### Reproduction Link
[https://codepen.io/anon/pen/jYZVvm](https://codepen.io/anon/pen/jYZVvm)

**Comment by KaelWD** [comment]
The first point is valid, but the second is not. Snackbars are intended for short messages only, and should not contain more than two lines of text. 

https://material.io/guidelines/components/snackbars-toasts.html#

**Comment by AlexSHoffman** [comment]
@KaelWD yeah I agree, I just wanted to make sure you'll see what's going on there on `sm` window size.
Good to see you guys are actually fixing a lot bugs.
