### ISSUE TITLE
[Bug Report] Scrollbar issue with expansion-panel

### ISSUE THREAD

**Issue by cfjedimaster** [vuetifyjs/vuetify#2971]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Create a set of panels, 3 (or more). The third panel has a horizontal scroll bar. This is only visible for me in Windows/Chrome. You can see a screenshot of it here:

http://www.evernote.com/l/AAOodNvYXUhGqbczbDIGQYyPkPo5H3M5U5A/

### Expected Behavior
For it not to have a scroll bar in the panel title.

### Actual Behavior
It has one.

### Reproduction Link
[https://codepen.io/cfjedimaster/pen/EooMea?editors=1010#0](https://codepen.io/cfjedimaster/pen/EooMea?editors=1010#0)

**Comment by nekosaur** [comment]
Windows 7 and Chrome 63.0.3239.132 here. Can't see scrollbar. Will check on W10 when I get home.

**Comment by smares** [comment]
1. That's a vertical scrollbar not a horizontal one.
2. No scrollbar under Windows 10 with Chrome, Also tested with latest Firefox and Edge, both also work fine.

**Comment by cfjedimaster** [comment]
Yes, sorry, vertical, not horizontal. Not sure why it isn't reproducing on your Win10.

**Comment by smares** [comment]
Do you have any scaling enabled for your display?

**Comment by cfjedimaster** [comment]
No zoom in Chrome. At the OS level I'm at 150%.

**Comment by smares** [comment]
Yep, this is it then. With 150% scaling, I see the scrollbar as well. With 100% and 125% it's not there.

**Comment by cfjedimaster** [comment]
Cool. Does it look right in FIrefox though? To be clear, all my tests were on this machine w/ the same scaling.

**Comment by nekosaur** [comment]
Closing this since it's pretty much impossible to account for system and/or browser level zooming.

**Comment by KaelWD** [comment]
Also:
- the codepen is blank
- the screenshot 404s
