### ISSUE TITLE
[Bug Report] v-dialog | methods | event is not defined | in Firefox

### ISSUE THREAD

**Issue by AlexAlabyev** [vuetifyjs/vuetify#2979]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- open reproduction link in Chrome and Firefox

- click the image

- see console error in Firefox

### Expected Behavior
To work in Firefox as well

### Actual Behavior
Throws and error in Firefox

### Reproduction Link
[https://codepen.io/anon/pen/MrVpgL?editors=1010](https://codepen.io/anon/pen/MrVpgL?editors=1010)

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/questions/30159017/why-is-event-available-globally-in-chrome-but-not-ff

Change `zoom (url)` to `zoom (event)`

**Comment by AlexAlabyev** [comment]
@jacekkarczmarczyk  thank you!
