### ISSUE TITLE
[Feature Request] Enhanced "tags" mode for v-select

### ISSUE THREAD

**Issue by JonasDoebertin** [vuetifyjs/vuetify#2980]
### New Functionality
It would be nice if we could build a more powerful "tags select" field as we currently can by not being limited to primitive items (as mentioned in https://next.vuetifyjs.com/components/selects#example-tags ).

Often times, tags (at least in bigger applications) consist of some type of object, like

```js
let tags = [
  {
    id: 1,
    label: "My first tag",
  },
  {
    id: "af395cd2-e3d0-42dc-b8b2-5edf7c45de57",
    label: "Another tag"
  }
```

### Improvements
If we could use `item-text` and `item-value` here, building a tags select that submits the selected ids instead of the selected texts a lot easier. We wouldn't have to scan the value/array submitted by the select for *tag labels* to translate it to *tag ids* when using the selected value elsewhere (ie. submit to API).

### Bugs or Edge Cases it Helps Avoid
See *Improvements*.

**Comment by KaelWD** [comment]
Looks like it's already possible if you use `return-object`, I'm not sure if there's any problems you might run into though. 

https://codepen.io/anon/pen/MQWyOq?editors=1010

**Comment by nekosaur** [comment]
Closing as wontfix since there's an existing solution.
