### ISSUE TITLE
[Bug Report] Navigation Drawer half hidden

### ISSUE THREAD

**Issue by IgorDePaula** [vuetifyjs/vuetify#2983]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Firefox 57.0
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
https://vuetifyjs.com/components/navigation-drawers

#6 and #7 items the drawer is not hide completly. Is correct?

### Expected Behavior
Expected is drawer whole hide

### Actual Behavior
Actual is half hidden

### Reproduction Link
[https://vuetifyjs.com/components/navigation-drawers](https://vuetifyjs.com/components/navigation-drawers)

**Comment by IgorDePaula** [comment]
![selecao_147](https://user-images.githubusercontent.com/2833993/34793786-b6a84ade-f633-11e7-86dd-37ec33f505b4.png)
![selecao_148](https://user-images.githubusercontent.com/2833993/34793787-b6d0ca7c-f633-11e7-9ee3-f379926004db.png)

**Comment by KaelWD** [comment]
It's a feature.

**Comment by IgorDePaula** [comment]
Feature?

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/34913447-c5b7a184-f951-11e7-9d20-2ff471e062fe.png)

Jokes aside, this is an issue with the documentation, not the framework itself. I also don't think it's even a problem, as it shows that there is something hidden on the left.
