### ISSUE TITLE
[Feature Request] Add option in v-data-iterator to put pagination at the top of the component, or bottom (as it is), or both

### ISSUE THREAD

**Issue by pauldaiko** [vuetifyjs/vuetify#2985]
### New Functionality
At the moment when using v-data-iterator, the pagination fragment is always placed at the bottom. We are currently displaying quite large cards, and a lot of them, using the iterator. In order to go to next page a user has to scroll all the way to the bottom to be able to switch to next page. This does not seem to be great user experience.

### Improvements
It would be great to be able to choose (by a property) if the pagination should be displayed at the top, at the bottom, or in both areas, so that users can navigate easily regardless of which part of the iterated elements they are viewing.

### Bugs or Edge Cases it Helps Avoid
N/A

**Comment by nekosaur** [comment]
In 2.0 you can use `header` slot and `v-data-footer` or `v-pagination` component to put things above items.
