### ISSUE TITLE
[Bug Report] v-tooltip wrong positioning with multiline content

### ISSUE THREAD

**Issue by SergeyKhval** [vuetifyjs/vuetify#2989]
### Versions and Environment
**Vuetify:** 1.0.0-beta.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Linux x86_64

### Steps to reproduce
Hover over button

### Expected Behavior
Tooltip appears above button

### Actual Behavior
Tooltip appears over button

### Reproduction Link
[https://codepen.io/transGLUKator/pen/ppVjrd?editors=1010](https://codepen.io/transGLUKator/pen/ppVjrd?editors=1010)

**Comment by SergeyKhval** [comment]
Can send a PR for this one

**Comment by johnleider** [comment]
A few things. The codepen is using 0.16.4, not 1.0.0-beta.3. Also, you have the **top** prop specified, which would normally try to put it above the button, but due to window collision, is being moved 16px from the top.

**Comment by SergeyKhval** [comment]
@johnleider yeah, sorry, I provided link with wrong vuetify version. in 0.16.4 it actually worked correctly.
Please take a look at [this pen](https://codepen.io/transGLUKator/pen/qpygdd?editors=1010), vuetify 1.0.0-beta.4
