### ISSUE TITLE
v-data-table is altering array order

### ISSUE THREAD

**Issue by martinweingart** [vuetifyjs/vuetify#2990]
## Versions and Environment

Vuetify: 0.17.6
Vue: 2.5.9
Browsers: Firefox 57.0.4 (32-bit)
OS: Linux Mint 18.1

## Expected Behavior

The items in the table should have the same order of the array

## Actual Behavior

The items in the table have the order altered. If I want to delete some item in the array using the props.index, the result is not correct.

## Reproduction Link

https://codepen.io/anon/pen/RxyRwm?editors=1010

**Comment by nekosaur** [comment]
`props.index` is not the index of the item in the original array. It is the index of the item in the filtered and sorted array. You'd want to use some unique value in your items when referencing them for actions such as delete or edit.

**Comment by martinweingart** [comment]
Ok but why is altering the order of the array? I didn't applied sort conditions

**Comment by nekosaur** [comment]
`v-data-table` sorts by default. if you want to disable sorting on all columns you will need to set `sortable: false` on each column in `headers`.

**Comment by martinweingart** [comment]
Ok thanks!
