### ISSUE TITLE
[Bug Report] beta v3 breaks dynamic theme colours

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#2995]
### Versions and Environment
**Vuetify:** 1.0.0-beta.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
If you change the CDN linked file to vuetify from v3 to v2 you will see how it used to work vs how it works now.

### Expected Behavior
In Beta 2 and earlier (since this functionality was introduced) it was possible to update the theme colours dynamically.

### Actual Behavior
However, it doesn't always seem to work as intended anymore.

### Reproduction Link
[https://codepen.io/shongololo/pen/GydvXy](https://codepen.io/shongololo/pen/GydvXy)

**Comment by nekosaur** [comment]
Because of the new changes to theming, which include the dynamically calculated lighten/darken variants, css color names are not currently supported.

Paging Dr @KaelWD. Ideally there's an easy way of converting the css color name to RGB?

**Comment by shongololo** [comment]
The challenge is that when a certain theme colour is used, e.g. for a button or text, let's say `info` colour, then when the `info` theme colour is dynamically updated the change is not reflected in items referring to the `info` colour. I suppose one way to deal with this is to assign hex colours to a variable and then use those variables instead of the theme colours.

**Comment by KaelWD** [comment]
There isn't an easy way fo us to convert named colors to hex, you have to either import the colors list or only use hex colors. There's supposed to be a console warning about this, but it isn't working for some reason. 
You pen works if you use the correct color format: https://codepen.io/anon/pen/mpLjbg

**Comment by shongololo** [comment]
Thanks for clarifying, I'm converting to hex colours for now.

**Comment by shongololo** [comment]
@KaelWD 
> There isn't an easy way fo us to convert named colors to hex

In case this is useful, and not sure what your policy is on keeping code lean vs. using third party libraries, but [d3-color](https://github.com/d3/d3-color/blob/master/src/color.js) might be handy for colour definitions

**Comment by KaelWD** [comment]
Not a chance, that thing's huge. I'm going to fix the error to make it clear what's going on, but you will have to use hex colors only.

**Comment by nekosaur** [comment]
Or import our colors util to use the material design colors
