### ISSUE TITLE
[Bug Report] v-btn-toggle mis-styled with certain v-btn props

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#2996]
### Versions and Environment
**Vuetify:** 1.0.0-beta.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Create a ```v-btn-toggle``` with children ```v-btn``` elements that have properties ```class``` or ```color``` (those are the two I've tested). The ```v-btn``` elements no longer receive the active class, and their opacity is therefore always low.

### Expected Behavior
You should be able to modify these props while still having the ```v-btn``` element receive the active class

### Actual Behavior
The ```v-btn``` elements do not receive the active class when using these props

### Reproduction Link
[https://codepen.io/anon/pen/NXMwLj](https://codepen.io/anon/pen/NXMwLj)

### Other comments
Notice how on page load the buttons are styled correctly, but lose the proper styling upon change.

This worked properly in prior versions.

**Comment by do-web** [comment]
"depressed" also not working with v-btn-toggle

**Current Version.**

**Comment by johnleider** [comment]
Please do not comment on closed issues. If you have a bug, please create a new issue, https://issues.vuetifyjs.com or seek help in our community, https://community.vuetifyjs.com
