### ISSUE TITLE
[Bug Report] Filter X

### ISSUE THREAD

**Issue by FelixBecquart1990** [vuetifyjs/vuetify#2998]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Write then click somewhere else

### Expected Behavior
text should stay when click somewhere

### Actual Behavior
the text disappear

### Reproduction Link
[https://codepen.io/anon/pen/LemKra](https://codepen.io/anon/pen/LemKra)

**Comment by FelixBecquart1990** [comment]
`    <v-text-field
      placeholder="Votre prénom"
      class="mi-input"
      style="margin-bottom:16px"
      v-model="firstName"
      :rules="nameRules"
      @input="firstNameToCapitalize"
      autofocus
      required
    ></v-text-field>`

`methods: {
    firstNameToCapitalize() {
      this.firstName = this.firstName.charAt(0).toUpperCase() + this.firstName.slice(1);
    }
}`

meanwhile, here is what I've done

**Comment by sorinsarca** [comment]
The #3006 PR should fix this
