### ISSUE TITLE
Select prop single-line does not work.

### ISSUE THREAD

**Issue by safaorhan** [vuetifyjs/vuetify#300]
### Steps to reproduce
- Put `single-line` prop to `v-select` component.
- It does not removes the floating label.

### Versions
Latest versions in unpkg.

### What is expected ?
The floating label should not be displayed.

### Reproduction Link
http://codepen.io/anon/pen/ryPvRa

**Comment by johnleider** [comment]
This has already been resolved on the dev branch. https://github.com/vuetifyjs/vuetify/blob/dev/src/components/selects/Select.js#L54
