### ISSUE TITLE
[Bug Report] The grid system does not work on safari 8

### ISSUE THREAD

**Issue by terily** [vuetifyjs/vuetify#3005]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Safari 8
**OS:** iOS 8

### Steps to reproduce
Open the URL: https://next.vuetifyjs.com/components/grid  and you'll find that all the examples can't run well on Safari 8 

### Expected Behavior
work fine

### Actual Behavior
flexbox is not working on Safari8

### Reproduction Link
[https://codepen.io/terily/pen/MrXXmW](https://codepen.io/terily/pen/MrXXmW)

### Other comments
It require -webkit- prefixes on older Safari versions.

**Comment by KaelWD** [comment]
Safari 8 is not supported. You'll have to implement the required fixes yourself. 

<https://next.vuetifyjs.com/getting-started/quick-start>
