### ISSUE TITLE
[Feature Request] Need a callback function for month/year navigation in v-date-picker

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3008]
@johnleider 

### New Functionality
Able to get only selected date, not able to watch/method for just navigating next/previous month or year.

### Improvements
Calendar needs give all interaction callback

### Bugs or Edge Cases it Helps Avoid
Calendar must cb function for month/year navigation

**Comment by ksankumar** [comment]
@jacekkarczmarczyk  How can we go back to calendar view, when i click year icon in calendar?

**Comment by johnleider** [comment]
@ksankumar Let's keep the issue post conversation focused on the request. Please direct that question to the [community](https://community.vuetifyjs.com)
