### ISSUE TITLE
[Bug Report] v-text-field's blur method doesn't blur the input

### ISSUE THREAD

**Issue by nkovacs** [vuetifyjs/vuetify#3009]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Linux x86_64

### Steps to reproduce
1. Click the text field
2. Type something
3. Press enter

### Expected Behavior
The field should be blurred

### Actual Behavior
The field loses its focused style, but its input element remains focused

### Reproduction Link
[https://codepen.io/anon/pen/WdKvxa](https://codepen.io/anon/pen/WdKvxa)

### Other comments
The focus method appears to work correctly.

**Comment by nkovacs** [comment]
Apparently the focus and blur methods are event listeners, and weren't meant to be called from outside like this.

A hackish workaround is possible: https://codepen.io/anon/pen/dJjovW

I would prefer to use the focus and blur methods methods because then it's the same as native input elements with ref.

**Comment by johnleider** [comment]
This is functionality that will be improved upon for the 1.1 forms release. Currently those methods are not considered public. Thank you for the report.

**Comment by Kleemer** [comment]
Any updates on that ?

**Comment by KaelWD** [comment]
Still works for me: https://codepen.io/anon/pen/ajPYWx?editors=1010

Please don't comment on old closed issues, open a new one **with a repro link** if you're still experiencing it.

**Comment by nkovacs** [comment]
@KaelWD I don't understand how your repro reproduces the bug. Of course the input is blurred if you click to activate the checkbox.

Here's a proper repro that shows the bug (type something into the field and hit enter): https://codepen.io/anon/pen/djwmZo

The issue was closed without a fix, with a promise that this will be improved in 1.1. It was not. It would be more appropriate to reopen this bug report, I don't really understand why it had to be closed in the first place anyway.

**Comment by KaelWD** [comment]
You're right, sorry I didn't check the original repro again. I don't know why the was closed originally.
