### ISSUE TITLE
[Bug Report] Using v-tabs components raises an error when generating static files with the nuxt template

### ISSUE THREAD

**Issue by farrajota** [vuetifyjs/vuetify#3010]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Firefox 57.0
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
Follow these steps to reproduce the error on your local machine:

- Fetch the nuxt template using vuetify

```bash
vue init vuetifyjs/nuxt
```

- cd to the project dir and install all dependencies

```bash
cd <proj> && npm install
```

- Install vuetify 1.0.0-beta.4

```bash
npm install vuetify@1.0.0-beta.4 --save
```

- Add the following code to layouts/default.vue

```
<template>
  <v-app dark>
    <!-- Add these 3 lines right after the first two tags in default.vue -->
    <v-tabs fixed-tabs centered>
      <v-tab router to="/">stuff</v-tab>
    </v-tabs>
    ...
```

- Attempt to generate static files

```bash
npm run generate
```

### Expected Behavior
Generating static files should not raise an error.

### Actual Behavior
Raises an error when building the static files.

### Reproduction Link
[https://github.com/farrajota/vuetify-nuxt-issue-report/tree/d51ad1572646721efb42c32d89270aeabd344e5a](https://github.com/farrajota/vuetify-nuxt-issue-report/tree/d51ad1572646721efb42c32d89270aeabd344e5a)

### Other comments
The issue revolves around using [v-tabs](https://next.vuetifyjs.com/components/tabs) to route to different views with the [nuxt](https://github.com/nuxt/nuxt.js/) framework.

When attempting to generate static files using the latest version of vuetify (`vuetify@1.0.0-beta.4`) it terminates the process with an error. Using the stable version (`vuetify@0.17.3`) works correctly.

Upgrading packages like `nuxt`, `vue` or any other package does not fix the issue (the error message clearly points that the problem come from the vuetify package itself).

> Note: `npm run dev` and `npm run build && npm run start` work correctly. It only raises an error when running `npm run generate`.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/350f01e6f63a2fbe921afce47f7fcfca914d45e4/src/components/VTabs/VTab.js#L54-L59
https://github.com/vuetifyjs/vuetify/blob/350f01e6f63a2fbe921afce47f7fcfca914d45e4/src/components/VTabs/VTab.js#L82-L89

It should be using something like `router.resolve()` to figure out if it should be active, this is just sloppy.

**Comment by farrajota** [comment]
### Version update (1.0.0-beta.5)

I've updated to `vuetify@1.0.0-beta.5` + `nuxt@1.1.1` and it continues to fail when building the static files: https://github.com/farrajota/vuetify-nuxt-issue-report/tree/ac731912be6c2ef20123685d0e31f0b104ade7dc
