### ISSUE TITLE
[Feature Request] Too much html loading a once when using v-menu and tooltip on multiple components

### ISSUE THREAD

**Issue by Malthebp** [vuetifyjs/vuetify#3015]
### New Functionality
This feature, could be a bug, but there were too many things to write, like a jsfiddle link etc. 
Changing the way you render v-menu and tooltip, only rendering it when you need it, will make the pagespeed way faster. Right now I am loading a lot of cards where you can select things from a v-menu, where each card needs its own v-menu. This makes the load speed slow. 

### Improvements
Not sure about the question, but. 
Changing the v-model from changing a display attribute, to a if-statement on the rendering might do the trick. 

### Bugs or Edge Cases it Helps Avoid
Pagespeed, pagespeed, pagespeed.

**Comment by nekosaur** [comment]
Which is exactly what the `lazy` prop on `v-menu` does.
