### ISSUE TITLE
[Bug Report] Tooltip too high above the element

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#3016]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
Create a button with tooltip .
Make a large height button (>= 60px)

### Expected Behavior
The tip is 5 pixels above the button.
![default](https://user-images.githubusercontent.com/1662812/34938382-d52a36c8-f9f0-11e7-887c-c058c2ee7334.png)

### Actual Behavior
The higher the button height the further the tip from the button:
![default](https://user-images.githubusercontent.com/1662812/34938312-952ed920-f9f0-11e7-9dc3-6c9724067d9a.png)
And if you reduce the height of the button, then the card is at a low:
![default](https://user-images.githubusercontent.com/1662812/34938418-f223beb6-f9f0-11e7-9ba8-ac4c81c96134.png)

### Reproduction Link
[https://codepen.io/cawa-93/pen/jYppRV?editors=1100](https://codepen.io/cawa-93/pen/jYppRV?editors=1100)

**Comment by cawa-93** [comment]
![default](https://user-images.githubusercontent.com/1662812/34938304-8a839876-f9f0-11e7-96a3-7f4ebb9b547f.png)

**Comment by SergeyKhval** [comment]
this is related to #2989, can send a PR for this

**Comment by nekosaur** [comment]
Fixed as of 1.1.1 https://codepen.io/anon/pen/NzQrxg?editors=1100

**Comment by KaelWD** [comment]
#3775 was merged without the correct commit message.
