### ISSUE TITLE
v-on:click.native on <v-list-tile>

### ISSUE THREAD

**Issue by Kylart** [vuetifyjs/vuetify#302]
I've been looking for this a lot but I can't manage to get it working my way.

So I have a dropdown menu with items. Like this: 
```html
<v-menu transition="v-slide-x-transition">
        <v-btn flat dark slot="activator">
           More
        </v-btn>
	<v-list>
		<v-list-item>
		    <v-list-tile>
			<v-list-tile-title>
				Check synopsis
			</v-list-tile-title>
                    </v-list-tile>
	        </v-list-item>
		<v-list-item>
			<v-list-tile>
			       <v-list-tile-title>Download all episodes</v-list-tile-title>
			</v-list-tile>
		</v-list-item>
	</v-list>
</v-menu>
```

Is it possible to click of list-tile to call a method ? 

I would like to do something like this : 
```html
<v-list-tile-title v-on:click.native="openModal(item.name, item.text)">
	Check synopsis
</v-list-tile-title>
```

Is it even possible ? Did I miss anything ? 

Thanks !

**Comment by johnleider** [comment]
If you are going to manually open a model not using the ```activator slot```, you must use click.stop. This will stop propagation of the click, which is being captured by the ```v-click-outside``` directive and closing it.
