### ISSUE TITLE
[Bug Report] IE11 + Compatibility View breaks icons due to lack of font ligature support

### ISSUE THREAD

**Issue by krestaino** [vuetifyjs/vuetify#3020]
### Versions and Environment
**Vuetify:** 1.0.0-beta.3
**Vue:** 2.5.2
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
1) Go here in IE11: https://krestaino.github.io/vuetify-font-ligatures/dist/
2) Add 'github.io' to Compatibility View ([screenshot](https://i.imgur.com/CmcYYJ4.png))
3) Refresh page

### Expected Behavior
Both icons should be visible.

### Actual Behavior
Only smiley (mood icon) is visible.

### Reproduction Link
[https://github.com/krestaino/vuetify-font-ligatures](https://github.com/krestaino/vuetify-font-ligatures)

### Other comments
Adding `font-feature-settings: 'liga';` to all icons will fix this. You can see Google's warning about lack of ligature support [here](https://google.github.io/material-design-icons/#using-the-icons-in-html). It seems IE11 Compatibility View, even when forced off with `<meta http-equiv="x-ua-compatible" content="ie=edge">`, breaks font ligatures.

To give some background on this. I use Vuetify for some internal forms where I work. Our IT has forced Compatibility View on everyone's computer while visiting our internal network, where the forms are hosted. Even though I'm using `<meta http-equiv="x-ua-compatible" content="ie=edge">` to turn off Compatibility View for the forms I built, I was having issues getting icons to load.

This is easily fixable on my end, `.icons { font-feature-settings: 'liga'; }`, but it seems worth it to add this to Vuetify out of the box.

**Comment by johnleider** [comment]
I actually see the ligatures just fine. With that being said, definitely a small change for a net gain. PR the change and we'll add it.
