### ISSUE TITLE
[Bug Report] Can't close v-navigation-drawer with hide-overlay option and using a click directive

### ISSUE THREAD

**Issue by l1qu1d** [vuetifyjs/vuetify#3021]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Create a navigation-drawer and a button with a click directive to open/close the navigation-drawer.

Add the hide-overlay option to the v-navigation-drawer

Clicking the button to open the drawer works , but trying to close it via the button doesn't work.

### Expected Behavior
To close the v-navigation-drawer when its open with a button or icon, etc. with a click directive.

### Actual Behavior
When clicking the button to close the v-navigation-drawer it doesn't close.

### Reproduction Link
[https://codepen.io/anon/pen/EoejZx?&editors=101](https://codepen.io/anon/pen/EoejZx?&editors=101)

### Other comments
I used the codepen code from https://next.vuetifyjs.com/components/navigation-drawers temporary v-navigation-drawer. The only thing I added was "hide-overlay" on line 13 in the html side.

I suspect this is due to the changes made to fix the memory leak.

**Comment by johnleider** [comment]
Moving this into beta.5 sprint as an emergent task.

**Comment by KaelWD** [comment]
This can be worked around by checking if the drawer was closed in the last event loop: https://codepen.io/anon/pen/xpyJjq?editors=1011

Switching the click-outside listener back to bubble would cause other issues elsewhere.
