### ISSUE TITLE
[Feature Request] Inline V-date-picker not supporting click/dbl click event

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3023]
@jacekkarczmarczyk 

### New Functionality
Mobile native calendar have double click date for allowing see the event/ create an event. Need that like functionality in v-date-picker

### Improvements
inline v-date-picker not allowing to add anyevent like click/dblclick in date

### Bugs or Edge Cases it Helps Avoid
v-date-picker needs to support like native calendar

**Comment by ksankumar** [comment]
@johnleider Is there any fix for this requirement?

**Comment by tvkit** [comment]
This may not work for the mobile app, but for the desktop, \@input responds to a selection:

` @input="$refs.menu.save(date)"`

https://codepen.io/tvkit/pen/BrJLLr?&editors=101

**Comment by ksankumar** [comment]
@tvkit Requested this feature in Inline calendar, not in model/menu date picker.
