### ISSUE TITLE
[Feature Request] Not able to go back or cancel, when we click year in v-date-picker

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3024]
@jacekkarczmarczyk 
### New Functionality
Need to add back/cancel button in year view when clicked year in calendar

### Improvements
 v-date-picker wont break any functionality 

### Bugs or Edge Cases it Helps Avoid
v-date-picker need  same functionality like native calendar

**Comment by jacekkarczmarczyk** [comment]
You can go back to the calendar view by clicking the date in the picker header
![gif](https://user-images.githubusercontent.com/15625235/35024058-235d3662-fb70-11e7-819a-f9695dee55e7.gif)
Close this issue if this is the solution for you

**Comment by ksankumar** [comment]
Is it possible to add any back button or arrow in calendar title panel. I am not sure End user aware of go back with help of click date title.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
