### ISSUE TITLE
[Feature Request] New button variant: plain (no background hover)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#3026]
### New Functionality
For some UI I prefer buttons with no background change on hover but rather a change in opacity for the icon/text itself.  I am suggesting a new prop `plain` to `v-btn` which will basically apply the following styles (as well as having the effect of passing the `flat` prop):

```
.btn--plain {
  height: auto;
  width: auto;
  margin: 0;
  padding: 8px;
  min-width: 0;
  > .btn__content {
    padding: 0;
    opacity: 0.75;
    &:before {
      background-color: transparent !important;
      transition: none !important;
    }
  }
  &:hover {
    > .btn__content {
      opacity: 1;
    }
  }
}
```
Here is an example of how it works/looks:
https://codepen.io/anon/pen/BJOYjd

I have been using this myself for a while and thought maybe others want something similar, so decided to suggest it as an addition to the `v-btn` component. What do you think? Is this something you will consider?

### Improvements
If this is functionality many users request it makes sense to include it in the framework.

### Bugs or Edge Cases it Helps Avoid
Users don't have to implement it themselves.

**Comment by ekoeditaa** [comment]
Hi, I would like to try and implement this. Since this is my first issue, can anyone help me on where to start? Thanks in advance :)

**Comment by davidbielik** [comment]
This has worked for me in the meantime.
```
<template>
  <v-btn flat class="plain" to="/">click me</v-btn>
</template>
<style scoped>
    .plain:before {
        content: unset !important;
    }
</style>
```

**Comment by SiamKreative** [comment]
I like this idea :)

**Comment by yuens1002** [comment]
```
v-btn:hover:before {
      background-color: transparent;
    }
```

should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance

**Comment by ryantunis** [comment]
> ```
> .v-btn:hover:before {
>       background-color: transparent;
>     }
> ```
> 
> should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance

This only gets rid of the hover for mouseover. As soon as you move your mouse off the button it does the hover effect from 1 opacity to 0.

**Comment by auresk** [comment]
> > ```
> > .v-btn:hover:before {
> >       background-color: transparent;
> >     }
> > ```
> > 
> > 
> > should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance
> 
> This only gets rid of the hover for mouseover. As soon as you move your mouse off the button it does the hover effect from 1 opacity to 0.

.v-btn:before {
  display: none;
}

Should do the trick. Cheers!

**Comment by auresk** [comment]
> > ```
> > .v-btn:hover:before {
> >       background-color: transparent;
> >     }
> > ```
> > 
> > 
> > should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance
> 
> This only gets rid of the hover for mouseover. As soon as you move your mouse off the button it does the hover effect from 1 opacity to 0.

> > ```
> > .v-btn:hover:before {
> >       background-color: transparent;
> >     }
> > ```
> > 
> > 
> > should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance
> 
> This only gets rid of the hover for mouseover. As soon as you move your mouse off the button it does the hover effect from 1 opacity to 0.

Add this to your CSS:

```
.v-btn:before {
  display: none;
}
```

This should take care of it. Cheers!

**Comment by auresk** [comment]
> > ```
> > .v-btn:hover:before {
> >       background-color: transparent;
> >     }
> > ```
> > 
> > 
> > should do the trick or add a class `your-class:hover:before` and apply it on the v-btn instance
> 
> This only gets rid of the hover for mouseover. As soon as you move your mouse off the button it does the hover effect from 1 opacity to 0.

Add this to your CSS:

```
.v-btn:before {
  display: none;
}
```

This should take care of it. Toggling the transitions as seen below also gives more specific desired result. Cheers!

![Screen Shot 2019-11-08 at 11 22 18 AM](https://user-images.githubusercontent.com/26942242/68497514-5499eb00-021a-11ea-8003-268ab5522c3a.png)

**Comment by SlackOng95** [comment]
This enhancement should apply whenever clicking on the v-btn as well.

Workaround to avoid opacity get changed to 0 when click on v-btn
`.v-ripple__animation{
    display: none;
  }
`
