### ISSUE TITLE
[Feature Request] Please update the Font Awesome icons to version 5

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3027]
### New Functionality
Font Awesome released version 5: https://fontawesome.com/

Most of the icons are free and have regular (outline) and solid variations.
https://fontawesome.com/icons?m=free

### Improvements
More icons to choose from

### Bugs or Edge Cases it Helps Avoid
None

**Comment by jacekkarczmarczyk** [comment]
Vuetify is already supporting it in version 1.0 beta
https://github.com/vuetifyjs/vuetify/pull/2665

**Comment by AlexSHoffman** [comment]
@jacekkarczmarczyk ah nice, so it settled then. Do you think v1.0 will come in the next few weeks?
