### ISSUE TITLE
Drawer close and open event

### ISSUE THREAD

**Issue by epileftro85** [vuetifyjs/vuetify#3028]
Hi guys, i am trying vuetify for a project at work, all is going on wheels, except for the drawer, i can't figure it out how to know when the drawer is closed, because if i store the drawer v-model in the vuex store, i have to change that value when it's closed. i've read about @transitionend but it doesn't work in this escenario, thanks in advance.

**Comment by jacekkarczmarczyk** [comment]
Please direct questions to our chat. You can join us at https://chat.vuetifyjs.com

**Comment by mmm8955405** [comment]
I met this problem, too. You should actively solve problems rather than just shut them down.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
