### ISSUE TITLE
'hidden-xs-and-down' doesn't work

### ISSUE THREAD

**Issue by mydogisbox** [vuetifyjs/vuetify#303]
### Steps to reproduce

Full html to reproduce:
```
<div id="app">
  <v-btn class='hidden-xs-and-down'>Hidden XS</v-btn>
  <v-btn class='hidden-sm-and-down'>Hidden SM</v-btn>
</div>
```

### Versions
Vuetify: 0.9.4
Tested on Edge 38.14393.0.0

### What is expected ?
The first button would disappear at extra small widths and the second button would disappear at small widths.

### What is actually happening ?
The first button is always visible and the second button disappears at small widths and below.

### Reproduction Link
http://codepen.io/anon/pen/ryRavE

**Comment by johnleider** [comment]
The documentation should be improved to reflect this. ```hidden-xs-and-down``` isn't a class.  It is ```hidden-xs-only```.

**Comment by mydogisbox** [comment]
Would it make sense to change it to 'hidden-xs-and-down'?  It would keep the documentation simple, make the class more discoverable and probably simplify the implementation as well.

**Comment by johnleider** [comment]
I don't think so. xs-and-down would imply there is another breakpoint that it overlaps, which is not the case. I think with improved documentation this would be more clear.

**Comment by csensoli** [comment]
hidden-xs-and-down does not work BUT hidden-xs doesn't work neither :-(
Only hidden-sm-and-down works...

**Comment by nekosaur** [comment]
Please do not comment on closed issues. If you had read through the comments you would have realized that it is `hidden-xs-only`, _NOT_ `hidden-xs`.
