### ISSUE TITLE
[Feature Request] activate v-menu/v-tooltip manually with function passed to scoped slot

### ISSUE THREAD

**Issue by nkovacs** [vuetifyjs/vuetify#3030]
### New Functionality
Both v-menu and v-tooltip assign events by default to the activator, even when that might not be desired.

In this example: https://codepen.io/anon/pen/KZxeOL, the X button uses the standard menu activator slot, but because of that, the clickable area is larger than the actual button. V-tooltip has a similar problem.
The checkmark button shows the desired behavior and the workarounds I had to use. I still want to put the button into the activator slot so that the menu aligns correctly with the activator, but I want to manually trigger the activation.
V-tooltip is worse, because a workaround like this forces me to reimplement the delay functionality.

### Improvements
This could be made much simpler if v-menu did not automatically add events (and cursor:pointer and other stuff like that) to the activator slot. Instead it could pass a function in slot-scope that the button can then call to activate the menu.
For v-tooltip, it could pass two functions: enter and leave. This would allow the delay functionality to still be handled by v-tooltip.

E.g. it would simplify my code to this:

```
<v-menu bottom left>
    <v-btn icon flat slot="manual-activator" slot-scope="props" @click="props.activate()">
       <v-icon>done</v-icon>
    </v-btn>
    <v-list>
        <v-list-tile>
            <v-list-tile-title>Entry 1</v-list-tile-title>
        </v-list-tile>
    </v-list>
</v-menu>
```

### Bugs or Edge Cases it Helps Avoid
Click and hover areas in v-menu/v-tooltip that don't match up with the element that's supposed to trigger the activation.

**Comment by KaelWD** [comment]
I'll keep this suggestion in mind for #3206, no promises though.
