### ISSUE TITLE
[Bug Report] v-form with single v-text-input submits on enter

### ISSUE THREAD

**Issue by danielx** [vuetifyjs/vuetify#3032]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Linux x86_64

### Steps to reproduce
1. place **one** v-text-field inside a v-form
2. press enter while the input is focused

### Expected Behavior
It should not submit on enter

### Actual Behavior
Submits on enter

### Reproduction Link
[https://codepen.io/anon/pen/ZvqvKy](https://codepen.io/anon/pen/ZvqvKy)

### Other comments
Placing more than one v-text-field prevents submission on enter

**Comment by jacekkarczmarczyk** [comment]
That's how html works
https://codepen.io/anon/pen/opapMV?editors=1000

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/2159#issuecomment-340242836
