### ISSUE TITLE
[Bug Report] VExpansion panel not registering VExpansionPanelContent when using a-la-carte

### ISSUE THREAD

**Issue by ssipos90** [vuetifyjs/vuetify#3035]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Firefox 59.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. clone
2. npm install
3. npm run dev

### Expected Behavior
I've used the provided a-la-carte boilerplate with vue-cli and upgraded to vuetify 1.0.0-beta.4 (this also is reproducible on 0.17).
The child component should be included with the parent.

### Actual Behavior
Console error and render issue: Unknown custom element: v-expansion-panel-content

### Reproduction Link
[https://github.com/ssipos90/vuetify-a-la-carte-bug-report](https://github.com/ssipos90/vuetify-a-la-carte-bug-report)

### Other comments
This was covered here: https://github.com/vuetifyjs/vuetify/issues/2472 but I think it misses a few lines.

**Comment by ssipos90** [comment]
I don't think this is important, but it also happens on the SSR boilerplate.

**Comment by KaelWD** [comment]
It's a separate component: `import { VExpansionPanel, VExpansionPanelContent } from 'vuetify'`

It would make sense to have them both be included at the same time though.

**Comment by ssipos90** [comment]
It's not exported from the main vuetify package. You have to import it:
`import VExpansionPanelContent from 'vuetify/src/components/VExpansionPanel/VExpansionPanelContent.js';`

The behaviour should be like with the VCard component, i.e.: `import { VCard } from 'vuetify';' also imports `VCardTitle`, `VCardAction`, etc...

**Comment by KaelWD** [comment]
Ah, I see what you mean. easy fix.

**Comment by ssipos90** [comment]
Maybe this plays a part? It's missing from VExpansionPanel/index.js
```js
import { createSimpleFunctional } from '../../util/helpers'
/* ... */
const VCardActions = createSimpleFunctional('card__actions')
const VCardText = createSimpleFunctional('card__text')
```

**Comment by ssipos90** [comment]
If you register the component as a global, it works great. What's the catch? Registering in a component a-la-carte style requires something extra? I took a long look in the docs and didn't see anything.
```js
Vue.use(Vuetify, {
    components: {
        // ...
        VExpansionPanel
    }
});
```

**Comment by ssipos90** [comment]
Just a thought, but exporting/importing multiple components at once could "fix" this.

```html
<template>
    ...
</template>
<script>
import * as VExpansionPanel from 'vuetify/components/VExpansionPanel';

export default {
    components: {
        ...VExpansionPanel
    }
};
</script>
```

**Comment by nekosaur** [comment]
There's a difference between doing

```
import { VExpansionPanel } from 'vuetify'

export default {
  components: { VExpansionPanel }
}
```

and 

```
import { VExpansionPanel } from 'vuetify'

Vue.use(Vuetify, {
  components: VExpansionPanel
}
```

(which is the official way of using a-la-carte components). When supplying it to `Vue.use`, internally we do `Vue.use(VExpansionPanel)` which will run the install method and register all child/related components.

If you import components in a single SFC file, then you will need to make sure you're loading all related components as well, like you wrote

```
import * as VExpansionPanel from 'vuetify/es5/components/VExpansionPanel
```

**Comment by ssipos90** [comment]
Then maybe just add this info in the docs?

**Comment by nekosaur** [comment]
Totally valid.

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetifyjs.com/issues/217
