### ISSUE TITLE
[Feature Request] Support JSX/TSX import-based componet

### ISSUE THREAD

**Issue by david50407** [vuetifyjs/vuetify#3036]
### New Functionality
Directly import a vuetify component and use with JSX/TSX, like this below:

```
import { VIcon } from 'vuetify';

export default {
  render (h) {
    return (
      <VIcon color="primary">group</VIcon>
    );
  },
};
```

### Improvements
Vurtify now has basic TypeScript Declaration support, but not on components.

With import-based component, TS can have type checking on TSX component props.

PS. Vuetify can use [vue-tsx-support](https://github.com/wonderful-panda/vue-tsx-support#using-custom-component) to wrap components for TSX component type definition, or Vuetify can declare components type definition by itself.

### Bugs or Edge Cases it Helps Avoid
This will support TSX props type checking.

**Comment by andtii** [comment]
This would be awesome!

**Comment by KaelWD** [comment]
Do you have an example of what the `d.ts` should look like for a vue component?

**Comment by david50407** [comment]
I will write some simple example with [vue-tsx-support](https://github.com/wonderful-panda/vue-tsx-support) this weekend.

**Comment by KaelWD** [comment]
Almost three weekends later, any update?

**Comment by chanlito** [comment]
@KaelWD I think he meant something like this https://github.com/chanlito/vuetify-tsx

**Comment by andtii** [comment]
Wow cool @chanlito i have to try it out!
