### ISSUE TITLE
[Feature-Request] Flexible Slots for prepend-and append-icon in v-list-group

### ISSUE THREAD

**Issue by LuckySphinX** [vuetifyjs/vuetify#3039]
**New Functionality**
With the newest version (1.0.0-beta4) you can set a prepend-and append-icon in the `v-list-group`.

Instead of only be able to set icons for the prepend- and append-area, there should be slots for both to improve the use-cases of the `v-list-group` prepend- and append-area.

**New Use-Cases**
-Setting text above and under prepend-icon.
-Setting text above and under append-icon.
-Setting other elements, such as chips,..... in prepend- and append-area

**Comment by johnleider** [comment]
This is possible as of latest version.
