### ISSUE TITLE
[Feature Request] Ability to block v-tabs swipe to next tab (mobile)

### ISSUE THREAD

**Issue by NickMcBurney** [vuetifyjs/vuetify#3047]
### New Functionality
I have a carousel within a tabs component and swiping the carousel is triggering the tab to change to the next tab

### Improvements
Haven't found a workaround as yet

### Bugs or Edge Cases it Helps Avoid
User accidentally changing tabs when they're trying to change active slide in a carousel

### Demo
[demo link (codepen)](https://codepen.io/NickMcBurney/pen/XVoVwe?editors=1010)

**Comment by jacekkarczmarczyk** [comment]
That's what `touchless` prop was added for to `tabs-items` component in 1.0
https://next.vuetifyjs.com/components/tabs

**Comment by NickMcBurney** [comment]
Thanks was looking at: https://vuetifyjs.com/components/tabs :)
