### ISSUE TITLE
[Bug Report] v-date-picker closes prematurely when browsing year

### ISSUE THREAD

**Issue by daftskunk** [vuetifyjs/vuetify#3048]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
1. Open the date-picker.
2. Browse years.
3. Re-open the date-picker
....

### Expected Behavior
1. Open the date-picker.
2. Browse years.
3. Select a year you want to browse.
4. Select a date.
5. The date-picker menu closes.

### Actual Behavior
1. Open the date-picker.
2. Browse years.
3. The menu closes
4. Re-open the menu
5. Select year.
6. Reopen the menu
7. Scroll back 100 year
8. Select year
9. Reopen the menu
10. Select date

### Reproduction Link
[https://codepen.io/maxkoi/pen/MrZVKP?editors=1010](https://codepen.io/maxkoi/pen/MrZVKP?editors=1010)

### Other comments
This bug was successfully reproduced in 1.0.0-beta.4 (https://codepen.io/maxkoi/pen/aEPGWW)

**Comment by LuckySphinX** [comment]
insert a `:close-on-content-click="false"` to the menu component above

**Comment by daftskunk** [comment]
The wanted behaviour here is that the menu only closes when the user actually selects a month. Inserting `:close-on-content-click="false"` contradicts this behaviour by required an OK and CANCEL button.
