### ISSUE TITLE
[Bug Report] Possible error on expandable and searchable data tables

### ISSUE THREAD

**Issue by dng93** [vuetifyjs/vuetify#3050]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 7

### Steps to reproduce
1.- Create a data table that is expandable, and searchable as well, with some items. 
2.- Expand one of the last items from the table.
3.- Search for that item on the text field (it should show you that item on the table expanded).
4.- Clear the search term from the textfield (now it shows all items with the expanded item still expanded).
5.- Close the expanded item.

### Expected Behavior
Item closes correctly with no errors.

### Actual Behavior
Item does close the expanded panel but throws and error on the console: "TypeError: Cannot read property 'classList' of undefined at afterLeave"

### Reproduction Link
[https://codepen.io/dn1993/pen/baOQVo](https://codepen.io/dn1993/pen/baOQVo)

### Other comments
The error can be triggered on the pen I attached here with the third and fourth items from the table. I tried to override the genExpandedRow function on the VDataTable mixins (body.js) to add a try catch block but I still get the error. This framework is truly awesome, keep up the great work!

**Comment by kaijajan** [comment]
I encountered exactly the same issue while combining search and expand features.
Error occurs right after manipulate expand feature after searching keyword
