### ISSUE TITLE
[Feature Request] Add support for grouping/aggregates to data table component

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3051]
### New Functionality
Use groups and aggregates.  It's a pretty big missing piece from the data tables.  For instance, see the aggregate and grouping example on this older Vuetiful component: https://codepen.io/andrewcourtice/full/woQzpa

### Improvements
I currently haven't been able to achieve this behavior at all.

### Bugs or Edge Cases it Helps Avoid
N/a

**Comment by nekosaur** [comment]
Closing this in favor of https://github.com/vuetifyjs/vuetify/issues/3180 which has gathered a couple of thumbs up
