### ISSUE TITLE
[Bug Report] Fa icons don't work with v-if

### ISSUE THREAD

**Issue by Nredor** [vuetifyjs/vuetify#3058]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Click the "toggle saving state" button and observe icons.

### Expected Behavior
I would expect the icon to change when saving boolean changes. With material icons it works like expected.

### Actual Behavior
Font awesome icon doesn't change when saving boolean changes. 

### Reproduction Link
[https://codepen.io/psoden/pen/Eorpwz](https://codepen.io/psoden/pen/Eorpwz)

**Comment by nekosaur** [comment]
It's the script tag for font-awesome you're using that causing problems it looks like. It works fine when using the following css link

```
<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
```

**Comment by Nredor** [comment]
Yeah, seems to fix the problem but causes another problem: fa-spin doesn't work with that css tag.

**Comment by nekosaur** [comment]
Strange. It doesn't in the codepen but it definitely did on my local env

**Comment by Nredor** [comment]
Very weird. fa-spin doesn't work with css tag even at my local env.

**Comment by Nredor** [comment]
Ok, got everything working by downloading fontawesome css and webfonts and importing in my main.js file. Was a little pain in the ass but seems that this isn't really bug with vuetify but just incompability that is caused by loading fa.css before vue.css (in case of using link at index.html)

**Comment by nekosaur** [comment]
Alright, good that you managed to solve it. I'll close this issue.

**Comment by MetalArend** [comment]
The issue still exists when using the javascript tag for font-awesome. It would be awesome to know what exactly causes the i tag to be reused between toggled elements, and if there might be a way to solve it.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727

**Comment by edwardkarlsson** [comment]
I experienced this issue in an older project that I picked up... updated VueJS, problem still there.
Updated FontAwesome's CDN url to the latest version... problem solved.

**Comment by martinjeannot** [comment]
Not sure what the problem was but I encountered the same bug and I ended up updating FA CDN URL (v5.0.8 => v5.7.2), solved the problem as well :+1:
