### ISSUE TITLE
[Help] How to center v-toolbar-items or menu in v-toolbar

### ISSUE THREAD

**Issue by jaelys** [vuetifyjs/vuetify#3066]
**Versions**
Latest Vue 2.5.x
Latest Vuetify 1.0.0.0 beta4

**What is expected ?**
Use the fill-height it should center to the v-container
**What is actually happening ?**
Try any properties i had found, but still it not located in the center view.
**Reproduction Link**

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
