### ISSUE TITLE
How to use Fontawesome 5  icon in vTextfield?

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify#3070]
I can use Fontawesome , vue-fontawesome as a component,
yes its good , only few icons, but 

I cant pass any of this on pre-prend icon props in VTextField since its only accepting string...

Is there a way i can only add few icons of fontawesome 5 
I dont want so much icons just few and i think that would save a lot bandwidth
and time for user to wait to load the apps

**Comment by codeitlikemiley** [comment]
Hope we can pass in prepend icon an html markup instead if it is not a name ...

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
