### ISSUE TITLE
[Feature Request] data-iterator pagination text property

### ISSUE THREAD

**Issue by danielx** [vuetifyjs/vuetify#3074]
### New Functionality
Expose property to change pagination text set in https://github.com/vuetifyjs/vuetify/blob/dev/src/mixins/data-iterable.js#L418

### Improvements
It seems to be the only text that is not modifiable for the data-iterator component. 

### Bugs or Edge Cases it Helps Avoid
Would help when trying to localize an data-iterator element for another language.

**Comment by jacekkarczmarczyk** [comment]
Use scoped slot 'pageText': https://github.com/vuetifyjs/vuetify/blob/dev/src/mixins/data-iterable.js#L427

**Comment by danielx** [comment]
Thanks!
