### ISSUE TITLE
[Bug Report] Ripple doesn't fade away on v-card unless mouse leaves

### ISSUE THREAD

**Issue by dng93** [vuetifyjs/vuetify#3076]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 7

### Steps to reproduce
1.- Create a v-card and add the v-ripple directive.
2.- Click the card element several times.
3.- Hover the element with the mouse (and leave it) several times to make the ripple fade away.

### Expected Behavior
Ripple effect triggers and fades away automatically.

### Actual Behavior
Ripple effect triggers but it doesn't completely fade away, if you click the card several times you can make it turn almost black.

### Reproduction Link
[https://codepen.io/dn1993/pen/RxdzBr](https://codepen.io/dn1993/pen/RxdzBr)

**Comment by KaelWD** [comment]
this might be fixed by #2678, I'll have to check

**Comment by dng93** [comment]
Oh, sorry. Thank you, that solved it
