### ISSUE TITLE
[Feature Request] V-Select Disable desired options

### ISSUE THREAD

**Issue by holuborhee** [vuetifyjs/vuetify#3079]
### New Functionality
The V-Select control allows for disable, but that is for the element itself, I will like to disable some options in some cases, while others are still enabled, but the control doesn't have a straightforward and official way to do that.

### Improvements
It helps to make the v-select element easier to use, you can easily toggle some options to be enabled or disabled and it makes the code cleaner to read.

### Bugs or Edge Cases it Helps Avoid
It helps to avoid cases of trying to manipulate the v-select option all by yourself, which could lead to errors.

**Comment by KaelWD** [comment]
```js
items: [
  { text: 'foobar', disabled: true }
]
```

**Comment by lattam** [comment]
Sorry for opening, but could be the "item-disabled" props a function ? I don't want to modify my items array, I just need to calculate the disabled status from its properties. Thanks

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/da212e00270998a1603aee55e37d78239639a795#diff-ebb3da5567a5b11ea831789469bcc709R74
