### ISSUE TITLE
[Feature Request] allow providing user icons in checkbox/radio

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#3080]
### New Functionality
It will allow providing user icons in checkbox/radio (will help get rid of material icons in favour of other icon lib)

Currently icons are hardcoded:
```js
    icon () {
      if (this.inputIndeterminate) {
        return 'indeterminate_check_box'
      } else if (this.isActive) {
        return 'check_box'
      } else {
        return 'check_box_outline_blank'
      }
    }
```

```js
    icon () {
      return this.isActive ? 'radio_button_checked' : 'radio_button_unchecked'
    }
```

### Improvements
Just binding few props instead of extending component or other dirty hacking

### Proposed API
```html
<v-checkbox on-icon="fa-square-filled" off-icon="fa-square-empty" indeterminate-icon="fa-something-else">
```

```html
<v-radio on-icon="fa-cicrle-filled" off-icon="fa-circle-empty">
```

**Comment by KaelWD** [comment]
I think this should be done globally instead of with yet another prop.

**Comment by jacekkarczmarczyk** [comment]
That could be the next step - provide a mechanism for setting globally default values of props in other components too (not only icons), but with keeping the possibility of overriding defaults in some special cases. That's why props are imho necessary (also for consistency with other components that have similar prop like carousel, pickers, pagination etc)

**Comment by jacekkarczmarczyk** [comment]
Same goes for `data-iterable` and `expansion-panel-content`.
Additionally (a bit off-topic but still icons thing) - pickers icon props could be renamed to `nextIcon` and `prevIcon` instead of `prependIcon` and `appendIcon` proposed by @johnleider (for constistency with for example `v-pagination`)

**Comment by jacekkarczmarczyk** [comment]
data-iterable, v-pagination and others are done in https://github.com/vuetifyjs/vuetify/pull/3152, checkboxes and radio will be handler in form inputs refactoring
