### ISSUE TITLE
[Bug Report] v-select min-width doesn't work

### ISSUE THREAD

**Issue by Lanayx** [vuetifyjs/vuetify#3081]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
Click on select, it changes it's width depending on the value

### Expected Behavior
min-width attribute should set the minimal width

### Actual Behavior
min-width attribute doesn't seem to work

### Reproduction Link
[https://codepen.io/anon/pen/NXmNrZ?&editors=101](https://codepen.io/anon/pen/NXmNrZ?&editors=101)

**Comment by KaelWD** [comment]
min-width only applies to the menu.

**Comment by Lanayx** [comment]
https://vuetifyjs.com/components/selects#api - should the documentation be updated then?

**Comment by KaelWD** [comment]
Probably. Make an issue on https://github.com/vuetifyjs/vuetifyjs.com

**Comment by Lanayx** [comment]
@KaelWD Should this file be updated as well? https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/mixins/select-props.js#L52

**Comment by KaelWD** [comment]
It gets passed to the select's menu, so v-select still needs that prop. The description just needs updating.
