### ISSUE TITLE
[Bug Report] page title undefined on data and time picker documentation page

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#3086]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.12.6

### Steps to reproduce
visit https://next.vuetifyjs.com/en/components/date-pickers and examine page title in chrome tab

### Expected Behavior
title to display correctly

### Actual Behavior
title displays undefined

### Reproduction Link
[https://github.com/vuetifyjs/docs/blob/master/router/meta.json](https://github.com/vuetifyjs/docs/blob/master/router/meta.json)

**Comment by KaelWD** [comment]
I'm going to fix this anyway, but it should be reported on the correct repo in the future: https://github.com/vuetifyjs/vuetifyjs.com
