### ISSUE TITLE
[Feature Request] Allow background-position customization for v-card-media background image.

### ISSUE THREAD

**Issue by braincomb** [vuetifyjs/vuetify#3087]
### New Functionality
Allow to customize _background-position_ of a `v-card-media` background image, because right now it sets it as _center center_ in inline CSS.

### Improvements
Currently you cannot override background-position in a scoped CSS, so this change will allow for easier customization.

### Bugs or Edge Cases it Helps Avoid
N/A

**Comment by lsbyerley** [comment]
This would be nice, for some reason, not even this is overriding the position, style isn't even being applied..

    .card {
      .card__media {
        .card__media__background {
          background-position: top center !important;
        }
      }
    }

**Comment by KaelWD** [comment]
> you cannot override background-position in a scoped CSS

Yes you can, you just have to use a [deep selector.](https://vue-loader.vuejs.org/en/features/scoped-css.html#deep-selectors)
