### ISSUE TITLE
[Bug Report] v-alert in data-table no-data slot doesn't expand to full width

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#3088]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Look at the example on https://next.vuetifyjs.com/en/components/data-tables#example-no-data

### Expected Behavior
v-alert should span the full width if no custom ```<td>``` is present

### Actual Behavior
v-alert spans only a single column even when no ```<td>``` is present

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/data-tables/noData.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/data-tables/noData.vue)

### Other comments
Assuming this has to do with the updates to the slot to allow ```<tr>``` and ```<td>```s

**Comment by dionysiosarvanitis** [comment]
Expected behavior taken from v0.17 https://codepen.io/pen/?&editors=101
Workaround by manually wrap the content with `<tr><td colspan="100%" class="text-xs-center"> `

**Comment by johnleider** [comment]
This is a breaking change detailed in the release notes https://github.com/vuetifyjs/vuetify/releases

![image](https://user-images.githubusercontent.com/9064066/35364400-ff7a2c00-013c-11e8-964f-66fda5293897.png)

**Comment by Dylan-Chapman** [comment]
I'm confused. The release notes say "with a top level <td>" and I'm talking about the case when that element is not present - just like the example on the website.

**Comment by jacekkarczmarczyk** [comment]
It is a breaking change, but I don't see the reason why we don't allow other (non tr/td) tags/components as the slot content same as we support text content. I'd reopen it but as a feature request instead of bug report. Solution should probably take https://github.com/vuetifyjs/vuetify/pull/3053 into account

**Comment by nekosaur** [comment]
I agree that if no tr/td is present, it should add a td with colspan. It was an oversight on my part
