### ISSUE TITLE
[Bug Report] Line below input field missing on different browser zoom or resolutions

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#3090]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Opera 50.0.2762.58
**OS:** Windows 10

### Steps to reproduce
Zoom in or out

### Expected Behavior
Line below input field should be visible

### Actual Behavior
Some input fields don't show line bolow them

### Reproduction Link
[https://codepen.io/anon/pen/QaRKZV?editors=1010](https://codepen.io/anon/pen/QaRKZV?editors=1010)

**Comment by mirhat** [comment]
I have worked around it by adding margin-top: 1px; to input-group__details

**Comment by KaelWD** [comment]
I don't know if this is something we should or even can support. It only happens to me when zooming out, which is something that even bootstrap don't fully support: http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#browser-zooming

**Comment by pbastowski** [comment]
This is not a new feature. It was working in beta.4 and now, unfortunately, the line disappears in my app also.

**Comment by nekosaur** [comment]
Like @KaelWD said this will probably be hard to support, and is a rendering artifact, not a specific issue with the framework. Closing issue.

**Comment by lannierose** [comment]
This is nonsense! Needs to be fixed. PolymerElements fixed it by using a border instead of another div in Nov 2016: https://github.com/PolymerElements/paper-input/issues/448

**Comment by KaelWD** [comment]
#3601 helped slightly, but got overtaken by the form refactor. I'd be happy to revisit this if someone wants to submit a new PR.
