### ISSUE TITLE
[Bug Report] Breadcrumb last child disabled

### ISSUE THREAD

**Issue by Sykomaniac** [vuetifyjs/vuetify#3091]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Simply create a new breadcrumbs instance. 

### Expected Behavior
The disabling of a child should be controlled through the disabled property

### Actual Behavior
The last child in the breadcrumb list has associated CSS to disable it. I wouldn't expect the last child to be disabled.

### Reproduction Link
[https://codepen.io/anon/pen/dJERbj](https://codepen.io/anon/pen/dJERbj)

### Other comments
Not really sure if this is a bug or a preference. However, I would like the last child to be enabled. Is it a case of overwriting the CSS?

**Comment by DedicatedManagers** [comment]
At first, I didn't like this behavior, but then I realized I could make the last child the current child, which I would want disabled by default.  So please create a simple option to keep this behavior if enhanced out.

**Comment by johnleider** [comment]
I'm going to remove this from a milestone as breadcrumbs needs to be refactored.

**Comment by NikoNagy** [comment]
In 1.2.0, last child is not disabled anymore. 

Is this wanted ?

**Comment by johnleider** [comment]
This has been default for a long time now (disabling items explicitly).
