### ISSUE TITLE
navbar in safari 10.0.2 navbar-item is not vertical center

### ISSUE THREAD

**Issue by yoyo930021** [vuetifyjs/vuetify#31]
<img width="1104" alt="2016-12-25 9 32 35" src="https://cloud.githubusercontent.com/assets/9126398/21471338/d25926e8-cae9-11e6-9e64-0cf9fc9735b0.png">

**Comment by johnleider** [comment]
Fixed with 4953d4df3e669a17f2f591a4f9bf9e9a6c181c51.
