### ISSUE TITLE
Bug: Unusual Padding in v-text-field when typing

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#310]
![image](https://cloud.githubusercontent.com/assets/25447231/24737451/61ea4356-1ac1-11e7-9421-025708944fba.png)
![image](https://cloud.githubusercontent.com/assets/25447231/24737456/6d3506b0-1ac1-11e7-9af7-89809c3148bf.png)

Adding :rows="1" fixes the problem but this would cause a huge code change for every v-text-field

maybe adding a :rows="1" when multi-line is not true in the component
http://codepen.io/anon/pen/NpVGGV

Please Fix

**Comment by dohomi** [comment]
@johnleider all v-text-field receive 120px height on focus. Sorry, no idea how that one slipped through, I'm sure I tested that one before..
