### ISSUE TITLE
[Bug Report] Fullscreen dialogs don't cover scrollbar on bigger resolutions

### ISSUE THREAD

**Issue by zaken** [vuetifyjs/vuetify#3101]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Linux x86_64

### Steps to reproduce
1. Shrink codepen sidebar to < 959px; toggle dialog -> no double scrollbar.
2. Resize to >= 960px; toggle dialog -> double scrollbar.

### Expected Behavior
Consistency between resolutions. Fullscreen dialogs should always overlay the page scrollbar.

### Actual Behavior
@ < 959px the fullscreen dialog correctly hides the underlying scrollbar.
@ >= 960px results in double scrollbar.

### Reproduction Link
[https://codepen.io/anon/pen/BJgZYa](https://codepen.io/anon/pen/BJgZYa)

**Comment by johnleider** [comment]
Closed via ff5d07b
