### ISSUE TITLE
[Feature Request] Add support for individual column filtering in Data Table

### ISSUE THREAD

**Issue by ayush987goyal** [vuetifyjs/vuetify#3102]
### New Functionality
It will allow us to filter data based on individual columns.

### Improvements
It will be driven by a boolean parameter which would allow the filtering for that specific column.

### Bugs or Edge Cases it Helps Avoid
It would not cause any breaking change and will be a straightforward functionality.

**Comment by jacekkarczmarczyk** [comment]
I'd use for this a generic filtering functionality that we already provide

**Comment by ayush987goyal** [comment]
For a big amount of data, generic filtering might have performance issues. By having individual filtering, we can restrict filtering based on some columns only. This might improve the performance.

**Comment by jacekkarczmarczyk** [comment]
I mean that you can provide your own filtering function that checks only selected columns

**Comment by LFP6** [comment]
A jQuery plugin that I wrote last year (pre my understanding of Vue, so I've now essentially scrapped it) might be of interest: https://github.com/LFP6/table-wrangler

In particular, I'd like to suggest something similar to the UI I developed, where when you click the column, it brings up a dropdown with a list of inputs based on the type of content. I happened to implement a text input for freeform strings, multi-select box for static strings, lt/lteq/eq/gteq/gt filtering for numbers, and a radio button for boolean options. I actually wanted to implement the ability for the user to "clone" the filter so that you could do something like num < 10 || num > 20, or similar. I happened to include sorting direction in here as well.

I'll try to put together a fiddle or at least screenshots at some point if that'd help.

**Comment by CherryChann** [comment]
how can i add custom filtering function for filtering the header value for each selected column? I'm having this problem.

**Comment by dcb99** [comment]
@jacekkarczmarczyk  i'd like to add a search bar to the top of each column, are you saying that using custom filtering can handle this?

**Comment by jacekkarczmarczyk** [comment]
Yes, you can pass a json representation of an object containing search values for all columns as a data-table's `search` prop and your custom filtering function should parse value of this prop and compare the value of each column with the corresponding search value

**Comment by dcb99** [comment]
And if I just want to search one individual column? Same thing? Just pass a JSON object to the filter function?

**Comment by jacekkarczmarczyk** [comment]
If you need to be able to filter just one column then there's no need to pass the JSON, just pass the search value (and the filtering function that checks only 1 column)

Please continue discussion on [the Discord chat room](https://community.vuetifyjs.com) if you have any questions

**Comment by husayt** [comment]
@blalan05 I have not seen this being implemented in latest merges. Can you please point to the commit or link mentioning it?

**Comment by nekosaur** [comment]
It is available in the 2.0.0 alpha

**Comment by husayt** [comment]
I went through documentation. could not find any reference. Is there any
example or mention I could refer to?

Thank you

**Comment by Mikilll94** [comment]
Also I don't see anything about per column filtering in the docs.

**Comment by jacekkarczmarczyk** [comment]
`  filter?: (value: any, search: string, item: any): boolean` in `headers` prop

**Comment by Mikilll94** [comment]
There should be an example in docs how to achieve per column filtering because right now it is not clear enough.

**Comment by PhilippHomann** [comment]
see #8264 for an example

**Comment by capynet** [comment]
Working sample: 

```
<template>
    <v-data-table :headers="headers" :items="desserts" item-key="name" class="elevation-1 pa-6">
        <template v-slot:top>

            <!-- v-container, v-col and v-row are just for decoration purposes. -->
            <v-container fluid>
                <v-row>

                    <v-col cols="6">
                        <v-row class="pa-6">
                            <!-- Filter for dessert name-->
                            <v-text-field v-model="dessertFilterValue" type="text" label="Name"></v-text-field>
                        </v-row>
                    </v-col>

                    <v-col cols="6">
                        <v-row class="pa-6">
                            <!-- Filter for calories -->
                            <v-select
                                    :items="caloriesList"
                                    v-model="caloriesFilterValue"
                                    label="Calories"
                            ></v-select>
                        </v-row>
                    </v-col>

                </v-row>
            </v-container>

        </template>
    </v-data-table>
</template>

<script>
  // Table info.
  import tableData from './sampleDataTable';
  export default {
    data() {
      return {
        // We need some values for our select.
        caloriesList: [
          {text: "All", value: null},
          {text: "Only 237", value: 237},
          {text: "Only 305", value: 305},
        ],
        // Filter models.
        dessertFilterValue: '',
        caloriesFilterValue: null,
        // Table data.
        desserts: tableData.data,
      }
    },
    computed: {
      headers() {
        return [
          {
            text: 'Dessert (100g serving)',
            align: 'left',
            sortable: false,
            value: 'name',
            filter: this.nameFilter,
          },
          {
            text: 'Calories',
            value: 'calories',
            filter: this.caloriesFilter,
          },
          {text: 'Fat (g)', value: 'fat'},
          {text: 'Carbs (g)', value: 'carbs'},
          {text: 'Protein (g)', value: 'protein'},
          {text: 'Iron (%)', value: 'iron'},
        ]
      },
    },
    methods: {
      /**
       * Filter for dessert names column.
       * @param value Value to be tested.
       * @returns {boolean}
       */
      nameFilter(value) {
        // If this filter has no value we just skip the entire filter.
        if (!this.dessertFilterValue) {
          return true;
        }
        // Check if the current loop value (The dessert name)
        // partially contains the searched word.
        return value.toLowerCase().includes(this.dessertFilterValue.toLowerCase());
      },
      /**
       * Filter for calories column.
       * @param value Value to be tested.
       * @returns {boolean}
       */
      caloriesFilter(value) {
        // If this filter has no value we just skip the entire filter.
        if (!this.caloriesFilterValue) {
          return true;
        }
        // Check if the current loop value (The calories value)
        // equals to the selected value at the <v-select>.
        return value === this.caloriesFilterValue;
      }
    }
  }
</script>
```

**Comment by palistha01-hash** [comment]
Where is sampleDataTable file and how can I filter in each individual column (text field)?
