### ISSUE TITLE
[Bug Report] Tooltip does not work with fab

### ISSUE THREAD

**Issue by virtuecoder** [vuetifyjs/vuetify#3107]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the repro link

### Expected Behavior
Button should be at the bottom right

### Actual Behavior
Button is somewhere else

### Reproduction Link
[https://codepen.io/anon/pen/zpgqXq?&editors=100](https://codepen.io/anon/pen/zpgqXq?&editors=100)

**Comment by johnleider** [comment]
This will have to be rectified once we removed the need for activator wrappers. Something @KaelWD has been working on in https://github.com/vuetifyjs/vuetify/tree/refactor/detachable-no-root

**Comment by KaelWD** [comment]
![peek 2018-10-22 03-36](https://user-images.githubusercontent.com/16421948/47269936-18b0cb00-d5b0-11e8-8e95-0a60b550ed69.gif)
