### ISSUE TITLE
Floating Small Button Icons not rendering fully

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#311]
http://codepen.io/anon/pen/wJbKob

Kindly check the icon on v-btn(floating small) it's not rendering properly

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
