### ISSUE TITLE
[Bug Report] Input style of background: transparent bleeds to non-vuetify components

### ISSUE THREAD

**Issue by 4storia** [vuetifyjs/vuetify#3111]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
All input elements get `background: transparent`, regardless of whether they're `v-text-field` or not

### Expected Behavior
Components, by nature, shouldn't bleed styles into other areas of the application. Only v-text-field and any other vuetify elements that have `input` get a transparent background

### Actual Behavior
The `input` element is always transparent

### Reproduction Link
[https://codepen.io/Flare/pen/jYgeJJ](https://codepen.io/Flare/pen/jYgeJJ)

### Other comments
I've been really impressed with how much styles have been encapsulated between 0.0.16 and 1.0 - this looks like just a little miss.

**Comment by johnleider** [comment]
This is actually part of the reset that we use. https://github.com/filipelinhares/ress

Unfortunately I do not see us changing this any time soon. Thank you for the report.
