### ISSUE TITLE
[Bug Report] Datatable border

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuetifyjs/vuetify#3113]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Firefox 57.0, Google Chrome, Mozilla Firefox
**OS:** Ubuntu undefined

### Steps to reproduce
sorry no idea

### Expected Behavior
as you see in the codepen the red border not correct around of tr in one side, that's because of the header if header hide (use `hide-headers` prop ) yo will see that the border is show correctly.

### Actual Behavior
border must be fine around of tr

### Reproduction Link
[https://codepen.io/miladmeidanshahi/pen/BJXXbp](https://codepen.io/miladmeidanshahi/pen/BJXXbp)

**Comment by miladmeidanshahi** [comment]
@johnleider

**Comment by nekosaur** [comment]
This might be above my CSS pay grade. It seems like it shows up at some screen widths and not others as well, so not sure if it's not some kind of rounding issue?

**Comment by nekosaur** [comment]
Unable to reproduce in 2.0
