### ISSUE TITLE
[Bug Report] v-list-tile-avatar no longer supports tile prop

### ISSUE THREAD

**Issue by DaleBeckles** [vuetifyjs/vuetify#3117]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.12
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Add a <v-list-tile-avatar tile> element such as the following

                                    <v-list-tile-avatar tile>
                                        <img :src="item.avatar">
                                    </v-list-tile-avatar>

### Expected Behavior
The avatar image should be square as per v0.17

### Actual Behavior
Avatar image is only round

### Reproduction Link
[https://codepen.io/osito/pen/JpPdro](https://codepen.io/osito/pen/JpPdro)

**Comment by ksankumar** [comment]
Not working.

https://codepen.io/ksankumar/pen/GQxQBr

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/36428438-f9dab8c4-16a3-11e8-9a44-55ca9106fc2e.png)

**Comment by ksankumar** [comment]
Just i pulled code from our vuetify site, thought there updated one..
