### ISSUE TITLE
[Bug Report] v-text-field with type set to 'number' accepts the letter 'e'

### ISSUE THREAD

**Issue by DaleBeckles** [vuetifyjs/vuetify#3118]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.12
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10, Mac OSX

### Steps to reproduce
Create a v-text-field and set type to number - the letter e can be input

### Expected Behavior
No letters should be accepted

### Actual Behavior
The letter e can be input

### Reproduction Link
[https://codepen.io/osito/pen/LQPVJZ?&editors=100](https://codepen.io/osito/pen/LQPVJZ?&editors=100)

**Comment by KaelWD** [comment]
> The number input can accept floating point numbers

https://codepen.io/anon/pen/Zrzbyb
https://stackoverflow.com/a/31706796/2074736
