### ISSUE TITLE
[Bug Report] [Help] actions at list component

### ISSUE THREAD

**Issue by arnoldtkl** [vuetifyjs/vuetify#3121]
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.0.0
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
1. Have a title name "Initial value"
2. Clicking on more_vert icon
3. User clicks on edit after the menu open.

### Expected Behavior
What I expected is when clicking on the more_vert icon, it will not change the title value. The menu will pop out and wait user click on edit button to trigger a new event.

### Actual Behavior
It will change the title value. The menu will pop out and the user can click on the edit button to trigger a new event.

### Reproduction Link
[https://codepen.io/anon/pen/vpoMwN?editors=1010](https://codepen.io/anon/pen/vpoMwN?editors=1010)

### Other comments
I need help on this. Because in my use case, suppose user click on the title name, it will redirect the user to the detail page. When user clicking on the more_vert icon, it only triggers the menu pop out and the user can choose other events. Such as edit.

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

`<v-menu @click.native.stop>`

**Comment by arnoldtkl** [comment]
Thank you!
