### ISSUE TITLE
[Bug Report] Clicking v-select combobox option after typing does not select the item

### ISSUE THREAD

**Issue by full-stack-solutions** [vuetifyjs/vuetify#3122]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Start typing a few letters in the text box and then and click an item from the list, only the text you have typed is selected and not the item you have clicked.

### Expected Behavior
You click an item from the autocomplete list and that item is selected.

### Actual Behavior
You click an item from the autocomplete list and only the text you have typed is selected.

### Reproduction Link
[https://codepen.io/mattstudios/pen/XZrzJJ](https://codepen.io/mattstudios/pen/XZrzJJ)

**Comment by Phyks** [comment]
:+1: for this bug, I am affected by it as well. Worth mentionning that if you click again after the first click, the behavior is the expected one (this bug seems to appear only on first click).

**Comment by Dandi91** [comment]
Just came across the same problem. I tried to work around it by using "item" slot with @click on it, but it's a lot of boilerplate.
Can confirm it on Firefox 57.0.4

**Comment by Akkarine** [comment]
Problem does not appear, if element initialized with something already choosen from list as default value.

**Comment by KaelWD** [comment]
This has been fixed in 1.0, not sure what the exact cause was: https://codepen.io/anon/pen/MQwKVK?editors=1010
