### ISSUE TITLE
[Bug Report] v-picker destroyed in dialog view in mobile(iphone5)

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3123]
@jacekkarczmarczyk 

### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
Run this in browser 
change the iPhone5 view 
Open the picker
see the screen

### Expected Behavior
Both picker should fit based on device / screen

### Actual Behavior
Not fited

### Reproduction Link
[https://codepen.io/ksankumar/pen/oEvqGe](https://codepen.io/ksankumar/pen/oEvqGe)

[](url)

**Comment by ksankumar** [comment]
<img width="463" alt="calendar" src="https://user-images.githubusercontent.com/3350098/35483006-c994c638-040a-11e8-8f1b-2acc0f09296b.png">

**Comment by ksankumar** [comment]
:full-width works fine for v-date-picker. But for time-picker not works good..

**Comment by jacekkarczmarczyk** [comment]
Can you be more specific about time picker?

**Comment by ksankumar** [comment]
I
<img width="186" alt="tp" src="https://user-images.githubusercontent.com/3350098/35484738-3beec67c-0422-11e8-8343-2bdf51d621fa.png">

this is the output when i go with full-width for time picker.

full-width not working based on the screen resolution

**Comment by jacekkarczmarczyk** [comment]
Temporary solution: set width manually (`:width="$vuetify.xs ? 250 : 330"`)

**Comment by ksankumar** [comment]
Sure. It will fix in next release ?

**Comment by jacekkarczmarczyk** [comment]
Will try, but I'm not sure how to fix it properly atm
