### ISSUE TITLE
Example of datatable behaves strange.

### ISSUE THREAD

**Issue by SidKwok** [vuetifyjs/vuetify#313]
### Steps to reproduce
 type something in the search text-field
### Versions
v0.10.0
chrome 57
firefox 50
safari 10

### What is actually happening ?
before:
<img width="439" alt="04efda6b-e39b-4332-ab60-dd6c64aef2c0" src="https://cloud.githubusercontent.com/assets/13268747/24747285/7590a49a-1aee-11e7-8daa-04cdcd6ba3d9.png">
after you type something:
<img width="465" alt="1d9d9295-4913-4116-aa09-7eb268bf4ef8" src="https://cloud.githubusercontent.com/assets/13268747/24747294/7ce66c48-1aee-11e7-97f1-7e1095a7b1e8.png">
after you delete the text:
<img width="748" alt="264065ba-4579-4811-8306-d754e1726bcf" src="https://cloud.githubusercontent.com/assets/13268747/24747352/aee433d8-1aee-11e7-9431-a9e12efbf7b7.png">

### Reproduction Link
[example of datatable](https://vuetifyjs.com/components/datatables)

**Comment by cawa-93** [comment]
#310

**Comment by johnleider** [comment]
This was fixed with v0.10.3
