### ISSUE TITLE
[Feature Request] Possibility to hide input details/messages

### ISSUE THREAD

**Issue by sorribes22** [vuetifyjs/vuetify#3131]
### New Functionality
Hi, I'm trying to make 2 switchs controls to interact with a google maps component (isn't the issue).

I only need 2 switchs that change the value of 2 booleans, then it can't cause any error. But the component `v-switch` creates a div at the same time that input to show message, if there is, taking unnecessary space like [this](https://codepen.io/axsor/pen/aqbzVY).

I'm not sure if the possibility of hiding that div exists, in any case I haven't found it.

**If it exists, can you help me? And if not, do you think that it will be usefull?**

Sorry for my english

### Improvements
If the possibility to hide message div does not exists, I'm sure that we can hide it with a simple boolean prop

### Bugs or Edge Cases it Helps Avoid
No one

**Comment by KaelWD** [comment]
The API section of the documentation has a search bar you know: 
![image](https://user-images.githubusercontent.com/16421948/35501359-c34f87f8-052d-11e8-92d3-ebc44da88fe7.png)

**Comment by sorribes22** [comment]
Thanks, I will use it since now...
