### ISSUE TITLE
[Bug Report] v-tabs pagination

### ISSUE THREAD

**Issue by macherel** [vuetifyjs/vuetify#3139]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 7

### Steps to reproduce
* Add enough tabs to bring up the pagination buttons
* Swich to second page
* Close any tabs on this page

### Expected Behavior
Automatically switch to the first page

### Actual Behavior
Pagination button disapear
It is no longer possible to access the first tabs

### Reproduction Link
[https://codepen.io/pen/JpoXaq](https://codepen.io/pen/JpoXaq)

### Other comments
Incidentally, the pagination buttons do not appear if the resolution is less than 1280

**Comment by jacekkarczmarczyk** [comment]
1.0-beta.1 has fixed a number of bugs with `v-tabs`, please check it with that version keeping in mind that the markup for `v-tabs` has changed: https://github.com/vuetifyjs/vuetify/releases/tag/v1.0.0-beta.1. If the bug still exists please update the codepen to the latest version (vuetify@next)

**Comment by macherel** [comment]
Thank you for the link ! I have tried to use 1.0.0-beta.5 without success before.
After updating the codepen to 1.0.0-beta.5, It seems there is same king of problems.
*Pagination button appears only when selecting the last visible tab
*If you are on the second page and remove enough tabs, the pagination buttons disappear while tabs remain on the first page

**Comment by johnleider** [comment]
This was resolved as of https://github.com/vuetifyjs/vuetify/releases/tag/v1.0.12

https://codepen.io/johnjleider/pen/pLGgKY
