### ISSUE TITLE
[Feature Request] [Documentation] Add docs to DevDocs.io

### ISSUE THREAD

**Issue by andMYhacks** [vuetifyjs/vuetify#3140]
### New Functionality
I would like to be able to cache the documentation from vuetifyjs.com with DevDocs.io so that I can use the documentation when traveling.

### Improvements
There is no current workaround at this time.

### Bugs or Edge Cases it Helps Avoid
N/A

**Comment by KaelWD** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #249](https://github.com/vuetifyjs/vuetifyjs.com/issues/249) via [**ZenHub**](https://www.zenhub.com/)
