### ISSUE TITLE
[Feature Request] Add scroll on overflow functionality to breadcrumbs component as well

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3141]
### New Functionality
Have you guys considered adding the "scroll" functionality to breadcrumbs component?

It would be nice to have a similar scroll functionality to the tabs component:
https://vuetifyjs.com/components/tabs#example-8

### Improvements
The component will become significantly more usable (smaller window sizes and longer paths)

### Bugs or Edge Cases it Helps Avoid
none

**Comment by nekosaur** [comment]
I would probably say that breadcrumbs are not the right component to use on mobile if it's deeply nested paths.

**Comment by AlexSHoffman** [comment]
@nekosaur the problem is, no breadcrumbs component is going to be 1920px in width. Most use cases would require a breadcrumb component to be nested in some other element which is by itself is probably < 100vw in width, so **even if the window is opened in full screen** we end up with the component of something like ~400px in width. That's just unusable

**Comment by nekosaur** [comment]
I have a hard time visualizing a layout/scenario where this would be a problem on desktop. Could you create a repro/mockup in codepen or similar?

**Comment by AlexSHoffman** [comment]
@nekosaur here: https://codepen.io/anon/pen/OQgqom

See? resize the window below 1380px and it becomes unusable with just 5 paths of average length. Most common display size is 1366x768, so you:

- have to use your app only in full screen, because breadrumbs component doesn't fit in at 80% of window width
- not allowed to use the app side by side with another app (the same reason - doesn't fit)
- not allowed to put it in other elements and have to make sure it's always 100vw so that it fits in most cases without breaking outer component (see the codepen, resize it and see how it behaves)
- not allowed to have more than 5 paths of average length
- not allowed to use it on displays smaller than 1080p

That's too many assumptions for a component to have, it's just unusable in a lot of use cases.

**Comment by KaelWD** [comment]
- use a smaller font, you've overridden it to 16px
- use shorter labels, one or two words max
- give it an entire row instead of shoving it in with other toolbar items
- truncate to the last couple of items (or even just one) on mobile

Just the first three makes it usable down to 600px:
![image](https://user-images.githubusercontent.com/16421948/36149386-924f5be6-1113-11e8-98be-521e694621d7.png)

**Comment by AlexSHoffman** [comment]
@KaelWD well, I could, but that's just more limitations. You have to adapt the whole app for the breadcrumbs component and what if you don't have any extra rows below the toolbar, you'd just have to reinvent the wheel instead of adding `scrollable` prop.

I just thought it would be nice to have the same scroll functionality for this component as in the tabs component

**Comment by AlexSHoffman** [comment]
@KaelWD well, I could, but that's just more limitations. You have to adapt the whole app for the breadcrumbs component. And what if you don't have any extra rows below the toolbar or cannot cut the directory names in half? You'd just have to reinvent the wheel instead of just adding `scrollable` prop.

I just thought it would be nice to have the same scroll functionality for this component as in the tabs component. If you don't agree, that's fine, it's up to you to decide.

**Comment by KaelWD** [comment]
eh, we'll consider it at least. I know we're already planning to make the tabs scroll functionality into something reusable so we can use it for carousels too (and maybe steppers? idk)

**Comment by nekosaur** [comment]
I'm not shooting you down either, and like kael said we are looking to break out the tab scroll functionality. However I am not sure how intuitive the scrolling would be to use, and how it would look.

In the end it might be something that's better suited for user implementation. But we'll see.

**Comment by johnleider** [comment]
In v2.0 you will have access to a `v-slide-group` component that gives you the side scrolling functionality from tabs.
