### ISSUE TITLE
[Bug Report] v-select with autocomplete not matching when using slot templates

### ISSUE THREAD

**Issue by appurist** [vuetifyjs/vuetify#3142]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- Open the referenced Codepen
- type `AA` in the select input field (or any text contained in the unfiltered list)

### Expected Behavior
It should match `AAA` and `CAA`.  Or it should match `11` (on the `myID` field). Or both or either. It should match on _something_.

### Actual Behavior
There are no matches regardless of what input is typed.

### Reproduction Link
[https://codepen.io/paulw/pen/EQaQBJ](https://codepen.io/paulw/pen/EQaQBJ)

### Other comments
This may be related to the `return-object` option being used, but it works fine if I don't use the `slot` templates (see the https://codepen.io/paulw/pen/gvbvxa Codepen for the working one which is very similar).

**Comment by appurist** [comment]
I just noticed that the 1.0 beta docs show scoped slots separately from slots.  Is this a new feature, and maybe I'm running into trouble here because I'm using the normal unpkg.com/vuetify/dist version on the Codepen? I see there are lots of fixes for `v-select` in the betas.

Also I just spotted the really excellent examples in the beta.5 v-select docs, including new stuff for scoped slots. I'll need to compare those with what I was doing. I've been assuming this was a bug in my code but couldn't find anything wrong or differed from the slot examples I could find. I'll compare against these newly-discovered ones.

**Comment by appurist** [comment]
I've tested with beta 5 and it didn't seem to make a difference in the behavior I was seeing. However, using the examples provided in the beta docs, I've been able to work around my problem and make it work with a custom query function ([Codepen sample](https://codepen.io/paulw/pen/WMbYaa?editors=1011)).

However, and this may be related to the non-custom auto-complete problem above, `item-text` and `item-value` did not seem to affect the parameters in any way, and `itemText` seems to have the wrong value. e.g.: 
for `customFilter (item, queryText, itemText)`, the third parameter `itemText` is always the same as `item`.  This may only be a problem if `return-object` is enabled, not sure.  There's a [Codepen for this](https://codepen.io/paulw/pen/WMbYaa?editors=1011) where you can see this in the Console output at the bottom. The itemText parameter is a full JSON object.

The code in that Codepen is enough for me to proceed with a workaround, the custom filter does seem to be respected in the `v-select` and allows me to code up what I need here.

(While I have this chance, thanks for the hard work on this amazing product. It is the best collection of UI components I've seen in years, and for the most part "just works". I love it. Kudos, folks.)

**Comment by KaelWD** [comment]
It works fine if you get rid of this space
![image](https://user-images.githubusercontent.com/16421948/35614708-19730442-06c4-11e8-8001-51c5d422257d.png)

**Comment by KaelWD** [comment]
And the reason `itemText` is the entire object in your second example is because the `item-text` value you're using doesn't exist on the objects, so it return the full object instead. https://github.com/vuetifyjs/vuetify/blob/77e119a039184a30978221c413b7b579394b8363/src/components/VSelect/mixins/select-helpers.js#L20-L25

**Comment by appurist** [comment]
Thanks very much for the additional info.  It wasn't until last night that I understood the purpose of `item-text` and `item-value`... they never seemed to do anything because I thought they were _formats_ for how to display each item (like simpler versions of the item slot templates). I now understand that it is for the case of identifying the specific item fields when you are using alternate variable names, therefore they must match the name of a single field/member of the item definition.  I did see a good description of that last night which answered that part, perhaps in the updated beta docs.  I like the behavior you're describing above and welcome it; I love it when it all makes total sense in the end.  And glad to see the only changes needed were in my app, part of the experience of learning Vuetify. Thanks for the detailed explanation and help!
