### ISSUE TITLE
[Bug Report] Unable to scroll mini-variant drawer

### ISSUE THREAD

**Issue by Mattchewone** [vuetifyjs/vuetify#3146]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a mini-variant toolbar with menu items that extend past the page and try to scroll

### Expected Behavior
The menu be scrollable

### Actual Behavior
The menu is not scrollable

### Reproduction Link
[https://codepen.io/mattchewone/pen/jZEvZE](https://codepen.io/mattchewone/pen/jZEvZE)

### Other comments
https://github.com/vuetifyjs/vuetify/blob/2ac4927d4b2e11f654e067c5a743a14589a4d011/src/stylus/components/_navigation-drawer.styl#L65-L66

**Comment by jacekkarczmarczyk** [comment]
Temporary workaround https://codepen.io/anon/pen/BYNLLq

**Comment by johnleider** [comment]
This is also present in v1.0.19

**Comment by johnleider** [comment]
This will be looked at during the toolbar update of 1.4

**Comment by johnleider** [comment]
Didn't make the cut for 1.4, will revisit during the 2.0 rebuild.
