### ISSUE TITLE
[Bug Report] Problem with autocomplete property in v-select

### ISSUE THREAD

**Issue by ManuStang** [vuetifyjs/vuetify#3150]
**Versions and Environment**

Vuetify: 0.17.6
Vue: 2.5.8
Browsers: Chrome 63.0.3239.132
OS: Windows 10

**Step to reproduce** 
1) Go on https://vuetifyjs.com/components/selects#example-5
2) Type "Alaska" and press "Enter" --> ok
3) In the same field type again "Alaska" and press "Enter" --> "Alabama" is selected

**Expected Behavior**
When press "Enter" on the field with an item previously selected, this last must be selected again

**Actual Behavior**
When press "Enter" on the field with an item previously selected the first item of the list is selected

**Other comments**
Autocomplete doesn't work if the element is already selected

**Comment by johnleider** [comment]
This has been resolved in v1.1
