### ISSUE TITLE
[Bug Report] save event is broken on v-edit-dialog

### ISSUE THREAD

**Issue by errrken** [vuetifyjs/vuetify#3154]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Mac OS 10.12.6

### Steps to reproduce
Edit the Iron column and click save.

### Expected Behavior
Should print test is console

### Actual Behavior
Nothing happens

### Reproduction Link
[https://codepen.io/anon/pen/YeyzPK?editors=1011](https://codepen.io/anon/pen/YeyzPK?editors=1011)

**Comment by jacekkarczmarczyk** [comment]
`VEditDialog` doesn't emit `save` event, that's actually the issue with documentation - those events shouldn't be there.
