### ISSUE TITLE
[Feature Request] Keep mask/placeholder visible after input

### ISSUE THREAD

**Issue by Craz1k0ek** [vuetifyjs/vuetify#3159]
### New Functionality
The mask will be visible after you have typed a value. This is useful for when you don't know how far you are in the mask (think about credit card numbers/phone numbers).

The placeholder is visible as normal:
![Idea](https://i.imgur.com/wEnqpq1.png)

The placeholder remains visible after typing:
![Idea expanded](https://i.imgur.com/emyeE1d.png)

This is just to give you an idea of the request. To make it clear what you have typed and what is placeholder, you'd want to have the typed text to have a different colour than the placeholder text:
![Colour example](https://i.imgur.com/4LSC9tG.png)

### Improvements
Currently a workaround could be to replace the v-model string, but it requires a lot of work and knowledge. A property for this would be helpful.

### Bugs or Edge Cases it Helps Avoid
None that I can think of.

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
