### ISSUE TITLE
Feature request for DataTable Component

### ISSUE THREAD

**Issue by abusalameh** [vuetifyjs/vuetify#316]
Today I've just seen the amazing **Datatable** Component.

It would be nice to have some extra features for this component 
1- Show/Hide Columns checkbox.
2- Export to different file types using External API ( PDF , CSV ) 
3- Filter results by specific column.
4- RTL Support ( flip the component from ltr to rtl using CSS ) it can be a property with a flag of (true/false) 
5-Print preview 
Many Thanks ^^

**Comment by johnleider** [comment]
-1 You can do this programmatically
-2 Potentially in the future
-3 I'm not sure if we will ever do this
-4 Will do
-5 Potentially in the future

**Comment by abusalameh** [comment]
about number ( 3 ) you can add input boxes for all fields to toggle search by field it's very useful. Think about it :) 

thank you for taking care of other issues 

all the best

**Comment by johnleider** [comment]
Closing this as the only remaining point is already covered in a previous issue, https://github.com/vuetifyjs/vuetify/issues/262
