### ISSUE TITLE
[Bug Report] v-stepper no closing animation

### ISSUE THREAD

**Issue by bliny** [vuetifyjs/vuetify#3161]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.2
**Browsers:** Opera 50.0.2762.67
**OS:** Windows 10

### Steps to reproduce
Start clicking the steps, and you can see that the closing animation is not always shown.. the content just disappears.

### Expected Behavior
Closing animation is always shown

### Actual Behavior
Closing animation is not always shown

### Reproduction Link
[https://codepen.io/anon/pen/YePvqM?&editors=101](https://codepen.io/anon/pen/YePvqM?&editors=101)

**Comment by johnleider** [comment]
All `v-stepper` updates are being moved to v2.0 due to backwards compatibility issues.

**Comment by sh7dm** [comment]
it has animations in `v2.0.0-beta.2`
