### ISSUE TITLE
[Feature Request] Jumbotron dynamic height

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#3164]
### New Functionality
I need to fill the screen with jumbotron. But currently it only supports fixed height, nothing like fill_height

### Improvements
it's an essential missing feature

### Bugs or Edge Cases it Helps Avoid
it makes  it more functional

**Comment by nolde** [comment]
Just place it inside a set of v-container/v-layout/v-flex and set `height="100%"` to it.

**Comment by KaelWD** [comment]
v-jumbotron is being deprecated in 1.2, and there is a `fill-height` class that you can use on any layout elements.
