### ISSUE TITLE
[Bug Report] Datatable injects text-xs-left or text-xs-right when no align prop is set on the TH tag

### ISSUE THREAD

**Issue by masteroleary** [vuetifyjs/vuetify#3167]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
Create a datatable and do not include the align prop in the header data objects

### Expected Behavior
no align class would be added

### Actual Behavior
text-xs-left or text-xs-right is added, overriding my own css

### Reproduction Link
[https://codepen.io/masteroleary/pen/rJxzQa](https://codepen.io/masteroleary/pen/rJxzQa)

### Other comments
I am new to code pen and wasnt sure how to set the same version of vuetify but it does have the same bug.

**Comment by nekosaur** [comment]
You can add `@next` to after vuetify in the unpkg links to switch to latest beta.

This is not a bug. Without the align property columns will default to `text-xs-left` for 1.0 beta and `text-xs-right` for 0.17. You will have to increase the specificity of your css selector if you want to override this with custom css.

**Comment by masteroleary** [comment]
Okay thanks
