### ISSUE TITLE
NuxtJS: [Vue warn]: Do not use built-in or reserved HTML elements as component id: button

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#317]
### Steps to reproduce
Use Vuetify with Nuxt and SSR
### Versions
0.10.3
### What is actually happening ?
On the server side I get this warning:
```
[Vue warn]: Do not use built-in or reserved HTML elements as component id: button
```

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by jvbianchi** [comment]
Here a repo with reproduction: https://github.com/jvbianchi/error-vuetify

**Comment by johnleider** [comment]
Thank you, what are the steps to get that running? I have not used NUXT before.

**Comment by jvbianchi** [comment]
```
npm install
npm run dev
````

**Comment by johnleider** [comment]
Hah, okay ty.

**Comment by jvbianchi** [comment]
To honest I don't know if this is an error caused by vuetify or not?
