### ISSUE TITLE
[Feature Request] Log a warning to the console when hiding the scrollbar when a dialog is opened

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#3173]
### New Functionality
I spent quite a while trying to figure out how to prevent the scrollbar from hiding when a dialog is opened. I eventually stumbled across this issue (https://github.com/vuetifyjs/vuetify/issues/2250#issuecomment-345484608), which made me realize it was only because my dev tools were open wide enough to shrink the viewport below the threshold at which this is supposed to happen.

It would be nice if there was a message in the console that I would likely see right away when this happens. It would only need to be logged once, not every time a dialog is opened.

### Improvements
Would prevent other devs from spending time thinking something that's actually a feature was a bug.

### Bugs or Edge Cases it Helps Avoid
Developer confusion

**Comment by johnleider** [comment]
Thank you for your request. This is not something we are looking to do at this time. My advice is to utilize the [community](https://chat.vuetifyjs.com) when running into issues like this.
