### ISSUE TITLE
[Bug Report] v-tooltip not working with v-badge and v-icon

### ISSUE THREAD

**Issue by jcepek** [vuetifyjs/vuetify#3178]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Firefox 58.0, Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
See provided codepen.   Codepen contains both a v-badge wrapped in tooltip and one which is not.  The first does not display neither the v-badge or v-icon.  The second works just fine without the v-tooltip wrap.

### Expected Behavior
v-tooltip to display on hover.

### Actual Behavior
Neither the badge or icon display when v-tooltip is in place.

### Reproduction Link
[https://codepen.io/jacCodePen/pen/VQedyd](https://codepen.io/jacCodePen/pen/VQedyd)

**Comment by chewy94** [comment]
@jcepek I was able to get it working by adding `slot="activator"` to your `v-badge` inside the tooltip

Let me know if that resolves your issue

**Comment by jcepek** [comment]
@chewy94 Worked like a champ! Thanks!  My apologies to everyone, being new to this framework I really had thought I had found a bug.  My intentions were not to have developers unnecessarily fix my work, I know you are all busy making a great product.  Appreciate the point in the correct direction.  

On a side note: Not sure if it is for me to close this item or someone else.

**Comment by chewy94** [comment]
You are more than welcome to close your issue if you find a solution 😄 And welcome to Vuetify!

I'll go ahead and close the issue though 😉

**Comment by amazzoccone** [comment]
Actually the Vuetify documentation has an example with an icon.
```
<v-tooltip bottom>
  <v-icon slot="activator" dark color="primary">home</v-icon>
  <span>Tooltip</span>
</v-tooltip>
```

More info: [Tooltip](https://vuetifyjs.com/en/components/tooltips)
