### ISSUE TITLE
[Bug Report] Scoped styling of expansion-panel__header and expansion-panel__body is not possible

### ISSUE THREAD

**Issue by matthewfp** [vuetifyjs/vuetify#3179]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 10

### Steps to reproduce
1. Create an expansion-panel
2. Create a header and a v-card for the content
3. This creates a div of class "expansion-panel\__header" and one of "expansion-panel\__body"
4. Add scoped CSS for both

### Expected Behavior
Scoped CSS styles should be used

### Actual Behavior
Scoped styles do not work, but global styles do

### Reproduction Link
[https://codesandbox.io/s/zqv3y95nnm](https://codesandbox.io/s/zqv3y95nnm)

### Other comments
Probably due to [data-v-...] attribute not being added to the two divs

**Comment by nekosaur** [comment]
Not a bug. See section on deep selectors here https://vue-loader.vuejs.org/en/features/scoped-css.html

**Comment by matthewfp** [comment]
My apologies. Thanks!
