### ISSUE TITLE
[Feature Request] Table group rows by header

### ISSUE THREAD

**Issue by matteocrippa** [vuetifyjs/vuetify#3180]
### New Functionality
The idea is to add a way to group rows by a field and having an header on top.
It's like to have a kinda expand feature always open and under there N sub-rows.

You can imagine in a table where items con be aggregated by month so you will have:
```
Month1
row-1
row-2
row-2
Month2
row-1
row-2
row-2
```

Having the filtering/search feature always in place

### Improvements
no workaround found

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by AGPDev** [comment]
i need so much this.

**Comment by nekosaur** [comment]
I'm not entirely sure what this entails. Could you show another table implementing this feature?

**Comment by matteocrippa** [comment]
I would say something close to ngTable grouping: http://ng-table.com/#/grouping/demo-grouping-basic

**Comment by mbj36** [comment]
This would be so much helpful

**Comment by BrianPurgert** [comment]
The [Syncfusion Grouping](https://ej2.syncfusion.com/16.1.37/demos/#/material/grid/grouping.html) is probably what we should go for.

**Comment by lzhouprovidertrust** [comment]
I made a initial version of it https://github.com/vuetifyjs/vuetify/pull/4966 so I have something to use before 2.0 is released.

**Comment by lzhoucs** [comment]
I made a initial version of it https://github.com/vuetifyjs/vuetify/pull/4966 so I have something to use before 2.0 is released.

**Comment by edivaldoms** [comment]
https://examples.sencha.com/extjs/6.6.0/examples/classic/grid/locking-group-summary-grid.html

**Comment by wouterfovel** [comment]
Releasing our application a month from now, really need the group-by to get our datatables well-organized ...
Any ETA on this? thx

**Comment by mrodal** [comment]
why was this closed? is it not going to be implemented?

**Comment by nekosaur** [comment]
It has been implemented in the upcoming 2.0 release

**Comment by ivanvorona** [comment]
Hi @nekosaur 
When upcoming release 2.0 will be released? i see Q2 2019 but is there a particular release date?

**Comment by DRoet** [comment]
> When upcoming release 2.0 will be released? i see Q2 2019 but is there a particular release date?

Beta next week, release end of june

**Comment by ivanvorona** [comment]
Thx!On May 23, 2019 09:42, Daan Roet <notifications@github.com> wrote:
When upcoming release 2.0 will be released? i see Q2 2019 but is there a particular release date?

Beta next week, release end of june

**Comment by ivanvorona** [comment]
Hello, is there an example with aggregated values from v-data-table in footer for release 2.0? similar to this example: https://examples.sencha.com/extjs/6.6.0/examples/classic/grid/locking-group-summary-grid.html
?
