### ISSUE TITLE
[Feature Request] Support input of type file

### ISSUE THREAD

**Issue by DarkIsDude** [vuetifyjs/vuetify#3183]
### New Functionality
`<v-text-field label="Image" v-model="wine.file" type="file" required></v-text-field>`

### Improvements
I don't have work-arounds actually but it will be a good feature

### Bugs or Edge Cases it Helps Avoid
I will try to make specific CSS... And maybe a PR but it will be a good help :)

**Comment by KaelWD** [comment]
Duplicate of #238
