### ISSUE TITLE
[Feature Request] [v-date-picker] disable left and right calendar navigation beyond min and max dates in allowed-dates

### ISSUE THREAD

**Issue by praveenpuglia** [vuetifyjs/vuetify#3184]
### New Functionality
Currently there's no way to disable those buttons beyond a certain date and in a lot of cases you are required to disable those buttons beyond a range. Example - not allowing user to select a date beyond today. In that case there's no point in allowing the user to move to the next month.

### Improvements
There's no workaround at the moment.

### Bugs or Edge Cases it Helps Avoid
Not sure if this applies to a feature request issue.

**Comment by jacekkarczmarczyk** [comment]
This has been fixed in 1.0beta (and if it's not then it should be a bug report, note that min/max are now handled by min/max props, not by allowed-dates)
