### ISSUE TITLE
[Feature Request] v-date-picker - set current date via prop

### ISSUE THREAD

**Issue by masterjg** [vuetifyjs/vuetify#3185]
### New Functionality
My app allows user to select timezone to adjust calendar. However currently I see no way to update "current date" on v-date-picker.

### Improvements
Currently I see no workarounds.

### Bugs or Edge Cases it Helps Avoid
Wrong timezone in browser. Currently I think that this component uses Date() so it is based on browser settings.

**Comment by jacekkarczmarczyk** [comment]
This feature is already available in 1.0 beta
https://next.vuetifyjs.com/en/components/date-pickers#example-date-current
