### ISSUE TITLE
Data tables - highlight row on click 

### ISSUE THREAD

**Issue by jakub-wisniewski** [vuetifyjs/vuetify#3187]
Hi, is there  build in API which allows to highlight row of data table when a user click on it? Please, don't send me to third party websites in order to answer this question there.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/components/data-tables#example-3

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
