### ISSUE TITLE
[Feature Request] Add support for Vue filters to select menu items

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3189]
### New Functionality
I'd like to use a translation option for select menu options which I currently have configured through a filter.  Currently it doesn't seem to be possible.  

For example in buttons I would add: `{{ $translations.SOME_TRANSLATION_KEY | translate }}` in the content which would run it through an i18n filter. 

### Improvements
No work arounds that I'm aware of.

### Bugs or Edge Cases it Helps Avoid
N/A

**Comment by nekosaur** [comment]
Can you not use the scoped slots for this?

**Comment by gabaum10** [comment]
I tried:

```
<v-select
        :items="sortItems"
        v-model="sortOrder"
        label="Sort"
        single-line
        hide-details
        :max-height="350"
      >
        <template slot="selection" slot-scope="data">
          <div
            @input="data.parent.selectItem(data.item)"
            :selected="data.selected"
            :key="JSON.stringify(data.item)"
          >
            {{ data.item.text | translate }}
          </div>
        </template>
</v-select>
```

The dropdown items look like this:
```
sortItems: [
          {
            text: this.$vtrans.SORT_ACTIVITY_DESC,
            value: 'activityDesc'
          },
          {
            text: this.$vtrans.SORT_ACTIVITY_ASC,
            value: 'activityAsc'
          },
          {
            text: 'Name - A to Z',
            value: 'nameAZ'
          },
          {
            text: 'Name - Z to A',
            value: 'nameZA'
          },
          {
            text: 'Created - Descending',
            value: 'createdDesc'
          },
          {
            text: 'Created - Ascending',
            value: 'createdAsc'
          }
        ]
```

That works for the selected value in the dropdown which you can see in my screenshot in behind.  However, the items themselves are not run through the filter presumably because they are still being rendered by the items collection.  The correctly rendered items don't have the translation key as text.
 
![sortdropdown](https://user-images.githubusercontent.com/1561245/35863700-7574895c-0b1d-11e8-9c17-96dd7f3f193d.png)

**Comment by gabaum10** [comment]
So, I was able to get the translations working by manually calling the translate function in the item text definition like so:

```
         {
            text: this.$t(this.$vtrans.SORT_ACTIVITY_DESC),
            value: 'activityDesc'
          }
```

**Comment by KaelWD** [comment]
I don't think that's something we need to handle. You can map your items in a computed property:
```js
computed: {
  translatedItems () {
    const items = Array(this.sortItems.length)
    for (let i = 0; i < this.sortItems.length; ++i) {
      const item = this.sortItems[i]
      items[i] = {
        text: this.$t(item.text),
        value: item.value
      }
    }
    return items
  }
}
```

**Comment by gabaum10** [comment]
Yeah, in this instance for sure.  What about the cases when you want to apply for example a formatter of some kind?  Like maybe a shared date formatter or something for a select of dates?  

I suppose you could still map to a computed prop, but if it's a filter that's used in other places for textual formatting, it makes sense to just pass it along to the select renderer.

I'm not super convinced it's necessary, I just don't want to leave out a potentially useful feature.

**Comment by KaelWD** [comment]
Oh, and I just realised that you're using the wrong slot too. `slot="selection"` is for the currently selected item, `slot="item"` is for each item in the list.

**Comment by gabaum10** [comment]
Ahh.  Well that may do it then.  Let me try and report back.

**Comment by KaelWD** [comment]
It should be under scoped slots
