### ISSUE TITLE
[Bug Report] Wrong width of .application on Chrome for Android

### ISSUE THREAD

**Issue by Axel92Dev** [vuetifyjs/vuetify#3190]
### Versions and Environment
**Vuetify:** 0.16.8
**Vue:** 2.3.3
**Browsers:** Chrome 63.0.3239.132
**OS:** Android

### Steps to reproduce
Access https://watch-neighbors.herokuapp.com/#/ from Chrome for Android

### Expected Behavior
The width is correct as it is in chrome simulator

### Actual Behavior
the width is 60px larger than body resulting in bad positioning

### Reproduction Link
[https://codepen.io/pen/](https://codepen.io/pen/)

### Other comments
i've just the application in heroku so no need of codepen

**Comment by jacekkarczmarczyk** [comment]
That's a prehistoric version of Vuetify, please check your issue using the latest beta and latest vuejs. If it still happens provide a codepen (with proper version of vuetify and vuejs) and reopen the issue
