### ISSUE TITLE
[Feature Request] v-select different TAB behavior, minimal search characters, reset list after selecting a value in multiselect

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#3192]
### New Functionality
I'm playing with `<v-select>` that is autocomplete and multiple as the same time
My suggestions based on #10 example from this page, https://vuetifyjs.com/components/selects.

1. Allow different behavior on TAB key press. Currently, when the select list opened, the tab key acts like enter key, it switches the element's selected state. The native html select closes the dropdown on first TAB and switches to the next form element by the next TAB press. It would be nice to have this (optional) behavior. 

2. Consider this example, https://codepen.io/kasheftin/pen/NyryVV?&editors=101. Start typing `ala`, press enter. The Alabama selected. Type `wy`. Alabama disappears. Is it a bug? Press enter. Now select contains Wyoming. Type `ala`. Selected Wyoming magically changes to Alabama.

3. Reload the page and type `ala`. Select the first item. Now the input does not contain `ala` anymore, but the search variable still holds `ala` value, and the list still shows 3 results. I would suggest to add the option for the different behavior - close the list and reset search variable. Even if I do that manually (watch the value and set search = '' when it changes) - the select dropdown still holds 3 items. Probably the option should choose between keeping the input search after selecting a value (so it will be Alabama chip followed by `ala` search and 3 results below) and reset it (only Alabama chip and empty search, no list below).

4. Implement minimal count of characters for starting search. That's probably can be achieved manually, but it does not work if combined with cache-items property.   

### Improvements
The first suggestion makes `<v-select>` behavior closer to the native `<select>` behavior.

### Bugs or Edge Cases it Helps Avoid
I'm almost certain that the #2 suggestion shows a bug in `<v-select>`. I could format it as a bug in the separate issue if you think so.

**Comment by jacekkarczmarczyk** [comment]
Please create separate issues for each feature request
