### ISSUE TITLE
[Bug Report] v-select with autocomplete - wrong highlighting of matched text when using custom filter

### ISSUE THREAD

**Issue by lattam** [vuetifyjs/vuetify#3194]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Linux x86_64

### Steps to reproduce
Open country select dropdown and type "et"

### Expected Behavior
The filtered items are highlighter correctly.

### Actual Behavior
The items which contain special characters (and which pass the test in my custom filter function) are wrongly highlighted:

Île Bouv**et**
Antigua-**et**-Barbuda
**Éthiopie**
**États-Unis**

### Reproduction Link
[https://codepen.io/lattam/pen/VQjNyw](https://codepen.io/lattam/pen/VQjNyw)

### Other comments
I would suggest either somehow reuse the custom filter function (which might not be easy because it returns boolean and not indexes) or add possibility to disable the matched text highlighting. Or add possibility to match special characters (for example using lodash.deburr like in my example).

Thank you for your time!

**Comment by Mikilll94** [comment]
Is it going to be done? Because I think that removing diactrics during search is pretty common use case.

**Comment by relief-melone** [comment]
would also be very happy if this was included

**Comment by marlavargas** [comment]
Hello! Did anyone get a solution?

**Comment by KaelWD** [comment]
Resolved by #14035, filter functions can return a match index.
