### ISSUE TITLE
[Bug Report] Snackbar color applied incorrectly.

### ISSUE THREAD

**Issue by AlexKovynev** [vuetifyjs/vuetify#3199]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Ubuntu 16.04

### Steps to reproduce
Apply color prop.

### Expected Behavior
Colored snackbar.

### Actual Behavior
Colored band behind snackbar

### Reproduction Link
[https://next.vuetifyjs.com/en/components/snackbars](https://next.vuetifyjs.com/en/components/snackbars)

![sn](https://user-images.githubusercontent.com/3380440/35871286-8759c098-0b6c-11e8-8a68-1e431143dcaa.png)

**Comment by nekosaur** [comment]
Please provide a screenshot as well

**Comment by AlexKovynev** [comment]
You see? I update issue.

**Comment by timoschwarzer** [comment]
Related to https://github.com/vuetifyjs/vuetify/pull/3155
