### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#32]
After upgrading to 0.7.9, I'm getting the following error on the console:
`vue.runtime.common.js:521 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

Did I few tests and even removed the `<router-view>` tag to make sure this wasn't coming from my templates.
Here's the App.vue content:

    <template>
      <v-app top-navbar footer left-sidebar>

        <header>
          <v-navbar>
            <v-navbar-side-icon class="hidden-sm-and-up"></v-navbar-side-icon>
            <v-navbar-logo>AltMan</v-navbar-logo>
            <v-navbar-items>
              <v-navbar-item v-dropdown:dropdown
                  :item="{ href: '#!', text: 'Client', icon: false }"
              ></v-navbar-item>
            </v-navbar-items>
            <v-dropdown v-bind:items="navMenu" id="dropdown" right></v-dropdown>

          </v-navbar>
        </header>

        <main>
          <v-sidebar id='sidebar'  left>
            <v-sidebar-items :items="sideMenu"></v-sidebar-items>
          </v-sidebar>

          <v-content>
            <v-container fluid>
              
            </v-container>
          </v-content>
        </main>

        <v-footer></v-footer>

      </v-app>
    </template>

**Comment by johnleider** [comment]
What version of vue are you running?

**Comment by johnleider** [comment]
If you are running on vue@2.1.7 there seems to be an issue with previous plugins as noted in the official release notes. Vuetify has not been upgraded to support 2.1.7 yet.

**Comment by mfferreira** [comment]
Yes, I had updated a few packages, including Vue to 2.1.7.
Downgrading to 2.1.6 fixed it (along with vue-server-renderer and vue-template-compiler).
