### ISSUE TITLE
Bug: Select component 0.10.0

### ISSUE THREAD

**Issue by banazak** [vuetifyjs/vuetify#320]
It selects all the array data instead of single object

https://codepen.io/banazak/pen/yMWEoG

**Version**  0.10.0

**Comment by johnleider** [comment]
Not a bug. You are not using a value for it to hook into. If you use an object, the default is ```value```. It is an easy fix, https://codepen.io/johnjleider/pen/rygrwM , set prop ```item-value``` to text.

**Comment by iesta** [comment]
Thank you !
Working example : http://codepen.io/iesta/pen/vmeRvv

This should be in the doc somewhere :-)

**Comment by johnleider** [comment]
Docs are being completely overhauled and will cover this! Ty
