### ISSUE TITLE
[Bug Report] v-tab with "to" attribute does not change tab contents immediately - it lags one tab click behind

### ISSUE THREAD

**Issue by pbastowski** [vuetifyjs/vuetify#3203]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Mac OS 10.12.6

### Steps to reproduce
Create a v-tabs with three v-tab elements that each have a unique "to" attribute.
Please see the Codepen link.

### Expected Behavior
1. Clicking on tab TWO should show the contents of tab TWO
2. Clicking on tab THREE should show the contents of tab THREE
3. Clicking on tab TWO again should show the contents of tab TWO again

### Actual Behavior
1. Clicking on tab TWO does nothing.
2. Clicking on tab THREE shows the contents of tab TWO.
3. Clicking on tab TWO again shows the contents of tab THREE.

Clicking on tabs lags in updating the v-model linked variable.

### Reproduction Link
[https://codepen.io/pbastowski/pen/gvwxLp?editors=1000](https://codepen.io/pbastowski/pen/gvwxLp?editors=1000)

### Other comments
This was working properly in Beta.5. If you change the codepen version of Vuetify to Beta.5 the same code will work as expected.

**Comment by AlexKovynev** [comment]
https://github.com/vuetifyjs/vuetify/pull/3126

:(

**Comment by KaelWD** [comment]
It probably does need that nextTick after all

**Comment by nasirouwagana** [comment]
@pbastowski I have the same issue

**Comment by pbastowski** [comment]
@nasirouwagana 

If you need a workaround right now, this is what I did:

```pug
    v-tabs(v-model="active_tab")
        v-tab(@click.native.stop="to({ path: '/previous' })") Previous
        v-tab(@click.native.stop="to({ path: '/current' })") Current
```

Data section:
```js
data() { return {
        active_tab: '',
    }
}
```

Methods section:
```js
methods: {
    to(route) {
        this.active_tab = route.path
        this.$router.push(route.path)
    }
}
```

**Comment by pbastowski** [comment]
@johnleider 
Thanks. 
Is there a way for me try the latest commits? Perhaps a continuous integration that auto-publishes to npm a version such as vuetify@nightly or vuetify@hot.

**Comment by johnleider** [comment]
You would need to clone the repository, check out latest dev and link the package locally to your project.

**Comment by pbastowski** [comment]
Yeah, I thought so. Thanks again.
