### ISSUE TITLE
how to accress action button in row properies

### ISSUE THREAD

**Issue by MINASHIJ** [vuetifyjs/vuetify#3204]
i have datatable with specific column that has a some of button to control each item separately, i want to  each button color in row after user click on this
`<v-data-table
                    v-bind:headers="headers"
                    v-bind:items="items"
                    v-bind:search="search"
                    v-model="selected"
                    item-key="name"
                    select-all
                    no-data-text="بدون هیچ آگهی"
                    no-results-text="نتیجه ای یافت نشد"
                    :rows-per-page-items="[20,40,60 ,{ text:'همه موارد', value: -1 }]"
                    rows-per-page-text="تعداد ردیف در هر صفحه"
                    class="elevation-1"
                    v-bind:pagination.sync="pagination">

                <template slot="headerCell" slot-scope="props">
                    <v-tooltip bottom>
        <span slot="activator">
          {{ props.header.text }}
        </span>
                        <span>
          {{ props.header.text }}
        </span>
                    </v-tooltip>
                </template>
                <template slot="items" slot-scope="props">
                    <td>
                        <v-checkbox
                                primary
                                hide-details
                                v-model="props.selected"
                        ></v-checkbox>
                    </td>
                    <td>{{ props.item.id }}</td>
                    <td class="text-xs-right">{{ props.item.title }}</td>
                    <td class="text-xs-right">{{ props.item.city_name }}</td>
                    <td class="text-xs-right">{{ props.item.cat_name }}</td>
                    <td class="text-xs-right">{{ props.item.desc }}</td>
                    <td class="text-xs-right">{{ props.item.tel }}</td>
                    <td class="text-xs-right">
                        <v-badge
                                v-if="props.item.attachments.length"
                                overlap color="red">
                            <span slot="badge">{{ props.item.attachments.length }} </span>
                            <v-avatar
                                    class="purple"
                            >
                                <img :src='getImageURL(props.item.attachments)' alt="avatar">
                            </v-avatar>
                        </v-badge>
                    </td>
                    <td class="text-xs-right">{{ props.item.shamsi_date }}</td>
                    <td class="text-xs-right">
                        <v-btn
                                :exact="true"

                                tag="span"
                                fab
                                :color="tableStatusColor"
                                :loading="table_status_loading"
                                @click.native="changeStatus(props.item.id)"
                                :disabled="table_status_loading"
                        >
                            
                            <v-icon>cached</v-icon>
                        </v-btn>
                    </td>
                    <td>
                        <v-btn color="primary" fab small dark @click.native.stop="showeditDialog(props.item.id)">
                            <v-icon>edit</v-icon>
                        </v-btn>
                        <v-btn color="error" fab small dark @click.native.stop="showremoveDialog(props.item.id)">
                            <v-icon>delete</v-icon>
                        </v-btn>
                    </td>
                </template>
            </v-data-table>`

how to control each button in row ?

**Comment by nekosaur** [comment]
The issues board is for bugs and feature requests only. Please visit our community at https://chat.vuetifyjs.com for questions and help.
