### ISSUE TITLE
[Bug Report] speed-dial icons are misaligned

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#3207]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/16421948/35909241-0cda2e3a-0c47-11e8-9b93-1e033f844dc8.png)

### Reproduction Link
[https://codepen.io/anon/pen/KQgOga?editors=1010](https://codepen.io/anon/pen/KQgOga?editors=1010)

### Other comments
new in beta 6

from #3127

**Comment by Ewocker** [comment]
Hi, 
This is not fixed in v1.0.0. 
I checked the reproduction above and was able to reproduce it by using v1.0.0 https://codepen.io/anon/pen/KQgOga?editors=1010

**Comment by jacekkarczmarczyk** [comment]
Your codepen is not using vuetify@1.0

https://codepen.io/anon/pen/GQvYEY

**Comment by Ewocker** [comment]
I change it to the v1.0.0, but I realize that the problem is related to #3279 because I have the tooltip with v-btn. Sorry for the wrong report. I was about to say that but you reply in ten minutes!!!!
Thanks for the hard work.
