### ISSUE TITLE
[Bug Report] v-text directive does not behave like plain text or {{ Mustache }} interpolation on v-btn

### ISSUE THREAD

**Issue by tbsvttr** [vuetifyjs/vuetify#3208]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Mac OS 10.13.3

### Steps to reproduce
Code with v-text directive:

```
              <v-btn
                v-text="'Registrieren'"
                color="secondary"
                type="submit"
              />
```

Code with {{ Mustache }} interpolation or plain text:

```
              <v-btn
                color="secondary"
                type="submit"
              >
                Registrieren
              </v-btn>
```

### Expected Behavior
It should behave like the same: https://vuejs.org/v2/api/#v-text

### Actual Behavior

{{ Mustache }} interpolation or plain text produces:

```
<button data-v-23e5932c="" type="submit" class="btn secondary" id="___registration___button" style="position: relative;">
<div class="btn__content">
              Registrieren
</div>
</button>
```

v-text directive produces (div with class "btn__content" is missing):

`<button data-v-23e5932c="" type="submit" class="btn secondary" id="___registration___button" style="position: relative;">Registrieren</button>`

### Reproduction Link
[https://codepen.io/tbsvttr/pen/XZNJbz](https://codepen.io/tbsvttr/pen/XZNJbz)

**Comment by KaelWD** [comment]
Nothing we can do about that. Use the slot instead.
