### ISSUE TITLE
[Bug Report] Label on Select (Customized item text and value)

### ISSUE THREAD

**Issue by ecencio** [vuetifyjs/vuetify#3210]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.3
**Browsers:** Google Chrome, Mozilla Firefox, Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
Select an item

### Expected Behavior
After selecting an item, show label on top of the selected item

### Actual Behavior
After selecting an item label is not showing

### Reproduction Link
[https://codepen.io/anon/pen/QQGGNQ](https://codepen.io/anon/pen/QQGGNQ)

**Comment by jacekkarczmarczyk** [comment]
Remove `single-line` prop
