### ISSUE TITLE
[Bug Report] v-btn calling another button @click method

### ISSUE THREAD

**Issue by Laurence88** [vuetifyjs/vuetify#3215]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Mac OS 10.13.3

### Steps to reproduce
          <v-btn v-if="!loggedIn" flat class="hidden-xs-only" :to="'/Signup'">Sign Up</v-btn>
          <v-btn v-if="!loggedIn" flat class="hidden-xs-only" :to="'/Login'">Login</v-btn>
          <v-btn v-if="loggedIn" flat class="hidden-xs-only"  @click="logout">Logout</v-btn>
        </v-toolbar-items>
    </v-toolbar>

 methods: {
      logout() {
        this.$store.dispatch('logout')
        this.$router.push('/LandingPage')
      }

### Expected Behavior
I login, then logout ...click the Login btn and the the Login page loads

### Actual Behavior
I login, then logout ...click the Login btn and the @click="logout" methods gets called.
I have to refresh the page for this to work.
This code was working before the update to beta.5

### Reproduction Link
[https://codepen.io/l-achard/pen/MQbqbp?editors=1010](https://codepen.io/l-achard/pen/MQbqbp?editors=1010)

### Other comments
This code is in a full app. Could not reproduce this in code pen,
but I have copied the page code in code pen in case you need to see it.
Many thanks!

**Comment by jacekkarczmarczyk** [comment]
Please provide reproduction, you can use codesandbox if you can't reproduce it in codepen. You can also try to get some help on discord channel http://chat.vuetifyjs.com
