### ISSUE TITLE
[Bug Report] Each icon color

### ISSUE THREAD

**Issue by artimann** [vuetifyjs/vuetify#3216]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140, Internet Explorer, Microsoft Edge, Safari, Mozilla Firefox, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Nothing

### Expected Behavior
Nothing

### Actual Behavior
This is make a side menu popup from side and close like any each mobile app.
I'm trying to change each icon color but after reading documentation and couple of solutions can't make something to got work. The components are creating all HTML code and there is no any way to add some specific class to icons. For example color class.

### Reproduction Link
[https://codepen.io/anon/pen/paNBGr](https://codepen.io/anon/pen/paNBGr)

**Comment by jacekkarczmarczyk** [comment]
You can set icons color by adding `color` prop.
Closing this issue as it doesn't look like a bug report and the reproduction is not working, for general questions join us at the official discord chat https://chat.vuetifyjs.com

**Comment by artimann** [comment]
There is no properties like color in documentation, plus I tried and it's isn't works.

**Comment by jacekkarczmarczyk** [comment]
If you have difficulties with providing the reproduction please first visit the chat for help

And about the `color` prop - https://vuetifyjs.com/components/icons:
![image](https://user-images.githubusercontent.com/15625235/35973858-8c50439e-0d09-11e8-8d3b-1a0fc5daca12.png)

**Comment by artimann** [comment]
I'm talking only about side menu (drawers):
https://vuetifyjs.com/components/navigation-drawers

Also I include the code snippet in main topic.

I saw that I can pass color property per icon if it's HTML tag but what's happend when you have a menu?

**Comment by jacekkarczmarczyk** [comment]
The code snippet you've provided cannot be run in the browser. Please visit https://chat.vuetifyjs.com for further discussion. Thank you.
