### ISSUE TITLE
[Bug Report] Detachable mixin doesn't allow element objects

### ISSUE THREAD

**Issue by aaronrosenthal** [vuetifyjs/vuetify#3226]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 7

### Steps to reproduce
Binding the "attach" property to an HTMLElement fails prop validation.

### Expected Behavior
Prop validation should not fail.

### Actual Behavior
The following error message is displayed:

[Vue warn]: Invalid prop: type check failed for prop 'attach'. Expected Boolean, String, Object, got HTMLDivElement.

### Reproduction Link
[https://codepen.io/anon/pen/ddNvbm](https://codepen.io/anon/pen/ddNvbm)

**Comment by KaelWD** [comment]
😠 You'd think `Object` would allow *any* object...
