### ISSUE TITLE
[Bug Report] v-avatar in v-btn in v-toolbar-items wrong hover effect

### ISSUE THREAD

**Issue by ShadowD** [vuetifyjs/vuetify#3229]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132, Google Chrome
**OS:** Windows, Mac OSX, Windows 10

### Steps to reproduce
Open https://codepen.io/anon/pen/WMoybE and hover avatar in header.

### Expected Behavior
Overlay size (hover) === avatar size

### Actual Behavior
Overlay has wrong dimensions - to height and to narrow.

### Reproduction Link
[https://codepen.io/anon/pen/WMoybE](https://codepen.io/anon/pen/WMoybE)

**Comment by Leehman** [comment]
I'm currently reviewing your requested issue and will respond after the review.

**Comment by johnleider** [comment]
This can be solved by simply using a large btn as the default is too small

https://codepen.io/johnjleider/pen/ZPyqJz
