### ISSUE TITLE
Bug in data tables

### ISSUE THREAD

**Issue by iansowinski** [vuetifyjs/vuetify#323]
### Steps to reproduce

- Create data table, allow sorting and edit of some field
- Open field to edit in browser, and without saving the changes click on sorting
- Look at console

### Versions

0.10.3

### What is expected ?

Edit should be canceled and sorting should start

### What is actually happening ?

Editable field becomes blank, and console raises error

### Reproduction Link

[http://codepen.io/iansowinski/pen/BWgayO](http://codepen.io/iansowinski/pen/BWgayO)

**Comment by johnleider** [comment]
Fixed the bug causing the console error. As far as the data being empty, this is sort of a quirk that comes with scoped slots and the way I setup the docs. When the table is sorted, before the edit-dialog closes, it actually switches data to the row that is sorted into the position of the initial row you open the data up on. So when that closes, it had not set the private property yet that is used for fall back.

I've updated the documentation to reflect this.
