### ISSUE TITLE
[Bug Report] v-expansion-panel input event only fires on initial expansion or closing

### ISSUE THREAD

**Issue by appurist** [vuetifyjs/vuetify#3230]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.5
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- In my codesandbox example above, Section 1 is open by default.
- Open the Console pane.
- Click on Section 3 (or something other than 1) repeatedly.

### Expected Behavior
I'd expect the input event to fire with a `true` every time the expansion panel is opened, and with a `false` every time it is closed.

### Actual Behavior
Only the first/new `true` input event is fired for any given section, while a close does successfully fire the input=`false` case for all closes.  If you click to open and close Section 3 repeatedly, you see open,close,(nothing),close,(nothing),close,(nothing),close ... so only the first open for that section. Only the input=`false` events come in, not the input=`true` cases.

### Reproduction Link
[https://codesandbox.io/s/l99jy01w79?module=%2Fexpander.vue](https://codesandbox.io/s/l99jy01w79?module=%2Fexpander.vue)

### Other comments
I'm not sure if it's a bug but it seems unexpected and inconsistent at least.  The purpose is due to an apparently limitation (can't move the expand arrows to the left side?) but the actual issue is that the `input` event is only triggered the _first_ time an expansion box is opened (and yet _every_ time it is closed). This sandbox example demonstrates this if you have the Console window open.  

Perhaps there's a better way to hook the open/close (and ideally there would just be a `left-arrow` prop or something to move it to the left) but maybe input isn't the best even for that. Any other ways to track the expand/collapse events?  Still, the `input` event seems one-sided with only the `false` cases being passed on the event.

**Comment by nekosaur** [comment]
The reason you're having problems with the `@input` value is because you're setting `:value="n==currSection"` as well. I have no idea exactly what you're trying to achieve, but you can see that events fire correctly in this codepen https://codepen.io/anon/pen/xYprxq

**Comment by appurist** [comment]
Unfortunately, that codepen has slightly different goals than mine; namely it does not provide code-based selection of an expansion.  But it's interesting, that removing the `:value` prop fixes the events. 

However, that breaks the ability for the app to open one of the expansions from the code, selectively. (See the Prev/Next buttons in my codepen which do this.)  Those buttons just increment or decrement `currSection` which is then tested in the `:value` prop to indicate open (expanded) or not.

I'd be very much up for any mechanism that can open an expansion without a mouse click.  How would you open one of these in code, if you were not going to use :value=true or something like that?

**Comment by appurist** [comment]
I should clarify here that I did remove the `:value` prop form my codepen and did get the events normally. However, that breaks the buttons of course, and the ability to have a specific panel expanded by default.

**Comment by appurist** [comment]
Here's a slightly modified version of your codepen that adds an extra panel to the end and opens it by default: https://codepen.io/paulw/pen/BYJxyN?editors=1011
Change the `:value=true` to `:value=false` to have it closed by default, change that at runtime to programmatically open or close it (like the Prev/Next buttons in my codesandbox example).

It seems that adding this `:value` prop prevents the open/expand case from sending the `true` event, while not preventing the close `false` case from being reported.

**Comment by nekosaur** [comment]
If this is just about programatically controlling the states of expansion panels, that is currently tracked in https://github.com/vuetifyjs/vuetify/issues/3271

**Comment by appurist** [comment]
Indeed, that would provide a _new_ mechanism for toggling the expansion panels, but I don't quite understand, are you saying the `:value` prop isn't _supposed to_ work (to do this)? (It does work, and I got that from one of the examples... somewhere.)  The only problem seems to be that its presence causes the `true` event from firing, in cases where it otherwise would if the `:value` prop had not been supplied.  It is, at the very least, inconsistent. 

I've been assuming it's just a matter of the tests for the event being in the wrong order in the expand vs contract cases (e.g. testing if the panel is to be expanded _before_ expanding it, or something of that nature).  The order of the steps in the logic likely needs to be reversed when expanding vs contracting the panels, so currently it only works on one of the cases when `:value` is used.  I think this is likely a fairly trivial problem, easily fixed, but I haven't had a chance to peek at the code for this yet (and obviously don't understand the intent, it seems).

**Comment by nekosaur** [comment]
Unfortunately I do not have the time to delve into this specific bug any further. And since #3271 provides a proper way of achieving the same functionality, I will be closing this issue.

Should this bug show up in any other context we will take another look.

**Comment by sayhitoarvind** [comment]
I came across this bug today

**Comment by johnleider** [comment]
Please do not comment on closed issues. If you have a bug, please create a new issue, https://issues.vuetifyjs.com or seek help in our community, https://community.vuetifyjs.com
