### ISSUE TITLE
[Feature Request] add slots for v-carousel controls

### ISSUE THREAD

**Issue by jeck5895** [vuetifyjs/vuetify#3235]
### New Functionality
I want to set thumbnails of the images as the carousel controls

### Improvements
 there are no work around for this feature at the moment.

### Bugs or Edge Cases it Helps Avoid
doesnt solve any bugs, but may allow for a richer and more customizable interface.

**Comment by nekosaur** [comment]
This could be supported by allowing the use of slots for the next/prev controls

**Comment by jeck5895** [comment]
Sorry but I don't get it... Can you elaborate it?

**Comment by killbotXD** [comment]
@jeck5895 I had one more suggestion. We can also have custom text on the delimiters rather than Icons/Images. 
I was trying to make a `carousel` like this but couldn't find any method to add text inside `delimiters`.
It would be nice if someone working on this issue tries to do this also.
![Screenshot from 2020-03-19 14-17-48](https://user-images.githubusercontent.com/42870378/77048546-a46c9800-69ec-11ea-8e1e-4d752c9abdcd.png)

**Comment by killbotXD** [comment]
same can be done to the carousel controls.

**Comment by chasedougherty4628** [comment]
I know you can simply add the images and then change the "value" attribute on the v-carousel element. This will allow you to change to the selected image. 
`  <v-carousel
    hide-delimiters
    :value="currentCarousel"
  >
    <v-carousel-item
      v-for="(component, index) in products()"
      :key="index"
    >
      <div class="justify-center d-flex flex-column align-center">
        <h3 class="red--text text--darken-3 text-center">
          Products
        </h3>
        <h1 class="text-center font-weight-bold pb-8">
          {{ component.attributes.displayName }}
        </h1>
        <v-img
          :contain="true"
          max-width="1000"
          max-height="700"
          :src="require(`@/assets/images/dimensions/${component.attributes.imageName}`)"
        />
        
        <div class="justify-center d-flex">
          <div
            v-for="(product, i) in productsWithDimensions()"
            :key="i"
            class="pa-2"
          >
            <v-img
              :contain="true"
              max-width="80"
              max-height="70"
              :src="require(`@/assets/images/dimensions/${product.attributes.dimensionImageName}`)"
              :class="index === i ? 'selected-image-color' : ''"
              @click="currentCarousel = i"
            />
          </div>
        </div>
      </div>
    </v-carousel-item>
  </v-carousel>`

**Comment by KaelWD** [comment]
prev/next slots added in #12602, delimiter slots may come in some future version.

**Comment by KaelWD** [comment]
An `item` slot was added in v3 with #14813
