### ISSUE TITLE
[Bug Report] Webpack-ssr Dialog document is not defined

### ISSUE THREAD

**Issue by jaelys** [vuetifyjs/vuetify#3242]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce

A setting : value = "true" , an error occurs .

### Expected Behavior
For the response for issue #411 #423 but still I am getting the error. 

### Actual Behavior
in ssr can run

### Reproduction Link
[https://codepen.io/JAELYS/pen/paeJKL](https://codepen.io/JAELYS/pen/paeJKL)

**Comment by KaelWD** [comment]
I can't reproduce this, can you provide a basic git repo that will show the error?
