### ISSUE TITLE
[Bug Report] Wrong character count of a <v-text-field multi-line>  using  maxlength including newlines

### ISSUE THREAD

**Issue by kris0017** [vuetifyjs/vuetify#3245]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.4.4
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
1. Create page with text field (or open link to reproduce):
`<v-text-field :counter="5"  v-model="message" maxLength="5" multi-line></v-text-field>`
2. Open it in Safari.
3. Click key 'enter' 5 times.

### Expected Behavior
Counter: 5/5
User is able to enter 5 new lines

### Actual Behavior
Counter: 3/5
User is not able to enter new lines

### Reproduction Link
[https://codepen.io/pen/rJyOPO](https://codepen.io/pen/rJyOPO)

**Comment by adamiBs** [comment]
i would like to try fix this bug as a first contribution

**Comment by blalan05** [comment]
This seems like it is expected behavior for textareas. See <https://codepen.io/etiennemartin/pen/qpwxZj>.
This issue is also present in Win7, Chrome 72 and Vuetify 1.5.9.

**Comment by johnleider** [comment]
This issue is no longer present in the latest version

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
