### ISSUE TITLE
[Feature Request] component size not accepting otherthan 'px'

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3249]
### New Functionality
For make it responsible sometime components need to accept the sizes in 'vh', 'rem' or in '%'

### Improvements
User can set any kind of size, height, width metrics(vh, em, %...)

### Bugs or Edge Cases it Helps Avoid
All component should responsive and should not only in 'px'

**Comment by nekosaur** [comment]
Which component(s) specifically have you had this problem with?

**Comment by ksankumar** [comment]
v-progress-circular
v-icon
v-chip
v-card
v-avatar
v-badge

Example: https://codepen.io/ksankumar/pen/xYdYdz

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
