### ISSUE TITLE
[Feature Request] DataTable Search by columns

### ISSUE THREAD

**Issue by jlfernandesjn** [vuetifyjs/vuetify#3250]
### New Functionality
Search by columns indivudualy.

### Improvements
It will avoid to use other dataTable plugins keeping theme integration.

### Bugs or Edge Cases it Helps Avoid
Visual theme bugs caused by other dataTable plugins

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3102
