### ISSUE TITLE
[Feature Request] DataTable Export to PDF and XLS like formats

### ISSUE THREAD

**Issue by jlfernandesjn** [vuetifyjs/vuetify#3252]
### New Functionality
Export data content to PDF and XLS like formats

### Improvements
It will avoid to use other dataTable plugins keeping theme integration.

### Bugs or Edge Cases it Helps Avoid
Visual theme bugs caused by other dataTable plugins

**Comment by nekosaur** [comment]
There are no plans to implement this. It is a user land feature that is independent of the framework.

**Comment by KaelWD** [comment]
Duplicate of #3128
