### ISSUE TITLE
[Bug Report] list group can't include another list group

### ISSUE THREAD

**Issue by LimbaHub** [vuetifyjs/vuetify#3256]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Windows 10

### Steps to reproduce
when i click the second level list, it supposed to spread it's child items. But it turned to closed it's parent item;

### Expected Behavior
the child items of second level items can show up when 

### Actual Behavior
can't show

### Reproduction Link
[https://codepen.io/anon/pen/JpNzKq?editors=1010](https://codepen.io/anon/pen/JpNzKq?editors=1010)

**Comment by nekosaur** [comment]
Nested list groups are supported in current 1.0 beta. However there are currently no examples on https://next.vuetifyjs.com. See https://github.com/vuetifyjs/vuetifyjs.com/issues/216

**Comment by johnleider** [comment]
Available in 1.0, but needs documentation. However, not a bug.

**Comment by bannostookaylo** [comment]
Anyone else that runs across this check this out https://github.com/vuetifyjs/vuetifyjs.com/blob/dev/components/core/AppDrawer.vue#L53

This is the source for the nav draw on the site... notice the attribute of "sub-group" on the nested v-list-group ... that is key

**Comment by calebanthony** [comment]
The updated link to the above example (which now 404s):
https://github.com/vuetifyjs/vuetifyjs.com/blob/dev/src/components/core/Drawer.vue
