### ISSUE TITLE
Top slot in sidebar

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#326]
Is the slot `top` missing in the sidebar? I couldn't find anything in the sourcecode.
https://vuetifyjs.com/components/sidebar

### Versions
10.0.03

### What is expected ?
The slot `top` should be rendered up in the sidebar

### What is actually happening ?
only the default slot got renderd

### Reproduction Link
http://codepen.io/anon/pen/yMdgKN

**Comment by johnleider** [comment]
This should be removed from the documentation. The slot no longer has a purpose after we moved to explicit  declaration of the sidebar contents. You can simply organize your markup to accommodate content being on the top.
