### ISSUE TITLE
[Bug Report] On mobile device, In searchable multi select dropdown, keyboard get closed and reopened on every select

### ISSUE THREAD

**Issue by rajagopalx** [vuetifyjs/vuetify#3260]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Android

### Steps to reproduce
1. On your mobile device, open up https://next.vuetifyjs.com/en/components/selects#example-tags
2. Select every dropdown item.
3. You will notice your keyboard get closed and reopened on every select.

### Expected Behavior
The keyboard should not close and reopen on every select.

### Actual Behavior
On Each and every select Keyboard get closed and reopened.

### Reproduction Link
[https://codepen.io/anon/pen/YeVeeb?&editors=101](https://codepen.io/anon/pen/YeVeeb?&editors=101)

### Other comments
Reference 10 sec Video: 
https://drive.google.com/file/d/1ORcPBl7em8Mpozf9troLrgKM2lFyU-4p/view

**Comment by johnleider** [comment]
This appears to be resolved. Tested in Galaxy S8+. Can you check against version rc.2?

**Comment by rajagopalx** [comment]
Yup. Bug get resolved in rc.2. Thank You.
