### ISSUE TITLE
Required property still active even when the input was provided

### ISSUE THREAD

**Issue by jamesxv7** [vuetifyjs/vuetify#327]
### Steps to reproduce
Add the `required` property to `v-text-field` component.

### Versions

Vue.js: 2.2.6
Vuetify: 0.10.3
### What is expected ?

Red indication of a required input removed after text field lost focus.
### What is actually happening ?

Red indication is still displayed when input is provided.
### Reproduction Link

http://codepen.io/jamespr/pen/GWbErd

**Comment by jamesxv7** [comment]
Also the computed property `hasError` remains true even when the input is provided and the input format is correct.

**Comment by johnleider** [comment]
The text-input does not have a v-model. When you add this, it works as [expected](http://codepen.io/johnjleider/pen/OpegBq).
