### ISSUE TITLE
[Bug Report] Carousel adding Jumbotron class to items

### ISSUE THREAD

**Issue by baztypetrucci** [vuetifyjs/vuetify#3273]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.4
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.3

### Steps to reproduce
We are using the component carousel for every carousel in the site, but the new version is adding "jumbotron" class by default

### Expected Behavior
The class doesn't need to be added

### Actual Behavior
Is adding the class "jumbotron"

### Reproduction Link
[https://codesandbox.io/s/1z7n2nrx5l](https://codesandbox.io/s/1z7n2nrx5l)

### Other comments
I left the page of the example using the component on cadesandbox only for checking the markup purposes, but the site is already working: movil.relaxchile.cl

**Comment by johnleider** [comment]
The carousel-item is made from the jumbotron, not a bug.
