### ISSUE TITLE
[Bug Report] Impossible to disable carousel auto cycle

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3275]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Add cycle="false" and interval="0" to v-carousel.

### Expected Behavior
Images cycle only on user input (clicking arrows or dots).

### Actual Behavior
Carousel cycles ignoring cycle and interval settings.

### Reproduction Link
[https://codepen.io/anon/pen/yvobyy?&editors=101](https://codepen.io/anon/pen/yvobyy?&editors=101)

**Comment by johnleider** [comment]
Look at the console logs, you are passing in a string.

**Comment by joshas** [comment]
<v-carousel :cycle="false"> that's what I needed.

**Comment by techmayordomo** [comment]
I have same problem. I have now:
<v-carousel height="auto" interval="1000000" :cycle="false">
cycling is still enabled. 
also note I have put interval="1000000" as interval="0" puts a validation error in the console. can interval be turned off at all?

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by techmayordomo** [comment]
ok, you're right. not opening another ticket as cycle does what it's intended to do, though the naming was misleading for me. I've expected cycle would turn off looping
