### ISSUE TITLE
[Feature Request] Stepper Component is not Colorable

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#3276]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Mac OS 10.13.3

### Steps to reproduce
Try applying a color attribute to the v-stepper-step element.

### Expected Behavior
It should be possible to change the colors used in the v-stepper-step element in the stepper component.

### Actual Behavior
There is no method to change the color of the v-stepper-step circle that contains/shows the step value.

### Reproduction Link
[https://codepen.io/MatthewAry/pen/qxXmRV](https://codepen.io/MatthewAry/pen/qxXmRV)

**Comment by johnleider** [comment]
This is not a bug, this is a feature request.

**Comment by MatthewAry** [comment]
Woops. Sorry @johnleider

**Comment by Ten-Taken** [comment]
It's almost a bug.  .stepper__step__step class shouldn't have bg-color 'primary' declared with !important.  This makes it difficult to override until the feature is built.

**Comment by buckwheat24** [comment]
:+1:  would love to be able to change the stepper color. Absolutely loving Vuetify! Thanks!

**Comment by vcastro45** [comment]
Is the feature released in v1.0.5 ? Still not work for me

**Comment by KaelWD** [comment]
No https://semver.org/#spec-item-6

**Comment by opelsrx** [comment]
This still won't work for me. I use Vuetify version 1.0.17. Essentially the same example as @MatthewAry . Using prop color does nothing.

**Comment by KaelWD** [comment]
That's because it isn't in 1.0.17
