### ISSUE TITLE
[Bug Report] Multiple empty columns on v-data-table

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#3277]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Visit reproduction link, view Console for error.
For comparison, here's a v-data-table with a single empty header cell (which is error-less): https://codepen.io/cdwyer/pen/EQvmQv

### Expected Behavior
No errors/warning (ie, unique keys).

### Actual Behavior
Vue throws a "duplicate keys" warning: 

"[Vue warn]: Duplicate keys detected: ''. This may cause an update error.

### Reproduction Link
[https://codepen.io/cdwyer/pen/RQZVge](https://codepen.io/cdwyer/pen/RQZVge)

### Other comments
This is only an issue on tables where you have two or more headerless columns. Probably most applicable for avatars, buttons, etc.—any element where the row itself provides context and a header isn't needed. Ideally, either an option to mark a header (in a data-based `headers` object) as `empty`, or just have Vuetify handle the creation of a random/unique key, if the `text` is left empty.

**Comment by johnleider** [comment]
Just don't define text in the headers prop,

https://codepen.io/johnjleider/pen/QQMqeE?editors=1111

**Comment by dwyer14** [comment]
@johnleider oh perfect. Didn't realize that was an option...might be worth mentioning in the docs but regardless, thanks for pointing that out!
