### ISSUE TITLE
[Feature Request] Resizable datatable column widths

### ISSUE THREAD

**Issue by Rleahy22** [vuetifyjs/vuetify#3278]
### New Functionality
Add a prop that lets users resize column widths by clicking and dragging the edge of a header.

### Improvements
Passing a `resize-column-widths` would be a simple addition to any data-table.

### Bugs or Edge Cases it Helps Avoid
Users complaining about column widths they don't like could just resize them.

**Comment by nekosaur** [comment]
I think this might be out of scope for our data-table.

**Comment by blalan05** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
--
 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by kogratte** [comment]
The suggested proposal does not works well, despite what has been told on many tickets. 
1 - Documentation is incorrect, and the user has to deep into source code to find how to use it (not anyone knows how)
2 - This package as issue when combined with sort events
3 - It also has issue when used with expandable rows.

I'll upvote to reopen this issue as column resize really needs to be a first class citizen with data tables.
