### ISSUE TITLE
[Bug Report] <v-tooltip> with <v-btn> not centered in the toolbar

### ISSUE THREAD

**Issue by Failcookie** [vuetifyjs/vuetify#3279]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 10

### Steps to reproduce
Add a tooltip around a button inside a `<v-toolbar>`. You'll notice the icon being pushed the to top in the example.

### Expected Behavior
Icon buttons should be centered in toolbar

### Actual Behavior
Icon buttons are pushed to the top (no center alignment)

### Reproduction Link
[https://codepen.io/anon/pen/WMEELP?&editors=100](https://codepen.io/anon/pen/WMEELP?&editors=100)

**Comment by tance77** [comment]
```css
.tooltip, .tooltip>span{
height: inherit;
}
```
Making it not inherit height seems to fix the problem

**Comment by dawzrd** [comment]
I had this same problem. used same fix.

**Comment by johnleider** [comment]
fixed in becd4843fdd766e4a59ee2dbd99760f18db7d340

**Comment by atilkan** [comment]
@johnleider 
Doesn't look like it fixed on version 1.3.7

**Comment by genez** [comment]
I have the same issue, how to fix it while waiting for an official change?

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
