### ISSUE TITLE
Empty data table shows 1-0 of 0 records

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetify#328]
### Steps to reproduce
Create a data table but don't populate it with anything

### Versions
Vuetify 0.10.3

### What is expected ?
It should probably say 0 of 0 records, or nothing at all?

### What is actually happening ?
It will display '1-0 of 0 records' in the footer

### Reproduction Link
http://codepen.io/anon/pen/OpexJb

**Comment by johnleider** [comment]
PR is up waiting for review.
