### ISSUE TITLE
[Bug Report] Switching routes with page embedded toolbar loses padding

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#3280]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.13.3

### Steps to reproduce
1. Open the provided codesandbox
2. Toggle between the two pages

### Expected Behavior
The page content doesn't move and the padding stays the same.

### Actual Behavior
The page content shifts after the first page load and subsequent navigation change.

### Reproduction Link
[https://codesandbox.io/s/9yq7m32mzp](https://codesandbox.io/s/9yq7m32mzp)

### Other comments
This issue only occurs on beta6 or greater, previous beta versions work as expected.

**Comment by ksankumar** [comment]
Me too facing same issue with beta-6

**Comment by benperiton** [comment]
This is also related to what I was seeing with height being lost when updating a template via HMR. 

This seems to fix it, but I'm not sure it's the best way: https://github.com/vuetifyjs/vuetify/pull/3290

**Comment by mcfarljw** [comment]
I can also confirm that it also happens with HMR and appears to be related. The bug also popped up somewhere specifically between beta-5 and beta-6.

**Comment by KaelWD** [comment]
Fixed by #3295, not sure why this issue wasn't closed automatically.
