### ISSUE TITLE
[Feature Request] V-Select - Property to allow free input

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#3281]
### New Functionality
While there are certain situations where you only want a user to select whats available, there are also situations where the user should only be suggest options and essentially allow free input

### Improvements
Current work around is by watching the search-input property, and injecting the currently written text as a select option. This could streamline this process.

### Bugs or Edge Cases it Helps Avoid
I don't see any bugs that this feature could avoid. purely a quality of life feature.

**Comment by lgullestrup** [comment]
Realized this can be achieved using the 'Tags' prop.

Sorry.

**Comment by na018** [comment]
In the past it was possible to create new items in the v-select field or to choose an existing one.
I need a v-select with no multiple option, but the option to create a single new item as was possible in the past.
**multiple: false** && **tags: true**
**no** Array
