### ISSUE TITLE
[Bug Report] Source code not working on docs (v0.17 tested)

### ISSUE THREAD

**Issue by Craz1k0ek** [vuetifyjs/vuetify#3284]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Safari 11.0.3
**OS:** Mac OS 10.13.3

### Steps to reproduce
Go to the Vuetify site and try to get the source code of examples by pressing 'View source'

### Expected Behavior
Show the source code of the examples

### Actual Behavior
The box expanded, but no source code is given

### Reproduction Link
[Example on cards](https://vuetifyjs.com/releases/0.17/#/components/cards)

### Other comments
Error I get is: `TypeError: undefined is not an object (evaluating 'this.$http.get')`

**Comment by johnleider** [comment]
We are tracking the issue. This is not the repository for documentation bugs though.
