### ISSUE TITLE
[Bug Report] Cannot go to 1.0.0 from old docs (v0.17 tested)

### ISSUE THREAD

**Issue by Craz1k0ek** [vuetifyjs/vuetify#3285]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Safari 11.0.3
**OS:** Mac OS 10.13.3

### Steps to reproduce
In the documentation of version 0.17, I cannot select the docs of v1.0.0 via the version selector. It also still says v.0.17 is the latest.

### Expected Behavior
I would like to have the ability to go to the newer docs and have a list of all versions

### Actual Behavior
Not displaying the newer versions and providing invalid information (wrong latest version)

### Reproduction Link
[Example on docs](https://vuetifyjs.com/releases/0.17/#/components/cards)

**Comment by johnleider** [comment]
This has sort of always been the case with the docs, older versions are compiled after release. This is also not a Vuetify bug.
