### ISSUE TITLE
[Bug Report] Documentation of version 0.17

### ISSUE THREAD

**Issue by titouancreach** [vuetifyjs/vuetify#3286]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chromium 62.0.3202.75
**OS:** Ubuntu undefined

### Steps to reproduce
"View source button" and "search bar" throw in the console and are not working anymore.

### Expected Behavior
View the source, like before.

### Actual Behavior
throw in the console. Cannot see the example source or search for feature.

### Reproduction Link
[https://vuetifyjs.com/releases/0.17/#/components/bottom-navigation](https://vuetifyjs.com/releases/0.17/#/components/bottom-navigation)

**Comment by jacekkarczmarczyk** [comment]
Please file an issue in the vuetifyjs.com repo

**Comment by titouancreach** [comment]
Why not just move it ?
