### ISSUE TITLE
[Feature Request] Support "Select value" property for <select> attributes in v-select 

### ISSUE THREAD

**Issue by Patsky** [vuetifyjs/vuetify#3289]
### New Functionality
Using 3rd party libs that work by adding attributes in `<select>` and probably rely on "select value property"

For example: [Quaderno](https://developers.quaderno.io/article/145-subscription-form) calculates tax on-the-fly on Stripe forms - depending on selected Country
 ```
<select data-quaderno="country">
    <option value="US" selected>United States</option>
    <option value="GB">United Kingdom</option>
 </select>
```
[example of checkout form](https://gist.github.com/polimorfico/f833ac9a5ab30b6bd4dd)

I assume that Quaderno checks [Select value Property](https://www.w3schools.com/jsref/prop_select_value.asp)  and on change gets the value and calculate tax.
However `<v-select>` returns the value of the `input` 

Please see https://codepen.io/patsky/pen/VQMeJW
1. Choose for example Sweden - then tap on "Check value" - you will see Sweden instead of SE
2. tap again on "Check value" - now it's empty despite "Sweden" showing in <v-select>
3. Type anything like "qweqwe" in the select form -  and tap on "Check Value" (without tapping anywhere else) - you will see "qweqwe" as value

### Improvements
there will be no need to create workarouds... 
One idea for workaround now (not tested - but suggested by Jacek on Discord) is to
_"workaround it by adding hidden select and set its value to the value of v-select model"_

### Bugs or Edge Cases it Helps Avoid
cases where people rely on `<select>` attributes or on getting values using `document.getElementById("mySelect").value = "someValue";`
Anything else?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement.
