### ISSUE TITLE
[Feature Request] Cannot override colors.styl

### ISSUE THREAD

**Issue by markballenger** [vuetifyjs/vuetify#3291]
### New Functionality
override colors.styl

Pretty sure we just need to remove the require here.... colors is already required via app.styl so this seems unnecessary anyway, preventing the override. 
https://github.com/vuetifyjs/vuetify/blob/becd4843fdd766e4a59ee2dbd99760f18db7d340/src/stylus/settings/_theme.styl#L1

### Improvements
Documentation already supports it with the instructions provided here. Today, these instructions do not work for overriding color values of theme

### Bugs or Edge Cases it Helps Avoid
ugly work arounds

**Comment by fnoop** [comment]
https://github.com/vuetifyjs/vuetify/issues/2155 implies we should be able to override colours, but I can't work out how..

**Comment by fnoop** [comment]
Oh actually it's not too difficult.  Create a main.styl and add something like:
```
$colors = {
  "newtest": {
    "base":       #009800,
    ...
  }
}
@import '~vuetify/src/stylus/main'
```

**Comment by johnleider** [comment]
That is correct.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by markballenger** [comment]
This suggestion does not work.

"vue": "^2.4.2",

"vuetify": "^0.17.2",

**Comment by johnleider** [comment]
Please do not comment on closed issues. If you are experiencing a problem, please create a new issue.
