### ISSUE TITLE
[Bug Report] Async select field, value can not be deleted 

### ISSUE THREAD

**Issue by flaver12** [vuetifyjs/vuetify#3292]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a select box, like in this example: https://vuetifyjs.com/en/components/selects#example-asynchronous

1. Remove the prop multiple
2. Remove the prop chips

Than enter a world, select something and click outside of the field.
Than try to delete the input, in the select field.

### Expected Behavior
Content gets removed.

### Actual Behavior
Content, is removed. But if you than click outside of the select box it comes back.

### Reproduction Link
[https://codepen.io/anon/pen/KQXedY?&editors=101](https://codepen.io/anon/pen/KQXedY?&editors=101)

**Comment by KaelWD** [comment]
Not a bug, use `clearable` or `combobox` if you want to be able to clear the selection.
