### ISSUE TITLE
[Bug Report] Snackbar Appearing Behind Toolbar In Documentation

### ISSUE THREAD

**Issue by tance77** [vuetifyjs/vuetify#3296]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
I couldn't replicate the issue in my own Vue application. 

If you you use the show snackbar button https://vuetifyjs.com/en/components/snackbars It will show the snackbar behind the top toolbar.

### Expected Behavior
The snackbar to be above the toolbar

### Actual Behavior
The snackbar is behind the toolbar

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

### Other comments
The reproduction link is just the sample code from the documentation.

**Comment by johnleider** [comment]
I believe this has already been reported, and if not, should be done on the documentation repo. https://github.com/vuetifyjs/vuetifyjs.com
