### ISSUE TITLE
[Feature Request] [Question] Can tabs be used as anchor links and disable the animation?

### ISSUE THREAD

**Issue by ryanmortier** [vuetifyjs/vuetify#3297]
### New Functionality
I want to be able to use tabs as basic anchors rather than switching content with javascript and animations.

### Improvements
Not aware of current workarounds.

### Bugs or Edge Cases it Helps Avoid
It will allow you to build a basic application and still want to use traditional behaviour of tabs without the modern javascript switching content/style/animations.

**Comment by ryanmortier** [comment]
Essentially I want to use tabs like GitHub tabs:

![image](https://user-images.githubusercontent.com/2053960/36276510-33bc9662-125c-11e8-9981-47d04130ae79.png)

**Comment by johnleider** [comment]
You can already do this, simply use the **href** prop instead of **to**. Tabs do not have to be connected to explicit content.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
