### ISSUE TITLE
[Bug Report] v-radio-group shows validation error when v-model is attributed programatically

### ISSUE THREAD

**Issue by leonardo-sj** [vuetifyjs/vuetify#3299]
### Versions and Environment
**Vuetify:** 0.17.7
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.3

### Steps to reproduce
Click in the reproduction link, just wait three seconds and the value of Radio Group's v-model will be attributed programatically.
So, the v-radio will be checked, but then it will show a validation error.

### Expected Behavior
Since, an option is marked, there shouldn't be errors.

### Actual Behavior
It shows validation error even when an option is checked.

### Reproduction Link
[https://codepen.io/anon/pen/padpqO](https://codepen.io/anon/pen/padpqO)

### Other comments
It can be mitigated using the following approach: https://codepen.io/anon/pen/NywyGB

**Comment by denmasyarikin** [comment]
any solution for this bug?

**Comment by johnleider** [comment]
This has been resolved on v1.1
