### ISSUE TITLE
Text input clears on blur

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#33]
I'm not sure if this is intended or not, but if a `v-text-input` doesn't have the `v-model` set, the typed text is cleared as soon as the focus leaves the input.

I can't imagine a scenario where you wouldn't bind the input value to data, but it sure feels odd that it behaves like this.

If it's intended, might be good to document it.

**Comment by johnleider** [comment]
This is not intended.

**Comment by johnleider** [comment]
Fixed with 744fe9d3cec80ea6b3a8b46f9cd0e8bc1df72857.
