### ISSUE TITLE
Importing single component

### ISSUE THREAD

**Issue by rzb** [vuetifyjs/vuetify#330]
How do I go about importing a single component, including its specific styles? I'm using webpack.

**Comment by johnleider** [comment]
This is not supported by default.

**Comment by faforty** [comment]
@johnleider it's very very bad. I'm very dispirit...

**Comment by johnleider** [comment]
This is functionality that we are working on for 0.14.

**Comment by smxsm** [comment]
Looks like this wasn't included in 0.14. ... Any further release plans yet?

**Comment by nekosaur** [comment]
Supporting modular components is something that will require large changes to the code base. There is currently no time table for it, but we are working on it.

**Comment by johnleider** [comment]
Vue 2.4 kind of accelerated 0.14 unfortunately.

**Comment by smxsm** [comment]
Ok, thanks for the info :) no worries, I figured that would take a while ;)

**Comment by Tugsbayar** [comment]
It's still not working.. :( . I need this feature.

**Comment by smxsm** [comment]
It is working now, check https://vuetifyjs.com/vuetify/a-la-carte

**Comment by johnleider** [comment]
It is also being updated/improved for 0.16. Release date October 4th.

**Comment by Tugsbayar** [comment]
Very good news!

**Comment by codewp** [comment]
@johnleider How to use it in an existing project?

**Comment by nekosaur** [comment]
Please do not comment on old and closed issues. If you need help please visit us at https://chat.vuetifyjs.com

**Comment by summerinsect** [comment]
https://vuetifyjs.com/vuetify/a-la-carte this page is 404
so，how to importing a single component？

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/guides/a-la-carte
