### ISSUE TITLE
[Feature Request] Auto grow text fields on load

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#3300]
### New Functionality
When text fields are loaded with preloaded content that overflows. The text area is not auto-grown and you have to scroll or manually trigger it to auto-grow.

### Improvements
 I currently have it so that it adds whitespace and removes it at the end to manually trigger it when they click on the field.

### Bugs or Edge Cases it Helps Avoid
No bugs.

**Comment by jaesung2061** [comment]
Let me try upgrading to 1.0 and see if that fixes it.

**Comment by jaesung2061** [comment]
@johnleider figured it out. It happens when inside an expansion panel.

Reproduction: https://codepen.io/jaesung2061/pen/KQoLxR

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/pull/4238 if you use `lazy` prop on expansion panel

**Comment by junwan01** [comment]
Hi, this problem seems to come back in the 1.2.2 release. the text area does not auto-grow when preloaded with text that overflow, the textarea is inside an expansion panel.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/YOEVKw
