### ISSUE TITLE
[Bug Report] Select menu should expand to the top if not enough space on screen

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#3303]
### Versions and Environment
**Vuetify:** 1.5.18
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132, Google Chrome
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the day menu in the bottom sheet and see the content overflowing out of the document.

### Expected Behavior
Menu should open to the top if not enough room below the select input.

### Actual Behavior
Menu opens to the bottom out of the view port of the document.

### Reproduction Link
[https://codepen.io/s3rh11/pen/xxKavdj](https://codepen.io/s3rh11/pen/xxKavdj)

**Comment by KaelWD** [comment]
It usually does, but I guess not when it's attached.

**Comment by mseele** [comment]
It does not work when the V-Select has attach="true". Does anyone have a workaround for that issue?

Is it possible to override calcTop() of menuable.js to calculate at our own as workaround?

**Comment by AuspeXeu** [comment]
It seems like the reproduction link is not working anymore.

**Comment by S3RH11** [comment]
Hello, @AuspeXeu 
I watched that issue because I need that fix.
Please see the fixed reproduction link: https://codepen.io/s3rh11/pen/xxKavdj

**Comment by AuspeXeu** [comment]
Fixed reproduction link

**Comment by mseele** [comment]
Same problem when you use a date picker inside a menu (https://vuetifyjs.com/en/components/date-pickers#date-pickers-in-dialog-and-menu) and give menu attach="true"

**Comment by flyingL123** [comment]
Here's a similar reproduction link with a few examples.

https://codepen.io/flyingl123/pen/mdPewOY

I can't figure out how to get this working properly.

**Comment by mseele** [comment]
@flyingL123 Sorry for the late reply. My workaorund is an own component:

```
// workaround for https://github.com/vuetifyjs/vuetify/issues/3303
<script>
import VAutocomplete from 'vuetify/lib/components/VAutocomplete/VAutocomplete'

export default {
  name: 'GAutocomplete',
  extends: VAutocomplete,
  methods: {
    // workaround https://github.com/vuetifyjs/vuetify/pull/10158
    onClick() {
      if (this.isDisabled) return

      this.selectedIndex > -1 ? (this.selectedIndex = -1) : this.onFocus()

      this.activateMenu()
    },
    activateMenu() {
      if (this.disabled || this.readonly || this.isMenuActive) return
      if (this.attach) {
        const content = document.querySelector('.content')
        if (content != null) {
          const contentRect = content.getBoundingClientRect()
          const elemRect = this.$el.getBoundingClientRect()
          const contentHeight = contentRect.top + contentRect.height
          this.menuProps.top = contentHeight - elemRect.top < 175
        }
      }
      this.isMenuActive = true
    },
  },
}
</script>

```
