### ISSUE TITLE
[Feature Request] Allowing to choose style of fontawesome 5 icons (solid, regular)

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3304]
### New Functionality
Fontawesome 5 icons has 2 styles to choose from: **solid and regular**
It would be nice if you could choose which style is used for fa- icons in the `<v-icon>` component. 

### Improvements
Visual

**Comment by nekosaur** [comment]
This should already be possible. Use `far fa-check` for regular and `fal fa-check` for light.

**Comment by AlexSHoffman** [comment]
@nekosaur thanks, good to know. It doesn't

**Comment by AlexSHoffman** [comment]
@nekosaur thanks, good to know. 
It doesn't work when you import it as `<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">`

Is there a better way to import it in a Electron-Vue project?

**Comment by AlexSHoffman** [comment]
@nekosaur I'm using Vuetify's Electron boilerplate. Is it already included in it?

**Comment by nekosaur** [comment]
Be aware that regular and light versions of fa5 icons are only available in the Pro license. The electron template does not include font awesome by default as far as I know.

**Comment by AlexSHoffman** [comment]
@nekosaur thanks for the info.
