### ISSUE TITLE
[Feature Request] More examples for <v-data-iterator>

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3308]
### New Functionality
`<v-data-iterator>` is a complex component. Could you please create more examples showing how to use all the props it has? 

For instance, an example showing how to add sorting, custom-filters, etc.

### Improvements
It would help new developers to understand how it works and allow them to use the component to its full potential.

### Bugs or Edge Cases it Helps Avoid
None

**Comment by johnleider** [comment]
Can you please re-post this to the documentation please. https://github.com/vuetifyjs/vuetifyjs.com

**Comment by stemid** [comment]
@johnleider where is the current documentation? I can't find the repo for it. I'm also after a better example of using filter with v-data-iterator.

**Comment by MajesticPotatoe** [comment]
Docs are now a part of the [Main Repo](https://github.com/vuetifyjs/vuetify). and can be viewed at [vuetifyjs.com](https://vuetifyjs.com). This particular component will be much better updated in 2.0 release.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
