### ISSUE TITLE
[Bug Report] V-Toolbar extension-height not applied

### ISSUE THREAD

**Issue by ndamjan** [vuetifyjs/vuetify#3310]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Safari 11.0.3, Google Chrome
**OS:** Mac OS 10.13.3

### Steps to reproduce
- Set extension-height="100" on v-toolbar
- Set height="100" on v-tabs

### Expected Behavior
The height of the extension is increased to accommodate the larger tabs

### Actual Behavior
Extension height remains at 48px

### Reproduction Link
[https://codepen.io/ndamjan/pen/EQoZOo](https://codepen.io/ndamjan/pen/EQoZOo)

### Other comments
Workaround: overriding CSS for toolbar__extension class like below

.toolbar__extension {
  height: 100px!important;
}

**Comment by KaelWD** [comment]
`<v-toolbar tabs` just applies `<v-toolbar extension-height="48"`, so it works if you remove that: https://codepen.io/anon/pen/LQQWNJ

**Comment by ndamjan** [comment]
Thank you!
