### ISSUE TITLE
[Bug Report] Select with overflow enabled breaks in dense toolbar

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#3312]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132, Google Chrome
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the select menu.

### Expected Behavior
Render the select and its menu correctly.

### Actual Behavior
The select is not displayed correctly when closed. But also when opened, the checkboxes are rendered wrong.

### Reproduction Link
[https://codepen.io/anon/pen/PQEjXM](https://codepen.io/anon/pen/PQEjXM)

**Comment by johnleider** [comment]
This is because overflow, editable and segmented selects have a defined height to match the proper design from spec. You will have to write custom-css to achieve what you are looking for.

**Comment by AuspeXeu** [comment]
Even without the dense option, the checkboxes look weird tho.
