### ISSUE TITLE
Option to  disable touch slide in v-tabs

### ISSUE THREAD

**Issue by marijnhurkens** [vuetifyjs/vuetify#3315]
### New Functionality
I have slider inputs in the content of my tabs and this interferes with the slide functionality on the tabs itself. This way we see a lot of accidental tab switching. Being able to disable the touch slide on v-tabs would help.

### Improvements
I have no current workarounds.

### Bugs or Edge Cases it Helps Avoid
Accidental tab switching when using slider inputs in tab content.

**Comment by KaelWD** [comment]
Duplicate of #2335

**Comment by nkprince007** [comment]
It has been marked as a duplicate and #2335 has a been closed. But, this issue still appears.
