### ISSUE TITLE
[Bug Report] form.reset() doesn't only reset validation, it also clears the inputs

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#3316]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
call this.$refs.form.reset()

### Expected Behavior
As the docs says, reset() will 

> Resets validation for all inputs

so it should only resetting the validation state, not the inputs

### Actual Behavior
Will also clear the inputs

### Other comments
Please add another function to v-form "resetValidation()" to only reset the validationState and don't reset the inputs

**Comment by BennyAlex** [comment]
@nekosaur @johnleider 
v-form will now render a form-tag, which breaks some things. E.g when pressing enter inside a text-field, the site will reload

**Comment by nekosaur** [comment]
`v-form` has always rendered a form tag? and pressing enter on a single text input in a form should trigger submit, this is normal browser behaviour.

**Comment by BennyAlex** [comment]
So how to disable the submit? I still want to use the v-form features like validate...
In my opinion it should not always render a <form>.

**Comment by nekosaur** [comment]
You can do something like

```
<v-form @submit.prevent>
</v-form>
```

**Comment by BennyAlex** [comment]
This isn't working at all.
I could swear it worked a few weeks ago.

**Comment by BennyAlex** [comment]
The funny thing is, when I use the same code in codepen, then it works...


This is what I have
```
<v-form @submit.prevent="save">
	<v-card-text>
	  <v-container>
		<v-text-field
		  v-model="businessCopy.name"
		  label="Name"
		  required
		  autofocus
		  clearable
		/>
	  </v-container>
	</v-card-text>
	<v-card-actions>
	  <v-btn flat @click="dialog=undefined">Cancel</v-btn>
	  <v-spacer/>
	  <v-btn
		color="accent"
		flat
		@click="save"
	  >
		Speichern
	  </v-btn>
	</v-card-actions>
</v-form>
```

**Comment by BennyAlex** [comment]
Thanks. What's with the method to only reset validation state?

**Comment by nekosaur** [comment]
In 1.1 `reset()` will only reset validation, not input

**Comment by KaelWD** [comment]
Will it? That sounds like a breaking change to me.

**Comment by BennyAlex** [comment]
It would be better to add `resetValidation() ` and keep `reset()`

**Comment by johnleider** [comment]
My initial thought was the just that @BennyAlex . Have a resetValidation and resetForm, with reset calling both. This would maintain backwards compat but allow more flexibility.

**Comment by ecmel** [comment]
As all we are using vue for form binding resetting form state should be done in the model IMHO

**Comment by johnleider** [comment]
That would cause breaking changes as the model currently functions as the valid state of the form.

**Comment by ecmel** [comment]
I mean resetting fotm should only reset validation state, for resetting form fields actual user defined vue model should be used (source of truth) which is up to the programmer

**Comment by johnleider** [comment]
This can be something we visit for v2.0.

**Comment by BennyAlex** [comment]
@ecmel if we have a resetValidation the programmer can reset the model by himself

**Comment by mustafaekim** [comment]
can someone clarify if this feature has been implemented or to be implemented? Because in my case, I use vuetify 1.2.4 and resetting form does not clear validations. Here is my code:

```ts
    resetForm() {
      this.form.type = "equal";
      this.form.test = "";
      this.form.score = 0;

      var form: any = this.$refs.evaluatorForm;
      form.reset()
    },
```

once resetForm() is called, the user is confronted with validation errors which is not what I expect. I just want to go to the initial state. How do you handle this case?

**Comment by KaelWD** [comment]
#4763

**Comment by zweeen** [comment]
Thanks guys for this awesome framework. You are doing a very good work :D

`resetValidation` work fine.

But there is not reference to it in form API. The available function as the docs says are only `reset` and `validate`

**Comment by binbinyo** [comment]
I am not sure if anyone still curious but here is my finding.
Analysis: it's because when the data return from the server, the v-bind data is linked to the form, so whenever you reset the form, the data binded will be removed too.

Solution: You need to unlinked with the return data from server, Try and use javascript clone object function, to create a new object, then use the cloned object as a new data source then you are free to reset the form.( which ultimately reset the form and  server return linked data )

**Comment by brokenthorn** [comment]
Weirdly enough, for me, calling `reset` clears the form and its errors, but also makes calling `validate` behave differently. Before calling `reset`, calling `validate` on an empty form will cause all invalid fields to be highlighted. After calling `reset`, calling `validate` again will cause ONLY THE FIRST field to be highlighted and only by fixing the error cause will the next field be validate, but only after calling `validate` again.

**Comment by kunalahirrao** [comment]
It means user has to reset field by setting defaultValue=''

**Comment by kunalahirrao** [comment]
No use of resetForm method
