### ISSUE TITLE
[Bug Report] v-text-field does not catch Chromium autofill

### ISSUE THREAD

**Issue by parzh** [vuetifyjs/vuetify#3317]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- Open the repro in any Chromium browser, e. g. Google Chrome
- Input an arbitrary email and password
- Allow browser to save the input
- Relaunch the fiddle (i.e. change the source code)
- Use arrow keys to select suggested email, do **not** press enter yet
- Remove focus from the email field (i.e. press <kbd>Esc</kbd> or click outside the card)

### Expected Behavior
Label of the password field styled in a way that corresponds to filled field

### Actual Behavior
Label of the password field styled in a way that does not correspond to filled field

### Reproduction Link
[https://codepen.io/anon/pen/ddJKdO?editors=1010](https://codepen.io/anon/pen/ddJKdO?editors=1010)

**Comment by parzh** [comment]
If it is a `wontfix`, is there any sort of workaround? I'm struggling to find this.

**Comment by KaelWD** [comment]
This has come up before, and it seems to be a problem with chrome. Even google's own sites don't respond to autofill properly. There are some [dirty hacks](https://stackoverflow.com/a/41530164/2074736) available, but I don't think we should be implementing them.
