### ISSUE TITLE
[Bug Report] Footer doesn't clipped or unclipped

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#3321]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
https://codepen.io/donpuerto/pen/EQoJYQ?editors=1010
![image](https://user-images.githubusercontent.com/9329005/36351044-6245ea9a-14de-11e8-8580-e125287b2e04.png)
![image](https://user-images.githubusercontent.com/9329005/36351040-460f1874-14de-11e8-9a1c-52df42ef8028.png)

### Expected Behavior
it will clip or unclipped

### Actual Behavior
none

### Reproduction Link
none

### Other comments
none

**Comment by KaelWD** [comment]
You should use `inset` if you want it to be next to the drawer.

@nekosaur Also `fixed` is automatically applied with `app`, that's intentional.

**Comment by nekosaur** [comment]
Well there you go. Could do with being documented.

**Comment by KaelWD** [comment]
Maybe not for footers though, only really makes sense to have it for toolbars and drawers.
