### ISSUE TITLE
[Feature Request] Make v-list-tile active if matches href matches current url OR add a property to manually set it to active

### ISSUE THREAD

**Issue by freakazoid707** [vuetifyjs/vuetify#3325]
### New Functionality
It will allow me to set the active state manually or automatically if it matches the current url. This helps if used in a multi-page app, where vue-router is not present or used at all.

### Improvements
As of now, I have not been able to find any workaround. I tried adding the necessary active class manually, but doesn't work well if it's inside a v-list-group. I saw [this issue](https://github.com/vuetifyjs/vuetify/issues/3311) but was closed.

### Bugs or Edge Cases it Helps Avoid
Not sure about bugs. For edge cases, I guess we can set v-list-tile as active when used in multi-page app.

**Comment by freakazoid707** [comment]
Decided to check how the active thing works. I can manually set it active by assigning v-model to the v-list-tile.

**Comment by johnleider** [comment]
Glad you found the property :)
