### ISSUE TITLE
[Bug Report] Footer auto height not reacting to changes

### ISSUE THREAD

**Issue by rikte88** [vuetifyjs/vuetify#3326]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Fedora undefined

### Steps to reproduce
Go to repr link, follow rendered instructions.

### Expected Behavior
When footer height changes, it alters the content margin-bottom accordingly.

### Actual Behavior
It does compute the hight on first render, but fails to observe height changes.

### Reproduction Link
[https://codepen.io/anon/pen/zRRqvb](https://codepen.io/anon/pen/zRRqvb)

### Other comments
Love your work, would be nice to get rid of my hack :)

**Comment by KaelWD** [comment]
This isn't really something we can do automatically without adversely affecting performance, you'll have to handle it on a case-by-case basis: https://codepen.io/anon/pen/JppRYZ
