### ISSUE TITLE
[Bug Report] v-tooltip causes the visualization to freeze

### ISSUE THREAD

**Issue by mclaran** [vuetifyjs/vuetify#3328]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.0
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 7

### Steps to reproduce
https://codepen.io/anon/pen/mXXwjz

### Expected Behavior
No delay while scrolling, No additional render for "v-tooltip"

### Actual Behavior
is each element using "v-tooltip", is being rendered in another element. This causes the visualization to freeze. If I remove all the "v-tooltip" from the markup, everything works smoothly.
https://user-images.githubusercontent.com/22270702/36366078-0f0f12f6-157f-11e8-8d1f-3f62994c73d6.png

### Reproduction Link
[https://codepen.io/anon/pen/mXXwjz](https://codepen.io/anon/pen/mXXwjz)

**Comment by johnleider** [comment]
I'm not sure if this is something we can get around, that is a lot of dynamically rendered tooltips. Thoughts @KaelWD ?

**Comment by mclaran** [comment]
I noticed such a feature that it occurs in all components using "slot='activator'". This checked for v-menu, dialog, v-tooltip

**Comment by KaelWD** [comment]
`lazy` is supposed to help with that, but doesn't seem to actually do anything for some reason.

**Comment by dmecke** [comment]
Maybe I am completely wrong, but... The `mounted` method of `src/mixins/detachable.js` reads `!this.lazy && this.initDetach()`. But when I look into the very same file in my projects `node_modules` directory (I am using `1.0.17`) or in the very same file of the source zip download of `1.0.17`, the line reads `this.initDetach()`. It seems that the bugfix #3593 somehow hasn't made it to the build!?

**Comment by KaelWD** [comment]
It'll be in 1.1 then, idk why that PR wasn't made to master. I'll have to check if that fixes this too.

**Comment by KaelWD** [comment]
Confirmed fixed by #3593 if you add `lazy` to the tooltips. That pen will still have terrible scrolling performance though unless you add `backface-visibility: hidden` to the scroll container.
