### ISSUE TITLE
[Bug Report] Wrapping steps in custom components does not work

### ISSUE THREAD

**Issue by sebastianbarfurth** [vuetifyjs/vuetify#3330]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
1. Create a stepper
2. Wrap a step in a custom component
3. Place component inside stepper

### Expected Behavior
The step should work as intended.

### Actual Behavior
The step shows up, but active step detection is broken and the step stays inactive.

### Reproduction Link
[https://codepen.io/anon/pen/gvvGzx?editors=1010#0](https://codepen.io/anon/pen/gvvGzx?editors=1010#0)

### Other comments
This also continues to happen if you only wrap the step's content, then the step shows active but the content remains hidden (display: none). It seems the stepper can't recognize the steps if they're inside a component.

The ability to wrap steps is crucial for complex steppers, otherwise files get way too crowded.

**Comment by johnleider** [comment]
This is another component that needs to be converted to use the registrable mixin.

**Comment by shantungbandits** [comment]
i came accross the same issue.no clue

**Comment by pinicius** [comment]
Same issue :(

**Comment by sindrepm** [comment]
Agree, it would be great if this could be fixed so steps can be composed into separate components.

**Comment by johnleider** [comment]
Hey guys, I'm going to tag this for v1.2 as v1.1's ship has sailed. Definitely tracking this and want to improve it.

**Comment by roger-russel** [comment]
I made this litle hack https://codepen.io/anon/pen/dKLqNj?editors=1111 I know that is not the best solution but it works at least.

**Comment by johnleider** [comment]
Here is an update on this request. The corresponding functionality has been abstracted into `v-item-group` and `v-window`. Unfortunately I have been able to convert it over without breaking changes.

What we _can_ do for this is at least move stepper to use the **registrable** mixin which will alleviate these issues.

I'll look to have this in before beta.

**Comment by johnleider** [comment]
Closed via f7b17e7

**Comment by CameronMcNair** [comment]
This appears to have broken non linear steppers. "this.getSteps is not a function" is thrown when you click a step
