### ISSUE TITLE
[Bug Report] DataTable headers get a light blue square around them when selected

### ISSUE THREAD

**Issue by cynicalsubject** [vuetifyjs/vuetify#3331]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
The codepen provided is just a direct copy of the Vuetify documents for DataTables.

Simply click any of the headers.

### Expected Behavior
To see no square around the headers when they are selected.

### Actual Behavior
You get a blue square around the headers when they're clicked.

### Reproduction Link
[https://codepen.io/anon/pen/QQQmeb?&editors=101](https://codepen.io/anon/pen/QQQmeb?&editors=101)

### Other comments
Almost every DataTables example has this behaviour, with the exception of those using a <template> tag to create the headers (using <th> tags).

So far I've tested this with Chrome (63.0.3239.132) and Firefox (58.0.2). Firefox doesn't seem to have this problem.

**Comment by johnleider** [comment]
This seems like a great issue for @Phlow2001 🥇

**Comment by julkuh** [comment]
This can be simply solved by integrating the following style to 'src/stylus/components/_data-table.styl'

`.datatable th[role="columnheader"]:focus{
  outline: none
}`

Sample:
https://codepen.io/anon/pen/YeLqVK
