### ISSUE TITLE
[Bug Report] Incorrect alignment of selection controls on right side of list

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3336]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Create a list and add selection controls (checkbox or switch) to right side using `v-list-tile-action` component.

### Expected Behavior
Selection controls are aligned to right margin on list, like in Material design guidelines example.
![Material design settings](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B1PhAWhtrRTrUXhhTFotZkwteEk/settings-switch1.png)

### Actual Behavior
Selection controls does not align to right margin, some controls are too close to the right side.

### Reproduction Link
[https://codepen.io/anon/pen/ZrrPXG?editors=1010](https://codepen.io/anon/pen/ZrrPXG?editors=1010)

**Comment by KaelWD** [comment]
The switch bounding box is too small, so part of it ends up outside the parent element:
![chrome_2018-02-20_11-16-20](https://user-images.githubusercontent.com/16421948/36402018-91ea7ad4-162f-11e8-8006-bd01ead73e82.png)

**Comment by scp-nm** [comment]
Watching this as I have the same issue, here's another example:

https://codepen.io/scp-nm/pen/VXejGz/

System info:
Vuetify: 1.0.7
Vue: 2.5.14
Browsers: Chrome 64.0.3282.186
OS: Mac OS 10.13.3

**Comment by nekosaur** [comment]
Fixed in 1.1 https://codepen.io/anon/pen/YvmWMN
