### ISSUE TITLE
[Bug Report] Safari slider track not repainting

### ISSUE THREAD

**Issue by rikte88** [vuetifyjs/vuetify#3339]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
Open repr link in safari, click button, observe issue.
Safari version: 11.0.2 (12604.4.71.6) from 2017. Unfortunately I cannot easily update my mac due to icloud password loss. Someone please verify :)

### Expected Behavior
The slider track blue and grey parts update.

### Actual Behavior
The thumb moves, but the blue and grey slideer tracks do not.

### Reproduction Link
[https://codepen.io/anon/pen/VQQoBN](https://codepen.io/anon/pen/VQQoBN)

### Other comments
Works in all other desktop/mobile browsers tested. Only safari desktop affected.

**Comment by chewy94** [comment]
I have tested on Safari 11.0.3 (13604.5.6) and cannot reproduce via the codepen above. Anyone else happen to have @rikte88's  version?

**Comment by rikte88** [comment]
Excellent. Closing :)
