### ISSUE TITLE
[Feature Request] Allow different TAB-Key behaviour in V-Select

### ISSUE THREAD

**Issue by WebsiteDeveloper** [vuetifyjs/vuetify#3341]
### New Functionality
Tab through a form as if it would contain a native html select

### Improvements
Currently, when the select list opened, the tab key acts like enter key, it switches the element's selected state. The native html select closes the dropdown on first TAB and switches to the next form element by the next TAB press -> I have yet to find a workaround for this

### Bugs or Edge Cases it Helps Avoid
-

**Comment by bad4iz** [comment]
[a similar problem](https://github.com/vuetifyjs/vuetify/issues/3341)

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by michelle-morin** [comment]
Is there a workaround for this? I would also like to use v-combobox in the same manner as v-autocomplete, allowing a user to tab through input fields in a form and select an item from the v-combobox's dropdown list using the tab key.
