### ISSUE TITLE
[Bug Report] Time-picker providing NaN and Timestamp values after migration from 0.17 to 1.0.1

### ISSUE THREAD

**Issue by iec989** [vuetifyjs/vuetify#3342]
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 66.0.3350.0
**OS:** Windows 10

### Steps to reproduce
https://imgur.com/a/xad3e

I can't reproduce it within your demo, but please, check the image above.

It was working perfectly fine until I've upgraded it.

The datepicker is pretty standard: https://imgur.com/a/9NQZ3

### Expected Behavior
The datepicker to be displayed like in the demo

### Actual Behavior
It shows timestamps and NaN values

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

**Comment by jacekkarczmarczyk** [comment]
Please provide a reproduction in codepen/jsfiddle/...

**Comment by iec989** [comment]
I didn't update vuetify's css file lol

I'm now using the `import 'vuetify/dist/vuetify.min.css'` to avoid future issues
