### ISSUE TITLE
[Bug Report] v-edit-dialog ignores 'rules'

### ISSUE THREAD

**Issue by emrdev** [vuetifyjs/vuetify#3344]
### Versions and Environment
**Vuetify:** 1.0.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Click a cell to show the inline editor.

Enter more chars than rule allows (25).

Hit enter or click anywhere.

### Expected Behavior
Rule violation causes underlying value not to update when editor is closed.

### Actual Behavior
Underlying value is updated.

### Reproduction Link
[https://codepen.io/anon/pen/PQRBrx](https://codepen.io/anon/pen/PQRBrx)

### Other comments
I had assumed the :rules would act as a gate to prevent bad input?

(Codepen is taken from stock v-edit-dialog example pen)

**Comment by johnleider** [comment]
@jacekkarczmarczyk any insight?

**Comment by jacekkarczmarczyk** [comment]
I'd get rid of `v-edit-dialog` component in the first place (afair we've discussed it with The Kael), but that's definitely not something for 1.0.*.
Checking errors before saving seems to be the right solution

**Comment by zfmaster** [comment]
Is there any workaround for that? There is even no possibility to add custom listener to prevent save.

**Comment by ayZagen** [comment]
+1

**Comment by jacekkarczmarczyk** [comment]
PRs are always welcome :)

**Comment by ayZagen** [comment]
@oxi049 no worries, i just need a little spare time.

**Comment by johnleider** [comment]
This component is being removed for v3. We haven't nailed down the exact replacement functionality but there will be an upgrade path.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
