### ISSUE TITLE
[Bug Report] Margin-botton on p tag

### ISSUE THREAD

**Issue by kyrillos52** [vuetifyjs/vuetify#3345]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
Open the page

### Expected Behavior
margin-bottom:16px should not be applied on p tag. To have a more restrictive CSS selector.

### Actual Behavior
margin-bottom:16px is applied on every p tag

### Reproduction Link
[https://codepen.io/anon/pen/ddmqmg?&editors=101](https://codepen.io/anon/pen/ddmqmg?&editors=101)

### Other comments
On my point of view, the CSS specific on a component should not be applied on a HTML tag because it can break an application style. Could it be possible to avoid to have that ?

**Comment by johnleider** [comment]
This has been in the framework since release, https://github.com/vuetifyjs/vuetify/blame/98354705d43538782afde4fd9b4442848add5726/src/stylus/elements/_typography.styl and is not something we are looking to change at this time. Thank you for the report.
