### ISSUE TITLE
[Bug Report] Only one error message displayed

### ISSUE THREAD

**Issue by b0g3r** [vuetifyjs/vuetify#3346]
### Versions and Environment
**Vuetify:** 1.0.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
add to error-messages two or more strings

### Expected Behavior
two errors

### Actual Behavior
only first error string

### Reproduction Link
[https://codepen.io/b0g3r/pen/jZzePw?page=1&](https://codepen.io/b0g3r/pen/jZzePw?page=1&)

### Other comments
Only one error string displayed in all input components (as text-field or select).
In es5/mixins/input.js:96 -> `messages = [this.genError(this.validations[0])];`

**Comment by johnleider** [comment]
This is not a bug, but part of Material Design spec.

**Comment by b0g3r** [comment]
@johnleider why error-messages is Array if spec allows only one error?

**Comment by johnleider** [comment]
Because an input can have multiple errors and will change to the next in order once they are resolved.
