### ISSUE TITLE
[Bug Report] Bulletpoint rendered by v-list shenanigans

### ISSUE THREAD

**Issue by kdlslyv** [vuetifyjs/vuetify#3348]
### Versions and Environment
**Vuetify:** 1.0.2
**Vue:** 2.5.13
**Browsers:** Firefox 58.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
* Press on the details v-list-group
* See a little bulletpoint appear on the left

### Expected Behavior
I suppose it'd look better without the bulletpoint

### Actual Behavior
Automatic ul bulletpoints feature

### Reproduction Link
[https://codepen.io/anon/pen/PQRMxY](https://codepen.io/anon/pen/PQRMxY)

### Other comments
* It only occurs when used in conjunction with v-layout

PS:
This is my first bug-report done in this manner, I apologize in advance :D
Vuetify is a great framework, starting using it at v0.15.3. I admire the work put into it.

**Comment by johnleider** [comment]
We need to convert `v-list` from a `ul` to a series of `div`s

**Comment by KaelWD** [comment]
Fixed by #3473
