### ISSUE TITLE
[Feature Request] Disable Theming Options

### ISSUE THREAD

**Issue by sbosell** [vuetifyjs/vuetify#3349]
### New Functionality
Integrating vuetify into a current project can cause issues with the way vuetify injects styling into the head.  We need a way to disable (or class/wrap it) the theming so full custom or existing themes don't have conflicts.  

Referring to these: https://www.dropbox.com/s/h7017iwwb5u2k25/2018-02-20_17-56-03.png?dl=0

### Improvements
I'm not sure there is a workaround except trying to override the styles.   We can currently do this as a workaround:

```
Vue.use(Vuetify, {
	options: {
	  themeCache: {
		get: () => ''
	  }
	}
  });
```

The workaround won't work if vue is included via a cdn as the Vue.use is automatically called by vuetify so this work may also require the ability to disable or change how the Vue.use(Vuetify) is called when using a cdn.

### Bugs or Edge Cases it Helps Avoid
The injected head styles cause conflicts with existing sites.

**Comment by KaelWD** [comment]
So my first thought was to allow the theme option to take a boolean:
```js
Vue.use(Vuetify, { theme: false })
```
But if that's going to cause issues with CDN users maybe we need to revisit the installation process again.
