### ISSUE TITLE
[Feature Request] Add a `freeze` prop to the `<v-expansion-panel>` component

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuetifyjs/vuetify#3352]
### New Functionality
Adding a ':freeze' prop would allow preventing the user to modify the `isActive` state of some or all of the `v-expansion-panel-content` child components.

The same way PR #3324 modified how the `v-model` handled the toggle states, we could imagine doing the same thing for the freeze states so that we could 'freeze' each panel separately, with:
```html
<template>
  <v-app dark>
    <v-expansion-panel
        v-model="model"
        :expand="expand"
        :freeze="freeze"
        focusable
    >
      <v-expansion-panel-content v-for="item in items" :key="item">
        <div slot="header">Item</div>
        <v-card>
          <v-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</v-card-text>
        </v-card>
      </v-expansion-panel-content>
    </v-expansion-panel>
    <!-- Modifying the model -->
    <v-btn @click="model = model - 1">prev</v-btn>
    <v-btn @click="model = model + 1">next</v-btn>
    <v-btn @click="model = [true,true,true,true,true]">all</v-btn>
    <v-btn @click="model = []">none (empty array)</v-btn>
    <v-btn @click="model = null">none (null)</v-btn>
    <!-- Expand actions -->
    <v-btn @click="expand = !expand">toggle expand</v-btn>
    <!-- Freeze actions -->
    <v-btn @click="freeze = freeze - 1">freeze previous</v-btn>
    <v-btn @click="freeze = freeze + 1">freeze next</v-btn>
    <v-btn @click="freeze = [true,false,false,true]">Freeze some (first and last) (array)</v-btn>
    <v-btn @click="freeze = [true,true,true,true]">Freeze all (array)</v-btn>
    <v-btn @click="freeze = true">Freeze all (true)</v-btn>
    <v-btn @click="freeze = 'all'">Freeze all ('all')</v-btn>
    <v-btn @click="freeze = []">Unfreeze all (empty array)</v-btn>
    <v-btn @click="freeze = null">Unfreeze all (null)</v-btn>
    <!-- What about toggling the freeze states? -->
  </v-app>
</template>
```
With this and if we want to provide the same behavior than for the `model`, *toggling* the `freeze` states would require an additional prop whose name would need to be defined.

One of the use case behind this is being able to use the `<v-expansion-panel>` component as a stepper when filling long/complex forms.
This could also allow:
- Being able to 'freeze' a panel until the user complete a certain set of text-field for instance.
- Being able to prevent a user to close a panel until the form it in is valid (or a field in another part of the page)
- When displaying a form with mandatory basic info and some optional ones, being able to freeze the basic info panel so it always stays open
- Another use case is to use that component to display permanent information
- etc.

More details about that feature can be seen and has been discussed in issue https://github.com/vuetifyjs/vuetify/issues/3271.

### Improvements
Currently, there is no easy way to prevent a `<v-expansion-panel-content>` from opening/closing, either globally or separately.

### Bugs or Edge Cases it Helps Avoid
N/A

**Comment by chewy94** [comment]
I think that this breaks material spec. Also, the major use case you have described here is already available by using a vertical `v-stepper`

**Comment by AlexandreBonneau** [comment]
However, with a vertical `v-stepper`, you cannot have more that one 'panel' opened at the same time, and even though you can skip one or more steps by clicking directly on the panel you want to open (when declaring an ` editable` prop on each `v-stepper-step`), the continuous and linear edition process does not bode well with forms with *optional* data.

ie. if the user *want to/can* set some optional data, he can decide when to open/close the panel(s), without the form shoving that part in front of his eyes obliging him to click a superfluous 'Continue' button.

I see those components serving different purposes, specially with that 'freeze' feature.

**Comment by chewy94** [comment]
Thoughts @vuetifyjs/dev-team ?

**Comment by johnleider** [comment]
I'm okay with it, granted it doesn't generated a bunch of extra code. @nekosaur just did a small refactor enabling model control in 2adc35727784e6251e579c88e4b1e686855f58d7
