### ISSUE TITLE
[Bug Report] Invisible text in flat solo-inverted Select within the toolbar 

### ISSUE THREAD

**Issue by iec989** [vuetifyjs/vuetify#3356]
### Versions and Environment
**Vuetify:** 1.0.2
**Vue:** 2.5.13
**Browsers:** Chromium 64.0.3282.167
**OS:** Ubuntu undefined

### Steps to reproduce
Click in the toolbar's "Property" dropdown.

When you click any option, the text has the same color (white) than the background, and therfore, it is not seen until it loses the focus.

### Expected Behavior
Either to blur as soon as you select an option, or to manage the colors in a different way so the text is visible

### Actual Behavior
Text is invisible as the color is equal to background's color (white)

### Reproduction Link
[https://codepen.io/iec989/pen/gvzKdM](https://codepen.io/iec989/pen/gvzKdM)

**Comment by johnleider** [comment]
The provided pen is not working.

**Comment by KaelWD** [comment]
Works for me, and looks like it's been fixed already in 1.1: https://codepen.io/anon/pen/xjywmW
