### ISSUE TITLE
[Feature Request] Date and Time Picker together in one component

### ISSUE THREAD

**Issue by Jamesking56** [vuetifyjs/vuetify#3357]
### New Functionality
At the moment, I have to create two separate fields so that I can make the most user friendly way of picking a date and time. This feature will allow the user to pick a date and a time in a single element.

### Improvements
Instead of having to create 2 fields and joining them later, we can just create a single field.

### Bugs or Edge Cases it Helps Avoid
When both pickers are visible, causing issues.

**Comment by KaelWD** [comment]
Duplicate of #459
