### ISSUE TITLE
[Feature Request] Use keyboard in time pickers

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#3359]
I think it would be nice to be able to enter the time in the time picker with the keyboard instead of only selecting it with the mouse. I don't know if this feature is possible with the material specs - it's just an idea to improve the time pickers.

**Comment by chewy94** [comment]
Not to be a stickler here... But please re-open this request using https://issues.vuetifyjs.com/

Closing the issue per the rules
