### ISSUE TITLE
Example codes should come with all relevant code to reproduce carbon copy of the excepted outcome

### ISSUE THREAD

**Issue by Napzu** [vuetifyjs/vuetify#336]
I have tried to get grid component example working couple of times.

When I copy pasted to code to Codepen, included all the relevant files, I did't get anything near the outcome I was expecting.

I was guided by @mfferreira that:
- wrap whole thing with v-app, still not the same outcome
- initialize your Vue app, still not the same outcome
- add some CSS to make it same, finally same outcome that I has excepting

So although maybe some "mistakes" was made by my part, I think examples could and should be made better with all the relevant code to reproduce the outcome of the example. Full minimal example links to codepen, jsbin or other would be nice.

With complete examples, new Vuetify triers would get much better user experience, get started more quickly, and most importantly, put Vuetify to their toolchain because "it just works" that good and gives exactly the documented outcome everybody is expecting it to be.

I really like what you guys are doing and I want Vuetify to come default choice to all Vue developers to make Vue things even better!

Keep up the good work!

**Comment by Napzu** [comment]
Actually one more point. All the examples should mirror the default you get with just including all the files. Just using the HTML should get same results as the examples.

**Comment by johnleider** [comment]
There is another documentation overhaul in the works that will provide a better overall experience for users. In light of that, I'm going to close this ticket as it is more to do with documentation than Vuetify. You are free to re-open something similar on this official docs repo.

**Comment by Napzu** [comment]
Ok, thanks for info. Made issue because @mfferreira asked if I could do it in gitter..

**Comment by johnleider** [comment]
For sure, issue should just probably be on the [docs](https://github.com/vuetifyjs/docs),

**Comment by Napzu** [comment]
Done.

**Comment by johnleider** [comment]
Thank you.
