### ISSUE TITLE
[Feature Request] V-Select: sortable and editable chips tags

### ISSUE THREAD

**Issue by robertsLando** [vuetifyjs/vuetify#3360]
### New Functionality
I will be able to sort the array of tags and edit single items. If the order of tags in the array is relevant for you this is very useful as If you need to edit a tag in position 0 right now you have to delete all tags and recreate them one by one. 

The edit feature can be triggered on double click on a tag, an element can be moved on long press/touch on it.

### Improvements
To make this you need to implement features on slot `selection` of `v-chip`

### Bugs or Edge Cases it Helps Avoid
This helps to make `v-select` with tags more flexible

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
