### ISSUE TITLE
[Bug Report] v-tabs: cannot read clientWidth of undefined

### ISSUE THREAD

**Issue by ram-you** [vuetifyjs/vuetify#3361]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Linux x86_64

### Steps to reproduce
Type something in the search field that will give no results and refresh page
Perhaps this is dependent on CPU speed so results may vary.
It's the same  issue as https://github.com/vuetifyjs/vuetify/issues/1195

### Expected Behavior
no errors

### Actual Behavior
Cannot read property 'clientWidth' of undefined

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/issues/1195](https://github.com/vuetifyjs/vuetify/issues/1195)

### Other comments
happened sometimes, not always when no data or few data in tab item.

**Comment by KaelWD** [comment]
You can't just link to an old issue, that codepen isn't valid any more.
