### ISSUE TITLE
[Bug Report] Clear icon always shown on clearable v-text-field with type 'date'/'time'

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#3362]
![image](https://user-images.githubusercontent.com/11846736/36543606-7ea0df0c-17e4-11e8-8081-ded7859d71b4.png)

See screenshot. The "clear" icon should not be shown because no date or time is selected.

It's a normal v-text-field with type "date" / "time" and the prop "clearable".

Codepen: https://codepen.io/anon/pen/GQGBeM

**Comment by chewy94** [comment]
Please follow the issue template found here: https://issues.vuetifyjs.com/
