### ISSUE TITLE
[Feature Request] Partial coloring of v-card elements

### ISSUE THREAD

**Issue by markwalet** [vuetifyjs/vuetify#3367]
### New Functionality
I want to include the Colorable mixin on elements like the v-card-title. Also on other sub-elements for v-card.

### Improvements
If I wanted to create something like the following:

http://mdlwp.com/wp-content/uploads/edd/2015/07/material-design-login-forms.jpg

I could just use the color trait on the v-card-title element. Instead of using custom css.

### Bugs or Edge Cases it Helps Avoid
None.

**Comment by nekosaur** [comment]
This is already possible using the css color helper classes.

https://codepen.io/anon/pen/EQpWOZ

**Comment by markwalet** [comment]
Sorry! Missed that :)
