### ISSUE TITLE
[Bug Report] Vee-validate not working - Error in render: "TypeError: Cannot read property 'collect' of undefined"

### ISSUE THREAD

**Issue by wachroberts** [vuetifyjs/vuetify#3368]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chromium 64.0.3282.140
**OS:** Ubuntu undefined

### Steps to reproduce
Text field with vee validate not working, using the example given in official vuetify docs.
Copying the exact example throws an error

### Expected Behavior
Error in render: "TypeError: Cannot read property 'collect' of undefined"

### Actual Behavior
validation

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/forms/veeValidate.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/forms/veeValidate.vue)

### Other comments
cant validate input fields with vee-validate

**Comment by KaelWD** [comment]
Have you installed vee-validate?

**Comment by wachroberts** [comment]
Thanks, **KaelWD**. It seems you have to manually add vee-validate. After I installed it validation started working again.
