### ISSUE TITLE
[Feature Request] Use keyboard in time pickers

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#3369]
### New Functionality
I think it would be nice to be able to enter the time in the time picker with the keyboard instead of only selecting it with the mouse. I don't know if this feature is possible with the material specs - it's just an idea to improve the time pickers.

### Improvements
Possibility to use the keyboard to set the time in time pickers.

### Bugs or Edge Cases it Helps Avoid
Accessibility

**Comment by johnleider** [comment]
This can be done with a text-field. Thank you for the suggestion.
