### ISSUE TITLE
[Bug Report] issue when adding (lighten/darken) to primary color to v-chip with (outline border)

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [vuetifyjs/vuetify#3374]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
create `v-chip` element
add lighten/darken to primary color.
add outline to element.
`<v-chip outline color="primary lighten-4">primary Border lighten-4</v-chip>`

### Expected Behavior
the color of the border get (lighten/darken) with primary color

### Actual Behavior
the border removed and the background changed to primary (lighten/darken)

### Reproduction Link
[https://codepen.io/NadhirBoukhenifra/pen/aqjGwN](https://codepen.io/NadhirBoukhenifra/pen/aqjGwN)

### Other comments
and the same issue for accent, seconday only.
other classes like (success, warning,..) works fine.

**Comment by KaelWD** [comment]
The theme stylesheet needs to be above everything else. 

Outline chips do `background: transparent !important;`, which is overridden by `.primary.darken-4`  
but not `.red.darken-4`, because that's declared first

**Comment by KaelWD** [comment]
`success`, `warning`, and `error` work because only `primary`, `secondary`, and `accent` have variations by default.
