### ISSUE TITLE
[Feature Request] Ability to set width of "select-all" column in data table

### ISSUE THREAD

**Issue by sbrth** [vuetifyjs/vuetify#3376]
### New Functionality
Set the width of the cell generated by the "select-all" property of data tables without having to set it manually on the checkbox column. As of now it scaled normally with all other cells, which may not be the behavior many would expect from a cell that will always be fixed width anyways.

### Improvements
As of now the width has to be set on the column containing the checkbox on each item, whereas all other columns widths can be set using the "width" property in the headers objects.

### Bugs or Edge Cases it Helps Avoid
There is no way at all to set the width of the "select-all" columns when there are no entries, as the entries are the only way to access that specific columns width. Unless one wanted to use something very brittle like "first-child" selectors there will need to be a way to do this.

**Comment by johnleider** [comment]
Can you show an example of what this resolves?

**Comment by SignificantOtter** [comment]
I just ran into this issue. I think a more flexible solution would be to allow us to apply an array of classes to the select-all header. For example:

    :select-all-classes="['dt-action-header', 'dt-select-all-header']"

**Comment by nekosaur** [comment]
This is now possible in 2.0. Add an item with value `data-table-select` and a `width` property to `headers` array.
