### ISSUE TITLE
V-Select with multiple:false && tags:true

### ISSUE THREAD

**Issue by na018** [vuetifyjs/vuetify#3378]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Linux x86_64

### Steps to reproduce
    <v-select label="Select/ create new Item"
            v-model="Intem.name"
                      :tags="true"
                      :items="alreadyExistingNames"
                      :multiple="false"
                      autocomplete
            ></v-select>

### Expected Behavior
Create new single Item or select an existing item (no multiple selection)
**multiple: false && tags: true**
**no Array**

### Actual Behavior
Selection with tags is always multiple.

### Reproduction Link
[https://jsfiddle.net/na0188/cqogvmdg/9/#&togetherjs=mot8lKDSgF](https://jsfiddle.net/na0188/cqogvmdg/9/#&togetherjs=mot8lKDSgF)

**Comment by KaelWD** [comment]
`combobox` is the single select variant of tags. There's supposed to be an example on https://vuetifyjs.com/components/selects but it seems to have gone missing.
