### ISSUE TITLE
[Bug Report] v-text-field required with counter errors

### ISSUE THREAD

**Issue by AbdulkaderMakki** [vuetifyjs/vuetify#3381]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
add required
add counter

### Expected Behavior
align errors:
required label at right
counter at left

### Actual Behavior
align errors not right
required: error label appear at center and take the whole width
counter: disappear because required error take all the width

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)
https://codepen.io/anon/pen/RQYMaX

**Comment by AbdulkaderMakki** [comment]
I fixed this by add
```
{
  flex: 1 0 80%;
  text-align: left;
}
```
to .input-group__error class

**Comment by chewy94** [comment]
The issue you are describing is not based on the use of required or counter. If you look at your codepen you have specified a `text-xs-center` on the `v-flex` containing the `v-text-fields`

**Comment by AbdulkaderMakki** [comment]
@chewy94 Thanks
you're right for required error text
but is this the expected behavior for both counter and required?
I mean the counter disappear once required error triggered

**Comment by KaelWD** [comment]
Caused by #3077
