### ISSUE TITLE
[Feature Request] <v-avatar> | Option To Set Border Radius

### ISSUE THREAD

**Issue by StephenMP** [vuetifyjs/vuetify#3382]
### New Functionality
Currently, you can either take the default border radius or specify the `tile` option to override the default border radius, but you can only get one of the two types of avatars:

1. A circular avatar
1. A square avatar

By having an option to set the border radius, it would allow users to have control over the border radius used for the image. For example:

```
<v-avatar size="500px" radius="10px">
     <img src="/path/to/image />
</v-avatar>
```

would create a responsive image with height and width at 500px and border radius set to 10px to give a rounded square look like the following:

https://codepen.io/anon/pen/OQoBRr

### Improvements
Users wouldn't have to override the avatar class stylings (which generally require a bunch of `!important` declarations and custom classes/ids).

It would also give users the flexibility to customize their exact look and feel.

### Bugs or Edge Cases it Helps Avoid
I don't think there are any bugs or edge cases the added feature would help avoid. A potential edge case it may introduce would potentially be with the `<v-list-tile-avatar>` tag since that reflects the same options.

**Comment by chewy94** [comment]
I cannot think of a reason to not add this as an option.

Thoughts @vuetifyjs/dev-team ?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
