### ISSUE TITLE
[Bug Report] GoTo element with offset above top of page locks scrolling

### ISSUE THREAD

**Issue by BenShelton** [vuetifyjs/vuetify#3384]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.13.3

### Steps to reproduce
- Have a page that can scroll
- Have an element near the top of the page that you want to scroll to
- Use `$vuetify.goTo('#element-near-top', { offset: -100 })` where the offset will attempt to scroll past the top of the page
- Try to scroll down

### Expected Behavior
Page will scroll down

### Actual Behavior
Page keeps bouncing back to the top preventing you from scrolling

### Reproduction Link
[https://codepen.io/BenShelton/pen/jZeNMg](https://codepen.io/BenShelton/pen/jZeNMg)

**Comment by BenShelton** [comment]
It also seems simple specifying a negative scroll value has the same effect, for example: `$vuetify.goTo(-100)`

**Comment by IPRIT** [comment]
offsetTop for h1-6 also doesn't work properly.

**Comment by ayush987goyal** [comment]
Also, it does not work in the production build. Using it with `@vue/cli@3.0.0-beta.2` and `vuetify@1.0.4`

**Comment by siloam** [comment]
Is there any solution for this bug? It practically makes scrolling impossible with goTo method.

**Comment by BenShelton** [comment]
I've created a PR to possibly fix this issue. In the meantime the best thing to do is make sure whatever you pass to `goTo` will not result in a negative number, so do the calculation beforehand:

``` js
let pos = 
  element.offsetTop // if using an element
  VueComponent.$el.offsetTop // if using a Vue component
  document.querySelector('#element-near-top').offsetTop // if using a string
  20 // if using a number

const offset = -100
const pos = Math.max(pos + offset, 0)
this.$vuetify.goTo(pos)
```
