### ISSUE TITLE
[Bug Report] v-menu item disabled but still trigger click event

### ISSUE THREAD

**Issue by ymchun** [vuetifyjs/vuetify#3387]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the Codepen link and click the button, you will see a menu with disabled items.
Mouse over the menu items and see hover highlight but no such effect when mouse over again.
Open the console and click on the menu item, will see click event triggered.

### Expected Behavior
When menu item disabled, it cannot trigger click event and have no hover highlight effect

### Actual Behavior
Still trigger click event
And the hover highlight effect appear once

### Reproduction Link
[https://codepen.io/anon/pen/oEaLKv?editors=1011](https://codepen.io/anon/pen/oEaLKv?editors=1011)

![](https://media.giphy.com/media/bkgvDcIdwuQaex3WFs/giphy.gif)

**Comment by johnleider** [comment]
I've pushed a fix for the highlighting and cursor issue. In regards to the click event, list-tiles do not sanitize events, you will need to that in your application.
