### ISSUE TITLE
[Bug Report] v-dialog seems to select the wrong item inside v-data-table

### ISSUE THREAD

**Issue by karlyao** [vuetifyjs/vuetify#3388]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.13.3

### Steps to reproduce
Click the third DELETE button, it shows 'Frozen Yogurt'. Click the forth DELETE button, it shows 'Ice cream sandwich'. After 5 clicks on any buttons, it stays with 'Gingerbread'

### Expected Behavior
Click on the third DELETE button should show 'Eclair' (the third row in the table). Click on the forth DELETE button should show 'Cupcake' (the forth row in the table).

### Actual Behavior
It seems like it is picking up the value from row 1 and then cycle through to row 2 etc, regardless of which row button is clicked.

### Reproduction Link
[https://codepen.io/karlyao/pen/vdVGWr](https://codepen.io/karlyao/pen/vdVGWr)

**Comment by johnleider** [comment]
This is happening because you are using the same model for all of the `v-dialog`s. So whichever one shows up is a race condition. My suggestion is to take a different approach https://codepen.io/johnjleider/pen/EQOaxO?editors=1010

**Comment by karlyao** [comment]
Thank you so much for the right approach. Yes it works! Much appreciated.

**Comment by karlyao** [comment]
Sorry... wonder if I can ask for further help... after it is sorted, not sure what is the approach to also re-sort the index. Thanks.

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
