### ISSUE TITLE
[Bug Report] calculate lighten/darken color for theme tokens

### ISSUE THREAD

**Issue by alphaelf** [vuetifyjs/vuetify#3389]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
create theme via theme generator and choose blue (`#2196F3`) for primary
set theme to `this.$vuetify.theme`
make card with toolbar and colored with theme color tokens plus (lighten/darken) `primary lighten-5`

### Expected Behavior
`primary lighten-5` must be `#E3F2FD` 

### Actual Behavior
`primary lighten-5` is `#D4FFFF`

### Reproduction Link
[https://codepen.io/alphaelf/pen/zRmzrp](https://codepen.io/alphaelf/pen/zRmzrp)

### Other comments
the codepen example will explain more

**Comment by johnleider** [comment]
@KaelWD thoughts?

**Comment by KaelWD** [comment]
This has come up before. The color generation could certainly be tweaked, I just roughly guessed what values would work. Getting exact matches on the other hand is pretty much impossible without just importing and comparing the color list util file.

**Comment by lebnor01** [comment]
Could there also be a way to specify which values the darken-x/lighten-x should be? For example I want to specify a custom primary / secondary color, but I don't want to have the darken/lighten values automatically calculated. I would like to specify my own values.

**Comment by KaelWD** [comment]
#4408

**Comment by KaelWD** [comment]
Closing in favour of #4408. I still think the generated colours could be improved if anyone feels like having a poke around, but it isn't anywhere near a priority.
