### ISSUE TITLE
[Bug Report] The example from the Quickstart page is not working

### ISSUE THREAD

**Issue by pmgpmg** [vuetifyjs/vuetify#3390]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
This code is a direct copy of the code on the QuickStart page https://vuetifyjs.com/en/getting-started/quick-start
I ran it on Chrome Version 52.0.2743.82 (64-bit) 
Firefox does not have this issue

### Expected Behavior
No errors in the console log

### Actual Behavior

Errors in the console log
index.js:37 Uncaught TypeError: Object.values is not a function
vue.js:584 [Vue warn]: Unknown custom element: <v-app> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
vue.js:584 [Vue warn]: Unknown custom element: <v-content> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
vue.js:584 [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### Reproduction Link
[https://jsfiddle.net/pmgFiddle/xw86c5wo/#&togetherjs=tgDDjku8Lz](https://jsfiddle.net/pmgFiddle/xw86c5wo/#&togetherjs=tgDDjku8Lz)

**Comment by KaelWD** [comment]
Old browsers need a polyfill.
