### ISSUE TITLE
[Bug Report] v-btn should depend on v-progress-circular

### ISSUE THREAD

**Issue by Igloczek** [vuetifyjs/vuetify#3391]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.13.3

### Steps to reproduce
1. Import `v-btn` component inside a .vue file following `a-la-carte` documentation
2. Use `loading` param to get loader on button

### Expected Behavior
Loader works

### Actual Behavior
`Unknown custom element: <v-progress-circular>`

### Reproduction Link
https://github.com/Igloczek/youtube-comments-downloader/blob/8a948c263ac908c56045e6b1cf4cc60cee12419b/src/components/YtForm.vue#L43-L51

### Other comments
`v-btn` component should import `v-progress-circular`

**Comment by dominik-bln** [comment]
The same problem exists for `VSelect` with async autocomplete and `VProgressLinear`
