### ISSUE TITLE
[Feature Request] Floating action buttons with optional text

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#3399]
### New Functionality
It will allow for more robust floating action buttons for actions that need more description than just a icon can provide.

### Improvements
n/a

### Bugs or Edge Cases it Helps Avoid
n/a

![speeddial_helper_text](https://user-images.githubusercontent.com/4167341/36714798-8fab6a9a-1bce-11e8-9017-84ccf455f329.jpeg)

**Comment by KaelWD** [comment]
tooltips with `:value="true"`?

**Comment by mcfarljw** [comment]
Good idea, didn't think to try that! It looks like the tooltip doesn't line up though when doing this inside a speed dial. I might be doing something wrong though.

https://codepen.io/mcfarljw/pen/VQVQap

**Comment by eelcowen** [comment]
@mcfarljw The tooltips position when they are created and still moving. If you create a small delay before they show they will position fine.

**Comment by KaelWD** [comment]
That's because of the animation. You can get around it by using a fade transition instead, or doing some janky timeouts: https://codepen.io/anon/pen/aqQKwN?editors=1010

**Comment by mcfarljw** [comment]
Thanks! This is definitely a sufficient work around for the time being.

**Comment by smanji** [comment]
With the tooltips overlaying on the page, by default, they have a tinted background. But depending on what is behind the tooltip, this little overlay can clutter the page and be a bit hard to read.

I'd like to suggest that when the speed dial opens, the entire page gets this tinted overlay (instead of just the size of each individual tooltip) so that way the text of the tooltip for each button really pops and is easy to read.

Perhaps the background color can be specified as it is today with the tooltips, but I like the dark tint that the tooltips have by default.

Is there a way to accomplish this?

**Comment by alexeigs** [comment]
@KaelWD How is this supposed to work if you have an absolutely positioned floating button? The tooltips are not shown anymore once you add `fixed` or `absolute` to `v-speed-dial`.

**Comment by dominik-korsa** [comment]
What's the progress on this feature?
I wasn't able to find the specs for this, but there's an example of labels in a speed dial component. 
![image](https://user-images.githubusercontent.com/29484605/81281474-2c206b80-905a-11ea-97fa-5c7edc422845.png)
https://material.io/components/buttons-floating-action-button#types-of-transitions

**Comment by joaofbvieira** [comment]
I've made a custom text for each fab button.

Here's an example:

<v-speed-dial
    v-model="fab"
    :top="false"
    :bottom="true"
    :right="true"
    :left="false"
    :direction="'top'"
    :open-on-hover="false"
    :transition="'slide-y-reverse-transition'"
    :absolute="true"
    >
    <template v-slot:activator>
        <v-btn
        v-model="fab"
        color="primary"
        dark
        fab
        >
        <v-icon v-if="fab">mdi-close</v-icon>
        <v-icon v-else>mdi-plus</v-icon>
        </v-btn>
    </template>
    <v-btn
        fab
        dark
        small
        color="green"
    >
        <v-icon>mdi-pencil</v-icon>
        <div class="fab-text-custom green">Create</div>
    </v-btn>
</v-speed-dial>

<style scoped>
.fab-text-custom {
    position: absolute;
    right: 50px;
    background-color: rgba(0,0,0,0.5);
    padding: 10px;
    box-shadow: 0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 6px 10px 0px rgba(0, 0, 0, 0.14), 0px 1px 18px 0px rgba(0, 0, 0, 0.12);
    border-radius: 2px;
}
</style>

**Comment by joaofbvieira** [comment]
I've made a custom text for each button.
Here's an example of this workaround:

`<v-speed-dial
    v-model="fab"
    :top="false"
    :bottom="true"
    :right="true"
    :left="false"
    :direction="'top'"
    :open-on-hover="false"
    :transition="'slide-y-reverse-transition'"
    :absolute="true"
    >
    <template v-slot:activator>
        <v-btn
        v-model="fab"
        color="primary"
        dark
        fab
        >
        <v-icon v-if="fab">mdi-close</v-icon>
        <v-icon v-else>mdi-plus</v-icon>
        </v-btn>
    </template>
    <v-btn
        fab
        dark
        small
        color="green"
    >
        <v-icon>mdi-pencil</v-icon>
        <div class="fab-text-custom green">Create</div>
    </v-btn>
</v-speed-dial>

<style scoped>
.fab-text-custom {
    position: absolute;
    right: 50px;
    background-color: rgba(0,0,0,0.5);
    padding: 10px;
    box-shadow: 0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 6px 10px 0px rgba(0, 0, 0, 0.14), 0px 1px 18px 0px rgba(0, 0, 0, 0.12);
    border-radius: 2px;
}
</style>`

**Comment by joaofbvieira** [comment]
I've made a custom text label.

Here's my example: https://codepen.io/joaofbvieira/pen/dyGoELN

I hope that they implement this option into Vuetify. Until then, we make workarounds, lol.

Cheers.

**Comment by abepetrillo** [comment]
@joaofbvieira Seems like your missing a few things in that codepen?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Skintillion** [comment]
https://codesandbox.io/s/vuetify-playground-forked-uz4mz?file=/src/layout.vue:2152-2202

Working example

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
