### ISSUE TITLE
DataTable initial row per page value

### ISSUE THREAD

**Issue by MitchelLabonte** [vuetifyjs/vuetify#340]
### Steps to reproduce
- Add a datatable
- Set rows-per-page-items with an array that doesn't contain 5

### Versions
Firefox 45.8.0
Vuetify 0.10.4

### What is expected ?
The selected value of the "rows per page" dropdown should be the first option.

### What is actually happening ?
The "rows per page" dropdown is initially set to an empty value while the table displays 5 items per page.

### Reproduction Link
https://codepen.io/ElMitchL/pen/yMmZYz

**Comment by silvioiannone** [comment]
The issue is still present on for 0.12.7: https://codepen.io/anon/pen/WOjbRb

**Comment by maesklaas** [comment]
Still not working, any clue when this will be fixed?

**Comment by xgrounds** [comment]
This issue has been fixed now.
