### ISSUE TITLE
[Bug Report] Rendering issue in ExpansionLists - ExpansionList is not rendering as its shown in documentation

### ISSUE THREAD

**Issue by Divine1** [vuetifyjs/vuetify#3402]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.75
**OS:** Windows 10

### Steps to reproduce
Download the `test-nuxtapp` project from my git repository.
[https://github.com/divine3/vuejs/tree/master/test-nuxtapp](https://github.com/divine3/vuejs/tree/master/test-nuxtapp)

```
npm install

npm run dev
```

### Expected Behavior
The output that is shown in this documentation is the expected output

https://vuetifyjs.com/en/components/lists#example-expansion-lists

![image](https://user-images.githubusercontent.com/10482177/36723703-09fd8b04-1bd7-11e8-9030-b84ea0050e3a.png)

### Actual Behavior
when you run my project you will find an output at localhost:3000.
This is the actual output

![image](https://user-images.githubusercontent.com/10482177/36723745-21a0d540-1bd7-11e8-8068-0b2281c8feae.png)

### Reproduction Link
[https://github.com/divine3/vuejs/tree/master/test-nuxtapp](https://github.com/divine3/vuejs/tree/master/test-nuxtapp)

### Other comments
The output shown in documentation and the output i get while doing the same steps are not the same. Kindly let me know if this is a bug or whether a fault in my program.i don't find any fault in my program

**Comment by KaelWD** [comment]
Your project is using vuetify 0.17.7 

https://github.com/divine3/vuejs/blob/master/test-nuxtapp/package-lock.json#L9252

**Comment by Divine1** [comment]
yea.  i didn't know why i thought i'm using 1.0.0
