### ISSUE TITLE
[Bug Report] Css Map on server with router:base

### ISSUE THREAD

**Issue by Greaka** [vuetifyjs/vuetify#3403]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
Make a project and use the base option of vue-router.

example from nuxt.config.js:
```javascript
module.exports = {
  router: {
    base: '/gw2-treasury/'
  }
}
```

### Expected Behavior
vuetify should reflect that option

### Actual Behavior
vuetify does not look use the base option

### Reproduction Link
[https://github.com/vuetifyjs/nuxt](https://github.com/vuetifyjs/nuxt)

**Comment by KaelWD** [comment]
This is related to *our* build process, has nothing to do with your router configuration. 

More context, from discord:

![image](https://user-images.githubusercontent.com/16421948/36729826-949fb010-1c19-11e8-91d1-87a26a9e4987.png)

![image](https://user-images.githubusercontent.com/16421948/36729864-b008c49a-1c19-11e8-94aa-40fb5f432d78.png)

![image](https://user-images.githubusercontent.com/16421948/36729886-c24d7790-1c19-11e8-8660-1abaf212e9ee.png)

**Comment by dhampik** [comment]
@KaelWD @johnleider @Greaka Can you confirm that it's really fixed in vuetify 1.0.5?
I just tried to do the following:
~~~
vue init vuetifyjs/nuxt vuetify-test
cd vuetify-test
yarn install
yarn run dev
~~~
I open developer tools in Chrome and refresh the page and I still see source maps 404 errors from nuxt.
vuetify 1.0.5 is used.

**Comment by KaelWD** [comment]
Which ones are failing? All the `vuetify/src/stylus/components/*.css.map` links didn't actually exist and were invalid, they are the only ones I removed. If you want to load the main `vuetify.js.map` then you need to use something like [`source-map-loader`](https://github.com/webpack-contrib/source-map-loader)

**Comment by dhampik** [comment]
@KaelWD Well, for me it does not seem, that they are removed. After doing the above steps, I still get the following output from nuxt dev server:
<details>
<summary>Please, click here to expand full nuxt output</summary>
 OPEN  http://localhost:3000

  nuxt:render Rendering url / +0ms
  nuxt:render Data fetching /: 1ms +0ms
  nuxt:render Rendering url / +6s
  nuxt:render Data fetching /: 0ms +6s
  nuxt:render Rendering url /assets/style/app.css.map +218ms
{ statusCode: 404,
  path: '/assets/style/app.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_app.css.map +24ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_app.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_cards.css.map +17ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_cards.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_navigation-drawer.css.map +22ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_navigation-drawer.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_footer.css.map +19ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_footer.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_overlay.css.map +29ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_overlay.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_lists.css.map +21ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_lists.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_icons.css.map +18ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_icons.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_avatars.css.map +35ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_avatars.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_buttons.css.map +27ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_buttons.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_progress-circular.css.map +25ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_progress-circular.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_content.css.map +23ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_content.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_grid.css.map +23ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_grid.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /node_modules/vuetify/src/stylus/components/_toolbar.css.map +25ms
{ statusCode: 404,
  path: '/node_modules/vuetify/src/stylus/components/_toolbar.css.map',
  message: 'This page could not be found' }
</details>

**Comment by marianagarciaferreira** [comment]
same problem

**Comment by KaelWD** [comment]
If you are importing vuetify's Stylus instead of precompiled CSS, you'll have to make similar config changes in your own project.

**Comment by dhampik** [comment]
Could you, please, provide some examples how to configure vuetify with nuxt properly or maybe point to some documentation? I was using "official" vuetifyjs/nuxt and I haven't found proper configuration there.

**Comment by DanjBethel** [comment]
@KaelWD anything further on the above comment? having the same issue

**Comment by KaelWD** [comment]
What options did you choose when setting up the template?

**Comment by movepixels** [comment]
A-La-Carte

**Comment by KaelWD** [comment]
Nuxt only has an option to completely remove CSS sourcemaps as far as I can tell, so that's something to bring up with them if you need sourcemaps for you own CSS

https://nuxtjs.org/api/configuration-build/#csssourcemap

**Comment by movepixels** [comment]
Even adding that in did not solve the issue.
Might just scrap it all together and do it manually.

**Comment by chanlito** [comment]
@movepixels Did you manage to find a way to fix this issue? currently I'm setting `cssSourceMap` to `false`.

**Comment by gomezmark** [comment]
same problem here

**Comment by movepixels** [comment]
This ended up working for me in the end:

 

build: {

    cssSourceMap: false, // add this into the nuxt.config

    extend (config) {

      config.devtool = false

    },

 

Dave Maharaj

Owner / Designer / Developer

 <mailto:dave@movepixels.com> dave@movepixels.com

 <http://www.movepixels.com/> www.movepixels.com
709-757-9457

**Comment by wahengchang** [comment]
@movepixels  you are the king !!

**Comment by bulwarkext** [comment]
@movepixels your solutions worked like a charm. Great!!!
