### ISSUE TITLE
[Bug Report] v-container doesn't render customer attribute value

### ISSUE THREAD

**Issue by mojo2012** [vuetifyjs/vuetify#3404]
## Versions and Environment

Vuetify: 1.0.4
Vue: 2.5.13
Browsers: Firefox 58.0.2
OS: macOS 10.12.6 (16G1212)

## Steps to reproduce
Hi all,

I have a tag `<v-container uuid="comp315884348" class=""  fluid>`. The rendered HTML only contains the the `uuid`attribute without the value.
This sees the same for other attributes.

## Expected Behavior
Using other tags like `v-content`it's working as expected (attributes and values are rendered)

**Comment by johnleider** [comment]
Grid components are special in that they will mirror their attrs as classes. If you need to use custom attributes beyond id, you will need to use a wrapper `div` with the required attrs.

**Comment by supaket** [comment]
Hi @johnleider . Data attribute some purpose we use for testing component. It really bad id to have more div wrapper.
Btw, do you have alternative idea to test ui component?
