### ISSUE TITLE
[Bug Report] Align standalone v-list-tiles with a v-list-group

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#3407]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Visit the Codepen, look at the red lines, compare icon alignment of "Dashboard" (standalone, one-off v-list-tile) with "Billing" and "Payments" (part of a v-list-group).

### Expected Behavior
Ideally, icons would be sized similarly and properly aligned, regardless of a v-list-group parent.

### Actual Behavior
Icons are misaligned.

### Reproduction Link
[https://codepen.io/cdwyer/pen/zRMMON](https://codepen.io/cdwyer/pen/zRMMON)

### Other comments
Per a Discord convo, @KaelWD noted it's a CSS issue. Here's what he recommended: 

```css
.list--dense .list__group__header .icon {
  font-size: 22px;
}
```

**Comment by johnleider** [comment]
This appears to be in the latest version. https://codepen.io/johnjleider/pen/jOEQbbL

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
