### ISSUE TITLE
[Feature Request] allow <v-text-field> to grow only up to 100% height of the parent component

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3411]
### New Functionality

Right now the `auto-grow` prop doesn't make it stop growing beyond the parent component: 
https://codepen.io/anon/pen/ddwPNB

### Improvements
It would be nice if it just stretchd between 2 other components taking up all the available space and become scrollable. Right now it just keeps growing when you add the `auto-grow` prop 

### Bugs or Edge Cases it Helps Avoid
none

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement.
