### ISSUE TITLE
[Bug Report] Long title in toolbar squeezes icon hover container

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3412]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Add long title to toolbar, so it would be cut off and two icons on sides. Hover over either icon.

### Expected Behavior
Hover shape is circle.

### Actual Behavior
Hover shape is oval, squeezed horizontally.
![hover-shape-firefox](https://user-images.githubusercontent.com/79141/36754386-73312862-1c11-11e8-8105-4e5b3aeb492d.png)

### Reproduction Link
[https://codepen.io/anon/pen/ZrVQOr?editors=1000](https://codepen.io/anon/pen/ZrVQOr?editors=1000)

**Comment by joshas** [comment]
Just noticed, that squished icon has smaller margin on the left, than normal:
![toolbar-icon-left-margin](https://user-images.githubusercontent.com/79141/36756501-d5b410ac-1c17-11e8-9bbc-d9c51b1b661a.png)

**Comment by ebisbe** [comment]
I hate that issue!

**Comment by ebisbe** [comment]
Why this issues has not been autoclosed? Using the keyword `fixes` should close it when the PR has been merged, right? 
https://help.github.com/articles/closing-issues-using-keywords/
