### ISSUE TITLE
[Help Wanted] CSS collision between Vuetify and HighchartJS

### ISSUE THREAD

**Issue by YounggilLee** [vuetifyjs/vuetify#3413]
Versions and Environment
Vuetify: 1.0.4
Vue: 2.5.2
Browsers: Crome
OS: OS X

Steps to reproduce
Create project using vue cli  vuetify/webpack.
import highchartJs version 3.2.1 (link : https://www.highcharts.com/products/highstock/)
import vue-highcharts 0.0.10 (link : https://github.com/weizhenye/vue-highcharts)

Expected Behavior
-Type in date in input box

<img width="284" alt="expect" src="https://user-images.githubusercontent.com/20617062/36755151-43ebe732-1bd9-11e8-9599-2f77a6195fa1.png">

Actual Behavior
-Duplicate date and can not remove and retype in data in input box

<img width="277" alt="actual" src="https://user-images.githubusercontent.com/20617062/36755187-6cb38c1a-1bd9-11e8-915b-cff84c6cd483.png">

Reproduction Link
https://jsfiddle.net/Younggil/53yh0gwr/20/

**Comment by KaelWD** [comment]
override it with ```css
input {
  background-color: transparent;
}
```

**Comment by YounggilLee** [comment]
Thanks KaelWD, but  the issue is still remain
