### ISSUE TITLE
[Feature Request] Using hex colors in colorable

### ISSUE THREAD

**Issue by greaka** [vuetifyjs/vuetify#3416]
### New Functionality
You are able to use hex color strings instead of materialize color strings.
Giving a color prop a string starting with `#` will treat that string as hex color value.

### Improvements
You can use computed color values without having to guess which materialize color string is closest to the computed color.

### Bugs or Edge Cases it Helps Avoid
Computed colors based on changing values can be set directly.
A very small example of a use case: https://codepen.io/anon/pen/wyRpWG

**Comment by AGPDev** [comment]
i need this too, dinamics elements, like Tags need much.

**Comment by swirlingsand** [comment]
So one option is:
`<v-icon :style="style_color(item.color.hex)"> turned_in </v-icon>`

With the method
```
    style_color: function (hex) {
      return "color:" + hex
    },
```
I'm sure this probably isn't a great way to do it but it does seem to work

**Comment by greaka** [comment]
Doesn't work for progress bars

**Comment by KaelWD** [comment]
You can already do this with the dynamic theme system, although it will probably murder performance if you do it too much: https://codepen.io/anon/pen/KoEmYp?editors=1010

**Comment by greaka** [comment]
This changes the color for every progress bar. Progress bars with different color values are not possible this way

**Comment by Ace-Cassidy** [comment]
I need a specific shade of blue for a corporate project and it is proving very annoying without this feature

**Comment by mmckalan** [comment]
I need this too. I'm working on a corporative project and would be nice to use some shade of blue. 
Hope the feature is added soon.
