### ISSUE TITLE
[Bug Report] Tabs with router not marked active

### ISSUE THREAD

**Issue by janein** [vuetifyjs/vuetify#3418]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Linux x86_64

### Steps to reproduce
Create Tabs which are based on a router. The tabs should point to the same route, but with different params in the url. (i.e. '/categories/1/', '/categories/2/')

### Expected Behavior
Active tabs should be marked with the highlight color and the sliding bar below it.

### Actual Behavior
Active tabs are only marked with the highlight color. Sliding bar stays at the first tab matching the route (but not the params).

### Reproduction Link
[https://codesandbox.io/s/4861v3lxmx](https://codesandbox.io/s/4861v3lxmx)

### Other comments
Worked fine in older versions. As the highlighting works fine on the highlight color, it should be solveable :)

**Comment by janein** [comment]
works in 1.0.2, is broken in 1.0.3

**Comment by janein** [comment]
managed to find the cause of the error in these changes:
https://github.com/vuetifyjs/vuetify/compare/v1.0.2...v1.0.3#diff-d429bd0dd45860c5f938bef84a1514a4

As I'm not aware why the checks to `name` have been added, I feel not secure to submit a pull-request. Maybe someone has a solution?

**Comment by Arteben** [comment]
I also came across this error in version 1.0.7.
https://codesandbox.io/s/v6rnpoo2k3

**Comment by janein** [comment]
Thanks a lot! Works like a charm! :)

**Comment by Arteben** [comment]
Thank very much)
