### ISSUE TITLE
Different colors for label and input border

### ISSUE THREAD

**Issue by rzb** [vuetifyjs/vuetify#342]
I'm getting different colors for label text and input bottom border. Shouldn't them be the same as per md specs?

This is my custom theme hash:

```
$theme := {
  primary   : $teal.darken-4
  accent    : $teal.accent-4
  secondary : $amber.base
  info      : $light-blue.base
  warning   : $orange.darken-2
  error     : $red.base
  success   : $green.base
}
```

![bug](https://i.imgur.com/5rf5HGl.png)

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by rzb** [comment]
It was on my end. I forgot to remove the cdn link after customizing the theme. My bad.
