### ISSUE TITLE
[Bug Report] Using a jumbotron within v-tab-items makes forward and backward animations difference evident.

### ISSUE THREAD

**Issue by cairinmichie** [vuetifyjs/vuetify#3420]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Use a Jumbotron in v-tab-items.
Changing tabs to the left and right and observe the difference.

### Expected Behavior
The left/right animations should be the same as the animation used when the page scrolls off screen to the left. i.e when there is no white gap in the background.

### Actual Behavior
When moving from the right to the left in the tabs there is a gap in the content in v-tab-items. When using a Jumbotron this is more evident.

### Reproduction Link
[https://codepen.io/anon/pen/VQqBXB](https://codepen.io/anon/pen/VQqBXB)

**Comment by johnleider** [comment]
This behavior has been present since the beginning of the framework. You can see it within carousel as well. It is because of how we delegate the transitions.

**Comment by johnleider** [comment]
This component has been deprecated. It is recommended to use `v-img` now.
