### ISSUE TITLE
[Feature Request] Convert the user's input into the Number type (将用户的输入转换为Number类型)

### ISSUE THREAD

**Issue by cn-xufei** [vuetifyjs/vuetify#3421]
### New Functionality
```html
<v-text-field type="number" />
```
The value type obtained is  String 😭

### Improvements
I want to add an attribute，for example : 
```html
<v-text-field number />
 ```
Convert string into number

### Bugs or Edge Cases it Helps Avoid
https://codepen.io/anon/pen/XZooPx?editors=1010

**Comment by KaelWD** [comment]
That is already part of Vue: `v-model.number="..."`

**Comment by cn-xufei** [comment]
Thanks
