### ISSUE TITLE
[Bug Report] v-select events don't provide event object

### ISSUE THREAD

**Issue by mojo2012** [vuetifyjs/vuetify#3422]
## Versions and Environment

Vuetify: 1.0.4
Vue: 2.5.13
Browsers: Firefox 58.0.2
OS: macOS 10.12.6 (16G1212)

## Steps to reproduce
I have the folowing selection box with select, change and click event listeners:
```
<v-select uuid="comp1862291722"  v-on:select="handleEvent" v-on:change="handleEvent"  v-on:click="handleEvent"
	class=""
	label="dropdown menu"
	:items="componentStates['comp1862291722'].menuItems"
	editable item-value="text"
>
</v-select>
```

Both the `select` and the `change` events are triggered and my handler method is called:
```
handleEvent: function(event) {
	var message = {
		"uuid": $(event.currentTarget).attr("uuid"),
		"event": event.type,
		"payload": event,
	};
	....
```

Unfortunately the `event` argument contains the selected value, not any of the other expected infos, like `currentTarget` or `type`

Other widgets seem to provide the event object correctly.

## Expected Behavior
The event object should be provided

Furthermore imho v-select should support standard events like click, blur etc.

**Comment by KaelWD** [comment]
v-select is a completely custom component, there is no dom event to emit. If you want additional information for your handler you can pass it in yourself: https://vuejs.org/v2/guide/events.html#Methods-in-Inline-Handlers

Blur and click should work as far as I know, create a bug report with reproduction otherwise.

**Comment by gustawdaniel** [comment]
I my opinion it is bug. Variable $event in combobox is array when it should be event because of I cant use

    @change.prevent

syntax. Error says that array with values from combobox does not have method preventDefault().

You can read about default modifiers there:

> https://vuejs.org/v2/guide/events.html#Event-Modifiers
