### ISSUE TITLE
[Bug Report] jsx v-model dosent work for switch and checkbox

### ISSUE THREAD

**Issue by andtii** [vuetifyjs/vuetify#3423]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Bind using v-model to the switch or checkbox components like `<v-switch v-model={this.isEnabled} />`

### Expected Behavior
The v-model should be set and work. It works for other components in vuetify like the dialog so there must be some differences in the v-switch and v-checkbox components.

### Actual Behavior
The v-model is not set and the components is not working as expected

### Reproduction Link
[https://github.com/andtii/vuetify-jsx-model-issue](https://github.com/andtii/vuetify-jsx-model-issue)

**Comment by andtii** [comment]
@nickmessing any idea what could go wrong here?

**Comment by KaelWD** [comment]
nickmessing/babel-plugin-jsx-v-model#10
