### ISSUE TITLE
[Feature Request] Allow the `v-btn-toggle` component to set a v-model different than the button index

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuetifyjs/vuetify#3426]
### New Functionality
With the `v-select` component, you can define the `item-text` and `item-val` props so that when selecting an `item-text` element, the v-model is set to the `item-val`.

However with the `v-btn-toggle`, there is no such feature available.
It would be great if you could pass an `items` props to `v-btn-toggle` so that when clicking a button, the v-model would be set to the given `item-val`, instead of the button index like it does now.

Check the console when clicking on [that example](https://codepen.io/AnotherLinuxUser/pen/KQbBRV?editors=1011).

### Improvements
Right now, we need to use an additional `:customValue` in order to track the value (while `:value` is currently used to select the buttons).

The workaround is a hack that makes the code harder to read.

### Bugs or Edge Cases it Helps Avoid
All the hacks to create a link between the buttons indexes and the real values to use.

**Comment by KaelWD** [comment]
`<v-btn :value="whatever">`

**Comment by KaelWD** [comment]
You can even see it in the example, the lat two here have custom button values set: https://vuetifyjs.com/en/components/buttons#example-toggle

**Comment by AlexandreBonneau** [comment]
Whoops, my bad :sweat_smile:
