### ISSUE TITLE
[Feature Request] Table Caption Support

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#3428]
### New Functionality
Offer a slot in the `v-data-table` element to allow for the creation of an HTML `table` `caption` element. This is required for accessibility purposes, i.e. screenreaders, as well as for visual identification of what a table contains. A slot would allow for complete customization of the `caption` as it can appear in different positions around the table and may need custom styling.

Right now there doesn't appear to be a way to "label" a table other than placing some text before it in the DOM.

### Improvements
n/a

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by blalan05** [comment]
Available in the 2.0 alpha
