### ISSUE TITLE
Error expansion-panel

### ISSUE THREAD

**Issue by Nightwelf** [vuetifyjs/vuetify#343]
When i add sample code i have this error:
```
 vuetify.js?e0ae:5504 Uncaught TypeError: Cannot read property 'addEventListener' of null
     at HTMLDocument.eval (eval at <anonymous> (app.js:1048), <anonymous>:5504:43)
```

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
