### ISSUE TITLE
[Bug Report] V-Text-Field Color only applies to active.

### ISSUE THREAD

**Issue by GarlandM** [vuetifyjs/vuetify#3430]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
Add:

color="colorname" 

To a <v-text-field>

### Expected Behavior
Would change resting color, as well as active.

### Actual Behavior
Changes only active color.

### Reproduction Link
[https://codepen.io/anon/pen/GQzMLO](https://codepen.io/anon/pen/GQzMLO)

### Other comments
Possible feature, allow both resting and active colors?

**Comment by johnleider** [comment]
There is no support to add a resting color. We are exploring adding a success-state in 1.1, but this is not a bug.
