### ISSUE TITLE
[Bug Report] Button with outline breaks text vertical centering

### ISSUE THREAD

**Issue by samuelcolburn** [vuetifyjs/vuetify#3433]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Make a v-btn
2. Give props == outline, small

### Expected Behavior
Text is centered vertically within the button

### Actual Behavior
Text is actually a few px lower than center.

### Reproduction Link
[https://codepen.io/smcolburn/pen/jZdXgG](https://codepen.io/smcolburn/pen/jZdXgG)

### Other comments
I played with it a fair bit and for whatever reason I can't seem to get it to center properly, adjusting the height or font-size still leaves it a few pixels off though it does improve things slightly.

**Comment by johnleider** [comment]
This is due to height inherit on `.btn__content`.

**Comment by adolfoBee** [comment]
I've noticed that text is centered vertically inside the button but a <v-icon> inside the button will be displayed at the top of the button.

**Property**: "fab",
**Results in**: icon displaying on top of the button

**Comment by KaelWD** [comment]
@adolfoBee not related, you're loading the icon CSS in the wrong order.

**Comment by adolfoBee** [comment]
@KaelWD this is the code I'm using:
<v-btn fab small class='green')'>
        <v-icon>keyboard_arrow_right</v-icon>
</v-btn>

**Comment by KaelWD** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/commit/7abf1aa1cea8dad76543f3d554c1d702e81f70cf
