### ISSUE TITLE
[Feature Request] Support v-spacer inside v-tabs as a sibling to v-tab components

### ISSUE THREAD

**Issue by bigcat** [vuetifyjs/vuetify#3434]
### New Functionality
In Vuetify 0.17 we were using a a v-spacer tag inside of tabs to push some of them to the left and some to the right.  (I know it isn't the best application of MD design principals, but it works in context).

When I upgraded our codebase to Vuetify 1.0 the v-spacer is no longer being rendered inside of the tabs.  It seems to be the re-working of the tabs has added a stricter set of options for what can be rendered inside the tab bar, which makes sense.  But I thought perhaps we could allow a layout component like v-spacer to exist as well inside of a tab bar.

### Improvements
As it stands we'll have to specifically tag each tab that floats right and figure out a CSS work-around, probably by overriding the flexbox properties, but it would be more straight-forward and less code to maintain to take advantage of the flexbox spec by adding a flexible item between the left and the right (much like is pattern on a header toolbar).

### Bugs or Edge Cases it Helps Avoid
Makes maintenance simpler for customizing layout behaviors that don't fit into the "all tabs go" left, right, centered, or fill patterns.

**Comment by KaelWD** [comment]
I thought I'd fixed this with bde89441229b2240de8fe5c8ab59e78480d16d0c but apparently not.
