### ISSUE TITLE
[Bug Report] Popover menu bound to FAB appears in wrong location the first time it appears

### ISSUE THREAD

**Issue by alex-at-rc** [vuetifyjs/vuetify#3438]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
1. Click the floating FAB in the bottom right to open the popover menu.
2. Note the location of the popover menu.
3. Click out of the menu to dismiss.
4. Click the FAB again to open the popover menu again.
5. Note the new location of the menu.

### Expected Behavior
The menu should appear off to the side of the button the first time it appears.

### Actual Behavior
The menu first appears covering the button the first time you click it; only the second and subsequent times does it appear in the proper location.

### Reproduction Link
[ https://codepen.io/anon/pen/PQLzRd]( https://codepen.io/anon/pen/PQLzRd)

**Comment by krizalid117** [comment]
Hi.
Any solution atm?

**Comment by lrstanley** [comment]
Was having the same issues as https://github.com/vuetifyjs/vuetify/issues/3732 and reporting here as that was closed as a duplicate to this, specifically when using `v-menu` with `:nudge-width`, causing the "popover" menu to go off screen on initial animation frames.

Took the example pen directly from https://vuetifyjs.com/en/components/menus (running 1.5.1, latest as of this comment), modified it to extend the width a bit more to make it easier to replicate as well as put the bottom to the right, and put it into a pen:

https://codepen.io/anon/pen/ZwqWJa

What I see is (far right being the right side of the viewport):

![image](https://user-images.githubusercontent.com/1847365/52826048-481ea280-308d-11e9-9a66-0f911bd3aae1.png)

I also see: https://github.com/vuetifyjs/vuetify/issues/6294 but that seems specific to absolute positioning and hasn't fixed these issues. I see https://github.com/vuetifyjs/vuetify/issues/6421, which looks familiar and similar to what we're looking for.

As a workaround for now, I will just not use nudge-width.

**Comment by lrstanley** [comment]
Thanks for the quick turnaround @KaelWD!

**Comment by KaelWD** [comment]
If you can call almost a year quick, sure
