### ISSUE TITLE
[Bug Report] Select input removes the wrong tags when the user removes a tag

### ISSUE THREAD

**Issue by lsapan** [vuetifyjs/vuetify#3439]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a select input with `multiple` and `tags` enabled, and an empty list of initial items. Add some tags through the UI, and try to remove a tag.

### Expected Behavior
The selected tag should be removed while the other tags are preserved.

### Actual Behavior
The exact opposite. Every single tag is removed except the selected one.

### Reproduction Link
[https://jsfiddle.net/td9hch4s/6/](https://jsfiddle.net/td9hch4s/6/)

### Other comments
The same happens when you click an "x" with `deletable-chips` enabled.

**Comment by KaelWD** [comment]
I guess that is technically a bug, but it works fine if it has a v-model: https://jsfiddle.net/wfny4muz/

**Comment by lsapan** [comment]
Whoops, looks like I misread the docs. For some reason I thought this use case used :items instead of v-model. Sorry about that!
