### ISSUE TITLE
[Bug Report] Canno't set default value for VTextField and VSelect from HTML when using value attribute and v-model directive

### ISSUE THREAD

**Issue by Melchyore** [vuetifyjs/vuetify#3444]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Create a new v-text-field or v-select element, set a value attribute with the initial value and v-model directive.

### Expected Behavior
The field should show the value of the "value" attribute.

### Actual Behavior
Value shown is the value of the v-model directive.

### Reproduction Link
[https://jsfiddle.net/r6rb0Lqz/4/](https://jsfiddle.net/r6rb0Lqz/4/)

**Comment by KaelWD** [comment]
That's how Vue works, `v-model` is shorthand for `:value="val" @input="val = $event"`
