### ISSUE TITLE
[Bug Report] potential infinite update loop detected when rendering a component within v-data-table?

### ISSUE THREAD

**Issue by githubfanster** [vuetifyjs/vuetify#3445]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
please just run the code in the reproduction link (i'm using vuetify's table with inline-editing example as a model, modifying it to conditionally change text and background color of cells in rental_duration column in my table). it's very probable i'm doing something incorrectly unknowingly so not sure it's a real bug.  i do like to understand what's going though, however, if possible.

### Expected Behavior
i'm using vuetify's table with inline-editing example as a model, modifying it to conditionally change text and background color of cells in rental_duration column in my table (original code has 100 table items, but problem can be reproduced with the 5 film data items in submitted code)

### Actual Behavior
encountered a potential infinite update loop problem in a component render function

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

### Other comments
it's very probable i'm doing something incorrectly unknowingly so not sure it's a real bug.  i do like to understand what's going on though, however, and perhaps a workaround or proper way to achieve my goal?  thanks so much for helping

**Comment by FFxSquall** [comment]
@githubfanster wrong reproduction link

**Comment by githubfanster** [comment]
the codepen submission didnt take ... here's my code ..

<!DOCTYPE html>
<html>
    <head>
        <title>Axios Get Many Demo</title>
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
        <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet">
        <script src="https://unpkg.com/vue@2.5.13/dist/vue.js"></script>
        <script src="https://unpkg.com/vuetify/dist/vuetify.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    </head>
    
    <body>
        <h2>Axios Get Many Demo</h2>
        <div id="app">
            <v-app id="inspire" >
                <v-data-table :headers="headers" :items="films">
                    <template slot="items" slot-scope="props">
                        <td>{{ props.item.film_id }}</td>
                        <td class="text-xs-right">
                            <v-edit-dialog :return-value.sync="props.item.title" lazy> {{ props.item.title }}
                                <v-text-field slot="input" label="Edit" v-model="props.item.title" single-line counter ></v-text-field>
                            </v-edit-dialog>
                        </td>
                        <td class="text-xs-right">{{ props.item.description }}</td>
                        <td class="text-xs-right" v-bind:style="durationStyle">
                            <v-edit-dialog :return-value.sync="props.item.rental_duration" large lazy persistent>
                                <div v-bind:style="durationStyle">{{ withDurationStyle(props.item.rental_duration) }}</div>
                                <div slot="input" class="mt-3 title">Update Rental Duration</div>
                                <v-text-field slot="input" 
                                        label="Edit" 
                                        v-model="props.item.rental_duration" 
                                        single-line 
                                        counter 
                                        autofocus
                                ></v-text-field>
                            </v-edit-dialog>
                        </td>
                    </template>
                    <template slot="pageText" slot-scope="{ pageStart, pageStop }">
                        From {{ pageStart }} to {{ pageStop }}
                    </template>
                </v-data-table>
            </v-app>
        </div>

        <script>
            demo = new Vue({
                el: "#app",
                data: {
                    films: [
                        { film_id: 1, title: 'title 1', description: 'description 1', rental_duration: 6 },
                        { film_id: 2, title: 'title 2', description: 'description 2', rental_duration: 3 },
                        { film_id: 3, title: 'title 3', description: 'description 3', rental_duration: 5 },
                        { film_id: 4, title: 'title 4', description: 'description 4', rental_duration: 7 },
                        { film_id: 5, title: 'title 5', description: 'description 5', rental_duration: 6 }

                    ],
                    pagination: {},
                    headers: [
                        {
                            text: 'ID',
                            align: 'right',
                            sortable: true,
                            value: 'film_id'
                        },
                        { text: 'Title', value: 'title'},
                        { text: 'Description', value: 'description'},
                        { text: 'Rental Duration', value: 'rental_duration' },

                    ],
                    lengthColor: 'black',
                    otherCriterionColor: 'white'
                },
                computed: {
                    durationStyle: function() {
                        return {
                            color: this.lengthColor,
                            background: this.otherCriterionColor
                        }
                    }

                },
                methods: {
                    withDurationStyle: function(val) {
                        //rd is rental_duration
                        //rd = parseInt(val)
                        rd = val
                        //console.log(rd)
                        if (rd <= 3) {
                            this.lengthColor = 'brown'
                        } else if (rd > 3 && rd <= 6) {
                            this.lengthColor = 'blue'
                        } else {
                            this.lengthColor = 'red'
                        }
                        this.otherCriterionColor = 'yellow'
                        return val
                    }
                }
            });
        </script>

    </body>
</html>

**Comment by githubfanster** [comment]
i've never used codepen. how to save and produce proper submission? do i need to sign up?

**Comment by githubfanster** [comment]
ok hope this link works

https://codepen.io/anon/pen/KQEEXY?&editors=101

**Comment by nekosaur** [comment]
You should avoid modifying component state inside templating tags.

https://codepen.io/anon/pen/MQxRbj

**Comment by githubfanster** [comment]
thank you! i learned something! :-)
