### ISSUE TITLE
[Feature Request] Allow to overwrite default transition of <v-menu> by wrapping it with <transition>

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3446]
### New Functionality
While some components like `<v-speed-dial>` allow you to apply custom (i.e. Animated.CSS) transition by wrapping it with `<transition>` e.g.:

```
  <transition 
    enter-active-class="animated slideInRight" 
    leave-active-class="animated slideOutRight"
  >
      <v-speed-dial>
      ...
      </v-speed-dial>
  </transition>
```

When you do the same thing with `v-menu` component , it still uses default `menu-transition`

### Improvements
More consistency and choice

### Bugs or Edge Cases it Helps Avoid
none

**Comment by johnleider** [comment]
You should be using the **transition** property to modify their transition.
