### ISSUE TITLE
enhancement for async data-tables  

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#345]
To provide better handling with async data we need following fields to improve on data-tables:

- [ ] emit/watch sort change
- [ ] emit/watch row-per-page 
- [ ] bind total-number-of-items to a property
- [ ] bind loading to a property

**Comment by Sarpedion** [comment]
I'd like to offer a couple of suggestions. 

1. Emitting paging event, with rows-per-page and current page parameters, would enable to fully customize async loading (use case: fetching a certain page from backend, while using Elasticsearch, based on current page and rows-per-page prop)

2. Visual indicator that async loading is in progress. As far as I know, this feature is not defined by Material Design standards, but would nevertheless improve user experience while using async loading. 
Example of such feature would be placing indeterminate linear progress bar between header row and first row.
For example:
![image](https://cloud.githubusercontent.com/assets/16826299/25384995/b58813e8-29c2-11e7-9a94-dc5ed3b7afaa.png)

**Comment by nekosaur** [comment]
Addressed in #446
