### ISSUE TITLE
[Feature Request] Add an `expandable` property to `v-expansion-panel-content`

### ISSUE THREAD

**Issue by HemanthGowda** [vuetifyjs/vuetify#3450]
### New Functionality
Today, all items in the expansion-panel are expandable even though some items do not have any description or any content to show on expand.

Expected behaviour is to not allow user to expand when there is no content to show. Right way to achieve this is by providing a expandable property. So that we can set this property depending on whether the item has description or not.

By default the `expandable` property value will be `true` so that we don't break any existing behaviour.
On setting `expandable=false` we hide expandable icon and deregister click event on item.

### Improvements
This improves the user experience of the applications. This will give clear idea to user that there is no content in particular item.

### Bugs or Edge Cases it Helps Avoid
The header icon indicates that there is some content even though there is nothing to show. Which cause confusion in user that there might be something wrong.

**Comment by nekosaur** [comment]
Not sure if this is a big enough use-case to consider. By their very nature, expansion panels hide some kind of content. If there is no content, why have an expansion panel?

In what scenario would you want to have an expansion panel without content?

**Comment by HemanthGowda** [comment]
@nekosaur I understand that this is not a big enough use-case for static websites. But it matters when you are using this for dynamic websites where you don't know whether all item's have content(description) to show or not.

**Comment by nekosaur** [comment]
I'm just saying if there is no content, why render the expansion panel at all?

**Comment by nekosaur** [comment]
If you could illustrate your use case with a codepen that would be great.

**Comment by HemanthGowda** [comment]
@nekosaur Here is an example. https://codepen.io/HemanthGowda/pen/MVgMMQ

For example, I have list of categories which may or may not have sub categories. 
When there are no sub categories (`children`), I don't want to show expansion icon and i don't want to expand a blank view on click. 
Check `Category 3` and `Category 6` in this example.

To achieve this kind of scenarios, I thought we can introduce a `expandable` property which will be set depending on whether the category has children or not.

**Assume the data in this example is returned by API.**

**Comment by jacekkarczmarczyk** [comment]
I'd call it "disabled" as it should be shown as disabled (otherwise it could be unclear why it doesn't open)

Not saying that this feature wouldn't be useful but maybe in your case it's enough to hide empty categories?

**Comment by KaelWD** [comment]
Something I've done in a similar scenario is just show an empty state: https://codepen.io/anon/pen/MVWgoW?editors=1010

**Comment by HemanthGowda** [comment]
@KaelWD That's is what i've done in my case right now. 
But i still think it is reasonable use case to not allow user to expand when there is no content to show.
