### ISSUE TITLE
Colors can only be numbers or strings, recieved Object instead

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify#3451]
I tried using the latest vuetify stable 
v 1.0.4

Before in 0.17 everything is working fine with theme

```
import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify, {
  theme: {
    primary: '#121212', // a color that is not in the material colors palette
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: colors.teal.lighten1,
    warning: colors.amber,
    error: colors.deepOrange.accent4,
    success: colors.green.accent3
  }
})

```
But then it just squack this error
Colors can only be numbers or strings, recieved Object instead

**Comment by codeitlikemiley** [comment]
nevermind ive fixed it...

```
Vue.use(Vuetify, {
  theme: {
    primary: String(colors.red.lighten2), // a color that is not in the material colors palette
    accent: String(colors.grey.darken3),
    secondary: String(colors.amber.darken3),
    info: String(colors.teal.lighten1),
    warning: String(colors.amber),
    error: String(colors.deepOrange.accent4),
    success: String(colors.green.accent3)
  }
})

```

**Comment by KaelWD** [comment]
> `warning: colors.amber`

Use `colors.amber.base`

**Comment by rwuttke** [comment]
Would be great if the word recieved was spelled as received.

**Comment by KaelWD** [comment]
soz fam, english is hard ok

feel free to PR a correction

**Comment by rwuttke** [comment]
English is hard, is a damn understatement. Sorry, wasn't trying to be rude, just pointing it out.

**Comment by Shadomax** [comment]
I am facing the same issue. i am using nuxt.js with vuetify version 1.4.0
import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify, {
  theme: {
    primary: '#121212', // a color that is not in the material colors palette
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: colors.teal.lighten1,
    warning: colors.amber,
    error: colors.deepOrange.accent4,
    success: colors.green.accent3
  }
})

i get no errors but the primary, secondary, info colors don't work

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
