### ISSUE TITLE
[Bug Report] Bottom navigation buttons have different colored padding on active state

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3452]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Add bottom navigation component.

### Expected Behavior
When clicking and holding button pressed its hover color stays uniform.

### Actual Behavior
Holding bottom navigation button pressed shows different colored (lighter) top and bottom padding.
![bottom-nav](https://user-images.githubusercontent.com/79141/36935948-317ebe0e-1f07-11e8-85e3-5ccfc862105a.png)

### Reproduction Link
[https://codepen.io/anon/pen/EQJQVR?&editors=101](https://codepen.io/anon/pen/EQJQVR?&editors=101)

**Comment by mmm8955405** [comment]
I encountered the same problem.     And do not know how to control, the activation state of the navigation bar, such as clicking the second button, but want the first button is active
