### ISSUE TITLE
[Feature Request] Some simple way to disable transition

### ISSUE THREAD

**Issue by deflexor** [vuetifyjs/vuetify#3453]
### New Functionality
Disable transition animations of some Vuetify components

### Improvements
no known workarounds

### Bugs or Edge Cases it Helps Avoid
Will make appplication faster and more responsive

**Comment by johnleider** [comment]
Your request is very vague. What components?

**Comment by deflexor** [comment]
Here is example:

http://jsbin.com/milutorumu/edit?html,js,output

You can try and click "map" button few times and you'll see that sometimes map is painted in half width because
it calculates its size while animation still runs. Currently I see only 2 ways to fix it: either disable animation or subscribe to drawer's `transitionend` event and recalculate map dimensions inside it. But none of them available now.

**Comment by kaliatech** [comment]
I'm still debugging this, but I think another example might be the progress components. I was using `v-progress-linear` to display audio playback progress from a `requestAnimationFrame` handler.  The progress often seems choppy and never completes to 100%, I think because the `slide-x-transition` transition is to slow for this purpose. Afaict, there is no way to disable or configure the transition.  It seems valid that some use-cases of progress components will require immediate updates without animated transitions.

**Comment by andrewharvey** [comment]
https://codepen.io/andrewharvey/pen/KxZmex?editors=1111

I `@transitionend` doesn't fire as it's not the navigation drawer that's transitioning it's all the other content.

**Comment by blackboxx** [comment]
Confirm feature request

**Comment by SaleCar** [comment]
> Your request is very vague. What components?

I want to disable transition for snackbar but there is no way to do it. I'm using it as Loading popup so must be quick.

**Comment by johnleider** [comment]
> https://codepen.io/andrewharvey/pen/KxZmex?editors=1111
> 
> `@transitionend` doesn't fire as it's not the navigation drawer that's transitioning it's all the other content.

This is unrelated and has been fixed since v1.1 https://codepen.io/johnjleider/pen/JQEprm?editors=1111

> I think another example might be the progress components. ...
> 
> This jsfiddle shows the issue:
> 
> * https://jsfiddle.net/kaliatech/L92t9tvz/

This is slightly unrelated but is something I'll resolve for v2.0

---

@deflexor The provided example no longer works. With regards to transitions, any component that supports defining one can be disabled. If you have specific components that have internals elements with transitions that cause visual anomalies (such as the example above), please provide me with additional information, otherwise I'll consider this resolved.

**Comment by johnleider** [comment]
@kaliatech Could you create a new issue for your specific issue. For now the workaround would be to disable the transition on the element:

```
<style lang="sass">
  .my-progress-linear .v-progress-linear__determinate
    transition: none !important
</style>
```

**Comment by kaliatech** [comment]
@johnleider The visual issue specific to progress components has been recreated and updated in #7705. I believe this issue can be closed.

**Comment by johnleider** [comment]
@deflexor could you update your reproduction? The link is dead.

**Comment by mitar** [comment]
#7705 has been closed with wontfix. But I agree that disabling transition in an easy way on progress bar would be useful. I was just hit with the same issue.

**Comment by oscar6echo** [comment]
Not just progress bar. It would be critical on sliders too.  
If the slider is synced to a process that moves fast, or worse loops, then the slider is seriously lagging and choppy too. I would argue this is a case where less (transitions) is more (useful).

**Comment by EricRenault** [comment]
For people looking for an answer on disabling the v-slider animation, I managed to do it with this snippet in CSS (Vuetify v2.3.9):

.v-slider__thumb-container, .v-slider__track-background, .v-slider__track-fill {
      transition: none !important;
}

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by MetRonnie** [comment]
I think this is mostly possible in Vuetify 3:
```js
// src/plugins/vuetify.js
import { createVuetify } from 'vuetify'

export default createVuetify({
  defaults: {
    global: {
      transition: false,
      ripple: false,
    },
  },
})
```

See https://vuetifyjs.com/en/features/global-configuration/#setup

N.B. some things are not affected, like tooltip animations

**Comment by 4698to** [comment]
> I think this is mostly possible in Vuetify 3:我认为这在 Vuetify 3 中是可能的：
> 
> // src/plugins/vuetify.js
> import { createVuetify } from 'vuetify'
> 
> export default createVuetify({
>   defaults: {
>     global: {
>       transition: 'no',
>       ripple: false,
>     },
>   },
> })
> See https://vuetifyjs.com/en/features/global-configuration/#setup请访问 https://vuetifyjs.com/en/features/global-configuration/#setup

This global setting cannot remove the animation effect of v-slider

**Comment by J-Sek** [comment]
@4698to , try `* { transition: none !important; }`
