### ISSUE TITLE
[Bug Report] v-select shouldn't emit @change unless the value has actually changed

### ISSUE THREAD

**Issue by Hellek** [vuetifyjs/vuetify#3457]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Yandex 18.1.1.835
**OS:** Windows 10

### Steps to reproduce
```html
<v-select
	label="Status"
	v-model="localSet.ordStatus"
	:items="selectOptions.ordStatus"
	@change="updateParent()"
/>
```

1. Click on `<v-select>`
2. Choose same option (don't change actually)
3. Get @change event

### Expected Behavior
Emit change just on really option change

### Actual Behavior
Emit change event always

### Reproduction Link
[https://jsfiddle.net/bdahgk7p/2/](https://jsfiddle.net/bdahgk7p/2/)

**Comment by KaelWD** [comment]
Please provide a valid reproduction. That link doesn't actually run anything.

**Comment by Hellek** [comment]
https://codepen.io/hellek/pen/EQBjBd try choose same options few times. It would not emit change event
