### ISSUE TITLE
[Bug Report] Toolbar items margin inconsistencies on mobile

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3458]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Add toolbar with title and action icon on right side. Open on mobile or resize window to mobile size (e.g. 320px width).

### Expected Behavior
On mobile screen title should have margin-left: 16px and action icon margin-right: 8px. If there's only title element - it has correct margin-left value.

### Actual Behavior
Title has margin-left: 24px and action icon has margin-right: 17px.
![toolbar](https://user-images.githubusercontent.com/79141/36944061-4515703e-1f9d-11e8-9238-216ac37ebcc0.png)

### Reproduction Link
[https://codepen.io/anon/pen/QQPXLQ?editors=1000](https://codepen.io/anon/pen/QQPXLQ?editors=1000)

### Other comments
Problem become apparent when app has one view with title and icons and another view with title only.

**Comment by KaelWD** [comment]
This has been fixed in 1.1: https://codepen.io/anon/pen/OEQXNd?editors=1000
