### ISSUE TITLE
[Feature Request] Disable entry transition for first slide

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3459]
### New Functionality
When carousel is displayed first time, first slide entry is animated. Would be nice to have option that disables this first time animation.

### Improvements
Currently I have no idea how to work around this.

### Bugs or Edge Cases it Helps Avoid
None, it's an UX improvement.

**Comment by johnleider** [comment]
I think this might be a regression of an old issue.

**Comment by KaelWD** [comment]
Seems to be fixed since the v-window refactor.
