### ISSUE TITLE
feature request header / footer fixed on data-tables

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#346]
As a nice add-on it would be great to support fixed header / fixed footer on data-tables. Similar like this plugin for the Angular data-tables:
http://codepen.io/anon/pen/qbLaMb?editors=1010

**Comment by johnleider** [comment]
Looking at that codepen, they actually just nest tables. I think that can be done by the developer if they truly want it, but it's not something we are going to put in the core.

**Comment by dohomi** [comment]
@johnleider maybe we can have an option to make the `tbody` scrollable on a `fixed-height` option? This would be basically the main functionality needed for making this to work. It was just an idea, I think most of the data-tables need to leave the header on top instead that it scrolls away.. at least thats my point of view. Nothing is more annoying on a big table that you need to scroll up to see which column you are actually looking at.. 
I agree that its something the dev can take care of but maybe something for future enhancement

**Comment by JacksMyth** [comment]
+1
This is a cool feature, adds a lot of polish for little reward

**Comment by stecava82** [comment]
👍   Very useful feature :-)

**Comment by JacksMyth** [comment]
@stecava82 there's a new issue for this here https://github.com/vuetifyjs/vuetify/issues/1547 (unsure how to link the two issues)

**Comment by ederluisf** [comment]
Very useful feature :-)

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by zhanghuanchong** [comment]
+1
Fixed header or/and columns are better. 😆

**Comment by nekosaur** [comment]
Please do not comment on closed issues. There is an open issue for this feature request here https://github.com/vuetifyjs/vuetify/issues/1547
