### ISSUE TITLE
[Bug Report] Black overlay above toolbar when opening sidebar

### ISSUE THREAD

**Issue by preeteshjain** [vuetifyjs/vuetify#3461]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Linux x86_64

### Steps to reproduce
* Resize the window to `1100 x 800` using Chrome Developer Tools.
* Now try opening the sidebar from the Hamburger menu.

### Expected Behavior
Notice the black overlay above the toolbar. That's only supposed to happen for mobile devices. It shouldn't happen when the toolbar title is visible at least. The sidebar should take the full height instead.

### Actual Behavior
There's a black overlay above the toolbar.

### Reproduction Link
[https://codepen.io/johnjleider/pen/EQOYVV](https://codepen.io/johnjleider/pen/EQOYVV)

### Other comments
If you can't reproduce the issue, see this GIF:

![GIF](https://i.imgur.com/QfqfrhQ.gif)

**Comment by johnleider** [comment]
You have incorrect logic for the breakpoint conditionals.

https://codepen.io/johnjleider/pen/LQogqv

**Comment by preeteshjain** [comment]
@johnleider Wait, I didn't change anything. It was your pen only. I got it from this page: https://vuetifyjs.com/en/examples/layouts/googleContacts

Can you tell me what did you change? Its hard to compare both the pens.

**Comment by preeteshjain** [comment]
And I think you should update the code here as well: https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/layouts/googleContacts.vue

So people in future get this right, and won't report it again. 😅

**Comment by preeteshjain** [comment]
Thanks man! Got it.
