### ISSUE TITLE
[Feature Request] Integrate custom inputs with vuetify forms and validations

### ISSUE THREAD

**Issue by eidellev** [vuetifyjs/vuetify#3464]
### New Functionality
I am currently trying to implement a signature pad that will integrate with Vuetify forms, allowing to ensure the user signs before proceeding.

### Improvements
Currently I have to validate the signature pad separately from the rest of the form

### Bugs or Edge Cases it Helps Avoid
this will simplify creating forms with custom inputs

**Comment by KaelWD** [comment]
Not sure how we're supposed to be able to provide anything for that, but you can simply copy the interface of the other inputs: 

```ts
interface Validatable {
  // data:
  errorBucket: Array<false | string>
  shouldValidate: boolean

  // methods:
  validate: (force?: boolean = false, value?: any) => boolean
  reset: () => void
}
```

**Comment by eidellev** [comment]
@KaelWD Thanks! Works like a charm 😄

**Comment by KaelWD** [comment]
Closing as resolved, there's nothing actionable in this issue as far as I can tell.
