### ISSUE TITLE
[Bug Report] v-data-table search option doesn't work when using the "Paginate and sort server-side" example from vuetify website.

### ISSUE THREAD

**Issue by Riotsmurf** [vuetifyjs/vuetify#3475]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
Use the default example from the vuetifyjs website for v-data-table "Paginate and sort server-side"
Then add the search bar above using the example "Search with custom no-results slot" only taking the search field from the example.

### Expected Behavior
Searching this table should hide items not related to the search.

### Actual Behavior
It shows a loading bar then does nothing.

### Reproduction Link
[https://codepen.io/Riotsmurf/pen/RQzWgR](https://codepen.io/Riotsmurf/pen/RQzWgR)

### Other comments
I am wondering if i have to create my own search function or that this is a bug. You can see in my code pen that everything in this is from the vuetifyjs site copied exactly and not modified.

**Comment by plokko** [comment]
If you paginate/sort server-side you also need to filter server side:
the server does return a fraction of the whole dataset so filtering on just a fraction of the data is useless, just add the search filter in the request and implement it server-side.

**Comment by nekosaur** [comment]
What @plokko said
