### ISSUE TITLE
[Bug Report] Bug: Tooltip doesnt work with v-btn-toggle

### ISSUE THREAD

**Issue by takotuesday** [vuetifyjs/vuetify#3477]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Wrap a btn-toggle in a tooltip

### Expected Behavior
button and tooltip display properly

### Actual Behavior
button is not rendered

### Reproduction Link
[https://codepen.io/anon/pen/bLPBQe?&editors=100](https://codepen.io/anon/pen/bLPBQe?&editors=100)

### Other comments
Not sure if this is related to https://github.com/vuetifyjs/vuetify/issues/3107 but it seems tooltip unfortunately *only* works with plain text or buttons.

**Comment by johnleider** [comment]
It's not rendered because you didn't add the activator slot.

https://codepen.io/johnjleider/pen/ddBQqY?&editors=100
