### ISSUE TITLE
Select controls in expandable lists get cut off

### ISSUE THREAD

**Issue by rzb** [vuetifyjs/vuetify#348]
I'm not sure if I'm misusing the lists component, but it'd be great if we could use form components such as selects inside expandable lists. You can see something similar being used in google chrome's settings with material enabled.

Currently it's not possible because the .list element hides the select box due to having overflow:hidden. And setting to visible is not an option because then the content shows up too early (ie before the animation completes).

If it was possible to detect when the animation ends, setting overflow:visible after that could fix it.

[pen](http://codepen.io/rzb/pen/vmYZNN)

**Comment by rzb** [comment]
The same happens with the ExpansionPanel component.

**Comment by rzb** [comment]
I tried the master branch to see the fix and it looks like the changes have brought up the collateral damage I mentioned before: the content shows up too early and overlaps the other list groups. I ended up using the expansion panel component and solved the former issue with the following css rule:
```
.expansion-panel__header--active + .expansion-panel__body:not(.v-enter-active):not(.v-leave-active) {
        overflow: visible;
}
```
that way overflow is never visible during the transition. I haven't checked the list component but if the markup allows it you could apply a similar css-only fix.

**Comment by johnleider** [comment]
It is actually fixed, I just borked the build process so you are unable to get the new dist files
