### ISSUE TITLE
[Feature Request] Datatable test without td font-size and font-weight

### ISSUE THREAD

**Issue by funkybg** [vuetifyjs/vuetify#3480]
### New Functionality
Optimize datatable rendering. Locally i've gotten around 50% improvement in pen 2 compared to pen 1
pen 1: https://codepen.io/anon/pen/PQrgpQ (font-size and font-weight on td level)
pen 2: https://codepen.io/anon/pen/KQjYXY (font-size and font-weight on table level)

### Improvements
There is no workaround, overriding the styles cannot achieve the same result

### Bugs or Edge Cases it Helps Avoid
Slow(er) rendering of datatables

**Comment by nekosaur** [comment]
And how are you measuring the performance?

**Comment by funkybg** [comment]
Chrome dev tools -> performance tab
1. page reload
2. navigating to the page (n/a on the pen)
3. update the number of rows per page property to force the pen to re-render the table

**Comment by KaelWD** [comment]
There's no measurable difference for me, sometimes the 2nd one is even slightly slower. Data tables have **much** bigger problems than an extra 5ms of style calculation. 

@funkybg numbers would be nice, and maybe a PR so we can see what's actually been changed
