### ISSUE TITLE
[Bug Report] theme not applied if using vue-meta

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#3482]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Use the official `vue-meta` plugin.

### Expected Behavior
Default or custom theme is applied.

### Actual Behavior
No theme is applied.

### Reproduction Link
[https://codepen.io/SeregPie/pen/gvVwGo](https://codepen.io/SeregPie/pen/gvVwGo)

**Comment by pSchaub** [comment]
I have the same bug on my nuxt project. It only happens sometimes. I think it's some type of race condition bug.
