### ISSUE TITLE
[Bug Report] v-text-field / v-model binding broken 1.0.5

### ISSUE THREAD

**Issue by djneely** [vuetifyjs/vuetify#3483]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a v-text-field and bind it to a v-model. On 'input' modify that v-model. The text field still shows the value being typed not 'cleaned' by the input method you're calling.

Same issue as was experienced a while back via this URL.

https://github.com/vuetifyjs/vuetify/issues/1726

### Expected Behavior
On 'cleaning/processing' of the input setting the v-model value should set the value shown.

### Actual Behavior
You see what you type not the value of the v-model.

### Reproduction Link
[https://codepen.io/djneely/pen/WMVRrR?editors=1111](https://codepen.io/djneely/pen/WMVRrR?editors=1111)

**Comment by johnleider** [comment]
You shouldn't use model if you are going to manually modify the input. If you want to use v-model, you need to wait for the next tick.

https://codepen.io/johnjleider/pen/YemQeP?editors=1111

**Comment by djneely** [comment]
What is the accepted way of monitoring, limiting, and formatting the text input of v-text-field if you can't use the v-model for doing it? The example provided using ':value' also does not accomplish the need. Seems to be a very common need to limit and format input text outside of the limitations of 'mask'.

Maybe this is more of a feature request?

**Comment by johnleider** [comment]
It has nothing to do with Vuetify and everything to do with data binding and Vue.
