### ISSUE TITLE
[Bug Report] Scrolling techniques broken

### ISSUE THREAD

**Issue by smiller171** [vuetifyjs/vuetify#3484]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 65.0.3325.106
**OS:** Mac OS 10.13.3

### Steps to reproduce
Toolbars in 0.15.7 allowed scrolling one toolbar away while aligning a lower toolbar with the top of the screen. This seems to have been broken with 1.0. I tried 0.16 and 0.17 but they had other bugs

Working: (0.15.7) https://codepen.io/smiller171/pen/qxeRmv
Broken: (1.0.5) https://codepen.io/smiller171/pen/YemNYP

### Expected Behavior
Expect to be able to scroll down and have toolbar slide away while keeping tab bar

### Actual Behavior
stuck with either scrolling toolbar and tab bar, or keeping both on screen

### Reproduction Link
[https://codepen.io/smiller171/pen/YemNYP](https://codepen.io/smiller171/pen/YemNYP)

**Comment by KaelWD** [comment]
I'd be doing that with the extension slot instead, but there doesn't seem to be a way to keep that on the screen either: https://codepen.io/anon/pen/gvVJrd

**Comment by smiller171** [comment]
@KaelWD I've been trying using the native tabs component with no luck. This example is one I found on CodePen that was working on 0.15.5 and I was able to update it as far as 0.15.7 before things started breaking. 0.16 and 0.17 just rendered completely wrong, and 1.0+ doesn't scroll the toolbars correctly.

**Comment by smiller171** [comment]
@johnleider That doesn't seem to have fixed the issue for me. Using Vuetify 1.0.8 with Nuxt.

**Comment by johnleider** [comment]
This ended up being pulled from the PATCH release for semver purposes. It is now in dev and will release with v1.1

**Comment by smiller171** [comment]
Thanks @johnleider. Is there a version in npm with these changes or do I need to point my package.json at this repo?

**Comment by johnleider** [comment]
You'd have to locally build Vuetify and link it to your package.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
