### ISSUE TITLE
[Bug Report] very long text in cards doesn't work on IE

### ISSUE THREAD

**Issue by asarimbekov** [vuetifyjs/vuetify#3495]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 8.1

### Steps to reproduce
run the codepen

### Expected Behavior
should work

### Actual Behavior
doesn't work on IE, works in chrome

### Reproduction Link
[https://codepen.io/asarimbekov/pen/ZxzzJW](https://codepen.io/asarimbekov/pen/ZxzzJW)

**Comment by nekosaur** [comment]
Putting `max-width: 100%` on the card solves the problem in IE11, but someone more well versed in CSS needs to determine if that's an acceptable solution.

Also your codepen has a missing `</div>` tag in `<v-card-title>`

**Comment by jokeronaldo** [comment]
IE is dead

**Comment by Mikilll94** [comment]
Is it going to be solved?

**Comment by avengerweb** [comment]
@asarimbekov can you provide browser version (IE) and screenshots.

IE11 works correctly after fix markup (you are didn't close one div `</div>`) codepen not working in IE11, so I tested it in on latest version from source.

Also in your markup you put text into `v-card-title` element

**Comment by Mikilll94** [comment]
It seems like CodePen is not supporting IE11. Is there any way to preview app with Vuetify on IE11?

**Comment by johnleider** [comment]
This has been resolved as of v2.

**Comment by Mikilll94** [comment]
@johnleider 

Hey,
this is a very annoying bug. Can we expect a fix for Vuetify 1.5?
