### ISSUE TITLE
[Bug Report] Performance issues with "menuable" components (Layout Trashing)

### ISSUE THREAD

**Issue by Toilal** [vuetifyjs/vuetify#3497]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Linux x86_64

### Steps to reproduce
- Open the reproduction link
- Click the switch to mount 500 instances of `v-select` components.

### Expected Behavior
Components should be displayed instantly.

### Actual Behavior
Browser is freezing for some time. It's worse in a real application where others components may be displayed. In my actual app, I spend about 8 seconds rendering a page because of this issue.

### Reproduction Link
[https://codepen.io/Toilal/pen/KoPKjo](https://codepen.io/Toilal/pen/KoPKjo)

### Other comments
This freeze is caused by reading `window.pageYOffset` inside `beforeMount` hook of menuable mixin. This property access causes "layout trashing", as [stated in this doc](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

Others components parts of vuetify may suffer the same kind of issue.

Maybe we could avoid accessing some of `window` and `document` properties by using application-wide window and scroll listener to store those values globally as soon as they change. Components could then access those stored values instead of directly reading `window` properties, this should help avoid layout trashing.

**Comment by KaelWD** [comment]
Ideally the menu shouldn't even exist until it's actually needed, and I don't know why it even needs to know the window scroll position before being activated. 

![image](https://user-images.githubusercontent.com/16421948/37103262-e8bb077a-227d-11e8-9300-97ee1594f389.png)

**Comment by Toilal** [comment]
I've created a pull request that fix the issue.
