### ISSUE TITLE
[Bug Report] Border on navigation-drawer missing with scrollbar

### ISSUE THREAD

**Issue by swunderlich** [vuetifyjs/vuetify#3498]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Or Go to https://vuetifyjs.com/en/components/alerts and scroll up in the drawer

### Expected Behavior
Border should be displayed all the time

### Actual Behavior
Border ends after content which was visible on load

### Reproduction Link
[https://jsfiddle.net/kLtkzbxk/51/](https://jsfiddle.net/kLtkzbxk/51/)

**Comment by kaaposc** [comment]
One way to extend the border is to wrap it in a `position: relative` container, like this:
```
--- VNavigationDrawer.orig.ts	2019-05-31 18:54:57.245675040 +0300
+++ VNavigationDrawer.ts	2019-05-31 19:01:59.088827659 +0300
@@ -349,9 +349,19 @@
       }
     }
 
+    const wrapperStyle = {
+      style: {
+        position: 'relative',
+        height: 'auto',
+        minHeight: '100%'
+      }
+    }
+
     return h('aside', data, [
-      this.$slots.default,
-      h('div', { 'class': 'v-navigation-drawer__border' })
+      h('div', wrapperStyle, [
+        this.$slots.default,
+        h('div', { 'class': 'v-navigation-drawer__border' })
+      ])
     ])
   }
 })
```
