### ISSUE TITLE
[Feature Request] Allow VSelect-Combobox to use arrow-keyed dropdown selection on tab press

### ISSUE THREAD

**Issue by whatjakecodes** [vuetifyjs/vuetify#3500]
### New Functionality
Allow user to move to keep their combobox dropdown selection by pressing the tab key when inside a VSelect/Combobox dropdown menu. Currently, when the user has arrow keyed to a dropdown selection, and then hits TAB key, they keep their current input. I want the highlighted item in the dropdown to be kept.

### Improvements
Some apps have users who want to fill out input forms as fast as possible, and they navigate with the tab key. With a combobox, they may type some input, arrow down to a selection, hit the enter key to get their selection, and then hit the tab key. If they only had to hit the tab key, they could skip the enter key press and save some time.

### Bugs or Edge Cases it Helps Avoid
Inconsistent behavior. The 'autocomplete' style of VSelect supports tab press using the selection, and combobox does not.

**Comment by whatjakecodes** [comment]
Relevant code snippet below (vuetify/src/components/VSelect/mixins/select-autocomplete.js). The `e.preventDefault()` prevents the next input from being focused, I believe.

```
      if (this.menuIsActive) {
        // Reset the list index if searching
        this.searchValue && this.$nextTick(() => setTimeout(this.resetMenuIndex, 0))

        e.preventDefault()
        this.selectListTile(menuIndex)
      }
```

**Comment by whatjakecodes** [comment]
On further analysis, I think this issue is misleading so I updated the original issue to be more about combobox.

I am actually looking to allow Comboboxes to use the dropdown-menu's selection when a user has arrow keyed to a selection, and then hit the Tab key. The 'autocomplete' style of VSelect has this behavior, but combobox does NOT.

**Comment by bad4iz** [comment]
this is a duplicate - [a similar problem](https://github.com/vuetifyjs/vuetify/issues/3341)
