### ISSUE TITLE
[Bug Report] CSS not working in typescript project

### ISSUE THREAD

**Issue by Aranir** [vuetifyjs/vuetify#3504]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Mac OS 10.13

### Steps to reproduce
Simply clone the project from github and then run:

`npm run dev`

Look at the site and observe that the css is not fully applied.

### Expected Behavior
The success button (as an example) is displayed in green.

### Actual Behavior
Sucess button is displayed in plain white.

### Reproduction Link
[https://github.com/Aranir/vue-vuetify-typescript-starter](https://github.com/Aranir/vue-vuetify-typescript-starter)

### Other comments
I'm not sure if its because of typescript, the webpack config or something else. I tried to follow the getting started section, and some CSS is loaded but it seems not everything is applied.

Any help of what I might have missed is appreciated.

**Comment by KaelWD** [comment]
The `v-app` component **must** be used for proper styling: https://vuetifyjs.com/en/getting-started/quick-start
