### ISSUE TITLE
[Feature Request] Add Height Attribute to Carousel

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#3508]
### New Functionality
I think its better we can customize the height of carousel via attribute. Currently I just add inline style manually.

### Improvements
This will allow us to make the carousel more flexible according to its functionality in our website.

### Bugs or Edge Cases it Helps Avoid
Nothing will be break I think.

**Comment by johnleider** [comment]
This is resolved in v1.3
