### ISSUE TITLE
[Feature Request] Specify a target element for goTo

### ISSUE THREAD

**Issue by Kelketek** [vuetifyjs/vuetify#3510]
### New Functionality
Currently it is not possible to scroll a full screen dialog, as one might want to do when validating a form before submission. If the goTo function could be handed an element to scroll (as an example) it might be possible to enable it to scroll in this case.

Here's an example where it would be nice if it worked: https://codepen.io/anon/pen/bvGrja

### Improvements
Right now one has to find the proper offsets and scroll the particular div they're working with, rather than using goTo, which scrolls the entire document. In the case of a fixed full screen dialog, all elements are currently 'on screen' even when scrolled out of view since they're subelements of the fixed element.

### Bugs or Edge Cases it Helps Avoid
The code for determining where and how to scroll can get rather complicated when rolling it on one's own.

**Comment by bschulz87** [comment]
Using vue-scrollto target .dialog--fullscreen as the container: 
v-scroll-to="{ el: '#top', container: '.dialog--fullscreen' }"

**Comment by johnleider** [comment]
This is being removed from milestones until @zaken has time to finish

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/5833

**Comment by quantumcat1** [comment]
If anyone else has trouble with this, using plain JS works: use getElementById and scrollIntoView(). Every single vue way I could find would only scroll the main page behind the dialog, not the dialog itself. But plain JS did the job.

**Comment by KaelWD** [comment]
```js
this.$vuetify.goTo('selector', { container: 'selector-of-scrollable-element })
```
