### ISSUE TITLE
[Bug Report] Datatable pagination.sync not syncing properly

### ISSUE THREAD

**Issue by causingh** [vuetifyjs/vuetify#3511]
Versions and Environment
Vuetify: 1.0.5
Vue: 2.5.13
Browsers: Chrome  64.0.3282.140
OS: Ubuntu 16.04 x64

Steps to reproduce
In the CodePen link, type 19 in the search field provided 

Expected Behavior
The pagination should contain only 1 page which reflects the table row count.

Actual Behavior
The pagination is not updating based on the actual table results, pagination.sync data also is not updated.

Reproduction Link
https://codepen.io/anon/pen/pLoaYv?editors=1010

**Comment by Elrinth** [comment]
Unsure if the is the correct issue to report on. But I'm also getting problems with the pagination. It won't show 1-10 of 523523 when I do filtering. I am using external data fetched from a server.

**Comment by johnleider** [comment]
Please do not comment on resolved issues. If you are having a problem, please create an issue with https://issues.vuetifyjs.com
