### ISSUE TITLE
[Bug Report] Sidebar menu manually expand

### ISSUE THREAD

**Issue by luckyboy07** [vuetifyjs/vuetify#3512]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
add two menus from "adding new layer" button,(eg shape, image or video)
click  1 menu to expand,

### Expected Behavior
when clicking the second menu the 1st menu will close.

### Actual Behavior
when clicking the second menu the 1st menu will not close.

### Reproduction Link
[My sample code](https://codepen.io/luckyboy07/pen/jzOzRB)

**Comment by KaelWD** [comment]
Works fine for me: 
![2018-03-09_18-41-59](https://user-images.githubusercontent.com/16421948/37196103-9803fda8-23c9-11e8-8b2c-1058e7f427a8.gif)

Your pen also has several JS errors

**Comment by luckyboy07** [comment]
@KaelWD  ignore the minor error , i mean how can we expand two of the sidebar menu without closing the other?

**Comment by KaelWD** [comment]
1. You should have said that in the issue
2. That is intended behaviour, so this should have been a feature request, not a bug report
3. It's already possible with the `expand` prop, which you would know if you'd read the documentation

**Comment by luckyboy07** [comment]
okay got it sorry for the trouble , thanks for the reply anyway..
