### ISSUE TITLE
[Feature Request] Better Scaling or Positioning Control for Jumbotron and Parallax Image

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#3514]
### New Functionality
We can control scaling for jumbotron and parallax image. It's a little bit more difficult to control it using current attribute. We also doesn't know how big is the image for the best view in jumbotron and parallax.  Let say the image is bigger than the container, as a designer we wanna focus on some part of the image to be highlighted.

### Improvements
It will give us flexibility to focus on which part of image we wanna highlight.

### Bugs or Edge Cases it Helps Avoid
I think nothing will be broken.

**Comment by johnleider** [comment]
I have plans to refactor how these work for 1.2, looking forward to it.

**Comment by trajano** [comment]
One of the problems I saw with https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VParallax/VParallax.js#L92 and https://github.com/vuetifyjs/vuetify/blob/dev/src/mixins/translatable.js#L16 is that it makes an assumption that height is always in `px` in MaterializeCSS I was able to use a CSS height attribute specifically I was able to do `calc(100vh - 64px)` to get the full height minus 64 pixels.

**Comment by johnleider** [comment]
`v-jumbotron` has been deprecated by `v-img` and `v-parallax` will not be receiving until v2.0.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
