### ISSUE TITLE
[Bug Report] Open navigation drawer after scroll can't see the items and can't scroll up to select

### ISSUE THREAD

**Issue by vip30** [vuetifyjs/vuetify#3516]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
1- Scroll down
2- Click the button
![image](https://user-images.githubusercontent.com/4260833/37195823-5728b568-23af-11e8-9fe0-8e98ba1f5611.png)

### Expected Behavior
The drawer will open and can see the drawer item

### Actual Behavior
White page and can't scroll up

### Reproduction Link
[https://codepen.io/anon/pen/PRoyZE?&editors=101](https://codepen.io/anon/pen/PRoyZE?&editors=101)

**Comment by johnleider** [comment]
This is happening because you have the `v-navigation-drawer` set to **absolute** positioning. For this use-case, use **fixed**.

https://codepen.io/johnjleider/pen/rdNEvz?&editors=101
