### ISSUE TITLE
[Bug Report] Blank pages on some Androids and iOS 10 Mobile devices

### ISSUE THREAD

**Issue by robertsLando** [vuetifyjs/vuetify#3519]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Safari, Google Chrome
**OS:** Ubuntu undefined, iOS, Android

### Steps to reproduce
The codepen link I have provided works if opened with a Desktop PC but doesn't works with some mobile devices (tested on IOs 10.2 and android 5.0).

### Expected Behavior
Expected the page to render the content correctly 

### Actual Behavior
The page is blank, vuetify elements are not rendered, just text is shown if present in html and I have found this error on dev console of Android: 

`Uncaught TypeError: undefined is not a function`

### Reproduction Link
[https://codepen.io/suitedJimster/pen/xqWVBP](https://codepen.io/suitedJimster/pen/xqWVBP)

### Other comments
I think the problem is due to an old Javascript version that doesn't support some new Javascript formatting like arrow functions and Self-Invoking Functions `(function(){})()`

**Comment by KaelWD** [comment]
Do either of these work?:

- https://codepen.io/anon/pen/aYbxGr?editors=1010
- https://codepen.io/anon/pen/oqNOyg?editors=1010

**Comment by robertsLando** [comment]
This one renders something: https://codepen.io/anon/pen/oqNOyg?editors=1010 it shows a button and a switch but the switch is not rendered well as the list is shifted on the right

The other one nothing, just "open" text is shown.

**Comment by robertsLando** [comment]
Here some screenshots: 

https://ibb.co/jgHgsn
https://ibb.co/cXXgsn
https://ibb.co/ftybQ7

**Comment by KaelWD** [comment]
1. `v-modal` hasn't been a thing since v0.11: https://github.com/vuetifyjs/vuetify/releases/tag/v0.11.0
2. You *must* use a `v-app` for menus to work correctly, this is stated multiple times in the documentation
3. Old browsers need polyfills, this is also clearly documented
