### ISSUE TITLE
Support vue-router on v-breadcrumbs-item

### ISSUE THREAD

**Issue by CesaRamirez** [vuetifyjs/vuetify#352]
Hi, there are next plans to implement vue-router on component v-breadcrumbs-item, currently refreshing the site.

for example:

``` html
    <v-breadcrumbs icons divider="chevron_right">
         <v-breadcrumbs-item href="/admin" router>
           Admin
         </v-breadcrumbs-item>
         <v-breadcrumbs-item :disabled="true">
           Settings
         </v-breadcrumbs-item>
    </v-breadcrumbs>
```

Adding props router like others components.

Thanks, greetings.

**Comment by manelclos** [comment]
I tried release v1.2.0-beta.0 and this is still happening

**Comment by johnleider** [comment]
Please do not comment on old closed issues. If there is a regression, please create a new ticket, https://issues.vuetifyjs.com
