### ISSUE TITLE
[Bug Report] parallax jumbotron feature not working anymore

### ISSUE THREAD

**Issue by nidrax69** [vuetifyjs/vuetify#3521]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Place jumbotron like this example :

https://vuetifyjs.com/en/components/parallax#example-jumbotron

### Expected Behavior
The parallax can have its effect disabled to be used as a standard jumbotron

### Actual Behavior
the component creates a 3d effect

### Reproduction Link
[https://codepen.io/anon/pen/MVYYBB](https://codepen.io/anon/pen/MVYYBB)

**Comment by johnleider** [comment]
This is a documentation issue as the example should be removed. The **jumbotron** prop was deprecated in v1.0 in favor of the new `v-jumbotron` component.
