### ISSUE TITLE
[Bug Report] Textfield crashes because there is no character limit on the input element

### ISSUE THREAD

**Issue by Hexodus** [vuetifyjs/vuetify#3523]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 10

### Steps to reproduce
Just type in (or paste) as much characters into the text field as you want. Obviously it's not limited at all. 

### Expected Behavior
There should be a maxlength property on the input element with let's say a 256 default. And v-text-field should provide that property as well.

### Actual Behavior
 Out of curiosity I just pasted a whole source code into a text field. Because of the v-model two way binding the website crashed immediately. 

![vuetify-bug1](https://user-images.githubusercontent.com/243039/37223199-13b5333a-23d0-11e8-89bf-c7cc0eac0836.jpg)

### Reproduction Link
[https://codepen.io/Hexodus/pen/YaPWOd](https://codepen.io/Hexodus/pen/YaPWOd)

**Comment by KaelWD** [comment]
> Because of the v-model two way binding the website crashed immediately

I don't see how that could possibly happen, here is your codepen with three million characters and it works fine: ![image](https://user-images.githubusercontent.com/16421948/37238735-ecc02738-2480-11e8-97e1-ab0ce0a2f124.png)

> There should be a maxlength property on the input element with let's say a 256 default

🤣 Not gonna happen mate, that would break so much shit. You can already use `maxlength` yourself if you want.

**Comment by Hexodus** [comment]
Hmm, funny that it didn't crash. Maybe the crash occurs only in the nuxt environment or when the stars align but it crashed anyways...

**Comment by KaelWD** [comment]
Was it the one in the codepen, or an email field with a great big regex behind it?
