### ISSUE TITLE
[Bug Report] autocomplete v-select with vue 2.5.14

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#3526]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.14
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Open the v-select

### Expected Behavior
It should work

### Actual Behavior
```
[Vue warn]: Invalid prop: type check failed for prop "name". Expected String, got Boolean.

found in

---> <Transition>
       <VMenu>
         <VSelect>
```

### Reproduction Link
[https://codepen.io/anon/pen/RMNJxZ?editors=1000](https://codepen.io/anon/pen/RMNJxZ?editors=1000)

### Other comments
vuejs/vue#2485

https://github.com/vuetifyjs/vuetify/blob/20ab9b77ad7df22043ce700be2a3bd86171ca13a/src/components/VSelect/mixins/select-generators.js#L58-L60
https://github.com/vuetifyjs/vuetify/blob/20ab9b77ad7df22043ce700be2a3bd86171ca13a/src/components/VMenu/VMenu.js#L77-L80
https://github.com/vuetifyjs/vuetify/blob/20ab9b77ad7df22043ce700be2a3bd86171ca13a/src/components/VMenu/mixins/menu-generators.js#L32-L40

In 2.5.13 `data.props.transition = ''` is kept as `''` and is falsy, in 2.5.14 it's cast to `true` and breaks shit

**Comment by mbertrandtrellisrx** [comment]
This is still happening for me with 1.0.8 with any of these directives
                            autocomplete
                            hide-details
                            combobox
                            clearable

**Comment by mbertrandtrellisrx** [comment]
This is still happening for me with 1.0.9 with any of these directives on v-select
autocomplete
hide-details
combobox
clearable

**Comment by jacekkarczmarczyk** [comment]
If you're still experiencing the problem please create a new issue https://issues.vuetifyjs.com (don't forget to provide the codepen reproduction)

**Comment by NanoDev777** [comment]
I'm experiencing the same problem, I'm using version 1.0.5, I'd like to know if this has been fixed in recent versions, to update vuetify.

**Comment by andreashuber69** [comment]
Somehow this problem must have crept back into the code. Whenever I add `combobox="true"` to a `v-select`, I get a bunch of `Invalid prop` warnings. I'm using vue 2.5.16 with vuetify 1.0.17.

**Comment by KaelWD** [comment]
Not related, the `combobox` prop must be a boolean but you're giving a string.
