### ISSUE TITLE
[Bug Report] [Documentation] Stopping event propagation for activator slot for v-dialog not needed

### ISSUE THREAD

**Issue by pranavjindal999** [vuetifyjs/vuetify#3534]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 65.0.3325.146, Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
As per  [documentation ](https://vuetifyjs.com/en/components/dialogs#api) of `activator` slot of `v-dialog`, you need to manually stop propagation of event when not using the slot and manipulating the `v-model` of `v-dialog`.

Steps:
* Do not use `.stop` modifier for changing `v-model` of `v-dialog`.

### Expected Behavior
Was expected to not work or cause some bug if `.stop` not used.

### Actual Behavior
Working perfectly without `.stop` modifier.

### Reproduction Link
[https://codepen.io/anon/pen/XEbXYB?editors=1010](https://codepen.io/anon/pen/XEbXYB?editors=1010)

### Other comments
Documentation needs to be corrected. Also the example that states that you need to use `.stop` needs updation.

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #346](https://github.com/vuetifyjs/vuetifyjs.com/issues/346) via [**ZenHub**](https://www.zenhub.com/)
