### ISSUE TITLE
[Feature Request] Allow to use v-spacer inside v-navigation-drawer to make the elements "bottom-aligned"

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3536]
### New Functionality
It would allow to move list elements (inside of a drawer) to the bottom & to scroll the whole list on y-overflow:

- **See GIF** (it's 60mb, let it load): https://imgur.com/a/NDbN3
- **Codepen:** https://codepen.io/anon/pen/zWGwOe?editors=1000

### Improvements
More use cases (for example: Windows 10 UWP style drawer). 
Right now, `v-spacer` doesn't work inside of `v-navigation-drawer`

### Bugs or Edge Cases it Helps Avoid
none

**Comment by jaxn** [comment]
This design pattern is in the Material guidelines too for where to place Help and feedback in a Navy drawer.

**Comment by KaelWD** [comment]
You have to put it in a column layout: https://codepen.io/anon/pen/pLJZGg?editors=1000

Not sure what our stance is on making drawers flex containers out of the box, might break some layouts.

**Comment by AlexSHoffman** [comment]
@KaelWD thanks for the example! 

Perhaps instead of making it work out of the box, it would be better to just add this example to the docs? 

The only thing the example would have to mention is that you have to remove the default `padding` on `v-navigation-drawer`, otherwise it seems like it doesn't work properly

**Comment by XanderLuciano** [comment]
You can remove the default padding pretty easily as well.

```html
<v-list class="py-0">
```

**Comment by XanderLuciano** [comment]
Nesting this in a `v-layout` also breaks some styling such as this:

![image](https://user-images.githubusercontent.com/13877593/44952089-d8906000-ae2a-11e8-916f-43c04fd69a9f.png)

**Comment by affanshahid** [comment]
Is this the recommended way? Will it break anything?

**Comment by XanderLuciano** [comment]
@affanshahid Your font weight will not be the same due to how the CSS is scoped (using `.navigation-drawer > .v-list` means placing inside a `.v-layout` prevents the rule from apply). Not sure what else is affected though. Other than font weight, I'm not aware of any other issues.

**Comment by EqualMa** [comment]
To make `v-spacer` work in `v-navigation-drawer`, all you need to do is apply the following styles to `v-navigation-drawer`

```css
.your-custom-class {
  display: flex;
  flex-direction: column; 
}
```

See this codepen: https://codepen.io/slandii/pen/JzaOYy?editors=1010

**Comment by klaveren** [comment]
> To make `v-spacer` work in `v-navigation-drawer`, all you need to do is apply the following styles to `v-navigation-drawer`
> 
> ```css
> .your-custom-class {
>   display: flex;
>   flex-direction: column; 
> }
> ```
> 
> See this codepen: https://codepen.io/slandii/pen/JzaOYy?editors=1010

Beautiful \o/

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, this is not functionality that we are looking to implement at this time. It causes multiple issues with existing layouts and is easily resolved with @KaelWD 's workaround https://codepen.io/anon/pen/pLJZGg?editors=1000 .

I know that I referenced this in #6947 but that was a mistake, my apologies for the misunderstanding.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by morphatic** [comment]
Working example with v2.0: https://codepen.io/morphatic/pen/ewWMvM?editors=1000

**Comment by JVP3122** [comment]
@morphatic Have you figured out a way to do this using the new grid system?  I'm trying to get away from using v-layout column setups but nothing I've found seems to work without creating my own custom css classes, which I feel like defeats the purpose of using a css library.

**Comment by oliveiracdz** [comment]
@JVP3122, did you try to use the new [append slot](https://vuetifyjs.com/pt-BR/components/navigation-drawers#examples)?

**Comment by JVP3122** [comment]
> @JVP3122, did you try to use the new [append slot](https://vuetifyjs.com/pt-BR/components/navigation-drawers#examples)?

Now I feel stupid because I clearly did not do this. Thanks for pointing me in the right direction

**Comment by morphatic** [comment]
Or: https://codepen.io/morphatic/pen/XWWxLXM?editors=1010

Allows you to keep the semantics of list items, but just add a couple of style rules to move the last list item to the bottom.
