### ISSUE TITLE
[Bug Report] "disable-route-watcher" prop doesn't work with mini drawer

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3539]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 10

### Steps to reproduce
- Open reproduction link
- Click any element of the list in the `mini drawer`
- The full drawer will get opened even if it has `disable-route-watcher` prop specified

### Expected Behavior
When you click an item in the `mini drawer` the full version should stay closed

### Actual Behavior
Clicking an item in the `mini drawer` opens the full drawer

### Reproduction Link
[https://codepen.io/anon/pen/MVwodb](https://codepen.io/anon/pen/MVwodb)

**Comment by johnleider** [comment]
Disable route watcher has nothing to do with this functionality. **mini-variant** is simply a design choice. You are adding the .sync method which means if you click the `v-navigation-drawer`, it will open.

If you need the **mini-variant** to behave different, simply change your logic that designates what it is.

**Comment by AlexSHoffman** [comment]
@johnleider oh sorry, it didn't occur to me that `.sync` is what opens the drawer
