### ISSUE TITLE
Add context option to snackbar

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#354]
It would be nice if the snackbars could have a context option that allows for quick styling as error, warning, success, etc.

**Comment by johnleider** [comment]
This  can be done by dynamically binding the state. While maybe not ideal, it sticks to the convention of semantic props.

```<v-alert :success="prop === 'success'" :error="prop === 'error'">```

**Comment by smares** [comment]
I am referring to toasts / snackbars and not alerts.

**Comment by johnleider** [comment]
The same logic applies, v-alert was just on my mind when writing.

**Comment by smares** [comment]
There is no such thing as success, alert, etc. for snackbars according to the docu, that is my concern.

**Comment by johnleider** [comment]
Ahh, my mistake, I thought contextual mixin was applied to snackbar and it is not.

```<v-snackbar :class="{ 'success': prop === 'success', 'error': prop === 'error' }">```

**Comment by smares** [comment]
Thanks. Can this be changed in a future version so that it's consistent with alerts for example?

**Comment by johnleider** [comment]
Yes
