### ISSUE TITLE
[Bug Report] Text field label overlaps icon when using icon and prefix 

### ISSUE THREAD

**Issue by andywhite8** [vuetifyjs/vuetify#3541]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.1

### Steps to reproduce
Use prepend-icon and prefix props on a text field

### Reproduction Link
[https://codepen.io/andywhite8/pen/ZxGaYE](https://codepen.io/andywhite8/pen/ZxGaYE)

**Comment by aero-no1-ks** [comment]
I am having the same trouble. It seems the default material icon css file is not loaded. 

All material icons are not working from a few days ago. 

I think this should be urgent. It ruins the UI.

**Comment by ultracote** [comment]
I have the same problem :(

**Comment by jacekkarczmarczyk** [comment]
Fixed in 1.1
https://codepen.io/anon/pen/WyoXPQ
