### ISSUE TITLE
[Feature Request] v-text-field prepend/append icon classes

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#3543]
**New Functionality**
I feel there is no way right now to add custom classes to append/prepend-icon.

**Improvements**
Custom classes on icons. We have a way to have a callback, why not custom classes ?

**Markup**
```
<v-text-field v-model="option" class="pa-0"
                                prepend-icon="view_headline"
                                append-icon="delete"
                                append-icon-class="form-element-invisible grey"
                                :append-icon-cb="removeOption"/>
```

**Bugs or Edge Cases it Helps Avoid**
I think it can be helpful in some cases, for exemple right now I want to add a class that makes my icon invisible when the text field is not hovered or active, I made it work with using icon separated from the text field but this is not as pretty, code-wise and even visually.

**Comment by KaelWD** [comment]
These are being moved to slots in 1.1
