### ISSUE TITLE
[Bug Report] Where I can find v0.14.11 doc please?

### ISSUE THREAD

**Issue by 90arther** [vuetifyjs/vuetify#3544]
### Versions and Environment
**Vuetify:** 0.14.11
**Vue:** 2.3.3
**Browsers:** Safari 11.0.3
**OS:** Mac OS 10.13.3

### Steps to reproduce
I had use v0.14.11 in a project for a long time, because it has compliance with v0.15, I didn't update it.

### Expected Behavior
Please tell me how to release a doc website for myself, Thanks.

### Actual Behavior
Please tell me how to release a doc website for myself, Thanks.

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/tree/v0.14.11](https://github.com/vuetifyjs/vuetify/tree/v0.14.11)

**Comment by jacekkarczmarczyk** [comment]
clone and `yarn run` https://github.com/vuetifyjs/docs, links to older versions should work there, but i'm not 100% sure
