### ISSUE TITLE
[Bug Report] v-text-field keydown events don't get called

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#3545]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 7

### Steps to reproduce
press enter

### Expected Behavior
keydown event gets called

### Actual Behavior
nothing 

### Reproduction Link
[https://codepen.io/anon/pen/dmorYW](https://codepen.io/anon/pen/dmorYW)

### Other comments
Did I ever tell you what the definition of insanity is? Insanity is doing the exact... same fucking thing... over and over again expecting... shit to change... That. Is. Crazy. The first time somebody told me that, I dunno, I thought they were bullshitting me, so, boom...I shot him! The thing is... He was right. And then I started seeing, everywhere I looked, everywhere I looked all these fucking pricks, everywhere I looked, doing the exact same fucking thing... over and over and over and over again thinking, 'This time is gonna be different, no, no, no please...

**Comment by KaelWD** [comment]
Broken by b596c1705ffeb12c8388933d8900d5f8b85ea119, fixed in 4887a13f44925e9acaade011bb1f390b4b73b76d, broken again in 54e2b78cf27be7d6f6aaf48b80734754f5ab3ba4

**Comment by beebase** [comment]
I have the same issue with ios 10.2 / safari 10, iphone 5,  
  "vuetify": "^1.0.0"
 "vue": "^2.5.2"

The thing is, when I use the default demo app (webpack), entries work ok. However, when using EXACT the same code in my own app, it stops working. When tapping the v-text-field, the virtual keyboard slides up and seems to destroy focus on the v-text-field. Sometimes, with some luck, I'm able to type in 1 character, but than it loses focus forever. I've tried to debug in all kinds of ways but I'm getting ZERO info. This is so frustrating. Please prio this issue. It's a complete show stopper.
(on android, everything is working perfect)

**Comment by beebase** [comment]
I fixed my issue which was not related to vuetify.
Found some custom css in my code that prevents user from doing "hold to copy text", but it also prevents entering a text field.
```
* {
      -webkit-user-select: none;
      ...
```
changed it to:
```
*:not(input):not(textarea) {
      -webkit-user-select: none;
      ...
```
