### ISSUE TITLE
[Feature Request] Stepper with large number of steps-  Only show current and nearby steps.

### ISSUE THREAD

**Issue by R-j-1** [vuetifyjs/vuetify#3546]
### New Functionality
It will allow you to use large number of steps in stepper with better look.
Right now, if you make a stepper with say 20 steps in my case, it looks cumbersome and scrolling doesn't look good. 

I was wondering if there was some way for only the steps around the current step to be visible
(Say i was on step 11 so i could see steps 10 through 14 in my header and the rest would be dotted)

### Improvements
I'm fairly new to this but I believe this will make it look a lot better and user-friendly.

### Bugs or Edge Cases it Helps Avoid
I'm not sure... I'm sorry...

**Comment by nekosaur** [comment]
I don't think this is something we would choose to implement. You could probably do this yourself in user land. @vuetifyjs/dev-team?

**Comment by Flamenco** [comment]
> I don't think this is something we would choose to implement. You could probably do this yourself in user land. @vuetifyjs/dev-team?

You should document that this will not be usable with more than a few steps then, as It was a total letdown and complete waste of time getting to this point.  Any reasonable developer would assume the header would scroll once the screen filled up.  I don't understand why the DevTeam would add a half-baked widget and then refuse to make it usable by *delegating it to userland*.

This is hardly a feature request, as the component **simply does not work or function**, certainly not on a narrow display.

Setting the following CSS certainly helps the situation for me (coupled with Element.scrollIntoView() whilst watching the current step):

# CSS
```css
.v-stepper_header {
    overflow: auto;
    display: flex;
    flex-wrap:no-wrap;
}
```
# Template
```html
 <v-stepper-step v-for="i in 20" :ref="`step-${i}`" :step="i" :complete="step > i">Step {{i}}</v-stepper-step>
```
# Component
```js
   data: () => ({
      step: 1
    }),
watch: {
      step() {
        // My template is in a loop, so I use [0]...
        const comp = this.$refs[`step-${this.step}`][0]
        comp.$el.scrollIntoView()
      }
    },
```

Even if you avoid implement the `scrollIntoView`, the missing CSS is a definitely a bug...

**Comment by Rony20191** [comment]
I had the same problem, the stepper with large number of steps and he also did not Responsive Design

**Comment by maba4891** [comment]
+1
I have the same problem and think it should be a core functionality for the stepper to work mobile devices with more than 8 steps without producing the following ugly layout error:

![grafik](https://user-images.githubusercontent.com/15227261/117262608-beb44000-ae51-11eb-9170-dd93dad0851d.png)

**Comment by maba4891** [comment]
Also see #2682 where this has been raised almost four years ago and for links to material design examples of mobile steppers:
https://material.io/archive/guidelines/components/steppers.html#steppers-types-of-steps

**Comment by johnleider** [comment]
When Stepper was originally developed it had proprietary functionality that was eventually abstracted into `v-item-group`. Unfortunately the homogenous functionality of item groups did integrate into the Stepper well.

Simply put, the changes required would be breaking and it was a very early component that didn't garner the attention of any of the Core team or even community members; no one wanted to work on it at the right times. We are addressing this issue in Vuetify 3 because the component is being rebuilt from the ground up.

Thank you everyone for your patience on this one.

**Comment by maba4891** [comment]
Cool, thanks for the informative and honest feedback.

**Comment by johnleider** [comment]
I'm finally on this one https://github.com/vuetifyjs/vuetify/pull/17685

Added header overflow and mobile support:

![image](https://github.com/vuetifyjs/vuetify/assets/9064066/d1ef23eb-5714-4eac-a0cd-1beb72c8f717)

Just a small step towards improving the UX. I plan on pushing this into Labs this month so if you have anymore feedback pertaining to this issue, let me know.
