### ISSUE TITLE
[Bug Report] v-chip RGB color string  not accepted as color attribute

### ISSUE THREAD

**Issue by janglada** [vuetifyjs/vuetify#3547]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.8
**Browsers:** Chrome 65.0.3325.146
**OS:** Mac OS 10.13.3

### Steps to reproduce
Just open the codepen

### Expected Behavior
v-chip should be using the RGB color defined in the attribute

### Actual Behavior
The color string is used as a class

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3416

(and you didn't save your codepen)
