### ISSUE TITLE
[Bug Report] v-footer inset problem

### ISSUE THREAD

**Issue by nidrax69** [vuetifyjs/vuetify#3549]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
This codepen (https://codepen.io/anon/pen/vRNYVr) was using old version of vuetify (0.17.7) and my footer was perfect

Now it's not working as expected

### Expected Behavior
See the footer like the old version

### Actual Behavior
footer has 32px

### Reproduction Link
[https://codepen.io/anon/pen/NYGPBR](https://codepen.io/anon/pen/NYGPBR)

**Comment by johnleider** [comment]
`v-footer` is part of the **app** components and has to have a designated height. By default this is 32px, but you can change it. In your example, I just added **height="auto"**.

https://codepen.io/johnjleider/pen/JLYWVw

**Comment by Lucassith** [comment]
@johnleider the problem is with the footer's inset prop. It does not seem to work even on the vuetify homepage predefined layouts. Also take a look at the markup on @nidrax69 codepen, even though it has "<v-footer app **inset** height="auto">" it does not inset itself with the navigation drawer.
