### ISSUE TITLE
[Feature Request] Ajouter un langue Français

### ISSUE THREAD

**Issue by Dob6458** [vuetifyjs/vuetify#3551]
### New Functionality
C'est d'avantage essayer les composants Vuetify.js

### Improvements
Amélioration des performances

### Bugs or Edge Cases it Helps Avoid
Corriger les bugs

**Comment by johnleider** [comment]
I'm not sure what this request is asking for. I ran it through google translate and this is what I got:

New Functionality
This is more to try the components Vuetify.js

[Feature Request] Add a language English
Improvements
Performance improvement

Bugs or Edge Cases it Helps Avoid
Correct the bugs

**Comment by Kleemer** [comment]
I guess he is asking for a translation of the documentation in French.

**Comment by nidrax69** [comment]
Even as a french, i don't understand his request

**Comment by KaelWD** [comment]
This issue makes no sense, translated or not. Please keep all conversation to english so everyone knows what's going on.
