### ISSUE TITLE
[Bug Report] circular progress width is relative to the size

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#3557]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
Open codepen

### Expected Behavior
first 3 items should have the same width, last 2 should not be distorted

### Actual Behavior
1-3: the bigger size the bigger width (although the width prop is same for all of them)
4-5: progress is distorted

![image](https://user-images.githubusercontent.com/15625235/37323387-07a7fd96-26b6-11e8-81a7-225c6b4802e8.png)

### Reproduction Link
[https://codepen.io/anon/pen/PRPaoZ?editors=1000](https://codepen.io/anon/pen/PRPaoZ?editors=1000)

**Comment by KaelWD** [comment]
> 4-5: progress is distorted

It's being clipped by the `<svg>` not being big enough:
![image](https://user-images.githubusercontent.com/16421948/37390815-62b6f89c-27bd-11e8-8f0e-cff411baacf6.png)
