### ISSUE TITLE
[Feature Request] Enhance the style/theme page with codepen examples

### ISSUE THREAD

**Issue by ppKrauss** [vuetifyjs/vuetify#3559]
### New Functionality
There are no real-life example (complete one-page with Vue instance initialization) at https://vuetifyjs.com/en/style/theme
so, it generate questions for beginners, as [this one](https://stackoverflow.com/q/49255051/287948).

### Improvements
As other guide pages of vuetifyjs.com, add some examples with codepen.

### Bugs or Edge Cases it Helps Avoid
**No use of theme**, no customizing, by beginners (that are using one-page-site Vue instances).

**Comment by KaelWD** [comment]
This repo is for framework issues only. The documentation repository is https://github.com/vuetifyjs/vuetifyjs.com
