### ISSUE TITLE
DataTable should have a prop for changing text "Rows per page"

### ISSUE THREAD

**Issue by KaRkY** [vuetifyjs/vuetify#356]
### Versions

v0.10.4

### What is expected ?

Text property on DataTable for changing text "Rows per page"

### What is actually happening ?

Text is fixed and can not be changed.

### Reproduction Link

Third example.
https://vuetifyjs.com/components/datatables

**Comment by johnleider** [comment]
Duplicate of #340

**Comment by KaRkY** [comment]
Why duplicate i am talking about changing text Rows per page to something like Products per page?

**Comment by johnleider** [comment]
My mistake.
