### ISSUE TITLE
[Bug Report] v-tabs would emit an input event twice

### ISSUE THREAD

**Issue by FFxSquall** [vuetifyjs/vuetify#3560]
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.15
**Browsers:** Chrome 65.0.3325.146
**OS:** Linux x86_64

### Steps to reproduce
1. Put `v-tabitem` inside` v-tabs`
2. Click tab
3. input emit twice (see console.log)

### Expected Behavior
input emit once

### Actual Behavior
input emit twice

### Reproduction Link
[https://codepen.io/anon/pen/dmGPgQ?editors=1011](https://codepen.io/anon/pen/dmGPgQ?editors=1011)

### Other comments
need to fix "tabProxy" method

**Comment by johnleider** [comment]
You are using v-model in conjunction with an explicit **@input** listener. The result is expected.

**Comment by FFxSquall** [comment]
@johnleider Even if I do not hang a listener, the input event will still be called twice. Note the 'should update model when route changes' test in `VTabs.spec.js`. If you use `toHaveBeenCalledTimes` instead of` toHaveBeenCalled`, you can see a problem. We already corrected similar behavior in #3494, than this case differs?

**Comment by KaelWD** [comment]
Fixed by #3561
