### ISSUE TITLE
[Bug Report] Data table not x-axis scrollable in 1.0.7

### ISSUE THREAD

**Issue by amyngb** [vuetifyjs/vuetify#3563]
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.15
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 8.1

### Steps to reproduce
Don't go to the CodePen link (the datatables ARE x-axis scrollable there, so I can't reproduce the problem on Codepen).
Resize your browser window and go to https://vuetifyjs.com/en/components/data-tables.  You'll see that the datatables in the Vuetify documentation aren't x-axis scrollable.  

### Expected Behavior
Datatables should have an x-axis scroll bar and be scrollable.

### Actual Behavior
Datatables have no x-axis scroll bar and are not scrollable.

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

**Comment by KaelWD** [comment]
Fixed by c4775e4d9ecb749b45fb53ac125f5f32b3c44218
