### ISSUE TITLE
[Bug Report] Blank icon not allowing another icon to be pressed

### ISSUE THREAD

**Issue by mmargerumImpactrx** [vuetifyjs/vuetify#3564]
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.15
**Browsers:** Google Chrome
**OS:** Mac OS 10.13.2

### Steps to reproduce
On google chrome on a Mac, the red trashcan button does not fire.  works in safari.  if you remove the blank icon, it works.

### Expected Behavior
Red trashcan should fire deleteClicked event

### Actual Behavior
button not responding to click

### Reproduction Link
[https://codepen.io/margerum/full/LdGjmr](https://codepen.io/margerum/full/LdGjmr)

**Comment by KaelWD** [comment]
`blank` is not a valid material icon, so it's rendered as text instead that overflows out of the button. 

https://material.io/icons/
