### ISSUE TITLE
[Bug Report] Slider is activated by drag not started on the slider

### ISSUE THREAD

**Issue by salomvary** [vuetifyjs/vuetify#3567]
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Mac OS 10.12

### Steps to reproduce
- Press and hold the left mouse button somewhere outside of the slider.
- Move the mouse over the slider.
- Release the mouse button.

### Expected Behavior
The slider should not move.

### Actual Behavior
The slider moves to where the mouse button was released.

### Reproduction Link
[https://codepen.io/anon/pen/zWreYR?editors=1010](https://codepen.io/anon/pen/zWreYR?editors=1010)

### Other comments
This is a minor issue but I noticed native range controls behave as expected (see code example). Seems to affect multiple browsers.

**Comment by FFxSquall** [comment]
Maybe need to use `click` instead of `mouseup` on line 338 in `VSlider.js`. Seems to work correctly
