### ISSUE TITLE
[Bug Report] DataTable: Performance impact inline editing

### ISSUE THREAD

**Issue by Faberle** [vuetifyjs/vuetify#3570]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Use inline editing

### Expected Behavior
Dialog is added to the DOM as needed. 

### Actual Behavior
For EVERY entry that uses Inline editing the dialog is always added to the DOM

Example: Table 50 rows and 10 columns => 500! dialogs added to the DOM

### Reproduction Link
[https://codepen.io/Faberle/pen/qoZWVg?editors=1111](https://codepen.io/Faberle/pen/qoZWVg?editors=1111)

### Other comments
The dialog should only be added to the DOM when it is shown the first time, especially when it's lazy.

**Comment by FFxSquall** [comment]
@johnleider The same situation is observed with the `v-tooltip`. I was very surprised. Maybe there are some reasons to do this?

**Comment by johnleider** [comment]
We just need to refactor the lazy logic for detachable implementing components.
