### ISSUE TITLE
[Bug Report] Tabs is not working properly with modal

### ISSUE THREAD

**Issue by wildstyles** [vuetifyjs/vuetify#3573]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.11
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Load the pen, open modal, then try to click on tabs.

### Expected Behavior
On first load of modal the first element of tab should  be selected.

### Actual Behavior
On initial modal load there are no selected tab. 

### Reproduction Link
[https://codepen.io/Wildstyles/pen/bvperv?editors=1010](https://codepen.io/Wildstyles/pen/bvperv?editors=1010)

**Comment by johnleider** [comment]
That is because tabs uses the dom in order to position the slider. While it is in the dialog, it has no dimensions to measure. The proper way to do this would be to add the lazy prop to the dialog.

https://codepen.io/johnjleider/pen/dmMNrv?editors=1010

**Comment by jdunk** [comment]
I see an issue has been filed for this no fewer than 3 times (and I'm here because I encountered it also).

Would be great if this gotcha (and solution) could be added somewhere on the tabs docs page.

**Comment by jacekkarczmarczyk** [comment]
@jdunk good idea imho, please create an issue in [vuetifyjs.com](https://github.com/vuetifyjs/vuetifyjs.com/issues) repo
