### ISSUE TITLE
[Feature Request] Change Data table 'items' slot to 'item'

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#3574]
### New Functionality
Data tables slot for rows is label as 'items', select 'rows' are labelled as 'item', not intuitive.

### Improvements
Keeps slot labels consistent and less need for troubleshooting or docs research

### Bugs or Edge Cases it Helps Avoid
Using the wrong slot label 'items' in selects or 'item' in data tables

**Comment by blalan05** [comment]
Available in 2.0 alpha.
