### ISSUE TITLE
[Feature Request] alternate text for icon

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#3577]
### New Functionality
When you use `<v-icon>arrow_back</v-icon>`, on a browser that has disabled web fonts it will render as arrow_back, I'd like to specify an fall back rendering using `<` when the fonts aren't rendered.

### Improvements
I don't know of a current workaround.

### Bugs or Edge Cases it Helps Avoid
It prevents confusing renderings for some users who have blocked custom fonts.

**Comment by nekosaur** [comment]
I would say this is outside of vuetify's scope.

1. How would you detect if browser has disabled web fonts

2. What would you fall back to for any other icon not easily represented with ascii characters?

**Comment by andrewharvey** [comment]
Fair enough material.io has the same issue, so probably outside your scope.

2. This should be up to the dev implementing the site, Vuetify shouldn't set any defaults.

**Comment by sfakir** [comment]
+1
