### ISSUE TITLE
[Feature Request] v-divider in  v-toolbar

### ISSUE THREAD

**Issue by alphaelf** [vuetifyjs/vuetify#3578]
### New Functionality
already `v-divider` component make horizontal line in lists.
and it will better to make vertical line in toolbars

### Improvements
increase reusability of `v-divider` component

### Bugs or Edge Cases it Helps Avoid
Fixes a defect

**Comment by Traxo7** [comment]
Will this apply only to toolbars, or we could for example split `v-card` in two parts with it as well?
