### ISSUE TITLE
Tooltips of action buttons on cards are covered by neighboring cards

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#358]
### Steps to reproduce
Create a multi-column layout with cards that have action buttons with long tooltips. The tooltips of the action buttons are covered by the neighboring cards.

### Versions
Vue 2.2.6, Vuetify 0.10.4, Ubuntu 16.10, Chrome 57.0.2987.133 (64-bit)

### What is expected ?
Tooltips should have highest z-axis level

### What is actually happening ?
Tooltips are covered by neighboring cards

### Reproduction Link
http://codepen.io/anon/pen/OmJYrM (hover the "Directions" button)

**Comment by johnleider** [comment]
Confirmed that this was fixed with the changes made for #334
