### ISSUE TITLE
[Bug Report] About using v-menu with v-data-table

### ISSUE THREAD

**Issue by cainsider** [vuetifyjs/vuetify#3580]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.2
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.12.6

### Steps to reproduce
please click icon at first row
v-menu will work
but another v-menu will show, when this row was removed

### Expected Behavior
when this row was removed, another v-menu will not show

### Actual Behavior
still show  :<

### Reproduction Link
[https://codepen.io/anon/pen/JLXzjV](https://codepen.io/anon/pen/JLXzjV)

**Comment by johnleider** [comment]
This is because Vue is re-using the deconstructed menu and rehydrating it for the new row. You need to assign a manual key to override this:

https://codepen.io/johnjleider/pen/LdZdpo

**Comment by nekosaur** [comment]
You could use the progress bar slot to do this. See this example https://vuetifyjs.com/en/components/text-fields#example-progress-bar
