### ISSUE TITLE
[Feature Request] Password strength component

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3584]

**Comment by gabaum10** [comment]
Idk what happened.  I tried to create the request via the template on mobile and nothing was populated. 

Anyway, I did have something about adding a password strength meter to the text input or as a stand alone component so an external one was not necessary.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

**Comment by nekosaur** [comment]
You could use the progress bar slot to do this. See this example https://vuetifyjs.com/en/components/text-fields#example-progress-bar

**Comment by KaelWD** [comment]
Here's a text-only one I dit 6 months ago: https://codepen.io/anon/pen/qoNJyM

**Comment by gabaum10** [comment]
Thanks all.  I'll rig something up using that.
