### ISSUE TITLE
[Bug Report] v-text-field shows hint when hide-details is present

### ISSUE THREAD

**Issue by knagyorg** [vuetifyjs/vuetify#3587]
**Versions and Environment**

Vuetify: 1.0.8
Vue: 2.5.16
Browsers: Firefox 58.0.2 (64-bit)
OS: Linux Mint 18.3
Steps to reproduce

**Slightly modified template**
Hint is shown on v-text-field when field is **required** and hide-details is present

**Expected Behavior**
No hint as it is described in documentation: hide-details - "Hides hint, validation errors"

**Actual Behavior**
Hint "Please fill out this field." is shown

**Reproduction Link**
https://codepen.io/anon/pen/oqLKXL

**Comment by jacekkarczmarczyk** [comment]
I can't reproduce it with your codepen

**Comment by KaelWD** [comment]
Neither

**Comment by knagyorg** [comment]
When i move mouse over text component hint is shown.
I can reproduce it even in Chromium Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

![image](https://user-images.githubusercontent.com/10117488/37522568-9dd88a2c-2924-11e8-8f29-6c9b5e0a431c.png)

**Comment by KaelWD** [comment]
That's part of the browser, `hide-details` just removes this part of the input:
![image](https://user-images.githubusercontent.com/16421948/37523251-78869100-297a-11e8-90b2-8bc671b60712.png)
