### ISSUE TITLE
[Bug Report] v-tab is not selected properly when href attribute is used

### ISSUE THREAD

**Issue by coronoahcoro** [vuetifyjs/vuetify#3589]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 10

### Steps to reproduce
From the CodePen, you can see that none of the v-tab is selected even though I specified the activeTab to select the tab with 'Change Password' text. If I take :href="tab-link" out from the v-tab (line 12), then the tab is selected properly.

### Expected Behavior
The v-tab is selected properly when a default selected v-tab is given whether href attribute is specified or not.

### Actual Behavior
The v-tab is not selected properly when a default selected v-tab is given and href attribute is specified.

### Reproduction Link
[https://codepen.io/jgunawan-dc/pen/XEjJOd](https://codepen.io/jgunawan-dc/pen/XEjJOd)

### Other comments
In my application, I use v-tabs component to navigate to other pages so I don't use <v-tab-items> and <v-tab-item> components. I do this because I want the URL to change when I click the tab (backend is ASP.NET Core).

**Comment by johnleider** [comment]
You are missing a `#`.

https://codepen.io/johnjleider/pen/Kogqav

**Comment by coronoahcoro** [comment]
@johnleider thank you for the response, but as can be seen on your CodePen, when the page is loaded the first time. No tab is being selected even though the activeTab is specified to '1'. The end result that I am expecting is the tab is pre-selected based on the activeTab value without clicking on the tab. The activeTab value is calculated on the server side.

**Comment by johnleider** [comment]
When using href, you shouldn't be using numbers, updated example: https://codepen.io/johnjleider/pen/pLGxJX

**Comment by coronoahcoro** [comment]
wow. thank you, much appreciated :)
