### ISSUE TITLE
Snackbar background color works wrong

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#359]
### Steps to reproduce
```html
<v-snackbar v-model="snackbar" class="red">Hi there!</v-snackbar>

```

### Versions
vuetify@0.9.4
vue@2.2.6

### What is expected ?
Snackbar shows with red background

### What is actually happening ?
In inactive state snackbar always visible with red background despite ```v-model```
In active state snackbar emerges with default background
![d27c6ff8ae](https://cloud.githubusercontent.com/assets/339596/25014320/eb3eb0f6-207f-11e7-81d6-aeec8702813a.png)

**Comment by johnleider** [comment]
Have you tried upgrading to 0.10.4? There are no breaking changes and I believe this is resolved.
If not, please supply a reproduction link, thank you.

**Comment by Darkside73** [comment]
Yes, you are right. It works in 0.10.4
