### ISSUE TITLE
How do I config vuetify/nuxt to use vuetify cdn?

### ISSUE THREAD

**Issue by yasinshaw** [vuetifyjs/vuetify#3594]
Hello! Thank you for the work about vuetify.
I use the vuetify/nuxt template to develop my application. And I want to use vuetify.js(and vue.js, vue-router and so on..) with cdn. 
I config nuxt.config.js:
```js
module.exports = {
	head: {
		script: [
			{ src: 'https://unpkg.com/vuetify/dist/vuetify.js' }
		]
                //...
       }
       //...
}
```
But it dosen't work. The console show me:
```js
[Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
...
```
Could you please give me a hand to solve the problem? Thanks very much!

**Comment by jefrydco** [comment]
@yasinshaw Take a look on the documentation, it has been documented there, [Quick Start](https://vuetifyjs.com/en/getting-started/quick-start)

**Comment by KaelWD** [comment]
Not possible, vue and vuetify must be installed with NPM for correct SSR operation with nuxt. Also the CDN version operates slightly differently so you would probably experience hydration errors when used with nuxt. 

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
