### ISSUE TITLE
[Bug Report] List-tiles used as activator doesn't get list__tile--link class

### ISSUE THREAD

**Issue by mwaldstein** [vuetifyjs/vuetify#3597]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Windows 10

### Steps to reproduce
 * Use a list-tile as an activator for a dialog

### Expected Behavior
I'd expect that the list tile has the have hover effects as when an @click property is provided - pointer mouse cursor, shaded tile.

### Actual Behavior
No indicator is given that the tile is clickable.

### Reproduction Link
[https://codepen.io/mjwalds/pen/NYRBNR/](https://codepen.io/mjwalds/pen/NYRBNR/)

### Other comments
There are a few easy workarounds - 
 * empty @click property (`<v-list-tile slot="activator" @click="">`) - inherently messy and an obvious workaround
 * Use a variable for the dialog rather than an activator - In our particular case, this ends up adding a lot of code and variables we don't need.

**Comment by JesusCrow** [comment]
List tile width is not inherited properly too.

**Comment by johnleider** [comment]
There is no way (that I'm aware) that we can check on a component if it is in a specific slot. Until that day comes, I'm adding a prop **link** to allow you to manually specify as a link.

**Comment by KaelWD** [comment]
`this.$vnode.data.slot`

**Comment by KaelWD** [comment]
But that's more flexible
