### ISSUE TITLE
RouterLink inside v-navbar-items

### ISSUE THREAD

**Issue by ackzell** [vuetifyjs/vuetify#36]
I figured out a way to use [https://github.com/vuetifyjs/vuetify/pull/25
](https://github.com/vuetifyjs/vuetify/pull/25
)

```
 <v-navbar-items>
    <v-navbar-item router :item="{ href: { name: 'page1' }, text: 'page1'}"/>
    <v-navbar-item router :item="{ href: { name: 'page2' }, text: 'page2'}"/>
 </v-navbar-items>
```

All is needed is to add the `router` attribute and the `href` key on the `item` prop can either have a string with the path (ie. `'/page1'` or `'/page2'` in the example code), or an object the way you would use the `to` prop in a _raw_ `router-link` implementation. 

Hope that helps someone else in case they need to implement it :)

**Comment by johnleider** [comment]
Thank you, I have not updated the documentation yet to reflect this change. I'm contemplating moving the router option into the item object so that it can be passed in as an argument when using the items prop for sidebar/navbar.

**Comment by johnleider** [comment]
Documentation has been updated. Will consider moving router option to the item object in the future.
