### ISSUE TITLE
Feature request: range slider

### ISSUE THREAD

**Issue by sebastianmacias** [vuetifyjs/vuetify#360]
It would be very helpful to have a range slider:

[------O------------------------O---]

I'm currently working on an app that requires being able to set a beginning and ending time; a range slider will work very well in this case. Another use case for a range slider would be having to implement a price range selector in an application.

**Comment by johnleider** [comment]
I'm going to close this for now as I have no intentions of creating this in the base vuetify repository. However, it may be something that is created for an addon pack.
