### ISSUE TITLE
[Bug Report] v-selector doesn't update choices dynamically

### ISSUE THREAD

**Issue by Tabrizian** [vuetifyjs/vuetify#3600]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.0
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 10

### Steps to reproduce
As you can see in the codepen by changing every item inside the upper ```v-select``` the ```itemChanged``` method adds a new item to the choices available for the second ```v-select```.  

### Expected Behavior
My expected functionality is that by changing every item of the upper ```v-select``` a new item is added to the ```v-select``` below.

### Actual Behavior
It doesn't add new choices that are added using the ```itemChanged``` event handler for ```@input```.

### Reproduction Link
[https://codepen.io/tabrizian/pen/PRGgNj](https://codepen.io/tabrizian/pen/PRGgNj)

**Comment by moustacheful** [comment]
I think this is more related to Vue than to vuetify. 

> When you are adding a new property that wasn’t present when the data was observed. Due to the limitation of ES5 and to ensure consistent behavior across browsers, Vue.js cannot detect property addition/deletions. 

In this case, you're forgetting to previously set a `choices` key inside  `data.object`.

Check https://vuejs.org/2016/02/06/common-gotchas/

**Comment by jacekkarczmarczyk** [comment]
As @moustacheful said
```js
      object: {
        key: "",
        choices: []
      },
```

**Comment by Tabrizian** [comment]
Thank you very much for your response. Sorry for the bothering
