### ISSUE TITLE
[Bug Report] Menu not focus when in absolute position

### ISSUE THREAD

**Issue by DrSensor** [vuetifyjs/vuetify#3602]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.186
**OS:** Linux x86_64

### Steps to reproduce
Exact as https://vuetifyjs.com/en/components/menus#example-absolute

### Expected Behavior
Menu list should be in `focused()` state so it could be navigated using up/down key like any other example.

### Actual Behavior
Menu list not being `focused`. Navigated using up/down key not work.

### Reproduction Link
https://codepen.io/drsensor/pen/PRebvy

**Comment by nekosaur** [comment]
Your codepen link is invalid. You forgot to save the pen before copying the link.

**Comment by DrSensor** [comment]
Updated.

**Comment by KaelWD** [comment]
Menus aren't ever focused when you click on them, that's just a side-effect of using a button as an activator.

**Comment by KaelWD** [comment]
Resolved in e9a816dd38a0ebe2c683e2bf4fac92cc44dcf6ff
