### ISSUE TITLE
[Feature Request] Dropdown documentation update

### ISSUE THREAD

**Issue by kkojot** [vuetifyjs/vuetify#3605]
### Problem to solve
It took me some time to find the dropdown component in the documentation. With these steps I couldn't find it:
1. find the right one in the list of components on the left drawer
2. search for the `dropdown` with the search box

The second step lead me to the `Button Dropdown Variants` example, which isn't exactly what I looked for. What I needed is https://vuetifyjs.com/en/components/menus
 

### Proposed solution
* link or example in `Button Dropdown Variants` with the menu component
* search result to the menu component after typing the `dropdown` phrase in the search box

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #358](https://github.com/vuetifyjs/vuetifyjs.com/issues/358) via [**ZenHub**](https://www.zenhub.com/)
