### ISSUE TITLE
eslint issue: absolute imports should come before relative imports  import/first

### ISSUE THREAD

**Issue by torarnv** [vuetifyjs/vuetify#3606]
```
import Vue from 'vue';
import App from './App';
import router from './router';
import Vuetify from 'vuetify';
import 'vuetify/dist/vuetify.min.css';
```

Results in:

```
/<foo>/src/main.js
  6:21  error  Absolute imports should come before relative imports  import/first
  7:8   error  Absolute imports should come before relative imports  import/first
```

When using the airbnb standard.

**Comment by KaelWD** [comment]
So change the order then? I don't know why you decided to make an issue here for that.

**Comment by torarnv** [comment]
This is what the default webpack template, provided by vuetify, via `vue init vuetifyjs/webpack` sets up. I usually expect starter-templates/guides provided by a project to be error free when I begin, it's a matter of good first-install user experience.

As a complete beginner, I don't know how to re-order the statements that `vue init vuetifyjs/webpack` generated to please the linter, while also not messing up Vue/Vuetify's dependencies etc. 

Can you tell me what the correct order is?

**Comment by torarnv** [comment]
For anyone hitting this issue, adding `'import/first': [ 'error', 'DISABLE-absolute-first' ]`, to `.eslintrc.js` silenced the error.

**Comment by torarnv** [comment]
> For anyone hitting this issue, adding 'import/first': [ 'error', 'DISABLE-absolute-first' ], to .eslintrc.js silenced the error.

This is the kind of stuff I'd expect the project to automatically add, if it knows it's generating templates with linter-issues, so that the first-install user experience doesn't start out with googling linter errors.

**Comment by KaelWD** [comment]
Sorry I can't read minds, you should have said that you were using a template in the issue. This issue board is only for framework-specific issues, problems with that template must be reported on https://github.com/vuetifyjs/webpack/issues  
Also the message is pretty self-explanatory, move the relative imports (App and router) below the others.

**Comment by torarnv** [comment]
Sorry, I thought that was clear from the imports. I'll report the issue in the template repo, thanks!

> Also the message is pretty self-explanatory, move the relative imports (App and router) below the others.

This is the part that's tricky for a beginner, I don't know if that would change/break/subtly affect the internal operation of any of those components. As a beginner I assume the order in a template is like that for a reason.
