### ISSUE TITLE
[Bug Report] v-menu not unshowing when click on scrollbar

### ISSUE THREAD

**Issue by WuerfelDev** [vuetifyjs/vuetify#3607]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Mozilla Firefox, Google Chrome
**OS:** Linux, Ubuntu undefined

### Steps to reproduce
1. open menu
2. click on scrollbar

### Expected Behavior
the menu should unshow

### Actual Behavior
works, but this exception

### Reproduction Link
[https://codepen.io/anon/pen/GxNodM?editors=1010](https://codepen.io/anon/pen/GxNodM?editors=1010)

**Comment by johnleider** [comment]
This is not a bug. There are no event listeners for clicking the scrollbar. Any implementations to add this support would be hacky at best.

**Comment by KaelWD** [comment]
`click` doesn't fire, but `mousedown` and `mouseup` do, at least in chrome.

**Comment by WuerfelDev** [comment]
What is the advantage of using click over mousedown?

For example in case of dragging another element i would say its better to close the menu, closing it when pressing a scrollbar isn't bad either, or when opening the context menu/right mouse click
