### ISSUE TITLE
[Bug Report] $vuetify.goTo never completes and never releases scroll

### ISSUE THREAD

**Issue by moustacheful** [vuetifyjs/vuetify#3608]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.140
**OS:** Linux x86_64

### Steps to reproduce
Use browser's zoom feature, then programatically scroll to an off-screen element

### Expected Behavior
The scroll animation stops after the set duration.

### Actual Behavior
goTo keeps requesting animation frames as it will never reach the target. Thus, locking the scrolling behaviour permanently.

This never triggers:
```javascript
    if (Math.round(window.pageYOffset) === targetLocation) return
```

### Reproduction Link
[https://codepen.io/anon/pen/MVbyNp](https://codepen.io/anon/pen/MVbyNp)

### Other comments
I tested on my machine, and a possible solution would be to besides the check above, a check on `progressPercentage` could be done as well. This works for my reproduction link.

I can provide a PR if needed.

**Comment by KaelWD** [comment]
If you have a fix for it already, feel free to PR.

**Comment by moustacheful** [comment]
Done. Let me know if I screwed up on any of the required steps!
