### ISSUE TITLE
Expose errors array as a prop within input.js mixin

### ISSUE THREAD

**Issue by matt-e-king** [vuetifyjs/vuetify#361]
Hey @johnleider! Quick potential feature request I wanted to run by you regarding error handling for TextFields. You mentioned in this closed issue: https://github.com/vuetifyjs/vuetify/issues/208 that your intent is for basic validation and for plugins to hook up nicely.

Do you think it would be advantageous to expose the `errors` array [located here](https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/input.js#L4) as a prop instead? That way if a developer does decides to use a plugin or their own custom validation, they can at least pass an array of error messages to the `<text-field>`, and still inherit all the styles and animations that come with it.

Ideally everything would still work the exact same way, however the developer can pass error messages instead of them only being set internally within the `validate()` method.

If you see potential behind this, I don't mind attempting a pull request. Thanks for all your hard work and commitment to this project!

**Comment by johnleider** [comment]
Thank you for the suggestion. Great news, you can already do this if you want to by passing an array of strings to the rules prop.
