### ISSUE TITLE
[Feature Request] Allow to add tooltips programmatically

### ISSUE THREAD

**Issue by jonasgroendahl** [vuetifyjs/vuetify#3610]
**Problem to solve**
If you're working with a JavaScript library that is not intended to work with Vue, for example FullCalendar. It would be neat to be able to add Vuetify tooltips to events of the calendar.

**Proposed solution**
$vuetifty.addTooltip(domElement) magic happens.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
