### ISSUE TITLE
[Bug Report] $vuetify.goTo doesn't properly detect vue components when Vue is minified

### ISSUE THREAD

**Issue by moustacheful** [vuetifyjs/vuetify#3611]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.140
**OS:** Linux x86_64

### Steps to reproduce
Use minified Vue.
When adding a ref and using `this.$vuetify.goTo(this.$refs.target)` it will complain about the target not being a Vue component.

Try changing the vuejs dependency to the non-minified version and you'll immediately notice it works as intended.

This issue can also be seen at the [documentation](https://vuetifyjs.com/en/motion/scrolling)
Scrolling to the radio group works as it's a DOM element, but not to the button as it is a Vue component.

### Expected Behavior
goTo should scroll to the given vue component

### Actual Behavior
Does not scroll and instead prints message:
```
[Vuetify] Target must be a Selector/Number/DOMElement/VueComponent, received o instead.
```

### Reproduction Link
[https://codepen.io/anon/pen/aYBpbq](https://codepen.io/anon/pen/aYBpbq)

### Other comments
A proposed change would be to change the function `isVueComponent` with 
```js
function proposedIsVueComponent(obj) {
  return obj && obj instanceof Vue;
}
```
To avoid mangling issues. See reproduction link, which includes both functions being called on the mount lifecycle hook.

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/37583860-4dbd06e6-2ba7-11e8-8575-5ad283065284.png)

**Comment by ayush987goyal** [comment]
I can still see this bug in 1.0.9. 
```
[Vuetify] Target must be a Selector/Number/DOMElement/VueComponent, received a instead.
s @ vuetify.js:436
```
When is this being targetted?

**Comment by KaelWD** [comment]
Soon&trade;
