### ISSUE TITLE
[Bug Report] Textarea border thickness is not correct

### ISSUE THREAD

**Issue by robertkern** [vuetifyjs/vuetify#3613]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a `v-text-field` with `textarea` prop.

### Expected Behavior
> Text areas should have a visible border, using the same color and thickness as the input line.

The above text is taken from https://material.io/guidelines/components/text-fields.html

### Actual Behavior
Text area thickness appears to be twice as thick as an input line.

### Reproduction Link
[https://codepen.io/anon/pen/yKVogR](https://codepen.io/anon/pen/yKVogR)

**Comment by johnleider** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/pull/7136
