### ISSUE TITLE
[Bug Report] Radio Button - Title attribute not supported

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3615]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.13
**Browsers:** Firefox 59.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
Hover over the radio wrapper.  No title.  Preferably it'd be the title on anywhere that would activate the input, such as the label.  

### Expected Behavior
There to be a title

### Actual Behavior
No Title

### Reproduction Link
[https://codepen.io/gabaum10/pen/oqYrdm](https://codepen.io/gabaum10/pen/oqYrdm)

**Comment by jacekkarczmarczyk** [comment]
Currently title goes to the hidden `<input type="radio">`

**Comment by johnleider** [comment]
This issue is resolved as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
