### ISSUE TITLE
[Bug Report] v-tabs is not updating lazyValue properly

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3617]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 7

### Steps to reproduce
- Open the reproduction link https://codepen.io/anon/pen/XEpmrR
- No tab should be active, but "Pricing" is active;
- Navigate to "/about";
- The "About" tab is active as expected;
- Navigate to "/other";
- No tab should be active, but "About" is active.

### Expected Behavior
- No tab should be active as default (before routing);
- No tab should be active when in other route than "/pricing" or "/about".

### Actual Behavior
The last tab stays active when the current route doesn't match to any tab `:to`

### Reproduction Link
[https://codepen.io/anon/pen/XEpmrR](https://codepen.io/anon/pen/XEpmrR)

### Other comments
The behavior I expect for tabs is that a tab is active only when it is on its route (or its children).

**Comment by chewy94** [comment]
I think this is just a wrong interpretation of what the `:to` prop is doing. `:to` should just define where clicking the tab will route to, not whether or not the tab is selected.

Can I get a confirmation from @vuetifyjs/dev-team ?

**Comment by KaelWD** [comment]
`to` should also select the tab so that you can link to a specific one. What's happening here is that it automatically selects the first one if no match is found.

**Comment by johnleider** [comment]
This will be resolved in the next alpha (tomorrow). One caveat is that tabs are mandatory by default. To facilitate this behavior there is a new prop, **optional** which will allow the component to deselect if there are no values. A few other points:

- lazyValue -> internalLazyValue
- Route for `/` and `/other` will not enter the model as they do not exist as an activatable item within the `v-tabs`

![tabs](https://user-images.githubusercontent.com/9064066/53747573-2c771280-3e69-11e9-83a6-6084c15e8c48.gif)

**Comment by johnleider** [comment]
Fixed in f22d754
