### ISSUE TITLE
[Feature Request] Mouseover and Mouseout events not quite working on v-text-field

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#3619]
### Problem to solve
Say you have a v-text-field with an appended icon. You want icon to only display on hover. If you put mouseover and mouseout events on the v-text-field, the mouseout function its gets fired constantly. So you have to move the events to the v-flex parent element. This is not always desirous since the handler size now includes the v-flex margin and padding.  Codepen with issue: https://codepen.io/anon/pen/vRgGKe

### Proposed solution
Move/copy the event handlers to include the append-icon container, debug mouseout event? Not exactly sure...

**Comment by nekosaur** [comment]
1. What exactly is not working in the codepen you posted? For me the icon appears on hover.

2. All inputs are getting refactored for 1.1 so this might no longer be relevant when it releases

**Comment by blalan** [comment]
1. If you hover over the field, it shows fine, however if you hover over the icon itself, it flashes as if mouseover and mouseout are both firing repeatedly.

**Comment by blalan** [comment]
Windows 7, Chrome 65 and Firefox 59

**Comment by johnleider** [comment]
The recommended way to handle this: https://codepen.io/johnjleider/pen/MGBXrY?editors=1111

When you apply the mouseover to the text-field, it will cause mouseout to be fired when hovering over the icon. Apply it to a different element.
