### ISSUE TITLE
[Bug Report] v-card-media: image-links with parentheses aren't recognized

### ISSUE THREAD

**Issue by schlensen** [vuetifyjs/vuetify#3625]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.2

### Steps to reproduce
Create a v-card with v-card-media and use an image-link with parentheses as src, e.g.:
/linkto/foo(2).jpg

### Expected Behavior
Image shown as background

### Actual Behavior
Image not shown

### Reproduction Link
[https://codepen.io/Schlensen/pen/oqBEye](https://codepen.io/Schlensen/pen/oqBEye)

### Other comments
(Hopefully no duplicate - couldn't find anything similar)
In the Codepen I took the example from the v-card docs (https://vuetifyjs.com/en/components/cards) and provided an image-link with parentheses - the background is not shown.
Without parentheses (your example-image) everything is fine. For me it's a severe problem because those parentheses are added by the OS (in general any OS) automatically if there is already another file with the same filename.

Tested on Chrome, Opera and Safari.

**Comment by praveenpuglia** [comment]
It's because VCardMedia should put the url in quotes or else it'll create parsing problems and the entire style won't get applied. Sending in a PR to fix this soon! :)

**Comment by schlensen** [comment]
Awesome fast response! Thank you very much!
