### ISSUE TITLE
[Bug Report] Right navigation drawer animation glitch on page change and activation

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#3629]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.3.3
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.12.6

### Steps to reproduce
1. Have two pages, one with a *right* drawer. On that page component, have the drawer opened by default
2. Wrap `<router-view/>` in a transition.
3. Change from page 1 to page 2.

### Expected Behavior
The drawer should translate left 100% and without the jumping/glitching.

### Actual Behavior
The drawer slides left more than 100% (looks like 200%). After transition is complete, it'll snap back to the right.

### Reproduction Link
[https://codepen.io/jaesung2061/pen/Brprog?editors=1010](https://codepen.io/jaesung2061/pen/Brprog?editors=1010)

### Other comments
I think this is caused because both the main content element (v-container or v-content?) is doing a transition at the same time. The main content area is shrinking while the drawer is transforming left.

**Comment by KaelWD** [comment]
As I said in discord, this is not a problem with Vuetify. Here's what's happening to your `otherPageTemplate` div while the transition is running: 
![image](https://user-images.githubusercontent.com/16421948/37696669-7da67b7c-2d2c-11e8-887a-85486aa87298.png)

Fixing this with css would be a pin in the ass, I'd recommend simply closing the drawer while the transition is running: https://codepen.io/anon/pen/eMvMgd?editors=1010
