### ISSUE TITLE
[Bug Report] data-table selected header highlight cropped from top

### ISSUE THREAD

**Issue by abdullah-saqer** [vuetifyjs/vuetify#3630]
### Versions and Environment
**Vuetify:** 1.0.9
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Mac OS 10.12.6

### Steps to reproduce
click on any table header.

### Expected Behavior
table header to highlighted from all directions 

### Actual Behavior
it will be highlighted from all directions with blue color except top of header it will be cropped and not visible even if there is space above table   

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

### Other comments
table__overflow this class has overflow-x auto and overflow-y hidden this case the issue

**Comment by jacekkarczmarczyk** [comment]
You didn't save the codepen

**Comment by abdullah-saqer** [comment]
https://codepen.io/abdullah-saqer/pen/yKMNmN?&editors=101

**Comment by chewy94** [comment]
Added margin top and it is visible to me

https://codepen.io/smkimbal/pen/VXrpvb

**Comment by johnleider** [comment]
The outline is removed in dev for v1.1.

https://github.com/vuetifyjs/vuetify/commit/720c6a867e6a58a8f584a7ddfc6c1d4ad0683473
