### ISSUE TITLE
[Bug Report] v-tabs-slider resize bug

### ISSUE THREAD

**Issue by fsx950223** [vuetifyjs/vuetify#3637]
### Versions and Environment
**Vuetify:** 1.0.9
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 10

### Steps to reproduce
1.click third tab
2.click menu icon
3.click menu icon

### Expected Behavior
slider returns to the old position

### Actual Behavior
slider becomes longer and leaves old position

### Reproduction Link
[https://codepen.io/fsx950223/pen/wmJXrj?&editors=101](https://codepen.io/fsx950223/pen/wmJXrj?&editors=101)

**Comment by FFxSquall** [comment]
It seems this will also solve my issues #3581
