### ISSUE TITLE
[Bug Report] v-tabs' v-model uses strings instead of numbers

### ISSUE THREAD

**Issue by destructive-dragon** [vuetifyjs/vuetify#3641]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Firefox 59.0
**OS:** Windows 10

### Steps to reproduce
The v-model input in the v-tabs component uses and requires string indices (like "0", "1", etc) for the individual tabs. If it's provided with Numbers instead, it causes odd behavior. In the codepen example, you need to click twice on the tabs in order for them to actually switch over. Note the + in line 15. If we remove it and thus are using strings instead of numbers, then everything works fine.

### Expected Behavior
Using Numbers for v-tabs should work normally and the v-tabs should return numbers.

### Actual Behavior
v-tabs requires and returns strings (stringified numbers, i.e. "0", "1", "2", ...) and can't handle actual numbers.

### Reproduction Link
[https://codepen.io/anon/pen/XERWmd](https://codepen.io/anon/pen/XERWmd)

### Other comments
An alternative solution or feature could be a prop to give each tab a custom string value that they respond to and thus make them act similar to the `value` of Selection Controls, as they are functionally very similar.

If on the other hand the decision to just use stringified numbers would be kept, then this gotcha should probably be documented.

**Comment by KaelWD** [comment]
I did suggest a `value` prop when we were rewriting tabs, don't remember the reason for not going with it though.
