### ISSUE TITLE
[Bug Report] "disabled" prop on tab doesn't disable tab

### ISSUE THREAD

**Issue by danielsvane** [vuetifyjs/vuetify#3644]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.2
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Add the "disabled" prop to any tab.

### Expected Behavior
The tab should not transition to its tabs-item element, since it's disabled.

### Actual Behavior
The disabled tab just functions like the "disabled" property wasn't set, except that the pointer cursor doesn't show when hovering it.

### Reproduction Link
[https://codepen.io/danielsvane/pen/LdyrZY](https://codepen.io/danielsvane/pen/LdyrZY)

### Other comments
I might have misunderstood what the "disabled" property is supposed to do.

**Comment by aemaething** [comment]
Hi guys,

maybe I miss a thing, but for me it seems the bug still exists as described above.
https://codepen.io/danielsvane/pen/LdyrZY

Is there any way to disable a tab completely?
Thanks!

**Comment by KaelWD** [comment]
That codepen is using 1.0.10

**Comment by aemaething** [comment]
I tried v.1.0.18 also:
https://codepen.io/anon/pen/vjMweV

**Comment by aemaething** [comment]
Argh, I just updated the JS part. Sry.
Thanks for help!
