### ISSUE TITLE
[Bug Report] VCheckbox rules do not react to external changes

### ISSUE THREAD

**Issue by gnarula** [vuetifyjs/vuetify#3646]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Mac OS 10.13

### Steps to reproduce
1. Select all 3 checkboxes
2. Unselect any checkbox but the last checked one

### Expected Behavior
The error should go away

### Actual Behavior
The error remains even though validation succeeds

### Reproduction Link
[https://codepen.io/anon/pen/aYWQvZ](https://codepen.io/anon/pen/aYWQvZ)

**Comment by jacekkarczmarczyk** [comment]
Fixed in 1.1
https://codepen.io/anon/pen/OEbjrW
