### ISSUE TITLE
Uncaught TypeError: Cannot read property 'complete' of undefined when i use the v-parallax component

### ISSUE THREAD

**Issue by shaotingg** [vuetifyjs/vuetify#365]
Hi
When i use the 'v-parallax' components it showed the error "Cannot read property ' complete' of undefined " if i reload the browser, The vuetify version is v0.10.4 .

The code:
`<v-parallax height="650" src="../static/images/download-banner-bg-01.jpg">
              </v-parallax>`

The error:
> Uncaught TypeError: Cannot read property 'complete' of undefined
    at VueComponent.init (bundle.js:39276)
    at HTMLDocument.boundFn (bundle.js:1012)

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
