### ISSUE TITLE
[Feature Request] Expansion Panel Header in action buttons

### ISSUE THREAD

**Issue by kucukahmet** [vuetifyjs/vuetify#3652]
Hi, firstly i am new to Vuejs and Vuetify.
I want to add a checkbox to the header slot. But I do not know how to do.
Because when checkbox selected. body is opened. I don't want this,
only checkbox should be selected. Body should not open.
Thanks :)

`<v-expansion-panel popout>
  <v-expansion-panel-content v-for="(item,i) in 5" :key="i">
    <div slot="header">
      <v-checkbox hide-details type="checkbox" v-model="selected" class="toggle todo-list-checkbox"></v-checkbox>
      ITEM
    </div>
      <v-card>
       <v-card-text class="grey lighten-3">Lorem ipsum dolor sit amet.</v-card-text>
     </v-card>
  </v-expansion-panel-content>
</v-expansion-panel>`

![ss](https://user-images.githubusercontent.com/11904609/37805340-9cc57bce-2e4a-11e8-8c03-c82b9372751f.png)

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

**Comment by MTyson** [comment]
Hm, a link to how to do this would be nice, if its already doable.

Otherwise, a feature request is appropriate here.
