### ISSUE TITLE
[Bug Report] Select scroll stops working after animation completed

### ISSUE THREAD

**Issue by mcipenuks** [vuetifyjs/vuetify#3653]
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
Here it also doesn't work https://issues.vuetifyjs.com/ . If you open select, you have something like 300ms to scroll, after animation is done you can't scroll anymore

### Expected Behavior
Should be able to scroll inside select any time it's open

### Actual Behavior
Scroll working only while animation is not completed

### Reproduction Link
[https://codepen.io](https://codepen.io)

### Other comments
No codepen link, just open select "for" on issue submit page https://issues.vuetifyjs.com/

**Comment by KaelWD** [comment]
Can't reproduce on windows.

**Comment by mcipenuks** [comment]
1) It works in Mozilla Firefox (52.7.2)
2) Don't have extensions, incognito didn't work.
3) In v-select examples it works differently, but still not quite there.
After animation complete, first few scrolls don't scroll the select but the page instead, only after multiple scrolls (up and down) it starts scrolling.

**Comment by cars10** [comment]
I experience the same issue. Chrome 65 in linux, cannot scroll in selects.

**Comment by nekosaur** [comment]
Checking in to say I just experienced this on the issues site as well.

Chrome 65.0.3325.181
Windows 10
