### ISSUE TITLE
[Feature Request] Default sorting without pagination

### ISSUE THREAD

**Issue by LanFeusT23** [vuetifyjs/vuetify#3658]
### Problem to solve
I want to be able to set a default sorted column without having to use pagination.
When pagination is not required we should still be able to sort by a default column. 

The current solution is to disable-initial-sort and have the data fed to the v-data-table pre-sorted.

### Proposed solution
Add a "default-sort-by" option to the datatable

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
