### ISSUE TITLE
[Feature Request] Multi column sorting on datatables

### ISSUE THREAD

**Issue by LanFeusT23** [vuetifyjs/vuetify#3659]
### Problem to solve
Multi sorting will allow to keep certains column permanently sorted in a certain way.

For example if I were to default sort my table by name, but then wanted to sort by age, all users of the same age should be sorted by name as well.

### Proposed solution
Add a "sort-by" array option

**Comment by jacekkarczmarczyk** [comment]
Duplicate of #2659

**Comment by jacekkarczmarczyk** [comment]
exactly 1000 issues between dups ;)
