### ISSUE TITLE
[Bug Report] Persistent v-edit-dialog in data table

### ISSUE THREAD

**Issue by lukashass** [vuetifyjs/vuetify#3662]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.14
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
* open a `v-edit-dialog` in the column *Iron*
* now sort some column of the table

### Expected Behavior
`v-edit-dialog` should be bound to the item it was opened on

### Actual Behavior
`v-edit-dialog` is bound to whatever item is in the row beneath it

### Reproduction Link
[https://codepen.io/lukashass/pen/WzEgXN](https://codepen.io/lukashass/pen/WzEgXN)

### Other comments
Reproduction is taken from documentation: https://vuetifyjs.com/en/components/data-tables#example-editdialog

**Comment by chewy94** [comment]
This does appear to be an issue here. I think `v-edit-dialog` is part of the work for v1.1 so we may lump this in there

**Comment by KaelWD** [comment]
Rows need to be keyed, dunno what's happening with #2662. You can do it yourself with `:key="props.item.name"`.

**Comment by johnleider** [comment]
This component is being removed in v3. We will provide an upgrade path.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
