### ISSUE TITLE
[Feature Request] Need scale / rating component

### ISSUE THREAD

**Issue by davidmw** [vuetifyjs/vuetify#3665]
### Problem to solve
Allow button selection of integer value within a range of N to M. For example a survey form might ask for 'pain on a scale of 0 to 10' to be selected from an array of 11 buttons with button numbers as the label. Or buttons could be icons that change color - five stars for movie ratings as an example.

### Proposed solution
The Pagination component would satisfy my immediate need for integer button range if I could hide the `next` and `prev` buttons.

**Comment by KaelWD** [comment]
I swear there was already a star rating feature request but I can't seem to find it. For 0 - 10 you can either use v-btn-group or just a bunch of buttons next to each other.

**Comment by davidmw** [comment]
Maybe you mean `v-btn-toggle` for 0-10. I had been ignoring it since the doc implies a toolbar is needed but it looks useful.  I do need it to function like a radio button.  For star rating you'd want everything to the left of the tap to be selected and everything to the right unselected. This could again be done with `v-btn-toggle` maybe with a slight modification. Hugely flexible this way in terms of picking which icons to use but need two icons for each slot.

**Comment by davidmw** [comment]
Actually it would be repetitive in code to specify two icons each time for five stars.  Ratings usually use the same icon for the entire range and can't image needing anything beyond that.
