### ISSUE TITLE
[Bug Report] Tab slider does not show when inside a VToolbar and enabling the "icons-and-text" prop 

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#3668]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.3

### Steps to reproduce
Enabling `icons-and-text` flag on a VTabs inside a VToolbar, as per documentation.

### Expected Behavior
Slider should appear as it does when the flag is not present.

### Actual Behavior
Slider does not show.

### Reproduction Link
[https://codepen.io/anon/pen/Ovxpqe](https://codepen.io/anon/pen/Ovxpqe)

**Comment by KaelWD** [comment]
The extension needs to be 72px high with `icons-and-text`: https://codepen.io/anon/pen/qoPVRE?editors=1010

**Comment by KaelWD** [comment]
Turns out I actually brought this up on discord a while ago
![image](https://user-images.githubusercontent.com/16421948/37889760-a97a7bfe-3119-11e8-9692-818ff5b33735.png)

**Comment by johnleider** [comment]
This is resolved as of the latest version: https://codepen.io/johnjleider/pen/MWYzaXP

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
