### ISSUE TITLE
[Bug Report] Text in a v-list cannot be selected for copy and paste

### ISSUE THREAD

**Issue by craigbroadbear** [vuetifyjs/vuetify#3669]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.2
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
Try and click on text to select with mouse - cant do it.

### Expected Behavior
It lets you copy and paste text.

### Actual Behavior
You cant select any text in the list.

### Reproduction Link
[https://jsfiddle.net/5a8z5xws/3/](https://jsfiddle.net/5a8z5xws/3/)

### Other comments
I have a lovely looking list that the users wish to copy certain text chunks with their browser and they cannot .  i will have to resort to making my own list which will not be as nice.

**Comment by KaelWD** [comment]
f67dd403b44b66b2ef77e5f7132399580d5cc51f

I think it's meant for mobile so you can't accidentally select words when clicking on a link.

**Comment by jacekkarczmarczyk** [comment]
Maybe user-select could be set to none only if it's a link?

**Comment by KaelWD** [comment]
Sounds alright to me, @nekosaur?

**Comment by nekosaur** [comment]
That sounds alright :+1:

**Comment by ebisbe** [comment]
What would be your prefered way of solving it?

If `:to`, `:nuxt` or `:href` is defined:
- add a class `non-selectable` with `user-select: none`
- add a `style: user-select:none`

Remove that property from the main class.
