### ISSUE TITLE
[Feature Request] How to select all on <v-select>?

### ISSUE THREAD

**Issue by trucb1203981** [vuetifyjs/vuetify#3670]
### Problem to solve
I want to choose select all city but I don't know how to do. Can anyone help me?

**Comment by AlexSHoffman** [comment]
@trucb1203981 
Are you trying to toggle multiple checkboxes buy clicking one "select-all" checkbox? 
If so, just specify the same `v-model` for all checkboxes as it's on the "select-all" checkbox

Codepen:
https://codepen.io/anon/pen/QmqBqx

P.S.
You should post questions on stackoverflow. Github is for reporting bugs/feature requests

**Comment by AlexSHoffman** [comment]
@trucb1203981 
You should google these type of questions first. Github is for reporting bugs/feature requests

There are several answers on the internet already:
https://codepen.io/jh-thank-you/pen/qjVWOj
https://stackoverflow.com/a/34019361/6171895

**Comment by KaelWD** [comment]
Thanks Alex. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by trucb1203981** [comment]
Thanks Alex. 
Because I don't know keywords to search.
Thank you very much
