### ISSUE TITLE
[Feature Request] Navigation drawer backdrop handler

### ISSUE THREAD

**Issue by conradolk** [vuetifyjs/vuetify#3671]
It would be great if you could get a callback if the user touches the grey overlay for closing the sidebar, for informing Vuex for example that the sidebar is now closed. There is no way to do this i think.

`<v-navigation-drawer :onBackdrop="handleBackdrop()">` or something like that.

**Comment by KaelWD** [comment]
It already emits `input`, or you can use v-model.
