### ISSUE TITLE
[Bug Report] Sorting issue for non-english locales

### ISSUE THREAD

**Issue by dmitrij-schmidt** [vuetifyjs/vuetify#3672]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
Create a sortable table, where sorted values contain any non-standard (non-english) characters, and try to sort them by the name, or just run a codepen link.

### Expected Behavior
String values should be sorted correctly in alphabetical order.

### Actual Behavior
String values are not sorted correctly. Character "Ł" based on a standard latin "L" is pushed to the end of sorted array.

### Reproduction Link
[https://codepen.io/dmitrij-schmidt/pen/geGvza](https://codepen.io/dmitrij-schmidt/pen/geGvza)

### Other comments
Possible solution http://www.jstips.co/en/javascript/sorting-strings-with-accented-characters/

**Comment by KaelWD** [comment]
You can use `custom-sort` for this, but it is extremely not user-friendly and can probably be improved. 

https://codepen.io/anon/pen/dmVKog?editors=1010

**Comment by Aramis13** [comment]
Hey, I am new here can i take a shot at this?

**Comment by jacekkarczmarczyk** [comment]
Yup, you can take a look at the closed PR (and comments in that PR), be sure that you're working on `next` branch

**Comment by Aramis13** [comment]
I am having some trouble finding the files from the PR can you direct me please

**Comment by jacekkarczmarczyk** [comment]
i think you need to search for `sortItems` in helpers.ts and VData.ts

**Comment by Aramis13** [comment]
I opened a PR, Let me know if it meets the standards.

**Comment by jacekkarczmarczyk** [comment]
Thank you, looks like some tests have failed though

**Comment by Aramis13** [comment]
Oops first time :)
I made the fix but now there are checks that failed.
