### ISSUE TITLE
[Bug Report] v-select filter not effective when items are selected and no query is given

### ISSUE THREAD

**Issue by iota-pi** [vuetifyjs/vuetify#3675]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
Have a `v-select` with the `autocomplete` and `filter` props. Click on the `v-select`, the list of items will be correctly filtered. Select any item, then check again before typing any text - the list of items is not filtered at all. Type any character and then delete it (i.e. query string is now `''` not `null`), and the items will be correctly filtered.

### Expected Behavior
Filter should be used even when some items are selected and `querystring === null`

### Actual Behavior
Filter is only used if:

* No items have been selected
* Or, a query string has been typed in

### Reproduction Link
[https://codepen.io/anon/pen/JLOXop](https://codepen.io/anon/pen/JLOXop)

**Comment by johnleider** [comment]
This is not the purpose of the filter prop. The fact that it does what it does for the first autocomplete is a bug. The **filter** prop is the algorithm that the data is passed through while searching. If you need to mutate the items in such a way, you should do that in a computed property, then pass that to your inputs.
