### ISSUE TITLE
[Feature Request] Support for z-depth-x

### ISSUE THREAD

**Issue by vincebanzon** [vuetifyjs/vuetify#3677]
### Problem to solve
Capability to adjust the shadow of the navigation bar by simply adding class="z-depth-1"

### Proposed solution
Add support for class "z-depth-1" or make some useful attribute.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/layout/elevation

**Comment by vincebanzon** [comment]
Thank you so much KaelWD. My suggestion isn't even a solution for it compared to elevation.
Elevation is a great helper. Thanks.
