### ISSUE TITLE
[Bug Report] Unsupported fast-in-slow-out transition at v-progress-linear component

### ISSUE THREAD

**Issue by beatgrabe** [vuetifyjs/vuetify#3678]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 10

### Steps to reproduce
The issue is more a source code related issue. The translation `fast-in-slow-out` used in `v-progress-linear` to be found here:
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_progress-linear.styl#L14
and here:
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_progress-linear.styl#L19

Has no belonging reference in the stylus translation variable:
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/settings/_variables.styl#L113

### Expected Behavior
The `$transition.fast-in-slow-out` variable should have a related entry in the `stylus` translation variables.

### Actual Behavior
Falls back to initial `transition-timing-function`

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_progress-linear.styl#L14](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_progress-linear.styl#L14)

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/37952863-ef3651d0-31ec-11e8-9048-2577e730d6ec.png)
