### ISSUE TITLE
[Bug Report] v-text-field labels need to raise when browser autofill completes the field

### ISSUE THREAD

**Issue by andyfusniak** [vuetifyjs/vuetify#3679]
![screen shot 2018-03-27 at 13 11 16](https://user-images.githubusercontent.com/21123937/37950286-31446506-31c2-11e8-9af0-6b322a74b0aa.png)
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.11.6

### Steps to reproduce
Fill in a dummy email and password such as

johndoe@example.com
testtest

Allow Chrome browser to offer autosave. Re-visit the page and you will see that the v-text-field labels are rendered over the top of the input text. 

### Expected Behavior
Expect the labels to raise above the input field.

### Actual Behavior
Labels are rendered over the top of the input field text.

### Reproduction Link
[https://codepen.io/mr6502/pen/geXxZQ](https://codepen.io/mr6502/pen/geXxZQ)

### Other comments
This can be achieved by detecting browser autofill within the UI JavaScript:

https://stackoverflow.com/questions/11708092/detecting-browser-autofill

Note, this is not to be confused with autocomplete.

**Comment by mr6502** [comment]
To add clarification as @kgrosvenor mentioned in #2792 "this is a UI bug, i just raised the same issue - if field has some text in it, we could add the class that adds the label above on the page render, can we re open this issue?"

@manico also points out "That does not sound like autocomplete but Chrome autofill feature." which I agree with.

**Comment by johnleider** [comment]
Normally this affects the password field, as chrome does not register the autofill as an input event. I'll take another look as we progress in the form refactor for v1.1

**Comment by 185driver** [comment]
+1 on a desire to see this rectified. It happens for me on each field Chrome autofills, not just the password.

An observation: `input-group--dirty` doesn't get applied to an auto-filled input until I interact with the view. I need only to mouse click anywhere on the page and `input-group--dirty` gets applied.

I'm looking for a workaround in the interim. I've tried:
```
  mounted () {
    this.$nextTick(function () {
      console.log(this.password);
    });
  }
```
but no joy. Thanks for your help.

**Comment by KaelWD** [comment]
To be fair, even google's own login form has the same problem. I believe that was the justification for closing the other issues as wontfix.

**Comment by johnleider** [comment]
This is due to a bug with Chrome. We can revisit this later in life if they ever fix it.

**Comment by kgrosvenor** [comment]
I still this this is a UI bug, as it doesn't happen with other frameworks i am using, surely its a CSS class and extra stylings to remove the default behaviour, or an autocomplete prop with boolean value?

**Comment by Partoo** [comment]
Just add a fake text-field on the top, like below:
```v-text-field(label="hidden" style="display:none")
```v-text-field(v-model="username" ...)
```...

**Comment by Mexarm** [comment]
@Partoo it does not worked for me:
```
...<v-flex>
                      <v-text-field label="hidden" style="display:none"></v-text-field>
                      <v-text-field name="email" label="Email" id="email" type="email" v-model="email" required></v-text-field>
                    </v-flex>...
```
The UI in chrome (Version 67.0.3396.99 (Official Build) (64-bit)): 

<img width="480" alt="screen shot 2018-07-26 at 10 53 35 am" src="https://user-images.githubusercontent.com/10228591/43273658-a0010fd0-90c2-11e8-9435-667c41b76ac1.png">
