### ISSUE TITLE
[Bug Report] Button click triggers an extraneous blur event

### ISSUE THREAD

**Issue by salomvary** [vuetifyjs/vuetify#3683]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Firefox 59.0
**OS:** Mac OS 10.12

### Steps to reproduce
- Open the reproduction link above
- Click on "Vuetify button"
- Look at the developer tools console

### Expected Behavior
Only a "click" event should be triggered. 

### Actual Behavior
A "blur" event is triggered followed by a "click".

### Reproduction Link
[https://codepen.io/anon/pen/WzXgGY?editors=1010](https://codepen.io/anon/pen/WzXgGY?editors=1010)

### Other comments
For comparison the reproduction link contains a plain button and Vue (but not Vuetify) managed one. None of these have the issue the Vuetify button one has.

The problem lies in [VBtn.click](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VBtn/VBtn.js#L92) where a blur() is intentionally called. The comment above says "Prevent focus to match md spec" which I assume refers to avoiding buttons getting focused after click (could not find this in the Material Spec though). Despite this, I think the button should still not emit a blur event.

Not sure if/how possible, but the best would be to make sure the button does not *look* focused without actually messing with its focused state (this is how native buttons behave in Chrome).

**Comment by johnleider** [comment]
So I made a mistake with this. It was explicitly there for this: https://material.io/guidelines/components/buttons.html#flat-buttons-figure-caption-8
