### ISSUE TITLE
[Feature Request] Add Transition Property to Data Iterator and Data Tables

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#3684]
### Problem to solve
I think its better to add transition between switching filter result.

### Proposed solution
Add transition property.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

**Comment by DjSloth** [comment]
You should

**Comment by marshallswain** [comment]
Let's remember that it's open source, so johnleider "should" do it as much as you "should" do it yourself.  Dropping "shoulds" on others doesn't support you or them.

The feature doesn't line up with goals for the Vuetify project.  If it lines up more with your goals for ***your*** projects, then maybe consider doing it yourself.  You could also consider having a conversation with @johnleider to find out what would make it worth his time to implement the feature.  Maybe you could even pay him to do it.

I'm glad this has been clearly communicated as a "wontfix".
