### ISSUE TITLE
[Bug Report] Preventing users from switching tab but tab-content disappears

### ISSUE THREAD

**Issue by MengtiSun** [vuetifyjs/vuetify#3686]
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.7
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.11.6

### Steps to reproduce
We asked the question "if its possible to prevent a user from switching tabs" in discord, and jacek replied with the link: https://codepen.io/anon/pen/qojoPR?editors=1010

It works good in this link. But when we put the code in our project, its tab-content is not there.

Steps to reproduce:
1. Click tab2, there will be a popUp that stops you from going to tab2. You stay in tab1, but its content is gone.
2. Open the developer tool to check the tabs-content element. You can see
div class="tabs__content tab-transition-leave-to" id="undefined" style=""
If you remove the className "tab-transition-leave-to", the content is back

### Expected Behavior
When switching tabs is prevented, I wish to see the content under the old tab

### Actual Behavior
The content is gone

### Reproduction Link
[https://codesandbox.io/s/vnlqvzl5m5 ](https://codesandbox.io/s/vnlqvzl5m5 )

**Comment by jacekkarczmarczyk** [comment]
You're using `key` props for `v-tab` and `v-tab-item`, you should use `href` and `id` respectively
I wasn't able to make that codesandbox working with this changes though, but as it works with codepen it seems that this might be a problem with codesandbox, not with Vuetify.
