### ISSUE TITLE
Feature Request: Floating Action Button (FAB)

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#369]
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior

**Comment by mornir** [comment]
Example of material FABs using Vue.js : https://github.com/PygmySlowLoris/vue-fab

**Comment by Izopi4a** [comment]
+1

**Comment by ram-you** [comment]
+1

**Comment by zeljic** [comment]
+1

**Comment by diazemiliano** [comment]
+1

**Comment by genu** [comment]
As of `0.12.2` it looks like a basic fab can be created with:

This isn't documented as of yet.

```html
<v-fab>
    <v-icon>add</v-icon>
</v-fab>
```

It may be possible to build more complex fabs, I just haven't experimented. It looks like its a fairly involved implementation so I suspect its possible.

**Comment by johnleider** [comment]
Yea, I didn't mean for that to slip through but git is fun.

**Comment by ghprod** [comment]
:+1:

**Comment by fabiomigliorini** [comment]
https://dev.vuetifyjs.com/components/floating-action-buttons ... almost there... thanks...

**Comment by johnleider** [comment]
Yes getting very close!

**Comment by ghprod** [comment]
Great.. Thanks

**Comment by johnleider** [comment]
This functionality is in dev and complete.
