### ISSUE TITLE
[Bug Report] Missing rows-per-page property on data-table, not able to set it programmatically

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#3694]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
I want to set the rows-per-page property programmatically (based on the window height ...) on data-table.
But there is no rows-per-page attribute, only rows-per-page-items.
When I set rows-per-page-items programmatically  it doesn't work.

### Expected Behavior
Able to set rows-per-page programmatically

### Actual Behavior
Doesn't work

**Comment by KaelWD** [comment]
It's part of the pagination object: https://vuetifyjs.com/en/components/data-tables#example-paginate
