### ISSUE TITLE
[Bug Report] TextField Box color

### ISSUE THREAD

**Issue by JesusCrow** [vuetifyjs/vuetify#3695]
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.3.3
**Browsers:** Chrome 67.0.3381.1
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a `TextField` with `box` style.
Add preferred color with `color` attribute.

### Expected Behavior
`TextField` should be styled, depending on color.

### Actual Behavior
Nothing happens to styling. Element stays the same.

### Reproduction Link
[https://codepen.io/anon/pen/mxpYMz?editors=1010](https://codepen.io/anon/pen/mxpYMz?editors=1010)

### Other comments
Also tried adding color class to element. Which styles it in a wrong manner.

**Comment by KaelWD** [comment]
This was added in v1.1.0 with #4353: https://codepen.io/anon/pen/QBJJQB?editors=1010
