### ISSUE TITLE
[Bug Report] [v-dialog] Dialog allows clicking while the dialog is animating to close.

### ISSUE THREAD

**Issue by stevencherry1** [vuetifyjs/vuetify#3696]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.14
**Browsers:** Firefox 61.0
**OS:** Windows 10

### Steps to reproduce
1. Open modal
2. Click on the save button
3. While loading icon is running, rapidly continue to click on the save button

Before the dialog closes, but after the loading is finished, you can get a couple more clicks in before the modal closes

### Expected Behavior
While dialog is closing, nothing inside should be clickable

### Actual Behavior
While dialog is closing, you can still click on buttons inside.

### Reproduction Link
[https://codepen.io/makotech222/pen/zWpVaM](https://codepen.io/makotech222/pen/zWpVaM)

### Other comments
Workaround is to add a v-if to the buttons container to only show when action is needed.

**Comment by nekosaur** [comment]
I have a hard time imagining this is anything other than an extreme edge-case.

And if you do want to solve it, simply add a small delay after setting dialog to false and before setting loading to false to allow the modal to disappear.

**Comment by stevencherry1** [comment]
Yeah there are lots of workarounds for this issue. But is there any case where you would want click events to occur while dialog is closing?

**Comment by quezadaesteban** [comment]
Another workaround while it is improved would be to use a :disabled="loading" to disable buttons while the form is being sent. Or if the form is sent with ajax, a debounce should do it too.

**Comment by jamesgeorge007** [comment]
@KaelWD @stevencherry1 @MajesticPotatoe I would like to take this up :clap: I'm new here :beginner: 
It would be great if you could point me to the required files to work with :+1:

**Comment by blalan05** [comment]
If you haven't figured it out yet, probably start here:   vuetify/packages/vuetify/src/components/VDialog/VDialog.js

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
I cannot reproduce this with the latest version: https://codepen.io/johnjleider/pen/qBEQOJE

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
