### ISSUE TITLE
[Feature Request] VTabs - When setting tab value, scroll tab into view.

### ISSUE THREAD

**Issue by logiclabs** [vuetifyjs/vuetify#3699]
### Problem to solve
When loading a set of TTabs/VTab, if the currently active tab (set by value prop) is off-screen, it can't be seen by the user. This mostly affects mobile usage, where the tab bar width is reduced.

### Proposed solution
If the current item is off screen, the slider should scroll the currently active Tab into view.  This doesn't appear to be the case when setting the value prop.

**Comment by logiclabs** [comment]
This issue appears to have been caused by recent commit #3494.  Before this change, setting value prop would call this.tabClick(), which would then initiate a scrollIntoView().  This no longer happens (see d8faedc46fcb084ffd5939ec6486410199f3f268).

**Comment by jacekkarczmarczyk** [comment]
Please provide reproduction

**Comment by jacekkarczmarczyk** [comment]
Closed due to inactivity
