### ISSUE TITLE
CLI is failing

### ISSUE THREAD

**Issue by enricribas** [vuetifyjs/vuetify#37]
Seems like CLI and base project is failing.

```
vue init vuetifyjs/webpack-ssr app
cd app
npm install
npm run dev
```

localhost:8080 simply shows "undefined" in the browser window not console.
package.json reads ...  "vuetify": "0.7.*",
node v6.9.2
this also happens with "vue init vuetifyjs/webpack <app>"

**Comment by johnleider** [comment]
This has been resolved on all vuetify cli packages. For now, I'm going to leave this up because vue@2.1.7 has changes that effect SSR and I have no upgraded Vuetify to support it as of yet.

**Comment by johnleider** [comment]
I've identified the hurdle with upgrading Vuetify to Vue@2.1.7. Involved a bug with the router-link and the SidebarItem component. I've submitted a ticket for now, but I've also created a work around. Should be updating tomorrow.

**Comment by johnleider** [comment]
An update for anyone that comes in. There is currently a bug report on the main vue repo, [#4584](https://github.com/vuejs/vue/issues/4584).

**Comment by johnleider** [comment]
This is now resolved with the v.8.0 release.
