### ISSUE TITLE
Light and dark theme for sidebar?

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#370]
Is there a simple way to change the color theme of the sidebar? The background and text color seems hard coded to dark/white. I could change the background color by applying a `class="blue"` for example, but the text color does not update. I think it would be useful to have some more options to customize the theme for the sidebar, e.g. a dark and light option, and also make it inherit the `<color>--text` class.

**Comment by johnleider** [comment]
Great idea. Will do
