### ISSUE TITLE
[Feature Request] Can not apply hover with rowspan.

### ISSUE THREAD

**Issue by h-shiratsuki** [vuetifyjs/vuetify#3701]
### Problem to solve
Can not apply hover when using rowspan with v-data-table.

### Proposed solution
Even if tbody is used within the items slot of template, it will be expanded into automatically created tbody.
If there is tbody in the item slot of template, do not perform automatic creation like tr.
By applying it to tbody, hover can be performed even if rowspan is used.

### Reproduction Link
https://codepen.io/shiratsuki/pen/WzzoZW

**Comment by jacekkarczmarczyk** [comment]
Please provide reproduction

**Comment by h-shiratsuki** [comment]
Reproduction Link has been added.
Since tbody becomes double in this way, the layout collapses and hover also becomes double.

**Comment by johnleider** [comment]
This seems more like a bug report than a feature request. What does the desired outcome look like?

**Comment by KaelWD** [comment]
It shouldn't generate a `tbody` if the items slot is also a `tbody`
![image](https://user-images.githubusercontent.com/16421948/38404106-189988ce-39ab-11e8-8c6c-c9f027c9ed3d.png)

**Comment by ckitt** [comment]
Would like to ask if doing a rowspan/colspan aligns with the material design spec? It seems that the look and feel of the table changed a lot since we had tried it before in our production system, and it feels a little bit of strange...

**Comment by xavadu** [comment]
It may help https://codepen.io/paulofsis/pen/xfHtC

**Comment by cdecinkoKnight** [comment]
What is the status of this fix? I am having issues where adding tbody to the template causes a nested tbody element(s), which breaks the page. I need a way to not have v-data-table add tbody when the template contains any tbody.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
