### ISSUE TITLE
[Feature Request] Include an interactive demo to show how child elements alignment works

### ISSUE THREAD

**Issue by theCrius** [vuetifyjs/vuetify#3703]
### Problem to solve
Element's alignment is managed by the [Grid](https://vuetifyjs.com/en/layout/grid) documentation page that list the various props for v-layout and v-flex, like:

- align-baseline
- align-content-center
- ...

While it helps clarifying the props, imho it doesn't really help visualising a result unless you tinker with it and lose quite some time until you get accustomed to it.

### Proposed solution
Implement something like this interactive demo on the documentation page of [MaterialJS](https://material.angularjs.org/latest/layout/alignment) (scroll down the page) that allow you to easily see the result of the props you need to use.

I'm not versed enough in Vuejs yet to be able to write it myself unfortunately.

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #385](https://github.com/vuetifyjs/vuetifyjs.com/issues/385) via [**ZenHub**](https://www.zenhub.com/)
