### ISSUE TITLE
[Bug Report] Vuetify data table

### ISSUE THREAD

**Issue by easverasuthan** [vuetifyjs/vuetify#3705]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Create a headerless vuetify table like i have created in the link
2. Add a header simply.
3. Try to refresh multiple times and check if <td> remains at the same place.

### Expected Behavior
My vuetify table row css gets changed on refreshing the page and again it gets to its place after refreshing multiple times.

### Actual Behavior
It should remain at the same place.

### Reproduction Link
[https://codepen.io/easverasuthan/pen/JLpZRW](https://codepen.io/easverasuthan/pen/JLpZRW)

**Comment by nekosaur** [comment]
Your codepen does not work. First of all you've put the CSS in the JS section, and the JS in the CSS section. And you can't use import. [Here](https://template.vuetifyjs.com) is a pen you can start from which has vue + vuetify enabled.

**Comment by easverasuthan** [comment]
Hi,

I'm sorry for that last link. Below is the official link for vuetify table.
You can check there. It's not working properly in their official table.
Column data are not in the expected position.

https://codepen.io/pen/?&editors=101

**Comment by jacekkarczmarczyk** [comment]
You forgot to save it

**Comment by easverasuthan** [comment]
Hi,

Can you check now with the below link.

https://codepen.io/easverasuthan/pen/NYMVZo

**Comment by easverasuthan** [comment]
Hi,

I tried to use my code. But it wasn't working properly. So,i have sent you
the official link.

Thank You

**Comment by jacekkarczmarczyk** [comment]
Closed due to inactivity
