### ISSUE TITLE
[Feature Request] Use vue "à la carte" with the vuetify.min.css

### ISSUE THREAD

**Issue by titouancreach** [vuetifyjs/vuetify#3706]
### Problem to solve
When using the vuetify "à la carte" components,  is it required to use stylus-loader to load the component style. In my case, I've multiple javascript modules that share css. Each module can use vuetify or not. So I included `vuetify.min.css` direclty in the html. After I found my modules big, I decided to use à la carte components to reduce their size but unfortunately, it won't compile because of stylus.  

### Proposed solution
Choose if we want to compile css or only the javascript

**Comment by KaelWD** [comment]
Use something like [null-loader](https://github.com/webpack-contrib/null-loader) to ignore the .styl imports.
