### ISSUE TITLE
[Bug Report] Font awesome icons don't fit nice in avatar and buttons

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#3707]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
I took the example code of:
https://vuetifyjs.com/en/components/lists
and changed the material.io icons into font awesome

### Expected Behavior
a normal sized icon

### Actual Behavior
a really big icon

### Reproduction Link
[https://codepen.io/anon/pen/MVQzLV?&editors=101](https://codepen.io/anon/pen/MVQzLV?&editors=101)

**Comment by KaelWD** [comment]
- FA's JS isn't compatible with vue
- You need to load the icon CSS *before* vuetify itself

https://codepen.io/anon/pen/zWReOG?&editors=101
