### ISSUE TITLE
[Bug Report] Browser is slow when VDatePicker and VTimePicker are used together 

### ISSUE THREAD

**Issue by KingMackle** [vuetifyjs/vuetify#3709]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
* In the provided CodePen, there is a Date picker and a Time picker
* If you are using chrome, open chrome's task manager. Observe the CPU usage of the tab 
* Click 5 different dates in a row, or keep switching back and forth between two dates 
* You will notice that the CPU usage of the tab spikes up, the browser will begin to feel slow and heavy

Another route where this performance issue is not noticed:
* Remove the `v-model` attribute from the VDatePicker 
* If you are using chrome, open chrome's task manager. Observe the CPU usage of the tab 
* Click 5 different dates in a row, or keep switching back and forth between two dates 
* You will notice that the CPU remains cool, and no spikes 

### Expected Behavior
VDatePicker coupled with VTimePicker should not slow down the browser.

### Actual Behavior
VDatePicker coupled with VTimePicker causes the browser to feel heavy and sluggish 

### Reproduction Link
[https://codepen.io/geminitheking/pen/xWWEYK?editors=1010](https://codepen.io/geminitheking/pen/xWWEYK?editors=1010)

**Comment by bdeo** [comment]
I've experienced this as well. It causes jumpy animations and everything is a bit delayed.

**Comment by jacekkarczmarczyk** [comment]
That might be related to https://github.com/vuejs/vue/issues/6351 (not 100% sure though)

**Comment by KaelWD** [comment]
On my machine it spikes to ~20ms for the frame the click is in, which is reasonable for how complex the components are. This may be improved in the future as it's due for a refactor, but there is nothing immediately actionable for this issue.
