### ISSUE TITLE
Snackbar timeout is not reset

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#371]
### Steps to reproduce
This is how to reproduce this issue with the default timeout of 6000 ms.

1. Go to https://vuetifyjs.com/components/snackbars
2. Click the 'SHOW SNACKBAR' button
3. Click, as soon as possible, the 'CLOSE' button on the toast
4. Click, ~5 seconds after the click of step 2, the 'SHOW SNACKBAR' button again

Now the toast closes within a second. 

### Versions
Current and master versions of Vuetify.

### What is expected ?
The second toast should timeout after 6 seconds

### What is actually happening ?
The second toast closes after 1 second

### Reproduction Link
https://vuetifyjs.com/components/snackbars

**Comment by jmmk** [comment]
@johnleider 
It seems like this is not completely fixed. My use case is a Snackbar that responds to events. Currently it looks like:

1. Snackbar receives event, pops up with 6s timeout
2. Snackbar receives second event. Props are updated, but the same 6s timeout is running so it will always close after 6s from the original event

Example code:

Script (using `vue-class-component`):
```typescript
import {globalEventBus} from "index"

@Component
class MySnackbar extends Vue {
  text = ""
  show = false
  timeout = 6000

  created() {
    globalEventBus.$on('snackbarMessage', (text) => {
      // TODO: Can we clear the timeout here?
      this.text = text;
      this.show = true;
    })
  }
}
```

Template:
```vue
  <v-snackbar
    :timeout="timeout"
    :top="true"
    v-model="show"
  >
    {{ text }}
    <v-btn flat @click.native="show = false">Close</v-btn>
  </v-snackbar>
```

Is there any way to hook into the timeout to explicitly clear/reset it? I tried setting `this.show = false; this.show = true` in the event callback, but it didn't seem to have an effect (I'm not sure how often the watchers are re-computed in Vue, but I imagine this could be prone to race conditions anyway).

**Comment by jmmk** [comment]
@johnleider 

Found a solution using my own timeout (e.g. `setTimeout(timeout, () => show = false)`). I noticed there is a check for `if (this.timeout)`, so if I pass a falsy value (e.g. `:timeout="false"`) I can use my own timeout and control it however I want.

I think it's a good solution (no need for a modification to the snackbar component), the only thing missing is maybe documentation that `timeout` can be set to a falsy value to shut it off

**Comment by johnleider** [comment]
Very valuable feedback, thank you! I'll get the docs updated

**Comment by jmmk** [comment]
@johnleider Slight correction: The props specify `timeout` as `Number`, so currently it would need to be `0`. Still works for my case, but seems slightly hacky treating `0` as `false`

**Comment by johnleider** [comment]
It could probably support both. Any falsy value should work.

**Comment by YonathanB** [comment]
I'm trying to post my feedback here (maybe I should open a new issue, let me know)
I would like the snackbar to be displayed all the time: no timeout.
Only if user clicks on it it would be hidden.
Is it possible?
