### ISSUE TITLE
[Bug Report] scrollable does not work for v-dialog with v-form

### ISSUE THREAD

**Issue by natalya-semenova** [vuetifyjs/vuetify#3713]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
1. Create v-dialog with v-card, v-card-title, v-card-text and v-card-actions
2.  Enable `scrollable` 
3.  Add v-form for v-card, add `height` to  v-card-text
4. Resize screen to make dialog scrollable

### Expected Behavior
card-text to have overflow-y

### Actual Behavior
dialog has overflow-y

### Reproduction Link
[https://codepen.io/anon/pen/qooorY?editors=1010](https://codepen.io/anon/pen/qooorY?editors=1010)

**Comment by KaelWD** [comment]
Scrollable requires a specific structure, put the form inside `v-card-text` instead.

**Comment by natalya-semenova** [comment]
I need buttons (v-card-action) to be under the form to use button type attribute

**Comment by KaelWD** [comment]
Hmmm, I guess that is probably a common scenario. I think we can support just forms, I don't want to have too many special cases.

**Comment by ToxicWar** [comment]
👍

**Comment by tafel** [comment]
Is this functionality in the devs pipe? I just ran into the exact same problem. I have a dialog scrollable with a form, and buttons are in the card actions. It should be very helpful to have all this working together.

Or maybe a suggestion of how to accomplish this in an other way?

**Comment by halimb** [comment]
Same problem here

**Comment by alvarosacari** [comment]
Same problem here D:

**Comment by tafel** [comment]
> Hmmm, I guess that is probably a common scenario. I think we can support just forms, I don't want to have too many special cases.

@KaelWD you said on April that you didn't want too many scenarii to manage. I'm ok not to implement this in the core, if it's what the team want. But should it be possible to have a little snippet showing how to make this working together?
Many thanks

**Comment by bruddah** [comment]
There's also something wrong with transitions too - in chrome v-dialogs with v-form have glitchy appearing-transition. I've modified the example above, to demonstrate the case (added buttons to toggle "show" state): 

https://codepen.io/bruddah/pen/bPqNKJ

**Comment by bruddah** [comment]
There's also something wrong with transitions - in chrome v-dialogs with v-form have glitchy appearing-transition. I've modified example above, to demonstrate this case (added buttons to toggle "show" state): 

https://codepen.io/bruddah/pen/bPqNKJ
