### ISSUE TITLE
[Feature Request] include any default icons in the vuetify module

### ISSUE THREAD

**Issue by tsraza** [vuetifyjs/vuetify#3716]
### Problem to solve
Components do not render because it cannot find material icons.  I'm having trouble getting them loaded via html, import, @import, etc.

### Proposed solution
Embed icons (base64, svg, or otherwise) in the vuetify source code for any default icons used in components such as data-table, v-select, expansion-panels, etc.

**Comment by KaelWD** [comment]
The default icon set is from material.io, **not** materialdesignicons.com

All of our vue-cli templates already have the icons loaded out of the box. 

We will not be including icons in the framework, it is up to you to decide how you want to load them.

**Comment by tsraza** [comment]
For posterity: I was able to render the built-in icon references by explicitly importing said component (via vue-class-component) from the parent, even if it was rendered via <router-view>.
