### ISSUE TITLE
[Feature Request]  `v-list-tile` slots should also support `to` property

### ISSUE THREAD

**Issue by Traxo7** [vuetifyjs/vuetify#3718]
### Problem to solve

Inside `v-list`, only `v-list-tile` accepts `to` prop. By putting `to` on `v-list-tile`, we turn everything inside it into a link, and sometimes it's not what we want.

Currently, to make `div.list__tile__content` a link without altering avatar or actions we need  workarounds such as wrapping `v-list-tile-content` in `a` or `router-link` and then fixing css, or adding `@click.stop=""` on other components inside `v-list-tile` if `v-list-tile` is a link (i.e. it has `to` property).
Ditto `v-list-tile-title` and `v-list-tile-sub-title`.

For example we now have to do something like

 ``` 
<router-link :to="{name: 'Item', params: {id: item.id}}" class="list__tile__content" style="text-decoration: none; color: inherit">
    <v-list-tile-content>
        <v-list-tile-title v-html="item.title"></v-list-tile-title>
    </v-list-tile-content>
</router-link>
```

Instead of 
```
<v-list-tile-content :to="{name: 'Item', params: {id: item.id}}">
    <v-list-tile-title v-html="item.title"></v-list-tile-title>
</v-list-tile-content>
```

### Proposed solution
`v-list-tile-content`, `v-list-tile-title`, `v-list-tile-sub-title` should be able to accept `to` property.

**Comment by KaelWD** [comment]
I don't think this should be done, there's a lot more clickable area in a list than just the text: <https://codepen.io/anon/pen/JmxGxd?editors=1111>
It's very trivial to add `@click.stop` to the action (maybe it should be there by default?), and things like menus are supposed to stop propagation too (#3333). I don't know your exact scenario, but there's probably a better way to go about it that doesn't involve making simple components more complex than they need to be.

**Comment by Traxo7** [comment]
The problem I have with `@click.stop` is that whole tile is still rendered as a link (it would be misleading), thus I wanted only `title` and `sub-title` (which are in the `content` section) to be rendered as a link. Wrapping `v-tile-content` with the router-link broke my style a bit.

Also, sometimes we would want to have `title` direct to one link, and `sub-title` to redirect to another, but I presume we can just wrap them in the `router-link` and it wont break any styles:  

https://codepen.io/anon/pen/BqMWEJ

(Example use-case would be a list of songs in which each item is a song, and it's `title` redirects to song page, and `sub-title` to an artist page)

So perhaps this can be considered trivial as well, and no need to introduce additional props after all.

**Comment by KaelWD** [comment]
> that whole tile is still rendered as a link

What should it look like if only `v-tile-content` is a link? `<v-list-tile to=` isn't misleading imo because the non-link parts will have their own hover effects to indicate they are something separate (like the icon in my example).

I think your solution with router-link inside the components is acceptable, and I agree that in that case it wouldn't make sense to have the whole tile be a link. I'd probably keep text-decoration on hover to indicate which element will be activated however.

**Comment by Traxo7** [comment]
> What should it look like if only `v-list-tile-content` is a link? `<v-list-tile to=` isn't misleading imo because the non-link parts will have their own hover effects to indicate they are something separate (like the icon in my example).

The issue (on desktop) is that if we have `to` on `v-tile` then when we have `@click.stop` on any child (e.g. action), hovering over that element will still tell us that it's a link, even when it's not (because of `@click.stop`)  
https://codepen.io/anon/pen/XxOPMx

**Comment by johnleider** [comment]
In the rewrite **@click** does not turn the element into an anchor tag. Only if **href** or **to** is present (or you specifically define it with **tag**).  To the rest of the request:

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
