### ISSUE TITLE
[Feature Request] Add scroll props to bottom navigation

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3721]
### Problem to solve
Bottom navigation should have auto scroll behavior following the [specs](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior)

> #### Scrolling
> The bottom navigation bar can appear and disappear dynamically upon scrolling:
> - Scrolling downward hides the bottom navigation bar
> - Scrolling upward reveals it

### Proposed solution
Following the dialog props for this behavior, bottom navigation can have the props below:

scroll-off-screen
scroll-threshold
scroll-navigation-off-screen

But they work upwards by default.

**Comment by johnleider** [comment]
Note for me: This will be part of the toolbar abstraction.

**Comment by rajagopalx** [comment]
👍

**Comment by johnleider** [comment]
This was added in version v2.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
