### ISSUE TITLE
[Bug Report] Snackbar buttons misaligned

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#3727]
### Versions and Environment
**Vuetify:** `dev` as of 83d78fc3f3cdbb4385fc82112f1d6405434c8ee6
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Enable `vertical`
```vue
<template>
  <v-app>
    <v-content>
      <v-container>
        <v-btn @click="snack = !snack">show</v-btn>
        <v-slider v-model="length" :label="'' + length" max="30"></v-slider>
        <v-checkbox label="second button" v-model="second"></v-checkbox>
        <v-checkbox label="vertical" v-model="vertical"></v-checkbox>
        <v-checkbox label="multi-line" v-model="multiline"></v-checkbox>
        <v-checkbox label="auto-height" v-model="autoHeight"></v-checkbox>
        <v-snackbar right v-model="snack" :vertical="vertical" :multi-line="multiline" :auto-height="autoHeight" :timeout="0">
          {{ 'long text '.repeat(length) }}
          <v-btn flat color="warning" @click="snack = false" :ripple="false">undo</v-btn>
          <v-btn icon v-if="second">
            <v-icon>close</v-icon>
          </v-btn>
        </v-snackbar>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      length: 5,
      snack: false,
      second: true,
      vertical: false,
      multiline: false,
      autoHeight: false
    })
  }
</script>
```

### Other comments
Caused by #3704  
There is also too much space between the text and the button in single-line mode.

**Comment by Bingbazaar** [comment]
The vertical problem isn't caused by my pull request. I saw this before I made those changes too. You can see this for yourself just by "resetting" the margins in your browser's dev tools and enabling vertical again. 
The code in the Vuetify docs should also still use the "old" code, so you can see it there as well: https://vuetifyjs.com/en/components/snackbars

**Comment by KaelWD** [comment]
Nah it's from the PR.

Master: 
![image](https://user-images.githubusercontent.com/16421948/38481298-4cf80776-3c0d-11e8-8582-f423ed747aa6.png) 
![image](https://user-images.githubusercontent.com/16421948/38481335-807bbcaa-3c0d-11e8-91a7-453e3b7736c1.png)

Master + margin change:
![image](https://user-images.githubusercontent.com/16421948/38481350-9829af88-3c0d-11e8-9deb-12eb79bfc6c1.png)
![image](https://user-images.githubusercontent.com/16421948/38481361-a87f3b96-3c0d-11e8-8e14-ecf2936b48ad.png)
