### ISSUE TITLE
Bottom Nav must have be on the left if its on desktop or tablet

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#373]
https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

**Comment by mfferreira** [comment]
@ralphchristianeclipse Quoting:
_"Larger displays, like desktop, may achieve a similar effect by using side navigation"_

In other words, use a styled [sidebar](https://vuetifyjs.com/components/sidebar).
It's not the Bottom Nav job to jump to the side.

This will be eventually be done by the component using a prop like "rail, but for now you'll have to style it yourself.
