### ISSUE TITLE
[Bug Report] Selects loading indicator doesn't work when going solo

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#3735]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
Add a `v-select` component with loading set to true and solo.

### Expected Behavior
The loading indicator displays.

### Actual Behavior
The loading indicator does not display.

### Reproduction Link
[https://codesandbox.io/s/j2n9qplroy](https://codesandbox.io/s/j2n9qplroy)

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2399
