### ISSUE TITLE
[Feature Request] v-select select-all functionality

### ISSUE THREAD

**Issue by orccufin** [vuetifyjs/vuetify#3746]
#### select-all -functionality option:
Option to have "select all" functionality in v-select dropdown.
Can be highly valuable for some solutions.

### Proposed solution
I have no code to propose for select-all method, but styling could be so that select-all would be aligned as first item of the list and would have a separator line to the actual results.

**Comment by KaelWD** [comment]
One issue per feature please

**Comment by jacekkarczmarczyk** [comment]
That should be possbible with additional slots https://github.com/vuetifyjs/vuetify/issues/4061

**Comment by johnleider** [comment]
With the introduction of the above slots, I'm going to close this as resolved as the functionality can be easily done in user-land now.

**Comment by bernardocs** [comment]
I would like to point that there's a limitation to it...

Did the `Select all` code as it was written in the docs ( https://vuetifyjs.com/en/components/selects ) with 2000 items and it just freezes my browser for a moment before render the next frame.

I would guess that Vue reactivity to each item of the list is causing this... But in any case, you may not want to have a number much higher than 1000 items or so.
