### ISSUE TITLE
[Bug Report] Invisible breadcrumb element leads to breadcrumb divider without an item

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#3747]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
It's instantly visible.

### Expected Behavior
Don't show a divider without an item.

### Actual Behavior
It shows a divider without an item.

### Reproduction Link
[https://codepen.io/anon/pen/pLZJxQ?editors=1010](https://codepen.io/anon/pen/pLZJxQ?editors=1010)

### Other comments
I would like to use this in a real project (invisible item).

**Comment by KaelWD** [comment]
This filter needs to be run *before* setting `length`: https://github.com/vuetifyjs/vuetify/blob/8ac7de34a631745624fdac100a82eb7743ce8e73/src/components/VBreadcrumbs/VBreadcrumbs.js#L59-L62

**Comment by ndabAP** [comment]
Yeah, found that, too. It's a bug for me because it's a typical way of doing this in Vue.js.

**Comment by KaelWD** [comment]
Fixed by #3854
