### ISSUE TITLE
[Bug Report] Pagination isn't responsive

### ISSUE THREAD

**Issue by fsx950223** [vuetifyjs/vuetify#3759]
### Versions and Environment
**Vuetify:** 1.0.12
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1.click menu icon
2.click menu icon

### Expected Behavior
Pagination response when drawer is outing

### Actual Behavior
Pagination out of window

### Reproduction Link
[https://codepen.io/johnjleider/pen/rJdVMq](https://codepen.io/fsx950223/pen/ZxjPBg)

**Comment by Traxo7** [comment]
Afaics it responds properly when screen `width` increases, but not when it decreases?

**Comment by fsx950223** [comment]
Yes

**Comment by fsx950223** [comment]
solution [3813](https://github.com/vuetifyjs/vuetify/pull/3813)
