### ISSUE TITLE
[Feature Request] Provide way to not require v-model on selection components

### ISSUE THREAD

**Issue by hairylime** [vuetifyjs/vuetify#3767]
### Problem to solve
Was putting together a small general framework for managing bulk data changes against a grid of objects, ran into a problem caused by the restriction of the vuetify radio checkbox and switch components. 

Basically I have a proxy to record and manage changes against a list of objects - the inputs in this grid are bound by setting the value property to the proxy entry, and emitting input change events to the proxy. However I couldn't find a way to make this work with v-model, thus vuetify selection components broke the whole thing - had to hack it to manually detect changes when these components are present (much more complicated).

My take on v-model is that it is syntactic sugar in vue.js, so requiring it (not supporting the underlying binding / eventing model) seems broken.

### Proposed solution
I don't know enough about the underlying model, but ultimately I want to be able to set v-switch, v-checkbox, v-radio properties and bind to events separately, IE
`<v-checkbox :value="isSet" @change="changed" />`

**Comment by hairylime** [comment]
vuetify 1.0.11 if it matters

**Comment by jacekkarczmarczyk** [comment]
Use `input-value` instead of `value`: https://codepen.io/anon/pen/RMYaMa

**Comment by hairylime** [comment]
Ok, that worked - this should be probably changed into the documentation, as I was led astray by the statement at the top of this page - [`Selection Controls`](https://next.vuetifyjs.com/en/components/selection-controls)

**Comment by KaelWD** [comment]
That's an issue for https://github.com/vuetifyjs/vuetifyjs.com
