### ISSUE TITLE
Loading Images

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#377]
https://material.io/guidelines/patterns/loading-images.html#loading-images-behavior

Must use fade in and out transition

**Comment by johnleider** [comment]
This seems more of like a guideline for developers than something Vuetify would implement, no?

**Comment by ralphchristianeclipse** [comment]
@johnleider yeap its material design guidelines

**Comment by johnleider** [comment]
So what is the point of making it an issue here? Does it have relevance to a component in Vuetify?

**Comment by ralphchristianeclipse** [comment]
@johnleider when i'm using the v-carousel-item with a src on it there is no fading transition just like in the material design specs it's not good for the eye when you switch the src image dynamically

so basically following the guidelines will make sure that vuetify is really 100% material design

**Comment by johnleider** [comment]
The second example on the documentation for carousels is literally an example of a carousel with a fade transition.

**Comment by ralphchristianeclipse** [comment]
@johnleider what about the simple image like the v-card-row(img) ??? and the native img tag

**Comment by johnleider** [comment]
I appreciate your issues. But just posting a link is not useful. We are aware of the recent md spec update and we are working on it  if you want to post specific examples you feel should be targeted first. Paste that. Otherwise, asume until 1.0 release, if it's in the spec, we are working on it.
