### ISSUE TITLE
[Bug Report] Navigation drawer clipped moves app bar content

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#3783]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Just uncomment the navigation drawer to see the difference.

### Expected Behavior
The text-field and the help button should not move.

### Actual Behavior
The content of the toolbar is moving, as if the navigation drawer was not clipped.

### Reproduction Link
[https://codepen.io/Kleemer/pen/yKRoWV](https://codepen.io/Kleemer/pen/yKRoWV)

### Other comments
https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior
Here we can see that a permanent, clipped drawer should be under the app bar without changing the display of the bar.

**Comment by KaelWD** [comment]
You have to use `clipped-left` on the toolbar.
