### ISSUE TITLE
[Bug Report] Validation error is not visible after Ajax request without focusing the input field

### ISSUE THREAD

**Issue by vankov1** [vuetifyjs/vuetify#3784]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3389.0
**OS:** Mac OS 10.13.3

### Steps to reproduce
https://codepen.io/vankov1/pen/YajvWP

1. Click the save button
2. The error is not visible
3. Focus the field
4. Blur the field - now it is visible

### Expected Behavior
After clicking the save button, the error should become visible.

### Actual Behavior
The error is visible only after focusing and blurring an input field.

### Reproduction Link
[https://codepen.io/vankov1/pen/YajvWP](https://codepen.io/vankov1/pen/YajvWP)

### Other comments
I'm not sure whether a particular functionality is intended or a bug.
I have a function which takes two parameters - errorBag + error key, this function is applied to each input field I have using the rules props.

My problem is that when a props changes, the watcher which is defined in mixins/validatable.js has a strange if with comment:

// TODO: This handler seems to trigger when input changes, even though
// rules array stays the same? Solved it like this for now
if (newVal.length === oldVal.length) return
this.validate()

The data which is passed is an array, so when we compare the two arrays the length will be the same, however their content is different - [true] vs ["My ugly error"].
I've changed the if to: newVal.length === oldVal.length && oldVal == newVal
and this works for me.

My second problem is that the this.validate() on the next line is not using the force parameter. Without the force parameter the error is not displayed.
This is a problem in the situation where a user clicks the Submit button without focusing a particular input field, in this case the "shouldValidate" variable is false and the error returned from the ajax request is not visible.

I think the solution here is:

if (newVal.length === oldVal.length && oldVal == newVal) return
this.validate(true)
But I'm not sure whether this would break any other functionality.

**Comment by KaelWD** [comment]
As I said in discord, but you probably didn't see because it wouldn't let me `@` you: 
![image](https://user-images.githubusercontent.com/16421948/38404032-a2949632-39aa-11e8-9d4b-76b0b36cc769.png)
