### ISSUE TITLE
[Bug Report] Issue with initial width in tab item, affecting pagination

### ISSUE THREAD

**Issue by danielsvane** [vuetifyjs/vuetify#3787]
### Versions and Environment
**Vuetify:** 1.0.12
**Vue:** 2.5.2
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Put a pagination inside a tab item

### Expected Behavior
The pagination uses the full width of the tab item

### Actual Behavior
The pagination bases it available width on the initial width of the tab item, which might be 0.

### Reproduction Link
[https://codepen.io/danielsvane/pen/VXExMQ?editors=1010](https://codepen.io/danielsvane/pen/VXExMQ?editors=1010)

### Other comments
I have had this problem with other components than paginations, inside the tab item.

**Comment by nekosaur** [comment]
This is a known limitation (but perhaps not documented). See https://github.com/vuetifyjs/vuetify/issues/1924#issuecomment-333104232
