### ISSUE TITLE
Missing prop 'firstDayOfWeek' in v-date-picker API

### ISSUE THREAD

**Issue by aroue2** [vuetifyjs/vuetify#3788]
Hello, I'm not sure it's the right place to post this, but I just searched for something to change the 1st day of week in my date picker, and I realized a prop has been created in #622, but it doesn't appear in the doc https://vuetifyjs.com/en/components/date-pickers

**Comment by jacekkarczmarczyk** [comment]
For documentation issues please use https://github.com/vuetifyjs/vuetifyjs.com/issues repo.
But anyway - the prop does appear:
![image](https://user-images.githubusercontent.com/15625235/38411344-15a86d96-39b1-11e8-8773-66618f9b736d.png)
