### ISSUE TITLE
Scrolling Techniques for Toolbar

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#379]
https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior

**Comment by johnleider** [comment]
I don't think I'm going to be able to implement all of the different variations. However, the basic ones are now done.

**Comment by smiller171** [comment]
@johnleider One of the basic ones I expect is to be able to scroll the toolbar off screen and keep the tabs in view. I can't find documentation for how to accomplish this. Is it implemented?

**Comment by johnleider** [comment]
Yes this is possible to do with the scroll off screen prop. Please do not
post on old closed issues. Ty

**Comment by smiller171** [comment]
@johnleider I've just opened a new issue #3484 because this functionality appears to be broken.
