### ISSUE TITLE
[Bug Report] List Component can not react correctly

### ISSUE THREAD

**Issue by MDHD-NoobCoder** [vuetifyjs/vuetify#3795]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Press title2.
2. Then press title1. 

### Expected Behavior
title2 close and title1 open

### Actual Behavior
title2 closed but title1 didn't open.

### Reproduction Link
[https://codepen.io/MDHD/pen/MVzYde?editors=1011](https://codepen.io/MDHD/pen/MVzYde?editors=1011)

### Other comments
If give a default `active` value it can react correctly. For example:
```
{
    icon: 'near_me',
    title: 'title1',
    active: false,
    items: [
        { title: 'subTitle1', url: '', active: false }
    ]
}
```

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
