### ISSUE TITLE
[Bug Report] Scoped CSS lost when adding expand slot to data-table

### ISSUE THREAD

**Issue by markrmessmore** [vuetifyjs/vuetify#3797]
### Versions and Environment
**Vuetify:** 1.0.12
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Create and populate v-data-table.
2. Add CSS Styling for specific rows.
3. Add the 'expand' slot to the v-data-table.

### Expected Behavior
Styling remains when expand slot is added.

### Actual Behavior
Once the expand slot is added all styling disappears.

### Reproduction Link
[https://codepen.io/anon/pen/MVzJbB](https://codepen.io/anon/pen/MVzJbB)

### Other comments
I recognize that this may have something to do with the rows being counted however I would anticipate then simply other rows would be styled. However none seem to be receiving the styling.

**Comment by KaelWD** [comment]
This is a problem in **your** css. You need to change the selector to something like `:nth-child(4n+3)`
