### ISSUE TITLE
[Bug Report] Specify data table heights

### ISSUE THREAD

**Issue by ekreutzer** [vuetifyjs/vuetify#3804]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Firefox 59.0
**OS:** Mac OS 10.12

### Steps to reproduce
Simply place a data table within a card component with specified height. You can see in the codepen how the data table does not resize.

### Expected Behavior
Data table should resize to its parent component's height and width.

### Actual Behavior
Data table always overflows its parent component's container.

### Reproduction Link
[https://codepen.io/tkted/pen/VXVdbV?&editors=101](https://codepen.io/tkted/pen/VXVdbV?&editors=101)

### Other comments
This shouldn't really be an issue, as it is intuitive to have a data table component resize to its parent component's height. Please fix this ASAP, love the product but this bug is actually a deal breaker. Was considering purchasing the alpha themes, but without this functionality the entire package seems a little useless.

**Comment by ekreutzer** [comment]
setting height="inherit" of the parent component fixes this.

**Comment by jsmedmar** [comment]
@ekreutzer this doesn't fix it in code pen:

```vue
<div id="app"  >
  <v-app id="inspire">
    <v-card width="80px"  height="300px" class="elevation-20">
      <v-card-title>Data</v-card-title>
      <v-card-content >
        <v-data-table
      height="inherit"
      :headers="headers"
      :items="items"
      hide-actions
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
        <td class="text-xs-right">{{ props.item.calories }}</td>
        <td class="text-xs-right">{{ props.item.fat }}</td>
        <td class="text-xs-right">{{ props.item.carbs }}</td>
        <td class="text-xs-right">{{ props.item.protein }}</td>
        <td class="text-xs-right">{{ props.item.iron }}</td>
      </template>
    </v-data-table>
      </v-card-content>
    </v-card>
    
  </v-app>
</div>
```
