### ISSUE TITLE
Using Emmet with vuetify syntax

### ISSUE THREAD

**Issue by ezosher** [vuetifyjs/vuetify#3808]
Hey guys, thanks for the great platform, I was wondering how can I use Emmet/tab to auto complete tags with Vuetify. currently I need to write all the components from scratch or copy them, hope you guys have any solution cheers. #

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

Works fine for me:
![2018-04-08_22-03-26](https://user-images.githubusercontent.com/16421948/38467236-b418c606-3b78-11e8-96df-540c2f47ef44.gif)

**Comment by ezosher** [comment]
Hey @KaelWD  sorry and thanks il check it out cheers, funny its not working doe, are you using atom ? did you made any settings ?
