### ISSUE TITLE
[Bug Report] Weird @input behavior on combobox

### ISSUE THREAD

**Issue by pdcmoreira** [vuetifyjs/vuetify#3811]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
A.
  1. Select an option
  2. Clear (press X button)

B.
  1. Search for an option
  2. Choose wanted option with arrow keys and enter

### Expected Behavior
A. An 'input' event should be emitted with value null.
B. Only one event should be emitted which is the selected object.

### Actual Behavior
A. 'input' event not emitted.
B. Two 'input' events are emitted: first the item-value and then the item-text, neither being the correct thing to emit.

### Reproduction Link
[https://codepen.io/anon/pen/geZpxJ](https://codepen.io/anon/pen/geZpxJ)

### Other comments
Input is also emitted a 3rd time, on blur, but that shouldn't be a problem.
Selecting the options with the mouse emits the object correctly.

**Comment by pdcmoreira** [comment]
Also, it doesn't react to external clearing. If you press the "Clear" button in the codepen below, the 'selectedItem' becomes null, but the v-select doesn't react to it.
https://codepen.io/anon/pen/KobdmZ

**Comment by pdcmoreira** [comment]
Using `return-object` helps by making it emit the object when it was emitting the id, but it still emits the item's text. Also, external clearing is still weird.

I guess I'll just have to make my own select

Updated codepen:
https://codepen.io/anon/pen/PRXRYw

Also, if I just use plain strings for items, the behaviour is kind of the same:
https://codepen.io/anon/pen/EEGLgx

Try searching for "jo" and then select John with arrows and enter: it emits twice.
Then, while the select is still focused, if you click the "Clear" button, it emits "John" again and doesn't clear. The second time you click "Clear" (the select is out of focus now), it clears but still doesn't emit the input event with `null`.

I'm pretty sure this can't be by design, any use case I can think of requires some workaround.

**Comment by KaelWD** [comment]
Ok that bit does look like a bug. 

>  it clears but still doesn't emit the input event with `null`

It isn't supposed to, *you*'re the one changing that.

**Comment by Renato66** [comment]
You can use @change instead of @input

**Comment by johnleider** [comment]
This has been resolved in v1.1
