### ISSUE TITLE
[Bug Report] v-data-table Expand Feature Problems

### ISSUE THREAD

**Issue by big213** [vuetifyjs/vuetify#3812]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
Using the codepen example:

1. Expand "Ice cream Sandwich" row

2. Click Switch Data

3. Click Switch Data again

4. Collapse the "Ice cream Sandwich" row

5. In the console: Uncaught TypeError: Cannot read property 'classList' of undefined

### Expected Behavior
No console error when performing this series of actions.

### Actual Behavior
Console error happens.

### Reproduction Link
[https://codepen.io/anon/pen/yKGgwx?editors=1010](https://codepen.io/anon/pen/yKGgwx?editors=1010)

### Other comments
On a side note, I would expect the expanded rows in the v-data-table to all be collapsed when the data is switched out entirely, which is what I am trying to accomplish. But it looks like the expanded state of a data table row will persist if the key is identical to that of a previously expanded data row.

I attempted to work around this by adding an "expanded" property to each of the items and then adding a v-if="props.item.expanded" to the v-card to collapse the card another way, but it ended up completely crashing the application with the same error as described above.

**Comment by big213** [comment]
Thank you for confirming. If there is an option or requirement to reset the data-table keys when the data is switched, I think this could be a potential fix, and it seems like this would be the expected behavior when switching data.

**Comment by KaelWD** [comment]
Would #2662 fix this?
