### ISSUE TITLE
[Feature Request] DataTable: translation of pagination

### ISSUE THREAD

**Issue by Michkkael** [vuetifyjs/vuetify#3814]
### Problem to solve
See here an [example](https://codepen.io/Michkkael/pen/qoLKrp/).

I can't find any prop to translate the 'of' in pagination.

### Proposed solution
By adding a new prop? (for example: pagination-text="my translation")

**Comment by nekosaur** [comment]
https://vuetifyjs.com/en/components/data-tables#example-page-text
