### ISSUE TITLE
[Bug Report] Filter prop doesn't work at with vanilla v-select

### ISSUE THREAD

**Issue by HaykoKoryun** [vuetifyjs/vuetify#3815]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. observe that the `customFilter` function in `data` is correctly bound in the template to the `:filter` attribute, and that it always returns `false`
2. observe that clicking the dropdown list shows all of the items in the list

### Expected Behavior
with the function always returning false, no items should appear in the list

### Actual Behavior
the function return value isn't evaluated correctly

### Reproduction Link
[https://codepen.io/HaykoKoryun/pen/jzdOaL?&editors=101](https://codepen.io/HaykoKoryun/pen/jzdOaL?&editors=101)

### Other comments
If you add the `autocomplete` attribute to the `v-select` the filter works correctly.

**Comment by johnleider** [comment]
`v-select`'s **filter** prop only works with the **autocomplete** prop. This is no longer an issue in v1.1 as `v-autocomplete` is its own component.
