### ISSUE TITLE
[Bug Report] v-select isn't initialized properly when using item-value="value"

### ISSUE THREAD

**Issue by iamianmiller** [vuetifyjs/vuetify#3825]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Load the page
2. Notice that the select is empty.
3. Change item-value to '_id'
4. Notice that after reloading the page the v-select is now properly initialized.

### Expected Behavior
When loading the page the select should show the value stored in it's model.

### Actual Behavior
When loading the page the select doesn't show the value stored in it's model.

### Reproduction Link
[https://codepen.io/ianmiller/pen/xWBbbe](https://codepen.io/ianmiller/pen/xWBbbe)

**Comment by KaelWD** [comment]
You're using `item-value` incorrectly, it refers to a key on the item object. In your case that would be `item-value="_id"`

**Comment by iamianmiller** [comment]
@KaelWD so it's not possible for the v-select to return the entire object rather than just the value of one key?  That is the behavior I want and I believe it's the intended behavior for the `item-value` default which is `value`.

**Comment by jacekkarczmarczyk** [comment]
use `return-object` prop

**Comment by iamianmiller** [comment]
Thanks @jacekkarczmarczyk, however the possible bug I reported still exists when using the `return-object` prop.  (The select isn't initialized).

**Comment by jacekkarczmarczyk** [comment]
Because it uses the item's value to find the selected item. You're missing `item-value="_id"` in your codepen

**Comment by iamianmiller** [comment]
I see, thank you!
