### ISSUE TITLE
A ask for release 0.15.8

### ISSUE THREAD

**Issue by kimixu717** [vuetifyjs/vuetify#3830]
Hi, this is not a issue, but a ask for release 0.15.8
I am using 0.15.7, but in some reason I need this commit https://github.com/vuetifyjs/vuetify/commit/24d0b895ff70da2940abca57919dea9745176e7c  in 0.15, 
because the 0.16+ is not ok with my project. So could you merge this commit into 0.15.7 and release 0.15.8 ? very thankful.

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
