### ISSUE TITLE
[Bug Report] FAB with "LEFT" or "Right" speed-dial doesn't work on IE

### ISSUE THREAD

**Issue by vinceliao99** [vuetifyjs/vuetify#3831]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. open IE 11
2. go to: https://vuetifyjs.com/en/components/floating-action-buttons#example-speed-dial
3. at the "FAB with speed-dial" section, change Speed dial direction to "left" or "right"

### Expected Behavior
It should expends out like using "top" or "bottom"

### Actual Behavior
Doesn't do anything if use "left" or "right"

### Reproduction Link
[https://codepen.io/pen/?&editors=111](https://codepen.io/pen/?&editors=111)

**Comment by KaelWD** [comment]
> Doesn't do anything

It does do something, just the buttons have no width.

**Comment by bajki** [comment]
Will be that fixed?
Thanks

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
