### ISSUE TITLE
[Bug Report] Headers tab hidden

### ISSUE THREAD

**Issue by JoinBugs** [vuetifyjs/vuetify#3835]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Google Chrome, Chrome 65.0.3325.181, Mozilla Firefox, Microsoft Edge, Internet Explorer, Opera
**OS:** Windows 10

### Steps to reproduce
click on a open dialog button and click and the second tab

### Expected Behavior
open the selected tab and header tabs not got be hidden

### Actual Behavior
tabs headers are hidden

### Reproduction Link
[https://codepen.io/bugger/pen/QmPEwL?editors=1010](https://codepen.io/bugger/pen/QmPEwL?editors=1010)

### Other comments
in the v1.0.13 vuetify all works fine

**Comment by johnleider** [comment]
It actually isn't working on 1.0.13 either. When using `v-tabs` in a dialog, you should apply the **lazy** prop on `v-dialog`. This allows the tabs component (also `v-text-field` with autofocus for example) to not instantiate until it is actually visible.

https://codepen.io/johnjleider/pen/KoOvXz?editors=1010
