### ISSUE TITLE
[Bug Report] Tabs component is broken with vue-router (tabs slides off screen)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#3838]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
1. Create a `v-tabs` component using the `:to` prop to integrate with vue-router
2. Go to a path specified on one of the tabs (open url in browser, not click on the tab)

### Expected Behavior
Active tab to be selected without any animation.

### Actual Behavior
The entire tab component does a slide-x animation to the left on initial page load and each time the tab component is re-created (e.g. after toggling it with `v-if`).

### Reproduction Link
[https://codepen.io/anon/pen/aYxqvb](https://codepen.io/anon/pen/aYxqvb)

### Other comments
In my code pen you can reproduce it when it is initially loading or by clicking the "Toggle tabs" button. Try moving the `:to="{ path: '/' }"` to the last tab to see how this effects the bug. It slides farther off screen and ends up hiding the first two tabs completely.

This bug is quite serious as it makes the tabs component useless with vue-router in the current version.

**Comment by greenya** [comment]
I also confirm this bug.
This bug was added (started to appear) only on 1.0.14. If you switch to 1.0.13 it disappears.

**Comment by krisl21** [comment]
It also occurs without a router. See: https://codesandbox.io/s/oo0k58kvv6

Click on the last item in tab-bar. The whole tab-bar slides offscreen.

**Comment by KaelWD** [comment]
@blalan You could just click the button
![image](https://user-images.githubusercontent.com/16421948/38745146-1527eca8-3f87-11e8-9d10-cffe4c0eab7a.png)

**Comment by mumairofficial** [comment]
Thank you, @greenya switching back to v1.0.13 fixed this issue!

Waiting for new release with this bug fix.

**Comment by logiclabs** [comment]
Awesome! Works like a charm.

**Comment by johnleider** [comment]
@krisl21 If you are still having issues with this, we might need to see a codepen reproduction. Please create a new issue from https://issues.vuetifyjs.com
