### ISSUE TITLE
Sidebar (drawer) should have a backdrop (scrim)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#384]
As per the [specs](https://material.io/guidelines/patterns/navigation-drawer.html), a navigation drawer when open should have everything behind it darkened by a backdrop (scrim), e.g. with an opacity value of `rgba(0, 0, 0, .54)`. This should only apply when it was triggered by a user action (i.e. when the initial state of the drawer is "hidden"). In addition, the drawer should span the height of the screen and not be clipped under the top bar.

I think these changes are important to stay more consistent with the Material Design spec.

**Comment by johnleider** [comment]
As far as the sidebar not being clipped under the toolbar, that's at the discretion of the developer, we have options to do that or not do it. 

The overlay, however, is something that we need to do.
