### ISSUE TITLE
How can i access to theme variables ??

### ISSUE THREAD

**Issue by imadHafsi** [vuetifyjs/vuetify#3844]
How can i do this for example 

.primary-border-bottom
    border-bottom: 2px solid $theme.primary

I need to access to variables if i change accent or secondary ... all color im my custom classes changes.
and Thank you

**Comment by KaelWD** [comment]
You can't, at least not in CSS. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by imadHafsi** [comment]
I mean by using stylus not css
