### ISSUE TITLE
[Bug Report] Error while destroying tabs

### ISSUE THREAD

**Issue by sergeantklin** [vuetifyjs/vuetify#3859]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows

### Steps to reproduce
1. Open chrome dev tools console
2. Click several times to "recreate tabs" button (about 3 times/sec)

### Expected Behavior
Tabs should be recreated without errors

### Actual Behavior
Console displays error
vuetify.min.js:6 Uncaught TypeError: Cannot read property 'clientWidth' of undefined
    at VueComponent.setOverflow (vuetify.min.js:6)
    at VueComponent.callSlider (vuetify.min.js:6)
    at vuetify.min.js:6

### Reproduction Link
[https://codepen.io/anon/pen/oqRdja?editors=1010](https://codepen.io/anon/pen/oqRdja?editors=1010)

### Other comments
clientWidth calculates after the component was destroyed

**Comment by johnleider** [comment]
You marked the issue with `1.0.14` but the codepen is using `1.0.13`. This issue was already resolved with last release.
