### ISSUE TITLE
Consistent paddings and margins

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#386]
As far as I know, the spec specifies all paddings and margins in pixel units (typically 8px, 16px, 24px, etc..). I have noticed that in some areas, Vuetify uses `rem` or `em` units. Is there a particular reason for this or do you plan to change it?

**Comment by johnleider** [comment]
Which areas? And rem is just based off the root pixel, so as long as the size is the same, it's no difference as far as I'm concerned.

**Comment by sindrepm** [comment]
After a closer look I guess it is mainly the spacer helpers that uses rem. I was using the `pa-3` class which produces a padding of 14px instead of 16px. No big issue, though, I could always add my own classes. `.toolbar` adds a 14px padding instead of 16px, though, which I think is wrong.

**Comment by johnleider** [comment]
I will take a look at this and confirm the consistency. Ty for the report.
