### ISSUE TITLE
[Bug Report] Form reset not working properly

### ISSUE THREAD

**Issue by nikitakress** [vuetifyjs/vuetify#3860]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Toggle checkbox
Press submit
Press clear

### Expected Behavior
Submit becomes available.

### Actual Behavior
Submit is greyed out.

### Reproduction Link
[https://codepen.io/anon/pen/GxVQZg?&editors=101](https://codepen.io/anon/pen/GxVQZg?&editors=101)

**Comment by piyush-sukhadiya** [comment]
Looks like may wait for [restructured input controls](https://medium.com/vuetify/rebuilding-input-controls-part-2-a01936b6520e)

**Comment by KaelWD** [comment]
Fixed in v.1.1: https://codepen.io/anon/pen/XYppZN?&editors=101
