### ISSUE TITLE
[Bug Report] v-select doesn't show selected option if "value" is an object and it's specified in v-model

### ISSUE THREAD

**Issue by websanya** [vuetifyjs/vuetify#3862]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Safari 11.1
**OS:** Mac OS 10.13.4

### Steps to reproduce
* Make a v-select with object as a value.
* Specify an object of the same scheme as v-model.

### Expected Behavior
Corresponding option should be selected.

### Actual Behavior
Nothing is selected.

### Reproduction Link
[https://codepen.io/websanya/pen/NYQeYP](https://codepen.io/websanya/pen/NYQeYP)

**Comment by Renato66** [comment]
What are you trying to do is the following:
```js
const obj1 = {hi:'hello'};
const obj2 = {hi:'hello'};
console.log(obj1 === obj2)  //false
```
https://vuetifyjs.com/en/components/selects#example-custom-text-and-value

if you want to compare the object properties pass them as a parameter
````js
  list: [
    {
      id: "1",
      name: "Foo"
    },
    {
       id: "2",
       name: "Bar"
    }
  ]
```
```html
 <v-select
          :items="items"
          v-model="select"
          item-text="name"
          item-value="id"
          return-object
 ></v-select>
```

**Comment by websanya** [comment]
Your example would work only with two properties, right? If I need each option to be a 3-property object — I can't do that because of JS behavior?

**Comment by Renato66** [comment]
you will need only 2 things: value and text

value: id.userCode
text: name.lastName
```js
{
  id: {
    userCode: 1,
    something: 3
   },
   name: {
     firstName: 'foo',
     lastName: 'bar'
   }
}

```

**Comment by websanya** [comment]
I need to be able to select between complex object values by one input field. So I need v-model to actually store this complex value to send it to the api later.

**Comment by KaelWD** [comment]
You need to tell the select what it's supposed to key on with `item-value` and `item-text`. The value must be a primitive as v-select uses a strict equality check (`===`). 

https://codepen.io/anon/pen/odvXVN?editors=1010
