### ISSUE TITLE
404 error at documention

### ISSUE THREAD

**Issue by ehsanskyboy** [vuetifyjs/vuetify#3868]
hi, in this page: https://vuetifyjs.com/en/directives/touch-support when i click on the next button at the end of the page, (Server side rendering) i have got a 404 error.
sorry for sending this here, I've tried to chat with you but i couldn't send message in your chatroom.
404 page : https://vuetifyjs.com/en/guides/ssr
i think it should be changed to : https://vuetifyjs.com/en/guides/server-side-rendering

**Comment by KaelWD** [comment]
Duplicate of vuetifyjs/vuetifyjs.com#316
