### ISSUE TITLE
[Bug Report] [v-text-field] Box background has incorrect background color

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#3869]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
Just add BOX prop to v-text-field.

### Expected Behavior
Background color should be 6% black on light version

### Actual Behavior
Background color is 60% white

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

**Comment by johnleider** [comment]
This has been resolved in v1.1.
