### ISSUE TITLE
Card placed inside a tab loses default styling

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#387]
Not sure if this is a bug or by design, but the following CSS changes the default styling of a card when placed inside a tab component.

```
.tabs .card {
    background: inherit;
    box-shadow: none;
}
```

I don't see any good reason why you would not want a card to look the same whether it is inside a tabbed interface or not.

**Comment by johnleider** [comment]
It is by design. Otherwise the card shadow will bleed out.

**Comment by sindrepm** [comment]
@johnleider maybe I am using the tab component incorrectly, but I simply want to display a grid-like layout with a card in each "cell". I am not doing anything special like placing a card inside a card. The tab is just a content container as far as I am concerned, and I don't want the container to affect how my content is displayed. I am not sure I understand your comment about the shadow bleeding out.

There is already a rule that applies to the first `.card` child of `.tabs__item`, which I kind of understand in case you are using a single card as a content container inside the tab, but the other rule that changes every `.card` inside a tab shouldn't be there in my opinion. If someone wants to remove the shadow they could always add the class `elevation-0` to a particular card. 

If I am still not making sense, let me know and I will see if I can create a code pen to show what I mean.

**Comment by johnleider** [comment]
Ahh, that makes sense. Yea, I'm sure I could clean this up a bit for that use case.

**Comment by sindrepm** [comment]
@johnleider Thanks. I found another similar issue as well. This rule is not wanted:

```
.tabs ul {
    padding: 0;
}
```
I understand this was probably added to lay out the tab items, but this also affects other components placed inside a tab view (e.g. lists). A specific rule targeting only the tab items should be used instead.

I think effort should be made to clean up these unwanted side effects. One component's rules should not unintentionally affect child elements.

What do you think?
