### ISSUE TITLE
[Feature Request]  make “Clear” button foe date picker

### ISSUE THREAD

**Issue by sergeynilov** [vuetifyjs/vuetify#3870]
### Problem to solve
Hello,
Using date-picker component (picker in menu style) from vuetify ( https://vuetifyjs.com/en/components/date-pickers )
I did not find if there is a way to make “Clear” button for it? 
I mean if the date is not required I need possibility to clear the value...
 
 
Thanks !

### Proposed solution
To add  option make “Clear” button.

**Comment by jacekkarczmarczyk** [comment]
Use `clearable` prop on `v-text-field`
