### ISSUE TITLE
[Bug Report] Bug with <v-layout row> is shifted left because of max-width

### ISSUE THREAD

**Issue by mav-im** [vuetifyjs/vuetify#3873]
### Versions and Environment
**Vuetify:** 1.0.15
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
1. just follow link
2. take a look at the row

### Expected Behavior
Rows should be centered within a card

### Actual Behavior
Rows are shifted left

### Reproduction Link
[https://jsfiddle.net/tgpfhn8m/301/](https://jsfiddle.net/tgpfhn8m/301/)

### Other comments
This example is taken from official documentation. You can find the same behavior in docs, see first grid example https://vuetifyjs.com/en/layout/grid, rows are shifted left too.

<v-layout> has "max-width: 100%" css style in v1.0.15, so .layout.row should have "max-width: none;" styling to not shift left because of the layout negative margin in this example.

**Comment by mav-im** [comment]
Also, good example to see this bug is nested grids from docs, see https://vuetifyjs.com/en/layout/grid#example-nested-grid

**Comment by throrin19** [comment]
Same problem Here, All my interface has this bug :

![image](https://user-images.githubusercontent.com/1394778/38930265-99a6d97c-430f-11e8-84f7-73d5a7de22fa.png)

If I remove the `max-width : 100%`, it works fine. 

The width at 100% and a margin does not works properly.

**Comment by anikolaev** [comment]
It now breaks my layout. I have a toolbar with left icon, tabs (`width: 100%`) and user avatar component (name and logo). User avatar is wrapped with `v-layout`. As a result user avatar is cropped. When I remove / override `min-width: 0` style from v-layout it returns to correct position. 

Demo: https://codepen.io/Dron007/pen/xjeGma

**Comment by johnleider** [comment]
@anikolaev , please do not comment on old closed issues. If you are having a problem, please create a new ticket at https://issues.vuetifyjs.com .

Thank you!
