### ISSUE TITLE
[Bug Report] v-breadcrumbs divider render

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#3874]
### Versions and Environment
**Vuetify:** 1.0.15
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
on [https://codepen.io/Buzzzzer/pen/xjxZar](https://codepen.io/Buzzzzer/pen/xjxZar)
click delete btn some times and add btn some times 

### Expected Behavior
-

### Actual Behavior
divider render several times

### Reproduction Link
[https://codepen.io/Buzzzzer/pen/xjxZar](https://codepen.io/Buzzzzer/pen/xjxZar)

**Comment by buzzzzer** [comment]
On v1.1.0-alfa.1 bug is back.

**Comment by KaelWD** [comment]
Merge conflict was resolved incorrectly in 0674f90305a64d85b84767d1a0f062759c2ef209
