### ISSUE TITLE
[Feature Request] menu component close-on-resize

### ISSUE THREAD

**Issue by WuerfelDev** [vuetifyjs/vuetify#3876]
### Problem to solve
I think menus shouldn't stay open on resize by default. With this new property the dev has the ability to choose

### Proposed solution
We should add the property close-on-resize to the menu component.
Therefore adding a resize listener if true

**Comment by samuelcolburn** [comment]
Is there any reason why you feel this should be default behavior? It seems like a personal preference to me, and it is fairly easy to implement within the framework already:

[https://codepen.io/smcolburn/pen/YOxNKJ?&editors=101](https://codepen.io/smcolburn/pen/YOxNKJ?&editors=101)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
