### ISSUE TITLE
[Bug Report] v-select color prop doesn't seem to work

### ISSUE THREAD

**Issue by kwindo** [vuetifyjs/vuetify#3877]
### Versions and Environment
**Vuetify:** 1.0.15
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Mac OS 10.13.4

### Steps to reproduce
Add "color" prop to v-select

### Expected Behavior
Change background color

### Actual Behavior
No Change

### Reproduction Link
[https://codepen.io/kimsanka/pen/PeoXPQ?editors=1010](https://codepen.io/kimsanka/pen/PeoXPQ?editors=1010)

**Comment by johnleider** [comment]
Color accepts a string color from the material design spec: https://vuetifyjs.com/en/style/colors

**Comment by kwindo** [comment]
Ah sorry for this. Also I was hoping it would change the background color of the menu items. Maybe a suggestion for an update but I guess that needs another kind of ticket. Thanks for your time anyway.
