### ISSUE TITLE
[Bug Report] Bug: Select does not render selected value if already present.

### ISSUE THREAD

**Issue by johncade** [vuetifyjs/vuetify#3881]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1) Create a select
2) Initialize page with value in selects v-model

### Expected Behavior
The item should show up

### Actual Behavior
No Item

### Reproduction Link
[https://codepen.io/anon/pen/ELaExR?editors=1010](https://codepen.io/anon/pen/ELaExR?editors=1010)

### Other comments
If I am doing this incorrectly, the documentation is incredibly vague. I would suggest an update.

**Comment by nekosaur** [comment]
You need to tell the `v-select` what property on the provided objects to use for checking equality. This is done with the `item-value` prop. In your case it would be `item-value="name"`.

If you feel like the documentation could be improved in this area, please open an issue in the documentation repository.
