### ISSUE TITLE
[Feature Request] Type Time in Timepicker

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#3883]
### Problem to solve
If the linked textarea is readonly (usually it is). There's isn't a quick way to set/update/change the time by typing it in. 

### Proposed solution
Allow hours and minutes to be able to be typed in the title section.

**Comment by jacekkarczmarczyk** [comment]
If you want be able to type in the time just don't add `readonly` to the textfield

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. This will be a part of rewriting time picker to match the new Material Design spec.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
