### ISSUE TITLE
[Feature Request] Printing raw data in text fields

### ISSUE THREAD

**Issue by danielsvane** [vuetifyjs/vuetify#3890]
### Problem to solve
Having external data with unescaped HTML, and needing to display and edit it in text fields.

### Proposed solution
A "raw" attribute on the input field, or something similar.

**Comment by nekosaur** [comment]
https://codepen.io/anon/pen/MGwojv ?

**Comment by danielsvane** [comment]
Sorry, I didn't give a very good explanation of my issue. I have a .json file with unescaped newlines and such, that needs to be shown in an input field. I modified your pen with a "\n", and you can maybe see the issue. This might not even be a Vuetify problem, as much as my lack of understanding of Vue.

https://codepen.io/danielsvane/pen/PeZooV

**Comment by KaelWD** [comment]
`multi-line` or `textarea`
