### ISSUE TITLE
[Bug Report] a-la-carte importing complex components in *.vue files

### ISSUE THREAD

**Issue by Nejik** [vuetifyjs/vuetify#3891]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. install vue project with vue-cli (3+)
2. vue add vuetify
3. Import any complex(with child components, such as VList) component with a-la-carte method

(transform-imports) installed and working fine with simple elements such vBtn.

### Expected Behavior
imported all subcomponents as with `import * as VList from 'vuetify/es5/components/VList'`

### Actual Behavior
not working app because child components not imported

### Reproduction Link
[https://github.com/Nejik/vuetifySandboxJs](https://github.com/Nejik/vuetifySandboxJs)

### Other comments
When importing such complex components as vList with child sub-components (vListTile, vListTileAction) with a-la-carte method only parent component vList is imported. 

Problem only in *.vue files, if we make such import in main.js - all working fine.

Destructuring NOT working:
components: {
...VList
}
Importing child components NOT working:
import {vListTile} from 'vuetify';

But this thing IS working:
import * as VList from 'vuetify/es5/components/VList'
components: {
...VList
}

So question is how to import full vList component with es2015 syntax?

**Comment by nekosaur** [comment]
This is already explained in [docs](https://vuetifyjs.com/en/guides/a-la-carte)

`You can also import components in .vue files, as seen below. When doing so it’s important that you import all named exports, and then destructure them in components. Otherwise child components such as v-card-text or v-expansion-panel-content will not be available.`

**Comment by nekosaur** [comment]
This is how it's currently working. If you look at the source code you will understand why.
