### ISSUE TITLE
[Feature Request] DataTable item-key to use index

### ISSUE THREAD

**Issue by lmcadory** [vuetifyjs/vuetify#3897]
### Problem to solve
There are cases where data is handled from 3rd party sources and there may not be unique field values. This will cause rows with functionality (i.e expand) to be treated as one

See codepen
https://codepen.io/anon/pen/ELjRaK

### Proposed solution
In the iterable mixin allow the option to supply a field from the items array or default to the index.

**Comment by nekosaur** [comment]
This can easily be handled by the user

https://codepen.io/anon/pen/NMqOeW?editors=1010
