### ISSUE TITLE
Cant add events on v-btn

### ISSUE THREAD

**Issue by pablohpsilva** [vuetifyjs/vuetify#39]
```
<v-btn ripple
      outline
      round
      info
      class="light-blue"
      @click.stop="buscar()">
      <v-icon>search</v-icon>
      <span>Buscar</span>
    </v-btn
```

the `buscar()` is a method and its working. I tested it on another element but, for some reason, its not binded on any of the vutify elements.

**Comment by johnleider** [comment]
Duplicate https://github.com/vuetifyjs/vuetify/issues/35.

**Comment by pablohpsilva** [comment]
Thank you @johnleider
