### ISSUE TITLE
 expected "indent", got "import"

### ISSUE THREAD

**Issue by thiner** [vuetifyjs/vuetify#390]
### Steps to reproduce
Follow the guide, add main.styl file, and then compile.

### Versions

```
    "vue": "^2.2.2",
    "vue-router": "^2.3.0"
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "webpack": "^2.2.1",
```
### What is expected ?

The .styl file should be imported correctly.

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
