### ISSUE TITLE
Document in API explorer the 'change' event supported by the selection controls like v-check-box

### ISSUE THREAD

**Issue by anachirino** [vuetifyjs/vuetify#3900]
### Problem to solve
Many times user apps need to react to input control changes.  Without input or change event on the controls like v-checkbox, it makes this hard to do.

### Proposed solution
Add some type of input/change event to all input controls. Similar to the event on v-text-field

**Comment by KaelWD** [comment]
Issues with the documentation should be reported on https://github.com/vuetifyjs/vuetifyjs.com/issues
