### ISSUE TITLE
[Bug Report] v-menu element within fixed toolbar scrolls with page when opened

### ISSUE THREAD

**Issue by v1996-96** [vuetifyjs/vuetify#3903]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Click on the search form and scroll the page.

### Expected Behavior
Menu scrolls with the toolbar.

### Actual Behavior
Menu block scrolls with the page.

### Reproduction Link
[https://codepen.io/v1996-96/pen/WJQyva](https://codepen.io/v1996-96/pen/WJQyva)

**Comment by jacekkarczmarczyk** [comment]
Use `attach` prop 
https://codepen.io/anon/pen/xjwzmr
