### ISSUE TITLE
[Bug Report] Vertical dynamic stepper

### ISSUE THREAD

**Issue by jamesblasco** [vuetifyjs/vuetify#3904]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.0.8
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Change number steps from 1 to 6

### Expected Behavior
The stepper should load 6 steps with a vertical divider on the left between them

### Actual Behavior
The stepper loads the 6 steps but not the vertical dividers on the left between them. When you open another step all the vertical dividers appears

### Reproduction Link
[https://codepen.io/jamesblasco/pen/wjKXQO](https://codepen.io/jamesblasco/pen/wjKXQO)

**Comment by KaelWD** [comment]
It only evaluates steps on mount: https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VStepper/VStepper.js#L73

This needs to be changed to provide/inject like tabs.

**Comment by jamesblasco** [comment]
It would be nice to have a wrapper component to put inside vue-stepper-content and vue-stepper-step in vertical mode. Better for using v-for rather than template

**Comment by KaelWD** [comment]
Can you give an example of what the markup would look like for that?

**Comment by jamesblasco** [comment]
<v-stepper v-model="e1" vertical>
        <v-stepper-item v-for="n in steps">
            <v-stepper-step
              :key="`${n}-step`"
              :step="n"
              :complete="e1 > n"
              editable
            >
              Step {{ n }}
            </v-stepper-step>
           <v-stepper-content
            :step="n"
            :key="`${n}-content`"
          >
          </v-stepper-content>
      </v-stepper-item>
</v-stepper>

**Comment by KaelWD** [comment]
I don't understand how that's any different? It'd just be adding extra runtime overhead.

**Comment by jamesblasco** [comment]
Yes but it allows to wrap v-stepper-step  and v-stepper-content inside a single component and use it in a custom component. In simple steppers doesn't affect it but when I am need computed properties for each item in the array of steps putting each of them in a custom component makes things easier and simpler

**Comment by dima74** [comment]
If `isVertical` prop for `VStepperContent` will be provided by `VStepper` (instead of setting it in [`getSteps`](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VStepper/VStepper.js#L82)) then looks like that this issue will be resolved. But it is not clear what to do with tests, because `isVertical` is changed dynamically in [one of them](https://github.com/vuetifyjs/vuetify/blob/dev/test/unit/components/VStepper/VStepperContent.spec.js#L70) and provide/inject is not reactive (so it is not possible to change them with avoriaz)
