### ISSUE TITLE
[Feature Request] Requesting a new prop to control overlap of v-select list options

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#3906]
### Problem to solve
By default, a `v-select` component's options are rendered above (over) the `v-select` control - the list of options overlap the control's value when popped up.

In some instances, e.g. when setting the `solo` or `autocomplete` props, the list of options are rendered below the `v-select` control. This enables the user to see the current value of the `v-select` control while the list of options is being displayed. 

It would be nice to have a prop that could control the positioning of the list of options relative to the control, in order to change the default behaviour when desired. Eg. a "bottom" prop could be added to `v-select`, to indicate that the list of options should be rendered below the `v-select` control.

It's currently not trivial to change the positioning behaviour via CSS, since the absolutely positioned list of options is positioned relative to the `v-select` component and the `top` value is calculated. 

### Proposed solution
The addition of a new prop to control option list overlap behaviour. Having a prop to control the overlap would provide an easy and predictable solution.

**Comment by KaelWD** [comment]
The menu is supposed to have the selected item scrolled into view. `autocomplete` is an exception to this because it needs to have a text field visible. 

https://material.io/guidelines/components/menus.html#behavior-figure-caption-0

If you can provide an example of this *not* happening then I'd say to change this to a bug report.

**Comment by wernerm** [comment]
@KaelWD You are correct, the MD specs clearly state that the selected option should overlap the current value. At the moment I'm setting the `solo` prop and then removing the solo-styling as a workaround - that made me think that a prop would be helpful.
