### ISSUE TITLE
[Bug Report] Bug: Select does not work with a list of objects

### ISSUE THREAD

**Issue by johncade** [vuetifyjs/vuetify#3908]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1) Create a select
2) Initialize page with value in selects v-model
3) I was told to use the `item-value` property so that if the page was loaded with a preset value, vuetify would know "what property on the provided objects to use for checking equality". This seems to be only partially correct. The way I interpreted `item-value` is that this sets the property on an object that you want to store as a value. So if you have a list of objects that have the following structure and you only wanted to store the `Name` property, then you would set `item-value="Name"` and `item-text="Name"`.:
```javascript
{ Name: "foo", id: 12345}
```
 It appears that this assumption is correct, but it is the only way to render a pre-selected value. Once the value is changed, the reference breaks because you are only storing the value for the property, in this case a string.

### Expected Behavior
Supports selection of an object in a list, supports rendering value's designated property if previously selected.

### Actual Behavior
Using `item-value` allows a preselected value to render, but once changed, breaks the data model.

### Reproduction Link
[https://codepen.io/anon/pen/ELaExR?editors=1010](https://codepen.io/anon/pen/ELaExR?editors=1010)

### Other comments
This was initially brought up in: 
https://github.com/vuetifyjs/vuetify/issues/3881#issuecomment-382786904

**Comment by johncade** [comment]
@nekosaur do you by chance have any solution to this problem? I appreciate the promptness of your previous response.

**Comment by nekosaur** [comment]
Add `return-object` prop to return the full object

**Comment by caliny97** [comment]
@nekosaur, this is happening when the items array is set asynchronously.

**Comment by jacekkarczmarczyk** [comment]
> this is happening when the items array is set asynchronously.

Then please prepare the proper reproduction, the codepen you've provided doesn't use asynchronous loading so it's impossible to reproduce your problem

**Comment by KaelWD** [comment]
@johncade As nekosaur said, use `return-object` to get the full object: https://codepen.io/anon/pen/JvEJvo?editors=1010

@caliny97 Please create a new issue if there is an actual problem with the component, this one is entirely user error.
