### ISSUE TITLE
[Feature Request] Expansion panel like the one in Google AdWords

### ISSUE THREAD

**Issue by coronoahcoro** [vuetifyjs/vuetify#3909]
### Problem to solve
The expansion panel in Google AdWords has a nice feature where it shows the selected option or input value in a read-only mode on the collapsed panel. And allows the value to be edited when the panel is expanded. This is quite good when there are a lot of settings need to be configured in a page because you can open only those configuration that you want and eyeball other configuration. 

### Proposed solution
Support the behavior that is shown in the attached gif.

![adwords](https://user-images.githubusercontent.com/1213597/39141178-fae16cdc-46f4-11e8-8f1a-c4d142339cf9.gif)

**Comment by nekosaur** [comment]
This will be possible to implement by users in 1.1

**Comment by coronoahcoro** [comment]
@nekosaur Is this supported in 1.1? I am looking through the documentation for 1.1 and don't see a feature that supports the behavior I explained in the original post.

**Comment by nekosaur** [comment]
Something like this https://codepen.io/anon/pen/djzrxd
