### ISSUE TITLE
Use breakpoints from the spec

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#391]
> For optimal user experience, material design user interfaces should adapt layouts for the following breakpoint widths: 480, 600, 840, 960, 1280, 1440, and 1600dp.

https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints

Maybe the breakpoints in Vuetify should follow these?

https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/settings/_variables.styl#L37

**Comment by capttrousers** [comment]
Sorry if I don't understand GH well, but is this released yet? I see it says merged but that looks like only to the dev branch. 

The current breakpoint values have a huge gap between 600 and 1024, so having a few bp's in there as well as the <600 bp at 480 would be really nice to make more responsive layouts.

**Comment by johnleider** [comment]
The breakpoints have been released and as within spec.

**Comment by capttrousers** [comment]
Hi John, thanks for the response. 

The spec linked above lists the following breakpoints along with the number of grid columns and gutters between them. 

It seems the vuetify breakpoints at 600, 1024, 1440, and 1920 are missing a number of useful breakpoints, especially in the range from 360 - 600, and 600 - 1024. Am I missing something?


Breakpoint (dp) | Columns | Gutter
-- | -- | --
0 | 4 | 16
360 | 4 | 16
400 | 4 | 16
480 | 4 | 16
600 | 8 | 16/24*
720 | 8 | 16/24*
840 | 12 | 16/24*
960 | 12 | 24
1024** |  12 | 24
1280** |  12 | 24
1440** |  12 | 24
1600** |  12 | 24
1920** |  12 | 24

**Comment by johnleider** [comment]
You are correct, we do not have the incremental breakpoints and it's something that we will not add. We strictly support the window break points as to cover all would be unnecessary bloating of the framework.

**Comment by Huixiong91** [comment]
Vuetify breakpoints at 600, 1024, 1440, and 1920 for the respective devices xs, sm, md, lg, xl

This seems to differ slightly from the material design breakpoints of 600, 960, 1280, 1920. 
That is for the max-width, 960 vs 1024 for sm & 1024 vs 1280 for md.

May I know the reason for the slight deviation and if in the future will this be aligned?

**Comment by johnleider** [comment]
Because more than 5 breakpoints is excessive and doesn't offer a real benefit for the increased size.  If you truly want this, you can easily expand on the grid hash and simply add them for you specific implementation.

**Comment by Huixiong91** [comment]
@johnleider
I was not referring to adding more breakpoints, but rather on the metrics of the breakpoints defined being inconsistent with Material Design Guideline.

Vuetify VS Material Design
xm: Both the same at <600px
**sm : 600px > < 1024px VS 600px > < 960px 
md: 1024px > < 1440px VS 960px > < 1280px
lg: 1440px > < 1920px VS 1280px > < 1920px**
xl: Both at > 1920px
