### ISSUE TITLE
[Feature Request] How to Add SEO Support

### ISSUE THREAD

**Issue by kamleshkatpara** [vuetifyjs/vuetify#3916]
### Problem to solve
How to Add SEO Support

### Proposed solution
Tried Vue-Meta but does not work

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
