### ISSUE TITLE
[Feature Request] Support "vw" and "vh" for navigation-drawer

### ISSUE THREAD

**Issue by Tyki** [vuetifyjs/vuetify#3919]
# Problem to solve
The "length" parameter (https://vuetifyjs.com/en/components/navigation-drawers) does not support "vw" and "vh".

# Proposed solution
Being able to support % and vw/vh to give alternatives to pixels parameters

Allow the parameter to be used as a string. 

Exemple : 
```
<v-navigation-drawer
    fixed
    clipped
    v-model="drawer"
    right
    app
    :disable-resize-watcher="true"
    width="20vw"
  >
  </v-navigation-drawer>
```

Assuming that we have "vw", "vh" or "%", use them directly as string into style balise instead of number parameter for width in pixels

**Comment by jpodwys** [comment]
The ability to use `100vw` in a `:width` binding does not appear to work in `^1.3.0`. Was support for this ever added? Thank you for your time!

@Tyki @johnleider @nekosaur @blalan

**Comment by MajesticPotatoe** [comment]
@jpodwys you wont see this is 1.x, It is available in 2.x <https://codepen.io/MajesticPotatoe/pen/ExYEyYL>

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by jpodwys** [comment]
I apologize for the traffic on the old issue. I'll remember this in the future. Thanks!
