### ISSUE TITLE
How to use tabs with Vue Router?

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#392]
I'm trying to use the Tabs component together with the Vue router, but I can't get it to work. Here is a fiddle of what I'm doing: http://jsfiddle.net/h4kpvk4v/2/

`v-tab-content` doesn't get 'active' and it throws this error: `Uncaught TypeError: this.href.replace is not a function`

Is this a bug or am I doing something wrong?

**Comment by mathieucivel** [comment]
Maybe this can help : http://jsfiddle.net/h4kpvk4v/

**Comment by maartendraijer** [comment]
@mathieucivel I have used that Fiddle as base for my own Fiddle. :-) Also it does not highlight the second tab (GO TO BAR) when you click it:

![screen shot 2017-04-18 at 17 26 06](https://cloud.githubusercontent.com/assets/808271/25138961/3762d130-245c-11e7-9951-c5a603c56cd5.png)

**Comment by johnleider** [comment]
That is something we are going to add in soon. It's currently not tracking the route change and doesn't actually move the slider.

**Comment by maartendraijer** [comment]
@johnleider Thanks for the new release! 🎉 

Though, I still can't get tabs to work in combination with the router. Check out this Fiddle: http://jsfiddle.net/h4kpvk4v/4/.

Am I still doing something wrong?

**Comment by johnleider** [comment]
I'm not home right now but it worked fine on my mobile.

**Comment by maartendraijer** [comment]
@johnleider That's strange. This is what I'm seeing when I load the page:

<img width="479" alt="screen shot 2017-04-22 at 20 19 45" src="https://cloud.githubusercontent.com/assets/808271/25306980/1fe9cbae-2799-11e7-98df-7c2e101292c9.png">

Here it _should_ highlight 'GO TO BAR' and show the 'bar' content. But it does not, unfortunately.

**Comment by johnleider** [comment]
Oh, I thought you were just having issues changing routes. It's on page load.

**Comment by maartendraijer** [comment]
@johnleider Also on changing routes it doesn't show the `<v-tab-content>` component. It keeps having a `display: none;` on it.

**Comment by johnleider** [comment]
If you're using the tabs as router you can't use tab content

**Comment by maartendraijer** [comment]
@johnleider Ah, yeah, alright. Then the only issue is that it doesn't highlight the proper tab on a page load/refresh.

**Comment by chrisgillis** [comment]
Still doesnt highlight the proper tab on a page load / refresh.

**Comment by johnleider** [comment]
Please don't comment on old tickets, if it is happening in a new version, you are best to create a new issue please. Thank you.
