### ISSUE TITLE
[Bug Report] Dialog transitions can't be disabled

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#3924]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 10

### Steps to reproduce
Create a dialog with transition false , destroy it, observe that content continues to be displayed after the component is destroyed.

### Expected Behavior
Dialog show/hide immediately

### Actual Behavior
The dialog remains visible for a few hundred millsecs after being destroyed.

### Reproduction Link
[https://codepen.io/anon/pen/ZyVBgB?editors=1010](https://codepen.io/anon/pen/ZyVBgB?editors=1010)

**Comment by KaelWD** [comment]
Regression of #960, which[ wasn't actually fixed. ](https://codepen.io/anon/pen/zjBqre?editors=1010)

**Comment by aldarund** [comment]
The PR fixes dialog transition disable. But overlay still have transition, and it look and act pretty awkward as for me with that pr. Is it desired behavior that  while dialog appears immediately overlay still fade in and fadeout slowly ?

**Comment by johnleider** [comment]
This was fixed in #4041

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
