### ISSUE TITLE
[Bug Report] Wrong cursor when hover a v-chip inside a v-card with href

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3925]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 10

### Steps to reproduce
- Mouse over the v-card
- Mouse over the v-chip

### Expected Behavior
Pointer cursor when hovering the v-chip

### Actual Behavior
Default cursor

### Reproduction Link
[https://codepen.io/anon/pen/LmNqKb?editors=1010](https://codepen.io/anon/pen/LmNqKb?editors=1010)

**Comment by johnleider** [comment]
This is an interesting cross-over as the input says pointer but the chip is designated as default for spec.

**Comment by johnleider** [comment]
This has been resolved for v2.0 and is currently fixed as of beta.11
