### ISSUE TITLE
[Bug Report] Navigation drawer bottom indent on mobile device

### ISSUE THREAD

**Issue by martin-kral** [vuetifyjs/vuetify#3928]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 10

### Steps to reproduce
The Bottom navigation (v-bottom-nav) with "app" prop breaks navigation drawer (v-navigation-drawer) bottom indent on mobile device - the navigation drawer then has bottom indent 56px (set by "max-height: calc(100% - 56px);" inline style). For detail see codepen.

### Expected Behavior
Navigation drawer height should be full screen height (100%) as defined in material design spec: 
 
![components-bottomnavigation-spec-elevation3-](https://user-images.githubusercontent.com/6748506/39243122-bd42bb76-488c-11e8-97ad-669e0a52a94c.png)

### Actual Behavior
Navigation drawer is indented at the bottom by the height of the bottom navigation (56px):

![broken_drawer_bottom_indent](https://user-images.githubusercontent.com/6748506/39243097-ac11772a-488c-11e8-99bb-cc602c07d229.png)

### Reproduction Link
[https://codepen.io/pyxis/pen/qpPjQV](https://codepen.io/pyxis/pen/qpPjQV)

**Comment by KaelWD** [comment]
@germsb Nothing we can do about that one, it's because chrome resizes the viewport when the address bar is shown.

**Comment by idealley** [comment]
This happens as well in the  desktop browser with mobile "size windows" 

It happens when a footer is used. the class `max-height: calc(100% - 56px)` is applied. This can not be over written without js has it is applied after the css of the component is applied. 

In an earlier version of the framework it was working fine.
