### ISSUE TITLE
[Bug Report] Vuetify adds overflow-y-hidden when prerendered using prerender-spa-plugin

### ISSUE THREAD

**Issue by lol2x** [vuetifyjs/vuetify#3929]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117, Google Chrome, Mozilla Firefox, Safari, Opera, Other, Microsoft Edge, Internet Explorer
**OS:** Windows 10

### Steps to reproduce
clone repo
npm install
npm run build
check dist/index.html

### Expected Behavior
html shouldn't have class="overflow-y-hidden"

### Actual Behavior
During prerendering overflow-y-hidden is added to html which turns off scrolling.

### Reproduction Link
[https://github.com/lol2x/vuetify-prerender-spa-plugin](https://github.com/lol2x/vuetify-prerender-spa-plugin)

**Comment by KaelWD** [comment]
https://github.com/lol2x/vuetify-prerender-spa-plugin/blob/master/src/App.vue#L45

prerender-spa-plugin is not supported by vuetify, use something with vue-server-renderer instead (vuepress?).
