### ISSUE TITLE
[Feature Request] DatePicker - Add support for disabling certain days of the week

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3931]
I have no idea what's going on, but issues.vuetifyjs.com won't let me create new issues via the template.  When I click "create" it just takes me to the github home page.  I'm going to copy in what I have from the preview dialog here:

Problem to solve

Date pickers currently don't allow limiting which days are selectable.
Proposed solution

Add a new option to intake a collection of disabled days. Perhaps an array of integers 0-6 representing Sunday-Saturday? Or whatever their specified 0 index day is.

**Comment by gabaum10** [comment]
I was able to accomplish it using moment and the `allowedDates` callback like this:

```
     allowedDates (value) {
        let enabled = false
        _.each(this.days, (day) => {
          enabled = moment(value).day() === parseInt(day)
          return enabled !== true
        })
        return enabled
      }
```

Does it make sense to add this example to the docs or create a simplified way to do this via an option?  Seems like something people would want to do.

**Comment by KaelWD** [comment]
There is already an example demonstrating that functionality: https://vuetifyjs.com/en/components/date-pickers#example-date-allowed-dates

It is also very simple to exclude a specific day of the week with some basic JS knowledge: https://codepen.io/anon/pen/NMRdqz?editors=1010

**Comment by gabaum10** [comment]
Right, I found those after I had posted this, as mentioned above.  It wasn't immediately clear that was how to do it.  Anyway, if that's the accepted response, so be it.
