### ISSUE TITLE
[Feature Request] Hope to add a CHANGELOG.md

### ISSUE THREAD

**Issue by wangyi7099** [vuetifyjs/vuetify#3933]
### Problem to solve
Hope to add a CHANGELOG.md for this reop like Vue or React.   And can be generated by [Angular's commit convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular)

### Proposed solution
Able to see the detailed changes of each version.

**Comment by KaelWD** [comment]
We use [github releases](https://github.com/vuetifyjs/vuetify/releases) to log changes.
