### ISSUE TITLE
[Bug Report] V-Tabs: Alignment & Width Inconsistencies

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#3934]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1.) Open CodePen.

### Expected Behavior
1.) `fixed-tabs` should control width bounds on tabs, while `right`, `centered` or default would affect only the alignment of the tabs.
2.) Width of individual tabs should be auto-width (w/ static padding, as it currently is), scaling to the content of each tab.

### Actual Behavior
`centered` applies the current `fixed-tabs` effect. 

### Reproduction Link
[https://codepen.io/cdwyer/pen/OZRPXY](https://codepen.io/cdwyer/pen/OZRPXY)

### Other comments
CodePen uses `unset` for the "expected" examples, which won't work in IE11. Probably just need to remove the `.tabs__container--centered .tabs__div { min-width }` rule in CSS.

**Comment by KaelWD** [comment]
Other considerations:

 - [keep the `sm` breakpoint for padding changes, but increase the min-width change to `md` or `lg](https://material.io/guidelines/components/tabs.html#specs-figure-caption-10)
- [`fixed-tabs` should make all items the same width](https://material.io/guidelines/components/tabs.html#types-of-tabs-figure-caption-3)

![image](https://user-images.githubusercontent.com/16421948/39308742-90d69724-49a9-11e8-93b0-39e25536050e.png)

**Comment by dwyer14** [comment]
One other small, really insignificant thing, haha...for consistency's sake, I wouldn't mind seeing `centered` changing to `center`, to match the format (grammar? idk) of `right`. Obviously not as much of an issue, but wanted to mention it here. Thanks!
