### ISSUE TITLE
[Bug Report] Wrong padding when use custom padding on v-btn

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3936]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 10

### Steps to reproduce
```html
<v-btn class="pa-4">Button</v-btn>
```

### Expected Behavior
Padding should be applied on .btn__content

### Actual Behavior
Padding is on .btn

### Reproduction Link
[https://codepen.io/anon/pen/vjXQVW?editors=1010](https://codepen.io/anon/pen/vjXQVW?editors=1010)

**Comment by peluprvi** [comment]
`v-btn` has fixed height, so it doesn't grow by applying top or bottom padding.
Suggested solutions:
- apply `min-height` instead of `height` on its css
- and/or create a `height` prop to buttons

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
