### ISSUE TITLE
[Bug Report] Toolbar extension-height does not allow "auto"

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#3938]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
Create a `v-toolbar` with an extension slot and set the `extension-height` prop to "auto". 

### Expected Behavior
Extension slot should grow with its content and not have an explicit height. Also, no errors/warnings should be thrown.

### Actual Behavior
The following warning is logged in the console:
`[Vue warn]: Invalid prop: custom validator check failed for prop 'extensionHeight'.`
The functionality actually works as the slot is rendered without the "height" CSS prop.

### Reproduction Link
[https://codepen.io/anon/pen/BxLbyw](https://codepen.io/anon/pen/BxLbyw)

### Other comments
The validation logic needs to allow the string "auto" in addition to numbers:
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VToolbar/VToolbar.js#L57

The same probably applies to the `height` prop as well.

**Comment by sindrepm** [comment]
@KaelWD It works in the sense that because the validation fails it does not add the `height` prop at all to the inline style which produce the desired outcome (height: auto is default). Not sure why you are referring to v-content. I don't want the extension to fill the entire page. I just want it to grow to fit any content you place within the extension slot. I made a small change to the codepen to illustrate my point.

Since the extensionHeight prop accepts both string and int I assumed it would allow any valid HTML unit, including "auto". Supporting percentages is probably not that useful, though, so I would argue just adding a special case to support "auto", which in effect just removes the inline style tag, is sufficient.

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/XqNXoa?editors=1010

This would be implemented similar to v-footer:
https://github.com/vuetifyjs/vuetify/blob/78c8c7b79d83540889b0c40d9b1086e9a96f3a8a/src/components/VFooter/VFooter.js#L71-L78

**Comment by sindrepm** [comment]
@KaelWD I see what you mean now. I don't use the `app` prop on the toolbar in this case so it does not use fixed positioning or affect the page layout calculations.

https://codepen.io/anon/pen/BxLbyw

**Comment by BennyAlex** [comment]
please allow auto heigth

**Comment by johnleider** [comment]
Unlike `v-footer`, `v-toolbar` actually needs these dimensions to calculate other things. In the sake of making things uniform however, I'm going to add it with the caveat that the scrolling functionality in the new `v-app-bar` will not support non-number values.
