### ISSUE TITLE
[Feature Request] Add max-height and max-width props to VCard

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3939]
### Problem to solve
- Help make responsive cards with a max height or width
- Avoid inline style or custom css
- Align with current height and width props
- Help future usage of ratio size of the card

### Proposed solution
Create a `max-height` and a `max-width` prop for cards.

**Comment by johnleider** [comment]
This was added in https://github.com/vuetifyjs/vuetify/commit/b6c34b70a33f234946bb12d44a6e18077e37f7b4 and is in v1.2
