### ISSUE TITLE
Action buttons increase height in card headers

### ISSUE THREAD

**Issue by jakobrosenberg** [vuetifyjs/vuetify#394]
http://codepen.io/jakobrosenberg/pen/MmKaLE

I'm not sure if this is by design or a bug.

**Comment by johnleider** [comment]
This is due to the margin around buttons. A fix for now would be to add the class ```ma-0``` to the button.

**Comment by jakobrosenberg** [comment]
``ma-0`` sets bar height to 68px (36px + 2 * 16px)

In itself it's not much of an issue. But if you have contextual actions, the small increase would change height of the card. In a gallery of cards, that could break the flow.

On topic, Angular Material has an md-toolbar-tools class which sets height to 64px.

https://material.angularjs.org/latest/demo/card
