### ISSUE TITLE
[Feature Request] Ability to theme the Stepper header independently of the Stepper content

### ISSUE THREAD

**Issue by shinynet** [vuetifyjs/vuetify#3942]
### Problem to solve
If I want to apply a color theme to the stepper header, I can do so by assigning it a color class.
If that's a darker color, then I would also need to assign it the 'dark' theme so text turns white. The problem is, the only component in the stepper component chain that accepts light/dark is the root <v-stepper> component. And if I assign dark to that root, it cascades throughout the entire component, including my stepper content (my stepper content background turns black). The only way I could figure out to get the correct results was to override the .stepper__label css attributes with !important overrides

### Proposed solution
In addition to <v-stepper-header> should be able to be themed independently.

**Comment by johnleider** [comment]
This is being moved to v2.0 to coincide with other stepper updates.

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
Closing this issue. Additional information here: https://github.com/vuetifyjs/vuetify/issues/3941#issuecomment-730545443

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
