### ISSUE TITLE
[Bug Report] Masonry Layout not working 

### ISSUE THREAD

**Issue by navaneethsr** [vuetifyjs/vuetify#3945]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 8.1

### Steps to reproduce
1- Enter more text in the purple v-card.
2- Run the script.

### Expected Behavior
The size of first card should be resized and other cards should retain their original size.

### Actual Behavior
Observe that when the size of first card changes, the other cards size also changes corresponding to the size of first card.

### Reproduction Link
[https://codepen.io/navaneethsr/pen/KRNKqr](https://codepen.io/navaneethsr/pen/KRNKqr)

### Other comments
Our requirement is while increasing the size any card, other card's size should not get affected.

**Comment by nekosaur** [comment]
The vuetify grid system is not a masonry layout. You will have to use some kind of masonry plugin.

**Comment by navaneethsr** [comment]
can you suggest a better plugin ?

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
