### ISSUE TITLE
[Bug Report] Toolbar extension adds "slot" class to layout components

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#3946]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
Create a `v-toolbar` and set `slot="extension"` to a component such as `v-container` or `v-layout`. It will add "slot" to the class list of the rendered component. For example, in the case of a `v-layout` it renders:

```
<div class="toolbar__extension">
    <div class="layout slot">Extension</div>
</div>
```
The functionality is not directly broken, but something is not handled properly since it adds that slot prop as a class. With other components, such as a `v-btn` or just plain HTML elements like `div` this is not the case.

### Expected Behavior
Be able to assign any component to the slot without wrapping it in `<template slot="extension"></template>` tags.

### Actual Behavior
Certain components misbehave when assigned to the slot.

### Reproduction Link
[https://codepen.io/anon/pen/MGbKya](https://codepen.io/anon/pen/MGbKya)

### Other comments
Not sure if this bug might affect other components that accept slots as well.

**Comment by KaelWD** [comment]
Seems like it might be more of a vue bug than anything else. Layout components just turn their props into classes, and shouldn't be receiving `slot` at all.

**Comment by sindrepm** [comment]
@KaelWD Hmm ok. So the issue is that Vue passes "slot" through to `data.attrs`? Maybe add a conditional to that filter so it ignores "slot" attribute?

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VGrid/grid.js#L18

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/RyoaBW?editors=1010

https://github.com/vuejs/vue/issues/7841#issuecomment-373651624

I guess we'll just have to filter it unless that issue gets resolved.
