### ISSUE TITLE
[Feature Request] Behavior of expansion panel with big amount of content

### ISSUE THREAD

**Issue by wildstyles** [vuetifyjs/vuetify#3947]
### Problem to solve
https://codepen.io/anon/pen/jxWzbO?&editors=100
If you try to expand last panel of current viewport - item is not become fully visible to user(https://prnt.sc/japvmm). Same happens then you scroll to bottom of opened panel and try to open another(only bottom part of new item become visible, https://prnt.sc/japxdq)
Is is expected behavior?  

### Proposed solution
Expaned item should be centered on open event

**Comment by KaelWD** [comment]
This is pretty simple to implement yourself, and I'm not sure that it would be wanted in all cases

https://codepen.io/anon/pen/Vxmjwe?editors=1010

**Comment by KaelWD** [comment]
Use an event listener then: https://codepen.io/anon/pen/ergEzY?editors=1010

**Comment by wildstyles** [comment]
Thanks!

**Comment by Crispried** [comment]
@KaelWD 

It sounds like "yes, it works wrong but, it's not too hard to create workaround", isn't it? 

Also, in which cases on your opinion expansion panel should have described behavior? I'm not sure if you got the whole picture of this issue so, here is a gif with 2 examples.
![expansion_panel_bug_reproducing](https://user-images.githubusercontent.com/14315420/39418662-450f1614-4c64-11e8-8ad0-df22b610e561.gif)
I'm pretty sure that there are not any cases when such behavior is desired. And finally if on desktops such a behavior is annoying but, it's possible to work with it, on mobiles it becoming hell.

Please think about it.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
