### ISSUE TITLE
[Feature Request] Buttons without Capslock

### ISSUE THREAD

**Issue by haexhub** [vuetifyjs/vuetify#3948]
### Problem to solve
Could you please add a property to the v-btn, that the text is not always formatted in big letters all the time. I would like to use the v-btn with unformatted text. 

### Proposed solution
Add a props to the v-btn, so that people can chosse, if they want capslock or normal text.

**Comment by praveenpuglia** [comment]
@KaelWD @johnleider Even I have wished this for a really long time. Could there be a prop that does that? Something like `case` with values like
- `uppercase`
- `titlecase`
- `user` - As authored by User.

**Comment by johnleider** [comment]
I think this could be solved better with helper classes.

`.text-capitalize`
`.text-uppercase`
`.text-lowercase`

Then it can be used for a multitude of scenarios for developers.

**Comment by johnleider** [comment]
We could either add a helper for `.text-normal` or something similar. Additionally, you could just add a custom class to the buttons that need this and apply custom css.

**Comment by XanderLuciano** [comment]
I'd also agree that this should be a css class. My proposal would be to add helper classes such as:  
`text-transform-uppercase`, `text-transform-lowercase`, `text-transform-none`

Usage:  
`<v-btn class="text-transform-none">Continue</v-btn>`

IMO this would be a simple addition and easy to use without complicating anything.

**Comment by johnleider** [comment]
These helpers have been added to v1.1 #3598

**Comment by plaa** [comment]
In the commit I see CSS classes `text-capitalize`, `text-lowercase` and `text-uppercase` but no option for no text transformation (`text-transform: none`).  Am I missing something?

**Comment by plaa** [comment]
The problem is that the button documentation doesn't refer to this documentation in any way. 

Someone (including myself) who is looking to make button texts non-capital will be looking through the 10 pages of options and examples the buttons have, and find no avail. I didn't even consider that it would be documented somewhere else, much less where to find it. I ended up writing my own CSS class for it.

**Comment by johnleider** [comment]
I actually ran into this the other day, I'll add the text-transform: none in as a class.

**Comment by johnleider** [comment]
It doesn't refer to it because its style is assumed to be capital based upon material design spec. It would be inferred that in order to change that you would need to apply some sort of style to overwrite it. That's what you would do with any framework.

**Comment by plaa** [comment]
Would it hurt to say that text is capital by default per material design spec, and a link to the typography section if you need to change it?  Maybe even have an example of it?  There are use cases where capital text is just wrong.

Just trying to make the docs more helpful.

**Comment by jacekkarczmarczyk** [comment]
I agree with @plaa, it's repeating question, it could be mentioned in docs

**Comment by GENL** [comment]
Just use the class .text-none

**Comment by garyo** [comment]
I came here because I have a button that needs to be the case I set it to. Agree with others here who suggest it be included in the doc somehow.

**Comment by FredrikWendt** [comment]
Material Design spec includes several examples where button text is not capitalized. See https://material.io/design/components/buttons.html#implementation
Google Contacts is an example application that uses Camel Case for pretty much all of its buttons with text on them. Every e-mail read in Gmail ends with three outlined buttons (reply, reply all, forward) with uncapitalized button labels.

Hence, I would've preferred to set this globally and not for every single button. Cross-linking to #1443 where this was requested, and turned down.

**Comment by dimshik100** [comment]
From Vuetify version 2 you need to use `text-lowercase` class instead of `text-none`

**Comment by ColinLaws** [comment]
Instead of using .text-none everywhere (or wrapping the v-btn in my own customized implementation), I just added this to my app's scss:

```css
.v-btn {
  text-transform:none !important;
}
```
