### ISSUE TITLE
[Feature Request] v-select with icons for each item

### ISSUE THREAD

**Issue by haexhub** [vuetifyjs/vuetify#3949]
### Problem to solve
if you have to select something from a select field, for example the language of the page, it would be nice to give each selection item an individual icon, like flags for each language.

### Proposed solution
one option could be, to change the prop type of items for v-select. Currently its an array of strings. It could be an array of objects like this
[ { icon: 'german_flag', text: 'de' }
, { icon: 'englisch_flag', text: 'en' }
]
and than its up to you to implement it nicely. ;) 

Another way could be to add an extra component like v-select-item 

v-select v-model = 'selected_language'
  v-select-item v-for = 'language in available_languages'
    v-btn {{ language.name }}
      v-icon {{ language.icon }}
  

The last one is way more flexible.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/selects#example-scoped-slots
