### ISSUE TITLE
[Bug Report] Vuetify requires unsafe-inline CSP

### ISSUE THREAD

**Issue by grk** [vuetifyjs/vuetify#3950]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.13
**Browsers:** Safari 11.2, Google Chrome
**OS:** Mac OS 10.13.4

### Steps to reproduce
1) Use Vuetify on a website that uses Content Security Policy headers

### Expected Behavior
Website should load without issues

### Actual Behavior
Loading theme specific styles crashes on CSP, at `document.head.appendChild(style);` with error 

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https: https://fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-AiuDn+GCYI1wpuA310/prXDmyv992zTtsIWKiuXkWCA='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Reproduction Link
[https://codepen.io/anon/pen/zjooqW](https://codepen.io/anon/pen/zjooqW)

**Comment by KaelWD** [comment]
Would adding a nonce to it be acceptable? Otherwise you can disable the theme styles entirely as #3349

**Comment by grk** [comment]
A nonce would be the best solution. With Rails 5.2, we get a `<meta name="csp-nonce" content="the_actual_nonce" />` tag in head, so ideally this could be used.
