### ISSUE TITLE
[Feature Request] (VList) Support transition group for v-list-tile

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3956]
### Problem to solve
- Allow transition effect item by item when load a list
- Allow transition when remove or add an item in a list
- Allow movement between list items when sort them
- Create transition group component to be used everywhere

### Proposed solution
- Add a prop to VList called `transition-item`, `item-transition`, `transition-tile` or `tile-transition`, which receives a transition as string (example `fade-transition`).
- Create `v-{name}-transition-group` components

Vue.js `<transition-group>` can help on that:
https://vuejs.org/v2/guide/transitions.html#List-Entering-Leaving-Transitions
https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions

**Comment by spaszek** [comment]
Are there any plans to actually implement this? :)

**Comment by johnleider** [comment]
This can be accomplished by transitional means using our built in transitions with the **group** property.
