### ISSUE TITLE
[question] dark material

### ISSUE THREAD

**Issue by 0xFireball** [vuetifyjs/vuetify#396]
hello,
 
I am looking to create a theme using Vuetify's theme system to get a dark-material theme, like the one displayed at the bottom of one of the material design guidelines pages: (https://material.io/guidelines/style/color.html#color-themes).

![image](https://cloud.githubusercontent.com/assets/15932100/25206300/fbfb2abe-251b-11e7-9087-2365b6a200be.png)

How can I create a dark theme to get a feel like this? By default the background is white and the secondary is dark, creating a kind of hybrid style, but I would like to make a completely dark material themec

thank you for maintaining vuetify!

**Comment by mfferreira** [comment]
@0xFireball Instructions to setup theme colors can be found here: https://vuetifyjs.com/style/theme

**Comment by 0xFireball** [comment]
@mfferreira I don't see any way to theme the entire page background, am I missing something? My goal is to get a complete dark material theme.

**Comment by mfferreira** [comment]
@0xFireball Right, `.content` color is actually hardcoded. So for now you'll need to style it yourself right now.

**Comment by 0xFireball** [comment]
thanks for the quick response.

@mfferreira are there plans to make this customizable?

**Comment by mfferreira** [comment]
@0xFireball Looking at the spec, I think it makes sense to able to set that as part of the theme.

@johnleider Thoughts?

**Comment by johnleider** [comment]
Agreed, if it's in spec, it should be in Vuetify.

**Comment by johnleider** [comment]
I have added the ability to set theme on ```v-app```. This changes the root color and changes backgrounds of a few components. I've also made a few updates throughout other components so they look better with the dark theme.

**Comment by 0xFireball** [comment]
thanks!
