### ISSUE TITLE
[Feature Request] Additional stepper icon support

### ISSUE THREAD

**Issue by XanderLuciano** [vuetifyjs/vuetify#3963]
## Issue

I'd like to create a stepper that allows you to edit previously completed steps, but not allow jumping ahead until a step is completed. I'd like all completed steps to have a check mark, the current step to have an editing icon, and the default styling for future steps (as shown in the photo and code pen below).

I'd like the ability to further customize the icons for the stepper.

Here's what I'm trying to accomplish: https://codepen.io/XanderLuciano/pen/ELZwQL

![image](https://user-images.githubusercontent.com/13877593/39405760-cb0dbac8-4b5f-11e8-9147-fb1e5577c192.png)
So in order to accomplish this I am setting step properties like so:

```
<v-stepper-step
:complete-icon="'edit'"
:edit-icon="'check'"
:complete="(index + 1 ) <= stepper" 
:editable="(index + 1) < stepper" ...>
```

i.e. All previous steps are editable, and all steps are complete *including* the current one, and all future steps are not editable and not completed. Then in order to get the icons to display as I want, I have to swap the edit and completed icons.

This is because the "edit" icon overrides the completed icon. So by reversing the roles, I can have a step that appears correctly, but is coded "backwards"

## Proposed solution:

I think the idea of keeping it simple should be used and instead of making some type of configuration to set icon priority, I'd like the ability to just directly set the icon or icon state for each step. Something like: `:icon-state="editable"` / `:icon-state="completed"` or :icon="edit"` / `:icon-state="check"`

## Why is this an actual issue?

The only reason why this is an "issue" is because I don't like the idea of having to set an incomplete step as "completed" prematurely. My options are either:  
1) Change the edit icon to a check mark - issue: The current step won't have the edit icon
2) Don't make previous editable, instead use custom styling and click event handler to manually create editable functionality - issue: too overkill
3)Don't make previous editable, add a back button - Poor UX compared to editable behavior
4) Swap editable and completed icons - cons: current step now registers as complete, while it's incomplete

It's not a big issue, but seems like it should be fairly straightforward to override the current icon with a custom property. If you're open to the idea, but feel it is more effort than it's worth, I wouldn't mind creating a PR with the proposed solution. Just wanted to start a discussion before going through the trouble of learning the inner workings of veutify.

**Comment by johnleider** [comment]
This is being moved to v2.0 to coincide with other stepper updates.

**Comment by jaminroe** [comment]
I also was looking to change the icons to Font Awesome icons in the steppers, and it just won't work ☹️ Maybe there's some way to "hack" it?

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
