### ISSUE TITLE
[Bug Report] Bottom navigation ripple is limited in its button

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#3964]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Click on some button

### Expected Behavior
Ripple effect should not be limited to its buttom and follow [spec](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior)

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B3321sZLoP_HQWtkdUY4U3lla0U/components-bottomnavigation-behavior-hierarchy.webm

### Actual Behavior
Ripple only inside the button.

### Reproduction Link
[https://codepen.io/anon/pen/MGJOpB](https://codepen.io/anon/pen/MGJOpB)

**Comment by johnleider** [comment]
This is no longer applicable in the new spec.
