### ISSUE TITLE
[Bug Report] v-tabs jumps back to the selected tab w/ pagination

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#3966]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 60.0.3112.101
**OS:** Windows 8.1

### Steps to reproduce
Open the code pen and click on the ">" pagination button for v-tabs

### Expected Behavior
The pagination works correctly and displays the next set of tabs

### Actual Behavior
The pagination hops back to the selected tab

### Reproduction Link
[https://codepen.io/anon/pen/wjgZBj](https://codepen.io/anon/pen/wjgZBj)

**Comment by jacekkarczmarczyk** [comment]
Looks like a bug but could you please narrow down the reproduction to minimal? There's a ton of unrelated staff there, no need for other drawers, toolbar, footer or anything in drawer except the tabs

**Comment by DRoet** [comment]
@jacekkarczmarczyk Sorry my bad, I've updated the codepen. it seems to happen within an navigation-drawer

**Comment by svdongen** [comment]
I don't see this problem in Chrome (Chrome/69.0.3497.100) on Windows (7).

**Comment by DRoet** [comment]
@svdongen you are right, I totally forgot about this issue, it seems to be resolved
