### ISSUE TITLE
[Bug Report] v-data-table duplicates icons in rows when sorting

### ISSUE THREAD

**Issue by creynir** [vuetifyjs/vuetify#3967]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.11
**Browsers:** Chrome 66.0.3359.117
**OS:** Mac OS 10.13.4

### Steps to reproduce
1)  Try to sort table with icons in rows

### Expected Behavior
Rows are sorted included icons 

### Actual Behavior
Icons don't change the placement, there is duplication issue also

### Reproduction Link
[https://codepen.io/creynir/pen/rvjrWq](https://codepen.io/creynir/pen/rvjrWq)

### Other comments
I tried many ways to bind icons to the rows, but the problem with wrong placement stays.

**Comment by KaelWD** [comment]
Font awesome 5's js doesn't work with Vue: https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727

**Comment by creynir** [comment]
Thank you, i tried to add something like a key, but didn't thought about <tr> tag, it seems like a good solution.

**Comment by jacekkarczmarczyk** [comment]
You can also add key to 'td' tag
