### ISSUE TITLE
[Feature Request] Navigation Drawer conditional rendering

### ISSUE THREAD

**Issue by rajagopalx** [vuetifyjs/vuetify#3970]
### Problem to solve
I want to load data from rest API in Navigation drawer on demand. Like If the navigation drawer gets activated then only data have to fetch from API.

### Proposed solution
Like lazy props in bottom sheet.

**Comment by nekosaur** [comment]
Please provide more information about this feature request. I am not clear on what you want to achieve. A markup/codepen illustrating the issue would help.

**Comment by KaelWD** [comment]
All the components that currently implement `lazy` are either detachable (performs a bunch of slow dom manipulation), duplicated a lot (menus, tooltips), or unlikely to be opened by the user. If you want to fetch data then simply watch the drawer's model.
