### ISSUE TITLE
[Bug Report] Pressing Enter in VSelect doesn't clear the selected index

### ISSUE THREAD

**Issue by xlm** [vuetifyjs/vuetify#3972]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.2
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
1. Enter 'cd' into the VSelect
2. Press enter (this selects 'bcd')
3. Pressing tab can no longer change the focus out of the VSelect (cycles between selecting/deselecting the first element 'abc')

### Expected Behavior
Pressing enter should have the same behaviour as pressing tab:
1. Enter 'cd' into the VSelect
2. Press tab (this selects 'abc')
3. Press tab again, this switches focus to the next field.

### Actual Behavior
Tab no longer allows the user to change focus to the next input field. User is stuck cycling between selecting and deselecting the first element of the VSelect.

### Reproduction Link
[https://codepen.io/anon/pen/MGpQXp](https://codepen.io/anon/pen/MGpQXp)

**Comment by KaelWD** [comment]
Fixed in 1.1: https://codepen.io/anon/pen/gKvVBr
