### ISSUE TITLE
[Bug Report]  transitionend called twice - navigation drawer

### ISSUE THREAD

**Issue by sagikarni** [vuetifyjs/vuetify#3977]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Click the button

### Expected Behavior
event will be invoked once

### Actual Behavior
event invokes twice

### Reproduction Link
[https://codepen.io/skarni/pen/odZVEK?&editors=101](https://codepen.io/skarni/pen/odZVEK?&editors=101)

**Comment by KaelWD** [comment]
Correct. One is for `transform`, the other for `box-shadow`. This is native browser behaviour.

**Comment by sagikarni** [comment]
Thx !
Though it will be much cleaner to have opened and closed events

**Comment by sagikarni** [comment]
The @input is called at the begining of the transition. (e.g. "opening" , "closing")
I would expect to have an event at the end of the transition (add the events "opened" , "closed")
thx
Sagi
