### ISSUE TITLE
[Bug Report] data table set totalitems cannot work with search

### ISSUE THREAD

**Issue by SvenWangChina** [vuetifyjs/vuetify#3978]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 66.0.3359.117
**OS:** Mac OS 10.13.4

### Steps to reproduce
when I input "o" in search textfield, the pagination don't show "1-5 of 8", it show " - "

### Expected Behavior
I want it show right pagination after search

### Actual Behavior
show wrong pagination info

### Reproduction Link
[https://codepen.io/svenwangchina/pen/JvNLBz](https://codepen.io/svenwangchina/pen/JvNLBz)

**Comment by nekosaur** [comment]
The internal search functionality (together with sorting and pagination) is disabled when using the `total-items` prop since you're getting your data from a backend. You need to search through your backend.
