### ISSUE TITLE
[Bug Report] Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by akash58** [vuetifyjs/vuetify#3979]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.12
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
After adding the a-la-carte in nuxtjs. i'm getting Cannot read property 'install' of undefined. i'm tried to solve the issue to changing the version of vuetify but not any affect on this eror

### Expected Behavior
After adding a-la-carte in nuxt i am expected then i will use require component of vuetify  

### Actual Behavior
but after adding a-la-carte in nuxt i'm getting error of Cannot read property 'install' of undefined

### Reproduction Link
[https://codepen.io/](https://codepen.io/)

### Other comments
please can you give me the solution of how to proper way to do a-la-carte in nuxtjs

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/nuxt

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by akash58** [comment]
Thank you very much, your solution is helpful for me.

**Comment by akash58** [comment]
Hi Kael,

i tried your template you provided me its working template but then after adding my dependencies in package.json then i'm getting 

**TypeError
Cannot read property 'install' of undefined** 

this is my package.json depencies please can you verify and suggest me what am i doing wrong?

"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "format": "prettier --write '**/*.{js,jsx}'",
    "lint": "eslint --fix --ext .js,.vue --ignore-path .gitignore .",
    "eslint-check": "eslint --fix --print-config .eslintrc.js | eslint-config-prettier-check",
    "prettier-watch": "onchange '**/*.js' -- prettier --write {{changed}}",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxtjs/pwa": "^2.0.8",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "nuxt": "^1.0.0",
    "vuetify": "^1.0.0",
    "js.cookie": "0.0.4",
    "vue-meta": "^1.5.0",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@nuxtjs/axios": "^5.3.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-imports": "^1.4.1",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-config-prettier": "^2.9.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-vue": "^4.0.0",
    "node-sass": "^4.8.3",
    "prettier": "^1.12.1",
    "sass-loader": "^6.0.7",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1"
  },

**Comment by usb248** [comment]
Same error. I don't understand why this issue is closed without help/explication ... 👎

**Comment by KaelWD** [comment]
Because I don't know what you've done. We have a template that works correctly, and if you can't follow that then you need to provide more information.

**Comment by DevHossamAli** [comment]
Make sure that you configured Babel plugins correctly..

**babel.config.js** or **.babelrc**

`{
  "presets": [
    ["env",  {"modules": false}],
    ["stage-2"]
  ],
  "plugins": [
    ["transform-imports", {
      "vuetify": {
        "transform": "vuetify/es5/components/${member}",
        "preventFullImport": true
      }
    }]
  ]
}`


hope that helps
