### ISSUE TITLE
Menus in toolbars are somewhat buggy

### ISSUE THREAD

**Issue by devmattrick** [vuetifyjs/vuetify#398]
### Steps to reproduce
Reproducing this is somewhat challenging, but occasionally when you click click on the **top half** of a dropdown menu activator in a toolbar, the menu's position changes oddly. I've noticed if you click in rapid succession, this is more likely to occur. Here is an [example](http://i.imgur.com/BgB7D3i.gif) (apologies for the poor quality).

### Versions
This is tested in Chrome 57, but I believe this will affect all browsers. This affects the latest stable version of Vue (2.2.6) and Vuetify (0.10.4).

### What is expected ?
The menu will be positioned based on the properties assigned to it.

### What is actually happening ?
The gif above illustrates this issue, but the menu shifts. This is caused by the top attribute being set to something unexpected (for [example](http://i.imgur.com/0iprlHh.gif), when it's supposed to be 50px in the gif, it is somehow changed to 14.9392px). The "top" property is also not consistent when it changes; I've seen anything from 11px - 14px.

I'm not too sure how or why this happens and I know its a minor bug, but I figure its worth reporting.

### Reproduction Link
This can be reproduced in the [Vuetify documentation](https://vuetifyjs.com/components/toolbar).

**Comment by johnleider** [comment]
This is something I've been aware of, but has been extremely low priority due to the conditions needed to produce it. I have some menu cleanup planned for v0.12.0 and will make sure to address this.

**Comment by johnleider** [comment]
Fixed. Also cleaned up some other areas of the menu.

**Comment by jamesxv7** [comment]
Fixed on current version or for the release 0.12.0? I'm seeing something similar in current version (0.11).

**Comment by devmattrick** [comment]
@jamesxv7 I don't believe it has been in an official npm release yet. I'm guessing it'll be out next milestone.
