### ISSUE TITLE
[Need help] Hamburger bars on Vuetify in complex layout

### ISSUE THREAD

**Issue by pirmax** [vuetifyjs/vuetify#3981]
I use **Vuetify 1.0.10**.

I want put *v-toolbar-side-icon* just beside slider/my name, above Dashboard title. But it is hidden by the navigation drawer where my name and first name.

I tried to add clipped and clipped-right but the orange headband come onto Dashboard toolbar.

    <template>
      <v-app id="inspire" dark>
    
        <v-navigation-drawer
          left
          :mini-variant="miniVariant"
          v-model="drawerLeft"
          fixed
        >
           
        </v-navigation-drawer>
    
        <v-card flat>
          <v-toolbar dark flat extended :color="dark ? 'dark' : 'orange'">
            <v-toolbar-side-icon @click.stop="drawerLeft = !drawerLeft"/>
            <v-spacer/>
            <v-btn flat>
              <v-icon left>create</v-icon> <span class="hidden-md-and-down">Publish Something</span>
            </v-btn>
            <v-btn flat>
              <v-icon left>account_circle</v-icon> <span class="hidden-md-and-down">Profile</span>
            </v-btn>
          </v-toolbar>
          <v-layout row pb-2>
            <v-flex xs8 offset-xs2>
              <v-card class="card--flex-toolbar">
                <nuxt/>
              </v-card>
            </v-flex>
          </v-layout>
        </v-card>
      </v-app>
    </template>
    
    <script>
      export default {
        name: 'app',
        data: () => ({
          pageTitle: null,
        })
      }
    </script>
    
    <style>
      .card--flex-toolbar {
        margin-top: -64px;
      }
    </style>

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/sd0g6.png

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
