### ISSUE TITLE
[Feature Request] Ability to set body text color with a-la-carte setup

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#3983]
### Problem to solve
Right now there is no proper way to set text color e.g. $material-light.text.primary

### Proposed solution
Something like with $body-font-family where u can just define it your app.styl and then import vuetify app.styl and all works fine. There is $body-color-light and $body-color-dark in sources, but they seems to be not used right now.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/framework/theme#modifying-stylus-variables
https://next.vuetifyjs.com/en/customization/sass-variables
