### ISSUE TITLE
[Feature Request] Add password reveal to VTextField

### ISSUE THREAD

**Issue by qricambi** [vuetifyjs/vuetify#3987]
### Problem to solve
Adds a built-in way to achieve password reveal in vuetify, without having to declare a variable for every password field.

### Proposed solution
[Link to our solution gist](https://gist.github.com/qricambi/9c545ac9084eb6d5f2a7a80d04932716)

**Comment by ll931217** [comment]
I think it would be better if you allow props to change the icons.

**Comment by qricambi** [comment]
Yes my proposed solution was somewhat unclear.
This was the solution we momently used to solve this problem in our application.
It could be cool to add a props that enables this feature directly into v-text-field, but that's just my opinion.

Thanks for the help

**Comment by KaelWD** [comment]
I think this is just a "nice to have" that would either be too complex to integrate into v-text-field, or too simple to justify a separate component. You can *very* easily do this yourself. 

```vue
<template>
  <v-text-field
     v-bind="$attrs"
     v-on="$listeners"
      :append-icon="visible ? 'visibility_off' : 'visibility'"
      :append-icon-cb="() => (visible = !visible)"
      :type="visible ? 'text' : 'password'"
  />
</template>

<script>
  export default {
    data: () => ({
      visible: false
    })
  }
</script>
```
