### ISSUE TITLE
[Feature Request] Data tables hide column by screen size

### ISSUE THREAD

**Issue by 0vvland** [vuetifyjs/vuetify#3993]
### Problem to solve
It's make wide table more relevant to screen size.

### Proposed solution
Add to headers structure parameter hide. Like:
headers: { hide: 'mdAndDown', text: ..., value:..., etc...}

**Comment by nekosaur** [comment]
This can already be achieved with relative ease in user land https://codepen.io/anon/pen/bMQGbm

**Comment by 0vvland** [comment]
This is very good decision. Thanks. But I have similar big tables at least on five pages of project. And it will be code duplication for them. I think it'll be good have this functionality in DataTable component.

**Comment by 0vvland** [comment]
Better way is make hide condition a function returning true/false. In some cases it will be very useful.

**Comment by KaelWD** [comment]
This can be solved in user land and doesn't require additional API. Create a wrapping component if you will have code duplication.

**Comment by 0vvland** [comment]
This solution https://codepen.io/anon/pen/bMQGbm required v-if on few columns on each rows. Added to component functionality it will take only on a item slot.
