### ISSUE TITLE
[Bug Report] Autocomplete input still visible when an initial value is set

### ISSUE THREAD

**Issue by birdlavv** [vuetifyjs/vuetify#3995]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Mac OS 10.13.4

### Steps to reproduce
Open Codepen in Chrome and note the 1-2px line formed by a portion of still visible text

### Expected Behavior
Setting an initial value for the autocomplete will display the current value

### Actual Behavior
The text is duplicated and shown twice, one of which is shown as a thin line when it should be not visible

### Reproduction Link
[https://codepen.io/George6789/pen/OZxdmj](https://codepen.io/George6789/pen/OZxdmj)

### Other comments
When the input is first interacted with it resolves. Attempted to recreate in other browsers, but it seems this issue is limited to Chrome. Probably due to a bug in Chrome as the input with a height: 0; is still visible.

**Comment by johnleider** [comment]
This has been resolved on v1.1
