### ISSUE TITLE
[Bug Report] <v-icon> puts extra space in front of some icons

### ISSUE THREAD

**Issue by lobo-tuerto** [vuetifyjs/vuetify#3997]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64, Linux

### Steps to reproduce
```html
<span style="border: 1px solid red"><v-icon color="success">user_account_box</v-icon></span>
<span style="border: 1px solid red"><v-icon color="success">user_account_box</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">create_new_folder</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">person</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">nonsense</v-icon>some text</span>
```

### Expected Behavior
`<v-icon>` should not put extra space in front of icons.
If icon keyword is not found, should not take any space.

### Actual Behavior
`<v-icon>` puts some extra space in front of some icons.

### Reproduction Link
[https://codepen.io/lobo-tuerto/pen/aGLrKz](https://codepen.io/lobo-tuerto/pen/aGLrKz)

![screenshot-2018-05-06](https://user-images.githubusercontent.com/5730/39677720-538162ac-5145-11e8-92bb-69ab2eb6ad3b.png)

**Comment by KaelWD** [comment]
Nothing we can do about that, material icons use a ligature font.
