### ISSUE TITLE
vendor chunk hashing

### ISSUE THREAD

**Issue by markschultz** [vuetifyjs/vuetify#40]
vendor chunk hash seems to change on every app code change when I would expect it to stay the same unless a vendor dep is updated. https://github.com/webpack/webpack/issues/1315 is potentially relevant.

**Comment by markschultz** [comment]
md5sum shows that app.hash.js, styles.hash.css, vendor.hash.js all have different content despite the fact I only made an app.vue change. I would expect only app.hash.js to change right?

**Comment by johnleider** [comment]
This pertains to both the webpack and webpack-ssr vue-cli templates I assume?

**Comment by markschultz** [comment]
i'm not sure if this is what's expected but when i run `npm run build` for the webpack template i just get a single file `dist/build.js` no hashes or css or vendor.js

**Comment by johnleider** [comment]
That is correct. The webpack and simple vue-cli repositories are forked from the official vue templates. Only the webpack-ssr template contains chunk hash.

**Comment by markschultz** [comment]
ok well in that case i can say `dist/build.js` has a different md5sum after a small change to app.vue but I would expect that and there is no hash issue because that template doesn't use chunk hash.

**Comment by johnleider** [comment]
Will definitely take a look at this.

**Comment by markschultz** [comment]
I also just tested https://github.com/vuejs-templates/webpack and vendor.hash.js/map and app.hash.css/map **do** stay the same with minor app.vue changes so presumably the answer is somewhere in their webpack config.

**Comment by markschultz** [comment]
hey just fyi this is only partially fixed with that pull. the vendor.hash.js is caching correctly but the styles.hash.css/map is still changing every build.

**Comment by johnleider** [comment]
I understand. It will be a new issue on the webpack-ssr repo.
