### ISSUE TITLE
[Bug Report] FAB icon not centered vertically

### ISSUE THREAD

**Issue by mkpaz** [vuetifyjs/vuetify#4001]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Just load page.

### Expected Behavior
FAB icon centered vertically

### Actual Behavior
FAB icon not centered vertically

### Reproduction Link
[https://codepen.io/miklever/pen/PeOeLZ](https://codepen.io/miklever/pen/PeOeLZ)

### Other comments
It looks that it's happened because of md icon `display=inline-block` property. Please see CSS in reproduction template attached.

**Comment by KaelWD** [comment]
Remove `class="d-block"`

**Comment by KaelWD** [comment]
vuetifyjs/vuetifyjs.com#353
