### ISSUE TITLE
[Bug Report] Horizontal scrollbar not working in datatables

### ISSUE THREAD

**Issue by anandrikka** [vuetifyjs/vuetify#4004]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.13
**Browsers:** Chrome 66.0.3359.139
**OS:** Mac OS 10.11.6

### Steps to reproduce
A very simple use case of datatable with more columns then view-port. Horizontal scroll is not visible

### Expected Behavior
Horizontal scroll should be available when the viewport is not enough to fit the columns

### Actual Behavior
Horizontal scroll is not visible when there are more columns than viewport fits.

### Reproduction Link
[https://codepen.io/anandrikka/pen/bMYyzL](https://codepen.io/anandrikka/pen/bMYyzL)

**Comment by nekosaur** [comment]
Seems to be platform specific? Horizontal scroll shows for me on Windows 7 and Chrome 65.0.3325.181

**Comment by KaelWD** [comment]
Can anyone else confirm this issue? It doesn't happen for me either on windows or linux.

**Comment by Melchyore** [comment]
It works fine on Windows 7 and FF 60.0.2

**Comment by DanielStefanK** [comment]
Happend to me on linux chromium and firefox, but not under the reproduce link.

**Comment by dfmiller** [comment]
This may be stating the obvious, but Macs, by default, don't show a scrollbar unless you are scrolling.  Could this be the problem?

They show up for me
Chrome 68.0.3440.106 (Official Build) (64-bit)
Mac OS 10.13.6

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to:
- [x] Requested information not provided (inactivity for 14 days)
