### ISSUE TITLE
[Bug Report] Printing page doesn't render some CSS (eg, colors)

### ISSUE THREAD

**Issue by jaimesanz** [vuetifyjs/vuetify#4007]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Opera 52.0.2871.99, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Use the browser's print dialog ("ctrl + p" in Opera/Chrome)

### Expected Behavior
Elements in rendered document **should** have colors

### Actual Behavior
Elements in rendered document don't have colors (eg, buttons, badges, chips, u.s.w)

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/badges/character.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/badges/character.vue)

**Comment by jacekkarczmarczyk** [comment]
I guess you may need to setup your printer correctly, check first if other pages print elements with background colors. Closing as most probably it's a user error, reopen if i'm wrong

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/39832680-3d489a14-540b-11e8-85cc-06ee5cfd327a.png)

**Comment by jaimesanz** [comment]
You are absolutely right, it was a browser configuration problem.

@KaelWD setting "background-graphics" flag solved it. Thanks!
