### ISSUE TITLE
[Bug Report] v-data-iterator does not show progress

### ISSUE THREAD

**Issue by WiRight** [vuetifyjs/vuetify#4008]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.30
**OS:** Linux x86_64

### Steps to reproduce
I imitate fetching data (using setTimeout) and set loading prop false while "fetching"
But progress bar not created
(if add v-progress-linear - nothing will be shown)

### Expected Behavior
Show progress bar like if using v-data-table (cause it both using mixin Progress)

### Actual Behavior
nothign shown

### Reproduction Link
[https://codepen.io/WiRight/pen/YLYBxz](https://codepen.io/WiRight/pen/YLYBxz)

### Other comments
I am sorry for future for my bad english and if i write wrong code =3

**Comment by nekosaur** [comment]
v-data-iterator does not actually support `loading` prop. It is a remnant of a previous refactor and should be removed.

**Comment by WiRight** [comment]
@nekosaur ok, thx) i will be using `v-if` with `v-progress-linear`

**Comment by dchenk** [comment]
@nekosaur the [docs here](https://vuetifyjs.com/en/components/data-iterator) still describe the `loading` prop. When was it removed? What's the correct way to show a loading indicator now?
