### ISSUE TITLE
[Feature Request] Tab v-model issue when changing tab order programatically

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#4009]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
- Click on "Swap elements".

### Expected Behavior
After the elements are swapped, the Tab 1 is supposed to be accessible when the v-model (here 'active') is set to 1.

### Actual Behavior
After the elements are swapped, the order of the tab internally is the same, so Tab 1 still accessible only when the v-model is set to 0.

### Reproduction Link
[https://codepen.io/Kleemer/pen/bMaXjN](https://codepen.io/Kleemer/pen/bMaXjN)

**Comment by KaelWD** [comment]
This is because vue reuses components if they don't have a key. We can't do anything about this except tell people to key their tabs if they want to do anything like this.

**Comment by kdepp** [comment]
Workaround above (Vuetify 1.0.7) doesn't work any more for latest Vuetify today. 

As of Vuetify 1.3.0,  `value` or `v-model` has to be a number instead of a string.  Updated code pen:  https://codepen.io/anon/pen/ZmLEpx?editors=1001
