### ISSUE TITLE
Vertical Steppers - steps should be always visible / fixed

### ISSUE THREAD

**Issue by rzb** [vuetifyjs/vuetify#401]
The main purpose of the steppers is to give the user a permanent notion of progress. If the step buttons are hidden from the screen, that can't be achieved unless he scrolls before filling the form.

The step buttons should stack at the bottom when the currently active step content is taller than the viewport, and similarly stack at the top when the user scrolls down.

**Comment by mfferreira** [comment]
@rzb Please provide a codepen sample to illustrate what you mean.

**Comment by rzb** [comment]
Sorry, I don't think I can illustrate such functionality in a pen. But think of the Vertical Steppers component as it is in the docs: 

- if content of a certain step is taller than the viewport, he doesn't see the next steps. 
- if he scrolls down, he loses track of the previous steps.

He should be able to see all steps all the time, just like an "affixed" menu.

I've mentioned this to @johnleider before and he got the idea. Perhaps he can explain it better than me.

**Comment by mfferreira** [comment]
Got it. I don't think it should be the component job to figure out how you want to display it.
But you can easily do it by settting the stepper content container heigh yourself.

**Comment by rzb** [comment]
I believe it's part of the behavior expected from a form wizard component. It doesn't make much sense to split a form in multiple steps if the user has to scroll down to find out there are other steps to navigate anyway.

The MD specs are not very specific on this, but they do mention fixing the horizontal steppers control at the top at least:

> On horizontal steppers, the step name and numbers appear on a horizontal bar, which can be fixed to the top of the page when scrolling down.

**Comment by mfferreira** [comment]
You're talking about scrolling up and down...I thought you were talking about vertical steppers.

I understand what you're saying, and maybe that could be an added enhancement for the component, that could be toggled on/off. But as any other component we have, Steppers can be put anywhere and inside any other component, and for this reason it would be very hard (and maybe unwanted behavior) to force the Stepper to stick to a specific layout.

That applies to almost all Vuetify components. We try to avoid enforcing any layout, giving more freedom to the developer.

**Comment by rzb** [comment]
I'm talking about scrolling up and down in vertical steppers specifically :smile: 

Yeah what you say about side effects on layouts makes sense. Perhaps toggling on and off might be a good idea. 

ps.: @johnleider asked me to create this issue and confirmed he would work on it for 0.12.

**Comment by johnleider** [comment]
After working on this for a bit, I've come to the conclusion that it would only work or make sense for the developer to implement their own variation of their specific needs in regards to the fixed on mobile. Reason being is it essentially becomes necessary (especially for vertical steppers) to have an alternate set of elements and structure in order to accommodate some sort of fixed navigation.

For these reasons, I do not feel that it is warranted to create new components to accommodate this use-case. It may be a feature that is added later on, but as of now, there are too many other important tasks to triage.
