### ISSUE TITLE
[Bug Report] Clicking the label does not activate associated text field/select

### ISSUE THREAD

**Issue by nkovacs** [vuetifyjs/vuetify#4013]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.1
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
Click the labels.

### Expected Behavior
The text field/select associated with the label should activate.

### Actual Behavior
The text field/select associated with the label does not activate.

### Reproduction Link
[https://codepen.io/anon/pen/jxZZWV](https://codepen.io/anon/pen/jxZZWV)

**Comment by KaelWD** [comment]
It worked only with v-select in 1.0, now it doesn't with either.

**Comment by nkovacs** [comment]
This is once again broken.
