### ISSUE TITLE
[Bug Report] Data table v-btn multi-line vertical alignment

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#4018]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.30
**OS:** Windows 10

### Steps to reproduce
Open the codepen and note the action icons in the 'Ice cream sandwich' row. They are not vertically aligned middle as they should be.

### Expected Behavior
`v-btn`s should align vertically to the middle of the `<td>` in multi-line rows as text and `v-icon`s do.

### Actual Behavior
`v-btn`s appear to align to the top of the row.

### Reproduction Link
[https://codepen.io/185driver/pen/gzvVRd](https://codepen.io/185driver/pen/gzvVRd)

### Other comments
This codepen is basically a copy of the code example provided in the docs [here](https://vuetifyjs.com/en/components/data-tables#example-crud). I only lengthened the Dessert column text.

Also, it's unrelated to this bug report, but I'm not seeing any effect provided by the `justify-center` class selector. I'm curious as to its purpose.

**Comment by DoritoBandito** [comment]
`td` is not getting set to full height. Have a look at this codepen to get the outcome you're wanting.
https://codepen.io/anon/pen/KRePKP

**Comment by KaelWD** [comment]
Thanks @DoritoBandito. You can actually remove `fill-height` from the td too. 

This is expected, `.layout` overrides the table cell's `display` property.
