### ISSUE TITLE
[Bug Report] v-select it is not reactive when the data changes 

### ISSUE THREAD

**Issue by gygoo** [vuetifyjs/vuetify#4020]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 61.0.3163.91
**OS:** Linux x86_64

### Steps to reproduce
In: https://codepen.io/gygoo/pen/Gdxqym

1. When we enter the value from 1 to 5 in the imput field, select is not set to the appropriate value.

2. When we change the value from 1 to 2, select is not set to the appropriate value.

The above two examples simulate eg incoming data from VUEX -> actions -> axios, or other asynchronous data.

When the data appears with a delay, the selected value is not set.

3. When we change data on the select element - the second select behaves correctly.

### Expected Behavior
Full v-select reactivity

### Actual Behavior
Currently, the selected value is not always set correctly

### Reproduction Link
[https://codepen.io/gygoo/pen/Gdxqym](https://codepen.io/gygoo/pen/Gdxqym)

**Comment by KaelWD** [comment]
Text fields return strings by default, and v-select uses a strict value comparison: <https://codepen.io/anon/pen/jxzyWY?editors=1010>
