### ISSUE TITLE
iOS status bar transparent

### ISSUE THREAD

**Issue by Symous** [vuetifyjs/vuetify#4021]
When I scroll the content from bottom to top, I found that the status bar in iOS is transparent, how can we fix this?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
