### ISSUE TITLE
[Bug Report] v1.1.0-alfa-1 v-text-field as v-menu activator

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#4022]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.1
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
see second text field width...

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
[https://codepen.io/Buzzzzer/pen/odqBjv](https://codepen.io/Buzzzzer/pen/odqBjv)

**Comment by KaelWD** [comment]
You should use `full-width` to make the menu fill its container: https://codepen.io/anon/pen/aGYpBr?editors=1010

The regression here is that v-text-field no longer has flex-grow.

**Comment by buzzzzer** [comment]
I've used full-width before, but after the 1.1 update it looks ugly.
 v-text-field as menu slots are shorter.

**Comment by buzzzzer** [comment]
@KaelWD, I copied your example into my project and....
![image](https://user-images.githubusercontent.com/1981785/39869019-b3247eac-5464-11e8-8422-89028b5aed20.png)
Something strange
All custom style are disabled

**Comment by johnleider** [comment]
I think he means **full-width** on `v-menu`.
