### ISSUE TITLE
[Bug Report] v-select "Cannot read property $refs of undefined"

### ISSUE THREAD

**Issue by johnpyp** [vuetifyjs/vuetify#4023]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Linux x86_64

### Steps to reproduce
Not really sure, it seems when vselect unmounts it triggers

### Expected Behavior
No error in console

### Actual Behavior
Error in console: Cannot read property $refs of undefined

### Reproduction Link
[https://codepen.io/johnpyp/pen/NMYgzY](https://codepen.io/johnpyp/pen/NMYgzY)

### Other comments
There is a note in the source code about it https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/VSelect.js#L130

**Comment by KaelWD** [comment]
The condition in 1.0 was 
```js
return (
  this.isActive &&
  !!this.content &&
  !this.content.contains(e.target) &&
  !!this.$el &&
  !this.$el.contains(e.target)
)
```
