### ISSUE TITLE
[Feature Request] Allow custom filtering for autocomplete select

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#4024]
### Problem to solve
For example it will allow to bring result for both value and text. E.g.  for a  state field autocomplete will be to bring results to show Texas for typed TX ( as well as for typed texa ) when its {value:'TX', text:'Texas'}.

### Proposed solution
Something like for v-datable custom-filter property

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/selects#example-custom-filter

**Comment by aldarund** [comment]
@KaelWD oh thanks, dont know how i missed it :) Asked two times in discord without any results too..
