### ISSUE TITLE
[Bug Report] Cannot close expansion panel

### ISSUE THREAD

**Issue by lebesnec** [vuetifyjs/vuetify#4027]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
1 - click on the header of the expansion panel to open it
2 - click on the "close" button

### Expected Behavior
the expansion panel should close when I set it's value to false

### Actual Behavior
The expansion panel does not close.

### Reproduction Link
[https://codepen.io/anon/pen/NMYwda](https://codepen.io/anon/pen/NMYwda)

### Other comments
if the `toggle` data is initialized with `true`, it works just fine.

**Comment by KaelWD** [comment]
`:value` -> `v-model`

**Comment by lebesnec** [comment]
Thanks, that worked! 
`v-model` should be added to the API documentation of the expansion panel component.
