### ISSUE TITLE
[Bug Report] VNavigationDrawer throws this exception in IE11: Object doesn't support this action

### ISSUE THREAD

**Issue by rick-hidef** [vuetifyjs/vuetify#4031]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
Click a button within the VNavigationDrawer component

### Expected Behavior
No exception occurs.

### Actual Behavior
When clicking a navigation item in the Navigation Drawer, this uncaught exception occurs in IE11: Object doesn't support this action

### Reproduction Link
[https://codepen.io/ricksharp7/pen/PeReML](https://codepen.io/ricksharp7/pen/PeReML)

### Other comments
It appears that this issue was introduced [in this commit](https://github.com/vuetifyjs/vuetify/commit/cf32d903f630fe0e7675ba72dd4a395056d67d0d#diff-442cd2fee6d6530f74d8b9af1cd62d56R330). Just entering  `new Event('resize')` in the IE11 console will produce the same exception. This appears to be a [known issue with IE11](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work). The suggested solution is to use [CustomEvent, with the associated polyfill](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent).

**Comment by johnleider** [comment]
Agreed

**Comment by usb248** [comment]
This fix is no a durable solution.... Please read : https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/initUIEvent

**Comment by arivera12** [comment]
@johnleider Which version of vuetify this bug is fixed?

**Comment by jacekkarczmarczyk** [comment]
1.1-rc1

**Comment by arivera12** [comment]
@jacekkarczmarczyk than you! <3
