### ISSUE TITLE
[Bug Report] Cannot close v-autocomplete dropdown with append-icon arrow

### ISSUE THREAD

**Issue by appurist** [vuetifyjs/vuetify#4033]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Linux x86_64

### Steps to reproduce
- click on the v-autoselect dropdown icon to expand and display the choices
- click on the v-autoselect dropdown icon a second time

### Expected Behavior
The dropdown should close.

### Actual Behavior
The dropdown stays open.

### Reproduction Link
https://codepen.io/anon/pen/gzzYGN

### Other comments
This problem was present in 1.0 as well. I don't think it was ever possible to close the select by clicking on the append-icon.  See also issue #1837

**Comment by KaelWD** [comment]
It worked in 1.0: https://codepen.io/anon/pen/WJJeXr

**Comment by appurist** [comment]
@KaelWD That's strange, this has been a problem for us long before the 1.1 alphas, and I had no trouble reproducing it in 1.0 with our more complex app. Perhaps it's particular to a certain combination of options (e.g. solo etc).  If I get a chance today, I'll check for differences, but either way, I'm just happy to see it being addressed!

**Comment by kaminilsen** [comment]
@KaelWD 's codepen now shows the bug as well
