### ISSUE TITLE
New Material Design guidelines

### ISSUE THREAD

**Issue by DawidCyron** [vuetifyjs/vuetify#4037]
Are you planning to update Vuetify according to new Material Design guidelines, and add new elements from it?

**Comment by KaelWD** [comment]
Eventually, we're working on getting 1.1 polished first though. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
