### ISSUE TITLE
Pagination of Data table in separate component

### ISSUE THREAD

**Issue by KaRkY** [vuetifyjs/vuetify#404]
Would it be posible to extract a Pagination component from Data table in to separate component?

I am talking about this: [Image](http://imgur.com/MFaJk1C)

**Comment by mfferreira** [comment]
@KaRkY That pagination is part of the Data Table component. If you want to use it somewhere else, you'll have to dig in and extract that piece of code yourself.

**Comment by thearabbit** [comment]
+1
