### ISSUE TITLE
[Feature Request] Toolbar RTL support

### ISSUE THREAD

**Issue by sagikarni** [vuetifyjs/vuetify#4043]
### Problem to solve
I would like to easily make the toolbar trl compatible.
This means I need an easy way to the following elements to be presented on the right corner.
Will it be part of the overall RTL effort which was already started ?
    <v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon>
     <v-toolbar-title>Application</v-toolbar-title>

### Proposed solution
Add RTL support for the toolbar (in addition to the form elements)

**Comment by nekosaur** [comment]
Duplicate of #262
