### ISSUE TITLE
[Feature Request] Override the default styles

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetify#4044]
### Problem to solve
Hey Team,
@stephane  @dberube @jaxn  @hrayr-artunyan  @ajsutton 

How can I override the default style ?
Example: 
If I want to override the color of disabled button, I could not override this easily.
Right now, I could not override disabled button background-color and many more things like this.

Could you please guide me the best way with Vuetify?

### Proposed solution
It would be great if we have list of variable and includes this kind of variables to override it.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
