### ISSUE TITLE
[Feature Request] v-select watch receive another parameter with current selected value

### ISSUE THREAD

**Issue by joaovieirabr** [vuetifyjs/vuetify#4049]
### Problem to solve
v-select doesn't consider a case we have here: same text, but different IDs. This happens when two people have the same name.
When the user choose a person for the first time, he (or she) can distinct the correct one looking at additional information. But if he reopens, search maybe locate the wrong one.

### Proposed solution
The watch informed on property ":search-input.sync" should receive another parameter besides the text : the id value of the selected item, so we can manage these situations.

**Comment by jacekkarczmarczyk** [comment]
`search-input` refers to the text field where you're typing something to filter the items list, it's not the selected value. If you need the text (name) and value (id) you need to use `v-model`
Closing for now, if I misunderstood your issue please provide more details and codepen
