### ISSUE TITLE
 vue-cli · Failed to download repo vuetifyjs/webpack-advanced: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by kadbhanem** [vuetifyjs/vuetify#4052]

**Comment by KaelWD** [comment]
THat template is called webpack now. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
