### ISSUE TITLE
[Feature Request] Line-height setting

### ISSUE THREAD

**Issue by LiTiang** [vuetifyjs/vuetify#4053]
### Problem to solve
it work well if i add class ` .subheading ` on ` <p> `

but if i feel the font-size of ` .subheading ` is too small

then i change to use ` .title ` . . . 

and i found the default line-height setting  of  `.title ` is too small !!!

but i can't find any Vuetify API to modify the `.title` line-height

any idea ?

or i miss something else ?

### Proposed solution
provide custom line-height api in typography

**Comment by johnleider** [comment]
Going to need some additional information. Maybe an example showcasing what you are trying to solve would be helpful.

**Comment by KaelWD** [comment]
I feel this will just bloat the CSS for no reason. If you need a different lin-height you can override it yourself.
