### ISSUE TITLE
[Bug Report] v-text-field does not fire an event object for @input

### ISSUE THREAD

**Issue by jlyon87** [vuetifyjs/vuetify#4056]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.11
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
1. Open the codepen
2. Open browser console to observe logs
3. Enter a value in the generic html 5 input and observe the full event object
4. Enter a value in the v-text-field input and observe only the input value.

### Expected Behavior
v-text-field should emit the full event object, just as any other emit should.

### Actual Behavior
v-text-field only emits the input's value.

### Reproduction Link
[https://codepen.io/anon/pen/YLjZLG](https://codepen.io/anon/pen/YLjZLG)

**Comment by KaelWD** [comment]
It's a vue component, it emits a vue event. Use `.native` if you want the native event for some reason.

**Comment by dhershman1** [comment]
Did you actually run his reproduction? I am pretty sure that the vue event gives you far more information than just the input value....

https://vuejs.org/v2/guide/events.html

**Comment by KaelWD** [comment]
> ... directive to listen to **DOM events** and run some ...

https://vuejs.org/v2/guide/components-custom-events.html

**Comment by dhershman1** [comment]
There isn't a custom event in the example. It's running an `@input` and then logging out the value of `$event` is it not? Or am I missing something here...

**Comment by jlyon87** [comment]
I don't understand this statement.

> It's a vue component

v-text-field is not a vue component. it is sitting between me and the input element. The @input event implemented on the v-text-field is only emitting the event.target.value instead of the event.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

> v-text-field is not a vue component

Yes it is

> is only emitting the event.target.value instead of the event

If it emitted the event object then you wouldn't be able to use v-model

**Comment by jlyon87** [comment]
Thanks for the follow up Kael, that actually makes complete sense now.

Appreciate it.
