### ISSUE TITLE
[Feature Request] Emit close event when dialog closes

### ISSUE THREAD

**Issue by tipsy** [vuetifyjs/vuetify#4057]
### Problem to solve
Often when you close a dialog you want do to some cleanup. The docs suggest you do:

```
watch: {
    dialog(val) {
        val || this.close();
    },
},
```
But it seems emitting a `close` event would be simpler.

### Proposed solution
Emit a `close` event, so you can do 

`<v-dialog v-model="dialog" @close="close">...</v-dialog>`

**Comment by jacekkarczmarczyk** [comment]
Listen to `@input` event
`<v-dialog @input="v => v || doSomething()">`
