### ISSUE TITLE
[Feature Request] Movable dialogs

### ISSUE THREAD

**Issue by tipsy** [vuetifyjs/vuetify#4058]
### Problem to solve
Currently you can't move dialogs. This would be a pretty nice feature for more complex UIs. As an example, in google docs every dialog is movable.

### Proposed solution
Add a `movable`/`draggable` config option to dialogs, so they can be moved.

**Comment by david-wg2** [comment]
> @nekosaur this will most likely not be a part of vuetify.

Any particular reason?

**Comment by nekosaur** [comment]
Because draggable DOM elements is a pretty big problem to solve in itself, and there are several existing libraries (including vue-specific ones) that do it better than any implementation that we might come up with.

**Comment by david-wg2** [comment]
At the risk of sounding naive; it's just draggable (not droppable), and it probably shouldn't work on mobile. I made a 30 line implementation that works well enough, but it has some quirks since it's just slapped on top of everything.

**Comment by nekosaur** [comment]
Those are *your* specific requirements. If we implement this functionality in core, soon others will need dropping, or mobile support, or any other number of features.

**Comment by david-wg2** [comment]
Moving a dialog to look behind it is a common use case, but I've never seen or heard about "dropping" a dialog before. They're almost always in fixed position relative to the window, and usually in overlays. Where would you drop them? Any why would you want to support this?

The slippery slope argument doesn't really convince me. There's nothing wrong with adding a feature that doesn't please everyone, you don't have to implement every related feature request.

**Comment by nekosaur** [comment]
I've said my thoughts on the matter. Not sure what the rest of @vuetifyjs/dev-team thinks?

**Comment by johnleider** [comment]
I would be more for showing an example implementation for solving this use-case than I would be creating this functionality. I feel this tech would end up like _masking_. It is a great feature to have, but the need of the community quickly out-grew our intended usage.

**Comment by tipsy** [comment]
@johnleider I'm not familiar with what happened with masking, but I'm having some trouble seeing how having a movable dialog would lead to a snowball effect of movable-dialog-related feature requests (if that's what you meant by the need of the community outgrowing the intended usage).

Sorry if I'm being difficult. I fully respect it if you don't want this this in vuetify, I'm just having some trouble understanding the reasons given.

An example implementation would be nice, but the solution is going to be pretty ugly and math-y, which is why I want it out of my project ... 😇

**Comment by johnleider** [comment]
Essentially, drag and drop, like masking, can be implemented in a very basic way that makes for a better experience. However, their presence also leads to the request of additional functionality, which leads to additional development of something meant to be simple. I believe this should remain in user-land.

**Comment by sandroden** [comment]
@johnleider I personally would greatly appreciate such a feature and I agree the drop functionality would sound weird to me.  You said  "I would be more for showing an example implementation for solving this use-case": do you have such an example to share? Thanks for vuetify, a very nice library...

**Comment by tipsy** [comment]
@sandroden this is the implementation I wrote earlier this year. It's hacky and just tacked on, but it's been working without issue for six months.

```js
(function () { // make vuetify dialogs movable
    const d = {};
    document.addEventListener("mousedown", e => {
        const closestDialog = e.target.closest(".v-dialog.v-dialog--active");
        if (e.button === 0 && closestDialog != null && e.target.classList.contains("v-card__title")) { // element which can be used to move element
            d.el = closestDialog; // element which should be moved
            d.mouseStartX = e.clientX;
            d.mouseStartY = e.clientY;
            d.elStartX = d.el.getBoundingClientRect().left;
            d.elStartY = d.el.getBoundingClientRect().top;
            d.el.style.position = "fixed";
            d.el.style.margin = 0;
            d.oldTransition = d.el.style.transition;
            d.el.style.transition = "none"
        }
    });
    document.addEventListener("mousemove", e => {
        if (d.el === undefined) return;
        d.el.style.left = Math.min(
            Math.max(d.elStartX + e.clientX - d.mouseStartX, 0),
            window.innerWidth - d.el.getBoundingClientRect().width
        ) + "px";
        d.el.style.top = Math.min(
            Math.max(d.elStartY + e.clientY - d.mouseStartY, 0),
            window.innerHeight - d.el.getBoundingClientRect().height
        ) + "px";
    });
    document.addEventListener("mouseup", () => {
        if (d.el === undefined) return;
        d.el.style.transition = d.oldTransition;
        d.el = undefined
    });
    setInterval(() => { // prevent out of bounds
        const dialog = document.querySelector(".v-dialog.v-dialog--active");
        if (dialog === null) return;
        dialog.style.left = Math.min(parseInt(dialog.style.left), window.innerWidth - dialog.getBoundingClientRect().width) + "px";
        dialog.style.top = Math.min(parseInt(dialog.style.top), window.innerHeight - dialog.getBoundingClientRect().height) + "px";
    }, 100);
})();
```

**Comment by Shadam** [comment]
> 
> 
> @sandroden this is the implementation I wrote earlier this year. It's hacky and just tacked on, but it's been working without issue for six months.
> 
> ```js
> (function () { // make vuetify dialogs movable
>     const d = {};
>     document.addEventListener("mousedown", e => {
>         const closestDialog = e.target.closest(".v-dialog.v-dialog--active");
>         if (e.button === 0 && closestDialog != null && e.target.classList.contains("v-card__title")) { // element which can be used to move element
>             d.el = closestDialog; // element which should be moved
>             d.mouseStartX = e.clientX;
>             d.mouseStartY = e.clientY;
>             d.elStartX = d.el.getBoundingClientRect().left;
>             d.elStartY = d.el.getBoundingClientRect().top;
>             d.el.style.position = "fixed";
>             d.el.style.margin = 0;
>             d.oldTransition = d.el.style.transition;
>             d.el.style.transition = "none"
>         }
>     });
>     document.addEventListener("mousemove", e => {
>         if (d.el === undefined) return;
>         d.el.style.left = Math.min(
>             Math.max(d.elStartX + e.clientX - d.mouseStartX, 0),
>             window.innerWidth - d.el.getBoundingClientRect().width
>         ) + "px";
>         d.el.style.top = Math.min(
>             Math.max(d.elStartY + e.clientY - d.mouseStartY, 0),
>             window.innerHeight - d.el.getBoundingClientRect().height
>         ) + "px";
>     });
>     document.addEventListener("mouseup", () => {
>         if (d.el === undefined) return;
>         d.el.style.transition = d.oldTransition;
>         d.el = undefined
>     });
>     setInterval(() => { // prevent out of bounds
>         const dialog = document.querySelector(".v-dialog.v-dialog--active");
>         if (dialog === null) return;
>         dialog.style.left = Math.min(parseInt(dialog.style.left), window.innerWidth - dialog.getBoundingClientRect().width) + "px";
>         dialog.style.top = Math.min(parseInt(dialog.style.top), window.innerHeight - dialog.getBoundingClientRect().height) + "px";
>     }, 100);
> })();
> ```

I just added that : 
``` css
.v-dialog.v-dialog--active .popup-header {
    cursor: grab;
}

    .v-dialog.v-dialog--active .popup-header:active {
        cursor: grabbing;
    }
```

**Comment by cawoodm** [comment]
Every dialog in every piece of SW I've ever seen on every platform is draggable - none are "droppable".
