### ISSUE TITLE
[Bug Report] RadioGroup: When programmatically changing possible values and input value, checked Value is not displayed correctly.

### ISSUE THREAD

**Issue by M3psipax** [vuetifyjs/vuetify#4060]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
When possible values for a radio group are changed programmatically and input value is changed programmatically as well in quick succession, then the radio button corresponding to the input value is not displayed as checked and its value for 'isActive' remains false.

In the codepen, simply press the 'Switch' button after making a selection in the radio group to observe the behaviour.

### Expected Behavior
The RadioButton corresponding to the input value should be displayed as checked.

### Actual Behavior
The RadioButton corresponding to the input value is not displayed as checked.

### Reproduction Link
[https://codepen.io/M3psipax/pen/MGBMOm](https://codepen.io/M3psipax/pen/MGBMOm)

**Comment by nekosaur** [comment]
make the v-model change in a `$nextTick` for it to apply correctly. https://codepen.io/anon/pen/BxOBYq

**Comment by M3psipax** [comment]
Interesting. I've tried nextTick before which didn't work. But looking at the issue again in my project, I found my problem was a bit more complex. The possible values were the result of a computed property while the inputValue was the result of a watcher. Problem was that the Watcher was calculating the new inputValue before the computed property even got recalculated. So putting nextTick inside the watcher didn't help because the computed property essentially waited for the watcher to be done. It seems that Vue generally does Watchers before Computed. So I had to reassign the Watcher to that Computed property instead and use nextTick() to make it work. Both the Watcher and the Computed have the same dependency, so this is fine. Anyway, thanks for pointing me in the right direction. :)

But still, this might be considered a bug, since it's necessary to know about the behaviour and specifically use nextTick() in these kinds of situations. What do you think?

**Comment by johnleider** [comment]
This works as expected on v1.1 using $nextTick.
