### ISSUE TITLE
[Bug Report] Slider bringing up keyboard and cursor after tap on mobile

### ISSUE THREAD

**Issue by Helmi** [vuetifyjs/vuetify#4062]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.4
**Vue:** 2.5.16
**Browsers:** Safari, Google Chrome
**OS:** Android, iOS

### Steps to reproduce
Tap on the slider from a mobile device (happens on Android and iOS)

### Expected Behavior
Slider moves to the position of the tap.

### Actual Behavior
Slider moves but also the keyboard comes up and a cursor shows up on the left side of the slider (likely due to the input element underneath)

### Reproduction Link
[https://codepen.io/Helmi74/pen/JvaKyL](https://codepen.io/Helmi74/pen/JvaKyL)

**Comment by KaelWD** [comment]
Fixed already: 641426c2b24374d5f35d45585327acd2032070d7
