### ISSUE TITLE
[Bug Report] solo-inverted text-feld

### ISSUE THREAD

**Issue by jamescoffman23** [vuetifyjs/vuetify#4064]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.4
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
add a <v-text-field> control with the solo-inverted attribute. Type something in the field.

### Expected Behavior
typed text should visible

### Actual Behavior
text color is too dark to see clearly.

### Reproduction Link
[https://codepen.io/jamescoffman/pen/OZobyQ](https://codepen.io/jamescoffman/pen/OZobyQ)

**Comment by johnleider** [comment]
Fixed in 33064ee76ce5a5dc1d5ffaf178a9cc4f447796c6
