### ISSUE TITLE
[Bug Report] Checkbox component inside of scrollable dialog error IE 11

### ISSUE THREAD

**Issue by hyezy** [vuetifyjs/vuetify#4066]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
I am on the IE 11, when I click "open dialog" then there's extra scrolling bar around the dialog card.

### Expected Behavior
I expected scrolling is working as Chrome.

### Actual Behavior
there's additional y and x scrolls 

### Reproduction Link
[https://codepen.io/ericajung/pen/WJgjqq?&editors=101](https://codepen.io/ericajung/pen/WJgjqq?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
Your codepen uses 1.0.17, but it happens also in 1.1.0-alpha.4, even in chrome
https://codepen.io/anon/pen/WJgOzr
