### ISSUE TITLE
[Bug Report] Large top margin on inputs

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#4070]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.4
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Checkboxes, radiobuttons and toggles have a large top margin. Textfields have also a some additional margin above the floating label. They do not even match with horizontal subheaders in the example in the documentation. Is it by design or is it a bug?

### Expected Behavior
Margin as it was in vuetify 1.0.

### Actual Behavior
Unnecessary large top margin.

### Reproduction Link
[https://codepen.io/SeregPie/pen/jxvjBE](https://codepen.io/SeregPie/pen/jxvjBE)

**Comment by johnleider** [comment]
Was done last night in https://github.com/vuetifyjs/vuetify/commit/f85b87941f9b32a2c5cb367d79eba011f07ecd8f
