### ISSUE TITLE
[Feature Request] Add outlined text fields as described in md-specs

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#4073]
It would be great to have outlined text fields as the Material Design specs describing: https://material.io/design/components/text-fields.html#outlined-text-field

The label move inside the outline when the field is focused.
On the material web components page is a live demo: https://material-components.github.io/material-components-web-catalog/#/component/text-field

**Comment by johnleider** [comment]
Thank you for the Feature Request. The MD Spec for this was literally updated less than a week ago, right smack in the middle of our form update. No need to request an update, it's already going to happen.

**Comment by BennyAlex** [comment]
Ok, there are some more missing components or alternative styles, are you planning to add them?
1. Backdrop: https://material.io/design/components/backdrop.html
2. Cut out fab button: https://material.io/design/assets/1xkb-3HQEAsb0IA292GLCziMMh6QE1YIX/anatomy-fab-cut.png
3. Bottom Navigation on large screens where the text is displayed on the side of the icon: https://material.io/design/assets/0B6xUSjjSulxcLU91YlhMLWJEazA/bottomnav-whentouse-do-5.png
4: New Navigation Drawer Item style: https://material.io/design/assets/1MylKkyLxQ83fM2L7y2toQ8HG8tdECh_r/lateral-nav-drawer.png

**Comment by KaelWD** [comment]
That'll all be for v2.x probably

I already have a (bad) implementation of the cut-out fab using svg: https://codepen.io/anon/pen/MGQJpL

**Comment by BennyAlex** [comment]
The new navigation drawer item style is really nice.
Maybe you can add it in 1.1 but dont use it as default? Activate it with alternative property?

**Comment by johnleider** [comment]
Stop trying to scope creep us Benny! v1.1 is about to go into a freeze.
