### ISSUE TITLE
[Feature Request] If component is in shadow-root then add styles in shadow-root

### ISSUE THREAD

**Issue by akki-jat** [vuetifyjs/vuetify#4075]
### Problem to solve
Overriding of vuetify component's css

### Proposed solution
Add styles to shadow-root if vuetify component is in shadow-root

### Detailed Explanation
I am using vuetify's v-select component only within my project. And I am building custom element with shadowDom and when I am including v-select in my custom element's shadow root element then it adds all style in <head> tag so it will be excluded from shadow-root element where I am using v-select. So I need styles in shadow-root element.

**Comment by AlexSHoffman** [comment]
@akki-jat aren't you supposed to use `!important` if you want to override external library's styles?

**Comment by akki-jat** [comment]
Hi @KaelWD, let me tell you what i s happening.
I am using v-select as separate component in custom element and that custom element is in shadow dom.
As you in shadowDom outside css are not applied.
And as your code all css required for v-select is added in <head> tag.

Ex: 

![error_1](https://user-images.githubusercontent.com/26685162/40177463-b6528068-59ac-11e8-9729-ed781804eee0.png)

And here is the my custom element: 

![error_2](https://user-images.githubusercontent.com/26685162/40177490-c3039770-59ac-11e8-874c-1a161aff617c.png)

So, css is affecting the v_select in shadow-root element.

**Comment by KaelWD** [comment]
I don't think that is something we can support at this time, you'll have to figure out a custom build from our source.

**Comment by Nayir** [comment]
Hi @akki-jat , did you find any solution ?

Mine was to wrap the shadow-root into a wrapper like this `<v-app></v-app>`, but it's a little "dirty". Moreover, i can't reach the css in the shadow-root, I need to add additional css in the wrapper.
