### ISSUE TITLE
[Feature Request] Programmatically set focus of text-field

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#4077]
### Problem to solve
Setting the focus to a given text-field

### Proposed solution
Offer a reactive property that allows to set a target text-field as focus.

**Comment by johnleider** [comment]
You can do this by using $refs and calling `.focus()`.

`<v-text-field ref="field" />`

Can now be accessed by doing:

`this.$refs.field.focus()`

**Comment by sim-jo** [comment]
$ref...focus() does not seem to work in version 1.1.6
Any alternative?

**Comment by johnleider** [comment]
Please do not comment on old closed issues. If you are having a problem, please submit a new ticket, thank you!

**Comment by pudjamansyurin** [comment]
not work for me too... any solution or link?
