### ISSUE TITLE
[Bug Report] VSwitch doesn't update on mapped computed properties even though v-model updates

### ISSUE THREAD

**Issue by someone1** [vuetifyjs/vuetify#4079]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.170
**OS:** Windows 10

### Steps to reproduce
Click on the switch toggle once, it will NOT update. Then click on the date menu below, you will see the toggle update!

### Expected Behavior
When the toggle is clicked, it should visually update.

### Actual Behavior
When the toggle is clicked, it does not visually update but the v-model attached is updated.

### Reproduction Link
[https://codepen.io/s0me0ne1/pen/YLJeZG?&editors=101](https://codepen.io/s0me0ne1/pen/YLJeZG?&editors=101)

### Other comments
This doesn't seem to be an issue in 1.1.0-alpha.5 but I wasn't sure if the fix was intentional or just a byproduct of an internal rewrite. Either way, I wanted to bring it to the maintainers attention to make sure the fix is purposeful and if possible a test be put in place to prevent a regression.

**Comment by johnleider** [comment]
So there are a few things going on here. You cannot use a computed property as a v-model without a getter/setter. So while you are binding the model, you are not actually updating the prop. You would normally do this with `.sync`, however, because you are passing in a computed property as the prop, you would need to handle this update differently.

Example impl https://codepen.io/johnjleider/pen/qYJKNE?editors=1011

**Comment by someone1** [comment]
Thanks for the clarification, I thought it might be something like that but for text fields it was updating the computed property fine, and in the upcoming 1.1 release it seems to update the computed property without getters and setters on the vswitch too.

Is it not supposed to work without getters and setters as it does in 1.1 and for other field types?

**Comment by johnleider** [comment]
That doesn't make sense because computed properties have no settable state, that's not how they work.

**Comment by someone1** [comment]
Gotcha, so the fact that it is working on properties of computed objects doesn't make it defined behavior. I'll have to go through my code and update it so that the components watch and cloneDeep props vs rely on computed properties.

My guess is that since I'm binding to properties of a computed object, I don't run into the getters/setters issue - though regardless I shouldn't be doing it.

Thanks!
