### ISSUE TITLE
Full Screen v-dialog must only occur on xs and sm width devices

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#408]
Due to limited space, full-screen dialogs may be more appropriate for mobile devices than dialogs used on devices with larger screens.

as it says it must only occur in fullscreen

**Comment by mfferreira** [comment]
The component has the option to toggle fullscreen. It's up to the developer to set the appropriate dialog layout based on app requirements.

**Comment by ralphchristianeclipse** [comment]
@mfferreira yeap the component has fullscreen toggle but that would make no sense for the css breakpoints the developer must use a media query javascript for the sake of detecting the device is in mobile width or not

**Comment by johnleider** [comment]
I agree with @mfferreira on this one. The developer can choose to do whatever they want.

**Comment by ralphchristianeclipse** [comment]
@johnleider any idea that i can toggle the fullscreen on mobile sm and xs breakpoints?

**Comment by johnleider** [comment]
I'd make a computed property ```isMobile``` and have it return ```window.innerWidth < whateverpx```

**Comment by ralphchristianeclipse** [comment]
@johnleider window.innerWidth is not reactive

**Comment by johnleider** [comment]
If you want it to be reactive then bind an event listener and update accordingly.

**Comment by ralphchristianeclipse** [comment]
@johnleider can i have a simple proposal aboutthis? will you add a prop mobileFullScreen?
for the sake of this mobile thing

**Comment by johnleider** [comment]
I can add something similar to sidebar, mobile-break-point.

**Comment by ralphchristianeclipse** [comment]
@johnleider thanks
