### ISSUE TITLE
[Feature Request] Add Text Field Prop: "outline"

### ISSUE THREAD

**Issue by ashrafhadden** [vuetifyjs/vuetify#4080]
### Problem to solve
Add a new `outline` property to the [`v-text-field`](https://vuetifyjs.com/en/components/text-fields) UI component to keep up with the latest Material Design Guidelines. Because it's reeealy pretty :heart_eyes: :pray:

### Proposed solution
_(Links to the Github source code are included)_

- [Material Design Documentation](https://material.io/design/components/text-fields.html#outlined-text-field)
- [MDC Web Demo](https://material-components.github.io/material-components-web-catalog/#/component/text-field)
- [MDC Web Demo | Vue Adapter](https://stasson.github.io/vue-mdc-adapter/#/component/textfield)

**Comment by jacekkarczmarczyk** [comment]
It's already done in 1.1-alpha
https://codepen.io/anon/pen/RyeYEW

**Comment by KaelWD** [comment]
Duplicate of #4073

**Comment by dawidmierzwa95** [comment]
That's not the same. Original outlined type has floating label on top border. In vuetify label floating under top border.

**Comment by DRoet** [comment]
@dawidmierzwa95 the new outline styles might make it in right here <https://github.com/vuetifyjs/vuetify/pull/7157>
