### ISSUE TITLE
[Feature Request] VSelect should allow displaying selected items in the order they were selected by users

### ISSUE THREAD

**Issue by xlm** [vuetifyjs/vuetify#4082]
### Problem to solve
We use `VSelect` to allow users to customise/select the headers to display in `VDataTable`, thus ordering is significant. `VSelect` preserves the order in which users select values (per the `v-model`) but displays them always in order per `:items` which makes it inconsistent with UI components that rely on that ordering (e.g. `VDataTable`).

https://codepen.io/anon/pen/yjRQaL
Select values in random order, and compare how it's displayed in the `VSelect` (always ordered per `:items` order) vs. the span below (displayed in the order the user selected the item).

### Proposed solution
~~It's straightforward to use the scoped `selection` slot, however~~ it would be more convenient and useful to the component if there was a boolean property to specify this, ~~then we wouldn't need to (re)implement the default slot with a very minor tweak~~ e.g.:
```
<v-select 
  :label="label"
  :items="items"
  preserve-selection-order
/>
```

**Comment by xlm** [comment]
Actually you **can't** use the scoped `selection` slot as a work around/roll your own implementation. The scoped slot property is the individual selected item. Ordering is still alphabetical/determined by the component.

Alternative solution is to provide scoped slot with the property for all the selected items.

**Comment by KaelWD** [comment]
Displayed order is the same as `:items`

**Comment by xlm** [comment]
Thanks @KaelWD I've updated the title/comments to reflect this. I think it's useful if we can preserve ordering per selection.
