### ISSUE TITLE
[Bug Report] vBottomSheet without activator only opens once

### ISSUE THREAD

**Issue by tommybravo** [vuetifyjs/vuetify#4084]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 57.0.2987.98
**OS:** Windows 7

### Steps to reproduce
1. Click on the button component to open the bottom-sheet
2. Click on the overlay to close the bottom-sheet
3. Click again on the button to re-open the bottom-sheet

Nothing happens.

### Expected Behavior
The variable bound to "value" prop should return to "false" upon clicking the overlay, and the button should be able to re-open the bottom-sheet by setting it to "true" again.

### Actual Behavior
The bottom-sheet remains closed, although the bound "value" remains true.

### Reproduction Link
[https://codepen.io/anon/pen/BxqEqL](https://codepen.io/anon/pen/BxqEqL)

**Comment by KaelWD** [comment]
Vue can only watch **changes**, you have to either use `v-model` or set value to false first.

**Comment by tommybravo** [comment]
I'm sorry, but I don't understand this comment. If you check the codepen, I did set an initial value to the variable controlling the visibility of the vBottomSheet, so Vue actually watches its changes. This does happen, when its value is set to "true" that effectively opens the vBottomSheet. The component should set the variable back to "false" when it is closed. This does not happen.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

**Comment by nirvana72** [comment]
try this
<v-bottom-sheet lazy v-model="commentsBox.visible">
.....
// btn event
showComments(){
      const _this = this
      setTimeout(() => {
        _this.commentsBox.visible = true
      }, 100);
    },
