### ISSUE TITLE
[Bug Report] textarea does not preserve line breaks

### ISSUE THREAD

**Issue by wsw70** [vuetifyjs/vuetify#4085]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Create a multi-line textarea via `<v-text-field multi-line ... ></v-text-field>` and input several lines with linebreaks.

### Expected Behavior
Line breaks should be available in the bound variable

### Actual Behavior
The bound variable is a string where line returns are replaced by a space.

### Reproduction Link
[https://codepen.io/WoJWoJ/pen/jxeyyO](https://codepen.io/WoJWoJ/pen/jxeyyO)

### Other comments
The line returns could be anything (`\n`, `<br>`, ...) which then could be parsed and stored to retain the formatting

**Comment by jacekkarczmarczyk** [comment]
That's how html works
https://codepen.io/anon/pen/JvePRP

**Comment by wsw70** [comment]
@jacekkarczmarczyk Thank you. I was misled by the fact that the string representation of the content does not (visually) show any new line separators.

I tried to convert the string to JSON and back (to show again in a `textarea`) and it works great - a very basic Codepen showing the transformations is here: https://codepen.io/WoJWoJ/pen/MGzWra
