### ISSUE TITLE
[Bug Report] v-select divider not adding without {divider:true} in list

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#4089]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 66.0.3359.139
**OS:** Mac OS 10.13.4

### Steps to reproduce
remove the  { divider: true } in list data and check the v-select item.
With scoped-slot able add divider

### Expected Behavior
In template itself able to add <v-divider>

### Actual Behavior
Done with css with adding custom-class

### Reproduction Link
[https://codepen.io/ksankumar/pen/pVQbxj](https://codepen.io/ksankumar/pen/pVQbxj)

**Comment by ksankumar** [comment]
@KaelWD  If i add divider in data list, v-select displays item with divider. If i remove divider from data list, v-select not showing divider
` people: [
        { name: "Sandra Adams", group: "Group 1", avatar: srcs[1] },
        { divider: true },
        { name: "Ali Connors", group: "Group 1", avatar: srcs[2] },
        { divider: true },
        { name: "Trevor Hansen", group: "Group 1", avatar: srcs[3] },
        { divider: true },
        { name: "Tucker Smith", group: "Group 1", avatar: srcs[2] }
]`
Here how can we add divider in v-select template ?

**Comment by KaelWD** [comment]
> Here how can we add divider in v-select template

Put a `<v-divider>` in the slot template.
