### ISSUE TITLE
[Bug Report] v-select change event doesn't propagate to form

### ISSUE THREAD

**Issue by trapperkeeper** [vuetifyjs/vuetify#4090]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Mac OS 10.13.4

### Steps to reproduce
In the linked codepen, modify the text field and then move to another ui widget, a "change" event will be fired. Though the text-field does not handle this event, it is handled by the parent "form" element (which is illustrated by a console output). Now modify the v-select labelled "Select 1" and check the console output. The select does not handle the event but it does not propagate to from. "Select 2" is there just to show that the change event is fired (works when caught directly by the v-select itself).

### Expected Behavior
I would expect the change events of v-text-field and v-select to propagate in the same manner. It would be good if they both bubbled to form and could be handled there (to detect any form change).

### Actual Behavior
As mentioned in "Steps to Reproduce", v-text-field events bubble to the parent form, but v-select does not. 

### Reproduction Link
[https://codepen.io/detwiler/pen/WJYzJq](https://codepen.io/detwiler/pen/WJYzJq)

**Comment by johnleider** [comment]
It actually goes a bit deeper than this. Most form controls don't behave as their native counterpart in relation to @change events at the form level.

**Comment by KaelWD** [comment]
I don't think this is a bug. Vue events are not native and don't bubble, and v-select is not a native input so shouldn't be expected to emit native events.

**Comment by KaelWD** [comment]
This isn't something that can realistically be implemented with support for v-select's various options. If you want to watch the entire form you can bind each input to properties on an object (which you should be doing anyway) and use a [deep watch](https://vuejs.org/v2/api/#watch)

**Comment by trapperkeeper** [comment]
OK, thanks, though that is a bit disappointing. I do have properties bound to inputs. But the objects are potentially large and deeply nested. Deep watch only tells me that the object has changed, not where. Worse, the "old val" isn't really the old value when deep watching objects. So I have to pull tricks like cloning objects before I modify them (so I'll still have the old value) and writing custom code to iterate over a pair of objects to find where the changes occurred. It would be much easier to simply be notified when a v-select value has changed.

**Comment by KaelWD** [comment]
Some more ideas from an issue on vue's board: 

 - [Clone the object first in a computed property](https://github.com/vuejs/vue/issues/2164#issuecomment-432872718), wouldn't work too well for deep objects though
 - [Iterate over the object and call `this.$watch` on each property](https://github.com/vuejs/vue/issues/2164#issuecomment-406223470). This way you can work out the path and supply it to the callback

Vue doesn't have anything to bubble custom events, and spoofing native events would cause problems as there isn't really a proper `event.target` you can get a value from.

**Comment by trapperkeeper** [comment]
Thanks KaelWD, I appreciate the ideas. And I understand that it isn't a practical extension right now. Thank you for considering it.
