### ISSUE TITLE
[Ask] how to keep the current page when update the data in datatables

### ISSUE THREAD

**Issue by thanhtungka91** [vuetifyjs/vuetify#4092]
how to keep the current page when the items in data change?
of example i want to push new item to items.

**Comment by bdeo** [comment]
This issue board is exclusively for bugs and feature requests. Please ask the community for help questions and other related discussion at https://community.vuetifyjs.com.

**Comment by thanhtungka91** [comment]
This is bug after confirm from community support channel. 
it will be fixed next version
