### ISSUE TITLE
[Bug Report] Fullscreen dialog along with scrollable is broken

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#4093]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 7

### Steps to reproduce
Using a v-dialog with scrollable & fullscreen properties set to true

### Expected Behavior
the inner content is scrollable if it is to long and the card-actions stay always at the bottom

### Actual Behavior
Layout is messed up, the actions aren't at the bottom of the dialog

### Reproduction Link
[https://codepen.io/Benny98/pen/odJNwW](https://codepen.io/Benny98/pen/odJNwW)

**Comment by BennyAlex** [comment]
Okay, when I apply the color classes and remove the v-dividers between v-card-title and v-card-text and v-card-actions the style is correct

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/YOjZpG

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
