### ISSUE TITLE
[Bug Report] Switch and checkbox components will not align right or center

### ISSUE THREAD

**Issue by kreierson** [vuetifyjs/vuetify#4096]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.5
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Create a flex component and apply a class of text-xs-right. Inside of that flex component put a checkbox or switch component.

### Expected Behavior
Component should be aligned to the right of the container

### Actual Behavior
Component will only be aligned to the left

### Reproduction Link
[https://codepen.io/kreierson/pen/erbJoV](https://codepen.io/kreierson/pen/erbJoV)

### Other comments
My attached codepen you can see that the button will align right properly, but the switch won't. Either will a checkbox.

**Comment by KaelWD** [comment]
Buttons are inline elements, inputs aren't. Either give it the `d-inline-flex` class or align it with flexbox instead.
