### ISSUE TITLE
[Help] How to show two router-views in both v-tab and navigation-drawer

### ISSUE THREAD

**Issue by abrhambas01** [vuetifyjs/vuetify#4097]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.13
**Browsers:** Chrome 67.0.3396.48
**OS:** Windows 7

### Steps to reproduce
1. Create a nav-drawer that has router-links in it.
2. In one of the links create a v-tab component that connects to another router-view.

### Expected Behavior
In one of the links in the navigation-drawer, I have a link that connects to router view in one of it I have a tab that connects to another router-view. Can you please help me ? 

### Actual Behavior
The router-view in the tab doesn't show up 

### Reproduction Link
[https://codepen.io/aabbrrm234/pen/deQjEe](https://codepen.io/aabbrrm234/pen/deQjEe)

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
