### ISSUE TITLE
v0.7.10 <v-text-input> is not updated if model value changed

### ISSUE THREAD

**Issue by rusenask** [vuetifyjs/vuetify#41]
After updating vuetify version to v0.7.10 I have noticed that if v-model is updated in the background it doesn't affect values that are shown in the  <v-text-input> component.
```
<v-text-input label="input name" id="new-input-name"  v-model="input.name"></v-text-input>
```

for example if user inputs "xxx" and in the background I process that value and then update `this.input.name = ''` - input component is unchanged and still shows "xxx". Not sure if it's desired behaviour.

**Comment by johnleider** [comment]
Fixed with 704f5c33265e5ea1e990f417bbccc818cdea0f84.
