### ISSUE TITLE
[Bug Report] Buttons may require clicking twice in Firefox

### ISSUE THREAD

**Issue by taekni** [vuetifyjs/vuetify#4100]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Mac OS 10.13

### Steps to reproduce
Using Firefox / Firefox Developer Edition, click on either of the red buttons a single time - the button ripples but no action happens. Click a second time and the links then open.

### Expected Behavior
Buttons respond to being clicked once.

### Actual Behavior
Buttons using the 'href' property require a second click to respond when using Firefox.

### Reproduction Link
[https://codepen.io/anon/pen/zjerzw](https://codepen.io/anon/pen/zjerzw)

### Other comments
Codepen extended from site docs. Both green buttons, using @click rather than href, work fine in all cases. As do similar components in lists, menus etc.

All work fine in Chrome / Safari.

Behaviour also observed on next.vuetifyjs homepage 'Get Started' button.

**Comment by KaelWD** [comment]
Fixed by 2d1e00e048ef335be32c1872f4c3568d16ea8152
