### ISSUE TITLE
[Feature Request] DataTable should have a prop for changing the icon of the "Rows per page" select

### ISSUE THREAD

**Issue by walter-schwarz** [vuetifyjs/vuetify#4101]
### Problem to solve
There is currently no way to set the icon of the rows per page select. Because this select is generated by Vuetify. If I am not using the Google’s Material Icons this creates a big problem. see: https://codepen.io/wschwarz/pen/odmLyB?&editors=101

### Proposed solution
Add a new prop for setting the icon of the "Rows per page" select, like it works now with the "sort-icon" prop, and pass it to the v-select component when it is being created.

**Comment by KaelWD** [comment]
See #3591

**Comment by walter-schwarz** [comment]
Thank you, that helps solve my problem.
But on the other hand, considering the v-select component does provide a prop for setting a custom icon, it also makes sense to be able to do that for a data table.
So I still think this would be a useful improvement.
