### ISSUE TITLE
[Bug Report] v-autocomplete not using selection slot when !isMulti

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#4104]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.15
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.12.6

### Steps to reproduce
Select an item

### Expected Behavior
Selection should display based on provided selection slot template.

### Actual Behavior
Displays item-text instead.

### Reproduction Link
[https://codepen.io/kdholt34/pen/gzdWoz?editors=1010](https://codepen.io/kdholt34/pen/gzdWoz?editors=1010)

### Other comments
Specific to !isMulti v-autocomplete. Codepen shows !isMulti v-select works as expected and so does isMulti v-autocomplete.

Oh (should maybe be opened in a separate issue?), but codepen also shows that placeholder doesn't display for regular v-select (shows fine for v-autocompletes).

**Comment by KaelWD** [comment]
Placeholder is a known issue, see #4098. Not sure about the slot, I'll have to check if it's been fixed yet.

**Comment by kdholt34** [comment]
I did mention the slot issue on discord last week, but hadn't seen any commits or pulls for it.  So thought I'd just open an issue to make sure it wasn't forgotten. :)
