### ISSUE TITLE
[Bug Report] New Material Icons are rendering incorrectly

### ISSUE THREAD

**Issue by mizzao** [vuetifyjs/vuetify#4107]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
The old material icons link (e.g. [on this Vuetify page](https://vuetifyjs.com/en/components/icons))  to http://material.io/icons/ now redirect to https://material.io/tools/icons/. The icons on this page have different names, and even though they are defined in Vuetify, render incorrectly. (I can't even find the old icon names anymore). See the two types of buttons as an example.

### Expected Behavior
Buttons render correctly.

### Actual Behavior
Icon button has icon floating off to the left. Normal button becomes much wider than necessary.

### Reproduction Link
[https://codepen.io/mizzao/pen/gzEwgj](https://codepen.io/mizzao/pen/gzEwgj)

### Other comments
We should either change the doc links to point to the old icon names, or fix these icons to work properly and mark the old icon names as deprecated/outdated etc.

**Comment by KaelWD** [comment]
google/material-design-icons#786

The codepen is using the correct font according to that page, I think this one's on Google.

**Comment by mizzao** [comment]
FYI here is a link to the old icon names that I found: https://materializecss.com/icons.html

**Comment by mizzao** [comment]
Hey guys, I don't understand how this is fixed, it's still super misleading on the Vuetify Icons doc page.
