### ISSUE TITLE
[Bug Report] [v1.1-alpha.6] v-test-field with readonly attrs looks like disabled

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#4108]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
see links

### Expected Behavior
The readonly field should  not look like a disabled
v1 link:  https://codepen.io/Buzzzzer/pen/zjbdvv

### Actual Behavior
The readonly field looks like disabled
v1.1-alpha link:  https://codepen.io/Buzzzzer/pen/mLoMJp

### Reproduction Link
[https://codepen.io/Buzzzzer/pen/mLoMJp](https://codepen.io/Buzzzzer/pen/mLoMJp)

**Comment by KaelWD** [comment]
We have `Readonly looks same as disabled (except the color of the icon)` on the google doc that's marked as done, but apparently not with my suggestion.

**Comment by kdholt34** [comment]
This behavior is particularly unfortunate for datepicker fields.

**Comment by buzzzzer** [comment]
v-select with readonly attr same as disabled too, but v-autocomplete  is ok.

updated template https://codepen.io/Buzzzzer/pen/mLoMJp
