### ISSUE TITLE
[Bug Report] close group without expand transition (Expansion Lists)

### ISSUE THREAD

**Issue by romangit** [vuetifyjs/vuetify#4109]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
Quick clicks will be most effective.
1. Click "Dining" for close
2. Click "Dining" for open
3. Click to "Breakfast & brunch"
4. Click "Dining" for close
5. Repeat

### Expected Behavior
Transition

### Actual Behavior
Close group without expand transition.

### Reproduction Link
[https://codepen.io/romanany/pen/NMJLXJ](https://codepen.io/romanany/pen/NMJLXJ)

**Comment by nekosaur** [comment]
Most likely related to #3161

**Comment by KaelWD** [comment]
Resolved by a967ef7e7a765ab96c6d7d936fe01f337a541243, cb605ac9d73f8f585e0a23591b4d54241950101e or 5d8b0dfc798a532c0f5e366bf681a50403b225c5
