### ISSUE TITLE
webpack-ssr document is not defined

### ISSUE THREAD

**Issue by WMTAndroidJaymin** [vuetifyjs/vuetify#411]
I have used this template and using `<v-dialog>` component but is gives me error. I have used the latest version 0.11.0

    error during render : /
      ReferenceError: document is not defined
         at render (__vue_ssr_bundle__:13272:7)
         at createFunctionalComponent (__vue_ssr_bundle__:3145:35)
         at createComponent (__vue_ssr_bundle__:3099:12)
         at _createElement (__vue_ssr_bundle__:3399:15)
         at createElement (__vue_ssr_bundle__:3353:10)
         at vm.$createElement (__vue_ssr_bundle__:3644:54)
         at Proxy.render (__vue_ssr_bundle__:11718:16)
         at VueComponent.Vue._render (__vue_ssr_bundle__:3677:22)
         at renderComponent (/opt/lampp/htdocs/vue2demo/node_modules/vue-server-renderer/build.js:6698:25)
        at RenderContext.renderNode (/opt/lampp/htdocs/vue2demo/node_modules/vue-server-renderer/build.js:6681:7)

Here is my code:

	 <template>
	    <v-app id="sidebar-example-2" class="elevation-1" top-toolbar left-fixed-sidebar sidebar-under-toolbar>
		<v-dialog v-model="d3" fullscreen transition="v-dialog-bottom-transition">
		    <v-btn primary dark slot="activator">Open Dialog</v-btn>
		    <v-card-row>
		        <v-toolbar>
		            <v-btn icon="icon" @click.native="d3 = false">
		                <v-icon>close</v-icon>
		            </v-btn>
		            <v-toolbar-title>Settings</v-toolbar-title>
		            <v-btn class="white--text" flat="flat" @click.native="d3 = false">Save</v-btn>
		        </v-toolbar>
		    </v-card-row>

		    <v-list three-line subheader>
		        <v-subheader>User Controls</v-subheader>
		        <v-list-item>
		            <v-list-tile avatar>
		                <v-list-tile-content>
		                    <v-list-tile-title>Content filtering</v-list-tile-title>
		                    <v-list-tile-sub-title>
		                        Set the content filtering level to restrict appts that can be downloaded
		                    </v-list-tile-sub-title>
		                </v-list-tile-content>
		            </v-list-tile>
		        </v-list-item>
		        <v-list-item>
		            <v-list-tile avatar>
		                <v-list-tile-content>
		                    <v-list-tile-title>Password</v-list-tile-title>
		                    <v-list-tile-sub-title>Require password for purchase or use password to restrict purchase
		                    </v-list-tile-sub-title>
		                </v-list-tile-content>
		            </v-list-tile>
		        </v-list-item>
		    </v-list>
		</v-dialog>
	    </v-app>
	</template>
	<script>
	    export default {
		data () {
		    return {
		        d3: false,
		    }
		}
	    }
	</script>

	<style lang="stylus">
	    @import '../node_modules/vuetify/src/stylus/main';
	    @import './css/main.css';
	</style>

am I missing something because this runs perfect in other `vuetifyjs/webpack` template.

**Comment by johnleider** [comment]
This is due to something I added into overlay. Will fix asap.
