### ISSUE TITLE
[Feature Request] Tooltip can open when focus by default

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4112]
### Problem to solve
- Better accessibility;
- Display tooltips when navigate using tab;
- Follow specs;

### Proposed solution
- Add focus event on https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VTooltip/VTooltip.js#L159
- Add a `open-on-focus` property with `true` by default

**Comment by KyleMit** [comment]
@peluprvi - link is broken - here's an updated one

https://github.com/vuetifyjs/vuetify/blob/v1.3.9/packages/vuetify/src/components/VTooltip/VTooltip.js#L173-L180

**Comment by blalan05** [comment]
This is added in the 2.0 alpha.

**Comment by KaelWD** [comment]
Specifically #6111
