### ISSUE TITLE
[Bug Report] Tooltip wraps on white space

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4113]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
- Open the codepen
- Mouse overon right menu

### Expected Behavior
No white space wrap, texet in a single line

### Actual Behavior
Text in two lines because it wraps on whitespace

### Reproduction Link
[https://codepen.io/anon/pen/ELJxLz?&editors=101](https://codepen.io/anon/pen/ELJxLz?&editors=101)

### Other comments
Right space issue reported on https://github.com/vuetifyjs/vuetify/issues/2489

**Comment by KaelWD** [comment]
This is because the position is calculated incorrectly, causing it to be slightly off-screen.

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 1.5.5 https://codepen.io/anon/pen/QoMwma?&editors=101
