### ISSUE TITLE
[Bug Report] v-dialog display problems

### ISSUE THREAD

**Issue by lebesnec** [vuetifyjs/vuetify#4116]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
open the reproduction link :)

### Expected Behavior
- dialog should have a background color
- dialog overlay should be behind the dialog content

### Actual Behavior
- dialog has no background color (in the given example we can see the red background through the dialog content)
- dialog overlay is covering the dialog content, dimming it

### Reproduction Link
[https://codepen.io/anon/pen/YLMqPj](https://codepen.io/anon/pen/YLMqPj)

**Comment by AlexSHoffman** [comment]
@lebesnec you just doing it wrong. You are applying "green" class only to the `v-layout` which is inside a container with padding. Try this: https://codepen.io/anon/pen/JvVaKY

**Comment by KaelWD** [comment]
Dialogs intentionally don't have a background, it's expected that you will put a card or something there.
