### ISSUE TITLE
Bug Report: Vuetify prevents A-frame from allowing opening in headset

### ISSUE THREAD

**Issue by aoighost** [vuetifyjs/vuetify#4117]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Run and open the immersive tab.

### Expected Behavior
 You should be able to open it in webvr, however the button to do so isn't there.

### Actual Behavior
No webvr button to open in VR.

### Reproduction Link
[https://github.com/aoighost/vuetify-aframe-issue](https://github.com/aoighost/vuetify-aframe-issue)

### Other comments
VR confirmed works with Nuxt and Vue with the same VR code, so the problem is down to vuetify

**Comment by johnleider** [comment]
This is happening due to the declared height of the `<a-frame>` being 100vh. This forces it to take up the padded space of `v-content` for the `v-toolbar` and `v-footer`. If the correct value is provided, `calc(100vh - 64px - 32px)`, it appears as expected.

**Comment by aoighost** [comment]
Yep, it works now. Thanks for the 2nd set of eyes on, sorry I assumed bug.
