### ISSUE TITLE
[Bug Report] Time Picker close-content-on-click=true functions improperly

### ISSUE THREAD

**Issue by bdeo** [vuetifyjs/vuetify#4119]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
* Open Picker
* Select any hour

### Expected Behavior
Picker remains open until minutes selected

### Actual Behavior
Picker closes without minute selected resulting in an empty input.

### Reproduction Link
[https://codepen.io/anon/pen/ZoZpoY?&editors=101](https://codepen.io/anon/pen/ZoZpoY?&editors=101)

### Other comments
This props seems to not be necessary anymore. When set to false, this functions as i'd expect with true, and when set to true, it feels to be a bug.

**Comment by jacekkarczmarczyk** [comment]
`close-on-content-click' is not picker's prop, it belongs to `v-menu`.
When it's set to `false` menu closes because of `@change` handler in the picker.
I don't see any bug here - close-on-content-click works as expected (closes menu on content click)

**Comment by bdeo** [comment]
Ah you're right, however I think that if this is a supported use case, this is still pretty confusing.

**Comment by jacekkarczmarczyk** [comment]
You may open issue in docs repo, i'm not sure what to do there though
