### ISSUE TITLE
[Bug Report] offset-[size] attribute doesn't work when layout is in column mode

### ISSUE THREAD

**Issue by nikhilem** [vuetifyjs/vuetify#4121]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Linux x86_64

### Steps to reproduce
1. Create a `v-layout` with column prop
2. Add a `v-flex` with a defined size(eg. `xs4`) and an offset(eg. `offset-xs4`)

### Expected Behavior
The flex item(`v-flex`) should be offset from the top by the defined offset

### Actual Behavior
The flex item(`v-flex`) is offset to the right instead of being offset to the bottom

### Reproduction Link
[https://codepen.io/anon/pen/KREbqj](https://codepen.io/anon/pen/KREbqj)

### Other comments
The offset attribute doesn't seem to be respecting the column layout

**Comment by KaelWD** [comment]
Column layout behaviour isn't very well defined, and we will be rebuilding the entire grid system for 2.0.
