### ISSUE TITLE
[Bug Report] Vuetify couples (*) sign to required attribute on fieldnames

### ISSUE THREAD

**Issue by Kailaash-Balachandran** [vuetifyjs/vuetify#4125]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Mac OS 10.13.4

### Steps to reproduce
Use case: Scroll to the first error using Vuelidate. 

1. Remove required=true for vuetify input text field. 
2.  (*) sign is removed from the field label.
 
### Expected Behavior
Vuetify should not tie required attribute to browser behaviour. (*) should be shown with another special attribute. Problem happens when we use Vuelidate (other libraries) for validation. 

### Actual Behavior
Doesn't work because HTML5 validatation doesn't submit the form as required fields are empty.

**Comment by KaelWD** [comment]
`required` no longer changes anything in v1.1
