### ISSUE TITLE
[Feature Request] Time Picker AM/PM selector moved out of the title

### ISSUE THREAD

**Issue by bdeo** [vuetifyjs/vuetify#4126]
### Problem to solve
This allows the no-title prop to be used in conjunction with ampm (which is default right now). Currently if the no-title prop is used, the times are always in the AM. 

### Proposed solution
VTimePickerTitle.`genAmPm()` just needs to be in VTimePickerClock and a readonly version displayed in the title and any css issues that come along with that. Prop `ampm` will also need to be moved as well.

**Comment by bdeo** [comment]
![image](https://user-images.githubusercontent.com/4085974/49340959-bcac7e00-f614-11e8-8c77-232740ddcea5.png)

**Comment by KaelWD** [comment]
Similar designs from a couple of Android apps:
![screenshot_2018-12-03-01-53-04-832_org gnucash android](https://user-images.githubusercontent.com/16421948/49341226-98957f00-f69e-11e8-8021-9308cfca9485.png)
![screenshot_2018-12-03-01-53-47-257_com urbandroid sleep](https://user-images.githubusercontent.com/16421948/49341227-9e8b6000-f69e-11e8-9386-e0220267b530.png)

**Comment by jacekkarczmarczyk** [comment]
fixed by da54462f7003c085e0e2945832b87692807c840d
