### ISSUE TITLE
[Bug Report] V-Btn/V-Text Hover Not Working

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#4131]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
1. Visit Codepen
2. Hover red & green buttons
3. Observe that red hover has no effect

### Expected Behavior
Expecting hover functionality to work, regardless of how text is passed to a component.

### Actual Behavior
When comparing **v-text** and **interpolation**, only the latter has hover functionality.

### Reproduction Link
[https://codepen.io/cdwyer/pen/jxoqMO](https://codepen.io/cdwyer/pen/jxoqMO)

### Other comments
Possible that this is expected behavior, and I'm just unaware of what's happening under the hood. Apologies if that's the case. Thanks!

**Comment by KaelWD** [comment]
`v-text` overrides the inner content element. In 1.1 the hover effect was changed, so that won't happen any more. https://codepen.io/anon/pen/yjWVmM

**Comment by dwyer14** [comment]
@KaelWD awesome! And my apologies, forgot to check for this on the beta release. Appreciate you clarifying. 👍
