### ISSUE TITLE
[Bug Report] Wording <v-expansion-panel-content/> without <v-expansion-panel>  issue

### ISSUE THREAD

**Issue by trollepierre** [vuetifyjs/vuetify#4133]
### Versions and Environment
**Vuetify:** 1.0.12
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.11.6

### Steps to reproduce
Create a component with this <v-expansion-panel-content/> without <v-expansion-panel> around
=> Open the console

### Expected Behavior
The v-expansion-panel component must be used inside a v-expansion-panel-content

### Actual Behavior
The v-expansion-panel-content component must be used inside a v-expansion-panel

### Reproduction Link
[https://codepen.io/trollepierre/pen/RymxwR](https://codepen.io/trollepierre/pen/RymxwR)

**Comment by jacekkarczmarczyk** [comment]
Closed in #4153
