### ISSUE TITLE
[Bug Report] Icon inside button does not get correct color

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4134]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
Create a `v-btn` with a `v-icon` inside.
Set the button color.

### Expected Behavior
The icon should inherit the same color as the text inside the button.

### Actual Behavior
The icon color is either dark (54% black) or white depending on the app theme. This overrides the color set on the button.

### Reproduction Link
[https://codepen.io/anon/pen/pVmpbO](https://codepen.io/anon/pen/pVmpbO)

### Other comments
The following CSS seem to have been added with 1.1 beta 0 which causes this:
```
.theme--light .v-icon,
.application .theme--light.v-icon {
  color: rgba(0,0,0,0.54);
}
.theme--light .v-icon.v-icon--disabled,
.application .theme--light.v-icon.v-icon--disabled {
  color: rgba(0,0,0,0.38) !important;
}
.theme--dark .v-icon,
.application .theme--dark.v-icon {
  color: #fff;
}
.theme--dark .v-icon.v-icon--disabled,
.application .theme--dark.v-icon.v-icon--disabled {
  color: rgba(255,255,255,0.5) !important;
}
```
Possible solution, add:

```
.v-btn .v-icon {
  color: inherit;
}
```
(By not specifying `!important` it will still allow to override the icon color specifically by setting the `color` prop on the `v-icon` element.

**Comment by SeregPie** [comment]
Same here.

I'm missing those lines:
```css
.v-btn .v-btn__content .v-icon {
  color: inherit;
}
```

**Comment by KaelWD** [comment]
Already reported on discord, but it's good to have an issue too. This was caused by a11be7a80290835762dae263154894dd073d864c.
