### ISSUE TITLE
[Feature Request] Don't focus on text-field after clearing it

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#4135]
### Problem to solve
On mobile devices it is annoying that the soft keyboard pops up after hitting the clear button of a clearable text-field.

### Proposed solution
Make an option to not focus upon clearing the text-field.

**Comment by AuspeXeu** [comment]
Feels more like a workaround ...

**Comment by jacekkarczmarczyk** [comment]
@KaelWD how about `clearable="nofocus"`? This could also support other features like `clearable="noopen"` or combined `clearable="noopen,nofocus"`. I agree that using `append-icon` is more like workaround than proper solution

**Comment by AuspeXeu** [comment]
@jacekkarczmarczyk I like that. Parametrising clearable seems intuitive here.

**Comment by KaelWD** [comment]
We could do that, but what's the use case? I imagine that the vast majority of the time, a cleared field will by typed in straight away. A small workaround is acceptable in this case instead of complicating the massive api we already have.

**Comment by jacekkarczmarczyk** [comment]
The problem with this workaround is that you can't use append-icon and clearable together

**Comment by johnleider** [comment]
While I can't speak to the suggested implementations within this thread, I do believe it is worth further discussion.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
