### ISSUE TITLE
[Bug Report] v-autocomplete doesn't automatically highlight the first matching option

### ISSUE THREAD

**Issue by throskam** [vuetifyjs/vuetify#4136]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Linux

### Steps to reproduce
- Enter "al"
- Press enter

### Expected Behavior
"Alabama" should be the new selection since it matches the filter the most.

### Actual Behavior
Nothing is selected or highlighted and the drop-down closes.

### Reproduction Link
[https://codepen.io/anon/pen/NMVOjV](https://codepen.io/anon/pen/NMVOjV)

### Other comments
It works fine when entering "alab" because there is only one option left.

**Comment by johnleider** [comment]
This logic has changed slightly in v1.1 to resolve a myriad of other issues regarding unintentional item changes. It will only auto-select the first item when only 1 item exists during a search filter.

**Comment by throskam** [comment]
Is there any plan to implement this later on maybe under a prop ?
If not, is there a way I could reproduce the behavior manually ?

**Comment by johnleider** [comment]
You can make a feature request for a prop.
