### ISSUE TITLE
[Bug Report] Missing some Material battery icon

### ISSUE THREAD

**Issue by AMontagu** [vuetifyjs/vuetify#4137]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Linux x86_64

### Steps to reproduce
Use v-icon with one of Material battery icon like: battery_X or battery_charging_X

### Expected Behavior
icon show

### Actual Behavior
nothing show

### Reproduction Link
[https://codepen.io/amontagu/pen/xjNBKW](https://codepen.io/amontagu/pen/xjNBKW)

**Comment by WuerfelDev** [comment]
Hi @AMontagu 
The icons are from google's material icon font. This is not related to vuetify.

Even if the icons appear in https://material.io/tools/icons/ not all of them are included in the icon font.
This is the same issue as yours: https://github.com/google/material-design-icons/issues/181

**Comment by WuerfelDev** [comment]
Alternatively you could try to use the battery icons from fontawesome: https://fontawesome.com/icons/battery-quarter?style=solid

**Comment by johnleider** [comment]
You will need to follow the instructions [here](https://google.github.io/material-design-icons/) in order to install the entire library, enabling these icons.

**Comment by bchoubert** [comment]
So are we supposed to create a custom font ourselves from the svg files just to have the full version ? (As the documentation just indicates where to find the svg files). Is there any other workaround ?

**Comment by johnleider** [comment]
Google doesn't provide all of the fonts in their (very recently) updated icons. There is nothing we can do about that. I'll add a task to create documentation on this subject.

https://github.com/vuetifyjs/vuetifyjs.com/issues/485

**Comment by bchoubert** [comment]
@johnleider : thank you ! I was just surprised that the website lists some icons that are not already included in the font, without telling it.

**Comment by johnleider** [comment]
They updated everything a few weeks ago. The icon was probably in at one point.

**Comment by unionthugface** [comment]
The partial battery icon `battery_20` is still available on the list of icons, but it doesn't show up in HTML.  Petition to reopen this ticket.

https://material.io/tools/icons/?icon=battery_20&style=baseline

**Comment by jacekkarczmarczyk** [comment]
This is not a Vuetify issue, please use proper repo, see https://github.com/vuetifyjs/vuetify/issues/4137#issuecomment-392955600
