### ISSUE TITLE
[Vuetify] HOW COULD I HAVE A REAL REPLY ?!

### ISSUE THREAD

**Issue by be-next-hotdog** [vuetifyjs/vuetify#4138]
Sorry guys,
I just feel little ridiculous cuz I follow strictly issue report steps or looked for a solution directly in Discord channels but up to present, I never ever got a real suggestion or nobody replied. 

Could you please tell me how to find a solution in Vuetify community ? 

Be grateful for your real helps before you remove this issue simply.

**Comment by bdeo** [comment]
This issue board is strictly for bug reports and feature requests. If you have joined the discord server at community.vuetifyjs.com and asked for help with an accompanying codepen reproduction, and no one replied then you may need to ask again. Our community members and team members try their best to answer when they can or when they know of a solution. Please try again at community.vuetifyjs.com.
