### ISSUE TITLE
Invalid prop in pagination component in 0.11.0

### ISSUE THREAD

**Issue by jijoel** [vuetifyjs/vuetify#414]
### Steps to reproduce
Insert a pagination component on a page. Click any link in the component.

### Versions
The pagination component does not work in vuetify 0.11.0. It does in 0.10.4. Testing on Chrome / Mac, and with codepen.

### What is expected ?
Highlight the item that was clicked on, and set the value to the page number 

### What is actually happening ?
All highlighting disappears. In the console, we get:

> Invalid prop: type check failed for prop 'value'. Expected Number, got Boolean. 
(found in &lt;Pagination&gt;)"

I believe it's related to this change in mixins/toggleable.js:

    0.10.4-  this.isActive = this.value
    0.11.0+  this.isActive = Boolean(this.value)

### Reproduction Link
https://codepen.io/anon/pen/BRzYdd?editors=1111

**Comment by nekosaur** [comment]
This has been fixed in dev (see #410)
