### ISSUE TITLE
[Bug Report] gap between the v-autocomplete async loading animation and prepend-icon

### ISSUE THREAD

**Issue by birdlavv** [vuetifyjs/vuetify#4141]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
Open pen and note the leftmost side of the blue stripe animation.

### Expected Behavior
Note how the animation from the `:loading` prop is not being applied beneath the `prepend-icon` although it is beneath the `append-icon`

### Actual Behavior
It was expected to be applied to the entire bottom width of the `v-autocomplete` to maintain symmetry

### Reproduction Link
[https://codepen.io/George6789/pen/yjdVNd](https://codepen.io/George6789/pen/yjdVNd)

**Comment by johnleider** [comment]
This is the intended behavior. Same would apply if you were to use append-outer.
