### ISSUE TITLE
[Bug Report] Navbar does not respect clipped-right

### ISSUE THREAD

**Issue by gtalarico** [vuetifyjs/vuetify#4142]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.13
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Add 2 navigation-drawers, left and right
Make left drawer `clipped`
Make navtoobar `clipped-left`

### Expected Behavior
right drawer should be drawn above nav-toolbar

### Actual Behavior
Right drawer is drawn behind nav-toolbar on wide screen
Right drawer is drawn correctly on narrower screens

### Update:
Note: If you remove `clipped-left` it fixes the right drawer z-index for all scales

### Reproduction Link
https://codepen.io/gtalarico/pen/NMZjGE
![vuetify](https://user-images.githubusercontent.com/9513968/40527300-992a1e3e-5fb9-11e8-921b-475fed7d0e43.gif)

**Comment by KaelWD** [comment]
`.toolbar--clipped` has a z-index of 3, not sure why.

**Comment by ebisbe** [comment]
In Vuetify v1.1.1 it's not happening any more. At least with those parameters:
Vuetify: 1.1.1
Vue: 2.5.16
Browsers: Chrome 67.0.3396.99
OS: Mac Os 10.13.5 Sierra

**Comment by KaelWD** [comment]
The repro link is incorrect, it doesn't have those props specified.

Here's an updated one, still happens in 1.1.3: https://codepen.io/anon/pen/xJKJjB?editors=1010

**Comment by ebisbe** [comment]
Yes, still failing. I'll look it tomorrow. Thanks for the update.

**Comment by johnleider** [comment]
Because of the nature of this type of layout, you have to order it so that elements stack properly.

https://codepen.io/johnjleider/pen/Epyxox?editors=1010
