### ISSUE TITLE
[Bug Report] Conflict with fontawesome in the animation of validation error from v-text-field

### ISSUE THREAD

**Issue by pwildschut** [vuetifyjs/vuetify#4143]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Generate a validation error in a v-text-field. Have fontawesome css linked behind the vuetify css

### Expected Behavior
text-field label jiggle at validation error

### Actual Behavior
label animation rotates 360º instead

### Reproduction Link
[https://codepen.io/pwildschut/pen/ZodxyJ](https://codepen.io/pwildschut/pen/ZodxyJ)

**Comment by johnleider** [comment]
This has been resolved in v1.1.
