### ISSUE TITLE
[Bug Report] select with header property

### ISSUE THREAD

**Issue by ziaxdk** [vuetifyjs/vuetify#4148]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Add an items property to data with a header property name

### Expected Behavior
select to work correctly

### Actual Behavior
select doesn't add hover and select doesn't work

### Reproduction Link
[https://codesandbox.io/s/9ovxq5p0q4](https://codesandbox.io/s/9ovxq5p0q4)

### Other comments
When binding to complex object with a 'header' property, the select component doesn't work

**Comment by KaelWD** [comment]
This is working as intended, the header property indicates that the item is a header. We should probably make this configurable though like with `text`, `value`, `disabled`, and `avatar`.

**Comment by KaelWD** [comment]
`header` and `divider` have been moved to `type: 'subheader' | 'divider'` in v3, and only `title` and `value` are read from objects by default unless you enable `item-props`
