### ISSUE TITLE
[Feature Request] Describe in more details how A-La-Carte could be used with Dynamic import()

### ISSUE THREAD

**Issue by vkorehov** [vuetifyjs/vuetify#4149]
### Problem to solve
No documentation exists how to use Viewtify with Webpack4 and async loading parts of Vuetify.

### Proposed solution
https://medium.com/@vladislavs.korehovs/optimizing-vue-vuetify-performance-async-loading-5e13ca43706e

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. Documentation issues should be opened on https://github.com/vuetifyjs/vuetifyjs.com

**Comment by vkorehov** [comment]
>Incorrect, VBtn/index exports VBtn/VBtn
ok, missed that bit. 

But for some reason "documented" way (* as VBtn) is not working for me with Webpack4 
it gives:

"template or render function not defined"
Changing imports the way I described is working, however it could be shortened to

import VBtn from 'vuetify/es5/components/VBtn'
but I still prefer 
import VBtn from 'vuetify/es5/components/VBtn/VBtn'
to include bare minimum of stuff.

**Comment by nekosaur** [comment]
When you import `* as VBtn` you have to destructure the object into components `components: { ...VBtn }`

**Comment by KaelWD** [comment]
I don't think VBtn exports everything properly to be used that way. There's another issue about it somewhere.

**Comment by vkorehov** [comment]
Thanks, I missed it, indeed. Also perhaps this section:
"You can also import components in .vue files, as seen below. When doing so it’s important that you import all named exports, and then destructure them in components. Otherwise child components such as v-card-text or v-expansion-panel-content will not be available."
could mention also that still need to import Vuetify via Vue.use() otherwise VApp crashes with this.$vuetify not defined.
