### ISSUE TITLE
Dialog should not add v-card

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#415]
I appreciate the refactoring of the old `v-modal` into `v-dialog`, but I don't like that it automatically adds a `v-card` to the content. It should be up to the user to decide what type of elements they want to place inside the dialog.

**Comment by johnleider** [comment]
This was heavily debated during development. I'd like for us to have a discussion on this. Personally, I agree with you, but I know @mfferreira has some good points.

**Comment by mfferreira** [comment]
@sindrepm I would also agree with you if the card added way more styling.

`v-card` only sets dropshadow, rounded corners and a couple of other small things.
`v-dialog` is just a `v-card` on steroids, giving a few more options to the developer.

If we removed the `v-card` from the dialog, we'd be adding all of the same styles... I think you get the point.

But as @johnleider mentioned said, we debated this quite a bit and we're always open for improvements.

**Comment by sindrepm** [comment]
@mfferreira I don't see the dialog as a card on steroids. To me the card is a completely unrelated component with different semantics, and using it inside another control just for the sake of saving a few bytes on styles is a moot point in my opinion and looks kind of like a hack. A card is not a general-purpose wrapper for other controls. Having to add rules like the following to "cancel" out the default card styling should prove my point further:

```
.card
      elevation(24)

      & ^[2..-1]__title
        padding 12px 24px

      & ^[2..-1]__text
        padding 20px 24px 24px

      & ^[2..-1]__row--actions
        padding: 8px 0

        .btn
          margin-right: 8px
```

Generally I am not fan of mutating existing style rules like this unless absolutely necessary. It often causes inconsistencies and unforeseen side effects at some point.

I really like the work that has been put into Vuetify and I think it is the best library for Material Design at the moment, but please be careful not to become too opinionated about how the controls are used and combined. I think it should be a goal to make each component as self-contained as possible.

**Comment by mfferreira** [comment]
@sindrepm All very valid points. Would you like to take a look at the [enhancement/dialogs](https://github.com/vuetifyjs/vuetify/tree/enhancement/dialogs) branch and give some feedback?

**Comment by Phunky** [comment]
I don't think the problem is that dialog uses a card, as that follows the spec of dialogs and MD doesn't have any generic modal component spec and I think this is the problem that's been raised here.

When i've built dialog components in the past I split them into three core components; overlays, modal and then dialogs. This allows you to compose other components from each to save on duplicating effort.

**Comment by johnleider** [comment]
@sindrepm While mutating existing style rules may not be the greatest thing to do, there are many things reused in MD and to me, it doesn't make sense to have a dialog-title component and a card-title component. I believe more of this issue stems from the fact that cards are not really in spec and need to be refactored. Once that is done, those styles will more than likely become obsolete.

**Comment by sindrepm** [comment]
To me personally, it is not the styling introduced by the card that is the main problem (I can always work around that if needed). It is more that I think it is fundamentally wrong to include a card in the dialog component when a card is not really intended for that purpose. Just that it happens to provide a similar shape and styling as a dialog does not mean it should be used as such. I am all for reusability but when you have to add override styles to tweak the original component to fit with your use case I think that advantage is lost. Why not just add the styles needed to the dialog itself? The markup would be simplified as well as you can get rid of one level of nesting divs.

Also, what if at some point the spec for card changes? It would introduce side effects because the dialog component is based on a card. Already I believe the spec differs with regard to padding. For example the card uses 16px left/right padding, where as the dialog uses 24px padding.

**Comment by johnleider** [comment]
I believe we are all in on the same page, dialog should not have a card by default. Have you been able to check my PR?

**Comment by sindrepm** [comment]
@johnleider looks good to me. I haven't tried it, but will it get a white background by default now? That was inherited from `.card` so just ensure it doesn't end up with a transparent background.

**Comment by johnleider** [comment]
@sindrepm Good feedback, will add.
