### ISSUE TITLE
[Feature Request] index.js contains "createSimpleFunctional" which does not allow to use more granular imports to improve performance.

### ISSUE THREAD

**Issue by vkorehov** [vuetifyjs/vuetify#4150]
### Problem to solve
Some sub-components don't have individual .js files, istead in index.js they have:

const VToolbarTitle = createSimpleFunctional('toolbar__title')
const VToolbarItems = createSimpleFunctional('toolbar__items')

Putting those into separate .js files and having consistent import structure, could allow to take only needed sub-components and reduce bundle sizes.
It should get substantial saving on many components.
Because people could use VList without need to use VListAvatar etc, .

Currenty some small things lie VSpacer, etc. are forcing you to use index.js, while you could get away on using individual "sub-components" otherwise.

### Proposed solution
package them like the other dependencies, into separate files please, you can keep createSimpleFunctional() but put it into consistenly named file.

**Comment by KaelWD** [comment]
This is no longer necessary with webpack 4's tree-shaking.
