### ISSUE TITLE
[Bug Report] v-list-tile emits click when disabled

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#4152]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.15
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.12.6

### Steps to reproduce
Click on a disabled list item in the menu.

### Expected Behavior
Click shouldn't be emitted, so @click method doesn't get called and nothing happens for disabled list items.

### Actual Behavior
Click is emitted.

### Reproduction Link
[https://codepen.io/kdholt34/pen/VxJJdR?editors=1010](https://codepen.io/kdholt34/pen/VxJJdR?editors=1010)

**Comment by bdsoha** [comment]
Having the same issue

**Comment by johnleider** [comment]
Disabled should really be refactored a bit, but since we are in beta, the most concise fix is to remove pointer events from the root div, which is the element that actually receives the events.

**Comment by JesusCrow** [comment]
This bug still exists https://codepen.io/JesusCrow/pen/NBEozb

**Comment by Heemrad** [comment]
This bug is still present - currently looking for any working solution
