### ISSUE TITLE
[Bug Report] v-autocomplete shows the value instead of text when selecting an option

### ISSUE THREAD

**Issue by arivera12** [vuetifyjs/vuetify#4158]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
Select an option.

### Expected Behavior
When selecting an option display the selected text and set the value of the option in a hidden input.

### Actual Behavior
When selecting an option the value of the option is being displayed instead of the text of the option.

### Reproduction Link
[https://codepen.io/anon/pen/OELBjO](https://codepen.io/anon/pen/OELBjO)

### Other comments
After selecting an option returns the value to the input and displays it. Which at least works on submitting the form but why the value is showing instead of the text? I think the value should be set in a hidden input and the text as a label or text. Keep in mind, what about if the value are numbers or something else? It doesn't make any sense displaying the value when selecting an option instead of the text. Please help.

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/40631776-bd03ef64-62ad-11e8-9c0a-68f037645932.png)

**Comment by arivera12** [comment]
@johnleider but why we are displaying the value instead of text when selecting an option. Let's think about the primitive select tag, You had a value and text, you show the text to the end user and the value it's what it's send to the server. Why this works like this instead of the primitive way? What about if the value is a number or is in another language or something else? It wouldn't make any sense for the end user.

**Comment by ste-brown** [comment]
@johnleider This is not at all how lookup/combo's/selects work. The value is most likely an internal id that identifies the option and is in no way meant for the end user to see. Is it expected that we take the text value and map it back to our internal id's on the server? This is loose and doesn't account for duplicates (it happens).

**Comment by arivera12** [comment]
@ste-brown I switched to v-autocomplete instead of using v-select and works as expected and have more features and functionalities than v-select give it a try you won't regret.
