### ISSUE TITLE
[Bug Report] Using vue-meta plugin breaks CSP nonce attribute addition (cspNonce)

### ISSUE THREAD

**Issue by detroitenglish** [vuetifyjs/vuetify#4159]
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Click 'Check Nonce' button in provided Codesandbox to check for nonce attribute on `#vuetify-theme-stylesheet`

Uncomment lines 7 and 8 in main.js to register vue-meta in the main Vue instance, and click the Check button again.

### Expected Behavior
A `nonce` attribute should be added to `#vuetify-theme-stylesheet` style element whenever `cspNonce` option is included in Vuetify registration, and not be affected by the inclusion of any additional Vue plugins.

### Actual Behavior
No `nonce` attribute is added if `vue-meta` is registered as a Vue plugin. This will break any app that requires said nonce for inline styling as a `style-src` content security rule.

### Reproduction Link
[https://codesandbox.io/s/qkj051mq8q](https://codesandbox.io/s/qkj051mq8q)

### Other comments
Behavior is being altered solely by the presence of one the most popular plugins out there 🙈

See `vuetify/src/components/VApp/mixins/app-theme.js:80` for offending code

**Comment by KaelWD** [comment]
Ah shit, forgot about that one. 

> Behavior is being altered solely by the presence

This is so SSR will work without having to configure anything, because vue-meta disables the other way of adding things to the head.

**Comment by KaelWD** [comment]
Looks like I forgot it for non-vue-meta SSR too.
