### ISSUE TITLE
[Feature Request] v-card-action align to end of v-card when extending height

### ISSUE THREAD

**Issue by pwildschut** [vuetifyjs/vuetify#4160]
### Problem to solve
When extending the height of a v-card by setting up the height attribute the v-card action does not align with the bottom of the v-card. I know this might be just my aesthetical liking. But still, is there a way to achieve this? Here is an example of what i mean:  https://codepen.io/pwildschut/pen/ERxayE

### Proposed solution
Not been able to find my own solution. Still exploring

**Comment by sindrepm** [comment]
I don't think this should be the default behavior as cards can have many different layouts. You can easily achieve this by using a few helper classes, though. See this example: https://codepen.io/anon/pen/oyNrEe

There are probably different ways this can be implemented, but an easy one is to make your card use flexbox (column) and then apply the "grow" class to the `v-card-text` element to make it fill the remaining space. This will effectively push the actions row to the bottom of the card.

**Comment by tecfu** [comment]
@sindrepm Very helpful example, thank you. 
@nekosaur Can we do a little more to document this?
