### ISSUE TITLE
[Bug Report] v-dialog no longer overflows

### ISSUE THREAD

**Issue by alex-red** [vuetifyjs/vuetify#4168]
### Versions and Environment
**Vuetify:** 1.1.0-beta.1
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Linux x86_64

### Steps to reproduce
Open the modal

### Expected Behavior
Overflows

### Actual Behavior
No longer overflows

### Reproduction Link
[https://codepen.io/anon/pen/gKbzvN?&editors=101](https://codepen.io/anon/pen/gKbzvN?&editors=101)

### Other comments
Looks like the fix is to just add overflow auto to .v-dialog

**Comment by Jemmy** [comment]
props **scrollable** 

`<v-dialog v-model="dialog" scrollable width="600px">`

https://codepen.io/Jemmy/pen/MXwwKE?editors=1010

 working :)

**Comment by johnleider** [comment]
Definitely a fix, but not the issue. I have a PR up currently to resolve this on both fronts #4170
