### ISSUE TITLE
[Bug Report] Sliders does not respect readonly prop

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4177]
### Versions and Environment
**Vuetify:** 1.1.0-beta.1
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
Create a `v-slider` with `readonly` prop.

### Expected Behavior
Should not be able to change slider value by dragging the thumb or click on the track.

### Actual Behavior
Able to change slider as normal.

### Reproduction Link
[https://codepen.io/anon/pen/jKbNPr](https://codepen.io/anon/pen/jKbNPr)

**Comment by KaelWD** [comment]
Last good version was alpha.3: https://codepen.io/anon/pen/RJWbvP?editors=1111
