### ISSUE TITLE
[Bug Report] Text Field's Mask for non-english characters (letters)

### ISSUE THREAD

**Issue by algiorgio** [vuetifyjs/vuetify#4178]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.2
**Browsers:** Chrome 67.0.3396.62
**OS:** Linux x86_64

### Steps to reproduce
1. Go to link
2. Try to input any non-english letter

### Expected Behavior
In accordance with Mask Legend for Text Field, Mask A is supposed to mask any letter (not only English).

### Actual Behavior
Mask A for Text Field is supporting only English letters.

### Reproduction Link
[https://codepen.io/algiorgio/pen/xzwxvO](https://codepen.io/algiorgio/pen/xzwxvO)

**Comment by AlexSHoffman** [comment]
Javascript's version of regex doesn't support non-English letters, so you cannot use `\w` to match any non-English word.

I'd suggest doing something like this:

```
/[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF\w]+/g
```

Here's a small demo: https://regexr.com/3qis0

**Comment by AlexSHoffman** [comment]
Javascript's version of regex doesn't support non-English letters. You can use `\w` only to match English words. I'd suggest doing something like this:
```
/[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF\w]+/g
```
Here's a small demo: https://regexr.com/3qis0

**Comment by algiorgio** [comment]
Mask for v-text-field has restricted format.
Where do you suppose to place these Unicode's ranges?

`v-text-field(label='Name' mask="/[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF\w]+/g")`
???

**Comment by AlexSHoffman** [comment]
@algiorgio I wasn't suggesting using it in the mask. This regex expression is what can allow Vuetify developers to implement support for other languages in the mask

**Comment by KaelWD** [comment]
Thanks for the suggestion, but we aren't planning to add any more functionality to masks at this time.

**Comment by vincent41** [comment]
Very sad regexp would be very helpful. because now two way filter is gone by vue2.
