### ISSUE TITLE
[Feature Request] v-list-group keyboard accessibility

### ISSUE THREAD

**Issue by franchert** [vuetifyjs/vuetify#4180]
### Problem to solve
The current v-list-group component cannot be accessed via tabbing on a keyboard.

### Proposed solution
Adding a tabindex and a keydown event to the genGroup method will allow keyboard access.

**Comment by franchert** [comment]
I have working code for this, but I'm new to the process for getting it moving along.

**Comment by bigtunacan** [comment]
@johnleider Is there any possibility of getting this PR (#4183) into the v.1.0.X release? I think this is a bug rather than a feature.  Right now expansion lists are completely inaccessible to blind and mobility impaired users.

**Comment by johnleider** [comment]
Fair enough. It won't go out for initial release as we are frozen, but can visit as a bug after.
