### ISSUE TITLE
[Bug Report] Additional CSS is not generated thus style is broken when using cli

### ISSUE THREAD

**Issue by aurimus** [vuetifyjs/vuetify#4181]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
Create app via vue-cli
Install vuetify with npm
Install material-design-icons-iconfont with npm

Modify main.js as such:
```
import Vue from 'vue'
import App from './App.vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'

Vue.config.productionTip = false

Vue.use(Vuetify)

new Vue({
  render: h => h(App)
}).$mount('#app')
```

### Expected Behavior
Expect additional styles to be added (generated) by JS resulting in fully style components

### Actual Behavior
Instead they stay the same and only style from vuetify.min.css is applied resulting in half styled components.

![screenshot from 2018-06-02 14-45-37](https://user-images.githubusercontent.com/1052992/40874099-b154abb2-6673-11e8-850e-e31649f90c4e.png)

**Comment by aurimus** [comment]
Anyone has any idea what could be wrong?

**Comment by johnleider** [comment]
There is nothing actionable with this, no provided reproduction.
