### ISSUE TITLE
[Bug Report] v-textarea genMarker () is not escaping textarea content

### ISSUE THREAD

**Issue by caliny97** [vuetifyjs/vuetify#4182]
### Versions and Environment
**Vuetify:** 1.1.0-beta.1
**Vue:** 2.5.15
**Browsers:** Chrome 66.0.3359.181, Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
enter some html into the textarea, it will get injected into the DOM

### Expected Behavior
html content typed in the textarea should not be injected into DOM.

### Actual Behavior
html content typed in the textarea injected into DOM.

### Reproduction Link
[https://codepen.io/anon/pen/OEybaX](https://codepen.io/anon/pen/OEybaX)

### Other comments
v-textarea genMarker () is not escaping textarea content. If the textarea input has for example an piece of html, the html is being added to the mask div.

**Comment by jacekkarczmarczyk** [comment]
Fixed by #4257
