### ISSUE TITLE
[Feature Request] how to fire Carousel @click event?

### ISSUE THREAD

**Issue by AngelaDaddyRoy** [vuetifyjs/vuetify#4184]
### Problem to solve
it's nice to jump into detail when user click Carousel's items,however it doesn't fire click event by this way:
```
 <v-carousel>
          <v-carousel-item v-for="item in bulletins" :src="item.coverImage" :key="item.id" lazy @click="goBulletinDetail(item)">
            <p class="title mt-3 grey--text text--lighten-2">{{item.title}}</p>
          </v-carousel-item>
        </v-carousel>
```

### Proposed solution
add ideas?

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by qm3ster** [comment]
Please consider the goats: `@click.native="goBulletinDetail(item)"`
Otherwise, put an overlay into the slot and click on that instead.
