### ISSUE TITLE
[Bug Report] Ripple won't go away when clicked with left and right click at the same time

### ISSUE THREAD

**Issue by fhadiel** [vuetifyjs/vuetify#4185]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
1. find components that have ripple
2. click with left and right mouse button at the same time

### Expected Behavior
ripple go away

### Actual Behavior
ripple won't go away

### Reproduction Link
[https://codepen.io/suitedJimster/pen/xqWVBP](https://codepen.io/suitedJimster/pen/xqWVBP)

**Comment by johnleider** [comment]
Having troubles reproducing this.

**Comment by fhadiel** [comment]
![Check this](https://im.ezgif.com/tmp/ezgif-1-7c68a76a81.gif)

**Comment by KaelWD** [comment]
On;y the last ripple gets removed, so if two "remove" events are fired within 300ms then only one element is removed: https://github.com/vuetifyjs/vuetify/blob/dev/src/directives/ripple.ts#L74

**Comment by DRoet** [comment]
This also happens when clicking a button + holding it + dragging

@KaelWD I hope you can appreciate my mouse movement
![](https://media.giphy.com/media/8cKrbBz3sRqO0cxyel/giphy.gif)

and it happens when tapping a button on Mobile (chrome android):

<img src="https://i.imgur.com/l9J9qgV.png" width="300" height="500">

**Comment by NBTX** [comment]
I was able to reproduce by left-clicking and then right-clicking before the ripple is removed.

**Comment by MaeseppTarvo** [comment]
Still exists on mobile.

**Comment by yurriiy** [comment]
still exists
![1](https://user-images.githubusercontent.com/38867716/121362519-ced2aa00-c93e-11eb-95f1-bcc55e7b9a93.png)

**Comment by DawnImpulse** [comment]
any update if this will ever be fixed?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
