### ISSUE TITLE
[Bug Report] Parallax Effect is a bit laggy under Firefox and Edge

### ISSUE THREAD

**Issue by norilt** [vuetifyjs/vuetify#4186]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Firefox 60.0, Mozilla Firefox, Microsoft Edge
**OS:** Linux x86_64, Windows, Android

### Steps to reproduce
If you scroll fast over the parallax, it looks a bit laggy.

### Expected Behavior
No lags like in Chrome.

### Actual Behavior
A bit laggy under Firefox and Edge.

### Reproduction Link
[https://codepen.io/norilt/pen/yEYKQZ](https://codepen.io/norilt/pen/yEYKQZ)

### Other comments
It looks like it is a a problem with large images. On 1280x800 the lags are not noticable, but on 1920x1080 it is noticable and on 4k it's quite bad.

**Comment by sh7dm** [comment]
MDN has an article about this lags: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by KaelWD** [comment]
Chrome, firefox, and IE are fine for me; it's just edge that gets a bit screwy.

**Comment by johnleider** [comment]
This looks just fine in Firefox now and Edge isn't that bad. With Edge moving to Chromium, I'm going to consider this resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
