### ISSUE TITLE
[question] v-date-picker min/max ,and/or allowedDates callback?

### ISSUE THREAD

**Issue by suitedjimster** [vuetifyjs/vuetify#419]
Hi, 
For the date picker (and maybe time picker), is it in the roadmap to implement a min/max prop?
or pass an array of allowedDates?
or even better to have a callback to filter allowed/disabled dates?

similar to Angular-material validation?
https://material.angularjs.org/latest/demo/datepicker

or the disableDayFn callback in
https://github.com/dbushell/Pikaday

**Comment by johnleider** [comment]
This is something we could implement in the future, tagging.

**Comment by smtlk** [comment]
I don't quite get what date ranges have to do with the allowed dates functionality, as far as i can tell you can only pick one specific day per picker, meaning you need to either use two at the same time to get a range of dates.

**Comment by nekosaur** [comment]
This issue was for filtering allowed dates. Picking a date range is something else, and you are correct that it is not something we support at this time.

**Comment by WaleedAli007** [comment]
any chance of adding "range" functionality? is it even in the roadmap?

**Comment by KaelWD** [comment]
@WaleedAli007 You know github has a search bar right? #1646

**Comment by WaleedAli007** [comment]
sorry. My bad
