### ISSUE TITLE
[Feature Request] 2 enhancements to v-tabs

### ISSUE THREAD

**Issue by ch-luke** [vuetifyjs/vuetify#4191]
### Problem to solve
Request 1 -  Support large lists of tabs on sections of a page (i.e. doesn't take up the whole width of the screen and still needs to be scrollable)
Request 2 - Improved swiping / scrolling for mobile phones

### Proposed solution
Request 1 (Solution)

Currently the scrolling of the tabs seems to work best when it occupies the full width of the screen. There are occasions when you might only use part of the screen. For example, on mobiles you could have a clickable navigation drawer, but on PC's you have it permanently shown - so the tabs in this chase only occupy: Screen width - 300px (drawer). This means that the "tab-wrapper" transform: translateX(-XXXXpx); is now always wrong.

See example repo: https://codepen.io/chluke/pen/Wyrpxa

Request 2 (Solution)

The current swiping action of tabs seems to scroll several items across and then selects the item you touched, which is a little different to how I've seen other solutions work and don't seem natural to me.

I would love the following to happen instead:
1. Big swipe - scrolls to end or beginning of tabs and aids as a quick preview to users
2. Small swipe - scrolls a few items ahead or behind
3. Seperate swipe from item select (rather have it as two actions. also a component option to switch on / off would be great)
4. Add an option to set scroll distance when a tab is clicked (e.g. for me the whole tab + min 50px should be always shown). This is important as sometimes you click on the tab at the end of the viewable screen and then it is moved fully into focus, but you are not aware there are more items to scroll too.

**Comment by jacekkarczmarczyk** [comment]
Please create only one request per issue

**Comment by ch-luke** [comment]
As requested, closing issue in support of the following:

https://github.com/vuetifyjs/vuetify/issues/4204
https://github.com/vuetifyjs/vuetify/issues/4205
https://github.com/vuetifyjs/vuetify/issues/4206
