### ISSUE TITLE
[Feature Request] Time picker - add step/precision/interval

### ISSUE THREAD

**Issue by TMantas** [vuetifyjs/vuetify#4192]
### Problem to solve
Sometimes it would be easier for users to pick time with fixed step. Eg.: instead of saving 15:08, users could input 15:10 straight away if the step is 10 (minutes). Another: if the step is 15 then the users could save only 00, 15, 30 and 45 minutes.

### Proposed solution
Add step prop to Time picker component. By default it should be 1 (that's how it currently works). Changing this value would snap the handle to nearest value.

**Comment by nekosaur** [comment]
This is very easy to do with the `allowed-minutes` prop. https://codepen.io/anon/pen/XYXZQE?&editors=101

**Comment by TMantas** [comment]
Damn that's right! Thanks!
Maybe this should be added to examples?

**Comment by jacekkarczmarczyk** [comment]
Please open an issue in vuetifyjs.com repo. Ty
