### ISSUE TITLE
[Bug Report] Light v-menu in dark app gets dark themed

### ISSUE THREAD

**Issue by UncertaintyP** [vuetifyjs/vuetify#4193]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
1) Set app to dark mode
2) Create menu with light mode
3) ????
4) Profit

### Expected Behavior
Menu is dark themed (dark theme overwrites light theme)

### Actual Behavior
Menu should be light themed

### Reproduction Link
[https://codepen.io/anon/pen/JZGxKr](https://codepen.io/anon/pen/JZGxKr)

### Other comments
The inverse (dark menu in light app) works as expected.
Tested in Chrome and Firefox

**Comment by jacekkarczmarczyk** [comment]
Workaround - use `light` prop for `v-list`
https://codepen.io/anon/pen/JZXgjQ

**Comment by KaelWD** [comment]
CSS cascade is a tricky bastard, we can't really fix this until we switch to some other way of inheriting themes (css variables?)
