### ISSUE TITLE
[Bug Report] <main> padding-bottom does not adapt when footer is larger than 32px

### ISSUE THREAD

**Issue by efriedli** [vuetifyjs/vuetify#4194]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Use a footer that is higher than 32px, for instance 100px.

### Expected Behavior
<main> padding-bottom should correspond to footer height, for instance 100px

### Actual Behavior
<main> padding-bottom remains 32px instead of adapting, hiding the content that is at the end of <main>. Applied style:
element.style {
    padding: 56px 0px 32px;
}

### Reproduction Link
[https://codepen.io/anon/pen/XYXGgP](https://codepen.io/anon/pen/XYXGgP)

**Comment by KaelWD** [comment]
You have to use either `:height="100"` instead of an inline style, or `height="auto"`.

**Comment by efriedli** [comment]
Spot on! Thanks @KaelWD !
