### ISSUE TITLE
[Feature Request] Focus field on icon click

### ISSUE THREAD

**Issue by Melchyore** [vuetifyjs/vuetify#4197]
### Problem to solve
Clicking on the prepend or append icon does not focus the field.

### Proposed solution
Clicking on the prepend or append icon focus the field.

If it's a select field, open the dropdown.

**Comment by jacekkarczmarczyk** [comment]
It works like this in 1.1
https://codepen.io/johnjleider/pen/YLYEKG

**Comment by jacekkarczmarczyk** [comment]
It works like this with append icon in 1.1, for prepend icon you need to add the callback (should work in 1.0 as well)
https://codepen.io/anon/pen/vrGJBK?editors=1010

**Comment by Melchyore** [comment]
@jacekkarczmarczyk Yep, I know we can do that in the append icon callback but it goes against the concept of DRY, no?
Let's say we have 30 inputs, so for every input you must call the `focus` method, but it's redundant.

**Comment by jacekkarczmarczyk** [comment]
You can create your own component that extends text field and focused input when icon is clicked

**Comment by Melchyore** [comment]
That's a solution! Thank you!
