### ISSUE TITLE
[Bug Report] autocomplete uses filter function by default

### ISSUE THREAD

**Issue by Graziel** [vuetifyjs/vuetify#4199]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
enter anything in autocomplete

### Expected Behavior
items to select

### Actual Behavior
items to select are always empty

### Reproduction Link
[https://codepen.io/anon/pen/XYdgeB?editors=1010](https://codepen.io/anon/pen/XYdgeB?editors=1010)

### Other comments
had to add
```
:filter="(item) => item"
```
to v-select

**Comment by jacekkarczmarczyk** [comment]
You're missing `item-text="name"` prop
https://codepen.io/anon/pen/ZRWyxo?editors=1010

**Comment by Graziel** [comment]
ok, but docs are kind of unclear its necessary when returning object

**Comment by KaelWD** [comment]
It isn't necessary, just if you're using something other than `text` as the property key.

**Comment by Graziel** [comment]
ahh i get it now, wierd that what i did worked anyway thanks for your time 👍
