### ISSUE TITLE
Component slots undefined after latest Vuetify update

### ISSUE THREAD

**Issue by Pwntus** [vuetifyjs/vuetify#42]
Using `Vue 2.1.8.`
Updated from Vuetify `0.7.7` to `0.7.10` and every component using a slot is outputting `undefined`, no error messages. Was working before the update. I'm initiating Vuetify in the main App component's `mounted` hook.
Am I missing something during the updates? Maybe a Vue bug?

I feel like this is a support matter and should be posted elsewhere. Is it possible to start a Gitter chat or a forum of any kind?
Thanks.

**Edit:** Just read https://github.com/vuetifyjs/vuetify/issues/26#issuecomment-269379561 and downgraded to `Vue 2.1.6` and it's working, sorry for the confusion. My question regarding a support channel still stands.

**Comment by johnleider** [comment]
A gitter chat is probably the best route, I'll look into that today. I have vuetify prepped to update to 2.1.7+, was just waiting for the next release. Will be launching that today.

**Comment by johnleider** [comment]
Updated README with gitter info.
