### ISSUE TITLE
[Bug Report] Support large lists of tabs on sections of a page (i.e. doesn't take up the whole width of the screen and still needs to be scrollable)

### ISSUE THREAD

**Issue by ch-lukas** [vuetifyjs/vuetify#4204]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Google Chrome
**OS:** Mac OS 10.13.4

### Steps to reproduce
1. Click on right most tab

### Expected Behavior
It should scroll across and show the next tab (i.e. tabs should go up to 'news 10')

### Actual Behavior
No scrolling

### Reproduction Link
[https://codepen.io/chluke/pen/Wyrpxa](https://codepen.io/chluke/pen/Wyrpxa)

### Other comments
Currently the scrolling of the tabs seems to work best when it occupies the full width of the screen. There are occasions when you might only use part of the screen. For example, on mobiles you could have a clickable navigation drawer, but on PC's you have it permanently shown - so the tabs in this chase only occupy: Screen width - 300px (drawer). This means that the "tab-wrapper" transform: translateX(-XXXXpx); is now always 300px off.

**Comment by KaelWD** [comment]
Do you have a screenshot or something? At 1080p the last tab **is** "news 10", and if I shrink the window down then there's no difference with or without the "Important Stuff" div.

**Comment by ch-luke** [comment]
Updated the repo to handle a larger screen (up to "new 20" now).

Click of news 6 doesn't adjust

<img width="869" alt="screen shot 2018-06-05 at 12 26 32 pm" src="https://user-images.githubusercontent.com/20023331/40973475-44900ddc-68bc-11e8-8a5f-02a21b03e73f.png">


Also tried to click on the next tab - news 7
<img width="195" alt="screen shot 2018-06-05 at 12 29 36 pm" src="https://user-images.githubusercontent.com/20023331/40973442-2d59bbae-68bc-11e8-9ad8-0430a258cf48.png">

**Comment by KaelWD** [comment]
#3901 will solve the first bit, but I think it could just default as a small offset rather than centering the tab. The second bit is definitely a bug.

**Comment by jacekkarczmarczyk** [comment]
I'm pretty sure that #3901 fixes also the offset thing

**Comment by johnleider** [comment]
A simplified reproduction: https://codepen.io/johnjleider/pen/MxYXEe

Haven't been able to pin down the exact cause. It does appear to be flexbox related.

**Comment by johnleider** [comment]
Fixed in f22d754
