### ISSUE TITLE
[Feature Request] Improved swiping / scrolling of Tabs

### ISSUE THREAD

**Issue by ch-lukas** [vuetifyjs/vuetify#4205]
### Problem to solve
The current swiping action of tabs seems to scroll several items across and then selects the item you touched, which don't feel 100% natural to me.

### Proposed solution
I would love the following to happen instead:

1. Big swipe - scrolls to end or beginning of tabs and aids as a quick preview to users
2. Small swipe - scrolls a few items ahead or behind
3. Seperate swipe from item select (rather have it as two actions. also a component option to switch on / off would be great)
4. Add an option to set scroll distance when a tab is clicked (e.g. for me the whole tab + min 50px should be always shown). This is important as sometimes you click on the tab at the end of the viewable screen and then it is moved fully into focus, but you are not aware there are more items to scroll too.

**Comment by KaelWD** [comment]
This sounds like a bug report, simply swiping on the tabs bar should only scroll. Could you update the issue with the bug report template and a reproduction link? I don't see anything like this happening on the documentation with android chrome.

**Comment by ch-luke** [comment]
Just to clarify, you are saying:

Point 1 /2 - Do not conform to standard material design principles 
Point 3 - Could be a bug - should currently work

Point 4 still sounds like a feature request to me does it not? For example in the screenshot below, it is not 100% clear that there are tabs passed "news 6"

<img width="869" alt="screen shot 2018-06-05 at 12 26 32 pm" src="https://user-images.githubusercontent.com/20023331/40974322-24119230-68bf-11e8-8bf9-4f744932c500.png">

**Comment by jacekkarczmarczyk** [comment]
@ch-luke can you please check your issues with https://github.com/vuetifyjs/vuetify/pull/3901 and if it fixes any of them just add the comment. Ty.

**Comment by ch-luke** [comment]
1/2 Ill get back to you on this as I need to try out a few more things. But generally in iphone/android apps the faster you swipe the faster & further you scroll ... even to the end of lists at times. I'm haven't tested on real devices, but on emulators I didn't seem to see this with Vuetify.

#3901 - center-active-tab, sounds like a good idea and will read through the code (& comment there).  But you might not want to centre every tab. For example, the first tabs are usually at the beginning / left of the page and don't need centring  (and any unnecessary movement could block user focus and be frustrating ... think autism...). 'center-active-tab' for only the clicked on overflowing tab could be great and similar to my 4th point of being able to control how far the overflowed tab scrolls back into view.

Will get back to you guys ...

**Comment by jacekkarczmarczyk** [comment]
It doesn't center most rights/left tabs, just the middle ones. But it doesn't matter now, i just wanted to know if it fixes any of your issues (without setting `center-active-tab` prop to true)

**Comment by johnleider** [comment]
We will be exploring this in the base component that is replacing this functionality. https://github.com/vuetifyjs/vuetify/pull/4979

**Comment by johnleider** [comment]
The current `v-slide-group` component was my resolution for this request. We have plans to improve this even further in v3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
