### ISSUE TITLE
[Feature Request] Tabs - add event to tracks size changes and auto trigger 'onResize' method

### ISSUE THREAD

**Issue by ch-lukas** [vuetifyjs/vuetify#4206]
### Problem to solve
For example, if you have tabs on a dialog box and then resize the dialog the tabs do not auto resize and then are misaligned. Refer to pictures below.

Before resize:

<img width="699" alt="screen shot 2018-06-05 at 11 42 50 am" src="https://user-images.githubusercontent.com/20023331/40972525-df801e4e-68b8-11e8-8f16-46ce96a15bbd.png">

After resize:

<img width="718" alt="screen shot 2018-06-05 at 11 43 25 am" src="https://user-images.githubusercontent.com/20023331/40972622-385b3e04-68b9-11e8-93e0-7a7692fd44b0.png">

### Proposed solution
There is a tabs method called onResize which seems to do the job.  You could create an event to track size changes and auto trigger it.

**Comment by pegiadise** [comment]
Same behaviour is noticed in dynamic change of tab text (e.g. locale change)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/4733#issuecomment-408421259
