### ISSUE TITLE
Validate on input change as well on blur

### ISSUE THREAD

**Issue by leonardoarroyo** [vuetifyjs/vuetify#421]
How should we go about validating rules as the input changes and not only on blur event?

**Comment by mfferreira** [comment]
@leonardoarroyo use the input's @change event to call validate()

**Comment by johnleider** [comment]
Text field already validates on any [change](https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/TextField.js#L106).

**Comment by leonardoarroyo** [comment]
Just in case anyone has the same problem, the reason why it wasn't triggering validate on value change was because my v-model variable wasn't declared at my `data` method.
