### ISSUE TITLE
[Bug Report] Autocomplete Backspace defaults to first item after selection change

### ISSUE THREAD

**Issue by darvi-sh** [vuetifyjs/vuetify#4212]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.62
**OS:** Mac OS 10.13.5

### Steps to reproduce
- focus on autocomplete dropdown
- start typing any name, e.g. Arizona
- add any other character (you'll see a disabled `no data available` label)
- press backspace
- press enter

### Expected Behavior
after pressing backspace only the matched item should be shown and highlighted
after pressing enter also that only item has to be selected

### Actual Behavior
the entire list appears, the initially selected item gets highlighted, but after pressing enter the first item in the list will be chosen instead

### Reproduction Link
[https://codepen.io/darvishzadeh/pen/ERKzZN](https://codepen.io/darvishzadeh/pen/ERKzZN)

### Other comments
https://vuetifyjs.com/en/components/selects#example-autocomplete
Example is exactly taken from vuetify.com website

**Comment by darvishzadeh** [comment]
Cool. It's is still buggy though.

![](https://media.giphy.com/media/8mBRdRYYZckTgAFEQG/giphy.gif)

As you can see typing through the name, filters through the list, but once going back from an extra character to original selection, it shows the entire list. I'm not sure if this is expected.

**Comment by KaelWD** [comment]
Hmm, it's supposed to do that so you can select a different item without having to clear the search first, but should probably stop if you start typing again. 

![2018-06-06_02-36-27](https://user-images.githubusercontent.com/16421948/40989848-708681a2-6932-11e8-81cf-42d6b52eae4c.gif)

**Comment by didinahmadi** [comment]
yes I got this too, still buggy
