### ISSUE TITLE
[Bug Report] Icon in v-list-tile gets incorrect color

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4216]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
1. Create a new `v-list`
2. Create a `v-list-tile` with an icon
2. Set the `color` or `disabled` prop on a `v-list-tile`

### Expected Behavior
The icon should inherit the color from the list tile.

### Actual Behavior
Icon always get default color

### Reproduction Link
[https://codepen.io/anon/pen/xzOywV](https://codepen.io/anon/pen/xzOywV)

### Other comments
The following CSS rule should fix it:
```
.v-list {
  &__tile {
    .v-icon {
      color: inherit;
    }
  }
}
```

**Comment by johnleider** [comment]
This bug is also present in v1.0.19. Will fix in 1.1.x

**Comment by johnleider** [comment]
Recommended fix for v2.x

```sass
  // VListItem.sass line 40
  &--disabled
    pointer-events: none

    .v-icon
      color: inherit
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
