### ISSUE TITLE
[Bug Report] Autocomplete should display no-data-text for empty items prop

### ISSUE THREAD

**Issue by elgutierrez** [vuetifyjs/vuetify#4217]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.10
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.1

### Steps to reproduce
1. Create an `v-autocomplete` component
2. Add slots like `selection` and `item`
3. Set the prop `items` to `[]` 

### Expected Behavior
It should display `no-data-text`

### Actual Behavior
Showing a list with only one item, which has no data in it

### Reproduction Link
[https://codepen.io/anon/pen/VdjVqJ](https://codepen.io/anon/pen/VdjVqJ)

**Comment by Tsaukpaetra** [comment]
Following this.

I think this may be related to why my conversion from `v-select overflow` to `v-overflow-btn` is broken, showing one empty iteration of the selection slot instead of the selected items / label text.
