### ISSUE TITLE
How to disable or make v-tab invisible?

### ISSUE THREAD

**Issue by farebord** [vuetifyjs/vuetify#4219]
```
<template>
  <div>
    <v-tabs
      v-model="active"
      color="cyan"
      dark
      slider-color="yellow"
    >
      <v-tab
        v-for="n in 3"
        :key="n"
        ripple
      >
        Item {{ n }}
      </v-tab>
      <v-tab-item
        v-for="n in 3"
        :key="n"
      >
        <v-card flat>
          <v-card-text>{{ text }}</v-card-text>
        </v-card>
      </v-tab-item>
    </v-tabs>

    <div class="text-xs-center mt-3">
      <v-btn @click.native="next">next tab</v-btn>
    </div>
  </div>
</template>
```

I just want to remove this and see the rest:

```
      <v-tab
        v-for="n in 3"
        :key="n"
        ripple
      >
        Item {{ n }}
      </v-tab>
```

I just want the tab-item and button to navigate between them. I've tried using v-show but they hide the v-tab-item aswell.

Thanks.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by sureshvv** [comment]
Adding class="d-none" worked for me

**Comment by DesKevinMendez** [comment]
You can use this
`mounted () {
      const deleteTabsShow = document.getElementsByClassName('v-tabs__wrapper')[0]
      deleteTabsShow.remove();
    }`
