### ISSUE TITLE
Form Validator?

### ISSUE THREAD

**Issue by thearabbit** [vuetifyjs/vuetify#422]
I base on `Meteor`, and use `Bootstrap + AutoForm of Blaze` [AutoForm](https://github.com/aldeed/meteor-autoform)
But now I would to try `Meteor + Vuetify`, but have problem with `Form Validator`.
Please help me.

**Comment by smares** [comment]
I guess you can use the chat room (https://gitter.im/vuetifyjs/Lobby) for that. Especially since you didn't write what exactly you need help with.

**Comment by johnleider** [comment]
@smares is correct, this would be a question for chat.

**Comment by thearabbit** [comment]
Thanks, I will do

**Comment by thearabbit** [comment]
Now I tried to use `gitter`, how to find, search, or issue/reply on topic?
I don't understand?
