### ISSUE TITLE
[Bug Report] V-select no-data slot won't work with combobox/tags

### ISSUE THREAD

**Issue by creativenoobie** [vuetifyjs/vuetify#4220]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Ubuntu undefined

### Steps to reproduce
Click on Select Option.
Type a new options like "Material" etc

### Expected Behavior
A clickable dropdown (For callback functionality) with no-data slot component.
I wanted to use list component in order to guide user to create a new option.

### Actual Behavior
No dropdown is displayed when using tag/combobox props. I know we can add options but I guess No data slot should be available in order to personalize user's experience.

### Reproduction Link
[https://codepen.io/anon/pen/ZRpQRV?&editors=101](https://codepen.io/anon/pen/ZRpQRV?&editors=101)

### Other comments
Also, "Enter" Key won't work after typing a new option.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VAutocomplete/VAutocomplete.js#L131

**Comment by creativenoobie** [comment]
@jacekkarczmarczyk Was that code a hint or something?

**Comment by jacekkarczmarczyk** [comment]
These lines are responsible for not showing the menu (with no-data), just a clue for anyone who wants to fix the issue
