### ISSUE TITLE
[Feature Request]  .v-input__slot behavior and cursor

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4222]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Compare the click on the ` .v-input__slot` padding:
https://codepen.io/anon/pen/QxKEON?&editors=101
https://codepen.io/anon/pen/MXjeOm?&editors=101

### Expected Behavior
Previously behavior do not focus on input when click on the ` .v-input__slot`.
I think the 1.1 behavior is better, but it can have a text cursor.

### Actual Behavior
It focus on input when click on the ` .v-input__slot`.

### Reproduction Link
[https://codepen.io/anon/pen/MXjeOm?&editors=101](https://codepen.io/anon/pen/MXjeOm?&editors=101)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
