### ISSUE TITLE
[Bug Report] goTo() goes to the top of the page instead of the dom element

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#4226]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Scroll to bottom, click the red/green button

### Expected Behavior
Both button should scroll to the "test"

### Actual Behavior
Red button scrolls to the top of the page

### Reproduction Link
[https://codepen.io/anon/pen/zaKyZm?editors=1000](https://codepen.io/anon/pen/zaKyZm?editors=1000)

**Comment by KaelWD** [comment]
#3638 should've updated this bit too: https://github.com/vuetifyjs/vuetify/blob/c646c66409c5753c65f028c191b71c87f8318c2a/src/components/Vuetify/util/goTo.js#L38-L42
