### ISSUE TITLE
[Bug Report] CSS utility classes conflict between "Visibility" and "Display"

### ISSUE THREAD

**Issue by KevinNTH** [vuetifyjs/vuetify#4229]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.62
**OS:** Linux x86_64

### Steps to reproduce
On an element, add both classes `hidden-md-and-up` and `d-block`.
e.g: `<p class="hidden-md-and-up d-block">Hello, world!</p>`

### Expected Behavior
`hidden-*` classes should be top priority

### Actual Behavior
Conflicts between `hidden-*` and `d-*`

### Reproduction Link
[https://codepen.io/KevinNTH/pen/BVLEjK](https://codepen.io/KevinNTH/pen/BVLEjK)

### Other comments
Regression from Vuetify 0.17 => `d-*` did not have `!important` instruction compared to now.

**Comment by KaelWD** [comment]
Fixed in 2.0
