### ISSUE TITLE
[Feature Request] Async validation rules for inputs

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#4231]
### Problem to solve
This feature would allow to:  
* Debounce text fields validation so that it's not done after each user keystroke (resulting in bad UX)
* Any other async validation (eg. a http request to verify an URL exists)

[This codepen](https://codepen.io/bviala/pen/WYeVyP) shows: 
* What you can do with current text field validation  
* What does not work but would be great to have  
* Workaround to have the expected behaviour  

### Proposed solution
Make the "rules" prop accept async functions like suggested in the codepen.
Bonus: Make a debounce prop for the text field component so that the user do not have to make his own debounced functions with Lodash

**Comment by KaelWD** [comment]
Your second example works if you actually define everything properly: <https://codepen.io/anon/pen/oyoQYP?editors=1010>

**Comment by ecmel** [comment]
It does not work like example 3.

Try entering 3 chars rapidly. Second example does not show error but third does.

**Comment by bviala** [comment]
@KaelWD No it doesn't. 
Check your codepen again: if you quickly type less than 5 chars then wait, no error message pops. Then if you add more chars, the error message will pop, when you're input is now actually ok.
It's even worse than first example.

**Comment by dneeleman** [comment]
Would really love the possibility. We want to validate all our individual inputs with our API. Hope this feature will be put on the roadmap.

**Comment by dneeleman** [comment]
Anyone with a solid solution? Currently trying to figure out a better solution after our first approach. But we need the validate-on-blur for our UX, which makes it a bit harder.

**Comment by ilyakamens** [comment]
I'd also love this to do things like validate that an email address isn't in use on blur.

**Comment by joshuaryoung** [comment]
Also waiting on this...

**Comment by bviala** [comment]
I submitted this quite some time ago, I no longer think it's relevant.

If you have sparse needs for async validation, building it like in the 3rd example I provided works just fine.
If you have stronger validation needs, libraries like Vuelidate or Vee-Validate are the way to go, and the Vuetify doc provides [examples](https://vuetifyjs.com/en/components/forms/#vuelidate) for them.

In fact I believe the built-in validation is a gadget that bloats the framework for no good reason. The `error-messages` prop is all what's really needed.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by vciloglu** [comment]
if you are getting the problem in vuetify v3 I solved the problem as follows.

`:rules="[async (v) => await checkFileHandler(v)]"`

You can do asynchronous validation by using await in the `checkFileHandler ` method.
