### ISSUE TITLE
[Bug Report] Navigation Drawer - Stateless prop doesn't disable touch gestures

### ISSUE THREAD

**Issue by olivercolas** [vuetifyjs/vuetify#4233]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Opera 53.0.2907.68, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Open the codepen provided on mobile, or using a browser with gestures enabled
2. Click on the menu icon to activate the parent drawer
3. Use a `right-to-left` swiping gesture to close the parent drawer
4. Re-open the parent drawer by clicking on the menu icon (nested drawer is now hidden)
5. Use a `left-to-right` swiping gesture to show the nested drawer

### Expected Behavior
A nested `<v-navigation-drawer>` with `stateless` prop should not hide or show based on gestures.

### Actual Behavior
A nested `<v-navigation-drawer>` with `stateless` prop applied hides or shows when a swiping gesture is used

### Reproduction Link
[https://codepen.io/ocolas/pen/ZRBEXB](https://codepen.io/ocolas/pen/ZRBEXB)

### Other comments
Combined drawers, one navigation-drawer inside another. 
The nested navigation-drawer has props `mini-variant, stateless, value="true"`

**Comment by KaelWD** [comment]
Unable to reproduce on Android Chrome.

**Comment by olivercolas** [comment]
I just tested it on Chrome 66.0.3359.158 and the bug is present. Basically the nested drawer (in red) disappears after step 3, and to bring it back you have to use swipe the opposite way as mentioned in step 5.

My android system is 6.0.1.

**Comment by KaelWD** [comment]
Just tried again, it only happens if you swipe over the grey drawer. Swiping further to the right only closes the parent.

**Comment by olivercolas** [comment]
I actually didn't realize that was the case, good find. 

For my use case I was always swiping the grey drawer because on mobile it extends to pretty much 80% of the screen width so it felt more natural to swipe over it. Anyways thanks for the clarification.

**Comment by haris44** [comment]
Same problem. I just want to reduce (to mini) the navigation drawer when I swipe left on the device.
Any solutions ?
