### ISSUE TITLE
[Bug Report] Auto-grow doesn't work anymore

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#4237]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Create a v-textarea field with the attribute auto-grow.

### Expected Behavior
Textarea should grow with input or show scrollbars if readonly/disabled.

### Actual Behavior
Field doesn't grow and no scrollbar shown.

### Reproduction Link
[https://codepen.io/anon/pen/YvpEdR](https://codepen.io/anon/pen/YvpEdR)

**Comment by KaelWD** [comment]
Fixed by #4257
