### ISSUE TITLE
[Bug Report] Time picker result is always in 24-hour format even when format is set to "ampm"

### ISSUE THREAD

**Issue by shravan-kaushik** [vuetifyjs/vuetify#4240]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
The code is straight from the ["Time pickers - In dialog and menu" example](https://vuetifyjs.com/en/components/time-pickers#example-time-dialog-and-menu), and everything is same except that the `format` is explicitly set to `ampm`, even though it is probably redundant.

### Expected Behavior
Expected the return value from the time picker to be in AM/PM format

### Actual Behavior
The return value is always in 24-hour format

### Reproduction Link
[https://codepen.io/shravankaushik/pen/KeNBRd](https://codepen.io/shravankaushik/pen/KeNBRd)

**Comment by KaelWD** [comment]
`ampm` is the default, the only other option is `24hr`: https://codepen.io/anon/pen/dKOqbQ?editors=1010

v-time-picker always returns a 24-hour formatted time, the prop is just for how the picker is displayed.

**Comment by jacekkarczmarczyk** [comment]
This is intended, `format` prop defines the way the picker is displayed but has no effect on the format of the data which is always hh:mm

**Comment by shravan-kaushik** [comment]
Oh, I didn't know that. It's not stated in the docs though, and it seems pretty semantically obvious for a `ampm` formatted picker to return an AM/PM value.

**Comment by KaelWD** [comment]
It isn't super clear, but the example below the one you linked shows `24hr` and the api table shows the default value. 

Currently all date/time formats are ISO 8601, I don't think there's any plans to change that.

**Comment by shravan-kaushik** [comment]
I understand. Perhaps making it a little more explicit in the docs won't hurt. Also, storing the dates internally as ISO 8601 is a good idea, I was just expecting a builtin to get the date in the required format, especially since in the earlier versions `v-time-picker` did produce such output.

**Comment by jacekkarczmarczyk** [comment]
Could you create an issue in docs repo? Ty

**Comment by shravan-kaushik** [comment]
Done!
