### ISSUE TITLE
[Bug Report] vSlider loop animation problem

### ISSUE THREAD

**Issue by hjlld** [vuetifyjs/vuetify#4243]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.79
**OS:** Windows 10

### Steps to reproduce
open link: https://codepen.io/anon/pen/Qxdboz
play the video
pay attention to the vSlider, especially when the video is over and loop from the beginning.

### Expected Behavior
When vSlider is used as a video player or an animation progress controller, when the video/animation is set to loop mode, when the video/animation is done, which should be played from the beginning, the progress controller should start again from the left extreme.

### Actual Behavior
Actually, vSlider makes the thumb roll back from the right to the left, which is an animation effect, but it can't reach in time following the video/animation, you can see the vSlider never starts from 0.

### Reproduction Link
https://codepen.io/anon/pen/Qxdboz

### Other comments
vSlider should have a mode for being used as a video player or an animation progress controller

**Comment by jacekkarczmarczyk** [comment]
This is not a valid reproduction, please use codepen or codesandbox and provided minimal code that reproduces the bug

**Comment by hjlld** [comment]
@jacekkarczmarczyk already reproduced with codepen

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/anon/pen/LrxpGy?editors=1100

**Comment by hjlld** [comment]
@jacekkarczmarczyk you're very appreciated!

**Comment by hjlld** [comment]
if you can add it as a prop of vSlider, it will be great.

**Comment by jacekkarczmarczyk** [comment]
Keep in mind that it won't work in 1.1
