### ISSUE TITLE
[Bug Report] $vuetify.goto - DOMElement as scrolling target throws error in IE11

### ISSUE THREAD

**Issue by peacefulseeker** [vuetifyjs/vuetify#4245]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
 - Open the IE11 browser and try to select DOMElement as scrolling target
 - Click "Scroll"
 - Open the console and see the error - "[Vuetify] Target must be a Selector/Number/DOMElement/VueComponent, received  instead."

### Expected Behavior
Scrolling to target

### Actual Behavior
Scrolling is broken

### Reproduction Link
[https://codepen.io/peacefulseeker/pen/gKGqGZ?editors=1011
](https://codepen.io/peacefulseeker/pen/gKGqGZ?editors=1011
)

**Comment by jacekkarczmarczyk** [comment]
Missing reproduction

**Comment by peacefulseeker** [comment]
@jacekkarczmarczyk, ou, I thought copied correctly. 
There is an example from an official Vuetify page.
I have amended my issue description.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/src/components/Vuetify/util/goTo.js#L38

IE11 doesn't support `window.scrollY`

**Comment by jacekkarczmarczyk** [comment]
The error message has to do something with the method of importing Vue in codepen, it doesn't appear when running dev server

**Comment by KaelWD** [comment]
Because 1.0 had error checking here instead:
https://github.com/vuetifyjs/vuetify/blob/98c5c652bdba3661ada7f85db9aecee9e9aa3eb9/src/components/Vuetify/util/goTo.js#L66-L70

**Comment by jacekkarczmarczyk** [comment]
Update to 1.1 (or maybe this PR could go to 1.0, but i'm not sure if we're going to release more 1.0 patches)

**Comment by jacekkarczmarczyk** [comment]
Or calcutate the offset by yourself and use it as a target
