### ISSUE TITLE
[Bug Report] v-text-field type=date 'date' mask should depends on locale. Now it totally prevents input

### ISSUE THREAD

**Issue by imShara** [vuetifyjs/vuetify#4246]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.17-beta.0
**Browsers:** Firefox 60.0
**OS:** Linux x86_64

### Steps to reproduce
Use browser with cyrillyc locale

### Expected Behavior
Date mask should depend on locale. E.g with en_US date mask should be ##/##/####, but with ru_RU it should be ##.##.####

### Actual Behavior
Now it totally blocks input from internal browser's datepicker. It's so important, because EN-locale developer can't see this problem and use both 'mask' and 'type' parameters, but for RU-locale user, app will be totally broken.

![Vuetify date mask prevents input](https://i.imgur.com/Zx6lQLs.gif)

### Reproduction Link
[https://jsfiddle.net/zd06cweh/](https://jsfiddle.net/zd06cweh/)

### Other comments
I don't dig how date localized in different languages and how it fills in different browsers and I think that 'mask=date' parameter shoud be ignored if 'type=date' passed.

**Comment by jacekkarczmarczyk** [comment]
I'd rather add an warning if the mask is used with date/time/color/file/... input or even just add information in docs. Definitely having a mask that depends on locale is not a thing

**Comment by KaelWD** [comment]
Yeah my response to this would just be "don't do that".

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3282
