### ISSUE TITLE
Textfield focus() does not focus

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#425]
### Steps to reproduce
Visit codepen.io/anon/pen/mmrEGK and click on the button

### Versions
Vuetify 0.11.0

### What is expected ?
Clicking on the button should focus the textfield

### What is actually happening ?
Only the focus decoration is applied to the textfield, but the actual input is not focused

### Reproduction Link
codepen.io/anon/pen/mmrEGK

**Comment by milleraa** [comment]
I have same issue in 0.12.2. 
Small detail: the v-text-field is placed into v-dialog. And I call 
```
this.$refs.loginTxt.focus();
this.loginDialog = true;
```

**Comment by asoltys** [comment]
Just to follow up on that last comment and save some time for anyone else who shows up here trying to focus a v-text-field in a dialog, the solution is to wrap the focus() call in a nextTick() as described here: https://github.com/vuetifyjs/vuetify/issues/1587#issuecomment-326967711

**Comment by jofftiquez** [comment]
@asoltys thanks.
