### ISSUE TITLE
[Bug Report] v-layout in column mode gives v-flex a max-width when it shouldn't

### ISSUE THREAD

**Issue by Fugiman** [vuetifyjs/vuetify#4258]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Make a `<v-flex xs6>` inside a `<v-layout column>`

### Expected Behavior
The flex element should have a max-width of 100%

### Actual Behavior
The flex element has a max-width of 50%

### Reproduction Link
[https://codepen.io/fugiman/pen/GGrBdX](https://codepen.io/fugiman/pen/GGrBdX)

### Other comments
Regression from 1.0.19

**Comment by KaelWD** [comment]
a4b5ce8826063cf86f62d71fa035971cbdf0b516

**Comment by bitsmakerde** [comment]
At version 1.3.14 I have the same error.

` <v-layout 
      column
    >
      <v-flex 
        md4 
      >
        <div class="red">center1</div>
      </v-flex>
      <v-flex 
        md4
      >
        <div class="red">center2</div>
      </v-flex>
    </v-layout>`

The width is 100% and not 33%.

Please reopen the bug.

Thanks

**Comment by tripish** [comment]
I'm also having the same issue with 1.4.1.
