### ISSUE TITLE
[Feature Request] Autoselect the only option in a required v-select

### ISSUE THREAD

**Issue by stratosgear** [vuetifyjs/vuetify#4263]
### Problem to solve
In case the value of a v-select is required, and the number of available options is exactly one, that value should be autoselected.

### Proposed solution
Either select the value automatically, or provide a v-select option to turn this feature on.

**Comment by KaelWD** [comment]
I feel like I've seen this exact request before.

**Comment by KaelWD** [comment]
It's very simple to do this yourself.

**Comment by stratosgear** [comment]
I bet I could, but if I have to do it for many such components in my app, it will quickly get tiring.

Or, do you mean to say I have to create my own component, extending v-select, for such a simple operation...?

**Comment by KaelWD** [comment]
Yes, I don't recommend extending it though. 

https://zendev.com/2018/05/31/transparent-wrapper-components-in-vue.html
