### ISSUE TITLE
[Bug Report] selects with array values are not working

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#4264]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Use items where a value is of type array.

### Expected Behavior
It is working in Vuetify 1.0.X.

### Actual Behavior
Items are showing but are not selectable.

### Reproduction Link
[https://codepen.io/SeregPie/pen/RJKzaL](https://codepen.io/SeregPie/pen/RJKzaL)

**Comment by jacekkarczmarczyk** [comment]
objects are fine, just problem with array https://codepen.io/anon/pen/bKgPgQ

**Comment by jacekkarczmarczyk** [comment]
unable to push anything atm, but this should help

```diff
--- a/src/components/VSelect/VSelect.js
+++ b/src/components/VSelect/VSelect.js
@@ -647,7 +647,7 @@ export default {
     },
     setSelectedItems () {
       const selectedItems = []
-      const values = Array.isArray(this.internalValue)
+      const values = this.isMulti
         ? this.internalValue
         : [this.internalValue]
```
