### ISSUE TITLE
[Task] Update tests to use new icon events

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#4265]
See #4254

There's like 1000000 tests using `*-icon-cb` props, these all need updating to use `@click:*` events instead. The `NODE_ENV` check in util/console can then be removed.

**Comment by ebisbe** [comment]
@KaelWD I'm trying to start with this issue but I'm not sure I've made it the right way. I've found that the callback it's only triggered when I check if it's set up in the listeners.
Is that right? 

https://github.com/ebisbe/vuetify/commit/14232343584f57ce0e70d8d572b16fffd72d6a5b

If that's right that's means that there was a bug, right?

thanks

**Comment by KaelWD** [comment]
No, that's correct. `wrapper.vm.$on('click:append', cb)` should work without any changes to the component itself.

**Comment by ebisbe** [comment]
With `wrapper.vm.$on('click:append', cb) ` it's not working. The only way I've managed to make it work is like the commit. I'll try other components.

**Comment by KaelWD** [comment]
ok yeah just realised why that won't work. Using `listeners` like you did before does register them properly, but they don't get triggered on emit for some reason. You will see that the event is handled correctly though if you add a log
![image](https://user-images.githubusercontent.com/16421948/42453627-a9d4942c-83d0-11e8-97ae-da70ada01604.png)

And using *both* `listeners` and `wrapper.vm.$on` works too. Seems like this might be a bug with avoriaz, `listeners` are never triggered even with simpler event names.

**Comment by ebisbe** [comment]
I've made a Pr. Using listeners won't call any cb function because they are ignored. I've made an update inside de on event.
