### ISSUE TITLE
[Bug Report] Appearing of hint message on first choose of radio item

### ISSUE THREAD

**Issue by DmytroKurapin** [vuetifyjs/vuetify#4266]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Make first select any of radio item

### Expected Behavior
I should not see hint (error message) for milliseconds

### Actual Behavior
Hint message appears for milliseconds under radio group.

### Reproduction Link
[https://codepen.io/anon/pen/pKNrGV](https://codepen.io/anon/pen/pKNrGV)

### Other comments
Sometimes in order to reproduce it, refresh the page few times is needed.

**Comment by johnleider** [comment]
This is resolved as of v2.
