### ISSUE TITLE
[Feature Request] Support a limited max-width, centered application layout (for desktops)

### ISSUE THREAD

**Issue by cb109** [vuetifyjs/vuetify#4267]
### Problem to solve
Vuetify by default layouts the application to use the full width of the browser, placing the drawer on the far left or right. On large screens one may prefer to limit the application to lets say `1280px` in width and center everything (with updated positioning for all fixed elements like drawer, toolbar, floating-action-buttons, snackbar etc.) accordingly.

Please see this stackoverflow question including pictures from `@nirmal`: https://stackoverflow.com/questions/49611926

#### Current
![](https://i.stack.imgur.com/jnS4c.png)

#### Desired
![](https://i.stack.imgur.com/xRjUe.png)

This can improve usability of the application quite a bit as it improves overview, shortens paths the user's mouse has to travel to reach the menu etc. It is kind of what people are used to on desktops and makes the application feel more integrated on that platform as opposed to a mobile-first, desktop-second look and feel.

### Proposed solution
Add props/options to set global `max-width` and `centered` attributes to the application config or `v-app` element, which allow to easily achieve the look and feel described above.

---

I could not find an existing ticket for this, but if there is one please feel free to close this. This topic has come up a number of times on the Discord channel recently which is why I created this issue. My current workaround for this is lots of custom CSS with calculated max-widths and position offsets and they are a pain to maintain.

### Todos
- [x] Add a codepen to play around with containing the above elements - This is simply the complex layout example from the docs https://codepen.io/cb109/pen/pONRBo

**Comment by cb109** [comment]
any comments? has this been discussed/decided before? I'd be willing to implement this, but only if you guys are okay with it, also some recommended approach would be very welcome

**Comment by johnleider** [comment]
I will explore this when I get to the application improvements slated for 2.0

**Comment by jacekkarczmarczyk** [comment]
That's related to <https://github.com/vuetifyjs/vuetify/issues/4742> - if we implement #4742 then you could just create centered div and put your app into this div

**Comment by cb109** [comment]
@jacekkarczmarczyk I like that approach! Define a box, put the app in the box, it adapts as much as it possibly can.

**Comment by johnleider** [comment]
What would the drawer look like when hidden in this layout?

I didn't get around to making some of the layout changes I had initially intended, but the above would still be a concern.  In light of that, this unfortunately did not make the cut for v2.0 but I'd like to keep the conversation open.

**Comment by cb109** [comment]
@johnleider Thanks for getting back to this. For my desktop-mode workaround I realizied that the drawer's "hide" feature basically just moves it to the left and out of screen, which of course is still in the screen when the left app border is moved like in the image above. My quickfix for that was to disable the animation and just hide the drawer, which I think is a bandaid-solution at best:
```stylus
.desktop-mode
&.v-navigation-drawer
  /* Don't animate the transition (it would look weird when coming
     back in) and make sure the drawer is hidden and unclickable. */
  transition-duration: 0s !important
  &.v-navigation-drawer--close
   .v-navigation-drawer:not(.v-navigation-drawer--right)
    z-index: -9999
    opacity: 0
```
Looks like this:
![Peek 2019-06-21 09-03](https://user-images.githubusercontent.com/6052590/59904349-834a2d00-9403-11e9-81a9-011e802f6295.gif)

If possible I'd like to keep the move-to-left animation while being cut off at the app border. That may be possible with animation a `clip-path` :man_shrugging: 

Btw: The offsets needed for the fixed elements differ depending on OS + browser combination, seemingly due to how the scrollbar is incorporated (as either 0, 8 or 16px width).

**Comment by KaelWD** [comment]
overflow: hidden would do that.

**Comment by VietKhangLH** [comment]
any news ?

**Comment by CesarGomezTissini** [comment]
Recall for this. We wanna to make our ecommerce with the same layout in desktop but centered one, looking like a mobile.

**Comment by johnleider** [comment]
This is resolved with the layout update for Vuetify 3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by vmihailenco** [comment]
While there is `max-width` prop on `v-layout`, it still [does not help](https://play.vuetifyjs.com/#eNrtlsFOhDAQhl9l0rMVEi9mg5sYz/oC4qFLu1DTlqadshDju1sKdDXx6MlwKfmn38z8cPl5/SDeNcWjtbdDEORAKhTaKobiWBuAaqCKTX1A0GykF8mxe6jJfVnWBBrFvI/K9cFwwWF9Us1Bj5QF7GuShqQxzFp6Yg5QohKxK25UsmEoewOxHtGqyFRsy42GDbJNHOWOXcR8OV8t5qTHrHOFyvgSedNLHgDLgHVXJq8D1+rmOsrftmdrmslVQP4anJ6VGIEp2RraCIPCwXvwKM/TKmuy9XickkMtDe2EbDs8wF1Z2nFDsrPnuAme+thusDo5KI7LmZ3/UP+b3qmd2qmd2qm/pa6hN+faEv9zIKb8j7Iqvv0akM8bE5RKx9sXc3dtzQ==) with the initial request. 2 nested layouts work, but it breaks lots of other stuff like sticky app-bar and navigation drawers.

Any hints how to do a limited max-width, centered application layout with Vuetify 3?

**Comment by cb109** [comment]
@vmihailenco Back then on v1.5.x I did the work and defined custom style changes for all main Vuetify elements to overall tweak them into a sort of desktop layout. 

It required calculating a few positions and max-widths and overriding whatever Vuetify did by default. The example below is written in `stylus` and for v1.5.24, so it may be somewhat irrelevant by now, but hopefully it illustrates the idea. We are still using that version, so once it was setup, I didn't have to touch it anymore. 

```stylus
$drawer-width = 300px
$offset-fab-right = 24px
$offset-lg1 = 8.33%

$desktop-max-width = 100%
$desktop-max-width-fullscreen-mode = 100%
$desktop-max-width-open-drawer = 'calc(%s - %s)' % ($desktop-max-width $drawer-width)

/* Offset Expressions */
$centered-left                = 'calc((100% - %s) / 2.0)'      % ($desktop-max-width)
$centered-left-fullscreen     = 'calc((100% - %s) / 2.0)'      % ($desktop-max-width-fullscreen-mode)
$centered-left-fab            = 'calc((100% - %s) / 2.0 + %s)' % ($desktop-max-width $offset-fab-right)
$centered-left-open-drawer    = 'calc((100% - %s) / 2.0 + %s)' % ($desktop-max-width $drawer-width)

/* Desktop Defaults */
.desktop-mode

  /* Force the overall App into a centered max-width. */
  &.application
    margin: 0 auto
    max-width: $desktop-max-width

    .container
      max-width: $desktop-max-width-fullscreen-mode

  &.v-toolbar--fixed
    left: $centered-left
    max-width: $desktop-max-width

  &.v-navigation-drawer
    /* Don't animate the transition (it would look weird when coming
       back in) and make sure the drawer is hidden and unclickable. */
    transition-duration: 0s !important

    &.v-navigation-drawer--close
      z-index: -9999
      opacity: 0

    &.v-navigation-drawer--fixed
      left: $centered-left

  &.alerts
    left: $centered-left !important
    max-width: $desktop-max-width

    &.visible-drawer
      left: $centered-left-open-drawer !important
      max-width: $desktop-max-width-open-drawer

  &.v-btn--fixed
    right: $centered-left-fab
```

The styles live in a `desktopModeStyles.global.stylus` file and can be globally defined in `App.vue` by adding it like
```html
<style src="@/mixins/desktopModeStyles.global.stylus" lang="stylus"></style>
```

To turn the overrides on I assign 
```html
<v-app :class="['desktop-mode': $store.state.common.desktopMode, 'visible-drawer': $store.state.common.showDrawer]">
``` 
which are initialized based on `$vuetify.breakpoint.width`, but are then under JS control if needed.
