### ISSUE TITLE
[Feature Request] configureable VSelect deletable items when pressing Delete/BackSpace

### ISSUE THREAD

**Issue by mp3il** [vuetifyjs/vuetify#4269]
### Problem to solve
According to the source code:
https://github.com/vuetifyjs/vuetify/blob/master/src/components/VSelect/VSelect.js#L117-L129

It's not possible to disable the hardcoded feature where pressing delete/backspace using the keyboard is deleting the selected option in VSelect with Tags/multiple options.

### Proposed solution
adding a simple flag to allow override this behaivor.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
