### ISSUE TITLE
[Bug Report] Invalid label alignment with prefix in solo/single line field

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#4271]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.79
**OS:** Windows 10

### Steps to reproduce
See the link

### Expected Behavior
Label should be aligned same as placeholder

### Actual Behavior
Label is few pixels off

### Reproduction Link
[https://codepen.io/anon/pen/qKrxbv?editors=1000](https://codepen.io/anon/pen/qKrxbv?editors=1000)

**Comment by yariksav** [comment]
![image](https://user-images.githubusercontent.com/2553313/41308171-dddac37a-6e83-11e8-915a-8a36ce0c54c2.png)
Also if prefix is more than 1 symbol, input doesn't move to right

**Comment by jacekkarczmarczyk** [comment]
That's a different thing and it's intended/`wont fix` (can't find the proper issue though)
