### ISSUE TITLE
[Bug Report] V-Autocomplete in v1.1.0-beta.3 removes input text after hitting enter

### ISSUE THREAD

**Issue by maciz84** [vuetifyjs/vuetify#4273]
### Versions and Environment
**Vuetify:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Press enter in the v-autocomplete control and the typed text goes away. This behaviour would affect users who use search-input.sync as the value cannot be used for anything as it would yield in a null value being passed.

### Expected Behavior
As it was in V1.0.19 when using the v-select. The input value should be retained on enter for binding and for UI purposes. Please see pen below:

https://codepen.io/maciz84/pen/JZWZVj?&editors=101

### Actual Behavior
When pressing enter the text/input value is lost thus rendering the use of the control against queryable datasource less effective on some use cases

### Reproduction Link
[https://codepen.io/maciz84/pen/ZReRmm?&editors=101](https://codepen.io/maciz84/pen/ZReRmm?&editors=101)

**Comment by ssendev** [comment]
in rc.2 its better but not solved https://codepen.io/anon/pen/BVOOYO to reproduce the bad behavior select an item then delete the text by pressing backspace when the text is empty the text of the selected item reappears

**Comment by johnleider** [comment]
Please do not comment on closed issues. Your pasted codepen is behaving as expected. An autocomplete can't be cleared by simply using backspace.

**Comment by PSausM** [comment]
This is still bug in 1.2.5
When results are loaded from the backend, the search input in the textbox is cleared
