### ISSUE TITLE
[Bug Report] Cannot Unit Test with Jest Using Your Webpack Boilerplate

### ISSUE THREAD

**Issue by CindyConway** [vuetifyjs/vuetify#4274]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
npm run unit

### Expected Behavior
For the unit test to run

### Actual Behavior
Unknown Element error and unexpected token error (See comment for details)

### Reproduction Link
[https://github.com/CindyConway/VuetifyUnitTestFailing](https://github.com/CindyConway/VuetifyUnitTestFailing)

### Other comments
First I just ran `vue init vuetifyjs/webpack myproject.`  Then I ran the unit test for HelloWorld.vue that is included with the boilerplate.  I got an error:
`TypeError: Cannot read property 'textContent' of null at Object.<anonymous> (test/unit/specs/HelloWorld.spec.js:8:45) at new Promise (<anonymous>)at <anonymous> at process._tickCallback (internal/process/next_tick.js:182:7)`
`console.error node_modules/vue/dist/vue.runtime.common.js:589 [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <Root>)`
`console.error node_modules/vue/dist/vue.runtime.common.js:589 [Vue warn]: Unknown custom element: <v-slide-y-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.(found in <Root>)`
`console.error node_modules/vue/dist/vue.runtime.common.js:589 [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <Root>)`

I though: OK, that makes sense. Vuetify isn’t getting imported, so I imported it. Still I get an error:

`● Test suite failed to run
/Users/cindyconway/Sites/vutifytest/node_modules/vuetify/src/stylus/components/_app.styl:1({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import '../bootstrap'`
`SyntaxError: Invalid or unexpected token at new Script (vm.js:51:7)at Object.<anonymous> (node_modules/vuetify/es5/components/VApp/VApp.js:7:1)
`

It looks to me like this has something to so with preprocessing the .styl. I tried the following, but nothing fixed the issues:
https://github.com/vuetifyjs/docs/issues/92
https://facebook.github.io/jest/docs/en/webpack.html

I have included a link to a repo that reproduces the issue.

**Comment by psychosis448** [comment]
You know how tests work, right?
If you set up a vue project with vue init and unit tests, the HelloWorld.spec.js: 
```javascript
expect(vm.$el.querySelector('.hello h1').textContent)  
    .toEqual('Welcome to Your Vue.js App')
```
So it naturally fails, because vuetify replaces all this content with the blockquote...
First you would have to change it, that the assertion is correct.

Second you need to import the custom elements into your test file.
The corresponding components are:

```javascript
import { Vuetify, VApp, transitions } from 'vuetify'  
Vue.use( Vuetify, {  
  components: {  
    VApp,  
    transitions  
  }  
}) 
```

I think the next problem has something to do with `_app.styl`
As it throws the following error
```bash
/node_modules/vuetify/src/stylus/components/_app.styl:1  
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest) 
 {@import '../bootstrap'  
                                                                                             ^

    SyntaxError: Invalid or unexpected token  

      at new Script (vm.js:51:7)  
      at Object.<anonymous> (node_modules/vuetify/es5/components/VApp/VApp.js:7:1)  

```

**Comment by psychosis448** [comment]
+1

**Comment by KaelWD** [comment]
This should be opened on https://github.com/vuetifyjs/webpack/

**Comment by psychosis448** [comment]
@CindyConway 
I found a fix!
If you could permit permission to your repo, I would push the changes!

**Comment by KaelWD** [comment]
That's what PRs are for.

**Comment by psychosis448** [comment]
Got to look into that later... never done one.

**Comment by CindyConway** [comment]
@psychosis448: I like it.  It's nice that Vuetify is imported for all tests. I was finding myself importing it over and over agin. Thanks!! 

For anyone reading this:  if you just want to see the diff, here is the link to the PR https://github.com/CindyConway/VuetifyUnitTestFailing/pull/1/files.
