### ISSUE TITLE
[Bug Report] v-select Selected Item overflows in Chrome and Safari

### ISSUE THREAD

**Issue by samium** [vuetifyjs/vuetify#4275]
### Versions and Environment
**Vuetify:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Google Chrome, Safari
**OS:** Mac OS 10.13

### Steps to reproduce
1. Have a v-select inside of a grid (to give it size)
2. Have the selected item text be longer than the size of the container

### Expected Behavior
Selected item text wraps (like it is in the Firefox screenshot) or is cut off and the line underneath is not offset with extra spacing.

### Actual Behavior
In Chrome and Safari, there is extra space between the input field and the line under it.

Chrome and Safari:
![image](https://user-images.githubusercontent.com/982214/41253917-a3ff8324-6d76-11e8-9fcd-dbea5357570a.png)

Firefox:
![image](https://user-images.githubusercontent.com/982214/41253940-b79635e0-6d76-11e8-9b63-75b44182ee15.png)

### Reproduction Link
[https://codepen.io/samium/pen/BVzaaa](https://codepen.io/samium/pen/BVzaaa)

**Comment by KaelWD** [comment]
1.0.19:
![image](https://user-images.githubusercontent.com/16421948/41499334-9f966240-71c1-11e8-9ce5-74bf03aac87d.png)
