### ISSUE TITLE
[Bug Report] Bug v-icon centering

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#4277]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Windows 10

### Steps to reproduce
See codepen

### Expected Behavior
icon centered

### Actual Behavior
icon not properly centered

### Reproduction Link
[https://codepen.io/anon/pen/zaZeEM](https://codepen.io/anon/pen/zaZeEM)

**Comment by jacekkarczmarczyk** [comment]
Apparently the Material Icons font doesn't have "star_rate" icon. If you use existing icon the button is displayed correctly
https://codepen.io/anon/pen/eKWOZM

**Comment by usb248** [comment]
Yes i've solved the issue myself shortly after... but i'don't understand why they display : 
![capture](https://user-images.githubusercontent.com/7659927/41280189-a3a5649e-6e2e-11e8-8463-a8d043b69602.PNG)
