### ISSUE TITLE
[Bug Report] Fixed v-footer at wrong position when v-tabs animation

### ISSUE THREAD

**Issue by gaozhe3321** [vuetifyjs/vuetify#4283]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.2
**Browsers:** Chrome 67.0.3396.62
**OS:** Windows 10

### Steps to reproduce
put fixed v-footer into v-tab-item

### Expected Behavior
during animation the fixed footers display at bottom

### Actual Behavior
changing the tabs the footer display at wrong position when animation finished it will jump to bottom

### Reproduction Link
[https://codepen.io/anon/pen/Wyjwjj](https://codepen.io/anon/pen/Wyjwjj)

**Comment by KaelWD** [comment]
https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/
