### ISSUE TITLE
[Bug Report] v-autocomplete :search-input.sync resets value while typing

### ISSUE THREAD

**Issue by ssendev** [vuetifyjs/vuetify#4284]
### Versions and Environment
**Vuetify:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Fedora undefined

### Steps to reproduce
select something and then try to search for something else

### Expected Behavior
it should work as in previous versions

### Actual Behavior
the search field is constantly reset to the selected value

### Reproduction Link
[https://codepen.io/anon/pen/GGmEbd](https://codepen.io/anon/pen/GGmEbd)

**Comment by KaelWD** [comment]
Probably caused by #4261

**Comment by KaelWD** [comment]
Duplicate of #4273
