### ISSUE TITLE
[Bug Report] text not horizontally centered to v-progress-circular

### ISSUE THREAD

**Issue by petersutter** [vuetifyjs/vuetify#4285]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181, Mozilla Firefox, Safari
**OS:** Mac OS 10.13.5

### Steps to reproduce
1. Have a circular progress (v-progress-circular)
2. place text behind progress

### Expected Behavior
Text is horizontally centered, similar to placing text behind a v-icon

### Actual Behavior
Text behind (or in front) of the circular progress is placed almost at the bottom of the div

### Reproduction Link
[https://codepen.io/psutter/pen/MXmvVj](https://codepen.io/psutter/pen/MXmvVj)
<img width="307" alt="screen shot 2018-06-13 at 11 10 53" src="https://user-images.githubusercontent.com/5526658/41341691-97eee69e-6efa-11e8-9054-256bef347c27.png">

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/ERvjEE
