### ISSUE TITLE
Carousel controls color 

### ISSUE THREAD

**Issue by pedrost** [vuetifyjs/vuetify#4287]
So, basically i just want to change the color of the "controls", by default chevron_right and chevron_left, there is a way to do it?

I have tried changing the icons to a dark version and dit not worked as well.

I will appreciate any help.

`<v-carousel class="m-carousel" prev-icon="mdi-dark mdi-arrow-left" next-icon="mdi-dark mdi-arrow-right"> <item-component/> </v-carousel>`

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
