### ISSUE TITLE
[Bug Report] Can't escape (blur) from input field using v-text-field component with placeholder and mask (IE 11)

### ISSUE THREAD

**Issue by tsimonavicius** [vuetifyjs/vuetify#4290]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 7

### Steps to reproduce
1. Use **v-text-field** component with placeholder and mask.
2. Focus input.
3. **IMPORTANT!** Do not type anything.
4. Try to escape field using mouse or TAB.

### Expected Behavior
Input blurs.

### Actual Behavior
Input keeps focusing (can't escape).

### Reproduction Link
[https://codepen.io/anon/pen/aKwpYb](https://codepen.io/anon/pen/aKwpYb)

**Comment by SebastianBienert** [comment]
There is a working hack:
[#5225](https://github.com/vuetifyjs/vuetify/issues/5225)
