### ISSUE TITLE
[Feature Request] v-carousel auto-height

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#4295]
Problem to solve

Actually, the component v-carousel has by default height 500px. We can change this with style attribut (and I've seen directly via a prop in a next version) but in the case I want to do a carousel with only text, the height is never the same according to the current slide... We can only set the height for all slides.

Proposed solution

Set height like this jquery plugin (owl carousel) and implement a auto-height feature in order to apply a transition of the height when it changes.

**Comment by johnleider** [comment]
This component is being refactored to use v-img and other base components being created for v1.3

**Comment by johnleider** [comment]
A **height** prop has been added to `v-carousel` but as you stated, this applies to all children. We are now offering `v-window` which will allow you to accomplish dynamic heights.
