### ISSUE TITLE
[Feature Request] Paper component

### ISSUE THREAD

**Issue by yordis** [vuetifyjs/vuetify#4296]
### Problem to solve
Allow me in a declarative way to create a Paper like component style.

### Proposed solution
Create a component called `v-paper` component with the following props

#### Props

```javascript
{
  component: {
    type: String,
    default: 'div'
  }, 
  elevation: {
    type: Number,
    default: 2
  },
  square: Boolean,
}
```

**Comment by KaelWD** [comment]
How would this be different to v-card?

**Comment by yordis** [comment]
@KaelWD all the underline complexity. Like I said, `v-card` could use this component. The only concern of `paper` is the elevation piece of it.

**Comment by KaelWD** [comment]
So just `<div class="v-card">`? I've been thinking about doing that anyway if you don't use any of the more advanced props.

**Comment by yordis** [comment]
@KaelWD right, that is CSS driven interfaces which I would like to avoid. `Paper` is an element and when times comes to use Custom Elements + Shadow DOM I dont need to do anything.

This is more like a refactoring idea (which you dont need to refactor the other code right now) around the structure of the components.

**Comment by KaelWD** [comment]
yea I mean just `h('div', { staticClass: 'v-card' }, context.slots().default)` internally. My idea was to have a function component that just renders that if you don't use any more advanced props.

**Comment by yordis** [comment]
@KaelWD semantically I would keep it separate (even from CSS perspective) A Card component is a little more than just an elevation style. It has normally a bunch of sections and more content on it.

Moving to Paper the only concern of that component is elevation, rounding corners and some background for theming. 

```stylus
.v-paper
  background-color: var(--vuetify-paper-background)

  &--rounded
    border-radius: 2px
  &--elevation-1
    box-shadow: ....
  &--elevation-n
    box-shadow: ....
```

This is seeking simplicity specially around the CSS layer and the usage. For example, many of the examples of the DataTable uses `.elevation-x` on it which more declarative would be using `v-paper` instead. Benefits?! Well theming is one of them and embracing encapsulation of something should work as well rather than just CSS.

Card makes sense as well depending on how you see it but I wouldn't target to use `v-card` for what I am seeking. 

This is a small change that could be beneficial for the core so far, Dialog and Card could use it, the less code you need to touch for change something the better.

**Comment by johnleider** [comment]
I think that this could be the baseline for elevation/colorable and themable. It would be nice to have that specific functionality scoped to a component so it could be used in other areas without containing all the extra fluff that comes with a card.

You could potentially use this in `v-card`, `v-nav-drawer`, all `bar` components etc. This would also allow us to maybe have easily controlled hoverable styles on `v-text-field` and variants using the **solo** prop.

Component must be functional, rip out elevation, hover and tile from `v-card`

**Comment by johnleider** [comment]
This is something we explored and ultimately decided not to implement. However, the testing led us to 2 bits of functionality that made it into the framework, **elevatable** mixin and the `v-hover` component.
