### ISSUE TITLE
[Feature Request] Allow v-select to create single new item

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#4306]
### Problem to solve
Allows easy creation of custom "autocompletable" fields.

### Proposed solution
The behaviour would be similar to the current one when using `tags`, but instead of forcing a `multiple` along with it, it would just use the newly set the newly create item to `v-model`, or or set an existing one by using the list.

Currently, using `tags` does indeed force it to behave like a `multiple` select.

**Comment by jacekkarczmarczyk** [comment]
Use `combobox` prop

**Comment by jacekkarczmarczyk** [comment]
API should be changed to `combobox` and `combobox multiple`, it's not intuitive now

**Comment by jacekkarczmarczyk** [comment]
Please create an issue on docs repo
