### ISSUE TITLE
[Feature Request] Access to $vuetify.theme on Vue Root Instance

### ISSUE THREAD

**Issue by voxivoid** [vuetifyjs/vuetify#4307]
### Problem to solve
Hello guys, I have a problem that I don't know how to solve. I've got a white label app built in nuxt that can be accessed through different domains and needs to have dynamic themes, (i.e. if it is accessed through www.asdf.com has one theme, if it is accessed through www.qwerty.com has another, etc.). The color themes are fetched through a request to a REST api and this needs to be done before rendering the page so that the user does not see the colors of the theme changing. My problem here is that I don't have access to the $vuetify.theme on the nuxt context (the Root Vue Instance -> check: https://nuxtjs.org/api/context#context) so I don't find a way to change the theme globally via a nuxt middleware. Is there a way to make what I'm trying to do? I'm using vuetify 1.0.19.

### Proposed solution
Having access to $vuetify.theme on Vue Root Instance.

**Comment by KaelWD** [comment]
`Vue.prototype.$vuetify`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
