### ISSUE TITLE
[Feature Request] Floating avatar option

### ISSUE THREAD

**Issue by vahdet** [vuetifyjs/vuetify#4308]
### Problem to solve
For a user profile page, I'd like to use v-avatar component floating on, let's say, on the left-top of a card.

### Proposed solution
A solution like [floating action buttons](https://vuetifyjs.com/en/components/floating-action-buttons) would make a way out.

**Comment by johnleider** [comment]
You can do this currently: https://codepen.io/johnjleider/pen/dqjWoV
