### ISSUE TITLE
Snackbar 

### ISSUE THREAD

**Issue by banazak** [vuetifyjs/vuetify#431]
Hello, the snackbar displays a background in mobile devices. It can be seen on the following Pen if you resize the window.

https://codepen.io/banazak/pen/OmRQdj

I don´t know if I´m using it the wrong way. I´ll appreciate your help.

Thanks.

**Comment by smares** [comment]
Your pen isn't quite correct: https://codepen.io/anon/pen/OmRvgZ

**Comment by johnleider** [comment]
This was actually fixed, but I did not properly get the merge in for v0.11.1. Will leave open until the fix is properly deployed.

**Comment by johnleider** [comment]
This is confirmed good to go, closing.
