### ISSUE TITLE
[Bug Report] v-data-table header width ignored when table reaches maximum size  (width)

### ISSUE THREAD

**Issue by jennyballard** [vuetifyjs/vuetify#4310]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
Resize the browser window until the table reaches maximum width or a horizontal scroll bar appears

### Expected Behavior
The width value in the header would still be used. Column A should be 800px. The horizontal scroll bar should kick in. 

### Actual Behavior
The width value in the header is ignored. Column widths are adjusted as if there was no width value in the header.

### Reproduction Link
[https://codepen.io/jenbee/pen/pKWbGK](https://codepen.io/jenbee/pen/pKWbGK)

### Other comments
This applies to width and class in the header ie when the width style is set using class it is also ignored when the table reaches maximum size (width).

**Comment by jennyballard** [comment]
A workaround is to put a display: block element in the cell with a width setting. e.g. put a div in the <td>.
<td><div style="width: 300px;">blah blah</div></td>

**Comment by johnleider** [comment]
Since this has a workaround and this is not considered a priority fix for backporting, I'm closing it.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
