### ISSUE TITLE
toolbar with responsive paddings

### ISSUE THREAD

**Issue by iliyaZelenko** [vuetifyjs/vuetify#4312]
How can I do it?

https://i.imgur.com/FF49wr6.png
https://i.imgur.com/25kCHV2.png

I tried unsuccessfully to do through the v-container
Perhaps you can add a prop for this

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
