### ISSUE TITLE
[Feature Request] Have an API functionality to limit the number of characters in a form.

### ISSUE THREAD

**Issue by VVNoodle** [vuetifyjs/vuetify#4317]
### Problem to solve
We can create a counter validation in the form. Say the validation checks if the character length is less than 150. When the form consists of more than 150 characters, we can tell the users that they exceed character length. The problem is, users can still increase character length even if the validator tells otherwise.

### Proposed solution
Have a way to limit character length, so when user reach 150 characters, they can't type more.

**Comment by jacekkarczmarczyk** [comment]
Use `maxlength` attribute
