### ISSUE TITLE
[Feature Request] Make it possible to add ignore characters to "v-text-field" so the counter ignores them

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#4320]
### Problem to solve
Counting decimal places not character lengths when entering a number at `v-text-field` component. 

E. g.: I'd like to allow three decimal places, regardless of the algebraic sign or dot. Both examples should be possible when allowing four characters:

a) 0.001
b) -0.001

This is not possible at the moment because the "-" and "." character count as regular characters.

### Proposed solution
Add an array expression pattern to `v-text-field`.

```html
<v-text-field
  :counter="4"
  :counter-ignore="['.', '-']">
</v-text-field>
```

`counter-ignore` ignores these characters when counting.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
