### ISSUE TITLE
[Feature Request] Button Block/Group

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#4325]
### Problem to solve
Coupling buttons together visually - similarly to how toggle buttons can be grouped together.

### Proposed solution
Clone and tweak the v-btn-toggle element to create a v-btn-group element that uses the same styles but obviously retains individual button functionality.

**Comment by NerijusD** [comment]
+1

**Comment by johnleider** [comment]
This can now be accomplished with the `v-item-group` component in v1.3

**Comment by johnleider** [comment]
This will still be done but is not going to make v2.0. Please watch #7582 for updates.
