### ISSUE TITLE
[Bug Report] wrong icon and alignment in date picker (RTL problem)

### ISSUE THREAD

**Issue by Ashafaat** [vuetifyjs/vuetify#4327]
### Versions and Environment
**Vuetify:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
just use date picker with  locale="fa-IR"

### Expected Behavior
icon of next and previous month button should change (each one need other one icon)
day and month text should align to right

### Actual Behavior
next and previous month button have wrong icons
day and month text is aligned to left

### Reproduction Link
[https://codepen.io/ashafaat/pen/NzwjVW](https://codepen.io/ashafaat/pen/NzwjVW)

![2018-06-17-0005](https://user-images.githubusercontent.com/30526295/41509541-bc3e1cf4-726a-11e8-89f6-fd46277ceebe.jpg)

**Comment by moslemir** [comment]
> ### Versions and Environment
> **Vuetify:** 1.1.0-beta.3
> **Vue:** 2.5.16
> **Browsers:** Chrome 67.0.3396.87
> **OS:** Windows 10
> 
> ### Steps to reproduce
> just use date picker with locale="fa-IR"
> 
> ### Expected Behavior
> icon of next and previous month button should change (each one need other one icon)
> day and month text should align to right
> 
> ### Actual Behavior
> next and previous month button have wrong icons
> day and month text is aligned to left
> 
> ### Reproduction Link
> https://codepen.io/ashafaat/pen/NzwjVW
> 
> ![2018-06-17-0005](https://user-images.githubusercontent.com/30526295/41509541-bc3e1cf4-726a-11e8-89f6-fd46277ceebe.jpg)

Hello
Please fix the bug for the day of the month in the fa-IR locale.
On the first day, the number 11 should not be. But it's number 1.

**Comment by moslemir** [comment]
I found :
https://github.com/vuetifyjs/vuetify/issues/3865
https://codepen.io/anon/pen/Yampdq
https://github.com/vuetifyjs/vuetify/issues/1892

**Comment by MajesticPotatoe** [comment]
### Closed issue
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
