### ISSUE TITLE
[Feature Request] Add "hover" prop to lists

### ISSUE THREAD

**Issue by david-wg2** [vuetifyjs/vuetify#4330]
### Problem to solve
Currently you have to add an empty click listener to lists in order for a hover-effect to be applied. This is used a lot in the docs as `@click=""`. This is confusing for people reading the code.

### Proposed solution
Add a `hover` prop.

**Comment by adamorlowskipoland** [comment]
There is a `v-hover` elem in vuetify.

[here](https://vuetifyjs.com/en/components/hover#hover)

**Comment by charles2k16** [comment]
is the hover prop a boolean?

**Comment by KaelWD** [comment]
`v-list-item` now has a `link` prop: 02337136d5c68280453996b5a34b081aef1993b9
