### ISSUE TITLE
[Feature Request] Component for Flexible SVG icons 

### ISSUE THREAD

**Issue by DmytroDiachuk** [vuetifyjs/vuetify#4340]
## Work without font
Don't need include icon fonts and additional css files for this icons ( svg icons betters that font icons. My opinion based on this article https://css-tricks.com/icon-fonts-vs-svg/  
From Article:  
>  If you can go IE 9+ / Android 3+, inline SVG is better at pretty much everything than icon fonts". 

## Full Vuetify box
Will create  **default folder** icons  in  *Vuetify*. All icons, which vuetify use,  will be include  in the box. Like (icon-selection-control, arrow_drop_down, chevron_left, chevron_right  and others.....) . 

When user include Vuetify in own project, **he does not need include additional files**. 

## Faster works
All icons will bundle with your script. It is **faster** loading in browser   than **bundle.js +  file.fonts + file.css**. 

Additionally,  every project don't use all icons from the font. You can include only needed icons, it makes less size for your project. 
  
## More combinations
You can use  some icons from  **FontAwesome** and  some icons from **Material Design Icons**  https://materialdesignicons.com . 

You can  create own unlimited combinations for your project. Maybe it's more work for including, but it's more flexible. 

       
### Proposed solution
I propose integrate https://github.com/Justineo/vue-awesome 

Not All project, Only one component
https://github.com/Justineo/vue-awesome/blob/master/src/components/Icon.vue 

#### OR

to use this idea for new v-icon compoent, wich can use both type (font icon component or svg icon component )  
## Compact Store 
Store your icons in object. If you look on the https://materialdesignicons.com  All icons you can download as svg or view svg in **Inline SVG for HTML**. Example for icon "menu-down" https://materialdesignicons.com/icon/menu-down:  

#### Inline SVG for HTML
    
    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M7,10L12,15L17,10H7Z" />
    </svg>

#### For Examle, We save our icon as object in common store : 
**file  vuetify/icons/arrow-drop-down**

     import  VIcon from 'vuetify/components/VIcon'
     VIcon.register({
      'arrow-drop-down': {
        d: 'M7,10L12,15L17,10H7Z'
     })   

  **Sizes saved as default** 
    
     Vue.use(Vuetify, { icons: {width:24, height:24, type:'svg'} })

## Flexible & Asynchronous component
You can  connect special icon directly in component.  For Example: 

If You using **asynchronous component** with as  Webpack Chunk, your  icons will registered  when   component will be loaded. And special icons store in loaded component.  

    /*
       chunk
    */ 
    import  'vuetify/icons/special-icon-1';
    import  'vuetify/icons/special-icon-2';
    import  'vuetify/icons/special-icon-3';
    import  'vuetify/icons/special-icon-4';
    import  'vuetify/icons/special-icon-5';

     export default {
     name: 'special-component'
     ...
    }

### In addition, to use of the component can be the same
    <v-icon>name-icon<v-icon>

By default we  start  functional for svg icons, which registered in the box.  And user can register own icons. 

If user wants fonts add options 

    Vue.use(Vuetify, 
    { icons: 
      {type:'fa' // fa or mdi  if use fonts
     } })

On this website  https://materialdesignicons.com to gather collection icons directly  for Vuetify. 
 

What do you think about this idea??  
P.S. Sorry for my English, I am in the process of studying ;)

**Comment by struers-mfr** [comment]
I think this is very good idea that will be very helpful for people that want to have full control over all assets that are used on their website and want to optimize the amount of loaded assets, and don't load any unused icons in large icon-font bundle.
@johnleider do you have any plan for future releases when you will include this kind of feature into Vuetify ?

**Comment by johnleider** [comment]
I'd like to support it within `v-icon` but I haven't had time to learn how to do it. Would love to chat with anyone who is an expert.

**Comment by struers-mfr** [comment]
I cannot call my self an expert, but I have some experience with SVG icons and how to work with them, so we can chat about it. Just say where and when, and I will try manage it for my self.

**Comment by sbowler** [comment]
I was wondering about using multiple icon sets. The material design ones provide some good icons that seem lacking from like font-awesome. It seems that currently there's no way to accomplish this very easily and it sounds like this suggestion would help provide that capability.

I would imagine supporting more than one icon set would be a lot easier to do than this though. Not sure if it's worth opening up a separate issue for that.

**Comment by javiertury** [comment]
I'd like to mention an additional benefit. Icon fonts can be large and heavy, specially [material design icons](https://materialdesignicons.com/). They include a wide choice of icons but most projects will just use a reduced subset.

Subsetting a webfont based on used css classes is hard.  It's easier to use tree shaking with webpack 4, which works out of the box. This is the approach used for [@mdi/js](https://github.com/Templarian/MaterialDesign-JS), which only loads SVG path data for icons that are used.

**Comment by JamesCoyle** [comment]
At MDI we are recommending our users migrate away from the webfont due to the growing file size. Adding support for [@mdi/js](https://github.com/Templarian/MaterialDesign-JS) to this project would definitely be recommended going forward. We can then add an example of integrating with this project to the work-in-progress documentation for Vue on our new site.

**Comment by johnleider** [comment]
@JamesCoyle I'll take a look

**Comment by vinerz** [comment]
Another additional benefit is the behaviour with `VIcon` inside elements.
I am using custom individually imported font-awesome icons throughout my project this way:

```vue
<template>
  <div>
    <font-awesome-icon :icon="faCircle"></font-awesome-icon>
  </div>
</template>

<script>
  import { faCircle } from '@fortawesome/pro-solid-svg-icons';

  export default {
    data() {
      faCircle,
    },
  };
</script>
```

The `VCheckbox` uses internally a hardcoded `VIcon` in order to show its state.
As I didn't include the full font-awesome icons using the css webfonts, I am not able to use this component and currently there's no way I can workaround this.

If `VIcon` and elements that accept an icon argument could also parse imported SVG objects as the `font-awesome-icon` element does, it would be, _awesome_. 😆

**Comment by vinerz** [comment]
Hey @appurist, thanks for the answer!

I am aware about changing the icons at startup!
It would be lovely to use this approach, but as you are also doing, I am using JS SVGs and also using `VSwitch` as workaround, hahaha 😄

I was mentioning that the `VIcon` element itself is hardcoded, so I can't, for example, replace the icon element as a slot. Making it accept JS SVGs would be the best thing ever for us!

**Comment by johnleider** [comment]
This is now supported as of alpha.11 with paths.
