### ISSUE TITLE
[Bug Report] strange behavior of combobox with items as array of objects

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#4345]
### Versions and Environment
**Vuetify:** 1.1.0-rc.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
Items as array of objects.

### Expected Behavior
As in the previous version.

### Actual Behavior
The checkboxes are not selected. Displays the value in a chip and not the text.

### Reproduction Link
[https://codepen.io/SeregPie/pen/MXQXGd](https://codepen.io/SeregPie/pen/MXQXGd)

**Comment by KaelWD** [comment]
Not new, here's 1.0: https://codepen.io/anon/pen/zaRagq

You have to use `return-object` with `tags`/`combobox`, but it should probably be like that by default.

**Comment by jacekkarczmarczyk** [comment]
From docs:
`

**Comment by kkkman22** [comment]
`<div id="app">
  <v-app id="inspire">
    <v-container fluid>
      <v-layout wrap>
        <v-select
    :items="items"
    label="Select Item"
    multiple
  >
    <template
      slot="selection"
      slot-scope="{ item }"
    >
      <v-chip >
        <span>{{ item.text
          + item.value}}</span>
      </v-chip>
      
    </template>
        </v-flex>
        
      </v-layout>
    </v-container>
  </v-app>
</div>`


new Vue({
  el: '#app',
  data () {
    return {
       items: [{text:'11',value:'222'},
               {text:'22',value:'1222'},
               {text:'33',value:'2223'},
               {text:'44',value:'222444'},
              ],
    
       
    }
  }
})

**Comment by johnleider** [comment]
Please do not comment on closed issues. If you have a bug, please create a new issue, https://issues.vuetifyjs.com or seek help in our community, https://community.vuetifyjs.com
