### ISSUE TITLE
[Bug Report] different styles for readonly checkbox and radio, readonly applied on v-radio-group doesn't work

### ISSUE THREAD

**Issue by Thibaud-R** [vuetifyjs/vuetify#4349]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3316.0
**OS:** Windows 7

### Steps to reproduce
There is 4 controls with a readonly attribute each.
Only the text-field is not editable

### Expected Behavior
v-switch, v-radiogroup and v-checkbox are expected to be in a readonly state.

### Actual Behavior
The user can change the value of these controls v-switch, v-radiogroup and v-checkbox

### Reproduction Link
[https://codepen.io/anon/pen/XYZxqW](https://codepen.io/anon/pen/XYZxqW)

**Comment by jacekkarczmarczyk** [comment]
Partially fixedin 1.1 https://codepen.io/anon/pen/jKZQwO, however the checkbox/switch styles differ from radios, also readonly applied to v-radio-group doesn't seem to work

**Comment by Thibaud-R** [comment]
OK.
Thanks for the very (very) quick answer.
And for the partial resolution in 1.1. 
In case, v-radiogroup is not fix in 1.1, the workaround is to use readonly on v-radio, good to know !
