### ISSUE TITLE
[Bug Report] Toolbar: regression in 1.1.0-rc.1 showing grey space left and right of items

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#4355]
### Versions and Environment
**Vuetify:** 1.1.0-rc.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
1. Create v-toolbar with some items

### Expected Behavior
Show toolbar with items and no further space around it (as worked fine before rc.1)

### Actual Behavior
v-toolbar_content seems to be wider than v-toolbar_items leading to grey background left and right of the actual toolbar. Some regression in CSS.

### Reproduction Link
[https://codepen.io/anon/pen/JZLoqq](https://codepen.io/anon/pen/JZLoqq)

### Other comments
Couldn't think of a better title...

**Comment by johnleider** [comment]
This is particularly difficult with the updated fixes for other issues with `v-toolbar` and gutters. I suppose we could add a workaround and apply the same logic applied to `v-list` here. Any changes made though would be removed in the next MAJOR.

**Comment by duebbert** [comment]
Ok. Just FYI, this is what it was like before RC: https://codepen.io/anon/pen/XYqKEd (Beta 3 in this case)

I'm using a few toolbars and it's screwing up their appearance now. It's not perfect even in the versions before as can be seen in the example because rounding is still used but would be good to get this at least to the working version before RC

**Comment by duebbert** [comment]
I believe this fixes it?
```
.v-toolbar
  &--floating
    .v-toolbar
      &__content
        padding: 0;
```

Would be integrated into `_toolbar.styl`

**Comment by johnleider** [comment]
I know this has been bounced around a bunch. I've been coming in and out trying to understand the best way to accomplish this, and either way, someone loses. In an effort to support the spec (at least md1), we cannot implement this change. I think your change above resolves the issue from a userland standpoint and I apologize for any inconvenience caused.
