### ISSUE TITLE
[Bug Report] Solo Text Field no longer allows `flat`

### ISSUE THREAD

**Issue by jeffberry** [vuetifyjs/vuetify#4358]
### Versions and Environment
**Vuetify:** 1.1.0-rc.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Mac OS 10.14.0

### Steps to reproduce
`<v-text-field solo flat></v-text-field>`

### Expected Behavior
The solo box would render without a shadow

### Actual Behavior
https://github.com/vuetifyjs/vuetify/pull/4286 moved the drop-shadow onto `.v-input__slot`, which prevents the `elevation-0` override class from taking effect. 

### Reproduction Link
[https://codepen.io/jeffberry/pen/eKMZjw](https://codepen.io/jeffberry/pen/eKMZjw)

### Other comments
--

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/6257e6d511409b54b57c12333def09a31b63080d
