### ISSUE TITLE
[Bug Report] Autocomplete with slot no-data not select items

### ISSUE THREAD

**Issue by AGPDev** [vuetifyjs/vuetify#4359]
### Versions and Environment
**Vuetify:** 1.1.0-rc.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Linux x86_64

### Steps to reproduce
Just try select value, after remove template slot and try again

### Expected Behavior
Select data like previous version

### Actual Behavior
not working

### Reproduction Link
[https://codepen.io/anon/pen/QxmKap?&editors=101](https://codepen.io/anon/pen/QxmKap?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
Works fine if `listData` in VSelect/VAutocomplete is changed from computed to method

**Comment by johnleider** [comment]
I'm in the process of debugging this as a Vue bug: https://codepen.io/johnjleider/pen/gKexBa?editors=1011

In a nutshell, when creating a node from a non-functional or string component, `listData`'s **on** property is being modified for whatever reason.
