### ISSUE TITLE
[Feature Request] Expose positioning and nudge properties on select

### ISSUE THREAD

**Issue by kendallroth** [vuetifyjs/vuetify#4362]
### Problem to solve
The `v-select` fields do not allow easily modify the positioning of the created `content` element(s). While it does expose a `content-class` this requires manually calculating the position attributes in the class, which comes at the risk of future changes and media query changes, etc.

### Proposed solution
Expose similar (or at least some) props to the `v-menu` component (such as `bottom..., nudge-top..., offset-x...`). This would allow customization of the menu position _if required_, much the same as the `v-menu` component can be easily overridden.

**Comment by KaelWD** [comment]
Already done in 1.1

**Comment by kendallroth** [comment]
Awesome, was not aware of that (although I couldn't find an issue or changelog for it at first glance)

**Comment by KaelWD** [comment]
No issue or changelog for that, just something that ended up happening.
