### ISSUE TITLE
v-dialog takes up space even when not active

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#437]
When adding a dialog inside a container (e.g. a card), the following style rule causes it to grow the size of the container because it occupies an height equal to the default line-height (21px). This is a bug causing side effects in the layout and must be fixed.

https://github.com/vuetifyjs/vuetify/blob/37032cc3f090c51972c849dc1e7accf0859a9eac/src/stylus/components/_dialogs.styl#L15

It can be fixed by changing `display` to `inline` or removing it completely (which will default to `inline`).

Also, a different issue but related to the same CSS class: when placing a `v-dialog` inside a `v-card` with the `hover` prop enabled, the whole viewport gets a pointer cursor when the dialog is active because it inherits the `cursor: pointer` from `.card--hover`. A simple fix is to reset the cursor to `auto` in `.dialog__container`.

It would be nice to get these fixes into the next release so I can remove my hacks ;)

**Comment by mfferreira** [comment]
@sindrepm If you have fix suggestions, you're very welcome to submit a PR instead of creating issues.

**Comment by sindrepm** [comment]
@mfferreira ok, will do. I wasn't sure if you were accepting PR's from everyone or just core members. Should the PR be created on the `dev` branch?

**Comment by johnleider** [comment]
If it's a bug with the current version, you can PR to master, otherwise, PR to dev.

**Comment by johnleider** [comment]
This no longer happens in the current dev version.
