### ISSUE TITLE
[Feature Request] Better Docs & Guides

### ISSUE THREAD

**Issue by mknx-io** [vuetifyjs/vuetify#4374]
### Problem to solve
Hello,
I send this message today, to first tell you that your set of components is very large and useful for my company's projects, so I'm glad to tell you my thanks.
The second thing, that is a lack for your project: a readable & complete documentation, that is missing in your website. Particularly, in a lot a cases I have to find by myself the behavior of your components, or I need to guess (or to search in code) the behavior of some components. It makes me waste a lot of time. Some of them are very well explained, but a lot are not explained at all.
So if you provide a documentation, please provide a complete documentation, or at least let the developer community contribute to the documentation, if you don't have the time/wish. It could be very useful for all of us. It's not to denigrate your project, it's only a suggestion.

Thanks in advance for your work!

### Proposed solution
The proposed solution has been explained above.

**Comment by KaelWD** [comment]
You **can** contribute to the documentation, it is completely open source: https://github.com/vuetifyjs/vuetifyjs.com

Any documentation-specific issues should also be opened there, not here. 

Also check out the updated docs for 1.1, we've corrected loads of missing information: https://next.vuetifyjs.com/en/
