### ISSUE TITLE
[Bug Report] Label cursor should be "pointer" in certain input controls

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4377]
### Versions and Environment
**Vuetify:** 1.1.0-rc.2
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 7

### Steps to reproduce
Not sure exactly which version this "bug" appeared, but it does not happen in 1.0. Basically the cursor for label inside any input control is set to `text` which looks strange for example in the `v-radio` or `v-select` control.

Here is the same example with version 1.0:
https://codepen.io/anon/pen/aKKBRx

### Expected Behavior
Expect cursor to be of type `pointer` when the label is clickable, e.g. in radio buttons, switch, checkbox and "unselected" state of selects.

### Actual Behavior
Label cursor is always of type `text`.

### Reproduction Link
[https://codepen.io/anon/pen/xzzRYB](https://codepen.io/anon/pen/xzzRYB)

### Other comments
This is not a critical bug, but something that affects "affordance" of the components and also it looks a bit strange.

**Comment by johnleider** [comment]
Fixed in f15f85174668370b49adb488544cd8cd330ac829

**Comment by sindrepm** [comment]
This hasn't been completely fixed. E.g. for select box the label still has a text cursor in the unselected state.

Suggested fix:
```
.v-input.v-select .v-label:not(.v-label--active) {
    cursor: pointer;
}
```
I have created a codepen with all different input controls (I think?) and it seems to work fine with no side effects.

https://codepen.io/anon/pen/gKBwLG

**Comment by KaelWD** [comment]
#4404
