### ISSUE TITLE
[Bug Report] Validation not showed correctly in Firefox

### ISSUE THREAD

**Issue by xevimayo** [vuetifyjs/vuetify#4379]
### Versions and Environment
**Vuetify:** 1.1.0-rc.2
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Windows 10

### Steps to reproduce
Just surf with <b>Firefox</b> to Vuetify web: 
https://next.vuetifyjs.com/en/components/text-fields#example-custom-validation

and
https://next.vuetifyjs.com/en/components/autocompletes#example-asynchronous

### Expected Behavior
No validation errors must be displayed before entering in an input field. And in the case, an error must be shown, it should be a red underline, not a red rectangle.

### Actual Behavior
The inputs are showing an ugly red error rectangle even not yet pressed any key inside the inputs. After leaving the input the rectangle still is there and not the nice underline that must be. The same is happening with the Autocomplete asynchronous item.

### Reproduction Link
[https://codepen.io/xevi/pen/eKKePY](https://codepen.io/xevi/pen/eKKePY)

**Comment by KaelWD** [comment]
af69aea was a correction to this.
