### ISSUE TITLE
[Feature Request] Easy way to implement multiple items in carousel, and hide the buttons (next or prev) depending on index (start of finish) and or infinite /loop with scroll

### ISSUE THREAD

**Issue by michelleLegend** [vuetifyjs/vuetify#4380]
### Problem to solve
It makes it easier to develop things that look like Netflix home page scroll section. A lot of websites use a similar layout.

### Proposed solution
https://codepen.io/anon/pen/wXjREa?editors=1010

This is a horrible solution, looking for something better.

**Comment by KaelWD** [comment]
Duplicate of #1886
