### ISSUE TITLE
[Feature Request] Date Picker Async allowed-dates

### ISSUE THREAD

**Issue by RobbinBaauw** [vuetifyjs/vuetify#4381]
### Problem to solve
This feature would make it possible to load allowed-dates of the date-picker component (https://vuetifyjs.com/en/components/date-pickers) through an async call, making it possible to check a server for allowed-dates. As far as I've tried this isn't possible, I tried a couple of things already, as using promises, for example: https://codepen.io/anon/pen/GGGxWE

### Proposed solution
It would be great if it were possible to return true or false using an async call, or being able to attach an array to the allowed-dates property which is updatable.

**Comment by jacekkarczmarczyk** [comment]
Async call for each date doesn't seem to be a good solution, you'll end up with 30 ajax calls for every month.

You can create a new `allowedDates` function when server returns data (an array of dates): https://codepen.io/anon/pen/MXXVOR?editors=1010
