### ISSUE TITLE
[Bug Report] Appended Icon on Autocomplete Rotating When It Is Already Changed

### ISSUE THREAD

**Issue by rgalaxy** [vuetifyjs/vuetify#4387]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10, Windows

### Steps to reproduce
Click on the text field, the icon is rotating

### Expected Behavior
Icon is not rotating

### Actual Behavior
Icon rotating as the normal behavior

### Reproduction Link
[https://codepen.io/RGALAXY/pen/VddJOW](https://codepen.io/RGALAXY/pen/VddJOW)

### Other comments
I dont know if it was me that need to change the code or anything, but i think the ability to rotate the icon should be done in the `append-icon-cb` ?

**Comment by johnleider** [comment]
This is solved to an extent in v1.1 with the use of **append-outer-icon**.

**Comment by markon1** [comment]
I fixed this by adding this CSS override:

`.v-select.v-select--is-menu-active .v-input__icon--append .v-icon {
	-webkit-transform: none !important;
	transform: none !important;
}`

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
