### ISSUE TITLE
[Feature Request] Property that makes activator toggle its menu in any case

### ISSUE THREAD

**Issue by Traxo7** [vuetifyjs/vuetify#4389]
### Problem to solve
`:close-on-click="false" :close-on-content-click="false"` makes menu non-closeable except by some workaround (see comments for an example).
It's kinda odd because some would expect that clicking on activator would toggle the menu in any case.

### Reproduction    
https://codepen.io/anon/pen/rKKXPm

### Proposed solution
Having a v-menu property that makes activator toggle the menu whenever we click on the activator, or make it a default behavior.

### Comments
Currently we need workaround like this:
https://codepen.io/anon/pen/RJJXOv
(thanks @&#8205;jacekkarczmarczyk for workaround)

**Comment by johnleider** [comment]
I'd like to explore some improved functionality for v2.0, especially with the abstraction of `v-click-outside` directive.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
