### ISSUE TITLE
[Bug Report] `v-navigation-drawer`s height is not properly calculated when using fixed `v-footer`

### ISSUE THREAD

**Issue by Traxo7** [vuetifyjs/vuetify#4390]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chromium 64.0.3282.167
**OS:** Ubuntu undefined

### Steps to reproduce
Use `v-navigation-drawer` and `v-footer` with `fixed app` attributes.

### Expected Behavior
`v-navigation-drawer` should calculate height properly when we use `app fixed` on `v-footer`

### Actual Behavior
`v-navigation-drawer` is not calculating height properly with fixed `v-footer`.  
It doesn't take `v-footer` into account

### Reproduction Link
[ https://codepen.io/anon/pen/XYBrQy]( https://codepen.io/anon/pen/XYBrQy)

### Other comments
It works properly with `v-bottom-nav`, but not with `v-footer`

@&#8205;jacekkarczmarczyk wrote in discord:
> https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VNavigationDrawer/VNavigationDrawer.js#L137 and https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VFooter/VFooter.js#L14

**Comment by idealley** [comment]
I can confirm, the same thing happens form me

**Comment by johnleider** [comment]
This is a different issue. Please submit a bug report.
