### ISSUE TITLE
Primary color problem

### ISSUE THREAD

**Issue by scippio** [vuetifyjs/vuetify#4395]
Hi, I'm using Nuxt with Vuetify ... everything is ok, but colors is not functional:

my code:
```
import Vue from 'vue'
import Vuetify from 'vuetify'

import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify,{
    theme: {
        primary: colors.red.darken1, // colors.amber.darken3
        secondary: colors.amber.darken1,
        accent: colors.amber.darken4,
        info: '#0D47A1',
        warning: '#ffb300',
        error: '#B71C1C',
        success: '#2E7D32'
    }
})
```
```
<v-toolbar color="primary">
...
</v-toolbar>
```

Toolbar is still white ... primary class not exists...

![image](https://user-images.githubusercontent.com/672903/41845659-7fa98ed0-7874-11e8-943a-ab6af3406291.png)

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/41846248-7580b27c-78b9-11e8-879b-9ccf82d6eb18.png)

**Comment by scippio** [comment]
@KaelWD Oh... :flushed: sorry. thank you...
