### ISSUE TITLE
[Bug Report] Checkboxes don't work when using objects for chips/multiple select.

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/vuetify#4398]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Mac OS 10.13.5

### Steps to reproduce
With the following example, use array of objects instead of array of strings.

https://vuetifyjs.com/en/components/selects#example-tags

### Expected Behavior
To set the checkboxes at the correct state for the selected items.

### Actual Behavior
They don't select the expected items at all. Everything else works functionally.

### Reproduction Link
[https://codepen.io/jaesung2061/pen/LrJPNr?editors=1010](https://codepen.io/jaesung2061/pen/LrJPNr?editors=1010)

**Comment by KaelWD** [comment]
> Keep in mind, tags only supports arrays of **primitive** items and cannot be used with props such as `item-text`, `item-value` for example.

This has also been fixed in 1.1: https://codepen.io/anon/pen/PadqRo?editors=1010
