### ISSUE TITLE
fullscreen dialog not poping on v-model change

### ISSUE THREAD

**Issue by billouboq** [vuetifyjs/vuetify#440]
Changing the value of v-model does not trigger the modal, is this intended?

```html
<template>
<v-dialog v-model="isOpen" fullscreen transition="v-dialog-bottom-transition" :overlay="false">

   <v-card>

      <v-card-row>

         <v-toolbar>
            <v-btn icon="icon" @click.native="close">
               <v-icon>close</v-icon>
            </v-btn>
            <v-toolbar-title>Création de dossier</v-toolbar-title>
            <v-btn class="white--text" flat="flat">Créer</v-btn>
         </v-toolbar>

      </v-card-row>

      <v-list>

         <v-list-item>

            <v-list-tile>
               <v-list-tile-content>
                  <v-text-field class="input-container" label="Nom du dossier" v-model="folderName">
                  </v-text-field>
               </v-list-tile-content>
            </v-list-tile>
         </v-list-item>

      </v-list>

      <v-divider></v-divider>

      <v-list three-line subheader>

         <v-subheader>Options</v-subheader>

         <v-list-item>
            <v-list-tile avatar>
               <v-list-tile-action>
                  <v-checkbox label="Dossier visible uniquement par les collaborateurs" v-model="collabOnly" light primary />
               </v-list-tile-action>
               <v-list-tile-content>
                  <v-list-tile-title>Visibilité</v-list-tile-title>
                  <v-list-tile-sub-title>Ce dossier ne sera visible que par les collaborateurs</v-list-tile-sub-title>
               </v-list-tile-content>
            </v-list-tile>
         </v-list-item>

      </v-list>

   </v-card>

</v-dialog>
</template>

<script>
export default {
   props: {
      folder: {
         type: Object,
         required: true
      },
   },
   data() {
      return {
         isOpen: true,
         folderName: '',
         collabOnly: true,
      }
   },
   computed: {
      userIsAdminOrCollab() {
         return [1, 2].includes(this.$store.state.self.scope);
      }
   },
   methods: {
      reset() {
         this.folderName = '';
      },
      open() {
         console.log('open');
         this.isOpen = true;
      },
      close() {
         console.log('close');
         this.isOpen = false;
      },
   },
}
</script>

<style lang="scss">
</style>
```

Calling open method does not work, it does fire so I think it's an internal issue.

Setting isOpen to true show the dialog.

How can I trigger the dialog without creating an activator slot ?

**Comment by billouboq** [comment]
My bad, close works as intended, just can't open it now... I must have forgot something.
Closing it for now.

**Comment by billouboq** [comment]
still can't figure it out ou to trigger dialog without using activator slot...

**Comment by mfferreira** [comment]
@billouboq `<v-btn @click.native="dialog = true" />` should do it.

**Comment by billouboq** [comment]
@mfferreira yeah sorry about that, but since it's a single component, reproducing it the way it is can be kinda hard sometimes. And still learning vue Js.

Don't understand your solution. I mean what does dialog variable do? is it the variable I have to give to dialog "v-model" attribute? I that case it's not different than my "isOpen" variable. Maybe I missed your point.

**Comment by mfferreira** [comment]
@billouboq That's exactly right.
Here's a working example: https://codepen.io/mfferreira/pen/KmNapB

**Comment by billouboq** [comment]
thank you very much

**Comment by billouboq** [comment]
Still not working when I try to put dialog inside a component. I found no way to make it work since v-dialog mutate the value passed in.

https://codepen.io/anon/pen/JNbWMM

See the inspect section.

**Comment by johnleider** [comment]
As far as I'm aware, v-dialog does not directly mutate the model.

**Comment by billouboq** [comment]
@johnleider mutation was a mistake of me, but can't figure it out why the modal does not show up when I click on the button.

https://codepen.io/anon/pen/JNbWMM

**Comment by johnleider** [comment]
The reason is the property change is not being evaluated properly by your component.

https://codepen.io/johnjleider/pen/XRNRWZ

**Comment by billouboq** [comment]
@johnleider you're a life savior thanks !

**Comment by JonasDoebertin** [comment]
Currently having the same problem. Unfortunately the last Pen https://codepen.io/johnjleider/pen/XRNRWZ isn't available anymore. May I ask how you were able to solve it, @johnleider @billouboq ?

**Comment by mfferreira** [comment]
@JonasDoebertin The gist of it is that the prop being passed to the component is typed wrong.

isOpen evaluates to "isopen", not isOpen as the component requires.

So instead of `:isOpen="d1"`, is should be`:is-open="d1"`.
