### ISSUE TITLE
[Bug Report] v-model don't update in v-tab

### ISSUE THREAD

**Issue by Tiagosophy** [vuetifyjs/vuetify#4402]
### Versions and Environment
**Vuetify:** 1.1.0-rc.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
If you click in "Item 2", the v-model update. But if you swipe left in tab content, the v-model don't update (v-tab-item will change, the indicator too, but the v-model don't). You will need turn on responsive mode in developer tools of your browser to be able to swipe.

### Expected Behavior
Update v-model

### Actual Behavior
V-model don't update

### Reproduction Link
[https://codepen.io/tiagoxavi/pen/aKaxmO](https://codepen.io/tiagoxavi/pen/aKaxmO)

**Comment by johnleider** [comment]
This was changed with https://github.com/vuetifyjs/vuetify/commit/158424fc546c07d11fa732f60bd92c9a99e20817 

This happens because of the comparison. The workaround is to simply not use `.toString()`

https://codepen.io/johnjleider/pen/JZmZJr

**Comment by Tiagosophy** [comment]
It's not about the "Next tab" button. I removed it from the pen.
it's about touch swipe to change the tab.

**Comment by aZilberstein** [comment]
I can confirm this issue still exists. Try to turn on the development mode in the [https://codepen.io/johnjleider/pen/JZmZJr](aforementioned Codepen) and try to swipe any of the tabs left or right. The V-model won't update accordingly

**Comment by mrtongkatali** [comment]
+1

**Comment by johnleider** [comment]
@mrtongkatali that is more than likely a different issue. This has to do with changes made for v1.1
