### ISSUE TITLE
[Feature Request] Allow usage of predefined palette in theme definition

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#4408]
### Problem to solve
Vuetify generates new palettes on the fly for the theme colors, removing designers freedom to manually create the most visually satisfying palette.

### Proposed solution
Allow usage of full palette when defining the theme. If the theme color is an object containing all the necessary color level properties, just use it straight away, skipping generation step.

**Comment by johnleider** [comment]
I'm not sure what you are asking for.

**Comment by KaelWD** [comment]
I'm guessing something like

```js
import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify, {
  theme: {
    primary: colors.blue // Instead of colors.blue.base
  }
})
```

And it would use all the lighten/darken stuff from there instead of generating it. This would also technically solve #3389.

**Comment by nolde** [comment]
Yes @KaelWD , that's what I want, thanks for the clarification.

Having that would give designers more freedom to determine palettes. Our designer already complained about "our palettes" being a bit "bland", heh!

**Comment by nolde** [comment]
Any chance of getting this in earlier if I get the code updated myself, @johnleider ??

**Comment by johnleider** [comment]
Kael mentioned to me he wants to do this for v1.2. We are still working out if there is even going to be a 1.2 or if we are going straight to 2.0 with the recent update to the md spec. I'll let him decide on this. If he wants to do a v1.2 then he can move this back.

**Comment by nolde** [comment]
Thanks for the answer, @johnleider !
And thanks for the update to 1.2.0, @KaelWD .

But this still doesn't answer my question. =)

If I make the change myself, would you you guys be willing to evaluate it and, if deemed, ok, get it into 1.1 ?

**Comment by KaelWD** [comment]
No, that isn't how semver works.

**Comment by nolde** [comment]
Yeah, I you are right, @KaelWD . 

I just say that because you guys seemed to take a good whole to move from v1.0 to v1.1, so I don't know whether you guys will do the same thing for a possible v1.2 or if it will move somewhat quicker.

**Comment by KaelWD** [comment]
We are planning to move a lot quicker for 1.2, probably will split the current milestone into several releases.

**Comment by nolde** [comment]
Yeeeeessssssssss thanks mates!
