### ISSUE TITLE
[Bug Report] prepend-icon not inside v-text-field when using solo

### ISSUE THREAD

**Issue by mrkswrnr** [vuetifyjs/vuetify#4409]
### Versions and Environment
**Vuetify:** 1.1.0-rc.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87, Mozilla Firefox
**OS:** Mac OS 10.13.5

### Steps to reproduce
Compare reproduction link with stable version example:
https://codepen.io/mrkswrnr/pen/QxJKNQ

### Expected Behavior
Icon displayed inside the textbox (as in stable version example)

### Actual Behavior
Icon displayed outside of the textbox

### Reproduction Link
[https://codepen.io/mrkswrnr/pen/vrQXOL](https://codepen.io/mrkswrnr/pen/vrQXOL)

**Comment by jim0thy** [comment]
You need to use `prepend-inner-icon` in v1.1 to get it inside the textbox.

https://codepen.io/jim0thy/pen/rKQwor

**Comment by johnleider** [comment]
We have to unfortunately treat this as a _style_ change rather than a bug. This may not be ideal and I'm sure someone is going to scream **semver** but it's almost impossible to guarantee no style changes.

**Comment by mrkswrnr** [comment]
Thank you for clarification 👍
