### ISSUE TITLE
[Bug Report] v-content calculates an incorrect padding when given height is a string

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#4413]
### Versions and Environment
**Vuetify:** 1.1.0-rc.3, 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
Open the pen

### Expected Behavior
v-content bottom padding should be 56px

### Actual Behavior
v-content bottom padding is 560px

### Reproduction Link
[https://codepen.io/anon/pen/YvRQEb](https://codepen.io/anon/pen/YvRQEb)

### Other comments
Passing a number instead prevents this (`:height="56"`)

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed
