### ISSUE TITLE
[Feature Request] Navigation Drawer - Add options to be "Top" or "Bottom"

### ISSUE THREAD

**Issue by dysol** [vuetifyjs/vuetify#4414]
### Problem to solve
One use case is enabling drawer to "slide" in from top of toolbar instead of sides.

### Proposed solution
Add a prop to allow drawer to slide from any direction / position

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/bottom-sheets
https://material.io/design/components/sheets-bottom.html

We'll be adding more functionality to these in line with the new material design specification.

**Comment by dysol** [comment]
I've seen the Bottom Sheets component, however there is no option to specific it to be "top". Would you confirm that it'll be added in future?

**Comment by KaelWD** [comment]
There's no plans to, nad it isn't to spec. Might be possible eventually though, depends how flexible we end up making things.
