### ISSUE TITLE
[Bug Report] v-menu open with activate method

### ISSUE THREAD

**Issue by zajca** [vuetifyjs/vuetify#4421]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Opera , Google Chrome, probably all
**OS:** Linux x86_64

### Steps to reproduce
Click on table head, menu will open, but when clicked outside menu will not close.

### Expected Behavior
Menu should close when clicked outside.

### Actual Behavior
Menu will not close. Also there is another weird issue (maybe I did not get it right) when I specify attach selector menu is weirdly positioned, this is better when I set parent to position: relative, but still covering parent, best result I'm getting when set attach to nonexisting selector and menu content is rendered inside menu div.

### Reproduction Link
[https://codesandbox.io/s/llrp5o02qm](https://codesandbox.io/s/llrp5o02qm)

### Other comments
I'm trying to extend VDataTable functionality to add more complex filtering options. Is it something that would be accepted in vuetify if I make PR? Here is what I'm now have: https://drive.google.com/file/d/1nZ3y6ZO5Ly7P78iLyI6wL60JptFzSOKr/view
full code is here: https://github.com/zajca/nuxt-jwt/blob/master/components/DataTable/headers.vue

**Comment by KaelWD** [comment]
`activate` doesn't do what you think, and is not public API. Use props the way they were intended. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
