### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by cayaner** [vuetifyjs/vuetify#443]
i hope i can find a guide for how to deploy

**Comment by dohomi** [comment]
@cayaner maybe check out https://zeit.co/now its easy to dipp in

**Comment by cayaner** [comment]
it worked like a charm,, thanks ..
if i can ask .. my back-end is a [forge.laravel.com](url) server, is it possible to deploy the ssr template to forge? 
thanks in advance

**Comment by dohomi** [comment]
I have no experience with that.. so can't give you any advise. I also don't understand what the PHP backend of forge has to do with your ssr template? it should not matter in my opinion where you deploy the template

**Comment by cayaner** [comment]
thanks again ...

**Comment by dohomi** [comment]
I'll close the issue for now, feel free to to keep the conversation going but I don't think that vuetify will take responsibility of deployments because there are too many options out there.

**Comment by cayaner** [comment]
it's clear ...
