### ISSUE TITLE
[Feature Request] append-icon-cb can't take arguments

### ISSUE THREAD

**Issue by wishinghand** [vuetifyjs/vuetify#4433]
### Problem to solve
When iterating through a list and putting icons on each iterated object, being able to pass the object's id so that it can be operated on is a fairly expected behavior. For whatever reason, `:append-icon-cb` doesn't allow it, making it very hard to use it for a delete icon to grab the iterated list item it exists in.

### Proposed solution
Allow `:append-icon-cb` to take a function that can receive an argument.

**Comment by KaelWD** [comment]
`append-icon-cb` is deprecated, it's an event `click:append` now.

**Comment by wishinghand** [comment]
Ah I see. The docs still referenced `append-icon-cb` which is why I was led astray. For those googling around because you're stuck on an earlier version of Vuetify, you can get around the issue with an arrow or lambda function:

`:append-icon-cb="() => deleteResource(resource.id)"` is what I ended up putting on the `v-checkbox`
