### ISSUE TITLE
text field label cursor is not pointer

### ISSUE THREAD

**Issue by iliyaZelenko** [vuetifyjs/vuetify#4436]
this is normal behavior? vuetify 1.1

**Comment by KaelWD** [comment]
Yes

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
