### ISSUE TITLE
[Bug Report] The vee-validate on specific events doesn't work with v-text-field

### ISSUE THREAD

**Issue by nmchau** [vuetifyjs/vuetify#4438]
### Versions and Environment
**Vuetify:** 1.1.0
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.10.3

### Steps to reproduce
Select v-text-field and then select other things. Or select v-text-field and type something.

### Expected Behavior
The validation in v-text-field should be activated only in blur event.

### Actual Behavior
The validation in v-text-field was activated when typing input and wasn't activated in blur event

### Reproduction Link
[https://codepen.io/nmchau/pen/eKxvKL](https://codepen.io/nmchau/pen/eKxvKL)

### Other comments
This behavior doesn't show in vee-validate@2.0.9. (But the vee-validate latest version does work well with normal input field)

**Comment by KaelWD** [comment]
This seems to be a problem with vee-validate, setting `data-vv-validate-on="blur"` works as expected. 
https://codepen.io/anon/pen/XYOReW?editors=1010

**Comment by FatihAydin52** [comment]
@KaelWD did not work for v-select
