### ISSUE TITLE
[Bug Report] v-chip disabled shouldn't be selectable

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4442]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Click on the disabled chips

### Expected Behavior
Disabled chips should not be selected
![image](https://user-images.githubusercontent.com/1561360/42137808-4e7b5ab2-7d49-11e8-9d6b-086dd302e32f.png)
![image](https://user-images.githubusercontent.com/1561360/42137803-3ca9616c-7d49-11e8-967c-4437e02aaf98.png)

### Actual Behavior
Disabled chips are displaying as selected after click on it
![image](https://user-images.githubusercontent.com/1561360/42137810-5c1f9fe8-7d49-11e8-8b1f-428f0b64643e.png)
![image](https://user-images.githubusercontent.com/1561360/42137797-2c37aba4-7d49-11e8-992d-529464289fcc.png)

### Reproduction Link
[https://codepen.io/anon/pen/dKamWm?editors=1000](https://codepen.io/anon/pen/dKamWm?editors=1000)

### Other comments
Related to the same prop discussed on https://github.com/vuetifyjs/vuetify/issues/3817

**Comment by KaelWD** [comment]
Last good version was 1.0.19: https://codepen.io/anon/pen/oymOgQ?editors=1000
