### ISSUE TITLE
[Bug Report] .font-weight-thin isn't working

### ISSUE THREAD

**Issue by vwxyzjn** [vuetifyjs/vuetify#4444]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.13
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Open the reproduction link
2. Compare the rendered font result with https://vuetifyjs.com/en/style/typography

### Expected Behavior
Expect `.font-weight-thin` to make the font as slim as the ones in https://vuetifyjs.com/en/style/typography

### Actual Behavior
The rendered font in the reproduction link is significantly "fatter" than that of https://vuetifyjs.com/en/style/typography

### Reproduction Link
[https://codepen.io/vwxyzjn/pen/pKGxdG](https://codepen.io/vwxyzjn/pen/pKGxdG)

**Comment by KaelWD** [comment]
You have to add `100` to the `fonts.googleapis.com` url.

**Comment by vwxyzjn** [comment]
@KaelWD That works. Thank you!
