### ISSUE TITLE
[Bug Report] v-select: selection is not reflected when value contains nested `value` field

### ISSUE THREAD

**Issue by downace** [vuetifyjs/vuetify#4446]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Linux x86_64

### Steps to reproduce
Pass array to `items` prop of `v-select` that contains nested `value` field. Example:

```javascript
[
    {
        text: 'Title',
        value: {
            value: 20
        }
    }
]
```

### Expected Behavior
Selected item should be visible

### Actual Behavior
Selected item is not visible

### Reproduction Link
[https://codepen.io/downace/pen/WyPYRV](https://codepen.io/downace/pen/WyPYRV)

**Comment by KaelWD** [comment]
Use `return-object` to get the entire thing out: https://codepen.io/anon/pen/YvBRvO?editors=1010
Also maybe reconsider having a separate object for `value`, I don't think that's something intentionally supported.
