### ISSUE TITLE
[Feature Request] Autocomplete Icon suppose to be inside the Text Field style and NOT rotating.

### ISSUE THREAD

**Issue by rgalaxy** [vuetifyjs/vuetify#4447]
### Problem to solve
this issue is the extension of this issue <a href="https://github.com/vuetifyjs/vuetify/issues/4387"> [Bug Report] Appended Icon on Autocomplete Rotating When It Is Already Changed #4387</a>

I need to change the icon inside the text field from those rotating triangle to just becomes magnifier (`icon-search`).
Today, i can do it by using `append-outer-icon` BUT it is not inside the div of input text anymore. Even the dropdown list will not extends to the end of the text-field.

Isn't it the rotation of the icon suppose to be the works of the developer? since not all people will use rotation animation as their default autocomplete behavior?

### Proposed solution
- Remove the rotating animation of the icon.
- Add properties of animation
- Make the dropdown-list to take up full length when `append-outer-icon` being used.

### CODEPEN

https://codepen.io/RGALAXY/pen/VddJOW

**Comment by ratron** [comment]
I would like to see that feature as well.  i think adding a property to enable/disable animation would be the best solution. that would preserve the different design options when using `append-icon` vs. `append-outer-icon`.

## workaround
for now, we use an extra css-style to disable rotation:
```
.v-select.v-select--is-menu-active
  .v-input__icon--append
  .v-icon {
  transform: rotate(0);
}
```
