### ISSUE TITLE
[Bug Report] Misalignment text in v-data-table with v-icon

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#4449]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Create table cell with v-icon

### Expected Behavior
On rc-2 and and below everything is ok

### Actual Behavior
text alignment

### Reproduction Link
[https://codepen.io/Buzzzzer/pen/VdgNNY](https://codepen.io/Buzzzzer/pen/VdgNNY)

**Comment by jacekkarczmarczyk** [comment]
because <https://github.com/vuetifyjs/vuetify/commit/52a5f077f2bbdcf7d7c850376f54a8057c11e269>

**Comment by johnleider** [comment]
This was made as an overall QoL improvement for the entire framework. I'd argue the previous version didn't look very well either way:

![image](https://user-images.githubusercontent.com/9064066/42166874-fb20c4cc-7dd1-11e8-8a84-b5b0ffd93f7a.png)

Example of workaround: https://codepen.io/johnjleider/pen/ZRPQzK

![image](https://user-images.githubusercontent.com/9064066/42166902-0aae44b4-7dd2-11e8-8a19-2001847bd5a1.png)
