### ISSUE TITLE
Error getting while creating project using webpack sample 

### ISSUE THREAD

**Issue by vishwasrao** [vuetifyjs/vuetify#445]
Hi ,
I am trying to create new project using webpack sample template.
but getting below error
> vue-cli · Failed to download repo vuetifyjs/webpack: self signed certificate in certificate chain

Tried by `npm config set strict-ssl false`

### Steps to reproduce
Run command `sudo vue init vuetifyjs/webpack hellovuetify`
### What is expected ?

Project should be created successfully.

### What is actually happening ?

Getting error
`vue-cli · Failed to download repo vuetifyjs/webpack: self signed certificate in certificate chain`

**Comment by mfferreira** [comment]
@vishwasrao It works fine here. That looks like an issue either with your npm or your vue-cli installation.

Pro tip: you shouldn't need to use "sudo" to bootstrap your projects.
