### ISSUE TITLE
[Bug Report] V-edit-dialog broke content aligment

### ISSUE THREAD

**Issue by AlexKovynev** [vuetifyjs/vuetify#4450]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create datatable, align column right

### Expected Behavior
align right

### Actual Behavior
align left

### Reproduction Link
[https://codepen.io/anon/pen/oymRxj?&editors=101](https://codepen.io/anon/pen/oymRxj?&editors=101)

**Comment by KaelWD** [comment]
0d8c97ed39c64f9cbc671272960eb8013080f281

**Comment by AlexKovynev** [comment]
Wtf?:( It's not a fix. Try your own example https://vuetifyjs.com/ru/components/data-tables.
