### ISSUE TITLE
[Bug Report] Theme configuration doesn't apply

### ISSUE THREAD

**Issue by kulikala** [vuetifyjs/vuetify#4452]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Mac OS 10.13

### Steps to reproduce
This is working reproduction:
https://codepen.io/anon/pen/NzJKYB

### Expected Behavior
Before v1.1 Vuetify bootstraps up without Vue, so I configure Vuetify to use custom theme in the following way:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Working example</title>
  <link rel="stylesheet" href="https://unpkg.com/vuetify@1.0.19/dist/vuetify.css">
</head>
<body>
  <div id="app">
    <v-app>
      <v-content>
        <v-btn class="primary">Primary colored button</v-btn>
      </v-content>
    </v-app>
  </div>
  <script src="https://unpkg.com/vuetify@1.0.19/dist/vuetify.js"></script>
  <script src="https://unpkg.com/vue@2.5.16/dist/vue.js"></script>
  <script>
  Vue.use(Vuetify, {
    theme: {
      primary: '#cc9900'
    }
  })

  new Vue({
    el: '#app'
  })
  </script>
</body>
</html>
```

This is documented way to modify theme colors:
https://vuetifyjs.com/ja/style/theme

### Actual Behavior
After v1.1 Vuetify seems to require Vue when bootstraping, so I need to load Vue before Vuetify.

Vuetify automatically installs Vuetify to Vue, and custom theming is just ignored because Vuetify is already installed.

```html
<!DOCTYPE html>
<html>
<head>
  <title>Reproduction example</title>
  <link rel="stylesheet" href="https://unpkg.com/vuetify@1.1.1/dist/vuetify.css">
</head>
<body>
  <div id="app">
    <v-app>
      <v-content>
        <v-btn class="primary">Primary colored button</v-btn>
      </v-content>
    </v-app>
  </div>
  <script src="https://unpkg.com/vuetify@1.1.1/dist/vuetify.js"></script>
  <!-- Vuetify throws error: TypeError: vue__WEBPACK_IMPORTED_MODULE_0___default.a is undefined -->
  <script src="https://unpkg.com/vue@2.5.16/dist/vue.js"></script>
  <script>
  Vue.use(Vuetify, {
    theme: {
      primary: '#cc9900'
    }
  })

  new Vue({
    el: '#app'
  })
  </script>
</body>
</html>
```

### Reproduction Link
[https://codepen.io/anon/pen/dKrbKO](https://codepen.io/anon/pen/dKrbKO)

### Other comments
If there's another way to modify theme colors in new Vuetify, I'd like to know.

**Comment by bestickley** [comment]
I'm having the same issue.

**Comment by KaelWD** [comment]
This is because Vuetify automatically registers itself if `window.Vue` is detected. I wanted to remove this behaviour in 1.0 but John was against it as it would have been a breaking change. There are already plans to overhaul the bootstrapping process to resolve some SSR issues, so you will just have to load vue first and modify `this.$vuetify` until that is released.

**Comment by HamadaFMahdi** [comment]
> I'm having the same issue.
> A workaround is to edit the theme colors in your App.vue's created() function with:
> `this.$vuetify.theme.primary = "#cc9900"`

This doesn't seem to work when I try it :/

**Comment by stamri** [comment]
Sam here: this.$vuetify.theme.primary does not fix it. This seems like a serious bug...unable to change themes....

**Comment by bestickley** [comment]
You need to put `this.$vuetify.theme.primary in the `created()` function on your `App.vue`
At least that's what works for me.

**Comment by jacekkarczmarczyk** [comment]
@stamri we kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by stamri** [comment]
Yep that worked. Thanks!
