### ISSUE TITLE
[Bug Report] Textarea counter color is wrong when theme is light and app theme is dark

### ISSUE THREAD

**Issue by abelovic** [vuetifyjs/vuetify#4453]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
- Add dark theme attribute to app
- Add light theme attribute to the textarea component

### Expected Behavior
The textarea counter color should be black

### Actual Behavior
Textarea color is white

### Reproduction Link
[https://codepen.io/ad_bel/pen/zabKVy](https://codepen.io/ad_bel/pen/zabKVy)

### Other comments
This works correctly in reverse i.e. the app theme is set to light and the textarea is set to dark (or light)

**Comment by jacekkarczmarczyk** [comment]
Same for label https://codepen.io/anon/pen/JZzWPL?editors=1000

**Comment by KaelWD** [comment]
And icons: #4462
