### ISSUE TITLE
[Bug Report] focus() input inside a menu not working

### ISSUE THREAD

**Issue by deiucanta** [vuetifyjs/vuetify#4454]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.3

### Steps to reproduce
click on the "v-menu" button"

### Expected Behavior
when I click the "v-menu" button I expect the input to be focused

### Actual Behavior
it's not focused

### Reproduction Link
[https://codepen.io/deiucanta/pen/VdRKJY](https://codepen.io/deiucanta/pen/VdRKJY)

**Comment by yanzijun** [comment]
I don't know why they are difference between `v-dialog` and `v-menu`.
And I have a way to solve it. But I think that it isn't the best way.

1. Watch the v-model variable, if `true` detect height of element.
2. If element height isn't 0, call focus.
3. I used a loop, it would check 3 times, every time delay 50 ms.

Usually, it just run once. Sometimes it would loop twice or more.
But I think there is a better way to solve it.

**Comment by jacekkarczmarczyk** [comment]
Updated pen for 2.0 https://codepen.io/anon/pen/JqeLgK?editors=1010

**Comment by johnleider** [comment]
For now here is a workaround: https://codepen.io/johnjleider/pen/mZOqNL?editors=1010

There are quite a few components that could technically benefit from this and unfortunately this is not something that we can get done in time for v2.0.

**Comment by mismith** [comment]
Any progress on this?

**Comment by DevSlick** [comment]
@johnleider Thanks! This is the only solution I found that actually worked!

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
