### ISSUE TITLE
[Bug Report] Text field has excessive vertical height but only in Chrome, not Firefox or even CodePen

### ISSUE THREAD

**Issue by jameycribbs** [vuetifyjs/vuetify#4456]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Linux x86_64

### Steps to reproduce
1.  HTML code works fine in codepen, even if you are running Chrome, but if you copy the html from codepen and save it to a html page and then open that page in Chrome, you should see the bottom of the text field pushed down off the bottom of the screen.  It actually works fine in Firefox.

### Expected Behavior
Should see the "Active Applications" and the text field line next to each other at the top of the screen.

### Actual Behavior
The "Active Applications" h2 is aligned halfway down the screen and the bottom line of the text field is aligned all the way to the bottom of the screen.

### Reproduction Link
[https://codepen.io/jameycribbs/pen/WymRNP?editors=1000](https://codepen.io/jameycribbs/pen/WymRNP?editors=1000)

### Other comments
Again, this was working in Chrome before 1.1.0 was released.  And, again, this currently works just fine in Firefox, but not in Chrome.

**Comment by VinceWilkie** [comment]
I'm seeing the same issue. Changing `height: 100%` to `height: auto` on `.v-text-field__slot` works but then I am also seeing an issue with `height: 100%` on `.v-menu__activator`. More specifically, when I'm trying to use vuetify date pickers (eg `v-menu` containing `v-text-field` and `v-date-picker`). Changing `.v-menu__activator` to `height: auto` also seems to work.

**Comment by ibbtek** [comment]
I also have the same issue with v-text-field and v-select.

This actually prevents me to update vuetify to version 1.1.x and to get advantage of all the new features and updates related to those versions.

A fix to this will be really appreciate

**Comment by sgehrman** [comment]
I have a clue.   I've noticed problems with setting the height: 100% inside a flexbox
so if you inspect the v-text-field__slot
and uncheck height: 100% it is OK
I've had this same issue for years, but never figured out why
works fine running in webpack-dev-server.

I would suggest removing the height: 100%; I don't think it's needed.  But I would like to know why this happens.

**Comment by Balour** [comment]
+1 I have the same 

My firefox looks fine but Chrome has the same problem as OP

My template looks like this, it's nothing fancy but it's doing the bug described above
      <v-container fluid grid-list-md>
        <v-layout column>
          <v-subheader>Informations formulaire</v-subheader>

          <v-slide-y-transition>
            <v-progress-linear :indeterminate="true" v-if="loading"></v-progress-linear>
          </v-slide-y-transition>

          <v-layout row>
            <v-flex>
              <v-text-field label="No. soumission" v-model="seq_form_data" readonly></v-text-field>
            </v-flex>
            <v-flex>
              <v-text-field label="Statut" v-model="statut" readonly></v-text-field>
            </v-flex>
            <v-flex>
              <v-text-field label="Créé le" v-model="dte_creation" readonly></v-text-field>
            </v-flex>
            <v-flex>
              <v-text-field label="Modifié le" v-model="dte_modification" readonly></v-text-field>
            </v-flex>
          </v-layout>

          <v-textarea label="Remarque publique" rows="1" auto-grow v-model="remarque_publique"></v-textarea>

          <v-textarea label="Remarque privée" rows="1" auto-grow v-model="remarque_prive"></v-textarea>
        </v-layout>
    </v-container>
  </div>

**Comment by sgehrman** [comment]
```
 https://github.com/philipwalton/flexbugs/issues/197   
https://github.com/philipwalton/flexbugs/issues/84
https://stackoverflow.com/questions/38991662/100-height-when-parent-is-flex-item-chrome-bug
```

**Comment by sgehrman** [comment]
Is this going to be fixed?  I'm trying to ship a product.  Just remove the unnecessary height: 100%.  It's not valid css.

**Comment by savitadwr** [comment]
Sorry, its not yet fixed. v-select 100% height issue, that I found is from 

> src/stylus/components/_small-dialog.styl

class: `.v-menu__activator`
