### ISSUE TITLE
[Bug Report] Missed v- prefix for table row hover

### ISSUE THREAD

**Issue by Punknium** [vuetifyjs/vuetify#4458]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
Expand a row in a datatable

### Expected Behavior
It doesn't have a hover background color.

### Actual Behavior
It has a hover background color.

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_tables.styl#L25](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_tables.styl#L25)

### Other comments
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_tables.styl#L25

**Comment by jacekkarczmarczyk** [comment]
96d262d2d85827ab2d3f3645d02cef3864a29696
