### ISSUE TITLE
[Bug Report] Width around child elements become larger cause content format crushed

### ISSUE THREAD

**Issue by jiangtianyu2009** [vuetifyjs/vuetify#4459]
### Versions and Environment
**Vuetify:** 1.1.0
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
The example in [codepen](https://codepen.io/jiangtianyu/pen/mKoLeg) is working on 1.0.19, you can find the width arround 'Search Element' is quite narrow, then change the version to 1.1.0, the width arround becames bigger.

### Expected Behavior
Expect the width arround child element stay narrow in new version.

### Actual Behavior
The width arround child element became bigger, this caused my content format crushed.

### Reproduction Link
[https://codepen.io/jiangtianyu/pen/mKoLeg](https://codepen.io/jiangtianyu/pen/mKoLeg)

**Comment by KaelWD** [comment]
v-container now always has 24px padding. You should add `pa-2` if you want to set it back to 8px.
