### ISSUE TITLE
[Feature Request] Bring back $vnode.data.model.expression on v-input

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#4460]
### Problem to solve
I have some code in a mixin which programatically assigns validation rules to v-input components during the mounted event. This code relies on v-input's $vnode.data.model.expression to get the v-model name used to bind the input. In versions prior to 1.1.1, this code worked great. In version 1.1.1 $vnode.data no longer contains the model property.

### Proposed solution
Bring back $vnode.data.model.expression on v-input or provide an alternative method of determining the  v-model name used to bind an input.

**Comment by KaelWD** [comment]
😒 vuejs/vue#8436

**Comment by KaelWD** [comment]
I can't figure out how to fix this, there doesn't seem to be a way to allow `v-model="" @input=""` *and* prevent the double-emit. 

```js
// Updates the model twice
if (data.model) {
  delete data.props.value
}
```

```js
// Prevents `@input` from firing
if (data.model) {
  delete data.props.value
  data.on && delete data.on.input
}
```

**Comment by logaretm** [comment]
VeeValidate also relies on either finding the `v-model` directive data in the array of directives (in case of html inputs) or the `data.model` prop to handle v-model bound components. Currently there is no way to find the bound model to the input.

@KaelWD I took a look at the issues linked here and there seem to be no solution until the PR is merged, have you found a way to solve this issue?

**Comment by KaelWD** [comment]
Had another go at it, found a fix. 

Playground for future me:
```vue
<template>
  <v-app>
    <v-container>
      <v-text-field v-model="model" @input="log"></v-text-field>
    </v-container>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      internal: ''
    }),
    computed: {
      model: {
        get () { return this.internal },
        set (val) {
          console.log('set', val)
          this.internal = val
        }
      }
    },
    methods: {
      log (e) {
        console.log('log', e)
      }
    }
  }
</script>
```
