### ISSUE TITLE
[Bug Report] solo textfields do not have border-radius

### ISSUE THREAD

**Issue by darylteo** [vuetifyjs/vuetify#4463]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Sorry @KaelWD if there is a dupe for this already. This is the same codepen as I posted before, but this time it's regarding the v-input__slot style. It has a margin-bottom, which makes the control not vertically aligned in a v-toolbar. 

I'm not sure if it is related to https://github.com/vuetifyjs/vuetify/issues/4420, as that relates to "side" margins, not bottom. 

### Expected Behavior
Should be vertically centered.

### Actual Behavior
It's 5-ish px above where it should be.

### Reproduction Link
[https://codepen.io/anon/pen/ERMpVP?&editors=101](https://codepen.io/anon/pen/ERMpVP?&editors=101)

**Comment by darylteo** [comment]
Also, missing a 2px border-radius that was in 1.0.x.

**Comment by KaelWD** [comment]
The margin is intentional so we can show hints. I don't think there's been any closed issues for it, but the response on discord has been to use `hide-details` in toolbars. The missing border-radius looks like an oversight.

**Comment by darylteo** [comment]
hide-details works =) thanks @KaelWD.

I'll update title re: border-radius.

**Comment by florianrubel** [comment]
`hide-details` didn't work for me. Text field still sticks to the top.

**Comment by darylteo** [comment]
@florianrubel works for me IN the toolbar. There is a toolbar specific style for it.

However, it doesn't seem to achieve it's expected behaviour when using "solo" and "hide-details" - the text-details element is still there, and has a margin, despite it being display: none. Weird stuff. @KaelWD  

I'm going to just hide that element directly anyway since i'm wrapping it in my component.

**Comment by KaelWD** [comment]
`hide-details` will be fixed by #4429
