### ISSUE TITLE
[Bug Report] v-slider unresponsive to changes via click on track

### ISSUE THREAD

**Issue by racer01** [vuetifyjs/vuetify#4464]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Windows 10

### Steps to reproduce
Click on the grey and blue tracks a couple times back and forth to change v-slider's value. 
I also tested in Chrome (67) and it works as expected. 

### Expected Behavior
Change slider value if I click anywhere inside input's boundaries. 

### Actual Behavior
If I click on the v-slider's track to change its value, sometimes it took me 2-3 clicks to change.

### Reproduction Link
[https://codepen.io/anon/pen/LraqRP](https://codepen.io/anon/pen/LraqRP)

### Other comments
I increased the track height on the second slider so it's easier to click on; also it is clear that this bug comes up only if I click on the track.

**Comment by KaelWD** [comment]
Can't reproduce, using FF 60 too. Increasing track height like that has no effect, the click target is an invisible `<input>` element.

**Comment by racer01** [comment]
I successfully reproduced it on another machine in Firefox 60. I noticed that there are more events in Vue dev tools when changing slider value is successful.

![vuetify-bug 4464](https://user-images.githubusercontent.com/14020544/42222003-46b63838-7ed4-11e8-8e16-07df9cd3066b.png)

You are right, increasing height doesn't effect functionality; it is only unresponsive in the middle 2 pixels of the track.

I also modified the codepen to log mouse clicks and position, and when slider is not working the event handler isn't being called either.
The top slider is unresponsive every time if `89 <= clientY <= 91`
and the bottom one if `141 <= clientY <= 143`. It only changes on second click if I haven't moved my mouse cursor.
I recorded this bug in action: https://gfycat.com/TenderAppropriateAyeaye

**Comment by racer01** [comment]
It works as expected if I untick all of these 3 rules. 
![vuetify-bug 4464 2](https://user-images.githubusercontent.com/14020544/42247824-c6913b90-7f22-11e8-83cb-47d8356c31ae.png)

**Comment by KaelWD** [comment]
So firefox is well retarded: https://codepen.io/anon/pen/wxPxPp

Those rules are part of our CSS reset (), and even overriding them back to `initial` doesn't change the slider back to its default style. Seems like just having them present will cause firefox to use a different style of slider that doesn't play nice with click events. 
The slider does need refactoring to use proper native events instead of re-implementing the native behaviour, but I'm working around it for now by going back to a text input internally instead.
