### ISSUE TITLE
[Bug Report] Modal does not work in v-progress v-dialog sample

### ISSUE THREAD

**Issue by xdoo** [vuetifyjs/vuetify#4466]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Linux x86_64

### Steps to reproduce
- click on 'START LOADING'
- wait for dialog
- click on 'CLICK ME' while dialog is open

### Expected Behavior
While the dialog with property 'persistent' is open, you shoul NOT be able to click the 'CLICK ME' button. So the 'my clicks' printout should always be 0.

### Actual Behavior
I can click the 'CLICK ME' button while the dialog is open. The 'my clicks' printout counts my clicks.

### Reproduction Link
[https://codepen.io/clausstraube/pen/RJObYK](https://codepen.io/clausstraube/pen/RJObYK)

### Other comments
You can see this n your sample site as well: https://vuetifyjs.com/en/components/dialogs#example-loader

**Comment by jacekkarczmarczyk** [comment]
hide-overlay for persistent dialog should create a transparent overlay, dialog shaking is not working as well
