### ISSUE TITLE
[Bug Report] Tabs component is not reactive to removal of tabs or resetting active tab

### ISSUE THREAD

**Issue by JamesDeegan** [vuetifyjs/vuetify#4467]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
First off, the active tab on page load should be the tab at index 5, yet the first tab is active.
Next, try selecting the right most tab, labelled "seven" then click the button to remove tabs, notice the slider does not move. 

### Expected Behavior
Firstly the 5th tab should be active, labelled "Six"
and secondly when removing tabs the slider should update, and also the activeTab should be reset to tab 1 as specified in the clickToggle method

### Actual Behavior
Cannot set activeTab, and the slider does not update when removing tabs

### Reproduction Link
[https://codepen.io/anon/pen/JZVPqG?page=1&](https://codepen.io/anon/pen/JZVPqG?page=1&)

**Comment by johnleider** [comment]
`:v-model` is not a thing

https://codepen.io/johnjleider/pen/JZVoJZ?editors=1111

**Comment by JosuaMeier** [comment]
@johnleider your example is not working too. Slider does not move.

Have the same Issue.
When removing a tab the tab item is not displaying correctly.
Even when setting the activeTab explicit after removing a tab.

Reproduction Link: https://codepen.io/josuameier/pen/qyJyyq

ps: shall i open another bug/issue?

**Comment by haugero** [comment]
@johnleider I have the same issue. Do you have an idea for a workaround in case a fix will take some more time?

**Comment by johnleider** [comment]
Not really, and the new `v-item-group` (which is what all components like `v-tabs` are going to) may have the same limitation. I'll tag this as v1.3 to keep it in mind.

**Comment by johnleider** [comment]
This has been fixed and is working for v1.3

![tabs](https://user-images.githubusercontent.com/9064066/46834389-e9f55200-cd70-11e8-9d93-2213fe6d53f3.gif)
