### ISSUE TITLE
[Bug Report] Solo Textfield is not vertically centered in the Toolbar

### ISSUE THREAD

**Issue by castilh0s** [vuetifyjs/vuetify#4471]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Opera
**OS:** Linux

### Steps to reproduce
It was like this before the update: https://i.imgur.com/Z8anooX.jpg
And as it has now: https://i.imgur.com/gSEAiEb.jpg

It is not vertically centralized like before.

### Expected Behavior
Should expect the textfield will be vertically centered.

### Actual Behavior
The textfield currently has the bottom margin larger than the top margin.

### Reproduction Link
[https://codepen.io/castilh0s/pen/eKoZLX](https://codepen.io/castilh0s/pen/eKoZLX)

**Comment by johnleider** [comment]
This is because in v1.0 solo fields did not support having messages. With the refactor these are now supported and add spacing below the field.

You can simply hide it with **hide-details**

https://codepen.io/johnjleider/pen/XYQKYK
