### ISSUE TITLE
[Bug Report] Cursor still wrong for text fields

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4473]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
Create a text field with label.

### Expected Behavior
Cursor should be text

### Actual Behavior
Cursor is default

### Reproduction Link
[https://codepen.io/anon/pen/RJOpbe](https://codepen.io/anon/pen/RJOpbe)

### Other comments
Following CSS fixes it:
```
.v-input.v-text-field .v-label:not(.v-label--active) {
    cursor: text;
}
```

**Comment by 06b** [comment]
This appears to have been fixed in the v.1.1.10 release via commit 74ff691
