### ISSUE TITLE
[Bug Report] Decrease label font size in <v-text-field>

### ISSUE THREAD

**Issue by kamleshkatpara** [vuetifyjs/vuetify#4474]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
tried to modify in css but doesn't work

### Expected Behavior
decrease v-label font size

### Actual Behavior
        <v-text-field
            label="Regular"
            single-line
          ></v-text-field>

### Reproduction Link
[https://codepen.io/kamleshkatpara/pen/yErMog](https://codepen.io/kamleshkatpara/pen/yErMog)

**Comment by rgalaxy** [comment]
It works just fine in my screen, you mean the radio button label?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by kamleshkatpara** [comment]
@rgalaxy check my site it does not work their offerdev.herokuapp.com
I am talking about the label of a text input field <v-text-field>
