### ISSUE TITLE
[Bug Report] TS2709: Cannot use namespace 'VuetifyDirective' as a type.

### ISSUE THREAD

**Issue by vitaliypva** [vuetifyjs/vuetify#4476]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows

### Steps to reproduce
We are using vuetify in typescript project. After  updating to 1.1.1 build crashes with an error:
 
```
ERROR in [at-loader] ./node_modules/vuetify/types/alacarte.d.ts:31:16 
2018-07-03T04:42:52.1375440Z         TS2709: Cannot use namespace 'VuetifyDirective' as a type.
```

**Comment by vitaliypva** [comment]
when I replace content of the file alacarte.d.ts with this, everything starts working :



declare module 'vuetify/es5/components/Vuetify' {
  import Vuetify from 'vuetify'

  export default Vuetify
}

// TODO: transitions
declare module 'vuetify/es5/components/*' {
  import { PluginFunction, PluginObject, VueConstructor, ComponentOptions } from 'vue'

  interface PluginConstructor extends VueConstructor {
    install: PluginFunction<never>
  }

  const Component: {
    default: PluginConstructor,
    [key: string]: PluginConstructor
  }

  export = Component
}

declare module 'vuetify/es5/directives' {
  import { PluginFunction, DirectiveOptions } from 'vue'
  import { VuetifyDirective } from 'vuetify'

  const ClickOutside: DirectiveOptions
  const Ripple: DirectiveOptions
  const Resize: DirectiveOptions
  const Scroll: DirectiveOptions
  const Touch: DirectiveOptions

  const Plugin: PluginFunction<never>

  export {
    ClickOutside,
    Ripple,
    Resize,
    Scroll,
    Touch
  }
  export default Plugin
}

**Comment by KaelWD** [comment]
Do you have a sample project to demonstrate this? What version of typescript/webpack/at-loader are you using? Do you have any other plugins or declarations that might be conflicting with that?

**Comment by vitaliypva** [comment]
typescript: 2.7
webpack: ^3.11.0

unfortunately I do not have a sample project

ср, 4 лип. 2018 о 15:21 Kael <notifications@github.com> пише:

**Comment by vitaliypva** [comment]
I have updated to  typescript: 2.9.2 to no avail

ср, 4 лип. 2018 о 15:54 Vitaliy Podstreshniy <vitaliypva@gmail.com> пише:

**Comment by vitaliypva** [comment]
fixed it by adding
"es2018" to lib array in tsconfig.json

Please close the bug

ср, 4 лип. 2018 о 16:07 Vitaliy Podstreshniy <vitaliypva@gmail.com> пише:

**Comment by henres** [comment]
Hello,

I still have the same error.
vuetify 1.1.1

my tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "node",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "es2018",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by KaelWD** [comment]
disable `allowSyntheticDefaultImports`?

**Comment by henres** [comment]
Still the same @KaelWD

**Comment by KaelWD** [comment]
I'll need answers to [these questions](https://github.com/vuetifyjs/vuetify/issues/4476#issuecomment-402366242) then.

**Comment by henres** [comment]
Ok, my bad, i let a `declare module 'vuetify'` in a d.ts.
Sorry for the inconvenient.

Have a nice day
