### ISSUE TITLE
[Bug Report] v-autocomplete - append-icon is "there" even when set to empty (which pushes clear icon to the left)

### ISSUE THREAD

**Issue by darylteo** [vuetifyjs/vuetify#4477]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
https://codepen.io/anon/pen/VdNQGe?&editors=101

### Expected Behavior
The clear icon appears where append-icon should be

### Actual Behavior
It appears to the left of append-icon, even when append-icon is empty

### Reproduction Link
[https://codepen.io/anon/pen/VdNQGe?&editors=101](https://codepen.io/anon/pen/VdNQGe?&editors=101)

**Comment by KaelWD** [comment]
For future me: `<v-autocomplete append-icon="" clearable :items="['a', 'b', 'c']"></v-autocomplete>`
