### ISSUE TITLE
[Bug Report] The filters in v-data-table do not work

### ISSUE THREAD

**Issue by AntoninSlejska** [vuetifyjs/vuetify#4480]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Windows 10

### Steps to reproduce
In a data table add:

    :filter="filterItems"
    :custom-filter="customFilter"

Add the following methods:

    methods: {
      filterItems(val, search) {
        console.log(val);
      },
      customFilter(items, search, filter) {
        console.log(items);
      }
    }

### Expected Behavior
In the console, the log messages should be displayed.

### Actual Behavior
No messages are displayed in the console.

### Reproduction Link
[https://codepen.io/antoninslejska/pen/qKwBda?editors=1011](https://codepen.io/antoninslejska/pen/qKwBda?editors=1011)

### Other comments
I try to find a way how to filter data in a data table. See: https://stackoverflow.com/q/51156800/3886962

**Comment by KaelWD** [comment]
`customFilter` is only called if you're using the `search` prop, and it gets passed `filter` as the third argument. The API is a bit confusing and difficult to use, but it is being improved for a future release.

**Comment by AntoninSlejska** [comment]
Thanks. But why does not work the ':filter' as well?

**Comment by nekosaur** [comment]
Because you are overriding the `custom-filter` function, which in the default implementation is the one calling the `filter` function.
