### ISSUE TITLE
[Bug Report] v-autocomplete fires change event twice

### ISSUE THREAD

**Issue by StefanFeederle** [vuetifyjs/vuetify#4481]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
Select an employee, @change is called
Switch to the next input with tab or by clicking on it, @change is called again

### Expected Behavior
blurring an input should not fire change event

### Actual Behavior
fires change event on blur

### Reproduction Link
[https://codepen.io/anon/pen/yErxVJ](https://codepen.io/anon/pen/yErxVJ)

### Other comments
This may be related to https://github.com/vuetifyjs/vuetify/pull/1251

**Comment by KaelWD** [comment]
1.0.19: https://codepen.io/anon/pen/XYQxdB?editors=1010
