### ISSUE TITLE
[Bug Report] Disabled button dark not visible

### ISSUE THREAD

**Issue by AGPDev** [vuetifyjs/vuetify#4482]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
Change disabled button to dark

### Expected Behavior
Show like in light or option to change color disabled in dark mode

### Actual Behavior
no

### Reproduction Link
[https://codepen.io/anon/pen/RJOwNZ?&editors=100](https://codepen.io/anon/pen/RJOwNZ?&editors=100)

**Comment by AGPDev** [comment]
Sugestion: Use same or equivalent color in both case.

**Comment by johnleider** [comment]
Dark shouldn't specifically be used to make text white. My rule of thumb is whatever color background the element is on. In this case you should opt to use `class="white--text"`.

**Comment by rromanv** [comment]
`<v-btn color="green lighten-1" :dark="valid" :disabled="!valid">Save</v-btn>`
This is my workaround

**Comment by PJLindsay** [comment]
for me, this issue reared it's head when vuetify bumped from 2.1.9 to 2.2.11 what is especially odd - is *both* my Cancel and Save buttons disappeared (an enabled one and a disabled one) and then *would not re-appear* once the validity changed -- did not happen in 2.1.9 but did happen in 2.2.11 @rromanv thanks for your great workaround - this fixed it for me

**Comment by kaan-atakan** [comment]
> Dark shouldn't specifically be used to make text white. My rule of thumb is whatever color background the element is on. In this case you should opt to use `class="white--text"`.

What exactly is the point of having the `dark` prop if we aren't supposed to use it? It seems obvious to me that this is a real issue from the sheer number of duplicates. Even if fixing it is not a priority for you, why not leave it open so someone can send a PR?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
