### ISSUE TITLE
[Bug Report] Click prevention for a checkboc

### ISSUE THREAD

**Issue by kakulukia** [vuetifyjs/vuetify#4485]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Use the reproduction link.

### Expected Behavior
I should be able to stop the checkbox from being activated.

### Actual Behavior
I cant stop the click event.

### Reproduction Link
[https://jsfiddle.net/ag63f9fm/49/](https://jsfiddle.net/ag63f9fm/49/)

**Comment by KaelWD** [comment]
You should use [capture](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture): https://jsfiddle.net/ag63f9fm/55/

**Comment by kakulukia** [comment]
Thx for solving the issue! 
But even according to your capture article stopPropagation() should have worked. Do you know why it did not in this case?

Id like to understand what happened here.
