### ISSUE TITLE
[Bug Report] Disabled v-text-field don't display dotted underline in IE

### ISSUE THREAD

**Issue by tommcgee** [vuetifyjs/vuetify#4486]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.2
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
1. Create a `v-form` with a disabled `v-text-field` inside.

### Expected Behavior
The dotted underline appears underneath the `v-text-field` like normal

### Actual Behavior
There is no dotted underline under the `v-text-field`.

### Reproduction Link
[https://codepen.io/tommcgee/pen/GGaRJE](https://codepen.io/tommcgee/pen/GGaRJE)

### Other comments
The example is taken directly from [the documentation](https://vuetifyjs.com/en/components/text-fields#example-disabled-and-readonly).

**Comment by tommcgee** [comment]
Is there a reason we use a `background-image: linear-gradient` vs a `border: dotted 1px` or similar? (Especially since it seems there's issues with IE using the former)

**Comment by KaelWD** [comment]
Fixed by 2dec42a and d95a80ad
