### ISSUE TITLE
[Bug Report] Input Field with prefix and outline

### ISSUE THREAD

**Issue by delueg** [vuetifyjs/vuetify#4487]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.12.4

### Steps to reproduce
v-textfield with prefix and outline

### Expected Behavior
functional layout

### Actual Behavior
broken layout

### Reproduction Link
[https://codepen.io/delueg/pen/BVeawV?editors=1100](https://codepen.io/delueg/pen/BVeawV?editors=1100)

### Other comments
maybe

.v-input--is-focused.v-text-field--outline .v-text-field__prefix,
.v-input--is-dirty.v-text-field--outline .v-text-field__prefix{
    top: 10px;
    position: relative; 
}

**Comment by aggarwaldev** [comment]
@delueg @johnleider This bug was fixed along with #3485 via commit a438ccde106ba198bee1c4f46e9288adee8b419a

**Comment by johnleider** [comment]
Closed via a438ccd
