### ISSUE TITLE
[Bug Report] Prop tabindex on v-radio-group and v-radio is ignored (always rendered as default tabindex="0")

### ISSUE THREAD

**Issue by vizo** [vuetifyjs/vuetify#4490]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Linux x86_64

### Steps to reproduce
Provided codepen.

### Expected Behavior
tabindex value should be the same as provided.

### Actual Behavior
Prop tabindex on v-radio-group and v-radio is ignored - always rendered as default tabindex="0".

### Reproduction Link
[https://codepen.io/vizo/pen/XYwjwV?&editors=101](https://codepen.io/vizo/pen/XYwjwV?&editors=101)

**Comment by KaelWD** [comment]
Doesn't appear to be a new bug: https://codepen.io/anon/pen/dKEeQq?editors=1010

**Comment by vizo** [comment]
It works in v1.0, but not in v1.1.1.
