### ISSUE TITLE
[Bug Report] V-scroll target options not working

### ISSUE THREAD

**Issue by dysol** [vuetifyjs/vuetify#4491]
### Versions and Environment
**Vuetify:** 1.1.0
**Vue:** 2.5.13
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
- Add v-scroll:#theTarget="onScroll"
- Scroll the container

### Expected Behavior
Scrolling to output something

### Actual Behavior
No output

### Reproduction Link
[https://codepen.io/anon/pen/VdObJe](https://codepen.io/anon/pen/VdObJe)

**Comment by KaelWD** [comment]
`#test` isn't being scrolled,`html` is. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
