### ISSUE TITLE
[Feature Request] Documentation missing about Focus, Blur Event on v-select

### ISSUE THREAD

**Issue by rajagopalx** [vuetifyjs/vuetify#4492]
### Problem to solve
Currently, there is no event for focus and blur event on v-select. 

### Proposed solution
Like in element-ui, we can include focus and blur event in v-select. 

http://element.eleme.io/#/en-US/component/select#select-events

**Comment by rajagopalx** [comment]
It's included in 1.1. But missing in the documentation. Thanks to nekosaur.

**Comment by KaelWD** [comment]
This repository is for bugs and feature requests, documentation issues should be reported on the vuetify.com board.
