### ISSUE TITLE
[Bug Report] Dynamic rendering of <v-carousel> items

### ISSUE THREAD

**Issue by neilcuetz** [vuetifyjs/vuetify#4493]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Mac OS 10.12

### Steps to reproduce
1. Click the Load New Button
2. Look on the console logs to check if it was working
3. See the carousel if the image will be loaded

### Expected Behavior
The image will show on the carousel

### Actual Behavior
The image is not showing, and saw on the inspector that it was always "display: none"

### Reproduction Link
[https://codepen.io/neilcuetz/pen/eKaGWr?&editors=101](https://codepen.io/neilcuetz/pen/eKaGWr?&editors=101)

### Other comments
using "push" on array seems to be working but directly equating a value from another value is the problem

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by mdsaudali365** [comment]
Hi! Are you sure it works with the push? I have opened #5102 as the push did not work for me.
