### ISSUE TITLE
[Bug Report] Validation validate-on-blur calls rule functions on input

### ISSUE THREAD

**Issue by ecmel** [vuetifyjs/vuetify#4494]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Add validate-on-blur on a v-text-field

### Expected Behavior
Rule functions should be called upon blur

### Actual Behavior
Rule functions are called on every input

### Reproduction Link
[https://codepen.io/ecmel/pen/XYwqWd?editors=1111](https://codepen.io/ecmel/pen/XYwqWd?editors=1111)

**Comment by KaelWD** [comment]
This might be intentional, I'll have to check.

**Comment by dishastalker** [comment]
:validate-on-blur="true"
