### ISSUE TITLE
[Bug Report] v-from fail to validate when running tests

### ISSUE THREAD

**Issue by shahar84** [vuetifyjs/vuetify#4496]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Install using vue-cli3
Running jest test using the default test runner

```bash
npm run test:unit
```

```javascript
// SignUp.spec.js
import {mount, createLocalVue} from '@vue/test-utils';
import VueRouter from 'vue-router';
import Vuetify from 'vuetify';
import SignUp from '@/views/SignUp.vue';

describe('SignUp.vue', () => {
    let wrapper;
    const routes = [
        {path: '/signup', name: 'signup'},
    ];
    const router = new VueRouter({routes});
    const localVue = createLocalVue();
    localVue.use(VueRouter);
    localVue.use(Vuetify);
    wrapper = mount(SignUp, {localVue, router});

    test('it should test that the submit button is enabled once the input fields has been filled', async () => {
        const button = wrapper.find('button');
        wrapper.setData({
            email: 'test@gmail.com',
            password: 'password',
        });
        // This is the line that create the error
        wrapper.vm.$refs.form.validate();
        await wrapper.vm.$nextTick();
        expect(button.element.getAttribute('disabled')).toBe(null);
    })
});
```

### Expected Behavior
The test should pass

### Actual Behavior
An error saying:
```bash
    TypeError: Cannot read property 'split' of undefined
```

### Reproduction Link
Sorry

### Other comments
We just updated the version and all of our test suit brock. 
We have been trying to solve this, but it seems that the API has changed

**Comment by OfekA** [comment]
I'm also able to reproduce it, it only happens when running tests.

**Comment by KaelWD** [comment]
You may need to register vuetify and vue-router globally rather than on localVue. This is probably the same as #4068

**Comment by OfekA** [comment]
But it used to work on version 1.0.16

**Comment by KaelWD** [comment]
Yeah but we have to import vue ourselves now, see #4068 for more.

**Comment by danielsarcor** [comment]
Thanks @OfekA. I just downgraded Vuetify to 1.0.16 and no console.error are being thrown when using nextTick (that was the issue for me).
