### ISSUE TITLE
[Bug Report] v-autocomplete not updating items list with asynchronous data

### ISSUE THREAD

**Issue by cozawariat** [vuetifyjs/vuetify#4497]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Type some anime title like "Naruto"

### Expected Behavior
Dropdown should be displayed with items list while typing

### Actual Behavior
Dropdown not visible

### Reproduction Link
[https://codepen.io/anon/pen/aKrRjX?editors=1010](https://codepen.io/anon/pen/aKrRjX?editors=1010)

### Other comments
It's rendering "No data available" even though the items array is updated
The dropdown with the items is actually showing after refocusing the text field.

**Comment by KaelWD** [comment]
Example of this exact thing from discord: https://codepen.io/anon/pen/aKXMxq?editors=1010

You have to skip the filter with `:filter="v => v"`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
