### ISSUE TITLE
[Feature Request] Provide way to highlight search match when using VAutocomplete's item slot

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4499]
### Problem to solve
Currently, the default ```item``` slot will highlight characters that match ```VAutocomplete```'s search value. However, if you use your own ```item``` slot, this behavior goes away.

### Proposed solution
Somehow expose the behavior used for the default ```item``` slot's search match highlighting for use.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/xzoeYq

**Comment by Dylan-Chapman** [comment]
Perfect! Didn't think about that. Appreciate it.
