### ISSUE TITLE
Multiline textboxes?

### ISSUE THREAD

**Issue by sirchas** [vuetifyjs/vuetify#45]
I tried the multiple parameter but still a single line. thanks for your help

**Comment by johnleider** [comment]
What component are you referring to? Could you provide an example of what you are trying to do?

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
