### ISSUE TITLE
[Bug Report] Data iterator regression on pagination width

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4500]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
Compare the items per page selector width:
Version 1.1.0-beta.3: https://codepen.io/anon/pen/dKBbow?&editors=101
Version 1.1.0-rc.1: https://codepen.io/anon/pen/OEeLNP?&editors=101
Version 1.1.1: https://codepen.io/anon/pen/JZQPjZ?&editors=101

### Expected Behavior
Items per page selector should be shrink, like on Version 1.1.0-beta.3: https://codepen.io/anon/pen/dKBbow?&editors=101

![image](https://user-images.githubusercontent.com/1561360/42337734-05c15584-805e-11e8-9c64-f9620d8a8932.png)

### Actual Behavior
Items per page selector width is too large: Version 1.1.1: https://codepen.io/anon/pen/JZQPjZ?&editors=101

![image](https://user-images.githubusercontent.com/1561360/42337769-1e5aafaa-805e-11e8-8f30-d48e78793c20.png)

### Reproduction Link
[https://codepen.io/anon/pen/JZQPjZ?&editors=101](https://codepen.io/anon/pen/JZQPjZ?&editors=101)

### Other comments
Data table looks right and should be tested too

**Comment by KaelWD** [comment]
beta.3 had
```css
.v-select:not(.v-autocomplete) input {
    font-size: 0;
    min-height: 32px;
}
```
