### ISSUE TITLE
[Feature Request] Add autocapitalization to v-text-field

### ISSUE THREAD

**Issue by dansteren** [vuetifyjs/vuetify#4501]
### Problem to solve
When entering text into a v-text-field on a mobile device, the keyboard always starts off with a capital letter (i.e. autocapitalize = sentence). There is no way to have the keyboard autocapitalize each character or each word.

To Reproduce:
Visit the list of components (https://vuetifyjs.com/en/components/text-fields) on a mobile device. Enter text into the text-field and notice that it only autocapitalizes the first word you enter.

### Proposed solution
Fixing this will involve modifying VTextField.js to include an autocapitalize prop that accepts a value in ['off', 'none', 'on', 'sentences', 'words', 'characters']. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize.

You could then use v-text-field like this:
```
<v-text-field autocapitalize="words"></v-text-field>
```

**Comment by KaelWD** [comment]
Did you even try it? vuetifyjs/vuetifyjs.com#501
