### ISSUE TITLE
[Bug Report] Time picker in dialog defaults to selecting minutes after first time opened

### ISSUE THREAD

**Issue by mdciotti** [vuetifyjs/vuetify#4502]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.2
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Click on time field to open dialog.
2. Select hours and minutes.
3. Close dialog.
4. Click on time field again.

### Expected Behavior
The time picker should always default to selecting hours when opened in a dialog or menu. Perhaps, when the dialog is closed, the picker should reset `selectingHour` to `true`.

### Actual Behavior
Opening a time picker in a dialog or menu for the first time shows hours. When I re-open the dialog, it always shows minutes until I specifically click on hours.

### Reproduction Link
[https://codepen.io/anon/pen/aKgzzm?editors=1010#0](https://codepen.io/anon/pen/aKgzzm?editors=1010#0)

### Other comments
Likely related to the issue from [PR 4198](https://github.com/vuetifyjs/vuetify/pull/4198).

**Comment by nekosaur** [comment]
Slight correction. It's not that it always shows minutes after the first time, it's simply that it remembers the last used type.

**Comment by jacekkarczmarczyk** [comment]
Workaround: use `<v-time-picker v-if="menu/dialog model">`

https://codepen.io/anon/pen/gKNqQa?editors=1010#0

**Comment by jacekkarczmarczyk** [comment]
Workaround 2:

https://codepen.io/anon/pen/VBoqaB?editors=1000

Requires `ref` for `v-time-picker` but preserves closing animation

**Comment by jacekkarczmarczyk** [comment]
Needs keep-content-alive prop to be implemented (see #4518)

**Comment by haggys22** [comment]
Looks like this bug is a "reimplementation" of #1549

Can't we just set `this.selecting = selectingTimes.hour` as I've done in e8bac4e?
Maybe put it in `onChange ()` like this:
```
onChange () {
  if (this.selecting === selectingTimes.hour) {
    this.selecting = selectingTimes.minute
  } else if (this.useSeconds && this.selecting === selectingTimes.minute) {
    this.selecting = selectingTimes.second
  } else {
    this.selecting = selectingTimes.hours  // <-- here it goes?
  }
  // ...
}
```

I can't test this right now but maybe tomorrow

**Comment by MartinX3** [comment]
Still happening in 2.4.0

**Comment by dylanoli** [comment]
it happens to me too

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

See https://github.com/vuetifyjs/vuetify/issues/4502#issuecomment-403077205 or https://github.com/vuetifyjs/vuetify/issues/4502#issuecomment-414019808 for workarounds

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
