### ISSUE TITLE
[Feature Request] Datepicker has no box style

### ISSUE THREAD

**Issue by FanrayMedia** [vuetifyjs/vuetify#4503]
### Problem to solve
The new v1.1.1 is great and I'm using many components with the `box style`, but when it comes to the [Datepicker](https://vuetifyjs.com/en/components/date-pickers) I don't see it has the box style, as a result my UI looks inconsistent.

### Proposed solution
Add box style to Datepicker just like a [Text field](https://vuetifyjs.com/en/components/text-fields).

**Comment by jacekkarczmarczyk** [comment]
Date picker is not an input component. You can just add `box` prop to the text field

https://codepen.io/anon/pen/Wyqwvw?&editors=101
