### ISSUE TITLE
[Bug Report] v-select shows blinking keyboard cursor on mobile screen when using "outline" or "solo" props

### ISSUE THREAD

**Issue by chungskie** [vuetifyjs/vuetify#4506]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.2
**Browsers:** Google Chrome, Safari
**OS:** iOS

### Steps to reproduce
Using your mobile device (iPhone X in my case), go to a page with a v-select in use with the "outline" or "solo" prop, or open Codepen from the Vuetify doc for Select (this one has all 4 styles): https://vuetifyjs.com/en/components/selects#usage

Tap on the select element to see its dropdown options.

You'll notice that a blinking keyboard cursor appears on "outline" or "solo" style selects, but not on standard or "box" selects.

### Expected Behavior
Blinking keyboard cursor should not appear on a select element.

### Actual Behavior
Blinking keyboard cursor appears on the select element, like it's a text input.

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/selects/usage.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/selects/usage.vue)

### Other comments
Reproducible on both Safari and Chrome.

**Comment by KaelWD** [comment]
Doesn't happen in android chrome, but does in IE11.

I think this just confirms that safari is the new IE.

**Comment by dinesh-sirvi** [comment]
The blinking cursor also overlaps the drop down on IE. The issue is visible on the vuetify site also. In the select doc page, try any example given there. The cursor will appear before the select pop up

**Comment by jacekkarczmarczyk** [comment]
`.v-select:not(.v-autocomplete) .v-select__slot input { visibility: hidden }` seems to fix it

**Comment by KaelWD** [comment]
That also hides the placeholder if you have one set. 

This is going to require some restructuring of the component, currently the input is focused and accepts keyboard events, this would have to be moved to another element with the proper aria roles instead.

**Comment by johnleider** [comment]
This is not an issue as of v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
