### ISSUE TITLE
[Bug Report] Vuetify cannot be initialized in Crosswalk 24.53.595.0

### ISSUE THREAD

**Issue by gaozhe3321** [vuetifyjs/vuetify#4507]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Other(Crosswalk 24.53.595.0)
**OS:** Android

### Steps to reproduce
1.Start New Android Studio Project
2.import crosswalk-webview-24.53.595.0-arm64 project as module
3.add org.xwalk.core.XWalkView to layout
4.XWalkView.load() to load a vuetify page
5.nothing to show just a blank page
6.add vConsole to vue and initialize before Vuetify it will show "Error script"

### Expected Behavior
Display Correct

### Actual Behavior
Android app built with Crosswalk will not display when browsing the vuetify page. The web console will display "Error script".

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

**Comment by gaozhe3321** [comment]
enable crosswalk remote debugging option will see the console
vuetify.js will throw a Error said "Object.values is not a function"

**Comment by KaelWD** [comment]
That is not an environment we support, sounds like you need some polyfills.
