### ISSUE TITLE
[Bug Report] Rows per page in DataTable doesn't display properly on IE

### ISSUE THREAD

**Issue by ChandruCR** [vuetifyjs/vuetify#4508]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Rows per page item dropdown doesn't render properly on IE. 
You can see this on Vuetify datatable page itself

### Expected Behavior
Rows per page item dropdown to render properly on IE

### Actual Behavior
Rows per page item dropdown to render properly on IE

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/data-tables/headerCell.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/data-tables/headerCell.vue)

**Comment by KaelWD** [comment]
They don't display properly anywhere.

Duplicate of #4500

**Comment by joec921** [comment]
Rows per page  didn't work , no response
