### ISSUE TITLE
[Bug Report] <v-select> model does not handle objects properly

### ISSUE THREAD

**Issue by david-wg2** [vuetifyjs/vuetify#4510]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.1.0
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
See codepen

### Expected Behavior
The watcher should receive two objects, "new" and "old".

### Actual Behavior
The objects "new" and "old" are actually the same object.

### Reproduction Link
[https://codepen.io/david-wg2/pen/aKgKaR?editors=1011](https://codepen.io/david-wg2/pen/aKgKaR?editors=1011)

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/42379423-f2dafe6e-816d-11e8-850e-687069089d44.png)

https://codepen.io/anon/pen/GGbBYv?editors=1011

1.0 change event: https://codepen.io/anon/pen/JZQajK?editors=1011
1.1 change event: https://codepen.io/anon/pen/vrqzEe?editors=1011
