### ISSUE TITLE
[Bug Report] v-menu on a button closes with v-time-picker as content with close-on-content-click = false

### ISSUE THREAD

**Issue by NickMBR** [vuetifyjs/vuetify#4516]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Create a button that opens a menu with a time picker component

### Expected Behavior
Should not close the menu when clicking on the time picker component

### Actual Behavior
Closing when clicking the time picker component

### Reproduction Link
[https://codepen.io/anon/pen/oyrmwQ](https://codepen.io/anon/pen/oyrmwQ)

**Comment by jacekkarczmarczyk** [comment]
It's closing because you're calling `$refs.hourMenu.save(hour)` on `@input`. You should call it on `@change`

https://codepen.io/anon/pen/mKZvGd
