### ISSUE TITLE
[Bug Report] Close buttons on VAutocomplete chips use cursor: text

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4517]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Select an item, then hover over the chip's close button

### Expected Behavior
```cursor: pointer``` used

### Actual Behavior
```cursor: text``` used

### Reproduction Link
[https://codepen.io/anon/pen/BVgbyp](https://codepen.io/anon/pen/BVgbyp)

### Other comments
Looks like ```.v-autocomplete .v-menu__activator *``` is overriding ```.v-menu__activator *``` for setting the cursor type.

**Comment by jacekkarczmarczyk** [comment]
Please narrow down your repro to minimal, there's a lot of stuff unrelated to the issue. Thank you

**Comment by Dylan-Chapman** [comment]
Sorry, just used a pen from the docs. Pen updated.

**Comment by jacekkarczmarczyk** [comment]
9a9b71872477dd3372067a61494d841d98ffad10
