### ISSUE TITLE
[Bug Report] v-list-group transition does not work if not direct child of v-list

### ISSUE THREAD

**Issue by lukegravitt** [vuetifyjs/vuetify#4519]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Place the v-list-group inside an otherwise empty div instead of as a direct child of v-list.

### Expected Behavior
List Group expand/collapse transition should work.

### Actual Behavior
List Group expand/collapse transition does not work -- the list is shown/hidden only.

### Reproduction Link
[https://codepen.io/lukegravitt/pen/eKwaor/](https://codepen.io/lukegravitt/pen/eKwaor/)

**Comment by matthewma7** [comment]
I ran into the same issue. I am trying to have <transition-group> wrapping <v-list-group>, however the <transition-group> transition works but the group expansion collapsing stopped working.

**Comment by Avgardyan** [comment]
Same here. Trying to render a navigation menu where some items are expandable and some are not. Trying to find a workaround or cause of this issue, but nothing so far.

**Comment by johnleider** [comment]
I haven't had time to dig into when this was resolved, but it is for v1.2, https://codepen.io/johnjleider/pen/ZMGKOp

**Comment by KaelWD** [comment]
It was your transition changes in beta.3: 719ac431bbcf42d275e248f96f7b98fd0a2b444c, bca41c6f03f0a6392ff78a049789e5c41beed228
