### ISSUE TITLE
Questions and feature requests

### ISSUE THREAD

**Issue by leonfather** [vuetifyjs/vuetify#453]
Hello, I would like to congratulate you for your effort in creating this beautiful implementation of vue js and material design, I added a new star in github and like in facebook. 
Actually i'm using another library and I'm just waiting some answers to migrate completely to vuetify:
1 - In textarea it is possible to have an expanded textarea, If I write some text, I want that the textarea expand vertically without scrollbar?
2- In picker date, Do you have an implementation of date range (Start and End date)?
3- Are you using bootstrap ? If not, you use which css framework?
4- What is the diference between https://unpkg.com/vuetify/dist/vuetify.min.css and https://vuetifyjs.com/dist/styles.f6181fb0172be4cd12cb.css? Are the same?
5- Is there a version in sass for css?
6- Can we have for each component its own separate css file?
7- Do you planning to do a back end using Vuetify?
8- In datatable, is it possible to display the data using ajax? (Server side)?
9- In datatable, how can we choose column toggle to show?
10- In steppers, how to go back to the previous step?
11- Is there a documentation for css classes?

I really appreciate the time you give us to respond our issues and also the time you spend to improve vuetify. Thanks.

**Comment by johnleider** [comment]
1. Yes with prop ```auto-grow```
2. Not currently
3. CSS is custom for Vuetify
4. One is the core css the other is the combined css from vuetify and docs
5. Not currently, only stylus
6. Ala carte components is not something I plan to do for now
7. Yes
8. There is a PR for such functionality currently #446 
9. Don't understand the question
10. You programmatically handle this through ```v-model```.
11. Under styles and layouts sections of the documentation.

**Comment by leonfather** [comment]
Thank you for your answers and also for your great reactivity.
2. Any ETA for that?
5. Any ETA for that?
7. Any ETA for that?
9. Is it possible to to choose columns to display/hide ?

**Comment by johnleider** [comment]
I try to avoid giving ETA's as much as possible, so for points 2 and 7, as soon as we can. Feel free to create an issue or support an existing one so we can prioritize.

For 5, I'm not sure if this will ever happen or is really needed.

9. Not currently, look for @nekosaur 's updates as he is currently in data-table land atm.
