### ISSUE TITLE
[Bug Report] VOverflowBtn shows item-value not item-text

### ISSUE THREAD

**Issue by mwaldstein** [vuetifyjs/vuetify#4533]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Firefox 62.0
**OS:** Windows 10

### Steps to reproduce
 * Create a v-overflow-btn with items that have both text and value parameters
 * set item-value and item-text props
 * Use the component to select an item

### Expected Behavior
The string stored in the item-text field is displayed on the component

### Actual Behavior
The value of item-value is displayed

### Reproduction Link
[https://codepen.io/mjwalds/pen/bKXgWr?editors=1010](https://codepen.io/mjwalds/pen/bKXgWr?editors=1010)

**Comment by hjlld** [comment]
same issue, will this be solved soon?

**Comment by hirofumi-matsumoto** [comment]
How is this workaround?

add return-object

<v-overflow-btn
  v-model="select"
  :items="items"
  item-text="state"
  item-value="abbr"
  single-line
  return-object
></v-overflow-btn>

default "select"  change to object

return {
  select: { state: 'Georgia', abbr: 'GA' },
  items: [
    { state: 'Florida', abbr: 'FL' },
    { state: 'Georgia', abbr: 'GA' },
    { state: 'Nebraska', abbr: 'NE' },
    { state: 'California', abbr: 'CA' },
    { state: 'New York', abbr: 'NY' }
  ]
}

**Comment by nelsonghezzi** [comment]
Any news on this one?

Thanks.

**Comment by apro23** [comment]
I'm having the same issue. Is there an update on this one too?

Thanks.

**Comment by cheposki** [comment]
Any news ?
