### ISSUE TITLE
[Feature Request] Higher range of z-index values

### ISSUE THREAD

**Issue by pscheit** [vuetifyjs/vuetify#4534]
### Problem to solve
The z-index values currently used to create the layered design are in the range from 1-12. If one has an application, that uses on it's own more than 2 absolute positioned layers, it is not possible to place those layers between the top navigation bar and a card - for example.

### Proposed solution
Changing z-index 1 to z-index 100, Change z-index 2 to z-index 200.. and so on..
or: make the z-index range configurable (to keep backwords compatibility) with variables:

$z-index1: 1
$z-index:2: 2
...

**Comment by KaelWD** [comment]
They're like that because cssnano was messing with them for ages, see e748769426391e55f65db7a62e50aa1f58928461. This should definitely be changed now that that's out of the way.

**Comment by duebbert** [comment]
This would be great and yes it should be configurable ideally.

**Comment by petermchale** [comment]
The following suggests that layering is possible with any hard-coded set of z indices that vuetify might use: 
https://github.com/vuetifyjs/vuetify/issues/4509#issuecomment-462393257

**Comment by jimut** [comment]
This is a different solution where layering doesn't work.
https://github.com/vuetifyjs/vuetify/issues/4509#issuecomment-563090591
