### ISSUE TITLE
[Bug Report] "Cannot read property 'indexOf' null" when switching between tabs first time

### ISSUE THREAD

**Issue by RZetko** [vuetifyjs/vuetify#4542]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Click between tabs.
First time you switch to new tab, it'll generate error message below.
After clicking through all the tabs at least once, error message is not thrown anymore.

### Expected Behavior
No errors should be thrown

### Actual Behavior
Throws following error:

Uncaught TypeError: Cannot read property 'indexOf' of null
    at Object.attrObserver (content.js:29)
    at MutationObserver.<anonymous> (content.js:137)

### Reproduction Link
[https://codepen.io/anon/pen/GBKjBx](https://codepen.io/anon/pen/GBKjBx)

### Other comments
Firefox 60.0.2 doesn't generate error messages.
Microsoft Edge 42.17134.1.0 also doesn't generate error messages.

Chrome throws error message in my personal project, codepen I posted and following official Vuetify examples:

- content
- icons and text
- desktop tabs
- with menu
- pagination
- custom icons

**Comment by KaelWD** [comment]
Doesn't happen for me in chrome 67.0.3396.87

Can you try incognito mode without any extensions enabled?

**Comment by RZetko** [comment]
Just did that. I forgot I had some extensions enabled even in incognito. It was caused by extension Imagus that I use to enlargen images while hovering over them. It was my fault, sorry. I'm closing the issue.
