### ISSUE TITLE
[Bug Report] VTextField + vuelidate @blur async validation does not work

### ISSUE THREAD

**Issue by artemistomaras** [vuetifyjs/vuetify#4543]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
Using the provided codepen link, write something on the text field input then loose focus.

Give focus back to the text field and start typing again.

The async validator is run on every keystroke.

### Expected Behavior
The asyn validator is run only onBlur

### Actual Behavior
The async validator is run on every keystroke.

### Reproduction Link
[https://codepen.io/atomaras/pen/XBrpMB](https://codepen.io/atomaras/pen/XBrpMB)

**Comment by KaelWD** [comment]
Nothing to do with vuetify, you need to somehow debounce your requests or only update data on blur. `v-model.lazy` doesn't work on custom components.

https://monterail.github.io/vuelidate/#sub-without-v-model
vuejs/vue#6914

**Comment by artemistomaras** [comment]
Thanks for the quick reply!

I  did not know that ``.lazy`` does not work on custom components.
I guess it is better to only update the model onBlur and not using something like lodash debounce correct ?
