### ISSUE TITLE
[Bug Report] Wrong text-field icons aligment with full-width

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4544]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
Open codepen

### Expected Behavior
Icons vertically centered

### Actual Behavior
Wrong aligned because some icons has an extra 16px margin top.

### Reproduction Link
[https://codepen.io/anon/pen/oMvopr?&editors=101](https://codepen.io/anon/pen/oMvopr?&editors=101)

**Comment by peluprvi** [comment]
Codepen updated to version 1.1.4:
https://codepen.io/anon/pen/KBKbxG?&editors=101

- Internal icons are fixed
- External icons are worse
- Label/input doesn't look aligned (mainly on default full-width)

**Comment by johnleider** [comment]
Please note, the **full-width** prop is an _exclusive_ prop just like **solo**, **outline**, etc. They are not intended to be used together.
