### ISSUE TITLE
[Bug Report] $vuetify.t(key,params)

### ISSUE THREAD

**Issue by deka** [vuetifyjs/vuetify#4548]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
- use vue-i18n module with vuetify like documention (https://vuetifyjs.com/en/framework/internationalization)
- add new object key to messages
```
{
    en: {
      $vuetify: {
        dataIterator: {
          rowsPerPageText: "Items per page:"
        }
      },
      other: {
        test: "the test"
      }
    }
  }
```
- use $vuetify.t('other.test') in vue template

### Expected Behavior
{{ $vuetify.t('other.test') }} must return the translation

### Actual Behavior
{{ $vuetify.t('other.test') }} return the key

### Reproduction Link
[https://codesandbox.io/s/py90q0l9q0](https://codesandbox.io/s/py90q0l9q0)

**Comment by KaelWD** [comment]
The documentation is wrong, keys must be prefixed with `$vuetify`

`{{ $vuetify.t('$vuetify.other.test') }} `

This is so we can dynamically change the locale with prop defaults. `$vuetify.t` isn't really intended to be used externally. 

https://github.com/vuetifyjs/vuetify/pull/4051/commits/c6e17bb1f5ad73e5a62b0a3df1d07796bb69d862

**Comment by wcjr** [comment]
I just ran into this documentation issue too...what's the reason for `wontfix` @KaelWD ?

**Comment by wcjr** [comment]
nm, I see now I don't need the `$vuetify.` prefix in `1.2.6`.  Thanks.

**Comment by madnik7** [comment]
the documentation still have the issue and killing developers time!

**Comment by nekosaur** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/pull/660

**Comment by MajesticPotatoe** [comment]
docs have been updated for next release.
https://github.com/vuetifyjs/vuetify/commit/97d74802282f846f697a32a09af5fc854d182490
