### ISSUE TITLE
[Bug Report] VSelect: "Cannot read property 'blur' of undefined" when changing route

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4549]
### Versions and Environment
**Vuetify:** 1.1.2
**Last working version:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Have a VSelect on a page, change route, then look at the console

### Expected Behavior
No console error

### Actual Behavior
Has the console error `Uncaught TypeError: Cannot read property 'blur' of undefined`

### Reproduction Link
[https://codepen.io/anon/pen/EpYRXm](https://codepen.io/anon/pen/EpYRXm)

**Comment by KaelWD** [comment]
33785e6

**Comment by Dylan-Chapman** [comment]
Oops, looked through recent issues, but not recent commits. My bad!

**Comment by chadsaun** [comment]
Any idea when this commit will reach an npm package update?
