### ISSUE TITLE
Documentation correction (pagination)

### ISSUE THREAD

**Issue by mubaidr** [vuetifyjs/vuetify#455]
### Steps to reproduce
visit: https://vuetifyjs.com/components/pagination

### Versions
NA

### What is expected ?
Pagination component documentation has two props of the same name (length) mentioned. 

### What is actually happening ?
Its confusing.

**Comment by mfferreira** [comment]
@mubaidr Good catch. Can you submit the issue in [the docs repo](https://github.com/vuetifyjs/docs/issues) ?

**Comment by mubaidr** [comment]
Sure. Closing this one.

**Comment by mfferreira** [comment]
Thanks
