### ISSUE TITLE
[Bug Report] Data Tables do not sort (or page) Font-Awesome icons

### ISSUE THREAD

**Issue by alphatrust-dev** [vuetifyjs/vuetify#4550]
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Include unique font-awesome icons in a data-table column and try to sort any other column and the font-awesome icons will remain in their original column and won't be sorted (or paged) with it's original row item data.

### Expected Behavior
The font-awesome icons should be sorted (or paged) along with the rest if its row item data.

### Actual Behavior
The row item data sorts but the font-awesome icons stay on their original row when the table is sorted or paged

### Reproduction Link
[https://codepen.io/alphatrust-dev/pen/MBgBGV](https://codepen.io/alphatrust-dev/pen/MBgBGV)

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727
