### ISSUE TITLE
[Bug Report] Fix align-center on iOS 9.3.5 Safari

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#4554]
### Versions and Environment
Vuetify: 1.1.0
Vue: 2.5.16
Browsers: Safari
OS: iOS 9.3.5

### Steps to reproduce
Vertically center content on iOS 9 Safari just like all other supported browsers.

### Expected Behavior
I expected the content to be centered vertically.

### Actual Behavior
The content remains aligned to the top.

### Reproduction Link
https://codepen.io/ChrisLandowski/pen/NBKoyK

### Additional Comments:
I was unable to get the above pen to run on iOS 9 Safari even after adding the babel pollyfill.

**Comment by KaelWD** [comment]
Closed due to inactivity.
