### ISSUE TITLE
fixed secondary toolbar

### ISSUE THREAD

**Issue by AndreasKlipp** [vuetifyjs/vuetify#456]
Hi,
is it possibly to fix the position of the secondary toolbar. So that i can scroll on the page and the toolbar is always on the screen.
Thanks!

**Comment by mfferreira** [comment]
@AndreasKlipp I don't understand the issue. Please create a codepen reproducing it.

**Comment by AndreasKlipp** [comment]
This was fast!
https://jsfiddle.net/hhd31e0z/

If the secondary toolbar get the attribute "fixed" it jumps to the top

**Comment by mfferreira** [comment]
I'm curious. Why are you using two toolbars in the first place?

**Comment by AndreasKlipp** [comment]
https://material.io/guidelines/layout/structure.html#structure-toolbars
https://material.io/guidelines/layout/structure.html#structure-side-nav

I try to make a two line Toolbar. The first is for general things and second for the current page (save/edit-Button, path-information)

**Comment by mfferreira** [comment]
What you see in the guidelines is not two toolbars, but a single one with extended height.
It's not implemented, but should be fairly easy to do changing the toolbar styles.

Regarding the "fixed" making the toolbar jump to the top, that is expected.
If you still want to go down this path, you can probably put both toolbars in a div and make that div fixed positioned to the top.
