### ISSUE TITLE
[Feature Request] v-chip with avatar on the right side

### ISSUE THREAD

**Issue by Sevyls** [vuetifyjs/vuetify#4562]
### What problem does this feature solve?
v-avatar within v-chip on the right side is not rendered near the border of the chip, as it is currently the case with left side avatars within a chip.

Currently it looks like this:
![bildschirmfoto 2018-07-10 um 14 03 16](https://user-images.githubusercontent.com/547842/42508861-53a8ce2c-844a-11e8-9e4b-6408a7d298e1.png)

A avatar on the right side is currently  overlaying the chip's contents.

I would like to highlight a Suffix of an Identifier  like 123456a where the letter at the end indicates a certain meaning. 

### What is your proposed solution?

analogue to the v-icon right, I would like to see a simple attribute "right" to set an avatar to the right side of a chip.

```xml
<v-chip dark text-color="white" color="secondary">
  {{ number }}
  <v-avatar right class="green darken-4">{{ suffix }}</v-avatar>
</v-chip>
```

**Comment by blalan05** [comment]
This is available in 2.0 alpha.
