### ISSUE TITLE
Broken shake-animation for v-text-field when using Font Awesome

### ISSUE THREAD

**Issue by MisterGoodcat** [vuetifyjs/vuetify#4563]
### Versions and Environment
Vuetify: 1.1.3
Font Awesome: 5.1.0
Chrome: 67

### Steps to reproduce
* Import Vuetify.min.css
* Import Font Awesome's "all.css" (minified)
* Trigger validation error in v-text-field

### Expected Behavior
"Shake"-animation when validating v-text-field works correctly.

### Actual Behavior
Interference with Font Awesome's keyframe definition and a resulting weird rotation animation.

### Reproduction Link
https://codepen.io/anon/pen/rrNJXm

### Additional Comments:
As discussed on Discord

**Comment by aldarund** [comment]
Heh, had the same animation problem with mdi & cssnano. But updating css nano to 4.0.0 from 3 solved issue

**Comment by MisterGoodcat** [comment]
Yes, it's a clash of keyframe names of minified CSS files. So probably everybody using similar minification frameworks or features potentially has these problems, as keyframes are renamed a, b, c... if you exclude them from mangling and work with prefixes the issue is solved - maybe they did that for css nano also.
