### ISSUE TITLE
[Feature Request] Add week picker 

### ISSUE THREAD

**Issue by zied-ati** [vuetifyjs/vuetify#4566]
### What problem does this feature solve?

Provide more flexible datepicker by adding week selection functionality.

**Comment by KaelWD** [comment]
Possible duplicate of #5415, can you clarify what you mean by this?

**Comment by jacekkarczmarczyk** [comment]
This one is for selecting **weeks** `YEAR-{01-52}`, #5415 is for selecting **weekdays** `YEAR-MONTH-{1-7}`

**Comment by inlinecoder** [comment]
Guys, @johnleider or @jacekkarczmarczyk , sorry for bothering you with questions in the closed thread 🙏 .

While this feature request is closed, I couldn't find a way on how to select a week (in one click; when a week or. a custom range of days is highlighted) neither in the docs nor in GitHub issues/discussions.

So the qqs are: Is it possible to select a week and it's not covered in the docs? If not, any plans on adding this feature?
