### ISSUE TITLE
feature request: customize the DatePicker date format when active

### ISSUE THREAD

**Issue by pandada8** [vuetifyjs/vuetify#457]
seems just a format function props for date-title should be enough

**Comment by johnleider** [comment]
Could you please be more descriptive. I don't know what you're asking for.

**Comment by pandada8** [comment]
Sorry for my poor english :/

![image](https://cloud.githubusercontent.com/assets/3305174/25558667/fc968a50-2d5d-11e7-8ba6-ee513cd0c126.png)

I want to customize the format of date when the datepicker is active (which is  `日, 四月 30` in the picture )

**Comment by johnleider** [comment]
This has been added.
