### ISSUE TITLE
Slider with step not start with the right value

### ISSUE THREAD

**Issue by MyHorseFamilyMTP** [vuetifyjs/vuetify#4575]
Hello guys!

### Versions and Environment
Vuetify: 1.1.1
Vue: 2.5.2
Browsers: Chrome, Firefox
OS: Ubuntu 16.04

### Expected Behavior
I want to use Slider with : 
- min = 45
- step = 2

So, get values like 45, 47, 49....

### Actual Behavior
Actually, it start at 46 not 45

### Reproduction Link
[Codepen](https://codepen.io/anon/pen/yqyedw)

**Comment by sh7dm** [comment]
The problem is in the roundValue (value) method of VSlider component
