### ISSUE TITLE
[Bug Report] v-switch top margin on hide-details should not be there

### ISSUE THREAD

**Issue by pwildschut** [vuetifyjs/vuetify#4576]
### Versions and Environment
**Vuetify:** 1.1.3
**Vue:** 2.5.14
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Align center and add a v-switch inline with hide-details as prop.

### Expected Behavior
The top margin should be reduced accordingly to the bottom one when hide-details prop is used.

### Actual Behavior
The top margin which equals the height of the placeholder for hints is still there.

### Reproduction Link
[https://codepen.io/pwildschut/pen/ZjYWPO](https://codepen.io/pwildschut/pen/ZjYWPO)

**Comment by KaelWD** [comment]
The top margin is to align it with text fields and other inputs. Use `class="mt-0"` to override it.
