### ISSUE TITLE
Feature: Form Validate

### ISSUE THREAD

**Issue by thearabbit** [vuetifyjs/vuetify#458]
Request `Form Validate`: builtin or use any package such as `Vee-Validate`.
💯

**Comment by mfferreira** [comment]
@thearabbit You can use `rules` to validate your inputs.

https://vuetifyjs.com/components/text-fields

**Comment by thearabbit** [comment]
thank for your reply.
could example, I don't understand on doc?

**Comment by thearabbit** [comment]
use this [Async Validator](https://github.com/yiminghe/async-validator)???

**Comment by jamesxv7** [comment]
@thearabbit here is a [brief example](https://gist.github.com/jamesxv7/0c020103c9a618c27c8fa4daba7a8405) how to use Vee-Validate with Vuetify.

To use the rule property, the trick is to remember that for the rules you can use an array of functions. Refer to the [following example](http://codepen.io/jamespr/pen/VbPZjg) to see how you can use it to validate a required field.

I hope the examples have been useful

**Comment by thearabbit** [comment]
Very thanks @jamesxv7, Look great

**Comment by thearabbit** [comment]
Tonight, I custom like this
[Vuetify + Vee-Validateion](http://codepen.io/yuomtheara/pen/oWBGRr)

**Comment by cannap** [comment]
Hi, when i try to use vee-validation i get this warning

`console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 [Vue warn]: The computed property "errors" is already defined in data.`

when i add 
```js
Vue.use(VeeValidate, {
  locale: 'de'
})

```

**Comment by abelovic** [comment]
I see this too (you don't even need to add the locale). Any idea what is causing this? 

You can see it in the example by @thearabbit

**Comment by nekosaur** [comment]
I would hazard that vee-validate add an errors property to all components, which collides with the one vuetify itself adds to input components.

**Comment by mige** [comment]
@abelovic @cannap Change the error property name:
`
Vue.use(VeeValidate, {
    errorBagName: 'veeErrors'
})
`

**Comment by abelovic** [comment]
@mige - thank you!

**Comment by thearabbit** [comment]
Now I try with `picker date`.
It have problem when `picker date` selected, form is validated (equal click submit btn).

**Comment by wilsonwu** [comment]
Base on you guys comment, I create a demo:
[https://gist.github.com/wilsonwu/e78b620c02f2b8c5227b48fecdcf62d2](url)

**Comment by smith64fx** [comment]
@mige thanks man! made my day :D

**Comment by bobbygerez** [comment]
@jamesxv7 Thanks.

**Comment by bobbygerez** [comment]
@jamesxv7 How not to validate  during initialization?I've tried it but failed... It displays the error in untouch. TY

**Comment by jamesxv7** [comment]
@bobbygerez What do you mena by "not to validate during initialization"? The example trigger the validation on the click event of the button.

**Comment by bobbygerez** [comment]
@jamesxv7 No the validation triggers directly after clicking the button... See photo 
![capture](https://user-images.githubusercontent.com/10149942/28651662-b94ab44a-72b5-11e7-99d8-ea0f44c2bc75.PNG)

**Comment by jamesxv7** [comment]
@bobbygerez What button? The validation should be trigger by the login button. Can you share a example of your code?

**Comment by bobbygerez** [comment]
`<v-text-field label="Email" required v-model="email" :rules="veeErrors.email"></v-text-field>`

```
 data(){
  		return {
  			  validationRules: {
	            password: 'required',
	            email: 'required|email',
	         },
  		}
  },
computed: {

         veeErrors() {
          let errors = {}
          Object.keys(this.validationRules).forEach(key => {
            if (!errors[key]) {
              errors[key] = []
            }

            this.validator.validate(key, this[key]).catch(() => {})

          })

          this.validator.getErrors().errors.forEach(error => {
            errors[error.field].push(error.msg)
          })
          return errors
        }
  }
```

`:rules="veeErrors.email"`  triggers directly even without clicking the `textbox` (untouch) because it's a computed property, I think. How to make it blur event and validate? or when they start typing. TY

**Comment by jamesxv7** [comment]
@bobbygerez First thing, for this particular case is better to use a method and not a computed property. I know the gist example use a computed property but the following example is better suited for your use case https://codepen.io/jamespr/pen/VbPZjg

Regards!

**Comment by bobbygerez** [comment]
@jamesxv7 Thanks... works like a charm!

**Comment by andreixk** [comment]
is there a documentation for the default vuetify form validation rules?

**Comment by nekosaur** [comment]
There are no default rules.

**Comment by andreixk** [comment]
the rules shown in the examples are neither from vee-validate nor from vuelidate. so i'm assuming vuetify is the one that processes those rules?

**Comment by nekosaur** [comment]
Yes, vuetify has an internal (simple) validation engine, but there are no pre-defined rules shipped with it.

The `rules` prop takes an array of function in the form of `(value) => boolean || string`

If the function returns true, the rule passes. If the function returns false, or a string, it fails. The returned string is used as the error message.

**Comment by andreixk** [comment]
But is there a more detailed documentation or examples? For example if I want to check that password and confirmation match or more advanced error checking, e.g. check if entered date is present in the "dates" prop ?

**Comment by nekosaur** [comment]
It's possible you could cobble something together using the internal engine, but for anything complex I would recommend you use an external validation library.

**Comment by qiuzuhui** [comment]
Is there any way to do async validation? Like check email already registered by the server side.

**Comment by niutech** [comment]
There is a [workaround](https://stackoverflow.com/questions/49132167/how-to-validate-vuetify-text-field-asynchronously/49133646#49133646) for async validation using `watch`.

**Comment by rahul1235** [comment]
any example using vuetify?

**Comment by escapedcat** [comment]
@rahul1235 example for what exactly?
