### ISSUE TITLE
[Bug Report] When "v-autocomplete" has one or more items selected, filtering breaks after x amount of characters are entered.

### ISSUE THREAD

**Issue by joshfoskett** [vuetifyjs/vuetify#4580]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Chrome, Firefox, etc.
OS: macOS High Sierra 

### Expected Behavior

1. Try and type "California" (or any other state) in full.
2. The list should be filtered accordingly, and you should be able to enter as many characters as desired.

### Actual Behavior

1. Try and type "California" (or any other state) in full.
2. After the third letter of the state is entered, the list goes away, as if there aren't any results.

### Reproduction Link

https://codepen.io/anon/pen/WKbzNe?&editors=101

---

### Additional Comments:
It works as expected for the initial search when there are no items selected. However, once one is selected, the issue starts to appear.

The issue appears to be caused by the combination of the `hide-no-data` and `hide-selected` properties. If you remove either of them, it works as expected.

**Comment by KaelWD** [comment]
Only happens with `hide-selected`
