### ISSUE TITLE
Switching between radio buttons doesn't work with 'tab' after 1.1

### ISSUE THREAD

**Issue by kstraszewski** [vuetifyjs/vuetify#4581]
Versions and Environment
Vuetify: 1.1.4
Browsers: Chrome
OS: Windows10

Expected Behavior
Using 'tab' and 'shift' + 'tab' should switch between radio buttons, and it worked before 1.1 version. Know it is only working between first and second element :/

Reproduction Link
https://vuetifyjs.com/en/components/selection-controls#example-radios-colors

**Comment by KaelWD** [comment]
This is now the same as native radios: https://codepen.io/anon/pen/xJbjpo
