### ISSUE TITLE
Add tooltip to prepend/append icons on inputs/selects

### ISSUE THREAD

**Issue by empresarrollo** [vuetifyjs/vuetify#4582]
### What problem does this feature solve?
This would give more information to the user to know what does that buttons do. I have selects with a prepend icon of a "plus" sign to add a new item, but the users do not find that option. If it would have a tooltip that says what the button does, I think it would be much more usable.

### What is your proposed solution?
It would be somethig like:

```
<v-autocomplete
label="Select user Type"
:items="types"
prepend-icon="add"
@click:prepend="addNewUserType"
prepend-icon-tooltip="Click here to add a new User Type"
</v-autocomplete>
```

**Comment by KaelWD** [comment]
Use the prepend slot instead.
