### ISSUE TITLE
[Bug Report] Wrong menu position after hide the toolbar

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4583]
### Versions and Environment
**Vuetify:** 1.1.4
**Last working version:** 1.0.0-beta.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
- open the menu
- resize the window width between xs, sm and md

### Expected Behavior
Menu reloads the position

### Actual Behavior
Sometimes menu doesn't reload its position
![menu-issue](https://user-images.githubusercontent.com/1561360/42592293-72385cba-851f-11e8-81db-abf78811dbfb.gif)

### Reproduction Link
[https://codepen.io/anon/pen/bjNjPw?editors=1010](https://codepen.io/anon/pen/bjNjPw?editors=1010)

### Other comments
vuetify@1.0.0-beta.3: https://codepen.io/anon/pen/yqyxEq?editors=1010

**Comment by sh7dm** [comment]
Maybe, there is a problem in the [083d55e](https://github.com/vuetifyjs/vuetify/commit/083d55eef5b29ab4ffd2a62e9f8bf0e4b33c257a) commit?

**Comment by peluprvi** [comment]
It still doen't working on v1.2.3: https://codepen.io/anon/pen/MqqyWN?editors=1010

You can resize the screen to ~500px, open the menu, click fullscreen.
If you close the menu and open it again you will see the position will be different.

The same happens if you restore the screen to mobile with the menu opened.

**Comment by johnleider** [comment]
After reviewing this for the `v-toolbar` update I've determined the the way it behaves on current 1.5.x is acceptable.
