### ISSUE TITLE
[Feature Request] Change Data table sort icon to right side

### ISSUE THREAD

**Issue by AGPDev** [vuetifyjs/vuetify#4584]
### Problem to solve
when the title header is align in center, not appear see in exacly center only on hover or is selected
See "Fat (g)" option:

https://codepen.io/anon/pen/QBwYvz?&editors=101

### Proposed solution
Change the icon in left to right side when title is aligned to center

**Comment by jacekkarczmarczyk** [comment]
If you move the arrow to the right it won't be centered as well

**Comment by nekosaur** [comment]
Yeah, not sure how having it on the right would be any different for the centering?

**Comment by AGPDev** [comment]
> Yeah, not sure how having it on the right would be any different for the centering?

Beacause when row is hide, looks like not centralized only visual effects (ocular illusion)

**Comment by nekosaur** [comment]
I'm sorry but I couldn't understand that

**Comment by Nealon01** [comment]
So the suggestion here clearly won't fix the issue, but it is a problem that centered columns aren't visually centered.  Can we get a fix for this?

**Comment by AGPDev** [comment]
In the example the header title "Fat(g)" is centered with icon, but when icon is hide the space of icon not hide, provoke impression the text is not centralized

**Comment by nekosaur** [comment]
I'm honestly not sure what the fix would be. Other than some hacky solution of wrapping icon and text and hardcoding a padding equal to the icon width.

**Comment by Nealon01** [comment]
So it's not possible to have content actually centered in a column?  That seems a little silly.

**Comment by jacekkarczmarczyk** [comment]
It is possible, but if we do it header won't be centered when you show the sorting arrow. And if you want to center it with arrow and without arrow then it will change position when you start sorting (or when you hover the header).

**Comment by Nealon01** [comment]
Why can't you just make it ignore the icon always and just center on the column header?  I think it's a much better trade-off to have it always ignore the icon than always include it.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
