### ISSUE TITLE
[v-data-table] Can't search by attribute which include dot character

### ISSUE THREAD

**Issue by ittus** [vuetifyjs/vuetify#4586]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
OS: Mac OS 10.13.5

### Steps to reproduce
1. Create an array of `items` which has dot in property name.
For example:
```javascript
        {
          value: false,
          '.name': 'Frozen Yogurt',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          iron: '1%'
        }
```
2. Pass `items` array to `v-data-table`. Can't search by `.name` attribute

### Expected Behavior
Can search by `.name` attribute

### Actual Behavior
Can't search

### Reproduction Link
https://codepen.io/ittus/pen/wxBLgV
(Can't search by `.name` property)

---
### Additional Comments:
- I think because of [getObjectValueByPath](https://github.com/vuetifyjs/vuetify/blob/f10901567282d4b437b603b195f75b8586ab6634/src/util/helpers.ts#L153), we can't get `object['.name']` value
- A popular use case is when using with [vuefire](https://github.com/vuejs/vuefire#array-bindings), `.key` attribute is exist.
 My workaround is using computed attribute:

```javascript
computed: {
   formatItems: function() {
      return this.items.map(item => {
           return {
              ...item,
             key: item['.key']
           }
      })
   }
}
```

**Comment by ittus** [comment]
I think we can add by passing `fallback` parameter to 
https://github.com/vuetifyjs/vuetify/blob/f10901567282d4b437b603b195f75b8586ab6634/src/components/VDataTable/VDataTable.js#L50

```javascript
return items.filter(item => props.some(prop => filter(getObjectValueByPath(item, prop, item[prop]), search)))
```

**Comment by KaelWD** [comment]
#1823, not sure what those "breaking issues" would be though.

**Comment by mismith** [comment]
Hmm, any idea how to accomplish the same thing with a workaround in <2.0.0?
