### ISSUE TITLE
[Feature Request] New prop "overlay" for detachables

### ISSUE THREAD

**Issue by dmecke** [vuetifyjs/vuetify#4588]
### What problem does this feature solve?
The current props `hide-overlay` and `persistent` handle both the behaviour of the background overlay. It effects it both visually and if it can be "clicked through".

### What is your proposed solution?

A new prop `overlay` with the options `visible`, `transparent` and `click-through` combines them and prevents illegal combinations of `hide-overlay` and `persistent`. (see https://github.com/vuetifyjs/vuetify/issues/4466)

**Comment by johnleider** [comment]
The issue you referenced has been resolved and the `v-overlay` standalone is being pushed to 2.0. Could you provide some additional information as to what this would look like in the wild visually?

**Comment by dmecke** [comment]
v1.1.2 introduced a bug for `v-bottom-sheet` with pull request https://github.com/vuetifyjs/vuetify/pull/4529 (https://codepen.io/anon/pen/wxaBXe). @jacekkarczmarczyk reverted this, so that issue is gone, but in the discussion on discord he said: (https://discordapp.com/channels/340160225338195969/443372064980729856/466856351704809492 ff)
> so now hide-overlay only controls visibility and persistent controls clicking through, i guess we need to persistent to prevent closing on click outside and add click-through prop
so for that guy it would be hide-overlay + persistent and for you it would be hide-overlay + persistent + click-through
hmmm, hide-overlay=false + click-through doesn't really make sense :wink: overlay must be in 1 of 3 states: visible, transparent, click-through (none?)

I think `v-overlay` wasn't a thing back then, so maybe this issue is superfluous now and can be closed.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
