### ISSUE TITLE
[Feature Request] Text Lighten/Darken for Missing Theme Colors

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#4594]
### Problem to solve
Currently there are no generated CSS style classes for lightening/darkening certain theme colors, namely [success, error, warning, info].  That is, it would be beneficial to be able to use the following style class `success--text text--darken-2`, which you cannot currently do.  However this does work with some of the other themes, e.g. `primary--text text--darken-2` does work.

### Proposed solution
Requesting that those problematic theme styles mentioned above have additional lighten/darken text CSS classes generated for them.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/style/theme#options

`themeVariations: ['primary', 'secondary', 'accent', 'success']`

Kinda dumb default but w/e

**Comment by dmcknight26** [comment]
@KaelWD thanks! Sorry I didn't catch that in the docs.
