### ISSUE TITLE
Add readonly support for form input fields

### ISSUE THREAD

**Issue by cayasso** [vuetifyjs/vuetify#460]
```html
<v-text-field
    name="input-3"
    label="Label Text"
    value="Input text"
    readonly
></v-text-field>
```

BTW. Awesome project!!!

**Comment by johnleider** [comment]
This is supported, may have been missed in the documentation.

**Comment by cayasso** [comment]
Strange its not working for me http://recordit.co/kiHQp174J8
I am using version **0.11.1**

**Comment by johnleider** [comment]
Can you reproduce it on codepen?

**Comment by cayasso** [comment]
http://codepen.io/anon/pen/oWZqXO#anon-login

**Comment by johnleider** [comment]
This is really quite strange, as it is there https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/TextField.js#L159. It's also used in the pickers docs and it works. Will have to do some digging.

**Comment by johnleider** [comment]
Hah found it, https://github.com/vuetifyjs/vuetify/blob/master/src/components/forms/TextField.js#L170 this was resetting attributes.

**Comment by cayasso** [comment]
Wow you fast man, thanks!!!
