### ISSUE TITLE
Possibility to control multiple expansion panel with the same model

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#4603]
### What problem does this feature solve?
Hi ! With Vuetify 1.1 the expansion panel changed, there is now a v-model directly on the `v-expansion-panel`, but this does not help in the situation where you have multiple expansion-panel and want to have one `v-expansion-panel-content` open **at the same time**.

On Vuetify 1.0.19 it was possible, using the value of the `v-expansion-panel-content` (see codepen).
https://codepen.io/Kleemer/pen/zLvOzg

### What is your proposed solution?
I actually cannot think of a good solution with using only v-model on the `expansion-panel`s. I know the whole point of this update is to have a consistent v-model for the whole object but this object becomes isolated from the others of the same type, and they cannot interact together anymore, which in my case (which I thought was more common 😞) is now a problem.

**Comment by Kleemer** [comment]
A @KaelWD mentioned on Discord, we can now nest anything we want under `v-expansion-panel` and not just `v-expansion-panel-content,` so it is possible for my case to put my whole layout in the same `v-expansion-panel`.

**Comment by nekosaur** [comment]
So can this be considered resolved?

**Comment by Kleemer** [comment]
Yes it is resolved. But maybe this should be said explicitely in the documentation ? I'll still close this issue though.
