### ISSUE TITLE
[Bug Report] Using select-all on a paginated server-side v-datatable

### ISSUE THREAD

**Issue by Thibaud-R** [vuetifyjs/vuetify#4604]
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3316.0
**OS:** Windows 7

### Steps to reproduce
1. Select a row on the page 1 of the datatable
2. Move to page 2
3. Click select-all
4. Back to page 1

### Expected Behavior
The selected row on page 1 ( step 1) should stay selected

### Actual Behavior
The ( step 3) select-all on page 2, clear the previous row selected

### Reproduction Link
[https://codepen.io/anon/pen/OwyRGb?editors=1010](https://codepen.io/anon/pen/OwyRGb?editors=1010)

**Comment by ndamjan** [comment]
The same issue happens also with Vuetify 1.0.17

**Comment by mofuliunian** [comment]
The same issue happens also with Vuetify 1.5.0

**Comment by sh7dm** [comment]
Fixed by 4f3adf1
