### ISSUE TITLE
v-select items are not aligned from right to left when using RTL

### ISSUE THREAD

**Issue by rondaniel00** [vuetifyjs/vuetify#4606]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Chrome
OS: Windows 10

### Steps to reproduce
Open the codepen provided below, click the select input list and verify that the list items are aligned to the left instead to the right.

### Expected Behavior
Have the select list items to be aligned to the right.

### Actual Behavior
Select list items are aligned to the left.

### Reproduction Link
https://codepen.io/anon/pen/bjVWpo

**Comment by praveenpuglia** [comment]
Hi,
So the expected output is this?
![image](https://user-images.githubusercontent.com/313363/42730886-4c065ad0-881f-11e8-84dd-0c93ec32d7c3.png)

**Comment by rondaniel00** [comment]
Correct.

בתאריך יום א׳, 15 ביולי 2018, 8:38, מאת Praveen Puglia ‏<
notifications@github.com>:

**Comment by M6stafa** [comment]
i will create PR again in correct repo(master).

**Comment by gorenamir** [comment]
the issue still exists

**Comment by gorenamir** [comment]
is that fixed? still have this issue.

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by mouadsah** [comment]
You can fix it by adding this style code :

.v-select__selection--comma {
width: 100%;
justify-content: flex-end;
}

RTL not working with v-select
