### ISSUE TITLE
[Feature Request] Non-linear steppers: editable and complete

### ISSUE THREAD

**Issue by suhrmann** [vuetifyjs/vuetify#4607]
### Problem to solve
I want to create a non-linear  step-list with a bunch of items. To mark which steps are "done" I'd like to use `completed` and its checkmark icon. Futher I have to use `editable` to use the _non-linear_ functionality.

**Problem:** `editable` binds its pencil icon with higher priority than `complete` with its checkmark icon.

So either I have the _non-linear_ functionality of `complete`, but with a pencil icon - or the checkmark icon of complete without _non-linear_ functionality.

### Proposed solution
Would you consider separating the icons of `editable` and `complete` from the logic of `non-linear` that requires `editable`.

### Workaround
Currently I **"workaround"** this by setting the *checkmark* as *edit icon*
```vue
<v-stepper-step edit-icon="$vuetify.icons.complete" ...>
```

Sample in this pen: https://codepen.io/Vadammt/pen/EpVvmL

**Comment by johnleider** [comment]
steppers are being refactored for v1.3 with the introduction of https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VItemGroup/VItemGroup.ts

**Comment by johnleider** [comment]
All `v-stepper` updates are being moved to v2.0 due to backwards compatibility issues.

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
