### ISSUE TITLE
Should Snackbar/toast have an elevation drop-shadow?

### ISSUE THREAD

**Issue by Phlow2001** [vuetifyjs/vuetify#461]
According to https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage under Placement, "they are equal in elevation to the floating action button".

Floating action buttons have drop-shadows, as seen here:
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

However, none of the snackbar/toast examples show a drop-shadow.

I just thought the toast could use a bit more visual appeal.

**Comment by johnleider** [comment]
That's definitely a good find, thank you very much!
