### ISSUE TITLE
[Feature Request] Add empty state

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#4610]
### What problem does this feature solve?
It's part of the [Material Design guidelines](https://material.io/design/communication/empty-states.html) and provides user friendliness. 

### What is your proposed solution?
An empty state component to be inserted everywhere, like [here](https://vuematerial.io/components/empty-state).

**Comment by yordis** [comment]
@ndabAP I don't believe that Vuetify should do anything about it.

From the guideline

> For example, they can include a list without list items, or a search that returns no results.

That explanation is really open to interpretation and you could get into a rabbit hole.

Here is the first question: what do you mean by empty state?!

The answer to that question is completely related to the project and the use cases, Vuetify taking absorption of what is empty states and which component should have empty state or not will make the framework to be hurt in the core, better to give you the tools for be able to do those use cases than assuming that everyone has to do it in one way.

Another, Which components?!

You could probably find a bunch of components that make sense for sure but others that are not so obvios could actually make sense for somebody, for example.

Would you have an empty state for a button?

I could have that use case for sure.

I don't believe that Vuetify needs to do anything for this.

**Comment by ndabAP** [comment]
> what do you mean by empty state

A call to action to increase the user engagement. I think it's pretty clear.

> The answer to that question is completely related to the project and the use cases

Most real world examples from Google consist of an image and a text. The table component already supports the empty state with the property `no-data-text`. My use case would be the first example at the Material Design guidelines. It's used at [Google Inbox](https://78.media.tumblr.com/9b38cc9022014d03c178187305ef7859/tumblr_nhkufzIxPk1rdf37to1_1280.png).

> Would you have an empty state for a button?

I don't see any purpose here. There is no real world example as I know.

**Comment by peterthomassen** [comment]
I agree. I would think that most data tables need an empty state. This is already supported through `no-data-text`, but no image can be set. However, the Material Guidelines say:

> The most basic empty state consists of a non-interactive image and a text tagline.

It would be nice if that "most basic" interpretation would be supported. A [neutral image default](https://www.patternfly.org/pattern-library/communication/empty-state/) might not hurt, either.

(From the quote, you can also see that buttons usually are not in scope for this.)

**Comment by KaelWD** [comment]
There is a `no-data` slot too.

**Comment by peterthomassen** [comment]
aha! In that case, I concur and don't think anything needs to be done. (I missed in the docs that the table with the props also has a "slots" tab. Still new -- sorry.)

**Comment by 06b** [comment]
Depending on the application I can see some cases where the `no-data` slot could work for an empty state, but I think there is still some validity to adding an empty state slot in addition to having a no data state.

For example - a `no-data` slot that states "No Data - Please adjust your filter criteria and try again." might be a correct statement to give a user however that message might not be the best first impression to give a user.

**Comment by peterthomassen** [comment]
How about a `v-if` inside the `no-data` slot, to distinguish these two cases?

**Comment by 06b** [comment]
The funny thing is I'm actually doing a `v-if` already in the `no-data` slot related to #4965 in the project I'm working on and I happen to be hiding the data-table for my empty state, but every project is different.

Ultimately "It Depends™" :)

**Comment by johnleider** [comment]
Since this component is very basic, I have no issues with implementing it. However, it's not going to make v2.0 release.

**Comment by johnleider** [comment]
To give everyone an update. @DRoet is going to champion the development of this component. It's being moved off of a minor release in 2.x due to the upcoming release of Vue 3 and the preparations that are being taken to prepare for it.

**Comment by mertyertugrul** [comment]
I am looking forward to this.

**Comment by TibebeJS** [comment]
any update/progress on this component please
