### ISSUE TITLE
[Feature Request] Add loading state to card

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#4611]
### What problem does this feature solve?
An uniform way of loading indication instead of having to choose between spinner and progress bar.

### What is your proposed solution?
Like other components: 

`<v-card :loading="isLoading"></v-card>`

**Comment by praveenpuglia** [comment]
@KaelWD do we have anything in material guideline to have a loading state to cards? This is something I too have wanted sometimes. May be a circular spinner?
