### ISSUE TITLE
Lazy Load Images in <v-card-media>

### ISSUE THREAD

**Issue by kamleshkatpara** [vuetifyjs/vuetify#4614]
Hi @johnleider 

### What problem does this feature solve?

How can we implement lazy load images feature in <v-card-media> ?
It will be useful for better U/X

I tried some of the lazy load modules, but none of them worked.

### What is your proposed solution?

add a data-src property to lazy load images

**Comment by KaelWD** [comment]
Duplicate of #2951

**Comment by kamleshkatpara** [comment]
@KaelWD  I didn't find any solutions there

**Comment by johnleider** [comment]
That is because they are currently in development. Kael was simply stating that this request has already been made.
