### ISSUE TITLE
[Bug Report] "v-content" doesn't update when drawer side is changed

### ISSUE THREAD

**Issue by n0ise9914** [vuetifyjs/vuetify#4617]
**Versions and Environment**
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Chrome
OS: Windows 10

**Problem**
"v-content" not restoring back to its actual "width" after switching RTL

**Codepen**
https://codepen.io/n0ise9914/pen/MBKJog

![GIF](https://cdn.discordapp.com/attachments/351121729164410882/467967851337089025/CaptureWiz_018.gif)

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/LBBNwW?editors=1010
