### ISSUE TITLE
Data Table | Requires Sorting

### ISSUE THREAD

**Issue by jteppinette** [vuetifyjs/vuetify#462]
### Steps to reproduce
1. create a data table that has all of its headers with `sortable: false`

### Versions
```
vuetify: 0.11.1
vue2-leaflet: 0.0.47
vue: 2.2.6
chrome: 58.0.3029.81 (64-bit)
```

### What is expected ?
The data table should allow you to have sorting disabled. This is important, because the data table currently doesn't support async data, so sorting on paginated data is not exactly correct.

### What is actually happening ?
If your defined headers do not include an item with `sortable: true`, then the view will crash.

*vuetify/src/components/tables/DataTable.js:114*
```
this.sorting = !this.sorting ? this.headers.find(h => !('sortable' in h) || h.sortable).value : this.sorting
```

The code listed above makes a `.value` check on the first `sortable` header, but if there are no `sortable` headers, it still attempts the lookup and crashes.

### Reproduction Link
https://codepen.io/jteppinette/pen/MmpqmM

**Comment by nekosaur** [comment]
This should be fixed in dev.

**Comment by jteppinette** [comment]
@nekosaur I can confirm that this is working properly in the `dev` branch.
