### ISSUE TITLE
[Feature Request] Add onChange event in v-text-filed

### ISSUE THREAD

**Issue by kyusupov33** [vuetifyjs/vuetify#4623]
### What problem does this feature solve?
Please add onChange event for update current input value. Now this feature can be used only in select element.

### What is your proposed solution?
Such like this:
`<v-text-field :change="val => props.item.value = val"></v-text-field>`
or
`<v-text-field :change="onChange"></v-text-field>`

**Comment by KaelWD** [comment]
It's an event - `@change="onChange"`
