### ISSUE TITLE
[Feature Request] Divide hide-actions in data-table

### ISSUE THREAD

**Issue by kyusupov33** [vuetifyjs/vuetify#4625]
### What problem does this feature solve?
Please add the ability to hide only pagination actions without "rows per page" select.

### What is your proposed solution?
![image](https://user-images.githubusercontent.com/29026701/42772574-8b3f631c-8933-11e8-9eaf-82942932d5e1.png)

**Comment by KaelWD** [comment]
Why

**Comment by kyusupov33** [comment]
Because it useless if u would like to use v-pagination

**Comment by KaelWD** [comment]
You have to implement it yourself using the `pagination` prop.
