### ISSUE TITLE
Checkbox not working with keyboard (spacebar) on Firefox

### ISSUE THREAD

**Issue by Phill** [vuetifyjs/vuetify#4627]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Firefox
OS: Linux

### Steps to reproduce
Tab into a checkbox and press the spacebar.

### Expected Behavior
The checkbox should check.

### Actual Behavior
The checkbox checks then unchecks right after.

### Reproduction Link
https://vuetifyjs.com/en/components/selection-controls#usage

Works fine in Chrome.

**Comment by jacekkarczmarczyk** [comment]
Same with v-switch

**Comment by DoritoBandito** [comment]
Firefox will not allow preventDefault() on Space with KeyPress event, although it will with KeyUp, can we change selectable mixin to use KeyUp instead of KeyPress?

**Comment by NiloCK** [comment]
Some other points:

- behaviour is the same in Windows FF
- The `Enter` key doesn't have the same problem
- No related problems with Edge, as far as I could see.
