### ISSUE TITLE
[Bug Report] Carousel not update when data change

### ISSUE THREAD

**Issue by xfront** [vuetifyjs/vuetify#4628]
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chromium 66.0.3359.181
**OS:** Android, Linux

### Steps to reproduce
yarn install
cordova prepare
yarn run cordova-serve
 open browser 

### Expected Behavior
should show grid on center Carousel after 3s startup

### Actual Behavior
Carousel not updated!!!!

### Reproduction Link
[https://github.com/xfront/smartpos](https://github.com/xfront/smartpos)

### Other comments
I change v-container, it's updated ok.

**Comment by jacekkarczmarczyk** [comment]
This is not a valid reproduction 
https://stackoverflow.com/help/mcve
