### ISSUE TITLE
[Bug Report] v-autocomplete: Different select behavior with custom filter

### ISSUE THREAD

**Issue by StefanFeederle** [vuetifyjs/vuetify#4630]
### Versions and Environment
**Vuetify:** 1.1.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
See codepen. Type 15 in both inputs. The input with the default filter does focus the last item that remains after filtering. The input with custom filter doesn't.

### Expected Behavior
When using a custom filter function the last item that remains in the dropdown should be focused.

### Actual Behavior
The focus does not show. It can however be selected with tab or enter.

### Reproduction Link
[https://codepen.io/anon/pen/ZjWVwK?editors=1010](https://codepen.io/anon/pen/ZjWVwK?editors=1010)

### Other comments
Is my filter function wrong? When typing only numbers I want to filter by the item Ids exactly. When typing text I want to search the compountName.

**Comment by StefanFeederle** [comment]
I'm still having the issue and investigated further.
It only happens when the intermediate input already filtered to zero results. Then the full input will find one result again but is not focused.
Test with searching for 15 or 25. Searching for 15 works perfectly because the intermediate result is 1. 25 breaks because there is no result for 2.

Can you point me in the right direction please? Then i'll try to create a PR.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity. If this is still present in the latest version, please provide a reproduction in a new issue.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
