### ISSUE TITLE
[Feature Request] Add a way to get paginated items currently shown on v-data-table with event on change

### ISSUE THREAD

**Issue by savitadwr** [vuetifyjs/vuetify#4631]
**New Functionality**

In `v-data-table`, in some scenarios, we need to perform some actions only on the rows displayed. 

So it would be nice to add an event (may be `change:paginated-items` or `change:active-items`) on change in paginated items with event payload containing updated paginated items.

There is `update:pagination` event, but it does not contain the updated paginated items in payload

**Comment by marcusx** [comment]
`+1`
Is this difficult to implement? I would need that desperately and would like to help with that? But I might need a bit of support how the internalys of `v-data-table` work.

**Comment by nekosaur** [comment]
It's something that's planned for the 2.0 refactor of data-table.

**Comment by nekosaur** [comment]
This is available in 2.0 with event `current-items`

**Comment by mabsito** [comment]
Is there any event that is triggered after the table items are displayed and not before? current-items event and the other available events are triggered before changing the content of the table and I need an event that is triggered after the update of the new table content to do some modifications with it using javascript methods.
If there is no event actually, is there any workaround to lose my problem?
Thanks !
