### ISSUE TITLE
[Bug Report] v-select not displaying 2 items with same item-text

### ISSUE THREAD

**Issue by martinjeannot** [vuetifyjs/vuetify#4633]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.3
Browsers: Chromium
OS: Linux Mint

### Previously worked in:
Vuetify: 0.17
Vue: 2.5.3

### Steps to reproduce

Create a v-select component with 2 items having the same value within the field used as item-text.
For example : 
```
items : [
  { cityName: 'Foo', state: 'FL', population: 2000 },
  { cityName: 'Foo', state: 'CA', population: 3000 }
]
```
In this case, the field we would like to display as item-text is cityName.
### Expected Behavior

The list should display the 2 lines, regardless of them having the same displayed text.
In my case, I use the item scoped slot to display more info, allowing the user to make the right choice so it does not matter that, when the user has made his choice, the displayed item-text is the same as another item in the list (since the user know which he clicked).

### Actual Behavior

Only one of the 2 items shows up in the list.

### Reproduction Link

https://codepen.io/anon/pen/KBzLRy

---

### Additional Comments:
The use of the selection scoped slot works well as a workaround for this bug so I'm not even sure this is a bug at all. I do understand the need of a key to know which item is which and I suspect the item-text being used as one when no other information, such as a custom selection appearance, is provided.

I still wanted to report this behavior because I'm almost certain it worked for us before migrating to 1.1 so it may surprised other Vuetify users as well. Still, great framework, keep up the good work guys !

**Comment by KaelWD** [comment]
If `item-value` is not provided, it will use `item-text` instead. I don't know why this worked previously, but it probably wasn't intentional.

**Comment by martinjeannot** [comment]
@KaelWD Makes sense, I also think it may have to do with the default value of the `return-object` property. I was able to replicate the behavior of 0.17 in 1.1.4 by specifying this property whereas it was not needed before migration.
The doc shows that currently the default value of `return-object` property is false, but it may have been true in 0.17 and before, hence the override of the behavior you explained.

Anyway, I let you decide if it's a bug or not and what to do with this issue (after all, a major version update may introduce breaking changes).

**Comment by labibimamhidayat** [comment]
@martinjeannot did you find any solution for that ? till this bug fixed?, i have same problem with that select same value of item-text

**Comment by martinjeannot** [comment]
@labibimamhidayat As stated in my original bug report, I used the selection scoped slot as a workaround to reproduce the default behavior of the v-select component. I don't remember the details exactly but I recall that I had to add vuetify specific styling to the "replicated" component (in the scoped slot) for it to "look n feel" like the rest of the UI.

**Comment by KaelWD** [comment]
See #6170
