### ISSUE TITLE
Multiple v-selects in same scope do not work unless wrapped in divs

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#4636]
Version 1.1.4

When I use multiple v-select or v-autocomplete, they will not both render unless I wrap them inside a container div.  Also, any HTML after unwrapped v-select does not render at all.

https://codepen.io/Flamenco/pen/BPzyOg?editors=1111

**Comment by KaelWD** [comment]
Components in DOM templates cannot be self-closing. 

https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended

**Comment by Flamenco** [comment]
@KaelWD,

>Components in DOM templates cannot be self-closing.

Components in DOM templates **should not** be self-closing unless in single-file components.  I am sorry, but this can, and should work, it simply does not.  This is a Vue single-file component template, and should be able to handle the use case.

Also, please read this from the Vue site
>Self-closing components STRONGLY RECOMMENDED
Components with no content should be self-closing in single-file components, string templates, and JSX - but never in DOM templates.

https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended

**Comment by Flamenco** [comment]
@KaelWD 
FYI My use case IS a single-file component and has the same result as the codepen.

**Comment by jacekkarczmarczyk** [comment]
Please use codesandbox to provide a reproduction that is using a vue files
