### ISSUE TITLE
Missing polyfill for Object.assign in documentation

### ISSUE THREAD

**Issue by thupi** [vuetifyjs/vuetify#464]
I was screening material design component libraries for Vue and found this awesome one. I was focused on browser compatibility and was testing the components in IE11. When I visited the documentation from IE11 I discovered an error in the console due to a missing property named `assign` of `Object`.

This issue can easily be fixed either by adding `babel-plugin-transform-object-assign` to the babel config or adding some polyfill such as `babel-polyfill` or polyfill.io :-)

**Comment by johnleider** [comment]
Can you please post this on the documentation [repo](https://github.com/vuetifyjs/docs).

**Comment by thupi** [comment]
After solving this issue in my project, i discovered that it is Vuetify that uses Object.assign. That might be by design if you don't support IE11 as most modern browsers support that :-) ?

**Comment by johnleider** [comment]
We are going to support IE11, begrudgingly. I'll be making updates this month.

**Comment by kelvinau** [comment]
Object.assign is still being used in 1.3.5. Does Vuetify fully support IE11? or I need to use babel actually?
