### ISSUE TITLE
[Bug Report] Vertical Dividers Regression - Width

### ISSUE THREAD

**Issue by slathrop** [vuetifyjs/vuetify#4641]
### Versions and Environment
Vuetify: 1.1.5
Browsers: Chrome, Firefox, Edge
OS: Windows

### Steps to reproduce
See example in Vuetify docs website [here](https://vuetifyjs.com/en/components/dividers#example-vertical) and note that the alignment/spacing of "My Home" text is off due to 100% width of vertical divider that is directly inside v-toolbar (in .v-toolbar__content)

### Expected Behavior
`.v-divider` to have `width: auto`

### Actual Behavior
`.v-divider` has `width: 100%` when directly inside a v-toolbar

### Reproduction Link
https://vuetifyjs.com/en/components/dividers#example-vertical
---

### Additional Comments:
Chrome is telling me that `v-divider` class is incorrectly getting `width: 100%` due to [this](https://github.com/vuetifyjs/vuetify/blob/c1404ab099748f83755cc954a994c77564529d69/src/stylus/components/_dialogs.styl#L50) line of code

**Comment by AlexSHoffman** [comment]
Does `.v-divider` even need a `width` rule? 

It looks like `flex` rule is handling the width by itself.

![output](https://user-images.githubusercontent.com/13764106/42848455-4d4cae20-8a28-11e8-9359-910fe6f49356.gif)
