### ISSUE TITLE
[Feature Request] Add aria-label="Rows per page:" to VDataTable row selection

### ISSUE THREAD

**Issue by bamab** [vuetifyjs/vuetify#4642]
### Problem to solve
I recently updated a project from 1.0.0-beta.4 to 1.1.4 (and now 1.1.5) and started receiving 508 compliance errors for missing labels on the v-data-table row selector. This error did not exist in the previous version.

### Proposed solution
Add aria-label="Rows per page:" to combobox div as previous versions did:

```
<div class="datatable__actions__select">
  Rows per page:
  <div tabindex="0"
    data-uid="27"
    aria-label="Rows per page:"
    role="combobox"
    class="input-group input-group--append-icon input-group--hide-details input-group--text-field input-group--select input-group--auto primary--text"
  >
```

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/32de3fa04fd359d001513295709ed05ca3fd5619/src/mixins/data-iterable.js#L423

Attrs aren't being passed through any more

**Comment by bamab** [comment]
I do not follow. How do you code the aria-label for the rows per page selection? I do not see a prop for it.

**Comment by KaelWD** [comment]
It should be there by default now, using the `rows-per-page-text`

**Comment by bamab** [comment]
Ah, had to update to 1.1.16. Thanks!

**Comment by notapianokey** [comment]
Also `aria-label` started working for `v-btn`, but this might be because I updated vue core at the same time.
