### ISSUE TITLE
[Bug Report] Autocomplete requires multiple clicks to close menu with conditional data

### ISSUE THREAD

**Issue by stephen-bunn** [vuetifyjs/vuetify#4644]
### Versions and Environment
**Vuetify:** 1.1.5
**Vue:** 2.5.16
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
- Create an autocomplete component using a method to retrieve items

```html
<v-autocomplete
  :items="getTypes()"
  v-model="selectedType"
></v-autocomplete>
```

- Requires two clicks on the desired item to select the item and close the menu

### Expected Behavior
Should close the autocomplete select menu when the item is clicked once.

### Actual Behavior
Requires two clicks on the desired menu item before the menu is hidden.

### Reproduction Link
[https://codepen.io/stephen-bunn/pen/KBMXqW](https://codepen.io/stephen-bunn/pen/KBMXqW)

### Other comments
This previously worked fine with `v-select` using the `autcomplete` prop prior to the release of the `v-autocomplete` component. I'm unsure if this is intended.

**Comment by johnleider** [comment]
You shouldn't bind data like that. It will get reset during re-hydration. Use a computed property instead: https://codepen.io/johnjleider/pen/KBMRZK

**Comment by ecmel** [comment]
If server side data is used, this behavior can still be seen.

In the first selection, because of search field sync it makes another request to the server and the menu appears again.
