### ISSUE TITLE
[Bug Report] Text fields could not handle the height properly

### ISSUE THREAD

**Issue by wfoxd** [vuetifyjs/vuetify#4646]
### Versions and Environment
**Vuetify:** 1.1.5
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Add a v-text-field and set the height to 12

### Expected Behavior
The whole text field height to 12

### Actual Behavior
The label text doesn't change

### Reproduction Link
[https://codepen.io/wfoxd/pen/WKxdmb](https://codepen.io/wfoxd/pen/WKxdmb)

**Comment by KaelWD** [comment]
That isn't something we support, see #1846

**Comment by admiralman12** [comment]
How do you not support this when there is an attribute in the documentation that specifically states it is supported?

**Comment by Nealon01** [comment]
Just to be clear, there is no supported way to change the height of a textbox in Vuetify?  That's laughable.
