### ISSUE TITLE
[Bug Report] Password Input - appended icon is not functioning

### ISSUE THREAD

**Issue by ericyam94** [vuetifyjs/vuetify#4647]
### Versions and Environment
Vuetify: 1.1.5
Vue:
Browsers: Chrome
OS: Windows

### Previously worked in:
Vuetify: 1.1.4
Vue:

### Expected Behavior

Should be able to show/hide password by click append icon in password input

### Actual Behavior

Showing/hiding password by clicking append icon in password Input from text-field component is not working.

### Reproduction Link

https://codepen.io/anon/pen/XBKqqN?&editors=101

**Comment by KaelWD** [comment]
Probably caused by #4545, that `this.$listeners[eventName](e)` bit looks pretty dodge
