### ISSUE TITLE
[Bug Report] disabled parameter trickles down

### ISSUE THREAD

**Issue by simon-stoic** [vuetifyjs/vuetify#4648]
### Versions and Environment
**Vuetify:** 1.1.5
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Put a v-btn and/or a v-tooltip inside a disabled v-menu and the v-btn and v-tooltip will also be disabled even if you explicitly set them as enabled.

### Expected Behavior
v-btn and v-tooltip should be enabled.

### Actual Behavior
v-btn and v-tooltip are disabled.

### Reproduction Link
[https://codepen.io/sjodet/pen/zLByOG?editors=1010](https://codepen.io/sjodet/pen/zLByOG?editors=1010)

**Comment by KaelWD** [comment]
```css
.v-menu__activator--disabled {
    pointer-events: none;
}
```
This is working as intended.

**Comment by simon-stoic** [comment]
@KaelWD I should be able to disable a menu and keep the components inside of it enabled. Why is this the desired behavior?
