### ISSUE TITLE
Typo Roboto font import

### ISSUE THREAD

**Issue by jmharveys** [vuetifyjs/vuetify#4659]
Even if you use **.font-weight-thin** or **.font-weight-light** class, the result is always Roboto thin.
There is a typo into the index.html file.

Please change the font <link> import Roboto in **public/index.html** from

`<link href="https://fonts.googleapis.com/css?family=Roboto:100:300,400,500,700,900|Material+Icons" rel="stylesheet">`

TO

`<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet">`

Thank you!

**Comment by KaelWD** [comment]
Is this in the documentation? Whatever it is, this is the wrong repo for this issue.
