### ISSUE TITLE
Tabs Transition Translate -X Direction when Going From Right to Left Tab

### ISSUE THREAD

**Issue by staffordjh** [vuetifyjs/vuetify#466]
Hi,

Thank you for your work on Vuetify. I was really happy to see the quality of your framework and its use of the Bootstrap layout in the demos. I was going to start playing around with it soon.

My issue is in regards to the tabs component in the demo. I think adding a reverse slide direction with transform: translate3d(-X,0,0);  would really improve the UI feel if going from a Right to Left tab (kind of a previous feel). Both the Right to Left and Left to Right tab selection directions show the same transition (transform: translate3d(+X,0,0); ). Is this going to be changed, or can I configure on my own?

Thanks again for your work.

**Comment by johnleider** [comment]
That functionality exists, it's apparently not working however.

**Comment by staffordjh** [comment]
Thanks for the quick response John. Keep up the good work on Vuetify.

**Comment by staffordjh** [comment]
Hi John, thank you for your quick response. Are your builds on the demo reflective of this #466 code push?

**Comment by johnleider** [comment]
Right now this change exists on dev branch. It must be built and linked to your project if you want to see the result.
