### ISSUE TITLE
[Feature Request] Spacing should have "start" and "end" directions

### ISSUE THREAD

**Issue by tamirvs** [vuetifyjs/vuetify#4660]
### What problem does this feature solve?
Having **start** and **end** directions for [spacing](https://vuetifyjs.com/en/layout/spacing) could help a lot with designs that support both RTL and LTR.

### What is your proposed solution?
`s` - applies the spacing for `*-left` in LTR and `*-right` in RTL.
`e` - applies the spacing for `*-right` in RTL and `*-left` in LTR.

Would really appreciate it if you could add it!

**Comment by ibrahimBeladi** [comment]
Will this be implemented and shipped into v2.0?

**Comment by jacekkarczmarczyk** [comment]
fixed by https://github.com/vuetifyjs/vuetify/pull/7448
