### ISSUE TITLE
[Bug Report] Clearable prop on a v-text-field with a type of password can crash the page

### ISSUE THREAD

**Issue by wishinghand** [vuetifyjs/vuetify#4661]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Mac OS 10.13

### Steps to reproduce
When setting up a `v-text-field` with a `clearable` prop and a `:rules` validation, it will crash the page when the clear functionality is used.

The example code is in the `App.vue` in the CodeSandbox link I provided.

### Expected Behavior
When the `X` is clicked, the field with clear the data and not crash the page.

### Actual Behavior
When the `X` is clicked to clear the field, the field clears, and the validation throws an error in the console.log saying: `TypeError: "v is null"` and a second error after it: `TypeError: "_this4.$refs.input is undefined"`. The page becomes unresponsive, the laptop's fans come on, and eventually Firefox shows a toast that says: 'A web page is slowing down your browser, what would you like to do?'

### Reproduction Link
[https://codesandbox.io/s/pxx4r1940](https://codesandbox.io/s/pxx4r1940)

**Comment by wishinghand** [comment]
I think I have it working: https://codesandbox.io/s/pk64y1r9vx

**Comment by wishinghand** [comment]
I think I have it working: https://codesandbox.io/s/pk64y1r9vx

**Comment by KaelWD** [comment]
That sandbox crashes the tab?

**Comment by wishinghand** [comment]
Nothing crashes in Codesandbox, I just put in the code that crashes my tab in Firefox when run in a normal environment.

**Comment by wishinghand** [comment]
The console of Codesandbox does show the `TypeError: "v is null", but it doesn't have the `TypeError: "_this4.$refs.input is undefined"` that I see on my dev site.

**Comment by KaelWD** [comment]
`v is null` is your rule not accounting for null values, can't help with the other one if it doesn't happen.

**Comment by wishinghand** [comment]
I think that's almost correct. If a user must account for null values, that breaks the truthy/falsy dichotomy being relied on in the docs for input validation. If a value is falsy, it returns the string associated with the check. Using the `clearable` prop renders the value `null`, it makes simple, one-liner validations impossible. I can't tell if this is a bug or merely that the built-in validations and `clearable` are incompatible and that it was missed because it's impossible to account for all interactions.

**Comment by KaelWD** [comment]
#4144

**Comment by KaelWD** [comment]
Crash reproduction was not provided, and the other problem is already reported in another issue.
