### ISSUE TITLE
[Bug Report] Expansion panel inside (second) Tab starts closed

### ISSUE THREAD

**Issue by tommybravo** [vuetifyjs/vuetify#4669]
### Versions and Environment
**Vuetify:** 1.1.6
**Vue:** 2.5.16
**Browsers:** Firefox 60.0
**OS:** Windows 10

### Steps to reproduce
Create vTab component, add vExpansionPanel to the second tab (or any tab that is not the starting tab). Use "expand" directive on vExpansionPanel with v-model that is set to an array of "true" values.

### Expected Behavior
Selecting the relevant tab, the expansion panels should render open.

### Actual Behavior
All expansion panels start closed. Clicking on the "header" turns the relevant v-model value to false (expansion panel does not change, remains closed), a second click on header returns the v-model to "true" and opens the expansion panel.

### Reproduction Link
[https://codepen.io/anon/pen/YjppLR](https://codepen.io/anon/pen/YjppLR)

### Etc.
[might be related issue](https://github.com/vuetifyjs/vuetify/issues/4483)

**Comment by tommybravo** [comment]
v1.1.8 shows the same issue and adds further issue by messing up the width of the expansion icon. Maybe that should be a separate issue, as it relates to CSS, I guess.

**Comment by johnleider** [comment]
Fixed with e084f2787e922772e77e961efc31d8b104486818
