### ISSUE TITLE
Dialog transition when navigating away

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#467]
When navigating to a specific route I want to show a dialog with a transition. This works fine when setting the dialog's `v-model` to `true` when the component is `mount()`ed. But, I also want to show the transition when navigating away from this route. How would I do this? Can I somehow programmatically close the dialog and `$router.push` afterwards? Or is there a better way?

Fiddle: http://jsfiddle.net/h4kpvk4v/11/

**Comment by johnleider** [comment]
You could use the [beforeRouteLeave](https://router.vuejs.org/en/advanced/navigation-guards.html) hook in your component.

**Comment by maartendraijer** [comment]
@johnleider Ah, great. Thanks. But.. how to "wait" until the `v-dialog` has been closed? I can of course set a timeout, but that feels a little ugly. Also when the transition duration of the dialog changes this won't work anymore.

**Comment by johnleider** [comment]
You could bind an event to 'transitionend' on the dialog.
