### ISSUE TITLE
[Feature Request] Autocomplete allows selection of filtered-out items when search query is empty

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#4670]
### Versions and Environment
Vuetify: 1.1.7
Vue:
Browsers: Firefox
OS: Linux

### Steps to reproduce

1. Open https://codepen.io/anon/pen/bjBWLG
2. Click on autocomplete field
3. Observe that "sunt aut facere repellat provident occaecati excepturi optio reprehenderit" is shown first
4. Type "sunt"
5. Observe that it is hidden
6. Remove everything from autocomplete query
7. Observe that it is shown again

### Expected Behavior

I want to filter some results and prevent the user to select them. This should be true even if user did not type anything yet in, or if they cleared everything.

### Actual Behavior

The issue is that if there is autocomplete is empty, all known values are shown. Which does allow the user to select a forbidden entry. The same if they clear the autocomplete.

In my case user is moving items from the autocomplete list to another list in UI. I want to filter out items which are already in the second list. Items are coming from the server and  so I am required to use `cache-items`. Because of that I cannot pre-filter items (because items are cached anyway), but have to rely on `filter` function. But `filter` does not work without a query string, so I cannot prevent user to select cached items which already exists in the second list.

### Reproduction Link

https://codepen.io/anon/pen/bjBWLG

**Comment by johnleider** [comment]
I don't know if I would classify this as a bug. Sounds like maybe you are recommending a **pre-filter** prop.

**Comment by mitar** [comment]
Hm, or maybe a prop which tells if all results should be shown without a search or not?

But I am not sure why filter could not be called also when query is empty? Default function could behave the same as now, not filtering anything.

**Comment by johnleider** [comment]
@vuetifyjs/dev-team thoughts?

**Comment by KaelWD** [comment]
I'd leave it to the filter function, and just have the default one return everything if there's no search. This would be a breaking change however.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. If this is still relevant, please create a new issue with an up-to-date reproduction and description.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
