### ISSUE TITLE
[Feature Request] Deselectable v-radio component (radio buttons)

### ISSUE THREAD

**Issue by madarche** [vuetifyjs/vuetify#4676]
Hello all,

### What problem does this feature solve?

Presently, once selected, a v-radio component cannot be deselected when clicked again. This behavior is the classical behavior of the HTML radio buttons.

The proposed feature is to add a property to make it possible to *deselect* a selected v-radio when clicked again.

The proposed feature is not what web users used to HTML radio buttons expect, but it adds a very neat addition, making UI really more sleek and powerful in some situations. The pros and cons of this feature are discussed over and over again: https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs. So the aim of this feature is not to try to convince people to use this feature, but rather to make it possible to use it if it is needed for some usecases.

Our usecase is building sleek surveys where people can easily reset/erase their answers, and that is deselect mutually exclusive options. We already have this HTML component in our old in-house UI library, but as we are switching to Vuetify we would love to have this feature available by default in Vuetify.

If you agree to this feature request we could provide a PR adding this feature. If you don't agree we would create a custom component on our own, but that would be sad.

### What is your proposed solution?

Our proposed solution is to provide a new `deselectable` property to `v-radio-group`, of course `false` by default.

This new property will play well with the already existing `mandatory` `v-radio-group` property.

**Comment by johnleider** [comment]
I think this probably belongs in userland. It differs from the definition of a radio and is very easy to implement: <https://codepen.io/johnjleider/pen/RBKgwd>

**Comment by madarche** [comment]
Thanks for your very fast answer @johnleider!

But allow me to object: the proposed userland solution doesn't scale at all. We have this survey application of ours, which is a form generator, which creates form fields programmatically. It programmatically instantiates vuetify components and sets their properties. The userland proposition is not (cleanly) possible in this case.

Moreover the proposed solution doesn't deselect the concerned radio when its corresponding label is clicked.

Considering this information, could you reconsider your decision to close this feature request? (and again we would propose the PR)

Thanks!

**Comment by johnleider** [comment]
Let's see what @vuetifyjs/dev-team thinks.

**Comment by madarche** [comment]
Thanks a lot!

**Comment by madarche** [comment]
Hello all,

Based on your very helpful comments, here is published the [`v-radio-deselectable`](https://www.npmjs.com/package/v-radio-deselectable) component, which is, as discussed, a wrapped `v-radio` component.

We still think that having the `deselectable` property on the `v-radio-group` would be a better solution, more practical, more powerful and easier to use for everyone.

Please everyone interested, could you [read the `v-radio-deselectable` code](https://github.com/madarche/v-radio-deselectable) and tell us if it can be improved?

**Comment by johnleider** [comment]
This can now be accomplished with `v-item-group` in v1.3

**Comment by kanteankit** [comment]
@johnleider Can you provide an example of how to accomplish this with `v-item-group`?
I came up with this,but, it is not working: https://codepen.io/anon/pen/yRxpyd

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/GYeMPx?editors=1111

**Comment by AledGBeso1Ded** [comment]
@johnleider How can you select the correct radio if we need to take his status (checked or unchecked)

**Comment by FrancMihani** [comment]
@johnleider @madarche 
Hello! I fixed it using v-checkbox inside a v-radio-group instead a v-radio, here is an example

 <v-radio-group v-model="item.readWrite" dense row>
              <v-checkbox label="R" value="r" v-model="item.readWrite" />
              <v-checkbox label="R/W" value="rw" v-model="item.readWrite" />
</v-radio-group>

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
