### ISSUE TITLE
Two column sidebar navigation

### ISSUE THREAD

**Issue by nsarvar** [vuetifyjs/vuetify#4677]
I would like to build two column sidebar navigation as shown on the picture below:
[https://ibb.co/kdf0KJ](https://ibb.co/kdf0KJ)
I'm trying to use `<v-navigation-drawer>` next to each other and customized, but it is not working as expected. What is the best way to make such type of sidebar navigation?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

https://vuetifyjs.com/en/components/navigation-drawers#example-combined
