### ISSUE TITLE
[Enhancement] v-combobox does not update until blur

### ISSUE THREAD

**Issue by nalbion** [vuetifyjs/vuetify#4679]
(Possibly unrelated) `v-combobox` does not seem to emit "input" events, only "update:searchInput".
I tried to use with [v-debounce](https://github.com/vuejs-tips/v-debounce) but it did not work.

I have a `v-combobox` in a `v-form`, it is a required field with `rules`. I want to be able to type in the combobox and see that the validation errors disappear and the submit button is enabled without clicking outside of the combobox

https://codepen.io/nalbion/pen/xJgYjL?editors=1111

**Comment by vincent41** [comment]
i think combobox makes validation on change event, that's why.

**Comment by nalbion** [comment]
I think that's bad UX. It should be possible for the app developer to choose when to validate

**Comment by jacekkarczmarczyk** [comment]
imho combobox should just emit `@input` while typing but it extends v-autocomplete so probably won't be a simple fix

**Comment by romucci** [comment]
Is there a way to update the v-model as soon as you start typing and to be able to search though the selection box?

**Comment by KaelWD** [comment]
No, that's what this issue's for.

**Comment by genez** [comment]
Any workaround until this is fixed?

**Comment by odai-alali** [comment]
you can use the native input event

```vue
<v-combobox :items="$store.state.models.map(item => item.fullName)"
                            @input="setFilterString"
                            @input.native="setFilterString"></v-combobox>
```

```javascript
setFilterString (e) {
      if (!e) {
        this.filterString = ''
      } else if (typeof e === 'string' || !e) {
        this.filterString = e
      } else if (typeof e === 'object') {
        this.filterString = e.srcElement.value
      }
    },
```

**Comment by thexperiments** [comment]
Hitting the same issue here.
My combobox is last in the form and thus when submitting the form it is very likely that it has not blurred yet and thus the value was not propagated to the property yet.

Additional ideas for a workaround?

**Comment by thexperiments** [comment]
https://codepen.io/thexperiments/pen/GeZbxX this demonstrates the issue

**Comment by thexperiments** [comment]
Possible workaround
https://codepen.io/thexperiments/pen/ywOdwe
```
@input.native="category=$event.srcElement.value"
```
where category is the same model attached to the v-model of the combobox.
Would still like it more if it was generic and I could just add this to all the comboboxes without modifying to point to the right model.

**Comment by ziggybrew** [comment]
> @input.native="category=$event.srcElement.value"

This works for disregarding the onblur, but it prevents the combobox from filtering through the object list as I type now. Has anyone solved this added problem?

**Comment by apavel3458** [comment]
Problem still unsolved a year later

**Comment by chouhanyang** [comment]
I have another UGLY workaround. I cannot use input.native since I'm using multiple chips with items containing array of objects {text..., value...}.

```
<v-form ... @submit="form_submit"> ...
...
form_submit: function(event) {
  // XXX: Allow background value update to complete first. (e.g. Combobox).
  //      See https://github.com/vuetifyjs/vuetify/issues/4679
  setTimeout(() => {
    // Actually form submission here.
  }, 100);
},
```

Simply allow blur event to run before submit. Ugly, but seem working fine. Hopefully this helps.

**Comment by MatthewAry** [comment]
I'm very interested in seeing this get fixed. I would like to use the events to track inputs to the field in real time while still being able to use the built-in filtering. Can't do that right now as this component currently is.

**Comment by jacekkarczmarczyk** [comment]
Workaround (updated to Vuetify 2.x) https://codepen.io/jkarczm/pen/pooOOjV?editors=1111 (same as #5203)

**Comment by Paulsky** [comment]
@jacekkarczmarczyk are you sure this workaround still works...? There is no update on input change?

**Comment by Paulsky** [comment]
I created a workaround myself. Please see this CodePen: https://codepen.io/Paulsky/pen/PowEZOE

I'm using the '$refs' to get the 'internalSearch' of a dummy model, and set the 'actually' model. The '@change' is a little misleading; this is only fired when a item from the list is chosen by the user.

Hope this helps someone.

**Comment by MrGuiMan** [comment]
Would love to see a fix for that as well. For now, requesting an animation frame seemed to do the trick for us, since relying on input.native would trigger validation rules too early.

**Comment by SameeranB** [comment]
I have a solution for this, it's just as hacky as all the solutions that have come before... but it doesn't have any side effects like breaking the filter or causing significant delays or complexities.

Here it is:

```
<template>
     <v-combobox  id="targetInput" @keydown="updateTargetInputValue" v-model="currentTargetInputValue" 
                              :items="autocompleteItems"></v-combobox>
</template>

<script>
    ...
    data() {
        return {
             ...
            currentTargetInputValue: null
        }
    },

    methods: {
        updateTargetInputValue() {
           setTimeout(() => {
                   this.currentTargetInputValue = document.getElementById('targetInput').value
           }, 1)
        }
</script>
```

I hope this helps.

`@keyup` doesn't work in this case because it interferes with the filtering.
I gave a timeout because on keydown, the key that was just pressed is not registered.

**Comment by SameeranB** [comment]
I seem to have found a workaround as well. It's less hacky than the others suggested here. I don't think this one has any side effects like broken filtering or delays either.

```
<template>
    ...
    <v-combobox :id="targetInput"
                @update:search-input="updateTargetInput" 
                :rules="rules" 
                :items="autocompletes"
                label="Diet"></v-combobox>
    ...
</template>

<script>
    ...
    data() {
        return {
            currentTargetInput : null
        }
    },
    methods: {
        updateTargetInput(){
            this.currentTargetInput = document.getElementById("targetInput").value
        }
    }
    ...
</script>
```

Turns out that the filtering issue goes away if you don't set a v-model on the component directly.

**Comment by nvspradeep** [comment]
> I seem to have found a workaround as well. It's less hacky than the others suggested here. I don't think this one has any side effects like broken filtering or delays either.
> 
> ```
> <template>
>     ...
>     <v-combobox id="targetInput"
>                 @update:search-input="updateTargetInput" 
>                 :rules="rules" 
>                 :items="autocompletes"
>                 ></v-combobox>
>     ...
> </template>
> 
> <script>
>     ...
>     data() {
>         return {
>             currentTargetInput : null
>         }
>     },
>     methods: {
>         updateTargetInput(){
>             this.currentTargetInput = document.getElementById("targetInput").value
>         }
>     }
>     ...
> </script>
> ```
> 
> Turns out that the filtering issue goes away if you don't set a v-model on the component directly.

When user selects an item from the autocomplete list, currentTargetInput is not getting updated, but rest everything is working 
@SameeranB

**Comment by SameeranB** [comment]
@nvspradeep 
Adding the `@update:list-index` might work. I haven't tried it though...

**Comment by PradeepNooney** [comment]
@SameeranB  **Problem resolved!!**  , I have assigned the value emitted from @ update event directly , instead of doc.getElementbyId.value, Now everything is working!! thanks!


```
<template>
    ...
    <v-combobox id="targetInput"
                @update:search-input="updateTargetInput" 
                :rules="rules" 
                :items="autocompletes"
                ></v-combobox>
    ...
</template>

<script>
    ...
    data() {
        return {
            currentTargetInput : null
        }
    },
    methods: {
        updateTargetInput(currentValue){
            this.currentTargetInput = currentValue
        }
    }
    ...
</script>
```

**Comment by SameeranB** [comment]
@PradeepNooney...  Thank YOU! Finally... It works...

**Comment by ndpu** [comment]
Im use `updateSelf` method (not documented, tested in vuetify 1.5)

From vuetify source (VCombobox.js)
```
updateSelf () {
  this.multiple ? this.updateTags() : this.updateCombobox()
},
```

My form submit:

```
submitForm () {
  // update all cboxses to catch inputed text before work with cbox data
  this.$refs.userCBox.forEach(cbox => cbox.updateSelf());

  // ...
}
```

**Comment by johnleider** [comment]
v2 still has a steady development cycle but has less dedicated developers to focus most of our efforts on v3. As we port over new components to the next version, we are addressing  existing issues before actually making the update. In the meantime, I'm labeling this as help wanted.

The team is working hard to ensure that we are able to disposition and resolve issues within a reasonable amount of time post v3. I want to thank everyone for your patience and understanding.

**Comment by ryanfrawley** [comment]
For anyone who still runs into this in v2, the easiest way I solved it was by manually calling blur() on the combobox ref:

```
<v-combobox ref="combo" v-model="model" />
...
onFormSubmit() {
  (this.$refs.combo as HTMLElement).blur();
  this.$nextTick(() => {
    // model now contains the correct data
  });
}
```

**Comment by dubst3pp4** [comment]
I couldn't get it working with the examples above, but the following works for me:
```typescript
  onBlur (): void {
    (this.$refs.combobox as VCombobox).updateSelf()
  }
```
with the combobox defined as:

```html
  <v-combobox
    ref="combobox"
    @blur="onBlur"
  />
```

**Comment by bar5um** [comment]
`
          @update:search-input="yourVModelData = $event"
`

worked for me!
