### ISSUE TITLE
[Bug Report] VTextarea wrong row-count after clearing it's content

### ISSUE THREAD

**Issue by dmecke** [vuetifyjs/vuetify#4683]
### Versions and Environment
**Vuetify:** 1.1.7
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Open the codepen, focus the textarea and press enter.

### Expected Behavior
The content should be cleared the textarea goes back to one row (as defined with the rows prop).

### Actual Behavior
The content is cleared, but the textarea stays at the row count it had. The row count is adjusted as soon as another key is pressed while the textarea is focussed.

### Reproduction Link
[https://codepen.io/anon/pen/EpZORp](https://codepen.io/anon/pen/EpZORp)

### Other comments
The `calculateHeight` method of `VTextarea` is not getting called when enter is pressed. Also, `onInput` is not called neither in the case of enter.

**Comment by jacekkarczmarczyk** [comment]
fixed by https://github.com/vuetifyjs/vuetify/pull/7363
