### ISSUE TITLE
v-autocomplete behaviour when editing 

### ISSUE THREAD

**Issue by akorz** [vuetifyjs/vuetify#4684]
Hello,

### What problem does this feature solve?

Autocomplete is good for creating form, but in case when it's editing form it should have already selected value. And when you are ready to edit that value autocomplete should to get some data from server, because usually item list is huge.

You can check it what I want 

![screencast](https://user-images.githubusercontent.com/5867543/43044088-5af10b4c-8da8-11e8-87e8-228b9752054c.gif)

Here how autocomplete looks like when I've tried to expand list and items did not loaded yet.

![screencast2](https://user-images.githubusercontent.com/5867543/43044152-cc6a7f00-8da9-11e8-8168-a98d4d58dcda.gif)

### What is your proposed solution?

Add something similar from first image?

**Comment by KaelWD** [comment]
Autocomplete already has support for loading state and custom slots: https://vuetifyjs.com/en/components/autocompletes#example-advanced
