### ISSUE TITLE
[Bug Report] v-footer leaves v-navigation-drawer too short when inset

### ISSUE THREAD

**Issue by a-riva** [vuetifyjs/vuetify#4686]
### Versions and Environment
Vuetify: 1.1.7/1.1.8
Vue: 2.5.16
Browsers: Google Chrome 68.0.3440.68, Firefox 61.0.1
OS: Windows 10 1803

### Previously worked in:
Vuetify: 1.1.6
Vue: 2.5.16

### Steps to reproduce

I am attaching a CodePen with an app navigation drawer and an app inset footer. By removing the inset attribute, the issue is not visible any longer, but only because the space under the drawer is actually needed.

### Expected Behavior

When the footer is inset, the navigation drawer expands to full height.
![image](https://user-images.githubusercontent.com/7723068/43046419-de98138a-8dc8-11e8-988e-189787cb747e.png)
(screenshot captured by changing the CodePen Vuetify version to 1.1.6)

### Actual Behavior

When the footer is inset, the navigation drawer is shorter than full height, leaving some space as if the footer wasn't inset.
![image](https://user-images.githubusercontent.com/7723068/43046403-a55ac9b4-8dc8-11e8-836c-493614776fcd.png)
(screenshot captured by using Vuetify version 1.1.7 on CodePen)

### Reproduction Link

https://codepen.io/a-riva/pen/OwpPOg

---

### Additional Comments:
Bug first appeared on version 1.1.7; still present up to version 1.1.8.

**Comment by wildan2711** [comment]
This also still happens in beta (v1.2.0-beta-3).
