### ISSUE TITLE
[Bug Report] Transition of color out of sync when leaving active state in list tile when used inside navigation drawer

### ISSUE THREAD

**Issue by backbone87** [vuetifyjs/vuetify#4689]
### Versions and Environment
Vuetify: 1.1.7
Vue: 2.x
Browsers: Chrome
OS: Win

### Steps to reproduce
Click the navigation links

### Expected Behavior
Transition of color of title and icon is in sync when leaving active state

### Actual Behavior
Transition of color of title and icon is out of sync when leaving active state

### Reproduction Link
https://codepen.io/anon/pen/RBppbN

### Additional Comments:
If you remove the `div.COMPONENT`, the transition is removed from v-list-tile (there is a special CSS rule for that) and it works as expected. But the extra element is required if you want to have the contents of the navigation in its own component

**Comment by bretonio** [comment]
I have had a similar experience with some but not all of the vue-cli templates for vuetifyjs.  In several projects based on the Nuxt template I have had the desired result out of the box. Current page with a highlighted color on its list tile. Icon and text color in sync. Why? Go figure. Trying to organize a list of was tried and the result.  The Nuxt router is a bit beyond me at this stage. Perhaps you can have a look and explain for dummies.

**Comment by backbone87** [comment]
I think my issue is just a CSS problem. I added an additional `div` so I can satisfy the "single root element per component" rule. But this pervents some CSS rules to be applied to the navigation.
