### ISSUE TITLE
Keep the menu displayed when i click

### ISSUE THREAD

**Issue by leonfather** [vuetifyjs/vuetify#469]
Hi please how can I keep the menu displayed when I click? I want to use a checkbox list in the menu so i need that the menu still displayed, I'm using : https://vuetifyjs.com/components/menus

**Comment by leonfather** [comment]
Hello, Any response please?

**Comment by mfferreira** [comment]
@leonfather You should use a select, instead of menu for that purpose.
https://vuetifyjs.com/components/selects

ps: please be more patient waiting for feedback

**Comment by johnleider** [comment]
In addition to what @marco said, you could use the ```close-on-click``` prop on the menu.

**Comment by leonfather** [comment]
Thanks @johnleider

**Comment by Kraigo** [comment]
I have some issue.
If you want to keep open menu after click on the menu container - you need add @click.stop for root element of menu content

**Comment by johnleider** [comment]
You can also set the prop, close-on-content-click to false.

**Comment by orccufin** [comment]
"You can also set the prop, close-on-content-click to false."
This doesn't seem to work currently, or am I doing something wrong?
`<v-menu offset-y close-on-content-click="false">
        <v-btn color="primary" slot="activator">menu <v-icon>arrow_drop_down</v-icon></v-btn>
        <v-list>
            <v-list-tile v-for="item in items" :key="item.title" @click="click">
                <v-list-tile-title>{{ item.title }}</v-list-tile-title>
            </v-list-tile>
        </v-list>
    </v-menu>`

**Comment by nekosaur** [comment]
Please do not comment on old issues. If you have a problem, create a new issue using https://issues.vuetifyjs.com
