### ISSUE TITLE
[Bug Report] Prop 'full-width' removes the bottom line from the 'v-text-field'

### ISSUE THREAD

**Issue by thisDOTname** [vuetifyjs/vuetify#4693]
### Versions and Environment
**Vuetify:** 1.1.7
**Vue:** 2.5.13
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
Add 'full-width' prop to the 'v-text-field'

### Expected Behavior
The text field should take up all available width

### Actual Behavior
The field takes up all available width but removes the bottom line 

### Reproduction Link
[https://codepen.io/thisDOTname/pen/djvgrJ?editors=1010](https://codepen.io/thisDOTname/pen/djvgrJ?editors=1010)

### Other comments
The 'full-width' prop works as expected but removes the bottom line from the v-text-field

**Comment by KaelWD** [comment]
That's intentional, have a look at the examples.
