### ISSUE TITLE
Checkbox is hard to click with ripple disabled

### ISSUE THREAD

**Issue by rgalaxy** [vuetifyjs/vuetify#4696]
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.2
Browsers: Chrome
OS: Windows 10

### Steps to reproduce
Click the checkbox

### Expected Behavior
Will trigger toggle checkbox by clicking anywhere inside the checkbox

### Actual Behavior
Only trigger when clicked on the top left side of the checkbox.

### Reproduction Link
https://codepen.io/RGALAXY/pen/rrmNPp

---

### Additional Comments:
It happens because, there is `<input>` that is too small. only 13x13 px.
while the checkbox is 24x24px.
today i overwrite it via css (but i think it's ugly, but worked)
the DOM is ` v-input--checkbox > v-input__control > v-input__slot > v-input--selection-controls__input > input`

addition (by @jacekkarczmarczyk ):
it happens only when `ripple` prop is `false`

**Comment by ackushiw** [comment]
I've found the same issue even with the ripple. Additionally the icon doesn't register any clicks. I fixed it with the following CSS:

```
.v-input--checkbox i {
   pointer-events: none;
}
.v-input--checkbox input {
   height: 24px;
   width: 24px;
}
```

**Comment by pegiadise** [comment]
This also happens with `VSwitch` when `:ripple="false"`.
