### ISSUE TITLE
Datatable - on mobile -is it possible to implement or is there a implementation when browsing from phone for DT to collapse into data iterator? 

### ISSUE THREAD

**Issue by jonatancamarena** [vuetifyjs/vuetify#4697]
when viewing in mobile devices is there an implementation to view data-table as collapsed cards as in the data-iterator component such as the behavior in the buefy table components? 

![screen shot 2018-07-23 at 17 51 50](https://user-images.githubusercontent.com/41026174/43107127-31599728-8ea1-11e8-944a-640c86a6643f.png)

**Comment by jacekkarczmarczyk** [comment]
```
<v-data-table v-if="$breakpoint.smAndUp" />
<v-data-iterator v-else />
```

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
