### ISSUE TITLE
[Bug Report] Bottom sheet dismiss mobile, with hide-overlay

### ISSUE THREAD

**Issue by eschirtz** [vuetifyjs/vuetify#4698]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.6

### Steps to reproduce
Set v-bottom-sheet props

hide-overlay

### Expected Behavior
Dismiss sheet when click outside sheet

### Actual Behavior
On mobile, sheet is not dismissed, it is dismissed when the over lay is not hidden, but when hidden, does not get dismissed

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

**Comment by KaelWD** [comment]
Yeah that's the whole point of `hide-overlay`

Follow #4588 for a change to this.

**Comment by eschirtz** [comment]
Isn't it just to hide the tint? It still dismisses when on desktop, but a touch event does not dismiss the sheet. 

Would "persistent" be what you are referring to? 

The only scenario this comes up in is on mobile. So there is most likely a bug. I wouldn't imagine the functionality to be different for click vs touch

**Comment by eschirtz** [comment]
I see your reference, and wasn't aware of that prop. However, something still seems funky with regards to the inconsistency between mobile and desktop
