### ISSUE TITLE
Undesired form submit on select date in picker

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#470]
### Steps to reproduce
Select date in picker inside form

### Versions

vue@2.3.0
vuetify@0.11.1

### What is expected ?
Form is not submitted

### What is actually happening ?
Form is submitted

### Reproduction Link
https://jsfiddle.net/8nz6dsnm/

**Comment by johnleider** [comment]
This is due to the buttons not being explicitly declared as buttons, will fix.
