### ISSUE TITLE
[Feature Request] v-text-field behavior not consistent between solo and solo-inverted

### ISSUE THREAD

**Issue by sunsande** [vuetifyjs/vuetify#4700]
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.16
Browsers: FF, Chrome, Edge
OS: Win 10

### Steps to reproduce
[https://codepen.io/sunsande/pen/bjWKyO](https://codepen.io/sunsande/pen/bjWKyO)

### Expected Behavior
For both **solo** and **solo-inverted** (one should change manually **solo-inverted** to **solo** for the test):
If the text field is not focused: it looks a kind of "disabled" (gray)
If the text field is focused: it has the normal color

### Actual Behavior
**solo-inverted** works as expected
**solo** - there is no difference between focused and not focused (and for example in Angular Material there is )

**Comment by johnleider** [comment]
The current styles are intended. With that being said, I want to add the ability to set this dynamically, so will tag for re-review in v1.4

**Comment by johnleider** [comment]
Can you provide your reference in Angular Material? I'm not seeing anything.

**Comment by KaelWD** [comment]
[Related](https://discordapp.com/channels/340160225338195969/340215499398840331/583313597418176512)

**Comment by sunsande** [comment]
Sorry, it was some time ago and I cannot exactly remember ...
but the idea is that solo-inverted provides a visual hint when the element has focus (background-color and icon-color change). This is not the case by solo. By solo only the magnifying glass icon color changes.

If you examine the current Angular material controls in [the light theme](https://material.angularjs.org/1.1.19/demo/input) you'll see that on focus the input's label and the underline change color - pointing that the element has the focus (and even the hint text changed its color in the previous versions of Angular Material - now it changes only for fields with error)

HTH

**Comment by KaelWD** [comment]
There's no solo fields on that page, our default text field behaves the same. The solo style matches [the designs here.](https://material.io/archive/guidelines/components/text-fields.html#field-variations-figure-caption-0)

**Comment by sunsande** [comment]
Thanks for the link. For me it is still not quite clear as the example there does not show focus vs. no focus. But if you go to the search field on the page you pointed out (upper right corner) you'll see that there is a difference on focus vs. no focus.
It is strange if  one has a change on the dark theme and no change on the light theme - this is just IMHO. Maybe other people prefer it without change in the light theme.

**Comment by johnleider** [comment]
This is resolved as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
