### ISSUE TITLE
[Feature Request] Current Page Number on v-data-table action bar

### ISSUE THREAD

**Issue by prooli22** [vuetifyjs/vuetify#4701]
### Problem to solve
For now I had to display the current page number manually, by creating a new `<div>` inside the page-text slot of the `<v-data-table>`. It was not that hard, but moving the `<div>` with a position absolute is not a great solution I think.

### Proposed solution
Maybe you guys can add a boolean property to the `<v-data-table>` to show or hide the current page number. Like so
![image](https://user-images.githubusercontent.com/21690832/43136576-2f519860-8f17-11e8-99dd-437fa1b7fad7.png)

**Comment by nekosaur** [comment]
Implemented in 2.0 with `show-current-page` prop on `v-data-footer`. Accessed through `footer-props` on `v-data-table` and `v-data-iterator`.
