### ISSUE TITLE
Typo in Russian documentation 

### ISSUE THREAD

**Issue by ishpartko** [vuetifyjs/vuetify#4702]
https://vuetifyjs.com/ru/components/autocompletes#api

prop: "search-input"

how it's now:
"При использовании свойства автозаполнения. Используйте модификатор .sync, чтобы отл**а**вить пользовательский ввод из ввода автозаполнения"

how need to be:
"При использовании свойства автозаполнения. Используйте модификатор .sync, чтобы отл**о**вить пользовательский ввод из ввода автозаполнения"

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #548](https://github.com/vuetifyjs/vuetifyjs.com/issues/548) via [**ZenHub**](https://www.zenhub.com/)
