### ISSUE TITLE
Many v-switch components inside a v-navigation-drawer creates severe lag in Chrome

### ISSUE THREAD

**Issue by mjy90** [vuetifyjs/vuetify#4703]
### Versions and Environment
Vuetify: 1.0.11 & 1.1.8 (probably all versions, at least since 1.0.11)
Vue: 2.5.16
Browsers: **Google Chrome 67.0.3396.99**
OS: Ubuntu 18.04

### Works in:
Vuetify: 1.0.11 & 1.1.8
Vue: 2.5.16
Browser: **Mozilla Firefox for Linux, Google Chrome 67.0.3396.87 for Android**

### Steps to reproduce
In the linked CodePen, try scrolling month to month in the date picker. You should see significant lag. If you zoom the page out until the scrollbar in the navigation drawer disappears, the date picker will operate smoothly again, as expected.

### Expected Behavior
Page performance should be at least as good when switches have overflowed as it is when they're rendered.

### Actual Behavior
Performance suffers when switches overflow, and bringing them all onto the page (by zooming out or resizing the window) fixes the issue.

### Reproduction Link
https://codepen.io/anon/pen/bjREbd

### Additional Comments:
It appears that this phenomenon only occurs with **switches and checkboxes** (perhaps any type of selection controls) **in the navigation drawer**. When the switches are in the content section, or another control is used to y-overflow the navigation drawer, this doesn't happen. The v-navigation-drawer's "value" (expanded state) has no effect. The effect becomes noticeable around 30 switches on my computer (newer Xeon, lots of RAM).

The issue affects overall page performance. The date picker control is used in this example only because it's a good visual indicator of the lag created.

This appears to have started only recently (in the last month or two), during which point we haven't deployed any code to the affected website. This and my testing lead me to believe it was a recent release of Chrome (67.0.3396.87 or 99, perhaps).

The Chrome performance profiler records extended "Update Layer Tree" events during these lag spikes.

My apologies if this has already been addressed. I wasn't able to find it in the tracker.

Thanks!

**Comment by KaelWD** [comment]
Runs fine in chrome 67.0.3396.99 for windows: 
![image](https://user-images.githubusercontent.com/16421948/43181146-fca7d416-901e-11e8-80ba-99a3ab62ac5e.png)

There is a single slow frame when changing months, but that's just the picker's massive render function:
![image](https://user-images.githubusercontent.com/16421948/43181262-8d5ae8fe-901f-11e8-8d71-4610f455669c.png)

400 switches doesn't make it any worse:
![image](https://user-images.githubusercontent.com/16421948/43181328-dfd1913c-901f-11e8-8405-f466c73398dc.png)

---

Same story on android, 67.0.3396.87:
![image](https://user-images.githubusercontent.com/16421948/43181490-d070a646-9020-11e8-965c-1b6b86691df4.png)

**Comment by KaelWD** [comment]
And here's chrome 68.0.3440.84 on the worst laptop I could find, with a centrino T5600 and ubuntu 17.10:

![screenshot_20180805_211101](https://user-images.githubusercontent.com/16421948/43685309-fe72dbc8-98f3-11e8-9409-fd9b7055ce58.png)

I'll close this unless you can show actual profiling results, "significant lag" doesn't mean anything to me.

**Comment by mjy90** [comment]
This issue was specific to Linux + Chrome, and update 69.0.3497.81 of Chrome appears to have resolved it. Thanks for taking a look.
