### ISSUE TITLE
Data table with inline edit select list

### ISSUE THREAD

**Issue by stojankukrika** [vuetifyjs/vuetify#4706]
Hi,
Can you tell me, because I can't find in documentation, is there option in data table to have data table with inline edit select list? And if it is, can you link me some example how to make it?

I need it for this: using custom filters filter data in table, then click on specific column in specific row and select specific Employee from list or something like that.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/selects

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
