### ISSUE TITLE
[Feature Request] Control the timing expand/collapse of `v-list-group`

### ISSUE THREAD

**Issue by gyarasu** [vuetifyjs/vuetify#4707]
### What problem does this feature solve?

In the `v-list-group`, I sometime handle asynchronous http request.
For example, artists list. The structure as below.
The parents is genre(Rock, Jazz, etc.) and chidlren are MusicianXs.

Musician List which depends on parent(genre) can be got by ajax request, when the parent(genre) is clcked.
I want to expand the group after completing ajax request.

```
Rock
    - Musician A
    - Musician B
Jazz
    - Musician C
    - Musician D

```

### What is your proposed solution?
Add tow props to `v-list-group` as below.
- controlled (Boolean): It represents enable timing controll.
- expand (Boolean): It represents status of group list, expand or collapse.

If controlled is true, `v-list-group` component watch `expand`.
When `expand` is changed, the component invert the status of group list.

In the component created by developers, `expand` is passed to `v-list-group`, when the prop is updated by completing ajax.

**Comment by KaelWD** [comment]
This is already possible: https://codepen.io/anon/pen/PBxxob?editors=1010

https://github.com/vuetifyjs/vuetify/pull/4708#issuecomment-411687380
