### ISSUE TITLE
v-select within v-dialog 

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#471]
What is the best way to "contain" a `v-select` within a `v-dialog`? Currently things get a bit messy: https://codepen.io/anon/pen/QvgaYZ?editors=1111

Screenshot from actual application:
<img width="610" alt="screen shot 2017-05-01 at 11 41 56" src="https://cloud.githubusercontent.com/assets/808271/25576993/4f757c1c-2e63-11e7-9a67-0b3cff5e52c7.png">

**Comment by mfferreira** [comment]
@maartendraijer On your pen, I can see the select being cut off by the dialog boundaries, which is an obvious issue. But is is that the issue you're pointing out?

I'm asking because your screenshot seems to be showing something else.

**Comment by maartendraijer** [comment]
@mfferreira Yeah, that is the issue I'm pointing out. Currently the `v-select` gets cut off and a horizontal scrollbar appears. It's not very elegant, but I'm also not sure what the best solution is here.

**Comment by mfferreira** [comment]
@maartendraijer While this isn't fixed, you can define this in your styles:
```
.dialog
  overflow: initial
```

**Comment by johnleider** [comment]
You have updated your pen that produced this issue, please fix.

**Comment by maartendraijer** [comment]
Woops, I have updated the pen. (https://codepen.io/anon/pen/QvgaYZ?editors=1111)
