### ISSUE TITLE
v-select won't load the information when editing

### ISSUE THREAD

**Issue by gabrielafilete** [vuetifyjs/vuetify#4717]
**Versions and Environment**
Vuetify: 1.1.8
Vue: 2.5.13
Browsers: Google Chrome
OS: Windows 10

**Steps to reproduce**
Try to edit an item that have a v-select field. The v-select doesn't load the information.
That's only occure on production mode.

**Expected Behavior**
The v-select field should load the information from the item.

**Actual Behavior**
When the item is edited, the v-select fields came blank.

**Reproduction Link**
In my local project, they work perfectly as you can see here: https://i.imgur.com/H79LLqw.gifv
But their behaviour change if I do the same tests in \dist (production mode). As you can see here: https://i.imgur.com/TgAy1OR.gifv , when I edit, they don't load the information.

**Comment by jacekkarczmarczyk** [comment]
We are not able to do anything without reproduction or even a sample of your code. Please provide a valid reproduction (codepen or codesandbox) and we'll reopen the issue if it turns out to be a bug in Vuetify, not in your application
