### ISSUE TITLE
v-select ignores item-value

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#472]
It seems like the `v-select` component is ignoring its `item-value` property: https://codepen.io/anon/pen/Mmmqez?editors=1111

When you select an item, the `selected` property gets set to an `object` (`{ "text": "State 1", "id": 1 }`), instead of just the `id` (`1`).

Am I doing something wrong?

**Comment by johnleider** [comment]
item-value is to tell the select which property in your object is the items value, it doesn't change the output.

**Comment by maartendraijer** [comment]
@johnleider Aah. But what is the difference between `item-text` and `item-value`?

**Comment by johnleider** [comment]
Yea, your assumption is correct in that input-value should alter what is returned in the array, will fix.

**Comment by arapmelly** [comment]
simillar issue with the autocomplete

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
