### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by anoop-ananthan** [vuetifyjs/vuetify#4720]
Hi,
A link in the page which points to installing Vuetify in applications created using Vue-Cli 2  https://vuetifyjs.com/en/getting-started/quick-start doesnot work.

> Tip: If you don't want to overwrite your current vue-cli because you still need vue init from version 2, then try [this](https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#pulling-vue-cli2x-templates-legacy).

Please check the above line in the doc. It shows an invalid page.

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #549](https://github.com/vuetifyjs/vuetifyjs.com/issues/549) via [**ZenHub**](https://www.zenhub.com/)
