### ISSUE TITLE
[Feature Request] Add plus/minus quantity picker

### ISSUE THREAD

**Issue by ShailenNaidoo** [vuetifyjs/vuetify#4722]
### What problem does this feature solve?
This feature would allow users to add or remove the quantity of a given item
### What is your proposed solution?
Using a chip with two buttons on either side representing the plus and minus buttons. The quantity should be in the middle of the chip

**Comment by AlexSHoffman** [comment]
@ShailenNaidoo come on mate, you cannot create a custom component yourself? You need a Vuetify component for a few lines of code?

Here I made and example for you:
https://codepen.io/anon/pen/EpvOBW?editors=1010

**Comment by AlexSHoffman** [comment]
@ShailenNaidoo come on mate, do you really need a Vuetify component for a few lines of code? Can't you create a custom component yourself?

Here, I made and example for you:
https://codepen.io/anon/pen/EpvOBW?editors=1010

**Comment by ShailenNaidoo** [comment]
@AlexSHoffman Thanks man. I have no idea why i havent thought of it like that

**Comment by AlexSHoffman** [comment]
@ShailenNaidoo no problem! Glad I could help. If you have any question regarding Vuetify or need some help, you can ask on official Discord channel: https://discordapp.com/channels/340160225338195969/340215499398840331
