### ISSUE TITLE
[Bug Report] Race condition of v-input error state on IE11

### ISSUE THREAD

**Issue by neelance** [vuetifyjs/vuetify#4724]
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.16
Browsers: IE11
OS: Windows

### Steps to reproduce
The bug is a race condition, so it is not easy to reproduce. On our site it shows quite prominently, but I couldn't figure out how to make a small example show it prominently. Still, I can observe it on Windows in my VirtualBox. Steps to reproduce:
Open https://storage.googleapis.com/afilio-tmp/bug.html with Internet Explorer 11. Click the button. Observe a short flicker of a huge "Error" label. If it does not work on the first try, please refresh the page and try again.

### Expected Behavior
There should be no error state, since the value is set to a valid option.

### Actual Behavior
The error state of the v-label is shown for a short amount of time. On our site, it shows for about 200ms, so it is always clearly noticeable.

### Reproduction Link
https://storage.googleapis.com/afilio-tmp/bug.html

### Additional Comments
The race condition seems to be here:
https://github.com/vuetifyjs/vuetify/blob/3c4fefc119fedc186d32c901996944b7a004a1a8/src/mixins/validatable.js#L122-L127
Setting `this.hasInput = true` makes the error state show up and `this.$nextTick(this.validate)` removes it, but only after a delay.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
