### ISSUE TITLE
How to disable on load scale animation on Vuetify

### ISSUE THREAD

**Issue by samialmorshedi** [vuetifyjs/vuetify#4728]
I have installed Vuetify on my app using https://github.com/nuxt-community/create-nuxt-app generator.
The problem is there is a scale animation on first load of page. Something like that page is half scale and goes to 100% scale smoothly. I want to disable it!!

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

That definitely has nothing to do with us, ask the template author instead.
