### ISSUE TITLE
[Bug Report] Cannot specify width value with percentage in navigation-drawers

### ISSUE THREAD

**Issue by t-k-** [vuetifyjs/vuetify#4729]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Chromium 66.0.3359.181
**OS:** Ubuntu undefined

### Steps to reproduce
Use a percentage value in width field of navigation-drawers, e.g. width="50%".

### Expected Behavior
The drawer only expands to 50% of its container.

### Actual Behavior
The drawer expands fully.

### Reproduction Link
[https://codepen.io/ga6840/pen/pZWoBo](https://codepen.io/ga6840/pen/pZWoBo)

**Comment by johnleider** [comment]
The `v-navigation-drawer` uses width only for the purpose of calculating the content area padding. It only accepts values that can be used as `{n}px`. This is expected. I have plans to touch this in the future when I refactor the layout system and allow components to have any measurement for content calculations.
