### ISSUE TITLE
[Bug Report] Setting active tab after removing an tab from array causes selection offset

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#4735]
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.16
Browsers: Chrome v68
OS: Windows 10

### Steps to reproduce

Click on an X button to close a tab. (as noted below, closing the last tab functions properly)

### Expected Behavior

The tab should close and the last tab should be selected.

### Actual Behavior

The slider bar selects the correct tab However the active tab is the 1 index behind. When clicking the tab with the slider, it behaves as if it was the active tab (nothing happens).

### Reproduction Link

[https://codepen.io/MajesticPotatoe/pen/rrGoEG](https://codepen.io/MajesticPotatoe/pen/rrGoEG)

---

### Additional Comments:
This behavior does not happen when iterating through active tabs (like in docs) or if you remove the last tab. Have also tried doing async/await but everything seems to debug as if its functioning normally.

One thing to note that may need a new ticket is that if you remove all of the tabs from the array, the slider bar still remains.

**Comment by tony-thomas-git** [comment]
Possibly related. Closing all tabs leaves GUI artifacts.
https://codepen.io/tony-thomas-codepen/pen/vVOMpQ?editors=1010

**Comment by johnleider** [comment]
Fixed in f22d754
