### ISSUE TITLE
Problem with v-textarea when added a la carte

### ISSUE THREAD

**Issue by bensiu** [vuetifyjs/vuetify#4736]
First, in the documentation, there is no ability to add v-textarea a la carte so I try to guess based how v-text-field is added and come up with (ES6):

import VTextArea `from` 'vuetify/es5/components/VTextArea';

however when using v-textarea component I having weird error:
```
[HMR] bundle has 1 warnings
client.js?name=client&reload=true&timeout=30000&path=/__webpack_hmr:189 ./node_modules/vuetify/es5/components/VTextArea/VTextarea.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/tomaszdubiel/Sites/nuxt-school/node_modules/vuetify/es5/components/VTextArea/VTextarea.js
    Used by 1 module(s), i. e.
    /Users/tomaszdubiel/Sites/nuxt-school/node_modules/vuetify/es5/components/VTextArea/index.js
* /Users/tomaszdubiel/Sites/nuxt-school/node_modules/vuetify/es5/components/VTextarea/VTextarea.js
    Used by 1 module(s), i. e.
    /Users/tomaszdubiel/Sites/nuxt-school/node_modules/vuetify/es5/components/VTextField/index.js
 @ ./node_modules/vuetify/es5/components/VTextArea/VTextarea.js
 @ ./node_modules/vuetify/es5/components/VTextArea/index.js
 @ ./plugins/vuetify.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

When loading Vuetify fully works as expected.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/guides/a-la-carte

`VTextarea`

**Comment by bensiu** [comment]
With all due respect, there is nothing about VTextarea on this page, could you extend your answer
Ps. I am also using nuxt js so I do not have .babelrc file and creating a new one and flowing documentation part about transform-import create another error: "Cannot read property 'install' of undefined"

**Comment by KaelWD** [comment]
You're importing `VTextArea`, note the casing. 

We also have a nuxt template if you want to use transform-imports: https://github.com/vuetifyjs/nuxt/blob/master/template/nuxt.config.js

**Comment by bensiu** [comment]
Thank you - this documentation and example works as a charm.
