### ISSUE TITLE
Issue in maintaining state for multiple component data

### ISSUE THREAD

**Issue by gattushivakrishna** [vuetifyjs/vuetify#4737]
I am creating single page application using vue and vuetify, we  have multiple component with same sets of properties but data for those properties are different for each component and dynamically gets updated from backend. so when I switch to any component I should get the updated data. Is there any simple way to do achieve this?

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
