### ISSUE TITLE
[Bug Report] Navigation drawer won't disappear when the window is resized

### ISSUE THREAD

**Issue by Tretent** [vuetifyjs/vuetify#4739]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Chrome 68.0.3440.75
**OS:** Windows 10

### Steps to reproduce
1) open the browser at full size
2) resize the window in order to make the sandwich icon appear
3) open the drawer
4) while keeping the drawer opend, resize the window to full size

### Expected Behavior
The drawer should collapse since the icon is no longer visible

### Actual Behavior
The drawer remains opened and cannot be closed

### Reproduction Link
[https://codepen.io/tretent/pen/ejevOm](https://codepen.io/tretent/pen/ejevOm)

### Other comments
I think this behavior is due to the fact that the "drawer" variable (associated with the v-model directive) remains set to true and cannot be changed later.
Should I use v-resize to fix this manually?
Thanks

**Comment by KaelWD** [comment]
You have `disable-resize-watcher`, so of course it won't respond to resizing. Sounds like you want to watch `this.$vuetify.breakpoint` to get the behaviour you want.

**Comment by Tretent** [comment]
I've resolved in this way

`        
watch: {
            '$vuetify.breakpoint.smAndUp'() {
                if(this.$vuetify.breakpoint.smAndUp) {
                    this.drawer = false;
                }
            }
        }
`

Thanks for the tip
