### ISSUE TITLE
v-data-table is not updated on a new data

### ISSUE THREAD

**Issue by daniilc-magnumwm** [vuetifyjs/vuetify#4741]
### Versions and Environment
Vuetify: 0.16.9
Vue: 2.4.4
Browsers: Chrome  67.0.3396.99
OS: macOS High Seria

### Steps to reproduce
I have a object `portfoliosData` in a Vuex store. This object has a property `metrics`

      state: {
        portfoliosData: {
          performance: [],
          metrics: []
        },

When performing an action I mutate the property in the store and want to show the updates in a table.

     <div id="amsample">
      <div id="chartdiv"></div>
       <v-tabs-items  :touchless="true">
          <v-tabs-content :key="0" id="tab-1">
            <v-card flat>
              <v-card-text>
                Return Performance
                <v-data-table
                  :headers="headers"
                  :items="metrics"
                  :custom-sort="sortPercentage"
                  hide-actions
                  class="elevation-1"
                >
                  <template slot="items" scope="props">
                    <td>{{ props.item.name }}</td>
                    <td class="text-xs-right">{{ props.item.acRet }}</td>
                    <td class="text-xs-right">{{ props.item.anRet }}</td>
                    <td class="text-xs-right">{{ props.item.anVol }}</td>
                    <td class="text-xs-right">{{ props.item.maxDd }}</td>
                    <td class="text-xs-right">{{ props.item.sRatio }}</td>
                    <td class="text-xs-right">{{ props.item.inRatio }}</td>
                  </template>
                </v-data-table>
              </v-card-text>
            </v-card>
          </v-tabs-content>
        </v-tabs-items>
     </div>

In the component table observes the metrics variable.

    data() {
          return {
    
            headers: [
              {text: 'Measure', value: 'name', sortable: false},
              {text: 'Accumulative Return', value: 'acRet'},
              {text: 'Annual Return', value: 'anRet'},
              {text: 'Annual Volatility', value: 'anVol'},
              {text: 'Max Drawdown', value: 'maxDd'},
              {text: 'Sharpe Ratio', value: 'sRatio'},
              {text: 'Information Ratio', value: 'inRatio'},
            ],
            metrics: []
          }
        },

When I call an action in the component I get the updated `metrics` from the store

      calulateMetrics(event) {
        this.$store.dispatch('performeMetricsCalculation', {dataZoomStart:event.startDate, dataZoomEnd:event.endDate}).then(() => {
          this.metrics = this.$store.getters.getMetrics;
          console.log("Calculated metric", this.metrics)
        })
      },

During debugging I printed the `metrics` variable and I see that the data differers from the initial one. But the table doesn't updates. 

In `mutations` I use the following logic

    calculateMetrics({portfoliosData, period, status}) {
      let updatedMetrics = []

      for (let s in portfoliosData.performance) {
        if (portfoliosData.performance.hasOwnProperty(s)) {
          //console.log("Calculate metrics", period.startDateIdx, period.endDateIdx)
          let port = {...portfoliosData.performance[s]}

          updatedMetrics.push({
            name: port.name,
            maxDd: maxDrawdown(port.data, period.startDateIdx, period.endDateIdx),
            acRet: accumulativeReturn(port.data, period.startDateIdx, period.endDateIdx),
            anRet: annualReturn(port.data, period.startDateIdx, period.endDateIdx),
            anVol: annualVolatility(port.data, period.startDateIdx, period.endDateIdx),
            sRatio: sharpeRatio(port.data, period.startDateIdx, period.endDateIdx),
            inRatio: informationRatio(port.data, period.startDateIdx, period.endDateIdx)
          })

          if (!status.isUpdated) {
            portfoliosData.metrics = updatedMetrics
          } else {
            Vue.set(portfoliosData, 'metrics', updatedMetrics)
          }
        }
      }
    }

### Expected Behavior
When I get the data without performing an action there is no problem with updating the table. However when I want to update the table the new data doesn't render, although the `metrics` variable changes.

### Reproduction Link

I observe this issue only in this specific case. Also I tried to change `:items="metrics"` to `:items=$store.getters.getMetrics` but it didn't help me either.

**Comment by KaelWD** [comment]
Nobody can help you with that code dump, please create a **minimal** reproduction of the issue that we can actually run.

https://stackoverflow.com/help/mcve

Also this is most likely you using vue incorrectly: https://vuejs.org/v2/guide/list.html#Caveats

**Comment by daniilc-magnumwm** [comment]
@KaelWD 
The problem is quite weird. I couldn't reproduce the same problem using artificial data in a sandbox using the same component. 
However I'm sure there is no problems with API and server side as well
https://codesandbox.io/s/9jz98r2x3o

**Comment by daniilc-magnumwm** [comment]
It was the problem with markdown. 
Close the issue.

**Comment by baermathias** [comment]
@daniilc-magnumwm I have a similar issue. I can update `this.metrics` and verify it via `console.log()`, but `v-data-table` is not being updated. Could you explain how you solved this?

**Comment by nekosaur** [comment]
Please do not comment on closed issues. If you have a problem, create a new bug report with a reproduction. Thank you.
