### ISSUE TITLE
Vue Router support for v-toolbar-title

### ISSUE THREAD

**Issue by Trikolon** [vuetifyjs/vuetify#4743]
The majority of websites allow the user to click on the website title / logo to navigate to the homepage.
I tried to implement this with Vuetify but `<v-toolbar-title>` doesn't seem to support the `Vue Router` attribute `to="<path>"` as other components do.
I've noticed that the Vuetify website also implements this behavior, however, its only possible to click the logo.

[An example Codepen of this](https://codepen.io/pbz/pen/zLPLmY)
I've tried nesting another component in `v-toolbar-title` which can hold a `to` attribute but that causes the title to loose its CSS properties.

**Comment by M6stafa** [comment]
[https://router.vuejs.org/api/#tag](https://router.vuejs.org/api/#tag)
maybe this fix your issue.

**Comment by Trikolon** [comment]
Interesting, that works. I guess I still have to apply css props to enable the hand cursor though.
Would prefer native Vuetify support for this!

**Comment by johnleider** [comment]
You can do this by simply wrapping it in a `router-link`.

https://codepen.io/johnjleider/pen/KxBGop

**Comment by drew-royster** [comment]
Johns solution is awesome just add `toolbar-title` as the class for the router-link and the following css
```
.toolbar-title {
  color: inherit;
  text-decoration: inherit;
}
```

**Comment by torueck** [comment]
Without adding the class `toolbar-title` as suggested by @drew-royster I do not see the title / router-ling visualized. I don't know why this is the case in John's codepen example. However, when you add the mentioned css class, you could also put the router-link inside the `v-toolbar-title` which I find visually a bit more pleasing:
``` html      
<v-toolbar-title>
    <router-link to="/" class="toolbar-title">Toolbar</router-link>
</v-toolbar-title>
```

**Comment by shanemgrey** [comment]
It seems that the rendered html has the class toolbar__title with double underscores now.  Maybe this changed in some recent update. 

This does the trick for me.  
```
.toolbar__title {
  color: black;
  text-decoration: none;
}
```

**Comment by Thomasda089** [comment]
try to wrap it in a v-btn with text="true" then you dont have to fix thinks like color and text-decoration

```
<v-btn  to="/" text="true">
 <v-toolbar-title>Title
</v-toolbar-title></v-btn>
```

**Comment by tobias74** [comment]
As it has already been pointed out, wrapping it in a router-link will interfere with the css. There are workarounds of course, but the original issue remains:  "Vue Router support for v-toolbar-title"

**Comment by tobias74** [comment]
as it seems the classname has changed to

> .v-toolbar__title {
>   color: black;
>   text-decoration: none;
> }

I do have to apply the color and the text-decoration explicitly though. 'Inherit' will keep the blueish-link-color of the <router-link>

Maybe this could be more elegantly solved within the framework by offering a ":to" on the v-toolbar-title as suggested by the original poster?

**Comment by absemetov** [comment]
I use helpers <a href="/" class="text-decoration-none black--text">Title</a>

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
