### ISSUE TITLE
[Bug Report] v-slider crashes the browser tab when converting to percent

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#4746]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Chrome 68.0.3440.75, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
Drag either the right or the left thumb icon. If you drag the right one, the tab normally crashes once you hit the value 59.

### Expected Behavior
The slider should work with values which are being converted before consumption. I have just used a test variable inside the component for the reproduction, but originally the computed property was supposed to emit the value (which also doesn't work).

### Actual Behavior
The slider works fine with numbers which are not being converted via a computed property, but as soon as you multiply/divide the input and output, the slider crashes after dragging it for a bit. 

### Reproduction Link
[https://codepen.io/thomaskuhlmann/pen/PBOLqb](https://codepen.io/thomaskuhlmann/pen/PBOLqb)

### Other comments
A 'percentage' option for the slider would be nice - I guess I am not the only one who wants to use the slider to help filter a data table with percentage values.

**Comment by KaelWD** [comment]
That might be a bug, I'll have to look into it. You can just use the thumb-label slot instead though: https://codepen.io/anon/pen/yqppgd?editors=1010

**Comment by KaelWD** [comment]
Also the .lazy thing is vue: vuejs/vue#6914

**Comment by jacekkarczmarczyk** [comment]
This is related to float numbers precision, change 100 to 128 and it works fine

**Comment by KaelWD** [comment]
Ah, of course. The problem here is that sliders re-emit the rounded value for some reason, which throws the whole thing into a loop.
