### ISSUE TITLE
zero values are not shown in an autocomplete selection

### ISSUE THREAD

**Issue by sholzmayer** [vuetifyjs/vuetify#4749]
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.16
Browsers: Chrome 67.0.3396.99
OS: OSX

### Steps to reproduce
```
    <v-autocomplete
      :items="[0, 1, 2, 3]"
    />
```
### Expected Behavior
All of those values are shown in the select-field... 

### Actual Behavior
For the 0 value is an empty line shown

![image](https://user-images.githubusercontent.com/20296626/43395109-4014e5ae-93fd-11e8-8a3d-3e55dc762b8b.png)

**Comment by KaelWD** [comment]
Unable to reproduce: https://codepen.io/anon/pen/RBQXmx?editors=1000

**Comment by jacekkarczmarczyk** [comment]
It shows on the list, but if you select '0' it doesn't show in the input
