### ISSUE TITLE
[Feature Request] Keep Selected items in v-select to 1 lines

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#4750]
### Problem to solve
In limited spaced forms/areas a select field grows tall if too many items are selected. 

### Proposed solution
Add prop to limit height of v-select__selections div, and add chip at end of list to inform user that more options are currently selected. Per Kael: (foo), (bar), (baz), (6 more...). Codepen for example: https://codepen.io/blalan/pen/vapZRK
Steps to reproduce: select lots of options to force more than one line of chips, toggle css.

**Comment by praveenpuglia** [comment]
Thanks to @johnleider, you can do something like this
https://codepen.io/johnjleider/pen/gjBgbx
