### ISSUE TITLE
[Bug Report] Navigation Drawer incorrectly handles nested paths and shows multiple list items as active

### ISSUE THREAD

**Issue by xlm** [vuetifyjs/vuetify#4757]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.12
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
From the navigation drawer:
1. Click on 'Home'. 'Home' is now active (correct)
2. Click on 'About us'. 'Home' and 'About us' are active (incorrect). Should only have 'About us' as active.
3. Click on 'About us About us'. 'Home', 'About us' and 'About us About us' are active (incorrect). Should only have 'About us About us' as active.
4. Click on 'Contact'. 'Home' and 'Contact' are active (incorrect). Should only have 'Contact' as active.

### Expected Behavior
Navigation drawer should mark only one list item as active. This should be the one that matches the path exactly/closest.

### Actual Behavior
Navigation drawer marks any list item as active as long as it's part of the current route's path i.e. 'Home' which is `/` will always be highlighted even when we the route is `/about-us` or `/contact`.

### Reproduction Link
[https://codepen.io/anon/pen/QBQLNw](https://codepen.io/anon/pen/QBQLNw)

**Comment by jacekkarczmarczyk** [comment]
use `exact` prop https://codepen.io/anon/pen/GBQKML

**Comment by xlm** [comment]
Thanks @jacekkarczmarczyk for the prompt help! FYI this prop is missing from the docs on navigation drawer and links.
