### ISSUE TITLE
[Enhancement] Allow disable transition for VDataTable expand row

### ISSUE THREAD

**Issue by pwang2** [vuetifyjs/vuetify#4764]
### What problem does this feature solve?

As requested here https://github.com/vuetifyjs/vuetify/issues/2890,  expand all  is quite helpful to implement some treeview rows.   

The [current transition](https://github.com/vuetifyjs/vuetify/blob/cc28151673b5efae8116dee5d461eef7fca14888/src/components/VDataTable/mixins/body.js#L23) of expand rows makes workaround solution like https://codepen.io/anon/pen/aEJeVo perform very slow.  I saw 300ms Recalculate Style in performance profiler. 
![image](https://user-images.githubusercontent.com/1592014/43472027-0aa76738-94b2-11e8-8cc7-5868550fcfb5.png)

### What is your proposed solution?

Expose the transition as an props to opt in by user.

**Comment by pwang2** [comment]
@KaelWD , Thanks for replying.  Could you help clarify what do you mean by use css for this?

In my case  for a nested table with 200 rows(maximum 3 levels, 20 columns), use dropdown select to re-grouping the rows takes 500ms to display the transitions. 
![image](https://user-images.githubusercontent.com/1592014/43535439-a603b3b2-957f-11e8-89ec-b6e1f7754199.png)

in the code here,  https://github.com/vuetifyjs/vuetify/blob/dev/src/components/transitions/expand-transition.js#L16.  **scrollHeight access will reflow the whole DOM again and again**.   This is a huge performance issue even in a not so extreme scenario.

**Comment by pwang2** [comment]
To be clear,  single row expand will not be an issue.  The bottleneck comes with the `expandAll` workaround code here https://codepen.io/anon/pen/aEJeVo.

**Comment by pwang2** [comment]
More information here FYI.

  Besides vuetify's transition, vue's global update lifecyle method also adds a unconditional getTransitionInfo hard query for all browser better than IE9 which aggravated the situation here.   In short, we can not overburden it by adding transition too much element here. 

![image](https://user-images.githubusercontent.com/1592014/43543424-8f9ecc40-9595-11e8-8fa7-bfc85950c584.png)

**Comment by husayt** [comment]
This is affecting us too, is there any workaround for time being?

**Comment by KaelWD** [comment]
New codepens with more rows:
0.17: https://codepen.io/anon/pen/GwLMEX?editors=1010
1.3: https://codepen.io/anon/pen/VVNMzX?editors=1010

Seems the new transition is even slower, because it has to reflow the page twice for each element. I wonder if we could batch the reflows with requestAnimationFrame somehow so it only has to be done once for the whole page.

**Comment by pwang2** [comment]
@jacekkarczmarczyk,  sorry for the so late response.  I quick checked the code and it seems the performance issue is still there.   
@KaelWD , please let me know if you need any help from my side. I finally have some change to working on a related project again.

**Comment by amanbolat** [comment]
I have same problem. My application have VTable with 100 rows. Even expanding a single row will create some lag.

**Comment by AakifMushtaq** [comment]
@amanbolat This is what I did to get rid of the transition because we didn't really need that effect. Not sure if this is the right solution but it worked for me. 
`.v-datatable__expand-content {
        transition: unset !important;
}`

**Comment by jacekkarczmarczyk** [comment]
v-data-table doesn't have transition on expanded row in 2.x, see https://github.com/vuetifyjs/vuetify/issues/8197
