### ISSUE TITLE
[Enhancement] Accessible icon button

### ISSUE THREAD

**Issue by randomstuff** [vuetifyjs/vuetify#4770]
### Versions and Environment

Vuetify: 1.1.9
Vue: -
Browsers: Firefox
OS: Linux

### Steps to reproduce

1. Go to https://vuetifyjs.com/en/components/icons#example-clickable
2. Inspect the clickable button

### Actual Behavior

    <i aria-hidden="true" class="v-icon v-icon--link 
          mdi 
          mdi-chevron-right" style="font-size: 36px;"></i>

This icon serves as a button it should not have `aria-hidden="true"`.

### Expected Behavior

The icon should probably have `role="button"`.

A workaround is to explicitly override them:

    <v-icon aria-hidden="false" role="button" @click="foo">add</v-icon>

### Reproduction Link

https://codepen.io/anon/pen/oMqxXe

### Additional Comments:

Additionally, the documentation should probably recommend setting `aria-label` and/or `title`:

    <v-icon "@click="foo" aria-label="Add">add</v-icon>

**Comment by jacekkarczmarczyk** [comment]
fixed in #7198
