### ISSUE TITLE
Cannot use separate components in nuxt.js project

### ISSUE THREAD

**Issue by p1pchenk0** [vuetifyjs/vuetify#4772]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.13
Browsers: Chrome
OS: Windows

### Steps to reproduce
1. create empty nuxt.js project using [guide](https://nuxtjs.org/guide/installation)
2. follow steps from [official guides](https://vuetifyjs.com/en/guides/a-la-carte)
3. inside "plugins" folder add file `vuetify.js` and paste there code:

```
import Vue from 'vue';
import Vuetify from 'vuetify/es5/components/Vuetify';
import VApp from 'vuetify/es5/components/VApp';
import VBtn from 'vuetify/es5/components/VBtn';
import VFooter from 'vuetify/es5/components/VFooter';
import VGrid from 'vuetify/es5/components/VGrid';

Vue.use(Vuetify, {
  components: {
    VApp,
    VBtn,
    VFooter,
    VGrid
  }
});
```
4. connect plugin in `nuxt.config.js` file:
```
plugins: [
    '~/plugins/vuetify'
]
```
5. in `layouts` folder add some basic html to `default.vue` file:
```
<div class="app">
    <v-app>
        <v-btn flat>click me</v-btn>
        <v-footer></v-footer>
    </v-app>
</div>
```
6. start app by using `npm run dev` command
### Expected Behavior
After building and opening `localhost:3000` app should show html
### Actual Behavior
Error in terminal

```
{ D:\projects\nuxt\node_modules\vuetify\src\stylus\components\_app.styl:1
(function (exports, require, module, __filename, __dirname) { @import '../bootstrap'
                                                              ^
SyntaxError: Invalid or unexpected token
```

### Additional Comments:
Looks like it complains about `@import` statement inside `.styl` file, but `stylus` and `stylus-loader` are installed.
Tried to add rule
```
{
      test: /\.styl$/,
      loader: ['style-loader', 'css-loader', 'stylus-loader']
}
```
to `nuxt.config.js` file, but did not help

**Comment by johnleider** [comment]
Looks like you are missing some things, have you checked out our boilerplate project with nuxt? Specifically the parts about a-la-carte https://github.com/vuetifyjs/nuxt/blob/master/template/nuxt.config.js

**Comment by p1pchenk0** [comment]
@johnleider thank you! did not see that!
All worked because of
```
if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]
      }
```

**Comment by johnleider** [comment]
Awesome! If you consider this resolved, please close the issue, ty.
