### ISSUE TITLE
[Bug Report] v-tabs__items class preventing scrolling tab contents

### ISSUE THREAD

**Issue by jlynde** [vuetifyjs/vuetify#4781]
### Versions and Environment
**Vuetify:** 1.1.9
**Vue:** 2.5.17
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
See reproduction example linked above. 

### Expected Behavior
Wanted to be able to make contents of tabs scrollable

### Actual Behavior
Unable to accomplish what I wanted to do because v-tabs__items height is larger than expected.

### Reproduction Link
[https://codesandbox.io/s/ojp729pjj5](https://codesandbox.io/s/ojp729pjj5)

**Comment by KaelWD** [comment]
Same as https://github.com/vuetifyjs/vuetify/issues/4782#issuecomment-410426294, your css is incorrect.
