### ISSUE TITLE
[Bug Report] V-tab achor hash doesn't update url

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#4784]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.16
Browsers: Chrome 68.0.3440.75
OS: Ubuntu 18.04

### Steps to reproduce
Use an href="#something" with the v-tab

### Expected Behavior
It changes the tab as well as updates the url with the new hash

### Actual Behavior
It changes the tab but does not update the url, nor does it load the correct tab if you manually type in the hash in the url.

### Reproduction Link
https://codepen.io/amritk/pen/djeqBX

---
### Additional Comments:
Can't really see the url changing in the codepen, not sure how to showcase that, but if you copy this code locally you should see that it doesn't change the url.

**Comment by amritk** [comment]
I tracked it down to this line in VTab.js line 75
```
if (this.href && this.href.indexOf('#') > -1) e.preventDefault();
```
If I comment it out, it works perfectly. Why is it preventing default on a hash fragment url?

**Comment by amritk** [comment]
If it was to allow people to use a '#' by itself, can we not instead do 
```
if (this.href && this.href === '#') e.preventDefault();
```
So this would work correctly:
```
<tab href="#teams">
```

**Comment by johnleider** [comment]
Closed via #5124

**Comment by johnleider** [comment]
I'm reverting this because it causes a bad user experience when using hrefs. After releasing we realized what its true purpose was.

**Comment by amritk** [comment]
Maybe we should update the docs to tell users to use router-link instead of an anchor for hash fragment tab routing?
