### ISSUE TITLE
v-autocomplete options list opens when it probably shouldn't

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#4786]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.17

### Steps to reproduce
1. https://codepen.io/andrewharvey/pen/LBmwMV
2. Choose a value for A
3. Choose a value for B
4. Clear A

Observe the autocomplete list for B opens, I don't think it should.

![vuetify_autocomplete](https://user-images.githubusercontent.com/117278/43629841-cac86418-9741-11e8-90dc-9e5bbfe6ffa1.gif)

**Comment by KaelWD** [comment]
Duplicate of #4663
