### ISSUE TITLE
V-Select Label Hiding if its placed inside V-List

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#4787]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.16
Browsers: Chrome 68.0.3440.84
OS: Ubuntu 18.04

### Previously worked in:
Vuetify: 1.0.17
Vue: 2.5.16

### Steps to reproduce

Take a look the following images, this image is coming from vuetify version 1.0.17
![17](https://user-images.githubusercontent.com/20434351/43635040-2309d3fa-9738-11e8-9e1c-1cc5260ece3f.png)

and the image below is coming from vuetify version 1.1.19
![19](https://user-images.githubusercontent.com/20434351/43635068-36269752-9738-11e8-902e-292112cc0473.png)

To reproduce just create a v-select inside v-list

### Expected Behavior

The label of v-select should be like the one in version 1.0.17, it is not hiding.

### Actual Behavior

The label of v-select is hiding.

### Reproduction Link

https://codepen.io/jefrydco/pen/MBXwXW

---

**Comment by KaelWD** [comment]
Told you it needed to be padding @johnleider

**Comment by johnleider** [comment]
This has more to do with `v-list-tile` having a set height for MD spec. The previous _working_ version on 1.0.17 looks terrible anyways.
