### ISSUE TITLE
Screen swipe in tabs acts wrong in RTL mode

### ISSUE THREAD

**Issue by MehrdadKhanzadeh** [vuetifyjs/vuetify#4788]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.16
Browsers: Chrome
OS: Windows 10

### Steps to reproduce

When you swipe screen in tabs in touchscreen devices, It doesn't matter if It's RTL or not. If you swipe left, You should go to the right tab and vise versa. But if You set RTL property to true, It acts in opposite.

### Expected Behavior

Swiping to left should make the current tab switch to the right tab.

### Actual Behavior

In RTL mode, It switches the tab to the left tab.

### Reproduction Link

https://codepen.io/MehrdadKhanzadeh/pen/ajKOKm
You just have to run It on a touchscreen.

### Additional Comments
I have to add that I noticed that the animation on the tab switch is reverse, too. I guess that's the main reason for swipe to act in opposite.

**Comment by KaelWD** [comment]
rtl is currently only supported for forms, everything else is still wip: #262

**Comment by MehrdadKhanzadeh** [comment]
@KaelWD It's okay if You don't support something, but if You do something I guess It shouldn't be wrong. What do You mean by "only supported for forms"? If It's so, It shouldn't change the default behavior of something and makes it wrong! It works fine on many things and I'm happy with It and without It I have to add a lot of style in a hard way but It makes tab switch acts wrong. This behavior of RTL in tabs makes me think that people who implement It thought in RTL the tabs act in opposite but They don't. So what I have to do? Only because of this bug in RTL I have to remove RTL property and do everything manually? Or what?

**Comment by KaelWD** [comment]
The RTL option was introduced in [1.1](https://github.com/vuetifyjs/vuetify/releases/tag/v1.1.0), but only really works for form elements (v-text-field, v-radio, v-select etc.). This tabs thing may be regarded as a bug, but there is no point having a separate issue for it when most components still don't have rtl support. This will be fixed eventually, we're still exploring possible options to make it happen. I don't think there's currently any workarounds available.
