### ISSUE TITLE
[Bug Report] v-select error when using from render function

### ISSUE THREAD

**Issue by NothingWeAre** [vuetifyjs/vuetify#4789]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.17
Browsers: Chrome, Firefox, others not tested
OS: Windows 10

### Steps to reproduce

use v-select inside render function

### Expected Behavior

v-select works as expected

### Actual Behavior

 browser returns error:
`Error in render: "TypeError: Cannot set property 'multiple' of undefined"`

### Reproduction Link

JSFiddle
[v-select inside render function](https://jsfiddle.net/NothingWeAre/2dpjrb7u/4/)
[v-select inside template with same parameters](https://jsfiddle.net/NothingWeAre/k36pyg9m/)

---

**Comment by KaelWD** [comment]
`attrs` not `props`

https://vuejs.org/v2/guide/render-function.html#Template-Compilation

**Comment by NothingWeAre** [comment]
From your link
```
// Normal HTML attributes
  attrs: {
    id: 'foo'
  },
  // Component props
  props: {
    myProp: 'bar'
  },
  // DOM properties
  domProps: {
    innerHTML: 'baz'
  },
```
Is there documentation on which properties are `props` and which are `attrs` ?

By the way `v-autocomplete` accepts `props`

**Comment by KaelWD** [comment]
I guess it's just the different way props are handled by functional components, you should be able to put everything in attrs. I was linking more to the compiler example on that page, if you put your template in it renders it with attrs. 
![image](https://user-images.githubusercontent.com/16421948/43655555-5bfbd104-9792-11e8-814f-1543e1d154a3.png)
