### ISSUE TITLE
v-list click colides with avatar click

### ISSUE THREAD

**Issue by danielschmitz** [vuetifyjs/vuetify#4793]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.17
Browsers: Chrome 
OS: Windows 10

### Steps to reproduce
- create a v-list-tile with @click
- create a v-list-tile-action with v-btn @click
- click on v-btn

### Expected Behavior
- Only v-btn click trigger

### Actual Behavior
- Both v-btn and v-list-tile triggers a click

### Reproduction Link
https://codepen.io/danielschmitz/pen/NBzMRb?&editors=101

### Additional Comments:

From [documentation](https://vuetifyjs.com/en/components/lists#example-icon-two-lines-and-action) example, we have:

```js
<v-list-tile
              v-for="item in items"
              :key="item.title"
              avatar
              @click="onListTileItemClick()" <<<<<<<<<<<<<<<<<<<<<
            >
              <v-list-tile-avatar>
                <v-icon :class="[item.iconClass]">{{ item.icon }}</v-icon>
              </v-list-tile-avatar>
  
              <v-list-tile-content>
                <v-list-tile-title>{{ item.title }}</v-list-tile-title>
                <v-list-tile-sub-title>{{ item.subtitle }}</v-list-tile-sub-title>
              </v-list-tile-content>
  
              <v-list-tile-action>
                <v-btn icon ripple @click="onButtonInfoItemClick()"> <<<<<<<<<<<<<<<
                  <v-icon color="grey lighten-1">info</v-icon>
                </v-btn>
              </v-list-tile-action>
            </v-list-tile>
```

![002](https://user-images.githubusercontent.com/1509692/43669834-8cbbbbdc-975c-11e8-9c71-d9898f859910.gif)

**Comment by KaelWD** [comment]
`@click.stop="...`

https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
