### ISSUE TITLE
RTL is not working in Electron

### ISSUE THREAD

**Issue by MehrdadKhanzadeh** [vuetifyjs/vuetify#4798]
### Versions and Environment
Vuetify: 1.1.9
Vue: 2.5.16
OS: Windows 10

### Steps to reproduce

Just set RTL to true in Electron template.

### Expected Behavior

The page should look RTL.

### Actual Behavior

It looks LTR.

### Reproduction Link

As I'ts an Electron bug I can't provide a link. Any Electron application with RTL set to true will do the work!

---

### Additional Comments:
I don't know, maybe It's a feature request. I don't know if It's supposed to work this way or not!

**Comment by johnleider** [comment]
Without a reproduction it is very hard for us to perform any actionable changes. My suggestion would be to coordinate with community leaders in our RTL channel for further debugging and discussion.

If you are able to provide a reproduction I will gladly re-open this.

https://community.vuetifyjs.com
