### ISSUE TITLE
vuetify@1.1.9 v-tabs-slider problem

### ISSUE THREAD

**Issue by annymosse** [vuetifyjs/vuetify#4800]
Hello , i have a bug with **v-tabs-slider** compenet , i made that short example to explain everythings
[https://codepen.io/anon/pen/MBBmaP?editors=1011](https://codepen.io/anon/pen/MBBmaP?editors=1011)
just switch cpanel value between (true and false) to understand the problem

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1978

Use `lazy` prop on `v-dialog`
