### ISSUE TITLE
[Feature Request] V-slider a11y:  readonly is always set to true and aria-readonly is present which isn't allowed by specs

### ISSUE THREAD

**Issue by lol2x** [vuetifyjs/vuetify#4806]
### Problem to solve
https://codepen.io/lol2x/pen/oMMmdx
Only the second slider have readonly prop set to true, however the HTML generated is always with readonly="readonly". 
What is more aria-readonly attribute should only be used for elements that are not allowed to have a readonly attribute in HTML5 - according to spec https://www.w3.org/TR/html-aria/

### Proposed solution
The presence of HTML readonly prop should be based on readonly prop from Vuetify
`readonly: String(this.readonly)`
and https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSlider/VSlider.js#L253 should be removed
I can create PR if you want this changes.

**Comment by KaelWD** [comment]
The first one has `readonly` because the input isn't actually used for anything, and I think the `aria-readonly="false"` was supposed to counteract that. Does this cause actual problems with screenreaders, or is it just a "muh spec" thing?

**Comment by lol2x** [comment]
Screen reader I'am using is smart enough to deal with that 
However chrome dev tools audits don't like it
![Screenshot google chrome dev tools]( https://i.imgur.com/PC1lWoF.png)

**Comment by KaelWD** [comment]
So it's a a "muh spec" thing. If this doesn't actually cause real problems then we'll leave it as it is, your suggested change would result in incorrect behaviour.

**Comment by lol2x** [comment]
Okay I can agree with it. Maybe to increase a11y in sliders you can rethink label prop. Currently label is shown up as text before(or after if inverted) the slider. And aria-label is set as the same as label. But there is no way to set just aria label (I don't want my sliders to have visible label, but I want them to be accessible)

**Comment by lol2x** [comment]
Yup, also adding 
```
aria-valuemin
aria-valuemax
aria-valuenow
aria-valuetext
```
could be then considered
