### ISSUE TITLE
[Feature Request] add `overlay-class` to v-dialog

### ISSUE THREAD

**Issue by tommie** [vuetifyjs/vuetify#4807]
### What problem does this feature solve?

I'd like to use a dialog as an overlay toolbox. I could use a `.v-dialog__content` style rule to change `align-items` and `justify-content` to both be `start`. However, my component evolved, and I now have two dialogs. Only one of which should be the special toolbox.

Because `content-class` is not applied to the detached overlay parent (but to its child), I cannot make a selector that only selects one of the dialogs. In my case, for `align-items`, I can use `align-self` on the child, but `justify-content` doesn't (yet) have a working corresponding `justify-self` (in my Chromium 67).

### What is your proposed solution?

It would be nice to have something similar to `content-class` added to the overlay parent so position could be customized.

Maybe an `overlay-class` property.

**Comment by johnleider** [comment]
This is still something I'd like to implement but unfortunately did not make the cut for v2.0. As a workaround for now, you can follow the same pattern that we did in creating the `v-bottom-sheet` component: https://github.com/vuetifyjs/vuetify/tree/next/packages/vuetify/src/components/VBottomSheet

**Comment by volarname** [comment]
how about this in 2.x.x ?
