### ISSUE TITLE
[Bug Report] Navigation drawers / Nested lists

### ISSUE THREAD

**Issue by ogio** [vuetifyjs/vuetify#4808]
### Versions and Environment
**Vuetify:** 1.1.9
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.84
**OS:** Mac OS 10.13.6

### Steps to reproduce
https://vuetifyjs.com/en/components/navigation-drawers

On your demo page navigation is not working properly. It is having some lag/jump after expanding and collapsing items. 

Example:
- expand users
- expand admin
- collapse users
- expand users

### Expected Behavior
Collapse and expand should work smooth.

### Actual Behavior
It is problematic after collapsing expanded subgroup. 

### Reproduction Link
[https://github.com/risticnikola/vuetifyTest](https://github.com/risticnikola/vuetifyTest)

### Other comments
Please is there easy way to fix this? Thank you in advance

**Comment by garshyn** [comment]
In 1.2.0 version, some nested items don't work on the demo site. Tested in Chrome
https://vuetifyjs.com/en/components/navigation-drawers#example-nested

**Comment by XMoose25X** [comment]
Still experiencing issues with this.

Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Chrome 68.0.3440.106
OS: Windows 10 Version 1709 (Build 16299.431)

Steps to Reproduce:
1. Navigate to https://vuetifyjs.com/en/components/navigation-drawers#example-nested
2. Click to expand Users Tile
3. Click to expand Admin Tile
4. Click to collapse Users Tile
5. Click to expand Users Tile
6. Notice that Admin group expands quickly before snapping back to collapsed.
