### ISSUE TITLE
stylus variable invalid

### ISSUE THREAD

**Issue by q-jason** [vuetifyjs/vuetify#4809]
Sorry, my English is not very good。
I use the transform-imports，but stylus variable invalid。code↓↓
![tim 20180806195742](https://user-images.githubusercontent.com/28495915/43715432-1557d3ce-99b3-11e8-88c2-39ea3b9d4c2a.png)
![123123123](https://user-images.githubusercontent.com/28495915/43715429-146656fc-99b3-11e8-9172-66d0273f0c9e.png)
![5435435435](https://user-images.githubusercontent.com/28495915/43715433-15c17176-99b3-11e8-98dc-b93c50d4dec0.png)

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-loader#a-la-carte

**Comment by miladmeidanshahi** [comment]
Hi @KaelWD,

i have same issue, i can't custom variables in a la carte.
i have searched and i have read many codes, but i didn't found how to custom variables.
i'm using `vue-cli-plugin-vuetify` and i can't load `vuetify-loader` can you send me an example code to do that ?
