### ISSUE TITLE
[Feature Request] Turkish letters capital 'İ' and lowercase 'ı' don't work correctly within search and autocomplete

### ISSUE THREAD

**Issue by safakadir** [vuetifyjs/vuetify#4811]
In Turkish language capital of 'i' is 'İ', not 'I'. And lowercase of 'I' is 'ı', not 'i'. These letters may cause issues, even though UTF-8 had them.

For autocomplete component, or for search model of components like data table in vuetify don't work correctly with these letters. Other local letters like 'ş', 'ğ', 'ü' etc. are ok; but capital 'İ' and lowercase 'ı' are not matching with the given text while filtering.

For example, items are ['İstanbul', 'izmir', 'ılgaz', 'Irak']
(beware of capital and non-capital letters)

Input: "i"
Matching records: "izmir", "Irak"
Expected: "izmir", "İstanbul", "Irak"*
(*English letter 'I' can still match with 'i' to prevent ambiguity)

Input: "ı"
Matching records: "ılgaz"
Expected: "ılgaz", "Irak"

(Note: As I understand, the filtering or search is done by converting items to lowercase)

Edit: I edited the post again and again to achieve most accurate examples. I hope it's final now, sorry...

**Comment by jacekkarczmarczyk** [comment]
@safakadir are you able to check the [PR](https://github.com/vuetifyjs/vuetify/pull/6333)?

In the browser with Turkish locale it should produce the following results:

"İ" - 'İstanbul', 'izmir'
"i" - 'İstanbul', 'izmir'
"ı" - 'ılgaz', 'Irak'
"I" - 'ılgaz', 'Irak'

It's not exactly what you requested, but maybe it's better than now
