### ISSUE TITLE
[Feature Request] Overwrite the touch/v-touch behavior of VCarousel component

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#4813]
### Problem to solve
Currently the swipe left, right on mobile device for the  VCarousel component will fire the next/previous slides. I want to be able to overwrite these actions or disable them completely. I tried the component directive change as:
```
v-touch="{
   left: () => doMyOwnSwipe(),
  right: () => doMyOwnSwipe()
        }"
```
However this did not cancel the original swipe behaviour

### Proposed solution
Ideally I like the new v-touch left and right functions to stop propagating and only executes the function that I call. Or give me the option to stop propagation like we have for the click event with the use of `@click:prevent:stop="onClick"

**Comment by johnleider** [comment]
This coincides with the abstraction of `v-item-group` and `v-slide` (still WIP/name subject to change).
