### ISSUE TITLE
Change transition behaviour in v-tabs

### ISSUE THREAD

**Issue by Gab0o777** [vuetifyjs/vuetify#4814]
### Feature request

It would be nice if the animation between tabs in the v-tabs component could be either chosen, changed, or removed if wanted.

### What problem does this feature solve?

There are cases where you may have a LOT of content inside a given tab, changing between tabs in those cases can make the animation look not very smooth and kind of slow.

For example using a complex component(like Monaco [https://microsoft.github.io/monaco-editor/]) or a few images in each tab could make this happen.

### What is your proposed solution?

Giving the option to the user:

```html
<v-tabs v-model="tabs" color="teal darken-1" :transition="fade">
```
Simplest solution removing the animation:

```html
<v-tabs v-model="tabs" color="teal darken-1" no-animation>
```

**Comment by jacekkarczmarczyk** [comment]
Use `transition` and `reverse-transition` props
https://codepen.io/anon/pen/EpdVxY?editors=1000

**Comment by jsmedmar** [comment]
Would be nice if this could be done at the `<v-tabs> ` level
