### ISSUE TITLE
v-select: readonly allows to switch, if outline styles are applied

### ISSUE THREAD

**Issue by aroshalva** [vuetifyjs/vuetify#4815]
### Steps to reproduce

switch between select options...

### Actual Behavior:

if v-select is _outline_,  _readonly_ does not work as it suppose to: it still allows to switch between options, if outline is false it does not allow to change (as it suppose to, so outline styles is problem).

### Reproduction Link

https://codepen.io/martlaboloa/pen/JBmoge
---

**Comment by KaelWD** [comment]
wtf

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VTextField/VTextField.js#L413

**Comment by aroshalva** [comment]
@johnleider to clerify: by posting that link(on specified line with comment on it) you showed where bug is or you're saying that its working as it suppose to, like some edge cases need mouse events to be alive ?

**Comment by johnleider** [comment]
Just a reminder for whoever works on this that it can be solved by adding a check there.

**Comment by jacekkarczmarczyk** [comment]
Or maybe `return this.readonly ? activator : [this.genMenu(activator)]` in https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/VSelect.js#L383

**Comment by KaelWD** [comment]
or https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/VSelect.js#L179

**Comment by aroshalva** [comment]
Hello again, too lazy to open new issue sorry, its related to this.

So, if I'm not mistaken now readonly state makes value blurry, same as in disabled state, readonly must not be de-emphasized. (you can look at same sandbox)

**Comment by KaelWD** [comment]
for. sucks. sake

**Comment by KaelWD** [comment]
Looks pretty minor, but I'm too cooked to fix it rn, maybe 1.1.12. 9442a21a442acd4abdf683f3c5d5d1f2bf83b01f

**Comment by KaelWD** [comment]
Should still open a new issue though, this will be forgotten as soon as I close the tab.
