### ISSUE TITLE
Reasoning behind `maximum-scale=1, user-scalable=no`

### ISSUE THREAD

**Issue by adelura** [vuetifyjs/vuetify#4816]
Not sure if it's a question or an issue. But it's related to documentation, so I'm going to report it here.

In the readme of this repository I noticed that html code includes following code:

``` html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
```

The part which bother me is `maximum-scale=1, user-scalable=no`.

1. Is there any particular reason why it's included?
2. Is this obligatory to include that meta value when I want to use vuetify?

**Comment by KaelWD** [comment]
> Is there any particular reason why it's included?

It makes the page behave like a native app

> Is this obligatory to include that meta value when I want to use vuetify?

No

> it's related to documentation

Documentation issues should be reported on https://github.com/vuetifyjs/vuetifyjs.com

> Not sure if it's a question or an issue

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
