### ISSUE TITLE
Expansion panels

### ISSUE THREAD

**Issue by santiGoncalves** [vuetifyjs/vuetify#4818]
Hi i have a expansion panel with 4 panels, it has expand property because i need the first to be open by default, but then when i click another panel i need it to behave like it doesnt have the expand property.

How can i achieve this behaviour?

thanks

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
