### ISSUE TITLE
[Feature Request] Validation warnings

### ISSUE THREAD

**Issue by deka** [vuetifyjs/vuetify#4819]
### Problem to solve
Is there nice way to have warning (orange color) and non blocking validation feature with vuetify validation system ?

### Proposed solution
Metadata 'non-bloquant'? 'warningRules' ? An other mechanisme ?

**Comment by KaelWD** [comment]
I don't know what "bloquant" means, and this seems more like a question than a feature request. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by deka** [comment]
?? This is a feature request. 
the wording is surely bad

Currently, the validation mechanism contains only one color (red). This color is commonly associated with an error. Can you add the possibility of using the orange color, which it is commonly associated with a warning.

I do not know how that can be orchestrated. I just need to have an orange message (warning) when a component has a value that does not respect a condition (boolean function)

About the concept of blocking. a component that has a warning, must not prevent validating the form (...form.validate())

**Comment by KaelWD** [comment]
So you want `hint="does not respect a condition"` and `color="warning"`, with the colour showing when not focused?

**Comment by KaelWD** [comment]
Looks like we already have (broken) logic for an unused `success-messages` prop, this should be fairly easy to refactor for general use with other colours.

**Comment by deka** [comment]
[](url)

**Comment by mseele** [comment]
@deka do you have a workaround for this? we nedd the exact same feature. thanks

**Comment by deka** [comment]
@mseele 
No workaround. Not priority for me

**Comment by mseele** [comment]
@KaelWD https://github.com/vuetifyjs/vuetify/pull/5896 seems like the perfect fix for this (except warning validation rules - but this is a second feature imho). Any chance to get this merged?

My workaround now it to use success & successMessages for warnings.

Is there anything i can help with to get this implemented?

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by renoirb** [comment]
Bonsoir @deka, pour t'aider, here is something that might be of help.

You can do this leveraging the DOM, like [this this example on MDN][form-validation-change-css], then you can use `document.querySelector('input:invalid')...` to access via JS.

```html
<style>
input:invalid {
  border: 2px dashed red;
}
input:valid {
  border: 2px solid black;
}
</style>
<form>
  <label for="choose">Would you prefer a banana or a cherry?</label>
  <input id="choose" name="i_like" required pattern="[Bb]anana|[Cc]herry">
  <button>Submit</button>
</form>
```

[form-validation-change-css]: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#Validating_against_a_regular_expression

**Comment by dora-gt** [comment]
really disappointed at this community

**Comment by rudolf61** [comment]
Struggling with the same issue. 

It is quite normal to have errors and warnings. I have created a custom component to render the messages myself. I only use @blur and the error attribute. @blur for validation and error to set the error state. The rest is handled by the custom component. Now I can show errors and warnings. And any submit button is disabled as long as there is minimal 1 error. It does not block on warnings. Is not such a weird request, is it?

**Comment by renoirb** [comment]
Yes. It's easy to write a mouse hover on the submit that checks if any inputs bmhas an error state. That's native. The color change can be done natively with CSS as [I've said in french above](https://github.com/vuetifyjs/vuetify/issues/4819#issuecomment-725617645).

i didn't touch Vuetify myself for a long while, but with what I see with priorities of frameworks, features that DO NOT have native ways, or ensuring internal framework is consistent with ither features clming that aren't native be of higher priority.

CSS [:invalid selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) and use [input fields pattern ("*constraint validation*"](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation) can do that easily.
