### ISSUE TITLE
[Bug Report] Data Table Progress bar overlaps table header border

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#4826]
### Versions and Environment
**Vuetify:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Microsoft Edge, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Use a data-table and set the loading state to true.

### Expected Behavior
The progress bar should appear as if it's not being overlaid over the data table header but appear as if it's part of the data table.

### Actual Behavior
When using the progress bar on a data-table due to `.v-progress-linear__background` having an opacity applied to it, the border on the data table's header is visible.

### Reproduction Link
[https://codepen.io/anon/pen/RBqRdj](https://codepen.io/anon/pen/RBqRdj)

### Other comments
Removing the property of [top from v-progress-linear](https://github.com/vuetifyjs/vuetify/blob/075e426a940c85e23c5093dff0afd40343e9b4cd/src/stylus/components/_data-table.styl#L108) within _data-table.styl  and changing the value of [margin to 0 rather than 0 0 -2px](https://github.com/vuetifyjs/vuetify/blob/075e426a940c85e23c5093dff0afd40343e9b4cd/src/stylus/components/_data-table.styl#L109) appears to fix this issue.

Let me know if you want me to create a pull request.

**Comment by praveenpuglia** [comment]
Do you mean this is correct?
![image](https://user-images.githubusercontent.com/313363/43915259-cb9a5dd4-9c27-11e8-96da-ad0c4bb4ff69.png)
 and this is wrong?
![image](https://user-images.githubusercontent.com/313363/43915277-d9f11e36-9c27-11e8-8b9e-e85b2080af6c.png)

**Comment by praveenpuglia** [comment]
Agreed. Will fix this.
