### ISSUE TITLE
[Feature Request] V-Suggestion

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#4828]
### Problem to solve
The VAutocomplete is too definitive. to use it, the item must exist. It is basically a VSelect with a search button. Which is really good if you have only definitive data. 

But there are instances where you would like to reuse existing data, and still allow for free input.

### Proposed solution
What i am suggesting is a bit different. It's a VTextfield with VSelect menu. 
You are free to write what ever text. The component will show / filter what is provided in the items property, as the autocomplete component would and you are free to select one if you wish.

When you select the item, the VSuggestion would update the bound model with the text of the selected item, and emit a 'selected' event providing the item selected to be handled by the parent.

[Example GIF](https://gph.is/2vuTPum)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/combobox

**Comment by lgullestrup** [comment]
I guess i could wrap it.

Thanks @KaelWD

**Comment by KaelWD** [comment]
Wrap it how? That's already exactly what you're looking for: `a VTextfield with VSelect menu`

**Comment by lgullestrup** [comment]
Apologies. You are right. it is pretty much what I am.

I was stuck in an older mindset.
