### ISSUE TITLE
[Bug Report] v-select cursor changes to pointer in area that is not clickable

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#4836]
### Versions and Environment
**Vuetify:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Google Chrome, Microsoft Edge, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Hover over the area below a select (currently the whole v-select class is highlighted with an outline in the reproduction link so you can visually see the area in which this bug is triggered)

### Expected Behavior
The cursor should remain as the default cursor when below the actual clickable area.

### Actual Behavior
The cursor changes to a pointer cursor which gives a false expectation to a user that they can click that area.

### Reproduction Link
[https://codepen.io/anon/pen/ZjVKVv](https://codepen.io/anon/pen/ZjVKVv)

### Other comments
Suggested workaround - Instead of applying `.v-select{cursor:pointer;}` apply `.v-select .v-input__slot{cursor:pointer;}` as shown here - https://codepen.io/anon/pen/WKLjLR

**Comment by KaelWD** [comment]
Already fixed by f37e961f0245ceed5a3ab31a996b2cd292e222fe
