### ISSUE TITLE
"Toolbar and Sidebar" pattern in Pre-defined layouts doesn't work

### ISSUE THREAD

**Issue by shannonliang312** [vuetifyjs/vuetify#484]
first， please forgive my poor english  ^_^
### Steps to reproduce
https://vuetifyjs.com/layout/pre-defined
I just copied "Toolbar and Sidebar" demo code into codepen,  modified id of v-app, the link is below
### Versions

Vue: 2.2.6
vuetify: 0.11.1
os: ubuntu 16.10
browser: chrome 56.0.2924.87
### What is expected ?

1、when sidebar is open, it is under the toolbar
2、there is no left padding in the main section, just like what demo shows 

### What is actually happening ?

1、when sidebar is open, it is on the toolbar, 
2、there is 300px left-padding in  the main section

then I changed v-app properties from "left-fixed-sidebar to " left-sidebar sidebar-under-toolbar", the left-padding of main section is gone, sidebar is under the toolbar, but the first item of sidebar is covered by  the toolbar

### Reproduction Link

http://codepen.io/shannonliang312/pen/PmjgrE

P.S.  
The "Toolbar, Sidebar & Footer" demo code doesn't work well too

**Comment by johnleider** [comment]
I just used your codepen an added the sidebar-under-toolbar and it looked correct. The main section padding is also there.

**Comment by egorovd** [comment]
Also does not work
https://plnkr.co/edit/K0tdlE1khYLxr66ZAx2P?p=preview

**Comment by johnleider** [comment]
I'm not understanding the issue you are having sorry, but, the layout system has been completely revamped for next release.

If you can tell me what you are trying to achieve, I will make it for you and show you an example.

**Comment by egorovd** [comment]
I want to repeat 
https://vuetifyjs.com/layout/pre-defined
http://joxi.ru/4Ak0MVNuyl8yEr

**Comment by shannonliang312** [comment]
I want to achieve what demo shows,  just like "Toolbar and Sidebar"  and "Toolbar, Sidebar & Footer" pattern : sidebar is under the toolbar and there is no left-padding in the main section....
I will be appreciate if you can show me an example   (^_−)☆

**Comment by egorovd** [comment]
I try... )
http://joxi.ru/1A5QMqDTnJ63lA
Thanks for your effort.

**Comment by AdminLP** [comment]
Add the "sidebar-under-toolbar" parameter to the <v-app>
`<v-app id="example-2" left-fixed-sidebar sidebar-under-toolbar>
    <v-toolbar>
      <v-toolbar-side-icon @click.native.stop="nav2 = !nav2" />
      <v-toolbar-logo>Toolbar</v-toolbar-logo>
    </v-toolbar>
    <main>
      <v-sidebar left fixed drawer v-model="nav2">
        <v-list>
          <v-list-item v-for="i in 3" :key="i">
            <v-list-tile>
              <v-list-tile-title>Item {{ i }}</v-list-tile-title>
            </v-list-tile>
          </v-list-item>
        </v-list>
      </v-sidebar>
      <v-content>
        <v-container fluid>
          <div class="title">Main Content</div>
        </v-container>
      </v-content>
    </main>
  </v-app>`

**Comment by johnleider** [comment]
Does @AdminLP's answer this solve your issue?

**Comment by shannonliang312** [comment]
@johnleider sorry，it's not working

**Comment by egorovd** [comment]
> @egorovd Add the "sidebar-under-toolbar" parameter to the \<v-app>
Thank you, AdminLP.

Yes, works. 
But I can not understand why "sidebar" over "footer" :
http://codepen.io/anon/pen/JNMGWv
http://joxi.ru/v29dv05f3NB7Pm

**Comment by egorovd** [comment]
Everything, figured out.
Thank you.

**Comment by rudicronje** [comment]
@egorovd: The issue is not the sidebar under the toolbar, that is working fine.

The issue here is the yellow highlighted padding when the sidebar is closed. The "Main Content" should responsively shift left when the sidebar is toggled closed.

![image](https://cloud.githubusercontent.com/assets/282419/25844909/47464f90-34ac-11e7-9674-5887c09ee34d.png)

**Comment by shannonliang312** [comment]
@rudicronje   YES！！you read my mind

**Comment by johnleider** [comment]
http://codepen.io/johnjleider/pen/GmyPBb

I believe this solves the issue. As far as being able to collapse the sidebar on desktop and have the content respond by shifting back left, this is not possible in the current version but is something that is supported for next release.

**Comment by swerrie** [comment]
It also appears placing the sidebar to the right is not working as expected, can anyone confirm?
