### ISSUE TITLE
behaviour of Button Toggle should be same as radio\checkboxes

### ISSUE THREAD

**Issue by sourenaraya** [vuetifyjs/vuetify#4842]
As said in documentation 

> Toggle buttons are essentially styled radio or checkboxes, depending on the properties selected.

but this is not true. Radios and checkboxes can be validated (and error message shows up below).
Radios can be unchecked by default, with no default value, and you cant uncheck checked radio.
v-btn-toggle hovever, behave very differently: it have two modes: 

1. pre-checked radio, cant uncheck

1. unchecked checkbox\radio, could be unchecked.

I think it should be fixed. 
### What problem does this feature solve?
More consistent behaviour between radios\checkboxes and radio\checkbox-like components
For example, i have form where user should select one of the variants. This is required field, but its should not be pre-checked or uncheckable. If user forgot to check one of the variants, hint should pop-up. With current implementation of v-btn-toggle i cant do this, so i am stuck witch v-radio-group\v-radio for now.

### What is your proposed solution?
I think API and logic behing should be identical to such of radio\checkboxes

**Comment by johnleider** [comment]
This can now be accomplished with `v-item-group` in v1.3
