### ISSUE TITLE
[Feature Request] Implement top notch code splitting and tree-shaking support and deprecate a la carte components

### ISSUE THREAD

**Issue by mrts** [vuetifyjs/vuetify#4845]
With Vue-CLI 3 and webpack 4 it should be possible to modularize all components so that default tree-shaking achieves the same result as a la carte components currently. In this case there is no longer any need for a la carte components.

**Comment by KaelWD** [comment]
Already planned, this doesn't need an issue for us to track.

**Comment by mrts** [comment]
Excellent, happy to hear that! Is the plan documented somewhere?

**Comment by KaelWD** [comment]
Does my head count?

**Comment by mrts** [comment]
Well, maybe it is indeed good enough :). Good to hear that you guys keep thinking deeply about the future of Vuetify - and many thanks for your awesome work with it!
