### ISSUE TITLE
VParallax has wrong style properties in version 1.1 & 1.2

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#4847]
### Versions and Environment
Vuetify: 1.1 & 1.2 beta
Browsers: all
OS: all

### Previously worked in:
Vuetify: 1.0.19

### Steps to reproduce
Open docs of the current VParallax examples
https://vuetifyjs.com/en/components/parallax
https://next.vuetifyjs.com/en/components/parallax
Only the first parallax of the page is visible. The second and third are either cut off or not visible at all.

### Expected Behavior
Parallax elements should be visible as in version 1.0.x
https://v1.vuetifyjs.com/en/components/parallax

### Actual Behavior
Parallax has non-correct applied styles after initialize and scrolling.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/4592/files#diff-5f661a376166de8c610039356f552bc3R30

**Comment by dohomi** [comment]
@KaelWD @johnleider do you guys know a temporary solution to fix this for the current v 1.1/1.2? Thanks
