### ISSUE TITLE
Text field in menu in toolbar does not get full width, while it does without a menu

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#4848]
### Versions and Environment
Vuetify: 1.1.10
Vue: 2.5.17
Browsers: Chrome  68.0.3440.84
OS: MacOs 10.13.6

### Steps to reproduce

Create a text-field within a menu within a toolbar

### Expected Behavior

The text-field should have full width of the toolbar, as is the case for a text-field within a toolbar when not using a menu.

### Actual Behavior

The text-field size is too smal

### Reproduction Link

https://codepen.io/everhardt/pen/yqwPQv

---

### Additional Comments:
I did use the `full-width` prop for the menu, as suggested in https://github.com/vuetifyjs/vuetify/pull/4546.

**Comment by KaelWD** [comment]
This will be fixed with #3206, you can work around it for now with `<v-menu class="grow"`

**Comment by everhardt** [comment]
Great, thanks for the very quick response!
