### ISSUE TITLE
[Feature Request] Replicate HTML Select hotkeys in Vuetify <v-select>

### ISSUE THREAD

**Issue by samuelcolburn** [vuetifyjs/vuetify#4853]
### Problem to solve
In a vanilla html select input, once the input is focused, the different options can be quick-selected by typing the first letter of an option. This not only highlights the value, but also  **selects** that value.

This may seem trivial, but it is a standardized feature in select inputs, and is an important feature for semi-advanced users who are accustomed to faster data input methods.

This pen shows the issue:
https://codepen.io/smcolburn/pen/zLbXOy?&editors=101

To reproduce:
1. Click on the vuetify `<v-select>` input.
2. Press `F`. Nothing happens.
3. Click on the HTML `<select>` input.
3. Press `D`. `Dog` is automatically highlighted. If the user tabs away, `Dog` is saved as the input value.

### Proposed solution
`<v-select>` should emulate standard HTML inputs in this regard. If a user begins to type with the input focused, it should automatically select the closest matched value to their input based on the `itemValue` prop, string match, or possibly a filter function. 

**THIS IS NOT THE SAME AS V-AUTOCOMPLETE** 
Note that is not the same as `v-autocomplete` or the basic filtering functionality therein. The autocomplete suggests options based on the users input, and filters possible values based on that input.

This is recreating the standard HTML select functionality. No options should be filtered out, and the closest matching option should be automatically selected from the list of options.

**Comment by sebastian-walter** [comment]
What is missing additionally is exiting the select by pressing the ESC button. This can be really annoying for users who are used to navigate forms via the keyboard.

**Comment by ThomasKientz** [comment]
It is still not replicating a vanilla html select. 

In a vanilla html select input, the input's value is **NOT** changed before the user hits ENTER.

https://github.com/vuetifyjs/vuetify/issues/9967
