### ISSUE TITLE
[Bug Report] padding-left in ol & ul tags in RTL instead of padding-right

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#4854]
### Versions and Environment
Vuetify: 
Vue: 2.5.17
Browsers: Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
OS: Ubuntu 18.04.1

### Steps to reproduce
Using ul and ol tags in RTL

### Expected Behavior
Having padding in the right

### Actual Behavior
Having padding in the left

### Reproduction Link
https://codepen.io/ibrahimbeladi/pen/mjoNdV

**Comment by KaelWD** [comment]
RTL is currently only supported for form components, we are working on bringing it to the rest of the framework. This does not need to be tracked separately.
