### ISSUE TITLE
[Feature Request] Add nuxt option to v-pagination components

### ISSUE THREAD

**Issue by dolphinysaru** [vuetifyjs/vuetify#4855]
### What problem does this feature solve?

Adding the nuxt option to v-pagination makes ssr (server side rendering) possible.

### What is your proposed solution?

If you add the nuxt option the same as the button component, the nuxt-link option should be applied.

**Comment by sourenaraya** [comment]
This would be nice addition.

**Comment by filipwronski** [comment]
@sourenaraya I'm trying to use your's workaround. On client side everything work fine, but after page refresh nuxt returning error "render function or template not defined in component: anonymous". Do you know what is wrong?

**Comment by johnleider** [comment]
Unfortunately this did not make the cut for v2.0. Thank you for your patience.

**Comment by KaelWD** [comment]
Should we just remove the `nuxt` prop elsewhere and always use `nuxt-link` if nuxt is detected?

**Comment by avgeeklucky** [comment]
My version of @sourenaraya's workaround. I couldn't get the `import { VPagination } from 'vuetify/es5/components/VPagination';` to work in my nuxt configuration. I'm getting a "Invalid or unexpected token" error on that.

```vue
<script>
    /**
     * @see https://github.com/vuetifyjs/vuetify/issues/4855
     */
    import Vue from 'vue';
    const VPagination = Vue.component('VPagination');
    export default {
        name: 'NuxtPagination',
        mixins: [VPagination],
        props: {
            toGenerator: {
                type: Function,
                required: true,
            },
        },
        methods: {
            next(e) {
                e.preventDefault();
                this.$router.push(this.toGenerator(this.value + 1));
            },
            previous(e) {
                e.preventDefault();
                this.$router.push(this.toGenerator(this.value - 1));
            },
            genItem(h, i) {
                return h('nuxt-link', {
                    attrs: {
                        to: this.toGenerator(i),
                    },
                }, [VPagination.options.methods.genItem.call(this, h, i)]);
            },
        },
    };
</script>
```

**Comment by Dean-Christian-Armada** [comment]
> Should we just remove the `nuxt` prop elsewhere and always use `nuxt-link` if nuxt is detected?

Do we have an updated here? I was also hoping that I can put a `nuxt-link` on the numbers of my `v-pagination`

**Comment by Dean-Christian-Armada** [comment]
> My version of @sourenaraya's workaround. I couldn't get the `import { VPagination } from 'vuetify/es5/components/VPagination';` to work in my nuxt configuration. I'm getting a "Invalid or unexpected token" error on that.
> 
> ```
> <script>
>     /**
>      * @see https://github.com/vuetifyjs/vuetify/issues/4855
>      */
>     import Vue from 'vue';
>     const VPagination = Vue.component('VPagination');
>     export default {
>         name: 'NuxtPagination',
>         mixins: [VPagination],
>         props: {
>             toGenerator: {
>                 type: Function,
>                 required: true,
>             },
>         },
>         methods: {
>             next(e) {
>                 e.preventDefault();
>                 this.$router.push(this.toGenerator(this.value + 1));
>             },
>             previous(e) {
>                 e.preventDefault();
>                 this.$router.push(this.toGenerator(this.value - 1));
>             },
>             genItem(h, i) {
>                 return h('nuxt-link', {
>                     attrs: {
>                         to: this.toGenerator(i),
>                     },
>                 }, [VPagination.options.methods.genItem.call(this, h, i)]);
>             },
>         },
>     };
> </script>
> ```

Where did you put this? Is this a component?

**Comment by avgeeklucky** [comment]
@Dean-Christian-Armada I've actually ended up with a slightly different version from the snippet mentioned above. It was work, but only in dev builds. `Vue.component('VPagination');` did not return anything in production builds.

**components/nuxt-pagination.vue**
```vue
<script>
    /**
     * @see https://github.com/vuetifyjs/vuetify/issues/4855
     */
    import { VPagination } from 'vuetify/lib/components';
    export default {
        name: 'NuxtPagination',
        mixins: [VPagination],
        props: {
            toGenerator: {
                type: Function,
                required: true,
            },
        },
        methods: {
            next(e) {
                e.preventDefault();
                this.$router.push(this.toGenerator(this.value + 1));
            },
            previous(e) {
                e.preventDefault();
                this.$router.push(this.toGenerator(this.value - 1));
            },
            genItem(h, i) {
                return h('nuxt-link', {
                    attrs: {
                        to: this.toGenerator(i),
                    },
                }, [VPagination.options.methods.genItem.call(this, h, i)]);
            },
        },
    };
</script>
```
Also needed to update `nuxt.config.js`:
```js
export default {
    ...
    build: {
        ...
        transpile: ['vuetify'],
        ...
    }
};
```
