### ISSUE TITLE
[Bug Report] v-edit-dialog is transparent on v1.2

### ISSUE THREAD

**Issue by alex-red** [vuetifyjs/vuetify#4856]
### Versions and Environment
Vuetify: 1.2
Vue: latest
Browsers: Chrome
OS: Ubuntu 18.04

### Previously worked in:
Vuetify: 1.1
Vue: latest

### Steps to reproduce

Open inline editing on a table
### Expected Behavior

White menu background
### Actual Behavior

Background is transparent
### Reproduction Link

https://codepen.io/anon/pen/ejodKX?&editors=101

---

### Additional Comments:
Also on https://next.vuetifyjs.com/en/components/data-tables#example-editdialog

Only seems to be transparent on 1.2

**Comment by bobeagle** [comment]
when is this going to be released? i'm on 1.2.4 and still seeing transparent v-edit-dialog

**Comment by P4Thi0ut** [comment]
A css fix will not do, please update :)

**Comment by jacekkarczmarczyk** [comment]
Please do not comment on closed issues
https://github.com/vuetifyjs/vuetify/issues/5127
