### ISSUE TITLE
[Feature Request] How drop search from table

### ISSUE THREAD

**Issue by AleksandarMiha** [vuetifyjs/vuetify#4857]
### Problem to solve
I can't drop search from table... I drop :search="search" and all from <v-data-table> and V-text-field but search is here.

### Proposed solution
I don't know.

**Comment by sh7dm** [comment]
Do you have an example of this bug?

**Comment by nekosaur** [comment]
This is not a feature request. If you are having specific problems, please join us at https://chat.vuetifyjs.com, or file a bug report with a reproduction of the issue.
