### ISSUE TITLE
[Bug Report] v-stepper breaks when selecting previous step (v1.2.0-beta.1)

### ISSUE THREAD

**Issue by alex-red** [vuetifyjs/vuetify#4862]
### Versions and Environment
Vuetify: 1.2.1
Vue: latest
Browsers: Chrome
OS: Ubuntu 18.04

### Previously worked in:
Vuetify: 1.2.0
Vue: latest

### Steps to reproduce

Click on Step 2 or Step 3, then click back to Step 2 or Step 1
### Expected Behavior

Show the stepper content properly
### Actual Behavior

Stepper content is missing
### Reproduction Link

https://codepen.io/anon/pen/djLEGO?&editors=101
---

### Additional Comments:
Worked on 1.2.0

**Comment by kdholt34** [comment]
Looks like `position: absolute;` is getting added to the stepper content element on "leave" and it's not removed on "enter".  A change in `src/util/helpers.ts` as part of 1.2.0-beta.1

**Comment by henriq-88** [comment]
Here is a temporary workaround:
`<style lang="stylus" scoped>
>>> .v-stepper__content:not(.tab-transition-enter):not(.tab-transition-leave):not(.tab-transition-leave-active):not(.tab-transition-leave-to):not(.tab-reverse-transition-enter):not(.tab-reverse-transition-leave):not(.tab-reverse-transition-leave-to)
  position: relative !important
</style>`

**Comment by KaelWD** [comment]
Already fixed on dev: 719ac431bbcf42d275e248f96f7b98fd0a2b444c
