### ISSUE TITLE
[Feature Request] Server side pagination for v-autocomplete/v-select (loading more items on scroll)

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#4867]
V-select and V-autocomplete load more items on scroll, this only loads more items into the HTML, but the `items` prop has to be filled already. It would be nice to be able to load this from the server.

### What problem does this feature solve?
Some API's endpoints are paginated, for now when i have an autocomplete i add a parameter like perPage=10000 to API request parameters so everything works, except this is really slow. 

### What is your proposed solution?
Add a prop which indicates if you want to use server side pagination, when the `onScroll` method from `v-select` at this point it raises the `this.lastItem`, it should fire an event which then can load x more items from the server.

**Comment by ricardovanlaarhoven** [comment]
When i had this issue i created a PR which fixed my issue.
Some time past since then.
My PR was closed "Unfortunately this is not functionality that we are looking to implement at this time."
And i have had some contact with @johnleider

He told me that there are ways to do this with the current functionality. And i think this is the right place to show the people who are struggling with this can find the solution.

Could anyone who knows the solution post it here?
At this point i request 10.000's of items from the api whithout pagination as a dirty bugfix

**Comment by johnleider** [comment]
This is what I was referring to: https://vuetifyjs.com/en/components/selects#example-slots

**Comment by massimolavermicocca** [comment]
Hi, any news on this subject yet? Is there a workaround to implement it using current vuetify release?

**Comment by kanteankit** [comment]
@massimolavermicocca 
You can use the `append` slot to add a button/menu-item to the end of the dropdown, that says `Load More`. When user clicks on it, you can make an API call to fetch more data and push it to the list

**Comment by massimolavermicocca** [comment]
@kanteankit Could you please provide a sandbox with that? the `append` slot seems to draw object next to the autocomplete itself.
Example: [https://codepen.io/anon/pen/omZNgo?editors=1010](url)

**Comment by KaelWD** [comment]
He means `append-item`

**Comment by tyteen4a03** [comment]
Bumping this - are there any workarounds right now?

**Comment by NothingWeAre** [comment]
This solution somewat buggy.
When added items count reach multipliers of 20 new items does not show, until user tries to scroll up.
This is related to the internal value of `lastItem`

**Comment by ricardovanlaarhoven** [comment]
@tyteen4a03 It is possible with the `append-item` mentioned by @KaelWD but i prefer a more build-in solution by vuetify like the PR i've made.
Because i think this is an issue which multiple users have and if everyone has to build an own way in the v-select/v-autocomplete..

**Comment by ebuychance** [comment]
:+1: to adding this feature or creating a new component.

**Comment by lorenzomorandini** [comment]
This seems quite an important feature. We have multiple paginated APIs that have to handle a lot of data. Loading all of them on page load would slow down the entire page.

**Comment by RobbinBaauw** [comment]
I don't see the problem with the PR, and I'm willing to port it to the new version of the component. The workarounds described here (e.g. creating a "load more" button) are a worse solution than automatic calculations of when to retrieve new records. The best way to do those calculation is in the component definition itself (and part of these calculations already happen). The "only" thing that would need to happen is to call a method instead of increasing "lastItem" right?

**Comment by ricardovanlaarhoven** [comment]
In my opinion that's correct @RobbinBaauw
I hope the vuetify team agree's!

**Comment by AyushiBShah** [comment]
Any workaround for this time being ?

**Comment by villeneuve-michael** [comment]
I'd like to still show interest for this feature request. In terms of UX it's the Load More idea is a terrible compared to the PR that was mentioned previously in this thread.

**Comment by ThomasKientz** [comment]
I have a simple solution for vuetify v1, see the repo : https://github.com/ThomasKientz/vuetify-v1-autocomplete-infinite-scroll

I have used the `append-item` slot with the [vue-observe-visibility](https://github.com/Akryum/vue-observe-visibility)'s directive. 

Then I am calling `this.$refs.autocomplete.onScroll();` to force a refresh of the list otherwise you have to scroll up then down again to render the new items.

**Comment by anhnguyenpku** [comment]
Thanks for your solution. This also aplly for vuetify 2x.

**Comment by HamletLeon** [comment]
> I have a simple solution for vuetify v1, see the repo : https://github.com/ThomasKientz/vuetify-v1-autocomplete-infinite-scroll
> 
> I have used the `append-item` slot with the [vue-observe-visibility](https://github.com/Akryum/vue-observe-visibility)'s directive.
> 
> Then I am calling `this.$refs.autocomplete.onScroll();` to force a refresh of the list otherwise you have to scroll up then down again to render the new items.

I see that now with https://vuetifyjs.com/en/components/lazy/#usage is possible to simulate the same aproach that your answer. 🤔

**Comment by ThomasKientz** [comment]
@HamletLeon Nop, `v-lazy` "will not render its contents until it has been intersected". So It is works for the first load, not the next ones. But https://vuetifyjs.com/en/directives/intersect/ can replace [vue-observe-visibility](https://github.com/Akryum/vue-observe-visibility). Above solution works for v2 as well. Do you have troubles make it work ?

**Comment by HamletLeon** [comment]
> @HamletLeon Nop, `v-lazy` "will not render its contents until it has been intersected". So It will work only for the first load, not the next ones. But https://vuetifyjs.com/en/directives/intersect/ can replace [vue-observe-visibility](https://github.com/Akryum/vue-observe-visibility). Above solution works for v2 as well. Do you have troubles make it work ?

I'm just testing, i can use v-lazy if just i set the boolean "...Active" to false after getting next "page" and re-rendering...

**Comment by yoelpc4** [comment]
> This solution somewat buggy.
> When added items count reach multipliers of 20 new items does not show, until user tries to scroll up.
> This is related to the internal value of `lastItem`

Hey I just realized we are experiencing the same issue in "This solution somewat buggy. When added items count reach multipliers of 20 new items does not show, until user tries to scroll up". 

So I came up with a solution to load 15 items each request, that could solve this issue.

**Comment by KaelWD** [comment]
> new items does not show until user tries to scroll up

This has been fixed in d9bb128a5

**Comment by mrodal** [comment]
this should be something general, also applicable for example to lists and tables

**Comment by mrodal** [comment]
I created a simple InfiniteScroll component that it enough for my needs for now, but of course can be further improved to allow for loading indicators and things like that

It is more oriented to lists and cards, I didnt try it on Select and Autocomplete, but it may be useful to someone

Here it is:
https://gist.github.com/mrodal/56952b72f6d378b3c263da506d002289

**Comment by DariaYeremina** [comment]
Inspired by @mrodal I've used v-intersect in v-autocomplete.

InfiniteScroll.vue
`<template>
    <div v-intersect="onIntersect"
         :data-last="index === itemsLength - 1">
        <slot :item="item"></slot>
    </div>
</template>

<script>
export default {
    name: 'InfiniteScroll',
    props: {
        itemsLength: {
            type: [Number, String],
            required: true
        },
        item: {
            type: Object,
            required: true
        },
        index: {
            type: [Number, String],
            required: true
        }
    },
    methods: {
        onIntersect (entries, observer) {
            if (entries[0].isIntersecting && entries[0].target.dataset.last) {
                this.$emit('load-more-items');
            }
        }
    }
};
</script>
`

Autocomplete.vue
`<template xmlns:v-slot="http://www.w3.org/1999/XSL/Transform">
    <ValidationProvider :name="$attrs.label"
                        :vid="name"
                        :rules="rules"
                        v-slot="{ errors }"
                        tag="div">
        <v-autocomplete  outlined
                         :error-messages="errors"
                         v-bind="$attrs"
                         v-on="$listeners">
            <template slot="label">
                {{ $attrs.label }}
                <span v-if="isRequired" class="error--text">*</span>
            </template>
            <template v-slot:selection="data">
                <span v-if="data.index === 0 || !$attrs.multiple" class="mr-1">{{ data.item.text }}</span>
                <span v-if="$attrs.multiple && $attrs.value.length > 1 && data.index === 1"
                      class="grey--text caption">(+ {{ $attrs.value.length  - 1 }})</span>
            </template>
            <template v-slot:item="{ item, on, attrs }">
                <InfiniteScroll :item="item"
                                @load-more-items="loadMoreItems"
                                :index="itemIndex(item)"
                                :items-length="itemsLength">
                    <v-layout align-center>
                        <Checkbox v-if="$attrs.multiple"
                                  v-bind="attrs"
                                  v-on="on"></Checkbox>
                        <span>{{ item.text }}</span>
                    </v-layout>
                </InfiniteScroll>
            </template>
        </v-autocomplete>
    </ValidationProvider>
</template>

<script>
import { ValidationProvider } from 'vee-validate';
import InfiniteScroll from '@/components/widgets/InfiniteScroll';
import Checkbox from '@/components/widgets/forms/Checkbox';
import isFieldRequired from '@/mixins/isFieldRequired';

export default {
    name: 'Autocomplete',
    components: { ValidationProvider, InfiniteScroll, Checkbox },
    mixins: [isFieldRequired],
    props: {
        slotName: {
            type: String,
            'default': ''
        },
        name: {
            type: String,
            'default': ''
        },
        rules: {
            type: [String, Object, Array],
            'default': ''
        }
    },
    computed: {
        itemsLength () {
            return this.$attrs.items.length;
        }
    },
    methods: {
        itemIndex (item) {
            return this.$attrs.items.findIndex(el => el.value === item.value);
        },
        loadMoreItems () {
            this.$emit('load-more-items');
        }
    }
};
</script>

<style scoped lang="scss">
    ::v-deep {
        & .theme--light.v-input.v-input--checkbox {
            margin-top: 0;
            & input {
                visibility: hidden;
            }
            & .v-messages {
                display: none;
            }
        }
    }
</style>
`

And usage example
`<Autocomplete :label="$t('labels.customer')"
                                  :disabled="isEditable"
                                  name="customer_id"
                                  rules="required"
                                  clearable
                                  @click:clear="getCustomers(null)"
                                  @load-more-items="getCustomersLazyLoading"
                                  :items="listingCustomers"
                                  :loading="isCustomersLoading"
                                  :search-input.sync="searchCustomers"
                                  v-model="customer_id"></Autocomplete>`

**Comment by Nikakto** [comment]
If input's with items (v-autocomplete, v-select, etc) will have slot items (like body for tables), we can show instead of props.items any other custom list or menu with server side pagination. So, we only required items slot scoped by attrs and listeners to inherit behaviors of items.

**Comment by Anubarak** [comment]
So as far as I can see there are really no real plans to implement it besides pushing the release to the future?
