### ISSUE TITLE
How to change alternate row color in v-data-table

### ISSUE THREAD

**Issue by sidnaik03** [vuetifyjs/vuetify#4868]
Hi,

I am using v-data-table in my project. I want to change alternate row color of rows (odd even). Please suggest how to do it.

**Comment by KaelWD** [comment]
Use CSS

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
