### ISSUE TITLE
[Feature Request] Support iOS Component Theme/Styles

### ISSUE THREAD

**Issue by geekox86** [vuetifyjs/vuetify#4869]
### What problem does this feature solve?
This will make Vuetify the single-go-to framework for mobile developers, when it comes to supporting both Android (MD) and iOS native look and feel. Such styles already exist in other frameworks, so it can be forked and customized for Vuetify.

### What is your proposed solution?
It can be a global option when registering Vuetify with Vue.use

**Comment by geekox86** [comment]
Hi awesome Vuetify team,

Thank you for your wonderful library that makes UX development a breeze!

Any feedback on this feature request?

Thanks!

**Comment by johnleider** [comment]
Maybe one day, if we find a champion for the functionality.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
