### ISSUE TITLE
Tabs inside modals or dialogs and improvement to your Core documentation

### ISSUE THREAD

**Issue by JaniSavolainen** [vuetifyjs/vuetify#487]
Have a feature request?
=======================
Tried to figure out how to make button with icon and text and went to "components --> buttons". i did not find any  similar so tried to make my own. Had troubles with button spacing :). ...few hours later by accident. Found button with icon in "icons section". Some examples to button section as well?

Now i struggle to make working tabs inside dialog/modal :) So examples would be nice in your documentation or is it possible right now?

**Comment by johnleider** [comment]
Would need to see what you are trying to do. As far as the documentation,  it's currently being completely overhauled.

**Comment by JaniSavolainen** [comment]
Solved. My mistake in routing
