### ISSUE TITLE
[Bug Report] Failed to resolve directive: scroll

### ISSUE THREAD

**Issue by digitalit** [vuetifyjs/vuetify#4871]
### Versions and Environment
**Vuetify:** 1.2.0-beta.1
**Last working version:** 1.1.8
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Mac OS 10.13.6

### Steps to reproduce
Scroll down page

### Expected Behavior
offsetTop should count up

### Actual Behavior
offsetTop stays at 0

### Reproduction Link
[https://codepen.io/anon/pen/djEWGp](https://codepen.io/anon/pen/djEWGp)

### Other comments
beta0 same problem but no console message

**Comment by DRoet** [comment]
same problem here: https://next.vuetifyjs.com/en/directives/scrolling

**Comment by shongololo** [comment]
The same is happening with the resize directive, so this is probably affecting all directives.

e.g. the browser error messages are:

```
[Vue warn]: Failed to resolve directive: scroll
[Vue warn]: Failed to resolve directive: resize
```

**Comment by ayZagen** [comment]
This issue still exists in 1.3.11

**Comment by abelit** [comment]
I came across the same problem when I use v-scroll directive in vue and vuetify project. I have tried it both vuetify@1.5.5 and vuetify@1.5.14 and the problem remains.

**Comment by raojingpeng** [comment]
> I came across the same problem when I use v-scroll directive in vue and vuetify project. I have tried it both vuetify@1.5.5 and vuetify@1.5.14 and the problem remains.

**If using a la carte, you should do this.**

import { Scroll } from 'vuetify/lib/directives'

Vue.use(Vuetify, {
  directives: {
    Scroll
  }
}

**Comment by abelit** [comment]
> > I came across the same problem when I use v-scroll directive in vue and vuetify project. I have tried it both vuetify@1.5.5 and vuetify@1.5.14 and the problem remains.
> 
> **If using a la carte, you should do this.**
> 
> import { Scroll } from 'vuetify/lib/directives'
> 
> Vue.use(Vuetify, {
> directives: {
> Scroll
> }
> }

Thanks !

**Comment by Skriptach** [comment]
@raojingpeng I'm not using a la carte

And when I try

```javascript
import { Scroll } from 'vuetify/lib/directives';
```

I got error

```shell
 FATAL  Invalid or unexpected token                                                                                                                                                                    
  @import '../../styles/styles.sass'
  ^

  SyntaxError: Invalid or unexpected token
  at Object.compileFunction (vm.js:403:10)
  at Generator.next (<anonymous>)
  at Object.<anonymous> (node_modules\vuetify\lib\directives\ripple\index.js:1)
  at Generator.next (<anonymous>)
```
