### ISSUE TITLE
[Bug Report] V-content padding for footer doesn't match v-footer height

### ISSUE THREAD

**Issue by Eyedicious** [vuetifyjs/vuetify#4872]
### Versions and Environment
**Vuetify:** 1.1.12
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
1. Create app with `<v-app>`, `<v-content>` and `<v-container>`
2. Apply `fill-height` on `<v-container>`.
3. Add `<v-footer>` below `<v-content>`
4. Add `app` to `<v-footer>`

### Expected Behavior
The padding that is being applied by V-content matches the height of the v-footer
either 36 pixels or 32 pixels for either

### Actual Behavior
The padding that is being applied is 32 pixels, while the v-footer is 36 pixels.

### Reproduction Link
[https://codepen.io/anon/pen/djEJey](https://codepen.io/anon/pen/djEJey)

### Other comments
I originally encountered this 1.1.7, but upgrading to 1.1.12 didn't seem to have resolved it.

The height that is being set for the v-footer is 32 pixels, but it is being overwritten by the specified min-height of 36 pixels. Either tweaking the footer height or the padding size can easily resolve this, but I figured it'd still be worth mentioning it.

**Comment by KaelWD** [comment]
Workaround: `<v-footer app height="auto">`

**Comment by jacekkarczmarczyk** [comment]
fixed by 959f07440fedb76473dedb71b1b0766d238a8531
