### ISSUE TITLE
[Bug Report] V-Btn (transition) heavy CPU usage in IE11

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#4873]
### Versions and Environment
**Vuetify:** 1.1.12
**Vue:** 2.5.17
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
profile either:

https://vuetifyjs.com/en/components/buttons

or the codepen code in IE11 (the codepen doesn't polyfill)

### Expected Behavior
CPU should stay lower

### Actual Behavior
CPU goes up significantly for multiple buttons ~40%

### Reproduction Link
[https://codepen.io/anon/pen/XBwYWw](https://codepen.io/anon/pen/XBwYWw)

### Other comments
`v-btn` takes up a ton of CPU, if you place around 10 of them it goes up to ~35% cpu, one button alone takes about ~7%

however the interesting part is that if you change is to `<v-btn fab>` and place around 10 of them it stays below 1% CPU

and this is idle performance not on render

removing the transition moves it back to ~0% CPU:

<img src="https://cdn.discordapp.com/attachments/351121729164410882/479248078080311337/unknown.png" width="250" height="250">

using a different transition like: `transition: opacity 15ms linear` does not create heavy CPU usage, so I'm guessing the `cubic-brezier` calculation is a little too much for IE11

**Comment by KaelWD** [comment]
#4045

**Comment by DRoet** [comment]
@KaelWD what can I do to further help here?

I've looked at the duplicate issue, but the suggested fix `border-radius: 0;` only brings down CPU with like 30%, my "fix" with the transition brings it down completely (without the `border-radius` patch)
I've looked at other material-design frameworks (angular.material / mdc) and they either have no transition (it doesn't get polyfilled, just works in newer browser) or use a different transition all-together `transition: opacity 15ms linear`

**Comment by DRoet** [comment]
I'm just going to use the workaround for now:

```
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
  .v-btn::before {
    border-radius: 1.5pt !important; // or border-radius: 0 !important
  }
}
```
