### ISSUE TITLE
[Feature Request] V-Autocomplete - prop to override opening the menu upon updated items

### ISSUE THREAD

**Issue by dkichler** [vuetifyjs/vuetify#4878]
### What problem does this feature solve?
V-Autocomplete has a feature where if the input has focus, and is not active when the `items` change, the menu is invoked/opened.  The [comments](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VAutocomplete/VAutocomplete.js#L180-L181) on this feature lead one to believe it is to account for async updates to `items`.  

Having a prop to override this feature would allow the client to control for cases where having the menu invoked is undesirable.  For example, an autocomplete input used in a dynamic form, with other elements that may change what collection is active in the autocomplete `items` via a computed property.  

### What is your proposed solution?
The proposed solution is a simple Boolean prop to act as a toggle for this feature.  Default behaviour would be unchanged, but including the prop would disable the menu being invoked when holding focus and having it's collection updated.

**Comment by KaelWD** [comment]
It's a bug: #4463

**Comment by dkichler** [comment]
I believe you meant to reference #4663.

**Comment by KaelWD** [comment]
Yeah numbers are hard lol.
