### ISSUE TITLE
[Feature Request] Popup events on mouseover for VDatePicker

### ISSUE THREAD

**Issue by Kailaash-Balachandran** [vuetifyjs/vuetify#4884]
### What problem does this feature solve?
Users should be able to get a top level description of the events for the mouseover-ed date.

### What is your proposed solution?
Supply additional event @mouseover with the hovered date so the parent could display the details for the date.

Component: VDatePicker

**Comment by johnleider** [comment]
This is solved in v1.2 with the addition of `v-hover`

**Comment by Kailaash-Balachandran** [comment]
I've created a PR for the feature https://github.com/vuetifyjs/vuetify/pull/4889

**Comment by jacekkarczmarczyk** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/pull/11126
