### ISSUE TITLE
v-data-table: align property for headers broken

### ISSUE THREAD

**Issue by peterthomassen** [vuetifyjs/vuetify#4887]
### Versions and Environment
Vuetify: 1.1.13
Vue: 2.5.17
Browsers: Chromium 68
OS: Linux Mint 18

### Steps to reproduce
1. Make a v-data-table
2. Use `align: '...'` in the `headers` prop.

### Expected Behavior
In the code, `align: 'left'` is defined for the first column heading ("Dessert"). It is expected that the column heading is left-aligned.

### Actual Behavior
The column heading is centered, and the alignment setting seems to have no effect.

### Reproduction Link
https://vuetifyjs.com/en/components/data-tables#example-headers

**Comment by johnleider** [comment]
Linking to the docs is not a reproduction link.

**Comment by KaelWD** [comment]
The example is incorrect, `align` doesn't work if you override the slot.

**Comment by ikit** [comment]
Hi, this ticket is closed, but I'm currently facing the same problem with vuetify 1.5.2... is it really fixed ? Or what is the good way to align left cell content in data-table ?

**Comment by Vedran-Basic** [comment]
Actually I have only overriden the data-table body, but headers aren't overriden. Align property doesn't work

**Comment by DestBest** [comment]
Doc is faulty:
[From doc](https://vuetifyjs.com/en/components/data-tables/) NOT WORKING: align?: 'start' | 'center' | 'end'
WORKING: align?: 'left' | 'center' | 'right'

**Comment by torueck** [comment]
Actually,
`align?: 'start' | 'center' | 'end'`
aligns the header, while 

`align?: 'left' | 'center' | 'right'`
aligns the cell content.

Is this the intended behavior?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
