### ISSUE TITLE
[Feature Requestt] Add error slot to v-img

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#4888]
### Problem to solve
v-progress-circular keeps on loading the loader when v-img src getting failed. 
v-progress-circular should dismiss either success or error

### Proposed solution
success slot - dismissing loader (Works fine)
error slot - will replace placeholder for error message or whatever

**Comment by nekosaur** [comment]
If this is a bug report, please use the appropriate template and provide reproduction of the issue.

**Comment by ksankumar** [comment]
https://codepen.io/ksankumar/pen/VBJWYM

Switch correct_imgSrc to wrong_imgsrc and watch. Now progress circular not getting dismissed.

**Comment by nekosaur** [comment]
This is a feature request, not a bug report. The current solution is to do something like this https://codepen.io/anon/pen/dqwyGz?editors=1010
