### ISSUE TITLE
First sortable column cannot be sorted in descending order in datatable

### ISSUE THREAD

**Issue by MitchelLabonte** [vuetifyjs/vuetify#489]
### Steps to reproduce
- Have a datatable with a sortable column.
- Click on the header of the first sortable column

### Versions
Firefox 45.8.0
Vuetify 0.11.1

### What is expected ?
By default, the first sortable column is in ascending order. Clicking on it should sort it in descending order.

### What is actually happening ?
The column stays in ascending order no matter how many times you click on it.
There is a workaround: sort another column then click on the first sortable column header and it will be sorted in descending order. If you click once more though, it will be stuck in ascending order again.

### Reproduction Link
This can be seen on the _Standard_ datatable demo in the official documentation:
https://vuetifyjs.com/components/datatables
(Try to sort the _Calories_ column)

**Comment by johnleider** [comment]
This has already been fixed in the dev branch of vuetify.

**Comment by kylejoeckel** [comment]
i still have this issue more than a year later. is this still in dev? the first column will not sort.

**Comment by johnleider** [comment]
@kylejoeckel please do not comment on old closed issues. If you are still experiencing problems, please create a new ticket.
