### ISSUE TITLE
[Bug Report] v-slider with thumb-label is missing margin-top

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#4891]
### Versions and Environment
Vuetify: 1.2.0-beta.1 (and beta.2)
Vue: 2.5.16

### Previously worked in:
Vuetify: 1.2.0-beta.0
Vue: 2.5.16

### Steps to reproduce

See margin-top

### Expected Behavior

Sliders with thumb-label should still have margin-top

### Actual Behavior

No CSS rule for margin-top on thumb-label sliders

### Reproduction Link

https://codepen.io/kdholt34/pen/RBzejK?editors=1010

**Comment by johnleider** [comment]
Resolved by #4899
