### ISSUE TITLE
[Bug Report] IE11 v-select in data-table footer is too tall

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#4892]
### Versions and Environment
**Vuetify:** 1.1.13
**Vue:** 2.5.17
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Go to the data table component page on vuetifyjs.com using Internet Explorer 11 and scroll to an example that shows the Rows per page data table action with a v-select.

### Expected Behavior
The dropdown arrow & number should be closer to the underline.
![image](https://user-images.githubusercontent.com/1302542/44229783-1d4ba400-a167-11e8-864a-fb25185b9c28.png)

### Actual Behavior
The v-select is too tall.
![image](https://user-images.githubusercontent.com/1302542/44229761-05742000-a167-11e8-965f-21b59f630c00.png)

### Reproduction Link
[https://codepen.io/anon/pen/JBQmXg](https://codepen.io/anon/pen/JBQmXg)

**Comment by 06b** [comment]
Coworker: "How fast has the vuetify team been in responding to any bugs you create?"
Me: "Pretty Quick"

![image](https://user-images.githubusercontent.com/1302542/44231723-158efe00-a16d-11e8-96bb-92ed734eddf2.png)

👍

**Comment by KaelWD** [comment]
It's automated lol.

**Comment by 06b** [comment]
I figured but it's still pretty accurate, one issue I created was fixed seven hours before I reported it. XD

Keep up the awesome work!
