### ISSUE TITLE
Data table sorting does not work, the result is incorrect. 

### ISSUE THREAD

**Issue by poweron707** [vuetifyjs/vuetify#4894]
### Versions and Environment
Vuetify: v1.11.1
Vue: v2.5.17
Browsers: Google Chrome Version 68.0.3440.106, Firefox Quantum 61.0.2
OS: Windows 10

### Previously worked in:
Vuetify: 
Vue: 

### Steps to reproduce

Data Table sorting feature is not work. The result will change randomly. 

### Reproduction Link

Refer to official examples of Data Table : https://vuetifyjs.com/en/components/data-tables#introduction , click "Fat(g)" sorting more than 3 times
---

**Comment by KaelWD** [comment]
Looks fine to me, it toggles between ascending/descending/unsorted. Use the `must-sort` prop to change this behaviour.
