### ISSUE TITLE
[Feature Request] VEditDialog: Add hover option

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#4896]
### What problem does this feature solve?
A table row might serve as a route, therefore, a click on the row triggers the router. The `VEditDialog` is activated by a click. To still provide an edit dialog, it should be possible to show the dialog while hovering.

### What is your proposed solution?
I made a [merge request](https://github.com/vuetifyjs/vuetify/pull/4895).

**Comment by KaelWD** [comment]
You can use `@click.native.stop` to prevent activating the link.

**Comment by ndabAP** [comment]
@KaelWD thanks for your proposal. Could you show me a quick example?

I have a table where a row servers as a route. A cell should be editable, too.

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/ajerae?editors=1010

**Comment by ndabAP** [comment]
Thanks a lot! Much better than my solution with an event that checks for an `a` tag.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/4895#issuecomment-417944126
