### ISSUE TITLE
not visible as should "hidden-sm-and-down" 

### ISSUE THREAD

**Issue by JaniSavolainen** [vuetifyjs/vuetify#490]
Reporting a bug?
================
  <v-toolbar>
      <v-toolbar-side-icon class="hidden-sm-and-up"></v-toolbar-side-icon>
      <v-toolbar-title class="hidden-sm-and-down">Toolbar</v-toolbar-title>
  <v-spacer></v-spacer>
  <v-btn icon dark>
    <v-icon>account_circle</v-icon>
  </v-btn>
  <v-btn icon dark>
    <v-icon>favorite</v-icon>
  </v-btn>
  <v-btn icon dark>
    <v-icon>more_vert</v-icon>
  </v-btn>
</v-toolbar>

Title shows correctly at 768px and up, but menu becomes visible at  576px and down. Should it be the same?

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by JaniSavolainen** [comment]
```
<v-toolbar>
  <v-toolbar-side-icon class="hidden-sm-and-up"></v-toolbar-side-icon>
  <v-toolbar-title class="hidden-sm-and-down">Toolbar</v-toolbar-title>
  <v-spacer></v-spacer>
  <v-btn icon dark>
    <v-icon>account_circle</v-icon>
  </v-btn>
  <v-btn icon dark>
    <v-icon>favorite</v-icon>
  </v-btn>
  <v-btn icon dark>
    <v-icon>more_vert</v-icon>
  </v-btn>
</v-toolbar>
```
this was my code and sorry. Had code there but forgot to click "insert code". there are space when both title and icon are not visible.

**Comment by JaniSavolainen** [comment]
[link to plunker](https://plnkr.co/edit/lFuEZK?p=preview)

**Comment by mornir** [comment]
I think what you're looking for is:
` 
<v-toolbar-side-icon class="hidden-sm-and-up"></v-toolbar-side-icon>
<v-toolbar-title class="hidden-xs-only">Toolbar</v-toolbar-title>
`

**Comment by JaniSavolainen** [comment]
thank you. it worked well. You are doing great work. Takes off the hat and bends.
