### ISSUE TITLE
v-autocomplete items container does not match the textfield's width

### ISSUE THREAD

**Issue by siegy22** [vuetifyjs/vuetify#4901]
### Versions and Environment (yarn list local --pattern vuetify)
Vuetify: vuetify@1.1.12
Vue: vue@2.5.16
Browsers: Chrome 70
OS: Mac OS X 10.13.5

### Previously worked in:
Vuetify: - 
Vue: -

### Reproduction Link
https://codepen.io/anon/pen/qyeXoJ

### Steps to reproduce

- Create a `v-autocomplete` with items which take more space than the textfield's width.
- Open the autocomplete's menu.

### Expected Behavior
In [the material guide](https://material.io/design/components/menus.html#exposed-dropdown-menu) (point "Text field dropdown menu") I can see that it should match the min-width of the activator. Apparently I can't find any example on how it should behave when an item is too large, my assumption is, to still match the width of the activator.

Always match the width of the activator. Resulting in a text overflow of the items which are too long.
Here's my workaround right now: https://codepen.io/anon/pen/XBveXx

### Actual Behavior
Only matches the min-width of the activator.

---
Thanks very much for all your work on vuetify, I really appreciate it.

**Comment by siegy22** [comment]
Apparently the material guide specifies the max width of a menu to be 280dps.
https://material.io/design/components/menus.html#specs

What do you think should be the correct behavior here?

**Comment by johnleider** [comment]
That's from the new spec, and either way, it's a fix that has side-effects. Applying a maximum width (which we can do) would absolutely destroy mobile use-cases. This is something that I think we will need to leave for user-land.
