### ISSUE TITLE
Can't vertically center correctly in a v-toolbar

### ISSUE THREAD

**Issue by kaminilsen** [vuetifyjs/vuetify#4904]
I am trying to center an image vertically in a v-toolbar.  I have tried multiple approaches and don tons of research but haven't been able to find a way to make it work correctly.  This is the closest I've gotten, but the image still isn't quite vertically centered.

**EDIT
I need to be able to display multiple other buttons in the toolbar as well (center and right-justified), which is why I am placing the image in a v-flex.  It's the nesting in the toolbar that seems to break the vertical alignment

### Versions and Environment
Vuetify: 1.1.12
Vue: 2.5.17
Browsers: Chrome
OS: Windows 10

### Steps to reproduce

NA

### Expected Behavior
I would expect the image to be centered vertically

### Actual Behavior
The image is shifted up
![image](https://user-images.githubusercontent.com/42477572/44282926-e08cb500-a219-11e8-8df5-0806cae0e741.png)

### Reproduction Link
https://codepen.io/kaminilsen/pen/OwKZZP

**Comment by jacekkarczmarczyk** [comment]
Like this https://codepen.io/anon/pen/wxVRev?editors=1000?

**Comment by KaelWD** [comment]
Or if you actually need all that extra markup for some reason: https://codepen.io/anon/pen/PBMvVK?editors=1010

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
