### ISSUE TITLE
Menu transitioning strangely

### ISSUE THREAD

**Issue by jamesxv7** [vuetifyjs/vuetify#491]
### Steps to reproduce
- Click the button to show the menu and then double click the button

### Versions

- vue 2.2.6
- vuetify 0.11.0
- OS Win X
- Chrome, Firefox, IE Edge

### What is expected ?

Menu displayed below button

### What is actually happening ?

Menu floating across the button sometimes across the screen

### Reproduction Link

http://codepen.io/jamespr/pen/mmMmaj

Note: A similar [issue](https://github.com/vuetifyjs/vuetify/issues/398) was reported for a menu inside a toolbar. This one occurs when no toolbars are present.

**Comment by johnleider** [comment]
This was fixed with #398.
