### ISSUE TITLE
[Bug Report] clipped v-navigation-drawer not rest under the toolbar

### ISSUE THREAD

**Issue by jk2K** [vuetifyjs/vuetify#4911]
### Versions and Environment
Vuetify: 1.1.13
Vue: 2.5.17
Browsers: Chrome 68
OS: Windows 10 1803

### Expected Behavior

![image](https://user-images.githubusercontent.com/4025839/44307291-6b181480-a3d2-11e8-84d3-c5d934cde45a.png)

clipped drawer rests under the application toolbar

### Actual Behavior

![image](https://user-images.githubusercontent.com/4025839/44307281-3b690c80-a3d2-11e8-99fe-bcde0bc21578.png)

clipped drawer not rests under the application toolbar

### Reproduction Link

https://codepen.io/jk2k/pen/bxbWQo
---

**Comment by KaelWD** [comment]
This is intentional, drawers should not clip on mobile.

**Comment by gorbypark** [comment]
Any way to enable clipping on non-mobile browsers?

**Comment by tarikhamilton** [comment]
I thought this was broken as well, but the clipping does work. The mobile layout might kick in at a breakpoint you weren't expecting. For me, it turns out my window was not large enough (I was developing with windows side-by-side).

**Comment by MarceloJoaoZanatta** [comment]
Hello!
Use mobile-break-point=0 in <navigation drawer> to resolve.
