### ISSUE TITLE
[Bug Report] Using mask with v-combobox

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#4915]
### Versions and Environment
**Vuetify:** 1.1.13
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Linux x86_64

### Steps to reproduce
Type any text to combobox

### Expected Behavior
Input should be masked

### Actual Behavior
Input is not masked

### Reproduction Link
[https://codepen.io/anon/pen/bxbYax](https://codepen.io/anon/pen/bxbYax)

**Comment by Darkside73** [comment]
Same behavior in vuetify 1.2 https://codepen.io/darkside73/pen/aabBzG

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
