### ISSUE TITLE
v-btn loading prop consume high cpu

### ISSUE THREAD

**Issue by benoit-ponsero** [vuetifyjs/vuetify#4918]
### Versions and Environment

Vuetify:1.1.3
Vue:2.5.16
Browsers:chrome
OS:mac

### Steps to reproduce
set loading prop to true and check your cpu load.

### Expected Behavior
It should not consume cpu.

**Comment by KaelWD** [comment]
#553, #720, #785, https://github.com/vuetifyjs/vuetify/issues/2324#issuecomment-340226923
