### ISSUE TITLE
v-pagination - value property broken

### ISSUE THREAD

**Issue by storycoding** [vuetifyjs/vuetify#4920]
### <v-pagination :value>
I couldn't work it out on my repo, so I checked the vuetify docs (https://vuetifyjs.com/en/components/paginations) for the reference codepen

I edited the original by adding the :value=3 property to the <v-pagination> component and the default highlighted / value doesn't change

here's my example:
https://codepen.io/storycoding/pen/gdOPWQ

**Comment by KaelWD** [comment]
v-model *is* value, you can't use both.

**Comment by storycoding** [comment]
Hi @KaelWD,

I'm sorry,  but your answer doesn't really make sense to me, could you elaborate a bit more ? 

Thank you

**Comment by nekosaur** [comment]
`v-model="page"` is syntactic sugar for `:value="page" @input="page = $event"`. So by adding `:value="3"` you're essentially trying to add the `value` prop twice.

https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

**Comment by storycoding** [comment]
Hi @nekosaur,

Thank you for clarifying!

It might be worth adding that detail to the docs...

**Comment by jacekkarczmarczyk** [comment]
That's the Vue thing and it is mentioned in the Vue docs
