### ISSUE TITLE
[Feature Request] Time period picker

### ISSUE THREAD

**Issue by ArturFormella** [vuetifyjs/vuetify#4925]
### Problem to solve
Input for picking the period of time. For example:
"2 days, 1 hour and 12min"

### Proposed solution
Configurable input for the following list of periods: year, month, week, day, hour, minute, second, millisecond.
Example: https://www.jqueryscript.net/images/Minimal-Duration-Picker-Plugin-For-jQuery-Bootstrap.jpg

**Comment by KaelWD** [comment]
Duplicate of #2763
