### ISSUE TITLE
Provide a way to control autocomplete's flyout's color properties

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#4926]
### What problem does this feature solve?
It is possible to control various combinations of the text and background colours for v-autocomplete through a combination of:
- light / dark modes - which control the the default text / icon / background colours for the text field and the colours used by the flyout 
- The color prop controls the text and icon colors for the textfield when selected
- The background-color prop sets the color of the text-box background

However, there are cases where it works better for the flyout to have a light or a dark scheme instead of the default, but there is no way to set this.

For example, in dark mode, v-autocomplete's text-field uses light text on a dark-background, and the flyout also uses light text on a dark-background, which can cause contrast issues against dark page backgrounds. In these cases, dark-text on a white background would work better for the flyout. 

### What is your proposed solution?
Either add a flyout-color and flyout-background-color prop, or add a flyout-color-invert prop.

**Comment by KaelWD** [comment]
#4795
