### ISSUE TITLE
Select component is cut off by sidebar

### ISSUE THREAD

**Issue by Sarpedion** [vuetifyjs/vuetify#493]
Select component, when placed in a card, and when there is a fixed sidebar is being cut off by sidebar.
[Codepen](http://codepen.io/Sarpedion/pen/yboojq)

![image](https://cloud.githubusercontent.com/assets/16826299/25694742/45ce1742-30b0-11e7-8a44-8baf5b824f29.png)

**Comment by johnleider** [comment]
I'm not sure how much of a bug this is. Yes, it is clipped under the sidebar, but the sidebar is a fixed element and the menu is relative to its parent, and non fixed. With that being said, in dev branch, the menu has a naturally higher z-index than the sidebar and this problem does not occur.
