### ISSUE TITLE
[Bug Report] Autocomplete sends another request when clicking item

### ISSUE THREAD

**Issue by full-stack-solutions** [vuetifyjs/vuetify#4935]
### Versions and Environment
**Vuetify:** 1.1.13
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
Search the autocomplete and click an item, another request is sent and the list re-opens

### Expected Behavior
Search the autocomplete and click an item and the list should close with no more requests

### Actual Behavior
Search the autocomplete and click an item, another request is sent and the list re-opens

### Reproduction Link
[https://codepen.io/mattstudios/pen/pOvYJd](https://codepen.io/mattstudios/pen/pOvYJd)

**Comment by KaelWD** [comment]
You should check for search being an empty string before making a request, The menu opening on items change is already reported: #4663
