### ISSUE TITLE
[Feature Request] Support v-html inside v-textarea

### ISSUE THREAD

**Issue by elyase** [vuetifyjs/vuetify#4937]
### Problem to solve
The current v-textarea doesn't allow for customizations like highlighting parts of the text.

In this example:

https://codepen.io/anon/pen/rZVBGz

we see that the component stops being editable as soon as `v-html` is used.

### Proposed solution
Add support for Vue's v-html mechanism to insert raw html.

**Comment by KaelWD** [comment]
Not possible. You probably want a rich text editor like quill.
