### ISSUE TITLE
[Feature Request] tab preview within hammer.js

### ISSUE THREAD

**Issue by SuperDoudou** [vuetifyjs/vuetify#4939]
as native app do, when drag tab it can preview the next tab ,
maybe vuetify could expose a value control the tab position, especially on the middle state

maybe like this
![image](https://user-images.githubusercontent.com/32198499/44506261-20e7a980-a6d8-11e8-926e-0dfa0eb65309.png)

**Comment by KaelWD** [comment]
It's in the pipeline already.
