### ISSUE TITLE
<v-text-field> input v-on:keyup not working

### ISSUE THREAD

**Issue by weimingwill** [vuetifyjs/vuetify#494]
Refer to this http://codepen.io/wingalong/pen/MmvzYK

`<v-text-field>` input `v-on:keyup` not working. While it is working by using the original <input>

**Comment by mornir** [comment]
Use `v-on:keyup.native` or `@keyup.native`

https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events
