### ISSUE TITLE
[Bug Report] V-autocomplete delete item with Backspace key is flawed

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#4940]
### Versions and Environment
Vuetify: 1.1.13

### Steps to reproduce

Just select an option then try to remove it using Backspace.

### Expected Behavior

The option should be deleted as soon as I click once.

### Actual Behavior

I have to press 3 times the Backspace button.

### Reproduction Link

https://codepen.io/Kleemer/pen/GXJxar

---

### Additional Comments:
Adding the 'multiple' props shows a behaviour that could explains what is happening. In that case, pressing Backspace the first time select the element on the left of the caret, and a second press is needed to delete the element, maybe something like this is happening behind the scenes ?

**Comment by chewy94** [comment]
I am not able to reproduce on Chrome using the codepen provided. After selecting an item I press backspace and I immediately start removing letters from the selected item

**Comment by KaelWD** [comment]
1. Select an item
2. Blur the field
3. Focus the field
4. Press backspace
5. Blur the field

Now try again but do step 4 three times

**Comment by Anima-t3d** [comment]
Issue still persists in v1.5.x, in v1.0.x using v-select this was not an issue.

**Comment by johnleider** [comment]
This is working as of v2.2.26.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
