### ISSUE TITLE
[Bug Report] Tab slider does not show when inside dialog

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#4943]
### Versions and Environment
**Vuetify:** 1.1.14
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Include `<v-tab>` inside a `<v-dialog>` and open the dialog

### Expected Behavior
Slider should appear for the first active tab when the dialog has opened

### Actual Behavior
Slider does not appear until another tab has been clicked on and then it will show on whatever is the active tab

### Reproduction Link
[https://codepen.io/anon/pen/NLGGPN](https://codepen.io/anon/pen/NLGGPN)

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1978
