### ISSUE TITLE
[Feature Request] v-expansion-panel - readonly attribute added to header slot

### ISSUE THREAD

**Issue by tonyhayes** [vuetifyjs/vuetify#4945]
### Problem to solve
My application has a very large list of items. If an item is programmatically opened that is off the screen, it cannot be viewed without the user scrolling to find the open expansion panel item. My workaround is - whether an item is clicked or programmatically opened - is to recreate the list with the selected item as the first item in the list - and then open this item programatically.

I can do this using nextTick() on an item that is clicked on, to close the expansion panel - but it still opens for a split second.

### Proposed solution
Ideally, you would have an attribute to always open programmatically (you would ignore the click) or add a readonly attribute to the header - I only want the first item to be expandable.

Another option would be to open at top - so whatever is selected would always be the first item in the list - or scroll to the top whatever is open. I've experimented with that and it is too variable, and doesn't seem to work .

**Comment by KaelWD** [comment]
Both of those are already possible

> add a readonly attribute

https://vuetifyjs.com/en/components/expansion-panels#example-disabled-and-readonly

> scroll to the top whatever is open

https://github.com/vuetifyjs/vuetify/issues/3947#issuecomment-384902926

**Comment by tonyhayes** [comment]
thank you
