### ISSUE TITLE
[Bug Report] Expansion panel content header spills out of container in smaller screen sizes if it is long

### ISSUE THREAD

**Issue by acwwat** [vuetifyjs/vuetify#4947]
### Versions and Environment
**Vuetify:** 1.1.14
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
With the expansion panel, when the content header is long (e.g. a question in FAQ), the header would spill out of the title box in smaller screen sizes, overlapping with other items in the panel. To reproduce the problem, use the CodePen link I provided and shrink your browser size down.

### Expected Behavior
Header would not spill out of box but will instead adjust the box size to fit the header.

### Actual Behavior
Header spills out of box.

### Reproduction Link
[https://codepen.io/acwwat/pen/mGeBja](https://codepen.io/acwwat/pen/mGeBja)

**Comment by acwwat** [comment]
As a workaround, I overrode .v-expansion-panel__header with a higher height based on media query. But this is very specific to my data/usage.

<style>
@media (max-width: 767px) {
  .v-expansion-panel__header {
    height: 72px !important;
  }
}
@media (max-width: 480px) {
  .v-expansion-panel__header {
    height: 96px !important;
  }
}
</style>

**Comment by johnleider** [comment]
This is resolved for v2.0 https://github.com/vuetifyjs/vuetify/pull/4933

**Comment by jacekkarczmarczyk** [comment]
This is fixed in 2.0 https://codepen.io/anon/pen/WqrmeV
