### ISSUE TITLE
[Bug Report] VDataTable expand slot doesn't work with normal element

### ISSUE THREAD

**Issue by lzhoucs** [vuetifyjs/vuetify#4948]
`expand` slot can't be used on normal elements.

### Versions and Environment
Vuetify: https://unpkg.com/vuetify@1.1.14/dist/vuetify.min.js
Vue: https://unpkg.com/vue@2.5.17/dist/vue.js
Browsers: Version 68.0.3440.106 (Official Build) (64-bit)
OS: macos 10.13

### Steps to reproduce

* Go to https://codepen.io/lzhoucs/pen/mGeBqz
* Click rows on the first table to expand, it works
* Click rows on the 2nd table to expand, it doesn't work

### Expected Behavior

The 2nd table rows expand should work, as vue supports slots on normal elements: https://vuejs.org/v2/guide/components-slots.html

### Actual Behavior
The 2nd table rows are not expandable

### Reproduction Link
Go to https://codepen.io/lzhoucs/pen/mGeBqz

### Additional Comments:
On the other hand, `items` slots work with normal elements in real projects, but not on codepen. For example, with the link above, the table brearks as soon as `items` slot is changed to the following to remove `template`:
```
        <tr slot="items" slot-scope="props" @click="props.expanded = !props.expanded">
          <td>{{ props.item.name }}</td>
          <td>{{ props.item.calories }}</td>
        </tr>
```
but it works in real projects with the same vue/vuetify version. Not sure if it is related to the `expand` slot issue.

**Comment by KaelWD** [comment]
This is why typescript is good, that needs to be an array. First is template, second is bare span: 
![image](https://user-images.githubusercontent.com/16421948/44564088-9751dd80-a7a4-11e8-8222-e78841ef9c4c.png)
