### ISSUE TITLE
v-text-field with datpicker does not use full width

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#495]
### Versions
Vue 2.3
vuetify 0.11.1
chrome 57.0.2987.133 on windows 10

### What is expected ?
the text-field of the date-picker should use the full width of the card

### What is actually happening ?
the text-field of the date-picker has a fixed width

### Reproduction Link
http://codepen.io/kpilard/pen/eWEQdB
![example](https://cloud.githubusercontent.com/assets/19437859/25697159/229c3f38-30ba-11e7-8e61-e41e41c542fe.PNG)

**Comment by johnleider** [comment]
The fixed width is intentional. You can modify this with css if you want, but I have no plans of making them full width.
