### ISSUE TITLE
[Feature Request] Extend themes to --border and color alpha

### ISSUE THREAD

**Issue by agnjunio** [vuetifyjs/vuetify#4950]
### Problem to solve
There are two issues to be tackled:
- We need a way to set border colors differently from background color (example, primary border and secondary background-color)
- Allows developers to set alpha channel to theme colors without appealing to third party libs like [tinycolor ](https://github.com/bgrins/TinyColor)

### Proposed solution
- Give a suffix --border to customize the color of the border just like in text (eg: `class='secondary primary--border'`)
- Assuming `primary=#CCCCC`, give all classes a suffix alpha-% (eg: `class=primary-alpha-%` will produce `rgba(204, 204, 204, 0.05)` as final result)

**Comment by KaelWD** [comment]
This is two features, and one of them is already possible. 

```js
Vue.use(Vuetify, {
  theme: {
    primary: {
      base: '#CCC'
      alpha1: 'rgba(204, 204, 204, 0.05)'
    }
  }
})

<div class="primary alpha-1">
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
