### ISSUE TITLE
[Bug Report] autofocus does not work for Checkboxes, Radios

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#4951]
### Problem to solve
Currently (1.1.14) some of the Vuetify inputs support the 'autofocus' attribute, yet Checkboxes and Radios do not.  It would be ideal if all input controls supported this feature (I'm not sure if there are any others as well lacking this).

### Proposed solution
Implement the 'autofocus' attribute for all input controls.

**Comment by johnleider** [comment]
This did not make the cut for v1.3, going to mark as help wanted if anyone wants to take a stab at it.
