### ISSUE TITLE
[Bug Report] Position of visible VMenu not changes when position-x prop changes

### ISSUE THREAD

**Issue by dima74** [vuetifyjs/vuetify#4956]
### Versions and Environment
Vuetify: 1.1.14
Vue: 2.5.17
Browsers: Chrome 68.0.3440.106
OS: Linux

### Steps to reproduce

Create `<v-menu>` without activator, open menu, then change `position-x` prop of menu

### Expected Behavior
Position of menu will change

### Actual Behavior
Position of menu will not change

### Reproduction Link
https://codepen.io/dima74/pen/qMbPzp

**Comment by KaelWD** [comment]
No idea why this isn't a computed property: https://github.com/vuetifyjs/vuetify/blob/dev/src/mixins/menuable.js#L156

Menus are a bit of a mess tbh, maybe that'll be our focus for 1.4
