### ISSUE TITLE
[Bug Report] Nuxt -- theme: false wipes html head elements

### ISSUE THREAD

**Issue by zerosym** [vuetifyjs/vuetify#4958]
### Versions and Environment
Vuetify: Latest
Vue: Latest
Browsers: Any
OS: Any

Doing the following in Nuxt causes Nuxt to wipe all elements with  `data-n-head` attributes.
```
Vue.use(Vuetify, {
  theme: false,
})
```

## Example
**theme: {...}**
![normal](https://user-images.githubusercontent.com/20721797/44623433-b030c080-a882-11e8-85ff-abebedb373e1.PNG)

**theme: false**
![wiped](https://user-images.githubusercontent.com/20721797/44623432-af982a00-a882-11e8-960f-7627c6f604d8.PNG)

## The Issue / Fix
vueMeta computed value returns undefined when theme is false.  

https://github.com/vuetifyjs/vuetify/blob/dabaaa941f6fa8edaee511ef2dcd9913c1d066d8/src/components/VApp/mixins/app-theme.js#L35

https://github.com/vuetifyjs/vuetify/blob/dabaaa941f6fa8edaee511ef2dcd9913c1d066d8/src/components/VApp/mixins/app-theme.js#L60

Returning an empty object rather than undefined fixes this.

**Comment by KaelWD** [comment]
You should probably report this to [vue-meta](https://github.com/declandewet/vue-meta/issues) too.

**Comment by alfredriesen** [comment]
vuetify schould return an empty Object instead of simply return:
`if (this.$vuetify.theme === false) return {}`
and not 
`if (this.$vuetify.theme === false) return`
Then it schould work.
