### ISSUE TITLE
All toolbar inside of fullscreen dialog get position fixed top

### ISSUE THREAD

**Issue by bunnypro** [vuetifyjs/vuetify#496]
### Steps to reproduce
Create some toolbar inside of fullscreen dialog/modal

### Versions
v0.11.1

### What is expected ?
only dialog toolbar that has fixed top toolbar.

### What is actually happening ?
All toolbar inside of fullscreen dialog get position fixed top

**Comment by mornir** [comment]
In my opinion, dialogs shouldn't contain more than one toolbar. Dialogs are to be used for specific tasks and shouldn't get too complex. Also, according to material specs:

> Dialogs should avoid containing scrolling content.
https://material.io/guidelines/components/dialogs.html#dialogs-behavior

**Comment by johnleider** [comment]
Could you not achieve this with some custom css? It seems more like your use case than something within the spec that we missed.

**Comment by bunnypro** [comment]
i tought it was a bug. since @mornir mentioned above i think i'll use custom css.

the use case is when i create a card with transparent toolbar inside of fullscreen dialog.
i fixed it with customize the toolbar position to `relative`.
