### ISSUE TITLE
Selectable groups of components

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#4960]
Common baseline functionality for:
- v-radio-group
- v-btn-toggle
- v-carousel
- v-tabs-items
- v-stepper
- v-expansion-panel
- [choice/filter chips](https://material.io/design/components/chips.html#usage) (MD2)

Some of these may have multiple selections, with the exception of radios, steppers, carousel, and tabs.

**Comment by johnleider** [comment]
Expansion panel and stepper was skipped in the update due to backwards compatibility issues. They will be handled in the v2.0 update.
