### ISSUE TITLE
[Feature Request] Avoid importing globally Vuetify in all tests

### ISSUE THREAD

**Issue by trollepierre** [vuetifyjs/vuetify#4964]
### Versions and Environment
Vuetify: ^1.1.11
Vue: 2.5.16
Browsers: all
OS: all

### Previously worked in:
Vuetify: ^1.1.10
Vue: 2.5.16

### Steps to reproduce

Since Vuetify version 1.1.11, developers have to import globally Vuetify in all tests to avoid having 2 multiples Vue instances running (and see a warning referring to #4068 ) 
```
localVue.use(Vuetify)
```
has been replaced by 
```
Vue.use(Vuetify)
```

### Expected Behavior

Using localVue is better because it prevents polluting the original Vue copy during tests.
I expect Vuetify not to use its own instance of Vue.
So I can come back using only `localVue.use(Vuetify)` in all of my tests

### Actual Behavior

I had to use `Vue.use(Vuetify)` in each of my test files

### Reproduction Link

https://codesandbox.io/s/mz86zx5vnj

**Watch the warnings generated by the test**
---

**Comment by johnleider** [comment]
We need to put together some testing documentation so that this is more clear.

**Comment by AtofStryker** [comment]
Related to the same issue. When switching from 
```
localVue.use(Vuetify)
```
to
```
Vue.use(Vuetify)
```

I have an issue when any watcher is triggered in my tests. A range Maximum callstack exceeded is triggered and the test fails. Has anyone else experienced this?

Also, should I open a separate issue for this? I can make a reproduction link if needed.

**Comment by johnleider** [comment]
Please create a separate issue @AtofStryker

**Comment by AtofStryker** [comment]
Actually looks like my issue is related to https://github.com/vuejs/vue-test-utils/issues/647 for any who are interested. Will wait @johnleider for more testing documentation

**Comment by KaelWD** [comment]
> I expect Vuetify not to use its own instance of Vue

We can't, see https://github.com/vuejs/vue/issues/8278. It might be possible to hack something together with `require.cache`, but I haven't tried.

**Comment by m4ss1m0g** [comment]
Vuetify 1.5.0
Vue 2.6.2

It is still an issue

**Comment by stas-kh** [comment]
This is super confusing, guys.
Any updates here?

**Comment by boutils** [comment]
Same here, I can't find a way to test my project correctly. @johnleider Do we have a documentation somewhere that can give us some exemples to test our projects properly?

**Comment by eddie-craftsmanshipcounts** [comment]
Any idea if this will be addressed? And, if so, when? It's kind of a big deal to those of us who take testing seriously.

Thanks in advance for any feedback. And, more than that, thanks for giving us such a remarkable, feature-rich material implementation!

**Comment by m4ss1m0g** [comment]
I found the reason of the error.

When you create a _local_ Vue with function `createLocalVue` you create a **VueComponent**.
On the startup of Vuetify there is an `if` where it validates the Vue loaded (internally) with the Vue passed from the installation; [here the source](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/Vuetify/index.ts#L23)

```
if (OurVue !== Vue) {
      consoleError('Multiple instances of Vue detected\nSee https://github.com/vuetifyjs/vuetify/issues/4068\n\nIf you\'re seeing "$attrs is readonly", it\'s caused by this')
}
```

Whit debug I saw this (pseudocode):

`if ([Function: Vue] !== [Function: VueComponent])`

See also #4068

**Comment by MerrySean** [comment]
I do have a solution. (but it depends on what you are going to test)

 
```
import { shallowMount, createLocalVue } from "@vue/test-utils";
import VueRouter from "vue-router";

import web from "@/views/layouts/web/index.vue";
import sidebar from "@/views/layouts/web/components/SSidebar.vue";
import navbar from "@/views/layouts/web/components/SNavbar.vue";

describe("layouts/web/index.vue", () => {
  let wrapper;
  let localVue;
  beforeAll(() => {
    localVue = createLocalVue();
    localVue.use(VueRouter, {});
    wrapper = shallowMount(web, {
      localVue,
      stubs: {
        VApp: "<div></div>"
      }
    });
  });

  it("Renders Sidebar", () => {
    expect(wrapper.exists(sidebar)).toBe(true);
  });

  it("Renders Navbar", () => {
    expect(wrapper.exists(navbar)).toBe(true);
  });
});

```

**Comment by Mei152** [comment]
Having same issue in rails
vue 2.6.7
vuetify 1.5.14

`[Vuetify] Multiple instances of Vue detected`

**Comment by slushnys** [comment]
How do I test a component currently if I use vuetify in almost every one of them? Do I have to shadowMount it in every test with 'localVue.use(vuetify)' when wanting to pass custom properties? That doesn't sound so good.

**Comment by johnleider** [comment]
An update on this issue. Currently with how we must extend the Vue object in order to have proper typescript support, you will have to bootstrap Vue in your test setup file:

```
// tests/setup.js
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)
```

I have dropped the ball on providing clear documentation on how to do this and for that I apologize. This is something that I will be adding to the documentation in the coming weeks for the next version.

In regards to a long term solution, I'm accepting any and all suggestions on how to accommodate typescript support while also enabling the bootstrapping of `localVue`.

**Comment by iwko** [comment]
Any progress on this?

**Comment by JohanSantamaria17** [comment]
Thanks @johnleider it worked fine 👍 


> An update on this issue. Currently with how we must extend the Vue object in order to have proper typescript support, you will have to bootstrap Vue in your test setup file:
> 
> ```js
> // tests/setup.js
> 
> import Vue from 'vue'
> import Vuetify from 'vuetify'
> 
> Vue.use(Vuetify)
> ```
> 
> I have dropped the ball on providing clear documentation on how to do this and for that I apologize. This is something that I will be adding to the documentation in the coming weeks for the next version.
> 
> In regards to a long term solution, I'm accepting any and all suggestions on how to accommodate typescript support while also enabling the bootstrapping of `localVue`.

**Comment by WaldemarEnns** [comment]
A great "thank you" from my side too - @johnleider , it works for me too :) Any progress on delivering a solution in the new version?

**Comment by johnleider** [comment]
This will be resolved as of our v3 upgrade to Vue3.

**Comment by jatin-maropost** [comment]
> An update on this issue. Currently with how we must extend the Vue object in order to have proper typescript support, you will have to bootstrap Vue in your test setup file:
> 
> ```js
> // tests/setup.js
> 
> import Vue from 'vue'
> import Vuetify from 'vuetify'
> 
> Vue.use(Vuetify)
> ```
> 
> I have dropped the ball on providing clear documentation on how to do this and for that I apologize. This is something that I will be adding to the documentation in the coming weeks for the next version.
> 
> In regards to a long term solution, I'm accepting any and all suggestions on how to accommodate typescript support while also enabling the bootstrapping of `localVue`.

Thanks @johnleider  It worked.

**Comment by bennysalewski** [comment]
I use following workaround:
``` javascript
describe('test', () => {
    let localVue = null;

    beforeEach(() => {
        localVue = require('vue');
        localVue.use(Vuex);
        localVue.use(Vuetify);
    });

    afterEach(() => {
        localVue = null;
    });

    it('hello world', () => {
        const wrapper = shallowMount(ConfirmAction, {
            localVue,
            vuetify: new Vuetify({})
        });

        expect(wrapper.text()).toMatch('Hello World!');
    });
});
```

So I can use the global Vue instance but because I dynamically require it in beforeEach, I retrieve always a new one.

**Comment by KaelWD** [comment]
Nodejs caches modules, if you aren't clearing the module cache that's the same as just doing it once at the top of the file.

**Comment by bennysalewski** [comment]
Yeah, bad first draft. If you use jest (vue test utils use it anyways) and based on this: [https://stackoverflow.com/questions/60735880/reset-vue-for-every-jest-test](https://stackoverflow.com/questions/60735880/reset-vue-for-every-jest-test). You can do this:

**Utils:**
``` javascript
export const addVuetify = context => {
  context.vuetify = require('vuetify');
  context.vue.use(context.vuetify);
  context.vuetifyInstance = new context.vuetify();
};

export const addVuex = context => {
  context.vuex = require('vuex');
  context.vue.use(context.vuex);
};

export const addI18n = options => {
  return context => {
    context.i18n = require('vue-i18n');
    context.vue.use(context.i18n);
    context.i18nInstance = new context.i18n(options);
  };
};

export const addFilter = (name, lambda) => {
  return context => context.vue.filter(name, lambda);
};

export const compositeConfiguration = (...configs) => {
  return context => configs.forEach(config => config(context));
};

export const bootstrapVueContext = configureContext => {
  const context = {};
  const teardownVueContext = () => {
    jest.unmock('vue');
    Object.keys(context).forEach(key => delete context[key]);
    jest.resetModules();
  };

  jest.isolateModules(() => {
    context.vueTestUtils = require('@vue/test-utils');
    context.vue = context.vueTestUtils.createLocalVue();

    jest.doMock('vue', () => context.vue);

    configureContext && configureContext(context);
  });

  return {
    teardownVueContext: teardownVueContext,
    ...context
  };
};
```

**Usage:**

``` javascript
describe('test', () => {
  let vueContext = null;

  beforeEach(() => {
    vueContext = bootstrapVueContext(
      compositeConfiguration(addVuex, addVuetify)
    );
  });

  afterEach(() => {
    vueContext.teardownVueContext();
  });

  it('hello world', () => {
    const wrapper = vueContext.vueTestUtils.shallowMount(HelloWorld, {
      localVue: vueContext.vue,
      vuetify: vueContext.vuetifyInstance
    });

    expect(wrapper.text()).toMatch('Hello World!');
  });
});
```

**Comment by gadelkareem** [comment]
I already had this set in the test setup and it works fine for the current versions https://gitlab.com/gadelkareem/skeleton/-/blob/master/src/frontend/test/_setup.js#L6
```
import Vue from 'vue'
import Vuetify from 'vuetify'
import Vuex from 'vuex'
import VueRouter from 'vue-router'

Vue.use(Vuetify)
```

However, if I upgrade I get `TypeError: Cannot read property 'component' of undefined` errors 
example failing test: https://gitlab.com/gadelkareem/skeleton/-/blob/master/src/frontend/src/components/base/__tests__/Alert.spec.js#L4
```
import { mount } from '@vue/test-utils'
import Alert from '../Alert'

describe('Alert.vue', () => {
  it('should have a custom error and match snapshot', () => {
    const w = mount(Alert, {
      propsData: {
        errors: [{ title: 'test error' }]
      }
    })

    expect(w.html()).toMatchSnapshot()

    const title = w.find('.v-alert__content > div')

    expect(title.text()).toBe('test error')
  })

  it('should have a custom success message', () => {
    const w = mount(Alert, {
      propsData: {
        successText: 'test success',
        success: true
      }
    })

    expect(w.find('.v-alert__content > div').text()).toBe('test success')
  })
})
```

The only way to fix it, is to reimport vuetify on the test as following:
```
import { mount } from '@vue/test-utils'
import Vuetify from 'vuetify'
import Alert from '../Alert'

const vuetify = new Vuetify()

describe('Alert.vue', () => {
  it('should have a custom error and match snapshot', () => {
    const w = mount(Alert, {
      propsData: {
        errors: [{ title: 'test error' }]
      },
      vuetify
    })

    expect(w.html()).toMatchSnapshot()

    const title = w.find('.v-alert__content > div')

    expect(title.text()).toBe('test error')
  })

  it('should have a custom success message', () => {
    const w = mount(Alert, {
      propsData: {
        successText: 'test success',
        success: true
      },
      vuetify
    })

    expect(w.find('.v-alert__content > div').text()).toBe('test success')
  })
})

```

Any idea where are these errors coming from?

**Comment by gadelkareem** [comment]
Seems like upgrading Vuetify to `2.2.12` causes this problem

**Comment by KaelWD** [comment]
Our testing documentation now shows this: https://vuetifyjs.com/en/getting-started/unit-testing/#spec-tests
