### ISSUE TITLE
[Bug Report] <v-text-field solo> is missing label

### ISSUE THREAD

**Issue by mccoyrjm** [vuetifyjs/vuetify#4967]
### Versions and Environment
**Vuetify:** 1.1.14
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
Use `<v-text-field label="LabelText" solo></v-text-field>`

### Expected Behavior
The label text should be shown by default and shift upwards when the input is focused on like how the  **regular**, **box** and **outline** styles do.

### Actual Behavior
No label is shown in the input field like the **regular**, **box** and **outline** styles.

### Reproduction Link
[https://codepen.io/anon/pen/LJNKQd](https://codepen.io/anon/pen/LJNKQd)

### Other comments
It is unclear whether this is intended design or if this is a bug. It can be argued that there are situations where having the label appear would be a nice option to have when using this style.

**Comment by KaelWD** [comment]
Labels behave like placeholders on solo fields

https://material.io/archive/guidelines/components/text-fields.html#field-variations-figure-caption-0
