### ISSUE TITLE
[Bug Report] [Safari] <v-img> with .svg files results in Unhandled Promise Rejection: EncodingError: Invalid image type.

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#4969]
### Versions and Environment
**Vuetify:** 1.2.0-beta.3
**Vue:** 2.5.17
**Browsers:** Safari 11.1.2
**OS:** Mac OS 10.13.6

### Steps to reproduce
Add `<v-img>` with `src` image that **ends with .svg**

### Expected Behavior
To display .svg image

### Actual Behavior
Results in error:
Unhandled Promise Rejection: EncodingError: Invalid image type.

### Reproduction Link
[https://codepen.io/henriq88/pen/LJZpLe](https://codepen.io/henriq88/pen/LJZpLe)

### Other comments
.svg files that don't end with ".svg" work though (see codepen for example.)

**Comment by KaelWD** [comment]
> .svg files that don't end with ".svg" work though (see codepen for example.)

That's because it's a png. Do other SVGs not work, or is it just the flaticon ones? https://codepen.io/kaelwd/pen/JaKpMY?editors=1000

Can you also show the full stack trace (from my pen, not yours) for the error?
