### ISSUE TITLE
[Bug Report] <v-tooltip> with top attribute, enter transition starts opposite of where exit transition ends

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#4971]
### Versions and Environment
**Vuetify:** 1.2.0-beta.3
**Last working version:** 1.2.0-beta.2
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Mac OS 10.13.6

### Steps to reproduce
Add `top` to `<v-tooltip>`

### Expected Behavior
`<v-tooltip top>` **slides up from the content on start**, and slides down towards the content on exit

### Actual Behavior
`<v-tooltip top>` **slides down from above content on start**, and slides down towards the content on exit

### Reproduction Link
[https://codepen.io/henriq88/pen/KxMdEg](https://codepen.io/henriq88/pen/KxMdEg)

**Comment by Gi60s** [comment]
This issue seems to be related to the transition in general, not just on tooltip. Even the example button `SLIDE Y REVERSE TRANSITION` on the website shows the incorrect behavior. https://vuetifyjs.com/en/motion/transitions#examples
