### ISSUE TITLE
Button visibility issue

### ISSUE THREAD

**Issue by bykka** [vuetifyjs/vuetify#4972]
### Versions and Environment
Vuetify: 1.1.14
Vue: 2.5.17
Browsers: Opera 55.0.2994.44
OS: Ubuntu 18.04

### Steps to reproduce
 - bind buttons property "value" to some data property with value "true"
 - change that data property value from "true" to "false"

### Expected Behavior
The button should became invisible

### Actual Behavior
The button is still visible

### Reproduction Link
https://codepen.io/anon/pen/aaZpKL

![image](https://user-images.githubusercontent.com/489997/44707594-362c5180-aaa5-11e8-84ce-355b4562e170.png)

**Comment by KaelWD** [comment]
value is literally the button's value: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-value

https://vuejs.org/v2/guide/conditional.html

**Comment by bykka** [comment]
But https://vuetifyjs.com/en/components/buttons#api says that "value" controls visibility

**Comment by nekosaur** [comment]
It's a documentation error. You're welcome to create an issue on the vuetifyjs.com repository.
