### ISSUE TITLE
[Bug Report] Pressing ENTER inside a select submits the form.

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#4974]
### Versions and Environment
Vuetify: 1.2.0
Vue: 
Browsers:
OS:

### Previously worked in:
Vuetify: 1.1.13
Vue:

### Steps to reproduce
Place a combobox inside a form with a submit button.

### Expected Behavior
Pressing `enter` creates a new item and does not submit the form.

### Actual Behavior
Pressing `enter`  submits the form.

### Reproduction Link
https://codepen.io/SeregPie/pen/rZLQRm

---

### Additional Comments:
Worked fine before I updated to 1.2.0.

**Comment by KaelWD** [comment]
This applies to v-select and v-autocomplete too.

**Comment by jacekkarczmarczyk** [comment]
Can't reproduce it in 1.3.0

**Comment by KaelWD** [comment]
I can

<https://codepen.io/anon/pen/MPVbgz?editors=1010>

**Comment by d3radicated** [comment]
Can be reproduced in the latest version v1.3.7. Is there somehow a workaround on this?

**Comment by johnleider** [comment]
No current work around to my knowledge.

**Comment by talski** [comment]
for now, I am using <form @keydown.enter.prevent>, at least it doesn't  have any strange behaviour

**Comment by d3radicated** [comment]
Found a workaround (albeit last week). Just add `@keydown.enter.native.prevent` to `v-autocomplete`.

**Comment by johnleider** [comment]
> I can
> 
> https://codepen.io/anon/pen/MPVbgz?editors=1010

After more looking into this, I believe this might be expected behavior. The same thing will happen if you use a regular text input. https://codepen.io/johnjleider/pen/ZZERRV?editors=1010

**Comment by tom-rb** [comment]
@johnleider I tested the default behavior of a select and they actually diverge. https://codepen.io/tomrb/pen/MWayMNV

I find very useful to open the dropdown with enter when navigating with the keyboard :+1:

**Comment by KaelWD** [comment]
Looks like this was fixed at some point, it doesn't happen any more in v1.5.24 or v2.3.2: https://codepen.io/kaelwd/pen/NWxvXMq?editors=1010
