### ISSUE TITLE
vertical v-divider

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#4976]
vertical v-divider isn' t looking well. It looks short.

**Here is codepen;**

https://codepen.io/navi3591/pen/EeyOLm?editors=1010

![image](https://user-images.githubusercontent.com/17800881/44746415-f8fea880-ab12-11e8-83a0-b03b9500c899.png)

**Comment by henriq-88** [comment]
You can wrap the divider with
```
<v-layout justify-center fill-height>
     <v-divider vertical></v-divider>
</v-layout>
```
