### ISSUE TITLE
v-expanssion-panel header height

### ISSUE THREAD

**Issue by etienneamiche** [vuetifyjs/vuetify#4977]
### Versions and Environment
Vuetify:1.2.0
Vue:2.5.17
Browsers:Chrome

### Previously worked in:
Vuetify:1.0.14

### Behavior
The panel header  should resize like in the 1.0.14 but the height stay the same.
i haven't found a more recent version to illustrate so maybe i am doing something wrong

Additional probleme, the panel expand if the v-btn is clicked. I don't know if it is normal (should i stopPropagation on click ?)

### Reproduction Link

1.2.0
https://codepen.io/etienneamiche/pen/JaRjZy
1.0.14
https://codepen.io/etienneamiche/pen/VGKYZG
---

**Comment by johnleider** [comment]
The first codepen link doesn't work and the second is using 1.0.9 for the javascript and 1.0.14 for the css

**Comment by etienneamiche** [comment]
My bad
v1.2.0
https://codepen.io/etienneamiche/pen/dqpyBj

it look like the 1.0.9 shows also what i would like to achieve
https://codepen.io/etienneamiche/pen/VGKYZG
