### ISSUE TITLE
slide-y-reverse-transition enter transition

### ISSUE THREAD

**Issue by Gi60s** [vuetifyjs/vuetify#4978]
### Versions and Environment
Vuetify: 1.2
Browsers: Chrome
OS: Linux

### Steps to reproduce

This bug can be seen on your production website at https://vuetifyjs.com/en/motion/transitions#examples. 

Click on the button titled `SLIDE Y REVERSE TRANSITION` and notice that it enters in from the top and exits out from the bottom.

It should be entering and exiting from the same side. See the button titled `SLIDE Y TRANSITION` for an example of correct (although opposite) behavior. The transition slides in from the top and exits out the top.

### Expected Behavior
Transition slide-y-reverse-transition should enter from the bottom.

### Actual Behavior
Transition slide-y-reverse-transition should entered from the top.

### Reproduction Link
https://vuetifyjs.com/en/motion/transitions#examples

**Comment by Gi60s** [comment]
See related issue #4971

**Comment by johnleider** [comment]
fixed in https://github.com/vuetifyjs/vuetify/commit/91f0fb3095b329bc5a9ed6160a11f76b0febf084
