### ISSUE TITLE
DataTable: changing rows per page mutates a prop, resulting in a warning

### ISSUE THREAD

**Issue by grk** [vuetifyjs/vuetify#498]
### Steps to reproduce
When the dropdown at the bottom of the table is used to change rows per page, a warning is shown by Vue:

```
"[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: 'rowsPerPage' 
(found in <Datatable>)"
```

### Versions
Vuetify 0.11.1, current master
Vue 2.3.0

### Reproduction Link
https://codepen.io/anon/pen/GmMvOp

**Comment by nekosaur** [comment]
Fixed in #516
