### ISSUE TITLE
Mention renaming of VSnackBar to VSnackbar in changelog

### ISSUE THREAD

**Issue by cars10** [vuetifyjs/vuetify#4980]
### Versions and Environment
Vuetify: 1.2.0
Vue: 2.5.16
Browsers: Chrome
OS: Arch

### Previously worked in:
Vuetify: 1.14
Vue: 2.5.16

Hi, i previously used the snackbar component like this:

```javascript
import VSnackBar from 'vuetify/es5/components/VSnackBar'
Vue.use(Vuetify, {
  components: {
    VSnackBar,
   // other components
}
```

After upgrading to 1.2.0 this did no longer work because the component was renamed. You now have to use:

```javascript
import VSnackbar from 'vuetify/es5/components/VSnackbar'
Vue.use(Vuetify, {
  components: {
    VSnackbar,
   // other components
}
```

Notice VSnack**b**ar vs VSnack**B**ar. It would be great to mention this in the changelog or something.

**Comment by KaelWD** [comment]
It's never been called VSnackBar 

https://github.com/vuetifyjs/vuetify/tree/v1.1.14/src/components/VSnackbar

**Comment by cars10** [comment]
Interesting, i wonder why it worked in the first place. Thanks.
