### ISSUE TITLE
[Feature Request] add v-img lazyload prop - only start loading src if element is visible

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#4983]
### What problem does this feature solve?
Option to lazyload images only if the content is visible
Google "Pagespeed Insights" would like to prioritize visible content. 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fimages

It would optimize network roundtrips and only loads images which are in visible area

### What is your proposed solution?
Add a prop to enable `lazyload` - only load images which are inside of visible content.

Two references of projects where this technique is applied:
* https://github.com/aFarkas/lazysizes
* https://github.com/hilongjw/vue-lazyload

**Comment by KaelWD** [comment]
This is already planned, I just didn't get around to adding it in 1.2

**Comment by dohomi** [comment]
@KaelWD great news! What is the current status of loading the `src`? Is it "non-blocking" for the robots/browser but still loads the image source in the background? I checked the source of `VImg` but not familiar enough with the technique you used.

**Comment by KaelWD** [comment]
Yes, it uses the technique described [here](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more#image_decoding_delays)

**Comment by dillionverma** [comment]
Any update on this? This is really important for PWA performance!

**Comment by dillionverma** [comment]
My solution for this using Interaction Observer API.

```

**Comment by kasper747** [comment]
It would be greate to have it.

**Comment by kasper747** [comment]
@dillionverma , where in your example should I put the url to the image? Trying now to solve this issue....

**Comment by dillionverma** [comment]
My apologies, updated the code above to make more explicit @kasper747! :smile:

**Comment by KaelWD** [comment]
@johnleider added this in 0df5f4290f2338066af3fe032cadf10f22fbf5ad
