### ISSUE TITLE
[Bug Report] v-toolbar extension slot doesn't scroll off screen when using scroll-off-screen prop

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4985]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
1. Have a toolbar with an extension slot and scroll-off-screen prop
2. Scroll down until toolbar scrolls off screen, notice the extension doesn't

### Expected Behavior
Extension scrolls off screen (as described in the docs)

### Actual Behavior
Extension stays at the top of the page

### Reproduction Link
[https://codepen.io/anon/pen/bxBbdg](https://codepen.io/anon/pen/bxBbdg)

### Other comments
Having the extension not scroll off the screen as a prop could be cool too

**Comment by KaelWD** [comment]
I think john was drunk when he did that, there was originally two separate props: 1822153bc4763dc30b3bb704107bf1f6f97ae5ec  
Then one of them was removed for some reason, keeping only the current broken behaviour: 0a1a8f69e2dda9a05c6525ea288b8b9ede43204d
