### ISSUE TITLE
[Bug Report] Disabled coloring not working correctly for v-breadcrumbs-item

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4986]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
1. Use `v-breadcrumbs` component with children `v-breadcrumbs-item`s
2. Notice that neither `disabled` prop nor being the last `v-breadcrumbs-item` changes the coloring to a "disabled" color

### Expected Behavior
Disabled and last `v-breadcrumbs-item` should be colored as if they are not links

### Actual Behavior
Color is the same for all `v-breadcrumbs-item`

### Reproduction Link
[https://codepen.io/anon/pen/eLBYBO](https://codepen.io/anon/pen/eLBYBO)

### Other comments
It looks like `v-breadcrumbs` has `themeable`-specific classes (`.theme--link`, `.theme--dark`) for settings the colors on disabled items, dividers, and last children, but doesn't use the `themeable` mixin. Of course you can get around this by setting the classes on `v-breadcrumbs` manually.

**Comment by KaelWD** [comment]
See also #3091, but this was not intentional
