### ISSUE TITLE
[Bug Report] v-data-iterator not centered in xs and sm devices.

### ISSUE THREAD

**Issue by andcuevas** [vuetifyjs/vuetify#4988]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Firefox 62.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
Resize the screen to less than 960px width and more than 960pix width.

### Expected Behavior
Elements centered for all sizes.

### Actual Behavior
For sizes with width less than 960pix the elements are not centered, for sizes greater than 960pix the elements are centered.

### Reproduction Link
[https://codepen.io/andcuevas/pen/XPNJQE](https://codepen.io/andcuevas/pen/XPNJQE)

**Comment by andcuevas** [comment]
In order to solve the problem I added the following styles to my component:


```
<style scoped>
@media only screen and (min-width: 300px) {
  .container {
    max-width: 280px;
  }
}
@media only screen and (min-width: 600px) {
  .container {
    max-width: 560px;
  }
}
@media only screen and (min-width: 960px) {
  .container {
    max-width: 900px;
  }
}
@media only screen and (min-width: 1264px) {
  .container {
    max-width: 1185px;
  }
}
@media only screen and (min-width: 1904px) {
  .container {
    max-width: 1785px;
  }
}
</style>
```

**Comment by jacekkarczmarczyk** [comment]
They are not centered in >960px as well

![image](https://user-images.githubusercontent.com/15625235/45543796-cf819480-b815-11e8-8e3c-f440fdb90687.png)

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
