### ISSUE TITLE
[Bug Report] html tag class overflow-y-hidden toggle slow when v-dialog background and button fast click epeatedly

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#4989]
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.16
Browsers: chrome
OS: android, iphone, ubuntu..etc..

### Steps to reproduce
1.activator button and dialog background fast click epeatedly
2. when dialog is opend, background scroll moving.

### Expected Behavior
html tag class overflow-y-hidden fast change

### Actual Behavior
1.html tag class overflow-y-hidden change slow 
2. opend dialog's parent scroll moving

### Reproduction Link
https://codepen.io/ksbgenius/pen/yxVVap

---

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
