### ISSUE TITLE
[Bug Report] Mobile keyboard reopens after selecting a suggestion from v-autocomplete

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#4993]
Related to #3879 

### Versions and Environment
Vuetify: 1.1.14
Vue: 2.5.17
Browsers: Chrome 68 mobile
OS: Android 8.0.0

### Steps to reproduce

**On mobile:**
1. Click on a v-autocomplete. Keyboard opens up and options are shown.
2. Close the keyboard. Options are still visible, which is ok.
3. Select an option.

### Expected Behavior

Keyboard should not reopen when you select an option

### Actual Behavior

Keyboard reopens on option selection

### Reproduction Link

[Autocomplete example from Vuetify doc](https://codepen.io/pen/?&editors=101)

---

### Additional Comments:
Once the keyboard is opened for filter typing, there is very little room for the options to show, this is why you might want to hide the keyboard to browse the options more easily.  
Generally speaking v-autocomplete is unusable on mobile.   
There is no prop to disable the autocomplete on an autocomplete component to turn it into a regular select, so if you want to do a responsive app you have to declare a v-autocomplete + a v-select with v-if on the size breakpoint, which works well but is not ideal from the code perspective.

**Comment by KaelWD** [comment]
> Generally speaking v-autocomplete is unusable on mobile

https://github.com/vuetifyjs/vuetify/issues/4059#issuecomment-389432438 Should help with that

> you have to declare a v-autocomplete + a v-select with v-if on the size breakpoint

`<component :is="isMobile ? 'v-select' : 'v-autocomplete'" ...`

**Comment by andrewharvey** [comment]
I think you can workaround this by calling [blur](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur) on on the input element once a value is selected (eg by a watch on the model). `document.activeElement.blur()`

**Comment by johnleider** [comment]
I can no longer reproduce this on Android (or iOS) on v1.5 or v2.0.
