### ISSUE TITLE
v-carousel-item breaks as VImg requires "src" while VJumbotron worked without

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#4994]
### Versions and Environment
Vuetify: 1.2

### Previously worked in:
Vuetify:1.1

### Steps to reproduce
As v-carousel-item logic changed to internally require VImg the `src` attribute is required. In previous versions VJumbotron was used internally which did not necessarily required the `src` attribute. Now VCarousel can't ship non-image content any longer.

### Expected Behavior
It would be great if either `VImg` src would be optional and not required. This way the carousel is very flexible to use works for any content to slide
 
### Actual Behavior
Currently carousel-items require a `src` attribute

### Additional Comments:
As reported in #4983 it would be great if VImg `src` attribute would not be required for the component. This way VImg and VCarouselItem would be more flexible to use.

**Comment by KaelWD** [comment]
Are you sure you're using the latest version? v-img seems to work just fine without src.

**Comment by dohomi** [comment]
Ok in the newest version the error seems to be gone 👍

**Comment by jrvaja** [comment]
hey @KaelWD & @dohomi  ,

```
<v-img gradient="to top right, rgba(100,115,201,.33), rgba(25,32,72,.7)"
>
  <div class="fill-height"></div>
</v-img>
```
This is what I mean to say. I just want gradient just like we had with `v-jumbotrons`.

Could we have this with`v-img` in next version?

**Comment by KaelWD** [comment]
You mean like this? https://vuetifyjs.com/en/components/images#example-gradients

**Comment by jrvaja** [comment]
@KaelWD This is good. Ref: https://vuetifyjs.com/en/components/images#example-gradients
But if I do not want to use image src and just want gradient like we had in v-jumbotrons, it does not work.

Please see this: https://codepen.io/jrvaja/pen/eLeKZb?editors=1010
Let me know if you need any other information.
