### ISSUE TITLE
v-img unknown element

### ISSUE THREAD

**Issue by PedroJuan91** [vuetifyjs/vuetify#4995]
### Versions and Environment
Vuetify:1.1.14
Vue:2.5.2
Browsers: chrome
OS: windows 7

### Previously worked in:
Vuetify:
Vue:

### Expected Behavior

i copy the code at the documentation for cards 
### Actual Behavior

actual output from ui:
![capture](https://user-images.githubusercontent.com/23392308/44863689-58de8600-acb0-11e8-94bc-5967a77ad7f4.PNG)
error in console:
![issue vuetify](https://user-images.githubusercontent.com/23392308/44863534-f1283b00-acaf-11e8-9084-4e95e15ea661.PNG)

### Reproduction Link

---

**Comment by jacekkarczmarczyk** [comment]
`v-img` was added in 1.2.0
