### ISSUE TITLE
V-Slider emits change twice when clicking a slider position 

### ISSUE THREAD

**Issue by bjschwa2** [vuetifyjs/vuetify#4996]
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Google Chrome
OS: Linux Ubuntu 16.04

### Steps to reproduce
Bind to change event 

### Expected Behavior
A single event is called for the new value

### Actual Behavior
Two events are called. One for the current value, then another with the new value

### Reproduction Link
https://codepen.io/bjschwa2/pen/WgomrJ

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/0a2e9cabe52ade10e4e372425ad92e1aff6f2d55/src/components/VSlider/VSlider.js#L423 https://github.com/vuetifyjs/vuetify/blob/0a2e9cabe52ade10e4e372425ad92e1aff6f2d55/src/components/VSlider/VSlider.js#L449
