### ISSUE TITLE
[Feature Request] Material-color picker

### ISSUE THREAD

**Issue by wouterfovel** [vuetifyjs/vuetify#4998]
### Problem to solve
We use colors in d3 generated html, these colors can be configured by the users.
However, we would like the user selected colors only to be those of the material-colors set. 

### Proposed solution
A neat vuetify color-picker component only selecting material-colors defined in https://vuetifyjs.com/en/style/colors#material-colors

**Comment by KaelWD** [comment]
For [the documentation](https://vuetifyjs.com/en/theme-generator) we use [vue-color](https://github.com/xiaokaike/vue-color) and simply [generate a palette](https://github.com/vuetifyjs/vuetifyjs.com/blob/17c2329cf9dfd86f9e01d99b4b58bcdddac23786/src/pages/ThemeGeneratorPage.vue#L132) from the color file.

**Comment by wouterfovel** [comment]
Cool, thx for the quick reply
