### ISSUE TITLE
Ideas to make "select" work better

### ISSUE THREAD

**Issue by monkeybrother65** [vuetifyjs/vuetify#500]
I love vuetify.  It is the most solid vue / material framework i have seen.

There are some usability issues that would help the end-user greatly.  When using a set of fields on a screen (like a form) the user expects certain behaviors that are not happening

1- when I tab from an input field to a select there is no indication that the select field has focus.  The best user experience IMHO would be for the field itself to light up the same way a normal text field doees and for the selections menu to appear either above or below the select field depending on where there is enough room on the screen.
2 - when the select field has focus I would expect the escape key to hide the selections menu and for the field to retain it's focus highlight.  when the field has focus and the user presses "enter" it should bring the selection menu back up.
3 - When the selection menu is up, using the up / down arrows should move the selection up and down the menu.
4 - When the select has focus of any kind and the user presses the delete key the selection menu should disappear and the value should go null.

For those building CRUD style screens where keyboard input is important, this stuff would be huge.

**Comment by johnleider** [comment]
I believe most of your suggestions are covered in #337 which is going to be acted upon. Is there something else that I'm missing? Maybe we could add it there as opposed to a new issue.

Thank you for the kind words!

**Comment by monkeybrother65** [comment]
Great minds think alike.  Excited to see this happen.
