### ISSUE TITLE
'v-card-media' is deprecated, use 'v-responsive' instead

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#5002]
It happens in v1.2.1, can't find anything in the docs, is v-card-media really deprecated?

**Comment by KaelWD** [comment]
yes

https://github.com/vuetifyjs/vuetify/releases/tag/v1.2.0#user-content-upgrade-guide

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by sevillaarvin** [comment]
Documentation for [cards](https://vuetifyjs.com/en/components/cards) has v-card-media as one of the 4 basic components but lists v-img in the examples.
