### ISSUE TITLE
[Bug Report] input-value update doesn't trigger lazyValue update in checkbox

### ISSUE THREAD

**Issue by pengiundev** [vuetifyjs/vuetify#5003]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chromium 67.0.3396.99, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Linux

### Steps to reproduce
Check one of the rows checkboxes, then check the header checkbox.

### Expected Behavior
The header "select all" checkbox should be unchecked.

### Actual Behavior
The header "select all" checkbox is checked.

### Reproduction Link
[https://codepen.io/penguindev/pen/jvyYdW](https://codepen.io/penguindev/pen/jvyYdW)

### Other comments
InputValue changes but lazyValue doesn't reflect this change, although it's in a watcher.

**Comment by nekosaur** [comment]
This has been fixed in 2.0
