### ISSUE TITLE
V-Select emits change event when V-Model changes (not only on user change)

### ISSUE THREAD

**Issue by bjschwa2** [vuetifyjs/vuetify#5006]
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Google Chrome
OS: Linux Ubuntu 16.04

### Steps to reproduce
Click the button to change the v-model of the v-select to 3. This will trigger a change event just like changing the v-select directly.

### Expected Behavior
The v-select is updated to 3 with v-model and no change event is triggered. The change event is triggered when v-select is changed directly.

### Actual Behavior
A change event is triggered when the v-select's v-model attribute is updated.

### Reproduction Link
https://codepen.io/bjschwa2/pen/WgRPKp

**Comment by hairylime** [comment]
I also observe this issue and it's fairly problematic. As it stands I'll have to add some hackery to 'eat' the event when it's not an actual change.

**Comment by rahimimo** [comment]
Same here even by changing the bounded model like: v-bind:value="authorizedAPIs" it triggers change event. Becasue I am posting on change this is a real hindrance.
