### ISSUE TITLE
[Bug Report] v-combobox doesn't select menu item when using <Enter> key

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#5008]
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Chrome 69
OS: Win 10

### Previously worked in:
Vuetify: 1.1.14
Vue: 2.5.17

### Steps to reproduce
Try to select a dropdown menu item from the v-combobox items list using the `<Enter>` key after highlighting it using an arrow key.

### Expected Behavior
The item gets selected and displayed in the input field, and the menu closes.

### Actual Behavior
No item is selected, but the menu closes.

### Reproduction Link
https://codepen.io/185driver/pen/dqOJvK

**Comment by KaelWD** [comment]
This applies to v-select and v-autocomplete too
