### ISSUE TITLE
Editable dropdown type in issue

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#501]
Not sure if the is designed to do so, but for editable dropdown, user has to press enter such that the value will become what is entered. Would it not be more intuitively straight forward if value is changed whenever the input is changed instead of having to press enter?

https://jsfiddle.net/Ewocker/bnad8os6/5/

**Comment by johnleider** [comment]
It was designed to do so. I'll leave this open to see if others agree with your POV.
