### ISSUE TITLE
Vue Dev Tools 5.0 beta 1 - Performance Tab error

### ISSUE THREAD

**Issue by ellis2323** [vuetifyjs/vuetify#5013]
Using the Vue Dev Tools 5.0 beta 1, i found this message in the console:
Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_ROOT_UID__' of undefined

Step to reproduce:
 $ vue create test
 $ npm run serve
then use vue dev tools plugin and select the performace tab.... No message in the console.

Then
 $ vue add vuetify
 $ npm run serve
then use vue dev tools plugin and select the performace tab.... Error message in the console:
Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_ROOT_UID__' of undefined

**Comment by johnleider** [comment]
This happens because under certain circumstances (I don't know which), Vue does not provide the $root element on children of functional components.

This has to do with the extension and not much we can do about it. You should probably report the error there.

**Comment by KaelWD** [comment]
It's got nothing to do with vuetify, it's a bug in vue-devtools (or vue itself) that just happens to be triggered by something we're doing.

**Comment by ellis2323** [comment]
It's understood but If you have the circumstances please fill in the vue-devtools tickets!
