### ISSUE TITLE
[Bug Report] Focus moves to another text field when releasing mouse over it

### ISSUE THREAD

**Issue by downace** [vuetifyjs/vuetify#5018]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chromium 68.0.3440.106
**OS:** Ubuntu undefined

### Steps to reproduce
Start mouse selecting text in "Second" field, drag mouse to "First" field, release mouse

Reproduction GIF: https://i.imgur.com/OmNLwZq.gifv

### Expected Behavior
"Second" field is focused (and text is selected in this case) like native `input`

### Actual Behavior
"First" field is focused

### Reproduction Link
[https://codepen.io/downace/pen/NLpZOy?editors=1011](https://codepen.io/downace/pen/NLpZOy?editors=1011)

### Other comments
`mouseup` and `mousedown` events are generated twice, this is strange too..

**Comment by rannooo** [comment]
Yeap, please fix this! Lots of users highlight text quite fast, so that almost always the swiping motion ends somewhere else (on another nearby text-field) , and now when other field is focused, it breaks the UX horribly.

**Comment by 185driver** [comment]
FWIW, I forked the codepen above and removed vuetify from it to replicate a basic vue build. Works fine, with no change in focus.
https://codepen.io/185driver/pen/GXOpLb
