### ISSUE TITLE
[Bug Report] Disabled chip text is invisible when dark theme applied

### ISSUE THREAD

**Issue by downace** [vuetifyjs/vuetify#5019]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chromium 68.0.3440.106
**OS:** Ubuntu undefined

### Steps to reproduce
Nothing to do, just look at result

### Expected Behavior
Text is visible (maybe light gray)

### Actual Behavior
Text is invisible until selected

### Reproduction Link
[https://codepen.io/downace/pen/VGbZWE](https://codepen.io/downace/pen/VGbZWE)

**Comment by KaelWD** [comment]
Duplicate of #5074
