### ISSUE TITLE
v-dialog not showing all fields

### ISSUE THREAD

**Issue by neegool** [vuetifyjs/vuetify#502]
### Steps to reproduce
Create a form dialog (copy-paste from the Vuetify docs)

### Versions
Vue 2.3.2
Vuetify 0.11.0
Chrome 58.0.3029.96

### What is expected ?
Multiple fields is shown, like in the "Form" section of the Dialog documentation: https://vuetifyjs.com/components/dialogs

### What is actually happening ?
Only the first text field is being rendered.

### Reproduction Link
https://codepen.io/neegool/pen/WjXevd

**Comment by neegool** [comment]
I can produce the expected behavior by using paired tags on <v-text-field>. I have updated the codepen above to show the difference.

**Comment by mfferreira** [comment]
@neegool you're missing two things.
1. `v-model` on the `v-dialog` tag, to be able to control the dialog visibility
2. `d4` boolean variable in `data` that is used both in `v-model` and on button `@click`

https://codepen.io/mfferreira/pen/MmOwGx

**Comment by johnleider** [comment]
This will be more clear in the new documentation. Sorry for the confusion.
