### ISSUE TITLE
[Bug Report] Ripple does not fill the entire button

### ISSUE THREAD

**Issue by BowenYin** [vuetifyjs/vuetify#5021]
### Versions and Environment
**Vuetify:** 1.2.1
**Last working version:** 1.1.12
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Mac OS 10.13.4

### Steps to reproduce
For any Vuetify button, the ripple does not completely fill the entire button if you click and hold on one edge of the button. I'm not sure if this is intended or that otherwise this would be fairly minor issue, but the ripple looks somewhat incomplete and unnatural now. The examples below use the left sidebar in the Vuetify documentation site.

### Expected Behavior
The ripple should fill the entire button, like it did before v1.2. The original working ripple is shown below in the animated gif:
![GIF of working ripple in previous version](https://i.imgur.com/Tp7RZ3m.gif)

--> The ripple was working perfectly fine before v1.2. Reverting it back would be an easy and effortless solution.

### Actual Behavior
The ripple does not fill the entire button if you click on one edge of the button. It starts off rippling very fast, then it stops before filling the whole button. This image shows the ripple in v1.2.1:
![GIF of ripple not filling entire button](https://i.imgur.com/bayPjlN.gif)

### Reproduction Link
[https://vuetifyjs.com/en/components/snackbars](https://vuetifyjs.com/en/components/snackbars)
(There's no specific link; it occurs for any button.)

**Comment by jacekkarczmarczyk** [comment]
With tabs it looks even worse https://codepen.io/anon/pen/QVvoem
![ripple](https://user-images.githubusercontent.com/15625235/45015250-69309100-b021-11e8-996c-4c77248b9d32.gif)

**Comment by KaelWD** [comment]
7f396e69d24fc75e0318832e060b23173d55198a

It was allegedly to help with performance, which seems bogus to me.

**Comment by nekosaur** [comment]
I should probably revive my ripple PR
