### ISSUE TITLE
incorrect documentation (or incomplete example) for dialog without activator

### ISSUE THREAD

**Issue by lebesnec** [vuetifyjs/vuetify#5023]
### Versions and Environment
Vuetify: 1.2.1

### Steps to reproduce
- open the documentation for dialog without activator : https://vuetifyjs.com/en/components/dialogs#example-without-activator
- it say  that "If for some reason you are unable to use the activator slot, be sure to add the .stop modifier to the event that triggers the dialog."

### Expected Behavior
the given example should show how to use the "stop" modifier, or the doc should be updated if the modifier is not needed.

### Actual Behavior
The given example does not use the "stop" modifier (and seems to be working fine without).

### Reproduction Link
https://vuetifyjs.com/en/components/dialogs#example-without-activator

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #591](https://github.com/vuetifyjs/vuetifyjs.com/issues/591) via [**ZenHub**](https://www.zenhub.com/)
