### ISSUE TITLE
[Feature Request] add custom colors on v-expansion-panel-content

### ISSUE THREAD

**Issue by PrismPrince** [vuetifyjs/vuetify#5026]
### Problem to solve
cannot customize each item on the expansion list

### Proposed solution
v-expansion-panel-content must support the color prop to customize the color

**Comment by AlexSHoffman** [comment]
@PrismPrince you can do that already. Here's a few examples:

### Changing color of the 4th item
```html
<v-expansion-panel-content
   :class="{'grey lighten-2': i === 3}"
>
```

### Changing color of the odd items
```html
<v-expansion-panel-content
   :class="{'grey lighten-2': i % 2 === 0}"
>
```

### Changing color of the even items
```html
<v-expansion-panel-content
   :class="{'grey lighten-2': i % 2 !== 0}"
>
```

Here's a live preview for you:
https://codepen.io/anon/pen/eLRYJy?editors=1010
