### ISSUE TITLE
[Feature Request] add a11y support to v-pagination

### ISSUE THREAD

**Issue by andreixk** [vuetifyjs/vuetify#5028]
### What problem does this feature solve?
Adding keyboard navigation to the component will improve Accessibility usage; e.g. people with disabilities who primarily rely on keyboard navigation would greatly benefit from it.

### What is your proposed solution?
Simple use case:

template:
```
<v-pagination
        v-model="page"
        :length="numPages"
        @keypress = "keyHandler"
/>
```

script:
```
keyHandler(btn) {
  switch(btn.key) {
     case 'ArrowRight': /* navigate to the next page */
     break;
     case 'ArrowLeft': /*navigate to previous page*/
     break;
  }
}
```

Perhaps this has been implemented in some other form I'm unaware of?

**Comment by johnleider** [comment]
This is something I 100% plan to implement. `v-pagination` updates unfortunately did not make the cut for v2.0's initial release but will be handled in a patch after. Thank you for your patience.
