### ISSUE TITLE
[Bug Report] New Multi Date Selector Validation Bug

### ISSUE THREAD

**Issue by eskemojoe007** [vuetifyjs/vuetify#5034]
### Versions and Environment
**Vuetify:** 1.2.2
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
Everytime the calendar is clicked within the combo box, the combo box loses focus, either losing its blue color, or triggering validation.  Open the empty combo box, then click next month arrow, and the whole main field will go red, even though nothing has been input yet.

### Expected Behavior
Expected that the combox remains in focus until the calendar is closed.

### Actual Behavior
Combo box loses functionality the first time the calendar is clicked.

### Reproduction Link
[https://codepen.io/eskemojoe007/pen/PdjOgb?&editors=101](https://codepen.io/eskemojoe007/pen/PdjOgb?&editors=101)

### Other comments
I had helped come up with this sort of solution here: https://codepen.io/eskemojoe007/pen/JBdpqE with jacek, which also suffered from this issue.

**Comment by jacekkarczmarczyk** [comment]
Not really related to date picker, this is how html works - when you click outside the text field it loses the focus and validates itself. I'm not sure what would be the best approach here

**Comment by eskemojoe007** [comment]
I agree, but I think that focus should be maintained in the text field while the datepicker is up, like is done for an autocomplete or combobox.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
