### ISSUE TITLE
[Feature Request] Function that checks if form is validated without triggering errors.

### ISSUE THREAD

**Issue by myrgato** [vuetifyjs/vuetify#5035]
### Problem to solve
When you push an error message to an array bound to :error-messages prop in a input, it makes the form v-model data false, but when you remove the error, it doesnt, so you have to manually set it to true.

If the user goes directly to the input you're doing this, and the validation pass (error messages array length would be 0), it would set the v-model form data to true even if you have other inputs that might need validation, misguiding the user to click ie a 'save' button that gets enabled whenever the v-model form data is true.

### Proposed solution
Make a validate() like function that checks if the form has errors without trigerring the error messages, so we can check if the form is valid before setting the form v-model to true manually.

**Comment by KaelWD** [comment]
Do you have a codepen demonstrating this? `lazy-validation` should always emit true if there's no visible errors.

**Comment by myrgato** [comment]
https://codesandbox.io/s/3x8p0l7m3q

In the example above, i have two fields, if i write the e-mail before any fields, it will trigger all error validations because i need to execute validate() to see if other fields in the form are validated or not before manually setting isValid to true

All i want is to check if theres anything that needs to be input, not also trigger the error messages

**Comment by KaelWD** [comment]
Don't call validate() then? v-form updates the model itself to indicate if it's valid, you shouldn't need to assign it manually like that.

**Comment by myrgato** [comment]
Hm, so simply removing the error from the bound error-messages array would make the field pass validation?

**Comment by KaelWD** [comment]
should do

**Comment by myrgato** [comment]
Okay! Thank you @KaelWD
