### ISSUE TITLE
v-list-tile-action crashes if using v-html only

### ISSUE THREAD

**Issue by frankdugan3** [vuetifyjs/vuetify#5037]
### Versions and Environment
Vuetify: 1.2.2
Vue: 2.5.17
Browsers: Firefox 61.0.1
OS: Pop!_OS 18.04 LTS

### Previously worked in:
Vuetify: 1.2.1
Vue: 2.5.17

### Steps to reproduce
Example code crashes and does not display the content of `v-html`. Adding any text between the `v-list-tile-action` tags will make the component work again.

### Expected Behavior
I would expect the component to simply use the content of `v-html`.

### Actual Behavior
Component crashes and displays nothing.

### Reproduction Link
https://codepen.io/anon/pen/zJzMpa?editors=1111

---
### Additional Comments: 
I'm pretty sure the issue is here: fbc5a35497bc37ab93fbcc7463eab5fcda44ad15
Though the minified errors are cryptic, the development version gives a more useful error:
```
[Vue warn]: Error in render: "TypeError: children is undefined"
```

**Comment by abhaywawale** [comment]
From my experience I think that v-html doesn't accept the inline block of code. [Do this instead](https://codepen.io/abhaywawale/pen/WgOPJe?editors=1010)

**Comment by frankdugan3** [comment]
OK, I was just trying to keep it simple. My actual use case doesn't use inline code, and your example will still fail without the child element: https://codepen.io/anon/pen/LJLqJQ?editors=1011

That is the specific behavior I'm thinking is a bug.

**Comment by shongololo** [comment]
I also encountered an issue with `v-list-tile-action`, I've downgraded back to 1.2.1 otherwise I would post the error message here.
