### ISSUE TITLE
Datatable default sorting is almost right.

### ISSUE THREAD

**Issue by joedooley** [vuetifyjs/vuetify#504]
The default sorting seems to be wrong. I could be missing something? I've moved other number based columns into the first position and those weren't sorted properly in ascending order either. I also tried the new default-sort prop and wasn't able to get it working that way. 

Thanks in advance for everything.

### Steps to reproduce
See [CodePen](https://codepen.io/joedooley/pen/jmadNG)

### Versions
Browser: Chrome Canary
Vue: 2.3
Vuetify: 0.11.1. No luck on the dev branch either

### What is expected ?
The results would be sorted by rank, 1 thru 90, in ascending order.

### What is actually happening ?
The results are almost in order. But not quite.

### Reproduction Link
https://codepen.io/joedooley/pen/jmadNG

**Comment by nekosaur** [comment]
It looks like the coinmarketcap api doesn't have any CORS headers set up? I'm getting an error `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access.`

**Comment by joedooley** [comment]
Yeah, their setting that up now. Do you mind installing the CORS chrome extension to bypass that for now? Here is a [link](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) to download the extension. 

Once installed just add https://api.coinmarketcap.com/ into the extension. Like this https://www.dropbox.com/s/uiqzouj5rd8gltt/Screenshot%202017-05-08%2017.16.51.png?dl=0

**Comment by nekosaur** [comment]
Fixed on dev in acd9af0. The problem was that your numbers are actually strings.
