### ISSUE TITLE
Vuetify official demo app does not work under ie11

### ISSUE THREAD

**Issue by cnyyk** [vuetifyjs/vuetify#5040]
### Versions and Environment
Vuetify: 1.2.2
Vue: latest maybe
Browsers: IE11
OS: Win10 x64

### Steps to reproduce
Open IE11, navigate to https://vuetifyjs.com/themes/blog-starter/ or https://vuetifyjs.com/themes/parallax-starter/, page breaks.

### Expected Behavior
Render properly as chrome

### Actual Behavior
Page breaks.

### Reproduction Link
https://vuetifyjs.com/themes/blog-starter/
https://vuetifyjs.com/themes/parallax-starter/

---
### Additional Comments:
Screenshot:
![tim 20180905120619](https://user-images.githubusercontent.com/275233/45070665-00bae000-b105-11e8-93af-be8b9c741448.png)

**Comment by abhaywawale** [comment]
For future reference. [Vuejs not loading in IE11](https://stackoverflow.com/questions/41185734/vue-js-not-loading-on-ie11-with-error-symbol-is-undefined).

**Comment by cnyyk** [comment]
@abhaywawale Got. Thanks.
