### ISSUE TITLE
Unexpected margin-bottom: 12px; in .v-input__slot when use "multiple" in v-select

### ISSUE THREAD

**Issue by roman-dynin** [vuetifyjs/vuetify#5043]
### Source

https://gist.github.com/roman-dynin/c0409b0e7fb30a68be3d19fd0932c56d

### Versions and Environment
Vuetify: 1.2.2
Vue: 2.5.17
Nuxt: 1.4.2
Browsers: Google Chrome 68.0.3440.106, Safari 11.0.3
OS: macOS 10.13.3

### Expected Behavior
<img width="1071" alt="screenshot 2018-09-05 16 20 40" src="https://user-images.githubusercontent.com/538251/45095814-abdc9100-b127-11e8-9f0a-66e209ed0c09.png">

### Actual Behavior
<img width="1071" alt="screenshot 2018-09-05 16 20 32" src="https://user-images.githubusercontent.com/538251/45095812-ab43fa80-b127-11e8-822c-f399f45f0685.png">

**Comment by jacekkarczmarczyk** [comment]
Looks fine? https://codepen.io/anon/pen/dqzNMg

**Comment by roman-dynin** [comment]
Yes, in this pen v-select look fine, but I cannot understand what wrong with my environment. I use only Vuetify .styl file.

**Comment by jacekkarczmarczyk** [comment]
Ping for reopening or just create a new issue when you'll manage to create the codepen reproduction that shows the problem (however it looks more like a problem with your set up). Check also whether your vuetify version is up to date.

You can also ask on [the Discord chat room](https://community.vuetifyjs.com), [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by KaelWD** [comment]
Looks like #2054

**Comment by scasic** [comment]
Faced same issue after upgrading to the latest version of vuetify.

**Comment by marcioibm** [comment]
Facing saming issue 👍

**Comment by chaim0m** [comment]
I have this issue as well, is there any solution other then the above (not an option for me)?

**Comment by aspickard** [comment]
I am also facing this issue.
