### ISSUE TITLE
[Feature Request] v-menu doesn't work when it has both "top" and "attach" props

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#5044]
### Versions and Environment
All

### Previously worked in:
Never

### Actual behavior:

v-menu doesn't work as expected in all cases. Here's what I mean:

- v-menu **DOES** work properly when it has has both `bottom` and `attach` props AND is located inside a `v-toolbar` (or any other container on top of the screen)
https://codepen.io/anon/pen/VGzQxy?editors=1000

- v-menu **DOES NOT** work when it has both `top` and `attach` props AND is located inside a `v-footer` (or any other container with `position: fixed; bottom: 0`) 
https://codepen.io/anon/pen/NLvyMm?editors=1000

**Comment by johnleider** [comment]
This is being addressed in the toolbar refactor of v1.4

**Comment by johnleider** [comment]
This has been resolved for v2.0 https://codepen.io/johnjleider/pen/VJYLvG?editors=1010
