### ISSUE TITLE
Autocomplete search input event cannot be bound using an HTML attribute

### ISSUE THREAD

**Issue by dkichler** [vuetifyjs/vuetify#5046]
### Versions and Environment
Vuetify: 1.1.1
Vue: 2.5.16
Browsers: Chrome 68.0.3440.106
OS: Mac OS 10.13.6

### Steps to reproduce

Attempt to register an HTML bound event handler with `<v-autocomplete>` search update event

### Expected Behavior

Expect to be able to register an event handler

### Actual Behavior

No event handler may be registered using an HTML attribute due to the [camel case event name](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VAutocomplete/VAutocomplete.js#L99)

### Reproduction Link

See this [codepen](https://codepen.io/dkichler/pen/BOdMJq) demonstrating the issue.

**Comment by KaelWD** [comment]
vuejs/vuejs.org#1721
vuejs/vue#6428
vuejs/vue#8297
