### ISSUE TITLE
Subheaders and Headers

### ISSUE THREAD

**Issue by uonick** [vuetifyjs/vuetify#505]
### Steps to reproduce
Open url https://vuetifyjs.com/components/subheaders in Google Chrome (57+) and scroll

### Versions
Google Chrome 57.0.2987.133 (64-bit) macOS
Vuetify v0.11.1

### What is expected ?
The header should be above the subheader

### What is actually happening ?
See:
![giphy](https://cloud.githubusercontent.com/assets/365029/25806360/92d06e42-340b-11e7-84dd-9423ec389f27.gif)

### Reproduction Link
https://vuetifyjs.com/components/subheaders

**Comment by johnleider** [comment]
This is mainly a problem with the documentation. With that being said, with the layout update in 0.12.0, this is no longer an issue. For that reason, I'll be closing this. Ty for the report.
