### ISSUE TITLE
[Bug Report] [Vue warn]: Error in callback for watcher "isActive": "TypeError: this.listClick is not a function"

### ISSUE THREAD

**Issue by jonathanw2004** [vuetifyjs/vuetify#5050]
### Versions and Environment
**Vuetify:** 1.2.3
**Last working version:** 1.1.8
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
Please see https://codepen.io/jonathanw2004/pen/eLEPzO

### Expected Behavior
- There should be no any warning in browser's console.
- There should be no error or warning such as [Vue warn]: Error in callback for watcher "isActive": "TypeError: this.listClick is not a function"
- The expand/collapse should behavior properly.

### Actual Behavior
- there are error and warning
- expand/collapse not working

### Reproduction Link
[https://codepen.io/jonathanw2004/pen/eLEPzO](https://codepen.io/jonathanw2004/pen/eLEPzO)

**Comment by nekosaur** [comment]
The warning actually explains what's wrong.

```
[Vuetify] The v-list-group component must be used inside a v-list
```

You need to place the v-list-group inside a v-list component.
