### ISSUE TITLE
[Bug Report] v-select readonly has incorrect styling

### ISSUE THREAD

**Issue by jshowatt** [vuetifyjs/vuetify#5051]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Internet Explorer, Chrome 69.0.3497.81
**OS:** Windows 10

### Steps to reproduce
Add two selects, one disabled and one readonly.
You'll see that styling is the same.

### Expected Behavior
Selections in a readonly control are darker than in a disabled control.

### Actual Behavior
Selections in readonly and disabled controls are rendered the same.

### Reproduction Link
[https://codepen.io/lqy1/pen/KxXeab](https://codepen.io/lqy1/pen/KxXeab)

### Other comments
It looks like `v-select__selection--disabled` is getting applied to selections instead of `v-select__selection--readonly`

**Comment by johnleider** [comment]
Closed via 5cfaeba
