### ISSUE TITLE
[Bug Report] [Mobile] Swiping <v-tab-item> doesn't adjust <v-tabs> position

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5052]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Mac OS 10.13.6

### Steps to reproduce
Open up a page with tabs that can't fit all the tabs.
Start swiping to the `<v-tab>` that's not visible on screen.

### Expected Behavior
Similarly to when you press a tab that's half visible, adjust the position of the `<v-tabs>` and make the selected `<v-tab>` completely visible in the `<v-tabs>` bar.

### Actual Behavior
The `<v-tabs-slider>` will adjust its position, but the `<v-tabs>` won't, so the `<v-tabs-slider>` is now outside of the view.

### Reproduction Link
[https://codepen.io/henriq88/pen/OoxdBw?&editors=101](https://codepen.io/henriq88/pen/OoxdBw?&editors=101)

**Comment by johnleider** [comment]
I'm looking at this and I'm a bit unsure of the exact issue. Can you provide a gif or some additional insight as to what the issue is?

**Comment by henriq-88** [comment]
https://imgur.com/a/693UMuW

As you can see the `<v-tabs-slider>` will move outside the `<v-tabs>` view, which makes it hard to know which tab you are currently on.
The expected behavior would be for the `<v-tabs>` view to adjust the position to its `<v-tabs-slider>` so the current `<v-tab>` is visible, similar to when you press a partly visible `<v-tab>`

**Comment by johnleider** [comment]
Perfect, thank you.
