### ISSUE TITLE
[Bug Report]  Navigation drawer animation issue [auto-collapse animation]

### ISSUE THREAD

**Issue by Vorror** [vuetifyjs/vuetify#5053]
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.17
Browsers: Chrome 68.0.3440.106
OS: OSX 

### Steps to reproduce
Resize window until navigation drawer auto collapses.

### Expected Behavior
When a `clipped` navigation drawer auto collapses — it should remain visibly behind the toolbar(z-index) during the entire animation.

### Actual Behavior
The navigation drawer briefly appears above the toolbar when it auto collapses.

### Reproduction Link
It seems all of the example templates from Vuetify's own website exhibits this issue. For example here: https://vuetifyjs.com/en/examples/layouts/dark.

---
### Additional Comments:

Gif: (I'm making the Chrome window's width smaller offscreen)
![2018-09-07 01 47 17](https://user-images.githubusercontent.com/3613230/45201006-762bcb00-b241-11e8-9cb8-44942d73d8df.gif)

**Comment by KaelWD** [comment]
It needs to wait for the transition to complete before applying `.v-navigation-drawer--is-mobile`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
