### ISSUE TITLE
[Feature Request] Wrapping Vuetify components as web components

### ISSUE THREAD

**Issue by RobbinBaauw** [vuetifyjs/vuetify#5054]
### Problem to solve
Hello, this might be a completely undoable (and odd) request, but this might be a nice feature for making the framework even more usable. I would propose wrapping the whole framework (or just a few components) as web components. As right now (as the name of the framework of course implies), it is only usable using VueJS. 

Vue is great of course, but the Typescript integration isn't mature enough. So I could imagine many bigger applications going for a framework like Angular, which is typed and object oriented by nature. But in Angular there is no framework that comes near the scope and quality of Vuetify. 

Wrapping Vuetify components as web components would make these components usable in every framework, even without any framework.

### Proposed solution
There is an officially supported Web Component Wrapper: https://github.com/vuejs/vue-web-component-wrapper. This could be used to wrap the components.

**Comment by RobbinBaauw** [comment]
For the ones interested, I made some changes to the [api-generator](https://github.com/vuetifyjs/api-generator) project. This generates a vueComp folder with all the vuetify components in the dist folder, upon running.

What then to do is to create a new vue project, copy the components to for example a vueComp folder, with at least those dependencies:
```
"dependencies": {
	"vue": "^2.5.17",
	"vuetify": "^1.0.19"
},
"devDependencies": {
	"@vue/cli-service": "^3.0.3",
	"vue-cli-plugin-vuetify": "^0.1.6",
	"vue-template-compiler": "^2.5.17"
}
```

Then you can compile this to a single js file using the following command:
`node node_modules\@vue\cli-service\bin\vue-cli-service.js build --target wc  --name vuetify vueComp/*.vue`

Then you need to add the vuetify and vue js in your html (or however you wanna do it, at least make sure it's available). Looks something like this:

```
<!DOCTYPE html>
<html>
    <head>
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>
        <script src="./dist/vuetify.js"></script>
    </head>
    <body>

        <vuetify-v-app>
            <vuetify-v-btn color="indigo" fab>Tesrt</vuetify-v-btn>
        </vuetify-v-app> 

    </body>
</html>
```

Mind you I had to remove the variable types from the props, as vue web component wrapper gave an error when I used the null type (any in vue).

**Comment by nickeyvee** [comment]
Has anyone found a workaround for doing this?

**Comment by mrts** [comment]
@KaelWD, @johnleider would it be possible to consider adding web components support in the upcoming version 3 codebase?

**Comment by mrts** [comment]
> Has anyone found a workaround for doing this?

You can just use ordinary run-time integration via JavaScript

```html
  ... other code ...
  <div id=app></div>
  <script src=/your-component/js/chunk-vendors.1234abc.js></script>
  <script src=/your-component/js/app.1234abc.js></script>
  ... other code ...
```

as a workaround (along with corresponding includes in the header).

**Comment by Zyles** [comment]
No progress on this? Was excited to use VueJS as web component then found out Vuetify won't work...

**Comment by MarcSkovMadsen** [comment]
I would really like this as well. This would enable data scientist to build awesome looking data apps in Python using [Panel](https://panel.holoviz.org/). I've been experimenting with using the mwc web components. But they are not nearly as developed.

Checkout awesome-panel.org to see what I am trying to build from Python only.

**Comment by jakecjones** [comment]
Any more news on this implementation?

**Comment by fklingler** [comment]
I would also love to see this implemented. We're trying to include the vuetify calendar inside an Angular app.

**Comment by 1shaked** [comment]
> > Has anyone found a workaround for doing this?
> 
> You can just use ordinary run-time integration via JavaScript
> 
> ```
>   ... other code ...
>   <div id=app></div>
>   <script src=/your-component/js/chunk-vendors.1234abc.js></script>
>   <script src=/your-component/js/app.1234abc.js></script>
>   ... other code ...
> ```
> 
> as a workaround (along with corresponding includes in the header).

Where do you include the script?

**Comment by mrts** [comment]
Wrapping Vuetify components as Web Components became a lot easier with version 3.2, quoting the [release blog https://blog.vuejs.org/posts/vue-3.2.html):

> Vue 3.2 introduces a new `defineCustomElement` method for easily creating native custom elements using Vue component APIs.

**Comment by YipingRuan** [comment]
> Wrapping Vuetify components as Web Components became a lot easier with Vue version 3.2, quoting the [release blog post](https://blog.vuejs.org/posts/vue-3.2.html):
> 
> > Vue 3.2 introduces a new `defineCustomElement` method for easily creating native custom elements using Vue component APIs.

Any hint how to use vite and vuetify to build Web Component?
I can't figure out how to convert the below setup for that case.  As there is no `App` or `mount` to play with. 

````JavaScript
createApp(App)
  .use(vuetify)
  .mount('#app')
````

Will something like this work?
````JavaScript
loadFonts()

const t = defineCustomElement(WidgetContainer)
createApp(t).use(vuetify)
// Regist web component
customElements.define('my-vuetify-component', t)
````

**Comment by GratienDSX** [comment]
I'm struggling at the same place as @YipingRuan. Did anyone crack the `defineCustomElement` + `use(vuetify)` problem the two things work together?

**Comment by mrts** [comment]
I'm afraid you have to wait for the Vuetify v3 release to get better support for web components.

**Comment by landoephan** [comment]
any updates here? someone make it work with the vuetify3 beta version maybe?

**Comment by PhysRex** [comment]
Found a potential workaround for this, following this [stackOverflow response](https://stackoverflow.com/a/69820280/7613388). I've gotten it to work this way, except that I need to add the styles into the shadow dom's `<style>`. In my case, vite is automatically adding the imported components' styles (vuetify components) into the `<head>`

**Comment by landoephan** [comment]
@PhysRex  I tried to follow the response you posted, I'm getting the following error though:
```
defaults.ts:25 Uncaught (in promise) Error: [Vuetify] Could not find defaults instance
    at useDefaults (defaults.ts:25:24)
    at setup (defineComponent.tsx:53:24)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7246:29)
    at setupComponent (runtime-core.esm-bundler.js:7201:11)
    at mountComponent (runtime-core.esm-bundler.js:5524:13)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at mountChildren (runtime-core.esm-bundler.js:5285:13)
    at mountElement (runtime-core.esm-bundler.js:5195:13)
 ```
do you have any idea how to solve this?

**Comment by Tsunade90** [comment]
@PhysRex I tried this solution but I have the same error as @landoephan .
Any update on this few month later?

**Comment by rifqi96** [comment]
> Any update on this few months later? I used @PhysRex 's trick to create web components in vue 3 using vuetify 3 but it does not include vuetify's css

Wondering the same thing

**Comment by landoephan** [comment]
@Tsunade90 @rifqi96 did one of you find a solution on this?

**Comment by FabianWilms** [comment]
@johnleider As you just closed this as completed - what is the recommended solution to this problem?

**Comment by alanluigi** [comment]
i have the same issue. what is the recommended solution to this problem?
