### ISSUE TITLE
Hiding a button inside a v-bottom-nav throws an error

### ISSUE THREAD

**Issue by alfreema** [vuetifyjs/vuetify#5057]
### Versions and Environment
Vuetify: 1.2.1
Vue: ^2.5.2
Browsers: Firefox
OS: Windows 10

### Steps to reproduce
Open your developer console and then click the "Click to hide button".   

### Expected Behavior
Button should toggle on/off without any error.

### Actual Behavior
Hiding the button seems to work fine, but there is an error thrown in the console.

Note:  Any button downstream of v-bottom-nav will also trigger it if toggled (for example if you had a dialog with buttons on it embedded inside of v-bottom-nav).

### Reproduction Link
https://codepen.io/alfreema/pen/mGqMwd

---

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 1.3
