### ISSUE TITLE
DatePicker requires 2 tries to select a date other than "today" (for picker in dialog)

### ISSUE THREAD

**Issue by jonno317** [vuetifyjs/vuetify#506]
When using a DatePicker in a dialog, if a date other than "today" is selected then the text field will be populated with the current date. Clicking through for a second selection works correctly.

The behavior can be seen on the example page for pickers. I checked some of the other flavors of picker (particularly menu) and they appear to all work as expected.

https://vuetifyjs.com/components/pickers

**Comment by leonfather** [comment]
The same problem

**Comment by johnleider** [comment]
This was something fixed on dev. Let me see if we can cherry pick the commit and get a small patch out.

**Comment by johnleider** [comment]
Fixed with 7c7afcb031a31c749772d693bfc171a03aecf8c4
