### ISSUE TITLE
[Feature Request] `v-list-tile`s should render an `a` isntead of a `div` (vue-router/nuxt-router wrapped)

### ISSUE THREAD

**Issue by gangsthub** [vuetifyjs/vuetify#5061]
### Problem to solve
The click target should be on an interactuable element (`<a>`); not a `<div>`. You can <kbd>right click</kbd> and select options within the Context Menu like (open in a new window), but not if the link navigation is generated by JS part. A _vue-router/nuxt-router_ makes more sense. This would require some changes in the API of the lists or the navigation drawers. And raises another problem: you should not place links inside links, so the nested lists have to be taken into consideration.

Right now, inserting the _vue-router/nuxt-router_ in the middle of the recommended structure, breaks the hover effect and some styles.

### Proposed solution
Add in the api the `:to` prop. And if present, render the content of the `li` in an anchor but if the item has sub-items, adapt the styles and the markup to play nice with each other.

Thank you very much

**Comment by KaelWD** [comment]
You can use `v-list-tile` as a router-link directly, you shouldn't be wrapping it: https://stackoverflow.com/a/47605842/2074736

**Comment by gangsthub** [comment]
So nice, thanks! Sorry I missed that one.
