### ISSUE TITLE
[Feature Request] Card Example Illustrating Four Components

### ISSUE THREAD

**Issue by bretonio** [vuetifyjs/vuetify#5062]
### Problem to solve
Documents do not illustrate proper and successful use of all four v-card components.  The user finds him-herself improvising to get the desired effect.

### Proposed solution
Please review the card examples and provide an example in which all four components are used. In your first example, for instance, v-card-media is not used to wrap a v-img as one might expect and v-card-text is not used at all. Title and body text are both  wrapped in v-card-title.

**Comment by jacekkarczmarczyk** [comment]
Please open the issue in docs repo (https://github.com/vuetifyjs/vuetifyjs.com)
