### ISSUE TITLE
[Feature Request] v-stepper should be more interactive like vue-form-wizard

### ISSUE THREAD

**Issue by rahul1235** [vuetifyjs/vuetify#5064]
### What problem does this feature solve?

it will be having universal action control for next, previous and finish step. which current stepper doesn't have as of now.
It should have basic functionality like before step change function, dynamic rendering for steps.

### What is your proposed solution?
v-stepper shoud give basic functionalities like vue-form-wizard

**Comment by johnleider** [comment]
This component is being fully reworked for v1.3

**Comment by johnleider** [comment]
Another update. Due to backwards compatibility issues, `v-stepper` was not fully integrated with `v-item-group`. I still intend to make improvements to the component but it not make the cut for v2.0.
