### ISSUE TITLE
Vuetify updated, then Jetbrains IDE autocomplete not working

### ISSUE THREAD

**Issue by cherryred5959** [vuetifyjs/vuetify#5067]
In my project, updated Vuetify from version 1.1.6 to version 1.2.2, 
Then my autocomplete does not work in my Jetbrains IDE.
How do I resolve this issue?

![screenshot from 2018-09-10 23-47-40](https://user-images.githubusercontent.com/32331576/45304894-16406780-b554-11e8-9ae3-17b4e49767fe.png)

**Comment by RobbinBaauw** [comment]
The components are now in Typescript, see https://github.com/vuetifyjs/vuetify/issues/4590 and https://youtrack.jetbrains.com/issue/WEB-32886 for possible workarounds

**Comment by cherryred5959** [comment]
@RobbinBaauw  My search capabilities are still far away, thank you.
