### ISSUE TITLE
Double Scrollbars on v-dialog with offset-x scrollbar

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#507]
Reproduction Link

http://codepen.io/anon/pen/gWojYx

![image](https://cloud.githubusercontent.com/assets/25447231/25841888/7a63d208-34d4-11e7-9557-20cc3c613573.png)

Can this be fixed? when on full screen making the body tag hide on overflow

**Comment by johnleider** [comment]
This is something you would need to do on your own. Unless @mfferreira thinks otherwise.

**Comment by ralphchristianeclipse** [comment]
im trying to add overflow none in the body tag using a watcher on the v-model of dialog but it seems its not working

**Comment by mfferreira** [comment]
@ralphchristianeclipse I agree with @johnleider. It doesn't make much sense for the dialog to control the page overflow.

Try this. Instead of `overflow: none` (none is not a valid value), use `height: 100vh` on `#app` or whatever feels right.

**Comment by ralphchristianeclipse** [comment]
@mfferreira well i give it a try thanks for the idea
