### ISSUE TITLE
[Bug Report] VTextField emits change-event even when value has not changed

### ISSUE THREAD

**Issue by tony19** [vuetifyjs/vuetify#5070]
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.17
Browsers: Chrome 68
OS: macOS High Sierra

### Steps to reproduce

 1. Create `v-text-field`
 2. Put cursor in text input
 3. Press <kbd>ENTER</kbd> multiple times (without changing text input value)

### Expected Behavior
`change`-event emitted only if there's a change in the text input's value.

### Actual Behavior
`change`-event emitted for every <kbd>ENTER</kbd>-keypress even when the value has not changed

### Reproduction Link
https://codepen.io/morphatic/pen/ExVKoRx?editors=1111

---

### Additional Comments:
This appears to be a bug caused by https://github.com/vuetifyjs/vuetify/commit/47c73e69f82ac4c553e8148e1737ae35315bdb47#diff-c2cbb2f11cf8c97e6eff0981f9927269R353

For reference, here's a demo of the `change`-event in a native `<input>`: https://codepen.io/tony19/pen/JapOod?editors=1001

**Comment by morphatic** [comment]
The repro was out of date. Still a bug. Here's a new "working" link: https://codepen.io/morphatic/pen/ExVKoRx
