### ISSUE TITLE
[Bug Report] v-btn default target

### ISSUE THREAD

**Issue by Ivanelo** [vuetifyjs/vuetify#5073]
### Versions and Environment
Vuetify: 1.2.2
Vue: 2.5.2
Browsers: Chrome, Safari
OS: Windows 10, Windows, Android, iOS

**Steps to reproduce**
 Add v-btn element with href : `<v-btn  class="primary-btn" :href="/" >Button</v-btn>`

**Expected Behavior**
If target attribute not specified, default attribute should be "_self", "undefined" instead.

![image](https://user-images.githubusercontent.com/8075003/45350071-423f0580-b5b3-11e8-99dd-30fb2e4d3319.png)

**Actual Behavior**
If target attribute not specified, link will be opened randomly (new window or same window)

**Note**
In vuetify source code "src/components/VBtn/VBtn.ts", missing props for target attribute such as:

```
props: {
...
    target: {
      type: String,
      default:  '_self'
    },
...
}
```

**Comment by vukan71** [comment]
I had the same issue. I think that it is better that default is set as _self.

**Comment by ntadic** [comment]
Same here.

**Comment by KaelWD** [comment]
Why?

> link will be opened randomly

No it won't, it'll be opened like every other link based on the browser's settings. Put `<base target="_self" />` in your \<head\> if you really want to override that.

**Comment by vukan71** [comment]
Override what? Opening in a random window?  <base target ...> we should use only if we want something that is not expected behavior.  Besides that in how many web apps did you see <base target="...whatever">?

**Comment by KaelWD** [comment]
It does exactly what you're asking for here - adds `target` to every link on the page. 

 - The current behaviour is not a bug
 - This change would result in the exact unexpected behaviour that you are talking about
 - If your browser is opening links "randomly" then you have some other problem going on that is not related to vuetify
 - We will not be making this change
