### ISSUE TITLE
[Feature Request] Show week numbers in date-picker 

### ISSUE THREAD

**Issue by Skaanning** [vuetifyjs/vuetify#5077]
### What problem does this feature solve?
Currently there is no way to see week numbers on the date-picker calendar.

### What is your proposed solution?
A week number option that can be filled out to add week numbers to the calendar view - [example](https://www.groovypost.com/wp-content/uploads/2015/10/Week-Calendar.jpg) 
The option should be able to specify how week number 1 is found. E.g. the first week with a monday is week 1 or the first 4 day week is week 1.

**Comment by RobbinBaauw** [comment]
Would indeed be nice. [Here ](https://www.syncfusion.com/products/vue/datepicker#week-number) is another example of a working calendar with that feature. It would also be nice if you could also type your date, as shown [here](https://ej2.syncfusion.com/vue/demos/#/material/datepicker/default.html). Perhaps a date picker overhaul (with https://github.com/vuetifyjs/vuetify/issues/1646, https://github.com/vuetifyjs/vuetify/issues/3650, https://github.com/vuetifyjs/vuetify/issues/459) for the component pack? ;)
