### ISSUE TITLE
[Bug Report] v-select (and kin) fail to center the initially selected item when it is 'below the fold'

### ISSUE THREAD

**Issue by asiFarran** [vuetifyjs/vuetify#5079]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 7

### Steps to reproduce
Load up a v-select (or v-autocomplete or any of the other siblings) with some items and set the value to one of the items that would require scrolling to get to.
Verify the component displays the correct value
Click to open the dropdown.

### Expected Behavior
When you open the drop-down the selected item is visible and centered (in this example we'd like to see 'Florida' centered in the dropdown popup)

### Actual Behavior
popup shows the first (top) batch of items and the user would have to scroll down to find the selection.

### Reproduction Link
[https://codepen.io/asifarran/pen/LJmxwR](https://codepen.io/asifarran/pen/LJmxwR)

### Other comments

This happens even even when the component is set to menu-props="auto" (i.e. all the items have been rendered and there's no reason to not auto-scroll it to the correct vertical location) and results in a very awkward and unexpected UX.

**Comment by nekosaur** [comment]
I get the expected behavior using Windows 7 and Chrome 69.0.3497.92

**Comment by jacekkarczmarczyk** [comment]
Fixed in 1.3.10 https://github.com/vuetifyjs/vuetify/pull/5448
