### ISSUE TITLE
v-textarea .selectionStart and .selectionEnd return undefined

### ISSUE THREAD

**Issue by vahdet** [vuetifyjs/vuetify#5081]
I get the values of `selectionStart` and `selectionEnd` properties as `undefined` when I try to apply on a `v-textarea` instance on a keydown (`@keydown`) event -which features an `event.preventDefault()` at the very beginning if it is a necessary thing to point out.

**The desired behavior**
Return the indices of the start and the end of the selected part.

**Snippet for Reprod**
https://codepen.io/vahdet/pen/WgJyEw

Select some part of the predefined text here and watch for the values above the `v-textarea`

**Comment by jacekkarczmarczyk** [comment]
You need to reference the actual textarea element, not the v-textarea component
https://codepen.io/anon/pen/XPqPYK
