### ISSUE TITLE
[Bug Report] Multiple combobox doesn't adjust the top style of suggestions

### ISSUE THREAD

**Issue by joke1** [vuetifyjs/vuetify#5082]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68 / Safari 11.1
**OS:** Windows 10 / Mac OS 10.13

### Steps to reproduce
Scroll the window to a position where suggestions appear above the input.
Search for a unique result or type some nonsense into the search field.

### Expected Behavior
Suggestions are displayed above the input.

### Actual Behavior
Big gap between suggestions and input.

### Reproduction Link
https://codepen.io/joke1/pen/zJjOMJ

**Comment by dominik-bln** [comment]
We are seeing the same, but it sometimes also moves horizontally.
