### ISSUE TITLE
Please provide an example of v-toolbar with fixed width content

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#5085]
Basically I took this, https://vuetifyjs.com/en/examples/layouts/googleContacts.
I don't like float containers, I want everything to fit into usual fixed-width centered v-container on a large screen. That's what I'm trying to achieve:
 
![screenshot from 2018-09-13 11-05-54](https://user-images.githubusercontent.com/379267/45475619-9548c200-b745-11e8-968f-8747db900f25.png)

But I met a number of obstacles with toolbar: it's float but it's content is centered and has fixed width. I pasted v-container inside v-toolbar, but it was not centered since v-toolbar__content > *:first-child and last-child have margin:0. Then added v-flex before v-container and that caused height collapse so the v-toolbar buttons were not occupy full toolbar height anymore. Then added v-layout to expand height and some v-flex inside but still haven't got any success. The question is how to properly work with v-toolbar and v-container to make the toolbar's content fixed width and centered.

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by jsgv** [comment]
@Kasheftin Were you able to solve this?

**Comment by cmeyertons** [comment]
looking for the same thing

**Comment by troneras** [comment]
Yea, same thing

**Comment by daniandl** [comment]
Not an optimal fix but this is one way to achieve it: 

html:
```
<v-toolbar class="navbar" app>
	<v-container class="py-0 disp-flex flex-center-y flex-grow">
		....
	</v-container>
</v-toolbar>
```

css:
```
.navbar {
	.v-toolbar__content {
		justify-content: center;
	}
}
```

The `disp-flex flex-center-y flex-grow` are custom classes I use, but you can probably imagine what they do :)

**Comment by saeedvaziry** [comment]
any fixes?
