### ISSUE TITLE
[Bug Report] V-Select/V-Autocomplete key down/up behavior

### ISSUE THREAD

**Issue by MateiNenciu** [vuetifyjs/vuetify#5086]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
Open dialog and then scroll to the age select. Focus on control and then navigate with down and up arrows.

### Expected Behavior
The selection should go up or down but the scroll on the dialog should stay the same.

### Actual Behavior
The dialog scrolls with the v-select selection.

### Reproduction Link
[https://codepen.io/anon/pen/qMKdrY](https://codepen.io/anon/pen/qMKdrY)

### Other comments
This is happening on v-autocomplete displayed as in this link: https://codepen.io/anon/pen/PdaqvP

**Comment by johnleider** [comment]
This issue is no longer applicable.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
