### ISSUE TITLE
[Bug Report] V-Autocomplete with chips and multiple-select opens at dialog close

### ISSUE THREAD

**Issue by MateiNenciu** [vuetifyjs/vuetify#5087]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
1. Open dialog => select at least one interests => click anywhere to close selection => click on a chip => close dialog.
2. Open dialog => select at least one interests => click anywhere to close selection => close dialog => re-open dialog => click on a chip => close dialog

### Expected Behavior
The autocomplete should stay closed at dialog closure.

### Actual Behavior
The v-autocomplete opens at dialog closure.

### Reproduction Link
[https://codepen.io/anon/pen/qMKdrY](https://codepen.io/anon/pen/qMKdrY)

**Comment by johnleider** [comment]
I can no longer reproduce this issue as of the latest version.

https://codepen.io/johnjleider/pen/zYBYdoR

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
