### ISSUE TITLE
[Bug Report] Closing v-dialog also closes temporary v-navigation-drawer

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#5089]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.81
**OS:** Windows 10

### Steps to reproduce
1) Open the temporary drawer by opening the codepen
2) open the dialog by clicking the button
3) attempt to close the dialog by clicking outside of it

### Expected Behavior
only the dialog will close, the drawer should remain open

### Actual Behavior
both the dialog and drawer close

### Reproduction Link
[https://codepen.io/anon/pen/VGdKMW](https://codepen.io/anon/pen/VGdKMW)

**Comment by RobbinBaauw** [comment]
I think it doesn't have to do with the dialog, but clicking anywhere outside of the drawer it will close, so also when closing the dialog

**Comment by johnleider** [comment]
This has to do with dependent elements. Unfortunately the changes will require some minor refactoring throughout as adding the **dependent** mixin to `v-navigation-drawer` will alter other layout functionality.

This is something that we _should_ do.

**Comment by DRoet** [comment]
@johnleider I tried pulling in the dependent mixin like you suggested just to test it out and it works:
https://github.com/DRoet/vuetify/commit/d7318a6764438445b9b3c735d7116b55509eb50a

I was just wondering if you could clarify the "will alter other layout functionality" since I couldn't find anything from my testing

**Comment by johnleider** [comment]
I probably should have said _could_ alter other layout functionality. PR looks good, will go with next PATCH.
