### ISSUE TITLE
Add to documentation info about v-checkbox slot

### ISSUE THREAD

**Issue by p1pchenk0** [vuetifyjs/vuetify#5095]
Hi all,
in current version of documentation for `v-checkbox` component there is only info, that we can add `:label` property to it. But this property accepts only string, which makes impossible to inject HTML inside of checkbox text (can be useful, when there is some bold highlighting need or when there should be `<a>` elements pasted.
Missing part of docs is that you can add HTML by using named slot:
```
<v-checkbox v-model="checkBoxModel">
    <div slot="label">
        For more info go <a href="http://example.com/">here</a>
    </div>
</v-checkbox>
```

**Comment by johnleider** [comment]
This should be made on the doc repository. https://github.com/vuetifyjs/vuetifyjs.com

**Comment by p1pchenk0** [comment]
Ok, pasted it there
