### ISSUE TITLE
[Bug Report] Tests using components with v-menu break with:  TypeError: Cannot read property 'dark' of undefined 

### ISSUE THREAD

**Issue by laliluna** [vuetifyjs/vuetify#5096]
### Versions and Environment
**Vuetify:** 1.2.3
**Last working version:** 1.1.15
**Vue:** 2.5.17
**Browsers:** Firefox 61.0
**OS:** Mac OS 10.13

### Steps to reproduce
Run yarn unit:test

======================
Original  thread: https://github.com/vuetifyjs/vuetify/issues/4987

This happens when testing:

[Vue warn]: Error in config.errorHandler: "TypeError: Cannot read property 'dark' of undefined"
TypeError: Cannot read property 'dark' of undefined

This happens when you attempt to mount any vue component that uses v-select:

wrapper = mount(Invite, {store, localVue, propsData: props, attachToDocument: true});

The actual code in the component:

<v-select
        id="role"
        v-bind:items="this.roles"
        v-model="form.data.role"
        label="Select user role"
></v-select>

The error is thrown at v-menu component on line: 211 which contains the following:

props: {
          provide: {
            theme: { isDark: this.$vuetify.dark || this.dark }
          }
        }

Versions and Environment

Vuetify: 1.20 or 1.21
Vue: 2.5.17
Browsers: N/A
OS: MacOS
Previously worked in:

Vuetify: 1.15
Vue: 2.5.17
Steps to reproduce

Attempt to test any component containing v-select using vue-dev-tools using the above mentioned versions.

### Expected Behavior
to not throw the exception

### Actual Behavior
throws exception [Vue warn]: Error in config.errorHandler: "TypeError: Cannot read property 'dark' of undefined"

### Reproduction Link
[https://github.com/laliluna/vuetify-bug-demo](https://github.com/laliluna/vuetify-bug-demo)

### Other comments
The weired thing is that I tried to create a codesandbox demo first but appearently it works in this environment.
See: https://codesandbox.io/s/201063371r

**Comment by lzhoucs** [comment]
I run into the same issue today and the following workaround worked for me:
```
// use
Vue.use(Vuetify)
// rather than
// localVue.use(Vuetify)
```

I was inspired by https://github.com/vuetifyjs/vuetify/issues/4068#issuecomment-415040833 although the issue there seems not directly related to this one.

**Comment by umbertooo** [comment]
I experienced the same behaviour with Vuetify version 1.2.4 and solved it the same way as @lzhoucs posted above. But even with this workaround the test happens to log a lot `[Vue warn]:...` warnings. These logs could be suppressed using this snippet:
https://github.com/vuetifyjs/vuetify/issues/3456#issuecomment-405199007

While these workarounds may be acceptable temporarily I'd expect to use the Vuetify like every other Vue.js plugin with the Vue Test Utils (https://vue-test-utils.vuejs.org/guides/common-tips.html#applying-global-plugins-and-mixins)

**Comment by ascott18** [comment]
Any updates on this? Would be great to be able to do `localVue.use(Vuetify)` since it is the officially prescribed method for testing Vue components.

**Comment by KaelWD** [comment]
See #4068 and https://github.com/vuejs/vue/issues/8278, it's a problem with vue that was uncovered when we switched to typescript. There's nothing wrong with not using localVue, that's how it worked with avoriaz before vue-test-utils was a thing.
