### ISSUE TITLE
[Bug Report] V-Text-Field Disabled Border Color With Outline Prop

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#5097]
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.17
Browsers: Chrome
OS: Windows 10

### Steps to reproduce
1. Click the 'Toggle Disabled Attribute' button to toggle the disabled attribute on the three v-text-fields.
2. Note that the middle input with the `outline` prop doesn't get any border color change on `disabled`.

### Expected Behavior
For consistency with other `disabled` css changes on v-text-field elements, it would be nice to see the border color update for the outline version too.

### Actual Behavior
No border color change occurs when `disabled` attribute is used with v-text-fields having an `outline` prop.

### Reproduction Link
https://codepen.io/185driver/pen/qMMZwx

---

I've added a css class to the pen showing what I believe the border color should change to, based on the color vuetify uses for other elements when they have a `disabled` prop. Toggling the second button will add the effect I'm proposing to the middle v-text-field element when it's disabled via the first button.

**Comment by jacekkarczmarczyk** [comment]
Also width of invactive field should be changed
![textfields](https://user-images.githubusercontent.com/15625235/45609539-b157a680-ba58-11e8-86b5-29a1f9bd1f8f.png)
