### ISSUE TITLE
Issue with displaying list items inside v-list-group (accordion) when data is not bound initially

### ISSUE THREAD

**Issue by bjendyk** [vuetifyjs/vuetify#510]
### Steps to reproduce
0. Open the provided example.
1. Click one of the items in the accordion.
2. The promise resolves, but the data that has just arrived is not rendered.
3. Click another item to expand it - now, when the promise resolves, the data is rendered correctly in the expanded container.
4. Refresh the example.
5. Click an item in the accordion - the element is expanded, but no data rendered.
6. Collapse the container and expand it again - this time the data is rendered correctly.

### Versions
Environment: Windows 7, Vuetify 0.11, Vue 2.2.2, Chrome 57.0.2987.133, Firefox 53.0.2 

### What is expected ?
The expected outcome is that whenever the promise is resolved and the data becomes available, the list items are rendered correctly when the list header is expanded for the first time.

### What is actually happening ?
What's happening is that the data arrives with the resolved promise, but is not rendered when the container is expanded for the first time. Clicking another accordion item (group), or collapsing/expanding the same container (regardless whether the data is fetched again or not) renders the data correctly.

### Reproduction Link
http://codepen.io/anon/pen/aWEXBP

**Comment by johnleider** [comment]
Expansion panel calculates the it's needed height by using scrollHeight at time of click. If your items are dynamically loaded, they are obviously not there when this calculation occurs. It seems like you should catch the click event, prevent default, fetch the data, then propagate your own click event to open the panel.

**Comment by bjendyk** [comment]
Thank you John for providing some tips. I played around with the example a bit and updated it so that the click is now .**stop**ped (.prevent was not enough) and when the data is ready, the click event is dispatched to v-list-group's v-tile-action - the element receives the event, but it seems that scrollHeight is still 0 because no items are shown.

**Comment by johnleider** [comment]
Okay, I'll take a look, ty.

**Comment by bjendyk** [comment]
Got it! I had to wrap the dispatchEvent in Vue.nextTick() and now it works as intended :)

**Comment by johnleider** [comment]
Awesome. Would you consider this resolved then?

**Comment by bjendyk** [comment]
Yes, this solves the issue I had 👍

**Comment by juppdes** [comment]
@bjendyk  can you post the solution? (codepen)

**Comment by vibrates09** [comment]
https://codepen.io/sockhenzie/pen/dqYdgK?editors=1011

**Comment by miljacb** [comment]
You should just add <v-list-tile slot="activator"> instead of <v-list-tile slot="item">.

**Comment by miljacb** [comment]
You should just add slot="activator" instead of slot="item". Just for future reference
