### ISSUE TITLE
[Bug Report] Pushing item to v-carousel model array does not render

### ISSUE THREAD

**Issue by mdsaudali365** [vuetifyjs/vuetify#5102]
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Firefox Developer edition 63.0b6
OS: Windows 10 64-bit

### Steps to reproduce

1. Click the Load New Button
2. Look on the console logs to check if it was working
3. See the carousel if the image will be loaded

### Expected Behavior
The image will display on the carousel

### Actual Behavior
The image is not showing, and saw on the inspector that it was always "display: none"

### Reproduction Link
https://codepen.io/mdsaudali365/pen/mGGYNz?editors=1011

---

### Additional Comments:
Referred #4493: It said that pushing an item to the carousel works. It does not work for me, am I doing something wrong? https://vuejs.org/v2/guide/list.html#Array-Change-Detection states that pushing should trigger view update.

**Comment by mdsaudali365** [comment]
Do you know if it is possible to call the cycle function manually?

**Comment by jan-san** [comment]
A workaround could be to add ` v-if="items.length"` to the `v-carousel` component:
https://codepen.io/anon/pen/gQGdrE?editors=1011

**Comment by johnleider** [comment]
The original issue has since been fixed. @damianac please report your bug as a separate issue.
