### ISSUE TITLE
Datepicker bug in dynamic fields

### ISSUE THREAD

**Issue by leonfather** [vuetifyjs/vuetify#511]
Hello, 
Firstly i want to thank the creator of vuetify for this awesome and wonderful job.
I need help to reselve this bug :
![piiik](https://cloud.githubusercontent.com/assets/25527820/25896180/fee469f6-357a-11e7-970a-8a310f1429c8.gif)

Bugs : 
1- Escape don't work.
2- When i select date for the fist time i get today selected, i must select twice to select the date i want.
3- When click + to add more lines with more text fields picker i get the bug in picture

This is loop that populate my pickers fields
```

<v-dialog
                                persistent
                                v-model="modal"
                                lazy
                        >
                            <v-text-field
                                    slot="activator"
                                    label="Date Expiry"
                                    v-model="inventory.dateExpiry"
                                    readonly
                            ></v-text-field>
                            <v-date-picker v-model="inventory.dateExpiry" scrollable></v-date-picker>
                        </v-dialog>

```

**Comment by johnleider** [comment]
As far as having to click twice to change date, that has been fixed. For the rest, could you please supply a reproduction example on codepen or jsfiddle please.

**Comment by johnleider** [comment]
I will re-open once you reproduce.
