### ISSUE TITLE
v-combobox error when 0 is selected

### ISSUE THREAD

**Issue by filipwronski** [vuetifyjs/vuetify#5110]
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.17
Browsers: Google Chrome  68.0.3440.106
OS: Fedora 28 

### Steps to reproduce
Select an item "0" from menu / Type on a keyboard 0

### Expected Behavior
0 should appear in input

### Actual Behavior
Input is empty

### Reproduction Link
https://codepen.io/filip0822/pen/qMQNGy

I'm using v-model.number

**Comment by Bbansjkl** [comment]
Also happens if you only use v-model and select a number `0` from the array of provided items. Typing a `0` works in that case.
As a workaround you can provide the `0` as a string in the selectable array
Reproduction: https://codepen.io/anon/pen/PyqdOr

**Comment by filipwronski** [comment]
@Bbansjkl Thanks for answer that's right. Another one workaround is using v-combobox  with chips. It's work with number 0.
