### ISSUE TITLE
[Bug Report] Vuetify table

### ISSUE THREAD

**Issue by AleksandarMiha** [vuetifyjs/vuetify#5115]
### Versions and Environment
**Vuetify:** 1.2.4
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
When i download my table i got additional space row.

### Expected Behavior
On normal <table> a got everythink good

### Actual Behavior
i got additional row

### Reproduction Link
[https://codepen.io/anon/pen/bxOVVQ?editors=1010](https://codepen.io/anon/pen/bxOVVQ?editors=1010)

### Other comments
How to not print space row.

**Comment by nekosaur** [comment]
This is not a problem with vuetify but with your code for generating the excel file. I would suggest you use an existing library instead, such as https://github.com/SheetJS/js-xlsx
