### ISSUE TITLE
[Feature Request] vuetify js custom ctyle

### ISSUE THREAD

**Issue by iTaurus85** [vuetifyjs/vuetify#5119]
### Problem to solve
How can I edit/change vuetify css styles without variables?Currenty, v-btn has its styles, and scoped doesn't help to add my own style. I have to use !important for each single css property, that's annoying. Are there any other ways to use my own custom styles for any vuetify component?
Here is the [link](https://codepen.io/iTaurus85/pen/XPoXeE) 

### Proposed solution
It says, that "scoped" helps to imply custom style.

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
