### ISSUE TITLE
Stepper buttons disappear with Chrome 58

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#512]
### Steps to reproduce
1. Visit https://vuetifyjs.com/components/steppers
2. If the Continue and Cancel buttons are visible (sometimes they disappear right after the page is loaded), click on Continue until you finish all steps and the first step appears again

The problem occurs only with Chrome 58. It did not occur with Chrome 57 or with Firefox 53.0. OS is Ubuntu 17.04.

### Versions
Versions installed on https://vuetifyjs.com/components/steppers

### What is expected ?
The Continue and Cancel buttons should always be visible

### What is actually happening ?
The Continue and Cancel buttons are invisible sometimes with Chrome 58.

### Reproduction Link
https://vuetifyjs.com/components/steppers

**Comment by smares** [comment]
I should mention that even though the buttons are invisible, they are there and work when clicked.

**Comment by johnleider** [comment]
I can see this bug on production and I can confirm it has been fixed in dev.

**Comment by jteppinette** [comment]
I also see the `<v-text-field>` get scrambed in the stepper on Chrome 58 and 0.11.1

I haven't tested this on develop, but I assume it is a similar issue.

<img width="1275" alt="screen shot 2017-05-16 at 3 20 05 pm" src="https://cloud.githubusercontent.com/assets/28163511/26124202/a1fb9d1a-3a4b-11e7-9275-25eaad2dbf87.png">

**Comment by jteppinette** [comment]
My issue was resolved by following the guidance in https://github.com/vuetifyjs/vuetify/issues/521

**Comment by johnleider** [comment]
This has cropped back up on dev, re-opening so I don't forget.
