### ISSUE TITLE
[Bug Report] Nested list groups close after the parent is reopened

### ISSUE THREAD

**Issue by dundich** [vuetifyjs/vuetify#5120]
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Chrome 68.0.3440.106
OS: Windows 10 Version 1709 (Build 16299.431)

Steps to Reproduce:
1. Navigate to https://vuetifyjs.com/en/components/navigation-drawers#example-nested
2. Click to expand Users Tile
3. Click to expand Admin Tile
4. Click to collapse Users Tile
5. Click to expand Users Tile
6. Notice that Admin group expands quickly before snapping back to collapsed.

_Originally posted by @XMoose25X in https://github.com/vuetifyjs/vuetify/issues/4808#issuecomment-417402760_

**Comment by dundich** [comment]
~ Vuetify: 1.2.4

**Comment by KaelWD** [comment]
f90d17b did nothing, the actual issue is in v-list/v-list-group

```
watch: {
  isActive (val) {
    if (!this.subGroup && val) {
      this.listClick(this._uid)
    }
  },
```

It needs to close children when it is being closed (`!val`), not when being opened again. The problem is that `listClick` is only provided from v-list instead of each individual group.

**Comment by jd-0001** [comment]
Hi, @KaelWD Can I know if there's any milestone/ETA for this issue?

**Comment by johnleider** [comment]
More than likely won't happen in v2.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
