### ISSUE TITLE
[Bug Report] Bind a method on click on arrow_down of header of v-expansion-panel-content

### ISSUE THREAD

**Issue by trollepierre** [vuetifyjs/vuetify#5122]
I would like to provoke a call to a method on click on arrow_down of v-expansion-panel-content

### Versions and Environment
Vuetify: 1.1.10
Vue: 2.5.17
Browsers: all
OS: all

### Previously worked in:
Vuetify: never
Vue: never

### Steps to reproduce

use v-expansion-panel, v-expansion-panel-content and add an onClick method on header of v-expansion-panel-content

### Expected Behavior

click on arrow_down will call `onClick` method

### Actual Behavior

click on arrow_down will not call `onClick`

### Reproduction Link

https://codepen.io/trollepierre/pen/MqZOqK?editors=1111

```
<v-expansion-panel-content
      :readonly="!REQUEST_IS_VALID"
      lazy>
      <div
        slot="header"
        @click="onClick()">
        choix des jours & des horaires
      </div>
      <v-container fluid>
        <datetime-request-form/>
      </v-container>
    </v-expansion-panel-content>
```

---

**Comment by johnleider** [comment]
This has been resolved in v2.0. The @click method has moved to the content so it would look like this:

`<v-expansion-panel-item @click="onClick">`
