### ISSUE TITLE
v-pagination button cutting the page number

### ISSUE THREAD

**Issue by Chiyaoching** [vuetifyjs/vuetify#5126]
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: chrome 69.0.3497.92
OS: macOS 10.13.6

### Steps to reproduce
Set the length amount with 100000(or more) in v-pagination

### Expected Behavior
should be show the all number digits in page button

### Actual Behavior
the page number out of page button

### Reproduction Link
https://codepen.io/sevenchi/pen/JaxPaj

---

### Additional Comments:
maybe set the min-width with 34px in class .v-pagination__item will solve this issue.

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/pull/5128
