### ISSUE TITLE
[Bug Report] edit-dialog in data table is transparent

### ISSUE THREAD

**Issue by Moedav** [vuetifyjs/vuetify#5127]
### Versions and Environment
**Vuetify:** 1.2.4
**Last working version:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Open inline editing on a table

### Expected Behavior
the dialog should not be transparent. 

### Actual Behavior
the dialog is transparent 

### Reproduction Link
[https://codepen.io/anon/pen/QVYydj?&editors=101](https://codepen.io/anon/pen/QVYydj?&editors=101)

### Other comments
if i use the dark theme, the dialog isnt transparent but the text is white

**Comment by jacekkarczmarczyk** [comment]
Looks like https://github.com/vuetifyjs/vuetify/commit/9bf02afc57fe639151c1250e28ef0c5dc1492cc8

**Comment by ais-one** [comment]
Is there a temporary fix for this that we can implement? Had been playing around with the css but no result

**Comment by ais-one** [comment]
> > Is there a temporary fix for this that we can implement? Had been playing around with the css but no result
> 
> Hey @ais-one, I was able to fix it doing this:
> 
> ```css
> .theme--dark .v-menu__content {
>   background-color: #424242;
> }
> .theme--light .v-menu__content {
>   background-color: #ffffff;
> }
> ```
> 
> Let me know if that works for you.

It does not seem to work, where should I put the CSS code?

Currently...

<template>
<v-data-table />
</template>

<script>
</script>

<style scoped>
.theme--dark .v-menu__content {
  background-color: #424242;
}
.theme--light .v-menu__content {
  background-color: #ffffff;
}
</style>

**Comment by ais-one** [comment]
Interesting, you solution does seem to work..., just not on my code.

Below is a codepen which shows it working!

https://codepen.io/anon/pen/qJbPbK

**Comment by ais-one** [comment]
It worked after I took out the scoped keyword...

```
<style lang="css" scoped>
```

Looks like I need to go back to CSS coding school because I do not even know what I am doing...
