### ISSUE TITLE
v-data-table: search in local time instead of UTC

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#5129]
### What problem does this feature solve?
The datatable component has an inbuilt search function. I think it just uses plain text search which works pretty well. Except in the case of ISO datetime strings such as `2018-09-20T12:15:49.753Z`.

The problem is that the above date string is taken at `14:15` local time and not `12:15`. So the datatable search actually does not find the above date string when searching for `14:15`, which is what the user thinks is the correct time.

So I can fix this by implementing a custom search filter, that's no problem. But it seems to me like this is a very common problem so I would like to request that the default datatable search will handle this case.

### What is your proposed solution?
No change to the API. 
Add a regex to check if a value is an ISO datetime string and if so, perform the search in the toString() version of the local time.

If a regex would slow things down too much, maybe add a `type` property in the header fields:
```
{
  text: 'Date Created',
  sortable: true,
  value: 'createdAt',
  type: Date
}
```

**Comment by nekosaur** [comment]
Solution to this is column filtering https://github.com/vuetifyjs/vuetify/issues/3102
