### ISSUE TITLE
Data table "item-key" generates warning even if key exists

### ISSUE THREAD

**Issue by tonybranfort** [vuetifyjs/vuetify#5134]
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Chrome 69.0.3497.100
OS: Windows

### Steps to reproduce
Create a `v-data-table` table using `item-key` that references a property in the data array. 

### Expected Behavior
No console errors or warnings

### Actual Behavior
Console warning `"[Vue warn]: Property or method 'name' is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties."`

### Reproduction Link
https://codepen.io/anon/pen/xaMype

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/zJeyNw
