### ISSUE TITLE
[Feature Request] Nuxt, SSR, different theme per request

### ISSUE THREAD

**Issue by jardakotesovec** [vuetifyjs/vuetify#5140]
### What problem does this feature solve?

We use Nuxt with veutify for SSR. Issue is that if I pass theme via Vue.use(Veutify, {theme: ...}) on server, I can't change theme per request, because its set globally so whatever theme is set first that will sit there forever. Changing this global theme object is not solution as several request that interleaves could end up with wrong theme (race condition).

### What is your proposed solution?

I investigated how this could be easily scoped and nice solution seems to me to have prop `theme` for `VApp` component, which is responsible for applying the theme. 

As result VApp would apply the theme from props if is being passed or the global theme if props is not available.

As workaround I extended VApp like this:
```
import * as Theme from 'vuetify/es5/util/theme'

const MyApp = Vue.component('VApp').extend({
  name: 'my-app',
  props: ['myTheme'],
  computed: {
    parsedTheme() {
      return Theme.parse(this.myTheme)
    }
  }
})
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Well it is implemented, theme is set by `new Vuetify()` per request now.
