### ISSUE TITLE
[Bug Report] v-menu appears behind v-dialog in Safari when a v-toolbar is involved

### ISSUE THREAD

**Issue by medeman** [vuetifyjs/vuetify#5141]
The `<v-menu>` appears behind the `<v-dialog>` if it is inside a `<v-toolbar>`.

### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Safari
OS: macOS 10.13 / iOS 11.4 / iOS 12.0

### Steps to reproduce

After the Codepen has loaded, click on the filter button in the dialog.

### Expected Behavior

The `<v-menu>` should appear in front of the `<v-dialog>`.

### Actual Behavior

In Safari on macOS and iOS, the `<v-menu>` appears behind the `<v-dialog>` and the overlay.

### Reproduction Link

https://codepen.io/anon/pen/qMvXaX

---

### Additional Comments:
This has to do with the `getZIndex()` function from the `util/helpers.ts` file. It returns `0` as z-index because the `<nav>` element from the `<v-toolbar>` has a computed z-index of `0` on Safari for some reason.

This issue is probably related to #2111. Pull request #3639 helps, but it doesn't work when a `<v-toolbar>` is involved since `<nav>` still has a computed z-index of `0`.

This issue doesn't occur in Chrome or Firefox.

**Comment by johnleider** [comment]
This has been resolved for v2.0 https://codepen.io/johnjleider/pen/agzOoL

**Comment by KaelWD** [comment]
@johnleider that commit didn't change anything, it was from the toolbar's `translateY` which has moved to v-app-bar.

@medeman tracking this as #5351 now
