### ISSUE TITLE
[Bug Report] v-overflow-btn has extra top padding

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#5142]
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Safari 12.0, Chrome 69.0.3497.100, Opera 55.0
OS: macOS 10.13.6

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Go to the bottom of the Vuetify button doc (see link), section "in toolbar"
Try to change the font or ratio.
Try to change the font to Verdana.

### Expected Behavior

Overflow buttons nicely integrated in the toolbar

### Actual Behavior

Bugged overflow buttons 

### Reproduction Link

[https://vuetifyjs.com/en/components/buttons](https://vuetifyjs.com/en/components/buttons)
---

**Comment by KaelWD** [comment]
I assume you're talking about this:
![image](https://user-images.githubusercontent.com/16421948/45891263-782c8700-be08-11e8-9adf-f9466626b8be.png)

**Comment by johnleider** [comment]
Fixed in 86290bec6864a279885ef26c673a5b3128395af4
