### ISSUE TITLE
v-autocomplete with clearable and append-icon=null is unclearable

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#5146]
### Versions and Environment
Vuetify: 1.2.4

### Steps to reproduce
A `v-autocomplete` with both `clearable` and `append-icon=null` results in the clearable icon being unclickable and a not all the way to the end. See the repo link below.

### Reproduction Link
https://codepen.io/andrewharvey/pen/ZMZQmp?&editors=101

**Comment by KaelWD** [comment]
`append-icon="null"` is a string, you want to be using v-bind instead. 

![image](https://user-images.githubusercontent.com/16421948/45918259-93120080-bec7-11e8-84d9-c7b2b036b806.png)
![image](https://user-images.githubusercontent.com/16421948/45918264-ad4bde80-bec7-11e8-968d-688b4a687602.png)

**Comment by andrewharvey** [comment]
Oops, sorry yes if I use `:append-icon=null` then it works as expected.
