### ISSUE TITLE
[Feature Request] Add ability to click on v-progress-linear

### ISSUE THREAD

**Issue by rchaput** [vuetifyjs/vuetify#5147]
Hello

### Problem to solve
I want my users to be able to click on a **v-progress-linear** and react to this change (e.g. by updating the model). A current workaround (thanks to *tutsplus.com*) is to get the element through a CSS selector, query its width, and compare to the mouse position in the native js click event:
```js
onClickProgress (event) {
  let el = document.querySelector(".progress-linear__bar"),
      mousePos = event.offsetX,
      elWidth = el.clientWidth,
      percents = (mousePos / elWidth) * 100
  doSomething(percents)
}
```
```html
<v-progress-linear @click="onClickProgress($event)"></v-progress-linear>
```
However, this workaround is not ideal ; replacing it by a "vuetify" click event would make this code shorter, easier to read and less error-prone.

Such an interactive progress bar would be an alternative to **v-slider**, with a different appearance (sometimes more pertinent in regard to your interface).

### Proposed solution
Please add a click handler to **v-progress-linear**, which will provide the new progress as an argument (a percentage value, ranging from 0.0 to 1.0 maybe, or 0 to 100)

**Comment by Elfayer** [comment]
It really seems to be a slider you're looking for. I'd suggest you override the `v-slider` css to get to your expected result. =/

**Comment by jacekkarczmarczyk** [comment]
@Elfayer linear progress would play nicely with video players, so I'd say it's a valid feature request
