### ISSUE TITLE
v-img produces node mismatch on nuxt

### ISSUE THREAD

**Issue by rnenjoy** [vuetifyjs/vuetify#5153]
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.17
Browsers: Chrome 69
OS: Windows 10

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Cannot reproduce using codepen. This requires nuxt SSR rendering.

### Expected Behavior

v-img produces node mismatch.

mismatching childNodes vs. VNodes:  
NodeList(2) [div.v-responsive__sizer, div.v-image__image.v-image__image--preload.v-image__image--cover] 

(3) [VNode, VNode, VNode]
0: VNode {tag: "div", data: {…}, children: undefined, text: undefined, elm: div.v-responsive__sizer, …}
1: VNode {tag: "vue-component-215-transition", data: {…}, children: undefined, text: undefined, elm: div.v-image__image.v-image__image--preload.v-image__image--cover, …}
2: VNode {tag: "div", data: {…}, children: undefined, text: undefined, elm: div.v-responsive__content, …}

### Actual Behavior
From what I can see SSR produces two children.
```
<div class="v-responsive__sizer" style="padding-bottom: 66.65%;"></div>
<div class="v-image__image v-image__image--cover" style=""></div>
```

But on client we also have a third child
`<div class="v-responsive__content"></div>`

Which causes the error.

### Reproduction Link

---

**Comment by 8bu** [comment]
Got the same problem, even with v-carousel-item. Sometimes they render `<div src="...">` but it's gone when we try to refresh the page. Weird behavior

**Comment by d1buts** [comment]
Same trouble after update `v-card-media` to `v-img` - `Mismatching childNodes vs. VNodes`

**Comment by NataliaTepluhina** [comment]
Same issue with Nuxt website after updating `v-card-media` to `v-img`

**Comment by jdkahn** [comment]
getting same as well

**Comment by dotneet** [comment]
I got the same issue.
This error was gone after specifing `:aspect-ratio`.

**Comment by dotneet** [comment]
The root cause of this issue is setting a property that affect rendering nodes in beforeMount hook.
I think that the only way to get around the changing nodes in beforeMount hook is specifying `:aspect-ratio`.

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VImg/VImg.ts#L172
```js
this.aspectRatio || this.pollForSize(image)
```

`calculatedAspectRatio` affects rendering nodes.

```js
    pollForSize (img: HTMLImageElement, timeout: number | null = 100) {
      const poll = () => {
        const { naturalHeight, naturalWidth } = img

        if (naturalHeight || naturalWidth) {
          this.calculatedAspectRatio = naturalWidth / naturalHeight
        } else {
          timeout != null && setTimeout(poll, timeout)
        }
      }

      poll()
    },
```

**Comment by KaelWD** [comment]
Thanks for investigating this @dotneet. It's probably safe to use `mounted ()` instead there.

**Comment by KaelWD** [comment]
I can't reproduce this, but I'll add the speculative fix anyway.

**Comment by Globerada** [comment]
Same here with v-img

**Comment by matjaeck** [comment]
Defining an aspect ratio doesn't fix it for me. I'm using the nuxt create-app template and it won't let me use the image component. Seems like it thinks it is a custom component. 

`error Require self-closing on Vue.js custom components (<v-img>) vue/html-self-closing`
