### ISSUE TITLE
[Feature Request] Card gradient background / Text Cover

### ISSUE THREAD

**Issue by Th0masP4ttz** [vuetifyjs/vuetify#5154]
vuematerial.io have a very helpful card feature I would love for you to apply. Gradient backgrounds! 

   
![vm_card](https://user-images.githubusercontent.com/40304925/45942200-6c43ef00-bfd9-11e8-8188-c0a040ba4190.JPG)

### What problem does this feature solve?

This enables the possibility to display larger images in cards and place cover text, as opposed to have a lot of unused space in the current set of card themes on vuetify. The gradient background and cover text would also be less restrictive in terms of the type / colour of images that can be used.  

![card_vuetify](https://user-images.githubusercontent.com/40304925/45942492-8af6b580-bfda-11e8-928b-12bd9421ceae.JPG)
![card_vuetify_02](https://user-images.githubusercontent.com/40304925/45942493-8b8f4c00-bfda-11e8-83d9-cbf1def31daf.JPG)

### What is your proposed solution?

Additional card options / full image backgrounds with gradient overlay and text holder. 

Many Thanks

**Comment by KaelWD** [comment]
This can be implemented with v-img and some basic CSS: https://v2.vuetifyjs.com/en/components/images/#fixed-ratio

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
