### ISSUE TITLE
[Bug Report] v-menu inside v-tabs with 'attach' prop cutting off

### ISSUE THREAD

**Issue by ram33** [vuetifyjs/vuetify#5156]
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Chrome
OS: Mac

### Steps to reproduce
Created a menu inside tab (inspired from [this](https://vuetifyjs.com/en/components/tabs#example-overflow-to-menu)) with 'attach' prop on menu(fixed toolbar). Click on any menu item.

### Expected Behavior
Expected sub menu to be visible properly 

### Actual Behavior
Sub menu getting hidden under tabs

### Reproduction Link
https://codepen.io/ram33/pen/zJQxMo?&editors=101

---

### Additional Comments:
If I don't use 'attach' prop on menu, it works as expected. Also I have tried removing (overflow:hidden, contain:content) on v-tabs__wrapper which fixed the issue but its breaking pagination arrows.

**Comment by johnleider** [comment]
This is a valid report and a tricky situation. This would have to be address in 2.0 if anything though.

**Comment by KaelWD** [comment]
You can attach to the toolbar instead, but it doesn't position properly: https://codepen.io/anon/pen/bmXzdG?editors=1010

**Comment by KaelWD** [comment]
Not gonna get to this in 1.4, it needs a rewrite of how the activator position is determined.
