### ISSUE TITLE
A pill shaped input fields

### ISSUE THREAD

**Issue by baibhabmondal** [vuetifyjs/vuetify#5161]
### What problem does this feature solve?
As Google rolled out the new material styles, And all you can see is pill shaped fields, buttons everywhere. As a normal internet user, most of my time is invested on Google, be it, the search itself, or Drive or Gmail, or any other products. When I browse through various sites having similar UI, I feel more comfortable. And Although I could override the style and make it appear as a pill, But it would be convenient for any user if he/she can add just an attribute. 

### What is your proposed solution?
Just make a border-radius of the inputs 50px, or similar, to make it appear as a pill. It exists for v-btn but not for any input fields.

**Comment by niutech** [comment]
These are called _rounded corners_ and you can add them yourself by CSS classes:

```
.v-btn--round-left {
        border-top-left-radius: 28px;
	border-bottom-left-radius: 28px;
}
.v-btn--round-right {
	border-top-right-radius: 28px;
	border-bottom-right-radius: 28px;
}
```

See the [demo](https://codepen.io/anon/pen/XPwaVm?editors=1100).

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/45959579-d9f31980-bfdf-11e8-9373-822a9b372317.png)

MD2 will be handled in v2.0
