### ISSUE TITLE
[Feature Request] add label prop to v-rating

### ISSUE THREAD

**Issue by JeremiahPinto** [vuetifyjs/vuetify#5167]
### What problem does this feature solve?

The addition of the label prop (with values passed as an array) would be able to clarify what each icon of the rating system means. This would vastly improve UX when used.

### What is your proposed solution?

The label could be displayed above or below each rating icon
Example for rating above and the extremities of the rating system:
https://codepen.io/jeremiahpinto/pen/qMzxmP

Image here in case link breaks in future:
![image](https://user-images.githubusercontent.com/24516879/46039891-6d902b80-c141-11e8-9797-2c1868d1c4cc.png)

**Comment by johnleider** [comment]
This is supported in Vuetify 3:

```html
<v-rating :item-labels="['Good', null, null, null, 'Bad']" />
```
![image](https://user-images.githubusercontent.com/9064066/135144041-c362bdf5-600f-4727-8c37-aaef768fe702.png)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
