### ISSUE TITLE
how to run vuetify project on local network?

### ISSUE THREAD

**Issue by maxzhou0** [vuetifyjs/vuetify#5169]
I've noticed the project used external css link , but my site was disconnected from the Internet , is there an option for local distribution?

**Comment by Elfayer** [comment]
Maybe this helps: https://github.com/vuetifyjs/a-la-carte/blob/master/template/src/main.js

**Comment by maxzhou0** [comment]
vuetify use google font , if can't reach google font, the layout will mess up. 
here's the solution i thought

**Comment by jacekkarczmarczyk** [comment]
Use vue-cli-plugin-vuetify and answer "Yes" to "Use fonts as a dependency (for Electron or offline)?" question

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by maxzhou0** [comment]
> Use vue-cli-plugin-vuetify and answer "Yes" to "Use fonts as a dependency (for Electron or offline)?" question
> 
> The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

i made a new project use vue cli 3 and vuetify plugin and use fonts as a dependency , the default setting missing the module material-design-icons-iconfont, and gives error when building, so i had to install it manually, is it a bug?

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
