### ISSUE TITLE
Select is hidden by tabs

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#517]
### Steps to reproduce
Try to pick item in select component

### Versions
vue@2.3.3
vuetify@0.11.1

### What is expected ?
Select should visible completely

### What is actually happening ?
Part of select is hidden by tab item

### Reproduction Link
http://codepen.io/darkside73/pen/NjyZNX

**Comment by johnleider** [comment]
So this is a usability issue as tabs are overflow hidden for the transition. I'll try to move that overflow to be dynamically added with the transition so that while it is resting you don't experience this.
