### ISSUE TITLE
[Bug Report] v-select does not render correctly in IE11 when align-center present in v-layout parent

### ISSUE THREAD

**Issue by philnichols** [vuetifyjs/vuetify#5171]
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Nuxt: 2.0.0
Browsers: IE11
OS: Windows 10

### Steps to reproduce
Add in [align-center] to the [v-layout] parent tag.

### Expected Behavior
The select label should appear as normal, as it does in Chrome.

### Actual Behavior
The "Solo field" label is hidden and the width of the component collapses.

### Reproduction Link
https://codepen.io/philnichols/pen/GXVYJy

---

### Additional Comments:

Here is a screen shot of the issue:

![v-select](https://user-images.githubusercontent.com/6458788/46089913-7ca9c480-c1a7-11e8-9b07-6218d75dbe5d.PNG)

babel-polyfill@6.26.0 is installed.

I am a Vuetify Noob!

**Comment by johnleider** [comment]
This is an issue with ie11 and column flex. Here is a workaround: https://codepen.io/johnjleider/pen/voYMJw
