### ISSUE TITLE
[Bug Report] All items are active when both scoped-slots are used in v-select

### ISSUE THREAD

**Issue by safakadir** [vuetifyjs/vuetify#5176]
The issue happens for selection components: v-select, v-autocomplete, v-combobox
When scoped-slots 'item' and 'selection' are both used and an item is selected, all items in the list appear to be active.
Setting the property 'item-text' to a dummy field helps. I know that missing item-text property while using return-object is not normal. But in my case, since both scoped slots are used, the item-text property does not mean something, I guess.

### Expected Behavior
It should highlight (make its class active) only the selected item in the list.

### Actual Behavior
It makes all items in the list active and highlighted.

### Steps to Reproduce
In a v-select, use both scoped slots 'item' and 'selection', use return-object property, don't set item-text property. And make a selection.

### Reproduction Link
Here is a codepen link referencing the issue. First v-select is behaving normal, second is not.
https://codepen.io/safakadir/pen/LJwBgq

**Comment by darkopetreski** [comment]
This happens also to me.

**Comment by johnleider** [comment]
The default values for `item-text` and `item-value` are **text** and **value**. If you are not using these values, you need to specify them.
