### ISSUE TITLE
[Bug Report] v-expansion-panel element does'nt open in index mode

### ISSUE THREAD

**Issue by GRUXXKi** [vuetifyjs/vuetify#5178]
### Versions and Environment
**Vuetify:** 1.2.4
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64

### Steps to reproduce
Click on add button, an element is added.

### Expected Behavior
The added element is automatically opened but changing the panel index value.

### Actual Behavior
When changing the index panel value, the element is not opened.

### Reproduction Link
[https://codepen.io/anon/pen/jeNGWQ?editors=1011#anon-login](https://codepen.io/anon/pen/jeNGWQ?editors=1011#anon-login)

**Comment by KaelWD** [comment]
set the active index in a `$nextTick`
