### ISSUE TITLE
Property gets deleted from object when clearing "v-select" (instead of being set to an empty string).

### ISSUE THREAD

**Issue by joshfoskett** [vuetifyjs/vuetify#5179]
### Versions and Environment
Vuetify: 1.2.5
Vue: 2.5.17
Browsers: Chrome
OS: macOS High Sierra

### Steps to reproduce

Clear the first select, and notice that `item.value.deep` gets deleted.

### Expected Behavior

The property should remain and be set to an empty string.

### Actual Behavior

The property is deleted from the object.

### Reproduction Link

https://codepen.io/anon/pen/JaxBYd

**Comment by KaelWD** [comment]
It isn't removed, it's set to `undefined`
