### ISSUE TITLE
[Feature Request] v-data-table "Load More" Functionality

### ISSUE THREAD

**Issue by big213** [vuetifyjs/vuetify#5181]
### What problem does this feature solve?
I am using the v-data-table for listing many items, which may need to be sorted server-side. I noticed that v-data-table uses pagination, and it requires the total count of the items as a prop for server-side pagination. However, fetching the total count is another database operation that must be fetched with each call, and a common solution these days is to not even show the total count, but just keep loading more as you scroll down, or maybe put a "Load More" button at the bottom of the page to load the next 15 records. This would save the effort of having a total count, and in my opinion, it is a smoother way of solving the pagination issue.

### What is your proposed solution?
Add a new prop on `v-data-table`, maybe `load-more`, that will remove the standard pagination interface, and add a "Load More" button to the bottom, which will load the next 15 or so records, if they exist. Perhaps the Load More section can be added as a slot, so that it can be customized. It would be nice to allow support for automatically triggering "Load More" if the user scrolls past a certain point as well, but I'm not exactly sure how this would work.

**Comment by nekosaur** [comment]
I am leaning towards not implementation this as any kind of special case. Instead a basic load more version should be possible to implement in user land with a footer slot.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
