### ISSUE TITLE
[Bug Report] hidden v-tabs active tab without slider

### ISSUE THREAD

**Issue by maryasov** [vuetifyjs/vuetify#5182]
### Versions and Environment
**Vuetify:** 1.2.5
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64

### Steps to reproduce
Click "SECOND" tab, then will open nested tabs control. Tab "Plans" will be active, but there is no slider line shown

### Expected Behavior
recalculate width of appear element

### Actual Behavior
because element was hidden it cannot get(calculate) width of currently activated tab and store wrong element style for slider "left: 0px; width: 0px;"

### Reproduction Link
[https://codesandbox.io/s/xr7q9zl1qo](https://codesandbox.io/s/xr7q9zl1qo)

**Comment by johnleider** [comment]
You will need to conditionally render the child tabs in order to achieve this, or manually call the **callSlider** method. The component is rendered and not visible, there is no way for us to determine when that is actually showing.
