### ISSUE TITLE
v-data-table: Allow per-row forms --> render table using div { display: table; }

### ISSUE THREAD

**Issue by peterthomassen** [vuetifyjs/vuetify#5186]
### What problem does this feature solve?
I am working on an application that provides in-place editing of a `v-data-table` on a per-row basis. To that end, I'd like to make each table row a `v-form` so that per-row submission is possible without complicated internal state tracking.

However, you can't add a `form` tag as a child tag in `table` or  `tr`, but only within table cells (too narrow) or outside the table (too wide). There should be a way to have `v-data-table` without this limitation.

Making this possible would give much greater flexibility when working with tables, with no downsides for users who don't need it.

### What is your proposed solution?
By means of a flag, render `v-data-table` using a `div` that has the CSS property `display: table` set (instead of using a `table`).

The visual rendering would remain unchanged, but the constraint described above would be lifted.

**Comment by jacekkarczmarczyk** [comment]
That's part of the table refactor PR https://github.com/vuetifyjs/vuetify/pull/3833
