### ISSUE TITLE
Using Select component scoped slots bug

### ISSUE THREAD

**Issue by altinselimi** [vuetifyjs/vuetify#5187]
When using the scoped slot 'selection', after selecting an option, the input field is non writeable anymore

### Versions and Environment
Vuetify: 1.0.19
Vue: 2.0.15
Browsers: Chrome 68
OS: MacOS

### Steps to reproduce
1) Select an option from the list
2) Try to write anything in the input field

### Expected Behavior
Input field should work properly even after selecting an option

### Actual Behavior
Its not

### Reproduction Link
https://codepen.io/altinselimi/pen/QZWeqd?editors=1010

**Comment by johnleider** [comment]
You can't clear an autocomplete without clearable. If you want the field to be editable, use combobox. https://codepen.io/johnjleider/pen/bmwBEQ?editors=1011
