### ISSUE TITLE
Feature Request: v-text-field append-icon/prepend-icon event handlers

### ISSUE THREAD

**Issue by nasvillanueva** [vuetifyjs/vuetify#519]
`v-text-field` prepend-icon/append-icon event handlers (e.g: prepend-icon-click)

- Answer those questions:
  - What will it allow you to do that you can't do today?
    - It will allow us to set events for prepended/appended icons, just like the [Password Input](https://vuetifyjs.com/components/text-fields)  examples. If we can add events, we can toggle the visibility of password (changing type to text/password) using the prepended/appended icon.
  - How will it make current work-arounds straightforward?
     - I can't find any work-arrounds as of the time this was posted.

**Comment by nasvillanueva** [comment]
Looked through the code and it was already in the [Input Mixin](https://github.com/vuetifyjs/vuetify/blob/master/src/mixins/input.js).

Closing this issue.

**Comment by BenRichter** [comment]
Just as a reference: https://vuetifyjs.com/components/text-fields#api **append-icon-cb / prepend-icon-cb**

**Comment by KaelWD** [comment]
Please don't bump old closed issues.
