### ISSUE TITLE
[Bug Report] v-dialog usage with button outside the dialog component

### ISSUE THREAD

**Issue by Shlomit1414** [vuetifyjs/vuetify#5191]
### Versions and Environment
**Vuetify:** 1.1.13
**Vue:** 2.5.16
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
When trying to use the dialog with the button outside the component,
I'm facing an issue when opening the popup more than once. 
That's because of the Prop sent from the parent component which isn't aware of the popup closure and therefore is not updated to false when closing, so next time I click, the Prop doesn't change and therefore the popup is not triggered.
A workaround for now is to use the @input event in the dialog component, so in the dialog component I'm emitting an event to the parent in order to inform him that it is closed and the parent changes the Prop to false, and then the next click will change the prop to true and trigger the popup.
Is there a better workaround for this scenario?

### Expected Behavior
A better solution for splitting the dialog and the button into two components

### Actual Behavior
A complicated workaround

### Reproduction Link
[https://jsfiddle.net/royprigat/fhox0rd9/](https://jsfiddle.net/royprigat/fhox0rd9/)

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

This is not even a vuetify related question. Yes, you do need to proxy the value changes through your custom component if you want to be able to control the dialog from a parent component. See here for a simpler solution that what you have https://jsfiddle.net/0qg7vfyj/
