### ISSUE TITLE
[Bug Report] V-Dialog Activator slot does not honor block prop on V-Button

### ISSUE THREAD

**Issue by samuelcolburn** [vuetifyjs/vuetify#5193]
### Versions and Environment
**Vuetify:** 1.2.5
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
1. Make a v-dialog component
2. Use a button in the activator slot
3. Give the button the `block` prop

### Expected Behavior
The button should be full width.

### Actual Behavior
The button renders normal width.

### Reproduction Link
[https://codepen.io/smcolburn/pen/rqaKvb](https://codepen.io/smcolburn/pen/rqaKvb)

### Other comments
The dialog should respect the block prop from its activator slot.
While this functionality is available via `full-width` on `v-dialog`, I feel that has 2 issues:

1. It is counter-intuitive that the width of the button is specified on the dialog. Every other style option is defined on the button itself, and it behaves this way in all other contexts. The width of the button should be independent of its role as an activator, and the dialog should respect it.

2. The documentation for `full-width` does not explain what it does. If for whatever reason the dialog cannot inherit the width of the activator slot, then I feel the documentation needs to be clarified. Currently it reads: 
  > `full-width` Specifies the modal to force 100% width

  Which to me states that the *modal* is forced to 100% width, not its activator slot. It could be re-written:

  > `full-width` Forces the activator slot to 100% width.

And an additional example could added to the docs to explain this quirk.

**Comment by bestickley** [comment]
I have this same issue.

**Comment by johnleider** [comment]
This should be resolved when https://github.com/vuetifyjs/vuetify/pull/5318 is merged
