### ISSUE TITLE
mdc-shape: Add support for Shape

### ISSUE THREAD

**Issue by HelloWorldIL** [vuetifyjs/vuetify#5195]
### What problem does this feature solve?

This feature is a part of the [Material Design spec](https://material.io/design/shape/about-shape.html#shaping-material) and is usually used for [Theming](https://material.io/design/material-theming/overview.html#material-theming): 

> Shapes direct attention, identify components, communicate state, and express brand.

A baseline Material button             |  That same Material button, but customized
:-------------------------:|:-------------------------:
<img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Xft7ot5qXNAtJxcpbSDXaB0yivkO3m5f%2Ftheming-overview-applyingtheming-default.png" width="300" height="300">  |  <img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1t0RnZ5ppWG3AHbfvg65_xpSeXy8AGQj4%2Ftheming-overview-applyingtheming-shrine.png" width="300" height="300">

### What is your proposed solution?

The material components for the web use sass variables and mixins to implement shape, you can apply a shape theme to your entire app, or apply a shape to individual components.

Another "first class" implementation can be found in [Flutter material components](https://flutter.io/widgets/material/) (Flutter is Google’s mobile app SDK with native interfaces on iOS and Android - its awsome :smiley:)
Flutter's implomentation uses the [`Shape`](https://docs.flutter.io/flutter/material/Material/shape.html) property applied to each component individually and accepts a [`ShapeBorder`](https://docs.flutter.io/flutter/painting/ShapeBorder-class.html) object that has a property for an[`EdgeInsetsGeometry`](https://docs.flutter.io/flutter/painting/EdgeInsetsGeometry-class.html) object.

For example, the code for a raised button with a text of "Add To Cart" and a shape with beveled borders (The same shape of the button in the image above) with a radius of 7px.

 (The language is [Google's Dart](https://www.dartlang.org/))
`RaisedButton(
  child: Text('Add To Cart'),
  shape: BeveledRectangleBorder(
    borderRadius: BorderRadius.all(Radius.circular(7.0)))`

The CSS for such a feature can be simple, I found a way to accomplish this by using the [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) CSS property, here's a [short article detailing how to use this property](https://css-tricks.com/notched-boxes/).

There is a concern about browser compatibility, the clip-path property is supported on google chrome, opera and firefox (With the exception of path() and fill-box and stroke-box, both of which are not needed for this feature), however, it is not supported on internet explorer and edge, and will require a polyfill.

**Comment by johnleider** [comment]
Please see the #1 FAQ question https://vuetifyjs.com/getting-started/frequently-asked-questions
