### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#520]
Hi John and Vuetify team,

Just wanted to say thank you for Vuetify! I'm really appreciating the amount of effort you're putting into this and your responsiveness on issues.

So, thank you & keep up the good work!

 ❤️ 💙 💛 💚 💜

**Comment by johnleider** [comment]
I am very humbled by your comments, thank you. We will continue to work hard to provide an awesome platform for developers!

**Comment by luceos** [comment]
Hello @johnleider ,

Also a big thank you from me for your great efforts. I seriously love how you set up vuetify and how you keep working on the components and themes etc. Hope your efforts pay off with the (soon) commercial additions you plan.

Keep it up!
