### ISSUE TITLE
Closing v-dialog outside v-navigation-drawer  also closes temporary v-navigation-drawer

### ISSUE THREAD

**Issue by jiayingwang** [vuetifyjs/vuetify#5201]
### Versions and Environment
Vuetify:1.2.5
Vue:2.5.2
Browsers: Chrome 67.0.3396.99
OS:Windows 10

### Steps to reproduce

1. Open the temporary drawer by opening the codepen
2. Close the dialog by clicking I accept

### Expected Behavior

only the dialog will close, the drawer should remain open

### Actual Behavior

both the dialog and drawer close

### Reproduction Link

[https://codepen.io/darlingbx/pen/yRNQBQ](https://codepen.io/darlingbx/pen/yRNQBQ)

**Comment by johnleider** [comment]
The only way that will happen is if the dialog is a dependent of dialog. Otherwise it has no way of knowing.

https://codepen.io/johnjleider/pen/PyZyyP

**Comment by jiayingwang** [comment]
I wonder if it is possible to add a property for v-dialog to stop other events except the button click in the dialog?

**Comment by johnleider** [comment]
Maybe the **persistent** prop is what you are looking for.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
