### ISSUE TITLE
[Feature Request] v-autocomplete/v-select(multiple) v-on:change/input

### ISSUE THREAD

**Issue by wouterfovel** [vuetifyjs/vuetify#5205]
**v-autocomplete/v-select(multiple chips)**

v-on:change/input returns the whole items-list, not the last added/deleted item

### What problem does this feature solve?
We add employees to ambitions and perform a direct api update when we link/unlink an employee from an Ambition.
As we get back a list of items in v-on:change, we need to calculate the difference between the list we started from ... 

### What is your proposed solution?
Allow v-autocomplete multiple to return the item added/delete instead of the total list of items via the v-on:change/input

**Comment by johnleider** [comment]
Can you please provide an example of what you are trying to do that you are unable to? I don't quite understand the Feature Request

**Comment by wouterfovel** [comment]
```
<v-autocomplete
	:value="employeesCurrent"
	:items="employeesOfTeam"
	box
	chips
	color="blue-grey lighten-2"
	label="Select"
	item-text="name"
	item-value="name"
	multiple
	return-object
	v-on:change="autoCompleteChanged($event)"
>
```
The v-on:change="autoCompleteChanged()" returns the total list of all employees currently in the selection => v-on:change() returns Employee[].

What we are looking for is to have v-on:change() return a single Employee (= the one just added/deleted).
In this case, each time the user adds/deletes en Employee, we get back from v-on:change that specific added/deleted Employee ...

many thanks for the prompt reply :)

**Comment by johnleider** [comment]
I think that this should be a userland solution. Just use built in Vue functionality to handle this:

https://codepen.io/johnjleider/pen/OByoOq?editors=1011

**Comment by KaelWD** [comment]
Duplicate of #4054

**Comment by ehvetsi** [comment]
Sorry, 

I've used the scoped slots to resolve this.

Vuetify is Great!
