### ISSUE TITLE
[Bug Report] Data table: Paginate and sort server-side

### ISSUE THREAD

**Issue by MatheusSouzaCC** [vuetifyjs/vuetify#5206]
### Versions and Environment
Vuetify: 1.2.5
Vue: 2.5.3
Browsers: Chrome 69.0.3497.100
OS: Windows

### Steps to reproduce

The reproduction link is data table paginate and sort server-side exemple found in documentation. Just go to the second page and change the sorting (click to sort by calories ascending for example). Keep the eye at the console **when you click to sort**.

### Expected Behavior

If the current page is 2 and you click to sort, it should "request" only page 1.

### Actual Behavior

The method is being called twice. First, page 2 is requested and after that the page 1 is requested. This can be seen in the console.

### Reproduction Link

[Data table server side sorting with console logs](https://codepen.io/matheussouzacc/pen/BqoYvW?editors=1010)

---

### Additional Comments:
The problems is: with real api calls, if you ask page two and then ask page one, you don't know what the server will respond first. In other words, sometimes the first page will be displayed and sometimes the second.
The workaround for me was to debounce the getDataFromApi method, making sure that only the last call will be made (which is the page one request) but i don't know if this is right.

Thanks for the attention and sorry for my bad English.

**Comment by nekosaur** [comment]
Can't reproduce in latest stable (1.5.14) or 2.0
