### ISSUE TITLE
Stepper doc is outdated for v-divider

### ISSUE THREAD

**Issue by ouraios** [vuetifyjs/vuetify#521]
Hello,

I tried using the stepper component but apparently stepper header only the first one item according to the first example of the component doc : 

https://jsfiddle.net/fx4srqy1/

Maybe is it me doing something wrong ? I just c/c the example from the component doc and doesnt work properly :/

I'm excited to use this awesome component and library that Vuetify is !

Edit : Also i wanted to know if it was possible to do multiple step-content in one step ?

Edit 2 : Okay i found out what was going wrong. Apparently the examples of the stepper in the doc are outdated. Now the divider is `<v-divider></v-divider>` instead of `<v-divider />`, update it when you have time so that new beginners wont do mistakes. 
My first question still remain though.

**Comment by johnleider** [comment]
It's just a self closing tag. It can have issues on 3rd party sites but not inside actual projects. With that being said they are being removed.

**Comment by ouraios** [comment]
Hmmm weird because in a blank html page on local with just the needed dependcy for vue it doesn't work either on self close tag :/ (On Chrome)

**Comment by johnleider** [comment]
Blank html page would be the same logic as a codepen. I should of said, inside actual projects that use the build process.

**Comment by ouraios** [comment]
Oh okay i see, okay, actually i cant use the build process, so i'll just use normal opening and closing tag.
And i found my answer for multiple step-content in one step too.

Again, your work is awesome dude ! Thanks thanks thanks thanks ! Keep going that way !

**Comment by johnleider** [comment]
Thank you! As I said before, self closing tags are being removed from the docs, so in light of that, I'm going to close this ticket.

**Comment by jteppinette** [comment]
@ouraios great find! converting my `<v-divider />` to `<v-divider></v-divider>` fixed all of my issues with the stepper component e.g. disappearing `v-btn`, `v-select` menu being the incorrect width, and `v-text-field` bottom borders flying around

@johnleider I am surprised more people aren't having issues with this due to it being used in the current docs, any possibility of hot fixing the current documentation?
