### ISSUE TITLE
Testing `v-slider` @change events

### ISSUE THREAD

**Issue by michaelmosher** [vuetifyjs/vuetify#5214]
I'm working with the `v-slider` component, and I want to dispatch a Vuex action when the value changes. This is working as expected. However, simulating that change in a unit test (using vue-test-util's [setValue](https://vue-test-utils.vuejs.org/api/wrapper/setValue.html)) doesn't seem to work. 

### Versions and Environment
Vuetify: 1.2.5
Vue: ^2.5.2
Vuex: ^3.0.1
Vue-Test-Utils: ^1.0.0-beta.25
Jest: ^22.0.4
OS: macOS

### Steps to reproduce

SliderTest.vue

```javascript
<template>
  <v-app>
    <v-content>
      <v-container>
        <v-slider @change="onChange($event)">
        </v-slider>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
export default {
  methods: {
    onChange(value) {
      this.$store.dispatch('handler', value)
    }
  }
}
</script>
```

SliderTest.spec.js

```javascript
﻿import { mount, createLocalVue } from '@vue/test-utils'
import * as Vuex from 'vuex'
import Vuetify from 'vuetify'

import SliderTest from '@/components/SliderTest.vue'

const localVue = createLocalVue()
localVue.use(Vuex)
localVue.use(Vuetify)

describe('SliderTest', () => {
  const handler = jest.fn()
  const store = new Vuex.Store({
    state: {},
    actions: { handler }
  })

  const wrapper = mount(SliderTest, {
    store,
    localVue
  })

  it('reacts to a slider change', () => {
    const slider = wrapper.find('input')
    slider.setValue(30)

    expect(handler).toBeCalledWith(expect.anything(), 30, undefined)
  })
})
```

### Expected Behavior

Expected mock function to have been called with:
      [Anything, 30, undefined]

### Actual Behavior

It was not called.

### Additional Comments:

If there is a better way to test this behavior, I'd be glad to hear it, but it seems to me like the event doesn't fire if the value is changed programmatically.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.

With that being said, you can see some examples of how we unit test slider https://github.com/vuetifyjs/vuetify/blob/dev/test/unit/components/VSlider/VSlider.spec.js
