### ISSUE TITLE
[Bug Report] Height prop does nothing in inputs

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#5216]
### Versions and Environment
Vuetify: 1.2.5
Vue: 2.5
Browsers: Chrome
OS: OSX

height prop doesn't work but it is in the documentation.

![screen shot 2018-10-04 at 02 07 01](https://user-images.githubusercontent.com/1254613/46444345-38578f00-c77a-11e8-93d2-800a6f6a1c1b.png)

Example
https://codepen.io/atilkan/pen/LgNZXV?&editors=101

**Comment by MatheusSouzaCC** [comment]
If you set `height:100` you will see that it works. 

I noticed that if the textfield is `box` or `outline` min-height of 56px is set:
`.v-text-field--box .v-input__slot, .v-text-field--outline .v-input__slot {
    min-height: 56px;
}`

And for `solo` text fields, the min-height is 48px:
`.v-text-field.v-text-field--solo .v-input__control {
    min-height: 48px;
}`

So if the value is too low, it won't work.

**Comment by atilkan** [comment]
Bummer. I need to make it lower than that. So i can say it doesnt work.

**Comment by atilkan** [comment]
Thanks. I dont like css overwrite. I prefer writing myself. 
I leave an example here that might help someone. https://codepen.io/atilkan/pen/GYpRwx

**Comment by salespaulo** [comment]
Hi Vuetify Community,

Are anybody analysis this issue?

I needs set height to text-field outline but because it doesn't work.

I hope known more about the fix if anybody analysed this bug please talk to me to work into fix it.

Thanks!
Best regards!! :)

**Comment by Sabbir-Noire** [comment]
Is overwriting the CSS is still best way/only way to do it ?

**Comment by RSpeekenbrink** [comment]
Same thing here, it's still restricting the functionality of the height prop...

**Comment by kunalahirrao** [comment]
I am facing the same issue. Tried using deep selectors

**Comment by michaelprankl99** [comment]
Will it be fixed or not?

**Comment by atilkan** [comment]
@michaelprankl99 Not probably. Try to open issue for version 2 and wait for it to be solved for another year.

**Comment by ogmo0n** [comment]
use the dense prop - it solved my issue

**Comment by johnleider** [comment]
This is now possible as of the latest version.

https://codepen.io/johnjleider/pen/RwpEQYP

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by alatiqueeagle** [comment]
Try going lower than the min-height
