### ISSUE TITLE
[Feature Request] Any way to get current theme (dark/light) in a (customed) component?

### ISSUE THREAD

**Issue by kuanyui** [vuetifyjs/vuetify#5223]
First, thanks for this awesome Vue plugin.

I drew some glyph icons (.ttf; surely for those which cannot found in FontAwesome or MaterialDesign) for my project. So I'm trying to write a Vue component to wrap my icon, which can aware currently activated theme (`dark`/`light`) and change color for it.

> Basically, for consistence, I wish it can works just like `v-icon`, with same API, maybe...

However, after hours of research, I didn't find any reliable way/API/mechanism to get the activated theme of a specific level of a HTML/Component hierarchy, for coloring the glyph icons I made. 

I guess the possible way can be (may be silly, I'm not familiar the internal implementation of Vuetify):

1. event from parent (e.g. `v-app` ?) to notify all children (oops, `this.$broadcast` seems only available in Vue1.x; not available in Vue2.x)
2. Accessible in `this.$vuetify`?
3. A CSS class which Vuetify will automatically change its color ?
4. A HTML attribute directive which Vuetify will automatically add CSS classes such as `.theme--dark` to the HTML element, then user can decide the color in CSS (e.g. `.my-glyphicon.theme--dark { color: #fff; }`)?

**Comment by KaelWD** [comment]
VIcon uses this: https://github.com/vuetifyjs/vuetify/blob/dev/src/mixins/themeable.ts#L70

If you just want to consume the current theme, simply use `inject: ['theme']` and `this.theme.isDark`. We could probably expose a renderless component to make this easier though.

**Comment by kuanyui** [comment]
Thanks a lot, currently `inject: ['theme']` seems to work as same as what I've expected, I will keep paying attention on its behaviors.

**Comment by kuanyui** [comment]
A little question: when using `inject: ['theme']`, how to satisfy the type checking of TypeScript without `vue-class-component`?

**Comment by KaelWD** [comment]
```ts
interface Themeable extends Vue {
  theme: {
    isDark: boolean
  }
}

export default Vue.extend<Themeable>().extend({
  ...
```

**Comment by NickBolles** [comment]
@kuanyui I think you need `this.props.dark` and `this.props.light`

**Comment by johnleider** [comment]
@MajesticPotatoe can we prioritize this? Thank you.

**Comment by johnleider** [comment]
Closing this because it involves information related to non-public functionality.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
