### ISSUE TITLE
Textfield with type "number" accepts letter e

### ISSUE THREAD

**Issue by MaeseppTarvo** [vuetifyjs/vuetify#5224]
### Versions and Environment
Vuetify: 1.2.6
Vue: 2.5.17
Browsers: Chrome
OS: MacOS

### Steps to reproduce
Use textfield with type "number" and type letter "e", you can see it accepts it
<v-text-field
              type="number"
              label="Regular"
            ></v-text-field>

### Expected Behavior

Reject letters, even "e"
### Actual Behavior

Textfield accepts letter "e"

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in
