### ISSUE TITLE
[Feature Request] v-card-text multi line text wrap with truncate 

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5227]
### Problem to solve
Setting truncate out of the box will be very halpful if you have given height and text lenght is unpredicatable (news lists/blog posts lists)

### Proposed solution
no solution provided

**Comment by johnleider** [comment]
While I will be adding **measurable** to `v-card-text`, text clamping will be a `v-list-item` exclusive feature until line-clamp is properly supported in modern browsers. My suggestion would be use a library such as https://github.com/josephschmitt/Clamp.js.

**Comment by gileneusz** [comment]
I've found vue-line-clamp as a good alternative as well

https://github.com/Frondor/vue-line-clamp#readme
