### ISSUE TITLE
[Bug Report] Navigation drawer - Navigation drawer that is not visible shows in Chrome after resize

### ISSUE THREAD

**Issue by xneg** [vuetifyjs/vuetify#5228]
### Versions and Environment
Vuetify: 1.2.6
Vue: 2.5.17
Browsers: Chrome 69.0.3497.100
OS: Windows 10

### Steps to reproduce
<v-navigation-drawer  :value = "false"/>

1. Resize Chrome browser window.
2. Click **Maximize** button.

### Expected Behavior
Navigation drawer should dont slide out cause its value = "false".

### Actual Behavior
Navigation drawer slides out.

### Reproduction Link
https://codepen.io/xneg/pen/ReRERo

---

### Additional Comments:
Here is gif of bug.
![navigation-drawer-chrome-bug](https://user-images.githubusercontent.com/5748886/46537607-6217cf80-c8ba-11e8-9daf-fd2ece1fbb1b.gif)

**Comment by johnleider** [comment]
There are 2 ways you can disable this behavior. With the **disable-resize-watcher** and **stateless**. When not using any of these values, the drawer only uses your provided model for instantiation. It maintains an internal active state.

Example using stateless: https://codepen.io/johnjleider/pen/oazzML

I'm not sure to your use-case, but if you want the drawer to conditionally show, just use **temporary**. It doesn't react to size changes.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by xneg** [comment]
O, thank you. **stateless** is exact what I need. Sorry for wrong issue.
