### ISSUE TITLE
[Bug Report] v-switch and v-checkbox 'dirty' state cannot be read by vee-validate

### ISSUE THREAD

**Issue by taekni** [vuetifyjs/vuetify#5230]
### Versions and Environment
**Vuetify:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Mac OS 10.14

### Steps to reproduce
The codepen shows a `v-switch` field, a `v-checkbox` field and a standard `checkbox` field.

Change the value of each input and see the vee-validate field flags change accordingly.

### Expected Behavior
All 3 inputs behave the same - that the `dirty` flag is set once they've initially been interacted with.

### Actual Behavior
The standard checkbox has its flag correctly set, but the two vuetify components' `dirty` flag remains untouched.

### Reproduction Link
[https://codepen.io/anon/pen/rqLgbw](https://codepen.io/anon/pen/rqLgbw)

### Other comments
I'm assuming a) the functionality of the vuetify components is expected to be the same, as they build on top of a checkbox input; and b) that this concerns how vuetify interacts with said checkboxes, rather than being exclusively a vee-validate issue.

It seems very similar to this issue - https://github.com/vuetifyjs/vuetify/issues/4704

Though I'm also conscious of this - https://github.com/baianat/vee-validate/blob/master/src/core/field.js#L483 - which may make it, at least partially, a Mac problem.

**Comment by sh7dm** [comment]
Related to selectable mixin, will try to fix in `VSwitch` update

**Comment by KaelWD** [comment]
This issue is very old and there have been significant changes to both vee-validate and vuetify since. Please open a new issue with an updated reproduction if you are still experiencing problems with this.
