### ISSUE TITLE
[Feature Request] add new layouts for v-speed-dial

### ISSUE THREAD

**Issue by humblecoder** [vuetifyjs/vuetify#5231]
### Problem to solve
Preserves screen real estate and looks nice

### Proposed solution
It would be nice to have a [circular menu](https://codepen.io/suez/pen/vAais) (or generally non-standard) menu direction for both screen real estate and decoration and purposes

**Comment by BotellaA** [comment]
That feature would be awesome!

**Comment by jacekkarczmarczyk** [comment]
Another example https://codepen.io/gerrells-david/pen/GWqgKy

**Comment by titou10titou10** [comment]
+1000
