### ISSUE TITLE
[Feature Request] Make v-data-table more responsive

### ISSUE THREAD

**Issue by firesharkstudios** [vuetifyjs/vuetify#5234]
### Problem to solve
Currently, a v-data-table with enough columns requires horizontal scrolling on mobile displays which isn't ideal.

### Proposed solution
Buefy solves this well by changing the table layout on narrow displays to stacked vertical cards.  See https://buefy.github.io/#/documentation/table and try making the browser narrow enough to see how the tabular format is auto converted into vertically stacked cards.

This is an effective solution and doing something similar would make v-data-table a good choice for desktop and mobile browsers.

**Comment by jacekkarczmarczyk** [comment]
This should be covered by https://github.com/vuetifyjs/vuetify/pull/5232

**Comment by HuthDev** [comment]
Was this removed? The feature does not exist with the current version of vuetify - nothing is responsive about the data tables.

**Comment by blalan05** [comment]
This feature is in the 2.0 alpha.

**Comment by blalan05** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

  
Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/pull/5737
