### ISSUE TITLE
[Bug Report]  Three line on v-list  in the mobile version looks bad

### ISSUE THREAD

**Issue by kulkoff** [vuetifyjs/vuetify#5235]
### Versions and Environment
**Vuetify:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
length greater than 100 characters

### Expected Behavior
increase the height of the three lines

### Actual Behavior
Two lines are perfectly folded and dots are added. Three lines all collapses, can make the height more?

### Reproduction Link
[https://codepen.io/kulkoff/pen/BqQWmR?&editors=101](https://codepen.io/kulkoff/pen/BqQWmR?&editors=101)

**Comment by yshrsmz** [comment]
same here. looks like `three-line` is not working
Below is an example of the issue. I've forked this from [official example](https://vuetifyjs.com/ja/components/lists).
See the last item.

https://codepen.io/yshrsmz/pen/PygZyz

**Comment by yshrsmz** [comment]
maybe it's because of the autoprefixer
https://github.com/postcss/autoprefixer/issues/1141

**Comment by sbowler** [comment]
Currently, I am using version 1.3.5. I believe I have ran into a very similar issue that maybe is the same issue or related. When running in development with hot reloading and all, The styling for `.v-list--three-line .v-list__tile__sub-title` appears to be different.
Development
```
  white-space: initial;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  display: -webkit-box;
```
Production
```
  white-space: normal;
  -webkit-line-clamp: 2;
  display: -webkit-box;
```
This causes the list to not display correctly in production. I noticed in the stylus file, https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/components/_lists.styl, it appears to have the correct styling. However, in the dist css and minified css published to NPM the styling matches what shows up in production. As best I can tell it seems like the css has not be properly re-compiled from the stylus for at least version 1.3.5 published to NPM.

**Comment by Mikilll94** [comment]
The CSS property
```
-webkit-line-clamp: 2;
```
is not supported in Firefox and IE, so prop "three-line" only works in Chrome. I think this should be fixed.

**Comment by johnleider** [comment]
The `v-list` component has been update to match the MD2 spec and meets all height requirements for v2.0. 

----
@Mikilll94 
In regards to line clamp, we used to have a warning that explained that this is an experimental feature that may not be supported on all browsers, for whatever reason this is gone.
