### ISSUE TITLE
[Bug Report] Vuetify Carousel 1st item carousel display none issue

### ISSUE THREAD

**Issue by kdeeksha** [vuetifyjs/vuetify#5236]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.2
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
1. Vuetify Version 1.0.14
2. click on 1st image ( used v-dialog as there was issue with z-index in ios device)
3. then click next and come back to previous image the image is displayed.

### Expected Behavior
There's a list of images when onclick image i trigger carousel. Like, when onclick 3rd image display 3rd image in carousel. 

### Actual Behavior
Works fine, but only on first click of index 0 (i.e 1st image) the caraousel is blank. In jumbotron class it shows display:none (vuetify version is 1.0.14)

### Reproduction Link
[https://codepen.io/anon/pen/XxNEza?editors=1010](https://codepen.io/anon/pen/XxNEza?editors=1010)

**Comment by johnleider** [comment]
You are reporting version 1.0.14 but the codepen is using 1.2.6. Could you clarify this?

**Comment by jacekkarczmarczyk** [comment]
Can't reproduce it with 1.3.2
