### ISSUE TITLE
[Bug Report] AM/PM Opacity does not change on click on time picker.

### ISSUE THREAD

**Issue by aeonagency** [vuetifyjs/vuetify#5237]
### Versions and Environment
**Vuetify:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Mozilla Firefox
**OS:** Linux

### Steps to reproduce
Click on AM/PM.

### Expected Behavior
Once AM/PM is clicked it should change the opacity to 1.

### Actual Behavior
Once AM/PM is clicked it does not change the opacity to 1.

### Reproduction Link
https://codepen.io/anon/pen/zmoavO?&editors=101

### Other comments
https://vuetifyjs.com/en/components/time-pickers#introduction

**Comment by jacekkarczmarczyk** [comment]
Alreday fixed by https://github.com/vuetifyjs/vuetify/pull/4905
