### ISSUE TITLE
Feature request for Chip Component inside inputs

### ISSUE THREAD

**Issue by MitchelLabonte** [vuetifyjs/vuetify#524]
It would be great to be able to use chips in inputs like in the following demo:
https://material.angularjs.org/latest/demo/chips

**Comment by johnleider** [comment]
This would probably live within the select if anything due to it already supporting most of this behavior.

**Comment by johnleider** [comment]
This functionality is now part of v-select with the chips and autocomplete props.

**Comment by MitchelLabonte** [comment]
It seems a bit different since it's not possible for the user to enter a term that is not in the options, or maybe I am missing something.

**Comment by johnleider** [comment]
That would be a different component, ala tags. I plan on adding tagging support in the future.

**Comment by jsuiker** [comment]
@johnleider is that something you'd want help with?

**Comment by nekosaur** [comment]
PRs are always welcome 👍

**Comment by johnleider** [comment]
This will be coming with 0.15.3, can't wait!

**Comment by satoyan** [comment]
Now I am using v1.1.8. But I clould not find this feature. I found I can use chip with combobox. But I would like to use chip with text-field.
