### ISSUE TITLE
[Bug Report] validate-on-blur and v-form @submit leads to hidden validation feedback

### ISSUE THREAD

**Issue by harveylee** [vuetifyjs/vuetify#5244]
### Versions and Environment
**Vuetify:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
1. Create a v-form: `<v-form ref='form' @submit='$refs.form.validate()' onsubmit='return false'>`
2. Put two v-text-fields into the form
3. Mark both text fields `validate-on-blur` prop and create simple validation rules which fail on an empty input (e.g. v => !!v || 'Required')
4. Add a v-btn with type='submit'
5. Click the first text field to give it focus
6. Press Enter to submit

### Expected Behavior
Because both text fields are blank they should fire the validation and display 'Required'

### Actual Behavior
Only the second text field shows 'Required'. This is because the focus is still on the first text field and so the validation feedback is hidden.

### Reproduction Link
[https://codepen.io/anon/pen/oaBwNe](https://codepen.io/anon/pen/oaBwNe)

### Other comments
Clicking on the Submit button produces the correct behaviour because neither text field has the focus. I think perhaps the @submit event on the v-form should assign focus to the submit button.

**Comment by johnleider** [comment]
I wonder if we should have a fieldset component that connects with inputs through `v-item-group`'s functionality and that talks with `v-form`, or just throw it into `v-form`. @vuetifyjs/core-team thoughts?

**Comment by KaelWD** [comment]
Having `input.validate(true)` ignore `shouldValidate` would fix this.

**Comment by KaelWD** [comment]
It's actually because `shouldValidate` doesn't like empty values. This really needs to be reverted to a stateful approach like it was before v1.1
https://github.com/vuetifyjs/vuetify/blob/10582102088a65756bb4313ff51bf5d88d6a1114/packages/vuetify/src/mixins/validatable.js#L79-L84

**Comment by johnleider** [comment]
The team is opting to close this issue due to lack of support and how old it is. The validation system is changing for Vuetify 3 so keep your eyes peeled for some new ways to interact with forms!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
