### ISSUE TITLE
Dynamic using v-list-group or v-list-tile in Navigation Drawer

### ISSUE THREAD

**Issue by aztran** [vuetifyjs/vuetify#5245]
Hello,
I wanna build navigation drawer with parent n child menu dynamic, for example data 

<img width="306" alt="screen shot 2018-10-09 at 14 53 37" src="https://user-images.githubusercontent.com/9424015/46654487-29863780-cbd3-11e8-95b7-75c89013823b.png">

in navigation drawer, if we want to make menu with child it must be used v-list-group, and if menu no child we can use v-list-title.
but how to make dynamic or automatic choose using v-list-group or v-list-tile in navigation drawer?

**Comment by KaelWD** [comment]
The documentation does that, look at the vuetifyjs.com source on github. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
