### ISSUE TITLE
[Bug Report] RTL not work.  I set  this.$vuetify.rtl = true;  I give result but item not in true side

### ISSUE THREAD

**Issue by vad11** [vuetifyjs/vuetify#5247]
### Versions and Environment
**Vuetify:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 8

### Steps to reproduce
new Vue({
  el: '#app',
   mounted () {
    this.$vuetify.rtl = true;
  },
  
})

### Expected Behavior
Item in right side

### Actual Behavior
In left

### Reproduction Link
[https://codepen.io/bmp1/pen/vVgbVZ?&editors=101](https://codepen.io/bmp1/pen/vVgbVZ?&editors=101)

**Comment by nekosaur** [comment]
RTL is currently only officially supported for form input components
