### ISSUE TITLE
z-index problem on toolbar

### ISSUE THREAD

**Issue by cospa-ishihara** [vuetifyjs/vuetify#526]
<img width="400" alt="screen shot 2017-05-12 at 12 03 26" src="https://cloud.githubusercontent.com/assets/18693163/25980728/93b708ea-370b-11e7-9e9d-e2e65c4fc71c.png">

### Steps to reproduce
Check out the image or directly your website.

### Versions
v0.11.1

### What is expected ?
You should change toolbar z-index when it is in cards or other components

### What is actually happening ?
Toolbar in card is going over toolbar when I scroll the page.

### Reproduction Link
https://vuetifyjs.com/components/dividers

**Comment by cospa-ishihara** [comment]
Bottom navigation has same problem.

**Comment by johnleider** [comment]
These are documentation irregularities and are not present in the new docs.

**Comment by Enaldi** [comment]
I don't understand. How is this fixed?

**Comment by johnleider** [comment]
Hi @Enaldi I don't understand what you are saying?

**Comment by Enaldi** [comment]
I'm still having the issue, even though it's not occurring in the documentation example anymore. What was the fix?

**Comment by johnleider** [comment]
The fix is to create an issue with a corresponding codepen so we can look into it, thank you!

**Comment by jrast** [comment]
I think this is the same as https://github.com/vuetifyjs/vuetify/pull/902
