### ISSUE TITLE
[Feature Request] Add loop prop to carousel

### ISSUE THREAD

**Issue by saintplay** [vuetifyjs/vuetify#5260]
### Problem to solve
Loop allows to:

- Go to the first item, when clicking *next* on the last item
- Go to the last item, when clicking *prev* on the first item

**Sometimes we need to disable this behavior.**

### Proposed solution
```vue
<v-carousel :loop="false">
```

**Comment by johnleider** [comment]
This prop will exist on `v-window` as **continuous** with a default of **false**. `v-carousel` will explicitly override this prop as **true** so in the future you can do:

```
<v-carousel :continuous="false">
```
