### ISSUE TITLE
[Vue warn]: Duplicate presence of slot "header" found in the same render tree -- v-data-table with search option

### ISSUE THREAD

**Issue by sombriks** [vuetifyjs/vuetify#5261]
### Versions and Environment
Vuetify: 1.2.8
Vue: 2.5.16
Browsers: Firefox
OS: Fedora

## steps to reproduce

see the project bellow to reproduce the problem

https://github.com/sombriks/v-data-table-duplicate-slot-issue

**Comment by nekosaur** [comment]
I took a quick look at your repro, and I'm stumped. Unless I'm missing something really obvious. It does feel like more of a Vue issue than something on our end, possibly related to the fact that you have a slot inside a slot. But that should work afaik.

One workaround is to use scoped slot instead, like so

```
<tr slot="header" slot-scope="props">
```

That gets rid of the error.

**Comment by sombriks** [comment]
indeed, this is vue-related.

thank you for the workaround!
