### ISSUE TITLE
Stepper: Clicking editable step no longer working

### ISSUE THREAD

**Issue by mjy90** [vuetifyjs/vuetify#5262]
### Versions and Environment
Vuetify: 1.2.8
Vue: 2.5.16
Browsers: Chrome 69.0.3497.81
OS: Ubuntu 18.04.1

### Previously worked in:
Vuetify: 1.1.9
Vue: 2.5.16

### Steps to reproduce

Create a stepper with an editable step. Click the editable step.

### Expected Behavior

The user should be brought to that step.

### Actual Behavior

Nothing happens in the UI, and the JS console gives this error and stack trace:
`Uncaught TypeError: this.getSteps is not a function
    at VueComponent.stepClick (vuetify.js?dc48:11722)
    at VueComponent.click (vuetify.js?dc48:11962)
    at invoker (vue.esm.js?efeb:2027)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.esm.js?efeb:1826)`

### Reproduction Link

Taken from [the Vuetify docs:](https://vuetifyjs.com/en/components/steppers#example-editable)
https://codepen.io/mjy90/pen/GYmOmy

**Comment by andrew-smythe** [comment]
Looks like the function `getSteps` was removed (perhaps by accident) in the latest commit (f7b17e7)

at line: https://github.com/vuetifyjs/vuetify/commit/f7b17e78b66420046382b8ad8a64b2ee7b0bcf7d#diff-f5aded692d4dcdd9e4bc1e4b90e8ba4aL74.

**Comment by johnleider** [comment]
The **genSteps** method is actually no longer needed, just forgot to remove the fn call.

**Comment by johnleider** [comment]
Fixed by e454bbaf

**Comment by mjy90** [comment]
Thanks, guys!
