### ISSUE TITLE
Forgive me, let me ask a question

### ISSUE THREAD

**Issue by bigradish** [vuetifyjs/vuetify#5263]
Please forgive me, because I can't access other help channels like discord, reddit and stackoverflow, I have to ask this question here.
My question is: How to make bottom navigation content view slide when being swiped?
I noticed that using v-tab-item with v-tab in v-tabs lets the content view in v-tab-item slide when being swiped. Is there a way to make the content view of v-bottom-nav act like this?
Thank you very much.

**Comment by johnleider** [comment]
It is not possible. The bottom-nav spec defined a maximum amount of content that should be displayed and does not support overflow scrolling.

**Comment by bigradish** [comment]
@johnleider Thank you very much for your kind answer. :)
