### ISSUE TITLE
[Bug Report] onChange for timePicker

### ISSUE THREAD

**Issue by pwildschut** [vuetifyjs/vuetify#5266]
### What problem does this feature solve?

In the case that a variable change is a trigger for other functionality the onInput event generates too much noise. An onChange event would be more reliable

### What is your proposed solution?

I have seen in the code that the timePicker is prepared to return the onchange event. it just seems to be returning the input value, so its actually not doing anything :/

**Comment by jacekkarczmarczyk** [comment]
@pwildschut Can you provide a codepen with explanation what and when should happen?

**Comment by pwildschut** [comment]
I have created this to visualize, somehow it looks weird. But functionally it proves my point.

https://codepen.io/pwildschut/pen/aRVJaN

Apologies for the delayed answer.

**Comment by KaelWD** [comment]
It always emits 00:25 for me, I'd call this a bug.
