### ISSUE TITLE
[Feature Request] Set v-autocomplete browser-autocomplete default value to "disabled", instead of "off"

### ISSUE THREAD

**Issue by ben1lam8** [vuetifyjs/vuetify#5267]
### Problem to solve
Chrome intentionally ignores "off" and "false" values for an input autocomplete attribute, to fit the WHATWG autofill standard (well... 'fit' their way). 
- https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164
- https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

Hence, v-autocomplete still prompts "autofilled browser suggestions" where their browser-autocomplete default value is "off".

### Proposed solution
Set the browser-autocomplete default value to something that doesn't match any WHATWG autofill standard, nor Chrome exception. Such as **"disabled"**.

To keep the browser autofill behaviour, we would have to clearly define the prop to 'on' or to a WHATWG autofill token value.

**Comment by johnleider** [comment]
In v2 the default autocomplete value has been removed.

**Comment by rgb-one** [comment]
I should probably make this a separate issue but with v2 the chrome autofill shows for the `v-text-field`, `v-autocomplete` and `v-combobox`. The browser autofill suggestions overlay the suggestions provided by v-autocomplete and v-combobox. Those two components should disable browser autofill functionality. It would be good if it was off by default with an option to disable it for `v-text-field` though.

**Comment by j4hangir** [comment]
Why's this issue, in Chrome the browser still shows the autocomplete popover.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
