### ISSUE TITLE
IPhone 5+ to 7 bottom bar doesn't work on Safari Browser or Stock Browser

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#527]
I don't know how to reproduce this because i dont have an iphone LOL (android user here)

can someone kindly test this put a bottom bar with routes and check it if its working thanks

**Comment by ralphchristianeclipse** [comment]
I've used browser stack and see that bottom bar is not rendered

![image](https://cloud.githubusercontent.com/assets/25447231/25993974/910325ec-373e-11e7-9afd-cac6d80559c4.png)


Using this image with this 

markup

```pug
				v-bottom-nav(:value="true" shift).accent
					template(v-for="{name,label,icon} in routes")
						v-btn(flat primary router :to="{name}", :value="$route.name === name")
							span {{label}}
							v-icon {{icon}}
```

```js
export default {
		data() {
			return {
				routes: [
//					{
//						name: 'admin-dashboard',
//						label: 'Dashboard',
//						icon: 'dashboard'
//					},
					{
						name: 'admin-plants',
						label: 'Plants',
						icon: 'shopping_basket'
					},
					{
						name: 'admin-users',
						label: 'Users',
						icon: 'supervisor_account'
					},
				]
			}

}
```

**Comment by ralphchristianeclipse** [comment]
found out that position: fixed when below a content overflows to the top and hidden from the toolbar

**Comment by johnleider** [comment]
Thank you for the report. Can you please put together a codepen so that we can access it with an iphone for testing, thank you.

**Comment by ralphchristianeclipse** [comment]
@johnleider http://codepen.io/anon/pen/gWzomv here

**Comment by johnleider** [comment]
Because of the current version of Vuetify, main is a flex container. When you put bottom-nav on the same level as v-content, v-content pushes it off the screen due to bottom-nav not having any flex properties. If you move the bottom-nav to the same level in the dom as main, it is visible just fine.

In the next release this won't be a caveat.
