### ISSUE TITLE
[Enhancement] grow/shrink classes don't function as expected

### ISSUE THREAD

**Issue by frattaro** [vuetifyjs/vuetify#5272]
### Versions and Environment
Vuetify: 1.2.5
Vue: 2.5.17
Browsers: Vivaldi
OS: Windows 10

### Steps to reproduce
`d-flex` on parent element, `shrink` class on immediate child

inspect `class="shrink"` behavior, it is overridden by `d-flex>*` selector specificity

### Expected Behavior
`shrink` class should override `flex-grow`

### Actual Behavior
class did not affect the cascade result

### Reproduction Link
https://codepen.io/frattaro/pen/NOgdmo

**Comment by johnleider** [comment]
Will be resolved in 2.0 with the grid refactor
