### ISSUE TITLE
Changing tabs by HREF

### ISSUE THREAD

**Issue by Oli-Wan** [vuetifyjs/vuetify#5273]
### Versions and Environment
Vuetify: 1.2.8

### Previously worked in:
Vuetify: 1.2.6

### Steps to reproduce

Just browse to [https://vuetifyjs.com/en/components/tabs#example-search](https://vuetifyjs.com/en/components/tabs#example-search) and change the selected tab

### Expected Behavior

I expect to change the selected tab, without affecting the route path

### Actual Behavior

The tab changes, the route path changes, and the page is scrolled up

### Reproduction Link

[https://vuetifyjs.com/en/components/tabs#example-search](https://vuetifyjs.com/en/components/tabs#example-search)
---

### Additional Comments:
I don't understand if this is an expected behaviour: 
- the page scrolls when changing the selected tab
- the HREF is exposed in the route url

Before the 1.2.7 version instead: 
- the page didn't scroll down/up when changing the tab
- the HREF wasn't exposed in route path   

Thanks,

**Comment by KaelWD** [comment]
#4784
e090589aae72e235093137515c4732957938a5a3
