### ISSUE TITLE
[Feature Request] Expansion Panel: Custom Icon COLORS

### ISSUE THREAD

**Issue by ekreutzer** [vuetifyjs/vuetify#5275]
### What problem does this feature solve?

Allowing one to customize the color of an expansion panel icon would be immensely beneficial for devs who don't want to use the default boring gray. It would also add valuable customizability to Vuetify.

Being able to change the icon color would be beneficial to users as it would enhance the visibility of the icons and make the component less bland.
### What is your proposed solution?

```html
<v-expansion-panel>

    <v-expansion-panel-content
      v-for="(item,i) in 5"
      :key="i"
      expand-icon="mdi-menu-down"
     ----->> expand-icon-color="primary"
    >
      <div slot="header">Item</div>
      <v-card>
        <v-card-text class="grey lighten-3">...</v-card-text>
      </v-card>
    </v-expansion-panel-content>
  </v-expansion-panel>
```

**Comment by KaelWD** [comment]
You can use the `actions` slot for that: https://codepen.io/anon/pen/MPodqV?editors=1000

**Comment by ekreutzer** [comment]
Thanks, would've been helpful to see that in the docs.

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #627](https://github.com/vuetifyjs/vuetifyjs.com/issues/627) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MajesticPotatoe** [comment]
Example Added via #5869
