### ISSUE TITLE
Refactor Navbar

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#53]
Refactor navbar functionality and styles.

**Comment by dohomi** [comment]
An option for having the navbar sticky to top would be a nice improvement.

**Comment by johnleider** [comment]
That option actually currently exists, just not in the docs for whatever reason.

Apply <strong>top-fixed-navbar</strong> to ```v-app``` and <strong>fixed</strong> to ```v-navbar```.

**Comment by johnleider** [comment]
Navbar refactor is complete and will launch with v0.8.6.

**Comment by dohomi** [comment]
great news, thanks @johnleider
