### ISSUE TITLE
v-row does not share data to v-col using a v-for

### ISSUE THREAD

**Issue by alexmgillis** [vuetifyjs/vuetify#530]
Seems like v-row isolates informaiton generateds fomr its own tag
Example

```
<template>
<v-container>    
<v-card>
   <v-card-text>
    <v-container fluid>
         <v-row v-for="column in selectedcolumns" :key="column.value">
         <v-col> {{column.name}}</v-col>
```

it would give me  this error: app.js:19286 TypeError: Cannot convert undefined or null to object
However if i do
`  <v-row v-for="column in selectedcolumns" :key="column.value">
         <div> {{column.name}}</div>
</v-row> `
It would print the valu in column.name as intended
**UPDATE**:
it seems that the problems is v-col, it does not allow pass info from outside:

>  <v-row> 
        <v-col>
      <table width="auto">
             <tr v-for="column in selectedcolumns" :key="column.value">
               <td><h5>{{column.name}}</h5></td>
             <td > 
               <v-select                    
            label="Select"
            v-bind:items="['NONE','Contain']"
            v-model="column['query']"
            light
            max-height="400"
            :hint="'set condition for '+column.name"
            persistent-hint
          /></td>
           <td >
             <v-text-field
            v-model="column['value']"
            label="value for condition"
          ></v-text-field></td>
          </tr>
         </table>
          </v-col>
        </v-row>

If I remove the <v-col> tag it would work otherwise it reports a similar error

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
