### ISSUE TITLE
Sidebar doesn't respect `close-on-click` on medium or small breakpoints

### ISSUE THREAD

**Issue by DivinoAG** [vuetifyjs/vuetify#531]
### Steps to reproduce

* Add a `v-sidebar` component
* Set `close-on-click` prop to `false`. This prevents the sidebar from closing when clicking outside the sidebar on desktop screens correctly.
* Open the page on a mobile device, or resize browser viewport to any width smaller than medium breakpoint (992px)
* Click/tap anywhere outside the sidebar

### Versions

Tested with Vue 2.3.3 and 2.2.6, and Vuetify 0.11.0 and 0.10.4 on latest Chrome/Safari.

### What is expected ?

If the `close-on-click` prop is set to `false`, clicking on the body or any other element should not close the sidebar.

### What is actually happening ?

The sidebar is closing when the viewport is on `xsmall`, `small` or `medium` breakpoints.

### Reproduction Link

http://codepen.io/DivinoAG/pen/rmvGaj

**Comment by johnleider** [comment]
This issue has been corrected on dev for the next release.
