### ISSUE TITLE
Date pickers - In dialog and menu not triggering Change

### ISSUE THREAD

**Issue by fpilee** [vuetifyjs/vuetify#5320]
Vuetify: 
Vue:"2.5.17"
Browsers: chrome
OS: windows

### Steps to reproduce
Try to change the date in a datepicker

### Expected Behavior
event should call a function

### Actual Behavior
nothing happens

### Reproduction Link
https://codepen.io/anon/pen/OBjzdG

**Comment by jacekkarczmarczyk** [comment]
`@change` event is emitted only when user types in the text field, not when the model is changed programatically. It has nothing to do with dialog or date picker
https://codepen.io/anon/pen/xyLYGY

**Comment by fpilee** [comment]
yeah I added the `@change="onChange"` in datepicker element not v-text-field
