### ISSUE TITLE
Support for Material Design 2 planned?

### ISSUE THREAD

**Issue by marcpabst** [vuetifyjs/vuetify#5323]
I've been using vuetify for a few days now in a small project and so far I absolutely like it. I used the official material-components-web before and vuetify is so much easier.

However, (and I hope this has not been asked before) I wonder if support for the new refined  Material Design 2 is planned? From a components perspective it seems to be mostly cosmetic work (increasing corner radius, redesign text inputs). Before I start to hack together something, there is already something in the pipeline?

**Comment by johnleider** [comment]
Yes.
