### ISSUE TITLE
Tabs component breaking in RTL mode

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [vuetifyjs/vuetify#5329]
### Versions and Environment
Vuetify: 1.2.9
Vue: 2.5.16
Browsers: All browsers(Chrome, Edge, explorer)
OS: Windows

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce
define more tabs along with the *next and previous Arrows* and set the **rtl** as true. 

### Reproduction Link
You can re-produce [here](https://codepen.io/Grandhi/pen/qJpqeY)

---

### Additional Comments:
Please check the codepen at any screen size, where entire tabs can't fit. So that you can see the broken behaviour. When I debug I understand **transform** property not setting properly also next and previous arrows appearing wrongly .

**Comment by jacekkarczmarczyk** [comment]
No idea, you may join [the Discord chat room](https://community.vuetifyjs.com), maybe somebody will know
