### ISSUE TITLE
Arrows in pickers are invisible

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#533]
The arrows in the pickers to switch months are invisible. At first I thought the components are totally unusable on mobile because they don't respond to swipe gestures. Happens on the demo in the docu.

**Comment by smares** [comment]
![screenshot_20170513-221045](https://cloud.githubusercontent.com/assets/818380/26028927/efc5c72e-3829-11e7-8393-552de4b0e030.png)

**Comment by johnleider** [comment]
Is this on iOS? I cannot repro issue on android.

**Comment by smares** [comment]
Nope, Android 7.0 on a Samsung Galaxy S7 using the default Samsung browser.

**Comment by smares** [comment]
I can confirm it doesn't happen with the beta browser.

Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36.

Another bug with the non-beta is that icons in toolbars don't show up, except for the search icon in the search field in the demo of the toolbar component.

**Comment by johnleider** [comment]
I have the exact device and I'm having issues reproducing it there and on browserstack.

**Comment by smares** [comment]
Weird. I have it all the time, so it's not something that happens sometimes. :( Nougat already installed? The problem occurs with the browser version 5.0.30-77.

**Comment by mfferreira** [comment]
@smares I can't reproduce it on my Android either. I don't have Samsung browser available.
If you reproduce the example on codepen, do you see that issue?

**Comment by smares** [comment]
Yep, it seems to actually affect all icons in buttons. Here are two pens I tested with:

http://codepen.io/anon/pen/dWgmxw
http://codepen.io/anon/pen/dWgeyw

Posting the screenshots in a minute.

**Comment by smares** [comment]
![screenshot_20170519-112258](https://cloud.githubusercontent.com/assets/818380/26241731/12092000-3c86-11e7-9d8e-7a33c9cf92d4.png)
![screenshot_20170519-112459](https://cloud.githubusercontent.com/assets/818380/26241732/120c72dc-3c86-11e7-864f-e123843ff975.png)

**Comment by mfferreira** [comment]
@smares If the beta version of that browser works fine, it's likely because they realized the screw up on supporting standards. Feel free to reopen when the beta version becomes GA.

**Comment by smares** [comment]
The beta browser is no longer beta so that everything works fine now with the latest stable. Just FYI. :)
