### ISSUE TITLE
Datatable filter by Select

### ISSUE THREAD

**Issue by james04gr** [vuetifyjs/vuetify#5330]
### What is your proposed solution?

I m not sure if it exists already, but i just needed a search filter above the datatable but a textfileld to write but a Select dropdown which filters the data array by a specific value. It can be done with v-if but it would be nice if it was built-in..!!

**Comment by jacekkarczmarczyk** [comment]
Data table `search` prop doesn't care whether it's value comes from text field or from select or from anything else

For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
