### ISSUE TITLE
Stepper : v-stepper-step with editable props don't work properly

### ISSUE THREAD

**Issue by nasirouwagana** [vuetifyjs/vuetify#5331]
### Versions and Environment
Vuetify: 1.3.0-Beta.0
Vue: 2.5.17
Browsers: Chrome Version 63.0.3239.84 (Build officiel) (64 bits)
OS: Ubuntu 16.04 xenial

### Previously worked in:
Vuetify: 1.3.0-alpha.2
Vue: 2.5.17

### Steps to reproduce

Add **editable** props to **v-stepper-step**

### Expected Behavior

When I clicked on an editable step, it should be normally opened.

### Actual Behavior

When I clicked on an editable step, I have a below issue.
![image](https://user-images.githubusercontent.com/8539387/47050941-19a1c100-d19a-11e8-98cb-b82e85cd678f.png)
![image](https://user-images.githubusercontent.com/8539387/47051002-4524ab80-d19a-11e8-8638-d20a1f4e95db.png)

---
### Reproduction Link

https://codepen.io/nasirouwagana/pen/VEyJoo

**Comment by KaelWD** [comment]
Already fixed in 1.2.9: e454bba
