### ISSUE TITLE
VTreeView active items are not synced

### ISSUE THREAD

**Issue by knagyorg** [vuetifyjs/vuetify#5343]
Versions and Environment
Vuetify: 1.3.0
Browsers: chrome/firefox (current versions)
OS: Windows 10

Steps to reproduce
Create v-treeview with items and set multiple-active. Select and deselect items.

Expected Behavior
selectedItems should be sync with selected items in component

Actual Behavior
array selectedItems only increase its size, but not decrease

Reproduction Link
Version 1.3.0
https://codepen.io/anon/pen/YJaZwb

**Comment by mgiraud** [comment]
The same error happens when trying to update the v-model value.
See your example here : https://vuetifyjs.com/en/components/treeview#example-hotspots
The reset button doesnt not work

**Comment by nekosaur** [comment]
That has also been fixed in #5373

**Comment by nparley** [comment]
I guess #5373 is waiting to be merged?
