### ISSUE TITLE
[Bug Report] v-data-table pagination

### ISSUE THREAD

**Issue by LeonVlad** [vuetifyjs/vuetify#5344]
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.17
**Browsers:** Firefox 64.0
**OS:** Windows 7

### Steps to reproduce
<body>
    
 <div id="book"> 
      
      
 <v-app>

  <div id="phbook" > 
    <v-data-table
      :headers="headers"
      :items="desserts"
      :pagination.sync="pagination"
      :total-items="totalDesserts"
      :loading="loading"
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
        <td class="text-xs-right">{{ props.item.calories }}</td>
        <td class="text-xs-right">{{ props.item.fat }}</td>
        <td class="text-xs-right">{{ props.item.carbs }}</td>
        <td class="text-xs-right">{{ props.item.protein }}</td>
        <td class="text-xs-right">{{ props.item.iron }}</td>
      </template>
    </v-data-table>
  </div>
</v-app>
     
 </div>  
</body>

### Expected Behavior
<body>
    
 <div id="book"> 
      
      
 <v-app>

  <div id="phbook" > 
    <v-data-table
      :headers="headers"
      :items="desserts"
      :pagination.sync="pagination"
      :total-items="totalDesserts"
      :loading="loading"
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
        <td class="text-xs-right">{{ props.item.calories }}</td>
        <td class="text-xs-right">{{ props.item.fat }}</td>
        <td class="text-xs-right">{{ props.item.carbs }}</td>
        <td class="text-xs-right">{{ props.item.protein }}</td>
        <td class="text-xs-right">{{ props.item.iron }}</td>
      </template>
    </v-data-table>
  </div>
</v-app>
     
 </div>  

### Actual Behavior
<body>
    
 <div id="book"> 
      
      
 <v-app>

  <div id="phbook" > 
    <v-data-table
      :headers="headers"
      :items="desserts"
      :pagination.sync="pagination"
      :total-items="totalDesserts"
      :loading="loading"
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
        <td class="text-xs-right">{{ props.item.calories }}</td>
        <td class="text-xs-right">{{ props.item.fat }}</td>
        <td class="text-xs-right">{{ props.item.carbs }}</td>
        <td class="text-xs-right">{{ props.item.protein }}</td>
        <td class="text-xs-right">{{ props.item.iron }}</td>
      </template>
    </v-data-table>
  </div>
</v-app>
  </div>  
</body>

### Reproduction Link
[https://codepen.io/LeonVlad/project/editor/XWwLeW](https://codepen.io/LeonVlad/project/editor/XWwLeW)

### Other comments
<v-app> 
<div id="table" >if id  here: Error rowsPerPage set
   v-data-table
</div> 
//OK 
<div id="tbl"> if  id here: Ok rowsPerPage set
<v-app> 
<div id="table" >
   v-data-table
</div> 
</v-app>
</div>

**Comment by KaelWD** [comment]
The issue description is garbage and the reproduction link is loaded with seemingly unrelated code. Please update the issue to clearly explain and demonstrate the problem and how to reproduce it.
