### ISSUE TITLE
[Feature Request] Grid grouping and drag

### ISSUE THREAD

**Issue by hilagaba** [vuetifyjs/vuetify#5346]
### Problem to solve
Data visualization, dashboard viewing in the BI field

### Proposed solution
Can you develop it?

**Comment by KaelWD** [comment]
Feature requests require more detail than that, but we will not be creating a custom drag solution. We recommend [vue-draggable](https://github.com/SortableJS/Vue.Draggable)

**Comment by hilagaba** [comment]
And what about grouping of grid?
