### ISSUE TITLE
ca.ts Catalan locale file dissapeared in Vuetify 1.3.0?

### ISSUE THREAD

**Issue by acacha** [vuetifyjs/vuetify#5348]
In previous versions of Vuetify there was a ca locale file, please readd the file

https://github.com/vuetifyjs/vuetify/commit/321df5a906f2a57aa5a877005ceffc2880110499#diff-90690ad9c8fa7c2d35a371ce3b79194e

**Comment by KaelWD** [comment]
Was caused by #4930: 3f142c58b1625cde5c93902d88fa875b7060ffa5
