### ISSUE TITLE
[Bug Report] menu in toolbar in dialog is not visible in safari

### ISSUE THREAD

**Issue by Guizzoni** [vuetifyjs/vuetify#5351]
### Versions and Environment
Vuetify: 1.3.0
Vue: 2.5.17
Browsers: Safari 10.0.1
OS: macOS 10.13.4 (this issue only happens in macOS Safari.)

### Steps to reproduce

Create a fullscreen v-dialog with a v-autocomplete inside.

### Expected Behavior

The v-lists results should appear above the card.

### Actual Behavior

 The v-list results are hidden under the card.

### Reproduction Link

[https://codepen.io/Guizzoni/pen/YJaOLz](https://codepen.io/Guizzoni/pen/YJaOLz)

---

### Additional Comments:
**This issue only happens in macOS Safari.** 
The workaround i found was to add the following to the css:
```
.v-autocomplete__content {
  z-index: 210 !important;
}
```

**Comment by Guizzoni** [comment]
This issue doesn't happen if I add the property "attach" to the v-autocomplete component.

**Comment by kendallroth** [comment]
Would like to mention that I just had this happen to me on macOS Chrome. Adding the workaround in additional comments works currently but definitely is a round-about hack. Adding `attach` caused more problems that it was worth (strange positioning, etc).

**Comment by JamesDeegan** [comment]
Yeah I'm experiencing this in Chrome too, anyone know of a workaround? Other than attach which isn't ideal

**Comment by KaelWD** [comment]
Similar to #2111, `transform: translateY(0px)` is causing safari to return `0` for the toolbar's z-index.
