### ISSUE TITLE
[Bug Report] v-tab v-model not updating

### ISSUE THREAD

**Issue by Avatar45com** [vuetifyjs/vuetify#5352]
### Versions and Environment
**Vuetify:** 1.3.0
**Last working version:** 1.2.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Linux x86_64

### Steps to reproduce
1. create a v-tabs
2. assign the v-model to an variable.
3. create the v-tabs using an for (n in array).
4. add a button to add a new value in the array from step 3.
5. when a new value is added change the v-model variable to the length of the array - 1.

### Expected Behavior
v-tab at the last position will be selected.

### Actual Behavior
v-tab selection does not change.

### Reproduction Link
[https://codepen.io/Avatar45com/pen/OBQdKr](https://codepen.io/Avatar45com/pen/OBQdKr)

### Other comments
The only way this works now is using nextTick. if you change the v-model variable within nextTick the model updates as expected.

**Comment by DRoet** [comment]
Maybe related, but I've also noticed a performance regression on 1.3.0 on initial load. The slider will appear a lot slower (100ms or more depending on the speed of the device)

simple codepen: <https://codepen.io/anon/pen/vVjpro?&editors=101>

**Comment by johnleider** [comment]
This is happening due to the introduction of **updateItemState** being called in a watcher. This is why nextTick currently works. Working on a solution.

**Comment by Avatar45com** [comment]
Can you reopen this issue. I think it is also affecting the v-window model as well

**Comment by johnleider** [comment]
Please do not comment on closed issues. If you have a bug, please create a new issue, https://issues.vuetifyjs.com or seek help in our community, https://community.vuetifyjs.com
