### ISSUE TITLE
[Bug Report] Setting color prop on v-stepper-step works when  my app runs locally, but not when deployed on Gitlab

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#5354]
### Versions and Environment
Vuetify: 1.2.4
Vue:
Browsers: Chrome, Firefox
OS: Ubuntu 18.04

### Steps to reproduce

- Use Vuetify.js in Nuxt.
- Use `v-stepper` component
- set `color` prop to `v-stepper-step` component
- Launnch your server locally: `yarn run dev`
- It **works locally** but when deploying on Gitlab, `color` prop does not take effect and in spection of the element in question shows: `element.style: {}`

### Expected Behavior
I expect `color` prop to take effect when set `v-stepper-step` not only locally but also when I deploy it on Gitlab.

### Actual Behavior

 `color` prop to take effect when set `v-stepper-step` when I run my Nuxt.js app locally, but not when I deploy my app on Gitlab.

### Reproduction Link

https://codepen.io/begueradj/pen/ePrRNm

---

**Comment by johnleider** [comment]
Does the same issue happen if you build for production and run locally?

**Comment by begueradj** [comment]
No, locally it works fine.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
