### ISSUE TITLE
v-component does not work with array of objects

### ISSUE THREAD

**Issue by k4ffee** [vuetifyjs/vuetify#5358]
### Versions and Environment
Vuetify: 1.3.0
Vue: 2.5.17
Browsers: Firefox 60.2.2esr (64-Bit), Google Chrome 69.0.3497.100
OS: Linux/Gentoo

### Steps to reproduce
Use a v-combobox with an array of objects, 

### Expected Behavior
V-model should hold the selected value. Value from {value,text} or as set with item-text and item-value

### Actual Behavior
v-model holds complete selected object

### Reproduction Link
https://codepen.io/anon/pen/ePreXg

**Comment by jacekkarczmarczyk** [comment]
Add `:return-object="false"` to combo box, it's `true` by default

**Comment by KaelWD** [comment]
Which is not supported behaviour by the way, so don't complain if it breaks everything.

**Comment by k4ffee** [comment]
@jacekkarczmarczyk thank you, had overlooked that, sorry for the noise

@KaelWD if so, it shouldn't be officially documented or the documentation should point out that. I could open a new bugreport about that if necessary
