### ISSUE TITLE
DataTable needs at least one sortable header

### ISSUE THREAD

**Issue by jpfong** [vuetifyjs/vuetify#536]
- What will it allow you to do that you can't do today?

Set a datatable without sortable header

### Steps to reproduce

Just create a datatable with all headers with sortable at false

### Versions

v0.11.1

### What is expected ?

A table without sortable header 
ex: https://codepen.io/jpfong/pen/QvroEg (v.0.10.3)

### What is actually happening ?

No datatable is displayed 
ex with v.0.11.1
https://codepen.io/jpfong/pen/KmREMX

### Reproduction Link

https://codepen.io/jpfong/pen/KmREMX)

**Comment by nekosaur** [comment]
I can confirm that this has been fixed in dev
