### ISSUE TITLE
[Feature Request] add support for horizontal v-timeline

### ISSUE THREAD

**Issue by cocoricoin** [vuetifyjs/vuetify#5360]
### Problem to solve
If you have a list of object that each requires a timeline, or if your design requires the old fashioned horizontal timeline, in those case the actual vertical timeline don't do the trick
(I was very exited by the Vtimeline. I still didn't had time to really look into it but I'm kind of disappointed that without horizontal layout i can't use it in my project right now)

### Proposed solution
Maybe allow us by a props to switch the layout of the Vtimeline to horizontal

**Comment by MirhaB** [comment]
Will this be released soon or is possible on  another way make timeline horizontal?

**Comment by nekosaur** [comment]
We have not even decided if this should be implemented. So the answer to the first part is no. As far as I know no one has created any workaround for this either, but you could always check in our community chat.

**Comment by caique0202** [comment]
It'd be a really nice feature.

**Comment by aximilli1212** [comment]
Yes Please. A horizontal timeline would be awesome.
Has it been added already?

**Comment by nekosaur** [comment]
If the issue is open, the answer is no. Use the emoji in original post to signal interest

**Comment by anderssonq** [comment]
+1 For this feature
