### ISSUE TITLE
[Bug Report] Read-only Text Field Rule Validation

### ISSUE THREAD

**Issue by rhydev** [vuetifyjs/vuetify#5362]
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
1. Open codepen
2. Focus textfield
3. Unfocus textfield
4. See rule applied

### Expected Behavior
Rules should not be applied to readonly textfield when unfocusing.

### Actual Behavior
Rules are applied to readonly textfield when unfocusing.

### Reproduction Link
[https://codepen.io/anon/pen/ReJrQm](https://codepen.io/anon/pen/ReJrQm)

### Other comments
You can change the `text` value and see that the error will no longer occur as the textfield now has a value.

**Comment by KaelWD** [comment]
Should they be included in v-form still?

**Comment by johnleider** [comment]
The complication here is that **validatable** mixin doesn't contain disabled/readonly props. This is the easy way to implement the above functionality.
