### ISSUE TITLE
[Bug Report] v-carousel: Image gets cropped

### ISSUE THREAD

**Issue by jkosonen** [vuetifyjs/vuetify#5363]
### Versions and Environment
Vuetify: 1.3.0
Vue: 2.5.17
Browsers: FF 62.0.3
OS: Win 10

### Previously worked in:
Vuetify: 1.2.6
Vue: 2.5.17

### Steps to reproduce
Add v-carousel and give it percentage height

### Expected Behavior
Image stays inside carousel

### Actual Behavior
Image is too big and overflows

### Reproduction Link
https://codepen.io/anon/pen/dgKNxm

---

**Comment by KaelWD** [comment]
This actually seems to be `v-window`, there's nothing restricting the height of `v-window-item` if `v-window__container` has a set height. 

@johnleider Adding `height: 100%;` to `v-window-item` fixes this, is it likely to break something else?

**Comment by johnleider** [comment]
Maybe during transition, will have to check.

**Comment by rcheung9** [comment]
Affects `v-tabs-items` too.  I have `transition` and `reverse-transition` set on `v-tab-item` and the rendered output sometimes sets the `.v-window__container` with a fixed pixel height.

Have to override the css 

```
.v-window__container--is-active {
    height: 100% !important;
}
```

**Comment by johnleider** [comment]
Putting 100% on window elements causes some issues:

- The window container no longer transitions its height
- window-y-transition is broken

This _may_ be something we could explicitly do on carousel as it was always intended for it to have a fixed height, but `v-tabs` would not.

**Comment by johnleider** [comment]
Adding as a fix specific to `v-carousel` as any other implementation breaks other functionality. I don't have an issue with locking this in to a single component as its expected that `v-carousel` maintain the same height.
