### ISSUE TITLE
[Bug Report] combobox auto-blurs on typing and default loader shifted upwards

### ISSUE THREAD

**Issue by pranavjindal999** [vuetifyjs/vuetify#5365]
### Versions and Environment
**Vuetify:** 1.3.0
**Last working version:** 1.2.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Mac OS 10.13.6

### Steps to reproduce
Use `v-combobox` component
Lazy load content and toggle `loading` prop accordingly
Apply `solo-inverted` prop

### Expected Behavior
Combobox input should not blur on typing
The default loader should be bottom aligned with text-box

### Actual Behavior
Combobox's input element blurs on typing 1 char
The default loader is shifted upwards by few pixels from bottom.

### Reproduction Link
[https://codepen.io/anon/pen/MPXQjV](https://codepen.io/anon/pen/MPXQjV)

**Comment by KaelWD** [comment]
Repro link just has tabs, and "Steps to reproduce" should say how to reproduce the issue in the provided environment, not in general.

**Comment by pranavjindal999** [comment]
@KaelWD I mistakenly overwrote my pen.. Link is not fixed..
Regarding the the repro step, issue isn't env specific.

**Comment by johnleider** [comment]
Caused by https://github.com/vuetifyjs/vuetify/commit/91ad55b915fc7eb1ecf954ef6e455b99ca489107
