### ISSUE TITLE
How to change icon color in <v-alert>?

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#5368]
I have this

                <v-alert slot="no-results" :value="true" :color="data_table.search_no_results_color" :icon="data_table.search_no_results_icon">
                    {{data_table.search_no_results_prefix_label}}{{ data_table.search }}{{data_table.search_no_results_suffix_label}}
                </v-alert>

where I make the bg color of the alert dark purple. However the warning icon comes out dark black, and barely visible. I want to change it to white color. Currently I am using this

        .v-alert .v-alert__icon.v-icon {
            color:white;
        }

to hack it, But is there a better way using a parameter option in the <v-alert> tag?

Thanks

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
