### ISSUE TITLE
[Bug Report] Floating Action Button (fab) Appears Over Fixed Toolbar

### ISSUE THREAD

**Issue by big213** [vuetifyjs/vuetify#5369]
### Versions and Environment
Vuetify: 1.3.1
Vue: 2.5.13
Browsers: Chrome
OS: Windows 7 x64

### Steps to reproduce
Scroll down using the provided reproduction link.

### Expected Behavior
Fixed toolbar appears below the floating-action button (fab) when scrolling down.

### Actual Behavior
Fixed toolbar appears above the floating-action button when scrolling down.

### Reproduction Link
https://codepen.io/big213/pen/jeKQyX

---

**Comment by SnakeyHips** [comment]
Changing the z-index of the v-toolbar to 5+ fixes it so maybe the default z-index of the toolbar should be increased.

**Comment by big213** [comment]
@SnakeyHips appreciate the advice, and maybe I should have mentioned this in the original report, but changing the z-index to 5 causes issues with the fixed navigation drawer, as shown here:

https://codepen.io/big213/pen/mzvpOV

**Comment by KaelWD** [comment]
z-index needs a do-over, they're all really low from back when cssnano was messing things up.
