### ISSUE TITLE
Checkbox alignment in v-select(multiple)

### ISSUE THREAD

**Issue by dzeroone** [vuetifyjs/vuetify#5372]
### Versions and Environment
Vuetify: 1.3.1
Vue: 2.9.17
Browsers: Chrome 70
OS: Ubuntu 17.10

### Steps to reproduce
use vuetify's stylus version to 
at _src/stylus/main.styl_ file `@import './components/*'` is importing file in alphabetic order. So,
__selection-controls.styl_ is imported after __list.styl_. Which creates problem for _v-select_ component. When I use it with `multiple` option flag, the checkboxes are not properly aligned with checkbox label

![ckb-problem](https://user-images.githubusercontent.com/5366980/47267522-ce572c00-d566-11e8-83b8-8aab13d3cb08.png)

![ckb-problem-css](https://user-images.githubusercontent.com/5366980/47267524-d4e5a380-d566-11e8-964a-a4c7d4b7bf57.png)

**Comment by jacekkarczmarczyk** [comment]
Possible duplicate of https://github.com/vuetifyjs/vuetify/issues/3583

Closing due to lack of reproduction and inactivity
