### ISSUE TITLE
[Feature Request] add icon color and text color parameters for <v-alert>

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#5375]
### Problem to solve
Contrast issues, since right now the icon color and text color is fixed

### Proposed solution
Add 2 more parameters to control them.

**Comment by johnleider** [comment]
Text can be controlled by using helper classes and there is an slot for icons now (in 2.0)

**Comment by blalan05** [comment]
This is available in the 2.0 alpha.
