### ISSUE TITLE
[Feature Request] Bug in Carousels component

### ISSUE THREAD

**Issue by sergeyxo** [vuetifyjs/vuetify#5376]
### Problem to solve
In https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VCarousel/VCarousel.ts
in genItems (): VNode {
const length = this.items.length
  ....
}
if  this.items is undef or null
then error  in render component

### Proposed solution
add check this.items

**Comment by jacekkarczmarczyk** [comment]
Please use proper template (it's a bug report, not feature request) and provide a reproduction
