### ISSUE TITLE
v-select the array automatically clears duplicate element

### ISSUE THREAD

**Issue by thongtran957** [vuetifyjs/vuetify#5378]
I have question : 
       when i use v-select , i have array   items: ['Foo', 'Foo', 'Fizz', 'Buzz']. But when show layouts , the array only show Foo, Fizz,Buzz . (the array automatically clears duplicate element)
       link: https://codepen.io/anon/pen/YJjYEj?&editors=101
       i want when show layouts , i have array show Foo, Foo, Fizz, Buzz 
thanks

**Comment by KaelWD** [comment]
If v-model is set to `Foo`, which item would be highlighted? If you have two different items with the same text, use objects with a unique `value` property instead.
