### ISSUE TITLE
[Feature Request] Add clarification to layouts documentation

### ISSUE THREAD

**Issue by thejoecode** [vuetifyjs/vuetify#5379]
https://vuetifyjs.com/en/layout/pre-defined#all-about-app

Current warning:

> In order for your application to work properly, you must wrap it in a v-app component. This component is required for determining grid breakpoints for the layout. This can exist anywhere inside the body, but must be the parent of ALL Vuetify components.

I'd like to add to the warning block: 

> v-content needs to be a direct descendant of v-app.

 Spent several hours troubleshooting why v-content was not filling the screen. Had a router between v-app and v-content and it was not working as expected. Even adding an empty div with height 100% causes v-content to only take up the middle of the screen.

Here I added a div between the v-app and v-container, the <> code link is no longer centered on the page and the v-content is not filling the section between the header and footer.

https://codepen.io/thejoecode/pen/Zqjqev

If you delete the div with class fullHeight you will see the v-container take up the full screen again.

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #643](https://github.com/vuetifyjs/vuetifyjs.com/issues/643) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MajesticPotatoe** [comment]
Updated https://github.com/vuetifyjs/vuetify/commit/a8f2f2b748f7bc07edf555cb2ce7f669a223e399
