### ISSUE TITLE
Reset Treeview

### ISSUE THREAD

**Issue by ahmadnchami** [vuetifyjs/vuetify#5380]
### Versions and Environment
Vuetify: 1.3.1
Vue: 2.5.17
Browsers: Chrome
OS: Windows 10

### Steps to reproduce

Treeview with "Selectable" option

### Expected Behavior

Clearing the model should reset all selections

### Actual Behavior

Treeview does not reset

### Reproduction Link

https://codepen.io/anec/pen/ZqjVNK?editors=1010
---

### Additional Comments:
Example is taken out of the official docs

**Comment by nekosaur** [comment]
Has been fixed in #5373
