### ISSUE TITLE
add full width snakbar

### ISSUE THREAD

**Issue by Akaronte** [vuetifyjs/vuetify#5381]
### What problem does this feature solve?

I think adding the full width to the snackbar will expand the range of vuetify design tools, it's an easy change and it's very important toadters

i share a codepen of the example
https://codepen.io/Akaronte/pen/JmBwvM

### What is your proposed solution?

add a props full-width un v-snakbar componente
add the css in the style for fulld option in ts

**Comment by KaelWD** [comment]
This is a material design library, and MD spec says snackbars should only be full-width on mobile (which they already are). Thanks you for the feature request, but this is not something we are looking to implement at this time.
