### ISSUE TITLE
[Enhancement] Remove extra div from list tiles

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#5383]
https://github.com/vuetifyjs/vuetify/pull/3473#pullrequestreview-101387802

Close this as invalid and I'll ban you m8

![image](https://user-images.githubusercontent.com/16421948/47301234-2a56a900-d66a-11e8-99ad-aad04d5f0dff.png)

**Comment by KaelWD** [comment]
This is breaking v-combobox since 390d2897e6147b78fdaebb4155e1b81439800a5f, probably because list tiles have `...this.$listeners` twice.

**Comment by jacekkarczmarczyk** [comment]
Fixed in 2.0
