### ISSUE TITLE
VTreeview can't set single-select mode !

### ISSUE THREAD

**Issue by murfey-sea** [vuetifyjs/vuetify#5388]
my code is :` <v-treeview :items="items" hoverable  v-model="select" selectable></v-treeview>`
and you'll  see checkbox in v-treeview, but i want to use single-select not multi-select!

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
