### ISSUE TITLE
Vuetify css ".tabs ul" is messing up typographic use of <ul>

### ISSUE THREAD

**Issue by firepick1** [vuetifyjs/vuetify#539]
### Steps to reproduce
The vuetify.min.css includes a style definition for the ".tabs ul" selector expression.
This works wonderfully for Vuetify components, but sadly disables typographic use of &lt;ul&gt; for bulleted lists. The bullets in a card in a tab end up in to the left of the paragraph. 
See https://codepen.io/anon/pen/KmRYwG?)#

### Versions 
Vuetify 0.11.1
### What is expected ? 
HTML ul element behaves as without Vuetify.
### What is actually happening ?
The  ".tabs ul" selector style padding declared in the vuetify.min.css cannot be overridden except by !important, which is very ugly. Even class="pl-6" doesn't do anything either for the ul element. I have even attempted other selector overrides, such as a body attribute "override" used with "[override] ul". A truly horrible workaround is to put the ul in a div with left padding. 

Would it be possible to narrow the scope of the ".tabs ul" selector style so that it limits itself to the actual elements used by Vuetify? For example ".tabs .tabs__container" might work, etc.

### Reproduction Link
https://codepen.io/anon/pen/KmRYwG?)#

**Comment by firepick1** [comment]
BTW. I found this using mobile-tabs-2, which has an unbalanced closing &lt;v-tabs-items&gt; at the bottom of the example. I removed that tag but it did not change anything. Either there is a missing opening tag or the closing tag should be removed from the example.

**Comment by johnleider** [comment]
This is corrected for the next release

**Comment by firepick1** [comment]
Yippee!!!!

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/components/_tabs.styl#L13 this is the culprit and it has already been removed on dev.

**Comment by firepick1** [comment]
Thank you. :)

I gave a presentation to a client today, recommending total abandonment of ANgularJS and Bootstrap for Vue+Vuetify. Keep up the great work!
