### ISSUE TITLE
v-timeline CSS bug with slot="opposite" and v-card

### ISSUE THREAD

**Issue by jvanst** [vuetifyjs/vuetify#5397]
### Versions and Environment
Vuetify:  v1.3.1
Vue: v2.5.17
Browsers: Chrome
OS: macOS Mojave

### Steps to reproduce
When using a v-card component in the opposite slot the small arrow pointer is facing the wrong direction.

### Expected Behavior
Expected it to point into the middle of the timeline.

### Actual Behavior
Pointed outwards.

### Reproduction Link
[https://codepen.io/jvanst/pen/zmJgao](https://codepen.io/jvanst/pen/zmJgao)

### Additional Comments:
Here is a solution, should I create a PR?

```
.v-timeline-item
  display: flex
  flex-direction: row-reverse
  padding-bottom: 24px

  &:nth-child(odd):not(.v-timeline-item--right), &--left
    flex-direction: row

    .v-card:before, .v-card:after
      transform: rotate(180deg)
      left: 100%

    .v-timeline-item__opposite
      margin-left: 96px
      text-align: left

      .v-card:before, .v-card:after
        transform: rotate(0)
        left: (0% - 4px)

  &:nth-child(even):not(.v-timeline-item--left), &--right
    .v-card:before, .v-card:after
      right: 100%

    .v-timeline-item__opposite
      margin-right: 96px
      text-align: right

      .v-card:before, .v-card:after
        transform: rotate(180deg)
        right: (0% - 4px)
```

**Comment by nekosaur** [comment]
PRs are always welcome
