### ISSUE TITLE
[Enhancement] Datatable select-all disable

### ISSUE THREAD

**Issue by mazyvan** [vuetifyjs/vuetify#5402]
### What problem does this feature solve?

This is a simple request I can't disable the `select-all` option on datatables     

![image](https://user-images.githubusercontent.com/10915753/47381371-76830700-d6c5-11e8-8adf-522613839644.png)
As you can see on the checkbox I have the option, but not on the `select-all` button

### What is your proposed solution?

![image](https://user-images.githubusercontent.com/10915753/47381548-e7c2ba00-d6c5-11e8-852e-7257d9baf9f9.png)

**Comment by nekosaur** [comment]
We need a better way to customize the select-all checkbox than littering the data-table with more props. This is something I'm looking at for the 2.0 refactor.

**Comment by mazyvan** [comment]
Haha tell me about it. Look at this  
`<v-autocomplete v-model="vAutocompleteModelo.select" v-bind:items="vAutocompleteModelo.modelos" v-bind:loading="vAutocompleteModelo.isLoading" v-bind:search-input.sync="vAutocompleteModelo.search" label="Buscar Modelo de Producto" item-text="nombre" :chips="true" browser-autocomplete="off" hint="Ingresa por lo menos 3 caracteres" hide-no-data hide-selected return-object></v-autocomplete>`

It's a great idea to think about changing this. Maybe using some configuration object

And btw thanks. It's by far the best framework for Vue

**Comment by nekosaur** [comment]
This is veering into OT, but one way to make that a little bit more readable would be to

1. use the shorthand `:` instead of `v-bind:`
2. put each prop on a new row

**Comment by mazyvan** [comment]
yep I know. it's just that the project is a little bit big and there are some conventions

**Comment by alexela8882** [comment]
The solution for now is to not use `select-all`, put a dummy header for replacement instead.

**Comment by nekosaur** [comment]
select-all checkbox is customizable in 2.0 with slot `header.data-table-select`

**Comment by mohamedmostafamasarat** [comment]
I`d recommend that you use the slot header `header.data-table-select` to disable the select all

` <v-data-table show-select v-model="selected" :headers="headers" :items="items" :items-per-page="15" class="elevation-1">
            <template v-slot:header.data-table-select>
            </template>
        </v-data-table>`
