### ISSUE TITLE
[Bug Report] Selection controls have bottom margin with no details

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#5404]
### Versions and Environment
**Vuetify:** 1.3.2
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Windows 10

### Steps to reproduce
Toggle styles in codepen

### Expected Behavior
Should have no space under when not using details

### Actual Behavior
Has margin!

### Reproduction Link
[https://codepen.io/johnjleider/pen/LggjZR?editors=1111](https://codepen.io/johnjleider/pen/LggjZR?editors=1111)

**Comment by KaelWD** [comment]
Works in the documentation, dist css has a different rule order somehow
https://vuetifyjs.com/en/components/data-tables#example-headers

**Comment by johnleider** [comment]
Typo in commit message, closed in 31f12b9

**Comment by mxs42** [comment]
For some reason I have it now?
v-select with multiple doesn't align checkboxes properly.
Documentation example is working correctly.
