### ISSUE TITLE
[Regression] dark animation makes theme transition much slower

### ISSUE THREAD

**Issue by jsmedmar** [vuetifyjs/vuetify#5405]
### Versions and Environment
Vuetify:1.3+
Vue: 2.+
Browsers: chrome
OS: mac

### Previously worked in:
Vuetify: < 1.1.9
Vue: 2.+

### Steps to reproduce

Simply toggle dark.

```html
<v-app id="inspire" :dark="isDarkTheme">
 </v-app>
```

### Expected Behavior

In versions earlier than 1.1.9 the transition to the dark theme was really fast!

### Actual Behavior

After 1.2.+ the transition to dark seemed to introduce some animations (e.g color fading). Maybe add an option to disable such animations so that changing themes is fast again?

### Reproduction Link

Not sure how to do this.

**Comment by jacekkarczmarczyk** [comment]
Closing due to lack of reproduction and inactivity
