### ISSUE TITLE
[Documentation] Need more information on how to create filters

### ISSUE THREAD

**Issue by graham-sportsmgmt** [vuetifyjs/vuetify#5409]
I'm new to Vuetify but am really impressed.  However, the documentation needs a lot more details on the filtering available in select and data-tables.

I'm happy to contribute by rolling up my sleeves and writing, but someone will need to tell me how this works.

**Comment by KaelWD** [comment]
Documentation issues should go on https://github.com/vuetifyjs/vuetifyjs.com, but if you just have questions about something use [discord](https://community.vuetifyjs.com)

**Comment by graham-sportsmgmt** [comment]
I wouldn't have questions if the docs had more details.  I'll open this on the other repo.
