### ISSUE TITLE
V-app component click event error.

### ISSUE THREAD

**Issue by dacastro4** [vuetifyjs/vuetify#541]
I'm not quite sure how to call this bug. But it seems like a click event issue.

There's an error with the v-app component, I think. I used the dev tools from Chrome to check which component was triggering the click event again and it seems to be the app component.

I'm attaching the three steps that is when I stopped dragging on the grid.

<img width="1438" alt="step 1" src="https://cloud.githubusercontent.com/assets/7808930/26043687/2924e5fc-390d-11e7-97d1-776bbcf0d8cb.png">
<img width="1440" alt="step 2" src="https://cloud.githubusercontent.com/assets/7808930/26043685/29246aa0-390d-11e7-9cfc-c6bea07292ed.png">
<img width="1440" alt="step 3" src="https://cloud.githubusercontent.com/assets/7808930/26043686/2924637a-390d-11e7-9933-b3a058d3fc83.png">

### Steps to reproduce
Click a drag to select multiple items in the grid

### Versions

Vuetify 0.11.0
Vue v2.3.3
Chrome 57 MacOS Sierra

### What is expected ?
User should be able to drag and select multiple items and at the end of the dragging a dialog should appear.

https://jsfiddle.net/dacastro4/Lhoww3c2/

### Reproduction Link

https://jsfiddle.net/dacastro4/h3mgkjjc/

# Update

After a little of testing, not even with the stopPropagation it's working now.

**Comment by dacastro4** [comment]
Adding `e.stopPropagation();` to the binding function fixed the problem but I don't know if it will cause more issues yet.

# Before
```
exports["a"] = {
  bind: function bind (el, binding, v) {
    v.context.$vuetify.load(function () {
      var click = function (e) { return e.stopPropagation();directive(e, el, binding, v); }
      document.querySelector('[data-app]').addEventListener('click', click, false)
      el._clickOutside = click
    })
  }
```

# After
```
exports["a"] = {
  bind: function bind (el, binding, v) {
    v.context.$vuetify.load(function () {
      var click = function (e) { return directive(e, el, binding, v); }
      document.querySelector('[data-app]').addEventListener('click', click, false)
      el._clickOutside = click
    })
  }
```

**Comment by johnleider** [comment]
I am unable to reproduce or even see anything from the linked reproductions.

**Comment by dacastro4** [comment]
@johnleider you're right, I can't see the output.. Anyways, I just update the links.

**Comment by johnleider** [comment]
I still cannot reproduce anything from your links. If you are able to fix it please open a new issue.
