### ISSUE TITLE
[Bug Report] v-checkbox with tabindex creates two tabstops

### ISSUE THREAD

**Issue by grant007** [vuetifyjs/vuetify#5412]
### Versions and Environment
Vuetify: 1.3.1
Vue: 2.5.16
Browsers: Chrome, Safari
OS: OSX

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Create a v-checkbox like...
`<v-checkbox v-model="x" :tabindex="1"></v-checkbox>`

## Expected Behavior

Single tabindex="1" attribute on the resultant input element.

### Actual Behavior

Two tabindex="1" attributes, one on a parent div and one on the input element.
### Reproduction Link

https://codepen.io/grant007/pen/LgXYew
---

**Comment by KaelWD** [comment]
Worked in 1.0, broken since 1.1

**Comment by scippio** [comment]
+ v-switch
