### ISSUE TITLE
[Bug Report] tooltip closed immediately after it's opened if mouse is on it

### ISSUE THREAD

**Issue by davidp-ctg** [vuetifyjs/vuetify#5413]
### Versions and Environment
Vuetify: 1.3.2
Vue: 2.5.17
Browsers: Firefox 63.0 (64-bit)
OS: Windows 10

### Steps to reproduce
Place a v-tooltip and open the responsive design mode (or just resize the window) so the tooltip opens under the mouse cursor.

### Expected Behavior
The tooltip stays open.

### Actual Behavior
Tooltip repeatedly opens and closes.

https://i.imgur.com/2obMlPV.gifv

### Reproduction Link
https://vuetifyjs.com/en/components/tooltips

**Comment by jacekkarczmarczyk** [comment]
1.2.0 https://codepen.io/anon/pen/YJRPGN

**Comment by KaelWD** [comment]
Resolved in 2.0, tooltips no longer respond to pointer events.
