### ISSUE TITLE
[Feature Request] Allow v-date-picker select week days

### ISSUE THREAD

**Issue by pedritin91** [vuetifyjs/vuetify#5415]
### Problem to solve
Some times I want to select the week-day, to mark a week day period.

### Proposed solution
When date-picker opens, the selection type (maybe called 'week-day'), select the year and month, and then, thanks to a prop called **selectedWeekDay** which might be bound to a value to get it, user finally select week day.

**Comment by jacekkarczmarczyk** [comment]
Can you show a working example of that in some other framefork or just a standalone lib? I think I understand what it should do but I dont understand the purpose or rather UI usability, imho it would be better if you just have 2 fields - month picker and select with 7 values (mon-sun)

**Comment by pedritin91** [comment]
You mean, separated fields or both in same picker? If it's the second one better, but different properties, like a **week-day** property for the selected week-day. So better, analyse this: I'm trying to build a task planner. I want to plan an activity all fridays of July. I want to have tha possibility withou affect the original behavior of the date-picker. I hope be understood. It's my opinion, maybe you make me understand your point or improve mine

**Comment by jacekkarczmarczyk** [comment]
That would probably need a big refactor of date pickers and I don't this it could happen soon, but you can try one of these solutions
https://codepen.io/anon/pen/oaOzYJ?editors=1010

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
