### ISSUE TITLE
[Bug Report] v-radio-group won't respect flex layout

### ISSUE THREAD

**Issue by UncleInf** [vuetifyjs/vuetify#5416]
### Versions and Environment
**Vuetify:** 1.3.2
**Last working version:** 1.2.9
**Vue:** 2.5.17
**Browsers:** Opera 56.0.3051.52
**OS:** Windows 7

### Steps to reproduce
Make few flex elements and inside those flex elements add v-radio. Surround everything with row and v-radio-group. After surrounding everything with v-radio-group flex layout is not respected.

### Expected Behavior
Radio elements stay in grid position defined with v-flex

### Actual Behavior
Radio elements get squeeze ignoring flex layout.

### Reproduction Link
[https://codesandbox.io/s/5m5m0680l](https://codesandbox.io/s/5m5m0680l)

**Comment by cqcmj74** [comment]
Here is a temporarily solution to fix it. 
In  app.vue, overwrite the style as below:
  .v-input--selection-controls .v-input__control{
    width: 100%
  }

**Comment by KaelWD** [comment]
Can you show what you're expecting to happen here? The grid specifies three columns, which is what I'm seeing.

**Comment by UncleInf** [comment]
Please change vuetify version to 1.3.2 in package.json file, you'll see the difference immediately.

**Comment by KaelWD** [comment]
Ok, you should have made that clear in the issue description. The link you posted has no visible problems.

**Comment by KaelWD** [comment]
Issue is caused by caace7224fc316b135fca206bfaf7987ee5c0438, no information given in the commit message as to why that change was made.

**Comment by ksankumar** [comment]
width: auto not taking remaining container spaces.

width:100% solving layout space issue

**Comment by Flyingon** [comment]
<style>
  .v-input--selection-controls .v-input__control{
    width: 100% !important;
  }
</style>

**Comment by johnleider** [comment]
Whatever purpose that style served in the past, it makes no difference to the display now. Reverting caace72
