### ISSUE TITLE
Iconfont Configuration Doesn't Reflect the Icon on Nuxt

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#5417]
### Versions and Environment
Vuetify: 1.2.6
Vue: 2.5.17
Browsers: 70.0.3538.67 (Official Build) (64-bit)
OS: Fedora 28

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Add iconfont configuration as nuxt plugin.

### Expected Behavior

Iconfont configuration reflects the icon.

### Actual Behavior

Iconfont configuration doesn't reflect the icon.

### Reproduction Link

https://codesandbox.io/s/github/jefrydco/vuetify-mdi-icon

---

**Comment by johnleider** [comment]
Wrong repo, this belongs here https://github.com/vuetifyjs/nuxt
