### ISSUE TITLE
[Bug Report] Codepen examples for Groups>Windows missing icon fonts

### ISSUE THREAD

**Issue by tony-thomas-git** [vuetifyjs/vuetify#5420]
### Versions and Environment
**Vuetify:** 1.3.2
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
The examples here https://vuetifyjs.com/en/components/windows#examples uses icon fonts that the corresponding example on codepens do not include. Notice the `<v-icon>mdi-record</v-icon>`  is missing in the codepen examples. 

### Expected Behavior
Documentation examples have exact codepen samples.

### Actual Behavior
codepen missing mdi libraries

### Reproduction Link
[https://codepen.io/tony-thomas-codepen/pen/zmMPgX?&editors=101](https://codepen.io/tony-thomas-codepen/pen/zmMPgX?&editors=101)

### Other comments
i <3 vuetify

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #648](https://github.com/vuetifyjs/vuetifyjs.com/issues/648) via [**ZenHub**](https://www.zenhub.com/)
