### ISSUE TITLE
[Bug Report] color and background-color conflict in v-text-field with outline

### ISSUE THREAD

**Issue by nolde** [vuetifyjs/vuetify#5422]
### Versions and Environment
Vuetify: 1.3.2
Vue: 2.5.17
Browsers: Chrome 69.0.3497.100
OS: Window 10

### Steps to reproduce
In the target `v-text-field` with `outline` set to `true`, set `color` prop, see field label and outline assume color on focus.

Now, set `background-color` prop in same field, notice field label and outline assume color in idle/unfocused mode. Focus the field, notice that it does not assume `color` on focus anymore.

### Expected Behavior
Setting  `background-color` in an outlined field should set idle color, but it should NOT override `color` prop behaviour.

### Actual Behavior
Setting  `background-color` nullifies `color` when `outline` is set.

### Reproduction Link
https://codepen.io/nolde/pen/GYwwVN

**Comment by johnleider** [comment]
This appears to be resolved as of the latest version https://codepen.io/johnjleider/pen/YzVNoLx

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
