### ISSUE TITLE
[Bug Report] v-tab-item with value prop causes codepen to hang

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetify#5427]
### Versions and Environment
**Vuetify:** 1.3.2
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 7

### Steps to reproduce
1. Add `:value="n"` to `v-tab-item`

### Expected Behavior
Codepen not to hang

### Actual Behavior
Codepen hangs

### Reproduction Link
[https://codepen.io/anon/pen/VEqKQK](https://codepen.io/anon/pen/VEqKQK)

### Other comments
Have not had the chance to test it out on real dev environment

**Comment by nekosaur** [comment]
After checking it out in dev env, this is caused by the `mergeData` recursion reported also in https://github.com/vuetifyjs/vuetifyjs.com/issues/630. Waiting for upstream fix.

**Comment by aldarund** [comment]
Dont happen in 1.3.0. but happens in 1.3.1 :)

**Comment by maxvanceffer** [comment]
+1 Found that, if to set :key="{}" some recursion happen. And CPU consumption grow to 100%.

**Comment by nekosaur** [comment]
Does not happen in 2.0

**Comment by adityaism** [comment]
Is there any way to fix this. Currently I don't have time to upgrade to version 2.0
