### ISSUE TITLE
[Feature Request] Documentation improvement suggestions

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#5429]
First of all I want to say kudos to the team for this excellent library and its fast growth. I really like it and want to contribute my grain of sand pointing to what is to me its weak point, that is not really that weak, but I think it could be better to allow us developers make the most of Vuetify. I'm talking about the docs, and more specifically, the docs on the components (the meat of Vuetify). 

On discord you guys told me that you are working on new docs, so I'm glad I came at the right time and 
can bring some suggestions for them.

When I need some UI component, I proceed like this:
1. Go to the docs to find one that fits my needs (for that I rely on the examples to have an idea of what I can do with them)
2. Once selected, learn how can I use it for my use case
3. Use it

And with Vuetify, I feel that the second point isn't fully covered. The current docs don't let me use Vuetify at its full potential because there's limited documentation on exactly what each component or subcomponent does or how should it be used apart from the examples. 

Right now I find myself going to each example trying to deduce how the components should be used and how can I combine various examples to fit my needs, but I would like to have a comprehensive description and usage guidelines for the components so that I don't have to rely on the examples, which maybe never show some of the functionality of the component, because as the word implies, examples are just samples.

To give a particular example (😄), the [docs on tabs](https://vuetifyjs.com/en/components/tabs) give a small description, an Usage section (that's just an example that could be placed with the rest), the API and then the rest of the examples. The tabs have 5 components (v-tabs, v-tab, v-tabs-items, v-tab-item and v-tabs-slider), and nowhere it says what each of these actually is, and how they can and should be used and combined; we have to figure it out from the given examples (that as I said before, may not and probably don't show all the functionality possible).

Some things I should know right away from the tabs docs and had to find out by either deduction or trial :
- v-tabs-slider is optional (I honestly don't even know when would this be useful, since the v-tabs have a slider-color prop)
- I don't need to use v-tabs-items inside v-tabs, I can directly use v-tab-item
- v-tabs-items is useful when controlling content from tabs that are "far" from the tab content
- The v-model on v-tabs controls the selected tab (on the api it says that value "controls visibility")
- To control the selected tab with v-model it has to be a integer that corresponds with the tab index you want to display

So to sum up, at large I'm suggesting two things:
- Descriptions and usage guidelines for each component and sub-component, including what they are, when they should and shouldn't be used, and how they can be combined with the other subcomponents
- Improved and mandatory prop description on the API (several times I was left wondering what some prop does since it didn't have description or it wasn't very descriptive)

As an example of documentation that I find really useful, look at the [sapui5 docs](https://sapui5.hana.ondemand.com/#/api/sap.m.Input/overview). The description on each component is very rich, with when to and not to use them, guidelines, the props are very well described, and the aggregations section describes what we can put inside them (something like what I said about knowing how to combine the components).

This got longer than I expected, but I think it was key to show that this is important.

**Comment by KaelWD** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #654](https://github.com/vuetifyjs/vuetifyjs.com/issues/654) via [**ZenHub**](https://www.zenhub.com/)

**Comment by KaelWD** [comment]
Issue has been unmoved back to here.

**Comment by jacekkarczmarczyk** [comment]
Documentation in 2.0 has received a lot of updates and things that are not covered yet are tracked in https://github.com/vuetifyjs/vuetify/issues/7047 and https://github.com/vuetifyjs/vuetify/issues/7694. And things that are not covered in these 2 issues should be reported in less general issues (for example "prop XXX in component YYY has no description")

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
