### ISSUE TITLE
Fail to load icons

### ISSUE THREAD

**Issue by cexposit** [vuetifyjs/vuetify#5431]
I have recently identified that the icons have disappeared from some components in Codepen while they remain in the webpage of Vuetify.

# Steps to reproduce:

1) Access to https://vuetifyjs.com/en/components/timelines#example-icons. The icons are displayed in the dots of the timeline.

2) Click on 'Edit in codepen'. The icons are not available in this case.

Similar scenario happens in at least treeviews as can be checked in https://vuetifyjs.com/en/components/treeview#example-file-explorer.

# Versions and Environment
Browsers: Chrome and Firefox
OS: Ubuntu

**Comment by jacekkarczmarczyk** [comment]
Issue moved to [vuetifyjs/vuetifyjs.com #655](https://github.com/vuetifyjs/vuetifyjs.com/issues/655) via [**ZenHub**](https://www.zenhub.com/)
