### ISSUE TITLE
[Bug Report] Data Table example Editing field broken when in sorting mode

### ISSUE THREAD

**Issue by fbrbovic** [vuetifyjs/vuetify#5434]
### Versions and Environment
**Vuetify:** 1.3.2
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
1. Select Iron column to be sorted
2. Click on the most bottom Row to be edited for Iron
3. Add some text to the edit box and then delete all the text and add more text and delete all
4. you will see that all the rows for column iron are being modified in the background

### Expected Behavior
It should not modify other rows but the one you are editing

### Actual Behavior
Sorting a colum and then inline editing a field causes data in other rows to be modified and broken

### Reproduction Link
[https://codepen.io/anon/pen/NOedqG?&editors=101](https://codepen.io/anon/pen/NOedqG?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
You've already created an issue https://github.com/vuetifyjs/vuetifyjs.com/issues/653

**Comment by fbrbovic** [comment]
any timeframe when this will be fixed ?

**Comment by MajesticPotatoe** [comment]
known bug #3468
