### ISSUE TITLE
[Bug Report] v-img component isn't displayed in firefox 56

### ISSUE THREAD

**Issue by 1001v** [vuetifyjs/vuetify#5435]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Mozilla Firefox
**OS:** Windows, Linux

### Steps to reproduce
Just use v-img component anywhere.

### Expected Behavior
Working v-img component.

### Actual Behavior
Component works, but .v-responsive block class has zero height, so the image isn't displayed.

### Reproduction Link
[https://codepen.io/1001v/pen/bmOzoz](https://codepen.io/1001v/pen/bmOzoz)

### Other comments
This bug is confirmed on firefox 56, on different machines both windows and linux. Earlier versions probably has this bug too.

**Comment by SnakeyHips** [comment]
This is due to the flexbox issue with earlier [Firefox and Edge versions.](https://stackoverflow.com/questions/44948158/flexbox-overflow-issue-in-firefox)
Updating to the latest version of Firefox will fix it.

**Comment by 1001v** [comment]
@SnakeyHips, this isn't very useful answer, because this is not the firefox or edge repo. Both edge and firiefox (even 56, i presume) are officially supported by vuetify, so "update the browser" isn't the solution.

**Comment by KaelWD** [comment]
> (even 56, i presume) 

We can't support every version of every browser, and in this case it looks like there's no acceptable workaround: https://bugzilla.mozilla.org/show_bug.cgi?id=958714  
You can override `display: flex` on a case-by-case basis, but we rely on that in some scenarios to size the content, so is not a solution for the library itself. 
I strongly suggest updating your browser, even IE11 does this correctly.
