### ISSUE TITLE
[Bug Report] Arrows on nested cards in the timeline component

### ISSUE THREAD

**Issue by MaximilianFranke** [vuetifyjs/vuetify#5437]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
See the nested cards in the sample

### Expected Behavior
No arrows on the nested card

### Actual Behavior
Arrows on the nested card

### Reproduction Link
[https://codepen.io/anon/pen/Jmxdzr?&editors=101](https://codepen.io/anon/pen/Jmxdzr?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/commit/29ebc6438833cd53844c9528dabf72dc16cefdff
