### ISSUE TITLE
I'm a newbie. How do I implement Toast with Snacker?

### ISSUE THREAD

**Issue by have1568** [vuetifyjs/vuetify#5439]
like this https://muse-ui.org/#/zh-CN/toast

I came up with a way to put a hidden Snacker inside the APP component and expose several global methods using Window, such as window.$info(text),window.$error(text).., these methods control Snacker.But I felt uncomfortable doing it.Hope that the author or the big bull do a plug - in.

**Comment by MajesticPotatoe** [comment]
Please use the issue creator to submit issues. Not quite sure where the bug or feature is here. Thank you.
