### ISSUE TITLE
[Feature Request] Select box child object as value

### ISSUE THREAD

**Issue by sirdowan** [vuetifyjs/vuetify#5441]
### Problem to solve
I would like to add the whole child-object I'm iterating through to the function on change, something like this:
v-select :items="items" item-value="sport" @change="selected(item)">
No matter what I do I can't get the whole 'item'. 
Thanks!

### Proposed solution
Not sure...

**Comment by jacekkarczmarczyk** [comment]
Use `return-object` prop

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
