### ISSUE TITLE
[Bug Report] <v-footer> height prop mostly useless

### ISSUE THREAD

**Issue by djhuistra** [vuetifyjs/vuetify#5444]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.16
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Add a `<v-footer>` component to the `<v-app>` and expect that it will be 32px in height.

### Expected Behavior
An added `<v-footer>` should be 32px in height, the default value of the `height` prop. If changed to 25 for example, the `<v-footer>` height should be 25px.

### Actual Behavior
The `<v-footer>` class has a `min-height` of 36px. Making the `height` prop useless if less than 36

### Reproduction Link
[https://codepen.io/anon/pen/XxOjLv](https://codepen.io/anon/pen/XxOjLv)

### Other comments
My proposed solution is to remove the `min-height` from the v-footer class, so that the height prop works as expected.

**Comment by jacekkarczmarczyk** [comment]
fixed by 959f07440fedb76473dedb71b1b0766d238a8531
