### ISSUE TITLE
[Bug Report] Swiping in Vuetify RTL carousel

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#5452]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Linux x86_64

### Steps to reproduce
In a mobile device in RTL, swipe the carousel from left to right.

### Expected Behavior
Carousel's image changes into the one in the left.

### Actual Behavior
Carousel's image changed into the one in the right.

### Reproduction Link
[https://codepen.io/anon/pen/rqRaNJ?editors=1010](https://codepen.io/anon/pen/rqRaNJ?editors=1010)

**Comment by KaelWD** [comment]
Duplicate of #4788

**Comment by ibrahimBeladi** [comment]
Is there any roadmap for extending RTL support cover other non-form components?
