### ISSUE TITLE
[Bug Report] v-switch affect another v-switch when previous was hidden by action

### ISSUE THREAD

**Issue by avengerweb** [vuetifyjs/vuetify#5453]
### Versions and Environment
**Vuetify:** 1.3.3
**Last working version:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64, Linux, Windows

### Steps to reproduce
1. Array with objects (models) [{isValid: true ...}]
2. Switch used to hide model from list using basic vue v-if  and v-for (look on codepen)
3. When you filtering results and hide it, state of switch (active) affects next element, when you click on last element it works correctly

### Expected Behavior
switch should affect another switch

### Actual Behavior
switch affects next switch

### Reproduction Link
[https://codepen.io/anon/pen/MPxYLP?editors=1011](https://codepen.io/anon/pen/MPxYLP?editors=1011)

**Comment by jacekkarczmarczyk** [comment]
That's how vuejs work

<https://codepen.io/anon/pen/YJgXGN?editors=1011>
