### ISSUE TITLE
[Bug Report] Duplicate names in breadcrumbs array lead to error

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#5454]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64

### Steps to reproduce
1. Visit link
2. open console and see error

### Expected Behavior
Breadcrumbs with duplicate names should be possible.

### Actual Behavior
Error.

### Reproduction Link
[https://codepen.io/anon/pen/NOJqqM?editors=1010](https://codepen.io/anon/pen/NOJqqM?editors=1010)

**Comment by onx2** [comment]
What is your use case for the same name being repeated? I would assume each breadcrumb link to be unique since it is a listing of the previous / parent pages.

**Comment by ndabAP** [comment]
My customers can create names for the entities and the entities are nested. Example: User has a table named "Test" and inside that table a dashboard named "Test".

> Tables > Test > Dashboards > Test

**Comment by onx2** [comment]
Got it -- that makes sense. 

I'm not very familiar with the breadcrumb code, but maybe in VBreadcrumbs.ts the genItems function could be refactored to use a different key than the item.text?
