### ISSUE TITLE
[Feature Request] Add @contextmenu event to v-tree, which returns the key of the clicked item (or the item itself)

### ISSUE THREAD

**Issue by pbastowski** [vuetifyjs/vuetify#5457]
### Problem to solve
I want to show a context menu when the user right clicks on a tree item, but there is no easy way to do it now.

### Proposed solution
Add @contextmenu event to v-tree, which returns the item key or preferably the item itself, as payload.

**Comment by o1lab** [comment]
This is very much needed! Waiting for this.

**Comment by divinespear** [comment]
alternatively, can you add slot matched `content` itself to control each node directly? (sry my bad english...)

**Comment by divinespear** [comment]
It will be pleasure if you share, @pbastowski :smiley:

**Comment by johnleider** [comment]
@pbastowski If it's simple enough, maybe you could work with @nekosaur on an implementation within the component itself.

**Comment by pbastowski** [comment]
@johnleider, @nekosaur  Sure, I'd be happy to do that.

**Comment by pbastowski** [comment]
@divinespear 

Here is a codepen link with a wrapper component "s-tree", which implements context-menu, item-click and item dragging (to an editor, not within the tree).

https://codepen.io/pbastowski/pen/OrJzgY?editors=1000

You can take the template #s-tree, the JS code from the STree const and the few lines of CSS and put them together into one component file to make your own s-tree.vue component.

**Comment by divinespear** [comment]
@pbastowski nice work!

**Comment by pbastowski** [comment]
@nekosaur 

I had a look at the source for `VTreeview.ts` and `VTreeviewNode.ts` and the following change would add click and context-menu handling. I tested it visually locally.

Let me know if this makes sense or I'm breaking some stuff inadvertently.

**VTreeviewNode.ts**
Add two handler methods, one for `click-item` and one for `contextmenu-item`.

```js
        // click-item, because click is a native event that can refer to any element
        emitClick(ev, item) {
            this.$emit('click-item', ev, item)
        },
        // contextmenu-item, because contextmenu is a native event that can refer to any element
        emitContextMenu(ev, item) {
            this.$emit('contextmenu-item', ev, item)
        },
```

**VTreeviewNode.ts**
Update genLabel to emit a SPAN with two event hooks.
```js
        genLabel() {
            let self = this
            return this.$createElement(
                'label',
                {
                    slot: 'label',
                    staticClass: 'v-treeview-node__label'
                },
                [
                    this.$createElement(
                        'span',
                        {
                            on: {
                                click(ev) {
                                    self.treeview.emitClick(ev, self.item)
                                },
                                contextmenu(ev) {
                                    ev.preventDefault()
                                    self.treeview.emitContextMenu(ev, self.item)
                                }
                            }
                        },
                        this.text
                    )
                ]
            )
        },

```

**Comment by pbastowski** [comment]
@johnleider @nekosaur 
Guys, I see that in the latest beta you have added the `label` scoped slot for us to use. This is all I actually need to easily implement the above, so, no need to add my above code any more.

Thanks!

**Comment by MajesticPotatoe** [comment]
Glad to hear that solves your request, Thanks for your interest in making Vuetify better. Shall close your FR 👍
