### ISSUE TITLE
Lists handling "target" attribute

### ISSUE THREAD

**Issue by Bronco84** [vuetifyjs/vuetify#546]
I am wondering if there is a way to add the target="_blank" attribute to a list item for use in a nav, or if this feature could be added.

Specifically, I'm using the sidebar with a list of links. I've successfully added my href attributes, but I would like some links to open in a new tab. This doesn't seem possible at the moment. 

Here's an example of how it might work. Perhaps the target could be identified in the parent object among the title and items, but adding it within the array of item objects would be fine too so that you could add the function to only certain items in the list.

```
 itemGroup: [
          { header: 'Navigation' },
          { title: 'Dashboard' },
          { title: 'Jobs' },
          { divider: true },
          {
            title: 'ADD',
            items: [
              { title: 'Job', href: '/addjob', target: '_blank'},
              { title: 'Pickup', href: '/pickup', target: '_blank' },
              { title: 'Customer', href: '/customer', target: '_blank' },
              { title: 'Invoice', href: '/invoice', target: '_blank' }
            ]
          }
]

```

**Comment by johnleider** [comment]
It is not possible, but it sure should be. Easy fix, will ship with 0.12.
