### ISSUE TITLE
[Feature Request] Not executing after updating from 1.3.0 to 1.3.3( > 1.3.0)

### ISSUE THREAD

**Issue by Gregory-Han** [vuetifyjs/vuetify#5460]
### Problem to solve
========= console.window
vuetify.js?ce5b:21922 [Vuetify] 'default slot' is deprecated, use ':items and scoped slot "item"' instead

found in

---> 
at src/components/util/C2iBreadcrumb.vue

at src/components/layout/toolbar/Toolbar.vue
at src/App.vue
Looks like an infinite loop....

### Proposed solution
Well...

**Comment by Gregory-Han** [comment]
This is my package.json
"dependencies": {
    "api-ai-javascript": "^2.0.0-beta.21",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "d3": "^3.5.17",
    "echarts": "^4.2.0-rc.1",
    "es6-promise": "^4.2.5",
    "lodash": "^4.17.11",
    "material-design-icons-iconfont": "^3.0.3",
    "numeral": "^2.0.6",
    "three": "^0.90.0",
    "vue": "^2.5.17",
    "vue-jstree": "^2.1.6",
    "vue-perfect-scrollbar": "^0.1.0",
    "vue-router": "^3.0.1",
    "vuedraggable": "^2.16.0",
    "vuelidate": "^0.7.4",
    "vuetify": "1.3.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.4.2",
    "@mdi/font": "^3.0.39",
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "@vue/eslint-config-standard": "^3.0.5",
    "bootstrap": "^4.1.3",
    "expose-loader": "^0.7.5",
    "javascript-natural-sort": "^0.7.1",
    "node-sass": "^4.9.4",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.5.17"
  }

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by pbastowski** [comment]
@Gregory-Han This is indeed a deprecation notice, stating that the Vuetify API for v-breadcrumbs has been altered with upcoming breaking changes, which apparently have been omitted from the release notes. 

For now you have no problem other than the deprecation message in your dev console. However, if you don't update your code soon, it may stop working with a future release. I have been fixing several such Vuetify deprecation notices, not specifically mentioned in release notes. 

You can reach me on pbastowski at gmail dot com, if you're having trouble figuring this one out.

**Comment by jacekkarczmarczyk** [comment]
Indeed it's just a warning, not a bug/feature request. Please see the example usage in documentation: https://vuetifyjs.com/en/components/breadcrumbs#example-item-slot

**Comment by Gregory-Han** [comment]
After the version is replaced, the execution itself falls into an infinite loop.
v-breadcrumbs has been resolved.

**Comment by Gregory-Han** [comment]
screen is white....

**Comment by jacekkarczmarczyk** [comment]
We require reproduction to be sure that it's not a problem with your environment. If you cannot reproduce it in codepen you can ask on our [Discord channel](https://community.vuetifyjs.com)

**Comment by Gregory-Han** [comment]
I find it.
<v-tabs grow icon-and-text>
      <v-tabs-slider color="yellow"></v-tabs-slider>
      <v-tab v-for="(s, idx) in settings" :key="idx">
        <v-icon :dark='config.dark'>{{s.icon}}</v-icon>{{s.caption}}
      </v-tab>
       **<v-tab-item v-for='(s, idx) in settings' :key='idx' :value='`k-${idx}`'>
        <component :is="s.name"></component>
      </v-tab-item>** 
    </v-tabs>

I modified it as follows.
=== fixed code ===
     <v-tab-item>
        <setting></setting>
      </v-tab-item>

That is ok.
It will run normally.
Why?
