### ISSUE TITLE
[Bug Report] v-dialog custom class/styles

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#5461]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Reproduction link shows a sample of the issue.

### Expected Behavior
1. Inline styles to work on v-dialog component.
2. Scoped CSS styles to work on v-dialog component.

### Actual Behavior
1. Inline styles aren't passed onto rendered v-dialog div.
2. Custom v-dialog classes are ignored when v-dialog div is rendered.

### Reproduction Link
[https://codepen.io/xon5/pen/RedxaX](https://codepen.io/xon5/pen/RedxaX)

### Other comments
This is the only component I've come across this issue with so I presume it's a bug??

**Comment by jacekkarczmarczyk** [comment]
You need to use `content-class` prop: https://codepen.io/anon/pen/jeJxZG

**Comment by xon52** [comment]
I don't think this works with scoped style. Although it may be a webpack issue - I can't figure that out.
