### ISSUE TITLE
[Bug Report] Missing RTL support for TreeView component

### ISSUE THREAD

**Issue by yeya** [vuetifyjs/vuetify#5462]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Windows 10

### Steps to reproduce
Hit the SWITCH button to activate RTL

### Expected Behavior
The spaces before each children should move to the right on RTL,

### Actual Behavior
The spaces remain on left side, so the children doesn't look like children.

### Reproduction Link
[https://codepen.io/anon/pen/ZqPoRR?editors=1010](https://codepen.io/anon/pen/ZqPoRR?editors=1010)

**Comment by yeya** [comment]
I found another bug in treeview rtl, it can be reproduced by the same link.

The arrow direction is pointing to the wrong direction
![image](https://user-images.githubusercontent.com/6382246/48076748-884cca00-e1ee-11e8-9c32-b80dcaca348a.png)
Should I open a new bug?

**Comment by jacekkarczmarczyk** [comment]
Yes, please
