### ISSUE TITLE
[Feature Request] Please add v-checkbox-group

### ISSUE THREAD

**Issue by ElevenRemco** [vuetifyjs/vuetify#5467]
### Problem to solve
When you place multiple checkboxes underneath each other, there is way to much space. There is no nice way to group multiple checkboxes together, even when they do belong together.

### Proposed solution
Implement v-checkbox-group, just like there is a v-radio-group.

**Comment by shanemgrey** [comment]
`hide-details` attribute reduces the vertical space between checkboxes. 
```
<div v-for="item in item">
    <v-checkbox
        v-model="checked"
        :label="item.text"
        :value="item.id"
        hide-details
    />
</div>
```

**Comment by ppatkar** [comment]
Refer closed issue #5627. Can the docs be please updated for example of group v-checkbox and also usage of "multiple" prop for check box?

**Comment by stas-kh** [comment]
Heyya,

I found out the way how to handle a `checkbox-group` like form components:
* https://codepen.io/anon/pen/PgPQNv

The example validates if at least one checkbox selected and shows up a validation message below the group if the element does not pass the validation.

**Comment by ppatkar** [comment]
Thanks. I had already implemented using work-around mentioned by you.

**Comment by MajesticPotatoe** [comment]
This can also now be handled with the use of `<v-item-group>`

**Comment by ly525** [comment]
@MajesticPotatoe can you please give a example?

**Comment by MajesticPotatoe** [comment]
@ly525 you can do it with or without depending on if you need stuff like multiple. heres an example of both <https://codepen.io/majesticpotatoe-the-bashful/pen/ZEbWzMB>

If you have any other questions, make sure to reach out to us in the [Discord community](https://community.vuetifyjs.com).

**Comment by ppatkar** [comment]
@MajesticPotatoe 
The issue is -  unlike v-radio-group which has "rules" prop, v-item-group does not have the prop. 
So multiple check boxes cannot be validated as a single unit.

**Comment by MajesticPotatoe** [comment]
@ppatkar That makes sense. It may actually be more beneficial to deprecate `v-radio-group` in favor of something such as a `v-selection-group` that can just be a wrapper for any selection control to provide the same baseline functionality. Would suggest opening a FR for that.

**Comment by ricardovanlaarhoven** [comment]
I agree with @ppatkar I would love a checkbox group for the label, the rules and perhaps even a v-model just like the v-radio group

For now i've found this "hacky" solution
The rules and labels work, but the v-model on the radio group doesn't

```
<v-radio-group
    label="Branches"
    :rules="[() => serverError('branches')]">
    <v-checkbox
        v-for="branch in branches" :key="branch.id"
        :value="branch.id"
        :label="branch.name"
        dense
        v-model="profile.branches"
        hide-details
        class="my-1"
    />
</v-radio-group>
```
