### ISSUE TITLE
Chip events

### ISSUE THREAD

**Issue by smousa** [vuetifyjs/vuetify#547]
How do I modify the behavior of clicking close on a chip? Would it be click.native or click.stop?

For example, I am using chips to define search filters, and by closing the chip, I want to update the filter.

Thanks

**Comment by nekosaur** [comment]
Chips will emit an input event when closed. So you can do something like `<v-chip close @input="doStuff">`

In the future, please direct any questions to [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by smousa** [comment]
Oh, okay, will do.  Thanks!
