### ISSUE TITLE
[Feature Request] Allow menu to be not openable without disabling activator's functionality

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#5472]
### Problem to solve
Currently if the menu needs to be opened conditionally you need to duplicate the activator's markup for the case when menu should not be openable:

```vue
<v-menu v-if="menuShouldOpenOnClick">
  <foo slot="activator"></foo>
  <bar></bar>
</v-menu>
<foo v-else></foo>
```

In the example below the menu doesn't open when it's disabled but also the button loses it's functionality
https://codepen.io/anon/pen/WaWXeL?editors=1000

### Proposed solution
Either add a new prop to control this behaviour or change the behaviour of the `disabled` prop so that disabled menu doesn't open when the activator is clicked without disabling activator's functionality

**Comment by KaelWD** [comment]
Remove `pointer-events: none`, and just ignore the click instead. 

I'd be fine with doing this in a minor release unless anyone objects too hard.
