### ISSUE TITLE
[Feature Request] [VDataTable] Make actions-prepend items align to the left by default

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#5477]
### Problem to solve
off looking default position for items on actions-prepend slot:
https://codepen.io/mrodal/pen/mzgQoQ
![image](https://user-images.githubusercontent.com/20667544/47673871-9b2f2100-db94-11e8-96f8-41d2fac48633.png)

### Proposed solution
Add flex:1 to the div enclosing the items to make them align to the left by default
![image](https://user-images.githubusercontent.com/20667544/47673882-a41ff280-db94-11e8-92a3-d9df9f2d6146.png)

**Comment by xuanduyrn** [comment]
@johnleider I updated the project's vuetify to> 2.0 @latest version, and my v-datatable previously used slot = "actions-prepend". Now it's gone. How do I know what this slot has changed to?

**Comment by mrodal** [comment]
looks like this slot is gone. Could you confirm @KaelWD @MajesticPotatoe? 
Then this issue no longer applies. Also I couldnt find a reference to this slot being gone on the migration guide
