### ISSUE TITLE
[Bug Report] When the return-object prop is set to false, it interferes with item-text on v-combobox component

### ISSUE THREAD

**Issue by rgb-one** [vuetifyjs/vuetify#5479]
### Versions and Environment
**Vuetify:** 1.3.1
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Linux x86_64

### Steps to reproduce
- Select something from the dropdown
- Instead of item-text (which is set to name), the id for the item shows up in the v-combobox text field. 

### Expected Behavior
When the return-object is set to false, the item-text displays its set value instead of the id.

### Actual Behavior
When the return-object prop is set to false on a v-combobox, the text-field 'item-text' apparently gets changed to the id of the item-value.

### Reproduction Link
[https://codesandbox.io/s/xov7v23wrz](https://codesandbox.io/s/xov7v23wrz)

**Comment by KaelWD** [comment]
combobox won't work without return-object, there's no way to tell if a value is supposed to be user input or an object lookup. 

See #4345, #4423, #5358

**Comment by rgb-one** [comment]
If whatever is typed into the `v-combobox` is not in the items array of objects, then return what was typed.

**Comment by KaelWD** [comment]
What if I type '4'?

**Comment by rgb-one** [comment]
4 doesn't match any of the item-text so it would be a new entry, so just return '4'

**Comment by KaelWD** [comment]
But if I click "Item 4" it would set the model to 4, which is ambiguous

**Comment by rgb-one** [comment]
Why doesn't it work like `v-autocomplete` in that respect? With `v-autocomplete` the `v-model` would use the item-value (id in this case) white the text-field would display the item-text.

**Comment by rgb-one** [comment]
Any reply?

**Comment by KaelWD** [comment]
autocomplete doesn't mix text and value in the same input. If the user enters the ID of an existing item it would be displayed as the text of that item instead of a separate value.

**Comment by SasanFarrokh** [comment]
Any progress?

**Comment by sevillaarvin** [comment]
I tried setting return-object to false, it did return the property (id) in item-value, but it doesn't use the item-text for its label. In the end, I adjusted my code so that it accounts for the return-object property set to true.

![image](https://user-images.githubusercontent.com/33614172/64922364-19260600-d801-11e9-8759-5cfec71e691a.png)

**Comment by stevenspinoza** [comment]
In case anybody find the same issue, **use autocomplete**, which has the correct functionality.
Here a demo/link: [https://vuetifyjs.com/en/components/autocompletes#slots](url)

**Comment by tombien** [comment]
Maybe it helps, I setup my combobox like this, for combining user input and select input.

```
v-model="content"
item-text="value"
item-value="value"
@input="handleInput"

```
```
handleInput(e) {
        console.log(e);
        if(typeof e == 'string') {
            console.log('string - do something with user value');
        }else{
           console.log('object - do something with object, value selected from list');
           console.log(e.value);
           this.content = e.value;
       }
 },
```

**Comment by NekoOs** [comment]
For now, he extended the component like this:

```html
<!-- file BaseCombobox.vue -->
<template>
  <v-combobox v-bind="entries" v-on="listeners">
    <template v-slot:selection="data">
      <slot name="selection" v-bind="{...data, item: itemSelected}"></slot>
    </template>
    <!-- Export other templates -->
  </v-combobox>
</template>

<script>
import { VCombobox } from "vuetify/lib";

export default {
  name: 'BaseCombobox',
  extends: VCombobox,
  computed: {
    entries() {
      return {
        ...this.$props,
        ...this.$attrs,
      };
    },
    listeners() {
      return {
        ...this.$listeners,
        input: (value) => {
          this.itemSelected = value;
          this.$emit('input', _.get(value, this.itemValue, value))
        }
      };
    },
  },
  data() {
    return {
      itemSelected: null
    }
  }
}
</script>
```

**Comment by pjabang1** [comment]
:return-object="false" - Changes the selection behavior to return the object directly rather than the value specified with item-value

**Comment by leeconaway** [comment]
My quick solve (that took an embarrassingly long time to think of, and caused reporting nightmares until I came up with it) for a field that is part of an iterated group of fields was to add a method that returns the value at input...not different from Tombien's just handles any value coming in. Probably better ways but again took me far too long to think of it so thought it may help others as a jumping off point.

Component:
```
<v-combobox
	label="nurse"
	v-model="cdi.nurse"
	@input="cdi.nurse = objToValue(cdi.nurse,'displayName')"
	:items="nurses"
></v-combobox>
```

Method:
```
objToValue(val,field){
	if(val[field]){
		return val[field];
	}else{
		return val;
	}
},
```

**Comment by fiftin** [comment]
Is this bug fixed?

**Comment by AndreyYolkin** [comment]
> Is this bug fixed?

It is not the bug, see https://github.com/vuetifyjs/vuetify/issues/5479#issuecomment-434270907

**Comment by Gnandal** [comment]
You can use, v-select, it does work very well with item-title and item-value

**Comment by sinjiya** [comment]
With Vuetify 3 and Vue 3 composition API, I use the onBlur event to change the combobox to use the selected item-value.

```
<template>
<v-combobox 
     v-model.trim="selected"
     v-model:search="search"
     items="items"
     item-title="text"
     item-value="value"
    @blur="handleInput"
    :name="name"
    :maxLength="maxlength"
    ...
></v-combobox>
...
</template>
<script setup>
const props=defineProps({
    name:{ 
        type: String, 
        required: true
    },
    maxlength:{ 
        type: Number, 
        required: false,
        default: 6
    },
  ...
}

import { ref } from 'vue'
const selected=ref(null)
const search=ref(null)
const items  = ref([ 
  {text: '123456', value: '123456 - Item A'}
 ,{text: '987654', value: '987654 - Item B'}
 ,   ... ]) 

...
function handleInput(event){
    if(typeof event == 'object') {  
          // user selected from the dropdown menu
          // now search.value is an item-text
        let val = items.value.find(item=> item.text==search.value)?.value ?? search.value.slice(0, props.maxlength)
          //  search.value.slice()  is a safety net in case that items.value.find() fails to find the item
        selected.value = val
    }     // else string value is a user input; therefore, leave it the way it is.
}

</script>
```
