### ISSUE TITLE
occasionally there is a black box instead of the image in the carousels [vuetify bug]

### ISSUE THREAD

**Issue by shaotingg** [vuetifyjs/vuetify#548]
Hi , i find occasionally there is a black box instead of the image in the carousels.

![image](https://cloud.githubusercontent.com/assets/13550610/26086899/29971780-3a20-11e7-84a1-ad021a8ce652.png)

**Comment by johnleider** [comment]
This happens when the tab/window is unfocused for a period and then refocused. It takes a second for it to render again.

**Comment by smares** [comment]
I can confirm your findings that it only happens when the tab or window was unfocused, but with latest Chrome stable under Ubuntu 17.04, it never recovers.

**Comment by jteppinette** [comment]
I can also confirm that it never recovers in Mac OSX Chrome Version 58.0.3029.110 (64-bit).

**Comment by lucafaggianelli** [comment]
Confirm no recover also in Firefox on Ubuntu 16.04

**Comment by johnleider** [comment]
I've been working on a fix for this but it will not ship with 0.12 at launch.

**Comment by johnleider** [comment]
So I have exhausted about as much time as I can with this particular issue. I've narrowed it down to an issue with the Vue transitions being stuck on, even when manually removing the classes, it gets the transition declared multiple times. I'll see if I can put together an issue for Vue's repo.

**Comment by mluggy** [comment]
Are you trying a custom transition as sampled here? https://vuetifyjs.com/components/carousels.

I found out you should use "v-fade-transition" instead of "fade" as per https://vuetifyjs.com/motion/transitions. Try this:

```html
<template>
  <v-carousel>
    <v-carousel-item
      v-for="(item,i) in items"
      v-bind:key="i"
      v-bind:src="item.src"
      transition="fade"
      reverseTransition="fade"
    ></v-carousel-item>
  </v-carousel>
</template>
```

**Comment by johnleider** [comment]
I can no longer reproduce this on vue@2.42 and vuetify@0.14.11

**Comment by jacekkarczmarczyk** [comment]
I had it yesterday on dev branch while working on some carousel related issue (Chrome/win)
