### ISSUE TITLE
[Feature Request] Component - Sheets: side

### ISSUE THREAD

**Issue by nathakits** [vuetifyjs/vuetify#5482]
### Problem to solve
Make Vuetify more up-to-date to Material Design design 

####  Use case
Currently Vuetify is lacking `Side sheet` from Material Design Ui component. I would like to be able to use `Side sheet` component in my own projects. It would save me time if this is available in the UI components so I could quickly build my projects.

### Proposed solution
Add [Sheets:side](https://material.io/design/components/sheets-side.html#) to Vuetify UI components

**Comment by KaelWD** [comment]
That's essentially v-navigation-drawer. Material design update is planned for early next year, we're still working on some core functionality first.
