### ISSUE TITLE
[Bug Report] Incorrect value after swapping the items in a VItemGroup

### ISSUE THREAD

**Issue by poulinjulien** [vuetifyjs/vuetify#5484]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
1. Bind a VItemGroup to a set of objects
2. Select (click on) the first item
3. Swap the set of objects with a new one
4. Select (click on) the first item again
5. The wrong item is selected

### Expected Behavior
The correct item should be selected

### Actual Behavior
It looks like the selected item is offset by the previous number of items in the VItemGroup.

### Reproduction Link
[https://codepen.io/anon/pen/VEOMGa?editors=1010](https://codepen.io/anon/pen/VEOMGa?editors=1010)

### Other comments
My guess would be that the problem comes from the registration/unregistration of the items in the VItemGroup (https://github.com/vuetifyjs/vuetify/blob/5f8434bfb21a2319a43861f3627106a99d9414ff/packages/vuetify/src/components/VItemGroup/VItemGroup.ts#L103) but don't take my word for it, I wouldn't want to point you in the wrong direction.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
