### ISSUE TITLE
[Bug Report] Difference in height between v-text-field & v-select 

### ISSUE THREAD

**Issue by wkornilow** [vuetifyjs/vuetify#5485]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Linux

### Steps to reproduce
Just add text field and select components

### Expected Behavior
v-text-field & v-select use same height

### Actual Behavior
   .

### Reproduction Link
[https://codesandbox.io/s/mq3yqp91zx](https://codesandbox.io/s/mq3yqp91zx)

**Comment by onx2** [comment]
The codesandbox doesn't seem to be working. @wkornilow

**Comment by wkornilow** [comment]
@onx2 I just try to follow the link, it`s works, can you pls try again?

**Comment by jacekkarczmarczyk** [comment]
Fixed in 2.0
