### ISSUE TITLE
[Bug Report] Textfield autofocus not working when switching between pages using vue-router

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#5487]
### Versions and Environment
**Vuetify:** 1.3.4
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Open nav drawer, click second link, then the text field does not autofocus.

As well, if the text field was open on default page, then the autofocus works, but then I switch page, and then go back, the autofocus does not work again. 

### Expected Behavior
The autofocus works on initial app load, and if I open the page again from nav drawer.

### Actual Behavior
The autofocus doesn't activate when opening the page.

### Reproduction Link
[https://jsfiddle.net/rhevxaf6/](https://jsfiddle.net/rhevxaf6/)

### Other comments
Might work better if you save the html code to a file and then open it on browser. (because vuerouter checks for links in the url, and jsfiddle changes it)

**Comment by KaelWD** [comment]
See https://github.com/vuejs/vue/issues/8112

**Comment by TheInvoker** [comment]
None of those solutions worked for me.

**Comment by marcus-hiles** [comment]
Hi, try implementing the fix I did here:
https://github.com/vuejs/vue/issues/8112#issuecomment-463635487
