### ISSUE TITLE
changing sidebar width

### ISSUE THREAD

**Issue by finalight** [vuetifyjs/vuetify#549]
is there a correct way to modify the sidebar width? I want to decrease the value but this affects the content somewhat when on mobile view. The contents get shifted to the left when i press on the show menu button

**Comment by johnleider** [comment]
You can modify it by building the css in your project and changing the default $sidebar-width value. If you have any additional questions, please direct them to [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by Flamenco** [comment]
@johnleider What if you only want to change the width of the right sidebar in the complex layout example?

**Comment by johnleider** [comment]
All questions should be directed to the official [Discord](https://chat.vuetifyjs.com) server. Thank you!
