### ISSUE TITLE
[Bug Report] "RangeError: Invalid time value" for v-date-picker with :multiple="true"

### ISSUE THREAD

**Issue by VesterDe** [vuetifyjs/vuetify#5493]
### Versions and Environment
**Vuetify:** 1.3.4
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Open link. Datepicker does now work, claiming 

[Vue warn]: Error in render: "RangeError: Invalid time value"

### Expected Behavior
Should work.

### Actual Behavior
Doesn't work.

### Reproduction Link
[https://codepen.io/anon/pen/rqEoQw](https://codepen.io/anon/pen/rqEoQw)

### Other comments
I put the date in data as "2018-12-12" to not get caught up in localisation issues for Month and Date order.

Removing multiple makes it work

**Comment by KaelWD** [comment]
You have to click "fork" on codepen

`multiple` requires the model to be an array IIRC

**Comment by VesterDe** [comment]
Ah, my bad, forked it now.

I see, I didn't look at the docs clearly enough, it is in fact stated there...

I guess my issue is moot then.

**Comment by VesterDe** [comment]
Haha, Layer 8 issue :)
