### ISSUE TITLE
[Feature Request] Style Compability with Boostrap

### ISSUE THREAD

**Issue by jcjabros** [vuetifyjs/vuetify#5496]
### Problem to solve
Projects created with bootstrap cause styles incompatibilities when adding vuetify.js to the project.

### Proposed solution
Add a prefix to all CSS classes to differ from classes with the same name from other frameworks.
Ex: .display-4 to .vtify-display-4.

**Comment by KaelWD** [comment]
Duplicate of #1561

Why don't you ask bootstrap to prefix their classes instead?

**Comment by jcjabros** [comment]
Because Bootstrap is older than vuetify and one of the most used frameworks.So it will work on created projects or frameworks like Laravel that use Bootstrap for the styles components.

**Comment by sbefort** [comment]
> Why don't you ask bootstrap to prefix their classes instead?

Maybe because you copied their class names like d-flex?
