### ISSUE TITLE
Select is hidden by toolbar

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#550]
### Steps to reproduce
1. Create v-select with 3 ro less items under toolbar
2. Open select. First element hidden under toolbar
### Versions
v0.11.0

### What is expected ?
If in select three or less items then select open UP. But if there more items select open DOWN.

### What is actually happening ?
Select always open DOWN

### Reproduction Link
https://jsfiddle.net/kozack/2kcuwsn6/1/

**Comment by cawa-93** [comment]
Maybe a duplicate #517, but I'm not sure

**Comment by johnleider** [comment]
Can confirm that this has been fixed on dev.
