### ISSUE TITLE
[Bug Report] Date Picker max attribute is not working properly for the date 2018-11-1

### ISSUE THREAD

**Issue by abhijeetjha47** [vuetifyjs/vuetify#5500]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
Set the max to 2018-11-1 , but it allows till 9th of november .

### Expected Behavior
It should be till 1st of november only.

### Actual Behavior
It is allowing till 9th of November.

### Reproduction Link
<a href="https://codepen.io/anon/pen/jegxqR?&editors=101" target="_blank">https://codepen.io/anon/pen/jegxqR?&editors=101</a>

**Comment by KaelWD** [comment]
01
