### ISSUE TITLE
[Bug Report] v-tabs-slider with vue-router works incorrectly after adding query params

### ISSUE THREAD

**Issue by vystepanenko** [vuetifyjs/vuetify#5513]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
Just click "Add query params". After that change tab. Tab will become active but v-tabs-slider will be on current tab. It happens only on first change.
If you'll try to change tab one more time it will work properly

### Expected Behavior
v-tabs-slider must change his position every time

### Actual Behavior
After adding query params on first click v-tabs-slider do not response

### Reproduction Link
<a href="https://codesandbox.io/s/xwlrkmo6q" target="_blank">https://codesandbox.io/s/xwlrkmo6q</a>

**Comment by KaelWD** [comment]
It works if you use vue-router correctly: `this.$router.push({ query: { shop: 21 }})`
