### ISSUE TITLE
[Bug Report] Snackbar @*leave event

### ISSUE THREAD

**Issue by kl3sk** [vuetifyjs/vuetify#5516]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
Open / close snack bar and read the "event log"

### Expected Behavior
Log the leave event

### Actual Behavior
Don't log leave event

### Reproduction Link
<a href="https://jsfiddle.net/klesk/mu2t3fyw/" target="_blank">https://jsfiddle.net/klesk/mu2t3fyw/</a>

### Other comments
May i misunderstood something ?

[Stackoverflow question](https://stackoverflow.com/questions/53119737/vuetify-snackbar-leave-event)

**Comment by johnleider** [comment]
Currently there are no transition hooks propagated from snackbar. This is something we may revisit for v2 but currently is not considered a bug as it is not advertised as part of the api.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by kl3sk** [comment]
@johnleider thank you for your answer, hope the V2 be released quickly 😃 

In fact enter events works !
