### ISSUE TITLE
[Bug Report] Bottom nav display bug on older iOS devices

### ISSUE THREAD

**Issue by mikejamesli** [vuetifyjs/vuetify#5519]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Safari, Google Chrome
**OS:** iOS

### Steps to reproduce
Using a older ios device e.g. iphone6, iPad Mini 2, ipadAir (I used BrowserStack), open safari or chrome, open up a site that uses the bottom-nav vuetify component. 

### Expected Behavior
All bottom nav tabs should be shown and the icon should be above the label.

### Actual Behavior
Tabs overflow offscreen when they should all be shown, icon appears to the right of the label.

### Reproduction Link
<a href="https://codepen.io/mikejamesli/pen/aQbErm" target="_blank">https://codepen.io/mikejamesli/pen/aQbErm</a>

### Other comments

Screenshot of bottom-nav on a working device (latest smartphones, iphone6 plus)- 
![bn1](https://user-images.githubusercontent.com/1974887/47955137-27718780-df8b-11e8-9019-3df36475508f.PNG)

Screenshot of non working device (iphone6, ipad mini)
![bn](https://user-images.githubusercontent.com/1974887/47955147-39ebc100-df8b-11e8-8c98-016815850384.PNG)

For a real example, the code pen did not show the issue maybe because its being sandboxed.

https://www.michaeljamesli.com (working with a workaround) 
https://www.mikejamesli.com (default behaviour)

Workaround I'm using for now:
.v-item-group.v-bottom-nav .v-btn {
  background: transparent !important;
  border-radius: 0;
  -webkit-box-shadow: none !important;
  box-shadow: none !important;
  font-weight: 400;
  height: 100%;
  margin: 0;
  max-width: 168px;
  min-width: 80px;
  padding: 8px 12px 10px;
  text-transform: none;
  opacity: 0.5;
  width: 0%; ---- used to be width 100%
  ms-flex-negative: 1;
  flex-shrink: 1;
}

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity and as v1.5 is no longer within LTS, won't be making any backwards compatible fixes.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
