### ISSUE TITLE
[Feature Request] Movable (Draggable!) Floating Toolbar

### ISSUE THREAD

**Issue by hnviradiya** [vuetifyjs/vuetify#5522]
### Problem to solve
In floating toolbar, we are not able to access the place where it is placed. so it would be great if we can drag it from one position to another position. so that user can work on that part also.

### Proposed solution
User should be able to move (with some dots on left side through which it can be moved) floating toolbar, so that all points of background can be accessed as per user preference. As per developer preference it can be fixed as well.

**Comment by KaelWD** [comment]
Can you show an example of the problem this would solve, or an implementation of it in some other framework?

**Comment by hnviradiya** [comment]
I actually wanted something like this. But I think I have got what I wanted as a standalone feature. So it's okay now. Please refer below links for reference.
https://www.gadgetdaily.xyz/create-stylish-responsive-html5-forms/
https://codepen.io/andyNroses/pen/AXwPkb
