### ISSUE TITLE
[Bug Report] v-img issue - Unknown custom element

### ISSUE THREAD

**Issue by edwardwbli** [vuetifyjs/vuetify#5523]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.13.3

### Steps to reproduce
<template>
  <v-img :aspect-ratio="16/9" src="../assets/DeviceOeeLine.jpg">
    <v-layout pa-2 column fill-height class="lightbox white--text">
      <v-spacer></v-spacer>
      <v-flex shrink>
        <div class="subheading">Jonathan Lee</div>
        <div class="body-1">heyfromjonathan@gmail.com</div>
      </v-flex>
    </v-layout>
  </v-img>
</template>

<script>
  import axios from 'axios'
  import { devicePerfUrl } from '../config'
  export default {
    data () {
      return {
        data: '',
        fetchError: null
      }
    },
    beforeMount () {
      this.fetchDevicePerf()
      setInterval(() => this.fetchDevicePerf(), 10000)
    },
    methods: {
      fetchDevicePerf: function () {
        var self = this
        return axios.get(devicePerfUrl)
          .then(function (response) {
            self.data = response.data
          })
          .catch(function (error) {
            self.fetchError = error
          })
      }
    }
  }
</script>

### Expected Behavior
show image 

### Actual Behavior
image not being shown, and below warning printed in console 
[Vue warn]: Unknown custom element: <v-img> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DeviceOeeLine> at src/components/DeviceOeeLine.vue
       <VCard>
         <OverallOee> at src/components/OverallOee.vue
           <VContent>
             <VApp>
               <App> at src/App.vue
                 <Root>

### Reproduction Link
<a href="https://codepen.io/anon/pen/pQvoGa" target="_blank">https://codepen.io/anon/pen/pQvoGa</a>

### Other comments
v-img

**Comment by jacekkarczmarczyk** [comment]
Your codepen doesn't show the issue and is also full of errors and unrelated code. Please try first reach out to us in our [Discord community](https://community.vuetifyjs.com) if you have any difficulties with using Vuetify.

Thank you for your contribution and interest in improving Vuetify.
