### ISSUE TITLE
[Bug Report] Auto-grow on v-textarea does not work if textarea is hidden (display:none)

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#5526]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
1. Hide textarea or one of its parents with display: none
2. Fill the textarea with enough text so that it should grow
3. Remove display: none from the textarea or its parent to display it again.
4. The textarea did not grow, instead it cuts off the remaining text. It does not grow until you add an additional character to it or call its calculateInputHeight() method manually.

### Expected Behavior
The textarea should adapt to the text size even if it was hidden while the text was inserted (because it was done during loading/initialization for example).

### Actual Behavior
The textarea does not grow if the text was inserted while the textarea was hidden with display: none

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/wQBxKv" target="_blank">https://codepen.io/wistudent/pen/wQBxKv</a>

**Comment by jacekkarczmarczyk** [comment]
You can use `v-if` instead of `display: none` https://codepen.io/anon/pen/rQxgXB

**Comment by KaelWD** [comment]
`input.scrollHeight` is 0 when you hide it that way, we have no way of knowing when it gets shown again. We may switch to an intersectionObserver based approach eventually, but until then you'll have to call calculateInputHeight or simply not place it in the dom until ready.
