### ISSUE TITLE
[Bug Report] Autocomplete is not updating while using no-filter prop

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#5529]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Expected Behavior
Items should update when change items even uses no-filter prop.

### Actual Behavior
Items are not updating, It keeps same items from first state.

### Reproduction Link
<a href="https://codepen.io/navi3591/pen/jQPWKK?editors=1010" target="_blank">https://codepen.io/navi3591/pen/jQPWKK?editors=1010</a>

**Comment by KaelWD** [comment]
That's what `cache-items` does.
