### ISSUE TITLE
[v-data-table] How can I align component to left in actions-prepend slot?

### ISSUE THREAD

**Issue by bongjinpark1** [vuetifyjs/vuetify#5530]
```vue
<template slot="actions-prepend">
  <component />
  <v-spacer />
</tamplate>
Doesn't work.

<template slot="actions-prepend">
  <v-layout justify-start>
    <component />
  </v-layout>
</tamplate>
Doesn't work.
```

How can I? or It's impossible?

Thanks.

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
