### ISSUE TITLE
[Bug Report] v-bottom-nav active link not removed on path change

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#5537]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.30
**OS:** Windows 10

### Steps to reproduce
Click second link at bottom and then click logo

### Expected Behavior
active class from second link removed ( so there only one active v btn at a time)

### Actual Behavior
active class from second link stay in place and two active button displayed
https://i.imgur.com/gYz7yxW.png

### Reproduction Link
<a href="https://codepen.io/aldarund/pen/XymRQd" target="_blank">https://codepen.io/aldarund/pen/XymRQd</a>

### Other comments
Work fine in 1.2

**Comment by KaelWD** [comment]
This only affects bottom nav, tabs are fine.
