### ISSUE TITLE
[Bug Report] lingering v-icon when using v-hover in v-data-table 

### ISSUE THREAD

**Issue by jricke** [vuetifyjs/vuetify#5539]
### Versions and Environment
**Vuetify:** 1.3.6
**Vue:** 2.5.17
**Browsers:** Edge 17.17134, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Hover over first column.

### Expected Behavior
Hover over first column should show icon, when leaving the area, the icon should disappear immediately.

### Actual Behavior
Icon lingers as if it ignores the v-hover delays

### Reproduction Link
<a href="https://codepen.io/anon/pen/MzKrpo" target="_blank">https://codepen.io/anon/pen/MzKrpo</a>

**Comment by rkomiyama** [comment]
You could just do the following:

```
...
<v-hover open-delay="0" close-delay="0">
	<v-layout slot-scope="{ hover }"> 
		<v-flex>
			{{ props.item.name }}
		</v-flex>
		<v-flex v-if="hover" style="position: absolute; left: 300px">
			<v-icon>
				alarm_on
			</v-icon>
		</v-flex>
	</v-layout>
</v-hover>
...
```

**Comment by KaelWD** [comment]
This is due to the catch-all transition john puts on everything: https://github.com/vuetifyjs/vuetify/blob/56c4ab6b77cd68f5ac046ac40ef073af20cf0a47/packages/vuetify/src/stylus/components/_icons.styl#L20

**Comment by jricke** [comment]
Thank you.

I fixed the issue by overriding the transition via css.

**Comment by kynetiv** [comment]
I don't think this applies just to data-tables. In my case v-icon nested in a v-btn ( & .v-btn__content ) all need `transistion: none` in order to remove the lag before the icon is hidden.

```css
.v-btn,
.v-btn__content,
.v-icon {
  transition: none;
}
```
