### ISSUE TITLE
[Feature Request] Allow passing additional props to v-input for on input elements

### ISSUE THREAD

**Issue by FalFire** [vuetifyjs/vuetify#5540]
### Problem to solve
I currently want to be able to set the "autocapitalize" attribute on the HTML input element of a v-text-field. Tomorrow I might want to be able to set yet another attribute directly on the input element.

### Proposed solution
Allow passing a dict of attributes which will be set directly on the HTML input elements of v-input and derived components (using e.g. v-bind="propsObject")

**Comment by jacekkarczmarczyk** [comment]
You can use it now
https://codepen.io/anon/pen/jQWoev?editors=1000
