### ISSUE TITLE
Is there a plan to develop a WeChat miniprogram version?

### ISSUE THREAD

**Issue by callmesoul** [vuetifyjs/vuetify#5541]
WeChat miniprogram has Many people use and develop.
But there is no good style system.
Is there a plan to develop a WeChat miniprogram version?

**Comment by jacekkarczmarczyk** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
