### ISSUE TITLE
[Bug Report] Datepicker scroll is way too sensitive on mac

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#5546]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.14.0

### Steps to reproduce
Open the datepicker and scroll to navigate in the calendar

### Expected Behavior
Normal scroll

### Actual Behavior
Calendar pages scrolling way too fast. 
It's impossible to scroll to the next page because the tiniest scroll movement brings you 5 or 6 pages away.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/date-pickers#example-date-dialog-and-menu" target="_blank">https://vuetifyjs.com/en/components/date-pickers#example-date-dialog-and-menu</a>

**Comment by jacekkarczmarczyk** [comment]
Mouse scroll or touch pad?

**Comment by bviala** [comment]
Touch pad

**Comment by jacekkarczmarczyk** [comment]
It's like that from the beginning, also on win, not sure atm how to approach this

**Comment by Dylan-Chapman** [comment]
Couldn't you just use a standard throttling method on the scroll event?

**Comment by hueiyang** [comment]
I have the same problem, is there any solution ?

**Comment by pcalin** [comment]
Same problem here. Both Windows and Mac, touchpad scroll and mouse wheel.
