### ISSUE TITLE
List Title bar is visible when the dialog in fullscreen is opened

### ISSUE THREAD

**Issue by abishekrsrikaanth** [vuetifyjs/vuetify#555]
### Steps to reproduce
I have 2 lists on the page and a button to open a full-screen dialog on the title bar of the first list. When the full-screen dialog is opened, the title bar of the other lists seem to show on top of the dialog. It seems to have an incorrect elevation or z-index. 

### Versions
[0.11.1](https://unpkg.com/vuetify@0.11.1/dist/vuetify.min.css)

### What is expected ?
The other title bars should not be over the fullscreen dialog

### What is actually happening ?
The title bars on the list show above the full-screen dialog

### Reproduction Link
[JS Bin Example](http://jsbin.com/yaxose/edit?html,output) - Click the button on the title bar to open the fullscreen dialog

**Comment by johnleider** [comment]
I can confirm this has been fixed on dev.
