### ISSUE TITLE
[Feature Request] Disable tab swipe

### ISSUE THREAD

**Issue by psychonetic** [vuetifyjs/vuetify#5551]
### Problem to solve
At the moment it's not possible to disable swiping on mobile devices. 
(and it's not a duplicate of #2711, #1516 or similiar)

### Proposed solution
Add a property to disable swiping.

**Comment by KaelWD** [comment]
There's like a billion duplicates of this, idk which is the original. The solution is to add `touchless` to v-tabs-items
