### ISSUE TITLE
Support touch devices in v-carousel

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#556]
It would be nice, if we can slide carousel items with swipe

**Comment by smares** [comment]
I think swiping should be added to all controls where it makes sense, like pickers and tabs for example, too.

**Comment by evromalarkey** [comment]
better support would be great, it's the only thing that's missing to make a perfect hybrid mobile app

**Comment by ram-you** [comment]
Make it MOBILE FIRST.

**Comment by johnleider** [comment]
Fixed with #931
