### ISSUE TITLE
[Bug Report] @input for v-carousel not triggered

### ISSUE THREAD

**Issue by phortx** [vuetifyjs/vuetify#5561]
### Versions and Environment
**Vuetify:** 1.3.7
**Last working version:** 1.2.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.14.0

### Steps to reproduce
Setup a v-carousel with @input handler and click on the arrow for the next image.

### Expected Behavior
@input handler will be triggered

### Actual Behavior
@input handler is not triggered

### Reproduction Link
<a href="https://codepen.io/anon/pen/pQbEON" target="_blank">https://codepen.io/anon/pen/pQbEON</a>

### Other comments
Not sure in which version this has worked. But it has, we have a feature based on that.

**Comment by KaelWD** [comment]
It should be on `v-carousel`, not `v-carousel-item`. Does look like the model was changed to `@change` in 1.3 though.

**Comment by phortx** [comment]
Yes, of course, I tried both just for fun. I fixed the codepen. `@change` works :)
