### ISSUE TITLE
[Bug Report] Using a CDN with webpack externals (vue-cli-3) is not working

### ISSUE THREAD

**Issue by mkhennoussi** [vuetifyjs/vuetify#5562]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.13.6

### Steps to reproduce
Just import the CDN link to the index.html page, for instance this one :
https://unpkg.com/vuetify@1.3.7/dist/vuetify.min.js

### Expected Behavior
Vuetify should be loaded

### Actual Behavior
Get this issue :

vuetify.min.js:6 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (vuetify.min.js:6)
    at i (vuetify.min.js:6)
    at vuetify.min.js:6
    at vuetify.min.js:6
    at vuetify.min.js:6
    at vuetify.min.js:6

### Reproduction Link
<a href="https://codesandbox.io/s/vue" target="_blank">https://codesandbox.io/s/vue</a>

### Other comments
Is there any doc or tutorial about how to use Vuetify as an external lib downloaded from a CDN and used trough webpack externals on vue app created with vue-cli-3 (vue is imported from node_modules) ? Thanks a lot !

**Comment by KaelWD** [comment]
You'd have to load vue first, but this is not recommended. Just use webpack if you've got it.
