### ISSUE TITLE
[Bug Report] VAutocomplete does not place the cursor on the current item

### ISSUE THREAD

**Issue by toshiroakio** [vuetifyjs/vuetify#5563]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Yandex 18.10.0.2724
**OS:** Windows 10

### Steps to reproduce
1. VAutocomplete set items as array of objects [{text: 'blabla', value: 0}...more]
2. Bind v-model
3. Open VAutocomplete

### Expected Behavior
VAutocomplete should place the cursor on the selected element satisfy to the v-model

### Actual Behavior
VAutocomplete does not place the cursor on the current item

### Reproduction Link
<a href="https://codepen.io/toshiroakio/pen/NENQgP" target="_blank">https://codepen.io/toshiroakio/pen/NENQgP</a>

**Comment by toshiroakio** [comment]
https://codepen.io/toshiroakio/pen/NENQgP
please check it again

sorry for `:menu-props="menuProps"` but `auto: true // does not solve the problem`

please open the link: https://codepen.io/toshiroakio/pen/NENQgP and immediately click on VAutocomplete to open It, then open and close the list several times, at some point it works correctly, but not immediately and not always

**Comment by KaelWD** [comment]
Seems to work every time for me.

**Comment by toshiroakio** [comment]
This is on mobile
https://youtu.be/_XZqV_pF1dI
https://youtu.be/svVKBY0KVmg

on PS the same

**Comment by toshiroakio** [comment]
https://youtu.be/rDj_CTyTFh0 on my PS

**Comment by jacekkarczmarczyk** [comment]
That's what I'm trying to fix in https://github.com/vuetifyjs/vuetify/pull/5448

**Comment by toshiroakio** [comment]
> That's another thing I'm trying to fix in #5448
Thanks
This does not solve the problem, unfortunately. (I cloned your branch and tested it)
I changed the code, please you can check it:
https://codepen.io/toshiroakio/pen/NENQgP

with `menu-props: {auto: true}` - very very slow
for testing you can set `menuProps.auto = true` and `statesCount = 1`, 
if statesCount = very big number - the list very  slow
How to make the list display the selected item when opening and open quickly? 
when `auto=true`, it does not always work and opens the list very slowly.

**Comment by jacekkarczmarczyk** [comment]
So the menu has slightly different position for v-autocomplete and v-select, but that has nothing to do with beign slow, it's a completely different issue, or I don't understand what you mean

**Comment by KaelWD** [comment]
@toshiroakio The solution to that is to not have a very big number, see #2660
