### ISSUE TITLE
[Feature Request] Documentation misleading: append-icon-cb is deprecated

### ISSUE THREAD

**Issue by Extarys** [vuetifyjs/vuetify#5565]
### Problem to solve
The documentation here: https://vuetifyjs.com/en/components/inputs refer to append-icon-cb but I get the following using it:
`[Vuetify] ':append-icon-cb' is deprecated, use '@click:append' instead`

The documentation doesn't say it is deprecated and doesn't refer to the new way of doing this.

Version 1.3.7

### Proposed solution
Fix the documentation

**Comment by MajesticPotatoe** [comment]
removed from docs to avoid confusion as this was deprecated many a version ago.
https://github.com/vuetifyjs/vuetify/commit/7c7859739f8913fe60c0bdc696bce1ff7cb52189
