### ISSUE TITLE
[Bug Report] Y overflow is hidden on mobile

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#5566]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
On wide screen, you get vertical scroll bar

### Expected Behavior
You can scroll down

### Actual Behavior
On mobile screen (xs), vertical scroll bar is disabled. It puts y-overflow-hidden class on html tag. Can't scroll down

### Reproduction Link
<a href="https://codepen.io/anon/pen/pQbdPG" target="_blank">https://codepen.io/anon/pen/pQbdPG</a>

### Other comments
It could be fixed with this

/* VUETIFY */
html {
    overflow-y:auto !important;
}

but even FAQS doesn't mention put important

**Comment by TheInvoker** [comment]
what do you mean change the full screen binding? It doesn't seem like it would have anything to do with a dialog.

**Comment by TheInvoker** [comment]
the dialog is not showing, but it happens anyways.

**Comment by Made-of-Clay** [comment]
I have this same bug/behavior. For me it manifests as a class on the `<html>` tag. The class is `.overflow-y-hidden`, but the result is the same.

**Comment by TheInvoker** [comment]
It seems to occur when a dialog is on the page, doesn't have to be showing. The overflow-y-hidden gets put on the html class, because when the dialog full screen is showing, it has it's own vertical scroll, so vuetify adds overflow-y-hidden to html tag to remove that main vertical scroll so you don't see two. It looks like the problem is it's adding overflow-y-hidden even when the dialog is hidden.

**Comment by KaelWD** [comment]
> what do you mean change the full screen binding

Like #2201, you're switching `is_mobile` from false to true when the component mounts. I'm marking as a duplicate because it's essentially the same thing.
