### ISSUE TITLE
[Bug Report] v-spacer not effective when used as a self closed component

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#5569]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Simply run this code:

```
  <v-card>
      <v-card-title primary-title>
        <div>
          <h3 class="headline mb-0">Ttile</h3>
          <div>Located two hours south of Sydney in the <br>Southern Highlands of New South </div>
        </div>
      </v-card-title>

      <v-card-actions>
        <v-btn left>Share</v-btn>
        <v-spacer />
        <v-btn right>Explore</v-btn>
      </v-card-actions>
</v-card>
```

### Expected Behavior
The 2 buttons should be shown on the extreme sides (left & right)

### Actual Behavior
The 2 buttons are displayed tightly to each others.

### Reproduction Link
<a href="https://codepen.io/begueradj/pen/XxQdEv?editors=1010" target="_blank">https://codepen.io/begueradj/pen/XxQdEv?editors=1010</a>

### Other comments
When using `<v-spacer></v-spacer>` instead of `<v-spacer />`, I get the expected result: the 2 buttons are distant from each others, one is displayed on the right, the other on the left.

Thank you
Billal Begueradj

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue/issues/1036#issuecomment-120634281
