### ISSUE TITLE
[Bug Report] if v-tab is disabled, it is still set as default when component is rendered first time

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5570]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Provided in reproduction link

### Expected Behavior
Second tab is active by default

### Actual Behavior
First tab is active by default

### Reproduction Link
<a href="https://codepen.io/anon/pen/YRGwXE?editors=1010" target="_blank">https://codepen.io/anon/pen/YRGwXE?editors=1010</a>

**Comment by johnleider** [comment]
The only good way to fix this would probably be to add the **disabled** property on `v-item`.

**Comment by jacekkarczmarczyk** [comment]
Fixed in 2.0 https://codepen.io/anon/pen/EBdyRo
