### ISSUE TITLE
[Bug Report] v-tab-item is not showing on dialog when changed on mounted or updated vue instance

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5571]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Follow first reproduction link:
https://codepen.io/anon/pen/bQwpqe?editors=1010
The same situation here:
https://codepen.io/anon/pen/rQMeGd?editors=1010
clicking on second tab is not working unless you click on the first one
Other example provided by zaken shows that it's working with created:
https://codepen.io/anon/pen/oQzxqR?editors=1010

But on any updated instance it's not working also: (click update button first)
https://codepen.io/anon/pen/qQaZJw?editors=1010

Which may cause bugs when you use multiple tabs that are updated constantly

### Expected Behavior
v-tab-item should be visible in all cases

### Actual Behavior
v-tab-item is not visible

### Reproduction Link
<a href="https://codepen.io/anon/pen/bQwpqe?editors=1010" target="_blank">https://codepen.io/anon/pen/bQwpqe?editors=1010</a>

**Comment by 185driver** [comment]
Unless I'm mistaken, I don't think this is a bug since it appears to work fine if you apply the `lazy` prop to v-dialog.

**Comment by MajesticPotatoe** [comment]
Adding lazy to v-dialog does fix this issue. marking closed.

**Comment by gileneusz** [comment]
@185driver @MajesticPotatoe you are right guys!

:majestic_potato: :majestic_potato: :majestic_potato:

**Comment by gileneusz** [comment]
but it still is not working in every case, opened the new issue: 
https://github.com/vuetifyjs/vuetify/issues/5572
