### ISSUE TITLE
[Bug Report] v-tab-item is not showing on dialog when  v-model is changed many times 

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5572]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Follow first reproduction link:
https://codepen.io/anon/pen/vQXKpx?editors=1010

adding lazy prop for v-dialog is not fixing the issue

### Expected Behavior
v-tab-item should be visible in all cases

### Actual Behavior
v-tab-item is not visible

### Reproduction Link
<a href="https://codepen.io/anon/pen/bQwpqe?editors=1010" target="_blank">https://codepen.io/anon/pen/bQwpqe?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/anon/pen/bQwqez?editors=1010

**Comment by KaelWD** [comment]
More like #5401

**Comment by jacekkarczmarczyk** [comment]
#4733 is for slider, this one is for tab contents

**Comment by KaelWD** [comment]
Worked in 1.2: https://codepen.io/anon/pen/OaRxKW?editors=1010

**Comment by johnleider** [comment]
This is no longer an issue as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
