### ISSUE TITLE
[Bug Report] Enter letter in TextField with mask removes numbers

### ISSUE THREAD

**Issue by mathe42** [vuetifyjs/vuetify#5573]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Google Chrome, Firefox 61.0
**OS:** Windows 10

### Steps to reproduce
* Open Codepen
* Enter "123456789"
* Move Cursor betwen 3 and 4
* Enter "a"

### Expected Behavior
Do nothing

### Actual Behavior
Numbers disapear...

### Reproduction Link
<a href="https://codepen.io/mathe42/pen/KrggvK" target="_blank">https://codepen.io/mathe42/pen/KrggvK</a>

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
