### ISSUE TITLE
[Bug Report] using expansion-panel and pagination at the same time will make the expand status of all item as false

### ISSUE THREAD

**Issue by cnwangjie** [vuetifyjs/vuetify#5580]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.10
**OS:** Linux x86_64

### Steps to reproduce
 - create an array of objects, each of them contains an expand status property and the default is true
 - use v-if to render the items in the current page
 - use computed data as the prop `value` of `expansion-panel`
 - change the page
 - expand status array become all false

### Expected Behavior
each panel keep the correct status after page changed

### Actual Behavior
each panel will be collapsed

### Reproduction Link
<a href="https://codepen.io/cnwangjie/pen/qQaVPd" target="_blank">https://codepen.io/cnwangjie/pen/qQaVPd</a>

### Other comments
I tried to use `updatePanels` and `$forceUpdate` but both not work.
Maybe I take the wrong usage, but how can I achieve the pagination effect with `expansion-panel`?
Besides, I think the passed way to control the expand status of panels( props of `expansion-panel-content`) is more convenient than using an array. Why we deprecated it?

**Comment by johnleider** [comment]
This is resolved for v2.
