### ISSUE TITLE
[Bug Report] v-tabs causing unexpected screen scroll

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5582]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Follow codepen:
https://codepen.io/anon/pen/XyjyGr

1. use next/previous button
2. scroll screen top to the half of the first card
3. use next/previous button
4. you will see instant screen scroll

you may try this with next v-tabs - all are cloned

### Expected Behavior
no screen scroll behaviour

### Actual Behavior
screen scroll behaviour

### Reproduction Link
<a href="https://codepen.io/anon/pen/XyjyGr" target="_blank">https://codepen.io/anon/pen/XyjyGr</a>

**Comment by jacekkarczmarczyk** [comment]
Simplified codepen https://codepen.io/anon/pen/oQYodX?editors=1000

**Comment by MatthewAry** [comment]
This issue may have returned with Chrome 74
