### ISSUE TITLE
[Bug Report] Breadcrumb scoped-slot="items" disabled link

### ISSUE THREAD

**Issue by kl3sk** [vuetifyjs/vuetify#5583]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
Change disabled  `true` <-> `false`

### Expected Behavior
The item with `disabled: true` should be disabled

### Actual Behavior
The item with `disabled: true` isn't

### Reproduction Link
<a href="https://codepen.io/kl3sk/pen/EONamy" target="_blank">https://codepen.io/kl3sk/pen/EONamy</a>

### Other comments
Works without `scoped-slot`

**Comment by nekosaur** [comment]
With a scoped slot not using `v-breadcrumbs-item` you'll have to implement a disabled state yourself.

**Comment by nekosaur** [comment]
Fixed https://github.com/vuetifyjs/vuetify/commit/46fd4ee698e1241e483a5a09b8f10aca2457fe06
