### ISSUE TITLE
[Bug Report] v-autocomplete scoped slots are extending given v-flex size

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5584]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Follow modified docs example:
https://codepen.io/anon/pen/BGQoOm?&editors=101

### Expected Behavior
Autocomplete result should be the size of the given v-autocomplete, ending with ellipsis

### Actual Behavior
Autocomplete result size is not predictable, which is bad especially for mobile devices

### Reproduction Link
<a href="https://codepen.io/anon/pen/BGQoOm?&editors=101" target="_blank">https://codepen.io/anon/pen/BGQoOm?&editors=101</a>

**Comment by johnleider** [comment]
**Detachables** are placed at the root of the application. The best way to achieve this functionality is [here](https://codepen.io/johnjleider/pen/GwNMva?&editors=101). The current implementation is intended/expected.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by gileneusz** [comment]
can't see any difference comparing to my example...

**Comment by johnleider** [comment]
After talking with @jacekkarczmarczyk he pointed out that you are probably referring to the chip overflowing. As it stands chips do not wrap and there is no workaround. I'll re-open if someone would like to contribute but this (at least for me) will have to be addressed in 2.0.

**Comment by gileneusz** [comment]
@KaelWD help :roll_eyes:
