### ISSUE TITLE
[Feature Request] Add drag and drop to v-treeview

### ISSUE THREAD

**Issue by Pulstarter** [vuetifyjs/vuetify#5585]
### Problem to solve
Te capacity to drag folders to create a functional file browser.

### Proposed solution
Use the current vue-draggable package to add this feature, or a way to use scoped slots with vue-draggable.

**Comment by andreapier** [comment]
After having experimented a bit with [SortableJS](https://github.com/SortableJS/Sortable) and it's [vue wrapper](https://github.com/SortableJS/Vue.Draggable) I'd say this is a much needed feature.  
I was not able to integrate SortableJS with `v-treeview` as they work in entirely different ways:  
- v-treeview exposes internal node slots (but not the node itself)
- SortableJS uses the DOM directly
- Vue.Draggable needs to wrap elements with a custom element  
  
This cannot currently be achieved as v-treeview does not expose the whole node slot so it all become super difficult: you either have to work with the DOM (which kind of defeats the use of vue itself) or you have to rewrite your personal treeview component.  
At least this is my understanding of the problem.  
  
Does anyone know how to get a decent dnd support in v-treeview?  
I am open to other packages but would prefer sticking to SortableJS if possible.  
Thanks

**Comment by danbaechtold** [comment]
We have a working implementation by using only the prepend-slot (icon), which means that DnD does only work on the icon, not on the label. It would be great to have a slot for the full node.

The way we did it is to use [vue-react-dnd](https://github.com/jenshaase/vue-react-dnd), and make a wrapping element around the actual icon with it. But I guess you could use about any other library, as long as you can live with only the icon beeing drag- and dropable (for now).

**Comment by ulissepress** [comment]
@danbaechtold  can you post the source code of your working example ?

**Comment by danbaechtold** [comment]
@ulissepress OK, but it's really just a workaround until official support is available, and some code is very specific to our product, so I'll just try to show the basic idea.

So in the v-treeview, we now use the label-slot and show both the icon and the label, to make both of them drag- and droppable:
```
<template slot="label" slot-scope="{ item }">
  <drag-drop-slot :class="['tree-item', (over && over.id === item.id ? over.mode : '')]" :key="item.id" :item="item" @drag="drag" @enter="enter" @leave="leave" @hover="hover" @drop="drop">
    <icon :config="item" size="17" />
    <span v-html="item.text"></span>
  </drag-drop-slot>
</template>
```

Then we handle all the events, like this (specific code removed, might be incomplete):
```
drag (dragging) {
  this.dragging = dragging
},
enter (dragging, target) {
  this.expanded.push(target.id)
},
leave (dragging, target) {
  this.over = null
},
hover (dragging, target) {
  let parent = this.findParent(dragging.id, this.tree)
  if (target.id !== parent.id) {
    this.over = { id: target.id, mode: 'append' }
  }
},
drop (dragging, target) {
  let parent = this.findParent(dragging.id, this.tree)
  if (dragging.id !== target.id && target.id !== parent.id) {
    let items = _.cloneDeep(this.tree)
    // get dragging item (local copy!)
    let item = this.findItem(dragging.id, items)
    // remove from parent
    let draggingParent = this.findParent(item.id, items)
    let draggingIdx = draggingParent.children.findIndex(sibling => sibling === item)
    draggingParent.children.splice(draggingIdx, 1)

    // find target (local copy!)
    target = this.findItem(target.id, items)
    // add to target (local copy!)
    target.children.push(item)

    // sort
    if (this.config.options.ddAppendOnly) {
      target.children.sort((a, b) => a['text'].localeCompare(b['text'], undefined, {sensitivity: 'base'}))
    }

    // expand target
    if (this.expanded.indexOf(target.id) === -1) {
      this.expanded.push(target.id)
    }
  }
  this.over = null
}
```
Note, the cloning is because we're working with Vuex and cannot modify these items directly.

The treeview has these props, among others:
```
:items="tree"
:open.sync="expanded"
```

And I've attached the DragDropSlot component (as .txt file, as .vue is not supported), which is really just a wrapper around vue-react-dnd.
[DragDropSlot.vue.txt](https://github.com/vuetifyjs/vuetify/files/2762951/DragDropSlot.vue.txt)

With this, you can append only. In our case, we had some trees which allow the user to reorder childrens manually. If you need that, too, let me know, then I can handover that parts of the code, too.

**Comment by Floriangr** [comment]
@danbaechtold I'm working on a similar issue. Would you mind sharing the part about re-ordering children? That would help me a lot.

**Comment by danbaechtold** [comment]
@Floriangr Sure, basically to support reordering, you would need to change hover and drop:

**hover:**
```
// determine rectangle on screen
const hoverBoundingRect = event.target.getBoundingClientRect()

// get pixels to the top
const hoverClientY = event.clientY - hoverBoundingRect.top

const hoverThird = hoverBoundingRect.height / 3

if (hoverClientY < hoverThird) {
  this.over = { id: target.id, mode: 'above' }
} else if (hoverClientY >= hoverThird && hoverClientY <= hoverThird * 2) {
  this.over = { id: target.id, mode: 'append' }
} else {
  this.over = { id: target.id, mode: 'below' }
}
```

**drop:**
```
// INSTEAD OF add to target and sort, do this:
let targetParent = this.findParent(target.id, items)
let targetIdx = targetParent.children.findIndex(sibling => sibling === target)
targetParent.children.splice(targetIdx + (dropMode === 'below' ? 1 : 0), 0, item)
```

And in your tree, with the mode added as class, you can then make it visible for the user when he is appending or reordering.

**Comment by Floriangr** [comment]
Thanks a lot, @danbaechtold! :)

**Comment by Floriangr** [comment]
Hi @danbaechtold,
apologies to bother you again. I'm trying to recreate your example but struggling with the DragDropSlot component. 
I am getting lots of errors which seem to result from vue-react-dnd:
- [Vue warn]: Injection "dragDropManager" not found
- [Vue warn]: Error in data(): "TypeError: manager is undefined"
And then many more follow-up ones resulting from those I guess.
Not sure if I'm not seeing something but I'm using exactly your DragDropSlot code... 
I have installed:
-     "vue-react-dnd": "^1.1.0",
I'm somewhat out of ideas... Anything that comes to mind?
Cheers,
Florian

**Comment by Floriangr** [comment]
ok, solved ;) DragDropContext is needed in the treeview file...

**Comment by MulderNick** [comment]
Is there already an expected release window for this feature?

**Comment by nekosaur** [comment]
There is currently no plan to implement drag & drop functionality

**Comment by 625781186** [comment]
> ok, solved ;) DragDropContext is needed in the treeview file...

Hello , can you provide a simple example, thanks~

**Comment by websitevirtuoso** [comment]
Wait it also

**Comment by softwareguy74** [comment]
Drag and drop for Treeview is really needed.  Almost every other tree control has it.

**Comment by 625781186** [comment]
> hi @danbaechtold! , I am new to this vue development.
> Can you help me, with the Codepen example for the drag and drop in treeview..
> A help would be appreciated.
> 
> Also when i try your code, i am getting error while creating a treeViewNode.
> Error in render: "TypeError: Cannot read property 'props' of undefined"
> 
> found in
> `<VTreeviewNode>`
> ``

I recommend you use the `iview framework` or the `vue-tree-halower` module.

`iview framework` ‘s `Tree` component support dnd.

**Comment by BundyQ** [comment]
I'm sorry to ask for this feature again but I see people building workarounds for this all the time but none of them really solve the problem completely. The solution for this should not be to switch to Element. There is a semi-solution in place that partly solves this problem with [Vue Draggable] (https://github.com/SortableJS/Vue.Draggable) that a user implemented already as [Vuetify draggable treeview](https://github.com/suusan2go/vuetify-draggable-treeview). However it is not maintained and only supports the basic "items" attribute.

I would love to contribute and bring dnd support into Vuetify or maintain this Gihub package but I am not confident enough in that. We desperately need this feature.

**Comment by YuriiGorin** [comment]
Hi guys! I'm really love vuetify and don't want to switch to Element or anything else, but I really need sortable treeview component.

**Comment by dorajistyle** [comment]
I have got an inspiration from the answer of ingd.(https://stackoverflow.com/questions/59335647/vuetify-treeview-drag-and-drop)

**Comment by tauanbinato** [comment]
At least a node slot on treeview..

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
