### ISSUE TITLE
[Bug Report] v-tab-item 'id' is deprecated, use 'value' instead

### ISSUE THREAD

**Issue by a-di-ez** [vuetifyjs/vuetify#5588]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Linux

vuetify.js?ce5b:21924 [Vuetify] 'id' is deprecated, use 'value' instead
found in
---> < VTabItem >
       < VTabsItems >

**Comment by jacekkarczmarczyk** [comment]
Deprecation warning is not a bug. The bug is that value prop causes code to hang, but that's #5427
