### ISSUE TITLE
[Bug Report] Progress Rounding

### ISSUE THREAD

**Issue by rhydev** [vuetifyjs/vuetify#5591]
### Versions and Environment
**Vuetify:** 1.3.7
**Last working version:** 1.0.18
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
1. Create v-progress-circular with decimal value
2. Observe no overlay stroke

### Expected Behavior
There should be overlay stroke for decimal values

### Actual Behavior
There is not overlay stroke for decimal values

### Reproduction Link
<a href="https://codepen.io/anon/pen/LXbezW" target="_blank">https://codepen.io/anon/pen/LXbezW</a>

### Other comments
Issue is in [this](https://github.com/vuetifyjs/vuetify/blob/45c10ca224b1b209fbde96067c180534789afd83/packages/vuetify/src/components/VProgressCircular/VProgressCircular.ts#L65) line. `parseInt` floors all values so even if a value is 0.99 it will not render anything.

**Comment by jacekkarczmarczyk** [comment]
same for linear progress
