### ISSUE TITLE
I can't dragscroll in vuetifyjs

### ISSUE THREAD

**Issue by thongtran957** [vuetifyjs/vuetify#5594]
I can't use dragscroll in vuetifyjs 
I use vue-dragscroll. link: https://www.npmjs.com/package/vue-dragscroll
how i can use dragscroll ?
thank you.

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
