### ISSUE TITLE
[Bug Report] v-btn inside v-tooltip and v-menu with 'block' prop do not work

### ISSUE THREAD

**Issue by PrismPrince** [vuetifyjs/vuetify#5596]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
Create `v-btn` inside a `v-menu` inside `v-tooltip` using `slot="activator"`

### Expected Behavior
`v-btn` must be block when `block` prop is present

### Actual Behavior
it do not cover the full width of the container when using `block` prop

### Reproduction Link
<a href="https://codepen.io/anon/pen/YRNwex" target="_blank">https://codepen.io/anon/pen/YRNwex</a>

**Comment by jacekkarczmarczyk** [comment]
Same as https://github.com/vuetifyjs/vuetify/issues/5581#issuecomment-437962012
Meanwhile you need to use `full-width` prop on menu: https://codepen.io/anon/pen/jQyvVv

**Comment by PrismPrince** [comment]
Oh thanks! That was great! 😸
