### ISSUE TITLE
[Feature Request] Expose hovered date value on VDatePicker

### ISSUE THREAD

**Issue by VesterDe** [vuetifyjs/vuetify#5598]
### Problem to solve
On the path to making a date-range picker for my app, similar to many booking type systems out there, I'd really benefit from having the VDatePicker expose what date is currently being hovered over (example reference: https://www.booking.com/).

This opens the way to implementing the rest of the features for such a date-range picker.

### Proposed solution
Implementing an event emitter to the VDatePicker, called @hover or something similar, that returns the current date being hovered over.

**Comment by jacekkarczmarczyk** [comment]
Started in https://github.com/vuetifyjs/vuetify/pull/4889

**Comment by VesterDe** [comment]
Ah, I searched issues but not pull-requests...

This is then a duplicate of #4884.

Pull request #4889 was closed due to inactivity, does that mean someone just needs to pick it up and keep it going?

**Comment by jacekkarczmarczyk** [comment]
Yeah, that PR was missing similar functionality for month picker, I'm also thinking about changing the event names to 'date:mouseenter' and 'date:mouseleave'

**Comment by VesterDe** [comment]
Could it also be a separate event for months and days (and, I guess, years), like 'day:mouseenter', 'month:mouseenter', 'year:mouseenter' ?

My use case needs only days to have hover events, so I'm ambivalent about adding month-based functionality of the same kind.

**Comment by jacekkarczmarczyk** [comment]
Month/date(day) should be very similar, year is a bit different but it's also just a few lines of code.
Are you willing to continue working on this?

**Comment by VesterDe** [comment]
I can't promise anything, I'm not familiar with Vuetify internals, but I'll take a look at the current progress and see if I can contribute.

**Comment by johnleider** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/commit/e706660aebe3f11f7869204fee1cee8b62952650

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
