### ISSUE TITLE
Card layout modified by Vue template style

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#56]
On the Vue template file `simple/template/styles.css` the Card component layout gets modified, leaving a transparent bottom section visible.

    .card {
      margin-top: -1rem;
      margin-bottom: 5rem;

![image](https://cloud.githubusercontent.com/assets/882713/21576191/9fbcd7c0-cf0d-11e6-8de8-90d2a986f813.png)

Removing that `.card` styling fixes it.

**Comment by johnleider** [comment]
I updated the styles to be more specific for the intro.
