### ISSUE TITLE
[Feature Request] Allow granular control of button elements inside VDatePicker

### ISSUE THREAD

**Issue by VesterDe** [vuetifyjs/vuetify#5600]
### Problem to solve
On the path to making a date-range picker for my app, similar to many booking type systems out there, I'd really benefit from having the VDatePicker allow granular control over individual date button elements, for instance allowing setting the various directives of each button (color, shape, etc...), and adding additional css classes.

This would be an important step to making a proper date-range picker. (see example: https://www.booking.com)

### Proposed solution
I'm not really sure how to get button data down there. A function|array could be passed via a new prop called 'buttonData', that would return|contain an object(s) with keys matching possible button directives.

A reference is the events/event-color props, but I think buttons can be styled in many more ways than events (just color), so it doesn't seem practical to implement button-color, button-shape, button-classes, button-color-text etc... props, does it?

An MVP for this would be a button-classes prop though, as that would allow control of many aspects of the button directly via classes.

**Comment by tafel** [comment]
+1

**Comment by johnleider** [comment]
As we build version 3 we are evaluating all of our ported components available slots. This seems like a likely customizable slot location and because of that I am going to close this issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
