### ISSUE TITLE
[Bug Report] v-tab-item DOM id property

### ISSUE THREAD

**Issue by clementmas** [vuetifyjs/vuetify#5601]
### Versions and Environment
**Vuetify:** 1.3.8
**Last working version:** 1.2.10
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
`<v-tab-item id="tab-1">`

### Expected Behavior
`<div id="tab-1" class="v-window-item">`

### Actual Behavior
`<div class="v-window-item">`

### Reproduction Link
<a href="https://codepen.io/anon/pen/zMZYoj" target="_blank">https://codepen.io/anon/pen/zMZYoj</a>

### Other comments
`VTabItem` offers an `id` prop to *"set the DOM id on the component"* but it is now stripped out. So it breaks the compatibility for any app using this `id` prop with JS or CSS

**Comment by MajesticPotatoe** [comment]
Your reproduction link seems to be broken (wont load/freezes up browser).
I believe as of v1.3 id was deprecated and replaced with value prop so that it would follow suit of v-window

**Comment by clementmas** [comment]
Yes, the `id` prop used to set the value of `v-model` was deprecated. I'm using the `value` prop instead and it works fine.

My problem came from the ability to set an id on the DOM element that was removed.
Deprecation is supposed to show warning messages at first and not break compatibility.

Anyway I switched to classes now and I managed to get it working.
