### ISSUE TITLE
[Bug Report] V-date-picker picker-date breaks changing months

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#5603]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Add a picker-date attribute to the date picker.

### Expected Behavior
It sets the initial date correctly, but does not allow you to change the month or date afterwards.

### Actual Behavior
Does not allow you to change the date or year

### Reproduction Link
<a href="https://codepen.io/anon/pen/yQMNjO?&editors=101" target="_blank">https://codepen.io/anon/pen/yQMNjO?&editors=101</a>

### Other comments
If I am using this incorrectly, how do you get the datepicker to open to a specific year/month without actually setting its value?

**Comment by jacekkarczmarczyk** [comment]
You need to use `.sync` https://codepen.io/anon/pen/jQBqoq?&editors=101

**Comment by amritk** [comment]
@jacekkarczmarczyk awesome many thanks!
