### ISSUE TITLE
[Bug Report] Slider thumb keeps moving after mouseup event

### ISSUE THREAD

**Issue by cpereyra5199** [vuetifyjs/vuetify#5604]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.13
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.14.1

### Steps to reproduce
On the first slider, if you hold down the max thumb and go all the way right and unclick I would expect the thumb to set on the max value.  However, if you move the mouse back to the left the thumb moves with it.

### Expected Behavior
When the mouseup event occurs the slider should no longer be active or react to mouse input

### Actual Behavior
Slider keep moving with mouse movement after mouseup event

### Reproduction Link
<a href="https://codepen.io/cpereyra5199/pen/MzpadB" target="_blank">https://codepen.io/cpereyra5199/pen/MzpadB</a>

**Comment by sh7dm** [comment]
@cpereyra5199 it seems that this bug occurs only when `mouseup` occurs outside the pen output viewport or on the scroll bar. If I have made a mistake, write about that, I'll reopen it.
