### ISSUE TITLE
[Feature Request] v-tooltip for each of v-treeview elements instead of whole tree component

### ISSUE THREAD

**Issue by frozonfreak** [vuetifyjs/vuetify#5605]
### Problem to solve
Allow to have tooltip for each nodes of a tree. 

### Proposed solution
Add a parameter to tree view to pass tooltip parameter

**Comment by jacekkarczmarczyk** [comment]
This should possible with https://github.com/vuetifyjs/vuetify/pull/5567

**Comment by nekosaur** [comment]
Closing as related PR has been merged.
