### ISSUE TITLE
v-checkbox auto checked problem

### ISSUE THREAD

**Issue by hofamilyiiii** [vuetifyjs/vuetify#5610]
I'm generating v-checkbox using v-for, and I found out that if I unshift a new object to the start of the array, the newly generated checkbox will be checked even if the input-value does not contain its value. But if I just push the new array, the newly generated checkbox will not be checked. Why?

<p data-height="265" data-theme-id="0" data-slug-hash="MzpOeo" data-default-tab="html,result" data-user="ho-xin-jun" data-pen-title="Checkbox Auto Checked" class="codepen">See the Pen <a href="https://codepen.io/ho-xin-jun/pen/MzpOeo/">Checkbox Auto Checked</a>

**Comment by jacekkarczmarczyk** [comment]
It's a vue thing - use `:key="main.value"`: https://codepen.io/anon/pen/MzprvZ
