### ISSUE TITLE
[Feature Request] 3D transformation

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5611]
### Problem to solve
There are no 3D transformations available

### Proposed solution
Implementation of some easy solutions that are available via css:
https://3dtransforms.desandro.com/card-flip

this will allow using 3D transformation inside carousel, creating v-window-like components like v-book with two cards flipping and showing the given content

**Comment by MajesticPotatoe** [comment]
Vuetify already has the ability to create custom transitions.

**Comment by sh7dm** [comment]
@gileneusz It can be done in userland. See [this docs page](https://vuetifyjs.com/ru/motion/transitions#create-your-own) for guide how to create your own transition. 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
