### ISSUE TITLE
[Bug Report] v-data-table actions elements use too much width

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5614]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
see codepen

### Expected Behavior
actions wrapping

### Actual Behavior
.v-datatable__actions__select uses too much space, and transforming actions into two row element

### Reproduction Link
<a href="https://codepen.io/anon/pen/qQrgGx?editors=1010" target="_blank">https://codepen.io/anon/pen/qQrgGx?editors=1010</a>

**Comment by Groxan** [comment]
It can be fixed by changing the `input` type attr (inside `.v-datatable__actions__select > ... > .v-select__selections`) from `'text'` to `'hidden'`.

**Comment by tamirvs** [comment]
Thanks to @Groxan I was able to fix it like this:
```
.v-datatable__actions .v-datatable__actions__select .v-select__selections input {
  display: none
}
```
