### ISSUE TITLE
[Bug Report] Datepicker internationalization

### ISSUE THREAD

**Issue by nikolakumric** [vuetifyjs/vuetify#5618]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.13.5

### Steps to reproduce
Click datepicker input to see datepicker component labels

### Expected Behavior
Datepicker should be using Vuetify lang.current defined in main.js

### Actual Behavior
Datepicker is not using Vuetify lang.current defined in main.js

### Reproduction Link
<a href="https://codesandbox.io/s/yjxz37r4pz" target="_blank">https://codesandbox.io/s/yjxz37r4pz</a>

**Comment by jacekkarczmarczyk** [comment]
closed by https://github.com/vuetifyjs/vuetify/pull/6320
