### ISSUE TITLE
[Bug Report] V-autocomplete with slotted "selection" acts as if chips was enabled

### ISSUE THREAD

**Issue by Balour** [vuetifyjs/vuetify#5625]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 7

### Steps to reproduce
1. Select item in component
2. Press backspace (nothing happens)
3. Press backspace (item is removed)

### Expected Behavior
The text should be selected and start removing characters

### Actual Behavior
The component behaves as if the chips option was present and "selects" the item on first backspace and removes it on a second backspace. An unsuspecting user would probably press more than 2 times and then the additional backspaces after the first 2 will go back in the navigation history.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KrqVgX" target="_blank">https://codepen.io/anon/pen/KrqVgX</a>

### Other comments
To fix my issue, I instead used the "item" slot to show my composed text and put the number as the item-text directly (working codepen: https://codepen.io/anon/pen/aQwNBO). There seems to be a similar issue in #4940, I think this codepen should help in figuring out what's happening.

**Comment by KaelWD** [comment]
> The text should be selected and start removing characters

What text, the one you supplied to the slot? We can't really do that because it could contain anything, and if it was more than just plain text it would cause a confusing jump switching back to text. 

> additional backspaces after the first 2 will go back in the navigation history

No they won't, the input is still active. 

The solution is to use `item-text="no"` to show what you want in the field, and the item slot to show more detail in the menu. You may also need to implement your own filter function if you want to be able to search more than just the ids. 

https://codepen.io/anon/pen/NovyVa?editors=1011

The only caveat here is that highlighting no longer works (#4417)

**Comment by Balour** [comment]
> > The text should be selected and start removing characters
> 
> What text, the one you supplied to the slot? We can't really do that because it could contain anything, and if it was more than just plain text it would cause a confusing jump switching back to text.

The text shown after selecting an item from the list. Normally the input on focus would highlight all of the text and deleting would remove all on the first backspace, or alternatively you can put the cursor somewhere and start deleting characters one by one. That is the expected behavior of the component as shown in the examples. What I have in the first codepen is an input which acts as if the chips property was on, which it is not. I say it acts as chips because when chips mode is active, selecting the input puts the cursor at the end and pressing backspace selects the last chip, pressing a second time actually deletes the chip. This behavior is seen in the examples in the doc.

> > additional backspaces after the first 2 will go back in the navigation history
> 
> No they won't, the input is still active.
I just tried here on this page. 

Steps to reproduce: 
1. Be on this page
2. click first code pen link (no new tab)
3. Select an item from the list
4. while focused in the input, press backspace once, "nothing" happens (it selects the text but not shown since it's not a chip)
4. press again, the text should be deleted
5. pressing again will go back one page in the history and should bring you back here

> The solution is to use `item-text="no"` to show what you want in the field, and the item slot to show more detail in the menu. You may also need to implement your own filter function if you want to be able to search more than just the ids.
> 
> https://codepen.io/anon/pen/NovyVa?editors=1011
> 
> The only caveat here is that highlighting no longer works (#4417)

Yes, I think I'll follow that, at present state my highlighting is not working either. I currently have the whole text as the item-text but I'll adapt it and do a filter function like you did and it should do it nicely.

I still don't understand why the autocomplete acts as if it was chips in certain instances tho

**Comment by Balour** [comment]
I don't think this solution will work as I'm using :search-input.sync="search" which feeds from a database and adding filter seems to break the input, I'm unable to write

**Comment by KaelWD** [comment]
So that did happen back in 0.16, but was removed in 0.17 for the reasons I stated above
https://codepen.io/anon/pen/QYMege?editors=1010
