### ISSUE TITLE
Initialising a drawer on opened mode is showing a weird border

### ISSUE THREAD

**Issue by allanchua101** [vuetifyjs/vuetify#5632]
Initialising a drawer on opened mode is showing a weird border that goes away after closing and re-opening the drawer.

[Open link to view image of the weird border](https://ibb.co/d8Fm5L)

```html
  <v-navigation-drawer 
    class="hidden-xs-only" 
    @mouseover.native="onHover" 
    @mouseout.native="onHoverOut" 
    @click.native.stop 
    :mini-variant.sync="isMini" 
    v-model="isOpened" 
    hide-overlay 
    enable-resize-watcher 
    absolute 
    stateless>
 .....Emitted for brevity.
 </v-navigation-drawer>
```

**Comment by AlexSHoffman** [comment]
@allanchua101 just add `floating` prop to the drawer component as it is [mentioned](https://vuetifyjs.com/en/components/navigation-drawers#api) in the docs

**Comment by allanchua101** [comment]
The floating prop fixed my issue @AlexandreBonneau. Thanks man

**Comment by AlexandreBonneau** [comment]
@allanchua101 You meant @AlexSHoffman I guess ;)
