### ISSUE TITLE
[Bug Report] Prefix text still in black when disabling input

### ISSUE THREAD

**Issue by ThomasFerro** [vuetifyjs/vuetify#5634]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.13.6

### Steps to reproduce
Simply add a v-text-field disabled with a prefix.

### Expected Behavior
The prefix should have the color of the input (gray).

### Actual Behavior
The prefix is still black.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xQroGg" target="_blank">https://codepen.io/anon/pen/xQroGg</a>

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5481

**Comment by vincentauger** [comment]
I am having this issue with Vuetify 1.5.2, Vue: 2.6.6. Problem still reproducing in link above. prefix remains black, does not go grey.
