### ISSUE TITLE
Property or method "$vuetify" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by HamedFathi** [vuetifyjs/vuetify#5635]
Hi

I created a project by Vue CLI 3 (Typescript) after that I added `Vuetify` by this command
```
vue add vuetify
```

Then I used your pre-defined [Google Contacts](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/layouts/googleContacts.vue) layout.

but when I run project I get an error.

![image](https://user-images.githubusercontent.com/8418700/48634947-0cb3ff80-e9dc-11e8-8469-5191d25977ad.png)

![image](https://user-images.githubusercontent.com/8418700/48634891-f60da880-e9db-11e8-8234-195e69c886d6.png)

How to fix it? Is not `$vuetify` a global variable ?

**Comment by gileneusz** [comment]
did you import vuetify inside your <script> tag? 

import Vue from 'vue'
import Vuetify from 'vuetify'

**Comment by HamedFathi** [comment]
@gileneusz 

This is what I have. You can find the repository in [here](https://github.com/HamedFathi/VueDotNetTemplate)

![image](https://user-images.githubusercontent.com/8418700/48637749-e85c2100-e9e3-11e8-8e3f-889565ba5848.png)

**Comment by gileneusz** [comment]
I can't see any issues there. I recommend you to visit need-help:
https://discordapp.com/channels/340160225338195969/340215499398840331

there you can find help way faster than here, creating issue

**Comment by johnleider** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 5 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by HamedFathi** [comment]
@johnleider 

It is so weird I not what is the problem but I removed `node_modules` and re-installed it again now it works.
Anyway thanks for everything.
