### ISSUE TITLE
[Bug Report] v-tabs: slider that shows active item remains visible even when all tabs are removed from v-tabs element

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#5636]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Click "Remove all tabs" button in the codepen snippet. This will remove all tab items but slider will persist as if active tab item is still there.

### Expected Behavior
Slider should not be visible when no tab items are shown

### Actual Behavior
Slider is visible even when no tab items are present

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/KrvPLL" target="_blank">https://codepen.io/milost1982/pen/KrvPLL</a>

### Other comments
Possibly related: there is no way to "deactivate" currently active item, that is, there is no way to clear selection from tab. Please see "Deactivate" button where I try to make no tab item selected.

**Comment by johnleider** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/6d1d51143cc501f0baa0406524dee8ca2c524d5b
