### ISSUE TITLE
[Feature Request] Invalidate current form in a custom component

### ISSUE THREAD

**Issue by vhmolinar** [vuetifyjs/vuetify#5638]
### Problem to solve
I wish I could set current v-form state to invalid in order to work properly with validations in a custom component. This way I can look only to v-model property at v-form in order to know if everything in the form is valid or not.
So far I didn't find any way to do this using vuetify api.

### Proposed solution
I'm not sure the proper way to do it, but what if I could emit an event(simular to input) where v-form can listen and set its state to false(invalid) ?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/3464#issuecomment-370240024

If your component has those properties and methods, you can inject the form and register in the created hook. I think v-input was supposed to be something like this but never got any useful slots so idk what it's actually for.

**Comment by vhmolinar** [comment]
Hi. Thanks for your answer.

Could you please show me how exactly I can do the following?
'you can inject the form and register in the created hook'
