### ISSUE TITLE
vue-cli webpack doesn't run

### ISSUE THREAD

**Issue by thatbignerdguy** [vuetifyjs/vuetify#564]
I'm not sure if this is the right place to put this, but there is no issue tracking in the [webpack repo](https://github.com/vuetifyjs/webpack).

The main.styl file isn't included. Vuetify and stylus-loader are not included as dependencies in the boilerplate webpack template.

### Steps to reproduce

```bash
$ vue init vuetifyjs/webpack test
$ cd test
$ npm install
$ npm run dev
```

### Versions

node: 6.10.3
npm: 4.3.0
vue-cli: 2.8.2
vue: 2.3.3
os: xubuntu 16.04 (64-bit)
browser: Firefox 53.0.2 (64-bit)
vuetify: ??

### What is expected ?

It is expected that the code is built and opened in the browser.

### What is actually happening ?

Vuetify and stylus-loader are not added as dependencies.

```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vuetify' in '/home/foo/test/src'
 @ ./src/main.js 3:0-30
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./src/App.vue
Module not found: Error: Can't resolve 'stylus-loader' in '/home/foo/test/src'
 @ ./src/App.vue 3:0-258
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

Once all of the dependencies are added in, it still doesn't run (unknown custom component 'v-navigation-drawer', 'router-link', etc.).

I think that's as far down the rabbit hole as I'm going tonight. :)

### Reproduction Link

N/A

**Comment by johnleider** [comment]
This will be fixed today.

**Comment by johnleider** [comment]
This should be fixed. If not, open a ticket on the template repo.

**Comment by smorales** [comment]
Hi John, thanks for the update. I was waiting for this and in fact it did resolve for me the problem with `v-navigation-drawer`, but after the update I get now this error:
```
[Vue warn]: Unknown custom element: <v-row> - did you register the component correctly? 
For recursive components, make sure to provide the "name" option.
```
Before the update the `v-row` component was working fine.

Thanks

**Comment by mfferreira** [comment]
@smorales `v-row` was replaced by `v-layout(row)`.
Check https://vuetifyjs.com/layout/grid

**Comment by smorales** [comment]
@mfferreira Thank you! 
It's strange, because I copied today the code from the examples. Was this page https://vuetifyjs.com/components updated today? 

However, thank you very much for the hint.

**Comment by mfferreira** [comment]
@smorales Yes, the docs were also updated.
You can check all breaking changes here: https://github.com/vuetifyjs/vuetify/releases/tag/v0.12.0

**Comment by Dark-Aii** [comment]
Hey guys, I am getting an error on Parallax.
I can't display "parallax--content" on my page. And can't seem to find where it's coming from.
Any help here ?

**Comment by mfferreira** [comment]
@Dark-Aii Please open a new issue for it.

**Comment by Dark-Aii** [comment]
Sorry, will do right away.
