### ISSUE TITLE
[Enhancement] Suggestion to remove !important from .display-{n} classes

### ISSUE THREAD

**Issue by gustawdaniel** [vuetifyjs/vuetify#5640]
I use `bootstrap` with `vuetify` with also other library. All of them use class `display-3`

+ vuetify `styl`

```
.display-3
  font-size: $headings.h2.size !important
  font-weight: $headings.h2.weight
  line-height: $headings.h2.line-height !important
  letter-spacing: $headings.h2.letter-spacing !important
  font-family: $headings.h2.font-family !important
```

+ bootstrap `scss`

```
.display-3 {
  font-size: $display3-size;
  font-weight: $display3-weight;
  line-height: $display-line-height;
}
```

+ other library (argon) `scss`

```
.display-3 {
	span {
		display: block;
		font-weight: $font-weight-light;
	}
}
```

Now my landing page is broken because of `vuetify` class `display-3` have `!important`. It would be easy constrain this by wrapping my other css in `.landing` class and apply enforce applying it due to higher specification of selectors, but `important` in vuetify everything spoils.

**Comment by gustawdaniel** [comment]
Temporary workaround:

For further readers with the same problem:

I not use command:

    // import 'vuetify/dist/vuetify.min.css'

Only append to `/public/index.html` line disabled by default

    <link id="vuetify-style" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.3.7/vuetify.min.css" disabled>

and in router disabling and enabling this line in dependence from if user is on landing/login/register or in dashboard

    routes: [
        {
            path: "/dashboard",
            component: Vuetify,
            children: [
                { path: "", name: "dashboard", component: Dashboard}
            ],
            beforeEnter: (to, from, next) => {
                isMeteorUser().then(response => {
                    // if true, continue, else redirect to Login page
                    if(response) { // logged in
                        document.querySelector('#vuetify-style').disabled = false;
                        next()
                    } else { // not logged in
                        console.log("TO",to);
                        if(to.path === "/") {
                            next({name: 'landing'})
                        } else {
                            next({name: 'login'})
                        }
                    }
                })
            },

        },
        {
            path: "/",
            component: Argon,
            children: [
                { path: "/", name: "landing",  components: { header: AppHeader, default: Landing, footer: AppFooter } },
                { path: "/login", name: "login",  components: { header: AppHeader, default: Login, footer: AppFooter } },
                { path: "/register", name: "register",  components: { header: AppHeader, default: Register, footer: AppFooter } }
            ],
            beforeEnter: (to, from, next) => {
                document.querySelector('#vuetify-style').disabled = true;
                next();
            }
        },
    ],

**Comment by Tribunal51** [comment]
Hi, I have a query, would it work if all !important tags from the Vuetify CSS file are removed so it doesn't override the default styles specified?

**Comment by MartinX3** [comment]
Running into the same problem with vuetify 2.6.14
Classes like `text-sm-h5` force "Roboto" with `!important` which prevents me from globaly define a font-family dynamically.
(Disability help -> Dyslexia Font)

**Comment by johnleider** [comment]
I'm going to remove !important from the font-family designation. Utility classes are supposed to have !important, but in this instance, it doesn't make sense for the family.
