### ISSUE TITLE
[Feature Request] Treeview component: allow access to "v-treeview-node__root" for routing

### ISSUE THREAD

**Issue by moranje** [vuetifyjs/vuetify#5644]
### Problem to solve
I would like to be able to activate a route from a treeview node. The feature allowing access to the label slot solves this incompletely. The more logical level to solve this would be a the "v-treeview-node__root" since it's the DOM node that `hoverabale` option seems to act on.

This may be related:
https://github.com/vuetifyjs/vuetify/issues/5585

### Proposed solution
Either expose the `VTreeviewNode` component or allow for a `treeview-node` slot. Both would need to take the `prepend` and `append`, and soon-to-be `label` slots into account. A third option (not sure if this is feasible) would be allow props to be set on `VTreeviewNode`

**Comment by nekosaur** [comment]
In what way does the label slot solve this incompletely?

**Comment by moranje** [comment]
I want to select a route based on the file I select. The selected file should be marked as `active`. The `.v-treeview-node--active` is set on `.v-treeview-node`.

Then there's the node that's highlighted by hover. That would seem to be the most logical area the click events should be handled from. Perhaps that's better handled with the `update:active` event emitted by VTreeView.

Setting the route from the `label` slot you would not be able set the `.v-treeview-node--active` class and the `prepend` and `append` slots would not be clickable.

<img width="1440" alt="schermafbeelding 2018-11-27 om 20 48 57" src="https://user-images.githubusercontent.com/666528/49107405-ef0d5280-f285-11e8-9583-69113897cff7.png">

Perhaps there is a better way of connecting the TreeviewNode elements to a route but there aren't a lot of examples to explore yet...

Martien

**Comment by sebpalluel** [comment]
I agree, it would be really nice to have access to the v-treeview-node component in some kind of way.

I'm using v-treeview to display a nested menu and i have tweaked the layout of the component with CSS so that it doesn't move to the right on nested routes.

![screen shot 2018-12-11 at 20 18 51](https://user-images.githubusercontent.com/11297176/49824697-f30b9b00-fd82-11e8-98f0-8224bbd1d14e.png)

Currently i'm using a black color with alpha at 0.1 so that it become darker depending of the depth of the node.
```css
.v-treeview-node {
  margin-left: 0px;
  width: inherit;
  /* background-color: rgba(var('--node-color-r'), var('--node-color-g'), var('--node-color-b'), 0.1); */
  background-color: rgba(0, 0, 0, 0.1);
}
``` 
The thing is, with different categories, i'm unable to apply a base color for each without having access to the specific DOM element v-treeview-node in the tree.

Adding a treeview-node slot would work perfectly in my case.

**Comment by nekosaur** [comment]
I am open to suggestions or implementations for how to do allow this gracefully (by exposing a slot). Right now, with the way the component works I see no easy way to implement this.

There are other solutions, like v-treeview-node implementing routable for the original problem, and adding a class/es property on node items for the second.

**Comment by moranje** [comment]
@nekosaur I'd be okay with implementing routable as I don't see a clean way of having the prepend, append and label slots in treeview-node slot.

**Comment by jd0e** [comment]
Is there any movement on that? It looks to me that treeview items are ideal for becoming routables.

**Comment by johnleider** [comment]
After discussion with the team we have decided that the `v-treeview` component is sort of the gold standard when it pertains to functionality of groups of lists. While `v-list-group` has functionality not present in treeview. We are going to keep this in mind as we build version 3; however there will be no changes to treeview in this regard for the v2.x major, and for that reason I am closing this issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
