### ISSUE TITLE
[Bug Report] Slider Keyboard Control (Left Arrow key and Right Arrow key) Not Always Working

### ISSUE THREAD

**Issue by jimmylee850328** [vuetifyjs/vuetify#5650]
### Versions and Environment
**Vuetify:** 1.3.5 (1.3.8 still not working)
**Vue:** 2.5.13
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.13.4

### Steps to reproduce
1. Click the **circle button** on slider.
2. Press the **right arrow key** or **left arrow key** on your keyboard.

### Expected Behavior
I hope when I click **circle button** on slider, I always can use my keyboard to control slider to move left or right. 

Just click any slider on the [Vuetify Official Website](https://v1.vuetifyjs.com/en/components/sliders#introduction), and you can see after you click the **circle button**, you can always move slider by keyboard.

### Actual Behavior
When I click **circle button** on slider, success rate ( use keyboard to move the slider ) is only 5%.

### Reproduction Link
<a href="https://codepen.io/TangentSita/pen/ZmXrbo?editors=1010" target="_blank">https://codepen.io/TangentSita/pen/ZmXrbo?editors=1010</a>

### Other comments
I made two demos below, I hope you can watch them  :D
1. [Not working demo](https://youtu.be/FRFj_ss-dvk)
2. [Working demo](https://youtu.be/6vPjGR6W9fQ)

**Comment by KaelWD** [comment]
Broken since 1.1, only receives focus if you click on the track instead of the thumb.

**Comment by jimmylee850328** [comment]
> Broken since 1.1, only receives focus if you click on the track instead of the thumb.

I see. 
Thank you for your reply :D

**Comment by evanbechtol** [comment]
Is there a plan to fix this? I see that it's _"Broken since 1.1, only receives focus if you click on the track instead of the thumb."_

But when is this going to be fixed?

**Comment by nekosaur** [comment]
fixed in #6424
