### ISSUE TITLE
[Feature Request] Sorting prop for v-select

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5658]
### Problem to solve
I've got array of objects that are not sorted. There is no way that `v-select` could sort it for me, so I need to use computed or raw js methods to sort my array before entering to `v-select`. 

### Proposed solution
It could be much more easier if `v-select` has sorting prop by itself. It could be also considered to be true as default as well

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

You can use `no-filter` and `:search-input.sync` to filter and sort externally. 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
