### ISSUE TITLE
[Feature Request] Using gradient (previously on jumbotron, but now what?)

### ISSUE THREAD

**Issue by dtrillo** [vuetifyjs/vuetify#5664]
### Problem to solve
Now that jumbotron is being deprecated, how can I use gradient property, because it doesn't work iwith v-response neither v-img as background.

### Proposed solution
Create "something" that allows gradients as a background

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/images#example-gradients

If you don't need any of the other functionality from v-img or v-responsive you should just use a div with either a class or inline styles. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
