### ISSUE TITLE
[Feature Request] aria roles for VList / VListTile

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#5667]
### Problem to solve
VList/VListTile use `div`s instead of `ol/ul/li` so they are missing aria roles

### Proposed solution
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/List_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Listitem_role

**Comment by plweil** [comment]
If these are lists, why not just use the html elements with the appropriate native semantics instead of adding aria roles? 

>[First Rule of ARIA Use](https://www.w3.org/TR/using-aria/#rule1): If you can use a native HTML element [ HTML51 ] or attribute with the semantics and behavior you require already built in, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, then do so.
