### ISSUE TITLE
[Bug Report] v-btn @click.once fires twice

### ISSUE THREAD

**Issue by pbastowski** [vuetifyjs/vuetify#5675]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.13.6

### Steps to reproduce
- open the Dev console and click the green button once
- you will see "ONCE v-btn" printed twice in the console
- for contrast, click the native blue button
- you will see "ONCE button" printed exactly once

### Expected Behavior
Clicking the green button prints "ONCE v-btn" exactly one time and no more.

### Actual Behavior
you will see "ONCE v-btn" printed twice in the console

### Reproduction Link
<a href="https://codepen.io/pbastowski/pen/xQpdYQ?editors=1010" target="_blank">https://codepen.io/pbastowski/pen/xQpdYQ?editors=1010</a>

**Comment by pbastowski** [comment]
Thanks for the workaround. This is, however, still a bug with the synthetic event emitted by v-btn.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers

https://github.com/vuetifyjs/vuetify/blob/862d5936c440f8579663b0e2fbbf621e3718a576/packages/vuetify/src/mixins/routable.ts#L53-L56

`@click` gets overridden by line 55, but `@click.once` is `~click` so it gets duplicated.

**Comment by johnleider** [comment]
> https://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers
> 
> [vuetify/packages/vuetify/src/mixins/routable.ts](https://github.com/vuetifyjs/vuetify/blob/862d5936c440f8579663b0e2fbbf621e3718a576/packages/vuetify/src/mixins/routable.ts#L53-L56)
> 
> Lines 53 to 56 in [862d593](/vuetifyjs/vuetify/commit/862d5936c440f8579663b0e2fbbf621e3718a576)
> 
>  [this.to ? 'nativeOn' : 'on']: { 
>    ...this.$listeners, 
>    click: this.click 
>  } 
> `@click` gets overridden by line 55, but `@click.once` is `~click` so it gets duplicated.
> 
> @vuetifyjs/core-team I think we had a helper for this, anyone remember where it was?

Yea, https://github.com/vuetifyjs/vuetify/blob/feat/md2-btn/packages/vuetify/src/globals.d.ts#L82. Although the reproduction link does not reproduce the issue for me on W10 Chrome 71.

**Comment by KaelWD** [comment]
[bindObjectListeners](https://github.com/vuejs/vue/blob/0948d999f2fddf9f90991956493f976273c5da1f/src/core/instance/render-helpers/bind-object-listeners.js) doesn't do anything with modifiers, I thought we had a helper somewhere that strips the event modifier from the name. Confirmed fixed in 2.5.18 though.
