### ISSUE TITLE
[Bug Report] v-window transition makes my component resize

### ISSUE THREAD

**Issue by Minoflaz** [vuetifyjs/vuetify#5677]
### Versions and Environment
**Vuetify:** 1.2.4
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Use a v-window with cards inside (codepen)

### Expected Behavior
Normal transition when swiping from a window-item to an other

### Actual Behavior
Component inside the v-window resizes each time it changes from an item to an other

### Reproduction Link
<a href="https://codepen.io/anon/pen/Rqxjpo" target="_blank">https://codepen.io/anon/pen/Rqxjpo</a>

**Comment by johnleider** [comment]
You should move the container inside of the window item.

https://codepen.io/johnjleider/pen/exNOLw
