### ISSUE TITLE
[Feature Request] [Autocomplete] Add way to close dropdown other then click outside

### ISSUE THREAD

**Issue by zajca** [vuetifyjs/vuetify#5679]
### Problem to solve
When you open menu on autocomplete there is no way to close it other than click outside. This way user sometimes click on other active element and cause unwanted behavior.

### Proposed solution
There are more solutions one would be adding append/prepend item which would stick when scrolling. This would add more options to use.
Other would be optional backdrop on site like modal has if it is transparent it would prevent unwanted click, if it's with opacity it would add nice focus for used element.

**Comment by KaelWD** [comment]
You can also press `esc`, or click on the dropdown arrow again. The click outside problem is tracked in #5310
