### ISSUE TITLE
Create Webpack Vuetifyjs project with SASS but not Stylus

### ISSUE THREAD

**Issue by wnasirou** [vuetifyjs/vuetify#568]
When I execute this command : ``vue init vuetifyjs/webpack``, project is scaffolded with Stylus.

How to create a webpack  vuetifyjs project with SASS but not Stylus ?

Please help me.

Thank you.

**Comment by johnleider** [comment]
Please direct questions like this to the official [gitter](https://gitter.im/vuetifyjs/Lobby).

**Comment by AndrewBogdanovTSS** [comment]
@johnleider link to a gitter you provided is broken

**Comment by nekosaur** [comment]
Because we've switched to [discord](https://chat.vuetifyjs.com/).

**Comment by johnleider** [comment]
We no longer use gitter for support. You can access the new community at https://chat.vuetifyjs.com
