### ISSUE TITLE
[Bug Report] v-tab-item not properly resizing when content gets added

### ISSUE THREAD

**Issue by svengt** [vuetifyjs/vuetify#5683]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.14.1

### Steps to reproduce
* Switch to the second tab. 
* Click add other.

### Expected Behavior
Expected the tab to grow with its new content.

### Actual Behavior
Tab stays the same height. 

### Reproduction Link
<a href="https://codepen.io/svengt/pen/RqxOPj" target="_blank">https://codepen.io/svengt/pen/RqxOPj</a>

### Other comments
When you switch back and forth from tabs the height will be updated.

**Comment by svengt** [comment]
This bug first occurred in 1.3.9. This pen uses 1.3.8 https://codepen.io/svengt/pen/RqxmPv

**Comment by KaelWD** [comment]
The transition doesn't seem to be ending properly, it still has `v-enter-active v-enter-to` classes and the `onAfterEnter` hook never fires.

**Comment by svengt** [comment]
@KaelWD Shouldn't this be marked as a regression? It used to work in previous versions.

**Comment by sh7dm** [comment]
This problem occured after ceddbce commit
