### ISSUE TITLE
[Feature Request] Snackbar HTML content support

### ISSUE THREAD

**Issue by KarmaCop213** [vuetifyjs/vuetify#5686]
### Problem to solve
Can you add a way to use html content inside the snackbar instead of just plain text?

Even easy things like adding line breaks or bold text are impossible in the way the snackbar is implemented at the moment.

### Proposed solution
Create a boolean property to render the html content provided in the "text" property.

"text" property could change its name to "content" since its value is no longer just plain text.

**Comment by KaelWD** [comment]
?

It's a slot, you can put whatever you like in there.

**Comment by KarmaCop213** [comment]
You're right!

Please ignore this.
