### ISSUE TITLE
[Feature Request] Wish: Mix desktop and mobile elements on page

### ISSUE THREAD

**Issue by pashute** [vuetifyjs/vuetify#5688]
### Problem to solve
Enables making a mobile mockup or controller inside a desktop app page

### Proposed solution
A "mobile emulator container"  which can be set on desktop app to "emulate" a phone app on the desktop. 

Useful for making app builders, component builders, property setters, app problem reporting from desktop, and many more apps where the "mobile phone" emulator is shown in a div of its own.

**Comment by KaelWD** [comment]
Not feasible to do without CSS element queries, which don't seem to be coming any time soon.
