### ISSUE TITLE
default theme is dark [0.12]

### ISSUE THREAD

**Issue by billouboq** [vuetifyjs/vuetify#569]
When upgrading from vuetify 0.11 to 0.12 all my app went from light to dark without any change but the doc says :

> Light and Dark
> The default configuration is set to a light theme, but you're free to swap to a darker one by doing the following.

Is there a way to change back to light theme without using stylus?

Edit: anyway will use light on those components or add a css property it's not a big deal.

**Comment by mfferreira** [comment]
@billouboq Some of the components had hardcoded colors, and light/dark didn't mean the same thing across the framework. Those reason made us move some things around so things could make more sense.

For example, previously the `light` prop on some components would mean "apply the light theme colors". But applying `light` and seeing dark colors could be a bit confusing... It was to us...
Now, `light` just means "apply lighter colors" and the opposite for `dark`. So if you had `dark` set to get the lighter colors, your component will now have a darker tint.

As you said, the solution is to change the prop to `light`. Happy coding!
