### ISSUE TITLE
[Bug Report] VTreeView - Value not work when single select mode

### ISSUE THREAD

**Issue by AudricCh** [vuetifyjs/vuetify#5690]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Use a VTreeView without property "selectable" to have single selection mode
Set value property with a good value key

### Expected Behavior
Select the data we set on the value property

### Actual Behavior
This not work, nothing is selected

### Reproduction Link
<a href="https://codepen.io/anon/pen/JepYNg" target="_blank">https://codepen.io/anon/pen/JepYNg</a>

### Other comments
It's working when we set selectable. The value checkbox is selected.
But when it's not selectable, nothing is selected

**Comment by KaelWD** [comment]
`value` is for **selected** items (`selectable`), `active.sync` is for **activated** items (`activatable`). Slightly confusing, could probably do with clarification in the documentation.

**Comment by AudricCh** [comment]
Ok, that's working well with this ! 
I guess that's the name of the property is not really clear, "value" is pretty simple, but "active-sync" look like it's for asynchronous loading data, or something like that.

I close the issue, but the doc update seems to be the appropriate answer.

Thanks
