### ISSUE TITLE
[Feature Request] can i set a v-tabs-slider background color?

### ISSUE THREAD

**Issue by HobaiRiku** [vuetifyjs/vuetify#5693]
### Problem to solve
set a  background color for v-tabs-slider like this :  
![snipaste_2018-11-21_23-34-08](https://user-images.githubusercontent.com/26238803/48851726-baf9e380-ede6-11e8-91ae-31a4f42c95dd.png)

### Proposed solution
don't know now

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

https://codepen.io/anon/pen/vQdKPx
