### ISSUE TITLE
<v-dialog> overlay stays when navigating away

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#570]
First of all, congrats on v0.12 of Vuetify! Migrating from v0.11.1 to v0.12 went really smooth, except for the dialogs.

The issue is that I'm opening a dialog when transitioning to a new route. When transitioning away I close the modal again (`this.showModal = false`). But since v0.12, even though the dialog goes away, the overlay stays and so the application can't be used anymore.

To reproduce on JS Fiddle, http://jsfiddle.net/h4kpvk4v/14/:

1. Click 'Open dialog'
2. Click 'CLOSE'
3. Now you end up on the Home route with an overlay from the dialog's route.

**Comment by johnleider** [comment]
http://jsfiddle.net/9b4g4zjn/

You can manually call hideOverlay on the dialog by adding a ref.

**Comment by johnleider** [comment]
If you continue to have issues please let me know.

**Comment by maartendraijer** [comment]
@johnleider Although your solution works, it throws the following error: `Uncaught TypeError: this.$refs.dialog.hideOverlay is not a function`.

**Comment by johnleider** [comment]
It most certainly is if you are on 0.12.0

**Comment by maartendraijer** [comment]
@johnleider Your Fiddle (http://jsfiddle.net/9b4g4zjn/) runs on v0.12.1.

**Comment by johnleider** [comment]
That's my bad, it should be this.$refs.dialog.removeOverlay

**Comment by maartendraijer** [comment]
Ah, yeah, thanks!

**Comment by maartendraijer** [comment]
@johnleider Seems like this is broken with v0.13 again: http://jsfiddle.net/y0yfgv6y/
