### ISSUE TITLE
[Feature Request] Add VExpandTransition to Motion/Transitions page

### ISSUE THREAD

**Issue by guilhermemj** [vuetifyjs/vuetify#5704]
### Problem to solve
`v-expand-transition` is a really useful component as expansion panels can be overkiling most of the time. The lack of documentation about it made me use some not-so-pretty workaround methods until I found the component being used in `v-hover` examples.

I think the Motions/Transitions page should be home to all `v-type-transition` components. It could save us some time searching for nice already-implemented transitions.

### Proposed solution
Simply add `v-type-transition` to Motions/Transitions page API.

It could be documented in Expansion Panel page too as it's also a logic related place to look for it.

**Comment by MajesticPotatoe** [comment]
added to docs for next update.
https://github.com/vuetifyjs/vuetify/commit/9c5464b55a1b003bb6226a1b69c48c7919940a75

Thank you for your contribution 👍
