### ISSUE TITLE
[Bug Report] Combobox item-value doesn't work

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#5705]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.14.1

### Steps to reproduce
Select an option with combobox, select an option with autocomplete

### Expected Behavior
combobox returns value of the item property specified by item-value prop

### Actual Behavior
combobox always returns full object

### Reproduction Link
<a href="https://codepen.io/bviala/pen/PxbNXP" target="_blank">https://codepen.io/bviala/pen/PxbNXP</a>

**Comment by jacekkarczmarczyk** [comment]
See https://github.com/vuetifyjs/vuetify/issues/5358
