### ISSUE TITLE
[Feature Request] When v-treeview is active, expand background width to whole treeview width

### ISSUE THREAD

**Issue by sjquant** [vuetifyjs/vuetify#5708]
### Problem to solve
Actually, when you see vscode file tree view, background color width of hover and active is whole tree width, but in vuetify it justs covers after component, not whole treeview. I think it is really essential feature.

### Proposed solution
Sorry, I don't have any proposed solution. I tried to change css but failed.

**Comment by nekosaur** [comment]
This has to do with how we're offsetting child nodes and how the markup looks like. It is not something we are currently planning on changing.

Thank you for you interest in improving vuetify.
