### ISSUE TITLE
[Bug Report] v-treeview - open-all does not always work

### ISSUE THREAD

**Issue by andreapier** [vuetifyjs/vuetify#5711]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.16
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Create a dummy node having a string id that starts with a "0".
Add children to this node.
Nodes are not open even if open-all is set.

### Expected Behavior
All nodes are open

### Actual Behavior
Only nodes with an id that does not start with a "0" are open

### Reproduction Link
<a href="https://codepen.io/anon/pen/xQWgPB?editors=1010" target="_blank">https://codepen.io/anon/pen/xQWgPB?editors=1010</a>

**Comment by KaelWD** [comment]
@nekosaur Any particular reason this is being cast to a number? https://github.com/vuetifyjs/vuetify/commit/4ec3066d4452fa176b8022d32d2eb9ae046f0f47#diff-7598eb722bcad876fcb8b93592baeb1dR121

**Comment by nekosaur** [comment]
Not suuuure. I'm certain there was a thought there when I wrote it..
