### ISSUE TITLE
[Bug Report] v-select is still partially open after value selected in v-edit-dialog

### ISSUE THREAD

**Issue by graduenz** [vuetifyjs/vuetify#5712]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
1. Open CodePen's demonstration by [clicking here](https://codepen.io/graduenz/pen/KroajB)
2. Click on the left column on the table to open text dialog
3. Type a new name and press enter
4. It should have been worked correctly
5. Now it's time to see the bug
6. Click on the right column to change the food
7. Change it from Pizza to another option
8. Press Enter to confirm changes
9. See the dialog being closed, but the v-select options opens again
10. Click again in the option you choose before to confirm changes

### Expected Behavior
Choosing an option in v-select and pressing Enter should close both v-select and v-edit-dialog

### Actual Behavior
Choosing an option in v-select and pressing Enter is closing v-edit-dialog but reopening v-select

### Reproduction Link
<a href="https://codepen.io/graduenz/pen/KroajB" target="_blank">https://codepen.io/graduenz/pen/KroajB</a>

### Other comments
I believe it opened again from pressing Enter to confirm changes while v-select is focused, but pressing Enter isn't the only way to confirm changes in v-edit-modal?

**Comment by johnleider** [comment]
@jacekkarczmarczyk we need to come up with a solution for edit dialog in 2.0

**Comment by jacekkarczmarczyk** [comment]
Definitely, but is this bug related to `v-edit-dialog`? I'm pretty sure that it can happen also in v-menu or v-dialog, didn't check though

**Comment by johnleider** [comment]
This is resolved for v2.0
