### ISSUE TITLE
[Feature Request] support prop size for v-radio and v-checkbox

### ISSUE THREAD

**Issue by ly525** [vuetifyjs/vuetify#5715]
I'd like to make the v-radio smaller to adapt the screen size (change the font-size of the icon), but the ripple with it was not responsive.
I read the source code, but result makes me sad. So can you provide the prop that we can adjust the size of v-radio?

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VRadioGroup/VRadio.js#L69

the

**Comment by jongio** [comment]
Here's how I got this working: https://codepen.io/jongallant/pen/MLGPVR

**Comment by ly525** [comment]
@jongio Thanks for your demo, I have tried it. but I think that's not what I want. Because It doesn't show the relationship between the font size of the icon and the size of ripple.

thanks again!

**Comment by jongio** [comment]
Yeah. Def still need feature. That was just a stopgap.

**Comment by mehrunrasoli** [comment]
I'm wondering why the `hint` prop shouldn't be available for v-radio and other radio-group components!

I need it to show some help message for each radio button and seems already I should do that in a dirty way.

**Comment by keyboardSmasher** [comment]
Yes. I'd love to have a `<v-checkbox large></v-checkbox>`

**Comment by johnleider** [comment]
The team has decided that anything involving changing the size of input controls would be done so as part of the Density specification:

https://material.io/design/layout/applying-density.html#usage

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
