### ISSUE TITLE
[Bug Report] v-treeview - Error when adding and removing a child

### ISSUE THREAD

**Issue by andreapier** [vuetifyjs/vuetify#5719]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.16
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
1) Open node "Applications"
2) Add a new child by clicking the "Add to applications" button
3) Remove the node by clicking the "Remove from applications" button
4) Add a new child again
5) Check the console for the error

### Expected Behavior
A new node should be added

### Actual Behavior
The following error is thrown:
```
[Vue warn]: Error in created hook: "TypeError: Cannot set property 'vnode' of undefined"
found in
<VTreeviewNode>... (1 recursive calls)
       <VTreeview>
...
TypeError: Cannot set property 'vnode' of undefined
    at VueComponent.register
    at VueComponent.created
    at callHook
    at VueComponent.Vue._init
    at new VueComponent
    at createComponentInstanceForVnode
    at init
    at createComponent
    at createElm
    at addVnodes
```

### Reproduction Link
<a href="https://codepen.io/anon/pen/OavdWd?editors=1011" target="_blank">https://codepen.io/anon/pen/OavdWd?editors=1011</a>

### Comment
I found a similar closed issue #5543.  
Not sure if it is the same problem though.  
The issue was closed but not solved anyway, so I don't think it makes a difference.

**Comment by andreapier** [comment]
@nekosaur Do you need more info about this bug?  
I can reproduce it sistematically with the reproduction steps I provided.  
Let me know if you need more info.  
Thanks!

**Comment by jonataswalker** [comment]
Need this fix too.

**Comment by LavrovE** [comment]
same problem

**Comment by nnnazzzarrr** [comment]
Create a new component:
/components/override/treeviewOverridden.vue

`<script>
    // Override VTreeView Vuetify component.
    // solves "Cannot set property 'vnode' of undefined" error.
    // issue is in 'register' method.
    // this.nodes contains only parent items. But when method is invoked on children, the 'key' will be
    // the 'id' of the child, obviously, not present in this.nodes.
    // When node.item is child (item.parent has a value) we have to use 'parent' property to identify the 'key'.
  import VtreeView from 'vuetify/lib/components/VTreeview/VTreeview'
  // Utils
  import { getObjectValueByPath } from 'vuetify/lib/util/helpers.js';

  export default {
    extends: VtreeView,
    name: "treeviewOverridden",
    methods: {
      register: function register(node) {
        let itemKey = node.item.parent ? 'parent' : this.itemKey;
        let key = getObjectValueByPath(node.item, itemKey);
        this.nodes[key].vnode = node;
        this.updateVnodeState(key);
      }
    }
  }
</script>
`

then import this component to your page, like:

`import TreeViewOverriden from '~/components/override/treeviewOverridden';`

register it:

`...,
    components: {
      'tree-view-overridden': TreeViewOverriden
    }`

and use <tree-view-overridden></tree-view-overridden> instead  of <v-treeview></v-treeview>

**Comment by nekosaur** [comment]
What is this for? If there is a bug in treeview or the original bug has not been solved, please create a new issue with a reproduction.

**Comment by pbteja1998** [comment]
Anyone else facing the same problem, I solved this by adding `item-key` to the `treeview`. So, if you do not have `item-key` set as some unique value for each item, then add that.

**Comment by lyutian** [comment]
> Anyone else facing the same problem, I solved this by adding `item-key` to the `treeview`. So, if you do not have `item-key` set as some unique value for each item, then add that.

Adding `item-key` doesn't fix my situation. 😢 
Still get this error when add new to a **leaf node**, even the vuex store already updated and `item-key` set to unique `id`.
