### ISSUE TITLE
Incorrect border radius with horizontal cards

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#572]
### Steps to reproduce
Visit https://vuetifyjs.com/components/cards and have a look at example no. 5.

### Versions
Vuetify 0.12

### What is expected ?
The cards of example no. 5 should have a rounded bottom left and top right corner while everything inside the cards should not have rounded corners.

### What is actually happening ?
The bottom left and top right corners are not rounded, but the first column inside the card (the hotel room image and the white text on yellow background) has a rounded top right corner and the second column (white text on brown background and the Hertz image) has a rounded bottom left corner.

### Reproduction Link
https://vuetifyjs.com/components/cards

**Comment by johnleider** [comment]
I saw this as soon as we launched yesterday :(. WIll fix.
