### ISSUE TITLE
[Bug Report] Disabled icon button

### ISSUE THREAD

**Issue by ecattez** [vuetifyjs/vuetify#5720]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.14.1

### Steps to reproduce
Add a color to a disabled icon button.

### Expected Behavior
Expected the background to be grey.

### Actual Behavior
Background still be in the chosen color.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xQWvjZ" target="_blank">https://codepen.io/anon/pen/xQWvjZ</a>

**Comment by rkomiyama** [comment]
Couldn't this be avoided by simply omitting the `color` prop? I don't know if it makes sense to force the grey color when someone might want to make it a different color instead (e.g. paler color to denote the disabled status).

**Comment by KaelWD** [comment]
This is inconsistent with regular buttons, which go fully grey when disabled: https://codepen.io/anon/pen/JeZKQx?editors=1010
