### ISSUE TITLE
Password input prevent form submitting when press 'enter'

### ISSUE THREAD

**Issue by alirizaadiyahsi** [vuetifyjs/vuetify#5721]
**Only text type input :** When I press enter, page is refreshing. 

````html
<v-form ref="form">
    <v-text-field prepend-icon="person" name="userNameOrEmail" type="text"
        :label="$t('UserNameOrEmailAddress')" 
        v-model="loginInput.userNameOrEmail" 
        :rules="[requiredError]"></v-text-field>
</v-form>
````

**TO MAKE IT WORK:** I am adding `@submit.prevent="onSubmit"`

-------

**With password type input :** When I press enter, nothing fired.

````html
<v-form ref="form">
    <v-text-field prepend-icon="person" name="userNameOrEmail" type="text"
        :label="$t('UserNameOrEmailAddress')" 
        v-model="loginInput.userNameOrEmail" 
        :rules="[requiredError]"></v-text-field>
    <v-text-field prepend-icon="lock" name="password" type="password"
        :label="$t('Password')" 
        v-model="loginInput.password" 
        :rules="[requiredError]"></v-text-field>
</v-form>
````

**TO MAKE IT WORK:** I am adding `@keyup.native.enter="onSubmit"`

------

I expect to make them work with same the statement `@submit.prevent="onSubmit"`. But this does not work for form that contains password input and it is refreshing. Is this bug?

**Comment by jacekkarczmarczyk** [comment]
Replace v-text-field with native input and you'll get the same. This is how html works

**Comment by alirizaadiyahsi** [comment]
Thanks for quick replay. I understand pressing enter causes form submitting (whole page refreshing) if there is only one input in form. But I thought that a SPA framework component(vuetify) handle the form submitting (with page refreshing) by default in a SPA framework.

**Comment by alirizaadiyahsi** [comment]
Actually I mean "a component of SPA framework", not "SPA framework". It does not matter, you are still right. 

> could be used both in SPA and non-SPA sites

I thought wrong :)
