### ISSUE TITLE
[Feature request] to disable month click in v-date-picker

### ISSUE THREAD

**Issue by mandaputtra** [vuetifyjs/vuetify#5725]
# What request?
date picker month select. can be disabled
-  [image](https://ibb.co/jiueAV)

# why?

I found that v-date-picker month section cannot be disabled. Is there any way to disabled this? cause it will create unexpected behavior when set to 100% width. here you can try to click the month header
 till changed to month.

-  https://aslieenaak-cuzndfgckf.now.sh/ 

If someone find ways to disable this here the codepen https://codepen.io/_mandaputtra/pen/KrqexY

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/YRLooz
What we could do here is make only the text clickable instead of the whole area
