### ISSUE TITLE
[Feature Request] V-Autocomplete with callback

### ISSUE THREAD

**Issue by namsir** [vuetifyjs/vuetify#5727]
### Problem to solve
It would be awesome if you allow v-autocomplete menu-props to accepts a function. Now we can dynamically calculate the "nudge-top", "nudge-bottom", "nudge-left", and "nudge-right". I'm currently using vuetify in my wordpress project. Wordpress admin sidebar + admin top nav offsets the left and top values of the v-menu. Also, please allow datatables to accept "menu-props" because it uses v-menu in it.

### Proposed solution
<v-autocomplete id="ct-partsfinder-products"
                                            :menu-props="calculateMenuProps"   <------- a method from parent component.
                                            v-model="selectedProduct"
                                            :items="products"
                                            background-color="transparent"
                                            color="primary"
                                            item-text="text"
                                            label="Product"
                                            :rules="selectedProductRules"
                                            required
                                            
                            ></v-autocomplete>
                          

<v-data-table
                        :headers="headers"
                        :items="desserts"
                        :search="search"
                        :pagination.sync="pagination"
                        class="elevation-1"
                        :menu-props="calculateMenuProps()"
                ></v-data-table>

![untitled](https://user-images.githubusercontent.com/6132858/48973445-67b5aa00-f00d-11e8-8b97-dbc20caaffa9.png)

**Comment by jacekkarczmarczyk** [comment]
You can just pass the method result `:menu-props="calculateMenuProps()"` (still better to use computed prop instead of method call). I don't see any profits from supporting the method, but feel free to show the example when it would be helpful

**Comment by jacekkarczmarczyk** [comment]
Still I don't see how accepting function would help to solve it - resizing window won't automatically call it and update the position
And adding `menu-props` to `v-autocomplete` is a different thing, you should open a separate issue for this

**Comment by namsir** [comment]
a function will allow us to set the left, top values dynamically. Menu-props is being accepted by v-autocomplete but not in DataTable. The last screenshot shows the Results Per Page drop down shifted to the right.
