### ISSUE TITLE
[Bug Report] v-flex doesn't have display flex

### ISSUE THREAD

**Issue by atilkan** [vuetifyjs/vuetify#5729]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.0

### Steps to reproduce
None of the alignment props works on v-flex. 

### Expected Behavior
display:flex

### Actual Behavior
display:block

### Reproduction Link
<a href="https://codepen.io/atilkan/pen/vQjwqV?editors=1010" target="_blank">https://codepen.io/atilkan/pen/vQjwqV?editors=1010</a>

### Other comments
According to docs we can add alignment props to v-flex. It wont work if display flex not set.
@jacekkarczmarczyk Is this ok? Does it pass your high standards?

**Comment by KaelWD** [comment]
Last time you asked this I pointed you to #2884, and the documentation has been updated since then. `v-layout` is `display: flex`

**Comment by atilkan** [comment]
@KaelWD Documentation is not updated. Or still wrong. v-flex has align-items prop which does nothing because v-flex is not flex.
