### ISSUE TITLE
[Feature Request] Data Table should have flat option

### ISSUE THREAD

**Issue by exyzzy** [vuetifyjs/vuetify#5731]
### Problem to solve
The last data table example, CRUD Actions, illustrates the issue: https://vuetifyjs.com/en/components/data-tables 
Namely that if you add toolbar and want it to blend seamlessly you will add flat to the toolbar. However then the toolbar renders as flat (no shadow) and the rest of the data table is shadowed - looks off. 

### Proposed solution
Presumably to fix you would make both the toolbar and data table flat, and then wrap both in a card. Which requires a flat option on the data table.

**Comment by jacekkarczmarczyk** [comment]
Data table has no shadow by default
https://codepen.io/anon/pen/PxaWog?&editors=101
