### ISSUE TITLE
[Feature Request] add horizontal support to scrolling features (v-scroll, goTo)

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5732]
### Problem to solve
Vuetify scrolling tools: `v-scroll` directive and Scrolling motion `$vuetify.goTo()` does not work with horizontal elements

### Proposed solution
providing `v-horizontal-scroll` directive, add horizontal functionality to `$vuetify.goTo()` element, enhance mouse scroll movement over horizontal elements

codepen: https://codepen.io/anon/pen/jQKVOX

**Comment by gileneusz** [comment]
@AlexVFornazieri I don't have enought experience to code it myself, maybe there are some raw js solutions for this

**Comment by PascalBe07** [comment]
Are there any news about if and when we might get a solution for the problem?

Or does anyone have a clean custom solution?
