### ISSUE TITLE
[Feature Request] Don't clear Autocomplete on blur

### ISSUE THREAD

**Issue by nhynes** [vuetifyjs/vuetify#5733]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.62
**OS:** Mac OS 10.14.1

### Steps to reproduce
1. focus the autocomplete
2. type some text
3. click anywhere else
4. observe that the autocomplete does not retain its text

### Expected Behavior
The autocomplete should retain its text. This is a standard design pattern. For instance
* amazon.com
* youtube.com
* google.com
* github.com
* duckduckgo.com
* the browser's own address bar
* spotlight

### Actual Behavior
The autocomplete clears on blur.

### Reproduction Link
<a href="https://codepen.io/anon/pen/qQKYRz" target="_blank">https://codepen.io/anon/pen/qQKYRz</a>

### Other comments
(the example codepen is just https://vuetifyjs.com/en/components/autocompletes#example-api)

**Comment by jacekkarczmarczyk** [comment]
Use v-combobox

**Comment by nhynes** [comment]
Thanks!
