### ISSUE TITLE
[Bug Report] Speed-dial animation only works for 7 buttons

### ISSUE THREAD

**Issue by ranarn** [vuetifyjs/vuetify#5735]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Add more than 7 buttons to v-speed-dial

### Expected Behavior
Animation works on every button regardless how many they are

### Actual Behavior
Animation runs only on the first 7 buttons

### Reproduction Link
<a href="https://codepen.io/anon/pen/mQKoRv" target="_blank">https://codepen.io/anon/pen/mQKoRv</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/components/_speed-dial.styl#L82
