### ISSUE TITLE
[Bug Report] VTextArea outline color in error state

### ISSUE THREAD

**Issue by CameronMcNair** [vuetifyjs/vuetify#5738]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 7

### Steps to reproduce
See codepen

### Expected Behavior
Textarea's border should be red when it fails validation and is not active

### Actual Behavior
Textarea's border is not red when it fails validation and is not active

### Reproduction Link
<a href="https://codepen.io/anon/pen/PyjmXW?&editors=101" target="_blank">https://codepen.io/anon/pen/PyjmXW?&editors=101</a>

### Other comments
This is a duplicate of issue https://github.com/vuetifyjs/vuetify/issues/5274
There was a pr for this - https://github.com/vuetifyjs/vuetify/pull/5447 - but it looks like it may have been overwritten or the fix didn't work in the first place

**Comment by jacekkarczmarczyk** [comment]
broken by https://github.com/vuetifyjs/vuetify/commit/a438ccde106ba198bee1c4f46e9288adee8b419a
