### ISSUE TITLE
<v-list-tile> nuxt without router

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#574]
### What is expected ?
`<v-list-tile nuxt href="/settings">` make router link.

### What is actually happening ?
Make a default link (page will reload). I must specify router attribute
`<v-list-tile router nuxt href="/settings">`

Is the presence of the attribute "nuxt" not implying that the link is "router"?

**Comment by johnleider** [comment]
When using just you should use router as well. Is that your question?

**Comment by cawa-93** [comment]
@johnleider Sorry, but I do not understand. I want to use
```html
<v-list-tile nuxt href="/settings">
```
instead of
```html
<v-list-tile router nuxt href="/settings">
```
, as I  doing now to create `<nuxt-link>`

**Comment by johnleider** [comment]
Nuxt is in addition to router. Your second markup should work fine. Is it an issue for you to use both? That's how it was designed.

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby).
