### ISSUE TITLE
[Bug Report] Tooltips are displayed transparently after being quickly shown then hidden

### ISSUE THREAD

**Issue by BenoitZugmeyer** [vuetifyjs/vuetify#5740]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Firefox 63.0, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
* Add a `v-tooltip` controled with a `:value` or `v-model` attribute
* Quickly (I guess before the next animation frame, 16ms) show and hide it, ex:

```js
{
  data: () => ({
    showTooltip: false
  }),
  
  methods: {
    quicklyShowAndHide () {
      this.showTooltip = true
      setTimeout(() => {
        this.showTooltip = false
      }, 0)
    }
  }
}
```

### Expected Behavior
The tooltip has `opacity: 0` and `display: none` (after a potential transition, if needed)

### Actual Behavior
The tooltip has `opacity: 0` and no `display` style, so it is still displayed (but transparently)

### Reproduction Link
<a href="https://codepen.io/anon/pen/zMJGyv?editors=1010" target="_blank">https://codepen.io/anon/pen/zMJGyv?editors=1010</a>

### Other comments
This probably works too with other components, like `v-menu`

**Comment by thomanau** [comment]
Just wanted to mention that i also just encountered this problem in my App. 
Vuetify: 1.3.11
Vue: 2.5.17
OS: Windows 10 - 64Bit
Browsers: Chrome (70.0.3538.110), Microsoft Edge (42.17134.1.0)

**Comment by jacekkarczmarczyk** [comment]
Can't reproduce in 1.5.X
