### ISSUE TITLE
[Bug Report] Firefox Icons are not centered

### ISSUE THREAD

**Issue by kiankji** [vuetifyjs/vuetify#5741]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.7
**Browsers:** Firefox 62.0
**OS:** Windows 7

### Steps to reproduce
Download the latest version of Firefox

### Expected Behavior
Icon should be in the center of the of the button 

### Actual Behavior
All MD icons are horizontinal centered but not vertical 

### Reproduction Link
<a href="https://codepen.io/miklever/pen/PeOeLZ" target="_blank">https://codepen.io/miklever/pen/PeOeLZ</a>

### Other comments
just for firefox 
with chrome it works fine 

![firefoxvschrome](https://user-images.githubusercontent.com/22913023/49087449-4e07a300-f257-11e8-9474-63339375cd8c.PNG)

**Comment by DRoet** [comment]
Are you loading your icon-font after your vuetify css dist by any chance?

it's suppose to be:
```
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'vuetify/dist/vuetify.min.css'
```
