### ISSUE TITLE
[Bug Report] VDataTable expand row classList 'null'

### ISSUE THREAD

**Issue by scp-nm** [vuetifyjs/vuetify#5742]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
Viewing the Codepen link will show how the existing template taken directly from Vuetify docs site (https://vuetifyjs.com/en/components/data-tables#example-expand) when clicking the row to expand it an error is thrown in the console.
`"[Vue warn]: Error in nextTick: 'TypeError: Cannot read property 'classList' of null'"`

### Expected Behavior
The row should expand and collapse without errors

### Actual Behavior
The first row clicked expands (with an error in the console), and clicking the same row doesn't collapse it. Any subsequent row clicks no longer expand.

### Reproduction Link
<a href="https://codepen.io/scp-nm/pen/bQxwJR" target="_blank">https://codepen.io/scp-nm/pen/bQxwJR</a>

### Other comments
This used to work previously, unfortunately I can't track down which version it stopped working in.

**Comment by jacekkarczmarczyk** [comment]
I guess this https://github.com/vuetifyjs/vuetify/commit/cb605ac9d73f8f585e0a23591b4d54241950101e
