### ISSUE TITLE
[Feature Request] Is there any way to customize the text color dynamically?

### ISSUE THREAD

**Issue by Lanfei** [vuetifyjs/vuetify#5749]
### Problem to solve
As the [document](https://vuetifyjs.com/en/style/theme) shows, we can customize the theme color by `Vue.use` function or by modifying the `$vuetify.theme` object, but I can't find any way to customize the text color and make the text color match the theme color dynamically.

### Proposed solution
Maybe we can provide a option like:

```js
import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify, {
  textTheme: {
    primary: 'rgba(0, 0, 0, .87)',
    secondary: 'rgba(0, 0, 0, .54)',
    disabled: 'rgba(0, 0, 0, .38)',
    link: colors.blue.darken2,
    link-hover: colors.grey.darken3
  }
})
```

**Comment by KaelWD** [comment]
From that page:
> Under the hood, Vuetify will generate css classes based upon these values that will be accessible in the DOM. These classes will follow the same markup as other helper classes, `primary` or `secondary--text` for example. 

Links use the primary colour by default (`.primary--text`).
