### ISSUE TITLE
[Feature Request] Bottom sheets should support the same properties as Dialog

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#5750]
### Problem to solve
It would be really useful if the `v-bottom-sheet` could support the following properties from `v-dialog`:

```
attach
content-class
dark
fullscreen
scrollable
```
I was recently trying to make the bottom sheet fullscreen (100% height) in mobile view and had to write a hacky solution with global CSS because `fullscreen` prop is missing, and also I could not add my custom class to the detached element because `content-class` is missing.

### Proposed solution
The `v-bottom-sheet` already shares functionality from `v-dialog` so it makes sense to support the same properties.

**Comment by johnleider** [comment]
Closed by #6786
