### ISSUE TITLE
[Bug Report] Ugly single-line text-field with prefix and outline style

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5752]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Linux x86_64

### Steps to reproduce
1. Create text-field with outline style
2. Enable single-line mode
3. Add prefix

### Expected Behavior
Prefix should be on one line with value

### Actual Behavior
Prefix is lower than value

### Reproduction Link
<a href="https://codepen.io/anon/pen/wQYWdQ" target="_blank">https://codepen.io/anon/pen/wQYWdQ</a>

**Comment by Djaler** [comment]
Same thing with box style

**Comment by bulkan** [comment]
Not sure if this is related but having a `prefix` with `outline` and no value causes the prefix to overlap with the label.

https://codepen.io/anon/pen/JxVQLO

**Comment by MatthewAry** [comment]
Any news on this? This issue's been open awhile now and the positioning problem is glaring.

**Comment by MajesticPotatoe** [comment]
PR maintainer became inactive. Probably wont be address until 2.0 (we haven't touched inputs yet as they are kinda a beast and we like to save the fun ones for last)

**Comment by jacekkarczmarczyk** [comment]
Seems fixed in 2.2.3 https://codepen.io/jkarczm/pen/QWwrOzj
