### ISSUE TITLE
[Feature Request] add support for fixed input labels

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5753]
### Problem to solve
Somethimes I don't need the label to go down to the input field, becoming a placeholder

### Proposed solution
New prop, for example `fixed-label`, that should force label to stay at top

**Comment by jacekkarczmarczyk** [comment]
Not sure if we want this, but it's easy to achieve with placeholder: https://codepen.io/anon/pen/qQGYoB

**Comment by Djaler** [comment]
Yeah, this can be a temporary workaround

**Comment by Joebayld** [comment]
I have the same request - and now it seems that the `placeholder=" "` trick no longer works. Any other workarounds?

**Comment by KaelWD** [comment]
Resolved by #13001, use `persistent-placeholder` (no placeholder actually required)

**Comment by tihomir-kit** [comment]
I don't think this really fixed it. The original thread was about the label, not the placeholder. `persistent-placeholder` was implemented, but that doesn't pin the label to always stay on top?

**Comment by johnleider** [comment]
> I don't think this really fixed it. The original thread was about the label, not the placeholder. `persistent-placeholder` was implemented, but that doesn't pin the label to always stay on top? There's even a `persistent-hint` but no `persistent-label`.

this is resolved for v3 https://github.com/vuetifyjs/vuetify/commit/7c361e637c9e76505c772d4aa31876b6a9a01084
