### ISSUE TITLE
[Bug Report] Inconsistent checkbox state in dropdown menu of v-select

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#5754]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Linux x86_64

### Steps to reproduce
The codepen shows a dropdown made using `v-select` with `multiple` prop. Now, I want to limit the number of items the user can select (In the codepen the limit is 3).
1) Open the dropdown and select any 3 items from the list. The items show up as selected
2) Now select the 4th item by clicking on the checkbox and see the behaviour

### Expected Behavior
It is expected that when the `changeHandler` is called and the item is popped out of the array, the checkbox will be un-selected and the item won't be added to the selected list

### Actual Behavior
The item is not added to the list,but, the checkbox remains selected which is incorrect behaviour

### Reproduction Link
<a href="https://codepen.io/anon/pen/PxyWze?&editors=101" target="_blank">https://codepen.io/anon/pen/PxyWze?&editors=101</a>

**Comment by nekosaur** [comment]
Use `$nextTick`. https://codepen.io/anon/pen/OrZJZZ?&editors=101
