### ISSUE TITLE
[Bug Report] v-img does not work in v-flex with certain v-layout props

### ISSUE THREAD

**Issue by ekreutzer** [vuetifyjs/vuetify#5757]
### Versions and Environment
**Vuetify:** 1.3.10
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Have v-layout align-center justify-center column, with flex's inside, and a v-img inside the flex. As can be seen in the codepen, the v-img only works if there is text or another component/element contained within the flex. The red border is around the flex in which the lone v-img should be appearing.

### Expected Behavior
The images should always work, obviously. It should not matter whether there are other elements in the component or flex.

### Actual Behavior
The image only appears if there is another component within the flex.

### Reproduction Link
<a href="https://codepen.io/tkted/live/BGqJEK" target="_blank">https://codepen.io/tkted/live/BGqJEK</a>

**Comment by KaelWD** [comment]
v-img has no actual content, therefore relies on the parent to provide width. I can fix this pretty easily, but I'm not sure if it should be the new default, with the current behaviour behind a prop; or keep the current default and add a prop for this. 

Current behaviour, image width determined by parent: 
![image](https://user-images.githubusercontent.com/16421948/49217717-7263ab00-f422-11e8-8217-4d941233e3ed.png)

New behaviour, image expands to its native size, limited by available space:
![image](https://user-images.githubusercontent.com/16421948/49217750-8ad3c580-f422-11e8-9cd7-1f986c2d7f1f.png)
