### ISSUE TITLE
[Feature Request] Persistent VSpeedDial children (i.e. v-show instead of v-if behavior)

### ISSUE THREAD

**Issue by simshaun** [vuetifyjs/vuetify#5760]
### Problem to solve
**The goal:**  
Allow VSpeedDial children to emit events that can be handled by the VSpeedDial parent even when the VSpeedDial is closed/not active.

**The problem:**  
When VSpeedDial is set to `open-on-hover` and a VSpeedDial child is clicked, VSpeedDial closes itself and destroys the child components (v-if behavior). If a child component contains a callback that emits an event on the child component, it's possible the child component no longer exists by the time the callback is called, so the emitted event can't be handled by the VSpeedDial parent.

**Real life scenario:**  
Given the following component hierarchy:
```
CommentForm (binds to UploadButton input event)
    |--- VSpeedDial (open-on-hover)
        |--- UploadButton (listens for HTML5 input onchange to emit an input event)
            |--- HTML5 file input (triggers "onchange" after files are chosen)
```

- UploadButton is basically a VBtn covered by a transparent HTML5 input that, when clicked, opens the OS's file chooser.
- UploadButton listens for the HTML5 file input's `change` event and emits an `input` event when files are chosen.

The problem is that when UploadButton is clicked, VSpeedDial closes itself -- causing the UploadButton instance to be destroyed. So when a user chooses files, the UploadButton instance has already been destroyed and the input event (emitted by the HTML5 input's onchange callback) can't be handled by the parent (CommentForm).

If VSpeedDial had some sort of "persistent" behavior then its children would always exist even when VSpeedDial is closed/not active.

### Proposed solution
Implement a new prop on VSpeedDial that causes children to always exist (v-show behavior) even when the speed dial is closed.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
