### ISSUE TITLE
[Bug Report] V-slider produces error when switching the data model

### ISSUE THREAD

**Issue by vitor-kato** [vuetifyjs/vuetify#5761]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
Using v-treeview to swap the currently selected object, and change its data with the v-slider.

Example:
1. Select any value for the min and max inputs
2. Go to the second object in the treeview
3. Select any value for the min and max inputs
4. Go back to any previously  selected object
5. Error!!

### Expected Behavior
Preserve the data, and get no errors.

### Actual Behavior
The object loses partial data from the range array, and becomes a Number.

### Reproduction Link
<a href="https://codepen.io/vitor-kato/pen/XyxONx" target="_blank">https://codepen.io/vitor-kato/pen/XyxONx</a>

**Comment by jacekkarczmarczyk** [comment]
Please first simplify your codepen by removing unrelevant code and fix the console errors

**Comment by vitor-kato** [comment]
I don't feel there is too much irrelevant code on the codepen, after all most is from the vuetify examples, and the console errors are caused by the component itself when the error occurs, so what you mean?

**Comment by jacekkarczmarczyk** [comment]
I see now about the errors, not sure what's causing them atm, but still the pen could be shortened, there's no need for card title, v-flexes, text-fields, v-tree-view etc

**Comment by jacekkarczmarczyk** [comment]
That's how the reproduction could be boiled down:

https://codepen.io/anon/pen/MzZbXQ?editors=1010

And that's how to fix it:

https://codepen.io/anon/pen/dQwOry?editors=1010
