### ISSUE TITLE
[Bug Report] Vertical centering not working in v-img when using max-height

### ISSUE THREAD

**Issue by WOo0W** [vuetifyjs/vuetify#5764]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Add some v-img under v-flex and set the max-height.

### Expected Behavior
v-img using max-height should be centered as same as which using aspect-ratio.

### Actual Behavior
Vertical centering not working in v-img when using max-height.

### Reproduction Link
<a href="https://codepen.io/anon/pen/Pxxorx" target="_blank">https://codepen.io/WOo0W/pen/Pxxorx</a>

**Comment by KaelWD** [comment]
`max-height` limits the size of the element:
![image](https://user-images.githubusercontent.com/16421948/49201146-d458ec00-f3f3-11e8-90ce-701a91925d84.png)
`aspect-ratio` does too, but `contain` just stops the image from being cut off, it doesn't affect the height at all:
![image](https://user-images.githubusercontent.com/16421948/49201170-f2bee780-f3f3-11e8-91f2-24f9fe799b0f.png)

You need to use a v-layout to center it: https://codepen.io/anon/pen/jQQEGq?editors=1010
