### ISSUE TITLE
[Bug Report] TextField mask - caret should skip separator

### ISSUE THREAD

**Issue by Spetnik** [vuetifyjs/vuetify#5765]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
1. Create a TextInput with a mask that includes separators (e.g. `credit-card`)
2. Enter characters up until the first separator (e.g. `1234`)

### Expected Behavior
The TextInput should display `1234-` with the caret *_after_* the hyphen

### Actual Behavior
The TextInput displays `1234-` with the caret *_before_* the hyphen

### Reproduction Link
<a href="https://codepen.io/AJSpetner/pen/rQQLbe" target="_blank">https://codepen.io/AJSpetner/pen/rQQLbe</a>

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
