### ISSUE TITLE
Add a "precision" property for numeric inputs

### ISSUE THREAD

**Issue by StratusBase** [vuetifyjs/vuetify#577]
**Feature Request:**

It would be awesome if support for a "precision" value was added to numeric inputs. That way I could always display numeric values with decimal places.

**Comment by johnleider** [comment]
Could you provide an example of how you would use this feature? Proposed markup and functionality. Thank you.

**Comment by GianPaoloBuffo** [comment]
I was also hoping a feature like this could be added.

Something like: `<v-text-field precision="2"></v-text-field>`

This will basically act as a mask, preventing values with more than 2 decimal places from being entered.

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Controlling_step_size

**Comment by GianPaoloBuffo** [comment]
@KaelWD Although this controls the step when using the up/down arrows, it unfortunately doesn't prevent a user from manually entering a value greater than `step` decimal places

**Comment by KaelWD** [comment]
#2138
