### ISSUE TITLE
[Feature Request] Charts Support

### ISSUE THREAD

**Issue by hassanarteaga** [vuetifyjs/vuetify#5771]
### Problem to solve
Create charts as vuetify component 

### Proposed solution
Create a wrapper for well known js chart libraries like chartjs, highcharts , etc in order to create nice chart with vuetify style and syntaxes.   There are many wrappers around there but if vuetify.js implement it, we all will be happy and sure about tech support.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
