### ISSUE TITLE
[Feature Request] Add open and close methods for v-dialog

### ISSUE THREAD

**Issue by sh7dm** [vuetifyjs/vuetify#5772]
### Problem to solve
The v-dialog can be opened with a variable, but I think it would be useful to add the `open` and` close` methods to them.

### Proposed solution
Add the `open` and `close` methods. I can open the PR, but I want to know the opinions of other people.

**Comment by MajesticPotatoe** [comment]
Seems pointless as an open/close method would be no different then setting v-model true/false

**Comment by KaelWD** [comment]
Agreed, "I think it would be useful" doesn't count as a problem.
