### ISSUE TITLE
Light and disabled v-btn is invisible

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#578]
### Versions
0.12

### What is expected ?
The disabled button without loading looks just like the disabled button with the loading

### What is actually happening ?
The disabled button without loading and with loading visually differ. If the button does not have a loading, it is almost invisible.

### Reproduction Link
https://jsfiddle.net/fgbknLsh/

**Comment by johnleider** [comment]
Light should only go on dark backgrounds. You are using a light button on a light background disabled, it's not going to show.

Loader is an exception because it was a PITA. There is room for improvement, but it was intentional.

**Comment by DivinoAG** [comment]
I would like to request this to be reconsidered. The `light` or `dark` props are the only standard way to set the font color on buttons (besides manually inserting CSS for every button variation, at which stage I have to ask what is even the point of using the components), and some background colors require white text to improve legibility.

The framework shouldn't be limiting implementation of components to one or another background color when the original material design specifications allow for this use case. If you check the [official material design components](https://material-components-web.appspot.com/button.html) you can see how they were implemented without preventing the use of light text buttons on light backgrounds.

**Comment by mfferreira** [comment]
@DivinoAG I'm not entirely sure how your comment is related to the this issue, but I like your comment and I would love if you could open a new issue so it doesn't get lost.
