### ISSUE TITLE
[Feature Request] [Local Support] Data Table footer (rows per page, etc.)

### ISSUE THREAD

**Issue by Abo-Hani** [vuetifyjs/vuetify#5786]
### Problem to solve
I would like to request a feature to translate various strings, which are located in the footer of the table, e.g. rows per page, 2 of 10, etc.) 

### Proposed solution
Add prop to translate it, e.g.: :local_shown_records="{current} من {total}"

Original is: 5 of 20

I'm currently doing this in mounted(): 

```
let RecordsString = $('.v-datatable__actions__select').html()
        RecordsString = RecordsString.replace('Rows per page', 'عناصر بكل صفحة')
        $('.v-datatable__actions__select').html(RecordsString)
```

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/framework/internationalization#create-translation

You can also create a PR with your locale file https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/locale
