### ISSUE TITLE
[Feature Request] data table  need to disable hover effect. 

### ISSUE THREAD

**Issue by sanhar** [vuetifyjs/vuetify#5787]
### Problem to solve
Data table is much useful on all most of projects . 
but sometimes we need to disable hover effect and even on specific columns and rows. 

### Proposed solution
adding api for switching hover effect on columns and rows

**Comment by diezfx** [comment]
Ist there any workaround as long as this is not implemented?

**Comment by boarnoah** [comment]
Setting the :hover background colour for the row to the same colour as it's usual background is a workaround.

Unfortunately there isn't a good way to style rows without using the item.slot and re-implementing most of the data table row yourself.  You could try with a deep selector in CSS as well.

**Comment by ptvagner** [comment]
i vote for this too

**Comment by stepanho** [comment]
As alternative, possible to use CSS to <tr> of DataTable:
`pointer-events: none;`

_Be notice, that It disables all JS and CSS animation for <tr> element._

**Comment by acro5piano** [comment]
As @mowolf mentioned here, this works well.

```css
.v-data-table__wrapper > table > tbody > tr:hover {
  background: inherit !important;
}
```

https://github.com/vuetifyjs/vuetify/issues/10297#issuecomment-1012303891
