### ISSUE TITLE
[Bug Report] Wrapping v-stepper-step and v-stepper-content in a tag causes improper rendering of step in a vertical stepper

### ISSUE THREAD

**Issue by wallslide** [vuetifyjs/vuetify#5790]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Wrap a v-stepper-step and v-stepper-content pair in a div and use that div as a child of a v-stepper tag instead of placing the pair as direct children of a v-stepper tag. 

### Expected Behavior
The step will be rendered normally

### Actual Behavior
There is no vertical line connecting the step that was wrapped with unwrapped steps

### Reproduction Link
<a href="https://codepen.io/wallslide/pen/NEJpXE" target="_blank">https://codepen.io/wallslide/pen/NEJpXE</a>

### Other comments
I'm not sure if the fix mentioned in this issue https://github.com/vuetifyjs/vuetify/issues/3330#issuecomment-428349733 was supposed handle this issue or not.

![image](https://user-images.githubusercontent.com/917069/49356737-062dc380-f710-11e8-9e58-bbe7e8153ba0.png)

**Comment by sindrepm** [comment]
I ran into the same issue and it happens because the CSS selector that adds the vertical line targets every `.v-stepper__content` element except the last one. When the step is wrapped in a div it will always be the last.
```
.theme--light.v-stepper--vertical .v-stepper__content:not(:last-child) {
    border-left: 1px solid rgba(0,0,0,0.12);
}
```
A workaround is to add the line yourself e.g. with a class on the `div` like this:

```
<template>
  <div class="step-border">
    <v-stepper-step step="1">
      <div class="subheading">Step 1</div>
    </v-stepper-step>
    <v-stepper-content step="2">Step 1...</v-stepper-content>
  </div>
</template>
```
```
<style>
.step-border > .v-stepper__content {
  border-left: 1px solid rgba(0, 0, 0, 0.12);
}
</style>
```
I am not sure if there is a better fix.

**Comment by mathieutu** [comment]
I event not have the circle with number on my side: 
<img width="614" alt="screen shot 2018-12-11 at 16 04 42" src="https://user-images.githubusercontent.com/11351322/49809166-7ff02d80-fd5e-11e8-8a0c-e8cfe329a8b8.png">
Some ideas ?

**Comment by wallslide** [comment]
Updated codepen to be compatible with 2.x release

**Comment by danieleades** [comment]
i have this exact problem.

suggested solution also adds a line *after* the last element

**Comment by Radiergummi** [comment]
@danieleades the solution from @sindrepm is just missing the same `:not(:last-child)` selector the original Vuetify style uses:
```
.step-border:not(:last-child) > .v-stepper__content {
  border-left: 1px solid rgba(0, 0, 0, 0.12);
}
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
