### ISSUE TITLE
[Bug Report] v-breadcrumb item slot render non valid HTML

### ISSUE THREAD

**Issue by kl3sk** [vuetifyjs/vuetify#5791]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Windows 10

### Steps to reproduce
Look at source

### Expected Behavior
all element should be in `<li></li>`

### Actual Behavior
`<a>` tags are between `<li>`

```html
<ul data-v-4c433b90="" class="v-breadcrumbs theme--light">
	<a data-v-4c433b90="" href="breadcrumbs_dashboard" class="">DASHBOARD</a>
	<li class="v-breadcrumbs__divider">/</li>
	<a data-v-4c433b90="" href="breadcrumbs_link_1" class="">LINK 1</a>
	<li class="v-breadcrumbs__divider">/</li><a data-v-4c433b90="" href="breadcrumbs_link_2" class="disabled">LINK 2</a>
</ul>
```

### Reproduction Link
<a href="https://codepen.io/kl3sk/pen/xQBpZb?&editable=true&editors=111" target="_blank">https://codepen.io/kl3sk/pen/xQBpZb?&editable=true&editors=111</a>

### Other comments
This may appears only in `slot="item"`

EDIT:
This shoud be like [this](https://codepen.io/kl3sk/pen/XyGZbj?&editable=true&editors=111) or component should add `<li>`

**Comment by johnleider** [comment]
That is why we have `v-breadcrumbs-item`. If you provide a slot, it's expected that you pass in this component. It's **routable** so it can be treated just like an anchor tag.
