### ISSUE TITLE
[Bug Report] v-hover not work, when hovered inner item

### ISSUE THREAD

**Issue by grishnyakov** [vuetifyjs/vuetify#5792]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.2
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 7

### Steps to reproduce
click on combobox
hover item in combo

### Expected Behavior
card should be hovered (shadow-on), when inner item hovered

### Actual Behavior
card lost shadow (shadow-off),  when inner item hovered

### Reproduction Link
<a href="https://codepen.io/grishnyakov/pen/vQPjmm" target="_blank">https://codepen.io/grishnyakov/pen/vQPjmm</a>

### Other comments
sorry for my english

**Comment by KaelWD** [comment]
The menu isn't technically an "inner item" unless you use the `attach` prop, have a look at what actually end up in the DOM.

https://codepen.io/anon/pen/MzxXOj?editors=1010

**Comment by grishnyakov** [comment]
thanks
