### ISSUE TITLE
[Feature Request] Prefix the css classes container, layout and flex with v-

### ISSUE THREAD

**Issue by taamrooz** [vuetifyjs/vuetify#5793]
### Problem to solve
When using the VContainer component, Vuetify automatically generates
```html
<div class="container">
```
I would propose to change the `container` class to `v-container` and do the same for layout and flex.
It can solve css conflicts when a generated css file is used inside another website which already uses a container/layout/flex class. (I couldn't manage to find a similar issue, excuse me if there is one.)

### Proposed solution
Prefixing the css classes in `_grid.styl` and in the files it gets applied, if that is all, I am no expert on either TypeScript or Stylus. I am currently not aware of any other css classes that should be prefixed. While the issue template requires me to create a minimal reproduction to illustrate the issue, I don't believe it would be too useful in this use case.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/1561#issuecomment-397815783

**Comment by taamrooz** [comment]
It seems I'm blind, thanks @jacekkarczmarczyk
