### ISSUE TITLE
[Bug Report] v-expansion-panel does not respect values when rendered server-side

### ISSUE THREAD

**Issue by mrkswrnr** [vuetifyjs/vuetify#5795]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
1. Create a nuxt.js project
2. Use code from example "Expand" (https://vuetifyjs.com/en/components/expansion-panels#examples)

### Expected Behavior
Expect panel 2 and 3 to be expanded.

### Actual Behavior
All panels are collapsed. Panels 2 and 3 show collapse-icon, but content is not shown. Panels need to be collapsed and expanded to reveal contents.

### Reproduction Link
<a href="https://github.com/mrkswrnr/vuetify-expansion-panels" target="_blank">https://github.com/mrkswrnr/vuetify-expansion-panels</a>

### Other comments
This happens only when the component is rendered server-side. This worked when using deprecated value for each v-expansion-panel-content

**Comment by mrkswrnr** [comment]
My current fix is to reset value and trigger expand via updateFromValue:
```javascript
const panels = this.$refs["panels"];
if (panels) {
    panels.updateFromValue([]);
    this.$nextTick(() => {
        panels.updateFromValue(this.expanded);
    });
}
```

**Comment by lautr** [comment]
Another workaround is to set the model on mounted, unfortunately this will animate the expand on page load and force a reflow.

**Comment by artentica** [comment]
@lautr does not work on 1.5.9 unfortunatly :/

**Comment by KaelWD** [comment]
This seems to be resolved in vuetify 2

<details>
<summary>layouts/default.vue</summary>

```vue
<template>
  <v-app>
    <v-container>
      <div class="text-center mb-5">{{ panel }}</div>
      <v-expansion-panels
        v-model="panel"
        multiple
      >
        <v-expansion-panel
          v-for="(item, i) in 5"
          :key="i"
        >
          <v-expansion-panel-header>Item</v-expansion-panel-header>
          <v-expansion-panel-content>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </v-expansion-panel-content>
        </v-expansion-panel>
      </v-expansion-panels>
    </v-container>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      panel: [0, 2]
    })
  }
</script>
```
</details>

**Comment by Paulo-Teodoro** [comment]
That issue has been resolved in Vuetify 2. You simply need to add the "eager" prop to the "v-expansion-panel-content" component, which will force the content to be rendered.

Here are the documentation links for both versions:

Version 2: https://v2.vuetifyjs.com/en/api/v-expansion-panel-content/#props-eager
Version 3: https://vuetifyjs.com/en/api/v-expansion-panel-text/#props-eager
