### ISSUE TITLE
v-text-input trying to load v-model without fallback

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#58]
Doing something like this will fail.
Data:

    foo: {}
    
Template:

    v-text-input( label="Error" v-model="foo.bar.willfail" )

Error:
TypeError: Cannot read property 'willfail' of undefined

The render should fail gracefully and have a fallback to an empty string or null in case the property doesn't exist, like Vue does for `<input>`

**Comment by johnleider** [comment]
After looking into this. The regular input from vue will only gracefully fallback at the first property, so ```foo.bar``` will pass to the input as undefined with no value. This is true for both ```v-text-input``` and a regular input with vue. Adding the 3rd level of property will cause an error on both scenarios. This seems like intended behavior and is inline with the normal reaction from javascript on attempting to access a property of an undefined variable.

I'll leave this open for now. Could you provide an example of the graceful fallback on a regular input with vue that maybe I'm missing?

**Comment by mfferreira** [comment]
Maybe it was changed in Vue 2, but I have a dashboard with several `<input>` in the same page, and none spit out errors.

	<div class="row">
		<div class="input-field col s12">
			<input id="selectedResource.logentriesToken" type="text" v-model="selectedResource.serviceTokens.logentries"></input>
			<label for="selectedResource.logentriesToken">Logentries Token</label>
		</div>
	</div>

That project is not using any build system either, it's just importing JS from cdn, in case that matters.

**Comment by johnleider** [comment]
As far as I can tell, this does not work like that in Vue 2. There shouldn't be an instance where you have a model binded that could be undefined on two levels.

**Comment by mfferreira** [comment]
That's true. For some reason this has been working on my dash with Vue 1. I'll move these `v-model` to use computed properties.
