### ISSUE TITLE
[Feature Request] WIP: French translations

### ISSUE THREAD

**Issue by Deraw-** [vuetifyjs/vuetify#5806]
### Problem to solve
The lack of translations for French language.

### Proposed solution
The solution is translating! I'm starting this on my fork.

**Comment by MajesticPotatoe** [comment]
No need to create a FR for this. You can submit a PR with your stuff when you are ready.
Also may want to take a look at #347 though not sure if outdated (courtesy of jacek)

**Comment by MajesticPotatoe** [comment]
AH! didn't realize that was there. (we only recently started shifting some stuff around in repos and what, and docs are going through a complete overhaul. Discord is probably the best point of contact for contributing. also, There's a more up to date contribution guide at [https://next.vuetifyjs.com/en/getting-started/contributing](next.vuetifyjs.com) - its a part of the docs rework alpha.
