### ISSUE TITLE
[Bug Report] Touch handling in Vuetify not consistent to MD

### ISSUE THREAD

**Issue by johuhype** [vuetifyjs/vuetify#5808]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
1. Activate mobile mode in chrome device toolbar. 
2. Please see the video of issue 2406. (https://github.com/vuetifyjs/vuetify/issues/2406)
3. Open my example and try the same touch wiggle effect on a v-list-tile.

When you touch an element and move the finger/mouse and release it while still on the element, click events are not getting fired.

E.g. if a user touches a v-toolbar-side-icon or v-list-tile and wiggles a bit, the click event is not triggered.

### Expected Behavior
If the user is still on the the element he first touched when releasing his touch, the click event should fire.

### Actual Behavior
As soon as the user wiggles a bit after his touch begins, the click event is not fired. This leads to lots of clicks not getting processed (as users tend to wiggle the more distance is between them and their touch display) and creates the impression of a unresponsive app.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gQyNpJ" target="_blank">https://codepen.io/anon/pen/gQyNpJ</a>

**Comment by KaelWD** [comment]
That is just a quirk with the browser, we don't do anything special with touch events: https://codepen.io/anon/pen/ZmNzRW?editors=1010
