### ISSUE TITLE
[Feature Request] Expand prop for v-list-group

### ISSUE THREAD

**Issue by rkomiyama** [vuetifyjs/vuetify#5809]
### Problem to solve
Allows multiple v-list-groups to remain open while toggling a v-list-group.

### Proposed solution
There seems to be a callback function called toggle() that, when clicking on a v-list-group, toggles the value prop for the other v-list-groups. If we add the expand prop to v-list-group, it would act just like it would in v-expansion-panel.

**Comment by KaelWD** [comment]
Already a thing: https://codepen.io/anon/pen/JeqPmr?editors=1010

**Comment by rkomiyama** [comment]
I'll be working on this since my team needs this functionality.

**Comment by mitar** [comment]
This should really be documented somewhat better.

**Comment by Sjoerd82** [comment]
The example given by KaelWD gives an "Uncaught ReferenceError: Vue is not defined at pen.js:-29". I would also like to see how this could be accomplished. I can't find it in the documentation.

**Comment by nicolo-paganin** [comment]
> This should really be documented somewhat better.

Yes I found it after 20 minutes reading this issue. It has to be better documented

**Comment by carweb99** [comment]
I been google a day for this and first when i found that expansion panel has the multiple property and googling with that i found this. Thank and WHY is this "expand" property it not documented !

**Comment by Tofandel** [comment]
This doesn't seem to work anymore

**Comment by stephane303** [comment]
This is 2022, still not documented properly, wasted 2 hours to use it !

**Comment by mitar** [comment]
Maybe another issue should be opened for this to be documented better?

**Comment by phatdangg** [comment]
`expand` prop to `v-list` doesn't work anymore.

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
