### ISSUE TITLE
0.12 data-tables do not display full rows-per-page selection list

### ISSUE THREAD

**Issue by firepick1** [vuetifyjs/vuetify#581]
### Steps to reproduce
See Vuetify documents for v-data-table https://vuetifyjs.com/components/data-tables
Go to #2 Selectable Rows
Click on pages per row
Only "5" shows fully -- all other options are clipped

### Versions

Vuetify 0.12.0

### What is expected ?

See all rows-per-page options

### What is actually happening ?

Options seem to be clipped by bottom of table. Maybe a z-index bug?

### Reproduction Link

https://vuetifyjs.com/components/data-tables

**Comment by johnleider** [comment]
I started a branch to help fix this since it is a little more detailed.

**Comment by firepick1** [comment]
Cool. You may also discover that clients cannot set the initial rows-per-page, which is hardwired to 5. 
If you want I can file another issue to fix in your new branch or just use this comment.

**Comment by johnleider** [comment]
You should definitely be able to set the initial rows-per-page, paging @nekosaur

**Comment by nekosaur** [comment]
You can set initial rows-per-page by using the `pagination` prop.

```
<v-data-table :pagination.sync="pagination"></v-data-table>
...
data () {
  return {
    pagination: {
      rowsPerPage: 10
    }
}
```

**Comment by forresthopkinsa** [comment]
@nekosaur Where is the documentation for this functionality? I couldn't find it.

**Comment by nekosaur** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/issues/503
