### ISSUE TITLE
[Bug Report] v-data-table slot-scope selected destructuring problem

### ISSUE THREAD

**Issue by gcvs** [vuetifyjs/vuetify#5811]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.13.6

### Steps to reproduce
Visit https://codepen.io/garyuk/pen/VVOLPM

Toggle the checkbox selection, the reactive selection list should update, but it doesn't.

### Expected Behavior
Visit https://codepen.io/garyuk/pen/zMQGoq

Toggle the checkbox selection the reactive selection list does update.

### Actual Behavior
I naively expected the destructured slot-options="{ item, selected }" syntax to allow me to use the "selected" field in the v-checkbox v-model.  But it doesn't work.  The equivalent use of slot-options="props" and v-model="props.selected" works as expected.

### Reproduction Link
<a href="https://codepen.io/garyuk/pen/VVOLPM" target="_blank">https://codepen.io/garyuk/pen/VVOLPM</a>

**Comment by KaelWD** [comment]
Not a bug, that's how JavaScript works.

**Comment by gcvs** [comment]
Let me clarify:

Javascript destructuring works like this:

```
function print({ item, selected }) {
  // both item and selected are available in this context
  console.log(item, selected);
}

var props = { item: 'a', selected: 'b' }
print(props);

// output: a b
// NOT: a undefined
```

The slot-options destructuring syntax does not reproduce this behaviour:

if I use
`slot-options="props"`
then _props_ is available in context, and I can refer to _props.item_ and _props.selected_.
However, if I use 
`slot-options="{ item, selected }"`
then _item_ **IS** available in context but _selected_ is **NOT** available in context. (the bug)

**Comment by KaelWD** [comment]
1. It's `slot-scope`, not `slot-options`
2. `slot-scope` is a vue thing, so even if this was a bug it has nothing to do with vuetify
3. `slot-scope="{ item, selected }"` with v-model is like doing this:
```js
const props = { item: 'a', selected: 'b' }
let { item, selected } = props
selected = 'c'
// props is still { item: 'a', selected: 'b' }, selected was redefined
console.log(props, { item, selected })
```
