### ISSUE TITLE
[Bug Report] v-menu + sub menu not opening on hover if disabled has been toggled

### ISSUE THREAD

**Issue by Avatar45com** [vuetifyjs/vuetify#5813]
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Linux x86_64

### Steps to reproduce
1. click Main
2. Hover over Test2
3. Change Active to any value except zero.
4. click Main
5. Hover over Test2
6. Change Active to zero (0).
7. click Main
8. Hover over Test2
9. Change Active to any value except zero.
10. click Main
11. Hover over Test2

### Expected Behavior
On step 2 no sub menu should appear.
On step 5 sub menu appears.
On step 8 no sub menu should appear
On step 11 sub menu appears.

### Actual Behavior
On step 2 no sub menu should appear.
On step 5 sub menu appears.
On step 8 no sub menu should appear
On step 11 sub menu does not appear.

### Reproduction Link
<a href="https://codepen.io/Avatar45com/pen/Pxgrrz" target="_blank">https://codepen.io/Avatar45com/pen/Pxgrrz</a>

**Comment by Avatar45com** [comment]
the starting value is null, then in the text field fill in any number or text which will update the computed value. then when you get to the next step that you are entering a value enter the number 0. Then the next entry step can be anything.

**Comment by Avatar45com** [comment]
enter 1 in the text field, open the menu, click on the Test2. then close the menu and enter 0 in the text field. open the menu then click on the Test2. then close the menu and enter 1 in the text field. open the menu and click on Test2. the sub menu should not open at that point.

I don't have any screen capture software at the moment.

**Comment by Avatar45com** [comment]
[Kazam_screencast_00000.mp4.zip](https://github.com/vuetifyjs/vuetify/files/2649368/Kazam_screencast_00000.mp4.zip)
Got a video, you might not be able to tell but I am clicking the menu item when I hover over it.

**Comment by Avatar45com** [comment]
Is this issue dead?

**Comment by johnleider** [comment]
No, it's pending a team member review.
