### ISSUE TITLE
[Bug Report] v-treeview there is a bug in selected-value when id like  "1016943313682833408"

### ISSUE THREAD

**Issue by murfey-sea** [vuetifyjs/vuetify#5814]
Versions and Environment
Vuetify: 1.3.12
Vue: 3.2.1
Browsers: Chrome 70.0.3538.110
OS: Linux x86_64

Expected Behavior
Toggle the checkbox selection, selected-value must be "1016943313682833408" not 1016943313682833400

Reproduction Link
https://codepen.io/murfey-sea/pen/bmxvvL

**Comment by jacekkarczmarczyk** [comment]
It's javascript
![image](https://user-images.githubusercontent.com/15625235/49488651-1cf02980-f87a-11e8-8c2f-15e216126dc2.png)

**Comment by KaelWD** [comment]
Duplicate of #5711, it's only a problem because the ids are being cast to numbers.
