### ISSUE TITLE
[Bug Report] Hover prop is not working

### ISSUE THREAD

**Issue by rromanv** [vuetifyjs/vuetify#5815]
### Versions and Environment
**Vuetify:** 1.4.0-alpha.0
**Last working version:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Firefox 64.0
**OS:** Mac OS 10.14

### Steps to reproduce
Add hover prop to Card

### Expected Behavior
Show elevation when hover the element

### Actual Behavior
Is not showing the elevation

### Reproduction Link
<a href="https://codesandbox.io/s/m303pzoqr8" target="_blank">https://codesandbox.io/s/m303pzoqr8</a>

**Comment by marchofreason** [comment]
You're supposed to use the slot-scope hover here? 
```
    <v-card
      slot-scope="{ hover }"
      :class="`elevation-${hover ? 12 : 2}`"
      class="mx-auto"
      width="344"
    </v-card
```
