### ISSUE TITLE
v-navigation-drawer__border BUG

### ISSUE THREAD

**Issue by mano233** [vuetifyjs/vuetify#5818]
When I create v-navigation-drawer, specify its left attribute and then make its width equal to a multiple of 5, <v-navigation-drawer__border> is hidden???

![image](https://user-images.githubusercontent.com/29190675/49516953-dcbe9480-f8d5-11e8-8c28-2cb45f5d77ea.png)
![image](https://user-images.githubusercontent.com/29190675/49517005-07105200-f8d6-11e8-893e-7d59507f6a11.png)

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/49517098-6a5aae00-f8ef-11e8-89b3-66eb7e0e96ad.png)
