### ISSUE TITLE
Navigation Drawer Vuetify 0.12 Webpack

### ISSUE THREAD

**Issue by staffordjh** [vuetifyjs/vuetify#582]
Hi John, thank you again for your work on this.

I have have a question. I was looking for better examples under the documentation of the navigation drawer component. Specifically, I was looking for an example of how to open and close a persistant navigation drawer. 

Also, my navigation drawer seems to be overlaying ontop of my content, and not pushing the content over. I was hoping to only make this dependent on my click of the button on the toolbar. 

Thanks.

John

**Comment by johnleider** [comment]
Can you post the relevant code please? The application structure one of the very opinionated pieces of this framework and ordering is important.

**Comment by staffordjh** [comment]
Hi John, I am not sharing an opinion of what I think needs to change. I am trying to achieve the navigation drawer that you have here: https://vuetifyjs.com/vuetify/quick-start and throughout the rest of the demo, where it pushes the content over when it is open, and when it closes, the content move to the left where the navigation drawer was when it was open.

The documentation here: https://vuetifyjs.com/components/navigation-drawers has no examples of how to create a navigation drawer like that. I have been adding and removing all the configurations of navigation-drawer component with no luck so far (absolute, permanent, persistant, etc.) .

**Comment by johnleider** [comment]
https://vuetifyjs.com/layout/pre-defined

I should probably have a link from navigation-drawers.

**Comment by staffordjh** [comment]
yep, I missed that. Thanks John!

**Comment by staffordjh** [comment]
Last thing. 

I was wanting to keep some of my landing pages less "material-like" and not use the pre-defined dom structure at the root level of my application. 

For the pages that have a more admin template look, keeping everything (navigation drawer, toolbar, main, etc.) at the same dom level within the admin template page itself is not a problem, correct?

**Comment by johnleider** [comment]
navigation-drawer should always be first, other orders are not as important.

**Comment by staffordjh** [comment]
Cool. Thanks for your prompt help John. Great work!
