### ISSUE TITLE
[Bug Report] Sloted Vuetify components don't work properly with v-tooltip library

### ISSUE THREAD

**Issue by royprigat** [vuetifyjs/vuetify#5821]
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.2
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Have the v-popover component with a Vuetify component as a sloted component such as v-checkbox or v-range-slider

### Expected Behavior
Normal functionality of the Vuetify components inside the popover

### Actual Behavior
Vuetify components have a delay when closing the v-popover, and they don't work properly.

### Reproduction Link
<a href="https://codesandbox.io/s/lpm863vq3m" target="_blank">https://codesandbox.io/s/lpm863vq3m</a>

**Comment by KaelWD** [comment]
This is the same as https://github.com/vuetifyjs/vuetify/issues/5539#issuecomment-436881821, that library uses `visibility: hidden` which is then inherited by the slider's transition.

**Comment by royprigat** [comment]
I specifically need the v-range-slider component... But overriding its style doesn't seem like the right approach, because in the future I might need other Vuetify components

**Comment by royprigat** [comment]
If only the menu component included an arrow that points to the activator component...

**Comment by KaelWD** [comment]
We can't support every other UI library, you'll have to either use our menu component or figure out a workaround on your own.
