### ISSUE TITLE
[Feature Request] Documentation update for supporting IE11

### ISSUE THREAD

**Issue by Aymkdn** [vuetifyjs/vuetify#5825]
### Problem to solve
Contratry to what https://vuetifyjs.com/en/getting-started/quick-start#ie11-support says, vue-cli-3 doesn't automatically bring IE11 compatibility for us (at least if we use à-la-carte without the vuetify plugin)

### Proposed solution
As described in https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/55, when using the à-la-carte, and if we don't use `vue add vuetify`, the user will have to manually add [`transpileDependencies` parameter](https://cli.vuejs.org/config/#transpiledependencies) in `vue.config.js` : 

```
module.exports = {
  transpileDependencies:[/node_modules[/\\]vuetify[/\\]/]
}
```

It would be nice to have this information somewhere in the documentation and should avoid issues like https://github.com/vuetifyjs/vuetify/issues/4997 (*Symbol is not defined*).

Thanks

**Comment by MajesticPotatoe** [comment]
Dev docs have been updated. 
Thank you for your contribution 👍

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/a12f97e392ba15202e2ad6f214fd6e7f0ca4d6c8
