### ISSUE TITLE
[Feature Request] v-data-table, allow grouping of first column rows

### ISSUE THREAD

**Issue by wouterfovel** [vuetifyjs/vuetify#5829]
### Problem to solve
We would like something like https://github.com/vuetifyjs/vuetify/pull/4966
Give the user the possibility to only expand rows for a certain first column value ...

### Proposed solution
Could first column grouping be added to v-data-table ? Or is there a solution you know of we can use ?

**Comment by wouterfovel** [comment]
Is in fact same as [Feature Request] Table group rows by header #3180

Any news ?

**Comment by nekosaur** [comment]
Duplicate of #3180 

Please follow that issue for any updates
