### ISSUE TITLE
Overlay Color Helpers for Backgrounds

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuetifyjs/vuetify#583]
![image](https://cloud.githubusercontent.com/assets/25447231/26327245/3170e200-3f71-11e7-85b9-9f67e1d3bdbf.png)

adding overlays using the context color or any color pallete

Example
.overlay-25 = rgba(0,0,0,.25)

**Comment by johnleider** [comment]
I know that I originally told you to post this, however. With the growing size of the package, it seems like an  unnecessary expense. Because of that, I don't have the time to dedicate to it.
