### ISSUE TITLE
[Bug Report] v-combobox :menu-props="{openOnClick: false} does not work

### ISSUE THREAD

**Issue by dph01** [vuetifyjs/vuetify#5830]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.13.6

### Steps to reproduce
click into the Search input field

### Expected Behavior
The dropdown menu should not open.

### Actual Behavior
The menu does open.

### Reproduction Link
<a href="https://codepen.io/damianhelme/pen/zMXJvb" target="_blank">https://codepen.io/damianhelme/pen/zMXJvb</a>

### Other comments
Discussed on this thread ... https://stackoverflow.com/questions/53610974/vuetify-combobox-open-dropdown-on-icon-click. Traxo suggested it might be a bug.

I suspect that none of the values set through :menu-props work. I've tried a few different values but none seem to make a difference. I'm new to Vuetify and from the documentation I'm not sure exactly what the different :menu-props= settings are meant to be doing, so hard to know if it's working OK.

**Comment by KaelWD** [comment]
> I suspect that none of the values set through :menu-props work

They do, v-select just controls the menu manually instead of using the activator slot, so openOnClick won't have any effect. 

> I'm not sure exactly what the different settings are meant to be doing

https://vuetifyjs.com/en/components/menus#api

**Comment by johnleider** [comment]
I'm going to close this as a won't fix. The controls were never designed to support that and even if we added this in, it would take away from work on v3.

This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
