### ISSUE TITLE
[Feature Request] Support for Material Theming

### ISSUE THREAD

**Issue by therealmarv** [vuetifyjs/vuetify#5836]
### Problem to solve
Google's updated material design guidelines support since I/O 2018 the so called "Material Theming" which supports more in deep customization of e.g. button shapes and/or fonts to make customization look less like Google's own material design.

Links:
https://material.io/design/material-theming/
https://youtu.be/3VUMl_l-_fI

Is it possible to make this in more deep customization already with vuetify and should vuetify support Material Theming more?!

### Proposed solution
Support Google's Material Theme editor or offer equivalent features either by own tools or with specific docs on how to do it. Not all UIs should look 100% like Google's own Material UI.

**Comment by ibrahimBeladi** [comment]
[As per the disclimar in Vuetify v1.1.0](https://github.com/vuetifyjs/vuetify/releases/tag/v1.1.0):
> Google updated the Material Design spec to version 2.0 mid way through v1.1's beta. Because of this, there will be styles that don't exactly match the new spec. We will be starting the framework upgrade to MD2 directly after this release. For more information on Material Design 2, navigate [here](https://material.io/design/).

Going fully MD2-complaint will require a major if not full rewrite, which will proabably will be on Vuetify v2 at the latest.

**Comment by johnleider** [comment]
This feature was added in v2.2.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
