### ISSUE TITLE
[Feature Request] Add overlay prop to v-speed-dial

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#5837]
### Problem to solve
This allow the match the MD2 specs without conflict with MD1 specs or other use cases.
Example: in a list where you can click on the list items, if that list have a fab as a speed dial, when you could close the speed dial by clicking on the overflow. This should avoid a wrong click on the list item.

### Proposed solution
A `overlay` property on a speed dial displays an overlay when the speed dial is opened.
`overlay` should be `false` by default.
When `true`, the overlay click should close the speed dial.

**Comment by johnleider** [comment]
This is a requirement of the v-feature-discovery component and will naturally happen in v3. There are currently no plans to implement this in v2.x.
