### ISSUE TITLE
[Bug Report] Long swipe on the navigation drawer opens the second navigation drawer

### ISSUE THREAD

**Issue by Groxan** [vuetifyjs/vuetify#5838]
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
1. Go to https://vuetifyjs.com/ru/examples/layouts/complex
2. Switch to mobile mode (320px width)
3. Look at this:
![gif](https://drive.google.com/uc?export=download&id=1MaXrwJLlBuQcQqrr_lgauDA5lXHvMYX1)

### Expected Behavior
After any swipe, active navigation drawer should be closed. That's it.

### Actual Behavior
Swipe on the navigation drawer from the edge of screen opens the second navigation drawer

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/KQrPKJ" target="_blank">https://codepen.io/johnjleider/pen/KQrPKJ</a>

**Comment by johnleider** [comment]
This is definitely something I'd like to resolve, but the methods I've tried so far have been unsuccessful. In light of that, I'm going to have to drop this from v2.0 release. Thank you for your patience.

**Comment by Groxan** [comment]
That's sad... Anyway I really appreciate your work and will look forward to any updates. Keep up the great work!

**Comment by johnleider** [comment]
I was never able to figure this out and for v3 we are handling this differently anyways (directive).

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KemikalGeneral** [comment]
> I was never able to figure this out and for v3 we are handling this differently anyways (directive).
> 
> If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

So, is there a solution for this at all?
