### ISSUE TITLE
[Bug Report] Bug in switches and checkboxes

### ISSUE THREAD

**Issue by AnwarElbo** [vuetifyjs/vuetify#5839]
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Set a value that cant be changed by v-model or use :value.
The value of switches or checkboxes isn't equal to the styling/played animation

### Expected Behavior
That it doesnt animate nor change color, I for example have a use case where I trigger the @change event on a v-switch where the value is a computed property and the value of the computed property depends on the outcome of the executed function in the @change event. Now the value is false but the switch is on which doesn't make any sense to me.

### Actual Behavior
Looks true, but the data false 

### Reproduction Link
<a href="https://codepen.io/AnwarElbo/pen/Xyvxgw" target="_blank">https://codepen.io/AnwarElbo/pen/Xyvxgw</a>

**Comment by KaelWD** [comment]
v-model is controlled by `input-value` for those components, not `value`

**Comment by AnwarElbo** [comment]
@KaelWD https://codepen.io/AnwarElbo/pen/Xyvxgw
Still same result, it still turns on and the value is still false.

**Comment by AnwarElbo** [comment]
@jacekkarczmarczyk last thing before I reach out to the discord. That is true, therefore it shouldn't update the value and it also shouldn't play the animation because the value stays false. Now it is possible to turn it on but the value stays false which is in my opinion a bug.

**Comment by jacekkarczmarczyk** [comment]
This behaviour is in line with native inputs behaviour: https://codepen.io/anon/pen/Bvaxqa
