### ISSUE TITLE
Overlay covers everything with Dialog

### ISSUE THREAD

**Issue by brouwno** [vuetifyjs/vuetify#584]
Hi John,

Thank you so much for your work on Vuetify, really appreciate it!
Yesterday I updated to v.0.12.0. After the update I had to change some code to update everything according to the changes. There is only one thing I cannot seem to fix:

When i use a model, on opening, everything is covered in the overlay. In the previous version the part that pops up was above the overlay. 

At first I thought I had some css somewhere that causes this behaviour, but it also occurs in a blank layout with only the Modal example copy-pasted from the documentation (https://vuetifyjs.com/components/dialogs). Here is a Codepen Example:

https://codepen.io/brouwno/pen/BRGZWv

The Modal on your Documentation website works fine. But when I use the modal, even it is the exact same as your given example the described example occurs. In the previous version it worked fine.

Hope you can help!

### Versions

Vue: 2.3.3
Vuetify: 0.12.0
Chrome: 58.0.3029.110
Safari: 10.1 

### What is expected ?
The background is covered with the overlay. The Modal (dialog) is above the overlay.
<img width="448" alt="screen shot 2017-05-22 at 22 53 03" src="https://cloud.githubusercontent.com/assets/18467164/26327976/966bc560-3f41-11e7-8af2-21a4637f2023.png">

### What is actually happening ?
Everything is beneath the overlay, including the Modal.
<img width="335" alt="screen shot 2017-05-22 at 22 53 30" src="https://cloud.githubusercontent.com/assets/18467164/26327993/9fcd18fc-3f41-11e7-9f4a-80ef58f02daa.png">

### Reproduction Link
Codepen Link: https://vuetifyjs.com/components/dialogs

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/mmaXdy

Every vuetify application must be wrapped in a ```v-app``` tag.
