### ISSUE TITLE
[Feature Request] Speed up scrolling of big data lists (for example: VSelect) with dynamic data loading

### ISSUE THREAD

**Issue by toshiroakio** [vuetifyjs/vuetify#5846]
### Problem to solve
When scrolling lists (for example, VSelect) with a big data, this action is very slow. Positioning on the current element is not performed or is very slow. (menuProps.auto loads the entire list at once, resulting in a very slow loading of the big data list and working with it)

### Proposed solution
I suggest that you never draw the whole list, but always use a slice of the list. I suggest not to use menu Props.auto in VSelect and inheritor, and always manually position the list on the current item.

**my solution** (into VSelect):
1. add prop `virtualItemHeight` (Or maybe calculate it somehow)
2. add computed `scrollHeight` = `computedItems.length * virtualItemHeight` (To set the full size of the scrollable area immediately when creating a VList)
3. add computed `pageSize` = `30 or computedItems.length` if length < 30 (30 is const)
4. add var `firstItemIndex` to data which will be set depending on the position of the scrollable area
5. correct computed `virtualizedItems` = `computedItems.slice(firstItem, lastItem)` (`lastItem` - calculate `(firstItem + pageSize) or computedItems.length`)
6. add var `scrollSelectionTop` to data. To track changes (watch) in the position of the scrollable area
7. remove `lastItem` vars on `data` (this calculate in virtualizedItems)
8. correct `onScroll` method: remove calculate `lastItem` and add `scrollSelectionTop = content.scrollTop`
9. add watch 
```

scrollSelectionTop (val, oldVal) {
      if (val !== oldVal) {
        const scrollDirection = val > oldVal
        const firstOffset = this.virtualItemHeight * this.firstItemIndex
        const needChange = scrollDirection
          ? val - firstOffset > (this.virtualItemHeight * this.pageSize * 0.33)
          : val - firstOffset < (this.virtualItemHeight * this.pageSize * 0.33)
        if (needChange) { // (scrollDirection ? 1 : -1) *
          let firstItemIndexValue = (val / this.virtualItemHeight - (scrollDirection
            ? this.pageSize * 0.15
            : this.pageSize * 0.66
          )) >> 0
          firstItemIndexValue = firstItemIndexValue > 0 ? firstItemIndexValue : 0
          if (this.firstItemIndex !== firstItemIndexValue) {
            this.firstItemIndex = firstItemIndexValue
          }
        }
      }
    }

```
for calculate `firstItemIndex`  depending on the current position of the scrollable area and the scroll direction.
10. when a menu opening event occurs, need set the correct value for `firstItemIndex` and `content.scrollTop` depending on the currently selected item

**and**

**my solution** (into VSelectList):
1. add props `firstItemIndex`, `itemHeight`, `scrollHeight`
2. correct `render` function: 
  2.1. in `VList` render add `style.height  = scrollHeight`
  2.2. into `children` calculate block add `itemIndex` calculating and transfer this value in `genTile` function
3. correct `genTile` function:
  3.1. add param `itemIndex`
  3.2. calculate `translateYValue` = `firstItemIndex * itemHeight + itemIndex * itemHeight`
  3.3. add `style` block  in `tile`:
```
style: {
  position: 'absolute',
  height: `${this.itemHeight}px`,
  transform: `translateY(${translateYValue}px)`,
  transition: 'none 0s ease 0s',
  width: '100%'
}
```
this works very quickly with big data.

I think my code is not clean enough, please rework it in accordance with the rules of your framework. Consider my some implementations a bit 'crutches'. You may want to handle not inside the `Select` and inside `VList` what is inside `VList` was held this treatment. I don't know this framework that well. Dear developers, what do you think about this?
Dynamic list loading while scrolling is really fast!

**for test it**: https://codepen.io/toshiroakio/pen/yGBMwP
**code**: https://github.com/toshiroakio/vuetify  (branch: feat/v-select-mod-load-vis-on-scroll-and-set-cur-pos)

this real close: #5563

**Comment by johnleider** [comment]
This is something that we intend to implement using our `v-virtual-scroller` component. It was introduced very late into the game though and proved to be more difficult than expected to integrate into existing features. Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
