### ISSUE TITLE
datatables selection of rowsPerPage not fully visible

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#585]
Currently the rowsPerPage selection on datatables is not fully visible. It happens on the current doc in every example, here a screenshot:
<img width="429" alt="screen shot 2017-05-22 at 22 46 25" src="https://cloud.githubusercontent.com/assets/489221/26327802/f8efc1ec-3f40-11e7-975e-b094d1511d2d.png">

**Comment by ayataprabir** [comment]
![screenshot 21](https://user-images.githubusercontent.com/20454189/43894277-41ca964c-9bef-11e8-9721-4a47e86a9b9d.png)

Can you guys reopen this issue and open the menu like this....

**Comment by jacekkarczmarczyk** [comment]
Please create a new issue using [issue creator](https://issues.vuetifyjs.com/) and provide a minimal reproduction
