### ISSUE TITLE
[Bug Report] activeClass shows all children as active when parent node clicked on the TreeView

### ISSUE THREAD

**Issue by rwuttke** [vuetifyjs/vuetify#5854]
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.19
**Browsers:** Chrome 71.0.3578.80
**OS:** Windows 10

### Steps to reproduce
When the codepen is rendered, open all three nodes.

Click on the middle node.

### Expected Behavior
The first and last icon will be red and the second icon will be orange.

Only the second account name will have the colour of the text change to the class as associated via the **active-class** property, in this case __primary--text__, as this is the only active **TreeViewNode**.

### Actual Behavior
The first and last icon is red and the second icon is orange.

The second and last accounts have their text colour set to the class __primary--text__.

### Reproduction Link
<a href="https://codepen.io/robert-wuttke/pen/VqwNPx" target="_blank">https://codepen.io/robert-wuttke/pen/VqwNPx</a>

### Other comments
Looking at the generated HTML we see

```html
<div class="v-treeview-node primary--text">
  <div class="v-treeview-node__root">
  <div class="v-treeview-node__children">
</div>
```

Because the outer _div_ has the **primary--text** class, all the children will be rendered in the browser with that colour as well.

I think the **primary--text** should be on the **v-treeview-node__root** _div_, so that only the currently active node is rendered with that colour, which will then be in sync with the colouring of the icon.

**Comment by rwuttke** [comment]
@MajesticPotatoe 

Hi, I just checked and the PR for this says it is in 1.3.16, but the tag for 1.3.16 doesn't have the code fix, and neither does 1.4.0 or master.

Checked a different PR and that is not in those 3 places either.

**Comment by nekosaur** [comment]
Strange

**Comment by rwuttke** [comment]
Just checked master again today, and it is now there, very strange indeed, but 1.3.16 and 1.4.0 still don't have the changes.

**Comment by nekosaur** [comment]
You will have to wait for a new release
