### ISSUE TITLE
css rule to support a wrapping div container for v-toolbar and main for pre-defined templates

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#586]
`NUXT` users will have one nested div container where the content would be displayed. Currently this is not working out of the box. A draft how a default layout in most cases would look like:
```
<v-app>
  <v-navigation-drawer></v-navigation-drawer>
  <div> <== <NUXT/>
    <v-toolbar></v-toolbar>
    <main>
      <v-container fluid>
        <router-view></router-view>
      </v-container>
    </main>
  </div>
  <v-footer></v-footer>
</v-app>
```

**Comment by johnleider** [comment]
Why would the navigation drawer be outside of the nuxt element but the others could not be?

**Comment by dohomi** [comment]
@johnleider its just my personal opinion to leave the main navigation outside of the dynamically re-rendered `NUXT` container. The main-navigation usually stays the same across all pages.

**Comment by johnleider** [comment]
It create's an issue due to the simplistic way the layout communicates. It does so with adjacent sibling selector, **`**, and it's one of the few opinionated things.

**Comment by dohomi** [comment]
@johnleider just as a reference, this is how nuxtjs.org default layout looks like:
https://github.com/nuxt/nuxtjs.org/blob/master/layouts/default.vue
If we could support this structure as well beside the current one it will be great for all `NUXT` users.

**Comment by johnleider** [comment]
I'll look into it!

**Comment by dohomi** [comment]
@johnleider one more thought about this issue: I wanted to prepare an additional toolbar to the right on specific form elements inside of my page layout. This would require again some CSS modification, because the toolbar would be inside of the nested `NUXT`container:
```
<v-app>
  <v-navigation-drawer></v-navigation-drawer>
  <div> <== <NUXT/>
    <v-toolbar></v-toolbar>
    <main>
      <v-container fluid>
        <router-view></router-view>
      </v-container>
    </main>
    <v-navigation-drawer right></v-navigation-drawer>
  </div>
  <v-footer></v-footer>
</v-app>
```

**Comment by johnleider** [comment]
We discussed this in chat and I was victorious ⚔
