### ISSUE TITLE
[Bug Report] v-select with append/prepend slot, clicking on slot closes menu

### ISSUE THREAD

**Issue by blalan05** [vuetifyjs/vuetify#5871]
### Versions and Environment
**Vuetify:** 1.3.13
**Last working version:** 1.3.11
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Open v-select, click on "Select All"

### Expected Behavior
Items selected and menu stays open

### Actual Behavior
Menu closes, nothing is selected.

### Reproduction Link
<a href="https://codepen.io/anon/pen/WLvJrY?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/WLvJrY?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/980142f

Simlified repro 1.3.13: https://codepen.io/anon/pen/GPJdOd
1.3.12: https://codepen.io/anon/pen/WLvJXm
