### ISSUE TITLE
[Bug Report] Dynamic dark prop not setting on created()

### ISSUE THREAD

**Issue by sphildreth** [vuetifyjs/vuetify#5873]
### Versions and Environment
**Vuetify:** 1.3.13
**Vue:** 2.5.20
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Put the "this.$vuetify.dark = true;" in "created" and the card isn't dark. Put the "this.$vuetify.dark = true;" in "mounted" and it works.

### Expected Behavior
That created() sets the dark prop based on the value in created.

### Actual Behavior
Seems to ignore in created() but works in mounted()

### Reproduction Link
<a href="https://codepen.io/anon/pen/roVrYo" target="_blank">https://codepen.io/anon/pen/roVrYo</a>

**Comment by sphildreth** [comment]
Can you give me an example of what you mean by "through provide/inject" for setting dark please? I opened this as the request of @jacekkarczmarczyk on discord when I asked if I should use created() or mounted().

**Comment by johnleider** [comment]
Setting `vuetify.dark` to true will change its primary value in `v-app` and automatically propagate through your application.

**Comment by sphildreth** [comment]
I don't see that behavior on https://codepen.io/anon/pen/roVrYo ?

**Comment by blalan** [comment]
This probably isn't the best way, but a simple fix: https://codepen.io/anon/pen/Qzjymo

**Comment by sphildreth** [comment]
> This probably isn't the best way, but a simple fix: https://codepen.io/anon/pen/Qzjymo

This is what I had originally, @johnleider was saying to not do that binding of ":dark" as it's handled automatically when the vuetify.dark value is set.

**Comment by johnleider** [comment]
I'm looking back on previous commits to see if this is a regression. @blalan 's workaround is sufficient for now.

**Comment by MajesticPotatoe** [comment]
Seems that beforeMounted will trigger dark change in the text, but not to app overall.

**Comment by johnleider** [comment]
This is resolved for v2.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
