### ISSUE TITLE
[Bug Report] Circular Progress Bar

### ISSUE THREAD

**Issue by amroessam** [vuetifyjs/vuetify#5874]
### Versions and Environment
**Vuetify:** 1.3.13
**Vue:** 2.5.21
**Browsers:** Chrome 69.0.3497.92
**OS:** Windows 10

### Steps to reproduce
add width attribute to v-progress-circular

### Expected Behavior
No warnings in the console

### Actual Behavior
Works, but logs an error in the console
```Invalid prop: type check failed for prop "width"```

### Reproduction Link
<a href="https://codepen.io/anon/pen/xmGBLN" target="_blank">https://codepen.io/anon/pen/xmGBLN</a>

### Other comments
Can make it work if you bind it to a data property, but this is unnecessary since it should convert the string to a number

**Comment by sh7dm** [comment]
Workaround: `:number="10"`

**Comment by amroessam** [comment]
Yeah, but again you're binding to a value, makes no sense, should just convert the string to int when passing to the css
