### ISSUE TITLE
[Bug Report] Text field with reactive modification of rules doesn't trigger re revalidation

### ISSUE THREAD

**Issue by PaulBernier** [vuetifyjs/vuetify#5878]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Firefox 63.0
**OS:** Ubuntu undefined

### Steps to reproduce
Input 8 in the second text field. Validation error triggers as expected because 8 < 10.
Now change the first text field value to 5. Nothing happen (second field is still in error) even though the rules have been effectively changed to validate the second field and that 5 < 8 so there shoudn't be an error.

### Expected Behavior
Text field rules get re validate as the rule function gets modified.

### Actual Behavior
After the rules get updated the field is not re validated which I would expect to happen reactively.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZVbMvg" target="_blank">https://codepen.io/anon/pen/ZVbMvg</a>

### Other comments
My own investigation led to this line:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/validatable.js#L120
This deepEqual value doesn't make the difference between 2 different functions, so I'm questioning the efficiency of that check.

Thank you.

**Comment by johnleider** [comment]
Not sure how to resolve this. The function signatures will always be the same. My suggestion would be to watch `number` and manually invoke **validate** when it changes: https://codepen.io/johnjleider/pen/LYEeaZg?editors=1111

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
