### ISSUE TITLE
[Feature Request] Treeview - Prop to return object instead of key for selected items

### ISSUE THREAD

**Issue by ssipos90** [vuetifyjs/vuetify#5881]
### Problem to solve
If you have a big tree, there's no point for the dev to lookup the active item in the tree based on the ID returned in the active array (via prop sync or update:active event).

Other components like v-select have the option to return the whole object as selected and I think this would be useful here as well.

### Proposed solution
I got nothing...

**Comment by bellagamba** [comment]
Has this change been overridden?
Latest version of Vuetify still returning the item.id on activeUpdate event
