### ISSUE TITLE
[Bug Report] v-tooltip and v-menu do not work with an external activator

### ISSUE THREAD

**Issue by builder7777** [vuetifyjs/vuetify#5890]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create `v-tooltip` component, create a **separate** activator button.

### Expected Behavior
Tooltip should appear when hovering over activator

### Actual Behavior
Tooltip does not appear

### Reproduction Link
<a href="https://codepen.io/anon/pen/roxwoZ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/roxwoZ?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
Are you trying to attach a tooltip to a button? Believe the activator goes on the button not the tooltip as such
https://codepen.io/anon/pen/ebJeJG?&editable=true&editors=101

**Comment by andrei7777** [comment]
I'm trying to use it according to the documentation. It says the "Tooltips **can** wrap any element.", meaning it doesn't **have to**. I'm trying to implement it the way where it doesn't wrap the button, and it's not working, hence the bug report.

**Comment by MajesticPotatoe** [comment]
They can. seems that we don't have an example of a detached, I will add one to the docs for the next update. You can do detached using the `attach` prop - https://codepen.io/anon/pen/KbzWLb

**Comment by MajesticPotatoe** [comment]
Updated https://github.com/vuetifyjs/vuetify/commit/9e89ec24f5c588ed6c121e3df6ad067b2d3c944c

**Comment by KaelWD** [comment]
This is a bug, see #5860

It only works for v-menu if the value bound to `activator` changes after mount, and v-tooltip doesn't have any handing for it at all.

**Comment by zajca** [comment]
I run into same issue, I want to add tooltip to svg path element, and I'm using id selector activator for this.
Here is example: https://codepen.io/anon/pen/rPpPVx?editors=1010
