### ISSUE TITLE
[Feature Request] Divider for tabs

### ISSUE THREAD

**Issue by ArtyomBist** [vuetifyjs/vuetify#5893]
### Problem to solve
Tabs have vertical divider when use iterator

### Proposed solution
Add vertical-divider boolean props for tabs (with indication for every side)

**Comment by KaelWD** [comment]
#3971?

You can't just open an issue with a single sentence repeated three times, there's no way this is gonna be implemented without more detail.

**Comment by skortabeast** [comment]
solution by link not resolve my problem and I don't want use other component. But simple solution for resolve my problem it's use css class with right border , such as
`.divider {
  border-right: 1px solid #b3d4fc
}
.divider:last-child  {
  border-right: 0
}`
solution [https://codepen.io/anon/pen/JwGzGZ?editors=1100](url)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
