### ISSUE TITLE
[Feature Request] why  vuetify dosen't  have a upload component?

### ISSUE THREAD

**Issue by fsisjacky** [vuetifyjs/vuetify#5895]
### Problem to solve
when I use vuetify, I found that vuetify dosen't have a upload component, but I think  it's very important componet for using vuetify make a bakend website. 

### Proposed solution
use an other UI like element instead of it.

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/50006582-51927c80-0002-11e9-8a4d-a2fe93a5b79a.png)
