### ISSUE TITLE
Only first v-layout is put into DOM if wrapped in <v-slide-y-transition>

### ISSUE THREAD

**Issue by aaronjpitts** [vuetifyjs/vuetify#590]
If multiple `<v-layout>` tags are used, only the first is put into the DOM, the rest are stripped out if wrapped in `<v-slide-y-transition>`.

 http://codepen.io/anon/pen/jmXqqa

**Comment by johnleider** [comment]
The reason for this is that you are wrapping multiple elements with a single transition. For multiple items you should use ```transition-group``` which is not supported by default with the transition functional components.

To do that you would need to do something like:

```
<transition-group name="slide-x-transition" tag="div">
...
</transition-group>
```

More information can be found here: https://vuejs.org/v2/guide/transitions.html#List-Transitions
