### ISSUE TITLE
[Feature Request] Medium icon size for v-timeline-item

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5900]
### Problem to solve
It would be nice if there could be something in between sizes of `small` and `normal-size` of `v-timeline-item`. 

Small is too small and normal is too big for me. 

### Proposed solution
Adding `medium` size prop would be nice enhancement

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time. There will be additional size options in v3 for all Vuetify components so make sure to check them out.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
