### ISSUE TITLE
[Feature Request] Multiple option on select component should have collapse option.

### ISSUE THREAD

**Issue by AshwinTayson** [vuetifyjs/vuetify#5903]
### Problem to solve
When we have more items than what the input could hold, it will break to the second line. This option will break it to the second line and so on.

### Proposed solution
If after a few options no  horizontal space is found instead of going to next line, it can add a chip showing how many extra options are selected. i.e (+1, +2) Element does this by collapse-tags

Example: https://jsfiddle.net/ur82xvh5/

**Comment by jacekkarczmarczyk** [comment]
You can do it in userland https://vuetifyjs.com/en/components/selects#example-selection-appearance
