### ISSUE TITLE
[Feature Request] add support for function callback of item-text to v-treeview

### ISSUE THREAD

**Issue by meteorlxy** [vuetifyjs/vuetify#5904]
### Problem to solve
`VSelect`'s `item-text` accepts `string | array | function`, while `VTreeview`'s `item-text` only accepts `string` for now.

It'll be more flexible if `VTreeview`'s `item-text` could accept functions

### Proposed solution
Like `VSelect` and `VAutocomplete`.

**Comment by jacekkarczmarczyk** [comment]
Related https://github.com/vuetifyjs/vuetify/issues/7328

**Comment by kingyangcn** [comment]
Yeah i need it too, this feature is really helpful. plz
