### ISSUE TITLE
[Bug Report] content of v-footer is not centered v-navigation-drawer exists on the right

### ISSUE THREAD

**Issue by dmecke** [vuetifyjs/vuetify#5908]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
In the pen you can see that the text in the footer is not centered but shifted to the left. Setting `showRightDrawer` to `false` centers the content.

### Expected Behavior
The content of the footer should be centered as the footer is not `inset`.

### Actual Behavior
The content is shifted to the left.

### Reproduction Link
<a href="https://codepen.io/dmecke/pen/NexjgZ" target="_blank">https://codepen.io/dmecke/pen/NexjgZ</a>

### Other comments
It seems to me that at https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VFooter/VFooter.js#L45 there is missing a `|| !this.inset`. If this is the case I could create a pull request if you like me to.

**Comment by sh7dm** [comment]
@dmecke Yes, after adding `|| !this.inset` it works perfect! Open the PR!
