### ISSUE TITLE
[Bug Report] Vuetify selects break tab key focus support in Mac OS Safari

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#5913]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Safari 12.0.2
**OS:** Mac OS 10.14.2

### Steps to reproduce
Open the reproduction link, click on a select, try using tab and shift tab to move between other selects.

### Expected Behavior
Focus should change to the next and previous selects.

### Actual Behavior
Focus does not change as expected.

### Reproduction Link
<a href="https://codepen.io/ChrisLandowski/pen/EGyjoK?&editable=true&editors=101" target="_blank">https://codepen.io/ChrisLandowski/pen/EGyjoK?&editable=true&editors=101</a>

### Other comments
If you visit the Vuetify Issue Creator page (https://issues.vuetifyjs.com), the tab key support works as expected until you tab into the affected browsers select.

**Comment by johnleider** [comment]
The bug here is shift-tab as the former was resolved in 1.3.14

**Comment by johnleider** [comment]
This is resolved with 5fa6a68 . Thank you for your patience on this.
