### ISSUE TITLE
[Bug Report] Links in labels are not clickable

### ISSUE THREAD

**Issue by mattcdavis1** [vuetifyjs/vuetify#5914]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a link inside the label slot of a v-text-field component.

### Expected Behavior
Link should be clickable and cursor should change to pointer (assuming css is added for this as it is in the codepen)

### Actual Behavior
Nothing happens when the link is clicked.  The cursor does not change to a pointer even though there is css for this.

### Reproduction Link
<a href="https://codepen.io/mattcdavis1/pen/BvzLpQ" target="_blank">https://codepen.io/mattcdavis1/pen/BvzLpQ</a>

### Other comments
The use case is that in the context of a dropdown, if the dropdown item does not exist i want the user to be able to click on the label to open a modal form for creating a new entry that will be added to the dropdown list.

**Comment by KaelWD** [comment]
I believe this is intentional. You should use v-autocomplete's `no-data` slot instead.

**Comment by mattcdavis1** [comment]
@KaelWD - the no-data slot does not show up in the label area which is where i want the links to show up.  Also, as the name implies, no-data is for when there is no-data and i want the links to show up regardless of whether there is no data or not.

**Comment by johnleider** [comment]
This is intentional and something that can be tweaked in userland.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
