### ISSUE TITLE
[Feature Request] Suggestions for documentation site (dev version)

### ISSUE THREAD

**Issue by BowenYin** [vuetifyjs/vuetify#5916]
These suggestions are regarding the dev version of the documentation at [next.vuetifyjs.com](https://next.vuetifyjs.com).

### Problem to solve
Is this even Vuetify pictured below?
![next.vuetifyjs.com screenshot](https://cdn.pbrd.co/images/HRXO6DU.png)

This is the Vuetify website I know and love:
![vuetifyjs.com screenshot](https://cdn.pbrd.co/images/HRXGaQ0.png)

Here are my suggestions regarding the recent updates to the dev Vuetify documentation site:
- Toolbar links are repetitive when viewing documentation
All the categories linked in the toolbar (Framework, Components, Directives) are already easily accessible using the left sidebar in docs, so displaying them at the top is repetitive.
- A lot of the options and resources available before on the toolbar are now gone.
Ecosystem links, support links, version selector are useful but they seem to be missing on the toolbar now. Also the GitHub star button looks old/outdated compared to the rest of the md, and there is already a GitHub icon button which makes it repetitive.
- The new monospace title font, round buttons, and deep theme color don't really fit into the Vuetify signature style (in my opinion) and don't exhibit the catchy style that the current site does.

### Proposed solution
Maybe revert the new design changes ([next.vuetifyjs.com](https://next.vuetifyjs.com)) back to the current design ([vuetifyjs.com](https://vuetifyjs.com)) of the documentation site.
Sorry for picking out so many little things, but I think these suggestions will allow the new documentation update to be less of a huge surprise change to everyone.
Thanks!

**Comment by johnleider** [comment]
Closed in 2ecd43221c51ab325fe0d2d1f8fe255ce35d726b
