### ISSUE TITLE
[Feature Request] Clear v-autocomplete selection as soon as the text field is empty

### ISSUE THREAD

**Issue by AlexandruMiricioiu** [vuetifyjs/vuetify#5917]
### Problem to solve
v-autocomplete behavior after you choose an item:

Case 1: If you delete all the text then you tab out, the v-autocomplete selection reappears.
Case 2: If you delete all the text then you hit 'backspace' or 'delete' (just once) and then you tab out, you will be left with an v-autocomplete with selected text that display's nothing.
Case 3: If you delete all the text then you hit 'backspace' or 'delete' (twice), the selection disappears.

https://codepen.io/alexandrumiricioiu/pen/RERwYm
I don't know if this is a bug or not.

It will be nice if as soon as the text field is empty, the selection dissapears.
This will inprove the ux and avoid having empty v-autocompletes with data binded.

### Proposed solution
I attached my workaround.
https://codepen.io/alexandrumiricioiu/pen/jXrOoB

Thank you

**Comment by KaelWD** [comment]
> Case 3: If you delete all the text then you hit 'backspace' or 'delete' (twice), the selection disappears.

This sounds like #4940

**Comment by Anima-t3d** [comment]
This issue still seems to persist. The linked feat issue is closed without implementation. Any update on this @KaelWD ? 
This issue also appears in combobox: after selection, user needs to backspace twice for placeholder to show/reset "is dirty" state.

It seems to me this behaviour should be the default behaviour? Am I doing something wrong perhaps? In v1.0.x using v-select it worked as expected.

**Comment by KaelWD** [comment]
#4940

**Comment by scscgit** [comment]
Isn't the proposed solution still extremely dangerous for purposes of any forms where mistakes can have severe consequences? I strongly disagree with the default behavior of value de-selecting only after the input has been completely cleared. At the very least, this could be a parametrized behavior where we can choose if we want to clear the value on **any** change, even if the user only deletes a single character. As an extreme case, even if the user types the exact match, their input will still revert back to the previous & hidden internal value, which they may not notice.

![image](https://user-images.githubusercontent.com/3118390/163006594-4c6961ad-8fc1-43fc-9986-358bf5cf172b.png)

I'm also tracking this, along with a related limitation of being unable to use a workaround, at
* https://github.com/vuetifyjs/vuetify/issues/12880
