### ISSUE TITLE
[Feature Request] add disabled prop to v-treeview

### ISSUE THREAD

**Issue by ahmadnchami** [vuetifyjs/vuetify#5918]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Try to click on any node

### Expected Behavior
Treeview nodes should be disabled

### Actual Behavior
Treeview nodes remains enabled

### Reproduction Link
<a href="https://codepen.io/anec/pen/ZVOxMK" target="_blank">https://codepen.io/anec/pen/ZVOxMK</a>

**Comment by jacekkarczmarczyk** [comment]
Treeview doesn't support `disabled` prop, it's a feature request, not a bug report

**Comment by jacekkarczmarczyk** [comment]
It should be possible to achieve it by adding `disabled: true` to each (or at least top level) nodes

**Comment by morficus** [comment]
this can also be done via the `item-disabled` prop on the Treeview component
