### ISSUE TITLE
[Bug Report] It's possible to enter multiple decimal separators in v-text-field

### ISSUE THREAD

**Issue by olegjo** [vuetifyjs/vuetify#5920]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a v-text-field with type="number". It is possible to type in a string like
3.14.15
which is not numeric.

### Expected Behavior
It should only be possible to have one decimal separator in a v-text-field with type="number"
3.14.15 - should not work
3.1415  - should work

### Actual Behavior
Can write as many "points" as I want.
3.14.15....2.3..12.. Works. It should note

### Reproduction Link
<a href="https://codepen.io/olegjo/pen/VqjGqv" target="_blank">https://codepen.io/olegjo/pen/VqjGqv</a>

**Comment by jacekkarczmarczyk** [comment]
`type="number"` is just passed to native input field which allows the same
https://codepen.io/anon/pen/oJLPrX

**Comment by KaelWD** [comment]
Duplicate of #5224
