### ISSUE TITLE
[Bug Report] Expansion Panel model unexpected behaviour with multidimensional arrays

### ISSUE THREAD

**Issue by M3psipax** [vuetifyjs/vuetify#5925]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
following the codepen link, use the text input field to set a number for the panel model. press the "setModel" button to open the respective panel.
now press the "insertModel" button. the item array will be replaced by a new array with an additional item in the 2nd sub category. the new item will be rendered correctly.
now set the model to the highest possible index: 12.
press the "setModel" button. the new item will open up.

### Expected Behavior
the last index should correspond to the last item in the list just as it would on a completely new render of the component.

### Actual Behavior
items that are added into a nested array are simply given the highest index value no matter where they are added.

### Reproduction Link
<a href="https://codepen.io/M3psipax/pen/yGJwQg" target="_blank">https://codepen.io/M3psipax/pen/yGJwQg</a>

**Comment by johnleider** [comment]
If you want this behavior, bind a unique key. The way expansion-panel works now (and in the future update where it uses item-group as an extension) each registered element gets an index based upon when it is registered. When you change the array it's not re-rendering any of the elements so only the diff gets added, hence index 12.

Working example https://codepen.io/johnjleider/pen/Mxrber
