### ISSUE TITLE
[Feature Request] Create slot for hint

### ISSUE THREAD

**Issue by mattcdavis1** [vuetifyjs/vuetify#5928]
### Problem to solve
Currently, i'm unable to add event handlers to links in hints.  For example, in [this codepen](https://codepen.io/mattcdavis1/pen/qLaOGy) i would like to add event handlers to handle "Split Transaction" and "Create Category" but i can't do this (at least not using the @click syntax)

### Proposed solution
Add a slot for hints that allows works with event handlers such as @click

**Comment by KaelWD** [comment]
The `message` scoped slot was added in c0a81f193743df261905a214de037ed1d183d9e4
