### ISSUE TITLE
[Feature Request] Define custom steps for v-slider

### ISSUE THREAD

**Issue by aster1210** [vuetifyjs/vuetify#5930]
### Problem to solve
As demonstrated in this pen: https://codepen.io/anon/pen/jXMZOZ , if a slider's step property is not a multiple of the slider's range, it won't be possible to select the minimum and maximum values of the slider. It is also not possible to offer specific values to select on a slider with a large step.

### Proposed solution
The proposed solution would be to add an attibute to the v-slider, that would allow to define custom values that a slider pin can stop on as well as the automatic values set by the stepper.

**Comment by vcastro45** [comment]
Also usefull in my case:
I want to step multiples of 50 AND 30 at the same time

**Comment by mathiasleroy** [comment]
+1
I would like to be able to make ~logarithmic steps

    1990, 1920, 1940, 1960, 
    1970, 1980, 1990, 2000,
    2005, 2010, 2015,
    2016, 2017, 2018, 2019, 2020

**Comment by AmirMeimari** [comment]
I also need this :)

**Comment by dzlabs** [comment]
I also need this 👍

**Comment by mentallydetached** [comment]
Looking for this as well

**Comment by VyazovskyE** [comment]
> +1
> I would like to be able to make ~logarithmic stops / steps
> 
> ```
> [0, 
>  50, 100, 
>  500, 1000, 
>  5000, 10000, 
>  50000, 100000, 
>  500000, 1000000]
> ```

Logarithmic steps are exactly what I'm looking for.

**Comment by GuiDevloper** [comment]
Sorry for bumping this one, but for anyone searching for this
I did used an step conditional generator (as computed property) based on current value of slider:
```js
// Using v-range-slider Array
let val = this.range[1];
let step = 0;
// Go until 1000e6 or break
for (let i = 1; i <= 6; i++) {
  // Check current range (e.g 10000~100000)
  const rangeFound = (
    val > this.getExpo(i) &&
    val <= this.getExpo(i + 1)
  );
  if (rangeFound) {
    step = this.getExpo(i);
    break;
  }
}
```
As I just need to test against exponentials of 1000, this method was helpful:
```js
getExpo(i) {
  return parseFloat('1000e' + i);
}
```

**Comment by technbuzz** [comment]
> +1
> I would like to be able to make ~logarithmic stops / steps
> 
> ```
> [0, 
>  50, 100, 
>  500, 1000, 
>  5000, 10000, 
>  50000, 100000, 
>  500000, 1000000]
> ```
> 
> or
> 
> ```
> [1900, 1920, 1940, 1960,       // steps of 20
>  1970, 1980, 1990, 2000,       // steps of 10
>  2005, 2010, 2015,             // steps of 5
>  2016, 2017, 2018, 2019, 2020] // steps of 1
> ```

I have temporarily solved it using mapped objects. We can leave the step as it is. In your case it would be like below. Just map it with v-model of v-slider
` {
  0: 0, 
  1: 50, 2: 100, 
  3: 500, 4: 1000
}`

**Comment by johnleider** [comment]
The team feels that this process has value but we aren't able to identify where it could be reused within the framework to better support its cause.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by dressuncoded** [comment]
I realized this is a closed issue, but in case people happen upon this––the workaround mentioned is not a true workaround as it only helps with mapping internal values, but does not help visually accommodating for uneven steps. Hope that this feature may be implemented in the future.
