### ISSUE TITLE
[Feature Request] Optional v-list-tile in v-autocomplete item slot

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#5933]
### Problem to solve
Allows the whole row to be styled, see the issue with this codepen: https://codepen.io/anon/pen/wRzEqG. 
If v-list-tile is used it is nested and styles don't work as expected.
Also is consistent with v-data-table items slot where you can optionally include a tr for click and style purposes.

### Proposed solution
Allow v-list-tile to be optionally included in the item slot.

**Comment by KaelWD** [comment]
It doesn't nest if you don't use a template element: https://codepen.io/anon/pen/OrRoaR?editors=1010
This needs to be normalised if the array only contains one item.

**Comment by ksankumar** [comment]
This issue may solve this one.
https://github.com/vuetifyjs/vuetify/issues/4089

**Comment by amritk** [comment]
Hey did you guys notice, that when there's a v-list-tile inside of an autocomplete, you cant click on it anymore? Check your codepens

**Comment by KaelWD** [comment]
Fixed by e19189c4 with #6376
