### ISSUE TITLE
[Bug Report] v-autocomplete placeholder not rendering correctly in IE11

### ISSUE THREAD

**Issue by ccarlton96** [vuetifyjs/vuetify#5937]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Go to the CodePen and type in something into the v-autocomplete. Then un-focus, or de-select, the autocomplete box.

### Expected Behavior
The placeholder should go away when there is an item in the autocomplete box

### Actual Behavior
The placeholder stays in the box and appends itself to the end of whatever is typed in the box. The placeholder will go away when the autocomplete is focused or selected.

### Reproduction Link
<a href="https://codepen.io/ccarlton96/pen/PXbqWp" target="_blank">https://codepen.io/ccarlton96/pen/PXbqWp</a>

### Other comments
This is my first time using codePen and submitting an issue, so sorry if I didn't do it quite right. The issue ONLY occurs in IE11, and codePen refuses to work with IE11 so I had trouble recreating the exact error. I can provide screenshots upon request.

**Comment by ccarlton96** [comment]
Tentatively fixed with some clever CSS-ing

.v-input--is-dirty :-ms-input-placeholder {
    color: $material-light.text.disabled;
    opacity: 0;
}

**Comment by jacekkarczmarczyk** [comment]
I couldn't reproduce it, maybe you can post the screenshots and exact version of IE or even better if you could clone the vuetify repo, copy `packages/vuetify/dev/Playground.vue.example` to `packages/vuetify/dev/Playground.vue`, edit the playground and run `yarn && yarn dev`. If you can reproduce it there then just send the contents of `Playground.vue`. Thank you
