### ISSUE TITLE
[Bug Report] <v-img> not working with height or width inline

### ISSUE THREAD

**Issue by tikusdugem** [vuetifyjs/vuetify#5939]
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.1

### Steps to reproduce
I'm trying to insert some image or logo on v-toolbar with v-img and then i put width and height inline
```
<v-toolbar dark color="primary">
  <v-toolbar-title>Siapa Kamu ?!</v-toolbar-title>
  <v-spacer></v-spacer>
  <v-img :src="require('@/assets/logo.svg')" alt="Icon Created By Twitter" height="30" width="30"></v-img>
</v-toolbar>
```

### Expected Behavior
I hope I can resize my image to like a logo with that parameter

### Actual Behavior
The image only resize with heigh, how many number width they didn't work

### Reproduction Link
<a href="https://github.com/tikusdugem/website-sales-fe/blob/master/src/views/LoginPage.vue" target="_blank">https://github.com/tikusdugem/website-sales-fe/blob/master/src/views/LoginPage.vue</a>

### Other comments
I don't know it's Bug or just i don't get enough reading the document but maybe it's tricky when I using max-width="30" it works
```
<v-toolbar dark color="primary">
  <v-toolbar-title>Siapa Kamu ?!</v-toolbar-title>
  <v-spacer></v-spacer>
  <v-img :src="require('@/assets/logo.svg')" alt="Icon Created By Twitter" max-width="30"></v-img>
</v-toolbar>
```

***Note:***
- I just copy paste template from https://vuetifyjs.com/en/examples/layouts/centered
- Vue and Vuetify download or install from VueCli-3

**Comment by KaelWD** [comment]
It works fine in codepen, I don't really understand what the problem is https://codepen.io/anon/pen/GPNWMV?editors=1010

**Comment by KaelWD** [comment]
It's just because the toolbar is a flex container, so `width` will just set the initial width but it'll be allowed to grow as much as it wants. If you just set `max-width` the height will be set to match the image aspect ratio.
