### ISSUE TITLE
[Feature Request] v-calendar

### ISSUE THREAD

**Issue by waspinator** [vuetifyjs/vuetify#5946]
### Problem to solve
 time-management and scheduling calendar ui

### Proposed solution
I noticed that there is a `v-calendar` component listed in the 1.4 release. But I couldn't find any mention of it on https://next.vuetifyjs.com/en/components/api-explorer. What is the status of the component, and is it aimed at becoming a component for  time-management and scheduling or something else?

I was thinking something like https://fullcalendar.io

**Comment by MajesticPotatoe** [comment]
Dupilcate of #1915.
`v-calendar` was postponed and did not make it into 1.4 release. You can follow its status in its PR - #4846

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
