### ISSUE TITLE
[Bug Report] v-treeview: "activatable" does not work with "open-on-click"

### ISSUE THREAD

**Issue by sp00x** [vuetifyjs/vuetify#5947]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Put both "open-on-click" and "activatable" on the same v-treeview element. 

### Expected Behavior
Both features are applied (?)

### Actual Behavior
Only open-on-click is applied

### Reproduction Link
<a href="https://codepen.io/anon/pen/yGgXRB" target="_blank">https://codepen.io/anon/pen/yGgXRB</a>

### Other comments
I'm not sure if this was even intended to work, but the documentation does not mention that they're mutually exclusive. (If they're not meant to work, I guess it should be mentioned or give a warning or something?)

**Comment by nekosaur** [comment]
Yes, these are mutually exclusive, and that should probably be mentioned somewhere in docs

**Comment by wehrmarc** [comment]
@nekosaur 
Actually, the docs states that when using the open-on-click prop with the activatable prop, you will be unable to mark nodes with children as active. It doesn't say that they're mutually exclusive.

It'd be really swell, if they weren't mutually exclusive, so only leaf nodes could be activated.

**Comment by nekosaur** [comment]
That is how it works currently. You are able to activate leaf nodes.

**Comment by nekosaur** [comment]
Ah, that should probably use `hasChildren`. I'll try to take a look this weekend.

**Comment by bovesan** [comment]
For anyone looking for a way to use both:
```
	watch: {
		active(to, from){
			if (!this.open.includes(to)){
				this.open.push(to);
			}
		}
	},
```

**Comment by YongzeYao** [comment]
This is still not fixed...

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
