### ISSUE TITLE
[Bug Report] v-list three line tile - subtitle not clamping vertically at 2 lines and then ellipsis

### ISSUE THREAD

**Issue by paul-a-byford** [vuetifyjs/vuetify#5949]
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
open codepen, then set viewport to mobile breakpoint size.

### Expected Behavior
subtitle within tile to clamping vertically at 2 lines and then ellipsis when there is more text than will fit in the tile

### Actual Behavior
subtitle text not ellipsing, instead the text spills out into the tile above

### Reproduction Link
<a href="https://codepen.io/pbyford/pen/pqRrJJ?editors=1010" target="_blank">https://codepen.io/pbyford/pen/pqRrJJ?editors=1010</a>

**Comment by paul-a-byford** [comment]
i looked into this further and found the issue can be solved by adding the css property  `-webkit-box-orient: vertical;`

i've updated the codepen to show how the property changes the results

**Comment by paul-a-byford** [comment]
i looked into this further and found the issue can be solved by adding the css property  `-webkit-box-orient: vertical;`

i've updated the codepen to show how the property changes the results

**Comment by johnleider** [comment]
This class already exists but is being removed from the build.
