### ISSUE TITLE
[Bug Report] v-autocomplete menu is not hiding behind mobile keyboard

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5950]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Opera
**OS:** Windows 7

### Steps to reproduce
Open documentation example of any autocomplete on mobile device and try to use mobile keyboard to input the value

### Expected Behavior
Autocomplete menu is hiding behind mobile keyboard

### Actual Behavior
Autocomplete menu is showing up over mobile keyboard, making v-autocomplete and also whole screen unreadable

![screenshot_2018-12-20-14-17-32-332_com opera browser](https://user-images.githubusercontent.com/34601970/50289351-dd743080-0468-11e9-8d44-86ab2bb55a18.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/OrWZaJ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/OrWZaJ?&editable=true&editors=101</a>

**Comment by mimischi** [comment]
On a similar note, this happens on big screens too. The menu overlaps with any site content, such that it fits on the available page height. Would it be possible to make it scrollable and overflow into the bottom of the page? 

<img width="1048" alt="screenshot 2018-12-21 at 10 28 17" src="https://user-images.githubusercontent.com/1052860/50335348-47ddad00-050b-11e9-93f5-0acf7d9bfe32.png">

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/vvZZqy?&editable=true&editors=101

**Comment by johnleider** [comment]
I'm removing this from the v2.0 milestone for 2 reasons:

- 1 There is a valid workaround which disables the default behavior
- 2 I'm honestly not sure the best way to approach this

The automatic positioning is to ensure that the menu is visible. This can in some cases cause unintended side effects, especially on mobile. I'm interested in additional feedback.

**Comment by etewiah** [comment]
The codepen no longer works.  Is someone able to explain what the workaround is?  Thanks.

**Comment by rethab** [comment]
I implemented a simpler workaround: On mobile, I just set the `maxHeight` to `130` and expand to the top. This means the user sees far fewer suggestions (2-3), but the input field is still visible and scrolling is possible as well.

```html
<v-autocomplete
  label="Please select a Timezone"
  v-model="timezone"
  :items="timezones"
  :error-messages="timezoneErrors"
  :menu-props="autocompleteMenuProps"
></v-autocomplete>
```

```javascript
autocompleteMenuProps() {
  // default properties copied from the vuetify-autocomplete docs
  let defaultProps = {
    closeOnClick: false,
    closeOnContentClick: false,
    disableKeys: true,
    openOnClick: false,
    maxHeight: 304
  };

  if (this.$vuetify.breakpoint.smAndDown) {
    defaultProps.maxHeight = 130;
    defaultProps.top = true;
  }
  return defaultProps;
}
```

**Comment by bad4iz** [comment]
[Possible Solution](https://github.com/vuetifyjs/vuetify/issues/10072#issuecomment-573528888)

**Comment by beshoo** [comment]
Any final fix for this?

**Comment by quroom** [comment]
New workaround
Tested in vuetify 2.3.19

Just add this code in v-autocomplete props.
```
:menu-props="
              $vuetify.breakpoint.smAndDown
                ? { maxHeight: 150 }
                : {
                    closeOnClick: false,
                    closeOnContentClick: false,
                    disableKeys: true,
                    openOnClick: false,
                    maxHeight: 304
                  }
            "
```

maxHeight makes selections height fixed to prevent hiding input.
