### ISSUE TITLE
[Feature Request] add rtl prop to v-icon

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#5953]
### Problem to solve
Ability the ability to flip icons by need and/or for RTL

### Proposed solution
Add a prop to v-icon that applies css to flip icons.
Google materials solution is detailed here: https://google.github.io/material-design-icons/#rtl-icons-on-the-web

Codepen example: https://codepen.io/anon/pen/VqPRyp

**Comment by johnleider** [comment]
updated codepen: https://codepen.io/johnjleider/pen/qBNGYVx

**Comment by johnleider** [comment]
I think that this is a quick win for v2.5 `v-icon` and will cautiously visit adding this functionality to other components as well.

**Comment by johnleider** [comment]
This is happening in version 3 with the updated lang service. Follow for future updates https://github.com/vuetifyjs/vuetify/issues/12699.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
