### ISSUE TITLE
[Bug Report] <v-select menu-props="auto" box/outline/solo> menu position incorrect 

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5954]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
Create a `v-select` with the `menu-props="auto"` and one of the style properties (`box`/`outline`/`solo`)
Open the `v-select` and select an item
Open the `v-select` again and the menu is not positioned so the list item and selected text are overlapping

### Expected Behavior
List item text overlapping the selected text (similar to `<v-select menu-props="auto">` without any style prop).

### Actual Behavior
`v-select` menu is dispositioned

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/YdZyOQ?&editable=true&editors=101" target="_blank">https://codepen.io/henriq88/pen/YdZyOQ?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Since this has been mostly resolved as of v2, I'm closing as resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
