### ISSUE TITLE
[Bug Report] Component inside list template loses focus

### ISSUE THREAD

**Issue by OOGV** [vuetifyjs/vuetify#5955]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
If key of v-for statement is the same as the text field's v-model
_v-list-tile :key="item.Code"_
_v-text-field v-model="item.Code"_
and we call a method on input event
_v-text-field @input="valueChanged"_
then the text field loses focus to body element after each key press.

### Expected Behavior
Text field should not lose focus.

### Actual Behavior
Text field loses focus

### Reproduction Link
<a href="https://codepen.io/OZYTRA/pen/wRJJMN" target="_blank">https://codepen.io/OZYTRA/pen/wRJJMN</a>

### Other comments
In example the text field with v-model="Code2" does not lose focus.

**Comment by jacekkarczmarczyk** [comment]
This is how vuejs works
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
