### ISSUE TITLE
[Bug Report] TreeView fails on register node and subnodes keys

### ISSUE THREAD

**Issue by pedritin91** [vuetifyjs/vuetify#5959]
### Versions and Environment
**Vuetify:** 1.3.15
**Last working version:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
1. Drop files into folder node.
2. Recursive-Reading builds the tree structure. (thank's to Chrome's FileSystem-API) 
3. When I expand tree internal register of nodes is crashing. Maybe `this.nodes` is not updated at this moment.
```javascript
//using https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js
register: function register(node) {
    var key = Object(_util_helpers__WEBPACK_IMPORTED_MODULE_4__["getObjectValueByPath"])(node.item, this.itemKey);
    this.nodes[key].vnode = node; //Line 15505:key is not mapped in nodes register object at this moment, That's why it fails here
    this.updateVnodeState(key);
},
```

### Expected Behavior
There should be no problems selecting nodes and subnodes.

### Actual Behavior
I can't use it for selection purpose in the actual state

### Reproduction Link
<a href="https://codepen.io/pedro-mora/pen/wRJpOw?editors=1011" target="_blank">https://codepen.io/pedro-mora/pen/wRJpOw?editors=1011</a>

**Comment by pedritin91** [comment]
Mean while I solved this by reasigning the items prop.

**Comment by nekosaur** [comment]
This will be fixed in https://github.com/vuetifyjs/vuetify/pull/5977
