### ISSUE TITLE
[Feature Request] Have control over scroll for v-data-table

### ISSUE THREAD

**Issue by JulienParis** [vuetifyjs/vuetify#5960]
### Problem to solve
I need to synchronize the horizontal scroll over two different overflown datatables, the two datatables being stacked one upon the other... The result I try to achieve is when I scroll horizontally one it scrolls the other one, so the columns of the two tables could always be aligned. (The same could be asked for vertical sync to align the rows)

Another note : those tables to sync are created from within different components : 1st component is one datable dedicated to display some "headers" appart with metadata (so I need a datatable for "headers"), the other component is used to display several datasets aligned with the "headers"... 

I tried to use the `v-scroll` prop inside the `v-data-table` component but it doesn't seem to return any change when scrolled. I believe it's because `<v-data-table>` creates some children (i.e. the table, the pagination, ...), and the div really scrollable is the first created inside the table component : `<div class="v-table__overflow">`

### Proposed solution
A `v-scroll-table` and a `scroll.sync` props could be added to the `<v-data-table>` component to return the scroll events occurring on the child `<div class="v-table__overflow">` ... 

Something like : 
```
<v-data-table  
  v-scroll-table="onScroll"
  scroll.sync="scrollSync"
>...< /v-data-table>
```

That way we could use a method getting the event `(e)` on the `<div class="v-table__overflow">` so we could send back the event's data to parent components and so on to sync all the tables together, even if they are within several components :

```
  <script>
      export default {
        data: () => ({
          scrollSync : {
            top: 0,
            left: 0
         }
       }),
      methods: {
        onScroll (e) {
          this.scrollSync.top = e.target.scrollTop ; 
          this.scrollSync.left = e.target.scrollLeft
        }
      }
    }
  </script>
```

... or something like that ? (BTW great work, I <3 Vuetify)

**Comment by JulienParis** [comment]
for now my solution (not the most elegant I guess) is the following (full code [here](https://github.com/entrepreneur-interet-general/solidata_frontend/blob/master/components/UI/viewEditDSI.vue#L294) ) : 

1. add a some scoped data in my child datatable component (ChildDT) : 
_(... in ChildDT ...)_
```
data () {
  return {
	offsetLeft : 0,
	dataTable : undefined,
   }
}
```

2.  add a ref to my datatable : 
_(... in ChildDT ...)_
```
<v-data-table
	:ref="'datatable'">
...
</v-data-table>
```

3. when the datatable is populated (from my backend API) I add a scroll listener to the `<div class=".v-table__overflow">`: 
_(... in ChildDT ...)_
```
methods : {
  get_FData_fromApi () {
    <... retrieve the data with a promise from API backend ...>
    .then( result => {
      var dataTable = this.$refs.datatable ;
      if ( dataTable !== undefined ) {
        var dt = dataTable.$el.querySelector(".v-table__overflow") 
        dt.addEventListener('scroll', this.onScroll);
        this.dataTable = dt
      }   
   }
}
```

4. add a method to react to scroll event
_(... in ChildDT ...)_
```
methods: {
  onScroll (e) {
    var scroll_data = e.target ;
     this.offsetLeft = scroll_data.scrollLeft ;
     this.$emit('scrollTable', { 
        left : scroll_data.scrollLeft 
     }) 
},
```

5. on the parent component (PaDT) the child component (ChildDT) receives the emit but also gets the prop `parent_scroll / scrollLeft` from parent : 
_(... in PaDT ...)_
```
<ChildDT
	:parent_scroll="scrollLeft"
	@scrollTable="updateScroll"
	>
</ChildDT>
```

6.  the parent component (PaDT) updates its own `scrollLeft` when receiving `scrollTable` by a method
_(... in PaDT ...)_
```
methods: {
  updateScroll(input) {
	this.scrollLeft = input.left
},
```

7. the child component (ChildDT) watches the inherited `parent_scroll` : 
_(... in ChildDT ...)_
```
watch: {
	parent_scroll : {
		immediate : true,
		handler (newVal, oldVal ) {
			if ( this.dataTable !== undefined ) {
				this.dataTable.scrollLeft = newVal
			}
		}
	},
}
```

... So that way if several `<ChildDT>` are created from `<PaDT>` a scroll from a `<ChildDT>` updates the others ...

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by dkichler** [comment]
@nekosaur I'm also interested in scrolling table functionality.  Curious whether there is some discussion I can read somewhere (that I haven't found) on why this isn't being pursued, or whether it's simply a matter of priority/bandwidth?

**Comment by kboicourt** [comment]
Also interested! The product I am working on needs to trigger a function to scroll back up to the top of the v-data-table when the v-data-table is scrolled, but we are having a hell of a time figuring out how to get it to trigger

**Comment by zkramer22** [comment]
Bummer that this can't be implemented natively, but honestly there is a super simple solution to this. Wild how no one has suggested this in so many years of this being an issue...

**just bind a scroll event to the DOM element** using regular ol' javascript after the component mounts! 

This is assuming you have a <v-data-table> with :fixed_header, :height, and the table is in its own component, although that last condition is not totally necessary).

`
<template lang="html">
  <div class="graph-content">
    <v-data-table v-show="topArtistUplifts.length" id="topUpliftTable" class="data-table-custom"
      :headers="tableHeaders" :items="topArtistUplifts" fixed-header :height="tableHeight"
      :items-per-page="-1" hide-default-footer :mobile-breakpoint="0">
      <template v-slot:item.artist_name="{ item }">
        <span>
          <router-link :to="{ name: 'Artist', query: { artistId: item.artist_id, ...linkQuery }}"
            class="artist-link inline">
              {{ item.artist_name }}
          </router-link>
        </span>
      </template>
      <template v-slot:item.absolute_number="{ item }">
        <span>+{{ getAbbreviatedNum(item.absolute_number) }}</span>
      </template>
      <template v-slot:item.relative_number="{ item }">
        <span :class="percentChangeStyle(item.relative_number * 100)">{{ percentChangeFormat((item.relative_number * 100).toFixed(2)) }}</span>
      </template>
    </v-data-table>
    <div class="no-notifs full-height" v-show="!topArtistUplifts.length">
      No uplift to report yet – please check back soon.
    </div>
    <Loader v-if="updating.topArtistUplifts" :height="50"/>
  </div>
</template>

<script>
  methods: {
    handleUpliftScroll(e) {
      console.log('yoooo this is a scroll event attached to the table!', e)
    },
  },
  mounted() {
    const tableWrapper = this.$el.children[0].children[0]
    tableWrapper.addEventListener('scroll', this.handleUpliftScroll)
  },
</script>
`

**Comment by zkramer22** [comment]
```
<template lang="html">
  <div class="graph-content">
    <v-data-table v-show="topArtistUplifts.length" id="topUpliftTable" class="data-table-custom"
      :headers="tableHeaders" :items="topArtistUplifts" fixed-header :height="tableHeight"
      :items-per-page="-1" hide-default-footer :mobile-breakpoint="0">
      <template v-slot:item.artist_name="{ item }">
        <span>
          <router-link :to="{ name: 'Artist', query: { artistId: item.artist_id, ...linkQuery }}"
            class="artist-link inline">
              {{ item.artist_name }}
          </router-link>
        </span>
      </template>
      <template v-slot:item.absolute_number="{ item }">
        <span>+{{ getAbbreviatedNum(item.absolute_number) }}</span>
      </template>
      <template v-slot:item.relative_number="{ item }">
        <span :class="percentChangeStyle(item.relative_number * 100)">{{ percentChangeFormat((item.relative_number * 100).toFixed(2)) }}</span>
      </template>
    </v-data-table>
    <div class="no-notifs full-height" v-show="!topArtistUplifts.length">
      No uplift to report yet – please check back soon.
    </div>
    <Loader v-if="updating.topArtistUplifts" :height="50"/>
  </div>
</template>

<script>
  methods: {
    handleUpliftScroll(e) {
      console.log('yoooo this is a scroll event attached to the table!', e)
    },
  },
  mounted() {
    const tableWrapper = this.$el.children[0].children[0]
    tableWrapper.addEventListener('scroll', this.handleUpliftScroll)
  },
</script>
```
