### ISSUE TITLE
[Bug Report] v-autocomplete with multiple values does not work when querying asynchronously

### ISSUE THREAD

**Issue by antice-eton** [vuetifyjs/vuetify#5961]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Setup a v-autocomplete in such a manner that the list of items is returned asynchronously based on the search criteria. In the linked to code pen, try choosing first New York then Wyoming.

### Expected Behavior
Able to select multiple items 

### Actual Behavior
Depends.

if cache-items is not set and the list of items returned from the server does not contain any of the previously selected items, t hen the selected items  disappear.

if cache-items is enabled,  behavior seems to stop you from selecting additional items.

### Reproduction Link
<a href="https://codepen.io/anon/pen/qLrLXX" target="_blank">https://codepen.io/anon/pen/qLrLXX</a>

**Comment by KaelWD** [comment]
> the selected items disappear

#4000

> seems to stop you from selecting additional items

#4580
