### ISSUE TITLE
[Feature Request] TypeScript definitions for component methods

### ISSUE THREAD

**Issue by mzhukovs** [vuetifyjs/vuetify#5962]
Let's say I have a v-form in my template;
`<v-form ref="form" v-model="valid" lazy-validation>`

If I want to use the functions like validate() and reset() on that form, I need a way to cast the ref to form.

I have added "vuetify" to the types array in my tsconfig, and am able to successfully import { VForm } from 'vuetify/lib', but when I try this, I get an error:
![image](https://user-images.githubusercontent.com/13161978/50335003-f3572380-0544-11e9-85dd-312e09cbf90b.png)

What is the proper way to achieve this? Please let me know, thanks.

**Comment by albernhagen** [comment]
I'd also like to see this implemented.

**Comment by mikestu** [comment]
We use TypeScript for our enterprise application, and would also benefit from fully fleshed out TypeScript definitions for the Vuetify components.  It appears to have been started, but all the individual components are just type "Component", which doesn't help with intellisense.  Since the next version of Vue will be built with TypeScript (although you can still use the transpiled javascript version as well), more people will likely start asking for this at some point.  It's not a deal-breaker for TypeScript users, but would be a nice-to-have.

https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/types

**Comment by rene-dohan** [comment]
How can I create my own definition or start external library for that if this is not to important for vue developers ? Any examples how to do that ? Or is there some other good UI library for vue with full type definitions ?

**Comment by CatsMiaow** [comment]
![image](https://user-images.githubusercontent.com/1300172/62352416-0dc59680-b543-11e9-8f1f-45ba098da5a9.png)

**Comment by nekosaur** [comment]
`InstanceType<typeof VForm>`

**Comment by CatsMiaow** [comment]
![image](https://user-images.githubusercontent.com/1300172/62434145-5a42e900-b772-11e9-8853-798ee39aa57b.png)
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/lib.d.ts#L15-L170

**Comment by mzhukovs** [comment]
hi @KaelWD , just wondering if there are any official plans to implement this any time soon? Please let us know when you get a chance, thanks!

**Comment by johnleider** [comment]
It's in our eyes for v3.

**Comment by Shinigami92** [comment]
If the [roadmap](https://vuetifyjs.com/en/introduction/roadmap) is correct, this will be more than a year away 😨

Are you interested in PRs? Or is something else in the way and blocking it?

**Comment by moshe5745** [comment]
+1 yes please

**Comment by josefsabl** [comment]
So far I added this to my vue.d.ts:

```
interface VForm extends HTMLFormElement {
    validate(): boolean;
}
```

**Comment by vegerot** [comment]
Three years later, what is the status of this?

I see you're "thinking about" adding it in Vuetify 3, but I don't see any PRs, issues, or proposals for this.  What does the Vuetify team think about this idea?

**Comment by farhadnowzari** [comment]
Is this resolved?
If I want to make a reference from a Carousel for example it seems I cannot simply do the following:
```
$refs!: {
carousel: VCarousel
}
```
This is NOT possible. How should it be done with typescript?

**Comment by tangdaohai** [comment]
I did:

```ts
import Vue from 'vue'

type VuetifyComponent = Vue & {
  validate (force: boolean, value?: any): boolean
}

export {
  VuetifyComponent
}

```

**Comment by davidzwa** [comment]
Vue3 Vuetify 3.0.0-beta.0

Defined VFormRef
```
export type VFormRef = {
  id: number | string;
  validate: () => Promise<string[]>;
  reset: () => void;
  resetValidation: () => void;
};
```

Usage:
```
// Either within defineComponents({...}) 
(this.$refs.formRefNameHere as VFormRef).reset();

// Or as ref type (do note it becomes type VFromRef | undefined which we have to handle and cast to VFromRef)
setup() {
 return {
   formRefNameHere: ref<VFromRef>()
 }
}
```
