### ISSUE TITLE
[Feature Request] v-autocomplete additional props required

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#5964]
### Problem to solve
v-autocomplete new suggested props url, minChars & response data key. See explanation below.

### Proposed solution
The following props can be introduced in v-autocomplete

url: remote url from which data is being fetched 

key: this refers to dictionary key of the response data objects that needs to be referred on resolve. In the example posted on Vuetify site (Searching an API ) the response data has 2 keys entries and count. The new proposed prop will point to "entries" key in this example.

minChars or something similar: required to trigger search-input:sync

**Comment by johnleider** [comment]
Duplicate (mostly) of https://github.com/vuetifyjs/vuetify/issues/835

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
