### ISSUE TITLE
[Feature Request] On-demand Loading Support

### ISSUE THREAD

**Issue by weihongyu12** [vuetifyjs/vuetify#5966]
### Problem to solve
Compared to Totally Import, On-demand Loading can effectively reduce the size of the package. The existing vuetify size exceeds 441kb, which has a bad impact on network performance.

### Proposed solution
Use [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) or [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin). Can modular import the packages, effectively reducing file size

``` javascript
// main.js
import Vue from 'vue';
// On-demand Loading, need use babel-plugin-import or ts-import-plugin
import { VApp, VContainer, VLayout, VFlex } from 'vuetify';

Vue.use(VApp);
Vue.use(VContainer);
Vue.use(VLayout);
Vue.use(VFlex);
```

Maybe there is a corresponding solution now, but it is not reflected in the documentation.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/guides/a-la-carte
