### ISSUE TITLE
[Bug Report] Empty VTextField with prefix erroneously has raised label

### ISSUE THREAD

**Issue by harrison-certain-lending** [vuetifyjs/vuetify#5969]
### Versions and Environment
**Vuetify:** 1.3.15
**Last working version:** 1.3.5
**Vue:** 2.5.21
**Browsers:** Chrome 73.0.3644.0
**OS:** Mac OS 10.14.1

### Steps to reproduce
Have a `VTextField` with a prefix and an empty string, `null`, or `undefined` value. 

### Expected Behavior
https://codepen.io/anon/pen/vvmdPB?&editable=true&editors=101
The label and prefix to be inline when `value.length === 0`

### Actual Behavior
The label is raised regardless of how many characters are present when a prefix exists. This causes particularly poor UX when first seeing a new form with a mix of prefixes and without. 

### Reproduction Link
<a href="https://codepen.io/anon/pen/romJPv?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/romJPv?&editable=true&editors=101</a>

**Comment by sh7dm** [comment]
This problem appeared in a438ccd

**Comment by jacekkarczmarczyk** [comment]
Related issue: https://github.com/vuetifyjs/vuetify/issues/6308 (cause by the same commit)

**Comment by johnleider** [comment]
This has been resolved as of v2 and will not be backported to the stable branch.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
