### ISSUE TITLE
v-btn-toggle(multi) manipulates vuex without mutations

### ISSUE THREAD

**Issue by LuckySphinX** [vuetifyjs/vuetify#597]
**Steps to reproduce**

-set an Array from the store as v-model in toggle button (multi)
-you can see the the error message in the console

**Versions**
Vuetify-Version: 0.12.1

### What is expected ?
The store should be updated by mutations.

### What is actually happening ?
The Toggle-Button manipulates the store directly.

**Reproduction Link**
http://codepen.io/anon/pen/vmbMEd?editors=1010

**Comment by mfferreira** [comment]
@LuckySphinX Vuetify does not touch the store.
The error is just a result of the implementation. You should provide the mutation to be called in the setter.

**Comment by kpilard** [comment]
I think it is still a bug. If there is no mutation in the the setter it is fine. Maybe he wants do do a validation or something like this.

But the state of the store is manipulated without an mutation call. That shouldn't happen. 
Here is a similar issue and it was fixed https://github.com/vuetifyjs/vuetify/issues/357
