### ISSUE TITLE
the homepage looks like lost iconts

### ISSUE THREAD

**Issue by ShuttleSpace** [vuetifyjs/vuetify#5970]
environment: MacOS Mojave 10.14.2,chrome  71.0.3578.98（正式版本） （64 位） either in safari.
here is a screenshot
![image](https://user-images.githubusercontent.com/6889653/50398366-ef7c0900-07b1-11e9-9891-13744032222a.png)

**Comment by sh7dm** [comment]
Try to refresh the page

**Comment by KaelWD** [comment]
- Any console errors?
- Does https://material.io/tools/icons load?
- Does https://fonts.googleapis.com/icon?family=Material+Icons load?

**Comment by lirunwin** [comment]
图标字体是再谷歌服务器上拿的。

**Comment by ShuttleSpace** [comment]
the material icons has loaded,but it still.

**Comment by ShuttleSpace** [comment]
![image](https://user-images.githubusercontent.com/6889653/50422934-33424180-088a-11e9-80ae-6e5321de3d4a.png)
![image](https://user-images.githubusercontent.com/6889653/50422940-40f7c700-088a-11e9-9092-018cb8ad61bf.png)
![image](https://user-images.githubusercontent.com/6889653/50422962-4bb25c00-088a-11e9-8534-8b02d7d9a1d0.png)
![image](https://user-images.githubusercontent.com/6889653/50422988-77354680-088a-11e9-8b93-08ccc2318ea8.png)

**Comment by ShuttleSpace** [comment]
I found the reason,the adguard block all of third fonts.
my fault,appology.
