### ISSUE TITLE
Vuetify autocomplete cannot change icon for showing/hiding menu

### ISSUE THREAD

**Issue by isaacnewtonfx** [vuetifyjs/vuetify#5971]
I have used the append slots to add two(2) icons to my v-autocomplete component and i have set callbacks on the icons but they seem to still hide and show the menu which is not what i want.

Is there a way to:
1. Change the icon that shows/hides the menu?
2. Prevent the default behavior of the default icon that shows/hides the menu?

I am hoping that this feature of controlling which button to show/hide the menu items can be added to bring more flexibility.

Check out my code below. Thanks

<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
  <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  

      <div id="app">
        <v-app id="inspire">
          <v-content>
            <v-container fluid fill-height>
              <v-layout align-center justify-center>
                <v-flex xs4>
                  
                                      
                        <template>
                          
                            
                            <v-autocomplete
                              prepend-inner-icon="menu"
                              :prepend-inner-icon-cb="prepend_sayHi"
                              v-model="model"
                              :items="items"
                              :loading="isLoading"
                              :search-input.sync="search"
                              chips
                              clearable
                              hide-details
                              hide-selected
                              item-text="name"
                              item-value="symbol"
                              label="Search for a coin..."
                              solo
                            >

                            <template slot="append">
                              <v-icon v-on:click.stop.prevent="append1_sayHi" left>search</v-icon>
                            </template>

                            <template slot="append">
                              &nbsp; &nbsp;
                            </template>

                            <template slot="append">
                              <v-icon v-on:click.stop.prevent="append2_sayHi" left>drive_eta</v-icon>
                            </template>

                              <template slot="no-data">
                                <v-list-tile>
                                  <v-list-tile-title>
                                    Search for your favorite
                                    <strong>Cryptocurrency</strong>
                                  </v-list-tile-title>
                                </v-list-tile>
                              </template>

                              <template
                                slot="selection"
                                slot-scope="{ item, selected }"
                              >
                                <v-chip
                                  :selected="selected"
                                  color="blue-grey"
                                  class="white--text"
                                >
                                  <v-icon left>mdi-coin</v-icon>
                                  <span v-text="item.name"></span>
                                </v-chip>
                              </template>

                              <template
                                slot="item"
                                slot-scope="{ item, tile }"
                              >
                                <v-list-tile-avatar
                                  color="indigo"
                                  class="headline font-weight-light white--text"
                                >
                                  {{ item.name.charAt(0) }}
                                </v-list-tile-avatar>
                                <v-list-tile-content>
                                  <v-list-tile-title v-text="item.name"></v-list-tile-title>
                                  <v-list-tile-sub-title v-text="item.symbol"></v-list-tile-sub-title>
                                </v-list-tile-content>
                                <v-list-tile-action>
                                  <v-icon>mdi-coin</v-icon>
                                </v-list-tile-action>
                              </template>
                            </v-autocomplete>
                            
                      
                        </template>

                </v-flex>
              </v-layout>
            </v-container>
          </v-content>

        </v-app>
      </div>
    

  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <script src="https://unpkg.com/vuetify/dist/vuetify.js"></script>

  <script>
    new Vue({
		  el: '#app',
		  data: () => ({
        isLoading: false,
        items: [{name:'Bitcoin',symbol:'B'},{name:'Ethereum',symbol:'E'},{name:'Litecoin',symbol:'L'}],
        model: null,
        search: null

		    }),
        watch: {
          search (val) {
            // Items have already been loaded
            if (this.items.length > 0) return

            this.isLoading = true

            // Lazily load input items
            window.axios.get('https://api.coinmarketcap.com/v2/listings/')
              .then(res => {
                this.items = res.data.data
              })
              .catch(err => {
                console.log(err)
              })
              .finally(() => (this.isLoading = false))
          }
        },
        methods:{
          prepend_sayHi(){
            alert("Prepend Hi")
          },
          append1_sayHi(e){
            //e.stopPropagation()
            alert("Append1 Hi")
          },
          append2_sayHi(e){
            //e.stopPropagation()
            alert("Append2 Hi")
          },
        }
		})
  </script>

</body>
</html>

**Comment by sh7dm** [comment]
@isaacnewtonfx Please use [Issue Creator](https://issues.vuetifyjs.com/) to create issues.

**Comment by sh7dm** [comment]
@isaacnewtonfx please create a new issue
