### ISSUE TITLE
Selects: currently selected menu item doesn't appear on top of the emitting element

### ISSUE THREAD

**Issue by MitchelLabonte** [vuetifyjs/vuetify#598]
### Steps to reproduce
- Have a select with multiple options
- Choose an option (not the first one) in the select
- Click on the select again to open the menu

### Versions
Vuetify 0.12.1

### What is expected ?
The currently selected menu item should appear on top of the emitting element.
I don't know if this isn't expected anymore, but I remember it used to act this way in an older version of Vuetify.
Also, it is in the Material Spec:: https://material.io/guidelines/components/menus.html#menus-behavior
"Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element."

### What is actually happening ?
The top of the menu is actually displayed on top of the emitting element.

### Reproduction Link
This can be seen in the first example here
https://vuetifyjs.com/components/selects

**Comment by johnleider** [comment]
This is in but bugged, being fixed on the fix/menu branch. (select uses the menu)
