### ISSUE TITLE
[Bug Report] v-combobox mask not working when set to multiple input 

### ISSUE THREAD

**Issue by curajorge** [vuetifyjs/vuetify#5981]
### Versions and Environment
**Vuetify:** 1.4.0-beta.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
when any input is given for value[ ] ex: "123456" for the mask "##-####"

### Expected Behavior
value[ "12-3456"]

### Actual Behavior
value[ "1", "2", "3" , "4" ,"5" , "6"]

### Reproduction Link
<a href="https://codepen.io/anon/pen/gZxYrB" target="_blank">https://codepen.io/anon/pen/gZxYrB</a>

### Other comments
this happens also with other input field that can take the multiple property

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
