### ISSUE TITLE
[Feature Request] Button Groups should disable option

### ISSUE THREAD

**Issue by matamune94** [vuetifyjs/vuetify#5989]
### Problem to solve
im using disable option for button in Button Groups , and it really not smooth if more than 50 button 

### Proposed solution
maybe vuetify team can add disable on Button Groups , i think it will be smooth more

**Comment by KaelWD** [comment]
> and it really not smooth if more than 50 button

Can you elaborate on this?

**Comment by badunius** [comment]
@KaelWD my case: user clicks some button in a group > I send a request > I don't want the user to click buttons in this group before I get a response.

v-btn-toggle doesn't have a loading prop (not convenient).
It also doesn't have a disabled prop.
Anyhow, I use it inside a wrapper, so I have to conditionally disable every button in the group.
