### ISSUE TITLE
(v-dialog - Form) I can't move dialog up or down when keyboard in mobile devices is visible

### ISSUE THREAD

**Issue by osmoramos** [vuetifyjs/vuetify#599]
**Versions**
Vuetify-Version: 0.12.1

**Reproduction Link**
Open from mobile device and test: https://vuetifyjs.com/components/dialogs

**Comment by johnleider** [comment]
It's a fixed element, you won't be able to move it on any device.

**Comment by osmoramos** [comment]
Do you have any recommendation?  Because when I need to fill a form in the bottom dialog the keyboard appear over the field and its not possible to type and view the content.

**Comment by mfferreira** [comment]
@osmoramos You could add some padding to the dialog when any of the inputs is focused on mobile devices.

**Comment by johnleider** [comment]
You could also use a scrollable dialog and reduce the height the dialog takes up. If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
