### ISSUE TITLE
[Feature Request] Add SplitPanel component

### ISSUE THREAD

**Issue by SGarno** [vuetifyjs/vuetify#5994]
### Problem to solve
For dynamically sized windows, there is currently no way to allow the user control the size of the content; it is all based on percentages set up initially.    There are many applications that enable the user to size the content panes to fit their workspace.

### Proposed solution
Create a new component SplitPanel that allows for content to be place in mutiple panels (vertically or horizontally) where the content adjusts appropriately.   [Here](https://github.com/bajaniyarohit/vue-split-panel) is a vuejs version of a control for this purpose.   It does not seem to work with vuetify, but the approach is good.

**Comment by jaxn** [comment]
I have a SplitPanel component in our app and would be happy to share the code. We specifically use it for a list/detail views where we want a left/right setup on tablet and above, and a full screen list down to detail, back up to list flow.

It works  well for messaging features or settings.

It's mostly just a component with two slots that get passed through to either the mobile view or the tablet+ view. 

For us, it ended up being more useful to have the detail panel as a nested router-view so that we could navigate directly to the appropriate message threat or setting from a notification or alert.

**Comment by BlackConure** [comment]
Sure.   If you would like to share the code.   I don't know if a router-view would work for me because my interface is actually a multi tabbed document style interface.

**Comment by jaxn** [comment]
@SGarno I was playing around with this a little more this weekend and put together an example of what we are currently doing: https://codesandbox.io/s/k5k85mz5n7

**Comment by nekosaur** [comment]
In what way does something like vue-split-panel not work with vuetify?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by softwareguy74** [comment]
Ah, that's too bad as splitter control is a pretty popular design paradigm for "enterprise" type apps.

**Comment by nscozzaro** [comment]
+1 would love to see this component

**Comment by nscozzaro** [comment]
@nekosaur I put together a CodeSandbox to show the responsivity/css issues I'm having using Vuetify with vue-split-panel: https://codesandbox.io/s/split-view-test-7mlx1

There are more details in the StackOverflow question I just made:
https://stackoverflow.com/questions/58355987/css-issues-with-vuetify-for-responsivity-using-vue-split-panel-and-select-border

**Comment by nekosaur** [comment]
Those issues wouldn't be fixed by having a native split panel either. Responsiveness is determined by browser width, not parent element width.

**Comment by nscozzaro** [comment]
@nekosaur okay, is there any "hack" that might be able to resolve the issue, e.g. wrapping in an iframe or something like that?

**Comment by sbernard31** [comment]
@johnleider, 

> After careful consideration the team has decided that this is not functionality that we are looking to implement **at this time.**

I understand "not for now but maybe later", correct ? 
Could you give us the reason about this ?

**Comment by johnleider** [comment]
It was and still is a bit of a niche component. These do and should exist in userland. If you have any additional questions reach out on Discord, https://community.vuetifyjs.com/
