### ISSUE TITLE
[Bug Report] Ripple effect triggered on an indirect click

### ISSUE THREAD

**Issue by mimischi** [vuetifyjs/vuetify#5999]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Firefox 64.0
**OS:** Mac OS 10.14

### Steps to reproduce
In the first list click on the vertical menu in the `<v-list-tile-action>` on the right.

### Expected Behavior
The ripple effect will be triggered only on the directly clicked `<v-btn>` component, not on the underlying `<v-list-tile>`.

### Actual Behavior
A ripple effect will be triggered on both the `<v-btn>` component of the vertical menu and on the `<v-list-tile>`.

### Reproduction Link
<a href="https://codepen.io/mimischi/pen/oJGbaL" target="_blank">https://codepen.io/mimischi/pen/oJGbaL</a>

### Other comments
The second list shows how I would it expect to behave, although it is missing the `ripple` property on the `<v-list-tile>` tag, so there is no ripple effect at all, when clicking the main list item.

I am not sure if the current behaviour is actual MD spec and I'm just wrong.

**Comment by KaelWD** [comment]
You can use `<v-list-tile-action @mousedown.stop>` to prevent the ripple.
