### ISSUE TITLE
Looking for iOS Testing

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#6]
I do not have an iOS device and could use some help from anyone that wouldn't mind doing some bug testing and iteration with me.

**Comment by weepy** [comment]
i can bug test if you like

**Comment by johnleider** [comment]
Essentially just use the documentation on an iOS device and post any bugs or irregularities that you find. Thank you!

**Comment by behnoodk** [comment]
These are a few things I noticed.

1. There is no sidebar or sidebar icon on iPad in portrait mode. (this is a big problem).
2. On iPhone (6s Plus), side menu won't close after tapping outside of it.(I have to tap one of the menu links for it close)
3. On iPhone (6s Plus), side menu closes after scrolling down or up.
4. On iPhone (6s Plus), Dropdown component wont close after tapping outside of it. one of the items has to be tapped for it to close.

I will update this issue if I find any more bugs on iOS.

by the way you can always use BrowserStack for testing on real devices. it is free for open source projects. 
https://www.browserstack.com/accounts/subscriptions
