### ISSUE TITLE
Can't set the v-modal dynamically

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#60]
Currently to bind a modal to an element one does:
`v-modal:myModalId`

In some cases the modal id could be set dynamically through a variable, so it would be useful to be able to set the modal with `v-modal="myModalId"`.

This change also brings more consistency to the framework directives.

**Comment by johnleider** [comment]
This functionality already exists, adding it to the modal directive. b2f99b2621a13d145f27be29e1de799385fb634d.
