### ISSUE TITLE
v-switch/v-radio doesn't detect v-model value

### ISSUE THREAD

**Issue by SystemZ** [vuetifyjs/vuetify#600]
Hi, does anyone have problem with those elements?
Maybe it's just something in my setup which induces this bug, strangely it's just this element is buggy.
All other elements are nice and bug free. Kudos for awesome 0.12 release :)

### Steps to reproduce
Click on switch or radio

### Versions

Vuetify v0.12.1, various browsers (Chrome, Firefox) and OS (Ubuntu, Android 6.0) doesn't seem to change this behaviour.

### What is expected ?
Switch should be active on true value, radio should be active on 'radio-1' value

### What is actually happening ?
Switch and radio are always inactive and click doesn't change value

![screenshot from 2017-05-25 01-43-30](https://cloud.githubusercontent.com/assets/1836094/26430133/9d9f7df8-40eb-11e7-94b5-08313ef11a27.png)

### Reproduction steps
```plain
git clone https://github.com/lvlup-pro/spawn-frontend-material.git
cd spawn-frontend-material
git checkout c4f58d7df59e5578557db6e2f9d7c894bad81b24
npm install && npm run dev
#visit http://127.0.0.1:8080/en/order
```

**Comment by johnleider** [comment]
Vuetify has a dependency of Vue@2.3.3 https://github.com/vuetifyjs/vuetify/blob/master/package.json#L79.

In particular, those components use a feature that was introduced with [Vue@2.2](https://github.com/vuejs/vue/releases/tag/v2.2.0) under the *Component v-model Customization* section. The repository linked was running on Vue@2.1.8. I attempted to upgrade to 2.3 but there were too many errors for me to sift to from the upgrade.

If you upgrade your package to the updated Vue and you can still produce this, just reply back here.

**Comment by SystemZ** [comment]
Vue upgrade to 2.2.6 solved this issue, thanks :+1: 
Upgrade to 2.3.x needs more work from me so it must wait.
