### ISSUE TITLE
[Bug Report] "rules" doesn't works on v-text-field with type="number"

### ISSUE THREAD

**Issue by lebesnec** [vuetifyjs/vuetify#6000]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
type an invalid number in the first field (since it's a number field you cannot type letters, so you can try something like `----`)

### Expected Behavior
field should display error message, like the one on the right.

### Actual Behavior
no error message under the field

### Reproduction Link
<a href="https://codepen.io/anon/pen/MZEvBZ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/MZEvBZ?&editable=true&editors=101</a>

### Other comments
"rules" on a v-text-field stop working if you add `type="number"` to the field.

**Comment by jacekkarczmarczyk** [comment]
That's how javascript works https://codepen.io/anon/pen/MZEryX

**Comment by douglasg14b** [comment]
@jacekkarczmarczyk 

That's an unhelpful, bordering on toxic reply and close. How is this `That's how javascript works`? The issue is that the custom error and styling *does not* work on the number input.

Other UI libraries have "error" styling for number inputs with rules, so it would seem reasonable that Vuetify would as well, especially given that other inputs are handled this way.

**Comment by lebesnec** [comment]
@douglasg14b 
A specific number field would be incredibly usefull in Vuetify, with number specific validations (min, max...), better styling for the decrease/increase button (currently it use the native one), and actually returning a number instead of a string.

**Comment by aburai** [comment]
returning a number instead of a string is implemented in vue `v-model.number="mynum"`

**Comment by nekosaur** [comment]
@douglasg14b An input with type number only emits an empty string if it can't parse the input, so there's no way for us to know what the invalid input is. The best you can do is check if it's an empty string. https://codepen.io/anon/pen/bJxaxO

@lebesnec That's a feature request unrelated to this issue

@aburai That is also unrelated to this issue

Please refrain from commenting on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) or reach out to us in our [Discord community](https://community.vuetifyjs.com).
