### ISSUE TITLE
[Feature Request] Time picker, "flat mode"

### ISSUE THREAD

**Issue by dawadam** [vuetifyjs/vuetify#6006]
### Problem to solve
Many components are available in "flat" mode to not display the shadow, but not this one.

### Proposed solution
The solution is to propose a property "flat" for this component which makes it possible to hide the shadow.

**Comment by jacekkarczmarczyk** [comment]
You can do `<v-time-picker class="elevation-0" />` but i agree that it could have a `flat` prop (or event `elevation`) for consistency

**Comment by heidricklevi** [comment]
I might give this one a shot

**Comment by MajesticPotatoe** [comment]
Elevation should receive the `flat` prop in 2.0 and any component using elevation should inherit it. 👍

**Comment by tobiaskohlbau** [comment]
Maybe it's a good idea to remove the label `good first issue` to avoid people trying to solve this without noticing the comments.

**Comment by jacekkarczmarczyk** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/pull/10362
