### ISSUE TITLE
[Bug Report] v-item-group/v-item incorrectly tracks active v-item

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#6014]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Firefox 64.0, Google Chrome
**OS:** Windows 7, Linux

### Steps to reproduce
Click the plus icon until you have three tabs. The last tab should be shown as active.
Click the minus icon. The first tab should be active. Instead the last tab is incorrectly being shown as active

### Expected Behavior
Click the minus icon. The first tab should be active.

### Actual Behavior
Click the minus icon. The last tab is incorrectly being shown as active

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/xmPjqM?editors=1111" target="_blank">https://codepen.io/uglyhobbitfeet/pen/xmPjqM?editors=1111</a>

**Comment by johnleider** [comment]
Fixed in f22d754
