### ISSUE TITLE
[Bug Report] Nomenclature unclear in v-treeview and documentation

### ISSUE THREAD

**Issue by SGarno** [vuetifyjs/vuetify#6015]
### Versions and Environment
**Vuetify:** 1.4.0-beta.0
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
See https://next.vuetifyjs.com/en/components/treeview

Documentation is not clear about what 'selected' vs 'checked' vs 'active' means and is a slight departure from UI/UX standard of what is identified as 'selected'.

### Expected Behavior
It seems to me that 'select' is more synonymous with 'active' and 'checked' is the term for managing the checkboxes and their state.   Should these be updated?

If this is not something that is doable or 'selected' is meant for a broader scope than just for checkboxes, perhaps more explanation of what terms mean for the tree view would clarify and help others to understand how the terminology is being applied; along with a simple checkbox example (in addition to "Custom selectable icons").

### Actual Behavior
The nomenclature used in v-treeview is confusing in that 'selectable' means the addition of a checkbox to the tree and 'active' means when you click on a node.   This is a departure from UI standards where you can 'select' a node whether or not it has a checkbox.   

When you disable checkboxes, can't you still select node(s)?

### Reproduction Link
<a href="https://codepen.io/anon/pen/KbyBeM?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/KbyBeM?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
`selectable` is as described `Will render a checkbox next to each node allowing them to be selected`
this is responsible for creating the checkboxes next to each node (purely cosmetic) 

`activatable`/`active` is as described `Allows user to mark a node as active by clicking on it`
this is responsible to the active state of the nodes

If you are only `activatable` you can still click on nodes and they will be marked 'active'
If you are only `selectable` you get checkboxes and can still mark nodes selected, but they can not be marked `active`

with that in mind, what would be your suggestions for rewording (I don't believe there is a `checked` prop). or would it be more or rewording of the props (or a combination of both).

**Comment by BlackConure** [comment]
I think the issue has to do with there being two different regions where the user can click, and therefore are not necessarily mutually exclusive.   In fact, I think it is quite OK to be able to select (activate) a node, but not necessarily mark it as checked.

Think of it this way:   Say your tree node shows a list of files that are in a directory.   Selecting (Activating) the node means you want to see the content in another pane.   Clicking on the checkbox of that node, however, means that you are going to use it (potentially) in a batch operation, such as copy or move.   They are not mutually exclusive.

That being said if you are going to treat them as exclusive, there should probably be something at the top of the component description that highlights this.    For me, I would consider separating them and using more common UI/UX nomenclature:

- Highlight/Hover means you are moving the mouse over the item (this is what you have now).
- Active means the node that is currently selected and is generally restricted to a single node
- Selected means you have clicked on one or more items and they are all highlighted
- Checked means the checkbox is enabled next to the node.

Take a look at the .NET framework [documentation for treeview](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview?view=netframework-4.7.2).   You will see they use 'Selected' and 'Checked'.   They don't use 'Active', but I have seen it to where it represents where the keyboard selection is.  If keyboard usage is enabled, it can have an 'Active' node that is different than Selected or Checked.   

Anyway, not sure where you are at in the release cycle, but at a minimum, I would say clarify at the top of the component description.   Better if it were to separate the two.

Hope that helps.

**Comment by BlackConure** [comment]
Oh, and by the way....It does actually work to have them both operating at the same time in the beta version, FWIW.   😄

**Comment by MajesticPotatoe** [comment]
its good info! It is a fairly new component and I believe there are some fixes slotted for 1.4 @nekosaur was the one that created it i believe, maybe have some stronger in-site as to the reason behind the nomenclature.

**Comment by nekosaur** [comment]
I agree that active vs selected could be more clear, and I did worry about their naming when creating the component. But could not come up with better terminology in the moment.

Majestic is incorrect though (as you noted) that they are exclusive. Nodes can be both active and selected at the same time. The reason it's not possible in the codepen you linked to is because the treeview is using the `open-on-click` prop, which _does_ prevent users from activating a node, since the click is used for opening a node, not setting it as active.

Selected state is managed through the v-model (which is in line with our other components that have checkboxes), while active state is managed through the `active.sync` prop.
