### ISSUE TITLE
[Feature Request] Emit show and close events from v-dialog

### ISSUE THREAD

**Issue by griest024** [vuetifyjs/vuetify#6016]
### Problem to solve
It is useful for me to hook into the show and close events of the dialog (close in particular is quite useful). For example I want to reset the dialog content to an initial state when the dialog is closed.

### Proposed solution
Emit show and close events from the dialog. It should be trivial, unless I'm missing something.

You could emit the close event [here](https://github.com/vuetifyjs/vuetify/blob/3920f0e19d5512899ac68bcb63ad63e74dfd1c55/packages/vuetify/src/components/VDialog/VDialog.js#L148) and the show event after [this line](https://github.com/vuetifyjs/vuetify/blob/3920f0e19d5512899ac68bcb63ad63e74dfd1c55/packages/vuetify/src/components/VDialog/VDialog.js#L166).

I can submit a PR if you are amenable to this feature.

**Comment by MajesticPotatoe** [comment]
you can accomplish this in userland simply by watching `v-model`.
see #4057

**Comment by yabuking84** [comment]
Use @input. 
<v-dialog 
@input="methodToExecuteWhenClosed()" 
:value="dialogData" 
lazy
scrollable>
....
