### ISSUE TITLE
Setting router to true on tabs component causes an error

### ISSUE THREAD

**Issue by qw3n** [vuetifyjs/vuetify#602]
### Steps to reproduce
Use :router="true" in `v-tabs-item`
### Versions

0.12.0
### What is expected ?

The `v-tabs-slider` working and no errors in the console
### What is actually happening ?

The route actually changes so content shows but the slider doesn't move and the following errors shows up in the console
```
[Vue warn]: Error in callback for watcher "activeIndex": "TypeError: e[0].componentInstance is undefined"
```
```
TypeError: e[0].componentInstance is undefined
Stack trace:
activeIndex@https://unpkg.com/vuetify/dist/vuetify.min.js:6:82437
```
If you log the activators before this line https://github.com/vuetifyjs/vuetify/blob/master/src/components/tabs/Tabs.js#L59 it exists, but its componentInstance is null. This is odd because if you check it here https://github.com/vuetifyjs/vuetify/blob/master/src/components/tabs/Tabs.js#L132 or in the render function both show a normal componentInstance object.
### Reproduction Link

I added two other cases that don't cause the problem. One with `v-tabs-content` added and one without the router prop being set to true.
http://jsfiddle.net/2657uxgs/

Here is a temporary workaround that creates a dummy `v-tabs-content` with its id tied to that of the current route http://jsfiddle.net/z3xkwgyc/

**Comment by johnleider** [comment]
Using your reproduction link, everything works correct with no errors. Am I missing something?

**Comment by qw3n** [comment]
The problem only appears to happen in Firefox. I tried it in Chrome and Edge and it works fine. But I get the error when using Firefox. I also tried it on a tablet with Firefox and the slider isn't moving so it looks like it only happens in Firefox.

I'm not sure then if this a vuetify, vue, or browser problem?

**Comment by johnleider** [comment]
Can confirm reproduction in firefox.
