### ISSUE TITLE
[Bug Report] Wrong positioning of tooltip in dialog

### ISSUE THREAD

**Issue by sandroden** [vuetifyjs/vuetify#6031]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.18
**Browsers:** Firefox 64.0
**OS:** Ubuntu undefined

### Steps to reproduce
A tooltip on an icon of a  v-card-actions does not position itself correctly

### Expected Behavior
The tooltip should place itself close to the icon

### Actual Behavior
The tooltip places itself in the center of the dialog, forcing it to scroll 
![immagine](https://user-images.githubusercontent.com/752776/50585173-0dadcd00-0e74-11e9-8986-52c91ef515ac.png)

### Reproduction Link
<a href="https://codesandbox.io/s/5w58w2k6l" target="_blank">https://codesandbox.io/s/5w58w2k6l</a>

### Other comments
In my real case, the tooltip is completely outside the dialog. I may have overlooked options for the correct positioning in which case mention in the docs would benefit. I saw other issues related to positioning but none of them seems to reflect this issue. In addition, It seems in this situation it doesn't honor the min-width prop.

**Comment by KaelWD** [comment]
The tooltip is missing a direction prop (top/bottom/left/right) and you also need a v-app component at the root of App.vue.

**Comment by sandroden** [comment]
Thanks, @KaelWD but that's not enough. In fact, I forgot that, in the codesandbox. Now I added v-app and the behaviour is identical as in my real application: the tooltip stays in the top of the page.

**Comment by KaelWD** [comment]
[Works for me](https://codesandbox.io/s/ywo646yn1z)

**Comment by sandroden** [comment]
@KaelWD you're right. Adding the "top" attribute now works. In my real environment that's not enought. Right now, adding the tooltip with no <span> does nothing (ok) adding <span> makes the icon button disappear. Its html  is moved out of the card-actions div and display is set to none...

**Comment by craigbroadbear** [comment]
I too get this problem when using tooltip inside a v-dialog.
