### ISSUE TITLE
[Bug Report] I cannot change the version of vuetify in the website at the top right anymore - it opens the github page now

### ISSUE THREAD

**Issue by Erik-Xtrapolate** [vuetifyjs/vuetify#6032]
### Versions and Environment
**Vuetify:** 1.4.0
**Last working version:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Firefox 64.0
**OS:** Linux

### Steps to reproduce
Open https://vuetifyjs.com/en/ and click on the version at the top right

### Expected Behavior
Present a dropdown to select the documentation version

### Actual Behavior
It opens the github repo

### Reproduction Link
<a href="https://jsfiddle.net/Erik_Xtrapolate/zcohw642/" target="_blank">https://jsfiddle.net/Erik_Xtrapolate/zcohw642/</a>

**Comment by sh7dm** [comment]
Seems like it isn't a bug. Sorry if I made a mistake, I'll reopen it if it's a bug.
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
