### ISSUE TITLE
[Bug Report] v-menu doesn't show content when value prop set to true

### ISSUE THREAD

**Issue by royprigat** [vuetifyjs/vuetify#6034]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Run the reproduction link

### Expected Behavior
When the v-menu's value prop is set to true, show the content it holds

### Actual Behavior
The v-menu does not open

### Reproduction Link
<a href="https://codesandbox.io/s/215o8lx1oy" target="_blank">https://codesandbox.io/s/215o8lx1oy</a>

### Other comments
This would work if the value prop is initialized to false, and then changed to true. But I am looking to manually trigger the v-menu without this condition.

**Comment by KaelWD** [comment]
Possible related to https://github.com/vuetifyjs/vuetify/issues/5890#issuecomment-450055389
