### ISSUE TITLE
[Bug Report] Navigation Drawer option to always show overlay regardless of screen width

### ISSUE THREAD

**Issue by PiusNyakoojo** [vuetifyjs/vuetify#6035]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
1. Create a navigation-drawer element
2. Set the prop value of stateless to false as follow: <v-navigation-drawer :stateless="false"></v-navigation-drawer>

### Expected Behavior
Always show the navigation-drawer overlay regardless of the screen width.

### Actual Behavior
Adding :stateless="false" will show the overlay until the width of the screen is greater than ~1270px, then the overlay will be hidden.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gZoXBy?editors=1010" target="_blank">https://codepen.io/anon/pen/gZoXBy?editors=1010</a>

### Other comments
Is there a way to tell the navigation-drawer to always show overlay? Even when the size of the screen is very large, I still want it to show the overlay. Thank you.

**Comment by sh7dm** [comment]
@PiusNyakoojo In your codepen it works as expected. If I change view and change width it hides overlay. 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Stateless is false by default, `temporary` will always show an overlay.

**Comment by PiusNyakoojo** [comment]
```html
<v-navigation-drawer temporary></v-navigation-drawer>
```

^ works as expected! Thank you @KaelWD

Also, I commend you all for your issue.vuetify.com project. Creating an issue was really easy to do and makes it straight-forward to provide you with the information you need.
