### ISSUE TITLE
[Bug Report]  Search not working

### ISSUE THREAD

**Issue by chtsngn** [vuetifyjs/vuetify#6036]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
- Open Docs
- Click 'Documentation' or 'Get Started'
- Open Nav Drawer (if applicable)
- Begin Typing in API Explorer

### Expected Behavior
Search

### Actual Behavior
Search doesn't work

### Reproduction Link

![vuetify-bug](https://user-images.githubusercontent.com/18267195/50597279-f690ce80-0eb7-11e9-89ea-f282bc1828cb.gif)

**Comment by MajesticPotatoe** [comment]
Known issue that is not related to vuetify. Searching is done by Algolia and takes at least 24hours to crawl and populate search results. There was major structural and file changes made to all of docs so may take some time.
