### ISSUE TITLE
[Bug Report] v-overflow-btn ignoring item-text option for display of selected item

### ISSUE THREAD

**Issue by bozzaj** [vuetifyjs/vuetify#6038]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
1. Create an array of objects each containing a text and value property
2. Create a v-overflow-btn that uses the array as the items property
3. Set item-text and item-value properties to the text/value property names
4. Select item from v-overflow-btn component

### Expected Behavior
The String in the property specified by item-text should be displayed, as it is with v-select

### Actual Behavior
The String in the property specified by item-value is displayed

### Reproduction Link
<a href="https://codepen.io/bozzaj/pen/mapXLM" target="_blank">https://codepen.io/bozzaj/pen/mapXLM</a>

**Comment by cheposki** [comment]
Same for me

**Comment by bad4iz** [comment]
Duplicateof #6394
