### ISSUE TITLE
Error when installing and running vuetifyjs.com

### ISSUE THREAD

**Issue by JorgeLuisMIPro** [vuetifyjs/vuetify#6042]
- The "https://github.com/vuetifyjs/vuetifyjs.com.git" repository no longer exists.

- Error trying to install and start an old version:
-- https://github.com/peluprvi/vuetifyjs.com
Error while executing:
/usr/bin/git ls-remote -h -t ssh://git@github.com/vuetifyjs/api-generator.git

- Error trying to install and start an new version:
-- https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetifyjs.com
code 404
404 Not Found: @vuetify/api-generator@^1.4.0

**Comment by MajesticPotatoe** [comment]
vuetifyjs.com repo no longer exists as everything has been merged to mono repo.
follow [contribution guide](https://vuetifyjs.com/en/getting-started/contributing) to install and start new environment. basics are as follows:
```
yarn
yarn build
yarn docs-dev (for docs)
yarn dev (for playground)
```
