### ISSUE TITLE
[Feature Request] Add `optional` prop to `<v-date-picker>`

### ISSUE THREAD

**Issue by eeriksp** [vuetifyjs/vuetify#6047]
### Problem to solve
Right now there is no easy way to make a `<v-date-picker>` optional. Once the value has been entered, it is possible to change it (by clicking to another date), but not to clear it.
The only exception I found was to add `multiple` prop,  but this does not suit for cases where you expect to get only one date or and empty field. 

### Proposed solution
When `multiple` prop is added, clicking again to a selected date will remove this date from selected options.
Similar behavior could be added by `optional` prop.
However, unlike `multiple` prop, it would still allow only one date to be chosen.

**Comment by haggys22** [comment]
If you use `VDatePicker` in combination with a `VTextField`, you can use the `clearable` prop on the text field.
In most use-cases, I assume, you don't use `VDatePicker` as a stand-alone.

https://codepen.io/anon/pen/qLojGX
