### ISSUE TITLE
[Bug Report] v-list-group collapse animation breaks in firefox

### ISSUE THREAD

**Issue by gamekingv** [vuetifyjs/vuetify#6049]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Firefox 64.0
**OS:** Windows 10

### Steps to reproduce
Use firefox and just open https://vuetifyjs.com/en/components/lists  to test v-list-group collopse animation. I also create a new firefox profile to test.

### Expected Behavior
When a list group closes, there should be a closing animation for the group list.

### Actual Behavior
The group list mostly closes with no animation. But when a group list closes by opening another group list, the closing animation is ok.

### Reproduction Link
<a href="https://codepen.io/anon/pen/zyRLOY" target="_blank">https://codepen.io/anon/pen/zyRLOY</a>

### Other comments
I had tried 1.0.19 version and the closing animation is fine in firefox. There's not such problem in chrome and edge with 1.4.0 version.

**Comment by johnleider** [comment]
Possibly related to #6102
