### ISSUE TITLE
[Feature Request] Add TextArea as input type for Combobox

### ISSUE THREAD

**Issue by tasoskn** [vuetifyjs/vuetify#6055]
### Problem to solve
It would be very nice if you could choose the input type of the combobox between text-field (which is the only option right now) and textarea.

I tried changing the files inside the es5/components, but nothing seems to work.
I even ended up manipulating the v-textfield files, just trying to set the default behaviour of v-text-field to textarea. Inside the index.js i set `textarea:true` instead of `textarea:Boolean` and even changed  `([0, _console.deprecate)('<v-text-field textarea>', '<v-textarea outline>, wrapper, parent) ` to `([0, _console.deprecate)('<v-text-field>', '<v-textarea outline>, wrapper, parent) `
### Proposed solution
It would be great if you could choose the input type by just setting an atrribute, something like `<v-combobox textarea></v-combobox>`

**Comment by r00nscapenab** [comment]
is this already solved?

**Comment by gopalkriagg** [comment]
I will like to use this feature too!

**Comment by Tomer-Alony** [comment]
Hi, was it solved?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
