### ISSUE TITLE
[Feature Request] Fixed background for parallax

### ISSUE THREAD

**Issue by sh7dm** [vuetifyjs/vuetify#6056]
### Problem to solve
Add option to `VParallax` which will set `backgroud-attachment: fixed`

### Proposed solution
Add new `VParallax` option: `fixed`, which will set `backgroud-attachment: fixed`.

**Comment by sh7dm** [comment]
This is good for beginner.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
