### ISSUE TITLE
[Bug Report] Even with faSvg Vuetify still renders <i> rather than <svg>

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#6065]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.20
**Browsers:** Chrome 72.0.3626.28
**OS:** Windows 10

### Steps to reproduce
I follow everything like [here](https://vuetifyjs.com/en/framework/icons#install-font-awesome-svg-icons) i.e.:
```
...
Vue.use(Vuetify, {
  iconfont: "faSvg", 
```

### Expected Behavior
Expect for component to render as svg

### Actual Behavior
Rather than `svg` component gets rendered like this: `<i aria-hidden="true" class="v-icon fas fa-angle-double-up theme--dark"></i>`

### Reproduction Link
<a href="https://codesandbox.io/s/o14vnjq66" target="_blank">https://codesandbox.io/s/o14vnjq66</a>

**Comment by KaelWD** [comment]
`iconfont` only affects components like v-checkbox, you still need to use the correct syntax in v-icon. That link also doesn't reproduce the issue and appears to have lots of unrelated code.

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
