### ISSUE TITLE
[Feature Request] Material banners

### ISSUE THREAD

**Issue by meyt** [vuetifyjs/vuetify#6068]
### Problem to solve
> A banner displays an important, succinct message, and provides actions for users to address (or dismiss the banner). It requires a user action to be dismissed. 

![mio_design_assets_147rjhtnyn2jvq](https://user-images.githubusercontent.com/10482278/50735762-2f3aeb80-11c9-11e9-80c2-dd04a49bd14e.gif)
![image](https://user-images.githubusercontent.com/10482278/50735788-7cb75880-11c9-11e9-8834-8b8f2ba3ea6b.png)

### Proposed solution
https://material.io/design/components/banners.html

**Comment by jaxn** [comment]
I'd be happy to help with this one. I have a banner sfc component in our app and would like to refactor it to use Vuetify mixins anyway.

Based on my experience and understanding of the MD spec,  `v-banner` should have an `app` prop that `v-content` respects.

**Comment by johnleider** [comment]
@jaxn just link up with me in the community.

**Comment by johnleider** [comment]
This is currently in alpha.6.
