### ISSUE TITLE
[Feature Request] Extended Floating Action Button

### ISSUE THREAD

**Issue by heath3n** [vuetifyjs/vuetify#6070]
### Problem to solve
The Material Design spec describes the concept of an [extended FAB](https://material.io/design/components/buttons-floating-action-button.html#extended-fab). I currently have need for this component as it provides linguistic reinforcement or clarification of an icon's action (such as that of the ambiguous ＋) and feel it should be included anyway for completeness.

I realize this can be faked with the existing button component but it would be nice if a prop existed so there was no manual effort involved in checking screen sizes to shrink the button appropriately, modify speed dial appearance, etc.

### Proposed solution
Add a `fab-extended` property to the existing `<v-btn>` component. In most cases, all this should do is elongate the button but note from the spec that the button shrinks to normal size under certain circumstances (scrolling, viewport resized) and speed dial items gain an extended view on hover.

**Comment by jaminroe** [comment]
Yes please, we've been using this in our desktop app designs, and it's been especially helpful. Right now, we have to make our own custom Extended FAB

**Comment by jaminroe** [comment]
@sh7dm @MajesticPotatoe what's the workflow like for these feature requests? I see that it was removed for Vuetify 2.0, so is there some timeline for that? I'm assuming that we need some folks who can contribute to a PR for this, correct?

**Comment by sh7dm** [comment]
@johnleider when do you want to implement this one?

**Comment by jacekkarczmarczyk** [comment]
Something like this? https://codepen.io/anon/pen/NoyONE?editors=1000

**Comment by sh7dm** [comment]
@jacekkarczmarczyk looks good!

**Comment by jaminroe** [comment]
@jacekkarczmarczyk that looks too narrow and the elevation isn't high enough. An Extended FAB isn't the same specs as a button. Make sure to cross check with the Material guidelines: 
https://www. material.io/design/components/buttons-floating-action-button.html

**Comment by sh7dm** [comment]
@jaminroe I already have done it the correct way, it is compatible to md2 and I will finish some work and open PR today

**Comment by MajesticPotatoe** [comment]
@jaminroe just noting that it wasn't removed from 2.0, was just moved from one list and put in another (we were just reorganizing issues between projects). still slotted for 2.0 👍

**Comment by johnleider** [comment]
We are most definitely going to implement this, didn't make the timeline cut for v2.0 release.

**Comment by Dev1lDragon** [comment]
its will be good if you can implement something like this: [Extended FAB speed dial](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Jmstk1Jw6xAnO4IY1dbE9morbTzcNzSY%2Fextended-fab-behavior-speeddial.mp4), its from.[Buttons: floating action button - Material Design](https://www.material.io/design/components/buttons-floating-action-button.html#extended-fab).

My fast interpretation: https://codepen.io/dev1ldragon/pen/Wqqvav

**Comment by jaminroe** [comment]
> its will be good if you can implement something like this: [Extended FAB speed dial](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Jmstk1Jw6xAnO4IY1dbE9morbTzcNzSY%2Fextended-fab-behavior-speeddial.mp4), its from.[Buttons: floating action button - Material Design](https://www.material.io/design/components/buttons-floating-action-button.html#extended-fab).
> 
> My fast interpretation: https://codepen.io/dev1ldragon/pen/Wqqvav

The only thing I disagree about this interpretation is that it's not supposed to change between a regular FAB and an Extended one. That is not a pattern in the Material Design system.

Looking forward to seeing this added in the future. 😃

**Comment by heath3n** [comment]
> The only thing I disagree about this interpretation is that it's not supposed to change between a regular FAB and an Extended one. That is not a pattern in the Material Design system.

@jaminroe Usually not, but see the speed dial example under the "Behavior" section: https://material.io/design/components/buttons-floating-action-button.html#extended-fab

**Comment by clementmas** [comment]
> We are most definitely going to implement this, didn't make the timeline cut for v2.0 release.

Any news on this feature? Will it make the cut for the 2.2 release? Thanks!

**Comment by jorisdemange** [comment]
Still looking for this feature

> We are most definitely going to implement this, didn't make the timeline cut for v2.0 release.

Still looking for this essential feature. Any news?

**Comment by hugodecasta** [comment]
> > We are most definitely going to implement this, didn't make the timeline cut for v2.0 release.
> 
> Still looking for this essential feature. How is it going?

Still nothing on this feature ?

**Comment by ashish141199** [comment]
This is how I do it:
**VUE**
```
<v-slide-y-transition>
      <v-btn
        color="primary"
        v-if="!isLoading && !currentUser.is_student"
        @click="showCreationOptions = true"
        dark
        right
        bottom
        fixed
        class="extended-fab"
        fab
      >
        Extended FAB
      </v-btn>
</v-slide-y-transition>
```
**CSS:**
```
.extended-fab {
  width: auto !important;
  border-radius: 100px !important;
  padding-left: 15px !important;
  padding-right: 15px !important;
}
```

**Comment by johnleider** [comment]
[`v-fab`](https://vuetifyjs.com/en/components/floating-action-buttons/) is now it's own component and is currently in labs.

https://play.vuetifyjs.com/#eNpNjsEKg0AMRH8l5OKldi89FVvopT/R7WHVCMKuG3ajFMR/b6oVvAwZ8jKT14w5NebBfJ5GwitWQoG9E7rbAaCaSse8jmrafoLGu5xvFoMrL8AqFv/rle5cDUIfUeIZY+2SRVBLQ0stmD3IaNKWb/aCyhyK1eYm9SyQScatvw8ck8AMiTpYoEsxQKE/F7/bjVYOl9Mwer/K+wuVTUjB
