### ISSUE TITLE
[Bug Report] Text field component mask: special symbol mask 'X' doesn't work

### ISSUE THREAD

**Issue by cmrd-senya** [vuetifyjs/vuetify#6071]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Firefox 64.0, Google Chrome
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
1. Create a text field component with a mask containing "X" mask character
2. Try to input any special character on the respective place in the text field, for instance '-'

### Expected Behavior
The special character is added to the text field

### Actual Behavior
No character is added to the text field

### Reproduction Link
<a href="https://jsfiddle.net/5hLovjq7/" target="_blank">https://jsfiddle.net/5hLovjq7/</a>

### Other comments
"X" mask for text field described at the vuetify documentation: https://vuetifyjs.com/ru/components/text-fields

**Comment by MatthewAry** [comment]
Thanks! Was going to file this as a bug too.

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
