### ISSUE TITLE
[Bug Report] Alert Dismissible Icon double-left padding

### ISSUE THREAD

**Issue by jondmoon** [vuetifyjs/vuetify#6072]
### Versions and Environment
**Vuetify:** 1.4.0
**Last working version:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 72.0.3626.28
**OS:** Windows 10

### Steps to reproduce
Used the first dismissible example from the documentation

### Expected Behavior
Expected left margin on dismiss icon to be 16px

### Actual Behavior
Left margin on dismiss icon is 32px (adds 16px left margin to both the i.v-icon--right and a.v-alert__dismissible; used to not be on the icon but just the parent).

### Reproduction Link
<a href="https://codepen.io/anon/pen/qLKObe?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/qLKObe?&editable=true&editors=101</a>

### Other comments
This throws off some of my messages when upgrading to 1.4. It's not the end of the world, but alert messages that didn't used to wrap at a particular screen size now wrap.

**Comment by johnleider** [comment]
Caused by f8de29d. Suggest use a workaround until v2.0 as alerts have been completely refactored and with the introduction of the margin for left/right icons, we can't remove that now.

Sorry for the inconvenience.

```css
.v-alert__dismissible > .v-icon {
  margin-left: 0;
}
```
