### ISSUE TITLE
[Bug Report] Pre-made layouts page returns 404

### ISSUE THREAD

**Issue by tamalsaha** [vuetifyjs/vuetify#6073]
### Versions and Environment
**Vuetify:** 1.4.0
**Last working version:** 1.3.16
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
Visit https://vuetifyjs.com/en/framework/pre-made-layouts (v1.4.0)

### Expected Behavior
This page should render.

### Actual Behavior
Returns 404

### Reproduction Link
<a href="https://github.com/tamalsaha/vuetifyjs-bugs/blob/master/pre-made%20layouts%20404.png" target="_blank">https://github.com/tamalsaha/vuetifyjs-bugs/blob/master/pre-made%20layouts%20404.png</a>

**Comment by MajesticPotatoe** [comment]
This has been resolved.
