### ISSUE TITLE
[Bug Report] data table example toggleAll fires twice

### ISSUE THREAD

**Issue by wanpeng2008** [vuetifyjs/vuetify#6077]
In example  https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetifyjs.com/src/examples/data-tables/headers.vue

Ln19: @click="toggleAll" will cause toggleAll trigger twice

should use @click.stop="toggleAll" instead

**Comment by sh7dm** [comment]
@wanpeng2008 open the PR (pull request). Fork repo and create a **NEW BRANCH** out of `master` for bug fixes or `dev` for new features. **Please don't work on `master` or `dev` branch of your fork**. Read more [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by MajesticPotatoe** [comment]
@wanpeng2008 @sh7dm no need, I will take care of it.

**Comment by MajesticPotatoe** [comment]
resolved in https://github.com/vuetifyjs/vuetify/commit/233506f
Thank you for your contribution and support for vuetify!

**Comment by sh7dm** [comment]
@MajesticPotatoe thanks for your fix!
