### ISSUE TITLE
[Feature Request] Filter props for v-treeview

### ISSUE THREAD

**Issue by koldka** [vuetifyjs/vuetify#6078]
### Problem to solve
It will filter the treeview according to the filter field. It would homogenize filter behavior.
https://codepen.io/anon/pen/PXeMmy?&editors=101

In this exemple when I search "Calen", only "Application -> Calendar" is visible. Until now, it's what I want.

But when I select "Calendar", "Application" is also selected; and when I clear the filter, all the children of "Application" are selected too. And I'd like to select "Calendar" and when I clear I don't want its siblings to be selected. Maybe I should mention this as a Bug instead of Feature Request.

Thank you for reading

### Proposed solution
Adding a v-text-field on the top/bottom of the treeview that will filter correctly.

**Comment by nekosaur** [comment]
filtering for treeview will be tracked in https://github.com/vuetifyjs/vuetify/issues/5621

**Comment by koldka** [comment]
ok, thank you
