### ISSUE TITLE
[Bug Report] v-data-table : Documentation - fix slot name "page-text" with "pageText"

### ISSUE THREAD

**Issue by Rouche** [vuetifyjs/vuetify#6082]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
https://vuetifyjs.com/en/components/data-tables
slot
property page-text (Code example have pageText) a bit misleading.

### Expected Behavior
pageText

### Actual Behavior
page-text

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
no code pen needed

**Comment by Rouche** [comment]
taken care off #6081

**Comment by MajesticPotatoe** [comment]
Going to re-open this. Needs to be reviewed a little more. Seems that the api-generator parses as `page-text` however the actual prop is `pageText`.

**Comment by MajesticPotatoe** [comment]
example resolved in https://github.com/vuetifyjs/vuetify/commit/88854d9b55fa2a46740d519e45c03bfd2223acce
