### ISSUE TITLE
[Feature Request] Alert Dismissible icon should allow for dismissal via keyboard

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#6084]
### Problem to solve
Currently it appears that the dismissible alert does not allow a user to focus on it via keyboard usage.
![vuetifydismissiblealertnofocus](https://user-images.githubusercontent.com/1302542/50861252-17e53500-1366-11e9-97b5-b4b354c60b8d.gif)

### Proposed solution
Changing the icon to use the button element instead of a link.

![vuetifydismissiblealertwithfocus](https://user-images.githubusercontent.com/1302542/50861297-31867c80-1366-11e9-9aa0-9729f078f98e.gif)

**Comment by johnleider** [comment]
Resolved in 01c5a5b1ef3268dbea5a7c1f21c208c8cca98566

**Comment by blalan05** [comment]
This is available in the 2.0 alpha.
