### ISSUE TITLE
Adding support for unofficial Material Design icons

### ISSUE THREAD

**Issue by walleXD** [vuetifyjs/vuetify#609]
Hi,

It seems the icon component has support for Font Awesome icons. Would it be possible to add [Material design icons](https://materialdesignicons.com/), a repository of unofficial material themed icons? Its similar to font-awesome when it comes to handling classes and it used the mdi class for its icons.

Thanks

**Comment by walleXD** [comment]
It seems #19 also refers to the same Material Design Icons. The implementation would be very similar to the one for font awesome and the only difference would be the mdi class instead of fa and everything else more or less remains the same. @johnleider what do you think?

**Comment by johnleider** [comment]
Yup, sounds good.
