### ISSUE TITLE
transitions is not exported, docs suggest to import

### ISSUE THREAD

**Issue by atilkan** [vuetifyjs/vuetify#6093]
Docs suggest this:

`import Vuetify, {
  VApp,
  VNavigationDrawer,
  VFooter,
  VToolbar,
  transitions
} from 'vuetify/lib'`

https://vuetifyjs.com/en/framework/a-la-carte

It is not exported. Throws error.

**Comment by KaelWD** [comment]
Transitions are individual components now, `VFadeTransition`

**Comment by MajesticPotatoe** [comment]
updated in https://github.com/vuetifyjs/vuetify/commit/476a999636ecf43ce4e750448e877ca53dbef650
