### ISSUE TITLE
[Feature Request] hope can add tag-like components

### ISSUE THREAD

**Issue by bluelovers** [vuetifyjs/vuetify#6095]
### Problem to solve
hope can add tag-like components

it maybe looks like a small button
but a little not same

can see here
https://www.iviewui.com/components/tag-en

### Proposed solution
https://www.iviewui.com/components/tag-en

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/chips

They will be getting an overhaul soon for the material design spec update.
