### ISSUE TITLE
[Feature Request] v-model type of v-text-field with prop type="number" may be a number

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#6096]
### Problem to solve
When we use `v-text-field` with prop `type="number"`, the `v-model` value still be a string (formated as a number, but it still be a string).
It's painful when we use TypeScript and when we expect a number.
If the v-model was directly a number, it would be more confortable.

### Proposed solution
`v-model` of a `v-text-field` with `type="number"` must be a `number`, not a `string`

### Example
https://codepen.io/Tuffy45/pen/XoPBQy

**Comment by KaelWD** [comment]
This reflects the native behaviour, use `v-model.number` otherwise.

**Comment by dpaquette** [comment]
Is this documented anywhere? Binding to `v-model.number` works but I had a really hard time finding the solution.
