### ISSUE TITLE
[Bug Report] Class elevation less than 2 doesn't work

### ISSUE THREAD

**Issue by CyberTopTuK** [vuetifyjs/vuetify#6098]
### Versions and Environment
**Vuetify:** 1.4.1
**Last working version:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
Use card component with class elevation-1 or elevation-0

### Expected Behavior
With elevation-0 there should not be box-shadow.

### Actual Behavior
With elevation-0 there box-shadow from elevation-2 class.

### Reproduction Link
<a href="https://codesandbox.io/embed/pjrmp4vrp0" target="_blank">https://codesandbox.io/embed/pjrmp4vrp0</a>

**Comment by KaelWD** [comment]
Seems like you have to use the elevation prop now instead, because cards use `class="elevation-2"` internally if it's not set. @johnleider

**Comment by DmytroDiachuk** [comment]
> Seems like you have to use the elevation prop now instead, because cards use `class="elevation-2"` internally if it's not set. @johnleider
 
It must works according documentation  https://vuetifyjs.com/en/framework/elevation    (Current playground does not work correct now)

> The elevation helpers allow you to control relative depth, or distance, between two surfaces along the z-axis. There is a total of 25 elevation levels. You can set an element's elevation by using the class elevation-{n}, where n is a integer between 0-24 corresponding to the desired elevation.

If I use  "elevation-0 or elevation-1"  my v-card  must change shadows.  It was good, but not now!

**Comment by aburai** [comment]
@DmytroDiachuk 

`<v-card class="pa-3" elevation="0"> <HelloWorld /> </v-card>`
or just
`<v-card class="pa-3" flat> <HelloWorld /> </v-card>`

it works this way, playground must be updated

**Comment by DmytroDiachuk** [comment]
Helper class "elevation-**n**" must have the same behavior for all elements same, where I can add shadows. For Example **"elevation-1"**: 
`<v-btn class="elevation-1"></v-btn>`
`<div class="elevation-1></div>`  
**`<v-card class="elevation-1></v-card>`**  -  _not working_

@aburai, Why `<v-card`  must be exclusion?? I don't understand this conception...

**Comment by aburai** [comment]
@DmytroDiachuk i don't know, i just search for a solution
