### ISSUE TITLE
Can not bind v-on:click event with v-btn

### ISSUE THREAD

**Issue by efootstep** [vuetifyjs/vuetify#61]
This is my html

>   <v-row>
>       <v-col lg5 >
>         <v-btn success v-on:click="filteredclcik">Submit</v-btn>
>       </v-col>
>     </v-row>
> 

This is my script

> 
> <script>
> export default {
>   name: 'dappForm',
>   data () {
>     return {
>     msg:"Dapps Form"
>     }
>   },
>   methods: {
>     filterClick: function () {
>       alert("test");
>     }
>   },
> }
> </script>

**Comment by yoyo930021** [comment]
@efootstep 
I have a same problem.
In doc, use `v-on:click.native` to instead of `v-on:click`

**Comment by efootstep** [comment]
Wow! it is working, Thanks for quick response. You saved my whole day.
