### ISSUE TITLE
[Bug Report] Expansion panel animation with 1 item

### ISSUE THREAD

**Issue by Tiagosophy** [vuetifyjs/vuetify#6102]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Click on "open" and "close" repeatedly.

### Expected Behavior
Smooth contract 

### Actual Behavior
Some times the close animation don't happen.

### Reproduction Link
<a href="https://codepen.io/tiagoxavi/pen/EGdjbZ" target="_blank">https://codepen.io/tiagoxavi/pen/EGdjbZ</a>

**Comment by johnleider** [comment]
This is indicative of how expand-transition behaves when working with elements that use `v-show`. @KaelWD I looked into this and the only reproduce-able step was having only 1 element. 2 or more and the transition works fine.

**Comment by KaelWD** [comment]
2 elements worked because the other one would call a reflow at the same time.
