### ISSUE TITLE
[Bug Report] v-touch error [Vue warn]: Failed to resolve directive: touch

### ISSUE THREAD

**Issue by TheFrogDaddy** [vuetifyjs/vuetify#6104]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
1. Create vue-cli project (choose default mode)
    ```
    vue create vue-touch-test
    ```

2. Navigate to new project
    ```
    cd vue-touch-test
    ```
3. Add vuetify via vue-cli plugin (choose default mode)
    ```
    vue add vuetify
    ```
4. Replace HelloWorld.vue component contents with the following _(from the v-touch documentation)_
    ```
    <template>
    <v-container>
        <v-layout
        v-touch="{
        left: () => swipe('Left'),
        right: () => swipe('Right'),
        up: () => swipe('Up'),
        down: () => swipe('Down')
        }"
        column
        align-center
        justify-center
        style="height: 500px"
        class="grey lighten-2"
    >
        <v-subheader>Swipe Direction</v-subheader>
        {{ swipeDirection }}
    </v-layout>
    </v-container>
    </template>

    <script>
    export default {
        data: () => ({
        swipeDirection: 'None'
        }),

        methods: {
        swipe (direction) {
            this.swipeDirection = direction
        }
        }
    }
    </script>
    ```
5. Build and run project
    ```
    yarn serve
    ```
6. Browse site on desktop and inspect console
7. Demo does not work. See error in console
    > [Vue warn]: Failed to resolve directive: touch

### Expected Behavior
To be able to replicate the demo on documentation page https://vuetifyjs.com/en/directives/touch-support

### Actual Behavior
Demo does not funtion and error in console (When in src mode).
[Vue warn]: Failed to resolve directive: touch

### Reproduction Link
<a href="https://codepen.io/TheFrogDaddy/project/editor/DakRJL" target="_blank">https://codepen.io/TheFrogDaddy/project/editor/DakRJL</a>

**Comment by MajesticPotatoe** [comment]
The `default` when you use `vue add vuetify` includes tree shaking by default (a-la-carte). If you would like to use directives with this you will need to import them manually. Alternatively you can still install with the `vue add vuetify` command you will just need to select the 'Configure (advanced)` option and choose not to use a-la-carte

**Comment by TheFrogDaddy** [comment]
Ah, sorry. I incorrectly thought that view-loader would automatically pick that up as it had been for my components. Thanks.

**Comment by jacekkarczmarczyk** [comment]
@TheFrogDaddy https://github.com/vuetifyjs/vuetify-loader/commit/a92e5595717f2dce2c2715bccff7edbfddea7946
