### ISSUE TITLE
[Bug Report] When using FAQ-suggested faked v-app, vuetify-theme-stylesheet does not exist

### ISSUE THREAD

**Issue by DaleMatthews** [vuetifyjs/vuetify#6106]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Due to the nature of the web app I'm working on, I cannot mount Vue at a high-level element, so I can't use the v-app component. Therefore I'm using the suggested alternative in the FAQ, but that causes the theme styles to never be created since it's a mixin for the v-app component.
https://vuetifyjs.com/en/getting-started/frequently-asked-questions#my-application-does-not-look-correct

### Expected Behavior
Vuetify theme styles are created

### Actual Behavior
Vuetify theme styles are not created

### Reproduction Link
<a href="https://codepen.io/emerson-matthews/pen/LMgxav" target="_blank">https://codepen.io/emerson-matthews/pen/LMgxav</a>

### Other comments
Also the FAQ says to use "application--light" but I think it means "theme--light"

**Comment by KaelWD** [comment]
This should hopefully be possible in a future release: https://github.com/vuetifyjs/vuetify/compare/refactor/bootstrap-process

**Comment by MajesticPotatoe** [comment]
docs updated in https://github.com/vuetifyjs/vuetify/commit/9f83197
