### ISSUE TITLE
[Feature Request] multiple progress bar

### ISSUE THREAD

**Issue by hiravebapu** [vuetifyjs/vuetify#6108]
### Problem to solve
include multiple progress segments into one. ex. 20% failed, 50% pass, 30% waiting = total 100%

### Proposed solution
something like in bootstrap: 
https://getbootstrap.com/docs/4.2/components/progress/#multiple-bars

**Comment by NicoAiko** [comment]
Any updates here?

**Comment by Kotoriii** [comment]
Would also love this to be added

**Comment by DimmuR** [comment]
Any chances for this to be implemented?

**Comment by johnleider** [comment]
We may revisit this in the future with a progress-linear rewrite or new component.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by frostycoles** [comment]
Similar to @mads03dk I opted to just hack my own together using v-sheets:
```
<script setup lang="ts">
defineProps<{total: number, value1: number, value2?: number, height?: string}>();
</script>
<template>
  <v-sheet width="100%" :height="height || '5px'" color="grey-lighten-3" class="d-flex my-4 rounded-xl overflow-hidden">
    <v-sheet color="success" height="100%" :width="`${value1 / total * 100}%`" />
    <v-sheet v-if="value2" color="primary" height="100%" :width="`${value2 / total * 100}%`" />
  </v-sheet>
</template>
```
