### ISSUE TITLE
[Bug Report] v-layout[column] nested v-flex max-width overrides breakpoint max-width

### ISSUE THREAD

**Issue by kurbar** [vuetifyjs/vuetify#6109]
### Versions and Environment
**Vuetify:** 1.3.16
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
Reproduceable example in Codepen

### Expected Behavior
Image width would be based on `v-flex` breakpoints max-width.

### Actual Behavior
`v-flex` breakpoints max-width is overridden by `.layout.column>.flex`

![alt text](http://snappyimages.nextwavesrl.netdna-cdn.com/img/a337a67253733f7d38f6ff9c2762c8b9.png "Chrome Dev Tools")

### Reproduction Link
<a href="https://codepen.io/anon/pen/ebPKxd" target="_blank">https://codepen.io/anon/pen/ebPKxd</a>

### Other comments
If I remove the the `max-width` rule in `.layout.column>.flex` it works as expected.

**Comment by KaelWD** [comment]
Don't use `column` then.

**Comment by kurbar** [comment]
If I am after `flex-direction: column;` how is that intended? Please elaborate.

**Comment by KaelWD** [comment]
#3470, #2888

Why do you need a column in this case? There's nothing else in the v-layout so the direction doesn't make a difference.

**Comment by AlissonRS** [comment]
@KaelWD I believe what kurbar wants is to display `v-flex` components vertically (hence column layout) without full width (e.g respecting the v-flex breakpoints).

Consider this:

```
<v-layout column>
  <v-flex xs12 sm6 md4>
  </v-flex>
  <v-flex xs12 sm6 md4>
  </v-flex>
</v-layout>
```

Here the sm6 and md4 are ignored and overriden by the layout = column. See this screenshot:

![image](https://user-images.githubusercontent.com/4753901/56014779-0563fa00-5ccd-11e9-9bf1-19943f10158c.png)

In bootstrap 3.x the equivalent of what kurbar wants would be something like:

```
<div class="container">
  <div class=row>
    <div class="col-sm-6 col-md-4">
    </div>
  </div>
  <div class=row>
    <div class="col-sm-6 col-md-4">
    </div>
  </div>
</div>

```
I'm not css expert, I know Vuetify grid system relies on flex, but is this possible to be done somehow using Vuetify grid system?

**Comment by KaelWD** [comment]
In that case you could just use a div instead of the v-layout, and the v-flex is sized with max-width.
