### ISSUE TITLE
 Biding $event to @blur, @click or @focus not working

### ISSUE THREAD

**Issue by dacastro4** [vuetifyjs/vuetify#611]
When I try to do this 
`<v-text-field @focus="onFocus($event)"></v-text-field>`
```javascript
...
onFocus(event) {
     console.log(event)
}
...
```
Console log returns `undefined` so I don't have the event

https://jsfiddle.net/dacastro4/h3mgkjjc/5/

**Comment by cawa-93** [comment]
Biding `$event` to `@click.native` work. 
https://jsfiddle.net/nqf7omvz/1/

**Comment by dacastro4** [comment]
@cawa-93 yep, works great with click but I need the event on focus because if the user 'tabs' to switch between inputs it won't work.

**Comment by smares** [comment]
@focus.native works too.

**Comment by johnleider** [comment]
I assume that you need the event as blur/focus as events already work. This will now properly pass up the blur/focus event objects.
