### ISSUE TITLE
[Question] CSS Grid

### ISSUE THREAD

**Issue by MrJmpl3** [vuetifyjs/vuetify#6117]
I need use CSS Grid in my template.

Can I replace the v-container . v-layout , v-flex instead to CSS Grid?

Any problem in the future?

**Comment by KaelWD** [comment]
No, the grid system uses flexbox. Use grid yourself if you want to. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
