### ISSUE TITLE
Vuetify Website down?

### ISSUE THREAD

**Issue by aksappy** [vuetifyjs/vuetify#6119]
Website seems to be down.

![image](https://user-images.githubusercontent.com/4348461/51057703-5bcd7980-15b4-11e9-9df1-2acb542c53da.png)

**Comment by aksappy** [comment]
It is back up now..

**Comment by saeedvaziry** [comment]
still website is down

**Comment by kssjmpv1** [comment]
![image](https://user-images.githubusercontent.com/20216922/59401235-a0ac4500-8dcc-11e9-999b-ab32827b8e28.png)

**Comment by klentoy** [comment]
@kssjmpv1 Same

**Comment by towfiles** [comment]
server down guys :(

**Comment by arnovanoordt** [comment]
Seems down again :(
![Login - ZEIT 9-15-2019 11-44-25 AM](https://user-images.githubusercontent.com/4664041/64919710-61680880-d7ae-11e9-848d-288730a1e818.png)

**Comment by arminmon** [comment]
> Seems down again :(
> It's redirecting to https://zeit.co/login
> ![Login - ZEIT 9-15-2019 11-44-25 AM](https://user-images.githubusercontent.com/4664041/64919710-61680880-d7ae-11e9-848d-288730a1e818.png)



> Seems down again :(
> It's redirecting to https://zeit.co/login
> ![Login - ZEIT 9-15-2019 11-44-25 AM](https://user-images.githubusercontent.com/4664041/64919710-61680880-d7ae-11e9-848d-288730a1e818.png)

Same here!

**Comment by PedroMMartins** [comment]
server is down guys

![image](https://user-images.githubusercontent.com/13222688/67771567-6d531580-fa50-11e9-88a2-c839103dab7c.png)

**Comment by PedroMMartins** [comment]
> server is down guys
> 
> ![image](https://user-images.githubusercontent.com/13222688/67771567-6d531580-fa50-11e9-88a2-c839103dab7c.png)

This one is working: https://dev.vuetifyjs.com

**Comment by os1r1s110** [comment]
Down again :)

**Comment by abhaygoel** [comment]
down again

**Comment by nonick891** [comment]
Still down for me.

Just in case if someone need offline docs:
`git clone https://github.com/vuetifyjs/vuetify.git
cd vuetify
yarn
yarn build
yarn dev docs`

**Comment by KarinaBauer** [comment]
Down again?

**Comment by KarinaBauer** [comment]
> 
> 
> Still down for me.
> 
> Just in case if someone need offline docs:
> 
> > git clone https://github.com/vuetifyjs/vuetify.git
> > cd vuetify
> > yarn
> > yarn build
> > yarn start

```
PS C:\Users\k\Code\vuetify> yarn start
yarn run v1.21.1
$ lerna run start --scope vuetifyjs.com --stream
lerna notice cli v3.16.2
lerna info Executing command in 1 package: "yarn run start"
vuetifyjs.com: $ cross-env NODE_ENV=production node server
vuetifyjs.com: internal/modules/cjs/loader.js:797
vuetifyjs.com:     throw err;
vuetifyjs.com:     ^
vuetifyjs.com: Error: Cannot find module './dist/vue-ssr-server-bundle.json'
vuetifyjs.com: Require stack:
vuetifyjs.com: - C:\Users\k\Code\vuetify\packages\docs\server.js
vuetifyjs.com:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
vuetifyjs.com:     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
vuetifyjs.com:     at Module.require (internal/modules/cjs/loader.js:849:19)
vuetifyjs.com:     at require (internal/modules/cjs/helpers.js:74:18)
vuetifyjs.com:     at Object.<anonymous> (C:\Users\k\Code\vuetify\packages\docs\server.js:47:18)
vuetifyjs.com:     at Module._compile (internal/modules/cjs/loader.js:956:30)
vuetifyjs.com:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
vuetifyjs.com:     at Module.load (internal/modules/cjs/loader.js:812:32)
vuetifyjs.com:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
vuetifyjs.com:     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
vuetifyjs.com:   code: 'MODULE_NOT_FOUND',
vuetifyjs.com:   requireStack: [ 'C:\\Users\\k\\Code\\vuetify\\packages\\docs\\server.js' ]
vuetifyjs.com: }
vuetifyjs.com: error Command failed with exit code 1.
vuetifyjs.com: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in 'vuetifyjs.com'
error Command failed with exit code 1.
```

**Comment by MajesticPotatoe** [comment]
@KarinaBauer We are aware of the issue and are looking into it. You can use https://dev.vuetifyjs.com for the time being, and monitor the status at https://status.vuetifyjs.com. 

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
