### ISSUE TITLE
text-xs-center not working

### ISSUE THREAD

**Issue by firepick1** [vuetifyjs/vuetify#612]
### Steps to reproduce
See https://vuetifyjs.com/components/cards
#7 Hover and Raised
Example uses class text-xs-center but "Your Product" is not centered on any viewport size

### Versions

Vuetify 0.12.2
Chrome

### What is expected ?

text-xs-center centers text as documented

### What is actually happening ?

Text is flush right

### Reproduction Link

https://vuetifyjs.com/components/cards
Example #7

**Comment by johnleider** [comment]
That's because text-xs-center will not work there. It is inside a card__row which uses flex. If you inspect the element you will see it is only as wide as it needs to be, hence text-xs-center won't work. I'll get it removed from the docs.
