### ISSUE TITLE
[Bug Report] Time Picker Color--text CSS issue

### ISSUE THREAD

**Issue by MohawkMan** [vuetifyjs/vuetify#6128]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a time picker and try to set the text color through the color prop with color="back--text"

### Expected Behavior
It would work the same as the date picker

### Actual Behavior
The css forces text to white

### Reproduction Link
<a href="https://codepen.io/jonnymohawk/pen/jXQoVe?editors=1010" target="_blank">https://codepen.io/jonnymohawk/pen/jXQoVe?editors=1010</a>

### Other comments
.v-time-picker-title class has color set to #fff which is a child of v-picker__title which is where the color prop gets written. Therefore the #fff always takes precedence.

v-date-picker works properly because .v-date-picker-title does not have color

**Comment by jacekkarczmarczyk** [comment]
`color` prop is meant to set only the background color, `green black--text` is not a valid value

**Comment by MohawkMan** [comment]
So there is no way to change the header text color?

**Comment by jacekkarczmarczyk** [comment]
You can use custom CSS, or create a feature request
