### ISSUE TITLE
[Bug Report] Button Groups change event is not "Emitted when the input is changed by user interaction"

### ISSUE THREAD

**Issue by dawadam** [vuetifyjs/vuetify#6133]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Firefox 64.0
**OS:** Ubuntu undefined

### Steps to reproduce
Just using "change" event on v-btn-toggle

### Expected Behavior
On documentation :
"Emitted when the input is changed by user interaction"

### Actual Behavior
When using v-model and when value is changed, event is fired

### Reproduction Link
<a href="https://codepen.io/nolink>:-)" target="_blank">https://codepen.io/nolink>:-)</a>

### Other comments
Solution is using click event on every buttons inside toggle

**Comment by MajesticPotatoe** [comment]
Seems to be working as intended : https://codepen.io/anon/pen/ZVdwEQ
