### ISSUE TITLE
[Bug Report] v-btn icon in footer not align near middle at firefox

### ISSUE THREAD

**Issue by bluelovers** [vuetifyjs/vuetify#6135]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
v-btn icon in footer not align near middle at firefox

firefox
![image](https://user-images.githubusercontent.com/167966/51092543-89dcd480-17d3-11e9-9ddc-1d94c3e84f43.png)

chrome
![image](https://user-images.githubusercontent.com/167966/51092540-86494d80-17d3-11e9-8cb8-ca74a2292577.png)

### Expected Behavior
should display near middle

![image](https://user-images.githubusercontent.com/167966/51092540-86494d80-17d3-11e9-8cb8-ca74a2292577.png)

### Actual Behavior
display in top

![image](https://user-images.githubusercontent.com/167966/51092543-89dcd480-17d3-11e9-9ddc-1d94c3e84f43.png)

### Reproduction Link
<a href="https://github.com/bluelovers/ws-novel-vue/blob/master/src/components/Nav/FooterItems.vue" target="_blank">https://github.com/bluelovers/ws-novel-vue/blob/master/src/components/Nav/FooterItems.vue</a>

### Other comments
live site: https://demonovel.netlify.com/

**Comment by vcastro45** [comment]
this code works fine for me (Chrome & Firefox):
```html
<v-toolbar>
      <v-toolbar-items>
        <v-btn icon>
          <router-link to="/" class="text-color-inherit">
            <v-icon>developer_board</v-icon>
          </router-link>
        </v-btn>
        <v-spacer/>
        <v-btn icon>
          <router-link to="/history" class="text-color-inherit">
            <v-icon>history</v-icon>
          </router-link>
        </v-btn>
      </v-toolbar-items>
    </v-toolbar>
```

**Comment by bluelovers** [comment]
in my firefox (dev) 65.0b10
in my firefox (lawlietfox) 56.0.1

they all is

![image](https://user-images.githubusercontent.com/167966/51153339-bc0d3580-18aa-11e9-8c64-721a93e10303.png)

i think my repo is already small enough
and i also put a live site too
@MajesticPotatoe 

is that live site display same as chrome and pic for u too ???
@vcastro45 

![image](https://user-images.githubusercontent.com/167966/51153511-79982880-18ab-11e9-8ca1-c753df4e78f8.png)

**Comment by MajesticPotatoe** [comment]
the idea of using something like codepen is to reproduce it **outside** your environment
your live site does not have this issue in chrome or Firefox 64.0.2 (64-bit)

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/51290634-3d95cc80-1a3f-11e9-9bfd-9bc0ae597311.png)

![image](https://user-images.githubusercontent.com/167966/51290638-42f31700-1a3f-11e9-81c1-bf55dc05abad.png)
