### ISSUE TITLE
[Bug Report] v-select onchange event returns previously selected value instead of current

### ISSUE THREAD

**Issue by ChoChik** [vuetifyjs/vuetify#6136]
### Versions and Environment
**Vuetify:** 1.4.1
**Last working version:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Chromium 71.0.3578.80
**OS:** Ubuntu undefined

### Steps to reproduce
```
<template>
<v-select
      v-model="value"
      :items="items"
      @change="printValue()"
    ></v-select>
</template>

<script>
  export default {
    data: () => ({
      value: null,
      items: ['Foo', 'Bar', 'Fizz', 'Buzz']
    }),
    methods: {
      printValue() {
        console.log(this.value);
      }
    }
  }
</script>
```

### Expected Behavior
When I selected Foo, it should console.log 'Foo',
And When I selected Bar, it should console.log 'Bar'.

### Actual Behavior
When I selected Foo, it actually  console.log 'null',
And When I selected Bar, it actually  console.log 'Foo'.

### Reproduction Link
<a href="https://codesandbox.io/s/m4n65nxvmx" target="_blank">https://codesandbox.io/s/m4n65nxvmx</a>

**Comment by johnleider** [comment]
A better reproduction of your issue https://codepen.io/johnjleider/pen/JwwMoB

**Comment by mascit13** [comment]
We also figured out, that the change event returns the previously selected instead of the current selected.

**Comment by KaelWD** [comment]
Not a bug. 

```
@change="printValue"

methods: {
  printValue(val) {
    alert(val)
  }
}
```

or

```diff
- @change="printValue"

watch: {
  value (val) {
    alert(val)
  }
}
```

**Comment by mascit13** [comment]
Ah! We also made this mistake of accessing the binded property in change function. Here is a sandbox that shows the different values. nextTick() can help, but i think better way is to use the functions parameter. 
https://codesandbox.io/s/vvjr2nylj0
thank KaelWD ;-)

**Comment by ChoChik** [comment]
@mascit13 thanks

**Comment by KaelWD** [comment]
This does actually seem to be a regression, caused by #6054 changing the event order. You should still be using the event value instead, but maybe this needs to be fixed to avoid breaking existing applications that're using poor practises.
