### ISSUE TITLE
[Feature Request] Ability to disable the next/previous buttons of `v-data-table` pagination, when an API call is being made to fetch data

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#6138]
### Problem to solve
In my app, I want to prevent the user from clicking the `next` button when an API call is in progress.
![image](https://user-images.githubusercontent.com/34302506/51101305-1b623b80-1800-11e9-828c-9737c60191f9.png)

So, I want to disable that button. The `v-pagination` provides this feature,but, the built-in pagination of `v-data-table` does not.

I cannot use `v-pagination` because it does not have a dropdown to select the number of rows.

### Proposed solution
Add a prop that says `disable-action` that prevents the user from changing anything in the action row.

**Comment by nekosaur** [comment]
This is now possible in 2.0 using the prop `disable-pagination` on `v-data-footer`. Accessed through `footer-props` on `v-data-table`

**Comment by polease** [comment]
do you have example how to use this disable-pagination property?
