### ISSUE TITLE
[Bug Report] v-hover not working correctly in data-table 

### ISSUE THREAD

**Issue by eddyZ** [vuetifyjs/vuetify#6139]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.18
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
create a data table with a column that uses a hover component to change the text color on hover.
move the cursor over the table column elements reasonably quickly.

### Expected Behavior
as long as an element is hovered, its text color is not black.
while it is not hovered, the text color is black

### Actual Behavior
as long as an element is hovered, its text color is more likely to change than to stay black.
often the text color stays changed after moving the cursor away from the element.

it seems that a lot of the mouse-in and mouse-out events are skipped.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KbGYeB" target="_blank">https://codepen.io/anon/pen/KbGYeB</a>

**Comment by grishnyakov** [comment]
browser not emit hover-event on every element
if you fast move mous under 100 dom-elements, may be 50-80 events will be emited events

**Comment by sh7dm** [comment]
@eddyZ I haven't got any issues in FF 64 on Ubuntu 18.04

**Comment by nekosaur** [comment]
Problem exists in FF 64.0.2 on Windows 10

**Comment by escobera** [comment]
Problem exists in Chrome 75 in both Windows 10 and Linux Mint 19.1

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
