### ISSUE TITLE
[Feature Request] Move v-toolbar heights to styles

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#6140]
### Problem to solve
Now v-toolbar heights hardcoded in VToolbar.js and I don`t know the way how to change the toolbar height globally.

### Proposed solution
Move heights to styles

**Comment by johnleider** [comment]
This cannot happen as it is needed for advanced functionality within the component.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
