### ISSUE TITLE
[Bug Report] no-data-text not working in v-data-table

### ISSUE THREAD

**Issue by r3j3c73d** [vuetifyjs/vuetify#6145]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
In v-data-table we can use no-data-text and custom it, i do that but it wasn't work and get warning from i18n

### Expected Behavior
translate and show my text when i use no-data-text

### Actual Behavior
[vue-i18n] Cannot translate the value of keypath '$vuetify.noDataText'. Use the value of keypath as default.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ebxzQB" target="_blank">https://codepen.io/anon/pen/ebxzQB</a>

### Other comments
also $vuetify.dataIterator.prevPage and $vuetify.dataIterator.nextPage not available to customize

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to:
- [x] Requested information not provided (inactivity for 14 days)
