### ISSUE TITLE
[Bug Report] v-radio does not have proper margin inside v-toolbar

### ISSUE THREAD

**Issue by builder7777** [vuetifyjs/vuetify#6146]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create a toolbar with radio buttons group

### Expected Behavior
Radio buttons should line up horizontally with title or other toolbar elements

### Actual Behavior
radio buttons' margins are not respected
![screen shot 2019-01-14 at 14 50 05](https://user-images.githubusercontent.com/44239909/51136961-b90f3800-180b-11e9-9d50-54f8f14c1c37.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/aPXpwB" target="_blank">https://codepen.io/anon/pen/aPXpwB</a>

You can see the CSS being ignored:
![screen shot 2019-01-14 at 14 48 13](https://user-images.githubusercontent.com/44239909/51136902-9715b580-180b-11e9-98d4-7c85a74cca1f.png)

**Comment by KaelWD** [comment]
You should use `hide-details`, `v-toolbar-items` is only for buttons. There's still a bug here though as teh radio group retains 4px top padding: https://codepen.io/anon/pen/KbJedZ?editors=1010

**Comment by builder7777** [comment]
@KaelWD I can't find any references to `hide-details` in the [toolbar documentation](https://vuetifyjs.com/en/components/toolbars) can you please provide a link to the documentation, where its usage is described? 
So far I only found one reference in the radio button [section](https://vuetifyjs.com/en/components/selection-controls#radios-default) where it simply says "Hides hint, validation errors". I'm a bit confused as to how that relates to using radios in the toolbar component.
