### ISSUE TITLE
[Bug Report] v-data-table scroll issue in Safari 12.0 on MacOs

### ISSUE THREAD

**Issue by admiralman12** [vuetifyjs/vuetify#6148]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Safari
**OS:** Mac OS 10.12.6

### Steps to reproduce
I have an issue in my app where I dynamically change the data set attached to data tables by selecting a  date within a picker. I have simulated this in the attached codepen with a button that does the same thing. The issue exists on Safari 12.0 and seems to happen consistently when the width of the initial data table is smaller than the width when the data set has changed. To properly see this it may be necessary to reduce the browser size to half of full width or view on a small screen (ie laptop) The scroll bar will not appear at the bottom of the data table. This seems to only occur within the layout structure because if I remove the app->content->container->layout->flex and just have the datatable the scroll bar appears correctly.

### Expected Behavior
Scroll bar appears when data is rebound

### Actual Behavior
Scroll bar doesnt appear

### Reproduction Link
<a href="https://codepen.io/admiralman/pen/LMMzPY" target="_blank">https://codepen.io/admiralman/pen/LMMzPY</a>

**Comment by nekosaur** [comment]
Unable to reproduce on latest stable (1.5.14)
