### ISSUE TITLE
Premium Themes Navbar Broken on iPhones 

### ISSUE THREAD

**Issue by vwxyzjn** [vuetifyjs/vuetify#6149]
Please check out the following screenshots. The navbar and the Jumbotron components are intersecting... I imagine this is not the desired behavior.

![f80f4d82-e419-4574-9b72-c005608dbc9b](https://user-images.githubusercontent.com/5555347/51150025-947a8680-1832-11e9-8668-0f33f1f9266a.jpeg)
![f83a1dea-44e5-436c-963b-8e6a3f67624d](https://user-images.githubusercontent.com/5555347/51150049-b6740900-1832-11e9-983b-a8ca4d9426ed.jpeg)

**Comment by vwxyzjn** [comment]
@jacekkarczmarczyk Hi, I am actually not using the premium themes. The screenshots are from the official demo sites for the themes:

https://alpha-construction.vuetifyjs.com/
https://alpha-saas.vuetifyjs.com/

![image](https://user-images.githubusercontent.com/5555347/51272714-de7d7c80-1998-11e9-958f-5506b57e936f.png)

If you just open one of the above sites via mobile browser or the mobile tool by chrome, you would be able to reproduce what I am seeing.

Thanks.

**Comment by MajesticPotatoe** [comment]
This happens on android as well. I Dont believe its device issue, has to do with the textbox not formatting properly for smaller screens. Can reproduce in chrome using devTools + device toolbar (or resizing window)

**Comment by vwxyzjn** [comment]
@MajesticPotatoe Yeah I noticed this issue for a while. Assumed it's gonna be fixed in future releases, but it didn't, so I am reporting now...

**Comment by johnleider** [comment]
This will be resolved when I rebuild these themes after v2.0 release. This board is strictly for the vuetify framework itself. If you'd like to change about the premium themes specifically you can join the channel in our discord community. https://discord.gg/w2qKXtD
