### ISSUE TITLE
Drawer opens after each router-view change

### ISSUE THREAD

**Issue by Dark-Aii** [vuetifyjs/vuetify#615]
- I've searched for an issue regarding this, but haven't found one so far.
So I'm posting this.

### Steps to reproduce
Use any pre-defined template with a toolbar, then implement a '@click' method to go on another 'router-view'.

### Versions

Version 0.12.0

### What is expected ?

I was expecting to have the browser hidden, no mater what. Only to be opened when clicked on the menu icon/button.

### What is actually happening ?

The drawer keeps opening whenever I change route with 'vue-router'.
From the home, to the about, to the blog, etc. It just keeps opening itself despite being 'false' in the variable data.

### Reproduction Link

I don't have one at this moment, I just found out about it when I launched the website on production mode.
(Production mode has nothing to do with the issue, I tested, and found that it was also in development mode).

http://dark-aii.net is where I have a copy in production.

**Comment by johnleider** [comment]
You can disable this with the prop *disable-route-watcher*.

**Comment by johnleider** [comment]
While I understand that part of spec persistent drawers should remain open or closed, as a QoL, the route watcher is there for mobile. Seeing as there is a prop that will solve this solution for you, I'm going to close this. I could add the check to only perform the action on mobile but I'm not completely sold on it.

**Comment by drennenb** [comment]
I am having this same behavior, despite specifying the disable-route-watcher prop

**Comment by johnleider** [comment]
@drennenb if you are able to reproduce this in a https://template.vuetifyjs.com codepen, please create a new issue https://issues.vuetifyjs.com

**Comment by drennenb** [comment]
found problem, it was a dumb error.  thanks
