### ISSUE TITLE
[Bug Report] Data Table - Expand example not working

### ISSUE THREAD

**Issue by simshaun** [vuetifyjs/vuetify#6150]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Firefox 64.0
**OS:** Windows 10

### Steps to reproduce
Open https://vuetifyjs.com/en/components/data-tables#slot-expand
Try to expand a row.

### Expected Behavior
Row should expand.

### Actual Behavior
Row does not expand.

### Reproduction Link
<a href="https://codepen.io/simshaun/pen/ebxjzY" target="_blank">https://codepen.io/simshaun/pen/ebxjzY</a>

**Comment by ibunubi** [comment]
seems like Data Table - Expand buggy after update, it isn't working too in codepen

**Comment by MajesticPotatoe** [comment]
Cant reproduce on either FF 64.0.2 (64-bit) / Chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by simshaun** [comment]
@MajesticPotatoe Yea it looks like it's been fixed.

The issue was the empty slot-scope here `<template slot="expand" slot-scope="">`.
The docs now show `<template slot="expand" slot-scope="props">`.

I'll go ahead and mark this as closed.

**Comment by KaelWD** [comment]
Dev must have leaked over to the live site somehow, it's still missing.

**Comment by JaredDahlke** [comment]
> @MajesticPotatoe Yea it looks like it's been fixed.
> 
> The issue was the empty slot-scope here `<template slot="expand" slot-scope="">`.
> The docs now show `<template slot="expand" slot-scope="props">`.
> 
> I'll go ahead and mark this as closed.

`<template slot="expand" slot-scope="props">` worked for me in 1.5.   Just FYI the 1.5 documentation is not showing this code.
