### ISSUE TITLE
[Feature Request] Remove spin-button for v-text-field type number

### ISSUE THREAD

**Issue by BestLice** [vuetifyjs/vuetify#6157]
### Problem to solve
If you add the "type = 'number'" Parameter to your v-text-field there are always spin-buttons, which destroy the beautiful vuetify-page. (IMHO)

A lot people need this feature and it's way better using a parameter (or whatever) then always modifying the CSS-Sheet. 

### Proposed solution
There is a way using CSS:
https://codepen.io/paulpv/pen/mxzwoq

(It's not my codepen, it's one of the first I found when i googled for the feature)

**Comment by chaule97** [comment]
Thank you

**Comment by vinicius182** [comment]
Any updates about this feature request?

**Comment by azurramas** [comment]
> Any updates about this feature request?

I couldn't find any updates, but weirdly only this worked for me 

.v-input .v-input__control .v-input__slot .v-text-field__slot input::-webkit-outer-spin-button,
.v-input .v-input__control .v-input__slot .v-text-field__slot input::-webkit-inner-spin-button
 {
  -webkit-appearance: none;
  margin: 0;
}

If you v-input has a custom class, you can use it instead of using ".v-input" class in the CSS.

**Comment by jarvilito1234** [comment]
this works fine

::v-deep input::-webkit-outer-spin-button,
::v-deep input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

**Comment by BaptisteCool** [comment]
I think it could be good with just a prop like 'hide-arrow' or 'show-arrow'

**Comment by kp2356** [comment]
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}

**Comment by 3aluw** [comment]
I tried this, but it doesn't seem to work. What am i doing wrong ? [vuetify playground](https://play.vuetifyjs.com/#eNqNUstOwzAQ/BXLJ5DqmJcQigKCD+DKBXNI6y0YYseyN4EK5d/Z2CmN2kN7snfGnpld+/WXP3lf9B3wklcI1jc1woNyjFW9QPhBsTbQ6BFg7MNoEBqwNk3MSNthYxxMvAYXIW97YVsNzb3iPrT+5XksFM8cbjwQ4Tq7hLAFk3b0xollh9i6ZJCDyHkSgio5C0plXAXjMZ2FH98GpCDrumuQ/U65aqzPzrcVYwGwC25Xj4gu2e3NYoe8BwBXssuruxm464WYi39iyJshAVRU8j9SFXHTwAMhaVWOLzhN7CsWn7F1NPQUQvFVjIqX7DUrKf6B6GMp5Uo7OkmGpg+FA5TOW0nPhWa9ebwurovLC6lNxC0mmnoZi6Q2Sr0pN5CjseNYhK39nm0mkvU0DcVJaayPZHikYzJ0Do2lP9HaFOYmZ5nBBUQrlqH9jhBIRPFpaMlmDHyC1dF2yeNAW5JhD0EEcBrC+M9Oa2nv2rytPeqgten1Bz4seLpGk8+Z+dsfARUemw==)

**Comment by blalan05** [comment]
This was added to v2 and has not been ported over to v3... yet.
