### ISSUE TITLE
[Bug Report] V-Select item text truncated when attach property is enabled

### ISSUE THREAD

**Issue by akw123** [vuetifyjs/vuetify#6159]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
click the long text, the item text are truncated when attached is enabled 

### Expected Behavior
v-select list should wrap the text 

### Actual Behavior
the select list item text truncated

### Reproduction Link
<a href="https://codepen.io/akw123/pen/oJVjRp" target="_blank">https://codepen.io/akw123/pen/oJVjRp</a>

### Other comments
attach is enabled to prevent select list from scrolling with dialog.

**Comment by johnleider** [comment]
I don't understand what the bug is. Can you please provide additional context?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
