### ISSUE TITLE
[Bug Report] VSelect reports error on console when selecting items with return key

### ISSUE THREAD

**Issue by klaro00** [vuetifyjs/vuetify#6161]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
1. Open Codepen link.
1. Open browser console to observe console logs.
1. Click the select box, choose an item using arrow keys, and select an item by hitting the return key.
1. This error is reported in the console log: "Cannot use 'in' operator to search for 'button' in undefined".
1. Optional: Change the Codepen: Replace "@blur.tab=..." by "@blur=..." (remove the "tab" modifier) and repeat selection of an item using return key. No error will be reported.

### Expected Behavior
No error on console.

### Actual Behavior
Error on console.

### Reproduction Link
<a href="https://codepen.io/klaro00/pen/ebbYBd" target="_blank">https://codepen.io/klaro00/pen/ebbYBd</a>

### Other comments
The source of the behaviour is the Return Key Handler "onEnterDown()". This handler calls the Blur Handlers without an argument (!). One of the Blur Handlers expects an argument (an event). This is only the case if you added a key modifier to the blur callback ("@blur.tab=...).

The errornous code fragment is shown below.

Suggested solution: The code of the second Blur Handler should first test for an existing argument.
```javascript
on: {     
    ...
    ...
    blur: [
        function($event) {
            _vm.onBlur($event)        
        },       
        function($event) {          
            // Before:
            if (!("button" in $event) && _vm._k($event.keyCode, "tab", 9, $event.key, "Tab")) { return null }
            // After:
            if ($event && !("button" in $event) && _vm._k($event.keyCode, "tab", 9, $event.key, "Tab")) { return null }
            ...
            ...
        }      
    ]    
},
```

**Comment by johnleider** [comment]
For future triage, this bug exists in 1.3.x as well.

**Comment by KaelWD** [comment]
> Suggested solution: The code of the second Blur Handler should first test for an existing argument.

Those handlers are generated by vue, not vuetify. This was fixed at some point anyway, vselect no longer calls `onBlur` when enter is pressed.
