### ISSUE TITLE
[Bug Report] v-btn strange styles (2.0.0-alpha.0)

### ISSUE THREAD

**Issue by iliyaZelenko** [vuetifyjs/vuetify#6162]
![image](https://user-images.githubusercontent.com/13103045/51225519-a6a01600-1953-11e9-8485-1944f153695b.png)

### Versions and Environment
**Vuetify:** 2.0.0-alpha.0
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Point your eyes to the buttons.

### Expected Behavior
Normal styles.

### Actual Behavior
Strange styles.

### Reproduction Link
<a href="https://codepen.io/iliyazelenko/pen/LMaJmB?&editable=true&editors=101" target="_blank">https://codepen.io/iliyazelenko/pen/LMaJmB?&editable=true&editors=101</a>

### Comment

The documentation shows the same example normally but example on the [codepen](https://codepen.io/pen/?&editable=true&editors=101) does not work correctly.

![](https://i.imgur.com/6pVSRBX.png)

https://codepen.io/iliyazelenko/pen/MZxqzm?&editable=true&editors=101

[This example](https://next.vuetifyjs.com/en/components/toolbars#usage) also does not work correctly on my project and [codepen](https://codepen.io/pen/?&editable=true&editors=101). Also there is used a deprecated `flat` prop.

**Comment by KaelWD** [comment]
The minified stylesheet is somehow missing some rules.

**Comment by MajesticPotatoe** [comment]
Resolved in Alpha.2 👍
