### ISSUE TITLE
[Bug Report] Timepicker not triggers events if hours stay the same

### ISSUE THREAD

**Issue by vollyimnetz** [vuetifyjs/vuetify#6163]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Use a timepicker twice with the same minute values (hours may change).

### Expected Behavior
The change event is triggered.

### Actual Behavior
The timepicker do not trigger.

### Reproduction Link
<a href="https://jsfiddle.net/volly_imnetz/2sbmLzgc/19/" target="_blank">https://jsfiddle.net/volly_imnetz/2sbmLzgc/19/</a>

### Other comments
It would be generally better if we had a second event that triggers once the cycle completed.

My use case is the following: i added the timepicker in an MENU which should close once the user selects/OR CHANGES a time. Selecting the time (for the first time) worked with no problem. When changing the time the user may decide to leave both, hours and minutes, the same. But then i got no event to determine that the menu could be closed. So a "cyclecomplete" event may be very good - as the input is composed on two or three (when seconds is active) different views.

**Comment by jacekkarczmarczyk** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by jacekkarczmarczyk** [comment]
Maybe instead of `cyclecomplete` we could add `click:hour`, `click:minute`, `click:second` events as it is done in date pickers (`click:date`, `click:month`)? Any opinions on that?

**Comment by MajesticPotatoe** [comment]
> Maybe instead of `cyclecomplete` we could add `click:hour`, `click:minute`, `click:second` events as it is done in date pickers (`click:date`, `click:month`)? Any opinions on that?

That would make more sense, would also allow for more granular control. 👍

**Comment by vollyimnetz** [comment]
@jacekkarczmarczyk 
hi, just found out about your solution with custom click-events. I now use this solution on my app and it worked flawless. Thank you very much.
