### ISSUE TITLE
[Bug Report] Form validation not work with form elements with required property

### ISSUE THREAD

**Issue by mahapo** [vuetifyjs/vuetify#6169]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
If a form element has a required property and is empty, the form validation will not validate this property.
It only works if it has a rules.

### Expected Behavior
If a form element has a required property and is empty, the form validation of this element should be invalid.

### Actual Behavior
If a form element has a required property and is empty, the form validation will not throw an error and the validation is valid for this element.

### Reproduction Link
<a href="https://codepen.io/mahapo/pen/aPxBBa" target="_blank">https://codepen.io/mahapo/pen/aPxBBa</a>

**Comment by johnleider** [comment]
This is the intended and expected outcome. You must provide rules for each and every validation that you want.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
