### ISSUE TITLE
group-tile-title-font-weight should be 400?

### ISSUE THREAD

**Issue by basejump** [vuetifyjs/vuetify#617]
Currently the defaults are
$list-group-tile-title-font-weight := 400
$list-group-tile-title-active-font-weight := 400
are set to 300.
Based on what I normally see and on material.io it should be darker
see https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls

![image](https://cloud.githubusercontent.com/assets/187726/26526163/792f6d96-4336-11e7-9f7e-ee1ea4ec914d.png)

**Comment by mfferreira** [comment]
@basejump I think you're right.
