### ISSUE TITLE
[Bug Report] v-select defaults item-value to the item label instead of return-object

### ISSUE THREAD

**Issue by Moustafa-WW** [vuetifyjs/vuetify#6170]
### Versions and Environment
**Vuetify:** 1.4.2
**Last working version:** 1.0.17
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a `v-select` with an items array that is a list of objects

```
      items: [
        { state: 'Florida', abbr: 'FL' },
        { state: 'Florida', abbr: 'FLORIDA_ON_MARS' },
        { state: 'Georgia', abbr: 'GA' },
        { state: 'Nebraska', abbr: 'NE' },
        { state: 'California', abbr: 'CA' },
        { state: 'New York', abbr: 'NY' }
      ]
```

Now create a `v-select` that has an item-text defined but no item-value

```
<v-select
            v-model="select"
            :items="items"
            item-text="state"
            label="Select a State"
>
</v-select>
```

Now print out the `v-model` of `select` which should be a state object

### Expected Behavior
When logging out the `v-model` (`select`) we should be getting back the full object by default like in Vuetify 1.0.17. 

### Actual Behavior
Instead we get back the `item-text` as a plain string and not the full object. The current way around this is using `return-object` but that seems to have changed as we didn't need to use `return-object` before by default.

### Reproduction Link
<a href="https://codepen.io/anon/pen/MZRbpO?editors=1010" target="_blank">https://codepen.io/anon/pen/MZRbpO?editors=1010</a>

**Comment by younetox** [comment]
you need to add return-object to the v-select.
<v-select
            v-model="select"
            :items="items"
            item-text="state"
            return-object
            label="Select a State"
>
</v-select>

**Comment by KaelWD** [comment]
I think this has been around for long enough that it would be a bigger breaking change to revert it.

**Comment by e200** [comment]
This sucks.
