### ISSUE TITLE
[Bug Report] [Vue 2.6] v-hover should only contain a single element

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#6171]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.6.0-beta.1
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
see console

### Expected Behavior
no error

### Actual Behavior
error

### Reproduction Link
`VHover`:
<a href="https://codepen.io/anon/pen/XoQeJV?editors=1001" target="_blank">https://codepen.io/anon/pen/XoQeJV?editors=1001</a>

`VItem`:
https://codepen.io/anon/pen/MZREVQ?editors=1001

**Comment by KaelWD** [comment]
Already tracked internally: https://gist.github.com/yyx990803/25e42014c7b6cd36e2f7d474a125229e

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/commit/9856ed69bab846bf5fae2d9fe1f412ad58c68c92
