### ISSUE TITLE
[Bug Report] Basic v-data-table not working.

### ISSUE THREAD

**Issue by ismet** [vuetifyjs/vuetify#6172]
### Versions and Environment
**Vuetify:** 1.4.2
**Last working version:** 1.4.0
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
```html
<div id="app">
  <v-app id="test">
    <v-data-table class="elevation-5" hide-actions>
      <template slot="headers">
        <tr>
          <th>Column 1</th>
          <th>Column 2</th>
          <th>Column 3</th>
        </tr>
      </template>
      <template slot="items">
        <tr>
          <td>Data 1</td>
          <td>Data 2</td>
          <td>Data 3</td>
        </tr>
      </template>
    </v-data-table>
  </v-app>
</div>
```

### Expected Behavior
1 row and 3 columns of data

### Actual Behavior
No data

### Reproduction Link
<a href="https://codepen.io/ismet-togay/pen/BvEwyN" target="_blank">https://codepen.io/ismet-togay/pen/BvEwyN</a>

### Other comments
I don't want to use :headers or :items props. I just want to create a static table from v-data-table.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/xmeXme

**Comment by ismet** [comment]
Thank you.

But I don't like the idea of using a `<table>` with vuetify classes. 
I think `v-data-table` must support headerless/itemless content in its slot templates.
