### ISSUE TITLE
[Feature Request] Sparkline: vertical labels and chart grid

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#6173]
### Problem to solve
Sparkline is a basic component for showing information in chart. It could be much more usable if there will be vertical labels and basic chart grid provided

### Proposed solution
Add vertical labels and basic chart grid for each label

**Comment by MajesticPotatoe** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by qq1162667214** [comment]
St,I have met the same question.

**Comment by ndunks** [comment]
+1

**Comment by t-k-** [comment]
I want this feature too!

**Comment by LMBernardo** [comment]
Love the sparklines, but it really would be much more usable with vertical axis labels. I'm using the sparkline component to show the number of items in a data set within certain ranges, i.e., if I have 5 items that are all between 100 and 200 then the horizontal label will say "100 - 200" but the sparkline data is 5. Without vertical labels you can only judge by the relative height of the lines with no context for what the actual count is. I appreciate the work that has gone into this, and obviously the devs providing this (free) component owe us nothing, but vertical axis labels are a basic and frequently essential part of graphing data. If you could re-evaluate adding this feature to the roadmap, I'm sure many people would  be grateful.

Thanks, Layne

**Comment by chiefbrwnmeanie** [comment]
+ 1 

the vertical labels would be really helpful in cases where you want to show a value that has changed over a time period, and having the context of that value change on the y axis is crucial for being useful in a lot of common scenarios. this is a great component and could be even more useful with the addition of vertical labels.

**Comment by bensweeney** [comment]
agreed, would love to see this! horizontal labels are a necessity, but so are vertical labels. It's like half the description of the data.

**Comment by ArthurVerstraete** [comment]
+1

**Comment by morandalex** [comment]
Please implement this feature!|
