### ISSUE TITLE
[Bug Report] Tree View component fails when replacing list with new list of same size

### ISSUE THREAD

**Issue by AsthirWP** [vuetifyjs/vuetify#6181]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.80
**OS:** Windows 10

### Steps to reproduce
Initialize a tree view component with a list. Then replace the list with a new list with the same number of elements. See Codepen https://codepen.io/anon/pen/QzRbeq?editors=1010 for test case. This will throws the following exception in the console. Adding a larger or smaller list doesn't seem to throw an exception.

### Expected Behavior
Tree view data set should be replaceable with new data set of the same size.

### Actual Behavior
Seems to work on the user interface, but behaviour is not correct afterwards. Selection etc. does not work correctly. Inspecting the v-treeview component in Vue Developer Tools shows that the nodes data object refers to the old data while items props contains the updated data.

### Reproduction Link
<a href="https://codepen.io/anon/pen/QzRbeq?editors=1010" target="_blank">https://codepen.io/anon/pen/QzRbeq?editors=1010</a>

**Comment by andreapier** [comment]
I am experiencing the same issue, but wasn't able to properly track it down to replacing a list of the same size.  
At least until now :)

**Comment by AsthirWP** [comment]
Yes, it took quite some time to nail down to a small reproducible case. I'm glad it can be of help.
