### ISSUE TITLE
[Feature Request] Toolbar with content and another toolbar

### ISSUE THREAD

**Issue by Extarys** [vuetifyjs/vuetify#6182]
### Problem to solve
Allow more flexible toolbar, navigation experience and design.

### Proposed solution
https://developer.android.com/guide/

There is a toolbar, then another toolbar with some content just before.
There is also the ability to use one background color for the app toolbar, and one color for the second toolbar.

![image](https://user-images.githubusercontent.com/11581433/51314616-2f838400-1a1e-11e9-9b6a-1dbcd084c58b.png)

**Comment by johnleider** [comment]
Everything above can be accomplished with the tools available in the latest version.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
