### ISSUE TITLE
[Bug Report] Vertical stepper with dynamic steps lacks entry animation when proceeding to a dynamically added step immediately after it is added

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#6189]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
In the repro link, click Add Step twice, and then continue. The first continue will have no "expand" animation for the contents of Step 1. The second continue, however, will have an animation.

I think this is because the dynamic steps aren't getting "booted" until a step change occurs. After the step is changed, all subsequent dynamic steps will have correct animations because they got booted when the transition to Step 1 occurred.

### Expected Behavior
The dynamic step has an "expand" animation

### Actual Behavior
The dynamic step's contents are immediately visible at full height.

### Reproduction Link
<a href="https://codepen.io/anon/pen/zyQmOz" target="_blank">https://codepen.io/anon/pen/zyQmOz</a>

### Other comments
Use case here is a form that consists of several sections that are filled out in steps. The first step is where the user enters some data which then determine what sections of a form will need to be filled out. Each dynamic step is a different section of the overall form.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
