### ISSUE TITLE
Toolbar right and left spacing defaults

### ISSUE THREAD

**Issue by basejump** [vuetifyjs/vuetify#619]
I believe the defaults on this should be the rough equivalent to 16 px, as it is in a List. 
"Toolbars are versatile and can be used in many different ways." is what it says in material.io's [structure-app-bar](https://material.io/guidelines/layout/structure.html#structure-app-bar) section. One of the more common ways is on a card. In essence, I think this is how it should default. 
![image](https://cloud.githubusercontent.com/assets/187726/26526794/d5bd6e6e-434a-11e7-8acb-cbf0e98be3b3.png)

There are really 2 types of toolbars. 1 is a more general use toolbar the other is what they call an appbar. Where it makes sense to have to widden the right and left spacing to 24px as its not really trying to line up with anything. There should probably be a parameter or another seperate component that specifys that its an "App" bar where it can deal with adjusting its height to 48,56 or 64 and padding to 24 based on screen size and orientation per the spec. 
 more  background can be found in this issue #618 with a doc example here https://github.com/basejump/vuetifyjs-docs/tree/616-dense-list-example. I roughed out the stylus settings for margins and padding. in reality we need to take into account the spacing for the button of 36x36 on the nav icon, and then on the right normal menu icon it would be dropped to account for it more or less being a dotted vertical line. I am going to create another issue as I think the "menu" button warrant its own component or setting in the v-toolbar-side-icon. 

material.io linke here https://material.io/guidelines/layout/structure.html#structure-app-bar and for lists here https://material.io/guidelines/components/lists.html

**Comment by johnleider** [comment]
Thank you for the detailed report. Will definitely fix.

**Comment by johnleider** [comment]
This has been fixed as of 0.13 release.
