### ISSUE TITLE
[Bug Report] Lazy ExpansionPanel not animating

### ISSUE THREAD

**Issue by oliveiracdz** [vuetifyjs/vuetify#6190]
### Versions and Environment
**Vuetify:** 1.4.2
**Last working version:** 1.3.7
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a ExpansionPainel with lazy ExpansionPainelContents.

### Expected Behavior
The opening animation to work initially, even with lazy content.
This used to work with v1.3.7, like in this [codepen](https://codepen.io/oliveiracdz/pen/pqmQYq) .

### Actual Behavior
The opening animation do not work.

### Reproduction Link
<a href="https://codepen.io/oliveiracdz/pen/OrYaKQ" target="_blank">https://codepen.io/oliveiracdz/pen/OrYaKQ</a>

**Comment by oliveiracdz** [comment]
@sh7dm, version [1.3.10](https://codepen.io/oliveiracdz/pen/MLgryX).
Maybe something related with this commit d0ffc88a75a2179bc5fbdb5578405863acfb47eb?

**Comment by sh7dm** [comment]
@oliveiracdz It works in both directions in v1.3.7 https://codepen.io/sh7dm/pen/XOrZad
Only on open: v1.3.8 / v1.3.9  https://codepen.io/sh7dm/pen/ErYQwg
Doesn't work at all 🤬: v1.3.10 https://codepen.io/sh7dm/pen/pGzadz

**Comment by sh7dm** [comment]
Looks like open anim was removed in 97053db

**Comment by sh7dm** [comment]
These commits between v1.3.9 and v1.3.10 are related to `VExpansionPanel`: ebc5aaf cb605ac a039846

**Comment by sh7dm** [comment]
Hmm... it only doesn't work for first time, then anim works good. It's very strange

**Comment by oliveiracdz** [comment]
@sh7dm, this fix breaks #5703 again. =/
Now the lazy content renders before open the expansion, like in this 
[codepen](https://codepen.io/oliveiracdz/pen/KJqOyz) with v1.4.5.

**Comment by sh7dm** [comment]
:boom: It's very difficult to fix. I think we need @johnleider's help!

**Comment by johnleider** [comment]
I have a fix for this going up

**Comment by oliveiracdz** [comment]
Thanks!

But I think that d3937e05228474844d764c55ef6c23ca0a58dfb1 broke this another https://github.com/vuetifyjs/vuetify/issues/4483 now.

https://codepen.io/oliveiracdz/pen/aXyajL

**Comment by AlexeyKot** [comment]
This change broke my expansion-list with a component containing dynamic chart. Code Example:
[https://codesandbox.io/s/98wo5r0664](https://codesandbox.io/s/98wo5r0664)
