### ISSUE TITLE
How to customize specific column in data table? 

### ISSUE THREAD

**Issue by Enigma10** [vuetifyjs/vuetify#6195]
Currently, if we want to customize one column in the table. we need to rewrite all the column in the template.
```
<v-data-table
  :headers="headers"
  :items="desserts"
  class="elevation-1"
>
  <template slot="items" slot-scope="props">
    <td>{{ props.item.name }}</td>
    <td class="text-xs-right">{{ props.item.calories }}</td>
    <td class="text-xs-right">{{ props.item.fat }}</td>
    <td class="text-xs-right">{{ props.item.carbs }}</td>
    <td class="text-xs-right">{{ props.item.protein }}</td>
  </template>
</v-data-table>

```
Is there any way using which we only need to write columns which we want to customize. Bootstrap-vue is having this [feature](https://bootstrap-vue.js.org/docs/components/table).

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
