### ISSUE TITLE
Problem with DataTable and server side data in IE 11

### ISSUE THREAD

**Issue by RRule** [vuetifyjs/vuetify#6196]
I'm having problems with setting my data items for vuetify datatables in IE11. 
https://vuetifyjs.com/en/components/data-tables

The issue is that IE11 can't use lambda expressions as the return type for my function. The suggested workaround is using 

> 'function(response)'

 instead of 

> response=>

But when i use function() the Vuetify Data Grid can't load any data at all. It doesnt 'see' the updated data. However when i test the content of data.items i can see the data is pushed correctly.

Method 1:
I use Axios GET method to retrieve the data. With Lambda expression.
```
                initialize: function () {
                    axios.get('/Admin/OnGetMenuItems')
                    .then(response => {
                        if (response) {
                            this.items = response.data;
                        }
                    })
```
This works fine in Chrome but not in IE 11. Syntax error in "response => "

Method 2:
I use function(response) instead
```
                initialize: function () {
                    axios.get('/Admin/OnGetMenuItems')
                    .then(function(response) {
                        if (response) {
                            this.items = response.data;
                        }
                    })
```
No errors show up, but the Vuetify table data does not 'see' the items. It says it's empty.
When i query the contents of this.items it shows me the correct data.

I'm completely stuck on how to fix this. 

Using the following scripts:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.21/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.20.1/moment.min.js"></script>
    <script src="https://unpkg.com/vee-validate@2.0.0-rc.25/dist/vee-validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/questions/40216015/arrow-function-not-working-in-ie-why

**Comment by RRule** [comment]
I feel like you haven't read the issue. I am using the replacement for the arrow function. 

However, this does **NOT** update the data in the **datatable**.

**Comment by jacekkarczmarczyk** [comment]
Still nothing to do with Vuetify
https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4
