### ISSUE TITLE
[Bug Report] multi v-range-slider component's 'change event'  be trigger at same time click event

### ISSUE THREAD

**Issue by bodhifan** [vuetifyjs/vuetify#6198]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.20
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
change any slider's value then see the console output, it will print three object's names.

### Expected Behavior
only the name of the one changed value be print out.

### Actual Behavior
all slider's event be triggered.

### Reproduction Link
<a href="https://jsfiddle.net/bodhifan/9bqu2vjh/30/" target="_blank">https://jsfiddle.net/bodhifan/9bqu2vjh/30/</a>

### Other comments
when I set any values of slider above, the onChange function be triggered three times!

**Comment by nekosaur** [comment]
Change `:change` to `@change`
