### ISSUE TITLE
Dialog and Stepper Issue

### ISSUE THREAD

**Issue by bunnypro** [vuetifyjs/vuetify#620]
### Steps to reproduce
create a dialog inside stepper

### Versions
0.12

### What is expected ?
dialog (and overlays) should shown above stepper

### What is actually happening ?
dialog shown only inside stepper-content

### Reproduction Link
https://jsfiddle.net/gzz8cv6w/3/

**Comment by johnleider** [comment]
This is a tricky one. This happens because its parent has translateZ(0) to fix another bug caused with rendering on Chrome.

**Comment by johnleider** [comment]
I'm going to have to re-open this until 12.4 as a fix interferes with this functionality.
