### ISSUE TITLE
v-slider does not initialize app data correctly when app is deployed as web component.

### ISSUE THREAD

**Issue by dhardin** [vuetifyjs/vuetify#6203]
# Issue
When using the v-slider component, a Vue app that was built as a web component will throw an error due to improper initialization of the component's **app** attribute.  This is due to the the Vue app being injected into a **ShadowRoot** and does not exist as one of the document's elements. 

https://github.com/vuetifyjs/vuetify/blob/70b99a40e6243bad87acb6ad6cdd6c5b9bbe451d/packages/vuetify/src/components/VSlider/VSlider.js#L219

As you can see, the query selector is selecting based off of the document instead of the Vue app's root element.

This causes the components onThumbMouseDown button to throw and exception due to this.app not being initialized.
``` diff
-> Uncaught TypeError: Cannot read property 'addEventListener' of undefined
-     at VueComponent.onThumbMouseDown (vuetify.js?ce5b:11749)
-     at invoker (vue.js:2141)
-     at HTMLDivElement.fn._withTask.fn._withTask (vue.js:1926)
```
## How to Reproduce

1. Create a Vue app that uses the [thumb.vue](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/sliders/thumb.vue) component.

2. Using the Vue UI, set your **Build Target** as _Web component_ build your project.  

3. Serve your app and attempt to drag a slider that has the thumb label.  Due to the app not being initialized, this attempts to attached an event listener to an undefined variable.

## How to Fix
Instead of using the query selector on the document, use a query selector on the Vue app's root element using the following:
``` javascript
this.app = this.$root.$el.querySelector('[data-app]') ||
 Object(_util_console__WEBPACK_IMPORTED_MODULE_5__["consoleWarn"])('Missing v-app or a non-body wrapping element with the [data-app] attribute', this);
```

Please let me know if you need additional info!

**Comment by KaelWD** [comment]
Web components are not currently supported (#5054), and your fix would break applications that rely on `[data-app]` being external to vue.
