### ISSUE TITLE
Missing navigation drawer highlighting with Vue Router

### ISSUE THREAD

**Issue by helmi77** [vuetifyjs/vuetify#621]
### Steps to reproduce
Please refer to the codepen below.

### Versions

* Vue 2.2.6
* Vuetify: 0.12.0
* Vue Router: 2.5.3

### What is expected ?
I'd expect to see the currently active route highlighted in the navigation drawer.
That is the color of the icon next to the list text should be updated.

### What is actually happening ?
Only the first tile ever gets highlighted.
I suspect the reason is that the corresponding CSS class is  
`.navigation-drawer > .list .list__tile--active:first-child .icon`  
If you change it to  
`.navigation-drawer > .list .list__tile--active .icon`  
the highlighting works correctly. This behaviour can also be observed in the codepen.

### Reproduction Link
[codepen](https://codepen.io/anon/pen/wdbPyg)

**Comment by johnleider** [comment]
This is happening because you have multiple ```v-list-tiles``` in a ```v-list-item``` which is not something I ever really anticipated. With that being said, the style did need to change and is fixed now.
