### ISSUE TITLE
[Feature Request] InLine Editable Datatable for saving Bulk Data

### ISSUE THREAD

**Issue by Raviteja369** [vuetifyjs/vuetify#6219]
### Problem to solve
We are looking for Editing the rows in line for Datatable. When User clicks on Save button which placed outside of data table, Need to save bulk data in single with rows edited in the grid view( Data table). 

### Proposed solution
We are looking for help from Vuetify to implement a simple example of this kind request.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
