### ISSUE TITLE
Feature request: Being able to specify first day of the week in date picker

### ISSUE THREAD

**Issue by Brimstedt** [vuetifyjs/vuetify#622]
It would be great if it was possible to specify first day of week in date picker. 

It is an i18n issue, lots of places consider Monday to be first day of the week and it is confusing to have the "wrong" day first.

> What will it allow you to do that you can't do today?

View the calendar according to users locale.

> How will it make current work-arounds straightforward?

Not aware of any workarounds for this.

> What potential bugs and edge cases does it help to avoid?

It will make it easier for users who does not look at the day titles to select the correct day (i.e it's easy to assume that monday is in the leftmost column)

**Comment by mornir** [comment]
An attribute similar to the firstDayOfWeek attribute in Element CSS Framework would be awesome:
http://element.eleme.io/#/en-US/component/date-picker#picker-options
