### ISSUE TITLE
[Bug Report] The date translation is not accurate with Edge

### ISSUE THREAD

**Issue by Ssssue** [vuetifyjs/vuetify#6220]
## Step to reproduce
```Javascript
       <v-date-picker
          v-model="date"
          :max="today"
          full-width
          landscape
          class="elevation-10"
          locale="zh-CN"
          width="100%"
          color="primary"/>
```

## Expected Behavior
![image](https://user-images.githubusercontent.com/33820860/51450776-02f8a080-1d6d-11e9-915f-a1580544f636.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/33820860/51450879-7c908e80-1d6d-11e9-9161-0c578851887a.png)

##Reproduction Link
emmm...It seems to show normally on the codepen,but not normally on the Edge.

**Comment by sh7dm** [comment]
@Ssssue what does it mean: it seems to show normally on codepen? Do you use the same version for your project and codepen?

**Comment by Ssssue** [comment]
> @Ssssue what does it mean: it seems to show normally on codepen? Do you use the same version for your project and codepen?

sorry, my English is not good...

I use the same version for my project. And the examples of the document has the same problem.

## Reproduction Link
[https://vuetifyjs.com/en/components/date-pickers#date-month-picker](url)

if you open this URL with Edge and go to the part of 'Date pickers - Internationalization', you can see this:

![image](https://user-images.githubusercontent.com/33820860/51460059-6991b480-1d95-11e9-9f5f-685e2722b124.png)

but this is right (Boswers: Chrome71.0.3578.98):

![image](https://user-images.githubusercontent.com/33820860/51460031-55e64e00-1d95-11e9-9f15-d81ef75d3ce8.png)

**Comment by jacekkarczmarczyk** [comment]
Looks like an Edge bug, you could provide your own formatter using `title-date` prop

![image](https://user-images.githubusercontent.com/15625235/51624837-49691d80-1f6e-11e9-81c9-37b6d992799f.png)
