### ISSUE TITLE
[Bug Report] Button Group Toolbar layout issue

### ISSUE THREAD

**Issue by ubitoffee** [vuetifyjs/vuetify#6221]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
1. Just toggle device toolbar & change to mobile layout

### Expected Behavior
I want to get mobile toolbar like column view

### Actual Behavior
This is just crushed layout

### Reproduction Link
<a href="https://codepen.io/ubitoffee/pen/WPeREG" target="_blank">https://codepen.io/ubitoffee/pen/WPeREG</a>

**Comment by sh7dm** [comment]
@ubitoffee It needs a good fix, the code above is just a workaround, add this to your custom CSS

**Comment by ubitoffee** [comment]
@sh7dm OK, I will use this workaround now and I hope next improved version!

**Comment by johnleider** [comment]
Toolbar content is purposefully meant not to wrap as within spec they have a specific that does not scale as such. The workaround css is your best bet.
