### ISSUE TITLE
[Bug Report] custom svg icons not handling click events

### ISSUE THREAD

**Issue by shaikemarc** [vuetifyjs/vuetify#6228]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
- Configure Vuetify to work with custom icons set - in my case svg's from npm: "material-design-icons-iconfont"
- In particular, configure the "clear" icon to be "Close"

### Expected Behavior
Clicking on the "X" icon will remove the selected item from the input.

### Actual Behavior
Instead, the list itself is being displayed. It seems like the click event is not attached to the custom icon

### Reproduction Link
<a href="https://github.com/shaikemarc/testvuetify" target="_blank">https://github.com/shaikemarc/testvuetify</a>

**Comment by Mintonne** [comment]
Same here. I am using [vue-svgicon](https://github.com/MMF-FE/vue-svgicon) in my project.

I was not able to run @shaikemarc's project so I setup another using Vue CLI 3.

### Repo

https://github.com/Mintonne/vuetify-clear-bug

### Demo

https://clearbug.netlify.com/

### Affected Components

All components with the clearable prop.

**Comment by nekosaur** [comment]
@Mintonne Is your issue different than OPs? The custom icon does not show up at all in the demo?

**Comment by Mintonne** [comment]
@nekosaur 

Unless I am misreading OP's issue, they are the same.

If the clear icon is set to a [component icon](https://vuetifyjs.com/en/framework/icons#component-icons), clicking on it does nothing.

```js
import {  Clear } from './components/icons';

Vue.use(Vuetify, {
  icons: {
    'clear': {
      component: Clear
    }
}
```

**Comment by shaikemarc** [comment]
@nekosaur @Mintonne 

The same. Clicking does open the Menu but does not clear.

**Comment by nekosaur** [comment]
My problem is that I do not see the close icon in your demo, but perhaps that's an issue on my end.

![screenshot 2019-01-23 at 16 39 34](https://user-images.githubusercontent.com/623137/51617982-a7c1dc00-1f2d-11e9-8203-a8ab4488ecf0.png)

**Comment by shaikemarc** [comment]
I'm too don't see the icon of @Mintonne demo.

**Comment by Mintonne** [comment]
@nekosaur 

You are right. The custom icons are not rendered on Chrome for some reason. The markup is there though.

On firefox, they show up just fine.

**Comment by Mintonne** [comment]
@nekosaur @shaikemarc

Should be fixed now.

**Comment by Mintonne** [comment]
**UPDATE**: Append and prepend icons are also affected. I have updated the demo to showcase this.

**Comment by KaelWD** [comment]
vue-mdi [doesn't delegate event listeners](https://github.com/Mintonne/vue-mdi/blob/b011595ad6c83a033b6f4800ca00d7e93475e8a8/template.mst), and v-icon just renders the target component directly without anything wrapping it. We could probably use `nativeOn` instead to work around poorly designed icon components?

**Comment by AGPDev** [comment]
@KaelWD Work tks.
@Mintonne i will make PR to help.
