### ISSUE TITLE
[Bug Report] v-autocomplete input's border does not render when `full-width` prop is used

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#6230]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
1) Open the codepen
2) The `v-autocomplete` has `full-width` prop added to it. You'll see that the border below the input is not visible.
3) Remove the `full-width` prop and you'll see the border below the input field

### Expected Behavior
Border should be visible below the input in all the cases

### Actual Behavior
Input border is not visible

### Reproduction Link
<a href="https://codepen.io/anon/pen/LqYmVa?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/LqYmVa?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
While the spec isn't extensive on this prop, from the provided examples in MD1, this is intended and part of how full-width looks. If you need to create separation between elements, use a `v-divider` component.

https://material.io/archive/guidelines/components/text-fields.html#text-fields-field-variations

![image](https://user-images.githubusercontent.com/9064066/51613899-24cb6200-1eea-11e9-9b17-206bd963f35d.png)
