### ISSUE TITLE
Layout Predefined Section

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#624]
I find it weird on docs
Permanent headline but example is persistent
![image](https://cloud.githubusercontent.com/assets/9329005/26551998/d4cb9f08-44b7-11e7-9353-065fd82a3a8f.png)

Also, Toolbar title name, the distance is too far
![image](https://cloud.githubusercontent.com/assets/9329005/26552082/2cc79dc4-44b8-11e7-83f8-49ea756c8b71.png)

**Comment by johnleider** [comment]
The first image is baseline, it's what I consider most people will end up using. As far as the second image, what browser? That does not happen for me.

**Comment by donPuerto** [comment]
Im using chrome...

**Comment by johnleider** [comment]
I'm going to need some help from you then because that is not the behavior that I can see on any browser. Can you inspect element and tell me what is causing that extra margin for you?

**Comment by donPuerto** [comment]
As i checked and tried to redo the error, as noticed on Toolbar title extra spacing is gone...
![image](https://cloud.githubusercontent.com/assets/9329005/26637776/f8c98c8e-4652-11e7-9811-1d504ab550a8.png)

**Comment by johnleider** [comment]
Are you having any additional issues?

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
