### ISSUE TITLE
[Bug Report] Can not ripple a v-label with v-ripple which works for HTML DIV

### ISSUE THREAD

**Issue by huaichaow** [vuetifyjs/vuetify#6245]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
there's no ripple effect with the following code:
```
<v-label v-ripple>
CAN NOT Ripple v-label
</v-label>
```

### Expected Behavior
There's a ripple on clicking the element.

### Actual Behavior
No ripple effect.

### Reproduction Link
<a href="https://codepen.io/huaichao/pen/LqVarj" target="_blank">https://codepen.io/huaichao/pen/LqVarj</a>

**Comment by MajesticPotatoe** [comment]
wrap the label with `<div v-ripple>`

**Comment by KaelWD** [comment]
Added a warning if ripple is bound to an inline element, it'll never work because we need `el.clientWidth` to figure out the correct dimensions.
