### ISSUE TITLE
[Bug Report] v-combobox don't update items / dropdown list

### ISSUE THREAD

**Issue by vincent41** [vuetifyjs/vuetify#6246]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.12.1

### Steps to reproduce
<v-combobox
            v-model="select"
            :items="items"
            item-text="value"
          ></v-combobox>

### Expected Behavior
if i change the object value, the list will not updated

### Actual Behavior
the list stay unchanged

### Reproduction Link
<a href="https://codepen.io/vincent4/pen/KJpYMz?editors=1010" target="_blank">https://codepen.io/vincent4/pen/KJpYMz?editors=1010</a>

### Other comments
items: [
        { id: 1, value:'Programming'},
        { id: 2, value:'Design'},
        { id: 3, value:'Vue'},
        { id: 4, value:'Vuetify'}
      ]

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by vincent41** [comment]
many thanks @MajesticPotatoe @jacekkarczmarczyk
