### ISSUE TITLE
Data table pagination dropdown cropped

### ISSUE THREAD

**Issue by helmi77** [vuetifyjs/vuetify#625]
### Steps to reproduce
Create a data table with the default pagination.

### Versions
* Vue 2.3.3
* Vuetify 0.12.2
* Chrome 58.0.3029.110

### What is expected ?
Clicking on the "rows per page" dropdown should allow users to select the preferred number of rows per page.

### What is actually happening ?
The dropdown overflow is hidden outside the data table.
![pagination](https://cloud.githubusercontent.com/assets/1245519/26560228/1f40cebc-44b5-11e7-90c3-f622b278364a.png)

### Reproduction Link
This issue also occurs in the [documentation samples](https://github.com/vuetifyjs/docs/blob/master/examples/tables/2.vue). 
See the screenshot above.

**Comment by psychonetic** [comment]
This issue has already been solved. See #585
