### ISSUE TITLE
[Feature Request] Export to excel and specific print for table with scroll

### ISSUE THREAD

**Issue by novandri511** [vuetifyjs/vuetify#6251]
### Problem to solve
can print table and export to xls or excel

### Proposed solution
i hope vuetify can add this feature quickly

**Comment by MajesticPotatoe** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

Excel is a very complex system in itself, and lays outside the scope of this framework. You may have better luck with pre-existing projects such as ExcelJS.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
