### ISSUE TITLE
[Feature Request] v-card-action-area

### ISSUE THREAD

**Issue by hareku** [vuetifyjs/vuetify#6253]
### Problem to solve
I want to use (a) tag in v-card.
But I don't want to surround v-card-actions with (a) tag.

### Proposed solution
https://material-ui.com/demos/cards/
https://material-ui.com/api/card-action-area/

Can vuetify implement v-card-actions-area like material-ui ?

**Comment by nekosaur** [comment]
Please show an example of what you are trying to achieve, using a codepen.

**Comment by nekosaur** [comment]
I'm still not sure exactly what you're after. Is it the ripple effect? That can be done with the `v-ripple` directive. https://codepen.io/anon/pen/pGgoJx

**Comment by hareku** [comment]
@nekosaur 
Thank you for your codepen.

I want an effect to dim a little like material-ui's CardActionArea when hovering.
v-hover is different from what i want.

**Comment by nekosaur** [comment]
You can use custom css for that.

**Comment by hareku** [comment]
OK.
I'll implement custom CSS myself.

But if there is an abstracted css or component, that would be helpful for us.

Thank you.
