### ISSUE TITLE
[Bug Report] Activator in disabled menu gets "pointer" cursor instead of "default" (regression since 1.4.0)

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#6256]
### Versions and Environment
**Vuetify:** 1.4.3
**Last working version:** 1.3.16
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
Hover over the second button

### Expected Behavior
It should show a default cursor

### Actual Behavior
It shows a pointer cursor

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/WPQWPw" target="_blank">https://codepen.io/everhardt/pen/WPQWPw</a>

### Other comments
This issue was earlier filed for Vuetify 0.14 (and fixed), see https://github.com/vuetifyjs/vuetify/issues/1479. As that one is closed and this is a regression, I assume it made more sense to open a new ticket.

Proof that it does work under 1.3.16 can be found at https://codepen.io/everhardt/pen/ZwbZPJ

**Comment by tux2nicolae** [comment]
Hi, I encounter the same issue, 

From my research I found that all classes under `__activator` have the `cursor: pointer` style property in [_menus.styl](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/components/_menus.styl).

Also I noticed that there is a class `v-menu__activator--disabled` added to the DOM element, which has no style props, maybe the fix would be to just add `cursor: default` to it. Just trying to help.

```
&--disabled 
  *
    cursor: default
```

**Comment by jacekkarczmarczyk** [comment]
Workaround: use scoped slot https://codepen.io/anon/pen/moMyJd

**Comment by jacekkarczmarczyk** [comment]
In 2.0 all activators must be placed in the scoped slot

**Comment by tpiekarski** [comment]
This is not a solution, this is a workaround for an obvious bug. 
I'd much appreciate if this issue would be reopened and solved. 
I hope I am not the only one, so please reconsider.
