### ISSUE TITLE
[Feature Request] Using Carousel Items as Links

### ISSUE THREAD

**Issue by Talha-T** [vuetifyjs/vuetify#6261]
### Problem to solve
Being able to navigate to a desired page on carousel item click. According to [this github issue](https://github.com/vuetifyjs/vuetify/issues/1709) , it should be already added; but it doesn't work currently.

Codepen: https://codepen.io/anon/pen/PVZPGJ

### Proposed solution
Carousel Items should support "to" property for nuxt, so I should be able to navigate to a desired page when a carousel item is clicked.

**Comment by jacekkarczmarczyk** [comment]
Can you please provide the codepen reproduction?
