### ISSUE TITLE
[Bug Report] Closing animation on v-expansion-panel is missing when css tag "user-select" is set to none

### ISSUE THREAD

**Issue by olegjo** [vuetifyjs/vuetify#6262]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Create a v-expansion-panel where the container element has style
```
    user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    -webkit-touch-callout: none;
    -o-user-select: none;
    -moz-user-select: none;
```

### Expected Behavior
When closing an expansion panel, there is usually an animation, however when the parent (any parent) element has the specified style, the animation is only working on open.

### Actual Behavior
Expansion panel animation is missing on close.

### Reproduction Link
<a href="https://codepen.io/olegjo/pen/JxGdwg" target="_blank">https://codepen.io/olegjo/pen/JxGdwg</a>

### Other comments
I have tested for the specified browsers, however more browsers may be (and likely are) affected.

**Comment by johnleider** [comment]
This is resolved on v1.5.
