### ISSUE TITLE
[Feature Request] VCalendar: Overlapping events

### ISSUE THREAD

**Issue by xplodwild** [vuetifyjs/vuetify#6264]
### Problem to solve
It seems like V-Calendar's event template only takes into account the fact that events cannot overlap: the example sets a full width for every event, which prevents overlapping events from display properly (i.e. one on top of the other, instead of one next to each other).

### Proposed solution
Is there any plan to integrate the width/x calculation inside V-Calendar, or is it something we're supposed to implement ourselves?

**Comment by ClickerMonkey** [comment]
The current calendar is not event specific, but it will be a feature if/when a v-event-calendar component is made.

(this is not an official vuetify plan, I'll be making enhancements and the other team members may mold what I end up doing)

**Comment by ClickerMonkey** [comment]
Related PR #6475

**Comment by smart-assistant** [comment]
Any update about this PR ?
