### ISSUE TITLE
[Bug Report] VCalendar: Weekly view: timeToY doesn't properly account for minutes

### ISSUE THREAD

**Issue by xplodwild** [vuetifyjs/vuetify#6265]
### Versions and Environment
**Vuetify:** 1.5.0-beta.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
1) Feed the timeToY function with a time of "12:30" (or anything :30)
2) Observe the resulting calendar position

### Expected Behavior
The event top border should be at half the height of the 12pm to 1pm block, to show the :30 delay of the event, as opposed to events o'clock.

### Actual Behavior
In the provided codepen (which is simply the Week example in the docs), the Mash Potatoes event is scheduled at 12:30. However, in the calendar, it appears directly at "12pm", not slightly offset to account for the half-hour delay.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ErPZrK" target="_blank">https://codepen.io/anon/pen/ErPZrK</a>

**Comment by ClickerMonkey** [comment]
I found the issue, thanks for reporting it
