### ISSUE TITLE
[Bug Report] Nested Lists in Nav Drawer Caret/Arrow Glitch (Mobile)

### ISSUE THREAD

**Issue by chriseickemeyerGH** [vuetifyjs/vuetify#6266]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Safari, Google Chrome
**OS:** iOS

### Steps to reproduce
1. Create a nested list within a nav drawer
2. In order to see the issue, the nested list needs to go from less than 100% height before opening to more than 100% after it has been opened. (I think)
3. Open and close the nested list; the caret will disappear/become displaced upon closing.
4. Only happens on mobile. (iOS for sure, unsure about Android)

### Expected Behavior
Smooth caret animation

### Actual Behavior
Brief displacement/disappearing of arrow

### Reproduction Link
<a href="https://codepen.io/DabbyDabber/pen/VgemPJ" target="_blank">https://codepen.io/DabbyDabber/pen/VgemPJ</a>

### Other comments
I tried removing the scrollbar with css, but it did not work.

**Comment by MajesticPotatoe** [comment]
No issue on android.
