### ISSUE TITLE
[Bug Report] Unbalanced button text/icon spacing using 'right' prop

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#6272]
### Versions and Environment
**Vuetify:** 1.5.0-beta.2
**Vue:** 2.5.21
**Browsers:** Chrome 72.0.3626.71
**OS:** Windows 10

### Steps to reproduce
Open the codepen and note that the spacing between the Prev button text and its associated icon does not match the spacing between the Next button text and its associated icon. Similar imbalance noted between the icon and the button edge.

### Expected Behavior
The spacing between button text and icons should be balanced when using the `right` prop or not. Same for icon to button edge spacing.

### Actual Behavior
Unbalanced spacing.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/xMVQdo" target="_blank">https://codepen.io/185driver/pen/xMVQdo</a>

### Other comments
My codepen is simply a copy of the vuetify docs example found here:
https://next.vuetifyjs.com/en-US/components/calendars#usage

![prev-btn](https://user-images.githubusercontent.com/1835454/51808114-f0cdb380-22d2-11e9-9039-6b1b7583a879.png)
![next-btn](https://user-images.githubusercontent.com/1835454/51808107-e90e0f00-22d2-11e9-823d-49429be2a3a2.png)

**Comment by KaelWD** [comment]
Use `left` on the other button.

**Comment by MajesticPotatoe** [comment]
usage example updated in dev to reflect this https://github.com/vuetifyjs/vuetify/commit/879c0491135799d9689c0cd7b507803978acebf8
