### ISSUE TITLE
[Feature Request] v-select auto width depending of content

### ISSUE THREAD

**Issue by Extarys** [vuetifyjs/vuetify#6275]
### Problem to solve
It would allow for a better flow of content depending of the usage and better UI overall.

### Proposed solution
```
<v-select
    :items="$i18n.locales"
    :item-value="code"
    :to="switchLocalePath(locale)"
    v-model="locale"
    class="pa-0 ma-0"
    item-text="name"
    hide-details
    single-line
    dense
    autowidth
  />
```
![image](https://user-images.githubusercontent.com/11581433/51817132-759adc00-2297-11e9-8309-2ad1e5712980.png)
![image](https://user-images.githubusercontent.com/11581433/51817150-83506180-2297-11e9-9e50-aea51e84659b.png)

Check google sign in page at the bottom.

**Comment by KaelWD** [comment]
It already does, but for some reason there's a hidden input with 218px width:
![image](https://user-images.githubusercontent.com/16421948/51818321-8e9c9f00-2322-11e9-8021-ad491fe1d856.png)
https://codepen.io/anon/pen/WPwqYJ?editors=1010

**Comment by Extarys** [comment]
Oh good catch @KaelWD I didn't notice the empty input there.

**Comment by heidricklevi** [comment]
I can take a look at this one

**Comment by heidricklevi** [comment]
This gets generated when the default slot is generated. [at this line](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSelect/VSelect.js#L357)

**Comment by 1hakr** [comment]
Guys, any update on this or a workaround till this is fixed?

**Comment by admxxi** [comment]
Hi everybody, can we expect that feature request be done soon?

**Comment by jacekkarczmarczyk** [comment]
For now you can fix it with simple css https://codepen.io/anon/pen/WBaarG (the problem is that there's no space for label or placeholder if there's not value selected)

**Comment by 1hakr** [comment]
You can add a min-width to make it visible 
https://codepen.io/anon/pen/WBaYYY

**Comment by douglasg14b** [comment]
Problem with specifying  min-width is that it causes anything in the flex grid to push outside of it's bounds if an item is set to grow in that row.

Instead of causing the growing item to just grow by less.

**Comment by Teellcory** [comment]
Can it be changed to let the input do whatever it does by default when nothing is selected, but when something is selected (a span becoming a sibling of the input), set the input to a width of 0?

**Comment by arnaldoperez** [comment]
Besides de CSS trick `.v-select__selections input { display: none}` I also put the `v-select` insde a `v-col` and set its `cols="auto"`. Works great!!

**Comment by KaelWD** [comment]
Workaround: https://codepen.io/kaelwd/pen/PowBxoK

**Comment by tamirvs** [comment]
```.v-select__selections input { display: none }``` messes up the keyboard lookup.
I think ```.v-select__selections input { width: 0 }``` works.

**Comment by rveruna** [comment]
is there any news on this?

**Comment by lovkiymusic** [comment]
guyz, wazzup, vuetify is amazing, but... select width bug from 2019?) does anyone have nice solution? scoped styles is bad i think, thanx a lot

**Comment by Jaffsterz** [comment]
In case it's useful for anyone, I got round this by putting ref="selectComponent" on the v-select, and  adding an @change listener to it and doing this in the listener:

`if (this.localSelectedItems.length > 0) {
        this.$refs.selectComponent.$el.querySelector('.v-select__selections input').style.width = 0;
} else {
        this.$refs.selectComponent.$el.querySelector('.v-select__selections input').style.width = '';
}`

It preserves the required input space when no selections have been made, and removes it otherwise.

**Comment by lovkiymusic** [comment]
I always have items in items array selections, redundantly create another listener for fix this little bug, i fix it with @arnaldoperez advice, thanx him for it.

> Besides de CSS trick `.v-select__selections input { display: none}` I also put the `v-select` insde a `v-col` and set its `cols="auto"`. Works great!!

**Comment by jost-s** [comment]
Hiding the input field in this manner breaks `v-select` in the current version 2.3.8.
What works very well is
```
.v-text-field .v-select__slot .v-select__selection--comma
  min-width: min-content
```
and then also `style="min-width: min-content;"` for the `v-select`

**Comment by alenamm** [comment]
I hope this helps to someone, because in my case input would slide under the selected item (.vs__selected) and I fixed it by changing flex configurations of the parent div to flex-wrap: nowrap: 
 .vs__selected-options {
    flex-wrap: nowrap;
  }

**Comment by djmore4** [comment]
I'm guessing it's not exactly reasonable to expect that this is going to be fixed any time soon given how long its been open already but are there any updates that could be provided on if this is ever going to be fixed?

**Comment by Flamenco** [comment]
So using the current version of Vuetify, here is what works for me.

Add a class to the select to indicate a *fit* style. 

```js
<v-select class='fit' />
```

Create the following CSS to target the select element.  The text-overflow will prevent a pesky ellipsis.

```css
.v-select.fit {
  width: min-content;
}
.v-select.fit  .v-select__selection--comma {
    text-overflow: unset;
}
```

**Comment by sophiestix** [comment]
> In case it's useful for anyone else, I got round this by putting ref="selectComponent" on the v-select, and adding an @change listener to it and doing this in the listener:
> 
> `if (this.localSelectedItems.length > 0) { this.$refs.selectComponent.$el.querySelector('.v-select__selections input').style.width = 0; } else { this.$refs.selectComponent.$el.querySelector('.v-select__selections input').style.width = ''; }`
> 
> where localSelectedItems is my selected items array.
> 
> It preserves the required input space when no selections have been made, and removes it otherwise.

I used a similar approach to Jaffsterz's solution by creating a method that I use when my component mounts or on change:
```
hideExtraInput() {
      if (this.selectedGroups.length > 0) {
        this.$refs.selectComponent.$el.querySelector('.v-select__selections input').type = 'hidden';
      }
},
```

**Comment by greyhixson** [comment]
None of the above solutions worked for me. My solution is this:
`<style>`
`.v-select__selections input { `
`  width: 0 !important; `
`  min-width: 0 !important;`
`}`
`</style>`

I'm using a v-autocomplete with a v-slot for the selection and this keeps the width of input 0px at all times when selected without interfering with keyboard input. 

![image](https://user-images.githubusercontent.com/27748673/149864858-386e2a19-8b30-4507-9f08-f475d5bf1cb5.png)
![image](https://user-images.githubusercontent.com/27748673/149864886-60c28e9b-c5e2-493d-8e47-23054e36a5bb.png)

**Comment by aentwist** [comment]
👀

**Comment by Julyemerson** [comment]
After hours, I can solve this problem with a **prop full-width** 

Vuetify V2.6.5
https://vuetifyjs.com/en/api/v-select/#props-full-width

**Comment by alfianwahid** [comment]
This issue still exist in vuetify 3
v-select (with no selected item) inside v-col auto
![image](https://github.com/vuetifyjs/vuetify/assets/2808896/049a7f8c-455e-4e1a-92f3-adcb0cd14a2b)

example:
https://play.vuetifyjs.com/#eNptUMFKxDAQ/ZUhl15qK66n0hVEQTzsqSfZ7iHWWQmkSUimlaX0350mu24VD2Hy3rzJvJf9JILvykfninFAUYmasHdaEj60BqAeb6Rz8RpBZw1JZdCfqUh6+/UDzyoNfMK2FXIg24pVOwoCauwItHxHzaImwSc7GPKnVkCl2MUyHivP1+VlaL2JSV5ztcL46iV113YXJqWpy1VKhqHzyhEEpCGFVb2znmACj0eY4ehtDxl/ULbIgcOZQBDNwRb2aeEEpEhjBdmr+bAGg5JZDqPUQ+SeM5jzv8pGmU/Jq3ClbF7+U+6klqffT+7eLsLDEimFYPtizsWm2BT3ItW7W3H4BrdklxM=

**Comment by sniperadmin** [comment]
Ok it is time to knock this issue out!

We can utilize the functionality of deep selectors in Vue:

```html
<v-select class="meow" />
```
And we access the nested input which has the extra width and set it to `0` (please don't hide the input to avoid and cons)
```css
.meow {
  width: max-content;
}
.meow::v-deep input {
  width: 0;
}
```

Source: https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles

**Comment by ARBUCHELI** [comment]
I have a solution for this: 

If you are using the <v-select> withing another container.  Wrap the <v-select> in a div and set the width on the parent div:

Something like this:

`<div class="v-select-container">
                            <v-select`
                            --- > Here all the props that <v-select> accepts
 Then, you can do something like this in your scss
 
`<style lang="scss" scoped>
.parent_container {
    width: 100%; 
    display: flex;
    flex-direction: column;

    .v-select-container {
        flex: 1;
  }
}
</style>`

**Comment by devpaps** [comment]
> Ok it is time to knock this issue out!
> 
> We can utilize the functionality of deep selectors in Vue:
> 
> ```
> <v-select class="meow" />
> ```
> 
> And we access the nested input which has the extra width and set it to `0` (please don't hide the input to avoid any cons)
> 
> ```css
> .meow {
>   width: max-content;
> }
> .meow::v-deep input {
>   width: 0;
> }
> ```
> 
> Source: https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles

Thank you for this! It helped me today. 👍🏻

**Comment by sniperadmin** [comment]
> > Ok it is time to knock this issue out!
> > We can utilize the functionality of deep selectors in Vue:
> > ```
> > <v-select class="meow" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And we access the nested input which has the extra width and set it to `0` (please don't hide the input to avoid any cons)
> > ```css
> > .meow {
> >   width: max-content;
> > }
> > .meow::v-deep input {
> >   width: 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Source: https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles
> 
> Thank you for this! It helped me today. 👍🏻

I'm glad that this helped :)
