### ISSUE TITLE
[Feature Request] Custom Date Picker Event Indicator Template

### ISSUE THREAD

**Issue by allanchua101** [vuetifyjs/vuetify#6276]
### Problem to solve
There is currently no way to support customised / templated calendar events in Vuetify.

[See Date Picker Events](
https://vuetifyjs.com/en/components/date-pickers#date-pickers-events)

### Proposed solution
Please introduce slots or scoped slots that could be utilised to customise the appearance of calendar events.

**Comment by ClickerMonkey** [comment]
Events were introduced to v-calendar in 2.0.
