### ISSUE TITLE
[Bug Report] Formatted datetime picker wont update when reset form function is run

### ISSUE THREAD

**Issue by D3m1urg0** [vuetifyjs/vuetify#6277]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Create a formatted datepicker (following the documentation example) inside a referenced form, and a button that runs a refs.form.reset()

### Expected Behavior
the reset button will clear the datepicker value

### Actual Behavior
because the formatter works on @blur and the reset button never focus the datetime field the reset of the data wont happen

### Reproduction Link
<a href="https://codepen.io/anon/pen/gqMLeV?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/gqMLeV?&editable=true&editors=101</a>

### Other comments
sorry for my bad english language, i am a foreigner ^^"

**Comment by aburai** [comment]
this doesn't work because you have a computed value in the textfield, use v-model="date" and it works
you can set the formatted date by example to the field hint property

**Comment by KaelWD** [comment]
Date pickers are not counted as form controls, so `reset` only clears the text field. As @aburai pointed out, you need to use v-model or listen for the text field's change event.

**Comment by lucafaggianelli** [comment]
@D3m1urg0 if it's useful to you, here my date picker with custom formatting and clear-ability, I use the `v-text-field` `click:clear` event to do the job:

```vue
<v-menu
    ref="pickermenu"
    v-model="menu"
    offset-y
    :close-on-content-click="closeOnClick"
    max-width="290px"
    min-width="290px"
    :nudge-right="40"
    :disabled="disabled"
  >
    <template v-slot:activator="{ on }">
      <v-text-field
        v-model="dateFormatted"
        :label="label"
        readonly
        clearable
        prepend-icon="event"
        :disabled="disabled"
        v-on="on"
        @click:clear="dateValue = null"
      />
    </template>

    <v-date-picker
      v-model="dateValue"
      :allowed-dates="allowedDates"
      :first-day-of-week="1"
      no-title
      scrollable
      actions
    >
      <v-spacer />

      <v-btn
        text
        color="primary"
        @click="menu = false"
      >
        Close
      </v-btn>
    </v-date-picker>
  </v-menu>
```

**Comment by alijahanpak** [comment]
try this: 
[Working example](https://codepen.io/ali-jahanpak/pen/QWjLaVv)
