### ISSUE TITLE
[Bug Report] Assigning new array in v-tabs component causes issues 

### ISSUE THREAD

**Issue by BenKoloski** [vuetifyjs/vuetify#6278]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.12.4

### Steps to reproduce
(1) Create a v-tab component and a v-tab-item component, both with v-for directives iterating over a data property "items" and a key set to "item.id"
(2) In the data method, define "items" to be an array of objects with a property "id."
(3) At some point after the initial render, assign a new array to the reactive data property "items" with a subset of the original array.

### Expected Behavior
The user should be able to activate all of the tabs by clicking on them.

### Actual Behavior
Not all of the tabs are able to be activated.

### Reproduction Link
<a href="https://codepen.io/corbatacolombiana/pen/NoraNK" target="_blank">https://codepen.io/corbatacolombiana/pen/NoraNK</a>

**Comment by blalan05** [comment]
Do you mean something like this? https://codepen.io/anon/pen/BMzwGN

**Comment by BenKoloski** [comment]
I still observe unexpected behavior in the result.

**Comment by aburai** [comment]
@BenKoloski https://codepen.io/aburai/pen/LqZedW use only one v-for

**Comment by BenKoloski** [comment]
This is working for me. Thank you very much!

**Comment by BenKoloski** [comment]
@aburai Sorry: when I actually compile this solution on my machine, I receive an error: "<template> cannot be keyed. Place the key on real elements instead." When I move the key attribute from the template to the elements inside, the errors persist. Any thoughts?

**Comment by aburai** [comment]
@BenKoloski maybe depending on vue version, use a span as workaround

`<span v-for="(item, index) in list" :key="index"></span>`

**Comment by johnleider** [comment]
My suggestion would be to key v-tabs to trigger a reset as a workaround for now: https://codepen.io/johnjleider/pen/ZwJQBO?editors=1011

**Comment by johnleider** [comment]
Fixed in f22d754
