### ISSUE TITLE
Feature Request: Make body un-scrollable when a dialog is open

### ISSUE THREAD

**Issue by SaMiCoOo** [vuetifyjs/vuetify#628]
Make body un-scrollable when a dialog is open
=======================
- I think it is normal to add a prop to dialogs to make sure that the *body* of the page is not scrollable while the dialog is open.
- My own workaround for this:

define a class that makes overflow-y: hidden
```styl
body.dialog-is-open
  overflow-y: hidden !important
```

and in component containing the dialog
```js
 watch : {
        dialog(value, old) {
        const body = document.body
        if (value) {
          body.classList.add('dialog-is-open')
        } else {
          body.classList.remove('dialog-is-open')
        }
      }
```

can also be done by computed class property, and many other ways, but in my case I preferred doing it like this. But I think the best way is to have it on  the *dialog* component itself through a prop.

- It avoids troublesome view glitches specially on mobile viewports.

I ❤️  Vuetify

**Comment by johnleider** [comment]
When just overflow is hidden, the screen will have a noticeable jump as the scrollbar is removed. I have done this in the past and had quite the conversation in regards to the pros and cons. There are other ways to achieve this, such as having the dialog screen and dialog outside of the normal flow, but this has its own complications.

I'm going to leave this open for now for discussion.

**Comment by smares** [comment]
Vue Material and Element handle this differently but in the end both implementations are better than what Vuetify is doing. Maybe you can have a look. If I remember correctly, Element uses JS to calculate the width of the scrollbar and uses that as padding while setting overflow to hidden, Vue Material uses CSS pointer-events to make the body ignore scrolling.
