### ISSUE TITLE
[Feature Request] Bottom Navigation Inset

### ISSUE THREAD

**Issue by FernandoFranco** [vuetifyjs/vuetify#6282]
### Problem to solve
Bottom Navigation only positioned bottom of the v-navigation-drawer fixed app component.
Does Not have a inset like the v-footer.
https://codepen.io/anon/pen/omLmmQ

### Proposed solution
Inset prop like v-footer inset prop to change paddings of the application

**Comment by MajesticPotatoe** [comment]
simple workaround would be to wrap in a `<v-footer inset app>`
https://codepen.io/anon/pen/gqMEPp

Will slate for 2.0.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
