### ISSUE TITLE
[Bug Report] Editable readonly v-text-field

### ISSUE THREAD

**Issue by JavaPantry** [vuetifyjs/vuetify#6288]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Open link to codesandbox

### Expected Behavior
Text field should be read only

### Actual Behavior
Text field editable

### Reproduction Link
<a href="https://codesandbox.io/s/yvjnmw7j11" target="_blank">https://codesandbox.io/s/yvjnmw7j11</a>

### Other comments
I saw many bug reports with similar subject. Discussed and closed. In codepen it works but in my project and in given above codesanbox it is NOT.

**Comment by JavaPantry** [comment]
PS. just checked

```
<v-text-field name="partCode"
                            readOnly
                            label="Parts Code"
                            v-model="partCode">
</v-text-field>
``` 
render input tag without readonly property

```
<input aria-label="Parts Code" name="partCode" type="text">
```

**Comment by MajesticPotatoe** [comment]
prop is `readonly` not `readOnly`
![321](https://user-images.githubusercontent.com/27827979/51946344-3089bd80-23ef-11e9-9e4e-d8b643115235.png)
