### ISSUE TITLE
[Bug Report] Custom component inside v-data-iterator has copied data properties

### ISSUE THREAD

**Issue by poganytamastsys** [vuetifyjs/vuetify#6296]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a custom component with data properties inside. Put the component into a multi page v-data-iterator

### Expected Behavior
Each component should have completely separate data properties.

### Actual Behavior
Components on the same position have the same data properties.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KJNZwZ" target="_blank">https://codepen.io/anon/pen/KJNZwZ</a>

### Other comments
In my example "count" is the data property. On the first page click on the first button, you see count is increasing. Go to the second page, button 5 will have the exact same counter as button 0,  also Button 10, etc... This is unwanted behaviour, each component should have different data. Also I noticed that the created, mounter, etc... events are not fired for elements on page two, three...

**Comment by jacekkarczmarczyk** [comment]
All items should have defined a unique key, but can't get it to work with the key as well https://codepen.io/anon/pen/BMQYRG

**Comment by nekosaur** [comment]
? <https://codepen.io/anon/pen/MLbqaX?editors=1010>

**Comment by jacekkarczmarczyk** [comment]
Probably items should be automatically keyed as it is done in `v-data-table`, for now you need to use @nekosaur 's solution

**Comment by poganytamastsys** [comment]
Thanks for the replies, using both item-key and :key solved the problem in my production code.
