### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#63]
vuetify.js:202 Uncaught TypeError: Cannot read property 'length' of undefined

close @ vuetify.js:202
boundFn @ vue.runtime.common.js:126
EventEmitter.emit @ vuetify.js:4073
pub @ vuetify.js:272
click @ vuetify.js:547

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by johnleider** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/commit/97c68918f229b73383f193ca52dc5f3019ac82db
