### ISSUE TITLE
Event for Checkbox

### ISSUE THREAD

**Issue by ssantanuberaa** [vuetifyjs/vuetify#630]
I came up with a situation where I need to execute a method whenever a checkbox is selected or deselected. After searching on the Checkbox control API on vuetifyjs.com, it seems there's no event associated with the checkbox. How can I achieve this ?

**Comment by zeljic** [comment]
Here is simple example with "change" event
https://jsfiddle.net/2vtk5nLp/2/

**Comment by johnleider** [comment]
@zeljic is correct, you can use @change.native for checkbox/radio/switches.

**Comment by ssantanuberaa** [comment]
Thank you so much for the reply. Its working now............
