### ISSUE TITLE
[Bug Report] Vuetify 2.0 , VBtn.sass not found in VBtn.js

### ISSUE THREAD

**Issue by rwatts3** [vuetifyjs/vuetify#6300]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
1. Using `2.0.0-alpha.3`
2. Create a component with `v-btn`
3. Styling is missing due to missing `VBtn.sass` file.

### Expected Behavior
The sass file may be missing from the latest alpha release. I see it working in the next.vuetifyjs.com examples.

### Actual Behavior
Using nuxt, an error is thrown expressing that the sass file is missing. See the comment below.

### Reproduction Link
<a href="https://codesandbox.io/s/o10jklw1m5" target="_blank">https://codesandbox.io/s/o10jklw1m5</a>

### Other comments
This relative module was not found:                                                                                                                         friendly-errors 11:59:33
                                                                                                                                                            friendly-errors 11:59:33
* ../../../src/components/VBtn/VBtn.sass in ./node_modules/vuetify/lib/components/VBtn/VBtn.js

**Comment by KaelWD** [comment]
Your link doesn't work, and that file does appear to exist <https://unpkg.com/vuetify@2.0.0-alpha.3/src/components/VBtn/VBtn.sass>

**Comment by rwatts3** [comment]
Correction feel free to close it appears this was an error on my part. 
In nuxt when I imported vuetify I imported it from `vuetify/lib'

**Comment by Denny143** [comment]
Hi @rwatts3 , I am trying to update to vuetify 2.0.0-alpha  in my nuxt project but I seem to get a build error "This relative module was not found:  * ../src/styles/main.sass in ./node_modules/vuetify/lib/framework.js". Currently, my in nuxt.config.js , vuetify is imported from 'vuetify/lib'. How do I change the import line to get vuetify 2.0.0 working on my nuxt project? Any help would be much appreciated. Thanks

**Comment by gpproton** [comment]
I'm also looking to upgrade my nuxt project but can't see any instruction anywhere.

**Comment by kyiv1pbed** [comment]
Hi guys!

The next guide was very helpful for me

https://github.com/nuxt-community/vuetify-module/
