### ISSUE TITLE
[Bug Report] Hover Styling Not Working Via Vue Build

### ISSUE THREAD

**Issue by itsMikeLowrey** [vuetifyjs/vuetify#6306]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.6

### Steps to reproduce
Clone git
npm install 
npm run build
serve files

### Expected Behavior
Hover Text To be Centered

### Actual Behavior
Hover Text Dosen't have any styling

### Reproduction Link
<a href="https://github.com/DecentralizeJustice/MultisigBlog" target="_blank">https://github.com/DecentralizeJustice/MultisigBlog</a>

### Other comments
I have attempted:
* Remove Scoped Styling
* Unique Id to specify vue reveal component 
* Deeply Selector
*  Add v-app to template
* Installed style packages https://vuetifyjs.com/en/framework/a-la-carte#vuetify-loader
I think it is an issue with the vue build. It works when you npm run serve but not build, as here: https://loving-mccarthy-a818c7.netlify.com/

**Comment by jacekkarczmarczyk** [comment]
It's not centered because you didn't make it centered
https://codepen.io/anon/pen/QYddWW

**Comment by itsMikeLowrey** [comment]
I applied your fix and built it. It does not work here: https://loving-mccarthy-a818c7.netlify.com/ . I think my example followed documentation well, but i think it has something to do with the compilation of the files via npm run build, since it works in dev mode but not when served from dist folder via a server.

**Comment by jacekkarczmarczyk** [comment]
Try Kael's solution, use any of grid components

**Comment by itsMikeLowrey** [comment]
I started a fresh build and it worked, served and in dev mode. I gutted the component from my initial repo, and filled it in with the same code from the example. It works when you run it via npm run serve but not when you serve it from the dist folder. 
fresh [working build](https://github.com/itsMikeLowrey/Test-Repo) 
updated initial 50% working [repo](https://github.com/DecentralizeJustice/MultisigBlog) 
How can I test the gridd css idea? Thanks for the help again.

**Comment by KaelWD** [comment]
Use any grid component (VLayout etc.) this way: https://vuetifyjs.com/en/framework/a-la-carte#markup-js-a-la-carte

**Comment by itsMikeLowrey** [comment]
I attempted to try and implement your fix but I was unable to figure out how to get my code to show. I was originally using the add vuetify plugin, so I attempted to convert to the example that you linked to but my nothing shows now.
