### ISSUE TITLE
[Feature Request] Calendar to support multi-day events

### ISSUE THREAD

**Issue by scp-nm** [vuetifyjs/vuetify#6307]
### Problem to solve
This will allow for the UI to show events in the calendar that span more than one day.

### Proposed solution
Follow how Google have implemented it in their calendar:

![image](https://user-images.githubusercontent.com/32037777/52041555-aba7bc80-2532-11e9-9ce2-e410662df9dc.png)

**Comment by ClickerMonkey** [comment]
This is already possible with negative margins on events that span days. The current calendar is not event specific, but it will be a feature if/when a v-event-calendar component is made.

**Comment by TheInvoker** [comment]
when will this feature be ready?

**Comment by ClickerMonkey** [comment]
v2.0.0 will allow you to pass an array of events to the calendar and will automatically handle multi day and timed events.

**Comment by ClickerMonkey** [comment]
Related PR #6475

**Comment by vip30** [comment]
I saw the pr from @ClickerMonkey has been closed, so is this feature request still valid? I guess this feature is pretty common in a calendar component.

**Comment by vip30** [comment]
@johnleider May I confirm that the reason of the pr is not merged is because the test coverage is getting low(0.1%)?

**Comment by MajesticPotatoe** [comment]
Test coverage and the maintainer is somewhat MIA. Was closed due to inactivity.

**Comment by ClickerMonkey** [comment]
I'm not MIA too much, the PR was completely ready in my eyes and I stated that much of the new code was not unit testable. The codebase for vuetify was constantly changing in major ways during it's development and I didn't have the time to update my code constantly to account for everyone's changes.

If the test coverage wasn't an issue I could create a new branch and apply my changes and fixes - but I'm hesitant to do that if it's just going to sit there without clear guidance on what precisely needs done while it very quickly becomes out of date and incompatible with the code base.

I would love for my v2.0 changes to be merged in, there are attractive visual changes made and the necessary event features which really push the component to the next level.

Let me know what you think!

**Comment by MajesticPotatoe** [comment]
Ill converse with john and see whats going on with it, he may just been click happy and saw there was no motion on it and slapped the close button lol. (also i think there were merge conflicts at the time)
