### ISSUE TITLE
[Bug Report] Multiple v-select with prefix cause an error

### ISSUE THREAD

**Issue by andrzejenne** [vuetifyjs/vuetify#6308]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
If more than 2 v-select components, app throws error: "Cannot read property 'offsetWidth' of undefined". 
Components can be in v-for or staticly managed.

### Expected Behavior
Component v-select should not throw an error if prefix is defined.

### Actual Behavior
Component v-select is failing when prefix is defined.

### Reproduction Link
<a href="https://codepen.io/lamasutra/pen/xMgrWj" target="_blank">https://codepen.io/lamasutra/pen/xMgrWj</a>

### Other comments
The problem is, that $ref is not defined when computed value prefixWidth is accessed.

Algorithm for prefixWidth should be optimized.

I have tried to replace that algo, but when prefix ref is not defined, prefix element overlaps others.

Layout should be computed after all necessary $refs are ready.

I have also tried v-text-field and v-checkbox, but they are working correctly.

You can experiment with codepen, change input types etc.

**Comment by jacekkarczmarczyk** [comment]
That has nothing to do with multiple selects, but indeed there is something wrong
https://codepen.io/anon/pen/XORwmx?editors=1000

**Comment by KaelWD** [comment]
Fixed in v2.0.0-alpha.20 with a081e21dd16abe9d2db173268de23885d17335af
