### ISSUE TITLE
[Bug Report] v-select doesn't update inner input element

### ISSUE THREAD

**Issue by EagleEyeBW** [vuetifyjs/vuetify#6310]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Select something in the select component

### Expected Behavior
the selected item has to be set as value in the input

### Actual Behavior
nothing is set

### Reproduction Link
<a href="https://jsfiddle.net/javaeagle/e8nft0mz/4/" target="_blank">https://jsfiddle.net/javaeagle/e8nft0mz/4/</a>

**Comment by EagleEyeBW** [comment]
I just detected the same behaviour of the v-checkbox, this also didn't set the value property of the input

**Comment by johnleider** [comment]
This is still a maybe but not something that has a champion to finish before v2.0

**Comment by azeos** [comment]
I have multiple selects that are generated from a JSON object, all with dynamic `name`s. I'm trying to send a fom using `formData`, but apparently because of this bug, all select inputs have null values.

What can I do in the mean time?

Thanks!
