### ISSUE TITLE
[Feature Request] How to use @mdi/js icons with Vuetify to have treeshaking on icons? 

### ISSUE THREAD

**Issue by alfredriesen** [vuetifyjs/vuetify#6318]
### Problem to solve
reduce build size

### Proposed solution
To include this option on configuration

**Comment by KaelWD** [comment]
If they provide a vue component you can use it the same as vue-fontawesome: https://vuetifyjs.com/en/framework/icons#custom-components

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
