### ISSUE TITLE
[Bug Report] Navigation Drawer loses mobile swap event

### ISSUE THREAD

**Issue by JonathanVandal** [vuetifyjs/vuetify#6319]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 72.0.3626.81
**OS:** Android

### Steps to reproduce
Create a navigation drawer and a toolbar inside a component (e.g named navbar). Use this component in App.vue inside `<v-app></v-app> `

### Expected Behavior
On mobile, grab the drawer from the edge of the mobile and open it by swapping right.

### Actual Behavior
On mobile, grab the drawer from the edge of the mobile and swapping right, but the drawer stay hidden.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GzWYor" target="_blank">https://codepen.io/anon/pen/GzWYor</a>

### Other comments
If you use directly `<v-navigation-drawer>` inside `<v-app>` there is no problem, it works. The bug appears only when we use the navigation drawer inside a custom component. 
I give you this codepen too to show you that swap event works outside component : https://codepen.io/anon/pen/xMqyEK

I noticed that the bug appears when we wrap the navigation drawer inside html tag (nav / div etc..) and inside a component we need these tags.

**Comment by johnleider** [comment]
Need a better example, this is impossible to debug.

**Comment by JonathanVandal** [comment]
Ok so I create another example. I took [this example](https://vuetifyjs.com/en/components/navigation-drawers#temporary) for the code base from the Vuetify documentation.

[Here is my codepen](https://codepen.io/anon/pen/RvgzYx)

If you go on your mobile phone on my codepen you can toggle the drawer with the button but you can't  open it if you slide right with your finger from the edge of the mobile. 

I don't changed lot of code I just wrapped `<v-navigation-drawer>` into `<nav>`. If you remove the nav tag it will works.

**Comment by KaelWD** [comment]
We should be using `offsetParent` instead of `parentNode`

**Comment by JonathanVandal** [comment]
Can I do something while I'm waiting your bug fix ?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
