### ISSUE TITLE
[Bug Report] Prepend inner icon example missing in docs

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#6325]
### Problem to solve
We're missing a version of the text fields, with an inner leading/prepend icon. We like to use these for search fields, to have a search icon before the field. An icon at the END of a field indicates that you can click it, and we do not want to use the icons that are outside the field. That is a legacy component, not part of Material 2. Thanks!

### Proposed solution
Create a version of text fields, that have a leading/prepend icon, INSIDE the field.

**Comment by MajesticPotatoe** [comment]
`prepend-inner-icon` will do this for you. Seems it got overlooked in api, Will update docs.

**Comment by jaminroe** [comment]
@MajesticPotatoe awesome, thanks!
