### ISSUE TITLE
[Feature Request] Add support for conditional required on form components (text, combo and date pickers)

### ISSUE THREAD

**Issue by allanchua101** [vuetifyjs/vuetify#6326]
### Problem to solve
At the date of this ticket's writing, the required attribute of the mentioned components are not supporting binding to required property. This will solve conditionally required use-cases for form controls.

### Proposed solution
Expose con-required property to enable conditionally required property.

**Comment by jacekkarczmarczyk** [comment]
Can you provide a codepen showing the issue?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
