### ISSUE TITLE
[Bug Report] v-select onchange event only pases in selected value, no event object even if using $event

### ISSUE THREAD

**Issue by BuhoSabio** [vuetifyjs/vuetify#6327]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98, Internet Explorer
**OS:** Windows 7

### Steps to reproduce
create a v-select populate it with some options, add change event call method, in method using event ,only the selected option value returned even if you pass to method from change event $event.

### Expected Behavior
obtain event object

### Actual Behavior
only selected option value returned.

### Reproduction Link
<a href="https://codepen.io/buho/pen/daWyrj" target="_blank">https://codepen.io/buho/pen/daWyrj</a>

### Other comments
How can the selected text of a v-select option be returned, using $event only passes in the value, how do I obtain the text? Think it is weird that no event object accessible with v-select.  Beside getting at the text, event object is nice to have for many other reasons.

**Comment by parthibd** [comment]
Try setting `return-object` on `<v-select/>`

**Comment by BuhoSabio** [comment]
Well, guess I should have read API more.
