### ISSUE TITLE
Persistent Drawer opens on resize

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#633]
### Steps to reproduce
Resize the window of a persistent Drawer

### Versions
Vuetify v0.12.2

### What is expected ?
The open/close state of the drawer is maintained, like on the MD docs: https://material-components-web.appspot.com/drawer/persistent-drawer.html

### What is actually happening ?
the drawer reopens

Code is here: https://github.com/vuetifyjs/vuetify/blob/master/src/components/navigation-drawer/NavigationDrawer.js#L105

I would suggest either changing the logic here to maintain its state, or add in a new prop to reopen on resize? I'm willing to submit a PR, but would want feedback on the direction first. 

Cheers!

**Comment by johnleider** [comment]
Also threw in a QoL change for initial render.

**Comment by crocodilered** [comment]
It's still here in vuetify@1.2.3

```
  <v-navigation-drawer
      v-model="drawer"
      clipped
      fixed
      app
      floating
  >
```

When I max window, drawer opens itself.
