### ISSUE TITLE
[Feature Request] Table - Mobile view (small screen)

### ISSUE THREAD

**Issue by bobemmen** [vuetifyjs/vuetify#6331]
### Problem to solve
Table viewing as 'cards' in Mobile view (small screens).

### Proposed solution
 Such as seen in Buefy (https://buefy.github.io/documentation/table

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5234

**Comment by HuthDev** [comment]
Test
