### ISSUE TITLE
[Bug Report] VAutoComplete/VSelect styling issue with "color" prop

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#6344]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Click on the VAutocomplete element in the codepen
Look at selected element's text color

### Expected Behavior
The `color` prop doesn't affect the color of the selected menu item

### Actual Behavior
The `color` prop can lead to scenarios, as linked, where the selected item is unreadable 

### Reproduction Link
<a href="https://codepen.io/anon/pen/xMrRGm?editors=1010" target="_blank">https://codepen.io/anon/pen/xMrRGm?editors=1010</a>

**Comment by johnleider** [comment]
This is no longer inferred by the input color. Here is an example of how to specify a list-item's selected color:

https://play.vuetifyjs.com/#eNqlU01v2zAM/SuEdsgGRPaS7mS0Q3fZfsCOdQ+KzbRa9QVJ9jYE/u+jZLtxnAIbsBxii3wi33ukH07si3NF3yGr2G1E7ZSI+Lk2ALc9F87lVzq0sodGiRDuaqYF/wSO/mo2pTO6Eb6djwCNVdYT2HXeKQQln54jGr6r2RnTCv8yn14rvdbiEX/FRXik1EXbWKKJEZcpgJ5r26JK/NJz2Sf9KknqEvsQSWFYp1OWRxkVEsQIjW8CeqG6BJDtOq3EIff+nqpfJi8kkIjZZXiXatKdEzhvXYBh4edCspIh8gQliQdp2mRqwtfsbLKXWvjfFCnX3cqLoZ7Dl1Yu3afUtf1zdN6HkhZiXJNUKe/JRSs6hsZLFyFg7MY1ktpZH+EEHo8wwNFbDRtavU2Cp40xIUIeHtwlzPvdh3N8HBslHkYGJ0hTqmDzlSyQrdhsQbYV7GDYrgDf0PonOQP2E+AxER4pEjm2ZSM7roUrfgRr6Hs4JRwNOyfI7gpyJMWIdTrX7DlGF6qybFpD14i67H1hMJbG6fKeYKXvTJQaeWv1/U1xU3zkB4yi2JODIS6zBQbND97+DOipVs0mIblblEca7187TkhqtC92Y4cpxGlDQ2pxVbqkfj167tG06NH/q7DVtTfErRBXAhOJoTYDua+keQkr45uQTZ8G/p/Kc7Fp8AMbtmxJlwjke+zxD4KOkTM=

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
