### ISSUE TITLE
[Bug Report] v-dialog's overlay not able to hide dynamically 

### ISSUE THREAD

**Issue by sandy2585** [vuetifyjs/vuetify#6346]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98, Google Chrome, Safari, Microsoft Edge, Internet Explorer, Mozilla Firefox, Opera
**OS:** Windows 10

### Steps to reproduce
1. Open dialog
2. Tab Hide overlay button

### Expected Behavior
Want to hide the overlay when sets the false to hide-overlay and needs to remain the dialog content

### Actual Behavior
overlay not hide

### Reproduction Link
<a href="https://codepen.io/ksankumar/pen/yZXMoV" target="_blank">https://codepen.io/ksankumar/pen/yZXMoV</a>

**Comment by jacekkarczmarczyk** [comment]
It should be `@click="hideme = true"` in the codepen (but it still doesn't work)

**Comment by 185driver** [comment]
That was fast! Thanks John.
