### ISSUE TITLE
[Bug Report] v-menu activator switching causes console errors

### ISSUE THREAD

**Issue by DanielRivers** [vuetifyjs/vuetify#6348]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 72.0.3626.81
**OS:** Windows 10

### Steps to reproduce
Press the button and will result in error to the console.  

### Expected Behavior
Switch activator with no error

### Actual Behavior
Errors to the console.

```[Vue warn]: Error in callback for watcher "activator": "TypeError: t.removeEventListener is not a function"```

```TypeError: t.removeEventListener is not a function```

### Reproduction Link
<a href="https://codepen.io/anon/pen/JxWgqq" target="_blank">https://codepen.io/anon/pen/JxWgqq</a>

### Other comments
This fiddle was put together by a Jacek from another fiddle I showed as example.  I have seen errors to do with both adding and removing of the eventListener

**Comment by KaelWD** [comment]
Basically https://github.com/vuetifyjs/vuetify/issues/5890#issuecomment-450055389, external activators are a bit broken atm

**Comment by DanielRivers** [comment]
Thanks @KaelWD - I can see there is currently no milestone on #5890 is there an idea when this may be addressed?

**Comment by KaelWD** [comment]
Workaround is to pass Element objects instead of a selector: https://codepen.io/anon/pen/aMyYmW?editors=1010

**Comment by KaelWD** [comment]
Going to mark as duplicate of #5890, there's a bunch of similar issues that should really be addressed at the same time.
