### ISSUE TITLE
[Feature Request] Add size-specific helper classes for padding, margin and elevation

### ISSUE THREAD

**Issue by BorjaRafols** [vuetifyjs/vuetify#6351]
### Problem to solve
Currently we can use $vuetify.breakpoint to adjust the padding and marking classes based on viewport size. However if using SSR (either with or without Nuxt) those classes are computed on the server which has no clue about the viewport size.

### Proposed solution
Extend the _spacing.styl to add a viewport size prefix to all spacing classes. Example:

py-3 -> p-xs-y-3
         -> p-md-a-5

**Comment by johnleider** [comment]
This is something we are going to work on for 2.0 on the server level.

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not 
functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by BorjaRafols** [comment]
Might I leave a little snippet then? You know, for others :)

```
$i = 0
for $level, $spacer in $spacers
  for $size, $width in $grid-breakpoints
    @media all and (min-width: $width)
      .{$size}-ma-{$i}
        margin: $spacer.y $spacer.x !important
      .{$size}-my-{$i}
        margin-top: $spacer.y !important
        margin-bottom: $spacer.y !important
      .{$size}-mx-{$i}
        margin-left: $spacer.x !important
        margin-right: $spacer.x !important
      .{$size}-mt-{$i}
        margin-top: $spacer.y !important
      .{$size}-mr-{$i}
        margin-right: $spacer.x !important
      .{$size}-mb-{$i}
        margin-bottom: $spacer.y !important
      .{$size}-ml-{$i}
        margin-left: $spacer.x !important

      .{$size}-pa-{$i}
        padding: $spacer.y $spacer.x !important
      .{$size}-py-{$i}
        padding-top: $spacer.y !important
        padding-bottom: $spacer.y !important
      .{$size}-px-{$i}
        padding-left: $spacer.x !important
        padding-right: $spacer.x !important
      .{$size}-pt-{$i}
        padding-top: $spacer.y !important
      .{$size}-pr-{$i}
        padding-right: $spacer.x !important
      .{$size}-pb-{$i}
        padding-bottom: $spacer.y !important
      .{$size}-pl-{$i}
        padding-left: $spacer.x !important
  $i = $i + 1
```

Added on the top of main.styl.

This creates the classes I asked for in the question.

`xs-ma-1`
`sm-pt-3`
etc...

@johnleider I'm curious about how you are planning to solve this in another way. Good luck
