### ISSUE TITLE
[Feature Request] Can v-ripple respond to touchstart events?

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#6354]
### Problem to solve
I'm working on a Cordova hybrid mobile app.  I have some buttons I tap on (response to @click) that have the v-ripple property applied.  However... these button navigate to a new page, so I never see the animation.  It would be nice it we could specify to show the ripple on a touchstart or at least have someway of waiting for the animation to end before the action is taken.  Right now I'm having to put a delay in the navigation for 500ms so that I can see the ripple.  It would also be nice if it did this when I pressed the item but moved outside of the click zone.  It would at least get feedback.  In that case no ripple would ever occur.  Maybe this isn't how the MD spec is written.

### Proposed solution
Add params to v-ripple to specify what event causes the ripple to occur?

**Comment by KaelWD** [comment]
It already does use touchstart, you're just navigating away instantly before the animation can play. I don't think adding a delay would be a good idea as it would cause poor UX in other areas, this is best left up to the consumer imo.

**Comment by funkyvisions** [comment]
I should. It doesn’t navigate until touchend when the @click handler is called.

**Comment by KaelWD** [comment]
> until touchend

Which is like 100ms later, you're not gonna see anything.

**Comment by daviesdoclc** [comment]
Understood. I wanted the touch and hold. That I will see. Thanks for implementing.

**Comment by martea** [comment]
I also think the ripple effect is strange to happend on "touchstart" since after touch start, if the user were to move/slide left right, then they havent really "clicked" on the element at that moment, might be a better solution to trigger this by the "click" event.

currently experiencing issue with using v-ripple on a element(custom made list), and on that element i have @click event bound to , and when i on touch devices scroll and the point of origin might be on that element it looks like i trigger the click event.. but it doesent since the click isnt triggerd either.

any known solutions regarding this?

**Comment by KaelWD** [comment]
You'll see that on https://material.io/design too

**Comment by Alleyfield** [comment]
> I also think the ripple effect is strange to happend on "touchstart" since after touch start, if the user were to move/slide left right, then they havent really "clicked" on the element at that moment, might be a better solution to trigger this by the "click" event.
> 
> currently experiencing issue with using v-ripple on a element(custom made list), and on that element i have v-on:click event bound to , and when i on touch devices scroll and the point of origin might be on that element it looks like i trigger the click event.. but it doesent since the click isnt triggerd either.

Agreed. It is confusing user experience when the ripple effect occurs when you scroll down a page and happened to trigger a touchstart on an element with a ripple applied to it. The animation would suggest that the user did click on the button but actually nothing happened as the click was not registered, only a touchstart event that caused the animation to occur

**Comment by hareku** [comment]
Is this correct behavior?

**Comment by martea** [comment]
found a directive where the events were removed, workaround to solve the issue
https://pastebin.com/uZfKdf9u
