### ISSUE TITLE
keyup event in text field

### ISSUE THREAD

**Issue by gaponte020** [vuetifyjs/vuetify#636]
<v-text-field
        append-icon="credit_card"
        label="Monto"        
        hide-details
        v-model="ammount"
        @keyup.enter="processPlay"
        /> 

Greetings, I have tried to place a keyup event and it does not take ¿ any idea ?, try with v-on and it does not work either

**Comment by johnleider** [comment]
Please direct questions for help to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
