### ISSUE TITLE
[Bug Report] v-select menu stays open

### ISSUE THREAD

**Issue by dbove** [vuetifyjs/vuetify#6361]
### Versions and Environment
**Vuetify:** 1.4.6
**Last working version:** 1.4.3
**Vue:** 2.6.1
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Add v-select component using v-model.

This started occurring after yarn upgrade. Both vuetify and vuejs were updated.

The select examples works on the vuetify sites but when you open in codepen and update to latest vuejs it breaks.

### Expected Behavior
Menu remains closed until control is interacted with.

### Actual Behavior
Menu is open.

### Reproduction Link
<a href="https://codepen.io/anon/pen/PVKWJE?editors=1010" target="_blank">https://codepen.io/anon/pen/PVKWJE?editors=1010</a>

**Comment by KaelWD** [comment]
This is a problem with vue 2.6.1, downgrade to 2.6.0 until we can get it fixed. We do have a workaround but we're working with evan to get it fixed in vue too.

**Comment by johnleider** [comment]
This has been fixed in https://github.com/vuejs/vue/releases/tag/v2.6.2
