### ISSUE TITLE
[Bug Report]  rows-per-page-items changed to ellipsis on Firefox v65 and up (revised)

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#6362]
### Versions and Environment
**Vuetify:** 1.4.6
**Vue:** 2.6.1
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
![image](https://user-images.githubusercontent.com/22522638/52251568-4851cc00-2930-11e9-90e0-50cbc4b41d0a.png)
v-data-iterator item shows ellipsis when `rows-per-page-items` is set with 4 int characters

### Expected Behavior
Proper functionality of the v-data-iterator-items

### Actual Behavior
Improper functionality of the v-data-iterator-items

### Reproduction Link
<a href="https://codepen.io/anon/pen/WPojbL" target="_blank">https://codepen.io/anon/pen/WPojbL</a>

**Comment by Kawacrepe** [comment]
This problem still persist with Vuetify 1.5.16 but with vuetify 2.X and the footer-props it's ok.
If someone can help me to fix that issue with the 1.5.16 it will be appreciate

**Comment by johnleider** [comment]
At this time there are no plans to back-port a fix due to the massive changes made to the data table component. I'd accept a PR for its fix but am considering this resolved at this time.
