### ISSUE TITLE
[Bug Report] Combobox chip's value should not be saved when editing a chip's text to a new value that has been existed in Combobox

### ISSUE THREAD

**Issue by Doflatango** [vuetifyjs/vuetify#6364]
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.6.2
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.0

### Steps to reproduce
1. Double click `A` and change the text to `B`
2. Now there are two `B` here.

### Expected Behavior
Step 1 should be failed or should not be saved.

### Actual Behavior
There are two `B` here

### Reproduction Link
<a href="https://codepen.io/anon/pen/yZoPGd?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/yZoPGd?&editable=true&editors=101</a>

### Other comments
I has been tested in v2.0.0, the issue still live.

**Comment by KaelWD** [comment]
5f6aaaa487cd93afc24be443686fbb5f62191d67 - I didn't even know that was possible.
