### ISSUE TITLE
[Bug Report] v-carousel-item not using the right transition

### ISSUE THREAD

**Issue by ulisses-cruz** [vuetifyjs/vuetify#6366]
### Versions and Environment
**Vuetify:** 1.4.6
**Vue:** 2.6.2
**Browsers:** Chrome 72.0.3626.81
**OS:** Windows 7

### Steps to reproduce
If we click the buttons of the carousel, everything works as expected (clicking next button plays the 'transition' and clicking the previous button plays the 'reverse'transition').
But when we click the button below the carousel it just plays the last transition no matter the direction of the next slide.

### Expected Behavior
The expected behavior is: when we click the button bellow the carousel, if the direction is 'right' it should play the 'transition' if it is 'left' it should play the 'reverse-transition'.

### Actual Behavior
When we click the button below the carousel it just plays the last transition no matter the direction of the next slide.

### Reproduction Link
<a href="https://codesandbox.io/s/yp1z36518j" target="_blank">https://codesandbox.io/s/yp1z36518j</a>

**Comment by crewow** [comment]
Hi please use reverse-transition="fade" see https://codesandbox.io/s/8nowxz043j for working example.

as per docs 

![image](https://user-images.githubusercontent.com/5371884/52531822-8da93b80-2d2c-11e9-9f34-4364e159d8f5.png)

**Comment by KaelWD** [comment]
@crewow the bug here is with changing the model externally.
