### ISSUE TITLE
[Bug Report] Set Year-Picker wrong scroll position

### ISSUE THREAD

**Issue by simonmaass** [vuetifyjs/vuetify#6367]
### Versions and Environment
**Vuetify:** 1.5.0-beta.3
**Vue:** 2.5.18
**Browsers:** Chrome 72.0.3626.81
**OS:** Windows 10

### Steps to reproduce
When creating a birthday picker as described in the documentation - when trying to set a default year for the year picker the scroll position is wrong.

### Expected Behavior
The scroll height is by the default given date

### Actual Behavior
scroll position is all the way at the top (2019)

### Reproduction Link
<a href="https://codepen.io/anon/pen/bzrjbo?editors=1010" target="_blank">https://codepen.io/anon/pen/bzrjbo?editors=1010</a>

### Other comments
When setting: picker-date="1980-01-01" the year picker is set to 1980 but the scroll position is wrong

![image](https://user-images.githubusercontent.com/32599710/52268943-07ac7f80-293d-11e9-8d34-d30e4630114c.png)

**Comment by jacekkarczmarczyk** [comment]
Works with setting `activePicker` after quite big timeout: https://codepen.io/anon/pen/jJLNzR?&editable=true&editors=101
