### ISSUE TITLE
[Bug Report] v-select item-text doesn't update dynamically

### ISSUE THREAD

**Issue by stact** [vuetifyjs/vuetify#6368]
### Versions and Environment
**Vuetify:** 1.4.6
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Change a parameter that change v-autocomplete render.
Select an in item in v-autocomplete.
Change the parameter with another value that change the v-autocomplete render.

### Expected Behavior
When changing a parameter, the v-autocomplete must refresh the render accordingly

### Actual Behavior
When changing a parameter, the v-autocomplete not refreshing the render, and the dropdown is empty

### Reproduction Link
<a href="https://codepen.io/stact/pen/ZwJmLw" target="_blank">https://codepen.io/stact/pen/ZwJmLw</a>

**Comment by KaelWD** [comment]
The autocomplete has no way to know you've changed that variable, use a computed property instead: https://codepen.io/anon/pen/ErvMbx?editors=1011

**Comment by stact** [comment]
Still same issue with autocomplete.
1. Select Parameter: 1033
2. Open Autocomplete and select ID 1 English
3. Select Parameter: 1036
4. The autocomplete not change selected "ID 1 English" to "ID 2 English"
5. Open Autocomplete
6. No data available

Could you re-open the issue please?

**Comment by heidricklevi** [comment]
https://github.com/vuetifyjs/vuetify/pull/6431
