### ISSUE TITLE
[Feature Request] Responsive grid gutters using breakpoints

### ISSUE THREAD

**Issue by jaminroe** [vuetifyjs/vuetify#6369]
### Problem to solve
Currently, the layout grid is static and I don't see a way to use breakpoints so gutters are responsive between device sizes. 
For example: On a large display, I want the gutters to be 24px and anything less than or equal to a medium device, I want it to have 16px gutters.

### Proposed solution
Have an API option for the layout grid, to use breakpoints in combination with the grid list classes. Thanks!

**Comment by johnleider** [comment]
Duplicate of #6020
