### ISSUE TITLE
v-navigation-drawer should follow material design guidelines by default

### ISSUE THREAD

**Issue by basejump** [vuetifyjs/vuetify#637]
this is related to #616 and the fix #617. 
The changes to fix those will now make the v-navigation-drawer less compliant with the guidelines.  To bring the default navigation-drawer  compliant with with this https://material.io/guidelines/patterns/navigation-drawer.html# some tweaks to the style need to happen. 

* The list should not require the "dense" setting under the nav-drawer
* list-item font-sizes should be 14px 
* list-item weight should be Medium (500) vs the regular (400)
* dense list should keep the medium weight
* I think the examples here makes sense [navigation guideline](https://material.io/guidelines/patterns/navigation.html#) and we should keep the group children list items as regular font weight, but they will also need to drop to 14px size.

**Comment by johnleider** [comment]
I'm so confused by what you are talking about...

**Comment by johnleider** [comment]
If what you are saying is that within the nav drawer lists should default be dense then I'll have to respectfully disagree. Some things are not worth coding when the developer can easily do this with props and it could potentially add more unneeded complexity.

**Comment by mfferreira** [comment]
@basejump the bullet points will me merged soon

**Comment by basejump** [comment]
I modified the initial comment above to be a bit more clear. Will also issue a pull request to bring the nav-drawer into spec.

**Comment by basejump** [comment]
I made some changes on a branch. @johnleider , the current defaults that are inplace in the template and examples use the dense setting, I am suggesting to have it default and setup as it is on the material.io links I referenced above
https://github.com/basejump/vuetify/tree/637-nav-drawer-list-per-guidelines

**Comment by AustinPaquette** [comment]
Do you have an example of what this would make it look like with the updated code?

**Comment by johnleider** [comment]
These changes have not been applied and basejump and the team are working together to correct the other PRs.
