### ISSUE TITLE
[Feature Request] v-slider at rtl mode

### ISSUE THREAD

**Issue by amitgur** [vuetifyjs/vuetify#6372]
### Problem to solve
when using v-slider in RTL mode, the slider runs from right to left. We, the RTL speakers,  used to look at those progress bars from left to right. 

### Proposed solution
Disable the direction change on RTL languges

**Comment by nekosaur** [comment]
I would like some sources on this.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by N-Pex** [comment]
LTR sliders are needed for media progress indicators in RTL environments.

"Do not mirror media playback buttons and the media progress indicator as they refer to the direction of tape being played, not the direction of time."

See here: https://material.io/design/usability/bidirectionality.html#mirroring-elements

Please reopen issue.

**Comment by nekosaur** [comment]
Please create a new feature request for adding an option to reverse a slider.
