### ISSUE TITLE
[Bug Report] Inconsistent checkbox state in v-select when using `item` slot

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#6376]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.1
**Browsers:** Chrome 72.0.3626.81
**OS:** Linux x86_64

### Steps to reproduce
I am generating the dropdown options using the `item` slot. Each option is basically a `v-checkbox` element with a label.
1) Open the dropdown
2) Click on one of the options by clicking outside the checkbox label.
![image](https://user-images.githubusercontent.com/34302506/52302440-32d1b600-29b3-11e9-90ee-0f692cd26836.png)

### Expected Behavior
The checkbox should be marked as checked, the `change` event should be fired and the option should be added to the `v-model`

### Actual Behavior
The option gets added to the `v-model`, but, the change event is not fired and the checkbox does not get selected.

### Reproduction Link
<a href="https://codepen.io/anon/pen/XOeKbo?editors=1011" target="_blank">https://codepen.io/anon/pen/XOeKbo?editors=1011</a>

### Other comments
**Use Case**
When the change event is fired, I want to get the newly added item. The `change` event on the `v-select` was only providing the entire value of the model and not the selected item. So, I decided to use the `item` slot to generate my own list.
The default `item` slot generates the list in such a way that the checkbox label covers the entire width of the dropdown. But, when using my own HTML, the label does not cover the full width of the dropdown and hence, the change event is not firing.
If this is genuine bug, please fix it or else please provide a workaround for my use case.

**Comment by KaelWD** [comment]
You aren't supplying any of that information back to the select, so it doesn't know that you've clicked on the checkbox: https://codepen.io/anon/pen/rPGGMG?editors=1010

There is actually a bug there where it's rendering two `v-list-tile`s, but you aren't actually using it for anything so your extra one can just be removed, then you don't need the change handler any more either: https://codepen.io/anon/pen/RvLLGO?editors=1010

**Comment by KaelWD** [comment]
There's a workaround in #4054
