### ISSUE TITLE
v-card-title has incorrect text spec

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#638]
[Material Specs for card title areas](https://material.io/guidelines/components/dialogs.html#dialogs-specs) are as follows:

- Top padding: 24dp
- Bottom padding: 20dp
- Text size: **Roboto Medium 20sp**
- Text line height: **28dp**

current .card__title class uses:{
```css
font-size: 24px;
font-weight: 400;
letter-spacing: 1px;
```

I would adopt/extend the .title class, which already has
```css
font-size: 20px;
font-weight: 500;
letter-spacing: 0.02em;
```
and add `line-height: 28px;`

Cheers!

**Comment by johnleider** [comment]
Card title is being removed in now favor of the refactored toolbar. So when the next patch releases, you will be using ```v-toolbar``` instead of card-title.
