### ISSUE TITLE
[Bug Report] v-tooltip cannot set programmatically although v-model is attached

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#6380]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Firefox Quantum v66.0
**OS:** Windows 10

### Steps to reproduce
Been asking on vuetify discord got no answer

### Expected Behavior
v-tooltip is hidden when data is false. programmatic in the nutshell

### Actual Behavior
v-tooltip's expected to be programmatic

### Reproduction Link
<a href="https://codesandbox.io/s/7w364j7jr6" target="_blank">https://codesandbox.io/s/7w364j7jr6</a>

**Comment by jacekkarczmarczyk** [comment]
Please reduce your reproduction to minimal https://stackoverflow.com/help/mcve

**Comment by handhikadj** [comment]
> 
> 
> Please reduce your reproduction to minimal https://stackoverflow.com/help/mcve
revised

**Comment by jacekkarczmarczyk** [comment]
Do you mean this? https://codesandbox.io/s/03vjwow240

**Comment by handhikadj** [comment]
> 
> 
> Do you mean this? https://codesandbox.io/s/03vjwow240



still not resolved

**Comment by KaelWD** [comment]
Set `disabled` to true and it will only react to the `value` you provide.
