### ISSUE TITLE
[Feature Request] Will you make an admin template for vuetify?

### ISSUE THREAD

**Issue by mazeteam** [vuetifyjs/vuetify#6381]
Will you make an admin template for vuetify
Such as  adminLTE, element ui admin

or have a new branch about admin template?

**Comment by KaelWD** [comment]
https://material-kit.vuetifyjs.com/
https://demos.creative-tim.com/vuetify-material-dashboard

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
