### ISSUE TITLE
[Feature Request] treeview append slot doesnt support preventDefault

### ISSUE THREAD

**Issue by john-dev** [vuetifyjs/vuetify#6383]
### Problem to solve
When adding a button to the append slot in a treeview, i can't prevent the treeview from selecting/deselecting the current item when i hit that button.

### Proposed solution
Add a prop for append-prevent true/false

**Comment by john-dev** [comment]
https://jsfiddle.net/6z37h2p5/3/

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/events.html#Event-Modifiers

https://jsfiddle.net/fgu1n372/

**Comment by john-dev** [comment]
ah nice, v-on:click.prevent.self didn't work @click.stop does.. thanks a lot

**Comment by john-dev** [comment]
@KaelWD this does fix the problem only partly.
Do you have an idea how to make it work with a v-menu?
My last jsfiddle wasn't complete..

This one is:
https://jsfiddle.net/qmk81shr/

**Comment by rambavd** [comment]
> @KaelWD this does fix the problem only partly.
> Do you have an idea how to make it work with a v-menu?
> My last jsfiddle wasn't complete..
> 
> This one is:
> https://jsfiddle.net/uwkt13ea/

You can simply put your menu outside of the treeview component, and only put the activator button inside the slot "append". (see [this](https://vuetifyjs.com/en/components/menus#absolute-position-without-activator) and work around of it, writing a simple method that passes which item's button activated the menu)
