### ISSUE TITLE
[Feature Request] advanced filtering component

### ISSUE THREAD

**Issue by lucasfernog** [vuetifyjs/vuetify#6385]
### Problem to solve
Filtering elements with a simple and dense UI (menu) to select options and showing selected filters (chips)

![screenshot_1](https://user-images.githubusercontent.com/20051258/52337959-346d9f00-29f0-11e9-95cd-6c4d10bcc4f2.png)
![screenshot_2](https://user-images.githubusercontent.com/20051258/52337985-4a7b5f80-29f0-11e9-91e6-613f23a22d17.png)
![screenshot_3](https://user-images.githubusercontent.com/20051258/52338042-6aab1e80-29f0-11e9-999f-3d82fe31281b.png)
![screenshot_4](https://user-images.githubusercontent.com/20051258/52338060-74cd1d00-29f0-11e9-8cce-80b8ccee7d55.png)
![screenshot_5](https://user-images.githubusercontent.com/20051258/52338068-7a2a6780-29f0-11e9-81e5-cc93404f1505.png)

### Proposed solution
Create a component that wraps the "Filter" button and the selected filters chips, with a slot/prop to populate the menu with default components such as DateFilter, TextFilter, ListFilter.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
