### ISSUE TITLE
[Bug Report] Sparkline not accepting theme colors

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#6387]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Add a v-sparkline component and set the `color` prop to any of the theme colors such as "primary", "error" or "success".

### Expected Behavior
Sparkline should be styled in the specified color.

### Actual Behavior
Sparkline is black.

### Reproduction Link
<a href="https://codepen.io/anon/pen/vbevdR" target="_blank">https://codepen.io/anon/pen/vbevdR</a>

### Other comments
According to the docs the color prop should "support the name of material color (for example success or purple) or css color (#033 or rgba(255, 0, 0, 0.5))".
https://vuetifyjs.com/en/components/sparklines#sparkline

Even the default value for color should be "primary".

**Comment by KaelWD** [comment]
`color` only seems to be used for falsy gradient stops for some reason.

**Comment by kewba** [comment]
I came across this report by making the mistake of expecting  a vuetify solution. use the css path to control the colour of the line. Look into the dom to find the specific path id. Hope this helps.
https://codepen.io/kewba/pen/EzxBMp

**Comment by t-MURO** [comment]
@kewba you didn't make a mistake expecting a solution from vuetify.

It's actually in the documentation:

> Applies specified color to the control - it can be the name of material color (for example success or purple) or css color (#033 or rgba(255, 0, 0, 0.5))

**Comment by Lavhe** [comment]
Is this still not fixed?
