### ISSUE TITLE
[Bug Report] The week of the 30th of April is broken on a v-calendar when the prop weekdays has a value of [1, 2, 3, 4, 5, 6, 0]

### ISSUE THREAD

**Issue by MaelNamNam** [vuetifyjs/vuetify#6389]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.6

### Steps to reproduce
Add a prop weekdays="[1, 2, 3, 4, 5, 6, 0]" to the v-calendar

### Expected Behavior
In the type="month",
1. weeks should start on Monday
2. weeks should all have 7 days

### Actual Behavior
The vast majority of weeks looks just fine.
Except the week of the 30th of April which contains 6 days on the "month" view of April

### Reproduction Link
<a href="https://codepen.io/hub-grade/pen/RvLvdw" target="_blank">https://codepen.io/hub-grade/pen/RvLvdw</a>

**Comment by KaelWD** [comment]
@ClickerMonkey Should this be changed to `first-day-of-week` to align with date pickers? I don't see much use in being able to have them out-of-order.

**Comment by ClickerMonkey** [comment]
This prop allows you to do things like MWF, or Monday through Friday... so it does a little more than first-day-of-week.

**Comment by ClickerMonkey** [comment]
It's also showing that the 31st is a Saturday, when it's most definitely a Sunday. I've found the problem
