### ISSUE TITLE
[Feature Request] Calendar: Scheduler support

### ISSUE THREAD

**Issue by cworreschk** [vuetifyjs/vuetify#6391]
### Problem to solve
As @scottpage requested at https://github.com/vuetifyjs/vuetify/pull/6092#issuecomment-458557936 , it would be great if the `v-calendar` component would support scheduling resources with a timeline and a ressource view like the FullCalendar Scheduler Plugin. 

See https://fullcalendar.io/scheduler or https://fullcalendar.io/docs/scheduler .

![Scheduler](https://user-images.githubusercontent.com/4706279/51913409-a6f8d200-2393-11e9-8188-84b877c4f72e.png)

### Proposed solution
Implement the functionality of the FullCalendar Scheduler Plugin (https://fullcalendar.io/scheduler) in the `v-calendar` component.

**Comment by ClickerMonkey** [comment]
There are plans to perhaps implement a similar view which Google Calendar has - but it's going to be after the 2.0 release.

**Comment by egeersoz** [comment]
We need this also. Our use case is service dispatching: you have a list of technicians, each assigned to projects, and projects have start and end times. We need to be able to display this information on a single page as a birds-eye view of everything, as well as spot conflicts easily.

Example screenshot:

![image](https://user-images.githubusercontent.com/1009235/55756128-6a41fa80-5a16-11e9-9c5b-d8534db69ce0.png)

**Comment by mjrc** [comment]
We are also using the FullCalendar Scheduler for resource based planning in our application. Having this integrated with Vuetify, similarly to the dispatch board example, would certainly be a nice upgrade! Subscribed.

**Comment by codewinkel** [comment]
+1

**Comment by r3stm4n** [comment]
+1

**Comment by laurent-brisbois** [comment]
+1 It would be an awesome addition to the `v-calendar` component.

Or even a brand new one `v-scheduler` ?

**Comment by danhumphrey** [comment]
I would also love to see this in Vuetify 👍

**Comment by aziztitu** [comment]
+1 I'd absolutely love to see this in Vuetify!!

**Comment by bartoszym** [comment]
+1

**Comment by ghost** [comment]
> We need this also. Our use case is service dispatching: you have a list of technicians, each assigned to projects, and projects have start and end times. We need to be able to display this information on a single page as a birds-eye view of everything, as well as spot conflicts easily.
> 
> Example screenshot:
> 
> ![image](https://user-images.githubusercontent.com/1009235/55756128-6a41fa80-5a16-11e9-9c5b-d8534db69ce0.png)

exactly what we need also

**Comment by cavernerg** [comment]
is this also about the schedule view from google calender? 
![grafik](https://user-images.githubusercontent.com/62744005/101481843-0e9be300-3956-11eb-9290-d218e5e8ae1a.png)
would love this feature!

**Comment by StefanFeederle** [comment]
It would be awsome If the vuetify calendar could be used as a scheduler.

With two changes the type="category" view could be a scheduler:
- Rotating the category view by 90° to have categories/resources as rows instead of columns.
- Displaying a continous timeline instead of days side-by-side.

**Comment by laurent-brisbois** [comment]
Hello @johnleider 

Sorry for notifying here but I see it has been closed without any reason (I don't see any PR not comment to explain whether it'll be done one day or not).

Thank you in advance.
