### ISSUE TITLE
[Feature Request] Creating a choice of Form Format as this little label format just isnt liked.

### ISSUE THREAD

**Issue by WHumphreys** [vuetifyjs/vuetify#6393]
### Problem to solve
Ive only just started doing some testing with Vuetify rather than using Bootstrap and on the whole I like it. Thats with the acception of this silly form format.

We have forms running over intranets used by thousands of users so their feedback counts. We experimented by creating a new form with your form format and a very large majority of the users complained.

The general feedback:

a) The label text is too small and is hard to read. (some got confused that it was still the label).

b) It isnt always clear that is was an input field.

c) If the label is very long (some labels are long questions) it is truncated. That has no possible use case I can think of.

d) When the client side validation kicked in on multiple fields it just looks a mess and its very unclear what is what.

e) People who invent this stuff may think its cool for all sorts of reasons but when most of the "real" users say it doesnt work then hey, it doesnt work...

f) The original "Bootstrap" type of forms they currently see they really like, in fact we rarely get feedback saying anything bad. 

Though I'm not a lawyer I would be surprised if in the UK if those small labels are even "complient" with our disability laws.

Sometimes I wish people would stop trying to fix something that isnt broke.

### Proposed solution
I propose that the option for the current style stays and you just add a seperate option for the "general way" its mostly always been done. Then you have a choice. (and I dont mean the "bodge" of some text to the left)

**Comment by KaelWD** [comment]
Can you clarify what you mean by this? All our components follow google's [material design guidelines](https://material.io/design/).

**Comment by johnleider** [comment]
We follow material design spec, this won't change.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
