### ISSUE TITLE
[Bug Report] v-scroll not working with v-dialog

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#6398]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
I don't know how to tag it, either Bug Report or Feature Request so excuse me beforehand

I want to create infinite scroll inside v-dialog. on my project, i've used vue-infinite-loading accompanied with v-datatable. when i click a "Detail" button, it opens v-dialog and lists all data. as i scroll the v-dialog, it pushes the data to array thus creates infinite scroll. but it only works on an id was just clicked (only worked once). i use v-scroll technique instead but turned out cannot console.log anything. by the way i can't show you the infinite loading project cause it's been hard to put it on a reproduction so i provide the minimal reproduction

### Expected Behavior
can console.log the event

### Actual Behavior
cannot console.log the event

### Reproduction Link
<a href="https://codepen.io/dhika345/pen/aXVYRg" target="_blank">https://codepen.io/dhika345/pen/aXVYRg</a>

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/MLOPEb?editors=1011

- Your example is using vuetify 0.17
- The target has to be the element that's actually scrolling, in this case v-card-text
- DOM templates don't support camelCase attributes, so the directive was actually looking for `#infinitescrollest`
