### ISSUE TITLE
[Feature Request] Option to enable/disable responsive behaviors

### ISSUE THREAD

**Issue by c8u** [vuetifyjs/vuetify#6399]
### Problem to solve
While making a desktop app (NW.js or Electron.js) few built in responsive behaviors (like, decrementation of padding in some elements, navigation drawer becoming mobile friendly etc) come into play when resizing app window

### Proposed solution
 Adding a switch (base class) to turn it off might solve this problem

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
