### ISSUE TITLE
v-menu doesn't propagate disabled prop to button/activator slot

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#640]
### What is expected ?
Disabling a v-menu should also disable the activator slot that opens the menu.

### What is actually happening ?
The activator slot has to also have it's disabled prop set in order to display as disabled. Setting just the activator slot item as disabled still enables clicks to open the menu despite its disabled state.

### Steps to reproduce
set the disabled prop on a `v-menu` 
```html
<v-menu :disabled="!user.authenticated">
    <v-btn icon light slot="activator" :disabled="!user.authenticated">
          <v-icon>more_vert</v-icon>
    </v-btn>
    <v-list> ... etc </v-list>
</v-menu>
```
### Versions
v 0.12.2

### Reproduction Link
https://codepen.io/mix3d/full/KmOppE/

**Comment by johnleider** [comment]
I can confirm this has been fixed in dev.
