### ISSUE TITLE
[Feature Request] Please improve the search engine of official doc.

### ISSUE THREAD

**Issue by arkceajin** [vuetifyjs/vuetify#6400]
### Problem to solve
For example, I want to know the knowledge about `v-container`, then get no result.
So I change search keyword `v-container` to `v-containe`, here is the result:
![default](https://user-images.githubusercontent.com/8335699/52396800-76810880-2af6-11e9-9e6f-0a9f6b0106f9.PNG)
Did I use the wrong way? Or somewhere else let me learn `vuetify` better than the official site...

### Proposed solution
The search engine could show the result which relates to the searching keyword.
Eg. Search `v-container` shall give https://next.vuetifyjs.com/en/framework/grid

**Comment by MajesticPotatoe** [comment]
Search results are provided by a third party called algolia. We have little control over how they crawl, index and parse the search results.

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
