### ISSUE TITLE
[Feature Request] pass the size prop if VIcon used with custom icons

### ISSUE THREAD

**Issue by Mintonne** [vuetifyjs/vuetify#6403]
### Versions and Environment
**Vuetify:** 1.4.8
**Vue:** 2.6.3
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows

### Steps to reproduce
Setup custom icons as explained here (https://vuetifyjs.com/en/framework/icons#using-custom-icons) using a vue-ready icon pack that has a size prop (https://gitlab.com/robcresswell/vue-material-design-icons)

### Expected Behavior
VIcon should pass the size prop to the icon component.

### Actual Behavior
VIcon does not pass the size prop to the icon component.

### Reproduction Link
<a href="https://codesandbox.io/s/52qvw4jz8n" target="_blank">https://codesandbox.io/s/52qvw4jz8n</a>

**Comment by hendrikbl** [comment]
Any news on this?

**Comment by UsmanJavedAttari** [comment]
If anyone using vuetify 2, then here's a workaround.

`<v-icon custom-prop="value">$icon</v-icon>`

Now you can access custom attribute in your custom component as `{{ $parent.$attrs['custom-prop'] }} <-- "value"`

**Comment by KaelWD** [comment]
`vuetify.icons.sets[name].component` can be a function that does whatever you want with the passed in props.
