### ISSUE TITLE
[Bug Report] VIcon strange rendering if there is a space before/after the icon name

### ISSUE THREAD

**Issue by Mintonne** [vuetifyjs/vuetify#6404]
### Versions and Environment
**Vuetify:** 1.4.8
**Vue:** 2.6.3
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows

### Steps to reproduce
If you use pass the icon name using the `$vuetify.icons.ICON_NAME` format and happen to have a space before or after the name or move the name to a new line, a dollar sign and some random dots appear together with the icon.

![image](https://user-images.githubusercontent.com/39894801/52415280-75dc7800-2ade-11e9-9a66-15832c220545.png)

### Expected Behavior
VIcon should show the icon only.

### Actual Behavior
A dollar sign and some random dots appear together with the icon.

### Reproduction Link
<a href="https://codesandbox.io/s/883jzz9lq0" target="_blank">https://codesandbox.io/s/883jzz9lq0</a>

### Other comments
The `$vuetify.icons.ICON_NAME` format is useful if you are using custom icons.

V-text and V-html don't seem to be affected and currently serve as a workaround for this issue.

**Comment by sh7dm** [comment]
Looks like it's interpreted like a name, not variable
