### ISSUE TITLE
Tab indicator does not update for programmatic route navigation

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#641]
### Steps to reproduce
Have a route-based tab-bar at the root of the app, and at least one route that doesn't match the tabs' `to:` destinations. 

From a non-matching route, programmatically navigate to a matching route.

### Versions
Vuetify 0.12.2

### What is expected ?
1) When no path is matched, the indicator should not show.
2) When a matching path is programmatically triggered/replaced, the correct tab has the indicator  
### What is actually happening ?
1) no tab is highlighted, but the indicator defaults to tab#1
2) the correct tab is highlighted, but the indicator stays at it's previous location

### Reproduction Link
https://s.codepen.io/mix3d/debug/KmOppE/yPkJjGKvQjVk#/path2

Note: Was chasing this bug when I noticed the `Cannot read property 'name' of undefined` console error locally, but was unable to reproduce the console issue on codepen.

**Comment by johnleider** [comment]
I'll work on #1 tomorrow

**Comment by johnleider** [comment]
After some trial and error, for now, I've concluded supporting -1 would be a decent investment of time. Considering soon there will be massive updates to toolbars and tabs for MD spec compliance, I'm opting to not put the time there.

**Comment by ptdv** [comment]
I'm running into the same issue for #2. 
Is no further work planned on this? Quite an important feature for a SPA to be able to update content based on router state/pragmatically.

**Comment by johnleider** [comment]
What do you mean? It is currently working. Please don't arbitrarily post on old issues.

**Comment by ptdv** [comment]
Huh sorry about that but doesn't your comment above say it "I'm option to not put the time there"? I found a work around using the v-model and a map but maybe this is what you mean?

**Comment by johnleider** [comment]
I did. And this release coming up has a complete tabs refactor.

**Comment by ptdv** [comment]
Oh rad! Sorry about this then.
