### ISSUE TITLE
[Feature Request] v-menu add option to create overlay

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#6410]
### Problem to solve
It would be nice to have an option to create an invisible overlay in the v-menu component, blocking all pointer events (hover, click, etc...) in the elements below the menu.

### Proposed solution
Since v-dialog have a overlay that blocks the user pointer events on elements below, and even close the dialog if clicked on it, it's just a matter of porting it to v-menu component.

**Comment by KaelWD** [comment]
Duplicate of #5310
