### ISSUE TITLE
[Feature Request] Why does v-range-slider not use VSlider.extend

### ISSUE THREAD

**Issue by i-ndigo** [vuetifyjs/vuetify#6411]
### Problem to solve
Most of the components extend the parent component by ParentComponent.extend({}) VRangeSlider does not do this. It is just using the "extend" property within an object. This does work and the component  functions as expected. BUT there seems to be a difference in the way Vue extends the component. With other components I can override functionality using "Vue.config.optionMergeStrategies". When using the "extend" property it seems it does not call the optionMergeStrategies in the right way. Maybe that is exactly the reason why it was done this way but it makes it difficult to change functionality without changing the library it self.  

I posted it as a Feature Request since the Component works as expected and my request seems to be more of a special case.

### Proposed solution
Use 
```javascript
export default VSlider.extend({
    name: 'v-range-slider',
    extends: VSlider
```
Instead of 
```javascript
export default {
    name: 'v-range-slider',
    extends: VSlider,
```

**Comment by nekosaur** [comment]
Fixed in 2.0 (#6424)
