### ISSUE TITLE
[Bug Report] Can't use spacing helpers on v-card-text

### ISSUE THREAD

**Issue by nickhall** [vuetifyjs/vuetify#6413]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Chrome 72.0.3626.81
**OS:** Mac OS 10.13.6

### Steps to reproduce
Use spacing helpers on a v-card-text element

### Expected Behavior
The margin and/or padding are changed

### Actual Behavior
Margin/padding are unchanged

### Reproduction Link
<a href="https://codepen.io/anon/pen/BMJMVg" target="_blank">https://codepen.io/anon/pen/BMJMVg</a>

**Comment by KaelWD** [comment]
1. those helpers are classes, they only work as attributes on grid components
2. if you don't want the spacing just use a div, v-card-text doesn't do anything special except that
