### ISSUE TITLE
[Bug Report] Will-change memory consumption warning

### ISSUE THREAD

**Issue by GianPaoloBuffo** [vuetifyjs/vuetify#6414]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Open the Firefox console and click on the card.

### Expected Behavior
There should be no console warning in Firefox.

### Actual Behavior
There is a console warning in Firefox.

### Reproduction Link
<a href="https://codepen.io/GPBuffo/pen/MLrLLb" target="_blank">https://codepen.io/GPBuffo/pen/MLrLLb</a>

### Other comments
This appears to happen when the `ripple` directive is added to `v-card`

**Comment by KaelWD** [comment]
The ripple is a circle, so its bounding box needs to be the width of the element squared. You can ignore this warning.
