### ISSUE TITLE
[Bug Report] VCalendar too many/few days for certain months

### ISSUE THREAD

**Issue by lukas-tr** [vuetifyjs/vuetify#6415]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Set `weekdays` to `[1, 2, 3, 4, 5, 6, 0]` and set `value` to either `2019-04-08`, `2017-05-01` or
`2015-06-01`.
- open the demo at https://youthful-bohr-c35667.netlify.com or clone and run the project
- click on any of the `go to wrong month` buttons
- compare with other months using the chevron buttons

### Expected Behavior
Every month has the right number of days and the scoped slot receives the right date.

### Actual Behavior
Some months have a different number of days in the last weak of the month. Also, the scoped slot receives the wrong date.

### Reproduction Link
<a href="https://github.com/lukas-tr/vuetify-calendar-bug" target="_blank">https://github.com/lukas-tr/vuetify-calendar-bug</a>

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6389
