### ISSUE TITLE
[Feature Request] Question about A la carte

### ISSUE THREAD

**Issue by furyscript** [vuetifyjs/vuetify#6417]
### Problem to solve
Is it possible to use A la carte in development and have only stylus required for components used?
This works correctly in production.

I'm using vuetify for VParallax but I also use `bootstrap-vue` for my theme.
In dev I have style conflicts because stylus compile all vuetify styles.
I use this with `nuxt` and `@nuxtjs/vuetify`.

### Proposed solution
#

**Comment by KaelWD** [comment]
- Remove vuetify-loader and import the components from their subfolder instead (`import { VParallax } from 'vuetify/lib/components/VParallax'`)
 - Or enable tree shaking in development (will slow builds down a fair bit). Enable `optimization.minimize`, `optimization.usedExports`, `optimization.concatenateModules`, and `optimization.sideEffects` in your webpack config. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by furyscript** [comment]
Ok thanks, I try fast but at this moment I get `Unexpected identifier` in browser.
Ps: I'm using nuxt...
After I will test more
