### ISSUE TITLE
[Bug Report] Ripple is broken since 1.4.7

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#6418]
### Versions and Environment
**Vuetify:** 1.5.0
**Last working version:** 1.4.6
**Vue:** 2.6.3
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a v-btn or other component using v-ripple.

### Expected Behavior
Ripple effect

### Actual Behavior
No ripple effect

### Reproduction Link
<a href="https://codepen.io/anon/pen/JxMQdZ" target="_blank">https://codepen.io/anon/pen/JxMQdZ</a>

**Comment by sindrepm** [comment]
I assume it is caused by https://github.com/vuetifyjs/vuetify/commit/79d4504

**Comment by KaelWD** [comment]
Works for me ¯\\\_(ツ)\_/¯

**Comment by githrdw** [comment]
The ripple effect does not work for me neither.
This capture is taken in Chrome (V72.0.3626, navigator.maxTouchPoints = 10, Windows 10 x64)

![ripplekapot](https://user-images.githubusercontent.com/1455140/52522005-203fd100-2c80-11e9-974b-83f07bd7a789.gif)

And this is captured in Edge (V44.17763, also 10 touchpoints)

![edgeripplekapot](https://user-images.githubusercontent.com/1455140/52522046-90e6ed80-2c80-11e9-9c4b-3507a0bc726c.gif)

**Comment by githrdw** [comment]
Oh I see, I am using a laptop with touchscreen. I never use the touchscreen and use the mouse instead.
The ripple reacts on touch, but not on mouse click events.

This is captured with my touchscreen

![touchrippleworks](https://user-images.githubusercontent.com/1455140/52522132-6ba6af00-2c81-11e9-87cd-306381c7e126.gif)

**Comment by FunnyPhantom** [comment]
ripple also does not work in the website since 1.5.0. (e.g. [Buttons](https://vuetifyjs.com/en/components/buttons).)

**Comment by KaelWD** [comment]
That PR should hopefully fix it, can someone check for me?

https://vuetifyjscom-uwujyewrqo.now.sh/en/directives/ripples

**Comment by githrdw** [comment]
Yep, works for me. Mouse-click and touch as well.
Thanks!
