### ISSUE TITLE
error of Unknown custom element: <dashboard> - did you register the component correctly?

### ISSUE THREAD

**Issue by lamatuts** [vuetifyjs/vuetify#642]
I have just separated the provided boiler plate into different components that is Toolbar, drawers and footer and added them to a Dashboard component but when i try using this dashboard component in the App component it returns an error

The full code is available at github on  [This link](https://github.com/lamatuts/dashboard)

**Comment by zeljic** [comment]
You have few issues in your code.
1. You have to close <script> tag in App.vue
2. Fix typo App.vue line 6 "Dashboard"
3. Remove footer-area from Dashboard.Vue (you don't have that component, yet ;) )

**Comment by lamatuts** [comment]
Damn so stupid mistake, Thanks Zelijc it now works
