### ISSUE TITLE
[Bug Report] Switch value is always undefined

### ISSUE THREAD

**Issue by woodgates** [vuetifyjs/vuetify#6422]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Firefox 64.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create a switch and check the props "value". Is always undefined. IS easy to check in Vue devtools.

### Expected Behavior
The "value" of the switch should be updated in every change of state.

### Actual Behavior
The "value" props keeps undefined

### Reproduction Link
<a href="https://codepen.io/woodgates/pen/omEjXa?editors=1112" target="_blank">https://codepen.io/woodgates/pen/omEjXa?editors=1112</a>

**Comment by KaelWD** [comment]
`inputValue`
