### ISSUE TITLE
[Bug Report] Bottom-Sheet prop disabled not working

### ISSUE THREAD

**Issue by mrspinn** [vuetifyjs/vuetify#6426]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.13.6

### Steps to reproduce
Apply the disabled prop to v-bottom-sheet

### Expected Behavior
Disabled v-bottom-sheet should not pop up.

### Actual Behavior
Disabled v-bottom-sheet pops up and is not disabled.

### Reproduction Link
<a href="https://codepen.io/mrspinn/pen/mvXrYq" target="_blank">https://codepen.io/mrspinn/pen/mvXrYq</a>

**Comment by KaelWD** [comment]
`disabled` just stops the activator slot from doing anything, you can still control it with v-model. You want to disable the button instead.

**Comment by mrspinn** [comment]
In the documentation, it says `Disables the ability to open the dialog`
I'll change the way I'm doing it, but that should be indicated in the docs.
