### ISSUE TITLE
[Bug Report] Vuetify monthly VCalendar when clicking in the date

### ISSUE THREAD

**Issue by Rolanddoda** [vuetifyjs/vuetify#6434]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.0
**Browsers:** Opera 57.0.3098.116
**OS:** Windows 10

### Steps to reproduce
The reproduction link is a copy paste of the examples in the vuetify docs. 

Click on the date link (e.g. click the 1 Jan)

### Expected Behavior
This should update the `start` property.

### Actual Behavior
There is an error in the console.The v-model doesn't update the `start` property correctly but instead returns an object.

### Reproduction Link
<a href="https://codepen.io/Roland1993/pen/gqvNOE" target="_blank">https://codepen.io/Roland1993/pen/gqvNOE</a>

**Comment by ClickerMonkey** [comment]
I've made a fix for this in 2.0, I'll check to see when/if we're patching 1.5.0

**Comment by ClickerMonkey** [comment]
@Rolanddoda are you still on 1.5.0 and require this fix?
