### ISSUE TITLE
[Enhancement] black, white, and grey hard-coded in _theme.styl

### ISSUE THREAD

**Issue by jaxn** [vuetifyjs/vuetify#6437]
### Problem to solve
The addition of calendar and some other recent changes have added hard-coded values for whites, blacks, and greys.

The current issues are with:

- [ ] `material-*.buttons.pressed`
- [ ] `material-*.calendar.background-color`
- [ ] `material-*.calendar.outside-background-color`
- [ ] `material-*.calendar.line-color`
- [ ] `material-*.calendar.text-color`
- [ ] `material-*.calendar.past-color`
- [ ] `material-dark.background`
- [ ] `material-dark.chips.background`
- [ ] `material-dark.expansion-panels.focus`
- [ ] `material-dark.table.active`
- [ ] `material-dark.bg-color`

### Proposed solution
Replace hard-coded values for whites/blacks/greys with `$colors.shades..`

**Comment by sh7dm** [comment]
Closed in #6446

**Comment by sh7dm** [comment]
@jaxn thanks for reporting this!
