### ISSUE TITLE
[Bug Report] searching "accordion" in docs does not bring up expansion panel

### ISSUE THREAD

**Issue by mikob** [vuetifyjs/vuetify#6438]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Chrome 72.0.3626.96
**OS:** Linux x86_64

### Steps to reproduce
1. search "accordion"

### Expected Behavior
expansion panel will be a result (it even has accordion later in the page)

### Actual Behavior
only see calendar API related result (1 result total)

### Reproduction Link
<a href="https://codepen.io/chriscoyier/pen/blExo" target="_blank">https://codepen.io/chriscoyier/pen/blExo</a>

### Other comments
Coden reproduction link is irrelvant

**Comment by MajesticPotatoe** [comment]
Thank you for your  interest in improving Vuetify! 
Doc search functionality is is controlled via a third party service called Algolia. Unfortunately we do not have control over what is populated for search criteria or how their crawlers work. Your search for accordion is bringing up the closest find in the text (according) on the calendar page.

Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by mikob** [comment]
@MajesticPotatoe not sure why this issue was closed, as it's still an issue. I'm also using Algolia in another project, specifically docsearch (https://community.algolia.com/docsearch/) which has enough configurability to get around such issues.
