### ISSUE TITLE
Second `v-navigation-drawer` with `persistent` and `right` expected to push content to left when shown.

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#644]
### Steps to reproduce

1. Use layout 6 as basis.
2. Add `v-navigation-drawer` with attributes `right` and `persistent`

### Versions

0.12.2

### What is expected ?

When showing the right navigation drawer the content would be pushed to the left just like it is pushed to the right when showing the left navigation drawer.

### What is actually happening ?

Right navigation drawer is opening as overlay over the `main` content.

### Reproduction Link

https://codepen.io/anon/pen/OmKxar

**Comment by maurop123** [comment]
Just dropping my two cents. Having the option to push the content or overlay it seems like a good option to have either the left hand drawer or the right hand one.

**Comment by maurop123** [comment]
Interestingly, in this version of your fiddle, the right-hand drawer is placed above the content, and when it's opened it pushes the content like the left-hand drawer. Odd, huh?

https://codepen.io/maurop123/pen/XRvqao

**Comment by maurop123** [comment]
I've got a fix for this issue. Submitting a pull request

**Comment by duebbert** [comment]
Thanks Mauro, this is a great start and useful if we have a navigation drawer on the right with `persistent`. 

My goal would be to have 2 navigation drawers: one on the left and one of the right. Both should push the contents accordingly to the right or left. In your improved version this still doesn't work because the navigation drawer expects a toolbar to come as direct sibling.

Or should I open a new issue to cover having 2 navigation drawers before a toolbar?

**Comment by maurop123** [comment]
I think I see what you're saying. I'll take another look.

**Comment by jdriesen** [comment]
If I can ask... any news about the 2 navigation drawers ?
Maybe an example ? Thanks in advance for any reply.

**Comment by johnleider** [comment]
No news, already works.

**Comment by jdriesen** [comment]
I'm searching now since a rather long time for a template example with 2 navigation drawers...
@johnleider  ... can you maybe point me in the right direction ?

**Comment by johnleider** [comment]
https://vuetifyjs.com/layout/pre-defined example #3

**Comment by jdriesen** [comment]
First of all, thank you for replying on a Sunday evening.
I guess there is a small misunderstanding in the definition of "double navigation drawers" (100% my fault, I'm new to vuetify ...)

I'm trying to rebuild [this layout ](http://develop.ireporter.be/) with Vuetify (it's currently made with BS)
See the double navigation bar on top...

I was hoping to find somewhere a similar layout which I could use as a 'start', but seems hard to find.
But once again, I'm very new to Vuetify...

Grtz,
Johnny

**Comment by johnleider** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/9064066/31058717-4a100a36-a6c6-11e7-9d7b-19f229337ff5.png)

**Comment by jdriesen** [comment]
Yes, sir.

**Comment by johnleider** [comment]
I think you are looking for **toolbars**, https://vuetifyjs.com/components/toolbars with an extended slot.

**Comment by jdriesen** [comment]
Have been trying and studying it a lot today :)
Tomorrow is another day. I will take a deeper look with a fresh mind.
THANK YOU for your help on this Sunday evening.

Kind regards,
Johnny
