### ISSUE TITLE
[Bug Report] v-form ResetValidation immediately followed by Validate does not display error messages

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#6441]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Chrome 72.0.3626.96
**OS:** Windows 7

### Steps to reproduce
1. Click Reset Form
2. Enter invalid email address in Email field - error will be shown - Invalid Email
3. Click Reset Validation Button - error is cleared & Validate Button is enabled
4. Click Validate - no errors are shows

If you remove this.resetValidation() from this.validate works OKAY.

### Expected Behavior
Error messages should be displayed

### Actual Behavior
No error messages are displayed

### Reproduction Link
<a href="https://codepen.io/prasmi/pen/damNbm" target="_blank">https://codepen.io/prasmi/pen/damNbm</a>

**Comment by KaelWD** [comment]
Why do you need to do this? The end result would be the same either way.

**Comment by ppatkar** [comment]
Both resetValidation & validate do not clear error-messages array if custom errors are pushed into the same. So if message is pushed in error-message and validate fails the validation messages do not get displayed even if error-count >1

**Comment by KaelWD** [comment]
Can you show that in a codepen please?

**Comment by ppatkar** [comment]
https://codepen.io/prasmi/pen/damNbm

Steps
1. Click on Custom Error
2. Click on Reset Validation - custom error message is still visible
3. Click Validation - Required error message is not displayed

**Comment by ppatkar** [comment]
Looks like validate, resetValidation, reset none have effect of pushed custom error-messages

**Comment by KaelWD** [comment]
Correct, you have to handle that yourself. The only bug I see here is `error-messages` not being merged with `rules`.

**Comment by ppatkar** [comment]
Docs would need to  state that custom messages will not be cleared for validate, resetValidation, reset

Alternatively all the above functions can have parameter clearCustom default=false.

**Comment by KaelWD** [comment]
> custom messages will not be cleared

That's obvious if you ask me, props are one-way.
