### ISSUE TITLE
[question] vue add vuetify still is 1.3.0

### ISSUE THREAD

**Issue by zhengwenjiee** [vuetifyjs/vuetify#6443]
when i use `vue add vuetify` to install it, vuetify version is 1.3.0. but the release version is 1.5.0.

how i can update to 1.5.0 with `vue add vuetify`.

**Comment by KaelWD** [comment]
https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
