### ISSUE TITLE
[Feature Request] API | API allows elements to trigger actions on a server

### ISSUE THREAD

**Issue by crewow** [vuetifyjs/vuetify#6444]
### Problem to solve
Integrates Seamlessly with UI
API is designed to make the process of integrating data sources to UI components seamless, tying API request state to UI states automatically.
see https://semantic-ui.com/behaviors/api.html 

### Proposed solution
we can integrate with all databases via api and its can read json data. api data like this https://api.semantic-ui.com/tags/

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
