### ISSUE TITLE
[Bug Report] Expansion panel broken

### ISSUE THREAD

**Issue by engblh** [vuetifyjs/vuetify#6448]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Chrome 72.0.3626.96
**OS:** Windows 10

### Steps to reproduce
Vuetify 1.5.0 seems broken the expansion panel component with model. After looking at the code Vuetify package (TS file), here is fix i had to do - instead of using : v-model="panel", USE :value="panel". Here is codepen. https://codepen.io/engblh/pen/LqjqGg what do you think ?

### Expected Behavior
v-model should work ?

### Actual Behavior
does not work

### Reproduction Link
<a href="https://codepen.io/engblh/pen/LqjqGg" target="_blank">https://codepen.io/engblh/pen/LqjqGg</a>

**Comment by MajesticPotatoe** [comment]
seems there's a few things wrong with your codepen:
- data should be in the form of a function returning an object
- you need to have your component within a `v-app`
- `v-slot:header` should be `slot="header"`
https://codepen.io/anon/pen/OdvZrj

**Comment by KaelWD** [comment]
- only for components
- yes, but wouldn't affect this
- no

:v-model shouldn't have `:`

**Comment by MajesticPotatoe** [comment]
`v-slot:header` syntax doesn't seem to be playing well with v-model but standard syntax + `v-model` is fine

**Comment by KaelWD** [comment]
https://github.com/vuejs/vue/commit/060686d6ea4d013129b4d2e93d7d2e5c93e09686
