### ISSUE TITLE
[Bug Report] VSelectList always wraps the item scoped slot in a v-list-tile

### ISSUE THREAD

**Issue by deckerst** [vuetifyjs/vuetify#6449]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Firefox 65.0
**OS:** Mac OS 10.14

### Steps to reproduce
Create a `v-select` with an `item` scoped slot. Instead of a `template`, the scoped slot root should be a `v-list-tile`.

### Expected Behavior
The scoped slot should not be wrapped in a `v-list-tile`, as it is a `v-list-tile` itself.

### Actual Behavior
The slot is wrapped in a `v-list-tile`, so it is rendered with a tile within another:
`<div role="listitem">
  <a class="v-list__tile v-list__tile--link theme--light">
    <div role="listitem">
      <div class="v-list__tile theme--light">
            [content here...]
`

### Reproduction Link
<a href="https://codepen.io/anon/pen/vbRzGY" target="_blank">https://codepen.io/anon/pen/vbRzGY</a>

### Other comments
It used to work with Vue 2.5. It seems that with Vue 2.6 scoped slots are always returned in an array (not directly), and the Vuetify method that checks whether wrapping is needed does not account for that.

**Comment by KaelWD** [comment]
Already fixed (e19189c4e7c237835599f35ab485a4bb33c02904), will go out tomorrow.
