### ISSUE TITLE
you cannot scroll down in a large dialog

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#645]
### Steps to reproduce
- create a dialog with an height > window.height
- try to scroll down to the bottom of the dialog

### Versions
vuetify 0.12.2

### What is expected ?
The dialog should be scrollable and the body shouldn't be scrollable
Bootstrap example: https://v4-alpha.getbootstrap.com/components/modal/#scrolling-long-content

### What is actually happening ?
you cannot scroll to the bottom of the dialog but to the bottom of the content

### Reproduction Link
https://codepen.io/kpilard/pen/aWeLjp

**Comment by kpilard** [comment]
@johnleider Thank you for the fast fix. But the codepen still doesnt work. Do I have to change something in the codepen?

**Comment by johnleider** [comment]
This hasn't been released yet.

**Comment by kpilard** [comment]
okay i thougt it is in v.012.7
https://github.com/vuetifyjs/vuetify/releases/tag/v0.12.7

**Comment by johnleider** [comment]
Well looks like I'm wrong. Let me see why.

**Comment by johnleider** [comment]
I apologize, I have no idea why but it looks like my fix is not there/doesn't work.

**Comment by kpilard** [comment]
@johnleider no problem. Thank you for your fast response. I was just confused

**Comment by johnleider** [comment]
This is confirmed fixed and now has a specific example within the docs.

**Comment by shongololo** [comment]
Scrolling in dialogues is not working for me (version 0.13).

I've tried per the example but seem to be having no luck.

The API documentation refers to a v-card-row which I assume is a deprecated element?
