### ISSUE TITLE
[Bug Report] The item columns of data table does not ordered by headers data

### ISSUE THREAD

**Issue by peterhpchen** [vuetifyjs/vuetify#6451]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Just open reproduction link.

### Expected Behavior
`Fat` and `Calories` item columns should exchange.

### Actual Behavior
`Fat` and `Calories` item columns does not exchanged.

### Reproduction Link
<a href="https://codepen.io/peterhpchen/pen/gqeBZj" target="_blank">https://codepen.io/peterhpchen/pen/gqeBZj</a>

### Other comments
I change `Fat` and `Calories` order in the headers data. The item columns should change too.

**Comment by KaelWD** [comment]
You have to change the slot too.
