### ISSUE TITLE
[Feature Request] Advance data grid rendering improvements

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#6452]
### Problem to solve
I use pretty advance data grids, sometime containing menu items and buttons. This causes the data grids to render substantially slower than without those items, especially working with 50 row per page. The obvious quick solution is to make the max row per page smaller. But I would like if it can handle more before the performance is impacted.

Please take a look at the sample I created. This `clean data` and `reset data` https://codepen.io/Jubels/pen/wNywdO

### Proposed solution
I am not sure if this is an bug or a feature request. But a solution would be if we can improve the rendering speed when there is other components in the datagrid.

**Comment by johnleider** [comment]
Rendering performance is being worked on as part of the v2.0 data-table update. Please follow this PR for future updates. https://github.com/vuetifyjs/vuetify/pull/5737
