### ISSUE TITLE
[Feature Request] Add move to chunk at page v-pagination component

### ISSUE THREAD

**Issue by sehee-ya** [vuetifyjs/vuetify#6453]
In pagination component, I want to use next button and prev button as next chunk and prev chunk. Please let user change event of ext. prev, next button manually, then they can move how much they want.

Please refer to below.
https://jsfiddle.net/matfish2/rnw8jjs3/

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
