### ISSUE TITLE
[Bug Report] Browser auto-filling makes 'v-on' events called (making a login form automatically submitted)

### ISSUE THREAD

**Issue by illyr** [vuetifyjs/vuetify#6454]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.3
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows

### Steps to reproduce
1. Go to https://jsfiddle.net/rkwdtcum/5/
2. In the form: put a login and a password (do not submit anything)
3. Save it with your favorite browser (save the credentials to make possible auto-filling)
4. Reload the jsFiddle
5. Click on the first field to make visible the auto filling option by Chrome (only tested on Chrome)
6. Enable the auto-filling
-> "v-on" events are thrown

### Expected Behavior
No "v-on" events called
-> I do not want the login form to be automatically submitted

### Actual Behavior
The login for is automatically submitted (magical auto-login)

### Reproduction Link
<a href="https://jsfiddle.net/rkwdtcum/5/" target="_blank">https://jsfiddle.net/rkwdtcum/5/</a>

### Other comments
This behavior is new since https://github.com/vuejs/vue/releases/tag/v2.6.0-beta.2

Before -> the v-on events are not thrown with auto filling
With v2.6.0-beta.2 and MORE, auto-filling make 'v-on' events thrown automatically

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue/issues/9441

**Comment by KaelWD** [comment]
Not related to vuetify, and you should be using `@submit.prevent` for form submission anyway.
