### ISSUE TITLE
[Bug Report] v-list-tile component renders anchors with no href rather than buttons 

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#6455]
### Versions and Environment
**Vuetify:** 1.4.8
**Vue:** 2.6.5
**Browsers:** Chrome 72.0.3626.81
**OS:** Mac OS 10.14.3

### Steps to reproduce
Create a `v-list` and `v-list-tile` list without `href`, `to` or `nuxt` props but with an `v-on:click=" "` event.

### Expected Behavior
The list items should render as `<button>` elements.

### Actual Behavior
They render as `<a>` (anchor) elements with no href. This is incorrect because they do not navigate anywhere.

### Reproduction Link
<a href="https://codepen.io/anon/pen/MLGYjr?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/MLGYjr?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Maybe something we can look into for v2 update @MajesticPotatoe
