### ISSUE TITLE
[Feature Request] v-select should expose attributes/slot for v-list

### ISSUE THREAD

**Issue by varna** [vuetifyjs/vuetify#6458]
### Problem to solve
I use custom item slot for `v-autocomplete` and my items are too dense. I can't fix that with props.
`v-autocomplete` uses `v-select`. `v-select` uses `v-text-field` and `v-menu`. `v-menu` is mounted globally so I cannot cascade styling by adding parent class/style.

Exposing props would allow user to use such props like `subheader`, `two-line` and `three-line` for `v-list` container used in `v-menu` (only `dense` prop is exposed, other props might be exposed via `Colorable` and `Themeable` mixins, but this is not tested).

Exposing slot would allow users to customise container looks. This also means that user can add `classes` to customise children looks. Enforcing something is a bad thing, right?

### Proposed solution
- Expose slot for `v-list` in `v-select`;
- Expose attributes for `v-list` in `v-select`:
  - All of them (props, classes, events etc.);
  - It could be done by adding prop (i.e. `list-attributes`) that is spread into `v-list` before other attributes;
- Update slots documentation, because currently it's wrong:
  - `append-item` and `prepend-item` are missing;
  - `append` and `prepend` are using description that should be used for `append-item` and `prepend-item`.

**Comment by loomchild** [comment]
If I understand correctly, due to this limitation if I set `dark` attribute on `v-select` or `v-autocomplete`, then although the input field will be shown as `dark`, the list of options will still be displayed as `light`. Additionally, there's no way to change this behavior via slots, the only solution is to change global theme. Could you please confirm that?

**Comment by varna** [comment]
> If I understand correctly, due to this limitation if I set `dark` attribute on `v-select` or `v-autocomplete`, then although the input field will be shown as `dark`, the list of options will still be displayed as `light`. Additionally, there's no way to change this behavior via slots, the only solution is to change global theme. Could you please confirm that?

Yes, 

`v-select` or `v-autocomplete` create the `v-list-item` elements and expose their _content_ (instead of the item itself) as a slot. In this case I can change the content of `v-list-item` but I can't change the `v-list-item` itself (i.e. by adding `dark` property).

### Current usage

```vue
  <template>
    <v-list-item-content>{{ data.item }}</v-list-item-content>
  </template>
```

### Suggested usage

```vue
  <template>
    <v-list-item dark class="AnythingElse"> <!-- you can't control this element now because it is generated by Vuetify under the hood -->
      <v-list-item-content>{{ data.item }}</v-list-item-content>
    </v-list-item>
  </template>
```

**Comment by KaelWD** [comment]
> there's no way to change this behavior via slots, the only solution is to change global theme

`menu-props="dark"`

> create the v-list-item elements and expose their content (instead of the item itself) as a slot

If the root element of the slot is a v-list-item it doesn't render another one:

https://github.com/vuetifyjs/vuetify/blob/739048495a8e4768794bee2a8517acef9e33c1fd/packages/vuetify/src/components/VSelect/VSelectList.ts#L200-L202 https://github.com/vuetifyjs/vuetify/blob/739048495a8e4768794bee2a8517acef9e33c1fd/packages/vuetify/src/components/VSelect/VSelectList.ts#L216-L220

**Comment by varna** [comment]
Sorry, this issue is really old... Maybe some features changed since then.

I already solved this issue on my project long ago by using separate input and `menu` components instead of a `select` or `autocomplete`. I wouldn't mind if you close this issue.

> menu-props="dark"

Sounds good. Maybe I needed to add props to the `v-list`, instead of `v-menu` for some reason?

> If the root element of the slot is a v-list-item it doesn't render another one:

True, but you need list items with `header` and `divider` boolean properties to add (headers and dividers) without using slots that get wrapped in `v-list-item` by default.
<img width="370" alt="CleanShot 2021-07-19 at 10 45 13@2x" src="https://user-images.githubusercontent.com/6717694/126122199-3a90eaa8-969f-43de-b814-437e60d1fee0.png">

**Comment by varna** [comment]
I guess that during development my autocomplete got bloated so much that it didn't fit the original use case 🤷

**Comment by loomchild** [comment]
Hi and thank you for your help. `menu-props="dark"` solves my issue, thank you very much for pointing it out. I wonder whether perhaps it should be a default behavior if the select component is `dark` (to avoid any confusion). Perhaps I can propose a simple PR for that?

I am afraid that I won't be able to contribute much to your discussion regarding `v-list-item` and `v-list` slot though

**Comment by KaelWD** [comment]
> perhaps it should be a default behavior if the select component is dark

This was intentional, a common use case is to have a darker background but without affecting the menu: https://vuetifyjs.com/en/components/autocompletes/#item-and-selection

**Comment by varna** [comment]
I need this feature again :D 

This time I want to change the style of `v-autocomplete` list items from `dense` to normal. But you can't pass props to the `v-list` :D

**Comment by daniandl** [comment]
I still need this functionality, even in v3...
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSelect/VSelect.tsx#L393C63-L393C63

It wouldn't be too hard to add a `{ ...props.listProps }` here, no?
(If it was that easy I would PR it myself, but I'm not sure of the other changes & side effects)
