### ISSUE TITLE
[Bug Report] Autocomplete lazySearch value not cleared when available option has been selected

### ISSUE THREAD

**Issue by scp-nm** [vuetifyjs/vuetify#6459]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.5
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
In the **Select** type `ali`, when the name appears then hit *tab* key to select, once the item **Ali Connors** is selected the typed term `ali` still remains.

### Expected Behavior
I would expect the value for `lazySearch` to be cleared once an item has been selected.

### Actual Behavior
The value for `lazySearch` remains in the text field.

### Reproduction Link
<a href="https://codepen.io/scp-nm/pen/aXGBVv" target="_blank">https://codepen.io/scp-nm/pen/aXGBVv</a>

**Comment by johnleider** [comment]
This is intended: https://github.com/vuetifyjs/vuetify/pull/6342
