### ISSUE TITLE
[Bug Report] Swiping inner tab will swipe outer tab

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#6462]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.5
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
This seems to be the issue mostly on touch screen devices (mobile and tablets) where swiping gesture is available.
From the desktop Chrome browser go to the reproduction link and then:
1. Open developer tools (Ctrl + Shift + I)
2. Toggle device toolbar (Ctrl + Shift + M) and select some smaller resolution device (eg. Tablet - 768px)
3. If you try swiping inner tabs (eg. hold left mouse button on "Inner Item 3" and drag to the left to bring tabs) it will actually swipe the outer tab. 

### Expected Behavior
Inner tab should be swiped and not the outer one.

### Actual Behavior
Outer tab is swiped.

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/bzMRPV" target="_blank">https://codepen.io/milost1982/pen/bzMRPV</a>

### Other comments
It seems that swiping event is propagating upwards to the outer tab.
Similar thing happens when you have some other inner element that can be horizontally swiped or scrolled (eg. data table with wide rows so when I swipe them to the right the outer tab is swiped).

**Comment by blalan05** [comment]
You could add touchless to the outer tabs `v-tabs-items touchless`.

**Comment by johnleider** [comment]
I'll look into this when tabs gets refactored for 2.0
