### ISSUE TITLE
[Feature Request] Slider with ticks and thumb labels

### ISSUE THREAD

**Issue by ManitaJ** [vuetifyjs/vuetify#6465]
### Problem to solve
We have sliders in our app that have fixed values at tick points and ones that allow the user to choose any % value. We'd like them to look more alike and to have visual cues that show the way they work more clearly than the current sliders in Vuetify.

### Proposed solution
Show users labeled tick points.
Show the selected value in the thumb label.
Allow users to use tick points and values in-between.

**Comment by aburai** [comment]
There are props for that:
- tick-labels
- thumb-label

**Comment by ManitaJ** [comment]
Hi André,

Thanks for getting back to me so quickly.
The issues we’re seeing is we can’t use ticks and choose a value between the ticks.
The thumbs are great as a visual label of what was chosen but it’s really the choice of values between ticks that we’re after.

Manita

**Comment by johnleider** [comment]
Do you have an example/picture or something the like to demonstrate what you are talking about?

**Comment by KaelWD** [comment]
I thought it was pretty clear, this without the snapping: https://codepen.io/anon/pen/zbGOVP?editors=1010

Removing `step` doesn't work because that also sets the space between ticks.

**Comment by ManitaJ** [comment]
Hi,

Thanks Kael, John and André.
Sorry took a while to get back to this.
These are our designs.

Example 1
The user can click on a step or label to select a figure or slide to an amount in between the labels.
The selected amount shows in the thumb label.
This lets users quickly select whole numbers and when they return to the page they can quickly see the amount selected.
[cid:image001.png@01D4D2A9.FC266E30]

Example 2
The user can click a step or label to chose an option. The label and the value are not the same, they complement each other to give the user more detail.
[cid:image002.png@01D4D2A9.FC266E30]
Thanks,

Manita

**Comment by keeganwitt** [comment]
An example in another library would be https://material-ui.com/components/slider/, with their example slightly tweaked so steps are 1 instead of 10:

```javascript
const marks = [
  {
    value: 0,
    label: '0°C',
  },
  {
    value: 20,
    label: '20°C',
  },
  {
    value: 37,
    label: '37°C',
  },
  {
    value: 100,
    label: '100°C',
  },
];
function valuetext(value) {
  return `${value}°C`;
}
function valueLabelFormat(value) {
  return marks.findIndex(mark => mark.value === value) + 1;
}
export default function DiscreteSlider() {
  const classes = useStyles();
  return (
    <div className={classes.root}>
      <Typography id="discrete-slider-custom" gutterBottom>
        Custom marks
      </Typography>
      <Slider
        defaultValue={20}
        getAriaValueText={valuetext}
        aria-labelledby="discrete-slider-custom"
        step={1}
        valueLabelDisplay="auto"
        marks={marks}
      />
    </div>
  );
}
```
This lets you drag the slide to select any temp between 0 and 100 centigrade, but you can also click on any of the marks defined to easily choose those temps.

**Comment by keeganwitt** [comment]
Actually, here's a Vue library that does the same thing: https://nightcatsama.github.io/vue-slider-component/#/basics/marks.  The mark as an object, array, and function examples all let you drag slider to any value, but also click on any mark.
