### ISSUE TITLE
[Bug Report] Changing the text in a tab doesn't update the slider

### ISSUE THREAD

**Issue by jacrosby** [vuetifyjs/vuetify#6466]
### Versions and Environment
**Vuetify:** 1.4.0
**Vue:** 2.5.21
**Browsers:** Firefox 64.0
**OS:** Windows 10

### Steps to reproduce
Change the text displayed on a tab

### Expected Behavior
The slider updates accordingly to reflect the width of the text

### Actual Behavior
The slider retains its original width

### Reproduction Link
<a href="https://codepen.io/Jimbo123/pen/MLGMNp?editors=1010" target="_blank">https://codepen.io/Jimbo123/pen/MLGMNp?editors=1010</a>

**Comment by johnleider** [comment]
We have no way of knowing when this text value changes. You will need to manually call the slider to re-adjust. https://codepen.io/johnjleider/pen/GzYLGX?editors=1010

**Comment by jacrosby** [comment]
Thanks, that's good to know!

**Comment by moas** [comment]
Hi,
When the tab-item content change, the slider position failed. I try "this.$refs.tabs.callSlider()" via tab value watching but not fix it!
