### ISSUE TITLE
[Feature Request] Enable custom mask on controls like v-text-field

### ISSUE THREAD

**Issue by HamedFathi** [vuetifyjs/vuetify#6467]
### Problem to solve
I want to use a 3rd party mask library for Vuetify controls like `v-text-field` but It is not possible now. You can find the issue here https://github.com/uNmAnNeR/imaskjs/issues/130

### Proposed solution
It should be configurable for 3rd party mask libraries or support custom mask function.

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
