### ISSUE TITLE
[Feature Request] Transition duration options

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#6470]
### Problem to solve
This would let us control the duration of the stock transitions

### Proposed solution
Provide another prop for each duration, that lets us control the duration of them. 🙂 Thanks!

**Comment by clementmas** [comment]
That'd be a good option to have.
Meanwhile, is there a workaround that doesn't involve creating a custom transition?

**Comment by andrewspy** [comment]
If duration option is added, I would propose to have a delay option added as well, so that we can apply some delay to make the transition start after the first transition ended, something like a chaining transition.

**Comment by jaminroe** [comment]
> If duration option is added, I would propose to have a delay option added as well, so that we can apply some delay to make the transition start after the first transition ended, something like a chaining transition.

I agree, thanks for mentioning that!

**Comment by douglasg14b** [comment]
Very much wanted, isn't this already a natively supported transition prop in vue?

**Comment by C0C41N** [comment]
Lots of components are missing these kind of "Basic" configs, Its been more than a year since this feature request and still nothing lol
When will vuetify be as mature as material-ui ?
