### ISSUE TITLE
[Bug Report] 'prepend-icon' not working when 'iconfont' is 'faSvg'

### ISSUE THREAD

**Issue by DomClayton** [vuetifyjs/vuetify#6474]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.27
**OS:** Windows 10

### Steps to reproduce
1. Follow the installation steps necessary for Font Awesome SVG: https://vuetifyjs.com/en/framework/icons#install-font-awesome-svg-icons

2. Create an input element such as `v-text-field` and give it a property such as `prepend-icon="fal fa-envelope"`

### Expected Behavior
The prepended icon should be a Font Awesome SVG using the `font-awesome-icon` Vue component.

### Actual Behavior
The prepended icon is inserted as a standard `i` element, so it doesn't get replaced.

### Other comments
You can manually have `fontawesome-svg-core` swap these out with its `dom.i2svg` and `dom.watch()` utility, but this isn't ideal as it affects the DOM directly, and prevents further manipulation of the element via Vue. For example, the icon colour doesn't get changed when an element gets focus.

(Sorry, I couldn't create a Codepen that replicated this setup due to the necessary steps in step 1.)

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/framework/icons#custom-font-awesome-pro-icons

```js
Vue.use(Vuetify, {
  icons: {
    envelope: {
      component: FontAwesomeIcon,
      props: {
        icon: ['fal', '2\. envelope']
      }
    }
```
`prepend-icon="$vuetify.icons.envelope"`

Or just use `<font-awesome-icon slot="prepend">`
