### ISSUE TITLE
[Bug Report] V-Dialog > Width is ignored when using scrollable

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#6479]
### Versions and Environment
**Vuetify:** 1.5.1
**Last working version:** 1.5.0
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.96, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1) Use a dialog that has a set width and is scrollable

### Expected Behavior
Dialog would be set at that width.

### Actual Behavior
Dialog expands to almost the full width of the screen

### Reproduction Link
<a href="https://codepen.io/anon/pen/exKxXw" target="_blank">https://codepen.io/anon/pen/exKxXw</a>

**Comment by MatthewAry** [comment]
I'm experiencing this issue too.

**Comment by MajesticPotatoe** [comment]
Seems that `scrollable` is adding `flex: 1 1 0px;` (it will still scroll without the prop)

**Comment by MajesticPotatoe** [comment]
This actually hasn't changed at all. you should use `max-width="600px"`
