### ISSUE TITLE
[Bug Report] Star rating, individual stars should flex together as one component

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#6481]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a v-rating component inside a data table. 

### Expected Behavior
Default to showing stars in a sequence / row as one component (ie the way a button takes up a specific amount of space.)

Could have option to "flex per star" too.

### Actual Behavior
The stars individually flex. This generally looks silly.

### Reproduction Link
<a href="https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/XOYwJx?editors=1010" target="_blank">https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/XOYwJx?editors=1010</a>

**Comment by swirlingsand** [comment]
![image](https://user-images.githubusercontent.com/18080164/52677152-97c06b00-2ee1-11e9-8fca-b14b21c2dcb7.png)

**Comment by sh7dm** [comment]
@swirlingsand I think it's good for resposivity, but looks strange. Maybe just convert it to column on some breakpoint?

**Comment by swirlingsand** [comment]
I think it already does the column thing at a certain point - that's fine in my opinion.

Default should be held together as a sequence, and maybe a flag to "flex per star".

To me the default use case is ratings and for ratings the expectation is it's in a sequence.

**Comment by aburai** [comment]
`<v-rating class="nowrap"></v-rating>`
```css
.nowrap { white-space: nowrap; }
```

**Comment by swirlingsand** [comment]
Working! Thanks :)

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/commit/c92e569ab0446ad9276e640c90d67a6744a45957
