### ISSUE TITLE
[Feature Request] Combobox doesn't create new item if it isn't exists.

### ISSUE THREAD

**Issue by tuyennv216** [vuetifyjs/vuetify#6485]
@rgalaxy Look the combobox can now do this functionality:
https://vuetifyjs.com/en/components/combobox

_Originally posted by @rudolph2907 in https://github.com/vuetifyjs/vuetify/issues/1069#issuecomment-437915523_

I know that combobox auto create new item if it is not exists in a menu item list.
But can I turn off this function?
I want user only selecting item in a list.

**Comment by jacekkarczmarczyk** [comment]
Use `v-autocomplete`

**Comment by tuyennv216** [comment]
Haha, I fint it. I not read about it because my requirement suggested using combobox.
Thanks you for the reply.
