### ISSUE TITLE
[Feature Request] Supports video for media card

### ISSUE THREAD

**Issue by tomocrafter** [vuetifyjs/vuetify#6486]
### Problem to solve
Be able to use the video for the media cards. I want to controls option to that.
or just like add the vue-material media card tag.

### Proposed solution
add the <v-video/> or <v-card-media></v-card-media>

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
