### ISSUE TITLE
[Feature Request] Set v-carousel first item

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#6489]
### Problem to solve
Being able to set the first item (e.g. the first image) in a carousel, which is especially useful for carousels inside `v-dialog`. Right now, the only way to achieve this is sorting the item/image list beforehand.

### Proposed solution
Add some sort of `:first-item` prop to `v-carousel` or `v-carousel-item`.

**Comment by blalan05** [comment]
No, this is already doable with v-model on v-carousel. https://codepen.io/anon/pen/bzjLdB?&editable=true&editors=111

**Comment by blalan05** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
