### ISSUE TITLE
[Bug Report] Outline button color changes are buggy on Safari

### ISSUE THREAD

**Issue by Tamakiwan** [vuetifyjs/vuetify#6490]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.5.17
**Browsers:** Safari
**OS:** Mac OS 10.14.3

### Steps to reproduce
Dynamically change button color, change button color on hover.

### Expected Behavior
The color should change the component color consistently -border color and text color should stay the same.

### Actual Behavior
The behavior varies:
- Border color changes partially (for example, top border stays a different color than the rest).
- Text color and border color do not change at the same time when the color prop is modified on hover.
- Text color stays an entirely different color from the border color.

### Reproduction Link
<a href="https://codepen.io/MarinaGranell/pen/xyaaar?editors=1111" target="_blank">https://codepen.io/MarinaGranell/pen/xyaaar?editors=1111</a>

**Comment by seanmedcalf** [comment]
I am experiencing a similar issue with Safari and text inputs.

<img width="304" alt="Screen Shot 2020-03-19 at 10 58 51 AM" src="https://user-images.githubusercontent.com/50877884/77104054-628e2280-69e9-11ea-82b7-dd960bd3bade.png">

<img width="320" alt="Screen Shot 2020-03-19 at 10 58 27 AM" src="https://user-images.githubusercontent.com/50877884/77104077-691c9a00-69e9-11ea-8b79-87c940538023.png">

This only happens in Safari. As soon as I bring up dev tools to inspect the element, it auto-rerenders and the colors are as expected. I'm guessing it has something to do with the browser rendering flow. Here are the settings I use:

```
<v-text-field
                  id="officeEmail"
                  v-model="locationCopy.officeEmail"
                  :rules="emailRules"
                  :label="$t('location-management-details.email').toUpperCase()"
                  placeholder=" "
                  color="#4183c1"
                  background-color="white"
                  outlined
                />
```

**Comment by a-froghyar** [comment]
Forcing the re-render of the element with js solved my issue on Safari:

```
const element = document.getElementById('name')
element.style.visibility = 'hidden'
element.style.visibility = 'visible'
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
