### ISSUE TITLE
[Feature Request] Move Paragraph and Ordered/UnorderedList Tag style to css class

### ISSUE THREAD

**Issue by renatodex** [vuetifyjs/vuetify#6492]
### Problem to solve
The style file vuetify/dist/vuetify.min.css is styling block elements, and its overriding my Reset CSS for previous Styled pages.

### Proposed solution
I believe all elements relying on these Block Element tags should be dependant on class level styling.
I know that there was a discussion like that on the past, regarding to other Block Element tags, but im not sure why those Tags where left behind on the past refactory.

**Comment by johnleider** [comment]
Which block elements?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
