### ISSUE TITLE
[Bug Report] Something Messes up the text color in chrome

### ISSUE THREAD

**Issue by Aryanr64x** [vuetifyjs/vuetify#6493]
The text color of the light theme is very light in chrome as compared to edge and firefox. This makes 
the content barely readable
**In Chrome**

![v2](https://user-images.githubusercontent.com/29349007/52728842-05ea5800-2fde-11e9-8a28-6dc1475d1640.PNG)

**In other browsers**
![v1](https://user-images.githubusercontent.com/29349007/52728897-1e5a7280-2fde-11e9-924d-48a6331d2032.PNG)

I went through the entire source code but I cant find the style thats causing it . I know the fix  is easy .
But This browser specific behaviour  is an ISSUE.So I am reporting it .
(I use chrome 72)

**Comment by MajesticPotatoe** [comment]
🤔 seems strange, maybe its optical illusion from gradient/shadows? I put the chrome 72 and firefox 64 and they look the same
![321](https://user-images.githubusercontent.com/27827979/52729531-5bdfe100-2f87-11e9-9296-a8e971a30cd7.png)

**Comment by Aryanr64x** [comment]
The gradient ;looks the same. But not the text inside the p tags . There cant be any illusion with white background in those cards

**Comment by 06b** [comment]
It looks like when roboto is being applied for some reason the browser is applying a thinner font-weight.

I'm can reproduce this issue in chrome if I set the font-weight to something like 100 or 200 on the paragraph in the dev tools but I'm not able to reproduce it when I just visit the site normally. 

@Aryanr64x Do you have any extensions installed? Or have you changed any of the settings in chrome?

**Comment by Aryanr64x** [comment]
No I dont have any extension that can mess up the view......!!!

**Comment by Aryanr64x** [comment]
its a bug in chrome in general . It happens everywhere . Not a fault of vuetify......This bug can be fixed
with some help from  https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browse 
but only if other people report the same issue in chrome 72
