### ISSUE TITLE
v-navbar-item error

### ISSUE THREAD

**Issue by leecz** [vuetifyjs/vuetify#65]
i use `<v-navbar-items>` , get an error '_vm.click is not a function' in browser console.
and 
i don't know what does 'v-on:click.native="click"' for?

**Comment by johnleider** [comment]
Please make sure you are using the latest version of vue. If you are, please provide a an example of this bug,  thank you.

**Comment by johnleider** [comment]
Even though this was first, https://github.com/vuetifyjs/vuetify/issues/66 seems like the same issue and has provides reproduction steps. Closing

**Comment by leecz** [comment]
sorry for my poor english,
i use the latest vue and vuetify,
my code: 
```javascript
//template
<v-navbar-items v-bind:items="items"> </v-navbar-items>

// data
        items: [
          { text: 'home', href: '/' },
          { text: 'show', href: '/show', router: true }
        ]

//when i click the show button in browser , the console log error
Uncaught TypeError: _vm.click is not a function
```

and in the vuetify source code , in `src/components/navbar/Navbaritem.vue` file
i saw this line(16) ,  
` v-on:click.native="click"`
i think this may cause the problem , and don't know what does this line doing ?

**Comment by johnleider** [comment]
This has been fixed with https://github.com/vuetifyjs/vuetify/commit/2003ec554f3714f195f32db3cc7c719a0539b6e7.

**Comment by leecz** [comment]
thank you!
