### ISSUE TITLE
Follwed Quick start-Tutorial - blank page

### ISSUE THREAD

**Issue by apbln** [vuetifyjs/vuetify#6500]
I've follwed this tutorial setting up my vuetify project: https://www.youtube.com/watch?v=FbEW3xAmhKs

I did the follwing: vue create vuetify-test -> I chose "manually" -> Babel, Router, linter -> history router (yes) -> Eslint only with error prevention ->vue add vuetify

thats it. After that I ran "npm run serve" and when I click the localhost...-link I get a blank page. with the developer tools in firefox I can see that all tags are at the top in one line. What am I doing wrong??

![unbenannt](https://user-images.githubusercontent.com/38110721/52819226-14ea0c80-30a9-11e9-90ea-01e5e0b4d1a5.png)

In the browser-console it says "Laden fehlgeschlagen für das <script> mit der Quelle "http://localhost:8080/app.js" i.e loading failed for <script> with source...
and shows me the script tag of my index.html

!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title>my-app</title>
  <link href="/about.js" rel="prefetch"><link href="/app.js" rel="preload" as="script"></head>
  <body>
    <noscript>
      <strong>We're sorry but my-app doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    
  <script type="text/javascript" src="/app.js"></script></body>
</html>

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Need to know things like vue version, vuetify version, browser. Additionally there's no reproduction.
The most i can tell from your screenshot is that you are maybe using IE11? (in which case you also most likely do not have polyfill, which is required for IE11).

Thank you for your contribution and interest in improving Vuetify.

**Comment by apbln** [comment]
vue --version
3.4.0
vuetify@1.5.1 | MIT | deps: none | versions: 252
Browser: Firefox

I didn't add any line to the code. I directly ran npm run serve after what I mentioned

**Comment by MajesticPotatoe** [comment]
is your node/npm versions up to date?
Cant seem to reproduce this following the steps you described. Possibly someone else may be able to.

**Comment by apbln** [comment]
node version: v10.15.1

repository: https://github.com/apbln/vuetifyy

**Comment by MajesticPotatoe** [comment]
Seems to be an issue with your local environment. the repo you provided is functioning normally.
Only other thing i could suggest is make sure your browsers are up to date. Maybe try creating the repo again.

**Comment by apbln** [comment]
what could it be in my local environment? Any idea?

**Comment by apbln** [comment]
oh man...It was just an antivirus-programm
