### ISSUE TITLE
[Bug Report] render update on v-for image delete

### ISSUE THREAD

**Issue by exyzzy** [vuetifyjs/vuetify#6503]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.0

### Steps to reproduce
Click on image.

### Expected Behavior
Should delete image that is clicked on.

### Actual Behavior
deletes all images except image to be deleted.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KJGWpL" target="_blank">https://codepen.io/anon/pen/KJGWpL</a>

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

> changes the contents of an array by removing or replacing existing elements

> Returns an array containing the deleted elements. If only one element is removed, an array of one element is returned. If no elements are removed, an empty array is returned.

**Comment by exyzzy** [comment]
Thanks
