### ISSUE TITLE
[Bug Report] v-tab does not deactivate when route changes to a non-tabbed route

### ISSUE THREAD

**Issue by randanunn** [vuetifyjs/vuetify#6505]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.4
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.13.6

### Steps to reproduce
Using vue-router and the `:to` parameter.  Create a route in your app that is not available via v-tab.  Navigate to it and see that the previously selected route/tab is still showing as active in the v-tab

### Expected Behavior
De-activate tab if route does not match the tab.

### Actual Behavior
Previously selected tab stays active even when route changes.

### Reproduction Link
<a href="https://codepen.io/lucille2/pen/bzMmPQ" target="_blank">https://codepen.io/lucille2/pen/bzMmPQ</a>

### Other comments
In my app I use a v-toolbar header with tabs in the extension slot and an account menu in the main slot. The account menu can go to routes that are not available as tabs. But I cannot de-activate the v-tab when the user goes to one of those other routes.  **Using vue-router

**Comment by randanunn** [comment]
<img width="813" alt="screen shot 2019-02-15 at 12 16 37 am" src="https://user-images.githubusercontent.com/5419140/52840590-0276cf80-30b7-11e9-8a80-6cab9ba1d931.png">

**Comment by lucafaggianelli** [comment]
I faced the same bug, is there a workaround to set the active tab? or somehow refresh vtabs?

**Comment by johnleider** [comment]
I'm adding a new prop to help facilitate this functionality. Tabs by nature are **mandatory** which means that it expects to always have a value if it can have one. The new **optional** prop will allow the component to have no designated value.

![tabs](https://user-images.githubusercontent.com/9064066/53505516-96fb0d80-3a79-11e9-8481-70676c35a89d.gif)

**Comment by randanunn** [comment]
Awesome! Thanks John!

**Comment by johnleider** [comment]
Fixed in f22d754

**Comment by dsldiesel** [comment]
Not working for me! V-tab item stays selected when navigating to a route that's not within tab route links.

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by randanunn** [comment]
@dsldiesel you have to set `:optional="true".

**Comment by dsldiesel** [comment]
Thanks @randanunn ,
But it sticks with selected state also binding it.
I don0t know what this is, it is inside a v-navigation-drawer, as follows:

```
<v-navigation-drawer
    :value="drawer"
    width="81px"
    disable-resize-watcher
    mobile-break-point="100"
    clipped
    left
    app
  >
    <v-tabs
      :optional="true"
      vertical
      mobile-break-point="100"
      active-class="blueActive"
    >
      <v-tab
        v-for="(button, index) in menu"
        :key="index"
        class="menuTab"
        :to="button.path"
      >
        <img
          :src="require('@/assets/img/menu/' + button.name + '.png')"
          :alt="button.alt"
        />
      </v-tab>
```

Anything weird?

**Comment by rock-pydev** [comment]
Hi, I have faced an issue that sometimes hides slider.
My code is below

`<v-tabs
          :optional="true"
          v-model="tab"
          background-color="transparent"
          color="#396899"
          slider-color="#de3c40"
        >
          <v-tab
            v-for="item in h_menu"
            :key="item.page_id"
            :to="path(item)"
          ><b>{{ item.menu_name }}</b></v-tab>
        </v-tabs>`

**Comment by rock-pydev** [comment]
Hi
When `optional` is set as true, how can I hide slider bar?

**Comment by bpeab** [comment]
Hello,

It seems the issue reappears with the new version of Vuetify for Vue 3. The `optional` prop is not listed in the docs, do you plan on implementing it or is there any other way to achieve this behavior ?

Thanks!

**Comment by septatrix** [comment]
> Hello,
> 
> It seems the issue reappears with the new version of Vuetify for Vue 3. The `optional` prop is not listed in the docs, do you plan on implementing it or is there any other way to achieve this behavior ?
> 
> Thanks!

I created a new issue, see #21569
