### ISSUE TITLE
[Feature Request] Add JSS Support

### ISSUE THREAD

**Issue by Patrick-Spiegel** [vuetifyjs/vuetify#6506]
### Problem to solve
When you are using third party components in your  apps, which sandbox your environment with an iframe then you need the ability to control, where vuetify renders its style to. 
Vuetify currently does not offer you any support for a-la-carte rendering in an iframe. 

### Proposed solution
https://material-ui.com/customization/css-in-js/

In Material UI you have an approach called JSS. That lets you inject style fragments where ever you want. 

    const jss = create({
      ...jssPreset(),
      // We define a custom insertion point that JSS will look for injecting the styles in the DOM.
     insertionPoint: doc.head
    });

jssPreset is provided by mui.

**Comment by KaelWD** [comment]
Use style-loader's [`insertAt`/`insertInto`](https://github.com/webpack-contrib/style-loader#insertat)

We use SASS, JSS is an entirely separate thing that is not compatible.
