### ISSUE TITLE
[Feature Request] v-edit-dialog - Enable propagating all menu props

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#6510]
### Problem to solve
The property that I specifically need is the `zIndex`.  I have a `v--data-table` inside a `v-dialog` and there doesn't seem to be a way to specify the z-index of the edit menu.  I can imagine there are other cases where other menu props would be useful.

### Proposed solution
Extend the edit dialog to include propagating the menu props down into the inner menu handler.

**Comment by johnleider** [comment]
This component is due for a full rework, something we can look into when that time comes.

**Comment by gabaum10** [comment]
Is there anything I can do in the meantime to work around the bug?  I could add just the z-index property to the menu and put in a PR if that's an acceptable short term fix to my issue.

**Comment by gabaum10** [comment]
Any thoughts on what I should do to deal with the bug in the short term?

**Comment by jacekkarczmarczyk** [comment]
`v-edit-dialog` is basically a `v-menu` with some additional options, you can look at the source and just write your own component that does exactly what you want

**Comment by gabaum10** [comment]
Yeah, I saw that and basically lifted that logic.  For now, that'll work just fine.  Thanks for the feedback.
