### ISSUE TITLE
[Feature Request] Drag&drop support

### ISSUE THREAD

**Issue by kolesnikovav** [vuetifyjs/vuetify#6512]
### Problem to solve
I need make some components draggable. v-chips, v-img or any items components.  And anover components can  be able to accept drag content. I have no found this ability in vuetify.

### Proposed solution
Create mixins draggable & droppable that encapsulate drag&drop logic and can  be attached to some components in place

**Comment by nekosaur** [comment]
We currently have no plans to implement generic drag & drop support for our components. Depending on your needs you should be able to use some 3rd party plugins.
