### ISSUE TITLE
[Feature Request] Menu popover styling option

### ISSUE THREAD

**Issue by fnoop** [vuetifyjs/vuetify#6516]
### Problem to solve
Menu component works well functionally as a popover as discussed in this issue:
https://github.com/vuetifyjs/vuetify/issues/1442

However there needs to be a styling option to make it look more like a standard popover that users are used to.

### Proposed solution
Add a popover styling prop?

**Comment by KaelWD** [comment]
> a standard popover that users are used to

Enough with the vague feature requests, show an example of what you actually want.

**Comment by fnoop** [comment]
@KaelWD read the referenced issue, there are extremely specific examples :)

**Comment by jacekkarczmarczyk** [comment]
@fnoop You mean the arrow or what?

**Comment by sagikarni** [comment]
+1

**Comment by zend** [comment]
A arrow pointing to activator would be nice. Maybe it can be done by adding an `arrow`  props?

Before that, we can override `.v-menu__content` and `.v-menu__content:before` to make it look like the popover?

**Comment by SyzbaLinux** [comment]
![image](https://user-images.githubusercontent.com/20104015/141292170-7a39a406-db90-457b-85c8-a8b8290debb0.png)

https://codepen.io/Adam_Orlov/pen/NWPgywg?editors=1100

**Comment by johnleider** [comment]
The only actionable part of this is the bubble, which is covered in #4843

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
