### ISSUE TITLE
[Bug Report] v-overflow-btn does not really work with segmented and outline enabled at the same time

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#6517]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Firefox 65.0
**OS:** Ubuntu undefined

### Steps to reproduce
Create `v-overflow-btn` with both `segmented` and `outline` enabled at the same time.

### Expected Behavior
It should functionally work as without `outline`, but it should visually look with `outline`.

### Actual Behavior
It does not work like `segmented` anymore. If I select an item from dropdown and then try to click on the button, it just opens a dropdown again, instead of accepting click on the button.

### Reproduction Link
<a href="https://codepen.io/anon/pen/wNQeBo" target="_blank">https://codepen.io/anon/pen/wNQeBo</a>

**Comment by johnleider** [comment]
I'm not sure how I feel about this as these props are intended to be inclusive.

**Comment by mitar** [comment]
Yea, but they are not at the moment, no? (If I understand you correctly.)

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity and your reproduction no longer works.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
