### ISSUE TITLE
[Bug Report] autocomplete suggestions bigger than input if 

### ISSUE THREAD

**Issue by devolution2409** [vuetifyjs/vuetify#6518]
### Versions and Environment
**Vuetify:** CDN version (1.5.1)
**Vue:** CDN version (2.6.6 i think)
**Browsers:** Chrome 67.0.3396.79
**OS:** MacOS El Capitan

### Steps to reproduce
Create an autocomplete field with tons of data, and add :menu-props="{auto:true}" attribute, it will correctly stop lazy-loading the data and load everything altogether (so scrollbar is the right height), but the size of the autocomplete suggestions is wrong.

### Expected behavior
Autocomplete suggestions field should be the same size as the input field.

### Actual behavior
Suggestions field size isn't the same as input.

### Reproduction link
https://codepen.io/anon/pen/bzQRxa

**Comment by jacekkarczmarczyk** [comment]
simplified codepen: https://codepen.io/anon/pen/Jzyjvv

**Comment by johnleider** [comment]
The **auto** prop is intentionally left off from inputs that are not `v-select`. It seems you are using the auto prop on menu to avoid some lazy loading behavior. This might need to turn into a feature request.

**Comment by supraniti** [comment]
a workaround for this issue using a ResizeObserver
note that ResizeObserver is currently [not supported on all browsers](https://caniuse.com/#feat=resizeobserver)


https://codepen.io/supraniti/pen/WNbPJPK
in my case, i had the autocomplete field on the app toolbar (which made it resize whenever the user opened or closed navigation drawer)
so i had to find a solution to match the menu width with the autocomplete input field width.
