### ISSUE TITLE
Tapable.plugin is depreciated error

### ISSUE THREAD

**Issue by sts-ryan-holton** [vuetifyjs/vuetify#6521]
Hi 👋

I'm not sure whether this is a problem related to Nuxt JS, or Vuetify. Recently after setting up a new Nuxt JS project with Vuetify I have been getting an error relating to `tapable.plugin`.

This error shows when running any of the `npm run` commands _(e.g: `npm run dev`)_

Here's the error:

```
 ERROR  (node:4688) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

I'm not sure how to fix this error and haven't had any luck yet, I've tried various of versions.

My `package.json` file contains the following:

```
"dependencies": {
    "@grpc/grpc-js": "0.3.5",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/pwa": "^2.6.0",
    "cross-env": "^5.2.0",
    "firebase": "5.8.2",
    "firebase-auth": "0.1.2",
    "nuxt": "2.4.3",
    "vue-moment": "^4.0.0",
    "vue-resource": "^1.5.1",
    "vuetify": "1.4.4",
    "vuetify-loader": "^1.0.8",
    "vuexfire": "2.3.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.12.1",
    "eslint-config-prettier": "^3.6.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-vue": "^5.1.0",
    "nodemon": "^1.18.9",
    "prettier": "^1.16.4",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }
```

Any suggestions would help on how to fix this error, the project appears to still function correctly, but it's nasty seeing this in my terminal window and for other developers, thanks 👍

**Comment by nekosaur** [comment]
A quick google would have given you this https://github.com/webpack/webpack/issues/6568

**Comment by sts-ryan-holton** [comment]
@nekosaur  I have already read that, but I'm not using `extract-text-webpack-plugin` in my package.json which is why I'm wondering how else to fix this.

**Comment by KaelWD** [comment]
This would be an issue for nuxt, we don't have anything to do with your webpack config.
