### ISSUE TITLE
[Bug Report] V-tab: Conditional tab messes up tabs on change

### ISSUE THREAD

**Issue by tommybravo** [vuetifyjs/vuetify#6527]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
Create a v-tab with named keys, set one tab and tab-item to conditional with v-if. Changing the v-if variable removes the tab and the tab-item, but you cannot shwitch to some of the tabs that should be still visible and accessible. 

### Expected Behavior
Clicking on the tab should take you to the tab-item even if other tabs are removed.

### Actual Behavior
If a tab (and tab-item) is removed by swicthing v-if, some of the tabs are not responding, tab-content does not change.

### Reproduction Link
<a href="https://codepen.io/t-th-tam-s/pen/JxwjNz" target="_blank">https://codepen.io/t-th-tam-s/pen/JxwjNz</a>

### Other comments
It might relate to named "key".

**Comment by tommybravo** [comment]
Might be related: https://github.com/vuetifyjs/vuetify/issues/5515

**Comment by ZenLiuCN** [comment]
change `v-if` to `v-show` make it action 
[example](https://codepen.io/anon/pen/yZwyyv)

**Comment by WORMSS** [comment]
I know I am late to the game here, but could you put the `v-show="condition"` on the tab, and `v-if="condition"` on the tab-item ? Maybe get around the heavy loading ? 

I know it's still a stop gap, but just an idea.

**Comment by johnleider** [comment]
Fixed in f22d754
