### ISSUE TITLE
Make vuetify dropdown menu overflow drawer

### ISSUE THREAD

**Issue by sorasanin** [vuetifyjs/vuetify#6529]
I already asked this on stackoverflow and laracasts and I got no answers.

When I add dropdown menu inside navigation drawer, dropdown content stays under the edge of drawer.

https://jsfiddle.net/sky996/3qLaedgt/

**Comment by ibrahimBeladi** [comment]
Please use the following link to create a new issue:
https://issues.vuetifyjs.com

**Comment by KaelWD** [comment]
- missing v-app
 - `attach` is a compromise between overflow and fixed scrolling, nothing we can really do about that. I suggest removing it and just dealing with the scroll weirdness.
