### ISSUE TITLE
[Feature Request] Support for flex-grow: 0 and flex-shrink: 0

### ISSUE THREAD

**Issue by justinhelmer** [vuetifyjs/vuetify#6530]
### Problem to solve
Currently, the flex CSS for `.layout`, `.flex`, etc. assume `flex-grow: 1` and `flex-shrink: 1`. Although this works for a lot of cases, there are situations where you may only want _some_ children of a flex container to grow/shrink, and others not to.

For example, consider a layout where you want to push a footer to the bottom of the page (but not `fixed`/`sticky`). If you have a wrapper with two children (i.e. `.content` and `.footer`) and they _both_ have `flex-grow: 1`, the `.footer` can grow even though you want it to remain a fixed height. The opposite is also true: the `flex-shrink: 1` results in the content of the footer being shrunk.

The `.shrink` option sets `flex-grow: 0`, but also sets `flex-shrink: 1`, which we wouldn't want in this case (don't want the footer wrapper to shrink smaller than the content).

In this case, it would be nice to be able to set `flex-grow: 0` and `flex-shrink: 0` for _just_ the `.footer`, and allow the `.content` to continue to grow to fill the remaining height.

### Proposed solution
Support for specifying the `.flex-grow` and `.flex-shrink` values, i.e.

```html
<v-layout grow-0 shrink-0>
```

Other solutions (such as [MDBootstrap](https://mdbootstrap.com/docs/vue/utilities/flexbox)) support this capability, and I think it would be a great value-add.

Currently we are adding an additional class to support this behavior and would like to be able to remove it.

**Comment by sh7dm** [comment]
Good for beginner, anyone wants to contribute?

**Comment by justinhelmer** [comment]
sure, I took a stab at it: https://github.com/vuetifyjs/vuetify/pull/6533

**Comment by sh7dm** [comment]
Fixed in #6538
