### ISSUE TITLE
[Bug Report] Incorrect behavior in v-checkbox

### ISSUE THREAD

**Issue by egorovd** [vuetifyjs/vuetify#6531]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chromium 71.0.3578.98
**OS:** Ubuntu undefined

### Steps to reproduce
If click on firs checbox, second not changed.
The only difference 

in firrst:

* v-model="checkbox"

in second 

* v-bind="checkbox".

### Expected Behavior
When click on the first, the second  should also change.

### Actual Behavior
When click on the first, the second NOT change.

### Reproduction Link
<a href="https://codepen.io/anon/pen/bzOEwM?editors=1010#0" target="_blank">https://codepen.io/anon/pen/bzOEwM?editors=1010#0</a>

**Comment by jacekkarczmarczyk** [comment]
> v-bind="checkbox"

And that's why the second one doesn't change, i have no idea what this code is meant to do

**Comment by egorovd** [comment]
In doc of [Vue](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components)

Custom events can also be used to create custom inputs that work with v-model. Remember that:
```html
<input v-model="searchText">
```
does the same thing as:
```html
<input
  v-bind:value="searchText"
  v-on:input="searchText = $event.target.value"
>
```

I need the same behavior, and so does not work.

Is this a error or should it be?

Thank you!

**Comment by jacekkarczmarczyk** [comment]
`<v-checkbox :input-value="checkbox" @change="checkbox = $event">`

**Comment by egorovd** [comment]
I am ashamed.
Thank you!

**Comment by yannanna0920** [comment]
> `<v-checkbox :input-value="checkbox" @change="checkbox = $event">`

怎么获取不到event呢  只能拿到checked 的value  `而我想要阻止冒泡事件 
![v-checkebox](https://user-images.githubusercontent.com/48897146/58303254-e1deb400-7e21-11e9-985b-0036119dd0a7.gif)
