### ISSUE TITLE
[Bug Report] v-scroll won't fire when using scoll-snap style

### ISSUE THREAD

**Issue by travbus** [vuetifyjs/vuetify#6532]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.2
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.3

### Steps to reproduce
Scroll the page

### Expected Behavior
when scrolling
v-scroll should fire and <v-flex xs12 class='area ...  should snap to <v-layout  v-scroll="handleScroll" wrap class='container .... 

### Actual Behavior
I can only get either one or the other by removing style height 100vm

### Reproduction Link
<a href="https://codepen.io/travis-pancakes/pen/zeyoww?editors=1111" target="_blank">https://codepen.io/travis-pancakes/pen/zeyoww?editors=1111</a>

### Other comments
code pen was version 1.4.3 but tested some script locally on 1.5.1

**Comment by KaelWD** [comment]
It watches the window by default: https://vuetifyjs.com/en/directives/scrolling#api

**Comment by travbus** [comment]
Yes and css scroll snap conflicts with it. I'm still searching for a fix
