### ISSUE TITLE
[Bug Report] Date Picker not show today

### ISSUE THREAD

**Issue by YipingRuan** [vuetifyjs/vuetify#6537]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.4
**Last working version:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
Date pickers - In dialog and menu

Click the textbook and today is white in the picker 

### Expected Behavior
(use to be a blue circle)

### Actual Behavior
Can't see at official page :https://next.vuetifyjs.com/en/components/date-pickers#date-month-picker

### Reproduction Link
<a href="https://codepen.io/anon/pen/bzOyxb" target="_blank">https://codepen.io/anon/pen/bzOyxb</a>

**Comment by YipingRuan** [comment]
![image](https://user-images.githubusercontent.com/5492274/52956179-8982bb00-33c9-11e9-890a-f26847df8638.png)

**Comment by KaelWD** [comment]
This is still an early work in progress. We are not accepting bug reports for v2 yet until the foundation work is complete.
