### ISSUE TITLE
[Bug Report] Nested v-dialog issue

### ISSUE THREAD

**Issue by runarb** [vuetifyjs/vuetify#6540]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.1
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.13.6

### Steps to reproduce
See linked Github repo.

### Expected Behavior
I expected nesting v-dialog within v-for and populating the v-dialog with data from the loop context to be a viable solution.

### Actual Behavior
I realise that there aren't any consistent relation between the buttons opening the dialogs and the content of the generated dialogs.

### Reproduction Link
<a href="https://github.com/runarb/vuetify-dialog-issue/" target="_blank">https://github.com/runarb/vuetify-dialog-issue/</a>

### Other comments
Please read my comments in the README of the linked repo. I still wonder if I've identified the best solution, and whether you think everything works as expected or not.

**Comment by KaelWD** [comment]
You're opening all three at the same time, that's why the backdrop is so much darker. Your solution is correct, or change the binding to `:value="dialogId === item.id"`
