### ISSUE TITLE
[Feature Request] Data Table horizontal scrollbar visible when table height larger than viewport height

### ISSUE THREAD

**Issue by tasoskn** [vuetifyjs/vuetify#6541]
### Problem to solve
It would make data table navigation so much easier. Currently, you have to scroll at the bottom of the table in order to move scroll the table horizontally. You can also use arrow keys, but that is slow.

### Proposed solution
Maybe place the data table inside a parent container, so that the scrollbar maps to parent.

**Comment by ZenLiuCN** [comment]
maybe it's the same problem #6544 , you can check is it has v-window class inside?

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
