### ISSUE TITLE
[Bug Report] v-badge overlap does not work if it will be used on v-btn icon

### ISSUE THREAD

**Issue by xdoo** [vuetifyjs/vuetify#6542]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.5.22
**Browsers:** Chrome 69.0.3497.92
**OS:** Linux x86_64

### Steps to reproduce
1. Create a v-badge with overlap attribute
2. Place a span (image doesn't work either) with slot badge inside.
3. Place a v-btn icon inside it

### Expected Behavior
It should overlap.

### Actual Behavior
It doesn't overlap.

### Reproduction Link
<a href="https://codepen.io/clausstraube/pen/qggMmB?&editable=true&editors=101" target="_blank">https://codepen.io/clausstraube/pen/qggMmB?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
You can use `class="ma-0"` on the button to remove its margins.

**Comment by xdoo** [comment]
Yes, that works. Thanks. If updated this in code pen. Perhaps this should be a documented example. I think badge on icon button is a frequend use case.

**Comment by johnleider** [comment]
Resolves for 2.0. `v-btn` no longer has implicit margin.
