### ISSUE TITLE
[Bug Report] tabs contant have no proper height under v-contaner for full-height

### ISSUE THREAD

**Issue by ZenLiuCN** [vuetifyjs/vuetify#6544]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 7

### Steps to reproduce
see codepen link. 

### Expected Behavior
tabs should be scrollable

### Actual Behavior
with that structure, v-tabs will not able to scroll as v-window is always full child height.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GzeKdB" target="_blank">https://codepen.io/anon/pen/GzeKdB</a>

### Other comments
i'm do some hack to fix this, but will there be a better one?

**Comment by jacekkarczmarczyk** [comment]
Please reduce your reproduction to minimal, this is hard to debug

**Comment by ZenLiuCN** [comment]
@jacekkarczmarczyk  
[codepen](https://codepen.io/anon/pen/GzeKdB) has been updated

**Comment by ZenLiuCN** [comment]
I've made a directive to handle this [codepen](https://codepen.io/anon/pen/Nomrzq).
this may closed. maybe  should be think as **enchancement**

**Comment by KaelWD** [comment]
You want this? https://codepen.io/anon/pen/bzybEY

I still have no idea what the problem is or how it relates to tabs.

**Comment by ZenLiuCN** [comment]
yeah,this is some solution.so part of it's my bad on stylus. but a better solution is tabs contant can be scrollable not full page be scrollable. It's an `enchancement` indeed.
