### ISSUE TITLE
[Bug Report] vue-tabs-items @input API not working

### ISSUE THREAD

**Issue by barakbd-bluevine** [vuetifyjs/vuetify#6549]
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.21
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.3

### Steps to reproduce
click on tabs

### Expected Behavior
function is called

### Actual Behavior
nothing happens

### Reproduction Link
<a href="https://codepen.io/anon/pen/VgRyjZ?editors=1011" target="_blank">https://codepen.io/anon/pen/VgRyjZ?editors=1011</a>

**Comment by DRoet** [comment]
Seems like it does work, however it only get triggered on `v-tabs-items` when the content gets swiped (mobile). I'm not sure if this a bug exactly since im not sure what is expected

also the docs say it has an `@input` event when it is actually an `@change` event, but that might be an error in the documentation

**Comment by MajesticPotatoe** [comment]
After some consulting with john, seems that @input got removed on `v-tabs-items` when `v-window` was released. Docs seem to missed the update to reflect this.
`@input` is still valid for `v-tabs` and will be fully deprecated for `@change` in 2.0 (will just throw a deprecation warning for now)

**Comment by KaelWD** [comment]
> `@input` got removed on `v-tabs-items`

Both `v-tabs` and `v-tabs-items` now extend `v-item-group`, which uses `@change`. `v-tabs-items` only emits when you swipe between tabs. 

> `@input` is still valid for `v-tabs`

Nope, and the way it's done makes it pretty hard to bring this one back without breaking people who are now using `@change`

**Comment by barakbd-bluevine** [comment]
Thanks for the clarification and updating the docs!
