### ISSUE TITLE
Feature request: Components should expose more its events

### ISSUE THREAD

**Issue by Napzu** [vuetifyjs/vuetify#655]
VuetifyJS components should expose more of its events.

Like when using v-select with multiple option, I like to hook to ie. @selectActive, @selectClosed

That's useful on situation when you like to do expensive ajax but don't want to spam it. Just to trigger it when selection(s) are done. And while selecting, with @selectActive you could inform user ie. "waiting selection".

Another option to avoid function spam is only emit input event only after selection box is closed.
So maybe lazySelect option?

**Comment by johnleider** [comment]
I'm not sure that I agree with this. Having a bunch of custom emitted events only bloats the framework for not much gain, subjectively. What event are you trying to capture that you cannot?

**Comment by Napzu** [comment]
Well as explained. I need to know when multiple selection is done, so after than I can trigger expensive ajax.

But your right, maybe I made the request to broad that not all components should emit more event.

But there is point to have @selectActive and @selectClosed events in v-select component as explained on my first post.

**Comment by johnleider** [comment]
If you are wanting to detect when things are selected, you can watch for a change in the variable that you use for the v-model of the select.

**Comment by Napzu** [comment]
Of course,  but if that variable is binded to trigger expensive ajax, it will trigger everytime it changes. I like to trigger it when user is done selecting and closes the selection box when clicking outside the box.

**Comment by johnleider** [comment]
I'll have to think about this.

**Comment by mix3d** [comment]
you can always run a debounce function, but a 'closed' event on any popup menu, dialog, any closeable ui etc, makes sense.

**Comment by johnleider** [comment]
I agree with @mix3d on this one. Adding a bunch of events only clutters the footprint of the component when the developer can easily (and should expect to) handle off-cases like this.

**Comment by Elbone** [comment]
To anyone reading this a good way to handle events like this is to add a watcher to the input's value changing. eg:
```html
<v-select v-model="selectValue" ...>
  ...
</v-select>
```
```javascript
new Vue({
  ...
  data () {
    return {
      selectValue: null
    }
  },
  watch: {
    selectValue() {
      console.log(this.selectValue)
    }
  }
})
```
