### ISSUE TITLE
[Bug Report] Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by Laurence88** [vuetifyjs/vuetify#6550]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.13.6

### Steps to reproduce
click to have visibility_off (for Password)
click Submit btn

### Expected Behavior
print password in console

### Actual Behavior
print password in console but with an error message:
Unchecked runtime.lastError: The message port closed before a response was received.

### Reproduction Link
<a href="https://codepen.io/l-achard/pen/mvoQBo?editors=1111" target="_blank">https://codepen.io/l-achard/pen/mvoQBo?editors=1111</a>

### Other comments
Used to work in previous versions, but I can't remember the exact version number.
Not working in 1.5.1

**Comment by KaelWD** [comment]
Cannot reproduce, sounds like you might have a browser extension that's playing up. Have a look where the error was actually thrown from.

**Comment by KaelWD** [comment]
Yeah that's from webextension-polyfill, not us.

**Comment by Laurence88** [comment]
Ok Thanks a lot for your quick reply!!!!!
I found the problem thanks to you:  it is the 1Password chrome extension.
(For info I have had this extension for a long time. Never had the issue before)
