### ISSUE TITLE
[Bug Report] Vuetify Data tables does not work in IE11

### ISSUE THREAD

**Issue by tft-robert** [vuetifyjs/vuetify#6551]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.5.18
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
Open https://www.vuetifyjs.com in IE11. The submenus in the top right corner are not clickable. The console prints out the error message:

SCRIPT1002: Syntax error
File: vendors~app.a95eca53053d7f411dcf.js, Line: 1388, Column 25541

The same happends if you try to open the data-tables component documentation:

https://vuetifyjs.com/en/components/data-tables

### Expected Behavior
Expected submenus on the mian page to work and that the data tables are rendered.

### Actual Behavior
SCRIPT1002: Syntax error
File: vendors~app.a95eca53053d7f411dcf.js, Line: 1388, Column 25541

**Comment by DRoet** [comment]
Can confirm that the docs are broken in IE11, however this has nothing to do with `v-data-table` since it works fine in my own project

**Comment by tft-robert** [comment]
Okay, another user created a jsbin: https://jsbin.com/bocazoqaqa/1/edit?html,js,output using v-data-table.
This is the same result I face in my project when using v-data-table in IE11.
Could be something about the setup though.

**Comment by DRoet** [comment]
I'm not sure if a CDN polyfill like the jsbin work correctly, please check [here](https://vuetifyjs.com/en/getting-started/quick-start#ie11-safari-9-support) for proper polyfilling

**Comment by DRoet** [comment]
@MajesticPotatoe this can be closed since the docs are now fixed in `IE11` and v-datatable does work correctly when polyfilling

**Comment by MajesticPotatoe** [comment]
Will Do. Thanks.
