### ISSUE TITLE
[Bug Report] Component with V-Dialog within Tabs Issue

### ISSUE THREAD

**Issue by Packtsardine87** [vuetifyjs/vuetify#6553]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.5.22
**Browsers:** All
**OS:** Windows

### Steps to reproduce
Example to reproduce: https://codesandbox.io/s/62w1n9w8nw
Click the Button "Show" on Tab 1 and there is a v-dialog showing up with the Text "Test". Click on Tab 2 or Tab 3 and the dialog is not visible. But when returning to Tab 1 it's visible. The Dialog is always opened within Tab 1, not the one that it was triggered in.

The dialog itself is part of the "MinDialog" component.

### Expected Behavior
The v-dialog should turn up within the tab that it's opened in.

### Actual Behavior
The v-dialog is showing within Tab 1.

**Comment by KaelWD** [comment]
You must have a **single** v-app at the *root* of your application.
