### ISSUE TITLE
[Bug Report] autofocus on a v-text-field keeps iOS soft keyboard popping even when v-if controlling the field changed to false

### ISSUE THREAD

**Issue by Alleyfield** [vuetifyjs/vuetify#6562]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.46
**OS:** iOS

### Steps to reproduce
1. v-text-field inside drawer that has autofocus (conditionally shown with *v-if*)
2. trigger v-if so v-text-field with autofocus can be seen
3. open iOS soft keyboard
4. trigger v-if so v-text-field with autofocus cannot be seen
5. toggle drawer - iOS softkeyboard keeps popping up

### Expected Behavior
iOS softkeyboard should not pop up after element with v-text-field with autofocus does not exist due to v-if being false

### Actual Behavior
iOS softkeyboard keeps popping - almost as-if autofocus triggers each time an update happens

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZwNbpb" target="_blank">https://codepen.io/anon/pen/ZwNbpb</a>

### Other comments
After having done the reproduction in codepen I noticed that codepen does not work on iOS iPad (at least for me). But it provides a reference implementation of what has been done.

Here's a video of what is happening
https://www.youtube.com/watch?v=7F0_jkuKrcI&feature=youtu.be
soft keyboard keeps popping up on each

**Comment by Alleyfield** [comment]
fyi implemented a hacky workaround;
Assigned a dynamic ref to the element in question and explicitly call 
        this.$refs[ref][0].blur();
when a watch notices the v-if change -- and thus iOS softkeyboard closes when the v-if changes to falsy

**Comment by johnleider** [comment]
This is resolved as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
