### ISSUE TITLE
[Feature Request] Tab Smooth Swipe Behavior

### ISSUE THREAD

**Issue by Dylan-Israel** [vuetifyjs/vuetify#6565]
### Problem to solve
Currently to swipe between tabs, you have to complete the swipe gesture, then the tab begins sliding over.  This feels a bit unnatural and native apps seem to have the behavior to start sliding gradually, then snap either forward or backward depending on how far you have gone. 

Article of example feature in a different component: 
<a href="https://medium.com/the-web-tub/improve-ux-with-swiping-tab-bar-using-onsen-ui-for-vue-4c7d0e5171f0">Article</a>

Example of Feature Implemented
<img src="https://cdn-images-1.medium.com/max/800/1*LOxwj15LmbJtyDtU0s93MQ.gif" />

### Proposed solution
Add an optional swipeBehavior prop. I would even suggest to make it the default behavior as it supports the mobile first and PWA web initiatives.

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by KaelWD** [comment]
This comes with #3262 and #6535

**Comment by AndreFvchs** [comment]
I'm currently using Flickity (https://flickity.metafizzy.co/) for this but would prefer a _native_ Vuetify solution. Any news if it will be added?

**Comment by HoLy1337** [comment]
Would be awesome if there comes a native support!
