### ISSUE TITLE
[Bug Report] Autocomplete "item" slot not clickable when VListTile included

### ISSUE THREAD

**Issue by dominik-bln** [vuetifyjs/vuetify#6566]
### Versions and Environment
**Vuetify:** 1.5.2
**Last working version:** 1.5.0
**Vue:** 2.6.6
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.12.6

### Steps to reproduce
Search something and try to click inside the popup menu.

### Expected Behavior
The clicked item is added to the selection. 

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://codepen.io/dmnk_bln/pen/NoVLPP?editors=1010" target="_blank">https://codepen.io/dmnk_bln/pen/NoVLPP?editors=1010</a>

### Other comments
Not sure if this was ever supposed to work, as the docs only show the slot with a `VListTileContent`, but we accidentally had this wrapped in a `VListTile` for month and this was working fine until the recent update. Removing the `VListTile` wrapper fixes the problem, so would be fine with us if the issue gets closed without a fix, but I just thought it might be helpful to report this as it was a breaking change for us and in case others come along the same problem.

**Comment by MajesticPotatoe** [comment]
At initial glance, seems that in 1.5.1 there were a few things that were changed on select/autocomplete. Will have to dig a little deeper.

**Comment by KaelWD** [comment]
You have to bind the listeners etc. https://codepen.io/anon/pen/omrjXY?editors=1010

Worked in 1.5.0 because of https://github.com/vuetifyjs/vuetify/issues/6376#issuecomment-460889668

**Comment by dominik-bln** [comment]
Thanks for looking into this and the explanation.

**Comment by nizantz** [comment]
This is working in v1.5.14. I upgraded to 1.523  and this functionality is broken. I have reverted to using 1.5.14.
