### ISSUE TITLE
[Bug Report] hide-details causes misalignment on v-autocomplete

### ISSUE THREAD

**Issue by joantiscar** [vuetifyjs/vuetify#6569]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109
**OS:** Linux x86_64

### Steps to reproduce
Create 2 or more of the same element (v-autocomplete, v-select...) and give one of them the "hide-details" prop.

### Expected Behavior
The three elements should be at the same height

### Actual Behavior
The element with the "hide-details" prop is misaligned vertically

### Reproduction Link
<a href="https://codepen.io/astio/pen/vbqJBa" target="_blank">https://codepen.io/astio/pen/vbqJBa</a>

**Comment by KaelWD** [comment]
hide-details is to reduce the component's height.
