### ISSUE TITLE
Feature request: Datatable components should have customizable theme colors

### ISSUE THREAD

**Issue by Sarpedion** [vuetifyjs/vuetify#657]
I've noticed that checkbox in header row (the one generated by select-all prop) and loading bar in table by default have primary theme color and as far as I can tell, there is no easy way to set some other theme color (secondary, info, accent). Would it be possible to add this feature?

**Comment by johnleider** [comment]
I told @nekosaur that this request was coming :)

**Comment by nekosaur** [comment]
Both the select-all and loading props can now also accept a String ('primary', 'secondary', 'success', 'info', 'warning', 'error') to change the color.
