### ISSUE TITLE
[Bug Report] Text field emits blur event when errorMessages change

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#6570]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.2

### Steps to reproduce
Steps to reproduce:
1) Click in the text box.
2) Click outside the text box.
3) Click inside the textbox and start typing.

### Expected Behavior
User should be able to continue typing, but a blur event is emitted after a single character is typed

### Actual Behavior
Blur event is emitted while typing

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/rPEvKY" target="_blank">https://codepen.io/everhardt/pen/rPEvKY</a>

### Other comments
Note that this is not the case if you start typing in step 1.

**Comment by KaelWD** [comment]
Blur is emitted because you v-ifed the component away.

**Comment by everhardt** [comment]
Apologies, my bad :(.
