### ISSUE TITLE
[Bug Report] Data table component - external pagination  autoupdate not working with custom-filter

### ISSUE THREAD

**Issue by Freeesia** [vuetifyjs/vuetify#6574]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
Choose some options from select

### Expected Behavior
If items set changed -> external pagination object should autoupdate

### Actual Behavior
Set of items changed, table rows redrawn, external pagination objects is old

### Reproduction Link
<a href="https://codepen.io/Freesia_p/pen/qgerXx" target="_blank">https://codepen.io/Freesia_p/pen/qgerXx</a>

### Other comments
#4455 and #3770 are similar problems

**Comment by laurengranada** [comment]
Facing this same problem, any work arounds?

**Comment by nekosaur** [comment]
This has been resolved in 2.0
