### ISSUE TITLE
[Feature Request] support prop hint and persistent-hint for v-radio and v-checkbox

### ISSUE THREAD

**Issue by mehrancodes** [vuetifyjs/vuetify#6576]
I'm wondering why the `hint` prop shouldn't be available for v-radio and other radio-group components!

I need it to show some help message for each radio button and seems already I should do that in a dirty way.
![screenshot from 2019-02-23 18-26-26](https://user-images.githubusercontent.com/7046255/53287999-8fe1b000-3798-11e9-87f5-cc7491d78ca3.png)

**Comment by spatialfusion** [comment]
Yes this would be a great feature. 

@mehrunrasoli what was the dirty way you found for this?

**Comment by simeon9696** [comment]
@mehrancodes ik it's been a long time but can you share how you did it?

**Comment by johnleider** [comment]
This is already possible in v2 and in v3.

```html
<v-radio label="One-time">
        <template #label>
          <div>
            One-time1

            <div class="text-caption">Patrons get this item once, after they pay</div>
          </div>
        </template>
      </v-radio>
```
If you have any questions please reach out to us in Discord, https://community.vuetifyjs.com/
