### ISSUE TITLE
[Feature Request] [Docs] Removing v-card-media from the docs

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#6579]
### Problem to solve
Avoiding misleading information.
The documentation of the card component contains some instances of v-card-media in it. Where as the examples now use v-img. 

### Proposed solution
To avoid misunderstanding, the documentation should be updated to reflect the latest state and the deprecation of v-card-media. Furthermore, v-card-media is still visible in the API explorer (PROPS), without any sign stating the deprecation; there should be a warning alert in the API explorer stating the deprecation if it is not completely removed.

![v-card-media](https://user-images.githubusercontent.com/11488356/53288919-d8509c00-379f-11e9-83e7-f265b409ff2d.png)

**Comment by MajesticPotatoe** [comment]
Will have to just post this above the api section for now. api generator doesn't have a clean way (aside of removing it completely) to deprecate a whole sub-component (or inject an alert in the fashion above). Ill look into including something like this with api regen rewrite.

**Comment by ibrahimBeladi** [comment]
Also, 'v-card-media' is mentioned twice, once in the usage, and the other in the 'Horizontal cards' example.
