### ISSUE TITLE
Menu opens at wrong position after update

### ISSUE THREAD

**Issue by smorales** [vuetifyjs/vuetify#658]
Hi, I have a button inside the toolbar which opens a menu. But with the latest Vuetify version (0.12.4), the menu opens now at the wrong place. Previously it worked perfectly. 

Menu button:
![screen shot 2017-06-01 at 11 23 24](https://cloud.githubusercontent.com/assets/1657692/26684328/0759c916-46bd-11e7-9fc6-a3064d4f440c.png)

Version 0.12.4 (Wrong behaviour):
![screen shot 2017-06-01 at 11 03 05](https://cloud.githubusercontent.com/assets/1657692/26683691/0e6ce9ce-46bb-11e7-9b2d-27204d60fb50.png)

Version 0.12.2 (Working correctly):
![screen shot 2017-06-01 at 11 07 01](https://cloud.githubusercontent.com/assets/1657692/26683679/04f82890-46bb-11e7-8cfd-5e3e3033df60.png)

### Steps to reproduce
See https://codepen.io/solano72/pen/yXBaPK

### Versions
Vuetify: 0.12.4

### What is expected ?
Menu should open at the correct position.

### What is actually happening ?
Menu opens outside the viewport.

### Reproduction Link
https://codepen.io/solano72/pen/yXBaPK

**Comment by dohomi** [comment]
@smorales does 0.12.5 fix your issue?

**Comment by smorales** [comment]
Wow, this was really fast! Yes this fixed my issue. 

Thank you very much!
