### ISSUE TITLE
[Bug Report] NOT work with Alpha 5

### ISSUE THREAD

**Issue by leapit** [vuetifyjs/vuetify#6581]
Vuetify: 2.0.0-alpha.5
Vue: 2.6.6
Browsers: Safari 12.0.3, Google Chrome, Mozilla Firefox
OS: Mac OS 10.13.6

Steps to reproduce

According to guide https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0-alpha.5,step by step create a vue project, and use alpha5 way
```
import Vue from 'vue'
import App from './App.vue'

Vue.config.productionTip = false
import Vuetify from 'vuetify'
Vue.use(Vuetify)
new Vue({
  vuetify: new Vuetify({}),
  render: h => h(App)
}).$mount('#app')
```
not work,consle error
```
main.js?56d7:11 Uncaught TypeError: vuetify__WEBPACK_IMPORTED_MODULE_6___default.a is not a constructor
    at eval (main.js?56d7:11)
    at Module../src/main.js (app.js:2149)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at Object.0 (app.js:2162)
    at __webpack_require__ (app.js:724)
    at app.js:791
    at app.js:794
```
Expected Behavior

expect run normal

Actual Behavior

got error as above

Reproduction Link

[https://codepen.io/anon/pen/WPVXBm](https://codepen.io/anon/pen/WPVXBm)

**Comment by jacekkarczmarczyk** [comment]
This is still an early work in progress. We are not accepting bug reports for v2 yet until the foundation work is complete.

**Comment by ibrahimBeladi** [comment]
@leapit, the alpha version is for the ones who are interesting in building Vuetify and willing to contribute via coding. Vuetify V2 alpha is buggy right not because it is not ready for public use, and still under heavy development. And hence the bug reports are not accepted at this stage.

You have to wait for the beta release in order to really use Vuetify V2.

**Comment by gsharp021** [comment]
This is still an issue in 2.0.0.beta.0.  Do I have to wait for it to be fixed or is there a workaround?

**Comment by jacekkarczmarczyk** [comment]
We need a runnable reproduction for bugs, please use a codesandbox or create a github repo (and create a new issue with link to your reproduction)
