### ISSUE TITLE
[Bug Report] v-calendar doesn't switch between dates

### ISSUE THREAD

**Issue by eduardoalbertorg** [vuetifyjs/vuetify#6586]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
Click in the next or prev buttons

### Expected Behavior
Calendar should change the month and display the change

### Actual Behavior
It doesn't do the change

### Reproduction Link
<a href="https://codepen.io/eduardoarg/pen/jJNEJW" target="_blank">https://codepen.io/eduardoarg/pen/jJNEJW</a>

### Other comments
Spoke with nekosaur in discord and he said:
"Seems like it stops working when you don't have a v-model set. You could create a bug report on github"

The code is a copy of the reference code in vuetify website.

**Comment by ncbinh98** [comment]
you should have v-model="start" in `<v-calendar v-model="start">`

`data(){
 return { start: "2019-25-02"}
}`

**Comment by ClickerMonkey** [comment]
That will fix the issue. I'll see if I can get next/prev working if someone doesn't pass in v-model/value/start.

**Comment by eduardoalbertorg** [comment]
I got it to work by changing these:

`<v-calendar
                            ref="calendar"
                            v-model="start"
                            :type="type"
                            :end="end"
                            color="primary"
                    ></v-calendar>`

`new Vue({
    el: '#incidence_calendar',
    type: 'month',
    data: {
      type: 'month',
      start: '2019-01-01',
      end: '2019-01-06',
    }
});`
