### ISSUE TITLE
[Feature Request] Treeview component: Allow indeterminate as part of selected values in v-model

### ISSUE THREAD

**Issue by Juslwk** [vuetifyjs/vuetify#6590]
### Problem to solve
It would be great to be able to have the indeterminate as part of the selected values in v-model.
As long as the parent has part of its children being selected, if this function is set to true, then the parent will be in the list of selected values.
Thank you

### Proposed solution
if checkbox status is indeterminate, add to list of selected values

**Comment by websitevirtuoso** [comment]
Yes I think it good idea. When I create v-treeview my parent has id with negave int. and when send data to server I make filter to get only positives. To avoid it need additional prop

**Comment by KosratDAhmad** [comment]
Is there any solution to get indeterminate values from the treeview ??
