### ISSUE TITLE
[Bug Report] Scrollbar hidden in scrollable dialog due to box-shadow

### ISSUE THREAD

**Issue by XavierTalpe** [vuetifyjs/vuetify#6592]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
Open the Vuetify scrollable dialog example in Chrome on Mac OSX (the bug doesn't happen on Linux): https://vuetifyjs.com/en/components/dialogs#scrollable

Use the mouse wheel to scroll up/down in the list. Notice the scrollbar is missing (not shown).

### Expected Behavior
Scrollbar is visible (as is the case in Chrome on Linux).

### Actual Behavior
Scrollbar is hidden (only on Mac OSX + Chrome)

### Reproduction Link
<a href="https://codepen.io/anon/pen/NJKzMb?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/NJKzMb?&editable=true&editors=101</a>

### Other comments
See video at https://drive.google.com/open?id=12wkzuOLBGr1Xqp1nevCX-Z-_3ixTKgYo for reproducing it as well as how it is "fixed" by disabling the box-shadow property on the v-dialog CSS class.

I assume the underlying cause is this bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=581136 . Given that this ticket is open for several years, I doubt it's going to be fixed anytime soon. For our project we are considering to disable the box-shadow for the v-dialog CSS class.

**Comment by KaelWD** [comment]
That's hilarious. 
I don't know if we can fix this, removing shadows for everyone is not a good solution. 

```js
if (isSafari) {
  die()
}
```

**Comment by xmwgp8** [comment]
How to disable vuetify dialog's 'box-shadow' ?

**Comment by XavierTalpe** [comment]
You can manually override the box shadow property of the `v-dialog` CSS class.

**Comment by KaelWD** [comment]
This was fixed in chrome 83 apparently.
