### ISSUE TITLE
[Bug Report] https://github.com/vuetifyjs/vuetify/issues/new

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [vuetifyjs/vuetify#6593]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Select any value from the dropdown
2. click outside of the dropdown
3. selected value will be cleared and replace with placeholder text.

### Expected Behavior
Selected value should not clear off, on outside click in IE. 

### Actual Behavior
Selected value should not clear off, on outside click in IE. 

### Reproduction Link
<a href="https://codepen.io/grandhisubrahmanyam35/pen/jJNYWR" target="_blank">https://codepen.io/grandhisubrahmanyam35/pen/jJNYWR</a>

**Comment by MajesticPotatoe** [comment]
What version of IE? also, please fix issue title.

**Comment by DRoet** [comment]
@MajesticPotatoe Pretty sure this is a duplicate of <https://github.com/vuetifyjs/vuetify/issues/5225>
