### ISSUE TITLE
[Feature Request] Support for multiline options in select/combobox

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#6598]
### Problem to solve
Selects with options longer that the available space get ellipsed, making it hard or impossible in some cases to know what are the options.
The workaround I found is playing with some vuetify classes, in particular, removing the fixed height  from `.v-list__tile`, but I think this is brittle since those classes might change

### Proposed solution
Allow for multiline options. At least changing the fixed height in .v-list__tile to a `min-height` so that we can use the `item` slot and make it adjust our needs

**Comment by KaelWD** [comment]
> At least changing the fixed height in .v-list__tile to a min-height so that we can use the item slot and make it adjust our needs

Can be done pretty easily in v3:

https://play.vuetifyjs.com/#eNqNVFFr2zAQ/itCG6SFyB7dxsBko6VsfRl92cModaFyfG3UyLKQ5CQj+L/vJDmJHZO2eYl0333ffTqddb+lV1onqwZoRmcOKi25gx+5ImS2YlzrsMwdbua1clwoMCHUBS1ImLsY8L8Vq+oS5Pecdgg9YNlCKIfI48dtBBPrsFg7JfsALwrTPg5IAk1ZZIX/PuIDzAknwVfzSiN0xWXjUS/bByUvgsc/I48ajBXWgXLMuz0ABlxjFKuLl8F5rVDPEpjEvvQ8V6Aapk2tvfEtqfjmryjdIiOfSHuo1vUxdHLXefLBGw8sv5iSoOJZ++yu8xJtMp+DPS+EKpETcnNKsl1XGlXCE1orB/SRQuwimUtuvWEHG8fWhmtkbaOPJGa07Swd8QbKA7yHzNLBbO1S47V3IR8YDpmPxBkc8Gd2boSONNjo2jiC5+SNdGQbpUruODk7321313fY482F0hnZkjA7GZn8krURJZ9MiZ8XH/g9Ie10OFM2I/f9A4/oZJIY0MDd2cXX85NSfeIN1OZZ9OreXJ1OvoXCcLvsZd/+PJ19zaV4qo3qq1+/qr4md7VZ9tTvhtkP+3UbFxHEzSztroVOKX4PS5u82FrhsxKantO5xdncdy+nC+e0zdJ0XirMxEdDrEyiwKVKVyk+SE48/bv8nFwkF2mJE7ULMfx4bRLEvNJDrlosKCo/Bqzi+qhqBELl7vJzikp+/4aFS0xLTaOcqICVdRW8fPkWzfTiCdiKFaZeWzCoktOuQ6GOd/yOWm8dF0uMpFOstwLDDOBXbgAfuPcd6Yg2ONYRNjpad9Utbac08rD3wTR9+A9n1/XX

**Comment by johnleider** [comment]
Closing as this is configurable in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
