### ISSUE TITLE
[Bug Report] preserve listeners on v-checkbox, v-radio icons

### ISSUE THREAD

**Issue by shaikemarc** [vuetifyjs/vuetify#6599]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109, Google Chrome
**OS:** Mac OS 10.13.6, Linux

### Steps to reproduce
Configure svg icon components for checkbox/radio on/off.

### Expected Behavior
There is an indication that the svg is clickable.
The icon is clickable.

### Actual Behavior
The icon is not clickable and no "clickable" indication appears on the svg icon.
The only clickable part is the label div.

### Reproduction Link
<a href="https://github.com/shaikemarc/testvuetify" target="_blank">https://github.com/shaikemarc/testvuetify</a>

### Other comments
This seems to be related to an issue i opened several weeks ago: Not clickable icon on "clearable" v-autocomplete. see here: https://github.com/vuetifyjs/vuetify/issues/6228.
This one was fixed here: https://github.com/vuetifyjs/vuetify/pull/6507

**Comment by KaelWD** [comment]
https://github.com/robcresswell/vue-material-design-icons/issues/49
