### ISSUE TITLE
Add action button in datatables

### ISSUE THREAD

**Issue by blogui91** [vuetifyjs/vuetify#660]
### Steps to reproduce
     Just make a click in the button 'Make fiscal address
### Versions

        vuetify 0.12.2
        vuex 2.3.1
        vue 2.3.3
        Windows 10
       Chrome 58
### What is expected ?
     I have to catch the data row when the button 'Make fiscal address'  is clicked

### What is actually happening ?
     I does not seem to make anything else, i tried adding an emit and  event handler in the component, another adding a $on in parent component, nothing seems to work :(
### Reproduction Link
https://codepen.io/blogui91/pen/vZBXVL?editors=1010

**Comment by johnleider** [comment]
Vue 2 requires the use of ```.native``` as a modifier to v-on (@) events on custom components.
https://codepen.io/johnjleider/pen/awoGXx

**Comment by blogui91** [comment]
Ohhh that's right!
My bad!
Thanks a lot!!
