### ISSUE TITLE
[Bug Report] CodePen for Expansion Lists doesn't work any more.

### ISSUE THREAD

**Issue by ivanvorona** [vuetifyjs/vuetify#6611]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.5
**Last working version:** 2.0.0-alpha.5
**Vue:** 2.6.7
**Browsers:** Chrome 74.0.3710.0
**OS:** Windows 7

### Steps to reproduce
open link above - this is standard link from Expansion list on vuetify website:
https://next.vuetifyjs.com/en/components/lists

### Expected Behavior
menu

### Actual Behavior
just string

### Reproduction Link
<a href="https://codepen.io/anon/pen/rRaBXJ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/rRaBXJ?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
We are not accepting bug reports for v2 yet, especially if they're documentation related.

**Comment by ivanvorona** [comment]
@KaelWD  -it is up to you but this is official documentation and one of examples shown there stopped working 2 days ago showing weird results what will be confusing people... I am not sure about the version used for your example...
