### ISSUE TITLE
[Bug Report] Bug in binding to an array prop in v-btn

### ISSUE THREAD

**Issue by WhoaWhoa** [vuetifyjs/vuetify#6619]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Google Chrome
**OS:** Linux, Windows

### Steps to reproduce
A button with its loading property bound to an array element does not function properly.

In attached codepen, click on the left button. Then click on the right. 

### Expected Behavior
Each button should go into a loading state when clicked.

### Actual Behavior
The left button (bound to array) doesn't go into loading state. When the right button (bound to a primitive) is clicked, both go into loading state.

### Reproduction Link
<a href="https://codepen.io/anon/pen/YgPJoB?editors=1011" target="_blank">https://codepen.io/anon/pen/YgPJoB?editors=1011</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/list.html#Caveats
