### ISSUE TITLE
[Bug Report] With new slot syntax v-slot:activator keyboard events does not work

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#6621]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
Click on the chips and try to choose an menu item with keyboard arrows

### Expected Behavior
as old slot

### Actual Behavior
The keyboard doesn't work

### Reproduction Link
<a href="https://codepen.io/Buzzzzer/pen/JzoqBM" target="_blank">https://codepen.io/Buzzzzer/pen/JzoqBM</a>

### Other comments
And additionally, when using a new slot syntax, hot reload sometimes throw errors  in the console like
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot create property 'activator' on boolean 'true'"
```

**Comment by KaelWD** [comment]
Stack trace for the error?

**Comment by buzzzzer** [comment]
@KaelWD 
[localhost-1551246170048.log](https://github.com/vuetifyjs/vuetify/files/2908730/localhost-1551246170048.log)

**Comment by KaelWD** [comment]
You may have an old version of vue-template-compiler somehow: https://github.com/vuejs/vue/commit/7ec4627902020cccd7b3f4fbc63e1b0d6b9798cd

Either that or some other similar bug in vue.
