### ISSUE TITLE
[Feature Request] Add events for focus state to `VAutocomplete` (and other inputs)

### ISSUE THREAD

**Issue by kestred** [vuetifyjs/vuetify#6632]
### Problem to solve
Generally, a parent component may like to have data-reactive behavior based on whether an input is focused.   Using `$refs` in Vue to access this data is a last resort because the computed properties and data of Vuetify components isn't part of the documented public interface and because using `$refs` circumvents the reactivity system (for example when using `$refs`) in a `computed` value.

### Proposed solution
The inputs (such as `VAutocomplete`) could expose an event such as `@update:focused` or `@update:isFocused` that can be used with `.sync` to bind to reactive data (or minimally documented/officially-supported `@blur` and `@focus` events).

**Comment by tyteen4a03** [comment]
This is needed for working with server-side pagination.

**Comment by nekosaur** [comment]
All input components should have blur and active events.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
