### ISSUE TITLE
[Bug Report] V-Img doesn't re-show lazy-src when src changes.

### ISSUE THREAD

**Issue by danfleck** [vuetifyjs/vuetify#6633]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.3

### Steps to reproduce
When dynamically changing the src of a v-img it seems like the lazy-src is not rendered while the new img src is loading. 

### Expected Behavior
When the v-img :src value is changed, the lazy-src shows until the new img is loaded.

### Actual Behavior
When the v-img :src value is changed, the new img is loaded and (if it is slow) you see the img drawn as the network loads it (top to bottom). 

### Reproduction Link
<a href="https://codepen.io/DanDC/pen/gEpZBG" target="_blank">https://codepen.io/DanDC/pen/gEpZBG</a>

### Other comments

This is more clear on a local site where the images are remote and you slow down network speeds. On the code pen above I don't think I see a flash of the lazy-src but it is hard to be certain with a fast network. When I test on my local machine and degrade the network it is much more obvious.

If there is a better way to verify if the lazy-src is shown or not let me know and I can edit the codepen.

**Comment by danfleck** [comment]
I believe this is the same as issue #5755 which was closed due to no one adding a reproduction link.

**Comment by joelpro2** [comment]
i have a codepen for that with buttons that trigger each step
[codepen](https://codepen.io/joel_rodrigues/pen/MWWPwXa?editors=1010)
Press set/reset avatar -> lazy loading must update img and src must wait for upload to be completed
Press finish uploading and the lazy shall vanish and src must render the new image ready

**Comment by DispatchCommit** [comment]
I figured out a workaround for now - I just set a `key` on my `v-img` component and just make sure to modify *both* the key and `src` properties. If you are using a new URL, you can just set both the `key` and `src` equal to the same value and it works great.

**Comment by DispatchCommit** [comment]
nice.
