### ISSUE TITLE
[Bug Report] v-icon with Font Awesome SVG doesn't render icons

### ISSUE THREAD

**Issue by servernoj** [vuetifyjs/vuetify#6634]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.3

### Steps to reproduce
The reproduction link (GitHub repo @ https://github.com/servernoj/vuetify-icons-demo) represents a minimalistic Vuetify project that uses **baseline** template from https://vuetifyjs.com/en/framework/pre-made-layouts as the basis. 

One entry point record, i.e. `src/plugins/vuetify.js` is configured to use **Font Awesome SVG** font as described in https://vuetifyjs.com/en/framework/icons#install-font-awesome-svg-icons 

1. Edit `src/views/boo.vue` file and confirm that either `<v-icon large v-text="'fas fa-edit'" />` or `<v-icon>fas fa-edit</v-icon>` is used
2. Run serving script `yarn serve` and open browser at `localhost:8080`

### Expected Behavior
Font awesome solid 'Edit' icon to be rendered in the middle of the screen

### Actual Behavior
Nothing is rendered

### Reproduction Link
<a href="https://github.com/servernoj/vuetify-icons-demo" target="_blank">https://github.com/servernoj/vuetify-icons-demo</a>

### Other comments
If instead of using one of the above mentioned ways of instantiating Font Awesome SVG icons I use `<font-awesome-icon size="2x" :icon="['fas', 'edit']" />` (which is currently commented) -- correct icon would be rendered. 

The non-SVG Font Awesome icons work with `v-icon` component as expected.

**Comment by KaelWD** [comment]
`fas fa-edit` is for icon fonts, not svg. You have to initialise it like this: https://vuetifyjs.com/en/framework/icons#custom-font-awesome-pro-icons and then use `$vuetify.icons.edit`
