### ISSUE TITLE
[Bug Report] Regression caused by #6431 - search input gets nulled immediately when using an `item-text` function + ajax loading

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#6635]
### Versions and Environment
**Vuetify:** 1.5.3
**Last working version:** 1.5.0
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 7

### Steps to reproduce
Create a v-autocomplete that uses a function for `:item-text`. Bind `:search-input.sync`, watch the bound property, and use that to perform an AJAX load of data.

Then, type some characters into the search input.

### Expected Behavior
Search works as normal

### Actual Behavior
No input appears. The watcher for the search property gets a single character that was typed in, and then immediately afterwards, gets set to null.

### Reproduction Link
<a href="https://codepen.io/anon/pen/droBmr" target="_blank">https://codepen.io/anon/pen/droBmr</a>

### Other comments
Caused by https://github.com/vuetifyjs/vuetify/pull/6431

The watcher on `itemText` is causing the search input to be reset.

**Comment by Kovalchuk91** [comment]
`<template>
    <v-autocomplete
            v-model="selectedVendors"
            :items="Array.from(vendors)"
            :loading="isLoading"
            :search-input.sync="search"
            label="Vendors"
            item-text="title"
            clearable
            multiple
            chips
            small-chips
            hide-no-data
            dense
            deletable-chips
            return-object
    />
</template>

<script>
  import { getVendors } from '@/shared/api';

  export default {
    name: 'VendorsFilter',

    props: {
      value: {
        type: Array,
        required: true
      }
    },

    data () {
      return {
        isLoading: true,
        search: '',
        vendors: new Set(),
        selectedVendors: []
      };
    },

    watch: {
      search: {
        immediate: true,
        handler: 'loadItems'
      },

      /**
       * В фильтры возвращаем только идентификаторы
       * @param vendors
       */
      selectedVendors(vendors) {
        this.$emit('input', vendors.map(vendor => vendor.identifier));
      }
    },

    methods: {
      loadItems () {
        this.isLoading = true;

        /**
         * Получаем вендоры
         */
        getVendors({ page: 1, rowsPerPage: 10, search: this.search })
          .then(response => {
            /**
             * Баг в библиотеке - если в selected есть значение, которого нет в списке items -
             * оно не отображается.
             * Поэтому склеиваем список выбранных в поле со списком полученным по апи.
             * Используем Set для того, чтобы значения не повторялись
             */

            this.vendors = new Set(this.selectedVendors);
            response.data.items.map(vendor => this.vendors.add(vendor));
          })
          .finally(() => this.isLoading = false);
      }
    }
  };
</script>`

**Comment by Kovalchuk91** [comment]
I've faced the same bug recently, was able to deal with it by merging array with selected values with the list that comes from API into Set (to avoid duplicates). Maybe it can help someone before it gets fixed:


<template>
    <v-autocomplete
            v-model="selectedVendors"
            :items="Array.from(vendors)"
            :loading="isLoading"
            :search-input.sync="search"
            label="Vendors"
            item-text="title"
            clearable
            multiple
            chips
            deletable-chips
            return-object
    />
</template>

<script>
  import { getVendors } from '@/shared/api';

  export default {
    name: 'VendorsFilter',

    data () {
      return {
        isLoading: true,
        search: '',
        vendors: new Set(),
        selectedVendors: []
      };
    },

    watch: {
      search: 'handleLoad'
    },

    methods: {
      handleLoad () {
        this.isLoading = true;

        getVendors({ search: this.search })
          .then(response => {
            this.vendors = new Set(this.selectedVendors);
            response.data.items.map(vendor => this.vendors.add(vendor));
          })
          .finally(() => this.isLoading = false);
      }
    }
  };
</script>

**Comment by Kovalchuk91** [comment]
I've faced the same bug recently, was able to deal with it by merging array with selected values with the list that comes from API into Set (to avoid duplicates). Maybe it can help someone before it gets fixed:

```
<template>
    <v-autocomplete
            v-model="selectedItems"
            :items="Array.from(items)"
            :search-input.sync="search"
            label="Items"
            item-text="title"
            clearable
            multiple
    />
</template>

methods: {
      handleSearch () {
        getItems({ page: 1, rowsPerPage: 10, search: this.search })
          .then(response => {
            this.items = new Set(this.selectedItems);
            response.data.items.map(item => this.items.add(item));
          });
      }
    }
```

**Comment by meteorlxy** [comment]
Same problem here. I have to roll back to 1.5.0 now.

**Comment by johnleider** [comment]
This really is just a product of how Vue binds inline functions. This can also causes anomalies when binding the **items** prop inline. The recommended way to handle this is by creating a function for **item-text* and bind that.

https://codepen.io/johnjleider/pen/NWKXNmg
