### ISSUE TITLE
Vuetify Disabling Dates

### ISSUE THREAD

**Issue by princeivankent** [vuetifyjs/vuetify#6637]
Hi Im using **vuetify** datepicker, is there any way to **disable dates** listed on an array?

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
