### ISSUE TITLE
[Bug Report] No speed dial animation with new Vue slot syntax when buttons are wrapped by tooltip

### ISSUE THREAD

**Issue by silvioiannone** [vuetifyjs/vuetify#6640]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
Click on the speed dial button on the bottom right.

### Expected Behavior
The speed dial buttons should appear with an animation.

### Actual Behavior
The speed dial buttons appear suddenly without animation.

### Reproduction Link
<a href="https://codepen.io/anon/pen/WmQZEP" target="_blank">https://codepen.io/anon/pen/WmQZEP</a>

### Other comments
The functionality worked before with the now deprecated Vue scoped slot syntax but not anymore.

**Comment by stygmate** [comment]
+1

**Comment by stygmate** [comment]
+1

**Comment by johnleider** [comment]
This is working as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
