### ISSUE TITLE
[Bug Report] Update of list not working correctly in combination of v-hover due to new vue scope

### ISSUE THREAD

**Issue by qnp** [vuetifyjs/vuetify#6643]
### Versions and Environment
**Vuetify:** 1.5.4
**Last working version:** 1.5.4
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.1

### Steps to reproduce
Wrap `v-list-tile` with `v-hover`:
```
...
<v-hover v-for="(item, i) in items" :key="'item' + i">
    <v-list-tile
        :key="'issue' + i"
        slot-scope="scope"
        :class="scope.hover ? 'elevation-4 blue lighten-4' : 'elevation-1'"
    >
...
data() {
   return {
      items: [ ... ]
   },
},
```
Then remove an item from `items` and see what happens. See reproduction link.

### Expected Behavior
This worked perfectly before I upgraded to vue 2.6.7:
Removing an item from `items` removed the correct one in the list.

### Actual Behavior
When you remove an item from `items`, you effectively have one less item in the list by all the data is not refreshed properly as if it was the last item which have been removed.

### Reproduction Link
<a href="https://codesandbox.io/s/r78l4lnk5n" target="_blank">https://codesandbox.io/s/r78l4lnk5n</a>

### Other comments
It seems to be a problem with new vue slots and slot-scope

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/rROQJz?editors=1010

**Comment by qnp** [comment]
@KaelWD My issue was pointing out the fact that, in combination with a *vuetify* `v-hover` component, the `v-list` does not seem to be properly updated.

(If you remove the dependency of the child components in `v-hover` scope, it is updated as desired. See this link: https://codesandbox.io/s/o9118rmkk9)

I may have been unclear, but, I am addressing here a bug in the usage of *vuetify*. Hence, I did not expect to receive a _raw vue_ code dealing with slot-scopes as the only answer. I am using vuetify extensively in my whole app and the benefit of it is to dispense with the need of creating UI components from scratch.

Could you at least provide me with a comment on why you do think that this issue should be closed, ensuring that you acknowledged what bug I am pointing out ?

Regards,

**Comment by qnp** [comment]
Thanks @KaelWD for creating a vue issue and linking to it.
