### ISSUE TITLE
[Bug Report] v-textarea container resize

### ISSUE THREAD

**Issue by wkornilow** [vuetifyjs/vuetify#6649]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.7
**Browsers:** Chromium 71.0.3578.98
**OS:** Ubuntu undefined

### Steps to reproduce
1. Add v-textarea component
2. Set height

### Expected Behavior
On textarea resize outer container should be also resized.

### Actual Behavior
Now only textarea resized, outer container not.

### Reproduction Link
<a href="https://codepen.io/wkornilow/pen/gEPoYY" target="_blank">https://codepen.io/wkornilow/pen/gEPoYY</a>

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/XGXVOO
