### ISSUE TITLE
[Bug Report] Inconsistent collapse animation in navigation drawer with group lists

### ISSUE THREAD

**Issue by breyvilas** [vuetifyjs/vuetify#6652]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.5.16
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
1. Have a navigation drawer with grouped and non-grouped items, all of them with icons.
2. Activate mini-variant

### Expected Behavior
The group activator tiles do the same animation as the simple tiles (text disappearing from the right with static icon)

### Actual Behavior
The group activator icon jumps to the right and then animates to the left.

### Reproduction Link
<a href="https://codepen.io/anon/pen/aMdPJa" target="_blank">https://codepen.io/anon/pen/aMdPJa</a>

### Other comments
This is probably because we're forced to use `:prepend-icon` on group headers, because if we use a regular icon on the activator template it disappears on collapse.

**Comment by johnleider** [comment]
I'm not seeing the icon jump. Could you take a small gif showing the issue?

**Comment by breyvilas** [comment]
Sure, here's a capture of the above codepen.

![](https://media.giphy.com/media/kG2vM0ks7c1JE5H2T1/giphy.gif)

You can see the User icon jumps to the right and then moves to the left with the animation, while the Home icon stays put.

**Comment by blalan05** [comment]
I see the same animation on win7 chrome 73.

**Comment by johnleider** [comment]
I've resolved the sub groups showing up as this is not intended. As far as the icons snapping into position—We have to do this in order to ensure proper styling for custom width **mini-variant** on the drawer.

**Comment by johnleider** [comment]
This has been resolved as far as I can get it. As stated above the snapping is required in order to support variable mini widths. If anyone comes up with a better solution, feel free to PR, thank you!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ChadWithCalDigit** [comment]
I was able to prevent the animation from traveling right by adding the following CSS:
`.v-navigation-drawer--mini-variant .v-list-item {
  -webkit-box-pack: left;
  -ms-flex-pack: left;
  justify-content: left;
}`

**Comment by ChadWithCalDigit** [comment]
I was able to prevent the animation from traveling right by adding the following:
```
.v-navigation-drawer--mini-variant .v-list-item {
    -webkit-box-pack: left;
    -ms-flex-pack: left;
    justify-content: left;
}
```
