### ISSUE TITLE
[Bug Report] Menu component breaks actions based on event delegation

### ISSUE THREAD

**Issue by rogal111** [vuetifyjs/vuetify#6654]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.0

### Steps to reproduce
Please check reproduction link below

### Expected Behavior
`v-menu` component shouldn't stop click event propagation from its children elements OR it should be configurable

### Actual Behavior
`v-menu` component stops unconditionally click event propagation from its children elements.

### Reproduction Link
<a href="https://codepen.io/rogal111/pen/gEPyQM" target="_blank">https://codepen.io/rogal111/pen/gEPyQM</a>

### Other comments
`e.stopPropagation()` is called unconditionally on all click events triggered on menu component. 

https://github.com/vuetifyjs/vuetify/blob/67b73b993c0a33a72841b48241d1ec5801921eb9/packages/vuetify/src/components/VMenu/mixins/menu-generators.js#L80-L86

It breaks scripts that use event delegation pattern: https://gomakethings.com/why-event-delegation-is-a-better-way-to-listen-for-events-in-vanilla-js/.
For example rails ujs uses it: https://github.com/rails/rails/tree/master/actionview/app/assets/javascripts

Here is example: https://codepen.io/rogal111/pen/gEPyQM

**Comment by KaelWD** [comment]
This was added in f1541583abd6a6de945daae3c64a26f6ace5775d and moved in 5be00505e96a14c5289a7067a259958fd9027ce5, might be safe to remove now.

**Comment by johnleider** [comment]
Was originally added in https://github.com/vuetifyjs/vuetify/pull/417 to fix a bug that is no longer relevant.
