### ISSUE TITLE
[Bug Report] Hide/Show password icons in the examples should be switched

### ISSUE THREAD

**Issue by osheikh** [vuetifyjs/vuetify#6655]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
Open vuetify text-field examples and copy the password input code.

### Expected Behavior
The visibility icon should be `visibility_off` (a crossed out eye) when the password is masked and `visibility` (a regular eye) when the password is visible.

### Actual Behavior
The icons are the other way around

### Reproduction Link
<a href="https://codepen.io/anon/pen/vPGYaV?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/vPGYaV?&editable=true&editors=101</a>

### Other comments
This is how its done on most websites such as Google's and Window's login pages. Having them in the current way might "surprise" developers who are looking to quickly copy functionality.

What do you guys think? I can send a PR for this if needed.

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/53691714-63d8b700-3db6-11e9-8b54-31b057798f27.png)

Agree, feel free to PR
