### ISSUE TITLE
[Feature Request] FAB Button loading/progress property

### ISSUE THREAD

**Issue by Pazza** [vuetifyjs/vuetify#6664]
### Problem to solve
Add determinate and indeterminate progress to FAB button. Uses are loading indicator to a FAB. Also can be used as a progress or cool-down indicator.

### Proposed solution
![](https://github.com/JorgeCastilloPrz/FABProgressCircle/raw/master/art/fabprogresscircle2.gif)

Shouldn't be limited to v-speed-dial but all v-btns with fab property. Or an equivalent for rectangular and rounded buttons.

**Comment by johnleider** [comment]
The best way to do this now is by using a `v-progress-linear` wrapping a `v-fab` or `v-btn`. 

https://play.vuetifyjs.com/#eNptj02OwjAMRq9iRSOxmU42AwtUkDgHZRGCiywlqeWklQBxd0zL34KNFSvvs5+3F5PF2w3z39CjWZq6YOTgCq6bBFAPlWMen9ocaAAfXM6rxkRX/QNraczje6RZuqNgzpUn8X1wApnOqPx80RigdMCCEik9F7yCrdsD+S4p+qMmhdqTBux7tv0y/Clm1WzyVWoSru3HIdpmL8QFMpZ+uocid1LgAoItXKGVLsJMN8/u2YlWzlx/Ux/CWHY309pivg==

**Comment by Pazza** [comment]
Looks great thank you. 🙏
