### ISSUE TITLE
[Bug Report] events calendar monthly overflows incorrectly when there are multiple events

### ISSUE THREAD

**Issue by ushau97** [vuetifyjs/vuetify#6665]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Firefox 65.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera
**OS:** Fedora undefined, Windows, Mac OSX, Linux

### Steps to reproduce
Add more than 2 events to a single day.

### Expected Behavior
Overflows correctly and all events in day can be seen as in other calendars.

### Actual Behavior
Third event for day overflows incorrectly and events after third one cannot be seen.

### Reproduction Link
<a href="https://codepen.io/anon/pen/NJrveR?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/NJrveR?&editable=true&editors=111</a>

**Comment by deanmikan** [comment]
Can confirm. Overflows the specified sheet height and flows outside the card. Whats the best approach to fix this? I was gonna specify a kind of ellipsis to show more events on certain day, but this should be inbuilt functionality.

![image](https://user-images.githubusercontent.com/28838199/61352310-642ea600-a8b0-11e9-81a1-3149b9d9da67.png)

**Comment by ClickerMonkey** [comment]
@deanmikan @ushau97 To take advantage of the new events props you'll have to use Vuetify 2.0+

Otherwise you'll have to implement your own event overflow logic in the day slot.
