### ISSUE TITLE
[Bug Report] Breakpoints object deprecation not documented

### ISSUE THREAD

**Issue by chip7pt** [vuetifyjs/vuetify#6666]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.6
**Last working version:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
- Follow Vuetify quickstart instructions.
- Try to use the breakpoints object as explained in https://next.vuetifyjs.com/en/framework/breakpoints#breakpoints

### Expected Behavior
Expected to have access to an object with a list of breakpoints and respective boolean status

### Actual Behavior
Undefined object

### Reproduction Link
<a href="https://codepen.io/ricardo-lobo/pen/ZPOmNQ" target="_blank">https://codepen.io/ricardo-lobo/pen/ZPOmNQ</a>

**Comment by nekosaur** [comment]
The alpha is still an early work in progress. We are not accepting bug reports for v2 yet until the foundation work is complete.
