### ISSUE TITLE
[Bug Report] Using vue-router with v-tabs

### ISSUE THREAD

**Issue by Rolanddoda** [vuetifyjs/vuetify#6667]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Opera 58.0.3135.79
**OS:** Windows 10

### Steps to reproduce
Click the "Go to Tabs" and later try to switch the tabs.

### Expected Behavior
When clicking the tabs should load the corresponding component. Or without clicking them should load the first tab's corresponding component.

### Actual Behavior
I am getting `Cannot read property '_c' of undefined`

### Reproduction Link
<a href="https://codesandbox.io/s/x3qr06zjzz" target="_blank">https://codesandbox.io/s/x3qr06zjzz</a>

### Other comments
I have google it a lot and use discord for help but I can't get the tabs working with vue-router.

**Comment by Codefa** [comment]
@Rolanddoda  Try my Project on Codesandbox check the routes are changing in the browser address section also it is swipe enabled 
[https://codesandbox.io/s/6ylmnn5m0z](url)
