### ISSUE TITLE
[Bug Report] Vertical position of autocomplete suggestions is not updated with async search

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#6668]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. Ensure that autocomplete is at the bottom of the screen, so that the menu with suggestions will appear above the autocomplete instead of below it. If there are not enough line breaks, make the rendered frame smaller or add more line breaks.
2. Type 'abc' in the autocomplete box 
3. Wait 1 second for the timeout to trigger an update of the options list 

### Expected Behavior
the single option is immediately above the autocomplete (or even below it)

### Actual Behavior
the single option is too far above the autocomplete

![Screenshot of actual behavior](https://imgur.com/f1NDTwS.png)

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/NJReBP?editors=1010" target="_blank">https://codepen.io/everhardt/pen/NJReBP?editors=1010</a>

**Comment by aiscorp** [comment]
It seems, that it still actual, I updated on 2.5.8 and this behaviour has remained.
<v-autocomplete>
 :search-input.sync="search"
@update:search-input="addressInput"
</v-autocomplete>

When you type search string it's working perfect till number of variants gets less than 5 (number items in view) and vertical position of list is not recalculated and items stays above.

May be has any suggests how to fix it?
