### ISSUE TITLE
[Feature Request] Date- & timepickers needs a "disabled-dates"

### ISSUE THREAD

**Issue by mads03dk** [vuetifyjs/vuetify#6677]
### Problem to solve
If you want to people to be able to select all other days than 7/3/2019 it would be useful

### Proposed solution
To add a disabled-dates to the datepicker as opposed to the allowed-dates. The same with the time picker. Disabled-hours, minutes and perhabs seconds

**Comment by jacekkarczmarczyk** [comment]
What's wrong with `:allowed-dates="date => date !== '2019-07-03'"?

**Comment by mads03dk** [comment]
> What's wrong with `:allowed-dates="date => date !== '2019-07-03'"?

Well... Didn't thougt about that lol. Anyways, i could do that (thanks). But it would be easier (atleast for a noob like me) if it just had that option, or if it was described that this was possible on the docs.

**Comment by jacekkarczmarczyk** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
