### ISSUE TITLE
[Bug Report] fab button loses icon

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#6681]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.5.17
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
click fab button

### Expected Behavior
icon doesn't lose state

### Actual Behavior
icon loses state and show text

### Reproduction Link
<a href="https://codepen.io/skortabeast/pen/KEaWeP?editors=1010" target="_blank">https://codepen.io/skortabeast/pen/KEaWeP?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
Can you show screenshot (or video)? I can't reproduce

**Comment by skortabeast** [comment]
![gfgf](https://user-images.githubusercontent.com/10978770/53937193-523c2b80-40a4-11e9-8475-26aa01f8fc84.gif)

**Comment by KaelWD** [comment]
I can't either. You have a lot of extensions installed, try in an incognito window.

**Comment by skortabeast** [comment]
@KaelWD strange bug of translator's extension
