### ISSUE TITLE
[Bug Report] v-slot on menu with tooltip

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#6682]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Firefox 65.0
**OS:** Windows 7, Linux

### Steps to reproduce
I'm trying to follow the online docs for v-slot. I looked at the v-menu example and the v-tooltip example. I am having trouble combining them and having them work

    <v-menu>
      <v-tooltip>
       <template v-slot:activator="{ on}">
        <v-icon v-on="on">some-image</v-icon>
       </template>
       <span>My Tooltip</span>
      </v-tooltip>
      <v-card>MyPopupMenuCode</v-card>
    </v-menu>

### Expected Behavior
I would expect the icon to have a tooltip pop up when moused over

### Actual Behavior
The icon is missing

### Reproduction Link
<a href="https://jsfiddle.net/qowae9bn/" target="_blank">https://jsfiddle.net/qowae9bn/</a>

### Other comments
If I add slot="activator" to both the v-tooltip and the v-icon it does show on the page. However, that seems the deprecated way to do things.

**Comment by DRoet** [comment]
The syntax required to make it work is a little verbose, but here:
<https://codepen.io/anon/pen/PLWXje?editors=1010>

**Comment by UglyHobbitFeet** [comment]
Wow, i wouldn't have guessed that.  Thanks!!

Is it possible to add something lime that example to the vuetify docs, as
that's not something most people would easily get.

**Comment by MajesticPotatoe** [comment]
The example @DRoet does exist in docs under menus as the subtax is what is needed to handle nested activators. The example you provide works in codepen (in terms of tooltips) and is also available in docs. Some reason youre fiddle is a little wonky in general. Additionally there is multiple syntaxes regaurding slots and you can find more info in vue docs. (Excuse my fat fingers, on mobile)

**Comment by DRoet** [comment]
@MajesticPotatoe

**Comment by UglyHobbitFeet** [comment]
The suggested solution generates an eslint-plugin-vue error due to spread
operators.  The title is 'vue/valid-v-on' and the message is "v-on'
directives require that attribute value or verb modifiers.

**Comment by KaelWD** [comment]
Well they're wrong.

**Comment by UglyHobbitFeet** [comment]
I also do not see any use of nested activators in the menu examples.  I
think an example should be added to the tooltip examples as this is a
common use-case

**Comment by UglyHobbitFeet** [comment]
lol, yeah they may be wrong. however it is still an issue that's going to come up until a bug is filed with them and  new version is updated by them :(

**Comment by lebesnec** [comment]
out of curiosity, what is the purpose of the `"{ on }"` and `v-on="on"` part ?
