### ISSUE TITLE
[Bug Report] Autocomplete selected item color no change

### ISSUE THREAD

**Issue by peterhpchen** [vuetifyjs/vuetify#6685]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
1. Open reproduction link.
1. There are two autocomplete, first is set color by css color, and second is set color by name of material color.
1. click first autocomplete, the option '1' no change color.
1. click second autocomplete, the options '1' color changed.

### Expected Behavior
autocomplete by css color should change selected color.

### Actual Behavior
autocomplete by css color no change selected color.

### Reproduction Link
<a href="https://codepen.io/peterhpchen/pen/RdKzKP?editors=1010" target="_blank">https://codepen.io/peterhpchen/pen/RdKzKP?editors=1010</a>

**Comment by johnleider** [comment]
This is a current limitation of the color system. The change to resolve this causes issues with existing functionality. Will leave open until we can re-access.

**Comment by lioneaglesolutions** [comment]
Closing as stale but also now a duplicate of https://github.com/vuetifyjs/vuetify/issues/16351
