### ISSUE TITLE
[Bug Report] Adding a zero after a "dot" decimal in a "number" textfield removes the dot

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#6688]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Chromium 72.0.3626.119
**OS:** Linux

### Steps to reproduce
Put a number in the field, put a "dot" as a decimal, and a zero right after.

### Expected Behavior
Typing "1.05" should write "1.05" in the field, just like in the standard vue + html field

### Actual Behavior
Typing "1.05" write "15"

### Reproduction Link
<a href="https://jsfiddle.net/L4qu37ay/1" target="_blank">https://jsfiddle.net/L4qu37ay/1</a>

### Other comments
If you write something else than zero, like "1.15", it works. It's only with zero that the field behave strangely

**Comment by jacekkarczmarczyk** [comment]
v-model modifiers don't work in custom components
https://github.com/vuejs/vue/issues/3666
