### ISSUE TITLE
[Bug Report] Chip, wrapped in v-item-group updates its selected attribute only on focus-out

### ISSUE THREAD

**Issue by rreckonerr** [vuetifyjs/vuetify#6690]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
Click on a chip to select it. Click one more time on it and it won't change its "selected" state. Click somewhere outside the button, it'll become deselected.

### Expected Behavior
I expect it to change its "selected" state right after clicking on it.

### Actual Behavior
It changes its state only on focus-out

### Reproduction Link
<a href="https://codesandbox.io/s/qxqojp6l0w" target="_blank">https://codesandbox.io/s/qxqojp6l0w</a>

### Other comments
You can find the same "buggy" behaviour on official Vuetify example page https://vuetifyjs.com/en/components/item-groups#chips

**Comment by KaelWD** [comment]
Resolved in 2.0: https://next.vuetifyjs.com/en/components/chip-groups

1.x chips don't differentiate between "selected" and "focused"

See also #3817
