### ISSUE TITLE
[Bug Report] v-treeview active.sync doesn't work with activatable and open-on-click

### ISSUE THREAD

**Issue by paulceli** [vuetifyjs/vuetify#6692]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.6
**Browsers:** Google Chrome
**OS:** Mac OS 10.14.3

### Steps to reproduce
Click on elements of the treeview

### Expected Behavior
I should update the active array with the selected element. At least work on leaves.

### Actual Behavior
There is apparently nothing being selected and active array stays empty

### Reproduction Link
<a href="https://codepen.io/anon/pen/XGMBjq?editors=1010" target="_blank">https://codepen.io/anon/pen/XGMBjq?editors=1010</a>

**Comment by paulceli** [comment]
Was concluded from Discord #bugs chat that the problems comes from empty children arrays.
Workaround-able, but would still be nice to have it work anyway.

**Comment by z0mbie42** [comment]
Hi,

I encountered the same bug (Vuetify 1.5.14), even without `open-on-click`

How did you managed to get it working ?

**Comment by paulceli** [comment]
@z0mbie42  Like I said, if you get rid of the empty children array in items data.

**Comment by z0mbie42** [comment]
Thank you, but it still doesn't work for me.


For the record, here is what look like my code

```vue
        <v-treeview
          :active.sync="to"
          :items="items"
          item-key="id"
          :load-children="fetch_folder"
          :open.sync="open"
          activatable
          class="grey lighten-5"
          indeterminate-icon="mdi-loading"
          item-children="files"
        >
```

So I don't have `open-on-click` and even if I remove the `files` property, `active.sync` does not work.

**Comment by z0mbie42** [comment]
Thank You!

**Comment by nekosaur** [comment]
items with `children` property are handled as parent nodes, which can not be activated when using `open-on-click`.

**Comment by CavalcanteLeo** [comment]
@nekosaur so is it impossible?

Should i use another lib for tree view?
