### ISSUE TITLE
[Feature Request] v-slider label 

### ISSUE THREAD

**Issue by pimboden** [vuetifyjs/vuetify#6693]
### Problem to solve
Add possibility to display label in the same way as it is in v-text-field component 
(over slide, not on right)

(Copied form  https://github.com/vuetifyjs/vuetify/issues/6555)

Depending on the use it  just doesn't look streamlined,
![image](https://user-images.githubusercontent.com/22517784/53975562-62d0be00-4105-11e9-96c7-a928f62f353f.png)

### Proposed solution
Add prop label-top:Boolean. If false than on right, else over slide.

https://codepen.io/marbibu/pen/QYPEqb

**Comment by pimboden** [comment]
Depending on the use it  just doesn't looked streamlined,

![image](https://user-images.githubusercontent.com/22517784/53975479-36b53d00-4105-11e9-942d-ce0a6639b064.png)

**Comment by KaelWD** [comment]
Like this? https://play.vuetifyjs.com/#eNqlUUFuwjAQ/IrlM7YruCFa0Tf0iDmYZBFubceyl1QV4u9dO0FNQw9IzSHKzu7szGx2F/4ao+zPwNd8g+CjMwgvOjC26YWJsX7WoukCGhsgjVAFjxZcy3qTrAn4rDnRbdCcOXMAR/Wbsy0kAkyDth8Wl0cjkXNtshO9RQu03GXWOJMzET2KJdHUj5ga1W6OqP5tqSCD442aJOELbn3sEgpvonzPXaCol0LQYyNrvmYVKRjdotSanxBjXivVtIFoLTjbJxkAVYhebWlMpXNA68l857cruZJP4kAx5Eq1NuO0KyF7cUjdZ4ZEuzRfTNTQHr8eUBwnSWgpl4PCCAm6di4Sd6sV6fWQRIJAly4/4rFgM9of4WYTdwGLiasOV7q+s+Ejzw7f5Hr03c3rv5LXZWXTvgheF3xqlwxUHt9/A/8j+Gk=

**Comment by johnleider** [comment]
If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
