### ISSUE TITLE
[Bug Report] v-select example no longer shows 'select all' when using prepend-item

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#6695]
### Versions and Environment
**Vuetify:** 1.5.5
**Last working version:** 1.5.1
**Vue:** 2.6.8
**Browsers:** Firefox 65.0
**OS:** Windows 7

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/selects#prepend-append-item-slots

When you run the code there is no longer a 'select all' option. This occurred when changing the example from slots to v-slot

### Expected Behavior
Expected to see 'select all'

### Actual Behavior
'select all' is missing

### Reproduction Link
<a href="https://jsfiddle.net/" target="_blank">https://jsfiddle.net/</a>

**Comment by UglyHobbitFeet** [comment]
It looks like it's because there are 2 separate prepend-item calls.  One solution is to combine them. However this is different from how it used to work (you could add multiple separate ones).  Not sure what the 'correct' solution should be

**Comment by rbanks54** [comment]
It's likely due to some Vue 2.6 changes. I'm not 100% sure, but if there's multiple templates targeting the same named slot Vue will only use the last one defined. I'm not sure why it would've worked before; likely a quirk that's since been cleaned up with all the slot related changes.

**Comment by KaelWD** [comment]
1b4a7fc9
