### ISSUE TITLE
[Bug Report] Touch functionality works improperly in RTL

### ISSUE THREAD

**Issue by FunnyPhantom** [vuetifyjs/vuetify#6696]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
* change direction
* use a touchscreen to swipe

### Expected Behavior
swiping to left shows the picture to the right of the current image in the view and vice versa.

### Actual Behavior
swiping to left results to show the picture to the left,
and swiping right results to show the picture to the right.

### Reproduction Link
<a href="https://codepen.io/funnyphantom/pen/PLpMRE" target="_blank">https://codepen.io/funnyphantom/pen/PLpMRE</a>

### Other comments
Although it is very nice to see that the setting `$vuetify.rtl` to `true` is reflected in direction of the items in the carousel, but it seems like to have an unnecessary impact on the touch control of the items.
(this bug is also present in touch functionality of `VTabs` and presumably all other component which mixined `touch`)

**Comment by sh7dm** [comment]
@johnleider that's not fixed yet

**Comment by FunnyPhantom** [comment]
@sh7dm the current workaround is to swap left and right default action, the default action can be accessed in touch util.

**Comment by johnleider** [comment]
This unfortunately will not be resolved in time for v2.0. Will resolve in a patch later on. Thank you for your patience!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
