### ISSUE TITLE
Code for Sidebar w/drawer?

### ISSUE THREAD

**Issue by cschweda** [vuetifyjs/vuetify#67]
Stupid question, but I'm trying to figure out how to embed a sidebar with drawer functionality as in the examples.

https://vuetifyjs.com/components/sidebar

However, the source code on the page doesn't seem to mirror the actual, working examples.

Essentially, what I want is a navbar with the hamburger icon to open/close the sidebar. That's it.

Is it possible to include the source code for your working examples (as opposed to the just minimum code needed for each example)? 

Hope this makes sense.

**Comment by johnleider** [comment]
The docs are still in the progress of being updated, however, I believe there are more examples [here](https://vuetifyjs.com/layouts).

```html
<v-app top-navbar left-fixed-sidebar>
  <header>
    <v-navbar><v-navbar-side-icon v-sidebar:sidebar></v-navbar-side-icon>
  </header>
  <main>
    <v-content>
       <v-container>
          <v-sidebar id="sidebar" drawer></v-sidebar>
       </v-container>
    </v-content>
  </main>
</v-app>
```

**Comment by cschweda** [comment]
Great -- thank you!
