### ISSUE TITLE
[Bug Report] VMenu positionX, positionY unexpected behaviour

### ISSUE THREAD

**Issue by jsmith** [vuetifyjs/vuetify#6702]
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
See `App.vue` in reproduction link.

### Expected Behavior
The menu should be positioned at 0, 0.

### Actual Behavior
The menu is positioned at 12, 12.

### Reproduction Link
<a href="https://codesandbox.io/s/xo4qyn6myw" target="_blank">https://codesandbox.io/s/xo4qyn6myw</a>

### Other comments
See the following links for the lines of code that I found: 
- https://github.com/vuetifyjs/vuetify/blob/a546c752e3209bbb09a54222e623573dbd35c038/packages/vuetify/src/mixins/menuable.js#L229
- https://github.com/vuetifyjs/vuetify/blob/a546c752e3209bbb09a54222e623573dbd35c038/packages/vuetify/src/mixins/menuable.js#L199

I am just wondering if there is a reason that this exists? Nothing seems to be documented. I'm currently trying to position a menu that has `positionX` set to 0 and ran into this issue.

Thanks :)

**Comment by atilkan** [comment]
I had the same issue. Update the version. It is broken on that release somehow.

![Screen Shot 2019-03-09 at 18 09 58](https://user-images.githubusercontent.com/1254613/54073304-9a22a480-4296-11e9-9f05-e82a15c1bc6d.png)

**Comment by jsmith** [comment]
Thank you for the suggestion!  I've upgraded `Vuetify` to `1.5.5` (in my actual application and the in codepen) and seem to be getting the same result :confused: 

The lines of code I linked to seem to still be in master.

**Comment by atilkan** [comment]
you are using it wrong. Read documents.

**Comment by jsmith** [comment]
I'm actually trying to position the menu at `0, 0` of the page though.

I'm using `VMenu` for a menu on an Electron app. Here is an image (to activate the menu you click `File`):

<a href="https://imgbb.com/"><img src="https://i.ibb.co/sqtPTnX/Screenshot-from-2019-03-09-11-49-08.png" alt="Screenshot-from-2019-03-09-11-49-08" border="0" /></a>

I expected the menu to be placed about `12px` to the left. My question is, why is there a minimum bound set at `12px`?

**Comment by atilkan** [comment]
good luck finding answer for that.

**Comment by jsmith** [comment]
Here is a simpler example -> https://codesandbox.io/s/mm7q1w9k69

Thank you haha

**Comment by jsmith** [comment]
Closing this since I eventually stopped using `VMenu`
