### ISSUE TITLE
[Bug Report] Calendar is using camelCase for slot names

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetify#6704]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
1. Open codepen
2. Observe that events are not shown

### Expected Behavior
Events are shown

### Actual Behavior
Events are not shown

### Reproduction Link
<a href="https://codepen.io/anon/pen/KEqLaJ?editors=1010" target="_blank">https://codepen.io/anon/pen/KEqLaJ?editors=1010</a>

### Other comments
We can't use camelCase slot names with the new slot syntax. Will have to be changed to kebab-case.

**Comment by ClickerMonkey** [comment]
@nekosaur Are kebab-case slots backwards compatible? Do we care?

**Comment by MajesticPotatoe** [comment]
@ClickerMonkey camelCase doesnt work with new slot syntax :(

**Comment by ClickerMonkey** [comment]
I get that, but does kebab-case work with older versions of Vue? I have to admit never seeing it before.

**Comment by KaelWD** [comment]
No idea if it gets converted to camelCase like props do, but if it doesn't it'd just be `this.$slots['kebab-case']`

@MajesticPotatoe yeah they do, just not in dom templates (which suck anyway)

**Comment by MajesticPotatoe** [comment]
ah 🤦‍♂️ probably best to standardize it across the board anyways.

**Comment by Azzeccagarbugli** [comment]
Sorry for the duplicate, I didn't see it at all. Is there any _temporary_ that we should use to fix the current bug? Thank a lot

**Comment by nekosaur** [comment]
yes, use the old slot syntax

**Comment by KaelWD** [comment]
Or don't use DOM templates.

https://forum.vuejs.org/t/confused-about-dom-template-and-string-template/1797/2
