### ISSUE TITLE
[Bug Report] Can't find variable performance in ripple directive

### ISSUE THREAD

**Issue by kxpvcr** [vuetifyjs/vuetify#6706]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.5.22
**Browsers:** Safari
**OS:** Mac OSX 10.9/10.10

### Steps to reproduce
I'm not sure, but using Vuetify is causing Bugsnag to generate the error shown in the comments section. Happens in macOS 10.9/10.10.

### Expected Behavior
Using the ripple directive yields no production errors

### Actual Behavior
Using the ripple directive yields production errors

### Reproduction Link
<a href="https://www.careship.de/kunde/anfrage" target="_blank">Careship.de page where it happens</a>

### Other comments
window.onerror/kunde/anfrage
ReferenceError: Can't find variable: performance
node_modules/vuetify/es5/directives/ripple.js:79
animation.dataset.activated = String(performance.now());

**Comment by KaelWD** [comment]
Safari what? performance should be supported by >8

**Comment by KaelWD** [comment]
Safari 9 doesn't work correctly in OSX < 10.11: https://stackoverflow.com/a/32940166/2074736

You may need polyfills if you want to support this particular combination.

**Comment by kxpvcr** [comment]
Safari 9 in macOS 10.9 and 10.10, yes. We don't particularly care about that browser/OS combination, I just thought I might as well report the issue :)
