### ISSUE TITLE
v-tabs interfering with card styling

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#671]
Just a small bugfix:
Please remove [this](https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/components/_tabs.styl#L6) CSS style. There is no reason for the tab component to alter the default card styling.

**Comment by johnleider** [comment]
Careful with statements like that. Nothing is ever done by accident.  With that being said, I'll look into why I put that there.

**Comment by sindrepm** [comment]
Sorry if my comment came across a bit harsh. I understand it was put there for a reason. In the docs I see that a card is used inside the tab to add a header/toolbar-like appearance to the example. I suspect that is the reason the border-radius style was added. As you probably figured I am not a big fan of such code which could eventually cause undesirable side effects.
