### ISSUE TITLE
[Bug Report] v-date-picker does not focus when min and show-current are set

### ISSUE THREAD

**Issue by arneysebaert** [vuetifyjs/vuetify#6714]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. Add v-date-picker to project
2. Set min prop in the future
( 3. Set show-current prop in the future ) 
=> v-date-picker focuses on current day, not the day set 

### Expected Behavior
v-date-picker sets focus to the date set in show-current or even min prop.

### Actual Behavior
v-date-picker focuses on current day, not the day set in show-current or min.

### Reproduction Link
<a href="https://codepen.io/arneysebaert/pen/GeMbNd" target="_blank">https://codepen.io/arneysebaert/pen/GeMbNd</a>

2.x https://codepen.io/jkarczm/pen/bGVpBoy

**Comment by johnleider** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/pull/11305
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
