### ISSUE TITLE
[Feature Request] Styling an entire day individually on a v-calendar 

### ISSUE THREAD

**Issue by ShetlandJ** [vuetifyjs/vuetify#6715]
### Problem to solve
I'm representing data on a calendar, and I'd like to use a conditional class to style calendar days individually. I can't see how this is possible within the current `<template scope-slot="day"></template>` at the moment.

### Proposed solution
https://i.imgur.com/LcBeZAX.png

Conditionally applying a class on the day. This example was done editing things in the inspector, but it would be cool if we could just easily add a flag to the day instance like `:background-color="backgroundColour"`.

**Comment by jadewon** [comment]
+1
I'd like to change font color to red on holidays
`
<template v-slot:day="{ date }">
  <template v-for="holiday in holidaysMap[date]">
    <div v-ripple class="holiday">
      {{ holiday.name }}
    </div>
  </template>
</template>
<style>
.v-calendar-weekly__day:has(.holiday) {
  color: red;
}
</style>
`
but unfortunatly `:has` pseudo-class is still not support yet.
so I want to add `.holiday` class on `.v-calendar-weekly__day`
something like this
`
<style>
.v-calendar-weekly__day.holiday {
  color: red;
}
</style>
`

**Comment by christian-kolb** [comment]
@ShetlandJ @MajesticPotatoe @jadewon @johnleider I have the same requirement but for the week view. At the moment the slot isn't used. According the documentation the week view should use the slot. But I guess with the intervals, it wouldn't be much fun to implement the behaviour from scratch.

```
<v-calendar ....>
  <template v-slot:day="{ date }">
    Test {{ date }}
  </template>
</v-calendar>
```

Did any of you find a workaround for this topic?

**Comment by ShetlandJ** [comment]
I didn't find a solution, I ended up using a sort of custom rolled calendar instead of Vuetify

**Comment by christian-kolb** [comment]
@ShetlandJ Shame, but thanks a lot for your quick reply 🙂

**Comment by christian-kolb** [comment]
@MajesticPotatoe @johnleider @ClickerMonkey What do you think of the proposal to do the following:

Add an additional property to the calendar component called `day-class` which could be set statically or via a function which would supply the current day as `CalendarTimestamp` and expect a `string` to be returned. This would solve all styling issues and there would be no need to overwrite a lot in a slot.

If I would supply such a solution as a Pull Request, would it be accepted?

**Comment by LucaColombi** [comment]
I did some magic, by using a template with a coloured square:

```
	<v-calendar locale="it" min-weeks="5" ref="calendar" v-model="calendar.value"
	.....>
		<template v-slot:day="{ past, date }">
			<div v-if="calendar.dates[date]" style="position:absolute;top:0;left:0;right:0;left:0;" v-bind:style="{ 'background-color': calendar.dates[date].color }">
				X {{date}}
			</div>
		</template></v-calendar>
```

**Comment by mrkazu** [comment]
> I did some magic, by using a template with a coloured square:
> 
> ```
> 	<v-calendar locale="it" min-weeks="5" ref="calendar" v-model="calendar.value"
> 	.....>
> 		<template v-slot:day="{ past, date }">
> 			<div v-if="calendar.dates[date]" style="position:absolute;top:0;left:0;right:0;bottom:0;opacity:0.5" v-bind:style="{ 'background-color': calendar.dates[date].color }">
> 				&nbsp;
> 			</div>
> 		</template></v-calendar>
> ```
> 
> you can start from here and see if you can obtain what you want
> 
> anyway, this component should have a little more extensibility

This is nice! however, the div layer will be under the events but above the date button, making the day button not activate functions when clicked.

to fix this you need to add 

.v-btn--fab {
    z-index: 2;
  }
