### ISSUE TITLE
v-checkbox and v-switch manipulate the value property directly (vuex strict)

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#672]
### Steps to reproduce
- load an array from a vuex store and use it as v-model in a v-switch/v-checkbox
- enable the strict mode of the vuex store (https://vuex.vuejs.org/en/strict.html)
- Select an v-switch/v-checkbox
- Now you get a warning in the Browserconsole: Do not mutate vuex store state outside mutation handler

### Versions
0.12.5

### What is expected ?
The component shouldn't manipulate the v-model directly. All manipulations of the v-model should be triggered by an $emit('input', newValue)

### What is actually happening ?
The component manipulates the v-model directly and not with an input emit.

### Reproduction Link
https://codepen.io/kpilard/pen/JJPzNy?editors=1010

**Comment by kpilard** [comment]
Thank you :)

**Comment by AliHaider26** [comment]
any update ???

**Comment by jacekkarczmarczyk** [comment]
This is issue is closed. If you're experiencing similar problem in the current branch create a new issue. Thank you
