### ISSUE TITLE
[Bug Report] Tabs with tooltips cannot be displayed centered

### ISSUE THREAD

**Issue by mseele** [vuetifyjs/vuetify#6721]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Chrome 73.0.3683.75
**OS:** Windows 10

### Steps to reproduce
add tooltip to tabs. without tooltip, the tabs are centered. (especially the last tab, when the last tab has no tooltip, the tabs are centered)

### Expected Behavior
tabs should be centered

### Actual Behavior
tabs are right aligned instead of centered

### Reproduction Link
<a href="https://codepen.io/anon/pen/oVoJeM" target="_blank">https://codepen.io/anon/pen/oVoJeM</a>

**Comment by KaelWD** [comment]
Fixed by b238b7192c473f39bc51e0b15b29f23e678d1e92: https://codepen.io/anon/pen/XGzoxZ

**Comment by mseele** [comment]
does that mean this bug will never be fixed in 1.5.x stream?
