### ISSUE TITLE
[Bug Report] text-truncate not working as expected inside default slot of v-img

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vuetifyjs/vuetify#6723]
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.4
**Browsers:** Firefox 65.0
**OS:** Windows 10

### Steps to reproduce
Add a long text inside a `text-truncate` `div` tag in the default slot of `v-img`

### Expected Behavior
It is expected that the text will be truncated well within the image boundary

### Actual Behavior
`v-responsive__content` takes the whole width of the text

### Reproduction Link
<a href="https://codepen.io/anon/pen/aMVeOw" target="_blank">https://codepen.io/anon/pen/aMVeOw</a>

### Other comments
Something like
```
.v-image .v-responsive__content {
    max-width: 100%;
}
```
seems to work.

**Comment by KaelWD** [comment]
This was resolved in 09725fc8f27d1ec543fced9236b033629c940b8c
