### ISSUE TITLE
[Bug Report] <v-expansion-panel> doesn't respect a fixed height of its parent

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#6724]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.3

### Steps to reproduce
Put `v-expansion-panel` into a `div` with fixed height and `overflow:hidden`.
Then click to expand one of the items

### Expected Behavior
The height of the `v-expansion-panel` should not exceed the parent's height.
If `v-expansion-panel` needs more height for its expanded items (e.g. in case they contain large portions of content), the content of those items should become scrollable in order for the whole component to fit into the parent element

### Actual Behavior
Part of the `v-expansion-panel` that doesn't fit the parent's height become hidden

### Reproduction Link
<a href="https://codepen.io/alexeime/pen/aMVgpv?editors=1000" target="_blank">https://codepen.io/alexeime/pen/aMVgpv?editors=1000</a>

**Comment by KaelWD** [comment]
You should add `overflow-y: auto` to the parent.

**Comment by aantipov** [comment]
The provided solution `overflow-y: auto` doesn't achieve the desirable affect. What it does is making the whole `v-expansion-panel` scrollable within the parent.
I expected to have a more sophisticated effect - making scrollable the contents of the active (expanded) element

**Comment by nmearl** [comment]
I am experiencing this issue as well -- I want the panel titles always visible, and therefore to ensure that if a panel is expanded, the contents inside become scrollable in order to keep the other panels from moving off-screen.

**Comment by dnasir** [comment]
I ran into a similar situation, where I needed the component to NOT overflow the parent container, and instead add a scrollbar to the content when necessary. Here's what I came up with.

https://codesandbox.io/s/contained-vuetify-expansion-panels-c0ugs

Hope it helps. Feel free to add improvements.
