### ISSUE TITLE
[Feature Request] Server Side Rendering docs are missing again?

### ISSUE THREAD

**Issue by nickforddev** [vuetifyjs/vuetify#6727]
### Problem to solve
I tried to make this a bug report but it didn't fit.

In this issue https://github.com/vuetifyjs/vuetify/issues/10#ref-commit-e7a9ba1, the webpack-ssr template was referenced, but that is now deprecated and archived. I see two very brief mentions of SSR in the docs, and there is still a big bullet point with a checkmark saying SSR is supported, but I see no examples of how to set it up.

I probably wouldn't be creating an issue for that alone, but I'm having a very difficult time getting Vuetify to play nicely with vue-server-renderer, I get the following error when I run the production build and the start the prod server: 

```
server.js:78 /Users/nford/Sites/vue-cli-ssr-example/node_modules/vuetify/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import Vuetify from './components/Vuetify';
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I've been using this Vue core team member's example as a guide for SSR: https://github.com/eddyerburgh/vue-cli-ssr-example

### Proposed solution
Update the docs to include information about SSR, or remove it from the list of supported features. 

Edit: I just tried out Nuxt and see that it sets up Vuetify quite easily. If usage with Nuxt is the only supported solution, fine, include that in the docs.

**Comment by Shigma** [comment]
I tried with vuetify-loader, and it failed just like above. After removing vuetify-loader, my SSR website works properly.
