### ISSUE TITLE
[Bug Report] VTabs does not properly handle removing items

### ISSUE THREAD

**Issue by scottbommarito** [vuetifyjs/vuetify#6729]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.9
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
1. Create an instance of VTabs that relies on a dynamic list of items.
2. Select a tab.
3. Delete the item associated with another tab.
4. Observe how selection changes

### Expected Behavior
- Clicking on any remaining tab will make it active
- Deleting the active tab will change the active tab to the next tab in the list (or the previous tab if the selected tab was last in the list)

### Actual Behavior
- Clicking on a tab to the right of the tab you deleted makes the tab to the right of the tab you clicked active
- Deleting the active tab does not update the UI unless it is the last tab in the list.

### Reproduction Link
<a href="https://codepen.io/anon/pen/drJBQW" target="_blank">https://codepen.io/anon/pen/drJBQW</a>

### Other comments
I looked at the code and believe this is a result of the base `VItemGroup`
- [the click handler for a item](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VItemGroup/VItemGroup.ts#L106) depends on the index of the item when it was registered
- the component keeps track of what active items by indexes but does not properly update what it stores when the list of items changes

**Comment by KaelWD** [comment]
Seems to work fine if you do it properly: https://codepen.io/anon/pen/xBpvWP?editors=1111

 - You have two 0s because of the post-increment
 - You weren't using 2.0
 - You're showing index in the bar but item in the content

**Comment by scottbommarito** [comment]
Apologies, I'm new to `vue` and `vuetify`, but the behavior still seems to be strange to me.

Could you clarify what you're referring to by `2.0`? I see the `vuetify: new Vuetify()` in your codepen but I had never seen this before or in the docs.

I don't see any change in behavior if I fix the duplicated `0` issue.

If I take out the reference to the `item` in the tab in your codepen (`{{ index }}` instead of `{{ item }} - {{ index }}`, it jumps around unpredictably when the selected tab is deleted. In the app I was building, I intentionally wanted the tabs to show the index of the item and not a reference to the item itself.

**Comment by KaelWD** [comment]
> what you're referring to by 2.0

You said you're using Vuetify 2.0.0-alpha.9

> I had never seen this before or in the docs

It isn't finished yet

> jumps around unpredictably

Always goes to the end tab for me

---

#4735, #5515, #6278

**Comment by scottbommarito** [comment]
Apologies, I clicked the latest version in the list because the bug reproduced when I pulled master and built it. I would suggest improving your bug filing and contribution documentation so that people don't have this confusion in the feature. Ideally you should have some sort of simple instructions on how to build and use the latest version if you expect people to know whether or not their bug reproduces in the latest version, especially if it's as simple as including `vuetify: new Vuetify()`.

Furthermore, going to the end tab is a bad experience. If there's 4 tabs and I've selected the second tab and then delete it, I shouldn't jump to the last tab in the list. I think the vast majority of people will expect that it will remain on the second tab (which was the third tab before).
