### ISSUE TITLE
v-tabs why it has “text-transform: uppercase;” default？

### ISSUE THREAD

**Issue by lx28110846** [vuetifyjs/vuetify#6730]
the word in v-tabs  is all uppercase，it has css “text-transform: uppercase;”，why？
how can i unset it ？

**Comment by KaelWD** [comment]
https://material.io/design/components/tabs.html

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by hadimsm** [comment]
Use following code in your css:

.v-tab {
    text-transform: none !important;
  }

**Comment by tonyinit** [comment]
You can also use the class `text-none` in the `v-tab` to remove the default capitalization.
This works for other vuetify components as well, such as `v-btn`.
