### ISSUE TITLE
[Bug Report] Height not working correctly for v-textarea default style & solo style

### ISSUE THREAD

**Issue by nidkil** [vuetifyjs/vuetify#6733]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.5.21
**Browsers:** Firefox 65.0
**OS:** Windows 10

### Steps to reproduce
Add the height attribute to the v-textarea with style default or solo.

### Expected Behavior
The textare to display correctly for all styles in all browsers.

### Actual Behavior
The textarea does not display correctly in Firefox.

### Reproduction Link
<a href="https://codepen.io/nidkil/pen/aMqqBG?editors=1010" target="_blank">https://codepen.io/nidkil/pen/aMqqBG?editors=1010</a>

### Other comments
It does work correctly for the styles box and outline. All styles work correctly with Chrome.

**Comment by Tarabass** [comment]
To be more clear about what's going wrong I made a pen with textarea's with a height and a lot of text. 

https://codepen.io/Tarabass/pen/JQBNqL?&editable=true&editors=101

**Comment by johnleider** [comment]
v-textarea with the outline property regressed from v1.5 and I'm marking #12075 as part of this task since they both have to do with coherent styles.

**Comment by johnleider** [comment]
This is resolved as of the latest version.

https://codepen.io/johnjleider/pen/WNpLMYE

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
