### ISSUE TITLE
[Bug Report] Menu will not work when element is displayed in fullscreen mode

### ISSUE THREAD

**Issue by BePsvPT** [vuetifyjs/vuetify#6739]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.9
**Browsers:** Firefox 65.0
**OS:** Mac OS 10.14

### Steps to reproduce
1. Click Enter Fullscreen Button.
2. Click select or menu.

### Expected Behavior
Select and menu list will show normally.

### Actual Behavior
Nothing shown.

### Reproduction Link
<a href="https://codepen.io/anon/pen/MxVvYd" target="_blank">https://codepen.io/anon/pen/MxVvYd</a>

### Other comments
All components that use menu will not work, like v-menu, v-select and v-tooltip.

**Comment by KaelWD** [comment]
Menus are detached to the root be default. Either fullscreen the `v-app` instead, or use the menu's `attach` prop.
