### ISSUE TITLE
[Bug Report] VTabs with vue router don't work with lazy loading

### ISSUE THREAD

**Issue by Rolanddoda** [vuetifyjs/vuetify#6740]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.5.22
**Browsers:** Opera 58.0.3135.79
**OS:** Windows 10

### Steps to reproduce
In the reproduction link, go to the `router.js` and see that the components are imported by using lazy load.

### Expected Behavior
In the view click the `Go to Tabs`. By clicking that, it should navigate you to the tabs page.

### Actual Behavior
As result I get 
```
[vue-router] Failed to resolve async component default: DependencyNotFoundError: Could not find dependency: 'function () {
            return require(".' relative to '/src/router.js'
```

### Reproduction Link
<a href="https://codesandbox.io/s/431x7nzkx0" target="_blank">https://codesandbox.io/s/431x7nzkx0</a>

### Other comments
The thing is, that if I use the imported components instead of lazy loading them everything works just fine.

**Comment by johnleider** [comment]
This has nothing to do with tabs. You can completely remove the component and this error still occurs.
