### ISSUE TITLE
[Bug Report] Overflow hides items in a toolbar

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify#6744]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.6.8
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Just by increasing the number of chips in the toolbar as per the attached reproduction link

### Expected Behavior
I expected to see a horizontal scrollbar incase items are many not pushing away other items in a toolbar

### Actual Behavior
The toolbar items are pushed away from the toolbar

### Reproduction Link
<a href="https://codepen.io/geowan/pen/OqZwyy" target="_blank">https://codepen.io/geowan/pen/OqZwyy</a>

**Comment by KaelWD** [comment]
In 2.0 you will be able to use [`v-slide-group`](https://next.vuetifyjs.com/en/components/slide-groups) to replicate the overflow behaviour of `v-tabs`

**Comment by Geowan** [comment]
The version 2.0 is not ready for production yet as per the release docs

> DO NOT USE IN PRODUCTION

. Is there any other options in the version 1.3.15 which can work to resolve this?

**Comment by KaelWD** [comment]
You can apply your own css.
