### ISSUE TITLE
[Bug Report] Property edit-icon of v-stepper-step doesn't work unless step is both editable and complete

### ISSUE THREAD

**Issue by alexandrucancescu** [vuetifyjs/vuetify#6745]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.3

### Steps to reproduce
Create v-stepper-step with edit-icon and editable properties. Doesn't show the custom icon. Add complete property and it works.

### Expected Behavior
Show the custom icon passed in the edit-icon property as long as step is editable, even though it is not complete.

### Actual Behavior
Custom icon only shows when step is also complete.

### Reproduction Link
<a href="https://codepen.io/anduhd/pen/ZEpOBdM?editors=1010" target="_blank">https://codepen.io/anduhd/pen/ZEpOBdM?editors=1010</a>

**edit: fixed link**

**Comment by MartinezNunezMarcoAntonio** [comment]
Please add "completed" like the second stepp,

**Comment by njbarrett** [comment]
Confirming, this is still an issue

**Comment by scscgit** [comment]
I'll add one more suggestion: could we have the option to disable the edit icon and display the original one? I tried some random alternatives like :step="null" or :step="1", but they don't seem to provide the expected result. (Btw. the repro link seems to have issue loading Vue.)

**Comment by alexandrucancescu** [comment]
The codepen is one year old and seems to have lost the CDN scripts for vue and vuetify. I treid to add them back but the vuetify API changed and the whole codepen is out of date. @scscgit If you are familiar with the new API can you please make a codepen ilustrating the problem?

My original code was this
```html
<div id="app">
  <v-app id="inspire">
    <v-stepper>
      <v-stepper-header>
        <v-stepper-step
          
          editable
          step="1"
          edit-icon="insert_photo"
        >
          Doesn't work
        </v-stepper-step>
  
        <v-divider></v-divider>
  
        <v-stepper-step
          complete
          step="2"
          edit-icon="insert_photo"
          editable
        >Works</v-stepper-step>
  
        <v-divider></v-divider>
  
        <v-stepper-step
          step="3"
        >
          Create an ad
        </v-stepper-step>
      </v-stepper-header>
    </v-stepper>
  </v-app>
</div>
```

```javascript
new Vue({
  el: '#app',
  
})
```
I tried making it work here:
https://codepen.io/anon/pen/RdyerJ?editors=1011

**Comment by alexandrucancescu** [comment]
Ok, managed to make it work again. Seems like the behaviour is the same.

[codepen](https://codepen.io/anon/pen/RdyerJ?editors=1011)

**Comment by Mstrdk** [comment]
Confirming, this is still an issue...

**Comment by mikeosexton** [comment]
Also confirming as an issue. Has anyone found a suitable workaround for this?

**Comment by Yuutakasan** [comment]
I'm having problems with it too.
