### ISSUE TITLE
[Bug Report] v-spacer sends elements below when inside v-flex

### ISSUE THREAD

**Issue by alexandrucancescu** [vuetifyjs/vuetify#6747]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.3

### Steps to reproduce
Create v-flex with two v-btns. Add v-spacer between them.

### Expected Behavior
The two buttons should be on the opposite sides of the row

### Actual Behavior
They are one above the other

### Reproduction Link
<a href="https://codepen.io/anon/pen/YgLmaV?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/YgLmaV?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
v-flex is not a flexbox container.
