### ISSUE TITLE
[Bug Report] fullscreen scrollable dialog stretches v-card-title and v-card-actions if there's not enough content in v-card-text

### ISSUE THREAD

**Issue by Fyroman** [vuetifyjs/vuetify#6754]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.9
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
Just open dialog, but try to set view to something like phone's portrait mode, bigger the height, more prominent the bug will be

### Expected Behavior
v-card-title and v-card-actions shouldn't grow to fill empty space

### Actual Behavior
v-card-title and v-card-actions do grow to fill empty space

### Reproduction Link
<a href="https://codepen.io/anon/pen/wOXVXy?editors=1010" target="_blank">https://codepen.io/anon/pen/wOXVXy?editors=1010</a>

### Other comments
v-card-title and v-card-actions have flex-grow set to 1 for some reason. might the fix be that easy?

**Comment by NerijusD** [comment]
Can this be fixed on v1.5.x ?

**Comment by Fyroman** [comment]
Just apply style flex: 0 to v-card-title and v-card-actions.
