### ISSUE TITLE
[Feature Request] Add prop to v-img to disable onerror logging

### ISSUE THREAD

**Issue by DanielStout5** [vuetifyjs/vuetify#6755]
### Problem to solve
Currently v-img will log an error to the console if the URL fails to load.

This is undesirable because sometimes the URL might be provided by a user, and we should be able to prevent console error logs.

### Proposed solution
Add a Boolean prop to VImg.ts called `logErrors` with a default value of true.

Change this line: `image.onerror = this.onError` to be: `image.onerror = this.logErrors && this.onError;`

**Comment by sh7dm** [comment]
@DanielStout5 maybe `noErrors`?

**Comment by alvarobrey** [comment]
For now we're working around this with a wrapper:

```javascript
import VImg from 'vuetify/lib/components/VImg'

export default VImg.extend({
  name: 'VImageWrapper',
  methods: {
    onError() {
      this.$emit('error', this.src)
    }
  }
})
```

**Comment by jfburdet** [comment]
I believe the default should be the same as the standard <img> html components, that is no error logging by default.

**Comment by KaelWD** [comment]
Removed the log on error, still warns about decode failures though. You'll be able to turn off all warnings with `Vuetify.config.silent`: #10909
