### ISSUE TITLE
[Bug Report] Documentation on `v-list-group` missing the `activator` slot

### ISSUE THREAD

**Issue by dbettini** [vuetifyjs/vuetify#6756]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.11.6

### Steps to reproduce
Read the provided `v-list` documentation

### Expected Behavior
The [documentation](https://vuetifyjs.com/en/components/lists) mentions the `activator` slot after picking `v-list-group`, which does exist as seen in the [source](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VList/VListGroup.ts)

### Actual Behavior
The `slots` tab for `v-list-group` is empty

### Reproduction Link
<a href="https://codepen.io/anon/pen/drjGwp" target="_blank">https://codepen.io/anon/pen/drjGwp</a>

### Other comments
I created a useless codepen because it was a required field in the issue creator (not sure what's the reason for that)

**Comment by Victor7095** [comment]
It happens when i fetch the list items from an axios request, but only when the data is empty. If it has at least one item, the activator shows correctly.
