### ISSUE TITLE
[Bug Report] v-time-picker locale option to change number format like 1 => ۱, 2 => ۲

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#6757]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.9
**Browsers:** Chrome 73.0.3683.75
**OS:** Mac OS 10.14.3

### Steps to reproduce
When we use v-time-picker on rtl pages, it's going to show clock rtl I mean reverse clock, also time show in v-time-picker going to rtl, but it's number and number in Persian or another rtl language is ltr as usual.

### Expected Behavior
Show clock like English in rtl pages, Also has locale option to change number format like 1 => ۱, 2 => ۲

### Actual Behavior
It's show clock reverse, you can see in codeSandBox example

### Reproduction Link
<a href="https://codesandbox.io/s/kvqj0413o?fontsize=14" target="_blank">https://codesandbox.io/s/kvqj0413o?fontsize=14</a>

**Comment by MrCapsLock** [comment]
Hi, do you have any plan for this issue? :) I'm waiting for it. thanks.

**Comment by jacekkarczmarczyk** [comment]
Yes, can you sketch the design? I'm not sure how it should be aligned (to left or right?) and where should I place the am/pm (on the left hand side of 00:00 or on the right hand side), also with new am/pm layout should i switch am/pm in rtl mode or not?
Use https://codepen.io/anon/pen/zQmRZL as a reference

**Comment by MrCapsLock** [comment]
I try my best. I do this with photoshop. Just one thing, selection color it not right.
on right side we have hours selection and on left we have minutes selection
![2019-05-30 13 45 40](https://user-images.githubusercontent.com/47828139/58622899-ffa88f00-82e1-11e9-945e-9868fd31075e.jpg)
AM === قبل از ظهر
PM === بعد از ظهر

**Comment by jacekkarczmarczyk** [comment]
Thanks for this, that looks greate, but i'd be greatful if you could make it with english letterns/digits, here i'm going to deal only with rtl alignment, arabic digits and am/pm translations are a separate thing and should be in a separate issue
Thank you!

**Comment by MrCapsLock** [comment]
<img width="590" alt="Screen Shot 2019-05-30 at 3 45 14 PM" src="https://user-images.githubusercontent.com/47828139/58629546-ffb08b00-82f1-11e9-8198-3a7ec35e370a.png">

**Comment by jacekkarczmarczyk** [comment]
Perfect!

**Comment by jacekkarczmarczyk** [comment]
Most of the issues are fixed in current version (2.2.8) or in https://github.com/vuetifyjs/vuetify/pull/10399/files
The only remaining thing is formating clock digits, I'm changing the issue to a Feature Request
