### ISSUE TITLE
[Feature Request] <no-rtl> feature

### ISSUE THREAD

**Issue by Cjumelin** [vuetifyjs/vuetify#6761]
### Problem to solve
Sometime I have unexpected revert of the layouting with the rtl value changes (with offset for example)
https://codepen.io/anon/pen/drqorZ

### Proposed solution
```<no-rtr> </no-rtl>``` that embrace code not reach by the changes of rtl.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jacekkarczmarczyk** [comment]
Also see https://github.com/vuetifyjs/vuetify/issues/6317
