### ISSUE TITLE
[Feature Request] Update documentation of Select to remove outdated/not-working props

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#6765]
### Problem to solve
The docs for `Select` refer to use of the following props:
- `browser-autocomplete`
- `filter`
- `search-input`

which seem to make sense for `Autocomplete` component only.
Also `search-input` refers to use of `autocomplete` prop which is not documented and the use of which is deprecated

### Proposed solution
Remove the props
- `browser-autocomplete`
- `filter`
- `search-input`

from the docs

**Comment by MajesticPotatoe** [comment]
I'll look into this, this evening.

**Comment by MajesticPotatoe** [comment]
* I'm going to go ahead and deprecate out `search-input` as you have mentioned `autocomplete` was deprecate in v1.1 and this has really no use here (will be cleaned up in 2.0 as well). 
* There isn't much need to deprecate `filter` given it has practical use (to filter items) If the team decides to remove this in 2.0 we shall update it accordingly.
* As for `browser-autocomplete` this will stay as it actually has nothing to do with `v-autocomplete`. It so you can disable browser form autocomplete as described.

**Comment by KaelWD** [comment]
Filter only applies when there's search active, so it does nothing for v-select.

**Comment by aantipov** [comment]
>As for browser-autocomplete this will stay as it actually has nothing to do with v-autocomplete. It so you can disable browser form autocomplete as described

The same as with `filter`. There is no search/input field in `v-select` => nothing to "autocomplete" => `browser-autocomplete` option has no effect

**Comment by aantipov** [comment]
Also created a related issue for `v-autocomplete` component https://github.com/vuetifyjs/vuetify/issues/6794

**Comment by MajesticPotatoe** [comment]
filter removed in 5f5db93

**Comment by aantipov** [comment]
@MajesticPotatoe 
> filter removed in 5f5db93

Great! What about `browser-autocomplete`? Will it be also deprecated?

**Comment by KaelWD** [comment]
It'll be replaced with the native `autocomplete` attribute in 2.0

**Comment by aantipov** [comment]
hmmm, do not get it, but ok

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete

**Comment by aantipov** [comment]
@KaelWD I meant for me the solution would be to remove `browser-autocomplete` from the `v-select` documentation, because there is no input field in `v-select`, thus no sense for any autocomplete functionality.

Thus I don't understand how native autocomplete attribute would help here

**Comment by MajesticPotatoe** [comment]
There is an input field in `v-select`

**Comment by aantipov** [comment]
Am I missing something? I looked through all the examples for `v-select` https://vuetifyjs.com/en/components/selects#select
and I haven't find an example where a user can provide any input, there is no filtering/searching functionality.
I thought filtering/search functionality moved to `v-autocomplete` and there only select functionality left in `v-select`
So if you could provide me an example of `v-select` with an input field where a user can type anything, I would appreciate it.

**Comment by MajesticPotatoe** [comment]
take any example of `v-select`, inspect it in a browser, you will see the underlying structure is that of a html `input` element. this element, per Kael's link contains the `autocomplete` attribute. `browser-autocomplete` is what toggles that native attribute on/off. (essentially disabling browser form fill / browser autocomplete)
