### ISSUE TITLE
Some v-dialog improvements

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#677]
After the v-dialog was changed so it is appended to the outer app element this has resulted in some issues. I am passing a custom class to v-dialog in order to override a few styles such as height and change the entire dialog into a flexbox. This used to work because `.dialog` was a child of `.dialog__container`. Now that the `dialog__content` element is moved I am no longer able to target the dialog with my custom class because the class remains on the `dialog__container` element.

Here is an example:
https://codepen.io/anon/pen/xrxZbj

Maybe it would be possible if the class passed into v-dialog is carried over to the same element that has `.dialog`, or perhaps add a new prop `cssClass` which can be used to pass additional classes to the dialog?

Secondly, I would like to see an option to specifiy the dialog height similarly to how the width can be specified.

What do you think?

**Comment by johnleider** [comment]
It's funny you mention this, @dohomi was already on me this morning :)

I completely agree, we need to figure out the best way for this. Unfortunately, due to overflow constraints, menu/dialog had to go to the body, the former was just causing too many issues.

As far as specifying dialog height, that's a great idea.

**Comment by sindrepm** [comment]
@johnleider Yes, I also agree that it had to be moved to the body. I was pulling my hairs out over those overflow issues myself, so was really excited to see this implemented so quickly.

**Comment by dohomi** [comment]
@johnleider maybe for this purpose it would be nice to pass any class from a `menu, select, dialog` and attach it as a class to the overlay container as well. Something like this:
```
<v-menu class="myCustom">...</v-menu>
==>
<div class="menu__container myCustom">...
```
