### ISSUE TITLE
[Bug Report] v-tabs do not show initial selected underline if used inside of a v-dialog

### ISSUE THREAD

**Issue by ktruong19** [vuetifyjs/vuetify#6775]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.10
**Vue:** 2.6.5
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
1. Press open dialog
2. Notice that the first tab "ROUTE" is bold, but there is no selection underline
3. Select "ROUTE2", notice selection underline appears
4. Select "ROUTE", now there is a selection underline

### Expected Behavior
1. Press open dialog
2. "ROUTE" is bold and shows a selection underline

### Actual Behavior
1. Press open dialog
2. Notice that the first tab "ROUTE" is bold, but there is no selection underline

### Reproduction Link
<a href="https://codepen.io/snipah19/pen/JzmMym" target="_blank">https://codepen.io/snipah19/pen/JzmMym</a>

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/54729674-d980a900-4b52-11e9-896f-3ed75138a5c9.png)
