### ISSUE TITLE
[Bug Report] v-select restrictions not displaying in select

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#6777]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.75
**OS:** Linux x86_64

### Steps to reproduce
Set the min value higher than the max or vice versa.

### Expected Behavior
The value itself is correct, but the select does not show the limited value.

### Actual Behavior
The select shows on the value that you clicked, the unlimited one.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xByzRv" target="_blank">https://codepen.io/anon/pen/xByzRv</a>

**Comment by KaelWD** [comment]
https://codepen.io/anon/pen/RdeqJY
