### ISSUE TITLE
Menus are off center and hide behind a dialog

### ISSUE THREAD

**Issue by catskull** [vuetifyjs/vuetify#678]
### Versions
Using 0.12.6. I have stepped back and the bug was introduced in 0.12.3.

### What is expected ?
The menu should not be hidden behind a modal. It should also display near the field.

### What is actually happening ?
For `<v-select>`, it should display just beneath the input field.
For `<v-date-picker>` in menu, it's rendering the picker at the center of the page, not near the input field.

### Reproduction Link
Here's a codepen for the dialog menu: https://codepen.io/anon/pen/JJjYbN
I could not replicate the date picker issue on codepen. I'll keep trying.

**Comment by johnleider** [comment]
Was not able to reproduce any issues with the date-picker. It's simply sitting inside of the menu so that shouldn't change anything.
