### ISSUE TITLE
[Bug Report] switching icons from btn changes width

### ISSUE THREAD

**Issue by dollinvans** [vuetifyjs/vuetify#6781]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.75
**OS:** Windows 10

### Steps to reproduce
if you change the icon in a btn with v-html or with something selfmade (you change the css-display e.g.), than the width of the btn-content doubled itself.  

### Expected Behavior
off course no changes in width

### Actual Behavior
doubles the width of the class btn-content

### Reproduction Link
<a href="https://codepen.io/schnitzeliggi/pen/OqaJpo" target="_blank">https://codepen.io/schnitzeliggi/pen/OqaJpo</a>

**Comment by nekosaur** [comment]
You're using an incorrect icon name. There is no icon `list_view`, so it uses the `list` icon instead and the remainer is what's causing the extra width. Either use `list` icon name, or `view_list` which also exists.

**Comment by dollinvans** [comment]
> You're using an incorrect icon name. There is no icon `list_view`, so it uses the `list` icon instead and the remainer is what's causing the extra width. Either use `list` icon name, or `view_list` which also exists.

ohh really? Oh man why I'm so dumb. Thank you !
