### ISSUE TITLE
vue-router enabled tabs do not match aliased links

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#679]
### Steps to reproduce
Have vue tabs linked to routes with route aliases. Hit the aliased route via a button.

### Versions
0.12.2,0.12.6

### What is expected ?
the tab class is updated to reflect the correctly matched route as active.
The tab indicator moves to the matched route tab.

### What is actually happening ?
The navigation happens but the tab headers are not updated to reflect the active status, when navigation matches an alias.
The tab indicator does not move at all when the tab is selected via code

### Reproduction Link
https://codepen.io/mix3d/pen/YQzqox/

**Comment by mix3d** [comment]
I know tabs are under the knife for reworking, but here are some important things to consider.

**Comment by johnleider** [comment]
This was already supposed to be correct.
