### ISSUE TITLE
[Bug Report] hidden-sm-and-down not working

### ISSUE THREAD

**Issue by k80oshea** [vuetifyjs/vuetify#6790]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
View the codepen in a resizeable window. Full screen desktop view should display a menu on the side. A smaller screen width should adjust to the 'mobile' version of a top toolbar and drop down menu.
Notice that between 960px and 1264px width (Vuetify's md breakpoint) neither appears.

### Expected Behavior
Sidebar menu should show on md, lg, and xl viewports. Top menubar should show on xs and sm viewports.

### Actual Behavior
On md viewports, neither the sidebar menu nor the top menubar are displayed. 

### Reproduction Link
<a href="https://codepen.io/k80oshea/pen/vPQjKQ" target="_blank">https://codepen.io/k80oshea/pen/vPQjKQ</a>

### Other comments
Current work-around is to change the mobile top toolbar class to hidden-lg-and-up so that there is some sort of menu on the md viewport, just not the desired one. 
Changing the sidebar class to hidden-xs-only instead also does not work - the sidebar will still hide after hitting the md breakpoint (1264px).

**Comment by KaelWD** [comment]
Navigation drawers hide themselves at md (1264px). It's recommended to use the `mobile-breakpoint` prop or `disable-resize-watcher` if you want to control it with css instead.
