### ISSUE TITLE
[Feature Request] Update documentation for Autocomplete

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#6794]
### Problem to solve
Description for `search-input` option in `v-autocomplete` is invalid
>Bound when using the autocomplete prop. Use the .sync modifier to catch user input from the autocomplete search input

There is no `autocomplete` prop in `v-autocomplete` component

### Proposed solution
Remove mentioning the `autocomplete` prop:
>Use the .sync modifier to catch user input from the search input

**Comment by MajesticPotatoe** [comment]
This was already resolved by 9324c3d which closed the last FR

**Comment by aantipov** [comment]
@MajesticPotatoe the mentioned PR is about deprecating `search-input` in `v-select`.
This issue is about incorrect docs for `search-input` in `v-autocomplete`.
So I don't see how this issue is resolved

**Comment by MajesticPotatoe** [comment]
AH! my apologies. got confused for a sec. should get my eyes checked lol. I'll make this change in a sec.
