### ISSUE TITLE
[Bug Report] the “item-value” props of component combobox seems not work

### ISSUE THREAD

**Issue by markrujun** [vuetifyjs/vuetify#6795]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.7
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
1.choose an item in combobox
2. Choos the same item in autocomplete
3. The model of combobox is an object, the model of complete is a string

### Expected Behavior
The model of combobox should be a string as same as autocomplete 

### Actual Behavior
The model of combobox is an object,

### Reproduction Link
<a href="https://codepen.io/markrujun/pen/QoJeOy" target="_blank">https://codepen.io/markrujun/pen/QoJeOy</a>

### Other comments
When I use object list([{text:”xx”, value:’’”}]) as the “items” props for combobox , I specify the “item-value” props as “value”, but I got a object as a model value instead of a string. However, I did the same thing to the autocomplete component, and it did work correctly. So I wonder there is something wrong with the combobox component. I would be sorry if this bug was caused by me.thanks

**Comment by KaelWD** [comment]
See #5479
