### ISSUE TITLE
[Vue warn]: Unknown custom element: <v-col>

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#680]
### Steps to reproduce
Use the "NUXT Quick Start", click on link to the inspire page, then click on back to the Welcome page.
 
### Versions
0.12.6

### What is actually happening ?
![screen shot 2017-06-02 at 18 59 22](https://cloud.githubusercontent.com/assets/13983663/26746407/9ef8be04-47c5-11e7-92a1-c53f5d1abaae.png)

**Comment by johnleider** [comment]
Please report this on the vuetify nuxt repository.

**Comment by jvbianchi** [comment]
https://github.com/vuetifyjs/nuxt doesn't have issues enabled.

**Comment by johnleider** [comment]
Fixed

**Comment by jvbianchi** [comment]
done, thanks
