### ISSUE TITLE
[Feature Request] i18n improved with ISO codes for each language

### ISSUE THREAD

**Issue by damvaz** [vuetifyjs/vuetify#6805]
### Problem to solve
Currently each language supported by the framework has a simple string for identification of the language. For example, **es**, **en** and so on.
In many apps we need use a better i18n support for the components.
For example, with a better support for ISO languages we make a select of allowed languages easily:

`
const languages = this.$vuetify.lang.locales.map(lang => {
   return {
      label: lang.info.native,
      value: lang.info.iso
   }
})
`

And then, we can change the language of entire components trought the selector.

### Proposed solution
I propose to add a new key in each locale, called **info** for example. This key will contain more information about that locale.
Then, the developer can use that information for use in the app.

**Comment by KaelWD** [comment]
The're already ISO 639-1, what else do you want to add?

**Comment by damvaz** [comment]
I want add ISO 639-2 B, because some apps needs 3 chars of language codes,
not 2.
