### ISSUE TITLE
[Feature Request] v-dialog: Add hook for on dismiss event

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [vuetifyjs/vuetify#6807]
### Problem to solve
There is a built in 'click outside of the dialog to dismiss' feature, but there is no way to track when the dialog gets dismissed.
I want to be able to trigger certain events when a dialog is dismissed by clicking outside of the dialog.

### Proposed solution
Add an additional prop `onDismiss` that takes a function to be executed when the user dismisses the dialog by clicking outside of the dialog.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
