### ISSUE TITLE
[Bug Report] Test of VOverflowBtn not correct

### ISSUE THREAD

**Issue by borisdayma** [vuetifyjs/vuetify#6810]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.10
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.75
**OS:** Windows 10

### Steps to reproduce
Pull request #6797 was merged, however an error was introduced: see line 41 of VOverflowBtn.spec.ts in [pull request diff](https://github.com/vuetifyjs/vuetify/pull/6797/files#diff-64044043e05e94bd56eb1ad0a8a69567R41).

### Expected Behavior
The test "segmented - should warn when item has no callback" should be executed switching from one item with callback to one item without as previously.

### Actual Behavior
Both items have no callback and the warning is tipped. However, this is an easier test than when switching between 2 items.

### Reproduction Link
<a href="https://github.com/borisdayma/vuetify/tree/tests/VOverflowBtn" target="_blank">https://github.com/borisdayma/vuetify/tree/tests/VOverflowBtn</a>

### Other comments
When simply changing back first item to `{ text: 'Hello', callback: () => {} }`, the test does not pass.

**Comment by MajesticPotatoe** [comment]
Unfortunately not taking bug reports for alpha builds at this time.
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
