### ISSUE TITLE
[Bug Report] Toolbar side-icon incorrect margin in RTL direction

### ISSUE THREAD

**Issue by MohamedSallam-VG** [vuetifyjs/vuetify#6819]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Linux x86_64

### Steps to reproduce
Open the link, remove [dir="rtl"] attribute and check the margin difference between RTL and LTR toolbar-side-icon and first child

### Expected Behavior
RTL margin should be similar to LTR margin but in reverse direction

### Actual Behavior
no margin exists

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZPwmyV" target="_blank">https://codepen.io/anon/pen/ZPwmyV</a>

**Comment by MajesticPotatoe** [comment]
This is resolved in 2.0 in which we are providing full rtl support.
eg: [Kitchen Toolbars](https://kitchen.vuetifyjs.com/Toolbars)
Toggle rtl with button in the top right.
