### ISSUE TITLE
Page structure does not recognize dynamically added components

### ISSUE THREAD

**Issue by clintonyeb** [vuetifyjs/vuetify#682]
I have this page layout:

```
<template>
  <div id="app">
    <router-view name="sideBar"></router-view>
    <router-view name="toolBar"></router-view>
    <main>
      <v-container fluid>
        <router-view></router-view>
      </v-container>
    </main>
    <v-snackbar :timeout="snackbar.timeout" success :top="snackbar.top" :bottom="snackbar.bottom" :right="snackbar.right" :left="snackbar.left" :multi-line="snackbar.multiline" :vertical="snackbar.vertical" v-model="snackbar.shown">
      {{ snackbar.text }}
      <v-btn flat class="pink--text" @click.native="snackbar.shown = false">Close</v-btn>
    </v-snackbar>
  </div>
</template>
```

Both the ***sidebar*** and the **toolbar** are determined at run time. This is so, I can have login and registration pages without a sidebar and a toolbar.

On pages that do have the sidebar and the toolbar, the main content is not able to recognize the presence of them and hence is placed under the sidebar and toolbar making  the content invincible. 

How do I get this to work? Thanks

**Comment by johnleider** [comment]
Please post an applicable codepen demonstrating the issue you are having.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
