### ISSUE TITLE
[Feature Request] Pass updated value to v-edit-dialog save event

### ISSUE THREAD

**Issue by nickhall** [vuetifyjs/vuetify#6821]
### Problem to solve
I want to send updated data to an API when saving through the v-edit-dialog. Currently a save event is available, but there is no way to access the isolated updated item.

Similar issues are discussed here: https://github.com/vuetifyjs/vuetify/issues/5828

### Proposed solution
Pass the updated data table entry to the save callback.

**Comment by Freeesia** [comment]
I want the same feature.
But, if the updated data is passed, the original data may not be specified.
So, I want you to pass the value of before update too to determine which value has been changed.

**Comment by lrossy** [comment]
Not the best solution but it may help you if you want to expand on it, you can pass a function as a parameter to save:

			<template v-slot:[`item.field`]="props">
				<v-edit-dialog
					:return-value.sync="props.item.field"
					large
					@save="() => save(props.item)"
					@cancel="cancel"
					@open="open"
					@close="close"
				>

If you want to get fancy, on open you can save the original value and then check if its changed. Hope this helps!
