### ISSUE TITLE
[Bug Report] Using List Tile in scoped slot doesn't work for select/autocomplete

### ISSUE THREAD

**Issue by tomhuntley** [vuetifyjs/vuetify#6824]
### Versions and Environment
**Vuetify:** 1.5.7
**Last working version:** 1.4.0
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
Add an item slot into a v-select or v-autocomplete that uses v-list-tile. 

````
<template v-slot:item="data">
    <v-list-tile>
      <v-list-tile-title>
        {{data.item.API}}
      </v-list-tile-title>
    </v-list-tile>
  </template>
````

### Expected Behavior
The selection should work as it does when using the default slot.

### Actual Behavior
The selection does not work at all.

### Reproduction Link
<a href="https://codepen.io/huntleth/pen/RddQQm" target="_blank">https://codepen.io/huntleth/pen/RddQQm</a>

**Comment by MajesticPotatoe** [comment]
you need to bind the v-list-tile
`<v-list-tile v-bind="data.tile.props" v-on="data.tile.on">`

[https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots)
