### ISSUE TITLE
[Bug Report] Breadcrumb Docs

### ISSUE THREAD

**Issue by jlommori** [vuetifyjs/vuetify#6829]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.5.21
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.13.4

### Steps to reproduce
Breadcrumbs docs, https://vuetifyjs.com/en/components/breadcrumbs, reference the "old" style slots `v-slot:item="props"`.

### Expected Behavior
For the docs example to work in the current version.

### Actual Behavior
When `v-slot:item="props"` is replaced with `slot="item" slot-scope="props"` everything works as expected. Took a bit to figure this out and would be helpful if the docs were updated accordingly.

### Reproduction Link
<a href="https://codepen.io/jlommori/pen/OqGNpY?editors=1111" target="_blank">https://codepen.io/jlommori/pen/OqGNpY?editors=1111</a>

**Comment by MajesticPotatoe** [comment]
in order to use new slot syntax, you need to be on vue 2.6+
