### ISSUE TITLE
After FullScreen Dialog closes, body is not scrollable

### ISSUE THREAD

**Issue by giray123** [vuetifyjs/vuetify#683]
This is also the case on the Documentation:
[Documentation](https://vuetifyjs.com/components/dialogs)

**Comment by johnleider** [comment]
While this is a bug, and it has been fixed (not released yet), can I ask. Why did you choose to not use the provided boilerplate when submitting an issue?

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by giray123** [comment]
You are right. Sorry for the mis-info.

**Comment by ghprod** [comment]
+1
