### ISSUE TITLE
[Bug Report] VCard raised prop not working

### ISSUE THREAD

**Issue by skwalgit** [vuetifyjs/vuetify#6832]
### Versions and Environment
**Vuetify:** 1.5.7
**Last working version:** 1.1.17
**Vue:** 2.6.9
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
1. Create a Vue Instance with Vuetify
2. Use VCard component with raised prop

### Expected Behavior
The VCard should have a higher level of elevation

### Actual Behavior
Nothing happens even if you add a value to the prop

### Reproduction Link
<a href="https://codepen.io/anon/pen/mogWNj" target="_blank">https://codepen.io/anon/pen/mogWNj</a>

### Other comments
I hope it's not deprecated cause it's still in the documentation

**Comment by KaelWD** [comment]
Broken in v1.3.4: 737d8d7b5f6abda557cc8a9aac89e91cb8610189

**Comment by johnleider** [comment]
resolved in v2.0 https://codepen.io/johnjleider/pen/XLQByw
