### ISSUE TITLE
[Bug Report] Starter template

### ISSUE THREAD

**Issue by MichaelPavlov** [vuetifyjs/vuetify#6834]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.10
**Last working version:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 7

### Steps to reproduce
Just open starter template https://template.vuetifyjs.com/ and point library script to 2.0.0-alpha.10 distr 
https://cdn.jsdelivr.net/npm/vuetify/vuetify@2.0.0-alpha.10/dist/vuetify.js

### Expected Behavior
Should start without JS exception

### Actual Behavior
JS exception in console

### Reproduction Link
<a href="https://codepen.io/MichaelPavlov/pen/qvwjoz" target="_blank">https://codepen.io/MichaelPavlov/pen/qvwjoz</a>

**Comment by KaelWD** [comment]
The codepen template will not be updated until 2.0 is released.

**Comment by MichaelPavlov** [comment]
It is not a codepen issue. See console messages. The same JS exception u can get just trying starter template in raw html file with local browser.

![image](https://user-images.githubusercontent.com/47882490/54984984-0accff00-4fc1-11e9-953f-eeee20b4e684.png)

![image](https://user-images.githubusercontent.com/47882490/54984773-a27e1d80-4fc0-11e9-97bf-8241e7c0d571.png)
