### ISSUE TITLE
[Feature Request] Add dynamic props as data

### ISSUE THREAD

**Issue by woodgates** [vuetifyjs/vuetify#6839]
### Problem to solve
When working with input elements as input text, selects, switch, etc. the states of them changes when user interacts: 
- they change to loading states
- they get blocked and unblocked.
- they change of class if corresponding.
- we have the add/take out text.

Working with props is great for one time sets but vue can get a bit complex when props change. Also the code gets cumberstone when creating a large form. for example:
```
<v-switch
name="yesno"
ref="yesno"
v-model="mydata.yesno"
:loading="loading.yesno"
:blocked="blocked.yesno"
:class="myclass.yesno"
:error="error.yesno"></v-switch>
```
All this code for each field. Its easy to make a mistake and is very annoying.

### Proposed solution
My solution is to work with a mixin in the v-form. I do not need the mixin but components need to have this props as data.
```
props:{
loading:false
},
data(){
 return{
  showLoading: this.loading
 }
}
```

And the loading state will depend on "showLoading" data instead of "loading" prop.
With this you can change the loading state with a mixin in v-form this way:
```
this.$refs.yesno.showLoading = true // or false if needed
```
and dont need to write all the props.

You cannot do this with props as Vue doesn't recommend to change props programatically.

**Comment by KaelWD** [comment]
```html
<v-switch
  name="yesno"
  v-model="mydata.yesno"
  v-bind="props.yesno"
></v-switch>
```

```js
computed () {
  props () {
    return { // would actually reduce all your other objects into one
      yesno: {
        loading: '',
        blocked: '',
        class: '',
        error: ''
      }
    }
  }
}
```

**Comment by woodgates** [comment]
> ```
> <v-switch
>   name="yesno"
>   v-model="mydata.yesno"
>   v-bind="props.yesno"
> ></v-switch>
> ```
> 
> ```js
> computed () {
>   props () {
>     return { // would actually reduce all your other objects into one
>       yesno: {
>         loading: '',
>         blocked: '',
>         class: '',
>         error: ''
>       }
>     }
>   }
> }
> ```

How can I change the loading state with this.$refs with your solution?
