### ISSUE TITLE
v-tabs-slider wrong size/position after closing drawer

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#684]
I had this bug initially on 0.12.2 but upgrading to 0.12.6 seems to have fixed my bug but the codepen below still has it so something is not quite right

### Steps to reproduce
With desktop screen size
Press the close drawer button

### Versions
Vuetify 0.12.6 (latest on unpkg)
Vue 2.3.3 (latest on unpkg)

### What is expected ?
Slider resizes to match the tab size

### What is actually happening ?
The tab slider indicating item 2 is in the wrong position

### Reproduction Link
https://codepen.io/anon/pen/WONKQP

**Comment by johnleider** [comment]
Please re-open the ticket using the provided issue boilerplate.

**Comment by Christilut** [comment]
Updated

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/weBeaX everything looks right here as of 0.12.7. Let me know if there is something I missed.

**Comment by Christilut** [comment]
It still shows the same problem for me

![image](https://cloud.githubusercontent.com/assets/3471363/26785553/509dbbfc-4a03-11e7-9dc1-cd6fff9d7aa6.png)

**Comment by SteffenDE** [comment]
It seems that this still is an issue or am I doing something wrong?
https://codepen.io/anon/pen/prxzZO

**Comment by johnleider** [comment]
So this has regressed, but for different reasons than the above.
