### ISSUE TITLE
[Bug Report] DataTables not showing actions column

### ISSUE THREAD

**Issue by bajki** [vuetifyjs/vuetify#6840]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.10
**Last working version:** 2.0.0-alpha.7
**Vue:** 2.6.10
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
Not working by  default.

### Expected Behavior
Show actions column..

### Actual Behavior
Nothing.

### Reproduction Link
<a href="https://codepen.io/anon/pen/QoPzNx?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/QoPzNx?&editable=true&editors=101</a>

### Other comments
Hi, why action column doesn't show on table?

**Comment by bajki** [comment]
<template #item.action="props">

needs to be

<template #item.column.action="props">

**Comment by nekosaur** [comment]
In latest 2.0 alpha, use `#item.action` as slot name. If you have any other questions please join us in our [Discord chat room](https://community.vuetifyjs.com)
