### ISSUE TITLE
[Bug Report] Scrolling does not work in IE (11) after dialog is closed

### ISSUE THREAD

**Issue by rubengees** [vuetifyjs/vuetify#6841]
### Versions and Environment
**Vuetify:** 1.5.7
**Last working version:** 1.3.16
**Vue:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
- Serve the project.
- Click the "Show dialog" button.
- Click somewhere.
- Try to scroll.

### Expected Behavior
Scrolling (with the mouse wheel) works like usual after the dialog is closed.

### Actual Behavior
Scrolling does not work. Using the scrollbar is possible though.

### Reproduction Link
<a href="https://github.com/rubengees/vuetify-scroll-ie11" target="_blank">https://github.com/rubengees/vuetify-scroll-ie11</a>

### Other comments
Related to https://github.com/vuetifyjs/vuetify/issues/767

**Comment by kdholt34** [comment]
Same as #6617 

Fix is in pull request #6710
