### ISSUE TITLE
[Bug Report] V-select (Box, Solo, Outline) Menu Opens When Removing a Chip 

### ISSUE THREAD

**Issue by lyonsbp** [vuetifyjs/vuetify#6844]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.9
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. Add items to the select box (box, outline, or solo style)
2. Click outside to close menu
3. Click the "x" remove icon on a chip

### Expected Behavior
Chip is removed without the menu opening.

### Actual Behavior
Chip is removed, but the menu is also opened.

### Reproduction Link
<a href="https://codepen.io/anon/pen/vPwEjZ" target="_blank">https://codepen.io/anon/pen/vPwEjZ</a>

**Comment by TrobbinsForNow** [comment]
@MajesticPotatoe I'm seeing this issue come back up in v2.1.14

**Comment by MajesticPotatoe** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
