### ISSUE TITLE
[Bug Report] Input with VeeValidate not working on first input

### ISSUE THREAD

**Issue by jsinhSolanki** [vuetifyjs/vuetify#6846]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 7

### Steps to reproduce
Type 1 in text field. Erorr won't showup then remove 1 and re-type 1. Error will show up.

### Expected Behavior
Error should shown on first input of invalid character(e.g. 1)

### Actual Behavior
It shows error if i remove and retype it.

### Reproduction Link
<a href="https://jsfiddle.net/jsinh0001/j28fxo5a/1/" target="_blank">https://jsfiddle.net/jsinh0001/j28fxo5a/1/</a>

### Other comments
I want to use veevalidate.

**Comment by KaelWD** [comment]
This is probably a VeeValidate bug. I'll re-open the issue if you can show us not emitting an event or something without the use of extra libraries.

**Comment by jsinhSolanki** [comment]
This works if I use normal <input type="text" /> but not with your component.
