### ISSUE TITLE
[Feature Request] v-btn add text under an icon

### ISSUE THREAD

**Issue by MickaMx** [vuetifyjs/vuetify#6847]
### Problem to solve
Actually we can't add a button with icon and a text underneath

### Proposed solution
Add a props "column" that allow to add element underneath

**Comment by ugurozturk** [comment]
This would be great. We can do it with tabs so why not on btn ?

**Comment by SamuelLaheux** [comment]
Yes it would be great. No news from this feature request ?

**Comment by Coricos** [comment]
An easy workaround I've gone with in the meantime: 

`<v-btn
  text
  outlined
  :class="{'text-none': true, clicked: individual == 'a relative'}"
  style="width: 100%; height: 100%;"
  @click="individual = 'a relative'; page++"
>
  <v-col
    cols="12"
  >
    <v-row
      width="100%"
      style="place-content: center; margin-bottom: 12px;"
    >
      <v-icon
        large
        color="rgb(0, 0, 0, 0.5)"
      >
        mdi-account-child
      </v-icon>
    </v-row>
    <v-row
      width="100%"
      style="place-content: center"
    >
      <span
        class="body-1"
        style="font-weight: bold;"
      >
        a relative
      </span>
    </v-row>
  </v-col>
</v-btn>`

**Comment by Sent1ence** [comment]
This would be really amazing if they can add this props

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
