### ISSUE TITLE
Navigation drawer doesnt work on small screen

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#685]
https://codepen.io/anon/pen/pwoZVJ

It works on a desktop screen

Go into dev tools, set screen size to tablet or phone and press the drawer toggle button. Notice drawer doesnt appear and in the console it shows `true` and immediately it also shows `false`.

**Comment by johnleider** [comment]
When controlling the state of a component that can be closed with a click, such as drawer, menu, or dialog, you must add the ```.stop``` modifier. This stops the click event from propagating up and causing the component to immediately close.
