### ISSUE TITLE
[Bug Report] Image load failed

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#6852]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.5
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

### Steps to reproduce
I receive the image base64 encode from the API server using axios and try to display it on the frontend:

```
<v-img
  :src="myImage"
/>
```

### Expected Behavior
I expect the image to be displayed on the browser

### Actual Behavior
I receive  what this screenshot of the console says:
https://github.com/begueradj/image/blob/master/iii.png

**Comment by moisesfk** [comment]
Anyone fix this?
To reproduction, just access the https://vuetifyjs.com/en/ , sometimes firefox dont load the images.
This behavior is often when I access other links, like "Documentation" and came back to home again.

I'm on firefox 68.0.1 (64-bits)
