### ISSUE TITLE
[Bug Report] Floating elements appearing misaligned when inside another container

### ISSUE THREAD

**Issue by victornpb** [vuetifyjs/vuetify#6854]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.5
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.0

### Steps to reproduce
Create a vuetify app inside a element that is not direct children of <body>

### Expected Behavior
Works just as normal

### Actual Behavior
Menus and floating components are not correctly placed where they should be

### Reproduction Link
<a href="https://codepen.io/anon/pen/YgoQoK" target="_blank">https://codepen.io/anon/pen/YgoQoK</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
