### ISSUE TITLE
[Feature Request] V-Select readonly mode

### ISSUE THREAD

**Issue by i-robert** [vuetifyjs/vuetify#6855]
### Problem to solve
I am looking for the possibility to select the text from an disabled v-select input. 
Something similar to readonly="readonly" attribute in usual inputs. 
Currently the disabled attribute removes the possibility to select the text within the disabled v-select.

### Proposed solution
Add the readonly attribute to v-select that would act like the disabled attribute but keeps the text selectable.

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/55297605-7cf07a00-53ed-11e9-8236-ce8bc74b571a.png)

**Comment by i-robert** [comment]
https://sagalbot.github.io/vue-select/docs/Api/Props.html - here is where I was looking for the props answer. 
I already tried the readonly attribute, but it does not work.
