### ISSUE TITLE
[Feature Request] VSelect - Ability to jump to first item in list using keyboard

### ISSUE THREAD

**Issue by ram33** [vuetifyjs/vuetify#6856]
### Problem to solve
Standard HTML select allow us to jump to particular items in the drop-down by pressing the letters on the keyboard. For example, if we want to select the "United Kingdom" from a list of countries you can start typing the word. Some allow multiple letters to be typed, others just cycle through the first letter pressed.

### Proposed solution
On VSelect's keyDown event we are setting scroll position by calling menu component's changeListIndex (menu-keyable.js line no: 58). However that method is handling only up and down keys by incrementing/decrementing index. We can extend this method to accept index as an optional parameter and then pass it by calculating on VSelect's keydown.

Happy to raise a pull request with above fix, if it makes sense.

**Comment by KaelWD** [comment]
Duplicate of #4853 

I've added an extra highlight so it's more clear what's happening.
