### ISSUE TITLE
[Feature Request] Multiple masks

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#6862]
### Problem to solve
When there are multiple correct inputs. I have an input that needs to be able to take ####-## or ######-##.

Right now, 123456 is displayed as 123456- when I need it to be 1234-56.

### Proposed solution
Implement mask arrays in the same manner as done here: https://github.com/vuejs-tips/vue-the-mask

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0

**Comment by streljk93** [comment]
When we receive the data as asynchronous, we receive their without a mask. (version 2.0 + vue-the-mask)

**Comment by chrisjenx** [comment]
Wait why were masks removed? It's the most useful feature for input fields!

**Comment by cavidz** [comment]
So, there's no way to mask v-text-input anymore?

**Comment by Harm-Nullix** [comment]
There now is a v-mask-input.
This should be reopend imo.
@KaelWD , Do you agree?

**Comment by Harm-Nullix** [comment]
You should be able to do this using a regex as a mask!
https://github.com/vuetifyjs/vuetify/issues/4484#issuecomment-3120340338
