### ISSUE TITLE
[Bug Report] Vertical stepper v-stepper__label is hidden inside horizontal stepper

### ISSUE THREAD

**Issue by MaeseppTarvo** [vuetifyjs/vuetify#6870]
I am using the [Vuetify's vertical stepper][1]. The problem is that the stepper labels are hidden on mobile devices but I couldn't find  any reference from the framework that it should be hidden. Also I haven't added any css to hide them.

[![enter image description here][2]][2]

This is the css that I saw while inspecting the `v-stepper__label`:

    @media only screen and (max-width: 959px) { 
        .v-stepper:not(.v-stepper--vertical) .v-stepper__label { 
            display: none; 
        }
    }
    
Shouldn't it be hidden only on horizontal stepper?

My question is, where the css is coming from? Why it is not happening on Vuetify's example? I am using the latest stable version: **1.5.7**

  [1]: https://vuetifyjs.com/en/components/steppers#vertical-steppers
  [2]: https://i.stack.imgur.com/dj7T9m.png

**Comment by johnleider** [comment]
We need a reproduction outside of your environment to confirm any bugs. Thank you in advance!

**Comment by MaeseppTarvo** [comment]
@johnleider You can see it happening [here](https://codepen.io/anon/pen/xexvjj)

**Comment by HamletLeon** [comment]
I have the same issue right now. What about this change? There's any prop that avoid this?

**Comment by HamletLeon** [comment]
Well. I found a way to avoid (as a fast solution):
```vue
<style>
    @media only screen and (max-width: 959px)
    {
        .ignoreMediaFilter .v-stepper__label {
            display: flex !important;
            margin-left: 15px;
        }
    }
    @media only screen and (min-width: 959px)
    {
        .ignoreMediaFilter .v-stepper__label {
            display: flex !important;
            margin-left: 7px;
        }
    }
</style>
```

**Comment by NegativeDearc** [comment]
+ 1 label not show in mobile device

**Comment by MaeseppTarvo** [comment]
If I created the post I investigated hours and finally understood that it is not a bug but expected behaviour since horizontal stepper is hiding labels on mobile. Now if you put your vertical slider into horizontal, it hides vertical slider's labels also :)

I fixed it by adding this line:

```
<style>
@media only screen and (max-width: 959px) {
  .v-stepper:not(.v-stepper--vertical) .v-stepper__label {
    display: -webkit-box; /* OLD - iOS 6-, Safari 3.1-6 */
    display: -moz-box; /* OLD - Firefox 19- (buggy but mostly works) */
    display: -ms-flexbox; /* TWEENER - IE 10 */
    display: -webkit-flex; /* NEW - Chrome */
    display: flex; /* NEW, Spec - Opera 12.1, Firefox 20+ */
  }
  @media only screen and (max-width: 959px) {
    .v-stepper:not(.v-stepper--vertical) .v-stepper__step__step {
      margin-right: 12px;
    }
  }
}
</style>
```
