### ISSUE TITLE
[Feature Request] V-Select item-value to support key value specification  

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#6871]
### Problem to solve
Say you have a `v-select` that gets populated by the crud service.

The lookup will look as follow:

`materials: [{id: 1, name: "steel"}, {id: 2, name: "glass"}, {id: 3, name: "wood"}]`

I want the v-model of the `v-select` component to look as follow after selection:
`[{id: 1}, {id: 3}]`.

Currently with item-value one can only specify primitives. So best case it would look like this: 
`[1, 3]`. 

### Proposed solution
For v-select which can have a property something like `item-provide-key` which is a boolean.

Example 
```
<v-select :items="materialsLookup" item-text="name" item-value="id" item-provide-key v-model="selectedMaterials"></v-select>
```
`selectedMaterials` will have something like this `[{id: 1}, {id: 3}]`.
Without property `item-provide-key`, `selectedMaterials` will look like as usual [1,3] .

**Comment by ibrahimBeladi** [comment]
You can just the javascript's map function.

**Comment by KaelWD** [comment]
I'd recommend just using `return-object`, but if that isn't suitable for whatever reason then you should do what @ibrahimBeladi suggested and just map the result in a computed property. This request is fairly niche and does not warrant its own prop.
