### ISSUE TITLE
[Feature Request] Add property to overflow button and select so you can hide dropdown arrows 

### ISSUE THREAD

**Issue by YuqiaoS** [vuetifyjs/vuetify#6874]
### Problem to solve
Dropdown arrows aren't desired in some cases. We could use v-menu and implement the functionality, but we should use a button or select to indicate input values.

### Proposed solution
Add a property to those components, maybe named `hide-arrow-icon`.

**Comment by ibrahimBeladi** [comment]
You can simply use `append-icon=""`

**Comment by KaelWD** [comment]
:point_up:
