### ISSUE TITLE
[Bug Report] Menu/Tooltip attach with absolute positioning does not work

### ISSUE THREAD

**Issue by aaronrosenthal** [vuetifyjs/vuetify#6877]
### Versions and Environment
**Vuetify:** 1.4.0
**Last working version:** 1.3.16
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
Configure v-tooltip with attach, absolute, position-x, and position-y props to externally attach content to an absolute position. Do not use an activator slot (use v-model to manually activate tooltip).

### Expected Behavior
This worked in my project as expected up to and including v1.3.16. Starting with v1.4.0, this does not work (including latest alpha release), preventing me from upgrading to latest versions.

### Actual Behavior
The position-x and position-y props appear to have no effect in this configuration.

### Reproduction Link
<a href="https://codepen.io/AaroneusMaximus/pen/QPLovX" target="_blank">https://codepen.io/AaroneusMaximus/pen/QPLovX</a>

**Comment by wolf991** [comment]
Any updated on this? I'm having the same problem with v-menu.

**Comment by lokanathchandrareddy** [comment]
Any update? facing the same problem. position-x seems to work, but not the position-y.

**Comment by usb248** [comment]
I confirm, position-y is buggy

**Comment by buryndin** [comment]
It works without attach and absolute: https://codepen.io/buryndin/pen/NWxPrOx

**Comment by lmindwarel** [comment]
Same problem here, any news on this issue ?

**Comment by emiliobongiorno** [comment]
This issue is still existing. If you see the code of @buryndin it is not working as expected (https://codepen.io/buryndin/pen/NWxPrOx)

**Comment by victororlyk** [comment]
any news on this issue? pretty annoying one.

**Comment by euberdeveloper** [comment]
Any new?
