### ISSUE TITLE
Change focus on the Select control

### ISSUE THREAD

**Issue by Kraigo** [vuetifyjs/vuetify#688]
When I have 2 select control. I click on the first select (bottom) then I click on the second control (upper).
It turns out that the first does not close. Expecting only one can be active and opened.

![screenshot 12](https://cloud.githubusercontent.com/assets/8700639/26761412/2a943e80-4937-11e7-94cb-537c9befb6b0.png)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Kraigo** [comment]
I can provide example on the Codepen.
https://codepen.io/Kraigo/pen/OgJYBO

First click on the 'Colors' select, then click on the 'Animals' select.
Expecting "Colors" list is closed, but will see 2 active.
