### ISSUE TITLE
[Feature Request] CLDR json

### ISSUE THREAD

**Issue by mhf-ir** [vuetifyjs/vuetify#6881]
### Problem to solve
Add standard CLDR Data for i18n for many usecases

### Proposed solution
For example if locale select `fa-IR` cldr json for get `first-day-of-week`  see:
https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/weekData.json#L130
As saturday.

And other stuff.

You could just add build process to extract useful data from cldr repository.
https://github.com/unicode-cldr/cldr-json

**Comment by KaelWD** [comment]
https://github.com/tc39/ecma402/issues/6

What is "other stuff"? Vague requests usually never get implemented.

**Comment by mhf-ir** [comment]
Here some of useful implementation:
Multiple calendar step for many countries:
Demo: https://www.time.ir/
![Screenshot from 2019-03-31 21-43-48](https://user-images.githubusercontent.com/1172526/55292305-38210f00-53fe-11e9-922c-d1b0fe73e5a4.png)
In Iran we use three calendar.
As CLDR data many countries has more than one calendars.
https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/calendarPreferenceData.json
statistics: https://mhf-ir.github.io/i18nplease/

**Comment by nekosaur** [comment]
I am still not sure exactly what you are requesting with this issue.

I don't think it's very likely that we will implement some mechanism of pulling relevant data from CLDR directly. If something gets implemented in JS like the spec Kael linked to, that's another story. It's up to the developer to use appropriate values with the props we expose.

**Comment by mhf-ir** [comment]
1. First of all calendar is the variable and depend per locale and each locale may have several calendar system that listed on CLDR data.
2. Each locale need to support calendar usage order by for example in Iran we use `persian gregorian islamic islamic-civil islamic-tbla` order or in Japan they use `gregorian japanese` and other stuff.
3. Depend of calendar and support fully i18n we need to know about more stuff on i18n data that stored and support in CLDR community so i think we better to use require ones.
For exampel angular team also use this methology:
https://github.com/angular/angular/blob/master/aio/content/guide/i18n.md

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
