### ISSUE TITLE
[Bug Report] Push the content left when I use 2 navigation-drawer on right

### ISSUE THREAD

**Issue by forest1102** [vuetifyjs/vuetify#6883]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. Tap the right side icon in the toolbar
2. you see the card content is pushed to left

### Expected Behavior
I want the content to stay the same

### Actual Behavior
The content is pushed to left

### Reproduction Link
<a href="https://codepen.io/forest1102/pen/PgoOpa" target="_blank">https://codepen.io/forest1102/pen/PgoOpa</a>

**Comment by johnleider** [comment]
The second drawer is temporary and doesn't need to update the applications sizing

https://codepen.io/johnjleider/pen/qwBYNo
