### ISSUE TITLE
[Feature Request] Missing doc on v-toolbar prop "manual-scroll"

### ISSUE THREAD

**Issue by YuqiaoS** [vuetifyjs/vuetify#6884]
### Problem to solve
No doc on how to use the property of manual-scroll. I want to manually hide the toolbar.

Also it seems that the scrollToolbarOffScreen prop is deprecated in the source code. Maybe indicate that in the doc too.
### Proposed solution
Please explain how to use it.

**Comment by johnleider** [comment]
This has been squared away on `next`.

**Comment by YuqiaoS** [comment]
Could you point me to the new doc? It seems the its been taken out of the toolbar entirely.

Also I'd like to know how to achieve this currently. Should I simply to change the style?

**Comment by MajesticPotatoe** [comment]
[https://next.vuetifyjs.com/en/components/app-bars](https://next.vuetifyjs.com/en/components/app-bars)

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
