### ISSUE TITLE
[Bug Report] v-list-tile-avatar not round

### ISSUE THREAD

**Issue by Sevyls** [vuetifyjs/vuetify#6885]
### Versions and Environment
**Vuetify:** 1.5.8
**Last working version:** 1.2.3
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
Make a list tile with an avatar
Use an icon or sizing where the icon is less wide than high

### Expected Behavior
List tile avatar icons should be round and equally in size and height

### Actual Behavior
List tile avatar icons are eliptical in form, height is correct but width is defaulted to the font size

### Reproduction Link
<a href="https://jsfiddle.net/sevyls/o3gr79L5/22/" target="_blank">https://jsfiddle.net/sevyls/o3gr79L5/22/</a>

### Other comments
I recently upgraded from Vue.js 2.5 and Vuetify 1.2 to the most current versions.

**Comment by KaelWD** [comment]
Don't use `right` on the icon.

**Comment by Sevyls** [comment]
Thank you
