### ISSUE TITLE
[Feature Request] Documentation update for transpileDependencies

### ISSUE THREAD

**Issue by Aymkdn** [vuetifyjs/vuetify#6887]
### Problem to solve
The Vue team fixed the issue reported in https://github.com/vuetifyjs/vuetify/issues/5825 and now `transpileDependencies` should just have `vuetify` and not some regexp.

### Proposed solution
Replace [this section of the documentation](https://vuetifyjs.com/en/getting-started/quick-start#ie11-safari-9-support) that says : 
```javascript
module.exports = {
  transpileDependencies:[/node_modules[/\\\\]vuetify[/\\\\]/]
}
```
With : 
```javascript
module.exports = {
  transpileDependencies:["vuetify"]
}
```

**Comment by MajesticPotatoe** [comment]
Resolved in 873e353
