### ISSUE TITLE
Opening a dialog in callback from third party library

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#689]
I'm using the Quill editor and I want to open a dialog when pressing the "insert link" image.
Problem is that the dialog opens and immediately closes. I'm sure this is due to the stopPropagation thing, however the callback from Quill doesnt give me the original event so I can't call `event.stopPropagation` there. This codepen shows the problem: https://codepen.io/anon/pen/VWwNJZ
I also dont have access to the button so doing `@click.stop` is also not possible.

I tried, as a major workaround, to put a v-btn inside the dialog activator slot and doing 
`this.$refs.modalImagesOpenButton.$el.click()`
but the problem remains the same.

Any ideas how to handle this? Workaround would be fine too :)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
