### ISSUE TITLE
[Feature Request] Allow Multiple Chips with the same name in a v-combobox

### ISSUE THREAD

**Issue by anthonycheng12** [vuetifyjs/vuetify#6891]
### Problem to solve
Allows you to have the same chip with the same keyword within the combobox. An example is 1 I pulled of your website at 
https://codepen.io/anon/pen/eomrKW?&editable=true&editors=101
The problem is if you click Foo then type Foo again to create another chip then it will delete both chips from the combobox.

### Proposed solution
Create a prop to allow for the combobox to hold identical data

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

This is already possible when using object items as long as their values differ.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
