### ISSUE TITLE
[Feature Request] Allow aliasing of Font Awesome SVG component name

### ISSUE THREAD

**Issue by GregPeden** [vuetifyjs/vuetify#6893]
### Problem to solve
Applicable to v2 only...

In order to use SVG version of Font Awesome v5 with Vuetify (with 'iconfont' set to "faSvg"), the component must be bound globally as "font-awesome-icon" or "FontAwesomeIcon". Many people use a shorthand like "fa-i" or "FaI" since it is used frequently in many applications and "font-awesome-icon" is somewhat verbose. Additionally icon packs historically have recommended use of the ```<i>``` tag for class-based implementations and <fa-i> is a natural extension of that.

### Proposed solution
Allow the component name to be defined as part of the options setting. For example:

```js
Vue.use(Vuetify, {
    icons: {
        iconfont: 'faSvg',
        component: 'fa-i'
    }
});
```

**Comment by KaelWD** [comment]
Is that a problem? You can register the same component with different names if you want a shorter one to use yourself.
