### ISSUE TITLE
[Bug Report] v-menu closes when trying to prevent it from closing by a computed property 

### ISSUE THREAD

**Issue by BigsonLvrocha** [vuetifyjs/vuetify#6898]
### Versions and Environment
**Vuetify:** 1.5.8
**Vue:** 2.6.10
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 7

### Steps to reproduce
* add data flag representing the desired state of menu
* add data flag to set if should prevent v-menu from closing
* pass computed property to v-model
    * getter returns the desired state
    * setter checks if prevent flag isn't set before setting state flag to false
* open menu
* click outside

### Expected Behavior
The menu should not close because v-model's getter is still returning true

### Actual Behavior
The menu ignores v-model's getter and still closes, now any attempt to reopen the menu will fail until setting the flag back to false again

### Reproduction Link
<a href="https://codepen.io/BigsonLvrocha/pen/BENJRM" target="_blank">https://codepen.io/BigsonLvrocha/pen/BENJRM</a>

### Other comments
Could make a workaround by setting the property `:close-on-click="!preventClosing"`, but still don't know why the menu closes even when v-model is true

**Comment by blalan05** [comment]
This is expected behavior. You found the correct "workaround".

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by BigsonLvrocha** [comment]
If it is expected behaviour, then it would be nice for that to be noted in the docs... maybe change from `Designates if menu should close on outside-activator click` to `Designates if menu should close on outside-activator click. Will close even when value is true`
