### ISSUE TITLE
Opening a dialog in callback from third party library

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#690]
### Steps to reproduce
I'm using the Quill editor and I want to open a dialog when pressing the "insert link" image.
Problem is that the dialog opens and immediately closes. I'm sure this is due to the stopPropagation thing, however the callback from Quill doesnt give me the original event so I can't call `event.stopPropagation` there. This codepen shows the problem:
I also dont have access to the button so doing `@click.stop` is not possible.

I tried, as a major workaround, to put a v-btn inside the dialog activator slot and doing 
`this.$refs.modalImagesOpenButton.$el.click()`
but the problem remains the same.

I'm not sure how to solve this, any ideas?

I can make a larger example using the actual Quill editor but I think the codepen below illustrates the problem.

### Versions
vuetify 0.12.6
vue 2.3.3

### What is expected ?
Dialog opens and stays open

### What is actually happening ?
Dialog opens and immediately closes

### Reproduction Link
Simplified example. Normally the button would be dynamically inserted into the DOM by Quill.
https://codepen.io/anon/pen/VWwNJZ

**Comment by johnleider** [comment]
You have to add the ```.stop``` modifier to your @click declaration. This is outlined in the docs when controlling dialog's outside of their activator slot.

**Comment by Christilut** [comment]
Yes but the problem is that Quill dynamically inserts an `input` into the DOM. So I can't add `.stop` to it.
I'm not sure how I can work around that right now.

**Comment by johnleider** [comment]
Can you provide an answer with Quill integrated? I'm afraid I can't debug otherwise.

**Comment by Christilut** [comment]
https://codepen.io/anon/pen/vZEJBz

Just click the Image button in the toolbar

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/owgedQ?editors=1111

**Comment by Christilut** [comment]
Awesome, thanks!
