### ISSUE TITLE
[Feature Request] Combobox Autocomplete does not support having chips with the same key word 

### ISSUE THREAD

**Issue by anthonycheng12** [vuetifyjs/vuetify#6902]
### Problem to solve
In the autocomplete say I have an API that will return different users informations then the combobox autocomplete using the search-input:sync does not show all the names. For example I am searching up Brian with my API and there are like 10 Brian's then how do I have all 10 Brian's show up on the autocomplete because their names are all Brian and combobox doesn't support having the same keyword. 

### Proposed solution
Have a prop to allow identical items in a combobox

**Comment by jacekkarczmarczyk** [comment]
@anthonycheng12 How is that different from https://github.com/vuetifyjs/vuetify/issues/6891?

**Comment by KaelWD** [comment]
It works if each item has a unique ID: https://codepen.io/anon/pen/arxEwM

Duplicate of #4633
