### ISSUE TITLE
[Bug Report] Can not mutate v-model from TreeView

### ISSUE THREAD

**Issue by mro95** [vuetifyjs/vuetify#6903]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Select all
2. Try to unselect via the X icon in v-chip (right sidebar)

### Expected Behavior
One (or more) of the selected items will be removed from the selected array

### Actual Behavior
One of the items was indeed removed but is inserted again.

### Reproduction Link
<a href="https://codepen.io/anon/pen/VNvYLW" target="_blank">https://codepen.io/anon/pen/VNvYLW</a>

### Other comments
This only happen when you select a parent node. It works when you only select child nodes.

**Comment by mro95** [comment]
A quick fix for me is to use this instead of `v-model`:
```
v-bind:value="selected"
v-on:input="selected = $event"
```

The downside is that is brakes the sync to the `v-treeview`

**Comment by aebrs** [comment]
Have you been able to use this component as a normal data tree, with insert, update and delete?
We have used it with async loading, as mentioned in vuetify example, but updated node and updating deleted parent node have been or has seems impossible to us. Have you any Idea?

**Comment by aebrs** [comment]
https://stackoverflow.com/questions/55572650/how-to-force-a-vuetify-treeview-node-reload

**Comment by sh7dm** [comment]
fixed in 2ecec4a
