### ISSUE TITLE
[Bug Report] Textfield dynamic mask with weird behavior

### ISSUE THREAD

**Issue by guiquintelas** [vuetifyjs/vuetify#6904]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
- Fill the textfield 
- Click away

### Expected Behavior
Textfield masked value to be equal to displayed maked value.

### Actual Behavior
- When the textfield is full it display the right mask, but the returned value dont. 
- When clicking away, it shouldn't clear half of th displayed value.

### Reproduction Link
<a href="https://codepen.io/guiquintelas/pen/xewVBm" target="_blank">https://codepen.io/guiquintelas/pen/xewVBm</a>

### Other comments
This only occurs if the **return-masked-value** prop is true

Fixing this would provide an alternative to #6862

**Comment by jacekkarczmarczyk** [comment]
masks have been removed in 2.0
