### ISSUE TITLE
[Bug Report] Incorrect v-menu full-width value calculation

### ISSUE THREAD

**Issue by shmigandrew** [vuetifyjs/vuetify#6906]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.13.6

### Steps to reproduce
Codepen example contains a buggy piece of code and also a working version.

### Expected Behavior
Codepen example contains a buggy piece of code and also a working version.

### Actual Behavior
Codepen example contains a buggy piece of code and also a working version.

### Reproduction Link
<a href="https://codepen.io/ashmig/pen/XQmYYZ?editors=1010" target="_blank">https://codepen.io/ashmig/pen/XQmYYZ?editors=1010</a>

**Comment by KaelWD** [comment]
`getActivator` was preferring the event, which is bound to the smaller `<input>` element. 

```vue
<template>
  <v-container>
    <v-menu
      offset-y
      bottom
      max-height="500"
      full-width
      :close-on-content-click="false"
    >
      <template v-slot:activator="{ on }">
        <v-text-field
          solo
          hide-details
          label="Расширенный поиск..."
          class="dsp_dense_input"
          v-on="on"
        ></v-text-field>
      </template>
      <v-card>
        <v-card-text></v-card-text>
      </v-card>
    </v-menu>
  </v-container>
</template>
```

**Comment by KaelWD** [comment]
See #8647

**Comment by usb248** [comment]
still a problem in last version .....so buggy
![image](https://user-images.githubusercontent.com/7659927/97152994-0dca3b80-1772-11eb-9d8c-47a5aa0c1187.png)

**Comment by johnleider** [comment]
@usb248 We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
