### ISSUE TITLE
[Bug Report] Breadcrumb produces node mismatch on nuxt 

### ISSUE THREAD

**Issue by ARMGAMES** [vuetifyjs/vuetify#6908]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
Same code that i done at codepen gives me "Mismatching childNodes vs. VNodes" error at nuxt SSR rendering only when i am using v-breadcrumbs

### Expected Behavior
-

### Actual Behavior
![Console Error](https://i.imgur.com/r5BMHeo.png)

### Reproduction Link
<a href="https://codepen.io/SLIpros/pen/ZZbgZQ" target="_blank">https://codepen.io/SLIpros/pen/ZZbgZQ</a>

**Comment by KaelWD** [comment]
Works here: https://codesandbox.io/s/k20wz0096v

You're probably changing data differently on the client side: https://ssr.vuejs.org/guide/universal.html

**Comment by ARMGAMES** [comment]
This reproduce my issue - https://codesandbox.io/s/mjkw3r44ny

I am using plugin "router.js" to update page breadcrumbs dynamically after page load/switch.
router.js call action "updateRouter", from it i am searching breadcrumbs for current page and call "updateBreadcrumbs" mutation.

![2019-04-04_16-24-40](https://user-images.githubusercontent.com/20094067/55559380-c0512e00-56f6-11e9-9911-3b0bf1c36ca7.png)

**Comment by KaelWD** [comment]
This isn't related to vuetify. 

You only have one on the server:
![image](https://user-images.githubusercontent.com/16421948/55559578-3cb93080-573a-11e9-90af-c61ed8fbf012.png)
Then three on the client:
![image](https://user-images.githubusercontent.com/16421948/55559605-4773c580-573a-11e9-9796-6dbd77d240d8.png)
