### ISSUE TITLE
'Select all' checkbox is missing from table head

### ISSUE THREAD

**Issue by kristandre** [vuetifyjs/vuetify#691]
Hi. Thank you for creating and maintaining this awesome repository!

I'm having some issues with the "Selectable rows" data table in my application and noticed that the problem is present on the [documentation](https://vuetifyjs.com/components/data-tables) page also.

### Steps to reproduce
1. A clean Webpack Quick Start install: `vue init vuetifyjs/webpack`
2. Create a [#2 Selectable rows](https://github.com/vuetifyjs/docs/blob/master/examples/tables/2.vue) data table

### Versions
Vue@2.3.3
Vuetify@0.12.6

### What is expected ?
The first table header should be a 'select all' checkbox.

### What is actually happening ?
The first table header is instead the first custom data header (which should be in the second column).

Here is a picture from the [documentation](https://vuetifyjs.com/components/data-tables). As you can see the 'Select all' checkbox is missing from the table head which causes the other table headers to be misaligned by one column to the left.

![image](https://cloud.githubusercontent.com/assets/6992505/26763050/7f322a3c-494c-11e7-8809-df65daeb6dd3.png)

**Comment by kristandre** [comment]
https://codepen.io/anon/pen/JJjgKv

**Comment by johnleider** [comment]
This is just do to the comparison that was being done. Until next release you can just assign select-all to anything and it will show. ```select-all="true"``` for example.
