### ISSUE TITLE
[Bug Report] Use Cleave.js for mask Number 

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#6910]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 7

### Steps to reproduce
input Number , input last symbol as letter

### Expected Behavior
data in text field without letters

### Actual Behavior
letters  always is present 

### Reproduction Link
<a href="https://jsfiddle.net/L1e87twd/" target="_blank">https://jsfiddle.net/L1e87twd/</a>

### Other comments
letters saved only with vuetify

**Comment by KaelWD** [comment]
https://jsfiddle.net/j7u4rwkv/

**Comment by skortabeast** [comment]
@KaelWD  lol
look vuetify v-text-field  it's not works , problem only with vuetify!

**Comment by KaelWD** [comment]
It has the exact same behaviour without vuetify.

**Comment by skortabeast** [comment]
@KaelWD  see scr
![image](https://user-images.githubusercontent.com/10978770/55534924-2745f700-56a5-11e9-8d8d-84cdaac2a526.png)

**Comment by KaelWD** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/16421948/55540166-1e3d4000-570e-11e9-9a52-7a0bc5d65868.png)

Firefox:
![image](https://user-images.githubusercontent.com/16421948/55540194-357c2d80-570e-11e9-8001-dd14013d5176.png)

Chrome w/o vuetify:
![image](https://user-images.githubusercontent.com/16421948/55540238-4d53b180-570e-11e9-9cc4-785c7a24b1b0.png)

Firefox w/o vuetify:
![image](https://user-images.githubusercontent.com/16421948/55540260-58a6dd00-570e-11e9-95bd-af219f3d55c6.png)

Cleave is broken, this has nothing to do with us.
