### ISSUE TITLE
[Bug Report] can't set heading-font-family different to body-font-family

### ISSUE THREAD

**Issue by sac-mg** [vuetifyjs/vuetify#6912]
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Firefox 63.0, Google Chrome
**OS:** Ubuntu undefined

#### Super basic Vue app, To run it, as every other basic Vue project, after following Vuetify's instructions https://vuetifyjs.com/en/style/theme:  
- vue create projectName  (no css pre-processors)
- add vuetify
- create a main.styl file
- add dependencies (stylus, stylus-loader)
- npm run serve
- localhost:8080

### Expected Behavior
To be able to have heading and body fonts with the different defined fonts. As it is explained by running the demo app

### Actual Behavior
$body-font-family overwrites everything.

### Reproduction Link
<a href="https://github.com/sac-mg/vuetifyFontIssueReport" target="_blank">https://github.com/sac-mg/vuetifyFontIssueReport</a>

### Other comments
Probably due to line 96:
$heading-font-family := $body-font-family
In: _variables.styl

This maybe related to #3583 in vuetify, https://github.com/vuetifyjs/vuetify/issues/3583

**Comment by KaelWD** [comment]
Simple variables need to be defined *above* the import, then stuff like map_merge below it.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
