### ISSUE TITLE
[Feature Request] [2.0.0] add item to the slot-scope item.column.data-table-expand

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#6918]
### Problem to solve
With the new way to customize data-tables in 2.0.0, it is now possible to customize directly the expansion icon.
But it is not possible to customize this icon depending on the item (row) datas.
For example, I only want to display the icon if the item has a property `item.expandable` true.

### Proposed solution
pass `item` to `item.column.data-table-expand` slot-scope

**Comment by KaelWD** [comment]
- [ ] Ensure all slots have the appropriate data available
- [ ] Fix slot documentation - missing `item.` prefix, incorrect props shown for many

**Comment by nekosaur** [comment]
This should be solved.
