### ISSUE TITLE
Opening a dialog or picker causes the page to shift left

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#692]
### Steps to reproduce

On the docs site open the dialogs demo page and shrink the browser window horizontally until it just causes the cards to start to resize.

Click the button to open the first demo dialog. The page will shift about 20 pixels to the left on open and reset on close. The same behavior occurs on the date picker page as well. 

### Versions

0.12.6

### What is expected ?

The page shouldn't shift left when the dialog is opened.

### What is actually happening ?

The outer page container is most likely compensating for the scrollbar when the dialog is opened. 

### Reproduction Link

https://vuetifyjs.com/components/dialogs
https://vuetifyjs.com/components/pickers

**Comment by johnleider** [comment]
This is the intended behavior, but it should not cause any type of visual disturbance. Could you create a gif showcasing what you are seeing?

**Comment by stoked74** [comment]
Here you go John. The gif is from the docs site but I'm experiencing the same thing 
in my app. 
![dialog gif2](https://cloud.githubusercontent.com/assets/963226/26766135/3e981542-4959-11e7-83a8-73d25d928a66.gif)

**Comment by johnleider** [comment]
Is that browser Chrome on MAC?

**Comment by stoked74** [comment]
Yes sorry. Chrome 58.0.3029.110 (64-bit) on Mac. It also happens in Firefox and Safari.

**Comment by johnleider** [comment]
Can confirm that this is a MAC only issue.

**Comment by Darkside73** [comment]
Maybe same issue (Chrome 58.0.3029.110 64-bit on Linux):
![peek 2017-06-06 14-14](https://cloud.githubusercontent.com/assets/339596/26826658/8229e56e-4ac2-11e7-9651-a17b104befdb.gif)

**Comment by jpodpro** [comment]
i'm seeing this too on the docs site and my app.

**Comment by johnleider** [comment]
@jpodpro There is always a reason. In this particular case, my judgement was wrong. This has been fixed bug not released. In the mean time, a workaround is to put the class ```pr-0``` on the ```body``` element.

**Comment by timothyhahn** [comment]
Just as a heads up, in case anyone else runs into this (and I may be wrong), I believe the workaround is actually to put the class `pr-0` on `html`.

That is what has seemed to work for me, and I believe this is also what the relevant code is attempting to modify: https://github.com/vuetifyjs/vuetify/blob/fbab06bf34337c86bba139206c948f7e8cf0abab/src/mixins/overlayable.js#L51
