### ISSUE TITLE
[Bug Report] v-data-table dublicates v-autocomplete cells while sorting

### ISSUE THREAD

**Issue by StasVolyansky** [vuetifyjs/vuetify#6920]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Windows 10

### Steps to reproduce
1. Create header with v-autocomplete inside.
2. Sort the header (make sure that the header value is equal to v-autocomplete value, otherwise sorting will not be applied)
3. Select item in v-autocomplete

### Expected Behavior
Column is sorted without duplication of value in autocomplete cell.

### Actual Behavior
Cell with autocomplete changes position as the sorting order changed (as expected)
but the autocomplete in cell that appeared on modified position is set to the same value.
As a result: 2 autocompletes with the same value

### Reproduction Link
<a href="https://codepen.io/volyansky/pen/QPyXwG?editors=1010" target="_blank">https://codepen.io/volyansky/pen/QPyXwG?editors=1010</a>

### Other comments
On the provided codepen you just need to select value in autocomplete.

**Comment by jacekkarczmarczyk** [comment]
Use `item-key` https://codepen.io/anon/pen/bPNLMV?editors=1010

**Comment by colighto** [comment]
I've added the item-key here but I still get the same issue
