### ISSUE TITLE
[Bug Report] Text fields prefix issue

### ISSUE THREAD

**Issue by mehrunrasoli** [vuetifyjs/vuetify#6922]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chromium 73.0.3683.75
**OS:** Linux

### Steps to reproduce
Add a "?" question mark to the prefix option of the v-text-field and add some text after the question mark.

### Expected Behavior
The text expected to be on one line.

### Actual Behavior
When you Add the "?" question mark to the prefix, any text after it goes to a new line!
I'm not sure if this is expected behavior.

### Reproduction Link
<a href="https://codepen.io/mehrunrasoli/pen/eoZBqE" target="_blank">https://codepen.io/mehrunrasoli/pen/eoZBqE</a>

**Comment by johnleider** [comment]
Workaround <https://codepen.io/johnjleider/pen/xeOPNm>

**Comment by mehrunrasoli** [comment]
@johnleider Thanks, man!
