### ISSUE TITLE
[Bug Report] Tooltip not displayed when wrapping custom button component

### ISSUE THREAD

**Issue by silvioiannone** [vuetifyjs/vuetify#6927]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
Create a new custom button component and wrap it with a tooltip.

### Expected Behavior
The tooltip should be displayed when hovering the custom component.

### Actual Behavior
The tooltip is not displayed when hovering the custom component.

### Reproduction Link
<a href="https://codepen.io/anon/pen/EJKdaK" target="_blank">https://codepen.io/anon/pen/EJKdaK</a>

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components
