### ISSUE TITLE
[Feature Request] Combobox/Select Multiple with Save Button

### ISSUE THREAD

**Issue by moonsphinx** [vuetifyjs/vuetify#6928]
I would like to add a button at the end of the list of items to close the combobox multiple instead of clicking to the side like it's done. I've tested my application with different users ( most with little to none experience using web applications ) and they seem to have trouble with components like combobox multiple, because they want to close the list of items, but can't find a button. Obviously for us, that's not a problem, but for others with little experience, it's confusing. Is there any possibility to add this small functionality?

This could also be applied to other selects multiple. They choose the items using the checkbox and then, to close the list, they could click on the button at the end of the list.

**Comment by johnleider** [comment]
You can use the **prepend-item** and **append-item** to do this. https://vuetifyjs.com/en/components/selects#prepend-append-item-slots
