### ISSUE TITLE
[Bug Report] Text input field does not respect numbers accordingly

### ISSUE THREAD

**Issue by Fohlen** [vuetifyjs/vuetify#6929]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
It is not possible to copy-paste or exceed numbers that are beyond the min/max. However if you start with 20 and continue typing (e.g 111111) the input will not restrict you from doing so.

### Expected Behavior
It should not allow me to type in larger / smaller numbers than I set up.

### Actual Behavior
It does allow me to do so.

### Reproduction Link
<a href="https://codepen.io/anon/pen/bJpPpd" target="_blank">https://codepen.io/anon/pen/bJpPpd</a>

**Comment by KaelWD** [comment]
Not related to vuetify: https://codepen.io/anon/pen/MRyMJo?editors=1010
