### ISSUE TITLE
Buttons don't display any focus state

### ISSUE THREAD

**Issue by SLaks** [vuetifyjs/vuetify#693]
### Steps to reproduce

Press Tab to focus on any button (eg, open https://vuetifyjs.com/components/buttons and press tab)

### Versions
Current version on https://vuetifyjs.com/components; all platforms

### What is expected ?
Currently-focused button should appear focused (with styles from `btn--light-flat-focused` _et al_).

### What is actually happening ?
There is no visual indication whatsoever of which button is focused.

### Reproduction Link
https://vuetifyjs.com/components/buttons

**Comment by johnleider** [comment]
This has been resolved on dev and will go out with next release.
