### ISSUE TITLE
[Bug Report] v-tab 'show-arrows'-prop doesn't always show arros

### ISSUE THREAD

**Issue by Bbansjkl** [vuetifyjs/vuetify#6931]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 7

### Steps to reproduce
Create a v-tabs component with less items than needed to trigger pagination
add the "show-arrows"-prop

### Expected Behavior
Pagination arrows are always shown, possibly `disabled` if no other items are available

### Actual Behavior
Pagination Arrows only show up if the tab bar can't display all tabs

### Reproduction Link
<a href="https://codepen.io/anon/pen/yrJYJg" target="_blank">https://codepen.io/anon/pen/yrJYJg</a>

### Other comments
Docs in both 1.5.9 and 2.0.0-alpha.12 says:
```
Name                Default   Type
show-arrows         false     boolean
Always show pagination arrows
```
https://next.vuetifyjs.com/en/components/tabs#api  

Not sure if the proper way is to match documentation to implementation, or the other way around.

**Comment by KaelWD** [comment]
It's more to show the arrows on mobile-sized screens too.
