### ISSUE TITLE
[Bug Report] v-tabs bar missing offset on medium(?) viewports to indicate that scrolling is possible 

### ISSUE THREAD

**Issue by Bbansjkl** [vuetifyjs/vuetify#6932]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 7

### Steps to reproduce
1) Create a v-tabs component with more tabs than fit into it  
2) Lower viewport size to <=1263px, e.g. by resizing the window or rendering within an iframe

### Expected Behavior
Offset is shown on the left-hand size

### Actual Behavior
Offset is not displayed

### Reproduction Link
<a href="https://codepen.io/anon/pen/jRrbYy" target="_blank">https://codepen.io/anon/pen/jRrbYy</a>

### Other comments
Also happens in 2.0.0-alpha.12

[Google Material specs](https://material.io/design/components/tabs.html#scrollable-tabs) (ctrl+f -> "Placement"->scroll down) say that "Do: On mobile and desktop, offset the first tab on the left to signal that tabs are scrollable." This is not the case on devices with a medium(?) viewport.  
On larger viewports this is kinda supported, since the left arrow is not displayed while there are no items on the left, but smaller viewports don't show arrows unless the "show-arrows"-prop is provided.

Kinda off-topic: On Desktop the arrows vanish too, which makes scrolling hard on smaller viewports (e.g. when the page is rendered within an iframe on a small resolution, or when the browser window is not maximized). The only way to scroll then is to repeatedly click the last item. This was first discussed in #1789, which was closed in favor of #2530, resulting in the PR #2838, which supposedly made arrows show up on all viewport sizes - was this removed again or is the arrows vanishing on viewports with less than 1264px width a bug and should be covered in a new issue?

**Comment by johnleider** [comment]
The last part should be in a new issue please/ty :)

**Comment by azollai** [comment]
Hi, I just looked into Material Design rules and examples.
It is true, that on offset is needed for the first item, but after scrolling, the tab bar should use the whole width to scroll.
Example:
from https://material.io/components/tabs
Before scroll
![image](https://user-images.githubusercontent.com/17653516/96265821-3742d480-0fc6-11eb-9bc1-00606bef690d.png)
After scroll
![image](https://user-images.githubusercontent.com/17653516/96265869-4590f080-0fc6-11eb-9d99-1beb64242b3e.png)

In Vuetify:
Before scoll
![image](https://user-images.githubusercontent.com/17653516/96265991-6bb69080-0fc6-11eb-9881-f511bbea4c20.png)
After scroll
![image](https://user-images.githubusercontent.com/17653516/96266033-78d37f80-0fc6-11eb-8ade-9404271272ec.png)

This is a very bad user experience. Please fix this.

**Comment by johnleider** [comment]
@azollai We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
