### ISSUE TITLE
[Bug Report] Vuetify a la carte does not work in .vue files

### ISSUE THREAD

**Issue by laurenra7** [vuetifyjs/vuetify#6935]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. Create basic Vue app with Vuetify:

vue create vuetify-alacarte
cd vuetify-alacarte
vue add vuetify

2. Modify generated HelloWorld.vue and simplify it to use some Vuetify buttons, import the VApp and VBtn components according to instructions for importing components into .vue files (see https://vuetifyjs.com/en/framework/a-la-carte#importing-components):

<template>
  <v-app>
    <h2 class="headline font-weight-bold mb-3">Buttons</h2>

    <div>
      <v-btn color="success">Success</v-btn>
      <v-btn color="error">Error</v-btn>
      <v-btn color="warning">Warning</v-btn>
      <v-btn color="info">Info</v-btn>
    </div>
  </v-app>
</template>

<script>
    import {
        VApp,
        VBtn
    } from 'vuetify/lib'
    export default {
        components: {
            VApp,
            VBtn
        }
    }
</script>

<style>
  @import '../../node_modules/vuetify/dist/vuetify.min.css';
</style>

### Expected Behavior
Buttons display.

### Actual Behavior
Error in browser console:

[Vue warn]: Error in render: "TypeError: Cannot read property 'application' of undefined"

found in

---> <VContent>
       <App> at src/App.vue
         <Root>

TypeError: Cannot read property 'application' of undefined
    at VueComponent.styles (VContent.js?549c:17)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4578)
    at Proxy.computedGetter (vue.runtime.esm.js?2b0e:4830)
    at Proxy.render (VContent.js?549c:37)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3542)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at new Watcher (vue.runtime.esm.js?2b0e:4462)
    at mountComponent (vue.runtime.esm.js?2b0e:4067)

Uncaught TypeError: _this.$el.setAttribute is not a function
    at eval (ssr-bootable.js?b57a:24)

### Reproduction Link
<a href="https://github.com/laurenra7/vuetify-alacarte" target="_blank">https://github.com/laurenra7/vuetify-alacarte</a>

### Other comments
I've tried importing components several ways into main.js and they all work. The instructions indicate that I can also import components into the .vue file but this does not work.

**Comment by KaelWD** [comment]
You still need to *use* v-app.

**Comment by laurenra7** [comment]
I _**am**_ using **v-app** which you would have seen if you had followed the code I put in GitHub. You can see the [HelloWorld.vue file here](https://github.com/laurenra7/vuetify-alacarte/blob/master/src/components/HelloWorld.vue).

I'm not sure why you closed this because it is not fixed. It still does not work according to the instructions on the Vuetify web page for [importing components into the .vue file](https://vuetifyjs.com/en/framework/a-la-carte#importing-components).

I spent an inordinate amount of time trying this several ways, following the instructions carefully and providing a sample project so you could easily try it yourself and see that it does not work. I would appreciate your consideration of this valid issue rather than dismissing it without even reviewing it.

Since I reported this issue, I was able to get it to work (sort of) by trying something that was not in the instructions. I put the `import Vue from 'vue'` statement and the `Vue.use(Vuetify, {...})` statement in the .vue file instead of the main.js file, as you can see in the [HelloWorld.vue](https://github.com/laurenra7/my-vuetify/blob/master/src/components/HelloWorld.vue) file in [this project](https://github.com/laurenra7/my-vuetify).

The button colors don't come in so I had to add them myself. I noticed that the ripple effect when you click on a button does not work despite importing the Ripple directive.

It still doesn't work right, but it is closer to working than can be achieved by following the instructions on the Vuetify website for importing components into a .vue file. It would be helpful if you would test this, provide the solution, and update your instructions for importing into a .vue file.

**Comment by blalan05** [comment]
From the Vuetify Docs "...can exist anywhere inside the body, but must be the parent of ALL Vuetify components. v-content needs to be a direct descendant of v-app."
https://vuetifyjs.com/en/framework/default-markup#all-about-app

Your v-app in not in the root file (app.vue).

**Comment by mzerara** [comment]
I completely agree wtih @laurenra7! Following the Vuetify instructions doesn't lead to fixing the problem. I am trying to getting the A la carte feature work on a project that uses custom webpack settings and I am having the same issues.
PS: I am using Vuetify 1.5
