### ISSUE TITLE
[Bug Report] Can't type any text in v-text-field

### ISSUE THREAD

**Issue by nicolasunivlr** [vuetifyjs/vuetify#6936]
## Versions and Environment

vue@2.6.10
vuetify@1.5.9
Browser: Firefox 66.0.1 (64 bits)
OS: Linux x86_64 

## Description

Can't type any text in v-text-field.

## Steps to reproduce

Enable in firefox "Search for text when you start typing" in prefs
Show the app in adaptative view (Ctrl+Shift+M),

**Comment by KaelWD** [comment]
This happens everywhere, go complain to mozilla instead.

**Comment by nicolasunivlr** [comment]
It's true : https://bugzilla.mozilla.org/show_bug.cgi?id=1322385
Sorry for this fake.
