### ISSUE TITLE
Pressing Escape on a button dropdown doesn't change its icon

### ISSUE THREAD

**Issue by SLaks** [vuetifyjs/vuetify#694]
### Steps to reproduce
Click on any v-btn-dropdown, then press `Escape` on the keyboard

### Versions
Current version on https://vuetifyjs.com/components; all platforms

### What is expected ?
Arrow should point down, like normal closed dropdowns

### What is actually happening ?
Arrow points upwards

### Reproduction Link
https://vuetifyjs.com/components/buttons

**Comment by VasiliyIsaichkin** [comment]
Сonfirm, but sometime works normally.

**Comment by johnleider** [comment]
It's because of how the dropdown is handling "focus" and is not dropping that when key ```esc``` is being pressed.

**Comment by johnleider** [comment]
button-dropdowns will be replaced with select as they are essentially the exact same with slightly different styles. This resolves the issue as selects work properly like this.

**Comment by SquareBeard** [comment]
This is not completely resolved, pressing escape does work with selects to loose focus. But focused selects should not have an arrow pointing up. See https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons
Reproduction link (using v0.16.4): https://codepen.io/anon/pen/dVmQJO

**Comment by johnleider** [comment]
In that guideline, focus really means tab focused, not clicked.

**Comment by KaelWD** [comment]
The arrow points up when you tab focus as well.

**Comment by johnleider** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by KaelWD** [comment]
And if you open the first select, press escape and then click it again it doesn't get the right styles applied.

**Comment by SquareBeard** [comment]
Same problem when you clear a clearable multi select. The next time you open it the arrow still points down. I believe it's the same as pressing escape.

Do you want me to make a new issue ?

**Comment by johnleider** [comment]
Yes, let's move this to a new issue please, thank you.

**Comment by SquareBeard** [comment]
Here it is #2103
