### ISSUE TITLE
[Feature Request] v-img enable router-link

### ISSUE THREAD

**Issue by cmeyertons** [vuetifyjs/vuetify#6941]
### Problem to solve
Currently, v-img is difficult to wrap in a router-link because router-links default behavior is an `a` tag that fills its child, while `v-img` is a tag that fills its parent -- so you end up w/ nothing :(

### Proposed solution
Add a `:to` capability to `v-img` like it's `v-btn` cousins.  This is a pretty common use case having a logo at the top left that you want to navigate back to the home page

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
