### ISSUE TITLE
[Bug Report] Grid list example does not change the tile size when a new size is selected

### ISSUE THREAD

**Issue by agrgic16** [vuetifyjs/vuetify#6943]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. In the size menu, select any different size

### Expected Behavior
Expected the image size to change according to the menu selection

### Actual Behavior
Image size stays the same as the default size

### Reproduction Link
<a href="https://codepen.io/anon/pen/wZzgGL?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/wZzgGL?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
We are currently not accepting bug reports for 2.0-alpha. Additionally the grid system/grid-lists have not been reworked yet. 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com). Thank you for your support and interest in improving Vuetify.
