### ISSUE TITLE
[Bug Report] Credit Card Mask is not applied when you bind the value

### ISSUE THREAD

**Issue by FabioZanchi** [vuetifyjs/vuetify#6944]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
Using the credit card mask template I created a paragraph to show the value from the credit card input.

### Expected Behavior
As the mask is applied I would like to show the value with the mask.

### Actual Behavior
It's binding but without the mask applied.

### Reproduction Link
<a href="https://codepen.io/fabiozanchi/pen/QPKmPK" target="_blank">https://codepen.io/fabiozanchi/pen/QPKmPK</a>

**Comment by KaelWD** [comment]
`return-masked-value`
