### ISSUE TITLE
#TreeView update after edit/delete

### ISSUE THREAD

**Issue by aebrs** [vuetifyjs/vuetify#6946]
Hi, it seems that there is no example on how to update treeview node after edit/delete.
By the way, **how is it possible to force any node / async loaded node to reload?**
Any full help link will be appreciated.

**Comment by aebrs** [comment]
https://stackoverflow.com/questions/55572650/how-to-force-a-vuetify-treeview-node-reload

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by aebrs** [comment]
You muted this but left the problem unsolved. If this is not a bug, then what is the link or doc to do it? If there is not any function or solution to update a particular node, then it is a bug.
Search all your community documents or web, certainly you can not find any sample or help for this issue.
So please instead of muting a request, help it.

**Comment by nekosaur** [comment]
If you think it's a bug, then please follow our instructions to create an [issue](https://issues.vuetifyjs.com).

**Comment by KaelWD** [comment]
This isn't a support channel, and even if it was you haven't provided enough information for anyone to help you.

**Comment by aebrs** [comment]
We are just using it int our project and during last 3 days have not been able to solve the problem. There would be a way to refresh any particular node in a tree by calling a method and passing some Id, but in main documents and on the web we have found nothing, so the only place that remain is here that may some body help. You are developer in this community, so you can say yes we forget it, or no, the document is not complete, or we thought it is obvious so we thought every developer knows it. 
We just need your help, not closing and leaving us in darkness. Ok?

**Comment by aebrs** [comment]
> If you think it's a bug, then please follow our instructions to create an [issue](https://issues.vuetifyjs.com).



> This isn't a support channel, and even if it was you haven't provided enough information for anyone to help you.

Believe me it a general question that is some how left un-solved, or I think not well documented. You are developer in this community, then you know exactly if it is a bug or not, then if you think it is a bug, I will follow the rule and using this [link](https://issues.vuetifyjs.com/)

**Comment by aebrs** [comment]
https://stackoverflow.com/questions/55572650/how-to-force-a-vuetify-treeview-node-reload
