### ISSUE TITLE
[Bug Report] Error pass selected values

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#6948]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
I am using apollo to fetch data. When I pass selected values manually it works fine. But my components fetching data after create and sync it. As a result, sometimes I have selected values which got from the server but in other 80% cases I got unselected tree

### Expected Behavior
https://www.awesomescreenshot.com/image/3961836/d35637bc6976a368eed2fdf733d52db4

### Actual Behavior
IT should be like at the screen but the real situation it doesn't select any one

### Reproduction Link
<a href="https://gist.github.com/websitevirtuoso/b1dc299c070f8607247428217f9e060c" target="_blank">https://gist.github.com/websitevirtuoso/b1dc299c070f8607247428217f9e060c</a>

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
