### ISSUE TITLE
[Feature Request] Expanding bottom sheet

### ISSUE THREAD

**Issue by ludoo0d0a** [vuetifyjs/vuetify#6949]
### Problem to solve
Could it be possible to integrate the "Expanding bottom sheet" or is there an already existing solution to mimic this pattern.
https://material.io/design/components/sheets-bottom.html#expanding-bottom-sheet

### Proposed solution
Add an expandingMode to allow to add an activator, for the Floating action button.
css should be applied as well to stick corner and not looks like a fab button.

![image](https://user-images.githubusercontent.com/294090/55754114-2e298c80-5a4c-11e9-83e1-f729c3ff8273.png)

**Comment by arkokoley** [comment]
Is this planned?

**Comment by johnleider** [comment]
Here is an example of how to do this in Vuetify 3:

https://play.vuetifyjs.com/#eNqlVU2P2zYQ/SsTpYVlQLLWu2kOxm66bZBDemiDpocC6wChJcpmliIFkrJ3u/B/73CoD9rpxwI5SZwZzbx584a6e0qsKYuf2nax73iySq4db1rJHH+zVgDX+5y1Lb3SQbJH3blcYFCwATS64jLfM9nxwaRYw2/WSc0262SwtdoKJ7RC+0Y7p5vJZcVfPvyH15OplMxatDn+4HKuqsHTIyEsG6eGE4CoMNp2bauNm9JgWcNb/D4XJZVuKpHX2nRR9bG+ZGbLY/uOi+3OnSEDMLpTFff1LsDZ/EHGzlJLbQiKqVnJkRcjmDqBdNKb7TZOOMnzJdRaufxANXO3Eyr+ZmXdo/Qg6Wljl0+Djo+hd0iX89h7W0pR3qNfq7f+bfKNVCKZw8zhZc9X5CSuPX0j8Mbml9Dw/HKdnHEHRZy1OJFSMNHYBj3hKRIUWkedBYnkdse5g31OGvOV/RPL1J2UtjScK2ClE3vmiPSXowBinTit5YYZIJ4npqKg5zCAsCESUbnje6NVXukDDmqimRDCDbwYoD6DkR7g2H/YNGHdpMDlxcX3mGzlefIjoGeUnYiNOAvLi8awvSeF8YjcidaB5a4Lyy0aEs8T6rdpO8erDAyvMzgwV+7gCLXRDczwhpgFkEgEwiMU2OzdMoPLDK4yePUp9qMykUleYQhmS2smLZ9P7oGr2Dd5g9LRPUBK0zncvIGn0LFB7EYNJ1wDw5TF1W5W8Jnefbd/pt89vRhQLOiOgh9hhmy2DzNYwexidpx/zkKOo38cewx1p1BYKPp+byDl86GYqCE9yzr6YGy6L3eDyKabkS+s0+37puGVQHwfjG7ZlvlCKREzoAggiP2UaMrgpHuCQI7/r0/UnrV4XQQJ4PCTLAnTzxvWLr5YrfAvQNlQZuRAoa2G/OsEReDP62TnXGtXRVFWCj9DKGJvFoq7QrVNcYthhemUE3hRVLq5vVpcLV4VFao6Ni+4bfKN0QfLDSZZJ/0sqIwT9eMzSvWRVGH5OpTobXi9bKyv8VXuAgvuucmN58pw89yWzj6L2zpzfdVaP9gjEi6FurdnXJeWeL4bQH5bz5TNp8KF9BWdxa2qxfa8KO6WkNz81noNng6aSakPv5DNS3hkD6++8v4f7F/sQ2Dxg+HERcS48/8HvHK9+93HX1GjkRN13MleVP/i/J1bLTuPMYT9jL9ghB3FEdr3pFehtn/Yd34N7NDUsINHiicFvP2P1ie4SPA4t2OW0LiRzsB78ulvXQrxOQ==

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
