### ISSUE TITLE
Selecting from a button dropdown loses focus

### ISSUE THREAD

**Issue by SLaks** [vuetifyjs/vuetify#695]
### Steps to reproduce
Click on any v-btn-dropdown, click any item, then press Tab

### Versions
Current version on https://vuetifyjs.com/components; all platforms

### What is expected ?
Dropdown should be closed and focused

### What is actually happening ?
Focus is lost; pressing Tab focuses the first element in the page.

### Reproduction Link
https://vuetifyjs.com/components/buttons

**Comment by johnleider** [comment]
I just went to the link and clicked on a btn dropdown then pressed tab. It closed the previous dropdown and opened the next. Can you please provide a gif of what you are experiencing because I'm not seeing it.

**Comment by SLaks** [comment]
It looks like the actual problem is that clicking the dropdowns doesn't consistently focus them.
If the dropdown itself actually gets focus, the bug won't happen.

However, if you reload the page, then immediately click a dropdown, click an item, and hit tab, it will happen.

**Comment by johnleider** [comment]
Able to reproduce. Happens when clicking on the dropdown icon.

**Comment by johnleider** [comment]
The btn-dropdown component is being removed in favor of select. They are the same component with the dropdown containing some additional styles that are now available on select.
