### ISSUE TITLE
v-radio-group prop loading doesn't work

### ISSUE THREAD

**Issue by paladin2005** [vuetifyjs/vuetify#6953]
By docs. There are a prop loading in v-radio-group

**loading**: **default** _false_, **type**: _boolean_
`Displays linear progress bar. Can either be a String which specifies which color is applied to the progress bar (any material color or theme color - primary, secondary, success, info, warning, error) or a Boolean which uses the component color (set by color prop - if it's supported by the component) or the primary color`

That's no work.

**Comment by blalan05** [comment]
The docs are wrong. VCheckbox and VRadioGroup do not have a loading prop. Only VSwitch. We'll get that updated.

**Comment by MajesticPotatoe** [comment]
This has been resolved
