### ISSUE TITLE
[Bug Report] v-tabs lazy functionality

### ISSUE THREAD

**Issue by NAVI-91** [vuetifyjs/vuetify#6954]
### Versions and Environment
**Vuetify:** 1.5.10
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
Combined vsteppers and vtabs.

### Expected Behavior
Waiting first or v-model tab is active.

### Actual Behavior
After going next step on stepper, first tab or v-model valued tab is not active

### Reproduction Link
<a href="https://codepen.io/navi3591/pen/PgWKyP?editors=1010" target="_blank">https://codepen.io/navi3591/pen/PgWKyP?editors=1010</a>

### Other comments
like vdialog, it needs lazy functionality I think.

**Comment by blalan05** [comment]
In 2.0 everything has/will have lazy by default. Will have to use 'eager' prop for other option.

**Comment by ghansham** [comment]
Do we have a demo showing lazy loading in vuetify tab component

**Comment by husayt** [comment]
In 2.3.4 it sill loads all the dynamic components from different tabs on mount. Even setting :eager="false" on tab-item doesn;t help

**Comment by core01** [comment]
Still actual in 2021

Vuetify 2.4.5

**Comment by nmalchy** [comment]
This is super rough, is it fixed yet

**Comment by snimavat** [comment]
+1

**Comment by CreativeWarlock** [comment]
Getting any answers in the Discord group is like winning in the lottery. 99% of all questions are without answers.

With that said, I'd appreciate a link to a v-tabs property - because I cannot find anything here:
https://vuetifyjs.com/en/api/v-tabs/#links

**Comment by johnleider** [comment]
> Getting any answers in the Discord group is like winning in the lottery. 99% of all questions are without answers.

We have ways to get you help https://vuetifyjs.com/introduction/enterprise-support/
