### ISSUE TITLE
[Bug Report] v-select close on input click with menu offset

### ISSUE THREAD

**Issue by zajca** [vuetifyjs/vuetify#6958]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Linux x86_64

### Steps to reproduce
Click on input, menu will open under select. Than click on input again or on chevron in right.

### Expected Behavior
On input click when menu is open I would expect that it will close again, this is how html select works and other select like select2 or select in quasar, but it's kind the OK.

On chevron click I would definitely expect to menu to close.

### Actual Behavior
On input click nothing happen.
On chevron click menu will blink, it's closed with click away and open again probably.

### Reproduction Link
<a href="https://codepen.io/zajca/pen/NmbVKv?&editable=true&editors=101" target="_blank">https://codepen.io/zajca/pen/NmbVKv?&editable=true&editors=101</a>

### Other comments
I tried other menu props but nothing help to work like expected.

**Comment by zajca** [comment]
This si also autocomplete issue which is directly in examples: https://vuetifyjs.com/en/components/autocompletes#scoped-slots

**Comment by ioagiannis** [comment]
Same issue. Can anyone provide a fix for this?

**Comment by eBrou** [comment]
Using v2.5.5.  
Clicking on the chevron closes it by default.  
By setting `closeOnClick: true` within `menu-props` the open select will close when you click anywhere on the input, as well as on the menu items.  
https://vuetifyjs.com/en/api/v-select/#props-menu-props
