### ISSUE TITLE
[Bug Report] Select object shows "[object Object]" as selected value

### ISSUE THREAD

**Issue by xaviarnl** [vuetifyjs/vuetify#6959]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.4

### Steps to reproduce
Select a value from the select object.
Instead of chosen value, '[object Object]' is shown.

### Expected Behavior
I would expect the selected player name ('naam') to be shown. And the 'selectedSpeler' variable be updated with the chosen value (which works correctly).

### Actual Behavior
When you click on a value in the list, the selected value shown after that is [object Object] instead of the selected value. 

### Reproduction Link
<a href="https://codepen.io/xaviarnl/pen/QPpdQo" target="_blank">https://codepen.io/xaviarnl/pen/QPpdQo</a>

**Comment by KaelWD** [comment]
`item-text="naam"`
