### ISSUE TITLE
[Feature Request] v-select and v-btn are ignored by the "next" android button

### ISSUE THREAD

**Issue by mardonedias** [vuetifyjs/vuetify#6965]
### Problem to solve
Browsing forms on mobile devices is already a bit complicated, skipping the selects is very complicated. This improvement will make the framework much more suitable for the development of mobile forms.

### Proposed solution
I'm making my first hybrid app, I'm not a programming expert. But the little I understand the problem seems to be that v-select and other more complex components are not a native input. I can not say how to solve at the moment, but I would like to ask for this improvement.

**Comment by KaelWD** [comment]
`<select>` is skipped too, and I don't know what you expect to be able to type into a button. This is consistent with the native behaviour.
