### ISSUE TITLE
[Feature Request] Add rules props to v-btn-toggle for v-form verification

### ISSUE THREAD

**Issue by wongwanchap** [vuetifyjs/vuetify#6966]
### Problem to solve
Most of input components support v-form verification. v-btn-toggle should be included for v-form verification as well.

### Proposed solution
Add rules props to v-btn-toggle for v-form verification.
When mandatory props is set to true, add a default rules to check whether v-btn-toggle 's value is contained in v-btn 's values. (Sometime, I initialize v-btn-toggle 's value to -1 to prevent default selection)

**Comment by DogFive** [comment]
I apologize for bumping issues, I haven't seen any movement on this. It seems that all inputs should be compatible with the v-form interface. 

I'm using v2.0.9

**Comment by havardthom** [comment]
Any status update on this feature request?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
