### ISSUE TITLE
[Feature Request] Allow selection of duplicate values in v-select

### ISSUE THREAD

**Issue by albertostiip** [vuetifyjs/vuetify#6967]
### Problem to solve
I need to be able to select duplicate values in a v-select how can I do it? Is it already possible?

### Proposed solution
Create a special prop with a value or pass a function to decide the selection criterion

**Comment by KaelWD** [comment]
Native selects don't do this either: https://codepen.io/anon/pen/ROVKmx

Do you have an example of what you're trying to do?

**Comment by albertostiip** [comment]
For example I have a list of strings that indicate the colors (yellow, red, green etc.) in the v-select.
The user must select the colors and these can also be repeated example [red, yellow, red]

How can I do?

**Comment by ibrahimBeladi** [comment]
@albertostiip 
I would recommend using objects, each with an id and a title, so you will have the duplicate color values.
[Here's an example](https://codepen.io/ibrahimbeladi/pen/yrbpZa?editors=1010)

**Comment by albertostiip** [comment]
> @albertostiip
> I would recommend using objects, each with an id and a title, so you will have the duplicate color values.
> [Here's an example](https://codepen.io/ibrahimbeladi/pen/yrbpZa?editors=1010)

Not really, I don't have the red option must once in the v-select, but I have to be able to choose it more than once. I think it's not possible to do this with a select. Do you have any ideas?

**Comment by KaelWD** [comment]
It'd be like my example, even if you have it in the list twice they both have to be selected as one, and there's no way for you to tell the difference.

**Comment by ibrahimBeladi** [comment]
> > @albertostiip
> > I would recommend using objects, each with an id and a title, so you will have the duplicate color values.
> > [Here's an example](https://codepen.io/ibrahimbeladi/pen/yrbpZa?editors=1010)
> 
> Not really, I don't have the red option must once in the v-select, but I have to be able to choose it more than once. I think it's not possible to do this with a select. Do you have any ideas?

What you are asking for is not clear. I am not sure about what you are trying to achieve, but I think you are misunderstanding the usage of v-select for something else. It might be simple buttons which push the colors to an array of strings.

**Comment by blalan05** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.
--
 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
