### ISSUE TITLE
[Bug Report] Month view omitting events when time is set in event object in v-calendar.

### ISSUE THREAD

**Issue by sonoftheweb** [vuetifyjs/vuetify#6968]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Remove or make empty the time attribute in any event object. The event shows up on the month view and adding it back removes it from the month view.

### Expected Behavior
Irrespective of whether time is added, I should be able to switch between month and week / day view and still have the calendar display as should.

### Actual Behavior
Right now I have to always check (watch) the calendar type and remove / add the time when in week / day view or in month view.

### Reproduction Link
<a href="https://codepen.io/sonoftheweb/pen/rbmYXV?editors=1010" target="_blank">https://codepen.io/sonoftheweb/pen/rbmYXV?editors=1010</a>

**Comment by KaelWD** [comment]
You have `v-if="!event.time"` in the day slot.
