### ISSUE TITLE
[Bug Report] Releasing mouse button outside a dialog should not close the dialog

### ISSUE THREAD

**Issue by gsjen** [vuetifyjs/vuetify#6969]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
1. Open the dialog
1. Left-click on the dialog
1. Without releasing the button, move the cursor outside the dialog
1. Release the button

### Expected Behavior
The dialog should remain open. The dialog should only be closed if the mouse button is both pressed and released outside the dialog.

### Actual Behavior
The dialog is closed.

### Reproduction Link
<a href="https://codepen.io/gjen_123/pen/ZZKMLb" target="_blank">https://codepen.io/gjen_123/pen/ZZKMLb</a>

**Comment by blalan05** [comment]
The click handler here is on the v-app element, which is receiving both the up and down events. Lots of refactoring would be needed I think.

**Comment by lebesnec** [comment]
This make selecting text from a text field with the mouse inside a dialog near impossible, as you can try here: https://codepen.io/anon/pen/QPRBJz?editors=1010

Since the text field is near the edge, your cursor will naturally fall outside the dialog when you try to select text, and this will cause the dialog to close.

**Comment by Xambey** [comment]
This problem is observed on my version 1.5.16, can this be somehow temporarily solved?

**Comment by diazemiliano** [comment]
@gsjen this has a workaround https://codepen.io/anon/pen/Xvaaed.

**Comment by akeyboardlife** [comment]
> @gsjen @blalan05 This has a workaround https://codepen.io/diazemiliano/pen/MNvEwb
> Basically if you set the `v-dialog` as `persistent` and you have a `@mousedown` handler for the `dialog content` you can do some logic to achieve what you want.

It worked great, thank you. But I find a problem.

If  a v-select is inside the v-dialog, when click on the v-select selection, it triggers the click:outside event which eventually close the dialog.

[A codepen](https://codepen.io/washan/pen/ExYWEgo)

**Comment by darren-outdev** [comment]
Bringing this up as it remains an issue
