### ISSUE TITLE
v-select inside of v-dialog has wrong z-index

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#697]
### Versions
0.12.6
### What is expected ?
v-select should be visible

### What is actually happening ?
v-select hidden behind dialog

### Reproduction Link
- https://vuetifyjs.com/components/dialogs Example 4
- https://codepen.io/anon/pen/NgPROR

**Comment by dohomi** [comment]
`z-index: 6` on `.menu__content` solved it for me temporary.

**Comment by duebbert** [comment]
Can confirm this. Just ran into it after updating to 0.12.6. Worked fine in 0.12.5.

**Comment by johnleider** [comment]
Must of been something lost in the merge. Will fix

**Comment by johnleider** [comment]
Yea, this is in the file, _menus.styl line 24. Hopefully rebuild/release will fix this.

**Comment by johnleider** [comment]
This was already fixed with #678 and #675 but has not been released yet. Is releasing now.

**Comment by mesaglam** [comment]
It has appeared again with latest version 1.2.1

**Comment by KaelWD** [comment]
Make a new issue then, this is over a year old.
