### ISSUE TITLE
[Bug Report] Input type file not working properly on Safari 12/11

### ISSUE THREAD

**Issue by ikudosi** [vuetifyjs/vuetify#6970]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Safari (12,11)
**OS:** Windows 10, Mac OSX

### Steps to reproduce
Click on first file input on Safari (v12) and upload any file type. You will see the file flash and then the input goes back to no file selected.

### Expected Behavior
Should upload the file.

### Actual Behavior
Somehow the state is going back to original state after uploading.

### Reproduction Link
<a href="https://codepen.io/anon/pen/EJmrzG?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/EJmrzG?&editable=true&editors=101</a>

### Other comments
Also tried on v11 of Safari.

**Comment by nekosaur** [comment]
`v-text-field` does not support the file type. We hope to have a `v-file-upload´ component available in the upcoming 2.0 release.

**Comment by ikudosi** [comment]
Okay - thanks for quickly clarifying this! There should be some indicator on https://vuetifyjs.com/en/getting-started/quick-start on what exactly is not supported on Safari 10+ (or any other browsers)!
