### ISSUE TITLE
[Bug Report] Disabled menu item not always working 

### ISSUE THREAD

**Issue by Tiagosophy** [vuetifyjs/vuetify#6977]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Use keyboard to access disabled item OR with a faster click
![Gif disabled](https://i.imgur.com/0yDNxPW.gif)

### Expected Behavior
Not emit click

### Actual Behavior
Emit click

### Reproduction Link
<a href="https://codepen.io/tiagoxavi/pen/vMJONz" target="_blank">https://codepen.io/tiagoxavi/pen/vMJONz</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
