### ISSUE TITLE
[Bug Report] Dynamically adding tab transition is not working properly.

### ISSUE THREAD

**Issue by santhikumar43** [vuetifyjs/vuetify#6979]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
Adding a new tab dynamically on clicking of the button.

### Expected Behavior
The transition is some how overlapping on the card. 

### Actual Behavior
The transition should not flicker on the card.

### Reproduction Link
<a href="https://codepen.io/anon/pen/axyyyd?editors=1010" target="_blank">https://codepen.io/anon/pen/axyyyd?editors=1010</a>

### Other comments
In the above example click on the Add button, it will add the tab and what ever is newly added is active. 
This used to work in these versions: 
Vue: 2.5.18
Vuetify: 1.5.5
Then i updated the version of the vue@2.6.10 and this is the problem. I later updated the Vuetify@1.5.11 but didn't solve the issue..

**Comment by KaelWD** [comment]
Timing issue with 2.6's nextTick change. You can fix it by updating the active tab after the DOM: https://codepen.io/anon/pen/NmvaWZ?editors=1010
