### ISSUE TITLE
[Feature Request] Data table component should have one source of truth for header order and visibility

### ISSUE THREAD

**Issue by danieleades** [vuetifyjs/vuetify#6980]
### Problem to solve
The columns of a data table are defined twice- once in the datatable headers prop, and then again in the cell definitions of the table. This means there are two sources of truth for the headers that must both be kept aligned (same headers, same order) or the table won't display properly.

In particular this adds complexity if we want to support dynamically reordering or hiding data table columns.

One workaround is to use a v-for to loop over the headers array to define the cells, but this fails if we want to do different formatting for different columns.
My current workaround is to define a 'Header' object which contains 'text', 'value' and a format function. I can then use a v-for loop over my array of Header[ ], and call the format function with the corresponding value. This works and means I only have to manage one list, but it's not very clean, and i'm passing this one list into the datatable in two different places- in the headers prop and again to define the cells. This strikes me as a poor design.

### Proposed solution
The columns templates (`<td>...</td>`) in the data table should be optionally wrapped in a component marked with a unique name that corresponds to a header passed to the 'headers' prop of the datatable. Only the headers in the 'headers' prop are rendered, using the corresponding templates.

This is how the Angular datatable api works. This means that the headers prop is the single source of truth for the order and visibility of headers. The cell templates need only be a superset of the provided headers and order is not important. This will make it far simpler to dynamically manage datatable columns.

**Comment by jacekkarczmarczyk** [comment]
This is already resolved in 2.0 - you have named slots for each column
