### ISSUE TITLE
[Bug Report] <v-btn> block doesn't work inside <v-btn-toggle> 

### ISSUE THREAD

**Issue by AlissonRS** [vuetifyjs/vuetify#6983]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Create a row layout with many flexbox, each flexbox with a <v-btn-toggle>, and a <v-btn> with block.

### Expected Behavior
The button should expand to full width of its parent flexbox.

### Actual Behavior
It doesn't expand when using <v-btn-toggle>

### Reproduction Link
<a href="https://codepen.io/alissonreinaldo92/pen/xeLedw" target="_blank">https://codepen.io/alissonreinaldo92/pen/xeLedw</a>

### Other comments
The Codepen linked has an example of how I expected it to work with <v-btn-toggle>.

**Comment by blalan05** [comment]
Issue is that v-button toggle has display: inline-flex.
Quick fix then is to put `class="d-flex"` on the v-button-toggle.
https://codepen.io/anon/pen/PgKvro

**Comment by AlissonRS** [comment]
@blalan05 that worked, thanks you so much, I really appreciate it.
