### ISSUE TITLE
[Bug Report] example code of v-menu not working with newly upgraded vuetify

### ISSUE THREAD

**Issue by DimasInchidi** [vuetifyjs/vuetify#6989]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.20
**OS:** Linux x86_64

### Steps to reproduce
> install Vuetify v1.3.0
> npm upgrade
> use v-menu

### Expected Behavior
A button that triggers the menu shown.

### Actual Behavior
only `<div data-v-2c1d3b74="" class="v-menu"></div>` rendered, nothing else.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GLMNqX" target="_blank">https://codepen.io/anon/pen/GLMNqX</a>

### Other comments
am quite familiar with VueJS but this is my first time using Vuetify, I start this project ~3 months ago, and today when I continue working on this project, I need to use Menu (this is my first Menu component in this project) am using same code with [example given](https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/menus/usage.vue) but it's not working well. Only `<div data-v-2c1d3b74="" class="v-menu"></div>` rendered, then i upgrade my Vuetify to latest version and still not working so i upgrade everything including vuetify-loader but still no luck.

So, i check git history and i know that old example use `slot="activator"` i give it a shot and its working. wondering whats wrong with new code and new upgraded version.

**Comment by blalan05** [comment]
The included codepen doesn't seem to replicate your issue... the menu is working there. 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by DimasInchidi** [comment]
@blalan05 hi, sorry i just add link to codepen that actually contain sample from https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/menus/usage.vue because actually i dont know what to put there and https://issues.vuetifyjs.com ask for it. please read extra information from comment i provided and please just ask me if you need any other information. 

thank you

**Comment by KaelWD** [comment]
There's no console errors? You sure you have vue 2.6? Have tried another browser?

**Comment by ibrahimBeladi** [comment]
> ### Versions and Environment
> **Vuetify:** 1.5.11
> ### Steps to reproduce
> > install Vuetify v1.3.0

Which version did you use!?

**Comment by nekosaur** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by DimasInchidi** [comment]
hi, apparently my IDE runs my Vue project using another NPM with old Vue in it so that Vue doesn't support v-slot yet and raise an error because of it.
thanks
