### ISSUE TITLE
Dialog custom CSS classes / width

### ISSUE THREAD

**Issue by bolerodan** [vuetifyjs/vuetify#699]
First, great project, thank you for your great work! I guess this is more of a discussion than a feature request or bug report.

One of my use cases with Dialogs is providing custom widths for various kinds of dialogs in my application. (As well as being CSS responsive to desktop screen size). So I would attach a custom class to the `v-dialog` element and could target the `.dialog` class to provide responsive css width.

```
<v-dialog class="schedule-dialog"></v-dialog>
```

Now with 0.12.7 the `.dialog__content` element gets removed out of flow which is super handy for overflow issues thank you for that. But now I'm unable to target the width of the `.dialog` element to control width. And interesting enough, in normal flow where the dialog used to be you can see where your class is attached to, but cannot target the dialog.
```
<div class="schedule-dialog dialog__container"></div>
```

So I guess my question is if I am missing a way for me to apply CSS classes to specific kinds of dialogs I may have without needing to provide a manual width as a prop.

Thanks!

**Comment by johnleider** [comment]
I think most of what you were looking for is in #677 so I'm going to close this. If I'm wrong, let me know.

**Comment by bolerodan** [comment]
Ahh you're absolutely right. Great, thanks again!
