### ISSUE TITLE
[Bug Report] Menu opens in the wrong area via v-model if activator is hidden, opens in correct spot after activator use when absolute

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#6990]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

![Vuetify Menu Issue 001](https://user-images.githubusercontent.com/1400380/56099836-3740b080-5ec7-11e9-8fb6-e8910bacb132.gif)

### Steps to reproduce
1. Setup a menu that has an activator AND opens with a v-model. But the activator is hidden
3. Activate menu and unhide activator at the same time. Menu will open to the far left
4. If the menu is now opened with the activator, it will open in the correct spot from now on

### Expected Behavior
It opens based on where the activator is on the first `v-model` based activation.

### Actual Behavior
It opens to the far left.

### Reproduction Link
<a href="https://codepen.io/anon/pen/EJwmdw?editors=1010" target="_blank">https://codepen.io/anon/pen/EJwmdw?editors=1010</a>

### Comments

My example isn't perfect, but it shows the behavior I'm trying to highlight. It's especially odd as it opens in the correct place (through v-model) AFTER being opened via the activator, but not before.

**Comment by douglasg14b** [comment]
Updated title and issue. It has nothing to do with the animation. Probably related to the activator being hidden when the menu is first opened. And since it opens in the correct spot after the activator has been used once, even if it's hidden, I assume that is a cached location?

If so, is there a workaround?

**Comment by douglasg14b** [comment]
Looks like it only opens up in the correct spot if `absolute` is used. If `absolute` is not used, it will always open to the upper left if activated via `v-model`

**Comment by douglasg14b** [comment]
Also if I use the `attach` property, when activated with v-model it opens off-screen to the left (`left: -229px`).  It opens as expected when clicking the activator.

https://codepen.io/anon/pen/oOGppL?editors=1010

**Comment by KaelWD** [comment]
Fix is to open the dialog after the activator is visible, and you also need to not use `absolute` if you aren't setting the position manually: https://codepen.io/anon/pen/ZZxGBm?editors=1010

Either that or don't use the activator slot and just set the position yourself every time: https://vuetifyjs.com/en/components/menus#absolute-position-without-activator

**Comment by douglasg14b** [comment]
Oh, I see. Thanks for the input!

**Comment by douglasg14b** [comment]
@KaelWD 

Unfortunately the issue still seems to exist when the activator is animating.

https://codepen.io/anon/pen/VNxaeo?editors=1010

1. Click play button. 
2. Hide/show the dropdown with the chevron icon/button
3. Click play button to hide and click again to show.
4. Dropdown will open on the far left again.

I'd very much like to avoid manual positioning, and all the edge cases that come along with that if I can... any idea why it seems to choke when the activator is animating?

**Comment by douglasg14b** [comment]
Oh I see.

This is because the entire button is replaced on the animation.

If I put the animation over just the icon this no longer occurs.

Scratch my above statement!
