### ISSUE TITLE
[Feature Request] [TreeView]  Auto Generator `itemKey` when not provided.

### ISSUE THREAD

**Issue by wmzy** [vuetifyjs/vuetify#6991]
### Problem to solve
Usually the tree data has no a key unique among all items. And the key is need not for the domain.So you should encapsulating it.

### Proposed solution
Auto Generator `itemKey` by the path.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
