### ISSUE TITLE
[Feature Request] [Question V2] Extends component

### ISSUE THREAD

**Issue by deka** [vuetifyjs/vuetify#6992]
### Problem to solve
Hi,
actually, to extend component i use a transparent pass through encapsulation like [this](https://codepen.io/anon/pen/XQeEwy#anon-login)

With V2, is there a better way/more optimized to extend a component ?
If yes, do you have an example ?
Thanks

### Proposed solution
Use typescript inheritance ?

**Comment by KaelWD** [comment]
No, you could optimise that a bit with prop defaults though. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by deka** [comment]
Thanks @KaelWD,
 You say :
> No, you could optimise that a bit with prop defaults though.
(https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

I do not see how. Do you have an example or 2 minutes to complete the codepen?
