### ISSUE TITLE
[Feature Request] overflow-x overflow-y attributes for containers, layout and card

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#6997]
### Problem to solve
In this codepen I demonstrate an example where mosaic tiling would be nice (I know it is a work in progress)

https://codepen.io/sumneuron/pen/qwmKMw

since it is not available I implement a simple style modification to allow overflow with scroll in a direction of choice.

### Proposed solution

It would be nice if all container like elements (container, layout, flex, card, etc) would support the attribute overflow-x and overflow-y, which expects a string or number setting the max width / height respectively.

**Comment by johnleider** [comment]
It looks like these exist but aren't documented:

![image](https://user-images.githubusercontent.com/9064066/102382383-03693880-3f90-11eb-8e9a-38f28305d62a.png)

You can use them like this:

```css
.overflow-auto
.overflow-hidden
.overflow-visible
.overflow-x-auto
.overflow-x-hidden
.overflow-x-visible
.overflow-y-auto
.overflow-y-hidden
.overflow-y-visible
```

**Comment by jornhymcfly** [comment]
it's a shame they are not documented. is there a way we can update the docs to make them easier to find?

**Comment by MajesticPotatoe** [comment]
> it's a shame they are not documented. is there a way we can update the docs to make them easier to find?

That is the plan hence the `documentation` tag
