### ISSUE TITLE
v-dialog will cause screen to be unresponsible

### ISSUE THREAD

**Issue by iury** [vuetifyjs/vuetify#700]
### Steps to reproduce
Set the model of v-dialog to true, perform a fast request cycle, like a GET request already cached (my example simulate it using a short setTimeout) and set the model to false. if it is fast enough, like less than 50ms, the entire screen will be unresponsible.

### Versions
0.12.7

### What is expected ?
Buttons on the screen be clickable

### What is actually happening ?
Unresponsible screen

### Reproduction Link
https://codepen.io/anon/pen/eRmVbX

**Comment by johnleider** [comment]
Very awesome issue report, I'll get this squared away.

**Comment by jessycormier** [comment]
Something similar is happening when viewing the docs, [#3 Fullscreen](https://vuetifyjs.com/components/dialogs) on v-dialog. Once you close the fullscreen dialog you can no longer scroll.

**Comment by johnleider** [comment]
Rgr, that's already a ticket.

**Comment by mornir** [comment]
Using **vue-router**, navigating to a new route from a dialog causes the same issue. The dark overlay stays and the screen becomes unresponsive.
