### ISSUE TITLE
[Bug Report] Can't create transition with v-list twoline

### ISSUE THREAD

**Issue by garyo** [vuetifyjs/vuetify#7005]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Transitions like `v-slide-y-transition` can be used with `v-list` by replacing the `v-list` element with something like this:
```html
<v-slide-y-transition
                  group
                  tag="v-list"
                  leave-absolute>
                  <v-list-tile v-for="(item) in items"> ...
                  </v-list-tile>
</v-slide-y-transition>
```
but if you're trying to replace a `<v-list twoline>` there seems to be no place to add the "twoline" prop.

### Expected Behavior
Should be able to create a twoline v-list

### Actual Behavior
I tried `tag="v-list twoline"` but that gave an error at runtime.

### Reproduction Link
<a href="https://codepen.io/oberbrunner/pen/NmwgLb" target="_blank">https://codepen.io/oberbrunner/pen/NmwgLb</a>

### Other comments
The repro codepen just shows a working regular (non-twoline) list with a transition.

**Comment by blalan05** [comment]
`tag="v-list" wrap`
https://codepen.io/anon/pen/oOpxzY

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by garyo** [comment]
Thanks -- in that case shouldn't `two-line` be listed as a prop of `v-slide-y-transition` in the doc?

**Comment by blalan05** [comment]
But two-line isn't a prop of `v-slide-y-transition` its a prop of v-list, the component you called out in tag. The props pass through...

**Comment by blalan05** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

  
Thank you for your contribution and interest in improving Vuetify.

**Comment by KaelWD** [comment]
> The props pass through

They kinda don't though:
![image](https://user-images.githubusercontent.com/16421948/56211256-d964c200-609a-11e9-98d3-22de50b14bbb.png)

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity and the reproduction no longer works. If this is still present in the latest version, please open a new issue with a reproduction.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
