### ISSUE TITLE
[Bug Report] v-slide-y-transition doc should mention that for lists, props pass through

### ISSUE THREAD

**Issue by garyo** [vuetifyjs/vuetify#7006]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Per issue #7005, this is a request to update the `v-slide-y-transition` doc (and other relevant docs) to explain how, in a "group" context, some props are passed through to the created component mentioned in the `tag` prop. (Specifically `two-line` but perhaps others are useful as well.)

### Expected Behavior
It should be easy for users to create a two-line v-list with animated add and remove functionality in Vuetify

### Actual Behavior
It's hard because the doc doesn't have a good example of a v-list, especially not a two-line v-list.

### Reproduction Link
<a href="https://codepen.io/anon/pen/oOpxzY" target="_blank">https://codepen.io/anon/pen/oOpxzY</a>

### Other comments
Ideally the example from the repro codepen could just be added to the doc for v-transition; that would be brilliant.

**Comment by MajesticPotatoe** [comment]
In your case here (at least in 2.0) the transition group doesn't actually render a true `v-list` with the two-line prop it renders a basic `v-list` (which is a div at its base, and its initial ) with its basic styles and an two-line attribute (which doesn't actually do anything). A true `two-line` would just involve wrapping the transition in a `v-list`, `two-line` prop to the `v-list-item`, or adding the actual `two-line` css class to the transition group.

The actual group prop does have a link to the vue docs where it explains the use of `tag` however it would be good to add an example into the transition section for use of the group prop (only real example that uses it is the todo list).

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
