### ISSUE TITLE
[Bug Report] VDialog - "[Vuetify] No activator found" error on escape keypress

### ISSUE THREAD

**Issue by dbove** [vuetifyjs/vuetify#7008]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Open dialog with button click. Hit escape key. Note error in console.

### Expected Behavior
No error in console.

### Actual Behavior
Error message in console:

"[Vuetify] No activator found"

### Reproduction Link
<a href="https://codepen.io/anon/pen/gyodPp?editors=1011" target="_blank">https://codepen.io/anon/pen/gyodPp?editors=1011</a>

**Comment by tmcdos** [comment]
Having the same issue - no problems with `1.5.7`, though.
