### ISSUE TITLE
[Bug Report] Problem with v-tabs not showing content on tab change programatically

### ISSUE THREAD

**Issue by siba2893-avantica** [vuetifyjs/vuetify#7009]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.3
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Click `Open` button this will open the dialog, close it clicking outside and then click `Change Tab 2` button and then Click `Open` again. You'll see the dialog opens with the `tab2` selected but with no content.

### Expected Behavior
I expect to switch the selected tab programatically and open the modal and see the content of the tab2 there.

### Actual Behavior
Blank under tab2.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gyXKLe?editors=0001" target="_blank">https://codepen.io/anon/pen/gyXKLe?editors=0001</a>

**Comment by KaelWD** [comment]
Similar to #6962, vue transitions don't fire hooks properly sometimes, in this case when the parent is hidden. 

Reminder for later: https://stackoverflow.com/a/21696585/2074736

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity and your reproduction no longer works.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
