### ISSUE TITLE
[Bug Report] v-parallax not shown if height is the same as the image height

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#7010]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.8
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
See https://codepen.io/anon/pen/axEXMm

### Expected Behavior
Image is shown

### Actual Behavior
Image is not shown

### Reproduction Link
<a href="https://codepen.io/anon/pen/axEXMm" target="_blank">https://codepen.io/anon/pen/axEXMm</a>

### Other comments
It will work as long as the height of parallax is not the same as the height of the  image

**Comment by ibrahimBeladi** [comment]
After debugging this, what I realized is that when the heights are the same the img tag (with class "v-parallax__image") have a style rule of "opacity: 0;", otherwise it would be "opacity: 1;"
