### ISSUE TITLE
[Bug Report] Outline Button Background Color Issues on Mobile

### ISSUE THREAD

**Issue by DanielStout5** [vuetifyjs/vuetify#7011]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.6
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
See the codepen.

On desktop, clicking the button will toggle its "Active" state.

On mobile, the button won't visually change until you click off of it.

### Expected Behavior
Active button changes states on mobile like it does on desktop.

### Actual Behavior
Active button does not change states on mobile like it does on desktop.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ROQggB" target="_blank">https://codepen.io/anon/pen/ROQggB</a>

### Other comments
I was able to fix it via this CSS:

```
@media (hover: none) {
    .v-btn.v-btn--active:before {
        background-color: currentColor;
    }
}
```

**Comment by ibrahimBeladi** [comment]
This is an issue with the behavior in most (if not all) mobile phones. In the mobile, after clicking the button it focuses on the button and applies the :focus CSS pseudo-class. Which in turn make it similar to the state of hover/active.
You can change it via CSS by using something like this:
```
.v-btn:focus {
  background-color: #abcdef !important;
}
```

**Comment by DanielStout5** [comment]
I would still consider it a Vuetify bug, since this (existing) CSS rule causes the problem:

```
@media (hover: none)
.v-btn:hover:before {
    background-color: transparent;
}
```

**Comment by bromix** [comment]
Same here. Using the v-btn (flat and round) as a back button for an desktop application. While navigating back 1-2 pages, the button is shown active (focused). This is not happening in v1.5.X.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
