### ISSUE TITLE
[Bug Report] Dialog scrollable does not work when card-text inside stepper content

### ISSUE THREAD

**Issue by redijedi** [vuetifyjs/vuetify#7012]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.13.6

### Steps to reproduce
Run the sample.

### Expected Behavior
Should be able to scroll the content in the card-text node.

### Actual Behavior
Cannot scroll.

### Reproduction Link
<a href="https://codepen.io/anon/pen/XQZgyg?editors=1111" target="_blank">https://codepen.io/anon/pen/XQZgyg?editors=1111</a>

**Comment by KaelWD** [comment]
See #3713. Iit isn't realistic to support every possible combination, you'll have to implement it yourself.
