### ISSUE TITLE
[Bug Report] Image component blink after loading on Safari

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#7017]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Safari, Other
**OS:** Mac OS 10.14.3

### Steps to reproduce
Load a `v-img` component from Safari. 

I have used an example with multiple images from the doc, but it happens as well with a single image.

### Expected Behavior
To show the image with no blinking.

### Actual Behavior
Image is loading, then blink (the image disappear for a few ms then re-appear).

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/eoMNeX" target="_blank">https://codepen.io/thomaskientz/pen/eoMNeX</a>

### Other comments
Video of the blinking :

https://www.dropbox.com/s/jpm63bjedjdhgvp/vuetify%20image%20blink%20issue%20safari.mov?dl=0

**Comment by i-ira** [comment]
This also occurs on chrome when using any aspect ratio other that 16/9. It blinks & reappears after approx. 100ms

**Comment by sergkhl** [comment]
This bug also happing at image component page right now https://vuetifyjs.com/en/components/images?nocache (first example)
Workaround for me is to set transition to false.
So its possible that problem with __cachedImage generation: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VImg/VImg.ts#L123

**Comment by PeterBurner** [comment]
I can see the same effect in Safari when using a gradient  
![animation](https://user-images.githubusercontent.com/15011953/80362866-a9422880-8883-11ea-9815-13d419b5b256.gif)  
since I have a big list of `v-img` elements the effect is even worse

**Comment by touloumtzidis** [comment]
I am having the exact same issue. I should add that the issue is only occurring while using the lazy-src or placeholder attribute on the v-img component.

**Comment by yamaaki** [comment]
I had the same issue and found a workaround.

Make custom transition like below and specify it to v-img.

=== YOUR CSS ===
```css
.xxx-enter-active {
  transition opacity .3s ease-in-out;
}

.xxx-leave-active {
  transition none;
}

.xxx-enter, .xxx-leave, .xxx-leave-to {
  opacity: 0;
}

.xxx-enter-to {
  opacity: 1;
}
```

=== YOUR VUE FILE ===
```vue
v-img(
  src="/path/to/large/image.png",
  lazy-src="/path/to/small/image.png",
  transition="xxx"
)
```

For some reason, if you use v-img with lazy-src in v-for,  v-imgs fire "leaving transition" after loading images. 

So hiding everything on "leaving transition" should do the trick.
