### ISSUE TITLE
[Feature Request] Differentiate between row and column gutters on grid-list

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7018]
### Problem to solve
When you want the gutters between `v-flex` columns, but don't want the additional horizontal spaces between rows.

Trying to margin it out also becomes tedious and inconsistent when wrapping.

### Proposed solution
Let us differentiate between rows/columns with the size of the `grid-list`.

Rough Example: https://codepen.io/douglasg14b/pen/rbdOxV

Proposed Attributes (roughly, just to show the gist of what I mean):
- `column-gutters`
- `row-gutters`

**Even better would being able to adjust the column/row gutters independently.** So `row-size` and `column-size` for gutters instead of a toggle.

Additional Attributes that might be helpful?:
- `outer-gutters` Toggle gutters on the outside edges. Handy if you want to maintain the same outer width with large internal gutters
- `inner gutters` Toggle gutters on the inside. Not sure how useful, but compliments the above.

**Comment by johnleider** [comment]
`v-flex` is part of the legacy grid system and is no longer supported.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ibrahimBeladi** [comment]
@johnleider, the requested feature is still applicable for `v-row` and `v-col`.

**Comment by douglasg14b** [comment]
Wait, this is still a valid issue.....

**Comment by ibrahimBeladi** [comment]
The issue still persist, you can use dense and no-gutters. But you will end u with messed up gutters if you nest rows and columns
