### ISSUE TITLE
[Bug Report] can't close v-expansion-panel-content item programmatically

### ISSUE THREAD

**Issue by pdagosto** [vuetifyjs/vuetify#7022]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.5.20
**Browsers:** Other
**OS:** Linux

### Steps to reproduce
1. npm run dev
2. click on a panel
3. click on the Close button

### Expected Behavior
Clicking the Close button should close the open panel

### Actual Behavior
The panels data property of the HelloWorld component is updated properly as is the value prop of the v-expansion-panel component. However, the v-expansion-panel component corresponding to the open panel remains open and its data properties isActive and isBooted still have the value of true.

### Reproduction Link
<a href="https://github.com/pdagosto/Vuetify-Expansion-Panel-Bug" target="_blank">https://github.com/pdagosto/Vuetify-Expansion-Panel-Bug</a>

### Other comments
OK, I don't know if this is really a bug or if I'm misunderstanding how the expansion panel components work. What I'm trying to do in my actual application is close expansion panel content items programmatically in response to events. If there's a better way to do it than what I'm attempting then I'd be happy with an explanation of how to do that.

Also, my browser is Chrome v 68.03440.106 64-bit on Linux (CentOS 7)

**Comment by ibrahimBeladi** [comment]
[This codepen shows the problem (via cdn) and also a workaround.](https://codepen.io/ibrahimbeladi/pen/jRxMEE)
It seems that it is not working unless you change the array with another array instance. Changing a value in the array is not triggering any changes upon it (even with vm.$forceUpdate()). The workaround in my example is creating a new array via map or via slice in order to assign a **new array** to the variable.

**Comment by KaelWD** [comment]
The value watcher needs to be deep.

**Comment by pdagosto** [comment]
Ibrahim: thanks -  that works great!
Kael: is this something I can do in my code or something that needs to be done in the Vuetify component?

**Comment by KaelWD** [comment]
I was wrong. 

https://vuejs.org/v2/guide/list.html#Caveats
