### ISSUE TITLE
[Feature Request] Auto-Scroll to elements in V-Select

### ISSUE THREAD

**Issue by blakenorman37** [vuetifyjs/vuetify#7024]
### Problem to solve
When typing, it allows the user to see, in the menu, exactly which item they are selecting. Currently, when the user opens a select and type into it, the focus is automatically taken to the correct element, but if that element is not in the menu part that is visible, the user has no idea which value was actually selected.

### Proposed solution
The menu should scroll to the selected value.  The item is already correctly selected in the list, but that item should be displayed automatically.

**Comment by johnleider** [comment]
This is already possible with the **auto** prop. `<v-select menu-props="auto">`.

**Comment by KaelWD** [comment]
I think this is in relation to #4853, and it does already scroll even without `auto`
