### ISSUE TITLE
[Bug Report] Text field with hint or error shifts content below it down

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#7025]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Focus into the first field
Notice the field below it shifts down a pixel or two

### Expected Behavior
The hint or error message appearing doesn't shift lower content down

### Actual Behavior
The hint or error message shift the content below them down

### Reproduction Link
<a href="https://codepen.io/Dylan-Chapman/pen/xejjva" target="_blank">https://codepen.io/Dylan-Chapman/pen/xejjva</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/5f884878964afa2d48cc4d53e47a1f35958379c9

**Comment by jacekkarczmarczyk** [comment]
Fixed in 96f874e3f88d9b66838e7d221a9033eca5fa4c6b
