### ISSUE TITLE
[Feature Request] Data Tables items slot fallback

### ISSUE THREAD

**Issue by nwhessel** [vuetifyjs/vuetify#7026]
### Problem to solve
Provides fallback content when no items slot is defined on a Data Table

### Proposed solution
Provide the following fallback:

```
<tr>
    <td v-for="(header, index) in headers" :key="index">
        {{ item[header.value] }}
    </td>
</tr>
```

**Comment by nekosaur** [comment]
This has been implemented in 2.0
