### ISSUE TITLE
[Feature Request] Add @click:period event to timepicker

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7027]
### Problem to solve
A timepicker in a menu cannot save the AM/PM selection, as is seen in the docs: https://vuetifyjs.com/en/components/time-pickers which saves the selected time on `@click:minute`.

Clicking out of the menu erases the value after changing AM to PM or vice versa.

### Proposed solution
Add a click event for the selection of a period.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/PowgvyE
