### ISSUE TITLE
[Feature Request] Input append-icon and prepend-icon have disimilar behaviors, have ability to prepend icon into input area, not only outside

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7029]
### Problem to solve
Prepending an icon, but it being inside the input area instead of outside of it.

### Proposed solution
Add a preprend-icon option that prepends the icon inside the input.

**Prepended:**
![image](https://user-images.githubusercontent.com/1400380/56450993-5b90f880-62de-11e9-99ff-49ea4bf68776.png)

**Appended:**
![image](https://user-images.githubusercontent.com/1400380/56451003-719eb900-62de-11e9-8ca6-91e0c1010de0.png)

**Desired Prepended Result:**
![image](https://user-images.githubusercontent.com/1400380/56451160-381a7d80-62df-11e9-86ed-7babf2ee24f8.png)

**Comment by ibrahimBeladi** [comment]
As of v1.1 there is prepend-inner-icon property. It have almost your desired behavior, except for the label position.

**Comment by douglasg14b** [comment]
Oh nice. That pretty much does the trick. Would be nice if the label moved over to the left edge of the input, but that's workable for now.

I wonder why it's not listed in the docs. Guess this is a docs issue then.

**Comment by ibrahimBeladi** [comment]
Actually it is in the docs, in the API section. However, the API will be rewritten at some point to fix some issues with the current one.

**Comment by KaelWD** [comment]
yep.

The names are weird because prepend-inner/append-outer were added later and we didn't want to break the existing api.

**Comment by douglasg14b** [comment]
@ibrahimBeladi Oh, is it not a thing for the input component? These are the docs it seems to be missing from:

![image](https://user-images.githubusercontent.com/1400380/56460490-68eac900-6358-11e9-88bd-3bc3a9eafe34.png)

**Comment by ibrahimBeladi** [comment]
@douglasg14b, you are right, in this point, the baseline input component missing prepend-inner/append-outer. The other form components have them included.

@KaelWD, could you give it a look. It seems the form components needs a refactor to move prepend-inner/append-outer into the v-input component.
