### ISSUE TITLE
The proper way to remove paddings on v-container

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#703]
It's seems the application layout must have a ```v-container``` to work properly. But ```v-container``` has paddings and there is no way to gaplessly fill viewport by content: if we reset left and right paddings the mysterious scroll appears (see https://github.com/vuetifyjs/vuetify/issues/698)

**Comment by mornir** [comment]
<v-container fluid> doesn't do the trick?

**Comment by Darkside73** [comment]
No. Same issue

**Comment by johnleider** [comment]
Right now the only way to do this would be with a helper class, ```pa-0```. The container is designed to provide the specified padding according to MD. I know you had another ticket that references an issue on NUXT and I'll be taking a look at that as well.

**Comment by Darkside73** [comment]
Ok. Thanks

**Comment by johnleider** [comment]
Following up. ```fluid``` is simply for removing the viewport specific max-widths. The container by default should have padding to match spec. So in this case, my previous answer of simply adding ```pa-0``` would be the solution.

**Comment by mitar** [comment]
I had the same issue. I just removed `v-container` and just have `v-layout` now.

**Comment by LiangNex** [comment]
```pa-0``` works for ```v-container```  when ```fluid``` is not present, the work case for me is
```html
      <v-container ma-0 pa-0>
        ...
      </v-container>
```

**Comment by johnleider** [comment]
This will be changing in 2.0. The grid system is a bit dated and is receiving a face lift.

**Comment by alimuhammed37** [comment]
can any one write here the code for how to add a class in a v-container,
i am asking this here to follow the best Practice 

#TIA

**Comment by MajesticPotatoe** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
