### ISSUE TITLE
[Bug Report] Circular dependency:

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#7033]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Mac OS 10.14

### Steps to reproduce
npm i
npm run r:build

### Expected Behavior
rollup bundle

### Actual Behavior
 (!) Circular dependency: node_modules/vuetify/lib/components/VBreadcrumbs/index.js -> node_modules/vuetify/lib/components/VBreadcrumbs/VBreadcrumbs.js -> node_modules/vuetify/lib/components/VBreadcrumbs/index.js
(!) Circular dependency: node_modules/vuetify/lib/components/VTimePicker/VTimePicker.js -> node_modules/vuetify/lib/components/VTimePicker/VTimePickerTitle.js -> node_modules/vuetify/lib/components/VTimePicker/VTimePicker.js
(!) Circular dependency: node_modules/vuetify/lib/components/VTreeview/VTreeviewNode.js -> node_modules/vuetify/lib/components/VTreeview/VTreeviewNode.js

### Reproduction Link
<a href="https://ryl2jrnz2q.sse.codesandbox.io/" target="_blank">https://ryl2jrnz2q.sse.codesandbox.io/</a>

### Other comments
I just want to make a component that uses vuetify circular progress

WHY FORM VALIDATION NOT ACCEPT GITLAB REPO??
        https://gitlab.com/SumNeuron/fsmd

**Comment by SumNeuron** [comment]
This also demonstrates circular dependencies https://gitlab.com/SumNeuron/nuet

**Comment by KaelWD** [comment]
It's just a warning

https://github.com/rollup/rollup/issues/1978
https://github.com/rollup/rollup/issues/2271

Vuetify is also only tested with webpack

**Comment by SumNeuron** [comment]
@KaelWD  may just be a warning but extends build time 10 fold

**Comment by KaelWD** [comment]
10 fold compared to what?

**Comment by nekosaur** [comment]
This issue is closed due to lack of activity. If you believe that this issue still exists, please create a new [issue](https://issues.vuetifyjs.com) or join us on [Discord](https://community.vuetifyjs.com) to discuss it further.

**Comment by SebastianNiemann** [comment]
While it would be nice to avoid circular dependencies, as it can easily introduce bugs later on (when top-level code immediately requires a dependency), rollup will still compile and (at least for our projects) can handle it quite fast (by more or less randomly choosing which it should import first). In the end, it is the same way as webpack handles this issue (even if it is not reported by webpack).

However, what bothers me more is this weird self-dependency in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTreeview/VTreeviewNode.ts, where the module imports itself (`import VTreeviewNode from './VTreeviewNode'`).
