### ISSUE TITLE
[Feature Request] disable pagination on fast page switching

### ISSUE THREAD

**Issue by eafomi4ev** [vuetifyjs/vuetify#7035]
### Problem to solve
Allow blocking of page switching buttons when an asynchronous request occurs.
Now if you quickly turn the pages forward, and the answer to the request for the last page comes faster than the request for the penultimate page, the data in the table will be displayed for the penultimate page, and the data in pagination will show that this is the last page.
[link to codepen example](https://codepen.io/anon/pen/MRXqVy?editors=1010)

### Proposed solution
add the ability to block pagination during a query

**Comment by nekosaur** [comment]
In 2.0 it will be possible to disable the next/previous buttons using a prop.
