### ISSUE TITLE
[Bug Report] FAB w/ v-speed-dial using v-avatar, v-avatar is offset

### ISSUE THREAD

**Issue by oliviermills** [vuetifyjs/vuetify#7038]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.0

### Steps to reproduce
1. Create a v-speed-dial with a FAB
2. Use a v-avatar with text or image inside it as the btn (instead of a v-icon)
3. Notice position of the v-avatar is offset

### Expected Behavior
Position of the v-avatar correct over the btn

### Actual Behavior
Position of the v-avatar offset over the btn

### Reproduction Link
<a href="https://codepen.io/anon/pen/zXaQKR?&editable=true&editors=111#anon-login" target="_blank">https://codepen.io/anon/pen/zXaQKR?&editable=true&editors=111#anon-login</a>

**Comment by ibrahimBeladi** [comment]
A workaround for that is:
`<v-avatar size="inherit">`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
