### ISSUE TITLE
v-select very slow and sluggish with many entries

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#704]
### Steps to reproduce
Create a `v-select` with many items (in my example 2000 which is from a real project).

### Versions

0.12.6

### What is expected ?

Clicking and selecting an item should not be sluggish.

### What is actually happening ?

Selection is very sluggish. 

In contrast a vue-multiselect (https://github.com/monterail/vue-multiselect) is very performant with the same amount of data: https://jsfiddle.net/r64s5yna/1/

### Reproduction Link

https://codepen.io/anon/pen/NgqPKV

**Comment by johnleider** [comment]
Infinite scroll did exist. Let me see why it isn't working.

**Comment by johnleider** [comment]
So this is because you are using the auto prop. Currently infinite scroll only works without it. If you remove that prop everything works as expected.

**Comment by duebbert** [comment]
Just fell over this issue again. It's not documented that the `auto` has problems with very large lists. Large selects are unusable when using with auto: https://codepen.io/anon/pen/QxJdGK

**Comment by nekosaur** [comment]
Please create an issue on the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) repo.

**Comment by duebbert** [comment]
Obviously an even better solution would be to actually fix this problem....

**Comment by johnleider** [comment]
Let me just wave my magical fix it wand.
