### ISSUE TITLE
[Bug Report] [Typescript] Missing property in VuetifyApplication interface definition

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#7040]
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.4

### Steps to reproduce
Refer to `$vuetify.application.insetFooter` in your code

### Expected Behavior
No linting errors

### Actual Behavior
`Property 'insetFooter' does not exist on type 'VuetifyApplication'.`

### Reproduction Link
<a href="https://github.com/vuetifyj/vuetify/blob/master/packages/vuetify/types/index.d.ts" target="_blank">https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/index.d.ts</a>

### Other comments
Same for `clientHeight` on the `$vuetify` root type
`Property 'clientHeight' does not exist on type 'VuetifyObject'.`
This one is less of an issue since it's possible to use `$vuetify.breakpoint.height`

I haven't checked the other properties, but there might be more properties missing, other than the two mentioned above (`application.insetFooter`, `clientHeight`)

**Comment by KaelWD** [comment]
> `clientHeight` on the `$vuetify` root type

I don't think that ever existed, and it certainly doesn't now.
