### ISSUE TITLE
[Bug Report] cdn.jsdelivr.net stable dist serves v.2.alpha CSS

### ISSUE THREAD

**Issue by rimutaka** [vuetifyjs/vuetify#7045]
### Versions and Environment
**Vuetify:** 1.5.12
**Last working version:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css serves `Vuetify v2.0.0-alpha.14`

https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css
```
@charset "UTF-8";
/*!
* Vuetify v2.0.0-alpha.14
* Forged by John Leider
* Released under the MIT License.
```

https://cdn.jsdelivr.net/npm/vuetify@1.5.12/dist/vuetify.min.css
```
/*!
* Vuetify v1.5.12
* Forged by John Leider
* Released under the MIT License.
```

### Expected Behavior
https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css should serve the latest stable, which is https://cdn.jsdelivr.net/npm/vuetify@1.5.12/dist/vuetify.min.css

### Actual Behavior
Vuetify components look completely broken.

### Reproduction Link
<a href="https://codepen.io/rimutaka/pen/axjMyr" target="_blank">https://codepen.io/rimutaka/pen/axjMyr</a>

**Comment by MajesticPotatoe** [comment]
Thanks for reporting this. Seems to be resolved now. 👍
