### ISSUE TITLE
[Bug Report] v-icon bug with icon 'visibility_on'

### ISSUE THREAD

**Issue by dmeskis** [vuetifyjs/vuetify#7046]
### Versions and Environment
**Vuetify:** 1.5.8
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.4

### Steps to reproduce
Use v-icon with 'visiblity_on'

### Expected Behavior
no excess padding

### Actual Behavior
much excess padding

### Reproduction Link
<a href="https://codepen.io/dmeskis/pen/YMjbvM" target="_blank">https://codepen.io/dmeskis/pen/YMjbvM</a>

**Comment by jacekkarczmarczyk** [comment]
https://material.io/tools/icons/?search=visibility&style=baseline
