### ISSUE TITLE
[Feature Request] Trying to show the current month is being viewed in <v-calendar>

### ISSUE THREAD

**Issue by cristianduque** [vuetifyjs/vuetify#7053]
### Problem to solve
Solves usability issue because it doesn't show the current year and month is currently showing

### Proposed solution
Provide a prop that provides the year and month while changing the view of months

**Comment by ClickerMonkey** [comment]
Showing the month/year is entirely up to the user - there are so many ways to visualize it it's left up to the user (tabs, just text, dropdowns, etc).

Listen to the @change event on the calendar, it sends an event with start and end timestamps whenever the calendar changes which days are viewed.

Those start and end timestamps on the event have the following properties:

- date (the yyyy-mm-dd string)
- day (day of the month, starting at 1)
- future (if this date is in the future relative to today)
- past (if this date is in the past relative to today)
- present (if this date is today)
- hour (the hour, 0-23)
- minute (the minute, 0-59)
- month (the month, 1-12)
- year (the year)
- weekday (the day of the week, 0 = Sunday)
- time (hh-mm, but this event is empty string)
- hasDate (true for this event)
- hasTime (false for this event)
