### ISSUE TITLE
[Bug Report] v-data-iterator fails to render v-list content-tag in A-La-Carte mode

### ISSUE THREAD

**Issue by someone1** [vuetifyjs/vuetify#7054]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux

### Steps to reproduce
1. npm run serve
2. Load Page
3. Open Console to see message that v-list is an unknown custom element
4. Result isn't styled under a list as expected

### Expected Behavior
No error, proper styling

### Actual Behavior
Error: Unknown custom element: <v-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Improperly styled.

### Reproduction Link
<a href="https://github.com/someone1/vuetify-di-test" target="_blank">https://github.com/someone1/vuetify-di-test</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/framework/a-la-carte#limitations
