### ISSUE TITLE
[Feature Request] Combobox search-input.sync or any autocomplete 

### ISSUE THREAD

**Issue by anthonycheng12** [vuetifyjs/vuetify#7058]
### Problem to solve
The autocomplete does not account for fuzzy autocomplete options. For example if someone misspelled the name james as jamed then the autocomplete option should still show james but because the text is not explicitly set to james then James won't show up as an autocomplete option. This is bothering because my autocomplete api gathers fuzzy results but they do not appear as an available option to pick because unless the letters align then the fuzzy results do not show up.

### Proposed solution
Allow the autocomplete to be determined by the api result's as well as what is typed in the box and not just solely what is typed in the input box.

**Comment by jacekkarczmarczyk** [comment]
Do you mean `no-filter` prop that lets you control the searching, whether it is done server side or in your component?

**Comment by anthonycheng12** [comment]
> Do you mean `no-filter` prop that lets you control the searching, whether it is done server side or in your component?

This worked thanks so much Jacek!
