### ISSUE TITLE
[Feature Request] Highlight the match for search string in "Treeview" component

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#7060]
### Problem to solve
It will be more user friendly. 

### Proposed solution
Changing the background colour of matching string would be good.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by softwareguy74** [comment]
I was going to open a request for this as well.  This is a VERY useful feature to have.
