### ISSUE TITLE
[Bug Report] in v-navigation-drawer components,the property of width is set to 100% invalid.

### ISSUE THREAD

**Issue by Bchuan** [vuetifyjs/vuetify#7062]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.6
**Browsers:** Google Chrome, Firefox 65.0
**OS:** Windows 10

### Steps to reproduce
In v-navigation-drawer components,the property of width is set to 100% invalid.

### Expected Behavior
set to 100%

### Actual Behavior
Finally set to 100px

### Reproduction Link
<a href="https://codepen.io/bchuan/pen/GLdEgE?&editable=true&editors=101" target="_blank">https://codepen.io/bchuan/pen/GLdEgE?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
The 1.5 navigation drawer must use px values for its width. This has been enhanced for v2.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by alhavizd** [comment]
you can do like this 
template
`<v-navigation-drawer :width="WindowsWidth">
    <v-btn class="ma-2 transparent" tile large color="teal" icon >
      <v-icon>mdi-close</v-icon>
    </v-btn>
  </v-navigation-drawer>`

and script
`export default {
  data: () => ({
    WindowsWidth: 256,
  }),
  created() {
    window.addEventListener('resize', this.handleResize)
    this.handleResize();
  },
  destroyed() {
    window.removeEventListener('resize', this.handleResize)
  },
  methods: {
    handleResize() {
      this.WindowsWidth = window.innerWidth;
    }
  }
}`
