### ISSUE TITLE
[Bug Report] Directive changing disabled property

### ISSUE THREAD

**Issue by mgohin** [vuetifyjs/vuetify#7063]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.4

### Steps to reproduce
Check the JSFiddle, a simple directive is disabling the element but the vuetify component is not disabled

### Expected Behavior
Dynamic set of property working, so I can dynamically disable any vuetify component already handling disabled property

### Actual Behavior
I took inspiration of https://codeburst.io/reusable-vue-directives-v-can-753bf54e563f to handle rights in my app. 
Vuetify seems to not be reactive when modifying property disabled with a directive

### Reproduction Link
<a href="https://jsfiddle.net/4zqgL7an/7/" target="_blank">https://jsfiddle.net/4zqgL7an/7/</a>

**Comment by jacekkarczmarczyk** [comment]
You're setting `disabled` attr on a `div` which has no effect (obviously it works for `input` element)

`vnode.componentInstance.disabled = true` (not sure if this is the best way but at least works as expected)

**Comment by nekosaur** [comment]
as a general rule, vue directives should really only manipulate the DOM, not components
