### ISSUE TITLE
[Bug Report] IE11 v-text-field input text is too low

### ISSUE THREAD

**Issue by BenShelton** [vuetifyjs/vuetify#7064]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.17
**Vue:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
This is probably easier to see in https://next.vuetifyjs.com/en/components/text-fields#prefixes--suffixes by going to that doc page in IE11. This is most obvious for the dollar currency example.

### Expected Behavior
The input should be aligned vertically with the prefix

### Actual Behavior
The input is a couple of pixels too low

### Reproduction Link
<a href="https://codepen.io/BenShelton/full/MRPZGx" target="_blank">https://codepen.io/BenShelton/full/MRPZGx</a>

### Other comments
Experimented adjusting the `line-height` on the input to fix this. It seems to work when changing the current value of `20px` down to `16px` but that messes up the alignment in Chrome then.

**Comment by BenShelton** [comment]
A workaround for this is to write some media query that targets IE11 and override the `line-height` there. This is an example I'm using now in a global stylus file (see https://stackoverflow.com/questions/20541306/how-to-write-a-css-hack-for-ie-11):

```stylus
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active)
  .v-text-field input
    line-height: 16px
```

**Comment by GianPaoloBuffo** [comment]
Hi all. Shouldn't the workaround be added as part of a future minor fix, instead of just closing the issue?
