### ISSUE TITLE
[Bug Report] IE11 Box-Shadow renders differently

### ISSUE THREAD

**Issue by BenShelton** [vuetifyjs/vuetify#7065]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.17
**Vue:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
This is more clearly evident when viewing the expansion panels at https://next.vuetifyjs.com/en/components/expansion-panels#usage but anything with elevation suffers the same problem

### Expected Behavior
Box shadow is meant to spread far enough to define an elevation "border"

### Actual Behavior
Components with low elevation look like they have no elevation

### Reproduction Link
<a href="https://codepen.io/BenShelton/pen/XQxvVL" target="_blank">https://codepen.io/BenShelton/pen/XQxvVL</a>

### Other comments
This is evidently a rendering issue with IE11 where `box-shadow` is way fainter than in other browsers. It seems doubling the 'spread' value in all instances of `box-shadow` just for IE provides a much closer appearance to Chrome.

**Comment by KaelWD** [comment]
IE11 support is limited to "usable". Each browser renders shadows slightly differently, this isn't something that can or should be fixed.
