### ISSUE TITLE
[Bug Report] Navigation-drawer strange behavior

### ISSUE THREAD

**Issue by QTCkarolym** [vuetifyjs/vuetify#7067]
### Versions and Environment
Vuetify: 1.5.9
Vue: 2.6.10
Browsers: Chrome 73.0.3683.75
OS: Windows 10 Pro 17134.648

### Steps to reproduce
It happens when i take all the letters inside the input and put the cursor outside the drawer and then i delete the content of the input i select before, the drawer the right side and stay show♥

### Expected Behavior
The drawer should be hidden when i closed♥

### Actual Behavior
The drawer is open and i'm not opening the drawer♥
![drawer](https://user-images.githubusercontent.com/46758150/56678968-ea609500-6691-11e9-9eb0-dea305e66bef.gif)

### Reproduction Link
https://codepen.io/qtckarolym/pen/eoQYqL

**Comment by KaelWD** [comment]
Duplicate of #6969
