### ISSUE TITLE
[Bug Report] v-menu with new syntax activator and click event

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#7069]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
See codepen

### Expected Behavior
Button display correctly (next to each other).
`<div class="v-menu"></div>` causes the return to the line

### Actual Behavior
Button are not displayed correctly owing to `<div class="v-menu"></div>` after activator in DOM
![Capture](https://user-images.githubusercontent.com/7659927/56685566-827e6e80-66d2-11e9-8c97-1ad39c529b2b.PNG)

### Reproduction Link
<a href="https://codepen.io/anon/pen/VNVepe" target="_blank">https://codepen.io/anon/pen/VNVepe</a>

**Comment by johnleider** [comment]
This is an unfortunate side effect of removing the activator from `v-menu`. Any ideas on what we could do @KaelWD ?

**Comment by KaelWD** [comment]
Duplicate of #6951

**Comment by usb248** [comment]
Any news ?
