### ISSUE TITLE
Select component needs to highlight

### ISSUE THREAD

**Issue by monkeybrother65** [vuetifyjs/vuetify#707]
I love the enhancements to the select component. This makes the select component much more usable. There are a few more things that would make it more polished.

1- when you tab to the select field it does not highlight. It is confusing to the user.
2- when the select component has the highlight. The user should be able to hit the delete key and it should null out the selection. For completeness the delete key should work wether the select drop-down is open or closed.

Thank you!!!

**Comment by johnleider** [comment]
This has been enhanced as of 0.13 release.
