### ISSUE TITLE
[Bug Report] v-date-picker locale error

### ISSUE THREAD

**Issue by horaciosolorio** [vuetifyjs/vuetify#7070]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.0

### Steps to reproduce
I set property locale="es-MX" and the months are display correctly in spanish, but de title when i don't select any date o more that two show "0 selected" , the selected word still is in english

### Expected Behavior
I expected when select other locale value the title of the calendar also change.

### Actual Behavior
The title for the calendar never change of lenguaje

### Reproduction Link
<a href="https://codepen.io/horaciosolorio/pen/mgQrgB" target="_blank">https://codepen.io/horaciosolorio/pen/mgQrgB</a>

**Comment by jacekkarczmarczyk** [comment]
Workaround: use `titleDateFormat` prop and provide you own formatter - `(date: string[]) => string`

**Comment by jcalderonbrierley** [comment]
I have the same issue with Japanese, how I can fix that?
