### ISSUE TITLE
[Feature Request] Validation rules to return a promise

### ISSUE THREAD

**Issue by mobsense** [vuetifyjs/vuetify#7071]
### Problem to solve
I need to determine if a field is unique when validating a form. To do this, I need to access the IndexedDB which is an async API. So I would like validation rules to be able to return a Promise.

### Proposed solution
Allow rules to return a Promise which when fulfilled will return true | Validation message | Exception. A rejected promise could be mapped into a generic 'validation failed' message.

**Comment by KaelWD** [comment]
Duplicate of #4231
