### ISSUE TITLE
[Bug Report] v-select as direct activator of v-menu does not work with v-on syntax

### ISSUE THREAD

**Issue by Quizart** [vuetifyjs/vuetify#7075]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
(See codepen) - create a v-menu with v-select (readonly) as activator. Works if you put `slot="activator"` on the v-select, or if you put the v-select inside `<template slot="activator">`, but not if you use the `<template v-slot:activator="{ on }">` `v-on="on"` or similar syntax.

Oddly, it once again works if you just wrap the select in anything at all, and put the v-on on the wrapper instead.

### Expected Behavior
v-select activates menu using v-slot:activator or #activator style syntax

### Actual Behavior
v-select does not activate menu using v-slot:activator or #activator style syntax (unless wrapped in another element)

### Reproduction Link
<a href="https://codepen.io/Quizart/pen/QPJOEy" target="_blank">https://codepen.io/Quizart/pen/QPJOEy</a>

**Comment by KaelWD** [comment]
v-select isn't re-emitting click events

**Comment by DRoet** [comment]
FYI: I had the same problem with VCheckbox earlier today

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity. If this is still present in the latest version, please submit a new issue with a reproduction.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
