### ISSUE TITLE
[Bug Report] Tabs and Items group: max property not applied

### ISSUE THREAD

**Issue by Akaryatrh** [vuetifyjs/vuetify#7076]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3776.0
**OS:** Mac OS 10.14.3

### Steps to reproduce
Add either a `v-tabs` component or `v-items-group` component. Add a property `max` with a value of `200` (and a `grow` property to `v-tabs`) as It has been done on [demo link](https://codesandbox.io/s/xj8pwqqv7w).

### Expected Behavior
Component should not be wider than 200px

### Actual Behavior
Component takes full width of available space

### Reproduction Link
<a href="https://codesandbox.io/s/xj8pwqqv7w" target="_blank">https://codesandbox.io/s/xj8pwqqv7w</a>

**Comment by KaelWD** [comment]
The description is incorrect, and should not propagate to VTabs. It's actually to set the number of selections with `multiple`

**Comment by Akaryatrh** [comment]
Understood, thanks for your answer 👍
