### ISSUE TITLE
[Bug Report] V-Navigation-Drawer stays hidden upon resizing of window to lgAndUp

### ISSUE THREAD

**Issue by mrspinn** [vuetifyjs/vuetify#7078]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.13.6

### Steps to reproduce
- Start with breakpoint lgAndUp
- Resize window to mdAndDown, navigation drawer is hidden
- Resize window to lgAndUp, navigation drawer stays hidden while other components react to breakpoint

### Expected Behavior
- Navigation drawer should fluidly switch between breakpoints upon resize
- Navigation drawer should re-appear when switching from medium to large breakpoints

### Actual Behavior
- Navigation drawer switches to mdAndDown state just fine, but does not switch back to lgAndUp state

### Reproduction Link
<a href="https://codepen.io/mrspinn/pen/GLwZOX" target="_blank">https://codepen.io/mrspinn/pen/GLwZOX</a>

### Other comments
This appears to happen it both 1.5.13 and 2.0.0

**Comment by KaelWD** [comment]
You have `disable-resize-watcher`, of course it won't react to resize. It works correctly if you remove that prop. Additionally what you're doing on `v-content` is redundant, it'll already do margins automatically if you add `app` to the corresponding components.
