### ISSUE TITLE
[Bug Report] Dark theme colors not applying

### ISSUE THREAD

**Issue by waszqba** [vuetifyjs/vuetify#7084]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.17
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
Create a sample app with vuetify@next
create color themes for light and dark variant, both including 'primary' property according to the `next` version of docs
add an app-bar
give it a `primary` class
Run app
change `v-app`'s mode to dark

### Expected Behavior
dark theme's primary color should be applied

### Actual Behavior
light theme's primary color stays on display.

### Reproduction Link
<a href="https://github.com/waszqba/vuetify-theme-example" target="_blank">https://github.com/waszqba/vuetify-theme-example</a>

### Other comments
Light theme's color palette is recognized correctly, but the dark theme seems to be completely ignored except for basic dark and light backgrouds and text color inversion

**Comment by KaelWD** [comment]
It's now `theme.dark` in the vuetify options.

**Comment by waszqba** [comment]
ok, so I guess I have to use ut like this:
```js
return default new Vuetify({
  theme: {
    light: {
      primary: '#123123'
    },
    dark: {
      primary: '#321321'
    }
  }
})
```
is that correct? if yes, is should it work in alpha.17? I'm trying to make it work with no success so far

**Comment by waszqba** [comment]
ok, I've done some digging, it seems that 
```js
export default new Vuetify({
  theme: {
    dark: true,
    themes: {
      light: {
        primary: colors.purple,
        secondary: colors.grey.darken1,
        accent: colors.shades.black,
        error: colors.red.accent3,
      },
      dark: {
        primary: colors.blue.lighten3,
        secondary: '#ff0000',
      },
    },
  },
});
```
Works just fine, but those classes were only applied when `$vuetify.theme.dark` is being changed

**Comment by mrodal** [comment]
@KaelWD, @waszqba is right, tie dark colors are only applied when setting dark to true.. but not if the default is light and some element is applied the dark property
