### ISSUE TITLE
[Bug Report] First window content leaves window boundaries visibly before disappearing

### ISSUE THREAD

**Issue by ToniTornado** [vuetifyjs/vuetify#7088]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
It DOES NOT happen in the linked codepen that I created from the link in the docs, but it DOES in the original examples in the docs at https://vuetifyjs.com/en/components/windows#windows (and in my app).

### Expected Behavior
All content outside the window boundaries is hidden.

### Actual Behavior
Window content moves visibly up or left outside of the window boundaries but only on first change after page load.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZZwdGE" target="_blank">https://codepen.io/anon/pen/ZZwdGE</a>

### Other comments
Here is a video showing the effect in action: https://imgur.com/rbbrYnY
I did not find a real reason for this to happen. In my app it started appearing after adding rules to a text field in the second step of my wizard OR if I set the second step (this.step = 'enterPassword') from a resolving promise (checking an email address with the server) instead of setting the step immediately.

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 2.0

**Comment by MatthewAry** [comment]
Yes, it's fixed in 2.0. But 1.5+ is going into LTS and I think this qualifies as a bug that will get fixed.

I disagree with the closure of this issue.

**Comment by MatthewAry** [comment]
Scratch that, it's not fixed in 2.0
