### ISSUE TITLE
[Bug Report] Using custom filter in v-data-table triggers customFilter method twice

### ISSUE THREAD

**Issue by yosafatade** [vuetifyjs/vuetify#7090]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu 18.04

### Steps to reproduce
In v-text-field:
remove: `v-model="search"`
then add: `@change="searchItems" `

In a data table add:
```
:custom-filter="customFilter"
```

then add following methods:
```
methods: {
      customFilter (items, search, filter, headers) {
        console.log("---customFilter---")
        console.log(items);
        console.log(search);
        if (search === "") return items;
        return items.filter(item => {
          return item.name.includes(search);
        });
      },
      searchItems (val) {
        this.search = val;
      }
    }
```

### Expected Behavior
The `customFilter` should be triggered only once. 

### Actual Behavior
The `customFilter` is triggered twice.

### Reproduction Link
<a href="https://codepen.io/yosafatade/pen/axMooM" target="_blank">https://codepen.io/yosafatade/pen/axMooM</a>

**Comment by KaelWD** [comment]
`computed.filteredItems` -> `filteredItemsImpl` has side-effects

**Comment by KaelWD** [comment]
Fixed already in 2.0

**Comment by yosafatade** [comment]
Thank you for the response @KaelWD 

Since I can't use v2 in production, I make a work around for v1.
So instead of using `custom-filter` prop, I make a computed property to filter the data.

See: https://codepen.io/yosafatade/pen/gyEKeW

**Comment by KaelWD** [comment]
That's an acceptable workaround. You might want to change the slot to `no-data` now though.
