### ISSUE TITLE
[Bug Report] V-slider tick click should change value

### ISSUE THREAD

**Issue by zajca** [vuetifyjs/vuetify#7094]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Linux x86_64

### Steps to reproduce
Open link click in any tick circle

### Expected Behavior
On tick click value of slider should change

### Actual Behavior
Nothing happened

### Reproduction Link
<a href="https://codepen.io/zajca/pen/BEbgQP?editors=1010" target="_blank">https://codepen.io/zajca/pen/BEbgQP?editors=1010</a>

**Comment by johnleider** [comment]
This has been resolved for v2. https://codepen.io/johnjleider/pen/GLbjox?editors=1010

**Comment by zajca** [comment]
Sorry for late response, but this is issue relevant to v1.5.x this means that there is not going to be any bug-fixing for other than v2?
