### ISSUE TITLE
[Bug Report] v-bottom-nav not closeable if custom height is bigger than standard height

### ISSUE THREAD

**Issue by euberdeveloper** [vuetifyjs/vuetify#7095]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Make a v-bottom-nav with height bigger than standard, such as 100

### Expected Behavior
When value is false, or the property bound to its v-model directive is false, the v-bottom-nav should be hidden. It should go down of its full height.

### Actual Behavior
The v-bottom-nav is still visible, it is went down only of the default height. The remaining part is still visible.

### Reproduction Link
<a href="https://codepen.io/euberdeveloper/pen/vMPdGN" target="_blank">https://codepen.io/euberdeveloper/pen/vMPdGN</a>

**Comment by johnleider** [comment]
This is resolved for v2.
