### ISSUE TITLE
Collapsible / Expendable with Angle

### ISSUE THREAD

**Issue by mindbits** [vuetifyjs/vuetify#71]
Hello and thank you for your hard work. 

The Expendables / Collapsibles don't have an angle-right that transforms by 90deg when clicked, so from an UX point of view, the users don't expect that clicking on the header will reveal more options. 

Is this easy to add?

**Comment by johnleider** [comment]
Yes it is easy to add, and it is something I'm hoping to be part of the next release. The collapsible component is currently being refactored along with numerous others.
