### ISSUE TITLE
[Feature Request] Add Direction To v-autocomplete Like Up, Down

### ISSUE THREAD

**Issue by bubundas17** [vuetifyjs/vuetify#7101]
### Problem to solve
Well, I wanna implement a search autocomplete to an input field. The v-autocomplete working really good. but the main issue is sometimes in different screen sizes. The autocomplete results are going upwards, but I like to make them go downwards no matter what. 

### Proposed solution
We can solve the issue by adding a prop to the v-autocomplete.
like 
direction="auto" <-- Automatically Position 
direction="up" <-- allow the suggestions to go upwords
 direction="down" <-- allow the suggestions to go downwords
direction="left" 
direction="right"

etc.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
