### ISSUE TITLE
[Bug Report] VDialog onFocusin event error

### ISSUE THREAD

**Issue by kamu22rus** [vuetifyjs/vuetify#7105]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
click button

### Expected Behavior
open dialog without errors

### Actual Behavior
error

### Reproduction Link
<a href="https://jsfiddle.net/evysq5pd/" target="_blank">https://jsfiddle.net/evysq5pd/</a>

### Other comments
I think we need change "event" variable to "e" variable on 200 row on https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDialog/VDialog.js

**Comment by johnleider** [comment]
This is resolved for v2.

**Comment by ekosynth** [comment]
I'm still getting this error in v2

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by ShawshankLin** [comment]
> This is resolved for v2.

v1.5.16 how to solve?
