### ISSUE TITLE
[Bug Report] VCalendar not rerendered when now props change

### ISSUE THREAD

**Issue by Ogromny** [vuetifyjs/vuetify#7106]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Linux x86_64

### Steps to reproduce
Pass a date to now props in VCalendar

### Expected Behavior
Why the date in VCalendar isn't the 2019/04/03 ?

### Actual Behavior
The date isn't correct 

### Reproduction Link
<a href="https://codepen.io/ogromny-the-sasster/pen/pBmjrG" target="_blank">https://codepen.io/ogromny-the-sasster/pen/pBmjrG</a>

### Other comments
Sorry for the very short question, english isn't my native language

**Comment by ClickerMonkey** [comment]
`:now` is only used for overriding today, today is something separate than "the day(s) that I'm viewing".

You want `v-model="date"`
