### ISSUE TITLE
[Bug Report] Checkbox with parent click event

### ISSUE THREAD

**Issue by poganytamastsys** [vuetifyjs/vuetify#7107]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Create a container with checkbox inside. Clicking inside the container must toggle checkbox. Clicking on the checkbox must toggle the checkbox

### Expected Behavior
Clicking on the checkbox should not bubble up to parent, resulting a parent click => double toggleing the checkbox

### Actual Behavior
Clicking a checkbox toggles it. But event bubbles up to parent, and toggles the checkbox again.

### Reproduction Link
<a href="https://codepen.io/anon/pen/jRoqdZ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/jRoqdZ?&editable=true&editors=101</a>

### Other comments
The only solution I found is to add the same @click.stop="checkbox1 = !checkbox1" to the checkbox itself. Shouldn't be a better way?

**Comment by nekosaur** [comment]
Use the `.self` modifier
