### ISSUE TITLE
[Bug Report] Selectable components like dropdown, autocomplete or selects open a popup when the browser has a popup blocker installed

### ISSUE THREAD

**Issue by EliuTimana** [vuetifyjs/vuetify#7109]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108, Mozilla Firefox, Google Chrome
**OS:** Linux x86_64, Windows, Linux

### Steps to reproduce
Install a popup blocker extension in your browser
when you hit ENTER in a dropdown item, like autocomplete or select, instead of selecting the item, it opens a popup, this is solved disabling the extension but is not an expected behavior

### Expected Behavior
When press ENTER in an element, it should be selected instead of open a popup

### Actual Behavior
It opens a popup instead of selecting the item.

### Reproduction Link
<a href="https://codepen.io/anon/pen/JVqvjE" target="_blank">https://codepen.io/anon/pen/JVqvjE</a>

### Other comments
I think the problem is that the item in the select is an anchor tag, it would be different if the element was a div or span.
This is the extension, you can install it on chrome or firefox.
http://www.poperblocker.com

**Comment by KaelWD** [comment]
This is a bug in the extension.

**Comment by EliuTimana** [comment]
You are right, it's an extension bug, I'm sorry :disappointed: I changed it and now it works perfectly, thanks for your time. :smiley:
