### ISSUE TITLE
[Bug Report] v-text-field clearable doesn't respect readonly=true

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#7111]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
Make a v-text-field readonly and clearable and note that it not only shows the clearable button, but also clears the field.

### Expected Behavior
Read only should mean read only and clearable button shouldn't even show.
(numeric inputs still show buttons for adjusting value when readonly but at least they don't do anything)

### Actual Behavior
click clears, should not even present the clear button when readonly and definitely not clear the control

### Reproduction Link
<a href="https://codepen.io/anon/pen/GLaPwz" target="_blank">https://codepen.io/anon/pen/GLaPwz</a>

**Comment by KaelWD** [comment]
This is intentional, it's easier to toggle both props than it would be to re-implement the clearable functionality yourself.

**Comment by WhatFreshHellIsThis** [comment]
> 
> 
> This is intentional, it's easier to toggle both props than it would be to re-implement the clearable functionality yourself.

Wait...what?  What are you saying here, I'm confused.  You're certainly not suggesting this broken confusing functionality is actually acceptable are you?

**Comment by KaelWD** [comment]
I am, #7175 was reverted because it broke the [date picker examples](https://vuetifyjs.com/en/components/date-pickers#date-pickers-formatting-date-using-external-libs) ([#7187](https://github.com/vuetifyjs/vuetify/pull/7187#issuecomment-492257755)). If you don't want a readonly field to be clearable simply do `<v-text-field :readonly="isReadonly" :clearable="!isReadonly">`

**Comment by WhatFreshHellIsThis** [comment]
Let me get this straight:  you're deliberately keeping a bug and removing a fix and suggesting every developer everywhere who uses this control must institute a workaround because to fix it would break an _*example*_!?  Astonishing!

**Comment by velly** [comment]
Having the RD solve this issue might not be the smoothest solution, but it's not a big deal.
