### ISSUE TITLE
Background color not changing

### ISSUE THREAD

**Issue by akkhan20** [vuetifyjs/vuetify#7113]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.6
**Browsers:** Mozilla Firefox, Google Chrome
**OS:** Windows 10

### Steps to reproduce
import 
@import '~vuetify/src/stylus/theme.styl'
and changing this
$material-light.background = '#fff'

### Expected Behavior
should change the background color from grey to white

### Actual Behavior
Background color doesn't change

### Reproduction Link
<a href="https://codepen.io/akkhan20/pen/axreVW" target="_blank">https://codepen.io/akkhan20/pen/axreVW</a>

### Other comments
Changing the font works that means the stylus file is functioning fine but for changing the background color the above mentioned changes doesn't reflect

**Comment by johnleider** [comment]
The provided reproduction will not do anything, stylus is already compiled at that point. We would need a project based reproduction.

**Comment by akkhan20** [comment]
is that the right way to do though? i might have some configuration problem on my side then

**Comment by KaelWD** [comment]
See https://discordapp.com/channels/340160225338195969/340215499398840331/553604239407185930

**Comment by akkhan20** [comment]
To show the problem i have spent a few hours now to setup a codesanbox where we can override stylus but failed to do so because it throws errors that i can't even read, i'v never done that before..
and i have asked it on discord 3 times since this morning and asked already several times last day,

**vuetify/src/stylus/settings/_theme.styl**
```
// Theme
// ============================================================
$body-font-family := 'Roboto', sans-serif
$font-size-root := 14px
$line-height-root := 1.5

// Material Design - https://material.io/guidelines/style/color.html#color-usability
// ============================================================
$material-light := {
  status-bar: {
    regular: $grey.lighten-2,
    lights-out: rgba($shades.white, .7)
  },
  app-bar: $grey.lighten-4,
  background: $grey.lighten-5,
  cards: $shades.white,
....
```
body font and line height are changing but the background doesn't when done like this:
```
$body-font-family = 'Rubik', sans-serif;
$font-size-root = 2
$material-light.background = '#fff'
```
though they are all defined in the same file.

**Comment by DevelGitH** [comment]
I have the same problem, the background color of the vuetify app is not changing (the font family is working). Here is my code:
`
@import '~vuetify/src/stylus/theme.styl'

$material-dark.background = #353535
$body-font-family = 'Open Sans'

// For a-la-carte
@import '~vuetify/src/stylus/app'
`
According to the vuetify documentation it should be possible to override like this the app values: https://vuetifyjs.com/en/framework/theme#changing-values

**Comment by jacekkarczmarczyk** [comment]
For modifying sass variables in 2.0 see https://next.vuetifyjs.com/en/framework/theme#modifying-sass-variables
