### ISSUE TITLE
[Bug Report] Tooltip hover not working on phone

### ISSUE THREAD

**Issue by Albertbol** [vuetifyjs/vuetify#7114]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Windows

### Steps to reproduce
Open the pen code with vue and vuetify imported on the phone (i use iphone) (https://codepen.io/albertb/pen/qwGegx) 
or start basic vue app and install vuetify take first tool tip code example from vuetify official docs (https://vuetifyjs.com/en/components/tooltips#tooltip) paste it to your code and open on the phone.

### Expected Behavior
Expected to have tool tip tapping on the elements, tool tip should disappear on tapping outside element that was activated

### Actual Behavior
Only first element button have effect on tap, but tool tip does not disappear on tapping outside with the phone, ,another elements dont show tool tip.

### Reproduction Link
<a href="https://codepen.io/albertb/pen/qwGegx" target="_blank">https://codepen.io/albertb/pen/qwGegx</a>

### Other comments
When i open vuetify docs with the phone, that demo is working i can click every icon and effect is working.
Also i added programmatic icon example to code pen , whish is showing that element wrapped in the button is showing tooltip but tapping outside gives no effect.

**Comment by Albertbol** [comment]
what is super weird, is if i add to template https://vuetifyjs.com/en/components/floating-action-buttons#buttons-floating-action-button floating action button , hover on icons is working aswell without any changes... is its something with ` <template v-slot:activator>` vs  `<template v-slot:activator="{ on }">` on tool tip ?

**Comment by KaelWD** [comment]
Works fine on android

Does Safari emulate hover on tap or do you need to hold it?

**Comment by Albertbol** [comment]
Its not working on the iphone with chrome or safari. 
Hover effect on vuetify and floating action button works perfect on tap, long tap is selecting icon as a text.

**Comment by Albertbol** [comment]
As I said before adding to page layout floating action button is solving this issue which I cannot understand why, if I take floating action button out, same problem appears , might be some issue with ‘slot activator’ ?

**Comment by KaelWD** [comment]
You mean if you have a FAB then the hover works on other elements too?

**Comment by Albertbol** [comment]
Exactly

**Comment by Enghouse-CCSP-PS** [comment]
we have same issue on IOS, what is workaround ? Adding v-card as parent object did not help

**Comment by Albertbol** [comment]
> we have same issue on IOS, what is workaround ? Adding v-card as parent object did not help
@Enghouse-CCSP-PS 
apply this class to parent div:
```
.transform {
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
}
```

**Comment by HoneyB4dger** [comment]
Same problem, menu/tooltip hover never closes, unless the touchend is on v-card... Looking at what's happening none of the close events for the activator button are firing - 'blur', 'mouseout', 'touchleave'.

A workaround is to detect if you are on a touch screen and use open-on-click in that instance.

`
<v-menu
  open-on-hover="!touch"
>
    ...
</v-menu>

mounted() {
  this.touch = matchMedia('(hover: none), (pointer: coarse)').matches
}
`

**Comment by shawn-p-m** [comment]
This issue is also happening on Safari and chrome of iphone for the open-on-hover of the v-speed-dial component.

**Comment by alitofresko** [comment]
I suppose the issue is related to the incompatibility of open-on-focus and open-on-click.
Try to set open-on-focus to false
