### ISSUE TITLE
[Feature Request] Reset vertical scroll on nav drawer

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#7119]
### Problem to solve
Ability to reset the position using code. Useful for when switching pages in SPA. Right now I have to do this, which targets a internal class.

    watch : {
        'drawer_state' : function(new_val, old_val) {
            // if drawer opened, reset scroll to top
            if (new_val) {
                this.$el.querySelector(".v-navigation-drawer").scrollTop = 0;
            }
        }
    }

### Proposed solution
Have a binding to vertical scroll (attribute).

**Comment by KaelWD** [comment]
You can use $refs or add a custom class to the drawer

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

**Comment by TheInvoker** [comment]
But how can I do it without hardcoding any internal classes?
