### ISSUE TITLE
vue-cli webpack template with v-card img load does not work properly

### ISSUE THREAD

**Issue by kaijajan** [vuetifyjs/vuetify#712]
### Steps to reproduce

vue-cli webpack template project, and use v-card with img attribute to load image (relative path)
but the path did not transpiled by webpack
And I also check the source code of v-card, it adds css style to load image
I tried the same way using div to load image, it works well.
But v-card did not transpile at all.

http://i.imgur.com/mOQ69hF.png
http://i.imgur.com/OBWLada.png

### Versions

Vue 2.3.3
Vuetify 0.12.6

### What is expected ?

v-card loads image as regular vue-cli project

### What is actually happening ?

image url did not transpile

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by kaijajan** [comment]
# reproduction repo
https://github.com/kaijajan/vuetify-bug
neither vue-cli official template nor vuetifyjs template works

**Comment by johnleider** [comment]
I see the issue, I honestly have no idea how to resolve this. Looking for help from anyone that can.

**Comment by iqbalsafian** [comment]
Could it be resolved by using this? https://github.com/bholloway/resolve-url-loader

**Comment by johnleider** [comment]
Is this still an issue as of 0.13 release?
