### ISSUE TITLE
[Bug Report] dialog is disabled when you select a text and release on overlay

### ISSUE THREAD

**Issue by danielpfs** [vuetifyjs/vuetify#7121]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Open dialog
Click and hold with left button mouse the text from dialog
Drop the selection on overlay

### Expected Behavior
Dialog keeps active after you select the text

### Actual Behavior
Dialog is disabled when you select the text

### Reproduction Link
<a href="https://codepen.io/anon/pen/KYjRYp" target="_blank">https://codepen.io/anon/pen/KYjRYp</a>

**Comment by KaelWD** [comment]
Duplicate of #6969
