### ISSUE TITLE
[Bug Report] hidden-sm-and-down not working correctly with custom breakpoints

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#7124]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.6
**Browsers:** Chrome 74.0.3729.108
**OS:** Linux x86_64

### Steps to reproduce
-> override $grid-breakpoints in stylus to 
  xs: 0
  sm: 576px
  md: 768px
  lg: (992 + 16)px
  xl: (1200 + 16)px
-> use class="hidden-md-and-up" in a element
-> use class="hidden-sm-and-down" in another

### Expected Behavior
one and only one element should be visible, and the breaking point must be in 768px

### Actual Behavior
hidden-md-and-up breaks in the right point but hidden-sm-and-down doesn't

### Reproduction Link
only as an example because i can't really override stylus because it needs to be compiled
<a href="https://codesandbox.io/s/2xjwq1q96j" target="_blank">https://codesandbox.io/s/2xjwq1q96j</a>

### Other comments
Im not using A-la-carte elements.
I'm overriding stylus and $vuetify object as the documentation says.

**Comment by joelpro2** [comment]
hidden-sm-and-down is breaking in the default 960px and hidden-md-and-up is breaking in custom 768px

**Comment by jacekkarczmarczyk** [comment]
This is probably because you have set breakpoints only in stylus, but you should set them also in js 
https://next.vuetifyjs.com/en/framework/breakpoints#usage

This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by joelpro2** [comment]
I'm not sure if you even opened my codesandbox.
i do have it set on my main.js in the same way that it is on my codesandbox, like i said in **Other Comments**

**Comment by jacekkarczmarczyk** [comment]
Honestly no ;) I've just noticed the "needs reproduction" label
But still you can provide a ready-to-run github repo that reproduces the issue.
Also note that we switched to Sass in 2.0 and this issue as non-critical probably won't be touched, but if you can provide a repo with vuetify 2.0 and Sass and there's still a problem then we'll definitely will take a closer look

**Comment by KaelWD** [comment]
The old documentation for stylus variables was not accurate with a-la-carte. It has been updated now on next.vuetifyjs.com
