### ISSUE TITLE
[Feature Request] make v-bind content-class property to accept object variable same as class property does

### ISSUE THREAD

**Issue by maggot99999** [vuetifyjs/vuetify#7125]
### Problem to solve
Simplifies the complex logic and unifies v-bind method for class and content-class properties

### Proposed solution
Accept object for content-class properties

**Comment by jacekkarczmarczyk** [comment]
Which components do you mean (except those having `content-class` prop)?

**Comment by KaelWD** [comment]
In vuetify 3 you can just use `class` normally.
