### ISSUE TITLE
[Feature Request] Remove the <a> tag's outline in Firefox

### ISSUE THREAD

**Issue by danclive** [vuetifyjs/vuetify#7128]
### Problem to solve
I found that in the Firefox browser, clicking the <a> tag will leave an unsightly dashed border, and chrome is not available. Can it be removed?

![2019-05-03 15-41-09屏幕截图](https://user-images.githubusercontent.com/7814847/57124879-f3501580-6db9-11e9-88c9-8cf586e58f75.png)

### Proposed solution
With my attempt, I can add `a:focus{ outline:none }` to the [_reset.styl](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/generic/_reset.styl#L94).

Or is there any other better way?

**Comment by jacekkarczmarczyk** [comment]
Fixed in 2.0
