### ISSUE TITLE
Using only specific components

### ISSUE THREAD

**Issue by mendiomon** [vuetifyjs/vuetify#713]
When i add vuetify to my page i get css conflicts, for example buttons get their own styles.

How can i use only specific components?

**Comment by mornir** [comment]
From the quick start page:

> While Vuetify attempts to not cause any css collision as much as possible, there is no guarantee that your custom styles will not alter your experience when integrating this framework into your existing project.

Importing single components is not supported by default #330

**Comment by johnleider** [comment]
mornir is correct.
