### ISSUE TITLE
[Bug Report] Native date/time pickers are not opening on click of v-text-field

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [vuetifyjs/vuetify#7130]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
1. Click on text-field native time picker will open
2. close the picker
3. click on append-icon, native picker not opening.

### Expected Behavior
On Click of append-icon, native picker should open

### Actual Behavior
Native pickers should open, if we click on anywhere of the text-field

### Reproduction Link
<a href="https://codepen.io/grandhisubrahmanyam35/pen/PgMrrm?editors=1010" target="_blank">https://codepen.io/grandhisubrahmanyam35/pen/PgMrrm?editors=1010</a>

**Comment by KaelWD** [comment]
This would require us to stop propagation of the click event. You can do this yourself if you don't need it and want to use native pickers: https://codepen.io/anon/pen/arbNzN?editors=1010
