### ISSUE TITLE
[Bug Report] Step header sub-text causes vertical disalignment

### ISSUE THREAD

**Issue by daviian** [vuetifyjs/vuetify#7140]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Linux x86_64

### Steps to reproduce
As can be seen in the codepen the first example is fine.
However, after adding a sub-text to one header the whole step-header bar (or at least the text within) moves downwards.

### Expected Behavior
Text should stay vertically centered

### Actual Behavior
Text moves downwards.

### Reproduction Link
<a href="https://codepen.io/anon/pen/LoYvzY" target="_blank">https://codepen.io/anon/pen/LoYvzY</a>

### Other comments
Setting `line-height: 1` on `.v-stepper__header` resolves issue

**Comment by johnleider** [comment]
Unfortunately this is not going to make it into LTS. As of the later versions it is resolved and I suggest moving to the latest 2.x release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
