### ISSUE TITLE
[Bug Report] v-timeline-item leaks callout style (side triangle) to child cards

### ISSUE THREAD

**Issue by mrts** [vuetifyjs/vuetify#7142]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
Create a `v-timeline` with a `v-timeline-item` that contains a `v-card` (timeline item card). Add other `v-card`s into the timeline item card (child cards).

See the CodePen example.

### Expected Behavior
The child cards do not have a callout triangle on the side.

### Actual Behavior
The child cards do have a callout triangle on the side.

### Reproduction Link
<a href="https://codepen.io/mrts/pen/JqjQgx" target="_blank">https://codepen.io/mrts/pen/JqjQgx</a>

### Other comments
The CSS rule that creates the callout triangle should apply only to immediate children of `v-timeline-item`, see e.g. https://stackoverflow.com/questions/9462432/how-to-apply-css-to-only-immediate-children-of-a-certain-class

**Comment by jacekkarczmarczyk** [comment]
Fixed in 2.0 https://codepen.io/anon/pen/EzGEmr
