### ISSUE TITLE
[Feature Request] v-btn prop color unable to use variants

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#7143]
### Problem to solve
Enable the use of v-btn color="primary.darken1"

### Proposed solution
prop color splits in "." or "-" then it loads the color with variant or color with base
 ```Javascript
 let auxColor = color.split('.')
buttonColor = 'var(--v-' + auxColor[0] + '-' + auxColor[1] || 'base')
```

**Comment by KaelWD** [comment]
`primary darken-1`

**Comment by joelpro2** [comment]
> `primary darken-1`

There's a way to define custom named variants? Like theme: { primary: { ghost: '#231242' } }
