### ISSUE TITLE
[Feature Request] Elevation color

### ISSUE THREAD

**Issue by maggot99999** [vuetifyjs/vuetify#7147]
### Problem to solve
- Adds ability to customize color for elevation.
- Adds better elevation effect since black color of elevation not always suitable for all color-based components

### Proposed solution
- Add color property to hover component
- Inherent color from component eg. inherent blue color of button to elevation.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ColinLaws** [comment]
I don't mean to beat a dead horse, but I just happened to need this functionality in an application that I am building. For some users who have cards with dark themes, they may better emphasize elevation by using color. 

For example, the elevation difference between the top and bottom cards in this image are not easily distinguishable. This is using Vuetify's built in dark mode. Again, color could probably really help here, although I understand it's not exactly material design spec.

![example](https://user-images.githubusercontent.com/10246886/57724616-35e6dd00-7659-11e9-82cd-c3d244231a3b.PNG)

**Comment by maggot99999** [comment]
Is there any objective reason this functionality should not be implemented even if Google, the publisher of Material Design design philosophy uses this color elevation in their own designs lately?

**Comment by michaelmov** [comment]
I was able to change the elevation color by overriding the following variables in my custom `variables.scss` file:

```
$shadow-key-umbra-opacity: rgba(var(--v-primary-darken4), 0.2);
$shadow-key-penumbra-opacity: rgba(var(--v-primary-darken4), 0.14);
$shadow-key-ambient-opacity: rgba(var(--v-primary-darken4), 0.12);
```

**Comment by michaelmov** [comment]
I was able to change the elevation color by overriding the following  3 variables in my project's `variables.scss` file with my custom color :

```
$shadow-key-umbra-opacity: rgba(#1a237e, 0.2);
$shadow-key-penumbra-opacity: rgba(#1a237e, 0.14);
$shadow-key-ambient-opacity: rgba(#1a237e, 0.12);
```

**Comment by ColinLaws** [comment]
Thanks so much for this @michaelmov I needed

**Comment by jffaust** [comment]
I would also like to know why this is not being considered. Material Design documentation for dark themes clearly uses color to represent elevation: https://www.material.io/design/color/dark-theme.html#properties

**Comment by adam-watkins** [comment]
If anyone is still having trouble solving this, published a [package ](https://github.com/adam-watkins/vue-glow) to solve this issue.

**Comment by shubh9415** [comment]
You can this using :root.

:root /deep/ .v-application .elevation-3{
  box-shadow: 0px 3px 3px 1px rgba(0, 0, 0, 0.01), 0px 3px 5px 0px rgba(0, 0, 0, 0), 0px 1px 11px 1px rgba(0, 0, 0, 0.1) !important;
}

**Comment by AtiaDjaber** [comment]
i solved it by using this css in app.vue :
.v-application .v-card {
  box-shadow: 0 0 20px rgb(0 0 0 / 10%) !important;
  -webkit-box-shadow: 0 0 20px rgb(0 0 0 / 10%) !important;
}
