### ISSUE TITLE
[Bug Report] Vuetify Data Table doesn't sort correctly when array object keys have special characters. 

### ISSUE THREAD

**Issue by jacksarle** [vuetifyjs/vuetify#7149]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3783.0
**OS:** Windows 10

### Steps to reproduce
1. Use a special character in an object key
2. Include said object key in data table as sort able 

### Expected Behavior
1. sort the rows based on the value in the column, 
2. or output an error as to why it can't sort.

### Actual Behavior
Nothing is sorted. 

### Reproduction Link
<a href="https://codepen.io/anon/pen/LoVjXw?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/LoVjXw?&editable=true&editors=101</a>

**Comment by wongwanchap** [comment]
This is because iron field data type is String instead of Number. One of the work around is to save the iron data in number and then add "%" at the template:
Change desserts data iron field from:
"x%" => x
Change template v-slot-items from:
<td class="text-xs-right">{{ props.item.iron }}</td> => <td class="text-xs-right">{{ props.item.iron}}%</td>

**Comment by jacksarle** [comment]
I think you misunderstand, I am not talking about the header labels but rather the internal data structure of the table. If you look in the code example I posted and look to how I split calories into cal.ories that is what I mean. when trying to sort by calories it no longer works, because in my data structure its key is cal.ories. 

this would be an easy fix by just changing the default sort function to index the object with bracket notation as opposed to dot notation which is how I'm assuming it does it now. 

ex. instead of items.key use items[key] to sort

**Comment by nekosaur** [comment]
This is because we allow one to specify a deeply nested property using `this.kind.of.structure`. It's probably not something that will change in the near future. What you can do is provide your own sort function using the `customSort` prop.

**Comment by jacksarle** [comment]
If it won't change then I at least think an error should be propagated out as to why its not sorting, or something needs to make note of it. If you are new to Vuetify this might not be apparent as to why it isn't working.

**Comment by nekosaur** [comment]
Although now that I think about it, I thought we'd changed the behaviour of `getObjectValueByPath` to fall back on just returning `obj[path]` if nothing else was found.

**Comment by jacksarle** [comment]
Yea, that would handle it if that was the case. I think even if it doesn't get support though it should throw an error to the console. As of right now you hit the header to sort and nothing happens.

**Comment by johnleider** [comment]
@nekosaur are you still trying to get this into 2.2.x?

**Comment by thatygama** [comment]
Maybe what happened to me could happen to someone else researching this error. Every :headers="variable_here" will contain an array with at least an object and that object should contain at least one text and one value.

So if I have a v-data-table like this:

_<v-data-table (...props)>
  <template slot="items" slot-scope="props">
    <tr>
        <td>{{ props.item.professional.profile.full_name || '-' }}</td>
    </tr>
  </template>
</v-data-table>_

So my variable with the Header must contain a value that redirects to the object being placed in the (dynamic) table:
For example:
_{ text: 'Professional', value: 'professional.profile.full_name' }_

Only in this way we will be able to make the default sortable function of v-data-table work on the data-table column.

It's something simple, but it can cause some confusion. Hope I helped someone with this.

**Comment by thatygama** [comment]
Maybe what happened to me could happen to someone else researching this error. Every :headers="variable_here" will contain an array with at least an object and that object should contain at least one text and one value.

So if I have a v-data-table like this:

<v-data-table (...props)>
  <template slot="items" slot-scope="props">
    <tr>
        <td>{{ props.item.professional.profile.full_name || '-' }}</td>
    </tr>
  </template>
</v-data-table>

So my variable with the Header must contain a value that redirects to the object being placed in the (dynamic) table:
For example:
{ text: 'Professional', value: 'professional.profile.full_name' }

Only in this way we will be able to make the default sortable function of v-data-table work on the data-table column.

It's something simple, but it can cause some confusion. Hope I helped someone with this.

**Comment by thatygama** [comment]
Maybe what happened to me could happen to someone else researching this error. Every :headers="variable_here" will contain an array with at least an object and that object should contain at least one text and one value.

So if I have a v-data-table like this:

```
<v-data-table (...props)>
  <template slot="items" slot-scope="props">
    <tr>
        <td>{{ props.item.professional.profile.full_name || '-' }}</td>
    </tr>
  </template>
</v-data-table>
```

So my variable with the Header must contain a value that redirects to the object being placed in the (dynamic) table:
For example:
`{ text: 'Professional', value: 'professional.profile.full_name' }`

Only in this way we will be able to make the default sortable function of v-data-table work on the data-table column.

It's something simple, but it can cause some confusion. Hope I helped someone with this.
