### ISSUE TITLE
[Bug Report] Non utf-8 character in data-iterable

### ISSUE THREAD

**Issue by peshos** [vuetifyjs/vuetify#7153]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
When I have an empty data-table control, the paging character is displayed as "���". This can only be reproduced on a local site. The code in data-iterable.js is as:

```
genPagination () {
      let pagination = '–'

      if (this.itemsLength) {
        const stop = this.itemsLength < this.pageStop || this.pageStop < 0
          ? this.itemsLength
          : this.pageStop

        pagination = this.$scopedSlots.pageText
          ? this.$scopedSlots.pageText({
            pageStart: this.pageStart + 1,
            pageStop: stop,
            itemsLength: this.itemsLength
          })
          : this.$vuetify.t('$vuetify.dataIterator.pageText',
            ...([this.pageStart + 1, stop, this.itemsLength].map(n => Number(n).toLocaleString(this.$vuetify.lang.current))))
      }

      return this.$createElement('div', {
        'class': this.actionsPaginationClasses
      }, [pagination])
    }
```

If you switch the encoding of the file to utf-8 though, this part:

let pagination = '–'

id displayed as:

let pagination = ''

### Expected Behavior
To see the "-" character in utf-8 OR be able to configure this text.

### Actual Behavior
Funny characters.

### Reproduction Link
<a href="https://codepen.io/pepebg/pen/rgOBEa" target="_blank">https://codepen.io/pepebg/pen/rgOBEa</a>

### Other comments
The bug would be to change the "-" character to utf-8. The feature would be to be able to set the value of the text when the data table has no items.

**Comment by KaelWD** [comment]
That's an en dash, which very much is a unicode character. Sounds like you're using an encoding other than UTF-8.

**Comment by peshos** [comment]
Download the file from the repo, open it with a SciTE text editor and actually try it. Or should I submit a feature request to be able to change this?

**Comment by KaelWD** [comment]
SciTE opens files as ANSI by default.

**Comment by peshos** [comment]
And does it look like an en dash in ANSI for you?

**Comment by peshos** [comment]
Created a feature request to be able to change this - [https://github.com/vuetifyjs/vuetify/issues/7154](https://github.com/vuetifyjs/vuetify/issues/7154)

**Comment by peshos** [comment]
@KaelWD Follow up and might help someone else - turned out to be a build server issue with one of the tasks. Changed the task to force utf-8 encoding and this solved it.
Still think the file mentioned above has wrong encoding though and the feature request is for the team to consider.
