### ISSUE TITLE
[Feature Request] Ability to change the pagination text for empty data tables

### ISSUE THREAD

**Issue by peshos** [vuetifyjs/vuetify#7154]
### Problem to solve
When a data table has no items, the user is presented with a "-" for the pagination items. There is no possibility to change this at the moment.

### Proposed solution
Instead of hard-coding the value to "-", use a localized resource that can be changed with a property.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
