### ISSUE TITLE
[Bug Report] Cannot read property 'map' of undefined' When using V-calendar  when using type "Day"

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#7155]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.5.18
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Set the type to "Day"
Set Weekdays to "Mon-Fri"
Click on "Next" button till Friday
Observe console after Friday for Saturday and Sunday it shows error in console.

### Expected Behavior
If Weekdays are choosen from "Mon-Fri" for tupe "Day" after Friday it should go to Monday in one click without error.

### Actual Behavior
It shows following error in console

"[Vue warn]: Error in render: 'TypeError: Cannot read property 'map' of undefined'
found in
<VCalendarDaily>
       <VCalendar>
         <VSheet>
           <VApp>
             <Root>"

### Reproduction Link
<a href="https://codepen.io/vaishali-ghayal-the-lessful/pen/qGOaQv?editors=1111" target="_blank">https://codepen.io/vaishali-ghayal-the-lessful/pen/qGOaQv?editors=1111</a>

**Comment by nekosaur** [comment]
So this is actually a user error. When setting weekdays to mon-fri and calendar to daily, we are trying to display a saturday (2019-01-12) which is outside the range of days to show. I have opted to throw an error which should be easier to interpret than the current one.

**Comment by vaishali-ghayal** [comment]
@nekosaur Thanks for your response on this. I guess it's not a user error , when day view is selected and days are set to mon-fri and user click on next button og calendar and if it's Saturday or Sunday it should not through error I guess it should go to Monday directly.
