### ISSUE TITLE
[Bug Report] Unable to use v-select inside of a v-menu

### ISSUE THREAD

**Issue by deen13** [vuetifyjs/vuetify#7159]
### Versions and Environment
**Vuetify**: 1.5.13
**Vue**: 2.6.8
**Browsers**: Chrome 74.0.3729.131
**OS**: Mac OS 10.14.0

#### Steps to reproduce
Place a v-select inside of a v-menu.

#### Expected Behavior
Display the options on click

#### Actual Behavior
The menu disappears and instantly shows up again which closes the select

#### Reproduction Link
https://codepen.io/deenerin0/pen/eapypW

#### Other comments
I think this happens because the v-select internally also uses a v-menu and the input events of both conflicting with each other.

**Comment by blalan05** [comment]
First, your reproduction wasn't complete. (Missing v-app and v-content, these are musts), Secondly, the menu was set to open on hover. I think there is an issue about that not working already. Thirdly, it will work if you add prop `:close-on-content-click="false"`. https://codepen.io/anon/pen/byVvKJ

**Comment by blalan05** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
