### ISSUE TITLE
How can I user mask in text-fields

### ISSUE THREAD

**Issue by brfreitas** [vuetifyjs/vuetify#716]
How can I usar some mask directive on text-field?

I was trying use https://github.com/moip/awesome-mask
`<v-text-field
              name="input-2"
              label="Label Text"
              value="Input text"
              class="input-group--focused"
              v-mask="'999.999.999-99'"
            ></v-text-field>`
but it's not working.

**Comment by nekosaur** [comment]
Please direct any questions to our [Gitter](https://gitter.im/vuetifyjs) channel instead. 

The MD spec includes formatted inputs, but it has not yet been implemented. We can't offer any direct support of other 3rd party libraries but there might be people in Gitter that have had the same problem as you.

**Comment by mariante** [comment]
Good morning,
 I entered on Gitter, ask for help and nothing.. No way to set mask on text field?
