### ISSUE TITLE
[Bug Report] Unable to use v-select inside of a v-menu

### ISSUE THREAD

**Issue by deen13** [vuetifyjs/vuetify#7160]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.8
**Browsers:** Google Chrome
**OS:** Mac OS 10.14

### Steps to reproduce
Place a v-select inside of a v-menu.

### Expected Behavior
Display the options on click

### Actual Behavior
The menu disappears and instantly shows up again which closes the select

### Reproduction Link
<a href="https://codepen.io/deenerin0/pen/eapypW" target="_blank">https://codepen.io/deenerin0/pen/eapypW</a>

### Other comments
I think this happens because the v-select internally also uses a v-menu and the input events of both conflicting with each other.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/7159#issuecomment-490561143

#6963

#1877
