### ISSUE TITLE
[Feature Request] Edit "of" in data table pagination controls.

### ISSUE THREAD

**Issue by leocabrallce** [vuetifyjs/vuetify#7164]
### Problem to solve
This enhancement is based on the [Issue #593](https://github.com/vuetifyjs/vuetify/issues/593)
You can not change this value yet. At least there is nothing in the documentation.

### Proposed solution
Such as "no-data-text", "no-results-text" and others, create a property to set the value of the field or, if it's already been solved, update the documentation

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/components/data-tables#slot-pagetext
