### ISSUE TITLE
[Feature Request] add "disable-scale", "disable-contextmenu", "disable-select", "disable-touch" to v-app

### ISSUE THREAD

**Issue by wongwanchap** [vuetifyjs/vuetify#7165]
### Problem to solve
For most web application, developers (including me) always want to disable pinch scale or contextmenu. It would be handy if vuetify support such function by just adding the directive to the v-app component.

### Proposed solution
Proposed directives for v-app:
1. "disable-scale": disable pinch scale
2. "disable-contextmenu": disable able right-click show context menu. This can be done by add event listener to contextmenu event and then preventDefault()
3. "disable-select": disable user from selecting any text in app. This can be done by adding css "user-select: none"
4. "disable-touch": disable all touch event including pinch to scale. This can be done by adding css "touch-action: none"

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
