### ISSUE TITLE
<v-tabs> centered prop seems broken

### ISSUE THREAD

**Issue by mathieucivel** [vuetifyjs/vuetify#717]
Using https://codepen.io/mix3d/pen/LyKvmp, you can try to add the `centered` property. 
The `tabs--centered` class is added but no css rule seems to use it.

**Comment by johnleider** [comment]
Even though this is a valid bug that I can easily reproduce, I feel compelled to post this:

When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
