### ISSUE TITLE
[Bug Report] Prop `disabled` for v-list-item does not work (v2.0.0-alpha.19)

### ISSUE THREAD

**Issue by DmytroDiachuk** [vuetifyjs/vuetify#7170]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.19
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.119
**OS:** Linux x86_64

### Steps to reproduce
Open  link. Components (v-list-item)  have prop  `disabled`  but  they are not disabled.  

### Expected Behavior
I think, when v-list-item has disabled, it must change class and turn off element. (I assume, it must work like v-list-tile in vuetify@1.5.9) 

### Actual Behavior
When set prop disabled to v-list-item  nothing happens

### Reproduction Link
<a href="https://codepen.io/dmytro-diachuk/pen/eaJMBq" target="_blank">https://codepen.io/dmytro-diachuk/pen/eaJMBq</a>

**Comment by ibrahimBeladi** [comment]
**Should I use alpha in production?**
No.

**Should I report bugs that I find in the alpha?**
No. We will open up bug reporting once we move to beta.

**What should I do now?**
Just close this issue. If this bug persists after the beta release, then resubmit it.
