### ISSUE TITLE
[Feature Request] v-select support item-key

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#7171]
### Problem to solve
For v-select, if `items` have duplicate values for a property declared in `item-text`, ie "name", then the duplicates are not shown in the list. It appears to silently hide duplicates which is confusing - and in some cases we may purposefully wish to show duplicate information.

### Proposed solution
This is solved on the data table by specifying an `item-key="x"` , ie `item-key="id"`
ie continuing above example then `[{"id": 0, "name": "hello"}, {"id": 1, "name": "hello"}]` would show as two items "hello", but with return-object it would return useful information based on the overall object.

OR update docs to declare how duplicates are handled more clearly
and create some option to simply disable that filter and show duplicates.

**Comment by ibrahimBeladi** [comment]
I have seen a similar issue before (#6967).
[It is doable, see the codepen.](https://codepen.io/ibrahimbeladi/pen/yrbpZa?editors=1010)

**Comment by swirlingsand** [comment]
Thanks! Ok so it seems like `item-value="id"` is what's causing it to work.
I see it working on the code pen but at least 1.5.1 locally the item-value doesn't appear to be working as expected. I'm pulling from a veux store for items, not sure if that's part of issue or something else.

Either way, Item value is confusing here. This should be `item-key`.
If I declare the value to to be the id, I would expect that's what gets returned, but then return-object overrules that which doesn't make sense. Where as `item-key` does make sense.

**Comment by KaelWD** [comment]
Datatable is completely separate, `item-key` just sets `:key` for the rows and it always returns the full item objects.
