### ISSUE TITLE
[Feature Request] How to toggle the expansion panel of data table rows from code?

### ISSUE THREAD

**Issue by gwh-cpnet** [vuetifyjs/vuetify#7172]
### Problem to solve
How to toggle expansion 'manually', or from code ? Not from the  embedded button. 

How to bind data table `props.expanded` to $data? I have a button to fetch some data and when the data is fetched, I would like to open the expansion slot `automatically` then.

### Proposed solution
make something like `expanded.sync` props.  or bind `expanded` to some member in `props.item`.

**Comment by KaelWD** [comment]
This has already been implemented in v2
