### ISSUE TITLE
Height for a <v-expansion-panel> elment not set to auto intially

### ISSUE THREAD

**Issue by clydefrog10002** [vuetifyjs/vuetify#718]
### Steps to reproduce
A simple v-expansion-panel with two v-expansion-panel-content elements. In case the first v-expansion-panel-content element is extended intially already and the height increases when shrinking the width of the browser window, it overlaps the second v-expansion-panel-content below.

### Versions
Tested with MacOS and Windows with latest version of Google Chrome.
"vue": "^2.2.1"
"vuetify": "^0.12.0"

### What is expected ?
The height should adapt automatically.

### What is actually happening ?
The first  v-expansion-panel-content elements overlaps the second one.

### Reproduction Link
https://codepen.io/king10002/pen/jmdRZP?editors=1010

**Comment by clydefrog10002** [comment]
I think the bug is not fully fixed yet. I changed the above mentioned codepen slightly by wrapping each of the two v-expansion-panel-contents in it's own <v-card> tag. The problem is still present.

**Comment by johnleider** [comment]
The fix has not released yet.
