### ISSUE TITLE
[Bug Report] v-data-table inherited attrs doesnt work select-row

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#7180]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Linux x86_64

### Steps to reproduce
Click to select row

### Expected Behavior
Should be selected

### Actual Behavior
When click on select all it should select all nested checkboxed but it doesnt do this.

### Reproduction Link
<a href="https://codesandbox.io/s/r41qv8jjmn" target="_blank">https://codesandbox.io/s/r41qv8jjmn</a>

### Other comments
To avoid duplicate I try to wrap v-data-table and define some functionality but it doesn't work as expected. I tried different options but without success

**Comment by nekosaur** [comment]
Solved by https://github.com/vuetifyjs/vuetify/pull/7240

**Comment by websitevirtuoso** [comment]
Great Thanks

**Comment by websitevirtuoso** [comment]
> Solved by #7240

Could you tell me how can I start using next branch to avoid waiting release?

**Comment by jacekkarczmarczyk** [comment]
Install vuetify@2.0.0-alpha.20 and follow the [releases notes](https://github.com/vuetifyjs/vuetify/releases) to find find out breaking changes

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by nekosaur** [comment]
That being said, you'll have to wait until the next alpha release
