### ISSUE TITLE
[Bug Report] Vuetify's prerendered output is not mobile friendly

### ISSUE THREAD

**Issue by nirmalraghavan** [vuetifyjs/vuetify#7184]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Linux x86_64

### Steps to reproduce
I have hosted the above code here,
https://determined-yalow-287958.netlify.com/

1. If you visit this site from desktop, it will have red background and if you visit from mobile device, background color will be green.

2. Now visit Google's mobile friendly testing tool and give the above URL. You can see the rendered screenshot color will be red.

### Expected Behavior
I have hosted the above site in netlify and enabled "prerendering". I have found that netlify is prerendering the site always with the resolution of 1440x718 and returns the response back to crawler. If the crawler is Google smartphone it will report the site is not mobile friendly. The above example site is a simple one and Google says it is mobile friendly. In my real program I have different layouts and width for desktop and mobile screens. It is always reporting "Content is wider than screen" for all my pages.

### Actual Behavior
In multiple places I have used `v-if="$vuetify.breakpoint.smAndDown`, this fails always because netlify prerendering with desktop screen size. But why it is not working when it is returned back to Google mobile bot?

### Reproduction Link
<a href="https://codepen.io/nirmalraghavan/pen/EzyoxV" target="_blank">https://codepen.io/nirmalraghavan/pen/EzyoxV</a>

### Other comments
I think once vue/vuetify site is prerendered it won't be responsive anymore. Please correct me if my understanding about javascript framework is wrong.

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/57578577-56d0f600-74d2-11e9-88cd-adba0b1ae613.png)

**Comment by nirmalraghavan** [comment]
@KaelWD I think you tested with a different tool. Netlify will prerender only for known bots. You must test the URL using [Google's mobile friendly testing tool](https://search.google.com/test/mobile-friendly?id=dYmxbo5SsM-dNOU8XlPvlg). Issue is only with prerendered result.

![vuetify_issue](https://user-images.githubusercontent.com/24563146/57579970-b4a91200-74c1-11e9-93d3-230c72cdb163.png)

**Comment by KaelWD** [comment]
Don't use that then? Googlebot runs chrome 74 now. Otherwise use actual SSR instead.
