### ISSUE TITLE
[Feature Request] Autocomplete scroll to top after new list

### ISSUE THREAD

**Issue by giray123** [vuetifyjs/vuetify#7188]
### Problem to solve
Much better user experience for autocomplete component

### Proposed solution
It would be much better if the component scrolls to top after new array is set. Currently scroll position stays the same.

**Comment by LucSalommez** [comment]
Hello, I am currently having the same issue.

I have an autocomplete component with a list of items that can be filtered.
When items are filtered the scroll keeps the same offset while I'd like to force it to be reset.

Is there a way to do it ?
I couldn't find props nor slots in the documentation that could fit this usecase.

Has this issue been solve or is there a workaround I could use ?

Thank you,
Luc

**Comment by Himanshu07Gurung** [comment]
Facing same issue.
