### ISSUE TITLE
Recursive dialogs

### ISSUE THREAD

**Issue by fortil** [vuetifyjs/vuetify#719]
Hi guys

I wanna build a list with editable controls, this list in a (close button) icon open a dialog, but when I click in each element its open the same value, because it opens all the v-dialogs.

The proyect reproduction 
https://jsfiddle.net/nqf7omvz/2/

thanks.

**Comment by fortil** [comment]
If I change the model for one property of the items, it works showing one only v-dialog but not close with the buttons.

https://jsfiddle.net/nqf7omvz/3/

**Comment by johnleider** [comment]
Your application was missing ```v-app``` at the root, https://jsfiddle.net/z59nu3k0/

**Comment by fortil** [comment]
Hi

But you not resolve my problem, if you see the text continue shown the same value for each click in close, because it opens all v-dialogs. The problem wasn't the style. 

Look, each v-dialog should to show different values, but all show the same, it is because by each click in "close" it opens all, then only can to see one.
`<v-card-text class="text-xs-left w-row">Some text {{props.item.id}}</v-card-text>`

Thanks

**Comment by johnleider** [comment]
The issue board is for bugs.

If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
