### ISSUE TITLE
[Bug Report] VTextField parses value of input type number as string

### ISSUE THREAD

**Issue by slushnys** [vuetifyjs/vuetify#7192]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. Create a component of v-text-field with type of number.
2. Type numbers
3. Returns text as value

### Expected Behavior
Type numbers in input field should return number type of value.

### Actual Behavior
Returns text type of value. Vue displays error when used that value passing to other components expecting prop with number type

### Reproduction Link
<a href="https://codepen.io/anon/pen/GajoRM" target="_blank">https://codepen.io/anon/pen/GajoRM</a>

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/forms.html#number
