### ISSUE TITLE
[Bug Report] Date Picker Component Range is Artificially Limited to +- 100 years

### ISSUE THREAD

**Issue by spina-a-d** [vuetifyjs/vuetify#7193]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Ubuntu undefined

### Steps to reproduce
* Click on the year selector
* Try and scroll past 100 years in any direction.  

### Expected Behavior
* Click on the year selector
* Scroll infinitely for year

### Actual Behavior
* Click on year selector
* Try and scroll
* Blocked at +- 100 years
* In order to continue you must select a date and the new range will be set

### Reproduction Link
<a href="https://codepen.io/spinaadbusiness/pen/joMMNe" target="_blank">https://codepen.io/spinaadbusiness/pen/joMMNe</a>

### Other comments
*  This makes any user experience involving historical dates awful.  If you want to click something around -2000 years you have to select a date 20 times.

**Comment by ewrayjohnson** [comment]
What is the status of this?
