### ISSUE TITLE
[Feature Request] VDialog does not have animation events

### ISSUE THREAD

**Issue by SanBen** [vuetifyjs/vuetify#7195]
### Problem to solve
React to animation end and start of dialogs

### Proposed solution
Implement v-on:after-enter and v-on:before-enter for vDialog as are available for other components:
https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

https://github.com/vuetifyjs/vuetify/issues/3454#issuecomment-415984337

**Comment by KaelWD** [comment]
Duplicate of #6504
