### ISSUE TITLE
[Bug Report] v-carousel breaks when used with keep-alive

### ISSUE THREAD

**Issue by CapitaineToinon** [vuetifyjs/vuetify#7196]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Linux x86_64

### Steps to reproduce
* Create a component that uses a v-carousel
* Set cycle on the carousel to true
* Name the component and use it in a route
* Use a keep-alive around the router-view and include your component
* Go to the route where you carousel is so it loads and gets cached by keep-alive
* Go to a different route and wait until the carousel cycles through its items
* Come back and the carousel will be broken

### Expected Behavior
The carousel's items should always be visible

### Actual Behavior
The carousel's items disappears after it cycled while not being rendered.

### Reproduction Link
<a href="https://jsfiddle.net/CapitaineToinon/0qohbfjy/34/" target="_blank">https://jsfiddle.net/CapitaineToinon/0qohbfjy/34/</a>

### Other comments
Note that the carousel's state is properly cached. For example, if you have 5 items in your carousel and it cycles through them automatically, that won't be reset when route changes. It's just that the content of the carousel items isn't rendered anymore.

**Comment by CapitaineToinon** [comment]
This seems to be caused by the carousel cycling through the items while it's not being rendered. Disabling the cycle fixes the issue 

```xml
<v-carousel :cycle="false" hide-delimiters height="200px">
  <v-carousel-item v-for="(item,i) in items" :key="i" :src="item.src"></v-carousel-item>
</v-carousel>`
```

And if you still want the items to cycle, you can bind the carousel item to a variable to enable and disable on activated / deactivated, the hooks called when a component is cached : https://vuejs.org/v2/api/#activated

```javascript
var Foo = Vue.extend({
  name: "carousel-page",
  template: `
    <v-carousel
      :cycle="cycle"
      hide-delimiters
      height="200px"
    >
      <v-carousel-item
        v-for="(item,i) in items"
        :key="i"
        :src="item.src"
      ></v-carousel-item>
    </v-carousel>`,
  data() {
    return {
      cycle: false,
      items: [
        {
          src: 'https://cdn.vuetifyjs.com/images/carousel/squirrel.jpg'
        },
        {
          src: 'https://cdn.vuetifyjs.com/images/carousel/sky.jpg'
        },
        {
          src: 'https://cdn.vuetifyjs.com/images/carousel/bird.jpg'
        },
        {
          src: 'https://cdn.vuetifyjs.com/images/carousel/planet.jpg'
        }
      ]
    }
  },

  activated() {
    this.cycle = true;
  },

  deactivated() {
    this.cycle = false;
  }
})
```

**Comment by JoDring** [comment]
try add height style to 'v-carousel-item' component,  like :  <v-carousel-item style="height: 200px">,  still not solve this problem completely but better then before;

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
