### ISSUE TITLE
[Bug Report] Autocomplete on data-table set initial value after async research

### ISSUE THREAD

**Issue by alessandrome-sinerbit** [vuetifyjs/vuetify#7197]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. Select a row of the table to open the edit dialog
2. Select which person you want and then save
3. Reopen the edit dialog and try to delete some characters to make call the research method

### Expected Behavior
When i type or delete on the autocomplete i expect that the component simply show me the filtered items

### Actual Behavior
When i type something or delete, after the filtered item list has been updated, autocomplete reselect the last option, rewriting it on the text box and making my typing useless 

### Reproduction Link
<a href="https://codepen.io/anon/pen/KLgmQg" target="_blank">https://codepen.io/anon/pen/KLgmQg</a>

### Other comments
I'm not very sure if this is a vuetify autocomplete component problem, but i found this behavior very strange. The codepen code is not totally equal to my code, but the autocomplete behavior is the same when you try typing something

**Comment by KaelWD** [comment]
Use `no-filter` with external filtering
