### ISSUE TITLE
Where is your main.styl in the webpack template

### ISSUE THREAD

**Issue by kayyyy** [vuetifyjs/vuetify#72]
Great Work, awesome! 👍

In your Documentation you say:
> To disable this, navigate to src/stylus/main.styl and assign $color-pack to false.

But in your [Webpack Template](https://github.com/vuetifyjs/webpack/tree/master/template/src) there is no main.styl.

I tried to import the `main.styl` from the node_modules Folder and then change the Variable. But with no Effect. 
### App.vue
```
...
<style lang="stylus">
@import '../node_modules/vuetify/src/stylus/main'
$body-bg := #ECEFF1
$body-font-family := 'Arial', san-serif
</style>
```
Could you give me a Tip how to change the Vars from the `main.styl`?

**Comment by johnleider** [comment]
That is an error, there should be. As far as your example, you should be able to put $color-pack = false above the import.
