### ISSUE TITLE
[Bug Report] When i add v-app tag, the page displays a blank space

### ISSUE THREAD

**Issue by MatheusCO22** [vuetifyjs/vuetify#7200]
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
Just open the page. That blank space between the content and the header should not be there

### Expected Behavior
The content was supposed to be right below the header

### Actual Behavior
Blank space between the header and the rest of the page content.

### Reproduction Link
<a href="https://codesandbox.io/embed/lrpxrl4r7" target="_blank">https://codesandbox.io/embed/lrpxrl4r7</a>

**Comment by ibrahimBeladi** [comment]
It is recommended to use 'v-app' in the application level (App.vue), while the rest of the component should not have it.
[For further information, check out the docs.](https://vuetifyjs.com/en/framework/default-markup)

**Comment by KaelWD** [comment]
:point_up: 

Replace `<div id="app">` with `<v-app>` and remove it everywhere else.

**Comment by MatheusCO22** [comment]
Ok, thanks!
