### ISSUE TITLE
[Feature Request] Do not automatically pop up the input method window when clicking the Combobox

### ISSUE THREAD

**Issue by xmwgp8** [vuetifyjs/vuetify#7203]
### Problem to solve
On the mobile side, can it be forbidden to automatically pop up the input method window when clicking the Combobox?

### Proposed solution
Is it possible to add an attribute: whether to close the input method window ？

**Comment by KaelWD** [comment]
>input method window

keyboard?

And no, it's supposed to be similar to a text field. If you don't want people to type in it use `v-select` instead.
