### ISSUE TITLE
[Bug Report] The input element's type ('time') does not support selection

### ISSUE THREAD

**Issue by suriyadi15** [vuetifyjs/vuetify#7205]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
after set value, the browser console show error
'vuetify.min.js:6 Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('time') does not support selection.'

### Expected Behavior
not show error

### Actual Behavior
show error in console

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZNBKwK?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/ZNBKwK?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Not all options are compatible with each other.
