### ISSUE TITLE
[Feature Request] Pass other arguments to the custom filter function of v-autocomplete

### ISSUE THREAD

**Issue by albertostiip** [vuetifyjs/vuetify#7208]
### Problem to solve
I need to search on multiple keys and not just the itemText.

### Proposed solution
In addition to the present arguments, it should be possible to pass an additional argument containing, for example, an array of keys on which to perform the text search.

**Comment by KaelWD** [comment]
The first argument contains the entire item object.

**Comment by albertostiip** [comment]
> The first argument contains the entire item object.

Yes, I know that.
But I need to be able to dynamically pass the keys to search in this object.

_ex. item object_

```
{
    id: 96
    subtitle: "simple"
    text: "Product"
}
```

For example here I would like to be able to pass an array with the keys ['text', 'subtitle'] to the filter function and filter these keys.

**Comment by KaelWD** [comment]
Where are they supposed to come from? What's the use case?

**Comment by jacekkarczmarczyk** [comment]
`:custom-filter="createFilter(['text' ,'subtitle'])"`?

**Comment by albertostiip** [comment]
I have a component called FieldsGenerator.vue that receives the skeleton of the form from a back-end API and dynamically creates it.

ex. skeleton (that comes from the back end) of v-autocomplete for select a product


```
{
    class: 'xs12 sm6 md6'
    type: "autocomplete"
    item_text: "text"
    item_value: "id"
    key: "product_id"
    label: "Prodotto"
    name: "product"
    options: [{id: 32505, text: "1005", subtitle: "variant"}, {id: 96, text: "1222", subtitle: "variant"},…]
    relation: "product"
    relation_field: "name"
    relation_model: "Product"
    required: true
    validations: "required"
    **// search keys**
    **searchKeys: ['text', 'subtitle']**
}
```

FieldsGenerator.vue

```

<v-flex v-for="(field, i) in fieldsset" :key="i" :class="field.class ? field.class : 'lg6 md6 xs12 px-4'">
    ....
    	<template v-if="field.type === 'text-field' ">
             ...
        </template>

    	<template v-else-if="field.type === 'autocomplete' ">
             <v-autocomplete
                  	:label="field.label"
			:items="field.options"
			:hint="field.hint"
			v-model="model[field.key]"
			:item-text="field.item_text"
			:item-value="field.item_value"
                        :filter="customFilter(item, queryText, itemText, **field.searchKeys**)"
             </v-autocomplete>
        </template>
    ....
</v-flex>
```

This is my use case.

**Comment by KaelWD** [comment]
You can do that already by having customFilter return another function

**Comment by albertostiip** [comment]
I'm trying but it's not working. Does not enter the custom function.

`:filter="customFilter"
`

```
methods: {
    customFilter(item, queryText, itemText) {
        return (item, queryText, itemText) => {
            console.log(item, queryText, itemText)
	}
    },
}
```

**Comment by albertostiip** [comment]
I solved that. Thank you all!! 

`:filter="(item, queryText, itemText) => customFilter(item, queryText, itemText, field.searchKeys)"
`
