### ISSUE TITLE
Vue warn on v-btn-dropdown when clicked

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#721]
### Steps to reproduce
1. Add `v-btn-dropdown`

### Versions
**Vuetify** - `^0.12.7`
**Browser** - `Version 58.0.3029.110 (64-bit)`
**OS** - Linux Mint Serena

### What is expected ?
There should be no Warn in the debug console.

### What is actually happening ?
There is this error `Invalid prop: type check failed for prop "closeOnClick". Expected Boolean, got FocusEvent.`

### Reproduction Link
https://jsfiddle.net/greenfoxx/mhxwcpc3/

**Comment by johnleider** [comment]
btn-dropdown is being removed in favor of select which contains the exact same functionality. The additional btn-dropdown styles have been moved over.

**Comment by jofftiquez** [comment]
@johnleider has this been released? Thanks.

**Comment by johnleider** [comment]
No
