### ISSUE TITLE
[Bug Report] Button Group Hangs

### ISSUE THREAD

**Issue by jrmore** [vuetifyjs/vuetify#7214]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Linux x86_64

### Steps to reproduce
Started with the codepen from https://vuetifyjs.com/en/components/button-groups#button-groups (the last example of the page)
Altered the button group for the text enhancements to use the dropdown_edit data as follows:
`
      <v-btn-toggle
        v-for="(item, x) in dropdown_edit" :key="x"
        v-model="toggle_multiple"
        class="transparent"
    >
        <v-btn :value="x" flat>
          {{item.text}}
        </v-btn>
      </v-btn-toggle>
`

### Expected Behavior
This executes as expected...... Until I add the  **mandatory**  prop to v-btn-toggle

### Actual Behavior
After adding **mandatory** the code seems to go into an infinite loop until stopped by the codepen framework or I kill the chrome thread.

### Reproduction Link
<a href="https://codepen.io/jrmore/pen/RmKovq?editors=1011" target="_blank">https://codepen.io/jrmore/pen/RmKovq?editors=1011</a>

### Other comments
I am by no stretch of imagination an experienced developer and I have exhausted my capabilities to dive deeper into this issue. I am very willing to do whatever I need to help if this really is a bug and not just something silly I have done.

**Comment by nekosaur** [comment]
You have placed the `v-for` on the wrong element. It should be on the `v-btn`, not the `v-btn-toggle`.
