### ISSUE TITLE
[Bug Report] Dynamically adding tab transition is not working properly.

### ISSUE THREAD

**Issue by santhikumar43** [vuetifyjs/vuetify#7216]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
Adding a new tab dynamically on clicking of the button.

### Expected Behavior
The transition is some how overlapping on the card.

### Actual Behavior
The transition should not flicker on the card.

### Reproduction Link
<a href="https://codepen.io/anon/pen/NmvaWZ?editors=1010" target="_blank">https://codepen.io/anon/pen/NmvaWZ?editors=1010</a>

### Other comments
In the above example click on the Add button, it will add the tab and what ever is newly added is active.
This used to work in these versions:
Vue: 2.5.18
Vuetify: 1.5.5
Then i updated the version of the vue@2.6.10 and this is the problem. I later updated the Vuetify@1.5.14 but didn't solve the issue.

**Comment by santhikumar43** [comment]
I already created an issue https://github.com/vuetifyjs/vuetify/issues/6979 , by adding $nextTick it worked but now it is not working. I am creating same issue because to not to comment on the closed issue. Please check the codepen once again. Thank you.

**Comment by KaelWD** [comment]
#7102 seems to think it's caused by chrome 74
also #7088
