### ISSUE TITLE
[Bug Report] v-overflow-btn does not work well inside a toolbar

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#7221]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

### Steps to reproduce
Add v-overflow-btn inside toolbar.

### Expected Behavior
It should be vertically centrally aligned (see "refresh" button for comparison in reproduction). It should have background color matching the background of the toolbar. Also, it has a blue progress bar on click on the bottom, while regular button does not have. It is also very wide and does not adapt to content inside it (even "very long entry" is still much shorter than the button).

### Actual Behavior
The opposite of the above.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pmeabG" target="_blank">https://codepen.io/anon/pen/pmeabG</a>

**Comment by anuger** [comment]
I also have this problem.
