### ISSUE TITLE
[Feature Request] Tab gets swiped when tab's content is scrollable

### ISSUE THREAD

**Issue by subashdbc** [vuetifyjs/vuetify#7222]
### Problem to solve
When we have multiple tabs and on the page, where each tab contains scrollable v-datatable/content when we scroll the table content, the tabs are also getting swiped on touch devices.

### Proposed solution
It would be good to prevent tab's scroll action when the tab item has got scrollable content in it on a touch device.

**Comment by KaelWD** [comment]
Duplicate of #2335
