### ISSUE TITLE
[Feature Request] Use Tooltip as the property on the button component

### ISSUE THREAD

**Issue by donnisnoni95** [vuetifyjs/vuetify#7223]
## Tooltips 
Tooltips help users understand unknown or unfamiliar objects that aren’t described directly in the user interface. They are a powerful way to simplify a UI — provide information users need when they need it, with minimal effort on their part, and help app developers use screen space more effectively (reduce screen clutter).

## The Problem
Of course Vuetify has provided the v-tooltip component, but in my opinion, the problem of using this v-tooltip component is rather difficult to see its structure. therefore I only suggest 'its nice if the tooltip can be used on the button just by putting it in the button's properties'

## Conclusion
Tooltip is very important in UX and tooltip is very often used for UX needs especially for button. I think if Vuetify can provide this, this can speed up and make it easier for developers to create applications that support high

### Proposed solution
FROM THIS :
 ```vue
<v-tooltip bottom>
	<template v-slot:activator="{ on }">
		<v-btn color="primary" dark v-on="on">Button</v-btn>
	</template>
	<span>Tooltip</span>
</v-tooltip>
   ```

TO THIS :
 ```vue
<v-btn tooltip="Close this dialog" tooltip-dir="top">Close</v-btn>
   ```

**Comment by KaelWD** [comment]
See the discussion in #2961

**Comment by donnisnoni95** [comment]
okay.. i'll do it for myself :)

**Comment by builder7777** [comment]
> See the discussion in #2961
> 
> You can use native tooltips with the built-in `title` attribute if you don't want anything fancy.

the "title" does not work everywhere
