### ISSUE TITLE
[Bug Report] Apply hover state on list elements with touch

### ISSUE THREAD

**Issue by ste-xx** [vuetifyjs/vuetify#7224]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Google Chrome, Safari
**OS:** Android, iOS

### Steps to reproduce
Open example in chrome
Switch to mobile view
Click on List element

### Expected Behavior
Hover state should not be applied on list element

### Actual Behavior
Hover state is applied on list element

### Reproduction Link
<a href="https://codepen.io/ste-xx/pen/VOpBYX?&editable=true&editors=101" target="_blank">https://codepen.io/ste-xx/pen/VOpBYX?&editable=true&editors=101</a>

### Other comments
Seems like a similar issue, which was fixed for buttons: https://github.com/vuetifyjs/vuetify/issues/6497

Current hotfix in our codebase:
``` 
.v-list__tile--link:hover
  @media (hover: none)
    background: transparent
```

**Comment by johnleider** [comment]
After re-evaluating this, I'm convinced this is working as intended.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
