### ISSUE TITLE
[Bug Report] Missing Typescript declarations

### ISSUE THREAD

**Issue by jlvos** [vuetifyjs/vuetify#7225]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
npm install vuetify@2.0.0-alpha.20

### Expected Behavior
No compiler warnings about missing definitions

### Actual Behavior
Typescript compiler complains about missing definitions

### Reproduction Link
<a href="https://github.com/vuetifyjs/vuetify/blob/v2.0.0-alpha.20/packages/vuetify/.npmignore" target="_blank">https://github.com/vuetifyjs/vuetify/blob/v2.0.0-alpha.20/packages/vuetify/.npmignore</a>

### Other comments
Cause is .npmignore excludes the types/presets and types/services folders so these are not included with the npm package

**Comment by DRoet** [comment]
We are aware of the issue and this will get fixed in a future `2.0` release

**Comment by buksy90** [comment]
this has been fixed in  #7229
