### ISSUE TITLE
[Bug Report] Prop color on v-list-tile not working

### ISSUE THREAD

**Issue by LostPlayer99** [vuetifyjs/vuetify#7226]
### Versions and Environment
**Vuetify:** 1.5.14
**Last working version:** 1.5.13
**Vue:** 2.6.8
**Browsers:** Chrome 74.0.3729.131
**OS:** Linux x86_64

### Steps to reproduce
Add the color prop to v-list-tile

### Expected Behavior
Change of the text color

### Actual Behavior
No change

### Reproduction Link
<a href="https://codepen.io/anon/pen/rgyPVg" target="_blank">https://codepen.io/anon/pen/rgyPVg</a>

**Comment by Sagarmak** [comment]
Its an small but important feature. Please Help Team Vuetify!

**Comment by rounce** [comment]
This is still a issue on 2.0 beta.4.
https://codepen.io/rounce/pen/bPaJzp

**Comment by johnleider** [comment]
The color prop was intended to change the color of the text when a `v-list-tile` was active: https://codepen.io/johnjleider/pen/xoWLjL , or more notably while in some sort of activator such as `v-list-group`

@rounce the same applies to v2.0 only it uses **input-value** now that **value** is reserved for actual values in groups. https://codepen.io/johnjleider/pen/agYyKy .

As this is the intended nature of the component and a **background-color** prop was added for v2.0, there are no intentions to change this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by NathanStrutz** [comment]
I understand the reason for closing, but I believe the question illuminates a different problem. There doesn't seem to be a way, without manually intervening with custom CSS, to customize the active item text color or active item background color in a navigational setting.
