### ISSUE TITLE
[Bug Report] Can not close tooltip on Safari/iOS

### ISSUE THREAD

**Issue by bieleckim** [vuetifyjs/vuetify#7227]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Click on Hello button and try to close tooltip.

### Expected Behavior
Tooltip should be closed when i click anywhere (except tooltip content).

### Actual Behavior
Tooltip is visible all the time.

### Reproduction Link
<a href="https://github.com/bieleckim/vuetify-tooltip-ios" target="_blank">https://github.com/bieleckim/vuetify-tooltip-ios</a>

**Comment by johnleider** [comment]
For whatever reason clicking outside the element isn't firing blur on safari, not sure why.

**Comment by KaelWD** [comment]
Click-outside on iOS should have been fixed by f4f8c7a378ec969b9aea7ad544d4692c328140c0
