### ISSUE TITLE
[Bug Report] v-data-table index doesn't update with pagination

### ISSUE THREAD

**Issue by depperm** [vuetifyjs/vuetify#7230]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
Change the page (bottom right)

### Expected Behavior
Index to update as items change

### Actual Behavior
index remains the same from 0 to number of items per page

### Reproduction Link
<a href="https://codepen.io/anon/pen/pmPLeJ#anon-login" target="_blank">https://codepen.io/anon/pen/pmPLeJ#anon-login</a>

**Comment by nekosaur** [comment]
This is by design. The index provided in the scope is just the index for the current page. It is not meant to be used as a persistent index to identify individual items.
