### ISSUE TITLE
[Feature Request] Carousel Image Background Position

### ISSUE THREAD

**Issue by tfprado** [vuetifyjs/vuetify#7231]
### Problem to solve
I am trying to make a responsive slider/carousel. I can change the height of the v-carousel component using a computed prop and the veutify breakpoints (which works great!). My problem comes on mobile browsers (where even though the carousel re-sizes properly, the image background position being center center causes it to be cut off). I have tried using CSS classes, the active-class prop and vanilla JS to change the background-position on the created div, but no success.

```html
<div class="v-image__image v-image__image--cover" style="background-image: url(&quot;http://localhost/storage/app/media/some_pic.jpg&quot;); background-position: center center;"></div>
```

Being able to change the background position on the carousel images would make it easier to make them mobile friendly.

### Proposed solution
Adding a prop to v-carousel-item to change the default image background position when v-carousel gets rendered.

**Comment by KaelWD** [comment]
v-carousel-item extends v-img, which has a `position` prop. Your issue sounds like #6067 which has been fixed in 2.0.
