### ISSUE TITLE
[Bug Report] ValidationError: webpack Dev Server Invalid Options

### ISSUE THREAD

**Issue by pSnehanshu** [vuetifyjs/vuetify#7232]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.75
**OS:** Linux x86_64

### Steps to reproduce
Step #1. Install vue-cli and vuetify.
Step #2. Run `$ npm run serve`

### Expected Behavior
Should start webpack dev server.

### Actual Behavior
 ERROR  ValidationError: webpack Dev Server Invalid Options
               
options.clientLogLevel should be {String} and equal to one of the allowed values
               
 [ 'info', 'warn', 'error', 'debug', 'trace', 'silent' ]
               
 (https://webpack.js.org/configuration/dev-server/#devserverclientloglevel)
  

### Reproduction Link
<a href="https://codepen.io/Nothing_to_reporoduce" target="_blank">https://codepen.io/Nothing_to_reporoduce</a>

### Other comments
Modify `node_modules/@vue/cli-service/lib/commands/serve.js` line 139. Set `clientLogLevel` to anything from 'info', 'warn', 'error', 'debug', 'trace', 'silent', the error goes away.

**Comment by pSnehanshu** [comment]
The solution can be found here: https://github.com/vuejs/vue-cli/issues/4017#issuecomment-493481614

**Comment by jacekkarczmarczyk** [comment]
This is vue-cli issue, not Vuetify
