### ISSUE TITLE
[Feature Request] GET INTERVAL START AND END, WHEN THE USER CLICKS ON SPECIFIC TIME

### ISSUE THREAD

**Issue by bionner** [vuetifyjs/vuetify#7237]
### Problem to solve
Hi, Im wondering how can i get the start and end interval times, when i click on a specific time.
Example:

I clicked on 09:23 am.
My interval is from 09:00 am to 09:30 am, then i wanna take this data.
Greetings!!

### Proposed solution
I propose to add a function or property which indicates the interval ranges.

**Comment by nekosaur** [comment]
What component is this regarding? VCalendar? If so, how does the calendar know you are interested in a 30 minute window, instead of an hour, or anything else?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
