### ISSUE TITLE
Button dropdown instantly closes after opening

### ISSUE THREAD

**Issue by Splogy** [vuetifyjs/vuetify#724]
### Steps to reproduce
Click on the body of the body, not the arrow
### Versions

Vuetify 0.12.7
### What is expected ?

The dropdown should stay open, and allow selection of items
### What is actually happening ?

The dropdown opens then closes straight again
### Reproduction Link

https://codepen.io/anon/pen/RgWyJY
https://vuetifyjs.com/components/buttons

**Comment by johnleider** [comment]
Button dropdown is going away in favor of select with the added styles available. Since this bug is not present with select it is no longer an issue.
