### ISSUE TITLE
[Bug Report] Vertical sliders won't work on iOS

### ISSUE THREAD

**Issue by SystemKeeper** [vuetifyjs/vuetify#7241]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10 (depends on what is used on next.vuetify.com)
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
- Open https://next.vuetifyjs.com/en/components/sliders#vertical-sliders on iOS (12.3 in my case)
- Try to move the vertical slider up and down

### Expected Behavior
The slider should move up an down, but the page itself should not

### Actual Behavior
The page moves up and down, making it impossible to change the value of a vertical slider (see video)

[WIN_20190519_13_25_33_Pro_1.zip](https://github.com/vuetifyjs/vuetify/files/3195026/WIN_20190519_13_25_33_Pro_1.zip)

### Reproduction Link
<a href="https://codepen.io/anon/pen/JqyRem?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/JqyRem?&editable=true&editors=101</a>
https://next.vuetifyjs.com/en/components/sliders#vertical-sliders

### Other comments
Also #4356 would make things much easier to use on mobile

**Comment by SystemKeeper** [comment]
Hey, any chance this getting adressed in a 2.1 or 2.2 ?! Thanks!

**Comment by johnleider** [comment]
This affected more than just iOS.
