### ISSUE TITLE
[Bug Report] Search nested object in VDatatable

### ISSUE THREAD

**Issue by alexela8882** [vuetifyjs/vuetify#7243]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
Add nested data in `desserts` object

### Expected Behavior
Can search nested object data

### Actual Behavior
Can't search nested object data

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-08b5b" target="_blank">https://codesandbox.io/s/vue-template-08b5b</a>

**Comment by KaelWD** [comment]
You need to implement your own filter function if you want to do that.
