### ISSUE TITLE
[Bug Report] Tabs center not working correctly in RTL

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuetifyjs/vuetify#7245]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
Use tabs component and add a center prop in RTL mode

### Expected Behavior
Should work like LTR in center

### Actual Behavior
_

### Reproduction Link
<a href="https://codepen.io/miladmeidanshahi/pen/xNLBqZ?&editable=true&editors=101" target="_blank">https://codepen.io/miladmeidanshahi/pen/xNLBqZ?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/xNLNqM?&editable=true&editors=101

**Comment by sh7dm** [comment]
Fixed in 48f325d
