### ISSUE TITLE
[Bug Report] Dialog issue with form

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#7246]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
Press click me in reproduction link.

### Expected Behavior
Smooth opening of dialog.

### Actual Behavior
Jittery opening.

### Reproduction Link
<a href="https://codepen.io/xon5/pen/dEVoKy" target="_blank">https://codepen.io/xon5/pen/dEVoKy</a>

### Other comments
I noticed that when using the &lt;form> tag inside the dialog component the dialog opens oddly. You have to watch carefully, and if you open close and open it quickly enough it opens properly - but if you wait a second between opening (and for the first opening), it seems to bounce as it's opening.

**Comment by Mikilll94** [comment]
It's hard to reproduce that but I can confirm that few times I have noticed this jittery opening.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
