### ISSUE TITLE
[Bug Report] VToolbar should be used before VNavigationDrawer in DOM

### ISSUE THREAD

**Issue by Akii** [vuetifyjs/vuetify#7247]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.13.6

### Steps to reproduce
Change order of components in the DOM: Use VToolbar as first component in VApp, VNavigationDrawer second.

### Expected Behavior
I would expect it to work the same regardless of ordering.

### Actual Behavior
Clips over the shadow dropped by the VToolbar.

### Reproduction Link
<a href="https://codepen.io/anon/pen/NVaPEG, https://codepen.io/anon/pen/WBZbgr" target="_blank">https://codepen.io/anon/pen/NVaPEG, https://codepen.io/anon/pen/WBZbgr</a>

### Other comments
This is just the "CSS" bug. The actual problem is semantics. The VToolbar must come first as it is the first element on the page. This is especially a problem with regard to accessibility and order of tabbing through. Documentation must also be fixed as it advices to put VNavigationDrawer first in "default app layout". A possible fix could be to set the z-index to 4 on the VToolbar.

**Comment by johnleider** [comment]
You reported this is in alpha but provided a 1.5 codepen. It is working as expected in the most recent beta version.

https://codepen.io/johnjleider/pen/RmvrJj
