### ISSUE TITLE
Navigation drawer shows up on page refresh

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#725]
### Steps to reproduce
Open https://vuetifyjs.com/vuetify/quick-start
Enable network throttling in devtools
Refresh page via browser

### Versions
latest (0.12.6)
Chrome 58.0.3029.110 (64-bit) Linux

### What is expected ?
Navigation drawer shouldn't be initially visible on page refresh

### What is actually happening ?
If we use ```enable-resize-watcher persistent``` options navigation drawer is hidden by default on small devices. But on page refresh the drawer becomes visible for a moment and pushes content to the right (or even make content width smaller)
![peek 2017-06-08 15-41](https://user-images.githubusercontent.com/339596/26929374-196fdc12-4c62-11e7-9bb9-a01ec95a8bab.gif)

### Reproduction Link
Any official vuetify docs page

**Comment by tforssander** [comment]
@johnleider I'm still seeing this issue in v0.16.4. Thank you!

**Comment by johnleider** [comment]
Please create a regression issue, ty.
