### ISSUE TITLE
[Bug Report] Display events parallelly in 'day' and 'week' views if same date and time slot is allocated 

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#7251]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.5.18
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
1- Add events in calendar with same date and time.
2- Switch to week or day view
3- Events will be stacked on each other and only last event wil be visible. 

### Expected Behavior
If same date and time is allocated to events the events should be displayed parallelly.

### Actual Behavior
Events are getting stacked and only last event is getting displayed.

### Reproduction Link
<a href="https://codepen.io/anon/pen/YbrgQp?editors=1010" target="_blank">https://codepen.io/anon/pen/YbrgQp?editors=1010</a>

**Comment by ClickerMonkey** [comment]
The example is not using the new event props which has the functionality to avoid event collision. Please switch over to the new (v2.0) props to take advantage of event functionality.

Any code before v2.0 assumes you'll handle the rendering logic yourself.
