### ISSUE TITLE
[Bug Report] List component is rendering twice

### ISSUE THREAD

**Issue by Alizadeh118** [vuetifyjs/vuetify#7252]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.5.22
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
use v-form and v-text-filed beside list component

### Expected Behavior
Component would be rendered once. (console would log each item once)

### Actual Behavior
When v-form and v-text-filed are present, the list component is rendering twice (console is logging each item twice)

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-0nttr?fontsize=14" target="_blank">https://codesandbox.io/s/vue-template-0nttr?fontsize=14</a>

**Comment by jacekkarczmarczyk** [comment]
see https://github.com/vuejs/vue/issues/6351
