### ISSUE TITLE
[Bug Report] v-form in scrollable modal component width issue

### ISSUE THREAD

**Issue by publicaccount365** [vuetifyjs/vuetify#7253]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chromium 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
Hello,
When using v-form component inside the modal as shown in sample codesandbox the form with is not filling the whole modal.
This seems to be fixed by adding width:100% to ".v-dialog--scrollable>form"

### Expected Behavior
Form is filled in the whole modal

### Actual Behavior
with is partial of the modal width

### Reproduction Link
<a href="https://codesandbox.io/s/vue-modal-form-mrgr8?fontsize=14" target="_blank">https://codesandbox.io/s/vue-modal-form-mrgr8?fontsize=14</a>

**Comment by AndreaRylander** [comment]
It seems to work if you remove the v-form tags

**Comment by jacekkarczmarczyk** [comment]
another workaround https://codepen.io/anon/pen/XLJZRa?editors=1000
