### ISSUE TITLE
[Bug Report] V-Calendar type month - can't centering month&day together on First Day and clickable on month text

### ISSUE THREAD

**Issue by ttquoccuong** [vuetifyjs/vuetify#7255]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
I think month should be put inside `v-calendar-weekly__day-label`

### Expected Behavior
Centering Month&Day together

### Actual Behavior
can't Centering Month&Day together

### Reproduction Link
<a href="https://codepen.io/ttquoccuong/pen/JqOYqK" target="_blank">https://codepen.io/ttquoccuong/pen/JqOYqK</a>

**Comment by ClickerMonkey** [comment]
This example uses an old version of the calendar, the newer versions match Google Calendar behavior and already have month and date centered.
