### ISSUE TITLE
[Bug Report] Autocomplete/Combobox counter prop uses item text instead of item value for length

### ISSUE THREAD

**Issue by ianperez** [vuetifyjs/vuetify#7257]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 7

### Steps to reproduce
Select a value in either the combobox or autocomplete inputs

### Expected Behavior
Counter uses length of item value

### Actual Behavior
Counter uses length of item text

### Reproduction Link
<a href="https://codepen.io/anon/pen/VOrrEm" target="_blank">https://codepen.io/anon/pen/VOrrEm</a>

**Comment by KaelWD** [comment]
v-combobox is more like v-text-field, and was never intended to work with objects. If I type "seventeen" I'd expect the counter to be `9`
A counter doesn't really make sense on v-autocomplete without `multiple`, where it does work correctly.

**Comment by enkhtulga** [comment]
I have another question. Please answer if possible. I am using v-autocomplete component with v-slot:selection template. when i change my items from categoryList to restaurantList and select one restaurant, it will not shown as selected on v-slot:selection template. How can i update v-slot:selection data? Thank you.
![question](https://user-images.githubusercontent.com/6397097/58450118-20d17a00-8140-11e9-9e7f-8145d4b86381.PNG)

**Comment by johnleider** [comment]
This is not a bug and the intended functionality at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
