### ISSUE TITLE
[Bug Report] Autocomplete/Combobox can't select same item after modifying input

### ISSUE THREAD

**Issue by ianperez** [vuetifyjs/vuetify#7259]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 7

### Steps to reproduce
Select a value in either the combobox or autocomplete inputs.  Press backspace to delete the last character.  Try to click the same value again from the list.

### Expected Behavior
Clicked item is selected

### Actual Behavior
Clicked item is not selected

### Reproduction Link
<a href="https://codepen.io/anon/pen/VOrrEm" target="_blank">https://codepen.io/anon/pen/VOrrEm</a>

**Comment by KaelWD** [comment]
Cherry-picked: aa9e7cbe1
