### ISSUE TITLE
I found a bug in web - its multiplies the last row

### ISSUE THREAD

**Issue by fortil** [vuetifyjs/vuetify#726]
When you entry to any component that it have multiple selectors in the API section, when you choose repeatedly each options one of this, its multiplies the last row.

this happened to me in https://vuetifyjs.com/components/lists

![image](https://user-images.githubusercontent.com/6068654/26945450-609b111c-4c51-11e7-8270-10e5cd9ff05b.png)

**Comment by cawa-93** [comment]
+1

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
