### ISSUE TITLE
[Feature Request] Provide"autofocus" property on input components

### ISSUE THREAD

**Issue by SirLamer** [vuetifyjs/vuetify#7263]
### Problem to solve
Form auto-complete / auto-suggestion is a common feature but oftentimes it relies on algorithms in the browser to predict the intention of forms. Sometimes it gets it wrong. HTML standards have introduced the "autocomplete" property on <input> to hint to the browser which fields should receive suggestion and, sometimes, which should not.

References:
https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#use_metadata_to_enable_auto-complete

https://www.w3schools.com/tags/att_input_autocomplete.asp

### Proposed solution
Provide "autocomplete" property on the Vuetify input components which rely on the "input" HTML element.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/byYZBr

**Comment by jacekkarczmarczyk** [comment]
Oops, the title says about "autofocus", please update title or description. BTW - there's also `browser-autocomplete` prop for vuetify inputs
