### ISSUE TITLE
[Bug Report] Alert icon

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuetifyjs/vuetify#7264]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
Set RTL to a true icon margin doesn't change 

### Expected Behavior
Icon margin should be a vice versa

### Actual Behavior
_

### Reproduction Link
<a href="https://codepen.io/miladmeidanshahi/pen/KLZzyN?&editable=true&editors=101" target="_blank">https://codepen.io/miladmeidanshahi/pen/KLZzyN?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
This is resolved in 2.0
