### ISSUE TITLE
[Feature Request] Problem on vuetify  Persian datepicker

### ISSUE THREAD

**Issue by Saeid32** [vuetifyjs/vuetify#7266]
### Problem to solve
when use datepicker with "fa" after select month year add to one!!!

### Proposed solution
this is byg

**Comment by jacekkarczmarczyk** [comment]
If it's a bug please use the bug template instead of feature request. See also https://github.com/vuetifyjs/vuetify/issues/1892 if it's not the same issue you're reporting
