### ISSUE TITLE
[Bug Report] New VListItem types arent registered

### ISSUE THREAD

**Issue by buksy90** [vuetifyjs/vuetify#7267]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
In following commit https://github.com/vuetifyjs/vuetify/commit/afed09a following file packages/vuetify/src/components/VList/index.ts got updated and *VlistItem* has been introduced over *VListTile* which got deprecated.

Unfortunately, this new component wasnt introduced in types/lib.d.ts file and therefore when referencing this new component in my project I got ts error.

### Expected Behavior
No ts error should be shown when using this package

### Actual Behavior
Following ts error is shown
>TS2305: Module '"vuetify/lib"' has no exported member 'VListItem'.

### Reproduction Link
<a href="https://codepen.io" target="_blank">https://codepen.io</a>

### Other comments
Please add following components into lib.d.ts file:
- VListItem,
- VListItemAction,
- VListItemAvatar,
- VListItemIcon,
- VListItemGroup,

**Comment by sh7dm** [comment]
Fixed in a090fe1
