### ISSUE TITLE
[Bug Report] false-value is not return undefined

### ISSUE THREAD

**Issue by wizardnet972** [vuetifyjs/vuetify#7269]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.6
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
set false-value to undefined in v-checkbox like this:
```
 <v-checkbox v-model="checkbox" label="Checkbox" :value="true" :false-value="undefined"></v-checkbox>
```

### Expected Behavior
value is undefined

### Actual Behavior
value is null

### Reproduction Link
<a href="https://codepen.io/shlomilevi/pen/BeJJbM?&editable=true&editors=101" target="_blank">https://codepen.io/shlomilevi/pen/BeJJbM?&editable=true&editors=101</a>

### Other comments
Full code
```
<div id="app">
  <v-app id="inspire">
    <v-container fluid>
      checkbox: {{checkbox | json }}
      
      <v-checkbox v-model="checkbox" label="Checkbox" :value="true" :false-value="undefined"></v-checkbox>
    </v-container>
  </v-app>
</div>
```

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/selectable.js#L129

**Comment by wizardnet972** [comment]
Correct I edit my issue and codepen.

The problem is still happen

**Comment by KaelWD** [comment]
- `false-value` only works with `true-value`, not `value`
- You can use a function to trick it: `:true-value="true" :false-value="() => undefined"`

**Comment by KaelWD** [comment]
Not possible, we need to check if the prop is set. There is no way to tell if a prop is present but undefined because vue doesn't even set undefined values on vnodes.
