### ISSUE TITLE
combobox data not showing when access page with vue router

### ISSUE THREAD

**Issue by fauzanmh** [vuetifyjs/vuetify#7275]
combobox data not showing when access page with vue router
this my code

<v-combobox
                    prepend-icon="home"
                    :menu-props="{value:true,closeOnContentClick:true,openOnClick:true,maxHeight:300}"
                    v-model="$v.nama_sekolah.$model "
                    :items="option_sekolah"
                    chips
                    item-text="school_name"
                    item-value="id"
                    label="Nama Sekolah"
                  ></v-combobox>
                  <v-combobox
                    prepend-icon="school"
                    v-model="$v.nama_jurusan.$model "
                    :items="option_jurusan"
                    chips
                    item-text="full_name"
                    item-value="id"
                    label="Nama Jurusan"
                  >
                    <template v-slot:selection="data">
                      <v-chip
                        :key="JSON.stringify(data.item)"
                        :selected="data.selected"
                        class="v-chip--select-multi"
                        @click.stop="data.parent.selectedIndex = data.index"
                      >
                        <v-avatar
                          class="accent white--text"
                        >{{ data.item.full_name.slice(0, 1).toUpperCase() }}</v-avatar>
                        {{ data.item.full_name }}
                      </v-chip>
                    </template>
                  </v-combobox>

and sorry for my english

**Comment by dwweb0309** [comment]
Got the same problem, and couldn't find solution anywhere
