### ISSUE TITLE
[Bug Report] v-form containing v-text-field will affect page css

### ISSUE THREAD

**Issue by shengjun** [vuetifyjs/vuetify#7276]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Reproduction Link
<a href="https://jsfiddle.net/u6aok9mq/54/" target="_blank">https://jsfiddle.net/u6aok9mq/54/</a>

### Other comments
After refreshing page other css layout Lost（For example, the effect of aos.js is broken after refreshing.）

**Comment by shengjun** [comment]
After testing, I think there may be some problems with my layout.

**Comment by shengjun** [comment]
After testing, I found that something may be related to nuxtjs. It is normal to change the mode in nuxt.config.js from universal to spa.😑

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
