### ISSUE TITLE
[Bug Report] V-menu doesn't close when clicking on iFrame

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#7277]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 7

### Steps to reproduce
Create a v-menu on a main page.
Explicitly set close-on-click to true on the v-menu
Create an iFrame within that main page
If you click anywhere in the iFrame, the menu will not auto-close.

### Expected Behavior
The menu should close when the mouse is clicked off of it

### Actual Behavior
The menu stays up and does not close

### Reproduction Link
<a href="https://codepen.io/anon/pen/zQRJWY" target="_blank">https://codepen.io/anon/pen/zQRJWY</a>

**Comment by KaelWD** [comment]
It is not possible to listen to events from a cross-browser iframe. This may be fixed at some point if we go with an invisible overlay for #5310, but it is not a great priority at the moment.
