### ISSUE TITLE
v-checked @change事件时 没有event 只有value 然而我需要阻止冒泡

### ISSUE THREAD

**Issue by yannanna0920** [vuetifyjs/vuetify#7281]
v-checked @change事件时 没有event 只有value 然而我需要阻止冒泡<v-checkbox v-model="td.has" class="percheck" :label="td.displayName" @change="grandsonChange((checkbox = $event), tr, item, td, tableList.items, s)" >
![v-checkebox](https://user-images.githubusercontent.com/48897146/58303554-36cefa00-7e23-11e9-94de-598520d044f6.gif)

**Comment by jacekkarczmarczyk** [comment]
@yannanna0920 The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
