### ISSUE TITLE
[Bug Report] delay on closing badge if transition is disabled

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7282]
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
Click the button twice

### Expected Behavior
Badge shows instantly on the first click but hides with delay on the second click

### Actual Behavior
Badge should hide instantly

### Reproduction Link
<a href="https://codepen.io/anon/pen/rgdxrX" target="_blank">https://codepen.io/anon/pen/rgdxrX</a>

### Other comments
Bug exists in 1.5.x as well, there's no prop for controlling open/close delay (even with such prop there should be no delay)

**Comment by sh7dm** [comment]
fixed by 98d9a3a
