### ISSUE TITLE
[Feature Request] Set colors for true and false for the switch element

### ISSUE THREAD

**Issue by fr4gst4** [vuetifyjs/vuetify#7284]
### Problem to solve
Currently it is possible to set a color for switches when they return a true value. When they return false, their color is white.

It would be possible to have a green color for true and a red color for false.

### Proposed solution
Currently you can solve the problem with some custom CSS

https://codepen.io/DutchmanSA/pen/rgdzBq

but it would be nice to have two color properties like

activeColor="success"
inActiveColor="error"

**Comment by kosratdev** [comment]
Are there any updates about this feature?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by batusekerci** [comment]
Any updates about this feature?

**Comment by SteamWind** [comment]
I feel like the switch component could be really improved and this feature would be a great one to add. You can see, a lot of users upvoted the idea.
A switch should be something to select between two states. Be able to document those states with different colors is a good idea.
In the same direction, being able to have a label on each sides would be great...

**Comment by SteamWind** [comment]
Thank you for this @johnleider ! 😄 
That was quick!

**Comment by johnleider** [comment]
> Thank you for this @johnleider ! 😄 That was quick!

I happened to be in the file when I read your comment so you got lucky :)
