### ISSUE TITLE
[Bug Report] Extra Header in Vuetify Data Table

### ISSUE THREAD

**Issue by bsk25** [vuetifyjs/vuetify#7285]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.5.18
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Run the component provided in code pen.
Go to WAVE TOOL.
We see an error stating empty header cell.

### Expected Behavior
Extra Header Column should not be seen.

### Actual Behavior
Extra Header Column is visible resulting in error --Empty Header Cell.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xNWXpd#anon-login" target="_blank">https://codepen.io/anon/pen/xNWXpd#anon-login</a>

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by bsk25** [comment]
Here's the latest pen -- https://codepen.io/tomHarry/pen/xNWXpd

Can you check if this is reproducible at your end?

**Comment by nekosaur** [comment]
It is not. Use https://template.vuetifyjs.com as your base

**Comment by bsk25** [comment]
Please check now 
https://codepen.io/tomHarry/pen/BerYmv

Issue in short --

Table header in vuetify with class as "datatable__progress" is having empty heading cell.

What is the use of this extra header column.?
How can we remove this header from the main headers defined and tagged to header property in v-data-table.?

**Comment by bsk25** [comment]
> It is not. Use https://template.vuetifyjs.com as your base

I have fixed it.
Can you check now.?

**Comment by jacekkarczmarczyk** [comment]
it's a container for displaying progress loader if `loading` prop is set to true.
Extra header is not in the markup anymore in 2.0 (unless `loading` is true)
