### ISSUE TITLE
Button Colors

### ISSUE THREAD

**Issue by sgehrman** [vuetifyjs/vuetify#729]
just updated to the latest. one change that doesn't work for me. I had my buttons set to primary which use to be blue with white text, now the text is black, so I set the button to primary light, and that looks fine, but when disabled on a white background, the button disappears. Is this expected behaviour?
Also, if I set the button to light, i get a gray button with white text which looks weird.

**Comment by johnleider** [comment]
This is already resolved on dev. The entire theme system has been rebuilt and small.detsild like this are accounted for.

**Comment by chidonna** [comment]
Still doesn't work
