### ISSUE TITLE
[Bug Report] v-autocomplete: Deleting selected item, then typing, causes invisible characters

### ISSUE THREAD

**Issue by lankyfrenchman** [vuetifyjs/vuetify#7291]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Safari, Google Chrome
**OS:** iOS, Mac OSX

### Steps to reproduce
- Start typing, and select one of the options offered from autocompletion.
- Focus away from the v-autocomplete.
- Focus on the v-autocomplete again.
- Delete *exactly* as many characters as the selected option.
- Hit delete *exactly* one more time.
- Type any characters.

### Expected Behavior
The input would function, and present options based on new inputs.

### Actual Behavior
The cursor moves as through there is text, but no text is visible in the form.

### Reproduction Link
<a href="https://codepen.io/anon/pen/LodXKo?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/LodXKo?&editable=true&editors=101</a>

### Other comments
Tested on our code with Vuetify version 1.5.7, but the example on Codepen is directly from Vuetify's website's documentation.

**Comment by johnleider** [comment]
This is resolved as of v2.2.26 and will not be backported.

This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
