### ISSUE TITLE
[Bug Report] Treeview 'input' event fired on component initialization

### ISSUE THREAD

**Issue by supraniti** [vuetifyjs/vuetify#7296]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Create a treeview component
Attach an event handler to 'input event'

### Expected Behavior
the event callback should be executed on an input event triggered by the user
when the component is initialized no input events should be fired

### Actual Behavior
an input  event is fired on component initialization without any user action involved

### Reproduction Link
<a href="https://codepen.io/supraniti/pen/EzLNWP" target="_blank">https://codepen.io/supraniti/pen/EzLNWP</a>

**Comment by sh7dm** [comment]
Fixed in 023e596
