### ISSUE TITLE
[Feature Request] V-Carousel-Item crops the image

### ISSUE THREAD

**Issue by aabounegm** [vuetifyjs/vuetify#7303]
### Problem to solve
When using the carousel without `height="auto"`, any image bigger (in width or height) than the default height will be cropped to fit the container exactly. This is due to the CSS property `background-size: cover` being set by default. This way, it is not possible to set a maximum height while viewing the entire picture.

### Proposed solution
Add an option (prop) to the v-carousel-item component that would allow changing the property from `background-size: cover` to `background-size: contain`.

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify/issues/7231#issuecomment-493727927

**Comment by aabounegm** [comment]
Then I think the fact that 
> v-carousel-item extends v-img

needs to be mentioned in the documentation of v-carousel-item
