### ISSUE TITLE
Better control over slots in DataTables 

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#731]
*enhancement*

## Current implementation
Currently the slots for `items` and `headers` allow control of how each header column and each data row is displayed. Especially for the headers slot the current implementation gives very limited amount of control. 

### Slot `headers`
Proposal: allow slotting in a full `<thead></thead>` instead of just the formatting for the column.
Why? As an example, we might want to have merged columns or two rows as header. 
Possible issues: would break backwards compatibility for existing solutions. Could introduce a new slot `headersRow` instead which would include the current slot also.

### Slot `items`
Proposal: allow slotting in the full row `<tr></tr>` instead of just the `<td></td>`
Why? This would allow styling of the rows but also crucially would give control to create 2 rows per entry if wanted.
Possible issues: breaks backwards compatibility especially because this slots will be used quite a bit in existing projects. Could maybe introduce an additional slot `itemsRow` instead which would include the current implementation.

**Comment by nekosaur** [comment]
This request has come up before and I think I am in agreement that we should be more flexible here. Adding two more slots is a slightly clunky solution and might lead to confusion on which to use. I think it might be possible to have a single slot and then inspect the provided template to know if we should create a `tr` tag or not.

**Comment by duebbert** [comment]
yes, probably cleanest changing the current slots and checking for a `tr` tag, although a bit hack-ish... but it would keep backwards compatibility.

**Comment by sindrepm** [comment]
Another +1 for this feature. I especially miss the option to style the entire row. Inspecting the template for a  `<tr>` doesn't sound like a good idea, though. Is it out of the question to make this a breaking change given that Vuetify is not 1.0 yet? There have been other breaking changes recently so I don't see this as such a big problem. It should be easy for developers to adapt existing code to this change (just wrap the slot template in a `<tr>`.

**Comment by johnleider** [comment]
I don't mind breaking changes like this. +1

**Comment by duebbert** [comment]
Thanks, great that it's implemented for the items. Would be just as
important for the header... Not sure how difficult that is?

**Comment by johnleider** [comment]
I merged his PR in too soon. He's doing that right now.

**Comment by duebbert** [comment]
Fantastic! Thanks!
