### ISSUE TITLE
[Bug Report] Auto grow text fields on load in v-stepper

### ISSUE THREAD

**Issue by kkojot** [vuetifyjs/vuetify#7312]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Open the codepen, click Continue button, you will see that the text area is not auto-grown with preloaded content.

### Expected Behavior
Text area should be auto-grown in all steps in v-stepper component.

### Actual Behavior
Text area is not auto-grown in every steps in v-stepper component ;)

### Reproduction Link
<a href="https://codepen.io/anon/pen/WBKGOG" target="_blank">https://codepen.io/anon/pen/WBKGOG</a>

### Other comments
Similar issue with expansion panel #3300
Reporoduced with the vuetify 2.0.0-alpha20 https://codepen.io/anon/pen/byjqbN

**Note**: Changing the value in one step collapses text area in the other steps.

**Comment by Nicholayton11** [comment]
Hi,

I'm having a similar issue to this.

Using Vue-Chart.js and <v-card>. The card does not expand to compensate for the size of the chart and causes the chart to overlap text.

**Comment by jacekkarczmarczyk** [comment]
VStepperContent should be bootable

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
