### ISSUE TITLE
[Bug Report] some outlined icons does not appear

### ISSUE THREAD

**Issue by jjangga0214** [vuetifyjs/vuetify#7313]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Ubuntu undefined

### Steps to reproduce
Please visit the repro link.

### Expected Behavior
`append-icon="visibility_outline"` should 
1. place the icon at the rightmost of the text field
2. show an outlined icon

### Actual Behavior
1. The appending icon is placed at more left than it should. 
2. The appending icon is not outlined icon. It's filled icon.

### Reproduction Link
<a href="https://codepen.io/jjangga0214/pen/KLBmoG" target="_blank">https://codepen.io/jjangga0214/pen/KLBmoG</a>

### Other comments
Funny thing is `lock_outline` does work, but `visibility_outline` doesn't.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/google/material-design-icons/issues/787
