### ISSUE TITLE
[Bug Report] Using whitespace in an async autocomplete doesn't work

### ISSUE THREAD

**Issue by dploeger** [vuetifyjs/vuetify#7314]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.4

### Steps to reproduce
* Enter "Luk" into the search field => "Luke Skywalker" is shown as a search result
* Enter "Luk " (add whitespace) into the search field => No data is found

### Expected Behavior
Both searches should return results as the backend call is actually returning results (check DevTools)

### Actual Behavior
Adding a whitespace leads to "No data found"

### Reproduction Link
<a href="https://codepen.io/anon/pen/BePZJM?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/BePZJM?&editable=true&editors=101</a>

### Other comments
This doesn't seem to happen with static items, only when the search is directly carried out via REST

**Comment by KaelWD** [comment]
The component doesn't do fuzzy matching, and `'Luke Skywalker'.includes('Luk ')` is false. Use `no-filter` if you're doing the search entirely server-side.

**Comment by dploeger** [comment]
Ahhh! That's the thing I missed. Thanks.
