### ISSUE TITLE
[Feature Request] Add a "dense" variant to "text-field"

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#7316]
### Problem to solve
All MD `text-fields` are unnecessarily too tall, including the `single-line` variants.

Look at the dense variant of the text-fields of the material-ui framework:
https://material-ui.com/components/text-fields/#outlined

### Proposed solution
Add a `dense` variant so that text-fields become usable in rather dense layouts

**Comment by MajesticPotatoe** [comment]
Duplicate of #1846
