### ISSUE TITLE
button disable problem

### ISSUE THREAD

**Issue by wilsonwu** [vuetifyjs/vuetify#732]
### Versions
2.3.3

### What is expected ?
button should be disabled

### What is actually happening ?
when a button with "light" prop, the "disabled" dose not work, when add "disabled" the button disappear

### Reproduction Link
code in below:
<v-btn light disabled>Stop</v-btn>

**Comment by mornir** [comment]
I'm not sure, but I don't think that the light prop was designed to be used on a white background.
On a dark background, it looks fine: https://codepen.io/mornir0/pen/vZLmoB

**Comment by mornir** [comment]
related to #729

**Comment by wilsonwu** [comment]
Got it, thanks for your reply, but seems can do some improve, whatever, this not a issue.

**Comment by johnleider** [comment]
This has been resolved on dev.
