### ISSUE TITLE
[Feature Request] Making Vuetify native for mobile app development

### ISSUE THREAD

**Issue by navicstein** [vuetifyjs/vuetify#7324]
### Problem to solve
This bridges the gap between opting in for ionic or other framework for mobile app development

### Proposed solution
am looking forward to leverage on Vuetify to scrape a mobile solution just like ionic but for Vue, ionic-vue does'nt just solve the problem

**Comment by KaelWD** [comment]
https://github.com/m0dch3n/vue-cli-plugin-cordova
