### ISSUE TITLE
[Bug Report] FOUC on ssr

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#7326]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.54
**OS:** Windows 10

### Steps to reproduce
Happens when vuetify loader is used. When its not used all fine. And all fine in 1.x version of vuetify.
The link just use VChip, but that applies not only to it but to other components as well.

### Expected Behavior
no FOUC

### Actual Behavior
FOUC

### Reproduction Link
<a href="https://codesandbox.io/s/q3lyoq6vkq" target="_blank">https://codesandbox.io/s/q3lyoq6vkq</a>

### Other comments
https://i.imgur.com/RXiRPvm.png  here some discussion and findings

**Comment by KaelWD** [comment]
This likely has to do with the changes in `@nuxtjs/vuetify`, it looks like the 1.x version isn't applying vuetify-loader at all. The only difference in vuetify from 1.x to 2.x was sass instead of stylus, and vuetify-loader just adds imports to each component, not traversing the entire tree like kevin says.

**Comment by kevinmarrec** [comment]
@KaelWD As far I investigated, it seems to be lazy load of Nuxt pages.
If `v-btn` (for example) is used for the first time around Nuxt Layout, everything works fine (styles are passed through SSR)
If it's in a Nuxt page, `v-btn` styles are inlined and not passed through SSR, wich means they are added at runtime, which cause FOUC.

**Comment by KaelWD** [comment]
I'm guessing nuxt inlines styles from the layout, and then uses style-loader to inject component styles client-side. This wasn't noticed before because the full vuetify.css was still being imported too. 

Basically neither vuetify or vuetify-loader touch the build config at all, it's still up to you to load everything the way you want.

**Comment by kevinmarrec** [comment]
@KaelWD With 1.5, I was excluding `vuetify.css` for build by using `css: NODE_ENV !== 'production'`, and there wasn't issues. Or maybe there was but it wasn't noticable cause Vuetify 2 changed how the theme is applied.

=> Theme styles are inlined and causing CSS animations from default theme to theme defined around component props (`dark` property)

**Comment by KaelWD** [comment]
Theme styles were inlined in 1.x too. (assuming you're talking about `.primary` etc.)

**Comment by kevinmarrec** [comment]
I'm talking about the last one on this screenshot :
![Screenshot from 2019-05-29 16-23-48](https://user-images.githubusercontent.com/25272043/58564952-345b0e80-822e-11e9-8353-f12dff2e3368.png)

**Comment by KaelWD** [comment]
https://github.com/nuxt/nuxt.js/blob/e161d70a4fbce31435c63daa1e464bb49bc7da3b/packages/config/src/config/build.js#L77-L80

**Comment by KaelWD** [comment]
I tried making a vuetify 1.x sandbox with `css: false` and it's still inlining the entire vuetify.css, not just used components: https://codesandbox.io/s/ep1xb

**Comment by kevinmarrec** [comment]
Tried splitChunks with different settings, no success.
Hum where is entire `vuetify.css` ? I looked for `v-btn` and only find one occurence, so I guess there isn't whole vuetify.css ?

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/58566357-e0731880-8273-11e9-81d8-368dcd44e497.png)

**Comment by aldarund** [comment]
i dont think full css included. I was able repro in 1.5 at least for vchip https://codesandbox.io/s/codesandboxnuxt-yvu44

**Comment by KaelWD** [comment]
Oh, `@nuxtjs/vuetify` isn't using the usual module configuration? https://nuxtjs.org/api/configuration-modules

Either way this is definitely related to build config and not something we can change. You're also gonna have some level of FOUC with ssr by nature unless you defeat the whole point by hiding the page until everything's loaded.

**Comment by aldarund** [comment]
not quite follow about not using usual module configuration. It is using it, at least it should unless there some bug :) Using vuetify key is an alternative way to configure it

**Comment by kevinmarrec** [comment]
@KaelWD What about svg icons turning black to white like on https://marrec.io ? I guess it will always happen using SSR and lazy loaded components even on non-Nuxt projects, no ?

**Comment by KaelWD** [comment]
> not using usual module configuration

I originally had `["@nuxtjs/vuetify", {
    css: false,
    treeShake: true
  }]` and it didn't seem to be applied. 

> svg icons turning black to white

If you disable js you'll see the css doesn't load, so it's just using the default colour from `<html>`. On vuetifyjs.com we are extracting css but you'll still see some white flashes and size changing from the default user-agent styles.
