### ISSUE TITLE
[Bug Report] custom headers not fixed when using datatable with fixed-header prop

### ISSUE THREAD

**Issue by kylejoeckel** [vuetifyjs/vuetify#7330]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
create basic implementation of datatable using version 2.0beta.0
add props fixed-rows and hide-default-rows 
add template v-slot:header={props:{header}} for custom header

### Expected Behavior
custom header should be fixed to top 

### Actual Behavior
custom header acts as another row and scrolls with entire table

### Reproduction Link
<a href="https://codepen.io/kylejoeckel/pen/VOGNEq" target="_blank">https://codepen.io/kylejoeckel/pen/VOGNEq</a>

### Other comments
i see that fixed headers works using the standard headers but this is not very useful when implementing custom header components

**Comment by KaelWD** [comment]
You need to use `th` not `td`

**Comment by kylejoeckel** [comment]
Well ok then the docs need to be updated... I copied this example directly from Vuetifyjs.com

Thanks

**Comment by KaelWD** [comment]
https://next.vuetifyjs.com/en/components/data-tables#slots
