### ISSUE TITLE
[Bug Report] v-slot:body not overriding default body in datatable

### ISSUE THREAD

**Issue by kylejoeckel** [vuetifyjs/vuetify#7332]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
create basic implantation of datatable using version 2.0beta.0
add props fixed-rows and hide-default-headers
add template v-slot:header={props:{header}} for custom header
add template v-slot:body={items} for custom body

### Expected Behavior
body should only have two column 'item.name' and "content" given custom body template

### Actual Behavior
body displays all data in object

### Reproduction Link
<a href="https://codepen.io/kylejoeckel/pen/VOGNEq" target="_blank">https://codepen.io/kylejoeckel/pen/VOGNEq</a>

### Other comments
this may be another documentation issue but i figured id submit it anyways..

**Comment by nekosaur** [comment]
Yeah this is a documentation issue. You can't override body slot when using virtual rows

**Comment by kylejoeckel** [comment]
oh bummer, that's unfortunate.

**Comment by nekosaur** [comment]
What is your use-case that you need to override body and not just single rows?

**Comment by kylejoeckel** [comment]
well I was conditionally rendering some items and formatting the data this way, however after you shot me down lol i found a better way using a computed prop with map and actually sped up load time pretty dramatically so that's all good. 
however, i was also using v-tooltip to display the original non-formatted data string on hover, this i have not solved but i think we can live without it so either way...

**Comment by kylejoeckel** [comment]
i could think of some use cases that i will likely run into soon though such as adding crud action buttons and column formatting now that this is an option with v2.0.0

**Comment by kylejoeckel** [comment]
also now that i think about it more, i have a feature to hide/display columns that will not work to my unless i can add a conditional to the <td> tag in the body.

**Comment by nekosaur** [comment]
You should be able to control which headers are shown just by modifying what you send to `headers` prop
