### ISSUE TITLE
[Bug Report] VueCLI3 Production build Error: 'TypeError: Cannot read property 'isDark' of undefined'

### ISSUE THREAD

**Issue by jvanst** [vuetifyjs/vuetify#7333]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
- `yarn install`
- `yarn build`
- Serve '/dist' folder via http (I have been using https://www.npmjs.com/package/serve)

### Expected Behavior
Root page loads without vender bundle errors.

### Actual Behavior
v-btns and a link elements fail to load due to error reported in the console:

```
vue.runtime.esm.js:1888 TypeError: Cannot set property 'isDark' of undefined
    at a.handler (index.js:87)
    at a.t.$watch (vue.runtime.esm.js:4943)
    at yr (vue.runtime.esm.js:4900)
    at mr (vue.runtime.esm.js:4882)
    at or (vue.runtime.esm.js:4642)
    at a.t._init (vue.runtime.esm.js:5000)
    at new a (vue.runtime.esm.js:5148)
    at on (vue.runtime.esm.js:3283)
    at init (vue.runtime.esm.js:3114)
    at d (vue.runtime.esm.js:5972)
```

### Reproduction Link
<a href="https://github.com/jvanst/requestly" target="_blank">https://github.com/jvanst/requestly</a>

### Other comments
This problem only seems to exist when building with NODE_ENV = production (`yarn build`).
Building the project with the mode flagged as development works fine, use `yarn build-dev`

**Comment by johnleider** [comment]
I looked at this yesterday per our discussion in discord and was not able to reproduce the error.

**Comment by jvanst** [comment]
Thanks again for taking a look. I was able to resolve this by removing some bad code, but I still have no idea why it was an issue in production mode and not development.

**Comment by neelance** [comment]
@jvanst We are seeing the same issue for some of our users. Could you tell me what your bad code was about? Maybe it can give me a clue on where to look.

**Comment by jvanst** [comment]
I will try my best to give more details but I never narrowed it down.

If your receiving the 'isDark' error in **development mode** (npm run serve) then I would believe that is a bootstrapping issue, not related to my issue here.

I was only getting this error when I had built my bundle (npm run build), then served the app in the browser. Elements were not being rendered and the 'isDark' error was reported in the browser console multiple times.

In my project I had built a Vue mixin that controlled the visibility and properties for a `snackbar.vue` component (which was simply a `v-snackbar`). Removing all instances of this component and mixin from being included in my bundle solved the isDark error for me.

A user by the name _Canh Kieu_ posted a solution in Discord to a relevant isDark issue:

> Do you remember few day ago I post an error that Can not access with isDark in Vue.extend() component. Now i found the way to fix it.
![EEDaSuFGdOLB8NMtSPd5IABKQgAQkIAGPE9BzEDyuy9VgCUhAAhKQgGuBch61vIjBIRbOHk7gtUUJZLveh0pIQAISkIAEJOBmAnp](https://user-images.githubusercontent.com/6911907/59930008-f5c10a00-940f-11e9-98d1-59087917bf2e.png)

I am no Vue expert, but my instance of the isDark issue was related to Vue.Mixin and he is claiming here that it was also an issue with Vue.Extends.

At the end of the day I still don't really know :man_shrugging: but I hope this information may lead to someone finding a solution they need.

You can clone and run my project here:
- isDark error: https://github.com/jvanst/requestly/tree/623fdb666e4411944e30b086dd620017f228ccdc
- Resolved, no more error: https://github.com/jvanst/requestly/tree/b08eb5b5c7238331476564353f68f5754a70cad5

I now know that Vue mixins are not really intended for application code, so I migrated my snackbar control into a Vuex module.

**Comment by neelance** [comment]
Thanks a lot for your detailed report. The strange thing in our case is that it only happens to a subset of our users. We can not reproduce it, which makes it very hard to track down. Maybe upgrading to Vuetify 2 will make it go away. ;-)

**Comment by daneren2005** [comment]
> Thanks a lot for your detailed report. The strange thing in our case is that it only happens to a subset of our users. We can not reproduce it, which makes it very hard to track down. Maybe upgrading to Vuetify 2 will make it go away. ;-)

Any chance did you ever find a work around for this?  We are also only having it happen to end users randomly.  Nothing we can do on our end reproduces it, even on the same production builds.  We are using the Vue CLI's modern build flag, but are having it happen on up to date versions of Chrome so I don't think it is an old device issue.
