### ISSUE TITLE
[Bug Report] datatable fixed-header background color 

### ISSUE THREAD

**Issue by kylejoeckel** [vuetifyjs/vuetify#7334]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
create basic implantation of datatable using version 2.0beta.0
add props fixed-rows and hide-default-headers

### Expected Behavior
fixed header should reflect dark/light background color per the table instance

### Actual Behavior
fixed header background is white and will not change even with style tags

### Reproduction Link
<a href="https://codepen.io/kylejoeckel/pen/VOGNEq" target="_blank">https://codepen.io/kylejoeckel/pen/VOGNEq</a>

**Comment by sh7dm** [comment]
fixed in b040ff3
