### ISSUE TITLE
[Bug Report] BOM mark present in VBreadcrumbs.sass

### ISSUE THREAD

**Issue by buksy90** [vuetifyjs/vuetify#7337]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Open latest version of VBreadcrumbs.sass file ( https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.sass ). When you click edit on this file you can see that there is an invisible char at the very first place in the file.
![image](https://user-images.githubusercontent.com/3020042/58620645-e4308a80-82c7-11e9-8e2f-81cb84376ecf.png)

### Expected Behavior
I would expect files not to contain invisible characters (just like any other in the project).

### Actual Behavior
Currently, there is an invisible character at the first place in the file

### Reproduction Link
<a href="http://codepen.io" target="_blank">http://codepen.io</a>

### Other comments
This character can cause problems with some packages. In my case, I'm unable to build my project when using rollup and sass plugin. But when I skip this file the build success.

**Comment by jacekkarczmarczyk** [comment]
a93403f155e2e5b6b523881545fca1b5d71bdbcc

**Comment by KaelWD** [comment]
blame: c97bd7cdf5e21237946124a7483f8767ecfcde2c
