### ISSUE TITLE
[Bug Report] Use mdiSvg options we get large icons in Data Table

### ISSUE THREAD

**Issue by FFxSquall** [vuetifyjs/vuetify#7338]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
1. Look at Data Table sortable icon

### Expected Behavior
18px icon size

### Actual Behavior
24 px icon size

### Reproduction Link
<a href="https://codesandbox.io/s/table-vuetify-491wg" target="_blank">https://codesandbox.io/s/table-vuetify-491wg</a>

**Comment by jacekkarczmarczyk** [comment]
It also doesn't rotate on sort

**Comment by KaelWD** [comment]
2.0 has regressed to selecting `i` instead of `.v-icon`
