### ISSUE TITLE
[Bug Report] Sass styles bug

### ISSUE THREAD

**Issue by FFxSquall** [vuetifyjs/vuetify#7339]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Linux x86_64

### Steps to reproduce
1. Look at any rule `.container.grid-list-lg .layout:not(:only-child)`

### Expected Behavior
margin: auto -8 (if gutter 16)

### Actual Behavior
margin: auto-8

### Reproduction Link
<a href="https://codepen.io/anon/pen/eaPbPv" target="_blank">https://codepen.io/anon/pen/eaPbPv</a>

### Other comments
Fix - `margin: auto (-$gutter / 2)

**Comment by johnleider** [comment]
closed by 6f09b23d4
