### ISSUE TITLE
Can swipe feature be added to the sidebar nav on mobile

### ISSUE THREAD

**Issue by zapping** [vuetifyjs/vuetify#734]
For this component https://vuetifyjs.com/layout/pre-defined

![swipefeature](https://user-images.githubusercontent.com/4123026/26970754-1fabf5b8-4d28-11e7-9609-a85c4f6dc249.PNG)

Can swipe feature be added to this on so that it can be closed on a mobile. 

- What will it allow you to do that you can't do today?
You need to have an explicit close button to close the sidenav bar or you have to leave enough space around the component so that it can be closed by touching outside it.

- How will it make current work-arounds straightforward?
If a swipe feature can be added to it then instead of the above or rather in addition to the about features a user can conveniently close it by swiping on the sidenav.

**Comment by johnleider** [comment]
Fixed with #931
