### ISSUE TITLE
[Bug Report] Clearing a v-autocomplete will set the search-input to both `undefined` and `null`

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#7344]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
- Use a v-autocomplete with a two-way bound `:search-input.sync` prop and `clearable`.
- Click the clear button

### Expected Behavior
Bound search prop gets set to only one value, any watchers watching it are only triggered once.

### Actual Behavior
Search prop is first set to `undefined`, and then in a separate update cycle, is then set to `null`.

Watchers watching the search prop are triggered twice, which in practice will possibly cause multiple API calls to a backend server to handle the changed search value to occur.

### Reproduction Link
<a href="https://codepen.io/anon/pen/QRJjPz" target="_blank">https://codepen.io/anon/pen/QRJjPz</a>

**Comment by sh7dm** [comment]
Fixed by 071ae76d7
