### ISSUE TITLE
[Bug Report] Checkboxes are invisible

### ISSUE THREAD

**Issue by ianbarker** [vuetifyjs/vuetify#7356]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
Add a checkbox component

### Expected Behavior
The checkbox should be visible

### Actual Behavior
The checkbox is not visible

### Reproduction Link
<a href="https://codepen.io/anon/pen/wbQxJq?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/wbQxJq?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Default iconfont has been changed to `mdi`, so either include `mdi` css or change `iconfont` to `md`

**Comment by shadow-light** [comment]
Is it possible to use SVG icons in checkbox component?

**Comment by fmarkos** [comment]
https://stackoverflow.com/a/67724488/2076316
`vuetify: {
    icons: {
      iconfont: 'mdiSvg',
     }
  ...
}`
