### ISSUE TITLE
[Bug Report] Autocomplete with outlined prop has text offset rather than centred

### ISSUE THREAD

**Issue by full-stack-solutions** [vuetifyjs/vuetify#7358]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Type in autocomplete and type in text field and compare the text position

### Expected Behavior
Type in autocomplete and text is centred

### Actual Behavior
Type in autocomplete and text is offset

### Reproduction Link
<a href="https://codepen.io/anon/pen/JqezyP?editors=1010" target="_blank">https://codepen.io/anon/pen/JqezyP?editors=1010</a>

**Comment by johnleider** [comment]
This has already been resolved as of beta.8
