### ISSUE TITLE
Feature Request: Tooltip hover delay

### ISSUE THREAD

**Issue by mix3d** [vuetifyjs/vuetify#736]
The ability to specify a timeout delay before the tooltip shows would help declutter the UI when moving the mouse around, which can get very annoying if the tooltip target site is one used very often, but may still need delayed hinting for new users to get hints.

  - What will it allow you to do that you can't do today?
Delay showing the tooltip

  - How will it make current work-arounds straightforward?
No known workaround without editing the tooltip source

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by johnleider** [comment]
This is something the developer should just add a transition-delay to [data-tooltip].
