### ISSUE TITLE
[Bug Report] Unable to build using beta.0

### ISSUE THREAD

**Issue by gsharp021** [vuetifyjs/vuetify#7360]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
Run the codepen.

### Expected Behavior
Code runs without error

### Actual Behavior
Error thrown in codepen: ZNVzQL:1 Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

Error in my dev environment: vuetify__WEBPACK_IMPORTED_MODULE_3___default.a is not a constructor

### Reproduction Link
<a href="https://codepen.io/gsharp/pen/ZNVzQL" target="_blank">https://codepen.io/gsharp/pen/ZNVzQL</a>

**Comment by johnleider** [comment]
You need to supply an actual reproduction of the issue. In this situation, preferably a minimal repository.

**Comment by sh7dm** [comment]
Maybe you need to install your dependencies?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
