### ISSUE TITLE
[Feature Request] add mandatory and multiple props to v-list

### ISSUE THREAD

**Issue by depperm** [vuetifyjs/vuetify#7365]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Click on any item (note the log that the prop is active)
2. Click on the same item (note from the log that the prop is still active but the item is collapsed)

### Expected Behavior
Click on an item that is already expanded/open and have nothing happen.

### Actual Behavior
Click on an item and toggle the visibility

### Reproduction Link
<a href="https://codepen.io/anon/pen/KLrayx?editors=1011" target="_blank">https://codepen.io/anon/pen/KLrayx?editors=1011</a>

**Comment by KaelWD** [comment]
Your logic is incorrect, vue can't detect setting something to the same value it already is. You probably want the `mandatory` prop from v-expansion-panel that doesn't appear to have been implemented on lists.

**Comment by johnleider** [comment]
This was added for v2.

https://codepen.io/johnjleider/pen/YbdmJE?editors=1010

**Comment by KaelWD** [comment]
Doesn't seem to work with `v-list-group`, and `v-list` still has the old `expand` prop instead of `multiple`.

**Comment by depperm** [comment]
@johnleider Can you provide an example of how to apply that to the provided code pen? If it's not possible can this be a feature request?

**Comment by KaelWD** [comment]
v3 has `open-strategy="single"`/`open-strategy="multiple"` but `mandatory` still only affects selection

**Comment by KaelWD** [comment]
@johnleider proposed

`mandatory="true"` - mandatory selection
`mandatory="open"` - mandatory open
`mandatory="both"` - both selection and open are mandatory

Another option would be to split it into two separate boolean props: `mandatoryOpen` and `mandatorySelected`
or make it part of `open-strategy` and `select-strategy` but then it gets a big silly: 
```ts
type SelectStrategy =
  | 'single-leaf'
  | 'leaf'
  | 'independent'
  | 'single-independent'
  | 'classic'
  | 'single-leaf-mandatory'
  | 'leaf-mandatory'
  | 'independent-mandatory'
  | 'single-independent-mandatory'
  | 'classic-mandatory'
```

**Comment by johnleider** [comment]
Do to lack of resources, this Issue is being closed due to inactivity. 

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
