### ISSUE TITLE
[Bug Report] form.validate validates hidden and / or disabled fields

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#7372]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 7

### Steps to reproduce
Enter required Email ID
If the name is hidden (nameShow=false) or disabled (nameShow=true & nameDisable=true) 

### Expected Behavior
Validations should be skipped for Hidden or disabled fields.
As an extension of the same  - form.validate should have a provision to skip validating certain rules (based on specific conditions not necessarily disabled or hidden) 

### Actual Behavior
form.validate returns false but user cannot enter the value of Name ????

### Reproduction Link
<a href="https://codepen.io/prasmi/pen/gJqgvM" target="_blank">https://codepen.io/prasmi/pen/gJqgvM</a>

**Comment by KaelWD** [comment]
> If the name is hidden

We can't easily know this. Use v-if instead or don't apply rules to inputs when hidden. 

> disabled

There isn't really a "right" way for this, and it's worked the same way since the beginning. Again, you can choose not to include a field in the validation by simply not binding rules to it.

**Comment by all43** [comment]
Please reopen.
It's bad idea to validate disabled fields as they don't show any errors.
Inputs might be conditionally disabled and need to be validated in case they are enabled.
Of course I could do something like:
`<v-text-field :disabled="condition" :rules="condition ? [] : actualRules">`
But this is ugly and unwieldy.

**Comment by miryamfv** [comment]
Yes If you could kindly please reopen, I believe is a bug as validating disabled fields is not HTML's natural behavior, Thanks

**Comment by c-ridgway** [comment]
> Yes If you could kindly please reopen, I believe is a bug as validating disabled fields is not HTML's natural behavior, Thanks

+1 This seems like a design flaw. The validation error is also greyed out while disabled, yet still active.

**Comment by c-ridgway** [comment]
> Yes If you could kindly please reopen, I believe is a bug as validating disabled fields is not HTML's natural behavior, Thanks

+1 This seems like a design flaw. The validation error is also greyed out while disabled, yet validation still occurs.

![image](https://user-images.githubusercontent.com/74696795/126245432-a28038da-4fae-42da-b27c-f4d70d9d66d6.png)

@KaelWD

**Comment by shiouming** [comment]
@KaelWD The bug's existence since v1 is a weak justification to mark it as wontfix :sweat_smile:

@everyone Another hack to get around is to add a top condition in validation rule, return true if disabled.

**Comment by monterhealth** [comment]
Cause found: optional hidden required date field still thought it was required.
