### ISSUE TITLE
[Bug Report] No theme applied if component not inside a v-app

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#7375]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
Simply add a v-btn component with primary color, without including a v-app component in the page

### Expected Behavior
The theme to be applied even without a v-app

### Actual Behavior
The theme is not applied

### Reproduction Link
<a href="https://codepen.io/anon/pen/vwbRJB" target="_blank">https://codepen.io/anon/pen/vwbRJB</a>

### Other comments
I do not want to use the v-app because I'm using vuetify within another app and the v-app component is restrictive (Full height, flex-styling), I just use v-form and other vuetify fields to create a form, which work amazingly well, except for the theme that isn't applied

Another issue I found is some theme styles are applied non scoped, example: if you have links outside the v-app they will be styled according to the primary color, this is not desired behavior only the ones inside the v-app should be styled

If it's not possible to add styling without v-app, I would suggest adding a v-wrapper component that mostly does the same but without default styling (so no flex/full height) applied to the wrapper but still load the theming functionality (and add a scope for the a style, to either be inside a v-app or v-wrapper)

**Comment by KaelWD** [comment]
This has been changed in 2.0

**Comment by Tofandel** [comment]
Any release date planed for v2 ? Last time I tried to compile (alpha16) with npm there were less compilation errors within vuetify

**Comment by Tofandel** [comment]
Still there with beta.0

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @content($material-light)
   ^
      Invalid CSS after "    @content": expected "}", was "($material-light); "

      in /node_modules/vuetify/src/styles/tools/_theme.sass (line 3, column 5)

**Comment by KaelWD** [comment]
This was supposed to be mentioned in the release notes, let me add it real quick. You need to use `sass` instead of `node-sass`.

**Comment by Tofandel** [comment]
That did it, thanks :)

**Comment by Tofandel** [comment]
Okay so the theming without v-app is working great, there only the theme not scoped issue still

Is there an option to scope the vuetify-theme-stylesheet ?

Like 
```
export default new Vuetify({
    theme: {
        primary: '#1976D2',
        secondary: '#424242',
        accent: '#82B1FF',
        error: '#FF5252',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#FFC107'
    },
   'scope': '.my-vuetify'
})
```
To apply each theme line to only certain classes?

```
<style type="text/css" id="vuetify-theme-stylesheet">
.my-vuetify a { color: #1976d2; }
.my-vuetify .primary {
  background-color: #1976d2 !important;
  border-color: #1976d2 !important;
}
.my-vuetify .primary--text {
  color: #1976d2 !important;
  caret-color: #1976d2 !important;
}
...
</style>
```

It would allow you to have 2 vuetify instances on the same page with 2 different themes

**Comment by Tofandel** [comment]
Can we reopen this?

This was working in v2-beta and now with the v2-release the v-app is necessary again to have styling applied
