### ISSUE TITLE
[Feature Request] Click on a day in Calendar to perform an action

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [vuetifyjs/vuetify#7377]
### Problem to solve
Not being able to perform actions whenever clicking on a day

### Proposed solution
Emit an event when clicking on the div that wraps the entire day

**Comment by flpgst** [comment]
Maybe a good solution could be creating an append icon to each day on calendar.
And the event could be emmit by onClick at that icon.

**Comment by sh7dm** [comment]
@CharlieBrownCharacter you can use `click:day` event, it's what you need. If I'm wrong, I'll reopen this.
![image](https://user-images.githubusercontent.com/19504461/60954068-0970d980-a307-11e9-8152-95b49e56e0bb.png)

**Comment by CharlieBrownCharacter** [comment]
The problem with the `click:day` is that you need to click exactly on the number. This is highly unpractical to a user who is not familiar with vuetify calendar. Design should be simple and intuitive and, as a user  no way I would ever see that clicking on that little number would render me action x

**Comment by ClickerMonkey** [comment]
An event is emitted, `click:day`. When you click on the date's day of the month you get `click:date`.

If it's not behaving this way, please provide a codepen. You should see how the events work here:

https://codepen.io/anon/pen/rEPqBp
