### ISSUE TITLE
[Bug Report] Active tab class applied to multiple tabs when using named, nested routes

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#7382]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.3

### Steps to reproduce
Use named routes for the tabs component. Some of the routes should be nested inside another route.

I have styled the text green in the codepen demo to highlight the issue.

### Expected Behavior
Only one tab should be highlighted.

### Actual Behavior
Multiple tabs get the `.v-tabs__item--active` class. Although, the correct tab gets the bottom border highlight.

### Reproduction Link
<a href="https://codepen.io/gmattgreenfield/pen/rgPRwd" target="_blank">https://codepen.io/gmattgreenfield/pen/rgPRwd</a>

### Other comments
It could be related to https://github.com/vuetifyjs/vuetify/issues/3270

**Comment by KaelWD** [comment]
It's the same as `router-link`, use `exact` if you have nested routes.

**Comment by mattgreenfield** [comment]
Ah so it is. Thank you @KaelWD, sorry to waste your time.
