### ISSUE TITLE
[Bug Report] Data Table With Subcomponents

### ISSUE THREAD

**Issue by joldenb** [vuetifyjs/vuetify#7383]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create Data Table, add a subcomponent to one of the table columns, such as v-select, and all the rows get rendered as one long row.

### Expected Behavior
Expect different rows to be rendered properly.

### Actual Behavior
All the rows are smushed together into one long row.

### Reproduction Link
<a href="https://codepen.io/anon/pen/JqzPXW?editors=1011" target="_blank">https://codepen.io/anon/pen/JqzPXW?editors=1011</a>

**Comment by KaelWD** [comment]
The item slot does not render its own `<tr>`
