### ISSUE TITLE
[Bug Report] v-date-picker styling issue when inside of a v-data-table expansion area 

### ISSUE THREAD

**Issue by waspinator** [vuetifyjs/vuetify#7384]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Ubuntu undefined

### Steps to reproduce
place a `<v-date-picker>` element inside a `<template v-slot:expand="props">`

### Expected Behavior
The `v-date-picker` should retain its original style and function

### Actual Behavior
the `v-date-picker` appearance becomes distorted

### Reproduction Link
<a href="https://codepen.io/anon/pen/xNBGKE?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/xNBGKE?&editable=true&editors=101</a>

**Comment by Nyami** [comment]
I've recently encountered something similar and manged to resolve using CSS as a work around, see [updated codepen ](https://codepen.io/nyami/pen/RXpjqB) for CSS and behavior.

**Comment by jacekkarczmarczyk** [comment]
2.x: https://codepen.io/jkarczm/pen/abvEWxB?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdata-tables%2F

**Comment by jacekkarczmarczyk** [comment]
fixed in https://github.com/vuetifyjs/vuetify/pull/11325
