### ISSUE TITLE
[Bug Report] Button with :to keeps hover style

### ISSUE THREAD

**Issue by oscaroscar** [vuetifyjs/vuetify#7386]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
There are two buttons with :to attributes. Click the first one then the other then the first one. You'll notice the :hover style sticks to the buttons now. 

### Expected Behavior
:hover style should only be applied on mouse over :)

### Actual Behavior
:hover style sticks to the buttons when a :to is used

### Reproduction Link
<a href="https://codepen.io/oscarayoun/pen/XwGmPP" target="_blank">https://codepen.io/oscarayoun/pen/XwGmPP</a>

### Other comments
Bonus issue : for some reason I can also see that when using the :to attribute on buttons the actual icon is not centered anymore.

**Comment by KaelWD** [comment]
There's two things here:
 - [router-link active class](https://router.vuejs.org/api/#active-class)
 - Because it's an `<a>` it receives `:focus` when clicked

> icon is not centered

Icon font needs to be loaded above vuetify.css
