### ISSUE TITLE
[Feature Request] Types not proper for Vuetify 2.0

### ISSUE THREAD

**Issue by TerenceZ** [vuetifyjs/vuetify#7387]
### Problem to solve
Make Vuetify 2.0 work properly with Typescript and JSX.

### Proposed solution
When I use Vuetify 2.0 with Typescript and JSX (created by vue-cli), some types are not proper.

1. Vuetify 2.0 not handle options like lang, theme, etc., instead, it use new Vuetify(options) to handle them, but currently, the types are not correct, the default exported from vuetify isn't constructable through new.
2. All components are typed as Vue's Component, but vue-cli's generated types for JSX isn't. Instead, vue-cli's JSX component type is VueConstructor (aka, typeof Vue), it makes it's not possible to use vuetify with Typescript + JSX for project generated by vue-cli.

**Comment by TerenceZ** [comment]
Moreover, is it possible to export each component's prop types? So user can use it to work with some libraries, e.g., `vue-tsx-support`, to get the correct property type check in TSX / TS.

**Comment by vortechs2000** [comment]
I'm really confused - it looks like there are type definitions in the vuetify/types directory, but they don't appear to be used.  I am *not* a typescript expert though, so maybe I'm missing some critical information.

**Comment by vortechs2000** [comment]
I managed to get past the error (Cannot use 'new' with an expression whose type lacks a call or construct signature.) by hacking a 'new' definition into the types/index.d.ts:
```
export interface Vuetify {
  new (options: any): any;
  install: PluginFunction<VuetifyUseOptions>
  version: string
}
```

This probably isn't what you want long term, but it seems to be working for getting things up and running.

**Comment by Connect-a** [comment]
@vortechs2000 
Other makeshift solution:
`import Vuetify from 'vuetify';`
to
`const Vuetify = require('vuetify');`

**Comment by Lobosque** [comment]
None of the aforementioned solutions worked for me.
Any other suggestion to try testing the beta?

**Comment by PaulKujawa** [comment]
@Lobosque 
https://github.com/PaulKujawa/eventvuel-client/blob/master/src/plugins/vuetify.ts
https://github.com/PaulKujawa/eventvuel-client/blob/master/src/vue-shims.d.ts#L12

if you care about typings for colors you could add `/// <reference path="node_modules/vuetify/types/colors.d.ts" />` before your import. Colleague said they would have to add this line to their `types/index.d.ts` themselves.

**Comment by jacekkarczmarczyk** [comment]
@TerenceZ i've added PR for 1., could you please create a separate issue for 2.? Some reproduction could be also nice, could be a simplified github repo. Thanks
