### ISSUE TITLE
[Bug Report] Vuetify's iconfont option is not changable in codepen

### ISSUE THREAD

**Issue by lzhoucs** [vuetifyjs/vuetify#7388]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OS 10.14

### Steps to reproduce
Go to codepen link below, check page output

### Expected Behavior
Output `mdi-menu-down`

### Actual Behavior
Output `arrow_drop_down`

### Reproduction Link
https://codepen.io/lzhoucs/pen/arMWEW

**Comment by KaelWD** [comment]
You have to set `Vue.prototype.$vuetify` in 1.x

**Comment by lzhoucs** [comment]
@KaelWD could you please be more specific?
I just tried the following but it doesn't seem to work:
```
Vue.prototype.$vuetify.iconfont = "mdi"
```

**Comment by jacekkarczmarczyk** [comment]
You need to add mdi css

**Comment by KaelWD** [comment]
Looks like the iconfont option is only available at initialisation. This was all tacked on to the existing system and will not be changed in 1.x

**Comment by lzhoucs** [comment]
@jacekkarczmarczyk thanks, however I don't think that is the right approach - override each icon if you look at the [docs](https://vuetifyjs.com/en/framework/icons#usage). Those are internally defined for each font icon libraries and all we should do to switch is change `iconfont`

I am aware of missing mdi css, however it is not related to the issue I am reporting as vuetify should behave the same with or without the mdi css in my case.

@KaelWD just to confirm, so this is a legit issue, and setting `Vue.prototype.$vuetify` is not an option. Although it is not going to be fixed in 1.x, right?

**Comment by KaelWD** [comment]
It's a legit issue, but

- we don't really care about the cdn build that much (sorry)
- that whole thing has already been rewritten for 2.0
- there is a workaround which is to set the entire `$vuetify.icons` object, you can copy the one you want from source
