### ISSUE TITLE
[Bug Report] Data Table Footers do no align with columns

### ISSUE THREAD

**Issue by nevaan9** [vuetifyjs/vuetify#7391]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
See codepen example. The footers do not align with the columns.

### Expected Behavior
https://codepen.io/nevaan9/pen/Loaqxy?&editable=true&editors=101

### Actual Behavior
The footers are squashed on to the left side

### Reproduction Link
<a href="https://codepen.io/nevaan9/pen/MdxyaW?&editable=true&editors=101" target="_blank">https://codepen.io/nevaan9/pen/MdxyaW?&editable=true&editors=101</a>

### Other comments
Hoping this could work even with custom passed in template items for the body

**Comment by nekosaur** [comment]
The footer is located outside of the actual table in the markup. Use slot `body.append` instead.
