### ISSUE TITLE
[Feature Request] Hide Text Input Counter when field does not have focus

### ISSUE THREAD

**Issue by blakenorman37** [vuetifyjs/vuetify#7392]
### Problem to solve
Removing the clutter of the screen when the page has many text fields. The counter does not add value to the user when they are not using the text field.

### Proposed solution
Add the ability to auto-hide the counter when the text field does not have focus, similar to how the hint text currently works.

**Comment by johnleider** [comment]
in v3 the counter is now hidden by default and can be enabled by using **persistent-counter**.

**Comment by ashunimh** [comment]
how can i hide counter from text field but show hint?
