### ISSUE TITLE
[Feature Request] describe how v-tooltip renders a slot outside the wrapper

### ISSUE THREAD

**Issue by alloself** [vuetifyjs/vuetify#7395]
### Problem to solve

understanding of the framework work, i try asked it in discord ,but got no answer

### Proposed solution
make a description of nontrivial work

**Comment by jacekkarczmarczyk** [comment]
You need to dig into the sources
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/detachable.js#L83
