### ISSUE TITLE
[Bug Report] [VListGroup] expand is not working when use vue-router

### ISSUE THREAD

**Issue by kyoungwoon-ko** [vuetifyjs/vuetify#7399]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
**in example codepen**

1. click menu "b"
2. click "/b/a"
3. click "/b/b"
3. click "/b/a" 

### Expected Behavior
always expanded "b"

### Actual Behavior
when step 2 and 4, expanded "a" then expanded "b"

### Reproduction Link
<a href="https://codepen.io/armadillo-dev167/pen/pmBPOo?editors=1010" target="_blank">https://codepen.io/armadillo-dev167/pen/pmBPOo?editors=1010</a>

### Other comments
**in VListGroup.vue** use blow for isActive

```js
matchRoute (to: string) {
  if (!this.group) return false
  return to.match(this.group) !== null
}
```

But `String.property.match` check only contain some string

**Comment by johnleider** [comment]
At the moment this is the intended functionality of `v-list-group` to require a group prop for determining if its children are active.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
