### ISSUE TITLE
<v-navbar-item> linking to router's named view

### ISSUE THREAD

**Issue by pipejesus** [vuetifyjs/vuetify#74]
When i'm using `<router-link>` from 'vue-router' like that:

```
<router-link :to="{name: 'namedview'}">
Some View
</router-link>
```

I can specify the route by its name and add parameters. Can it be done using `<v-navbar-item>` ? 

I found 'router' parameter down on the docs page but i don't know how to use it.

Thanks!

**Comment by pipejesus** [comment]
Ok so i experimented and found out that i can write this (which almost works):

`<v-navbar-item v-bind:item="{ text: 'add', icon: true, router:true, href:{name:'streamnew'}}"></v-navbar-item>`

And when i click on the button it takes me to the named view but i also get this error in the console:

`Uncaught TypeError: _vm.click is not a function`

Can somebody tell me why?

**Comment by johnleider** [comment]
This is currently a bug with navbar item being used as a route. Was fixed with https://github.com/vuetifyjs/vuetify/issues/65.
