### ISSUE TITLE
chip with avatar inside list

### ISSUE THREAD

**Issue by elbarto132** [vuetifyjs/vuetify#740]
If you put a chip with an avatar inside a list the size of the chip's avatar is distorted, because the min-width here:
```
.chip .avatar {
  border-radius: 50%;
  height: 32px;
  width: 32px;
  min-width: 32px;
  margin-left: -14px;
  margin-right: 8px;
  color: #fff;
}
```
is being overwritten by this:
```
.list__tile .avatar, .list__tile__action {
  -webkit-box-pack: start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  min-width: 56px;
}
```
changing ".list__tile .avatar" to ".list__tile__avatar" probably fixes this, but i don't know if this has any side effects somewhere else.
So as a work around for now i put this in my component
```
    .list__tile__sub-title
        .avatar
            min-width: 32px
```

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
