### ISSUE TITLE
[Bug Report] (VToolbar) wrapping an v-btn in an extra div messes up the styling

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#7400]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Wrap a `v-btn` in an additional div within a `v-toolbar`

### Expected Behavior
`v-btn` displays with the correct styling

### Actual Behavior
`v-btn` displays as a smaller btn and there is no way of manually fixing it through a prop, since `<v-btn large>` causes the ripple/btn to be too big

### Reproduction Link
<a href="https://codepen.io/anon/pen/RmvOOj?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/RmvOOj?&editable=true&editors=101</a>

### Comments
This is especially usefull when you are splitting your buttons into seperate components

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/58943502-12bbd300-87aa-11e9-92df-a11bcd9d7868.png)
