### ISSUE TITLE
[Bug Report] When choosing year for date picker with an initial value of 9999 for the year results in an 'invalid time' error

### ISSUE THREAD

**Issue by SanBen** [vuetifyjs/vuetify#7401]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
* Use picker and set value to the year 9999
* Go to year selection
* Error

### Expected Behavior
* Either handle edge-case gracefully
* Support years up till 9999

### Actual Behavior
invalid time exception, component is unusable afterwards

### Reproduction Link
<a href="https://jsfiddle.net/1t4mxvjr/" target="_blank">https://jsfiddle.net/1t4mxvjr/</a>

**Comment by jacekkarczmarczyk** [comment]
So we've a got a Y10K problem

![image](https://user-images.githubusercontent.com/15625235/58946301-c378a100-87af-11e9-8aa0-4f6e909c3592.png)

I'd say it's a no fix, unless your example is a real world example and not just testing edge cases

**Comment by KaelWD** [comment]
It works without the time, in chrome at least
![image](https://user-images.githubusercontent.com/16421948/58947235-dd73ad00-87ca-11e9-8763-30f727a5bd56.png)

Firefox doesn't like either. 

ISO says 5 digit years should be prefixed with +/- for CE/BCE, but that doesn't seem to make a difference.

**Comment by KaelWD** [comment]
6 digit year with `+` works in both browsers
![image](https://user-images.githubusercontent.com/16421948/58947643-a94cbc00-87cb-11e9-8665-ec6573a12603.png)

**Comment by jacekkarczmarczyk** [comment]
Not sure if there is no problem on MacOS/ios if we skip the time.
It's a pity that in 2019 there is not built in support for operating just on pure dates, not only in JS...

**Comment by jacekkarczmarczyk** [comment]
Should be easy fix
![image](https://user-images.githubusercontent.com/15625235/58948539-8b279180-87b4-11e9-8b18-5dae125dba79.png)

**Comment by KaelWD** [comment]
Yeah that already works, the problem is converting it back to a string. Maybe the date should be stored as a tuple internally so you can do `new Date(...dateTuple)`

**Comment by jacekkarczmarczyk** [comment]
@nekosaur  any thoughts as you're doing now date-time refactor?

**Comment by SanBen** [comment]
> 
> 
> So we've a got a Y10K problem
> 
> ![image](https://user-images.githubusercontent.com/15625235/58946301-c378a100-87af-11e9-8aa0-4f6e909c3592.png)
> 
> I'd say it's a no fix, unless your example is a real world example and not just testing edge cases

Unfortunately it is a real use case, we are renewing a legacy codebase and are migrating the old data.
The previous developers used the date '9999-31-12' for certain cases 💥 

I have fixed my specific problem by just clamping the value for now, so this is not urgent...
I thought making an issue for it might help others as well.

**Comment by jacekkarczmarczyk** [comment]
@SanBen https://codepen.io/anon/pen/rgbQwm

**Comment by jacekkarczmarczyk** [comment]
Also if you want to go to year selection change it to the current year then you'll still face the problem https://github.com/vuetifyjs/vuetify/issues/7193

**Comment by nakhoa2111** [comment]
I suddenly fix this issue by just add attribute `max="9999-12-31"` in v-date-picker. Hope this will fix your issue also

`<v-date-picker
    no-title
    scrollable
    :picker-date.sync="item.startDate"
    :value="item.startDate"
    max="9999-12-31"
    @input="
      ($event) => {
        item.startDate = $event;
        item.startDateFormated = formatDateString($event);
      }
    "
    @change="validateRegionPublishDate(index)"
/>`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
