### ISSUE TITLE
[Docs] DataTable: missing props for item scoped slot

### ISSUE THREAD

**Issue by ndabAP** [vuetifyjs/vuetify#7403]
### Problem to solve
This is about the beta v2.0.0-beta.1. 

At the moment, it is not possible to let a table row become a clickable route and have select boxes at the same time because there is no way to native way to get the checked status of a specific row.

My old setup was like this:

```vue
<template
    slot="items"
    slot-scope="props">
        <tr
	:active="props.selected"
	class="pointer"
	@click="to('/somewhere')">
	    <td>
	        <v-checkbox
	        :input-value="props.selected"
	        primary
	        hide-details
	        @click.stop="props.selected = !props.selected"/>
	    </td>
	    <td>{{ props.item.name }}</td>
	    <td>{{ props.item.description }}</td>
	</tr>
</template>
```

### Proposed solution
Add the props from `header.data-table-select` to the `body` prop so one can simulate a route via row clicks.

**Comment by nekosaur** [comment]
I'm not sure exactly what you are missing? You can do this

```vue
<template v-slot:item="{ item, select }">
  <tr
    :active="select.props.value"
    class="pointer"
    @click="to('/somewhere')"
  >
    <td>
      <v-checkbox
	        :input-value="select.props.value
	        primary
	        hide-details
	        @click.stop="select.on.input"/>
    </td>
    <td>{{ item.name }}</td>
    <td>{{ item.description }}</td>
  </tr>
</template>
```

**Comment by ndabAP** [comment]
Hey @nekosaur, thanks for your feedback.

The documentation doesn't include this:

```
{ items: any[]", "pagination": { page: number", itemsPerPage: number", pageStart: number", pageStop: number", pageCount: number", itemsLength: number" }, "options": { page: number", itemsPerPage: number", sortBy: string[]", sortDesc: boolean[]", groupBy: string[]", groupDesc: boolean[]", multiSort: boolean", mustSort: boolean" }, updateOptions: (obj: any): void", sort: (value: string): void", group: (value: string): void", groupedItems: Record<string, any[]>" }
```

**Comment by nekosaur** [comment]
oh, right. you're using the click handler. so you'd do `@click.stop="select.on.input(!select.props.value)"`

https://codepen.io/anon/pen/rggNKz?editors=1010

yeah, documentation for slot props is probably not 100% yet. it's something we unfortunately can't autogenerate yet.

**Comment by ndabAP** [comment]
Thank you for the clarification!

**Comment by nekosaur** [comment]
Documentation has been updated

**Comment by josephgunawan97** [comment]
Hello, 

Have been trying to use this solution for vuetify 2.2.14 but came up with 'value' undefined

https://codepen.io/josephgunawan/pen/KKpajYe

Did i do something wrong? Need some solution. Thank you
