### ISSUE TITLE
[Feature Request] Incorrect documentation for tabs

### ISSUE THREAD

**Issue by theblindprophet** [vuetifyjs/vuetify#7405]
### Problem to solve
The documentation for the "change" event on the Tabs component is incorrect/confusing. It states:

"Emitted when tab is changed by user interaction" | string

https://vuetifyjs.com/en/components/tabs

![tabs-change](https://user-images.githubusercontent.com/7903413/58960447-34e72e00-8775-11e9-9b2d-3f6907f8a9e4.PNG)

### Proposed solution
It should say something similar to:

"Index of active tab emitted when tab is changed by user interaction" | number

**Comment by jacekkarczmarczyk** [comment]
It's the description of the event, not the value. The description of the value should be added instead of replacing the description of the event
