### ISSUE TITLE
[Feature Request] VBtn (FAB) and VBottomNavigation interaction missing padding

### ISSUE THREAD

**Issue by jvanst** [vuetifyjs/vuetify#7407]
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
- Create a bottom fixed floating action button
- Create a bottom navigation component with 'app' attribute

### Expected Behavior
I expect that the FAB will be automatically pushed above the bottom navigation so it remains visible.

### Actual Behavior
The FAB is hidden behind the bottom drawer. 

### Reproduction Link
<a href="https://codepen.io/jvanst/pen/MdRKeX" target="_blank">https://codepen.io/jvanst/pen/MdRKeX</a>

### Other comments
I believe this interaction has existed since 1.0. I _might_ have time to open a PR for this one.

**Comment by johnleider** [comment]
This is something that has never been in the framework. I completely agree that it should be, but it has quite a few use-cases. In light of this, the plan was to abstract fab into its own component and extend btn as to not further bloat its functionality. Something we can look at for a future release.
