### ISSUE TITLE
[Feature Request] Vuetify documentation does not contain information on slot options for v-img

### ISSUE THREAD

**Issue by nccurry** [vuetifyjs/vuetify#7409]
### Problem to solve
Educates developers on options for v-img slots

### Proposed solution
Document the API for v-img slots

**Comment by nccurry** [comment]
Looking at VImg.ts it appears there is a single slot for v-img ```v-slot:placeholder```.

**Comment by MajesticPotatoe** [comment]
This will be handled as a part of a larger upgrade to the API system.
<https://github.com/vuetifyjs/vuetify/issues/7047>

**Comment by nccurry** [comment]
Awesome thanks!
