### ISSUE TITLE
Feature Request: Lazy Validation

### ISSUE THREAD

**Issue by jijoel** [vuetifyjs/vuetify#741]
I would love to have the option to validate text inputs when the user has left a field, instead of when the user has changed data in a field. I created a codepen showing a current work-around at https://codepen.io/jijoel/pen/QgNyvJ

Ideally, I'd like to present users with a happy path, where they don't see an error message unless there's something actually wrong with their input. An email field, for instance, will not pass validation until the '@' symbol is entered, but I'd really rather not tell them that when they enter the first letter of their address.

When errors pop up everywhere during regular use, it tends to condition people to ignore them, which I'd rather not do.  :-)

**Comment by johnleider** [comment]
You might have to bug Evan You about putting back the ability for devs to hook into v-model modifiers. He removed it in 2.2.

**Comment by johnleider** [comment]
As this is something not currently possible within Vue, I'm going to close it until Evan adds it back.

**Comment by senid231** [comment]
already implemented as `validate-on-blur` prop for `v-text-field` component
