### ISSUE TITLE
[Bug Report] VDataTable header - Mismatching childNodes vs. VNodes

### ISSUE THREAD

**Issue by csheppard** [vuetifyjs/vuetify#7410]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.13.6

### Steps to reproduce
`yarn dev`

View http://localhost:3000/datatable via SSR. 

### Expected Behavior
`<thead>` should contain 6 `<th>`

### Actual Behavior
`<thead>` has 1 `<th colspan="6">` with combobox for mobile. You see this flash before the browser is then able to build the 6 `<th>`.  

Console errors:
```
vendors.app.js:214 warn Parent:  <th colspan=​"6">​…​</th>​<div class=​"v-data-table-header-mobile__wrapper">​…​</div>​</th>​

vendors.app.js:214 warn Mismatching childNodes vs. VNodes:  NodeList [div.v-data-table-header-mobile__wrapper]0: div.v-data-table-header-mobile__wrapperlength: 1__proto__: NodeList [VNode]

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

### Reproduction Link
<a href="https://github.com/csheppard/nuxt-vuetify-2" target="_blank">https://github.com/csheppard/nuxt-vuetify-2</a>

**Comment by chanlito** [comment]
I'm facing same issue here.

**Comment by paulhobbel** [comment]
The datatable also defaults to the mobile view for me in SSR also resulting in a mismatch

**Comment by erickarbe** [comment]
Any updates on this? My app is breaking because of this bug.

**Comment by paulhobbel** [comment]
For now I have surrounded the vdatatable with `<nossr>`

**Comment by 0biWanKenobi** [comment]
I resorted to coding headers and body manually, since both are bugged. Not ideal, not sure if ssr would be better - certainly faster to code! - but.. any ETA on this? Thanks :)

**Comment by lechim** [comment]
I seem to still get this bug with SSR on a brand new project running Nuxt v2.12.2 and Vuetify v2.3.0. 

The server renders in mobile view and then I get this same error on desktop. The SSR works for mobile but on larger screens still have the error: "Mismatching childNodes vs. VNodes: Nodelist [div.v-data-table-header-mobile__wrapper]...". 

I just wrapped the v-data-table in <client-only></client-only> for the time being.

**Comment by tvld** [comment]
Same here...

**Comment by KaelWD** [comment]
This was broken again by 5533b030a3f892abed057dbb00946d57352e6751

The original fix wasn't great anyway, it just meant a mismatch on mobile instead.

**Comment by ARMGAMES** [comment]
Same here. <client-only> is working, but it's not a option.

**Comment by ryan-cahill** [comment]
Within a universal Nuxt app, I attempted to upgrade Vuetify from 2.2.x to 2.3.8 and the issue of the data table initially rendering as the mobile view persists. Using `<client-only>` tags isn't an option for us either

**Comment by tjhiggins** [comment]
Is there a way to dynamically set the breakpoint for ssr? I'd rather take an educated guess via https://www.npmjs.com/package/nuxt-user-agent then have a bunch of spinners client-side.

**Comment by phips28** [comment]
Facing the same problem. SSR renders this dropdown select for sorting. How can I disable this?

![image](https://user-images.githubusercontent.com/3694800/99365146-2e8c3980-28b7-11eb-8510-1afc602de945.png)

**Comment by udisun** [comment]
Still an issue for me too on a fresh nuxt v2.15.0 and vuetify v2.4.4

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
