### ISSUE TITLE
[Bug Report] datatable header dividers transparent

### ISSUE THREAD

**Issue by kylejoeckel** [vuetifyjs/vuetify#7411]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
add divider: true to header object with datatable
fixed headers

### Expected Behavior
should be solid color similar to those in table

### Actual Behavior
they are transparent and you can see the table pass by underneath as your scrolling

### Reproduction Link
<a href="https://codepen.io/kylejoeckel/pen/joorXM?editors=0010" target="_blank">https://codepen.io/kylejoeckel/pen/joorXM?editors=0010</a>

### Other comments
i could not get the dividers to show at all in the code pen, you'll have to take my word for it.

**Comment by jacekkarczmarczyk** [comment]
Issues says about Vuetify 2.0 but reproduction uses 1.5, please update the pen so that is shows the actual problem

**Comment by kylejoeckel** [comment]
Ok i was hoping this was fixed in beta.2 but it hasn't been. I cant find a cdn for beta... the highest ive found is alpha.20. Ive updated to alpha.20 but the issue is not present. where can i get a beta cdn?

**Comment by kylejoeckel** [comment]
![opaqueborders](https://user-images.githubusercontent.com/35591687/59301686-69645980-8c4f-11e9-827f-362fdc7fc4ae.PNG)

**Comment by kylejoeckel** [comment]
![lightmode opaqueborders](https://user-images.githubusercontent.com/35591687/59301861-d1b33b00-8c4f-11e9-8a8a-fc1a812c0db7.PNG)

**Comment by kylejoeckel** [comment]
<v-data-table dense mobile-breakpoint="0" disable-sort disable-pagination disable-filtering :headers="headernames" :items="tabledata"
        hide-default-footer hide-default-header fixed-header item-key="id"
        height="76vh" class="elevation-0" :loading="loading">
        <template v-slot:header="{ props: { headers } }">
          <thead style="background-color: #4d4d4d; ">
            <tr>
              <th v-for="(header, i) in headers" :key="i">
                <column-filter v-if="options[i].filter || options[i].choices" :header="header.text" :table="page_name"
                  :filters="pagination.search" :value="header.rval" :opts="options[i]" :hidden="is_hidden(header.text)"
                  @set="set_settings" />
                <span v-else>{{header.label}}</span>
              </th>
            </tr>
          </thead>
        </template>
</v-data-table>

**Comment by kylejoeckel** [comment]
As you can see in the screen shots the row boarders underneath the header are able to be seen through the header dividers. in light mode you see what appears to be a black background when scrolled all the way to the top. this is the code i am using for the template.

**Comment by kylejoeckel** [comment]
ive managed to get the code pen linked above to duplicate the problem

**Comment by jacekkarczmarczyk** [comment]
I can see an issue when i hover the first displayed row

![image](https://user-images.githubusercontent.com/15625235/59705354-6ad1eb00-9228-11e9-895e-fbbd4e035c8c.png)

But can't reproduce the issue from your screenshots

**Comment by kylejoeckel** [comment]
the issue in the screen shot is the issue that I'm attempting to report, the dividers are transparent. weather you hover over the first row or not you can see through the dividers.
