### ISSUE TITLE
[Feature Request] v-date-picker initial date view option

### ISSUE THREAD

**Issue by waspinator** [vuetifyjs/vuetify#7413]
### Problem to solve
allows for the date picker to display an initial month or year other than the current one, while still retaining the ability to navigate to other months or years. Currently `picker-date`  prevents navigation. 

````
<v-date-picker picker-date="2019-01-01"></v-date-picker>
```

### Proposed solution
add a `goToDate(date)` function to change the display date to a specific month/year, or a prop 

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by KaelWD** [comment]
It's a syncable prop: https://codepen.io/anon/pen/joomQR
