### ISSUE TITLE
[Feature Request] Unify icon syntax when using custom components to render the icons

### ISSUE THREAD

**Issue by arbesulo** [vuetifyjs/vuetify#7415]
### Problem to solve

Versions:
  - vue 2.6.10
  - Vuetify 1.5.14

When using custom components to render icons, the used syntax can lead to different results:

Having instructed Vuetify to use a custom icon:

```javascript
Vue.use(Vuetify, {
  icons: {
    'share': {
      component: IconComponent
    }
  }
})
```

Using

```javascript 
<v-icon v-text="'$vuetify.icons.share'"></v-icon>
```
will use my IconComponent as expected, but using

```javascript
<v-icon>share</v-icon>
```
will render the default share icon from the iconfont.

After seeing this behaviour, I thought that using `<v-icon v-text="'$vuetify.icons.[icon-name]'"></v-icon>` would always behave the same, but I have seen that `$vuetify.icons` only defines 27 icons. So for all other icon names it will render trash.

### Proposed solution
Unify the syntax so that in all cases it behaves the same

**Comment by jacekkarczmarczyk** [comment]
`<v-icon>whatever</v-icon>` will render icon `whatever` from the icon font, `<v-icon>$vuetify.icons.whatever</v-icon>` will render the icon you defined as `whatever` in the configuration. If you define it as `whatever` then `$vuetify.icons.whatever` will render `whatever` icon, but you can define it to render different icon so we can't make `$vuetify.icons.whatever` to render `whatever` icon

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
