### ISSUE TITLE
[Bug Report] Autocomplete/Combobox loses correct focus on pressing tab after clicking on value

### ISSUE THREAD

**Issue by Vuetifiyer** [vuetifyjs/vuetify#7416]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Chose any value in the second or third Combobox by clicking on it (do not chose the value by keyboard!)

2. After selecting it, press "tab" on the keyboard.

### Expected Behavior
By pressing tab, the field-focus should change to the next field. 

### Actual Behavior
The field-focus always returns to the first field of the application.

### Reproduction Link
<a href="https://codepen.io/anon/pen/rggKYX?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/rggKYX?&editable=true&editors=101</a>

### Other comments
If the value is instead selected by keyboard and pressing "Enter" there seems to be a different event, as pressing Tab enters the next field correctly.

Note: The example in codepen.io does also have the issue, but it can be reproduces with any Combobox/Autocomplete. It actually is better visible if it's being triggered at https://vuetifyjs.com/en/components/combobox (simply use the first Comobox here with the "Programming" as text, then the focus will change to the "Become a Sponsor"-Button after pressing tab)

**Comment by johnleider** [comment]
This is resolved as of v2.
