### ISSUE TITLE
[Bug Report] Data Table slot progress ignored / not working

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#7417]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Ubuntu undefined

### Steps to reproduce
Open the codepen and watch the progress bar: it's the standard VDataTable one, i.e. indeterminate

### Expected Behavior
I would expect the progress bar to be the one in the slot and not the standard, indeterminate one

### Actual Behavior
the progress in the slot seems to be ignored

### Reproduction Link
<a href="https://codepen.io/lucafaggianelli/pen/VOOEdp?&editable=true&editors=101" target="_blank">https://codepen.io/lucafaggianelli/pen/VOOEdp?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
You are using the new slot syntax incorrectly https://codepen.io/anon/pen/dEEwex

The only time you can put `v-slot` on anything other than `<template>` is when you are _only_ using the default slot.

**Comment by lucafaggianelli** [comment]
thanks @nekosaur ! I suggest to update the docs as the erroneous codepen was taken from there
https://vuetifyjs.com/en/components/data-tables#slot-progress

Luca

**Comment by psychosis448** [comment]
> You are using the new slot syntax incorrectly https://codepen.io/anon/pen/dEEwex
> 
> The only time you can put `v-slot` on anything other than `<template>` is when you are _only_ using the default slot.

Didn't know about that either. Glad I found the solution here, was about to open another issue. :)

**Comment by MajesticPotatoe** [comment]
updated in #7650
