### ISSUE TITLE
[Bug Report] Slot appended items to select menu not selecting like normal item

### ISSUE THREAD

**Issue by 12s** [vuetifyjs/vuetify#7418]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. open menu in fiddle. 
2. Click on 'four', the appended item

### Expected Behavior
Select menu should close and behave like other items

### Actual Behavior
Nothing happens, menu stays open

### Reproduction Link
<a href="https://jsfiddle.net/2ku5a6f4/" target="_blank">https://jsfiddle.net/2ku5a6f4/</a>

**Comment by KaelWD** [comment]
`:menu-props="{ closeOnContentClick: true }"`
