### ISSUE TITLE
[Feature Request] Treeview: Event on selection

### ISSUE THREAD

**Issue by BotellaA** [vuetifyjs/vuetify#7419]
### Problem to solve
I would like to bind an action each time an item is selected or unselected. The goal is to directly use the selected item. 

### Proposed solution
I do not know...

**Comment by nekosaur** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
