### ISSUE TITLE
Controls dialog visibility from v-model

### ISSUE THREAD

**Issue by Kraigo** [vuetifyjs/vuetify#742]
### Versions
Vue 2.3.4
Vuetify 0.12.7

### What is actually happening ?
Can't control dialog visibility after changing v-model of dialog.

If I control Dialog visibility from activator - all is ok.
But if I need to change visibility from component - dialog appear on half second and hides. Only show backdrop and can't close

### Reproduction Link
https://codepen.io/Kraigo/pen/PjNNyY

**Comment by johnleider** [comment]
Please make sure to read the documentation. It talks in numerous places about using your own methods that involve clicking an element. You need to add .stop to the @click handler.
