### ISSUE TITLE
[Bug Report] Unable to change button colors and sizes in VBtnToggle

### ISSUE THREAD

**Issue by Mintonne** [vuetifyjs/vuetify#7420]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Create VBtnToggle in 2.0 & 1.5

Attempt to modify button color and sizes using VBtn props.

### Expected Behavior
https://codepen.io/anon/pen/joRrGM

### Actual Behavior
https://codepen.io/anon/pen/VONjmE

### Reproduction Link
<a href="https://codepen.io/anon/pen/VONjmE" target="_blank">https://codepen.io/anon/pen/VONjmE</a>

**Comment by KaelWD** [comment]
Specificity too high on these rules
![image](https://user-images.githubusercontent.com/16421948/59086622-9958e780-8945-11e9-808d-589100fe6a89.png)
