### ISSUE TITLE
[Bug Report] Cannot bind events to VCardText

### ISSUE THREAD

**Issue by Pazza** [vuetifyjs/vuetify#7421]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Bind event (click, scroll, etc) to <v-card-text> and try to trigger said event.

### Expected Behavior
Even should be set. According to Chrome Debug, the element does not have the event registered.

### Actual Behavior
event is not bound to element

### Reproduction Link
<a href="https://codepen.io/pazza/pen/EzMYBo" target="_blank">https://codepen.io/pazza/pen/EzMYBo</a>

**Comment by jacekkarczmarczyk** [comment]
`scroll.native`

Not sure if we want to pass $listeners in all components

**Comment by Pazza** [comment]
Thanks @jacekkarczmarczyk. I figured it was a bug since $listeners is passed to VCardTitle.

The workaround is sufficient for me, although might not be clear to others.

**Comment by jacekkarczmarczyk** [comment]
That's why i've left the issue open...

**Comment by KaelWD** [comment]
#6788

VCardText was previously using createSimpleFunctional, now it's a very naive functional component that doesn't inherit any user defined attributes or events for some reason.
