### ISSUE TITLE
[Feature Request] Ability to fix tabs in nested routes

### ISSUE THREAD

**Issue by MartinMuzatko** [vuetifyjs/vuetify#7426]
### Problem to solve
Hello!

The problem I am facing right now, is that `v-tabs` has to be within a `v-toolbar` with the property "fixed" in order to be at the correct position on the top nested to the right of my sidebar (navigation-drawer).

However, my toolbar is dependent on nested child routes that also define their own tabs on the top.

![](https://i.imgur.com/Za56ucr.png)

The restriction right now, is to use the `v-tabs` component outside of `v-content` - ok I can move the `v-content` element to within the router-view, but then how will I do with the nested router view?

### Proposed solution
The tabs component should be able to be placed within a `v-content` element.
I'd like to avoid to globally defining these tabs and tabs children, to make the pages extend it as needed.

I think the properties "app" and "fixed" are not enough to tell the components where they belong efficiently.
In this case, the app is not able to find out if it should belong to the right or left part of the page.
A similar system like quasar has,  (https://quasar.dev/layout-builder) that can define where different parts of the page belong to, would be nice. But maybe this can be done with properties only, even if the items are nested. 
Since the menus are aligned with paddings, that are partially found out automatically based on  element placement and `app` and `fixed` property.

For stacked tabs from different nested routes (parent and child) I would need to be able to define their position without having them in the same element.

**Comment by KaelWD** [comment]
> The tabs component should be able to be placed within a v-content element.

It can be

> like quasar has

That looks like you need an even more specific structure to work correctly?

You can also use [named views](https://router.vuejs.org/guide/essentials/named-views.html#named-views) for the navigation.

**Comment by MartinMuzatko** [comment]
With named views I do not have the possibility to extend a view. And when I have nested pages then this approach does not work.
Then I'd need to define a top for every v-tabs I add.

**Comment by johnleider** [comment]
I'm really not sure what we can solve with this. There are quite a few ways that this issue could be approached and I believe it should be left in userland.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
