### ISSUE TITLE
[Bug Report] Invalid aria role for VIcon when using svg

### ISSUE THREAD

**Issue by kevinmarrec** [vuetifyjs/vuetify#7428]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
IMPORTANT : The Reproduction link (codepen) only showcase that the svg tag has an invalid `role` attribute value. Here is how I found the issue & reproduction in production :

Go to https://marrec.io with Google Chrome
Run Audits (Lighthouse)

Check for the **Accessibility -> ARIA** section

### Expected Behavior
No issues

### Actual Behavior
![Screenshot from 2019-06-07 12-37-35](https://user-images.githubusercontent.com/25272043/59098670-36555980-8921-11e9-9859-8bc0a7136b4f.png)

### Addition Comments

Seems that https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VIcon/VIcon.ts#L137 can be removed, as the ARIA is handled around the VIcon or VBtn.

`icon` is not a valid value for `role`.

### Reproduction Link
<a href="https://codepen.io/anon/pen/jojQYg" target="_blank">https://codepen.io/anon/pen/jojQYg</a>

**Comment by sh7dm** [comment]
Fixed in 1866aca
