### ISSUE TITLE
[Bug Report] Form reset should set value to null

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#7429]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
Press "Reset" button

### Expected Behavior
Resetting form should set input value to null (according to docs) 

### Actual Behavior
Resetting form set input value to undefined

### Reproduction Link
<a href="https://codepen.io/anon/pen/zQVmob?editors=1010#0" target="_blank">https://codepen.io/anon/pen/zQVmob?editors=1010#0</a>

**Comment by KaelWD** [comment]
`reset()` uses `null`: https://github.com/vuetifyjs/vuetify/blob/4cc8b8c4e1e4cfbac1751da132daa4a69311e0a1/packages/vuetify/src/mixins/validatable.ts#L205

`click:clear` uses `undefined`: https://github.com/vuetifyjs/vuetify/blob/9b354fd9aa9c5a15ec9b23c80dad677bb6430820/packages/vuetify/src/components/VTextField/VTextField.js#L210

See also #4144 and #2752

**Comment by Djaler** [comment]
![image](https://user-images.githubusercontent.com/7964583/59158623-79503200-8ac5-11e9-80f8-dd83d765f5b8.png)

**Comment by Djaler** [comment]
@KaelWD so what about it? ^

**Comment by Djaler** [comment]
@KaelWD so what about it? ^

**Comment by Djaler** [comment]
This is still relevant

**Comment by Djaler** [comment]
With current behaviour it is really ugly to use data with typescript, cause you should consider both undefined and null in type definition

**Comment by Djaler** [comment]
Is anybody here?

**Comment by arcreative** [comment]
@KaelWD So is that the end of it? Why were these both closed as duplicates of each other without explanation?

**Comment by arcreative** [comment]
@KaelWD nevermind, I see #12373 now, thanks :-)
