### ISSUE TITLE
Function preventing closing of dialog

### ISSUE THREAD

**Issue by codaha** [vuetifyjs/vuetify#743]
There shoudl be some kind of function preventing closing dialog from closing when clicking outside - under some kind of conditons of course. 

For example, dont close when fields inside dialog are not validated correctly.

Vue element have dialog with before-close function
http://element.eleme.io/#/en-US/component/dialog

**Comment by johnleider** [comment]
Does example 2 not show this functionality?

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by mendiomon** [comment]
No, it didnt. In example nr. 2 closing by clicking autside is just disabled.

What i mean is giving developr ability do decide what happens when clicked outside dependimng of some conditions.

**Comment by johnleider** [comment]
Well you could just conditionally trigger that prop based upon your form validation logic.
