### ISSUE TITLE
[Bug Report] Text field within expansion panel will not focus (using autofocus)

### ISSUE THREAD

**Issue by escapedcat** [vuetifyjs/vuetify#7430]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Open pen

### Expected Behavior
Text field is focused after expansion panel is loaded

### Actual Behavior
Text field is not focused after expansion panel is loaded

### Reproduction Link
<a href="https://codepen.io/escapedcat/pen/WBqWrQ" target="_blank">https://codepen.io/escapedcat/pen/WBqWrQ</a>

### Other comments
Not sure if this is even possible due to how expansion panels might work. I guess they are closed initially so the page doesn't know there's an input field that needs to be focused. Would be great if this would work though.

**Comment by johnleider** [comment]
This has been resolved as of v2.
