### ISSUE TITLE
VuetifyLocale API?

### ISSUE THREAD

**Issue by longrunningprocess** [vuetifyjs/vuetify#7431]
### Problem to solve
I can't quite figure out how to utilize fallbacks for translations or what options are available.

### Proposed solution
I'd like to see some additional docs on how to utilize fallbacks.  Maybe someone was already planning to do this here? (https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/lang.d.ts#L7)

**Comment by wcjr** [comment]
Here's what I ended up doing but it seems so boilerplate to me, I think I'm wondering if it wouldn't make more sense as the default implementation from Vuetify?

```
import Vue from 'vue'
import Vuetify from 'vuetify/lib';
import locales from '@/locales'

Vue.use(Vuetify, {
  lang: {
    locales,
    current: determineCurrentLanguage()
  },
  ...
})

function determineCurrentLanguage() {
  const mainLangOnly = navigator.language.substring(0,2)

  return locales[mainLangOnly] ? mainLangOnly : 'en'
}
```

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
