### ISSUE TITLE
[Bug Report] calendar show-month-on-first not working

### ISSUE THREAD

**Issue by depperm** [vuetifyjs/vuetify#7433]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 7

### Steps to reproduce
add `show-month-on-first="false"` to v-calendar

### Expected Behavior
No month to show up on the first

### Actual Behavior
month still shows up on the first

### Reproduction Link
<a href="https://codepen.io/anon/pen/NVQqvw?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/NVQqvw?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/59158432-5ccfec00-8afd-11e9-8c5f-4598433c7f5d.png)

**Comment by depperm** [comment]
Changing to =false doesn't work either

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/59176528-8b90a580-8b83-11e9-8362-61cfa169164a.png)

Documentation states that this property accepts `boolean` values, you're passing the `string`. If you don't know how to pass a `boolean` please check out the vuejs docs, if they are not clear enough please open the issue in their repo. And if we suggest somewhere that it accepts a `string` or we bind a `string` please show the link/screenshot and we'll fix it.
Thank you.

**Comment by dannycoulombe** [comment]
I confirm that this issue is still relatable. Passing a boolean doesn't work either.

**Comment by nekosaur** [comment]
Please don't comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
