### ISSUE TITLE
[Feature Request] Hide details on inputs unless there are details to show

### ISSUE THREAD

**Issue by yancyknight** [vuetifyjs/vuetify#7434]
### Problem to solve
Vuetify inputs have space reserved under them for showing errors and hints. This adds to the problem of large forms having too much white space as mentioned in #1846. Using `hide-details` will remove this extra space, but it also hides any hint text or validation errors. I want to remove that space unless there is a hint or error that needs to be displayed.

### Proposed solution
A new prop, maybe `conditional-details` or `auto-details`, that will hide the white space unless a hint or error is showing.

**Comment by jacekkarczmarczyk** [comment]
maybe `hide-details="auto"`?

**Comment by nekosaur** [comment]
That might lead to unwanted jumping of elements as space is hidden/shown

**Comment by jacekkarczmarczyk** [comment]
It will, but I wouldn't call it 'unwanted'

**Comment by jacekkarczmarczyk** [comment]
closed by https://github.com/vuetifyjs/vuetify/pull/7472
