### ISSUE TITLE
[Bug Report] TypeError: Cannot read property 'click' of undefined at VueComponent.changeListIndex (menu-keyable.js:69)

### ISSUE THREAD

**Issue by tmcdos** [vuetifyjs/vuetify#7440]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3773.0
**OS:** Windows 7

### Steps to reproduce
Click inside the first VSelect and type "+359" (without the quotes), then press ENTER.

### Expected Behavior
The first item which begins with the just typed prefix should be selected and the drop-down list should be closed. Or even better - the drop-down list should dynamically change the focus between the items while you type, just like the standard SELECT.

### Actual Behavior
    TypeError: Cannot read property 'click' of undefined
      at VueComponent.changeListIndex (https://r2hwi.codesandbox.io/node_modules/vuetify/dist/vuetify.js:9822:44)

      at VueComponent.onKeyDown (https://r2hwi.codesandbox.io/node_modules/vuetify/dist/vuetify.js:12612:71)

      at invokeWithErrorHandling (https://r2hwi.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:1859:26)

      at HTMLInputElement.invoker (https://r2hwi.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:2184:14)

      at HTMLInputElement.original._wrapper (https://r2hwi.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:7537:25)

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-r2hwi" target="_blank">https://codesandbox.io/s/vue-template-r2hwi</a>

**Comment by KaelWD** [comment]
See #2660, only the first 20 items are loaded if you don't have `menu-props="auto"`. If you add that then everything works as expected.

**Comment by tmcdos** [comment]
Yes, adding the `auto` works around the issue - but if you think objectively and unbiased, would not you agree with me that it would be better to check if `this.tiles[this.listIndex]` is undefined and if it is - then load the corresponding chunk of 20 items which contains the corresponding `listIndex` before calling the `click()` method ? Currently you break your own idea - the manual says that the component lazy loads items in batches of 20 to improve performance but in order to allow the user to type any item I am advised to sacrifice the performance ....

**Comment by KaelWD** [comment]
Maybe

**Comment by KaelWD** [comment]
This was resolved in 4a3d39b4cf1305be9fc97e45a1020b105322af14 as #10406
