### ISSUE TITLE
[Bug Report] Incorrect position of textarea resize handler with append icon

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7446]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1, 1.5.X
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Create an textarea with appended inner icon

### Expected Behavior
Resize handler should be located at the end of the bottom line

### Actual Behavior
Resize handlers is located before the end of the bottom line

### Reproduction Link
<a href="https://codepen.io/anon/pen/dBbNBV?editors=1000" target="_blank">https://codepen.io/anon/pen/dBbNBV?editors=1000</a>

**Comment by johnleider** [comment]
This is the same behavior as v1.5 and is expected due to the structure of inputs.
