### ISSUE TITLE
[Bug Report] iPhone keyboard is not showing search/search icon for v-text-field with type search 

### ISSUE THREAD

**Issue by nmanikiran** [vuetifyjs/vuetify#7450]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
for vuetify input with type search 
https://codepen.io/nmanikiran/pen/wLwpaN
For native browser input type search 
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_search

check the keyboard different in both links

### Expected Behavior
Now it is showing `return` instead of search.
It should show search/ search icon for the `iPhone` if the input field type is `search`

### Actual Behavior
The input type search is rendering as text field, not like a search.
It is working as expected in `Android` but not in `iPhone`

### Reproduction Link
<a href="https://codepen.io/nmanikiran/pen/wLwpaN" target="_blank">https://codepen.io/nmanikiran/pen/wLwpaN</a>

**Comment by KaelWD** [comment]
Safari = :hankey: 

It only shows the search button if the input is in a form with an `action` attribute.
