### ISSUE TITLE
[Bug Report] VSelect: Menu is larger than text field

### ISSUE THREAD

**Issue by diegosr90** [vuetifyjs/vuetify#7454]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.8
**Browsers:** Chrome 75.0.3770.80
**OS:** Mac OS 10.14.4

### Steps to reproduce
Open the input menu without typing

### Expected Behavior
menu width should not exceed the input's width

### Actual Behavior
I see that on the dynamic styles added to the menu, the widht of the input is placed as min-width.

### Reproduction Link
<a href="https://codepen.io/diegolz/pen/PrYrge" target="_blank">https://codepen.io/diegolz/pen/PrYrge</a>

### Other comments
Changing min-width to width  works fine

**Comment by johnleider** [comment]
That is not how native selects handle this scenario. The select will always try to display the full width needed to display every option without truncation.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
