### ISSUE TITLE
[Feature Request] VDivider is themable but is missing keywords styling

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#7459]
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
Add a color prop to a v-divider, while a color name or an hex code successfully changes the color of the divider (because of html behavior on hr),
 the keywords (eg: primary, secondary, info, success..) do not.

### Expected Behavior
The v-divider to take the keyword color

### Actual Behavior
The v-divider takes a lime green color

### Reproduction Link
<a href="https://codepen.io/anon/pen/EBxQdd?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/EBxQdd?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Fixed by #14797
