### ISSUE TITLE
Dialog has problem

### ISSUE THREAD

**Issue by wilsonwu** [vuetifyjs/vuetify#746]
### Steps to reproduce
When use mobile model for the page that dialog be shown, there is a gap on the page right side.
You can just try in the document site Simple Dialog: https://vuetifyjs.com/components/dialogs, switch to mobile model and click the Open Dialog.

### Versions
0.12.7

### What is expected ?
No layout change when the dialog be shown.

### What is actually happening ?
layout be modified

### Reproduction Link
https://vuetifyjs.com/components/dialogs

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/692. This will be solved in the next release, and you can find a temporary solution in the previous issue.
