### ISSUE TITLE
[Feature Request] v-tabs height support for percentages

### ISSUE THREAD

**Issue by guykatz** [vuetifyjs/vuetify#7462]
### Problem to solve
currently, the height property on the v-tabs uses px. in some cases, for example with flex layouts the pixel number is not known in advance. it would be nice to be able to 'tell' v-tabs to occupy the full height available of its parent container.
in the following codepen: https://codepen.io/guykatz/pen/LKYOyV?editors=1111 I would like v-tabs to occupy the height of the parent container (without knowing the px)
there is a css bypass which is a bit cumbersome:
```css
    .v-tabs__bar,.v-tabs__wrapper,.v-tabs__container{
    height:100%;
    }
```
this will fix the issue but maybe it will be more elegant to have peoperty on the v-tabs to accomodate this.

### Proposed solution
maybe use height property to also access percentages
thanks.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
