### ISSUE TITLE
[Bug Report] v-timeline rtl problems in cards edge

### ISSUE THREAD

**Issue by MrCapsLock** [vuetifyjs/vuetify#7465]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80, Mozilla Firefox, Safari
**OS:** Mac OS 10.14.5

### Steps to reproduce
Just add v-timeline on rtl veutify

### Expected Behavior
Edge of card should point to avatar(icon/dots)

### Actual Behavior
They point to other side (opposite)

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-9qpfz" target="_blank">https://codesandbox.io/s/vue-template-9qpfz</a>

**Comment by jacekkarczmarczyk** [comment]
This is resolved in 2.0
