### ISSUE TITLE
[Feature Request] Change color of chips in v-select

### ISSUE THREAD

**Issue by haexhub** [vuetifyjs/vuetify#7466]
### Problem to solve
You can use chips as design element in v-selects for the selected elements. It would be nice, if we could change the styling of the chip, like it is possible in normal chips.
There you can pass the color argument for proper styling. 

### Proposed solution
Can you provide an argument or style attribute for the v-select element, where we can pass the styling information for the chip? Or you could change the type of **chips** from boolean to string and pass the styling information. It would be backward compatible, because any non empty string would be considerd as true.
```
<v-select
  v-model='value'
  :items='items'
  label='Selection with chips'
  
  chips='secondary'
  chips-color='secondary'
  style='chip-color="secondary"'
></v-select>
```

**Comment by KaelWD** [comment]
There is `item` and `selection` scoped slots if you wish to customise the component more than what's available with props.
