### ISSUE TITLE
[Bug Report] v-expansion-panel-header triggers form submit within v-form

### ISSUE THREAD

**Issue by stanzakh** [vuetifyjs/vuetify#7471]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Create v-expansion-panel within a v-form
2. Click on the v-expansion-panel-header

### Expected Behavior
Expansion panel should open.

### Actual Behavior
Form submit is triggered and page refreshes.

### Reproduction Link
<a href="https://codepen.io/anon/pen/WqboGv" target="_blank">https://codepen.io/anon/pen/WqboGv</a>

**Comment by jacekkarczmarczyk** [comment]
Fixed in cf0da4b54a5db9b59d85468bfd1824580112b123
