### ISSUE TITLE
[Bug Report] Searching and sorting does not working when we are using 'body' slot.

### ISSUE THREAD

**Issue by PKacprow** [vuetifyjs/vuetify#7474]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Create v-data-table,
2. Use body slot to body creation
3. Add searching option
4. Try to search and sort data in table

### Expected Behavior
Proper result of sorting and serching when we are using body slot

### Actual Behavior
Sorting and searching does not working with body slot

### Reproduction Link
<a href="https://codepen.io/anon/pen/vqEryQ?editors=1010" target="_blank">https://codepen.io/anon/pen/vqEryQ?editors=1010</a>

### Other comments
Searching and sorting does not working when we are using 'body' slot.

**Comment by jacekkarczmarczyk** [comment]
If you're providing body slot then you are responsible for its contents, including sorting and searching

**Comment by nekosaur** [comment]
Incorrect, both search and sort works just fine when using the body slot.

However,

1. You are _not_ using the body slot in the provided codepen, you are using the item slot.
2. Inside the item slot, which is meant for rendering a single row, you are instead iterating over the desserts prop and rendering multiple rows.

https://codepen.io/anon/pen/mZyQPJ?editors=1010

**Comment by jacekkarczmarczyk** [comment]
Oops, i missed the wrong slot name and iterating over desserts mislead me even more
