### ISSUE TITLE
[Feature Request] Carousel transition speed

### ISSUE THREAD

**Issue by depperm** [vuetifyjs/vuetify#7476]
### Problem to solve
The option to change the speed at which the transition happens. This is not the interval speed which is the time between transitions. 

Currently all transitions (1 sec or 10sec apart) all happen at the same speed. 

### Proposed solution
New prop, transition-speed that is number|string

**Comment by KaelWD** [comment]
There's a `$window-transition` stylus/sass(2.0) variable.

**Comment by jacekkarczmarczyk** [comment]
Won't it affect tabs and other window-based component as well? There's always custom css if you need it just for carousel or a specific instance of some component

**Comment by depperm** [comment]
Can you give an example of `$window-transition` as I don't see any documentation on that.

**Comment by JakubOrzol** [comment]
Try adding this (sass) to your styles to override vuetify:
`.v-window {
    &-x-transition,
    &-x-reverse-transition,
    &-y-transition,
    &-y-reverse-transition {
        &-enter-active,
        &-leave-active {
            transition: .6s cubic-bezier(.25, .8, .50, 1) !important;
        }
    }
}`

**Comment by bryanspearman** [comment]
Just expanding on this a little for the benefit of total novices like myself:

`<style lang="scss" scoped>
  .v-window {
      &-x-transition,
      &-x-reverse-transition,
      &-y-transition,
      &-y-reverse-transition {
        &-enter-active,
        &-leave-active {
          transition: 1.5s cubic-bezier(0.25, 0.8, 0.5, 1) !important;
        }
      }
    }
</style>`

Thanks @ JakubOrzol
