### ISSUE TITLE
[Feature Request] Size-change for table per page event

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#7477]
### Problem to solve
Check when change row per page

### Proposed solution
-

**Comment by jacekkarczmarczyk** [comment]
?

**Comment by skortabeast** [comment]
@jacekkarczmarczyk  for example element ui table has method change-size , when  Rows per page in table is changing,  how check if Rows per page change value, except use watch?

**Comment by nekosaur** [comment]
`@update:items-per-page` in 2.0, `@update:pagination` in 1.5
