### ISSUE TITLE
Main content appearing behind permanent clipped drawer 

### ISSUE THREAD

**Issue by KrashBlanding** [vuetifyjs/vuetify#748]
### Steps to reproduce
Followed the demo for [permanent clipped drawer](https://github.com/vuetifyjs/docs/blob/master/examples/layouts/3.vue) in the pre-defined layouts section.

### Versions

Vue - 2.3.4
Vuetify - 0.12.7
OS - Windows 10
Browser - Chrome 58

### What is expected ?

I would expect the main content to be to the right of the navigation drawer.  When the navigation drawer is not clipped, the main content appears as I would expect.

### What is actually happening ?

My main content takes up the full width of the viewport which is partially occluded by the drawer.

### Reproduction Link

https://codepen.io/KrashBlanding/pen/MoyVVG

**Comment by johnleider** [comment]
Can confirm this bug has been resolved on dev. Just a missing style declaration. For now, here is an example workaround until next release, https://codepen.io/johnjleider/pen/EXyxKL.
