### ISSUE TITLE
[Bug Report] Nuxt adding another vuetify-theme-stylesheet on every page refresh

### ISSUE THREAD

**Issue by csheppard** [vuetifyjs/vuetify#7481]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.13.6

### Steps to reproduce
```
yarn
yarn run dev
http://localhost:3000/
```

### Expected Behavior
There should only ever be 1 vuetify-theme-stylesheet.

### Actual Behavior
Every time you do a full page refresh a new `<style data-n-head="true" type="text/css" id="vuetify-theme-stylesheet" nonce>` will be added to the head.

This only occurs when vuetify-loader is used and so makes it difficult to develop theme colors or switch between dark/light themes. 

![Imgur](https://i.imgur.com/R24cC0L.png)

### Reproduction Link
<a href="https://github.com/csheppard/nuxt-vuetify-loader-issue" target="_blank">https://github.com/csheppard/nuxt-vuetify-loader-issue</a>

### Other comments
Have tested in dev mode without vuetify-loader and all is fine.

**Comment by KaelWD** [comment]
This isn't directly related to vuetify-loader. 

@kevinmarrec fixed #7443, but that was an empty stylesheet. This one appears to be added by vue-meta instead.

**Comment by KaelWD** [comment]
#7497
