### ISSUE TITLE
[Bug Report] How to install local document

### ISSUE THREAD

**Issue by 625781186** [vuetifyjs/vuetify#7490]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.5.8
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
I'm going to do this step,
[docs/README.md](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/README.md)

but :
![image](https://user-images.githubusercontent.com/30521429/59403940-541a3700-8dd7-11e9-9543-00b7ffa30dac.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify.git

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by 625781186** [comment]
> https://github.com/vuetifyjs/vuetify.git
> 
> The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

Sorry , I can't find any answer on the Internet.
I don't know if [https://github.com/vuetifyjs/vuetifyjs.com.git](https://github.com/vuetifyjs/vuetifyjs.com.git) in  [docs/README.md](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/README.md) is correct, because when I access it it says 404.

![image](https://user-images.githubusercontent.com/30521429/59405768-33091480-8dde-11e9-81da-53988b5aa78f.png)

**Comment by 625781186** [comment]
Resolve :
Don't read ~~[docs/README.md]~~

Just
`yarn & yarn build & yarn dev docs`

![image](https://user-images.githubusercontent.com/30521429/59410661-fb08ce00-8deb-11e9-8412-e93471595af4.png)
