### ISSUE TITLE
[Feature Request] Add row click event to table component

### ISSUE THREAD

**Issue by canhkieu** [vuetifyjs/vuetify#7491]
### Problem to solve
With vuetify v2.0 table are more convenient. Table just config in v-data-table tag. Now if I wanna catch RowClick Event, I must overide item template. I suggess add a onRowClick.
```
<v-data-table
    :headers="headers"
    :items="desserts"
    :items-per-page="5"
    @onRowClick="openDetail"
    class="elevation-1"
  ></v-data-table>
```

**Comment by canhkieu** [comment]
Fix format

**Comment by jacekkarczmarczyk** [comment]
`@click:row` would be more in line with other components

**Comment by Davor111** [comment]
Would be great if you could add this to the documentation.

**Comment by KaelWD** [comment]
You mean like this?
![image](https://user-images.githubusercontent.com/16421948/74016542-b23efe80-49e6-11ea-9109-34149c3f6753.png)
