### ISSUE TITLE
[Bug Report] mousedown & mouseup Events on append-outer and prepend are not fired

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#7493]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
Add an event @mouseup:append-outer on a VInput, click on it and notice the event is not triggered at all

### Expected Behavior
The event should be triggered when clicking

### Actual Behavior
No event

### Reproduction Link
<a href="https://codepen.io/anon/pen/ewNPgz" target="_blank">https://codepen.io/anon/pen/ewNPgz</a>

### Other comments
Those events are quite important when you need to check for continuous pressing of a button, for example I wanted to create a number input but I can only listen to the click event, I need the events mouseup to set a timeout and intervals and the mousedown to clear those intervals/timeouts

**Comment by nekosaur** [comment]
Use a slot for more complex scenarios involving prepend/append. https://codepen.io/anon/pen/RzPevd

**Comment by Tofandel** [comment]
That will do, thanks
