### ISSUE TITLE
[Bug Report] deletable-chips setting doesn't work for autocomplete, combobox

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#7494]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows

### Steps to reproduce
It can even be seen in vuetify's own example
https://next.vuetifyjs.com/en/components/combobox
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/combobox/usage.vue

that despite deleteable-chip being false by default, chips inside dropdowns have delete button 

### Expected Behavior
bu default chips in dropdopwn editors are without delete button 

### Actual Behavior
Despite deleteable-chip being false by default, chips inside dropdowns have delete button 

### Reproduction Link
<a href="http://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/combobox/usage.vue" target="_blank">http://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/combobox/usage.vue</a>

**Comment by KaelWD** [comment]
Just having an event listener is apparently enough to show the button now, doesn't seem like a great idea imo: https://github.com/vuetifyjs/vuetify/commit/148332d98c15a7bd361c9b7ae69ec60b7800e245#diff-f1183a2a68b3129e318f779aa8307443
