### ISSUE TITLE
[Bug Report] Can't scroll in a div with text-fields inside on iOS

### ISSUE THREAD

**Issue by Akyrish** [vuetifyjs/vuetify#7495]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Safari
**OS:** iOS 12.3.1

### Steps to reproduce
Open the link on a iPhone, try to scroll in the div.

### Expected Behavior
It scrolls

### Actual Behavior
When your finger is on a text-field when you try to scroll, it try to scroll the whole page. 
To scroll in the div, you have to put your finger beetween 2 text-fields.

### Reproduction Link
<a href="https://codepen.io/Akyrish/pen/PrPYEV" target="_blank">https://codepen.io/Akyrish/pen/PrPYEV</a>

### Other comments
Works fine on android. Does not happen if the div containing the text-fields have a height:100%.
I use -webkit-overflow-scrolling: touch as a workaround, but it causes other problems.

**Comment by KaelWD** [comment]
You have to use `-webkit-overflow-scrolling: touch` on your scrollable div.

**Comment by Akyrish** [comment]
I'm using it, but their is at least 2 problems with this CSS property :
- When you put focus on an input and scroll, the cursor in the input does not scroll
- When you have custom scrollbars (::-webkit-scrollbar), they do not appear anymore

**Comment by KaelWD** [comment]
I'm not sure what we're supposed to do about that, it sounds like a browser bug.
