### ISSUE TITLE
Vuetify mixed with Material Design Light

### ISSUE THREAD

**Issue by fbmfbm** [vuetifyjs/vuetify#750]
Hi all,

Any one use Vuetify associated with Material Design Light ? 
can both work in same app without pbm ?

Thank's for your answer.

fbm

**Comment by johnleider** [comment]
Please direct questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by fbmfbm** [comment]
Ok sorry..
