### ISSUE TITLE
[Feature Request] contextmenu for treeview

### ISSUE THREAD

**Issue by sunmoonone** [vuetifyjs/vuetify#7503]
### Problem to solve
right click or hold-press a tree item will popup a contextmenu with commands.
can i use the ```append``` slot to open a contextmenu?

### Proposed solution
bind a contextmenu with the ```append``` slot

**Comment by jacekkarczmarczyk** [comment]
Probably it could be solved by [adding a slot support](https://github.com/vuetifyjs/vuetify/issues/8138)

**Comment by johnleider** [comment]
I'm going to close this in favor of the above listed Feature Request as that would be the extent of our support for this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
