### ISSUE TITLE
[Feature Request] Granular RTL Support

### ISSUE THREAD

**Issue by shrfarzk** [vuetifyjs/vuetify#7507]
### Problem to solve
Usually when people switch an app to rtl, they want to exempt the toolbar from this change, which usually also contains the language switch, otherwise, things shift around too much.

Use case: I want to switch an app to rtl while still keeping the toolbar ltr.

This would solve: being forced to have an rtl toolbar in an rtl app when it should be optional.

End user benefits: app behaves more predictably.

### Proposed solution
API suggestion:
An :rtl prop on all vue components that overrides the global rtl value for this component (maybe it's children as well)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
