### ISSUE TITLE
[Feature Request] Add the option for v-pagination to show only arrows

### ISSUE THREAD

**Issue by lsparey** [vuetifyjs/vuetify#7510]
### Problem to solve
Allow the pagination to be more compact and match the style used in Gmail, where only a left and right arrow are visible. Setting total-visible="0" is ignored and setting length="0" has the desired appearance but disables the pagination

### Proposed solution
Either allow total-visible="0" or add a prop for compact / mini-variant / just-arrows

**Comment by josephzidell** [comment]
Is this the inverse of #12520?

**Comment by MajesticPotatoe** [comment]
resolved in 53ba1d8
