### ISSUE TITLE
[Bug Report] Failed to building Vuetify with TypeScript

### ISSUE THREAD

**Issue by osasson** [vuetifyjs/vuetify#7513]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Windows 10

### Steps to reproduce
The codepen is irrelevant!

Scenario 1 (A la Carte)
=====================
vue create test (
  Bable, TypeScript; 
  class-style component syntax; 
  Babel alongside TS; 
  Dedicated config files)
cd test
npm i vuetify@v2.0.0-beta.2 (or with 'vue add vuetify' and updating after)
npm i sass-loader
npm i node-sass

  comment the stylus import in ./plugins/vuetify.ts

npm run build

Scenario 2 (full package)
=====================
vue create test (
  Bable, TypeScript; 
  class-style component syntax; 
  Babel alongside TS; 
  Dedicated config files)
cd test
npm i vuetify@v2.0.0-beta.2 (or with 'vue add vuetify' and updating after)

main.ts:
  import '@babel/polyfill'
  import Vue from 'vue'
  import Vuetify from 'vuetify'
  import './plugins/vuetify'
  import App from './App.vue'

  Vue.config.productionTip = false

  new Vue({
    vuetify: new Vuetify({  iconfont: 'md'}),
    render: h => h(App),
  }).$mount('#app')

npm run build

### Expected Behavior
no errors

### Actual Behavior
Scenario 1 (many errors like the one below)
=====================
error  in ./node_modules/vuetify/src/components/VDataTable/VDataTable.sass

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
   ^
      Invalid CSS after "    @content": expected "}", was "($material-light); "
      in C:\Users\SASSON\dev\test\t1\node_modules\vuetify\src\styles\tools\_theme.sass (line 3, column 5)

Scenario 2
=====================
Cannot use 'new' with an expression whose type lacks a call or construct signature

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by KaelWD** [comment]
> `Invalid CSS after "    @content"`

Please read the upgrade guide, you need to be using the `sass` package. 

> `Cannot use 'new'`

We haven't written type definitions for 2.0 yet.
