### ISSUE TITLE
[Bug Report] fab v-btn with href and nested v-icon utilizing fontawesome5 causes misalignment

### ISSUE THREAD

**Issue by num-lock** [vuetifyjs/vuetify#7516]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Create a round `v-btn` with a nested `v-icon` utilizing fontawesome5. Applying a `href` to the button messes up the alignment. Works fine with Material Icons, though.

### Expected Behavior
Icon should be centered within the button area.

### Actual Behavior
Icon is misaligned to the top-left of the button area.

### Reproduction Link
<a href="https://codepen.io/anon/pen/MMKeab" target="_blank">https://codepen.io/anon/pen/MMKeab</a>

### Other comments
Only appears on fab (round) buttons as far as I can tell. No matter if small or large.

**Comment by KaelWD** [comment]
Icon CSS needs to be loaded above vuetify.css
