### ISSUE TITLE
[Feature Request] Parent class for theme generator

### ISSUE THREAD

**Issue by runegame** [vuetifyjs/vuetify#7517]
### Problem to solve
The automatically generated vuetify-theme-stylesheet classes are very general (.primary .secondary... continue). Then when we insert Vuetify into a site, it can collide with other elements and is unwanted behavior.

### Proposed solution
To solve this problem we can add in the initiator of Vuetify an option that is parentClass, and this will be used in all the rules of 'vuetify-theme-stylesheet'.

https://codepen.io/anon/pen/KjVadV

**Comment by jacekkarczmarczyk** [comment]
fixed in https://github.com/vuetifyjs/vuetify/pull/7768
