### ISSUE TITLE
[IE11 bug] Dialog Overlay Issue

### ISSUE THREAD

**Issue by mornir** [vuetifyjs/vuetify#752]
### Versions
Vuetify 0.12.7
only affects IE11

### What is expected ?
When closing the dialog, the div element with the class "overlay overlay--active" become "overlay ". Then this div element is removed from the DOM.

### What is actually happening ?
The div element is not removed from the DOM. Since the overlay is still present, the page becomes unresponsive.

### Reproduction Link
After I closed the dialog, the added div the overlay class is not removed:
![image](https://user-images.githubusercontent.com/1411843/27050247-1b26c37e-4fb2-11e7-9f61-0afc8feacad1.png)
I don't have any error in the IE11 console.

### Commentary
I created a code pen, but I couldn't reproduce the bug. I also created two projects, one with the template "Simple HTML" and one with "webpack-simple". In both projects, the overlay doesn't appear at all (the div element with the overlay class isn't added to the DOM). Here the console gives me the error: Object doesn't support property or method 'closest'. But I don't think that the issue. (And for all my tests, I've always added the necessary polyfills).

This is a really weird bug... I spent my afternoon looking for the cause.
From what I could gather, this line in the overlay mixin is working properly:
`this.overlay.className = this.overlay.className.replace('overlay--active', '')`
The problem might lie in the `this.overlay.remove()`

I hope my issue report is not too confusing...

**Comment by johnleider** [comment]
Would it be possible to get you on chat so we could troubleshoot this since you can't reproduce it in a codepen?

**Comment by manjuk41** [comment]
Vuetify 0.12.7 
Not only in IE, the problem is occurring in chrome also.
overlay element stays in the DOM after closing dialog programmatically.
I used removeOverlay method. It would be good to get it fixed if its a bug.

**Comment by mornir** [comment]
I tried the deployed version of my app on another computer with IE11. No overlay is applied when a dialog is open, so there's no bug when closing it. For my current project, I don't mind if there's no overlay effect on IE11. I just want basic support for this dreadful browser.

I'm leaving this issue open because manjuk41 raised another problem. @johnleider but feel free to close it. 

When I'm back home I will try manjuk41 quickfix, as shown in #570

Anyway, maybe the fix to Vuetify provided in #700 will solve everything once it is shipped.

**Comment by manjuk41** [comment]
@mornir 
thank you

**Comment by mornir** [comment]
I didn't succeed in using removeOverlay. But like I said, once my app deployed, no overlay is applied = no issue when closing dialog, which is fine by me.

@manjuk41 I'm pretty sure that your bug is related to #700. Wait for the 0.13.0 Vuetify update. If your problem persists, open an issue.
