### ISSUE TITLE
[Bug Report] Tooltip disappears after clicking button in Chrome

### ISSUE THREAD

**Issue by BowenYin** [vuetifyjs/vuetify#7529]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.0

### Steps to reproduce
With Google Chrome on Mac, click on the button in the new docs at the top of the page for tooltips, like shown below.
![2019-06-15 18 05 35](https://user-images.githubusercontent.com/30426637/59557812-537cce80-8f98-11e9-9020-7e338e496e32.gif)

### Expected Behavior
The tooltip should stay visible after clicking the button, like it did in v1.5.

### Actual Behavior
When a tooltip is attached to a button in v2.0, clicking on the button in Google Chrome makes the tooltip disappear suddenly.

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/tooltips#usage" target="_blank">https://next.vuetifyjs.com/en/components/tooltips#usage</a>

### Other comments
As far as I'm aware, Safari and Firefox don't have this issue.

**Comment by KaelWD** [comment]
This was unintentional, but could be argued as correct based on google's spec: 

> [If the user takes another action before that time ends, the tooltip will disappear.](https://material.io/design/components/tooltips.html#behavior)

**Comment by emiliemarchand** [comment]
Adding `retain-focus-on-click` to the button did the trick for me:

```
<v-tooltip top>
  <template v-slot:activator="{ on, attrs }">
      <v-btn
        v-bind="attrs"
        v-on="on"
        retain-focus-on-click
      >
          Button
      </v-btn>
  </template>
  <span>Tooltip</span>
</v-tooltip>
```
