### ISSUE TITLE
Question: Difference between v-app, v-container, v-flex, v-col, v-row and v-layout

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#753]
I didn't anywhere in the documentation. What is the difference between v-app, v-container, v-flex, v-col, v-row and v-layout?

I took a look in here (https://vuetifyjs.com/layout/grid), but it didn't mentioned v-app, v-col or v-row.

**Comment by mornir** [comment]
For this kind of questions, it is better to use the Gitter channel: https://gitter.im/vuetifyjs/Lobby/
v-col and v-row are deprecated. v-row is now v-layout. v-col is now v-flex. v-app encapsulates every Vuetify app.
https://vuetifyjs.com/layout/pre-defined

**Comment by jvbianchi** [comment]
Thanks
