### ISSUE TITLE
[Bug Report] V-tab animation on the iPhone on chrome only, safari works

### ISSUE THREAD

**Issue by Albertbol** [vuetifyjs/vuetify#7533]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Google Chrome
**OS:** iOS

### Steps to reproduce
Open official vuetify docs with iphone using chrome on tab section https://next.vuetifyjs.com/en/components/tabs#tab , animation is not working as expected on tabs where text needs to be changed under them. 
P.S on safari animation works good.

### Expected Behavior
Smoother animation same as desktop

### Actual Behavior
Rapid animation

### Reproduction Link
<a href="https://codepen.io/anon/pen/mZVKJM#anon-login" target="_blank">https://codepen.io/anon/pen/mZVKJM#anon-login</a>

**Comment by johnleider** [comment]
The provided pen is v1.5. Also it's very difficult to test this without an actual device. Can you check the latest beta and see if this behavior is still happening? Maybe provide a gif of the issue.

**Comment by johnleider** [comment]
I've tested v2 with an iphone and it performs as expected.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
