### ISSUE TITLE
[Bug Report] Rules get triggered on initial load

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#7534]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 7

### Steps to reproduce
Initial load of the page shows the alert as rule is executed. But error message is suppressed.

### Expected Behavior
Rules should not get executed on initial load. 

### Actual Behavior
Rules get executed on initial load. This has performance implications.

### Reproduction Link
<a href="https://codepen.io/prasmi/pen/KjzdQM?editors=1011" target="_blank">https://codepen.io/prasmi/pen/KjzdQM?editors=1011</a>

**Comment by johnleider** [comment]
This has been in place for over the past 2 years. I don't necessarily disagree with your assessment, but I'm cautious to fix this as a bug. It also stands to reason for that case, the soonest we'd be able to consider a change like this would be in v3 unless the @vuetifyjs/core-team has any additional insight.

**Comment by KaelWD** [comment]
v-form checks field validity without forcing them to display validation errors, this can be used to disable submit buttons until the form is valid: https://vuetifyjs.com/en/components/forms/#playground
