### ISSUE TITLE
[Bug Report] Buttons size inconsistency on Vuetify 2

### ISSUE THREAD

**Issue by kevinmarrec** [vuetifyjs/vuetify#7535]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
If you compare [Vuetify **1.5.x**](https://vuetifyjs.com) & [Vuetify **2.x**](https://next.vuetifyjs.com) documentations and look after the `large` buttons (**i.e** "Get Sarted" button), you can easily see the height differences (**44px** vs **54px**).

### Expected Behavior
| size    | 1.5.x | 2.0.0-beta.2 | Expected
|---------|--------|---|---|
| x-small |  -  | 20px | 20px
| small   | 28px   | 28px | 28px
| default | 36px   | 36px |  36px |
| large   | **44px**   | <div style='color:red;'>**54px**</span>| **44px** |
| x-large | -  | **70px** | **52px** |

This size table is the result of if we keep a **8px** step between them.
Font sizes may also need to be recalculated as well to fit these sizes.

### Reproduction Link
<a href="https://codepen.io/anon/pen/MMyyex" target="_blank">https://codepen.io/anon/pen/MMyyex</a>

### Other comments
I thought it was cause of a MD2 guideline but couldn't find any about this, so I think buttons sizes should be reviewed, as there is for now a too high gap between `default` & `large` sizes (**18px**).

**1.5.x** sizes (source code) : https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/settings/_variables.styl#L181

**2.x** sizes (source code) : https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VBtn/_variables.scss#L9

**Comment by MajesticPotatoe** [comment]
closed in #7536
