### ISSUE TITLE
Add a "loading-text" property to the data table (feature request)

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#754]
It would be great if there was a loading-text prop for the data table that displays a text string in the table when the loading property is true. The majority of my tables load their data after the template is mounted and in its current configuration the user sees the no-results-text value while the grid is still in a loading state. The message is technically true but I'd rather display "fetching data..." or something along those lines instead. 

It's certainly not a big deal and I can most definitely work around it, I just thought I'd throw it out there. 

Keep up the great work.

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Thank you for your feature request and I'll reopen this once the correct format is followed.

**Comment by bashilbers** [comment]
@stoked74 please reformat, I would also like a loading text :-)

**Comment by nekosaur** [comment]
@bashilbers  Please create a new issue using the [issue creator](https://issues.vuetifyjs.com). Thank you.
