### ISSUE TITLE
[Bug Report] Floating Button Positioning Only Works With “fab”

### ISSUE THREAD

**Issue by princej888** [vuetifyjs/vuetify#7540]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.155
**OS:** iOS 12.3

### Steps to reproduce
Use Example from https://next.vuetifyjs.com/en/components/floating-action-buttons and set :fab=“false”

### Expected Behavior
Positioning, e.g. top right, should work regardless of whether fab is true or false

### Actual Behavior
Positioning only works for :fab=“true”

### Reproduction Link
<a href="https://codepen.io/princej8/pen/dBMmrQ" target="_blank">https://codepen.io/princej8/pen/dBMmrQ</a>

**Comment by johnleider** [comment]
Didn't catch this, I associated the fix with #7948 even though this was first.

Resolved in 23c8518
