### ISSUE TITLE
[Bug Report] Attach menu from v-select with menu-props not working

### ISSUE THREAD

**Issue by sarahtheflame** [vuetifyjs/vuetify#7547]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Insert a v-select
2. Create a div with an id
3. Add this attribute to the v-select: `:menu-props="{ attach: '#yourId' }"`
4. Inspect DOM to locate the menu: it is at the application root instead of inside the div with the id

### Expected Behavior
The menu generated by v-select should be a child of the div with the id

### Actual Behavior
The menu is attached to the root element of the Vue app

### Reproduction Link
<a href="https://codepen.io/sarahtheflame/pen/MMyzPb" target="_blank">https://codepen.io/sarahtheflame/pen/MMyzPb</a>

### Other comments
I included a basic menu in the codepen with the expected functionality. The attach property works in a simple menu, but not when passed from a v-select by menu-props

**Comment by jacekkarczmarczyk** [comment]
Workaround: https://codepen.io/anon/pen/pXNXWq

**Comment by alex-lit** [comment]
Same bug on Vuetify  2.3.14

**Comment by C0Nd3Mnd** [comment]
Same with `<v-autocomplete>`, passing `menu-items` ignores the `attach` prop.

**Comment by arawwad0** [comment]
just pass the attach prop to the component(v-select or v-autocomplete), it works for me. It messes up the menu styles  but could be fixed

**Comment by jsmedmar** [comment]
the prop `content-class ` is also not being passed to the menu.

**Comment by mirash333** [comment]
> the prop `content-class ` is also not being passed to the menu.

```contentClass``` *

**Comment by jourdain** [comment]
I'm wondering if there is any solution/workaround when using [v-runtime-template](https://github.com/alexjoverm/v-runtime-template) where the `v-app` along with the rest of the vuetify components belong to the string template provided as prop to `v-runtime-template`?

From my initial investigation, the `.v-menu__content` is nowhere to be found which is expected when `v-app` is not part of the tree. But the thing is that the `v-app` will be available, but probably not at the time when `v-select/v-menu` is looking for it.

So I was hoping I could `attach` either the `v-menu` or `v-select` to a static `div#menuRoot` that live as a sibling to the dynamically generated `v-app`. Unfortunately I can't figure out a way to get the menu to show up...

My project is probably too big/tricky to get into for testing/debugging. But in case you are curious the code is [here](https://github.com/Kitware/py-web-vue).

And to reproduce/test you can run the following commands:

```
mkdir tmp
cd tmp
curl -O https://raw.githubusercontent.com/Kitware/py-web-vue/master/examples/00_getting_started/basic/app.py
python3 -m venv py-env
source ./py-env/bin/activate
pip install pywebvue
python ./app.py --port 1234
=> open: http://localhost:1234/
```

And to adjust the template code, just edit the python file...
Thanks for any help/hint you could provide.

My dependencies versions are as follow:

```
    "@mdi/font": "^5.9.55",
    "core-js": "^3.6.5",
    "typeface-roboto": "^1.1.13",
    "v-runtime-template": "^1.10.0",
    "vue": "^2.6.11",
    "vuetify": "2.5.0",
    "vuex": "^3.4.0",
```

**Comment by stuomas** [comment]
Any workaround for contentClass not working on v-menu?

**Comment by caseybishop** [comment]
> 

This linked codepen doesn't show a work around. Could it be updated please?

**Comment by jourdain** [comment]
I wanted to add that I'm all good with my specific needs. I end-up updating the `key` or the component when my html template was getting updated. This allowed the widget to properly regenerate the `v-menu` in the new DOM content.
