### ISSUE TITLE
Text input label has no for attribute & input doesn't have matching ID attribute

### ISSUE THREAD

**Issue by Shelob9** [vuetifyjs/vuetify#755]
### Steps to reproduce
* Create text input

### Versions
Vuetify 0.12.0, Vue 2.1.10

### What is expected ?
I would expect that label has a for attribute and input has matching ID attribute to screen readers & other assistive devices can properly interpret form.

### What is actually happening ?
No for attribute on label

### Reproduction Link
![screenshot from 2017-06-12 18-06-38](https://user-images.githubusercontent.com/1994311/27057376-eb855dc8-4f99-11e7-84fc-1d1a0a5bf403.png)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Shelob9** [comment]
Sorry, I also maintain an open source project and I know this is important,
I thaught I had given enough info to illustrate a very simple bug. I will
try again tomorrow.

**Comment by dohomi** [comment]
@johnleider I think what @Shelob9 is missing:
```
<v-text-field label="Some Label"></v-text-field>
==>
<div>
<label for="thisInputField">Some Label</label> // missing "for" attribute
<input id="thisInputField" (...)/> // missing "id" attribute connected to the label
</div>
```
@Shelob9 not sure which elements are you missing precisely for screen readers?

**Comment by Shelob9** [comment]
@dohomi You are understanding correctly.

**Comment by dohomi** [comment]
@johnleider what do you think? Either using the v-model variable as string or better the `id` on any form element? This might be usable for any input element (especially checkbox or radio I guess).

**Comment by johnleider** [comment]
The text input looks for an id or name to fill those props. I'm not sure that just putting something there when not specified is the right approach. What is the difficulty with specifically assigning an id or name to avoid this?

**Comment by dohomi** [comment]
I'm good with that 👍 then the chosen `id` attribute should be linked as `for`attribute on the label?

**Comment by johnleider** [comment]
It already does, which is why I'm confused by this ticket.

**Comment by dohomi** [comment]
@Shelob9 did you try using the `id`?

**Comment by johnleider** [comment]
This functionality currently exists and works in 0.13, if you have any additional issues, please open another issue.
