### ISSUE TITLE
[Feature Request] v-overlay with detachable and click-outside

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#7554]
### Problem to solve
I want to show a menu with a translucent overlay across the whole page, but it's in a positioned container so the overlay has to detach to the root as well. Click-outside could be handled by v-menu still but it makes sense to have as an option (and could replace click-outside entirely: #5310)

### Proposed solution
Make v-overlay extend detachable
Emit a model update when clicked on the overlay background instead of the content
VDialog can then use VOverlay directly instead of hacking around with `$mount()`

Related: #2984, #3924, #4588, #5310, #5751, #5837, #7310

**Comment by pcornelissen** [comment]
the event for "outside clicks" would be very handy, so we can close the overlay in this case

**Comment by boris-graeff** [comment]
Hi @KaelWD , any update on this ? Thanks

**Comment by sigjak** [comment]
What worked for me in calendar  was watching selectedOpen and toggle an overlay on when selectedOpen is true,  and off when selected open is false

**Comment by KaelWD** [comment]
Resolved by #13681
