### ISSUE TITLE
[Bug Report] v-text-field style wrong

### ISSUE THREAD

**Issue by Ariaal** [vuetifyjs/vuetify#7559]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.6
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
npm install vuerity@2.0.0-beta.2 and then add in mian.js : import vuetify from vuetify ; import 'vuetify/dist/vuetify.min.css'; Vue.use(vuetify);  and ready to use it in other page. <v-text-field label="Outline" outlined></v-text-field> but laber displayed on the right which sholud on the left.

### Expected Behavior
laber displayed on the left

### Actual Behavior
laber displayed on the right

### Reproduction Link
<a href="https://codepen.io/ariaal/pen/agZrzX" target="_blank">https://codepen.io/ariaal/pen/agZrzX</a>

### Other comments
may i use this plugins wrong?

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
