### ISSUE TITLE
[Bug Report] VTreeview - selecting parent node activates last child

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7566]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2; 2.0.4
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Click the arrow to open the Applications node
2. Click the checkbox
P. S. by @sh7dm: Works both ways (1; 2) or (2; 1)

### Expected Behavior
Last child node should not be activated

### Actual Behavior
Last child node is activated

### Reproduction Link
https://codepen.io/anon/pen/EBgyrW?&editable=true&editors=101

**Comment by nekosaur** [comment]
Setting the same value for `value` and `active` won't work. When selecting the parent node, the actual value of `value` is only the child nodes `[2, 4]`. And activatable only supports having a single active node (unless you use `multiple-active`). Using `multiple-active` perhaps gets you a bit close to what you want.
