### ISSUE TITLE
[Feature Request] Set transition origin for tooltips

### ISSUE THREAD

**Issue by BowenYin** [vuetifyjs/vuetify#7568]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.90
**OS:** Mac OS 10.14.0

### Steps to reproduce
Use a transition with a tooltip (see Codepen below for the working example with a menu and the non-working example with a tooltip).

### Expected Behavior
VMenu and other components come with an `origin` prop which can set the transition origin, like `"top center"` for the scale transition. VTooltip currently doesn't have this, only a `transition` prop so the origin can't be customized.

### Actual Behavior
When using the scale transition with a tooltip, setting the transition origin is not possible with props. Should be an easy fix.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pXEdjY?editors=1010" target="_blank">https://codepen.io/anon/pen/pXEdjY?editors=1010</a>

**Comment by 1337erik** [comment]
just ran into this same issue with animating buttons with tooltips. Not sure whats wrong

**Comment by johnleider** [comment]
It doesn't work because it's not currently a feature. Changing ticket.

**Comment by johnleider** [comment]
Mistakenly referenced this issue, disregard.

**Comment by BowenYin** [comment]
Was this issue mistakenly closed again? https://github.com/vuetifyjs/vuetify/commit/85ac7d47b5c9c20bc12c86c6f4543fdd1dcd0238 doesn't seem to be related to this.

**Comment by KaelWD** [comment]
In v3 tooltips and menus use the `origin` prop to define a point on the activator they attach to, and automatically animate from that point.
