### ISSUE TITLE
date-packer in Chinese display issue.

### ISSUE THREAD

**Issue by midori-tooyama** [vuetifyjs/vuetify#757]
# Steps to reproduce

Use Chinese days in date-packer.

```javascript
days: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
```

# Versions

Vuetify 0.12.7

# What is expected ?

Show '日 一 二 三 四 五 六' in thead

# What is actually happening ?

Show '星 星 星 星 星 星 星' in thead

<https://github.com/vuetifyjs/vuetify/blob/master/src/components/pickers/mixins/date-table.js#L41>

Because the src uses

```javascript
o.substr(0, 1)
```

to get short shorthand of days.

Could you add a props like 'days' and 'months' to change this?

# Reproduction Link

<https://codepen.io/anon/pen/gRMXKa>

# And Feature Request (I'm not sure if this can be called bug)

Custom the way how date be shown.

In the file

<https://github.com/vuetifyjs/vuetify/blob/master/src/components/pickers/mixins/date-title.js#L5>

The default data format in title is hard coded like this (I ignored the '<br>
' here):

```javascript
`${this.dayName.substr(0, 3)}, ${this.monthName.substr(0, 3)} ${this.day}`
```

Result looks like '星期二, 6月 13'.

But in Chinese, people use :

```javascript
`${this.monthName}${this.day}日, ${this.dayName}`
```

Should looks like '6月13日, 星期二'

And in

<https://github.com/vuetifyjs/vuetify/blob/master/src/components/pickers/mixins/date-header.js#L31>

```javascript
`${this.months[this.tableMonth]} ${this.tableYear}`
```

Result looks like '6月 2017'.

In Chinese:

```javascript
`${this.tableYear}年 ${this.months[this.tableMonth]}`
```

Should looks like '2017年 6月'

Could it be possible to add props to change these two functions like this:

```vue
<template>
  <v-date-picker
  :months='months'
  :title-date-format='titleDateFormat'
  :header-date-format='headerDateFormat' />
<template>

<script>
export default {
  data() {
    return {
      months: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
        .map(x => x + '月'),
    }
  }
  methods: {
    titleDateFormat: (dayName, monthName, day) =>
      `${monthName}${day}日, ${dayName}`,
    headerDateFormat: (tableMonth, tableYear) =>
      `${this.months[tableMonth]} ${tableYear}`,
  }
}
</script>
```

**Comment by nekosaur** [comment]
These are some good suggestions
