### ISSUE TITLE
[Bug Report] bottom-navigation button icon margin affected by a badge

### ISSUE THREAD

**Issue by bkarlson** [vuetifyjs/vuetify#7576]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.25
**OS:** Mac OS 10.14.5

### Steps to reproduce
Normally: 
```css
.v-item-group.v-bottom-navigation .v-btn .v-btn__content>.v-icon {
    margin-bottom: 4px;
}
```

but wrapping a button icon in a badge breaks cascade and margin resets to 0:

```html
      <v-badge color="orange" overlap>
        <template v-slot:badge>
          100
        </template>
        <v-icon>
          star
        </v-icon>
      </v-badge>
```

Setting `class="ma-0"` to badgeless icons (or adding an empty badge) helps.

### Expected Behavior
Badges should not affect icons margins

### Actual Behavior
An icon wrapped in a badge gets different margin from normal icon.

### Reproduction Link
<a href="https://codepen.io/anon/pen/LKbYWR" target="_blank">https://codepen.io/anon/pen/LKbYWR</a>

### Other comments
In Vuetify 1.* it was not an issue I believe.

**Comment by johnleider** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/85ac7d47b5c9c20bc12c86c6f4543fdd1dcd0238
