### ISSUE TITLE
NavigationDrawer with sidebar updating parent controller variable

### ISSUE THREAD

**Issue by eliacamposilvan** [vuetifyjs/vuetify#758]
How can the NavigationDrawer component modify the variable that i pass on the v-model? 
From what I understand the overlayable component (that appears when the sidebar is open on small devices), when clicked, updates the "drawer" value to false. 
This should not be possible since vue doesn't support two-way bindings:

```html
<v-navigation-drawer persistent :mini-variant.sync="mini" light v-model="drawer">
   ...
<v-navigation-drawer>
```

Thanks!

**Comment by nekosaur** [comment]
Please direct questions to our [Gitter](https://gitter.im/vuetifyjs) instead.

Vue.js does support two-way bindings with the [v-model directive ](https://vuejs.org/v2/api/#v-model)
