### ISSUE TITLE
[Feature Request] [v2.0.0-beta.3] Ability to set v-btn content span's width to 100%

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#7580]
### Problem to solve
To be able to float v-btn content to either left or right.

This works fine in the stable version because width of content was relative to v-btn width

### Proposed solution
Solution 1: Add the ability to create your own v-btn__content container via slot scopes.

Solution 2: Attribute that make the v-btn__content class relative to the parent class.

**Comment by KaelWD** [comment]
Example of what you're doing in 1.5?

**Comment by JeremyWalters** [comment]
Hi @KaelWD please take a look at the image provided. So the button content looks as follows:
```
<v-flex class="text-xs-left">
	<span>{{ menu.name }}</span>
</v-flex>
<v-icon right color="grey">arrow_forward_ios</v-icon>
```

![image](https://user-images.githubusercontent.com/6836639/59834728-c398a500-9348-11e9-8909-2705ee81c647.png)

**Comment by KaelWD** [comment]
@johnleider Any particular reason for removing flex-grow?

https://github.com/vuetifyjs/vuetify/commit/18c8355ece3c539211ef511c7368959b662a6045#diff-728ee51df438a9601b3cf7b998c4a065L93

**Comment by johnleider** [comment]
This still doesn't really answer the question imho. Can you provide a codepen of what you were doing on 1.5?

**Comment by KaelWD** [comment]
That's clear enough to me. In 1.x btn__content had flex-grow so it filled the whole width.

**Comment by johnleider** [comment]
I understand now. I'll check as to why that was done.

**Comment by JeremyWalters** [comment]
Thanks guys! So far v2 is looking great!
