### ISSUE TITLE
[Bug Report] v-sparkline does not use custom labels for type bar

### ISSUE THREAD

**Issue by nikkon226** [vuetifyjs/vuetify#7584]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Try to add custom labels for any type="bar"

### Expected Behavior
Labels should be custom.

### Actual Behavior
Labels are only the graph values

### Reproduction Link
<a href="https://codepen.io/anon/pen/XLNgVJ" target="_blank">https://codepen.io/anon/pen/XLNgVJ</a>

### Other comments
Looking into it further, although the tests do pass, they are not actually showing the custom labels. Looking at the [spec](https://github.com/vuetifyjs/vuetify/blob/fe03a7a57da7b0262613f51950fe5ed546728b74/packages/vuetify/test/unit/components/VSparkline/VSparkline.spec.js#L115) and match it with the [snapshot](https://github.com/vuetifyjs/vuetify/blob/fe03a7a57da7b0262613f51950fe5ed546728b74/packages/vuetify/test/unit/components/VSparkline/__snapshots__/VSparkline.spec.js.snap#L362) you can see that none of the custom labels are rendered.

The [genBarLabels](https://github.com/vuetifyjs/vuetify/blob/fe03a7a57da7b0262613f51950fe5ed546728b74/packages/vuetify/src/components/VSparkline/VSparkline.ts#L386) function does not use the custom labels, it directly references the points.

**Comment by nikkon226** [comment]
Although I haven't tested it, it appears that [v2.0](https://github.com/vuetifyjs/vuetify/blob/9d4030ee1f7a035fe6a3b1a7900a1880d92dd829/packages/vuetify/src/components/VSparkline/VSparkline.ts#L386) has the same issue.

**Comment by sh7dm** [comment]
fixed in https://github.com/vuetifyjs/vuetify/commit/454235d53f157ef9fdc3669dc2e88970d148ed61
