### ISSUE TITLE
[Feature Request] v-select item-disabled as a function on the item

### ISSUE THREAD

**Issue by EBMike** [vuetifyjs/vuetify#7588]
### Problem to solve
allows each item to determine if its disabled dynamically

### Proposed solution
https://codepen.io/ebmike/pen/mZOxBM

**Comment by johnleider** [comment]
The best way to accomplish this would be to update that information in a computed property.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
