### ISSUE TITLE
[Bug Report] VAppBar does not adapt to the window width in combination with the mini variant VNavigationDrawer

### ISSUE THREAD

**Issue by erkan87** [vuetifyjs/vuetify#7589]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
Toggle the mini variant by clicking the app bar icon.

### Expected Behavior
The app bar should be adjusted to the window width and the elements after v-spacer should be visible.

### Actual Behavior
The toolbar does not adjust to the window width. The elements after v-spacer are not or only partially visible.

### Reproduction Link
<a href="https://codepen.io/Kayji/pen/zVojzw" target="_blank">https://codepen.io/Kayji/pen/zVojzw</a>

### Other comments
If the mini variant is true/false, the component adds the CSS style "left" instead of using it with a "padding-left". In vuetify v1 the component adds a "padding-left" to the style, in v2 it's adds a "left".

**Comment by johnleider** [comment]
This was fixed in beta.1 but reintroduced in beta.3. I've added a better fix in https://github.com/vuetifyjs/vuetify/commit/8d9b25e3b6ca18313c2a4db2b5a6dd9e34ac4eb5
