### ISSUE TITLE
[Bug Report] v-data-table with virtual-rows - rows don't update until next chunk is rendered

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#7591]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.90
**OS:** Linux x86_64

### Steps to reproduce
- Select all items
- Scroll the table

### Expected Behavior
All checkboxes should be ticked

### Actual Behavior
Row content only updates when the next scroll chunk is reached

### Reproduction Link
<a href="https://codepen.io/anon/pen/RzomVb" target="_blank">https://codepen.io/anon/pen/RzomVb</a>

**Comment by nekosaur** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by phifa** [comment]
also, `show-expand` does not work with `virtual-rows`. maybe you can add it to the issue.

**Comment by nekosaur** [comment]
Solved in https://github.com/vuetifyjs/vuetify/pull/16235
