### ISSUE TITLE
[Bug Report] css-loader upgrade breaks on vuetify components load

### ISSUE THREAD

**Issue by chaim0m** [vuetifyjs/vuetify#7592]
### Versions and Environment
**Vuetify:** 1.5.14
**Last working version:** 1.5.14
**Vue:** 2.6.7
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
```npm install css-loader@latest``` 
You will get the following error when trying to compile:
<div>error  in ./node_modules/vuetify/src/stylus/components/_time-picker-clock.styl

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
options should NOT have additional properties

    at validateOptions (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/dist/index.js:34:28)

 @ ./node_modules/vuetify/src/stylus/components/_time-picker-clock.styl 4:14-192 13:3-17:5 14:22-200
 @ ./node_modules/vuetify/lib/components/VTimePicker/VTimePickerClock.js
 @ ./node_modules/vuetify/lib/components/VTimePicker/VTimePicker.js
 @ ./node_modules/vuetify/lib/components/VTimePicker/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/main.js

 error  in ./node_modules/vuetify/src/stylus/components/_content.styl

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
options should NOT have additional properties

    at validateOptions (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/dist/index.js:34:28)

 @ ./node_modules/vuetify/src/stylus/components/_content.styl 4:14-182 13:3-17:5 14:22-190
 @ ./node_modules/vuetify/lib/components/VGrid/VContent.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/main.js

 error  in ./node_modules/vuetify/src/stylus/components/_lists.styl

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
options should NOT have additional properties

    at validateOptions (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/home/careboxdev/Projects/AdminApp/node_modules/css-loader/dist/index.js:34:28)

 @ ./node_modules/vuetify/src/stylus/components/_lists.styl 4:14-180 13:3-17:5 14:22-188
 @ ./node_modules/vuetify/lib/components/VList/VList.js
 @ ./node_modules/vuetify/lib/components/VList/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/main.js

 error  in ./node_modules/vuetify/src/stylus/components/_radios.styl
</div>
My configuration of the `css-loader` looks like this:
```
{
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, {loader: 'css-loader', options: { sourcemap: false }},{loader: 'postcss-loader', options: {sourcemap: false, plugins: [postCssCleanup] }}]
      },``` I tried adding `minimize: false` did not help.

### Expected Behavior
Proper compilation

### Actual Behavior
Will not compile

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by KaelWD** [comment]
We aren't responsible for your build configuration.
