### ISSUE TITLE
[Feature Request] [Docs] Fix Japanese translation of DataTable

### ISSUE THREAD

**Issue by ikedaosushi** [vuetifyjs/vuetify#7597]
### Problem to solve
Fixing Japanese translation of DataTable.

### Proposed solution
Fix `src/lang/ja-JP/components/DataTables.json`

**Comment by johnleider** [comment]
Translations should be contributed here: 
![image](https://user-images.githubusercontent.com/9064066/59855873-72ce7f80-933b-11e9-9886-f6c4d0dfb50c.png)
