### ISSUE TITLE
[Feature Request] [Docs] Create japanese translation for VPagination

### ISSUE THREAD

**Issue by TeXmeijin** [vuetifyjs/vuetify#7599]
### Problem to solve
There is no translation for Japanese of VPagination Docs.

### Proposed solution
Create japanese translation for VPagination.

**Comment by johnleider** [comment]
Contributions for language should be done here: 
![image](https://user-images.githubusercontent.com/9064066/59855801-4581d180-933b-11e9-9e13-a9fe07f424a3.png)
