### ISSUE TITLE
Label text is not taking into account prefix text

### ISSUE THREAD

**Issue by Kwal** [vuetifyjs/vuetify#760]
### Steps to reproduce
* Create a text field that has a prefix but no initial value

### Versions
Vue 2.3.4
Vuetify 0.12.7

### What is expected?
Label text takes into account the prefix

### What is actually happening?
Label text is overlaying the prefix text

### Reproduction Link
https://codepen.io/anon/pen/RgRXvV

**Comment by johnleider** [comment]
I'm not sure how what you posted is a reproduction link. That's the docs, post a codepen or jsfiddle. These requirements are listed as boilerplate when you post an issue.

**Comment by Kwal** [comment]
Apologies - although this does occur on the docs page itself, I've updated the issue with a codepen example.

**Comment by johnleider** [comment]
Thank you. Will get fixed tonight.

**Comment by johnleider** [comment]
Pushed fix for this to dev.
