### ISSUE TITLE
[Bug Report] Ripple effect happens twice in mobile browsers

### ISSUE THREAD

**Issue by syonip** [vuetifyjs/vuetify#7605]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Safari, Google Chrome
**OS:** iOS, Android

### Steps to reproduce
Just use any component with a ripple effect, and use a mobile browser - chrome on android or safari on ios.

### Expected Behavior
will show a ripple effect once on click, like on desktop browsers.

### Actual Behavior
ripple effect happens twice for each click

### Reproduction Link
<a href="https://codepen.io/syonip/pen/QXdvrv" target="_blank">https://codepen.io/syonip/pen/QXdvrv</a>

**Comment by WIStudent** [comment]
I am having this Issue also with version 1.5.16 (I think the linked demo in the pose above uses 1.5.16 too). Will this alos be fixed in an upcomming 1.5.x release or only in 2.0.0?

**Comment by hamedbaftam** [comment]
I am having this issue what should I do?

**Comment by syonip** [comment]
@hamedbaftam I solved it by upgrading to vuetify 2
