### ISSUE TITLE
[Feature Request] Fix documentation for changing Stylus variables

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#7606]
### Problem to solve
Official docs https://vuetifyjs.com/en/framework/theme#theme suggest 
to create a  `main.styl` file
```
// main.styl
@import '~vuetify/src/stylus/main' // Ensure you are using stylus-loader
```
and import it in main application
```
// index.js or main.js
import 'vuetify/dist/vuetify.min.css' // Ensure you are using css-loader
```
The link `import 'vuetify/dist/vuetify.min.css'` is wrong

### Proposed solution
1. The link `import 'vuetify/dist/vuetify.min.css'` should be changed to `import './stylus/main.styl'`
2. It would be nice to note that `import './stylus/main.styl'` should go after `import Vuetify from 'vuetify/lib'`, otherwise theme customisations won't work

**Comment by MajesticPotatoe** [comment]
Obsolete. Stylus is not longer used.
