### ISSUE TITLE
v-select not rendering properly inside v-stepper

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#761]
### Steps to reproduce
1. Use `vue-cli` with `webpack` as template
2. Add `vuetify`

### Versions
**vuejs** - `^2.3.3`
**vuetify** - `^0.12.7`

### What is expected ?
The select dropdown should show.

### What is actually happening ?
It doesn't. Instead, if I move the `<v-select></v-select>` to the different part of the template is shows up but in an odd position, sometimes in the middle but slightly offset to right. 

When I moved the `<v-select></v-select>` to the root of the template like : 
```
<template>
<div>
    <v-select></v-select> // this slighty works
    <v-container>
       // layout
       // flex
       // v-card
       <v-select></v-select> // this does not work
    </v-container>
</div>
</template>
```
I noticed the odd behavior when I used `webpack` template in `vue init`. Prior to this project, I used `webpack-simple` and everything works fine. 

Just an added note, `<v-divider></v-divider>` seems to be not working as well.

I'm highly confident that I haven't missed any closing tag because I am using `eslint`, otherwise it will not work.

### Reproduction Link
Here's the link to the drive with the video of the behavior. I added `.vue` file and the `package.json` as well. 

http://bit.ly/2tibL8a

**Comment by johnleider** [comment]
I see the video and the first thing that comes to mind is, are you using a v-app in your application?

**Comment by jofftiquez** [comment]
@johnleider No. No `<v-app>` anywhere in the app. My root component is just :

<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

**Comment by dohomi** [comment]
@jofftiquez can you wrap your root element into <v-app> ?

**Comment by jofftiquez** [comment]
@dohomi That's what I thought. :+1: Thanks. Sorry for the bother. Is this `<v-app></v-app>` tag mentioned in the docu?

**Comment by dohomi** [comment]
@jofftiquez yes it is here: https://vuetifyjs.com/layout/pre-defined

**Comment by jofftiquez** [comment]
Thank  you guys.
