### ISSUE TITLE
[Bug Report] Duplicated sentence in docs

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7611]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
On "Quick Start" page in vuetify docs https://vuetifyjs.com/en/getting-started/quick-start

this sentence

`
Unfortunately vue-cli-3 doesn't automatically bring IE11 compatibility in which you may encounter various errors (such as Symbol is not defined). To assist in resolving these errors you may need to manually add transpileDependencies parameter in vue.config.js
`

is duplicated. Exactly the same sentence is written below in blue alert

### Expected Behavior
The sentence should not be duplicated.

### Actual Behavior
The sentence is duplicated.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

![image](https://user-images.githubusercontent.com/17653648/59866631-5ad31c00-938c-11e9-810c-d7cc689ab054.png)

**Comment by jacekkarczmarczyk** [comment]
Fixed on `next` in <https://github.com/vuetifyjs/vuetify/commit/ffdb48c833ec040485d4b008510d9e1e6dca6408>
