### ISSUE TITLE
[Feature Request] VTreeview - item-disabled prop

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7612]
### Problem to solve
It'll allow to disable specific nodes, similar to VSelect

### Proposed solution
New prop

**Comment by jacekkarczmarczyk** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/ae15ed825837eac0134b336ed4219cc33faff9bb

**Comment by tvld** [comment]
@jacekkarczmarczyk  this "fix" also disables any click-event I might have on a label, which is not desirable, right?. 
For example: I like to show an info bubble when a user clicks on a (i) icon in any label, so also the disabled, of the tree node.
```js
<template v-slot:label="{ item }">
    <span>{{ item.title() }}</span>
    <v-icon @click.prevent="showHelp(item)">mdi-information-outline</v-icon>
</template>
```

**Comment by jacekkarczmarczyk** [comment]
Please create a new issue for this.
Although this is more general problem, all (or at least most) Vuetify components use `pointer-events: none` when disabled, same behaviour you can observe here <https://codepen.io/jkarczm/pen/NWqjZxP>

**Comment by tvld** [comment]
See #10708
