### ISSUE TITLE
Tabs not rendering properly after deletion

### ISSUE THREAD

**Issue by eclipseAce** [vuetifyjs/vuetify#762]
### Steps to reproduce
Use tabs like this
```xml
<div id="app">
  <v-tabs scroll-bars light v-model="current">
    <v-tabs-bar slot="activators">
      <v-tabs-item v-for="tab in tabs" :key="tab.id" :href="'#' + tab.id" @dblclick.native="closeTab(tab)">
        {{ tab.text }}
      </v-tabs-item>
      <v-tabs-slider></v-tabs-slider>
    </v-tabs-bar>
    <v-tabs-content v-for="tab in tabs" :key="tab.id" :id="tab.id">
      <v-card flat>
        <v-card-text>This is {{ tab.text }}</v-card-text>
      </v-card>
    </v-tabs-content>
  </v-tabs>
</div>
```
and the scripts
```javascript
export default {
  name: 'app',
  data() {
    return {
      tabs: [
        { id: 'item1', text: 'Item 1' },
        { id: 'item2', text: 'Item 2 blablablabla' },
        { id: 'item3', text: 'Item 3' },
        { id: 'item4', text: 'Item 4' }
      ],
      current: null
    }
  },
  methods: {
    closeTab(tab) {
      const index = this.tabs.indexOf(tab);
      this.tabs.splice(index, 1);
      const nextIndex = Math.min(index, this.tabs.length - 1);
      this.current = this.tabs[nextIndex].id;
    }
  }
}
```
Double click on tab 'ITEM 2 blablablabla...'
### Versions
Vue 2.3.4
Vuetify 0.12.7

### What is expected ?
Tab 'ITEM 3' should be focused

### What is actually happening ?
Tab 'ITEM 2 blablabla...' disappeared, but the length of slider bar was not changed and 'ITEM 3' was not focused

I've read the Tabs.js in src, I think the problem is the watcher of 'activeIndex' wasn't triggered when reducing tabs

### Reproduction Link
https://codepen.io/eclipseAce/pen/wezKNz

**Comment by johnleider** [comment]
Tabs doesn't (and cant) watch the length of its children.

**Comment by johnleider** [comment]
I see that you are working on a fork with potential changes, just make sure that you are basing these changes off of what exists in DEV as the structure is quite different.
