### ISSUE TITLE
[Feature Request] v-data-table - Scoped slot for "select all" checkbox

### ISSUE THREAD

**Issue by TullariS** [vuetifyjs/vuetify#7620]
### Problem to solve
On a website I am working on, I've had a request to add an "all" label next to the "select all" checkbox in a `v-data-table` header. Apparently some users did not notice it was there.

This website will be used by people that are not very good with computers, so not noticing that checkbox is there is not unreasonable.

### Proposed solution
Add a scoped slot to customise the checkbox. Possible props:
`{ indeterminate: boolean, all: boolean, toggle: function }`

**Comment by nekosaur** [comment]
This is available in the upcoming 2.0 release using slot `header.data-table-select`

**Comment by TullariS** [comment]
I just noticed that. Sorry for not checking first.

**Comment by kunalahirrao** [comment]
How to pass a specific value instead of true or false as i want value="item,mobileNo"
