### ISSUE TITLE
[Bug Report] V-select padding differs based on presence of value

### ISSUE THREAD

**Issue by stanzakh** [vuetifyjs/vuetify#7621]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Last working version:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
1. Create 2 v-selects in a form row
2. Select a value for one of them

### Expected Behavior
They should have the same padding and line up correctly regardless of whether it has a value or not.

### Actual Behavior
The selects do not match up.

### Reproduction Link
<a href="https://codepen.io/anon/pen/WqboGv" target="_blank">https://codepen.io/anon/pen/WqboGv</a>

**Comment by johnleider** [comment]
Resolved in https://github.com/vuetifyjs/vuetify/commit/4963f72fac3e5fbe1a6bfbfae132ddfa736a6a74
