### ISSUE TITLE
[Bug Report] [VDataTable] Mobile compatibility mode does not work well with the body slot

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#7625]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Reduce window size to mobile compatible mode.

### Expected Behavior
Well I am not sure if this is an bug or a feature. But I would expect the same behavior as the other slots. I understand that `tbody` element get replace with the `body` slot. But if that is not possible, the headers should be shown at least.  

### Actual Behavior
Headers disappear and row class dont get replaced by mobile compatible classes

### Reproduction Link
<a href="https://codepen.io/Jubels/pen/YoZXaM" target="_blank">https://codepen.io/Jubels/pen/YoZXaM</a>

**Comment by nekosaur** [comment]
The built-in mobile view is not just a few added classes, it's a different markup. If you override the body slot you will have to implement mobile view yourself. I did notice that `isMobile` variable was not passed to body slot but I just fixed that and it will be available in next beta.

**Comment by KaelWD** [comment]
Is there a prop to disable the mobile header? You might want to still use a table on mobile but the default header gets replaced with a select.

**Comment by nekosaur** [comment]
perhaps not super intuitive but you can set `mobile-breakpoint` prop to `0`

**Comment by JeremyWalters** [comment]
> The built-in mobile view is not just a few added classes, it's a different markup. If you override the body slot you will have to implement mobile view yourself. I did notice that `isMobile` variable was not passed to body slot but I just fixed that and it will be available in next beta.

Will it be possible to maybe add an example to the documentation how the mobile view should look to be identical to the default mobile view?

**Comment by nekosaur** [comment]
I would first ask what the reason is for needing to override the body slot.

**Comment by JeremyWalters** [comment]
Yes generally its just for row clicks. I also used it for custom components in columns like checkbox, buttons, text-field etc. **But** I can use `item.<name>` for custom components. So I believe [#7578] (https://github.com/vuetifyjs/vuetify/pull/7578) would solve the problem. Thank you, #7578 would save me a lot time.

**Comment by KaelWD** [comment]
You can also use the `item` slot to do the whole row in one place.

**Comment by JeremyWalters** [comment]
@KaelWD Yes I can `item` slot, but then I loose mobile compatibility. With `item.<name>` I don't.
