### ISSUE TITLE
[Bug Report] The button disappears if transmitted the dark and disabled props.

### ISSUE THREAD

**Issue by vladstarikov88** [vuetifyjs/vuetify#7626]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Opera 60.0.3255.83
**OS:** Linux x86_64

### Steps to reproduce
You should set dark property and then disabled

### Expected Behavior
The button should be visible

### Actual Behavior
The button disappear if I set disable property

### Reproduction Link
<a href="https://codepen.io/vladstarikov88/pen/pXeNOw" target="_blank">https://codepen.io/vladstarikov88/pen/pXeNOw</a>

**Comment by vladstarikov88** [comment]
The same situation with Firefox and Chrome on the latest version

**Comment by johnleider** [comment]
The **dark** prop doesn't mean _turn my button text white_. Dark and light variants have different disabled colors. Don't use dark buttons on a light background.

https://codepen.io/johnjleider/pen/VJpbeG
