### ISSUE TITLE
Autocomplete update:searchInput creates infinite Events on blur

### ISSUE THREAD

**Issue by woodgates** [vuetifyjs/vuetify#7631]
Hi.
I'm trying to update items to show on the autocomplete calling the items from a server. But everytime I select an item and then blur the update:searchInput event gets fired forever.

      <autocomplete
      name="test"
      id="test"
      v-model="test"
      :items="activities"
      :search-input.sync="search"
      cache-items
      item-text="short_name"
      item-value="slug"
      @update:searchInput="updateActivity"
      ></autocomplete>

method:
      updateActivity(data){
        if(data){
          axios.get('activities',{
            params:{
              filter:data
            }
          }).then((response)=>{
            this.activities = response.data
          })
        }   
      }

**Comment by Kleemer** [comment]
@woodgates did you fix this by any chance? Currently using version 1.5.20 and having the same problem, if not I will open a codepen.

**Comment by thomaslecoeur** [comment]
+1
