### ISSUE TITLE
[Feature Request] v-slider: option to set a precision for step

### ISSUE THREAD

**Issue by scottg521** [vuetifyjs/vuetify#7632]
### Problem to solve
Ability to have a stepped slider where the steps are rounded to numbers other than 1

For example, for a range of 2 - 9,999,999 with a step of 100,000, you end up with stepped values like 100,002 rather than 100,000, with no way to change that. The point of having steps is that most people who want to narrow the range will want numbers at even values.

### Proposed solution
Add a "step-precision" option to v-range-slider and v-slider to set the rounding precision. For example, a step-precision of 10 would mean that you get numbers rounded to the nearest 10, so in the example above you would have 100,000, 200,000, etc. rather than 100,002, 200,002, etc.

MDN Web Docs for Math.round() gives an example of an algorithm for rounding to numbers other than 1 ([https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round])

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
