### ISSUE TITLE
[Bug Report] Bar sparkline does not render negative values properly

### ISSUE THREAD

**Issue by pras2015** [vuetifyjs/vuetify#7636]
### Versions and Environment
**Vuetify:** 1.5.16, 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Linux, Windows

### Steps to reproduce
Set the sparkline type to "bars" to render a bar sparkline
Set one of the values in the values array to negative. 

### Expected Behavior
There should be a negative bar in the sparkline
The chart should display a bar going in the negative direction from the baseline x-axis

### Actual Behavior
all bars are positive

### Reproduction Link
<a href="https://codepen.io/anon/pen/PrpgNE?editors=1010#0" target="_blank">https://codepen.io/anon/pen/PrpgNE?editors=1010#0</a>

**Comment by sh7dm** [comment]
Present in `v2.0.0-beta.3`: https://codepen.io/sh7dm/pen/wLegbd?editors=1010

**Comment by sh7dm** [comment]
Fixed in f8d180cd9. @pras2015 thanks for reporting this!

**Comment by sh7dm** [comment]
This fix will be available today with `v2.0.0-beta.4`

**Comment by pras2015** [comment]
@sh7dm Thanks for the quick update. But there seems to be a bug in the implementation. Please refer to the following pen

https://codepen.io/anon/pen/jjGqVQ?editors=1010

-33, -6, -1 seem to be rendering same sized bars and only 4 values are showing up from an array of 5 values.

Should I open a new bug report for this?

**Comment by nekosaur** [comment]
There is a further fix for negative values on the way https://github.com/vuetifyjs/vuetify/pull/7664
