### ISSUE TITLE
[Bug Report] The v-btn-toggle doesn't support outline buttons well

### ISSUE THREAD

**Issue by dominik-korsa** [vuetifyjs/vuetify#7640]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Place multicolored outline buttons in v-btn-toggle with "multiple" prop.

### Expected Behavior
Dividers between buttons should match the color of the buttons, no grey divider is shown between colored buttons. A colored divider is always shown if it's adjacent to an active button. 

### Actual Behavior
A colored divider (technically border in this case) is only shown if a button is on the right side of the divider and not when a button is only on the left side. *(In the pen mainly: `1`, `2`, `3`, `2 3`)*

A grey divider is shown between two buttons *(`1 2`, `2 3`, `1 2 3`)*

A grey divider is shown even if the two buttons aren't *touching* *(`1 3`)*

### Reproduction Link
<a href="https://codepen.io/dominik-korsa/pen/GbmjYd" target="_blank">https://codepen.io/dominik-korsa/pen/GbmjYd</a>

### Other comments
The pen also includes a no-elevation version, which in my opinion fits the outline buttons well.

**Comment by johnleider** [comment]
It's not intended to. We have added some more flexibility in v2.0 but ultimately this component isn't very configurable outside of the MD specification.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
