### ISSUE TITLE
[Bug Report] Using Vuetify with i18n using CDNs only

### ISSUE THREAD

**Issue by ZimGil** [vuetifyjs/vuetify#7644]
### Versions and Environment
**Vuetify:** 1.5.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.90
**OS:** Windows 10

### Steps to reproduce
Create a Vue + Vuetify + Vue-i18n app with only CDNs, no build.
Add translation to Vuetify (data table specifically) 

### Expected Behavior
See the `Rows per page` translated

### Actual Behavior
`Rows per page` in not translated, nor any vuetify text.
Other translated text is translated 

### Reproduction Link
<a href="https://codepen.io/7uP/pen/JQXbWG?editors=1010" target="_blank">https://codepen.io/7uP/pen/JQXbWG?editors=1010</a>

### Other comments
I've tried using `Vue.use()` but no effect, also I couldn't `import` Vuetify to `Vuetify.install()`
No errors in the console, no translation.

**Comment by johnleider** [comment]
This is not possible in v1.5 due to how Vuetify is bootstrapped. However, we rebuilt that process for v2.0 and is now possible. https://codepen.io/johnjleider/pen/RzgGPR?editors=1011

**Comment by ZimGil** [comment]
> This is not possible in v1.5 due to how Vuetify is bootstrapped. However, we rebuilt that process for v2.0 and is now possible. https://codepen.io/johnjleider/pen/RzgGPR?editors=1011

Cool! But I can't seems to import `Vuetify` from `vuetify.js` cdn file
