### ISSUE TITLE
[Bug Report] [VNavigationDrawer] Margin-top is not adjusted when VLayout is scrollable

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#7645]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Have a VNavigationDrawer with the `app` prop.
Have a VLayout which is scrollable.
Scroll VLayout to bottom

### Expected Behavior
Drawer `margin-top` should be adjusted if VAppBar is not fixed.

### Actual Behavior
Margin top stays : `margin-top: 64px;` and causes  white gap between the drawer and top window.

### Reproduction Link
<a href="https://codepen.io/Jubels/pen/OemdVa" target="_blank">https://codepen.io/Jubels/pen/OemdVa</a>

### Screenshot
![image](https://user-images.githubusercontent.com/6836639/59998392-90635800-965f-11e9-8b4f-2f9adb00256a.png)

**Comment by johnleider** [comment]
The codepen you provided is for v1.5. Your use-case is now possible in v2, https://codepen.io/johnjleider/pen/orwLwV

**Comment by JeremyWalters** [comment]
My apologies. The` https://next.vuetifyjs.com/en/examples/layouts/google-keep` example's codepen package still point to v1.5.

I see one get the issue if the `VAppBar` has the attribute `absolute` instead of `hide-on-scroll`. 
https://codepen.io/Jubels/pen/pXwwRP. Will use `hide-on-scroll` from now on.

Thanks for the trouble.
