### ISSUE TITLE
[Bug Report] Icons not visible in v-data-table header when using custom header

### ISSUE THREAD

**Issue by ianbarker** [vuetifyjs/vuetify#7647]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
Add a v-autocomplete or v-select to a custom header slot (e.g. header.iron) then sort the data table by another column (e.g. calories).

### Expected Behavior
The icons that are part of the v-autocomplete or v-select should always be visible.

### Actual Behavior
The icons are only visible if the column is currently being sorted by

### Reproduction Link
<a href="https://codepen.io/anon/pen/dBRMGV?editors=1010" target="_blank">https://codepen.io/anon/pen/dBRMGV?editors=1010</a>

**Comment by johnleider** [comment]
This is a very interesting use-case, @nekosaur thoughts?

**Comment by ianbarker** [comment]
Haha thanks. We use it to for filtering on the columns, I didn't bother to build the filters for the example though.

**Comment by nekosaur** [comment]
yeah we're too liberal when targeting the built-in sort icons in the css. there's another issue where non-sort icons get rotated as well

**Comment by Daaron3** [comment]
Check if you have correctly installed the icons.

```
Vue.use(Vuetify, {
    icons: {
        iconfont: 'fa'
    }
});
```
