### ISSUE TITLE
[Feature Request] Slider component docs do not mention the 'thumb-label' slot

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#7648]
### Problem to solve
The functionality exists to customise the content in the slider thumb label but there is no documentation for it.

### Proposed solution
Add the docs on https://vuetifyjs.com/en/components/sliders#custom-range-slider.
It should appear in a 'Slots' tab. The code for the slot is here: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSlider/VSlider.js#L387

**Comment by jacekkarczmarczyk** [comment]
Missing in 1.5 docs, fixed in 2.0 https://next.vuetifyjs.com/en/components/sliders

**Comment by btbritz** [comment]
For a range slider component is there a way to target both the first and second thumb label via a slot definition? Right now if I use _v-slot:thumb-label_ it overwrites the thumb label for both thumbs.
