### ISSUE TITLE
v-dialog still opens even if activator has disabled props

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#765]
### Versions

**Vue** - `^2.3.3`
**Vuetify** - `^0.12.7`

### What is expected ?

Dialog shouldn't open.

### What is actually happening ?

It does open even if the `v-btn` activator was set to `disabled`

### Reproduction Link

https://jsfiddle.net/greenfoxx/wcwdfqgu/

**Comment by johnleider** [comment]
This is because the activator slot wraps the element. The disabled button isn't what is propagating the click, the activator slot is. There are two ways you can solve this. Don't use the activator slot, or, the preferred method, add the disabled prop to the actual dialog.

**Comment by jofftiquez** [comment]
:100: Thanks @johnleider
