### ISSUE TITLE
[Bug Report] v2: Elevation-0 doesn't remove elevation like in v1

### ISSUE THREAD

**Issue by fbrbovic** [vuetifyjs/vuetify#7652]
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Apply elevation-0 class to an element

### Expected Behavior
Should not show any elevation

### Actual Behavior
Showing shadow / elevation

### Reproduction Link
<a href="https://codepen.io/anon/pen/mZwqKy?editors=1010" target="_blank">https://codepen.io/anon/pen/mZwqKy?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
fixed in 111d7773122f0c79703a0b58b2430cb43f0e7816
