### ISSUE TITLE
[Bug Report] VTabs with mandatory doesn't route to first item 

### ISSUE THREAD

**Issue by pasibonfire** [vuetifyjs/vuetify#7660]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Other
**OS:** Windows 10

### Steps to reproduce
Run the app with VTabs, with `to` prop set to routes.

### Expected Behavior
First tab should show slider AND `$route.path` should be the first item's path AND correct component should be shown.

### Actual Behavior
First tab shows slider, but the path doesn't change, or the component is not shown

### Reproduction Link
<a href="https://codepen.io/pasibonfire/pen/NZgVzZ" target="_blank">https://codepen.io/pasibonfire/pen/NZgVzZ</a>

### Other comments
Is this normal behavior? Workaround possible with route `alias` or `redirect`

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
