### ISSUE TITLE
[Feature Request] v-select disabled props can accept 0 and 1 values 

### ISSUE THREAD

**Issue by albertostiip** [vuetifyjs/vuetify#7662]
### Problem to solve
These are the items that I pass as a prop to v-select: (from JSON API)
{
    product_id: 1,
    name: "ACT - DATI FONIA",
    subtitle: "simple",
    barcode: null,
    disabled: 0
}

The items collection is extracted from a mysql database so 'disabled' takes values of 0 and 1 instead of true or false. 

This is the Warning I receive:

[Vue warn]: Invalid prop: type check failed for prop "disabled". Expected Boolean, got Number with value 0.

and it is the same if I transform 0 and 1 into strings 'true' or 'false'.

### Proposed solution
It would all be easier if the disabled prop could accept numeric values 0 and 1 intended as true and false.

**Comment by jacekkarczmarczyk** [comment]
`disabled` in items definitely doesn't show this error message, it's only for props

**Comment by johnleider** [comment]
My suggestion would be to either cast it from your query to a bool, do the conversion server side or create a computed property that modifies it.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
