### ISSUE TITLE
[Feature Request] validate v-stepper-step

### ISSUE THREAD

**Issue by dhiegohenrique** [vuetifyjs/vuetify#7663]
### Problem to solve
I have a question: I created some steps using v-stepper-step. Each step has a validate method that returns true or false and is invoked through ref. There is a forward button. I would like to know how to invoke validation and make it checked in v-stepper that there are errors in that step and also block the feed. Anyone have an idea?

### Proposed solution
Invoke validation of meaning and prevent progress if there are errors

**Comment by LNAline** [comment]
Hi, I am looking for that feature too =)

It's amazing that you can put rules to show errors for each step, but it could be better if we could avoid the user to change the current step if the current form isn't validated (by using a rule too or whatever)

I tried some things, like catching click on editable step and checking current step validation to block or allow the step to change. But I couldn't make it, I can't avoid the step to change when it's changed on editable step.

Thanks in advance for the feature or for help !

**Comment by Beatriz-Sanchez** [comment]
Also looking for that feature. It would also be nice if you could check the whole stepper for any steps in it that didn't pass the rules. That would be perfect

**Comment by johnleider** [comment]
This is supported in v3 through the **rules** prop: https://vuetifyjs.com/en/api/v-stepper-item/#props-rules
