### ISSUE TITLE
[Bug Report] [v-combobox] Making values case insensitive

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#7666]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Try to insert "VIP", "vip", "Vip" it creates 3 selected items. In my case I want it to insert only the one Matched so all three should result in one "VIP". 

### Expected Behavior
When the search term matches one of the items that are highlighted it should insert them, not a new one when the new one is different in case sensitivity.

### Actual Behavior
Inserts 3 different values

### Reproduction Link
<a href="https://codepen.io/anon/pen/PrKbVX?editors=1111" target="_blank">https://codepen.io/anon/pen/PrKbVX?editors=1111</a>

### Other comments
Tried using the value-comparator https://codepen.io/anon/pen/KjvaRW?editors=1111
but it acts weirdly. Try inserting "vip" then "VIP", it will delete both.

**Comment by CodeSkills** [comment]
First example: 
![preview](https://user-images.githubusercontent.com/3975293/60108141-68abe700-9768-11e9-9f84-e94e630a14d6.gif)

Second example:
![preview2](https://user-images.githubusercontent.com/3975293/60108148-6b0e4100-9768-11e9-842e-57c42f299db8.gif)

**Comment by jacekkarczmarczyk** [comment]
Related to https://github.com/vuetifyjs/vuetify/issues/3194

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
