### ISSUE TITLE
[Bug Report] Custom components inside data-tables are rendered only for the first page of results

### ISSUE THREAD

**Issue by theCrius** [vuetifyjs/vuetify#7667]
### Versions and Environment
**Vuetify:** 1.5.14 (but tested with the latest version as well)
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
I started from the example of data table in the vuetify documentation website.

Create a simple custom component like I did in the codepen. Change page in the datatable and you'll see that the values are passed only for the first page of rows.

I added a console log for the created() and and updated() hooks as well so you can see that the only component created are the one on the first page. Changing page does not create new components.

### Expected Behavior
The components being created/updated on every page change.

### Actual Behavior
Only the components in the first page are created.

### Reproduction Link
<a href="https://codepen.io/thecrius/pen/WqEpOX?editors=1010" target="_blank">https://codepen.io/thecrius/pen/WqEpOX?editors=1010</a>

### Other comments
I tried looking online for similar issues but I'm fairly new with Vue and could have failed to find the proper google-fu.

If there is a proper way to approach this, please point me in the right direction even just with a link, thanks.

**Comment by jacekkarczmarczyk** [comment]
Rows must be keyed, use `item-key="name"` (or instead of `name` use any unique prop from your items)

I'll leave this issue open as a documentation issue as it's not properly described in the docs

**Comment by theCrius** [comment]
For the complete new to vue and vuetify, this is the change needed:

```
<v-data-table
      :headers="headers"
      :items="desserts"
      item-key="name"
      class="elevation-1"
    >
```

Just change `name` with an attribute of the array of objects that is being iterated by data-tables that you can rely on being unique.

Thank you for the blazing fast response @jacekkarczmarczyk :)
