### ISSUE TITLE
[Bug Report] v-tabs-slider

### ISSUE THREAD

**Issue by bruno-ab** [vuetifyjs/vuetify#7669]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.5.16
**Browsers:** Chrome 75.0.3770.90
**OS:** Linux x86_64

### Steps to reproduce
when use v-tab the and click in another tab , the url changes and the slider changes too.But after change the tab if i reloaded the page the slider goes to the first tab position and not the current.

### Expected Behavior
v-tab slider change according to the tab url

### Actual Behavior
v-tab slider goes to the first tab after reload page

### Reproduction Link
<a href="https://codepen.io/morgenstern_/pen/wLqraX" target="_blank">https://codepen.io/morgenstern_/pen/wLqraX</a>

**Comment by KaelWD** [comment]
It isn't magic, you need to tell the tab what its URL is with `to` or `href` instead of the click handler.
