### ISSUE TITLE
[Feature Request] Option for showing CRUD actions on hover only

### ISSUE THREAD

**Issue by jaminroe** [vuetifyjs/vuetify#7670]
### Problem to solve
A common pattern you'll usually see for tables these days, is showing CRUD type actions/icons when hovering over the row only. Think of most modern email apps. This also helps alleviate a lot of repetitive visual clutter in tables. If we want to do this now, we have to hack something together to make this work across all of our many different data tables in our complex products.

### Proposed solution
Having an option/attribute that we could add to the data tables API so this behavior becomes present, would be really nice to have. I'm envisioning the Actions column would show as blank first, then the icons show as the hover interaction happens on that row.

### Note
Not sure how I take advantage of this, but my company is a Palladium level sponsor - Fractal Industries. I can provide you my work email if you need it too. Our CEO or CTO was the one that made the sponsorship, but they obviously don't have time to do these types of requests for us. I'm the Senior Product Designer here :) Thanks!

**Comment by KaelWD** [comment]
This depends on your project structure of course, but if you have a common wrapper component for crud tables it shouldn't be too hard to do. 
Using CSS, all I added in the template was a class: https://codepen.io/anon/pen/mZMNZW
Or using v-hover: https://codepen.io/anon/pen/JQygeP?editors=1000

We have a channel on discord for sponsors, just ask john or myself to give you access.

**Comment by jaminroe** [comment]
> This depends on your project structure of course, but if you have a common wrapper component for crud tables it shouldn't be too hard to do.
> Using CSS, all I added in the template was a class: https://codepen.io/anon/pen/mZMNZW
> Or using v-hover: https://codepen.io/anon/pen/JQygeP?editors=1000
> 
> We have a channel on discord for sponsors, just ask john or myself to give you access.

Oh wow, excellent!! I really appreciate the help. I'm going to forward this to the engineering team. I'll be sure to ask one of you for access to the discord channel, as well as for a couple of our engineers. Thanks!
