### ISSUE TITLE
[Feature Request] Support jetbrains web-types standard

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#7674]
### Problem to solve
Code completion and hints in jetbrains IDEs

### Proposed solution
Publish a web-types.json file to npm and link it in package.json

https://github.com/JetBrains/web-types
https://youtrack.jetbrains.com/issue/WEB-31682#comment=27-3538850

**Comment by vaibhavhrt** [comment]
@KaelWD Looking to contribute, since it's labelled `good first issue` I guess it should be easy enough. I am new to vue and vuetify (coming from React and [mui-org/material-ui](https://github.com/mui-org/material-ui)) so some help will be appreciated.

**Comment by vaibhavhrt** [comment]
Unless it's already done as I see there is json for various versions of vuetify already on JetBrains/web-types repo.

**Comment by DRoet** [comment]
@vaibhavhrt I think the idea is to create a script that automatically generates a new `web-types.json` file for every new vuetify release in the future.

The files located in `JetBrains/web-types` have been generated by the jetbrains team and might fall out of date eventually

**Comment by KaelWD** [comment]
We already have `packages/api-generator` for the documentation and vscode, so this would just be an addition to that to output a different format.

**Comment by vaibhavhrt** [comment]
@KaelWD thanks, I will take a look at it when I get home after work.

**Comment by vaibhavhrt** [comment]
@KaelWD , I have set up development environment and took a look at the api-generator code. It's quite a bit of code so might take a while to figure out whats going on and what to add to create one more file, so please be patient, it might take me a while before I open a PR.

**Comment by vaibhavhrt** [comment]
nvm created a PR, it's work in progress but created PR anyway so  that I can receive some help and feedback.
