### ISSUE TITLE
[Feature Request] Add possibility to add custom classes to v-select item

### ISSUE THREAD

**Issue by sayhicoelho** [vuetifyjs/vuetify#7676]
### Problem to solve
The possibility to add custom classes to v-select items when you need to make the item display: flex to justify-content: space-between or anything else.

### Proposed solution
Add v-select and v-autocomplete `item-class` prop.

Please see what I need to do with this feature request: ![image](https://user-images.githubusercontent.com/8188365/60196884-9189b600-9814-11e9-83ba-44131fb20224.png)

Note: To align the chips to the right, I just changed using browser inspector.

**Comment by myleslee** [comment]
It can be achieved by using slots to customize the item's look and feel. It's much more than just the 'item-class' approach. @sayhicoelho 

sample code: https://codepen.io/myleslee/pen/dBZLEx

<img width="553" alt="Screen Shot 2019-06-28 at 10 30 55" src="https://user-images.githubusercontent.com/108758/60313100-61ffb880-9990-11e9-9561-76f547694e2e.png">

**Comment by sh7dm** [comment]
@myleslee I think so. @sayhicoelho you can use slots for your purposes.

**Comment by sh7dm** [comment]
Easily replaceable with slots: https://codepen.io/anon/pen/RzEwyJ?editors=1010
