### ISSUE TITLE
[Bug Report]  v-chip close not working

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#7680]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux

### Steps to reproduce
click the close button

### Expected Behavior
chip is gone

### Actual Behavior
no effect

### Reproduction Link
<a href="https://codepen.io/gadelkareem/pen/dBVQpd" target="_blank">https://codepen.io/gadelkareem/pen/dBVQpd</a>

**Comment by johnleider** [comment]
fixed in f9eadbe9b8919be73e6a14ac388dc054fdf1ebad
