### ISSUE TITLE
[Enhancement] v-radio-group color not working

### ISSUE THREAD

**Issue by brendanmatkin** [vuetifyjs/vuetify#7681]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Applying color to individual v-radio components works: `<v-radio color="red"> ...`
but applying to v-radio-group does not `<v-radio-group color="red"> ...`

### Expected Behavior
Change the color of all the radio buttons in the group.

### Actual Behavior
No effect.

### Reproduction Link
<a href="https://codepen.io/anon/pen/bPoPQG?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/bPoPQG?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Moving this to an enhancement as it was never functionality that existed in the framework.

**Comment by brendanmatkin** [comment]
Sounds good - maybe remove the prop from the documentation until it gets implemented?

**Comment by johnleider** [comment]
My apologies, did not catch that.
