### ISSUE TITLE
[Bug Report] Badge doesn't work in a v-list-item-avatar

### ISSUE THREAD

**Issue by bigplum** [vuetifyjs/vuetify#7682]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.9
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
As this code shows, I want to place a badge on the top of the avatar. 

```html
          <v-list-item-avatar>
            <v-badge
              color="purple"
              overlap
              right
            >
              <template v-slot:badge>
                <span v-if="item.messages > 0">{{ item.messages }}</span>
              </template>
              <v-img :src="item.avatar"></v-img>
            </v-badge>

          </v-list-item-avatar>
```

### Expected Behavior
I want to place a badge on the top of the avatar. 

### Actual Behavior
The badge doesn't show, and the avatar become a larger icon.

### Reproduction Link
<a href="https://codepen.io/bigplum/pen/NZaQVa" target="_blank">https://codepen.io/bigplum/pen/NZaQVa</a>

**Comment by Billybob** [comment]
Meanwhile better

```
<v-list-item-avatar>
  <v-badge
    color="purple"
    overlap
    right
  >
    <template v-slot:badge>
      <span v-if="item.messages > 0">{{ item.messages }}</span>
    </template>
    <v-avatar size="36">
      <v-img :src="item.avatar"></v-img>
    </v-avatar>
  </v-badge>

</v-list-item-avatar>
```

**Comment by bigplum** [comment]
@Billybob It works, well done, thanks.

**Comment by uuf6429** [comment]
This doesn't work for me with `v-list-item-avatar` inside a `v-list-group`.
