### ISSUE TITLE
[Bug Report] The images of the caroussel stop displaying when used with tabs. How can I solve it?

### ISSUE THREAD

**Issue by yonvela20** [vuetifyjs/vuetify#7686]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
First both tabs work properly. If you wait in the main tab 10-15s and then switch to the second tab, which has a caroussel, the images are not displaying anymore. 

### Expected Behavior
The caroussel tab should be displaying the images no matter the time you spend in the first tab. 

### Actual Behavior
Both tabs work properly until you spen some time in the first tab then the caroussel stops displaying images

### Reproduction Link
<a href="https://codepen.io/yonvela20/pen/vqWOYG" target="_blank">https://codepen.io/yonvela20/pen/vqWOYG</a>

**Comment by buqiyuan** [comment]
you can set the css like this:
```
.v-window__container{
      height: 100%!important;
    }
    .v-carousel__item{
      height: 100%!important;
    }
```

**Comment by yonvela20** [comment]
Yup, that worked for me! Thank you so much @buqiyuan <3

**Comment by johnleider** [comment]
This has been resolved as of v2.
