### ISSUE TITLE
[Bug Report] V-Icon. Fonts ligatures are translated by inbrowser translater

### ISSUE THREAD

**Issue by heggi** [vuetifyjs/vuetify#7689]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 7

### Steps to reproduce
1. Google Chrome do not translate iframe in jsfiddle.net, so open link https://fiddle.jshell.net/feb9qxsy/1/show/
2. Click right mouse button and select "Translate to ..." in popup menu (In my browser Translate to Russian, but I think it will work with any non latin languages)

### Expected Behavior
Icons stay as is

### Actual Behavior
First icon is broken, because text "menu" was translated to other language (russian in my situation)
Second icon is not broken, because it has class "notranslate", which prevents translation text to other language

### Reproduction Link
<a href="https://jsfiddle.net/feb9qxsy/1/" target="_blank">https://jsfiddle.net/feb9qxsy/1/</a>

### Other comments
Component v-icon must have class "notranslate" by default.

**Comment by hfoletto** [comment]
Will this be fixed in v1.5?
