### ISSUE TITLE
[Feature Request] Add API docs to Dash

### ISSUE THREAD

**Issue by juddlyon** [vuetifyjs/vuetify#7690]
### Problem to solve
Making the excellent Vuetify documentation available to Dash enables offline searching, bookmarking, and annotation. Vue is already included, along with dozens of other JS projects.

### Proposed solution
There are a number of accepted documentation formats, including HTML: https://kapeli.com/docsets

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Sandural** [comment]
I  think api docs to dash  is very good idea 😄
