### ISSUE TITLE
[Bug Report] [2.0.0] Virtualized rows scrolling behaves glitchy

### ISSUE THREAD

**Issue by DanielRivers** [vuetifyjs/vuetify#7691]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Note: The codepen above is an unedited pen from the vuetify docs.  

Scroll up and down using mouse wheel
More prevalent when scrolling to the bottom then trying to scroll up again

### Expected Behavior
Normal smooth scroll behaviour, that of a non virtual row table

### Actual Behavior
glitchy scrolling, data flickering and the scroll bar doing its own thing.

http://recordit.co/maXN4kBY7H

### Reproduction Link
<a href="https://codepen.io/DanielRivers/pen/agEdEK" target="_blank">https://codepen.io/DanielRivers/pen/agEdEK</a>

**Comment by grishnyakov** [comment]
It would be great if a v-simple-table also supported virtual rows

**Comment by nekosaur** [comment]
Unable to reproduce in v3
