### ISSUE TITLE
Need help with vuetify datatable - table without hard code column and expandable

### ISSUE THREAD

**Issue by dineshvinay** [vuetifyjs/vuetify#7696]
Below is the links which have solution for table without hard code columns, but I need it combined with expandable rows

https://top10webjs.com/2019/02/18/vue-js-vuejs--vuetify---possible-to-dynamically-load-a-data-table-without-having-to-hard-code-the-columns/

https://codepen.io/anon/pen/daQbrE?&editable=true&editors=101

**Comment by softmarshmallow** [comment]
official example needs to be provided for dynamic table rendering
