### ISSUE TITLE
[Bug Report] VDataTable Items Per Page Options Is Not Working

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#7700]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Using the first VDataTable example in the documentation

I set the option to [5, 20, 50]

### Expected Behavior
rows per page should show 5, 20, 50, ALL as dropdown options

### Actual Behavior
it shows 5, 10, 15, ALL which is the default setting

### Reproduction Link
<a href="https://codepen.io/ais-one/pen/xoYORw" target="_blank">https://codepen.io/ais-one/pen/xoYORw</a>

**Comment by ais-one** [comment]
My bad, I am closing this issue. I found the correct way to do it...

https://next.vuetifyjs.com/en/components/data-tables#footer-props

**Comment by junyan-lin** [comment]
<v-data-table
:footer-props="{
          itemsPerPageOptions: [100,200]
}"

**Comment by mikepizzica** [comment]
for the latest vuetify, this worked for me:

```javascript
<v-data-table
:items-per-page-options="[
      { value: 100, title: '100' },
      { value: 200, title: '200' },
    ]"
```
