### ISSUE TITLE
[Bug Report] Progress components can show choppy or incorrect progress

### ISSUE THREAD

**Issue by kaliatech** [vuetifyjs/vuetify#7705]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Change the progress property of progress components (linear or circular) frequently, and then visually observe the progress determinate indication and transition animation.

### Expected Behavior
The progress determinate should quickly and smoothly try to go to the mostly recently given progress value. 

### Actual Behavior
The progress indicator updates sporadically and often doesn't reflect the given progress value.

Some level of inaccuracy is expected when the progress updates are changing faster than the transition animation duration. However,  currently discrepancies appears to quickly compound, and in many cases, the animation is never smooth. 

### Reproduction Link
<a href="https://codepen.io/kaliatech/pen/NZywmJ" target="_blank">https://codepen.io/kaliatech/pen/NZywmJ</a>

### Other comments
This issue was split from #3453.  An example use case would be when using the progress component to display the playback progress of a media element, where progress value is being driven by frequent media playback progress events.

Possible workarounds:
 * Throttle progress property updates
 * Disable the CSS transition of the progress bar determinate

Given the workarounds, this might be considered a feature request rather than a bug.

Expectations for how this should be handled, while keeping smooth transitions, might not be obvious. Other options might be to simply document this as a limitation when using the default transitions, and/or provide an easier way disable transitions for these components for certain use cases.

**Comment by johnleider** [comment]
This won't make it for v2.0 but I have intentions of resolving this as a bug fix in a future patch.

**Comment by johnleider** [comment]
After digging into this a little, I think it might be best to leave in userland.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
