### ISSUE TITLE
[Bug Report] word-wrap isn't working for table headers

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#7713]
### Versions and Environment
**Vuetify:** 1.5.16
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
set width/class with word-wrap for table header with long text 

### Expected Behavior
long text is wraps

### Actual Behavior
long text isn't wrap

### Reproduction Link
<a href="https://codepen.io/skortabeast/pen/PrQLJE" target="_blank">https://codepen.io/skortabeast/pen/PrQLJE</a>

**Comment by jacekkarczmarczyk** [comment]
You need to set white-space as well https://codepen.io/anon/pen/XLZGEW

**Comment by skortabeast** [comment]
@jacekkarczmarczyk  
thanks for answer, its works, but when use word-wrap with your method, horizontal scrolling is disabling and if have more table column it's looks not usable

**Comment by jacekkarczmarczyk** [comment]
You can try 2.0, data table was heavily refactored and received tons of fixes and features, 1.5 is unlikely to be updated in this area
