### ISSUE TITLE
[Bug Report] 2.0.0 beta 4 checkbox does not respect value (v-model works)

### ISSUE THREAD

**Issue by koush** [vuetifyjs/vuetify#7714]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Look at the codepen. The first checkbox is unchecked. This is a copy of the sample code in the docs, except v-model was changed to value. The second checkbox demonstrates the functional v-model.

### Expected Behavior
The first checkbox is checked.

### Actual Behavior
The first checkbox is unchecked.

### Reproduction Link
<a href="https://codepen.io/koush/pen/gNvEEz" target="_blank">https://codepen.io/koush/pen/gNvEEz</a>

**Comment by jacekkarczmarczyk** [comment]
It's `input-value`, not `value`. Clearly documentation issue as this prop is not even mentioned in API

**Comment by Mikilll94** [comment]
> It's `input-value`, not `value`. Clearly documentation issue as this prop is not even mentioned in API

Why is this prop called `input-value` instead of `value`?

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Additional_attributes

**Comment by johnleider** [comment]
@jacekkarczmarczyk yes it is: 
![image](https://user-images.githubusercontent.com/9064066/60451139-06803580-9bf1-11e9-8058-4d374eed7ddf.png)

@koush 👍 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jacekkarczmarczyk** [comment]
lol, that's why i think that components should be in tabs instead of v-select
