### ISSUE TITLE
[Bug Report] Autocomplete component with removeable items  is broken

### ISSUE THREAD

**Issue by alexeytihomirov** [vuetifyjs/vuetify#7715]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
Just try to remove items in your own example

### Expected Behavior
Items should be removed

### Actual Behavior
Items are not removing

### Reproduction Link
<a href="https://codepen.io/anon/pen/ydvrXe" target="_blank">https://codepen.io/anon/pen/ydvrXe</a>

### Other comments
Also items values are not submitted

**Comment by jacekkarczmarczyk** [comment]
It's `input-value`, not `value`. Clearly documentation issue as this prop is not even mentioned in API

**Comment by johnleider** [comment]
This was caused by my adding routable to chips but this conflicts with the value prop (enabling/disabling the visibility of the chip) and therefor I'm going to revert this change.

**Comment by johnleider** [comment]
Opted for a different path, still fixed either way.
