### ISSUE TITLE
[Bug Report] Inline editing with select causes the dialog for editing to close after each keypress.

### ISSUE THREAD

**Issue by natecorkish** [vuetifyjs/vuetify#7718]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Create a datatable with a dialog edit box. Add ```show-select``` to the datatable

### Expected Behavior
Save when the dialog has been closed.

### Actual Behavior
The Dialog saves and closes on every keypress.

### Reproduction Link
<a href="https://codepen.io/anon/pen/qzopXX" target="_blank">https://codepen.io/anon/pen/qzopXX</a>

### Video of said bug

https://www.youtube.com/watch?v=PiKZckia4Gg

**Comment by KaelWD** [comment]
```
item-key="task"
```

You're changing the key of the item, so vue re-renders it.
