### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by andypike** [vuetifyjs/vuetify#772]
Hi all,

I hope this is ok to post here. Just wanted to say a huge thank you for the awesome work you are doing with this project. I started using it a few days ago and it's been an absolute joy to use.

Your hard work is very much appriciated! Thank you so much!

❤️  💛  💙  💜  💚 

Please close this issue when you've seen it 😄

**Comment by dohomi** [comment]
Haha 💯

**Comment by johnleider** [comment]
Thank you for your support!
