### ISSUE TITLE
Search is not working on data tables sample 3

### ISSUE THREAD

**Issue by harryho** [vuetifyjs/vuetify#773]
### Steps to reproduce
* Issue is found on the sample of data tables
URL: https://vuetifyjs.com/components/data-tables
* Sample name: #3 Search with custom page text edit
* Click the pagination to the last page
* The search will not work.

**Comment by johnleider** [comment]
Good find!

**Comment by nekosaur** [comment]
Fixed in 88f989be1a45b51103332ba5f60898d1cecf6eb8
