### ISSUE TITLE
[Feature Request] More spacer intervals

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#7733]
### Problem to solve
$spacers skips some values and doesn't increase linearly, eg. there's no 12px or 32px option
![image](https://user-images.githubusercontent.com/16421948/60565526-5274db00-9da7-11e9-9ea2-76dc01b017a4.png)

### Proposed solution
Add `$spacer * 0.75` and `$spacer * 2` values, or just do 4px increments up to 48px.

**Comment by edbryanrosete** [comment]
add 24px please

**Comment by edbryanrosete** [comment]
Hello and thank you for improving the spacing for vuetify!

Are you by any chance also adding 12px? needed for left and right paddings/margins so it totals up to 24px

**Comment by KaelWD** [comment]
4 was always 24px

`pa-{n}` is now `n * 4px`

**Comment by edbryanrosete** [comment]
if we have 24px on each sides of the cards it will be a 48. That's why we need 12px so that it totals to 24px.
