### ISSUE TITLE
[Bug Report] No Margins Around v-tooltip in v-card-actions

### ISSUE THREAD

**Issue by BotellaA** [vuetifyjs/vuetify#7736]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Create tooltip buttons inside v-card-actions within a v-card

### Expected Behavior
Presence of margins whether buttons have tooltips or not inside a v-card-actions

### Actual Behavior
No margins when wrapping v-btn with v-tooltip in a v-card-actions

### Reproduction Link
<a href="https://codepen.io/BotellaA/pen/NZzGLw" target="_blank">https://codepen.io/BotellaA/pen/NZzGLw</a>

### Other comments
This same issue #4428 has been closed, and the fix has been tagged in the v1.4.0 but the issue is still here in v1.5.16.

**Comment by KaelWD** [comment]
You need to use the new slot syntax.

**Comment by BotellaA** [comment]
@KaelWD The behavior looks identical with the new syntax https://codepen.io/BotellaA/pen/NZzGLw

**Comment by KaelWD** [comment]
Old slot syntax duplicate of #4428, new syntax duplicate of #6951
