### ISSUE TITLE
Scroll disabled after fullscreen dialog closed

### ISSUE THREAD

**Issue by PhilGenois** [vuetifyjs/vuetify#774]
When I close a fullscreen dialog, the page scrolling stays disabled.

To reproduce, open the Fullscreen Dialog in the Doc and then close it :
https://vuetifyjs.com/components/dialogs

The CSS style "overflow-y: hidden; padding-right: 17px;" stays on the HTML tag when a fullscreen dialog is closed

**Comment by thomassjogren** [comment]
See https://github.com/vuetifyjs/vuetify/issues/767
