### ISSUE TITLE
[Bug Report] Cannot center v-switch inside v-flex

### ISSUE THREAD

**Issue by nccurry** [vuetifyjs/vuetify#7741]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Put v-switch inside a v-flex

### Expected Behavior
The ability to center v-switch elements inside v-flex.

### Actual Behavior
v-switch elements and always position to the left of their parent container.

### Reproduction Link
<a href="https://codepen.io/spicyusername/pen/pXKVrG" target="_blank">https://codepen.io/spicyusername/pen/pXKVrG</a>

**Comment by nccurry** [comment]
The solution is to embed the component inside a ```<v-layout column align-center>```.

**Comment by timothymarois** [comment]
@nccurry while this solution does help center the switch, The switch itself can not be centered with the text or in the box exactly. The switch box itself is aligning its content left. 

<img width="180" alt="Screen Shot 2021-01-04 at 4 33 16 PM" src="https://user-images.githubusercontent.com/2489333/103581806-b4396800-4eaa-11eb-8624-e93930e3ac7a.png">

<img width="134" alt="Screen Shot 2021-01-04 at 4 33 12 PM" src="https://user-images.githubusercontent.com/2489333/103581810-b7ccef00-4eaa-11eb-8212-92264d205bae.png">

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
