### ISSUE TITLE
[Bug Report] VToolbar background image not displayed

### ISSUE THREAD

**Issue by morphatic** [vuetifyjs/vuetify#7742]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Last working version:** 2.0.0-beta.1
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
1. Create a `v-toolbar` component with `src` prop set to a valid image URL

### Expected Behavior
The background image should be visible

### Actual Behavior
The background image is not visible (although it **is** being loaded)

### Reproduction Link
<a href="https://codepen.io/morphatic/pen/GbGddy" target="_blank">https://codepen.io/morphatic/pen/GbGddy</a>

### Other comments
This appears to have originated with the refactoring that created `v-app-bar` as a separate component from `v-toolbar`. There are a series of computed styles in [`VAppBar.ts`](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VAppBar/VAppBar.ts) (lines 102-171) that used to be a part of `VToolbar` but were removed during the refactor. The most important of these appears to be [`computedTransform()`](https://github.com/vuetifyjs/vuetify/blob/3a58522a1279f0b8f5072be1432958713af70753/packages/vuetify/src/components/VAppBar/VAppBar.ts#L160) that sets the [`transform: translateY(0px);`](https://github.com/vuetifyjs/vuetify/blob/3a58522a1279f0b8f5072be1432958713af70753/packages/vuetify/src/components/VAppBar/VAppBar.ts#L201) style rule on the component.

It appears that some or all of these styles should be ported back to `VToolbar`.

Another piece of possibly relevant info is that the [`contain: layout`](https://github.com/vuetifyjs/vuetify/blob/64f9e607a1bcaad4f365ff681abfc66624b16d7d/packages/vuetify/src/components/VAppBar/VAppBar.sass#L6) prop in `VAppBar.sass` also affects the background image visibility, but only in Google Chrome--[the `contain` property is not supported in Firefox and some other browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/contain#Browser_compatibility).

**Comment by morphatic** [comment]
Partially fixed by 162149f. Now works in Chrome, but still doesn't work in Firefox and Safari. Haven't checked Edge.

**Comment by kanteankit** [comment]
@morphatic @johnleider Is there a workaround for Firefox?

**Comment by morphatic** [comment]
Here's a workaround until it's fixed. Add the following style to your `<v-toolbar>`:

```css
.v-toolbar {
  tranform: translateY(0)
}
```

I've updated this pen to illustrate: https://codepen.io/morphatic/pen/GbGddy

**Comment by jacekkarczmarczyk** [comment]
@morphatic 2.0.3 seems to work fine https://codepen.io/anon/pen/RXgWRK

**Comment by morphatic** [comment]
Indeed. Just saw that someone had commented and missed f6c5cce and that this was close. 😅  @kanteankit, you should upgrade to v2.0.3. This bug was fixed.
