### ISSUE TITLE
[Feature Request] v-treeview providing a single choice function

### ISSUE THREAD

**Issue by MunMunMiao** [vuetifyjs/vuetify#7743]
### Problem to solve
> Sometimes we need a radio function like ```v-radio```,  And need a required option

- [x] all
 - [ ] a1
 - [ ] a2
   - [ ] a2.1
 - [ ] a3

### Proposed solution
Add a radio function in ```v-treeview```, and you can choose the required

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by plong0** [comment]
In case others are needing this functionality, I accomplished it by building a `RadioTree` component which wraps the `v-tree-view` with a `v-radio-group` and injects `v-radio` items into the tree using the 'label' slot.

When a selected `v-radio` is removed from the `v-radio-group` the `v-radio-group` value would be set to undefined (occurs when a tree node is collapsed.)  This component preserves the value even when its parent node is collapsed.

An example `CategoryTree` component is included with dummy data.  The example also demonstrates removing an item from the tree (try selecting item 1.3 and then press the "Nuke" button.)

https://gist.github.com/plong0/1dda8388e2e63ccdc19372f9095fff7c

Hope this helps, even if it is a bit of a workaround.
