### ISSUE TITLE
If the root app has spacing around it, menus display away from root element.

### ISSUE THREAD

**Issue by catskull** [vuetifyjs/vuetify#775]
### Steps to reproduce
Give your root app element a margin.

### Versions
This was introduced in 0.12.3. All versions after that have the problem.

### What is expected ?
Menus should display below the root element regardless of external element's spacing.

### What is actually happening ?
If the root app has any spacing around it, caused by margin/padding or other elements, then that spacing is also applied to the menu component, effectively doubling the spacing so the menu shows up far away from the element.

### Reproduction Link
https://codepen.io/catskull/pen/qjqpjv

**Comment by dohomi** [comment]
@catskull just curious here: did you try it with any pre-defined layout as well? you are using a quite unique way to structure your app

**Comment by catskull** [comment]
What do you mean by pre-defined layout?

**Comment by johnleider** [comment]
Vuetify tries to be very opinionated, layouts are an exception. A list of supporting layouts is in layout -> predefined.

**Comment by catskull** [comment]
I didn't check the pre-defined layout, but I assume it will work there. I can't use a predefined layout unfortunately.

This issue appears to be fixed in the latest dev branch though.

**Comment by dohomi** [comment]
@catskull whats your issue with a pre-defined layout? we are gathering information to make vuetify work instantly with NUXT. Maybe tell us how you structure your app

**Comment by catskull** [comment]
@dohomi My company's app is currently in Rails. We are using webpacker to gradually convert each page to Vue/Vuetify. Because of this, all navigation is handled by the Rails app. So my Vue app only consists of the content on the page, not any of the navbar stuff.

**Comment by johnleider** [comment]
After looking into this, it might end up being a caveat to the framework. The surrounding v-app can not have margin directly on it. Due to the theme system, v-app has to encompass all of Vuetify's components. Which ultimately means if there is margin on it, they will not be taken into account for the position calculations and it will be off.

**Comment by catskull** [comment]
I guess I'm curious because this used to not be a problem. Any idea why the position calculation needed to be changed?

**Comment by catskull** [comment]
Woah, sorry. This was introduced in 0.12.3, not 0.12.4.

**Comment by johnleider** [comment]
This was changed because the detachable contents were being appended to the v-app. This is now changed and everything gets pre-pended to the body.

**Comment by johnleider** [comment]
I can confirm that this is no longer an issue in dev.

**Comment by johnleider** [comment]
Had to revert this change due to menu inside of a dialog caveat...

**Comment by johnleider** [comment]
And it appears that it is still fixed! go me
