### ISSUE TITLE
[Bug Report] v-btn tile prop not work

### ISSUE THREAD

**Issue by lansi951** [vuetifyjs/vuetify#7750]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
`v-btn` create with `tile` prop.
<v-btn tile></v-btn>

### Expected Behavior
`v-btn` border-radius is 0.

### Actual Behavior
`v-btn` border-radius is still 2px. no tile class.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GbBVMW" target="_blank">https://codepen.io/anon/pen/GbBVMW</a>

**Comment by ibrahimBeladi** [comment]
You reproduction link is using Vuetify v1.5.15.

**Comment by lansi951** [comment]
@ibrahimBeladi I updated reproduction link.

**Comment by sh7dm** [comment]
fixed in 49292c8
