### ISSUE TITLE
[Bug Report] v-sparkline with values prop set to an array with same values is throwing an error

### ISSUE THREAD

**Issue by emoldovan** [vuetifyjs/vuetify#7753]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.5.17
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Set property values to an array like next one [2, 2, 2, 2, 2, 2]

### Expected Behavior
Should look like a straight line

### Actual Behavior
it is throwing an error: "Error: <path> attribute d: Expected number, "M16 NaNLNaN NaNS83 N…"."

### Reproduction Link
<a href="https://codepen.io/anon/pen/OeoRvj?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/OeoRvj?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
fixed in https://github.com/vuetifyjs/vuetify/commit/a375292e3fb3f90ba39b9a4133e407d6c7c07f04
