### ISSUE TITLE
[Bug Report] IE 11 text field label overlay after page refresh

### ISSUE THREAD

**Issue by rubinovk** [vuetifyjs/vuetify#7754]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Open a page https://vuetify-text-field.azurewebsites.net/ in IE11
2. Type text in text fields
3. Refresh the page

Try (3) several times to see the issue as it does not show up on every page refresh. Every 3rd time on average.

### Expected Behavior
No overlay of the past text input

### Actual Behavior
Past text input overlays the text field label

![text-field-refresh-ie](https://user-images.githubusercontent.com/2063487/60730822-50954e00-9f46-11e9-9c76-b4ac539738e6.PNG)

### Reproduction Link
<a href="https://github.com/rubinovk/vuetify-text-field" target="_blank">https://github.com/rubinovk/vuetify-text-field</a>

**Comment by webistomin** [comment]
I think IE11 keeps input values after browser refresh. But if you refresh page by hitting ctrl+f5, everything OK. You can reset form on mounted hook for example

```
mounted() {
  this.$refs.form.reset();
}
```

**Comment by tankerkiller125** [comment]
This is definitely due to the way IE11 handles forms. I suggest using @webistomin as the correct solution as technically IE11 is only supported using polyfills to start and in some cases, some users/developers may actually want to keep the form data still in the fields.

**Comment by Sotta94** [comment]
@webistomin your solution works but messes up the form bindings and sets values to undefined. Do you ever encounter this problem?

**Comment by webistomin** [comment]
> @webistomin your solution works but messes up the form bindings and sets values to undefined. Do you ever encounter this problem?

It works for me. Can you reproduce the issue? Sandbox or JSFiddle? I think you just get form data the wrong way.

**Comment by rubinovk** [comment]
> @tankerkiller125 some users/developers may actually want to keep the form data still in the fields.

The actual behavior is that information is not  kept in the fields, it is visually overlaying the form and disappears as soon as one clicks on the form. 
It's a __"ghost"__ of the data, this is why I think it's a bug.

**Comment by johnleider** [comment]
With the provided feedback I'm going to consider this issue as solved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by rubinovk** [comment]
@johnleider and @webistomin I disagree with this analysis: 
- The form is used properly just like in documentation
- Repo with the code is provided in the issue description  
- IE issues can’t be reported in JSfiddle or Sandbox, why asking? 
- Expecting end-users to refresh pages with Ctrl-f5 is unreasonable. 
- Works for me is not an answer

Our users are impacted. 
Could you give it another shot please?
