### ISSUE TITLE
[Bug Report] Submenu Item Not Highlighted When Selected Using v-list and v-list-group

### ISSUE THREAD

**Issue by wonder95** [vuetifyjs/vuetify#7756]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.5.22
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create a menu/submenu tree using v-list/v-list-group/v-list-tile like so:

```
<template>
  <v-list dark class="ap-sidebar-applist">
    <v-list-group
      class="ap-sidebar-group"
      v-for="(item, i) in items"
      :key="i"
      :prepend-icon="item.icon"
      :value="item.visible"
      @click="onClick(item)"
    >
      <v-list-tile slot="activator">
        <v-list-tile-title>{{ item.title }}</v-list-tile-title>
      </v-list-tile>

      <div v-if="item.children">
        <v-list-tile class="sub-list"
          v-for="(subMenu, j) in item.children"
          :key="j"
          @click="onClick(subMenu, true)"
          :class="subMenu.isActive?'v-list__group__header--active':''"
        >
          <v-list-tile-action>
            <v-icon>{{ subMenu.icon }}</v-icon>
          </v-list-tile-action>
          <v-list-tile-title>{{ subMenu.title }}</v-list-tile-title>
        </v-list-tile>
      </div>
    </v-list-group>

<!--</v-list-group> -->
  </v-list>
</template>
```

### Expected Behavior
Without having to implement any hacks (as I've had to do as shown in the linked CodePen). when selecting the submenu items, the submenu item is highlighted, and the highlighting is removed from the top level menu item.

### Actual Behavior
When clicking on the top level menu item that has children, the submenu items are displayed. However, when selecting the submenu item, the parent menu item stays highlighted and the submenu item is not highlighted.

### Reproduction Link
<a href="https://codepen.io/wonder95/pen/xoORpb" target="_blank">https://codepen.io/wonder95/pen/xoORpb</a>

### Other comments
The CodePen shows how I've had to hack this in `onClick()` to add the highlighting for the submenu item when it is selected and to remove the highlighting from the parent item.

**Comment by jacekkarczmarczyk** [comment]
Please reduce your reproduction to minimal @wonder95

**Comment by wonder95** [comment]
Sorry, I'm not sure I understand. How much more minimal? This is actually part of a much larger app, so I've reduced it and added some dummy data (instead of pulling from Vuex). Do you want just one top level menu with the two submenus (i.e. the `Tenants` item)?

**Comment by jacekkarczmarczyk** [comment]
If one top level menu with two submenus will show the issue then yes, but i mean also all (or at least most of) css, a lot of irrelevant js (things like `toggleSendMessageModal`, `ROLE_SUPER_ADMIN`, `setCurrentWorkspace` etc don't seem to be related to highlighting list items)
Here is a good article on creating good reproductions https://stackoverflow.com/help/minimal-reproducible-example

**Comment by wonder95** [comment]
Ok, I've cut it down to the minimum.

**Comment by johnleider** [comment]
The provided reproduction still has numerous issues in regards to missing data properties, missing methods and broken functionality.

With that being said, in order to properly facilitate highlighting, you must use the **group** property on `v-list-group`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
