### ISSUE TITLE
How to use the drawer selected effect like the official website?

### ISSUE THREAD

**Issue by xiuqianli1996** [vuetifyjs/vuetify#776]
The item won't turn blue when I select the menu item

**Comment by bolerodan** [comment]
Are you taking about the Icon next to each collapsible title, when you expand an item, that icon turns blue? If so, it's just a CSS class. The component automatically appends a class `list--group__header--active` and then targets the icon to turn it blue.

**Comment by johnleider** [comment]
Please direct all question based issues to gitter.
