### ISSUE TITLE
[Bug Report] VSnackbar Content left padding differs from md2 spec

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#7772]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.46
**OS:** Windows 10

### Steps to reproduce
Inspect `.v-snack__content` element in dev tools and note padding value on the LH side.

### Expected Behavior
LH padding should be 16px

### Actual Behavior
LH padding is 24px

### Reproduction Link
<a href="https://codepen.io/anon/pen/YoJZYP" target="_blank">https://codepen.io/anon/pen/YoJZYP</a>

### Other comments
Snackbar md2 spec found at https://material.io/design/components/snackbars.html#spec

<img width="264" alt="vuetify-snack-example" src="https://user-images.githubusercontent.com/1835454/60771631-98d07f80-a0b0-11e9-8e18-ce39f08550bb.PNG">
<img width="332" alt="md2-snack-example" src="https://user-images.githubusercontent.com/1835454/60771633-9cfc9d00-a0b0-11e9-829a-389a45ab9aa7.PNG">

**Comment by johnleider** [comment]
Part of this accidentally went out with https://github.com/vuetifyjs/vuetify/commit/49e3161ef74150fb2419c1c1821d3b3f8e7d123f

Finished remaining parts in: https://github.com/vuetifyjs/vuetify/commit/9f12df767034a7b73d8697d776b54d1b245e63fa
