### ISSUE TITLE
[Bug Report] VDialog Text left padding differs from md2 spec

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#7773]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.46
**OS:** Windows 10

### Steps to reproduce
Inspect `.v-card__text` element in dev tools and note padding value on the LH side.

### Expected Behavior
LH padding should be 24px

### Actual Behavior
LH padding is 16px

### Reproduction Link
<a href="https://codepen.io/anon/pen/gNBmKL" target="_blank">https://codepen.io/anon/pen/gNBmKL</a>

### Other comments
Dialog md2 spec found at https://material.io/design/components/dialogs.html#specs

<img width="384" alt="vuetify-dialog-example" src="https://user-images.githubusercontent.com/1835454/60771722-6ffcba00-a0b1-11e9-86ae-129e3e2d225c.PNG">
<img width="521" alt="md2-dialog-example" src="https://user-images.githubusercontent.com/1835454/60771723-712de700-a0b1-11e9-8637-bc477b50ce84.PNG">

**Comment by johnleider** [comment]
This will be an interesting one to solve as there is no real good way to determine if the card should have increased padding or not. Maybe will have to add an explicit property on `v-card` for **dialog**.

**Comment by johnleider** [comment]
Going to push this to a patch after release, need more time to determine a proper implementation.

**Comment by KaelWD** [comment]
We already have rules for `.v-dialog--scrollable>.v-card>.v-card__text`, doesn't seem to radical to add padding there too.
