### ISSUE TITLE
[Enhancement / Docs] v-select's unexpected itemValue default with returnObject

### ISSUE THREAD

**Issue by lukaw3d** [vuetifyjs/vuetify#7775]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.46
**OS:** Windows 8.1

### Steps to reproduce
1. Create `<v-select items="[{ id: 1, label: "A" }]" v-model="model">`
2. Selections aren't readable, so add `item-text="label"`
3. Model doesn't return object anymore, so add `return-object`
4. Everything looks okay
5. Change items to `[{ id: 9, label: "A" }]`
6. Input remains filled with wrong selection

### Expected Behavior
I would expect either:
- a warning that `<v-select` with `return-object` also requires `item-value` to be specified for item uniqueness
- or that `<v-select` with `return-objects` defaults to less-optimal object reference comparisons for uniqueness
- documentation to mention this danger
- or documentation to encourage `:item-value="null"` instead of `return-objects`

### Actual Behavior
Everything looks okay, but v-select is comparing items by item-text unnoticed

### Reproduction Link
<a href="https://codepen.io/anon/pen/JQmrJX?editors=1010" target="_blank">https://codepen.io/anon/pen/JQmrJX?editors=1010</a>

### Other comments
`item-value` is not required: https://github.com/vuetifyjs/vuetify/blob/d802994ee239ac5a0e0086e63e3ddaa31c56d7e8/packages/vuetify/src/components/VSelect/VSelect.ts#L91-L94

so `getValue` defaults to `getText` even in case of `return-objects`: https://github.com/vuetifyjs/vuetify/blob/d802994ee239ac5a0e0086e63e3ddaa31c56d7e8/packages/vuetify/src/components/VSelect/VSelect.ts#L529-L531

**Comment by johnleider** [comment]
- **item-value** is required when using any object for an item and is not exclusive to **return-object**
- don't really understand what you are asking here
- I'll add something to the docs
- as stated above, if you are using an object for an item, **item-value** will always be required.
 - item is returned on the second conditional when it's determined that it is not an object https://github.com/vuetifyjs/vuetify/blob/d802994ee239ac5a0e0086e63e3ddaa31c56d7e8/packages/vuetify/src/util/helpers.ts#L238

**Comment by lukaw3d** [comment]
Ah, sorry. I listed four possible behaviours that I would prefer. If you could make that requirement more explicit through documentation or a console warning, that would be great.

(right now `item-value` looks optional. And if it isn't used with `return-object`, it isn't evident that it defaults to `item['value'] === undefined ? itemText(item) : item['value']`)
