### ISSUE TITLE
[Bug Report] V-List-Group text not centered in a V-List with Nav

### ISSUE THREAD

**Issue by SheanDe** [vuetifyjs/vuetify#7779]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Last working version:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-list-group` inside a `v-list nav`

### Expected Behavior
The text should be centered vertically

### Actual Behavior
The text is not centered vertically and is a little too high

### Reproduction Link
<a href="https://codepen.io/anon/pen/PrxQqW" target="_blank">https://codepen.io/anon/pen/PrxQqW</a>

### Other comments
The text also move when clicked if we use `append-icon=""`
Maybe it's because of the new margin-bottom applied on the `.v-list-nav` ?

**Comment by sh7dm** [comment]
Fixed in b899bb783

**Comment by jacekkarczmarczyk** [comment]
Reverted in 40cd20824c72aa9c91f1bbb8f354526bef22e8d7

**Comment by johnleider** [comment]
`v-list-item` should no longer be used in the `v-list-group` activator slot: https://codepen.io/johnjleider/pen/NQWVQO

This was a breaking change introduced in https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0-alpha.10

**Comment by SheanDe** [comment]
You're right, i totally missed that. Thanks for the update.
Btw the doc is not updated for this change. Should i make an issue for that? Or it's already in the pipeline?
