### ISSUE TITLE
[Feature Request] Multiple suffix support on v-text-field

### ISSUE THREAD

**Issue by elonsalfati** [vuetifyjs/vuetify#7782]
### Problem to solve
For example, I have an input which requires the user to provide some amount of money, in the suffix of this input I want the user to select the currency from a predefined drop-down.

This will make the UX much better than providing the user with two different inputs one for the amount and one for the currency.

### Proposed solution
something like:

```
        <v-text-field
          label="Email address"
          value="example"
          suffix="['@gmail.com', '@hotmail.com']"
        ></v-text-field>
```

e.g. https://getbootstrap.com/docs/4.3/components/input-group/#buttons-with-dropdowns

**Comment by StefanFeederle** [comment]
Have you seen the last-example on the button-group pages?https://vuetifyjs.com/en/components/button-groups
I think you can combine an input and a select and get the final email with
```javascript
{
	computed: {
		email() {
			return `${this.text}${this.suffix}`;
		}
	}
}
```

**Comment by KaelWD** [comment]
This doesn't look like it's going to happen any time soon.
