### ISSUE TITLE
[Bug Report] VDialog :hide-overlay="false" not work with fullscreen prop

### ISSUE THREAD

**Issue by lansi951** [vuetifyjs/vuetify#7786]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
`v-dialog` create with `fullscreen` and `:hide-overlay="false"` props.

### Expected Behavior
dialog overlay is displayed.

### Actual Behavior
dialog overlay is not displayed.
and displayed two scroll(body, dialog) if long dialog content.

### Reproduction Link
<a href="https://codepen.io/anon/pen/dBwQOv" target="_blank">https://codepen.io/anon/pen/dBwQOv</a>

**Comment by johnleider** [comment]
That's unfortunately not how fullscreen works. The prop assumes that the dialog literally takes up the fullscreen, so there is no where for the overlay to be.

https://codepen.io/johnjleider/pen/VJgpJR is an example of a different way to approach it.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
