### ISSUE TITLE
[Bug Report] Select with prepend-inner slot

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#7787]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Selecting gender -> label placed in wrong place.
cliking on toggle not rerender label back

### Expected Behavior
PLacing label on corect position

### Actual Behavior
Not place label on corect position and not rerender label behavior on change.

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/jjdqBG" target="_blank">https://codepen.io/dev1ldragon/pen/jjdqBG</a>

**Comment by johnleider** [comment]
The label adjustments are calculated based upon the width of prepend/append/prefix/suffix. Your use-case is not something that we plan to support.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Dev1lDragon** [comment]
you have some programing trigger to recalc all things related with label?

**Comment by jacekkarczmarczyk** [comment]
you can try `:key="`${value}${readonly}`"`

**Comment by Dev1lDragon** [comment]
worked tnx for answer @jacekkarczmarczyk
