### ISSUE TITLE
[Bug Report] Floating Action Button

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#7788]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Floating Action Button not rendered corectly

### Expected Behavior
Corect display

### Actual Behavior
---

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/GbzZYN" target="_blank">https://codepen.io/dev1ldragon/pen/GbzZYN</a>

**Comment by jacekkarczmarczyk** [comment]
Closing in favour of https://github.com/vuetifyjs/vuetify/issues/7833 (better description)
