### ISSUE TITLE
[Bug Report] [2.0.0] [VCalendar] Event slot doesn't work if initial events array is empty

### ISSUE THREAD

**Issue by xplodwild** [vuetifyjs/vuetify#7790]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
1) Setup a custom event scoped slot (`<template v-slot:event="event">`)
2) Pass an empty `events` array to the `<v-calendar>`  component
3) Add an element to the events array

### Expected Behavior
The event should display on the calendar, containing the scoped slot layout

### Actual Behavior
The event, or any event added, doesn't display

### Reproduction Link
<a href="https://codepen.io/anon/pen/pXGPzw" target="_blank">https://codepen.io/anon/pen/pXGPzw</a>

### Other comments
Note that it works if you don't define a custom event slot-scope template, or if there is at least one element in the initial events array when the V-Calendar component is mounted.

Also, please note that the "event" slot isn't in the documentation, I figured it from the code.

**Comment by ClickerMonkey** [comment]
The issue actually lies with how you overrode the event slot. Without your slot override the event is actually there.

https://codepen.io/anon/pen/ydZRBb

**Comment by xplodwild** [comment]
@ClickerMonkey I agree, however the event slot is not even instantiated/mounted by the VCalendar component if the initial events array is empty.

It is a bug to me, as the slot override should be properly instantiated even when the events are loaded afterwards.

**Comment by RdCoding** [comment]
@ClickerMonkey Not sure why this is closed as I'm also having trouble with this issue now, is there some way to "correctly" implement the event slot? 

The Vuetify docs do not seem to specify how to make use of the event slot and in the API explorer, the event slot is not shown under the "slots" tab for the calendar either, any specific reason for this?

**Comment by domzware** [comment]
Hi, any workaround on this issue? It's still occurring on v2.0.10.

**Comment by xplodwild** [comment]
@domzware My workaround was to pass a fake event in the original data. As long as there is at least one event when the VCalendar is mounted, it will work fine afterwards.

@ClickerMonkey Still not willing to fix this issue? I might give it a try someday otherwise.

**Comment by RdCoding** [comment]
@domzware @xplodwild's solution works, as an example I start with an `events` property in my component's data with an initial event as follows:

```
data() {
 events: [{ start: "1900-01-01", name: "" }],
}
```

**Comment by qmo2015** [comment]
This bug also occurs when event slot is not overrode but other slots are.

**Comment by AlexandroWillianHervis** [comment]
It's still occurring on v2.2.3 :(

**Comment by phayes** [comment]
This should be re-opened, it's still an issue

**Comment by phayes** [comment]
@ClickerMonkey  - This took me an hour to debug, and was utterly baffling until I found this ticket.  

I would recommend re-opening this ticket since this seems to have caught quite a few number of people unaware.

**Comment by UsmanJavaidFullStack** [comment]
I have a proposed solution.
