### ISSUE TITLE
[Bug Report] mdiSvg icons are persistently black in color

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#7793]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.46
**OS:** Windows 10

### Steps to reproduce
1. Set up a vue-cli 3 project to use the mdiSvg iconfont.
2. Note the color of any built-in or imported icons are black in color.

### Expected Behavior
The icons should be responsive to color changes.

### Actual Behavior
The icons are all black in color.

### Reproduction Link
Unable - See comment below

### Other comments
I'm unable to create a reproduction in a simulated env that uses mdiSvg icons. Apologies.
@KaelWD commented on this bug in Discord [here](https://discordapp.com/channels/340160225338195969/351121729164410882/598306118753845268)

**Comment by jacekkarczmarczyk** [comment]
fixed in 7f0ba3899177d582002d4e29a50c63109994e3e6
