### ISSUE TITLE
[Bug Report] VExpansionPanel not handling v-text or v-html directives well

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#7794]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.3.15
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.46
**OS:** Windows 10

### Steps to reproduce
See codepen.

### Expected Behavior
Using `v-text` or `v-html` directives in template shouldn't:
1. cause the panel header expand-icon to disappear
2. break panel content css spacing
3. html tags honored in content panel if `v-html` directive used

### Actual Behavior
1. `<v-expansion-panel-header>` `expand-icon` disappears unless mustache interpolation is used
2. `<v-expansion-panel-content>` content css spacing breaks unless mustache interpolation is used
3. html tags not honored in content panel when `v-html` directive is used

### Reproduction Link
<a href="https://codepen.io/anon/pen/mZvjJW" target="_blank">https://codepen.io/anon/pen/mZvjJW</a>

### Other comments
[vuejs v-text docs](https://vuejs.org/v2/api/#v-text)
[vuejs v-html docs](https://vuejs.org/v2/api/#v-html)

**Comment by jacekkarczmarczyk** [comment]
Another example: https://codepen.io/anon/pen/wLNxgm?editors=1000
That's because v-text/v-html overwrites the internal DOM structure of the component with the provided text/html, so instead of 
```html
<div class="v-component">
  <div class="v-component__child">
    contents
  </div>
</div>
```
you get
```
<div class="v-component">
  contents
</div>
```
I don't think we can do anything about it

**Comment by 185driver** [comment]
```css
.v-expansion-panel-content {
  display: block;
}
```
seems to be a possible fix for #3 above.

**Comment by 185driver** [comment]
I just saw your comment, @jacekkarczmarczyk . All okay, as it's not difficult to work around this. I just noticed the behavior changed as I was upgrading to v2 and I wanted to raise the issue if it was not intentional or could be made the same as before.

**Comment by sgehrman** [comment]
I encounted the same issue
