### ISSUE TITLE
[Bug Report] Overlay not showing when close and open VDialog quickly

### ISSUE THREAD

**Issue by DanSnow** [vuetifyjs/vuetify#7798]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
1. Click on `CLICK ME` to open VDialog and make sure the button is not covered by the dialog
2. Double click on `CLICK ME`

![gif](https://i.imgur.com/ebKF1CR.gif)

### Expected Behavior
The overlay is showing

### Actual Behavior
The overlay is gone

### Reproduction Link
<a href="https://codepen.io/anon/pen/rERBrZ?editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/rERBrZ?editable=true&editors=101</a>

### Other comments
This issue can also reproducing with VDialog document demo [https://next.vuetifyjs.com/en/components/dialogs](https://next.vuetifyjs.com/en/components/dialogs)

**Comment by MrsSima** [comment]
Got the same issue with vuetify 2.3.10: when v-dialog is opened right after page is loaded, overlay is lost
