### ISSUE TITLE
v-text-input ignores v-model.lazy modifier

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#78]
Hello,
I think inside of the form elements like v-text-input the `.lazy` modifier is not evaluated. Would be a nice addon for search text input elements

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by dohomi** [comment]
@johnleider sure thing. Have you ever created a raw starting point of `vuetify` which would be fast to clone?

**Comment by johnleider** [comment]
You could use one of the vue-cli templates, https://vuetifyjs.com/quick-start

**Comment by dohomi** [comment]
Here the reproduction-repo: http://jsfiddle.net/5jd6yeth/3/
```
<v-text-input type="text" v-model.lazy="message" label="with lazy" placeholder="Message without lazy"></v-text-input>  
```
`v-model.lazy` inside of v´`v-text-input` does not update the message model

**Comment by johnleider** [comment]
From what I can find, https://github.com/vuejs/vue/issues/3666, this is not supported on custom components. I've been looking through the Vue instance and I cannot find anywhere that I would determine this modifier. If I can, then I have an update that would fix this.

**Comment by johnleider** [comment]
After some more research, I believe I would have to have a prop where you could specify lazy.

**Comment by johnleider** [comment]
I have been unable to find a way to hook into this manually. If it is needed for this functionality to exist. Please open a another issue for a feature request.
