### ISSUE TITLE
[Feature Request] Prevent scrolling on input in VTextarea with auto-grow

### ISSUE THREAD

**Issue by darivs** [vuetifyjs/vuetify#7803]
### Problem to solve
1 Open this: https://codepen.io/anon/pen/MMxKKY
2 Scroll down to bottom of the page
3 Place caret somewhere in the textarea
4 Start typing

The browser automatically scrolls up until the row containing the caret is at the very end of the page.

### Proposed solution
As long as the caret is visible on the page, there is no reason to scroll up to it. It's just an annoying behaviour which would be amazing to get rid of.

**Comment by KaelWD** [comment]
This is native browser behaviour.
