### ISSUE TITLE
[Bug Report] Missing line wrap for tabs with long title

### ISSUE THREAD

**Issue by albert0815** [vuetifyjs/vuetify#7804]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 7

### Steps to reproduce
Open codepen

### Expected Behavior
Title of the tab should look nice, e.g. by doing line wrap as it used to work in 1.5 version of Vuetify.

### Actual Behavior
It is not possible to read the title.

### Reproduction Link
<a href="https://codepen.io/anon/pen/zVboKW" target="_blank">https://codepen.io/anon/pen/zVboKW</a>

**Comment by jacekkarczmarczyk** [comment]
According to https://material.io/design/components/tabs.html#spec maximum tab width is 360px, you can override it using custom css or setting `$tabs-item-max-width` sass variable

side note: in beta.7 max width is 300px and there's a typo in the variable name (`$tabs-item-man-width`), it's fixed in 47689caa5b653ccccb66740ea2e40bbe3fbfa652

**Comment by albert0815** [comment]
I am just wondering why the title does not wrap as it did in the current version:

https://codepen.io/anon/pen/pXYRrQ

This does not seem to be an issue of maximum size.

**Comment by jacekkarczmarczyk** [comment]
I missed the wrapping part. I'll reopen this to get other team members' comments, but personally i'd avoid long tabs titles, also it's not recommended in the specs

![image](https://user-images.githubusercontent.com/15625235/61050050-5d9ebb00-a3e6-11e9-9034-ba87b342aaa8.png)

**Comment by johnleider** [comment]
I'm okay with it, it was removed by inheritance from the new slide-group component.

Workaround for now: https://codepen.io/johnjleider/pen/ydWMaw

**Comment by sh7dm** [comment]
@johnleider IMHO this workaround can be used as a primary solution

**Comment by MatthewAry** [comment]
The spec also says:
"Tab labels appear in a single row. They can use a second line if needed, with truncated text. Alternatively, you can use scrollable tabs to allow room for longer titles."

**Comment by buglavecz** [comment]
Hi Guys,
With vertical tabs has something wrong: 
https://vuetifyjs.com/en/components/tabs#vertical-tabs

I updated my project to 2.0.17, and  I got this:
![image](https://user-images.githubusercontent.com/43108336/64760103-29a45b00-d539-11e9-8613-e517d52bc402.png)

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
