### ISSUE TITLE
[Bug Report] Nested VExpansionPanels Style Conflicts

### ISSUE THREAD

**Issue by Pazza** [vuetifyjs/vuetify#7809]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Nest VExpansionPanels and open and close panels. Set nested ExpansionPanel to use accordion and notice rounded panel borders.

### Expected Behavior
Nested Panels should behave independent of its parent

### Actual Behavior
Nested panels are carrying the styles of its parent. Nested panel header icon's state reflect the parent, not itself. Nested panels set as accordion continue to carry radius-border as set in parent.

### Reproduction Link
<a href="https://codepen.io/pazza/full/NZoMrZ" target="_blank">https://codepen.io/pazza/full/NZoMrZ</a>

**Comment by johnleider** [comment]
😱
