### ISSUE TITLE
Dialog overlay persists if enabled dialog is destroyed

### ISSUE THREAD

**Issue by chriswa** [vuetifyjs/vuetify#781]
### Steps to reproduce
Destroy an enabled dialog, for example, by removing it with a v-if in a parent component.

### Versions
vue@2.3.4
vuetify@0.12.7
Google Chrome 58.0.3029.110 (Official Build) (64-bit)
Windows 10

### What is expected ?
The overlay disappears when the dialog disappears.

### What is actually happening ?
The overlay remains, darkening the page and preventing all user interaction.

### Reproduction Link
https://codepen.io/anon/pen/OgRqdV?editors=1010

**Comment by johnleider** [comment]
Good find. I need to add the destroy overlay into the beforeDestroy hook. Good find.

**Comment by chriswa** [comment]
Thanks again! :)

**Comment by jamesxv7** [comment]
Nuke version while waiting for 0.13 release 
```javascript
let overlay = document.getElementsByClassName('overlay')
while (overlay.length > 0) {
  overlay[0].parentNode.removeChild(overlay[0])
}
```
Is this aceptable?

**Comment by johnleider** [comment]
It really depends on your setup, the above code could have quite a few issues.

**Comment by jamesxv7** [comment]
Agree, especially if the class `overlay` is been used in other places which is not the overlay functionality.
