### ISSUE TITLE
[Bug Report] Box Shadow on v-expansion-panel

### ISSUE THREAD

**Issue by dritir** [vuetifyjs/vuetify#7813]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Open https://next.vuetifyjs.com/en/components/expansion-panels#expansion-panel inspect and search for v-expansion-panel::before css class

### Expected Behavior
Box shadow should be applied to the Div (.v-expansion-panel) so it can be controlled with .elevation-(n)

### Actual Behavior
Is being applied to v-expansion-panel::before

### Reproduction Link
<a href="https://codepen.io/anon/pen/JQVNOB" target="_blank">https://codepen.io/anon/pen/JQVNOB</a>

### Other comments
.v-expansion-panel {
  flex: 1 0 100%;
  max-width: 100%;
  position: relative;
  transition: 0.3s cubic-bezier(0.25, 0.8, 0.5, 1);
}
.v-expansion-panel::before {
  border-radius: inherit;
  bottom: 0;
  content: "";
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  z-index: -1;
  transition: box-shadow 280ms cubic-bezier(0.4, 0, 0.2, 1);
  will-change: box-shadow;
  **box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);**
}

**Comment by KaelWD** [comment]
It has to be applied to a separate element so it doesn't overlap adjacent panels: https://blog.dudak.me/2014/css-shadows-under-adjacent-elements/
