### ISSUE TITLE
[Feature Request] v-select should display menu on focus (by tab cycle)

### ISSUE THREAD

**Issue by bhaskar-nair2** [vuetifyjs/vuetify#7817]
### Problem to solve
The v-select should show menu on focus by tab cycle. The current behavior is to show the menu only when clicked / pressed down arrow / started typing.

This will be very useful as users tend to click on the field open the menu open unless explicitly told to use the down arrow key. In long forms this becomes a hassle. One might argue that the user can just start typing to open the menu, but in a lot of cases the options are not known to the user. 

### Proposed solution
The v-select menu should open whenever it receives focus, both mouse click and tab cycle. This can be added as an option in the menu-props.
Reproduction Link
https://codepen.io/bhaskar-nair2/pen/RzOOVj

**Comment by johnleider** [comment]
We try to have the inputs react as they would with their native counter parts. In light of that, this is not how selects behave.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
