### ISSUE TITLE
[Bug Report] Dark mode broken

### ISSUE THREAD

**Issue by luzik** [vuetifyjs/vuetify#7818]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
Check
https://next.vuetifyjs.com/en/examples/layouts/sandbox

### Expected Behavior
Theme change to dark

### Actual Behavior
Theme not changing to dark

### Reproduction Link
<a href="https://codepen.io/anon/pen/MMRNVg?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/MMRNVg?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Use `$vuetify.theme.dark` to switch between dark/light modes: https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0-beta.7

Docs fixed in 153a50877e5f4e69745c31944ad32a692177ca9d

**Comment by luzik** [comment]
More to fix:
https://next.vuetifyjs.com/en/getting-started/pre-made-layouts

**Comment by jacekkarczmarczyk** [comment]
39fc0cdeb9e6e2b4002fb6fd0061608e6ceace23
