### ISSUE TITLE
[Feature Request] data-table: ability to group headers/columns

### ISSUE THREAD

**Issue by morficus** [vuetifyjs/vuetify#7819]
### Problem to solve
It is currently not possible to group table headers / columns so that related headers can have a common title above them.

There are various use cases across different industries for being able to create column groups, especially when doing multi-dimension comparisons (I can provide real-world examples if needed).

### Proposed solution
From a props perspective, I think one could augment the current `:headers` prop to accept nested column definitions. Something along these lines:

```javascript
[
{ text: 'Total', value: 'yearlyTotal', align: 'left' },
{
 text: 'Q1 2019',
 align: 'center',
 headers: [
    { text: 'Travel', value: 'travelQ1' },
    { text: 'Food', value: 'foodQ1' },
    { text: 'Equipment', value: 'equipmentQ1' }
  ]
},
{
{
 text: 'Q2 2019',
 align: 'center',
 headers: [
    { text: 'Travel', value: 'travelQ2' },
    { text: 'Food', value: 'foodQ2' },
    { text: 'Equipment', value: 'equipmentQ2' }
  ]
}
]
```

Column nesting / grouping to continue recursively (meaning the developer could create as much grouping and sub-groupings as they need).
Column groups would not be sortable nor filtrable, only individual columns.

**Comment by johnleider** [comment]
Is this not possible in v2 @nekosaur ?

**Comment by nekosaur** [comment]
No. This is talking about grouping columns, now rows.

**Comment by vschimpf** [comment]
This was possible in v1 by using the headers slot. I tried the same in v2 using the header slot, but the column group didn't work.
Also saw in documentation that there is a group.header slot, but don't know how to use it.
I couldn't find any example of grouping column header for v2.

**Comment by nekosaur** [comment]
`header` slot should be pretty much identical to old `headers` slot. What didn't work?

**Comment by nekosaur** [comment]
yes, you have to manually set `hide-default-header`

**Comment by mandaputtra** [comment]
So, for now, it must be added manually? Like [these](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_th_colspan) ?

**Comment by krishnarhl** [comment]
Is this feature implemented yet?

**Comment by mandaputtra** [comment]
@krishnarhl as long it is still open it is not implemented for now use my method to do this kind of stuff or you can use simple table to do this

**Comment by nikoaliro** [comment]
> Sorry for the late response. I can see my custom header placed under the default one, it is not replacing the default header with the custom one. This is my code:
> 
> ```
> <v-data-table ...>
>   <template v-slot:header="props" >
>     <tr><th>...</th></tr>
>     <tr><th>...</th></tr>
>   </template>
> </v-data-table>
> ```

Using this info, it turns out you can simply implement your own categories line if you just add `<thead>` in the template.

```
<v-data-table ...>
  <template v-slot:header="props" >
    <thead>
      <tr>
         <th colspan="2">Category 1</th>
         <th colspan="3">Category 2</th>
       </tr>
    </thead>
  </template>
</v-data-table>
> ```

**Comment by KaelWD** [comment]
v3 accepts a 2d headers array, where each inner array is a new row
```js
[
  [
    { title: 'Total', value: 'yearlyTotal', rowspan: 2 },
    {
      title: 'Q1 2019',
      align: 'center',
      colspan: 3,
    },
    {
      title: 'Q2 2019',
      align: 'center',
      colspan: 3,
    }
  ],
  [
    { title: 'Travel', value: 'travelQ1' },
    { title: 'Food', value: 'foodQ1' },
    { title: 'Equipment', value: 'equipmentQ1' },
    { title: 'Travel', value: 'travelQ2' },
    { title: 'Food', value: 'foodQ2' },
    { title: 'Equipment', value: 'equipmentQ2' }
  ],
]
```

"groups" can be used for filtering or sorting if they have a `key` property

**Comment by asugomez** [comment]
With vue 3 we can group columns using the `children` props:
`
[
    { title: 'Total', value: 'yearlyTotal', rowspan: 2 , children:
         [ {
                title: 'Q1 2019',
                align: 'center',
                colspan: 3
           },
            {
                title: 'Q1 2019',
                align: 'center',
                colspan: 3
           },
       ]
    },
   ....
]
`
