### ISSUE TITLE
Feature Request: styling for inline form fields

### ISSUE THREAD

**Issue by jijoel** [vuetifyjs/vuetify#782]
When we include forms with inline items, the spacing changes, as shown in the image below: 

![image](https://user-images.githubusercontent.com/3487641/27254877-a3eded4e-532d-11e7-9b88-f561957f5e95.png)

It would be nice to have consistent spacing when putting inline text fields on a form. It's not critical, in any way, but presents users with a cleaner, more polished interface.

https://codepen.io/jijoel/pen/VWPyaq

**Comment by johnleider** [comment]
I don't quite understand what you are asking for. Can you help clarify a bit? The image looks fine to me, so I assume I'm not understanding properly.

**Comment by nekosaur** [comment]
My guess is he's talking about the spacing between Street Address and the inputs below. At a glance it looks to be larger than between Street Address and Country

**Comment by johnleider** [comment]
Thank you.

**Comment by johnleider** [comment]
This can be fixed by adjusting your markup. You need to have everything inside of the grid.

https://codepen.io/johnjleider/pen/zzEPwJ

**Comment by BonnieDoug** [comment]
> This can be fixed by adjusting your markup. You need to have everything inside of the grid.

When doing it this way you end up with 2 fields stuck together with no padding or margin between. As you can see from your example:

![image](https://user-images.githubusercontent.com/4302775/33831626-b7aefe80-de70-11e7-83f6-e56bcf5a55fe.png)

Which looks almost bearable, until you get validation errors next to a character count, then they almost merge into one another:

![image](https://user-images.githubusercontent.com/4302775/33831748-353b1352-de71-11e7-8317-f3d67b61bf38.png)

This happens even when applying the [m](https://vuetifyjs.com/layout/spacing) spacing classes to either the `v-flex` or the `v-text-field`.

Pen https://codepen.io/anon/pen/LePeLy

**Comment by johnleider** [comment]
If you are using a grid, then you should probably use a grid-list if you want spacing between different flex items, this is how flexbox works. The only difference is that we used to always apply some level of padding between flex items, and now we don't. If you feel you have a legitimate issue, please create a new ticket.

**Comment by BonnieDoug** [comment]
Thank you, that works perfectly.
