### ISSUE TITLE
[Bug Report] Treeview Item Active Class Stuck When Item Moved in Tree

### ISSUE THREAD

**Issue by zzachattack2** [vuetifyjs/vuetify#7822]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
-TreeView with items array with at least 1 level of children items. Multiple-active is set to false. 
-Modify items array where some child item is moved CLOSER to the root of the tree. 
-Select the item.
-Select a different item. 

### Expected Behavior
-Active class changes as normal to inactive of the node that was moved, after selecting another item. 

### Actual Behavior
-Active class remains on item after selecting another item. 

### Reproduction Link
<a href="https://codepen.io/zzachattack2/pen/qzGmBX" target="_blank">https://codepen.io/zzachattack2/pen/qzGmBX</a>

### Other comments
The "active" property array behaves as expected. Behavior is only observed when child item is moved CLOSER to the root of items. Does not occur when moved further/deeper in the tree. When inspecting the treeview component's "nodes" property, the moved item's corresponding node (and any child items of that item) object, all have their vnode property set to null.

**Comment by johnleider** [comment]
Please update this to target v1.5, which is what your codepen references, thank you.

**Comment by zzachattack2** [comment]
I updated the codepen to target 2.0.18 .

**Comment by johnleider** [comment]
This seems to work when using a `active.sync` and a default value (array in this example). It doesn't maintain the active selection (which may be intended).

**Comment by johnleider** [comment]
@nekosaur thoughts?

**Comment by AgileInteractive** [comment]
I just ran into this issue on 2.2.11. I have set active.sync. When dataprovider moves a node closer to the root, the vnode object becomes null in the tree's node structure. The "active" state of the node won't deselect when other nodes in the tree are clicked (it will however deselect the active state if you specifically click the faulty node).

My workaround right now: Remove the object from the dataprovider and re-add it 1 ms after, so VTreeView treats it as a new object.

**Comment by filonik** [comment]
Same problem here, quite annoying if your tree structure changes in more complicated ways than one item at a time (you basically have to throw away and rebuild the tree on the next tick). Not sure why the vnode get lost...

**Comment by ssipos90** [comment]
if anyone is wondering, it's still happening on 2.4.8

I will upgrade next week to 2.5.x and check again.

**Comment by longtengz** [comment]
Still happening on 2.6.10.
