### ISSUE TITLE
[Bug Report] v-checkbox Icons defualts not used when using custom icon

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify#7823]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Windows 10

### Steps to reproduce
1. Use Font awesome icons
2. Specify below option in Vuetify options
```
  icon: {
    iconfont: 'fa',
    checkboxOff: 'far fa-square',
    checkboxOn: fas fa-check-square'
  }
```

3. The v-checkbox does not render. As it cannot find the icon

### Expected Behavior
v-checkbox should defult the icons specified

### Actual Behavior
Current, need to specify the icons on each component

```
                <v-checkbox
                  v-model="myValue"
                  on-icon="fas fa-check-square"
                  off-icon="far fa-square"
                ></v-checkbox>
```

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-35nug" target="_blank">https://codesandbox.io/s/vue-template-35nug</a>

**Comment by KaelWD** [comment]
Your object structure is wrong: https://next.vuetifyjs.com/en/customization/icons#using-custom-icons

**Comment by steklopod** [comment]
You've lost `values`:
```json
 icon: {
    iconfont: 'fa',
values: {
    checkboxOff: 'far fa-square',
    checkboxOn: fas fa-check-square'
   }
}
```
