### ISSUE TITLE
[Feature Request] Fixed Header and Footer in Data Table

### ISSUE THREAD

**Issue by phifa** [vuetifyjs/vuetify#7827]
### Problem to solve
Need a robust solution for fixed header and footer in data table

### Proposed solution
This has been requested before, but it is not available yet. The new vuetify 2.0 will have a fixed header, that is a good start, but this should be extended. The codepen from the angular data table shows how it's done: it includes the complete header, not just the column headers and the footer:

https://codepen.io/anon/pen/qbLaMb?editors=1010

#346
#2787
#6865
#7404

**Comment by KaelWD** [comment]
I don't see how that's any different to this: https://codepen.io/anon/pen/VJJvbO?editors=1010

**Comment by phifa** [comment]
You are right. This is good. Last time I did not get it to work. Closing this! 🖤

**Comment by laventnc** [comment]
this is different b/c in the original example only the table body overflowed. in the official implementation, it relies on z-indexing the table headers & applying a background to the headers.

as a result, scenarios like a container with a gradient background break the fixed header b/c a transparent background on the table ends up showing the table elements visibly underneath the headers, with no background on the headers to hide them
