### ISSUE TITLE
[Feature Request] v-autocomplete slot="item" z-index not working

### ISSUE THREAD

**Issue by Bogdah9** [vuetifyjs/vuetify#7831]
### Problem to solve
In my exemple (https://codepen.io/bogdah9/pen/Gbbvey) not working @click last list. And not working z-index.

### Proposed solution

Add a class to scoped slots

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
