### ISSUE TITLE
[Bug Report] Icons vertically misaligned with text within buttons

### ISSUE THREAD

**Issue by desyatnik** [vuetifyjs/vuetify#7832]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
https://next.vuetifyjs.com/en/components/icons#buttons

### Expected Behavior
An icon and text are vertically aligned within a button.

### Actual Behavior
The text seems higher than icon.

### Reproduction Link
https://next.vuetifyjs.com/en/components/icons#buttons

**Comment by KaelWD** [comment]
Looks fine in chrome 74 on linux

**Comment by jacekkarczmarczyk** [comment]
They are slightly misaligned chrom&edge/win but also cut from the top and bottom

![image](https://user-images.githubusercontent.com/15625235/61267284-97314680-a797-11e9-9fa7-2cb8c825e511.png)

Alignment looks better on firefox, still cut

![image](https://user-images.githubusercontent.com/15625235/61267356-e4adb380-a797-11e9-8be8-48f34af059e5.png)

**Comment by desyatnik** [comment]
Hmm, they are not cut for me (chrome on win), but misaligned only:
![misaligned](https://user-images.githubusercontent.com/34752947/61332779-cabeb000-a82d-11e9-8621-e59eb82733e3.png)
