### ISSUE TITLE
[Bug Report] v-speed-dial expanded appearance is abnormal

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#7833]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.62
**OS:** Windows 10

### Steps to reproduce
Open codepen and tap on FAB. Note the button spacing and button size.

### Expected Behavior
It should behave and appear as it does in v.1.5.16

### Actual Behavior
The  buttons open up too close together and are too small.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ewwMVM" target="_blank">https://codepen.io/anon/pen/ewwMVM</a>

### Other comments
Here is a codepen taken from the v1.5.16 docs showing the correct behavior/appearance:
https://codepen.io/anon/pen/orrqEO

**Comment by johnleider** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/5146c85d6938d822a7a4eb9f5d27b4cf043bfe13
