### ISSUE TITLE
[Feature Request] v-file-input: Allow chips to be removable

### ISSUE THREAD

**Issue by softwareguy74** [vuetifyjs/vuetify#7837]
### Problem to solve
Allows user to selectively remove chips from list.  

### Proposed solution
Allow X icon to be displayed in chip and when clicked, remove just that chip from the list.

**Comment by johnleider** [comment]
We discussed this internally and decided against it. It's technically possible for the user to do it but goes against what is possible on a regular file input, which is what we aim to mimic. It's also why we didn't provide any examples of how to implement it.

This is functionality that we plan to do for `v-file-upload`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
