### ISSUE TITLE
Feature Request - v-select: check selected when items array changes

### ISSUE THREAD

**Issue by bradyob** [vuetifyjs/vuetify#784]
# Feature Request

**v-select component**
Recheck selected when the items array changes

**Purpose**

- If items array is built from an http request or a cpu intensive calculation, the selected item cannot be set until the items array has been changed.

**Comment by johnleider** [comment]
I'm checking this on dev and it is working exactly as requested above. Since the items array is in a computed fn, it recalcs when that is updated. Are you able to check and see if this works for you on dev?

**Comment by johnleider** [comment]
I can confirm this is in dev and working.
