### ISSUE TITLE
[question] can i change v-select option style?

### ISSUE THREAD

**Issue by charmjeh** [vuetifyjs/vuetify#7842]
### Problem to solve
hello,

i want to change v-select option style. how can i modify css like below?
![image](https://user-images.githubusercontent.com/43127789/61271846-9ffa3a80-a7e0-11e9-8efb-0ffd63e8c56b.png)

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
