### ISSUE TITLE
[Feature Request] v-checkbox / v-simple-checkbox - loading state

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7843]
### Problem to solve
https://codepen.io/anon/pen/KONvrR?editors=1010

### Proposed solution
`<v-checkbox v-model="model" :loading="loading" />`

**Comment by dsanders11** [comment]
This is almost a bug fix rather than a feature request, since the documentation documents the `loading` prop (incorrectly, says it's a linear progress bar) and there is a `loading` prop, it just does nothing.

**Comment by johnleider** [comment]
An unfortunate downside when extending. We'll get it resolved.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ricardo17coelho** [comment]
This would be nice.. this issue should be reopened..

**Comment by egeersoz** [comment]
Not sure why this was closed, since it's not fixed.

**Comment by johnleider** [comment]
If this is still a problem in v3 please create a new issue: https://issues.vuetifyjs.com/

**Comment by ricardo17coelho** [comment]
Hi @johnleider 
This still be a problem in v2

**Comment by smohammadhn** [comment]
vuetify 2 still has the issue:

        <v-checkbox loading />
        <v-switch loading />
        <v-text-field outlined loading />

checkbox simply does nothing where the other two show loading state perfectly !

First i thought there is something wrong with my project structure, so i decided to test it on a vue 2 codeSandBox
(https://codesandbox.io/s/vuetify-2-forked-tskku9?file=/src/App.vue:659-760)
which gave the exact same result!
