### ISSUE TITLE
[Bug Report] Virtual rows prevents expanded rows from working on v-data-table

### ISSUE THREAD

**Issue by dark-matter-matters** [vuetifyjs/vuetify#7844]
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Create a v-data-table like the one provided in the docs : https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/examples/data-tables/simple/footer-props.vue.
Add the property virtual-rows.

### Expected Behavior
Rows should be expandable.

### Actual Behavior
Rows can't be expanded while expand arrows are shown. Doesn't work when adding manually rows inside _expanded_ array neither.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gNVbKx" target="_blank">https://codepen.io/anon/pen/gNVbKx</a>

**Comment by johnleider** [comment]
This particular functionality was disabled before release v2.0. This will be handled as part of our upcoming virtual loader component. You can watch progress here: <https://github.com/vuetifyjs/vuetify/pull/10944>

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
