### ISSUE TITLE
[Bug Report] v-file-input - File not showing when added again after deletion

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7848]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
1. Add a file.
2. Delete a file
3. Add the same file which was added in point 1

### Expected Behavior
The file should show.

### Actual Behavior
The file is not showing.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ydmqpM?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/ydmqpM?&editable=true&editors=101</a>

**Comment by harrip12** [comment]
i'm facing the same issue.. can anyone help me to resolve this. any help will be appreciated.
