### ISSUE TITLE
[Bug Report] v-file-input - multiple files upload

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7849]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Add multiple files to v-file-input

### Expected Behavior
Multiple files should be visible.

### Actual Behavior
Only the last added file is visible.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gNVjdO?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/gNVjdO?&editable=true&editors=101</a>

### Other comments
In the current implementation, it is not clearly visible that the file input has multiple files.

**Comment by MajesticPotatoe** [comment]
This is working as intended and can be achieved with the `selection` slot.
https://next.vuetifyjs.com/en/components/file-inputs#scoped-slots

**Comment by jacekkarczmarczyk** [comment]
or chips <https://codepen.io/anon/pen/pXMxrX?&editable=true&editors=101>

**Comment by jacekkarczmarczyk** [comment]
Although it could display file names same as v-select multiple (names separated with comma)
@vuetifyjs/core-team ?
