### ISSUE TITLE
[Bug Report] Hover effects and lines disappear when use custom body with v-slot:body

### ISSUE THREAD

**Issue by mesaglam** [vuetifyjs/vuetify#7854]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Last working version:** 2.0.0-alpha.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
You can see that in your #slot example in doc. Just click the pen and select "body" from selectbox..

### Expected Behavior
Mouse hover effects and row lines should appear like regular view has

### Actual Behavior
When I use custom body, it looks like a card. Lines disappear...

### Reproduction Link
<a href="https://codepen.io/anon/pen/wVwKmB?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/wVwKmB?&editable=true&editors=101</a>

### Other comments
Thanks...

**Comment by KaelWD** [comment]
Needs `tbody`

**Comment by mesaglam** [comment]
Yeah it works. You may wanna change the example in doc. Thanks...
