### ISSUE TITLE
[Bug Report] Autofill/autocomplete does not work in Chrome

### ISSUE THREAD

**Issue by nidkil** [vuetifyjs/vuetify#7857]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chromium 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
See codepen example.

### Expected Behavior
Autofill/autocomplete in Chrome to work like it does in Firefox and Chromium.

### Actual Behavior
It does not work.

### Reproduction Link
<a href="https://codepen.io/nidkil/pen/OKLrQR?editors=1010" target="_blank">https://codepen.io/nidkil/pen/OKLrQR?editors=1010</a>

**Comment by johnleider** [comment]
It's disabled by default, you'll have to enable it. This has changed on v2.0 https://codepen.io/johnjleider/pen/RXbvgg?editors=1010

**Comment by nidkil** [comment]
Hi John,

Thx for the quick response. I see that I should have been more specific in my example and question. My problem is with the v-text-field. I have narrowed down my example to the two first fields (email and name).

https://codepen.io/anon/pen/JgPQoN?editors=1011

Sorry for the confusion.
