### ISSUE TITLE
v-select Should Open Upwards When There is Not Enough Space

### ISSUE THREAD

**Issue by devmattrick** [vuetifyjs/vuetify#786]
### Steps to reproduce
Place a `<v-select>` element near the bottom of the page.

### Versions
This affects all versions of Vue and Vuetify and is browser-agnostic, as far as I am aware. Tested on Vue 2.3.3, Vuetify 0.12.7, and Chrome 58.

### What is expected?
The select should open upwards instead of downwards when there is not enough room to fit it in the viewport (or at least the document). In other words, it should not forcibly expand the document if it is going to overflow, similar to how a vanilla HTML `<select>` element would work.

### What is actually happening?
The select will expand the document to fit, causing strange styling issues.

### Reproduction Link
https://codepen.io/anon/pen/PjpNJm

**Comment by dohomi** [comment]
@devmattrick can you check it now again? 0.13.0 has a fixed for the alignment of v-select

**Comment by devmattrick** [comment]
@dohomi It seems to be working properly now on the CodePen. Thanks!
