### ISSUE TITLE
[Feature Request] v-data-table height property does not include footer

### ISSUE THREAD

**Issue by gorsat** [vuetifyjs/vuetify#7860]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
create a v-data-table
set height to "100px"
check height of the v-data-table element in browser
see that it is 159px (because the child v-data-footer element is 59px tall)

### Expected Behavior
the height of the v-data-table element (incl the footer) should 100px
- OR - 
create a separate property to get (and set?) the height of the footer and update the docs

### Actual Behavior
setting the height of the table only sets the height of the table header + body but not the footer. so the height of the actual v-data-table element is height_property_in_pixels + 59

### Reproduction Link
<a href="https://codepen.io/OGCoder/pen/XvrLvV?&editable=true&editors=101" target="_blank">https://codepen.io/OGCoder/pen/XvrLvV?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
This is more of a feature request in my eyes as this is intended behavior.

**Comment by felixis-1** [comment]
I have a feature request tangential to this for one more use case. I often set **itemsPerPageOptions: []** in **footer-props** on **v-data-table** to get rid of the **itemsPerPage** selector. Doing so, collapses the height of the footer to 37px from 59px making it look odd in comparison to the other rows. If a mechanism can be provided to set the height explicitly for the footer component or have it not collapse itself in this scenario will be great.
