### ISSUE TITLE
[Bug Report] v-chip ripple not working

### ISSUE THREAD

**Issue by luna2216** [vuetifyjs/vuetify#7863]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Last working version:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Click on the chip

### Expected Behavior
Ripple shows

### Actual Behavior
Ripple not showing

### Reproduction Link
<a href="https://codepen.io/anon/pen/wVvggO?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/wVvggO?&editable=true&editors=111</a>

### Other comments
https://github.com/vuetifyjs/vuetify/blob/51e49cfccb860d01a875fc74475994cbff6bf338/packages/vuetify/src/components/VChip/VChip.ts#L183

This line overrides the ripple directive in generateRouteLink()

should be 
```
    data.directives = [
      ...data.directives,
      {
        name: 'show',
        value: this.active,
      },
    ]
```

**Comment by johnleider** [comment]
The ripple prop is not part of v-chip's API. If you want to use it, apply the v-ripple directive:

https://codepen.io/johnjleider/pen/MNWqoE?&editable=true&editors=111

**Comment by KaelWD** [comment]
@johnleider https://github.com/vuetifyjs/vuetify/blob/51e49cfccb860d01a875fc74475994cbff6bf338/packages/vuetify/src/mixins/routable/index.ts#L33

#7327 has a mergeData helper that could prevent errors like this.

**Comment by johnleider** [comment]
Fair enough, I'll update the api for chips.
