### ISSUE TITLE
[Bug Report] VDialog not hiding background scroll bar when dialog open

### ISSUE THREAD

**Issue by lansi951** [vuetifyjs/vuetify#7867]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
make long background content.
and make long dialog content.

### Expected Behavior
When open the dialog, background scroll bar is hidden.
Only dialog scroll bar is shown.

### Actual Behavior
Background and dialog scroll bars are displayed.

### Reproduction Link
<a href="https://codepen.io/anon/pen/dBwQOv" target="_blank">https://codepen.io/anon/pen/dBwQOv</a>

**Comment by johnleider** [comment]
This is not a bug. The toolbar is only hidden on mobile devices.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
