### ISSUE TITLE
Layout not responsible on smartphone and browser device toolbar 

### ISSUE THREAD

**Issue by SgtPepper27** [vuetifyjs/vuetify#787]
I dont know whats going wrong but the Layout is not responsible by switching to the device toolbar or watching it on smartphone.

Template: webpack-advanced

![image](https://user-images.githubusercontent.com/27993481/27281753-6dcf22ac-54ed-11e7-9bca-7d1d2d26d1d8.png)

instead of 

![image](https://user-images.githubusercontent.com/27993481/27281741-5be9c952-54ed-11e7-828e-96cfcd9d6057.png)

some suggestions?

**Comment by nekosaur** [comment]
I'm guessing the template is missing the following meta tag

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
