### ISSUE TITLE
[Bug Report] v-icon x-small not working

### ISSUE THREAD

**Issue by gorsat** [vuetifyjs/vuetify#7873]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
make v-icon with attr x-small

### Expected Behavior
an icon is rendered at "extra small" size which is reasonably expected to be "less than the small size" 

### Actual Behavior
an icon is rendered at medium size (bigger than the small size)

### Reproduction Link
<a href="https://codepen.io/OGCoder/pen/bXNVoZ" target="_blank">https://codepen.io/OGCoder/pen/bXNVoZ</a>

**Comment by KaelWD** [comment]
v-icon doesn't actually use the x-small prop, it's just inherited from a mixin created for v-btn. @vuetifyjs/core-team should this be added, or just removed from docs?

**Comment by jacekkarczmarczyk** [comment]
Seem natural to use x-small icon in x-small btn, also sizing props should be consistent withing the framework, not sure where these large/small props are used but all components having at least one of these props should have the others
