### ISSUE TITLE
[Bug Report] Does not use passive listeners

### ISSUE THREAD

**Issue by ahmedfaical** [vuetifyjs/vuetify#7877]
### Versions and Environment
**Vuetify:** 1.5.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.2

### Steps to reproduce
Hello, I'm using vuetify with nuxt and i'm using a scroll to top functionality juste like vuetifyjs.com
When i generate report in lighthouse i get this report : Does not use passive listeners to improve scrolling performance (Consider marking your touch and wheel event listeners as passive to improve your page's scroll performance.)
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners?utm_source=lighthouse&utm_medium=extension

Any idea how can i add this in v-scroll directive?

### Expected Behavior
Must wrok with v-scroll.passive="onScroll"

### Actual Behavior
I get lighthouse error

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by KaelWD** [comment]
The v-scroll directive already uses a passive listener, this could be from anything.
