### ISSUE TITLE
[Bug Report] Explicitly defined theme color for a component reverts back on page navigation even though theme property changed

### ISSUE THREAD

**Issue by manastalukdar** [vuetifyjs/vuetify#7879]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Vivaldi 2.7.1609.4
**OS:** Windows 10

### Steps to reproduce
1.  Run the Python script `scripts/create_blog_metadata.py`. The prerequisite python packages can be installed using the `scripts/python-requirements.txt` file.
2. Run `npm run nuxt-dev`
3. Open the website (localhost) in any browser.
4. Click on the `change theme` icon in the top nav bar. Your theme will now change from the default dark to light.
5. Click on a link (any link, say `Legal` in the top bav bar).
6. The top nav bar and footer will now revert back to the dark theme colors.
7. Go back to the home page. You will see that all components that have explicitly a color defined have reverted back to the default dark color.

### Expected Behavior
Colors as defined under theme options stay put after navigation to a different link, even though the theme property has changed from dark to light and vice versa.

### Actual Behavior
All components that have explicitly a color defined have reverted back to the default dark color.

### Reproduction Link
<a href="https://github.com/manastalukdar/manastalukdar.github.io/tree/source/website" target="_blank">https://github.com/manastalukdar/manastalukdar.github.io/tree/source/website</a>

### Other

- Using Nuxt.
- Using the `@nuxtjs/vuetify`, `1.0.0-beta.7` module.

**Comment by manastalukdar** [comment]
Repro gif available here: https://user-images.githubusercontent.com/2075466/61583571-e3112200-aaee-11e9-8495-074e410a496e.gif

If you are having trouble running the Python script, follow these steps to not have to run the script:

1. Get blog_metadata.json file from here: https://gist.githubusercontent.com/manastalukdar/5af89c4ab56edf2a32c7292ecf4de759/raw/e3a8ece4589d47900c2fb8232591e620697899e1/blog_metadata.json
2. Under the `website/src/static` folder, create a new folder called `blogdata`.
3. Under `blogdata` folder create a new folder called `metadata` and copy the blog_metadata.json from step 1 into this new `website/src/static/blogdata/metadata` folder.
4. Copy the folder (along with all sub-folders) `website/blog/2019` into `website/src/static/blogdata`. `website/src/static/blogdata` should now have 2 subfolders: `2019` and `metadata`.

That should be it. `npm run nuxt-dev` should now work.

**Comment by manastalukdar** [comment]
Perhaps this is related to: https://github.com/vuetifyjs/vuetify/issues/7481.

**Comment by kevinmarrec** [comment]
@manastalukdar I followed your instructions, it ends up with
```
Cannot find module 'src/components/pages/index.js' from '/home/kevin/tmp/manastalukdar.github.io/website'
```
on my computer :/

Even if your custom SCSS variables will be broken, can you try setting `treeShake: false` ? Just to see if it's related. Thanks.

**Comment by manastalukdar** [comment]
@kevinmarrec Just tried `treeShake: false`. Does not solve the problem.

I am really not sure why you are getting that `Cannot find module...` error. I do not reacll every running into it. Are you working off of the right branch `feature/vuetify2`?

**Comment by manastalukdar** [comment]
@kevinmarrec The `Cannot find module... index.js` error seems to a random nuxt.js issue that has been reported in the past on Linux and Max OS's (https://github.com/nuxt/nuxt.js/issues/5132). I just tried it running `npm run nuxt-dev` using my repro project on a Linux OS and  ran into the exact same problem. If you have a Window machine that might work better.

**Comment by kevinmarrec** [comment]
@manastalukdar I'm indeed on a Linux machine, but didn't face this issue in my Nuxt projects, why would it happen here, seems weird and persisting, will try again tomorrow

**Comment by theomjones** [comment]
I've come across something similar too, when running Vuetify in nuxt's spa mode, you cannot dynamically update the theme colors from a component, but you can update it from within a plugin (by accessing context).

I opened an issue in the vuetify community module as I wasn't sure where the problem lives. However, maybe it's a Vuetify problem.

See issue here: https://github.com/nuxt-community/vuetify-module/issues/69

**Comment by kevinmarrec** [comment]
@manastalukdar Do you still have issue with last version of the module ? AFAIK the dynamically change of theme should only be broken in SPA mode and a fix is on his way here : https://github.com/vuetifyjs/vuetify/pull/8079

**Comment by manastalukdar** [comment]
@kevinmarrec Yes issue persists even with the latest version of the module. I am using `universal` mode.

**Comment by manastalukdar** [comment]
With the latest version of vuetify-module (1.1.0), there is now a slight change in behavior. On page navigation, instead of reverting to the custom colors for the default theme as defined in the theme options, we now end up reverting back to the default colors for the non-default theme. So, here is the new workflow:

1. Start with dark (default theme).
2. Change theme to light (on the same page). Header, footer change background color to light blue as defined in theme options, as expected.
3. Navigate to different page. Background color for header, footer background color revers back to white (default for the light theme).

**Comment by manastalukdar** [comment]
@kevinmarrec After installing vue-meta 2.2.0, the original issue as described in this thread no longer exists. However, there is now a slight variation of the original issue:

1. Go to home page. Default dark theme exists.
1. Navigate to a different page. Theme will revert from custom colors in dark theme to the default dark theme colors.

Interestingly, the above issue will not manifest in the following workflow:

1. Go to home page. Default dark theme exists.
1. Switch theme to light.
1. Navigate to a different page. Everything is still fine.
1. Switch theme again and navigate to different page. Everything is still fine.

So, if the default theme is not switched (ever), only then the custom colors for the default theme will revert to the default colors on page navigation.

The other issue with `nuxt generate` as described [here](https://github.com/nuxt-community/vuetify-module/issues/63) still exists.

**Comment by kevinmarrec** [comment]
@manastalukdar If i'm right last Vuetify version which ships a PR i did, is broken whith Vue Meta.

I'm working on a fix, it may fix every issue people could have with theme and route navigation.

Theme on Route navigation should be only broken when setting `head` in the pages if i'm right

**Comment by kevinmarrec** [comment]
@manastalukdar I think everything should be fixed by using `vue-meta` 2 + new Vuetify release with this PR (https://github.com/vuetifyjs/vuetify/pull/8234)

The PR may even fix the issue without having to upgrade `vue-meta`

**Comment by P4sca1** [comment]
I am experiencing a similar issue on webpack hmr.
Is this related and also fixed in #8234?

**Comment by kevinmarrec** [comment]
@P4sca1 Yes, at least i'm sure it's fixing it in Nuxt with `universal` mode (there's still some issues regarding SPA with VueMeta, see the PR description)

**Comment by manastalukdar** [comment]
Just verified that this issue is fixed with PR https://github.com/vuetifyjs/vuetify/pull/8234 in latest vuetify without having to upgrade vue-meta to v2.

**Comment by P4sca1** [comment]
The problems with webpack hmr are also fixed.
