### ISSUE TITLE
[Bug Report] Cannot deselect radio button when using "multiple" prop

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7880]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. Click on one of the radio buttons.
2. Click it again
3. As you can see it is not possible to deselect radio button.

### Expected Behavior
There should be a possibility to deselect a radio button when using "multiple" prop.

### Actual Behavior
There is no possibility to deselect a radio button when using "multiple" prop.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KOwLjG?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/KOwLjG?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
That's not how radio inputs work. Use checkboxes if you want this behavior.

**Comment by Mikilll94** [comment]
So this "multiple" prop is useless because I will select all radio buttons and now I cannot deselect anyone.

**Comment by pynner** [comment]
ehhhh not the functionality I expected from the multiple prop on radio-groups....

for anyone looking to do something like this, just attach an @click on the inner v-radio, and just work with the array manually. 

here's my snippet for inspo
```
    toggleMultipleRadio(_id) {
      if (this.internalData.includes(_id)) {
        this.internalData = this.internalData.filter((i) => {
          return i !== _id;
        });
      } else {
        this.internalData = this.internalData.concat(_id);
      }
    },
```

**Comment by NicolaMigliore** [comment]
I am honestly struggling to come up with a scenario in which the current functionality would be acceptable...
If my understanding is correct, using the multiple prop on radio-groups means that if the user mistakenly select an incorrect option it is not possible for them to correct the mistake, but only add the selection of other radios.
As workarounds I would second @pynner 's suggestion or add a clear button/icon using v-radio-group's _append_ slot.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
