### ISSUE TITLE
[Bug Report] v-radio-group with "row" prop is not correctly aligned

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7881]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
As you can see from the codepen above v-radio-group is NOT in the center between the labels.

### Expected Behavior
"justify-space-between" should work. v-radios should be exactly in the center between labels.

### Actual Behavior
There is no possibility to correctly align horizontally v-radio-group with "row" prop.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KOwLjG?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/KOwLjG?&editable=true&editors=101</a>

**Comment by Mikilll94** [comment]
Even if you wrap every `div` and `v-radio` in `v-flex` the effect is the same - radios are not in the center.

**Comment by johnleider** [comment]
This is the intended styling of radios and expect to have a label and spacing between. This should be solved in userland.

https://codepen.io/johnjleider/pen/oKpgKB
