### ISSUE TITLE
[Bug Report] absolute fab button is to low

### ISSUE THREAD

**Issue by gotenxds** [vuetifyjs/vuetify#7882]
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
As far as I see just create a simple page with an absolute bottom fab, it  will be created to low (under the app) and will cause scrolling.

### Expected Behavior
To be a bit higher. around bottom: -20 ?

### Actual Behavior
To low ( bottom: -24)

### Reproduction Link
<a href="https://codepen.io/gotenxds/pen/QebLwv" target="_blank">https://codepen.io/gotenxds/pen/QebLwv</a>

**Comment by KaelWD** [comment]
`absolute` is used to position button half-out of an element: https://vuetifyjs.com/en/components/floating-action-buttons#usage
