### ISSUE TITLE
[Feature Request] Don't display the ripple for touch scroll events

### ISSUE THREAD

**Issue by hareku** [vuetifyjs/vuetify#7887]
### Problem to solve
Now, v-ripple displays the ripple effect when a mobile user scrolls.
material-ui doesn't display the ripple for touch scroll events.

### Proposed solution
https://github.com/mui-org/material-ui/blob/v4.2.1/packages/material-ui/src/ButtonBase/TouchRipple.js#L118

**Comment by hareku** [comment]
material-ui PR: https://github.com/mui-org/material-ui/pull/8605/files

**Comment by bitbytebit1** [comment]
I'm also looking for this functionality!

**Comment by pcalin** [comment]
Yes. Pretty please, can we get this?

**Comment by Tantawi** [comment]
Can we merge this please? it is an important fix.

**Comment by yoshschoemaker** [comment]
This is indeed a pretty important fix. Can this be fixed/merged please?

**Comment by Sshuichi** [comment]
Any update on this?

**Comment by kyleoliveiro** [comment]
Please merge this. It is very important for mobile devices.

**Comment by bublikOff** [comment]
As temporary workaround it can be done with something like this

CSS
.hide-ripple .v-ripple__container { display: none }

JS
window.addEventListener('touchmove', function() { document.body.classList.add('hide-ripple') }, { passive: true });
window.addEventListener('touchend',  function() { setTimeout(function(){ document.body.classList.remove('hide-ripple') }, 50); });

**Comment by bitbytebit1** [comment]
Still waiting on this one guys ♥️

**Comment by johnleider** [comment]
resolved with #10596
