### ISSUE TITLE
[Bug Report] v-dialog inside v-dialog forces the view to scroll to the top

### ISSUE THREAD

**Issue by Mohammad-Ha** [vuetifyjs/vuetify#7888]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
- Click the link.
- Navigate to "Blog" from the menu.
- Click on the FAB.
- Scroll to the bottom.
- Press the button to open the dialog.

### Expected Behavior
Screen shouldn't be scrolling.

### Actual Behavior
Screen scrolls and resets.

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-4yzpz" target="_blank">https://codesandbox.io/s/vue-template-4yzpz</a>

### Other comments
This issue happens only when the second dialog is installed/mounted outside the v-dialog.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
