### ISSUE TITLE
[Feature Request] Add instructions on typescript setup to docs

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#7890]
### Problem to solve
I could not find any info on how to configure typescript correctly to consider vuetify typings.

### Proposed solution
Add instructions to the quick start section.
`vuetify/types` needs to be added to the `types` array in `tsconfig.json`.
Note that I only tested this for vuetify 2 so this should propably only be considered for the docs at next.vuetifyjs.com.

**Comment by RobbinBaauw** [comment]
To add to this, for testing with Jest I have always needed to add the following lines to my Jest config:
```javascript
transformIgnorePatterns: ["node_modules/(?!(vuetify))"],
moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^vuetify/lib$": "vuetify",
},
```
