### ISSUE TITLE
[Bug Report] Form no longer propagating default gutter to container

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#7891]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Last working version:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Look at the codepen

### Expected Behavior
The container is given a default gutter from the form

### Actual Behavior
It's not

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/qedXXo?&editable=true&editors=101" target="_blank">https://codepen.io/johnjleider/pen/qedXXo?&editable=true&editors=101</a>

### Other comments
Removed in grid update https://github.com/vuetifyjs/vuetify/pull/7327/files#diff-d2626ce843e1103877670cd3c8f3078bL1

**Comment by johnleider** [comment]
After team discussion we have decided to break this functionality and require the developer to manually define the gutter.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Reverted: b67610fef7382ac226dc09a654005a7092c1e6e8
Docs update: 7f9d060fadc7fd8fa461742ed07338dd8d06094d
