### ISSUE TITLE
[Bug Report] using VForm with  VeeValide,but 'confirmed:xx' does't work

### ISSUE THREAD

**Issue by bvvy** [vuetifyjs/vuetify#7899]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
input email & input same email

### Expected Behavior
validate pass

### Actual Behavior
validate fail

### Reproduction Link
<a href="https://codepen.io/anon/pen/XvbVBe?editors=1010" target="_blank">https://codepen.io/anon/pen/XvbVBe?editors=1010</a>

**Comment by d3radicated** [comment]
From Vee-Validate,

> Target based rules like `after`, `before`, and `confirmed` can target custom components as well as native inputs, but the target field must have a `ref` attribute set and the confirmed parameter must be the same ref value.

Adding `ref="email"` to your email text field works.
