### ISSUE TITLE
Sidebar: let it stay open when clicking on an item

### ISSUE THREAD

**Issue by pipejesus** [vuetifyjs/vuetify#79]
Hi, I'm trying to have the sidebar visible all the time and found the `closeOnClick` attribute in `Sidebar.vue` tempate but this doesn't work:

`<v-sidebar id="sidebar" fixed v-bind:closeOnClick="false">`

Am i using it correctly?
Greg

**Comment by johnleider** [comment]
Try ```v-bind:close-on-click="false"```.

**Comment by pipejesus** [comment]
hey John, it stills hides itself after click when `v-bind:close-on-click="false"`

**Comment by johnleider** [comment]
Could you post a jsfiddle reproducing this bug? I'm looking at the sidebar right now and unless you are on an older version of Vuetify, this should not be happening.

**Comment by pipejesus** [comment]
Ok, just before i do that : should i have the latest Vuetify if i simply do:

npm install --save vuetify ?

**Comment by johnleider** [comment]
```npm install vuetify@0.8.5 --save```

**Comment by pipejesus** [comment]
Ok John, so i had the latest version. Here, same thing happens on JSfiddle:

https://jsfiddle.net/ff2Lkesp/2/

**Comment by johnleider** [comment]
So you mean, when you resize window and it closes? That is intended. If you want it to not close on mobile, change the mobile-breakpoint to a lower number. https://github.com/vuetifyjs/vuetify/blob/master/src/components/sidebar/Sidebar.vue#L46

**Comment by pipejesus** [comment]
no, i mean when the window is wide and open and the click happens, the side bar hides ;) (to simulate my case make the result window on jsfiddle totally wide)

**Comment by johnleider** [comment]
https://jsfiddle.net/johnjleider/ff2Lkesp/3/

**Comment by pipejesus** [comment]
John i think i know now what's going on: it's not about the breakpoint but the `<v-btn v-sidebar:sidebar>Click</v-btn>` button : if you remove this button, the sidebar will hide whatever breakpoint you set. Is this button neccessary for the construction of the sidebar (i mean i will definitely want to use it) but is it intended that the sidebar should hide if no button is present? Thank you!

**Comment by johnleider** [comment]
I'm actually undecided. Personally, I would never expect a sidebar to not close on mobile, so you would always need a way to open it. I'm up for any arguments to the contrary.

**Comment by pipejesus** [comment]
I totally agree with you on that John, i'm sorry i think i'm just unable to convey the meaning because it's not my mother tongue. The problem that happens to me is that the absence of the button/whatever with this tag: `v-sidebar:sidebar` causes the whole sidebar to 'hide on click' doesn't taking into considerations any setup the user makes on the sidebar (like `v-bind:close-on-click` etc). Sorry for taking up so much time, i just wanted to know if i'm doing the stuff the right way : )

**Comment by johnleider** [comment]
For now, ensure that you always have an activator for the sidebar, in my jsfiddle, I use a button.

**Comment by pipejesus** [comment]
great, thanks a lot John
