### ISSUE TITLE
Feature Request: Tooltip on mini navigation drawer list icon

### ISSUE THREAD

**Issue by bunnypro** [vuetifyjs/vuetify#790]
it will be nice if a mini navigation drawer has a tooltip on its list icon that show its title.

**Comment by cawa-93** [comment]
https://codepen.io/cawa-93/pen/qjaqxm

**Comment by johnleider** [comment]
@cawa-93 is correct. 
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
