### ISSUE TITLE
[Bug Report] V-Dialog should lose focus on dismissal 

### ISSUE THREAD

**Issue by technbuzz** [vuetifyjs/vuetify#7907]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Edge 17.17134
**OS:** Windows 10

### Steps to reproduce
We need to look for the close event of v-dialog by pressing `esc` key.
1. First we need to listen to global keyboard event Go to "Sources" Tab of "Google Chrome". 
2. On the right pane from *Event Listener Breakpoints* enable the *Keyboard* checkbox
3. Press the `esc` key to close the modal, continue pressing the *Continue Script Exception* until modal is completely hidden.
4. Now press `esc` key again. Now code execusion is stopped again by *Debugger*, this is the problem. 

### Expected Behavior
The Modal should completely lose the focus when we close/dismiss it. The focus should be resumed on the parent component.

### Actual Behavior
The modal is still in focus even if it is dismissed.

### Reproduction Link
<a href="https://codepen.io/samiullah1989/pen/WVQRoJ" target="_blank">https://codepen.io/samiullah1989/pen/WVQRoJ</a>

### Other comments
This is accessibility problem when we navigate the app with the keyboard. The problem become worse when I wrote a toggle function that would listen to `v-model=dialog` and decide the present/dismiss status of modal. With current situation pressing esc also toggles the modal which is not desired behaviour. 

Some what related problem is the focus state button is not entirely visible not following the proper contrast ratio https://github.com/vuetifyjs/vuetify/issues/3923

**Comment by KaelWD** [comment]
Where should the focus go? It already returns correctly to the button if you use the activator slot or prop: https://codepen.io/anon/pen/LwGjGb?editors=1010

**Comment by technbuzz** [comment]
Well the activator works, but I have to apply some hacks when the **button that presents the modal** is placed in another component/view. I had to provide button inside **activator template** and make it visible only for assistive technologies.

**Comment by johnleider** [comment]
This would be my suggestion for code change that doesn't mess with the current activator functionality:

![image](https://user-images.githubusercontent.com/9064066/62482836-dc83db00-b77b-11e9-8cfc-7f38d67932ce.png)

The caveat is the button will not focus when the dialog closes. This would only be possible with an activator slot or if an explicit activator is passed as an option to the dialog. model only binding would simply close the dialog.

Workaround: https://codepen.io/johnjleider/pen/YmYzvm?editors=1111

**Comment by KaelWD** [comment]
We could store the last `document.activeElement` and return focus to it on close.
