### ISSUE TITLE
[Bug Report] Typography helper classes overriding font

### ISSUE THREAD

**Issue by hopefeda** [vuetifyjs/vuetify#7911]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.5.17
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Just import a font and set it globally or within a div's style. Then use a span or div with a typography helper class like .display-1, .display-2, title, etc.

### Expected Behavior
Typography helper classes should not affect font

### Actual Behavior
Font is changed

### Reproduction Link
<a href="https://codepen.io/anon/pen/LwVzdw" target="_blank">https://codepen.io/anon/pen/LwVzdw</a>

### Other comments
Using "!important" in the font-family css code works, but ruins icon fonts like material icons & fontawesome

**Comment by KaelWD** [comment]
#6912

**Comment by hopefeda** [comment]
I'm not sure if this is the right way but I think removing "!important" from the typography font-family styling solves the issue for the majority. Even better, removing the font form everyone and letting the user specify a font when bootstrapping the app.

example:

`.display-1 {
   //font-family: "Roboto", sans-serif !important; 
     font-family: "Roboto", sans-serif; 
}
`

**Comment by johnleider** [comment]
Typography classes are utility classes and meant to have the highest specificity for whatever they change.

Just update the `heading-font-family`:

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/stylus/settings/_variables.styl#L98
