### ISSUE TITLE
[Bug Report] `@change` not fired after clearing the textfield and focusing out

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7916]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. create clearable text field with some initial value
2. make sure it's not focused, click the clear icon
3. blur the input

### Expected Behavior
`@change` event should be fired

### Actual Behavior
`@change` event is not fired

### Reproduction Link
<a href="https://codepen.io/anon/pen/XvmxpZ?editors=1010" target="_blank">https://codepen.io/anon/pen/XvmxpZ?editors=1010</a>

### Other comments
This is NOT duplicate of https://github.com/vuetifyjs/vuetify/issues/5797 which says that `@change` event is not fired when the clear icon is clicked - this is expected and in line with native input fields.
`@change` event should be fired when the field is blured (same as native inputs)

**Comment by johnleider** [comment]
Verified not a regression.
