### ISSUE TITLE
[Bug Report] v-container id property no longer generates id for div element

### ISSUE THREAD

**Issue by manastalukdar** [vuetifyjs/vuetify#7919]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Last working version:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 77.0.3843.0
**OS:** Windows 10

### Steps to reproduce
Create an element `<v-container id="container-testing" fluid>`

### Expected Behavior
Generated div will have the id in the DOM

### Actual Behavior
id is absent in generated div

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-p43g5" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-p43g5</a>

### Other

This used to work in beta.8.

**Comment by johndevney** [comment]
**Vuetify:** 2.6.7
**Vue**: 2.6.10
**Browsers**: Chrome 104.0.5112.101
**OS**: MacOS Monterey

This seems to be an issue again. 

<v-container id="test-content-container" class="fill-height" style="display: block;" fluid>

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
