### ISSUE TITLE
[Bug Report] When light child card is inside of a dark parent card, the child card text is white.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#7920]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Put a light card inside of a dark card. Inside of the light card add v-card-text and observe that the text placed in this component is white and unreadable.

### Expected Behavior
v-card-text's color css property should be inherited by its most immediate parent v-card component.

### Actual Behavior
v-card-text is inheriting the color property from the dark card because the css rules for the light card are being overridden by the dark card's css property.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/gVaqPV" target="_blank">https://codepen.io/MatthewAry/pen/gVaqPV</a>

### Other comments
The dark card's theme is winning out because it's rule comes after the light theme rule. This is likely fixable by being more explicit about how the property is inherited.

**Comment by johnleider** [comment]
For future:

```sass
 > .v-card__text
    color: map-deep-get($material, 'text', 'secondary')
```
