### ISSUE TITLE
[Bug Report] Deleting a v-tab causes active selection and slider to be out of sync

### ISSUE THREAD

**Issue by tiagomalheiro** [vuetifyjs/vuetify#7926]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Mozilla Firefox, Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. Select the second tab entry (named 1001-1)
1. Close the first tab (1000-0)

### Expected Behavior
1. The first tab is closed
1. The new first tab (was the second previously) is now named 1001-0 and is selected 
1. The slider is under the first entry

### Actual Behavior
1. The first tab is closed (OK)
1. The new first tab (was the second previously) is now named 1001-0 and is selected (OK)
1.  The slider is under the second entry (bad)

### Reproduction Link
<a href="https://codepen.io/anon/pen/ymYGEe" target="_blank">https://codepen.io/anon/pen/ymYGEe</a>

### Other comments
When you select either remaining tab, the slider fixes its position.

Please notice I am using the 'value' property in v-tab, which the documentation makes no reference to it.
In that regard, I have other codepen which uses 'href' in v-tab and 'value' in v-tab-item. The behavior is the same: https://codepen.io/anon/pen/ZgbgEz

**Comment by johnleider** [comment]
FYI, there is no mention of the value property because it is not a property.

**Comment by tiagomalheiro** [comment]
thanks @johnleider for the note!

**Comment by johnleider** [comment]
This is resolved as of the latest version.
