### ISSUE TITLE
[Bug Report] Menu as context menu is opening multiple times

### ISSUE THREAD

**Issue by bmacher** [vuetifyjs/vuetify#7935]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Just right click on both items.

### Expected Behavior
Right click on a object should close the context menu of the object which was right clicked before.

### Actual Behavior
Context menus are opened multiple times.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-context-menu-opened-multiple-times-idstb" target="_blank">https://codesandbox.io/s/vuetify-context-menu-opened-multiple-times-idstb</a>

### Other comments
If I left click any object on the screen all context menus are closed.

**Comment by johnleider** [comment]
In order to prevent the browser context window, we prevent the default behavior. This also stops the event from triggering an outside click that would close the other one. 

My best suggestion would be to track the contextmenu state in a store that can be shared across your components.
