### ISSUE TITLE
[Bug Report] Scrolling area in navigation with bottom padding is shorter than the border

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#7936]
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
`<v-navigation-drawer class="pb-5">`

### Expected Behavior

![image](https://user-images.githubusercontent.com/15625235/61722347-67bba480-ad6a-11e9-9f90-4400655bec66.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/15625235/61722303-55416b00-ad6a-11e9-9ced-6c060945288e.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/oKXYMg?editors=1010" target="_blank">https://codepen.io/anon/pen/oKXYMg?editors=1010</a>

**Comment by johnleider** [comment]
Then you should add the padding on the list.
