### ISSUE TITLE
IE11 is not supported

### ISSUE THREAD

**Issue by alexs20** [vuetifyjs/vuetify#794]
Just want to say that IE11 doesn't work with vuetify, but web site saying that IE11 should work.
To reproduce that simply create a quick-start project (simple or cli) and try to open it in IE11.

**Comment by jijoel** [comment]
You need to load a polyfill for IE11 support. On your landing page, before loading the script for your app, load:

<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>

**Comment by alexs20** [comment]
Thanks for the propt responce.
I have added this script to my header section but it is still not working
`  <head>
    <title>Welcome to Vuetify</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet" type="text/css">
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <link rel="icon" type="image/png" href="public/favicon-32x32.png" sizes="32x32">
  </head>`

In console see the folowing:
HTML1300: Navigation occurred.
File: localhost:8080
polyfill-eventsource added missing EventSource to window
SCRIPT1003: Expected ':'
File: app.js, Line: 1707, Column: 1

**Comment by zeljic** [comment]
Yap, I found this too. Here is my workaround:
`yarn add babel-polyfill --save`
or
`npm install babel-polyfill --save`

Edit your webpack.config.js file, add `babel-polyfill` to entry definition before main js file, something like:

`entry: ['babel-polyfill', './src/main.js']`

Rebuild your project and try on IE11.
This change will increase your build size for ~80kb

**Comment by johnleider** [comment]
We have created a guide for using Vuetify in IE11 that will go with next release. For now, as stated above, you will need to include a polyfill.

**Comment by alexs20** [comment]
Unfortunately after installing babel-polyfill (even without modifying webpack.base.conf.js) my project stopped working with error:
`These dependencies were not found:

* vuetify in ./src/main.js
* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-5d98256e","sco
ped":false,"hasInlineConfig":false}!stylus-loader?{"sourceMap":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue in ./src/App.vue`

But ok, thanks for trying to help. will wait until official guide release.

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by zeljic** [comment]
@alexs20 try to clean-up your project

**Comment by zhuanjiaozm** [comment]
@zeljic   how to clean-up ?

**Comment by zeljic** [comment]
@zhuanjiaozm remove node_modules directory (then install components again)
But you should check "Internet Explorer 11 Support" section on Vuetify documentation
[https://vuetifyjs.com/vuetify/quick-start](url)

**Comment by Alendorff** [comment]
It seems doubtfully to add whole babel polyfill because of vuetify. 

Is it possible to specify what exactly should be polyfilled? Like `es6 array from` etc? Or it doesn't make sense because of too many things should be polyfilled?

**Comment by maslunde** [comment]
@zeljic Your link is broken.

**Comment by johnleider** [comment]
Please stop commenting on old close issues.

@Alendorff Then use babel-env
@maslunde https://vuetifyjs.com/getting-started/quick-start
