### ISSUE TITLE
[Bug Report] V-app v-show and data-app="true"

### ISSUE THREAD

**Issue by victorsilent** [vuetifyjs/vuetify#7943]
### Versions and Environment
**Vuetify:** 2.0.0
**Last working version:** 1.5.16
**Vue:** 2.6.9
**Browsers:** Firefox 68.0
**OS:** Linux, Ubuntu undefined

### Steps to reproduce
Use data-app="true" and <v-app v-show="false"> and render the project outside the v-app
https://codepen.io/victorsilent/pen/wVGMGj?editors=1010

### Expected Behavior
Get the current theme
https://codepen.io/victorsilent/pen/ZgWQOd?editors=0010

### Actual Behavior
Can't get the current theme

### Reproduction Link
<a href="https://codepen.io/victorsilent/pen/wVGMGj?editors=1010" target="_blank">https://codepen.io/victorsilent/pen/wVGMGj?editors=1010</a>

### Other comments
Hello, I'm upgrading to the newest release and to get my application working I'm using an approach as you can see on the image below. I did the upgrade to the v2 and right now my theme is not being applied to the application. How can I achieve the same thing with the current version?

The reason of this code is because I have legacy code that is being updated, so I have inline vuejs code inside the @yield('content'), which breaks the app when vuejs tries to render the components.

**Comment by johnleider** [comment]
If you are not using `v-app`, you have to add its classes (it scopes everything now):

https://codepen.io/johnjleider/pen/GVZoMQ?editors=1010
