### ISSUE TITLE
[Bug Report] If set export default App, v-text-field is same as header element.

### ISSUE THREAD

**Issue by hukusuke1007** [vuetifyjs/vuetify#7945]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.1
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. create vue template
2. add vuetify and setting.
3. implement header and v-text-field

This is source code.
https://github.com/hukusuke1007/vuetifytest

### Expected Behavior
v-text-field and header are not the same element.

### Actual Behavior
v-text-field and header are the same element...

This is screen shot.

![Imgur](https://i.imgur.com/b8vPhoB.png)

### Reproduction Link
<a href="https://github.com/hukusuke1007/vuetifytest" target="_blank">https://github.com/hukusuke1007/vuetifytest</a>

**Comment by johnleider** [comment]
I don't see any code in that repository that resembles what you posted above. Can you just create it in a codepen? https://template.vuetifyjs.com

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
