### ISSUE TITLE
"v-menu" appears as fixed if parent component is inside a scrolling container

### ISSUE THREAD

**Issue by matt-e-king** [vuetifyjs/vuetify#795]
I did my best to see if this has already been reported, but could find anything. I wouldn't really call this an issue, I am more curious what your thoughts are on adding a prop to `v-menu` to avoid mounting to the root of the app, that way a menu can exist inside of a scrolling container also.

Could possible check for a prop in the `mount` method:
(https://github.com/vuetifyjs/vuetify/blob/a79b018c557789b2cd4cf89ac3badbca40abd5fe/src/components/menus/Menu.js#L138)

### Steps to reproduce
Put a `<v-menu>` inside of a component that has a `overflow: auto` or `overflow-y: scroll`

### Versions
0.12.7

### What is expected ?
The menu should "stick" to the activator that opens the menu, e.g. Dropdown, Select.

### What is actually happening ?
If you place any component that has a `<v-menu>` inside of a parent component that is scrollable, the menu appears to be fixed and becomes "disconnected" from the activator

### Reproduction Link
Click the "Dropdown" button and then start scrolling up or down.
https://codepen.io/anon/pen/BZWOry

Thanks!!!

**Comment by johnleider** [comment]
Maybe we could provide an ** absolute** prop for the detachable mixin that would append it to its parent instead of root. Thoughts?

**Comment by matt-e-king** [comment]
Is there a "detachable" mixin? At first glance I thought it was all happening in the `mount()` method. 

Either way, yeah, a boolean prop seems to be the simplest. Could even be called `detach` and it is set to true by default. 

Anything else seems like overkill, unless it's on the roadmap to create some type of  "detachable" or "portal" mixin that allows you to control where in the DOM something mounts.

**Comment by johnleider** [comment]
I know that neko had a change for this, but at this point, I don't know what the best course of action is.

**Comment by matt-e-king** [comment]
Gotcha. Thanks for the follow up. So you're thinking that even this commit alone:
https://github.com/vuetifyjs/vuetify/pull/936/commits/57db3e5de48efeae527384ca01aa8073369f21f5
would still create some unwanted side-effects?

Related issue: I'm sure this has already been pointed out but, I also noticed if you've applied hover styles to a component that is the direct parent of a menu, when you hover over the menu, the hover styles are removed from the parent.

https://codepen.io/anon/pen/BZWOry

Thanks for all your work!

**Comment by johnleider** [comment]
I'm thinking that the best solution for this may be to remove scroll when a menu is open, I know other frameworks do that, and now I understand why hah.

**Comment by sindrepm** [comment]
I would really like to see an option like this added. My app contains of multiple sub views, each that are scrollable and the fact that the menu attaches to the root container makes this a really bad user experience.  Disabling scrolling is not a good solution imho.

I like the idea of an `attach-to` property which expects an element query selector and possibly a special `parent` value which will attach the menu to the immediate parent. For my use case it would be sufficient to be able to explicitly specify the container, though.

@johnleider @nekosaur what do you guys think? Could this be implemented in an unobtrusive way without causing any unwanted side effects to existing code?

**Comment by matt-e-king** [comment]
Even though I agree that @sindrepm solution would the most ideal, I'll defer to your judgement @johnleider. I take your word if you feel trying to solve this will create new issues (as you mentioned here https://github.com/vuetifyjs/vuetify/pull/936#issuecomment-320127348)

Preventing the scroll seems like a good compromise for the time being.

**Comment by johnleider** [comment]
I have been recently abstracting functionality out and think that this should be possible with the already implemented functionality. If not, I will probably defer to removing scroll when it is open.

**Comment by sindrepm** [comment]
@johnleider do you mean that this should already be possible in 0.15.7, or the next version to be released? As long as the menu is mounted to the root container I don't see how this could be possible.

What exactly is the side effects of allowing the user to specify a custom mount point? If you don't specify one explicitly it should just work like today, no?

Removing scroll is not really a solution to the problem, just a quick hack that circumvent it. It makes no sense from a user perspective to disable scroll just because a menu has been opened. It would also make the entire content of the overflow container shift to the right which looks nasty from a UX perspective.

**Comment by johnleider** [comment]
Keep in mind @sindrepm , it's only something I'm considering because that is what a lot of other big frameworks do. I have been making gradual code updates that should make this cleaner in the future, but it is not currently supported.

**Comment by ultraN** [comment]
Same here [Codepen](https://codepen.io/arthur_zhu/pen/LOeKXa)

**Comment by jacekkarczmarczyk** [comment]
fixed with https://github.com/vuetifyjs/vuetify/pull/2716

**Comment by gctommy** [comment]
Also happening on v1.0.1 inside fixed element (with or without "**absolute**" prop): [Codepen](https://codepen.io/anon/pen/MQVbPZ)

**Comment by nekosaur** [comment]
1) Use `attach` prop on `v-menu`

2) In the future, please create new issues instead of commenting on closed ones, or join our chat at https://chat.vuetifyjs.com to get help.

**Comment by codewp** [comment]
@nekosaur 

I used attach prop for menu but it can not calculate right position for menu when menu is inside of `v-bottom-nav`

It opens menu under bottom-nav!

https://codepen.io/anon/pen/yEjwMr

Please let me know how can I solve this problem?

**Comment by jacekkarczmarczyk** [comment]
Please do not comment old issues. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
