### ISSUE TITLE
[Bug Report] Checkbox,radio box issue

### ISSUE THREAD

**Issue by Alex1000A** [vuetifyjs/vuetify#7951]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
copy from here

https://vuetifyjs.com/en/components/selection-controls#checkboxes-boolean

### Expected Behavior
should same as documentation

### Actual Behavior
box missing

### Reproduction Link
<a href="https://github.com/Alex1000A/vuetify/blob/master/index.html" target="_blank">https://github.com/Alex1000A/vuetify/blob/master/index.html</a>

### Other comments
Using cdn,
checkbox,and radio option not work as expect

**Comment by KaelWD** [comment]
Vuetify 2.0 uses https://materialdesignicons.com/ by default

**Comment by Alex1000A** [comment]
Thank it work now!
