### ISSUE TITLE
[Documentation] Italian Support Language

### ISSUE THREAD

**Issue by lucaros97** [vuetifyjs/vuetify#7952]
### Problem to solve
Can you please add Italian to the supported languages for documentation translation?
There was another issue open (https://github.com/vuetifyjs/vuetify/pull/4962) but until now Italian does not appear on the supported languages available for translation.

<img width="499" alt="Schermata 2019-07-24 alle 09 47 18" src="https://user-images.githubusercontent.com/8333004/61774878-1954e700-adf8-11e9-8285-155893efc619.png">

### Proposed solution
Add italian to supported languages available for translation in this page https://vuetifyjs.com/eo-UY/

**Comment by nekosaur** [comment]
Italian has now been added.
