### ISSUE TITLE
[Feature Request] v-btn:before opacity

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#7954]
### Problem to solve
in version 1.5.x

when v-btn click
v-btn:before opacity always zero

but
when v-btn click
in version 2.0.0
v-btn:before opacity not zero

is it true?

when click remain like shadown..

check this..

### Proposed solution
v-btn:before
always opacity zero

**Comment by KaelWD** [comment]
Appears to be intentional (#7519), although I do agree it's probably unwanted.

**Comment by johnleider** [comment]
This is what MD2 specifies but we do provide variables that you can override: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VBtn/VBtn.sass

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
