### ISSUE TITLE
[Bug Report] v-layout wrapping with just "row" prop and not "wrap" prop

### ISSUE THREAD

**Issue by pklitscher** [vuetifyjs/vuetify#7956]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.0.0
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. v-layout with "row" prop only
2. place three children inside where combine flex-basis exceeds 100% 

### Expected Behavior
Children should be maintained on single row 

### Actual Behavior
Children will wrap

### Reproduction Link
<a href="https://codepen.io/pklitscher/pen/rXeJmy" target="_blank">https://codepen.io/pklitscher/pen/rXeJmy</a>

### Other comments
```
.row {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -webkit-box-flex: 1;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    margin-right: -12px;
    margin-left: -12px;
}
```

.row css appears to have wrap set. This was not the case in 1.5.16

I had a look through the migration docs and could not see info about the change. 

Sorry if this is intended behaviour and I am abusing v-layout. 

Thank you for 2.0 - it's like Christmas.

**Comment by KaelWD** [comment]
You're abusing v-layout, `.row` is part of the new grid system and was never actually needed before. 

eslint-plugin-vuetify will now remove it for you: https://github.com/vuetifyjs/eslint-plugin-vuetify/releases/tag/v1.0.0-beta.2

**Comment by pklitscher** [comment]
Oh sweet, cheers @KaelWD . 
Good call on getting rid of row. 
Row is still listed as a prop in the docs and that would be super helpful in the upgrade guide

**Comment by Disorrder** [comment]
it's pain (
![image](https://user-images.githubusercontent.com/2883539/61907802-e82f0080-af36-11e9-875a-6567d434dc56.png)

**Comment by douglasg14b** [comment]
@KaelWD 

>You're abusing v-layout, .row is part of the new grid system and was never actually needed before.

I'd like to note that the 1.x documentation explicitly used the `row` prop in examples... If it wasn't meant to be used/not necessary, the documentation examples probably shouldn't be consistently using it?

**Comment by KaelWD** [comment]
6f502dfeb27ddb8de28eb140aef8857c754b0f92
