### ISSUE TITLE
[Bug Report] Tabs: current tab is not highlighted on initial 

### ISSUE THREAD

**Issue by ldar** [vuetifyjs/vuetify#7959]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chromium 75.0.3770.90
**OS:** Ubuntu undefined

### Steps to reproduce
Tabs are inside list
Notice that the first tab is selected, but it does not have slider-wrapper blue bottom border.

### Expected Behavior
The first tab should have blue underline.

### Actual Behavior
There's no blue underline.

### Reproduction Link
<a href="https://codepen.io/ldar/pen/VoaxOr?editors=1010" target="_blank">https://codepen.io/ldar/pen/VoaxOr?editors=1010</a>

**Comment by johnleider** [comment]
This is resolved as of v2 and will not be back ported.

**Comment by ldar** [comment]
Will version 1.5 be supported until 2020?

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/getting-started/long-term-support
