### ISSUE TITLE
[Bug Report] 'v-app-bar-nav-icon' is not shown

### ISSUE THREAD

**Issue by Octopodo** [vuetifyjs/vuetify#7963]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create a single-file component :

```javascript
<template>
  <nav>
    <v-app-bar >
      <v-app-bar-nav-icon></v-app-bar-nav-icon>
    </v-app-bar>
  </nav>
<template>

<script>
export default {

  }
</script>
```

### Expected Behavior
A navigation icon appears inside `v-app-bar`

### Actual Behavior
The button is there, because I can see the hover effect, but the icon is not shown

### Reproduction Link
<a href="https://codepen.io/Okptopoid/pen/VoaELQ" target="_blank">https://codepen.io/Okptopoid/pen/VoaELQ</a>

**Comment by MajesticPotatoe** [comment]
Seems you are missing icon fonts. Vuetify 2.0 uses `mdi` by default now instead of `md`. 
eg: https://codepen.io/anon/pen/JgXmBL

**Comment by Octopodo** [comment]
Thank, that was my problem. I solved it adding this line to my index.html:
´<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.8.95/css/materialdesignicons.css">`

**Comment by abcdevelop** [comment]
Thanks

**Comment by Hoopie** [comment]
Thanks all. I had the same issue after upgrade to vuetify 2.0. I had updated the icon font correctly correctly to `mdi` but missed the reference to the icon font itself.

Refer to [installing material design icon fonts](https://vuetifyjs.com/en/customization/icons#) for vuetify different options.

**Comment by GermanRuelasCastillo** [comment]
@Octopodo  Thanks! Works perfect!

**Comment by pgh268400** [comment]
> Thank, that was my problem. I solved it adding this line to my index.html:
> 
> `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.8.95/css/materialdesignicons.css">`

Thx a LOT
