### ISSUE TITLE
[Documentation] V1.5 search return 404 page

### ISSUE THREAD

**Issue by lucaros97** [vuetifyjs/vuetify#7965]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
In v1.5 documentation search for something in the docs (ex. "Text Wrapping") and then click on the result

### Expected Behavior
It must be show the page selected from the search results

### Actual Behavior
Show the 404 page for everything you search

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/styles/typography#text-wrapping" target="_blank">https://v15.vuetifyjs.com/en/styles/typography#text-wrapping</a>

![vuetify](https://user-images.githubusercontent.com/8333004/61799427-643c2200-ae2b-11e9-952a-b20d1d3882ab.PNG)

### Other comments
If you navigate to pages from the navbar it works perfectly

**Comment by MajesticPotatoe** [comment]
This unfortunately is not something we have control over. The search is done by algolia and is currently linked to the live docs search. The 1.5 docs doesn't have its own search, so some search links will produce 404's as they don't exist in 1.5 but do in live.

We are in the process of making a `stable` branch for 1.5/LTS in which we will most likely disable the search to prevent confusion. Thank you for the report.

**Comment by johnleider** [comment]
The `stable` branch is now up and v1.5 docs have been updated to remove sections that are no longer relevant (including search).
