### ISSUE TITLE
[Bug Report] MDI SVG Codepen does not load

### ISSUE THREAD

**Issue by chaim0m** [vuetifyjs/vuetify#7968]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
The codepen for mdi svg simply shows text not icons

### Expected Behavior
To show the icons

### Actual Behavior
Shows text

### Reproduction Link
<a href="https://codepen.io/chaim0m/pen/VoaOOq?&editable=true&editors=101" target="_blank">https://codepen.io/chaim0m/pen/VoaOOq?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
There are console errors for that pen, and I'm not even sure if that would work in codepen. I've tested this in a project and it works just fine. If you can reproduce it without errors, even in a repo, please create a new issue.
