### ISSUE TITLE
[Documentation] Clarify vuetify (plugin) vs Vuetify module in bootstrap docs

### ISSUE THREAD

**Issue by appurist** [vuetifyjs/vuetify#7973]
### Problem to solve
The [initial bootstrap example](https://vuetifyjs.com/en/getting-started/quick-start#bootstrapping-the-vuetify-object) shows an import of the Vuetify plugin as `vuetify` and passing that to the Vue constructor.  It seems like a 1.5-style counter-example to the later ones that pass a `new Vuetify()`, but it isn't because it's not the Vuetify module but rather a different one (the plugin wrapper).  This is mostly hidden from new users. It seems like the 2.0 required `new Vuetify()` syntax is being lost (at least it was to me and I was not new to Vuetify) by this example. I asked if there was a simpler alternative  form being shown by this example. The answer was of course no, it's not Vuetify, it's the plugins wrapper.

### Proposed solution
@jacekkarczmarczyk  suggested I create an issue suggesting that this be clarified, perhaps by including the relevant snippet from the `plugins/vuetify.js` file, rather than just mentioning it's relative path.  I'd also like to suggest the plugin import variable be changed from `vuetify` to `vuetifyPlugin` or something that clarifies that it is not the Vuetify module (from `node_modules`).

I don't really want to create a separate issue for this (I think it's the same issue anyway, just less specific) but I think this is one example of the larger problem of the plugins file itself: I'd like to suggest that this plugins wrapper concept is going to cause more trouble than it is worth and that the wrapper code should be snippets that need to go in the main startup file (with the `new Vue` call).  Splitting the `new Vue()` and `new Vuetify()` into separate modules in different folders is more akin to obfuscation of what is effectively all user code, not a core part of Vuetify.  For example, when I needed to change the plugin, I was unclear whether I should, because it seemed to be part of the Vuetify project / CLI plugin.  (It's not, it's user code, generated for me to use, and modify as desired or needed.) In my project, I had to move the plugin initialization to main.js in order to avoid rewriting the plugins wrapper significantly to pass in i18n options for the Vuetify options parameter.  So at the very least, I'd like to suggest that the generated plugins code also be clarified to be user-level code that developers may need to modify and customize according to their needs.

**Comment by longrunningprocess** [comment]
Not sure if this is the best place to ask but please redirect me if needed.  

When I needed translation support in a plain javascript file, I used to grab the `t` function like this in `1.x`:
```javascript
const t = Vue.prototype.$vuetify.t
```

That does not work anymore in `2.0` presumably because of the change to how vuetify is plugged into Vue now.  Is there another way I can grab that `t` function in a plain js file now?

**Comment by longrunningprocess** [comment]
conversation on discord (https://discord.com/channels/340160225338195969/361889521815519233/777973482440753232) looks like `t` might only be available within components as of the `2.0` upgrade.

**Comment by KaelWD** [comment]
The v3 page shows it all in a single file, and `new Vuetify()` is replaced by `createVuetify()` so there shouldn't be any confusion with variable casing.
