### ISSUE TITLE
[Bug Report] There's no .container rule in productuon

### ISSUE THREAD

**Issue by rounce** [vuetifyjs/vuetify#7978]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.71
**OS:** Linux x86_64

### Steps to reproduce
1. vue create test; cd test; vue add vuetify; vue vuild
2. check css file

### Expected Behavior
.container in css file
.container {
    width: 100%;
    padding: 12px;
    margin-right: auto;
    margin-left: auto;
}

### Actual Behavior
no .container rule

### Reproduction Link
<a href="https://github.com/rounce/vuetify_test" target="_blank">https://github.com/rounce/vuetify_test</a>

### Other comments
![dev](https://cdn.discordapp.com/attachments/361889521815519233/603648088888049675/dev-mode.jpg)
![production](https://media.discordapp.net/attachments/361889521815519233/603648143334047744/pro-mode.jpg)

**Comment by jeverduzco** [comment]
Here's some more information: https://github.com/nuxt-community/vuetify-module/issues/67#issuecomment-514792485

**Comment by mardonedias** [comment]
I upgraded to version 2.0.1, but it still has the same problem.

**Comment by rounce** [comment]
@mardonedias, can it be a cache? I upgraded and the problem is gone.

**Comment by mardonedias** [comment]
> @mardonedias, can it be a cache? I upgraded and the problem is gone.

Hello, you're right, it was the cache, thanks.
sorry for the inconvenience

**Comment by nedvajz** [comment]
I am at version Vuetify 2.2 and experiencing same issue. When I force refresh with Dev bar on in Chrome, nothing changes .. so surely no cache problem.
  
On live https://www.exchangehours.com/, there is no container, row or col styles applied at all.  
  
On dev all of these works as expected.

**Comment by nedvajz** [comment]
The solution seems to be obvious now, but it took a while until I realized it was [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) .. aaah ..
   
```
# What I used
<div class="container"> </div>  
  
# What needs to be used  
<v-container> </v-container>  
```  
More here: https://stackoverflow.com/questions/65108642/vuetify-js-class-container-losts-styles-after-npm-run-build/65425266#65425266
