### ISSUE TITLE
Feature Request: Allow set numeric values in falseValue and trueValue

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#798]
## What will it allow you to do that you can't do today?
Allows you to switch between numeric values. For example 1 and 0
## How will it make current work-arounds straightforward?
In many databases, boolean values are stored as numbers: 1 and 0. And on the frontend they are loaded as numbers. And to use this value in the checkbox it is necessary to perform additional transformations to Boolean and back. The ability to configure the checkbox to switch between numbers will greatly simplify the user case
```vue
<v-checkbox v-model="user.is_admin" :true-value="1" :false-value="0" />
```
## What potential bugs and edge cases does it help to avoid?
A numeric value always keeps its type.

**Comment by johnleider** [comment]
The checkbox currently already supports true and false value.

**Comment by cawa-93** [comment]
But I wrote about supporting numbers. It is numbers and not Strings or Booleans

**Comment by johnleider** [comment]
Misunderstood.
