### ISSUE TITLE
[Documentation] Broken V15 documentation

### ISSUE THREAD

**Issue by FoxUSA** [vuetifyjs/vuetify#7980]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Go to https://v15.vuetifyjs.com/en/framework/pre-made-layouts and clock on the google youtube layout(https://v15.vuetifyjs.com/en/examples/layouts/googleYoutube) and click the code pen or source option.

### Expected Behavior
Be directed to a working code pen. Or be directed to the source

### Actual Behavior
Code pen will be blank with console errors indicating the issue was related to the v2.0.0 release. Source cod will redirect to a broken Github page

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/framework/pre-made-layouts" target="_blank">https://v15.vuetifyjs.com/en/framework/pre-made-layouts</a>

### Other comments
A lot of other vuetify plugins and apps are broken across the web due to the v2.0.0 release. I assume the dist link provided was not versioned. Perhaps role it back and provide a new versioned dist link for v2.0.0 since it is the breaking change.

**Comment by MajesticPotatoe** [comment]
seems these broke when we moved 1.5 to `stable` branch. updated now, should see the effects shortly. thanks! 👍 
resolved in 664f78f
