### ISSUE TITLE
[Bug Report] v-snackbar is missing an exit animation

### ISSUE THREAD

**Issue by HeadAdmiral** [vuetifyjs/vuetify#7981]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 2.0.0-beta.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Toggle a snackbar on and off.

### Expected Behavior
Should match this video:
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1smqQHvwlE8Nm5nNwHXgvnJ9JDrOt_CB1%2F01-appear.mp4

### Actual Behavior
 It has an enter animation, but lacks an exit animation. On timeout or when dismissed, it just disappears immediately instead an exit animation.

### Reproduction Link
<a href="https://codepen.io/anon/pen/eqzNKv" target="_blank">https://codepen.io/anon/pen/eqzNKv</a>

### Other comments
I think this was working in 2.0.0-beta.8, but I don't know for certain.

**Comment by MajesticPotatoe** [comment]
This is intended as its a part of MD2 Spec.
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Ox5qX5je_tUiv8P9V9tTfGRTd3RTsvxh%2F02-appearconsecutive.mp4

**Comment by KaelWD** [comment]
@MajesticPotatoe The one in the video still has a slight fade out instead of just disappearing.

**Comment by jacekkarczmarczyk** [comment]
If i see correctly it fades only when user clicks the close btn
