### ISSUE TITLE
[Documentation] Update CSS links in Quick Start documentation

### ISSUE THREAD

**Issue by jcgoodru** [vuetifyjs/vuetify#7987]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.3

### Steps to reproduce
The `<link>` tags in the Quick Start documentation all refer to the latest version of Vuetify.  Given the recent upgrade from `1.5.X` to `2.0.X`, the stylesheet for the `1.5.X` documentation points to the wrong version.  This may be the case for the script tags as well.

### Expected Behavior
Vuetify `1.5.X` documentation should include the following tag in the head:
`<link href="https://cdn.jsdelivr.net/npm/vuetify@1.5.16/dist/vuetify.min.js" rel="stylesheet">`

### Actual Behavior
Vuetify `1.5.X` documentation points to version `2.0.X`
`<link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.js" rel="stylesheet">`

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/getting-started/quick-start" target="_blank">https://v15.vuetifyjs.com/en/getting-started/quick-start</a>

### Other comments
Thank you for all your hard work!

**Comment by jacekkarczmarczyk** [comment]
related to https://github.com/vuetifyjs/vuetify/pull/7979
going to open a new PR for 1.5

**Comment by jacekkarczmarczyk** [comment]
lol pushed directly to `stable` branch
9544b185bb5d1ad1da708accaec009237cbe96a0
