### ISSUE TITLE
[Bug Report] v-list-item ripple effect gets triggered when you click on v-list-item-action

### ISSUE THREAD

**Issue by AssetKid** [vuetifyjs/vuetify#7988]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox, Google Chrome
**OS:** Windows, Mac OSX

### Steps to reproduce
Click v-list-item-action on the demos linked below

1.5.16 - https://codepen.io/anon/pen/YmWWWb
2.0 - https://codepen.io/anon/pen/EqyyyR

### Expected Behavior
Ripple effect should only be on v-list-item-action

https://codepen.io/anon/pen/YmWWWb 

### Actual Behavior
Ripple effect is triggered for both v-list-item and v-list-item-action

### Reproduction Link
<a href="https://codepen.io/anon/pen/EqyyyR" target="_blank">https://codepen.io/anon/pen/EqyyyR</a>

### Other comments
This is a regression from 1.5.x. Not sure if it is a feature or bug.

**Comment by johnleider** [comment]
Not really sure how we can efficiently fix this. `v-list-item` supports ripple now by default. If the same would have been the case for v1.5, it would have been experienced there as well.

https://codepen.io/johnjleider/pen/bXweXq

**Comment by WIStudent** [comment]
For anyone looking for a workaround, I fixed this issue by stopping the propagation of the mousedown and touchstart event inside the action:
```html
<v-list-item :to="someRoute">
  <v-list-item-content>
      <v-list-item-title>Title</v-list-item-title>
  </v-list-item-content>

  <v-list-item-action>
    <v-btn icon @click.prevent="delete" @mousedown.stop @touchstart.native.stop>
      <v-icon>delete</v-icon>
    </v-btn>
  </v-list-item-action>
</v-list-item>
```
`@click.prevent` prevents the `v-list-item` from routing to `someRoute` when clicking on the button inside the action.

**Comment by seankenny** [comment]
I think this may have caused an IE11 bug `Out of stack space`.  Pretty straightforward to repro assuming you have access to IE11 - open in IE11 and click any component with a ripple directive and you will see the issue immediately in the console.

![Screenshot 2021-03-22 at 18 23 32](https://user-images.githubusercontent.com/435556/112039248-bfac3f00-8b3b-11eb-8c7a-f9d949d683d3.png)
![Screenshot 2021-03-22 at 18 23 15](https://user-images.githubusercontent.com/435556/112039279-c89d1080-8b3b-11eb-803e-dc8b7b9347f3.png)

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
