### ISSUE TITLE
[Bug Report] Error With App Bar

### ISSUE THREAD

**Issue by aleverarise** [vuetifyjs/vuetify#7991]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Al utitlizar el component nuevo llamado App Bars se produce un error:
1. TypeError: Cannot read property 'smAndDown' of undefined
2. Error in getter for watcher "computedHeight": "TypeError: Cannot read property 'smAndDown' of undefined"

### Expected Behavior
When using the new component called App Bars an error occurs
1. TypeError: Cannot read property 'smAndDown' of undefined
2. Error in getter for watcher "computedHeight": "TypeError: Cannot read property 'smAndDown' of undefined"

### Actual Behavior
None, give error

### Reproduction Link
<a href="https://codepen.io/aleverarise/pen/ymJMgQ" target="_blank">https://codepen.io/aleverarise/pen/ymJMgQ</a>

### Other comments
Up to now it has been the component that gives error along with the component Toolbar

**Comment by jacekkarczmarczyk** [comment]
Most probably you didn't bootstrap vuetify properly, if you switched to 2.0 please read the release notes and upgrade guide https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide (especially the bootstrapping section)

If the problem still exists please create a new issue with the reproduction that shows the problem

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
