### ISSUE TITLE
[Bug Report] [V-Calendar] [2.0.0] Monthly Calendar using invalid button attribute

### ISSUE THREAD

**Issue by vip30** [vuetifyjs/vuetify#7992]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Use monthly calendar

### Expected Behavior
The event slide bar should be smooth 

### Actual Behavior
The event slide bar is rugged
![image](https://user-images.githubusercontent.com/4260833/61842902-6609f200-aecc-11e9-8331-ab6d73bcc85e.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/gVMmgR?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/gVMmgR?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
`rounded` and `icon` button heights don't match.
