### ISSUE TITLE
[Feature Request] Vuetify 1.5/2 carousel's delimiters don't have right support for a11y

### ISSUE THREAD

**Issue by justvr** [vuetifyjs/vuetify#7996]
### Problem to solve
ay11 issues solved for buttons used in carousel's delimiter.
as you can see there is no `aria-label` in button of the delimiter so the screen readers would read it as 'button' only leaving the users without the real information what is it really about.

https://codepen.io/just-vr/pen/GVqEoV?editors=1000

### Proposed solution
a prop that will deliver an: `id`, `aria-label`, `aria-labelledby`, `title` or maybe not even a prop, maybe just an id that would write out the carousel's item name and number such as 'carousel-item-${number}'. not completely sure what the solution could be, but this might help https://dequeuniversity.com/rules/axe/3.1/button-name?application=lighthouse

```javascript
// example with aria-label
<button type="button" value="0" aria-label="some-title-from-props" class="v-carousel__controls__item v-btn v-item--active v-btn--active v-btn--fab v-btn--flat v-btn--icon v-btn--round theme--dark v-size--small"><span class="v-btn__content"><i aria-hidden="true" class="v-icon notranslate material-icons theme--dark" style="font-size: 18px;">stop</i></span></button>
```

**Comment by cschweda** [comment]
+1.

I saw this flagged on a Lighthouse audit a day or so ago. I'm using Vuetify 2.0.

My hacky (temp, I hope) solution for this was to add the 'aria-label' programmatically in my carousel component:

```
mounted() {
    // a11y fix for nav buttons

    document.addEventListener("DOMContentLoaded", () => {
      let arr = [
        ...document.getElementsByClassName("v-carousel__controls__item")
      ];
      arr.forEach(item => {
        item.setAttribute("aria-label", "navigation button");
      });
    });
  }
```

This passes the Lighthouse audit, but it's obviously not enough. I work for govt agency, and our accessibility guidelines (in a short time) will be (apparently) super-strict -- so I'm hoping this can be fixed in an upcoming release.

**Comment by redahas** [comment]
@jacekkarczmarczyk Havent contributed to the project before before but would like to start. Is this still an issue and if so could it be assigned to me?
