### ISSUE TITLE
[Bug Report] style different with npm run serve and npm run build(v-bottom-navigation and v-dialog)

### ISSUE THREAD

**Issue by cheneyweb** [vuetifyjs/vuetify#7998]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
npm run build

### Expected Behavior
css style correct
![image](https://user-images.githubusercontent.com/24515746/61851886-ab3d1c80-aeea-11e9-9669-de3a7c952339.png)

### Actual Behavior
it only display correct with npm run serve

but the css error with npm run build

the follow css is been remove with npm run build
.v-bottom-navigation--fixed {
    position: fixed;
}

![image](https://user-images.githubusercontent.com/24515746/61852006-f9eab680-aeea-11e9-92ef-a6f4c693ba68.png)

### Reproduction Link
<a href="https://codepen.io/cheneyweb/pen/MNeEVe" target="_blank">https://codepen.io/cheneyweb/pen/MNeEVe</a>

**Comment by jacekkarczmarczyk** [comment]
The simplest fix would be to add `!important`. I'm aware that imporant sux, there are other ways to increase specificity, but i think in this case it's more like trump class (like .text-left etc where we use `!important)

But I think that the proper fix would be to use bottom navigation as a container, so `VItemGroup` should be rendered inside of the navigation instead of mixing these two functionalities:

```js
render () {
  return h('div', { class: 'v-bottom-navigation ...' }, [
    h(VItemGroup, [contents])
  ])
}
```
Wouldn't be that a bit breaking change?

Another thought - app bottom bar could be used a container and make bottom navigation "positionless"

**Comment by cheneyweb** [comment]
@jacekkarczmarczyk 
I have upgrade to vuetify 2.0.1, the v-dialog css style has been fixed，but the v-bottom-navigation's position still error

but I find out npm run serve is the same too! 
now npm run serve & npm run build show the same!

But hat still puzzles me is the usage of v-bottom-navigation，I follow the official doc to copy the code to my project.

Is there any v-bottom-navigation demo for the right way to use? how to make it position fixed on the bottom and make the button style correct? There follow is my layout:

![image](https://user-images.githubusercontent.com/24515746/61921172-c2cde100-af8e-11e9-843b-e0c1884a10f5.png)

![image](https://user-images.githubusercontent.com/24515746/61921184-cd887600-af8e-11e9-9c5e-51969982100d.png)

**Comment by andrewlamyw** [comment]
I'm also having difficulty to make the v-bottom-navigation to fixed at bottom.

**Comment by jacekkarczmarczyk** [comment]
> but the v-bottom-navigation's position still error

That's why the issue is still open. You can override the styles with `.v-bottom-navigation--fixed: { position: fixed !important }` until we fix this

**Comment by cheneyweb** [comment]
> > but the v-bottom-navigation's position still error
> 
> That's why the issue is still open. You can override the styles with `.v-bottom-navigation--fixed: { position: fixed !important }` until we fix this

yes, with override the styles, I have fixed the position problem，but there is still a problem about the v-btn inside the v-bottom-navigation

![image](https://user-images.githubusercontent.com/24515746/61966172-93f25200-b004-11e9-9a91-e1ac80e48b05.png)

The button is not vertically centered，how can I fix this problem?

And will next version of vuetify fix the v-bottom-navigation style?

**Comment by jacekkarczmarczyk** [comment]
Please create a separate issue for button problem

> And will next version of vuetify fix the v-bottom-navigation style?

Probably, no guarantee

**Comment by cheneyweb** [comment]
thanks, I will create another issue for the v-btn

the v-bottom-navigation is really a important component for mobile web app :)

**Comment by lleonk** [comment]
>
> ![image](https://user-images.githubusercontent.com/24515746/61966172-93f25200-b004-11e9-9a91-e1ac80e48b05.png)
> 
> The button is not vertically centered，how can I fix this problem?
> 

The problem is the `height` of the button.

I've fixed this by  adding 

```
#app .v-bottom-navigation .v-btn {
  height: inherit !important;
}
```
in my `App.vue` file.
