### ISSUE TITLE
<v-navbar-items> doesn't load the array from data

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#8]
I hope I'm not missing anything obvious, but the items are not binding for me.

Here's my App.vue:
```
<template>
    <v-app top-navbar footer left-fixed-sidebar>

      <header>
        <v-navbar>
          <v-navbar-logo>Vuetify</v-navbar-logo>
          <v-navbar-items v-bind:items="items"></v-navbar-items>
        </v-navbar>
      </header>

      <main>
        <v-sidebar id="sidebar" fixed left></v-sidebar>
        <v-content>
          <v-container fluid>
            <router-view></router-view>
          </v-container>
        </v-content>
      </main>

      <v-footer></v-footer>

    </v-app>
  </template>

  <script>
    export default {

      data () {
        return {
          items: [
            { text: 'Link', href: '#!' }
          ]
        }
      },

      mounted () {
        this.$vuetify.init()
      }
    }
  </script>
```

![screen shot 2016-12-19 at 12 29 51 am](https://cloud.githubusercontent.com/assets/882713/21299396/5752dd66-c582-11e6-87d8-2926e34f3548.png)

UPDATE: UI wasn't hot reloading automatically. After hitting the refresh the navbar items showed up.

**Comment by Pwntus** [comment]
I thought I had the same problem but for me it was the color of the text that was set to the same color as the background of the sidenav. Why is this and how do I change the text color?

![vuetify](https://cloud.githubusercontent.com/assets/854759/21334636/2cbb4480-c659-11e6-9733-6ce795830be4.jpg)

**Comment by mfferreira** [comment]
@Pwntus I faced the same color issue. It really doesn't make sense and should be changed in the base color scheme.

Anyways, just set the color variables to the color you want in /stylus/main.styl
