### ISSUE TITLE
[Feature Request] Expansion panel content v-model un-deprecation

### ISSUE THREAD

**Issue by aledujke** [vuetifyjs/vuetify#8001]
### Problem to solve
Being able to target individual panel state without using magic numbers or knowing their index

### Proposed solution
Keep the value binding for expansion panel content

I don't get how I am supposed to target individual expansion panel content open/closed state. 

I basically want to be able to type something like `this.someVarThatControllsSingleExpandContent = true`, it looks like using v-model on the parent element is expected here, but that forces me to use magic numbers like `Vue.set(this.panelModel, 2, true)`, which is not pretty at all.

**Comment by aledujke** [comment]
I see now that I was a bit unfamiliar on how to use the the v-model from the parent (v-expansion-panel), it's either a single value that tells which panel should be opened or an array of expansion-panel-content indexes that are supposed to be open. Not like in the example I wrote. In either way I still need to keep a list of indexes to avoid magic numbers that I then need to remember to change if I change my template ordering.

**Comment by johnleider** [comment]
`v-expansion-panels` extends `base-item-group` so this should be an easy implementation.
