### ISSUE TITLE
Regression in toolbar CSS on side icon position (dev branch)

### ISSUE THREAD

**Issue by stephane** [vuetifyjs/vuetify#801]
VuetifyJS docs linked to vuetify dev branch (3775d10bbf67e0596d382d52704d54dfd292807d) produces that menu layout:

![vuetify-toolbar-issue](https://user-images.githubusercontent.com/1815/27336305-69ad734e-55cf-11e7-8fc4-f7a127e308d7.png)

The class `toolbar___side-icon` used by the component https://github.com/vuetifyjs/vuetify/blob/master/src/components/toolbar/index.js#L16 is commented in the stylus file (so undefined):
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_toolbar.styl#L122

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by stephane** [comment]
OK

**Comment by stephane** [comment]
Fixed in current dev
