### ISSUE TITLE
[Bug Report] Issue With V-app 

### ISSUE THREAD

**Issue by kuldeep-porwal** [vuetifyjs/vuetify#8011]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1  please go to console you will see error.

### Expected Behavior
it should work.

### Actual Behavior
it should be load layout of the component.

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/wyYVVj" target="_blank">https://codepen.io/johnjleider/pen/wyYVVj</a>

### Other comments
Please Provide Imediate Solution.

**Comment by jacekkarczmarczyk** [comment]
Vuetify 2.0 changed change the way of bootstrapping, read more in release notes https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide

See the sample codepen https://template.vuetifyjs.com

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
