### ISSUE TITLE
[Feature Request] Support for faSvg in 2.0

### ISSUE THREAD

**Issue by basselAhmed** [vuetifyjs/vuetify#8016]
### Problem to solve
Allows the use of Fontawesome SVG icons

### Proposed solution
This was implemented in 1.5 but was removed in 2.0 not sure why, maybe we could copy over the code from 1.5 over to 2.0? I could help with a PR if you approve.

**Comment by garlian** [comment]
Documentation states that "faSvg" is an option:
https://vuetifyjs.com/en/customization/icons#install-font-awesome-svg-icons

But VuetifyIconOptions is missing "faSvg", so the documented usage is not possbile right now :-(

For example see here:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/services/icons.d.ts#L13
and here
https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/services/icons/presets

**Comment by basselAhmed** [comment]
@garlian Yea that's why I opened this issue, I have a fork updated with the necessary code to make faSvg work but I am waiting on Vuetify's team approval of this issue as they might have removed faSvg support for a reason.

**Comment by DRoet** [comment]
Yeah im pretty sure this is a valid regression, so feel free to PR

**Comment by KaelWD** [comment]
blame: #6464, bf709a1f5c47214d2cd9eff73b83bb4438793236

The original feature #4910 was probably done after whatever bf709a1f5c47214d2cd9eff73b83bb4438793236 got cherry-picked from.
