### ISSUE TITLE
[Bug Report] Applying @click="$emit('clicked')" on v-card causes ripple when clicked

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8017]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create a v-card element and apply `@click="$emit('clicked')"` to the component. Click anywhere in the card.

### Expected Behavior
You should not see a ripple when you click the card.

### Actual Behavior
The card ripples when clicked.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/GVjKGY" target="_blank">https://codepen.io/MatthewAry/pen/GVjKGY</a>

**Comment by jacekkarczmarczyk** [comment]
I don't see the reason why the ripple wouldn't show. You may want to do some action, for example "add to cart" that shouldn't turn off the ripple, you can use `@click.native` or force the ripple to be turned off using `ripple` prop
https://codepen.io/anon/pen/mNrbvQ

**Comment by MatthewAry** [comment]
I did not add the v-ripple directive. That's why it should not show up.

**Comment by jacekkarczmarczyk** [comment]
But we're adding it internally when there's a click handler - this is intended behaviour (`v-list-item` is similar). And if you don't need it you can turn it off as I showed in the codepen

**Comment by MatthewAry** [comment]
Then is this behavior in the docs?

**Comment by jacekkarczmarczyk** [comment]
It's not there, definitely it should. And here is another one solution: https://codepen.io/anon/pen/EqgxKo
