### ISSUE TITLE
[Bug Report] Cannot disable ripple for <v-tab>

### ISSUE THREAD

**Issue by jHellmundt** [vuetifyjs/vuetify#8023]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
Set ripple="false" for a v-tab

### Expected Behavior
Ripple effect disabled for clicking that tab

### Actual Behavior
Ripple effect stays

### Reproduction Link
<a href="https://codepen.io/anon/pen/wVzGrN" target="_blank">https://codepen.io/anon/pen/wVzGrN</a>

### Other comments
In the Vuetify Docs it stated that v-tap has a prop for ripple. I guess it should allow me to disable the ripple effect for that tab, but well... it doesn't.
I think it would also be nice to have the option to turn off ripple in v-taps.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/oKzxJE
