### ISSUE TITLE
[Bug Report] 10 shows up in pagination options even when overridden

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8026]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Open pagination options

### Expected Behavior
Only the specified array [50,60,70] should be the options.

### Actual Behavior
[10,50,60,70] shows up!!!!!!!!!!!!!!!!!

### Reproduction Link
<a href="https://codepen.io/anon/pen/NQRRzY?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/NQRRzY?&editable=true&editors=101</a>

### Other comments
https://stackoverflow.com/questions/57210397/vuetify-2-10-showing-up-in-pagination-options-even-though-set-a-new-array

**Comment by johnleider** [comment]
Workaround for now is explicitly defining the default itemsPerPage:

![image](https://user-images.githubusercontent.com/9064066/61918271-69c26680-af16-11e9-910a-912637a55e39.png)

**Comment by TheInvoker** [comment]
This is still an issue.
https://codepen.io/anon/pen/NQRRzY?&editable=true&editors=101
it alerts the options.itemsPerPage which is 10.
