### ISSUE TITLE
[Bug Report] Text color does not change for disabled button w/ >1 text color property

### ISSUE THREAD

**Issue by morphatic** [vuetifyjs/vuetify#8030]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create a `<v-btn>` instance. Assign multiple text color modifiers. Disable it, e.g.

```js
<v-btn
  color="primary--text text--darken-2"
  :disabled="true"
/>
```

### Expected Behavior
The text of the button gets greyed out.

### Actual Behavior
The text of the button does not change color.

### Reproduction Link
<a href="https://codepen.io/morphatic/pen/eqJwEP" target="_blank">https://codepen.io/morphatic/pen/eqJwEP</a>

### Other comments
May have been caused by and/or be related to https://github.com/vuetifyjs/vuetify/commit/c5dae24d

**Comment by nekosaur** [comment]
Your assumption is correct. The change in css specificity that followed when adding `.v-application` to colors caused this bug.

**Comment by sh7dm** [comment]
Just a specifity issue

**Comment by phil-rw** [comment]
Is this truly a bug? Our design purposefully keeps some color on disabled buttons (typically significantly lowers the opacity). By making the code change that this is related to which was introduced in 2.0.6, it appears we've lost the ability to specify any colors for disabled state. Would Vuetify be willing to remove this and be less opinionated on this manner?

**Comment by morphatic** [comment]
Yes, it is a bug because it deviates from [the official Material 2.0 spec for button styles](https://material.io/design/components/buttons.html). Vuetify specifically aims to hew as close to this spec as possible. The spec is clear and explicit about what the disabled state should look like for all button styles. It's totally fine if you want to deviate from the spec in your own app, but [the buggy version](https://codepen.io/morphatic/pen/yLBexdp) unexpectedly fails to grey out the button text when developers specify colors with more than one rule.

You're still able to override the default style with your own custom CSS. Here's an (admittedly awful to look at) example using the latest, non-buggy version: https://codepen.io/morphatic/pen/jONWeEG

**Comment by phil-rw** [comment]
Got it! Thank you for the detailed explanation @morphatic - makes sense. 👍
