### ISSUE TITLE
[Documentation] Premium theme parallax link doesn't work 

### ISSUE THREAD

**Issue by Sabbir-Noire** [vuetifyjs/vuetify#8031]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Go to the Vuetify documentation. Click on the premium theme section. Click on the parallax theme. 

### Expected Behavior
Should show an live theme of the parallax. 

### Actual Behavior
Shows blank 

### Reproduction Link
<a href="https://vuetifyjs.com/themes/parallax-starter/?ref=vuetifyjs.com" target="_blank">https://vuetifyjs.com/themes/parallax-starter/?ref=vuetifyjs.com</a>

**Comment by ThomasMcDonnell** [comment]
I am also experiencing the same issue, 

**Environment**
Browsers: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
OS: MacOs 10.14.6

Ubuntu: LTS 18.04

**Comment by johnleider** [comment]
Can you try again? This is working as far as I can see.

**Comment by Sabbir-Noire** [comment]
@johnleider It's working now !!!

**Comment by Myenny** [comment]
where do i find this https://store.vuetifyjs.com/products/parallax-theme-free/preview repo?
