### ISSUE TITLE
[Documentation] Doesn't show the logo of pre-made layout

### ISSUE THREAD

**Issue by Sabbir-Noire** [vuetifyjs/vuetify#8032]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
In documentation > Getting started > Pre-made layouts > Click on the "Link to Layout to . . ." > Click on the code example link here > In the example pen, the logo doesn't show

### Expected Behavior
Should show the logo

### Actual Behavior
Not showing the logo.

### Reproduction Link
<a href="https://vuetifyjs.com/en/examples/layouts/google-youtube" target="_blank">https://vuetifyjs.com/en/examples/layouts/google-youtube</a>

**Comment by jacekkarczmarczyk** [comment]
Missing MDI and FA icons imports, applies also to other layouts

**Comment by inkexit** [comment]
@MajesticPotatoe  What we would need to change in John's code to make it work properly?

**Comment by MajesticPotatoe** [comment]
Read the comments from the original issue. If it is not working locally, it is most likely you are using a different icon set or you do not have mdi icons installed and bootstrapped correctly. 

Feel free to reach out to the [Discord community](https://community.vuetifyjs.com) if you need assistance.

**Comment by inkexit** [comment]
You don't "install" webfonts or icons.  You link to them in the header.

If anyone else is looking for an answer of how to get these icons to show,  adding these links to the header makes them visible:

`<link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" as="style" rel="preload" onload="this.rel='stylesheet'">

<link href="https://cdn.jsdelivr.net/npm/@mdi/font@3.x/css/materialdesignicons.min.css" rel="stylesheet">`

However, it does not fix the problem of the "Source" and "Codepen" icons not being centered horizontally, they are still on the far left.

**Comment by MajesticPotatoe** [comment]
Not entirely true, yes you can link them in header, but you can also install some via npm/yarn depending on your setup and how you are using them (eg: offline usage or if you dont like relying on cdns ).

As stated above, john needs to update the codepens which is why this is still open.

**Comment by github-grabaz** [comment]
Still not fixed?  I was going to file a bug report but found that there have been several already started.

I am just getting started with vuetify and I turn to the examples when something doesn't work for me and the broken examples aren't helping!

Can someone bump up the priority on this?  This would be much appreciated from everyone new to Vuetify!  

Thx
