### ISSUE TITLE
[Documentation] No searchbar for v1.5 documentation

### ISSUE THREAD

**Issue by kgoel085** [vuetifyjs/vuetify#8034]
### Environment

**Browsers:** Firefox 69.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows 10, Windows, Linux, Mac OSX, iOS, Android

### Steps to reproduce
Visit https://v15.vuetifyjs.com/en/getting-started/quick-start

### Expected Behavior
On the left hand sidebar before the version 2.0 was released, there was a search bar which helped to search for a specific component or feature of vuetify. But now there is no search bar on the v1.5 documentation but the same is available on the v2.0.0 documentation. Please bring back the v 1.5 documentation search bar as it helped to sort through components easily

### Actual Behavior
On the left hand sidebar before the version 2.0 was released, there was a search bar which helped to search for a specific component or feature of vuetify. But now there is no search bar on the v1.5 documentation but the same is available on the v2.0.0 documentation. Please bring back the v 1.5 documentation search bar as it helped to sort through components easily

### Reproduction Link
<a href="https://v15.vuetifyjs.com/en/getting-started/quick-start" target="_blank">https://v15.vuetifyjs.com/en/getting-started/quick-start</a>

### Other comments
On the left hand sidebar before the version 2.0 was released, there was a search bar which helped to search for a specific component or feature of vuetify. But now there is no search bar on the v1.5 documentation but the same is available on the v2.0.0 documentation. Please bring back the v 1.5 documentation search bar as it helped to sort through components easily

**Comment by kgoel085** [comment]
V 1.5 vuetify documentation

![image](https://user-images.githubusercontent.com/38721303/61930356-180fef80-af9b-11e9-8737-88c8f3b4eb29.png)

V 2.0.1 vuetify documentation
![image](https://user-images.githubusercontent.com/38721303/61930449-5efde500-af9b-11e9-8b9f-33059a305ab3.png)

**Comment by nekosaur** [comment]
This is intentional. Our search is powered by algolia and we are only scraping the main documentation to generate the search results. Searching on 1.5 would lead to incorrect search results since the content has changed. We have therefore disabled search on 1.5

**Comment by madebycaliper** [comment]
@nekosaur I understand the logic behind your decision but it makes maintenance/development on any 1.X branch WAY more difficult than it used to be. Is there any simple search replacement you can implement? Or even an alphabetical list of component names with quick links to docs? I just spent a few minutes looking for the `v-select` docs and couldn't even begin to find it...I don't have the bandwidth or budget to update my project from 1.5 to 2.0 and I feel pretty stuck.

Thanks for your time.

**Comment by timothymarois** [comment]
I would also like to ask for this feature as it is very frustrating now that the docs have shifted to v2.

**Comment by vellebelle** [comment]
Yes.. I agree. It's really frustrating not being able to search the 1.5 docs anymore :( There must be a way.
