### ISSUE TITLE
[Bug Report] Datatables Disabled Sort Key is still showing on small screens

### ISSUE THREAD

**Issue by msforbes09** [vuetifyjs/vuetify#8036]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Open the Codepen link

### Expected Behavior
Disabled keys must not be present in dropdown selection

### Actual Behavior
All keys are visible

### Reproduction Link
<a href="https://codepen.io/msforbes09/full/zgKaOY" target="_blank">https://codepen.io/msforbes09/full/zgKaOY</a>

**Comment by msforbes09** [comment]
is this PR update already available for using?

**Comment by nekosaur** [comment]
No, it will go out in next release.

**Comment by RoboBurned** [comment]
I think we should completely hide sort select instead of disabling it.  This is how it works in Desktop mode now.
