### ISSUE TITLE
v-list-item-icon not recognized

### ISSUE THREAD

**Issue by bestickley** [vuetifyjs/vuetify#8043]
The element v-list-item-icon isn't recognized as a component in Vuetify 2.0.1:
[Vue warn]: Unknown custom element: <v-list-item-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by andresmerida** [comment]
@bestickley , I have the same proble but I can see it was reported as issue on it: [https://github.com/vuetifyjs/vuetify/pull/8080](url) . Only wait, it is open yet.
