### ISSUE TITLE
[Bug Report] Datatables in V2 cannot make use of the body and expand slot at the same time

### ISSUE THREAD

**Issue by waffshappen** [vuetifyjs/vuetify#8045]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Create a v-data-table

Use both the body and expanded-item v-slot
Try to expand the item by manually placing the item in the array for the :expanded.sync

In the pen if you rename the body slot you can instantly see it expand without the custom body on load.
Example: https://codepen.io/anon/pen/mNradJ

### Expected Behavior
The expanded item should render below the custom body. 

### Actual Behavior
The expanded item is not showing up

### Reproduction Link
<a href="https://codepen.io/anon/pen/voXQRM" target="_blank">https://codepen.io/anon/pen/voXQRM</a>

### Other comments
As said, this used to work in 1.5 and still does.

**Comment by nekosaur** [comment]
This is expected behaviour. When you use the `body` slot, you override all of the internal row rendering of the table. If you need expand functionality, you will have to provide it yourself inside the slot.

I'm not sure what you mean by it working in 1.5. There is no `body` slot in 1.5

**Comment by waffshappen** [comment]
> This is expected behaviour. When you use the `body` slot, you override all of the internal row rendering of the table. If you need expand functionality, you will have to provide it yourself inside the slot.
> 
> I'm not sure what you mean by it working in 1.5. There is no `body` slot in 1.5

Oh, right - In 1.5 i used the "items" slot - and body seemed to have replaced it to me because it was the closest in syntax.
With the "item" slot in 2 it works as expected.
