### ISSUE TITLE
[Bug Report] Small icons in navigation drawer are not correctly aligned

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#8046]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
Set v-list to nav and dense, and icons to small

### Expected Behavior
icons should be small and horizontally aligned with the tile content, at least with the tile title.

### Actual Behavior
Icons are aligned to the top of the tile. 

### Reproduction Link
<a href="https://codepen.io/anon/pen/BXLGXz" target="_blank">https://codepen.io/anon/pen/BXLGXz</a>

### Other comments
I tried using the dense prop from v-icon which sounds like the most logical thing to apply in this case but it doesn't seem to have any effect.

**Comment by johnleider** [comment]
For spec, list-icons are aligned to start. We are only going to support the default use-case (officially), but you can easily remedy this with a helper class.

https://codepen.io/johnjleider/pen/eqBZvO

**Comment by ThomasKuhlmann** [comment]
@johnleider perfect, thanks for the explanation!
