### ISSUE TITLE
[Bug Report] Not registered v-list-item-icon

### ISSUE THREAD

**Issue by FFxSquall** [vuetifyjs/vuetify#8047]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Clone repo https://github.com/FFxSquall/vue-loader-bug
`npm i`
`npm run serve`

### Expected Behavior
Component registered correctly

### Actual Behavior
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <v-list-item-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by KaelWD** [comment]
Need to go through every component folder and make sure $_vuetify_subcomponents is correct

**Comment by buzzzzer** [comment]
VSimpleCheckbox the same

**Comment by scientronic92** [comment]
I have the same issue, I tried #8080 solution but the problem seems persistent. any solutions, please?
