### ISSUE TITLE
[Bug Report] V-Dialog click:outside event handler has Void parameters (fixing | the v-dialog closes on outside when mouse released)

### ISSUE THREAD

**Issue by Xambey** [vuetifyjs/vuetify#8055]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Linux x86_64

### Steps to reproduce
1. Open the dialog
2. Left-click on the dialog
3. Without releasing the button, move the cursor outside the dialog
4. Release the button

### Expected Behavior
it is impossible to know the state of the mouse (keys). I would like to be able to prevent the closure of the dialogue if the left mouse button is released outside. Or maybe there is some other hidden property that can fix this? 

### Actual Behavior
The Click:outside handler doesn't have an object with a description of the event. 

### Reproduction Link
<a href="https://codepen.io/xambey/pen/gVwypP" target="_blank">https://codepen.io/xambey/pen/gVwypP</a>

### Other comments
I think this should be related with #6969 issue

**Comment by diazemiliano** [comment]
@xambey you mean to use a modal dialog?
https://vuetifyjs.com/en/components/dialogs#modal

**Comment by Xambey** [comment]
@diazemiliano ok, but it still seems to me that adding an object with information about the state of the mouse to the click.outside event will be easier and more correct. What you offer is only suitable as a temporary solution. Perhaps it would be even better if the dialog had a property at all, allowing you to control the closing of the dialog box if you release the mouse

**Comment by diazemiliano** [comment]
@Xambey I agree, that's what I said it was a **workaround**.  Labeling this as a bug.

**Comment by arnovanoordt** [comment]
Apart form the "persistent" workaround there doesn't seem to be a way to catch a close event and stop the dialog from closing. Adding an event that can be canceled or stopped to the @click:outside handler would be the cleanest solution.

**Comment by NoahStahl** [comment]
I'm hitting this as well, trying to handle the keydown.esc and click:outside to conditionally close the dialog. I can't seem to stop the dialog from closing itself -- is there any way to prevent this?

**Comment by KaelWD** [comment]
This was fixed in f11d8454320a671392bf96c9076b2f39d29d11e6
