### ISSUE TITLE
[Bug Report] Using v-img in a v-avatar prevents the v-img slot contents from being shown correctly.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8056]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Use this code:
```
      <v-avatar>
        <v-img src="https://placekitten.com/200/300" alt="avatar">
          <v-icon class="white--text">check</v-icon>
        </v-img>
      </v-avatar>
```

### Expected Behavior
You should see a white checkmark icon over the kitten image.

### Actual Behavior
The white checkmark is not visible.

In v-img there is an inner div with the class `v-responsive__content` which has a style property applied with a width of 400px. I don't think this style property should be there as the width is somehow cascading to the icon.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/rXMOEr" target="_blank">https://codepen.io/MatthewAry/pen/rXMOEr</a>

**Comment by KaelWD** [comment]
#5783

Guess it should've been a prop after all.
