### ISSUE TITLE
[Bug Report] Missing search from v15.vuetifyjs.com

### ISSUE THREAD

**Issue by alexcroox** [vuetifyjs/vuetify#8057]
### Environment
**Vuetify Version:** 1.5.14
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Visit https://v15.vuetifyjs.com/en/getting-started/quick-start

### Expected Behavior
A search bar at the top of the sidebar like there used to be

### Actual Behavior
Missing search bar

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by Mikilll94** [comment]
I have also noticed that!

**Comment by MajesticPotatoe** [comment]
This is intended. v15 docs search was removed in 3bf0fa0.

**Comment by Jcroxford** [comment]
I don't understand this decision. Can someone clarify why the search functionality needs to be removed from legacy docs?

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/8034#issuecomment-515349730

**Comment by Jcroxford** [comment]
To bad! Makes the legacy docs harder to use for sure. But, sounds like a decent sized project to change that.

Thanks @jacekkarczmarczyk!
