### ISSUE TITLE
[Bug Report] v-tabs show-arrows won't take effect in an extended v-toolbar if v-tabs is not at the root of v-slot:extension

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8063]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
In v-toolbar, add v-slot:extension slot with:
- div
 - v-tabs

Open up browser dev tools and enable mobile simulation mode. Change viewport width to be smaller than the tab row length. Note the absence of the arrows.

### Expected Behavior
Tab arrows should appear when the tabs are rendered outside of the viewport. (It's more complicated than that but you get the point)

### Actual Behavior
Tab arrows are not showing up.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/WVoevg" target="_blank">https://codepen.io/MatthewAry/pen/WVoevg</a>

### Use case for not requiring tabs be kept at root of slot
I'm using portal-vue to render and unrender content from the v-app-bar's extension slot. In one of these situations, I want to have a v-divider between the tabs and the toolbar content. Problem is, portal-vue wraps everything up into its own div. I can set a parameter in portal-vue to not do this, but that means that I need to wrap everything into my own div to ensure that there is a root node in the contents of the portal-target. If I want to put a v-divider in along with my v-tabs, I have to wrap it in some sort of node. For some reason, doing this makes it so v-tabs won't render the arrows on narrow screens when they should.

**Comment by KaelWD** [comment]
Your extra div doesn't shrink
![image](https://user-images.githubusercontent.com/16421948/61964915-657b7380-b012-11e9-915b-acae4c40c835.png)

You need to add a couple of styles to match how tabs behave
```html
<div class="d-flex flex-grow-1 mx-n4" style="width: 100%">
```

**Comment by MatthewAry** [comment]
Great! Thanks!
