### ISSUE TITLE
[Bug Report] letter-spacing in rtl languages

### ISSUE THREAD

**Issue by eyadfareh** [vuetifyjs/vuetify#8065]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Safari, Microsoft Edge, Internet Explorer, Mozilla Firefox, Opera, Other
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
v-btn

### Expected Behavior
no letter spacing in Arabic 

### Actual Behavior
there is letter spacing in Arabic

### Reproduction Link
<a href="https://codepen.io/eyadfareh/pen/wVovBb?editors=1100" target="_blank">https://codepen.io/eyadfareh/pen/wVovBb?editors=1100</a>

**Comment by johnleider** [comment]
Workaround for now would be to manually remove the letter-spacing with css as you have demonstrated in your example..

**Comment by eyadfareh** [comment]
the bug is not in all RTL languages, but in some aphabet,  some RTL languages like Hebrew has no problem with letter spacing

**Comment by melbahja** [comment]
Workaround: Add in your App.vue style:

```css
.v-application--is-ltr .v-btn {
    letter-spacing: 0 !important;
}
```

**Comment by johnleider** [comment]
@nekosaur would it make sense to have typography values as css variables so that this could be modified easier?

**Comment by KareemDa** [comment]
Any updates for this issue ?
