### ISSUE TITLE
[Bug Report] 2.0.x component won't work for functional component

### ISSUE THREAD

**Issue by xiaoshuw** [vuetifyjs/vuetify#8069]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a simple application
and a simple component, in this case, MyHello.vue

### Expected Behavior
Expect the chip to render correctly

### Actual Behavior
The chip is not rendered. The console shows the following error.

vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <v-chip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

However, remove the "functional" from the MyHello component will make it work. Similar component works in 1.5.x version of vuetify.

### Reproduction Link
<a href="https://github.com/xiaoshuw/vuetify-2-bug" target="_blank">https://github.com/xiaoshuw/vuetify-2-bug</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/customization/a-la-carte#limitations
