### ISSUE TITLE
[Feature Request] Data Tables in scrollable dialogs should have a sticky header (or a way to make it possible)

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8070]
### Problem to solve
If you put a data table into a dialog and that data table has more rows than can be shown on one page (which can happen even with pagination) then you can make the dialog scrollable so you can scroll to see the rest of the rows. The nice thing about scrollable dialogs is that when you use a card, the title and the action areas of the card stick to the top and bottom respectively. The unfortunate thing is that the data table headers don't come along for the ride which makes us lose context to the rows' contents.

### Proposed solution
There are a lot of ways that this can be approached and I'm not sure if there are any perfect ones. But, perhaps an additional property could be added to v-data-table which when set to true, will obtain a height value from it's parent node. This can be done by using resizeObserver (yes it might need to have a polyfill) to detect changes to the parent's height.

Any thoughts or ideas?

**Comment by nekosaur** [comment]
There is a `fixed-header` prop on v-data-table

**Comment by MatthewAry** [comment]
Yes, and I tried it, but I don't think it works unless you specify a table height.

**Comment by nekosaur** [comment]
That is correct, and the current intended usage

**Comment by jacekkarczmarczyk** [comment]
Should be in docs

**Comment by MatthewAry** [comment]
@nekosaur If you're talking about adding a height to a data-table to make the fixed header work, than yes, I don't disagree with that. 

Yet I'm are talking about putting a data-table into a dialog with an unknown height. If I tried to apply a height to a data-table inside of a dialog, than its possible that on a smaller screen the table height will be too big and it will cause the dialog and the data-table to scroll. I'm trying to avoid that. If the maximum height of a dialog is determined by screen size then we don't have a way to ensure that a data-table inside of it doesn't end up exceeding the size of it's parent element.

Like I was trying to say in the original issue (which I didn't do a very good job of), if there was some way to dynamically set the height for the data-table, It can avoid problems like having a double scroll bar in the dialog (one being on the data-table and another being on or in the dialog).

**Comment by MajesticPotatoe** [comment]
> If the maximum height of a dialog is determined by screen size then we don't have a way to ensure that a data-table inside of it doesn't end up exceeding the size of it's parent element.

if the max-height of the dialog is determined by screen size, then you should be able to calculate a height of what the data-table should be (theoretically speakin. I do this currently with fixed header datatables on a single page to make them responsive to screen resize).

I think the major hurdle is the more you add in conjunction with the data-table on the vertical plane the more complicated the logic becomes 🤷‍♂

**Comment by MatthewAry** [comment]
Just ran into this issue again and I had an idea. Generally, a VDialog gets used like this most of the time:
```
VDialog
   VCard
      VCardTitle
      VCardText
      VCardActions
```
If VDialog has the scrollable prop applied, then why can't VCardText's default slot have a slot prop which can inform it's children it will be scrollable?

I think VDataTable can be engineered to support sticky headers without having to set a height. It would likely require getting the Element height of it's parent and comparing it against its own height, while also have a ResizeObserver applied. It would calculate if it needs a sticky header by determining if it's larger than the height of it's parent and recalculate if it needs to continue to be sticky when the height of it's parent or itself changes. Currently the `position: sticky;` CSS property has poor support, but I think that can be worked around by using CSS `absolute` and `relative` functions.

According to CanIUse, ResizeObserver has 89% support in the global browser market and there are some polyfills (they have their caveats though) that can be used with a fallback. Combined with requestAnimationFrame and a debouncer, it could be pretty performant.

Obviously this could require a bit of reengineering work, so it might be something better saved for V3 but it would be super handy....

Thoughts? Can V3 get this at least? Could we make it so height is not required for sticky headers in VDataTable?
