### ISSUE TITLE
[Documentation] FA icons don't work

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8077]
### Environment

**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Move mouse cursor over the reproduction link, press left button

### Expected Behavior
FA icons are displaying

### Actual Behavior
FA icons are not displaying

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/icons#font-awesome" target="_blank">https://vuetifyjs.com/en/components/icons#font-awesome</a>

### Other comments
It works in v15: https://v15.vuetifyjs.com/en/components/icons#font-awesome
Codepen works on firefox: https://codepen.io/anon/pen/ymVOKm?&editable=true&editors=101
Everything works in chrome/edge

**Comment by malgamves** [comment]
They seem to be present if you inspect the webpage but not visible for some reason. Trying to figure out why. This was using Firefox on Deepin

**Comment by MajesticPotatoe** [comment]
This seems to be working.
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Works for me in firefox 80 on linux.

**Comment by jacekkarczmarczyk** [comment]
Looks fine on windows too (v79 & v80). Might be a problem with old version of firefox

**Comment by MajesticPotatoe** [comment]
These are working in current version of firefox and chrome.
