### ISSUE TITLE
[Bug Report] Remove vuetify theme stylesheet from page source

### ISSUE THREAD

**Issue by udanpe** [vuetifyjs/vuetify#8082]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OS 10.14.5

### Steps to reproduce
Fresh install

### Expected Behavior
Should remove stylesheet

### Actual Behavior
Does not remove stylesheet

### Reproduction Link
<a href="https://codepen.io/anon/pen/bXBevd" target="_blank">https://codepen.io/anon/pen/PMbjaM</a>

### Other comments
After upgrading to v2 (theme: false)  not work more. Previous issue https://github.com/vuetifyjs/vuetify/issues/3349
<img width="894" alt="Screen Shot 2019-07-27 at 12 06 13" src="https://user-images.githubusercontent.com/7540232/61992460-71ddeb80-b067-11e9-8e5e-3c6dea6db515.png">

**Comment by clixmat** [comment]
I have the same problem, I have verified in forums and issues and the problem persists they have not yet solved it ...

**Comment by johnleider** [comment]
I've also updated the v2.0 upgrade guide.

**Comment by S1ipKn0T** [comment]
i have the same problem with vuetify nuxtjs! can anyone help me?

**Comment by udanpe** [comment]
@S1ipKn0T 
```
const vuetify = new Vuetify({
  theme: { disable: true },
})
```

**Comment by BonBonSlick** [comment]
@udanpe  theme disable doe not work
```
 vuetify:      {
        customVariables: ['~/assets/variables.scss'],
        theme:           {
            disable: true,
```
still, **theme--light** applied

**Comment by marvix** [comment]
Is it fixed? I have the same problem with the latest version.

**Comment by jacekkarczmarczyk** [comment]
Documentation has been updated, if you're following the docs and it still doesn't disable the theme please create a new issue and provide reproduction

**Comment by daviesdoclc** [comment]
Ugh. Just came across this today while moving a project from Vuetify 1.x to 2.x.  The light theme is applied to lots of components.  All my v-cards have an opacity applied to the text, where it didn't before.  Hope someone figures this out.

**Comment by samnau** [comment]
Nuxt appears to pass along the correct Vuetify config options, but it has no affect on whether or not the theme is applied.
```
// auto generated options.js from nuxt.config.js
export default {"theme":{"dark":false,"disable":true}}
```
```
// config applied in the auto generated plugins.js from Nuxt
import Vue from 'vue'
import Vuetify from 'vuetify'

import options from './options'

Vue.use(Vuetify, {
})

export default (ctx) => {
  const vuetifyOptions = typeof options === 'function' ? options(ctx) : options

  vuetifyOptions.icons = vuetifyOptions.icons || {}
  vuetifyOptions.icons.iconfont = 'mdi'

  const vuetify = new Vuetify(vuetifyOptions)

  ctx.app.vuetify = vuetify
  ctx.$vuetify = vuetify.framework
}
```

**Comment by rarangels** [comment]
> @S1ipKn0T
> 
> ```
> const vuetify = new Vuetify({
>   theme: { disable: true },
> })
> 
> ['@nuxtjs/vuetify', {
>   theme: { disable: true },
> }]
> ```

Works for me

**Comment by marctorresbcn** [comment]
The solution of disable: true not works :( 

I'm working with the last version of Vuely Theme (https://themeforest.net/item/vuely-vuejs-admin-template/21247764)

`import Vue from 'vue'
import Vuetify from 'vuetify'
// store
import { store } from '../store/store';

Vue.use(Vuetify);

export default new Vuetify({	
	theme: { disable: true /*
		themes: {
			light: store.getters.selectedTheme.theme,
			dark: store.getters.selectedTheme.theme
		},
	*/},
})`
