### ISSUE TITLE
[Bug Report] Untranslated "Sort by" label in VDataTableHeaderMobile

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8083]
### Steps to reproduce
https://github.com/vuetifyjs/vuetify/blob/v2.0.1/packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts#L42

**Comment by WhatFreshHellIsThis** [comment]
This does not seem to have exposed a property to set alternate translated text for "Sort by", did I miss that aspect of this?
