### ISSUE TITLE
[Bug Report] Immediate parent of current page is auto-disabled in v-breadcrumbs

### ISSUE THREAD

**Issue by manastalukdar** [vuetifyjs/vuetify#8084]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Edge 77.0.223.0
**OS:** Windows 10

### Steps to reproduce
1. Go to link `/blog/tags/` by clicking on the `Blog - Tags` button in the home page from the codesandbox repro.
2. While the final breadcrumb item (also the current page) `Tags` (/blog/tags/) is disabled (expected behavior), its immediate parent `Blog` (/blog/) is also disabled.

### Expected Behavior
The immediate parent of the current page is not disabled in the breadcrumbs.

### Actual Behavior
The immediate parent of the current page is disabled in the breadcrumbs.

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-5uv1u" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-5uv1u</a>

**Comment by mrgr4v1ty** [comment]
i think there is a problem with :to prob, If i use :href its fine but for :to prob on v-breadcrumbs all items are disabled

**Comment by jacekkarczmarczyk** [comment]
Use `exact: true` in your items https://codepen.io/anon/pen/ymVXZb?editors=1010
