### ISSUE TITLE
[Feature Request] Fix Carousel component to a specific aspect ratio

### ISSUE THREAD

**Issue by shadowdreamer** [vuetifyjs/vuetify#8086]
### Problem to solve
easy to fix the carousel component to a specific aspect ratio

### Proposed solution
do like this
```
<v-responsive :aspect-ratio="16/9">
    <v-carousel>
        <v-carousel-item v-for="item in [url1,url2]" :key="item" :src="item"> 
        </v-carousel-item>
    </v-carousel>
</v-responsive>
```
or
```
    <v-carousel :aspect-ratio="16/9">
        <v-carousel-item v-for="item in [url1,url2]" :key="item" :src="item"> 
        </v-carousel-item>
    </v-carousel>
```
but , is there some way to do this in current version?

**Comment by diazemiliano** [comment]
@shadowdreamer in latest version the images inside the carousel are using...
``` css
.v-image__image--cover {
    background-size: cover;
}
```
So you can set a custom aspect ratio with `<v-carousel style="width:...px; height:...px">` to the carousel component and the images will always cover the entire carousel. Like here https://codepen.io/diazemiliano/pen/OKjggm

**Comment by shadowdreamer** [comment]
@diazemiliano thanks to comment,but I means in any width of window, how carousel compoent can keep max width and auto fix heigth to a aspect ratio.
actrully,i did this in a project:
`
<template>
<v-flex xs12>
  <v-carousel cycle :height="carouselHeight">
    <v-carousel-item
        v-for="item in ['url1','url2']"
         :key="item"
         >
            <v-img :height="carouselHeight" :src="item" @click="checkImg(item)"/>
          </v-carousel-item>
    </v-carousel>
  </flex>
</template>
<script>
export default {
 computed: {
    carouselHeight () {
      switch (this.$vuetify.breakpoint.name) {
        case "xs":
          return "200px"
        case "sm":
          return "320px"
        case "md":
          return "360px"
        case "lg":
          return "400px"
        case "xl":
          return "420px"
      }
    }
}
</script>
`
but it's seems a bad solution,I hope there is a better way to do this
