### ISSUE TITLE
Feature request: multiple date selection in v-date-picker

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#809]
On every date select do not reset previous selection

**Comment by adrianbarbe** [comment]
Thank you guys for Vuetify!
I need this feature (multiple dates select).

Can you tell when you plan to include this in production package (as I saw there is PR)?
Can I help with something for this feature?

**Comment by jacekkarczmarczyk** [comment]
I'll revisit it this weekend

**Comment by DiegoAyalaE** [comment]
Just adding a +1 for this feature. It would be great. Thanks!
