### ISSUE TITLE
[Bug Report] prepend icon not show

### ISSUE THREAD

**Issue by fachrizalrifahdi** [vuetifyjs/vuetify#8090]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
The prepend icon is not show

### Expected Behavior
the prepend icon must be show

### Actual Behavior
the prepend icon not show

### Reproduction Link
<a href="https://codepen.io/anon/pen/XvNMdB" target="_blank">https://codepen.io/anon/pen/XvNMdB</a>

### Other comments
https://ibb.co/cbKtkQF

**Comment by jacekkarczmarczyk** [comment]
You're using Material Icons but you're not importing them
https://vuetifyjs.com/en/customization/icons
