### ISSUE TITLE
[Documentation] active button is invisible in bottom nav example

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8093]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
click the button

### Expected Behavior
should be visible

### Actual Behavior
is not visible
![image](https://user-images.githubusercontent.com/15625235/61993052-4c041700-b066-11e9-9e63-9cdcc3128442.png)

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/bottom-navigation#scroll-threshold" target="_blank">https://vuetifyjs.com/en/components/bottom-navigation#scroll-threshold</a>

**Comment by renoirb** [comment]
I can't really see the issue, on macOS Firefox 82, it shows well.

I don't have access to a Windows OS, maybe someone else can have a look?

## Screenshots

### Firefox 82 macOS

<img width="915" alt="vuetify-issues-8093-14 16 22" src="https://user-images.githubusercontent.com/296940/102803649-562f5f80-4397-11eb-9c34-e25b509786ae.png">

**Comment by neelansh15** [comment]
I can confirm. The active tab disappears, but only in the *scroll-threshold* example.
My System Info:
```
Microsoft Edge (Chromium): 
  88.0.705.74 (Official build) (64-bit)
  Revision: 498de26f3a841db44fe68b74f2d05bb9f2464147
Windows 10 OS Version 2004 (Build 19041.804)
```
**Screenshots:**  
![image](https://user-images.githubusercontent.com/53081208/108681398-1ca0df00-7515-11eb-9cb4-5c1ad5574c02.png)
![image](https://user-images.githubusercontent.com/53081208/108681667-6d183c80-7515-11eb-8b73-0ae369decb84.png)
