### ISSUE TITLE
[Documentation] category page looks empty

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8094]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Click the category button
![image](https://user-images.githubusercontent.com/15625235/61993084-ca60b900-b066-11e9-8a23-3ccce435c814.png)

### Expected Behavior
?

### Actual Behavior
goes to empty page https://vuetifyjs.com/en/components/categories/forms

Hmm, there are some links to components, maybe it's intended, but imho it looks like an empty page, there might be maybe some text?

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/api-explorer" target="_blank">https://vuetifyjs.com/en/components/api-explorer</a>

**Comment by MajesticPotatoe** [comment]
This page no longer exists in new docs. related #10301
