### ISSUE TITLE
[Bug Report] VCalendar - [Vue warn]: Failed to resolve directive: ripple

### ISSUE THREAD

**Issue by Apther** [vuetifyjs/vuetify#8096]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10, Windows

### Steps to reproduce
1) Add calendar __with event__ (use the provided git with example from docs)
2) Check console

### Expected Behavior
No warning

### Actual Behavior
Console:

[Vue warn]: Failed to resolve directive: ripple
(found in <VCalendar>)

### Reproduction Link
<a href="https://github.com/Apther/vuetify-calendar-ripple-bug.git" target="_blank">https://github.com/Apther/vuetify-calendar-ripple-bug.git</a>

### Other comments
Probably missing import in vuetify/lib/components/VCalendar/mixins/calendar-with-events.js :

    import ripple from '../../../directives/ripple'

and directive in CalendarBase.extend:

    directives: {
        ripple
    }

But I'm not sure if it's correct solution.

Another way to solve it was importing vuetify from vuetify (not vuetify/lib), but since version 2.0.1 it destroys some styles, so it's not usable.

**Comment by KluseG** [comment]
Same in v2.0.2, no ripple effect on event "bar" and [Vue varn] in console

**Comment by ClickerMonkey** [comment]
Thanks for the issue, creating a PR to fix this soon.

**Comment by jild** [comment]
Same for using <v-data-table>
with Code example from https://vuetifyjs.com/en/components/data-tables/#crud-actions

And using a custom slot with a checkbox:
    <template v-slot:item.linked="{ item }">
      <v-simple-checkbox
          v-model="item.linked"
      ></v-simple-checkbox>
    </template>

If the checkbox is disabled everything works perfectly. 
Otherwise I get:

[Vue warn]: Failed to resolve directive: ripple

**Comment by TheDevMinerTV** [comment]
This issue should be reopened, as it still appears on `v-simple-checkbox`.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
