### ISSUE TITLE
[Documentation] codepen.io don't work

### ISSUE THREAD

**Issue by TomishaCom** [vuetifyjs/vuetify#8099]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
If you want to use the codepen. Opens an empty code page without content.

### Expected Behavior
If you want to use the codepen. Opens an empty code page without content.

### Actual Behavior
If you want to use the codepen. Opens an empty code page without content.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/simple-tables" target="_blank">https://vuetifyjs.com/en/components/simple-tables</a>

**Comment by jacekkarczmarczyk** [comment]
They won't work in codepen because of how html works
https://codepen.io/anon/pen/MNbQVN?editors=1000
