### ISSUE TITLE
[Feature Request] Rounded dialogs

### ISSUE THREAD

**Issue by dotvirus** [vuetifyjs/vuetify#8100]
### Problem to solve
Dialogs leave a strange phantom shadow when using heavily-rounded cards, which makes them a little bit unattractive.

MD2: https://material.io/design/components/dialogs.html#theming

Vuetify: https://codepen.io/dotvirus/pen/NQbYpK

### Proposed solution
Add a 'rounded' prop to Dialogs? Rounded dialogs also need more padding, especially near the actions.

**Comment by nekosaur** [comment]
You need to use the `content-class` prop instead, because the border-radius needs to be applied one step further up the hierarchy.

https://codepen.io/anon/pen/dxOrJK

**Comment by danielskeeled** [comment]
Is there a way to make it work when the dialog is vertically scrollable?

[https://codepen.io/iskilled/pen/JjoxabQ](https://codepen.io/iskilled/pen/JjoxabQ)

**Comment by nekosaur** [comment]
You could do something like this https://codepen.io/nekosaur/pen/JjozOWM

Please do not comment on closed issues. If you have any questions join us in our chat instead at https://community.vuetifyjs.com
