### ISSUE TITLE
[Bug Report] Extended toolbar doesn't take extension height into account

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8101]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create extended toolbar, provide height and extension height

### Expected Behavior
Toolbar height should be sum of main area an extension

### Actual Behavior
Toolbar height is same as main area height

### Reproduction Link
2.0
<a href="https://codepen.io/anon/pen/BXQrob?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/BXQrob?&editable=true&editors=101</a>
1.5
https://codepen.io/anon/pen/oKYqbp?editors=1010

### Workaround
https://codepen.io/anon/pen/gVLezJ?&editable=true&editors=101

### Other comments
`measurableStyles` called in `VToolbar::styles` is not aware of extension height:

Following fix worked in my case, but may need to be tested more thoroughly
```diff
--- a/packages/vuetify/src/components/VToolbar/VToolbar.ts
+++ b/packages/vuetify/src/components/VToolbar/VToolbar.ts
@@ -94,7 +94,10 @@ export default VSheet.extend({
       return this.prominent
     },
     styles (): object {
-      return this.measurableStyles
+      return {
+        ...this.measurableStyles,
+        height: this.computedHeight,
+      }
     },
   },
```

**Comment by johnleider** [comment]
Checked this fix and everything was working as expected.

**Comment by jacekkarczmarczyk** [comment]
I meant this https://codepen.io/jkarczm/pen/pozLYje?editors=1000 @johnleider
