### ISSUE TITLE
[Feature Request] add debounce functionality to delayable mixin

### ISSUE THREAD

**Issue by morphatic** [vuetifyjs/vuetify#8103]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create a `<v-tooltip>` with `debounce="2000"` (or any number). The debounce effect is not applied.

### Expected Behavior
The appearance/disappearance of the tooltip should be delayed 2 seconds.

### Actual Behavior
There is no delay.

### Reproduction Link
<a href="https://codepen.io/morphatic/pen/QeGrKv" target="_blank">https://codepen.io/morphatic/pen/QeGrKv</a>

### Other comments
The [`debounce` prop is defined on the component](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VTooltip/VTooltip.ts#L29) but never associated with any functionality.

[There is a `debounce` helper defined](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/util/helpers.ts#L453), but it appears only to be used internally [by the `VVirtualTable` component](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VDataTable/VVirtualTable.ts#L12) related to scrolling. I could not find any other places that it was used.

It seems logical to add the `debounce` prop and/or the `debounce` helper to [the `Delayable` mixin](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/mixins/delayable/index.ts). It could be a "shortcut" prop that is an alias for using both the `open-delay` and `close-delay` props.

I don't know if there was any history of having the `debounce` prop in earlier versions of Vuetify that might make it desirable to keep around for backwards compatibility.

Of course, the easiest solution is just to remove it from `VTooltip` and the docs, since the behavior is already available via the `open/close-delay` props.

I couldn't really find any other uses of debounce functionality throughout the framework, so I don't know how much sense it makes to keep it around. Does it have broader applicability?

**Comment by johnleider** [comment]
So I'm going to handle this one a little differently. This prop has existed for a long time but has never officially been hooked up. Due to this fact, I'm going to remove the prop and update the documentation.

I'll convert this issue to a feature request and triage accordingly.

**Comment by johnleider** [comment]
This has been added to Vuetify 3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
