### ISSUE TITLE
[Feature Request] Reset nav drawer scroll to top when opened

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8104]
### Problem to solve
When you open a nav drawer, and then scroll down, then close it. Then open it again, I expect it to be scrolled to top again. But currently it retains it's scroll state which is annoying. Having a prop would solve that. Currently I have to do this which is not good

    watch : {
        'drawer_state' : function(new_val, old_val) {
            // if drawer opened, reset scroll to top
            if (new_val) {
                this.$el.querySelector(".v-navigation-drawer__content").scrollTop = 0;
            }
        }
    }

### Proposed solution
Having a prop that sets scrollTop to 0 when opening the nav drawer.

**Comment by diazemiliano** [comment]
Reproduction link: https://codepen.io/diazemiliano/pen/mNMyYa

**Comment by jacekkarczmarczyk** [comment]
@diazemiliano what information are you missing?

**Comment by diazemiliano** [comment]
It's isn't created through issues.vuetifyjs.com as a feteature request.

**Comment by TheInvoker** [comment]
I did create it through a feature request.

**Comment by diazemiliano** [comment]
@TheInvoker @jacekkarczmarczyk My fault! sorry.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
