### ISSUE TITLE
[Feature Request] Hide main scrollbar when dialog is open

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8105]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Click the pink button to open dialog. 

### Expected Behavior
The main page which has a scroll bar, should hide when the dialog is open. This is because you shouldn't be able to scroll on the main page anyways, and it gives a little extra room horizontally (or vertically) for the dialog. Plus since the dialog is almost full width, it looks bad to see 2 scroll bars next to each other. 

### Actual Behavior
The main scroll bar still appears when dialog is open.

### Reproduction Link
<a href="https://codepen.io/anon/pen/VomBbd" target="_blank">https://codepen.io/anon/pen/VomBbd</a>

### Other comments
Can it be changed to hide the main page scrollbars (up/down/left/right) while dialog is open?

**Comment by diazemiliano** [comment]
@TheInvoker Not sure this is a bug. And for sure is something that you can control based on the `v-model` state of the dialog or using events to listen when the dialog is opened to set the `overflow: hidden` where you need it.

**Comment by TheInvoker** [comment]
I had my own solution for this, but if this is a popular thing to do, might as well come by default from the framework?

**Comment by Dylan-Chapman** [comment]
Just wanted to add to this. It looks like dialogs add the `overflow-y-hidden` class to the main `<html>` element. However, utility classes are now scoped to `.v-application`, which `<html>` is outside of, and thus the class has no effect.

**Comment by Traxo7** [comment]
Thanks @&#xfeff;Dylan-Chapman, that seems to be correct.
So the temporary workaround is to add the following css:   
```
html.overflow-y-hidden {
  overflow-y: hidden
}
```

**Comment by Traxo7** [comment]
Thanks @&#xfeff;Dylan-Chapman, that seems to be correct.
So the temporary workaround is to add the following css
   
```
html.overflow-y-hidden {
  overflow-y: hidden
}
```

**Comment by TheInvoker** [comment]
But that needs some js to add  and remove that class to the html tag right?

**Comment by Traxo7** [comment]
@TheInvoker JS already exists apparently - class is added/removed properly on `html` tag. So only the CSS that provided is enough until Vuetify updates it's JS (or perhaps CSS?) accordingly.

**Comment by TheInvoker** [comment]
yeah i just noticed that too. I think it would be better if main content scroll is disabled in general is a dialog is active.

**Comment by KaelWD** [comment]
It was done to prevent a layout jump afaik. See #10086 for the other thing.
