### ISSUE TITLE
[Bug Report] Ripple effect for icons not extending to the whole button in Appbar

### ISSUE THREAD

**Issue by JeremiahPinto** [vuetifyjs/vuetify#8107]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
For this bug to happen, the button must:
1. be in a `toolbar`/`app-bar`
2. be contained in the `v-toolbar-items` tag
3. have `icon` prop on the button

### Expected Behavior
The ripple on click of the button should extend to the whole button

### Actual Behavior
On click, the ripple only extends to a circle (assuming to be the default button size of an icon button)

### Reproduction Link
<a href="https://codepen.io/anon/pen/JgbBzB" target="_blank">https://codepen.io/anon/pen/JgbBzB</a>

**Comment by nekosaur** [comment]
This happens because we apply the `circle` option for v-ripple when v-btn has `icon` prop.

**Comment by diazemiliano** [comment]
Same example as above with a standalone button https://codepen.io/diazemiliano/pen/gVxReW

**Comment by KaelWD** [comment]
Only use `<v-btn text>` in v-toolbar-items.
