### ISSUE TITLE
[Feature Request] Giving every visual component "transition" prop

### ISSUE THREAD

**Issue by Granathar** [vuetifyjs/vuetify#8109]
### Problem to solve
I recently encountered problem with v-app-bar as it seems completely "immune" to any transition effects. Probably it has his own transition inside that overwrites any <transition> element around it. I don't know how many such components are there, but they may be pain in the ass as we would have to move whole page or other things together with them, because we just can't do anything to them directly.

If every visible component could take custom transition to override it's default one (like v-alert) it would spare me few hours of thinking "how can I give some animation to appearing v-app-bar?".

### Proposed solution
Every visible component should be able to take custom transition as prop OR being wrapped by transition should override it's internal transitions if it has any.

**Comment by diazemiliano** [comment]
@Granathar can you provide an example to have a better understanding on what your trying to achieve?

**Comment by Granathar** [comment]
Looks like jsfiddle doesn't like transitions too much, at least with Vuetify - I personally create my app with CLI.

Generally speaking there are some elements that are not affected by <transition></transition> - for example v-app-bar mentioned earlier (at least it didn't work for me). Even if they are inside, they appear instantly because they have some kind of their own transition inside. Probably nothing other than setting !important flag in CSS would work.

Wrapping v-alert with v-scale-transition like that didn't work too:

`<v-scale-transition>
    <v-alert></v-alert>
</v-scale-transition>`

Yet v-alert has it's own "transition" prop, so this of course works:
`<v-alert transition="scale-transition"></v-alert>`

So my point is that tag transitions are not consequent. They sometimes work, sometimes don't, and it's not good because often you don't have "transition" prop to set. Every visual element should be affected by <transition>, even if it's element that has "transition" prop or his own internal transitions OR every visual element just should have "transition" prop so you can set it or disable it.

**Comment by johnleider** [comment]
In regards to the alert transition issue, this is being tracked here https://github.com/vuetifyjs/vuetify/issues/8272 . It has to do with the css minification ordering issues.

As far as adding the transition prop to more components than what is already designated, that is not something we are looking to do at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
