### ISSUE TITLE
Menu does not close if you open dialog from it

### ISSUE THREAD

**Issue by ravlio** [vuetifyjs/vuetify#811]
### Steps to reproduce

Put `Dialog` inside `Menu` item causes menu remaining.
### Versions

0.12.7
### What is expected ?

menu need to be closed

### What is actually happening ?

Open the menu. Then click on item, dialog will opens, but menu will remain.
### Reproduction Link

go to https://codepen.io/anon/pen/xrdNaB and click on "OPEN" button.

**Comment by johnleider** [comment]
This is related to #730, and has been resolved.
