### ISSUE TITLE
[Feature Request] Add pageText prop to v-data-footer

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8110]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
See the footer in the table, it does not use the custom one I specified.

### Expected Behavior
It should display 'ooff' in the middle.

### Actual Behavior
It showing the default 'of'.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pMNxzO?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/pMNxzO?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
This is not a bug. There is no `page-text` prop in `v-data-footer`. Currently if you need to customize that text, you will need to create your own translation file as described [here](https://vuetifyjs.com/en/customization/internationalization).

An argument could certainly be made that the prop _should_ exist, but that's a feature request.

**Comment by TheInvoker** [comment]
Which version of 2.1 will this come out on?
