### ISSUE TITLE
[Bug Report] v-tab to prop disables active value

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#8113]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Open the link

### Expected Behavior
The selected/active tab should be index 2 as in the script

### Actual Behavior
the selected/active tab will be index 0 

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-gsxvj" target="_blank">https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-gsxvj</a>

### Other comments
if you remove the to prop then the selected/active tab will be index 2 as in the script. But the to prop disables this functionality.

**Comment by KaelWD** [comment]
- You don't have vue-router installed
- `to` uses the route's path as a value

**Comment by gadelkareem** [comment]
But I would like to use to without a router-view. I handle the router via code. IMHO the value should override the router value if exists.
