### ISSUE TITLE
[Bug Report] v-progress-linear background-color prop covers progress

### ISSUE THREAD

**Issue by davidbkay** [vuetifyjs/vuetify#8114]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox, Safari, Google Chrome
**OS:** Mac OS 10.14

### Steps to reproduce
Add a v-progress-linear component that includes a value and background color prop.

### Expected Behavior
Vuetify 1.5 used class to fill the background to 100%, background-color prop to fill the buffer and color to show the value.

![image](https://user-images.githubusercontent.com/16613132/62002308-38d56380-b0c7-11e9-8eac-052200a63523.png)

https://codepen.io/davidbkay/pen/RXoqXz

```
<v-progress-linear
    value="45"
    buffer-value="70"
    color="cyan"
    height="45"
    background-color="grey"
    class="grey lighten-2"
    buffer>
      <v-layout justify-space-between>
        <h1 class="title font-weight-regular pa-3">School</h1>
        <h1 class="title font-weight-regular pa-3">45%</h1>
      </v-layout>
</v-progress-linear>
```

According to the 2.x docs, I should be able to recreate this with:
https://codepen.io/davidbkay/pen/xvRQBj?editors=1010

```
<v-progress-linear
    value="45"
    color="cyan"
    height="45"
    buffer-value="70"
    class="grey lighten-2"
    background-color="grey">
        <v-layout
            row
            justify-space-between
            class="px-5">
                <strong>School</strong>
                <strong>45%</strong>
        </v-layout>
</v-progress-linear>
```

### Actual Behavior
The buffer color (background-color prop) actually sits over the value bar...if you don't lower the opacity it actually hides the value bar completely if the buffer value > value.

![image](https://user-images.githubusercontent.com/16613132/62002307-1b07fe80-b0c7-11e9-8866-2f59d02ba5c7.png)

### Reproduction Link
<a href="https://codepen.io/davidbkay/pen/xvRQBj?editors=1010" target="_blank">https://codepen.io/davidbkay/pen/xvRQBj?editors=1010</a>

### Other comments
I guess I'll play with the CSS tomorrow to see what works.

**Comment by davidbkay** [comment]
apparently adding `position:absolute;` to `.v-progress-linear__determinate` solves the issue...not sure if it breaks anything else though.

**Comment by nekosaur** [comment]
I'm.. not sure what I should be looking at here. For me, the reproduction link does not look like the image you posted (Chrome/Win10 & MacOS). Here is how it looks for me, which is correct I think?

![chrome_5XSuAuhbiO](https://user-images.githubusercontent.com/623137/62003871-c80d6600-b11d-11e9-98b4-bef1334948fd.png)

**Comment by davidbkay** [comment]
Sorry I was playing with the CSS last night and my temporary fix unconnected...the repro link now shows the current state.
