### ISSUE TITLE
[Bug Report] Chip group slider in touch mode in RTL has the wrong direction

### ISSUE THREAD

**Issue by seyed-me** [vuetifyjs/vuetify#8116]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Fix the direction of the slider in RTL mode

### Expected Behavior
When swiping to the right, the slider does not back to the left. 

### Actual Behavior
When swiping to the right, the slider will back to the left. 

### Reproduction Link
<a href="https://codepen.io/seyed_me/pen/XvNONv?&editable=true&editors=101" target="_blank">https://codepen.io/seyed_me/pen/XvNONv?&editable=true&editors=101</a>

**Comment by MOAB7698** [comment]
hi I use nuxt and vuetify": "^2.6.1 but I still have problem
