### ISSUE TITLE
[Bug Report] v-chip-group changes styling behaviour of v-chips

### ISSUE THREAD

**Issue by paul-a-byford** [vuetifyjs/vuetify#8119]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. create a v-chip-group with 2 vchips in it - one default and one outlined
2. set color of default chip to primary

### Expected Behavior
1. default chip to have text color white
2. outlined chip text to be visible and have an outline

### Actual Behavior
default chip has text color black

### Reproduction Link
<a href="https://codepen.io/pbyford/pen/aeBdvQ" target="_blank">https://codepen.io/pbyford/pen/aeBdvQ</a>

### Other comments
a. the issue seems to be due to how v-chip-group styling overrides vchip styling. 
b. there is a second related issue when using the dark attribute. i attempted to set the v-chip-group dark attribute as a work around. This work around fixes the styling of the default chip, but breaks the styling of outlined vchips, by making the outlined chip seemingl disappear (as outline color and text color are changed to the same as the background).

see 3 examples in codepen

**Comment by johnleider** [comment]
There is not much that we can do about this, it's the intended way for it to work. If you want to modify chip color, use the **color** prop on the `v-chip-group` component. We don't specifically configure the group to work with multiple variations of chips and if you want to do that, it's pretty easy to accomplish manually with `v-item-group`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by gurumzip** [comment]
This issue is already closed but I leave this comment for helping who is looking for same question.
When you want to change text color of v-chip in v-chip-group, reference this code[https://codepen.io/pbyford/pen/aeBdvQ](url)
