### ISSUE TITLE
[Bug Report] VDataTable - slot for footer.page-text doesn't work

### ISSUE THREAD

**Issue by piotrbulinski** [vuetifyjs/vuetify#8120]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
See Code Pen for sample code.

### Expected Behavior
Footer should show: "Items: 1 - 1"

### Actual Behavior
Footer shows default: "1-1 of 1"

### Reproduction Link
<a href="https://codepen.io/piotrbulinski/pen/OKbKpN" target="_blank">https://codepen.io/piotrbulinski/pen/OKbKpN</a>

**Comment by piotrbulinski** [comment]
Related to #8110 ?

**Comment by PetrPy** [comment]
True, have the same issue.

**Comment by sideng** [comment]
True, have the same issue too.

**Comment by nekosaur** [comment]
Please just use the thumbs up reaction on original post. That way we can actually measure the impact of an issue.
