### ISSUE TITLE
[Bug Report] RTL: v-list-item-action has margin-right instead of margin-left

### ISSUE THREAD

**Issue by engmah** [vuetifyjs/vuetify#8125]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Set vuetify to RTL mode and add a list with list-item-action or list-item-icon slot

### Expected Behavior
expected a proper margin between the item list icon and item list content

### Actual Behavior
no margin between item list icon and item list content

### Reproduction Link
<a href="https://codepen.io/engmah/pen/oKBjwE" target="_blank">https://codepen.io/engmah/pen/oKBjwE</a>

### Other comments
I think generated css should have something like:

    .v-application--is-rtl .v-list-item__action:first-child,.v-application--is-rtl .v-list-item__icon:first-child{
      margin-right:0;
      margin-left:32px;
    }

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/7861
