### ISSUE TITLE
[Bug Report] Spacing issue with an app absolute inset footer

### ISSUE THREAD

**Issue by tomparle** [vuetifyjs/vuetify#8128]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Hi,

see attached codepen to see the issue :
- use a footer with the `app absolute inset` properties inside a `v-app` with contains a navigation drawer
- to see the issue, make the footer contain some items with, for instance, a `justify-end` layout

### Expected Behavior
the footer should be properly sized and all its items visible (ok in Vuetify 1.5)

### Actual Behavior
the footer items overflow on the right, as if the footer width was not properly computed with the drawer

### Reproduction Link
<a href="https://codepen.io/tomparle/pen/MNJaXb" target="_blank">https://codepen.io/tomparle/pen/MNJaXb</a>

**Comment by MrJmpl3** [comment]
The problem is the Footer have width: 100% , solved with width:auto 

https://codepen.io/mrjmpl3/pen/VopjNd
