### ISSUE TITLE
[Bug Report] wrong styling of v-switch inset in RTL mode

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#8130]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
`<v-switch inset>`

### Expected Behavior
![image](https://user-images.githubusercontent.com/15625235/62014066-7fe15880-b19c-11e9-9fe8-268941766f48.png)
(or opposite, idk)

### Actual Behavior
![image](https://user-images.githubusercontent.com/15625235/62014062-6a6c2e80-b19c-11e9-8194-aefaed8382c3.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/zgNrXe?editors=1000" target="_blank">https://codepen.io/anon/pen/zgNrXe?editors=1000</a>

**Comment by Dinver** [comment]
v-switch gets out of the container
![000033](https://user-images.githubusercontent.com/36528841/62114565-93391480-b2bf-11e9-8afd-895dd78db217.jpg)
