### ISSUE TITLE
[Bug Report] VDataTable with all items filtered out does not display 'no-results-text'

### ISSUE THREAD

**Issue by dsanders11** [vuetifyjs/vuetify#8131]
### Versions and Environment
**Vuetify:** 2.0.2
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. Use `filter: () => false` for a header

### Expected Behavior
Since all results are filtered out, 'no-results-text' should be displayed

### Actual Behavior
Table displays no rows

### Reproduction Link
<a href="https://codepen.io/anon/pen/MNJypL" target="_blank">https://codepen.io/anon/pen/MNJypL</a>

### Other comments
This behavior is especially inconsistent if you have both filters and and search available on a table, as when there is a search query 'no-results-text' will be displayed when all items are filtered out, but with no search query, nothing is displayed.

**Comment by gsmitto** [comment]
Hi, 
   im having a similar issue calling the v-slot:no-results.

 https://codepen.io/gsmitto/pen/EqvaGX

**Comment by MajesticPotatoe** [comment]
@gsmitto unrelated. response in discord.

**Comment by gsmitto** [comment]
> Hi,
> im having a similar issue calling the v-slot:no-results.
> 
> https://codepen.io/gsmitto/pen/EqvaGX

Corrected and working! Thank @MajesticPotatoe
