### ISSUE TITLE
[Bug Report] Extend component in Typescript

### ISSUE THREAD

**Issue by MrJmpl3** [vuetifyjs/vuetify#8132]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Extend the component in Typescript

### Expected Behavior
Nothing type error

### Actual Behavior
I have the type error:

Value of type '(VueConstructor<Vue> & { $_vuetify_subcomponents?: Record<string, ComponentOrPack>; }) | (FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>> & { ...; } & VueConstructor<...>) | (ComponentOptions<...> & ... 1 more ... & VueConstructor<...>)' is not callable. Did you mean to include 'new'?

### Reproduction Link
<a href="https://gist.github.com/MrJmpl3/1fd0fc22973319000754e1f6da1f376c" target="_blank">https://gist.github.com/MrJmpl3/1fd0fc22973319000754e1f6da1f376c</a>

### Other comments
If I use @ts-ignore in the component , work perfect

**Comment by MrJmpl3** [comment]
The problem is related from this type
```
export type ComponentOrPack = Component & {
  $_vuetify_subcomponents?: Record<string, ComponentOrPack>
}

declare module 'vuetify/lib/components/*' {
  import { ComponentOrPack } from 'vuetify'
  import { VueConstructor } from 'vue'

  const VuetifyComponent: {
    // FIX: The & VueConstructor is a lie.
    // This might not be a valid component.
    // But registering arbitrary objects as components is the status quo.
    default: ComponentOrPack & VueConstructor
    [key: string]: ComponentOrPack & VueConstructor
  }

  export = VuetifyComponent
}
```

**Comment by KaelWD** [comment]
There are no plans to change this, you should be using composition instead of extending in most cases. To support this we'd have to generate type definitions including all internal component properties.

**Comment by Shinigami92** [comment]
> [...] we'd have to generate type definitions including all internal component properties.

Is it just time consuming? Can we help in anyway with this?
Is it possible to not do all at once but step by step?

If component properties are typed, we also could later benefit from it while passing properties through html/pug templates

**Comment by KaelWD** [comment]
There are tools to do it automatically, it's not something I want to support though especially with the changes coming in v3.
