### ISSUE TITLE
[Bug Report] [VNavigationDrawer] mini-variant.sync doesn't reflect the correct value if expand-on-hover is set true

### ISSUE THREAD

**Issue by myleslee** [vuetifyjs/vuetify#8133]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Set `expand-on-hover` to `true`, move mouse over and off the drawer and observe the value of `mini` which is bound to `mini-variant.sync`. The value doesn't change regardless.

If `expand-on-hover` is set to `false`,  `mini` becomes 'live' again.

### Expected Behavior
`mini-variant.sync` should give true or false when the drawer switches between mini and normal state, with `expand-on-hover` set to true.

### Actual Behavior
`mini-variant.sync` stops responding to the drawer's mini-variant state.

### Reproduction Link
<a href="https://codepen.io/myleslee/pen/JgbMVP" target="_blank">https://codepen.io/myleslee/pen/JgbMVP</a>

**Comment by cb109** [comment]
Came up again on the Discord today. These are the relevant code areas:
- https://github.com/vuetifyjs/vuetify/blob/2ad27f604fb1e3f228224bf6e046c81ec067eca8/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts#L134
- https://github.com/vuetifyjs/vuetify/blob/2ad27f604fb1e3f228224bf6e046c81ec067eca8/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts#L363-L366
