### ISSUE TITLE
[Bug Report] VSpeedDial transition does not work with tooltips

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#8135]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Hover on button.

Only green fab without tooltip has a transition

### Expected Behavior
Transitions

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/anon/pen/jgyBea" target="_blank">https://codepen.io/anon/pen/jgyBea</a>

**Comment by sh7dm** [comment]
Duplicate of #8159, closed in e8dbd0b
