### ISSUE TITLE
[Bug Report] When v-table-data is nested in v-expantion-panel,  horizontal scroll doesn't work.

### ISSUE THREAD

**Issue by nysopua** [vuetifyjs/vuetify#8136]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Vivaldi 2.5.1525.40
**OS:** Windows 10

### Steps to reproduce
when window is narrowed too much, You'll see the bug in the v-data-table nested in the v-expantion-panel

### Expected Behavior
Horizontal scroll 

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/nysopua/pen/xvgdEK" target="_blank">https://codepen.io/nysopua/pen/xvgdEK</a>

**Comment by nekosaur** [comment]
Workaround is to add `overflow: auto` to `v-expansion-panel-content__wrap`
