### ISSUE TITLE
[Bug Report] v-subheaders no longer automatically collapse in a mini nav-menu

### ISSUE THREAD

**Issue by JamesDeegan** [vuetifyjs/vuetify#8137]
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
In the codepen open the nav drawer via the toggle button. Then toggle to mini mode, via another toggle button. You'll notice the v-subheader is still in the mini nav menu and the text looks terrible.

### Expected Behavior
via css classes v-subheaders should be hidden when in a nav menu with class "mini"

### Actual Behavior
the v-subheaders remain visible in the mini nav menu

### Reproduction Link
<a href="https://codepen.io/anon/pen/bXgYxb?&page=1" target="_blank">https://codepen.io/anon/pen/bXgYxb?&page=1</a>

**Comment by kulkoff** [comment]
<v-list-item-subtitle> also does not fold

**Comment by johnleider** [comment]
resolved by d7d2d6918

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
