### ISSUE TITLE
[Feature Request] Provide a slot to the tree-node itself

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#8138]
### Problem to solve
I tried to do some stuff when right-click on a node (parent/leaf), or to do something when hovering (like showing 'X' icon next to the label).
Many things could work well (i.e. any native attribute) and I think it's a necessary thing.

Currently the suggested slots are for small parts in the node, hence native attributes work only if you aim exactly on these elements, which is usually not the wanted result.

### Proposed solution
Add a tree-node slot

**Comment by ameinhardt** [comment]
Maybe the recursion is tricky with scopedSlots. An option to have a custom class for the nodes (inheriting and defaulting to VTreeviewNode) could also give full control over the nodes, too

**Comment by mooction** [comment]
Hello, you can popup a context menu by adding `@contextmenu` event in a `label` slot:

```vue
    <v-treeview :items="files" dense open-on-click transition hoverable>
      <template v-slot:prepend="{ item, open }">
        <v-icon v-if="item.children">{{ open ? 'mdi-folder-open' : 'mdi-folder' }}</v-icon>
        <v-icon v-else>{{ icon(item.basename) }}</v-icon>
      </template>
      <template v-slot:label="{ item }">
        <div @contextmenu.prevent="right($event, item)">{{ item.basename }}</div>
      </template>
    </v-treeview>
```
