### ISSUE TITLE
Feature Request - v-select: implement 'select' event handler

### ISSUE THREAD

**Issue by de5peratelighter** [vuetifyjs/vuetify#814]
Feature Request
------------
**v-select** component
Component supports only **"input"** event handler and there is no way to distinguish it from actual user **"select"**. So for example "input" event is triggered even whenever values are updated programatically without user interaction(let's say with updating data after successful API call, if needed I can provide living example of this situation).

**Similar implementations:**

selected|changed in VueMaterial
https://vuematerial.github.io/#/components/select 

iron-activate|selected-changed in Polymer https://www.webcomponents.org/element/PolymerElements/iron-selector/elements/iron-selector

Thank you !

**Comment by johnleider** [comment]
Yes, please provide an example, I'm a bit confused.

**Comment by de5peratelighter** [comment]
I've sent an example to your email John, thank you!
