### ISSUE TITLE
[Bug Report] Date picker icon don't trigger the event

### ISSUE THREAD

**Issue by JonathanVandal** [vuetifyjs/vuetify#8141]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Click on the icon

### Expected Behavior
Trigger the event to display the date picker

### Actual Behavior
It doesn't trigger the event to display the date picker

### Reproduction Link
<a href="https://codepen.io/anon/pen/qeqBJJ" target="_blank">https://codepen.io/anon/pen/qeqBJJ</a>

### Other comments
It works only if I click on the text field but It doesn't work if I click on the icon. With Vuetify 1.5 when I click on the icon, the date picker is displayed.

**Comment by jacekkarczmarczyk** [comment]
None of the icons trigger click on v-text-field https://codepen.io/anon/pen/BXRLNE?editors=1000
Not sure if bug or intended
You can easily workaround by adding a click handler to the icon https://codepen.io/anon/pen/ZgKpWp

**Comment by JonathanVandal** [comment]
Hmm I know why I said it works in 1.5, it's because I used the old way `slot="activator"` on my text field. Here is the codepen : https://codepen.io/anon/pen/xvdzyo

But with the new way (v-slot:activator) it's different and we don't have the cursor pointer anymore.

**Comment by jacekkarczmarczyk** [comment]
So this is intended behaviour, you need to use `click:append`
