### ISSUE TITLE
[Bug Report] vendor_4348f070b0b8b6aab9de is not defined

### ISSUE THREAD

**Issue by tomasfil** [vuetifyjs/vuetify#8147]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
this was working. On IE, fixed icons and css caching for IE 11 (Needed because intranet might be offline)
```
require("es6-promise").polyfill();
import "babel-polyfill";
import Vue from "vue";
import axios from "axios";
import router from "./router/index";
import store from "./store";
import { sync } from "vuex-router-sync";
import App from "components/app-root";
import { FontAwesomeIcon } from "./icons";

import "material-design-icons-iconfont/dist/material-design-icons.css"; // Ensure you are using css-loader
import Vuetify from "vuetify";
import "vuetify/dist/vuetify.min.css";
import colors from "vuetify/lib/util/colors";

// Registration of global components
Vue.component("icon", FontAwesomeIcon);

Vue.use(Vuetify, {
  iconfont: "md",
  theme: {
    options: {
      minifyTheme: function(css) {
        return process.env.NODE_ENV === "production"
          ? css.replace(/[\s|\r\n|\r|\n]/g, "")
          : css;
      }
    },
    primary: "#2e2e2e",
    secondary: "536069",
    accent: colors.red
  },
  breakpoint: {
    thresholds: {
      xl: 1900
    }
  }
});

Vue.prototype.$http = axios;

sync(store, router);

const app = new Vue({
  store,
  router,
  ...App
});

export { app, router, store };

```

Then I have updated to
 "vuetify": "^2.0.2",
    "vuetify-loader": "^1.3.0",

and changed app.js to 
```
require("es6-promise").polyfill();
import "babel-polyfill";
import Vue from "vue";
import axios from "axios";
import router from "./router/index";
import store from "./store";
import { sync } from "vuex-router-sync";
import App from "components/app-root";
import { FontAwesomeIcon } from "./icons";

import "material-design-icons-iconfont/dist/material-design-icons.css"; // Ensure you are using css-loader
import Vuetify from "vuetify";
import "vuetify/dist/vuetify.min.css";
import colors from "vuetify/lib/util/colors";

// Registration of global components
Vue.component("icon", FontAwesomeIcon);

const opts = {
  iconfont: "md",
  theme: {
    dark: false,
    themes: {
      light: {
        primary: "#2e2e2e",
        secondary: "536069",
        accent: colors.red
      },
      dark: {
        primary: "#2e2e2e",
        secondary: "536069",
        accent: colors.red
      }
    },
    breakpoint: {
      thresholds: {
        xl: 1900
      }
    }
  }
};

Vue.use(Vuetify);

Vue.prototype.$http = axios;

sync(store, router);

const app = new Vue({
  vuetify: new Vuetify(opts),
  store,
  router,
  ...App
});

export { app, router, store };
```
and installed 

npm install sass -D

### Expected Behavior
I didnt see any more steps in upgrade guide and I am not sure what am I missing 

### Actual Behavior
Page doesnt load and throws 
Uncaught ReferenceError: vendor_4348f070b0b8b6aab9de is not defined
    at eval (external_"vendor_4348f070b0b8b6aab9de":1)
    at Object.dll-reference vendor_4348f070b0b8b6aab9de (bootstrap:907)
    at __webpack_require__ (bootstrap:769)
    at fn (bootstrap:129)
    at eval (eventsource.js_from_dll-reference_vendor_4348f070b0b8b6aab9de:1)
    at Object../node_modules/event-source-polyfill/src/eventsource.js (bootstrap:907)
    at __webpack_require__ (bootstrap:769)
    at fn (bootstrap:129)
    at eval (client:1)
    at Object.0 (bootstrap:907)

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by jacekkarczmarczyk** [comment]
```
opts = {
  icons: {
    iconfont: 'md'
  },
  ...
```

Still reproduction id required, can be boiled down to minimal github repo

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
