### ISSUE TITLE
[Bug Report] VTabs internal list is not updated if tabs are dragged and droped

### ISSUE THREAD

**Issue by Steinliiippp** [vuetifyjs/vuetify#8148]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create a VTabs component with VTabs backed by a list. No if you use standard vue annotations for drag and drop (@dragstart, @dragenter, @dragleave, ...) and modiefie the unterlying list with the tabs you will see, that the list is updated and also the tab component displays the tabs in the right order. But if you try to select on of the dragged tabs it will select the index of his previous position. The problem it, that the underlying implementation is not updated. If you log this.$refs.vtabscontainer.$refs.items you will see, that the list in vtabs is not updated.

### Expected Behavior
If you drag and drop an item and modifie the underlying list, the vtabs component should recognize the change and rebuild the list order

### Actual Behavior
The List for the v-tab rendering is updated but not the list in the component itself

### Reproduction Link
<a href="https://codesandbox.io/s/vue-with-vuetify-eagles-hlqo0?fontsize=14" target="_blank">https://codesandbox.io/s/vue-with-vuetify-eagles-hlqo0?fontsize=14</a>

### Other comments
After dragging the tab you will see the output of the internal list in the console. I think you know where to look at :)

**Comment by johnleider** [comment]
I'm not really sure if there is much we can do about this. @vuetifyjs/core-team any thoughts?

Workaround for now: https://codesandbox.io/s/vue-with-vuetify-eagles-wk7fz

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
