### ISSUE TITLE
[Feature Request] Customize theme colours in SASS

### ISSUE THREAD

**Issue by johnfraney** [vuetifyjs/vuetify#8149]
### Problem to solve
Currently, it is possible to customize Vuetify by overriding [SASS variables](https://vuetifyjs.com/en/customization/sass-variables). Theme colours, however, are customized by specifying [an object of colors in `Vue.use`](https://vuetifyjs.com/en/customization/theme) which is used to [generate a custom stylesheet](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/index.ts). Because SASS/CSS variables are spread across JS/TS and SASS, it can be difficult to maintain a custom theme.

### Proposed solution
Add additional SASS variables that mirror the theme object passed into `Vue.use()`, and create a SASS file that uses those variables, similar to what the [theme utils](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/utils.ts) generates.

**Comment by jacekkarczmarczyk** [comment]
This might be possible with https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript, didn't check it though

**Comment by KaelWD** [comment]
I already have #7530

**Comment by johnleider** [comment]
There is a solution for this in v2.x using the [custom variables](https://vuetifyjs.com/en/features/theme/#custom-properties) option in the Vuetify config options.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
