### ISSUE TITLE
Scrollbars missing after closing fullscreen dialog

### ISSUE THREAD

**Issue by caleron** [vuetifyjs/vuetify#815]
### Steps to reproduce
1. open dialog documentation: https://vuetifyjs.com/components/dialogs
2. open fullscreen dialog (example 3)
3. close the dialog
4. documentation is not scrollable!

### Versions
Chrome 59 on Windows 10
Vue 2.3.3
Vuetify 0.12.7

### What is expected ?
Content is scrollable after closing the dialog

### What is actually happening ?
Content is not scrollable (i guess `showScroll` in the `overlayable` mixin is not called in the `removeOverlay` function when the dialog is fullscreen)

### Reproduction Link
https://vuetifyjs.com/components/dialogs

**Comment by johnleider** [comment]
Duplicate. Has already been fixed in dev.
