### ISSUE TITLE
[Bug Report] VTabsBar value only works with tab index

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#8150]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
The active tab is not working

### Expected Behavior
The active tab should be selected 

### Actual Behavior
Not working

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-lp4vy" target="_blank">https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-lp4vy</a>

**Comment by johnleider** [comment]
You weren't assigning a value to the tabs to correlate the specific model:

https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-0h3kp

**Comment by gadelkareem** [comment]
But the href prop turns it into a link and I don't want that.

**Comment by qinkaiyuan** [comment]
Why not use the value and use the key

**Comment by qinkaiyuan** [comment]
> You weren't assigning a value to the tabs to correlate the specific model:
> 
> https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-0h3kp

Why not use the value and use the key

**Comment by qinkaiyuan** [comment]
> You weren't assigning a value to the tabs to correlate the specific model:
> 
> https://codesandbox.io/s/vuetify-active-tab-v-tabs-component-0h3kp

`
               <v-tabs
                        background-color="transparent"
                        v-model="homeType"
                >
                    <v-tab :href="'#'+$const.homeType.all">全国</v-tab>
                    <v-tab :href="'#'+$const.homeType.likeMe">喜欢我的</v-tab>
                    <v-tab :href="'#'+$const.homeType.iLike">我喜欢的</v-tab>
                </v-tabs>
`

This is not elegant
