### ISSUE TITLE
[Bug Report] Vuetify does not work with Storybook

### ISSUE THREAD

**Issue by jacklp** [vuetifyjs/vuetify#8153]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Click on above link

### Expected Behavior
expected no errors

### Actual Behavior
got errors

### Reproduction Link
<a href="https://github.com/storybookjs/storybook/issues/7593" target="_blank">https://github.com/storybookjs/storybook/issues/7593</a>

### Other comments
I posted on the storybook repo and thought it worth posting the link here to encourage collaboration between the two projects to get integration working correctly

**Comment by johnleider** [comment]
From the linked issue it appears there is a workaround that isn't something we could explicitly fix. What are you looking to come from this?
