### ISSUE TITLE
[Bug Report] Can't select an item in combobox when pressing enter

### ISSUE THREAD

**Issue by zbyju** [vuetifyjs/vuetify#8154]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Select an option from the item list using arrow keys and press ENTER

### Expected Behavior
The item gets selected and displayed in the combobox and menu closes.

### Actual Behavior
The menu closes without changing the value/displaying the item

### Reproduction Link
<a href="https://codepen.io/TuruMan/pen/jgyRLy" target="_blank">https://codepen.io/TuruMan/pen/jgyRLy</a>

### Other comments
This exact behaviour works with the v-autocomplete just fine. It even works with the combobox when using chips

**Comment by hyvyys** [comment]
https://codepen.io/hyvyys/pen/gVRgRx Actually the value is changed but then reverted to what is typed.

**Comment by zbyju** [comment]
https://codepen.io/TuruMan/pen/aeybXO So what I meant with the comment is that selecting the item from the dropdown is broken only for v-combobox. Works fine with v-autocomplete and even with v-combobox when it's using chips.

**Comment by goeh** [comment]
I have a codepen https://codepen.io/goeh/pen/bXrBMe that's more complicated, I will verify with that once this issue is fixed.

**Comment by sh7dm** [comment]
Issue is caused by https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VCombobox/VCombobox.ts#L182

**Comment by egeersoz** [comment]
This is a major regression that broke large parts of our app. Hope it gets fixed soon!

**Comment by egeersoz** [comment]
This seems to be fixed. On the current latest version (2.1.4) I cannot reproduce it inside my own app or in the Codepen provided in the OP. @zbyju Can you confirm?

**Comment by KaelWD** [comment]
This was fixed in eab8d329c33bf9eb8c22b1038e614c105c7b05d9
