### ISSUE TITLE
[Bug Report] v-checkbox @click.native doesn't work in Firefox ESR

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#8157]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0.1 / Firefox 60.8.1 ESR
**OS:** Linux x86_64

### Steps to reproduce
Please see the example codepen. 
In Firefox 68.0.1 the checkbox toggles as expected when a user clicks on it.
In Firefox 60.8.1 ESR the checkbox does not toggle when a user clicks on it.

### Expected Behavior
The checkbox should toggle when a user clicks on it in both version of Firefox (ESR and non ESR)

### Actual Behavior
The checkbox does not toggle in the ESR version.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gVgNdZ" target="_blank">https://codepen.io/anon/pen/gVgNdZ</a>

**Comment by KaelWD** [comment]
What's the usecase for this?

 - cancelBubble is deprecated
 - you shouldn't be using the click event anyway as checkboxes can also be toggled by the keyboard and have their own internal state

**Comment by UglyHobbitFeet** [comment]
The use case is that I have a v-checkbox inside a v-expansion-panel-header.
Every time I click on it, the checkbox does not trigger and instead it only
opens/closes the expansion panel.

**Comment by KaelWD** [comment]
Does this work in esr? https://codepen.io/anon/pen/ZgeBrw?editors=1010

**Comment by UglyHobbitFeet** [comment]
I will verify tomorrow when I have an esr available. Thanks!

**Comment by UglyHobbitFeet** [comment]
It displays the same incorrect behavior. The Checkbox is permanently
checked and clicking on it expands/collapses the expansion panel

**Comment by sebiniemann** [comment]
Is it possible to emit a `change` event every time the input changes?

If i understand @UglyHobbitFeet correctly, this may solve his use case and also align Vuetify more with standard HTML and VueJS expectations.

https://developer.mozilla.org/de/docs/Web/HTML/Element/Input/checkbox
> Events: change and input

https://vuejs.org/v2/guide/forms.html
> checkboxes and radiobuttons use checked property and change event;

Looking through the docs, `checkbox` seems to be the only selection control missing a `change` event.

**Comment by thomasklein-winemaker** [comment]
Any progress on this one?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
