### ISSUE TITLE
[Bug Report] Banner Sticky not working on Safari

### ISSUE THREAD

**Issue by astrahov** [vuetifyjs/vuetify#8158]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Safari 12.1.2
**OS:** Mac OS 10.14.6

### Steps to reproduce
Scroll long page

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/alexstrakhov/pen/ZgLdqp" target="_blank">https://codepen.io/alexstrakhov/pen/ZgLdqp</a>

**Comment by johnleider** [comment]
Apparently position: sticky is only supported on Safari with **-webkit-sticky**.

**Comment by ibrahimBeladi** [comment]
The problem exists in both Chrome and Safari browsers in iPhone.

**Comment by astrahov** [comment]
Tested on the following:
- Vuetify Version: 2.0.17
- Vue Version: 2.6.10
- Browsers: Chrome 76.0.3809.100
- OS: Mac OS 10.14.6

There is no bug. Everything is working fine, as it should be.

There is a bug in the Safari browser (v12.1.2).

**Comment by astrahov** [comment]
In Safari 13 (OS X and iOS) `position: sticky` works without prefix `-webkit-`!

**Comment by astrahov** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10589
