### ISSUE TITLE
Loading disabled button is invisible on light background

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#816]
### Steps to reproduce
Create button with `loading` and `disable` attributes.
Try toggle loading. 
### Versions
v0.12.7

### What is expected ?
The button should be visible

### What is actually happening ?
But it must be partially transparent. If you look closely, during the switching of the load, it is clear that the button first becomes as expected, and then disappears.

### Reproduction Link
https://codepen.io/cawa-93/pen/awwRMP?editors=1010

**Comment by johnleider** [comment]
This was already fixed in dev.
