### ISSUE TITLE
[Bug Report] v-chip doesn't support long text

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8160]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Look at chip on page load

### Expected Behavior
The height of the chip should auto adjust to fit the content, and the close icon (if set to show) should be right aligned and centered vertically. Or it should get cut off and eclipsed with a hover over title.

### Actual Behavior
Chip height is the same and text overflows.

### Reproduction Link
<a href="https://codepen.io/anon/pen/oKBrmd?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/oKBrmd?&editable=true&editors=111</a>

**Comment by johnleider** [comment]
I'll need to evaluate if there is any specific information from spec and if not how we should proceed. This would be the case for a lot of components such as `v-btn`.

Workaround: https://codepen.io/johnjleider/pen/NQjWEm?&editable=true&editors=111

**Comment by TheInvoker** [comment]
Multi line chips may not look good. If that is the case, can it at least get a max-length prop, where I can set like say 150 chars, and if it goes over, it gets truncated with elipses? Or have it support multilines.
