### ISSUE TITLE
[Bug Report] VTabs misaligned with fixed-tabs property

### ISSUE THREAD

**Issue by dylancopeland** [vuetifyjs/vuetify#8163]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
1. Create an application with tabs inside of an app-bar.
2. Set the tabs to use `fixed-tabs`.
3. View the website on a mobile browser.

### Expected Behavior
- The tab item should fill its container.
- The tabs should have equal padding on each horizontal side.
- The first tab should be aligned with the app bar's left button.
- The tab item itself should be sized to fit the tab text.
- The slider should be aligned with the tab item.

### Actual Behavior
- The first tab has a large margin and is no longer aligned with the app bar's left button.
- The slider is misaligned with the text.
- The tab's text exceeds the bounds of the ripple effect.

### Reproduction Link
<a href="https://codepen.io/dylancopeland/pen/dxvYwe" target="_blank">https://codepen.io/dylancopeland/pen/dxvYwe</a>

**Comment by dylancopeland** [comment]
The Vuetify documentation seems to be affected by this, too:

<img src="https://user-images.githubusercontent.com/99355/62084941-7271b000-b228-11e9-8ad7-90eaabcc51c1.png" width="50%" />

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/qemBjq

**Comment by maroon1** [comment]
@johnleider i fix this problem by add "show-arrows" attribute, awesome!

**Comment by neanderthil** [comment]
I ended up overriding the css

`.v-tabs-bar.v-tabs-bar--is-mobile:not(.v-tabs-bar--show-arrows) > .v-slide-group__wrapper > .v-tabs-bar__content > .v-tab:first-of-type {
  margin-left: unset !important;
}`

**Comment by EBMike** [comment]
@johnleider The work-around doesn't seem to work when you have tabs in a drawer. I think the reason is because the drawer's width is changing as it opens and closes.

**Comment by johnleider** [comment]
This is resolved as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
