### ISSUE TITLE
[Bug Report] V-list-item color being override by light-theme color

### ISSUE THREAD

**Issue by victorsilent** [vuetifyjs/vuetify#8164]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
https://codepen.io/victorsilent/pen/PMpZqr?&editable=true&editors=101

### Expected Behavior
Text color be the same as the primary color

### Actual Behavior
Texto color being rgba(0,0,0,.87) !important

### Reproduction Link
<a href="https://codepen.io/victorsilent/pen/PMpZqr?&editable=true&editors=101" target="_blank">https://codepen.io/victorsilent/pen/PMpZqr?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
`v-list-item` only displays the defined **color** when it is active. This is by design.
