### ISSUE TITLE
[Bug Report] v-list-group value not binding correctly

### ISSUE THREAD

**Issue by curbol** [vuetifyjs/vuetify#8166]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
When the page has first loaded, the group starts open. Click the group heading and the group stays open even though the value binding has changed to false. Further toggling of the group works, but the value is the opposite of the actual group state.

The same thing happens, but opposite if the group starts closed.

Refresh the page to reset the behavior.

### Expected Behavior
If the group value is true then it should be open. If the value is false it should be closed. The group state should be bound to the value prop.

### Actual Behavior
On the first click of the group, the value changes, but the group does not visually close/open. On the next clicks the group closes/opens, but the state is opposite of what it should be.

### Reproduction Link
<a href="https://codepen.io/curbol/pen/eqvdvE?editors=1111" target="_blank">https://codepen.io/curbol/pen/eqvdvE?editors=1111</a>

### Other comments
Using v-model or not providing a value or v-model causes the group to behave normally. However I am wanting to control the group using a vuex state which is not possible with v-model that I know of. I would like to use value and @click instead of v-model

**Comment by FloryanFilip** [comment]
Same issue here, any update on this?

**Comment by Shinigami92** [comment]
I'm also affected by this bug

**Comment by KaelWD** [comment]
You should use `:value="active" @input="active = $event"`. In v3 we're changing this so if `value` is bound the component will not maintain its own internal state.

> vuex state which is not possible with v-model 

You can use a computed setter: https://vuex.vuejs.org/guide/forms.html#two-way-computed-property

**Comment by Shinigami92** [comment]
@KaelWD Thank you really much
This fixed our problem :rocket: and I was able to create a workaround with this `@input="fun($event)"`
