### ISSUE TITLE
[Bug Report] v-file-input also trigger change event on blur

### ISSUE THREAD

**Issue by dragonH** [vuetifyjs/vuetify#8167]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 7

### Steps to reproduce
Normal usage of v-file-input

### Expected Behavior
When file change, then trigger change event

### Actual Behavior
it would  trigger change event when blur

especially when i have something like upload preview

the preview image would reload

### Reproduction Link
<a href="https://codepen.io/dragonH/pen/GVWNPv?editors=1010" target="_blank">https://codepen.io/dragonH/pen/GVWNPv?editors=1010</a>

### Other comments
Add 

```
this.$refs.myUpload.blur();
```

would make it looks normally

but it still trigger the event

i'm not sure if this is a bug though

**Comment by PabloRN** [comment]
Any update about this issue. It still happening!!! Is not only annoying. It's behavior is not the expected.

**Comment by PabloRN** [comment]
I can't stop the propagation of the onChange.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
