### ISSUE TITLE
[Documentation] Have to change Theme minify example

### ISSUE THREAD

**Issue by armadillo-dev** [vuetifyjs/vuetify#8168]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. customize theme
```
theme: {
  dark: false,
  themes: {
    light: {
      primary: colors.grey.darken4,
      ...
    }
  }
}
```
2. apply minification use example code(in https://vuetifyjs.com/en/customization/theme#minification)
```
options: {
  minifyTheme: function (css) {
    return process.env.NODE_ENV === 'production'
      ? css.replace(/[\s|\r\n|\r|\n]/g, '')
      : css
  },
},
```

3. build project

### Expected Behavior
apply custom theme

### Actual Behavior
custom theme is not working

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/theme#minification" target="_blank">https://vuetifyjs.com/en/customization/theme#minification</a>

### Other comments
all spaces is removed when using minification example code(`\s`).
so generated theme code like `.v-application.primary`.

but, we need to space between `.v-application` and '.primary'.
so, we have to remove `\s|` in minifyTheme function.

**Comment by armadillo-dev** [comment]
I replaced minifyTheme option code with below.
``
minifyTheme: function (css) {
  return process.env.NODE_ENV === 'production'
    ? css.replace(/[\s|\r\n|\r|\n]/g, '').replace(/.v-application/g, '.v-application ')
    : css
}
```

**Comment by KaelWD** [comment]
Honestly this should probably just be removed. It only applies to SSR and the amount you save is probably never going to be worth the hassle.

**Comment by armadillo-dev** [comment]
I closed this issue. and changed issue title to more special for SSR.
