### ISSUE TITLE
[Bug Report] v-simple-table: styling missing in production builds

### ISSUE THREAD

**Issue by curio77** [vuetifyjs/vuetify#8170]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
1. Clone the repro repo. `npm i`.
2. `npm run-script serve`. Observe that the `v-simple-table` has a hover effect.
3. `NODE_ENV=production npm run-script serve`. Observe that the `v-simple-table` lacks the hover effect.

### Expected Behavior
The `v-simple-table` should have a hover effect independent of the mode the application is being run at.

### Actual Behavior
The `v-simple-table` lacks its hover effect in production mode.

### Reproduction Link
<a href="https://github.com/curio77/vuetify-simple-table-hover.git" target="_blank">https://github.com/curio77/vuetify-simple-table-hover.git</a>

### Other comments
The `v-simple-table` component has a hover effect analogous to `v-data-table`, with which it apparently shares CSS. However, in production mode the effect is missing. Including a dummy `<v-data-table v-show="false"></v-data-table>` in the same component the `v-simple-table` is used in works around the issue, presumably by preventing CSS from being purged by webpack that otherwise is.

BTW, existing Codepen templates for Vuetify 2 also exhibit a lack of any styling for `v-simple-table`, maybe that's related.

**Comment by jacekkarczmarczyk** [comment]
fixed in https://github.com/vuetifyjs/vuetify/pull/8165
