### ISSUE TITLE
[Bug Report] Remove active-class attribute from VBtn

### ISSUE THREAD

**Issue by BotellaA** [vuetifyjs/vuetify#8172]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Using the active-class props on a VBtn.

### Expected Behavior
Using the active-class props on a VBtn does not override the v-btn_active default class. In my example, the icon should be darker without the circle shadow.

### Actual Behavior
Additional circle shadow.

### Reproduction Link
<a href="https://codepen.io/BotellaA/pen/KOWQKy" target="_blank">https://codepen.io/BotellaA/pen/KOWQKy</a>

**Comment by johnleider** [comment]
I'm not really sure what you are looking to get resolved, could you please elaborate, maybe show a gif or something?

**Comment by BotellaA** [comment]
From the 1.5.x documentation of `active-class` prop of VBtn:
```
Class bound when component is active. warning Depending upon the component, 
this could causeside effects. If you need to add a custom class on top of a default, 
just do active-class="default-class your-class"
```

New doc is:
```
Configure the active CSS class applied when the link is active. 
You can find more information about the active-class prop on the vue-router documentation.
```

My goal is to be able to remove the `default-class` attribute which is `v-btn--active`. This could be done in 1.5.x using `<v-btn active-class=""/>` but does not work in 2.0.x. Is this a bug or a new design?

**Comment by KaelWD** [comment]
2bb3ec068154f53c83d8be5fded2a436adb078ca

**Comment by BotellaA** [comment]
I assume removing the `v-btn--active` is not possible anymore. Any workaround to achieve this behavior in 2.x?

**Comment by johnleider** [comment]
The only workaround would be to create a class that targets the active-class and then change whatever properties you want. They are inherit now and there are no plans to change that.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ricardovanlaarhoven** [comment]
For now i'm adding a class to buttons that doesn't need the opacity `no-active`
And have this css in my main.scss file which i import in the variables (don't know how else):
`.v-btn--active.no-active::before { display: none }`

But i would like to see this issue reopen. Perhaps this could be build in into vuetify

**Comment by KaelWD** [comment]
`v-list-item` has an `inactive` prop, but it also no longer affects the active-class since this change. I think it could be added to routable and made to work properly in all other implementing components too.

**Comment by maxflex** [comment]
**+1**
Can't remove the `v-btn--active` class, though I don't need it. Intuitive solution `active-class=""`  doesn't work. The active class never goes away

**Comment by andrewharvey** [comment]
The workaround I'm using is:
```js
<v-btn active-class="no-active"></v-btn>
```
```css
.v-btn--active.no-active::before {                                                                             
  opacity: 0 !important;
}
```

This replaces the opacity setting which v-btn--active is setting where the no-active class is set, and provides a migration path for the change in behaviour of `v-btn` `active-class` from vuetify 1.x to 2.x.

**Comment by mikesaintsg** [comment]
Quick Solution: Use an "href" attribute instead of "to"

Example: 
I had a logo wrapped in a VBtn that sends the user back home on click, but of course I already have a Home button that will already show active for that route. No need for the logo to be highlighted and not much of a need for the full functionality of the "to" attribute.

**Comment by EmmyMay** [comment]
In my case, I set the active-class attribute in a v-btn to a class of my choosing and then did the below

active-class="no-active"

 .no-active::before{
      background-color: transparent !important;
    }

**Comment by dmcknight26** [comment]
> The workaround I'm using is:
> 
> ```js
> <v-btn active-class="no-active"></v-btn>
> ```
> 
> ```css
> .v-btn--active.no-active::before {                                                                             
>   opacity: 0 !important;
> }
> ```
> 
> This replaces the opacity setting which v-btn--active is setting where the no-active class is set, and provides a migration path for the change in behaviour of `v-btn` `active-class` from vuetify 1.x to 2.x.

FWIW in 2.x I had to use this to keep hovering and tabbing highlighting in place, while preventing the highlighting on matching URLs...

```
.v-btn--active.no-active:not(:focus):not(:hover)::before
{                                                                             
  opacity: 0 !important;
}
```

**Comment by mdryden** [comment]
> The workaround I'm using is:
> 
> ```js
> <v-btn active-class="no-active"></v-btn>
> ```
> 
> ```css
> .v-btn--active.no-active::before {                                                                             
>   opacity: 0 !important;
> }
> ```
> 
> This replaces the opacity setting which v-btn--active is setting where the no-active class is set, and provides a migration path for the change in behaviour of `v-btn` `active-class` from vuetify 1.x to 2.x.


Thanks for this, it was helpful.  For anyone else who would like to disable this globally, I used this non-scoped style in my App.vue:

```
.v-btn--active::before {
  opacity: 0 !important;
}
```

**Comment by ricardovanlaarhoven** [comment]
i would suggest adding it to a global css/scss/sass file so you won't pollute your app.vue with all those global styles

**Comment by gorka-lab** [comment]
This is not a bug and have nothing to do with vuetifyjs. It belongs to vue-router, it's just not documented.

Work with router.js file; add an alias and replace what's in path into the alias and set the path to the route name (or whatever you want that URL to be named)

Before

```javascript
const routes = [ 
    { 
        path: "/",
        name: "home", 
        component: () => 
            import(/* webpackChunkName: "home" */ "../views/Home.vue"), 
    }
]
```
After:
```javascript
const routes = [ 
    { 
        path: "/home", 
        alias: "/", 
        name: "home", 
        component: () => 
            import(/* webpackChunkName: "home" */ "../views/Home.vue"), 
    }
]
```

**Happy Coding!!**

**Comment by the94air** [comment]
A simple way to fix this is to add the attribute `:exact="true"` to the button 😂
