### ISSUE TITLE
[Feature Request] v-bottom-navigation request inverted-scroll

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#8173]
### Problem to solve
not problem
v-app-bar has inverted-scroll and hide-on-scroll both

v-bottom-navigation has both feel so good

### Proposed solution
just request inverted-scroll

**Comment by johnleider** [comment]
Removing the updates I previously left after a discussion with the team.

For v3, v-bottom-nav will essentially be v-app-bar with styling changes. However, this is not something we would do for v2. You can follow this issue for future updates: https://github.com/vuetifyjs/vuetify/issues/12709

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
