### ISSUE TITLE
[Bug Report] Text-truncate stoped working

### ISSUE THREAD

**Issue by struers-mfr** [vuetifyjs/vuetify#8174]
### Environment
**Vuetify Version:** 2.0.0-beta.9
**Last working version:** 2.0.0-beta.8
**Vue Version:** 2.6.10
**Browsers:** Chromium 74.0.3729.169
**OS:** Ubuntu undefined

### Steps to reproduce
no steps needed.
You should see it after load

### Expected Behavior
truncate too long text

### Actual Behavior
text overflow parent element

### Reproduction Link
<a href="https://codepen.io/anon/pen/PMpeNv?&editable=true&editors=101#anon-login" target="_blank">https://codepen.io/anon/pen/PMpeNv?&editable=true&editors=101#anon-login</a>

**Comment by jacekkarczmarczyk** [comment]
already fixed https://codepen.io/anon/pen/rXyvJY
