### ISSUE TITLE
[Bug Report] End date is earlier than start date when accessing days of the calendar reference

### ISSUE THREAD

**Issue by jessielaf** [vuetifyjs/vuetify#8175]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
- Add v-calendar
- Access the days on the reference of the calendar

### Expected Behavior
Get the days of the calendar

### Actual Behavior
Throws error: "Exception: Error: End date is earlier than start date"

### Reproduction Link
<a href="https://codepen.io/anon/pen/wVJjOW" target="_blank">https://codepen.io/anon/pen/wVJjOW</a>

**Comment by ClickerMonkey** [comment]
This occurs when no value or v-model is specified, a fix for this will be in a PR shortly.

**Comment by jessielaf** [comment]
Same error occurs when one is :value or v-model is provided: https://codepen.io/anon/pen/wVJjOW
