### ISSUE TITLE
[Bug Report]  v-text-field prefix length does not change dynamically.

### ISSUE THREAD

**Issue by AlekseenkoAnton** [vuetifyjs/vuetify#8176]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. Create a text field with a dynamic prefix. 
2. Increase the prefix length

### Expected Behavior
The prefix length should change dynamically depending on the prefix value. V-text-field's label should not overlap the prefix.

### Actual Behavior
V-text-field's label overlaps the prefix if the prefix length is increased.

### Reproduction Link
<a href="https://codepen.io/alexeenko_ao/pen/MNpGPE" target="_blank">https://codepen.io/alexeenko_ao/pen/MNpGPE</a>

**Comment by jacekkarczmarczyk** [comment]
You need to rerender text field manually, for example https://codepen.io/anon/pen/MNpXaV

**Comment by pcornelissen** [comment]
The codepen doesn't seem to rerender anything?
