### ISSUE TITLE
[Bug Report] Custom colors for progress component

### ISSUE THREAD

**Issue by mvdriel** [vuetifyjs/vuetify#8179]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu 18.04

### Steps to reproduce
When a custom background color is set, progress is not visible anymore.

### Expected Behavior
Display progress

### Actual Behavior
Progress not visible; only background color is visible

### Reproduction Link
<a href="https://codepen.io/anon/pen/EqWdaO" target="_blank">https://codepen.io/anon/pen/EqWdaO</a>

### Other comments
The issue is also visible in the documentation:
https://vuetifyjs.com/en/components/progress-linear#custom-colors

**Comment by mvdriel** [comment]
Probably relates to #8114

**Comment by johnleider** [comment]
Going to mark this as duplicate because fixing #8114 would solve this.
