### ISSUE TITLE
[Bug Report] SASS cannot compile due to missing semicolons 

### ISSUE THREAD

**Issue by StummeJ** [vuetifyjs/vuetify#8183]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Other
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a new vue project via the cli, add vuetify, try to write a component test.

### Expected Behavior
The sass files to compile when using Mocha + Chai tests

### Actual Behavior
$ yarn test:unit 

WEBPACK  Failed to compile with 9 error(s)

Error in ./node_modules/vuetify/src/components/VAppBar/VAppBar.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VToolbar/VToolbar.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VImg/VImg.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/directives/ripple/VRipple.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VProgressCircular/VProgressCircular.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VResponsive/VResponsive.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VBtn/VBtn.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 2:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VIcon/VIcon.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 2:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VSheet/VSheet.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 2:9                                                                                      root stylesheet
        in http:/localhost/Users/{REDACTED}/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

### Other comments
Cannot provide a link to the repo, sorry

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by StummeJ** [comment]
Please don't just close it that fast.  Is there an example of using Vue CLI and Vuetify?  all of the examples look like custom webpack files and not using Vue CLI.

@johnleider

**Comment by StummeJ** [comment]
Literally just did a `vue new` with stylus and typescript, then `vue add vuetify` with the defaults and I get the same issue...

**Comment by JamesMcMahon** [comment]
Attempting to upgrade to Vuetify 2 and hitting the exact same issue.

@StummeJ Can you upload your small example to a repo and maybe we can get this reopened or opened as new issue?

**Comment by JamesMcMahon** [comment]
Seeing the exact same issue on a newly created app, see https://github.com/JamesMcMahon/vuetify-create-issues

**Comment by JamesMcMahon** [comment]
New bug at https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/101

(This was automatically linked before but broken when they moved it)

**Comment by chris4dd** [comment]
Same problem here, upgrade from v1.5

**Comment by Niush** [comment]
Any Progress here? Issue still persists with Mochapack + Vuetify Tests.
Failed to compile with bunch of sass and scss errors.
 ```
error  in ./node_modules/vuetify/src/components/VApp/VApp.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1│ @import '../../styles/styles.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```
and more.
