### ISSUE TITLE
not working link inside of the current dev docs

### ISSUE THREAD

**Issue by ram-you** [vuetifyjs/vuetify#819]
https://dev.vuetifyjs.com/components/grid-lists 
broken link

**Comment by dohomi** [comment]
@ram-you where did you find this link?

**Comment by dohomi** [comment]
update: just found it..

**Comment by johnleider** [comment]
I haven't created it yet.

**Comment by johnleider** [comment]
Thank you for the report, but closing this as it is not a bug, I just haven't had a chance to add those docs to dev yet :)
