### ISSUE TITLE
[Feature Request] Data table: missing props.index in item slot

### ISSUE THREAD

**Issue by vschimpf** [vuetifyjs/vuetify#8199]
### Problem to solve
I need that index to do several customizations that depend on the current item index (which depends on the current sort).
I use it for programatically select the first item on the table, customize the row hover behavior, customize the row selection, specify tabindex, and more. All these inside my own generic table component that I use for serveral tables (like a wrapper).
It is a requirement for me to be able to migrate to version 2.0.x

### Proposed solution
Inside the slot "item" the props should also contain the "index" property, like the previous version has.

**Comment by redijedi** [comment]
This is a blocker for my current project. How does one integrate this change? I do not see the `src/maps/v-data-table.js` referenced in the PR.

**Comment by vschimpf** [comment]
> 
> 
> This is a blocker for my current project. How does one integrate this change? I do not see the `src/maps/v-data-table.js` referenced in the PR.

I think the changes are not merged to master yet, let's see if they are included in the next release..
