### ISSUE TITLE
v-dialog fade background missing in IE and Edge

### ISSUE THREAD

**Issue by milleraa** [vuetifyjs/vuetify#820]
### Steps to reproduce
https://codepen.io/milleraa/pen/bRredW
### Versions
IE 11.1198.14393.0
Edge 38.14.393.1066.0
vuetify v0.12.7 

### What is expected ?
Dark background blocks underlying page.

### What is actually happening ?
Background is missing. I can click on undelying page elements.

**Comment by johnleider** [comment]
Can you take a screenshot to show me what you see? I'm testing and everything looks correct to me.

**Comment by milleraa** [comment]
![edge-missing-fade-bg](https://user-images.githubusercontent.com/19791414/27483754-dbce0b90-5850-11e7-9b35-07595b3620e3.PNG)
Here it is. On my win10 without creators update

**Comment by KelvinYYY** [comment]
Hi, I am still experiencing the same issue with chrome 68.0.3440.75. I am using the exact same code from vuetify examples. It shows good on vuetify website but the background will not be faded when I run my code.
dependencies:
```
"dependencies": {
    "axios": "^0.17.1",
    "bootstrap": "^4.0.0-beta.2",
    "bootstrap-vue": "^2.0.0-rc.11",
    "highlight.js": "^9.12.0",
    "i": "^0.3.6",
    "npm": "^5.5.1",
    "sha1": "^1.1.1",
    "vue": "^2.5.17",
    "vue-cookie": "^1.1.4",
    "vue-router": "^3.0.1",
    "vuetify": "^1.3.3",
    "vuex": "^3.0.1"
  }, 
```
Thanks if anyone could help!
![screenshot from 2018-10-29 18-09-01](https://user-images.githubusercontent.com/18172104/47689138-d128d100-dba5-11e8-8d5e-3aadf7dd13d7.png)

**Comment by KaelWD** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
