### ISSUE TITLE
[Feature Request] Sliders don't have options for icon size

### ISSUE THREAD

**Issue by delaneyj** [vuetifyjs/vuetify#8202]
### Problem to solve
Elsewhere in the app using `x-small` but not settable in the slider.

### Proposed solution
Add `icon-size` prop.  Already have `tick-size` and `thumb-size`.

**Comment by diazemiliano** [comment]
Hi @delaneyj, you mean the append or prepend icons? You can always use the slots to customize what you want. See here https://codepen.io/diazemiliano/pen/BXRvJX?&editable=true&editors=111
On the case of the label you can use `<template v-slot:thumb-label="props">`.
Tell me if that helps.

**Comment by delaneyj** [comment]
@diazemiliano  yeah that should work great, didn't make the connections reading the docs.  Thanks!

**Comment by diazemiliano** [comment]
@delaneyj glad to help. 👍
