### ISSUE TITLE
[Bug Report] A-La-Carte Install (vuetify-loader) duplicate css issue

### ISSUE THREAD

**Issue by Shardik04** [vuetifyjs/vuetify#8209]
### Environment
**Vuetify Version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.4

### Steps to reproduce
https://codesandbox.io/s/codesandbox-nuxt-1z4qt

### Expected Behavior
It should load only single CSS on /about page on code sandbox demo link

### Actual Behavior
It should load only single CSS on /about page on code sandbox demo link

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-1z4qt" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-1z4qt</a>

**Comment by KaelWD** [comment]
https://v15.vuetifyjs.com/en/framework/a-la-carte#required-styles

**Comment by akash58** [comment]
I'm also facing this issue in vuetify version 1.5.14 and i tried your solution but then i get the issue

Module build failed (from ./node_modules/css-loader/dist/cjs.js):                                                     friendly-errors 16:08:18
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'exportOnlyLocals'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (/home/parity3/Workspace/dd_pwa/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:49:11)

Can you explain me how to solve ?
@KaelWD

**Comment by nekosaur** [comment]
Your error is unrelated to vuetify. See https://github.com/webpack-contrib/css-loader/issues/976

**Comment by Shardik04** [comment]
@KaelWD 
I have gone through https://v15.vuetifyjs.com/en/framework/a-la-carte#required-styles 
and https://github.com/vuetifyjs/nuxt/tree/master/template this demo example also for the a-la-carte module.

Below, code sandbox is my demo code 
https://codesandbox.io/s/codesandbox-nuxt-1z4qt

But I doubt that it has only included required component CSS and JS. Because when I see on chrome console performance coverage[attached below snap shot].
<img width="1279" alt="Screenshot 2019-08-01 at 12 53 09 PM" src="https://user-images.githubusercontent.com/11913104/62273606-8bae7280-b45b-11e9-8e38-4c2c05dc5569.png">
