### ISSUE TITLE
[Documentation] VDataTable footer props need more clear example

### ISSUE THREAD

**Issue by hendiche** [vuetifyjs/vuetify#8211]
### Given Example : 
[Footer props](https://vuetifyjs.com/en/components/data-tables#footer-props)
```vue
<div id="app">
  <v-app id="inspire">
    <v-data-table
      :headers="headers"
      :items="desserts"
      :items-per-page="5"
      item-key="name"
      class="elevation-1"
      :footer-props="{
        showFirstLastPage: true,
        firstIcon: 'mdi-arrow-collapse-left',
        lastIcon: 'mdi-arrow-collapse-right',
        prevIcon: 'mdi-minus',
        nextIcon: 'mdi-plus'
      }"
    ></v-data-table>
  </v-app>
</div>
```

### comments
I'm so sorry if this is stupid request, and i'm sorry also maybe my experience is not enough, but i just want to solve the problem that i had, and share it also, so other people won't have the same problem that i had, and waste time to search about it.

In the API props table written `items-per-page-options`
but if going to use under `<v-data-table>` as `footer-props` it's become `itemsPerPageOptions`.

### Proposed Example:
```vue
<div id="app">
  <v-app id="inspire">
    <v-data-table
      :headers="headers"
      :items="desserts"
      :items-per-page="5"
      item-key="name"
      class="elevation-1"
      :footer-props="{
        itemsPerPageOptions: [5, 10], // -> Add this example
        showFirstLastPage: true,
        firstIcon: 'mdi-arrow-collapse-left',
        lastIcon: 'mdi-arrow-collapse-right',
        prevIcon: 'mdi-minus',
        nextIcon: 'mdi-plus'
      }"
    ></v-data-table>
  </v-app>
</div>
```

**Comment by yanqd0** [comment]
Agree.

I tried to implement a `<v-data-footer>` on the top, but failed about operations, according to this #2985.

**Comment by annymosse** [comment]
@MajesticPotatoe i believe this request is helpful and eliminate some confusing

**Comment by L-HommeSage** [comment]
Hello, how can I go to the next page pressing the right key and comeback with the left key ?

**Comment by cincarnato** [comment]
+1

**Comment by djpeach** [comment]
Would also like to see this in the docs. I was not aware how to pass nested props in Vue. Either this, or a site-wide "Nested Props" section would help. I'm sure this applies to more than just the footer props in the data table.

**Comment by sakuriki** [comment]
+1 run into this problem today

**Comment by logesh-manoharan** [comment]
`firstIcon: 'mdi-arrow-collapse-left',
 lastIcon: 'mdi-arrow-collapse-right',`
 
 How can I add **functions** to these two icons i.e. how can I add `@click` property?

**Comment by mtwolak** [comment]
Hello from Google. Also experienced this problem, would be great to see this in docs.

**Comment by Richardtugwell** [comment]
+1 - had to search to figure this out
