### ISSUE TITLE
[Bug Report] Bad behaviour when not using md-icons in v-treeview

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#8212]
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
use all required things for proper work of vuetify (i.e vuetify vue and babel-polyfill cdns, roboto fonts). *instead of md-icons, use font-awesome*.

create a `v-treeview` with some nested data such as:

File1
Folder1
* nestedFile
* nestedFolder

EmptyFolder

use `#prepend` slot and put there icon for folder and for file.

### Expected Behavior
Expected alignment of file and folders to be aligned together.

### Actual Behavior
When an item has children it gets negative alignment due to lack of md-icons

### Reproduction Link
<a href="https://codepen.io/Tzahile/pen/GVmxbB" target="_blank">https://codepen.io/Tzahile/pen/GVmxbB</a>

**Comment by jacekkarczmarczyk** [comment]
More real life reproduction: https://codepen.io/anon/pen/bXRdpe?editors=1000

**Comment by rajasekhar02** [comment]
Is this issue fixed? if not can I work on it?

**Comment by commonspace** [comment]
Another related issue is that when you use another icon set like font-awesome, the expand-icon is static and does not switch when expanded.

**Comment by jifka** [comment]
> Another related issue is that when you use another icon set like font-awesome, the expand-icon is static and does not switch when expanded.

You can hack this with the following CSS to rotate the icon when expanded, but it would be nice to have an expanded-icon prop to set:

```
.v-icon.v-treeview-node__toggle--open {
    transform:rotate(90deg);
}
```
