### ISSUE TITLE
[Bug Report] VTooltip issue when activating only on click

### ISSUE THREAD

**Issue by deraw** [vuetifyjs/vuetify#8213]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Click on the button

### Expected Behavior
The tooltip is shown and disappears after the delay specified with the `close-delay` property

### Actual Behavior
The tooltip appears then disappears immediately. When you click a second time just after the first one, the tooltip is shown but it only disappear when you loose focus on the button (and after the delay).

### Reproduction Link
<a href="https://codepen.io/dylan-broussard/pen/xvdJMR" target="_blank">https://codepen.io/dylan-broussard/pen/xvdJMR</a>

### Other comments
I think that's related to the "active/focus" state of the button!

**Comment by KaelWD** [comment]
Workaround: https://codepen.io/kaelwd/pen/JjdbPRB

**Comment by MatthewAry** [comment]
I'm seeing an issue also with open-on-click. When you apply an open-delay in conjunction with open-on-click (while not explicitly turning open-on-hover off) it becomes functionally no different than not having open-on-click set at all.

https://codepen.io/MatthewAry/pen/gOMYqpm
