### ISSUE TITLE
[Bug Report] Tooltip is not positioned correctly

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#8215]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
It can be seen from the first moment, it has a value of "true" by default

### Expected Behavior
That it really appears where it is indicated, that it does not appear as in this photo (https://drive.google.com/file/d/1W1JGq_QXWn_QDH7M670JHEdYH9KpdVPY/view?usp=sharing)

### Actual Behavior
At the moment it is untidy and it does not show as it should, in the example it is not noticed so much but in my photo it is seen that it is too unguarded

### Reproduction Link
<a href="https://codepen.io/frbuceta/pen/xvdyqm" target="_blank">https://codepen.io/frbuceta/pen/xvdyqm</a>

**Comment by frbuceta** [comment]
[UPDATE] When the value of "value" equal to "true" is set, the tooltips are not positioned correctly

**Comment by MajesticPotatoe** [comment]
Your reproduction is a 404. Please updated it when you get a chance. Thanks.

**Comment by frbuceta** [comment]
I can't find the reproduction, if I can do it again, I open the issue again
