### ISSUE TITLE
[Bug Report] v-list-subheader not cropped when reducing screen

### ISSUE THREAD

**Issue by kulkoff** [vuetifyjs/vuetify#8216]
### Environment
**Vuetify Version:** 2.0.2
**Last working version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
remove max-width in v-card. Reduce screen size.
Can open in a mobile phone with a width of less than 500, the star will not appear

### Expected Behavior
same as 1.15.14

### Actual Behavior
Extends width on v-list beyond parent

### Reproduction Link
<a href="https://codepen.io/kulkoff/pen/eqWbeg?&editable=true&editors=101" target="_blank">https://codepen.io/kulkoff/pen/eqWbeg?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
I can only reproduce this in the actual codepen. Checked MAC Safari/Chrome, iOS, W10 Chrome, all works good. The irregularity can also be solved in the codepen by forcing the `v-card` to max width.

https://codepen.io/johnjleider/pen/bXRRMK?&editable=true&editors=101

**Comment by kulkoff** [comment]
Sorry. You added width=100% for v-card, and your result ok. I migrate from
1.15.14 to 2.0.3, and was surprised that the code behaves differently
Thank you!

чт, 1 авг. 2019 г. в 07:07, John Leider <notifications@github.com>:
