### ISSUE TITLE
Picker and Data table locale

### ISSUE THREAD

**Issue by gpassero** [vuetifyjs/vuetify#822]
I'm using Picker and Data table components and they are awesome. However, it's very important to me that they show information in my own language (Portuguese). It's currently necessary to overwrite some attributes like *days* and *months* for Picker, and *no-results-text* and *no-data-text* for Data table.
I think future developer would be very pleased to not need to overwrite those props with this data. 
I think maybe the value of *lang* attribute of *html* root relement could be used as the default value for i18n of this parameters.

**Comment by nekosaur** [comment]
Please show a code sample of your proposed enhancement, in contrast to the existing solution

**Comment by gpassero** [comment]
Vee-Validate has a similar feature. Checkout the locale folder in their repo: https://github.com/logaretm/vee-validate.

I'm currently loading Vee-Validate passing an argument with a dict of translated labels:

**main.js**
```javascript
const veevalidate_locale = require('./locale/vee-validate-pt-br');
Vue.use(VeeValidate, { locale: 'pt-br', dictionary: { 'pt-br': veevalidate_locale.default }, errorBagName: 'vErrors' })
```
The Validator.prototype._formatErrorMessage method searches the dict for the localized text:

**vee-validator code**
```javascript
// LOCALE default value is 'en'
var msg = this.dictionary.getFieldMessage(LOCALE, field.name, rule.name);
```

Instead of passing a dictionary to the component in main.js, we could pass only the locale, and when requiring the dictionary it could be automatically added to the library locale dicitionaries. This code is in the vee-validate-pt-br.js, but needed a modification to work for me:

**vee-validate-pt-br.js**
```javascript
const messages = {
  after: (field, [target]) => `O campo ${field} deve estar depois do campo ${target}.`,
  alpha_dash: (field) => `O campo ${field} deve conter letras, números e traços.`,
  ...
}
const locale = {
  name: 'pt_BR',
  messages
}

import VeeValidate from 'vee-validate' // added this line
if (typeof VeeValidate !== 'undefined' && VeeValidate && typeof VeeValidate.Validator) {
  VeeValidate.Validator.addLocale(locale);
}

export default locale;
```

I hope this ideia helps to improve Vuetify in the future.

**Comment by johnleider** [comment]
Enhanced with #905
