### ISSUE TITLE
[Feature Request] Make v-autocomplete be more consistent with its width

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8221]
### Problem to solve
v-autocomplete works because it has a text input field hidden within it. Yet, once a selection is made, the input field combined with the selection essentially makes the width of v-autocomplete double in size. In my situation, this looks visually like some sort of bug, but I know that it's just a consequence of having a selection and a text input field together. Either way, it would be nice to make the width of the input field be more consistent.

![auto-complete-width](https://user-images.githubusercontent.com/157217/62213418-190c9c80-b360-11e9-9837-28db96f005f6.gif)

### Proposed solution
If the v-autocomplete is only being used to select ONE value at a time, any currently selected value can be hidden when characters are inputted into the text field. If they clear the input field without making a selection the original selection can return.

If the v-autocomplete is set up to allow multiple selections, I think that either the current behavior of having the text input field at the end of the present selections will work in some situations, but perhaps an additional property can be added which would move the text input field into the selection menu, with it being sticky at the top of the selection menu. This is just an idea. But my overall goal here is to find ways to make the width of the v-autocomplete component more consistent.

**Comment by johnleider** [comment]
Would it be possible to provide a small reproduction of your markup?

**Comment by MatthewAry** [comment]
By markup do you mean that you want me to create a codepen that shows this behavior with the width?

**Comment by MatthewAry** [comment]
#6275 is related it seems.
