### ISSUE TITLE
[Bug Report] v-content padding is inverted while toggle Navigation drawer mini-variant with defined width

### ISSUE THREAD

**Issue by Arsync** [vuetifyjs/vuetify#8223]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Create App with clipped Navigation drawer and App bar (clipped-left).
2. Bind drawer 'mini-variant' to button click event for toggle.
3. All works correctly.
4. Set drawer width to 320px and mini-variant-width to 120px.

### Expected Behavior
v-content left padding is 120px when mini-variant is true and 320px when not.

### Actual Behavior
v-content left padding is 320px when mini-variant is true and 120px when not.

### Reproduction Link
<a href="https://codepen.io/anon/pen/PMmgNX" target="_blank">https://codepen.io/anon/pen/PMmgNX</a>

**Comment by KaelWD** [comment]
It works if you use a number instead: `width="320"`

**Comment by johnleider** [comment]
This happens due to a change made in order to allow the drawer to take non px value numbers such as `40vw`. However, even when using `300px`, the system checks to see if it is NaN and if so, simply returns the current width of the drawer.

The issue starts when you swap between mini and full width, the element is animating when the check for its width is called and therefor returns an incorrect value.

What I'll probably end up doing with this is informing users of the caveat as I'm not sure it is worth dedicating time to come up with a specific solution.

**Comment by HeshamMeneisi** [comment]
>It works if you use a number instead: `width="320"`

Only works for the first time then breaks (expand, collapse, expand, collapse << fails). 
This is on v2.2.11.

I only got it to works with this workaround inside my `Drawer` component:

```ts
onTransitionEnd () {
    this.isMini = this.$refs.drawer.isMiniVariant;
}
@Watch("isMini")
onIsMiniChanged() {
  this.width = this.miniWidth;
  this.$nextTick(() => {
    this.width = this.fullWidth;
  });
}
```
`onTransitionEnd` is triggered by `@transitionend`

**Comment by AlexDaniel** [comment]
This is still an issue and the workaround mentioned above doesn't seem to work.

**Comment by AlexDaniel** [comment]
OK, I think I managed to get it working, anyone should feel free to try the same.

Basically, I stumbled upon this idea, which may sound nuts but it actually does the trick: https://stackoverflow.com/a/63340144/2698019

1. Add `:key="drawerRefreshKey" @transitionend="transitionEnd"` when creating the navigation drawer
2. When you toggle your miniVariant (in your own handler), set a flag somewhere that the navigation drawer needs to be refreshed. Let's say that the flag is `refreshNeeded`.
3. Then: `transitionEnd() { if (this.refreshNeeded) this.drawerRefreshKey += 1 }`
4. This makes Vue recreate the navigation drawer from scratch, with new non-broken internal state. This happens after the transition, so hopefully the user will not even notice. 
5. Yay?

The only bug I see now (completely unrelated to the workaround above, I promise) is that v-content gets resized if you move the mouse really fast on the navigation drawer edge. Basically, it toggles the navigation drawer really fast, and somehow a v-content resize attempt is made, even though the drawer still has its mini flag on, so why would that be the case I have no idea.

🤷

**Comment by hector** [comment]
Thanks @AlexDaniel. It does the trick for me. Until they official fix it I will use your trick to be able to update Vuetify....

**Comment by johnleider** [comment]
This is handled differently in v3 and is no longer an issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Turbine1991** [comment]
The workarounds don't work for me. I've managed to come up with a workaround.

In Nav:
```
  <v-navigation-drawer
...
    :expand-on-hover="isMini"
    :mini-variant="isMini"
    ref="nav"
    width="265px"
    :style="{ width: isMiniWidth ? '65px' : '265px' }"
...
    </v-navigation-drawer}

------
    computed: {
        isMiniWidth() {
            return this.isMini && !this.$refs.nav.isMouseover;
        },
    }
```

Fixing it in v3 does nothing for us v2 users. This ought to be fixed.

**Comment by duverre** [comment]
Following worked for me:

```
// Navigation.vue
<template>
  <v-navigation-drawer app clipped expand-on-hover
                       mini-variant-width="72"
                       :mini-variant.sync="drawerIsMiniVariant"
                       :key="drawerIsMiniVariant">
  </v-navigation-drawer>
</template>

<script lang="ts">
import {Component, Vue} from "vue-property-decorator";

@Component
export default class Navigation extends Vue {
  
  private drawerIsMiniVariant: boolean = true;
  
}
</script>
```
Works on Vue 2.3 and up.

**Comment by alexanderbetz** [comment]
@duverre Thank you a lot! 💪😎
