### ISSUE TITLE
[Feature Request] Button Focus Color (Tab vs Mouseover) (v2.0.3)

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#8229]
### Problem to solve
Currently (v2.0.3) when navigating to a button via the Tab key, the background highlighting is darker than when you hover on the button with your mouse.  This will provide UI consistency for buttons.

### Proposed solution
Darken the background hover color when mousing over a button such that it matches the focused color of the button.

**Comment by ibrahimBeladi** [comment]
This is as per the [Material Design](https://material.io/design/interaction/states.html).

**Comment by KaelWD** [comment]
Yep
![image](https://user-images.githubusercontent.com/16421948/62257141-6adc2200-b447-11e9-9886-1dbc97f36884.png)
