### ISSUE TITLE
v-select: navigation with arrow keys does not work after filling autocomplete

### ISSUE THREAD

**Issue by vizo** [vuetifyjs/vuetify#823]
### Versions

dev

### What is expected ?

To navigate v-select with up/down arrow keys.

### What is actually happening ?

If you open select list, you can navigate with up/down arrow keys on keyboard, but after writing something to autocomplete, you can't navigate with up/down keys anymore. But i guess it's just css class problem, because if you hit enter after pressing up/down, you see that you were actually moving, but it's "invisible".
Sometimes it throws error in console:
```
Error in callback for watcher "listIndex": "TypeError: Cannot read property 'classList' of undefined"
found in
---> <Menu>
<Select>

```

### Reproduction Link:

[https://dev.vuetifyjs.com/components/selects](https://dev.vuetifyjs.com/components/selects), example 5 Scoped slots

**Comment by vizo** [comment]
Hey, i still get error:
```
Error in callback for watcher "listIndex": "TypeError: Cannot read property 'classList' of undefined"

found in

---> <Menu>
       <Select>
         <Create> at /home/vivizio/workspace/worldofbreeders.com/app/assets/javascripts/components/pages/pages/Create.vue
           <Application> at /home/vivizio/workspace/worldofbreeders.com/app/assets/javascripts/components/Application.vue
             <Root>```

**Comment by johnleider** [comment]
Please make sure you have the most recent dev. I just tested this again and is working properly.

**Comment by vizo** [comment]
I feel like idiot again :) Before i wrote to you i did it 10 times - deleted all, clone again, release again, deleted old node_modules/vuetify. But looks like there was "same" release in cache huh :)

Now error is gone, but i still notice that sometimes when you write autocomplete fast and then you pres down, you need to press more than one time that the "selection" shows up ... 

For example if list shrinks from 10 items to 1 by filter, you need sometimes to press "down" more times. I guess index of current "selection" should reset to 0 every time you write each character?

**Comment by vizo** [comment]
I am trying to figure pattern when it happens, but looks so random .. :S

**Comment by vizo** [comment]
Ok i guess i figure it out... 

I have around 10 items, 4 of them includes "ho" inside ...
It works until you select first 3 by doing same thing: writing "ho" and pressing "down arrow" and "enter.
But when all first 3 are selected, if i write "ho" again to select 4th on list, I need to press "up arrow" more times to get "selection". And sometimes even pressing "right arrow" after text in autocomplete i get "selecion" in list.

**Comment by johnleider** [comment]
Can you give exact reproduction steps?

**Comment by vizo** [comment]
1. Make sure you have v-select multiple with 10 items and at least 4 items in list, which includes same string e.g. "en".
2. Repeat selecting them by entering autocomplete filter "en", pressing "down arrow" and "enter". I see that each time selection index jumps on first unselected item on list.

First 3 items can be selected with no problems, but when i want to select 4th item (first 3 must be already selected), selection is not in visible area of drop down. I have to press "arrow up" more times to see it.

So i guess, there must be some bug in "jump selection to first unselected item" mechanism.

I hope i was clear enough, English is not my native :)
