### ISSUE TITLE
[Bug Report] Resetting selected nodes on items change

### ISSUE THREAD

**Issue by ofca** [vuetifyjs/vuetify#8231]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Steps to reproduce are here https://codepen.io/anon/pen/VoWmbO

### Expected Behavior
When "items" are changed selected nodes should not be cleared.

### Actual Behavior
When "items" are changed selected nodes are cleared.

### Reproduction Link
<a href="https://codepen.io/anon/pen/VoWmbO" target="_blank">https://codepen.io/anon/pen/VoWmbO</a>

### Other comments
It's because after :items changes, this.selectedCache is cleared and this.emitSelected() is called but for some reason with empty this.selectedCache rather old :value.
https://github.com/vuetifyjs/vuetify/blob/055c2465dd11740931e6993dbfa4b176cce0a6a1/packages/vuetify/src/components/VTreeview/VTreeview.ts#L134

**Comment by nekosaur** [comment]
Looking at the codepen you linked, I am not sure what you expect to happen. Setting the selection before having any items at all in the treeview will not work. This however, will keep selection when items change https://codepen.io/anon/pen/voZbJq

**Comment by ofca** [comment]
Ok, your codepen is some kind of workaround. I just thought that clearing selection when items are set are bad idea, don't see why selection need to be cleared.

I have form (and function which loads values to it) and a custom treeview component which loads items to it. Now I have to wait with loading values to form until my treeview component loads items because otherwise nothing will be selected in treeview.

Nevertheless thank you for presented workaround.
