### ISSUE TITLE
[Documentation] Data Table - Need documentation on how to use `expanded-item` slot when also using custom `body` slot

### ISSUE THREAD

**Issue by randanunn** [vuetifyjs/vuetify#8233]
### Problem to solve
Ability to use custom Body slot template in a data table, as well as the custom expanded-item slot.  I assume this is possible, but the documentation does not have an example or mention how it can be done. Here is a code pen with 2 tables. The one on top won't expand because it is using a custom body. The one on bottom is not using a custom body and it does expand as expected.

https://codepen.io/lucille2/pen/jgwBBN/

I would think that EITHER the expanded-item slot would work out of the box with a custom body row OR there would be a snippet of code you could add to your custom row for the expanded section.

### Proposed solution
Provide documentation on how it is done. (If it can be.)

**Comment by nekosaur** [comment]
It is not possible to use `expanded-item` slot when using `body` slot. `body` slot takes over the internal rendering completely, and so you will have to implement things like expanded slot, or selection checkboxes yourself.

This should probably be emphasised somewhere in the documentation.
