### ISSUE TITLE
[Bug Report] Enabling customProperties breaks the theme in IE11

### ISSUE THREAD

**Issue by literallyliterature** [vuetifyjs/vuetify#8235]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Codepen seems to have its own issues on IE11. So, to reproduce with a new project created with Vue CLI:

1. Create a new project with the Vue CLI with default preset.
2. (Change directory and) `vue add vuetify` with default preset.
3. As given in [the docs for IE 11 support](https://vuetifyjs.com/en/getting-started/quick-start#ie-11-safari-9-support), create `vue.config.js` and add

```js
// vue.config.js

module.exports = {
  transpileDependencies: ['vuetify']
}
```

4. Enable customProperties in the vuetify initialisation

```js
// src/plugins/vuetify.js

import Vue from 'vue';
import Vuetify from 'vuetify/lib';

Vue.use(Vuetify);

export default new Vuetify({
  theme: {
    options: {
      customProperties: true,
    },
  },
  icons: {
    iconfont: 'mdi',
  },
});
```

5. Add `color="primary"` to Latest release button in `App.vue` (or somewhere else where adding the color would have an effect)
6. On running (or building) the project, the button is not given the correct background color.

### Expected Behavior
The colors are shown correctly even on IE11.

### Actual Behavior
Different colors shown on IE11 vs Chrome and Firefox

### Reproduction Link
<a href="https://codepen.io/literallyliterature/pen/dxRvZm" target="_blank">https://codepen.io/literallyliterature/pen/dxRvZm</a>

**Comment by jacekkarczmarczyk** [comment]
Custom properties don't work in IE11, that should be stated in the docs
Probably I could generate 
```css
.primary { background: #123456; };
.primary { background: var(--v-primary-base);
``` 
instead of just  
```css
.primary { background: var(--v-primary-base);
```

but you will have to same in your styles if you want to use theme colors, so I'm not sure what's the point of using custom properties anyway if you need IE11 support. Am I missing something?

**Comment by literallyliterature** [comment]
No, I don't think you're missing anything. It would not make sense to enable `customProperties` if IE11 support is needed (if Vuetify explicitly would not support `customProperties` for IE11).

It would certainly be useful to have it stated in the docs. I had assumed that it was a bug because I didn't find it in the docs.

However, could there be a workaround for enabling `customProperties` while supporting IE11? Possibly some additional webpack configuration?

**Comment by jacekkarczmarczyk** [comment]
Maybe polyfill (https://github.com/jhildenbiddle/css-vars-ponyfill), but i don't know if it works well with Vuetify

**Comment by kumaravnish** [comment]
> Maybe polyfill (https://github.com/jhildenbiddle/css-vars-ponyfill), but i don't know if it works well with Vuetify

This worked for me.

**Comment by opadilla** [comment]
> > Maybe polyfill (https://github.com/jhildenbiddle/css-vars-ponyfill), but i don't know if it works well with Vuetify
> 
> This worked for me.

That one didn't work for me for some reason.   This one did though: https://github.com/nuxodin/ie11CustomProperties
