### ISSUE TITLE
[Bug Report] Tab adds margin when used as router-link 

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#8237]
### Environment
**Vuetify Version:** 2.0.3
**Last working version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
open the link and switch to mobile view. You'll see a gap between tab two and tab three

### Expected Behavior
All tabs should be aligned to their neighbours without margins

### Actual Behavior
When using tabs as router-link with :to, the first tab gets a margin of 52px added (no matter if they are the first tab or somewhere in the middle of the row). Subsequent router-link tabs don't have this margin.

### Reproduction Link
<a href="https://codepen.io/thomaskuhlmann/pen/qejyeq" target="_blank">https://codepen.io/thomaskuhlmann/pen/qejyeq</a>

**Comment by jacekkarczmarczyk** [comment]
Didn't dig deep into this issue but possibly there's already PR for this https://github.com/vuetifyjs/vuetify/pull/8123, will take a look later (or maybe you can check if that PR solves the issue and report back)

**Comment by johnleider** [comment]
fixed in #8123
