### ISSUE TITLE
[Bug Report] No margin between the prepend-icon and v-text-field / v-select when RTL is enabled

### ISSUE THREAD

**Issue by desyatnik** [vuetifyjs/vuetify#8241]
### Environment
**Vuetify Version:** 2.0.3
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Use a v-text-field /v-select (checked with these controls, but might be not isolated to them) with prepend-icon and RTL enabled.

### Expected Behavior
A margin between the icon and the field.

### Actual Behavior
There's a margin from the right side of the icon, i.e. RTL is not taken into account.

### Reproduction Link
<a href="https://codepen.io/desya/pen/eqRxJE" target="_blank">https://codepen.io/desya/pen/eqRxJE</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/7861

**Comment by rajasekhar02** [comment]
Can I work this? 
I hope this is place I need to fix
> https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VInput/VInput.sass#L62
