### ISSUE TITLE
[Bug Report] Treeview: It's possible to select a disabled item by selecting its parent

### ISSUE THREAD

**Issue by mclak** [vuetifyjs/vuetify#8244]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3853.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Set a child item as disabled in a selectable treeview
Click on its parent node

### Expected Behavior
The disabled item state should not change

### Actual Behavior
The disabled item state is changing

### Reproduction Link
<a href="https://codepen.io/anon/pen/NQgVwR" target="_blank">https://codepen.io/anon/pen/NQgVwR</a>

**Comment by SirPoot-** [comment]
+1 to add some traction, please.

**Comment by nekosaur** [comment]
Please don't +1 in comments. Use the thumbs up on the original post. That way we can prioritize issues by sorting them.

**Comment by SirPoot-** [comment]
Thank you @nekosaur for letting me know the correct process. Appreciate it!

**Comment by mikestu** [comment]
I wanted to add that the reverse is also true - you can cause a disabled child item that is checked, to become unchecked by unchecking its parent.  If an item is disabled, but checked, I think it shouldn't be allowed to become unchecked by using the parent nodes.

**Comment by Noreu** [comment]
Is there some news about it ? Thx
