### ISSUE TITLE
[Feature Request] Change the way how opacity is applied to bottom navigation buttons

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#8245]
### Problem to solve
Right now an opacity is applied to every bottom nav button that isn't active. As a result, badges have the opacity applied as well and it's not possible to prevent the inheritance since it's not an inherited property. But usually badges are meant to highlight something - applying an opacity should be optional in this case.

https://codepen.io/thomaskuhlmann/pen/mNwZLm

### Proposed solution
it'd be nice if instead of applying 'opacity: 0.7' we could change the colour of the inactive buttons - e.g. rgba(0, 0, 0, 0.7), that way you can overwrite it on a child element.

**Comment by klukiyan** [comment]
@ThomasKuhlmann hi, did you find a solution? I have this issue in @nuxt/vuetify
