### ISSUE TITLE
[Bug Report] V- select autocomplete and V-Autocomplete does not work in IPAD Safari browser

### ISSUE THREAD

**Issue by asif-ali04** [vuetifyjs/vuetify#8249]
### Environment
**Vuetify Version:** 1.5.14
**Vue Version:** 2.5.20
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
HI we are using v-autocomplete component to achive below functionality
https://codepen.io/anon/pen/YmQmoJ?&editable=true&editors=101

 

versions
   "vuetify": "^1.5.14" 
  "vue": "^2.5.2"

 

it works completely fine with both IE and Chrome browser also in safari in mac browser.

 

The issue is with ipad safari browser. when  list values in dropdown is loaded after search then select any value from dropdown, selection is not happenig it just get closed.

the above code in codepen link also works fine with ipad safari browser.   but it does not with our code based.

### Expected Behavior
Should be able to select the values from v-autocomplete

### Actual Behavior
unable to select the values from v-autocomplete, after selecting value from for list ,select does not happen instead list just goes off.

### Reproduction Link
<a href="https://codepen.io/anon/pen/YmQmoJ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/YmQmoJ?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Please correct me if I'm mistaken, but this appears to work just fine:

![image](https://user-images.githubusercontent.com/9064066/62316522-41c68c00-b45d-11e9-89db-d0167c6de767.png)

**Comment by asif-ali04** [comment]
Yes it works fine, if we implement above logic in our code base it just does not work in ipad safari

**Comment by Meenakshise** [comment]
even this link  works in ipad for us. But our code base which is using the vuetify version "vuetify": "^1.5.14" and "vue": "^2.5.2" not working in ipad. We are clueless of why it is not working. We are able the select an item from the list. But the selected item is not displaying in the v-select input control. Please guide us what is missing. It is working in all the windows browsers like IE, chrome, etc.. but in iPad device. Even from windows browser if we run our code via developer tools device toggle bar it is working but in the actual ipad device it is not working. 
https://codepen.io/anon/pen/YmQmoJ?&editable=true&editors=101

**Comment by Meenakshise** [comment]
Also this control was working fine in our ipad earlier. It got broken recently in ipad browser. We are trying to figure out since when it is broken.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
