### ISSUE TITLE
[Bug Report] No spacing between v-avatar with img and text in chip

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8250]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Look at chip on page load.

### Expected Behavior
Spacing between v-avatar and the text.

### Actual Behavior
No spacing.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KOvwKY?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/KOvwKY?&editable=true&editors=111</a>

**Comment by johnleider** [comment]
You have to use the **left** prop. This is by design.

https://codepen.io/johnjleider/pen/WVEwXG?&editable=true&editors=111
