### ISSUE TITLE
[Bug Report] [v-data-table] The bottom border of the group row  is not well drawn

### ISSUE THREAD

**Issue by cafedo** [vuetifyjs/vuetify#8251]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Run the code pen attached

### Expected Behavior
The bottom border of each group row in v-data-table should be well drawn

### Actual Behavior
The border of each group row is cut

### Reproduction Link
<a href="https://codepen.io/volyansky/pen/EqvaWg" target="_blank">https://codepen.io/volyansky/pen/EqvaWg</a>

**Comment by nekosaur** [comment]
The origin of this behavior is a chrome bug, see https://bugs.chromium.org/p/chromium/issues/detail?id=356132
