### ISSUE TITLE
[Bug Report] VDataTable footer-props.item-per-page-text not working

### ISSUE THREAD

**Issue by PetrPy** [vuetifyjs/vuetify#8254]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
See CodePen.

### Expected Behavior
Table should show the contents of items-per-page-text.

### Actual Behavior
Default text is shown instead.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pMrjax" target="_blank">https://codepen.io/anon/pen/pMrjax</a>

### Other comments
Guys, this Vuetify Issue Creator sucks. Please:
* Make the CodePen template link open in a new window, so we don't lose everything we have written.
* Do not require us to fill all stuff, be glad that we report at least something. If you require CodePen, do not require Steps to reproduce.
* Do not require reproduction link, it is not always possible to create one.

Cheers!

**Comment by jacekkarczmarczyk** [comment]
In what situation you are forced to use kebab-case? We're not converting it in other places, like `menu-props` for example, i don't see a reason why we should do this here
