### ISSUE TITLE
[Bug Report] New treeview items set indeterminate state based on parent

### ISSUE THREAD

**Issue by skycow** [vuetifyjs/vuetify#8256]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
1. Expand the applications node
2. Select an item in the list
3. Click the Add Item button

### Expected Behavior
The new item is added and is not selected or indeterminate.

### Actual Behavior
The new item is added in an indeterminate state.

### Reproduction Link
<a href="https://codepen.io/anon/pen/KOvVgj?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/KOvVgj?&editable=true&editors=101</a>

### Other comments
New items' indeterminate state should be based on the children not the parent's indeterminate state.

**Comment by johnleider** [comment]
This line: https://github.com/vuetifyjs/vuetify/blob/5a70900855475b8fe3ea68a41fb76afdd2bb511a/packages/vuetify/src/components/VTreeview/VTreeview.ts#L217

Not sure if this would ever be desired behavior. Thoughts @nekosaur ?
