### ISSUE TITLE
[Bug Report] Breadcrumb not clickable with items to prop does not make

### ISSUE THREAD

**Issue by nwhessel** [vuetifyjs/vuetify#8257]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 8.1

### Steps to reproduce
Create breadcrumbs with to prop:
```
        [{
          text: 'Dashboard',
          disabled: false,
          to: 'breadcrumbs_dashboard',
        },
        {
          text: 'Link 1',
          disabled: false,
          to: 'breadcrumbs_link_1',
        },
        {
          text: 'Link 2',
          disabled: true,
          to: 'breadcrumbs_link_2',
        }]
```

### Expected Behavior
First two breadcrumbs are clickable, 3rd is not

### Actual Behavior
No breadcrumbs are clickable

### Reproduction Link
<a href="https://codepen.io/anon/pen/MNveRR?editors=1111" target="_blank">https://codepen.io/anon/pen/MNveRR?editors=1111</a>

**Comment by jacekkarczmarczyk** [comment]
You're using `to` but not using vue-router

**Comment by nwhessel** [comment]
I am using vue router, it just isn't set up in the codepen

**Comment by Morrowless** [comment]
same issue

**Comment by nekosaur** [comment]
Then please create a new issue that reproduces the problem and includes vue-router.
