### ISSUE TITLE
[Bug Report] V-toolbar fixed prop is missing

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#8259]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
v-toolbar is not fixed

### Expected Behavior
toolbar should float

### Actual Behavior
not floating

### Reproduction Link
<a href="https://codepen.io/gadelkareem/pen/gVxrEP" target="_blank">https://codepen.io/gadelkareem/pen/gVxrEP</a>

**Comment by MajesticPotatoe** [comment]
This is intended.
`fixed` prop has been moved to `v-app-bar`
