### ISSUE TITLE
[Feature Request] Possibility to combine vuetify with existing app (or new app) with other frameworks such as Bootstrap, Bulma, etc

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#8261]
### Problem to solve
Is there any plan to make vuetify friendly with other aforementioned frameworks? or is it?

### Proposed solution
```html
// for example we are using bootstrap
<div id="app">
    <div class="row">
        <div class="col-md-4">

            // in this line contains vuetify component for instance
            <v-app>
                <v-date-picker v-model="selectedDate" />
            </v-app>

        </div>
    </div>
</div>
```

**Comment by johnleider** [comment]
Vuetify should work with other libraries, just put the `v-app` component at the root. We have scoped the styles of the framework and to that extent, I believe we have no further plans to modify our implementation to explicitly work with other frameworks.

In the future we do plan on removing the explicit need to have a root `v-app` and that's the only QOL change for this particular request (it's already be tracked) that will be implemented at this time.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by hjelperne** [comment]
> Vuetify should work with other libraries

This is not entirely true.
I am for instance using bootstrap-vue. I then added vuetify (^2.2.11).
Once I wrapped my App.vue template code in the v-app code several components and existing styles are affected.
For instance the b-navbar component of bootstrap-vue is altered by the following CSS:
 .v-application ul, .v-application ol { padding-left: 24px;} - ref screenshot:
![vuetify-css-bug](https://user-images.githubusercontent.com/342842/78079104-bdd9f080-73ab-11ea-98e8-474b81986e02.png)

Some guys over there also mentioned that vuetify uses CSS styles that are in conflict (same as used in) bootstrap core - which again causes issues.

It would be good to know that this gets resolved once and for all - if possible

**Comment by ftuyama** [comment]
Try using this:
```
@forward 'vuetify/settings' with (
  $reset: false,
);
```

The `v-` prefix helps to reduce the conflicts, but Vuetify introduces generic modifiers like:

https://github.com/vuetifyjs/vuetify/blob/0ac6f09a305d70350e18102b298f20ed7419fe90/packages/vuetify/src/styles/generic/_reset.scss

```
button, [type=button], [type=reset], [type=submit], [role=button] {
    cursor: pointer;
    color: inherit;
}
```

and

```
* {
    padding: 0;
    margin: 0;
}
```

Which breaks the existing page style

**Comment by ftuyama** [comment]
Another cause of conflicts is the CSS reset: https://github.com/vuetifyjs/vuetify/issues/8530

https://vuetifyjs.com/en/styles/css-reset/#bootstrapping

**Comment by johnleider** [comment]
![image](https://github.com/vuetifyjs/vuetify/assets/9064066/6dc50fb1-3bde-4584-b4c5-7e9f5c44aa7e)
