### ISSUE TITLE
[Bug Report] VToolbar: Collapsed state width is fixed

### ISSUE THREAD

**Issue by Ar4093** [vuetifyjs/vuetify#8262]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. Create a `v-toolbar` with the `collapse` prop.
2. Add some buttons
3. Observe that the width of the v-toolbar does not change.

### Expected Behavior
Either the v-toolbar should adjust its width to accomodate all elements that aren't hidden by collapsing, or there should be a note in the documentation that the width is not dynamic.

### Actual Behavior
The collapsed toolbar has a fixed width of 112px, which only really fits if there's exactly 2 icon buttons.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pMrVrM" target="_blank">https://codepen.io/anon/pen/pMrVrM</a>

### Other comments
This is also visible in the playground at https://vuetifyjs.com/en/components/toolbars#playground

Relevant code: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VToolbar/VToolbar.sass#L113

**Comment by johnleider** [comment]
The collapsed style is not an official spec and instead pulled from the Google MWC implementation. There is has a defined **112px** width when collapsed. This particular feature can be implemented (and I believe should stay) in user land.

Example: https://codepen.io/johnjleider/pen/zgPNrW

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
