### ISSUE TITLE
[Bug Report] DataTable: Invalid prop: type check failed for prop "search"

### ISSUE THREAD

**Issue by PhilippHomann** [vuetifyjs/vuetify#8264]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Use an object as search attribute for DataTable.
See Codepen for example

### Expected Behavior
Working

### Actual Behavior
Not working. Warning in console:
[Vue warn]: Invalid prop: type check failed for prop "search". Expected String with value "[object Object]", got Object 

### Reproduction Link
<a href="https://codepen.io/anon/pen/xvLaqE?editors=1111" target="_blank">https://codepen.io/anon/pen/xvLaqE?editors=1111</a>

### Other comments
My intention is to use an object as search attribute, so I can really use column specific filtering.

**Comment by PhilippHomann** [comment]
@nekosaur @sh7dm I think you've implemented column based filtering and this typecheck.

**Comment by nekosaur** [comment]
That is not how the functionality has been designed. See https://codepen.io/anon/pen/MNvqNy?editors=1111

**Comment by PhilippHomann** [comment]
Okay thanks for that hint.
Maybe you can put this example to the documentation?

**Comment by nekosaur** [comment]
There is an example of column filtering here https://vuetifyjs.com/en/components/data-tables#custom-filtering
