### ISSUE TITLE
[Bug Report] VDataTable initial pagination

### ISSUE THREAD

**Issue by deraw** [vuetifyjs/vuetify#8266]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Set initial pagination with `options` object (with `page: 2`)

### Expected Behavior
The current page is the second (6-10 of 10)

### Actual Behavior
The current page is the first (1-5 of 10)

### Reproduction Link
<a href="https://codepen.io/dylan-broussard/pen/ZgJdNP?&editable=true&editors=101" target="_blank">https://codepen.io/dylan-broussard/pen/ZgJdNP?&editable=true&editors=101</a>

### Other comments
[Working v1.5 demo](https://codepen.io/dylan-broussard/pen/zgdgOO?&editable=true&editors=101)
This is very useful feature because we save the pagination in localStorage to keep it when leaving the application, so the user retrieves it next time

**Comment by TheInvoker** [comment]
which vuetify version will this get merged in?

**Comment by nekosaur** [comment]
PR is still open, it has not been merged

**Comment by deraw** [comment]
Hi @nekosaur!

I've got the impression that the issue is only fixed partially :confused: 

When the items are declared on the `data` field (*default example*) the initial pagination works as intended ([example here](https://codepen.io/dylan-broussard/pen/WNerqwY?editors=1011))

But when it comes from the server (*Paginate and sort server-side* example), the initial pagination is ignored (for the `page` prop) ([example here](https://codepen.io/dylan-broussard/pen/PoYZvvO?editors=1011))

**Comment by nekosaur** [comment]
Correct. The server side issue is tracked here https://github.com/vuetifyjs/vuetify/issues/8359

**Comment by tbanys** [comment]
Reproduction Link of this Bug Report is misleading then if server side issue is tracked #8359
