### ISSUE TITLE
[Documentation] Can't access to Vuetify Docs: Error 524

### ISSUE THREAD

**Issue by runyasak** [vuetifyjs/vuetify#8267]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Type url and enter to access website

### Expected Behavior
The site should appear

### Actual Behavior
I've got error 524 - a timeout occurred

![image](https://user-images.githubusercontent.com/6861191/62386333-b4c92300-b581-11e9-9dd5-f2e2bceb9e39.png)

### Reproduction Link
<a href="https://vuetifyjs.com/" target="_blank">https://vuetifyjs.com/</a>

### Other comments
Have any alternative way to access or optional docs for offline?

**Comment by MajesticPotatoe** [comment]
Is being redeployed.

**Comment by runyasak** [comment]
Oh, that's great.

Thank you 😁

**Comment by Shinigami92** [comment]
![Bildschirmfoto 2019-10-29 um 14 15 10](https://user-images.githubusercontent.com/7195563/67770414-a55d5700-fa56-11e9-91b3-49bf98ca1491.png)
