### ISSUE TITLE
[Bug Report] Label and prefix overlap when binding prefix to data

### ISSUE THREAD

**Issue by d-jurgens** [vuetifyjs/vuetify#8268]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a text field that has a prefix bound to a value from a autocomplete field

### Expected Behavior
When a value is submitted by the autocomplete field, the label in the text field moves to make space for the prefix

### Actual Behavior
The label and the prefix overlap

### Reproduction Link
<a href="https://codepen.io/d-jurgens/pen/mNBere" target="_blank">https://codepen.io/d-jurgens/pen/mNBere</a>

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/QeOGXN
