### ISSUE TITLE
Feature request: Native css variables

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#827]
As far as I understand, at the given moment, all the stylys settings ([colors](https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/settings/_colors.styl), [theme](https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/settings/_theme.styl), etc.) are compiled into css as values.

This causes some inconvenience. For example, to change the primaty color of a theme, I have to integrate the sources into my project, redefine the `$theme` variable and compile the result.

How much easier it would be if the colors of the theme were set using the **native CSS variable**. In this case, redefining the color palette becomes much easier and more flexible. And the original code of the vuetifyjs is reduced.
```css
:root {
  --primaryColor: #f06d06;
}
```

I understand that the use of native variables may not give all the possibilities as a stylus, but I am convinced that this is something to which one should strive.

I think you should take the parameters of the theme into native variables. And in the future expand other [settings](https://github.com/vuetifyjs/vuetify/tree/master/src/stylus/settings).

**Comment by johnleider** [comment]
As far as I'm aware, stylus variables are not compiled into the src.

**Comment by johnleider** [comment]
Due to IE11 and Safari 9/10 not supporting this, we will have to pass.

**Comment by cawa-93** [comment]
I believe that the support of this technology is satisfactory
https://caniuse.com/#feat=css-variables
It seems that last version of the safari, already support CSS variables. IE11 there is no such support. However, this browser is deprecated and removed by Microsoft for the benefit of the Edge.

Here is an approximate example of how light and dark themes could be implemented with the use of CSS variables:
http://simurai.com/blog/2018/04/01/contextual-styling

**Comment by nekosaur** [comment]
CSS variables is a no go as long as we support IE11. We can revisit this in the future if/when we decide to drop IE11.

**Comment by cawa-93** [comment]
@nekosaur Of course you are right. Well, I will hope for progress in development in this direction.

**Comment by jacekkarczmarczyk** [comment]
I don't think we need to wait for IE to die or even make a separate build. We can just generate css variables together with theme classes, they will be ignored in IE (or if they will cause any error then there could be a theme var defining whether css vars should be generated or not).

There could be however a separate build requiring vue-next (vue version that doesn't support IE, 2.6-next or 3.0 or whatever it's called), but that's not really related to this issue

**Comment by Christilut** [comment]
Well I'm hitting this roadblock as well and CSS variables would perfectly solve this problem. 
I think it should be used and IE11 can use a fallback to stylus.

**Comment by Christilut** [comment]
I'm using [this stackoverflow answer](https://stackoverflow.com/questions/48280990/using-custom-theming-in-vuetify-and-pass-color-variables-to-components/50882165#50882165) as workaround for now
