### ISSUE TITLE
[Bug Report] Indeterminate state of checkbox is not correct

### ISSUE THREAD

**Issue by c1337r** [vuetifyjs/vuetify#8270]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 2.0.0-beta.8
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Select all items
2. Unselect any item

### Expected Behavior
Headline checkbox should display indeterminate state.

### Actual Behavior
Headline checkbox shows false state

### Reproduction Link
<a href="https://codepen.io/s3p/pen/jgGPjm" target="_blank">https://codepen.io/s3p/pen/jgGPjm</a>

**Comment by jacekkarczmarczyk** [comment]
Simplified repro https://codepen.io/anon/pen/YmrJza?editors=1000

**Comment by sh7dm** [comment]
ty @jacekkarczmarczyk. Oversimplified version xD: https://codepen.io/sh7dm/pen/pMWXWd?editors=1010

**Comment by cLupus** [comment]
I have observed that `inputIndeterminate` will not update in certain circumstances, even when it is supposed to.

**Comment by c1337r** [comment]
Is there anything I can do to help solving this issue?
Actually, it is a real show stopper...

**Comment by jacekkarczmarczyk** [comment]
You can create a PR :) Also there's a simple workaround using `key`: https://codepen.io/jkarczm/pen/LYPZwZL

**Comment by c1337r** [comment]
Thanks a lot for providing the workaround!

**Comment by isysmacedo** [comment]
This problem still happens in version 1.5.24 @johnleider
