### ISSUE TITLE
[Bug Report] Alert transition is not working

### ISSUE THREAD

**Issue by nfraz007** [vuetifyjs/vuetify#8272]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
just click on the toggle button, you will notice that fade transition is not working

### Expected Behavior
It should give fade effect

### Actual Behavior
fade effect

### Reproduction Link
<a href="https://codepen.io/anon/pen/LwzNZd?editors=1010" target="_blank">https://codepen.io/anon/pen/LwzNZd?editors=1010</a>

### Other comments
Please fix this.

**Comment by johnleider** [comment]
This is a css ordering issue where in the minified css, the utility transitions are being placed above the components. In the case of v-sheet, it applies a box shadow transition. @vuetifyjs/core-team any thoughts on just making the transition on v-sheet a blanket `transition: $primary-transition`?

Workaround for now: https://codepen.io/johnjleider/pen/voWyVQ?editors=1010

**Comment by nfraz007** [comment]
@johnleider : thanks for your response, I tried temprary solution, adding `class="transition-swing"` but still this is not working.

**Comment by poganytamastsys** [comment]
> Workaround for now: https://codepen.io/johnjleider/pen/voWyVQ?editors=1010
This workaround works for me.

**Comment by KrilMun** [comment]
Is this still being tracked? I'm a little concerned, because I just wanted to follow this thread until it gets closed for good, so I can remove the workaround as soon as it gets fixed. It's sad the documentation's not updated to this issue, though..

**Comment by nfraz007** [comment]
Actually it is still not working, i updated the vuetify to latest version
but no success.
i tried all the alternative which is given in this email. but no success.
if you want i can show you my code. i dont know it is working in other pr
not, but it is not working in mine.

**Comment by pynner** [comment]
Just encountered this bug today, can confirm still happening. I'm seeing it with a VSkeletonLoader, working pre-minified @johnleider

**Comment by sh7dm** [comment]
@pynner please open a new issue!

**Comment by MajesticPotatoe** [comment]
@pynner no need to open an issue, there already is one that is open  #9033
