### ISSUE TITLE
[Bug Report] Carousel erratic behavior when clicking twice in the same delimiter

### ISSUE THREAD

**Issue by TwireonEnix** [vuetifyjs/vuetify#8273]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Just click twice in any delimiter and it goes back to the first slide always. I don't know if this is intended behavior

### Expected Behavior
Stay in the same slide even when the same delimiter is clicked

### Actual Behavior
A delimiter cycles between the current and the first slides on subsequent clicks. This happens even in all vuetify docs examples.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZgXWgv" target="_blank">https://codepen.io/anon/pen/ZgXWgv</a>

**Comment by ibrahimBeladi** [comment]
By watching the value I noticed that: when I click on the next delimiter (say 1) it goes there and when clicked again, it goes to the first (say 0). But the value changes like this: 0 -> 1 -> **undefined** -> 0.
