### ISSUE TITLE
[Bug Report] Missing translation for v-data-table: "Sort by"

### ISSUE THREAD

**Issue by mlebrasseur** [vuetifyjs/vuetify#8274]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Only on small screens, when the v-data-table turns into v-window, the filter text is always "Sort by".

### Expected Behavior
i18n locale file should have a key for that missing translation.
"dataTable": { "sortBy": "Sort by" }

### Actual Behavior
There's no key value that vuetify can use for this translation.

### Reproduction Link
<a href="https://jsfiddle.com" target="_blank">https://jsfiddle.com</a>

**Comment by jacekkarczmarczyk** [comment]
duplicate of https://github.com/vuetifyjs/vuetify/issues/8083
