### ISSUE TITLE
[Bug Report] Bad contrast with dark mode and focus colors

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8276]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
In dark mode, and a dark purple primary color, colors of text on certain components don't look good via contract issues. In the code pen link, if you click on the text field to focus it, the placeholder text transitions up and turns purple. But now you can barely read the purple text. 

On the table pagination items per row dropdown, the one that is selected is not readable either.

### Expected Behavior
A prop to help further contrast in scenarios like this, so the theme can still be purple but you can still read it.

### Actual Behavior
Unreadable.

### Reproduction Link
<a href="https://codepen.io/anon/pen/rXGWrG?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/rXGWrG?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
What do you want us to do about this? It's up to you to choose legible colours.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
