### ISSUE TITLE
[Bug Report] v-text-field with icons is still expecting the old material-icons instead of mdi

### ISSUE THREAD

**Issue by cdterry87** [vuetifyjs/vuetify#8277]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.13

### Steps to reproduce
Refer to the reproduction link.

### Expected Behavior
v-text-field icon properties should use the configured icon font

### Actual Behavior
v-text-field icon properties are using material-icons instead of the (default) configured mdi icons

### Reproduction Link
<a href="https://codepen.io/anon/pen/pMWRaV" target="_blank">https://codepen.io/anon/pen/pMWRaV</a>

**Comment by jacekkarczmarczyk** [comment]
MDI icons need `mdi-` prefix https://codepen.io/anon/pen/zgENMX
