### ISSUE TITLE
[Bug Report] Spacing is not correct with RTL for list items

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8278]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Windows 10

### Steps to reproduce
In non-RTL mode, the list item looks alright. Spacing betwen the 3 things in the list item is good. But when RTL is on, the spacing between checkmark and the word is too close together.

### Expected Behavior
Spacing should mimic non RTL mode.

### Actual Behavior
No spacing between in RTL mode.

### Reproduction Link
<a href="https://codepen.io/anon/pen/JgrEgo?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/JgrEgo?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Fixed in #7861

**Comment by TheInvoker** [comment]
was this change already released to public?

**Comment by jacekkarczmarczyk** [comment]
yes

**Comment by TheInvoker** [comment]
But I just tried this
https://codepen.io/anon/pen/JgrEgo?&editable=true&editors=101
changing the links to point to v 2.0.5, and it looks exactly the same?
The checkmark is too close to the text.

**Comment by jacekkarczmarczyk** [comment]
It was changed in 2.0.4 so you should compare with 2.0.3. Also 
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
