### ISSUE TITLE
Firefox dropdown first animation

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#828]
### Steps to reproduce
Click the "Dropdown" button in the docs

### Versions
Firefox 54, latest vuetify

### What is expected ?
Animation the same as chrome

### What is actually happening ?
menu flies in from the left, outside the screen

### Reproduction Link
https://vuetifyjs.com/components/menus

**Comment by johnleider** [comment]
I can confirm this has been fixed in dev when we switched timeouts to requestAnimationFrame.

**Comment by JacksMyth** [comment]
Firefox is working now but safari still has this issue for me. Even on the demo pages for both menu and selects
