### ISSUE TITLE
[Bug Report] Data Table capitalization issues

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#8287]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 7

### Steps to reproduce
Use a prop that is capitalized.
A v-slotted template can no longer "sync" with the column and is ignored.

### Expected Behavior
The properties of an object can be capitalized

### Actual Behavior
Any capitalized property will be passed to the table, but can not be modified by a template

### Reproduction Link
<a href="https://codepen.io/anon/pen/xvXzyj" target="_blank">https://codepen.io/anon/pen/xvXzyj</a>

**Comment by Teellcory** [comment]
Through more testing, I found that the issue is specifically with the header value being capitalized. The prop can be capitalized as long as the header is not. The example given will be fully functional if the header Calories' value is changed to "calories" without the need to change the v-slot or anything else.

**Comment by jacekkarczmarczyk** [comment]
That's how html works. You should be able to use capitalized version in SFC but not in codepen

![image](https://user-images.githubusercontent.com/15625235/62416288-fd431800-b637-11e9-986c-f4437fd6b713.png)

**Comment by ahswch** [comment]
> Through more testing, I found that the issue is specifically with the header value being capitalized. The prop can be capitalized as long as the header is not. The example given will be fully functional if the header Calories' value is changed to "calories" without the need to change the v-slot or anything else.
> 
> Header capitalized, prop capitalized: works implicitly only
> Header not capitalized, prop capitalized: works explicitly only
> Header not capitalized, prop not capitalized: works regardless

Thank you!  I make the Header not capitalized, it works well!
