### ISSUE TITLE
[Bug Report] v-app-bar bug

### ISSUE THREAD

**Issue by yakovlevkll** [vuetifyjs/vuetify#8288]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Linux x86_64

### Steps to reproduce
1. Create project with `vue create my-project`
2. Add Vuetify after `cd my-project` with `vue add vuetify`
3. Move `v-app-bar` section from generated `App.vue` to separate component, then import it

### Expected Behavior
Rendered header

### Actual Behavior
No header rendered

### Reproduction Link
<a href="https://github.com/yakovlevkll/vuetify-v-app-bar-bug" target="_blank">https://github.com/yakovlevkll/vuetify-v-app-bar-bug</a>

**Comment by jacekkarczmarczyk** [comment]
You have `components` in your `data`
