### ISSUE TITLE
Firefox: disabled v-text-field is unselectable

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#829]
### Steps to reproduce
Try to select the text in the disabled text field

### Versions
Firefox 54, latest vuetify

### What is expected ?
Text can be selected

### What is actually happening ?
Text is unselectable

### Reproduction Link
https://codepen.io/anon/pen/JJOdEJ

**Comment by johnleider** [comment]
This is not a Vuetify related caveat, it is Firefox. You can add any input (with or without Vuetify) and once you disable it, Firefox does not allow selection.
