### ISSUE TITLE
[Documentation] Vuetify 2.0 Doc  - Autocomplete Sync - :search-input.sync is used but deprecated

### ISSUE THREAD

**Issue by IxCluzts** [vuetifyjs/vuetify#8291]
### Environment

**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.1

### Steps to reproduce
1. Go to documentation
2. Go to Advanced slots
3. Look at the example source

### Expected Behavior
Advanced slots => :search-input.sync should be removed since it is not supported on vuetify v.2

### Actual Behavior
Documentation still use sync features as per the document: https://vuejs.org/v2/guide/migration.html#once-and-sync-Modifiers-on-v-bind-removed

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/autocompletes#autocompletes" target="_blank">https://vuetifyjs.com/en/components/autocompletes#autocompletes</a>

**Comment by KaelWD** [comment]
https://github.com/vuejs/vue/releases/tag/v2.3.0
