### ISSUE TITLE
[Bug Report] Right alignment of tabs in mobile sizes moves to the left.

### ISSUE THREAD

**Issue by Elprogrammador** [vuetifyjs/vuetify#8294]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Just you have to rezise the screen size to a "sm" or xm "size". 

### Expected Behavior
The alignment keep the property who was estableced, in this case "right"

### Actual Behavior
The alignment of the tabs change from right to left.

### Reproduction Link
<a href="https://codepen.io/anon/pen/Jgregj?editors=1010" target="_blank">https://codepen.io/anon/pen/Jgregj?editors=1010</a>

### Other comments
The problem also happens in Google Chrome 76.0

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTabs/VTabs.sass#L50

**Comment by jacekkarczmarczyk** [comment]
Another example broken by f3808423a055ab6d4cfbc30f571722519e38fb03 : https://codepen.io/dikeshjariwala/pen/WVKqjz

**Comment by andreyrk** [comment]
was this ever pushed to production?
