### ISSUE TITLE
[Feature Request] Create class for main app background color

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8299]
### Problem to solve
It allows you to set a background color to elements where the bg color dynamically changes based on if the theme is dark or not in the same way as the main app background.

### Proposed solution
Vuetify to have a special class for this.

https://codepen.io/anon/pen/XvzpaY?&editable=true&editors=101

In the code pen, when I create a dialog, I want the dialog bg color to be the same as the main app bg color, but currently it's some lighter gray coming from v-card.

Instead I would like to add a class or prop to it, and have it take on the same bg color as the main app. Then if I dynamically change theme from dark to light, I want it to also change bg color to the main app bg color, all without hardcoding the colors.

**Comment by johnleider** [comment]
There are quite a few ways that you could solve this, from overwriting the `v-card` default background color through sass variables, to creating a specific `theme--light`, `theme--dark` color for `.v-dialog .v-card`.

The easiest way would be to create a `core-dialog` component where you define the color based upon the value of `$vuetify.theme.dark` like this:

https://codepen.io/johnjleider/pen/dxZryg?&editable=true&editors=101

With that being said, I believe this is a userland solution and not something we would bake into the framework.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by TheInvoker** [comment]
I am using CDN to install (no sass) and that solution just hard codes the colors. Is there no better way?
