### ISSUE TITLE
v-select reverts to default text rather than selected option on blur

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#83]
When you select an option from the v-select, it shows; however as soon as you leave the field it reverts back to the defaultText. Should display the selected value similar to a native select element. See demo/documentation site for example. Thanks.

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by fontzter** [comment]
here's a fiddle: https://jsfiddle.net/fontzter/kvfcpdmk/

Thanks!
