### ISSUE TITLE
v-select: Dropdown options not appearing on the select -help

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#830]
### Steps to reproduce
Unsure, unable to reproduce in codepen. It seems to happen anywhere i use v-select in my project.

### Versions
0.12.7 (Latest)

### What is expected ?
I expected the options to be over the select field

### What is actually happening ?
The menu__content container is being created within the menu container within the select container. This is pushing the options left and off the screen in some cases.

### Reproduction Link
I have been unable to reproduce this issue in codepen. how ever i have reconstructed the page 
https://codepen.io/anon/pen/wePMQx

![weird select](https://user-images.githubusercontent.com/12128294/27569622-d5a87dc0-5b3b-11e7-98d7-3f721843ccfb.jpg)

### Extra notes
The pages are using vue-router and most content is stored within router views.

App bar and Nav drawer are in use.

Two router views are used, one for the action bars (bottom nav), and the other for the actual content of the page.

**Comment by lgullestrup** [comment]
ok this was my fault.

didn't wrap everything in <v-app>

**Comment by datesss** [comment]
himm still having this problem on 0.13.0 
![screen shot 2017-07-04 at 14 50 51](https://user-images.githubusercontent.com/9736319/27840595-4670a4ce-60c8-11e7-8550-450ea7ee7d7d.png)
