### ISSUE TITLE
How to solve dependencies not found

### ISSUE THREAD

**Issue by ljsharp** [vuetifyjs/vuetify#8300]
I want to explore Vuetify docs for offline use but this error gave me a headache. after yarn installing, i got couples of warning messages but was successful. Then error occurred when yarn building.
Please what should I do to fix this error?
Thanks in advance.
ERROR  Failed to compile with 14 errors                                                                                                                                              3:26:45 AM

These dependencies were not found:

* @vuetify/api-generator in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-loader-opti
ons!./src/components/components/ApiExplorer.vue?vue&type=script&lang=js&, C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetif
y/node_modules/vue-loader/lib??vue-loader-options!./src/components/doc/Api.vue?vue&type=script&lang=js&
* vuetify in ./src/main.js, C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-loader-opti
ons!./src/components/doc/Codepen.vue?vue&type=script&lang=js& and 1 other
* vuetify/dist/vuetify.css in ./src/entry-client.js
* vuetify/es5/locale in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-loader-options!
./src/components/doc/Locales.vue?vue&type=script&lang=js&
* vuetify/es5/mixins/ssr-bootable in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-lo
ader-options!./src/components/core/Ad.vue?vue&type=script&lang=js&
* vuetify/es5/services/goto in ./src/router/scroll-behavior.js, ./src/vuetify/index.js
* vuetify/es5/services/goto/easing-patterns in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/l
ib??vue-loader-options!./src/examples/scroll/usage.vue?vue&type=script&lang=js&, C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder
/vuetify/node_modules/vue-loader/lib??vue-loader-options!./src/examples/scrolling/usage.vue?vue&type=script&lang=js&
* vuetify/es5/util/colors in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-loader-opt
ions!./src/components/style/Colors.vue?vue&type=script&lang=js&
* vuetify/es5/util/helpers in C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/vue-loader/lib??vue-loader-op
tions!./src/components/doc/Parameters.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @vuetify/api-generator vuetify vuetify/dist/vuetify.css vuetify/es5/locale vuetify/es5/mixins/ssr-bootable vuetify/es5/services/goto vuetify/es
5/services/goto/easing-patterns vuetify/es5/util/colors vuetify/es5/util/helpers
Hash: a1004e3b426327793c6bdf14d5a3c9733386113b
Version: webpack 4.36.1
Child client:
    Hash: a1004e3b426327793c6b
    Time: 100879ms
    Built at: 08/05/2019 3:26:45 AM
    Entrypoint app = runtime~app.923d3661e7b58dd083e5.js common.782963045bf067ed1f80.css vendors~app.782963045bf067ed1f80.js common.92fc7469e9061324b506.css

    ERROR in ./src/components/components/ApiExplorer.vue?vue&type=script&lang=js& (C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New fold
er/vuetify/node_modules/vue-loader/lib??vue-loader-options!./src/components/components/ApiExplorer.vue?vue&type=script&lang=js&)
    Module not found: Error: Can't resolve '@vuetify/api-generator' in 'C:\Users\LJ Sharp\Desktop\New folder\vuetify\packages\docs\src\components\components'
     @ ./src/components/components/ApiExplorer.vue?vue&type=script&lang=js& (C:/Users/LJ Sharp/Desktop/New folder/vuetify/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/New folder/vue
tify/node_modules/vue-loader/lib??vue-loader-options!./src/components/components/ApiExplorer.vue?vue&type=script&lang=js&) 99:0-41 145:18-21 157:13-16 191:17-20 191:30-33 191:49-52
     @ ./src/components/components/ApiExplorer.vue?vue&type=script&lang=js&
     @ ./src/components/components/ApiExplorer.vue
     @ ./src/components sync \.vue$
     @ ./src/components/index.js
     @ ./src/main.js
     @ ./src/entry-client.js

**Comment by sebaveg** [comment]
I have same error. In folder docs where run _yarn_ && _yarn build_ I run _yarn add ../api-generator_ but no solution problem

**Comment by KaelWD** [comment]
It's a monorepo, you have to run it from the root directory.

**Comment by ljsharp** [comment]
I did but no solution.

**Comment by sebaveg** [comment]
I run in _package/api-generator_ **npm i && npm run build** and then in _package/docs_ npm i && npm i ../api-generator && npm run build
![111](https://user-images.githubusercontent.com/18223950/62512022-99158500-b7ec-11e9-98ec-ca58a8a0e7f7.png)

**Comment by KaelWD** [comment]
Don't use npm

https://yarnpkg.com/lang/en/docs/workspaces/

**Comment by grenukaprasad** [comment]
Hey All,
i am unable to run the docs offline

Steps:
1. git clone https://github.com/vuetifyjs/vuetify.git
2. cd {myfolderlocation}/vuetify-master/packages/docs/
3. yarn install
4. yarn dev (for development)
5. http://localhost:8095/en/

![image](https://user-images.githubusercontent.com/51689890/63638752-e7aa9680-c6a9-11e9-9cbc-08f71b230cb3.png)

node version is 10.16.3
yarn version is 1.17.3

![image](https://user-images.githubusercontent.com/51689890/63638804-5be53a00-c6aa-11e9-95a1-981d99a0ff3d.png)

any solutions?

**Comment by jacekkarczmarczyk** [comment]
in root folder:
```bash
yarn
yarn build
yarn dev docs // for development
yarn start // for browsing
```

**Comment by grenukaprasad** [comment]
Nope... not working... tried that too 
![image](https://user-images.githubusercontent.com/51689890/63638881-4c1a2580-c6ab-11e9-9a01-eec3501e43b6.png)

**Comment by grenukaprasad** [comment]
Thanks it works after building

**Comment by ljsharp** [comment]
grenukaprasad, Sir, can I please have your vuetify docs zipped for me to use? I have been trying to fix the problem but no solution. I will really appreciate if you can drop me your docs here for me to download it. Thanks in advance bro.

**Comment by grenukaprasad** [comment]
Yep sure
[vuetify-master.zip](https://github.com/vuetifyjs/vuetify/files/3537352/vuetify-master.zip)

Please follow there steps after extracting
https://github.com/vuetifyjs/vuetify/issues/8300#issuecomment-524555249

**Comment by ljsharp** [comment]
Okay thanks. I will do it right away.

**Comment by ljsharp** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/17466284/63640288-df446280-c68d-11e9-9359-9edf4ed198dc.png)

ERROR in ./src/components/doc/Api.vue?vue&type=script&lang=js& (C:/Users/LJ Sharp/Desktop/vuetify-master/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/vuetify-master/node_modules/vue-loader/lib??vue-loader-options!./src/components/doc/Api.vue?vue&type=script&lang=js&)
    Module not found: Error: Can't resolve '@vuetify/api-generator' in 'C:\Users\LJ Sharp\Desktop\vuetify-master\packages\docs\src\components\doc' 
     @ ./src/components/doc/Api.vue?vue&type=script&lang=js& (C:/Users/LJ Sharp/Desktop/vuetify-master/node_modules/babel-loader/lib!C:/Users/LJ Sharp/Desktop/vuetify-master/node_modules/vue-loader/lib??vue-loader-options!./src/components/doc/Api.vue?vue&type=script&lang=js&) 102:0-41 207:46-49
     @ ./src/components/doc/Api.vue?vue&type=script&lang=js&
     @ ./src/components/doc/Api.vue
     @ ./src/components sync \.vue$
     @ ./src/components/index.js
     @ ./src/main.js
     @ ./src/entry-client.js


I got this error. How can I solve this problem?

**Comment by grenukaprasad** [comment]
Ok.... i will rewrite the proper steps...

`git clone https://github.com/vuetifyjs/vuetify.git`
`cd {folderLocation}/vuetify-master/`
`yarn` or `yarn install`
`yarn build`
`yarn dev docs`

node version needs to be more than 10
and yarn version is 1.17.3

**Comment by ljsharp** [comment]
Okay I will try it now.

**Comment by ljsharp** [comment]
The error still exists but api - generator folder exists under packages.

**Comment by grenukaprasad** [comment]
can i have your node and yarn versions? and did you build your project?
I have shared a dist folder zip file of vuetify/packages/docs for reference...

[dist.zip](https://github.com/vuetifyjs/vuetify/files/3537445/dist.zip)

**Comment by ljsharp** [comment]
Yes sure. 
Node version: v10.16.1
Yarn version: 1.17.3

**Comment by grenukaprasad** [comment]
Are you building the project in root directory(vuetify or vuetify-master)?
`yarn run build`
`yarn run dev docs`
in {folderlocation}/vuetify

and Please try upgrading node to v10.16.3 and trying again

sharing api-generator zip just in case
[api-generator.zip](https://github.com/vuetifyjs/vuetify/files/3537470/api-generator.zip)

**Comment by ljsharp** [comment]
Okay copy that.

**Comment by ljsharp** [comment]
Yes please I was building in vuetify folder which was compiled successfully but when runing dev, I still got the same error.
Alright bro, you have helped me to try to fix it so thank you. I will stick to online Vuetify documentation though.

**Comment by ljsharp** [comment]
The problem has been solved by the following:
git clone <vuetify repo>
cd vuetify 
yarn or yarn install
yarn build
yarn start
http://localhost:8095.
Done!!! 😊
