### ISSUE TITLE
[Feature Request] VDataTable should have mobile property

### ISSUE THREAD

**Issue by ngongon** [vuetifyjs/vuetify#8302]
### Problem to solve
When breakpointXsOnly, VDataTable turns into mobile-row view, but it should be optional. For some reasons like customizing cells, I want to make the table as desktop view. Also, sortby option is malfunctioning at this moment(sortable=false doesn't work on mobile view)

### Proposed solution
VDataTable should have 'mobile' property, which enables mobile view when xsOnly.

**Comment by jacekkarczmarczyk** [comment]
It turns into mobile view when it reaches mobile breakpoint which you can change https://codepen.io/anon/pen/bXYLpz?&editable=true&editors=101, there's no need imho for a separate prop

For problems with sortby please create a new issue using a bug report template
