### ISSUE TITLE
[Feature Request] Add rounded prop to v-sheet

### ISSUE THREAD

**Issue by HeadAdmiral** [vuetifyjs/vuetify#8307]
### Problem to solve
Vuetify lacks a component which emulates the extra-rounded corners that you can find in a lot of Google's applications. The Backdrop component on material.io is a great example of this.

### Proposed solution
Add a rounded prop to v-sheet. This would partially encompass the functionality of the backdrop component without the need for creating a new component.

**Comment by baishishi** [comment]
This feature is very much needed.

**Comment by johnleider** [comment]
Happy to report that this has been resolved for some time now.

https://codepen.io/johnjleider/pen/zYKxzRW

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
