### ISSUE TITLE
[Bug Report] v-autocomplete/v-select selected item getting collapsed when text is more length

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#8308]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6, Android, iOS, Mac OSX, Windows

### Steps to reproduce
select 1st item in dropdown

### Expected Behavior
selected item's text should be truncated when text has more length

### Actual Behavior
<input > item makes issue

### Reproduction Link
<a href="https://codepen.io/ksankumar/pen/rXpVxV" target="_blank">https://codepen.io/ksankumar/pen/rXpVxV</a>

**Comment by johnleider** [comment]
Realistically, the only thing we can really do would be to hide the overflow of the chip or destroy the ability to put anything inside of the chip and have it properly aligned.

Taking any suggestions, help wanted.

Workaround: https://codepen.io/johnjleider/pen/LwepzX

**Comment by VinitaPotter** [comment]
Can I work on this?

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
