### ISSUE TITLE
[Feature Request] allow autocomplete to keep partial search-input

### ISSUE THREAD

**Issue by gotenxds** [vuetifyjs/vuetify#8310]
### Problem to solve
Currently with autocomplete you can search for an item but not for partial data.
for example when I write `de` I wand to see all items the contains `de` in the name without needing to select one of them as doing so removes all outer finds.
You can see what I mean in this gif : https://i.imgur.com/PCvT9Mz.gifv

### Proposed solution
Add some property that will disable to auto clear when partial text entered.

**Comment by jacekkarczmarczyk** [comment]
You mean v-combobox?

**Comment by gotenxds** [comment]
Hi, ya, the v-combox is what I was looking for. I think it is confusing that we have 3 different components(comboxbox, autocomplete and select) to do very similar behaviors and we should just allow props for those behaviors,

**Comment by johnleider** [comment]
We used to have them all together within a single `v-select` component but maintenance became very cumbersome.

**Comment by johnleider** [comment]
I also still don't understand what you are looking for.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
