### ISSUE TITLE
[Feature Request] v-responsive, v-img tag props

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#8314]
### Problem to solve
none

### Proposed solution
how about add tag props in v-responsive and v-img

v-responsive, v-img default tag is `div` tag

but when use in `a` tag

`span` tag is more prefer then `div`

just request..thanks

**Comment by johnleider** [comment]
If this does happen it will be a natural thing as part of the version 3 update. You can watch either #12701 or #12727.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
