### ISSUE TITLE
[Bug Report] In appropriate icon in custom actions -Card Component

### ISSUE THREAD

**Issue by inra003** [vuetifyjs/vuetify#8316]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
I have change the code for the icon only. 

<v-icon>{{ show ? 'keyboard_arrow_up' : 'keyboard_arrow_down' }}</v-icon>

### Expected Behavior
<v-icon>{{ show ? 'keyboard_arrow_up' : 'keyboard_arrow_down' }}</v-icon>

### Actual Behavior
<v-icon>{{ show ? 'keyboard_arrow_down' : 'keyboard_arrow_up' }}</v-icon>

### Reproduction Link
<a href="https://codepen.io/inra003/pen/pMpWNX" target="_blank">https://codepen.io/inra003/pen/pMpWNX</a>

**Comment by KaelWD** [comment]
You don't have that icon font loaded.
