### ISSUE TITLE
[Bug Report] Weird data table expand slot css

### ISSUE THREAD

**Issue by OysterD3** [vuetifyjs/vuetify#8322]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Using v-slot:expanded-item="props"

### Expected Behavior
In 1.5.16, the expand slot will not resize the `<tbody>` and will force the element in expand slot fit in.

### Actual Behavior
Images that with huge resolution will resize the `<tbody>` and user will have to scroll horizontally

### Reproduction Link
<a href="https://codepen.io/OysterD3/pen/dxJKbO" target="_blank">https://codepen.io/OysterD3/pen/dxJKbO</a>

### Other comments
Not sure if it's because of the `<v-layout>`

**Comment by nekosaur** [comment]
You will need to define the `<td>` elements of `expanded-item` slot in 2.0. This was missed in the upgrade guide but I have now added it.

See https://codepen.io/anon/pen/oKpQRO

**Comment by OysterD3** [comment]
In your codepen, the user still has to scroll horizontally.
How can I make it behave like this https://codepen.io/OysterD3/pen/dxJrYK

It's v1.5.16 by the way

**Comment by OysterD3** [comment]
> You will need to define the `<td>` elements of `expanded-item` slot in 2.0. This was missed in the upgrade guide but I have now added it.
> 
> See https://codepen.io/anon/pen/oKpQRO

In your codepen, the user still has to scroll horizontally.
How can I make it behave like this https://codepen.io/OysterD3/pen/dxJrYK

It's v1.5.16 by the way
