### ISSUE TITLE
[Bug Report] a dismissible v-alert gets misshapen by the height of the dismiss button

### ISSUE THREAD

**Issue by he3er** [vuetifyjs/vuetify#8323]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
setting a v-alert to be dismissible causes the v-alert component to get misshapen by what seems to be the height of the dismiss icon/button

The issue is more visible if the v-alert component is set to be "dense"

### Expected Behavior
For the height of the dismiss icon/button to adapt to the component height, not the opposite

### Actual Behavior
The component gets misshapen by the height of the dismiss button

### Reproduction Link
<a href="https://codepen.io/Memc/pen/qepZoX" target="_blank">https://codepen.io/Memc/pen/qepZoX</a>

### Other comments
tested also on:
Chromium Version 76.0.3809.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/commit/d3bfccb
