### ISSUE TITLE
[Bug Report] Week-view breaks when changing weekdays to [1, 2, 3, 4, 5, 6, 0]

### ISSUE THREAD

**Issue by sanderquirynen** [vuetifyjs/vuetify#8324]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
In example calendar at https://vuetifyjs.com/en/components/calendars,
set :weekdays="[1, 2, 3, 4, 5, 6, 0]" on v-calendar
change the view to 'week'

### Expected Behavior
Change to week view

### Actual Behavior
Chrome tab crashes

### Reproduction Link
<a href="https://codepen.io/anon/pen/aeEMqG?&editable=true" target="_blank">https://codepen.io/anon/pen/aeEMqG?&editable=true</a>

**Comment by ClickerMonkey** [comment]
You're not supposed to send an array constant to a prop, so ideally you pass a variable name. In a recent release I allow you to pass a comma delimited string, so if you update to a newer version of Vuetify and switch it to `weekdays="1,2,3,4,5,6,0"` you should be good.
