### ISSUE TITLE
[Bug Report] Default Slot Scope for Image not working inside v-hover

### ISSUE THREAD

**Issue by baldeepsinghkwatra** [vuetifyjs/vuetify#8325]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
In the below code default scope for the image is not working inside hover, Check CodePen
  
### Expected Behavior
slot scope for the image should work when inside v hover

### Actual Behavior
slot scope for the image is not working when inside v hover

### Reproduction Link
<a href="https://codepen.io/anon/pen/oKEXEw" target="_blank">https://codepen.io/anon/pen/oKEXEw</a>

**Comment by johnleider** [comment]
This is not a valid reproduction, please update your example.

**Comment by baldeepsinghkwatra** [comment]
I have updated the reproduction link. (https://codepen.io/anon/pen/oKEXEw)
If you comment out the default slot of the image then hover will work. 
Else in the current case hover is not showing. 
Till version 1.5 on hover, we used to click on delete icon which displayed the default slot for an image that showed deleting processing loader.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/components-slots.html#Abbreviated-Syntax-for-Lone-Default-Slots

This isn't 100% clear but you're basically mixing the two slot types

> Whenever there are multiple slots, use the full <template> based syntax for all slots:

**Comment by baldeepsinghkwatra** [comment]
I am using full based syntax only, Please re-check the CodePen shared previously.
You will find that there are two components:
**1) Hover -** having 1 default slot in full syntax
**2) Image -** having 2 slots (default+ placeholder) in full syntax

I want all the three slots to function.
The placeholder slot for the image is shown when the image is loading initially.
Then user hovers on the image, which shows a delete button & when he clicks on delete button the default slot of the image is shown displaying a loader that image is being deleted.

Currently, if you comment out the default image slot and hover on the image you will see the delete button.
So the issue does not seems to be fixed.

**Comment by KaelWD** [comment]
You don't have a placeholder slot, and that isn't a thing. You have an expand-transition in the default slot, and then a v-layout in the default slot again overriding the first one. If you just remove the `<template v-slot:default>` it works as expected.

**Comment by jacekkarczmarczyk** [comment]
or `<v-img :aspect-ratio="1" src="https://cdn.vuetifyjs.com/images/cards/kitchen.png" #default>`

**Comment by baldeepsinghkwatra** [comment]
@KaelWD the default slot that you want me to remove is for the v-img component which is placed inside the default slot for v hover.
So we have two default slots here one for hover and other for the image. I want to use both of them. But it does not seem to work. (Maybe because of default naming conflict), Is there a workaround?

**Comment by baldeepsinghkwatra** [comment]
`<div id="app">
   <v-app id="inspire">
      <v-hover>
         <template v-slot:default="{ hover }">
            <v-card class="mx-auto" color="grey lighten-4">
               Showing Image Below
               <v-img :aspect-ratio="1" src="https://cdn.vuetifyjs.com/images/cards/kitchen.png">
                  <v-expand-transition>
                     <div v-if="hover" class="d-flex transition-fast-in-fast-out orange darken-2 v-card--reveal title white--text" style="height: 100%;">
                        <v-tooltip bottom>
                           <template v-slot:activator="{ on }">
                              <v-btn @click="onDelete" class="mr-0 ml-1 v-btn--hover" fab small color="error darken-2" v-on="on">
                                 <v-icon small>delete</v-icon>
                              </v-btn>
                           </template>
                           <span>Delete</span>
                        </v-tooltip>
                     </div>
                  </v-expand-transition>
                  <template v-slot:default>
                     <v-layout fill-height align-center justify-center ma-0>
                        <v-progress-circular size="100" indeterminate color="grey lighten-5">
                           <span class="title">Deleting</span>
                        </v-progress-circular>
                     </v-layout>
                  </template>
               </v-img>
            </v-card>
         </template>
      </v-hover>
   </v-app>
</div>`

**Comment by baldeepsinghkwatra** [comment]
Tried with full syntax and # based as shared by @jacekkarczmarczyk 
https://codepen.io/baldeepsinghkwatra/pen/vodPMM
