### ISSUE TITLE
[Bug Report] Style binding with string not working on v-row

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#8328]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Look at the codepen

### Expected Behavior
Text is hidden

### Actual Behavior
Text is visible

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/pMaNgG" target="_blank">https://codepen.io/johnjleider/pen/pMaNgG</a>

**Comment by KaelWD** [comment]
https://github.com/alexsasharegan/vue-functional-data-merge/commit/6894fa7f97ba216f3fefd0754a80a878a9083095
