### ISSUE TITLE
Feature Request: `.native` should not be required for common events (ex: `click`)

### ISSUE THREAD

**Issue by Morgul** [vuetifyjs/vuetify#833]
I've been looking into Vuetify, and I'm very impressed with what I see. However, I've noticed that Vuetify requires the use of `.native` on common events (like `click`), and I've gone the rounds on that before with a few other libraries I contribute to. Here is a slightly modified version of the argument I've successfully made elsewhere:

> Vue's change to require `@click.native` lead me to question my design choice of reemitting in some of the libraries I've been writing, and left me wondering if I was not following best practices, so I asked on the Vue forums:
> 
> https://forum.vuejs.org/t/should-libraries-require-native/7885
>
> Evan responded with this:
>
> > I would personally re-emit it to present a more natural interface to the user. The only possible drawback of re-emitting is you need to be explicit about the events you re-emit in the docs so that the users won't be surprised when they try some other events without `.native` and find them not working.
>
> (There was also a mention of making those components [functional][], where that paradigm makes sense. Functional components don't require `.native`.)
>
> Personally, I find the change to `@click.native` to be a very frequent papercut, as none of the other libraries I use frequently require it, and it's not how I've trained myself to write Vue code.
> 
> [functional]: https://vuejs.org/v2/guide/render-function.html#Functional-Components

Having helped to make this change in a few other places, I can admit that while it's a pretty minor change, it touched a lot of places. Still, I feel like Vuetify would be strongly improved by removing this papercut. :smile:

**Comment by johnleider** [comment]
Wew this might take a bit.

**Comment by Morgul** [comment]
Maybe the best place to start is to go components by component and document what events it should rethrow. If you can make up a list, I'm more than happy to start working it and putting in some PRs.

**Comment by johnleider** [comment]
Yea, this will have to be a 0.14 under-taking.

**Comment by Morgul** [comment]
@johnleider Oh, I figured. :smile:

**Comment by ACalitz** [comment]
Hi there, I see the new vue.js release (2.4.0) has added some functionality that might make this easier. They call it 'Easier creation of wrapper components'.

Not exactly sure if it is related, just thought I would post this here incase.

**Comment by Morgul** [comment]
From the [release notes](https://github.com/vuejs/vue/releases/tag/v2.4.0):

> New instance properties: $attrs & $listeners. $attrs contains the parent-scope attribute bindings that were not recognized as props, and $listeners contains the v-on listeners registered in the parent scope (without the .native modifier). These are essentially aliases of $vnode.data.attrs and $vnode.data.on, but are reactive.
>
> Combining these allows us to simplify a component like this down into this:
> ```html
> <div>
>  <input v-bind="$attrs" v-on="$listeners">
> </div>
> ```

That certainly does make it easier, as you no longer have to bind to every single event that you want to rethrow. What's more, `$attrs` and `$listeners` are _reactive_, which makes them even nicer. :smile:
