### ISSUE TITLE
[Bug Report] V-Slide-Group scrollability does not change when items are added/removed

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#8330]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.0

### Steps to reproduce
* Configure a `v-slide-group` with a number of items that does not require scrollability
* Add items programmatically so that scrollability is required

### Expected Behavior
the `v-slide-group` will be scrollable when required by added items

### Actual Behavior
it remains non-scrollable

### Reproduction Link
<a href="https://codepen.io/fontzter/pen/ZgrOpB?&editable=true&editors=101" target="_blank">https://codepen.io/fontzter/pen/ZgrOpB?&editable=true&editors=101</a>

### Other comments
The inverse is also true...if you start scrollable and remove items, it does not remove the scrollability

**Comment by fontzter** [comment]
should line 139 be
`if (this.internalItemsLength === (this.$children || []).length) return`
instead of
`if (this.internalItemsLength === (this.$children.length || [])) return`
?

**Comment by emax77** [comment]
Does that bug have been fixed ? I still experience the same issue with vuetify version 2.1.5
