### ISSUE TITLE
[Bug Report] v-slide-group not wrap or truncate long word

### ISSUE THREAD

**Issue by bc96123** [vuetifyjs/vuetify#8333]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Create a slide-group, put the card inside the slide-group, put a long word in card-title or card-text

### Expected Behavior
The word should be wrapped or truncated

### Actual Behavior
The word going out of the box

### Reproduction Link
<a href="https://codepen.io/bc96123/pen/JgpOoy" target="_blank">https://codepen.io/bc96123/pen/JgpOoy</a>

### Other comments
slider-group may use for image or button, it should works with card that contains a bunch of words

**Comment by fontzter** [comment]
fwiw, i ran into this and a quick work-around is to add `class="text-wrap"` to the `v-card-text`.
https://codepen.io/fontzter/pen/vojyQx
