### ISSUE TITLE
[Documentation] Page not found for "Content Styles"

### ISSUE THREAD

**Issue by brunopulis** [vuetifyjs/vuetify#8335]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
When I click on the "Content Styles" submenu of "Styles & Animations"

### Expected Behavior
I expected that the documentation page would open with the available information.

### Actual Behavior
Page is displayed blank with a message "Whoops, 404 The page you were looking for does not exist"

### Reproduction Link
<a href="https://vuetifyjs.com/en/styles/content" target="_blank">https://vuetifyjs.com/en/styles/content</a>

**Comment by KaelWD** [comment]
Unable to reproduce, try clearing your cache.
