### ISSUE TITLE
[Documentation] Page not found for "Alignment"

### ISSUE THREAD

**Issue by brunopulis** [vuetifyjs/vuetify#8336]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
When I click on the "Alignment" submenu of "Styles & Animations"

### Expected Behavior
I expected that the documentation page would open with the available information.

### Actual Behavior
Page is displayed blank with a message "Whoops, 404 The page you were looking for does not exist"

### Reproduction Link
<a href="https://vuetifyjs.com/en/styles/alignment" target="_blank">https://vuetifyjs.com/en/styles/alignment</a>

**Comment by KaelWD** [comment]
Duplicate of #8335
