### ISSUE TITLE
[Bug Report] Menu width in IE11

### ISSUE THREAD

**Issue by Zhernet** [vuetifyjs/vuetify#8338]
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Go to https://vuetifyjs.com/en/components/menus#absolute-position-without-activator with IE11
1. Try to open a menu

### Expected Behavior
The menu should be displayed correctly.

### Actual Behavior
The menu width is too small to display anything

### Other comments
It works fine with the version 1 of Vuetify. See: https://vuetifyjs.com/en/components/menus#absolute-position-without-activator.

A temporary fix is to add a `min-width` to `<v-list>`

**Comment by johnleider** [comment]
Tried a few fixes but all had issues with browsers that are not ie11.

**Comment by mseele** [comment]
One more thing.

Without `v-list-item-avatar text` is also not centered vertically:
![screenshot](https://user-images.githubusercontent.com/15141672/65758073-b0039400-e118-11e9-8e28-614d2a2952ba.png)

Workaround is to add a div with "correct" height in front of `v-list-item-title`:
```
<div style="height: 48px;"></div>
<v-list-item-title>{{ item.title }}</v-list-item-title>
```

**Comment by cjhih456** [comment]
i found a solution..
i hope to take better idea

```
    <v-list-item>
      <v-list-item-content class="flex-grow-0 flex-shrink-1 px-0"/>
      <v-list-item-action class="flex-grow-1 ml-0">
        {{ item.title }}
      </v-list-item-action>
    </v-list-item>
```
it's running clearly on ie11 & chrome

**Comment by Webifi** [comment]
Any updates on this?  The "work-around" (adding a min-width) doesn't seem to support dynamic widths, so not really a work-around.

**Comment by maiorano84** [comment]
This bug is affecting #9185 

Absolutely positioned menus in IE are failing both locally as well as on the Vuetify website examples. Min widths are not an acceptable workaround, as not all menu widths can be calculated beforehand.

**Comment by Mikilll94** [comment]
Ping. Is this going to be fixed?

**Comment by jworkmeister0** [comment]
I'm currently working around this by overriding `display: flex;` to `display: block;` in `.v-list-item` (see [here](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VList/VListItem.sass#L28)). This is not ideal, but it's a quick and dirty fix for the time being.

**Comment by johnleider** [comment]
This issue has existed for years and currently has a workaround. We just do not have the bandwidth to work with IE11 bugs and since Vuetify 3 drops IE11 support, as such, I'm going to close this issue.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
