### ISSUE TITLE
[Bug Report] Vuetify does not compile when using Typescript

### ISSUE THREAD

**Issue by hamza0867** [vuetifyjs/vuetify#8339]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Run yarn serve.
Open browser with the correct url (usually "localhost:8080").
Click on the lightbulb button on the top right corner.
The theme will change from light to dark.

Run yarn build.
The build will fail with the error: "Property 'framework' does not exist on type 'Vuetify'."

### Expected Behavior
Since the App is serving and working correctly, I expect it to build

### Actual Behavior
It fails to build with the error: "Property 'framework' does not exist on type 'Vuetify'." 

### Reproduction Link
<a href="https://github.com/hamza0867/vuetify-ts-bug" target="_blank">https://github.com/hamza0867/vuetify-ts-bug</a>

### Other comments
Yes I added: "vuetify/types" in tsconfig.json in the "types" array

**Comment by nekosaur** [comment]
Use the `$vuetify` instance on `this`.

```js
this.$vuetify.theme.dark = !this.$vuetify.theme.dark;
```

**Comment by KaelWD** [comment]
Also #7387

**Comment by hamza0867** [comment]
Yeah I know about that. But what about when I want to achieve the same inside an mutation call ( in vuex ) ?? The store doesn't have reference to $vuetify. Does it ?? Did I miss something ??

**Comment by KaelWD** [comment]
#7387
