### ISSUE TITLE
v-tabs-slider is not initially shown when v-tabs are within v-tabs

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#834]
### Steps to reproduce
When tabs are within tabs the slider is not visible on first load. Once a different tab is clicked it will show correctly and stays visible.
### Versions
Vue 2.3.4
Vuetify 0.12.7
Win 10, Chrome 58
### What is expected ?

v-tabs-slider is visible at the correct tab
### Reproduction Link

https://codepen.io/anon/pen/MoOxvv

**Comment by johnleider** [comment]
I can confirm this is fixed in dev.
