### ISSUE TITLE
[Bug Report] Incorrect icons vertical align in two-line list group

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#8340]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
Open reproduction link

### Expected Behavior
Prepend icon and chevron-down icon are vertical aligned to the center

### Actual Behavior
Prepend icon and chevron-down icon are vertical aligned to the top

### Reproduction Link
<a href="https://codepen.io/anon/pen/wVyKgw" target="_blank">https://codepen.io/anon/pen/wVyKgw</a>

### Other comments
VListGroup missed two-line prop

**Comment by johnleider** [comment]
The prepend-icon is not supposed to be center aligned per spec: https://material.io/design/components/lists.html#specs

The only reason it is in your first example is that you are using `v-list-item-action` instead of `v-list-item-icon`.
