### ISSUE TITLE
[Feature Request] Calendar 24hrs

### ISSUE THREAD

**Issue by ScopZy** [vuetifyjs/vuetify#8342]
### Problem to solve
Can you add an option to put 24hrs format for events in the calendar (actually : 9:00a - 9:00p).
But for 24hrs format need to be : 9:00 - 21:00
Thanks a lot

### Proposed solution
add an option: 12hrs - 24hrs

**Comment by ClickerMonkey** [comment]
@ScopZy 

For now you could use the `interval-format` prop to pass your own function. The function receives two arguments, a `timestamp` and `short`. `short` is determined by the value of the prop `short-intervals` (default true) passed to the calendar.

Here's the data available in the `timestamp` variable: https://github.com/vuetifyjs/vuetify/blob/0df2dc0a81f53321c420f898fa95ed23e181ebfe/packages/vuetify/src/components/VCalendar/util/timestamp.ts#L17

@johnleider 
Here are our options, let me know what you think:

1. Leave the code as-is and recommend the `interval-format` function.
2. Change the code so time formatting is only based on locale. There are no options.
3. Time formatting is controlled by a new prop `interval-time-format` which accepts nothing (which means browser locale determines it), 12 or 14.

Resources:
- https://devhints.io/wip/intl-datetime
- https://github.com/vuetifyjs/vuetify/blob/0df2dc0a81f53321c420f898fa95ed23e181ebfe/packages/vuetify/src/components/VCalendar/mixins/calendar-with-intervals.ts#L67
