### ISSUE TITLE
[Feature Request] Click and select event for data-table needed

### ISSUE THREAD

**Issue by ebolavirus** [vuetifyjs/vuetify#8345]
### Problem to solve
we need to show other content and do some logic when a list item is selected/high-lighted, so we hope the v-data-table add a event callback like item-clicked,item-double-clicked.also, this may need a color change when a data table item is selected.

### Proposed solution
v-data-table add a event callback like item-clicked,item-double-clicked.also, this may need a color change when a data table item is selected.

**Comment by nekosaur** [comment]
There is both a `@click:row` event and a `item-selected` event.
