### ISSUE TITLE
[Bug Report] Events on v-text-field

### ISSUE THREAD

**Issue by Alfred75** [vuetifyjs/vuetify#8347]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
Change text field values and watch event counters

### Expected Behavior
change to be trigger when value has changed and we leave the text field
blur/focus to be triggered when we enter/leave
lazy attribute to stop changing v-model value unless change is triggered

### Actual Behavior
Change events is "random"
blur and focus events only fired when input is also fired
lazy does not work

### Reproduction Link
<a href="https://codepen.io/Alfred75/pen/LwQgBW" target="_blank">https://codepen.io/Alfred75/pen/LwQgBW</a>

### Other comments
Maybe it's something I dont understand

**Comment by johnleider** [comment]
A few things:

- You have the same bound input event for multiple, so it appears weird

![image](https://user-images.githubusercontent.com/9064066/62638426-0adff280-b903-11e9-9a39-0d25117c726f.png)

- You are modifying an array by index which does not trigger reactivity
- .lazy doesn't work for custom components
- If you watch the events in vue-dev-tools you will see that it's working correctly

**Comment by Alfred75** [comment]
thanks a lot for clear reply. works as intended now
