### ISSUE TITLE
[Bug Report] v-data-table dont work with array syntax

### ISSUE THREAD

**Issue by cde-laro** [vuetifyjs/vuetify#8349]
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 1.5.2
**Vue Version:** 2.6.7
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a `v-data-table` where the items values are in an other object that contain a `-` char, so you need to do something like this `name['en-US']` to use it

### Expected Behavior
Display the correct data

### Actual Behavior
All the ['en-US'] values dont display in the data-table

### Reproduction Link
<a href="https://codepen.io/wilstan/pen/ZgrPEb" target="_blank">https://codepen.io/wilstan/pen/ZgrPEb</a>

**Comment by KaelWD** [comment]
It's just dot-separated, not javascript. `name.with-dash` works.
