### ISSUE TITLE
[Bug Report] File inputs component does not support Named Slots

### ISSUE THREAD

**Issue by 1995Everton** [vuetifyjs/vuetify#8351]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
Add to Named Slots Without Multiple Property
When executing the code you get the error: "this.internalValue.forEach is not a function"

### Expected Behavior
Edit the selected item with the slot

### Actual Behavior
It is only possible to add the slot if there is a prop "multiple"

### Reproduction Link
<a href="https://codepen.io/1995everton/pen/XvZQjY" target="_blank">https://codepen.io/1995everton/pen/XvZQjY</a>

### Other comments
sorry my english. : (

**Comment by nekosaur** [comment]
Line 182 should use `internalArrayValue` instead of `internalValue`
