### ISSUE TITLE
[Documentation] vuetify variable not in scope in unit testing spec example

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#8357]
### Environment

**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Scroll down to the `beforeEach` area of the code

### Expected Behavior
Spec test case example can be mounted.

### Actual Behavior
Spec test cases example can't be mounted due to out of scope variable.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/unit-testing#spec-tests" target="_blank">https://vuetifyjs.com/en/getting-started/unit-testing#spec-tests</a>

### Other comments
Moving the vuetify const outside of the `beforeEach` function will allow it to be accessed when being mounted in the test cases.

```
let vuetify

beforeEach(() => {
  vuetify = new Vuetify(...)
})
```

**Comment by johnleider** [comment]
resolved in 0df2dc0
