### ISSUE TITLE
[Bug Report] v-img on Firefox

### ISSUE THREAD

**Issue by moisesfk** [vuetifyjs/vuetify#8362]
### Environment
**Vuetify Version:** 2.0.0-beta.9
**Vue Version:** 2.6.8
**Browsers:** Firefox 68.0
**OS:** Windows 7

### Steps to reproduce
Sorry for the fake reproduction link, but sometimes the firefox dont load v-img
to test, access https://vuetifyjs.com/en/, sometimes the imagens will not load
i'm on firefox 68.0.1 (64-bits)
these behavior is often when I dont use fierefox for a while...

### Expected Behavior
Always show the images

### Actual Behavior
Sometimes firefox dont load images

### Reproduction Link
<a href="https://jsfiddle.net/zcfgd74r/" target="_blank">https://jsfiddle.net/zcfgd74r/</a>

**Comment by KaelWD** [comment]
Refreshed like 20 times with a clean cache and it worked fine.

**Comment by peluprvi** [comment]
It looks like a Firefox issue.
Someone reported it too on Discord channel and he said:

> It happens on Firefox 68.0.1 (64-bits), with Windows 7 or 10, clean install, without extensions. It started after I update the Firefox from version 64.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
