### ISSUE TITLE
[Documentation] Sass variables Documentation Clarification

### ISSUE THREAD

**Issue by cpitt** [vuetifyjs/vuetify#8366]
### Problem to solve
The current documentation for [Sass Variables](https://vuetifyjs.com/en/customization/sass-variables) seems to assume one is using the vuetify-loader or the vue-cli-vuetify. (Based on assumption that minified css would clash with sass, and main.sass isn't imported by default but only with vuetify/lib).

### Proposed solution
Update the documentation to include steps to configure SASS without vuetify-loader and/or explicitly call out that sass is only supported with vuetify-loader.

**Comment by cpitt** [comment]
I'm happy to write the documentation given that someone can validate my assumptions.

**Comment by MajesticPotatoe** [comment]
I would agree having clarity of sass variable use with and without vuetify-loader would be beneficial. If you would like to write it up and submit a PR by all means.

**Comment by bromix** [comment]
I can validate parts of it. I used sass without vuetify-loader first, later with vuetify-loader. So I used both ways. Right now vuetify-loader 1.3.0 seems to be broken, because sinse the update from 1.2.2 my main.scss isn't loaded anymore. So I test with vuetify-loader 1.2.2

**Comment by cpitt** [comment]
@bromix 
In your plugins/vuetify.js (or wherever your bootstrapping vuetify) file did you change
`import Vuetify from 'vuetify';` -> to `import Vuetify from 'vuetify/lib';`

**Comment by cpitt** [comment]
So in order to support sass without vuetify loader it appears you have to 
1. import main.sass
2. import styles.sass
3. setup vue.config with sass loader

I need to validate on clean repo, as my project repo is having some issues

**Comment by bromix** [comment]
@cpitt 
Strange, if I use `import Vuetify from 'vuetify/lib'`; the layout is allright, but non of the theme colors are used. It's all grey'ish.

**Comment by cpitt** [comment]
@bromix once you have vuetify/lib imported everything should work assuming you've followed the existing documentation 

https://vuetifyjs.com/en/customization/sass-variables

**Comment by bromix** [comment]
@cpitt 
I'll update the project structure via VUE CLI3. My current work is based on an updated existing HTML-Project. Maybe some of my configuration aren't okay. My tests with VUE CLI3 and SASS variables worked so far. I'll give feedback as soon as I'm finished.

**Comment by bromix** [comment]
So I converted to project creation to vue cli3 and everything is wokring. I could follow the guide:
[SASS variables](https://vuetifyjs.com/en/customization/sass-variables)

Loading a main.scss and change some of the vars worked also.
