### ISSUE TITLE
[Bug Report] Component doesn't update on dynamically generated array

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8370]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Windows 10

### Steps to reproduce
Click the buttons.

### Expected Behavior
Tooltip shows up.

### Actual Behavior
Tooltip doesn't show up.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/BXrjOp?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/BXrjOp?&editable=true&editors=101</a>

### Other comments
I want to create a toggle tooltip based on a generated array, where it remembers the state (for v-model).

**Comment by jacekkarczmarczyk** [comment]
items returned by getData are not reactive and if you make them reactive getData will be called every time something changes and show will be resetted to false
