### ISSUE TITLE
[Bug Report] Can't migrate from v1.5 to v2.0

### ISSUE THREAD

**Issue by MohamadCM** [vuetifyjs/vuetify#8381]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.6
**Browsers:** Firefox 68.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
Update vuetify to newest version using npm install vuetify@latest --save

### Expected Behavior
Should display site same as before update

### Actual Behavior
Noting is shown in the page

### Reproduction Link
<a href="https://github.com/MohamadCM/login-vue" target="_blank">https://github.com/MohamadCM/login-vue</a>

**Comment by jacekkarczmarczyk** [comment]
Your repo still has vuetify 1.5 in package.json, so clearly you didn't commit your changes after running npm install. Also it definitely won't display site same as before update before lot of things has changed, you need to go through the upgrade guide in release notes https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0 and update vue-cli-plugin-vuetify as well

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
