### ISSUE TITLE
[Bug Report] <v-list-item-action> placed on the <v-menu> do not focus

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#8386]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a list, one of which will be inactive.
In this item, create an interactive button in action.
Put your list in the drop down box.
Try clicking on the interactive button using the keyboard only

### Expected Behavior
Moving from the keyboard, the focus alternately switches between the `<v-list-item>` and their `<v-list-item-actions>`

### Actual Behavior
When moving from the keyboard, `<v-list-item-actions>` are ignored

### Reproduction Link
<a href="https://codepen.io/cawa-93/pen/LwdXgd?editors=1000" target="_blank">https://codepen.io/cawa-93/pen/LwdXgd?editors=1000</a>

### Other comments
I only see this problem when it is listed in the drop-down menu. If it is placed on a page then everything works as expected: https://codepen.io/cawa-93/pen/jgzXBy?editors=1000

**Comment by johnleider** [comment]
This will not be possible as we focus the menu on open to ensure that the keyboard interactions work (as they are coded and no inherit).

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
