### ISSUE TITLE
[Bug Report] Tooltip not working on a <v-select> component

### ISSUE THREAD

**Issue by tomparle** [vuetifyjs/vuetify#8387]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
- add a `<v-select>` with some items
- wrap it in a `<v-tooltip>` component to add a tooltip to it on hover

### Expected Behavior
When hovering the mouse on the `select` component, the tooltip should appear

### Actual Behavior
The tooltip does not appear on hover.
Instead, it appears very briefly then disappears when clicking on the `select` component.
Once an item has been chosen, the tooltip stays visible indefinitely until the user clicks again anywhere.

### Reproduction Link
<a href="https://codepen.io/tomparle/pen/ymKGxp" target="_blank">https://codepen.io/tomparle/pen/ymKGxp</a>

**Comment by jacekkarczmarczyk** [comment]
I'm pretty sure that i've seen this issue somewhere here, can't find it though. Anyway workaround would be to wrap v-select in a div and attach event handlers to the div instead of v-select

**Comment by tomparle** [comment]
Hi @jacekkarczmarczyk ,
I also searched other issues related to tooltips but unfortunately I could not find a similar one.
I tried your workaround and it works, thank you.

**Comment by johnleider** [comment]
After re-reviewing the implications of this change and that there is a valid workaround, I'm going to opt to revert the applied changes.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jatin-maropost** [comment]
> I'm pretty sure that i've seen this issue somewhere here, can't find it though. Anyway workaround would be to wrap v-select in a div and attach event handlers to the div instead of v-select

This works, Thanks a lot.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
