### ISSUE TITLE
[Bug Report] v-color-picker hex doesn't output alpha

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#8390]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Just drag around the alpha slider in the hex mode, you'll see that it wont change the alpha.

### Expected Behavior
hex should contain alpha

### Actual Behavior
no alpha in hex

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/pMVogX" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/pMVogX</a>

**Comment by sh7dm** [comment]
The issue is: hex mode doesn't output alpha, not slider issue. @ricardogobbosouza if i'm wrong, tell me about that.

**Comment by nekosaur** [comment]
That mode `hex` does not contain alpha is correct I would say. However that `hexa` does not  (unless the initial value has it) is a bug though.

**Comment by jacekkarczmarczyk** [comment]
> That mode hex does not contain alpha is correct I would say

So the alpha slider should not be displayed in hex mode

**Comment by nekosaur** [comment]
I had forgotten exactly how color-picker works, but `mode` does not dictate input or output format, but simply which controls the UI will show. It is the structure of the `v-model` that dictates what is put out.

So, currently, if you supply a `hex` color you will always get that back, if you supply `hexa` you'll get that back, etc, for the currently supported input types.

As such, hiding alpha slider should be dependent on what type of input you give it, regardless of which mode you are in.

**Comment by nekosaur** [comment]
Although we are not entirely consistent with how we parse input...
