### ISSUE TITLE
[Feature Request] MaxFiles in VFileInput 

### ISSUE THREAD

**Issue by jbmchd** [vuetifyjs/vuetify#8391]
### Problem to solve
Allows you to limit the amount of files that will be sent.

### Proposed solution
Create a prop that will receive an integer stating the allowed limit.

e.g. https://codepen.io/rikschennink/pen/WXavEx

**Comment by jacekkarczmarczyk** [comment]
That should be validated with `rules` prop as you can't restrict the number of selected files with native input
`wontfix` imho

**Comment by MajesticPotatoe** [comment]
Would have to agree with @jacekkarczmarczyk as we also intended it to be as close to native.
Given it has the ability to validate, it can be something handled via rules. May be something worth considering as a feature to `v-file-upload` with will have a much more robust feature set.
