### ISSUE TITLE
[Bug Report] carousel children has dark theme while dark: false

### ISSUE THREAD

**Issue by Graziel** [vuetifyjs/vuetify#8392]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. set {theme: {dark: false}}
2. use v-carousel

### Expected Behavior
use setting from theme.dark

### Actual Behavior
dark and light prop are null in carousel

### Reproduction Link
<a href="https://codesandbox.io/s/bug-report-g2ukh" target="_blank">https://codesandbox.io/s/bug-report-g2ukh</a>

### Other comments
2 v-card same content just for sanity check

**Comment by rotemrevivo91** [comment]
any update?

**Comment by Graziel** [comment]
for quick fix you can use
```js
<v-carousel
   :dark="$vuetify.theme.dark"
   :light="!$vuetify.theme.dark">
...
</v-carousel>
```

**Comment by MaciejJanyska** [comment]
Any updates guys?

**Comment by GastonDonnet** [comment]
Now is "dark" per default. When you use "light", "hide-delimiter-background" not work

**Comment by sugoidesune** [comment]
This cost me an hour of looking for the error on my side haha

**Comment by therealpaulgg** [comment]
can confirm the bug still exists (defaults to dark mode), using the fix @Graziel put out works perfectly.

**Comment by stefanfr** [comment]
Adding `:light="!$vuetify.theme.dark"` to `v-carousel` seems to "fix" this

**Comment by alexwohlbruck** [comment]
I don't mind adding the `light` property, but at least document this? I've been banging my keyboard for 2 hours trying to solve this until I found this issue.

**Comment by Radiergummi** [comment]
@KaelWD will this be available to V2, or is the fix exclusive to V3?

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v2.5.0-beta.0

**Comment by Tofandel** [comment]
Previous PR was sadly buggy, don't upgrade to 2.5 just yet.

First the theme was not propagating correctly to children (eg: setting `dark` to the `vCarousel` only would not apply to the children vCards, which it should if you follow the logic of all other themeable components

Second, it was throwing an error if put inside a `v-if`

#13669 Will fix both issues
