### ISSUE TITLE
[Bug Report] Outline intersecting label

### ISSUE THREAD

**Issue by nwhessel** [vuetifyjs/vuetify#8393]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 8.1

### Steps to reproduce
Click the append button to see the outline intersect the label

### Expected Behavior
Outline does not intersect label

### Actual Behavior
Outline intersects the label

### Reproduction Link
<a href="https://codepen.io/nwhessel/pen/GVdgWV" target="_blank">https://codepen.io/nwhessel/pen/GVdgWV</a>

**Comment by turdwaster** [comment]
2.0.7 still has the same problem if the text field is hidden in an expansion panel. See updated pen: https://codepen.io/perlinden/pen/yLBOXpm
