### ISSUE TITLE
[Feature Request] Add isMobile to expanded-item slot scope

### ISSUE THREAD

**Issue by yariksav** [vuetifyjs/vuetify#8394]
### Problem to solve
In mobile view of VDataTable **expanded-item** slot continue set colspan to headers length, and no chance to change it
```
      <template v-slot:expanded-item="{ headers, item }">
        <td :colspan="headers.length">
          ...
        </td>
      </template>
```
### Proposed solution
I suppose after adding isMobile into slot scope
https://github.com/vuetifyjs/vuetify/blob/9ff56168dba30db3284e7b1d901c400e1058a13a/packages/vuetify/src/components/VDataTable/VDataTable.ts#L381
we can do like this
```
      <template v-slot:expanded-item="{ headers, item, isMobile }">
        <td :colspan="isMobile ? 1 : headers.length">
          <OrderInfoPanel :value="item" />
        </td>
      </template>
```

**Comment by jacekkarczmarczyk** [comment]
Could be added to other slots as well
