### ISSUE TITLE
[Bug Report] Chrome's input history suggestions shows for input fields with Vuetify v2

### ISSUE THREAD

**Issue by rgb-one** [vuetifyjs/vuetify#8395]
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.5.17
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
1. Choose an item from the `v-autocomplete` dropdown list
2. Click 'Submit'
3. Repeat step 1
4. Observe the browser input suggestion overlaying the autocomplete list

### Expected Behavior
When typing content into a `v-autocomplete` or `v-combobox`, No browser input suggestions should be provided.

### Actual Behavior
When typing content into a `v-autocomplete` and `v-combobox`, the Chrome input history dropdown overlays the results provided by these components. For the v-text-field, it provides suggestions as well but this isn't much of an issue.

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-5b1p7" target="_blank">https://codesandbox.io/s/vue-template-5b1p7</a>

### Other comments
In the reproduction example, if you submit multiple items, only the first one submitted shows up in the browser autocomplete list. In the initially observed scenario however, multiple would show. The more data submitted from that input field, the more browser input suggestions would show.

Also, what has been observed is that these browser suggestions show for `v-text-field`'s as well even if the context is different (i.e. the text field is not related to the data); for example the 'Reproduction Link' in this issue form, it shows some of the suggestions that first showed up in an app I am working on.

Here are some images:
![browser-input-history-dialog-v-combobox](https://user-images.githubusercontent.com/5672238/62804809-f0994680-bab3-11e9-92a3-c6f39cd3ba0d.png)
![browser-input-history-v-autocomplete](https://user-images.githubusercontent.com/5672238/62804810-f131dd00-bab3-11e9-8de8-e6edc403558a.png)

**Comment by myleslee** [comment]
Adding `autocomplete="off"` to  `v-autocomplete` seems to fix the problem.

**Comment by rgb-one** [comment]
@myleslee, indeed. Cool stuff. `autocomplete="off"` by default on `v-autocomplete` and `v-combobox` would be good.

**Comment by simjes** [comment]
I would like to work on this
