### ISSUE TITLE
[Bug Report] Timepicker allows violation of min/max via am/pm buttons

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#8399]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.0

### Steps to reproduce
* create a timepicker with a max of 10:00
* set it to 09:00
* click the pm button

### Expected Behavior
pm button should be disabled and not change the time to 21:00

### Actual Behavior
time changes to 21:00

### Reproduction Link
<a href="https://codepen.io/fontzter/pen/ZgoBOM?&editable=true&editors=101" target="_blank">https://codepen.io/fontzter/pen/ZgoBOM?&editable=true&editors=101</a>

### Other comments
The inverse is also true if you set a min time of say 14:00, pick 15:00 then click am, it allows for 03:00.

**Comment by jacekkarczmarczyk** [comment]
> pm button should be disabled

Not a good idea, imagine you have allowed hours 8-10am and 4-6pm - how do you want to switch from 8am to 4pm i pm button is disabled?

**Comment by fontzter** [comment]
true, in that case. but if the restrictions do not allow for any times in the pm range, disabling the pm button seems like a good way to handle it.

An interesting test case would be an allowed range that crosses am/pm, say 10:00 - 14:00. Currently, if you have 11:00 and click "pm" it will set to 23:00. However, as with your example, the pm button must remain enabled. So, what "should" it go to in this scenario? 12:00 mabye? Or perhaps the max time allowed that is before the current time + 12?

**Comment by jacekkarczmarczyk** [comment]
I think I'd rather allow switching between am/pm but without changing the selected hour, at least when there's no allowed pm hours.

**Comment by fontzter** [comment]
agreed. it seems to happen here: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTimePicker/VTimePicker.ts#L294

where zero is used if there is no first returned. Maybe on the line above: ```if (first === undefined) return this[`input${upperFirst(type)}`]``` (and importing the upperFirst helper)

**Comment by sh7dm** [comment]
we can just move hours/minutes to the closest allowed value when switching.

**Comment by mikemathewson** [comment]
When setting a min value to sometime in the afternoon, the time picker defaults to AM with everything grayed out. I would expect that AM would be disabled and it would be defaulted to PM.
