### ISSUE TITLE
Tabing out of select with autocomplete doesn't focus next form item.

### ISSUE THREAD

**Issue by lgullestrup** [vuetifyjs/vuetify#840]
**Steps to reproduce**
Set up any form with an 'autocomplete' select and attempt to tab past the 'select'

**Versions**
Vuetify 0.12.7

**What is expected ?**
while the select is focus's, tab should go to next field

**What is actually happening ?**
the select field looses focus, but the next field is not highlighted
(i suspect theres a hidden element getting focus? but i am unable to find it.)

**Reproduction Link**
https://codepen.io/anon/pen/awEjeR

**Extra notes:**
The autocomplete feature im working on very similar to the select autocomplete, how ever i have had to implement the menu to override the keycodes mixin. how ever this seems to be

**Comment by johnleider** [comment]
Thank you for the report. This is something that came up during testing for the next release and was fixed last night.

**Comment by lgullestrup** [comment]
awesome! thanks!
