### ISSUE TITLE
[Bug Report] Overlapped events were hidden behind multi-days events in week and day view

### ISSUE THREAD

**Issue by annahanhhoang** [vuetifyjs/vuetify#8400]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
see reproduction link

### Expected Behavior
All events should be visible

### Actual Behavior
The other events were hidden behind the multi-days events

### Reproduction Link
<a href="https://codepen.io/annahoang/pen/zgjBPK?editors=1010" target="_blank">https://codepen.io/annahoang/pen/zgjBPK?editors=1010</a>

**Comment by tryptamine25** [comment]
In some cases, events are completely hidden
https://codepen.io/tryptamine25/pen/QWLvGvY
'event3' in codepen.
