### ISSUE TITLE
[Feature Request] VDataTable: Add per-row classes when using item.<name> slots

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#8401]
### Problem to solve
Currently you can add classes to rows by using the `item` slot and providing the content for your entire row. However, by switching to the default `item` slot you lose a lot of convenience provided by the `item.<name>` slots, like mobile-friendly rows. In my case, I want to add colors to different rows based off different statuses associated with each item.

### Proposed solution
Perhaps the `headers` prop could have something like `rowClassKey` (bad name) which points to a key within each item that has the classes that should be added to its row.

**Comment by jacekkarczmarczyk** [comment]
Maybe `item-class="foo"` and `items: [{..., foo: 'class1'}, {..., foo: 'class2'}]`, default `item-class` value could be just `"class"`

**Comment by itelmenko** [comment]
@jacekkarczmarczyk Look like `item-class` does not work.
I have added `item-class = 'rowclass'` and add for each item `rowclass: 'app-test-row-class'`. But TR tags don't have any class on my datatable.

**Comment by itelmenko** [comment]
Ah Ok. I need update to 2.3.8

https://stackoverflow.com/questions/62969944/vuetify-data-table-item-class-do-nothing

**Comment by jacekkarczmarczyk** [comment]
fixed in https://github.com/vuetifyjs/vuetify/pull/11254
