### ISSUE TITLE
[Bug Report] Integrated VueI18n dosen't render some translations

### ISSUE THREAD

**Issue by fdaugs** [vuetifyjs/vuetify#8402]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** All
**OS:** Windows 10

### Steps to reproduce
1. Integrate VueI18n as described here: 
https://vuetifyjs.com/en/customization/internationalization#create-translation.
2. Create property outside of "$vuetify" in messages-object.

### Expected Behavior
String should be accessible in template by $vuetify.lang.t('PROPERTY_NAME').

### Actual Behavior
The key is rendered instead of the translation. When i use VueI18n directly, everything works fine.

### Reproduction Link
<a href="https://codepen.io/fdaugs/pen/EqLXyK" target="_blank">https://codepen.io/fdaugs/pen/EqLXyK</a>

### Other comments
Mayby I'm doing this the wrong way. Is there any real-world example of using  VueI18n  with vuetify? I also had some trouble with including the premade translations of vuetify.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/lang/index.ts#L58

**Comment by johnleider** [comment]
After discussion we have determined that when using a custom translator that there is no reason to explicitly call `$vuetify.lang.t` and instead (in the case of vue-i18n) simply call `$t`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
