### ISSUE TITLE
[Bug Report] Vertical scrolls appear inconsistently in RTL mode and dialogs

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8405]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Windows 10

### Steps to reproduce
Notice the main app has a vertical scroll on right side. Then open dialog and notice scroll is on left side. 

### Expected Behavior
IN RTL mode, both scrolls should appear on the same side, namely the left side in RTL mode.

### Actual Behavior
main app scroll is on right, dialog scroll is on left.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/YmLevG?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/YmLevG?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
This is a known bug in webkit. https://lists.webkit.org/pipermail/webkit-unassigned/2011-April/314538.html

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Duplicate of #7146
