### ISSUE TITLE
How to set DataTable Header  display with class ''text-xs-center"

### ISSUE THREAD

**Issue by zhangzhenfei** [vuetifyjs/vuetify#841]
"vue": "^2.3.3",
"vuetify": "^0.12.7"

Hi, I want to set the datatable header Text text-align center ,but i try set the datatable's headers item  option center: true, it don't work, Is there any other way to change it?

**Comment by johnleider** [comment]
This has been updated for next release. You will use the prop **align** in your header data and you can specify left/center/right.

**Comment by Christilut** [comment]
@johnleider just a heads up, I don't see this in the [v-datatable docs](https://vuetifyjs.com/components/data-tables)

Actually on second look, I don't see any of the available props in header data there

**Comment by johnleider** [comment]
Because this is an out dated ticket. It has since changed again.
