### ISSUE TITLE
[Bug Report] V-select chips error while Server side rendering (Nuxt)

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#8417]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
If you have chips attribute on with a v-select, then you set the v-model in created, you will get this `Focus is not defined` error

### Expected Behavior
Should just work

### Actual Behavior
```
 ERROR  [Vue warn]: Error in render: "ReferenceError: focus is not defined"

found in

---> <VSelect>
       <VApp>
         <Pages/index.vue> at pages/index.vue
           <Nuxt>
             <Layouts/default.vue> at layouts/default.vue
               <Root>
```

### Reproduction Link
<a href="https://codesandbox.io/s/nuxt-vuetify-wnru5?fontsize=14" target="_blank">https://codesandbox.io/s/nuxt-vuetify-wnru5?fontsize=14</a>

### Other comments
It will work if you either remove the chips attribute, or comment out setting the v-model in created.

**Comment by erickarbe** [comment]
Getting the exact same issue, just FYI.

**Comment by praburangki** [comment]
One workaround is to fill in the values of the `v-model` on `mounted`.

**Comment by amritk** [comment]
I just removed the chips attribute for now

**Comment by just10minutes** [comment]
Same here removing the chips attribute worked, but wanted chips feature :(

**Comment by robodude666** [comment]
@praburangki Could you please provide an example? Thanks!

**Comment by kobayashi5884** [comment]
I had the same issue with v-combobox and the simplest workaround seems to be wrapping <v-select> by <no-ssr> though I am waiting for the complete fix.
