### ISSUE TITLE
How to set DataTable Header background color

### ISSUE THREAD

**Issue by aldozumaran** [vuetifyjs/vuetify#843]
Hi, I want to set the datatable header background color, i try to do that, but it not works
is it possible to add classes to table element "stripped highlight" ?

```
<template slot="headers" scope="props" light class="indigo">
       <span v-tooltip:bottom="{ 'html': props.item.text }">
               {{ props.item.text }}
       </span>
</template>
```

**Comment by johnleider** [comment]
Please direct all questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
