### ISSUE TITLE
[Bug Report] v-date-picker event for prev/next month

### ISSUE THREAD

**Issue by slimee** [vuetifyjs/vuetify#8430]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
use a v-date-picker
can't find an event for triggering month next/prev button click.

### Expected Behavior
emit an event when month change with prev/next button

### Actual Behavior
no events

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/KQrPKJ" target="_blank">https://codepen.io/johnjleider/pen/KQrPKJ</a>

**Comment by jacekkarczmarczyk** [comment]
Your reproduction shows nothing but errors in console, please fix it first and remove all unnecessary code

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
