### ISSUE TITLE
[Documentation] Data Table slots - item.data-table-select does not work

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#8432]
### Environment

**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.5

### Steps to reproduce
Choose `item.data-table-select` from slot select

### Expected Behavior
Checkboxes work and are selected / de-selected

### Actual Behavior
Checkboxes don't work

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#slots" target="_blank">https://vuetifyjs.com/en/components/data-tables#slots</a>

### Other comments
I'm trying to migrate from `https://v15.vuetifyjs.com/en/components/data-tables#slot-items-and-headers` for using checkboxes and bind their v-model to the data-table v-model. The current documentation doesn't make it clear on how this is done in 2.0. Previously, you used `v-slot:items="props` and then `:input-value="props.selected"` for the checkbox, whereas now if I need to edit the template for a 2.0 data table to accommodate a checkbox and bind its functionality to the data table v-model, I have no idea how it works.

**Comment by nekosaur** [comment]
Fixed in edd367412

**Comment by Paulsky** [comment]
Thanks for fixing this. But is there any documentation/example available of what is described in 'other comments' and how to migrate?

v1.5:
```
<template v-slot:item="props">
    <tr>
        <td>
            <v-checkbox v-model="props.selected"></v-checkbox>
        </td>
        <td>Custom property getter code</td>
    </tr>
</template>
```

v2.x:
`??`

**Comment by nekosaur** [comment]
The diff of the commit I linked to shows the markup

```vue
<template v-slot:item.data-table-select="{ isSelected, select }">
  <v-simple-checkbox :value="isSelected" @input="select($event)"></v-simple-checkbox>
</template>
```

**Comment by thomasswilliams** [comment]
As at 2.0.11 I found I had to use the "change" (not "input") event e.g. 
`<v-checkbox hide-details :value="isSelected" @change="select($event)" />`

**Comment by nekosaur** [comment]
for `v-checkbox`, it's `input-value` and `change`
for `v-simple-checkbox`, it's `value` and `@input`

**Comment by cby016** [comment]
I finally got this to work with the item slot using this markup:

```
<template v-slot:item="props">
  <tr>
    <td><v-checkbox :input-value="props.isSelected" @change="props.select($event)"></v-checkbox></td>
    <td>{{ props.item.name }}</td>
    ...
  </tr>
</template>
```

**Comment by kunalahirrao** [comment]
How to pass the desired value using item.data-table-select ?? I want to pass item.mobileNo if someone ticks the checkbox. Codepen for the same: https://codepen.io/spider007/pen/ZEbYxrd

**Comment by GabrielHangor** [comment]
Hey guys..What about using radio-buttons in the `item.data-table-select` slot. 

```
    <template #item.data-table-select="{ isSelected, select, on, attrs }">
          <v-radio color="primary" v-bind="attrs" v-on="on" :value="isSelected" @change="select" />
        </template>
```

This one is correctly selecting data but radio buttons are not getting selected, seems taht i am doing smth wrong..

**Comment by RafalOddslife** [comment]
hey @GabrielHangor 
if you really need the appearance of a radio but the behaviour of a checkbox try this:

```html
<template v-slot:item.data-table-select="{ isSelected, select }">
    <v-simple-checkbox off-icon="mdi-radiobox-blank" on-icon="mdi-radiobox-marked" :value="isSelected" @input="select($event)"></v-simple-checkbox>
</template>
``` 

however this may not be the best solution in terms of ux because user shouldn't be able to deselect radio button by design

**Comment by GabrielHangor** [comment]
@RafalOddslife Hey, i've done smth similar to this approach, works nice for me...

**Comment by kroawen** [comment]
In Version 3.9. I use this:
`<template v-slot:header.data-table-select="{ selectAll }">
                <v-checkbox v-model="allSelected" @update:model-value="selectAll($event)"></v-checkbox>
            </template>


            <template v-slot:item="{ item, toggleSelect, internalItem, isSelected }">
                <tr>
                    <td><v-checkbox :model-value="selectedItems.includes(item.id)"
                            @change="toggleSelect(internalItem)"></v-checkbox>

                    </td>
                    <td v-for="header in tableHeaders" :key="header.value">
                        {{ item[header.value] }}
                    </td>
                </tr>
            </template>`

**Comment by kroawen** [comment]
<template v-slot:header.data-table-select="{ selectAll }">
                <v-checkbox v-model="allSelected" @update:model-value="selectAll($event)"></v-checkbox>
            </template>


            <template v-slot:item="{ item, toggleSelect, internalItem, isSelected }">
                <tr>
                    <td><v-checkbox :model-value="selectedItems.includes(item.id)"
                            @change="toggleSelect(internalItem)"></v-checkbox>

                    </td>
                    <td v-for="header in tableHeaders" :key="header.value">
                        {{ item[header.value] }}
                    </td>
                </tr>
            </template>
