### ISSUE TITLE
[Bug Report] VDataTable shows sort selection in mobile view when disable-sort is true

### ISSUE THREAD

**Issue by yariksav** [vuetifyjs/vuetify#8434]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.0

### Steps to reproduce
Put disable-sort into VDataTable and switch to mobile view

### Expected Behavior
Must not render sort select on mobile view at:
https://github.com/vuetifyjs/vuetify/blob/6de09720c91f283b994fc331d9a02c5063876b4b/packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts#L84

### Actual Behavior
VDataTable with property **disable-sort** generates sort selection in mobile view

### Reproduction Link
<a href="https://codepen.io/yariksav/pen/zgJyrG" target="_blank">https://codepen.io/yariksav/pen/zgJyrG</a>

**Comment by jacekkarczmarczyk** [comment]
I'd say it's intended. To disable means to disable, not to hide, if you want to hide there's `hide-default-header` for this.
You may want to disable sort when for example you're loading data and you don't want the layout to jump.

**Comment by yariksav** [comment]
Understand, but property **hide-default-header** hides header at all, even in not mobile view. In desktop  mode header is necessary.

**Comment by jacekkarczmarczyk** [comment]
You can hide them only for mobile, just bind a boolean. I wonder if it could accept other values than bools, for example `hide-default-header="mobile"`. Otherwise you need to apply the condition so either you need to know when the table switches to mobile by default or you need to duplicate the value of `mobile-breakpoint` prop.
@nekosaur thoughts?

**Comment by nekosaur** [comment]
hmm. well any changes to how hide-default-header or disable-sort works would be a (potentially) breaking feature request. for now I'd say this is working as intended?

**Comment by johnleider** [comment]
This is working as intended.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by WangHaoming** [comment]
> I'd say it's intended. To disable means to disable, not to hide, if you want to hide there's `hide-default-header` for this.
> You may want to disable sort when for example you're loading data and you don't want the layout to jump.

Sorry,  I think to disable sort and display the sort menu on mobile which makes no sense
