### ISSUE TITLE
[Bug Report] Vuetify v-btn component stays in active state after click

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#8436]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
After button is clicked it stays in "active" state (eg. focus is retained) and thus background is not returned to normal color. This is especially visible on flat buttons. Just click any button and see what I mean: https://vuetifyjs.com/en/components/buttons#flat

Is this desired behavior (a feature) or a bug? This was not present in earlier versions of Vuetify 1.x (button background color was returned to default after click).

### Expected Behavior
Button returned to default state after click.

### Actual Behavior
Button stays in active state after click.

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/pMOGdR?&editable=true&editors=101" target="_blank">https://codepen.io/milost1982/pen/pMOGdR?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
This is intended as it is how it works in MD2 spec which is the basis of vuetify 2.0 <https://material.io/design/components/buttons.html>

**Comment by ljmatkins** [comment]
I also am looking for a way around this, even if it is technically part of the MD2 spec.

To a user, it looks like they click the button and then it gets into some sort of stuck down state, almost like a half toggle. It makes it seem like something has broken. The first time I clicked one, I immediately checked the Javascript console for errors.

It'd be great if v-btn offered some way to disable this behavior. Failing that, does anyone have any workarounds?

**Comment by milost1982** [comment]
Exactly my thoughts.
