### ISSUE TITLE
Bug: When ever i append a select to my project i get a warning

### ISSUE THREAD

**Issue by Geekonometry** [vuetifyjs/vuetify#844]
I seriously dont know how to solve this issue 

[Vue warn]: Error in nextTick: "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'."

found in

---> <Menu>
       <App> at /vue/src/App.vue
         <Root>
warn @ vue.esm.js?65d7:434
vue.esm.js?65d7:523 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at VueComponent.eval (eval at <anonymous> (app.js:1276), <anonymous>:3228:32)
    at Array.eval (eval at <anonymous> (app.js:723), <anonymous>:656:14)
    at nextTickHandler (eval at <anonymous> (app.js:723), <anonymous>:603:16)
    at <anonymous>
handleError @ vue.esm.js?65d7:523

### Steps to reproduce

included the following 

```
<v-layout row justify-center>
      <v-dialog v-model="dialog" :width="600">
        <v-btn primary light slot="activator" v-show="false">Open Dialog</v-btn>
        <v-card>
          <v-card-row>
            <v-card-title>Add new brand</v-card-title>
          </v-card-row>
          <v-card-row height="160px">
            <v-card-text>
              <v-flex xs6>
                <v-text-field v-model="currentBrand.name" label="Brand Name"></v-text-field>
              </v-flex>
              <v-flex xs6>
                <v-select v-bind:items="parentBrandArr" v-model="currentBrand.parent_id" label="Brand Parent"></v-select>
              </v-flex>
            </v-card-text>
          </v-card-row>
          <v-card-row actions>
            <v-btn class="blue--text darken-1" flat @click.native="resetForm()" :disabled="dialogLoading">Close</v-btn>
            <v-btn class="blue--text darken-1" flat @click.native="saveBrand()" :loading="dialogLoading" :disabled="dialogLoading">
              Save
              <span slot="loader" class="custom-loader">
                <v-icon class="blue--text darken-4">cached</v-icon>
              </span>
            </v-btn>
          </v-card-row>
        </v-card>
      </v-dialog>
    </v-layout>
```

if i remove the select components then the warning dissapears

### Versions

All Versions

### What is expected ?

Just no warnings in the console

### What is actually happening ?

getting a warning for every select i include

**Comment by johnleider** [comment]
There is issue boilerplate for a reason. I cannot help you with the code provided. Not only is it not in a codepen or fiddle, it doesn't have all of the methods/data. 

Producing this on an external site helps me solve your issue. It also confirms that it's not something related to your local dev. 

Please update this.

**Comment by Geekonometry** [comment]
Give me a sec to get it in codepen with data and all

**Comment by Geekonometry** [comment]
Strange that its not doing it in codepen. 

Heres the pen for interest sake https://codepen.io/anon/pen/LLQPwO

It must be something on my local. Apologies
