### ISSUE TITLE
v-tabs: cannot change transition behaviour

### ISSUE THREAD

**Issue by awhitneye** [vuetifyjs/vuetify#8441]
I've been attempting to override the transition behaviour of v-tabs without much success.  

`.v-window-item {
		transition-duration: 1000ms !important;
		transition-delay: 250ms !important;
	}`
is not ideal, nor does it work *consistently*.  It seems that the behaviour of tabs will only allow this to override when "stepping down" through the tabs (indeces x -> 0), but not in reverse (indeces 0 -> x).

Request that transition details be adjustable, perhaps :transition-duration and :transition-delay and such be exposed for the user to adjust as desired.  Because it seems as though there are things going on under the hood that I am unable to override or workaround, and it would be lovely to have the option to adjust these.  

I need to provide a short delay for users, in order to provide my users with a particular experience - being able to augment delay and duration, at the very least, would be helpful (and probably to more than just me).

Any help/clarification is appreciated.

**Comment by awhitneye** [comment]
I thought I did that... ^

**Comment by astroxvimy** [comment]
Could you share me your practise?
