### ISSUE TITLE
[Feature Request] v-tabs:  unable to adjust transition-delay or transition-duration consistently.

### ISSUE THREAD

**Issue by awhitneye** [vuetifyjs/vuetify#8442]
### Problem to solve
I've been attempting to override the transition behaviour of v-tabs without much success.

.v-window-item { transition-duration: 1000ms !important; transition-delay: 250ms !important; }
is not ideal, nor does it work consistently. It seems that the behaviour of tabs will only allow this to override when "stepping down" through the tabs (indeces x -> 0), but not in reverse (indeces 0 -> x).

I need to provide a short delay for users, in order to provide my users with a particular experience - being able to augment delay and duration, at the very least, would be helpful (and probably to more than just me).  It seems as though there are things going on under the hood that I am unable to override or workaround, and it would be lovely to have the option to adjust these.

### Proposed solution

Request that transition details be adjustable, perhaps :transition-duration and :transition-delay and such be exposed for the user to adjust as desired.

**Comment by johnleider** [comment]
Can you provide me with an example of what you are trying to do?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
