### ISSUE TITLE
Add possibility to disable a tooltip

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#845]
I think we could add a option to disable a tooltip, maybe like the new object property `visible` of the badge directive.

Right now, the workaround is to add a v-if and duplicate the element, one has the tooltip and the other one doesn't.

**Comment by nekosaur** [comment]
This has been added to next release

**Comment by jvbianchi** [comment]
@johnleider told me on gitter that it wasn't. I was added only for badge not for tooltip

**Comment by nekosaur** [comment]
You're right. I confused them
