### ISSUE TITLE
[Feature Request] Combining v-progress-linear into v-snackbar for timeouts

### ISSUE THREAD

**Issue by mrgr4v1ty** [vuetifyjs/vuetify#8451]
### Problem to solve
I want to show a backward progress bar in the v-snackbar (at the bottom for example) to show the timeout amount that remains until the v-snackbar disappears automatically.

### Proposed solution
Combining v-progress-linear and v-snackbar

**Comment by johnleider** [comment]
This could be handy for carousel as well.

**Comment by Stoom** [comment]
You can do this manually with the absolute placement, but it looks like the progress bar goes the entire length of the screen.
