### ISSUE TITLE
[Bug Report] v-carousel-item circular progress when there is an image

### ISSUE THREAD

**Issue by abdumuslim** [vuetifyjs/vuetify#8452]
### Problem to solve
It will display a circular progress while the carousel's image is loading.

### Proposed solution
making a default activated prop doing that.
I tried to use the same as used in img but it didn't worked as the below example:
https://codepen.io/abdumuslim/pen/Zgqpyz

**Comment by johnleider** [comment]
This is actually a bug since the placeholder slot should be available for all v-img extensions.
