### ISSUE TITLE
[Bug Report] v-menu position is glitched when trying to open animation before close animation completes

### ISSUE THREAD

**Issue by dingming1994** [vuetifyjs/vuetify#8454]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OS 10.13.6

### Steps to reproduce
In the link, first click button to open menu, then try to double click the button ( first click closed the menu with animation, and second click re-open the animation). if the double click is fast enough, the newly opened menu is in the wrong position. 

### Expected Behavior
The menu should be always on the top of the button

### Actual Behavior
if click fast, it wrongly goes below the button. 

### Reproduction Link
<a href="https://codepen.io/dingming/pen/oKaByg" target="_blank">https://codepen.io/dingming/pen/oKaByg</a>

### Other comments
I think this is due to the calculation if the position and it has some error in animation. Please Kindly advice. thanks

**Comment by dingming1994** [comment]
Hi. Just a follow up, is there any update on this ? 

Thanks!

**Comment by johnleider** [comment]
This is being caused by the scale transform. I tested this with other's such as fade/slide-x etc and none of them exhibited this behavior. No idea how to resolve it.
