### ISSUE TITLE
[Bug Report] VTabs adds v-tabs-bar--is-mobile too early

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#8456]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
resize your screen with inspect to under 1580px width. 

### Expected Behavior
No margin should be added to VTabs and v-tabs-bar--is-mobile class should not be added

### Actual Behavior
a margin left will appear due to .v-tabs-bar--is-mobile class added

### Reproduction Link
<a href="https://codepen.io/gadelkareem/pen/EqdWYY" target="_blank">https://codepen.io/gadelkareem/pen/EqdWYY</a>

**Comment by KyleRicardo** [comment]
+1
I was just about to report this bug, and I found this issue.
Looking forward to the fix.

ScreenShot:
![image](https://user-images.githubusercontent.com/10452272/62823700-5d046a80-bbc6-11e9-9715-90e492b0922d.png)

**Comment by KyleRicardo** [comment]
+1
I was just about to report this bug, and I found this issue.
Looking forward to the fix.

ScreenShot:
![image](https://user-images.githubusercontent.com/10452272/62823726-a359c980-bbc6-11e9-8d38-530ac807b6be.png)

**Comment by jacekkarczmarczyk** [comment]
@gadelkareem tabs switch to mobile by default on 1264px and it's intended, you can controll it using `mobile-break-point` prop
Margin issue is already reported here <https://github.com/vuetifyjs/vuetify/issues/8294>

**Comment by gadelkareem** [comment]
But it switches at 1580px

**Comment by jacekkarczmarczyk** [comment]
Not for me, screenshot shows width below 1300 and tabs are not mobile

![image](https://user-images.githubusercontent.com/15625235/62824448-3cc0b580-bb9e-11e9-93ca-0c16ff3aeffb.png)

Maybe 1580px is the width of the iframe with codepen panels?

**Comment by gadelkareem** [comment]
I tried without Codepen and it still breaks at 1580 maybe something with my chrome then.

**Comment by jacekkarczmarczyk** [comment]
Probably, checked without codepen too to be sure, toggles at 1264px

**Comment by viestursv** [comment]
A quick workaround is adding a class to the first child since "v-tabs-bar--ismobile" messes with margins. This works if you need tabs to remain centered.

#tab-parent {
  a:first-of-type {
    margin-left: auto;
  }
}
