### ISSUE TITLE
[Bug Report] Multiple v-dialog with v-btn cause infinite recursion errors

### ISSUE THREAD

**Issue by mitsakosgr** [vuetifyjs/vuetify#8459]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Create a simple app with two persistent dialogs with a button inside each (buttons trigger the error).
Clicking the button (or focusing the dialog - for example a v-card) will cause an infinite loop of focusing.
Pressing Shift+Tab will cause this error to repeat.

Chrome will have an error:
    Uncaught RangeError: Maximum call stack size exceeded.
    at VueComponent.onFocusin (VDialog.ts:225)

Firefox will complain about too much memory usage and after a while will say about too much recursion.

### Expected Behavior
No error

### Actual Behavior
Uncaught RangeError: Maximum call stack size exceeded.
at VueComponent.onFocusin (VDialog.ts:225)

### Reproduction Link
<a href="https://codepen.io/mitsakosgr/pen/MNPoKQ" target="_blank">https://codepen.io/mitsakosgr/pen/MNPoKQ</a>

### Other comments
Setting retain-focus to false will prevent this error.

**Comment by MuizU** [comment]
I am encountering this exact issue when I remove `<v-btn>` s it goes away

**Comment by MuizU** [comment]
I solved it by replacing `v-model` with `:value`.

**Comment by KaelWD** [comment]
> setting retain-focus didn't do any good

`:retain-focus="false"` does

I'm reverting this because it has an easy workaround and broke the original behaviour.

**Comment by turbobuilt** [comment]
Same issue in v3 alpha.  doing `<v-dialog :retain-focus="false"` on both seemed to work. Thanks @mitsakosgr for the solution.
