### ISSUE TITLE
[Feature Request] v-navigation-drawer not respecting RTL

### ISSUE THREAD

**Issue by abdumuslim** [vuetifyjs/vuetify#8461]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Using v-navigation-drawer while rtl is true

### Expected Behavior
drawer in the right side

### Actual Behavior
drawer in the left side

### Reproduction Link
<a href="https://codepen.io/abdumuslim/pen/aeRWMK" target="_blank">https://codepen.io/abdumuslim/pen/aeRWMK</a>

**Comment by melbahja** [comment]
@abdumuslim @jacekkarczmarczyk  I fixed this issues locally after testing i will open a PR

**Comment by melbahja** [comment]
@abdumuslim to fix the issue you need to add just a ```:right="$vuetify.rtl"```
example:
https://codepen.io/dev0x0/pen/RwbaeXK

**Comment by johnleider** [comment]
This is not considered a bug at the moment. Moving to a feature request.

**Comment by johnleider** [comment]
Blocked by https://github.com/vuetifyjs/vuetify/pull/9800

**Comment by johnleider** [comment]
This slipped v2.2, moving to v2.3.

**Comment by redbayoub** [comment]
i made it work through  setting drawer right property  to true
https://vuetifyjs.com/en/components/navigation-drawers/

**Comment by KaelWD** [comment]
Fixed but not fully correct, follow #15364
