### ISSUE TITLE
[Bug Report] The v-app bar component's collapse property will have animation with absolute prop

### ISSUE THREAD

**Issue by beedrill** [vuetifyjs/vuetify#8462]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Please see the two code pen, the first has collapse animation, the second doesn't, the only difference is changing the absolute to fixed:
https://codepen.io/beedrill/pen/JgmyEX
https://codepen.io/beedrill/pen/mNzMRB

### Expected Behavior
The animation should always be there with absolute or fixed prop

### Actual Behavior
the animation only happens when it's absolute, not for fixed

### Reproduction Link
<a href="https://codepen.io/beedrill/pen/JgmyEX" target="_blank">https://codepen.io/beedrill/pen/JgmyEX</a>

**Comment by johnleider** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.8
