### ISSUE TITLE
[Bug Report] weekdays of v-calendar seems does not apply in some cases

### ISSUE THREAD

**Issue by ony3000** [vuetifyjs/vuetify#8467]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
- Set the "weekdays" property to exclude one or more days of the week.
- Set the "start" property to the date of the excluded days of the week.

### Expected Behavior
I want to see only the days of the week set by the "weekdays" property.

### Actual Behavior
Weeks before and after the start date are displayed.

### Reproduction Link
<a href="https://codesandbox.io/s/v-calendar-in-vuetify-15-9zvuy" target="_blank">https://codesandbox.io/s/v-calendar-in-vuetify-15-9zvuy</a>

### Other comments
I also checked that it reproduces in the latest version at https://codesandbox.io/s/v-calendar-in-vuetify-20-v3dpp

**Comment by Oleksii14** [comment]
Any updates here? It is very annoying

**Comment by 4mbk0r** [comment]
you use 1,2,3,4,5 and not [1,2,3,4,5]
