### ISSUE TITLE
[Documentation] Bottom sheet component -> playground

### ISSUE THREAD

**Issue by NurimOnsemiro** [vuetifyjs/vuetify#8468]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1. Click 'open playground'
2. Click 'close'
3. Switch on 'hide overlay'
4. Switch off 'hide overlay'

### Expected Behavior
overlay will be disappear

### Actual Behavior
overlay is not disappear

### Reproduction Link
<a href="https://vuetifyjs.com/ko/components/bottom-sheets" target="_blank">https://vuetifyjs.com/ko/components/bottom-sheets</a>

**Comment by MajesticPotatoe** [comment]
duplicate #8142
