### ISSUE TITLE
[Bug Report] Checkbox within a data table does not respect alignment

### ISSUE THREAD

**Issue by nmummau** [vuetifyjs/vuetify#8469]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-data-table` with an array of objects that has a boolean data point within the object.
In the headers specify that this column should be right aligned.
Create a slotted template for that boolean value and add a `v-checkbox`.
View the data table and observe the boolean column does show up as a checkbox but it is left aligned (Is Very Good column in reproduction link)

The workaround that I've found is to add the `v-checkbox` inside a `v-layout` with `justify-end` (Is Low Calorie column in reproduction.

### Expected Behavior
A template `v-checkbox` respects the alignment specified in the headers.

### Actual Behavior
A template `v-checkbox` is always left aligned by default.

### Reproduction Link
<a href="https://codepen.io/nmummau/pen/ZgqVXg?&editable=true&editors=101" target="_blank">https://codepen.io/nmummau/pen/ZgqVXg?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
This has not been documented yet, but `v-data-table` actually uses a component called `v-simple-checkbox` which will solve this for you. 

https://codepen.io/nekosaur/pen/OKGKYM?editors=1010

**Comment by nmummau** [comment]
Thank you @nekosaur . 
I have to ask, are there other undocumented components for the `v-data-table`? And if so, is there an easy way to preview them before they are documented?

**Comment by nekosaur** [comment]
data-table has a number of internal components, most of which should probably not be used or are not usable when consuming vuetify. if you are interested in which those are, you can check the source code.

**Comment by nekosaur** [comment]
We need to document v-simple-checkbox API, and inform users that it should be used in place of v-checkbox in v-data-table.
