### ISSUE TITLE
[Feature Request] ability to modify VDataTable cell's properties without using `item` slot

### ISSUE THREAD

**Issue by cluidold** [vuetifyjs/vuetify#8474]
### Problem to solve
When i create a datatable, i pass a headers and a item array to it.
If i want to add a style to a specific column (eg. color, font-size, alignment, disable sorting...) i have to use the template "<template v-slot:item.COLUMNNAME>...</template>". If i add a style in e extra <div> the style works, but the elements in the resulting table were nested like following.

< td>
   < div style:"color=red">Text< /div>
< /td>

instead of 

< td  style:"color=red">
   Text
< /td>

### Proposed solution
Add a property for passing the styles directly via the slot to prevent nesting of resulting elements.

**Comment by makana** [comment]
IMO the headers config object needs a 'itemClass: string | string[]' config or just pass the current "class" config to the td elements and not just the headers. Also adding an additional class using the "value" option makes sense, i.e. th.header-<value> and td.item-<value>. So it would be easy to style the cells for a specific column. Currently it is uncomfortable because you either have to override the complete item slot to customize or use something like td:nth-child(2) to get cell elements.

**Comment by MoritzMix** [comment]
+1 for this feature.
In my case i simply want to print a table and hide cells that contain control elements.
For now i have to do css workarounds as mentioned,

**Comment by varadekd** [comment]
Any update on this?? Also can someone tell me to specify table row width using percentage

**Comment by ktiedt** [comment]
> Any update on this?? Also can someone tell me to specify table row width using percentage

A row is as wide as the table....  do you mean columns? Those are controlled by percentage or width using the header array and the `width` property.

**Comment by stevelacey** [comment]
BootstrapVue does a great job with this, it'd be great to have it work similar here

**Comment by nekosaur** [comment]
@stevelacey In BootstrapVue, is this `_cellVariants` you're talking about?

**Comment by stevelacey** [comment]
@nekosaur yes, anything that works like that, i.e. allowing the developer to pass the data along with their item objects would be :ok_hand: :ok_hand: it was very easy to grasp and implement solutions with

**Comment by peteruithoven** [comment]
@ktiedt while usually using the headers to control the width is a good idea, you don't always want headers. (There even is a `hide-default-header` option.)

I love the cellClass idea.

**Comment by ktiedt** [comment]
> @ktiedt while usually using the headers to control the width is a good idea, you don't always want headers. (There even is a `hide-default-header` option.)
> 
> I love the cellClass idea. 

I know, which is actually how I came to this ticket, removing the header broke our column sizing 🤦🏼‍♂️ we had to resort to manually hiding the headers with css instead along with some other dirty hacks for specific column decorating 🙁

**Comment by peteruithoven** [comment]
Could be as simple as adding something like
``` js
[header.cellClass]: header.cellClass,
```
to: 
https://github.com/vuetifyjs/vuetify/blob/a406dd4476eaf864d15fdc478093edf7b3964f90/packages/vuetify/src/components/VDataTable/Row.ts#L42

I'll try doing a pull request.

**Comment by ibrahimBeladi** [comment]
Any updates on this issue?

**Comment by asterd** [comment]
No one? there can be a good improvement with minimum impact.. please take a look!

**Comment by KaelWD** [comment]
If the problem is just the nesting, we could do something similar to VSelectList:
https://github.com/vuetifyjs/vuetify/blob/ed76169e26795f9fd386d3b371af3c47ad70fb35/packages/vuetify/src/components/VSelect/VSelectList.ts#L215-L219

If the root element of the slot is `tr`, `th`, or `td` then just render it as-is.

**Comment by johnleider** [comment]
> If the root element of the slot is `tr`, `th`, or `td` then just render it as-is instead of putting it in a `td`.

I think that this is the best way forward. We don't want to add endless props covering every use case when we expect the user to be able to customize.

**Comment by KaelWD** [comment]
It wouldn't be a prop, you just look at what's rendered in the slot

**Comment by KaelWD** [comment]
I can't read ok

![Screenshot_2021-06-05-12-28-40-741_com android chrome](https://user-images.githubusercontent.com/16421948/120877444-eab21500-c5f9-11eb-90ad-d4be291302ff.png)

**Comment by wesley3295** [comment]
> > @ktiedt while usually using the headers to control the width is a good idea, you don't always want headers. (There even is a `hide-default-header` option.)
> > I love the cellClass idea.
> 
> I know, which is actually how I came to this ticket, removing the header broke our column sizing 🤦🏼‍♂️ we had to resort to manually hiding the headers with css instead along with some other dirty hacks for specific column decorating 🙁

Any Idea how to control the width of the table data with the hide-default-header prop set to true?
