### ISSUE TITLE
Contextualable Mixin: Accent color option

### ISSUE THREAD

**Issue by JonasDoebertin** [vuetifyjs/vuetify#848]
Is there a specific reason why "contextualable components" don't implement an `accent` option?

Just earlier today I happened to be in a situation where I needed a linear progress component in the themes accent color.

If it is for the sole reason that nobody implemented it yet, I would maybe try to start a PR adding this tomorrow.

**Comment by johnleider** [comment]
This is being changed partially for next release, and fully implementing for 0.14.
