### ISSUE TITLE
[Feature Request] Add prop to change "of" text in v-data-footer within v-data-table

### ISSUE THREAD

**Issue by konstantinsteinmiller** [vuetifyjs/vuetify#8480]
### Problem to solve
You can provide a translated text string to the "of" label

### Proposed solution
create a prop like its done for itemsPerPageText

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8110

**Comment by konstantinsteinmiller** [comment]
Can we still get the prop for the "of" text? its not really suitable for our project to enforce the user to provide a language file for his app.

**Comment by jeyhunhasanov** [comment]
```
footer-props="{
    'items-per-page-text': 'Rows per page:',
    'items-per-page-options': [50, 100, 150, 200, -1],
    'items-per-page-all-text': 'All',
    'page-text': '{0}-{1} of {2}'
}"
```

**Comment by Norge0529** [comment]
> footer-props="{
>     'items-per-page-text': 'Rows per page:',
>     'items-per-page-options': [50, 100, 150, 200, -1],
>     'items-per-page-all-text': 'All',
>     'page-text': '{0}-{1} of {2}'
> }"

In page-text how can you add comma if there is a thousand of records?
