### ISSUE TITLE
[Bug Report] Using transition hooks causes error on v-stepper

### ISSUE THREAD

**Issue by nmagee-akiri** [vuetifyjs/vuetify#8482]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
attempting to use the `after-enter` hook on `v-stepper-content` throws error on `leave`. Simply transition to the second step and then transition back to see the error

### Expected Behavior
should be able to transition back without issues

### Actual Behavior
transitioning back throws the following error:
```
"[Vue warn]: Error in directive show update hook: 'TypeError: leave is not a function'

found in

---> <VStepperContent>
       <VStepper>
         <VApp>
           <Root>"

[object Error] {}
```

### Reproduction Link
<a href="https://codepen.io/nmagee12/pen/NQZKEa" target="_blank">https://codepen.io/nmagee12/pen/NQZKEa</a>

**Comment by YuWaiLinn** [comment]
It also causes in my environment.

**Comment by johnleider** [comment]
Resolved as of latest version.

References:

https://github.com/vuetifyjs/vuetify/commit/ad1f6ce8cf5261b60665222b2854615bcef7c2f3
https://github.com/vuetifyjs/vuetify/commit/18439d6e370cf35b7c29d274f093a4674d244bca

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
