### ISSUE TITLE
Cannot import and use vuetify components for unit testing with jest

### ISSUE THREAD

**Issue by sametsafak** [vuetifyjs/vuetify#8483]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.15.0

### Steps to reproduce
yarn install
yarn test:unit

to serve

vue serve src/dev.vue

### Expected Behavior
Working smoothly with single file component structure from vue

### Actual Behavior
Syntax Error

### Reproduction Link
<a href="https://github.com/sametsafak/sfc-jest" target="_blank">https://github.com/sametsafak/sfc-jest</a>

### Other comments
I am trying to create a single file component and write unit tests with jest. Project works with vue's instant prototyping method.

Normally project and tests are working smoothly but not with vuetify.

When I try to import vuetify components, jest gives me SyntaxError: Unexpected identifier error on importing vuetify components line (src/components/FcTable.vue:41:1). I checked my environment to make sure if it's an es6 import issue but it's not. I can import and use another script files.

**Comment by johnleider** [comment]
There is an ongoing issue with https://github.com/vuejs/vue-cli/issues/1584 . Not sure if something pops out at @KaelWD .

**Comment by KaelWD** [comment]
I have this in a project at work:
```js
transformIgnorePatterns: ['node_modules/(?!vue-router|@babel|vuetify)']
```

**Comment by morficus** [comment]
Adding that `transformIgnorePatterns` property to my Jest config did the trick
Thank you, @KaelWD 🙏

**Comment by morphatic** [comment]
@KaelWD solution works for me. Here is another alternative that I found to be faster to run:

```js
// jest.config.js
module.exports = {
  // ... other config ...
  moduleNameMapper: {
    // ... other mapped names ...
    'vuetify/lib': '<rootDir>/node_modules/vuetify/es5',
  }
}
```

The reason this works is because Vuetify ships with a pre-compiled ES5 version, so just mapping to that one prevents you from having to use Babel or any other sort of pre-processor.

**Comment by KaelWD** [comment]
@morphatic note that isn't 100% equivalent as `vuetify/es5` doesn't export components, so anything other than the default import from `vuetify/lib` will fail.

**Comment by morphatic** [comment]
Yeah, sorry. I've been banging my head against Jest and TS all day. I was sure I understood it at the time... 😓

**Comment by KaelWD** [comment]
It will work in most cases if you aren't manually importing anything else, just something to be aware of if you start getting problems.

**Comment by WaldemarEnns** [comment]
> Adding that transformIgnorePatterns property to my Jest config did the trick

That worked for me too. Thank you @KaelWD ! 🎉

**Comment by rudolfbyker** [comment]
What does the `transformIgnorePatterns` regex look like for `yarn berry` in `pnp` mode? See https://yarnpkg.com/advanced/rulebook#modules-shouldnt-hardcode-node_modules-paths-to-access-other-modules
