### ISSUE TITLE
[Bug Report] v-btn-toggle with v-model can't be tested 

### ISSUE THREAD

**Issue by shmaram** [vuetifyjs/vuetify#8485]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. I was trying to test the code provided in the codepen using Jest, please see that i'm using v-btn-toggle with v-model and no click event
2. trying to test clicking the button and it doesn't work 
I have tried both: 
    1. wrapper.trigger('click)
    2. wrapper.vm.$emit('click')

### Expected Behavior
to be able to test v-btn-toggle using v-model and no click event 

### Actual Behavior
not able to click on the buttons 

### Reproduction Link
<a href="https://codepen.io/shahar-shmaram/pen/dybYXPZ" target="_blank">https://codepen.io/shahar-shmaram/pen/dybYXPZ</a>

**Comment by johnleider** [comment]
Need more information such as your unit test. Also, this is already tested by us, what additional checks are you trying to do?

**Comment by shmaram** [comment]
H @johnleider , 
here is the testing I'm trying to run:
```
test('test click on mode switch to change url param named mode', () => {
    const wrapper: any = shallowMount(ToolbarComponent, { localVue, router, store });
    const vm: Toolbar = wrapper.vm;
    const toolbarDevBtn = wrapper.find('[data-id="toolbar-development-toggle-btn"]');
    toolbarDevBtn.trigger('click');
    expect(vm.$route.query).toMatchObject({mode:Number(contextModeEnum.Development).toString()});
  });
```

my test should check that after the click the URL query "mode" is changed, I have updated the codepen code according.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by shmaram** [comment]
Hi
Why did you close the issue? You requested more info and I provided the test and answered your question. What else was missing?

**Comment by frck006** [comment]
Hi,

I think your component is a functional component so without instance, no ?
But how to test the case of @shmaram ?
If it's not necessary to do like that, can you explain why ?
