### ISSUE TITLE
[Documentation] Search on Vuetify website and DataGrid shows [object InputEvent] in search field

### ISSUE THREAD

**Issue by shubhranshu** [vuetifyjs/vuetify#8487]
### Environment

**Browsers:** Chrome 76.0.3809.100, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce

**Issue in docs API search field**

* Click in the Search field in api section https://vuetifyjs.com/en/components/data-tables#api and start typing
* **[object InputEvent]** would appear in the text field, this string can not be deleted using backspace or delete.
* The text being typed in the field is not visible.

**Other instances**

The same issue can be reproduced on the site global search in the left action bar and on the search documentation in the Grid component.
 

### Expected Behavior
The search text shoukd be visible in the text field

### Actual Behavior
The event object string is appearing in the text field.
The search functionality seems to remain unaffected.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#api" target="_blank">https://vuetifyjs.com/en/components/data-tables#api</a>

**Comment by jacekkarczmarczyk** [comment]
Looks like ecde38e35ae69410dcffdde29eecbdeb938f6ace

**Comment by johnleider** [comment]
closed in c423ca21943a49f973d5e00d095c9be63be06bdd
