### ISSUE TITLE
[Bug Report] Button remains in on-hover after click on mobile browsers

### ISSUE THREAD

**Issue by unlink2** [vuetifyjs/vuetify#8495]
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Linux x86_64

### Steps to reproduce
Click on the button on mobile. The button will remain active and display a hover effect until another element is tapped.

### Expected Behavior
Button becomes inactive after click.

### Actual Behavior
Button remains active and displays on-hover colors.

### Reproduction Link
<a href="https://jsfiddle.net/unlink2/pckdz5qu/" target="_blank">https://jsfiddle.net/unlink2/pckdz5qu/</a>

### Other comments
On desktop browsers the button only remains in its on-hover state until the mouse leaves, which is to be expected. On mobile the button just remains stuck until the user taps another element.

**Comment by yooneskh** [comment]
This is not about Vuetify and is more about how mobile browsers handle hover state. nothing much can be done.

**Comment by unlink2** [comment]
Yes, that does make sense, however before 2.0 this did behave as expected. This is why I assumed it was due to a change rather than browser related.

**Comment by yooneskh** [comment]
Hmmm, makes sense to assume that. i didn't know about previous versions.
maybe others can help.

**Comment by MajesticPotatoe** [comment]
Your reproduction does not match the version you are saying has this issue (js fiddle is using v.0.14.8)
Also related to #8436?

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
