### ISSUE TITLE
[Feature Request] v-treeview - How to get all nodes selected ? Leaf and Parent 

### ISSUE THREAD

**Issue by frck006** [vuetifyjs/vuetify#8499]
### Problem to solve
Hi

Is is possible to have a way to get all nodes selected (Leaf & Parent)
https://codepen.io/frck006/pen/BXewBK?&editable=true&editors=101

### Proposed solution
When we click on "child #3",we ant leafs and parents "child #3" and "root" with "grandChild".

**Comment by frankhommers** [comment]
This seems impossible with selectionMode leaf. I think it's a bug. I have the same problem.

**Comment by nekosaur** [comment]
It is not a bug. Leaf mode will always only include leaf nodes. Before the selection mode prop existed we always included all nodes but with the current implementation of treeview that lead to a couple of annoying bugs. There are no immediate plans to add another mode.

If you do need the parent nodes you can always traverse the tree on your own and find them.

**Comment by tauanbinato** [comment]
Yep.. a leaf version including the root would be nice. Because if i want to delete all the folder i would like to delete the parent as well. Right now im doing that traversing the tree but in the future maybe would be nice to have more freedom on that
