### ISSUE TITLE
Can't negate the close-on-click attribute of a sidebar

### ISSUE THREAD

**Issue by acarnage** [vuetifyjs/vuetify#85]
Hello,

I can't set the attribute close-on-click of the sidebar to false...
i tried 
`close-on-click=false`
`close-on-click="false"`

it doesn't work :/

**Comment by johnleider** [comment]
Close on click is a boolean. You must use data binding. Try ```:close-on-click=false```

**Comment by acarnage** [comment]
It doesn't work for me, i also tried `v-bind:close-on-click=false`

Here is my side bar : 
` <v-sidebar id="sidebar" :close-on-click=false  fixed>`
Is there any order for parameters ?

**Comment by johnleider** [comment]
Do you have an element with v-sidebar directive on it? The sidebar  won't
work properly without it

**Comment by acarnage** [comment]
you mean something like v-sidebar-items ? 
I don't so i will try

**Comment by johnleider** [comment]
```<v-btn v-sidebar:sidebar>... </v-btn>```

**Comment by acarnage** [comment]
Work like a charm ! thanks
