### ISSUE TITLE
[Feature Request] minified navigation drawer close on losing focus

### ISSUE THREAD

**Issue by abarisuzuner** [vuetifyjs/vuetify#8501]
### Problem to solve
On our project we want to use minified navigation drawer. However there is no option to minify it when outside of the drawer is clicked. We want to expand the drawer by a button click and minify it back like when we do with `absolute` tag. Here is basic example to play around: 

https://codepen.io/abarisuzuner/pen/vYBLmBO

### Proposed solution
Can we have a minify on losing focus tag? When we click outside, it will minify the drawer instead of closing it.
Or maybe if mini is true, go to minified state when lose focus instead of hiding completely.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
