### ISSUE TITLE
vuetify 2.0.0 breaks

### ISSUE THREAD

**Issue by jappyjan** [vuetifyjs/vuetify#8503]
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Linux x86_64

### Steps to reproduce
Upgrade a 1.5.16 Vuetify manually to Vuetify 2.05.

### Expected Behavior
It should work

### Actual Behavior
running "yarn serve" throws 

    ERROR in /home/jappy/code/unitect/gui/src/main.ts
75:5 Argument of type '{ router: VueRouter; store: Store<State>; i18n: VueI18n; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
    73 |     i18n,
    74 |     // tslint:disable-next-line
  > 75 |     vuetify,
       |     ^
    76 |     render: (h) => h(App),
    77 | });
    78 | 

in main.js.

### Reproduction Link
<a href="https://codepen.io" target="_blank">https://codepen.io</a>

**Comment by nekosaur** [comment]
Have you added `vuetify` to `types` in tsconfig.json?

**Comment by jappyjan** [comment]
thanks a lot! that was the missing peace! :)
