### ISSUE TITLE
[Bug Report] Radios button

### ISSUE THREAD

**Issue by iTEEECH** [vuetifyjs/vuetify#8506]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
Hi

I use your framework Vuetify v2.0.5 on my project. 
I want to put radios button in radios group but I have a little bug on this module.

### Expected Behavior
 I would like to have radios buttons with color.

### Actual Behavior

I made a copy and paste of the example and always the same one The button not displayed, just the label. I must to add background color in the style. My style is scoped and I don't have overide the vuetify css

<a href="https://ibb.co/Lx707fm"><img src="https://i.ibb.co/Lx707fm/1.png" alt="1" border="0"></a>

### Reproduction Link
Nothing

### Other comments
Thank you for your help

**Comment by nekosaur** [comment]
From looking at the screenshot, it looks like you are not loading the correct icon css. But we are unable to further troubleshoot without a reproduction of the issue.

**Comment by iTEEECH** [comment]
Hi, Yes I understand.  I will try to reproduce the problem and see in more detail.
There is a special file for icons ?
