### ISSUE TITLE
[Bug Report] VDataTable dividers no longer visible

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#8514]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a `VDataTable` with a header that has the `divider` prop set to `true`

### Expected Behavior
A column divider appears

### Actual Behavior
No column divider visible

### Reproduction Link
<a href="https://codepen.io/Dylan-Chapman/pen/bGbEKjL" target="_blank">https://codepen.io/Dylan-Chapman/pen/bGbEKjL</a>

**Comment by bcronje** [comment]
Exact same issue with divider. In addition `width` is also ignored in v2.0.7

**Comment by nekosaur** [comment]
This was caused by the fix in https://github.com/vuetifyjs/vuetify/pull/8297. It seems like we might have to revert that and live with the chrome bug instead.
