### ISSUE TITLE
Editable Stepper inside a Dialog, Icon closes Dialog

### ISSUE THREAD

**Issue by BlueDotLaser** [vuetifyjs/vuetify#852]
### Steps to reproduce
Create a stepper with an editable step inside of a dialog. 
Complete the editable step. 
Click on the editable step to go back to it.
If you click on the step's label, it simply goes back to that step, but if you click on the icon, it will close the dialog.

### Versions
Vue.js v2.3.4
Vuetify v0.12.7
OS - Windows 10 & OSX... something
Browser - Chrome

### What is expected ?
I would expect the stepper to go back to the selected step without closing the dialog.

### What is actually happening ?
The dialog is being closed.

### Reproduction Link
https://codepen.io/eLaser/pen/zzRwMq

**Comment by johnleider** [comment]
Was the codepen changed? It seems there are some missing elements.

**Comment by BlueDotLaser** [comment]
Could you elaborate on "missing elements"? I tried to keep the codepen reproduction as stripped down as I could make it. There's a button, a dialog, and a stepper with three steps. 

To reproduce, press the button that says, "Open Dialog". In the dialog, click on the second step (they're 'editable'), then click the first step to go back to it.

If you click on the step's label, it works fine, if you click on the "Editable" icon, it closes the dialog.

**Comment by johnleider** [comment]
By the grace of the coding gods, it appears 0.13 has fixed this!

**Comment by BlueDotLaser** [comment]
So I too thought the issue was resolved with 0.13 but it looks like it's still occurring. 

I did a little more digging and discovered some info that might be helpful.

It seems the issue only occurs with non-persistent dialogs. I updated my codepen so that you can toggle between persistent and non-persistent. If you open a non-persistent dialog and get the stepper in a state where the "editable" icon is showingon  a step, click on the icon, and it will close the dialog. 

I did some debugging in the Dialog component and found that the "closeConditional" method is being hit when selecting the icon, both in persistent and non-persistent states. 

Seems like maybe the dialog registers a click on the material-icon as a click outside the dialog.

Let me know if the codepen is a good enough reproduction of the issue.

- Ethan

**Comment by BlueDotLaser** [comment]
Thank you @johnleider!
