### ISSUE TITLE
[Bug Report] Autocomplete showing all the values when already selected text entered

### ISSUE THREAD

**Issue by nmanikiran** [vuetifyjs/vuetify#8520]
### Environment
**Vuetify Version:** 1.5.2
**Vue Version:** 2.6.7
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce

https://codepen.io/nmanikiran/pen/eYOJvXK?editors=1010
In the Above codepen try to type and select `Sandra Adams` and after selecting it again type the same name as it is (ie.with casing).

then you can see all the items are displayed again

### Expected Behavior
when we type already selected value again then it should not display values

### Actual Behavior
autocomplete: 

when we type already selected value again then it should not display values but
it's displaying all the values again

### Reproduction Link
<a href="https://codepen.io/nmanikiran/pen/eYOJvXK?editors=1010" target="_blank">https://codepen.io/nmanikiran/pen/eYOJvXK?editors=1010</a>

**Comment by johnleider** [comment]
This is intended.
