### ISSUE TITLE
[Documentation] Overflow btn says the default key for item-value = 'value' but it is actually 'Value' with a capital V and will not work with lower case 'value'

### ISSUE THREAD

**Issue by jacklp** [vuetifyjs/vuetify#8522]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
just make a standard overflow btn that takes :items as an array of objects

### Expected Behavior
should be bound to 'value' lowercase

### Actual Behavior
binds to 'Value' uppercase

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/overflow-btns#overflow-buttons" target="_blank">https://vuetifyjs.com/en/components/overflow-btns#overflow-buttons</a>

**Comment by nekosaur** [comment]
Default value for `item-value` prop is `value`. Please provide a reproduction where the error can be observed.

**Comment by morficus** [comment]
@jacklp - are you using Vuetify 2.x or 1.x?

**Comment by jacklp** [comment]
just realised that this was a red herring.

The actual issue is that if you have this data:

:items=[
{
  name: 'a',
  value: '1',
},
{
  name: 'b',
  value: '1'
}
]

It will only show item a in the list because there are duplicate values. Spent 30mins completely confused as to why both items were not rendering when it seems that the backend team at my company were sending through a duplicate id as a value for the 2 products we are offering ><
