### ISSUE TITLE
[Bug Report] Checkbox has positioning issues when prepended to an autocomplete

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#8523]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Hover over the checkbox that is prepended to the autocomplete. See that the shadow effect is at a different position and the box is not centered within that shadow.

### Expected Behavior
Properly positioned checkbox

### Actual Behavior
Not properly positioned checkbox when prepended to an autocomplete field

### Reproduction Link
<a href="https://codepen.io/auspex/pen/yLBOBev?&editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/yLBOBev?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
I don't think we should take care of every possible component that can be put in the slot, this issue is easy enough to fix in userland https://codepen.io/jkarczm/pen/LYPNEEQ?editors=1010

**Comment by AuspeXeu** [comment]
From your link.
![Screenshot_20190814-142729](https://user-images.githubusercontent.com/2115696/63046092-c83c8e00-be9f-11e9-83f7-7e4269e41011.png)

**Comment by jacekkarczmarczyk** [comment]
Oops sorry, misread, i thought you're talking about vertical position of checkbox... I've also missed the Firefox part, Chrome and Edge look fine, that's why i didn't notice it
