### ISSUE TITLE
v-navigation-drawer affect layouts

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#853]
Reproduction of this issue:
See corner right of the second photo.
<img width="1440" alt="screen shot 2017-06-29 at 3 25 30 pm" src="https://user-images.githubusercontent.com/11958538/27713173-21a98aee-5cdf-11e7-845e-931de9858ac0.png">
<img width="1440" alt="screen shot 2017-06-29 at 3 25 32 pm" src="https://user-images.githubusercontent.com/11958538/27713174-2464927e-5cdf-11e7-8edb-1e6aca28d714.png">

When the nav-bar is opened, the layout is changed.
Sorry for the messy pictures, and thanks for keeping Vuetify so great. Just update from 10 to 12, and realize a lot has been changed...

**Comment by stephane** [comment]
The problem is gone in master
https://dev.vuetifyjs.com/layout/pre-defined

**Comment by johnleider** [comment]
If you are just now upgrading you may want to wait. 0.13 ous coming soon

**Comment by Ewocker** [comment]
Thanks! Love u guys 👍
