### ISSUE TITLE
[Feature Request] Adapt behavior of a v-input's label to other controls

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#8533]
### Problem to solve
When adding a label to the `v-input` component, it simply gets prepended to the default slot. However, when specifying a label for a more specific input, e.g. a v-combobox, the label get's put above the input. This leads to a non uniform look.

https://codepen.io/auspex/pen/dybMXbp?&editable=true&editors=111

### Proposed solution
Have a v-input's label be positioned above the default slot, just like for other inputs.

**Comment by johnleider** [comment]
This component is being removed as a public offering in v3 and there are no plans to change it before then.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
