### ISSUE TITLE
v-app-bar not working with clipped-right

### ISSUE THREAD

**Issue by santi77** [vuetifyjs/vuetify#8534]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
I try to reproduce the clipped right navigation drawer as seen in the complex layout example (https://vuetifyjs.com/en/examples/layouts/complex) and it doesn't work in the example code pen (https://codepen.io/johnjleider/pen/QewYYx) so I don't know if the example is not right or there is a bug.

### Expected Behavior
navigation drawer clipped by the app bar

### Actual Behavior
navigation drawer is not clipped

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/QewYYx" target="_blank">https://codepen.io/johnjleider/pen/QewYYx</a>

**Comment by johnleider** [comment]
The code you posted looks normal.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
