### ISSUE TITLE
[Bug Report] [VBtn] [2.0.7] incorrect event.target when clicking on button's text

### ISSUE THREAD

**Issue by annahanhhoang** [vuetifyjs/vuetify#8535]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1. create a v-btn with id and "Add" text
2. create a @click function handler which prints out button id when clicked
3. click on the btn inside the text area (ie on the Add text) 

### Expected Behavior
event.target is the button so the function prints button id

### Actual Behavior
event.target is the span "v-btn__content" so id is empty

### Reproduction Link
<a href="https://codepen.io/annahoang/pen/eYOZzEm?&editable=true&editors=101" target="_blank">https://codepen.io/annahoang/pen/eYOZzEm?&editable=true&editors=101</a>

### Other comments
This bug only happens when I click on the text. Clicking outside the button's text  prints out correct ID

**Comment by Teellcory** [comment]
This is just an issue with how the buttons are formed: they are a button tag with a span inside. When you click the text, you are specifically clicking the span. When you click outside the text, you are clicking the button.

Here's a working example: https://codepen.io/teellcory/pen/OJLNpJq

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
