### ISSUE TITLE
[Bug Report] Adding fill-height class to child row elements extends page

### ISSUE THREAD

**Issue by r3d4rmy** [vuetifyjs/vuetify#8536]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a row that takes up the full height of the page, create a child column element containing two same-level row elements and attempt to have the second row element take up the remaining height using the fill-height class.

### Expected Behavior
Rows at the same hierarchical level should take up any remaining space on the page if they contain the fill-height class.

### Actual Behavior
Rows at the same hierarchical level containing the fill-height class cause the page to be extended and adds white space.

### Reproduction Link
<a href="https://codepen.io/R3d4rmy/pen/BaBjvwy" target="_blank">https://codepen.io/R3d4rmy/pen/BaBjvwy</a>

### Other comments
I've read the 'grow and shrink' documentation in the grid section but that does not seem to apply in this case.

**Comment by Daaron3** [comment]
Hi, I couldn't achieve that behaviour with new grids system, but there is my solution of problem.

https://codepen.io/daaron3/pen/BaBZYvP

**Comment by johnleider** [comment]
You don't need to apply fill-height to `v-row`, this is handled by the designation on `v-container`.

https://codepen.io/johnjleider/pen/mdbqXBy
