### ISSUE TITLE
[Bug Report] [v-navigation-drawer] Texts are not aligned correct when using font awesome

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#8541]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Just use font awesome and the navigation drawer

### Expected Behavior
an equally aligned menu

### Actual Behavior
Some texts are aligned more to the right then others

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/qBWZmgE" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/qBWZmgE</a>

**Comment by johnleider** [comment]
Not much we can do. Font-awesome is designating that icon as needing 32px on the x-axis.

**Comment by ricardovanlaarhoven** [comment]
when giving the `.v-icon.fa` a width this problem is solved.
Not sure what width i should give them but then it's solved

https://codepen.io/ricardovanlaarhoven/pen/dybgGmw
