### ISSUE TITLE
[Bug Report] Vuetify docs uses cache option which not provide by vue ssr

### ISSUE THREAD

**Issue by wizardnet972** [vuetifyjs/vuetify#8543]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
The server file have cache option: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/server.js#L30.

### Expected Behavior
Without cache or other implementation

### Actual Behavior
unnecessary code

### Reproduction Link
<a href="https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/build.dev.js#L9506" target="_blank">https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/build.dev.js#L9506</a>

### Other comments
according to the vue sources. The cache option is supported only in `createRenderer` and not in `createBundleRenderer`.
https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/build.dev.js#L9506

So I think there is a mistake to [add cache option](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/server.js#L30) in the vuetify docs website in `createBundleRenderer`.

**Comment by KaelWD** [comment]
You're wrong, the line you linked is inside `createBundleRenderer`

https://ssr.vuejs.org/api/#createbundlerenderer
