### ISSUE TITLE
[Documentation] bottom-sheets, playground

### ISSUE THREAD

**Issue by Lustach** [vuetifyjs/vuetify#8544]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 7

### Steps to reproduce
At the section "Playground" click "hide overlay" then click "open playground" then click "close" then click "hide overlay"

### Expected Behavior
"hide overlay" must be disabled

### Actual Behavior
Now overlay force me to refresh the page 

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/bottom-sheets" target="_blank">https://vuetifyjs.com/en/components/bottom-sheets</a>

### Other comments
Ty

**Comment by MajesticPotatoe** [comment]
Duplicate #8142
