### ISSUE TITLE
[Bug Report] v-data-table reset shared options.sync model properties not sorting specific

### ISSUE THREAD

**Issue by isimonov** [vuetifyjs/vuetify#8548]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
If I have options.sync model shared with another component, a table sort call resets other properties to their original. For example options.sync="filter" if set filter.test in v-select field any value, then do sorting any table field - this reset filter.test See codepen exemple...

In version 1.5, everything was fine. In version 2, I noticed the wrong behavior in my opinion.

I think this is wrong, because it is often convenient to share this sorting model with the filtering model, rather than dividing them into 2 independent entities.

### Expected Behavior
Not reset shared options.sync model properties.

### Actual Behavior
Reset shared options.sync model properties.

### Reproduction Link
<a href="https://codepen.io/isimonov/pen/BaBKmWV" target="_blank">https://codepen.io/isimonov/pen/BaBKmWV</a>

**Comment by nekosaur** [comment]
I would say this is a `wontfix`. `options` has a specific structure as it is used by v-data-table. I don't see why we should need to bother to preserve arbitrary properties on the object outside of what it is used for. You can always nest things if you want a shared object

```js
{
  test: 'foo',
  options: {...}
}
```
