### ISSUE TITLE
[Bug Report] v-data-table does not display boolean values

### ISSUE THREAD

**Issue by sw34** [vuetifyjs/vuetify#8554]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Took codepen from your documentation (first example) and changed a couple values for the "fat" property to true or false, and nothing displays in those rows for the Fat column.

### Expected Behavior
If you take the 1.5.17 version of the first codepen in documentation and do the same thing, "true" or "false" shows up.

### Actual Behavior
nothing displays in those rows for the Fat column.

### Reproduction Link
<a href="https://codepen.io/swaterhouse/pen/jONqzyX?&editable=true&editors=101" target="_blank">https://codepen.io/swaterhouse/pen/jONqzyX?&editable=true&editors=101</a>

**Comment by rahultrivedi180** [comment]
> ### Environment
> **Vuetify Version:** 2.0.7
> **Last working version:** 1.5.17
> **Vue Version:** 2.6.10
> **Browsers:** Chrome 76.0.3809.100
> **OS:** Windows 10
> 
> ### Steps to reproduce
> Took codepen from your documentation (first example) and changed a couple values for the "fat" property to true or false, and nothing displays in those rows for the Fat column.
> 
> ### Expected Behavior
> If you take the 1.5.17 version of the first codepen in documentation and do the same thing, "true" or "false" shows up.
> 
> ### Actual Behavior
> nothing displays in those rows for the Fat column.
> 
> ### Reproduction Link
> https://codepen.io/swaterhouse/pen/jONqzyX?&editable=true&editors=101

You can use template with v-prop inside data table.

**Comment by marinko-peso** [comment]
Can confirm this issue is happening, same thing, Chrome - Mac, v2.0.10

**Comment by LouwrensP** [comment]
> > ### Environment
> > **Vuetify Version:** 2.0.7
> > **Last working version:** 1.5.17
> > **Vue Version:** 2.6.10
> > **Browsers:** Chrome 76.0.3809.100
> > **OS:** Windows 10
> > ### Steps to reproduce
> > Took codepen from your documentation (first example) and changed a couple values for the "fat" property to true or false, and nothing displays in those rows for the Fat column.
> > ### Expected Behavior
> > If you take the 1.5.17 version of the first codepen in documentation and do the same thing, "true" or "false" shows up.
> > ### Actual Behavior
> > nothing displays in those rows for the Fat column.
> > ### Reproduction Link
> > https://codepen.io/swaterhouse/pen/jONqzyX?&editable=true&editors=101
> 
> You can use template with v-slot prop inside data table.

Please give example how one would use v-slot to solve this?

**Comment by sw34** [comment]
<template v-slot:item.yourBoolean="{ item }">
     <v-icon>
	{{ item.yourBoolean ? "mdi-checkbox-marked" : "mdi-checkbox-blank-outline" }}
     </v-icon>
</template>

**Comment by LouwrensP** [comment]
> ```
> <template v-slot:item.yourBoolean="{ item }">
>      <v-icon>
> 	{{ item.yourBoolean ? "mdi-checkbox-marked" : "mdi-checkbox-blank-outline" }}
>      </v-icon>
> </template>
> ```

Thank you! Works like a charm.

**Comment by simonklimek** [comment]
Vuetify 3 has the same problem with Booleans, can somebody create the issue for Vuetify 3 please
