### ISSUE TITLE
[Bug Report] v-avatar in v-card loses border radius (round corners) if it is first child

### ISSUE THREAD

**Issue by iamareebjamal** [vuetifyjs/vuetify#8555]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.8
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Add v-avatar as the first element of v-card

### Expected Behavior
v-avatar should have round corners (equal border radius) irrespective of where it is placed

### Actual Behavior
v-avatar loses border radius (round corners) if it is first child in a v-card

### Reproduction Link
<a href="https://codepen.io/iamareebjamal/pen/aboNYyd" target="_blank">https://codepen.io/iamareebjamal/pen/aboNYyd</a>

### Other comments
As a workaround, I have to add an empty element like `<div></div>` as the first child of v-card

**Comment by johnleider** [comment]
There is unfortunately no better way to ensure that child elements can have the proper border-radius from v-card.

Yes, we could add exceptions for some components like `v-btn` or `v-avatar`, but those exceptions may not be wanted by the user, there is no way for us to know. If you feel that you have a way we can achieve both outcomes, I will gladly accept a PR to make this better. In the mean time though, it is not considered a bug.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Farnazed** [comment]
Has this issue been fixed?
