### ISSUE TITLE
[Bug Report] v-app-bar-nav-icon bug

### ISSUE THREAD

**Issue by oixan** [vuetifyjs/vuetify#8559]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Just click the top left button. As you can see the button effect dont go away. it remain until you click some else.

### Expected Behavior
the menu button effect should go away like in 1.5.6 version

### Actual Behavior
the menu button effect dont go away

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/aezMOO" target="_blank">https://codepen.io/johnjleider/pen/aezMOO</a>

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8436
