### ISSUE TITLE
[Bug Report] VFab button is sickly blinking when hovered over VFooter with { hover } slot

### ISSUE THREAD

**Issue by km2442** [vuetifyjs/vuetify#8560]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Follow the steps listed in codepen

### Expected Behavior
No sick blinking with hiding below Footer

### Actual Behavior
Sick blinking with hiding below Footer

### Reproduction Link
<a href="https://codepen.io/km2442/pen/GRKZdKY" target="_blank">https://codepen.io/km2442/pen/GRKZdKY</a>

**Comment by jacekkarczmarczyk** [comment]
This is because fab button has `z-index: 4` and normal button doesn't have `z-index` and it hides below the footer. Adding `style="z-index: 4"` to the button fixes the problem

**Comment by km2442** [comment]
Actually yes, it fixes this issue, thanks,
 Also, you could add specific prop for pulling element to the top of z-index...

**Comment by johnleider** [comment]
I think the fab functionality just needs to be moved to a dedicated component. I've marked this for v2.3 but it could make it into v2.2.

**Comment by johnleider** [comment]
This component is now available https://vuetifyjs.com/en/components/floating-action-buttons/
