### ISSUE TITLE
[Documentation] Add an example in Sass Variables to customize components with multiple style properties

### ISSUE THREAD

**Issue by lnarea** [vuetifyjs/vuetify#8564]
### Problem to solve

In the current documentation for [Sass Variables](https://vuetifyjs.com/en/customization/sass-variables) there are one example to change the default background color style of the card component.

```
@import '~vuetify/src/styles/styles.sass';

// For updating SASS lists
$material-light: map-merge($material-light, ( cards: blue ));
```

I understand that this will overwrite _light.scss when compiling to css

```
 ./styles/settings/_light.scss

$material-light: (
'cards': map-get($shades, 'white')
)
```

This works perfectly

but if I want to change the background color of the calendar component,

```
./styles/settings/_light.scss

$material-light: (
  'calendar': (
    'background-color': map-get($shades, 'white'),
    'outside-background-color': #f7f7f7,
    'line-color': map-get($grey, 'lighten-2'),
    'interval-color': map-get($grey, 'darken-3'),
    'interval-line-color': map-get($grey, 'lighten-2'),
    'text-color': map-get($shades, 'black'),
    'past-color': rgba(map-get($shades, 'black'), .38)
  ),
);

```
Doing this will not work.
```


$material-light: map-merge($material-light, ( calendar { background-color: red }));//SCSS
or
$material-light: map-merge($material-light, ( calendar background-color: red)); Sass

```
### Proposed solution
There should be an example in the documentation to change the style of a component that has more than one property such as the calendar component

**Comment by lnarea** [comment]
Well, I was using an incorrect syntax to reallocate the value of a property, now it works.

$material-light: map-merge($material-light, ( cards: red));
$material-light: map-merge($material-light, ( calendar: (background-color: red) ));
$material-light: map-merge($material-light, ( picker: (body: red) ));

or 

$material-light: map-merge($material-light, ( 
    cards: red, 
    calendar: (background-color: red), 
    picker: (body: red)
));

**Comment by OstapL** [comment]
@lnarea are you using vue cli or webpack ?
I can't change variables (
even $btn-border-radius

**Comment by lnarea** [comment]
@OstapL, I´m using VUE CLI.

If you are using VUE CLI make sure you are writing the file vue.config.js correctly

// vue.config.js
module.exports = {
  configureWebpack: {
    // Configuration applied to all builds
  },
  css: {
    loaderOptions: {
      sass: {
        data: `@import "~@/styles/sass/main.scss"` // change the route with you main.scss location in yout proyect
      }
    }
  },
  chainWebpack: config => {
    ["vue-modules", "vue", "normal-modules", "normal"].forEach(match => {
      config.module
        .rule("scss")
        .oneOf(match)
        .use("sass-loader")
        .tap(opt =>
          Object.assign(opt, { data: `@import '~@/styles/sass/main.scss';` })
        );
    });
  }
};
