### ISSUE TITLE
[Bug Report] Overlapping events on day view causes some event texts to be hidden by other events

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#8565]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Create overlapping events on the day view

### Expected Behavior
All event texts should be visible.

### Actual Behavior
On page load, the "Lunch" event texts are hidden by "Another Meeting".

When you click on the event, or go to the next day and back, this fixes itself and shows all the events properly. 

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/BaBKqXm?" target="_blank">https://codepen.io/pumpknhd/pen/BaBKqXm?</a>

### Other comments
Instead of doing it the "Google Calendar" way with the overlaps, I think it might be better for the system to create columns as needed.

For example, in the attached CodePen, there are 4 events:
A) Big Meeting - 8-11:30a
B) Meeting - 9-10a
C) Another Meeting - 10-1:30p
D) Lunch - 12-3p

Currently, v-calendar is showing:
A - overlapped by B and C. With C overlapping D.

I'd like to propose that instead of overlapping, it would calculate out 2 columns during that time. So that:

Column 1 |  Column 2
------------ | -------------
Big Meeting | Meeting
Lunch | Another Meeting

**Comment by pumpknhd** [comment]
To illustrate.

Current bug:
![v-calendar-overlap-bug](https://user-images.githubusercontent.com/22015251/63132551-4a978180-bf76-11e9-932a-00ab55349b70.png)

When you click on an event or change dates, it fixes itself:
![v-calendar-overlap](https://user-images.githubusercontent.com/22015251/63132566-5be08e00-bf76-11e9-87b4-f51f584c3342.png)

But I think this would look even better:
![v-calendar-overlap-after](https://user-images.githubusercontent.com/22015251/63132573-63079c00-bf76-11e9-8bd4-7e070ae7fcd9.png)

**Comment by tryptamine25** [comment]
+ In some cases, events are completely hidden
https://codepen.io/tryptamine25/pen/QWLvGvY
'event3' in codepen.

**Comment by tryptamine25** [comment]
@pumpknhd In my codepen i use 
`.v-calendar .v-event-timed {
    display: inline-flex;
    position: sticky;
}`
But i think it's a kludge and in my project, when i have many events in day i have result like in pic
![Снимок экрана 2019-08-28 в 10 21 59](https://user-images.githubusercontent.com/32172474/63834355-d5687b00-c97d-11e9-9439-b222d379ba3b.png)

**Comment by tryptamine25** [comment]
And also of course on the weekly calendar everything is broken :(
![Снимок экрана 2019-08-28 в 10 33 45](https://user-images.githubusercontent.com/32172474/63835073-64c25e00-c97f-11e9-9c0c-5c8fe6ff4de3.png)

**Comment by pumpknhd** [comment]
@tryptamine25 What do you think? Maybe we could get input on which option people like.
A) Option 1 - Overlap (like Google does it)
B) Option 2 - Put things into columns

**Comment by tryptamine25** [comment]
@pumpknhd idk, in my project i separate events data to people, and showing personal events for people, but it's bad solution

**Comment by ClickerMonkey** [comment]
The overlapping functionality needs to exist for the week view when days aren't so wide. Perhaps an option could be added at some point to switch to column mode. There would be two new modes, individual column, or collapsed columns.

**Comment by p0ngzzz** [comment]
Has anyone have problem like me  in my project using vuetify3 weekly v-calendar and when events have same time and same date the latest event is stack on each other how could i fix it bro ?
