### ISSUE TITLE
[Bug Report] Boolean value incorrect default value

### ISSUE THREAD

**Issue by NathanWang2** [vuetifyjs/vuetify#8567]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Resizing the navigation bar

### Expected Behavior
The default value for the "sideNav" boolean value should be "false". This boolean value should make the navigation drawer stay hidden.

### Actual Behavior
Upon resize to a bigger screen, it will eventually default the value of "sideNav" to "true" even though the default value is false and there is no place that this value is changed.

### Reproduction Link
<a href="https://github.com/NathanWang2/FirebaseVueTutorial/tree/dev" target="_blank">https://github.com/NathanWang2/FirebaseVueTutorial/tree/dev</a>

### Other comments
Video can be seen here https://imgur.com/FFdZuPi

**Comment by MajesticPotatoe** [comment]
This is intended. Setting v-model to false doesn't negate the internal functions of the component (which has auto open/close based on screen size) It simply just initializes it in a closed state. You can disable the auto resize with the `disable-resize-watcher` prop (or disable all auto state functionalities with `stateless`)
