### ISSUE TITLE
[Feature Request] Add space-evenly for Flex justify

### ISSUE THREAD

**Issue by ikarosu** [vuetifyjs/vuetify#8568]
### Problem to solve
I need css style
```css
justify-content: space-evenly
```

### Proposed solution
Add the following class
`.justify-space-evenly`
`.justify-sm-space-evenly`
`.justify-md-space-evenly`
`.justify-lg-space-evenly`
`.justify-xl-space-evenly`

**Comment by zhang53** [comment]
@ikarosu You can use <v-row> like so:
```
<v-row justify="center" no-gutters>
    <v-spacer />
    <!-- Component 1 -->
    <v-spacer />
    <!-- Component 2 -->
    <v-spacer />
    <!-- Component 3 -->
    <v-spacer />
</v-row>
```

**Comment by danieldanielecki** [comment]
Wouldn't say that the solution proposed by @zhang53 is adequate. What about columns for example?

The Vuetify's Grid System is still far from [Angular Flex-Layout](https://github.com/angular/flex-layout), how it would've been great to have it here can be seen in the [GitHub repo](https://github.com/angular/flex-layout) or on the [demo page](https://tburleson-layouts-demos.firebaseapp.com).

Would be great to have the `justify-space-evenly`-related classes, same case for `space-between`, `space-around` for both, columns and rows. It would simplify to build complex Grid Layouts.

**Comment by PhysRex** [comment]
Another reason for this is a custom layout that doesn't use or need the whole container/row/column paradigm, but can be used just as a helper class. Also, just for consistency's sake 😁

**Comment by KaelWD** [comment]
`space-evenly` has poor browser support, notably IE11. We're dropping IE in v3 so it should be safe to implement now.

**Comment by ecerulm** [comment]
[caniuse.com justify-content-space-evenly](https://caniuse.com/justify-content-space-evenly)  estimates that `space-evenly` is usable by 92% of the users.

**Comment by baranelitez** [comment]
It's ~95% now. Is this going to be added soon or should we expect v3?

**Comment by bmccaffrey** [comment]
@KaelWD Is there anyway we can re-open this issue since that commit seems to have been removed from master?
