### ISSUE TITLE
[Feature Request] v-carousel set cycle property to numeric rather than boolean 

### ISSUE THREAD

**Issue by rotemrevivo91** [vuetifyjs/vuetify#8575]
### Problem to solve
currently `cycle` is a boolean value adding a 6s transition. It would be nice to allow users to set the seconds.

### Proposed solution
if this value is not 0, use cycle instead of boolean, use passed numeric value as the delay between transitions

**Comment by jacekkarczmarczyk** [comment]
Do you mean the `interval` prop?

**Comment by rotemrevivo91** [comment]
You're absolutely right i might have skipped it. Wouldn't it make more sense to combine the two together though? And maybe change the interval from ms to s as it makes little sense having images/items moving in such a speed in a carousel.
Thanks for the help!

**Comment by ibrahimBeladi** [comment]
Having the interval in milliseconds will provide better flexibility.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
