### ISSUE TITLE
[Bug Report] Scroll with open autocomplete detaches dropdown

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#8579]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 7

### Steps to reproduce
Open the dialog
Type into the autocomplete to start the dropdown
Scroll down with the mouseover the card, not the dropdown list

### Expected Behavior
Dropdown to close

### Actual Behavior
Dropdown stays open and detaches from autocomplete

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/wvwWGVr" target="_blank">https://codepen.io/teellcory/pen/wvwWGVr</a>

**Comment by jacekkarczmarczyk** [comment]
That's what `attach` prop is for
