### ISSUE TITLE
Add table row expand panel

### ISSUE THREAD

**Issue by hellwen** [vuetifyjs/vuetify#858]
add table row expand panel
like: [element](http://element.eleme.io/#/en-US/component/table) ```<el-table-column type="expand">```

**Comment by johnleider** [comment]
You should be able to do this now with an ```expansion-panel```. Ill try to get together an example.

**Comment by kennethllamasares** [comment]
any example of table row with expansion panel?

**Comment by nekosaur** [comment]
Here's a prototype https://codepen.io/anon/pen/bRKMQd

**Comment by kennethllamasares** [comment]
wow thanks! @nekosaur

**Comment by nekosaur** [comment]
A second version https://codepen.io/anon/pen/YQJwar

**Comment by smtlk** [comment]
Nowhere near as easy to use as Element UI and more of a hack than a feature of the framework, as such i think the feature request is still valid, but if no one else wants if then i guess it's alright

**Comment by nekosaur** [comment]
This is a feature request, the codepen is only a prototype

**Comment by wunderdojo** [comment]
+1 on this and thinks for the codepen

**Comment by johnleider** [comment]
This has been added to the framework and will actually launch with 0.16, ahead of schedule!

**Comment by kmcmh** [comment]
I am a little late to the party but can you perform the same operation just opposite? Meaning, have the syntax match something below? I need to have an expansion panel that opens up to a very specific data table that matches the id of the expansion panel. For example, have 10 states where the expansion-panel header is each states name. Once you click on the expansion a data table opens up with information that is tied directly to that state.

PS I am new to Vuetify and VueJS but I am LOVING the language! 

<v-expansion-panel-content>
   <v-data-table>
      <td class="text-xs-left">{{ props.item.ID }}</td>
      <td class="text-xs-left">{{ props.item.first_name }}</td>
      <td class="text-xs-left">{{ props.item.last_name }}</td>   
   </v-data-table>
</v-expansion-panel-content>

**Comment by kmcmh** [comment]
```
<v-expansion-panel-content>
   <v-data-table>
      <td class="text-xs-left">{{ props.item.ID }}</td>
      <td class="text-xs-left">{{ props.item.first_name }}</td>
      <td class="text-xs-left">{{ props.item.last_name }}</td>   
   </v-data-table>
</v-expansion-panel-content>
```

**Comment by jscottwillems** [comment]
Trying to implement the above prototype but the expansion panels only show when I refresh the table. How can I set this up to where the table automatically refreshed when the expanded value is changed?
