### ISSUE TITLE
[Feature Request] allow grouping of nested values

### ISSUE THREAD

**Issue by ivanvorona** [vuetifyjs/vuetify#8580]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
try to group based on one of columns.

### Expected Behavior
recognized group instead of undefined.

### Actual Behavior
undefined is shown.

### Reproduction Link
<a href="https://codepen.io/ivorona/pen/ZEzOOmE" target="_blank">https://codepen.io/ivorona/pen/ZEzOOmE</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Works in v3: https://play.vuetifyjs.com/#eNq1VMlu2zAQ/ZUBL06AeAlaoIChBGidrumhh16KOAeKGimEKZIgKReq4X/vyFpdVC0SwyeS8zjvvRkuDzvmnZi/tXa2LZAtWRQwt4oHvF1rgGg7TXjg08BjhVUAYPmEPEHnb9asma1Zg0jKreIJeo8u9EDmTGGncUnYYfqubKEqZbrlqkDCNM+xBm6j+VCZvETzgTFaeuGkDeAxFPZgVebWuAA7cJjCHlJncphQTZNqO4Aw2gdo1OGm2nXxUHvY1QPABsslTLRJcCZIKDOunFy1oHFUK8Hciza4P4yPl0OFpiek8Cd7kEEhEdzV3YGL68UiowLcVursshfiSmaa9ilMQx899Kh1VzXq2ATpdAKrzvtxVldTa7x33Z7YX2xXqct+SQESJ8oPzvxCDT9MVriBT2JsZGjPZ4EgHPK8x1u7ne3/6XQc4LlOfkrxdEax90Jx6UYEVsZsZNf3F7CvCiv4ZsBwRP+N+zC8cM+m/0j3CF1MLUjOVcEXVKqEGLkeU6AzOqWGr0YpaY09E/0no7EUJo9H+L+bNMVTGnRndDH2Gk4+4HsZ7vkY+z9bQ089mtdfJn2WbH/FXs1ez96werxesMffxTO5oA==
