### ISSUE TITLE
[Bug Report] [v-text-field] Loss of persistant form label when outlined is set along side full-width

### ISSUE THREAD

**Issue by goofballtech** [vuetifyjs/vuetify#8586]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Click link. Observe the only difference is full-width prop on the v-text-field

### Expected Behavior
label to persist as subscript

### Actual Behavior
it disappears

### Reproduction Link
<a href="https://codepen.io/goofballtech/pen/RwbRpYv" target="_blank">https://codepen.io/goofballtech/pen/RwbRpYv</a>

**Comment by johnleider** [comment]
While there is no actual reason to use those 2 props together, the fix cleans up the styles so I'll bite.
