### ISSUE TITLE
[Bug Report] Unable to use custom text value for header in v-data-table

### ISSUE THREAD

**Issue by nutann3** [vuetifyjs/vuetify#8589]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Mac OS 10.14.6

### Steps to reproduce
Pass header-text prop to v-data-table

### Expected Behavior
I want to use custom key instead of default key "text" for headers object. For example i want use label instead of text for header --- {label: "header text"} 

### Actual Behavior
But header-text prop is disappeared in the v2.

### Reproduction Link
<a href="https://codepen.io/nutan/pen/mdbEmWd" target="_blank">https://codepen.io/nutan/pen/mdbEmWd</a>

**Comment by nekosaur** [comment]
What are the reasons for you not being able to use the `text` property?

**Comment by nutann3** [comment]
I'm loading a table using third party API where the header text is under 'label' property. Now I'm replacing 'label' property with 'text' property after fetching the data solely for this purpose. Using header-text prop I can skip this step and can have much more maintainable code.

**Comment by johnleider** [comment]
Due to limited bandwidth, moving to v2.3.x.

**Comment by KaelWD** [comment]
We're moving away from these `*-text` props for several reasons, if you have a different structure we recommend mapping your array to match the structure required by the component.
