### ISSUE TITLE
left-fixed-sidebar layout overlaps navbar

### ISSUE THREAD

**Issue by pauloramires** [vuetifyjs/vuetify#86]
Hello John,
first of all many thanks for your excellent work!
After playing with the left-fixed-sidebar layout a bit, I realized that the sidebar overlaps the navbar component. Is this the expected behavior for the sidebar, or should it's top position be located below the navbar?

Here is the fiddle:
https://jsfiddle.net/pauloramires/kLtkzbxk/1/

Thanks,
Paulo

**Comment by johnleider** [comment]
That is intended. When using ```v-app```, it will automatically scale the padding for those other components.

**Comment by pauloramires** [comment]
Could you check the fiddle then?
I used the template provided in the documentation but somehow that auto scaling of the padding is not happening... Event within the v-app component, the overlap occurs.
Thanks

**Comment by pauloramires** [comment]
Just delete the extra css line that I have included in the fiddle...
--- .sidebar--fixed { top: 5rem; } ---

**Comment by johnleider** [comment]
I have, and I'm looking at the fiddle. Nothing seems out of order. When I resize the window, at mobile break point, the sidenav closes and the header/content padding is removed. Is there something that I'm missing?

**Comment by pauloramires** [comment]
Isn't the sidenav overlapping the header in your browser? If so, is this the expected behavior?
PS: I have added that extra css line in the fiddle, pls remove it before...

**Comment by johnleider** [comment]
It does overlap the header, that is intended. If you inspect the header, it should have padding to compensate for that.

**Comment by pauloramires** [comment]
ok John, many thanks then.
btw, what is the difference then between the fixed and drawer layouts for the sidebar?

**Comment by johnleider** [comment]
A drawer is not opened by default.
