### ISSUE TITLE
Different width of Navigation Drawer  (left/right)

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#860]
What will it allow you to do that you can't do today?
- we are using the left navigation drawer as a navigation and the right one as detail-window/form-container ...
- the navigation should have the default value of 300px and the other drawer should have a larger width
- in the stylus files is only one variable for both drawers. Could we add something like $navigation-drawer-width-right and $navigation-drawer-width-left
  
 How will it make current work-arounds straightforward?
- at the moment you have to override a multiple specific classes to get that effect. 
- if the classes change we have to change them too

If you are okay with the new variables i would create a pull request

**Comment by johnleider** [comment]
I am okay with a PR, but if you could, please wait to submit it until after 0.13 so that you are working with the release state of the drawer, Thank you!

**Comment by johnleider** [comment]
The default is now properly set to 300, however, adding specific functionality to handle different drawer widths would be really difficult with the way the framework is currently setup. The current values are expected by the main layout elements and they will always adjust based upon that 300px.

In light of that, this is just something that I think we could "even" support, let alone the time it would take to support it.

**Comment by JeanLucEsser** [comment]
I would have loved if that functionality could have been added.
I guess an alternative would be to create our own flex based fixed column.
But I wonder if that would mean specifying the width for the fluid container when resizing the window. Need to make some tests, but know that if one day the framework is able to support different width, it would be awesome. The navigation drawer is a good design not only for navigation. Think filter pane for a list of items.

BTW, any hints on such design (right fixed filter pane) is welcomed.
