### ISSUE TITLE
[Documentation] New vuetify grid is a unclear - migration examples or comparesion

### ISSUE THREAD

**Issue by gotenxds** [vuetifyjs/vuetify#8602]
### Problem to solve
Currently it is unclear how is the new row and col componenets work in realtion to a normal flexbox, layout was a bit more straight forward, it was just a flexbox, right now I cant even guess how am I suppose to use a `direction-column` Am I to just use multiple v-rows ? am I missing a prop ?

### Proposed solution
A migration guide/comparsion to v-layout v-flex/ compression to flexbox

**Comment by michaelscheurer** [comment]
This definitely needs to get priority. We are also in the process of migrating from 1.5 to 2.x. But this is almost impossible as long as there is such a basic gap in the documentation. Please, please prioritize. We've been waiting for this for days.

**Comment by zulrang** [comment]
Half of the examples in documentation don't even work.  See: https://vuetifyjs.com/en/components/grids#row-and-column-breakpoints

**Comment by MajesticPotatoe** [comment]
Do you have any other suggestions on best ways to improve or add clarity? Doesn't really seem that they are 1:1 but just borrows some of their functionalities combined with bootstrap inspiration. Not sure about the direction-column ordeal, my best guess would be to use multiple v-rows. thoughts @KaelWD ? 
* Looking at just the [usage](https://vuetifyjs.com/en/components/grids#usage) alone it seems pretty indepth (including links to additional resources to bootstrap and the css flexbox guide)
* AFAIK,  there is little in terms of a migration guide as they are more or less to be considered completely different grid systems (v2 being inspired by bootstrap-which is mentioned, v1 being more homegrown)
* One thing worth adding would be information on the eslint plugin and maybe a reference to the 1.5 documentation noting `v-layout` -> `v-row` and `v-flex` -> `v-col`

**Comment by gotenxds** [comment]
I think a brief explnation about how does the v-col and v-row transfer into the flex-box world, Flexbox is a clear and web wide standard of working with layouts, bootstrap is only used by, well bootstrap.
As a vuetify user I shouldn't need to go and search the web for bootstrap to flexbox guides, I'm not working with bootstrap, honestly one of the reasons my team and I decided to go with vuetify was the lack of bootstrap related stuff... but ho well... that's where we are and there is no changing stuff now, at least make the usage clear for people who come from a normal flexbox, again, a web wide standard.

**Comment by AyushiBShah** [comment]
@KaelWD  : can you please help us how to migrate from v-layout and v-flex to new grid?

**Comment by throrin19** [comment]
Same problem here, The v-layout/v-flext to new grid system is a shame for my team and my project. 

All responsive examples does not works at this time and we need them to understand the new grid system and migrate to this.

Our site is fully responsive in vuetify 1.5 and we want to continue in vuetify 2. 

But we have so many components to upgrade (and so many forms in our case). 
It's very bad to change this core part of vuetify.

**Comment by douglasg14b** [comment]
100% on this. The migration guide barely touches on it, and makes no mention of the parallels between the new `v-col` & `v-row` and the old `v-layout` and `v-flex`.... And why they are not completely interchangeable.

**Comment by MajesticPotatoe** [comment]
There is no migration guide for the grid - thus why this issue is here. the docs for 2.x and 1.x grids contain just as much information. the only real addition was a small section related to the individual parts. Other than that its the same format. Most of the migration itself is handled by the eslint plugin.

Unfortunately I have yet to touch the 2.x grids and know little about it which is why this hasn't progressed.

**Comment by johnleider** [comment]
Loud and clear. Will resolve today.

**Comment by b-strauss** [comment]
In version 1.5 it was possible to set a column attribute on v-layout to change the flex-direction to column. The version 2 docs don't mention the flex-direction at all. Furthermore v-layout is now called v-row. Is it even possible to change the flex-direction anymore?

**Comment by morficus** [comment]
@b-strauss take a look at the [Grid System](https://vuetifyjs.com/en/components/grids#api) page in v2.x. If you change API explorer to `v-row` you should see props for controlling various flex things. You can also take a peak at the code behind the [horizontal alignment example](https://vuetifyjs.com/en/components/grids#horizontal-alignment)

**Comment by MajesticPotatoe** [comment]
@b-strauss Additionally there is also a whole section on [flex](https://vuetifyjs.com/en/styles/flex) and [flex direction](https://vuetifyjs.com/en/styles/flex#flex-direction)

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
