### ISSUE TITLE
[Bug Report] Vuetifty file upload only load empty object

### ISSUE THREAD

**Issue by fachrizalrifahdi** [vuetifyjs/vuetify#8603]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
I can't use vuetify file upload on my v data table , i have tried change v-model edited item but still send empty object payload on post api please help to fix this

### Expected Behavior
payload send file location object

### Actual Behavior
payload send empty location object

### Reproduction Link
<a href="https://codepen.io/fachrizalrifahdi/pen/yLBJpEJ" target="_blank">https://codepen.io/fachrizalrifahdi/pen/yLBJpEJ</a>

**Comment by MajesticPotatoe** [comment]
Please provide a minimal reproduction that illustrates your issue. The codepen you provided is unusable and does not demonstrate the issue. You can use the following template https://template.vuetifyjs.com/ .

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
