### ISSUE TITLE
[Bug Report] Toolbar in fullscreen, scrollable dialog is too big

### ISSUE THREAD

**Issue by robbevp** [vuetifyjs/vuetify#8606]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0, Google Chrome, Safari
**OS:** Mac OS 10.14, Android

### Steps to reproduce
Create a dialog that is full screen and scrollable.
Place elements inside the dialog that do not fill up the full screen.
Place an element that can grow and shrink inside the dialog.

### Expected Behavior
The toolbar should have a fixed height, with empty space below the items in the dialog

### Actual Behavior
the header of the dialog shrinks and grows with the content. Once the content fills the screen, the toolbar acts as expected.
This is caused by the flex property of `.v-toolbar`.

### Reproduction Link
<a href="https://codepen.io/RobbeVP/full/QWLNgWV" target="_blank">https://codepen.io/RobbeVP/full/QWLNgWV</a>

### Other comments
Reproduced on: 
macOS: FF, Chrome and Safari
Android: FF, Chrome

**Comment by ProyekRiad** [comment]
For temporary solution, you can wrap toolbar with div

**Comment by AlexVFornazieri** [comment]
Hey @ProyekRiad , @robbevp n all,

I tried the temporary solution above, the "v-toolbar" backed to normal height, but the "v-card-actions" don't go to bottom, i try put ".v-card" and ."v-card__text" with "height: 100%", but just the .v-card make effect don't solving the issue, anyone have any solution for it? Thanks all

![Anotação 2020-05-16 194730](https://user-images.githubusercontent.com/13385315/82131812-9a2e0680-97af-11ea-967a-38195845ccea.png)

**Comment by robbevp** [comment]
Hi @AlexVFornazieri 

Another solution is to add the `flex-grow-0` class to the VToolbar. That is how I worked around this issue.

I can't say why your v-card-actions isn't fully at the bottom. Maybe you need to add a flex-grow property to the content of the dialog? If you can make a codepen reproducing the issue it will be easier to figure out
