### ISSUE TITLE
[Feature Request] DataTable/DataIterator: Allow ItemsPerPage selector to be hidden

### ISSUE THREAD

**Issue by robbevp** [vuetifyjs/vuetify#8607]
### Problem to solve
The DataTable/DataIterator  items per page selector can be disabled, but not hidden.

Hiding the selector would be handy in cases where  we never allow the user to select the number of items, since it might cause confusion to the user.

I realise that it is possible to hide the selector by using `hideDefaultFooter` and recreating the rest of the footer, but that seems a big workaround for such a small thing.

### Proposed solution
Add a property to footer-props called `hideItemsPerPage` to easily hide the selector

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/9531#issuecomment-573313181
