### ISSUE TITLE
[Bug Report] fill-height on v-container makes v-row unusable

### ISSUE THREAD

**Issue by erleiuat** [vuetifyjs/vuetify#8608]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Windows 10

### Steps to reproduce
Click the switch button in the codepen

### Expected Behavior
Rows shouldn't change at all or fill the height of v-container
For better understanding check out this:
<a href="https://codepen.io/erleiuat/pen/BaBzGRm?editors=1010#0" target="_blank">codepen.io/erleiuat/pen/BaBzGRm?editors=1010#0</a>

### Actual Behavior
Rows become columns

### Reproduction Link
<a href="https://codepen.io/erleiuat/pen/eYOzPQj?editors=1010" target="_blank">https://codepen.io/erleiuat/pen/eYOzPQj?editors=1010</a>

### Other comments
The fill-height attribute shouldn't affect the child components but enable to use align="" attributes correctly. 

It shouldn't be necessary to do this for achieving a correct structure, since v-layout is depreciated (I think) or at least not documented anymore.
![image](https://user-images.githubusercontent.com/14804153/63226746-508f9b80-c1de-11e9-80c1-51cbc3495ca7.png)
<a href="https://vuetifyjs.com/en/getting-started/frequently-asked-questions#how-to-center-vertically" target="_blank">vuetifyjs.com/en/getting-started/frequently-asked-questions#how-to-center-vertically</a>

**Comment by pauloddr** [comment]
I just moved to Vuetify 2.0 and am facing the same issue. Cannot use `<v-rows>` inside `<v-container fill-height>`.

**Comment by MrGuiMan** [comment]
Same issue, as it stands, migration to the v2 grid is compromised.

**Comment by DRBragg** [comment]
Also running into the same issue

**Comment by DRBragg** [comment]
FWIW, at least in my case, adding this to my CSS fixed the issue:
`.container.fill-height {
  flex-wrap: wrap;
}
.container.fill-height > .row {
  flex: 1 1 100%;
}`

**Comment by hackinteach** [comment]
Same issue here. using `v-row` inside `<v-container fill-height>` mess up my grid.

**Comment by arminmon** [comment]
Same here.

**Comment by rodrigogs** [comment]
Same here. Why the hell it was closed without any answer?

**Comment by opelsrx** [comment]
fill-height doesnt seem to be in the vuetify 2.x docs. Could it be deprecated?

**Comment by thoni56** [comment]
Also looking for `fill-height` in vuetify docs, at least a search does not turn up anything...

**Comment by hoektoe** [comment]
fill-height breaks the child row on mobile display. Just tested with default google keep template

**Comment by joffff** [comment]
@thoni56 @opelsrx it's not on the Grid system API reference but there's a passing mention in the Usage notes: https://vuetifyjs.com/en/components/grids#usage

**Comment by tomwalsh96** [comment]
Does anyone know of an alternative to fill-height? I want to make my container to be 100% of the viewport, however, I'm only able to set nominal heights of the rows it nests.

**Comment by edwinhageman** [comment]
If you use an extra v-container component everything works as expected.

`<v-container fill-height><v-container class="pa-0 ma-0"><v-row><v-col></v-col></v-row></v-container></v-container>`

**Comment by alibitek** [comment]
Yep, `fill-height` simply doesn't work. 
Using latest release of vuetify 2.2.4
How can I tell a `div` inside `v-col` to fill the entire available height ?

**Comment by adambeck7** [comment]
@alibitek Doubling up the v-container as @edwinhageman suggested works for me. Make sure the parent container has the fill-height on it, not the child.

**Comment by gotenxds** [comment]
Why is this closed ? this is not fixed
