### ISSUE TITLE
[Bug Report] Toolbar or Appbar Extension Slot with Block Buttons

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#8609]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
.

### Expected Behavior
Block prop should make buttons fit in toolbar or appbar

### Actual Behavior
Buttons go infinite in extension slot.

### Reproduction Link
<a href="https://codepen.io/navi3591/pen/QWLNRQq?editors=1010" target="_blank">https://codepen.io/navi3591/pen/QWLNRQq?editors=1010</a>

**Comment by johnleider** [comment]
You have to assign a height of **auto** if you want it to adjust: https://codepen.io/johnjleider/pen/gObKYWW

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
