### ISSUE TITLE
Masking Inputs

### ISSUE THREAD

**Issue by ChavaSobreyra** [vuetifyjs/vuetify#861]
Hi guys. Great library. Are there any plans for built-in support for masking text inputs? I think most serious applications employ masking for phone number inputs and the like.  Given that this will continue to be a need for developers using vuetify, even if built-in support isn't on the roadmap, I think an example on how to integrate with a 3rd party solution would be useful. 

> What will it allow you to do that you can't do today?

Mask inputs

> How will it make current work-arounds straightforward?

All I see right now is a closed issue directing users to get help using 3rd party libraries on gitter.

> What potential bugs and edge cases does it help to avoid?

Helps users to input data correctly the first time without reyling on hints and form errors.

**Comment by johnleider** [comment]
We will be adding this now that it is part of the MD spec.

**Comment by noobkilar** [comment]
It was pretty easy to implement with your textfield. https://text-mask.github.io/text-mask/

So maybe that will help you. Just need to change like 5 line in your core code.

**Comment by snarlynarwhal** [comment]
[Cleave.js](https://nosir.github.io/cleave.js/) seems to be a popular solution to this problem also. Looking forward to this feature!

**Comment by maiconpazin** [comment]
Can anyone share a example of vuetify text input with mask?

**Comment by johnleider** [comment]
@noobkilar What were the lines that you changed? I'll be baking a lot of this into Vuetify, but still want to support cleave.
