### ISSUE TITLE
[Bug Report] Vuetify appends class="v-list-item--highlighted" in autocomplete element dropdown for just removed element

### ISSUE THREAD

**Issue by Cesarevich** [vuetifyjs/vuetify#8615]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
In the codepen link above.
1. Type in the autocomplete's input "Williams"
2. Select Sandra Williams
3. Remove Sandra Williams by clicking Chips "x"
4. Open dropdown and try to select any other name for example Trevor Hansen
Result: From now Sandra Williams has class="v-list-item--highlighted" and all further selected users will be anchored to Sandra Williams in case of big lists this anchoring it is extremely inconvenienced

### Expected Behavior
No class="v-list-item--highlighted" and no anchoring

### Actual Behavior
Do not work like expected

### Reproduction Link
<a href="https://codepen.io/Cesarevich/pen/LYPZwpy?&editable=true&editors=101" target="_blank">https://codepen.io/Cesarevich/pen/LYPZwpy?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
Could not reproduce in latest 2.x version
