### ISSUE TITLE
[Bug Report] CSS for vertical slider height doesn't work

### ISSUE THREAD

**Issue by tomfree** [vuetifyjs/vuetify#8616]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Open codepen and compare slider height to v-card height and see where the prepended icon is in comparison to slider

### Expected Behavior
slider should have height of 800px

### Actual Behavior
slider height does not change

### Reproduction Link
<a href="https://codepen.io/tomfree/pen/GRKjKLZ" target="_blank">https://codepen.io/tomfree/pen/GRKjKLZ</a>

### Other comments
love vuetify!

**Comment by msteller-connyun** [comment]
Just discovered this bug, too.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Comment by timolson** [comment]
Any workaround available?
