### ISSUE TITLE
[Bug Report] v-navigation-drawer: when using clipped and temporary, clipped is disabled

### ISSUE THREAD

**Issue by ShlomitSibony** [vuetifyjs/vuetify#8617]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
https://codepen.io/shlomitsibony/pen/BaBLypv

### Expected Behavior
drawer under the toolbar

### Actual Behavior
drawer not under the toolbar

### Reproduction Link
<a href="https://codepen.io/shlomitsibony/pen/BaBLypv" target="_blank">https://codepen.io/shlomitsibony/pen/BaBLypv</a>

### Other comments
removing temporary attribute will solve it

**Comment by johnleider** [comment]
Unfortunately that is not how they are intended to work. Here is a workaround for your issue but this is not a bug.

https://codepen.io/johnjleider/pen/vYBpZVx

**Comment by CMQNordic** [comment]
Description from official documentation:
A clipped drawer rests under the application toolbar

A little more extensive description that clipped do not work for some combinations of other properties would save lot of time... Possible to update the documentation if this is default behaviour.

**Comment by Yihao-G** [comment]
The workaround above pushes the drawer down. Anything at the bottom of the drawer are unable to see, so at least we also need `:height="`calc(100vh - ${$vuetify.application.top}px)`"`.

And in the latest version (2.3.6), the overlay `z-index` is now 7 rather than 5 in v2.0.7. This darkens the toolbar as well. So we also need to use CSS to change the `z-index` of `v-app-bar` to at least 7.

**Comment by xerzen** [comment]
I had the same problem and I fixed it by using johnleider's solution; That is, adding 'clipped-left app'  in <v-app-bar> props and 'clipped app :style="`margin-top: ${$vuetify.application.top}px`" ' in <v-navigation-drawer> props

**Comment by johnleider** [comment]
This is something we have drastically improving for v3 and will be available in tomorrow's alpha release. With that being said:

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
