### ISSUE TITLE
[Bug Report] VTabs "align-with-title" not working

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#8621]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add "align-with-title" prop to a tabs within a toolbar

### Expected Behavior
The tabs to align with title

### Actual Behavior
The tabs don't align with title

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/WNeGGoW?&editable=true&editors=101" target="_blank">https://codepen.io/thomaskientz/pen/WNeGGoW?&editable=true&editors=101</a>

### Other comments
I used the exact same codepen from the doc : https://vuetifyjs.com/en/components/tabs#align-tabs-with-toolbar-title

**Comment by chanlito** [comment]
Just ran into this as well.
