### ISSUE TITLE
[Feature Request] Bindings to control vertical tab width

### ISSUE THREAD

**Issue by delaneyj** [vuetifyjs/vuetify#8623]
### Problem to solve
I have dynamic content using vertical tabs.  Other components need to line up with these tabs.  Instead  of using normal vue dynamic classes I'm have to do nested selectors to style.  

### Proposed solution
`<v-tabs v-model="tab" vertical :tab-width="250">`

**Comment by johnleider** [comment]
Can you provide an example of what's not working at the moment?

**Comment by delaneyj** [comment]
Sorry this was almost 6 months ago.  Started using Tailwind in the interim.  Thank you for the response.
