### ISSUE TITLE
Vuetify spacing example is broken in docs page

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#8626]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Open first example in codepen. Template is broken, there are ( ) instead of < >.

### Expected Behavior
Should work.

### Actual Behavior
Doesn't work.

### Reproduction Link
<a href="https://vuetifyjs.com/en/styles/spacing" target="_blank">https://vuetifyjs.com/en/styles/spacing</a>

**Comment by MajesticPotatoe** [comment]
fixed in 67cd6f2
