### ISSUE TITLE
[Bug Report] file-input fails to show size when show-size property is applied

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8634]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use codepen.
Click on v-file-input field.
Select File
Observe contents of v-file-input field

### Expected Behavior
v-file-input should display cumulative file size for file(s) selected.

### Actual Behavior
v-file-input does not display cumulative file size for file(s) selected.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/yLBadpx" target="_blank">https://codepen.io/MatthewAry/pen/yLBadpx</a>

**Comment by MajesticPotatoe** [comment]
Your codepen is invalid. You are using `display-size` which is a prop that does not exist. if you change it to `show-size` you do in fact get the size for single and multiple files.

**Comment by MatthewAry** [comment]
Then the documentation needs to reflect that https://vuetifyjs.com/en/components/file-inputs#size-displaying

**Comment by MajesticPotatoe** [comment]
It does now. d937e25
