### ISSUE TITLE
[Bug Report] v-data-table default footer navigation UI wrapping issue on small device 

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#8635]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Change the browser width to 320px (i.e. iPhone 5/SE)

### Expected Behavior
The navigation button "<" and ">" should always be on the same line, and "Rows per page: [10]" should wrap into the next line instead.

### Actual Behavior
navigation button ">" is wrapped into the next line.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/YzKGoaq" target="_blank">https://codepen.io/andrewspy/pen/YzKGoaq</a>

### Other comments
It used to work as expected on Vuetify 1.5.x

**Comment by johnleider** [comment]
Due to limited bandwidth, moving to v2.3.x.

**Comment by linpan** [comment]
@johnleider 
v-footer not adjust 
![image](https://user-images.githubusercontent.com/6077601/120210127-061bc980-c262-11eb-9446-2f6234f7b4f0.png)
![image](https://user-images.githubusercontent.com/6077601/120210149-0ae07d80-c262-11eb-82af-c5f017c7805e.png)
![image](https://user-images.githubusercontent.com/6077601/120210161-0ddb6e00-c262-11eb-9443-ca73b037e8b7.png)
