### ISSUE TITLE
[Feature Request] file-input should have an event that returns file size in bytes and in human readable format

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8636]
### Problem to solve
This will assist with two potential use cases. Since the file-input already tracks file size, it will save the computational overhead and trouble for the programmer to find out the file size value for validation purposes.

The second use case is that it will allow the programmer to have better control over the presentation of the file size value to the end user.

### Proposed solution
Create an event that returns the file size values whenever the contents change.

**Comment by MatthewAry** [comment]
Just noticed that https://vuetifyjs.com/en/components/file-inputs#validation includes an example for validating for size. However, I think that the rules for this input field is a bit of a black box. Without the example I would not have found out that I could get the size this way. It leads me to wonder what else is contained in the return value used for validation. Will this handle file lists too?

**Comment by nekosaur** [comment]
This is not something vuetify is doing. The v-model for v-file-input is simply the `File` instance (or an array of `File` instances in the case of using `multiple`), which includes a `size` property. https://developer.mozilla.org/en-US/docs/Web/API/File

**Comment by MajesticPotatoe** [comment]
You already have access to this info via `@change` event.
+ everything @nekosaur said.

**Comment by MatthewAry** [comment]
It would be nice to not have to recalculate the size when the component is already doing it privately.

**Comment by johnleider** [comment]
You can access this information by using the counter slot:

![image](https://github.com/vuetifyjs/vuetify/assets/9064066/3d5564d8-f32a-467a-b801-3c4aa94e5620)

https://play.vuetifyjs.com/#eNpVj0EOgyAQRa8ymW6rYHRlrEnTY9QuiNKWBIEI2KTGu5cqJrohw/z/Z+bdJ7RDS67GpKPnWGLleG8kc7xuFEA1JsyYpQyfTozQSmbtpcGeJQWY8DQY5cX9FJInQhnvoNVeOT5A76UTRnIo7Vt/Eiu+POQzSukuGsLbYjjFZHB1zLGDK/isG7R61bc43krt4O8rKxIlmKalA/O8m08OZGtrf/BGSQLmCh/klf6QxfmMeVqkWY6xoPj4AX7zZPs=

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
