### ISSUE TITLE
[Bug Report] Over-scrolling on iOS in dark theme reveals white background

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#8638]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Open the [dark layout example](https://vuetifyjs.com/en/examples/layouts/dark) on iOS device, and scroll before/past the content.

### Expected Behavior
over-scrolling background should match the dark theme.

### Actual Behavior
over-scrolling background is white, and ruin the overall dark theme.

### Reproduction Link
<a href="https://www.github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/layouts/dark.vue" target="_blank">https://www.github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/layouts/dark.vue</a>

### Other comments
Not sure if there is a limitation on implementing this on iOS, or if there is a way to prevent "over-scrolling" on iOS so that the white background doesn't ruin the dark theme.

**Comment by jerme404** [comment]
I set a body background color to fix this.

`body { background-color: #2C3033; }`

**Comment by andrewspy** [comment]
@jerme404 Thanks for the quick fix. but I think it should be handled by vuetify internally.

**Comment by euller88** [comment]
This is not exclusive to iOS. I'm using Chrome on a Ubuntu and the same bug happens.

**Comment by hubert17** [comment]
This happens on my Android 11 Chrome v92 Vuetify 2.5.x. A white background is revealing when scrolling.

**Comment by KaelWD** [comment]
The problem with this is then we'll piss off all the people who only want to use vuetify for a portion of their page.

**Comment by KaelWD** [comment]
We're setting `color-scheme: dark` now (#14039), if safari isn't respecting that open an issue on https://bugs.webkit.org/ instead.
