### ISSUE TITLE
[Feature Request] Scroll Bar in full-page desktop app

### ISSUE THREAD

**Issue by MeirionHughes** [vuetifyjs/vuetify#864]
### Steps to reproduce

* open https://vuetifyjs.com/layout/elevation 
* or run vuetify webpack advanced template 

### Versions
"vue": "^2.3.3",
"vuetify": "^0.12.7",

### What is expected ?

scroll-bar should not be visible when there is no overflowing. 
dialogs should not interfere with html padding

### Why is it a problem ? 

I'm trying to use vuetify within electron (full-screen desktop app with fixed header and footer). 

![image](https://user-images.githubusercontent.com/3584509/27768224-f2dfc498-5f05-11e7-9178-5b41429c0fa0.png)

the scroll-bar is not desired here. 

### What is actually happening ?

importing `../../node_modules/vuetify/src/stylus/main` sets 
```
html {   overflow-y: scroll; } 
```
looks like the reset style `ress` is doing it. 

Further, if I override with ``` html {   overflow-y: auto; } ``` I can remove the scroll-bar, but opening any menu appears to add a fixed right margin in place for the scroll-bar (which is hidden) to the body

### Reproduction 

https://vuetifyjs.com/layout/elevation

vuetify webpack advanced template

**Comment by johnleider** [comment]
This is part of the design of Vuetify. You can simply add custom cad to remove the automatic html overflow.

**Comment by grofit** [comment]
Is there ever a benefit to having the scrollbar always there by default? as it seems (from my primitive perspective) that you are more likely to not want `auto` than an explicit `scroll`.

**Comment by mcfarljw** [comment]
I'm also not to certain of the benefit of changing `overflow-y` from `auto` to `scroll`. It actually threw me for a bit of a loop because I thought that I had accidentally added some padding or chrome was being wonky.

![screen shot 2017-07-28 at 5 38 50 pm](https://user-images.githubusercontent.com/4167341/28711895-afd2860c-73bb-11e7-938d-c94de0e66911.png)

**Comment by MeirionHughes** [comment]
Presumably it is a design choice so that the dialogs and side-navs play well with the rest of the UI when used. Its just a shame its hard-coded to the root html element and not a specifiable container element.

**Comment by Rolanddoda** [comment]
I see that scroll even if the page does have content to scroll.Bad thing

**Comment by MeirionHughes** [comment]
yup; single reason I can't use veutify for desktop applications. Could be fixed by having a container, but as it stands I think the slide menus work off body.

**Comment by johnleider** [comment]
You can't use Vuetify because a design decision that can be fixed with 1 line of css is in your way? The scroll bar is part of the reset that we use, https://github.com/filipelinhares/ress and has been debated countless times over the course of Vuetify's life. Both sides have comparable arguments, so it stays as it is, simply because it can be fixed relatively easily.

**Comment by MeirionHughes** [comment]
Perhaps you can document the fix then because its not as simple as switching to auto; the slide menu offsets get borked; at least the last time I tried to "fix" it.

**Comment by johnleider** [comment]
That's a fair comment, something I had not considered.  Not something that we can address before launch, but I think we should at least be able to compensate for it in the future.

**Comment by hughanderson4** [comment]
Furthermore the scrollbar doesn't belong there.  If we are to emulate the UI of a mobile app, the scroll bar belongs between the header and footer, not beside it.

**Comment by johnleider** [comment]
Well that is a different conversation entirely and has implications in itself.

**Comment by hughanderson4** [comment]
On the subject of scrollbar. Suggest to include a nice mobile-style scroll bar in Vuetify suite.

See [link](https://codepen.io/devstreak/pen/dMYgeO) for inspiration.  [Angular.io](https://angular.io/) has a nice mobile-style scroll bar but is a little too skinny of click target.

Thanks for considering it.

**Comment by AlexSHoffman** [comment]
@johnleider could you please suggest why does `pageYOffset `stops working when you make only content tag scrollable? `OffsetTop `stays at 0. Here's an example: https://codepen.io/anon/pen/xYppdQ

**Comment by privateer** [comment]
Was this ever addressed or the solution documented?  I need a "Slack message area" style interface as well with an internal content area scrolling between the elements above (header & toolbar) and the footer at the bottom.  html {overflow: hidden} gets rid of the scroll bars... now how do I get it back on the container that should scroll...

**Comment by AlexSHoffman** [comment]
@privateer it's quite easy to do. See [this comment](https://github.com/vuetifyjs/vuetify/issues/2132#issuecomment-347211864)

**Comment by privateer** [comment]
Thank you Alex.  I'm much closer now.  Do you happen to know if there is a way to have a header area under the toolbar that doesn't scroll?

**Comment by AlexSHoffman** [comment]
@privateer I'm not sure what you're asking, do you mean you need an [extended area](https://vuetifyjs.com/en/components/toolbars#example-app-bar-extension) under the toolbar?

**Comment by privateer** [comment]
Yes.  For example an area for tabs.

**Comment by privateer** [comment]
Basically, I would like to setup a tab component above the scrolling area so the content can be switched.  The content area that scrolls could be cards that are shown or not based on which tab is selected.

**Comment by AlexSHoffman** [comment]
@privateer there are multiple examples in the Vuetify docs. For example, [here's an example](https://vuetifyjs.com/en/components/tabs#example-content) of a toolbar with tabs. There's a few more examples there, you can see the code by clicking the "view source" button above an example

**Comment by privateer** [comment]
Thanks again.  I study that and see if I can get things working the way I am hoping.

**Comment by AlexSHoffman** [comment]
@privateer no problem, if you have any questions, it's better to ask them on [stackoverflow](stackoverflow.com) with a tag `vuetify` or `vuejs`.

**Comment by privateer** [comment]
Okay.  Will do.

**Comment by johnleider** [comment]
The community is an excellent place for help,
https://community.vuetifyjs.com

**Comment by blalan05** [comment]
Fix has been documented in the FAQ section.
