### ISSUE TITLE
Can not type in text field when it is behind a bottom-sheet

### ISSUE THREAD

**Issue by kwindo** [vuetifyjs/vuetify#8640]
This is basically a copy of an issue I reported back in May which was closed for being a duplicate of an other issue which was closed for being a duplicate. I think all related issues have been closed by now but, sadly, the issue seems to still be there. If this is a duplicate again or if I'm missing something I sincerely apologise.

Previous closed tickets
https://github.com/vuetifyjs/vuetify/issues/7286
https://github.com/vuetifyjs/vuetify/issues/7209
https://github.com/vuetifyjs/vuetify/issues/6892

### Versions and Environment
**Vuetify:** 2.0.7
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
https://codepen.io/kimsanka/pen/MdVvWX

### Expected Behavior
Being able to use a text field on a page behind the bottom sheet when the bottom sheet is showing and hide-overlay and persistent are true.

### Actual Behavior
When the bottom sheet is showing (with hide-overlay and persistent on true) it is not possible to type text into a text field on the page behind the bottom sheet.

### Reproduction Link
<a href="https://codepen.io/kimsanka/pen/MdVvWX" target="_blank">https://codepen.io/kimsanka/pen/MdVvWX</a>

**Comment by shelakel** [comment]
I agree this behavior (document level capturing of focusin event per https://github.com/vuetifyjs/vuetify/issues/6892) is unexpected considering the `v-bottom-sheet` is marked as `hide-overlay` and `persistent`.

**Comment by KaelWD** [comment]
bottom-sheet with hide-overlay should probably imply `:retain-focus="false"`, and there's also a new problem of `persistent` being ignored completely for some reason.

**Comment by swirlingsand** [comment]
Same for me!
https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/eYmEgxY?&editable=true&editors=101

**Comment by jaxn** [comment]
Maybe the appropriate fix to this issue is to make `retain-focus` default to `false`.

Per the [Material spec for bottom sheets](https://material.io/components/sheets-bottom/#usage):

> **Standard bottom sheets** display content that complements the screen’s primary content. They remain visible while users interact with the primary content.
> **Modal bottom sheets** are an alternative to inline menus or simple dialogs on mobile and provide room for additional items, longer descriptions, and iconography. They must be dismissed in order to interact with the underlying content.

As an aside, the music player example in the Vuetify docs should probably demonstrate the **Standard bottom sheet** behavior since that is the exact use case the Material docs provide.

**Comment by jaxn** [comment]
This is mostly fixed for me now, except for one specific case.

When there is a `<v-card @click>` inside a `<v-bottom-sheet>`, the user is unable to click to focus a `<v-text-field>`.

Here is a simple [codepen repro demonstrating the issue](https://codepen.io/jaxn615/pen/Yzqzjxw)

That codepen demonstrates that when you put the `@click` on the `v-card-text` instead of the `v-card` itself, everything works as expected.  You can click on the `v-checkbox` either way.

**Comment by johnleider** [comment]
This is resolved in v3

https://play.vuetifyjs.com/#eNrNVcFu2zAM/RVOl7ZAZKPodgnSLtuwr6h7cGwa0WJLgiRnGYL8+yjZSRWlaJP20pv1KL5HUs/S45b90Dpb98imbOaw023p8KGQALM1L7UOn2HRlUKOq7CulHQEoTmAATbqbwQEyOHG8UZgWwPRV7hUbY3mvmC/pUMDPgxLNAgFgzxmy/d0bylUS6xWC7UBKlPV2BJ31Ypq9as0NZG25SJg8wCCkrSvotD3cwT3Q6Ec0RwTp2UslHOq43aJ6OIQgJA2hTQaK6xDmeBTWxnRkVBTthYLdhyViocCeClFVzqholJDduifr8u2R+Jwpk8ojmoehke9wDAaysCNLmWNNdzDl/130mmUF8724WfoG0Lf4H1BTcH1MGynYKC58dN9zolnfEq5H/YrFVCCpSBUbWktbbX9gjvhWuS3tPvQxljOLPebT9tIanopdnzKBMbHfOSe6P952UBIJ/oZTXOpXV61w1teOj3I9xgoZbnYUBdb/nMbLqJILmaPHS5vvxiu9cSuM+8g7YAs1w+3vui0Mg62YLCBHTSGTuiKXoqrYdIkY914NGF2tO062O/mOXy4LMe4NxiFaThBjXTYhA1CVKPO/lgl6SXaeoZiDNiCTSEgHqMC/LpgS+e0neZ5VUtKo0tPrE0m0eVSd/mctuWml050yGvVze+yu+xrXtO/E8MZ2o4v6Mq3aIikYJNIxonm3xlS486gcPttkBgxTg+P9Ron3DkJrtFwgzQ8g+bclpK0uK0kdNKaV98VckcDb4Vc2WTWlQ1zftwX+bGeA5unevKKuwkLhZL0kMGe/gMxP42k

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
