### ISSUE TITLE
[Feature Request] Support Expansion Panel opening up/above the header element

### ISSUE THREAD

**Issue by SirLamer** [vuetifyjs/vuetify#8641]
### Problem to solve
Expansion Panel content can only be expanded in the downward direction. It might be more meaningful in some cases for it to expand upward.

In my case, the "content" area is an activity history on the record summarized in the "header" element. I would prefer for the most recent activity records to appear immediately adjacent to the header, with UI elements for adding comments or updating the status appearing right there. I want the newest and most relevant info to appear nearest to the header element, and the oldest content to appear farthest. I could also reverse sort the content list with the newest data at the top but this is not intuitive to most people.

### Proposed solution
Add a boolean property to make the expansion panel content appear above the header instead of below. This could introduce some scroll tracking issues for cases where the content length is long (header element could be pushed down below the browser view). This could be resolved automatically by tracking/scrolling with the header element or by leaving this to the developer to be resolved per a method they choose (ignore/accept, apply programmatic scroll effect, etc.).

**Comment by KaelWD** [comment]
This seems like a niche use-case that can be resolved easily with a few lines of your own css, and is not a part of the material design specification or any similar frameworks that I know of. 

<details>

```css
.v-expansion-panel {
  display: flex;
  flex-direction: column;
}

.v-expansion-panel-header {
  order: 1;
}

.v-expansion-panel-content__wrap {
  padding: 16px 24px 0;
}
```
</details>

> scrolling with the header element

Not feasible due to the many ways the component could actually be used - #3947
