### ISSUE TITLE
[Feature Request] Reorderable List 

### ISSUE THREAD

**Issue by felix-pb** [vuetifyjs/vuetify#8645]
### Problem to solve
It would be a super useful component.

### Proposed solution
Something similar to the Material Design guidelines:
https://material.io/design/components/lists.html#types
(see "Reorder" example at the end of the "Types" section)

**Comment by mahapo** [comment]
You can do it easily with https://github.com/SortableJS/Vue.Draggable.

Just wrap the list item element with draggable the element

**Comment by YipingRuan** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
