### ISSUE TITLE
Nuxt: time picker does not switch to minutes selection automatically

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#865]
### Steps to reproduce

1. Click on "Picker in dialog" text field
1. Select random hour

### Versions
Versions installed by ```vue init vuetifyjs/nuxt``` command

### What is expected ?
After selecting an hour, time picker should switch to minutes selection

### What is actually happening ?
![peek 2017-07-02 15-58](https://user-images.githubusercontent.com/339596/27769980-571c98b2-5f3f-11e7-94e3-2d6716cb58ff.gif)

### Reproduction Link
Reproduction repository https://github.com/Darkside73/vuetify-time-picker-nuxt

**Comment by johnleider** [comment]
This is not NUXT, this is a mobile issue.
