### ISSUE TITLE
[Bug Report] Unable to create tfoot elements in VDataTable

### ISSUE THREAD

**Issue by Yihao-G** [vuetifyjs/vuetify#8651]
### Environment
**Vuetify Version:** 2.0.9
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1. Create a `tfoot` or `tr` element, or `td` or `th` elements inside `footer` slot in `VDataTable`
2. The element is not appended inside `table`
3. Add `hide-default-footer` prop
4. The element is still not appended inside `table`

### Expected Behavior
The element should be appended inside its `table` element.

### Actual Behavior
This element got appended after `.v-data-table__wrapper`

### Reproduction Link
<a href="https://codepen.io/gaosong2101/pen/LYPbROW" target="_blank">https://codepen.io/gaosong2101/pen/LYPbROW</a>

**Comment by nekosaur** [comment]
This is not a bug. The `footer` slot lives outside of the `<table>` element and that is by design. You can use `body.append` slot to append rows to the end of the `<tbody>` element for a similar functionality.

**Comment by Yihao-G** [comment]
@nekosaur Thank you for your reply.

`body.append` only appends elements inside `tbody`. In 1.5.x, `footer` slot was used for appending `tfoot` element inside `table`, adjacent to `tbody` (see #1172 and #1190). Is this still doable in 2.0?

**Comment by jsshapiro** [comment]
When implementing drag-and-drop, you want the drag/drop behavior to apply to everything in TBODY, but nothing in THEAD/TFOOT. The new behavior doesn't break that, but...

The problem with sticking the footer slot outside that table is that it stops being possible to get aligned columns in the footer area. This is an unjustified and undocumented regression in presentation capability. The notion of having top/bottom slots seems like a good idea. That's not the same concept as the footer slot, and it doesn't replace the need for TFOOT.
