### ISSUE TITLE
[Bug Report] Vertical v-divider is not displayed when inside div

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#8656]
### Environment
**Vuetify Version:** 2.0.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
See reproduction link.
If you remove <div id="parent"> then v-divider is shown but it breaks the text.

I found out that if you set display: inline to vertical v-divider then it works.

### Expected Behavior
Should display vertical divider without setting it to inline level block.

### Actual Behavior
Vertical divider is not shown.

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/BaBQZjL?&editable=true&editors=101" target="_blank">https://codepen.io/milost1982/pen/BaBQZjL?&editable=true&editors=101</a>

**Comment by navi35** [comment]
Please try like this

https://codepen.io/navi3591/pen/ZEzBddV

**Comment by johnleider** [comment]
This is resolved as of the latest version.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Kruemmelspalter** [comment]
> Please try like this
> 
> https://codepen.io/navi3591/pen/ZEzBddV

Your codepen link sadly died, so people have no idea what the solution is

**Comment by diehardy** [comment]
> > Please try like this
> > https://codepen.io/navi3591/pen/ZEzBddV
> 
> Your codepen link sadly died, so people have no idea what the solution is

You died too :(
