### ISSUE TITLE
[Bug Report] DataTable hide-default-footer is not removing default items-per-page

### ISSUE THREAD

**Issue by timo-reymann** [vuetifyjs/vuetify#8657]
### Environment
**Vuetify Version:** 2.0.9
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
Open the fiddle, you will see the default amount of items: 10, but in the list there are 17 items. 
If you add items-per-page=-1  you get all items

### Expected Behavior
hide-default-footer should remove the default amount of items per page (10) and set the items per page to -1 to show all

### Actual Behavior
hide-default-footer keeps the default amount of items per page

### Reproduction Link
<a href="https://codesandbox.io/s/vue-with-vuetify-eagles-v0y73" target="_blank">https://codesandbox.io/s/vue-with-vuetify-eagles-v0y73</a>

**Comment by Yihao-G** [comment]
I think it's as expected https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0 since 2.0

> hide-actions prop has been renamed to hide-default-footer. **Also it no longer changes the visible items per page**

**Comment by timo-reymann** [comment]
@Yihao-G Okay, then it is intended this way. But there should be something in the docs mentioning this, because i would presume that if there is no visible pagination there should be no limiting of the visible items.

**Comment by KaelWD** [comment]
Pagination can be managed externally, so there has to be a way to remove the default controls without affecting behaviour.

**Comment by timo-reymann** [comment]
@KaelWD As far as i know, with 1.5.x external pagination was already possible, and the default behaviour of hide-default-footer was that all items was displayed. 

So this would be a step backward ...

**Comment by nekosaur** [comment]
It has simply been made more explicit. If you want to show all items, use `:items-per-page="-1"`

**Comment by timo-reymann** [comment]
@nekosaur Yeah i have done that for now, but i see that more like a work around than a real solution ...

**Comment by nekosaur** [comment]
It is the official way of doing it.
