### ISSUE TITLE
[Feature Request] Provide event when v-snackbar closes due to timeout

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#8658]
### Problem to solve
It would be usable if v-snackbar could notify when it's closed due to timeout. I'd like to perform additional tasks when this happens.

### Proposed solution
Raise an event when v-snackbar is hidden due to timeout.

**Comment by coyotte508** [comment]
For now you can sort of use the `input` event, with the `false` parameter.

**Comment by MajesticPotatoe** [comment]
`@input` is the proper way to handle this.

**Comment by johnleider** [comment]
Keep in mind this will probably be deprecated in the future in favor of @change.

**Comment by KickButtowski80** [comment]
In my humble opinion, using input as an event name is odd. Does not it make more sense to use change as the event? why the event was named input?

**Comment by coyotte508** [comment]
Because in vue 2 `v-model` is implemented with a combination of `value` prop and `input` event
