### ISSUE TITLE
[Bug Report] Vuetify calendar events don't change in color

### ISSUE THREAD

**Issue by jessielaf** [vuetifyjs/vuetify#8659]
### Environment
**Vuetify Version:** 2.0.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a v-calendar with events. Edit the color for the calendar

### Expected Behavior
The calendar's events turn into the color passed to the v-calendar element

### Actual Behavior
Events stay black

### Reproduction Link
<a href="https://codepen.io/Jessielaff/pen/rNBWwLr" target="_blank">https://codepen.io/Jessielaff/pen/rNBWwLr</a>

**Comment by iToshk** [comment]
You can use `:event-color` like this
https://codepen.io/itoshk/pen/WNeRdNM
@jessielaf

**Comment by jessielaf** [comment]
@iToshk this works thanks! Although the playground in the documentation suggests its the color attribute: https://vuetifyjs.com/en/components/calendars. Thanks though!

**Comment by ClickerMonkey** [comment]
The color attribute controls the color of the button and header for the current day/weekday.
