### ISSUE TITLE
[Bug Report] v-data-table using v-slot:body no-data-text not show in electron-vue

### ISSUE THREAD

**Issue by HobaiRiku** [vuetifyjs/vuetify#8660]
### Environment
**Vuetify Version:** 2.0.9
**Vue Version:** 2.5.16
**Browsers:** Chrome 76.0.3809.100, Other
**OS:** Mac OS 10.14.6, Windows

### Steps to reproduce
1.  create an electron-vue project.   
2.  add vuetify.   
3.  use v-data-table and use v-slot:body to replace the content.   
4.  empty the table's items.

### Expected Behavior
the no-data-text will show when there are no items.

### Actual Behavior
the no-data-text is missing

### Reproduction Link
<a href="https://github.com/HobaiRiku/vuetify-v-data-table-electron-test" target="_blank">https://github.com/HobaiRiku/vuetify-v-data-table-electron-test</a>

### Other comments
 when use v-slot:body:
![image](https://user-images.githubusercontent.com/26238803/63442486-c5c0d200-c465-11e9-8c36-cce4981a2ecf.png)
when not use:
![image](https://user-images.githubusercontent.com/26238803/63442613-fdc81500-c465-11e9-9ff7-e0e9511788ae.png)

**Comment by nekosaur** [comment]
`body` slot overwrites all the internal rendering of data-table. it is up to you to display a no data message. This should probably be emphasized more in documentation.

**Comment by HobaiRiku** [comment]
> `body` slot overwrites all the internal rendering of data-table. it is up to you to display a no data message. This should probably be emphasized more in documentation.

But in version 1.x, it is simple to custom the table content without this problem, now using 2.x how can I do this, can you help me, thank!

**Comment by HobaiRiku** [comment]
Oh, i can write a custom 'no-data-text' in `<tbody>`, solved.

**Comment by nekosaur** [comment]
There was no `body` slot in 1.x. In 99% of cases you should be using the `item` or `item.<name>` slots instead of body. Only if you need access to `<tbody>` should you use `body` slot.

**Comment by HobaiRiku** [comment]
@nekosaur Thank a lot! I had not noticed that `item.<name>` slots API, sorry, this version is smooth！

**Comment by vijay-appirio** [comment]
> Oh, I can write a custom 'no-data-text' in `<tbody>`, solved.
> But, it is better to have an API to use.

How can we write 'no-data-text' on tbody? I tried but not worked. Can you please write some example here?

**Comment by HobaiRiku** [comment]
As described by @nekosaur : 

> `body` slot overwrites all the internal rendering of data-table. it is up to you to display a no data message. 

it means you need to write your own table display by HTML and CSS on your own because if you use the API of body slot, other slots will be ignored. 

it is recommended to use item slot and no-data slot separated, and no need to use body slot in 2.x version, t-body is used in 1.x to custom table item.
see my test: https://github.com/HobaiRiku/vuetify-v-data-table-electron-test/blob/master/src/renderer/components/LandingPage.vue
