### ISSUE TITLE
[Feature Request] VDataTable Expose row mouse listeners

### ISSUE THREAD

**Issue by ivaneliasoo** [vuetifyjs/vuetify#8663]
### Problem to solve
When trying to show/hide actions when mouse enter or leave had to use native events but this way I cant access item object data

### Proposed solution
It would be really helpful if VDataTable exposes mouse listeners, for example to show custom actions when over and hide them when leave.

<v-data-table
    :headers="headers"
    :items="desserts"
    :items-per-page="5"
    @mouseover:row="showActions= $event.rowColumnId" ></v-data-table>

**Comment by jacekkarczmarczyk** [comment]
Related (duplicate?): https://github.com/vuetifyjs/vuetify/issues/8643

**Comment by jacekkarczmarczyk** [comment]
Related (duplicate?): https://github.com/vuetifyjs/vuetify/issues/8643

**Comment by ivaneliasoo** [comment]
Yes, I think #8643 Will be enough
