### ISSUE TITLE
[Bug Report] v-tab getting more space in mobile view

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#8666]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Open in mobile view.
2. Check the space between window to active tab

### Expected Behavior
No more space between window to active tab

### Actual Behavior
In mobile getting more margin 

### Reproduction Link
<a href="https://codepen.io/ksankumar/full/bGbBjMr" target="_blank">https://codepen.io/ksankumar/full/bGbBjMr</a>

**Comment by ksankumar** [comment]
![Screen Shot 2019-08-21 at 3 35 44 PM](https://user-images.githubusercontent.com/3350098/63462868-dd7a6500-c429-11e9-82ea-db0adca3d65d.png)

**Comment by navi35** [comment]
It has already opened #8294 :)

**Comment by johnleider** [comment]
This is part of spec and nothing related to #8294

https://material.io/components/tabs/#scrollable-tabs
