### ISSUE TITLE
[Feature Request] Show minutes in slot boundaries v-calendar

### ISSUE THREAD

**Issue by Larissagilliane** [vuetifyjs/vuetify#8668]
### Problem to solve
If my v-calendar slots have a number of minutes that it is different than 60, the time doesn't appear at the slots boundaries.

### Reproduction Link
At this example my minutes intervals have 45 as value.

https://codepen.io/larissagilliane/pen/mdbOjme

### Proposed solution
A solution is to show every value that exists at the slot boundaries, this solution will turn easier to discover the period of each block.

**Comment by ClickerMonkey** [comment]
The default behavior will be changed shortly, but for future reference there's an existing prop `show-interval-label` that accepts a function given a timestamp and must return true or false for determining if a label should be displayed.
