### ISSUE TITLE
Text Field with action (button) on the left or right.

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#867]
Hi, I think it would be nice to have a button next or before a text field. 

I am currently doing it like : 

```
<v-layout row>
  <v-flex p>
    <v-btn flat icon>
      <v-icon class="primary--text">add</v-icon>
    </v-btn>
  </v-flex>
  <v-flex xs12>
    <v-text-field label="Services" name="Services" hint="Ex. Consultation" type="text" ></v-text-field>
  </v-flex>
</v-layout>
```

But the button is awkwardly positioned. 

![selection_133](https://user-images.githubusercontent.com/8638243/27780607-864cc63a-5ffc-11e7-8b99-0c8f02e0a477.png)

![selection_134](https://user-images.githubusercontent.com/8638243/27780640-b611fed0-5ffc-11e7-92bb-820b11cb830e.png)

![selection_135](https://user-images.githubusercontent.com/8638243/27780661-dae63b90-5ffc-11e7-8177-46a03aad168c.png)

**Comment by johnleider** [comment]
I have a feature I'm working on that will give you access to a scoped slot, however, the way that you show above will not be possible as there is only so much space allocated for a prepended or appended icon.

**Comment by jofftiquez** [comment]
Thanks @johnleider any solution/improvement will be much appreciated.

**Comment by johnleider** [comment]
After careful consideration, I have decided that this should be handled with the grid and not a feature that we can support currently.

**Comment by psychonetic** [comment]
@jofftiquez Did you find a good solution?
I am doing it with pt-3
 ```
   <v-flex x1 class="pt-3">
     <v-btn dark color="secondary" @click="removeTarget(target)">Remove</v-btn>
    </v-flex>
```
which looks a bit better.

**Comment by takotuesday** [comment]
Any update on this? Seems like a relevant feature for any UI

**Comment by psychonetic** [comment]
@takotuesday As @johnleider mentioned, it should remain to the grid and the issue is already closed. So I guess there won't be an update.

**Comment by johnleider** [comment]
Not to continue this, but in the form refactor (1.1), I've already added functionality that supports this behavior.

**Comment by takotuesday** [comment]
@johnleider is it possible to leverage the capabilities in the form component? Looking at the grid, its a bit confusing as to the appropriate syntax for achieving the desired result. @psychonetic's solution:
```html
  <v-flex x1 class="pt-3">
    <v-btn dark color="secondary" @click="removeTarget(target)">Remove</v-btn>
   </v-flex>
```
does not include the `v-text-field`, or its wrapping `v-flex`. Is the above snippet within the `v-text-field`'s `v-flex` or outside? This didn't seem to work in all cases, especially with icons.

**Comment by Trimakas** [comment]
bump.. any solution to this?

**Comment by johnleider** [comment]
Already accounted for in 1.1. You can monitor progress on the
refactor/input-controls branch

**Comment by jofftiquez** [comment]
@johnleider thanks!

**Comment by mkpaz** [comment]
So, can someone, please, share solution for this issue? It's exactly the same in 1.5.9.

**Comment by douglasg14b** [comment]
Kind of a shame this isn't a feature :(

Looking for the same solution that pretty old libs like Semantic-UI [have](https://semantic-ui.com/elements/input.html#action), where they let you attach buttons to inputs in the same way you can make a button group. You can attach dropdowns, buttons, really anything to anything else this way: 

![image](https://user-images.githubusercontent.com/1400380/58228638-3419bb00-7ce4-11e9-81e5-ac6d5c387137.png)

**Comment by gorsat** [comment]
Looking for the same thing. Such a basic feature. Is there really no good solution for this in vuetify?

**Comment by jofftiquez** [comment]
@gorsat  I created a custom input using [v-input](https://vuetifyjs.com/en/components/inputs#input) like:

```
<v-input>
  <input type="text">
  <button>Custom button</button>
</v-input>
```

**Comment by gorsat** [comment]
Thanks @jofftiquez  But that's not what I'm trying to do. I'd like to be able to do something like this:

![image](https://user-images.githubusercontent.com/10043170/59288216-1aef9480-8c28-11e9-8046-6b0e78b1391f.png)

...where that area in the middle is a text field used for either display or input. This is trivially easy to do in bootstrap-vue. But in vuetify, I can't seem to do better than this: 

![image](https://user-images.githubusercontent.com/10043170/59289259-77ec4a00-8c2a-11e9-8075-79e885a5585b.png)

So I'm either missing something obvious about how to use vuetify or, imho, there is a basic feature missing (having to do with grouping). I think that's what this issue thread is about. 

While I'm at it, I also want to reemphasize something the OP pointed out which is the inherently awkward layout of buttons with text fields. This is how they layout by default (each in a v-flex within a v-layout row): 

![image](https://user-images.githubusercontent.com/10043170/59289452-f648ec00-8c2a-11e9-92d5-b8ecd7af633d.png)

And there is no obvious way to get them to align vertically (no combo of align-xxx seems to do it). Isn't this just a bug?

**Comment by douglasg14b** [comment]
@gorsat  Pretty much.

**Comment by jofftiquez** [comment]
> trivially

Hello @gorsat that's the best you can have as of now. You really have to adjust things using CSS to achieve your desired design.

**Comment by Sushi2all** [comment]
I also like the Semantic-UI style, but Vuetify is explicitly based upon the Material Design specification, which clearly [does not consider such a design](https://material.io/design/components/text-fields.html).

**Comment by douglasg14b** [comment]
@Sushi2all

You are right, Vuetify is *based* on material design. However, this doesn't mean Vuetify is *restricted* by it.

Plenty of large material frameworks make available alternative, or additional styling, alongside material styling. Recognizing that flexibility and extendability for it's users is more valuable than strict, and unyielding, adherence to the current implementation of Google's Material Design Framework. Sometimes in the way of common, loved, features found and shared between in popular frameworks like Bootstrap, Semantic, or Foundation.

Now, I'm not claiming that Vuetify doesn't recognize the value on flexibility. Just that your argument isn't particularly valid given that Vuetify, as a framework, isn't exactly a Material purist to begin with.

**Comment by Alizadeh118** [comment]
https://jsfiddle.net/alizadeh118/whsfpkub/1/
Hope it helps

**Comment by nlien** [comment]
Here's an alternative for you:
https://codepen.io/nilslien/pen/KKKxxYJ

**Comment by armando25723** [comment]
this is the prettiest solution I've found:
`<v-text-field
                                v-model="search"
                                label="Nombre"
                                hide-details
                                style="margin-right: 15px; max-width: 460px"
                        >
                            <template slot="append">
                                <v-btn outlined style="margin-bottom: 6px" @click="getDataFromApi">
                                    <v-icon left>mdi-magnify</v-icon>
                                    Buscar</v-btn>
                            </template>
                        </v-text-field>`

**Comment by zd87** [comment]
Another solution
https://codepen.io/zd87/pen/rNVNYPR

**Comment by Dhauzur** [comment]
Another solution
`			<v-autocomplete
				v-model="schedulePersonSelect"
				:items="scheludePersons"
				label="Programa"
				outlined
				filled
				dense
				append-icon="mdi-ballot-recount-outline"
				class="mr-0"
			>
				<template v-slot:append>
					<v-btn icon class="mr-0 ml-2 mb-1 p-0">
						<v-icon>mdi-plus</v-icon>
					</v-btn>
				</template>
			</v-autocomplete>`

**Comment by szeref** [comment]
How can I stop the event propagation?
The v-autocomplete list opens when I click on the button.
I tried @click.stop, @click.native.stop, event.stopPropagation(), return false; None of them worked... :(

**Comment by douglasg14b** [comment]
@johnleider Shouldn't this be re-opened?
