### ISSUE TITLE
[Documentation] XS Breakpoint for v-col

### ISSUE THREAD

**Issue by wonderf** [vuetifyjs/vuetify#8672]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
see at API window

### Expected Behavior
Write something to use xs breakpoint.

### Actual Behavior
In v-card doc I am find magic combination v-bind="{ [`xs${card.flex}`]: true }"

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/grids" target="_blank">https://vuetifyjs.com/en/components/grids</a>

**Comment by squalsoft** [comment]
xs = cols
xs3 (xs="3") will be
<v-col cols="3">

**Comment by MajesticPotatoe** [comment]
as stated above, when no breakpoints are provided, `xs` is assumed, and `cols` is essentially replaces this.
related: #9233
