### ISSUE TITLE
[Bug Report] Material Icon do not display when name ends with digits

### ISSUE THREAD

**Issue by valleen** [vuetifyjs/vuetify#8673]
### Environment
**Vuetify Version:** 1.5.18
**Vue Version:** 2.6.6
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
<v-list dense two-line>
      <v-list-tile avatar>
        <v-list-tile-avatar>
          <v-icon color="white" large>battery_80</v-icon>
        </v-list-tile-avatar>

        <v-list-tile-content>
          <v-list-tile-sub-title>Battery</v-list-tile-sub-title>
          <v-list-tile-title>80%</v-list-tile-title>
        </v-list-tile-content>
      </v-list-tile>

      
    </v-list>

### Expected Behavior
Display of all material icons

### Actual Behavior
Do not display material icons ending with digits, like battery_20, battery_80...etc.

### Reproduction Link
<a href="https://jsfiddle.net/jbhuez17/3/" target="_blank">https://jsfiddle.net/jbhuez17/3/</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/google/material-design-icons/issues/786
