### ISSUE TITLE
[Feature Request] Open On Hover Menu Activator

### ISSUE THREAD

**Issue by NAVI-91** [vuetifyjs/vuetify#8674]
### Problem to solve
Is it possible to make same style behavior open-on-hover and click on menu.

https://codepen.io/NAVI-91/pen/mdbOZGE?editors=1010

Click

![image](https://user-images.githubusercontent.com/17800881/63501671-ba58bf80-c4d4-11e9-90ea-c7b1f0aef456.png)

Hover

![image](https://user-images.githubusercontent.com/17800881/63501709-ce042600-c4d4-11e9-9466-f8951755686b.png)

as you can see, activator has different styles on hover and click. Could you make same :)

### Proposed solution
Make same style for activator on open hover and click

**Comment by johnleider** [comment]
You can do this now, with a small tweak: https://codepen.io/johnjleider/pen/NWPYmBv?editors=1010

I think passing down the active state of the menu through the activator slot would be a good direction for this request.
