### ISSUE TITLE
[Bug Report] Issue with using prepend-icon as slot for v-list-group (slot name should be kebab-case instead of camelCase)

### ISSUE THREAD

**Issue by chiragshahklc** [vuetifyjs/vuetify#8676]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
I am trying to set prepend-icon dynamically. I have name of icon into `data` . I want it to set using slot because I want to change color of icon.

### Expected Behavior
`v-slot:prepend-icon` should make it work.
Though workaround as nekosaur suggested is working
```
<template #prependIcon>
            <v-icon class="red">{{iconName}}</v-icon>
</template>
```

### Actual Behavior
`v-slot:prepend-icon` shows nothing. it doesn't work that way.

### Reproduction Link
<a href="https://codepen.io/chiragshahklc/pen/xxKRvQR" target="_blank">https://codepen.io/chiragshahklc/pen/xxKRvQR</a>

**Comment by ositowang** [comment]
Any progress on this bug?

**Comment by jacekkarczmarczyk** [comment]
@ositowang https://github.com/vuetifyjs/vuetify/pull/9788#issuecomment-571424610 (tldr - v3.x)
