### ISSUE TITLE
[Bug Report] Nested expansion-panels get active class of parent

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#8677]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create an `expansion-panels` component with few panels,
In one of the panels content, put another `expansion-panels` component with at least one panel.

### Expected Behavior
When opening the parent panel, nested panels height is expected to be as normal as other panels height: 48px

### Actual Behavior
nested panels get the class behaviour of their parent, `.v-expansion-panel--active`, resulting change in their min-height from *48px* to *64px*

![nestedExpPanBug](https://user-images.githubusercontent.com/13683050/63511015-be8ed800-c4e8-11e9-9164-f18c35b082c9.PNG)

### Reproduction Link
<a href="https://codepen.io/Tzahile/pen/QWLdLzE?editors=1010" target="_blank">https://codepen.io/Tzahile/pen/QWLdLzE?editors=1010</a>

**Comment by andreydos** [comment]
I catch something like this in my project too and need some help :)

<img width="498" alt="123" src="https://user-images.githubusercontent.com/13402400/63690942-953ab880-c816-11e9-816e-6ff16f61f124.png">
<img width="412" alt="456" src="https://user-images.githubusercontent.com/13402400/63690954-99ff6c80-c816-11e9-85d1-1428b41ef6ad.png">

**Comment by andreydos** [comment]
My issue was fixed after manual update to 2.0.10 version (I had 2.0.7 previously). Thanks

**Comment by pranavcbalan** [comment]
The following style is getting applied to all nested panel elements since the parent is active.

`.v-expansion-panel--active .v-expansion-panel-header {
    /* min-height: 64px; */
}`


It needs to update with the direct child selector to avoid selecting nested expansion panel elements.

`.v-expansion-panel--active > .v-expansion-panel-header {
    /* min-height: 64px; */
}`
