### ISSUE TITLE
[Feature Request] Vertical Alignment

### ISSUE THREAD

**Issue by jacklp** [vuetifyjs/vuetify#8682]
### Problem to solve
Using the new grid layout system how do we position a button at the bottom left corner of the page when there is a large gap between the main content at the top, surely we are not expected to use v-spacer and loads of rows to pad out the space. We used to have v-layout and the 'column' attribute to help us vertically align things... now I'm kind of lost with how to approach this. You have no example of using the spacer on the grid list page

### Proposed solution
show a better vertical align demo and show a v-spacer demo on the grid list page

**Comment by pauldaiko** [comment]
try class="flex-column" on a v-row

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
