### ISSUE TITLE
[Documentation] Tabs Custom icon demo probably has a bug

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8688]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
If you look at the code for the demo it seems to be using the `<v-tabs-items>` component to show tabs with text contents. For some reason, no text is being shown in this demo even though it looks like the component is set up to actually show the text

### Expected Behavior
Demo should show text under the tabs

### Actual Behavior
Text is missing from under the tabs.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tabs#custom-icons" target="_blank">https://vuetifyjs.com/en/components/tabs#custom-icons</a>

### Other comments
This might not be simply a documentation bug but actually a bug with tabs themselves. Any thoughts?

**Comment by MajesticPotatoe** [comment]
Just an error in the example. `v-tabs-items` should exist outside the `v-tabs` and they would be bound to the same `v-model` like in the grow example <https://vuetifyjs.com/en/components/tabs#grow>.

I'll just remove the text portion. not really needed as the props focus is on the arrows.
