### ISSUE TITLE
Select overwrap another select

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#869]
### Steps to reproduce
1. Open [codepen](https://codepen.io/cawa-93/pen/gRzOWj?editors=1010#0)
2. Open second select
3. Open open first select

### What is expected ?
Second select close when open another

### What is actually happening ?
Select stay opened

### Reproduction Link
https://codepen.io/cawa-93/pen/gRzOWj?editors=1010#0

**Comment by johnleider** [comment]
This has already been fixed for next release.
