### ISSUE TITLE
[Bug Report] Incorrect dropdown position

### ISSUE THREAD

**Issue by hyvyys** [vuetifyjs/vuetify#8690]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Use v-select with `label` and `items` props.

### Expected Behavior
I want to display select dropdown below the opener (or above, when no space is available below), like a classic native select and many of its replacements do. This could be opt-in, to avoid breaking changes.

### Actual Behavior
The dropdown opens centered above the opener, almost like the native select in Edge. Clumsy to say the least, and practical only in small viewports. Otherwise the user can forget what the label says (as it is not visible any more) before she decides on the option.

### Reproduction Link
<a href="https://codepen.io/hyvyys/pen/oNvBBKX" target="_blank">https://codepen.io/hyvyys/pen/oNvBBKX</a>

**Comment by Larissagilliane** [comment]
The v-select has a property called "attach" that has 'false' as default value, you can set this props as 'true' and your dropdown will be shown below the opener.
