### ISSUE TITLE
[Bug Report] TypeError: Cannot read property 'dark' of undefined

### ISSUE THREAD

**Issue by Anubarak** [vuetifyjs/vuetify#8700]
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Mount a component in runtime with Vuetify components v-dialog inside it and see this error in the console

### Expected Behavior
No error in the console and a proper theming of the dialog

### Actual Behavior
An error in the console and no proper theming of the dialog

### Reproduction Link
<a href="https://codesandbox.io/embed/vue-template-5eq3z" target="_blank">https://codesandbox.io/embed/vue-template-5eq3z</a>

**Comment by jacekkarczmarczyk** [comment]
You need to wrap all your component with `<v-app>`
https://vuetifyjs.com/en/components/application

**Comment by Anubarak** [comment]
Thank you for your quick reply, could you eventually show me how?
Because when I wrap my component with v-app it does not work
https://codesandbox.io/embed/vue-template-5eq3z

**Comment by jacekkarczmarczyk** [comment]
```vue
  <div id="app">
    <v-app>
      <img width="25%" src="./assets/logo.png">
      <HelloWorld msg="Hello Vue in CodeSandbox!" />
    </v-app>
  </div>
```

**Comment by Anubarak** [comment]
I have it exactly like that but the issue still appears

**Comment by jacekkarczmarczyk** [comment]
You still have another v-app in codesandbox (you can have only one), also read this https://github.com/vuetifyjs/vuetify/issues/7333#issuecomment-504450994

**Comment by Anubarak** [comment]
There is no other `v-app` as far as I can see.
At least I was not able to found another one, can you show me where it is or make the codesandbox working?

As for the other link - options is always undefined, do I have to pass vuetify options by myself?

**Comment by jacekkarczmarczyk** [comment]
It was when i looked before, now i can't see it anymore
I think you need to pass options, but better ask the author of that comment or on discord

**Comment by Anubarak** [comment]
Okay I solved the issue...

You need to pass the vuetify instance to all your components and if plugins want to use Vuetify they must have access to the same vuetify instance used everywhere else.

```JS
  <div id="app">
    <v-app>
      <img width="25%" src="./assets/logo.png">
      <HelloWorld msg="Hello Vue in CodeSandbox!"/>
    </v-app>
  </div>
```
Is by the way wrong - `<v-app>` creates an element with ID `app` so you would have two elements with the same ID in your DOM

What you need to do is

```js
import Vue from "vue";
import App from "./App.vue";
import Dialog from "./components/dialog/index";
import vuetify from "./plugins/vuetify";

Vue.config.productionTip = false;
Vue.use(Dialog, {vuetify});    // <-- pass vuetify
new Vue({
  vuetify,
  render: h => h(App)
}).$mount("#app");
```

instead of 

```js
import Vue from "vue";
import App from "./App.vue";
import Dialog from "./components/dialog/index";
import vuetify from "./plugins/vuetify";

Vue.config.productionTip = false;
Vue.use(Dialog);
new Vue({
  vuetify,
  render: h => h(App)
}).$mount("#app");
```

This was the key point, otherwise other components won't have access to vuetify anymore after Version 2.0
