### ISSUE TITLE
[Bug Report] Unknown custom element: <v-list-tile>

### ISSUE THREAD

**Issue by AyushiBShah** [vuetifyjs/vuetify#8701]
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.5.17
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Migrating from 1.5 to 2.0.10 and now getting below error

app.js:48954 [Vue warn]: Unknown custom element: <v-list-tile> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <MainHeader> at resources/js/components/common/Header.vue
       <Dashboard> at resources/js/components/dashboard/Dashboard.vue
         <App> at resources/js/components/App.vue
           <Root>

### Expected Behavior
Elements should be identified

### Actual Behavior
Elements were getting detected earlier

### Reproduction Link
<a href="https://codepen.io/ayushibshah/pen/mdbRqaP" target="_blank">https://codepen.io/ayushibshah/pen/mdbRqaP</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0

![image](https://user-images.githubusercontent.com/15625235/63575386-3e20b380-c58a-11e9-8f28-e196fd7e97a7.png)

**Comment by escapedcat** [comment]
More info can be found here now:  
https://vuetifyjs.com/en/getting-started/releases-and-migrations

**Comment by benwinding** [comment]
Why couldn't they simply just include alias's for the old component names?? 

It wouldn't bloat the library as tree-shaking would remove the unused components anyway right?

Alias's would remove the burden of renaming components from every single application... which seems like a good solution.

PS: Love the framework
