### ISSUE TITLE
[Bug Report] <v-img> doesn't work with browser print

### ISSUE THREAD

**Issue by runyasak** [vuetifyjs/vuetify#8703]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Using `<v-img>` to preview image and click browser print or `window.print()`.

### Expected Behavior
The image from `<v-img>` should appear on print like `<img>`.

### Actual Behavior
The image was not appeared

### Reproduction Link
<a href="https://codepen.io/runyasak/pen/bGbgamx" target="_blank">https://codepen.io/runyasak/pen/bGbgamx</a>

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/63665807-530e7880-c810-11e9-99f5-d939b76e7cb1.png)

**Comment by Khan-Sohail** [comment]
I got stuck at the Same, But After try doing some surfing. The main point was we can't ask every user to enable background Graphics Manually. So you have to do it forcely. 
Add this to your CSS 
@media print {
  
  #section-to-print,
  #section-to-print * {
    visibility: visible;
    -webkit-print-color-adjust: exact; /* Enables  Background Images & Color to Load without Enabling it Manually in Print Settings* / 
  }
