### ISSUE TITLE
[Feature Request] Disabled property for v-stepper-step

### ISSUE THREAD

**Issue by poganytamas** [vuetifyjs/vuetify#8705]
### Problem to solve
I have a situation where 2 of the 6 steps of the v-stepper depends on the selection the user makes on the first step. They don't make any sense, if the user chooses option A, and makes sense when chooses option B.

### Proposed solution
v-stepper-step shoud have a disabled property. If the step is disabled, then it should be gray, not selectable, and skipped by navigation.

**Comment by kenliten** [comment]
I think it can got done by styling the new disabled property and then adding a simple if to ensure the step isn't disabled.

Can I work on this, or is someone already creating the feature?

**Comment by jacekkarczmarczyk** [comment]
> Can I work on this, or is someone already creating the feature?

you can take it

**Comment by Julesdevops** [comment]
Hi, is there any news about this ?

**Comment by Flamenco** [comment]
I created a workaround for this.

Create a style for disabled steps.

```
.v-stepper__step.disabled {
  .v-stepper__step__step {
    background-color: rgba(255, 255, 255, 0.50) !important;
    border-color: rgba(255, 255, 255, 0.50) !important;
  }

  .v-stepper__label {
    color: rgba(255, 255, 255, 0.50) !important;
  }
}
```

Create a method to indicate if a step is disabled.
```js
function isStepDisabled(step: number | string) {
  if (step === 2) {
    if (noDetailsTypes.includes(rootType)) {
      return true
    }
  }
  return false
}
```

Update your component to mark states and add classname.  `v-bind:complete` can go either way, showing a checkmark or not.

```js
<v-stepper-step
    step="2"
    :class="{disabled: isStepDisabled(2)}"
    :editable="!isStepDisabled(2)"
    :complete="isStepDisabled(2)"
</v-stepper-step>
```

Add a guard to any `change step` methods.
```js
function next() {
  step++
  while(isDisabled(step) && step <  totalSteps) {
   step++
  }
}

```
