### ISSUE TITLE
[Bug Report] (v2) Toolbar buttons with a badge are pushed off screen, misaligned vertically

### ISSUE THREAD

**Issue by charliegilmanuk** [vuetifyjs/vuetify#8710]
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use a v-badge on any v-btn within v-toolbar-items

### Expected Behavior
Button and badge should be inline with other buttons within the toolbar items.  Badge should overlap correctly as described on v-badge documentation.

### Actual Behavior
Buttons are pushed up almost off the screen, badge is unreadable whether using overlap prop or not.

### Reproduction Link
<a href="https://codepen.io/charliegilman/pen/vYBgzVJ" target="_blank">https://codepen.io/charliegilman/pen/vYBgzVJ</a>

**Comment by johnleider** [comment]
`v-toolbar-items` targets `v-btn`'s height, inside of badge, it just won't properly receive the styles. Just wrap the inner `v-btn` icon.

https://codepen.io/johnjleider/pen/WNNPeWg

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
