### ISSUE TITLE
[Feature Request] [VDialog] [Performance] Don't create ThemeProvider when dialog is lazy and not visible

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#8712]
### Problem to solve
VDialog components are creating a ThemeProvider even when the dialog is hidden. 

This is an extra component allocation, and it also causes extra dependency subscriptions against `$vuetify` theme props. On a page that has a large number of lazy dialogs (in my case, a table with multiple button-activated dialogs on each row), this causes a significant performance hit due to https://github.com/vuejs/vue/issues/10435

I can work around this by taking my dialogs out of my table and manually providing data and activating, but it would be nice if this wasn't needed.

### Proposed solution
Include the ThemeProvider (and maybe even its containing div(s)) in the set of elements that aren't rendered when the dialog is hidden.

**Comment by KaelWD** [comment]
It's probably best to have a single external dialog anyway tbh.
