### ISSUE TITLE
[Feature Request] Using vee-validate 3.0

### ISSUE THREAD

**Issue by WhiteBookmark** [vuetifyjs/vuetify#8714]
### Problem to solve
Validation of forms with latest vee-validate library which uses different rules and syntax now.

### Proposed solution
Change form validation to acquire the new rules according to the latest version of library.
[Link to release notes](https://github.com/baianat/vee-validate/issues/2191)

**Comment by mynormeza** [comment]
Any updates on this?

**Comment by sw34** [comment]
It works fine now, here is the basis for what you need on each field

`<ValidationProvider v-slot="{ errors }" rules="required|min:3">
    <v-text-field
      v-model="username"
      :error-messages="errors"
      label="Username"
    ></v-text-field>
  </ValidationProvider>`

If I have time tonight or tomorrow I will try updating the codepen example from the vuetify 2 docs.

**Comment by jscottsf** [comment]
How about for `ValidationObserver`? Seems the `rules` prop is used by Vuetify on inputs. Any working example in this use case?

**Comment by sw34** [comment]
The example on Vee-Validate Doc site has been updated to Vuetify 2

https://logaretm.github.io/vee-validate/examples/ui-libraries.html#element-ui

**Comment by adarshmadrecha** [comment]
@sw43, the link is no longer valid.
Updated Link - https://logaretm.github.io/vee-validate/guide/3rd-party-libraries.html#vuetify
Code Sandbox - https://codesandbox.io/s/veevalidate-components-vuetify-pij6w?fontsize=14

**Comment by EtienneM** [comment]
Is there any plan to support vee-validate 3? I'm not completely comfortable to use an old version of vee-validate on my new project. If Vuetify ever supports vee-validate 3 it would induce a lot of rewriting in my project.

**Comment by sw34** [comment]
As noted, there are ways of using VeeValidate 3 today, it not as integrated as the older version, but honestly the way its documented in the links shown here is a better implementation and allows for full use and flexibility of the new features of VeeValidate 3.

**Comment by EtienneM** [comment]
OK thanks for the clarification :)

I found it unclear whether you wanted to do something else as the issue is still open. Thanks for your prompt answer!
