### ISSUE TITLE
[Bug Report] VTreeview rebuilding tree with selection-type

### ISSUE THREAD

**Issue by willyong82** [vuetifyjs/vuetify#8720]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. have parent node selected by clicking on Child1 or Parent
2. hit Change Array Set button to replace item with semi-similar new array

### Expected Behavior
step1. resulting: [ "C2", "C3", "C4", "C1" ] 
step2. resulting: [ "C1", "C2", "C3", "C4" ] 

### Actual Behavior
step2. resulting: [ "C1", "C2", "C3", "C4" , "PARENT"] 

### Reproduction Link
<a href="https://codepen.io/willyong82/pen/RwbpbLB?editors=1010" target="_blank">https://codepen.io/willyong82/pen/RwbpbLB?editors=1010</a>

**Comment by frankhommers** [comment]
I have exactly the same problem.

Also can not make a workaround because in this case I can't see which node is removed on the `@input` event.

**Comment by marceloavf** [comment]
I'm having the same problem, 

For now I'm using a filter function to remove all parents to use them.

**Comment by MicroDreamIT** [comment]
I am having the same problem.

**Comment by whbjzzwjxq** [comment]
the same as mine 
select the root item with 'selection-type = leaf' 
then the input event just **commit** the **root item** but not the **whole tree**

**Comment by johnleider** [comment]
@marceloavf @MicroDreamIT @frankhommers  Please take a moment to review the Contributing Guide, thank you!

![image](https://user-images.githubusercontent.com/9064066/76907209-a9f2a280-6873-11ea-9c2b-0b586c065680.png)

https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md

**Comment by frankhommers** [comment]
> @marceloavf @MicroDreamIT @frankhommers Please take a moment to review the Contributing Guide, thank you!

No problem, but I gave more info than just +1.

**Comment by MartB** [comment]
https://github.com/vuetifyjs/vuetify/blob/3de45255c51473fde1ffe247bf948edf145688a0/packages/vuetify/src/components/VTreeview/VTreeview.ts#L238

This line breaks the selection behaviour for a common, unofficial workaround (https://github.com/vuetifyjs/vuetify/issues/9088)

Would it be possible to change the if condition to `!== 'leaf'` as this is the only other officially supported mode?
