### ISSUE TITLE
[Bug Report] Next and prev does not work on v-calendar

### ISSUE THREAD

**Issue by jessielaf** [vuetifyjs/vuetify#8721]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Add the v-calendar element and buttons for previous and next

### Expected Behavior
The calendar goes to the next or previous week or other timebox

### Actual Behavior
Calendar state does not change

### Reproduction Link
<a href="https://codepen.io/Jessielaff/pen/rNBWwLr" target="_blank">https://codepen.io/Jessielaff/pen/rNBWwLr</a>

**Comment by monikadulik** [comment]
It looks like you can add `v-model="value"` to `<v-calendar> `for workaround.

Just like this:
`<v-calendar v-model="value" :value="value" :now="now" ref="calendar" type="week" :events="events" color="red">`

**Comment by jacekkarczmarczyk** [comment]
`<v-calendar v-model="value" :now="now" ref="calendar" type="week" :events="events" color="red">` (no need for `:value="..."`)

**Comment by nxmndr** [comment]
I understand Vuetify's team is overbooked, but that's a workardound, the problem isn't solved. You end up rewriting component parts over basic features. Not to mention the API doesn't say it's broken, so you lose time over it.

**Comment by mrc-bsllt** [comment]
Same in 2025, with version 3.8.2 (and I can't use the latest version because there are day and event slots that don't work). Any news?
