### ISSUE TITLE
Nuxt link via route-link mixin broken - causes full page refresh

### ISSUE THREAD

**Issue by ChavaSobreyra** [vuetifyjs/vuetify#873]
**Repro:**
https://github.com/ChavaSobreyra/vuetify-nuxt-link-repro

**Instructions to reproduce:**
Navigate to /users. In the nav-drawer I've set up normal nuxt-links and vuetify tile nuxt links. 

Clicking vuetify links results in full page refresh to get to new page. 

**Vuetify Version: **
```
    "vuetify": "^0.12.7"
```

**Relevant code for quick reference: **
```
// /layouts/app.vue

<v-navigation-drawer hide-overlay v-model="drawer" light clipped persistent disable-route-watcher>
  <v-list dense>
    <nuxt-link to="/users">
      Normal nuxt-link to /users
    </nuxt-link>
    <br>
    <br>
    <nuxt-link to="/users/add">
      Normal nuxt-link to /users/add
    </nuxt-link>

    <v-list-item>
      <v-list-tile href="/users" nuxt ripple>
        <v-list-tile-action>
          <mdi icon="account"></mdi>
        </v-list-tile-action>
        <v-list-tile-content>
          <v-list-tile-title>
            Users
          </v-list-tile-title>
        </v-list-tile-content>
      </v-list-tile>
    </v-list-item>

    <v-list-item>
      <v-list-tile href="/users/add" nuxt ripple>
        <v-list-tile-action>
          <mdi icon="account"></mdi>
        </v-list-tile-action>
        <v-list-tile-content>
          <v-list-tile-title>
            Users Add
          </v-list-tile-title>
        </v-list-tile-content>
      </v-list-tile>
    </v-list-item>

  </v-list>
</v-navigation-drawer>
```

**Comment by ChavaSobreyra** [comment]
Ok I found the problem:
Using the `nuxt` prop also requires using the `router` prop because the nuxt-link login is nested under `      if (options && this.router) {` in the `route-link.js` mixin.

**Comment by johnleider** [comment]
I agree, will fix.

**Comment by johnleider** [comment]
This has been added, the router prop will be deprecated in 0.14.

**Comment by ImTheDeveloper** [comment]
Hi is there an example of how this should actually be used?

I'm currently using:
`<v-list-tile :href="item.route" nuxt>`

**Comment by ChavaSobreyra** [comment]
@ImTheDeveloper `<v-list-tile nuxt :to="item.route">`

`to:` is for router links. 

Since this issue is closed be sure to open a new issue if you continue to have problems
