### ISSUE TITLE
[Bug Report] VFileInput height messes up alignment

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#8732]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a `<v-file-input>`.
Add a *placeholder* prop,
Add *prepend-inner-icon* prop,
Set **height** to something bigger than the default value

### Expected Behavior
Either all of them (prepend-icon, prepend-inner-icon and placehoolder) will be aligned to the **top**,
Or all of them will be aligned to the **center**

### Actual Behavior
Icons are aligned to the top, whereas the placeholder is aligned to the center

### Reproduction Link
<a href="https://codepen.io/Tzahile/pen/oNvZaXB?editors=1010" target="_blank">https://codepen.io/Tzahile/pen/oNvZaXB?editors=1010</a>

### Other comments
I think it's preferable to provide the **align** prop.
In my case I would like to align all to the center, but in other cases others might prefer something different

**Comment by sh7dm** [comment]
That should always align to center I think, just as it is by default. @Tzahile if you want, you can create a feature request about that so it'll be considered separately.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
