### ISSUE TITLE
[Feature Request] An autocomplete control with datatable

### ISSUE THREAD

**Issue by robertzml** [vuetifyjs/vuetify#8734]
### Problem to solve
Hi, is there any plan that make an autocomplete control with datatable.
Now it's the v-list in v-autocomplete item slot, can I change it to v-data-table.
Just a data table in the combo's dropdown list, and can search in any column.

### Proposed solution
Make a new control.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
