### ISSUE TITLE
Toolbar overlaps navigation

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#874]
### Steps to reproduce
- create to persistent navigation-drawer
- set the right one to clipped

### Versions
dev-branch

### What is expected ?
 - the left navigation drawer should be next to the toolbar

### What is actually happening ?
- the toolbar overlaps the letf navigation-drawer

### Reproduction Link
https://codepen.io/kpilard/pen/VWxPRx

**Comment by johnleider** [comment]
After looking into this, due to how styles are applied from the drawer to the toolbar, you will have to change your structure very slightly. Move the toolbar between the two drawers.

https://codepen.io/johnjleider/pen/owyYOj
