### ISSUE TITLE
[Bug Report] custom-filter on VDataTable always has undefined 'value'-argument

### ISSUE THREAD

**Issue by meesoverdevest** [vuetifyjs/vuetify#8741]
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
1. Create a VDataTable
2. Add a :search field
3. Add a :custom-filter
   1. Write a console.log in the custom filter method and log the 'value' (first) argument
   2. It will be empty in 2.0.10

### Expected Behavior
The method will work without the first argument which is always undefined.

```javascript
customFilter(search, item) { 
        const normalizedSearchTerm = search.toString().toLowerCase().trim();

	return item.name.toLowerCase().includes(normalizedSearchTerm) || item.mainAccountContact.firstName.toLowerCase().includes(normalizedSearchTerm);
}
```

### Actual Behavior
The custom-filter method itself is not broken. When the second and third arguments are used to apply the filter to an item in the data table, it will work correctly.

My current working example: (The value is always undefined)

```javascript
customFilter(value, search, item) {
        console.log("value: " + value);
        const normalizedSearchTerm = search.toString().toLowerCase().trim();

	return item.name.toLowerCase().includes(normalizedSearchTerm) || item.mainAccountContact.firstName.toLowerCase().includes(normalizedSearchTerm);
}
```

### Reproduction Link
<a href="https://codepen.io/meesov/pen/QWLvjWw" target="_blank">https://codepen.io/meesov/pen/QWLvjWw</a>

### Other comments
I don't know what the 'value' argument should add to this method, because the 'search' and 'item' argument are sufficient enough for the custom filtering.

**Comment by colearendt** [comment]
I believe this has been resolved, at least it looks to be resolved in the codepen, which no longer reproduces

**Comment by meesoverdevest** [comment]
@colearendt , I see indeed, thank you. I will close this issue now.
