### ISSUE TITLE
[Bug Report] Vuetify 1.5 treeview - select parent without selecting children

### ISSUE THREAD

**Issue by VishalGulati** [vuetifyjs/vuetify#8743]
### Environment
**Vuetify Version:** 1.5.16
**Last working version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
I am using treeview component of Vuetify 1.5 and am stuck in a scenario where I want the user to select parent without selecting children and vice-versa.

I googled and found that adding property selection-type="independent" to achieve the same. Unfortunately, that's supported in Vuetify 2.0 and not available in Vuetify 1.5. Is there any way I can achieve the same in 1.5 without upgrading?

### Expected Behavior
Allow independent selection type

### Actual Behavior
Independent selection not supported

### Reproduction Link
This is link to codepen with vuetify 2.0 treeview and independent selection works here: 
<a href="https://codepen.io/vishalgulati/pen/qBWmOYM?&editable=true&editors=101" target="_blank">https://codepen.io/vishalgulati/pen/qBWmOYM?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
Unfortunately there are no plans to update VTreeview in 1.5 with this functionality.
