### ISSUE TITLE
[Bug Report] Simple and Data tables fixed header doesn't work in UCbrowser

### ISSUE THREAD

**Issue by salalaslam** [vuetifyjs/vuetify#8746]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
scroll the table

### Expected Behavior
header shouldn't scroll

### Actual Behavior
header scrolls with the body

### Reproduction Link
<a href="https://codepen.io/salalaslam/pen/BaBRLrZ" target="_blank">https://codepen.io/salalaslam/pen/BaBRLrZ</a>

### Other comments
if demo not work use official documentation link https://vuetifyjs.com/en/components/simple-tables#fixed-header

**Comment by nekosaur** [comment]
According to caniuse, it should have partial support for `position: sticky` on `th` elements, which is what we use in vuetify.

However UCBrowser is not a browser that we officially support. It does not work on IE11 either, which _is_ a supported browser. We have simply made the decision that using `position: sticky` gives us a good trade-off between maintaining the implementation and complete browser coverage.
