### ISSUE TITLE
[Bug Report] v-text-field not clearing input

### ISSUE THREAD

**Issue by boodland** [vuetifyjs/vuetify#8749]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
enter e34354345 in the input and click clear icon

### Expected Behavior
Clears the input

### Actual Behavior
Does nothing

### Reproduction Link
<a href="https://codepen.io/boodland/pen/MWgmJvp" target="_blank">https://codepen.io/boodland/pen/MWgmJvp</a>

**Comment by johnleider** [comment]
This is because `e3` is not a valid number and does not trigger an input event. You need to put a 1 in front of it, `1e3`.
