### ISSUE TITLE
[Bug Report] App bar with image can shrink and fade partly on scroll

### ISSUE THREAD

**Issue by sarahthe** [vuetifyjs/vuetify#8750]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
I am trying to use the prominent app bar with scroll shrink and image that is fading on scroll (https://vuetifyjs.com/en/components/app-bars#prominent-w-scroll-shrink-and-image-fading-on-scroll). However, the app bar can be shrinked (and thus, the image faded) only partly when the amount of scrolling available is too small.

### Expected Behavior
App bar is either extended or collapsed, not something in between.

### Actual Behavior
App bar is neither extended, nor collapsed.

### Reproduction Link
<a href="https://codepen.io/sarahthe/pen/aboWJmX?&editable=true&editors=101" target="_blank">https://codepen.io/sarahthe/pen/aboWJmX?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Adjust `scroll-threshold` to change how fast it shrinks.

**Comment by sarahthe** [comment]
In my case, this cannot solve the problem. When the app bar is not expanded, the page cannot be scrolled. Adjusting the scroll-threshold to a very small value like 5 does not eliminate the problem but prevents the app bar from collapsing altogether.
