### ISSUE TITLE
[Bug Report] v-slide-group doesn't properly calculate width

### ISSUE THREAD

**Issue by bartroodzant** [vuetifyjs/vuetify#8752]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Open the codepen and the v-slide-group goes outside of the screen. If you change Acknowledge with 123, Ackno or another short word it works properly.

### Expected Behavior
The v-slide-group has a right icon at the most right section of the card.

### Actual Behavior
The v-slide-group goes outside of the card and outside of the screen and the right icon is not visible.

### Reproduction Link
<a href="https://codepen.io/BartFTW/pen/BaBRpye" target="_blank">https://codepen.io/BartFTW/pen/BaBRpye</a>

**Comment by deraw** [comment]
I think the problem is in your layout, if you remove `v-row` it works fine!

I had a similar issue: arrows were hidden, it was because I had applied `max-width: 100%` to `v-slide-group__content` by error!
