### ISSUE TITLE
[Feature Request] selected row colour

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#8753]
### Problem to solve
from material design: 

When a row checkbox is selected, the row should display a background color.

For users who use screen magnification, the background color fill provides a way to indicate that a row has been selected, as the selected checkbox may appear outside of the magnified screen area.

### Proposed solution
add active class when row is selected

**Comment by KaelWD** [comment]
This was added in v2.0.19 with 7c875d8cb272f5ed5feec79f73763da234407709
