### ISSUE TITLE
[Feature Request] <a> tag for pagination

### ISSUE THREAD

**Issue by jhd4tmr** [vuetifyjs/vuetify#8759]
### Problem to solve
For SEO purpose, a tag is very import to the html content. Now v-pagination uses button, i suggest an alternative choice to use a tag.

### Proposed solution
Add some new attributes to the pagination component like, tag, to, nuxt, link or something else.

**Comment by jacekkarczmarczyk** [comment]
See also https://github.com/vuetifyjs/vuetify/issues/4855

**Comment by vibonacci** [comment]
Agreed. A possibility to make all buttons <a> tags with href / link is very important for SEO.

**Comment by nyamane** [comment]
Any progress for this feature?
I really wanted this option for SEO cause.
