### ISSUE TITLE
[Bug Report] v-switch still toggles value when label is clicked with @click.stop

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#8764]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a `v-switch` with `label` prop or `label` slot and add `@click.stop`.

### Expected Behavior
The switch should not toggle when the label is clicked.

### Actual Behavior
The switch is toggled.

### Reproduction Link
<a href="https://codepen.io/dEradicated/pen/GRKmzBx" target="_blank">https://codepen.io/dEradicated/pen/GRKmzBx</a>

**Comment by johnleider** [comment]
We'll have to come up with a process for determining functionality based upon provided listeners.

**Comment by KaelWD** [comment]
This is #5968 and is unintended. To disable a switch without affecting it visually use the `readonly` prop.

**Comment by douglasg14b** [comment]
This is still a bug it seems as the `readonly` prop makes the switch look `disabled`.... 

A normal switch that we can capture the click event on is the point here.
