### ISSUE TITLE
[Feature Request] Add threshold sensitivity for navigation drawer

### ISSUE THREAD

**Issue by sts-ryan-holton** [vuetifyjs/vuetify#8769]
### Problem to solve
I believe there should be an option added to the API section to allow a user to control whether a short, or long swipe from the edge of the screen is needed on a touch device to open the navigation drawer. There's a `touchless` option to disable the whole touch element, would be nice to add this extra feature in. (https://v15.vuetifyjs.com/en/components/navigation-drawers#api)

### Proposed solution
This might already be doable via a setting, and if it is, I'm not aware of it. But a new API option should be added here.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
