### ISSUE TITLE
Documentation - List item selection examples

### ISSUE THREAD

**Issue by apb2006** [vuetifyjs/vuetify#877]
The material guidelines has a section about [selection-usage](https://material.io/guidelines/patterns/selection.html#selection-usage). In particular the "Item selection" part.
Vuetify has examples and support for row selection using [data-tables](https://vuetifyjs.com/components/data-tables) but no examples using list items.

I understand from [Glitter](https://gitter.im/vuetifyjs/Lobby/~chat#) that this can be done now 
`...So that is something you can do now, but we can definitely add an example of how `
John Leider@johnleider Jul 03 23:57

The addition of examples showing selection management in list items would enhance the documentation.

**Comment by nekosaur** [comment]
Please open this issue on the docs repo instead.

**Comment by apb2006** [comment]
Done. https://github.com/vuetifyjs/docs/issues/99
