### ISSUE TITLE
v-data-table not sorting third attempt

### ISSUE THREAD

**Issue by mutex12** [vuetifyjs/vuetify#8772]
Using 2.0.11, clicking on the table header the third time will erase the pagination settings: sortBy, sortDesc and no sort will be performed.

This can be demonstrated on the official documentation website:
https://vuetifyjs.com/en/components/data-tables

Nutrition table, click a header multiple times.

**Comment by d3radicated** [comment]
That is intentional. To prevent it from losing sorting, add the `must-sort` prop to the `v-data-table`.
