### ISSUE TITLE
[Bug Report] v-data-table sorting table header on third click loses pagination

### ISSUE THREAD

**Issue by mutex12** [vuetifyjs/vuetify#8773]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.12.4

### Steps to reproduce
Using 2.0.11, clicking on the table header the third time will erase the pagination settings: sortBy, sortDesc and no sort will be performed.

This can be demonstrated on the official documentation website:
https://vuetifyjs.com/en/components/data-tables

Nutrition table, click a header multiple times.

### Expected Behavior
Pagination settings aren't lost.

### Actual Behavior
Pagination settings are lost.

### Reproduction Link
<a href="https://github -> https://vuetifyjs.com/en/components/data-tables" target="_blank">https://github -> https://vuetifyjs.com/en/components/data-tables</a>

**Comment by d3radicated** [comment]
That is intentional. To prevent it from losing sorting, add the must-sort prop to the v-data-table.

**Comment by mutex12** [comment]
Ah ha. Thanks for the reply. The change to table behaviour wasn't obvious between v1 and v2.

**Comment by dario30186** [comment]
Why isn't it on the documentation for version 2? 
I lost a lot of time before I found the solution.
Could you update the doc please?

**Comment by nekosaur** [comment]
v1 has the same behaviour. both v1 and v2 toggle between ascending, descending and no sorting. unless you use the `must-sort` prop like @d3radicated mentioned.

**Comment by dario30186** [comment]
@nekosaur Yes I know, but `must-sort` it's not documented for v2.
That's why I asked to update the documentation

**Comment by d3radicated** [comment]
It's in the API section of the data tables doc.

https://vuetifyjs.com/en/components/data-tables/#api
