### ISSUE TITLE
[Bug Report] Data table's hide-default-header not working on mobile viewport

### ISSUE THREAD

**Issue by kinow** [vuetifyjs/vuetify#8774]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Created a data table with headers and some items data
2. Add hide-default-header to the data table
3. Confirm the headers are gone
4. Change view port to mobile on Firefox
5. The headers appear again because you changed the viewport

### Expected Behavior
Headers are kept hidden even on mobile when hide-default-header is true

### Actual Behavior
Headers are being displayed on mobile

### Reproduction Link
<a href="https://codepen.io/kinow/pen/XWrgpQz" target="_blank">https://codepen.io/kinow/pen/XWrgpQz</a>

**Comment by kinow** [comment]
Normal viewport:

![image](https://user-images.githubusercontent.com/304786/63907986-94ea2980-ca71-11e9-82a3-7e9582ca8b2a.png)

Firefox window resized: 

![image](https://user-images.githubusercontent.com/304786/63908018-acc1ad80-ca71-11e9-84cf-2cb1e295ecbd.png)

**Comment by benjibuiltit** [comment]
Ran into this today. While waiting on a fix, this can be worked around relatively well by adding this to your styles:
```
.v-data-table__mobile-row__header {
    display: none;
}
```

Can see it in action here: https://jsfiddle.net/zva6jL7r/

**Comment by johnleider** [comment]
Your reproduction is missing `v-app`
