### ISSUE TITLE
[Bug Report] v-tab with "/" route stays always active

### ISSUE THREAD

**Issue by Riippi** [vuetifyjs/vuetify#8778]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Using vue-router and `:to` parameter. Create routes so that one is `/`  and tabs for all routes.
Use the tabs to navigate and see that the tab with `/` route will always stay active.  v-tabs-slider works ok.

### Expected Behavior
De-activate tab if route does not match the tab.

### Actual Behavior
Tab with `/` route stays active.

### Reproduction Link
<a href="https://codepen.io/riippi/pen/mdbwdBa" target="_blank">https://codepen.io/riippi/pen/mdbwdBa</a>

### Other comments
This affects also vuetify 1.5.16.

**Comment by jacekkarczmarczyk** [comment]
https://router.vuejs.org/api/#exact
