### ISSUE TITLE
Tabs without tab-bar

### ISSUE THREAD

**Issue by ACalitz** [vuetifyjs/vuetify#878]
Hi there, 

Would it be possible to allow the v-tabs component to work without the need for v-tabs-bar component.

I am attempting to create a slightly complicated (nested) filter menu which requires the content to slide around like the content of the v-tabs component currently does. Allowing for this behaviour would allow for some nice interactive (nested) menus.

I have been able to sort of create my desired effect by piecing together some other components and making use of transitions. I just feel like using the v-tabs component would allow for a much cleaner and potentially more reusable implementation.

Some code to show what I mean:
```
<template>
  <div>
    <v-tabs dark v-model="active">
      <v-tabs-content id="main">
        <v-card flat>
          <v-list>
            <v-list-tile @click.native="active = 'gender'">
              <v-list-tile-title>
                Gender
              </v-list-tile-title>
            </v-list-tile>
            <v-list-tile @click.native="active = 'dateAdded'">
              <v-list-tile-title>
                Date Added
              </v-list-tile-title>
            </v-list-tile>
          </v-list>
        </v-card>
      </v-tabs-content>

      <v-tabs-content id="gender">
        <v-card flat>
          <v-list>
            <v-list-tile @click.native="active = 'main'">
              <v-list-tile-title>
                Back
              </v-list-tile-title>
            </v-list-tile>
            <v-list-tile>
              <v-list-tile-title>
                Select Gender
              </v-list-tile-title>
            </v-list-tile>
          </v-list>
        </v-card>
      </v-tabs-content>

      <v-tabs-content id="dateAdded">
        <v-card flat>
          <v-list>
            <v-list-tile @click.native="active = 'main'">
              <v-list-tile-title>
                Back
              </v-list-tile-title>
            </v-list-tile>
            <v-list-tile>
              <v-list-tile-title>
                Select Date
              </v-list-tile-title>
            </v-list-tile>
          </v-list>
        </v-card>
      </v-tabs-content>
    </v-tabs>
  </div>
</template>

<script>
  export default {
    data: () => ({
      active: 'main'
    })
  }
</script>
```

I have also attached some images to try and show what I mean. Not that they do it well...

Main view
<img width="353" alt="screen shot 2017-07-04 at 15 53 57" src="https://user-images.githubusercontent.com/11047198/27832976-08fa5514-60d1-11e7-95f9-a8c83b889f1f.png">

Gender view
<img width="350" alt="screen shot 2017-07-04 at 15 52 03" src="https://user-images.githubusercontent.com/11047198/27832945-ed1ededc-60d0-11e7-9604-c40619d30e79.png">

**Comment by mix3d** [comment]
I see the idea to have a menu that slides back and forth for sub-menus, but I don't see how the tabs specifically fit in here

**Comment by johnleider** [comment]
This will not be possible without an entire rewrite (which we just did for 0.13). This specific use-case seems very specific to your needs and I don't think we should add it to the framework.

**Comment by ACalitz** [comment]
Completely understand man! Thanks for having a look.

I will use my workaround for now and refine it to hopefully be good enough for a PR someday.
