### ISSUE TITLE
[Documentation] Listing non-supported features on supported browsers

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#8780]
### Problem to solve
Vuetify supports the evergreen browsers, but sometimes a feature is not supported or even can not be supported in a browser. For example 'fixed-header' in the data-table component and 'sticky' in the banner component for IE11. Also, the lack of support can be temporary until it is implemented, for example, 'sticky' in the banner component for Safari (#8158).

I am not sure if these are all the inconsistencies, but you get the idea.

### Proposed solution
Some alerts within or below "Supported Browsers" section, listing the permanent and temporary inconsistencies across the supported browsers.

**Comment by KaelWD** [comment]
The browser support page now has a list of required polyfills.
