### ISSUE TITLE
[Documentation] Docs don't mention lack of support of multiple VuetifyJS instances on a page

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#8781]
### Problem to solve
VueJS supports having multiple VueJS apps on a page.
We use that feature to incrementally migrate from AngularJS to VueJS.
Each AngularJS page contains multiple VueJS apps in it.
We started to use VuetifyJS to style VueJS apps.
The problem we encountered is that VuetifyJS doesn't work nicely when there are multiple `v-app` tags on a page (e.g. problems with closing dropdowns/menus).
I didn't find in the documentation that VuetifyJS doesn't support having multiple instances per page

### Proposed solution
State clearly in the documentation that Vuetify doesn't support multiple isolated Vuetify instances on a page

**Comment by Bbansjkl** [comment]
They do mention it, but it's a bit hidden. Taken from [Components -> Application](https://vuetifyjs.com/en/components/application):

>The v-app component is **REQUIRED** for all applications. [...] It [...] should only be used within your application **ONCE**.

**Comment by MajesticPotatoe** [comment]
As @Bbansjkl mentions, it is in the docs under application, though kinda mixed into the header. I can update / rearrange the header section to make it more clear.

**Comment by aantipov** [comment]
I understand that "ONCE" differently - you can't use `v-app` tag inside of other `v-app` tags, that is have nested `v-app` tags.
But there are other situations:
1. having multiple non-nested `v-app` tags withing the same VueJS app on the same page
2. having multiple `v-app` tags in different VueJS apps on the same page

**Comment by MajesticPotatoe** [comment]
From what i know (and what is listed in the alert below it) is that you should only have 1 `v-app` and it should be at the highest level that wraps all vuetify components. Like i said, I will rearrange and update the header section for clarity.

**Comment by jacekkarczmarczyk** [comment]
The main problem is that ClickOutside directive is not catching clicks outside of v-app, see the pen (open select and click on he yellow area): https://codepen.io/jkarczm/pen/bGbRvGz
If you don't need ClickOutside it could probably work with multiple v-apps

**Comment by aantipov** [comment]
@jacekkarczmarczyk My problem is similar - to close menus/dropdowns I have to click on a separate v-app, not the v-app the activator is placed in

@MajesticPotatoe Ok, thanks!
