### ISSUE TITLE
[Bug Report] v-tabs Custom layout inside not properly aligned

### ISSUE THREAD

**Issue by AyushiBShah** [vuetifyjs/vuetify#8783]
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.6.7
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
The designing of custom elements used to be there now tabs get aligned vertically

### Expected Behavior
Title should come and tabs should be horizontal with proper deisgning rather than vertically stacked

### Actual Behavior
Title on left and tabs on right side horizontally aligned

### Reproduction Link
<a href="https://codepen.io/ayushibshah/pen/oNvwGxb" target="_blank">https://codepen.io/ayushibshah/pen/oNvwGxb</a>

**Comment by AyushiBShah** [comment]
@KaelWD  : Can you please help me with this?

**Comment by AyushiBShah** [comment]
@MajesticPotatoe  : Can you please help me on this one?

**Comment by johnleider** [comment]
Please cleanup the reproduction so that it's easy to work with and as minimal as possible to display the issue. This feels more like something custom you are doing and not necessarily a bug with the framework.

**Comment by AyushiBShah** [comment]
Hi @johnleider, I have removed few extra elements and my concern is with tab indentation
![image](https://user-images.githubusercontent.com/17173974/64401184-67af0400-d08d-11e9-91ef-e3715f11e60e.png)

**Comment by KaelWD** [comment]
`v-tab` is expected to be a direct child of `v-tabs`
