### ISSUE TITLE
[Bug Report] V-select "light" prop doesn't on work dropdown menu when app theme is set to dark

### ISSUE THREAD

**Issue by Ignas-S** [vuetifyjs/vuetify#8789]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows, Linux

### Steps to reproduce
Set dark theme
Create a v-select with the light prop

### Expected Behavior
v-select should have all properties of light theme

### Actual Behavior
the drop-down menu of v-select is in dark theme

### Reproduction Link
<a href="https://codepen.io/ignnsc/pen/rNBwdZm" target="_blank">https://codepen.io/ignnsc/pen/rNBwdZm</a>

### Other comments
the v-select element itself does set to light theme - the outline of the input doesn't change while switching themes, however the drop-down selection menu follows after the set theme

**Comment by MajesticPotatoe** [comment]
not sure if this is intended or not. simple work around is to explicitly set light prop on menu (as you are doing with the `v-select` using `menu-props` eg: `:menu-props="{light: true}"`

**Comment by KaelWD** [comment]
This is so the menu doesn't end up inheriting dark from something like a toolbar (https://jsbin.com/mikusiyilu/1/edit?html,output). The menu uses `this.$vuetify.theme.dark` unless set explicitly. 
Previously you could just [set `dark` on v-app](https://jsbin.com/yacetujuba/1/edit?html,js,output) while leaving it false on the vuetify object to get the behaviour you want, but that was removed in 2589d0c456099ca08a83455c8555370781cd0eef for some reason.

**Comment by KaelWD** [comment]
There are currently no plans to change this behaviour.
