### ISSUE TITLE
[Bug Report] v-calendar Event is duplicated instead of spanning the days when using event slot

### ISSUE THREAD

**Issue by kreierson** [vuetifyjs/vuetify#8792]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.5.17
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
Use the event slot in the calendar.
Add an event that spans multiple days.

### Expected Behavior
The event should span the days instead of duplicating the event

### Actual Behavior
Anything in the event slot essentially is just duplicated as if it were another event instead of spanning the days

### Reproduction Link
<a href="https://codepen.io/kreierson/pen/zYOzJby" target="_blank">https://codepen.io/kreierson/pen/zYOzJby</a>

**Comment by Nico264** [comment]
This slot provides the `start` and `end` props to avoid duplicating the event content.
See this example : https://codepen.io/Nic264/pen/gOObrea

However, it does not enable one to have an event title spanning multiple days. Long titles always get clipped to the first day.
