### ISSUE TITLE
[Bug Report] v-autocomplete w/ `multiple` passes entire array to item-text/item-value

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#8793]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Click on the v-autocomplete in https://codepen.io/ascott18/pen/zYOzeGX?editors=1011, then clear focus from it.

### Expected Behavior
I would expect that itemText and itemValue functions would only be called on array elements contained within either the bound `value` or the bound `items` array when using the `multiple` option.

### Actual Behavior
An error is thrown because the whole array gets passed to the itemText function. Function tries to access properties on the items and fails because the item was actually the whole array. This will also happen if the bound value is `null` or `undefined` (as opposed to an array) - `null` or `undefined` will be passed to `itemText` and/or `itemValue` functions.

### Reproduction Link
<a href="https://codepen.io/ascott18/pen/zYOzeGX?editors=1011" target="_blank">https://codepen.io/ascott18/pen/zYOzeGX?editors=1011</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L385
