### ISSUE TITLE
[Bug Report] Long text cross the border of the width-fixed input component

### ISSUE THREAD

**Issue by yujinghe95** [vuetifyjs/vuetify#8797]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
click the select component and choose one option with long text.

### Expected Behavior
the redundant letters should be hidden as "looooooon..." and be wrapped completely by the component.

### Actual Behavior
the long text cross the border.

### Reproduction Link
<a href="https://codepen.io/JhinYu/pen/jONwgOr" target="_blank">https://codepen.io/JhinYu/pen/jONwgOr</a>

**Comment by Teellcory** [comment]
Note that on a larger screen it'll look perfectly fine (since a flex of 2 contains it), but definitely broken.
