### ISSUE TITLE
v-data-table with tooltip breaking design in Chrome mobile view

### ISSUE THREAD

**Issue by DonDozone** [vuetifyjs/vuetify#8799]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a data table with a column that contains a tooltip and at least 2 additional columns afterwards. so for example:
- column 1
- column 2 with tooltip
- column 3
- column 4

If you then resize the viewport then down to the mobile view, then rendering of the columns below the one with the tooltip breaks.

Instead of the expected
- column 1
- column 2 with tooltip
- column 3
- column 4

it actually looks like
- column 1                       |  - column 3
- column 2 with tooltip  |  - column 4

This does not happen when loading the page directly in the mobile view, only when resizing it down from desktop to mobile version.

### Expected Behavior
All columns are arranged under each other and not in two columns.

### Actual Behavior
The columns AFTER the one with tooltip are placed on a second column.

### Reproduction Link
<a href="https://codepen.io/DonDozone/pen/MWgvYvE" target="_blank">https://codepen.io/DonDozone/pen/MWgvYvE</a>

### Other comments
This only happens in Chrome for me, not in Firefox or Edge. I can also reproduce it on my phone with chrome browser

**Comment by KaelWD** [comment]
What the hell. This appears to be #6951 at first but applying the workaround doesn't fix it.

**Comment by DonDozone** [comment]
Just to let you know: I compared the HTML code for when table is rendered initially in mobile view and when it is resized down to it. They are identical. So this seems to be an issue with the chrome browser, I'm afraid :( Maybe something with the ordering in which the table cells are processed or something?
Very weird indeed.

**Comment by YipingRuan** [comment]
Resize result user agent stylesheet display: table-row at <tr>
![image](https://user-images.githubusercontent.com/5492274/66841117-c7a59e00-ef9b-11e9-8516-6c9f4b4f542c.png)

Override with inline seems fixing the problem instantly:
![image](https://user-images.githubusercontent.com/5492274/66841232-f459b580-ef9b-11e9-83ea-cf9ab644748c.png)
