### ISSUE TITLE
data table component request

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#88]
It would be great if a data table component would be available. This is the link to material.io specs: 
https://material.io/guidelines/components/data-tables.html#

**Comment by johnleider** [comment]
This is currently slated for v0.8.7.

**Comment by johnleider** [comment]
Unfortunately this has slipped past the next release. It is still on the radar, but will not ship with v0.8.7.

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/wiki/Roadmap#v089
