### ISSUE TITLE
[Bug Report] v-data-table wrapper overflow does not scroll (horizontally) in IE11

### ISSUE THREAD

**Issue by NathanStrutz** [vuetifyjs/vuetify#8805]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Visit the vuetify data-table docs in IE11 (I know, it hurts) and shrink the browser horizontally until it cuts off parts of an example table.

### Expected Behavior
It should provide a horizontal scroll bar at the bottom of the table as with a default `overflow: auto;` css rule.

### Actual Behavior
Horizontal scroll bars do not appear in IE11, but they do appear in Firefox, Chrome, and Edge.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables" target="_blank">https://vuetifyjs.com/en/components/data-tables</a>

**Comment by NathanStrutz** [comment]
If anyone else is in a pinch like me, it looks as though this will fix it (SCSS dialect):

```scss
div.v-application {
    display: block;
    th {
        white-space: nowrap;
    }
    div.v-content__wrap {
        width: 100%;
    }
}
```

IE11's misunderstanding of flexbox means my v-application had to switch back to `display:block;`, which broke table headers (they started word wrapping). So that's the first two rules. For the third, IE11 is stupid when it comes to CSS max-width, and often doesn't enforce it or just gets it wrong. The fix is to set an actual width instead of (or in addition to) the max-width, which could affect other things, but didn't break anything for me.

I hope that this can be a clue to fixing it for everyone eventually.

**Comment by johnleider** [comment]
Due to limited bandwidth, moving to v2.3.x.
