### ISSUE TITLE
[Bug Report] v-data-table expand function in item slot expands all rows

### ISSUE THREAD

**Issue by andreskeeled** [vuetifyjs/vuetify#8807]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
Use item slot and expanded-item slot in v-data-table.

### Expected Behavior
The expand should open only the item clicked

### Actual Behavior
It expands all the rows.

### Reproduction Link
<a href="https://codepen.io/andrevferreira/pen/bGbrwbN" target="_blank">https://codepen.io/andrevferreira/pen/bGbrwbN</a>

**Comment by randanunn** [comment]
Your items need a unique key.  `id` by default, or use `item-key` for custom

**Comment by andreskeeled** [comment]
Thank you @randanunn !

**Comment by azabroflovski** [comment]
@randanunn thx

**Comment by jquinter** [comment]
@randanunn not evident at all, many thanks for this!

**Comment by rossginn** [comment]
Maybe consider adding ID to the demo at https://vuetifyjs.com/en/components/data-tables/#expandable-rows

It works but doesn't seem to include ID.

**Comment by nekosaur** [comment]
It uses `item-key` to specify a custom id property.
