### ISSUE TITLE
[Feature request] Support Fontawesome Duotone icons

### ISSUE THREAD

**Issue by egeersoz** [vuetifyjs/vuetify#8809]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100, Mozilla Firefox
**OS:** Windows 10, iOS, Mac OSX, Linux, Android, Windows

### Steps to reproduce
Open the Codepen link.

### Expected Behavior
The correct icon (the one with the `fad` prefix) should get rendered, and it should inherit the CSS custom properties (i.e. `--fa-primary-color` and `--fa-secondary-color`) from `v-icon`.

(Actually, it would be best if the primary color and secondary color could be specified in opts when Vuetify is being bootstrapped.)

### Actual Behavior
You'll see that the duotone icon works when used directly inside a regular HTML element, but the icon itself is not even recognized when used inside `v-icon`, much less colored correctly.

### Reproduction Link
<a href="https://codepen.io/enraged_camel/pen/jONLbGN" target="_blank">https://codepen.io/enraged_camel/pen/jONLbGN</a>

### Other comments
More info on Duotone icons: https://fontawesome.com/how-to-use/on-the-web/styling/duotone-icons

**Comment by sh7dm** [comment]
Should be a feature request since we don't support it yet.

**Comment by jaminroe** [comment]
Thanks for opening this issue, I'll be watching 👀

**Comment by megaroeny** [comment]
Any update on this since it looks like the SVG version of Font Awesome will be supported soon?

**Comment by johnleider** [comment]
An update on this request. In order to improve a11y across the framework, we had to utilize the ::after psuedo element on icons. Apparently duotone uses this same psuedo element to create its effect.

**Comment by geekox86** [comment]
Greetings gentlemen. Thank you for the outstanding framework.
I tried to use Duetone icons today and they get rendered but not correctly.

Is this a bug or a feature not implemented yet? Any update on the implantation?

**Comment by geekox86** [comment]
Any update?

**Comment by apierri** [comment]
Any update on this issue?

**Comment by KaelWD** [comment]
There's two problems with this:
 - VIcon parses the string you give it (`fad fa-coffee-togo fa-fw`) into `fad fa fad fa-coffee-togo fa-fw` which incorrectly has a `.fa` class
 - If you use the ligature font instead like I suggest in https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727, then you run into the ::after problem john mentioned

This should work correctly if you use the SVG icons (@fortawesome/pro-duotone-svg-icons) instead, but I don't have access to that to check.

**Comment by megaroeny** [comment]
Also, I would hold off until [Font Awesome 6](https://fontawesome.com/6) is launched. Things are slightly different there, and icons have refined/changed classes too.

**Comment by KaelWD** [comment]
Vuetify 3 no longer uses the `::after` element in icons and the string parser has been rewritten.

**Comment by megaroeny** [comment]
> Vuetify 3 no longer uses the `::after` element in icons and the string parser has been rewritten.

Just so I fully understand, does that mean Duotone icons can be used for Vuetify v3?

**Comment by johnleider** [comment]
That is our intent, yes.

**Comment by KaelWD** [comment]
When it's out, yeah. You still shouldn't be using the js kits but the font and svg icons both work now. You can use duotone icons in Vuetify 2 with vue-fontawesome but the config isn't as flexible so you have to specify each individual icon you want to use beforehand.

**Comment by megaroeny** [comment]
> When it's out, yeah. You still shouldn't be using the js kits but the font and svg icons both work now. You can use duotone icons in Vuetify 2 with vue-fontawesome but the config isn't as flexible so you have to specify each individual icon you want to use beforehand.

Ah, darn. We rely on using their Kits so I guess that won't work then? Or does it depend on if we use the Icon Font version versus the SVG version?

**Comment by KaelWD** [comment]
> We rely on using their Kits

As in `/js/all.js`? Last time I checked it was pretty much incompatible with Vue due to how it modifies the DOM.

**Comment by megaroeny** [comment]
> As in `/js/all.js`? Last time I checked it was pretty much incompatible with Vue due to how it modifies the DOM.

Nope, so for example one of our Kits script is : `<script src="https://kit.fontawesome.com/#########.js" crossorigin="anonymous"></script>`

Mentioned starting here: https://fontawesome.com/how-to-use/on-the-web/using-kits/uploading-icons

**Comment by KaelWD** [comment]
TIL. If you've been using that with vue already then yeah dutone should work in v3.

**Comment by KaelWD** [comment]
Here's the problem with kits and vue: https://codepen.io/kaelwd/pen/qBqmgqp

**Comment by megaroeny** [comment]
Got it! Well, our kits are using the web font version. You can pick one or the other 😉 So I would assume it's fine? It doesn't say otherwise in their documentation.
![image](https://user-images.githubusercontent.com/1559447/108250309-16c98900-7124-11eb-9bad-0ca4ec8a1302.png)

**Comment by KaelWD** [comment]
Ah ok, definitely no problems there then :+1:
