### ISSUE TITLE
v-list-item  alternative?

### ISSUE THREAD

**Issue by Dmitry1987** [vuetifyjs/vuetify#881]
![image](https://user-images.githubusercontent.com/9369080/27839640-73eeecde-60fb-11e7-90c5-6f9bf8431ec9.png)

The top Toolbar broke and shown as "2 rows"
after last version was pushed (took me a while to realize what happened, it happened in real-time almost :D )

### Steps to reproduce
Use 'v-list-item' with current release
### Versions
v0.13.0
### What is expected ?
Toolbar work
### What is actually happening ?
Toolbar broke
### Reproduction Link
Internal network dashboard...

Hi,  I tried to remove all  "< v-list-item >" from sidebar because reading the changelog i thought it caused the issue, but it didn't help.

What else might cause a problem except the deprecated  'v-list-item'  in the sidebar code (code comes before this snippet of toolbar)?

How should I change this structure of toolbar for the new version:

```
<v-toolbar v-if="is_logged_in" fixed class="indigo darken-4" light>
           <v-toolbar-side-icon light @click.native.stop="drawer = !drawer"></v-toolbar-side-icon>
           <v-toolbar-title>{{mainHeader}}</v-toolbar-title>
           <v-toolbar-items>
           <v-toolbar-item ripple>
               <v-text-field prepend-icon="search"
                     label="Filter view..."
                     @input="setFilter()"
                     @keyup.enter="setFilter()"
                     v-model="filterString" hide-details single-line light>
                </v-text-field>
           </v-toolbar-item>
         </v-toolbar-items>
         </v-toolbar>
```

thanks

**Comment by johnleider** [comment]
```v-list-item``` was removed, noted in the release notes. Just use ```v-list-tile```.

**Comment by johnleider** [comment]
If you have any additional questions, please direct them to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
