### ISSUE TITLE
[Bug Report] TreeView transition glitch when rounded or shaped

### ISSUE THREAD

**Issue by milesial** [vuetifyjs/vuetify#8811]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
Open / close a folder of a v-treeview, shaped or rounded, with transition

### Expected Behavior
The transition should be smooth

### Actual Behavior
The transition glitches

### Reproduction Link
<a href="https://jsfiddle.net/cawqgvbr/5/" target="_blank">https://jsfiddle.net/cawqgvbr/5/</a>

**Comment by bludnic** [comment]
Removing this line solves the issue.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/transitions/expand-transition.ts#L36

`overflow: hidden` increases the height of `v-treeview-node__children` due to `v-treeview-node__root` vertical margin.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
