### ISSUE TITLE
[Feature Request] v-file-upload

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#8812]
### Problem to solve
Increasing the usability of the file-input, as to not being constrained to the very specific form-factor and limitations of a `v-text-field`. 

Example: 
![image](https://user-images.githubusercontent.com/1400380/64057404-52981980-cb51-11e9-8d14-30ab174ef597.png)

### Proposed solution
Creating a base component that contains the `FileInput` functionality, with a template slot?

**Comment by MajesticPotatoe** [comment]
This will come in another component called `v-file-upload` which is already planned to extend the functionality of `v-file-input`

**Comment by MajesticPotatoe** [comment]
extension of original uploader issue #238

**Comment by douglasg14b** [comment]
That will be great! Thanks for the response.

**Comment by CodeSkills** [comment]
It would be nice to have simple Upload Button too. For quick anywhere file upload.

**Comment by odanado** [comment]
workaround
```vue
    <div>
      <v-file-input v-show="false" id="file-upload" />
      <v-btn>
        <label for="file-upload">click</label>
      </v-btn>
    </div>
```
