### ISSUE TITLE
[Bug Report] Bottom Sheet persistent dosen't work anymore with hide-overlay

### ISSUE THREAD

**Issue by FelixINX** [vuetifyjs/vuetify#8813]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
- Add a `v-bottom-sheet`
- Add the `hide-overlay` prop
- Add the `persistent` prop

### Expected Behavior
The sheet stays open

### Actual Behavior
The sheet closes

### Reproduction Link
<a href="https://codepen.io/felixinx/pen/vYBJmjg" target="_blank">https://codepen.io/felixinx/pen/vYBJmjg</a>

**Comment by KaelWD** [comment]
Duplicate of #8697
