### ISSUE TITLE
[Bug Report] Breadcrumbs link is disabled by mistake when link has same name as component

### ISSUE THREAD

**Issue by adivity** [vuetifyjs/vuetify#8814]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
https://prnt.sc/ozxl5x

I have a component called 'Track' with the path '/track'. 

The user is on the path: localhost:8000/track/add and I want to take the user back to localhost:8000/track, but the link is disabled by mistake.
```
<v-breadcrumbs :items="breadcrumbs" divider=">" class="pa-0 ma-0"></v-breadcrumbs>

  data() {
    return {
      breadcrumbs: [
        {
          text: 'Dashboard',
          disabled: false,
          to: '/'
        },
        {
          text: 'Track',
          disabled: false,
          to: '/track'
        },
        {
          text: 'Add Products',
          disabled: true
        },
      ]
    }
  }

```

### Expected Behavior
The "Track" link should be enabled

### Actual Behavior
The "Track" link is disabled

### Reproduction Link
<a href="https://codepen.io/adivity/pen/pozrdgX?&editable=true&editors=101" target="_blank">https://codepen.io/adivity/pen/pozrdgX?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
https://router.vuejs.org/api/#exact

**Comment by adivity** [comment]
Didn't realise there was an 'exact' prop available. Thanks.
