### ISSUE TITLE
[Bug Report] set-items-per-page being triggered twice

### ISSUE THREAD

**Issue by paulvonber** [vuetifyjs/vuetify#8815]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 2.0.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Reload the page, check the console.

### Expected Behavior
Should be triggered only once on the server on the first page load

### Actual Behavior
set-items-per-page is triggered on server and on the client 

### Reproduction Link
<a href="https://codesandbox.io/embed/codesandbox-nuxt-g5guq" target="_blank">https://codesandbox.io/embed/codesandbox-nuxt-g5guq</a>

### Other comments
I'm running vuetify on nuxt 2.9.2

**Comment by johnleider** [comment]
Can you please explain what I need to do in order to observe your bug?

**Comment by paulvonber** [comment]
@johnleider that was a while ago and now I'm totally confused seems that I can't reproduce it anymore by myself, so it was maybe somehow fixed on your side with other improvements, or I did things in a different way. so probably this issue can be closed.
Anyway thanks for Vuetify!!!
