### ISSUE TITLE
[Bug Report] error property not working in v-text-field

### ISSUE THREAD

**Issue by VIXI0** [vuetifyjs/vuetify#8818]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
in a new proyect in a v-text-field try to bind error property

<v-text-field error="false" >
</v-text-field>

### Expected Behavior
when error ="false" the text field should not be red or present the error

### Actual Behavior
the text field always has an error

### Reproduction Link
<a href="https://codepen.io/VIXI0/pen/oNvePMV?&editable=true&editors=101" target="_blank">https://codepen.io/VIXI0/pen/oNvePMV?&editable=true&editors=101</a>

### Other comments
**I LOVE VUETIFY**

*keep doing that wonderful job*

**Comment by VIXI0** [comment]
Sorry it start working unexpectly

**Comment by VIXI0** [comment]
sorry it start working unexpectly.... I did nothing... I supose slow computer or something like that!!

**Comment by VIXI0** [comment]
I have found that im not wrong... sometime work but it needs to be optimize!!

**Comment by MajesticPotatoe** [comment]
what you are looking for is `:error="false"`
`error="false"` is setting it the the string value false, which is a truthy value.

**Comment by VIXI0** [comment]
@MajesticPotatoe You are completly right but is not working i set it to `:error="false` but it keep been _true_ and you know @MajesticPotatoe when I load the form the error property is set to _false_ but the error its there. 

I have verified that **vuetify** its working properly through https://codepen.io/VIXI0/pen/oNvePMV?&editable=true&editors=101

I supose that my problem its about vue
