### ISSUE TITLE
v-select label don't fade if single-line prop is true

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#882]
### Versions

0.13

### What is expected ?
v-select Label should disappear when user enters a value
### What is actually happening ?
v-select label and user value are overflowing each other

### How to reproduce

Create a v-select and define autocomplete, single-line and a label.
Enter a value on the v-select and see it overflowing each other

**Comment by nekosaur** [comment]
Please reproduce the problem in a codepen using the provided template

**Comment by 4eveRS** [comment]
https://codepen.io/anon/pen/MoXemM
