### ISSUE TITLE
[Feature Request] how to add vuetify into existing Vue instance

### ISSUE THREAD

**Issue by sammyne** [vuetifyjs/vuetify#8821]
### Problem to solve
For the case where  an existing Vue instance is passed along to me from somewhere else (in my case, it's vuepress), it would need a way to integrate vuetify into that Vue instance. 

But the [bootstrapping-the-vuetify-object](https://vuetifyjs.com/en/getting-started/quick-start#bootstrapping-the-vuetify-object) cannot address this case.

### Proposed solution
Really appreciate if someone could propose a solution for this

**Comment by jacekkarczmarczyk** [comment]
That's more a question for vuepress. I'm not familiar with it but maybe you just need to add
```
options.vuetify = new Vuetify(...)
``` 
in https://vuepress.vuejs.org/guide/custom-themes.html#app-level-enhancements
Also https://github.com/vuejs/vuepress/issues/1631 might be related
