### ISSUE TITLE
[Feature Request] Rotate Image based on EXIF orientation tag

### ISSUE THREAD

**Issue by andrewlamyw** [vuetifyjs/vuetify#8824]
### Problem to solve
This feature would rotate image based on it's EXIF Orientation tag information. So that photo which captured with camera or phone would be displayed with the correct orientation.

### Proposed solution
Add a new prop "rotate" to v-img component, if "rotate" value is "true", then the component will rotate the image based on EXIF orientation tag.

**Comment by KaelWD** [comment]
This is not supported by browsers, you should rotate the image on your server. 

https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
http://softov.org/oria/image-orientation/index.html
