### ISSUE TITLE
[Bug Report] v-show attribute on v-tooltip

### ISSUE THREAD

**Issue by ARKhoshghalb** [vuetifyjs/vuetify#8825]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
In the code provided in CodePen, the tooltip element should not be shown as `v-show` is false.

### Expected Behavior
`v-tooltip` element should not be shown.

### Actual Behavior
`v-tooltip` element is shown.

### Reproduction Link
<a href="https://codepen.io/ARKhoshghalb/pen/xxKXxeL" target="_blank">https://codepen.io/ARKhoshghalb/pen/xxKXxeL</a>

**Comment by KaelWD** [comment]
Runtime directives apply to the root element, and v-tooltip doesn't really have one. Use it on the icon instead.
