### ISSUE TITLE
Calendar Events under 1H showing as a Clash when end / start is the same

### ISSUE THREAD

**Issue by nimashoghi0** [vuetifyjs/vuetify#8826]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
You will need to change the event dates start, end to be current date to see the events in the codepen

### Expected Behavior
Events to sit below each other

### Actual Behavior
They sit side by side (like a clash)

### Reproduction Link
<a href="https://codepen.io/nimashoghicompnow/pen/OJLXeQz" target="_blank">https://codepen.io/nimashoghicompnow/pen/OJLXeQz</a>

### Other comments
Only happens for events that are under 1H, next event ending at the same time considered a clash when it actually isn't a clash. 

I have fixed this locally however I cannot compile the project so I can't use it. 
File: vuetify-2.0.1.js 
Line #2862, changed 
FROM: 
'if (other.columnCount === -1 && _this.isSameColumn(visual, other))) {'

TO 
'if (other.columnCount === -1 && _this.isSameColumn(visual, other) && _this.isOverlapping(visual, other)) {'

Hopefully you can update the project so I can download it down with NPM with the fix, so we can use this for a project. I had trouble compiling my own version..

**Comment by KaelWD** [comment]
How is that not a clash? The event is 30min high, so if they don't overlap it'll look like it actually starts at 1:30

**Comment by nimashoghi0** [comment]
Did you check out the code pen ? You will need to change the date of the events to the current day to get it working 

A clearer example:
Event A: 9:15-9:30
Event B: 9:30-10:00 
This will cause a clash however
Event A: 8:30-9:30
Event B: 9:30-10:00
Will not cause a clash
- if First event is under 1h it causes an unnecessary clash

**Comment by KaelWD** [comment]
Yeah that's what I'm seeing. In the first example event A appears to end at 9:45 because of the min-height necessary to display the label. 

If you think I'm wrong some screenshots would be helpful.

**Comment by nimashoghi0** [comment]
Right, I know what you mean with the minimum 30M block. 
Check out the CodePen now I have made it 30M instead, and you should be able to see the issue now:
https://codepen.io/nimashoghicompnow/pen/OJLXeQz

This is where the error lies. Even for events that are 30M 45M it still shows them side by side when it shouldn't be. The lines I changed in the original ticket fix this problem, however I can't work out how to recompile the project with the changes so I can't use my version.

**Comment by nimashoghi0** [comment]
Hey @KaelWD,

Any chance you can give me some guidance on how I can compile the modified Vuetify project and use it in my Vue project. I can't seem to work out how to download the github project, change a file and recompile the local version. 

Any help would be greatly appreciated !! I am pretty stuck on this.
