### ISSUE TITLE
[Bug Report] Wrapped v-checkbox is not emitting events

### ISSUE THREAD

**Issue by jessielaf** [vuetifyjs/vuetify#8828]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Wrap the v-checkbox in a component. Use the component with v-model. Submit the form to see if the value has changed

### Expected Behavior
Value is either false or true depending on the state of the v-checkbox

### Actual Behavior
Value is the same as the original value, false.

### Reproduction Link
<a href="https://codepen.io/Jessielaff/pen/qBWPOYm" target="_blank">https://codepen.io/Jessielaff/pen/qBWPOYm</a>

**Comment by nekosaur** [comment]
v-checkbox uses non-standard sugar for v-model (`input-value` for prop, `change` for event). Your wrapping component would need to do the same if you are just passing down event listeners to v-checkbox.

https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model
