### ISSUE TITLE
[Feature request] Use SASS variables for VInput

### ISSUE THREAD

**Issue by roblugt** [vuetifyjs/vuetify#8829]
### Problem to solve
Vuetify 2.0 allows applications to change the styling using SASS variables.  However the SASS styles for VInput use hard-coded values for e.g. font-size

### Proposed solution
Use the common SASS variable for font-size and introduce new variables to allow the control of label height, icon sizes and margins.

**Comment by jacekkarczmarczyk** [comment]
SASS variables were introduced in 2.2
