### ISSUE TITLE
[Bug Report] v-file-input not working with vee-validate

### ISSUE THREAD

**Issue by AyushiBShah** [vuetifyjs/vuetify#8832]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.5
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
When selecting a file still its showing file input has nothing.

### Expected Behavior
Once selected v-validate should recognize and let the form submit

### Actual Behavior
Currently it is showing no value for v-file-input also can't bind value or model attribute

### Reproduction Link
<a href="https://codepen.io/ayushibshah/pen/WNeZdRb" target="_blank">https://codepen.io/ayushibshah/pen/WNeZdRb</a>

**Comment by KaelWD** [comment]
It works if you use v-model instead of the change event.

**Comment by AyushiBShah** [comment]
https://codepen.io/ayushibshah/pen/WNeZdRb?editors=1112

I am facing error in that scenario if you can please check console of the issue

**Comment by MajesticPotatoe** [comment]
you are initializing v-model as a string, where it should be null or an array.

**Comment by AyushiBShah** [comment]
@MajesticPotatoe : Thank you for the response! 
I tried initializing as an array as well as null but none of those seemed to work.  
CC : @KaelWD
