### ISSUE TITLE
[Bug Report] Wrong colors when using RGBA swatches in color picker

### ISSUE THREAD

**Issue by maurice-g** [vuetifyjs/vuetify#8833]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a color picker with 
- `show-swatches` property
- `swatches` property with rgba values (as strings, e.g. `rgba(1, 2, 3, 0.5)`) as elements

### Expected Behavior
That the colors are parsed correctly (same color as shown in the swatch).
Additionally, some more documentation on the expected format of the swatches would be helpful.

### Actual Behavior
The colors are displayed correctly, but when *clicking* on the swatches the colors are parsed wrongly (result is always some sort of pink)

### Reproduction Link
<a href="https://codepen.io/mauriceg84/pen/jONGXKr" target="_blank">https://codepen.io/mauriceg84/pen/jONGXKr</a>

### Other comments
As an alternative, I tried feeding the swatches as parsed rgba objects (`{ r: 1, g: 2, b: 3, a: 0.5}`), however, the colors are not even displayed in this way.

**Comment by KaelWD** [comment]
In the source it's typed as `string[][]`, so elements of `[r, g, b, a]` I guess?

**Comment by MajesticPotatoe** [comment]
Updated the docs with this detail. May want to close and open a FR, or convert this to a FR

**Comment by charliebdewing** [comment]
One of the issues with only accepting rgba hex strings is they do not display correctly on IE 11 / Edge.

**Comment by nekosaur** [comment]
It doesn't have to be hexa colors. hex is fine as well.

**Comment by charliebdewing** [comment]
> 
> 
> It doesn't have to be hexa colors. hex is fine as well.

Yes but then you lose the ability to set the alpha.

**Comment by nekosaur** [comment]
Sure. I was mostly responding to the `only accepts rgba hex` statement. @MajesticPotatoe
