### ISSUE TITLE
v-list-group remove mdi

### ISSUE THREAD

**Issue by Kevinl7** [vuetifyjs/vuetify#8834]
Environment
Vuetify Version: 2.0.11
Vue Version: 2.6.10
Browsers: Chrome 76.0.3809.100
OS: mac 10.14

![1567524114381](https://user-images.githubusercontent.com/22197685/64186581-ac764780-cea1-11e9-89cb-9e475a3d6ea1.jpg)

Hello, I have to introduce mdi/font@3.x  to display the triangle normally，
But i do not want to introduce mdi/font@3.x, Because I have introduced material-design-icons。
What should I do?    Thanks

**Comment by javieringacosta** [comment]
Hello,

I had the same issue and I solved it using the following code in the Css file:

.v-list-group__header__append-icon {
  display: none !important;
}

**Comment by alekbless** [comment]
Set the prop 'append-icon' to null to remove the appended icon.

`:append-icon="null"`

https://vuetifyjs.com/en/api/v-list-group/#props
