### ISSUE TITLE
[Bug Report] All my 2.X Vuetify projects do not work on older IOS devices (iPhone 5 - newest available version of iOS)

### ISSUE THREAD

**Issue by leo1200** [vuetifyjs/vuetify#8837]
### Environment
**Vuetify Version:** 2.0.12
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Create a project with vue CLI, use the standard settings, add Vuetify (cli-plugin), open the page on iOS 10.3.3, nothing happens

### Expected Behavior
The page should be displayed...

### Actual Behavior
Nothing is displayed

### Reproduction Link
<a href="https://lernzettel.org/#/" target="_blank">https://lernzettel.org/#/</a>
Why no Codepen you might ask?
Does not work on those devices either...

**Comment by johnleider** [comment]
We are not going to debug based upon your sight. Please provide the requested information.

**Comment by Jnig** [comment]
I had a similiar issue. Adding the following to vue.config.js solved it for me:

```
transpileDependencies: ['vuetify']
```

**Comment by leo1200** [comment]
@Jnig thanks, I thought this was only necessary for IE
