### ISSUE TITLE
Version 0.13: Bottom navigation - btn did not resize on mobile

### ISSUE THREAD

**Issue by bookstylus** [vuetifyjs/vuetify#884]
### What is expected ?
The btn width to resize on mobile

### What is actually happening ?
Some btn is hiding (only 2 is showing)

### Reproduction Link
Resize the browser on
https://vuetifyjs.com/components/bottom-navigation

**Comment by jacekkarczmarczyk** [comment]
Screenshots available at http://imgur.com/a/IHj2W
