### ISSUE TITLE
[Bug Report] Can't access activator in v-menu when using jest 

### ISSUE THREAD

**Issue by shmaram** [vuetifyjs/vuetify#8843]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
when using the code from the given code in the codepen, I was trying to create a jest test that checks if the button exists and the test fail because the button is not rendered in the wrapper. I have attached the test in the comments 

### Expected Behavior
the test should contain the activator slot (the button)

### Actual Behavior
the button is not part of the wrapper 

### Reproduction Link
<a href="https://codepen.io/shahar-shmaram/pen/wvwPWOQ?&editable=true&editors=101" target="_blank">https://codepen.io/shahar-shmaram/pen/wvwPWOQ?&editable=true&editors=101</a>

### Other comments
Test: 

```
describe('test v-menu', () => {
  test('click on button', () => {
    const toolbarWrapper: Wrapper<any> = shallowMount(ToolbarComponent, { localVue });
    const foundSettingBtn = toolbarWrapper.find('[data-id="toolbar-settings-btn"]');
    expect(foundSettingBtn.exists()).toBeTruthy();
  });
});
```

**Comment by sh7dm** [comment]
You can just query for e.g. `button` you are using as an activator.

**Comment by shmaram** [comment]
@sh7dm, 
this is the issue, the button is not rendered in the html of the wrapper, 
this is how the html looks like, see that the button is not there

```
<div class="cl-right-side-container">
	<v-menu-stub opendelay="0" closedelay="0" contentclass="" maxwidth="auto" nudgebottom="0" nudgeleft="0" nudgeright="0" nudgetop="0" nudgewidth="0" openonclick="true" closeonclick="true" closeoncontentclick="true" maxheight="auto" offsety="true" origin="top left" transition="v-menu-transition"> 
		<v-list-stub tag="div" tile="true"></v-list-stub>
	</v-menu-stub>
</div>
```

**Comment by shmaram** [comment]
@sh7dm ,
this is actually the main problem, the button is not rendered in the html of the wrapper. 

```
 <v-menu-stub opendelay="0" closedelay="0" contentclass="" maxwidth="auto" nudgebottom="0" nudgeleft="0" nudgeright="0" nudgetop="0" nudgewidth="0" closeonclick="true" closeoncontentclick="true" maxheight="auto" openonclick="true" offsety="true" origin="top left" transition="v-menu-transition"> 
	<div>HELLO</div>
</v-menu-stub>
```

**Comment by sh7dm** [comment]
@shmaram you use shallow mount, use just `mount` to fix it.

**Comment by shmaram** [comment]
@sh7dm, 
It worked in 1.5 version when using shallow mount. I expect it to be the same in 2.0
