### ISSUE TITLE
[Bug Report] Autofocus on v-text-field in dialog does not have any effect

### ISSUE THREAD

**Issue by avenmore** [vuetifyjs/vuetify#8845]
### Environment
**Vuetify Version:** 2.0.14
**Last working version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Set autofocus to true on a v-text-field in a dialog.

### Expected Behavior
v-text-field is focused when the dialog is shown.

### Actual Behavior
The v-text-field is not focused.

### Reproduction Link
<a href="https://codepen.io/avenmore/pen/LYPOboY" target="_blank">https://codepen.io/avenmore/pen/LYPOboY</a>

### Other comments
I believe this behaviour may have been changed by the commit [970ac5a](https://github.com/vuetifyjs/vuetify/commit/970ac5a) to fix the dialog focus issue.

**Comment by sh7dm** [comment]
@avenmore no, it's not caused by 970ac5a, this but was present on v2.0.11 too: https://codepen.io/sh7dm/pen/aboqzxw

**Comment by avenmore** [comment]
@sh7dm In the pen you provided, for me, on FF69, the text field is focused on first show, but not on subsequent shows (possibly expected behaviour).

**Comment by sh7dm** [comment]
ahh, sorry, that does! subsequent shows mustn't focus it since it had been blurred already.
