### ISSUE TITLE
[Bug Report] Incorrect position of v-menu when using v-tooltip with activator button

### ISSUE THREAD

**Issue by mariobuikhuizen** [vuetifyjs/vuetify#8846]
### Environment
**Vuetify Version:** 2.0.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132, Safari
**OS:** Mac OS 10.14.6

### Steps to reproduce
Click the activator button

### Expected Behavior
Menu opens over the activator button

### Actual Behavior
Menu opens to the left of the activator button

### Reproduction Link
<a href="https://codepen.io/mariobuikhuizen/pen/gOYXgWG?&editable=true&editors=101" target="_blank">https://codepen.io/mariobuikhuizen/pen/gOYXgWG?&editable=true&editors=101</a>

**Comment by ianbarker** [comment]
With 2.1 the menu opens on the far left of the window. https://codepen.io/ianbarker/pen/gOOYpLw

**Comment by divinespear** [comment]
with `absolute`, position will be expected, but `offset-x` and/or `offset-y` ignored.

**Comment by neanderthil** [comment]
this is a major problem not sure why it isnt getting more attention...
this breaks like all tooltips on a button that pop a menu....

**Comment by KaelWD** [comment]
@neanderthil Thanks for the last good version, tracked this down to #8121
