### ISSUE TITLE
[Feature Request] Better typescript support: v-data-table allow header value to be selected using a function

### ISSUE THREAD

**Issue by bugproof** [vuetifyjs/vuetify#8847]
### Problem to solve
Currently `v-data-table` allows you to pass to it headers in a format like:

`[ { text: 'Name', value: 'name' } ]`

For people using typescript, it's not typesafe

### Proposed solution
My proposal is to allow a function to be passed to value instead of a string. So you could do:

`[ { text: 'Name', value: (item : MyItem) => item.name } ]`

Which would be much more flexible and less prone to errors

**Comment by KaelWD** [comment]
Very simple to do this yourself, and you'd have to be annotating it anyway:

http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgLIE8CSkC2yDeAUMiciHDhAFzIDOYUoA5saROQEYA2EAJjRwD2gnnBCEAvoUKhIsRCgASEOL2gB5GAB4AKgD4CrEpAAeYGvUYgWpZADc4XAK7VkAawjpBMZDsnSEQRB6ZAALFTUoWhplVQ1tDGwIHD0AbQBdZABeZFSjAmRTc2QAcgA5CggSgBp7RxcaEvJKEuQJavz8QogzRoBRTh5eGrrnVxL2OG4+VvbO7t7SzBAHLmBh2tWG0tBV9dmO9MIgA

**Comment by bugproof** [comment]
Not getting autocompletion everywhere with strings though. Also, hover doesn't work and you can't use "Go to definition" or "Peek definition"

**Comment by bugproof** [comment]
Would this change be fine?

https://github.com/vuetifyjs/vuetify/blob/620d87a4c3f2c5855fa4d39c8974caf227347ca0/packages/vuetify/src/util/helpers.ts#L222

```ts
function getObjectValueByPath (obj: any, path: string | ((obj : any) => any), fallback?: any): any {
  // credit: http://stackoverflow.com/questions/6491463/accessing-nested-javascript-objects-with-string-key#comment55278413_6491621
  if (obj == null || !path) return fallback
  if (typeof path === 'function') return path(obj)
  if (typeof path !== 'string') return fallback
  if (obj[path] !== undefined) return obj[path]
  path = path.replace(/\[(\w+)\]/g, '.$1') // convert indexes to properties
  path = path.replace(/^\./, '') // strip a leading dot
  return getNestedValue(obj, path.split('.'), fallback)
}
```

**Comment by nekosaur** [comment]
This is not something we're looking to change at this time.
