### ISSUE TITLE
[Bug Report] v-data-table: column filter not updated in typescript

### ISSUE THREAD

**Issue by mullerch** [vuetifyjs/vuetify#8848]
### Environment
**Vuetify Version:** 2.0.14
**Vue Version:** 2.6.6
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Convert this example to typescript :
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/data-tables/intermediate/custom-filter.vue
Sorry I was not able to do a codepen example in TS, it's beyond my abilities.

### Expected Behavior
The displayed data table lines should be updated when the 'calories' property changes.

### Actual Behavior
The data tables is not updated.

### Reproduction Link
<a href="https://codepen.io/cmwifx/pen/dybZvpd?&editable=true&editors=101" target="_blank">https://codepen.io/cmwifx/pen/dybZvpd?&editable=true&editors=101</a>

### Other comments
It looks lie there is a strange link between the data table items field and the property. They must have the same name so that the datatable get updated in js. In TS it looks like the transpiled js does not respect the condition for this update to be triggered.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
