### ISSUE TITLE
Version 0.13: Block Button on Docs is not centered

### ISSUE THREAD

**Issue by bookstylus** [vuetifyjs/vuetify#885]
### What is expected ?
The Block Button to be centered - margin auto?

### What is actually happening ?
The button is slightly to the right

### Reproduction Link
https://vuetifyjs.com/components/buttons

<img width="474" alt="screen shot 2017-07-04 at 21 51 26" src="https://user-images.githubusercontent.com/21321215/27845347-eaf6d9a0-6104-11e7-821f-c4194c71a420.png">

**Comment by jrast** [comment]
I can confirm this.

If I add `margin:0` to the `button` it seems to be ok
