### ISSUE TITLE
[Bug Report] v-dialog is listen the contained form inputs keydown/keypress events (??)

### ISSUE THREAD

**Issue by buglavecz** [vuetifyjs/vuetify#8854]
### Environment
**Vuetify Version:** 2.0.14
**Last working version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 7

### Steps to reproduce
1. Open the codepen example
2. Click open dialog button
3. Type into text field something
4. Error: the dialog is closed

### Expected Behavior
V-dialog don't listen the input field keydown/keypress events.

### Actual Behavior
 If <v-dialog> component  contains input text fields and we type something to input fields, then <v-dialog> is listen this events.

### Reproduction Link
<a href="https://codepen.io/buglavecz/pen/JjPOEEY" target="_blank">https://codepen.io/buglavecz/pen/JjPOEEY</a>

### Other comments
@johnleider, please fix it. (We discussed on discord)
Thank you. :-)

**Comment by aeonatech-camden** [comment]
I also noticed this (particularly when using a v-switch component). When toggling switches, or typing into inputs that are on a v-dialog component, it seems to fire the @input event on the dialog which causes it to close

**Comment by johnleider** [comment]
The change that caused this bug is being reverted.
