### ISSUE TITLE
[Bug Report] Theme colors do not load when package "nuxt-jsonld" is installed (used to work with 2.0.11)

### ISSUE THREAD

**Issue by oanstein** [vuetifyjs/vuetify#8855]
### Environment
**Vuetify Version:** 2.0.14
**Last working version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
run `yarn remove nuxt-jsonld`and the colors are back.

### Expected Behavior
It shows theme colors

### Actual Behavior
It does not show theme colors

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-8tbth" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-8tbth</a>

### Other comments
It might be related to "theme: fix issues for spa with vue-meta (#8566) (1386cbb)"

**Comment by LordOfDav11** [comment]
Same problem when I install vue-meta.

**Comment by DRoet** [comment]
@kevinmarrec

**Comment by szhorvath** [comment]
Hi. 
I have the same problem. 
No theme colors. 
I also use vue-meta not sure if its related

**Comment by kevinmarrec** [comment]
@LordOfDav11 @szhorvath Also with `nuxt-jsonld` ?

**Comment by LordOfDav11** [comment]
No, but i fixed that with update vue-meta from 1.x to current 2.2.2. I'm sorry for my mistake.

**Comment by kevinmarrec** [comment]
Yes, it's true that if people want last Vuetify with vue-meta, they need last version of vue-meta as well.

**Comment by szhorvath** [comment]
No joy for me. I updated to the latest vue-meta 2.2.2 but theme just won't load.
I don't use `nuxt-jsonld` or nuxt. Only vue-cli

**Comment by kevinmarrec** [comment]
@oanstein See https://github.com/ymmooot/nuxt-jsonld/blob/master/src/createMixin.ts, it's a mixin with `head`, so it will override what `Vuetify` does. You need to open an issue around the `nuxt-json-ld` repository. They should take into account that `head` could already be set, either `object` or `function`.

@szhorvath Could you provide a repository ?
Do you have any error in brower console ?

**Comment by szhorvath** [comment]
@oanstein Thank you. The problem was the `function`. Swaped it to an `object`. Works perfectly. Also I have to have both the lates version `vuetify 2.0.14` and `vue-meta 2.2.2`

Thank you for the help again.

**Comment by ymmooot** [comment]
Hi, I am publisher of `nuxt-jsonld`.
Sorry for the bug. I have  just published a new version v1.4.3 that fixes the issue.
Please use the new version 🙏

**Comment by shekhar677** [comment]
> Hi, I am publisher of `nuxt-jsonld`.
> Sorry for the bug. I have just published a new version v1.4.3 that fixes the issue.
> Please use the new version 🙏

Still the same isssue!!!!!

**Comment by oanstein** [comment]
> > Hi, I am publisher of `nuxt-jsonld`.
> > Sorry for the bug. I have just published a new version v1.4.3 that fixes the issue.
> > Please use the new version 🙏
> 
> Still the same isssue!!!!!

I don't have an issue ...
Do you have a Reproduction Link?

**Comment by nekosaur** [comment]
This seems to have been an issue with an unrelated package. If the problem persists then you should create an issue in that repository.
