### ISSUE TITLE
v-text-field losing/nullfying value after click

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#886]
### Versions

0.13.0
### What is expected ?
after defining the value of a v-text-field, even if v-text-field is not attached to a v-model or binded to a vue variable, it should stay as the defined by the algorithm. 

### What is actually happening ?
if you define the value of a v-select by javascript, if it isn't related to a v-model or binded to a vue variable, once the user clicks the text-field, the value is reseted/nullified.

(*Also, the value is overlaying the label/placeholder)

### Reproduction Link
https://codepen.io/anon/pen/gRKWZg

**Comment by johnleider** [comment]
I'm not sure what I'm looking for, I don't see any issues in that codepen.

**Comment by 4eveRS** [comment]
1. input start with no value.
2. click on button
3. input gets value. (value = test)
4. value overlaps input label - bug probably ( already reported it )
5. click on input
6. input value is reset
7. IMO it shouldn't be reseted

if it's not an issue, is there anyway to make it stick? or I will have to prevent default action, etc?

**Comment by johnleider** [comment]
I see now, ty, will fix.

**Comment by johnleider** [comment]
After looking into this, it is not a bug. You should not set the value of an input in Vue through javascript. Use v-model, or value.
