### ISSUE TITLE
[Bug Report] v-dialog takes up space even when not active

### ISSUE THREAD

**Issue by pascalmattes** [vuetifyjs/vuetify#8864]
### Environment
**Vuetify Version:** 2.0.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Could be the same as #437

### Expected Behavior
Should take up no space

### Actual Behavior
Takes up unnecessary space

### Reproduction Link
<a href="https://codepen.io/pascalmattes/pen/JjPMoxp" target="_blank">https://codepen.io/pascalmattes/pen/JjPMoxp</a>

**Comment by johnleider** [comment]
Duplicate of #6951
