### ISSUE TITLE
[Bug Report] Making boxes  readonly will not prevent deleting

### ISSUE THREAD

**Issue by pcm0nk** [vuetifyjs/vuetify#8867]
### Environment
**Vuetify Version:** 2.0.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Make an autocomplete with readonly prop , chips 

### Expected Behavior
with readonly prop pressing choosing a chip and pressing backspace or delete should not remove the item

### Actual Behavior
click on a chip and press backspace or delete and it would be deleted!

### Reproduction Link
<a href="https://codepen.io/pcmonk/pen/qBWpEMp" target="_blank">https://codepen.io/pcmonk/pen/qBWpEMp</a>

**Comment by jacekkarczmarczyk** [comment]
Happens also without chips https://codepen.io/jkarczm/pen/OJLvVmG
