### ISSUE TITLE
[Bug Report] Changing v-tabs via key doesn't work with a menu

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#8868]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 7

### Steps to reproduce
1. Go to the codepen example and click on the dropdown menu and select foo then bar.  You will see the foo and bar pages shown at the bottom as expected.  
2. Remove the lines for those v-tabs
```
    <v-tab href="#tab-foo" style="display:none">FOO</v-tab>
    <v-tab href="#tab-bar" style="display:none">BAR</v-tab>
```
3. Repeat step 1. You will no longer see the foo and bar pages at the bottom

### Expected Behavior
Menu items in a tab should not need a corresponding v-tab.  A v-tab-item should be sufficient on its own.

### Actual Behavior
A v-tab has to be created for each menu item and set to display:none.

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/NWKaQGZ?editors=1010" target="_blank">https://codepen.io/uglyhobbitfeet/pen/NWKaQGZ?editors=1010</a>

**Comment by BonBonSlick** [comment]
Still exists

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
