### ISSUE TITLE
[Feature Request] Pass item data to @click:row in Data Table

### ISSUE THREAD

**Issue by semipro8** [vuetifyjs/vuetify#8869]
### Problem to solve
That way you can redirect people like so @click:row="routerRedirect(item.id)" versus having to do it in the items/item slot.

### Proposed solution
I'm not sure how this would be done to be honest.

**Comment by MajesticPotatoe** [comment]
`@click:row` already passes item data to the function. It doesn't however if you are using `item` slot, you can do this with a normal click handler.
<https://codepen.io/MajesticPotatoe/pen/jONYbwp>
