### ISSUE TITLE
Calculation of container in min-height calc is missing value

### ISSUE THREAD

**Issue by jamesxv7** [vuetifyjs/vuetify#887]
### Steps to reproduce
Use the default application markup or the `vue init vuetifyjs/webpack` quick start 
### Versions

Vue, 2.3.4
Vuetify, 0.13.0
OS: Windows 10
Browser: Chrome 59.0.3071.115
### What is expected ?

The content should not be scroll-able if content doesn't fill the viewport.
### What is actually happening ?

Scrollbars appears even there is no content to display scrollbars
### Reproduction Link

https://codepen.io/jamespr/pen/eRKWxb

Note: The calculation should also take in consideration the height of the toolbar.

**Comment by johnleider** [comment]
You can work around this for now by explicitly adding the classes to your v-app. ```application--toolbar```, ```application--footer``` and ```application--footer-fixed``` explicitly.

**Comment by jamesxv7** [comment]
Since the height size of my toolbar is fixed I just override the min-height rule of the container class. What classes do I need to add to items you are mentioning?

**Comment by johnleider** [comment]
Fixed with https://github.com/vuetifyjs/vuetify/commit/76f3eecf6dd2d986501653678177588e70b8b9b7
