### ISSUE TITLE
[Documentation] calendar example throws error

### ISSUE THREAD

**Issue by SlavMAK** [vuetifyjs/vuetify#8870]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce

In the example for the weekly calendar, it seems to contain an error. Slots do not work out.
You need to go to the calendar, and try changing the date display slot.
Check, please.

### Expected Behavior

If I understand correctly, slots should provide the opportunity to independently make up for example an event.

### Actual Behavior

I was unable to change the layout of the event.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars#weekly" target="_blank">https://vuetifyjs.com/en/components/calendars#weekly</a>

### Other comments
I may misunderstand the functionality, I'm just starting to learn vuetify. Please give comments. Thank you in advance.

**Comment by MajesticPotatoe** [comment]
assuming you are referring to changing the type to custom-weekly/custom-daily In which the calendar disappears and console logs a `End date is earlier than start date` error. Nothing seems to be wrong per say with the slots, just lack of visibility of the error. Example could use some updates.
