### ISSUE TITLE
[Bug Report] v-radio retrieves wrong value for null

### ISSUE THREAD

**Issue by Blancowicz** [vuetifyjs/vuetify#8876]
### Environment
**Vuetify Version:** 2.0.15
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
Do not set prop `value` for a `<v-radio>` component, or set it to null:
```javascript
<v-radio-group v-model="radio">
  <v-radio :value="null"></v-radio>
  <v-radio></v-radio>
</v-radio-group>
```

### Expected Behavior
Setting no `:value` for a `<v-radio>` tag should return `null` for this element.

[Codepen with 1.5 version working has expected](https://codepen.io/Blancowicz/pen/bGbaKJg?editors=1111)

### Actual Behavior
`radio` should be null when one of those radios are selected, but instead it takes the index of the element as value.

### Reproduction Link
<a href="https://codepen.io/Blancowicz/pen/xxKpzyQ" target="_blank">https://codepen.io/Blancowicz/pen/xxKpzyQ</a>

**Comment by sh7dm** [comment]
Looks like this is intented behavior:
![image](https://user-images.githubusercontent.com/19504461/64491569-b79af000-d272-11e9-8a3d-f400bcf2c56a.png)

**Comment by Blancowicz** [comment]
Thanks for taking your time to watch this @sh7dm

**Comment by johnleider** [comment]
You can change this behavior in your project by extending if you want:

```js
import { VRadio } from 'vuetify/lib'

export default {
  extends: VRadio,

  methods: {
    getValue (item, i) {
      ...
    }
  }
}
```

**Comment by BenShelton** [comment]
Actually this method doesn't exist on `VRadio`, it exists on the `VRadioGroup`. So a complete alternative would be:

```javascript
import { VRadioGroup } from 'vuetify/lib'

export default {
  extends: VRadioGroup,

  methods: {
    getValue (item) {
      return item.value
    }
  }
}
```

There seems to be a lot of checks for `null` though internally for this Vuetify component (or rather VItemGroup which VRadioGroup extends), so although this seems to work in our project YMMV.

**Comment by davesauce14** [comment]
@sh7dm 
If we are closing this issue and marking as `wont fix` can the API docs be updated to show that null / undefined are unsupported values in `v-radio:value`

https://vuetifyjs.com/en/api/v-radio/#events

**Comment by johnleider** [comment]
This issue was eventually fixed and works just fine in the provided Codepen.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
