### ISSUE TITLE
[Bug Report] v-dialog is not persistent when hide-overlay

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#8880]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
1. Open bottom sheet
2. Click outside the bottom sheet
3. It disappears

### Expected Behavior
It does not disappear

### Actual Behavior
It disappears even though it's supposed to be persistent

### Reproduction Link
<a href="https://codepen.io/auspex/pen/QWLaZjj?&editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/QWLaZjj?&editable=true&editors=101</a>

**Comment by sh7dm** [comment]
Same thing w/ Dialogs: https://codepen.io/sh7dm/pen/XWrVQPj?&editable=true&editors=101

**Comment by sh7dm** [comment]
It's a dialog issue since bottom sheet extends dialog

**Comment by sh7dm** [comment]
Duplicate of #8697. Closing
