### ISSUE TITLE
[Bug Report] problems with <template v-slot> inside <v-data-table>

### ISSUE THREAD

**Issue by gerice92** [vuetifyjs/vuetify#8881]
### Environment
**Vuetify Version:** 2.0.15
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Here is the example: https://codepen.io/gerak/pen/yLBpqqG

For this example i used the package https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.5.17/vuetify.min.js and the table shown is fine.

If i go to Settings and change thew package to the latest version https://cdnjs.cloudflare.com/ajax/libs/vuetify/2.0.15/vuetify.min.js the table result, is different, it seems like the template v-slot tag is ignored. You can see how the td with the custom Button "Created Button" is not shown anymore

### Expected Behavior
The code should work the same way as the one with the package https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.5.17/vuetify.min.js

### Actual Behavior
a columns in the resulting table are missing, it's like the template tag is ignored

### Reproduction Link
<a href="https://codepen.io/gerak/pen/yLBpqqG" target="_blank">https://codepen.io/gerak/pen/yLBpqqG</a>

### Other comments
It seems like a version issue, right? Thanks.!

**Comment by jacekkarczmarczyk** [comment]
`items` slot has been renamed to `item`
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0
