### ISSUE TITLE
[Bug Report] Button group Multiple not works as expected

### ISSUE THREAD

**Issue by chris4dd** [vuetifyjs/vuetify#8882]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 7

### Steps to reproduce
Double click one button.

### Expected Behavior
When I double click one button, I should be able to deselect it. 

### Actual Behavior
When I double click one button, seems nothing changed.

### Reproduction Link
<a href="https://codepen.io/chris4dd/pen/wvwpNaw?&editable=true&editors=101" target="_blank">https://codepen.io/chris4dd/pen/wvwpNaw?&editable=true&editors=101</a>

### Other comments
It's actually an example from the Vuetify website. It works fine in v1.5 .

**Comment by phiter** [comment]
You can deselect it. What is happening is that the button still has focused state when you select and deselect. Clicking outside will make it unfocused.

**Comment by MajesticPotatoe** [comment]
This is essentially a duplicate by extension of #8572
