### ISSUE TITLE
[Bug Report] v-tooltip not working on disabled items

### ISSUE THREAD

**Issue by rodrigoriome** [vuetifyjs/vuetify#8884]
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Simply add a tooltip to a component (in my example it was v-btn and v-list-item)

### Expected Behavior
The v-tooltip appears

### Actual Behavior
The v-tooltip does not appear

### Reproduction Link
<a href="https://codepen.io/rodrigoriome/pen/ZEzvNPr" target="_blank">https://codepen.io/rodrigoriome/pen/ZEzvNPr</a>

### Other comments
This is probably a desired behavior, but maybe it could be optional to force the display or not as it is breaking lots of screens when migrating. If there is already a workaround for that, I did not found yet.

**Comment by myleslee** [comment]
Agree. I also wanted to display a hint telling users why the component is disabled and how they can reactivate it.

**Comment by myleslee** [comment]
@rodrigoriome A workaround is to wrap the button with `<span>`: 
https://codepen.io/myleslee/pen/mdbpNKK


Here's the insight from another UI framework:
https://material-ui.com/components/tooltips/#disabled-elements

So hopefully Vuetify can support such use case without the need of the workaround too.

**Comment by rodrigoriome** [comment]
I liked you solution @myleslee , very simple! It is going to save my dev team from redesigning the interface to fit any changes, thank you!

**Comment by KaelWD** [comment]
Duplicate of #7077

**Comment by rodrigoriome** [comment]
The span tag solution does not work when `v-btn` has the prop `absolute`. Reopening until this is solved.

**Comment by bad4iz** [comment]
Duplicate of #7077
