### ISSUE TITLE
[Bug Report] page-count event of v-data-iterator did not triggered when using loading data from server side.

### ISSUE THREAD

**Issue by liupengf12** [vuetifyjs/vuetify#8886]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
The same page-count event of v-data-table works normally, please check this [codepen](https://codepen.io/liupengf12/pen/jONZEgE)

### Expected Behavior
The page-count event should be triggered normally.

### Actual Behavior
The page-count event did not triggered.

### Reproduction Link
<a href="https://codepen.io/liupengf12/pen/ExYQjYX" target="_blank">https://codepen.io/liupengf12/pen/ExYQjYX</a>

**Comment by NGPixel** [comment]
In fact, it's never triggered no matter if you're using server-side loading or not.

Right now it's impossible to get the proper page count when the `v-data-iterator` is handling the filtering. I'm trying the get the total page count when using the `search` option.

Even the [Filter Demo](https://vuetifyjs.com/en/components/data-iterators#filter) on the documentation site has the same issue. Enter any text in the search box and the pagination will still show 3 pages even though there could be only 1 item shown.
