### ISSUE TITLE
[Feature Request] Simple Icons

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#8892]
### Problem to solve
Brand related icons

### Proposed solution
Integrate https://simpleicons.org/ as supported icons ets

**Comment by sh7dm** [comment]
@SumNeuron I know Simple Icons. Sorry, we can't add them as a main icons option since they don't have smth like arrow back, options or file upload icons. So maybe just support for v-icon.

**Comment by SumNeuron** [comment]
If I register it in icon fonts and it only works in v-icon as a supplementary icon set, I would be super happy. `mdi-icons` (Vuetify 2.0's default), is moving away from branded icons so for people wanting to link to dependencies (e.g. Rollup), list various products / blog interests, or skills (e.g. Adobe), would really benefit from having them easily accessible:

```js
// vuetify.js plugin / nuxt.config.js
{
  //...
   icons: ['mdi', 'simpleicons', ...]
}
```

```html
<v-icon>si-adobe-illustrator</v-icon>
```

**Comment by sh7dm** [comment]
okay, so we'll just add Simple Icons to v-icon. no Icons service support

**Comment by Paulsky** [comment]
I also would like to see SimpleIcons to be integrated. Mainly, because the brand icons in Material Design Icons are deprecated and they recommend SimpleIcons themselves: http://dev.materialdesignicons.com/roadmap/brand-icons

**Comment by johnleider** [comment]
For version 3 we are redoing how `v-icon` handles all first party supported icon libraries as well as drastically improving third party support.

You can watch https://github.com/vuetifyjs/vuetify/issues/12699 for updates on how v-icon will work in the future.

**Comment by Alexisgt01** [comment]
```
// plugins/vuetify.js

import Vue from 'vue';
import Vuetify from 'vuetify';

Vue.use(Vuetify);

let vuetify = new Vuetify({
    ...
    icons: {
        iconfont: 'mdi',
    }
});

const simpleIcons = require('simple-icons');

for (const iconSlug in simpleIcons) {
    const icon = simpleIcons.Get(iconSlug);
    vuetify.framework.icons.values[`si-${icon.slug}`] = icon.path
}

export default vuetify;

```

**Comment by patrickelectric** [comment]
Hey, what is the status of this issue ?
