### ISSUE TITLE
[Bug Report] Grids not resizing with small screens

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify#8899]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Resize the screen to small size sm

### Expected Behavior
The page should automatically resize

### Actual Behavior
The small screen doesnt resize to 6 instead flows to 12

### Reproduction Link
<a href="https://codepen.io/geowan/pen/mdbXaym" target="_blank">https://codepen.io/geowan/pen/mdbXaym</a>

**Comment by jacekkarczmarczyk** [comment]
?
![image](https://user-images.githubusercontent.com/15625235/64553115-1460de00-d339-11e9-85ae-5d5e06c0cc7d.png)
