### ISSUE TITLE
Wrapping a <v-btn> with a "flex" element stretches the button

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#89]
After updating to 0.8.6, my action buttons look like this:
![screen shot 2017-01-11 at 5 42 16 pm](https://cloud.githubusercontent.com/assets/882713/21863609/531ef580-d825-11e6-86fa-1b5700f7511e.png)

My (pug) markup:
```
v-col(xs4 class="action-buttons")
	v-btn(floating default class="my-3 mx-2" @click.native="refreshResource" v-bind:disabled="loading" v-bind:loading="loading" )
		v-icon refresh
	v-btn(floating success class="my-3 mx-2" @click.native="addBtnClicked" v-bind:disabled="loading" v-modal:editModal="")
		v-icon add
```

Styles:
```
.action-buttons
	display: flex
	flex-direction: row-reverse
```

Turns out that .action-buttons with a "display: flex" causes that stretching.

**Comment by johnleider** [comment]
Spoke with you on gitter, will need repro as I cannot: http://codepen.io/johnjleider/pen/Xpdjqr

**Comment by johnleider** [comment]
We determined that this happening is expected.
