### ISSUE TITLE
[Bug Report] Content scrolling when navigation drawer is open

### ISSUE THREAD

**Issue by dakshshah96** [vuetifyjs/vuetify#8911]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.4

### Steps to reproduce
Open the navigation drawer in the reproduction link and scroll.

### Expected Behavior
Main content should not be scrollable when the navigation drawer is open.

### Actual Behavior
Main content scrolls even when the navigation drawer is open.

### Reproduction Link
<a href="https://codepen.io/dakshshah/pen/xxKWLgb" target="_blank">https://codepen.io/dakshshah/pen/xxKWLgb</a>

**Comment by KaelWD** [comment]
@johnleider this is caused by scoping utility classes under .v-application

**Comment by dakshshah96** [comment]
@KaelWD Any way I can help in fixing this? Would love to help out since I need to fix this issue in our web app.

**Comment by KaelWD** [comment]
Workaround is to add a global style somewhere with 
```css
.overflow-y-hidden {
  overflow-y: hidden !important;
}
```

The fix is very simple, jut depends if john wants to annoy those people mixing frameworks that he's been putting so much work towards.

**Comment by tpodom** [comment]
The workaround works well but I guess maybe where overflow-y-hidden is getting added to the HTML document it should explicitly set overflow-y: hidden?  The HTML document root wouldn't normally have the v-application class would it?

**Comment by Yihao-G** [comment]
This should have been fixed by now. 

But adding `overflow-y: hidden` hides the scrollbar which changes the page content width every time the drawer open or close, which is annoying.

**Comment by KaelWD** [comment]
@Yihao-G you might want #3875, this was about not using v-app. v-navigation-drawer adds a scroll listener on larger screens that works everywhere but safari.

**Comment by ErikliPizza** [comment]
Commenting it if anyone still suffer from the same issue.

I don't know why, but the mentioned solution did not work for me. It's probably due to my inexperience with Vuetify or other. 

Anyway, I found a solution that fits perfectly **for my case**, basically just hide the main content if the drawer is open and it is on mobile:
`<v-main v-show="((!leftDrawer && !rightDrawer) || !mobile)">`
