### ISSUE TITLE
[Bug Report] VAutoComplete item-text function usage

### ISSUE THREAD

**Issue by AndreasBackx** [vuetifyjs/vuetify#8912]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Linux x86_64

### Steps to reproduce
Create a VAutoComplete component with items that have a method and use that one in the `item-text` property. E.g.: the name of the method is `newFunction`, so enter `item-text="newFunction"`.

### Expected Behavior
For it to evaluate the function and return the result.

### Actual Behavior
It returns the source code of the function.

### Reproduction Link
<a href="https://codepen.io/AndreasBackx/pen/oNvqxdM" target="_blank">https://codepen.io/AndreasBackx/pen/oNvqxdM</a>

### Other comments
#5133 seemed to also ask about this, but didn't explain what he did wrong. Could the usage of function also be clarified in the documentation? The documentation states it accepts functions, but doesn't explain this.

`getPropertyFromItem` in [helpers.ts](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/util/helpers.ts) seems to say that if a function is passed, it's with the signature `((item: object, fallback?: any) => any)`. So I wonder how you have to pass a function here. Is it a component function it's evaluating or the item's function? In general, could this be clarified in the docs?

**Comment by MajesticPotatoe** [comment]
`item-text="newFunction"` => `:item-text="newFunction"`  ?

**Comment by AndreasBackx** [comment]
> `item-text="newFunction"` => `:item-text="newFunction"` ?

I tried that as well, though it results in the item text being: "[object Object]".

**Comment by MajesticPotatoe** [comment]
@AndreasBackx well in your codepen you dont actually have a method called newFunction
eg: <https://codepen.io/MajesticPotatoe/pen/QWLrpKQ>

**Comment by AndreasBackx** [comment]
See line 51, I have added there. It's a workaround, but it should have added it. And as you can see, when you use `item-text` without a colon before it, it shows the signature of that function indicating that it actually is there.

**Comment by MajesticPotatoe** [comment]
oof, my bad, glazed over that one. 
```
entry.newFunction = function() {
  return "this is the new function";
}()
```

**Comment by AndreasBackx** [comment]
> oof, my bad, glazed over that one.
> 
> ```
> entry.newFunction = function() {
>   return "this is the new function";
> }();
> ```

Well that is evaluating it in the map function. I'm simply assigning the `newFunction` so it looks like it came from a real object where I assigned the methods. It should be evaluated by Vuetify.

**Comment by MajesticPotatoe** [comment]
I cant see any indication even back into v1.5 where the components would actually evaluate the function provided by the objects property. I believe in the end the typing has to do with what the `item-text` prop itself will accept to lookup the property within each object and display it. for example these all parse to the `newFunction` property of each object in the items array
`item-text="newFunction" //string` 
`:item-text="'newFunction'" //string`
`:item-text="['newFunction']" //array`
`:item-text="() => { return 'newFunction'} //function`

I apologize for the back and for, just trying to gauge if this is actually a bug/regression/intended and needs better clarification/potential FR.
Any other @vuetifyjs/core-contributors that can help clarify this would be great.

**Comment by AndreasBackx** [comment]
No worries. I simply came here to ask the question, thank you for answering and for your time. The documentation states that the function type is accepted, but does not clarify how that happens.

Regardless of the implementation then. When you have got a few getter methods on an object, is there any way to make them use those?

**Comment by KaelWD** [comment]
The documentation is missing: #5557

It has always been a property lookup, never actually executed a function on the item object. I don't think this makes sense to do anyway, most of the time you'll be getting items from an API so they can't have functions as properties.  If you do have this for whatever reason you'd use `:item-text="item => item.newFunction()"`

**Comment by AndreasBackx** [comment]
So it then requires Typescript to be used I assume? Is there any way to get the same behavior as Vue's `v-if` and similar statements? These resolve `item.isPaid()` unlike `item-text`.
