### ISSUE TITLE
Error during extend/change default vuetify variables 

### ISSUE THREAD

**Issue by vtcentm** [vuetifyjs/vuetify#8913]
From documentation about SASS variables 
1) the style file aka src/scss/main.scss
```
// Any changes to a default variable must be
// declared above the initial style import
$grid-breakpoints: map-merge($grid-breakpoints, (sm: 100px));
// Required for modifying core defaults
@import '~vuetify/src/styles/styles.sass';
```
2) and connect loader via vue.config.js
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: `@import "~@/scss/main.scss"`,
      },
    },
  },
};
```

So I get errors for each component which is unexpected(

```
 error  in ./node_modules/vuetify/src/components/VTooltip/VTooltip.sass

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import ../../styles/styles.sass
       ^
      Can't find stylesheet to import.
  ╷
1 │ @import "~@assets/scss/vuetify-custom-variables.scss"
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:9  root stylesheet
      in /Users/name/project/node_modules/vuetify/src/components/VTooltip/VTooltip.sass (line 1, column 9)

 @ ./node_modules/vuetify/src/components/VTooltip/VTooltip.sass 4:14-206 14:3-18:5 15:22-214
 @ ./node_modules/vuetify/lib/components/VTooltip/VTooltip.js
 @ ./node_modules/vuetify/lib/components/VTooltip/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.220.1.6:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

Please advice the clean example of extending default variables.

**Comment by ctwhome** [comment]
I do have the same problem, but if I create a new project from scratch with `vue create test`, and `vue add vuetify`, I only have to create a new file in `src/sass/variables.scss` and it works, i don't understand because my project has exactly the same configuration.. but it was migrated from 1.5 to 2. I am not sure if that would be the problem

**Comment by nlien** [comment]
I believe you have to upgrade the `vue-cli-plugin-vuetify` to the latest version for this to work. P.t. it is `1.0.0`.

**Comment by ctwhome** [comment]
You are totally right!

**Comment by ctwhome** [comment]
Because it is a major update the regular npm update doesn't do it immediately.. Which i understand, but I find it a bit... Not that visual
