### ISSUE TITLE
[Feature Request] Data Table allow items to not be selectable

### ISSUE THREAD

**Issue by MickaelTH** [vuetifyjs/vuetify#8915]
### Problem to solve
When enabling "show-select" on Data Table, this will make all items (rows) selectable.

But there are situations where those should not selectable (ex: when user is not owner of the item, when an operation is running on this item, etc.).

Also, click on "Select All" should exclude those items.

### Proposed solution
Add a property "isSelectable" on the item to exclude it from being selectable.

**Comment by rriixx** [comment]
this features would be also super helpful for me. I couldn't find a proper solution to achieve this yet.

**Comment by nsamuelssonAtLend** [comment]
Yes please, would be a perfect match in our project.

**Comment by rriixx** [comment]
@nekosaur thx for the integration. Is there a soonish release planned for that feature?
