### ISSUE TITLE
[Bug Report] VSelect: close menu on icon click

### ISSUE THREAD

**Issue by OstapL** [vuetifyjs/vuetify#8916]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.4

### Steps to reproduce
- click on select
- expect menu
- Click on icon

### Expected Behavior
open and close the select menu by click on the icon 

### Actual Behavior
menu not closing by click

### Reproduction Link
<a href="https://codepen.io/OstapL/pen/wvwmyyV" target="_blank">https://codepen.io/OstapL/pen/wvwmyyV</a>

**Comment by MajesticPotatoe** [comment]
This is resolved by setting the following:
`:menu-props="{ closeOnClick: true }"`

**Comment by MajesticPotatoe** [comment]
nvm that. this is still there. prop above can stand as a temp workaround.

**Comment by OstapL** [comment]
@MajesticPotatoe yes, I know about closeOnClick, but even with this it's not working
https://codepen.io/OstapL/pen/wvwmyyV

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6564
