### ISSUE TITLE
[Bug Report] Vuetify v-icon styles overwrite FontAwesome

### ISSUE THREAD

**Issue by mju516** [vuetifyjs/vuetify#8919]
### Environment
**Vuetify Version:** 2.0.15
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Firefox 60.0
**OS:** Linux i686

### Steps to reproduce
Inspect first icon

### Expected Behavior
Fontawesome style for fa-lg would normally be 1.33333 rem.

### Actual Behavior
V-Icon styling overwrites

### Reproduction Link
<a href="https://codepen.io/mju516/pen/OJLvaWy" target="_blank">https://codepen.io/mju516/pen/OJLvaWy</a>

### Other comments
Noticed while upgrading from 1.5.16 to 2.0.14

**Comment by sh7dm** [comment]
It's not intended to use `fa-<size>` with `v-icon`. Use its own sizes
