### ISSUE TITLE
[Bug Report] update:search-input event is not working

### ISSUE THREAD

**Issue by blackpost38** [vuetifyjs/vuetify#8925]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
go to below link and just input some text

### Expected Behavior
print text like 'working!' in console

### Actual Behavior
no print

### Reproduction Link
<a href="https://codepen.io/blackpost38/pen/aboGOOm" target="_blank">https://codepen.io/blackpost38/pen/aboGOOm</a>

### Other comments
I've checked this is working with veutify@2
Also, if i use `@update:searchInput` instead `@update:search-input`, It's working.

**Comment by KaelWD** [comment]
v-bind.sync only used to work with camelCase events
