### ISSUE TITLE
[Bug Report] Horizontal scrollbar appears for Edge when filepinput in dialog

### ISSUE THREAD

**Issue by DonDozone** [vuetifyjs/vuetify#8931]
### Environment
**Vuetify Version:** 2.0.16
**Vue Version:** 2.6.10
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Create a dialog that contains a card which in turn contains a v-file-input.

### Expected Behavior
The dialog displays the whole card and nothing more.

### Actual Behavior
In Edge there appears a horizontal scrollbar. Sometimes it is smaller, sometimes larger. Other browsers don't seem to be affected.

### Reproduction Link
<a href="https://codepen.io/DonDozone/pen/oNvdzQz" target="_blank">https://codepen.io/DonDozone/pen/oNvdzQz</a>

**Comment by johnleider** [comment]
Reference for the fix: https://stackoverflow.com/questions/32991051/absolutely-positioned-flex-item-is-not-removed-from-the-normal-flow-in-ie11

**Comment by DonDozone** [comment]
Mr. @johnleider , thank you very much once more for fixing another bug! :)
