### ISSUE TITLE
[Bug Report] Embedding a v-tab in a vertical v-tab does not respect boundaries

### ISSUE THREAD

**Issue by BrokenImmortal** [vuetifyjs/vuetify#8934]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Pretty simple - put a horizontal tab in a vertical tabs v-tab-item and it won't respect the boundaries of any columns or anything else containing it. If you do this the opposite way (vertical inside of horizontal) it works just fine.

### Expected Behavior
Horizontal Tabs in a vertical tab <v-tab-item> area should still be contained within the defined workspace.

### Actual Behavior
Horizontal Tabs in Vertical Tabs go eternally. Outside of any columns, off the page, wherever they want.

### Reproduction Link
<a href="https://codepen.io/TypewriterKey/pen/LYPmdLg" target="_blank">https://codepen.io/TypewriterKey/pen/LYPmdLg</a>

### Other comments
In my example I provided I showed both examples of this - one is vertical inside of horizontal working properly, and the other is horizontal inside of vertical going beyond the bounds of the parent column.

**Comment by johnleider** [comment]
Can you please simplify this reproduction, thank you.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
