### ISSUE TITLE
[Bug Report] v-pagination inside v-expansion-panel-content does not respect total-visible prop

### ISSUE THREAD

**Issue by mcculleydj** [vuetifyjs/vuetify#8935]
### Environment
**Vuetify Version:** 2.0.17
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
See the code pen. Basically, a pagination component outside of the expansion panel renders with the appropriate number of buttons, but a pagination component inside the panel does not (number of buttons seems to equal value of length prop). Note: once you interact with the component total-visible prop value is respected and the number of visible buttons is reduced.

### Expected Behavior
Expect total-visible to be respected on initial render even inside a v-expansion-panel-content.

### Actual Behavior
Total-visible prop is not respected inside expansion panels until the user interacts with the pagination controls.

### Reproduction Link
<a href="https://codepen.io/mcculleydj/pen/QWLrJKN?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/mcculleydj/pen/QWLrJKN?&editable=true&editors=101#anon-signup</a>

**Comment by mcculleydj** [comment]
I started to investigate this and cannot reproduce it on dev branch inside the playground (still an issue on master). Contribution guidelines say to target bug fixes at master, but I'm thinking that this can be closed. I will try and figure out which commit to dev fixes this so that you can reference that if agree that this will be fixed on the next dev merge.

**Comment by mcculleydj** [comment]
Looking a bit closer it seems like the addition of ` || maxLength < 1` to the conditional on line 68 of VPagination.ts 9 days ago on master is the breaking change (not in dev). That said, there is a lot going on here. onResize() is being relied on to set maxButtons data prop in a responsive manner, but width is 0 when the control is housed in a v-expansion-panel-conent leading to a maxButtons value of -3 and undesired behavior. After seeing this, I'd actually like to keep this open for a longer look.

**Comment by adnanchang** [comment]
Any update on this issue?

**Comment by johnleider** [comment]
I think this might be closed in favor of this https://github.com/vuetifyjs/vuetify/pull/9313 . While it's not directly this component, it suffers from the same issue, being in the DOM before it has dimensions. We can fix this throughout the framework by making a mixin that can do this for us. If you feel I'm off base here, let me know.

**Comment by mcculleydj** [comment]
Makes sense.
