### ISSUE TITLE
[Bug Report] Content is overlapped by VAppBar when extended=false during hide-on-scroll

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#8938]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
1. Enable`Hide-on-scroll`
2. Enable `Extended`
3. Scroll down until `VAppBar` is hidden
4. Disable `Extended` (ONCE and ONLY ONCE)
4. Scroll to top to see content hidden under `VAppBar`

### Expected Behavior
Content should not be overlapped by `VAppBar` after `Extended` is disabled once.

### Actual Behavior
Content is overlapped by `VAppBar` after `Extended` is disabled once.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/bGbMJWo" target="_blank">https://codepen.io/andrewspy/pen/bGbMJWo</a>

**Comment by johnleider** [comment]
This is resolved in v3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
