### ISSUE TITLE
picker show the date wrong with prop firstDateOfWeek in spanish 

### ISSUE THREAD

**Issue by fgutr** [vuetifyjs/vuetify#894]
What is expected ?
show the correct date

What is actually happening ?
Show the date wrong, today is Wednesday, July 5
![image](https://user-images.githubusercontent.com/13359919/27866394-279bf638-6164-11e7-9c11-a9d072d92b02.png)
![image](https://user-images.githubusercontent.com/13359919/27866472-8085f4ec-6164-11e7-9dd8-c1f765ea574e.png)

Reproduction Link
https://codepen.io/anon/pen/RgJKog

**Comment by nekosaur** [comment]
The codepen link is not correct

**Comment by fgutr** [comment]
now is correct

**Comment by johnleider** [comment]
I'm looking at the codepen and everything appears to be correct. Can you please guide us in the right direction?

**Comment by fgutr** [comment]
If you check the codepen the date is incorrect, today is Friday July 7, not Saturday July 7

**Comment by johnleider** [comment]
Fixed with #905
