### ISSUE TITLE
[Bug Report] [VList] tag prop does not work. Lists should be able to render as ul and li.

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#8942]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
1. Open the codepen
2. Inspect the list

### Expected Behavior
The list should render as an `ul`.

### Actual Behavior
It is rendering as a `div`. Also, the `list-items` are rendering as anchors instead of `li`.

### Reproduction Link
<a href="https://codepen.io/phiter/pen/MWgXbQW?editors=1010" target="_blank">https://codepen.io/phiter/pen/MWgXbQW?editors=1010</a>

### Other comments
I understand that a `v-list-item` that has a `:to=""` prop transforms itself into a `router-link`, but `router-link` has a [`tag` property](https://router.vuejs.org/api/#tag) which can be used to change it into something else. Vuetify does not pass that prop to the router-link.

The prop tag is being ignored in the `VList` component, as seen in the following lines:

https://github.com/vuetifyjs/vuetify/blob/a01a1508219ae2a23049e3fcf070b032cb2ba853/packages/vuetify/src/components/VList/VList.ts#L94-L105

My suggestion is to allow changing the tag of a `v-list` to something else, and if a list item has both `to` and `tag` props, maybe wrap the anchor inside the chosen tag.

That would allow for semantic HTML, instead of always using divs.
This is important for accessibility, since screen readers rely on lists in order to provide better information to the user.

**Comment by johnleider** [comment]
> Also it seems like the screen readers are not reading list items inside a v-menu when you navigate with arrows.

Should create a separate issue unless directly related. Thank you!

**Comment by johnleider** [comment]
Fixed in fb062bf
