### ISSUE TITLE
[Feature Request] V-data-table index access via row click

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#8943]
### Problem to solve
Say I want to highlight a row on click, the old way would be to pass the index via the props.index on the table row. I'm failing to see a way to do it now that click is declared directly on the data table itself and currently only passes the item of the row.  

### Proposed solution
Add the index of the row clicked to the parameters of @click:row

**Comment by taylanwhite** [comment]
I figured out the proper way if this doesn't get added to the row prop for anyone with the same issue.

Overriding the body v-slot allows you to declare a custom table row. You can then make a reference to it, and change the color. Quick example:

<template v-slot:body="{ items }">
  <tbody>
    <tr v-for="item in items" :ref="notes.items[notes.items.indexOf(item)].id" :key="item.id" 
     @touchend="updatedMessageTitle(item)" @click.stop="updatedMessageTitle(item)">
       <td> {{item.updated_by}} </td>
        <td> {{item.summary}} </td>
        <td colspan="2" style="vertical-align: top; width:100%" class="body-2" align="left"
        >{{ item.description }}</td>
    </tr>
  </tbody>
</template>

**Comment by RyanFrantz** [comment]
@taylanwhite Can you provide an example of overriding the body?

**Comment by taylanwhite** [comment]
Sure.
In the data table component, declare a new template like
<template v-slot:body="{ items }">
  <tbody>
    <tr v-for="item in items"> // You can add a click to this
       //declare table definitions here
    </tr>
  </tbody>
</template>

**Comment by MaevskiyE** [comment]
Any news?
