### ISSUE TITLE
[Feature Request] v-select : unfocus on clearable

### ISSUE THREAD

**Issue by max13fr** [vuetifyjs/vuetify#8946]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Linux

### Steps to reproduce
Click on the cross to clear the field

### Expected Behavior
Unfocus the select to enlarge label

### Actual Behavior
The select keeps the focus. You can't do anything without another click on the select to show options.

### Reproduction Link
<a href="https://codepen.io/max13fr/pen/wvwXjgg" target="_blank">https://codepen.io/max13fr/pen/wvwXjgg</a>

### Other comments
- the focus should be kept if open-on-clear is true
- the issue seem's to be the same on v-autocomplete but at least you can write your query (but options are not shown so use open-on-clear seems better)

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
