### ISSUE TITLE
[Bug Report] Expansion Panels animation lags if added bottom padding to expansion panel content

### ISSUE THREAD

**Issue by kumold** [vuetifyjs/vuetify#8947]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Edge 78.0.268.3
**OS:** Windows 10

### Steps to reproduce
add bottom padding to expansion-panel-content

### Expected Behavior
Smooth transition of opening and closing panels

### Actual Behavior
Opening animation starts mid way, closing animation ends before fully closed.

### Reproduction Link
<a href="https://codepen.io/kumold/pen/GRKGBrz" target="_blank">https://codepen.io/kumold/pen/GRKGBrz</a>

**Comment by KaelWD** [comment]
The animation uses `height: 0`, which doesn't include padding: 
![image](https://user-images.githubusercontent.com/16421948/64920220-35717500-d7f8-11e9-9e67-d6a1937ca294.png)

Apply it to an inner element instead.
