### ISSUE TITLE
[Documentation] No Mention of Events for v-switch Component

### ISSUE THREAD

**Issue by yogeshkudikala** [vuetifyjs/vuetify#8948]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Go to v-switch API Documentation

### Expected Behavior
List of events to be mentioned in API Documentation

### Actual Behavior
No Events Mentioned

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/selection-controls#api" target="_blank">https://vuetifyjs.com/en/components/selection-controls#api</a>

**Comment by MajesticPotatoe** [comment]
Covered in #7694 - Will work on completing this weekend.

**Comment by adarshmadrecha** [comment]
@MajesticPotatoe, shouldn't this issue be closed after the documentation is updated?
Thanks for referring the parent issue.

**Comment by MajesticPotatoe** [comment]
The parent issue is will be used to track it.
