### ISSUE TITLE
Hint alignment on text fields that use prepend-icon

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#895]
### Steps to reproduce
Create a text input that uses the prepend-icon prop and the hint prop.

### Versions
0.13

### What is expected ?
I would expect the hint text to left align itself with the beginning of the text input. It's currently left aligned underneath the prepended icon. I'm not sure if this is the intended behavior but I think it would look better if the hint text displayed under the input and not the icon.  

### What is actually happening ?
The hint text left aligns underneath the prepended icon.

### Reproduction Link
https://codepen.io/smitchell/pen/rwKPYr

**Comment by johnleider** [comment]
Regression was fixed with a2524850a9ab2106c8e7365fa4ffc2960867a667
