### ISSUE TITLE
[Documentation] v-data-table Example for server-side sorting does not work

### ISSUE THREAD

**Issue by randanunn** [vuetifyjs/vuetify#8955]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.5

### Steps to reproduce
Add a v-data-table, try to use the `options.descending` property as shown in example. It never gets populated.  It appears that this property has been changed to an array in `options.sortDesc` which works as expected.

### Expected Behavior
Update example to use the new property

### Actual Behavior
options.descending is unavailable as a property

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side" target="_blank">https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side</a>

### Other comments
This code pen is a copy of the documentation:  
codepen: https://codepen.io/lucille2/pen/xxKzeao

docs:  https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side 

the example only sorts ascending, not descending.

**Comment by danhogan** [comment]
It seems this issue was resolved last September with [this commit](https://github.com/vuetifyjs/vuetify/pull/9138/commits/2626c02aa0b31c2dd7702a3180f749bcf060d6cc)
