### ISSUE TITLE
[Bug Report] Datepicker component does not accept ISO strings

### ISSUE THREAD

**Issue by Kritten** [vuetifyjs/vuetify#8959]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Run the app in the repository

or

create a ISO 8601 Date string with `new Date().toISOString()` and insert it into the vuetify datepicker component

or

In the first example in the date picker docs the code for the input is 
`new Date().toISOString().substr(0, 10)`
If you remove the substr-call the error appears too.
But the substr-call should be really dangerous because you loose all the information about the timezone. 

### Expected Behavior
Should accept the ISO String as the docs say for `value` "Date picker model (ISO 8601 format, YY-mm-dd or YY-mm)"

### Actual Behavior
Logs ` Error in render: "RangeError: Invalid time value"`

### Reproduction Link
<a href="https://github.com/Kritten/date-picker" target="_blank">https://github.com/Kritten/date-picker</a>

**Comment by Kritten** [comment]
So.. is this a bug or expected?
My future implementation depends on it

**Comment by KaelWD** [comment]
It's expected. The component doesn't handle timezones at all, it only accepts ISO 8601 **date** strings.
