### ISSUE TITLE
Indexing a table

### ISSUE THREAD

**Issue by Pyrd** [vuetifyjs/vuetify#896]
Reporting a bug?
================
No, everything works fine

Have a feature request?
=======================
Hello, I would like to know if you could add a feature that could allow the indexing of a table ?
I've looked for a long time if I could without asking here, but I could not find a way to achieve it with vuetify.

Thanks you !

**Comment by nekosaur** [comment]
I'm not sure what you mean by index of a table. Please direct your question to our [gitter](https://gitter.im/vuetifyjs/Lobby) instead.

**Comment by Pyrd** [comment]
I mean to have a specific index for each row. So each row has his own id
number.

I don't know if i'm clear.

**Comment by nekosaur** [comment]
There is an `index` prop available on the item slot.
