### ISSUE TITLE
[Documentation] Unable to Load vuetifyjs.com

### ISSUE THREAD

**Issue by anktsrkr** [vuetifyjs/vuetify#8963]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Go to https://vuetifyjs.com, it is redirecting to https://zeit.co/deployments/vuetifyjs.com

### Expected Behavior
Should open official site

### Actual Behavior
It is redirecting to https://zeit.co/deployments/vuetifyjs.com

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

**Comment by MajesticPotatoe** [comment]
May be cached or a regional outage/issue. From a system standpoint things seem kosher. Will continue to monitor. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
