### ISSUE TITLE
[Documentation] Vuetify Documentation Website not working

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#8966]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 8.1

### Steps to reproduce
I'm opening vuetify main website 

### Expected Behavior
it should open 

### Actual Behavior
it redirect to 
https://zeit.co/deployments/vuetifyjs.com?redirect=1

### Reproduction Link
<a href="https://vuetifyjs.com/" target="_blank">https://vuetifyjs.com/</a>

### Other comments
I've tried to use VPN to open website, same result

**Comment by benitarego** [comment]
This is exactly happening with me as well

**Comment by saeed1202** [comment]
same to me.
it was OK yesterday! OMG

**Comment by bjorntrondsen** [comment]
In the meantime you can try https://dev.vuetifyjs.com/en/
Or run the docs locally
https://stackoverflow.com/questions/51292967/vuetify-offline-docs

**Comment by KareemDa** [comment]
> In the meantime you can use https://dev.vuetifyjs.com/en/
> Or run the docs locally
> https://stackoverflow.com/questions/51292967/vuetify-offline-docs

Thanks a lot, dev site is working fine

**Comment by chegelawrence** [comment]
also happening here man!!
