### ISSUE TITLE
[Documentation] Website not opening

### ISSUE THREAD

**Issue by tbhaxor** [vuetifyjs/vuetify#8967]
### Environment

**Browsers:** Firefox 69.0
**OS:** Linux x86_64

### Steps to reproduce
1. Open the link
2. It will redirect to zeit.co oauth consent screen (if not logged in) otherwise to https://zeit.co/deployments/vuetifyjs.com?redirect=1

### Expected Behavior
Open the blue-colored website of docs

### Actual Behavior
Redirecting to https://zeit.co/deployments/vuetifyjs.com?redirect=1

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

**Comment by MajesticPotatoe** [comment]
Dupe #8966 #8963 #8964 etc etc
https://github.com/vuetifyjs/vuetify/issues/8966#issuecomment-531537314
