### ISSUE TITLE
[Documentation] Documentation leads to different homepage

### ISSUE THREAD

**Issue by LeducH** [vuetifyjs/vuetify#8968]
### Environment

**Browsers:** Chrome 77.0.3865.75
**OS:** Linux x86_64

### Steps to reproduce
go to https://vuetifyjs.com/en/

### Expected Behavior
Documentation will open 

### Actual Behavior
some zeit link opens 

### Reproduction Link
<a href="https://zeit.co/login?next=%2Fdeployments%2Fvuetifyjs.com%3Fhost%3Dvuetifyjs.com%26redirect%3D1%26section%3D" target="_blank">https://zeit.co/login?next=%2Fdeployments%2Fvuetifyjs.com%3Fhost%3Dvuetifyjs.com%26redirect%3D1%26section%3D</a>

**Comment by algomax** [comment]
The same for me. Zeit seems to be the hosting company for the documentation website.

**Comment by islamzatary** [comment]
same for me

**Comment by abhinavReduxpress** [comment]
+1

**Comment by lloydbanks** [comment]
Any alternative documentation resources?

**Comment by bartduisters** [comment]
It seems to be working again.
