### ISSUE TITLE
[Bug Report] Native ESM (Non-webpack or babel) bootstrapping of Vuetify is broke for 2+ while works in 1.5.18

### ISSUE THREAD

**Issue by jrgleason** [vuetifyjs/vuetify#8973]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Run the pug file in your favorite web application platform (I am using koa)

### Expected Behavior
In 1.5.18 everything works fine. 

### Actual Behavior
However, in the 2x versions I get an following error...

> Error in beforeCreate hook: "Error: Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object"

### Reproduction Link
<a href="https://gist.github.com/jrgleason/b2a3fb61469d02ea46fdc2349e0461ef" target="_blank">https://gist.github.com/jrgleason/b2a3fb61469d02ea46fdc2349e0461ef</a>

**Comment by jrgleason** [comment]
I will also try to provide a basic example to demo. I just need to find a good CDN to use because I currently host the node_modules version using koa-static

**Comment by KaelWD** [comment]
- That's never been officially supported: #5736
 - You didn't initialise vuetify properly, it needs to be passed into the vue instance as well.

**Comment by jrgleason** [comment]
This is kind of a silly answer when it had worked and then stopped. If I initialized improperly why was it working before.

**Comment by MajesticPotatoe** [comment]
> You didn't initialize vuetify properly, it needs to be passed into the vue instance

(because the way vuetify initializes changed from 1.x -> 2.x)
