### ISSUE TITLE
[Bug Report] RTL not working on stepper-content

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#8978]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 8.1

### Steps to reproduce
* initialized vuetify with project,
* added stepper as documentation 

### Expected Behavior
content should translate from left to the right

### Actual Behavior
it translates from right to the left

### Reproduction Link
<a href="https://codepen.io/kareemda/pen/KKPBrwO" target="_blank">https://codepen.io/kareemda/pen/KKPBrwO</a>

**Comment by KareemDa** [comment]
Side Note: 
v-progress-linear component also have problem in RTL.

it should increase from right to left not the opposite

**Comment by melbahja** [comment]
@sh7dm should this be closed ?
