### ISSUE TITLE
[Bug Report] Shows multiple Date Pickers when used in Data Tables

### ISSUE THREAD

**Issue by 7188162** [vuetifyjs/vuetify#8979]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 7

### Steps to reproduce
1. Click the "due" from a row and close edit dialog
2. Click the field from other row

### Expected Behavior
Shows only 1 Date Picker on the edit dialog

### Actual Behavior
Shows 2 Date Pickers on the edit dialog and the upper-left side of the window

### Reproduction Link
<a href="https://codepen.io/7188162/pen/vYBaQea" target="_blank">https://codepen.io/7188162/pen/vYBaQea</a>

**Comment by nekosaur** [comment]
I can't reproduce this on Windows 10 and 77.0.3865.120

**Comment by esynaps** [comment]
I was able to reproduce it under the same conditions

Video: https://gyazo.com/1b7bcb2b229f29ec1d42766d12663e22

**Comment by 7188162** [comment]
@esynaps Thanks your advice. I've longing for it!
