### ISSUE TITLE
 Nested menu?

### ISSUE THREAD

**Issue by sunabozu** [vuetifyjs/vuetify#898]
Is there a conventional way for creating nested menus with `v-menu`? So far I couldn't come up with a clean solution based only on the available API.

**Comment by johnleider** [comment]
Please direct questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by capttrousers** [comment]
Nested menu's are part of the spec, is this going to be implemented in the Vuetify API?

**Comment by nekosaur** [comment]
This is also a question. Please use our new chat at http://chat.vuetifyjs.com. The answer (for any future askers) is that anything part of MD spec will eventually be implemented in Vuetify.
