### ISSUE TITLE
[Bug Report] VListGroup with sub-group still generates prepend icons although prepend-icon is set to empty string

### ISSUE THREAD

**Issue by geekox86** [vuetifyjs/vuetify#8980]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use a v-list-group with sub-group and prepend-icon=""

### Expected Behavior
Prepend icon should stop being generated

### Actual Behavior
Prepend icon is still being generated

### Reproduction Link
<a href="https://codepen.io/geekox86/pen/RwbBveL" target="_blank">https://codepen.io/geekox86/pen/RwbBveL</a>

### Other comments
This should match the behavior of append-icon="" with non-sub-group v-list-group's

**Comment by johnleider** [comment]
The culprit: https://github.com/vuetifyjs/vuetify/blob/952f561bb9d2278f5920f202fb8be8932d5dfe73/packages/vuetify/src/components/VList/VListGroup.ts#L175
