### ISSUE TITLE
[Bug Report] v-menu fixed prop not applying

### ISSUE THREAD

**Issue by z3nz** [vuetifyjs/vuetify#8983]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Linux x86_64

### Steps to reproduce
Use a `v-menu` component and try to add the `fixed` prop.

### Expected Behavior
Expected `position: fixed;` style to be applied to `v-menu` when prop `fixed` is applied.

### Actual Behavior
Style remains `position: absolute;`

### Reproduction Link
<a href="https://codepen.io/z3nz/pen/WNegwxM" target="_blank">https://codepen.io/z3nz/pen/WNegwxM</a>

### Other comments
Also tried adding classes to the v-menu to style manually and no classes or ids are applied either.

**Comment by johnleider** [comment]
This prop is being passed in by positionable mixin (within menuable mixin). It's not meant to be public. I'll mark this as a documentation update but otherwise will be resolved for v3.0
