### ISSUE TITLE
[Bug Report] v-menu inside of v-dialog broken

### ISSUE THREAD

**Issue by justinledwards** [vuetifyjs/vuetify#8991]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132, Google Chrome
**OS:** Mac OS 10.15.0, Linux

### Steps to reproduce
Click the button to open dialog.  

### Expected Behavior
The datepicker should be hidden until you click on the v-text-field.

### Actual Behavior
The datepicker is not hidden, and if you close the modal and open it back up the v-text-field is missing.   

### Reproduction Link
<a href="https://codepen.io/justinledwards/pen/pozOmOx" target="_blank">https://codepen.io/justinledwards/pen/pozOmOx</a>

**Comment by KaelWD** [comment]
You've put the date picker inside the menu's activator slot.

**Comment by justinledwards** [comment]
@KaelWD I appreciate the the layer 8 fix.  I have a couple of other bugs with the behavior now that it's working.   I'll try to resolve them before further embarrassment.
