### ISSUE TITLE
[Bug Report] Horizontal scrollbar not appearing on data table

### ISSUE THREAD

**Issue by ikushum** [vuetifyjs/vuetify#8993]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.1
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
Use `v-container` having `class="fill-height"` as a wrapper element around `v-data-table` component. Also make sure that the `v-data-table` has lots of columns.

### Expected Behavior
A horizontal scrollbar should appear on `v-data-table` component.

### Actual Behavior
Horizontal scrollbar doesn't appear on `v-data-table` component and rest of the columns get cropped out.

### Reproduction Link
<a href="https://codepen.io/ikushum/pen/vYBrdPj?editors=1010" target="_blank">https://codepen.io/ikushum/pen/vYBrdPj?editors=1010</a>

### Other comments
[Here](https://www.google.com) is a similar issue in Vuetify 2.0.11 but seems like an IE11 issue

and [here](https://www.google.com) is another similar closed issue in Vuetify 1.0.17 which might be related

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/jkarczm/pen/yLLxqrv

**Comment by Lucascoorek** [comment]
For me, fix was:
```scss
.v-data-table { 
  overflow-x: auto !important;
  }
```
