### ISSUE TITLE
[Bug Report] vuetify-loader loading in Expension Panel error

### ISSUE THREAD

**Issue by donthijackthegit** [vuetifyjs/vuetify#8994]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
webpack@`^4.39.3`, in webpack.conf.js

in a .vue file <template> tag:
```
<v-expansion-panels
      v-model="panel"
      :disabled="disabled"
      multiple
    >
      <v-expansion-panel>
        <v-expansion-panel-header>Panel 1</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>

      <v-expansion-panel>
        <v-expansion-panel-header>Panel 2</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>

      <v-expansion-panel>
        <v-expansion-panel-header>Panel 3</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>
    </v-expansion-panels>
```

Compilation is successful, but in runtime webpack-dev-server throw errors and warnings.

### Expected Behavior
vuetify-loader loads vuetify components correctly

### Actual Behavior
page broken, in console:

- A warning shows "v-expansion-panel should wrapped in v-expansion-panels"
- this.expansionPanel.registerContent is not a function

### Reproduction Link
<a href="https://codepen.io/donthijackthegit/pen/rNBqxQJ (sorry this is fake link)" target="_blank">https://codepen.io/donthijackthegit/pen/rNBqxQJ (sorry this is fake link)</a>

### Other comments
Seems vuetify-loader only loads the v-expansion-panel but not other dependencies, I have to disable vuetify-loader and use 
```
import Vuetify, {
	VExpansionPanel,
	VExpansionPanels,
	VExpansionPanelContent,
	VExpansionPanelHeader,
} from 'vuetify/lib';

Vue.use(Vuetify, {
	components: {
		VExpansionPanel,
		VExpansionPanels,
		VExpansionPanelContent,
		VExpansionPanelHeader,
	},
});
```

**Comment by sh7dm** [comment]
probably you should reopen this issue in `vuetify-loader`.

**Comment by jacekkarczmarczyk** [comment]
Might be bug in vuetify, but we do need a reproduction (can be a github repo), so please open a new issue when you are able to provide one.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
