### ISSUE TITLE
[Bug Report] XS class in vuetify grid does not work

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#8997]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
when adding xs class to v-col, xs class is not applied, as it doesn't exist in css. 

### Expected Behavior
xs class to work as any other class - sm, md, lg, xl

<div class="col-xs-6 col-12">

### Actual Behavior
<div xs="6" class="col-12">

### Reproduction Link
<a href="https://codepen.io/rveruna/pen/GRKYqeY?editors=1010" target="_blank">https://codepen.io/rveruna/pen/GRKYqeY?editors=1010</a>

**Comment by sh7dm** [comment]
This one is intended since `sm` for example uses `min-width`, so `cols` prop work for xs size:
![image](https://user-images.githubusercontent.com/19504461/65145614-a1cfbc80-da22-11e9-8933-01088dee8b1b.png)

**Comment by JohnnyCrazy** [comment]
IDK why this issue got closed, small reproduction: https://codesandbox.io/s/vuetify-playground-kqvb7

Expected

**Comment by sh7dm** [comment]
use `cols` instead of `xs`

**Comment by JohnnyCrazy** [comment]
> use `cols` instead of `xs`

Owwww, this works :) Sorry for the confusion then!

**Comment by geocolumbus** [comment]
Why was "xs" changed to "cols", but "sm" and "md" still work? Also, the documentation still tells people to use "xs". This makes zero sense.

https://vuetifyjs.com/en/components/grids

**Comment by MajesticPotatoe** [comment]
@geocolumbus changing `xs` -> `cols` was intentional. `xs` itself is a valid breakpoint, and is only mentioned in that link once that i can see in regards to the breakpoint system:
>It contains 5 types of media breakpoints that are used for targeting specific screen sizes or orientations, xs, sm, md, lg and xl.

So not sure where it says you should use it as a prop, though if you can point it out I would be happy to remove it.

there is already an issue(#8888)/PR(#9041) in regards to a migration guide from 1.x -> 2.x grids.

**Comment by geocolumbus** [comment]
OK - thanks for the clarification!

**Comment by iedmrc** [comment]
This is still an issue and made me crazy. It wasted my time much. And must be open until clarified.

**Comment by JSilversun** [comment]
Hi, please reopen this, I don't think using "cols" instead of "xs" is intuitive, and change the docs to avoid mentioning any xs, it's misleading.

**Comment by MajesticPotatoe** [comment]
@iedmrc As stated, there is already an issue and PR in regards to clarification on this.
@JSilversun `cols` is the appropriate replacement for `xs` in 2.x grids. This likely will not change until vuetify 3 as it would be considered breaking.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
