### ISSUE TITLE
[Bug Report] Incorrect checkbox `off-icon` when using font-awesome

### ISSUE THREAD

**Issue by leftclickben** [vuetifyjs/vuetify#8998]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
Use `iconfont: "fa4"` in Vuetify's `icon` options, and use a `v-checkbox` element with default everything.

### Expected Behavior
A box with a tick in it is rendered when the checkbox is checked, and an empty box is rendered when the checkbox is unchecked, as per [the documentation](https://vuetifyjs.com/en/components/selection-controls).

### Actual Behavior
A box with a tick in it is rendered when the checkbox is checked, but nothing is rendered when the checkbox is unchecked, except on hover when the grey disc appears.

### Reproduction Link
<a href="https://codepen.io/leftclickben/pen/rNBZQOa" target="_blank">https://codepen.io/leftclickben/pen/rNBZQOa</a>

### Other comments
Pen demonstrates the problem and the solution.

**Comment by KaelWD** [comment]
Version locked codepen: https://codepen.io/kaelwd/pen/qBdNqOv

You've linked fontawesome 5.4.0 here, of course fa4 won't be displayed properly.

**Comment by leftclickben** [comment]
You might want to check the linked PR then, as it was accepted and merged: #8999
