### ISSUE TITLE
Unknown custom element: <v-tab>

### ISSUE THREAD

**Issue by agc11** [vuetifyjs/vuetify#90]
I do not know if I'm doing something wrong or it happens to some people but the component tab does not appear included, thank you in advance

Room.vue
```

> <template>
>     <div class="room">
>         <v-tabs id="mobile-tabs-5" grow>
>             <v-tabs-tabs>
>                 <v-tab v-bind:item="{ href: '#mobile-tabs-5-1', icon: 'phone' }">dd</v-tab>
>                 <v-tab v-bind:item="{ href: '#mobile-tabs-5-2', icon: 'favorite' }">ss</v-tab>
>                 <v-tab v-bind:item="{ href: '#mobile-tabs-5-3', icon: 'account_box' }">aa</v-tab>
>             </v-tabs-tabs>
>             <v-tabs-items>
>                 <v-tabs-item v-for="i in 3" v-bind:id="'mobile-tabs-5-' + i">
>                     <v-card>
>                         <v-card-text>pepe</v-card-text>
>                     </v-card>
>                 </v-tabs-item>
>             </v-tabs-items>
>         </v-tabs>
>     </div>
> </template>

```

app.js
`import Vuetify from 'vuetify'

Vue.use(Vuetify)

Vue.component('room-list', require('./components/Room-list.vue'));
Vue.component('room', require('./components/Room.vue'));

const app = new Vue({
    el: '#app',
    mounted() {
        this.$vuetify.init()
    }
});`

**Comment by johnleider** [comment]
This was a breaking change in 0.8.6. Just change the component name to ```v-tab-item```

**Comment by agc11** [comment]
thanks!

**Comment by Geowan** [comment]
Am still facing this problem

My package.json has "vuetify": "^0.17.7",

**Comment by nekosaur** [comment]
Please do not comment on closed issues. If you have a problem, create a new issue at https://issues.vuetifyjs.com.

That said, 0.17.7 does not have a `v-tab` component. https://vuetifyjs.com/releases/0.17/#/components/tabs
