### ISSUE TITLE
Text fields  validation

### ISSUE THREAD

**Issue by MoustafaBayommy** [vuetifyjs/vuetify#900]
hi guys thank you for your delight effort in this  beautiful lib 

i trying to use text field component in my project  and when i try to validate the user input using required directive or rules i don't know how to check from code if their are errors in validation , for example when i was using vee-validatior i can access error object easily and check for errors how could i do this here?

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
