### ISSUE TITLE
[Bug Report] v-tabs spacing issue

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#9000]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
1. Open the codepen
2. Visit the page on mobile (e.g. by scaling your browser window)

### Expected Behavior
`v-tabs` should be hidden without leaving empty space

### Actual Behavior
`v-tabs` is hidden but there is a lot of empty space

### Reproduction Link
<a href="https://codepen.io/p4sca1/pen/aboRpzO" target="_blank">https://codepen.io/p4sca1/pen/aboRpzO</a>

### Other comments
I tried adding `v-if="$vuetify.breakpoints.smAndUp"` to the `template` but that messes with server-side-rendering.

**Comment by sh7dm** [comment]
Tabs hide, space leaves due to expansion slot of toolbar. the fix for your problem can be e.g. adding `:extension-height="$vuetify.breakpoints.smAndUp ? 0 : 48"` to the toolbar. this one will remove extension when breakpoint is reached.

**Comment by P4sca1** [comment]
That works great, thank you very much! :)
