### ISSUE TITLE
[Feature Request] Data table column number formatting

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#9006]
### Problem to solve
Custom number formatting for locale and currencies.

Is it possible to get number formatting in a data table column? If I change the original data for example from "1000000" to "1 000 000" then I will have to do a bunch of parsing when working with filters.

I would rather not change the original data, just the presentation data.

Is there a way to do this or can it be added?

### Proposed solution
Don't know.

**Comment by nekosaur** [comment]
Use `item.<name>` slot to customize rendering of a column. Look at examples in documentation.
