### ISSUE TITLE
[Bug Report] v-data-table: no-data-text not working when using v-slot:body

### ISSUE THREAD

**Issue by okrepp** [vuetifyjs/vuetify#9007]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
See reproduction link.

Create v-data-table, pass no-data-text and add body by using v-slot:body. Let items prop be an empty array.

### Expected Behavior
That no-data-text is shown in table body.

### Actual Behavior
no-data-text is never displayed. Resulting table has empty tbody. 

### Reproduction Link
<a href="https://codepen.io/okrepp/pen/GRKYMyj" target="_blank">https://codepen.io/okrepp/pen/GRKYMyj</a>

### Other comments
Seems to work when not using v-slot:body.

**Comment by nekosaur** [comment]
This is working as intended (and is documented in docs afaik). The body slot will override all internal rendering of content. You should only use the body slot if you need access to the `tbody` element.

Otherwise use the `item` or `item.<name>` slots.
