### ISSUE TITLE
Navigation bar list group should close in mini mode

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#901]
This is not mini
<img width="1440" alt="screen shot 2017-07-05 at 12 14 28 pm" src="https://user-images.githubusercontent.com/11958538/27880873-6f2305ac-617b-11e7-906e-d0662bc7e5c8.png">

if keeping list-item open and use mini mode: 
<img width="1440" alt="screen shot 2017-07-05 at 12 14 30 pm" src="https://user-images.githubusercontent.com/11958538/27880904-8a919c68-617b-11e7-8f3c-dcffc5f2095d.png">

however I think this is expected:
<img width="1440" alt="screen shot 2017-07-05 at 12 14 34 pm" src="https://user-images.githubusercontent.com/11958538/27880931-9b16defe-617b-11e7-9f99-63aeef68e89e.png">

otherwise when use click on ex. PPS on the picture, it will open the navbar with everything close. Plus, it looks ugly to have a big gap between two list item

This issue can be reproduce using the vuetify page as well, so I will not create a codepen or jsfiddle here.

**Comment by johnleider** [comment]
Do you think the expected behavior is when mini is changed to true, all list-groups retract?

**Comment by dohomi** [comment]
@johnleider I think we had this discussion before, here might be the right place to gather some ideas. I think nested/grouped list items should be either:
* not visible and only show if the sidebar is full-with again
* nested items are displayed inside a v-menu on mini variant

**Comment by SquareBeard** [comment]
What about list group items with tile action ?
I was expecting to see my sub menu icons in the mini drawer.

I don't think it is a good idea to force hide the list groups in mini mode. For my use case I need to open all listgroups in mini mode (I'm not sure that this is even possible actually).
IMHO you should leave the decision to the developer and not force it in the CSS. We can still add it ourselves or even do more complicated stuffs with v-show/hide.

**Comment by amyngb** [comment]
This is broken again in Vuetify 1.0.  I am expecting the display of the list__group__items to change from 'block' to 'none' when the mini-variant drawer is closed.  Since I can see that some other devs want all list groups to be open in mini mode, maybe this could be left up to the developer with a new prop.

**Comment by amyngb** [comment]
I fixed it by setting the children v-list-tiles in the v-list-group to v-if="!Mini" (only displaying them if the drawer is not in mini mode.)
