### ISSUE TITLE
[Bug Report] V-Data-Table: When deleting all the rows off of the last page of the non-first page, the table is not refreshed to the previous page

### ISSUE THREAD

**Issue by JeffersonSchuler** [vuetifyjs/vuetify#9010]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
This behavior is exhibited in the CRUD Actions example.  In a v-data-table create a table with 10 rows and choose 5 rows per page.  Go to the second page, rows 6 -10.  Then delete all the rows in the second page.

### Expected Behavior
When all the rows on the second page are deleted, the table should switch to the previous (first) page.

### Actual Behavior
Nothing happens, and in the footer 6-5 of 5 is shown.

### Reproduction Link
<a href="https://codepen.io/jeffersonschuler/pen/rNBqvWy?&editable=true&editors=101" target="_blank">https://codepen.io/jeffersonschuler/pen/rNBqvWy?&editable=true&editors=101</a>

**Comment by JeffersonSchuler** [comment]
I was able to work around the issue using using the current-items event.  Checking to make sure we are not on the first page, and if there are no more items left on the current page, we can decrement the current page value.  In my case I am using external server pagination.

**Comment by anakmuda01** [comment]
check this
https://codepen.io/anakmuda09/pen/JjPxzYw?editors=0010

**Comment by JeffersonSchuler** [comment]
> check this
> https://codepen.io/anakmuda09/pen/JjPxzYw?editors=0010

That works.
