### ISSUE TITLE
[Feature Request] File Dialog expansion

### ISSUE THREAD

**Issue by angrymarker** [vuetifyjs/vuetify#9013]
### Problem to solve
Add Save File Dialog and Directory Selection Dialog Components.
Add Drag and Drop ability to file-input component.
Agreed that this may be unusable for web client tools, but for Electron Tools this would be great.

### Proposed solution
For the Save File Dialog, I'm hoping to act the same as electrons, does not write out info, but simply returns the file path for the new-to-save file.

Firefox. Edge, and Chrome allow the following tag to use for directory selection.
```
<input type="file" webkitdirectory directory />
```

**Comment by sh7dm** [comment]
:-1: for save file dialog, but :+1: for drag&drop

**Comment by richdunajewski** [comment]
The Drag and Drop support is already mentioned in #7836. Maybe add your comments to that issue and revise this one to not mention drag and drop so it doesn't get marked as a duplicate.

**Comment by johnleider** [comment]
We are not officially supporting drag and drop as of now. This is something we are going implement as part of #12716.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
