### ISSUE TITLE
[Feature Request] V-select using a button or icon

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#9017]
### Problem to solve
I'd like to popup a v-select using an icon or a button.

The use case for this is a data table grid and I want the user to select visible columns by clicking a settings icon instead of having a full v-select visible.

A v-select with multiple choices would show.

### Proposed solution
Support v-select to use an icon or v-btn only.

Or make v-btn support multiple selects.

**Comment by Teellcory** [comment]
You could have the button set a v-select to show when clicked. This isn't exactly an expected functionality of a select itself. Referring to your specific use case: I'd like there to simply be a built in prop for allowing filtering of the v-data-table columns.

**Comment by jacekkarczmarczyk** [comment]
Why not use `v-menu` for this?

**Comment by Leespiker** [comment]
What you're describing is already possible with [menus and lists](https://codepen.io/Leespiker/pen/oNXrYzB).

**Comment by Zyles** [comment]
And... how do you do this with an icon? An icon without any borders.

**Comment by Leespiker** [comment]
I updated the codepen to use an icon. If you don't even want a button, put `v-on="on"` on the icon directly.

**Comment by M-ac-i-ej-s** [comment]
Steps to actually do this: 

- set v-slot:selection as empty span
- set v-slot:append as v-icon of your choice
- create a <div class="select"> outside of your v-select with width close to the width of an icon
- using SCSS, inside .select class:

  .v-text-field > .v-input__control > .v-input__slot:before {
    border-style: none !important;
  }

  .v-text-field > .v-input__control > .v-input__slot:after {
      border-style: none !important;
  }

And that's it, this is as close as I could get to what you're asking for. 5 years too late but hope it will help someone :)
