### ISSUE TITLE
[Bug Report] Button stays in hover state after being pressed on chrome or mobile

### ISSUE THREAD

**Issue by Fr3027** [vuetifyjs/vuetify#9019]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.5

### Steps to reproduce
Press the regular button

### Expected Behavior
After pressing the button is done, it should have the same state/color as before pressing it.

### Actual Behavior
After the button was pressed, it stays in the hover state until I press somewhere else on the page.

### Reproduction Link
<a href="https://codepen.io/fr3027/pen/XWrxyyd?editors=1010" target="_blank">https://codepen.io/fr3027/pen/XWrxyyd?editors=1010</a>

### Other comments
No problem on safari.

**Comment by MajesticPotatoe** [comment]
duplicate of #8572
