### ISSUE TITLE
[Bug Report] Field validation message changes height of the field 

### ISSUE THREAD

**Issue by ilearnjs** [vuetifyjs/vuetify#9025]
### Environment
**Vuetify Version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.1

### Steps to reproduce
Open the link and pay attention to the line 6

### Expected Behavior
Heights of fields on the right and on the left column are the same

### Actual Behavior
Heights of fields on the right and on the left column are different

### Reproduction Link
<a href="https://codepen.io/ilearnjs/pen/JjPmgVa?editors=1010" target="_blank">https://codepen.io/ilearnjs/pen/JjPmgVa?editors=1010</a>

**Comment by johnleider** [comment]
This was resolved with v2.0: https://codepen.io/johnjleider/pen/NWPYmLv

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
