### ISSUE TITLE
[Bug Report] v-alert transition property has no effect

### ISSUE THREAD

**Issue by gumdrop** [vuetifyjs/vuetify#9033]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Linux x86_64

### Steps to reproduce
This is a forkl of the vuetify codepen linked from the docs.    Open the codepen and click 'Toggle'.  The alert vanishes with no animation.  Click 'Toggle' again, and the alert re-appears, again with no animation.    

### Expected Behavior
The alert display state change should employ the scale-transition animation

### Actual Behavior
The transition does not function

### Reproduction Link
<a href="https://codepen.io/gumdrop/pen/jONQVPB?&editable=true&editors=101" target="_blank">https://codepen.io/gumdrop/pen/jONQVPB?&editable=true&editors=101</a>

### Other comments
This works on the docs page, but not in the codepen and not in my app.  Is there some undocumented special magic missing in the codepen?

**Comment by giddie** [comment]
Is this definitely fixed? I'm seeing the same behaviour with 2.2.19, and updating the above codepen to 2.2.19 seems to confirm it:

https://codepen.io/giddie/pen/XWbGjRm

**Comment by KaelWD** [comment]
@giddie That's using 2.0.18 CSS

**Comment by giddie** [comment]
Are you sure? If so, I'm not sure what I'm missing:

![Screenshot_20200331_170353](https://user-images.githubusercontent.com/10906/78048708-096fa880-7372-11ea-986e-c52cbc3d416e.png)

**Comment by giddie** [comment]
Gotcha! Thanks :)

**Comment by giddie** [comment]
OK, so several transitions do seem to work, but I'm having no luck with `expand-transition` or `expand-x-transition`. Maybe these just aren't the right names to use?
