### ISSUE TITLE
[Bug Report] V-app-bar does work as expected for scroll shrink, hide-on-scroll, collapse-on-scroll, elevate-on-scroll and, inverted-scroll prop

### ISSUE THREAD

**Issue by kamit-transient** [vuetifyjs/vuetify#9034]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Firefox 60.0
**OS:** Linux x86_64

### Steps to reproduce
You can use any of the given example on vuetifyjs.com for app-bar component for hide-on-scroll, collapse-on-scroll, elevate-on-scroll, and inverted-scroll prop

### Expected Behavior
It should work without any use of v-sheet component

### Actual Behavior
v-app-bar component is not working as expected for hide-on-scroll, collapse-on-scroll, elevate-on-scroll, and inverted-scroll prop without v-sheet component.

So please suggest, if there is any workaround for this. if the v-sheet is supposed to be used, then update the documentation for v-app-bar for the same.

### Reproduction Link
<a href="https://codepen.io/kamit_transient/pen/YzKRZxj" target="_blank">https://codepen.io/kamit_transient/pen/YzKRZxj</a>

**Comment by wannikid** [comment]
I got it to work without v-sheet, but I had to set a fixed height on my scrolling element and use class "overflow-hidden". Still, I agree, this could be documented better.

**Comment by kamit-transient** [comment]
Most of the example on app-bar doc is either misleading or not beginner friendly. I got it work by adding adding `app` attribute to `app-bar` and removing those unnecessary sheet and cards given in example.

closing this issue.

**Comment by kamit-transient** [comment]
> I got it to work without v-sheet, but I had to set a fixed height on my scrolling element and use class "overflow-hidden". Still, I agree, this could be documented better.

You do not need to do so

**Comment by aneesshameed** [comment]
User: "This could be documented better."
Vuetify team: Documentation? What does that mean?

**Comment by aneesshameed** [comment]
Below is a code pen link. That's how I did it. What I understood is that you need to add 'app' on to v-app and v-app-bar
https://codepen.io/aaha/pen/YzXwgbR

**Comment by thieleju** [comment]
If anyone comes across this problem, here is how I solved it for a v-app-bar shrink-on-scroll.

``` vue
<template>
  <v-app app id="inspire">
    <v-app-bar app scroll-target="#main">
     <!-- navigation drawer -->
    </v-app-bar>

    <v-sheet max-height="100vh" id="main" style="overflow: auto">
      <v-content>
        <v-container fluid>
	  <!-- router view -->
        </v-container>
      </v-content>
    </v-sheet>
  </v-app>
</template>
```

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
