### ISSUE TITLE
[Bug Report] DatePicker possible dates do not include the minimum date

### ISSUE THREAD

**Issue by esynaps** [vuetifyjs/vuetify#9039]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Initialize a date picker with a min prop

### Expected Behavior
The min date should be available

### Actual Behavior
You cannot select the min date

### Reproduction Link
<a href="https://codepen.io/Alex83690/pen/mdbQxoX" target="_blank">https://codepen.io/Alex83690/pen/mdbQxoX</a>

**Comment by Teellcory** [comment]
I believe it rounds time up to the next day (or something along those lines). If you remove the time, it'll work: https://codepen.io/teellcory/pen/qBWLWXL

**Comment by alexandre-le-borgne** [comment]
Nice workaround. On the other hand, it would be more logical for the date to be rounded down
