### ISSUE TITLE
[Bug Report] v-autocomplete doesn't show value in input

### ISSUE THREAD

**Issue by y-zim** [vuetifyjs/vuetify#9042]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
1. Open drop-down
2. Select any value
3. Clear value by pressing Backspace multiple times
4. When user have empty value in search field press Backspace one more time
5. Select any item from drop-down

### Expected Behavior
Item should be shown in input right after user clicks it

### Actual Behavior
Empty value in input, selected value is shown when input loses focus

### Reproduction Link
<a href="https://codepen.io/y-zim/pen/LYPXgGX" target="_blank">https://codepen.io/y-zim/pen/LYPXgGX</a>

### Other comments
This is reproducible with the default settings: https://vuetifyjs.com/en/components/autocompletes#usage

**Comment by johnleider** [comment]
fixed in 8580c7bb59945158c1b9e8df7da6979a9a394fec and released with v2.1.4
