### ISSUE TITLE
[Bug Report] TreeView - Nodes of the tree with an empty array of children should be treated as a leaf of the tree

### ISSUE THREAD

**Issue by esynaps** [vuetifyjs/vuetify#9043]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Use treeview component with  activatable prop and items without children (null, undefined, empty array)

### Expected Behavior
When you click on these items, they should be considered as activated

### Actual Behavior
Depending on the value of the property, they are either not selectable or selectable but do not change the array of active items

### Reproduction Link
<a href="https://codepen.io/Alex83690/pen/YzKRJYK?editors=1111" target="_blank">https://codepen.io/Alex83690/pen/YzKRJYK?editors=1111</a>

### Other comments
Only items with a property 'children'  of size > 0 should be considered as a branch

**Comment by CavalcanteLeo** [comment]
Any news about it?

I'm facing this on  nuxtjs/vuetify 1.11.2

**Comment by KaelWD** [comment]
This was fixed in Vuetify v2.4.1. `@nuxtjs/vuetify` can use any version of vuetify, you need to upgrade it separately.
