### ISSUE TITLE
[Bug Report] Cannot bind to style attribute on v-container

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#9044]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Create a `v-container` element and try binding to the `style` attribute.

### Expected Behavior
The `style` attribute should bind with the dynamic expression supplied.

### Actual Behavior
The `style` attribute is ignored if used as a binding expression.

### Reproduction Link
<a href="https://codepen.io/dmcknight26/pen/xxKQQXG" target="_blank">https://codepen.io/dmcknight26/pen/xxKQQXG</a>

### Other comments
The example issue linked is very simple and only attempts to bind to hardcoded strings.  I kept the example simple on purpose.  In my application I am performing calculations which need to be dynamically bound to the `style` attribute.

**Comment by esynaps** [comment]
I do not think it's a bug. This syntax is incorrect :

```
    <v-container :style="'background-color:red'">
      <v-row>
        <v-col cols="12">i should have red background</v-col>
      </v-row>
    </v-container>
```

The style property must be an object : 

```
    <v-container :style="{'background-color':'red'}">
      <v-row>
        <v-col cols="12">i should have red background</v-col>
      </v-row>
    </v-container>
```

**Comment by MajesticPotatoe** [comment]
or an array of objects as so:
```
<v-container :style="[{'background-color': 'red'}, {border: '1px solid black'}]">
```

**Comment by KaelWD** [comment]
Duplicate of #8328
