### ISSUE TITLE
[Documentation] update v-data-table options prop

### ISSUE THREAD

**Issue by juhasev** [vuetifyjs/vuetify#9048]
### Problem to solve
Vuetify 2 introduces new props for data table like page, items-per-page, sort-by and sort-desc. Devs will assume that those options will have to synced individually which adds to the complexity of implementation. Options prop also allows sync (missing from documentation) and can handle all of these props. The options -prop is not documented (docs just say refer to examples). I had to convert 20+ tables from Vuetify 1.5 and this made the conversion somewhat painful. If you are using server side pagination you actually have to use the options -prop because you cannot easily watch all the individual sort and page props for changes (as they update in some random order when user click on header sort options).

### Proposed solution
Document v-data-table options property and mention .sync modifier can be used.

**Comment by MajesticPotatoe** [comment]
Awaiting on a PR merge that contains an update to api that allows for expanded details for props and will get in. Thanks for reporting this.

**Comment by WhatFreshHellIsThis** [comment]
Just stumbled across this, yes the Options prop is not documented properly at all and the existing docs are misleading claiming it is documented in an example below which I picked through one by one trying to find but confusingly the one that actually mentions "Options" in the title doesn't use it and the only example that even references it in code doesn't mention it at all in the title and the example: 
https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side
doesn't actually provide any information about Options property at all.
This is a big thing and huge breaking change and perhaps requires a very detailed dedicated section to Options usage and explanation of all the properties alone.

**Comment by exbarboss** [comment]
Any updates on this?

**Comment by MariaPet** [comment]
It would be really useful to update the docs with more information about this prop

**Comment by stildalf** [comment]
I second the sentiment here that the documentation on the `options` prop falls well short of assisting this noob in trying to implement external pagination and sort for the first time - something I would assume to be rather common for a data table, Hasn't helped that of the examples I've found most refer to the now deprecated `pagination` prop with `.sync` modifier. If anyone can point me to a working example using vuex store actions/getters I'd appreciate.

**Comment by WhatFreshHellIsThis** [comment]
I must be missing something here, there doesn't appear to be any new documentation in the resolution?

**Comment by cogscape** [comment]
Indeed, this issue is not resolved. I have no clue why @MajesticPotatoe closed this issue, maybe he can provide some insight?

This may very well be a crucial feature and part of the component's documentation.

**Comment by MajesticPotatoe** [comment]
@cogscape it was closed automatically with the merge of the PR above that added this information to the api as noted.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
