### ISSUE TITLE
[Bug Report] v-chip > href Prop > object problem

### ISSUE THREAD

**Issue by mrgr4v1ty** [vuetifyjs/vuetify#9050]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
When using "href" prop of v-chip for inserting route object, the produced link is not correct.
but if you use @click and link the chip to a function and use the same route object for navigation there, you get a correct link and navigation.

### Expected Behavior
object for href works correctly

### Actual Behavior
inserting object is producing incorrect link

### Reproduction Link
<a href="https://codepen.io/mrgr4vity/pen/BaBvzVY" target="_blank">https://codepen.io/mrgr4vity/pen/BaBvzVY</a>

**Comment by KaelWD** [comment]
It extends `router-link`, you need to use `to` not `href`
