### ISSUE TITLE
[Feature Request] Change initial border for outlined v-text-field

### ISSUE THREAD

**Issue by logol** [vuetifyjs/vuetify#9051]
### Problem to solve
Using the light theme and a v-text-field with the outlined property the border is light grey, black on hover and then get's a thicker border line once it's clicked. Is there a way to have the inactive/initial state look like the hovered one e.g. a thin solid black line?

![2019-09-21_16-38](https://user-images.githubusercontent.com/12373037/65374801-56b9e180-dc8e-11e9-862e-09acf327d9e4.png)

### Proposed solution
May add properties for initial and hover border colors?

**Comment by KaelWD** [comment]
It's part of the material design spec, change `$material-light, 'text-fields', 'outlined'` or target the component's `fieldset` element to override it.
