### ISSUE TITLE
[Bug Report] Component in shadow-root is creating html elements outside shadow-root

### ISSUE THREAD

**Issue by lsshenrique** [vuetifyjs/vuetify#9056]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Create a web component with a vuetify dialog.
Add the web component that was created to html page. 
Run a static server to serve the html and then open the vuetify dialog of the web component.

To shorten...
1. download git repository lsshenrique/vuetify-shadow-root
2. prompt de command:
$ npm install
$ npm run build
$ npm run server
3. open the url browser (that can be): http://localhost:8080/static/index.html

### Expected Behavior
Expected that the html elements of the vuetify dialog were created inside of shadow-root of the web component.

### Actual Behavior
The html elements of the vuetify dialog were created outside of shadow-root where is the web component and this is causing a vuetify css break.
**Initial:**
![image](https://user-images.githubusercontent.com/25511742/65381190-a7e3c880-dcc2-11e9-8070-162d7f713b9d.png)
**Dialog opened:**
![image](https://user-images.githubusercontent.com/25511742/65381205-06a94200-dcc3-11e9-9210-ab647147e8c9.png)

### Reproduction Link
<a href="https://github.com/lsshenrique/vuetify-shadow-root" target="_blank">https://github.com/lsshenrique/vuetify-shadow-root</a>

### Other comments
I don't know if this behavior is exactly a bug or a configuration. I would like a direction to try solve this.

**Comment by MajesticPotatoe** [comment]
Dialogs (and other overlay components) attach themselves to the root `v-app` element by default. to attach them to a specific component, specify the `attach` prop.

**Comment by lsshenrique** [comment]
Thanks @MajesticPotatoe for your response!

Upon your response, I went to use the attach prop, but it didn't work.
![image](https://user-images.githubusercontent.com/25511742/65392948-271fdd80-dd51-11e9-9fd2-816e8ec3cc20.png)

The console showed the message:
![image](https://user-images.githubusercontent.com/25511742/65392919-c98b9100-dd50-11e9-91ce-09aa19ad94d2.png)

Ok, so I removed the attach prop and got a new message:
![image](https://user-images.githubusercontent.com/25511742/65392897-7fa2ab00-dd50-11e9-83cf-c3f27e675cc8.png)

But it's strange, because there are the data-app element and the #vcontent element:
![image](https://user-images.githubusercontent.com/25511742/65392939-0b1c3c00-dd51-11e9-9e35-933f6bf2b59e.png)

### Possible cause of the problem
Tracking vuetify dialog rendering I found the **initDetach** method located in **mixins/detachable** that get the **page document** and use the querySelector to search the element to attach.

```javascript
if (this.attach === false) {
        // Default, detach to app
	target = document.querySelector('[data-app]');
} else if (typeof this.attach === 'string') {
	// CSS selector
	target = document.querySelector(this.attach);
} else {
	// DOM Element
	target = this.attach;
}

if (!target) {
	consoleWarn(`Unable to locate target ${this.attach || '[data-app]'}`, this);
	return;
}
```

The problem is that when it is a **web-component** it has **shadow-root** and elements within the shadow are **not accessible by querySelector of the page document**.

### Suggestion for correction/improvement
In this case, instead of using the page **document** as a base, we should use the **shadow-root (only if necessary)**, that is, using the code described below, we would have the expected result when it was a **web-component**.

```javascript
if (this.attach === false) {
	// Default, detach to app
	let _document = this.getDocument();
	target = _document.querySelector('[data-app]');
} else if (typeof this.attach === 'string') {
	// CSS selector
	let _document = this.getDocument();
	target = _document.querySelector(this.attach);
} else {
	// DOM Element
	target = this.attach;
}

getDocument() {
	let element = this.$refs.content;

	if (!element) return document;

	while (element.parentNode && (element = element.parentNode)) {
		if (element instanceof ShadowRoot) {
			return element;
		}
	}

	return document;
}
```

What do you think about this?
