### ISSUE TITLE
[Feature Request] Calendar fixed-width day field in month view

### ISSUE THREAD

**Issue by monikadulik** [vuetifyjs/vuetify#9058]
### Problem to solve
When an event has long name, VCalendar component in month view changes width of certain day field to accommodate long event name.

### Proposed solution
Add property that can set month calendar grid as 'fixed-width' so every day field in calendar is of the same width despite event names..

It works as expected after following change:
from
.v-calendar.v-calendar-events .v-calendar-weekly__day {
    overflow: visible;
}
to
.v-calendar.v-calendar-events .v-calendar-weekly__day {
    overflow: hidden;
}

**Comment by igadmile** [comment]
This is the reproduction [reproduction](https://codepen.io/igadmile/pen/vYBPgWE) link.

Proposed fix would add borders between days. Proper fix should be to add `min-width: 0` to `.v-calendar-weekly__day`.

The root of the issue is the same as in #8319
