### ISSUE TITLE
v-footer exceed the screen

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#906]
https://jsfiddle.net/Ewocker/dwgzvoem/

The footer exceed the screen size in v0.13, which is not the same as in v0.12.

**Comment by johnleider** [comment]
The provided codepen does not include a v-footer, also:

When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
