### ISSUE TITLE
[Bug Report] app bar title in mobile is truncated even when bar is expanded

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#9061]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
Set the browser to mobile view or reduce the width of the window

### Expected Behavior
I expect to see a longer title in the app-bar when the app bar is expanded. When I scroll and the app-bar shrinks the title should be truncated (and this happens!).

### Actual Behavior
The title is truncated both with the expanded and shrunk bar

### Reproduction Link
<a href="https://codepen.io/lucafaggianelli/pen/zYOyLxy?&editable=true&editors=101" target="_blank">https://codepen.io/lucafaggianelli/pen/zYOyLxy?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Unfortunately this is not possible with the structure I used to create the shrinking text functionality. If it is possible, it would be very low priority.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
