### ISSUE TITLE
[Bug Report] Incoherent "focussed" color for text field

### ISSUE THREAD

**Issue by matthieusieben** [vuetifyjs/vuetify#9065]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a form with a "v-text-field", focus the field

### Expected Behavior
The outline color should be consistent with other input colors ("accent")
<img width="361" alt="Capture d’écran 2019-09-23 à 11 09 47" src="https://user-images.githubusercontent.com/813661/65413854-af09f400-ddf2-11e9-9659-ca00c75d74a8.png">

### Actual Behavior
The text-field outline has a "primary" color
<img width="361" alt="Capture d’écran 2019-09-23 à 11 07 47" src="https://user-images.githubusercontent.com/813661/65413762-6b16ef00-ddf2-11e9-95d4-781395fe76ec.png">

### Reproduction Link
<a href="https://codepen.io/matthieusieben/pen/XWrowbg" target="_blank">https://codepen.io/matthieusieben/pen/XWrowbg</a>

### Other comments
It is weird that the text field hase the same color, when focussed, as the "submit" button (primary) whereas other form input element are using an accent color.

**Comment by KaelWD** [comment]
MD1 spec shows text fields as primary and says selection controls should use the accent color. MD2 says secondary for selection controls but we haven't changed the theme system yet so that isn't relevant.
