### ISSUE TITLE
[Bug Report] v-menu list item width on IE11

### ISSUE THREAD

**Issue by Nyami** [vuetifyjs/vuetify#9067]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
In IE11, the width of the list items under the menu does not automatically expand to fit content

### Expected Behavior
List, and list item content is fully visible

### Actual Behavior
Content is truncated

### Reproduction Link
<a href="https://github.com/Nyami/vuetify-playground/tree/v-menu" target="_blank">https://github.com/Nyami/vuetify-playground/tree/v-menu</a>

### Other comments
This appears to only occur in IE11, other browsers work as expected

**Comment by mseele** [comment]
duplicate of #8338?

**Comment by Nyami** [comment]
Yes, this is a duplicate of #8338
