### ISSUE TITLE
Allow font awesome icons in Text fields

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#907]
### What will it allow you to do that you can't do today?
Allow font awesome icons in Text fields (`v-text-field`) props: `append-icon` and `prepend-icon`.
### How will it make current work-arounds straightforward?
Right now, I'm not aware of any workaround.
### What potential bugs and edge cases does it help to avoid?
This could prevent some hacks, trying to use `v-icon` with `v-text-field`, since `v-icon` already has support for **Font Awesome**
### Versions
0.13

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by jvbianchi** [comment]
I updated the issued, is it ok now?

**Comment by xplodwild** [comment]
+1, except that I'd like to use MDI icons in my textfields

**Comment by johnleider** [comment]
Are you a mind reader, I'm working on this right now :>

**Comment by xplodwild** [comment]
I probably am :) Thanks for the great work! The latest release is amazing, and can't wait the next one.

**Comment by nekosaur** [comment]
Should be fixed by #1044

**Comment by johnleider** [comment]
Confirm fixed with #1044
