### ISSUE TITLE
[Feature Request] v-carousel set time offset for first transition

### ISSUE THREAD

**Issue by blsho** [vuetifyjs/vuetify#9070]
### Problem to solve
I have multiple carousels on the same page set to the same interval value. Transitions of those carousels automatically start and end at the same moment - which I don't want to.

### Proposed solution
Introduce new prop `interval-offset` which will be applied only for first transition when interval will be calculated as `interval` + `interval-offset`

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
