### ISSUE TITLE
[Bug Report] Missing v-col prop for extra small  breakpoints (xs)

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#9077]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OS 10.15

### Steps to reproduce
Just by trying to use the "xs"-breakpoint property. When the extra small screen size gets triggered nothing happens. 

### Expected Behavior
There should be a xs property like for each other breakpoint (sm, md, lg, xl)

### Actual Behavior
The xs breakpoint is not implemented in the 2.x grid system. In the 1.x grid system it was implemented and worked fine

### Reproduction Link
<a href="https://jsfiddle.net/valentingavran/0xdfLwrk/19/" target="_blank">https://jsfiddle.net/valentingavran/0xdfLwrk/19/</a>

**Comment by nekosaur** [comment]
You are already using the `cols` prop which is the 2.0 equivalent of `xs`

**Comment by valentingavran** [comment]
It should, in my opinion, be better highlighted in the documentation.
