### ISSUE TITLE
[Bug Report] v-bottom-sheet dont append at root element (v-app)

### ISSUE THREAD

**Issue by simplecard** [vuetifyjs/vuetify#9078]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Windows 10

### Steps to reproduce
layout overlay hide the bottom sheet menu because it is rendered at the same element, not at the root element (v-app)

### Expected Behavior
the bottom sheet will be before the overlay that he can be clicked

### Actual Behavior
layout overlay hide the bottom sheet menu because it is rendered at the same element, not at the root element (v-app)

**Comment by johnleider** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify. 
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
