### ISSUE TITLE
Row and column based on breakpoint not working in 0.13 anymore

### ISSUE THREAD

**Issue by vuessy** [vuetifyjs/vuetify#908]
BUG REPORT

### Steps to reproduce
Visit https://vuetifyjs.com/layout/grid (version 0.13)
and look at "#5 Row and column based on breakpoint" on a large screen,
Three rows are being displayed.

### Versions
Vuetify 0.13, latest greatest Chrome and Vue

### What is expected ?
Compare to same thing in 0.12
On large screen only one row is shown and it changes to a column only when you make the browser window smaller.

### What is actually happening ?
Three rows are being displayed.
Found problem in other self-made examples

### Reproduction Link
https://vuetifyjs.com/layout/grid

Thanks in advance.
You are doing a great job!

**Comment by johnleider** [comment]
I've gotta stop drinking at night.

**Comment by dbjoomla** [comment]
Thanks John, for your precious work, high yet ;)
