### ISSUE TITLE
[Bug Report] Cannot start app locally in MS Edge

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#9085]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
* Begin new project with vue-cli via `vue create edge`
* Start vue-cli UI interface via `vue ui`
* Add the vue-cli-vuetify plugin through the UI interface
* Start the app locally for development via `npm run serve`

### Expected Behavior
The application is accessible.

### Actual Behavior
Edge displays a white page with a console error `SCRIPT1028: SCRIPT1028: Expected identifier, string or number` which appears to be originating from inside the `mergeData.js` utility.

### Reproduction Link
<a href="https://jsfiddle.net/fvkqxh03/" target="_blank">https://jsfiddle.net/fvkqxh03/</a>

### Other comments
Works in both Chrome (latest) and Firefox (latest).  `mergeData.js` appears to be using the spread operator which I don't believe is supported in Edge yet.

Are they any additional settings that need to be configured for Edge support?  I see it listed as a supported browser but wasn't sure if I need to include additional libraries or babel settings for this to work.

**Comment by dmcknight26** [comment]
I finally found the note in the FAQ and applied the `transpileDependencies: ['vuetify']` option.  Can we perhaps get this added into the quick start guide as it seems necessary for Edge to work?

**Comment by MajesticPotatoe** [comment]
This does exist there. Actually has a section dedicated to it.
https://vuetifyjs.com/en/getting-started/quick-start#edge-support

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by burunin** [comment]
still have exact issue
