### ISSUE TITLE
[Feature Request] Typography classes inconsistent with Material definitions

### ISSUE THREAD

**Issue by aantipov** [vuetifyjs/vuetify#9086]
### Problem to solve
Vuetifyjs implements its Typography system via the following classes:
- .display-4, .display-3, .display-2, .display-1, .headline, .title, .subtitle-1, .subtitle-2, .body-1, .body-2, .caption and .overline

Material's type system supports the [following variants of text](https://material.io/design/typography/the-type-system.html):
- h1, h2, h3, h4, h5, h6, Subtitle 1, Subtitle 2, Body 1, Body 2, Button, Caption, Overline

So the correspondence map should be the following:
.display-4 = h1, 
.display-3 = h2, 
.display-2 = h3, 
.display-1 = h4, 
.headline = h5, 
.title = h6, 
.subtitle-1 = Subtitle 1, 
.subtitle-2 = Subtitle 2, 
.body-1 = Body 1, 
.body-2 = Body 2, 
.caption = Caption
.overline = Overline

The problem is that when your design uses Material definitions and you need to translate them into VuetifyJS, then it becomes a problem, because fist 6 matches are non-trivial and hard to remember.

### Proposed solution
To better match the Material spec for Typography, we need to use similar text class names.

For example, by doing the following renamings:
.display-4 => .head-1, 
.display-3 => .head-2, 
.display-2 => .head-3, 
.display-1 => .head-4, 
.headline => .head-5, 
.title => .head-6,

**Comment by MajesticPotatoe** [comment]
Related: #6258

**Comment by KaelWD** [comment]
These are the original names that were kept to reduce the number of breaking changes: https://material.io/archive/guidelines/style/typography.html#typography-styles

**Comment by aantipov** [comment]
> These are the original names that were kept to reduce the number of breaking changes: https://material.io/archive/guidelines/style/typography.html#typography-styles

OK, I see now. Makes sense 👍  But now its really confusing all the new users who uses the new Material spec.

**Comment by johnleider** [comment]
Resolved as of https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0-beta.3

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
