### ISSUE TITLE
[Bug Report] VAutocomplete does not emit focus when tab is focused again

### ISSUE THREAD

**Issue by literallyliterature** [vuetifyjs/vuetify#9089]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Focus on a v-autocomplete (or v-select) field.
Focus out of the tab. blur event is emitted
Focus back into the tab. The v-autocomplete remains focused, but the focus event is not emitted.

### Expected Behavior
The focus event should be emitted by VAutocomplete (and other components where this does not happen) when the automatically gain focus because of the tab or window getting focused again.

### Actual Behavior
The focus event is not emitted when VAutocomplete automatically gains focus because of the window or tab being refocused.

### Reproduction Link
<a href="https://codepen.io/literallyliterature/pen/oNvVLPN" target="_blank">https://codepen.io/literallyliterature/pen/oNvVLPN</a>

### Other comments

Note that the VTextField already exhibits the expected functionality.

**Comment by jacekkarczmarczyk** [comment]
s/counter/focusedCount
