### ISSUE TITLE
<v-toolbar-side-icon> 

### ISSUE THREAD

**Issue by Emptyless** [vuetifyjs/vuetify#909]
### Steps to reproduce
1. Clean install vue-electron (https://github.com/SimulatedGREG/electron-vue)
2. Add jQuery and Materialize-css (jQuery 2.2.4 latest Materialize-css) 
3. Add Vuetify (yarn install) 
4. Use #6 Persistent Layout template

### Versions

Chromium browser of Electron
Latest version of Vue
Latest version of Vuetify
MacOS

### What is expected ?

Expected <v-toolbar-side-icon> behavior is a circular menu button

### What is actually happening ?

There is a spherical menu button (see attached image)
<img width="453" alt="schermafbeelding 2017-07-06 om 12 19 41" src="https://user-images.githubusercontent.com/1910691/27907003-10d1418c-6246-11e7-9807-e96a668543f2.png">

### Reproduction Link

? Do I need to upload a copy of my code here?  ?

**Comment by nekosaur** [comment]
Can I ask the reason why you're using both materialize and vuetify? It's not impossible that the error is due to conflicting CSS.

**Comment by Emptyless** [comment]
@nekosaur That was it indeed. I assumed they were linked, sorry.
