### ISSUE TITLE
[Bug Report] v-file-input rules and multiple tag doesn't work properly together

### ISSUE THREAD

**Issue by AyushiBShah** [vuetifyjs/vuetify#9090]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
When you pick a file which is below size still error count sets to 1. Rules aren't getting checked

### Expected Behavior
It shouldn't show error if file size is below limit for all files selected combined

### Actual Behavior
Currently error comes up as soon as any file is selected

### Reproduction Link
<a href="https://codepen.io/ayushibshah/pen/zYObKzY?&editable=true&editors=101" target="_blank">https://codepen.io/ayushibshah/pen/zYObKzY?&editable=true&editors=101</a>

**Comment by nekosaur** [comment]
When using `multiple` prop, value is an array https://codepen.io/nekosaur/pen/QWLoGPE?editors=1010

**Comment by AyushiBShah** [comment]
@nekosaur : Thank you for the response!
