### ISSUE TITLE
[Bug Report] V-data-table for server side sorting with must-sort doesn't work

### ISSUE THREAD

**Issue by Kutkov** [vuetifyjs/vuetify#9093]
### Environment
**Vuetify Version:** 2.0.18
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Linux x86_64

### Steps to reproduce
Set `options.sync = options`, and look on options object

### Expected Behavior
Add default properties (sortBy and sortDesc) in `options` when using `must sort`

### Actual Behavior
At initialization, the properties (sortBy and sortDesc) are empty.

### Reproduction Link
<a href="https://codepen.io/kutkov/pen/bGbZgGp" target="_blank">https://codepen.io/kutkov/pen/bGbZgGp</a>

**Comment by nekosaur** [comment]
I am not understanding the issue? You say expected behaviour should be that `sortDesc` and `sortBy` are present in `options`, but they _are_ present in the codepen?

**Comment by Kutkov** [comment]
@nekosaur Yes they are present but they are empty (`sortDesc = []`, `sortBy = []`).
>
For example:
>In vuetify 1.5
```vue
<v-data-table
    :headers="headers"
    :pagination.sync="pagination"
    must-sort
></v-data-table>
<script>
    export default {
        data () {
            return {
                headers: [
                  { text: 'Name', value: 'name' },
                  { text: 'E-mail', value: 'email' }
                ],
                pagination: {}
            }
        },
        mounted () {
            this.pagination // { sortBy: "name", descending: false, ... }
        }
    }
</script>
```
>In vuetify 2.0
```vue
<v-data-table
    :headers="headers"
    :options.sync="options"
    must-sort
></v-data-table>
<script>
    export default {
        data () {
            return {
                headers: [
                  { text: 'Name', value: 'name' },
                  { text: 'E-mail', value: 'email' }
                ],
                options: {}
            }
        },
        mounted () {
            this.options // { sortBy: [], sortDesc: [], ... } but Expected Behavior { sortBy: ['name'], sortDesc: [false], ... }
        }
    }
</script>
```

**Comment by nekosaur** [comment]
That is by design, and is documented in the migration guide for 2.0. The data-table (and data-iterator) will no longer automatically sort on first column.

**Comment by Kutkov** [comment]
@nekosaur Oh, I just realized why I got an error when trying to set the parameters myself.
Thanks, and I apologize for this issue.
