### ISSUE TITLE
[Bug Report] Combobox with chip & multiple & hide-selected has bug on select in v-menu with enter key

### ISSUE THREAD

**Issue by florealcab** [vuetifyjs/vuetify#9095]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chromium 76.0.3809.100
**OS:** Ubuntu undefined

### Steps to reproduce
Define a v-combobox like this:
```
<v-combobox
         :items="['Test', 'Value1', 'Value2']"
         multiple
         hide-selected
         chips
         deletable-chips
         autofocus
         label=""
>
</v-combobox>
```

Important: add chip, multiple and hide-selected options

### Expected Behavior
Start writing "Va", and use keyboard arrows to highlight the value "Value1". Select the value with the "enter" key. "Value1" chip is added to the selection, and only this.

### Actual Behavior
There is another chip "Va" which is added to the selection.

### Reproduction Link
<a href="https://codepen.io/florealc/pen/VwZRXwg" target="_blank">https://codepen.io/florealc/pen/VwZRXwg</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #8841

**Comment by florealcab** [comment]
Thank you, the workaround solves my problem :)
