### ISSUE TITLE
[Feature Request] add type 'year' for v-date-picker

### ISSUE THREAD

**Issue by robin-dongbin** [vuetifyjs/vuetify#9096]
### Problem to solve
As the title suggests

### Proposed solution
As the title suggests

**Comment by Steeve55** [comment]
I agree with this request, I need this too please.

**Comment by WaldemarEnns** [comment]
Yes, I need this feature too - would be nice to have it in the next release! :)

**Comment by script-anzcro** [comment]
It looks like the feature is there, but the validator doesn't like it.
If I use type='year' the calendar will open the year list which is what I want.

Maybe I mis-using the property type.

If I should use something else to open the year list first please let me know.

**Comment by jacekkarczmarczyk** [comment]
This is feature request for date picker showing only the year panel (just for selecting year instead of year-month or full date).
If you want to be able to select the full date but just having year panel opened initially then look at the birthday picker example <https://vuetifyjs.com/en/components/date-pickers/#date-pickers-birthday-picker>

**Comment by script-anzcro** [comment]
> This is feature request for date picker showing only the year panel (just for selecting year instead of year-month or full date).
> If you want to be able to select the full date but just having year panel opened initially then look at the birthday picker example https://vuetifyjs.com/en/components/date-pickers/#date-pickers-birthday-picker

Thanks,date-pickers-birthday-picker is what I need :)

**Comment by Steeve55** [comment]
Has this feature been taken into account by the dev vuetify team ?

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/87797024-75571d80-c84a-11ea-9597-5bf4d6028d0e.png)

But why not just use v-select or v-autocomplete if it's only selecting year?

**Comment by Steeve55** [comment]
> ![image](https://user-images.githubusercontent.com/15625235/87797024-75571d80-c84a-11ea-9597-5bf4d6028d0e.png)
> 
> But why not just use v-select or v-autocomplete if it's only selecting year?

Because for my use, the "v-date-picker" is used for all date choices. I don't want to change this by confusing the user with another widget when it's a date too. I want it to look the same visually. Do you understand me ?

**Comment by belov38** [comment]
It seems this feature implemented (as my vuetify==2.4.0).
Pls describe it in the [API  section](https://vuetifyjs.com/en/api/v-date-picker/)

**Comment by barbarakr** [comment]
Doesn't seem to be implemented yet: Also in current master, there is only month and täte possible: https://github.com/vuetifyjs/vuetify/blob/d3de71bfc4db0180c5f8d269dc02c030ea5fa4a0/packages/vuetify/src/components/VDatePicker/VDatePicker.ts#L128

**Comment by danieeis** [comment]
sounds great that can would have this  :(

**Comment by mavyfaby** [comment]
Any updates?

**Comment by McHulotte** [comment]
Yes it would be great so type would take much more sense having a year and maybe a week selection ?

**Comment by alanscordoba** [comment]
I'm also waiting for this to be added

**Comment by hogivano** [comment]
> I'm also waiting for this to be added

Me too

**Comment by bushuosx** [comment]
this Feature should be add !

**Comment by marioBaltiSolar** [comment]
I don't know why they didn't add it yet

**Comment by Steeve55** [comment]
Hello, why it's closed ? It's done ?

**Comment by johnleider** [comment]
https://play.vuetifyjs.com/#eNpVj8EKwjAQRH9l3UsVbIsoCFIFb/6BB+shpKsGmyZs0oqU/rtpq2BPuzsMb2YvLTqW6dHapKkJd5h50rYUng55BZA1sbB2WIdDmsoLVRF/pUEsgju2Sj6JoVH0irUpaJ/jmwTnCA9VUCykV6Zyhyyd+H/koE7RvTImZ+lfo3A6ycp6cOTrsZjS1rCHFphu0MGNjYYoPBP1doDAdR60u8O+d8yjE5WlgbPhsphFiz5gRAYYdktcJ+tkg+NcbfH6AR1wXy4=

**Comment by robin-dongbin** [comment]
@johnleider This feature request is request a type `year` for a `Year Picker` only. not for a `Date picker` with year view.

ref:
This is a month picker
https://v2.vuetifyjs.com/zh-Hans/components/date-pickers-month/#section-4f7f7528

@jacekkarczmarczyk has explained it.
https://github.com/vuetifyjs/vuetify/issues/9096#issuecomment-660003163

**Comment by Steeve55** [comment]
Indeed, I thought it still wasn't right. We should reopen this ticket.

**Comment by WaldemarEnns** [comment]
> https://play.vuetifyjs.com/#eNpVj8EKwjAQRH9l3UsVbIsoCFIFb/6BB+shpKsGmyZs0oqU/rtpq2BPuzsMb2YvLTqW6dHapKkJd5h50rYUng55BZA1sbB2WIdDmsoLVRF/pUEsgju2Sj6JoVH0irUpaJ/jmwTnCA9VUCykV6Zyhyyd+H/koE7RvTImZ+lfo3A6ycp6cOTrsZjS1rCHFphu0MGNjYYoPBP1doDAdR60u8O+d8yjE5WlgbPhsphFiz5gRAYYdktcJ+tkg+NcbfH6AR1wXy4=

Thank you! Didn't know I can do that and initially view the year-selection. 👍🏼

> @johnleider This feature request is request a type `year` for a `Year Picker` only. not for a `Date picker` with year view.
> 
> ref: This is a month picker https://v2.vuetifyjs.com/zh-Hans/components/date-pickers-month/#section-4f7f7528
> 
> @jacekkarczmarczyk has explained it. [#9096 (comment)](https://github.com/vuetifyjs/vuetify/issues/9096#issuecomment-660003163)

I agree, I also thought it was clear in this ticket. Would be nice if we can re-open this ticket to get a dedicated picker for _only_ year-selection.
