### ISSUE TITLE
[Bug Report] V-dialog: persistent property is cancelled out by hide-overlay

### ISSUE THREAD

**Issue by jeep-chan** [vuetifyjs/vuetify#9099]
### Environment
**Vuetify Version:** 2.0.19
**Last working version:** 2.0.0-beta.8
**Vue Version:** 2.5.22
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Use persistent and hide-overlay props in a v-dialog.

### Expected Behavior
V-dialog should not close when you click outside of dialog box.

### Actual Behavior
V-dialog closes when you click outside of dialog box.

### Reproduction Link
<a href="https://codepen.io/jeepchan/pen/ZEzPqZK" target="_blank">https://codepen.io/jeepchan/pen/ZEzPqZK</a>

**Comment by MajesticPotatoe** [comment]
duplicate of #8697
