### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by cschweda** [vuetifyjs/vuetify#91]
The updates look great -- especially the source code display in the documentation. But one thing that would be really nice -- especially when trying to piece together how each component fits (or doesn't fit) together (like the navbar and sidebar) -- would be several examples in this repo.

In fact, I wish you'd include the actual site as part of the source. (I realize you might be hesitant to do this.)

The layout examples are great -- but much of the actual implementation is missing. It'd be nice, for example, to see some fully functional example layouts.

Still, what you've got here is fantastic. Really nice. Plan to use it shortly for a project (once I figure out the sidebar.)

**Comment by johnleider** [comment]
I completely agree. As far as the site being part of the source, it is currently in a repository under this company. I just don't want to include it within the source of this repository. You can see it [here](https://github.com/vuetifyjs/docs).

As far as more in-depth examples, they are coming. Come join us on gitter when you start your project. Thank you for the feedback.
