### ISSUE TITLE
[Bug Report] Using v-tab-slider with v-tabs breaks the tabs

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9101]
### Environment
**Vuetify Version:** 2.1.0-beta.0
**Last working version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Can see the issue on page load

### Expected Behavior
Tabs span full width

### Actual Behavior
Giant white bar on left of tabs. Can see it on the doc page here on the few examples that use v-tab-slider
https://dev.vuetifyjs.com/en/components/tabs

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/ZEzPPmR?&editable=true&editors=101#anon-login" target="_blank">https://codepen.io/sneaky666/pen/ZEzPPmR?&editable=true&editors=101#anon-login</a>

**Comment by johnleider** [comment]
That's because you put an arbitrary tab-slider into the markup. https://codepen.io/johnjleider/pen/yLBwWrV?&editable=true&editors=101#anon-login

**Comment by TheInvoker** [comment]
I don't understand, my codepen was literally the one taken from the documentation page. I did not modify it. Also this is the way I set the color of the underline on the active tab.  If it's not supposed to be there, how do I set that color?

**Comment by johnleider** [comment]
Disregard, misunderstood the issue.

**Comment by putrasurya** [comment]
https://vuetifyjs.com/en/components/tabs#examples

All example also not working.

**Comment by johnleider** [comment]
Resolved in 1c0f0ad17 . Will go out today.
