### ISSUE TITLE
[Bug Report] [v-text-field] In dense mode, when it is not outlined, the fieldname disappears

### ISSUE THREAD

**Issue by cafedo** [vuetifyjs/vuetify#9105]
### Environment
**Vuetify Version:** 2.1.0-beta.0
**Vue Version:** 2.6.10
**Browsers:** Edge 78.0.276.2
**OS:** Windows 10

### Steps to reproduce
See codepen

### Expected Behavior
When a text field is dense, not outlined and the user enters a text, I'll expect that the label goes in the top part of the control

### Actual Behavior
When a text field is dense, not outlined and the user enters a text, the label disappear

### Reproduction Link
<a href="https://codepen.io/cafedo/pen/OJLGLZG?&editable=true&editors=101" target="_blank">https://codepen.io/cafedo/pen/OJLGLZG?&editable=true&editors=101</a>

**Comment by DRoet** [comment]
@melbahja friendly ping since u are the PR author for `dense`

**Comment by melbahja** [comment]
dense in md desnse not clear, but if john want this i will open a new PR 
https://codepen.io/dev0x0/pen/ExYJVKE

**Comment by melbahja** [comment]
in dense mode non outlined are single line
https://github.com/vuetifyjs/vuetify/blob/v2.1.0-beta.0/packages/vuetify/src/components/VTextField/VTextField.ts#L139

**Comment by MajesticPotatoe** [comment]
@melbahja we had discussed this in discord. I requested @cafedo to make the PR. Label should remain, as there is a spec for it to exist in a non-outline scenario, and users can choose to toggle it off using the `single-line` prop

**Comment by melbahja** [comment]
I didn't see it in discord :), ok i will open a new PR to fix this

**Comment by MajesticPotatoe** [comment]
(apparently GH is being weird and wont let me update, but i meant this issue not the PR).
Should be pretty easy fix. Dense text field with a label should be 52dp height.

**Comment by cafedo** [comment]
Ok, thanks @melbahja for the support and thanks @melbahja for the PR that you will develop.

**Comment by cafedo** [comment]
Ok, thanks @MajesticPotatoe for the support and thanks @melbahja for the PR that you will develop.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/8810#issuecomment-533851827
