### ISSUE TITLE
[Feature Request] [v-text-field] Give the possibility to leave the label on top also when the field hasn't the focus and is empty (specially in the outline mode)

### ISSUE THREAD

**Issue by cafedo** [vuetifyjs/vuetify#9106]
### Problem to solve
For the user point of view, when he/she fills a form composed by a lot of v-text-fields in outline mode: 
- it is not always clear using the label as a watermark when a v-text-field is not filled; a lot of our user prefer to have the v-text-field empty but with label present on top.
- it is much more clear having the label of each v-text-fields fixed in a certain position instead of having a transition that moves the label when the v-text-fields gets focus.

### Proposed solution
Add a prop `fix-label-on-top` that keeps the label in the top position when the v-text-field has not the focus and is empty

**Comment by KaelWD** [comment]
An empty placeholder will do this (`placeholder=" "`)

**Comment by MajesticPotatoe** [comment]
duplicate #5753
