### ISSUE TITLE
[Bug Report] v-img responsiveness broken with v-container and fill-height

### ISSUE THREAD

**Issue by xalunda** [vuetifyjs/vuetify#9107]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.13.6
### Steps to reproduce
Codepen shows 3 cases. Resize window to mobile size.

* Not working: `<v-container fill-height>` with `<v-img>`. 

* Working: to make responsiveness work properly,  I had to either remove `fill-height` from the container, or add `aspect-ratio` to the img

### Expected Behavior
Case 1 should resize image properly

### Actual Behavior
It's not

### Reproduction Link
<a href="https://codepen.io/xalunda/pen/RwbOwVX" target="_blank">https://codepen.io/xalunda/pen/RwbOwVX</a>

### Screen Shot
![Screen Shot](https://user-images.githubusercontent.com/2316221/65673599-00a8bd80-e043-11e9-958f-3fa256ce683a.png)

**Comment by KaelWD** [comment]
Fixed by #9731
