### ISSUE TITLE
[Bug Report] Object select with value-comparator

### ISSUE THREAD

**Issue by raphael-jolimoi** [vuetifyjs/vuetify#9108]
### Environment
**Vuetify Version:** 2.1.0-beta.0
**Vue Version:** 2.6.9
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
Create a select input with return-object at true and pass a function to value-comparator so that the selected item is correctly shown in the select input. Use object with unique IDs so that there is no possibility of not knowing which object from the list was selected. 

### Expected Behavior
The selected item updates the v-model variable correctly AND this value is shown both in the input and in the options dropdown

### Actual Behavior
The first element is shown as selected

### Reproduction Link
<a href="https://codepen.io/raphael-jolimoi/pen/JjPVodg" target="_blank">https://codepen.io/raphael-jolimoi/pen/JjPVodg</a>

### Other comments
I have weird behaviors on my project where the selected item is shown correctly but all the options are highlighted in the dropdown , I couldn't get to reproduce it.

**Comment by KaelWD** [comment]
If you place a breakpoint you'll see that the function only receives the values, not the complete object: https://github.com/vuetifyjs/vuetify/blob/77d2c4b5d2c7bdbb1d663c12b89ff75662a57539/packages/vuetify/src/components/VSelect/VSelect.ts#L791-L794

**Comment by Glandos** [comment]
I am currently facing the same issue, but with `VAutocomplete`.
After a long search I solved it by using the following property:
```vue
:item-value="(item) => item"
```
It tells everything to use the object as the value, and the fallback in `getPropertyFromItem`.

It worked flawlessly in the codepen.

**Comment by dews** [comment]
This issue is fixed when I update vuetify to 2.6.13.
