### ISSUE TITLE
[Documentation] Provide better search engine in documentation

### ISSUE THREAD

**Issue by putrasurya** [vuetifyjs/vuetify#9109]
### Problem to solve
sometime we forgot the casual name of the component, rather than memorize Group Buttons, we more likely memorize <v-btn-toggle />

the search engine in documentation does not provide this.

### Proposed solution
make search engine in documentation support to syntax searching, like when we search for <v-btn-toggle /> then it will provide API documentation for this one.

thanks

**Comment by MajesticPotatoe** [comment]
There's little we can do in terms of what the search engine crawls and provides back as search results, as its handled automatically by algolia.
