### ISSUE TITLE
[Feature Request] Provide now line on vcalendar (day, 4 day and week views)

### ISSUE THREAD

**Issue by iamgmd** [vuetifyjs/vuetify#9110]
### Problem to solve
Gives visual representation of the current time in the calendar

### Proposed solution
Inject a red (or any other colour) line at the current time viewed in the vcalendars day, 4 day or week views. This line should be reactive and move automatically when the current time changes by 1 minute in the background. Styling of the line should be configurable, its not uncommon to see in other examples, a small triangle at the beginning of the line or a small text of the current time on the left hand side of the line.

**Comment by sajjadali487** [comment]
{ v-calendar } View More Button not showing on all days if a single date has 4 events, the other date has same 4 events it shows only viewmore button or sometime shows event with view more button on different dates. I don't know what is the flow of v-calendar event binding.

For Example :

20-12-2019 has 4 event 2 are multi days and 2 are normal day, it shows "2 more" but same scenario on different dates its behaviour changed. Sometime show 4 events or sometime show only view more button when i click on that then show 4 event inside day view why this is not showing on initialization of map with same behaviour.

Second thing, i want to developed custom template when i pass my data to template then multi day events functionality not worked only shows single day event.
![image](https://user-images.githubusercontent.com/58727918/70520029-b5407e80-1b5e-11ea-86f0-df2ce345256b.png)

**Comment by sajjadali487** [comment]
![image2](https://user-images.githubusercontent.com/58727918/70520398-50d1ef00-1b5f-11ea-9bc0-4c76f2e05428.png)

**Comment by ClickerMonkey** [comment]
The event rendering logic is being redone as we speak and it resolves those issues mentioned.  Your issues are also unrelated entirely from this particular FR, so please create new issues for issues you find.
