### ISSUE TITLE
[Bug Report] Autocomplete losing focus when trying to set focus programatically

### ISSUE THREAD

**Issue by mseele** [vuetifyjs/vuetify#9113]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
- Open https://codepen.io/mseele/pen/XWrQdPM
- Click on "Focus" button
- Autocomplete gets focus (correct)
- Click on "Focus" button, again
- Autocomplete loses focus (incorrect)

### Expected Behavior
- Open snippet
- Click on "Focus" button
- Autocomplete gets focus
- Click on "Focus" button, again
- Autocomplete gets (remains) focus

This works correct for textfield: https://codepen.io/mseele/pen/zYOXBrp

### Actual Behavior
Focus is lost when autocomplete has focus and focus is set programmatically

### Reproduction Link
<a href="https://codepen.io/mseele/pen/XWrQdPM" target="_blank">https://codepen.io/mseele/pen/XWrQdPM</a>

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/jkarczm/pen/PoodBrG

**Comment by stavro-gh** [comment]
if compared to v-select and other input components, v-autocomplete behave general different with focus. eg if you select one item from the list (with mouse or keyboard) and the popup closes you lost focus on the v-autocomplete component. this never happens in eg v-select. in my case this leads to the problem that going with tab trough the form ist broken at this place where i use v-autocomplete every time when is select items with the mouse. if i select items with the keyboard i can tab to the next component in the row even though the v-autocomplete had lost the focus before.
