### ISSUE TITLE
[Bug Report] vuetify not working with typescript

### ISSUE THREAD

**Issue by VIXI0** [vuetifyjs/vuetify#9115]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
1. `vue create test`
2. `vue add vuetify`
3. add type `"vuetify"` to tsconfig.ts
4. `yarn or npm serve`

### Expected Behavior
it should run properly

### Actual Behavior

 WAIT  Compiling...                                                                                         

98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                  

`This dependency was not found:`

`* vuetify/lib in ./src/plugins/vuetify.ts`

To install it, you can run: npm install --save vuetify/lib
Type checking and linting in progress...
WARNING in D:/Repositories/test/src/main.ts
14:24 Missing trailing comma
    12 |   store,
    13 |   vuetify,
  > 14 |   render: (h) => h(App)
       |                        ^
    15 | }).$mount('#app');
    16 |
ERROR in D:/Repositories/test/src/main.ts
13:3`No overload matches this call.`
  
    11 |   router,
    12 |   store,
  > 13 |   vuetify,
       |   ^
    14 |   render: (h) => h(App)
    15 | }).$mount('#app');
    16 |
ERROR in D:/Repositories/test/src/plugins/vuetify.ts
2:21 `Cannot find module 'vuetify/lib'.`
    1 | import Vue from 'vue';
  >2 | `import Vuetify from 'vuetify/lib';``
      |                     ^
    3 |
    4 | Vue.use(Vuetify);
    5 |
Version: typescript 3.6.3, tslint 5.20.0
Time: 3527ms

### Reproduction Link
<a href="https://github.com/VIXI0/test" target="_blank">https://github.com/VIXI0/test</a>

### Other comments
i update all my proyect now i messed up everything

**Comment by melbahja** [comment]
I don't work with ts but I think your import should be like `import Vuetify from 'vuetify'` or `import Vuetify from 'vuetify/src'`

**Comment by VIXI0** [comment]
thanks god i work with [github](github.com/VIXI0)

the bug seens to appear when you make a fresh install of vuetify 2.0.19 or update vuetify from previous versions in typeScript.

if you try to reverve the installation you ger this error: 
` PS D:\Repositories\my> yarn serve
yarn run v1.17.3
$ vue-cli-service serve
 ERROR  ReferenceError: opts is not defined
ReferenceError: opts is not defined
    at module.exports (D:\Repositories\my\node_modules\vue-cli-plugin-vuetify\index.js:18:5)
    at D:\Repositories\my\node_modules\@vue\cli-service\lib\Service.js:83:7
    at Array.forEach (<anonymous>)
    at Service.init (D:\Repositories\my\node_modules\@vue\cli-service\lib\Service.js:81:18)
    at Service.run (D:\Repositories\my\node_modules\@vue\cli-service\lib\Service.js:221:10)
    at Object.<anonymous> (D:\Repositories\my\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. `

I have found a solution far of coding:

1. make a github repository
2. push your proyect
3. clone your proyect & install all dependencies (obviously with vuetify@2.019 )

this will install vuetify with no problems.

thanks @melbahja for your time!!!!.

**Comment by VIXI0** [comment]
### the reproduction link will work thats how i found the solution.

**Comment by infacto** [comment]
### When I use 

`import Vuetify from 'vuetify/lib';`

It says error: `Could not find a declaration file for module 'vuetify/lib'`. But the build works and on runtime all works as expected. Btw. this error also produces the error in `main.ts` `No overload matched this call.`

### When I use

`import Vuetify from 'vuetify';`

No error and the also works. BUT on runtime the font is not loaded / set correctly. It's like the default `Times New Roman` instead of the font of Vuetify.

### When I use

`import Vuetify from 'vuetify/src';`

The build works and the font also works. BUT in `main.ts` is the same error like when using `vuetify/lib` > `No overload matched this call.`

### Conclusion 

No solution yet works correctly.

**main.ts**

```ts
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import vuetify from './plugins/vuetify';

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  vuetify,
  render: h => h(App)
}).$mount('#app');
```

**plugins/vuetify.ts**

```ts
import Vue from 'vue';
import Vuetify from 'vuetify/src';

Vue.use(Vuetify);

export default new Vuetify({});
```

**Comment by MajesticPotatoe** [comment]
@infacto https://vuetifyjs.com/en/introduction/frequently-asked-questions#when-adding-typescript-error-could-not-find-a-declaration-file-for-module-vuetify-lib

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by infacto** [comment]
@MajesticPotatoe Ok thanks :) Adding `vuetify` to `compilerOptions.types` in `tsconfig.json` works. Now the import of `vuetify/lib` is ok. 👍

**Comment by marcoValkyriweb** [comment]
I know this is closed, but it's still the number one hit, just generated a new project using Vue 3 cli. 
Here is a working ../tsconfig.json (using webpack + TS), note as infacto said, it's under the types array:
`
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "vuetify" //THIS LINE NEEDS TO BE ADDED
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
`

**Comment by angelsix** [comment]
Vue cli 4.3.1. Using pnmp (if that makes any difference). `vue create test`. Select Typescript as an option.

```
cd test 
vue add vuetify
pnpm i
pnpm run serve
```
```
ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
10:3 No overload matches this call.
  Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
  Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
  Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
     8 | new Vue({
     9 |   router,
  > 10 |   vuetify,
       |   ^
    11 |   render: h => h(App)
    12 | }).$mount("#app");
    13 |
ERROR in C:/Users/conta/Desktop/test/src/plugins/vuetify.ts(2,21):
2:21 Could not find a declaration file for module 'vuetify/lib'. 'C:/Users/conta/Desktop/test/node_modules/vuetify/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/lib';`
    1 | import Vue from "vue";
  > 2 | import Vuetify from "vuetify/lib";
      |                     ^
    3 |
    4 | Vue.use(Vuetify);
    5 |
Version: typescript 3.8.3
```

Add `vuetify` to `tsconfig.js` in `types` section. Now get this

```
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(64,10):
64:10 Cannot find name 'DefaultData'.
    62 |   export interface ComponentOptions<
    63 |     V extends Vue,
  > 64 |     Data=DefaultData<V>,
       |          ^
    65 |     Methods=DefaultMethods<V>,
    66 |     Computed=DefaultComputed,
    67 |     PropsDef=PropsDefinition<DefaultProps>,
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(65,13):
65:13 Cannot find name 'DefaultMethods'.
    63 |     V extends Vue,
    64 |     Data=DefaultData<V>,
  > 65 |     Methods=DefaultMethods<V>,
       |             ^
    66 |     Computed=DefaultComputed,
    67 |     PropsDef=PropsDefinition<DefaultProps>,
    68 |     Props=DefaultProps> {
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(66,14):
66:14 Cannot find name 'DefaultComputed'.
    64 |     Data=DefaultData<V>,
    65 |     Methods=DefaultMethods<V>,
  > 66 |     Computed=DefaultComputed,
       |              ^
    67 |     PropsDef=PropsDefinition<DefaultProps>,
    68 |     Props=DefaultProps> {
    69 |     vuetify?: Vuetify
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,14):
67:14 Cannot find name 'PropsDefinition'.
    65 |     Methods=DefaultMethods<V>,
    66 |     Computed=DefaultComputed,
  > 67 |     PropsDef=PropsDefinition<DefaultProps>,
       |              ^
    68 |     Props=DefaultProps> {
    69 |     vuetify?: Vuetify
    70 |   }
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,30):
67:30 Cannot find name 'DefaultProps'.
    65 |     Methods=DefaultMethods<V>,
    66 |     Computed=DefaultComputed,
  > 67 |     PropsDef=PropsDefinition<DefaultProps>,
       |                              ^
    68 |     Props=DefaultProps> {
    69 |     vuetify?: Vuetify
    70 |   }
ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(68,11):
68:11 Cannot find name 'DefaultProps'.
    66 |     Computed=DefaultComputed,
    67 |     PropsDef=PropsDefinition<DefaultProps>,
  > 68 |     Props=DefaultProps> {
       |           ^
    69 |     vuetify?: Vuetify
    70 |   }
    71 | }
ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
10:3 No overload matches this call.
  Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
  Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
  Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
    Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
      Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
     8 | new Vue({
     9 |   router,
  > 10 |   vuetify,
       |   ^
    11 |   render: h => h(App)
    12 | }).$mount("#app");
    13 |
Version: typescript 3.8.3
```

**Comment by JkCrowN07** [comment]
> Vue cli 4.3.1. Using pnmp (if that makes any difference). `vue create test`. Select Typescript as an option.
> 
> ```
> cd test 
> vue add vuetify
> pnpm i
> pnpm run serve
> ```
> 
> ```
> ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
> 10:3 No overload matches this call.
>   Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>   Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>   Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>      8 | new Vue({
>      9 |   router,
>   > 10 |   vuetify,
>        |   ^
>     11 |   render: h => h(App)
>     12 | }).$mount("#app");
>     13 |
> ERROR in C:/Users/conta/Desktop/test/src/plugins/vuetify.ts(2,21):
> 2:21 Could not find a declaration file for module 'vuetify/lib'. 'C:/Users/conta/Desktop/test/node_modules/vuetify/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/lib';`
>     1 | import Vue from "vue";
>   > 2 | import Vuetify from "vuetify/lib";
>       |                     ^
>     3 |
>     4 | Vue.use(Vuetify);
>     5 |
> Version: typescript 3.8.3
> ```
> 
> Add `vuetify` to `tsconfig.js` in `types` section. Now get this
> 
> ```
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(64,10):
> 64:10 Cannot find name 'DefaultData'.
>     62 |   export interface ComponentOptions<
>     63 |     V extends Vue,
>   > 64 |     Data=DefaultData<V>,
>        |          ^
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(65,13):
> 65:13 Cannot find name 'DefaultMethods'.
>     63 |     V extends Vue,
>     64 |     Data=DefaultData<V>,
>   > 65 |     Methods=DefaultMethods<V>,
>        |             ^
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>     68 |     Props=DefaultProps> {
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(66,14):
> 66:14 Cannot find name 'DefaultComputed'.
>     64 |     Data=DefaultData<V>,
>     65 |     Methods=DefaultMethods<V>,
>   > 66 |     Computed=DefaultComputed,
>        |              ^
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,14):
> 67:14 Cannot find name 'PropsDefinition'.
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>   > 67 |     PropsDef=PropsDefinition<DefaultProps>,
>        |              ^
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
>     70 |   }
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,30):
> 67:30 Cannot find name 'DefaultProps'.
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>   > 67 |     PropsDef=PropsDefinition<DefaultProps>,
>        |                              ^
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
>     70 |   }
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(68,11):
> 68:11 Cannot find name 'DefaultProps'.
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>   > 68 |     Props=DefaultProps> {
>        |           ^
>     69 |     vuetify?: Vuetify
>     70 |   }
>     71 | }
> ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
> 10:3 No overload matches this call.
>   Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>   Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>   Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>      8 | new Vue({
>      9 |   router,
>   > 10 |   vuetify,
>        |   ^
>     11 |   render: h => h(App)
>     12 | }).$mount("#app");
>     13 |
> Version: typescript 3.8.3
> ```

I encountered the same problem,did you solve it?

**Comment by JkCrowN07** [comment]
@angelsix I encountered the same problem,did you solve it?

**Comment by LZQCN** [comment]
> Vue cli 4.3.1. Using pnmp (if that makes any difference). `vue create test`. Select Typescript as an option.
> 
> ```
> cd test 
> vue add vuetify
> pnpm i
> pnpm run serve
> ```
> 
> ```
> ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
> 10:3 No overload matches this call.
>   Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>   Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>   Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>      8 | new Vue({
>      9 |   router,
>   > 10 |   vuetify,
>        |   ^
>     11 |   render: h => h(App)
>     12 | }).$mount("#app");
>     13 |
> ERROR in C:/Users/conta/Desktop/test/src/plugins/vuetify.ts(2,21):
> 2:21 Could not find a declaration file for module 'vuetify/lib'. 'C:/Users/conta/Desktop/test/node_modules/vuetify/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/lib';`
>     1 | import Vue from "vue";
>   > 2 | import Vuetify from "vuetify/lib";
>       |                     ^
>     3 |
>     4 | Vue.use(Vuetify);
>     5 |
> Version: typescript 3.8.3
> ```
> 
> Add `vuetify` to `tsconfig.js` in `types` section. Now get this
> 
> ```
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(64,10):
> 64:10 Cannot find name 'DefaultData'.
>     62 |   export interface ComponentOptions<
>     63 |     V extends Vue,
>   > 64 |     Data=DefaultData<V>,
>        |          ^
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(65,13):
> 65:13 Cannot find name 'DefaultMethods'.
>     63 |     V extends Vue,
>     64 |     Data=DefaultData<V>,
>   > 65 |     Methods=DefaultMethods<V>,
>        |             ^
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>     68 |     Props=DefaultProps> {
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(66,14):
> 66:14 Cannot find name 'DefaultComputed'.
>     64 |     Data=DefaultData<V>,
>     65 |     Methods=DefaultMethods<V>,
>   > 66 |     Computed=DefaultComputed,
>        |              ^
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,14):
> 67:14 Cannot find name 'PropsDefinition'.
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>   > 67 |     PropsDef=PropsDefinition<DefaultProps>,
>        |              ^
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
>     70 |   }
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(67,30):
> 67:30 Cannot find name 'DefaultProps'.
>     65 |     Methods=DefaultMethods<V>,
>     66 |     Computed=DefaultComputed,
>   > 67 |     PropsDef=PropsDefinition<DefaultProps>,
>        |                              ^
>     68 |     Props=DefaultProps> {
>     69 |     vuetify?: Vuetify
>     70 |   }
> ERROR in C:/Users/conta/Desktop/test/node_modules/.pnpm/registry.npmjs.org/vuetify/2.2.27_vue@2.6.11/node_modules/vuetify/types/index.d.ts(68,11):
> 68:11 Cannot find name 'DefaultProps'.
>     66 |     Computed=DefaultComputed,
>     67 |     PropsDef=PropsDefinition<DefaultProps>,
>   > 68 |     Props=DefaultProps> {
>        |           ^
>     69 |     vuetify?: Vuetify
>     70 |   }
>     71 | }
> ERROR in C:/Users/conta/Desktop/test/src/main.ts(10,3):
> 10:3 No overload matches this call.
>   Overload 1 of 3, '(options?: ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
>   Overload 2 of 3, '(options?: ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object> | undefined): CombinedVueInstance<Vue, object, object, object, Record<...>>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ThisTypedComponentOptionsWithRecordProps<Vue, object, object, object, object>'.
>   Overload 3 of 3, '(options?: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined): CombinedVueInstance<...>', gave the following error.
>     Argument of type '{ router: VueRouter; vuetify: Vuetify; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>       Object literal may only specify known properties, and 'vuetify' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
>      8 | new Vue({
>      9 |   router,
>   > 10 |   vuetify,
>        |   ^
>     11 |   render: h => h(App)
>     12 | }).$mount("#app");
>     13 |
> Version: typescript 3.8.3
> ```

I have the same problem. The known solution is:
create a file `src/types/vuetify.d.ts`
```
declare module 'vuetify/lib' {
  import 'vuetify/types/lib';
  import 'vue/types/options.d';
}
```

**Comment by douglasg14b** [comment]
The above did not work, but the following was a resolution:

```ts
declare module 'vuetify/lib/framework' {
  import Vuetify from 'vuetify'
  export default Vuetify
}
```
