### ISSUE TITLE
[Feature Request] Show week numbers in v-calendar

### ISSUE THREAD

**Issue by goeh** [vuetifyjs/vuetify#9117]
### Problem to solve
Currently there is no way to see week numbers in v-calendar.

### Proposed solution
A week number option that can be filled out to add week numbers to the calendar view. For example in the leftmost column, above hours.

The config property should be able to specify how week number 1 is found. E.g. the first week with a monday is week 1 or the first 4 day week is week 1.

This was fixed for date-picker, see https://github.com/vuetifyjs/vuetify/issues/5077 for reference.

**Comment by raygervais** [comment]
I'd like to take a crack at this, but need advice on the design of it 👍

**Comment by goeh** [comment]
Here is an example screenshot from the MacOS calendar displaying week 39 (sv locale). But for v-calendar I think it should go into the first column above hours.
<img width="494" alt="macos-calendar-week-number" src="https://user-images.githubusercontent.com/322721/65764360-bf3d0e80-e125-11e9-89a2-e604ba600861.png">

**Comment by goeh** [comment]
An alternative would be to just provide a named slot there and some easy way to get the current week number from the `change` event. That way I could render the number myself and it would automatically follow the current calendar view.

**Comment by MajesticPotatoe** [comment]
looks like google handles it pretty simply by adding it in the upper right of first column 
<img width="247" alt="321312" src="https://user-images.githubusercontent.com/27827979/65767531-1f1ebf80-e0fc-11e9-9776-20ec60628838.png">

maybe should go with a slot that applies that, and make the default look a little more clean and visible

**Comment by raygervais** [comment]
I'll take a shot at the above, will reference Material Design 2.0 spec if possible. Thanks for sharing some of the common ways the week number is added :smiley:

**Comment by ClickerMonkey** [comment]
And as an important note, the "week of the year" is not calculated the same for every locale. And even what's standard for the current locale might not be what the user wants.

**Comment by ClickerMonkey** [comment]
The slot `interval-header` is being added in https://github.com/vuetifyjs/vuetify/pull/9974

**Comment by abbierwolf** [comment]
The slot `interval-header` helps in the `week` and `day` view, but I wanted to show week numbers in the `month` view.  I implemented this like the google calendar does. 
![image](https://user-images.githubusercontent.com/6149151/77425473-10774380-6dd3-11ea-924e-db14f3da4e3e.png)
Shall I create a pull request for it?

**Comment by johnleider** [comment]
resolved in #10928 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
