### ISSUE TITLE
[Bug Report] Removing range prop dynamically on date range picker throws JS error

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9118]
### Environment
**Vuetify Version:** 2.1.0-beta.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Open dev tools console tab. Click the button to remove the range. See in dev tools the error being thrown.

### Expected Behavior
No error. If range was selected, it should clear the range or set the value to the from or end date.

### Actual Behavior
Throws error.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/wvwZqKe?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/wvwZqKe?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Date picker in single and non-range mode requires v-model to be `string|null`
