### ISSUE TITLE
[Bug Report] Time picker does not with full-width props

### ISSUE THREAD

**Issue by BenjaminVadant** [vuetifyjs/vuetify#9119]
### Environment
**Vuetify Version:** 1.x
**Last working version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Add the full-width props to a time picker

### Expected Behavior
The clock should be visible

### Actual Behavior
The clock is not visible

### Reproduction Link
<a href="https://codepen.io/BenjaminVadant/pen/KKPYXXP" target="_blank">https://codepen.io/BenjaminVadant/pen/KKPYXXP</a>

**Comment by BenjaminVadant** [comment]
I saw this issue raised also [there](https://github.com/darrenfang/vuetify-datetime-picker/issues/42)

**Comment by darrenfang** [comment]
Reset the style `.v-picker__body`:

```css
.v-picker__body {
    margin: initial;
}
```

**Comment by BenjaminVadant** [comment]
Another solution is to apply this to the picker:

`style="width:100%"`

It's a bit dirty but it does the trick.
