### ISSUE TITLE
[Bug Report] Performance issue when using large date range (0000-01-01 to 9999-12-31) in date range picker

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9120]
### Environment
**Vuetify Version:** 2.1.0-beta.1
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
Click the left arrow to go back a month.

### Expected Behavior
Should change instantly with all days selected in the month.

### Actual Behavior
Takes long time and kills cpu to change months.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/zYOXpOy?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/zYOXpOy?&editable=true&editors=101</a>

### Other comments
There should not be a huge spike in CPU performance and time because switching months or when setting a long date range should only draw at most 7x5=35 circles on the calendar. It feels like it is iterating through the huge date range (10000 years worth of days in this case) and drawing circles around them all in realtime.

**Comment by KaelWD** [comment]
#8891

It's creating a `new Date()` object for each day in the selection, so in this case 3,652,424 times. Really you shouldn't be using this for anything longer than a couple of months so it isn't a big problem. 

https://github.com/vuetifyjs/vuetify/blob/72e279c5/packages/vuetify/src/components/VDatePicker/VDatePicker.ts#L373-L381

**Comment by TheInvoker** [comment]
Why was it designed to loop through all dates though? Shouldn't it lazy load the current month (or visible view) and process that only?

**Comment by TheInvoker** [comment]
This code snippet also seems really inefficient. Firstly I feel like it should be lazy load the visible view only. On top of that it's doing a linear map of the range, then sorting it for some reason when it should already be sorted if going from min to max in the range. Then again it's looping through the range for some reason when it could have processed it in the first linear map.

**Comment by KaelWD** [comment]
I didn't write it. You shouldn't be using this for longer ranges so I guess the guy who did didn't think lazy loading was worth the effort. The map then sort is making sure the array is actually in the format `[from, to]` in case you passed `[to, from]` instead, and the second loop is over the number of days in the range not the range itself.
