### ISSUE TITLE
[Bug Report] Offset for extra small not working

### ISSUE THREAD

**Issue by aadriantech** [vuetifyjs/vuetify#9121]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 7

### Steps to reproduce
Created a v-row with v-col col-xs-4 and offset-xs-2
https://ibb.co/pLkn2zP

### Expected Behavior
Center both buttons with 2 offset on each side

### Actual Behavior
does not have 2 offset on left side at least

### Reproduction Link
<a href="https://jsfiddle.net/32ckwrey/1/" target="_blank">https://jsfiddle.net/32ckwrey/1/</a>

**Comment by MajesticPotatoe** [comment]
in the 2.0 grids `xs` is assumed as the default breakpoint if none is specified thus there is no `offset-xs-#` you would simply use `offset-#`

[Example](https://codepen.io/MajesticPotatoe/pen/OJLGrRp)
