### ISSUE TITLE
[Feature Request]Scroll Bar Hidden

### ISSUE THREAD

**Issue by kingdom84521** [vuetifyjs/vuetify#9127]
### Problem to solve
So there are already some methods can let scroll bar hide itself, just wonder if this can be a feature write in vuetify. Because ways in Chrome maybe can't work on Firefox too, if vuetify can make a feature of hiding scroll bar that supported to most of the browsers, that would be great.

### Proposed solution
Maybe like a class named "scroll-bar-hidden", or just make a component that can let users customized their scroll bar style.

**Comment by MajesticPotatoe** [comment]
Assuming you are speaking of the main scrollbar covered in #864 in which case will not be added and can be handled in userland by applying html `{   overflow-y: scroll; }` or applying this style anywhere you don't want a scrollbar

As for custom scrollbars that would be covered in #5196

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
