### ISSUE TITLE
[Bug Report] Opening v-menu with focus event on a text-field breaks click event

### ISSUE THREAD

**Issue by Phennim** [vuetifyjs/vuetify#9129]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Mac OS 10.14

### Steps to reproduce
- Open reproduction link
- Click on the input field

### Expected Behavior
The menu with the datepicker shoud open

### Actual Behavior
The menu flashes open and closes immediately

### Reproduction Link
<a href="https://codepen.io/Phennim/pen/KKPYGRK" target="_blank">https://codepen.io/Phennim/pen/KKPYGRK</a>

### Other comments
I used the setTimeout workaround posted in https://github.com/vuetifyjs/vuetify/issues/4454
Which seems to work. Though I don't know how stable it is, since setting the timeout too low breaks it again

**Comment by mismith** [comment]
Any idea what's causing this @johnleider ?

**Comment by Lisible** [comment]
I can confirm this bug is still present in v2.2.19

**Comment by Lisible** [comment]
In my case, adding @mousedown.prevent on the v-text-field worked. However this workaround doesn't seem to work in the example posted above.

**Comment by tstar** [comment]
It's a pity, but this problem is still present in the latest version 2.3.8.

**Comment by kathar0s** [comment]
This is alternative solution.

use v-menu props "open-on-click: false" and "close-on-click: false"
and you just control v-menu model through v-text-field's blur and focus event.

https://codepen.io/kathar0s/pen/YzqyWbz

**Comment by tstar** [comment]
> This is alternative solution.

Thanks for the solution, but it does not work with the date-picker, you cannot change the date, it seems to me that the menu closes before the date-picker selects a date. Without v-on:blur="pickDate = false" for the text-field it works but does not close the date-picker. I still can't get it to work :(

**Comment by bHacklv** [comment]
@tstar and the rest, I found a solution using @kathar0s approach.

You have to add timeout for blur:

```
private onBlur() {
      setTimeout(() => {
        this.pickDate = false;
      }, 100)
    }
```
must be 100ms+ delay or it stops working.
I've set mine to 500 just to be sure.

**Comment by ElPodge** [comment]
Solution seems to be there  (but not documented ?) : https://vuetifyjs.com/en/components/date-pickers/#birthday-picker => you have to call `this.$refs.menu.save(date)`

**Comment by vcavallo** [comment]
> @tstar and the rest, I found a solution using @kathar0s approach.
> 
> You have to add timeout for blur:
> 
> ```
> private onBlur() {
>       setTimeout(() => {
>         this.pickDate = false;
>       }, 100)
>     }
> ```
> 
> must be 100ms+ delay or it stops working.
> I've set mine to 500 just to be sure.

As far as I can tell, using this workaround _with_ `close-on-content-click="false"` does not work.

**Comment by vcavallo** [comment]
> This is alternative solution.
> 
> use v-menu props "open-on-click: false" and "close-on-click: false"
> and you just control v-menu model through v-text-field's blur and focus event.
> 
> https://codepen.io/kathar0s/pen/YzqyWbz

This example doesn't actually set the date, which is a crucial feature of this component.

**Comment by meekot** [comment]
Hello everyone, I find a solution, it may slightly affect performance, but focus works correctly https://codepen.io/meekot-the-reactor/pen/abwwJMa
