### ISSUE TITLE
Scrollbar with v-footer

### ISSUE THREAD

**Issue by bhamon** [vuetifyjs/vuetify#913]
### Steps to reproduce
Just run the codepen.

### Versions
vue: v2.3.3
vuetify: v0.13.0

### What is expected ?
The content should fill the viewport without scrolling.

### What is actually happening ?
When adding a `v-footer` to a `v-app`, a scrollbar appears.
Same issue as #906

### Reproduction Link
https://codepen.io/anon/pen/VWBBev

**Comment by Nicholaiii** [comment]
Same issue, currently, also the footer is pushed out of the view.

**Comment by Nicholaiii** [comment]
@bhamon looking through the other issues, this is resolved by addint this snippet to your v-app`class="application--toolbar application--footer application--footer-fixed"`
