### ISSUE TITLE
[Documentation] Time Picker in Docs is broken

### ISSUE THREAD

**Issue by hrakaroo** [vuetifyjs/vuetify#9136]
### Environment

**Browsers:** Chrome 68.0.3440.106
**OS:** Linux x86_64

### Steps to reproduce
Click on "Picker in menu".  It looks like the time report is overlayed over the actual clock used to pick the time.

### Expected Behavior
The clock to be visible

### Actual Behavior
The clock is not visible.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/time-pickers#time-pickers" target="_blank">https://vuetifyjs.com/en/components/time-pickers#time-pickers</a>

**Comment by hrakaroo** [comment]
Looks like this is a duplicate of https://github.com/vuetifyjs/vuetify/issues/9119, although you don't need codepen to view it as it looks like it is broken on the vuetify docs page.

**Comment by MajesticPotatoe** [comment]
Fixed in 2.1.0-beta.x
