### ISSUE TITLE
[Documentation] Center vertical outdated documentation

### ISSUE THREAD

**Issue by robertofd1995** [vuetifyjs/vuetify#9137]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
In "frequently-asked-questions" there is a question "how-to-center-vertically" this is outdated and it only works for the old grid system, how can I archive this with the new one?

### Expected Behavior
Docs showing how to center things vertically inside a container

### Actual Behavior
Old docs showing how to do it for the old grid system

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/frequently-asked-questions#how-to-center-vertically" target="_blank">https://vuetifyjs.com/en/getting-started/frequently-asked-questions#how-to-center-vertically</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
