### ISSUE TITLE
[Bug Report] V-dialog does not retain focus

### ISSUE THREAD

**Issue by avenmore** [vuetifyjs/vuetify#9144]
### Environment
**Vuetify Version:** 2.0.19
**Last working version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
Show a dialog and press tab repeatedly.

### Expected Behavior
When pressing tab, the focus cycles back to the first control of the dialog after the last control has been focused.

### Actual Behavior
The focus goes out of the dialog, cycling through the page behind.

### Reproduction Link
<a href="https://codepen.io/avenmore/pen/WNeBOZr" target="_blank">https://codepen.io/avenmore/pen/WNeBOZr</a>

### Other comments
Can be shown to be [working in 2.0.11](https://codepen.io/sh7dm/pen/aboqzxw) in this pen (sorry, not mine, created to demo another problem). Setting "retain-focus" on the dialog has no effect.

**Comment by KaelWD** [comment]
fa0a8936be2411f0739259c7762fec350bd9e082

#8459

@johnleider 3681cd59fe82bd1716a46038245236b2922923db was done specifically to allow for an override in cases like that

**Comment by mshmelev** [comment]
This bug is a regression introduced by commit https://github.com/vuetifyjs/vuetify/commit/fa0a8936be2411f0739259c7762fec350bd9e082
If you remove that check for `e.target === document.activeElement` everything works as expected.

**Comment by KaelWD** [comment]
I literally said that
