### ISSUE TITLE
[Documentation] Show an example of v-app-bar working with mobile devices

### ISSUE THREAD

**Issue by alexramsey92** [vuetifyjs/vuetify#9147]
### Problem to solve
All examples in 2.x show v-app-bar only in desktop scenarios. There is no working example of how this might work on a mobile phone. V-app-bar-nav-icon seems to do nothing but be an icon with a click animation.

### Proposed solution
Provide a simple navbar with a collapse menu that works well for phones and looks good on a desktop.

**Comment by alexramsey92** [comment]
`  <v-app-bar>
    <v-toolbar-title>
      <img
        src="@/assets/logo.png"
        alt="RTS ENVIRONMENTAL SERVICES, INC."
        class="mt-8 hidden-sm-and-down"
      />
      <img
        src="@/assets/logo.png"
        alt="RTS ENVIRONMENTAL SERVICES, INC."
        class="mt-1 hidden-md-and-up"
        height="50px"
      />
    </v-toolbar-title>
    <v-spacer></v-spacer>
    <v-toolbar-items class="hidden-sm-and-down">
      <v-btn v-for="item in menu" :key="item.title" :to="item.link" text>{{ item.title }}</v-btn>
    </v-toolbar-items>
    <v-menu class="hidden-md-and-up">
      <v-app-bar-nav-icon></v-app-bar-nav-icon>
      <template v-slot:activator="{ on }">
        <v-btn icon v-on="on">
          <v-icon>mdi-dots-vertical</v-icon>
        </v-btn>
      </template>
      <v-list>
        <v-list-tile v-for="item in menu" :key="item.title">
          <v-list-tile-content>
            <v-list-tile-title>{{ item.title }}</v-list-tile-title>
          </v-list-tile-content>
        </v-list-tile>
      </v-list>
    </v-menu>
  </v-app-bar>`

![image](https://user-images.githubusercontent.com/6438890/65826341-42a74e80-e251-11e9-91d3-18a7be2af315.png)

Imma just go back to using bootstrap...I can't spend an hour fighting with a navbar. GRrr.

**Comment by alexramsey92** [comment]
Ok, I think I've got a decent navbar working now:

  <div>
    <v-navigation-drawer v-model="sidebar" app>
      <v-list>
        <v-list-item v-for="item in menuItems" :key="item.title" :to="item.path">
          <v-list-item-action>
            <v-icon>{{ item.icon }}</v-icon>
          </v-list-item-action>
          <v-list-item-content>{{ item.title }}</v-list-item-content>
        </v-list-item>
      </v-list>
    </v-navigation-drawer>

    <v-app-bar app>
      <span class="hidden-sm-and-up">
        <v-app-bar-nav-icon @click="sidebar = !sidebar"></v-app-bar-nav-icon>
      </span>
      <v-toolbar-title>
        <router-link to="/" tag="span" style="cursor: pointer">
          <img
            src="@/assets/logo.png"
            alt="RTS ENVIRONMENTAL SERVICES, INC."
            class="mt-8 hidden-sm-and-down"
          />
          <img
            src="@/assets/logo.png"
            alt="RTS ENVIRONMENTAL SERVICES, INC."
            class="mt-1 hidden-md-and-up"
            height="50px"
          />
        </router-link>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-toolbar-items class="hidden-xs-only">
        <v-btn text v-for="item in menuItems" :key="item.title" :to="item.path">
          
          {{ item.title }}
        </v-btn>
      </v-toolbar-items>
    </v-app-bar>
  </div>

**Comment by MajesticPotatoe** [comment]
Could you provide a little more clarity on your request. It sounds more like asking for a better example of mobile navigation drawers? `v-app-bar-nav-icon` by default doesn't have any functionality. Its a common positioned hamburger icon used in toolbars, more often to toggle a nav drawer. rather mobile independent. There are set plans to expand usage and definitions for these sub-components in the works.

**Comment by cioby23** [comment]
Can an example using the **v-app-bar-nav-icon** be added to documentation regarding how to collapse a full  **<v-navigation-drawer>** to a mini-variant and restore it back ?
