### ISSUE TITLE
Select, multiline, and ellipsis

### ISSUE THREAD

**Issue by Equals182** [vuetifyjs/vuetify#915]
### Steps to reproduce
Just use `<v-select>` with item having a long enough text.
Use any other inline component nearby to see how ridiculous it looks.
[Or click here for codepen](https://codepen.io/anon/pen/jwpKja?editors=1111)

### Versions

Vue: v2.3.4
Vuetify: v0.13.0
OS: Windows, but I guess it doesn't really matter
Browser: Firefox, Chrome, doesn't matter, it's just CSS.

### What is expected ?

It would be cool to have an ability to set ellipsis prop, I guess. Multiline `<v-select>` looks kinda weird.

### What is actually happening ?

It wraps text making <v-select> look huge and weird. 
In [example](https://codepen.io/anon/pen/jwpKja?editors=1111) it also breaks `<v-text-field>` a bit.

Is it bug report or feature request? You decide!

### Reproduction Link

https://codepen.io/anon/pen/jwpKja?editors=1111

**Comment by mix3d** [comment]
This, while not ideal, is one of the only ways to handle multi-selects and actually show the data.

Example from the select docs #4: 
![image](https://user-images.githubusercontent.com/1474137/27940747-95aefada-629a-11e7-8ede-ae90ca3a2f8c.png)

ellipses could be a good feature addition for single-line selects, and perhaps a visual fix for adjacent text fields and selects; perhaps they're all bottom-aligned so the lines and text match the bottom of the tallest input type?

**Comment by johnleider** [comment]
I'm not sure about introducing a change like this. Essentially, it would be a prop specifically for designating the maximum width before ellipsis is applied. I think it would be more suited for the dev to simply truncate the string themselves in this scenario.

**Comment by mix3d** [comment]
Not necessarily. The single-line css property is exactly what this scenario
is for

**Comment by johnleider** [comment]
The single-line property denotes a label that does not float, not the presence of overflow text. It also would mean that the select could not wrap at all, meaning a multi-select wouldn't be able to use the prop.

**Comment by mix3d** [comment]
That was my earlier point. It'd have to be mutually exclusive to the single line. Maybe this is left to the user to fix with their own css?

Still, the comment about the positioning of a single line text input next to the select that wraps is a valid point. That could do with some cleanup regardless

**Comment by johnleider** [comment]
After consideration this is something that I believe should be left up to the dev if the result does not fit their design needs.
