### ISSUE TITLE
[Bug Report] Calendar month view does not align days column properly in Firefox

### ISSUE THREAD

**Issue by pamantea** [vuetifyjs/vuetify#9152]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Open attached codepen in Firefox 
2. The week days are not properly aligned between all rows (Rows 2-3 are aligned between each other but the others are all over the place)

### Expected Behavior
All columns and rows are properly aligned, regardless of each days content

### Actual Behavior
Columns get different width on each row, depending on the events title in each day

### Reproduction Link
<a href="https://codepen.io/pamantea/pen/YzKoWyL" target="_blank">https://codepen.io/pamantea/pen/YzKoWyL</a>

**Comment by BjornLuG** [comment]
Seems like it's already fixed in #9092

**Comment by pamantea** [comment]
> Seems like it's already fixed in #9092
> 
> EDIT: It's already fixed in [v2.0.20](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.20)

Thanks! I've just checked it and it was indeed fixed! :)
