### ISSUE TITLE
[Bug Report] Calendar month view collapses all content into single row in Safari

### ISSUE THREAD

**Issue by pamantea** [vuetifyjs/vuetify#9154]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
1. Open attached codepen in Safari 
2. All rows seem collapsed into a single row - neither headers nor content are clearly visible

### Expected Behavior
All columns and rows are properly aligned, regardless of each days content

### Actual Behavior
All rows are collapsed and positioned in the first row

### Reproduction Link
<a href="https://codepen.io/pamantea/pen/YzKoWyL" target="_blank">https://codepen.io/pamantea/pen/YzKoWyL</a>

**Comment by jappyjan** [comment]
I have the same problem on an iPad running chrome/safari

And on chrome on Linux 


![5C1885DF-F661-4105-8E79-05513ABD4470](https://user-images.githubusercontent.com/10154260/68131864-0df87800-ff1e-11e9-8b02-b7118ec3cb9a.png)

**Comment by JoeRadman** [comment]
I ended up fixing this with:

.v-calendar-weekly__week {
height: unset;
}
