### ISSUE TITLE
[Bug Report] Outline on v-select is broken within Stepper

### ISSUE THREAD

**Issue by lostlivio** [vuetifyjs/vuetify#9156]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Click on CONTINUE to second step of stepper and you will see a line runs through the label text that is not visible in the first step.

### Expected Behavior
On the 2nd step, the label on the v-select should not have a line through it

### Actual Behavior
On the 2nd step, the label on the v-select has a line through it

### Reproduction Link
<a href="https://codepen.io/lostlivio/pen/KKPjWro" target="_blank">https://codepen.io/lostlivio/pen/KKPjWro</a>

**Comment by Phennim** [comment]
This also happens within v-expansion-panel

**Comment by jacekkarczmarczyk** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/pull/9341
