### ISSUE TITLE
[Bug Report] v-checkbox with array type of model behaves incorrectly in Vue tables 2 

### ISSUE THREAD

**Issue by AyushiBShah** [vuetifyjs/vuetify#9158]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.7
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
When the data is loaded after that when you change page no. from pagination bar shown below, all check boxes show checked although the bound model is still an empty array. Because no action has been taken on check boxes

### Expected Behavior
Checkbox should be retained as checked and shouldn't come up automatically checked

### Actual Behavior
Checkbox should be retained as checked and shouldn't come up automatically checked

### Reproduction Link
<a href="https://codepen.io/ayushibshah/pen/qBWzdjN?editors=1000" target="_blank">https://codepen.io/ayushibshah/pen/qBWzdjN?editors=1000</a>

### Other comments
It works properly with normal input checkbox

**Comment by KaelWD** [comment]
Custom components need to be keyed when being iterated over.

**Comment by AyushiBShah** [comment]
@KaelWD : Thanks for the response !
