### ISSUE TITLE
Missing prop in an example of the documentation

### ISSUE THREAD

**Issue by Pyrd** [vuetifyjs/vuetify#916]
Reporting a bug?
================
Problems in the documentation : 
 In the dialogs section, for the fullscreen example, a persistant example is missing in the source   

#documentation

**Comment by johnleider** [comment]
I'm not sure what you mean?

**Comment by johnleider** [comment]
https://vuetifyjs.com/components/dialogs example 3

**Comment by Pyrd** [comment]
In the example of the fullcreen dialog, the exposed source code is missing a persitent prop to work

If you copy past it like it, it does not work proprely. The persistent prop is needed.

**Comment by Pyrd** [comment]
In the example of the fullcreen dialog, the exposed source code is missing
a persitent prop to work

If you copy past it like it, it does not work proprely. The persistent prop
is needed.
[image: @Pyrd] <https://github.com/Pyrd>





Write

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by Pyrd** [comment]
I'll do it on monday at work.

Sorry i'm quite new here, don't have the reflexes.

Thanks you
