### ISSUE TITLE
[Bug Report] v-data-table group.header does not span the entire row

### ISSUE THREAD

**Issue by yjagota** [vuetifyjs/vuetify#9160]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Add the following templat to a grouped v-data-table:

`<template v-slot:group.header="{ group, headers }">
	<tr>
		<td :colspan="headers.length">
			<span style="font-weight:bold;">
				{{ group.toUpperCase() }}
			</span>
		</td>
	</tr>
</template>`

### Expected Behavior
The header row should span the entire row.

### Actual Behavior
The header only appears in the first column.

### Reproduction Link
<a href="https://codepen.io/yjagota/pen/VwZJdjj" target="_blank">https://codepen.io/yjagota/pen/VwZJdjj</a>

**Comment by BjornLuG** [comment]
Omitting the `<tr>` tag resolves the issue since the slot is already a `<tr>` tag.

So it becomes like this:
`<template v-slot:group.header="{ group, headers }"> <td :colspan="headers.length"> <span style="font-weight:bold;"> {{ group.toUpperCase() }} </span> </td> </template>`

**Comment by yjagota** [comment]
Thanks. That does resolve it. Is there any way to find the information about slot tags? The documentation does not provide any such information. Some are obvious but others, not so much.

**Comment by BjornLuG** [comment]
The [v-data-table](https://vuetifyjs.com/en/components/data-tables#api) API section's slot tab only briefly describes its scoped props. I can't find any examples below regarding the `group.header` slot too. I could make a PR to have it included under the example's slot section, no promises though :)

**Comment by yjagota** [comment]
Haha. Thanks will be great. 👍 

I am closing the issue as it is resolved.

**Comment by andrewsauder** [comment]
Since the documentation hasn't been added, for posterity, here is a complete v-data-table group.header slot example that renders the same as the default slot:

`<template v-slot:group.header="{ groupBy, group, headers, isOpen, toggle, remove }">
	<td :colspan="headers.length">
		<v-btn icon small @click="toggle">
			<v-icon v-if="isOpen">mdi-minus</v-icon>
			<v-icon v-else>mdi-plus</v-icon>
		</v-btn>
		{{ groupBy[0] }}: {{ group }}
		<v-btn icon small @click="remove">
			<v-icon>mdi-close</v-icon>
		</v-btn>
	</td>
</template>`
