### ISSUE TITLE
[Feature Request] Add support for custom text with numbers for calendar show more items and date picker multi select

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9166]
### Problem to solve
Gives the ability to replace default text with custom text that includes the count as well.

### Proposed solution
Instead of this selected-items-text="X Selected" (date picker range) and event-more-text="See X More" (calendar) which only displays static text (unable to get the number), make it point to a function which gets number as a param, and there I can dynamically make the text and return that.

**Comment by ClickerMonkey** [comment]
`event-more-text` is prop that's available, `{0}` is where the number hidden will be inserted. Does this work for what you're trying to do? Can you add more detail?

**Comment by TheInvoker** [comment]
thanks, i think it worked.

**Comment by mahammad-sixberries** [comment]
@ClickerMonkey thanks, could you please update the description as well in `event-more-text`
