### ISSUE TITLE
[Documentation] V-list prop light on by default

### ISSUE THREAD

**Issue by dakkafex** [vuetifyjs/vuetify#9168]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
use the v-list component anywhere with default settings

### Expected Behavior
component rendering without the light theme

### Actual Behavior
light theme automaticly applied even though the documentation states that "light" is false by default

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/lists" target="_blank">https://vuetifyjs.com/en/components/lists</a>

**Comment by MajesticPotatoe** [comment]
both `light` and `dark` theme are false by default. This is because `$vuetify.theme.dark`/`$vuetify.theme.light` controls the overall theme of any app. The `light`/`dark` props are used apply the theme to the component, essentially overriding application theme.

**Comment by dakkafex** [comment]
so the light theme is always on by default?

**Comment by MajesticPotatoe** [comment]
yes, unless you set it to dark in your bootstrap options:
https://vuetifyjs.com/en/customization/theme#light-and-dark
or set it manually within the app via `this.$vuetify.theme.dark = true`

**Comment by dakkafex** [comment]
alright, thanks for clearing it up, i was wondering why i got a white background while i did not set anything for it
