### ISSUE TITLE
[Documentation] Multiple Date Picker Playground Displays Incorrect Selected Number

### ISSUE THREAD

**Issue by raygervais** [vuetifyjs/vuetify#9172]
### Environment

**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
- Enable multiple flag
- Select multiple dates, take notice of the count and year field's being malformed.

### Expected Behavior
When I click on a single date, the count should be `1`. When I select another, the count should be `2`.

### Actual Behavior
Year field increments from `1` to `9` sporadically, occasionally returning back to the appropriate year. Furthermore, the selected count field is adding a `0` at the end of the number,  which makes it no longer accurate.

![Vue Issue](https://user-images.githubusercontent.com/14265337/66006455-b7120580-e47c-11e9-921b-b62c5e53c4bf.PNG)

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/date-pickers#playground" target="_blank">https://vuetifyjs.com/en/components/date-pickers#playground</a>

### Other comments
[Documentation multiple months selection works as expected](https://vuetifyjs.com/en/components/date-pickers#examples)

**Comment by MajesticPotatoe** [comment]
Note: all playgrounds are in the process of being overhauled

**Comment by MajesticPotatoe** [comment]
This example no longer exists.
