### ISSUE TITLE
Feature Request: hint as HTML (or with slot)

### ISSUE THREAD

**Issue by JCKodel** [vuetifyjs/vuetify#918]
I need to inform my user about a huge documentation in how to use a text field (a lucene query documentation). I would use an attached action button besides the textbox, but this is not yet supported (#867), so I was thinking in using the hint and persistent-hint attributes.

The problem is that HTML is not allowed in hints (it renders as text). I'm not sure if there is a work-around to this.

Would be nice if we could use HTML in the hint or if we could use an inner component and assign it to the hint, for instance:

```
<v-text-field label="Something" v-model="something" persistent-hint>
    <div slot="hint">This is my <b>HTML</b> hint.</div>
</v-text-field>
```

That ``<div slot`` would render the ``<div class="input-group__hint">``.

**Comment by nekosaur** [comment]
This is something I've been thinking of as well. Using the :before pseudo element for hints it pretty limiting.
