### ISSUE TITLE
[Bug Report] Nuxt 2.10 not compatible

### ISSUE THREAD

**Issue by kevinmarrec** [vuetifyjs/vuetify#9181]
### Environment
**Nuxt Version:** 2.10.0
**Vuetify Version:** 2.1.0

### Description
This issue is overall here as a notice to let **Nuxt + Vuetify** users aware that **Nuxt 2.10** is not compatible with Vuetify due to a Nuxt core change : https://github.com/nuxt/nuxt.js/pull/6477

### Screenshot
![image](https://user-images.githubusercontent.com/25272043/66045629-69e96e80-e524-11e9-8083-1ff0a8ae498a.png)

### Notice

Nuxt team is working on releasing a fix as soon as possible.

Thank you for your understanding.

---

This issue will be closed whenever the fix will be released around Nuxt.

**Comment by pimlie** [comment]
Quick solution for now is to install `vue-meta@2.3.0-beta.0`

**Comment by praburangki** [comment]
@pimlie hi, I haven't tried the workaround yet but I want to make sure do you have any issues with it?

**Comment by janvennemann** [comment]
BTW, this appears have been resolved with Nuxt 2.10.2. I don't see any issues using @nuxtjs/vuetify@1.9.0 (which uses Vuetify 2.1.9+).

**Comment by kevinmarrec** [comment]
Should have been closed since months, the compatibility has been fixed since `vue-meta`upgrade to `2.3` since **2.10.1** (https://github.com/nuxt/nuxt.js/pull/6529)
