### ISSUE TITLE
[Feature Request] Expose method to call toggleSelectAll in v-data-table

### ISSUE THREAD

**Issue by cfguimaraes** [vuetifyjs/vuetify#9187]
### Problem to solve
Allow applications call toggle select all programmatically, instead of user interaction with a checkbox.

### Proposed solution
I've created a directive that listens for an event in my application and calls toggleSelectAll in componentInstance from v-data-table when that event is fired.
We should have an option to call this method directly in our application

**Comment by cfguimaraes** [comment]
```js
Vue.directive('toggle-select-all', {
  bind: function(el, binding, vNode) {
    vNode.context.$root.$on(binding.value, () => {
      vNode.componentInstance.toggleSelectAll();
    });
  },
  unbind: function(el, binding, vNode) {
    vNode.context.$root.$off(binding.value);
  }
});
```

`bindind.value` is the string with the event I want to listen and trigger to toggleSelectAll from vuetify v-data-table

**Comment by nekosaur** [comment]
You can easily use a ref https://codepen.io/nekosaur/pen/WNvoyGr
