### ISSUE TITLE
[Bug Report] Can't use v-data-table from my own npm package

### ISSUE THREAD

**Issue by raphaelcfernandes** [vuetifyjs/vuetify#9188]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux, Fedora undefined

### Steps to reproduce
Create a new vue project with vuetify (javascript)
install the package: npm install --save sastify
import { HelloWorld } from 'sastify'
Then use the component in the template

### Expected Behavior
V-data-table rendered

### Actual Behavior
"TypeError: Cannot read property 'breakpoint' of undefined"

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-7i1lv" target="_blank">https://codesandbox.io/s/vue-template-7i1lv</a>

### Other comments
It only happens with v-data-table. I tried with other components and it worked fine.

**Comment by nekosaur** [comment]
Not knowing what sastify or the HelloWorld looks like we can only guess at what the issue is.

But from the error message, and your code, it looks like you're not initializing sastify (or vuetify).

**Comment by raphaelcfernandes** [comment]
I pushed it here https://github.com/raphaelcfernandes/sastify.

My HelloWorld.vue only contains a simple data-table:
```
<template>
  <v-container>
    <v-card>
      <v-data-table
        :headers="headers"
        :items="desserts"
        sort-by="project"
        class="elevation-1"
        light
      >
        <template v-slot:top>
          <v-toolbar flat color="white">
            <v-toolbar-title>OSS Licenses</v-toolbar-title>
            <v-spacer></v-spacer>
          </v-toolbar>
        </template>
        <template v-slot:item.action="{ item }">
          <v-icon small class="mr-2" @click="viewLicense(item)">mdi-battery-alert-variant</v-icon>
        </template>
      </v-data-table>
    </v-card>
    <v-layout wrap>
      <v-flex xs12 sm12 lg6 xl6>First resizable column</v-flex>
      <v-flex xs12 sm12 lg6 xl6>Second resizable column</v-flex>
    </v-layout>
  </v-container>
</template>

<script>
export default {
  name: "HelloWorld",
  data: () => ({
    headers: [
      {
        text: "Dessert (100g serving)",
        align: "left",
        sortable: false,
        value: "name"
      },
      { text: "Calories", value: "calories" },
      { text: "Fat (g)", value: "fat" },
      { text: "Carbs (g)", value: "carbs" },
      { text: "Actions", value: "action", sortable: false }
    ],
    desserts: [
      {
        name: "Frozen Yogurt",
        calories: 159,
        fat: 6.0,
        carbs: 24,
        protein: 4.0,
        iron: "1%"
      }
    ]
  })
};
</script>
```
My vuetify.js:
```
import Vue from 'vue';
import Vuetify from 'vuetify/lib';

Vue.use(Vuetify);

export default new Vuetify({
  icons: {
    iconfont: 'mdi',
  },
});

```

Then I export my package as:
```
import HelloWorld from './components/HelloWorld.vue'

export function install(Vue) {
    Vue.component('HelloWorld', HelloWorld)
}
export { HelloWorld }
```

**Comment by nekosaur** [comment]
Doing it like that, your `main.js` file never gets executed when you consume your sastify library, so vuetify is never initialized. You will either need to initialize vuetify from your consuming project, or wrap the initialization in a sastify plugin install function and use that in the consuming project.

Either way, this is not a bug. If you have any more questions you're welcome to your our chat.
