### ISSUE TITLE
[Documentation] v-skeleton-loader VS v-boilerplate confusion

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#9193]
### Environment

**Browsers:** Waterfox 56.2.14
**OS:** Linux x86_64

### Steps to reproduce
In the docs, in the playground, it is named `v-skeleton-loader`. While in the example (boilerplate component example) it is `v-boilerplate`. Are these two different components with different purposes, or it is just a misnomer. Because, in the API explorer, there is only `v-skeleton-loader`.

### Expected Behavior
Showing both in the API if they are meant to be used differently.
Otherwise, renaming `v-boilerplate` to `v-skeleton-loader`.

### Actual Behavior
Mentioned earlier.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/skeleton-loaders#examples" target="_blank">https://vuetifyjs.com/en/components/skeleton-loaders#examples</a>

### Other comments
Codepen using both components
https://codepen.io/ibrahimbeladi/pen/xxKvmLz?editors=1010

**Comment by MajesticPotatoe** [comment]
`The v-skeleton-loader can be used as boilerplate designs`
v-boilerplate is not an actual vuetify component. If you look at the script, it is showing that you can take `v-skeleton-loader` and make it into a boilerplate component (which we are calling `v-boilerplate` for the sake of the example)

<img width="248" alt="12123123123" src="https://user-images.githubusercontent.com/27827979/66075208-162d5400-e529-11e9-977a-8a4e03335761.png">

**Comment by SumNeuron** [comment]
@MajesticPotatoe I would remove 
```js
{
   boilerplate: false,
  elevation: 2
}
```

in my experience, this prevents users from overwriting these props: https://codesandbox.io/s/vboilerplate-doesnt-like-props-isbec


Semirelated, using VBoilerplate in nuxt production results in nothing being shown...
