### ISSUE TITLE
[Bug Report] v-skeleton-loader (& v-boilerplate) custom types not rendered like pre-defined type 

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#9194]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Waterfox 56.2.14
**OS:** Linux x86_64

### Steps to reproduce
Using a custom type (like `button@2`) does not render like its equivalent pre-defined type (`actions`).

### Expected Behavior
The custom type renders like its equivalent pre-defined type.

### Actual Behavior
Rendered differently.

### Reproduction Link
<a href="https://codepen.io/ibrahimbeladi/pen/xxKvmLz?editors=1010" target="_blank">https://codepen.io/ibrahimbeladi/pen/xxKvmLz?editors=1010</a>

### Other comments
Same goes to v-boilerplate (#9193).

**Comment by alvarobrey** [comment]
@ibrahimBeladi the devs may correct me on this, but the `@` syntax always multiplies components vertically. On the other hand, `actions` is a predefined type with buttons displayed horizontally. 

I believe this is working as intended.

**Comment by ibrahimBeladi** [comment]
On the contrary, I believe it is a bug. `actions` should be equivalent to `button@2` and should render the same. After all, `actions` is a pre-defined type that expands to `button@2`. If that's not the case then it is not possible to use two skeleton-loaders next to each other **without** using the grid.

**Comment by Leespiker** [comment]
@ibrahimBeladi The preset types have their own styles and _wrap_ the types they are mapped to. You can easily override types though. See my response to a related issue [here](https://github.com/vuetifyjs/vuetify/issues/10199#issuecomment-596036424).

**Comment by ibrahimBeladi** [comment]
@Leespiker That does not really answer my issue. Overriding is limited. See the update [codepen](https://codepen.io/ibrahimbeladi/pen/xxKvmLz?editors=1000). The predefined types and their presets kind of have some custom css, so they are not a solution for all cases. I want to build custom skeleton loaders without having to write css nor rows and columns.

**Comment by johnleider** [comment]
I've refactored the more often used types to stand on their own, removing quite a bit of custom css from some of the more complex pre-defined types. There are some assumptions made that put content inline, such as having `buttons@2`. Here is an example of some of the type combinations.

![image](https://user-images.githubusercontent.com/9064066/229586584-fde80d27-e5e9-48ff-b655-30333505ecd6.png)

There are surely more improvements that can be made, but this should at least improve the expected behavior of using some types standalone and also make it a bit easier to roll your own.

**Comment by act185947** [comment]
I still find this new API a bit confusing:
![image](https://github.com/user-attachments/assets/3bd1c729-3cec-4648-b2be-52dd11fdf83d)
![image](https://github.com/user-attachments/assets/81b7ae8c-899c-4ed7-b95f-16164b9d1ba4)

![image](https://github.com/user-attachments/assets/ba0fa648-b7ca-4e0e-8c34-567dd0cb1864)
![image](https://github.com/user-attachments/assets/1af03c60-3794-4001-87a1-c2223c53a267)

I feel like these two scenarios should either both produce a single line, or both produce two lines. How else are you supposed to display buttons on the right side of text?
