### ISSUE TITLE
[Documentation] Example Anchors not working for their Children

### ISSUE THREAD

**Issue by hychan48** [vuetifyjs/vuetify#9195]
### Environment

**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
https://vuetifyjs.com/en/components/cards#examples
Clicking "Advanced"

### Expected Behavior
https://vuetifyjs.com/en/components/cards#advanced

### Actual Behavior
https://vuetifyjs.com/en/components/cards#examples

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/cards#examples" target="_blank">https://vuetifyjs.com/en/components/cards#examples</a>

**Comment by MajesticPotatoe** [comment]
We are aware 😉 thank you for posting this reminder though.

**Comment by MajesticPotatoe** [comment]
resolved in 393cc87
