### ISSUE TITLE
[Bug Report] Grow/Shrink/v-spacer not working in new grid layout

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9196]
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 2.0.20
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
See grid.

### Expected Behavior
The toggle with label should be right aligned, as it has shrink prop and there is a v-spacer to the left.

### Actual Behavior
The shrink prop is being ignored.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/rNBXgWQ?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/rNBXgWQ?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
There is no shrink prop. You probably want `class="flex-grow-0"`

**Comment by TheInvoker** [comment]
tried it, but it minimizes the width of the switch, making the label text wrap into 3 lines. It should keep it 1 line.
