### ISSUE TITLE
[Bug Report] v-tabs with grow and vertical prop do not "take up all available [vertical] space"

### ISSUE THREAD

**Issue by jbuhacoff** [vuetifyjs/vuetify#9197]
### Problem to solve
When using v-tabs with vertical prop sometimes the page has a certain area for them to fill. The "grow" prop works nicely on horizontal tabs, but it has not effect on vertical tabs. Also, setting style="width: 100%" on the v-tabs element doesn't work because the generated html includes a div inside that with role="tablist" and styles placed on v-tabs don't apply to that div. As a workaround, I add css to target that inner div:

``` html
<v-tabs vertical class="mytabs">
  <v-tab>one</v-tab>
  <v-tab>two</v-tab>
</v-tabs>
```

``` css
div.mytabs div[role="tablist"] {
  width: 100%;
}
```

### Proposed solution
When used in conjunction with the vertical prop, the grow prop on v-tabs should make the tabs width 100%,  so instead of the workaround we can just write this:

``` html
<v-tabs vertical grow>
  <v-tab>one</v-tab>
  <v-tab>two</v-tab>
</v-tabs>
```

All that would be inside some other element that sets its width or max-width, such as a menu, drawer, sidebar, etc so the 100% would be constrained by that enclosing element.

CodePen examples:

[grow prop doesn't have an effect on vertical tabs](https://codepen.io/jbuhacoff/pen/jOONqxK)

[workaround](https://codepen.io/jbuhacoff/pen/GRRKZBW)

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
