### ISSUE TITLE
[Documentation] Add documentation in pt-BR for getting started 'default instalation' paragraph 

### ISSUE THREAD

**Issue by hugoazevedosoares** [vuetifyjs/vuetify#9199]
### Environment

**Browsers:** Chrome 77.0.3865.75
**OS:** Linux x86_64

### Steps to reproduce
The first paragraph under 'default instalation' in getting started section of the docs does not have a pt-BR translation

### Expected Behavior
A translation in pt-BR should be exhibited.

### Actual Behavior
Only the docs in en are displayed

### Reproduction Link
<a href="https://vuetifyjs.com/pt-BR/getting-started/quick-start" target="_blank">https://vuetifyjs.com/pt-BR/getting-started/quick-start</a>

**Comment by hugoazevedosoares** [comment]
I'm making a PR to solve it

**Comment by MajesticPotatoe** [comment]
To provide translations for the docs, the please contribute through Vuetify's crowdin project. This can be accessed by clicking the `translate` button in the language selector of the docs.

**Comment by hugoazevedosoares** [comment]
did not kwno that, tanks
