### ISSUE TITLE
v-select not selecting proper value on mount

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#92]
If the mounted v-select has a v-model bound, and that model has a value, select not properly selecting that value.

http://codepen.io/johnjleider/pen/dNXeRy

**Comment by jpfong** [comment]
Hello, 

I think the problem is still here. Please take a look at my codePen:

https://codepen.io/jpfong/pen/EWyEjG

**Comment by exilod** [comment]
I can confirm too there is a problem with this. I set the v-model property to a default value and it selects it but i doesn't make it blue. It set it like a placeholder.

**Comment by simzen85** [comment]
I still encounter this in 0.17

**Comment by nekosaur** [comment]
Please createa a new issue using the [issue creator](https://issues.vuetifyjs.com)

**Comment by ais-one** [comment]
@simzen85 @nekosaur , please look here...

https://github.com/vuetifyjs/vuetify/issues/766#issuecomment-308541140

maybe this could be better highlighted in the docs
