### ISSUE TITLE
Using v-text-field with counter does not work in IE

### ISSUE THREAD

**Issue by dholladay** [vuetifyjs/vuetify#920]
### Steps to reproduce
Add a counter to a v-text-field
Recieve "Object doesn't support property or method 'parseInt'" console error

### Versions
Vue@latest
Vuetify v0.13
Win 10, IE11

### What is expected ?
v-text-field with counter to show

### What is actually happening ?
IE does not support [Number.parseInt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt), instead use the [global parseInt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)
It looks like only TextField.js is using Number.parseInt
### Reproduction Link
[https://codepen.io/anon/pen/weEwxW](https://codepen.io/anon/pen/weEwxW)

**Comment by johnleider** [comment]
Thank you for the in-depth report! I will fix this tonight.
