### ISSUE TITLE
[Bug Report] v-for directive does not work when bound to an initially empty array

### ISSUE THREAD

**Issue by nmummau** [vuetifyjs/vuetify#9201]
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
Create an javascript/typescript object (we'll call it `complexObject` that contains an array we'll call `details[]`. The array should be empty to start.
Then in a v-card, bind the v-for directive to the `complexObject.details`.
To start, the v-card is not shown, which is expected because the array it is bound to is empty.
`.push()` a new object to details[], expecting to see a new card appear.
It does not appear.

### Expected Behavior
When a v-card is bound to an array, when pushing a new object to that array I expect a new card to appear.

### Actual Behavior
When a v-card is bound to an array, when pushing a new object to that array a new card does not appear.

### Reproduction Link
<a href="https://codepen.io/nmummau/pen/zYOgVrv" target="_blank">https://codepen.io/nmummau/pen/zYOgVrv</a>

### Other comments
If you start by defining a starting value of `complexObject.details` (instead of it being empty), then it works.

**Comment by KaelWD** [comment]
This is not related to vuetify. 

https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
