### ISSUE TITLE
[Bug Report] v-dialog not properly showing

### ISSUE THREAD

**Issue by Blackcityhenry** [vuetifyjs/vuetify#9203]
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 2.0.12
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
A predefined 'true' v-model assigned to a v-dialog.

### Expected Behavior
A v-dialog should pop on load.

### Actual Behavior
Only overlay is shown. '.v-dialog__content' remains `display:none`.

### Reproduction Link
<a href="https://codepen.io/blackcityhenry/pen/mddbbbe" target="_blank">https://codepen.io/blackcityhenry/pen/mddbbbe</a>

### Other comments
Switching to version 2.0.12. v-dialog works fine.

**Comment by MajesticPotatoe** [comment]
duplicate #9175
