### ISSUE TITLE
[Bug Report] [v-combobox] After migration from 2.0.X to 2.1.0 the v-combobox is not raising anymore events @blur and @focus

### ISSUE THREAD

**Issue by cafedo** [vuetifyjs/vuetify#9204]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Edge 79.0.287.2
**OS:** Windows 10

### Steps to reproduce
In a v-combobox try to handle @blur or @focus events

### Expected Behavior
If I handle @blur or @focus events, I want that the handle method will be executed when the events are raised

### Actual Behavior
The handle method won't be executed when the events @blur or @focus are raised

### Reproduction Link
<a href="https://codepen.io/cafedo/pen/BaBXOJo?&editable=true&editors=101" target="_blank">https://codepen.io/cafedo/pen/BaBXOJo?&editable=true&editors=101</a>

### Other comments
If you use @focus.capture or @blur.capture (aka, the native of Vue), the handle method will be executed. So it seems that is Vuetify that is not raising @focus and @blur.

**Comment by MajesticPotatoe** [comment]
also affects `v-autocomplete` but not `v-select` and `v-text-field`

**Comment by mseele** [comment]
Having the same bug under chrome with `v-autocomplete`. Showstopper for migrating to 2.1.x
