### ISSUE TITLE
[Bug Report] Rules validation triggered with wrong value when switching inputs

### ISSUE THREAD

**Issue by davorbadrov** [vuetifyjs/vuetify#9206]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Fedora undefined

### Steps to reproduce
Just click on the toggle button and look at the console.
It'll say: "validating integer, input is:" "abc", even if the integer field value is empty.

### Expected Behavior
It should only call the validation function with the value from the integer field

### Actual Behavior
It calls the validation function with the value from the string field ("abc")

### Reproduction Link
<a href="https://codepen.io/davorbadrov/pen/yLLBNME" target="_blank">https://codepen.io/davorbadrov/pen/yLLBNME</a>

**Comment by davorbadrov** [comment]
This can be closed, adding unique `key` attributes solves the problem.
I got the hint from `Kaelwd#6373` from Vuetify's Discord app, great community you have there!

**Codepen link with the solution**
https://codepen.io/davorbadrov/pen/MWWgaEW?editors=1011#0

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
