### ISSUE TITLE
[Documentation] in some cases documentation from API explorer <> current documentation

### ISSUE THREAD

**Issue by vanillamasonry** [vuetifyjs/vuetify#9207]
### Environment

**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
Select/search v-row in the search field and hit enter

### Expected Behavior
same documentation as
https://vuetifyjs.com/en/components/grids (v-row)

### Actual Behavior
In component details result all property descriptions are missing.
I didn't check if other data is the same

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/api-explorer" target="_blank">https://vuetifyjs.com/en/components/api-explorer</a>

**Comment by MajesticPotatoe** [comment]
This is resolved for the most part in the future docs next update. List of pending missing descriptions are as follows:

**v-autocomplete, v-combobox, v-file-input, v-overflow-btn, v-select, v-text-field, v-textarea**
- counter-value

**v-bottom-sheet, v-menu**
- open-on-focus

**v-calendar**
- title function

**v-date-picker**
- next-month-aria-label
- next-year-aria-label
- prev-month-aria-label
- prev-year-aria-label

**v-edit-dialog**
- return-value

**v-flex, v-layout - deprecated v1.5 grids**

**v-img**
- options

**v-list-item**
- keydown event

**v-pagination**
- current-page-aria-label
- next-aria-label
- page-aria-label
- previous-aria-label
- wrapper-aria-label

**Comment by johnleider** [comment]
This is resolved as far as I'm aware. This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
