### ISSUE TITLE
[Bug Report] [v-calendar] Calendar is not rendering correctly on Safari if fixed height is not provided

### ISSUE THREAD

**Issue by CodeSkills** [vuetifyjs/vuetify#9208]
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create v-calendar, add some events, and remove fixed height of a root element (for ex. remove "height" from v-sheet". (MONTH view)

### Expected Behavior
v-calendar should render normally with minimum height as its content (Events and so) required. (Same as in Chrome)

### Actual Behavior
Whole month view is rendered over itself and unreadable, unlike in Chrome.

### Reproduction Link
<a href="https://codepen.io/GeorgeZizka/pen/JjjPYzr?&editable=true&editors=101" target="_blank">https://codepen.io/GeorgeZizka/pen/JjjPYzr?&editable=true&editors=101</a>

**Comment by CodeSkills** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/3975293/66116694-74af0c80-e5d3-11e9-8fa6-c5dab9542bac.png)

Safari:
![image](https://user-images.githubusercontent.com/3975293/66116702-78db2a00-e5d3-11e9-8c52-695b7e4bb53e.png)

**Comment by TareqNewazShahriar** [comment]
Interesting thing is if you go to Vuetify calendar component page with safari, you will see those are ok.
https://vuetifyjs.com/en/components/calendars

**Comment by JoeRadman** [comment]
I ended up fixing this with:

.v-calendar-weekly__week {
    height: unset;
}

**Comment by ClickerMonkey** [comment]
Thank you for the information!
