### ISSUE TITLE
[Bug Report] Data table headers replaced with "Sort by" selector on mobile screen

### ISSUE THREAD

**Issue by Tallyrald** [vuetifyjs/vuetify#9209]
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Open Pen, activate development mode in Chrome and turn on mobile view (or open pen on mobile).

As long as the data table has custom item view implemented, headers are replaced with a Sort By selector (where does that come from?) even if sorting is disabled.

### Expected Behavior
Headers are visible.

### Actual Behavior
Headers are replaced with a Sort by selector.

### Reproduction Link
<a href="https://codepen.io/Tallyrald/pen/mddbVPv" target="_blank">https://codepen.io/Tallyrald/pen/mddbVPv</a>

### Other comments
It is also interesting to notice that rows are not displayed as "blocks" below each other (like how the examples do in the API docs), but stay as scrollable rows.

**Comment by TimvdEijnden** [comment]
Sort by seems not to respect the disable-sort. To get the row displayed as "blocks" you should use an object. See this example:

https://jsfiddle.net/1s0xua3f/

**Comment by TimvdEijnden** [comment]
@nekosaur What is the expected behavior in mobile when there are no sortable headers or `disable-sort="true"` ? Should the VSelect still be visible or disabled like it is now.

I guess the expected behavior from the reporter is incorrect, because when using an object properly the header is already shown. It might need no fix. But hiding it might be more elegant.

**Comment by Tallyrald** [comment]
@TimvdEijnden Thanks to your input I realised that there is more granular control over row items than I originally thought so thanks for that!

Staying on topic I would expect the v-data-table not to display any unneeded components if they have no relevance in the given context (like when sorting is disabled), especially on mobile where there is limited space available.
