### ISSUE TITLE
update to v0.13.0 issue

### ISSUE THREAD

**Issue by yellowgocl** [vuetifyjs/vuetify#921]
hi, im using nuxt@1.0.0.alpha.4+backpack+vuetify, when i try to update vuetify version to v0.13.0. my browser console throw the warn:"The client-side rendered virtual DOM tree……" when project run . how do it work? :）

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).

**Comment by yellowgocl** [comment]
ok , so sorry.
