### ISSUE TITLE
[Feature Request] Align v-tabs titles at start or end

### ISSUE THREAD

**Issue by jbuhacoff** [vuetifyjs/vuetify#9211]
### Problem to solve
When using v-tabs we sometimes need the tab titles to be left-aligned (start-aligned). It seems the tab titles are always centered within the tab. This is especially useful when using v-tabs with the vertical prop for navigation, but is also useful for notebook-style left-aligned titles with fixed-tabs and grow props. The "centered" and "right" props on v-tabs are used to align the entire group of tabs to the center or right of the area, instead of the default left alignment, but there isn't a prop for controlling the alignment of text within the tab title. Here is the workaround I use:

``` html
<v-tabs vertical class="my-tabs">
  <v-tab>title</v-tab>
  <v-tab>long title</v-tab>
</v-tabs>
```

``` css
div.my-tabs [role="tab"] {
  justify-content: flex-start;
}
```

[example of workaround](https://codepen.io/jbuhacoff/pen/QWWLNoB)

### Proposed solution
A new v-tabs prop to control alignment of the tab titles to "start", "center" (default), or "end". So instead of the workaround we can just write something like this:

``` html
<v-tabs vertical justify-tab-title="start">
  <v-tab>title</v-tab>
  <v-tab>long title</v-tab>
</v-tabs>
```

The new prop name doesn't have to be "justify-tab-title", it's just for illustration.

**Comment by johnleider** [comment]
https://vuetifyjs.com/en/components/tabs/#align-end
