### ISSUE TITLE
[Bug Report] Tab line slider misaligned with tabs when switching to/from a tab that needs a vertical scroll bar

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9219]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
I see the issue happening in my own code base, but it is too difficult to figure out how to re-produce into an example. The closest I got was in the codepen, but even there the issue does not happen for some reason.

In the code pen, switch to the 2nd last tab (which has a large height).

Issue happens when switching to/from a tab that needs a vertical scroll bar to something that doesn't needs a vertical scroll bar.

### Expected Behavior
The slider line is always aligned with the tab.

### Actual Behavior
When switching tab, it seems to calculate the lengths (to know how far to move the slider line) assuming the vertical scroll bar is going to be the same in the next tab. However when the next tab shows (and now the vertical bar is changed to showing), it does not factor in that extra width and the slider line ends up misaligned.

Here is an image of how it looks.

https://imgur.com/apt12dK

A workaround is to set overflow-y to scroll for the v-dialog. This keeps the scroll width consistent and pretty much fixes the issue.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/gOOYxrE" target="_blank">https://codepen.io/sneaky666/pen/gOOYxrE</a>

**Comment by johnleider** [comment]
This appears to be working normal as of the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
