### ISSUE TITLE
Stepper 'complete' colour doesn't work in Safari

### ISSUE THREAD

**Issue by techntrails** [vuetifyjs/vuetify#922]
### Steps to reproduce

1. Load the Stepper Documentation in Safari
2. Notice that the completed Steps in the second example are still grey

### Versions
0.13 Vuetify in Safari

### What is expected ?
Completed item should have highlighted color, has it does in Chrome

### What is actually happening ?
Shows as grey

### Reproduction Link
https://vuetifyjs.com/components/steppers

**Comment by johnleider** [comment]
What safari version?
