### ISSUE TITLE
[Feature Request] set max-height in v-input and v-text-field

### ISSUE THREAD

**Issue by wongtalawan** [vuetifyjs/vuetify#9222]
### Problem to solve
cant set max-height in v-input and v-text-field it default input max-height: 32px,
It is not flexible to use.

### Proposed solution
add API property or do something to set max-height

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9123 ?

**Comment by wongtalawan** [comment]
yes
