### ISSUE TITLE
[Bug Report] v-autocomplete does not emit blur events

### ISSUE THREAD

**Issue by perezd** [vuetifyjs/vuetify#9223]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
click in and out of the autocomplete field.

### Expected Behavior
blur event to fire (triggering console.log output)

### Actual Behavior
Never fired.

### Reproduction Link
<a href="https://codepen.io/perezd/pen/eYYOrME?editors=1011" target="_blank">https://codepen.io/perezd/pen/eYYOrME?editors=1011</a>

**Comment by MajesticPotatoe** [comment]
duplicate #9204
