### ISSUE TITLE
[Bug Report] Datatable - Sorting the same column multiple times loses the sortBy parameter after the 3rd click 

### ISSUE THREAD

**Issue by mcmahonnate** [vuetifyjs/vuetify#9230]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132, Google Chrome, Safari
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Pick a column header.
2. Click it's header to sort. (Works as expected)
3. Click the same header to reverse your sort. (Works as expected)
4. Click the same header again.  The sort parameter is lost and the table reloads to its initial state.

### Expected Behavior
Each consecutive click on the same column should reverse the sort from the previous click for that column.  

### Actual Behavior
If you are sorting by Calories, the 3rd click will appear to do nothing. If you are sorting by any other column the 3rd click will appear to sort by Calories descending which is the table's initial state.

Click on the column for a 4th time and the column sorts as expected. As will the 5th click. The 6th click again loses the sort parameter.

### Reproduction Link
<a href="https://codepen.io/TMFMaynard/pen/MWWgRRv" target="_blank">https://codepen.io/TMFMaynard/pen/MWWgRRv</a>

### Other comments
Looking at the pagination prop you can see pagination.sortBy lose its value on the 3rd click on that same header.

**Comment by mcmahonnate** [comment]
FWIW I was able to work around this in v1.5.18 using the headers slot and adding my own sort function.  Documented here https://v15.vuetifyjs.com/en/components/data-tables#slot-items-and-headers

```
<template v-slot:headers="props">
    <tr>
        <th v-for="header in props.headers" :key="header.text"
            :class="['column sortable', pagination.descending ? 'desc' : 'asc', header.value === pagination.sortBy ? 'active' : '']"
        @click="changeSort(header.value)">
        <v-icon small>arrow_upward</v-icon>
        {{ header.text }}
        </th>
    </tr>
</template>
```

```
methods: {
    ...
    changeSort (column) {
        if (this.pagination.sortBy === column) {
            this.pagination.descending = !this.pagination.descending
        } else {
            this.pagination.sortBy = column;
            this.pagination.descending = false
        }
    }
    ...
}
```

**Comment by BjornLuG** [comment]
I think that's how it's supposed to work. Sort ascending > sort descending > no sort, and it loops over it.

**Comment by nekosaur** [comment]
@BjornLuG is correct. If you do not want it to reset the sort order and only toggle between asd/desc, use prop `must-sort`
