### ISSUE TITLE
[Feature Request] Add column reordering to v-data-table

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#9234]
### Problem to solve
I've seen numerous requests for this. It would make sense to have it done in one place correctly, instead of having many different/wrong implementations out there trying to achieve it.

### Proposed solution
I'm far from an expert, but a starting point would be here using the 'sortable-table' directive:

Version 1: Works fine but uses a key on the data-table to refresh when the column headers move
https://codepen.io/uglyhobbitfeet/pen/ExxaNGO

Version 2: No key and pretty much works except for when adding new data.
https://codepen.io/uglyhobbitfeet/pen/NWWKVza

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
