### ISSUE TITLE
[Feature Request] Tooltip to have mobile-open-delay

### ISSUE THREAD

**Issue by nmummau** [vuetifyjs/vuetify#9237]
### Problem to solve
I have navigation buttons that move the user forward/backward through a timeline workflow.

On a desktop computer it is helpful to have a hover tooltip on these two foward/backward buttons,  but on a mobile device as soon as the mobile device clicks the button, then the tooltip appears while navigation is occurring, so it seems really sloppy to the user.

[Currently I can add](https://codepen.io/nmummau/pen/XWWWXVg) an `:open-delay="1000"` to the tooltip, so it doesn't often open when clicked on mobile. But that workaround means that the user on the desktop app has to hover it for 1 second to see the tooltip -- I'd like the desktop user to see the tooltip immediately.

### Proposed solution
Add a prop to v-tooltip: `:mobile-open-delay` which would be an object of { mobile-breakpoint: number, open-delay: number }

{400, 1000} would mean when the mobile screen is <=400, the tooltip is not activated until 1000ms later.

**Comment by jacekkarczmarczyk** [comment]
IMHO it should be a userland solution `:open-delay="$vuetify.breakpoint.width <= 400 ? 1000 : 0"`
