### ISSUE TITLE
[Feature Request] [v-data-table] Provide expand-icon-position of expand icon when show-expand is props

### ISSUE THREAD

**Issue by runyasak** [vuetifyjs/vuetify#9239]
### Problem to solve
I always use `v-data-table` to display rows data.
Then, I need to custom `v-data-table` by add extra header at last to provide expand icon on the right side.

### Proposed solution
It should has prop value to set order position of expand icon that would be left or right.

**Comment by nekosaur** [comment]
You can do this by adding a column to your headers array. I don't think this is documented.

https://codepen.io/nekosaur/pen/bGGGgKm?&editable=true&editors=101
