### ISSUE TITLE
v-list-tile currently only works with paths, not named routes.

### ISSUE THREAD

**Issue by aldozumaran** [vuetifyjs/vuetify#924]
https://codepen.io/aldozumaran/pen/owPePo
"UserHome" is a named route,
Submenu item User / Create doesn't work

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by stoked74** [comment]
Named routes work if you pass an object to the href prop.

href: {name: 'projects-add', params: {id: 'add'}}
