### ISSUE TITLE
[Bug Report] v-autocomplete focus or blur event do not trigger

### ISSUE THREAD

**Issue by VincentBlouin** [vuetifyjs/vuetify#9240]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chromium 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
use @focus="event" or @blur="event" for v-autocomplete

### Expected Behavior
should trigger event

### Actual Behavior
does not trigger event

### Reproduction Link
<a href="https://codepen.io/VincentBlouin/pen/GRRRWeb?editors=1111" target="_blank">https://codepen.io/VincentBlouin/pen/GRRRWeb?editors=1111</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #9204
