### ISSUE TITLE
[Feature Request] Add additional useful classes

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9243]
### Problem to solve
Removes the need to create my own

### Proposed solution
Add these

.overflow-y-scroll {
    overflow-y:scroll !important;
}
.text-decoration-none {
    text-decoration:none !important;  
}
.position-relative {
    position:relative !important;
}
.position-absolute {
    position:absolute !important;
}
@media print {
    .media-print-position-absolute {
        position:absolute !important;
    }
}
.d-block-before:before {
    display: block !important;
}

**Comment by johnleider** [comment]
I like the overflow and position ones (I reach for those all the time), not sure about the rest. Thoughts @vuetifyjs/core-contributors @vuetifyjs/core-team ?

**Comment by YipingRuan** [comment]
> I like the overflow and position ones (I reach for those all the time), not sure about the rest. Thoughts @vuetifyjs/core-contributors @vuetifyjs/core-team ?

How will the "print" being used?

**Comment by MajesticPotatoe** [comment]
The position and overflow ones make sense, especially for components that don't have positionable.
would say 1, 3, and 4.

**Comment by TheInvoker** [comment]
for some things I noticed that they need to be altered for print mode. For example if you have a sticky header, then you try to print, the banner ends up on top of every page covering the content. So I needed that class to make it only stick to the very top during print mode only.

**Comment by rwam** [comment]
Maybe it's possible to adapt utility classes from bootstrap: https://getbootstrap.com/docs/4.1/utilities/position/ Would be helpful sometimes.
