### ISSUE TITLE
[Bug Report] v-toolbar :tile="false" is not working

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9247]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
Look at v-toolbar

### Expected Behavior
Rounded corners.

### Actual Behavior
Not rounded corners. The v-sheet class which has border-radius 0 makes it not rounded on the v-toolbar.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/bGGGoGp?&editable=true&editors=101" target="_blank">https://codepen.io/sneaky666/pen/bGGGoGp?&editable=true&editors=101</a>

### Other comments
The documentation says you can put a false value to the prop tile. However even with that it is not rounded.

**Comment by TheInvoker** [comment]
when will this come out?

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 2.1.9 https://codepen.io/jkarczm/pen/abbjrgY
