### ISSUE TITLE
[Bug Report] Cannot create chip in v-combobox inside a v-form on mobile platform

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#9248]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Create a v-form.
Create v-combobox inside v-form.

In mobile browser (I tried Chrome on Android), click in the combobox and type something. Press enter.

### Expected Behavior
On desktop browser, a chip is created.

### Actual Behavior
On the mobile browser, it goes to the next field on the form instead.

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/bGGGoJo" target="_blank">https://codepen.io/pumpknhd/pen/bGGGoJo</a>

**Comment by d00kIe** [comment]
I found a workaround: you can set type="search" on the combobox. The disadvantage is that on Android the icon of "return" button will be a "search" icon.

**Comment by pumpknhd** [comment]
I found another workaround. I added comma and double-space as a delimiter to create chips. It makes sense that Enter may not work on mobile in a form.
