### ISSUE TITLE
[Bug Report] footer-props -> items-per-page-options Does not work

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#9249]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Refer to Codepen link.

I set the items-per-page-options in footer-props to [3, 6, 9]

On the v-data-table I set the items-per-page to 3

### Expected Behavior
drop down should show 3, 6, 9

### Actual Behavior
It shows, 5, 10, 15, All

Also if you use i18n, the dropdown disappears. Please just have a look at the i18n part also.

### Reproduction Link
<a href="https://codepen.io/ais-one/pen/PoooOmO" target="_blank">https://codepen.io/ais-one/pen/PoooOmO</a>

**Comment by MajesticPotatoe** [comment]
you are not binding properly
https://codepen.io/majesticpotatoe-the-bashful/pen/QWWWOqZ

**Comment by ais-one** [comment]
Thank you... I also found out how to make it work with kebab case...

https://codepen.io/ais-one/pen/RwwwjzM


```html
    <v-data-table
      v-bind="abc"
      :headers="headers"
      :items="desserts"
      :items-per-page="3"
      class="elevation-1"
    ></v-data-table>
```

```js
  data () {
    return {
      abc: {
        'footer-props': {
          'items-per-page-options': [3, 6, 9]
        }
      },
```
