### ISSUE TITLE
[Feature Request] Make VAlert Routable

### ISSUE THREAD

**Issue by xblitz** [vuetifyjs/vuetify#9254]
### Problem to solve
Making VAlert routable, so you can click on them to navigate to a route,  just like VCard or VList-Item

### Proposed solution
Im guessing this will involve adding the "Routable" mixin to the component ..not sure about the rest. I will try to make a PR, though someone from the "insides" would probably be able to make this change a lot more easily

**Comment by MajesticPotatoe** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by xblitz** [comment]
Seriously?  so if you are not looking for it, no one gets it?
