### ISSUE TITLE
[Bug Report] "Expected identifier, string or number" JavaScript error in Microsoft Edge browser, even with "transpileDependencies: ['vuetify']" set

### ISSUE THREAD

**Issue by etiennemorin** [vuetifyjs/vuetify#9259]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Just following the getting started doesn't work. https://vuetifyjs.com/en/getting-started/quick-start

vue create edgy
cd edgy
vue add vuetify

Then, add a vue.config.js:

module.exports = {
  transpileDependencies: ['vuetify']
}

### Expected Behavior
The site loads up in Edge without errors.

### Actual Behavior
JavaScript Error:  

Expected identifier, string or number app.js (5953,1)

### Reproduction Link
<a href="https://github.com/etiennemorin/edgy" target="_blank">https://github.com/etiennemorin/edgy</a>

### Other comments
This is a vanilla vue and vuetify project with a vue.config.js for the recommended setting and it doesn't work.

**Comment by DRoet** [comment]
You are using `@vue/cli` without babel, so transpilation doesn't work.

try adding `@vue/cli-plugin-babel` + `babel.config.js` + `.browserlistrc`

(or rerun `@vue/cli create <project>` and make sure to select `babel` in the configuration

**Comment by etiennemorin** [comment]
That worked great.  Thanks.

In package.json:
"@vue/cli-plugin-babel": "^3.11.0"

A new babel.config.js

module.exports = {
  presets: [
    '@vue/app'
  ]
}

And the vue.config.js setting for transpileDependencies:

 transpileDependencies: ['vuetify']
