### ISSUE TITLE
[Bug Report] vue-meta 2.3.0 breaks vuetify theme

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#9263]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Clone project and run it. Observe that the default hello world component has some of its links replaced with buttons.

It's that or you can add vue-meta 2.3.0 to a project with custom theme colors.

### Expected Behavior
The buttons should be green.

### Actual Behavior
The buttons are white.

### Reproduction Link
<a href="https://github.com/MatthewAry/bug-reproduction-vue-meta-breaks-vuetify" target="_blank">https://github.com/MatthewAry/bug-reproduction-vue-meta-breaks-vuetify</a>

### Other comments
Downgrading vue-meta from 2.3.0 to 2.2.2 fixes the problems with the theme. Other observations include that the theme's light and dark settings are not propagating through out.

**Comment by kevinmarrec** [comment]
Invoking @pimlie , hopefully he may have some clues about this issue :)

**Comment by FPurchess** [comment]
Can't confirm that downgrading vue-meta to 2.2.2 fixes the problem:

Tested on Firefox 69.0.1 (64-Bit) / Linux (Ubuntu) and the repository provided by @MatthewAry + this codepen: https://codepen.io/0in1/pen/GRRgmRa

**Comment by DRoet** [comment]
just had a quick look, but I think it might be caused by: https://github.com/nuxt/vue-meta/commit/c344d60

since we are using `root.$options.metaInfo = () => {}` in `initVueMeta`

the removal of 
```js
if (isFunction(data)) {
   data = data.call(component)
}
```

prevents the metaInfo from loading

**Comment by pimlie** [comment]
The docs needs to be updated still, but in `v2.3` i've added (due to all the vuetify issues) better support for adding meta info from 3rd party libs to prevent issues like here. Docs are currently my comments in [this pr](https://github.com/nuxt/vue-meta/pull/452)

**Comment by DRoet** [comment]
@pimlie so something like this? https://github.com/vuetifyjs/vuetify/pull/9268

**Comment by tvld** [comment]
I can confirm that after upgrading to vuetify@2.3.1 today, my theme immediately broke as well (using nuxt). All colors are back to default
