### ISSUE TITLE
[Bug Report] V-select and object Itens

### ISSUE THREAD

**Issue by 1995Everton** [vuetifyjs/vuetify#9264]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
Use multiple property and an array of objects with values

### Expected Behavior
Create item selection with keys and values

### Actual Behavior
Unable to select items, vue reports an internal component error:

"[Vue warn]: Error in v-on handler: 'TypeError: (this.internalValue || []).slice is not a function'

### Reproduction Link
<a href="https://codepen.io/1995everton/pen/OJJPbxy" target="_blank">https://codepen.io/1995everton/pen/OJJPbxy</a>

### Other comments
Sorry, my english is not good.

**Comment by ibrahimBeladi** [comment]
That's because you are using a single object in `select`. Instead, make `select` an array of objects.
`select: [{ state: 'Florida', abbr: 'FL' }]`

**Comment by jacekkarczmarczyk** [comment]
v-model for multiple v-select must be an array
