### ISSUE TITLE
[Bug Report] v-table-data options documentation is misleading

### ISSUE THREAD

**Issue by tmcintire** [vuetifyjs/vuetify#9265]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.5.17
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
1. Create a table following the documentation
2. Add sortDesc and sortBy options using strings instead of an array

### Expected Behavior
The table should render properly without errors

### Actual Behavior
The table does not render, and there are console errors referencing the code trying to call "indexOf" on a string.  According to the documentation, sortBy and sortDesc can both be strings, but it is being treated as an array in the code.  

### Reproduction Link
<a href="https://codepen.io/tmcintire/pen/bGGNgMM" target="_blank">https://codepen.io/tmcintire/pen/bGGNgMM</a>

**Comment by poganytamastsys** [comment]
I can confirm this, sortBy is an array, even if it is a single-sort

**Comment by nekosaur** [comment]
The documentation states that the `sortBy` and `sortDesc` _props_ can be either strings or arrays. But the properties inside the `options` prop object are always arrays.

There is supposed to be a definition example for `options` prop in API but it is missing. See this issue https://github.com/vuetifyjs/vuetify/issues/9048
