### ISSUE TITLE
[Bug Report] Datatable - Sorting the same column multiple times turn the sort-desc parameter from boolean to array after the 4th click

### ISSUE THREAD

**Issue by alaarihan** [vuetifyjs/vuetify#9267]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
1. Pick a column header.
2. Click it's header to sort.  sort-desc = false (Works as expected)
3. Click the same header to reverse your sort. sort-desc = true  (Works as expected)
4. Click the same header again.  sort-desc = undefined  (Works as expected)
5. Click the same header again. sort-desc = [ false ] the type will change to Array!

### Expected Behavior
In the 4th click, the value should be false not [ false ]

### Actual Behavior
The sort-desc value changed to array in the 4th click

### Reproduction Link
<a href="https://codepen.io/alaarihan/pen/yLLyMda?&editable=true&editors=101" target="_blank">https://codepen.io/alaarihan/pen/yLLyMda?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Due to limited bandwidth, moving to v2.3.x.

**Comment by emailnikola** [comment]
This bug still exists. Date: 20/07/2021
"vue": "~2.6.12" & "vuetify": "^2.4.0".
