### ISSUE TITLE
[Bug Report] Vuetify Combobox auto-select-first disregards full word

### ISSUE THREAD

**Issue by tonyOP1985** [vuetifyjs/vuetify#9269]
### Environment
**Vuetify Version:** 2.1.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
- Type 'Gaming' into v-combobox
- hit enter

### Expected Behavior
- populates model array

### Actual Behavior
- does not populate model array

### Reproduction Link
<a href="https://codepen.io/tonyop1985/pen/xxxbrMZ" target="_blank">https://codepen.io/tonyop1985/pen/xxxbrMZ</a>

### Other comments
When using `auto-select-first` prop on `v-combobox` when a full word is selected from the dropdown items list it doesn't populate the resulting model array.

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity. Please keep an eye 

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
