### ISSUE TITLE
[Feature Request] Option to turn off typing query for v-select

### ISSUE THREAD

**Issue by buyeno** [vuetifyjs/vuetify#9271]
### Problem to solve
Having values that are not strings(numbers), not adjusting the bound value until user clicks selection

### Proposed solution
add an option to turn off the typing query but still be able to select the value from the dropdown.

**Comment by KaelWD** [comment]
Not sure I understand what the problem is here, if you don't want to select anything by typing then don't type?

**Comment by buyeno** [comment]
I can't control what a user does. Also if it's adjusting a non-string value
it causes an error when a key is pressed.
