### ISSUE TITLE
[Feature Request] MobileBreakPoint attribute should accept breakpoint names as well as integer pixel value

### ISSUE THREAD

**Issue by shubhranshu** [vuetifyjs/vuetify#9272]
### Problem to solve
**mobileBreakPoint** property in various components e.g. **VNavigationDrawer** can only accept an integer. This is not ideal to have numbers scattered around the app which may or may not be in sync.

### Proposed solution
We already have breakpoints as named string, mobile breakpoint should be able to accept the breakpoint name as a value for this property.

e.g. **mobile-break-point="sm"** and **mobile-break-point="960"** should both work the same way.

**Comment by johnleider** [comment]
resolved by #11480

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
