### ISSUE TITLE
[Documentation] Missing documentation page for Lazy component - 404

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#9277]
### Environment

**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
Just open the link

### Expected Behavior
to view docs for lazy component

### Actual Behavior
shows a 404 page

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/lazy" target="_blank">https://vuetifyjs.com/en/components/lazy</a>

**Comment by ibrahimBeladi** [comment]
Works for me.

**Comment by MajesticPotatoe** [comment]
most likely cache, as it does in fact work. closing.
