### ISSUE TITLE
[Bug Report] DatePicker - Birthday picker year scroll position

### ISSUE THREAD

**Issue by eolant** [vuetifyjs/vuetify#9278]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. Open a birthday picker
2. Scroll years to the bottom
2. Pick a date
3. Open a birthday picker
4. Pick another date in the bottom
...
N. Repeat until you see a year not scrolled to the right position

### Expected Behavior
To be scrolled to selected year all the time

### Actual Behavior
Randomly doesn't scroll to selected year

### Reproduction Link
<a href="https://codepen.io/eolant/pen/GRRgPoQ" target="_blank">https://codepen.io/eolant/pen/GRRgPoQ</a>

### Other comments
Current scroll is happening in the mounted lifecycle method and overall usage of birthday picker using a watcher to set an active screen to YEAR picker seems unreliable and quite random at times, changing delay in Timeout to a bigger number to switch to YEAR selector seems to make it more consistent but as a drawback it introduces fade out animation on the previously visible screen. Would be nice to have a proper birthday picker type without watch-timeout hacks that will work consistently.

**Comment by stephanebiolley** [comment]
Hello there, 

Any update? A customer reported this bug in our application.

Did anyone have a workaround?

**Comment by acabreragnz** [comment]
You can replicate this easily with this versions:

- iOS: iPhone X (2436×1125 px) iOS 16.6 / Safari Version 16.6
- "vuetify": "^2.4.0",

**Comment by acabreragnz** [comment]
Hello @stephanebiolley,

I implemented a simple workaround that scrolls automatically to the most recently selected date, or to the default date if none has been selected previously.

https://codepen.io/Toni-Cabrera/pen/XWoeqMr?editors=1010

**Comment by acabreragnz** [comment]
Well, my workaround does not work for certain devices, for example in iOS and macOS we found issues. Using the two `setInterval` is the wrong thing here.
