### ISSUE TITLE
[Feature Request] CSS color variables in RGB or HUE

### ISSUE THREAD

**Issue by ctwhome** [vuetifyjs/vuetify#9282]
### Problem to solve
Variable colors for theming are based in HEX color: #FFFFFF
It is not possible to use functions like  color : rgba(var(--v-primary-base),0.5); to add opacity to the background color.

### Proposed solution
Change to RBG format: RGB(255, 255, 255) the color themes, so it can be more flexible to manipulate. This could also allow playing with the text color based on the background-color: https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/

RGB or HUE format

**Comment by KaelWD** [comment]
I thought I'd opened this already but apparently not.

**Comment by 185driver** [comment]
The ability to add opacity to the `theme.themes` object in the vuetify plugin would be quite helpful at times, though to my mind, an alternative solution would be to simply add opacity capability using hex (e.g. `#000000de`).

**Comment by ctwhome** [comment]
> The ability to add opacity to the `theme.themes` object in the vuetify plugin would be quite helpful at times, though to my mind, an alternative solution would be to simply add opacity capability using hex (e.g. `#000000de`).

that would be interesting indeed. The idea of this request is to be able to read the color of a text with contrast enough, not about the opacity, please check the link: https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/#article-header-id-5

**Comment by 185driver** [comment]
Apologies. I'll open a new issue. Thanks.

**Comment by stanislavhh** [comment]
Does anyone know if there will be work on this task?

**Comment by PeterDias55** [comment]
I need this feature

**Comment by stanislavhh** [comment]
I`m using a small workaround while this request is opened,

I have created small utils, which transforms hex to rgb, goes for each color in themes and then sets variables to app:

`
export const hexToRgb = (h) => {
  let r = 0
  let g = 0
  let b = 0

  // 3 digits
  if (h.length === 4) {
    r = '0x' + h[1] + h[1]
    g = '0x' + h[2] + h[2]
    b = '0x' + h[3] + h[3]

    // 6 digits
  } else if (h.length === 7) {
    r = '0x' + h[1] + h[2]
    g = '0x' + h[3] + h[4]
    b = '0x' + h[5] + h[6]
  }

  return `${+r}, ${+g}, ${+b}`
}


export const generateRgbVar = (name, color) => {
  const colorRgb = hexToRgb(color)
  if (!colorRgb.includes('NaN')) {
    document.documentElement.style.setProperty(`--v-${name}-rgb`, colorRgb)
  }
}

export const createRgbVarsForThemes = (themes) => {
  forEach(themes, (theme) => {
    forEach(theme, (colors, key) => {
      if (isObject(colors)) {
        forEach(colors, (color, colorKey) => {
          generateRgbVar(`${key}-${colorKey}`, color)
        })
      } else {
        generateRgbVar(key, colors)
      }
    })
  })
}
`

In App.vue we can use this like:
![image](https://user-images.githubusercontent.com/31501873/100540449-1668d280-3246-11eb-85ab-a343143ea623.png)

Now in any styles we can use our rgb vuetify color:
![image](https://user-images.githubusercontent.com/31501873/100540467-34cece00-3246-11eb-9382-b640cab9cfbb.png)

**Comment by johnleider** [comment]
Our suggestion is to use a custom class to set the opacity.

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by williamli** [comment]
I think it can be solved if vuetify can just let us define anything we want in the theme configuration object. If it is not a hex color, then don't create light / dark variations for it, and just pass the string through... then we can just use it however we want.

**Comment by timothymarois** [comment]
Yeah I believe this should be added, you should be able to add HEXA codes in the theme colors, opacity is NOT what this alpha is used for. Its to combine colors and reduce their overall "solidness".  As an example, I added a custom theme color for a deep orange `#E45D25`, that worked, however, if I wanted to lighten up the same color by adding alpha too it, using `#e45d2517` it fails to be rendered in the theme. HEXA should most definitely be allowed in the color codes, it has the same format as HEX.

**Comment by viniciusbarth** [comment]
Any news about this thread?

**Comment by KaelWD** [comment]
Opacity won't happen. Theme variables in v3 are a list of R,G,B.

**Comment by ThomasBerne** [comment]
Here is the script written in typescript and without isObject an forEach homemade.
```typescript
import { Framework as VuetifyFramework } from 'vuetify';

export const hexToRgb = (h) => {
  let r: string | number = 0;
  let g: string | number = 0;
  let b: string | number = 0;

  if (h.length === 4) {
    r = '0x' + h[1] + h[1];
    g = '0x' + h[2] + h[2];
    b = '0x' + h[3] + h[3];
  } else if (h.length === 7) {
    r = '0x' + h[1] + h[2];
    g = '0x' + h[3] + h[4];
    b = '0x' + h[5] + h[6];
  }
  return `${+r}, ${+g}, ${+b}`;
};

export const generateRgbVar = (name, color) => {
  const colorRgb = hexToRgb(color);
  if (!colorRgb.includes('NaN')) {
    document.documentElement.style.setProperty(`--v-${name}-rgb`, colorRgb);
  }
};

export const createRgbVarsForThemes = (vuetify: VuetifyFramework) => {
  Object.entries(vuetify.theme.themes).forEach((theme) => {
    Object.entries(theme[1]).forEach((colors) => {
      const key = colors[0];

      if (typeof colors[1] === 'object') {
        Object.entries(colors[1]).forEach((color) => {
          const colorKey = color[0];
          generateRgbVar(`${key}-${colorKey}`, color[1]);
        });
      } else {
        generateRgbVar(key, colors[1]);
      }
    });
  });
};
```
