### ISSUE TITLE
[Bug Report] Dragging an item from v-menu onto v-dialog closes v-dialog

### ISSUE THREAD

**Issue by alexanderjanke** [vuetifyjs/vuetify#9283]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Open fullcreen v-dialog
Open v-select
Drag and drop item onto dialog

### Expected Behavior
v-select closes
v-dialog remains open

### Actual Behavior
v-select closes
v-dialog closes

### Reproduction Link
<a href="https://codepen.io/alexanderjanke/pen/ExxaGzv" target="_blank">https://codepen.io/alexanderjanke/pen/ExxaGzv</a>

### Other comments
Seems to happen only when using a fullscreen dialog

**Comment by ricardovanlaarhoven** [comment]
Isn't this a bug of the v-dialog?

And a workaround is adding `persistent`  and `no-click-animation` props to the dialog.

**Comment by radiorz** [comment]
i think this is a bug of the v-menu.when i change the v-menu to another,this bug will not happen anymore.
@ricardogobbosouza 
add persistent and no-click-animation props doesnt work,it still happens.

**Comment by radiorz** [comment]
Environment
Vuetify Version: 2.1.1
Vue Version: 2.6.10
Browsers: Chrome 77.0.3865.90
OS: Windows 10

Steps to reproduce
Open v-menu
Open v-dialog
Drag and drop item out of dialog

Expected Behavior
v-dialog remains open dont close v-dialog

Actual Behavior
v-menu closes
v-dialog closes

Other comments
i have add the props ( persistent and no-close-animation ) but the bug still...

**Comment by ricardovanlaarhoven** [comment]
As you say on your commit "don't trigger if mousedown inside target" isn't the solution right?
when you literally drag and drop (perhaps by accident) the dialog is still closed

Like in this animation:
![closing dialog](https://user-images.githubusercontent.com/1246691/124601122-c00ce380-de67-11eb-90fa-cdef7e52f84e.gif)

@alexanderjanke have you already tested this?

**Comment by alexanderjanke** [comment]
> As you say on your commit "don't trigger if mousedown inside target" isn't the solution right?
> when you literally drag and drop (perhaps by accident) the dialog is still closed
> 
> Like in this animation:
> ![closing dialog](https://user-images.githubusercontent.com/1246691/124601122-c00ce380-de67-11eb-90fa-cdef7e52f84e.gif)
> 
> @alexanderjanke have you already tested this?

I haven't. Haven't done anything Vuetify related since I posted the bug I'm afraid so I'm not sure how I can help out with more information.

I'm surprised to see this bug I found by pure accident being such a hassle to fix. Sorry for you guys to deep dive for such an obscure bug

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
