### ISSUE TITLE
[Bug Report] FAB speed-dial not transitioning with click handlers

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#9287]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
* Create a new FAB w/ speed-dial configuration.
* Attach a `click` handler to one or many of the buttons.

### Expected Behavior
The buttons should transition in and out of visibility.

### Actual Behavior
The buttons do not transition in, they simply pop in to visibility.  They do however transition out according to the configuration.

### Reproduction Link
<a href="https://codepen.io/dmcknight26/pen/KKKwLrq" target="_blank">https://codepen.io/dmcknight26/pen/KKKwLrq</a>

### Other comments
Remove the click handler from the first button to view both the in and out transitions as they should be.

**Comment by johnleider** [comment]
fixed as of v2.1.3 https://codepen.io/johnjleider/pen/KKKdZjO
