### ISSUE TITLE
Entry animation for v-stepper NOT removed

### ISSUE THREAD

**Issue by mornir** [vuetifyjs/vuetify#929]
### Versions
Vuetify 0.13.0

### What is expected ?
Entry animation for v-stepper removed, as stated in the changelog under "Things we removed".

### What is actually happening ?
The entry animation is still playing.

### Reproduction Link
https://vuetifyjs.com/components/steppers

### Comment
Or maybe I misunderstood the changelog(?)

**Comment by johnleider** [comment]
My apologies, my method only fixed the issue on refresh, not when navigating to. I've ended up changing the process so it doesn't rely on an arbitrary amount of time (setTimeout).
