### ISSUE TITLE
[Bug Report] app-bar colors SASS variables conflict with cards colors variable

### ISSUE THREAD

**Issue by YannMCX** [vuetifyjs/vuetify#9296]
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
- Create a vue project
- Add vuetify
- Configure webpack sass variables imports in vue.config.js **(is this documented ?)**
- Create a sass or scss file with the map-merge block
- Try to change the color of the "app-bar" key (the app-bar colors doesn't change)
- Try to change the color of the "cards" key (the app-bar colors change)

### Expected Behavior
AppBar should follow "app-bar" key color

### Actual Behavior
AppBar follow "cards" key color

### Reproduction Link
<a href="https://github.com/YannMCX/vuetify-issue" target="_blank">https://github.com/YannMCX/vuetify-issue</a>

### Other comments

There may be other conflicts than this one, I haven't found them yet at this time, Or maybe I misintegrated the merges of the Sass variables....

> The map-merge block
```css
@import "~vuetify/src/styles/styles.sass";

$material-dark: map-merge(
	$material-dark,
	(
		"app-bar": map-get($blue, "darken-3"),
		"cards": map-get($red, "darken-3")
	)
);
```
File location (from reproduction repo) : /src/assets/sass/_variables.scss/

**Comment by johnleider** [comment]
This is resolved in v3

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
