### ISSUE TITLE
[Feature Request] Set Snackbar default duration to 5 seconds

### ISSUE THREAD

**Issue by nimitbhargava** [vuetifyjs/vuetify#9298]
### Problem to solve
Currently default duration is set to 6 seconds, following Material Component Library 5 seconds is used. Source - https://material.io/develop/web/components/snackbars/#javascript-api

### Proposed solution
To update 
packages/vuetify/src/components/VSnackbar/VSnackbar.ts
packages/kitchen/src/pan/Snackbars.vue

with 5000 as default duration

**Comment by nimitbhargava** [comment]
I can pick this up, if it's okay.

**Comment by johnleider** [comment]
I think this can be considered a bug fix for the purpose of spec match, @vuetifyjs/core-team thoughts?

**Comment by KaelWD** [comment]
The spec doesn't say an exact duration, just 4-10 seconds: https://material.io/components/snackbars/#behavior

**Comment by phiter** [comment]
@KaelWD the specs in the link you sent does not have a default time, but the Javascript API in the official docs use a default timeout of five seconds, so I think we should use that too.

Check the link in the issue description.

**Comment by KaelWD** [comment]
material.io/develop/web is documentation for a material design implementation (https://github.com/material-components/material-components-web/), not the specification itself.

**Comment by phiter** [comment]
I don't know, that's under material.io, which is google official docs. I think we should follow the same implementation details as their one to keep a consistency between multiple implementations.
