### ISSUE TITLE
[Bug Report] Incorrect text field size calculation inside expansion panel

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#9299]
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
1. Open expansion panel
2. Focus second field

### Expected Behavior
Correct notch width in border
Correct label positioning in second field

### Actual Behavior
Incorrect notch width in border
Incorrect label positioning in second field

### Reproduction Link
<a href="https://codepen.io/djaler/pen/oNNXywM" target="_blank">https://codepen.io/djaler/pen/oNNXywM</a>

### Other comments
Elements width calculated while they are hidden, so offsetWidth = 0

**Comment by haggys22** [comment]
Related: #9165, #9156, #9225 

I've been working on a PR as well: #9313

**Comment by Djaler** [comment]
@haggys22 I work on this too #9300
