### ISSUE TITLE
[Bug Report] Override headings tag in variables.scss (h1, h2...)

### ISSUE THREAD

**Issue by nlien** [vuetifyjs/vuetify#9306]
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Ubuntu undefined

### Steps to reproduce
* Create a Vue CLI 3 project
* Add vuetify (vue add vuetify)
* Create a folder called `sass` in the `src` directory
* Create a file called `variables.scss` in the `sass` directory
** Paste the following contents into the file:
```
$font-size-root: 18px;
$headings: map-deep-set($headings, 'h1' 'size', 32px);
```
* Start the app (npm run serve)
* Notice how the font-size-root is applied correctly (18px)
* Notice how the h1-tag's font size is not applied correctly (should be 32px)

### Expected Behavior
The h1-tag should have a font-size of 32px according to the variables.scss file

### Actual Behavior
The h1-tag is given the browser's standard font-size, not the size given in the variables.scss file

### Reproduction Link
<a href="https://github.com/nlien/vuetify-heading-issue" target="_blank">https://github.com/nlien/vuetify-heading-issue</a>

### Other comments
*Important* The devDep `vue-cli-plugin-vuetify` must be at version `1.0.0`. It seems that the latest version (1.0.1) has broken some functionality...

**Comment by nlien** [comment]
I realize that the `$headings: map-deep-set($headings, 'h1' 'size', 32px);` will apply to the class `display-4` as per the `~vuetify/src/styles/elements/_typography.sass`:
```
.v-application
  .display-4
    font-size: map-deep-get($headings, 'h1', 'size') !important
    font-weight: map-deep-get($headings, 'h1', 'weight')
    line-height: map-deep-get($headings, 'h1', 'line-height')
    letter-spacing: map-deep-get($headings, 'h1', 'letter-spacing') !important
    font-family: map-deep-get($headings, 'h1', 'font-family') !important
```
Nevertheless, I find this confusing. I expected that the `$headings` definition of `h1` would apply to the corresponding tag, or at least to the same class (`.h1`). The latter is the case for  e.g. `.subtitle-1`:
```
.v-application
  .subtitle-1
    font-size: map-deep-get($headings, 'subtitle-1', 'size') !important
    font-weight: map-deep-get($headings, 'subtitle-1', 'weight')
    letter-spacing: map-deep-get($headings, 'subtitle-1', 'letter-spacing') !important
    line-height: map-deep-get($headings, 'subtitle-1', 'line-height')
```

**Comment by johnleider** [comment]
Update your vue-cli-plugin-vuetify to ^1.0.0, update Vuetify to v2.1.3 and follow the updated guide https://vuetifyjs.com/en/customization/sass-variables

**Comment by nlien** [comment]
I'm sorry, but this issue is about giving styles to the actual h1...6 HTML tags. Ref. #8292. Upgrading the mentioned libs doesn't solve this. I propose labeling this issue with `wontfix` if that's the intention.

Maybe the docs should be clear about when you override the `h1...6` heading variables, you are actually targeting the `display-4` (h1 variable), `display-3` (h2 variable), `display-2` (h3 variable), `display-1` (h4 variable), `headline` (h5 variable) and `title` (h6 variable) classes (which is slightly confusing).

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/66633878-981f2a80-ec57-11e9-8a72-d0b278112d11.png)

**Comment by tommykamkcm** [comment]
Hi @johnleider @nlien I'm not sure but it seems to partially work on my verison:

This image shows my `app.scss`
![image](https://user-images.githubusercontent.com/1722447/67596988-9a779d80-f79c-11e9-8a17-449de5b80668.png)

This image shows the result
![image](https://user-images.githubusercontent.com/1722447/67596893-60a69700-f79c-11e9-8d03-ca84620d5cb1.png)

the 1st line (declared before importing the main.sass) was bundled to the app.css.
I guess we are at a good spot and the next step is probably figure out why the <style> appears. Hope my observations will be useful.

**Comment by tommykamkcm** [comment]
An update on my last comment:
I referred to this example https://github.com/nekosaur/laravel-vuetify and finally got it working.
The key things are:
- ./webpack.mix.js - `the Mix.listen(...)`
- ./resources/sass/app.scss - keep it empty
- ./resources/sass/styles.scss - it's the main file and just put everything e.g. SASS variables, @import  there

**Comment by laurensV** [comment]
@KaelWD What is the reason the styling is not applied anymore to h1,h2 etc? I see that in the old documentation (https://v15.vuetifyjs.com/en/framework/typography) this was indeed the case, now h1-h6 became useless in vuetify. Would be great if I can use the heading tags again for headings..

**Comment by ottz0** [comment]
> @KaelWD What is the reason the styling is not applied anymore to h1,h2 etc? I see that in the old documentation (https://v15.vuetifyjs.com/en/framework/typography) this was indeed the case, now h1-h6 became useless in vuetify. Would be great if I can use the heading tags again for headings..

Are you saying you cant have styling for h1,h2,h3 but to use <h1 class="display-4">?

**Comment by candu** [comment]
I sort of understand why they did this - `<h1>` through `<h6>` are about the _semantic_ organization of the page, while `.display-4`, etc. are about the _visual_ organization.  IMHO having these two diverge is a bit of a usability / design / a11y smell, although sometimes there are good reasons to break the rules.

Wouldn't it make sense to apply these styles to *both* the heading tags *and* the typography classes?  You could put the typography classes after the headings:

```css
h1 {}
/* ... */
h6 {}

.display-4 {}
/* ... */
.title {}
```
This way you'd get consistent default behavior on headings without having to add typography classes everywhere, but you'd still be able to override them (due to precedence) by explicitly using a typography class.
