### ISSUE TITLE
[Bug Report] v-expansion-panels z-index makes v-dialog overlay to be on fron of everything

### ISSUE THREAD

**Issue by taai** [vuetifyjs/vuetify#9308]
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Inside of ```v-expansion-panels » v-expansion-panel``` I have a custom component ```UserView``` and in it I include and open another custom component ```UserForm``` which is using a ```v-dialog```. But when the dialog opens, its overlay is on the front of everything. I found out that the reason of this issue is that the ```v-expansion-panels``` (the container of ```v-expansion-panel```) has CSS ```z-index: 1``` set and it messes up the dialog's content position (no, increasing dialog's ```z-index``` doesn't help).

Have a look on my codepen example!

### Expected Behavior
The ```v-dialog``` should open normally.

### Actual Behavior
The dialog's overlay blocks everything and the dialog's content is behind it.

### Reproduction Link
<a href="https://codepen.io/taai/project/editor/AegwyE" target="_blank">https://codepen.io/taai/project/editor/AegwyE</a>

### Other comments
The cause is ```v-expansion-panels``` with CSS ```z-index: 1``` set.

**Comment by taai** [comment]
![image](https://user-images.githubusercontent.com/90734/66557791-25308980-eb5b-11e9-84a8-fa181a22e596.png)

**Comment by KaelWD** [comment]
The overlay isn't in front of everything, you just didn't put a card in the dialog.
