### ISSUE TITLE
[Documentation] Fix for Vue-cli-3 sass/scss incomplete setup doc

### ISSUE THREAD

**Issue by SuperGerb** [vuetifyjs/vuetify#9309]
### Environment

**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
In the first code block, please add: 

@import '~vuetify/src/styles/styles.sass';

### Expected Behavior
Here's where to put it: 

```
// Any component modifications must be imported
// Variables must come before the import
// while lists must come after
$btn-letter-spacing: 0;
$btn-font-weight: 400;
$list-item-title-font-size: 0.929rem;
$list-item-dense-title-font-size: 0.929rem;
$list-item-dense-title-font-weight: initial;

@import '~vuetify/src/styles/styles.sass';      
@import '~vuetify/src/components/VBtn/_variables.scss';
@import '~vuetify/src/components/VList/_variables.scss';
``` 

### Actual Behavior
Setup doesn't work without it.

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables#vue-cli-3-setup" target="_blank">https://vuetifyjs.com/en/customization/sass-variables#vue-cli-3-setup</a>

**Comment by DRoet** [comment]
Are you using the latest version of `vue-cli-plugin-vuetify`?  (`^1.0.1`)

**Comment by SuperGerb** [comment]
Yes, I am.

On Oct 10, 2019 10:02 AM, Daan Roet <notifications@github.com> wrote:

Are you using the latest version of vue-cli-plugin-vuetify? (^1.0.1)

**Comment by johnleider** [comment]
If you are then importing styles.sass is no longer necessary. Also the documentation has been updated as of today for v2.1.3 release.
