### ISSUE TITLE
[Feature Request] Button min-width

### ISSUE THREAD

**Issue by megaroeny** [vuetifyjs/vuetify#9312]
### Problem to solve
Aligns with latest Material Design specs, and will help prevent very short buttons from appearing

### Proposed solution
Can we update the `min-width` for buttons to `96px` please?

**Comment by johnleider** [comment]
![image](https://user-images.githubusercontent.com/9064066/66607500-f83f9f00-eb79-11e9-9a35-a25edd000810.png)

**Comment by megaroeny** [comment]
Oh!! Wait, there must be a mix up in their docs then. I'm gonna double check if so 😆 We were documenting our design system and we used 96px for a reason. 🤔

I'll follow up. Thanks!

**Comment by megaroeny** [comment]
Okay, maybe we decided that 64px was too short and that's where the number came from. Beyond that, not sure. My bad!
