### ISSUE TITLE
[Bug Report] <v-text-field> with type="number" allows non-numeric characters in Edge

### ISSUE THREAD

**Issue by 1kevgriff** [vuetifyjs/vuetify#9314]
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1) Go to CodePen
2) Type in number, and the number model should update
3) Type in "1,234" and the number model will go blank or ""

### Expected Behavior
<v-text-field> should not allow the input of non-numeric characters if the type="number"

### Actual Behavior
Backing model of the text field holds an empty string

### Reproduction Link
<a href="https://codepen.io/1kevgriff/pen/bGGVWBP" target="_blank">https://codepen.io/1kevgriff/pen/bGGVWBP</a>

### Other comments
I understand this is because of Edge not having proper support for type="number", but was expecting Vuetify to overcome some of the limitations of browser support.

**Comment by 1kevgriff** [comment]
Also, not an issue on Edge Insider Builds that use Chromium.

**Comment by 1kevgriff** [comment]
Workaround: I had to capture the `@keypress` event on and manually reject the input if it was not a number.

**Comment by KaelWD** [comment]
This is the same behaviour as `<input type="number">`, we don't handle it any differently.

See also #3118, #7374
