### ISSUE TITLE
[Bug Report] Persistent full-screen V-Dialog is closing when a snackbar is clicked

### ISSUE THREAD

**Issue by stephannv** [vuetifyjs/vuetify#9318]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Mac OS 10.14

### Steps to reproduce
1) Open fullscreen dialog
2) Show the snackbar
3) Click on snackbar

### Expected Behavior
Keep fullscreen dialog opened

### Actual Behavior
Fullscreen dialog is closing

### Reproduction Link
<a href="https://codepen.io/stephann/pen/NWWGwgp" target="_blank">https://codepen.io/stephann/pen/NWWGwgp</a>

**Comment by KaelWD** [comment]
Duplicate of #8697, #7310
