### ISSUE TITLE
[Documentation] Missing or Unnecesary? "vuetify/src/styles/styles"

### ISSUE THREAD

**Issue by MrJmpl3** [vuetifyjs/vuetify#9322]
### Environment

**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
Look the documentation

### Expected Behavior
Need import "vuetify/src/styles/styles"

### Actual Behavior
Missing import "vuetify/src/styles/styles"

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables" target="_blank">https://vuetifyjs.com/en/customization/sass-variables</a>

### Other comments
In the new version of documentation, i see missing the `@import '~vuetify/src/styles/styles.sass';` , if a typo? or now is unnecesary?

**Comment by DRoet** [comment]
The documentation was updated after releasing `2.1.3` since it is no longer needed
