### ISSUE TITLE
[Documentation] Error when merge the variables

### ISSUE THREAD

**Issue by MrJmpl3** [vuetifyjs/vuetify#9323]
### Environment

**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
Using the example of the docs

### Expected Behavior

Compile without problems

### Actual Behavior

Error, cannot find the variable

### Reproduction Link
<a href="https://vuetifyjs.com/en/customization/sass-variables" target="_blank">https://vuetifyjs.com/en/customization/sass-variables</a>

### Other comments
map-merge tried to get the variable to merge, but don't exists because the import is after of the merge

**Comment by MrJmpl3** [comment]
In variable , I only have variables, nothing of CSS ..

```
@import "~vuetify/src/styles/styles";

$font-size-root: 14px;

$material-light: map-merge(
  $material-light,
  (
    "background": map-get($grey, "lighten-3")
  )
);

@import "~vuetify/src/components/VBtn/variables";

$btn-font-sizes: map-merge(
  $btn-font-sizes,
  (
    "default": 0.85rem
  )
);

$btn-letter-spacing: 0;
```

The others css is import like another styles, because all code in variables.scss prepend and repeat and process in all sass/scss file in your project when compile

**Comment by DRoet** [comment]
make sure you are using the latest version of vuetify (`2.1.3`), the import of `@import "~vuetify/src/styles/styles";` should not be needed anymore

**Comment by MrJmpl3** [comment]
> 
> 
> make sure you are using the latest version of vuetify (`2.1.3`), the import of `@import "~vuetify/src/styles/styles";` should not be needed anymore

Depende if you use the default value of import from the vuetify-plugin , because vuetify plugin inject the `@import "~vuetify/src/styles/styles";` before your styles, the order is

- Your variables (not list)
- @import "~vuetify/src/styles/styles";
- Your variables (list or maps)

https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/f0864903d9d4b474e922a3b8e0aef8ddeb1562be/util/helpers.js#L45
