### ISSUE TITLE
[Bug Report] Simple-table sticky headers with multiple rows placement when dense is activated

### ISSUE THREAD

**Issue by chocolord** [vuetifyjs/vuetify#9325]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
Create a Simple table with multiple rows in the `<thead>`, set `fixed-header`, `height`and `dense` attribute.

### Expected Behavior
Header's row well positioned vertically.

### Actual Behavior
The N+1 header's rows doesn't apply dense vertical positioning when styicky.

### Reproduction Link
<a href="https://codepen.io/chocolord/pen/qBBOJox" target="_blank">https://codepen.io/chocolord/pen/qBBOJox</a>

### Other comments
I've tried a simple fix but it looks too simple.

    /* Simple CSS fix */
    .v-data-table--fixed-header thead tr:nth-child(2) th {
      top: 32px;
    }

**Comment by jacekkarczmarczyk** [comment]
Imho if you're using more complicated markup like row/colspan etc you should take care of styles by yourself, we're not able to provide a valid solution for whatever markup is provided
