### ISSUE TITLE
[Feature Request] About changing default font of Vuetify

### ISSUE THREAD

**Issue by kingdom84521** [vuetifyjs/vuetify#9326]
### Problem to solve
When using chinese in vuetify's tags, the default font: roboto, just can't properly suit to those chinese words, and would automatically change the font into a chinese font called "PMingLiU", which is the chrome browser's default font for chinese words. There are several ways to change default font which was found by some hackers online, but seems like there isn't a official way to change it.

### Proposed solution
I have looked into the css code, and found that there is a "!important" at the place where defined the default font, which was cannot be override. Just looking for a method to override this part of code.

**Comment by melbahja** [comment]
You can add a class to v-app and apply font-family.
https://codepen.io/dev0x0/pen/eYYJgQK

**Comment by kingdom84521** [comment]
already add things like
* {
   font-family: "Font Name"
}

but it didn't actually work because of "!important"

**Comment by kingdom84521** [comment]
OK, i found that the problem is actually came from vuetify's typography.
When using typography classes, the font-family will be lock at roboto and can't change to another.
i know that i can just add a css class to define a customize typography like the comment say above, but i still want to know if there is a way  to change the default font family( and also i am not really sure if the "!important" keyword only works on typography classes. )

**Comment by kingdom84521** [comment]
Just found a way to use sass file to override the "body-font-family" variable, but still wondering if there can be a easier official method.

---

( Using vue-cli 3 )
1. Create a .sass file at your project folder, write down these code into the file:
```sass
@import '~vuetify/src/styles/styles.sass'
// If you need to import the font family from CDN then add a import line

$body-font-family: "YOUR FONT FAMILY NAME"
​
$typoOptions: display-4 display-3 display-2 display-1 headline title subtitle-1 subtitle-2 body-1 body-2 caption overline
​
%font-choice 
  font-family: $body-font-family, sans-serif !important
​
@mixin md-typography
  @each $typoOption in $typoOptions 
    .#{$typoOption} 
      @extend %font-choice
​
.v-application
  @extend %font-choice
  @include md-typography
```

2. Create a file called "vue.config.js" in your project root folder, write down these code into the file:
```javascript
module.exports = {
    sass: {
        prepandData: `@import "your_sass_file_path"`
    }
    // You can use "@" to shorten the path, which represent the "src" folder
}
```

3. Run the project then you will see the difference.

**Comment by johnleider** [comment]
There are instructions on how to do this on the documentation. https://vuetifyjs.com/customization/sass-variables

**Comment by kingdom84521** [comment]
that didn't work at all, already try it before

**Comment by AntonioCollin-s** [comment]
I replace with Google Font "Poppins" like below;
1. Replace font in index.html
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:100,300,400,500,700,900">
```
2. Set font-family in App.vue
```
<style lang="scss" scoped>
  .v-application {
    font-family: 'Poppins', sans-serif;
  }
</style>
```

**Comment by acarlstein** [comment]
@Antonio-Collins regrettably your solution didn't work.

I added to the head tag of the `index.html`:
 
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap">
```

and to the `App.vue`:

```
<style lang="scss" scope>
  @import "./scss/_variables.scss"; 
  .v-application {
    font-family: 'Lato', sans-serif;
  }
  .font-white {
    color: $white;
  }
</style>
```  

Zero luck. :(

**Comment by Antonio-Collins** [comment]
@acarlstein It was working on my side..
Could you please share the template in App.vue?

**Comment by jarvilito1234** [comment]
I have done something that doesn't need so much configuration like installing a ton of package.
if you dont have a global css, just make one then type this 

* {
  font-family: "selawk", sans-serif !important;
}

**Comment by diamond-shine** [comment]
UPDATE Jan/04/2020
https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file
```
// src/sass/variables.scss

// Globals
$body-font-family: 'Work Sans', serif;
```

**Comment by AllanPinheiroDeLima** [comment]
> UPDATE Jan/04/2020
> https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file
> 
> ```
> // src/sass/variables.scss
> 
> // Globals
> $body-font-family: 'Work Sans', serif;
> ```

This do not work.... about 2 hours trying to make it work using the same tutorial

**Comment by Dorianslavov** [comment]
Not the best but I managed to simply overwrite it by placing this on the most **high level parent component** ( in my case `default.vue` since im using `nuxt.js`

```css
.v-application {
	font-family: 'Poppins', 'Open Sans', 'Helvetica Neue', sans-serif !important;
}
```

**Comment by viscas91** [comment]
> UPDATE Jan/04/2020
> https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file
> 
> ```
> // src/sass/variables.scss
> 
> // Globals
> $body-font-family: 'Work Sans', serif;
> ```
Working for me.

For people whom it did not work, please make sure you have **variables.scss** or **variables.sass** in _src/sass_ directory.

_FULL PATH:_ **src/sass/variables.scss**

**Comment by FenoRC** [comment]
> > UPDATE Jan/04/2020
> > https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file
> > ```
> > // src/sass/variables.scss
> > 
> > // Globals
> > $body-font-family: 'Work Sans', serif;
> > ```
> 
> This do not work.... about 2 hours trying to make it work using the same tutorial

This work for me, check your folder name.
If your variables file has extension **.scss** then your folder must be named **scss or styles** (I prefeer styles).
If the folder and file name are correct, then this file is load by vuetify bootstrap loader automatically.

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
