### ISSUE TITLE
[Documentation] Lack of any examples on how to use VTabs with :to or :href

### ISSUE THREAD

**Issue by gkatsanos** [vuetifyjs/vuetify#9327]
### Problem to solve
Looking in the documentation, experimenting, and digging into Stackoverflow old questions (most of which obsolete) , we can't figure out how to use the :to and :href props with VTabs.
There's a codepen from @johnleider https://codepen.io/johnjleider/pen/pLGxJX posted in an old support question but it doesn't seem to be rendering anything.

Our use case is pretty simple : We need a URL linked to each tab so we can programmatically change the active tab by visiting this URL. (also for integration testing but also for UX improvement).
 

### Proposed solution
Add the missing documentation with 2-3 examples on the ideal way to achieve Tab Changing with URL.

**Comment by johnleider** [comment]
I will work on something for this. The difficult part is doing a router example within the documentation. I'll more than likely update that codepen and link it.

**Comment by gkatsanos** [comment]
Thank you John 👍

**Comment by gkatsanos** [comment]
btw, how about skipping router-view (which is problematic) and using `:is` instead? https://jsfiddle.net/chrisvfritz/b2qj69o1/

**Comment by johnleider** [comment]
The problem is that wouldn't accurately showcase what happens for views.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
