### ISSUE TITLE
[Bug Report] Misplaced small icon for items in dense list

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#9331]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
Add a list item with small icon, if you make the list dense, the icon will go higher than it should.

### Expected Behavior
Small icon should be vertically centered just like when it is not dense

### Actual Behavior
The small icon is a little higher than it should.

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/bGGEdry" target="_blank">https://codepen.io/yooneskh/pen/bGGEdry</a>

### Other comments
You guys rock with this great framework <3

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/pull/9395
