### ISSUE TITLE
[Bug Report] Expansion Panel Freezes when dynamic panel is removed

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#9336]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Mac OS 10.14.6

### Steps to reproduce
- Create an expansion panels set with the mandatory prop true
- Create 2 dynamic panels inside of it using a v-for over an array data item
- Remove the first panel by changing the array

### Expected Behavior
The last panel will remain and be opened

### Actual Behavior
The last panel remains but is closed and will not open with click

### Reproduction Link
<a href="https://codepen.io/fontzter/pen/dyyYZxY?&editable=true&editors=101" target="_blank">https://codepen.io/fontzter/pen/dyyYZxY?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
Use the iteration key instead of group so that Vue re-uses the existing expansion-panel.

https://codepen.io/johnjleider/pen/zYExXOK?editors=1010

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
