### ISSUE TITLE
[Documentation] VuetifyJS Documentation Website Not Deployed

### ISSUE THREAD

**Issue by k----n** [vuetifyjs/vuetify#9338]
### Environment

**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Go to https://vuetifyjs.com

### Expected Behavior
Website loads

### Actual Behavior
402 error: PAYMENT_REQUIRED

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

**Comment by monoland** [comment]
have same issues here..

**Comment by jacekkarczmarczyk** [comment]
Seems to be working now
