### ISSUE TITLE
[Bug Report] v-card-subtitle component is missing but is in the docs

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#9345]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use `v-card-subtitle`.

### Expected Behavior
The component is rendered with the appropriate styles.

### Actual Behavior
An error that the component is missing is logged in console.

### Reproduction Link
<a href="https://codepen.io/dEradicated/pen/GRRoaMG" target="_blank">https://codepen.io/dEradicated/pen/GRRoaMG</a>

**Comment by MajesticPotatoe** [comment]
This is resolved in 0799040

**Comment by TheFrogDaddy** [comment]
Was this supposed to be fixed in 2.1.14?

I've just created a bug for this same issue I think? It's still an issue in 2.1.14 for me.
https://github.com/vuetifyjs/vuetify/issues/9384

**Comment by saulortega** [comment]
Not working yet on 2.1.9

**Comment by edrichhans** [comment]
It's fixed on 2.1.9

**Comment by d3radicated** [comment]
@edrichhans Why the thumbs down? The issue was made on version 2.1.3 and is already closed.

**Comment by edrichhans** [comment]
@d3radicated Whoops, my bad, it was a misclick 😅
