### ISSUE TITLE
[Bug Report] Center v-textarea text when rows is set to 1

### ISSUE THREAD

**Issue by ctwhome** [vuetifyjs/vuetify#9346]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
when setting v-textarea rows="1" and "solo" mode, the text gets unaliegned

### Expected Behavior
Align the text to the center of the box

### Actual Behavior
The text is closed to the bottom, giving an odd visual effect.

### Reproduction Link
<a href="https://codepen.io/ctw/pen/YzzwoXJ" target="_blank">https://codepen.io/ctw/pen/YzzwoXJ</a>

**Comment by ctwhome** [comment]
![image](https://user-images.githubusercontent.com/4195550/66732205-3af3c680-ee5b-11e9-8848-0d40b32eef23.png)

**Comment by MysteryPlays** [comment]
Can confirm this on latest Vue (2.6.10) and Vuetify (2.1.10)
