### ISSUE TITLE
[Bug Report] Expansion panel title expands panel even if other components are clicked on top of it

### ISSUE THREAD

**Issue by Tallyrald** [vuetifyjs/vuetify#9347]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Click on either the button or the link in the CodePen example on any of the expansion-panel-titles.

### Expected Behavior
The expansion panel stays in the state it was after the click since another element on top of it was clicked.

### Actual Behavior
The expansion panel toggles it's open/closed state.

### Reproduction Link
<a href="https://codepen.io/Tallyrald/pen/abbNvrQ" target="_blank">https://codepen.io/Tallyrald/pen/abbNvrQ</a>

**Comment by KaelWD** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

`@click.stop`

**Comment by aonghas** [comment]
This doesn't work with Microsoft Edge browser? Any suggestions?
