### ISSUE TITLE
[Feature Request] [v-data-table] Freeze table header below app bar while scrolling

### ISSUE THREAD

**Issue by mrksoftware** [vuetifyjs/vuetify#9348]
### Problem to solve
If we want `fixed-header` prop to work with a data table, we have to set a fixed height on the `v-data-table`.

Without this mode, the data table expand itself as much as needed, but when the user scrolls the page, the headers aren't visible anymore.

By adding this feature, we would have a non-fixed height data table with the headers always visible even if the user scroll

### Proposed solution
I was thinking about something like this: [Angular Data Grid Demo](http://angular-data-grid.github.io/demo/fixed-header/angular-md-grid.html#!?page=1&itemsPerPage=75) found in this [github repo](https://github.com/angular-data-grid/angular-data-grid.github.io/tree/master/src/js/directives/fixedHeader).

![fixed-header-freezed](https://user-images.githubusercontent.com/7292153/66759850-4669e080-eea1-11e9-87cd-e480f39152b6.gif)

**Comment by KaelWD** [comment]
This isn't really possible to do in a generic way with CSS sticky, but is very easy if you just need this specific scenario and don't need to worry about anything like fixed height parents:

```css
.v-table__wrapper {
  overflow: visible
}
.v-data-table__th {
  top: var(--v-layout-top) !important
}
```
