### ISSUE TITLE
[Feature Request] Auto truncate length for v-file-input

### ISSUE THREAD

**Issue by mullerch** [vuetifyjs/vuetify#9349]
### Problem to solve
A fixed length of string is not always appropriate in a responsive context, the available width is generally not the same between mobile phones and a desktop.

### Proposed solution
When setting the *truncate-length* property of the *v-file-input* to "**auto**", the component dynamically adapts the length of the string by truncating it in the middle, respecting the following conditions:

1. The name is truncated only if the width of the text (name + size + others) is larger that the width of the input (when it overflows)
2. If 1. is fulfilled, the name is truncated so that the width of the text equals the width of the input
3. The input stays always one line height

I would even suggest to put this as the default value.

It could eventually be extended to other components if suitable.

I hope this is technically possible.

**Comment by RejownAhmed** [comment]
Why is the truncate-length prop removed in the latest version?
