### ISSUE TITLE
Navigation drawer covers status bar when opened

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#935]
### Steps to reproduce
Create layout with toolbar, status bar and navigation drawer and try to open/close the drawer

### Versions
0.13.1 

### What is expected ?
Status bar should shrink same as toolbar shrinks when the drawer is opened

### What is actually happening ?
Status bar remains full width and is covered by navigtion drawer, while the toolbar width changes

### Reproduction Link
https://codepen.io/anon/pen/rwqvYB

**Comment by johnleider** [comment]
I don't agree that it should respond like this. I do, however, believe we should make some improvements to what a system-bar actually does (you are using the wrong markup in your codepen), but it really should only be used at the very top level and should take priority over all other components.

**Comment by jacekkarczmarczyk** [comment]
Indeed markup was wrong, shame on me... However after changing v-status-bar to v-system-bar and moving it before v-app (just for try) or as a first child of v-app doesn't change anything, it's still hidden behind the navigation drawer, which i think is incorrect behaviour

Correct (I hope) markup
https://codepen.io/anon/pen/QgZzWr

**Comment by johnleider** [comment]
The reason it was not working is because you are missing the **status** or **window** prop on v-system-bar.
