### ISSUE TITLE
[Bug Report] VSelect vertical alignment

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#9352]
### Environment
**Vuetify Version:** 2.1.3
**Last working version:** 2.0.20
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 7

### Steps to reproduce
Visual examination of the example

### Expected Behavior
Select's bottom line is the same vertical position as the text field

### Actual Behavior
Select is above text field

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/yLLOzbd" target="_blank">https://codepen.io/teellcory/pen/yLLOzbd</a>

**Comment by MajesticPotatoe** [comment]
This is because you are applying dense to your `v-select` and not your `v-text-field`

**Comment by Teellcory** [comment]
No wonder. The original code I stripped down had a conditional dense I didn't copy over (and wasn't triggering). I think dense was not working on Select properly until now, so it was fixed with 2.1.x, not broken by it. Thanks!
