### ISSUE TITLE
[Feature Request] data-table itemsPerPage v-select does not allow v-select props for `attach`, `offsetY`, etc.

### ISSUE THREAD

**Issue by johannes-z** [vuetifyjs/vuetify#9355]
### Problem to solve
As of now, the v-select for the "Rows per page:" selection doesn't have any props that are passed to the v-selectcomponent, e.g. `attach` or `offset-y`.

### Proposed solution
As with `footer-props`, add a property called `select-props` that are passed to the v-select

**Comment by nekosaur** [comment]
Please describe a use case or scenario where this would be needed.

**Comment by johannes-z** [comment]
Since this was filed a few days ago, I don't fully remember why this had happened, but I was implementing an application using `VDataTable`. When I opened the `rows per page:` menu, the menu would appear in the middle of the page. I guess this is due to containers having `position: relative` set or something like that... The table was embedded in a CMS, so I couldn't change the CSS of the page layout... 

I had to work around this by recreating the whole footer and using the `external pagination` method. If you still need more information, please let me now, and I'll try to recreate it when I have more time.

I'm not sure if `attach` would solve the problem... I've also noticed, that if the parent container has `overflow: hidden` and `height` set the menu is cut off. An overlay like this would actually always have to rendered into the `body` and correctly positioned instead.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
