### ISSUE TITLE
[Bug Report] Unexpected behaviour of v-tabs

### ISSUE THREAD

**Issue by pranavcbalan** [vuetifyjs/vuetify#9360]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.14.6

### Steps to reproduce
Remove tab from start and add tab at the end while the last tab is active will show multiple tabs content as active.

### Expected Behavior
Should need to work normally.

### Actual Behavior
It should show the last tab instead of showing the previous one as active.

### Reproduction Link
<a href="https://codepen.io/pranavcbalan/pen/WNNwaGa?editors=1010" target="_blank">https://codepen.io/pranavcbalan/pen/WNNwaGa?editors=1010</a>

### Other comments
Temporary workaround : https://codepen.io/pranavcbalan/pen/NWWNObL?editors=1010

**Comment by johnleider** [comment]
fixed in 85f963eea
