### ISSUE TITLE
[Feature Request] v-expansion-panel multiple custom "icons" should turn indiviadually

### ISSUE THREAD

**Issue by carlos-abraao** [vuetifyjs/vuetify#9363]
### Problem to solve
In the 'v-expansion-panels' i'm currently using two icons on the actions slot. Well, one is a 'menu-down' icon and the other one is a custom button. I want the 'menu-down' icon to turn but my button fixed. For now, the property 'disable-icon-rotate' is aplied on the 'v-expansion-panel-header' and by consequence both 'icons' are affected. My goal is to disable the rotation for each icon individually, that way i can choose the icons that i want the animation to happen.

### Proposed solution
the property 'disable-icon-rotate' should work when used inside every element inside the actions slot.

**Comment by KaelWD** [comment]
This reads like a bug report.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
