### ISSUE TITLE
[Feature Request] Add a item-value property to the v-data-table with show-select

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#9365]
### Problem to solve
When using the `v-data-table` component with `show-select` it sets the complete selected row object as the select value. I would like/ only need to return an id only. This can "easily" be solved with `item-value` property as can be seen on other components such as `v-select` 

### Proposed solution
Add the `item-value` property to the `v-data-table` component

**Comment by nekosaur** [comment]
1) Pulling whatever data you need from the selected object is trivial. Can you describe or show a scenario where your feature request would support a new use case?

2) _If_ this would be done, a new prop would not be necessary. `item-key` prop is already used to denote a unique property on the items.

**Comment by SuperDJ** [comment]
@nekosaur I don't need a `item-key` prop just a `item-value` prop such as with the `v-select`. It would make it easier to pull the required data from the selected object as the prop takes care of it. Adding the `item-value` prop would mean it's also more consistent between different components such as `v-select`, `v-combobox`, `v-autocomplete`

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
