### ISSUE TITLE
[Bug Report] NPM Registry version confusion

### ISSUE THREAD

**Issue by icleolion** [vuetifyjs/vuetify#9367]
### Environment
**Vuetify Version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Visit https://www.npmjs.com/package/vuetify?activeTab=versions

### Expected Behavior
Versions listed under Current Tags to be correct, e.g. "latest" tag showing 2.1.4.

### Actual Behavior
"Latest" tag shows 1.5.19. 

### Reproduction Link
<a href="https://www.npmjs.com/package/vuetify?activeTab=versions" target="_blank">https://www.npmjs.com/package/vuetify?activeTab=versions</a>

### Other comments
This is confusing the Version Lens plugin for VS Code.  Also not sure if the "next" and "dev" tags are showing the right version numbers.  Also I'm assuming what's shown on npmjs webpage is under your control.

**Comment by MajesticPotatoe** [comment]
This has been corrected in the repo and may take some time to update on npm's end. Thank you for bringing it to out attention :+1:
